### ISSUE TITLE
Table Panel Gradient Gauge Color incorrect for Percentage Threshold

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#25026]
**What happened**:

When using a Grafana 7 Table Panel Override Cell display mode `Gradient gauge` the background color of the bar is incorrect if `Thresholds mode Percentage` is used.

By contrast, the color of the numeric value label is calculated correctly.

See below, the backgrounds is solid green ❌ 

**What you expected to happen**:
Correct background color in `Percentage` mode, should be a gradient to **red**, the numeric value is correctly in red.

**How to reproduce it (as minimally and precisely as possible)**:
- Go to https://play.grafana.org/dashboard/new , `Add new panel` , use `Table` panel
- Get any values in Query
  - e.g. use existing `prometheus` datasource and scalar query: `0.75` and Format `Table`
  - (or use some demo data source random walk)
- Set suitable Field / Standard options `Min = 0` , `Max = 1`
- Set `Threshold mode` to `Percentage` and use `% 60` as Threshold for Color Red
- Add `Override` for Column `Value` , Set `Cell display mode` to `Gradient gauge`

## Result

![grafik](https://user-images.githubusercontent.com/33002073/82685896-372bec00-9c55-11ea-94f8-b0369ea3bd1a.png)

## Expected Result

![grafik](https://user-images.githubusercontent.com/33002073/82685963-562a7e00-9c55-11ea-95aa-44f03ce8b9b1.png)

The correct display is achived by using `Absolute` Threshold mode and a Threshold of `0.6`:

![grafik](https://user-images.githubusercontent.com/33002073/82686084-87a34980-9c55-11ea-8d7b-1fdd2edbaaa1.png)

**Anything else we need to know?**:

The bug is reproducible with values > 1 too.
Use Query Value `54` , `Min = 0` , `Max = 60` and `Threshold = % 60` for example.
The Value is now 90% of Max, but the color is solid green.

![grafik](https://user-images.githubusercontent.com/33002073/82687401-8c68fd00-9c57-11ea-9c23-847618a7737a.png)

![BoxyP3aGS2](https://user-images.githubusercontent.com/33002073/82687871-3052a880-9c58-11ea-9236-d7cf00efa64d.gif)

You can try it directly in this example:
https://play.grafana.org/d/U_bZIMRMk/table-panel-showcase?viewPanel=2&orgId=1 

**Environment**:
- Grafana version: `Grafana v7.0.0 (aee1438ff2)`
- Data source type & version: Doesn't matter
- OS Grafana is installed on: https://play.grafana.org 
- User OS & Browser: Windows 10 `1909` , Firefox `76.0.1`
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
@Mario-Hofstaetter if I check the link you provided it looks to be solved? Can you confirm?

**Comment by Mario-Hofstaetter** [comment]
@peterholmberg  , I can not confirm, as of `Grafana v7.0.3 (00ee734baf)` on play.grafana.org , percentage threshold is still incorrect, IMHO?

- Open the [link above](https://play.grafana.org/d/U_bZIMRMk/table-panel-showcase?viewPanel=2&orgId=1) 
- Edit Field Standard Options to `Min = 0, Max = 50`
- Set Threshold to `% 50`
- Refresh Query till you have values a little below 50
- Value Text is colored red, bar has no gradient

Value `46` is **92%** of Max 50 , the gradient is not calculated in percent of range:

![3MHR95gvLY](https://user-images.githubusercontent.com/33002073/83901698-72511380-a75b-11ea-9501-d350cf48dbb1.gif)

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/32415
