### ISSUE TITLE
Version 7.0 - export issues and bugs

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#25021]
Found some issues with version 7.0 

The Bar gauge, shows results on top of all other Panels. This also happens when editing the Bar gauge.  I get this bug for Google Chrome  and Edge.

![image](https://user-images.githubusercontent.com/8969659/82675055-8289ce80-9c44-11ea-9c43-64fd8788ebdc.png)

When exporting data. I miss the excel format selection, we used this a lot in version 6x.  In version 7.0 you don't get human data time but only unix time. This makes the export not very useful. The export possibilities where you have to  select the the Join by time, should be set to Join by time as default. Most users want to get all data during eksport. Colleages already complanes about the the eksport posibilityes so have to runback to version 6.

**Comment by aned** [comment]
+1 export to csv is gone in grafana 7.0, is it a bug or it was removed on purpose?

**Comment by torkelo** [comment]
It’s available in inspect option in panel menu.

**Comment by peterholmberg** [comment]
Closing this since bar gauge seems fixed and there's another issue tracking csv export
