### ISSUE TITLE
Give outer join row counts

### ISSUE THREAD

**Issue by yanickrochon** [grafana/grafana#25030]
**What would you like to be added**:

When adding a "Outer Join" tranformation, add a column giving how many rows have been grouped together. Currently, this information is lost, and this is all we need. There doesn't seem to be any other way to accomplish this.

**Why is this needed**:

We have an SQL query returning a bunch or rows, and we are reusing the same query to display various panels. In one of these panels, we need to display a distinct count for a certain column value. For example :

```
+------------------+------------------+
|  order_no        |  status          |
+------------------+------------------+
|  100002          |  completed       |
|  100003          |  paid            |
|  100004          |  invoice         |
|  100005          |  completed       |
|  100006          |  invoice         |
+------------------+------------------+
```

The output should look something like

```
+----------------+---------+
|  status        |  total  |
+----------------+---------+
|  completed     |  2      | 
|  invoice       |  2      |
|  paid          |  1      |
+----------------+---------+
```

Unfortunately, currently, I can group the first column with an "Outer join", but there seem to be no way to get the frequenciy of each values.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
