### ISSUE TITLE
Error "Annotation Query Failed: r[e].split is not a function" when tag == text

### ISSUE THREAD

**Issue by giddyhup** [grafana/grafana#25039]
**What happened**:

I manually created an annotation to mark a maximum value within the last 24 hours in a dashboard:

![image](https://user-images.githubusercontent.com/4533781/82728554-48c2d180-9cf1-11ea-9b89-fd4066d2e6ee.png)

(Query: `SELECT max("value") FROM "temps" WHERE ("tag" = 'balcony') and time>=(now() - 24h) AND time< now();`)

After saving and returning to the panel this error appeared:

![image](https://user-images.githubusercontent.com/4533781/82728571-6d1eae00-9cf1-11ea-9e46-0509bb05f1ae.png)

After further experimentation it seems that the text field may not contain the same information as the tag. After changing the tag to 'maximum' the error went away.

**What you expected to happen**:

No error, working annotation.

**How to reproduce it (as minimally and precisely as possible)**:

See attached image.

**Environment**:
- Grafana version: 7.0
- Data source type & version: Influxdb 1.7.10
- OS Grafana is installed on: Raspberry Pi 3b+
- User OS & Browser: Windows 10, Raspbian, Firefox, Chrome, Chromium
- Grafana plugins: Graph

**Comment by hugohaggmark** [comment]
@giddyhup sorry for late response but I'm reading this https://grafana.com/docs/grafana/latest/datasources/influxdb/#annotations and according to that you shouldn't use the Field Mappings when you are querying just one column. 

I'm going to close this for now but we can always reopen this issue if the needs arises.

All the best
