### ISSUE TITLE
Disabling super-user\admin

### ISSUE THREAD

**Issue by Asgoret** [grafana/grafana#25032]
I tried to run grafana in stateless mode with LDAP authentication and stuck at the moment disabling super-user. I used official grafana docker image 6.6.0 and specify my *.ini file with 'GF_PATHS_CONFIG', but seems it doesn't help because every time when new grafana pod rollouts in logs I see that both config files loaded and super-user is enabled again. Can somebody help to fix it?
```
lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
```

Custom config:
```
[auth.ldap]
allow_sign_up = true
config_file = /etc/grafana/ldap.toml
enabled = true
[metrics]
enabled = true
[secure]
disable_initial_admin_creation = true
```

**Comment by torkelo** [comment]
try 
```ini
[security]
disable_initial_admin_creation = true
```

**Comment by Asgoret** [comment]
@torkelo It's in my config file already. It doesn't work.

**Comment by torkelo** [comment]
You had spelled the section for the option wrong

**Comment by Asgoret** [comment]
@torkelo 
My bad! Sorry! It's working!

**Comment by torkelo** [comment]
No problem, glad you got it working!
