### ISSUE TITLE
compare operator forced to =~ if tag value is /surrounded by slashes/

### ISSUE THREAD

**Issue by TheJonny** [grafana/grafana#25035]
**What happened**: In the query editor, when adding a WHERE filter, selecting a value surrounded by / (in my case a path from `telegraf inputs.cgroup`) sets the operator to =~. = is not selectable any more. As the path is not a regular expression, the query fails.
 
**What you expected to happen**:
the operator stays =, or at least = is selectable from the drop down

**How to reproduce it (as minimally and precisely as possible)**:
create tag values /surrounded by slashes/ in an influxdb datasource, and use the query editor in grafana to add a WHERE clause

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.0
- Data source type & version: influxdb 1.8.0-1
- OS Grafana is installed on: debian buster
- User OS & Browser: archlinux, firefox
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
Currently there is no way to fix this. You have to switch to the raw query editor

**Comment by gabor** [comment]
since grafana 8 beta 1 this is better. you can switch the operator back to `=`

**Comment by gabor** [comment]
for now we will not work more on improving this. guessing whether the user enters a regular expression or a string-value involves some amount of heuristics, and it sometimes goes wrong. with being able to change the operator after the value is entered, the situation should be manageable.
