### ISSUE TITLE
Postgres: SQL injection when using variables in variable queries

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25045]
**What happened**:
Variables are not properly escaped when used inside variable queries

**What you expected to happen**:
Variables should be escaped.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a variable called `var1`, with type "Custom". The values don't matter.
2. Create a second variable called `var2`, with type "Query".
    1. Set Refresh to "on dashboard load" or "on time range change".
    2. Set query to `select '$var1'`
3. Save dashboard (you don't need any panels)
4. Append the following to the dashboard URL: `&var-var1=%27;select%20pg_rotate_logfile()--`

Note in your postgres logs:

    postgres[5442]: [31] 2020-05-24 00:57:24.244 UTC [5442] ERROR:  permission denied for function pg_rotate_logfile

...or a success message if your grafana user has the permissions.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins: None
- Others:

**Comment by phemmer** [comment]
On a side note (but related), I think the way variable quoting is handled is bad. The current implementation is rather confusing and prone to error.
To take a specific example, when you're building a panel with the query builder, and you want to use a variable, the builder puts quotes around the variable.
![image](https://user-images.githubusercontent.com/1826947/82743457-e80bb700-9d39-11ea-8741-c3a28dcbbbd8.png)
Those quotes should be automatically injected when the variable is substituted. It's not even a valid use case where a user might want an unquoted variable, as the special characters inside the variable are still escaped. For example if you use the variable `$foo`, where foo is `ba'r`, then the actual SQL that gets executed is going to be `ba''r`. Thus variables **have** to be used as strings, in which case the quotes should always be there.

Its even more confusing as when the variable is a dashboard variable with multiple values, you're **not** supposed to put quotes around it. The inconsistency leads to confusion and will likely result in people creating dashboards susceptible to SQL injection attacks.

**Comment by aknuds1** [comment]
Thanks for reporting this, will look into it.

**Comment by aknuds1** [comment]
I could confirm it, looks as if the injection issue happens on the front-end, since the back-end receives the SQL fully formed.

**Comment by hugohaggmark** [comment]
@phemmer if you read the [docs](https://grafana.com/docs/grafana/latest/features/datasources/postgres/#database-user-permissions-important) we can't validate that any Postgres query is safe. 

I'll close this issue for now, but we can always reopen it if needed.
