### ISSUE TITLE
Influx db native data source showing correct message in grafana

### ISSUE THREAD

**Issue by saiyam1814** [grafana/grafana#25047]
Steps to reproduce: 
Add influx as a data source 
in the http endpoint write - http://sfsdfsdfsfdsf:8088
![image](https://user-images.githubusercontent.com/8190114/82752680-52296800-9ddd-11ea-8799-1d6c2b5c8aa8.png)
![image](https://user-images.githubusercontent.com/8190114/82752714-9ddc1180-9ddd-11ea-98a8-ba55fc8f2554.png)

shouldn't it fail at the testing phase? when grafana tries to connect with the mentioned address is should fail , right ?

tried in grafana 6 and 7 as well

**Comment by Estrax** [comment]
Checked 6.6.2, 6.7.3 and 7.0 - wasn't able to reproduce this issue. I'm always getting a correct response - 502.

@saiyam1814 Are you sure you don't have anything such as `http://sfsdfsdfsfdsf:8088` in your DNS settings so that your DNS resolves it to a correct address?

**Comment by saiyam1814** [comment]
@Estrax 

Ok one thing I forgot to mention, I was running it as docker container. 
Now to easily reproduce the issue go to any katakoda playground:
to 100% reproduce the issue

```
https://www.katacoda.com/courses/ubuntu/playground
docker run -d -p 3000:3000 --name grafana grafana/grafana:7.0.0
```


![image](https://user-images.githubusercontent.com/8190114/82771186-cce39900-9e58-11ea-8114-3d153cb14dd7.png)

![image](https://user-images.githubusercontent.com/8190114/82771202-d836c480-9e58-11ea-9540-0463a5a62188.png)

**Comment by Estrax** [comment]
Well, that's not a Grafana issue, as it properly throws 502 status codes when the datasource is not available. That's a problem with DNS on Katacoda - you can type literally anything and it's going to "work" - of course until you want to fetch anything from that datasource.

**Comment by saiyam1814** [comment]
Yes you are correct. Thanks for clarifying
