### ISSUE TITLE
Grafana 7 Decimal not work diff unit

### ISSUE THREAD

**Issue by nopjeab** [grafana/grafana#25046]
**What happened**:
After I upgrade grafana 6 to 7 data decimal not work if it diff units
![image](https://user-images.githubusercontent.com/48899439/82746581-ae7b9000-9dbb-11ea-8fc2-f23519ee8099.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7
- Data source type & version: Elasticsearch 6
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by maniel** [comment]
i have this problem too, the decimals in legend and tooltip get crazy if you input anything in legend or axis decimals, works fine if it's on auto

**Comment by dprokop** [comment]
This should be fixed by https://github.com/grafana/grafana/pull/24931
