### ISSUE TITLE
postgres generated sql stops updating after switching visualization

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25043]
**What happened**:
When using the query builder for postgres, if you switch the visualization to anything else, the generated sql preview stops updating, even if you switch back to the original visualization.

**What you expected to happen**:
generated sql should continue to update.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new panel.
2. enable the generated sql preview
3. change the visualization type
4. change the query and notice that the generated sql does not update.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins: None
- Others:

**Comment by zoltanbedi** [comment]
We reworked the sql query editor so this shouldn't be a problem anymore.
