### ISSUE TITLE
v7: Bar Gauge - results display order is not the same as the query returned results order 

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25049]
Upgraded to V7 and bar gauge results are not listed in the order in which they are returned from the query.
Also, on every dashboard refresh, order is changed.

I've noticed that there is a similar bug for table not preserving order that has already been fixed for 7.0.1, but I wasn't sure it's the same thing and this is a critical bug for me.

**Comment by gilkgit** [comment]
Looks like the issue is with the datasource (Azure data explorer) ignoring the order, verifying and opening a bug to them.

**Comment by aknuds1** [comment]
Can we close this issue then @gilkgit?

**Comment by gilkgit** [comment]
Yק

> Can we close this issue then @gilkgit?

Yes. Please close

**Comment by aknuds1** [comment]
That's great :)
