### ISSUE TITLE
dashboards.json has no effect when database sqlite3 is active

### ISSUE THREAD

**Issue by ctradu** [grafana/grafana#2504]
I have the following sections configured in 'grafana.ini' along these lines:
```
[database]
type = sqlite3
name = grafana
user = grafana
password = grafana
path = grafana.db
```
and 
```[dashboards.json]
enabled = true
path = /srv/metrics/grafana/dashboards
```

The path has proper permissions, however no dashboard is saved there:
```
/srv/metrics # ll grafana
total 64
drwxr-xr-x 2 grafana grafana  4096 Aug 13 08:52 dashboards/
-rw-r--r-- 1 grafana grafana 51200 Aug 13 08:52 grafana.db
drwxr-xr-x 3 grafana grafana  4096 Aug 13 08:53 sessions/
/srv/metrics # ls grafana/dashboards
```

In the logs I only get something like this:
```
2015/08/13 08:52:22 [I] Creating json dashboard index for path: /srv/metrics/grafana/dashboards
```
When I push the save button in the grafana webui I see no error, no debug message (even when logging is set on Trace level)

**Comment by torkelo** [comment]
You must have misunderstood this feature, it is only for already generated dashboard files. Saving back to this folder is not support, only indexing json files so they appear in search. Saved dashboards are always saved to grafana db. 


http://docs.grafana.org/installation/configuration/#dashboardsjson

**Comment by ctradu** [comment]
What you say it is correct.
However when you first look for a quick way to migrate dashboards between deployments, db dump is not what I first look at.
Also, if you look at the documentation page you gave above, the word 'dashboard' is used a lot in the part related to dashboard.json; which I read too fast and misunderstood its purpose. I still do not understand its purpose.
You say: "it is only for already generated dashboard files". 
Does this apply to fresh installs ?
If so, who generates them ?

**Comment by torkelo** [comment]
@ctradu some have automated build systems that generate dashboards, others build dashboards with text editor or templates and checks them into version control

**Comment by torkelo** [comment]
@ctradu if you want a way to easily migrate dashboards, maybe the HTTP api can be of service? and tools like this https://github.com/m110/grafcli
