### ISSUE TITLE
Misspelling of level in logfile

### ISSUE THREAD

**Issue by DanielFuchs98** [grafana/grafana#25052]
**What happened**:
In my Log-Files there are a misspelling of the level error:

t=2020-05-21T21:55:30+0000 **lvl=eror** msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=5 name="Swarm Size alert" error="tsdb.HandleRequest() error server_error: server error: 503" changing state to=alerting

**What you expected to happen**:
It should be **lvl=error**, not **lvl=eror**

**Environment**:
- Grafana version: v7.0.0
- Data source type & version: irrelevant
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: -
- Others: -

**Comment by aknuds1** [comment]
I think the spelling might be intentional for technical reasons, although I'm not 100% sure.

**Comment by aknuds1** [comment]
I've received confirmation that the "eror" spelling is on purpose when printing to the console, since we want to align log lines. You might want to consider enabling JSON format logs.
