### ISSUE TITLE
Bar Gauge "Display Name" is not interpolated for table format datasource 

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25051]
In Bar Gauge, the Display Name is not interpolated, at least not for Table info query, so in practice, there's no way to change the Display Name to something meaningful (for a table format input).

Repro:
Choose "Test Database" -> "Random Walk Table" for data source.
Choose "Bar Gauge" and set display name to "${__data.fields[Info]}"

the display name literally changes to "${__data.fields[Info]}" instead of the values behind it

![image](https://user-images.githubusercontent.com/55378597/82758174-a4728500-9ded-11ea-8352-eb78efec6668.png)

**Comment by torkelo** [comment]
This interpolation is not supported yet, to refer to another field you have to use this syntax and index:  ${__cell_4}
