### ISSUE TITLE
LDAP authentication with Active Directory - issue with group membership

### ISSUE THREAD

**Issue by svetomir** [grafana/grafana#2505]
Hi,

I am using Grafana 2.1.1 and trying to setup LDAP authentication with AD.
I have server.group_mappings set as in the screenshot bellow.
![ldap_toml](https://cloud.githubusercontent.com/assets/6276860/9250798/00200230-41d0-11e5-89f7-59b6a429cd9c.JPG)

When I try to login with user that is a member of one of those groups I get unauthorized access.

Logging says: user ... does not belong in any of the specified ldap groups ...
but then again it does (please see picture bellow).
![logs](https://cloud.githubusercontent.com/assets/6276860/9250790/f8feba78-41cf-11e5-9946-c7976bb10cad.JPG)

Did anyone have similar issue or am I doing something wrong?

Thanks a lot

P.S. Password is correct. :)

**Comment by torkelo** [comment]
Does the ldap group specified in ldap config match exactly that which is returned from ldap?

**Comment by svetomir** [comment]
Yes, they match exactly.
I also have the same LDAP settings for confluence and it works.

**Comment by torkelo** [comment]
@svetomir I think they do not match exactly, in ldap.toml you define the group with lowercase CN, OU etc but what is returned from ldap is captial case.

**Comment by wingZero21** [comment]
Hi,

Nice catch I had a similar issue. By adding the servers.group mappings with uppercase CN/DN/OU etc this fixed the issue with the groups mapping correctly.

Cheers

**Comment by ybizeul** [comment]
This is a big source of confusion I found. Is there any plan to implement case insensitive match?
