### ISSUE TITLE
v7 New table panel - dashboard refresh reverts user-chosen sort order

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25053]
**What happened**:
v7 new table panel. The user can choose a sort field/order by clicking the top titles, however a dashboard refresh reverts this sort order to the default. So for example if you have a 5s dashboard refresh this change of sort order is fairly unusable/useless.

**What you expected to happen**:
Table panels prior to v7 the user could choose a sort order and dashboard refreshes (manual or automatic) would not affect that sort order, the table would continue to show data in the users chosen sort order.

**How to reproduce it (as minimally and precisely as possible)**:
Add a v7 table panel with some data (in my case MySQL data source). Change the sort order. Click the dashboard refresh button and see the chosen sort order revert.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu v19.10
- User OS & Browser: Ubuntu v20.04 Firefox v76.0.1
- Grafana plugins: 
- Others:

**Comment by orena1** [comment]
Fixed here:
https://github.com/grafana/grafana/pull/24705
