### ISSUE TITLE
upgrading from 2.1 to 2.1.1

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2506]
I see there is documentation to install but how would you upgrade from 2.1 to 2.1.1 to take advantage of ldap authentication?

**Comment by torkelo** [comment]
2.1.1 is a patch release for 2.1, 2.1 already has ldap

Upgrade depends on how you installed grafana

**Comment by gsaray101** [comment]
Sorry, I meant upgrading from Grafana version: 2.0.2, commit: v2.0.2, build date: 2015-04-22 11:51:50

**Comment by gsaray101** [comment]
This is how installed:
downloaded grafana-2.0.2.linux-x64.tar and untar the file, and manually configured to ini file.

**Comment by torkelo** [comment]
then download the 2.1.1 tar and untar it to the same folder, be sure you did not modify defaults.ini because then your config will be overwritten
