### ISSUE TITLE
Embed grafana with iframe, it is not saved after editing the panel, and cannot be operated after refreshing the page

### ISSUE THREAD

**Issue by LIUBOliubo** [grafana/grafana#25063]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.5.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Please provide more info using the template fields.

**Comment by torkelo** [comment]
closing due to lack of details
