### ISSUE TITLE
Sorting Tables is not persistent in Grafana 7

### ISSUE THREAD

**Issue by Breee** [grafana/grafana#25069]
**What happened**:

We sorted a bunch of Table panels and saved the Dashboard, on reload the panels are unsorted again. This issue was not present pre Grafana 7

**What you expected to happen**:

The sorting is saved in the dashboard JSON.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Table Panel
2. Sort it
3. Save it
4. Reload.

**Environment**:
- Grafana version: docker image `grafana:latest`

**Comment by dprokop** [comment]
Fixed in https://github.com/grafana/grafana/pull/24705
