### ISSUE TITLE
Cannot connect to SQL Named Instance

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#25067]
**What happened**:
When trying to connect to a named instance when using version 7.0 we cannot specify a named instance. When using a backslash (`\`) to seperate the server name from the instance name, it gives us an error. See attached.

**What you expected to happen**: We should we able to connect as in the past to the server. This worked in version 6.7.2

**How to reproduce it (as minimally and precisely as possible)**:
Try to create a connection to a new instance using server\InstanceName. Is seems that you interpret each single slash (back slash) as two slashes.

**Anything else we need to know?**: No

**Environment**:
- Grafana version: 7.0
- Data source type & version: SQL Server
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome

- Grafana plugins:
- Others:

![ServerName](https://user-images.githubusercontent.com/1325158/82801925-bd7b4480-9e86-11ea-8b4b-d4d90c077f3b.png)
![Connection](https://user-images.githubusercontent.com/1325158/82801927-bf450800-9e86-11ea-8331-401dd34e58e1.png)

**Comment by xslugx** [comment]
https://github.com/grafana/grafana/issues/19483

**Comment by Rookeh** [comment]
Seeing exactly the same issue after updating to 7.0.0.

**Comment by marefr** [comment]
Introduced by #23731

**Comment by aknuds1** [comment]
@marefr Assigning it to myself to work on.

**Comment by aknuds1** [comment]
I'm trying to reproduce this now. Sorry for the long wait, but there's been a lot of other work to take care of.

**Comment by aknuds1** [comment]
I have a suggested fix in https://github.com/grafana/grafana/pull/25629.
