### ISSUE TITLE
Table: Add ad-hoc filters support to new table panel

### ISSUE THREAD

**Issue by ktibi** [grafana/grafana#25072]
**What happened**:
Can't use the filter feature in table panel

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/2437140/82812417-3ed8d400-9e93-11ea-8e74-ffa2fb55bb86.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a table with elasticsearch datasource.

**Anything else we need to know?**:
Feature work if I import old dashboards. I can see panel json config : "type": "table-old"

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: elasticsearch
- OS Grafana is installed on: docker ubuntu official image

**Comment by dguendisch** [comment]
I noticed that the new table panel got filtering with 7.1.
I'm wondering whether it is by intent that this only works with e.g. term queries (using elasticsearch):
![image](https://user-images.githubusercontent.com/30311254/88293495-5ef20b80-ccfb-11ea-9006-5c4978d3996b.png)


but not with raw data queries:
![image](https://user-images.githubusercontent.com/30311254/88293803-c6a85680-ccfb-11ea-9453-b0db4da49c3f.png)


Is that by intent/bug/missing-feature?

**Comment by ktibi** [comment]
Raw data is a new panel, maybe need modifications.

**Comment by torkelo** [comment]
That is correct, it currently only works for term queries

**Comment by fsa1803** [comment]
Do you think to add this possibility also to raw data?

**Comment by Yentel** [comment]
Any updates on this?
Also missing the ad-hoc filters on tables using raw data.

**Comment by fsa1803** [comment]
I am using version 7.3.1, this feauture is available.

**Comment by fjlour** [comment]
7.5.2 and the Filter for Value icons do nothing in a Raw Data Table panel.
