### ISSUE TITLE
Ability to define allowable alert tag names and values

### ISSUE THREAD

**Issue by raags** [grafana/grafana#25073]
**What would you like to be added**:
Enhance tags added to alerts in the Alert tab:
1. Ability to specify list of allowed tag names and values. This can be an autocomplete list that the user gets when adding a tag for an alert.
2. Admin page to allow viewing all the tags (Name and Values) added across all alerts.

**Why is this needed**:
Tags allow downstream alert aggregation and routing to work. But these can get inconsistent, due to typos, or someone forgetting to add an important tag. By making allow these to be defined by an administrator, as well as making them easy to use (via auto-complete / drop-down list), reduces errors, and ensure consistency across all alerts.

**Comment by peterholmberg** [comment]
Converting this to a discussion since that's how we want to handle feature requests going forward.
