### ISSUE TITLE
Problems when data set for a query is empty

### ISSUE THREAD

**Issue by lisagustafsson** [grafana/grafana#2507]
When having multiple queries in a graph and one of them returns empty data set, non of the queries are shown, it says "no datapoints" and the warning text is "Cannot read property 'length' of undefined".

If you click the eye to make the empty query hidden, the other data sets are shown but not always correctly:
* if the query generating empty data set is furthest down, the others are shown correctly
* if the query generating empty data set is not furthest down, the aliases are incorrect. The alias that is supposed to be hidden is shown for one of the other data sets.

Info about versions used:
influxdb version 0.9.1-rc1-159-g6402079
Grafana v 2.1.0-pre1

Note: If only some of the values for a data set is empty, I don't have the same problem, then that specific point is just empty.

**Comment by torkelo** [comment]
this is fixed in final version of 2.1 (and 2.1.1)
