### ISSUE TITLE
Legend Table Values Hidden

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#25078]
**What happened**: When using IE11 the table values as part of the legend do not appear. On the other hand they appear when using Chrome. See the attached screenshot.

**What you expected to happen**: The table legend should appear in IE11 as well.

**How to reproduce it (as minimally and precisely as possible)**: Configure the legend to be shown as table (you don't need to shows any values).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.2 (also reproed in 7)
- Data source type & version: Influx
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome & IE11
![TableHidden](https://user-images.githubusercontent.com/1325158/82819466-18be2e80-9ea9-11ea-9398-716f0c3192f1.png)

- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
IE11 is not supported https://github.com/grafana/grafana/issues/15754
