### ISSUE TITLE
Bug: Value mapping not working (with value type "string"?)

### ISSUE THREAD

**Issue by roman-tiukh** [grafana/grafana#25070]
**What happened**:
Value mapping not work. (if value type "string"?)

**What you expected to happen**:
Value mapping work correctly

**How to reproduce it (as minimally and precisely as possible)**:
Graylog + Elasticsearch -> table panel -> configure as in the screenshots -> value mapping and thresholds not working at "level" field

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/38906004/82808074-d3dacd80-9e91-11ea-9608-31d261b51af5.png)
![image](https://user-images.githubusercontent.com/38906004/82808091-e05f2600-9e91-11ea-9522-fb5a021ef1da.png)

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Elasticsearch
- OS Grafana is installed on: debian 8
- User OS & Browser: Ubuntu & Chrome

**Comment by marcusolsson** [comment]
I can verify this bug. 

When I create a value-to-text mapping for a number field, it works as expected. 
When the field type is of string, the value doesn't seem to get saved. If I press Apply and go back, the value field is empty.

**Comment by torkelo** [comment]
This looks fixed, can save string value maps
