### ISSUE TITLE
grafana 7 font size

### ISSUE THREAD

**Issue by ramivis** [grafana/grafana#25089]
The font size in Graphana 7 is very large compared to Graphana 6, is it possible to reduce it? I'm zooming out to be able to hold everything on screen.

**Comment by torkelo** [comment]
Maybe you changed a browser setting? We did not change any font size in v7

**Comment by ramivis** [comment]
> Maybe you changed a browser setting? We did not change any font size in v7

![img01](https://user-images.githubusercontent.com/47853421/82839308-5325cc80-9ea5-11ea-87a1-c0c8300d8e6c.PNG)

**Comment by ramivis** [comment]
![img2](https://user-images.githubusercontent.com/47853421/82842541-5a060c80-9eb0-11ea-928d-f0f95d3959ac.png)

other example
