### ISSUE TITLE
Non-default logging directories cause Grafana to fail to start

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#2508]
In version 2.1.1, the `loadConfiguration` function in https://github.com/grafana/grafana/blob/master/pkg/setting/setting.go initializes logging after reading defaults.ini but *before* reading the specific configuration file. If the default for paths.logs of "data/log" is not writable by the Grafana process, then Grafana will fail to start.

In my company's usage, the entire point of changing paths.logs was to have Grafana not write to the directory where our packaging system installs the Grafana distribution. (The logs directory is under a separate hierarchy.) Since that paths.logs override is read after logging is initialized, Grafana attempts to write to its installation directory (which is owned by a separate user than user under which Grafana is running) and fails. It then errors out and fails to start.

I suggest Grafana just default to console logging until all configuration has been processed.

**Comment by torkelo** [comment]
This is in order to log errors during that happen during configuration loading. 

You can override the default via command line parameter 
"cfg:default.paths.logs=/new/log/path" and
"cfg:default.paths.data=/new/log/path"

**Comment by iwinux** [comment]
This is a little bit counter-intuitive (and not getting mentioned in docs)...

And even if I override log modes via cmd line `cfg:default.log.mode=console`, it still attempts to write to a file named `xorm.log` :(
