### ISSUE TITLE
Legend ordering after CPU upgrade

### ISSUE THREAD

**Issue by chench00** [grafana/grafana#25080]
**What happened**:

Can't sort legend/out of order
**What you expected to happen**:
Legend in order
**How to reproduce it (as minimally and precisely as possible)**:
Upgrade CPU
**Anything else we need to know?**:
I have a graph that displays CPU usage of a host and recently after upgrading it (the CPU), the core count legend is out of order. The number of logical processors went from 10 to 20 and this is the result:

![a745582f876c1c72077dfb49b34a1216aaa1e586_2_690x260](https://user-images.githubusercontent.com/63960113/82820244-d4fb0300-9e6f-11ea-9782-9563b34bae08.png)

I tried dropping the measurement responsible for the CPU graph but nothing changed. 

**Environment**:
- Grafana version: 7
- Data source type & version: Influxdb (latest)
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
what does your query look like and what is the raw response? (Use Query inspector to inspect)=

**Comment by junior466** [comment]
It shows out of order as the graph. 

```
        name:"vsphere_host_cpu"
        tags:Object
        cpu:"0" <---------------------
        columns:Array[2]
        values:Array[361]
        1:Object
        name:"vsphere_host_cpu"
        tags:Object
        cpu:"1" <---------------------
        columns:Array[2]
        values:Array[361]
        2:Object
        name:"vsphere_host_cpu"
        tags:Object
        cpu:"10" <---------------------
        columns:Array[2]
        values:Array[361]
        3:Object
        name:"vsphere_host_cpu"
        tags:Object
        cpu:"11" <---------------------
        columns:Array[2]
        values:Array[361]
```
Does that mean the data is coming in out of order? This is an ESXi host by the way using the vSphere Telegraf plugin.

**Comment by torkelo** [comment]
yes, so a query & influxdb issue
