### ISSUE TITLE
The size of the columns in the new table are not adjusted - v7

### ISSUE THREAD

**Issue by ramivis** [grafana/grafana#25091]
The size of the columns in the new table are not adjusted correctly / automatically, they overflow the panel. I tried to use the fill, fit and exact option but nothing changes either.

If I set a fixed size for the columns, when I open the dashboard on a larger screen the columns get small ..
![img01](https://user-images.githubusercontent.com/47853421/82840334-887fe980-9ea8-11ea-9de3-f83bd1f5e443.png)

**Comment by torkelo** [comment]
You have to adjust the columns manually, and the rest will be divided between the rest that do not have manually set width
