### ISSUE TITLE
Unable to "undo" a text/query in Panel Query field

### ISSUE THREAD

**Issue by Simeda** [grafana/grafana#25093]
**What happened**:
After upgrading to Grafana 7 I am not able to undo text/query (ctrl + z) in Panel Query field.

**What you expected to happen**:
Revert back changes.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Rhel 7.6
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
The fix for this is going to be released in 7.0.1. See https://github.com/grafana/grafana/pull/24797

**Comment by Simeda** [comment]
@zoltanbedi thank you for the quick response.
