### ISSUE TITLE
Broken upgrade from 2.1 to 2.2.0-pre1

### ISSUE THREAD

**Issue by olourkin** [grafana/grafana#2509]
Just tried to update to the new 2.2.0-pre1 build, but Grafana threw the following error and wouldn’t start.  Reverted back to 2.1 and it started up fine, then tried to upgrade again and got the same error.

2015/08/13 10:13:53 [T] Sending anonymous usage stats to stats.grafana..org
2015/08/13 13:27:51 [I] Starting Grafana
2015/08/13 13:27:51 [I] Version: 2.2.0-pre1, Commit: v2.1.1+80-gf784551, Build date: 2015-08-12 23:52:50 -0700 MST
2015/08/13 13:27:51 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/08/13 13:27:51 [I] Database: mysql
2015/08/13 13:27:51 [I] Migrator: Starting DB migration
2015/08/13 13:27:51 [I] Migrator: exec migration id: create temp user table v1-7
2015/08/13 13:27:51 [migrator.go:134 func·001()] [E] Migrator: exec FAILED migration id: create temp user table v1-7, err: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
) ENGINE=InnoDB' at line 13
2015/08/13 13:27:51 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: Error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
) ENGINE=InnoDB' at line 13

**Comment by torkelo** [comment]
thanks for reporting this, fixed now! new builds should appear shortly
