### ISSUE TITLE
Graph line shifted

### ISSUE THREAD

**Issue by mikycol** [grafana/grafana#25098]
**What happened**:

![grafana_bug](https://user-images.githubusercontent.com/15212290/82874894-f4109800-9f36-11ea-8a51-74f3f66d113c.png)

The lines that represent the series on the graph seem to have shifted a few pixels, from the image you can see the starting point of the line, even if there are data prior to that point and above all from the legend it is perfectly clear that there are values that at the moment on the graph are not shown.

Grafana has been installed with the official rpm package

**Environment**:
- Grafana version: 7.0.0-1
- Data source type & version: InfluxDB 1.8.0
- OS Grafana is installed on: Centos 7 x64
- User OS & Browser: Windows 10 Chrome 81.0.4044.138
- Grafana plugins: Graph
- Others:

**Comment by aknuds1** [comment]
Could you include how to reproduce this issue?

**Comment by torkelo** [comment]
you can enable points rendering in display options to see the position of the data points, we have no other reports that the position of the lines are not correct so closing this
