### ISSUE TITLE
CloudWatch Logs: Variables in log group name don't get interpolated

### ISSUE THREAD

**Issue by oliver-schoenherr** [grafana/grafana#25099]
**What happened**:

Using variables in log group names seems to be not possible like:

`/aws/ecs/containerinsights/$cluster/performance`

**What you expected to happen**:

Variables values are  rendered.

**How to reproduce it (as minimally and precisely as possible)**:

Cloudwatch Log Insights Query Syntax with Log Group Name like: `/aws/ecs/containerinsights/$cluster/performance`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Safari
- Grafana plugins:
- Others:

**Comment by jordanpurinton** [comment]
Would very much like to see this feature as well.

**Comment by mikeparker** [comment]
I think this is a missing feature rather than a bug. But yes we'd love to use this too. we use separate log groups for different environments and use a variable to select the environment, so we can't switch log groups based on the dropdown right now.
