### ISSUE TITLE
Advanced variable format for Doublequote don't add double quotes

### ISSUE THREAD

**Issue by nikolaev-rd** [grafana/grafana#25095]
**What happened**:
When using advanced variable format option [Doublequote](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#doublequote) result does not contain double quotes, seem like variable has raw format.
```
${some_var} -> a, b, c, d, e, f, g
${some_var:raw} -> {a,b,c,d,e,f,g}
${some_var:doublequote} -> {a,b,c,d,e,f,g}
```

**What you expected to happen**:
```
${some_var:doublequote} -> "a","b","c","d","e","f","g"
```

**How to reproduce it (as minimally and precisely as possible)**:
Add variable with type _Custom_ and values: `a,b,c,d,e,f,g`. Then create Text panel with content:
```
| Variable formats           | Result                  |
|----------------------------|-------------------------|
| `$ {some_var}`             | ${some_var}             |
| `$ {some_var:raw}`         | ${some_var:raw}         |
| `$ {some_var:doublequote}` | ${some_var:doublequote} |
```

**Environment**:
- Grafana version: v6.7.3 (a04ef6cefc)
- OS Grafana is installed on: Ubuntu 18.04.3 LTS
- User OS & Browser: MacOSX Catalina 10.15.4 & Google Chrome 81.0.4044.138

**Comment by torkelo** [comment]
think this format was added in 7.0: 

semes to work: https://play.grafana.org/d/Gs2NBKkGk/variable-format-doublequote?orgId=1&var-test=value1&var-test=value2&var-test=value3
