### ISSUE TITLE
Grafana heatmap: hide y-axis labels

### ISSUE THREAD

**Issue by wolfig** [grafana/grafana#25097]
This is a copy of my question in Stackoverflow: [Grafana heatmap: hide y-axis labels](https://stackoverflow.com/questions/62002476/grafana-heatmap-hide-y-axis-labels)

As I do not get any answer to this question, I guess it is a missing feature. What I request is the following:

1. For the GRAFANA Heatmap, provide the option to hide/suppress the y-axis tick labels
2. For the GRAFANA Heatmap, provide the topion to hide/suppress the grid lines separating the heatmap "cells".

As can be seen in linked Stackoverflow question and screenshot therein, with great number of heatmap rows the tick labels become useless and the grid lines between heatmap cells are blurring the image the user is focusing on.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
