### ISSUE TITLE
Stat and gauge visulization query output is not reliable

### ISSUE THREAD

**Issue by elancheziyan** [grafana/grafana#25100]
**What happened**:
using a stat panel / gauge  with prometheus datasource using the query
```
sum(count by (name)(openshift_apps_deploymentconfigs_active_rollouts_duration_seconds{exported_namespace=~"application-.*"}))
```
For example the query output is 24, getting 3 is displayed in the panel. after clicking executing query after some activity 24 is displayed

**What you expected to happen**:
i would like to get the actual output instantly.

**How to reproduce it (as minimally and precisely as possible)**:
create a stat or gauge panel and use the query similar to below 
```
sum(count by (name)(openshift_apps_deploymentconfigs_active_rollouts_duration_seconds{exported_namespace=~"application-.*"}))
```
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: windows 7 enterprise, chrome browser
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Is this a problem also with the latest Grafana version (7.0.1)?

**Comment by torkelo** [comment]
Not sure what your asking? Is your problem with prometheus returning inconsistent results? should that be opened in the Prometheus repo?

**Comment by torkelo** [comment]
if you think there is a bug in the visualization please include the raw query results, the panel settings & the visualization result

**Comment by elancheziyan** [comment]
For the first time stat / gauge panel output is 46
After I do something (say query inspector) in the panel then the output is 80
Could you please suggest its a query issue or grafana issue
raw query results:
Object
xhrStatus:"complete"
request:Object
method:"GET"
url:"api/datasources/proxy/226/api/v1/query_range?query=sum(count%20by%20(name)(openshift_apps_deploymentconfigs_active_rollouts_duration_seconds%7Bexported_namespace%3D~%22investments-nexus-.*%22%7D))&start=1590654900&end=1590741300&step=60"
response:Object
status:"success"
data:Object
resultType:"matrix"
result:Array[1]
0:Object
metric:Object
values:Array[79]
0:Array[1590657060,1]
1:Array[1590657120,1]
2:Array[1590664680,1]
3:Array[1590665280,1]
4:Array[1590666480,1]
5:Array[1590666540,1]
6:Array[1590666600,1]
7:Array[1590666660,1]
8:Array[1590666720,1]
9:Array[1590666780,1]
10:Array[1590666840,1]
11:Array[1590666900,1]
12:Array[1590666960,1]
13:Array[1590667020,1]
14:Array[1590671880,1]
15:Array[1590673980,1]
16:Array[1590674040,1]
17:Array[1590674520,1]
18:Array[1590676020,1]
19:Array[1590676080,1]
20:Array[1590676320,1]
21:Array[1590677880,1]
22:Array[1590678360,1]
23:Array[1590680520,1]
24:Array[1590682020,1]
25:Array[1590682080,1]
26:Array[1590682140,1]
27:Array[1590682260,1]
28:Array[1590682320,1]
29:Array[1590682380,1]
30:Array[1590682860,1]
31:Array[1590682920,1]
32:Array[1590683580,1]
33:Array[1590683640,1]
34:Array[1590683700,1]
35:Array[1590683760,1]
36:Array[1590683820,1]
37:Array[1590683880,1]
38:Array[1590683940,1]
39:Array[1590684000,1]
40:Array[1590684060,1]
41:Array[1590684120,1]
42:Array[1590685380,1]
43:Array[1590685440,1]
44:Array[1590685500,1]
45:Array[1590685560,1]
46:Array[1590685620,1]
47:Array[1590685680,1]
48:Array[1590685740,1]
49:Array[1590685800,1]
50:Array[1590685860,1]
51:Array[1590685920,1]
52:Array[1590691020,1]
53:Array[1590691620,1]
54:Array[1590691680,1]
55:Array[1590694260,1]
56:Array[1590694320,1]
57:Array[1590694380,1]
58:Array[1590694440,1]
59:Array[1590694500,1]
60:Array[1590694560,1]
61:Array[1590694620,1]
62:Array[1590694680,1]
63:Array[1590694740,1]
64:Array[1590694800,1]
65:Array[1590695280,1]
66:Array[1590695400,1]
67:Array[1590695460,1]
68:Array[1590695520,1]
69:Array[1590696240,1]
70:Array[1590696300,1]
71:Array[1590696360,1]
72:Array[1590696720,1]
73:Array[1590698040,1]
74:Array[1590698100,1]
75:Array[1590701400,1]
76:Array[1590701520,3]
77:Array[1590706320,1]
78:Array[1590722940,1]

Panel Json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 1310,
  "links": [],
  "panels": [
    {
      "datasource": "openshift-monitoring",
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "colorMode": "value",
        "fieldOptions": {
          "calcs": [
            "sum"
          ],
          "defaults": {
            "mappings": [],
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "color": "green",
                  "value": null
                },
                {
                  "color": "red",
                  "value": 80
                }
              ]
            }
          },
          "overrides": [],
          "values": false
        },
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "horizontal"
      },
      "pluginVersion": "6.6.1",
      "targets": [
        {
          "expr": "sum(count by (name)(openshift_apps_deploymentconfigs_active_rollouts_duration_seconds{exported_namespace=~\"investments-nexus-.*\"}))",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "stat"
    }
  ],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "stat panel issue",
  "uid": "NBKcJbkMk",
  "version": 1
}

**Comment by torkelo** [comment]
Closing this as not sure this is a Grafana issue but a query or config issue, The panel setting is for the gauge to show the sum, so the query must return different results for the value to change
