### ISSUE TITLE
404 status code when updating an existing Dashboard using API

### ISSUE THREAD

**Issue by semblano** [grafana/grafana#2510]
When using Grafana API to update an existing dashboard we are facing a 404 status code, but all api details are correct, the dashboard exists and the 'overwrite' is set to true

curl -H "AUTHORIZATION: Bearer @@@@@@@" -H "Content-Type: application/json" -H "Accept: applic0.6,identity;q=0.3" -X POST http://grafana.mydomain.com:3000/api/dashboards/db -d @dashboard.json
{"message":"Dashboard not found","status":"not-found"}

After manually deleting the dashboard:

curl -H "AUTHORIZATION: Bearer @@@@@" -H "Content-Type: application/json" -H "Accept: application/json" -H "Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3" -X POST http://grafana.mydomain.com:3000/api/dashboards/db -d @dashboard.json
{"slug":"my-dashboard-name","status":"success","version":0}

Acording to docs: http://docs.grafana.org/reference/http_api/
POST /api/dashboards/db
Status Codes:

    200 – Created
    400 – Errors (invalid json, missing or invalid fields, etc)
    401 – Unauthorized
    412 – Precondition failed

If we manually delete the dashboard and try again, it works without a flaw.

**Comment by torkelo** [comment]
when you update an existing dashboard, the dashboard json must contain the id of the dashboard, does your dashboard.json do that?
