### ISSUE TITLE
Make Centring of Bars in Graph Visualisation Optional

### ISSUE THREAD

**Issue by elvijsm** [grafana/grafana#25102]
**What would you like to be added**:
The Pull Request https://github.com/grafana/grafana/pull/19723 made the bars in bar charts centered. There should be an option to revert to the old style, such that a bar's left edge, and not its centre, coincides with the corresponding time.

**Why is this needed**:
The centring of bars is quite confusing to our customers because the values shown in the pop-up change as one moves the pointer across a bar. This gets particularly confusing when the graph additionally includes lines. Here is an example:
<img width="1348" alt="day1" src="https://user-images.githubusercontent.com/39801444/82881156-9c2a5f00-9f3f-11ea-8c46-18b7cc0b8613.png">
<img width="1348" alt="day2" src="https://user-images.githubusercontent.com/39801444/82881178-a3ea0380-9f3f-11ea-94a9-59d489a00669.png">
The line showing the event durations has no GROUP BY clause. The bars have a GROUP BY (1d) and are simply counts of the number of events in each day. The pop-up in the first image displays the value for the duration on April 27, 2020 at 20:37:58 and the counts (3 OK, 0 Errors) for April 27. The pop-up in the second image displays the value for the duration on April 28, 2020 at 04:14:37 and the counts (5 OK, 1 Errors) for April 28.

The confusion stems from different values being shown in the pop-up at different parts of the same bar. This is a direct result of the centring of the bars. Were the bars not centred, they would be visually shifted by 8 hours to the right (spanning from 00:00 to 16:00). This would mean that at the location of the first pop-up there would be a gap.

**Comment by Bubbu17** [comment]
This issue is mentioned already a few times but somhow still not fixed and to my oppinion a major issue even if it looks just like  a kosmetic issue to one.

**Comment by torkelo** [comment]
Feels like a problem with the all series tooltip not the bar centering?

**Comment by elvijsm** [comment]
> Feels like a problem with the all series tooltip not the bar centering?

Maybe it can be interpreted that way but I am not convinced. The date and time shown in the tooltip corresponds to the x-axis value of the highlighted duration in both screenshots. It would be incorrect to show the values (5 OK, 1 Error) with a time of 2020-04-27 20:37 in the first screenshot because the values (5 OK, 1 Error) correspond to April 28.

**Comment by Bubbu17** [comment]
Hello Torkel, I also disagree to your statment. As you can see in my plot the bar goes from the27/5/2020 18:00  to the 28/5/2020 10:00 but the data shown represents only data from the 28th. So it is clearly the centering of the bar which is here incorrect, this bug has been mentioned already a few times in the past.

![image](https://user-images.githubusercontent.com/62136070/83143444-421dcb00-a0f2-11ea-9b56-a0880dfc131f.png)

The data shown: Startdate
![image](https://user-images.githubusercontent.com/62136070/83143510-58c42200-a0f2-11ea-8999-c551f21b0d98.png)
The data shown: Enddate
![image](https://user-images.githubusercontent.com/62136070/83143561-6b3e5b80-a0f2-11ea-954c-ddf342d5f1d9.png)

Looking forward to a bugfix ;-)

**Comment by phastens** [comment]
Hi,
I have the same issue as Bubbu17. I graph energy consumption every day and now i have 3 bars for the weekend (red area). 
As @clamber originally did in pull request https://github.com/grafana/grafana/pull/19723, we should have a button to choose between centered or not. https://github.com/grafana/grafana/pull/19723/commits/dcc1d8d18fc1ecfcd543b990f1195180f8929ebb

![Screenshot_2020-06-16_15-06-31](https://user-images.githubusercontent.com/14843118/84778235-3a0aca00-afd2-11ea-9058-b27195527072.png)

**Comment by leshy** [comment]
Same issue here trying to create monthly bar charts, our time column containing GMT starts of the month

![bar_alignment](https://user-images.githubusercontent.com/681516/86463392-136cc300-bd36-11ea-98bf-72e9ed14d0e5.png)

**Comment by cmtk** [comment]
Here is another example of that confusing behavior, on a smaller scale.
Having the ability to align bars to the left (left edge on the data point) should fix this.

![grafana-offset](https://user-images.githubusercontent.com/12386329/87884771-9e4fed80-c9c5-11ea-8c40-42877fbc0fa7.gif)

**Comment by leeoniya** [comment]
the new Timeseries panel supports left/center/right alignments
