### ISSUE TITLE
Issue with the "Custom all" template variable value

### ISSUE THREAD

**Issue by m-kratochvil** [grafana/grafana#25105]
**What happened**:
I enabled the `Include All option` for a dashboard variable `$X`, to be able to see time series for all $X values at once in a single Graph panel, one time-series for each variable value. `$X` value is part of a long Prometheus label value.<br>
When I leave the `Custom all value` empty, select `All` option in the dashboard selector, Grafana builds comma separated array from the variable values and displays the time-series only for the first array item, which is not what I want.<br>
So I set the `Custom all value` as a regex `.+` which resulted in Grafana correctly displaying the time-series separately for each array item, but I'm unable to make the legend display the actual value of each array item (variable), instead the legend always shows the exact `Custom all` value, which is the regex `.+` The "Legend" definition is set to `$X`.<br>
I see the same behavior for both the `Include All` and `Multi-Value` variables.

**What you expected to happen**:
Since Grafana correctly splits the array and displays separate time-series per array item, I expected the Legend to show the actual value of each of the array items (`$X` values).

**How to reproduce it (as minimally and precisely as possible)**:
- create dashboard template variable that has multiple values
- enable the `Include All option`
- set the `Custom all value` to regex `.+`
- create a Graph panel to show time-series for each of the variable values at once
- define the Legend as the variable (e.g. `$X`)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.5
- Data source type & version: Prometheus 2.15.2
- OS Grafana is installed on: Linux
- User OS & Browser: Win10/Chrome and MAC Catalina/Safari
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Can you please try and reproduce with the latest Grafana version (v7.0.1)? 6.3.5 is quite old.

**Comment by m-kratochvil** [comment]
Tested just now with both v6.7.1 and v7.0.1 and the behavior is the same, no change..

**Comment by torkelo** [comment]
For the legend (series name) you need up define that via legend format patterns. It is not something you can use the variable for
