### ISSUE TITLE
Characters %EF%BB%BF appear in links via Edit Link dialogue 

### ISSUE THREAD

**Issue by matthubb** [grafana/grafana#25107]
**What happened**:
I was composing a data link in the `Edit link` dialogue box and the resultant URL had extraneous characters of `%EF%BB%BF` in it.
```https://server.local/grafana/hosta%EF%BB%BF/foo```

**What you expected to happen**:
I did not expect these characters. I expected:
```https://server.local/grafana/hosta/foo```

**How to reproduce it (as minimally and precisely as possible)**:
This is quite subtle and appears to be related to the autocomplete pop-up.
Start a new dashboard
Add a graph panel
Add a custom dashboard variable, name "host" values "hosta"
Add a link, title "Foo", in the URL input box type the following:
`${host}/foo`
After typing this, the autocomplete popup is still open. Hit the delete key, the popup closes and a character is deleted, put the `o` back again. Click save.

Observe the resulting link contains: `hosta%EF%BB%BF`

**Anything else we need to know?**:
Each time the delete key closes the popup, `%EF%BB%BF` is appended to any earlier highlighted items.

Typing: `$`, `{`, `h`, `o`, `s`, `t`, `}`, `/`, `$`, `BACKSPACE`, `$`, `BACKSPACE`, `$`, `BACKSPACE`, `$`, `BACKSPACE`
Creates a link with: `grafana/hosta%EF%BB%BF%EF%BB%BF%EF%BB%BF%EF%BB%BF/`

**Environment**:
- Grafana version: v7.0.0
- User OS & Browser: Win10 & Chrome

**Comment by M0rdecay** [comment]
I had the same issue - https://github.com/grafana/grafana/issues/23360

Uploading dashboards to JSON, clearing these characters, and loading them back through the HTTP API resolved the issue.

**Comment by wnasich** [comment]
if you have multiple urls with this issue, you could save all of them into a file, and then execute this command :

`sed -i 's/\xEF\xBB\xBF//g' urls.txt`

**Comment by lealceldeiro** [comment]
I'm facing the same issue while creating a Data Link from one dashboard to another,

Why was this closed?

**Comment by hickman-santini** [comment]
This happened to me too and the culprit was a zero-width character in my data link. Word to the wise... check for those!

**Comment by Yuriy-Kuchinskiy** [comment]
> I had the same issue - #23360
> 
> Uploading dashboards to JSON, clearing these characters, and loading them back through the HTTP API resolved the issue.

the above workaround worked for me: export dashboard to json file; find the link-urls and remove all non ascii symbols in (I used intellij); then import json into dashboard and save it... 

not sure from where they come... maybe when I initially inserted the link or when I tried to use query fields in the link, like: ${__data....}

**Comment by pauljones0** [comment]
This is still an issue. An is still relevant. I was able to duplicate this occurring in the grafana playground, using the backspace popup method

![image](https://github.com/grafana/grafana/assets/32859666/fb68c10a-b22c-44a8-b151-b0360fd07ee7)
![image](https://github.com/grafana/grafana/assets/32859666/79fab6fe-15bc-4113-bac6-03d99769660d)

**Comment by knorth55** [comment]
I still have the same issue as @pauljones0 
grafana version: Grafana v10.1.0 (ff85ec33c5)

Is this issue solved in the latest version?

**Comment by nimaforoughi** [comment]
I copied the link URL to Notepad++ and removed bad chars like ZWNBSP and FIXED!!!

**Comment by craftzneko** [comment]
How is this fixed it STILL happens, i have a sql database that shows characters in the table view fine but when trying to access via a variable in a data link adds %EF%BB%BF%EF%BB%BF to the end

**Comment by cboggs** [comment]
Seeing the same behavior, where there's no data import of any sort happening, just building panels through the UI. Given that the UI's own behaviors are inserting breaking characters, it seems like something that should be fixed on the Grafana side rather than forcing manual edits to 'correct' what is generated by very basic usage of the UI. :-)
