### ISSUE TITLE
DataLinks: ${__dashboard} variable does not interpolate correctly after query refresh 

### ISSUE THREAD

**Issue by matthubb** [grafana/grafana#25103]
**What happened**:
Created a data link as:
```d/${__dashboard}/${__dashboard.name}?var-host=${__value.text}```
The link renders as:
```https://hostname/grafana/d/$%7B__dashboard%7D/$%7B__dashboard.name%7D?var-host=host2```

**What you expected to happen**:
The dashboard variables should be expanded in the rendered link to produce a URL similar to:
```https://hostname/grafana/d/AHwBKXnZk/interface-errors?var-host=host2```

**How to reproduce it (as minimally and precisely as possible)**:
Display some data in a table panel.
Add an override with a data-link containing `${__dashboard}`

**Anything else we need to know?**:
Tangentially related to: #22380

**Environment**:
- Grafana version: v7.0.0
- Panel: table

**Comment by torkelo** [comment]
Unable to replicate, works when I test: https://play.grafana.org/d/27c0IFkGk/data-link-with-dashboard-variable?orgId=1

**Comment by matthubb** [comment]
Ah. I was also able to make it work, but only after saving _and_ reloading the dashboard.

**Comment by aknuds1** [comment]
@torkelo Have another look, given his latest reproduction info?

**Comment by torkelo** [comment]
could replicate, thanks for reporting this!

**Comment by torkelo** [comment]
This is caused by updateIndex https://github.com/grafana/grafana/blob/master/public/app/features/templating/template_srv.ts#L103  resetting the index and clearing all global variables, maybe we need a separate index for global variables so we do not lose them on updateIndex
