### ISSUE TITLE
Check count value using specific time range

### ISSUE THREAD

**Issue by srkfru** [grafana/grafana#25101]
**What happened:**
While i am using default time range(last 30m, 24h or 2d), below query is working fine and showing the appropriate count. 
Query:
```sum by (app)(increase(orders_success_seconds_count{app="$app", exception="none"}[$__range]))```

But while i am giving custom time range, the graph is changing which should not be proper one and not showing the proper value. Which should be 199K as per the above snapshot.

 I haven't found any error in the query inspector. (for $__range getting this value: &start=1589863500&end=1589868045&step=15")

**What you expected to happen:**
Want to see the order count number using custom time range.

**How to reproduce it (as minimally and precisely as possible):**
You can use any counter metrics for this. 

**Anything else we need to know?:**
Pic:
![image](https://user-images.githubusercontent.com/51711089/82344202-5e927700-9a11-11ea-9400-5ee86614eb2e.png)

![image](https://user-images.githubusercontent.com/51711089/82344726-0a3bc700-9a12-11ea-99e4-d1dce3d30dec.png)

Given Time Range is :
![image](https://user-images.githubusercontent.com/51711089/82345004-5e46ab80-9a12-11ea-9193-b6497249a42d.png)

**Comment by aknuds1** [comment]
Could you please rewrite the issue using our standard issue template, so we can reproduce it easily?

**Comment by srikanta50** [comment]
> Could you please rewrite the issue using our standard issue template, so we can reproduce it easily?

@aknuds1, i have update the issue using standard template. Please let me know if any changes require.

**Comment by srkfru** [comment]
@aknuds1 , can you please help here to fix this issue?

**Comment by srkfru** [comment]
Can someone please look into this issue?

**Comment by torkelo** [comment]
Just tested this, and I get the same $__range rendering when using absolute time range and a relative. 

So this is likely a prometheus query logic issue

**Comment by srkfru** [comment]
@torkelo, thanks a lot for checking on this. I will look into the Prometheus side to get this fix, if anything available.
