### ISSUE TITLE
getting error while creating variable for tag_values

### ISSUE THREAD

**Issue by ssaurav-1987** [grafana/grafana#25104]
Hi I am using Grafana 6.5 with InfluxDB 2.0. Well I have multiple tags and each tag will have multiple values. Just want to create a variable for each tag so that If I select option from a tag its value should get populated in another dropdown list to give value in flux query from variable.

I have seen tag value group part in grafana variable page. Need some guidance in this how to create multiple variable for tag lists and to populate data in dropdown from each tag

<img width="1169" alt="Screenshot 2020-05-26 at 4 13 13 PM" src="https://user-images.githubusercontent.com/4965334/82891870-183a9c00-9f6c-11ea-9cb6-d584ca319dfe.png">

**Steps to reproduce**:

**Actual Result**:

**Expected Result**

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by aknuds1** [comment]
As this looks like a support request rather than a bug report, I will close this issue and suggest you ask in the [community forums](https://community.grafana.com) or [Slack](http://slack.raintank.io/). Thanks!
