### ISSUE TITLE
Playlists: Improve selectable dashboards list

### ISSUE THREAD

**Issue by hedss** [grafana/grafana#25118]
**What would you like to be added**:
Playlist creation: Either ability to page through all of the available dashboards to pick them, or to show the top 20 most viewed dashboards.

**Why is this needed**:
When creating a playlist, it seems that the list of dashboards is in alphabetic order, but the list is a max of 20 items long with no option to see another ‘page’ of them. Consequently the user needs to search by the dashboard name to add them to a playlist if they’re not in the list. The assumption is this stops huge numbers of dashboards potentially being listed.

However, on the home page, Grafana shows the most viewed/starred dashboards and it would make sense to show these instead instead of an alphabetical list.

**Comment by tskarhed** [comment]
I would suggest doing these changes with the Angular migration, and possibly more UX updates.

**Comment by tskarhed** [comment]
Other possible playlist UX improvements:

- SplitButton for "Start playlist"
- Drag and drop reorder

**Comment by tskarhed** [comment]
We had this as a subject on a UX feedback session a couple of weeks ago. For whoever is implementing the changes, please [have a look at the disucssion](https://docs.google.com/document/d/1m2yciWfQa-rp-KLUrMLYOge00GAd8bLPzmDtDwDFt0o/edit#heading=h.zgly6f12mbcq).

**Comment by hugohaggmark** [comment]
Closing this PR in favor of #32218
