### ISSUE TITLE
SQL data sources: Query Builder and Query Editor and desynchronized

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#25111]
**What happened**:
There are some issues with SQL Query Builder and Raw Query Editor that I've noticed during my work on https://github.com/grafana/grafana/pull/25110:

- Query Builder and Raw Editor Query editor are desynchronized. Change in one doesn't affect the change in second.
![Kapture 2020-05-26 at 14 46 24](https://user-images.githubusercontent.com/30407135/82904476-d35e3780-9f62-11ea-95ee-2d3825f6012a.gif)

-  When we are interpolating, we always interpolate just RawSql query. When sharing the panel with template variables, it always interpolates only the ones in RawQuery and makes Query Builder and displayed results not synced.
![Kapture 2020-05-26 at 15 01 19](https://user-images.githubusercontent.com/30407135/82904510-e07b2680-9f62-11ea-8753-2dc2d64141da.gif)

**What you expected to happen**:
I would expect Query Editor and Query Builder to be just different views and they would update the same query. Change in one would result in change in the other. When interpolating, it wouldn't matter which query gets interpolated as they would be the same. 

**How to reproduce it (as minimally and precisely as possible)**:
See videos

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 7.0.0
- Data source type & version: Postgres, MySQL, MSSQL
- OS Grafana is installed on: OSX Catalina

**Comment by aknuds1** [comment]
Added this to our backlog, since it was said in Slack that we should have it, but I frankly can't tell if the bug happens in front-end or back-end.

**Comment by marefr** [comment]
Frontend or backend doesn't matter. We own it, but maybe we'll need help with frontend from others? Need to prioritize it first

**Comment by aknuds1** [comment]
@marefr Ah OK, that's interesting. I thought the dividing line depended on the code being client-side or server-side.

**Comment by marefr** [comment]
Normally yes, but plugins is currently a bit of an edge case.
