### ISSUE TITLE
Alerting: Support storing sensitive notification settings securely/encrypted

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#25113]
**What would you like to be added**:
Support secure json in notification channel setting.

**Why is this needed**:
Some of the notification channel setting store api token, password, etc...
Editor role user can see these settings, but Admin want to hide the value from Editor user.

**Comment by mtanda** [comment]
@marefr 
I think `terraform-provider-grafana` also need to support secureFields.
https://github.com/grafana/terraform-provider-grafana/issues/147

From `Grafana Cloud` administrator perspective, terraform provider feature is important.
`Grafana Cloud` doesn't support provisioning (because it doesn't allow to put config file), administrator might use terraform for manage configuration.
I use terraform for setup datasource, alert notification, dashboard, alert rule.

**Comment by marefr** [comment]
@mtanda make sense. Great you've created an issue there
