### ISSUE TITLE
Using Variables/queries in thresholds

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#25127]
**What would you like to be added**:
That I can use query/variable in thresholds
**Why is this needed**:
For dynamical thresholds.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/159

**Comment by radimkohout** [comment]
Will It ever be done? The issue that you are mentioning is 6 years old

**Comment by torkelo** [comment]
hope so

**Comment by radimkohout** [comment]
Is there any expectation when?

**Comment by Freeze777** [comment]
Any updates?

**Comment by radimkohout** [comment]
Nope
