### ISSUE TITLE
Transformations: cannot add a transformation to a new or existing panel, moving between query tab and transform tab results in an error

### ISSUE THREAD

**Issue by baur** [grafana/grafana#25122]
**What happened**:

```
An unexpected error happened
Подробнее
TypeError: Cannot read property 'data' of null

    in t
    in div
    in Ma
    in div
    in an
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Open Existing Table Panel in Edit Mode-> Click Transform Tab

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Is that error copied from the browser console?

**Comment by baur** [comment]
console:

```
react-dom.production.min.js:196 TypeError: Cannot read property 'data' of null
    at t.n.renderTransformationEditors (TransformationsEditor.tsx:112)
    at t.value (TransformationsEditor.tsx:203)
    at Ka (react-dom.production.min.js:181)
    at Ya (react-dom.production.min.js:180)
    at Su (react-dom.production.min.js:261)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at KqkS.t.unstable_runWithPriority (scheduler.production.min.js:18)
fu @ vendors~app.7c9669f9d715261b5af3.js:2
i.componentDidCatch.r.callback @ vendors~app.7c9669f9d715261b5af3.js:2
Oi @ vendors~app.7c9669f9d715261b5af3.js:2
mi @ vendors~app.7c9669f9d715261b5af3.js:2
mc @ vendors~app.7c9669f9d715261b5af3.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.7c9669f9d715261b5af3.js:2
Wo @ vendors~app.7c9669f9d715261b5af3.js:2
gc @ vendors~app.7c9669f9d715261b5af3.js:2
ic @ vendors~app.7c9669f9d715261b5af3.js:2
(anonymous) @ vendors~app.7c9669f9d715261b5af3.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.7c9669f9d715261b5af3.js:2
Wo @ vendors~app.7c9669f9d715261b5af3.js:2
Ko @ vendors~app.7c9669f9d715261b5af3.js:2
Yo @ vendors~app.7c9669f9d715261b5af3.js:2
ue @ vendors~app.7c9669f9d715261b5af3.js:2
Er @ vendors~app.7c9669f9d715261b5af3.js:2
```

![image](https://user-images.githubusercontent.com/2898361/82926505-1d660e00-9fa1-11ea-8543-4941a3c3c475.png)

**Comment by pcedelle** [comment]
Hello,

FYI, I have the *exact same error* with InfluxDB as the datasource.

Side effect I believe : I cannot add a Transform on a new Panel

1. I click select on a Transform, nothing happens
2. I switch to the `Query` tab, then the `Transform` tab now shows `(1)`.
3. I click on the `Transform` tab again -> above error happens.

Environment:

- Grafana version: 7.0.1
- Data source type & version: InfluxDB
- OS Grafana is installed on: Official alpine grafana/grafana docker image
- User OS & Browser: MacOS & Chrome 81

I believe this to be related but I'd be happy to report another issue if it is not.

**Comment by GrzegorzLyp** [comment]
Same problem with ElastcSearch 7.6.2.

**Comment by Estrax** [comment]
Can confirm - any datasource and any visualization - reproduce steps as mentioned by @pcedelle.

@aknuds1 that should go into the platform frontend backlog I think.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/25152
