### ISSUE TITLE
Grafana 2.1 Metrics get multiplied on longer timewindows

### ISSUE THREAD

**Issue by dieserkai** [grafana/grafana#2512]
Hello,

i'm running a test environment for grafana 2.1 to visualize the resource usage of hundreds of virtual servers (KVM). The measurements are collected by collectd with the virt / libvirt plugin. I store them in a influxdb (version 0.9). 

I'm running the virtual servers on various hardware generations. Each generation uses a own influxdb server. Also each hardware generation does have its own templated Dashboard (a very simple one). So we have a fixed mapping: one dashboard = one Influxdb data source

this seems to work fine, as long as the time window of the graph is smaller than 2 days:
![grafana_24h](https://cloud.githubusercontent.com/assets/8260813/9269029/503f9808-4265-11e5-85af-543629bb4797.png)

As soon as i switch the time window to 2 days, the metrics get multiplied:
![grafana_2d](https://cloud.githubusercontent.com/assets/8260813/9269036/6aea5b7a-4265-11e5-9479-b13469a6e741.png)

the only difference between the 2 views is the the time window size. I didn't change any metric.

if i switch over to 7 days, it get worse:
![grafana_7d](https://cloud.githubusercontent.com/assets/8260813/9269059/b1416bae-4265-11e5-8a15-e05422f88d71.png)

I do have this issue on all of my dashboards, with all of my influxdb data sources and with various collectd versions. Some hardware generations are running on debian, some on centos, so they do not have the same collectd version running (there is no version mix within one hardware generation).

I already made a dump of the data stored in the influxdb: there is now variation in the raw data (only the measured values diversify, but that was expected ;) )

Do you have any idea what could be the source of this Issue?

best regards,
Kai

**Comment by torkelo** [comment]
This is a bug in InfluxDB 0.9 which has yet to be solved I think
https://github.com/influxdb/influxdb/issues/3242

**Comment by dieserkai** [comment]
in that issue they are saying that we have to set a higher value for the chunk_size Paramater or that we have to set the parameter chunked to false. 

Is there any way to do this in grafana?

**Comment by torkelo** [comment]
@dieserkai if your query is returning more than 10000 data points you are doing something wrong, your influxdb query should only return number of data points as there are pixels on the graph, otherwise you are just slowing down your browser needlessly.  Grafana sets the $interval variable so that the InfluxDB group by time results in about the same number of data points as there are pixels on the graph.

**Comment by dieserkai** [comment]
@torkelo in that case: my grafana installation ignores the time interval. i can set this to any value without any change. i tried to set it to 5 min, but i still have a data point every 10s

**Comment by torkelo** [comment]
@dieserkai not sure I believe you, does your queries contain $interval ? or have you used raw query mode and specified a group by time your self or removed the group by time?

**Comment by dieserkai** [comment]
@torkelo i used the metric editor to create the queries, i did not made any changes in the raw mode. 

if i take a look in the json or raw view my query is for example:

SELECT derivative(value) FROM "virt_rx" WHERE "host" = '$HOST' AND "type" = 'if_packets' AND $timeFilter GROUP BY time($interval) fill(0)

The field "Group by time interval" has been tested with various values: 30s 60s >60s 1m 5m 300s, but it does not change anything.  Only if i write something invalid into this filed, like "abc" i get a syntax error

**Comment by torkelo** [comment]
looks like a bug with derivative function in InfluxDB it does not respect the group by time interval, it is as if you did not have any group by time or aggregation at all, it is returning raw unaggregated data (but with derivative applied). 

You can issue queries like this (not supported in the function editor yet)
SELECT derivative(mean(value), 10s) FROM "cpu" WHERE "hostname" =~ /$hosts/ AND $timeFilter GROUP BY time($interval), "hostname"

**Comment by dieserkai** [comment]
yes you are right. this seems to work. with this "SELECT derivative(mean(value), 10s)" syntax i can use the group by time function and get better graphs without multiplication of the data series.

thank you for your help!
