### ISSUE TITLE
Postgres: Error messages delayed until next input

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25124]
**What happened**:
When editing a panel with multiple queries, if you have an error in your query, the error message isn't shown until after you modify the query.

**What you expected to happen**:
Error messages should be shown as soon as they are received.

**How to reproduce it (as minimally and precisely as possible)**:
https://stormcloud9-misc.s3.amazonaws.com/vokoscreenNG-2020-05-26_12-48-56.webm

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: PostgreSQL 12 
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins:
- Others:

**Comment by kirederik** [comment]
Hey @phemmer, thanks for opening this issue and apologies for the delay.

The good news is that this seems fixed; I tested on Grafana 8.2.

I'll close this one but few free to reopen it if needed!
