### ISSUE TITLE
Add ability to transform text values in table panel

### ISSUE THREAD

**Issue by neilmunday** [grafana/grafana#25120]
**What would you like to be added**:

I have a table to show results from a Loki query, e.g.

```sum(count_over_time({app="sshd",user=~".*"}|="Invalid user"[$__interval])) by (user)```

Then I add a _Calulcation Total_ transform which results in a table with two columns: the first I would like to display the `user` value from the query, instead the table displays values such as:

```
Value {{user="foo"}}
Value {{user="bar"}}
```

I'd like the table to show this instead:

```
foo
bar
```
i.e. extract out  the actual user name in this example say using a regular expression.

**Why is this needed**:

Being able to modify text values from a result in the table panel would be very useful. Wasn't this possible in the previous version of Grafana (6.7) using column styles?

**Comment by torkelo** [comment]
have you tried using {{user}} in the legend format in your query editor? the Value prefix should be fixed in 7.0.1

**Comment by neilmunday** [comment]
Hi @torkelo 

With the Loki data source, I do not have the option to set the legen format in the query editor.

**Comment by torkelo** [comment]
ah, I see.

**Comment by pcbl** [comment]
+1. Have exatbly the same demand for a Loki Datasource...

so far using {__series.name} which would bring something like `{user="foo"}` from the demo above but it would be extremelly valuable if we get only the value... the rest could be ignored...

Meanwhile, is there any possibility that i use a function like "replace()" on the Display name property?

**Comment by neilmunday** [comment]
I can confirm that with Grafana 7.1.5-1 that using `{{user}}` in the legend option of the table works.
