### ISSUE TITLE
Bar Gauge Auto min/max does not use correct value for Totals function

### ISSUE THREAD

**Issue by fgnn** [grafana/grafana#25128]
**What happened**:
I have electricity usage data in Influxdb, where the values are the electricity consumed, exported, etc. in 5 minute intervals. The bar gauge visualization is being used to sum up these values for the chosen time range. The values themselves are correct, but the min and max range are not. It appears that the min and max ranges used are the min and max of the individual values within the series, not the reduced total. For this example, the max individual value is about 1.03 kWh, which is the most produced my by Solar Array in full sun in a 5 minute period.
![2020-05-26 13_04_13-Inverter and Meter - Grafana](https://user-images.githubusercontent.com/12035623/82940814-94c08100-9f52-11ea-9c45-f326d352b6be.jpg)

**What you expected to happen**:
In this example, I would expect 2.4 MWh to the max, with "Production" to be a full bar. All other bars would show a partially full bar as a percentage of 2.4 MWh. Assume the Min is manually set to 0. I would expect the bars to look similar to those in the below picture, but using the "Total" function instead of "Max".
![2020-05-26 13_04_47-Inverter and Meter - Grafana](https://user-images.githubusercontent.com/12035623/82942705-98a1d280-9f55-11ea-81b1-c9a5bace6c69.jpg)

**How to reproduce it (as minimally and precisely as possible)**:
Any time series data should be able to reproduce this. In your data query, "Group By" 5 minute intervals, and then in your bar gauge choose "Total" as the Value. Leave "min" and "max" blank.
![2020-05-26 13_05_01-Inverter and Meter - Grafana](https://user-images.githubusercontent.com/12035623/82942664-8b84e380-9f55-11ea-8e2a-dd94a29c1c8b.jpg)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0 (armhf)
- Data source type & version: influxdb 1.7.10-1 (armhf)
- OS Grafana is installed on: Raspbian GNU/Linux 10 (4.19.108-v7l+)
- User OS & Browser: Windows 10, Chrome 83.0.4103.61(64-bit)
- Grafana plugins: 
- Others: Raspberry Pi 4 Model B , 4GB RAM

Please let me know if there is any other information I can provide. Thanks to the Grafana team!

**Comment by torkelo** [comment]
> It appears that the min and max ranges used are the min and max of the individual values within the series

Yes this is how the auto min & max values are determined, it does not always work so in this case you have to specify a manual min & max

**Comment by PayBas** [comment]
Why was this closed? Seems like a valid (and pretty common) use-case, which can be implemented.

**Comment by saminurm** [comment]
I also think this is a valid use case.

- I'm categorizing acceleration events to different bins by their magnitude
- On some conditions / time range my event counts might vary in range between 0 to 100
- On other conditions / time range the counts may vary from 0 to 100000
- If I set the max to "1000", then on some conditions all the bins hit the maximum
- If I set the max to "100000", then on some conditions the bars are very small

Correct graph would be produced if the Max value was the maximum of total counts instead of the max of the latest measurement. It could be parametrized so that the user could select if the max is calculated from the total values or from the latest measurement.

**Comment by lollocavs** [comment]
> > It appears that the min and max ranges used are the min and max of the individual values within the series
> 
> Yes this is how the auto min & max values are determined, it does not always work so in this case you have to specify a manual min & max

I think that defining a min/max value for each gauge bar is a conceptual mistake. With this logic, the visual comparison with the drawn values is inconsistent!

**Comment by bjiirn** [comment]
Looks like this is long closed, but i'm encountering the same problem now 3 years later. Or am i overlooking something?

**Comment by dumistoklus** [comment]
> Update: I found a solution:
> Transform -> Reduce -> Mode: Reduce fields -> Calculations: Total

@bjiirn Thank you!
That worked for me too!

**Comment by SeWieland** [comment]
why is this still not working by using the default Total reducer function on the Gauge?

Using the custom transfrom, the overrides per field name do not work anymore..
