### ISSUE TITLE
Unable to get data for CWAgent

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#25136]
**What happened**:
Tried to add CWAgent disk_used_percent metric and other. But the data is not displayed. All not custom metrics is displayed.

**What you expected to happen**:
Graphics

**How to reproduce it (as minimally and precisely as possible)**:
Add custom metric namespace, CWAgent, add metric disk_used_percent, add all dimensions (*) from list-metrics

**Anything else we need to know?**:
Virtual machine

**Environment**:
- Grafana version: 7.0.0 (aee1438ff2)
- Data source type & version: sqlite3 3.7.17
- OS Grafana is installed on: 4.14.173-137.229.amzn2.x86_64  Amazon Linux 2 AMI
- User OS & Browser: Win 10 Chrome 83.0.4103.61
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What data source are you using? What are your data source settings? What's the request grafana makes and what is the response from your data source? 

Sounds like cloudwatch? can you get these metrics from the grafana server if you use the cli tools? You will have to troubleshoot this a lot yourself and give as much detail as you can on network calls & responses

**Comment by Tepew** [comment]
AWS ClaudWatch from IAM policies. In Claudwatch a see this metrics. 

from Query inspector:
Object
request:Object
method:"POST"
url:"api/tsdb/query"
data:Object
from:"1590543994878"
to:"1590565594878"
queries:Array[1]
response:Object
results:Object
A:Object
refId:"A"
meta:Object
gmdMeta:Array[1]
0:Object
Expression:""
ID:"queryA"
Period:60
series:Array[1]
0:Object
name:"disk_used_percent_Average"
points:Array[0]
tables:null
dataframes:null

**Comment by torkelo** [comment]
So cloudwatch is returning disk_used_percent_Average,  is that not what you expect or see in Grafana?

**Comment by Tepew** [comment]
![image](https://user-images.githubusercontent.com/42611903/83224080-39c2a000-a185-11ea-8e68-6bcc19e1dace.png)
but in claudwatch
![image](https://user-images.githubusercontent.com/42611903/83224164-6aa2d500-a185-11ea-83cc-708374e05cdf.png)

**Comment by Tepew** [comment]
Upgrading to 7.0.3 still does not work.

**Comment by daniellee** [comment]
@Tepew I have it added as a custom metric:

![image](https://user-images.githubusercontent.com/434655/85307523-4dc19f00-b4b0-11ea-9b3d-5fd7575c3e57.png)

What do your config settings look like?

**Comment by Tepew** [comment]
![image](https://user-images.githubusercontent.com/42611903/87550135-64c26e00-c6b7-11ea-84b1-6ee9e8c96669.png)

**Comment by aknuds1** [comment]
@papagian Is this issue solved now?

**Comment by aknuds1** [comment]
I think this might be solved by #28391.

**Comment by aknuds1** [comment]
Closing this issue since it should be solved in v7.2.2. Please let us know if it turns out to be still broken.
