### ISSUE TITLE
StatPanel: Migration from singlestat does not support the metric "Time of last point"

### ISSUE THREAD

**Issue by cicciopizza** [grafana/grafana#25139]
like bug #24076 
In the old singlestat we had a "Time of last point" option in the show value
 option dropdown.
In the new stat panel this option is missing
![Selezione_125](https://user-images.githubusercontent.com/26459829/83003574-cb5bd180-a00e-11ea-9116-01bf913eca47.png)

![Selezione_126](https://user-images.githubusercontent.com/26459829/83003623-dc0c4780-a00e-11ea-82d1-33fd91c7b80c.png)

**Comment by aidenprice** [comment]
I found a workaround in PostgreSQL/Timescale with the Stat panel. Should be possible in any other datasource.

Manually set the query to return Epoch milliseconds as the value. Postgres returns seconds so you just need a multiplier, like so;

```SELECT
  time_col AS "time",
  EXTRACT(EPOCH FROM time_col) * 1000.0
FROM history
ORDER BY 1 DESC
LIMIT 1```

Then set the Unit to `From Now`.

You could leave out the `LIMIT` clause if you like and just use the Stat panels own aggregation.

**Comment by cicciopizza** [comment]
In grafana 7.0.3 a new option 'Fields' has been added where it is possible to choose 'Time' so by making a query with 'last value' it is possible to view the timestamp of the last measurement. 
![image](https://user-images.githubusercontent.com/26459829/84237449-a761bb00-aaf9-11ea-9353-f983c9cc2b4a.png)

However, I have seen that formatting has no effect and it would still be nice to have the possibility of applying a custom format Eg hh24: mm: ss
![image](https://user-images.githubusercontent.com/26459829/84237906-7b930500-aafa-11ea-87c0-9efbfeaf3396.png)

**Comment by ikkemaniac** [comment]
> However, I have seen that formatting has no effect and it would still be nice to have the possibility of applying a custom format Eg hh24: mm: ss
> ![image](https://user-images.githubusercontent.com/26459829/84237906-7b930500-aafa-11ea-87c0-9efbfeaf3396.png)
I have 'Time' select on Panel->Display->Fields.

On Field->standard options->Unit
Selecting 'From Now' as unit has no effect.

However, on Overrides->Filter by field "Time" -> unit 'From Now' does work.

**Comment by torkelo** [comment]
Closing this as you can now do this in 7.2

**Comment by Appelg** [comment]
It was far from clear on how to achieve this.

1) Scroll to the very bottom of the right-hand panel when editing the singlestat and click "+ add field override"
2) Select "Fields with type"
3) Select "Time (1)" in the dropdown that appeared
4) Click "+ add override property"
5) Select "Standard options > unit"
6) Click "choose" and then type "from" in the search, "Date & Time / From now" should appear

Really intuitive huh? :)
