### ISSUE TITLE
Failing migration between Grafana v6.7.3 to v7.0.0

### ISSUE THREAD

**Issue by muzzafari** [grafana/grafana#25133]
**What happened**:

Here's the logs:
t=2020-05-26T06:00:12+0300 lvl=eror msg="Executing migration failed" logger=migrator id="Update uid value" error="Error 1644: Trying to insert a negative value in data_source"
t=2020-05-26T06:00:12+0300 lvl=eror msg="Exec failed" logger=migrator error="Error 1644: Trying to insert a negative value in data_source" sql="UPDATE data_source SET uid=lpad(id,9,'0');"
t=2020-05-26T06:00:12+0300 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: Failed to roll back transaction due to error: %!s(<nil>): Error 1644: Trying to insert a negative value in data_source"

**What you expected to happen**:

I expected migration to execute without errors and Grafana continue to work.
Version 6.7.3 works correctly on this database
**How to reproduce it (as minimally and precisely as possible)**:
Update Grafana from v6.7.3 to v7.0.0.

**Anything else we need to know?**:
We upgrade base mysql to ver. 8

**Environment**:
- Grafana version:
7.0.0
- Data source type & version:
- OS Grafana is installed on:
Red Hat 4.8.5-36
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@aocenas any ideas what could be wrong here?

**Comment by torkelo** [comment]
We have not other similar reports, can show the content of your data_source table?

**Comment by aocenas** [comment]
@torkelo definitely seems like issue with this migration https://github.com/grafana/grafana/blob/e5dd7efdee6a683a5722286afcf428f10871736a/pkg/services/sqlstore/migrations/datasource_mig.go#L148 but not sure why and I do not get the message. Uid is string so not sure what negative value means here. Also the UID generation pattern is taken from dashboards. I suspect maybe it is something with the `lpad` function and mysql version or something like that.

**Comment by aocenas** [comment]
So no sure what the problem is. Tried the migration locally and does not seem to be an issue. From the error message it seems like this is some custom constraint so my assumption is that some other field is throwing that during the update (not sure if that is the behavior for mysql). I wasn't able to find anything in our codebase that seems like this though. 

@muzzafari is it possible you have some custom constraints on the data_source table?

@marefr or @papagian do you have any ideas what could be the cause of this or where to look?

**Comment by papagian** [comment]
@muzzafari 
thank you for reporting this!

is it possible to enable logging of SQL queries and debug log level by setting the following environmental variables and restarting your server?
```
GF_DATABASE_LOG_QUERIES=true
GF_LOG_LEVEL=debug
```

what is the query that causes the problem?

**Comment by muzzafari** [comment]
Thank you all, we sorted it out. The reason was a custom trigger on the datasource table that forbade updating the Url field to a value other than '^https?://127.0.0.1.*'
