### ISSUE TITLE
Live Drilldown on same Page based on selected row

### ISSUE THREAD

**Issue by hypermagicmountain** [grafana/grafana#25144]
**What would you like to be added**:
Dynamic "on page" variable for filters and drilldown, updated onclick.

Example:
https://coronavirus.jhu.edu/map.html

If you click one row in the "Country"-table, all other visualizations will dynamically drill down to the selected value.

I guess in grafana it would be a variable that we can use in queries that will be updated when the user is clicking a cell in a table.

**Why is this needed**:
A modern, fast way to troubleshoot data and visualize dynamic dashboards. I have been using Grafana for 3 years now for IT monitoring and this is the only feature I miss every day...

**Comment by torkelo** [comment]
This can be done with ad hoc filters (supported by some data sources), or with data links + variables used in queries

**Comment by hypermagicmountain** [comment]
Thanks for the quick reply - but I don't think data links or ad hoc filters are doing what I asked for.

**Data Links:**

- Do not work on tables
- Don't refresh the same page but rather link to another dashboard

**Ad hoc filters:**

- I don't know what "some" data sources mean, but they do not exist for MSSQL, MySQL or influxDB which are heavily used data sources
- Do they really do what I described? I can't test it, since I don't use any sources they are implemented for

Would you consider reopening the issue? If you check out the URL with the example (corona dashboard) I think you'll see how helpful this functionality can be.
