### ISSUE TITLE
What version of jaeger-query youare usinfg in grafana 7.0v?

### ISSUE THREAD

**Issue by vvvprabhakar** [grafana/grafana#25146]
<img width="1425" alt="Screenshot 2020-05-27 at 6 30 18 PM" src="https://user-images.githubusercontent.com/20414336/83021818-32e24300-a048-11ea-8e73-94666ecde98e.png">
Traces are not found, it is able to list the trace
What else I am doing wrong ?

**Comment by vvvprabhakar** [comment]
The same trace when I find in jaeger UI its is present

**Comment by aknuds1** [comment]
This looks more like a request for support than a bug report, so I will close the issue and kindly suggest you try our community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io/).
