### ISSUE TITLE
Extension of Graphite Metric Editor

### ISSUE THREAD

**Issue by MarcelT0815** [grafana/grafana#2514]
I would love to do a multiselect in the metric element selection dropdown of the queryeditor. This should result in a metric element like this: {aaa,bbb,ccc}. Also direct support for the asterisk with some piece of string, like aaa*bbb and letterlists like aaa[1-9a-z]bbb would be fine. Today i have to use the raw editor, but if i configure a complex query it is not fun. And you easy destroy your query if you accidentially use the editor not in raw mode.
I think about a special entry in the dropdown which activates a edit mode to enable direct modifications of the metric element string. When showing a metric in the editor, you can easy decide if its a simple string oder single asterisk or contais letters with an asterisk/[] or is a list {...}

**Comment by torkelo** [comment]
You can use the editor for this, you can enter any value in a metric node (segment). 

![test](https://cloud.githubusercontent.com/assets/10999/9269501/9f4f7594-426a-11e5-9a57-3aea58a29b19.gif)
