### ISSUE TITLE
Opening explore in a new window from a panel in a dashboard doesn't preserve the subpath

### ISSUE THREAD

**Issue by skgsergio** [grafana/grafana#25141]
**What happened**:
We've tried to open the explore in a new browser tab from a panel in a dashboard, for that we just did ctrl + click (or cmd + click in macOS) and it opened a new window with the explore link but with the subpath missing. If we click normally (without ctrl/cmd pressed) it preserves it.

click -> `/grafana/explore?...`
ctrl/cmd+click -> `/explore?...`

**What you expected to happen**:
To preserve the subpath.

**How to reproduce it (as minimally and precisely as possible)**:
1.- Configure grafana to be served from a subpath
2.- Go to any dashboard and click explore with ctrl/cmd pressed in any panel

**Anything else we need to know?**:
Our relevant Grafana config:
```
ENV GF_SERVER_SERVE_FROM_SUB_PATH true
ENV GF_SERVER_DOMAIN monitoring.ourdomain.tld
ENV GF_SERVER_ROOT_URL %(protocol)s://%(domain)s/grafana/
```

It is being served using Nginx but we also tried by opening directly `http://monitoring.ourdomain.tld:3000/grafana/` to test it directly against Grafana.

Just in case, this is the link I'm referring to:

![image](https://user-images.githubusercontent.com/186349/83007586-30fe8c80-a014-11ea-885a-454b98ee770c.png)

**Environment**:
- Grafana version: `v7.0.1 (ef5b586d7d)`
- Data source type & version: any
- OS Grafana is installed on: official docker image
- User OS & Browser: Linux/macOS, Google Chrome 81
- Grafana plugins: None
- Others: N/A

**Comment by peterholmberg** [comment]
@skgsergio I am not able to reproduce this, is this still an issue? Please reopen if so.
