### ISSUE TITLE
Unable to see POD details in Graph after restarting the PODS

### ISSUE THREAD

**Issue by srkfru** [grafana/grafana#25142]
**What happened**:
I have created a health monitoring check for PODs and it is showing proper data for all. It is working fine until PODs are restarted. After the restart, new PODs are being aligned to applications and in Grafana we can see only new POD information. Unable to find data for older PODS.

I think I have to change it @template level, that I am using to collect the details for POD. I have created this template using the query option "pod $namespace" and the refresh option is "on time range" but still this is not working. 

**What you expected to happen**:
It should have shown me older POD information when I am changing the time range to POD restart or earlier time.
**How to reproduce it (as minimally and precisely as possible)**:
You can use default Cluster plugin dashboard to validate this.

**Anything else we need to know?**:
Dashboard prior to restart:
![image](https://user-images.githubusercontent.com/51711089/83010137-6ff10a00-a035-11ea-8e2c-2515380c75b9.png)
After Restart we have new pod details, you cannot see the data of older PODS prior to 5/24/20:
![image](https://user-images.githubusercontent.com/51711089/83010571-13dab580-a036-11ea-8cef-a4cbefc339e0.png)
Template details for POD: (Here I have used regex to collect specific POD which is initiated with app name, it will remain same every time)
![image](https://user-images.githubusercontent.com/51711089/83010669-3c62af80-a036-11ea-8de0-e2581de8d3bb.png)

One more thing, i can see the data in Prometheus for older PODs when I am changing the time range but unable to fetch those details in Grafana.

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Out side of Cluster
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Can you try Grafana v7.0.1 and see if the problem persists?

**Comment by srkfru** [comment]
@aknuds1, Can you suggest any solution for the current version? As migration work will take some time and if this is the only solution we have then we will plan on this further.

**Comment by torkelo** [comment]
That template variable query does not look like a Prometheus template variable query. 

I would open chrome dev tools and inspect the network queries and the response, this does not look like a Grafana problem, more of a query or TSDB issue. 

If you have network requests & responses and grafana is showing the wrong thing please put the details here and I can re-open

**Comment by srkfru** [comment]
@torkelo, m really a fan of yours.

I just used the existing template from the cluster plugin that i am using. Below is the default template for cluster plugin:( I just used regex to filter the namespace that's all)

![image](https://user-images.githubusercontent.com/51711089/83054835-a5671900-a070-11ea-9107-3f082ea389c3.png)

**Comment by torkelo** [comment]
Not familiar with the cluster plugin, maybe it’s an issue with that plugin ?

**Comment by Hl278** [comment]
@torkelo , as you mentioned above
>>this does not look like a Grafana problem, more of a query or TSDB issue.
- Yes more of a query problem.
- something changes required to do with variable creation (regex and refresh refresh option)

Issue :  We are able to get data for pods(Container) resource usage, but only until PODs are active and not the old data (after restart).
Prometheus has the older data, but not shown in grafana dashboard - reason is dashboard variable "pod_name" returns names for current time and not for the earlier time mentioned.
Can you please suggest on this?

**Comment by torkelo** [comment]
not sure what could be the reason, maybe the cluster plugin is failing to return names for old series? Can you inspect the network requests & the parameters used? anything that looks wrong in the parameters sent?
