### ISSUE TITLE
Update Grafana from latest 6.7 to 7.0.1 on SLES12 SP4 - Failed dependencies chkconfig urw-fonts

### ISSUE THREAD

**Issue by srnlfk** [grafana/grafana#25149]
**What happened**: If you try to update grafana with 'rpm -i grafana-7.0.1.rpm' on SLES12 SP4 you get an error "failed dependencies chkconfig and urw-fonts".

rpm -i grafana-7.0.1-1.x86_64.rpm
error: Failed dependencies:
        chkconfig is needed by grafana-7.0.1-1.x86_64
        urw-fonts is needed by grafana-7.0.1-1.x86_64

**Environment**:
- Grafana version: 6.7.2
- OS Grafana is installed on: SLES12 SP4

Hint about urw-fonts: https://build.opensuse.org/package/show/home:jfrede/urw-fonts

**Comment by marefr** [comment]
The needed dependencies is documented as needed to be preinstalled [here](https://grafana.com/docs/grafana/latest/installation/rpm/#install-with-rpm).

**Comment by tim-99** [comment]
The needed dependencies are not longer avaialable for SLES 12 SP4... pls check it first before you post some old docs.

**Comment by marefr** [comment]
Sorry didn't understand that was the problem.

**Comment by simonc6372** [comment]
The urw-fonts dependency should be provided by "ghostscript-fonts-std" on SUSE systems. 
On my openSUSE Tumbleweed system: 
 ```
> zypper se --provides urw-fonts
Loading repository data...
Reading installed packages...

S  | Name                  | Summary                     | Type
---+-----------------------+-----------------------------+--------
i+ | ghostscript-fonts-std | Basic Fonts for Ghostscript | package 
```
Looking on SUSE's build server, that is not available on SLES12, but you can get it for openSUSE 12.3, which should be compatible. You would have to check with SUSE Support why that package is not available for SLES12 directly. 

We also have a problem of having a dependency on `chkconfig` which is probably out of date by now. 
Again, you can use zypper to search for what provides that. 
```
> zypper se --provides chkconfig
Loading repository data...
Reading installed packages...

S  | Name           | Summary                                             | Type
---+----------------+-----------------------------------------------------+--------
i+ | insserv-compat | Simple insserv replacement for systemd only systems | package
```
but, for some reason even when I install insserv-compat, zypper/rpm both still think they want a `chkconfig` rpm. That sounds like a strange zypper bug to me. You are safe to ignore the dependency on `chkconfig`

**Comment by tim-99** [comment]
thats right... but you have to build and install your own rpm package of urw-fonts out of  ghostscript-fonts-st to pass the dependencies check. and also their is no chkconfig rpm anymore, but its still available as command.

**Comment by srnlfk** [comment]
It worked for me when i first installed 6.7.4 and then updated to 7.2 with rpm -U --nodeps grafana-7.2.0-1.x86_64.rpm.

**Comment by marefr** [comment]
Thanks @srnlfk. 

The dependency of chkconfig was added due to this bug report #22935 to support Fedora. That obviously broke support using SLES12. The main question moving forward is whether we can maintain a single RPM package to support all different distro's. Or is there perhaps best practices/suggestions of how to build RPM package to better support multiple distro's? Any input/feedback would be valuable here. 

@tim-99 can you verify suggested workaround works for you?

**Comment by tim-99** [comment]
@marefr yep, suggested workaround did it for me too! thanks!

**Comment by marefr** [comment]
Will close this since there are workaround in place. Thanks
