### ISSUE TITLE
Pressing enter on dropdown doesn't select highlighted option

### ISSUE THREAD

**Issue by Stono** [grafana/grafana#25156]
**What happened**:
If you have a variable drop down, use your keyboard to go down the list and then press enter, the highlighted item is not selected, the top item is.

For example in this screenshot you can see i've highlighted `vehicle-metric-service`, however if i press enter, `consumer-vehicle-metric-service` is actually selected.

![Screenshot 2020-05-27 at 18 07 00](https://user-images.githubusercontent.com/1486729/83050839-07118e00-a045-11ea-9370-eb8658e2c971.png)

**What you expected to happen**:
The highlighted item should be selected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Promethus
- OS Grafana is installed on: Centos
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
If anyone wants to help with this, here is the react component used in this variable dropdown: https://github.com/grafana/grafana/blob/master/public/app/features/variables/pickers/shared/VariableInput.tsx

**Comment by rakeshraih** [comment]
Looks like this is fixed with v7.2.0.  Tested on https://play.grafana.org/d/000000002/influxdb-templated?orgId=1  and it works fine.

**Comment by zoltanbedi** [comment]
Thanks for confirming this @rakeshraih, I've also checked and it is working fine.
