### ISSUE TITLE
Question: convert singlestat minutes to hours

### ISSUE THREAD

**Issue by dry4ng** [grafana/grafana#2515]
Hi. I have a metric that logs number of minutes since last successful transaction. I show it as singlestat on dashboard. Is there a way to convert singlestat minutes to hours and minutes.

**Comment by torkelo** [comment]
yes, if you multiply by 60 so the metric becomes seconds, then you can use the unit -> duration -> seconds,  this unit will scale and show hours, days, weeks, etc if the value is high enough

**Comment by movermeyer** [comment]
Note that this gives you things like "2.77 hours" instead of "2 hours, 46 minutes, 1 second"

**Comment by jodli** [comment]
Is there any way to get around this and display "2 hours, 46 minutes" instead?

**Comment by torkelo** [comment]
@movermeyer No the duration unit gives you a friendly name for the duration, if you use something like 3.77 hours your using the wrong unit

**Comment by movermeyer** [comment]
@torkelo You're right. I'm not sure how I messed that up. 

It only shows the largest unit that fits (ex. `3800` =`1 hour`, not `1 hour, 3 minutes, 20 seconds`), but it does use human-friendly names.

**Comment by timtofan** [comment]
Duration unit seems to round "5 hours, 50 minutes" to just "5 hours" on version 4.4.3.

Perhaps a new unit could be introduced to show "X hours, Y minutes, S seconds"? Or maybe could even better to have customizable precision, f.e. duration with N "sub-units". Duration with 1 sub-unit would be "X hours", with 2 sub-units it would be "X hours Y minutes", etc.

What do you think?

**Comment by schwarzlowe** [comment]
I cannot find this option. I'm using 5.1.0 x64.

**Comment by astateofmind01** [comment]
Hmmm, for me it didn't work.

i have it in seconds and decimals 2 but it only shows the weeks. Any help? :)

**Comment by faikabouthalja** [comment]
This is not working for me : Grafana v6.2.5 , i'am trying to show elapsed time with precision for example 5days, 10hours, 2minutes ago but i can only show 6 days instead. I tried using decimal 2 but it doesn't have any effect. I use unit "time: From Now" , stat current (getting elapsed time in ms from prometheus metric). Any Help please ?
