### ISSUE TITLE
FieldConfig: Override rule matcher for ref id to set graph axis option for a specific query result 

### ISSUE THREAD

**Issue by beremour** [grafana/grafana#25157]
**What would you like to be added**:
Is it possible to have an option of placing items at Right Axis in query pane ? In my screenshot Query A must be attached to left Axis and Query B to Right Axis

**Why is this needed**:
Moving large number of dynamic items (produces by regex) to Right Axis is hard now

<img width="1235" alt="Grafana 2020-05-27 at 20 00 17" src="https://user-images.githubusercontent.com/14082299/83050243-f10bc980-a054-11ea-9230-ca5cfd1ba9e6.png">

**Comment by MacNale** [comment]
Is that what you are looking for?
https://play.grafana.org/d/000000012/grafana-play-home?viewPanel=4&orgId=1

**Comment by beremour** [comment]
Oh, thank you very much! It's the thing.
