### ISSUE TITLE
Panel: Show the day on mouse hover and on x-Axes. In other words, allow formatting of date.

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#25167]
**What would you like to be added**:
![image](https://user-images.githubusercontent.com/14235758/83073885-d296d580-a036-11ea-93cb-6dbfaece0f44.png)

Above chart shows the date on mouse hover but not the day. 

![image](https://user-images.githubusercontent.com/14235758/83074189-636db100-a037-11ea-9747-bc4a98090e1c.png)

Above chart shows the date on x-axes but not the day.

**Why is this needed**:
It would be beneficial to allow the date format to be shown.  I end up finding out the day manually for the given date. Having Day or different date format helps in diagnosing a problem quickly. I think, 'TIme region' is for recurrent days and may not be a solution. Is there any other option.

**Comment by torkelo** [comment]
Do not think we will allow full control over date format specifically for the tooltip, but date formats in general is something we want to add

https://github.com/grafana/grafana/issues/1459
