### ISSUE TITLE
Config documents incorrect defaults

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25163]
**What happened**:
The sample/default config file advertises that the `x_content_type_options` and `x_xss_protection` options will change as of version 6.3. We're now on version 7.0.1 and they haven't changed.

**What you expected to happen**:
Config file documentation should be accurate.

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/grafana/grafana/blob/v7.0.1/conf/sample.ini#L204-L211
https://github.com/grafana/grafana/blob/v7.0.1/conf/defaults.ini#L203-L210

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by bergquist** [comment]
Thank you for noticing! Seems like we forgot about this :)
