### ISSUE TITLE
Folders without a view permission not visible to admin

### ISSUE THREAD

**Issue by phemmer** [grafana/grafana#25169]
**What happened**:
Folders which the user doesn't have view permission for, but does have admin permission, don't show up on the list. The only way to reach them is through the "manage dashboards" page.

**What you expected to happen**:
Admins (and editors) should be able to see dashboards they have permissions for.

**How to reproduce it (as minimally and precisely as possible)**:
Be an admin.
Create a folder.
Remove the viewer role & editor role from folder permissions.
Open the dashboard list at the top and note the folder is missing.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: N/A
- OS Grafana is installed on: CentOS/8
- User OS & Browser: Linux Chrome
- Grafana plugins:
- Others:

**Comment by xlson** [comment]
I'm unable to reproduce this as an Org Admin (which I presume is what you are referring to by admin). As an Org Admin (or user with manually added admin permission for a dashboard or folder) I can see the dashboard or folder in both search and manage dashboard views.

Is there anything else you can tell me about what you did or any settings you have modified?

**Comment by phemmer** [comment]
Yes, org admin.

As for why it's not reproducible, that's a good question. I can reproduce it consistently on one environment. But on another environment of the exact same version, I can't reproduce it.

I haven't changed any settings that would seem relevant. Just stuff like the org name, site url, etc.

**Comment by phemmer** [comment]
I exported the dashboards, wiped everything, and reimported them and it seems to be fine now. So will close, and open again if issue recurs.
