### ISSUE TITLE
@grafana/e2e and e2e-selectors API redesign

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#25166]
## *Un*wrap `Cypress` and `cy` globals
We're using Cypress, so we should be explicit about it in our code instead of wrapping it to look like something else. We currently need to learn two _overlapping_ APIs which causes grind. If we were to switch to a different tool, everything—assertions, etc—would have to change with it, so there's no benefit.

### Before
```js
import { e2e } from '@grafana/e2e'
e2e().get('something')
```

### After
```js
cy.get('something')
```

## Use convenience functions in a flat module structure
This solves multiple problems:
* Time wasted when referencing _@grafana/e2e-selectors_' source code as it's not a 1:1 relation with _@grafana/e2e_'s API.
* Importing everything and having to follow a deeply nested structure.
* Component selectors within "pages", separate from "components".
* Magic/confusing (function with no arguments) syntax to use real CSS selectors instead of `aria-label`. Generally, we want to use `aria-label` whenever we can, but they're often not applicable to dependencies created with different methodologies.

### Before
```js
export const Components = {
  PanelEditor: {
    OptionsPane: {
      Group: {
        Visualization: {
          header: 'Options group Panel type'
        }
      }
    }
  }
}
```
```js
export const Pages = {
  Dashboard: {
    url: (uid: string) => `/d/${uid}`,
    someComponent: 'Some label'
  }
}
```
```js
import e2e from '@grafana/e2e'
e2e.pages.Dashboard.visit('abc123')
e2e.pages.Dashboard.someComponent()
e2e.components.PanelEditor.OptionsPanel.Group.Visualization.header()
e2e.flows.addPanel()
```

### After
```js
export default {
  dashboard: {
    someComponent: '[aria-label="Some label"]'
  },
  panelEditor: {
    optionsPane: {
      group: {
        visualization: {
          header: '[aria-label="Options group Panel type"]'
        }
      }
    }
  }
}
```
```js
export default {
  dashboard: (uid: string) => `/d/${uid}`
  // `someComponent` moved
}
```
```js
import { addPanel, getRoute, getSelector } from '@grafana/e2e'
cy.visit(getRoute('dashboard', 'abc123'))
cy.get(getSelector('dashboard.someComponent'))
cy.get(getSelector('panelEditor.optionsPanel.group.visualization.header'))
addPanel()
```

With this, we can educate somehow (via documentation or other means) on how to maintain consistent key naming as we currently have examples of `content` and `container`.

A downside to this approach is relying on runtime errors due to string values instead of relying on static (compile-time) errors.

**TODO**: This makes it more difficult to import `aria-label` values from _@grafana/e2e-selectors_ into core/plugin UI code. We may need a second set of maps for them, imported into the selectors maps.

### Before
Currently, some selectors accept arguments. There are inconsistencies that may persist which only cause confusion, so we should avoid this. For example:
```js
pages.Dashboard.Toolbar.toolbarItems('Dashboard settings')
//-> [aria-label="Dashboard navigation bar button Dashboard settings"]
```
and:
```js
cy.get('[aria-label="TimePicker Open Button"]')
```
`TimePicker` happens to be a toolbar item, but it is not accessible via `toolbarItems()` because it, as a separate component, is reusable anywhere and does not contain the prefix "Dashboard navigation bar button" in its label.

### After
```js
pages.Dashboard.Toolbar.Items.settings()
//-> .navbar [aria-label="Dashboard navigation bar button Dashboard settings"]

pages.Dashboard.Toolbar.Items.timePicker()
//-> .navbar [aria-label="TimePicker Open Button"]
```
and, improved further with the aforementioned convenience functions:
```js
cy.get(getSelector('dashboard.toolbar.items.settings'))
cy.get(getSelector('dashboard.toolbar.items.timePicker'))
```

## Remove `scenario()`
From only looking at a test's code, we don't even know _vaguely_ what is happening behind the scenes. Also, we're limited to a single `it()`, which makes for less granular descriptions and less consistency with unit tests. We can solve all of this and more (such as signing up before login) with convenience functions.

### Before
```js
e2e.scenario({
  describeName: 'asdf',
  itName: 'asdf',
  skipScenario: true,
  scenario: () => {
    a();
    b();
  }
})
```

### After
```js
describe.skip('asdf', () => {
  before(() => login())
  afterEach(() => revertAllChanges())
  after(() => logout())

  it('asdf1', () => a())
  it('asdf2', () => b())
})
```

With this, we should rename `scenarioContext` to `testState` since the concept of a "scenario" is gone. However, this is a smaller change as use of this is now internal only.

---
---

Closing notes:
* The [E2E style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/e2e.md) will need to be updated.

**Comment by hugohaggmark** [comment]
@stevenvachon I like this approach! 2 things that come up at the top of my mind:

1. The e2e wrapper was there in case we were to change e2e test framework again :)
2. I would try to keep the object tree structure in favor of using `const PANEL_EDITOR_OPTIONS_PANE_GROUP_VISUALIZATION_CONTAINER` because it's "can" be easier to find/add items. I do feel our current structure needs some love though, so I realize the object tree has its pitfalls.

**Comment by stevenvachon** [comment]
Per our discussion, your first point has been addressed in the original comment above.

I'll need more time for the second.

**Comment by stevenvachon** [comment]
@hugohaggmark @dprokop  @srclosson @scottlepp @briangann @jhunthrop @kminehart thoughts?

**Comment by kminehart** [comment]
I like it. Flatter hierarchies make a lot more sense to me. I don't have a whole lot of feedback to give since I'm not super familiar with frontend testing. :)
