### ISSUE TITLE
Explore: Support inspect drawer in explore (to get CSV Download support) 

### ISSUE THREAD

**Issue by timlharrison** [grafana/grafana#25162]
**What would you like to be added**:  I would like to be able to export a CSV from the Explore UI.  

**Why is this needed**: Currently Prometheus can't export query results to CSV, but Grafana can.  Right now if I write a query in Explore UI that I want to export, I have to create a new dashboard and copy it over to a dashboard panel just to export it.  This CSV export functionality should be built right in to the Explore UI.

**Comment by aocenas** [comment]
@torkelo what is the status for this? Did anybody start working on this or is this planned for later?

**Comment by torkelo** [comment]
no status update. It's on the 7.2 roadmap, might be something we can start during or late summer

**Comment by eyakimov-bbg** [comment]
Was quite surprised to find that this doesn't exist, I often fall back to a explore workflow when triaging non trivial issues where a dashboard doesn't quite make sense. It would be really great to be able to export data just like you can for any other table/graph today.
