### ISSUE TITLE
Rendering Timeout with Grafana Render Plugin

### ISSUE THREAD

**Issue by asaivan** [grafana/grafana#25165]
**What happened**:
Image render and upload to Slack times out

**What you expected to happen**:
Image renders and uploads to Slack

**How to reproduce it (as minimally and precisely as possible)**:
On my server with 4 GB memory, trigger alert that has upoad to Slack configured

**Anything else we need to know?**:
This was working fine with the Phantom.JS renderer

**Environment**:
- Grafana version: 7
- Data source type & version: MySQL
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome latest, Windows 10
- Grafana plugins: Image Renderer Plugin
- Others:
`t=2020-05-27T13:10:03-0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=3 newState=alerting prev state=pending
t=2020-05-27T13:10:03-0700 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/iUEjwQAWk/agiot-graphs?orgId=1&panelId=30"
t=2020-05-27T13:10:03-0700 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"http://localhost:3000/d-solo/iUEjwQAWk/agiot-graphs?orgId=1&panelId=30&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/aefZ5RYvkWVHuUIzoU2S.png\" renderKey:\"4aom2Z4B0z45bFAPv816U9kOccCAlPey\" domain:\"localhost\" timeout:15 "
t=2020-05-27T13:10:18-0700 lvl=info msg="Rendering timed out" logger=rendering renderer=plugin
t=2020-05-27T13:10:18-0700 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=3 error="Timeout error. You can set timeout in seconds with &timeout url parameter"
t=2020-05-27T13:10:18-0700 lvl=info msg="Executing slack notification" logger=alerting.notifier.slack ruleId=3 notification="Slack Alerts"
t=2020-05-27T13:10:18-0700 lvl=info msg="Uploading to slack via file.upload API" logger=alerting.notifier.slack`

**Comment by torkelo** [comment]
Does this happen to al server side image renderings? Can you try using the share modal for a panel and the direct link to rendered image link

**Comment by asaivan** [comment]
Thanks for your response,

I can get the image directly via the link provided in the debug logs, changing the localhost address to the FQDN of the server.

Asai

**Comment by asaivan** [comment]
Hello, just checking if you have any more insight on this?

**Comment by skylite21** [comment]
I have the same problem on grafana 7.1.3. I'm using grafana-image-render from the same host where grafana is running, and sometimes the image is not rendered. 

```grafana-server[188419]: t=2020-08-17T15:19:04+0200 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"http://localhost:3000/d-solo/W1MEaoSMk/alerting?orgId=1&panelId=3&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/uxbiBJlFRWrd2RY4vV8L.png\" renderKey:\"bSFOU6JGdhFfgiNBbueRtJQivTzN0BEr\" domain:\"localhost\" timeout:15 "```

I have no idea where the timeout:15 is coming from and how to change it. I assume if I could increase the timeout this would be resolved because I also see: 
```
msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=2 error="Timeout error. You can set timeout in seconds with &timeout url parameter"
```
Only problem is I do not have a &timeout parameter because I do not have a URL since the image renderer is running on localhost...

**Comment by asaivan** [comment]
Is there any way to change the timeout parameter so that queries that take a long time to build graphs will not time out?  This has been confirmed as the cause of the problem.  Optimizing database indexes helps, but still sometimes the renderer times out waiting for the graphs to build.

**Comment by Blackbaud-ChrisBlythe** [comment]
I'm also hitting a similar issue... and would love to know where/how to adjust that 15 sec timeout.

**Comment by tg44** [comment]
After 4 months it is still an issue for some of us. My alerts are not as urgent that they can't wait out even a minute rendering time, but it would give a lot of context if I would get the image.

**Comment by asaivan** [comment]
Yes, we have had to turn off sending images to slack because of frequent timeouts.  It's too bad that we can't adjust a simple parameter like this.

**Comment by midiwidi** [comment]
I have that issue too. Would be great if the timeout would be adjustable somewhere.

**Comment by ajimix** [comment]
Same problem here, having timeouts all the time 😩

**Comment by dg-nvm** [comment]
Anyone know where timeout parameter from Grafana is coming from ?

**Comment by dg-nvm** [comment]
maybe from here:
```go
timeout := setting.AlertingNotificationTimeout / 2
```
