### ISSUE TITLE
Feature request : Add suggest and auto complete for user list

### ISSUE THREAD

**Issue by Othyus** [grafana/grafana#2517]
Hi,
when we want to add user to organization, we must type username or email.
it will be more userfriendly to have usernames suggested when input get focus

Use case :
I must add user, but he has a really tricky name and i forget how to write the name,
 with this feature, I can retrieve the user.

Thanks

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by daniellee** [comment]
The UX has changed and I don't think this feature request is relevant anymore (though there are lots of improvements we can make to user management). Closing this issue for now but feel free to comment on this issue to clarify why this is needed and upvote it.
