### ISSUE TITLE
Make it possible to disable ARN authentication for Cloudwatch

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#25179]
Some users get confused about the ARN authentication setting when using Hosted Grafana. Since ARN is not available for Hosted Grafana users it would be desirable to turn it off on the datasource edit page.

**Comment by patstrom** [comment]
I don't really understand what disable ARN authentication means but PR https://github.com/grafana/grafana/pull/23439 addresses a lot of things with the CloudWatch authentication. I think it addresses this issue as well.

**Comment by bergquist** [comment]
The idea is to remove ARN as a possible authentication method with config settings. On our hosted Grafana service customers cannot use ARN since it's in our infra. This caused some confusion for our customers.

**Comment by sunker** [comment]
Makes sense. @bergquist any input on how to disable this? env variables, ini.file, check host etc.

**Comment by sunker** [comment]
fixed in https://github.com/grafana/grafana/pull/31805
