### ISSUE TITLE
e.data.data is undefined for Prometheus Graph dashboard with 2 targets

### ISSUE THREAD

**Issue by povilasv** [grafana/grafana#25172]
**What happened**:

If add two rate queries in graph panel it breaks.

![image](https://user-images.githubusercontent.com/22289110/83095198-630efd80-a0ab-11ea-8752-c07ac88f2489.png)

Red corner error shows `e.data.data is undefined`

If I leave either one of the queries it works:

![image](https://user-images.githubusercontent.com/22289110/83095263-981b5000-a0ab-11ea-8182-3e8d3dbd42a7.png)

I removed the top query, it works:

![image](https://user-images.githubusercontent.com/22289110/83095288-a4071200-a0ab-11ea-9f11-b16005902fc3.png)

I removed the bottom query, it works:

![image](https://user-images.githubusercontent.com/22289110/83096243-dca7eb00-a0ad-11ea-8b56-470cacb676b2.png)

**What you expected to happen**:

Things to work ;)

**How to reproduce it (as minimally and precisely as possible)**:

2 prometheus rate queies in a single dashboard probably?

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0-f0065364pre (6a4f45625c)
- Data source type & version: Prometheus 
- OS Grafana is installed on: image: grafana/grafana:master
- User OS & Browser: firefox, linux

**Comment by torkelo** [comment]
We have no other similar reports, and unable to replicate. Does both queries work in isolation? Can you open query inspector and show the raw response from your queries?

**Comment by povilasv** [comment]
I think I did something wonky, can't reproduce it anymore :/
