### ISSUE TITLE
CloudWatch Logs: Log Group not saved in panel settings when saving dashboard

### ISSUE THREAD

**Issue by niklasR** [grafana/grafana#25185]
**What happened**:
- Editing a log type panel with a CloudWatch Logs data source
- Set a log group
- Save the dashboard
- Close the dashboard
- Come back to the dashboard, edit the panel
- The "log group" field in the panel settings is empty and has to be filled out again
- This does not seem to affect fetching results, only the edit mode, so the log group is saved somewhere, just not displayed

**What you expected to happen**:
Display the log group that's been saved with the panel when editing the panel

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
-
**Environment**:
Grafana version: Grafana v7.0.1 (ef5b586)
Data source type & version: CloudWatch
OS Grafana is installed on: CentOS 7
User OS & Browser: Mac OS 10.15.4, Chrome 83.0.4103.61
Grafana plugins: NA
Others: NA

**Comment by DarkZatarra** [comment]
I encountered the same bug but for me there is a difference, since I am facing this first time it keeps saying that I need to set up a log group (it is not saved)

**Comment by rickbowden** [comment]
Same issue for me too.

Grafana version: Grafana v7.0.1
Data source type & version: CloudWatch
OS Grafana is installed on: Windows Version	10.0.17134 Build 17134
User Browser: Chrome Version 83.0.4103.61 (Official Build) (64-bit)

**Comment by hristaki** [comment]
Can confirm the problem too

![image](https://user-images.githubusercontent.com/4948421/83884006-8ccbc280-a744-11ea-908e-bc03ca4515e5.png)

**Comment by Brolywood** [comment]
We have the same issue with v9.1.8 (3c0c14de5d) version

**Comment by hristaki** [comment]
I can confirm the problem in v9.2.0 as well

![Kapture 2022-10-17 at 11 55 48](https://user-images.githubusercontent.com/4948421/196148398-9dd6f13e-da6a-4a09-a400-91b48aaa7abe.gif)

**Comment by rkul** [comment]
Hello @hristaki 
Did you find how to fix that? We faced with the same issue and there is nothing in logs and in browser dev console...

**Comment by hristaki** [comment]
Hi @rkul ,
Yes. You just need to update to the newest version
