### ISSUE TITLE
Cloudwatch datasource, add authentification with role assume

### ISSUE THREAD

**Issue by rgarrigue** [grafana/grafana#25184]
**What would you like to be added**:

As explained in [this doc](https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#iam-roles), [AWS authentification through assuming role](https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_use_switch-role-cli.html) isn't supported. I would like it to be supported.

**Why is this needed**:

It's a kind of authentication which is quite recommended (as far as I know, I'm not an AWS expert), at least this is the one I use for everything, both users and technicals account, worked well so far.

**Comment by aknuds1** [comment]
We're working on supporting CloudWatch authentication through rule assumption in https://github.com/grafana/grafana/pull/23439.

**Comment by rgarrigue** [comment]
@aknuds1 I've browsed in the PRs, it's not clear if this is in progress or not ?
