### ISSUE TITLE
Failed to start renderer plugin: Unrecognized remote plugin message (Grafana - 7.0.0-1)

### ISSUE THREAD

**Issue by dgdevops** [grafana/grafana#25180]
Hello Team,

I am trying to upgrade Grafana version from 6.7.1 to 7.0.1 on my k8s cluster.
The Grafana is installed via HELM chart and the grafana-image-renderer plugin is installed as a part of the chart. When the Grafana is deployed with version 6.7.1 the pods with the containers come up perfectly and no issues are observed, however when I change the image.tag in the chart to 7.0.1 in the hope to upgrade the instance to 7.0.1 the pods get redeployed but they end up in CrashLoopBackOff state in around 20 seconds. Based on the container logs Grafana starts installing plugins and I could see a log entry "✔ Installed grafana-image-renderer successfully", however the container stops with "grafana stream closed" message. Before that log message I can see the following:

msg="Some plugins failed to load" logger=plugins errors="[Failed to register plugin:\n    github.com/grafana/grafana/pkg/util/errutil.Wrap\n        /root/msg="Stopped RenderingService" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply
msg="plugin failed to exit gracefully" logger=plugins.backend pluginId=grafana-image-renderer 
msg="Stopped Stream Manager"
msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=
msg="A service failed" logger=server err="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to b
msg="Server shutdown" logger=server reason="Failed to start renderer plugin: Unrecognized remote plugin message: \n\nThis usually means that the plugin is either invalid or simply\nneeds to ││ grafana stream closed

I also tried using Grafana 7.0.0 docker image, however I could not see any improvement.
I stumbled upon the following issue on GitHub (https://github.com/grafana/grafana/issues/21874), however I think my issues is not related to IPv6 as with version 6.7.1 the image renderer start perfectly with address=[::]:3000

**What happened**:
Tried to upgrade Grafana to 7.0.1 from 6.7.1

**What you expected to happen**:
Expected to see the grafana-image-renderer plugin come up

**How to reproduce it (as minimally and precisely as possible)**:
1) Install Grafana using HELM chart to a k8s cluster (with grafana-image-renderer plugin)
2) Make sure to use image 7.0.0 or 7.0.1
3) Connect Grafana to a MySQL database

**Anything else we need to know?**:
-

**Environment**:
- Grafana version: 7.0.0 & 7.0.1
- Data source type & version: -
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Windows & Chrome
- Grafana plugins: grafana-image-renderer (2.0.0)

**Comment by Tim-Schwalbe** [comment]
did you find a solution? I just ran into the same issue and now I can not even terminal into the grafana pod  to delete the plugin:/

**Comment by dgdevops** [comment]
@Tim-Schwalbe , for now the only workaround I have is to remove that plugin from the helm chart's plugins array and redeploy Grafana.

**Comment by dgdevops** [comment]
@Tim-Schwalbe, the developers of the grafana-image-renderer plugin suggested to use remote rendering service to avoid the dependency on the plugin. Just tested the remote-rendering service and I can confirm it worked perfectly with Grafana 7.0.1.

**Comment by DmitriyMurzin** [comment]
I just ran into the same issue(

**Comment by advorsky73** [comment]
same

**Comment by dgdevops** [comment]
Hello Everyone,
I can confirm that the remote image renderer works perfectly. I have been running it for over a month now without any issues. I even upgraded to 7.0.4 and it went smoothly.
