### ISSUE TITLE
Explore  link does not have the evaluate variable value  if it is used for retention

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#25183]
**What happened**:
No data is shown cause the retention was still a variable name not a value and Explore does not have any clue about variables. 
Explore view also did not show any error message for the invalid query. 
When I looked the http request response then there it was explained :
{"results":[{"statement_id":0,"error":"retention policy not found: $retention"}]}

**What you expected to happen**:
I see the same Graph I was able to see in the panel view.

**How to reproduce it (as minimally and precisely as possible)**:
* create a query variable for any influxdb datasource  with query SHOW RETENTION POLICIES
* create a Graph panel  where you use the created variable as retention policy in panel query. Make the panel to show some data.
* click on the panel header and select Explore

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Influxdb 1.8.0
- OS Grafana is installed on: RH7.7
- User OS & Browser:Win10 Chrome 81.0.4044.138
- Grafana plugins:
- Others:

**Comment by Estrax** [comment]
Hi @gjemp! In Explore, you should see an interpolated value of the variable you used. Can you post there the following things, please? It's going to help us debug the issue. 
- screenshot of the query from the dashboard panel,
- screenshot of the query you get after moving to Explore by clicking on the panel header,
- the definition of your variable.

**Comment by gjemp** [comment]
![image (1)](https://user-images.githubusercontent.com/4919667/83852894-27b0a680-a71d-11ea-9a5c-f5bbebd9bdc1.png)
![image (2)](https://user-images.githubusercontent.com/4919667/83852904-2aab9700-a71d-11ea-9cb1-63d2c4d140f1.png)
![image](https://user-images.githubusercontent.com/4919667/83852910-2c755a80-a71d-11ea-9a4e-1fd53d9d70f0.png)

**Comment by Estrax** [comment]
@gjemp Thanks for providing us with additional details. One more thing: can you go inside the retention variable and make a screenshot of its definition? The currently posted view doesn't include all the details about that variable.

**Comment by Estrax** [comment]
@gjemp Thanks for providing us with additional details. One more thing: can you go inside the retention variable and make a screenshot of its definition? The currently posted view doesn't include all the details about that variable. Do you have `Include All option` selected?

**Comment by gjemp** [comment]
![image](https://user-images.githubusercontent.com/4919667/83855666-15d10280-a721-11ea-9cc3-6833dbde16b8.png)

**Comment by Estrax** [comment]
@gjemp Thanks again for submitting an issue and providing us with the details! Fixed in #25500.
