### ISSUE TITLE
v7 New table panel missing many old features?

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25187]
**What happened**:
I don't know if this is really an issue report or feature request/s or a bit of both but the new v7 table panel _seems_ to be missing a lot of features of the old table panel.

I may be missing where these options are (but I am not the only one) but the following seem to be no longer possible:

- Rows per page (paging).
- Font size.
- Render value as link.
- Sanitize HTML (this was one of the most powerful features for me).
- Hide columns.

I know I can (and am) just using the old table panel, but will that remain available in future releases?

**Anything else we need to know?**:
I realise the table paging has been removed as the table is now meant to infinitely scroll, but for me this did not even work efficiently enough with large tables with complex queries. It would be good to have a choice of paging vs the new infinite scroll.

The old table panel is incredibly powerful, you can have tables with (clickable) images, links, icons, custom fonts/colours, whatever you want. With the new table panel it seems not so much :-(

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu v19/10
- User OS & Browser: Ubuntu v20.04 Firefox v76.0.1
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
* Font size might come in a later update 
* Paging is not needed in this new panel as it has virtualized rows (sort of infinite scroll), 
* Render value as link is supported via data links (can be added in the Field or Overrides tab)
* Sanitize Html https://github.com/grafana/grafana/issues/24482
' Hide columns: Use organize fields transform (in Transform tab beside query tab)

**Comment by eriklouise** [comment]
Hi @torkelo,

Regarding the hide column trick using field transformation, it's not a visibility hidden or collapsed as it is done using CSS but the hidden column is simply not rendered so it's not possible to involve its values into an URL or something else (my use case is displaying a friendly name in a column but using an UUID in the associated link).
Are you aware of a workaround or a solution on this point ?

Regards.

**Comment by fcremer2inv** [comment]
@torkelo

Seconding feedback by @eriklouise
In my case I want to select a name and a metric from my datasource, along with an ID. The ID needs to be used in a link generated per table row, but has to be hidden from the table itself.

**Comment by kale1d0code** [comment]
I can confirm this is still broken in Grafana 8

using the filter transform to remove a column of ids which are used in a data link removes the ids from the datalink

**Comment by industrial64** [comment]
The font size for the new tables is still outstanding (forcing most users, such as myself to modify the global font size in the .js manually). Grafana 8 has no obvious option to revert to the (old) table - making this transition very confusing given all the other missing features (like colouring the entire row, and not just a single cell)
