### ISSUE TITLE
Available dashboard list varies when opening and closing list version 1.9.0

### ISSUE THREAD

**Issue by jsully74** [grafana/grafana#2518]
Hi All,
We recently imported some dashboards created in the lab on the same 1.9.0 configuration and also deleted some of the previously created dashboards and now the dashboard list is not displaying correctly.  On the dashboard list below we imported the lower case dashboard names and removed some of the upper case dashboard names.  If we close the dashboard list by clicking on the folder icon in top right corner and then open again by clicking on the folder icon in the top right corner a different list will be populated.  Please see the differences below between screenshot 1 and screenshot 2.

![screenshot1](https://cloud.githubusercontent.com/assets/13799802/9278161/e35c2748-427c-11e5-989c-f283813c11f7.PNG)
![screenshot2](https://cloud.githubusercontent.com/assets/13799802/9278187/1d3a7b4a-427d-11e5-9699-6c765ffd6766.PNG)
![manualdelete](https://cloud.githubusercontent.com/assets/13799802/9278288/db54d684-427d-11e5-933c-367809f8a858.PNG)
![stillinlist](https://cloud.githubusercontent.com/assets/13799802/9278302/fb42fbf6-427d-11e5-8dcf-7e3a6088f792.PNG)
![dashboardloadfailed](https://cloud.githubusercontent.com/assets/13799802/9278324/1d1fcb8c-427e-11e5-8281-b734ef75da96.PNG)

Is there a back-end way to just blow away the available dashboards from the list and re-import?

**Comment by torkelo** [comment]
Are you having some caching infront of elasticsearch? No one has reported anything like this before so not sure what could be wrong with your Elasticsearch instance. 

I recommend upgrade to 2.1 :)

**Comment by jsully74** [comment]
I’m not aware of any caching that has been setup.  Is there any way to remove the dashboard list other than the GUI so we can just rebuild our dashboards?

**Comment by torkelo** [comment]
The dashboard list is generated from a search request to elasticsearch, where the dashboards are stored.

**Comment by jsully74** [comment]
I appreciated your responses.  Is there a back-end way to wipe out the current available dashboards in elasticsearch?

**Comment by torkelo** [comment]
yes, delete the grafana-dash index, you will loose ALL YOUR DASHBOARDS,

**Comment by jsully74** [comment]
I removed the following entire directory but my dashboard lists are still populated when I go to the Grafana GUI.  Am I removing the correct directory to delete the grafana-dash index?

/var/lib/elasticsearch/elasticsearch/nodes/0/indices/grafana-dash

**Comment by torkelo** [comment]
looks ok, unless you have a clustered elasticsearch with many nodes?

**Comment by jsully74** [comment]
I have found 2 machines in my setup that contain grafana-dash directory.

I made a backup and removed the /var/lib/elasticsearch/elasticsearch/nodes directory from both of the machines and the dashboard list still populates.  It must be residing in another location.

**Comment by jsully74** [comment]
Yes, looks like I do have a clustered elasticsearch with 2 nodes.  I see identical directories on 2 separate virtual machines.

VM01
[cid:image001.png@01D0DF28.8F60DC40]

VM02
[cid:image002.png@01D0DF28.8F60DC40]

Really struggling to get back to just a base install so I can start loading new dashboards from scratch.

Any other suggestions to try to get the dashboards wiped out, or get back to base install would be appreciated.

Thank you,
Jim

**Comment by torkelo** [comment]
just change the name of the elasticsearch dashboard index in config.js, grafana will create a new index in Elasticsearch first time you save a dashboard.

**Comment by jsully74** [comment]
Thank you very much Torkel, changing the name of the elasticsearch dashboard index in cofig.js solved the issue.
