### ISSUE TITLE
Adding a query doesn't update the counter on the Query tab

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#25196]
**How to reproduce it (as minimally and precisely as possible)**:

1. Open the editor on any panel.
2. Click '+ Query'.
3. **The query counter doesn't update**.
4. Go to the Transformations or the Alerts tab.
5. **The query counter is incremented** only when you navigate away from the Query tab.

**Environment**:
- Grafana version: v7.0.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
This is also true for alerts and transformations.
