### ISSUE TITLE
UI crashes when switching from and back to Transform tab in panel editor

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#25197]
**How to reproduce it (as minimally and precisely as possible)**:

1. Open the panel editor (the datasource doesn't matter, you can create a new panel with TestData DB)
2. Go to the **Transform** tab.
3. Click any transformation. You don't need to configure anything.
4. Go back to the **Query** tab.
5. Go back to the **Transform** tab.

The `main-view` div blanks out with an error and a stack trace.

> An unexpected error happened
> TypeError: n.state is null

**Environment**:
- Grafana version: v7.0.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed by #25152 , will come in patch 7.0.3 next week,
But I would suggest download nightly to get fix right away: https://grafana.com/grafana/download/7.1.0-cdcd1ef9pre

Sorry for this, we added integration test for transforms so this does not happen again
