### ISSUE TITLE
Docs feedback: /tutorials/stack_guide_graphite.md

### ISSUE THREAD

**Issue by tasoss** [grafana/grafana#25198]
Hello.
"Sending metrics to StatsD" is empty.
Any ideas?
Thanks!

**Comment by oddlittlebird** [comment]
@marcusolsson ?

**Comment by marcusolsson** [comment]
Looks like never was written in the first place. Here's the original commit from... 5 years ago:
https://github.com/grafana/grafana/commit/2f849be9d8fefaea6c9dc858a68cc9d4ffe770b7#diff-c3546302c5e61c4c4a31b42d7e6d19e9

I think it's safe to remove the heading :)

**Comment by tasoss** [comment]
thanks for the info
