### ISSUE TITLE
Query editor dropdown menu goes crazy when there is not enough space in the browser window

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#25193]
**What happened**:
When the browser page has not enough space to show a dropdown (of the query editor in my case) menu the dropdown itself goes crazy by opening and closing at high speed

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
While Creating a second query for influxDB, with the query builder at the bottom of the screen the dropdown for choosing the function goes crazy on certain voices (the ones which options don't fit in the browser window)
See attached gif.
![2020-05-28_17-19-10](https://user-images.githubusercontent.com/12230314/83160595-b1ea8080-a107-11ea-928a-55521e04ba81.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: Windows Server 2019 Standard
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: 
- Others:

**Comment by peterholmberg** [comment]
@Trovalo not able to reproduce this. Is this still an issue on 7.1.3? Please reopen if so.

**Comment by Trovalo** [comment]
Can confirm that in version 7.2 this does not happen
