### ISSUE TITLE
v7.0.1 Cannot add any transformations, get TypeError

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25194]
**What happened**:
When I click on any of the Transformation options nothing at all happens. The tab still just says `Transform 0`.
When I then click the `Query` tab the transform tab then shows `Transform 1`
When I then click back to the transform tab I get a Grafana error page `An unexpected error happened` with the following details:
```
Grafana
An unexpected error happened
TypeError: n.state is null

    in t
    in div
    in Ma
    in div
    in an
    in div
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in t
    in div
    in div
    in t
    in x
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l
```

**How to reproduce it (as minimally and precisely as possible)**:
- Click `Add Panel` then `Add new panel`.
- I chose Grafana data walk as data source but does not seem to matter which source.
- I kept the default graph visualization but does not seem to matter which panel.
- Click the `Transform` tab and click `Select` on any transformation such as `Organize fields`.

**Anything else we need to know?**:
This is 100% reproducible for me. 
Tried restarting grafana-server.
Tried 2 browsers (Firefox & Chrome).
Tried disabling browser add-ons.
I cannot see any errors appear in the syslog or grafana.log
I can see some errors in the browser console (I have put them below).

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Tried with sources: MySQL, Prometheus, Grafana data walk etc.
- OS Grafana is installed on: Ubuntu v19.10
- User OS & Browser: Ubuntu v20.04 Firefox 76.0.1 Chrome v 83.0.4103.61
- Grafana plugins:
- Others:

Browser console errors from Firefox:
`TypeError: "n.state is null"
    renderTransformationEditors TransformationsEditor.tsx:112
    value TransformationsEditor.tsx:203
    React 13
        Ka
        Ya
        Su
        yc
        hc
        ic
        Ko
        unstable_runWithPriority
        Wo
        Ko
        Yo
        ue
        Er
react-dom.production.min.js:196:194
    React 16
        fu
        callback
        Oi
        mi
        mc
        unstable_runWithPriority
        Wo
        gc
        ic
        Ko
        unstable_runWithPriority
        Wo
        Ko
        Yo
        ue
        Er
`

Browser console errors from Chrome:
`TypeError: Cannot read property 'data' of null
    at t.n.renderTransformationEditors (TransformationsEditor.tsx:112)
    at t.value (TransformationsEditor.tsx:203)
    at Ka (react-dom.production.min.js:181)
    at Ya (react-dom.production.min.js:180)
    at Su (react-dom.production.min.js:261)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at KqkS.t.unstable_runWithPriority (scheduler.production.min.js:18)
fu @ vendors~app.7c9669f9d715261b5af3.js:2
i.componentDidCatch.r.callback @ vendors~app.7c9669f9d715261b5af3.js:2
Oi @ vendors~app.7c9669f9d715261b5af3.js:2
mi @ vendors~app.7c9669f9d715261b5af3.js:2
mc @ vendors~app.7c9669f9d715261b5af3.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.7c9669f9d715261b5af3.js:2
Wo @ vendors~app.7c9669f9d715261b5af3.js:2
gc @ vendors~app.7c9669f9d715261b5af3.js:2
ic @ vendors~app.7c9669f9d715261b5af3.js:2
(anonymous) @ vendors~app.7c9669f9d715261b5af3.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.7c9669f9d715261b5af3.js:2
Wo @ vendors~app.7c9669f9d715261b5af3.js:2
Ko @ vendors~app.7c9669f9d715261b5af3.js:2
Yo @ vendors~app.7c9669f9d715261b5af3.js:2
ue @ vendors~app.7c9669f9d715261b5af3.js:2
Er @ vendors~app.7c9669f9d715261b5af3.js:2`

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/25152 , will come in patch 7.0.3 next week, 
But I would suggest download nightly to get fix right away: https://grafana.com/grafana/download/7.1.0-cdcd1ef9pre 

Sorry for this, we added integration test for transforms so this does not happen again
