### ISSUE TITLE
Grafana refuses to start

### ISSUE THREAD

**Issue by FredSUEE** [grafana/grafana#2520]
Hi I'm new to Grafana and just made it work on my virtual machine. But then when I installed Grafana on my Linux server and tried to start it, it just showed me "failed". Here's what I got in log:
~~~
2015/08/14 11:40:44 [I] Starting Grafana
2015/08/14 11:40:44 [I] Version: 2.1.1, Commit: v2.1.1, Build date: 2015-08-11 01:48:19 -0700 PDT
2015/08/14 11:40:44 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/08/14 11:40:44 [I] Database: sqlite3, ConnectionString: file:/var/lib/grafana/grafana.db?cache=shared&mode=rwc&_loc=Local
2015/08/14 11:40:44 [I] Migrator: Starting DB migration
2015/08/14 11:40:44 [I] Migrator: exec migration id: create index IDX_org_user_org_id - v1
2015/08/14 11:40:44 [migrator.go:134 func·001()] [E] Migrator: exec FAILED migration id: create index IDX_org_user_org_id - v1, err: index IDX_org_user_org_id already exists
2015/08/14 11:40:44 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: index IDX_org_user_org_id already exists
~~~

Sorry if this is a very simple problem. And I will provide more details if that's needed.

**Comment by torkelo** [comment]
This i s very strange. The error means that something in the database schema migration engine has been applied twice or in the wrong order, but no one else has reported issue with this early migration. Have you modified the sqlite3 database somehow or removed things from the migration_log table?

**Comment by FredSUEE** [comment]
I haven't done anything to the database or the configuration. Note that I made it work on my virtual machine and then followed the same procedure. Since it has something to do with the id, could it be because the virtual machine and the linux server link to the same account in my company ?

**Comment by torkelo** [comment]
No, the error says that the a database schema migration cannot be applied because it is already applied.

If you remove grafana.db (sqlite3 database) and try again?

**Comment by FredSUEE** [comment]
Yes, I remove the grafana.db and start again, it works. Thanks a lot.

**Comment by lotux** [comment]
I also have this issue, it doesn't happen all the times on fresh installation, db doesn't exist prior to installation

**Comment by olibob** [comment]
I just stumbled upon the same issue using a Virtualbox docker machine.

I just mapped uid/gid 1000 to grafana. Here's my Dockerfile

```
FROM grafana/grafana

# Docker machine uid and gid fix
RUN userdel grafana
RUN groupadd -g 1000 grafana
RUN useradd -M -d /usr/share/grafana -u 1000 -g 1000 -s /bin/false grafana
```

**Comment by torkelo** [comment]
It needs read access to/var/lib/grafana and /var/log/grafana as well

**Comment by mcbain** [comment]
I have the same problem with the 3.0.1, 2.6.0 when started from docker and linked to a simple mysql container.  

```bash
grafana-1 | 2016-05-19T11:55:11.178657285Z 2016/05/19 11:55:11 [I] Database: mysql
grafana-1 | 2016-05-19T11:55:11.178893978Z 2016/05/19 11:55:11 [I] Migrator: Starting DB migration
grafana-1 | 2016-05-19T11:55:15.368523214Z 2016/05/19 11:55:15 [log.go:84 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: dial tcp 10.7.0.18:3306: getsockopt: no route to host
```

The mysql container is running for a while so the `no route to host` is even more strange?!

**Comment by bergquist** [comment]
@mcbain are you sure the linking is working? could you test this in any other way?

**Comment by mcbain** [comment]
@bergquist My current workaround is to wait 5sec before starting grafana.... this seems to work (10+ deployments succeeded)

```docker
FROM grafana/grafana:3.0.2

RUN echo "#!/bin/bash" > /start
RUN echo "echo 'Sleeping 5sec'; sleep 5; /run.sh" >> /start
RUN chmod +x /start

ENTRYPOINT ["/start", "dummy"]
```

**Comment by bergquist** [comment]
@mcbain Ah! good info :) Grafana expects the sql server to be started when starting. I guess the error message should be improved for this case.

**Comment by 492162921** [comment]
谢谢，成功解决了该问题。 因为 conf 中配置了 mysql数据库。 数据库出现了故障，导致了Grafana无法开启。
