### ISSUE TITLE
Loki: label_values() - Use series API instead of labels API

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#25205]
**What would you like to be added**:

Ability to filter variables in loki using other variables. 

Ie in prometheus i can use 
```
label_values(disk_used_percent{host=~"$server"},path)
```
Where $server is
```
label_values(cpu_usage_idle, host)
```
To get list of mountpoints on this specific server. 

Will be nice to have same feature for loki, for example i have promtail collecting systemd journal on all machines, and needless to say they have different services running. Using label_values(unit) lists tons of services and it's not easy to understand how they correlate to specific servers.

Looks like loki already have matching functionality built-in, providing only units running on that node in case i already specified host:

![image](https://user-images.githubusercontent.com/84462/83216214-65d42600-a171-11ea-8c52-cb66a5948176.png)

**Why is this needed**:
Much cleaner selectors in dashboards and overall usability improvement

**Comment by Hybrid512** [comment]
Definitely want this one !

**Comment by aocenas** [comment]
For future reference. `label_values` is usable only in prometheus template variables and has a special implementation to go through different endpoint to get the values. So something similar will need to be implemented also for Loki.

**Comment by aocenas** [comment]
I may have been mistaken and the label_values seems to be implemented to some extent https://github.com/grafana/grafana/blob/eafc132d3dca0f42cf81c4b49b12965a5c4019e6/public/app/plugins/datasource/loki/datasource.ts#L287 but seems like it ignores a case when it should work on top of metrics endpoint like here https://github.com/grafana/grafana/blob/7e8bd0c1b77f7b48fdde21cf8a5c9130d57fef00/public/app/plugins/datasource/prometheus/metric_find_query.ts#L29 and not sure if we use this processing for all querying or not.

**Comment by cyriltovena** [comment]
IMHO, it should use the series API. That way we can use `label_values({app="foo", namespace="prod"},instance)`.

**Comment by cyriltovena** [comment]
Definitively agree with you @aocenas we need a special case for Loki.

**Comment by wardbekker** [comment]
+1 Would like to be able to queries like `label_values({filename="/var/log/nginx/json_access.log"} | json, status)`

**Comment by lux4rd0** [comment]
+1 This feature request would be great - label_values({compose_service=~$service, compose_project=~$project}, container_name) - nested label filtering!

**Comment by cyriltovena** [comment]
Gentle bump, I think this is an important feature.

I think at first we can use the series API for those 

```
label_values({compose_service=~$service, compose_project=~$project}, container_name)
```

May be later we can think of  `label_values({filename="/var/log/nginx/json_access.log"} | json, status)` but currently no API would allow that.

**Comment by treksler** [comment]
## using loki as datasource for variables

# this does not work at all
label_values({namespace="ingress-nginx"}|json|nginx_host!=""}, nginx_host)

# this returns all namespaces, when it should obviously only return ingress-nginx
label_values({namespace="ingress-nginx"}|json|nginx_host!=""}, namespace)

loki dashboards are kind of useless with this bug, no?

**Comment by LEDfan** [comment]
We also bumped into this limitation today, and would be very happy if this would be implemented some day.
The workaround for using Prometheus metrics isn't working for us, since we need to filter based on Kubernetes annotations which are not exposed by `kube-state-metrics` we are using.

**Comment by matiasba** [comment]
I just run into this problem. It makes very difficult to offer this as a log solution to my team if I cant make a simple dashboard for them to search on. Hope It can be fixed soon :)

**Comment by jorgelbg** [comment]
A (partial) workaround that I've found for this is to have the Loki instance also configured as a Prometheus datasource in Grafana (create a Prometheus datasource and add the `/loki` path in the URL, `http://$LOKI_HOST:$LOKI_PORT/loki`). Using that datasource in your variable with a query like:

```ruby
label_values({domain=~"jorgelbg.me"},  status)
```

should work.

This works partially because `label_values` doesn't accept a full-featured query, only a label matcher, meaning that it will only work for the labels available before using the `json` or `logfmt` parsers.

![image](https://user-images.githubusercontent.com/1291846/108536910-45d72a80-72dd-11eb-97e6-9b4e05f6f697.png)

**Comment by lux4rd0** [comment]
Ha! Nice - I love it! That let's me do something like

`label_values({compose_project="$compose_project"}, compose_service)`

To drill down without using Prometheus! Thanks for the tip!!

** off to update my Dashboard variables **

**Comment by alanhe** [comment]
We have a hierarchy of Account -> Application -> Pod. We would like to be able to define variables like
```
label_values(account)
label_values({account="$account"}, application)
label_values({account="$account", application="${application}"},  pod)
```
to achieve cascading change.

**Comment by myselfghost** [comment]
This feature still doesn't work。loki  2.2.1, grafana 7.5.6

**Comment by pgassmann** [comment]
@myselfghost it works for us. Try using regex queries for nested values.
We have installed loki 2.2.1 and grafana 7.5.5.

The dashboard above uses label_value queries like `label_values({host=~"$host",compose_project=~"$project"}, compose_service)`
![image](https://user-images.githubusercontent.com/460192/118549407-b2868780-b75b-11eb-8e89-10f99ccda44a.png)

**Comment by loganmc10** [comment]
I'm on Grafana Cloud and it doesn't seem to work, any query just seems to be ignored and it returns all label values.

I also haven't seen anything in the changelog for Loki or Grafana that would indicate that this has been solved

**Comment by pgassmann** [comment]
@loganmc10 Oh, I didn't realize that the values were not filtered.

**Comment by timurkhisamov** [comment]
+1 label_values doesn't filter. Outputs all values of label, not per host.

**Comment by sherifkayad** [comment]
Hey guys .. are there any plans to work on this soon? I think for us it's also a critical use case to have a logging dashboard that's supporting nested label selection e.g. `namespace` -> `service` -> `pod` or `instance`

**Comment by isaiasanchez** [comment]
It works now with grafana 8.1.x and loki 2.3 (probably with previous version as well)

**Comment by slzzz** [comment]
> +1 label_values doesn't filter. Outputs all values of label, not per host.

+1

**Comment by daper** [comment]
> Gentle bump, I think this is an important feature.
> 
> I think at first we can use the series API for those
> 
> ```
> label_values({compose_service=~$service, compose_project=~$project}, container_name)
> ```
> 
> May be later we can think of `label_values({filename="/var/log/nginx/json_access.log"} | json, status)` but currently no API would allow that.

Sorry for commenting on closed issue...

Hey @cyriltovena, is there any issue/feature request/place to track the status of the feature that would allow to make pipeline queries for label_values?
