### ISSUE TITLE
Prometheus alertmanager for notification channel

### ISSUE THREAD

**Issue by admyavuzs** [grafana/grafana#25207]
Hello there.

I’m trying to create a notification channel as a type Prometheus alertmanager on Grafana. After selecting Prometheus alertmanager type, there is only 2 mandatory fields which are name and url. I simply filled these fields and tested the configuration which was also successful. But I have no idea the where the test message is gone.

In alertmanager I already have slack and mail configuration. My goal is using existing alertmanager slack and mail configuration and send alerts from Grafana to alertmanager.

I couldn’t find any useful documentation about this configuration? Should I also make some changes in alertmanager side? Or should I also need make changes in Grafana side. Could you please advise me how to do that? Thanks.

Grafana: 6.5
Prometheus AlertManager: 0.19.0
Prometheus: 2.13.1

**Comment by admyavuzs** [comment]
never mind. i solved

**Comment by BhaRgav-MoRadiya** [comment]
HI, im facing the same issue.How did you solve this?
