### ISSUE TITLE
Consolidate data from multiple data sources 

### ISSUE THREAD

**Issue by jaypatel8110** [grafana/grafana#25202]
Added the results from two data source and display combined results in a single graph 

I have two same queries and I want to monitor data from two different data source . I am unable to combine data from different Prometheus data source.

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Prometheus 
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome

**Comment by aknuds1** [comment]
Is this supposed to be a feature request?

**Comment by torkelo** [comment]
Use the mixed data source then you can issue queries to different datasources

**Comment by jramirezneira** [comment]
is this feature already available? I need to join two queries from different datasources (cloudwatch and elastiicsearch), but I haven´tn found the way to solve it
