### ISSUE TITLE
"Panel not found" when row is collapsed 

### ISSUE THREAD

**Issue by reidko** [grafana/grafana#25219]
I have an alert panel set to show 'all' alerts in a row on a dashboard. The issue is when I select an alert in the panel and the alert pertains to a panel that is in another "collapsed" row on the same dashboard, I get a "panel with id n not found" error. If I expand the row and select the alert, I get redirected as expected. I am not sure if this is working as designed or if it is considered a bug. 

I would expect to be redirected to the edit panel page even if the panel is contained in a row that is collapsed.

**How to reproduce it**:
1. Add two rows on a dashboard
2. Add alert panel in one row and graph in other row and set alert.
3. Collapse row that contains graph
4. Select alert in alert panel that pertains to the graph in collapsed row
5. Error should appear

**Environment**:
- Grafana version: 7.0.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: cloud hosted

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/25079
