### ISSUE TITLE
Problem with filtering large multi-valued variables (Grafana 7+)

### ISSUE THREAD

**Issue by S0bakaRU** [grafana/grafana#25211]
We have a variable on a dashboard. 
This variable contains multiple values (hundreds of hostnames) with an enabled multi-select option.
Because of a large number of values users always used filtering while choosing hostnames they needed.

After Grafana 7 released - filtering for multi-valued variable fields appears to be broken.

**What happened**:
The user clicks on a variable and sees a large list with a scrollbar.
User types the first letters of a needed item. Filtering works well - user sets preferred checkboxes. On top of the list, user sees a counter of selected values.

Then, without closing a list, user deletes typed letters and types another first letters for filtering to chose the next items - counter unexpectedly resets to zero. Previously selected items reset too. 

**What you expected to happen**:
On pre-7 versions of Grafana users could make filtering (by typing first letters) multiple times: to type first letters, to set checkboxes, to erase typed letters, to type next ones, to set next checkboxes - all the way to form a needed list of multiple items.

**How to reproduce it (as minimally and precisely as possible)**:
- create new dashboard
- create a variable with multiple distinct text values and selected option "Multi-value". 
Used method for multiple values ​​obtaining doesn't matter: problem reproduced as with queries, as even with custom type with comma-separated values.
- open variable's list on a dashboard, select one item by a checkbox (notify the counter increases)
- then without closing a list, try to filter items by typing name of next item (counter resets, previously selected items resets too). 

**Anything else we need to know?**:
Update 7.0.1 did not resolve the issue.

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: Doesn't matter
- OS Grafana is installed on: Debian Jessie
- User OS & Browser: Ubuntu 18.04 / Chrome 81.0.4044.138 / Firefox 76.0.1

**Comment by palsivertsen** [comment]
Any items not matched by the filter will be removed from selection:
![grafana-variable-bug](https://user-images.githubusercontent.com/11890143/83267596-bfb20b80-a1c4-11ea-941e-9f0f00e8ef8a.gif)

**Comment by V-A-S** [comment]
similar problem on almost the same configuration

**Comment by markus080402** [comment]
Are there any solution to this problem?

**Comment by palsivertsen** [comment]
I just upgraded from 7.0.1 to v7.1.5 (9893b8c53d) and there's no longer a problem.

**Comment by hugohaggmark** [comment]
@S0bakaRU @markus080402 @palsivertsen @V-A-S this [PR](https://github.com/grafana/grafana/pull/25119) has fixed this so I'm closing this issue for now, we can always reopen it if you think the issue still exists.

All the best
