### ISSUE TITLE
CI: Clearer strict null check errors

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#25218]
**What would you like to be added**:
When new Typesript strict null errors are created, I would like to clearly see in the CI which ones that have been added.

```
Executing './scripts/ci-frontend-metrics.sh'
Collecting code stats (typescript errors & more)
Typescript strict errors 728 exceeded 726 so failing build
'./scripts/ci-frontend-metrics.sh' returned 1.
 
```

**Why is this needed**:
For quicker fixes if they fail on master.

**Comment by torkelo** [comment]
This far from trivial, we would have to store the typescript output for master somewhere and then do a diff against that in the CI check

**Comment by torkelo** [comment]
would just plow through these errors and get rid of all instead :)

**Comment by aknuds1** [comment]
I like Torkel's thinking :smile:

**Comment by aknuds1** [comment]
Actually, one improvement that could be made is to fail the front-end tests CI job ASAP if this check fails. As of now, the job only catches the error at the end (after ~14 minutes).

**Comment by mckn** [comment]
We could also do a check to see if any on the changed files in the PR have strict null errors. That isn't perfect but at least it narrows the scope a bit.

With that said, I agree with @torkelo. We still need to just fix all of the issues anyway.
