### ISSUE TITLE
Type Error: Cannot Read Property 'Data' of Null Table Plugin

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#25227]
**What happened**:
Get an Unexpected Error when attempting to apply a Transform on a new table

**What you expected to happen**:
Successfully be able to apply apply transform to table to hide the time column

**How to reproduce it (as minimally and precisely as possible)**:
- Add a table to existing or new dashboard (using InfluxDB data source)
- select multiple fields from a series (3 in my case, query in attached picture)
- Attempt Apply Transform "Filter by Name"

**Anything else we need to know?**:
All our Grafana instances are up on 7.0.1 so I can't test on 7.0.0 any more but I think I did do this a couple times successfully in that release but I can't prove 100% this is a regression I think I'm seeing.  I've attached a screenshot of the error and of the query.  One can see a (1) by the Transform tab, but that stays after getting the failure (was initially at 0 as it should have been).

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: InfluxDB v1.8
- OS Grafana is installed on: CentOS 7.8
- User OS & Browser: MacOS; Safari and Chrome
- Grafana plugins: Table
- Others:

<img width="597" alt="Screen Shot 2020-05-29 at 5 42 08 PM" src="https://user-images.githubusercontent.com/16138910/83313350-6b665600-a1db-11ea-8f80-4d7aed060f1e.png">

<img width="1442" alt="Query" src="https://user-images.githubusercontent.com/16138910/83313520-24c52b80-a1dc-11ea-8094-7b3e3306b21d.png">

**Comment by aknuds1** [comment]
Can you get the untruncated stack trace from the browser JavaScript console when the error happens?

**Comment by jdmaloney** [comment]
@aknuds1 Sure thing, here it is
<img width="1643" alt="Screen Shot 2020-05-30 at 1 30 00 AM" src="https://user-images.githubusercontent.com/16138910/83321439-48f12e80-a215-11ea-92db-4cc2dffa7592.png">

**Comment by aknuds1** [comment]
Thanks!

**Comment by aknuds1** [comment]
I think this might be a duplicate of #25194, which has the same error (and in the same code). You could try the [nightly](https://grafana.com/grafana/download/7.1.0-1d66e55cpre) and see if it's fixed for you.

**Comment by jdmaloney** [comment]
Will do tomorrow, thanks for the pointer.  Sorry my search foo didn't find that one, I think was filtering on open issues and since that was already closed I missed it :)  Thanks for squashing these quick.

**Comment by dprokop** [comment]
@jdmaloney did you have a chance to test this against nightly? If so, we can close this issue

**Comment by jdmaloney** [comment]
@dprokop I'm unable to grab a nighly rpm unfortunately, I tried the first 7 or so from the list and keep getting 404 errors when trying to pull them down:

`wget https://dl.grafana.com/oss/master/grafana-7.1.0-765b30a4pre.x86_64.rpm
--2020-06-01 09:13:46--  https://dl.grafana.com/oss/master/grafana-7.1.0-765b30a4pre.x86_64.rpm
Resolving dl.grafana.com (dl.grafana.com)... 151.101.186.217, 2a04:4e42:2c::729
Connecting to dl.grafana.com (dl.grafana.com)|151.101.186.217|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2020-06-01 09:13:47 ERROR 404: Not Found.`

**Comment by adkinsjd** [comment]
I just ran into this same issue, and I think that the nightly fixed it.

**Comment by jdmaloney** [comment]
I just installed v7.0.2 that just was tagged/released and it does not seem to fix the issue

**Comment by jjkrol** [comment]
@jdmaloney I don't think v7.0.2 is enough. I took the nightly v7.1.0-aed17029pre (2760889501) and the problem is fixed there.

**Comment by jdmaloney** [comment]
@dprokop The v7.0.3 release took care of this, all good now.
