### ISSUE TITLE
Grafana - first implemention - doubts!

### ISSUE THREAD

**Issue by ceinmart** [grafana/grafana#2522]
Hi, 

I looking for a dashboard tool to create an IT and Bussinness dashboards and found Grafana :)

Reading the documentation, after install and run the Grafana at my test environment I've notice need work with specific timeseries datasources.
All my data is at IBM Informix database, so, I'm considering will need create jobs to export this data to some supported datasource and then able to show at Grafana.
For who never worked with Grafana and timeseries database , which supported datababase is recommended in this case ? 
which is easier to work , stable and able use with more resources at Grafana?

**Comment by torkelo** [comment]
I recommend graphite :)
