### ISSUE TITLE
Query Inspector: Show query time range in Panel inspector

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#25229]
**What would you like to be added**:
When I am looking at the query inspector, I loose sight of time range selected for the chart as it overlays on the top of the time range drop down. I wish if query inspect panel is resizable.

![image](https://user-images.githubusercontent.com/14235758/83318915-eab95100-a1fe-11ea-9fc3-b1c1a5981375.png)

**Why is this needed**:
Easy access.

Grafana 7.0

**Comment by peterholmberg** [comment]
I can see your issue but I think we can either include it in the panel inspector rather than make the inspector resizable.
