### ISSUE TITLE
Webhook notification channel password field is in plain text

### ISSUE THREAD

**Issue by reidko** [grafana/grafana#25222]
**What would you like to be added**: It would be ideal if the password field for the webhook notification channel was hidden and not exposed in plain text. 

**Why is this needed**: Anyone who has access to set up notification channels can see the password which raises a security concern for the application we send the alert to.

**Comment by xlson** [comment]
@marefr Seems to me like we should make sure that any secrets in alert channel configurations are kept secret just as we have done for datasources. Has this come up before?

**Comment by marefr** [comment]
Duplicate of #25113

**Comment by marefr** [comment]
Duplicate issue also have an open [PR](https://github.com/grafana/grafana/pull/25114) so closing this.
