### ISSUE TITLE
Help, SVG/Translation graph can go outside the div panel in grafana V7

### ISSUE THREAD

**Issue by algenty** [grafana/grafana#25239]
Hi Grafana,
I don't know if i need to fix flowcharting or it's a bug in grafana V7 but the SVG/Translation graph can go outside the div panel when no panel defined in border.
In grafana 6.7.3, no problem.
See example below
![gf7vsgf6](https://user-images.githubusercontent.com/47012725/83339925-b616c980-a2d2-11ea-8b04-afe5683af0f4.gif)

BR
Arnaud

**Comment by algenty** [comment]
I found a solution by adding overflow: hidden on div
Maybe other plugins have the same problem

**Comment by aknuds1** [comment]
I don't know the context here, are you saying it's a problem in implementing the flowcharting plugin?

**Comment by algenty** [comment]
Hi @aknuds1, i'am the author of flowcharting,when you add it on grafana V7, the plugin can overflow the panel since the v7, not in v6.

**Comment by aknuds1** [comment]
OK, that confirms my understanding. I've added it to the front-end team's backlog, since they're best equipped to consider this issue.

**Comment by ryantxu** [comment]
Are you able to put the content in a div with overflow:hidden?

This did change in 7... In an effort to allow ui components to break out of the panel (like drop-down choice)

**Comment by algenty** [comment]
Hi Ryan
Off course, it's already fixed in v0.9,
https://github.com/grafana/grafana-plugin-repository/pull/638

**Comment by ryantxu** [comment]
great!
