### ISSUE TITLE
Request for new datasource support - non opensource - IBM Informix

### ISSUE THREAD

**Issue by ceinmart** [grafana/grafana#2523]
Hi, 
How your guys see a request to add support for a no open source timeseries database ? 

I don't know if is acceptable for Grafana developer team, but IBM Informix have timeseries support , for free at they free edition (Informix Innovator-C) and it's very well rated at timeseries world (at least is what IBM says).

What is the difficult and needs to add support for one more datasource? 

Below put references if have any interesting at this subject.

Informix TimeSeries manual 
  http://www-01.ibm.com/support/knowledgecenter/SSGU8G_12.1.0/com.ibm.tms.doc/tms.htm?lang=en

Informix Edition comparison - where Innovator-C is free and include TimeSeries and JSON support.
  http://www.ibm.com/developerworks/data/library/techarticle/dm-0801doe/index.html

Informix engine also work with JSON data (and SQL at same time) , which I don't know if could be useful for integration with Grafana... 

Cesar

**Comment by torkelo** [comment]
Anyone can implement an additional data source, it is a plugin system :) 

https://github.com/grafana/grafana-plugins
