### ISSUE TITLE
Stacking on bar gauge

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#25233]
**Steps to reproduce**:
Use a bar gauge to display anything.
**Actual Result**:
I cannot find the stacking option.
**Expected Result**
Find the stacking option as in  v6.6.0
**Environment**:
- Grafana version:7.0
- Data source type & version: MySQL(MariaDB)

Am I only blind?

**Comment by radimkohout** [comment]
Seems like it is not implemented now?

**Comment by torkelo** [comment]
bar gauge is not designed for complex bar charts, but just be a simple gauge
