### ISSUE TITLE
Add a feature to drop first and last data points

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#25234]
Hi, I've been trying to display a website's availability over time. What I did is a simple calculation which is actually (actual counts / expected counts) per time interval. 

![image](https://user-images.githubusercontent.com/43188411/83326511-4de9c880-a27d-11ea-86d6-2db529ac51a6.png)

The query that results the graph, can't say it's closely related to our topic.

```
SELECT count("http_response_code") / (3*$__interval_ms/60000) AS "availability" FROM "http_response" WHERE ("name" =~ /^$name$/ AND "status_code" = '200' AND "result" = 'success') AND $timeFilter GROUP BY time($__interval), "name", "site" fill(null)
```

**What would you like to be added**:

Add an option to drop/ignore last and first points when plotting and calculating (e.g. mean in stats panel) since these points will be incomplete.

**Why is this needed**:

If you look closely the first and last data points are lower than 1.0. It's no coincidence since I'm aggregating data over time(5m) and the last point is not fully shown (or not returned by query) when time is not exactly HH:M0 or HH:M5. I hope screenshots below will make it more clear.

SS taken at 13:04

![image](https://user-images.githubusercontent.com/43188411/83326688-bf764680-a27e-11ea-92a4-cc95bcbc825b.png)

SS taken at 13:06

![image](https://user-images.githubusercontent.com/43188411/83326705-da48bb00-a27e-11ea-88f3-cfac5342ae6f.png)

Eventually, if I increase the time horizon and decrease the group by interval I get better results yet this is not very efficient. I've tried to use "now delay on-" option but it edits the $timeFilter so same result happens with a delay and the aggregation would result similar. Since, I couldn't solve this on query/db side I thought an option in grafana would be good and independent of the source db.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
