### ISSUE TITLE
Last 7 nightly downloads for Linux not downloadable - 404 errors.

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25236]
**What happened**:
If I go to the [Grafana downloads](https://grafana.com/grafana/download/7.1.0-1d66e55cpre?edition=oss&platform=linux) page and choose `Linux` The last (top) 7 nightly builds don't seem to be downloadable. At least for some platforms. For example:
`wget https://dl.grafana.com/oss/master/grafana_7.1.0-1d66e55cpre_amd64.deb`
`--2020-05-30 16:07:06--  https://dl.grafana.com/oss/master/grafana_7.1.0-1d66e55cpre_amd64.deb`
`Resolving dl.grafana.com (dl.grafana.com)... 151.101.18.217, 2a04:4e42:4::729`
`Connecting to dl.grafana.com (dl.grafana.com)|151.101.18.217|:443... connected.`
`HTTP request sent, awaiting response... 404 Not Found`
`2020-05-30 16:07:06 ERROR 404: Not Found.`

And on the download page where it should show the SHA key it says:
`Ubuntu and Debian(64 Bit)SHA256: <?xml version='1.0' encoding='UTF-8'?><Error><Code>NoSuchKey</Code><Message>The specified key does not exist.</Message><Details>No such object: grafana-downloads/oss/master/grafana_7.1.0-1d6`

If I choose the 8th nightly (or lower) from the list all seems well. It's just the most recent 7 as of time of writing.

**Comment by aknuds1** [comment]
Thanks for reporting this, we will look into it.

**Comment by aknuds1** [comment]
I've had a look, and indeed it looks as if we're not uploading RPMs nor Debian packages for master builds. Will give it a go when time permits.

**Comment by aknuds1** [comment]
Looks as if there's a bug in our publishing since the 28th. The RPMs and Debian packages are uploaded, but with a `~` (instead of `-`) separating the pre-release component, f.ex. https://dl.grafana.com/oss/master/grafana_7.1.0~4a981fcdpre_amd64.deb.

**Comment by aknuds1** [comment]
The issue should be fixed, please have a look.

**Comment by therealcodlord** [comment]
Yes, I can now download the latest nightly build. Thank you.
