### ISSUE TITLE
Download CSV: Unicode Support

### ISSUE THREAD

**Issue by baur** [grafana/grafana#25232]
**What would you like to be added**:

Download CSV: Unicode Support

**Why is this needed**:

![image](https://user-images.githubusercontent.com/2898361/83323349-00bb2600-a280-11ea-856e-6427c04c2938.png)

v7.1.0-1d66e55cpre (53b9f325c0)

**Comment by yangliuyu** [comment]
I found a solution which works in v7.0.5
```
Index: public/app/features/dashboard/components/Inspector/InspectDataTab.tsx
<+>UTF-8
===================================================================
--- public/app/features/dashboard/components/Inspector/InspectDataTab.tsx	(revision efbcbb838b4318eaf04161bc9216c74d0155efba)
+++ public/app/features/dashboard/components/Inspector/InspectDataTab.tsx	(date 1594118068625)
@@ -85,8 +85,8 @@
 
     const dataFrameCsv = toCSV([dataFrame]);
 
-    const blob = new Blob([dataFrameCsv], {
-      type: 'application/csv;charset=utf-8',
+    const blob = new Blob([String.fromCharCode(0xFEFF), dataFrameCsv], {
+      type: 'text/csv;charset=utf-8',
     });
     const transformation = transformId !== DataTransformerID.noop ? '-as-' + transformId.toLocaleLowerCase() : '';
     const fileName = `${panel.title}-data${transformation}-${dateTimeFormat(new Date())}.csv`;

```

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
