### ISSUE TITLE
Difficult to view data point tool-tip (details) when hover is only 1 pixel wide

### ISSUE THREAD

**Issue by kaddkaka** [grafana/grafana#25248]
**Steps to reproduce**:
Look at a graph with a few data points and try to get the tooltip with detailed data to show (exact number for all series at this position on the x-axis). If you hover just 1 pixel outside you will not get this information. Even if you manage to hover exactly on that pixel needed just nudging the mouse will hide the tooltip.

**Actual Result**:
Tooltip only shows up if you manage to exactly hover 1 pixel wide line, which is near impossible.

**Expected Result**
Show tooltip of the closest datapoint instead of showing nothing.

Perhaps some way to click to select closest data point and then use arrow keys to select and view the next/previous data point.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: Grafana v6.5.1 (1763a0f)
- Data source type & version: Dotted graph. See JSON below
- User OS & Browser: Firefox 76.0.1 (64-bit) on Ubuntu
- Others: Offline

**JSON of the graph**
```
{
  "datasource": "InfluxDB license",
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "fill": 1,
  "fillGradient": 0,
  "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 49
  },
  "hiddenSeries": false,
  "id": 38,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "options": {
    "dataLinks": []
  },
  "percentage": false,
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
   ... // Data from Influx DB //  ... // "resultFormat": "time_series", // ...
],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "Title",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}
```

**Comment by torkelo** [comment]
There is a tooltip mode to show all series for the time point you are hovering over

**Comment by kaddkaka** [comment]
Toreklo I think you misunderstood the problem? I do get a tool tip when hovering, but I have to hover the exact right pixel.

**Comment by BernH4** [comment]
I have the same problem, its really hard to get the tooltip show up. Even more when points are disabled and i have to search for the 1 correct pixel on the graph.

**Comment by tibyte** [comment]
How about trying GROUP BY fill(linear)?
![image](https://user-images.githubusercontent.com/15897077/137594153-03295de8-46cc-440c-a25e-dd32c08ecf5d.png)

**Comment by BernH4** [comment]
> How about trying GROUP BY fill(linear)? ![image](https://user-images.githubusercontent.com/15897077/137594153-03295de8-46cc-440c-a25e-dd32c08ecf5d.png)

I that's a workaround but then i would loose the ability to see when exactly the data was stored in the database.

Here again a video showing the wanted behaviour (default on visualization "Graph (old)"):

https://www.youtube.com/watch?v=Zv2DuhDOwwE

Queries settings are equal, im not sure if it is a bug or if i did not configure some needed setting to get the tooltip working as wanted.

**Comment by kaddkaka** [comment]
@torkelo why was this issue closed?
