### ISSUE TITLE
transform panel first value issue 

### ISSUE THREAD

**Issue by macd2** [grafana/grafana#25240]
**What happened**:
On the Transform panel the first data point always gets offset to an very large or small value see image.

https://i.imgur.com/rLUrZla.png

**What you expected to happen**:
That the graph starts on the last valide data point 

**How to reproduce it (as minimally and precisely as possible)**:
Use the transform panel and divide 2 series by each other 

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.0
- Data source type & version: influxDB latest 
- OS Grafana is installed on: Docker

**Comment by dprokop** [comment]
@macd2 can you please provide us with the data that your queries returned? I've just tested it against some basic sample data, and it seems to work OK:

![image](https://user-images.githubusercontent.com/2376619/83414621-1b2b0600-a41e-11ea-8213-b6e033b70a41.png)

**Comment by torkelo** [comment]
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.
