### ISSUE TITLE
Need to sort table by column header

### ISSUE THREAD

**Issue by duybinh0208** [grafana/grafana#25243]
I have a table and I need to sort the values by the column header. My column contains numeric values but it seems that the table sort them by string. I expect to have a way to configure the sort type for column.

Thank you.

**Comment by aknuds1** [comment]
If this is a feature request, please post an issue using our standard feature request template, or ask for support in the community [forums](https://community.grafana.com) or [Slack](https://slack.grafana.com). Thanks!
