### ISSUE TITLE
Not possible to override backend plugin configuration settings using environment variables 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#25258]
**What happened**:
Tried to use Grafana backend plugin configuration settings using environment variable.

**What you expected to happen**:
Use Grafana backend plugin configuration settings using environment variable should be sent to backend plugin.

**How to reproduce it (as minimally and precisely as possible)**:
For example trying to use `GF_PLUGIN_SOME_PLUGIN_KEY=value` without Grafana configuration file containing it, e.g.
```ini
[plugin.some-plugin]
key = 
```

**More:**
There's functionality for dynamically adding override of env variables for a section using https://github.com/grafana/grafana/blob/01ecbae2ee4898e316429d688035254838eccb49/pkg/setting/setting.go#L1181.

**Environment**:
- Grafana version: 7.0.1 / master

**Comment by torkelo** [comment]
@marefr will this make 7.4? or move to v8?
