### ISSUE TITLE
Unable to apply transformation inside Table panel

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#25254]
**What happened**:
I tried to organise fields inside my Table Panel from a ElasticSearch datasource.
I wanted to do something similar to the JSON Data option we got before the 7.0.0 update which update the Table panel.

But whenever i try to applied any transformation to the table, nothing happens and then Grafana grant me this error :

![image](https://user-images.githubusercontent.com/33425208/83390501-3f70ed80-a3f2-11ea-9b33-b4ad63cc233c.png)
![image](https://user-images.githubusercontent.com/33425208/83390714-aee6dd00-a3f2-11ea-9e1b-5f36a9f9a95d.png)

**What you expected to happen**:
I wanted to apply "Organise" transformation to only display certains field from the JSON that got returned with my query

**How to reproduce it (as minimally and precisely as possible)**:

1. Edit a Table panel post 7.0.0 update 
2. Change the panel type to the new Table panel (7.0.1 in this case)
3. Go to the Transformation panel and click on any transformation available
4. Go back to the Query panel
5. Click again on the Transformation panel, you will be granted with the error above

**Anything else we need to know?**:
I also tried this issue with a brand new dashboard and panel, which result to the same issue.

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: ElasticSearch 7.6.1
- OS Grafana is installed on: CentOS 1704
- User OS & Browser: Edge 83.0.478.37

**Comment by Joe-TJ** [comment]
Same issue here. Grafana V7.0.1 on CentOS 7, data source is InfluxDB, Edge 83.0.478.37

**Comment by TimHaynie90** [comment]
Same issue here. Grafana V7.0.1 on Linux, SimpleJSON plugin.  This service IS working on v7.0.0-beta1 (413aaf26d7)

**Comment by Theoooooo** [comment]
If i remember i tested this functionnality with the version Grafana V7.0.0-beta2 and it was working, but there was the "Value" string pined just before the aggregate value, for which i submitted an issue. It was supposed to got fixed after that but maybe that is the cause of the issue

**Comment by ryan-garner-msm** [comment]
This issue looks to be fixed in 7.0.3 by #25122

**Comment by Theoooooo** [comment]
It is fixed. I'm closing this issue
