### ISSUE TITLE
Auto-refresh variables are not shwoing

### ISSUE THREAD

**Issue by majdya** [grafana/grafana#25252]
Grafana Cloud

**What happened**:
I lost the ability to refresh the dashboards in time interval smaller than 5 sec

**What you expected to happen**:
to have the ability to auto refresh the dashboards in time interval of 1 second, as what I were doing in previous version

**How to reproduce it (as minimally and precisely as possible)**:
try to add refresh variables less than 5 second, it wont be displayed in the main dashboard page to use them

**Anything else we need to know?**:
I saw that there is a new setting in the grafana ini file, but im not hosting mine, im using grafana cloud, is that a known bug? any way to fix it, or a work around to handle this issue?
**Environment**:
- Grafana version: 7 - cloud hosted
- Data source type & version:  influxdb
- OS Grafana is installed on: not sure, 
- User OS & Browser: Ubuntu, Chrome
- Grafana plugins: none
- Others: none

@peterholmberg i

**Comment by peterholmberg** [comment]
Thanks for reporting this @majdya, please use the bug issue template https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md

**Comment by ayebayley** [comment]
Same issue here.

**What happened**: Auto-refresh dropdown is unresponsive to values populated in Settings > General > Auto-refresh

**What you expected to happen**: Populated Auto-refresh values to display in auto-refresh picker

**How to reproduce it (as minimally and precisely as possible)**: 

1. Dashboard settings > Auto-refresh. Added "1s,5s," to the beginning of the list
2. Clicked save dashboard > "Esc"
3. Dropdown doesn't contain appended values.
4. Dashboard settings > Auto-refresh , values should be correctly edited
5. Click any other subsetting "Variables" for instance, and then click back to "General", the auto-refresh box will be reset to defaults.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.1 (ef5b586d7d)
- Data source type & version: Influxdb 1.6.4
- OS Grafana is installed on: AWS Debian 10 Buster
- User OS & Browser: MacOS Catalina 10.15.4, Chrome
- Grafana plugins: none
- Others: none

**Comment by ayebayley** [comment]
> Same issue here.
> 
> **What happened**: Auto-refresh dropdown is unresponsive to values populated in Settings > General > Auto-refresh
> 
> **What you expected to happen**: Populated Auto-refresh values to display in auto-refresh picker
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Dashboard settings > Auto-refresh. Added "1s,5s," to the beginning of the list
> 2. Clicked save dashboard > "Esc"
> 3. Dropdown doesn't contain appended values.
> 4. Dashboard settings > Auto-refresh , values should be correctly edited
> 5. Click any other subsetting "Variables" for instance, and then click back to "General", the auto-refresh box will be reset to defaults.
> 
> **Anything else we need to know?**:
> 
> **Environment**:
> 
> * Grafana version: Grafana v7.0.1 ([ef5b586](https://github.com/grafana/grafana/commit/ef5b586d7d9e561b78c8aaa098c4e9f1e3a78d62))
> * Data source type & version: Influxdb 1.6.4
> * OS Grafana is installed on: AWS Debian 10 Buster
> * User OS & Browser: MacOS Catalina 10.15.4, Chrome
> * Grafana plugins: none
> * Others: none

UGH. sorry, I edited the ini file and now I'm able to specify lower refresh settings. 5s is a pretty high default for our use case. we run at 500ms or 1s most of the time.

**Comment by marefr** [comment]
Yeah it's a new default in Grafana 7, see https://grafana.com/docs/grafana/latest/installation/upgrading/#dashboard-minimum-refresh-interval-enforced
