### ISSUE TITLE
Update UI for Panel Inspect data display options and transformations

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25268]
## Current state
In 7.0 we have introduced field configuration and transformations control when inspecting panel with Panel Inspect. The UI for this feature looks like this currently:

1. When no transformations applied in the panel:
![image](https://user-images.githubusercontent.com/2376619/83409621-0d24b780-a415-11ea-9deb-295b76515424.png)

2. When transformations applied in the panel:
![image](https://user-images.githubusercontent.com/2376619/83409654-1dd52d80-a415-11ea-9ff7-1c17b59e8847.png)

3. When multiple series available in the panel:
![image](https://user-images.githubusercontent.com/2376619/83409696-36454800-a415-11ea-9d9d-e2cc9f9f31e8.png)
---

We have discussed with @torkelo @jessover9000 and @sarlinska that the UI for transforming data, applying overrides, and transformations in the Panel Inspect is not optimal and confusing. 

As a result, @sarlinska came up with this [design proposal](https://www.figma.com/file/afM4ojoMBRfSmlb0LA0pYQ/Inspect-Drawer?node-id=506%3A0):
![image](https://user-images.githubusercontent.com/2376619/83409865-950ac180-a415-11ea-9911-5c85eb826d49.png)

## UI updates to be implemented
This [proposed UI](https://www.figma.com/file/afM4ojoMBRfSmlb0LA0pYQ/Inspect-Drawer?node-id=506%3A0) organizes the Inspect data options in a simpler way. The most significant changes are:

1. The current Transform select (None/Join By Time) and Data frame select are gone and integrated into a single select that allows Data frame selection and Join By Time transformation:
![image](https://user-images.githubusercontent.com/2376619/83410107-05b1de00-a416-11ea-9a93-a20513b3e67d.png)
2. All data options should be organized into single expandable section **Table data options**:
![image](https://user-images.githubusercontent.com/2376619/83410159-20845280-a416-11ea-8e1b-86b63c05c67a.png)
3. The **Table data options** expandable section should show a summary of the data options applied:
![image](https://user-images.githubusercontent.com/2376619/83410232-49a4e300-a416-11ea-83ba-7871a10b3d91.png)

**Figma design**: https://www.figma.com/file/afM4ojoMBRfSmlb0LA0pYQ/Inspect-Drawer?node-id=506%3A0

**Comment by mckn** [comment]
For scenario 3 here one solution could be to apply the merge transform to get everything in one serie/table.
