### ISSUE TITLE
frontend building got error

### ISSUE THREAD

**Issue by efvhi** [grafana/grafana#25261]
**What happened**: 
build frontend
yarn run build
yarn run v1.22.4
$ grunt build
Version 7.1.0-pre
Loading "Gruntfile.js" tasks...ERROR
>> SyntaxError: Unexpected token '<<'

Running "clean:release" (clean) task
Verifying property clean.release exists in config...ERROR
>> Unable to process task.
Warning: Required config property "clean.release" missing. Use --force to continue.

Aborted due to warnings.
error Command failed with exit code 3.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Makefile:43: recipe for target 'build-js' failed
make: *** [build-js] Error 3

**What you expected to happen**:
build succeed

**How to reproduce it (as minimally and precisely as possible)**:
yarn run build

**Anything else we need to know?**:
on master branch

**Environment**:
- Grafana version: 7.x
- Data source type & version:
- OS Grafana is installed on: macos
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
Strange, I am unable to reproduce this when running on master. Does `yarn start` work?

**Comment by efvhi** [comment]
> arn sta

yeah ! yarn start works fine !
