### ISSUE TITLE
RethinkDB as a Data Source

### ISSUE THREAD

**Issue by skynet** [grafana/grafana#2526]
Are there any plans to add RethinkDB as a data source?

**Comment by torkelo** [comment]
RethinkDB is not really a time series database, so no plans

**Comment by skynet** [comment]
Is Grafana plugable? I would like to be able to use such data source.

**Comment by torkelo** [comment]
yes, all data sources are plugins. Can you explain why you want to use RethinkDB for this? Seems like a very poor choice (don't get me wrong, I have used RehinkDB and I think it is great), but for time series database it does not seem like a good fit.

**Comment by tmonk42** [comment]
@skynet https://github.com/grafana/grafana-plugins

**Comment by skynet** [comment]
Thank you, @tmonk42
