### ISSUE TITLE
highlighter function not working properly

### ISSUE THREAD

**Issue by thuck** [grafana/grafana#2527]
Hi @torkelo;  
Looks like the highlighter function on the vendor/bootstrap/bootstrap.js has some odd behavior:  
![snapshot1](https://cloud.githubusercontent.com/assets/184833/9293017/e38495d2-4418-11e5-8c21-fca887837100.png)

Not sure what should be the value for this.query on it; but I get an empty value.
So the item.replace(new RegExp('(' + query + ')', 'ig') becomes (); which matches everything; and generates the: ```<strong></strong>v<strong></strong>a...```
I'm not sure if this highlight should be only for the active one; or if this should be for all the items in the menu.

**Comment by torkelo** [comment]
not sure what you are talking about, are you talking about auto complete drop down?

**Comment by thuck** [comment]
Yes, looks like this happens in all places that you have dropdown-menu.
This function:
```
  , highlighter: function (item) {
      var query = this.query.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, '\\$&')
      return item.replace(new RegExp('(' + query + ')', 'ig'), function ($1, match) {
        return '<strong>' + match + '</strong>'
      })
    }
```
Instead of returning:   
```
<strong>value</strong>
```

it returns:   
```
<strong></strong>v<strong></strong>a<strong></strong>l ...
```

Because (as far as I could see) the ```this.query``` is empty, and as it's empty the:
```new RegExp('(' + query + ')', 'ig')```
Becomes:
```new RegExp('()', 'ig')```

Another screen shot maybe it can help more:
![snapshot2](https://cloud.githubusercontent.com/assets/184833/9293798/43bdddee-4439-11e5-9794-85c881bb0a6e.png)

The html part that is generated as an example:
```
<ul style="top: 28px; left: 42px; display: none;" class="typeahead dropdown-menu"><li class="" data-value="-- remove from select --">
  <a href="#">
    <strong></strong>
    -
    <strong></strong>
    -
    <strong></strong>
    
    <strong></strong>
    r
    <strong></strong>
    e
    <strong></strong>
    m
    <strong></strong>
    o
    <strong></strong>
    v
    <strong></strong>
    e
    <strong></strong>
    
    <strong></strong>
    f
    <strong></strong>
    r
    <strong></strong>
    o
    <strong></strong>
    m
    <strong></strong>
    
    <strong></strong>
    s
    <strong></strong>
    e
    <strong></strong>
    l
    <strong></strong>
    e
    <strong></strong>
    c
    <strong></strong>
    t
    <strong></strong>
    
    <strong></strong>
    -
    <strong></strong>
    -
    <strong></strong>
    </a>
  </li>
  <li class="active" data-value="value">
    <a href="#">
      <strong></strong>
      v
      <strong></strong>
      a
      <strong></strong>
      l
      <strong></strong>
      u
      <strong></strong>
      e
      <strong></strong>
    </a>
  </li>
</ul>
```

**Comment by thuck** [comment]
I don't think it's relevant; but the html above is generated by this:
```
  , render: function (items) {
      var that = this

      items = $(items).map(function (i, item) {
        i = $(that.options.item).attr('data-value', item)
        i.find('a').html(that.highlighter(item))
        return i[0]
      })
```
More precisely the:
```
i.find('a').html(that.highlighter(item))
```

Also just for the sake of information, I'm testing this in an iceweasel/firefox 38.1.0; and I tested in a chromium 44.0.2403.107.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9325217/e6c47c66-4590-11e5-8148-64dd6eb70e96.png)


Fixed, and changed highlight color to something better.  :)
