### ISSUE TITLE
Gauge: Panel throws error when all values are null 

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#25279]
**What happened**:
When the query returns no data, the Gauge visualization throws the error "Cannot read Property 'toFixed' of undefined instead of showing 'No Data'. 
![image](https://user-images.githubusercontent.com/49911675/83495561-6e6a8a80-a4ea-11ea-810d-808ce8f29650.png)
![image](https://user-images.githubusercontent.com/49911675/83496838-3fedaf00-a4ec-11ea-9926-e46650e772f1.png)

These  2 panels have the same query, and everything works well when there is data
![image](https://user-images.githubusercontent.com/49911675/83495998-05cfdd80-a4eb-11ea-8a13-a5ce88a6b80d.png)

**What you expected to happen**:
'No Data' message displayed, like it is in other panels.

**How to reproduce it (as minimally and precisely as possible)**:
Use Gauge visalization on a query returning no data.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by donmahallem** [comment]
I did face this issue too today. I am not familiar enough with the source code so I can just provide some hints:

If the query only returns null values from the datasource the problem are [these lines](https://github.com/grafana/grafana/blob/e03da3760efc9be99c6808fd67c6a3e09ee1f2a5/packages/grafana-ui/src/components/Gauge/Gauge.tsx#L134-L135).

Min and max will be set to 'null' which causes toFixed() to throw.

As the code [does expect ](https://github.com/grafana/grafana/blob/e03da3760efc9be99c6808fd67c6a3e09ee1f2a5/packages/grafana-ui/src/components/Gauge/Gauge.tsx#L119-L120) to never be not defined there either should be a null check within the draw function or the method(I couldn't find it in the code base), which sets the those values should provide "proper" values.
