### ISSUE TITLE
grafana add elasticsearch datasource with https return 400

### ISSUE THREAD

**Issue by liminghua999** [grafana/grafana#25288]
docker run:
`grafana : 7.0.1
elasticsearch: 7.6.4
`

es run with https
![es](https://user-images.githubusercontent.com/18185326/83509576-3f5e1400-a4fe-11ea-86b2-8a7c927ac74c.png)
![es2](https://user-images.githubusercontent.com/18185326/83509586-4422c800-a4fe-11ea-93b6-57b371fa7aed.png)
where I mistake

**Comment by peterholmberg** [comment]
community.grafana.com is better suited for questions like this
