### ISSUE TITLE
The  Org is not getting assigned , generic_oauth

### ISSUE THREAD

**Issue by mohamednizar** [grafana/grafana#25281]
**What happened**:
while authenticating the user via generic_auth, the org is not assigned to the user

**What you expected to happen**:
The user needs to be assigned to specific org

**How to reproduce it (as minimally and precisely as possible)**:
the given config
```
[auth.generic_oauth]
enabled = true
name = SIS

;allow_sign_up = true
client_id = 3
client_secret = 6Ck1R9XzWyxSe4UMVUOFDBJ7hp0mgsznEqZkzquB
scopes = '*'
;email_attribute_name = email:primary
email_attribute_path = email
auth_url = http://localhost:3001/oauth/authorize
token_url = http://localhost:3001/oauth/token
api_url = http://localhost:3001/api/user
;allowed_domains =
team_ids = 2
allowed_organizations = 'Schools'
```
response of http://localhost:3001/api/user/orgs 

`[{\"orgId\":2,\"userId\":80305,\"role\":\"Viewer\",\"name\":\"Schools\",\"email\":\"nizarm@opensource.lk\",\"login\":\"Schools\"}]
`

find the logs below:
```
t=2020-06-02T14:42:23+0530 lvl=dbug msg="HTTP GET http://localhost:3001/api/user: 200 OK {\"email\":\"nizarm@opensource.lk\",\"name\":\"M Nizar\",\"username\":\"903483261V\",\"info\":{\"groups\":[\"school\"],\"company\":{\"orgId\":2,\"userId\":80305,\"role\":\"Viewer\",\"name\":\"Schools\",\"email\":\"nizarm@opensource.lk\",\"login\":\"Schools\"},\"role\":[\"Editor\",\"Viewer\"]}}"
t=2020-06-02T14:42:23+0530 lvl=dbug msg="Received user info response" logger=oauth.generic_oauth raw_json="{\"email\":\"nizarm@opensource.lk\",\"name\":\"M Nizar\",\"username\":\"903483261V\",\"info\":{\"groups\":[\"school\"],\"company\":{\"orgId\":2,\"userId\":80305,\"role\":\"Viewer\",\"name\":\"Schools\",\"email\":\"nizarm@opensource.lk\",\"login\":\"Schools\"},\"role\":[\"Editor\",\"Viewer\"]}}" data="Name: M Nizar, Displayname: , Login: , Username: 903483261V, Email: nizarm@opensource.lk, Upn: , Attributes: map[]"
t=2020-06-02T14:42:23+0530 lvl=dbug msg="HTTP GET http://localhost:3001/api/user/teams: 200 OK [{\"id\":2,\"orgId\":2,\"userId\":80305,\"role\":\"Viewer\",\"name\":\"schools\",\"email\":\"schools@sis.moe.gov.lk\",\"login\":\"schools\",\"ids\":[2]}]"
t=2020-06-02T14:42:23+0530 lvl=dbug msg="Received team memberships" logger=oauth.generic_oauth ids=[2]
t=2020-06-02T14:42:23+0530 lvl=dbug msg="HTTP GET http://localhost:3001/api/user/orgs: 200 OK [{\"orgId\":2,\"userId\":80305,\"role\":\"Viewer\",\"name\":\"Schools\",\"email\":\"nizarm@opensource.lk\",\"login\":\"Schools\"}]"
t=2020-06-02T14:42:23+0530 lvl=dbug msg="Received organizations" logger=oauth.generic_oauth logins=[Schools]
t=2020-06-02T14:42:23+0530 lvl=dbug msg="User info result" logger=oauth.generic_oauth result="&{Id: Name:M Nizar Email:nizarm@opensource.lk Login:903483261V Company: Role: Groups:[]}"
t=2020-06-02T14:42:23+0530 lvl=dbug msg="OAuthLogin got user info" logger=oauth userInfo="&{Id: Name:M Nizar Email:nizarm@opensource.lk Login:903483261V Company: Role: Groups:[]}"

```

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.0.0
- Data source type & version:j
- OS Grafana is installed on: Linux
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by dalcde** [comment]
In general it would be helpful to be able to specify a claim that provides the list of organizations the user is in, instead of querying `api_url/orgs` blindly.

**Comment by marefr** [comment]
Think you have misunderstood the `allowed_organizations` property - that is used to validate that  users authenticating through oauth provider must be in specified organization, otherwise login will not be allowed. I think you're interested in this issue 23473 so will close this.

**Comment by dalcde** [comment]
My understanding of this issue is that Grafana retrieves the list of
organizations the user is in via a non-standard API endpoint (namely
api_url/orgs). For most OAuth2 providers that are not GitHub, I believe
such information is usually provided through an openid claim, (e.g.
`groups`), so the allowed_organizations property is unusable.

**Comment by didiez** [comment]
Same problem over here.
Without a deep knowledge of the implementation details and the reasons behind querying `userinfo/orgs`, a conf property like `orgs_attribute_path` could be super useful, allowing to map users to orgs without leaving the standad api endpoint.
