### ISSUE TITLE
Fix nightly Docker links

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#25280]
There seems to be a bug on grafana.com's listing of Docker images for nightly releases. E.g., for 7.1.0-f7d68d71pre, it lists the Docker images grafana/grafana and grafana/grafana:7.1.0-f7d68d71pre-ubuntu. The first is not a nightly, and the second one doesn't exist.

**Comment by Theoooooo** [comment]
I got a similar issue, i can't download any nightly build on the website.
I always got this issue :
![image](https://user-images.githubusercontent.com/33425208/83502858-829a9180-a4c2-11ea-9896-2080b08b771c.png)

**Comment by aknuds1** [comment]
@Theoooooo I just merged a fix for that - see #25236.

**Comment by aknuds1** [comment]
This has been fixed.
