### ISSUE TITLE
Multi selection Variables are not working with Azure Log Analytics based panels

### ISSUE THREAD

**Issue by networkandcode** [grafana/grafana#25295]
Grafana Version: 7.0.0
Deployment type: Helm

I have added variables for Deployment names, and was able to view graphs on Prometheus based panels when I do single, multi selection, or All.

However this doesn't work with Azure Log Analytics based panels. It only works when 'Allow multiple values' is not checked in the Variables defining page of the dashboard.

Is this something not supported now ?, or am I doing something wrong

**Comment by peterholmberg** [comment]
Hello,
this looks more like a question which is better discussed on our community site (community.grafana.com). If it happens to be an issue in Grafana, please update the issue with the bug issue template.
