### ISSUE TITLE
InfluxDB: Query edit does revert to previous setting

### ISSUE THREAD

**Issue by ScruffR** [grafana/grafana#25298]
**What happened**:
When using the query text edit feature (![image](https://user-images.githubusercontent.com/6604878/83523006-c05ae280-a4e1-11ea-85aa-4ffa2772060d.png)) the edits are correctly applied to the data table but switching back to "mouse edit" undoes these edits in the "mouse edit" view while the data table still shows the data defined before the switching.
However, when switching back to "text edit" now the wrong query text is displayed here too.
Even after hitting <kbd>Apply</kbd> and/ort <kbd>Save</kbd> that inconsistency is not resolved. I see the data of a different query than what the Edit Panel is presenting to me.

**What you expected to happen**:
When editing - no matter which way, text or mouse - I'd expect to *keep* my changes across all edit views but most of all I cannot accept the inconsistency between query and displayed data.

**How to reproduce it (as minimally and precisely as possible)**:
Some screenshots to show the behaviour when reproducing the issue
This is the inital query before editing
![image](https://user-images.githubusercontent.com/6604878/83525278-09606600-a4e5-11ea-9f8b-73fc0001fb6d.png)
then switching to text edit mode
![image](https://user-images.githubusercontent.com/6604878/83525419-3dd42200-a4e5-11ea-89fd-ee47e11d6a38.png)
(data panel still shows the same data)
then editing `mean("AP")` to `mean("Kenn")` results in this (expected behaviour)
![image](https://user-images.githubusercontent.com/6604878/83525660-94d9f700-a4e5-11ea-9d6d-b08245dd8670.png)
(mark data is now `1` instead of `30`)
Hitting <kdb>Save</kbd> and then going back to "mouse edit" results in this
![image](https://user-images.githubusercontent.com/6604878/83525978-0619aa00-a4e6-11ea-9b67-0adf218d24a7.png)
it should be `field(Kenn)` but is `field(AP)` while still showing the data of  `Kenn` and after going back to text edit view this happens
![image](https://user-images.githubusercontent.com/6604878/83526225-6577ba00-a4e6-11ea-9506-1c76d85ae3d3.png)
the text here too has been reverted to `mean("AP")`.
After hitting <kdb>Save</kbd> and/or <kdb>Apply</kbd> nor closing and reopening the dashboard changes that anymore. 
The query and the data don't match anymore.

When doing the editing solely in "mouse edit mode" the result is as expected.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: InfluxDB v1.8
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 10 Pro 64bit 1809 (Build 17763.1217) / Chrome 81.0.4044.138 (64-Bit)
- Grafana plugins: none

**Comment by gabor** [comment]
in grafana 8 beta3 or later this works in a predictable way now: whenever you switch between "text edit" and "mouse edit" mode, the visualization always shows the data based on the query you see on the screen. 

so, going by your example, after doing the `Hitting Save and then going back to "mouse edit" ` step, you will see the value `30` in the second column.

note, when switching from text-mode to mouse-mode, you get a dialog warning you that you are going to loose your changes. if you accept, you switch back to mouse-mode and the changes you did while in text-mode are now lost.
