### ISSUE TITLE
Dashboard input variables vanish causing havok in Grafana 7.0

### ISSUE THREAD

**Issue by rustysys-dev** [grafana/grafana#25292]
Grafana Version: 7.0.0

**ISSUE**
Importing dashboards with `__input` variables fail to work.
More specifically the `__input` variables disappear and have to be manually defined.

My `__input` variables:

```json
"__inputs": [
  {
    "name": "DS_PROMETHEUS",
    "label": "Prometheus",
    "description": "",
    "type": "datasource",
    "pluginId": "prometheus",
    "pluginName": "Prometheus"
  }
]
```

![image](https://user-images.githubusercontent.com/34673206/83520110-18144080-a518-11ea-86e0-44ebd1593b21.png)

At which point bringing up the dashboard gives a string of the following errors.

`Object { message: "Datasource named ${DS_PROMETHEUS} was not found" }`

and then all of the panels default to the `default` test datasource, and their queries erased.

Is this a bug? or is there something more to importing a dashboard than just importing the JSON?

**Comment by mckn** [comment]
@rustysys-dev thanks for reporting this 🙏  Do you have a datasource called `DS_PROMETHEUS` when importing the dashboard?

hmm, I think it should ask for a replacement if it isn't available. Correct, @peterholmberg @torkelo?

**Comment by torkelo** [comment]
Testing import and it works as it should 

![Screenshot from 2020-06-15 16-24-50](https://user-images.githubusercontent.com/10999/84669149-d1b1df00-af24-11ea-83ac-7974b3e724f5.png)

Can you include the exported json you fail to import?

**Comment by rustysys-dev** [comment]
> Testing import and it works as it should 
> 
> ![Screenshot from 2020-06-15 16-24-50](https://user-images.githubusercontent.com/10999/84669149-d1b1df00-af24-11ea-83ac-7974b3e724f5.png)
> 
> Can you include the exported json you fail to import? 
> 

seems i was thinking that this was sonething it was not.  sorry about that!

I should have read it more clearly, if i change DS_PROMETHEUS to my actual input name it works...
