### ISSUE TITLE
Allow to "anchor" the leftmost column(s) in table panel

### ISSUE THREAD

**Issue by ScruffR** [grafana/grafana#25294]
**What would you like to be added**:
It would be nice to have an option to "anchor/fix/lock" the leftmost column(s) in a table so that they will stay visible when scrolling horizontally.

**Why is this needed**:
When dealing with a time based table that's wider than the width of the table panel it is most important to keep (at least) the time column visible even when scrolling all the way to the right.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by SaberStrat** [comment]
Well since feature requests are back under issues again, I'd like to express my interest in this too.

Maybe not even just the leftmost column, offer a way to fix a custom amount of columns.

**Comment by leeoniya** [comment]
we're working on a new Table panel which should be able to support this more easily. there is an existing issue for this: https://github.com/grafana/grafana/issues/83567
