### ISSUE TITLE
AlertRules: List shows orphaned alert rules (dashboard panel no loner has alert rule) 

### ISSUE THREAD

**Issue by slash-zero** [grafana/grafana#25305]
**Grafana Version:** 6.4.4 (092e514)

While setting up some alerting rules and experimenting, I set up an alert rule for a graph, trying to use template variables, on a graph that is in an auto-repeating row.  This results in alerting rules being set up.  I deleted the alert rules from the offending graph, however the alerting rules panel still shows all of them, and they are being triggered, and posting to Slack anyway.  

![image](https://user-images.githubusercontent.com/5788688/83550942-a0bdbd00-a4d5-11ea-981f-d0817ff59202.png)

Clicking to the "gear" icon for each alert rule, takes me to the graph alert panel, however the only option there is "Create Alert".  The rule was already deleted. 

![image](https://user-images.githubusercontent.com/5788688/83551016-bdf28b80-a4d5-11ea-8d9c-85cb0e31c5bf.png)

This seems like a bug.  How can I remove those rules which were set up incorrectly (the alert was already deleted from the graph).

**Comment by torkelo** [comment]
Can you try upgrading to latest 7.3 release? There is a possibility that orphaned alert rules are cleaned up then

**Comment by weeco** [comment]
@torkelo We are running Grafana 7.3.1 and we have a similar issue, though it shows an error when I want to navigate to this alert.

**Step 1:**

![image](https://user-images.githubusercontent.com/23424570/98262133-8b1d5980-1f85-11eb-8cb2-ea3bfb5dd9b7.png)

**Step 2:**

![image](https://user-images.githubusercontent.com/23424570/98262213-a38d7400-1f85-11eb-996a-af6b5ec18ef3.png)

It seems like there's no way to get rid of these alerts? They kept trying to send notification to teh respective alerting channel, hence we stopped them as we can't figure out how to delete them. The affected dashboard has been imported via JSON from another Grafana organization (we used the JSON export with the "export for external" ticked).

**Comment by marefr** [comment]
@weeco have you tried to save the dashboard from which the orphaned alert rules was created?

**Comment by marefr** [comment]
I'm closing this for now since it seems like source problem has been fixed in later versions of Grafana. Easiest way to get rid of the orphaned alerts would be to connect to the database if it's not helping saving the dashboard. But I'll reconsider if you provide more information.
