### ISSUE TITLE
stat and  barguage deafult text is gone

### ISSUE THREAD

**Issue by efvhi** [grafana/grafana#25300]
<img width="1650" alt="屏幕快照 2020-06-02 下午9 46 23" src="https://user-images.githubusercontent.com/22891991/83527571-8e19a700-a51a-11ea-935d-40efea16a379.png">

**What happened**:
the cloudwatch alias `{{DBClusterIdentifier}} `cannot show

**What you expected to happen**:
show Dimensions alias

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
Could this be related to https://github.com/grafana/grafana/issues/25283 ?

**Comment by peterholmberg** [comment]
Closed via: https://github.com/grafana/grafana/pull/24829
