### ISSUE TITLE
Add back old csv export feature for old angular table panel

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#25306]
## Summary

Migrated Table panel from v6.7.3 to v7.0.1.
Table panel has **Time series aggregations**.
I want to export to CSV.

## Result in v6.7.3

CSV data has the same content as displayed in the table. This is the expected output.

```
"Metric";"Max"
"A-series";"8.72"
```

## Result in v7.0.1

CSV data shows the original time series, without the Time series aggregation applied.

```
"Time","A-series"
2020-06-02 09:24:08,70.22958832599566
2020-06-02 09:24:38,70.07173357919876
2020-06-02 09:25:08,70.24055108619038
2020-06-02 09:25:38,69.92584200471863
2020-06-02 09:26:08,69.85882691834809
2020-06-02 09:26:38,70.23020700096605
2020-06-02 09:27:08,70.57990735979517
2020-06-02 09:27:38,70.2935682855995
2020-06-02 09:28:08,69.81276325857075
[…]
```

## Panel JSON models for reproduction

Use this panel JSON model and try exporting the CSV in v6.7.3 and in v7.0.1.

### v6.7.3 model

```
{
  "datasource": null,
  "columns": [
    {
      "text": "Max",
      "value": "max"
    }
  ],
  "fontSize": "100%",
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "pageSize": null,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "alias": "Time",
      "align": "auto",
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "pattern": "Time",
      "type": "date"
    },
    {
      "alias": "",
      "align": "right",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "decimals": 2,
      "pattern": "/.*/",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "refId": "A",
      "scenarioId": "random_walk",
      "stringInput": ""
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Panel Title",
  "transform": "timeseries_aggregations",
  "type": "table"
}
```

### v7.0.1 model

```
{
  "columns": [
    {
      "$$hashKey": "object:171",
      "text": "Max",
      "value": "max"
    }
  ],
  "fontSize": "100%",
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "$$hashKey": "object:139",
      "alias": "Time",
      "align": "auto",
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "pattern": "Time",
      "type": "date"
    },
    {
      "$$hashKey": "object:140",
      "alias": "",
      "align": "right",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "decimals": 2,
      "pattern": "/.*/",
      "thresholds": [],
      "type": "number",
      "unit": "short"
    }
  ],
  "targets": [
    {
      "refId": "A",
      "scenarioId": "random_walk",
      "stringInput": ""
    }
  ],
  "title": "Panel Title",
  "transform": "timeseries_aggregations",
  "type": "table-old",
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "pageSize": null,
  "timeFrom": null,
  "timeShift": null,
  "datasource": null
}
```

# Additional info

Possibly related to #25268

# Environment

- Grafana version: v7.0.1
- Data source type & version: TestData DB (any data source)

**Comment by torkelo** [comment]
Not sure what we can do here beyond adding back the old csv export feature

**Comment by mckn** [comment]
@torkelo this might already be fixed. When testing this against master I get the expected result if I have the reduce transformation applied and the following settings.

<img width="821" alt="Skärmavbild 2020-06-15 kl  16 29 30" src="https://user-images.githubusercontent.com/172951/84669869-a67bbf80-af25-11ea-95c1-e351cfe12f29.png">

@adeverteuil is this something you have tested?

**Comment by torkelo** [comment]
yes if you use new transformations, but for old table panel using the built-in table transform option. 

Maybe the solution is to just ask users to migrate from the table transform option to the new transformations feature

**Comment by shalstea** [comment]
What we have found is that in the panel json we see "table-old" to get transformations to work properly, we recommend that they click on the visualization to change the type (say graph) and then back to table.  This resets the panel json to be "table" when that happens this old transformations are removed.. and then they can use the new transformations.

Just a FYI.

**Comment by shalstea** [comment]
I should have added, once you convert to the new "table" the export works fine from the panel inspect -> data -> download csv.

**Comment by mckn** [comment]
> yes if you use new transformations, but for old table panel using the built-in table transform option.
> 
> Maybe the solution is to just ask users to migrate from the table transform option to the new transformations feature

Yes, that sounds like a good plan? Is there some drawbacks with that approach?

**Comment by mckn** [comment]
> I should have added, once you convert to the new "table" the export works fine from the panel inspect -> data -> download csv.

Awesome feedback! Thanks for the update 🙏

**Comment by dprokop** [comment]
@adeverteuil do you think the solution described above would work for you? If so, please close this issue.

**Comment by dprokop** [comment]
@adeverteuil friendly ping :)

**Comment by itldo** [comment]
We encountered another difference from the old CSV Export that we miss.
The new CSV Export does not preserve or respect the column sorting order selected.

**Comment by zoltanbedi** [comment]
I'm going to close this issue as there was no response in a long time. Please let us know if this is still something that you are looking forward to.
