### ISSUE TITLE
Right Y axis lost when variables used in alias

### ISSUE THREAD

**Issue by tokudan** [grafana/grafana#2530]
Grafana forgets which Y axis to move to the right side everytime I select a different variable value with an alias like this:
alias($group.stats.uptime.average, '$group uptime')

As $group can be multi-value, I need to keep $group in the alias to be able to figure out which line shows which data.
Also the groups are generated automatically, so I cannot move them around manually.

**Comment by torkelo** [comment]
y axis is specified using alias, so if the series name change the setting is lost. 

You can specify y axis using regex rule as well, you define these rules using series override in display style tab:
http://play.grafana.org/dashboard/db/new-features-in-v2-1?panelId=15&fullscreen&edit

**Comment by tokudan** [comment]
I'm sorry, but I seem unable to find that setting. I see that I can change the color of the series there, but where is the setting to move a series to the right Y-axis?
Similar to this one, where the percentage is on the right.
https://ff.besaid.de/dashboard/db/freifunk-gruppen?panelId=13&fullscreen

**Comment by torkelo** [comment]
in the Series specific overrides section, add a new override rule, specify regex that match series, hit the plus icon to specify an override option enter "axis", the auto complete dropdown should show "Y-axis 1" and "Y axis 2" , you can use the dropdown menu and select "Y-axis" -> then "Y-axis 2"

**Comment by tokudan** [comment]
I wasn't able to find that in the menu that shows up. It's not visible there (or I'm blind?).
I figured it out with your help. Thank you.
