### ISSUE TITLE
Alerting: cleanup alerts whenever deleting a notification channel

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#25309]
**What happened**:
Currently it is too expensive to find alerts using a specific notification channel and remove it when that channel is deleted. The reason is that this information is kept in a JSON field in the alert table. The code should be refactored so that it will be easier to keep alerts consistent whenever a notification channel is deleted.

An extra effort should be put also on updating alerts having references to already deleted notification channels.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Related issue #24969

**Environment**:
- Grafana version: 7.0.2

**Comment by davidnewhall** [comment]
When importing dashboards, I'm given a choice of data sources. I'd like to see the same thing for notification channels: Show me the old name, and give me a selection of existing channels. The alternative would be to remove the notifications channels upon import. Often, they conflict or do not exist.

**Comment by davidnewhall** [comment]
It would also be handy if the error messages printed into my Grafana log every ten seconds for "missing notifications channels" contained a link to the dashboard. Then I could fix them in a few minutes.
