### ISSUE TITLE
Icon: Better typing for mono/default icon names

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#25314]
Currently we have[ IconName type](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/types/icon.ts#L5) that includes all icons that can be implemented (appx. 110). However, we support only around [13 of those in mono type](https://github.com/grafana/grafana/tree/master/packages/grafana-ui/src/components/Icon/assets). We could introduce better typing/messaging, so our users know which mono icons can be used and are implemented.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
