### ISSUE TITLE
[Feature request] Dynamic Thresholds for the SingleStat panel

### ISSUE THREAD

**Issue by StaelensJarne** [grafana/grafana#25313]
**What would you like to be added**:
I don't know if this is already possible, but can you add dynamic thresholds for the SingleStat panel? And what threshold values are allowed?
![Visualisation SingleStat panel](https://user-images.githubusercontent.com/26405591/83609749-fa2df680-a57e-11ea-8591-d18fbb566d1c.png)
Is this possible via a template variable or via a MySQL query? And then set that variable in the Thresholds fields? 

**Why is this needed**:
If I have another device, the same model but with a different firmware version than these Thresholds are 5 and 55, for another firmware version these Thresholds are -5 and 40, for another one 2 and 52 ... Is this possible to get the values variable and then set this in the thresholds field. 

Or is the best solution in this case to update all devices to the same firmware version?

**Comment by peterholmberg** [comment]
Single stat panel has been depricated, please use the Stat panel

**Comment by StaelensJarne** [comment]
Since which version is the SingleStat panel deprecated? As far as I know the SingleStat panel is the only official panel that support single queries?

And the question remains the same for the Stat panel? Can you add dynamic thresholds for the Stat panel?

**Comment by StaelensJarne** [comment]
Is my opinion the issue is not yet closed. The question remains unanswered.

According to the documentation the question is also the same for a Bar gauge, Gauge, Graph, Stat and Table panel.

**Comment by Phara0h** [comment]
> Single stat panel has been deprecated, please use the Stat panel
The issue was not addressed, I +1 this feature, please. Or should I make a duplicate ticket, since the feature does not exist in "stat panel" either

**Comment by nicolargo** [comment]
Why this issue has been closed ? The Stat panel do not implement the requested feature and it will be a very nice value added to Grafana...

**Comment by a-vogel-tappert** [comment]
A threshold based on a query or variable would be great.
Please enter that feature :-)

**Comment by barthelemyguillaume** [comment]
Need it!

**Comment by ruslantagirov** [comment]
Need it. For any threshold on various graph types.
For example, a gauge for k8s namespace quota, I want to set pomql query like `sum(kube_resourcequota{namespace="$namespace",type="hard"})` as Max value or Threshold value and use smth like `sum(kube_resourcequota{namespace="$namespace",type="used"})` as a 'main' datasource for Gauge or Stat, or Graph
