### ISSUE TITLE
support sum aggregation in singlestat 

### ISSUE THREAD

**Issue by gaos1** [grafana/grafana#2531]
when I create a siinglestat graph and specify multiple values using | for a tag,  I want the final value to be sum of the matched metric values.  This is very useful for this case. 

![screen shot 2015-08-17 at 11 03 24 am](https://cloud.githubusercontent.com/assets/1188196/9297324/26d3f80c-44d0-11e5-9eb9-04ffa2791f60.png)

As shown in attachment, the metric will show value 1, which is the value of one of matched job tag etcd_z1 or etcd_z2. 
I want the value to be 2, which is the sum value of two matched job tag etcd_z1 and etcd_z2.

**Comment by newpcraft** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
최중연(choe.jungyeon@naverc...) 님은 현재 부재중입니다.</br>
보내신 메일 <[grafana] support sum aggregation in singlestat (#2531)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
최중연(choe.jungyeon@naverc...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-08-17 10:00 ~ 2015-08-17 19:00 GMT +09:00]<br>17일 월요일 휴가 입니다.<br>NDOT, NPOT 문의는 조지원 대리님께 부탁드립니다.
--------------------------------------------

**Comment by gaos1** [comment]
if grafana can convert input tag value etcd_z1|etcd_z2 to the following opentsdb query,  it should be able to return proper value 2:

m=system.healthy{job=etcd_z1,job=etcd_z2}

**Comment by newpcraft** [comment]
NAVER - http://www.naver.com/
--------------------------------------------
최중연(choe.jungyeon@naverc...) 님은 현재 부재중입니다.</br>
보내신 메일 <Re: [grafana] support sum aggregation in singlestat (#2531)> 은 저장되어 있으므로 다시 보내실 필요는 없습니다.</br>
최중연(choe.jungyeon@naverc...) 님이 남기신 메시지 입니다.
--------------------------------------------
[Absence period : 2015-08-17 10:00 ~ 2015-08-17 19:00 GMT +09:00]<br>17일 월요일 휴가 입니다.<br>NDOT, NPOT 문의는 조지원 대리님께 부탁드립니다.
--------------------------------------------

**Comment by torkelo** [comment]
singlestat only shows the sum, avg, current, min, max of the FIRST series returned by the query. 

would OpenTSDB return a single query when the query is m=system.healthy{job=etcd_z1,job=etcd_z2}

**Comment by gaos1** [comment]
opentsdb just return two query result for the given query. Can Grafana sum them and show the sum result from multiple query results?

**Comment by gaos1** [comment]
opentsdb query: 
/api/query?start=1h-ago&m=sum:system.healthy{job=etcd_z1|etcd_z2}

opentsdb response:
[
    {
        "metric": "system.healthy",
        "tags": {
            "index": "0",
            "job": "etcd_z2",
            "role": "unknown"
        },
        "aggregateTags": [],
        "dps": {
            "1439790128": 1,
            "1439790188": 1,
            "1439790248": 1,
            "1439790308": 1,
            "1439790368": 1,
            "1439790428": 1,
            "1439790488": 1,
            "1439790548": 1,
            "1439790608": 1,
            "1439790668": 1,
            "1439790728": 1,
            "1439790788": 1,
            "1439790848": 1,
            "1439790908": 1,
            "1439790968": 1,
            "1439791028": 1,
            "1439791088": 1,
            "1439791148": 1,
            "1439791208": 1,
            "1439791268": 1,
            "1439791328": 1,
            "1439791388": 1,
            "1439791448": 1,
            "1439791508": 1,
            "1439791568": 1,
            "1439791628": 1,
            "1439791688": 1,
            "1439791748": 1,
            "1439791808": 1,
            "1439791868": 1,
            "1439791928": 1,
            "1439791988": 1,
            "1439792048": 1,
            "1439792108": 1,
            "1439792168": 1,
            "1439792228": 1,
            "1439792288": 1,
            "1439792348": 1,
            "1439792408": 1,
            "1439792468": 1,
            "1439792528": 1,
            "1439792588": 1,
            "1439792648": 1,
            "1439792708": 1,
            "1439792768": 1,
            "1439792828": 1,
            "1439792888": 1,
            "1439792948": 1,
            "1439793008": 1,
            "1439793068": 1,
            "1439793128": 1,
            "1439793188": 1,
            "1439793248": 1,
            "1439793308": 1,
            "1439793368": 1,
            "1439793428": 1,
            "1439793488": 1,
            "1439793548": 1,
            "1439793608": 1,
            "1439793668": 1
        }
    },
    {
        "metric": "system.healthy",
        "tags": {
            "index": "0",
            "job": "etcd_z1",
            "role": "unknown"
        },
        "aggregateTags": [],
        "dps": {
            "1439790083": 1,
            "1439790143": 1,
            "1439790203": 1,
            "1439790263": 1,
            "1439790323": 1,
            "1439790383": 1,
            "1439790443": 1,
            "1439790503": 1,
            "1439790563": 1,
            "1439790623": 1,
            "1439790683": 1,
            "1439790743": 1,
            "1439790803": 1,
            "1439790863": 1,
            "1439790923": 1,
            "1439790983": 1,
            "1439791043": 1,
            "1439791103": 1,
            "1439791163": 1,
            "1439791223": 1,
            "1439791283": 1,
            "1439791343": 1,
            "1439791403": 1,
            "1439791463": 1,
            "1439791523": 1,
            "1439791583": 1,
            "1439791643": 1,
            "1439791703": 1,
            "1439791763": 1,
            "1439791823": 1,
            "1439791883": 1,
            "1439791943": 1,
            "1439792003": 1,
            "1439792063": 1,
            "1439792123": 1,
            "1439792183": 1,
            "1439792243": 1,
            "1439792303": 1,
            "1439792363": 1,
            "1439792423": 1,
            "1439792483": 1,
            "1439792543": 1,
            "1439792603": 1,
            "1439792663": 1,
            "1439792723": 1,
            "1439792783": 1,
            "1439792843": 1,
            "1439792903": 1,
            "1439792963": 1,
            "1439793023": 1,
            "1439793083": 1,
            "1439793143": 1,
            "1439793203": 1,
            "1439793263": 1,
            "1439793323": 1,
            "1439793383": 1,
            "1439793443": 1,
            "1439793503": 1,
            "1439793563": 1,
            "1439793623": 1
        }
    }
]

**Comment by torkelo** [comment]
No, all other time series databases can sum series, this makes more sense to have in the time series database. Maybe open a feature request with OpenTSDB to be able to sum two series?

**Comment by gaos1** [comment]
thanks. I opened an enhancement request with opentsdb.  if opentsdb cannot add the feature easily, can Grafana add it? even other time series database supports the sum query on two series, it still makes sense to have some general and basic calculation on Grafana side. for example, for a response A and B series, I want to show A + 10%, or A*40% + B* 60%

**Comment by torkelo** [comment]
@gaos1 yes, but that is something you can do with Graphite easily. 

I will in the future provide a metric query engine that can transform metrics and combine them (for any data source), but this needs to be done in the grafana backend in order to now slow down the browser to much.

**Comment by gaos1** [comment]
when will the query engine feature be started as your estimation? or we can
talk more about this and probably I can help here.  almost half of the
charts in my dashboard requires this feature.

**Comment by torkelo** [comment]
@gaos1 it has already been started, but is complex feature and will probably take 1-2 months before it is seen in Grafana stable.

**Comment by gaos1** [comment]
Great. Look forward to the feature release. :)

**Comment by cixelsyd** [comment]
I believe that this one change would dramatically increase the 'single-stat feature uptake and usability' by a wide margin.  I have multiple lists of related counters that I would like to show the total for in the beautiful single stat presentation.  What are the plans for this?  Any good news?

**Comment by torkelo** [comment]
@cixelsyd I am not sure what you mean, singlestat already can show total (ie sum). Most capable TSDB
databases like graphite support summing multiple queries :)

**Comment by harloveleenKaur** [comment]
@torkelo  Is there a same option (summing multiple queries) for InfluxDB ?

**Comment by torkelo** [comment]
InfluxDB does not support that last time I checked

**Comment by tombinns** [comment]
Has there been any movement on this issue?

My specific issue is wanting to combine the count from multiple auto-scaling groups in AWS and display it as a Singlestat.

**Comment by torkelo** [comment]
this issue is closed, so no movement. The problem of summing many time series to one value is left to the query engine of what ever time series store you use.
