### ISSUE TITLE
Dashboard List panel - filter to exclude tags

### ISSUE THREAD

**Issue by Techno-than** [grafana/grafana#25311]
**Dashboard list panel - filter for excluding tags**: At present we have functionality of filtering dashboards to show in panel based on tags associated with dashboards, need a filter to exclude the dashboards which have certain tags.

**Why is this needed**: We had certain use case, where we didn't want to show the dashboard link in dashboard panel list which is displayed at present. It is not even highlighted or something. And when user clicks on the same dashboard link in dashboard panel while being on same dashboard, it has issues with template variable refreshing.

Currently, we have used a workaround to hide the links using custom css through boom theme plugin.

I think this needs in a way to have change the code in actual search dashboard functionality as well to be able to pass as 'tagsToExclude'

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
