### ISSUE TITLE
Admin permissions not granted after admin login under reverse proxy

### ISSUE THREAD

**Issue by thedeepc** [grafana/grafana#25324]
**What happened**:
We have Grafana set up under Apache's reverse proxy. We have the subpath specified as local and the domain/port specified as remote in Apache's reverse proxy configuration.
When a login is attempted, the login "succeeds" but does not actually grant access to the user beyond the login screen. If anonymous access is **disabled**, it returns the user to the login screen despite the logs declaring a successful login. If anonymous access is **enabled**, then it returns the user to the unauthenticated user view of the dashboard (in our case, the permission level was "Viewer").

It is worth noting that **without the reverse proxy, the default Grafana install does allow admin login and sets permissions appropriately**. This issue is occurring only under the Apache reverse proxy.

This is what is found from the logs on debug mode:
```t=2020-06-03T13:54:41+0000 lvl=dbug msg="user auth token created" logger=auth tokenId=5 userId=1 clientIP=192.168.146.10 userAgent="Mozilla/5.0 (Windows NT 6.3; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36" authToken=83deca9ea8ff620b4a04feb0c8b412e72928a90773e0009465bc26e07ebad183
t=2020-06-03T13:54:41+0000 lvl=info msg="Successful Login" logger=http.server User=grafanaadmin@localhost
t=2020-06-03T13:54:42+0000 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=0 orgId=1 uname= dashId=1 action=View
t=2020-06-03T13:54:42+0000 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=0 orgId=1 uname= dashId=1 action=Edit
t=2020-06-03T13:54:42+0000 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=0 orgId=1 uname= dashId=1 action=Edit
t=2020-06-03T13:54:42+0000 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=0 orgId=1 uname= dashId=1 action=Admin
```
**What you expected to happen**:
We expected that, upon successful admin login under the reverse proxy, we would be granted admin-level permissions with the Grafana dashboard.
**How to reproduce it (as minimally and precisely as possible)**:
Set up Grafana under Apache's reverse proxy. Include the following two lines:
`
proxy.reverse.pass.grafana.local=/grafana/
proxy.reverse.pass.grafana.remote=https://localhost:3000/
`
Attempt to login via Grafana presented through the reverse proxy page.
**Anything else we need to know?**:
We have unauthenticated user access set to Viewer. Grafana is embedded in an iFrame.
**Environment**:
- Grafana version: 7.0.0
- Data source type & version: Prometheus 2.13.1
- OS Grafana is installed on: Windows Server 2012
- User OS & Browser: Windows Server 2012 & Google Chrome 81.0.4404.122
- Grafana plugins: n/a
- Others: Apache reverse proxy

**Further investigation**
Further research has found that the issue is related to the fact that we are hosting the Grafana iFrame in a page with a different port. We have our website domain as accessible to a port X, while Grafana is hosted under port Y (we kept the default, 3000). When you access Grafana directly through port Y, even under proxy, the "Set-Cookie" response header with a grafana_sesion cookie is returned. However, when the same request with no changes but the URL are put through port X, no such response header containing grafana_session cookie is delivered. Unsure if this is an issue with the reverse proxy or with Grafana.

**Comment by thedeepc** [comment]
Further research has found that the issue is related to the fact that we are hosting the Grafana iFrame in a page with a different port. We have our website domain as accessible to a port X, while Grafana is hosted under port Y. When you access Grafana directly through port Y, even under proxy, the "Set-Cookie" response header with a grafana_sesion cookie is returned. However, when the same request with no changes but the URL are put through port X, no such response header containing grafana_session cookie is delivered.

**Comment by marefr** [comment]
This feels like a configuration error. Make sure to configure the [root_url](https://grafana.com/docs/grafana/latest/installation/configuration/#root-url) to your public facing URL.
