### ISSUE TITLE
Grafana 7 Table CSV Export missing

### ISSUE THREAD

**Issue by fl0wx** [grafana/grafana#25334]
**What happened**:
-  I cant find csv export when i click a panel and go to "more -> csv export??"
- when i pick inspect -> data and have a table with elastic data, then it doesnt export the table to csv but the data as objects.
**What you expected to happen**:
The presence of any csv export mechanism to export the table as it is like it was in Grafana 6*
**How to reproduce it (as minimally and precisely as possible)**:
click on https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1 -> "ES Metrics" -> More
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: elastic 
- OS Grafana is installed on: debian 9 
- User OS & Browser: chrome
- Grafana plugins: -
- Others: also doesnt work on play.grafana.com
https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1  on the tables

**Comment by peterholmberg** [comment]
The export to CSV has been moved to panel inspect, data tab. There's a Export to CSV button there. 
![Screenshot from 2020-06-04 09-00-17](https://user-images.githubusercontent.com/946275/83725213-d8497800-a641-11ea-99f6-1f569defc566.png)

**Comment by fl0wx** [comment]
@peterholmberg like i wrote in my issue: "when i pick inspect -> data and have a table with elastic data, then it doesnt export the table to csv but the data as objects". so export as csv under inspect isnt useful if you use transformations. proof images:
https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1 ES logs Query:
![grafik](https://user-images.githubusercontent.com/2448081/83789972-c85c8300-a697-11ea-8482-ddeabfc5ca6f.png)
And the downloaded csv looks even worse:
![grafik](https://user-images.githubusercontent.com/2448081/83790078-ec1fc900-a697-11ea-9675-37a0b49d4753.png)

So this isnt solved.

**Comment by dannyspijker** [comment]
I do have the same problem after upgrading to version 7. Would be nice if this issue can be reopened.

**Comment by fl0wx** [comment]
@peterholmberg ??

**Comment by nomar22** [comment]
I'm facing the same problem, it is not solved.

**Comment by ryantxu** [comment]
Looking at this issue... when everyone says "it is not solved"  are you using the elastic search datasource?  or in general?  Grafana 7 has an export CSV, so the issue was closed -- maybe we need a new issue about elastc search?

**Comment by rishabh-khurana** [comment]
yeah I am using infinity to fetch data from an API and facing the same issue

**Comment by mrcljx** [comment]
I have the same problem that transforms are ignored. My workaround just now was:

- Create snapshot
- Open snapshot
- Inspect -> Data

The data there has been transformed.
