### ISSUE TITLE
FieldConfig: Color option for string fields

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#25341]
**What happened**:
With #24829 the Stat Panel now supports multiple fields (or `labels`), other than just metric value, (big thank you).

However, changing the **Color** of Stat Panel (Threshold Base Color) only changes the color of the value field.

**What you expected to happen**:
All fields should use the same color except configured otherwise (overrides?).

**How to reproduce it (as minimally and precisely as possible)**:
- Create new dashboard, add `Stat` panel, choose `Fields` -> `All fields` and `Value` -> `Last not null`
- Use `Color mode` -> `Background` for better effect
- Use prometheus query `grafana_build_info` and `Format` -> `Table` or similar to get _fields_
- Change `Base` Color from Green to something else.

Only `Value` changes Color:

![FxnFlySfH5](https://user-images.githubusercontent.com/33002073/83692802-fb016f80-a5f4-11ea-9962-6f819a856b74.gif)

**Environment**:
- Grafana version: `Grafana v7.0.3 (00ee734baf)`
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows 10 `1909`
- User OS & Browser: Windows 10 `1909` , Firefox `76.0.1`

**Comment by peterholmberg** [comment]
Could be solved via https://github.com/grafana/grafana/pull/24829 ?

**Comment by Mario-Hofstaetter** [comment]
@peterholmberg I don't think so because #24829 is what enabled this new feature in `7.0.3`

The option is not available in `7.0.2` on https://play.grafana.org/d/emCF6llZk/stat-panel-issue?orgId=1&editPanel=2

**Comment by peterholmberg** [comment]
Oh I see!

**Comment by torkelo** [comment]
Threshold only applied to the numeric fields  

We have yet to add a fixed color option for string fields.

a bit related to this https://github.com/grafana/grafana/pull/24763

**Comment by tkinz27** [comment]
So unsure if this belongs in a new issue, but I was hoping to be able to display a prometheus label but color the text based ont the value. 

For instance if I have the metrics 
* `kube_cronjob_status_active cronjob="Cron Job 1" 1`
* `kube_cronjob_status_active cronjob="Cron Job 2" 0`

It be nice to be able to select the `cronjob` label to display but have `Cron Job 1` in green and `Cron Job 2` in red.

**Comment by torkelo** [comment]
With this PR you will be able to set a fixed color mode using an override rule 
https://github.com/grafana/grafana/pull/28039
