### ISSUE TITLE
Verify that 7.0.2 RPM/Debian packages don't mix OSS and Enterprise

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#25340]
A user reported the following:

```
yum install grafana-7.0.3-1.x86_64.rpm
Loaded plugins: fastestmirror
Examining grafana-7.0.3-1.x86_64.rpm: grafana-7.0.3-1.x86_64
Cannot install package grafana-7.0.3-1.x86_64. It is obsoleted by installed package grafana-enterprise-7.0.2-1.x86_64
Error: Nothing to do
```

Investigate what happened here.

**Comment by Zayan1221** [comment]
This is solution - It has been resolved now:
yum erase grafana-enterprise
wget https://dl.grafana.com/oss/release/grafana-7.0.3-1.x86_64.rpm
yum install grafana-7.0.3-1.x86_64.rpm
service grafana-server status
systemctl daemon-reload
service grafana-server restart

grafana-cli -v
Grafana CLI version 7.0.3

**Comment by Zayan1221** [comment]
But the initial problem still exist
it shows 7.0.2 on Grafana and Edit option still doesnot shows

**Comment by aknuds1** [comment]
@Zayan1221 You mean the Grafana server is v7.0.2 after installing v7.0.3? Have you tried restarting the server, to make sure version 7.0.3 is running?

**Comment by aknuds1** [comment]
@Zayan1221 How did you install grafana-enterprise-7.0.2-1.x86_64 in the first place?

**Comment by simonc6372** [comment]
@Zayan1221 If you're still having problems, can you try and send the output of 
yum updateinfo 
yum search grafana 
yum info grafana 
yum info grafana-enterprise 
rpm -qif $(which grafana-cli) 

That should hopefully give enough info to see what's going on on your system.

**Comment by aknuds1** [comment]
@Zayan1221 I just tested installing in a fedora:latest Docker container, Grafana server installs correctly and has version 7.0.3

```
$ curl -fLO https://dl.grafana.com/oss/release/grafana-7.0.3-1.x86_64.rpm
$ yum install grafana-7.0.3-1.x86_64.rpm 
$ service grafana-server start
```

**Comment by kylebrandt** [comment]
`curl 'https://packages.grafana.com/enterprise/rpm/repodata/repomd.xml'`

or (/oss) for the open source packages

Look at the URL, primary.xml.gz, for example it would contain something like:

```
<data type="primary">
  <checksum type="sha256">e2e7e6c73884bae6bb5ebc294dbed0e1e0010136d16c7095271c501f74ace7a0</checksum>
  <open-checksum type="sha256">a1da772cba47d5430b494339190007010bf35a128bc147f54dfc99410cb36ef2</open-checksum>
  <location href="repodata/e2e7e6c73884bae6bb5ebc294dbed0e1e0010136d16c7095271c501f74ace7a0-primary.xml.gz"/>
  <timestamp>1591199914</timestamp>
  <size>22394</size>
  <open-size>352640</open-size>
</data>
```

Curl that url, for example:

```
curl 'https://packages.grafana.com/enterprise/rpm/repodata/450c44e3e79f13796588fe06174e058473917ad576487fdf06c3b007744bbdb1-primary.xml.gz' | gunzip  | grep -i Obs -A 10 -B10
```

You will see entries like:

```
<rpm:obsoletes>
      <rpm:entry name="grafana"/>
    </rpm:obsoletes>
```

**Comment by Zayan1221** [comment]
Hello All - I have installed Grafana 7.0.3 fine and it shows the same version on Grafana Browser as well as 7.03, But the Edit option in Panels has been gone after this Upgrade.

The out for the above commands are below:
[root@rbialilnxp027v ~]# yum updateinfo
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
epel/x86_64/metalink                                     |  12 kB     00:00
 * base: mirrors.sonic.net
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.nodesdirect.com
 * updates: mirror.centos.iad1.serverforge.org
base                                                     | 3.6 kB     00:00
extras                                                   | 2.9 kB     00:00
grafana/signature                                        |  488 B     00:00
grafana/signature                                        | 2.9 kB     00:00 !!!
nodesource                                               | 2.5 kB     00:00
updates                                                  | 2.9 kB     00:00
yarn                                                     | 2.9 kB     00:00
updateinfo summary done
[root@rbialilnxp027v ~]# yum search grafana
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.tds.net
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.nodesdirect.com
 * updates: mirror.centos.iad1.serverforge.org
======================================================== N/S matched: grafana ========================================================
grafana-enterprise.x86_64 : Grafana
pcp-webapp-grafana.noarch : Grafana web application for Performance Co-Pilot (PCP)

  Name and summary matches only, use "search all" for everything.
[root@rbialilnxp027v ~]# yum info grafana
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.tds.net
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.genesishosting.com
 * updates: mirror.es.its.nyu.edu
Error: No matching Packages to list
[root@rbialilnxp027v ~]# yum info grafana-enterprise
Loaded plugins: fastestmirror
Loading mirror speeds from cached hostfile
 * base: centos.mirrors.tds.net
 * epel: mirror.sfo12.us.leaseweb.net
 * extras: mirror.genesishosting.com
 * updates: mirror.centos.iad1.serverforge.org
Installed Packages
Name        : grafana-enterprise
Arch        : x86_64
Version     : 7.0.3
Release     : 1
Size        : 144 M
Repo        : installed
From repo   : grafana
Summary     : Grafana
URL         : https://grafana.com
License     : unknown
Description : Grafana

[root@rbialilnxp027v ~]# rpm -qif $(which grafana-cli)
Name        : grafana-enterprise
Version     : 7.0.3
Release     : 1
Architecture: x86_64
Install Date: Wed 03 Jun 2020 11:45:31 PM CDT
Group       : default
Size        : 151469873
License     : unknown
Signature   : RSA/SHA256, Wed 03 Jun 2020 10:45:24 AM CDT, Key ID 8c8c34c524098cb6
Source RPM  : grafana-enterprise-7.0.3-1.src.rpm
Build Date  : Wed 03 Jun 2020 10:44:58 AM CDT
Build Host  : 7106fb81a925
Relocations : /
Packager    : contact@grafana.com
Vendor      : Grafana Enterprise
URL         : https://grafana.com
Summary     : Grafana
Description :
Grafana
[root@rbialilnxp027v ~]#

**Comment by aknuds1** [comment]
@Zayan1221 See #25352.

@simonc6372 Please see the user's report above.

**Comment by aknuds1** [comment]
Guess we can close this until we eventually find the problem is still around.
