### ISSUE TITLE
grafana 2.1 use Repeating Rows and Panels, url variable don't work

### ISSUE THREAD

**Issue by zjian1993** [grafana/grafana#2534]
hi, I have used the new feature "Repeating Rows and Panels" in grafana 2.1, but after setting Repeating Rows and Panels, the variable in the url not work, for example, we set templating variable named partner and open the link like http://grafana.mydomain.com/dashboard/db/partner?var-partner=movie . And we have a graph which use influxdb 0.88 as data source. the sql is "select sum(count) from "parnter" where $timeFilter and partnerid = '$partner' group by time($interval) fill(0) order asc"
But no matter what var-partner we use in url, the web are show the same partner graph which is the graph that we have not use var-partner.
Is someone have the same problem?

**Comment by torkelo** [comment]
Can you describe the dashboard more, what variables exists, which is being used to repeat panel (or row), what variables are used in the query, maybe show a redacted json of the dashboard?

**Comment by zjian1993** [comment]
{
  "id": 999,
  "title": "PayNotify",
  "originalTitle": "PayNotify",
  "tags": [
    "paynotify",
    "notify"
  ],
  "style": "light",
  "timezone": "browser",
  "editable": true,
  "hideControls": false,
  "sharedCrosshair": false,
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {
            "SEND_NOTIFY_FAIL": "#E24D42",
            "SEND_NOTIFY_SUCCESS": "#7EB26D",
            "success_rate": "#6ED0E0"
          },
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": 1,
            "rightMin": 0,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 2,
          "interval": ">30s",
          "legend": {
            "alignAsTable": false,
            "avg": true,
            "current": false,
            "hideEmpty": false,
            "max": true,
            "min": false,
            "rightSide": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "repeat": "partner",
          "scopedVars": {
            "partner": {
              "selected": true,
              "text": "2012",
              "value": "2012"
            }
          },
          "seriesOverrides": [
            {
              "alias": "sendpaynotify_rate.min",
              "yaxis": 2
            },
            {
              "alias": "success_rate",
              "yaxis": 2
            }
          ],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "alias": "$g",
              "column": "value",
              "function": "mean",
              "interval": "30s",
              "query": "select _mt_action, sum(count) from \"sendpaynotify\" where $timeFilter and partnerid = '$partner' group by time($interval), _mt_action fill(0) order asc",
              "rawQuery": true,
              "series": "select _mt_action, sum(count) from \"sendpaynotify\" where $timeFilter and partnerid = '2013091800010001' group by time($interval), _mt_action fill(0) order asc"
            },
            {
              "alias": "success_rate",
              "column": "value",
              "function": "mean",
              "interval": "30s",
              "query": "select rate_value from sendpaynotify_rate where $timeFilter  and _mt_action = 'SEND_NOTIFY_SUCCESS' and partnerid = '$partner' order asc",
              "rawQuery": true,
              "target": ""
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "$partner",
          "tooltip": {
            "shared": true,
            "value_type": "cumulative"
          },
          "transparent": false,
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "short",
            "short"
          ]
        }
      ],
      "title": "Row"
    }
  ],
  "nav": [
    {
      "collapse": false,
      "enable": true,
      "notice": false,
      "now": true,
      "refresh_intervals": [
        "5s",
        "10s",
        "30s",
        "1m",
        "5m",
        "15m",
        "30m",
        "1h",
        "2h",
        "1d"
      ],
      "status": "Stable",
      "time_options": [
        "5m",
        "15m",
        "1h",
        "6h",
        "12h",
        "24h",
        "2d",
        "7d",
        "30d"
      ],
      "type": "timepicker"
    }
  ],
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "templating": {
    "list": [
      {
        "allFormat": "glob",
        "current": {
          "tags": [],
          "text": "2012",
          "value": "2012"
        },
        "datasource": null,
        "includeAll": false,
        "multi": true,
        "name": "partner",
        "options": [
          {
            "selected": true,
            "text": "2012",
            "value": "2012"
          },
          {
            "selected": false,
            "text": "2013",
            "value": "2013"
          },
          {
            "selected": false,
            "text": "2014",
            "value": "2014"
          }
        ],
        "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d",
        "refresh_on_load": false,
        "type": "custom"
      }
    ]
  },
  "annotations": {
    "list": []
  },
  "refresh": "1m",
  "schemaVersion": 6,
  "version": 4,
  "links": []
}

**Comment by zjian1993** [comment]
like this json file, and open url http://mydomain/dashboard/db/paynotify?var-partner=2014 is not the graph of partner 2014, is 2012

**Comment by torkelo** [comment]
fixed in master and in v2.1.x branch

**Comment by harryshayne** [comment]
anyone can show me how to use the new feature "Repeating Rows and Panels" in grafana 2.1,i just know how to repeating Panals.

**Comment by torkelo** [comment]
Open row editor (green icon to the left to open row menu, then select row editor)
