### ISSUE TITLE
Angular panel additional menu items arent added in 7.0

### ISSUE THREAD

**Issue by Etzku** [grafana/grafana#25347]
**What happened**:
An angular panel plugin we use added its own items to the panels drop down menu using getAdditionalMenuItems, which is a method of panelCtrl that can be overridden. However in later versions this method seems to no longer be called. Only menu items returned on the event PanelEvents.initPanelActions (via PanelCtrl.getExtendedMenu) are turned into the new react menu items in getPanelMenu.ts. These created react menu items are added to the panels "more" submenu. GetAdditionalMenuItems let us make our own sub menu which is a much nicer way to use our plugin.

**What you expected to happen**:
Expected getAdditionalMenuItems to be called, and items to be added to the panel menu.

![image](https://user-images.githubusercontent.com/50619212/83722559-e0a3b200-a645-11ea-801b-705677e66cf9.png)

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to add a menu item using getAdditionalMenuItems in a panel.

**Anything else we need to know?**:
This issue might have come up in earlier versions than 7.0. We have been primarily using version 6.0.

**Environment**:
- Grafana version: 7.0
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome

**Comment by torkelo** [comment]
Sadly getAdditionalMenuItems is not supported anymore 

getExtendedMenu is the only supported way to add panel specific menu actions
