### ISSUE TITLE
Request: Filter Series

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#25357]
**What would you like to be added**:

I've a query which returns let's say 100 different time-series. I would like to have these 3 features in grafana:

* Display only top N series. (N should be selected by user, like 10-15)
* Filter/Hide series below a certain constant 'threshold'. This is like hide series with only zeroes / nulls features but I want to tell grafana to:

```
Hide series with mean below 20
Hide series with max below 20
Hide series with percentile(90) below 20
```
20 was arbitrary here.

* Filter/Hide series below a dynamic 'threshold'. In the end, grafana already collects all the series then hides them for both easy render and clear dashboards. So, we can apply mean, meadian or percentile operations across series. For example, there are 3 series in the img below and their avg's. We should take avg of these averages, or median of these averages. Then this new value will be our dynamic threshold, and we can say hide series below that.

![image](https://user-images.githubusercontent.com/43188411/83739965-ece83900-a65e-11ea-8610-03582f186723.png)

**Why is this needed**:

When we are working with queries that returns many time series things get messy. First of all graph becomes a spaghetti and hard to analyse. Also it's not elegant to look at. Lastly, browsers are having hard time to render all those pixels.

Visualizing time series in grafana is great but there are certain features that are hard to achive with queries. Examples above will make queries complicated and many data sources might be already missing them. Adding these to grafana would make grafana stronger in terms of  analysing data.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
