### ISSUE TITLE
Broken long variable dropdown

### ISSUE THREAD

**Issue by rakhadityap** [grafana/grafana#25356]
**What happened**:
I don't know hot to say this, it's broken.
Variables text are stuck behind every dashboard component.
![image](https://user-images.githubusercontent.com/10526365/83741386-562d7380-a682-11ea-80db-8f68c8469288.png)

**What you expected to happen**:
It used to be tidier on version 6.3.2
It will push all the panels down
like this:
![image](https://user-images.githubusercontent.com/10526365/83741060-ea4b0b00-a681-11ea-9146-c6d7b21881cf.png)

**How to reproduce it (as minimally and precisely as possible)**:
simply select so many template variables.

**Anything else we need to know?**:
this happened on any dashboards i have wether new or imported from old version.

**Environment**:
- Grafana version: 7.0.1 & 7.0.3
- Data source type & version: MySQL
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 6.4
- User OS & Browser: Windows 10 Chromium Edge
- Grafana plugins: -
- Others: -

**Comment by mertbakir** [comment]
I can confirm this happened after 7.0 and still persists at 7.0.2

**Comment by rakhadityap** [comment]
> I can confirm this happened after 7.0 and still persists at 7.0.2

and 7.0.3 too

**Comment by dprokop** [comment]
Should be fixed by https://github.com/grafana/grafana/pull/25801
