### ISSUE TITLE
Grafana json Plugin not making /query api request for backend in version 6.7.3

### ISSUE THREAD

**Issue by utkarshsudhakar** [grafana/grafana#25355]
Hi Team,
We have developed a backend for json plugin which gives the desired response based on the **/query** api request as mentioned in following post- 
https://grafana.com/grafana/plugins/simpod-json-datasource

We have developed following 3 endpoints-
**/test** - for testing datasource
**/search** - returns the parameters to be used in graph
**/query** - returns the json with timestamp and value.

we tried this in grafana version- 6.6 and working fine , but in **grafana version 6.7.3** the plugin is making only **/search** request and not the **/query** request.

Can you please let us know is it a known bug or something additional is needed in v.6.7.3?

![image](https://user-images.githubusercontent.com/17815552/83737921-478a9080-a671-11ea-8b4c-e27e3003a67c.png)

**Comment by peterholmberg** [comment]
Do you have any server logs or similar to share? Additionally I'd suggest asking these types of questions on the community site (community.grafana.com).

**Comment by utkarshsudhakar** [comment]
There was issue with the Grafana and plugin version.
Resolved the issue by downgrading the version.

Thanks!
