### ISSUE TITLE
Stat Panel: Thresholds do not work when using Value mappings with null text

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#25350]
**What happened**:
Threshold colors are not set when using a Value mapping to null text.

**What you expected to happen**:
Color should sell follow the initial value

**How to reproduce it (as minimally and precisely as possible)**:
Set thresholds of: Base, 1, 2 on background color
While having some stats with the value of 2 (red), set Value Mapping of 2 with no mapping text set. The color returns to the Base color. The color returns when the mapping text is changed to something that is not null.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: RedHat 7.8
- User OS & Browser: Chrome 81.0.4044.138 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
hi @maemigh,

I know it's been a while, but I tried reproducing this and I couldn't quite recreate your bug:

https://play.grafana.org/d/h_aHbKY7z/25350?orgId=1

do you think that the issue is still present? If so, please let me know. I will reopen and work on a fix. Thank you!
