### ISSUE TITLE
Entering text in the Value field in the Value Mappings section

### ISSUE THREAD

**Issue by xAnder1402** [grafana/grafana#25351]
Value in the Value Mappings section of the New Table panel does not support text input, only numbers.
Grafana 7.0.3

In old table:
![image](https://user-images.githubusercontent.com/12598781/83844222-3a23e380-a70f-11ea-813b-f0d35bf69249.png)

In new table:
![image](https://user-images.githubusercontent.com/12598781/83844307-6475a100-a70f-11ea-9ed6-05f475642c16.png)

**Comment by dprokop** [comment]
@peterholmberg did you have a chance to verify if this is a regression compared to 6.x?

**Comment by xAnder1402** [comment]
In grafana 6.7.3, entering a text value worked.

**Comment by Multiply** [comment]
Same problem here. Our old panels from grafana 6.x renders different than our new 7.x dashboards. In the old one we still see `type: Value to text`, where as the new one in 7.x only allows us to choose between `value` and `range`, where both have `<input type="number">` making it impossible to target non-number values upon saving the panel.

**Comment by peterholmberg** [comment]
@xAnder1402 and @Multiply does it actually transform values though? The valueMappings code from Jan 2019 does not support text as value.

https://github.com/grafana/grafana/blob/1378cadb685fe439c4f5523df27d4dcc30831a13/packages/grafana-data/src/utils/valueMappings.ts#L21

**Comment by therealcodlord** [comment]
@peterholmberg I can confirm that the old v6 table panel did and still does transform text values.

Just tested on latest nightly build v7.1.0~419f29efpre_amd64 with Grafana random walk datasource or MySQL data source. 

Steps to reproduce with MySQL:

Added (old) table panel.
Query: `select 'test' as 'col_1'`.
Table displays `test`.
Added column style to `col_1` and set to `Type: String`.
Added `Value to text` mapping `test` -> `transform`.
Table displays `transform`.

**Comment by Multiply** [comment]
@peterholmberg Yes, it works in our old panel.

![image](https://user-images.githubusercontent.com/453031/86018200-4c9aef80-ba25-11ea-8db3-9508e2a59649.png)

**Comment by peterholmberg** [comment]
Thank you! WIll continue to investigate!
