### ISSUE TITLE
Moving dashboard to the folder does not show the list of dashboards already present

### ISSUE THREAD

**Issue by cw-pratik** [grafana/grafana#25358]
I was trying to move a dashboard from the general folder to another already created folder. I did that. Then when I tried to open that folder, I am able to see only the dashboard that was moved and not the old dashboards that were already present

**What you expected to happen**:
Expected to see the new dashboards as well as the old dashboards in the folder

**How to reproduce it (as minimally and precisely as possible)**:
 - Open the dashboars in folder view
 - Select one dashboard that is to be moved
 - Move the dashboard to a folder that is already present
 - Expand the folder where the dashboard was moved
 - You will see only the dashboard that was moved and not the old dashboards

**Environment**:
- Grafana version: 7.0.3
- OS Grafana is installed on: ubuntu 14.04
- User OS & Browser: Mac, Chrome

**Comment by Clarity-89** [comment]
Hi, thank you for creating the issue. I tried replicating it with 7.0.3 docker image and for me it works as expected. Maybe you have dashboards with same names or ids somehow? Could you maybe provide a screen recording of the issue? Moving dashboards to another folder doesn't override the existing ones, only adds new dashboards.

**Comment by cw-pratik** [comment]
It is not overriding any dashboard. It seems to be a UI issue. What happens is that when you move a dashboard. And then open the folder in the UI. You can see only the new dashboard. Once you refresh the page, you will be able to see all the dashboards properly.

**Comment by Clarity-89** [comment]
I see the issue now. It happens if you move a dashboard to a non-expanded folder, where the dashboards haven't been fetched yet. Will be fixed soon.
