### ISSUE TITLE
grafana doesn't start if grafana-cli was executed (as root) prior to first grafana-server startup

### ISSUE THREAD

**Issue by andreasgerstmayr** [grafana/grafana#25367]
**What happened**:
If I run `grafana-cli` as root to set the admin password **before** starting grafana-server, the database and logfile are created as root and grafana-server doesn't start.

**What you expected to happen**:
The files are created with the correct user and grafana starts.

Possible solutions:
* we run grafana-cli always as the grafana user (`sudo -u grafana` in the grafana-cli wrapper script `grafana/packaging/wrappers/grafana-cli`)
* exit grafana-cli with an error message if it was started as root
* pre-create these files with correct user (grafana) as part of the package installation

**How to reproduce it (as minimally and precisely as possible)**:
```
podman run -d --systemd always --name grafana fedora:32 /usr/sbin/init
podman exec -it grafana bash
[root@c78fb900ce05 /]# dnf install -y wget
[root@c78fb900ce05 /]# wget https://dl.grafana.com/oss/release/grafana-7.0.3-1.x86_64.rpm 
[root@c78fb900ce05 /]# yum install -y grafana-7.0.3-1.x86_64.rpm 
[root@c78fb900ce05 /]# grafana-cli admin reset-admin-password testdemo
[root@c78fb900ce05 /]# ls -l /var/lib/grafana/
-rw-r--r--. 1 root root 483328 Jun  4 12:58 grafana.db
[root@c78fb900ce05 /]# ls -l /var/log/grafana/
-rw-r--r--. 1 root root 28719 Jun  4 12:58 grafana.log
[root@c78fb900ce05 /]# systemctl start grafana-server
Job for grafana-server.service failed because the control process exited with error code.
See "systemctl status grafana-server.service" and "journalctl -xe" for details.
[root@c78fb900ce05 /]# journalctl -e -u grafana-server
-- Logs begin at Thu 2020-06-04 12:55:53 UTC, end at Thu 2020-06-04 12:59:26 UTC. --
Jun 04 12:59:25 c78fb900ce05 systemd[1]: Starting Grafana instance...
Jun 04 12:59:25 c78fb900ce05 grafana-server[238]: Failed to start grafana. error: failed to initialize file handler: open /var/log/grafana/grafana.log: permission denied
Jun 04 12:59:25 c78fb900ce05 systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 04 12:59:25 c78fb900ce05 systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Jun 04 12:59:25 c78fb900ce05 systemd[1]: Failed to start Grafana instance.
```

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: -
- OS Grafana is installed on: Fedora
- User OS & Browser: -
- Grafana plugins: -
- Others: -

**Comment by andreasgerstmayr** [comment]
related to #16320

**Comment by aknuds1** [comment]
@torkelo do you have any advice on how to best solve this issue? The following two suggestions by the issue author sounds plausible to me:

* Modify the installation package's grafana-cli wrapper script to always use the grafana user (`sudo -u grafana` in grafana/packaging/wrappers/grafana-cli)
* exit grafana-cli with an error message if it was started as root (could use advice on whether this is a sound strategy or not)
