### ISSUE TITLE
Grafana Internal Metrics - Page Response Unknown

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#25362]
**What happened**:

I am not sure if it's related to new version but this happened after 7.0. I've used the same docker volume 6.7.3 doesn't return 'unknown' page responses while 7.0 does. Still, I'm not sure if this about version.

![image](https://user-images.githubusercontent.com/43188411/83754262-59b9fe00-a674-11ea-9f25-64b0feebcaa4.png)

I don't know how to troubleshoot these 'unknown responses'. Where should I look into?

**How to reproduce it (as minimally and precisely as possible)**:

* Activate internal grafana metrics and send to some datasource.
* Plot the page response graph.

**Environment**:
- Grafana version: 7.0, 7.0.1, 7.0.2 alpine docker image

**Comment by marefr** [comment]
The `page_response_status_total` code is logged as unknown if the response status code is not 200, 400 or 500. Please enable [router logging](https://grafana.com/docs/grafana/latest/installation/configuration/#router-logging) and turn on debug logging to inspect what requests are creating those. 

Could also enable [data proxy logging](https://grafana.com/docs/grafana/latest/installation/configuration/#logging).

**Comment by mertbakir** [comment]
Thanks for the information. I noticed that they are 302 redirects. Resulting from http_checks to main page which redirects to /login.
