### ISSUE TITLE
Incorrect message display for Gelf + Logstash + ElasticSearch in dashboards

### ISSUE THREAD

**Issue by kalemas** [grafana/grafana#25370]
**What happened**:
Incorrect display for specific index from elasticsearch datasource.

![RQRG8i3MPk](https://user-images.githubusercontent.com/638393/83764237-61809f00-a682-11ea-892b-973199ffd596.png)

and single data is:

```
{
  "_index" : "logstash",
  "_type" : "_doc",
  "_id" : "xxxxxxxxxxxxxxxxxxxx",
  "_version" : 1,
  "_seq_no" : 569,
  "_primary_term" : 1,
  "found" : true,
  "_source" : {
    "host" : "xxxxxxxxxxxx",
    "message" : "xxxxxxx xxxxx xxxxxxx, xxxxxxxxx...",
    "facility" : "xxxxxxxxxx",
    "line" : 32,
    "file" : "main.py",
    "level" : 6,
    "version" : "1.0",
    "function" : "<module>",
    "level_name" : "INFO",
    "@timestamp" : "2020-06-04T13:11:12.755Z",
    "source_host" : "x.x.x.x",
    "process_name" : "MainProcess",
    "@version" : "1",
    "pid" : 1,
    "tag" : "xxxxxxxxxx",
    "thread_name" : "MainThread"
  }
}
```

**What you expected to happen**:
The "message" field instead of "line"

**How to reproduce it (as minimally and precisely as possible)**:
The pipeline as follows: graypy python logging library -> logstash gelf input -> elasticsearch output without any transformation -> grafana

**Anything else we need to know?**:
In 6.7.4 this setup working, in explore metrics and inspect widgets i see correct message field but not at dashboards

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: ElasticSearch with "message" as message field and "level_name" as level
- User OS & Browser: Windows 10, Chrome

**Comment by IT307** [comment]
I'm seeing the same issue with filebeat->logstash->elasticsearch on grafana 7.0.3. Explore and Logs panel show the contents of field "line" instead of field "message". The log source field is set to "message" in the data source. This worked in grafana 6.
