### ISSUE TITLE
"pipe" syntax for graphite datasource

### ISSUE THREAD

**Issue by apla** [grafana/grafana#25379]
**What would you like to be added**:

Since version 1.1.1 graphite supports much cleaner query syntax using pipe symbol. https://github.com/graphite-project/graphite-web/pull/2042

Editing graphite functions will be much easier

**Why is this needed**:

Simple query like this one already unreadable:

```
aliasSub(aliasByTags(groupByTags(seriesByTag('plugin=memory', 'type_instance=~(?:buffered|cached|inactive)'), 'sum', 'host'), 'host'), '(.*)', '\1 cache')
```

Especially the part `(?:buffered|cached|inactive)'), 'sum', 'host'), 'host'), '(.*)', '\1 cache')`

but it can be written like

```
seriesByTag('plugin=memory', 'type_instance=~(?:buffered|cached|inactive)') | groupByTags('sum', 'host') | aliasByTags('host') | aliasSub('(.*)', '\1 cache')
```

Also it looks exactly like query in UI

**Comment by zoltanbedi** [comment]
Hi @apla,
Have you tried to run this query in the text editor mode in Grafana? Does that works for you? Have you seen this blog post https://grafana.com/blog/2018/01/11/graphite-1.1-teaching-an-old-dog-new-tricks/ ? It seems like that piping should work. I'm not exactly sure what the feature request is about.
