### ISSUE TITLE
Grafana 6.7.2 invalid Stackdriver requests

### ISSUE THREAD

**Issue by alexashley** [grafana/grafana#25373]
**What happened**:

We have multiple Stackdriver datasources using JWT authentication, one per project.  Each datasource uses the same service account with `roles/monitoring.viewer` attached on the org level. 

When upgrading to 7.0.3 (but also reproducible in 6.7.2), we noticed that the Stackdriver API calls for our alerts no longer seemed to include the project name:

```
t=2020-06-03T16:28:01+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://content-monitoring.googleapis.com/v3/projects//timeSeries
```

which results in a 400 from the Stackdriver API:
```
 logger=alerting.evalContext ruleId=72 name=$ALERT_NAME error="tsdb.HandleRequest() response error &{{\n \"error\": {\n \"code\": 400,\n \"message\": \"Name must begin with '{resource_container_type}/{resource_container_id}', got: projects/\",\n \"status\": \"INVALID_ARGUMENT\"\n }\n}\n A 0xc0007fc020 [] [] []}" changing state to=alerting
```

**What you expected to happen**:

The alert query would be updated to use the project name from the datasource. 

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Stackdriver datasource in 6.6.1
- Create an alert using the datasource, setting the alert to fire on execution error or timeout
- Upgrade Grafana to 6.7.2
- See that the alert state transitions

**Anything else we need to know?**:

Opening a panel with an alert and then saving the dashboard seems to fix the issue. Also when looking at the query in the UI, the project selector does show the correct project tied to the datasource. 

**Environment**:
- Grafana version: 6.7.2/7.0.3
- Data source type & version: Stackdriver
- OS Grafana is installed on: Running the `grafana/grafana:6.7.2` image in GKE 1.15 with COS
- User OS & Browser: macOS 10.14.6 / Chrome 83.0.4103.61
- Grafana plugins: N/A
- Others: N/A

**Comment by arteal** [comment]
From what I have written in https://github.com/grafana/grafana/issues/23688#issuecomment-642658875 I guess there will be no way to create graphs to utilize this fix in graphs created with Grafana 7.0.3, am I right ?

Still this is needed and I hope that #23688 will be resolved soon too.
Thanks
