### ISSUE TITLE
Req: Support snapshots with very slow queries (current limit is 4 seconds)

### ISSUE THREAD

**Issue by chudleycannon** [grafana/grafana#2537]
Hi,

When trying to view a snapshot dashboard I am getting an error "Problem! Unauthorized."

![image](https://cloud.githubusercontent.com/assets/9591897/9309531/2fd8a786-4502-11e5-92c9-baa9f2c8741d.png)

I can see where the graphs should be and their names etc but no actual graphs.

The request sent is: 

```
GET /api/metrics/test?from=1439815865016&maxDataPoints=100&to=1439819465016 HTTP/1.1
Host: localhoat
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
Referer: http://localhost/dashboard/snapshot/9ab518a4ZK3dKeoq0qCgf84J8X6WwHCm
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
Cookie: grafana_sess=61e04df7f6d9c03c

```

With the response:

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=UTF-8
Date: Mon, 17 Aug 2015 13:53:21 GMT
Content-Length: 27

{"message":"Access denied"}

```

A second request to login is made:

```
GET /api/login/ping HTTP/1.1
Host: localhost
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.155 Safari/537.36
Referer: http://localhost/dashboard/snapshot/otago6bh78OcC3o933eJY8iGygyvqW11
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-GB,en-US;q=0.8,en;q=0.6
Cookie: grafana_sess=61e04df7f6d9c03c
```

with the response:

```
HTTP/1.1 401 Unauthorized
Content-Type: application/json; charset=UTF-8
Date: Mon, 17 Aug 2015 13:56:07 GMT
Content-Length: 26

{"message":"Unauthorized"}

```

I can view the normal dashboards so it's not an issue with accessing graphite-web and it doesnt seem to work on snapshot.raintank.io either.

EDIT: I am running Grafana v2.0.2

**Comment by torkelo** [comment]
strange, both local and external snapshots work for me
https://snapshot.raintank.io/dashboard/snapshot/Dyiz79H55zZoyhekKHmP027fIqDziZwO
http://play.grafana.org/dashboard/snapshot/BSqmn44zyUGAld9wjAGGBtTHNNCYONaa


Do you have any special auth settings? auth proxy? any special panels?

**Comment by chudleycannon** [comment]
Most settings are default except for database and session (both postgres)

The most _unusual_ thing is we have it setup in AWS with 3 instances all pointing to the same database.

![grafana](https://cloud.githubusercontent.com/assets/9591897/9325276/081ccf2e-4589-11e5-9f6b-dd92f85ea6c0.png)

But it's not like I get a 404 it shows some of the dashboard just not the data.

<img width="1277" alt="screen shot 2015-08-18 at 09 17 57" src="https://cloud.githubusercontent.com/assets/9591897/9325427/270ba4c2-458a-11e5-9baa-31e93c056b95.png">

**Comment by torkelo** [comment]
How long does the metric queries take? when the snapshot is being created it will wait for all panels to refresh their data (and save the data), if this is not completed in 4 seconds the panels will not get any snapshotted data. 

Can you test snapshotting a single graph panel over a short time frame?

**Comment by chudleycannon** [comment]
That seems to be the issue.
Is there an easy way to increase the time or is that fixed in the code?

**Comment by torkelo** [comment]
currently it is fixed, but time series queries usually take 25 - 150ms, 

what query do have that takes 4 seconds?

**Comment by chudleycannon** [comment]
Quite a lot of our queries take 4 seconds or more. Our Graphite server is quite slow.

**Comment by christianchristensen** [comment]
xref: https://github.com/grafana/grafana/issues/1933

**Comment by ureesoriano** [comment]
I'd surely appreciate that timeout to be more dynamic/configurable as well; +1

**Comment by akrzos** [comment]
I suspect I am running into the same issue:

I am creating "snapshots" via the api (/render/dashboard-solo/db/) of various panels of grafana and occasionally some of my "snapshots" display two popups:

![10 16 31 16-tail-errors](https://cloud.githubusercontent.com/assets/6154223/13265838/2685f73e-da43-11e5-81d7-1e174a8dbbf6.png)
![overcloud-controller-0-all-cpu](https://cloud.githubusercontent.com/assets/6154223/13265840/280e3f6c-da43-11e5-8e22-2868044e8338.png)

In the grafana logs I see:
```
2016/02/23 15:29:45 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/openstack-general-system-performance?panelId=92&from=1455649200000&to=1455656400000&var-Cloud=westfordperf&var-Node=XXXXXXXX_localdomain&var-Interface=interface-test&var-Disk=disk-sda&width=1200
2016/02/23 15:29:46 [I] Completed [::1] - "GET /api/datasources/proxy/1/metrics/find/ HTTP/1.1" 401 Unauthorized 26 bytes in 339us
2016/02/23 15:29:46 [I] Completed [::1] - "GET /api/login/ping HTTP/1.1" 401 Unauthorized 26 bytes in 340us
...
2016/02/23 15:30:09 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/openstack-general-system-performance?panelId=1&from=1455649200000&to=1455656400000&var-Cloud=westfordperf&var-Node=overcloud-controller-0_localdomain&var-Interface=interface-test&var-Disk=disk-sda&width=1200
2016/02/23 15:30:09 [I] Completed [::1] - "GET /api/datasources/proxy/1/metrics/find/ HTTP/1.1" 401 Unauthorized 26 bytes in 594us
2016/02/23 15:30:09 [I] Completed [::1] - "GET /api/login/ping HTTP/1.1" 401 Unauthorized 26 bytes in 182us
2016/02/23 15:30:09 [I] Completed [::1] - "POST /api/datasources/proxy/1/render HTTP/1.1" 401 Unauthorized 26 bytes in 321us
2016/02/23 15:30:09 [I] Completed [::1] - "GET /api/login/ping HTTP/1.1" 401 Unauthorized 26 bytes in 187us
```

**Comment by torkelo** [comment]
there is a timeout option in the snapshot modal (introduced many versions ago) so we can close this.

**Comment by ipasic** [comment]
What about timeout option as a parameter for HTTP API  ? 
https://community.grafana.com/t/how-to-set-timeout-for-snapshot-when-creating-it-with-http-api/14922

Any plans for that one?

**Comment by YoninL** [comment]
Is the timeout only works in UI? I found that snapshots via API always has 401 unauthorized issue, can we somehow pass timeout settings to api as well?

**Comment by torkelo** [comment]
That would not work, as snapshots happen in the browser not the http backend api
