### ISSUE TITLE
Configured dingding alarm, why can't send out

### ISSUE THREAD

**Issue by Gliulei** [grafana/grafana#25372]
![image](https://user-images.githubusercontent.com/13186386/83780859-4df42900-a6c0-11ea-8625-37f019ad5163.png)
![image](https://user-images.githubusercontent.com/13186386/83780872-5482a080-a6c0-11ea-834b-b5ccae601256.png)

I configured the dingding alarm, why can't it be sent? I'm confused

**Comment by peterholmberg** [comment]
Please use community.grafana.com for questions.
