### ISSUE TITLE
URL Linking with parameters

### ISSUE THREAD

**Issue by minzhekang** [grafana/grafana#25383]
Hello all, i’ve recently added an external button to link my dashboard along with the time range, variable values parameters in the URL. However, i am intending to get the URL parameters through my external webserver, so I require to have absolute data that are best to be in epoch timings instead of the relative timings.

For example, from my dashboard, i am able to query the relative time ranges such as
“xx.xx.xx/grafana/?from=now-15m&to=now”, but what i would like to get is
“xx.xx.xx/grafana/?from=1591264576083&to=1591265476083”.

Is there anyway to convert the “now” keyphrase into something more code friendly like the epoch timing? I have also noticed that if i were to click on the “share dashboard” button on the top left, it is able to generate a URL and convert the relative timings to epoch timings.

Thanks.

edit: I have found a link to disable the custom time ranges from disable-unwanted-quick-ranges, however i am still unable to find the “boot.e4836696.js” file

**What would you like to be added**:
A way to disable to relative time range panel, only allowing the absolute time ranges, or convert the keyword "now" into epoch timings.

**Why is this needed**:
To allow time data variables to be passed easily into my system

**Comment by peterholmberg** [comment]
So you want grafana to interpolate relative time ranges from query parameters to epoch?

**Comment by minzhekang** [comment]
@peterholmberg Right, I would like to interpolate the relative time ranges to epoch in the URL.

**Comment by minzhekang** [comment]
@peterholmberg Hi, I have found a [package](https://pypi.org/project/dateparser/) to parse the relative dates and convert them. This feature is no longer required, thanks.
