### ISSUE TITLE
light/dark mode based on browser local storage

### ISSUE THREAD

**Issue by povilasv** [grafana/grafana#25384]
**What would you like to be added**:

I'm a fan of light mode, my colleagues are fans of dark mode. If I switch grafana to light mode, everybody shouts at me :boom: So can we make it that when I switch to light mode, it switches only for me based on browser local storage or cookie?

**Why is this needed**:

So that coworkers don't kill me :gun:

**Comment by peterholmberg** [comment]
You can change the theme in user settings.

**Comment by GregorB54321** [comment]
I would also appreciate that. Presentation according to browsers preference. Just like prometheus itself does it...
