### ISSUE TITLE
The DingDing Chinese instruction link is not valid

### ISSUE THREAD

**Issue by KEVISONG** [grafana/grafana#25389]
Hey there.

In [https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md](https://github.com/grafana/grafana/blob/master/docs/sources/alerting/notifications.md)

line 151: [Instructions in Chinese](https://open-doc.dingtalk.com/docs/doc.htm?spm=a219a.7629140.0.0.p2lr6t&treeId=257&articleId=105733&docType=1).

The link seems to be out of date since the page says "页面出错了，请稍候再访问。"

**Comment by oddlittlebird** [comment]
Can anyone provide the correct link? Or should I just remove it?

**Comment by ying-jeanne** [comment]
hey, this should be the correct link; https://developers.dingtalk.com/document/app/custom-robot-access

**Comment by achatterjee-grafana** [comment]
Thanks, @ying-jeanne. I will. update the link.

**Comment by achatterjee-grafana** [comment]
Fixed with PR https://github.com/grafana/grafana/pull/32514.
