### ISSUE TITLE
URL sent with Pushover alerts is to editPanel rather than viewPanel

### ISSUE THREAD

**Issue by Codelica** [grafana/grafana#25381]
**What happened**:
Pushover message to alert condition includes a link to "Show dashboard with alert", however that link is actually to "editPanel" for the alert panel creating the alert.

**What you expected to happen**:
I'd expect to either be linked to "viewPanel" for the alert that was triggered, or to the dashboard that including the panel triggering the alert.  The later makes more sense based on the current link text : "Show dashboard with alert"

**How to reproduce it (as minimally and precisely as possible)**:
Create any alert panel targeting Pushover and trigger the alert condition.

**Anything else we need to know?**:
Not that I know of.

**Environment**:
- Grafana version: 7.0.1
- Data source type & version: InfluxDB
- OS Grafana is installed on:  Ubuntu 18
- User OS & Browser:  MacOS Catalina & Chrome
- Grafana plugins:  Several but not involved.
- Others:

**Comment by McAnix** [comment]
+1 on this as it affects my business users who don't have edit permissions.

**Comment by kogent** [comment]
when a user who doesn't have edit permissions or a dashboard is marked not editable (eg- when doing dashboards as code) and they click on an alert that takes them to the editPanel linked page, you are taken to the full dashboard with an error in the top right of the page
![image](https://user-images.githubusercontent.com/796/94728838-b1603180-0315-11eb-91ae-8eee696d15eb.png)

This makes the alert links much less useful when trying to follow the [high optimized maturity model](https://grafana.com/docs/grafana/latest/best-practices/dashboard-management-maturity-levels/#high---optimized-use) that you recently published.

**Comment by kohts** [comment]
+1, guys, please upvote the issue

**Comment by andy-paine** [comment]
I think this should be fixed by [this commit](https://github.com/grafana/grafana/commit/6d0a98b2495393cd68bbf6f24b96931a7d8bb1e1) so should be in the next release 🎉

**Comment by marefr** [comment]
Fixed by #27378
