### ISSUE TITLE
Auto number in K range have wrong thousand separator formatting

### ISSUE THREAD

**Issue by Sarke** [grafana/grafana#25388]
**What happened**:

Auto numbers are wacko.

![image](https://user-images.githubusercontent.com/2719310/83845700-43d12b00-a6be-11ea-90e0-2566390bc64c.png)

**What you expected to happen**:

`1976` should be `1.97 K` or better yet just `1,976`.
`22770` should be `22.77 K`.

**How to reproduce it (as minimally and precisely as possible)**:

[test.sql](https://github.com/grafana/grafana/files/4734388/test.sql.txt)
[paneltest.json](https://github.com/grafana/grafana/files/4734389/paneltest.json.txt)

**Anything else we need to know?**:

Yes, having more than 2 decimals for the K range is stupid.  Why output `1.234 K` when you can just have `1,234`?  See https://github.com/grafana/grafana/issues/11732#issuecomment-632466775

**Environment**: Docker Swarm
- Grafana version: 7.0.1
- Data source type & version: PostgreSQL 11.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit (docker)
- OS Grafana is installed on: Official docker release
- User OS & Browser: Ubuntu MATE 18.04, both Chrome and Firefox affected.
- Grafana plugins: Pie Chart
- Others: ?

**Comment by torkelo** [comment]
This is not about thousand separators but about  decimal symbol.  When grafana writes `1.9760 K`  it is not `1960 000`  but a decimal point

**Comment by torkelo** [comment]
the number of decimals should be better in 7.3 and even more so in 7.4
