### ISSUE TITLE
LDAP groups should also support searching and not assume MemberOf

### ISSUE THREAD

**Issue by choffee** [grafana/grafana#2538]
The MemberOf field is a feature of Windows AD I think. 
It would be good if when the MemberOf field in the ldap users is populated in the searchForUser function of pkg/login/ldap.go it could also search for the groups that are defined in the config and if the user is in those groups add them to the MemberOf field.

So essentially looping over a.server.LdapGroups and doing an ldap search for the user in each of those groups and if it finds them adding that to the local MemberOf array.

**Comment by torkelo** [comment]
memberOf is not a windows AD feature, available in most LDAP system, for example OpenLDAP and others.

If what you suggest can be done in an efficient manner than I am open for it :)

**Comment by drawks** [comment]
:+1:

**Comment by abligh** [comment]
I've fixed this in https://github.com/grafana/grafana/pull/2928

**Comment by atdt** [comment]
:+1: 

This would be resolved by landing either of #2928 or #2746.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/2928
