### ISSUE TITLE
Wrong Scale with Unit Energy, Watt

### ISSUE THREAD

**Issue by s1738berger** [grafana/grafana#25397]
There seems to be a bug when using Energy, Watt as unit. Easiest to explain with attached picture:

![grafik](https://user-images.githubusercontent.com/368973/83881119-77ed3000-a740-11ea-87ee-50983379e94c.png)

That strange behaviour only seems to ocur with this unit ( haven't tested all ... )

Grafana is actual 7.0.3, but was already in 6 on Ubuntu 18.

**Comment by peterholmberg** [comment]
Thanks for reporting, could you add more information on how to reproduce. Please use the bug issue template.
