### ISSUE TITLE
Enhance data-link variables with ISO8061 time variable

### ISSUE THREAD

**Issue by sta-szek** [grafana/grafana#25396]
**What would you like to be added**:
Currently there are `$__from` and `$__to` variables which are timestamps.
Unfortunatelly, in order to create proper link to kibana, with fixed time, we have to pass ISO8061 time format.
Please add another variables, or functions, which will allow to convert value from one format (timestamp) to another (e.g. ISO 8061).

**Why is this needed**:
To render proper URL to kibana.
I am pretty sure one will find more usages for it.

Related links: 
https://discuss.elastic.co/t/help-required-for-kibana-link-redirection-from-grafana/191126/3
https://github.com/grafana/grafana/issues/1909

**Comment by jnsvd** [comment]
+1

We cannot redirect to Kibana right now, it fails to parse the URL. Please allow more time formats or otherwise add functions that we can apply to the variables.

**Comment by pessoa** [comment]
+1

**Comment by rgrizzell** [comment]
+1

**Comment by torkelo** [comment]
This was implemented and added in 7.1.2 

you can now format __from and __to like ${__from:date:iso} , actually ${__from:date} is enough as iso is the default date format 

https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__from-and-__to
