### ISSUE TITLE
Special character in avatar endpoint will crash the Grafana process

### ISSUE THREAD

**Issue by jordyv** [grafana/grafana#25393]
Not sure if I should report this because it's already fixed in the 6.7.4 and 7.0.2, but in earlier Grafana versions it's possible to let crash the Grafana process by using a special character in the avatar URL. PR https://github.com/grafana/grafana/pull/25322 fixed this already because of the regex check for the hash.

**What happened**:
Grafana crashes if I send a request to the avatar URL with a special character (null byte, back space, new line, carriage return, etc.).
The 'fetch' method (https://github.com/grafana/grafana/blob/v6.7.3/pkg/api/avatar/avatar.go#L206) doesn't check if the URL parsing returned an error. If Go can't parse the URL (due to the special chars), http.NewRequest returns the error. In the code the error won't get checked so any call on 'req' will cause a nil pointer dereference error and due to the panic Grafana will crash.

**What you expected to happen**:
The error is checked and Grafana won't crash.

**How to reproduce it (as minimally and precisely as possible)**:
Start Grafana (v6.7.3 or earlier or v7.0.2 or ealier) and call the avatar URL with a special character.
I used 'http://localhost:3000/avatar/abc%00', but I also tested this with '%08', '%0a' and '%0d'.

![grafana_dos_small](https://user-images.githubusercontent.com/8904537/83865603-b5dd5a80-a726-11ea-9c23-97cb629faea5.gif)

**Anything else we need to know?**:
I used the Docker images to run Grafana.

**Environment**:
- Grafana version: 6.7.3 and earlier, 7.0.2 and earlier
- Data source type & version: Docker
- OS Grafana is installed on: 
- User OS & Browser: OSX
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
Thanks for reporting but since this is fixed in the latest versions of v6 and v7 we see no real reason to fix this in earlier major versions.
