### ISSUE TITLE
Wrong Scale with Unit Energy, Watt

### ISSUE THREAD

**Issue by s1738berger** [grafana/grafana#25399]
**What happened**:
Error in scale when using unit Energy, Watt. Twice showing 2kW. That strange behaviour only seems to ocur with this unit ( haven't tested all ... )

![grafik](https://user-images.githubusercontent.com/368973/83881119-77ed3000-a740-11ea-87ee-50983379e94c.png)

**What you expected to happen**:
0 W, 500 W, 1 kW, 1.5 kW, 2kW

**How to reproduce it (as minimally and precisely as possible)**:

![grafik](https://user-images.githubusercontent.com/368973/83882439-69077d00-a742-11ea-95de-f8a0b5a7632b.png)

Feed data from 0 ... 2000

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.0.3,
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu 18
- User OS & Browser: Firefox 76, Mac
- Grafana plugins: 
- Others:

**Comment by peterholmberg** [comment]
Thanks!

**Comment by s1738berger** [comment]
Well, I think when Decimals is set to 0, this the desired behaviour. 1.5 kW is correctly rounded to 2 kW :-)
I think this issue can be closed.
