### ISSUE TITLE
No info for users about limited response data up to 100 metrics in cloudwatch datasource

### ISSUE THREAD

**Issue by tarfik** [grafana/grafana#25400]
**Steps to reproduce**:
Create a graph using cloudwatch datasource and configure query for multiple metrics.

**Actual Result**:
"No data" on the graph.

**Expected Result**
Error with info about metric limit exceeded.

**Relevant WCAG Criteria:**
https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#error-identification

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: cloudwatch build in 7.0.0 grafana
- User OS & Browser: macOS, chrome
- Others:

**Comment by mchene** [comment]
Hi Tarfic, are you able to see any CloudWatch metrics when editing a graph panel or does this issue only happen when you have multiple queries?  Can you also confirm if this happens with using only metrics or are you using CloudWatch metric math, https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html?
Thanks, Marc

**Comment by sunker** [comment]
@tarfik when the 100 metrics per response limit is reached, a warnings is displayed and it's been like that for about a year. The 100 metrics that was returned will still be rendered in the graph.

<img width="415" alt="Screen Shot 2021-01-12 at 15 46 30" src="https://user-images.githubusercontent.com/2388950/104329822-a9f01d00-54ed-11eb-8ec0-bec19be34728.png">

**Comment by tarfik** [comment]
thanks
