### ISSUE TITLE
API does not return correct Panel Id (always 0)

### ISSUE THREAD

**Issue by Bukran** [grafana/grafana#25405]
**What happened**:
Getting dashboard info via API returns 0 for every panel inside dashboard

**What you expected to happen**:
panels Id should be 1, 2, 3, 4, 5, for example, if my dashboard contains 5 panels

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard including one or more panels via API (POST /api/dashboards/db)
Then, get this dashboard by uid via API (GET /api/dashboards/uid/{uid})

**Anything else we need to know?**:
Panels id are correct when you inspect the dashboard via GUI (Dashboard settings > JSON model) but incorrect when got from the API.

**Environment**:
- Grafana version:
7.0.3

- Data source type & version:
InfluxDB 1.7.10

- OS Grafana is installed on:
Using docker image grafana/grafana:7.0.3

- User OS & Browser:
Windows 10 x64, Chrome

- Grafana plugins:
None. Clean install

- Others:

**Comment by torkelo** [comment]
The panel ids are assigned by the UI, so they need to be in the panel json when you save as well

**Comment by Bukran** [comment]
> The panel ids are assigned by the UI, so they need to be in the panel json when you save as well

Thank you very much.
I wrongly assumed that leaving every panel Id = 0 will lead to a proper assignation by the API. So, if anyone reads: when you build a dashboard via API, panel Ids must also be set in the json.
