### ISSUE TITLE
Provisioned dashboards with editable: false shouldnt be updated through the api

### ISSUE THREAD

**Issue by yeplaa** [grafana/grafana#25406]
I use the dashboard provisioning functionality  on Grafana 6.6.2 : 

      # config file version
      apiVersion: 1
      providers: 
      - name: 'dbms_dashboards'
        orgId: 1
        folder: 'dbms'
        folderUid: '1'
        type: file
        disableDeletion: true
        editable: false
        updateIntervalSeconds: 10
        allowUiUpdates: false
        options:
          path: /var/lib/grafana/dbms-dashboards

I use "editable: false" option because I don't want the dashboards not to be updated by the users.

**What happened**:

With the API by CLI, i can update my dashboaards. 
By GUI, it's not possible to update the dashboards as expected. 
 
**What you expected to happen**:

I would that the dasboards cannot be modified even by API.

**How to reproduce it (as minimally and precisely as possible)**:

I reproduce the problem every time.

**Anything else we need to know?**:
no

**Environment**:
- Grafana version: 6.6.2
- Data source type & version: Prometheus 2
- OS Grafana is installed on: I use grafana:6.6.2 in Container from Dockerhub repo. 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by AgnesToulet** [comment]
Hi, 
Actually, the `editable` field is related to the UI behavior (do the "edit" buttons should be displayed on the dashboard or not) but it doesn't say if a dashboard is "updateable" or not.
If you really need a behavior like the one you describe, you can create a feature request for making it possible to create dashboards that aren't updateable through the API and that will only allow changes through provisioning.
