### ISSUE TITLE
Ldap problem

### ISSUE THREAD

**Issue by mudisama** [grafana/grafana#25409]
**What happened**:
The configurantion on /etc/grafana/ldap.toml my host as configured with 172.25.1.50 this is my AD server, but the error log is with remote_addr different, the error is:

t=2020-06-05T14:33:48-0300 lvl=eror msg="No user was found in the LDAP server(s) with that username" logger=context userId=1 orgId=1 uname=admin error="Invalid Username or Password" remote_addr=192.168.240.254

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version:
- OS Grafana is installed on: CentOs 7.4.1708
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
that remote_addr is the server making the http request
