### ISSUE TITLE
When image rendering fails the telegram alert should be sent without image instead of being muted

### ISSUE THREAD

**Issue by fvigotti** [grafana/grafana#25415]
**What happened**:

Telegram notification channel failed to send alert when image rendering failed.

**What you expected to happen**:

An alert to be sent without an image.

**How to reproduce it (as minimally and precisely as possible)**:

Setup a telegram notification channel (with image) and send an alert without setting up image rendering configured.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.1
- Others: telegram notification channel

Original issue:

> the alert is important,
> but the current behaviour in version 7.0.1  + separated renderer + telegram alerting is :
> if  the renderer fail to build the image, telegram webhook return error 400 code, and nothing is sent..
> I think that grafana could at least try to re-contact the telegram webhook without the image ( maybe add *image error* to the code ) 
> 
> to further exacerbate the situation there is the "test" link in the "notification channel" section which send a pre-built image ( not built using the renderer ) so this give a false "ok" message..
> while instead if the renderer have issues .. no alert will be ever sent to telegram.
> 
> Thank you :) 
>

**Comment by ying-jeanne** [comment]
I did a quick test today, with the telegram notification setup without image rendering configured. I still able to receive the alert notification with an image as following:
![image](https://user-images.githubusercontent.com/74549700/103375325-3eb04f00-4ada-11eb-8ef3-06c0a0ffbf1e.png)

The suggestion in the initial issue seems better (use the prebuild image that is the same as test link one).
![image](https://user-images.githubusercontent.com/74549700/103375424-8636db00-4ada-11eb-96ce-2b26523d9c32.png)

**Comment by ying-jeanne** [comment]
@fvigotti Hi, Thanks for the logged ticket :).  I just did a test on the problem, it seems during the time, it is solved, could you just retry and let me know if you still having the issue?

**Comment by fvigotti** [comment]
Hi, I'm sorry but right now I don't remember what I've done in my setup to fix but the issue is fixed right now for me.. I don't know why I've left this issue opened if I just forgot to close it .. Probably the problem was due by my current kubernetes container isolation setup + changes in how images are rendered in new releases of grafana.. 
I'm going to close the issue I'll let you know if I have updates about it..

Thank you,
Francesco
