### ISSUE TITLE
V7.0.3- Table column sort is broken for numbers with different precision

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25412]
Table column sort is broken for numbers with different precision  

![image](https://user-images.githubusercontent.com/55378597/83911075-4ee69280-a774-11ea-9c27-f4f0b0b4fda6.png)

it works fine for numbers having the same precision :

![image](https://user-images.githubusercontent.com/55378597/83911609-3b87f700-a775-11ea-8681-5582dc9c2ceb.png)

**Comment by aerosadegh** [comment]
I have the same problem.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/14781 

Fix incoming https://github.com/grafana/grafana/pull/25421
