### ISSUE TITLE
cannot configure the column style after upgrade to 7.0.3

### ISSUE THREAD

**Issue by gaimereil** [grafana/grafana#25425]
**What would you like to be added**:
I can configure teh column style in table panel like before.
For example,
the data is "2020-01-01 09:00:00" is shown like "2020-01-01" by setting the column style.
**Why is this needed**:
It is very useful.

**Comment by torkelo** [comment]
duplicate of #24655  , fix incoming https://github.com/grafana/grafana/pull/25195   (Using override & custom unit)
