### ISSUE TITLE
Add search to the panel edit mode options

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25426]
To improve the experience when working with options in panel editor side pane, especially for panels with loads of options, a search would be nice.

TODO: 
- [ ] Prepare design sketches for the search results.
  - [ ] Question: How should the options be grouped in the results?
  - [ ] Question: What information about the option should be visible in the search results?
  - [ ] Question: What should be the scope of the search query (option names, descriptions?)
- [ ] Bring back UI input for search in the tabs bar of the side pane.
  @torkelo added this in work for 7.0, but then we decided to remove it as there was no space for implementing this in 7.0. Should be easy to bring back.
- [ ] Dev
- [ ] Update documentation

**Comment by dprokop** [comment]
@sarlinska `Prepare design sketches for the search results.` deserves an issue on UX backlog board. I've already added this "project" to your Monday board last week :)

**Comment by torkelo** [comment]
Done!
