### ISSUE TITLE
DataSources: Be able to view & delete data sources using uninstalled plugins 

### ISSUE THREAD

**Issue by rawsGit** [grafana/grafana#25422]
Grafana v7.0.3 (00ee734baf)
Issue: Grafana TestData Datasource 
 
 When attempting to delete by ID : Not Found
curl --user user:password  -H "Content-Type: application/json-rpc" -X PUT http://localhost:3000/api/datasources/ -d'
{
DELETE /api/datasources/1 HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer myveryveryveryverysupersecureextralongkeygoeshere
}'
{"message":"Not found"}[root@zabbix00 testdata]#

When attempting to delete by name : Not Found
curl --user user:password  -H "Content-Type: application/json-rpc" -X PUT http://localhost:3000/api/datasources/ -d'
{
DELETE /api/datasources/name/ grafana-testdata-datasource HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer myveryveryveryverysupersecureextralongkeygoeshere
}'
{"message":"Not found"}[root@zabbix00 testdata]#
When attempting to delete by name w/ POST:
curl --user user:password  -H "Content-Type: application/json-rpc" -X POST http://localhost:3000/api/datasources/ -d'
{
DELETE /api/datasources/name/ grafana-testdata-datasource HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer myveryveryveryverysupersecureextralongkeygoeshere
}'

[{"classification":"DeserializationError","message":"invalid character 'D' looking for beginning of object key string"},{"fieldNames":["Name"],"classification":"RequiredError","message":"Required"},{"fieldNames":["Type"],"classification":"RequiredError","message":"Required"},{"fieldNames":["Access"],"classification":"RequiredError","message":"Required"}][root@zabbix00 testdata]#

**Comment by rawsGit** [comment]
Update: Additional Log infografana-server[4799]: t=2020-06-07T12:58:11-0500 lvl=eror msg="Could not find plugin definition for data source: grafana-testdata-datasource"
:

**Comment by rawsGit** [comment]
![image](https://user-images.githubusercontent.com/24832389/83976741-8f075b80-a8c1-11ea-9e87-4b400f58677e.png)
![image](https://user-images.githubusercontent.com/24832389/83976748-97f82d00-a8c1-11ea-83d3-34ab1392fdc2.png)

**Comment by torkelo** [comment]
In the data_source table, update the type column for this data source to just `testdata`

**Comment by rawsGit** [comment]
@torkelo was easy enough. SQLite DB Browser is my new friend. Thanks!
