### ISSUE TITLE
Panel Edit: Enable collapse/expand of all options sections in the panel side pane

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25431]
Add button enabling expanding/collapsing all of the options within the side pane.

TODO:
- [ ] Consult with @grafana/grafana-labs-ux-design what is the best UI solution for this proble
- [ ] Update panel edit documentation

**Comment by seriych** [comment]
It would be convenient "solo mode": automatic collapse all options sections except last opened options section.
