### ISSUE TITLE
Panel Edit: Implement change indicators for options

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25430]
The change indicators are an important feature that will help people understand which options in options were modified in the panel. 

Design proposal for this feature is available here: https://www.figma.com/file/LJtrlpFTAZEDgnS8COtMSL/Panel-edit?node-id=427%3A0

Whenever we start this project we need to go through the design together with @sarlinska to prepare the exact scope of the work.

**Comment by ashharrison90** [comment]
@torkelo i'm wondering whether your PR (https://github.com/grafana/grafana/pull/40250) closes this issue? 🤔

**Comment by torkelo** [comment]
no, this is something else. Not sure this is needed, more important when we users can change defaults
