### ISSUE TITLE
Panel Edit: double click on viz type should collapse the visualization picker

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25434]
Prior 7.0 double-clicking on the element on the **Visualizations list** made the viz picker to collapse. We should bring back this behavior.

- [ ] Brind back double-click behaviour on the viz picker list
- [ ] Add tooltip with information about the behaviour when user clicks on the active element on the VizPicker
- [ ] Add information about this interaction to the panel edit documentation

**Comment by peterholmberg** [comment]
Spent some time researching this today, here's my findings:

### Approach #1
Use the pre [7.0 logic](https://github.com/grafana/grafana/blob/v6.7.0/public/app/features/dashboard/panel_editor/VisualizationTab.tsx#L153) . This was fairly easy to implement but it comes with a severe downside in my opinion. 

If a VizPickerPlugin is selected, clicking on it again at any time will close the OptionGroup. Think of this scenario: Select the Table viz, click some of the options and then go back to click the Table viz in the VizPicker. This will collapse the OptionGroup. 


### Approach #2
Use RxJS. This adds some more complexity but is doable-ish. However, there's very little support in OptionGroup for controlling its expanded/collapsed state. So this means adding callbacks and passing these through multiple components.

Another issue is that collapsed/expanded state is save in localStorage, we might want to add a reducer to manage this expanded/reduced state. This might make more sense to do in another PR.
