### ISSUE TITLE
Issue with teams and external group sync

### ISSUE THREAD

**Issue by TheSilverHawkx** [grafana/grafana#25441]
Hello,

Recently I got into using external group sync to manage the permissions in my environment, and one error that occurred many times is "error while trying to authenticate user".
This error pops when a user is manually added to a group which has active external group sync, and then adding them to that external group without removing them afterwards. 

**Background:**
- Grafana 6.5.2 Enterprise, running on RHEL 7.6.
- LDAP authentication enabled.
- server group mapping:
`[[servers.group_mappings]]
  group_dn="*"
  org_role = "Viewer"
`
- Not using Active sync.

If I missed anything I'll add.

**Replicate problem:**
1. Create a Group via **Configuration>Teams>New Team**.
2. Add an LDAP user to the group manually.
3. Add an external group sync with a group this user is a part of.
4. Logout (if needed) and then log in.

**Log:**
` t=2020-06-07T17:49:26+0300 lvl=dbug msg="LDAP users found" logger=ldap users="([]*models.ExternalUserInfo) (len=1 cap=1) {\n (*models.ExternalUserInfo)(0xc00056c6c0)({\n  OAuthToken: (*oauth2.Token)(<nil>),\n  AuthModule: (string) (len=4
) \"ldap\",\n  AuthId: (string) (len=89) \"CN=מישאל גולן - Mishael Golan,OU=Users,OU=**REDACTED**\",\n  UserId: (int64) 0,\n  Email: (string) \"\",\n  Login: (string) (len=9) \"mishael_g\",\n  Name: (string) (le
n=13) \"Mishael Golan\",\n  Groups: ([]string) (len=165 cap=256) {**REDACTED**}}}"`

`t=2020-06-07T17:49:26+0300 lvl=dbug msg="Adding user to team" logger=group-sync org=1 user=mishael_g team=11`

`t=2020-06-07T17:49:26+0300 lvl=eror msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="User is already added to this team"`

`t=2020-06-07T17:49:26+0300 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=500 remote_addr=10.10.171.132 time_ms=167 size=53 referer=https://vmgrafana1:3000/login`

**Pictures:**
1. Team with mixed manually added and synced users:
![image001](https://user-images.githubusercontent.com/32996317/84004670-95a2db00-a974-11ea-8064-c10272f1ac6a.png)
while most of the member will be able to log in, user _nir_bi_ won't be able.

2. Failed login (disregard ie, a user sent me this):
![grafana-error-login](https://user-images.githubusercontent.com/32996317/84004115-be76a080-a973-11ea-8a0a-4b553289b98b.png)

**Closure:**
Is that an expected behavior? I'd expect the user to be overwritten or updated, instead of throwing "unable to authenticate" error which isn't very informative for this kind of error.

Best Regards,
Omer

**Comment by xlson** [comment]
Thanks for the detail report. I'll look into this, it seems like a bug. Is the user able to login after being removed manually from the team?

**Comment by TheSilverHawkx** [comment]
> Thanks for the detail report. I'll look into this, it seems like a bug. Is the user able to login after being removed manually from the team?

Yes, once the user is removed from the group and added by the external group sync process - everything works fine.

**Comment by xlson** [comment]
Thanks. Should be easy to fix.

**Comment by mckn** [comment]
@xlson was this fixed in the 7.0.4 version?

**Comment by xlson** [comment]
@mckn it wasn't. But I'll try to get it into 7.1-beta3 or 7.1 stable.

**Comment by mckn** [comment]
> @mckn it wasn't. But I'll try to get it into 7.1-beta3 or 7.1 stable.

ah, no stress. I was just wondering since it had that milestone.
