### ISSUE TITLE
Service Buttons: Wrong color when active

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#25448]
Here is a perfect beginner friendly issue :)

**What happened**:
The service buttons has the wrong text color
![Screenshot from 2020-06-08 14-34-13](https://user-images.githubusercontent.com/1438972/84030955-2b4e6280-a995-11ea-9c50-27356bb7b153.png)

**What you expected to happen**:
The same thing as when you hover over the button.
![Screenshot from 2020-06-08 14-35-22](https://user-images.githubusercontent.com/1438972/84031058-520c9900-a995-11ea-9468-6d212fff2fbf.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable some alternative auth methods in [the config](https://grafana.com/docs/grafana/latest/installation/configuration/#auth)
2. Go to `/login`
3. Select one of the input fields and tab until one of the service buttons are active

**Solution:**
Take inspiration from #25009

**Comment by zixlin7** [comment]
Hi! May I work on this if it's alright?

**Comment by tskarhed** [comment]
> Hi! May I work on this if it's alright?

Yes, please! Eagerly awaiting a PR! Just tell me if you need any help!

**Comment by zixlin7** [comment]
@tskarhed I enabled the buttons and I see the same behavior for active and hover. Please let me know if I'm missing something.
<img width="455" alt="Screen Shot 2020-06-16 at 8 29 07 PM" src="https://user-images.githubusercontent.com/60411978/84851832-29794480-b010-11ea-929e-ba371e26f583.png">

**Comment by tskarhed** [comment]
@zixlin7 You're right, it seems to have been fixed. I can't find any `active` styles related to the service buttons. Could have been some active styles that were accidentally applied to these before.

Thanks for the help and initiative anyways. :1st_place_medal: I'd be glad to help you with any other issue, just ping me!
