### ISSUE TITLE
Templating: set an variable based on another variable

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2544]
For example I have series

host.test1
host2.test1
host2.test2

I would like to make a dashboard where all metrics like host2.* to display on a graph. I make a templating variable named $host to discover all host and user can select host to see all metrics from the host. It is good.

But what if the user do not know the host. He only knows `test1`. Of course I can make `host.*` as an variable $hostAndMetric, but that way I can not graph all metrics of a host on one graph now. Because $hostAndMetric will be equal to, say, host2.test2, I do not want the `test2` part.

I think of one solution that If I can choose one variable, and another variable will be auto set using regex or something (like what grafana does now towards what data source returns), I can use the processed variable in my graph.

**Comment by torkelo** [comment]
Like this suggestion, https://github.com/grafana/grafana/issues/2343
