### ISSUE TITLE
Dashboard provisioning using environment variables is not working

### ISSUE THREAD

**Issue by mieseprem** [grafana/grafana#25443]
**What happened**:

I tried to get rid of the envsubst commands in my dockerfile as this approach led to environment issues in the provided dashboards.

A slight digression about my dashboards workflow:
* initially create dashboard within grafana
* save json source of new dashboard into provisioning folder
* replace environment specific parts (e.g. parts of URLs) with environment variables
* build grafana image using envsubst command
* change provisioned dashboard within grafana (all environment variables are obviously are replaced with their values)
* save json source of changed dashboard into provisioning folder
* again replace environment specific parts (e.g. parts of URLs) with environment variables
  * and here is the problem -> if I miss to replace any of the needed replacements...

I read severeal things:
1. [using-environment-variables](https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables)
  -> "It is possible to use environment variable interpolation in all 3 provisioning config types. [...]"
2. [#23097](https://github.com/grafana/grafana/issues/23097#issue-588236691)
  -> It seems this is the same issue but regarding datasources. Unfortunately dashboards are exported as JSON and I can't find the 'apiVersion' field in it nor I found a documentation saying at which position it has to be placed.
3. [#12896](https://github.com/grafana/grafana/issues/12896#issue-349999484) and [#16499](https://github.com/grafana/grafana/pull/16499#issue-269326251)
  ->this seems to address exactly my problem and it was merged over a year ago.

**What you expected to happen**:
In my provisioned dashboards all environment variables ${MY_VARIABLE} should be replaced by its value.

**How to reproduce it (as minimally and precisely as possible)**:
In Grafana create a simple dashboard and place it into the provisioning folder. Replace something in file with a environment variable (please see simple example attached - [000_test.json.txt](https://github.com/grafana/grafana/files/4745158/000_test.json.txt)). Start Grafana.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: FROM grafana/grafana:7.0.3
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: grafana-image-renderer,grafana-piechart-panel,jdbranham-diagram-panel,snuids-trafficlights-panel
- Others:

**Comment by mieseprem** [comment]
I edited the original post: In attachment 000_test.json.txt a system environment variable with name TALEND_ENV is used. You'll find it at line 71.

**Comment by mieseprem** [comment]
Wow, as I read my own post myself I think I provided some uncorrect information...

I place this yaml file into /etc/grafana/provisioning/dashboards/
`apiVersion: 1

providers:
- name: 'default'
  orgId: 1
  folder: 'DAVID'
  type: file
  disableDeletion: false
  updateIntervalSeconds: 600
  options:
    path: /opt/grafana/dashboards/`
In the original post "provisioning folder" is /opt/grafana/dashboards/

**Comment by xlson** [comment]
The support for environment variable substitution is only available in the provisioning config files, not in the dashboards themselves. We mention this in the docs, but perhaps not clear enough, see the last part of https://grafana.com/docs/grafana/latest/administration/provisioning/#using-environment-variables

I'll close this issue but if you are interested in this feature I urge you to create a feature request.
