### ISSUE TITLE
Explorer view, 7.0.3, after receiving a 504, the query_range api call being fired after I press the refresh button, the UI does not reflect that it's waiting for a new query result.

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#25442]
Explorer view, 7.0.3, after receiving a 504, the UI does not reflect that it's waiting for a new query result when pressing and looks like the refresh is ignored. This is not the case, because there is a query_range API query being triggered from the frontend.

It probably makes sense to clear the error state when firing off a new query in the explore view, after an error.

**Comment by aocenas** [comment]
Sorry for keeping this here for so long but seems like this should be fixed right now. Cannot replicate it and seems like we changed the code so that we properly reset the state on query run. If you still see this in newer version please let me know.
