### ISSUE TITLE
Grouping Field disregards Query

### ISSUE THREAD

**Issue by mac3000** [grafana/grafana#25451]
Hi,
**What happened**:
After upgrading to Grafana 7.0, we have noticed that while using query and grouping on a certain field, the query results will include all the available values on the index with zero values. While we expect to see only the metric we defined on the query.
These "phantom" values are causing problems to our monitoring, since on the 1 hand a "0" (zero) Count on a value is an issue, but on the other these values are not real since they are filtered out in Query.

**What you expected to happen**:
If I Query specific values of Field, this is the only value we should see.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a Graph on a field that can have several values.
2. Enter query to see only 1 of these values.
2. Add Group By (Count) on that field.
3. See all values of that field, and not only the one in Query (only that value has Count)

![Grafana Query Group](https://user-images.githubusercontent.com/17688782/84033506-9d2ca900-a9a1-11ea-9202-6b3267e68392.jpg)

- Grafana version: Grafana v7.0.0 (aee1438ff2)

Let me know if you need more info...

Thanks,
Jacob

**Comment by torkelo** [comment]
Unable to replicate here: https://play.grafana.org/d/000000014/elasticsearch-metrics?editPanel=1&orgId=1 

So looks like a problem with your query. or how elasticsearch queries work. Try changing min doc count to 1 (in the terms aggregation)

![Screenshot from 2020-06-08 16-31-54](https://user-images.githubusercontent.com/10999/84042637-9bfd7b00-a9a5-11ea-9727-faa785d33423.png)

**Comment by mac3000** [comment]
For some reason the Graph you sent is not working now.
However, if you are able to run it and change  the Metric in your graph from  "Max" to "Count", and then use in the query to get 1 specific @hostname value, you should see what I described...

Adding the "min doc count to 1" does seem to resolve this, but still want to know if what I described is correct behavior or a bug...
