### ISSUE TITLE
Support old panelId urls for view & edit panel

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#25459]
We need to add redirects for old links that use panelId , to redirect viewPanel & editPanel 

In 7.0 we changed the view panel & edit panel urls from 

From
 https://play.grafana.org/d/000000012/grafana-play-home?panelId=2&orgId=1&edit&fullscreen

To
 https://play.grafana.org/d/000000012/grafana-play-home?editPanel=2&orgId=1 

For view panel (only difference is missing edit url param)

From
 https://play.grafana.org/d/000000012/grafana-play-home?panelId=2&orgId=1&fullscreen

To
 https://play.grafana.org/d/000000012/grafana-play-home?viewPanel=2&orgId=1

**Comment by dprokop** [comment]
@torkelo can you explain a little bit more? Just in case someone want's to pick this up.

**Comment by torkelo** [comment]
Added more info
