### ISSUE TITLE
Multi selection variables are not working Azure Log Analytics queries

### ISSUE THREAD

**Issue by networkandcode** [grafana/grafana#25468]
**What happened**:
I have added a variable that captures list of deployments in a Kubernetes namespace, observed the following when I try to  use this variable in my query:
- works  with Azure Log Anayltics query, when the variable allows only single selection
- works when the variable allows single selection, or multi selection, or All with Prometheues query

**What you expected to happen**:
- should work with Azure Log Anayltics query, when the variable is enabled for single selection, or multi selection, or All 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.0
- Data source type: Azure Monitor
- Others: Helm chart based installation

**Comment by daniellee** [comment]
@networkandcode can you show a screenshot of your template variable settings and can you also show how you are using the template variable query.

There are some macros that could help depending on what you are doing in your query: https://grafana.com/docs/grafana/latest/features/datasources/azuremonitor/#azure-log-analytics-macros

**Comment by networkandcode** [comment]
@daniellee 
Here is a sample query, with one multi selection variable '$service':
```
let cluster = '$cluster';
let namespace = '$namespace';
let service = '$service'; \\ this is a multi selection variable
let pod = '$service.*';
let metric = 'cpuUsageNanoCores';
Perf     
| where TimeGenerated >= ago(10m) 
| where InstanceName has cluster
| where ObjectName == "K8SContainer" 
| where CounterName == metric
| extend value = CounterValue/pow(2,30)
| extend splitInstance = split(InstanceName, '/')
| extend ContainerName = strcat(splitInstance[-2], '/', splitInstance[-1])
| join kind=inner (
    KubePodInventory
    | where TimeGenerated >= ago(10m) 
    | where ClusterId has cluster
    | where ServiceName == service
    | where Namespace == namespace
    | where Name matches regex pod
) on ContainerName
| summarize arg_max(TimeGenerated, *) by ContainerName
| summarize sum(value) by Name
| sort by Name asc
| project now(), sum_value, Name
```

It shows '400 Bad request' in the panel

variable settings snapshot below:
![image](https://user-images.githubusercontent.com/30622440/84237856-b5becf80-ab17-11ea-9d8b-21f2956f681d.png)

The same query works and displays info on the panel, when I disable Multi selection / All for the variable

**Comment by maxilampert** [comment]
@networkandcode For multi-values to work you need to use the contains macro in your graph queries `$__contains(service, $service)` which will expand the selected variables to `service in ('value1', 'value2')` in the Kusto query language. Also you need to write 'all' in the 'Custom all-value' setting.

As daniellee mentioned its described in the link he posted
![image](https://user-images.githubusercontent.com/1974396/84565853-9371bf80-ad6c-11ea-9ccc-645cd4c5f726.png)

**Comment by networkandcode** [comment]
thank you @daniellee and @maxilampert 

Is there a way we can out regex in the $__contains macro, say like $__contain(pod, $service.*)
