### ISSUE TITLE
Option to add search field on graph or table panel

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#25462]
**What would you like to be added**:
Option to add search field on graph or table panel based on alias field.
Graph would show only selected metric. Table would show only selected metric and hide other rows.

**Why is this needed**:
It would be useful to have search field in graph or table panel that has many metrics, based on alias field in query.

We are using OpenTSDB 2.2.1 with filters applied that returns many metrics with alias from specific tag:
![image](https://user-images.githubusercontent.com/66313770/84063952-22c05100-a9c2-11ea-8e31-60e992c0b2a1.png)

Graph example with many metrics:
![image](https://user-images.githubusercontent.com/66313770/84064733-6cf60200-a9c3-11ea-9fc4-0968d51d8fb5.png)

Table example with many metrics:
![image](https://user-images.githubusercontent.com/66313770/84063144-d3c5ec00-a9c0-11ea-877d-27f1184e7098.png)

**Comment by AgnesToulet** [comment]
Hello,

It seems that what you want to achieve is possible using templates and variables (you'll find the documentation here: https://grafana.com/docs/grafana/latest/variables/templates-and-variables/). If you configure a variable to get all your metrics names, you'll then be able to select multiple values in the variable and show according metrics.

If you already tried this, could you add in your issue why it doesn't meet your needs please?

**Comment by edin008** [comment]
Thank you for suggestion. I solved my issue.
