### ISSUE TITLE
Group by time with offset (influxdb) hangs graph panel and errors out

### ISSUE THREAD

**Issue by malcolmwhat** [grafana/grafana#25465]
**What happened**:
With a graph panel, and the display bars set to true, using InfluxDB, the following

Works correctly:
```influxql
[QUERY] GROUP BY time(12h)
```
Fails:
```influxql
[Query] GROUP BY time(12h, 2h)
```

Correctly looks like this:
![image](https://user-images.githubusercontent.com/6776991/84068924-b6c8f300-a997-11ea-90e0-f31226b7a263.png)

Failed looks like this:
![image](https://user-images.githubusercontent.com/6776991/84068894-a9ac0400-a997-11ea-8eb9-2dda7c2f7671.png)

**What you expected to happen**:
Graph shows correctly with offset time.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel, select `Graph`
1.2. (might be optional) select show bars = true
2. Select an influxDB connector
3. Write a basic query with a group by time, should work fine
4. Add a second argument to the group by time, which offsets the result.
5. 💣 

**Anything else we need to know?**:
It seems like the data comes back fine, it just takes like 5 minutes, the graph doesn't render and there are a bunch of 
![image](https://user-images.githubusercontent.com/6776991/84070519-45d70a80-a99a-11ea-8556-4ceb58289dc8.png)

**Environment**:
- Grafana version: v7.0.2
- Data source type & version: Influxdb
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you include the influxdb query response when you get this error?

**Comment by malcolmwhat** [comment]
I can send it through support, but unfortunately I won't put it here on the public issue. Looks like the actual issue was not the group by time...

I hadn't inspected the payload itself, just the response code in the network pane. The payload we were getting back was ~5MB, oops. The real issue was a nested query:
```
SELECT [...]
FROM (SUBQUERY where $timeFilter)
GROUP BY time(12h, 1h)
```
Added:
```
SELECT [...]
FROM (SUBQUERY where $timeFilter)
WHERE $timeFilter GROUP BY time(12h, 1h)
```
the payload is more sanely sized and the graph renders correctly with the offsets.

My bad for not being more diligent.
