### ISSUE TITLE
Make default home dashboard configurable in grafana.ini

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#25463]
It should be possible to switch the [path to the default home dashboard](https://github.com/grafana/grafana/blob/master/pkg/api/dashboard.go#L335) in `grafana.ini`.

This will make it possible to change the first impression using config files.

**Comment by iangkent** [comment]
+1

**Comment by GTB3NW** [comment]
I believe the home dashboard is also per organization? In which case could that also be taken into consideration please :)

**Comment by bergquist** [comment]
This issue is only about making the path to the default dashboard configurable.

Ref
https://github.com/grafana/grafana/issues/10266
https://github.com/grafana/grafana/issues/24588
