### ISSUE TITLE
grafana 2.2 - InfluxDB 0.9.2 "show series" for template variables only displays first result...

### ISSUE THREAD

**Issue by kvesterling** [grafana/grafana#2546]
<img width="592" alt="screen shot 2015-08-18 at 9 49 02 am" src="https://cloud.githubusercontent.com/assets/13852287/9331627/79632354-458e-11e5-9910-7bc64df290d3.png">
<img width="770" alt="screen shot 2015-08-18 at 9 49 38 am" src="https://cloud.githubusercontent.com/assets/13852287/9331628/7964cf60-458e-11e5-8faa-57dded624e73.png">

**Comment by torkelo** [comment]
These types of queries should work
SHOW MEASUREMENTS
SHOW TAG KEYS FROM 
SHOW TAG VALUES FROM "cpu" WITH KEY = "hostname"

Is there a reason you want to use show series instead of the above?
