### ISSUE TITLE
Zabbix Problems Visualization - parameters change doesn't get saved

### ISSUE THREAD

**Issue by Students** [grafana/grafana#25476]
**What happened**:

Zabbix Problems panel configuration changes in specific cases are not getting saved.

**What you expected to happen**:

It should be possible to save the panel configuration changes.

**How to reproduce it (as minimally and precisely as possible)**:

Having a Grafana dashboard with Zabbix Problems visualization panel with the following configurations:
Options: Show hosts in maintenance, Sort problems = default, Acknowledged = 2, Limit problems = 200

If you change this parameters to the following ones:
Options: Sort problems = default, Limit problems = 200
* basically selecting just the unacknowledged problems and selecting not to show hosts in maintenance
Afterwards save the dashboard (with or without a comment).
Then check, that after dashbord is saved - new config is in place.
Then refresh the page (hit F5). And check - the configuration is back to the original one, the new one did NOT get saved.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v6.7.4
- Data source type & version: Zabbix. Plugin version 3.12.2
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome 
- Grafana plugins: Zabbix. Plugin version 3.12.2
- Others: 
Issue is NOT reproducible on Grafana v7.0.3

**Comment by xlson** [comment]
@alexanderzobnin can you take a look?

**Comment by alexanderzobnin** [comment]
Ok, trying to reproduce.

**Comment by alexanderzobnin** [comment]
This is a plugin-related issue, so please reopen it in grafana-zabbix repo.

**Comment by Students** [comment]
Thanks for the note.
https://github.com/alexanderzobnin/grafana-zabbix/issues/988 is for it.
