### ISSUE TITLE
Creating new Threshold should autofocus the threshold input

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#25479]
Currently, when a new threshold is created the focus stays with the _Add threshold_ button when user clicks it (see video below). 

To improve the usability of the thresholds editor it would be great if creating a new threshold would automatically focus the new threshold's input so that you can type in the value straight away.

![Kapture 2020-10-19 at 08 43 51](https://user-images.githubusercontent.com/2376619/96410547-63896b80-11e7-11eb-8315-9205e5b64030.gif)

**Comment by rakeshraih** [comment]
Can i take this up?

**Comment by torkelo** [comment]
Yes!

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/ThresholdsEditorNew/ThresholdsEditor.tsx#L50

**Comment by rakeshraih** [comment]
> https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/ThresholdsEditorNew/ThresholdsEditor.tsx#L50

Pls correct me if am wrong, I don't see the above method `onAddThreshold`  being called. ThresholdFormCtrl is being used to add the threshold. Using the master branch with the latest code. Hope am looking at the correct location. (Attached the front end screenshot)
<img width="580" alt="Screen Shot 2020-10-03 at 9 14 32 PM" src="https://user-images.githubusercontent.com/6831851/95006861-c0690d00-05bd-11eb-9017-7b3d0d35c66d.png">
