### ISSUE TITLE
Provisioning datasources leaves incorrect version number in database

### ISSUE THREAD

**Issue by kali-brandwatch** [grafana/grafana#25473]
I have already asked this as a question in the community site but it didn't seem to catch any attention, so after confirming he issue stays in 7.0.2 i'm opening this bug issue.

**What happened**:
When using automagic provisioning of datasources to control data source config updates, I get a wrong version number declared in the database configuration. My issue was discovered using puppet for management of the `provisioned.yaml` file but it would do the same however this file is managed.
Regardless of what the `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` file specifies for `version` field, the resulting mysql stored configuration will have `version: 1` as a value.

**What you expected to happen**:
I would expect the provisioned data source to be set in the database respecting the version number set in the `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` file, same as it respects every other provided value in the yaml file.

**How to reproduce it (as minimally and precisely as possible)**:
0- Have a datasource already defined, regardless how (e.g.: Influxdb `_internal` database). In my case, deployed via puppet on `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` file.
1- Modify data source, via grafana UI, to change the database field to something like `_internalfoo.` Database then gets the datasource defined with `version: 2`
2- deploy a new `puppetprovisioned.yam`l file with the field database declared as `_internalbar` and `version: 3` to ensure the value gets updated over what was changed on step 1. Grafana's mysql database then gets updated with the new `database` value, but `version` is then restored to `1` rather than `3`

**Anything else we need to know?**:
In our case we are managing the `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` using grafana's own puppet module. In the scenario above, this means several annoyances and risks:
* If someone changes again a value through the UI, the version in the database will change to `2`. Puppet doesn't change the `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` file therefore there is no restart of grafana service and therefore the `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` values don't go on the database, keeping the latest UI change. But if *for any reason* grafana service restarts, it will catch the `/etc/grafana/provisioning/datasources/puppetprovisioned.yaml` file content, compare `version: 3` as greater than the current db stored value of `version: 2` and re-apply the puppet deployed configuration. This will happen randomly time after the change is done in the UI, leaving whoever made that change with questions regarding why their changes got lost.
* In our case we initially deployed the data source configs via puppet. Then someone changed the data source config through the UI increasing the version number. When we decided to change some setting and do so through puppet, we needed to go on to the database to double check the current `version` number of the datasource (not available through the UI) and set our puppet code to use a value greater than that.

**Environment**:
- Grafana version: 7.0.2
- Data source type & version: Influxdb
- OS Grafana is installed on: Debian 10
- User OS & Browser: any
- Grafana plugins: none
- Others:

**Comment by marefr** [comment]
@kali-brandwatch I think you might have a misconception of provisioned data sources automatically being refreshed when .yaml files are updated? They're not, you have to either restart Grafana or either [manually reload them](https://grafana.com/docs/grafana/latest/http_api/admin/#reload-provisioning-configurations) for the changes to be picked up. 

I would suggest removing usage of the version field in the provisioning configuration if you still want to allow users to update the data source from the UI. If you don't want to allow users updating it from the UI please set `editable: false`.

**Comment by marefr** [comment]
If I misunderstood something please let me know and we'll consider reopen this.
