### ISSUE TITLE
Make time picker consistent with time correction setting

### ISSUE THREAD

**Issue by swissdave** [grafana/grafana#2547]
Hi there.. just updated to the latest version - very nice, thanks!

I've had a request from a couple of users - when you set the time correction to UTC mode, the charts show the correct times in UTC.  As far as I can see, the time picker remains in local browser time though - this makes things a little confusing.

Could we possibly switch the time picker to either local/UTC based on the dashboard setting and show this in the title bar somewhere?

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/1050

**Comment by swissdave** [comment]
Sorry, searched but this didn't turn up.
