### ISSUE TITLE
Data not aligned with Bars when grouped by Day (worked OK with 6.5.2)

### ISSUE THREAD

**Issue by sumocomputers** [grafana/grafana#25488]
**What happened**:
A single bar, which should represent 1 Day, is representing data from 2 different days when you hover over (see screenshots). Seen on 7.0.3.

**What you expected to happen**:
A single bar for 1 Day should represent data from 1 Day when you hover over (see screenshots). Seen on 6.5.2.

**How to reproduce it (as minimally and precisely as possible)**:
Go from Grafana 6.5.2 to 7.0.3

**Anything else we need to know?**:
I have attached screenshots of the before and after as well as some of my panel config. If I am missing something, please let me know.

Total newbie, so please go easy. I am using InfluxDB with Grafana as part of a package with my home automation software (Indigo), so I don't have direct access to Influx, but do with Grafana.

I am grouping by 24h and using tz = America/Los_Angeles in the panel, as well as America/Los_Angeles in Dashboard settings and Relative Time Range as last 30 days.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: InfluxDB (1.7.10?)
- OS Grafana is installed on: macOS 10.15.5
- User OS & Browser: macOS 10.15.5 & Safari 13.1.1, Brave v1.9.76
- Grafana plugins: Discrete v0.0.9, Pie Chart v1.3.9, World Map 0.2.1 + Core
- Others:

![Screen Shot 2020-06-09 at 9 13 04 AM](https://user-images.githubusercontent.com/656453/84175751-4375be80-aa35-11ea-8677-1dafe56ec92d.jpeg)

![Screen Shot 2020-06-09 at 9 13 56 AM](https://user-images.githubusercontent.com/656453/84175776-4bcdf980-aa35-11ea-87ac-a4bb380dc79b.jpeg)

![Screen Shot 2020-06-09 at 9 24 15 AM](https://user-images.githubusercontent.com/656453/84175792-5092ad80-aa35-11ea-96aa-e736efe480bd.jpeg)

![Screen Shot 2020-06-09 at 9 24 20 AM](https://user-images.githubusercontent.com/656453/84175803-54becb00-aa35-11ea-9a93-131563f52cee.jpeg)

![Screen Shot 2020-06-09 at 9 26 03 AM](https://user-images.githubusercontent.com/656453/84175850-686a3180-aa35-11ea-8777-f75e2c3e0549.jpeg)

![Screen Shot 2020-06-09 at 9 30 40 AM](https://user-images.githubusercontent.com/656453/84175860-6c964f00-aa35-11ea-8040-f3b960bfdd69.jpeg)

![Screen Shot 2020-06-09 at 9 30 58 AM](https://user-images.githubusercontent.com/656453/84175873-7029d600-aa35-11ea-9cab-6a6d8b2fb09f.jpeg)

![Screen Shot 2020-06-09 at 9 31 13 AM](https://user-images.githubusercontent.com/656453/84175886-73bd5d00-aa35-11ea-9f98-9aea93f49f7a.jpeg)

**Comment by torkelo** [comment]
We changed so that the bars are centered on the data point, instead of being right-aligned

**Comment by sumocomputers** [comment]
@torkelo - Might there be any workaround, so each bar represents a 24h day?

**Comment by torkelo** [comment]
not sure what you mean, it still does that, that is up the query. Just now the bars are centered on the data point.

If the data points are not aligned to midnight, might be a problem in influxdb ?

**Comment by sumocomputers** [comment]
I have been struggling with this, and since the version of InfluxDB has not changed between Grafana versions, I have still not been able to resolve this issue. However, I did find something else peculiar in trying to find a solution.

If I change one of charts to last 15 days just to see better, and then add a Time Region for Sat to Sun (blue in screenshots), you will notice that it actually covers July 10, 11, and 12 (a Friday, Saturday, and Sunday). Shouldn't only cover Sat & Sun? Seems like a Grafana issue to me, unless I am understanding incorrectly.

![Grafana-01](https://user-images.githubusercontent.com/656453/87880578-9aad6e00-c9a7-11ea-9c89-3042bac383d5.jpeg)
![Grafana-02](https://user-images.githubusercontent.com/656453/87880579-9c773180-c9a7-11ea-9581-6fffd9ec7a07.jpeg)
