### ISSUE TITLE
When adding links with more than 1 tag it doesn't work

### ISSUE THREAD

**Issue by malosaa** [grafana/grafana#25489]
**What happened**: When using links with tags they dont work, if i put 1 tag in it it works but when entering another one and refresh it disappears, aswell with drop down menu.

**What you expected to happen**: just to show up like normal.

**How to reproduce it (as minimally and precisely as possible)**: just go to settings and links and add dashboard by tags.

**Anything else we need to know?**: no

**Environment**: 
- Grafana version: 7.0.3
- Data source type & version: -
- OS Grafana is installed on: windows 10
- User OS & Browser: chrome,edge
- Grafana plugins: influx
- Others: nope

**Comment by torkelo** [comment]
works fine here: https://play.grafana.org/d/Lu_Xd1mMk/new-dashboard-copyasad?orgId=1 

The tags filtering is inclusive, so all tags must match
