### ISSUE TITLE
Dashboard variable for Stackdriver's Label Values not returning results

### ISSUE THREAD

**Issue by oholdswo** [grafana/grafana#25487]
**What happened:**
After upgrading from 6.6.1 to 7.0.0 (now on 7.0.3) I noticed the dashboard used for monitoring CloudSQL databases wasn't working. After looking into it a bit further I saw the issue was with the dashboard variable used to get the database id. I tried deleting the variable and making it again but noticed there were no values in the preview values section and after saving it and opening it again I saw the query had changed so that "Service", "Metric Type" and "Label Key" were all set to the first value in the dropdown, rather than to "cloudsql", "CPU utilization" and "resource.label.database_id" respectively.

I also noticed that it's not just the cloudsql option, setting the "Service" to any of the options in the list return no data in the previews section. 

I tested the same query in the Explore section of Grafana where it worked fine and was able to return metrics from the databases using Stackdriver. 

Finally, other query types for the Stackdriver data source are working fine in dashboard variables, only the "Label Values" option is affected. 

Query before save:
![query_before](https://user-images.githubusercontent.com/62296375/84173480-40022780-aa75-11ea-8250-562adf0ba324.png)

Query after save and re-opening the variable page:
![query_after](https://user-images.githubusercontent.com/62296375/84173509-47293580-aa75-11ea-8e98-e46603aa87bd.png)

**What you expect to happen:**
The selected query returns values from Stackdriver and persists after saving the variable.

**How to reproduce it (as minimally and precisely as possible):**
- Create a custom service in GCP project with Stackdriver enabled: https://cloud.google.com/monitoring/api/ref_v3/rest/v3/services/create	
- Create Stackdriver datasource, create a new dashboard. Go to settings>variables. Try to create a new variable:
name: anything
type: query
data source: stackdriver
query type: label values
project: your project
service: anything
metric type: anything
label key: anything
- Save
- Re-open the variable edit screen and the options from Service and below will be reset to the first option in the list.

**Anything else we need to know?:**
- This dashboard was working on Grafana 6.6.1, so it's a new bug since then. I haven't tested any versions between 6.6.1 and 7.0.0 though.
- This issue is very similar to #24660 
- I turned on debug logging but couldn't see anything that jumped out as an error in the log output. Happy to provide logs if needed.

**Environment:**
- Grafana version: 7.0.3
- Data source type: Stackdriver
- OS Grafana is installed on: Docker on Alpine
- User OS & Browser: Ubuntu 20.04, Chrome 83.0.4103.61 (Official Build) (64-bit)
- Grafana plugins: only things provided by docker image
Others:
- Running in GKE on node version 1.15.9-gke.24 (master version 1.16.8-gke.15)

**Comment by arteal** [comment]
Happens to me also. Also no error in (container) log

**Comment by Eraac** [comment]
Same here, just want to add information:

The project dropdown seems to be blocked on the default project. If we change the project and update then go back to the variable the project isn't save
