### ISSUE TITLE
Can't change the dashboard's time selection range

### ISSUE THREAD

**Issue by ningyougang** [grafana/grafana#25499]
**What happened**:

   Can't change  a dashboard's time selection range.

**What you expected to happen**:

  Can change a dashboard's time  selection range successfully.

**How to reproduce it (as minimally and precisely as possible)**:
  1. Create a dashboard with time range: `last 24 hours`
  2. Change it to `last 12 hours` in page, and click `save`
  3. refresh this dashboard without time range
  4. i found that, the time range is `last 24 hours` (normally, it should be` last 12 hours`)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: elasticsearch & 6.7.2
- OS Grafana is installed on: Centos7
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by AgnesToulet** [comment]
Hello,
Did you check the "Save current timerange as dashboard default" before saving? It doesn't appear in your step to reproduce the issue and it's required if you want to save the new selected time range.
![image](https://user-images.githubusercontent.com/35176601/84239575-f9f0a680-aafc-11ea-9acc-1fe16e05bab4.png)

**Comment by ningyougang** [comment]
@AgnesToulet , thanks you, i find it.
Close as done.
