### ISSUE TITLE
Proxy-authn/LDAP-authz combo

### ISSUE THREAD

**Issue by dannygoulder** [grafana/grafana#2549]
Hi, thanks for a great 2.1 release. Great news on the LDAP auth support and InfluxDB 0.9.

I think this may count as a feature request, but it would be really great if it would be possible to combine proxy authentication (to allow Kerberos SSO through Apache) with LDAP authorisation (to allow LDAP group to role mapping). If we could map the proxied username to a specified LDAP attribute (and use the bind user to do the group lookup) this would be awesome.

**Comment by seuf** [comment]
I think it's the same issue than #5764
It would  be great it the pr can be merged.

**Comment by torkelo** [comment]
was impylemented morle than a year ago, in https://github.com/grafana/grafana/pull/6895

**Comment by dannygoulder** [comment]
Awesome!  Thanks for the follow-up!
