### ISSUE TITLE
Cloudwatch SORT metrics math function is not respected for more than 10 results

### ISSUE THREAD

**Issue by jkim-** [grafana/grafana#25494]
**What happened**:
When using [`SORT(SEARCH(...), SUM, DESC)`](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/using-metric-math.html#metric-math-syntax) to sort the results of a SEARCH query with 10+ results, the time series are sorted based on their labels rather than the order returned by Cloudwatch.

Because the rank of the result is affixed to the label, this results in the ordering of the rank 1, 10, 11, 12, 2, 3, 4, 5, 6, 7, 8, 9 (assuming the result contains 12 time series). I suspect [this](https://github.com/grafana/grafana/blob/5f923be2bf67deadab90dcd328e84bee8a9b41cf/pkg/tsdb/cloudwatch/response_parser.go#L69) is the line that causes this.

**What you expected to happen**:

I expected Grafana to respect the order returned by Cloudwatch (1, 2, 3, ...), which helps in visualizing multiple time series when stacked.

**How to reproduce it (as minimally and precisely as possible)**:

SEARCH and SORT for metrics that return more than 10 time series and inspect the response array in Grafana.

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: 7.0.3

**Comment by bergquist** [comment]
This sort was added in https://github.com/grafana/grafana/commit/59469e14cfeba57e31019b81a5dc15151ce1bd0c

@marefr Looking at the code I think this should work even without the sort. Any strong arguments for keeping it? I think we should default to return data in the order returned from the database.

**Comment by aknuds1** [comment]
I'm going to put some work into this issue and try solve it.

**Comment by aknuds1** [comment]
I've made a PR to try to fix this https://github.com/grafana/grafana/pull/26835.
