### ISSUE TITLE
Alerts are not sent with image_url in VictorOps notification channel

### ISSUE THREAD

**Issue by amit-o** [grafana/grafana#25506]
**What happened**:
While sending alerts, using a remote grafana-image-renderer, alerts are not sent with the image_url 

Grafana logs - 
t=2020-06-10T11:12:40+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://grafana-image-renderer:80/render?deviceScaleFactor=1.000000&domain=redacted&encoding=&height=500&renderKey=TPibYbnufiNXT9WisdLBT0g6HnZeGKS2&timeout=15&timezone=&url=https%3A%2F%2Fredacted%2Fd-solo%2FQTOkNoiMk%2Fuptime-checks%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000"  
t=2020-06-10T11:12:43+0000 lvl=info msg=Requesting logger=data-proxy-log url=https://content-monitoring.googleapis.com/v3/projects/redacted/timeSeries  
t=2020-06-10T11:12:44+0000 lvl=info msg="Executing victorops notification" logger=alerting.notifier.victorops ruleId=20 notification="Engineering Critical"

image renderer logs - 
{"url":"https://redacted/d-solo/QTOkNoiMk/uptime-checks?orgId=1&panelId=2&render=1","level":"debug","message":"Render request received"}
{"message":"10.32.24.1 - - [10/Jun/2020:11:12:42 +0000] \"GET / HTTP/1.1\" 200 22 \"-\" \"kube-probe/1.15+\"\n","level":"debug"}
{"file":"/tmp/9e5cc365.png","level":"debug","message":"Deleting temporary file"}
{"message":"10.32.24.144 - - [10/Jun/2020:11:12:44 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=redacted&encoding=&height=500&renderKey=TPibYbnufiNXT9WisdLBT0g6HnZeGKS2&timeout=15&timezone=&url=https%3A%2F%2Fredacted%2Fd-solo%2FQTOkNoiMk%2Fuptime-checks%3ForgId%3D1%26panelId%3D2%26render%3D1&width=1000 HTTP/1.1\" 200 18561 \"-\" \"Grafana/7.0.3\"\n","level":"debug"}
{"url":"https://redacted/d-solo/QTOkNoiMk/uptime-checks?orgId=1&panelId=2&render=1","level":"debug","message":"Connection closed"}

**What you expected to happen**:
Alerts should be sent out with image_url as specified in the [integration guide](https://help.victorops.com/knowledge-base/grafana-integration-guide/)

**How to reproduce it (as minimally and precisely as possible)**:
Create VictorOps notification channel with include image checked. Send alert, confirm image_url is missing from the data in VictorOps

**Anything else we need to know?**:
Grafana and the renderer are running on Kubernetes.
I can confirm the actual rendering works (Through sharing & slack channel), albeit a bit slow.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Stackdriver
- OS Grafana is installed on: Docker (official images)
- User OS & Browser: Mac/Chrome
- Grafana plugins:  N/A
- Others: N/A

**Comment by sakjur** [comment]
@marefr Is it possible this was introduced by #23194 ?

**Comment by marefr** [comment]
@sakjur possibly yes. But don't understand why

**Comment by darealkrb** [comment]
I'm facing similar issue. I have configured grafana container & Image rendered container in AWS Fargate with EFS as persistent storage. I'm trying get alerts on victorops with image and used this integration steps https://help.victorops.com/knowledge-base/grafana-integration-guide/  . I was able to get the test image but when actual alert is triggered I'm not getting the image.
