### ISSUE TITLE
Functioning client-side dashboard and graph export

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#2550]
It would be great to be able to share a fully functioning dashboard or graph into a folder, complete with all code and data. Sometimes, you want to be able to share a particular view of things in a way that has no future dependencies on network or systems. The data source could simply be routed to local files that are part of the export. It's ok if this means that server-side aggregates are not renderable. However, it would be necessary to encode the aggregates in a way that the pre-rendered data that is saved during export could be mapped and loaded. Even if this disallows resizing the view/interval, it would still be useful.

This would be using a dashboard or graph as a durable artifact of some effort, which is exactly what I'm interested in.

**Comment by torkelo** [comment]
you have the snapshot feature http://docs.grafana.org/reference/sharing/#publish-snapshots

It comes close to your requirement, all the visible data is captured and embedded in the dashboard, so you can view the dashboard and the graph in all their glory months and years later without the data sources being available. 

But doing this feature in a offline mode is a little tricker and seems like an edge case that very few would use.
