### ISSUE TITLE
Grafana 7.0.2 is not loading on Samsung TV or Edge browser

### ISSUE THREAD

**Issue by Nekasas** [grafana/grafana#25507]
**What happened**:
can't login to page from Edge browser or Samsung TV. With version 6.* everything was working as expected. We tried to clean cookies, check from private mode, check from different computers and so on

**What you expected to happen**:
Login to page

**How to reproduce it (as minimally and precisely as possible)**:
Login to page from Edge browser or Samsung TV

**Anything else we need to know?**:
From logs I can see this line:
t=2020-06-10T14:27:29+0300 lvl=info msg="Successful Login" logger=http.server User=monitor

**Environment**:
- Grafana version: Grafana v7.0.2
- OS Grafana is installed on: CentOS Linux release 7.8.2003 (Core)
- User OS & Browser:  User: Windows 10 Enterprise (10.0, Build 17134), Browser: Microsoft Edge 42.17134.1098.0

![grafana](https://user-images.githubusercontent.com/53274311/84264017-27534980-ab29-11ea-9f28-91aa49758500.gif)

**Comment by torkelo** [comment]
Rolling discussion from https://github.com/grafana/grafana/issues/25518 into this one 

I think this is related to cookie somehow, would explain why the browser does not stay logged in

try
```
[security] 
cookie_samesite = disabled
```

restart grafana server, and try to login again. 

Or 

```
[security] 
cookie_samesite = none
``´

restart grafana server, try to login again

**Comment by Nekasas** [comment]
tried to use both solutions, but unfortunately it didn't solve my issue for both browsers

**Comment by seblu** [comment]
To follow up #25518, both `disabled` and `none` doesn't solve the login issue on my Samsung TV.

**Comment by seblu** [comment]
I tested with Microsoft Edge 44.18362.449.0 on Windows 10 (1903, build 18362) and login works correctly.

**Comment by Nekasas** [comment]
> I tested with Microsoft Edge 44.18362.449.0 on Windows 10 (1903, build 18362) and login works correctly.

yes, Edge with 44 version works correcty, but with 42 version not

**Comment by tskarhed** [comment]
Here is the component the error points at. Not sure why it would be related to the login issue yet.
https://github.com/grafana/grafana/blob/2d4bcbeff617bb921348536c652fecc410960875/public/app/features/admin/UserProfile.tsx#L24

**Comment by tskarhed** [comment]
As mentioned here: https://github.com/grafana/grafana/issues/26007#issuecomment-652975012

Might be related to these functions

https://github.com/grafana/grafana/blob/2d4bcbeff617bb921348536c652fecc410960875/public/app/core/components/Login/LoginCtrl.tsx#L97

https://github.com/grafana/grafana/blob/2d4bcbeff617bb921348536c652fecc410960875/public/app/core/components/Login/LoginCtrl.tsx#L126


Just to be sure; there isn't any redirectUrl in the url?

**Comment by nadgobpx01** [comment]
Hi , I am having the same issue any workaround  on this?

**Comment by AgnesToulet** [comment]
Hello, is anyone here can say if Grafana 6.7.x is working on Microsoft Edge 42.xx or recent TV browsers?

On my Samsung TV, Grafana 6.6.2 is working but I have a similar issue from 6.7.0.

**Comment by Nekasas** [comment]
> Hello, is anyone here can say if Grafana 6.7.x is working on Microsoft Edge 42.xx or recent TV browsers?
> 
> On my Samsung TV, I have a similar issue from 6.7.0 but I'm not 100% sure if it's the same.

before upgrade we had Grafana 6.7.x and Microsoft Edge 42 or Samsung TV didn't have any issue

**Comment by nadgobpx01** [comment]
> Rolling discussion from #25518 into this one
> 
> I think this is related to cookie somehow, would explain why the browser does not stay logged in
> 
> try
> 
> ```
> [security] 
> cookie_samesite = disabled
> ```
> 
> restart grafana server, and try to login again.
> 
> Or
> 
> ```
> [security] 
> cookie_samesite = none
> ``´
> 
> restart grafana server, try to login again 
> ```

also tried  with no result

**Comment by nadgobpx01** [comment]
....is something related to authentication . I have enabled anonymous authentication and now i am able to view the dashboards on Samsung TV.

**Comment by AgnesToulet** [comment]
Do you have any non-default settings regarding authentication? Can you post these settings here (replacing any sensitive data)?

**Comment by paulohmorais** [comment]
@nadgobpx01 that solved for me. Thanks

**Comment by Nekasas** [comment]
> @nadgobpx01 that solved for me. Thanks

what did you do? Please share your configuration

**Comment by nadgobpx01** [comment]
> > @nadgobpx01 that solved for me. Thanks
> 
> what did you do? Please share your configuration

I have enabled anonymous acces .Changed the following to grafana.ini config file :


```
[auth.anonymous]
# enable anonymous access
enabled = true

org_name = "_change with your organization name_"

# specify role for unauthenticated users
org_role = Viewer
```

**Comment by paulohmorais** [comment]
> > > @nadgobpx01 that solved for me. Thanks
> > 
> > 
> > what did you do? Please share your configuration
> 
> I have enabled anonymous acces .Changed the following to grafana.ini config file :
> 
> ```
> [auth.anonymous]
> # enable anonymous access
> enabled = true
> 
> org_name = "_change with your organization name_"
> 
> # specify role for unauthenticated users
> org_role = Viewer
> ```

I needed to set same value of org_name in Grafana Web too, to work.
Settings -> Preferences
![image](https://user-images.githubusercontent.com/31579998/87792199-ecc08900-c819-11ea-88bb-30eb7ef14101.png)

**Comment by Nekasas** [comment]
> > > > @nadgobpx01 that solved for me. Thanks
> > > 
> > > 
> > > what did you do? Please share your configuration
> > 
> > 
> > I have enabled anonymous acces .Changed the following to grafana.ini config file :
> > ```
> > [auth.anonymous]
> > # enable anonymous access
> > enabled = true
> > 
> > org_name = "_change with your organization name_"
> > 
> > # specify role for unauthenticated users
> > org_role = Viewer
> > ```
> 
> I needed to set same value of org_name in Grafana Web too, to work.
> Configuration -> Preferences
> ![image](https://user-images.githubusercontent.com/31579998/87792199-ecc08900-c819-11ea-88bb-30eb7ef14101.png)
> 
> After this i open URL of Grafana in TV.
> And i can open my Dashboard without make a login.

As a workaround it works like a charm

**Comment by gilvi** [comment]
More troubles regarding to this after update from 5x to 7.1.2 (and now on 7.1.3)

Your browser is not fully supported
A newer browser version is recommended

Firefox ESR 52.9.0(64bits) logs in but returns again to login page 
LG Smart TV  model 47LB652V-Z: software 05.05.70  webOS 1.4.0-2532(afro-ashley) can log in, but the stats are empty 
Samsung TV model UE70KU6000 software T-JZL6DEUC-1242.0  can log in, but the stats are empty
Samsung TV model UE60J6240 software 1550 can log in, but the stats are empty

In newer Smart TVs we own works propperly, but these older models don`t and, sadly, if there is not a fix, we'll have to downgrade to a compatible version beacuse the only use of these TVs is to show grafana dashboards.

**Comment by gilvi** [comment]
I've trying old versions, the last working for me is 6.6.2, it advises of webbrowser incompatibility but still works. In 6.7.0 something broke the compatibility.

Hope it helps.

**Comment by Nekasas** [comment]
> > > > @nadgobpx01 that solved for me. Thanks
> > > 
> > > 
> > > what did you do? Please share your configuration
> > 
> > 
> > I have enabled anonymous acces .Changed the following to grafana.ini config file :
> > ```
> > [auth.anonymous]
> > # enable anonymous access
> > enabled = true
> > 
> > org_name = "_change with your organization name_"
> > 
> > # specify role for unauthenticated users
> > org_role = Viewer
> > ```
> 
> I needed to set same value of org_name in Grafana Web too, to work.
> Configuration -> Preferences
> ![image](https://user-images.githubusercontent.com/31579998/87792199-ecc08900-c819-11ea-88bb-30eb7ef14101.png)
> 
> After this i open URL of Grafana in TV.
> And i can open my Dashboard without make a login.

Do you know is it possible to publish more than one org_name?

**Comment by nadgobpx01** [comment]
> > > > > @nadgobpx01 that solved for me. Thanks
> > > > 
> > > > 
> > > > what did you do? Please share your configuration
> > > 
> > > 
> > > I have enabled anonymous acces .Changed the following to grafana.ini config file :
> > > ```
> > > [auth.anonymous]
> > > # enable anonymous access
> > > enabled = true
> > > 
> > > org_name = "_change with your organization name_"
> > > 
> > > # specify role for unauthenticated users
> > > org_role = Viewer
> > > ```
> > 
> > 
> > I needed to set same value of org_name in Grafana Web too, to work.
> > Configuration -> Preferences
> > ![image](https://user-images.githubusercontent.com/31579998/87792199-ecc08900-c819-11ea-88bb-30eb7ef14101.png)
> > After this i open URL of Grafana in TV.
> > And i can open my Dashboard without make a login.
> 
> Do you know is it possible to publish more than one org_name?

At the moment i am using more than one organisation .

**Comment by Tomicapo** [comment]
I'm also having problems from an LG TV. I'm using grafana.net and I simply can't load the login page. I get an error right after entering the URL. I've checked enough times to see if I typed it correctly. Even tried http and https and more.
Also, if I try to login to grafana.com I get this error: "Invalid method (HTT verb)" (plain text on a white screen).

**Comment by Nekasas** [comment]
> > > > > > @nadgobpx01 that solved for me. Thanks
> > > > > 
> > > > > 
> > > > > what did you do? Please share your configuration
> > > > 
> > > > 
> > > > I have enabled anonymous acces .Changed the following to grafana.ini config file :
> > > > ```
> > > > [auth.anonymous]
> > > > # enable anonymous access
> > > > enabled = true
> > > > 
> > > > org_name = "_change with your organization name_"
> > > > 
> > > > # specify role for unauthenticated users
> > > > org_role = Viewer
> > > > ```
> > > 
> > > 
> > > I needed to set same value of org_name in Grafana Web too, to work.
> > > Configuration -> Preferences
> > > ![image](https://user-images.githubusercontent.com/31579998/87792199-ecc08900-c819-11ea-88bb-30eb7ef14101.png)
> > > After this i open URL of Grafana in TV.
> > > And i can open my Dashboard without make a login.
> > 
> > 
> > Do you know is it possible to publish more than one org_name?
> 
> At the moment i am using more than one organisation .

how you are using anonymous authentication with 2 organizations?

**Comment by Nekasas** [comment]
with latest version (v7.1.3 (5723d951af)) and anonymous authentication I even can't login from Google Chrome or Firefox

**Comment by nadgobpx01** [comment]
> > > > > > > @nadgobpx01 that solved for me. Thanks
> > > > > > 
> > > > > > 
> > > > > > what did you do? Please share your configuration
> > > > > 
> > > > > 
> > > > > I have enabled anonymous acces .Changed the following to grafana.ini config file :
> > > > > ```
> > > > > [auth.anonymous]
> > > > > # enable anonymous access
> > > > > enabled = true
> > > > > 
> > > > > org_name = "_change with your organization name_"
> > > > > 
> > > > > # specify role for unauthenticated users
> > > > > org_role = Viewer
> > > > > ```
> > > > 
> > > > 
> > > > I needed to set same value of org_name in Grafana Web too, to work.
> > > > Configuration -> Preferences
> > > > ![image](https://user-images.githubusercontent.com/31579998/87792199-ecc08900-c819-11ea-88bb-30eb7ef14101.png)
> > > > After this i open URL of Grafana in TV.
> > > > And i can open my Dashboard without make a login.
> > > 
> > > 
> > > Do you know is it possible to publish more than one org_name?
> > 
> > 
> > At the moment i am using more than one organisation .
> 
> how you are using anonymous authentication with 2 organizations?
I haven't tried for anonymous on more than one. I am guessing that  this parameter  should be duplicated with different org name 
[auth.anonymous]
# enable anonymous access
enabled = true

org_name = "_change with your organization name_"

# specify role for unauthenticated users
org_role = Viewer"

**Comment by nadgobpx01** [comment]
After updating Grafana to 7.1.3  , graphics are not visible anymore . Is there any workaround for this new challenge ?:) .

**Comment by peterholmberg** [comment]
Closing this issue since it seems to have deviated from the original issue. If you still have an issue with logins and/or other functionality please open a new issue using the bug template so we can gather which browser versions this is happening on.

**Comment by seblu** [comment]
@peterholmberg issue #25518 was rolled into this one. You are closing an unresolved issue affecting LG TV, were some people are disabling logging to workaround it.

**Comment by maxout123** [comment]
> 
> 
> Closing this issue since it seems to have deviated from the original issue. If you still have an issue with logins and/or other functionality please open a new issue using the bug template so we can gather which browser versions this is happening on.

Are you kidding? People are waiting for solution. The details are perfectly described in the initial post.
Samsung TVs are now unusable with Grafana, and many organizations was using them explicitly for Grafana.

**Comment by Nekasas** [comment]
this is one of the major bug in Grafana 7.x. Atleast keep this issue in backlog, it can't be closed!

**Comment by Baboy71** [comment]
> Closing this issue since it seems to have deviated from the original issue. If you still have an issue with logins and/or other functionality please open a new issue using the bug template so we can gather which browser versions this is happening on.

Crazy!  This major issue is clearly described and the only deviation is people suggesting a workaround (that bypasses the login security) because it still hasn't been resolved.  Currently we can't use Grafana on our Samsung TVs in our NOC and so unfortunately are starting to evaluate alternatives as disappointingly there seems to be no solution in sight for what otherwise is a great dashboard tool.

**Comment by peterholmberg** [comment]
Sorry, my mistake!

**Comment by Baboy71** [comment]
Thanks.  If it helps our Samsung TVs has Tizen Browser 2.1.3.0821293 and the TV is reporting it is up to date.

**Comment by yangliuyu** [comment]
I fixed part of the problem #27007

**Comment by safadig** [comment]
I do not believe this issue is addressed. Cannot get Grafana > 6.7 to load on Samsung TV... Went back to 6.7 from an old backup.. Staying there till this issue fixed

**Comment by jhfin** [comment]
So I have Samsung QB13R-T display. It is not loading the home page but only telling it is probably not supported browser.

I asked about this from Samsung support: My 1,5 years old Q13R-T has "Tizen 4,  SSSP6 and Chromium version M56 as web engine" (https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html). No way up updating the browser.

Is there any way of getting version 8 Grafana to work with Chromium M56?

**Comment by safadig** [comment]
> So I have Samsung QB13R-T display. It is not loading the home page but only telling it is probably not supported browser.
> 
> I asked about this from Samsung support: My 1,5 years old Q13R-T has "Tizen 4, SSSP6 and Chromium version M56 as web engine" (More details on the browser capabilities can be found here https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html). No way of updating the browser.
> 
> Is there any way of getting version 8 Grafana to work with Chromium M56 and available features of the browser of my screen?

I have given up. I am in the process of going to Raspberry - Pi via HDMI Display to all those displays used for Grafana. Another option would Magicinfo but at least from my trials, nothing other than Premium ( neither Lite or S) works even! what a shame!

**Comment by boringthegod** [comment]
> > So I have Samsung QB13R-T display. It is not loading the home page but only telling it is probably not supported browser.
> > I asked about this from Samsung support: My 1,5 years old Q13R-T has "Tizen 4, SSSP6 and Chromium version M56 as web engine" (More details on the browser capabilities can be found here https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html). No way of updating the browser.
> > Is there any way of getting version 8 Grafana to work with Chromium M56 and available features of the browser of my screen?
> 
> I have given up. I am in the process of going to Raspberry - Pi via HDMI Display to all those displays used for Grafana. Another option would Magicinfo but at least from my trials, nothing other than Premium ( neither Lite or S) works even! what a shame!

Personally I have a raspberry Pi, and I can't with chromium, go on my grafana in v8.2.5 (same problem as you). I have another grafana in v7.3.5 and on this one it works

**Comment by safadig** [comment]
> > > So I have Samsung QB13R-T display. It is not loading the home page but only telling it is probably not supported browser.
> > > I asked about this from Samsung support: My 1,5 years old Q13R-T has "Tizen 4, SSSP6 and Chromium version M56 as web engine" (More details on the browser capabilities can be found here https://developer.samsung.com/smarttv/develop/specifications/web-engine-specifications.html). No way of updating the browser.
> > > Is there any way of getting version 8 Grafana to work with Chromium M56 and available features of the browser of my screen?
> > 
> > 
> > I have given up. I am in the process of going to Raspberry - Pi via HDMI Display to all those displays used for Grafana. Another option would Magicinfo but at least from my trials, nothing other than Premium ( neither Lite or S) works even! what a shame!
> 
> Personally I have a raspberry Pi, and I can't with chromium, go on my grafana in v8.2.5 (same problem as you). I have another grafana in v7.3.5 and on this one it works

It was not easy but this is how it worked for me on raspbian lite 32:
`sudo apt update && sudo apt upgrade && sudo apt install xserver-xorg-core xserver-xorg-video-fbdev xserver-xorg-input-evdev xinit xfonts-base lxde tightvncserver --no-install-recommends -y`
Then MUST INSATTL CHROMIUM
`sudo apt install chromium`
console should show should show that it is now the preferred (xxx-browser....etc), otherwise update from raspi-config
`sudo nano /etc/xdg/openbox/autostart`
add the following:
`# If you want to use XFCE config tools...
#
#xfce-mcs-manager &
xset -dpms            # turn off display power management system
xset s noblank        # turn off screen blanking
xset s off            # turn off screen saver

# Remove exit errors from the config files that could trigger a warning

sed -i 's/"exited_cleanly":false/"exited_cleanly":true/' ~/.config/chromium/'Local State'

sed -i 's/"exited_cleanly":false/"exited_cleanly":true/; s/"exit_type":"[^"]\+"/"exit_type":"Normal"/' ~/.config/chromium/Default/Preferences

# Run Chromium in kiosk mode
#chromium  --noerrdialogs --disable-infobars --kiosk $KIOSK_URL #Another way to run but no scaling)
sh -c 'xrandr --display :0.0 --output HDMI-1 --mode 1920x1080 --scale 0.6x0.6 --rotate normal --rate 60.00'
/usr/bin/grafana-kiosk -URL http://yoururl:3000/d/678fHDA7z/yourdashboard  -kiosk-mode full -autofit
--check-for-update-interval=31536000`

**Comment by marcelmfs** [comment]
I'm trying to upgrade from 5.4 to latest 8, and I got here because I'm facing the same issue (login form loop after green success toast), but it's not for a TV, it's for latest browsers (tried with Chrome/Canary/Safari/Firefox). Is there a different upgrade path I should be looking into? Should I upgrade from 5.4 to 6 then to 7 to finally get up to latest 8.X?
