### ISSUE TITLE
Default Password Does not work

### ISSUE THREAD

**Issue by Setheck** [grafana/grafana#25519]
**What happened**:
Using the latest grafana container 
The documentation for the image -> https://hub.docker.com/r/grafana/grafana 
states `Try it out, default admin user is admin/admin.`
But these credentials do not work.

**What you expected to happen**:
I expected to login to the grafana ui with the default creds of `admin/admin`

**How to reproduce it (as minimally and precisely as possible)**:
Simply run the docker container as the example 
`docker run -d --name=grafana -p 3000:3000 grafana/grafana`
and try to login with admin/admin

**Anything else we need to know?**:
Not sure if this is an issue with grafana, or just a documentation issue. But there should be clear direction that either the login works, or more steps to login are required.

**Environment**:
Docker `grafana/grafana:latest` -> `DIGEST:sha256:f22e7f865da0052a0e62987c4fe37a2479b2e4770583aeaaa679345b5e813dc7`

**Comment by torkelo** [comment]
Just tested this and admin/admin works for me. and we would have gotten hundreds of similar reports if this was the case 

What browser are you using? no do not happen to have an old docker volume (and hence grafana db) that has a changed admin password?

**Comment by Setheck** [comment]
I think you pretty much nailed it. I believe this was caused by a previous run i did where the admin pw was set via env var. Seems like i re-used a container name, so instead of creating a new one, it just launched the old one.
Apologies, this was my mistake

**Comment by torkelo** [comment]
No problem, glad you fixed it
