### ISSUE TITLE
Multi-value variable filter doesn't fit in the text box, if too many values or values are too long

### ISSUE THREAD

**Issue by silentZaika** [grafana/grafana#25514]
![Screenshot 2020-06-10 at 17 45 09](https://user-images.githubusercontent.com/24699684/84282648-ad2fbe80-ab42-11ea-9b51-b5b65b4cf2eb.png)

**What happened**:
Having multi-value variable with many values or very long string makes the filter overflow the text box
**What you expected to happen**:
The filter is either trimmed to fit the text box, or the text box expanded to fit the
whole string
**How to reproduce it (as minimally and precisely as possible)**:
- Add a multi-value variable with a lot of values, or very long values
- Select all of them

**Environment**:
- Grafana version: 7.0.2
- OS Grafana is installed on: docker (ubuntu)
- User OS & Browser: Chrome, Safari

**Comment by torkelo** [comment]
Think some tweaks to no-wrap and overflow ellipsis to this component and class could fix this:

 https://github.com/grafana/grafana/blob/master/public/app/features/variables/pickers/shared/VariableLink.tsx
