### ISSUE TITLE
Elasticsearch: AND operator has to be upper case, otherwise its a OR

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#25510]
**What happened**:
The following log lines are in elasticsearch:
| # | Customer | Rating |
|---|----------|--------|
| 1 | cust1    | WARN   |
| 2 | cust1    | ERR    |
| 3 | cust2    | WARN    |

▶ `Customer : "cust1" and Rating : "WARN"`

Result via grafana:
| # | Customer | Rating |
|---|----------|--------|
| 1 | cust1    | WARN   |
| 2 | cust1    | ERR    |
| 3 | cust2    | WARN    |

`and` is working like a or operator.

**What you expected to happen**:

| # | Customer | Rating |
|---|----------|--------|
| 1 | cust1    | WARN   |

The query should return the first row only, because of the **and** statement. In Kibana a lowercase **and** works fine. Took me a hour to find the mistake... i thought the syntax in Grafana is the same as in Kibana - it is **not**.

**Anything else we need to know?**:

The `and` must be in caps to be interpreted correct (= **AND**, `Customer : "cust1" AND Rating : "WARN"`).

**Environment**:
- Grafana version: 7.0.3 (00ee734baf)
- Data source type & version: 7.7.1

**Comment by torkelo** [comment]
Grafana does not modify the query, so you need to follow the syntax defined here: https://www.elastic.co/guide/en/elasticsearch/reference/7.7/query-dsl-query-string-query.html#query-string-syntax

**Comment by FireEmerald** [comment]
Interesting, because Kibana allows lower case operators and the results are correct. In Grafana they don't work. Seems like Kibana is doing some magic behind.
