### ISSUE TITLE
Grafana 7.0.3 is not loading on LG TV

### ISSUE THREAD

**Issue by paulohmorais** [grafana/grafana#25518]
What happened:
can't login to page from Browser of LG Smart TV. We tried to clean cookies, check from private mode.

What you expected to happen:
Login to page

How to reproduce it (as minimally and precisely as possible):
Login to page from LG TV

Anything else we need to know?:
The problem happen after i upgrade my container to 7.0.3.
But after made a rollback to 6.7.4, still not working.

I decide to run a brand new container in another server with grafana 6.7.4  and dont working anymore. 
I think this is important, the browser engine of webos LG TVs:
http://webostv.developer.lge.com/discover/specifications/web-engine/

The error in image
![IMG_20200610_113513 (2)](https://user-images.githubusercontent.com/31579998/84295526-1272b800-ab21-11ea-992c-52beaea18bef.jpg)

Environment:

Grafana version: Grafana v7.0.3
OS Grafana is installed on: Ubuntu Server 18.04 - With Docker 19.03
User OS & Browser: User: LG SmartTV Webos 05.10.45, Browser: From TV

**Comment by torkelo** [comment]
strange, webOS TV 5.x says Chromium 68 which should be fine, that error should only be for IE11 and really chrome browsers (before version 54)

**Comment by torkelo** [comment]
Can you double OS version & user agent? when was the TV purchased?

**Comment by paulohmorais** [comment]
@torkelo I made a mistake.
The OS Version of TV are: 4.1.4 instead of 05.10.45

I need to change my level for logs in grafana.ini to: debug
So i can see the full http request and here the log request of TV:

t=2020-06-12T14:04:38+0000 lvl=dbug msg="user auth token created" logger=auth tokenId=54 userId=1 clientIP=XXXX userAgent="Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.31 SmartTV/6.0" authToken=156354095b706a6bdfb10cd20cc9588a541e19d73e27e16673625cbdfded0ec9

How you say version 53 of chrome is above of 54. :cry: 

There a way i can desative this check Browser Compatibility?

**Comment by seblu** [comment]
Same issue. TV is [LG 43UK6300](https://www.lg.com/fr/televiseurs/lg-43UK6300-led-uhd-4k-tv) and was bought in july 2019. 
The TV software version is `05.10.45` and **there is no newer version available**.

#### Nginx log
```
a0:b1:c2:d3:fffe:e4:f5 - - [18/Jun/2020:17:05:16 +0200] "GET / HTTP/2.0" 302 29 "https://graph.x.y/login" "Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.31 SmartTV/6.0"
```

**Comment by torkelo** [comment]
Are you seeing any other issues other than the browser version alert? @paulohmorais  reporting problem login, @seblu you the same?

**Comment by maxout123** [comment]
The TV software version is 05.10.50 - the same issue.
After entering login/password - screen refreshes and we got login screen with the same alert again.

**Comment by paulohmorais** [comment]
@maxout123 @seblu The TV Software Version are different of the OS version of TV.
My TV are on TV Software 05.10.45.
But, the webOS version are 4.1.4-5727.

See images:
![Webp net-resizeimage (9)](https://user-images.githubusercontent.com/31579998/86010070-4d199300-b9f1-11ea-9597-9de21b670caf.png)
![Webp net-resizeimage (10)](https://user-images.githubusercontent.com/31579998/86010077-4ee35680-b9f1-11ea-9204-57a512f5ea0b.png)


And here http://webostv.developer.lge.com/discover/specifications/web-engine/
you see that webOS TV 4.x have a Chromium 53.

**Comment by maxout123** [comment]
> 
> 
> Are you seeing any other issues other than the browser version alert? @paulohmorais reporting problem login, @seblu you the same?

I have the same login problem too. Login screen just refreshes on form submit and alert appears again.

**Comment by torkelo** [comment]
Try setting this cookie setting

```
[security] 
cookie_samesite = disabled
```

or to 

```
[security] 
cookie_samesite = none
```

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L184

**Comment by maxout123** [comment]
> Try setting this cookie setting (in grafana.ini)

Unfortunately it doesn't help.

**Comment by seblu** [comment]
> Are you seeing any other issues other than the browser version alert? @paulohmorais reporting problem login, @seblu you the same?

Yes, I'm unable to login. I can't say if something else is broken, as I'm always redirected to login screen after successful attempt. 

> @maxout123 @seblu The TV Software Version are different of the OS version of TV.
> My TV are on TV Software 05.10.45.
> But, the webOS version are 4.1.4-5727.

Mine too. That's the last public version available on this. Is there a way to force the upgrade to webOS 5.x?

> Try setting this cookie setting (in grafana.ini)
> 
> ```
> [security] 
> cookie_samesite = disabled
> ```
> 
Same issue. Back to login screen.

I also tested the login issue from a desktop Firefox 77 and a Chromium 83 with a custom user agent string set to  `Mozilla/5.0 (Linux; NetCast; U) AppleWebKit/537.31 (KHTML, like Gecko) Chrome/53.0.2785.34 Safari/537.31 SmartTV/6.0` (same as TV) and login works correctly.

**Comment by torkelo** [comment]
Can you try setting cookie_samesite = none? 

I think there is something with the cookie in these old chrome browsers  that is causing this

**Comment by torkelo** [comment]
rolling this issue into https://github.com/grafana/grafana/issues/25507 as they are the same
