### ISSUE TITLE
Default group by $interval does not produce enough points

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2551]
I'm a little confused as to how the `group by time($interval)` is meant to work in Grafana. In my case, I have 1-second granularity iostat data over a 2-hour window that I've imported into InfluxDB.

Using Grafana's default dropdown, I create the following query:
```
SELECT mean(value) FROM "iowait" WHERE $timeFilter GROUP BY time($interval)
```
and then drag to zoom in, which creates a graph like this:

![screenshot 2015-08-19 15 00 19](https://cloud.githubusercontent.com/assets/243499/9349056/90863bde-4683-11e5-8505-f69343a85700.png)

In this case, the graph seems quite disjointed, as it only seems to have created 8 points over a 2-hour window - this is not a very good representation of the data.

However, if I manually edit the query to remove the `mean()` and `group by()`:
```
SELECT value FROM "iowait" WHERE $timeFilter
```
which gives:
![screenshot 2015-08-19 15 00 27](https://cloud.githubusercontent.com/assets/243499/9349080/c0149db4-4683-11e5-8647-d771d0b8bd5a.png)

As you can see, this graph is *very* different, but is actually the same data over the same period - this second one represents the data much better.

My question is - is this by design? Or is Grafana meant to adjust the group by interval?

**Comment by torkelo** [comment]
This is strange, when I test this myself Grafana calculates the $interval to 1s when the time range is "Last 2h". 

So Grafana will issue a query to InfluxDB with a group by(1s) which should in your case (and in mine) return the raw data, which it does for me, but for you it looks strange. Can you open chrome dev tools and inspect the raw request being sent to InfluxDB? (find it in the network tab), inspect the raw query being sent and the response (and please paste both here)

**Comment by victorhooi** [comment]
I deleted the InfluxDB database, re-created the database, and re-imported the data.

I then loaded up a Grafana dashboard as follows - time period was set to 2 days to a few seconds ago:

![screenshot 2015-08-20 11 12 47](https://cloud.githubusercontent.com/assets/243499/9373378/0c5a5dc2-472d-11e5-8aef-32515ff9d15c.png)

Here are the request headers - let me know if this isn't the right one:

```
GET /api/datasources/proxy/1/query?epoch=ms&q=SELECT+mean(value)+FROM+%22iowait%22+WHERE+time+%3E+now()+-+2d+GROUP+BY+time(1m) HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36
Referer: http://localhost:3000/dashboard/db/new-dashboard?panelId=1&fullscreen&edit
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: grafana_sess=96bfdda8569f5937; grafana_user=admin; grafana_remember=c9d3a71986148cbbff4400a61e3806191740d50cfbebe9dc
```

And here is the response - https://gist.github.com/victorhooi/8b51529c4c042ce03234 (it was too long to put in the issue itself).

I then used my mouse to drag over the period with data, and zoom in:

![screenshot 2015-08-20 11 18 21](https://cloud.githubusercontent.com/assets/243499/9373393/2f295826-472d-11e5-9a21-80499293d2af.png)

Looking at Chrome Dev Tools, this seemed to trigger a new request - this is the new request headers:

```
GET /api/datasources/proxy/1/query?epoch=ms&q=SELECT+mean(value)+FROM+%22iowait%22+WHERE+time+%3E+1439940421s+and+time+%3C+1439950672s+GROUP+BY+time(1s) HTTP/1.1
Host: localhost:3000
Connection: keep-alive
Accept: application/json, text/plain, */*
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2486.0 Safari/537.36
Referer: http://localhost:3000/dashboard/db/new-dashboard?panelId=1&fullscreen&edit
Accept-Encoding: gzip, deflate, sdch
Accept-Language: en-US,en;q=0.8
Cookie: grafana_sess=96bfdda8569f5937; grafana_user=admin; grafana_remember=c9d3a71986148cbbff4400a61e3806191740d50cfbebe9dc
```
And the response - https://gist.github.com/victorhooi/c94573c3e7d18a1bd91f

Let me know if you need anything else.

**Comment by torkelo** [comment]
I cant see any issue with Grafana here, the query being sent to influxdb is using `group by time(1s)`, InfluxDB is returning data points for each second interval, but if you look at the data returned by influxdb in your gist the values are mostly null

**Comment by victorhooi** [comment]
Actually, is it possible that I hit this issue?

https://github.com/grafana/grafana/issues/2565

As in, I dragged over the region in the graph that had points, InfluxDB sent through the new points, but Grafana simply zoomed into the existing points, but didn't add in the new finer-granularity points?

**Comment by torkelo** [comment]
That issue is only custom absolute date picker did not automatically refresh dashboard.
