### ISSUE TITLE
Importing panel into existing dashboard throws value errors when editing another panel

### ISSUE THREAD

**Issue by McAnix** [grafana/grafana#25525]
**What happened**:
I imported "stat" panel JSON from another dashboard into an existing dashboard, both created pre 7.0. When I add a new panel and try to edit then an exception is thrown. I can edit the imported panel JSON. I cannot edit some panels within the new dashboard. 

**What you expected to happen**:
No errors 

**How to reproduce it (as minimally and precisely as possible)**:
I'm not sure if this is replicatable but create a dashboard then import panel JSON for a "stat" panel. Attempting to edit another panel after this then throws an unexpected error.

**Anything else we need to know?**:

Stack trace:
```
react-dom.production.min.js:196 TypeError: Cannot read property 'values' of undefined
    at Object.showIf (types.ts:62)
    at PanelOptionsEditor.tsx:50
    at Array.map (<anonymous>)
    at PanelOptionsEditor.tsx:49
    at Array.map (<anonymous>)
    at lr (PanelOptionsEditor.tsx:47)
    at la (react-dom.production.min.js:154)
    at Su (react-dom.production.min.js:259)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
fu @ vendors~app.640775f84f40d9b3b2ee.js:2
```

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: MariaDB 10.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: MacOS 10.15.5 & Chrome 83.0.4103.97
- Grafana plugins: 

flant-statusmap-panel @ 0.2.0
grafana-image-renderer @ 2.0.0
grafana-piechart-panel @ 1.5.0
grafana-worldmap-panel @ 0.3.2
snuids-radar-panel @ 1.4.4

- Others:

**Comment by torkelo** [comment]
Can you include the json for the stat panel your importing?

**Comment by McAnix** [comment]
It looks like it's a conflict between the old version and new version. When I recreated from scratch (timeconsuming) it works 100%. 

{
  "datasource": "Slave",
  "description": "Total number of X right now",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "none",
      "min": 58000,
      "max": 61000,
      "displayName": "",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "red",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 59000
          },
          {
            "color": "green",
            "value": 59900
          },
          {
            "color": "#6ED0E0",
            "value": 61000
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 4,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 4,
  "options": {
    "reduceOptions": {
      "values": true,
      "calcs": [
        "mean"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "colorMode": "value",
    "graphMode": "area",
    "justifyMode": "auto"
  },
  "pluginVersion": "7.0.3",
  "targets": [
    {
      "format": "table",
      "group": [],
      "hide": false,
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "select count(id) as \"Count\" from X",
      "refId": "B",
      "select": [
        [
          {
            "params": [
              "id"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "account",
      "timeColumn": "last_billing_run",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "X Count",
  "transparent": true,
  "type": "stat"
}

**Comment by peterholmberg** [comment]
There's definitely something weird going on when importing panel json into a dashboard.

**Comment by torkelo** [comment]
How are you importing the JSON? You can just copy panels from another dashboard using the panel menu copy, and then in the other select paste panel in the add panel dialog.

Was not able replicate this specific problem. But we do have issues updating panel JSON from the inspect drawer

**Comment by dprokop** [comment]
@McAnix is this problem still happening to you? 

I've tried to reproduce this, but no success.

**Comment by McAnix** [comment]
It was related to importing a legacy table panel into a newer panel. I’m happy to close as I haven’t hit it again and nobody else is reporting it.

**Comment by dprokop** [comment]
@McAnix OK, let's close it now, and if that happens again feel free to re-open.
