### ISSUE TITLE
Folders: Editors should not be able to create folders with editors_can_admin is set to false 

### ISSUE THREAD

**Issue by elohmeier** [grafana/grafana#25532]
**What happened**:
Users with the "Editor" role are able to create dashboard folders but are unable to edit or delete them. I think this should be possible and is also an usability bug.

See the recording:
![Peek 2020-06-11 10-56](https://user-images.githubusercontent.com/2536303/84366270-e1eb5680-abd2-11ea-810f-b503fc5e17d1.gif)

**What you expected to happen**:
Editors can rename or delete folders. At least the folders they create on their own should be editable for them to correct e.g. typos in the folder name.

**How to reproduce it (as minimally and precisely as possible)**:
- Authenticate as user with "Editor" role.
- Create folder.
- Try to edit folder.

**Anything else we need to know?**:
I've been using LDAP authentication.

**Environment**:
- Grafana version: 7.0.0
- Data source type & version: no datasource
- OS Grafana is installed on: Offical Alpine Docker container
- User OS & Browser: Windows 7, Google Chrome 80.0.3987.100
- Grafana plugins: no extra plugins
- Others: -

**Comment by torkelo** [comment]
A temporary workaround you can set this to true:
https://grafana.com/docs/grafana/latest/installation/configuration/#editors-can-admin

**Comment by elohmeier** [comment]
I must have missed that in the docs, thank you @torkelo!

**Comment by torkelo** [comment]
To fix this we should make it not possible  to create folders as an Editor unless editors_can_admin is set to true
