### ISSUE TITLE
Tabs: The main navigation tabs should support being anchor hrefs and support clicking on active tab 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#25536]
1) The change to tabs component during 7.0 made them not handle/support link hrefs (so you cannot ctrl click to open tabs). 
2) The active tab can no longer be clicked (this is a big problem in a few pages where you need to be able to click the active tab to go back) 

the second point might sound strange but think GitHub, when view an issue the issues tab is active, but you can still click it to go back to issue list (same when you create new issue and want to go back to issue list, or have a PR open). 

Problem page in grafana, server admin > user page. No way to go back to user list now. 

![Screenshot from 2020-06-11 11-38-03](https://user-images.githubusercontent.com/10999/84370312-5d9bd200-abd8-11ea-9be3-a4d021bfc8e7.png)

**Comment by tskarhed** [comment]
Is there aan example where it is used/should be used as an anchor href? Is the thinking that you should be able to ctr+click to open in new tab?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/v6.1.6/public/app/core/components/PageHeader/PageHeader.tsx#L62
