### ISSUE TITLE
Grafana 7 Table CSV Export missing!

### ISSUE THREAD

**Issue by fl0wx** [grafana/grafana#25534]
What happened (still not solved and previous issue was closed and no reaction on comments):

    I cant find csv export when i click a panel and go to "more -> csv export??"
    when i pick inspect -> data and have a table with elastic data, then it doesnt export the table to csv but the data as objects.
    What you expected to happen:
    The presence of any csv export mechanism to export the table as it is like it was in Grafana 6*
    How to reproduce it (as minimally and precisely as possible):
    click on https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1 -> "ES logs Query" -> More
    Anything else we need to know?:

Environment:

    Grafana version: 7.0.1
    Data source type & version: elastic
    OS Grafana is installed on: debian 9
    User OS & Browser: chrome
    Grafana plugins: -
    Others: also doesnt work on play.grafana.com
    https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1 on the tables

@peterholmberg like i wrote in my issue: "when i pick inspect -> data and have a table with elastic data, then it doesnt export the table to csv but the data as objects". so export as csv under inspect isnt useful if you use transformations. proof images:
https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1 ES logs Query:
![grafik](https://user-images.githubusercontent.com/2448081/83789972-c85c8300-a697-11ea-8482-ddeabfc5ca6f.png)
And the downloaded csv looks even worse:
![grafik](https://user-images.githubusercontent.com/2448081/83790078-ec1fc900-a697-11ea-9675-37a0b49d4753.png)

So this isnt solved. Can you please reopen it @peterholmberg ?

_Originally posted by @fl0wx in https://github.com/grafana/grafana/issues/25334#issuecomment-638990695_

**Comment by torkelo** [comment]
this related to this Elasticsearch issue: https://github.com/grafana/grafana/issues/24163
