### ISSUE TITLE
Join data series by tag/label with some func

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#25543]
**What would you like to be added**:
It would be very convenient to be able to join data series by tag/label using the aggregation function (sum, mean, max, etc).

**Why is this needed**:
I will try to explain the problem using an example:
I have data from several applications in different measurements (for example, 
let it be counters of bad HTTP requests and some internal errors):
Table 1:
| application | error_counter | 
|-------------|-----------------|
| app1        | 0               |
| app2        | 10              | 

Table 2:
| application | error_counter | 
|-------------|-----------------|
| app1        | 15               |
| app2        | 0              | 

I would like to merge them into one table by tag `application`, sum up columns:
| application | error_counter_total | 
|-------------|-----------------|
| app1        | 15               |
| app2        | 10              | 

The presence of such functionality will allow very flexible data management if the data source itself is not flexible enough.
Maybe I was doing something wrong, I could not solve this problem using `outer join` transform.

**Comment by torkelo** [comment]
duplicate if https://github.com/grafana/grafana/issues/25594
