### ISSUE TITLE
Make dashboard editable again

### ISSUE THREAD

**Issue by michalbachowski** [grafana/grafana#2554]
Hi,

I have created dashboard and made it non-editable. Now I would like to remove it or edit it - and there is no such option despite having role "Grafana admin". The only option is to make it editable again manually. I would expect that "Grafana admin" and "Org. admin" roles as well as dashboard owners should have been able to make dashboard editable.

Best regards

Michał Bachowski

**Comment by torkelo** [comment]
You can make it editable again using the Save As... feature and enter the same name. 

I agree though, there should be an easier way to make it editable.

**Comment by michalbachowski** [comment]
Got it, thank you. And you are right - there should be an easier way of doing this.

**Comment by kokarn** [comment]
Maybe even add that to the "Editable" checkbox so people know how to get them editable again?

**Comment by itatabitovski** [comment]
It is also not possible to delete the dashboard

**Comment by addshore** [comment]
> You can make it editable again using the Save As... feature and enter the same name.

Well, that doesn't make it editable again, that just creates a copy of it...?

**Comment by addshore** [comment]
Okay, my solution (until this is fixed) is
 - Export / save the JSON
 - DELETE the dashboard using the API
 - import the JSON (recreating the dashboard)

**Comment by alxndr13** [comment]
@addshore When you save the Dashboard under the same name and you agree to overwrite the existing one, you have to reload the page or go to the overview of the dashboards. Then it's editable again.

**Comment by antoonh** [comment]
Running into this too. the "Save as..." under the same name works for me, but it's far from elegant.

**Comment by marcinkubica** [comment]
+1

**Comment by hecko** [comment]
+1

**Comment by krishnakummar** [comment]
+1

**Comment by ngleader** [comment]
+1

**Comment by bergquist** [comment]
This is done and available in nightly and soon grafana 3.0

**Comment by mattwilmott** [comment]
+1

**Comment by huoxy** [comment]
+1

**Comment by rwarren** [comment]
Where did this get implemented? I'm unable to figure out how to make a dashboard editable again!

I'm running Grafana v4.4.1 (commit: 6a9f8ca).

**Comment by torkelo** [comment]
Should be in the dashboard cogs menu
