### ISSUE TITLE
Offer of Help - Updating dashboard variables from panels

### ISSUE THREAD

**Issue by lstroud** [grafana/grafana#25550]
My company needs a way to update dashboard variables from panels. For us, this would allow the selection of a data value in one panel to effect what's displayed in another.  This would create an an additional interaction model for dynamic filtering within a dashboard.

We have some bandwidth and are willing to create a pull request for the feature.  However, we wanted gauge your willingness to accept that type of pull request before we invested too much time. Is this something that you would be interested in having added?

**Comment by StarScape** [comment]
+1
I work with @lstroud and can also work on this.

I did quite a bit of research and it seems setting a variable from inside a panel used to be possible, but now isn't -- is this something the Grafana team is opposed to adding or just hasn't yet? Being able to use variables for intra-panel interaction would be pretty sweet.

**Comment by StarScape** [comment]
Another thing, I tried setting a dashboard variable with `getLocationSrv`, like this:

```
import { getLocationSrv } from '@grafana/runtime';

getLocationSrv().update({
    partial: true,
    query: {
      'var-somevar': valueOfVar,
    },
    replace: true,
})
``` 

...but it doesn't work without doing a full page refresh. Is this fixed by #25192 or no?

**Comment by torkelo** [comment]
No it is not, 

Something here is not working as it should: https://github.com/grafana/grafana/blob/master/public/app/core/services/bridge_srv.ts#L81

**Comment by StarScape** [comment]
Hm, but the code I wrote above theoretically **should** work right? Assuming BridgeSrv were working correctly?

I and/or @lstroud could dig in to see what's going wrong there.

**Comment by torkelo** [comment]
yes

**Comment by rubaeros** [comment]
Hello, I follow the the code example from @StarScape and it works but Grafana start to make request until get an error:

`Unhandled promise rejection InternalError: "too much recursion"
    _invoke runtime.js:263
    t runtime.js:97
    Ht app.bb5d8fb9085bbb733af9.js:2
    i app.bb5d8fb9085bbb733af9.js:2
    Xt app.bb5d8fb9085bbb733af9.js:2
    H es.promise.js:233
    Xt app.bb5d8fb9085bbb733af9.js:2
    t actions.ts:20
    $/</</< Redux
    i store.ts:27
    e adapter.ts:29
    c runtime.js:45
host-report-errors.js:6:56`

Did you have this error also?

**Comment by rubaeros** [comment]
Just to give you more information I am using Text box variable, InfluxDB data source and Grafana 7.1.0-beta2

**Comment by rubaeros** [comment]
Ok, I can confirm it is happening with Text box variable not with Custom variable.

**Comment by StarScape** [comment]
@rubaeros I got a similar error, at least when using a version of Grafana I'd built from source. I spent maybe a day trying to find the bug in the Grafana code but did not fix it yet. I believe @lstroud is still going to try to figure it out when he has bandwidth.
