### ISSUE TITLE
Explore incorrect table result on Loki metric queries

### ISSUE THREAD

**Issue by slim-bean** [grafana/grafana#25553]
**What happened**:

Run a metric query in Explore against a Loki datasource `sum(rate({cluster="some-cluster"}[1m]))` and the table result contains many entries, also contains a strange date timestamp

**What you expected to happen**:

There should be a single result for this query as they `sum` should combine all the series into a single result.  When I look at the browser debug tools I can see the instant query result does indeed only have one series in it.

It looks as though the query_range result is being used in the table result seems like maybe a mismatch here in how the returned results from Loki are parsed/visualized.

**Comment by aocenas** [comment]
We were fixing this for prometheus lately and missed this for Loki
