### ISSUE TITLE
The UserPicker component has a hardcoded limit of 10.

### ISSUE THREAD

**Issue by mmwagner02** [grafana/grafana#25552]
I'm trying to add Users to a Team.  I followed all the instructions, but when I see the dropdown menu with the list of users, it only ever includes the same 10 users.  

I tracked this down to line 47 of UserPicker.tsx:
https://github.com/grafana/grafana/blob/1e88e508220159cddb846e5934af3fe3ae39bef9/public/app/core/components/Select/UserPicker.tsx#L47

Is there a reason not to list more than 10?  If so, can we be allowed to page through 10 at a time instead of being limited to the first 10?

**Comment by rvillablanca** [comment]
There is no pagination so the limit param is indeed needed, maybe increasing the value (50 perhaps) should be enough.

**Comment by hugohaggmark** [comment]
Closed by #29258
