### ISSUE TITLE
Tracing: Add tracing dashboard panel

### ISSUE THREAD

**Issue by Just-Sieb** [grafana/grafana#25568]
**What would you like to be added**:

I would like the ability to display Jaeger Traces with in a dashboard and not only from the explore view.

**Why is this needed**:

I am working on a Grafana dashboard where I can input a correlation id we use for our requests as a dashboard variable and it will output all availability telemetry we have for the request. Metrics and logs were fairly easy to do. Grafana 7's new ability to display Jaeger traces seemed like it would do the trick, however that seems to be limited to the explore view and can not be embedded on a dashboard.

**Comment by CarwynNelson** [comment]
This would be fantastic IMHO.

In work I am trying to make more use of Grafana and having a dashboard that contains metrics, logs, traces, and alarms all in one would be an incredibly powerful tool for us. Right now we have to switch between multiple tools and it's just painful.

**Comment by aocenas** [comment]
@Just-Sieb just to understand the usecase. You have a dashboard build around single correlation id? Does that mean that this dashboard works just when you input the ID and without it, it will show nothing?

**Comment by alirezamansoori** [comment]
@aocenas We have the same need. Once a tracing datasource (Tempo, Jaeger, etc, mix) can be used on a dashboard and a tracing panel exists, then it opens the door to using the 'repeat by variable' multiple correlation ids at once. To me this goes hand in hand with Grafana's unified data approach taken with metrics and logs.

**Comment by bennbollay** [comment]
In my specific usecase, I have a kiosk-mode log panel that I’m using to show specific logs based on parameterized variables in the dashboard.  These logs can be expanded.  When a user clicks on the “tempo” link, my ideal usecase would involve loading a panel that is just the trace view (screenshot 1 below), with some kind of “go backwards” button.  The current button drops the user in the full grafana tempo explore UI, which isn’t a particularly friendly user experience (screenshot 2).  All of the useful information is hidden “below the fold”, and there’s a lot of surrounding chrome that isn’t relevant nor useful for the discovery mode the user is in.

To work around this, I’m expecting to do some deep hackery to cause that button to trigger a sendMessage event to the parent browser window, where I’ll open up another tab to load that tempo explore context.  Very disruptive, takes the user out of the flow, lots of work on my end.

The broader scenario is that links between services are part of “targeted discovery”, which is distinct from exploration.  In this scenario, the user has already identified a discrepancy and is attempting to perform focused drilling on that element, possibly within the context of other informational elements presented on the same dashboard (running the mouse over the timeline for a trace could generate the same simultaneous timebars to show up on all of the other panels in the dashboard, for example, to see when a specific span occurred in relation to other events like a CPU spike).

From that perspective, clicking on a trace could perform a “panel flip” where the panel, like an informational card, “flips to it’s other side”, allowing the user to explore that focused collection of information within the same context.  It would need some kind of “back” gesture, of course, to flip the panel again, but there’s a lot of idioms available to that (including leaning on the left-vertical-bar modality and putting a full-panel-height < button on the left side, which could be stacked a few times if there’s a stack depth to the flips).

![image](https://user-images.githubusercontent.com/3607121/144662917-55c81f9c-ce8c-466c-9196-29f7d209ffe1.png)
![image](https://user-images.githubusercontent.com/3607121/144662949-ab008fab-3b33-46cf-a6f1-e045a5c6f878.png)

**Comment by locmai** [comment]
> @Just-Sieb just to understand the usecase. You have a dashboard build around single correlation id? Does that mean that this dashboard works just when you input the ID and without it, it will show nothing?

IHMO:

1. Some cases when we could extract single trace ID from the log like above.
2. When debugging a bottleneck, we usually want to take a look for a specific time range when the graph is at the peak. And if we could correlate with some tracing samples that we had at the current time range, that would be so helpful. Take an example with Kiali UI:
![trace-detail](https://user-images.githubusercontent.com/27542393/152184520-62451dd8-b2e3-4877-9afc-1497f47551b7.png)
3. We could also filter by the service name / some shared tags between metrics and tracing spans.
