### ISSUE TITLE
default grafana.sock path collides with systemd PrivateTemp option

### ISSUE THREAD

**Issue by unknowndev233** [grafana/grafana#25564]
What would you like to be added:

We need to change the socket path in default.ini from /tmp/grafana.sock to /run/grafana/grafana.sock.

Why is this needed:

When combined with systemd option PrivateTemp to isolate grafana from other files in /tmp, it's found that the default socket of grafana is also isolated.

Also this corresponds to the requirement of FHS:
https://refspecs.linuxfoundation.org/FHS_3.0/fhs/ch03s15.html

**Comment by sakjur** [comment]
The `/run` directory doesn't exist on MacOS, adhering to FHS would be break the socket transport for Darwin. Since the default value is overridable, you can configure it to `/run/grafana/grafana.sock` in the configuration file or using environment variables.
