### ISSUE TITLE
Multiple Field Key Select Statements for "Query Defined Variables" 

### ISSUE THREAD

**Issue by jakkarta0990** [grafana/grafana#25560]
Hi there!

I'm using Influxdb as my backend for one of my grafana dashboards.

I'm trying to define a variable [using a query.](https://grafana.com/docs/grafana/latest/variables/templates-and-variables/#variable-types) 

Now Influxdb supports the ability to query multiple field keys or tag keys with [a single select statement.](https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#description-of-syntax)

Now I have run such a query with my influx prompt and it runs successfully. However when running it in my grafana variable query statement it only returns the values of the first field key.

Thank you for any help in advance. 
![Capture](https://user-images.githubusercontent.com/29838924/84475128-4a4a3e80-ac8c-11ea-9965-d0e95f440fe1.PNG)

**Comment by sakjur** [comment]
It works as intended for now and you'll have to create separate variables for `username` and `client_mac` as we don't support selection of multiple options in a single variable query, but we're already doing it for some internal variables (`$__dashboard.id`), so it's not an unprecedented idea.

I'll mark this as a feature request 🙂

**Comment by jakkarta0990** [comment]
Thanks for the reply.

The thing is I would create seperate variables. Unfortunately InfluxQL doesn't support a select statement for a single tag key. At least 1 field key must always precede any tag key in a select statement.

**Source**: _https://docs.influxdata.com/influxdb/v1.2/query_language/data_exploration/#description-of-syntax_

Hence my predicament :D

**Comment by sakjur** [comment]
@jakkarta0990 Ah, I see! Yeah, it's a good feature request even _without_ that limitation, and with it is even more important.

**Comment by asergunovkl** [comment]
Found workaround in case only one column needed

`SELECT "Tag" FROM (SELECT last("Field") FROM ... WHERE ... GROUP BY "Tag")`

So first request returns "Field" and "Tag". Second one drops the "Field" we don't need
