### ISSUE TITLE
Row dynamic not filter at level of variable

### ISSUE THREAD

**Issue by ceinmart** [grafana/grafana#2556]
Hi, 
I'm start using Grafana 2.1.1 at OpenSuse 13.2.
I configure my Zabbix server and learning how Grafana works....

Not sure if this report is a defect or if designed this way or I don't know how use .... 

I was configured few templates variable where all appear works fine. 
This variables is a level, one inner other , the last one is : $grupo.$host.$app.* 
Then I configure a Graph to work with this variables... then all OK
When I configure row dynamic at $host level and put $host at "Row Title field"
This works when I select more than one host , but the level bellow (Items) repeat at each row... and this doent's make sense because at end I just have a duplicated graph... 

![screenshot 459](https://cloud.githubusercontent.com/assets/7062410/9360121/ca587458-466a-11e5-820e-4ecaec86b2f8.jpg)

**Comment by torkelo** [comment]
Zabbix datasource does not appear to support scoped variables (used by row repeat and panel repeat), can you reopen this issue in the plugins repo https://github.com/grafana/grafana-plugins/

ping @alexanderzobnin

**Comment by alexanderzobnin** [comment]
@ceinmart Use code from develop branch. This problem was fixed.

**Comment by ceinmart** [comment]
Thank you @alexanderzobnin  !
Works perfect!
