### ISSUE TITLE
Support __range_s variable in the Loki query editor.

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#25561]
Like with Prometheus, upcoming Loki topK queries need the correct range to return the expected number of results. $__interval is supported, but this returns more results than the limit set in the topK, which is correct but counter-intuitive and not what is needed by the user. See also the Prometheus docs here: 
https://grafana.com/docs/grafana/latest/features/datasources/prometheus/#templating

Loki is going to support the following syntax in upcoming versions:

topk(5, sum by (ipaddress) (count_over_time({filename=\"/var/log/nginx/access.log\"} | regexp \"(?P<ipaddress>\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3}\\\\.\\\\d{1,3})\"[10m])))

**Comment by candux** [comment]
I also wrestled with this problem for some time. 
One workaround is to set "Max date points" in the Query Options to 1. 
Then $__interval is always equal to what would be $__range

**Comment by Phara0h** [comment]
Any updates on this bad boy?
