### ISSUE TITLE
Don't send datasource passwords to the browser

### ISSUE THREAD

**Issue by tmonk42** [grafana/grafana#2557]
Was poking around, and it looks like if you enter a User/Password for Basic Auth, the value of the password is passed back to the browser when you go to edit that datasource. Not sure if there's a better way to handle this, since you need to be an Admin to edit/view datasource definitions. Maybe these passwords could be held in the DB like user passwords.
![screen shot 2015-08-19 at 10 07 27 am](https://cloud.githubusercontent.com/assets/4541/9363249/2644f63a-465a-11e5-8f1c-4411d79e2e7f.png)

**Comment by torkelo** [comment]
thanks for reporting this

**Comment by daniellee** [comment]
This security issue has already been fixed, so we’re going to go ahead and close this.

Passwords are now also encrypted in the database since Grafana 6.2:

https://grafana.com/docs/grafana/latest/installation/upgrading/#ensure-encryption-of-data-source-secrets
