### ISSUE TITLE
Disabling line wrap in Explore causes extra 'frame' to appear in Firefox

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#25571]
**What happened**:
Using firefox (77.0.1, macOS) with Explore, toggling the 'wrap lines' causes the rendered logs to pop in/out of some sort of hidden iframe/scroll area. I've reduced the amount of lines shown in this gif just to clearly illustrate the issue, but this is repeatable whether or not you've used text filtering or any other default settings. Does not occur in chrome. A similar issue was previously fixed in #24205 

![Kapture 2020-06-12 at 14 07 11](https://user-images.githubusercontent.com/1272954/84533392-0bc97980-acb6-11ea-9699-48244a4d80ac.gif)

**What you expected to happen**: 
Lines should wrap or not wrap, but this extra element should not be visible

**How to reproduce it (as minimally and precisely as possible)**:
In firefox select a Loki log stream with events. Toggle the line wrap on/off.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Loki 1.5.0
- OS Grafana is installed on: Ubuntu 18
- User OS & Browser: MacOS 15.5.5 Firefox 77.0.1 
- Grafana plugins: n/a

**Comment by aocenas** [comment]
Seems like the issue is that we show all the scrollbars when lines are not wrapped whether they actually overflow or not.

**Comment by aocenas** [comment]
The fix will not show them if they are not needed but as these are native scroll bars they will still probably look ugly if they are present but at least it should be clear those are scroll bars.
