### ISSUE TITLE
Table: Support filtering by column value

### ISSUE THREAD

**Issue by fsa1803** [grafana/grafana#25570]
**What would you like to be added**:
New Table panel in 7.0, add "Filter for value" for Log Metrics with Elasticsearch datasource

**Why is this needed**:
In previous version I'm using "Raw document" metric, where this option was available. Now "Raw document" metric not allow a correct .CSV export, because it show only raw JSON documents.

**Comment by sakjur** [comment]
I'm not sure I understand what feature you're referring to. Could you please provide some more details of what the problem you want solved is and how you'd like for it to work? (preferably with screenshots)

**Comment by fsa1803** [comment]
With old table panel, with Elasticsearch datasource:
![img02](https://user-images.githubusercontent.com/66841577/84754398-9f55bf80-afc0-11ea-8e42-effc130af0ac.PNG)

I can filter table data like this:
![img01](https://user-images.githubusercontent.com/66841577/84754520-cb714080-afc0-11ea-8929-1a5856e05f3b.PNG)

With new table panel we can use Logs metric:
![img03](https://user-images.githubusercontent.com/66841577/84756165-bdbcba80-afc2-11ea-9195-59054a7120c6.PNG)

but without filter value.

It would be helpful, for Logs Metric, to have this possibility.

Thanks

**Comment by torkelo** [comment]
Already done and coming in 7.1 https://github.com/grafana/grafana/pull/25467

**Comment by torkelo** [comment]
You can try it in nightly builds
