### ISSUE TITLE
Logs Panel not working

### ISSUE THREAD

**Issue by hvdort** [grafana/grafana#25578]
The logs panel shows only a square white dot in the upper right corner. No logs showing. Switching to table panel it shows data.

- Grafana version: 7.0.3 (upgraded from 7.0.0)
- Data source type & version: Graylog (Elasticsearch)
- OS Grafana is installed on: Linux Redhat
- User OS & Browser: Windows & Chrome
- Grafana plugins: Logs (core)
![image](https://user-images.githubusercontent.com/64264862/84574878-c9816480-ada9-11ea-81f5-85d40dfd5df9.png)

**Comment by torkelo** [comment]
In the query "Metric" option, specify Logs
