### ISSUE TITLE
Revamp GitLab OAuth2 Authentication

### ISSUE THREAD

**Issue by vladdy** [grafana/grafana#25573]
**What would you like to be added**:
Hi! I'd like to offer to get rid of API calls during OAuth2 authentication with GitLab as the service currently provides all the necessary information via the OpenID endpoint (https://docs.gitlab.com/ee/integration/openid_connect_provider.html#shared-information).

**Why is this needed**:
The current implementation requires `api` or `read_user` scopes to authenticate a user, however it appears to be excessive as `openid` and `profile` should be enough.

Would you be open for a PR for the above change?

**Comment by marefr** [comment]
> Would you be open for a PR for the above change?

@vladdy we're always open to PR's, but if we accept it is a later discussion. The feature request sounds valid though

**Comment by sakjur** [comment]
> [...]should apply to all different oauth provider

Are scopes standardized in OpenID Connect? From a pure OAuth perspective, this change sounds to me like it's beyond the standard and in the IdP specific configuration, so it would make sense to apply specifically for GitLab imo

**Comment by vladdy** [comment]
> [...]should apply to all different oauth provider

@marefr, can you please clarify why do you think it should be applied to all different providers? AFAIK, the groups is not a standard claim (https://openid.net/specs/openid-connect-core-1_0.html#StandardClaims). My reasoning for proposing the change is to avoid giving unnecessary permissions to the OAuth2 tokens used by Grafana with GitLab as IdP, which should improve the security of already existing functionality.
