### ISSUE TITLE
Cannot change "cache timeout" when using graphite data source

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#25575]
**What happened**:

I have tried to change the "Cache timeout" under "Query options"

**What you expected to happen**:

When I wrote a number in the "Cache timeout" field, instead of the "Cache timeout" changing, the "Max data points" have changed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Edit any graphite dashboard (e.g. https://play.grafana.org/d/000000022/graphite-panel-repeats-hidden?tab=query&orgId=1&editPanel=3 )
2. Click on "query options"
3. Write number on "Cache timeout" (in my example I wrote "4") 

Select "cache timeout" textfield:
![image](https://user-images.githubusercontent.com/8693064/84572677-bb811300-adac-11ea-96dd-856a3579ae52.png)

Write number:
![image](https://user-images.githubusercontent.com/8693064/84572681-c6d43e80-adac-11ea-8956-2796dda6cd21.png)

4. Observe the "Cache timeout" text field, but the number you wrote ends up in "Max data points" text field

**Environment**:
- Grafana version: Grafana v7.0.3 (00ee734baf)
- Data source type & version: Graphite
- User OS & Browser: macOS with Chrome

**Comment by sakjur** [comment]
Seems like the cache timeout is accidentally connected to the max data points value instead of it's own value 👍 Thank you for reporting this!

@mckn See
https://github.com/grafana/grafana/blob/bd76c66e5058b1820570044e21f4cbb9239d7a24/public/app/features/dashboard/panel_editor/QueryOptions.tsx#L154-L166
