### ISSUE TITLE
Grammar mistake in dashboard

### ISSUE THREAD

**Issue by callahan22** [grafana/grafana#25572]
Running latest version of Grafana.
- New Dashboard
- Transform tab

Warning states: "Many transforms are not suitable if your using the Graph visualization as it currently only supports time series"

You mean "you're", not "your".

:-)

**Comment by neufeldtech** [comment]
Note: this was fixed in https://github.com/grafana/grafana/pull/24966

**Comment by zoltanbedi** [comment]
Thanks for confirming this @neufeldtech. I'm going to close this issue.
