### ISSUE TITLE
snashot export to raintank.io is not showing my 2nd annotation query

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#25577]
I am only getting the first annotation query lines on the chart. However the chart does have on the top the on/off switch for this query.

**Comment by sakjur** [comment]
Hi, I'm not sure I understand what you mean with this report, could you answer these three questions one by one so I can reproduce and verify this issue?

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md

**Comment by torkelo** [comment]
snapshots wont have the switch, only the data you had when you created the snapshot
