### ISSUE TITLE
Image render plugin is not working properly.. 

### ISSUE THREAD

**Issue by rnachire** [grafana/grafana#25584]
Hi, 
Image render plugin is not working properly.. 

> 
error getting panel {Id:32 Type:graph Title:Top5 Node CPU Usage \% GridPos:{H:5 W:24 X:0 Y:24}}: Error obtaining render: 500 Internal Server Error

However, it is not grafana issue, but why did we make this as external dependency for pdf exporter.. Please consider this and make this as implicit.. and also what are the benefits/problems we get when we make image rendering as another container.. 

please pass us if any k8s deployment manifest for the same with pdf-exporter, image rendering.

**Comment by torkelo** [comment]
Because the image / pdf rendering needs chrome running to load Grafana and capture images. And chrome is huge dependency, both in binary size but also in memory usage. Making this an optional plugin had a ton of advantages 

Please review your server logs to troubleshoot your issue
