### ISSUE TITLE
Provide an API to export the Legends data in csv/xls format

### ISSUE THREAD

**Issue by rnachire** [grafana/grafana#25583]
Provide an API to export the Legends data in csv/xls format

As most of the time, we would be focusing on summary of the panel which is present in legends in table format.

We need a way to export this in csv format, it can be easily presentable in other systems or to business executives about previous report.

Please consider this is as enhancement request..

**Comment by sakjur** [comment]
The legends summary is a component of a particular graph, not something which is ubiquitous in Grafana. With the new **transformations** feature in Grafana 7.0 you can use the "Add field from calculation" to calculate equivalent values to that which is displayed in the graph panel's legend that can be exported from the **Inspect > Data** option for the panel.

I'll close this feature request as I think we're already providing the functionality requested (but in a different way). If I've misunderstood or am underestimating the differences between what I'm proposing and what you want, feel free to keep using this issue and we'll reopen it if it becomes clear that this is a feature that has both some interest (by a :+1: reaction on the first comment 👆)  and a viable implementation.
