### ISSUE TITLE
Bug: Drag drop panel broken in v2.1.1

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#2558]
Hello! I use Grafana 2.1.1 and have noticed strange panel behavior:

![panels_bug_2 1 1](https://cloud.githubusercontent.com/assets/4932851/9365221/12d5c61a-46b9-11e5-87a1-d0dbb4d17731.gif)

Instead moving it was copied. And then all changes are affected to both panels.

**Comment by torkelo** [comment]
Thanks for reporting this, looks like a pretty big bug in 2.1.1, cant believe it hasnt been reported until now, will fix asap tomorrow and release patch release

**Comment by alexanderzobnin** [comment]
Great thanks!
