### ISSUE TITLE
Using MySQL as datasource

### ISSUE THREAD

**Issue by ceinmart** [grafana/grafana#2559]
Hi , 

I'm trying understand how create a datasource-plugin. 
My objective is create to informix, but I found a SQL prototype at grafana install :  /usr/share/grafana/public/app/plugins/datasource/sql
So , I like to try mysql first...

I know this isn't work... 
I like to know if until today anyone implement a access to MySQL ? 
I just not found where... 

Is there a tutorial to guide what Is needed to create a datasource plugin ? 
how grafana flows, whats is need for each file , standards , thinks to concern...  
Isn't intuitive for who never code in javascript.. 
and at grafana-plugin , I found nothing useful... at least what I capable to understand.. 

Thanks

**Comment by torkelo** [comment]
no I do not know of anyone who has implemented a sql data source. 

There is not documentation yet on how to write a data source plugin, most have looked at the existing plugins as reference.

**Comment by dduleep** [comment]
why we cann't use any SQL data source?

**Comment by torkelo** [comment]
@dduleep because someone has to implement the support for it before someone can use it :)
