### ISSUE TITLE
grafana  how to support yaxes  format millicores

### ISSUE THREAD

**Issue by zhangschunfeng** [grafana/grafana#25598]
my database is influxdb , i  use grafana to display cpu/usage_rate
cpu/usage_rate | CPU usage on all cores in millicores.
but   grafana has no millicores   unit ,not support cpu 

**Steps to reproduce**:

**Actual Result**:

**Expected Result**

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version:6.6
- Data source type & version: influxdb
- User OS & Browser: 
- Others:

**Comment by sakjur** [comment]
You can type in millicores as a custom unit (see animation below), would that work for you?

![setting custom unit to millicores for a graph panel's second y-axis](https://user-images.githubusercontent.com/298945/84661027-02404b80-af1a-11ea-958b-279d0a86cba0.gif)

**Comment by torkelo** [comment]
don't think we need a custom unit for this, you can use short, as it's just a basic thousands unit

**Comment by sakjur** [comment]
You could use multiple queries and [expressions](https://grafana.com/docs/grafana/latest/panels-visualizations/query-transform-data/expression-queries/) or the query language to ensure that the unit is the same?

Something like `$A*1000` to convert per core usage to millicore usage.

**Comment by consideRatio** [comment]
With grafana 11, we can use `SI Prefix` unit, which provides the `m` or the milli prefix, so a value like 0.123 becomes 123m which would be nice for CPU.

I think further use of SI prefix could perhaps be adjusted so that it provides ` cores` after, presenting it like `m cores` or similar.
