### ISSUE TITLE
Spelling error on Tranformations tab of panel

### ISSUE THREAD

**Issue by fatpelt** [grafana/grafana#25608]
**What happened**: Spelling error on the transformations tab on a panel.
"Transformations allow you to join, calculate, re-order, hide and rename your query results before being visualized.
Many transforms are not suitable if your using the Graph visualization as it currently only supports time series.
It can help to switch to Table visualization to understand what a transformation is doing. "

"Many transforms are not suitable if *you're* using the Graph visualization...."
or
"Many transforms are not suitable if you are using the Graph visualization..."

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**: Open a new dashboard -> open a graph panel -> click on the "Transform" tab

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- OS Grafana is installed on: Ubuntu 18

![Screen Shot 2020-06-15 at 11 24 25 AM](https://user-images.githubusercontent.com/6977736/84687325-cc3f9f00-aefa-11ea-89f1-bac4e2398a91.png)

**Comment by zoltanbedi** [comment]
Thanks for letting us know @fatpelt. This is already fixed in master.
