### ISSUE TITLE
Direct links to panels embeded in a row do not work in Grafana 7.0.0

### ISSUE THREAD

**Issue by jaroslawr** [grafana/grafana#25607]
When I do "View Panel" on a panel embedded within a row, the browser navigates to a URL like this:

https://grafana.something.net/d/_iE-SVDZk/some-dashboard?viewPanel=123&orgId=1&from=now-90d&to=now

When I paste this url into a new browser tab, I get the error: "Panel with id 123 not found"

This is on:
Grafana v7.0.1 (ef5b586d7d)

**Comment by sakjur** [comment]
**Steps to reproduce**

1. Create a row.
2. Add a panel to that row.
3. Fold the row.
4. Save dashboard.
5. Unfold the row, press view on the panel, copy URL.
6. Paste URL in browser:
  **Expected:** Single panel view for the panel you just created
  **Happens:** Browser ends up on the dashboard with the error message mentioned in the first comment

**Comment by torkelo** [comment]
Try 7.0.3
