### ISSUE TITLE
Use timeshift in one graph

### ISSUE THREAD

**Issue by kapayi** [grafana/grafana#2560]
hi, I have used the time shift in time range, but it works for graph not query
what I need is to look at now and 7d ago in one graph, but if use time shift, I have to look now and 7d ago in two graph
ps: I am use influxdb as data source

**Comment by torkelo** [comment]
For this to work it needs to be supported by the time series store, like Graphite has a timeShift function that does this, so for now please request this feature in from InfluxDB
