### ISSUE TITLE
Documentation incorrectly says Variables are allowed in alerts

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#25605]
**What happened**:
The documentation at 
https://grafana.com/docs/grafana/latest/alerting/create-alerts/#notifications says 

   "Message - Enter a message to be sent on the notification channel. The message can be in text, markdown, or HTML format. It can include links and variables as well.
I've tested this in a test alert, and even fixed variables are not translated at all.
Is this a documentation bug ?

**What you expected to happen**:
This is incorrect, variables are not currently processed in alerts. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version:n/a
- OS Grafana is installed on:n/a
- User OS & Browser:n/a
- Grafana plugins:n/a
- Others:n/a

**Comment by torkelo** [comment]
@bergquist 

I think the docs are incorrect here 

>  It can include links and variables as well.

Especially variables part (the notification message can include links), but not variables.

**Comment by sergeivalko** [comment]
i can send logs from elasticsearch into alert message ?

**Comment by bergquist** [comment]
@sergeivalko no thats not supported.

@torkelo yea Im not sure how that ended up there. At its core we only support text. Alert notifications can then turn that into HTML or links if they support it. 

Fix inc
