### ISSUE TITLE
Sorting table rows is not saved when saving the dashboard in Grafana 7

### ISSUE THREAD

**Issue by steenstra** [grafana/grafana#25615]
Sorting the table by clicking on the column name and saving the dashboard doesn't work anymore with tables created in Grafana 7.

It does work with the tables created before Grafana 7, since they have a different format:
"type": "table-old"

See also:
https://github.com/grafana/grafana/issues/14787

I've also tried to sort it by adding:
`"sort": {
    "col": 2,
    "desc": false
  },`
in the panel json, but that didn't seem to do anything either.

**Comment by sakjur** [comment]
This should be fixed in 7.0.3, let me know if you're running 7.0.3 and it's still not working.

**Comment by steenstra** [comment]
Thanks Sakjur, upgrading to that version solved it for me.
