### ISSUE TITLE
Table transform in Grafana 7

### ISSUE THREAD

**Issue by xAnder1402** [grafana/grafana#25616]
How to convert a table with time series to columns in the new table pane in Grafana 7?
The old table panel in Grafana 6.7.3 converts a table with time series into columns.
I used Grafana version 7.0.3 with datasource InfluxDB

I use the format as: Timeseries
![image](https://user-images.githubusercontent.com/12598781/84734458-9279a180-afa9-11ea-9527-220e9bf6c211.png)

How it looks without transformation:
![image](https://user-images.githubusercontent.com/12598781/84734489-a4f3db00-afa9-11ea-8f81-ea6a33dd262c.png)

How it should look:
![image](https://user-images.githubusercontent.com/12598781/84734122-c86a5600-afa8-11ea-9852-1c33c2598cc5.png)

Parameter item of the old table panel:
![image](https://user-images.githubusercontent.com/12598781/84734197-fea7d580-afa8-11ea-8e85-51786b6ecd5a.png)

**Comment by torkelo** [comment]
Format as Time series in query, 

Use new table visualization, then use the Outer Join reducer
