### ISSUE TITLE
InfluxDB: Improve error message when no valid query is specified (missing measurement) 

### ISSUE THREAD

**Issue by erwinw** [grafana/grafana#2561]
When connecting an Influxdb data source (0.9.2) in proxy mode, with a working connection, and trying to add a graph, all I get is a console error 'Panel data error: Metric measurement is missing'. No other information is available in browser or in logs, no matter if I change the log levels or try setting breakpoints.

Version details: grafana 2.1.1, influxdb 0.9.2, server: ubuntu, vanilla install from APT repo, browser Chrome 44 on MacOS X 10.10.4 (fwiw).

**Comment by erwinw** [comment]
The little error indicator, by the way, shows "timeseries data request error", clicking it produces a popup with tabs Request, Response and JS Error with several labels - but no values whatsoever.

**Comment by torkelo** [comment]
Thanks for reporting this, will make sure the error message is more helpful. 

Before you get data in the graph you need to enter an InfluxDB query: 


![influxdb_09_update](https://cloud.githubusercontent.com/assets/10999/7678060/65deb472-fd51-11e4-9651-ffbf339f70b5.gif)

**Comment by erwinw** [comment]
Oh wow.

Not to be bitchy but I would *never* have guessed that. I never even noticed that the title was a button. Could I suggest opening that menu when you create a new graph (if there are no other ways to configure it)?

**Comment by torkelo** [comment]
Even when the title says `(click here)` and it is mentioned in the getting started guide, included in the annotated screenshots in the docs? 

I know it is very intuitive though :(  compromise between intuitive and elegant graphs that aren't covered in buttons :)'
