### ISSUE TITLE
Interpolate variables in backend data source plugins Not support repeat options

### ISSUE THREAD

**Issue by tomjamescn** [grafana/grafana#25614]
**What happened**:
If there is a variable named *some-variable* in the dashboard which is multi value [1, 2, 3]
```
import { getTemplateSrv } from '@grafana/runtime';
const variableValue = getTemplateSrv().replace('$some-variable'), options.scopedVars);
```
if enable repeat by variable *some-variable*, the variableValue is not the current value, but all of the options values. 

For example:
in the first panel, variableValue should be 1, but is [1, 2,3].
in the second panel, variableValue should be 2, but is [1, 2,3].
in the last panel, variableValue should be 3, but is [1, 2,3].

**What you expected to happen**:
in the first panel, variableValue should be 1.
in the second panel, variableValue should be 2.
in the last panel, variableValue should be 3.

**How to reproduce it (as minimally and precisely as possible)**:
```
import { getTemplateSrv } from '@grafana/runtime';
const variableValue = getTemplateSrv().replace('$some-variable'), options.scopedVars);
console.log(variableValue)
```

**Anything else we need to know?**:
the mysql datasource plugin worked as expectd.

**Environment**:
- Grafana version: 7.0.3 and plugin @grafana/runtime version is  7.1.0-pre.0-b1dee9392b (because 7.0.3 applyTemplateVariables not worked)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Unable to replicate, can you console log options.scopedVars? 

When testing here: https://play.grafana.org/d/dfOf9RWGk/variable-repeat-used-in-query?orgId=1  

It uses the variable in the query (to set alias (legend name)) to $server and it has the correct value for each panel

**Comment by torkelo** [comment]
Ah I see your error:

scoped vars is an argument to replace! You should write it as: 
```ts
const variableValue = getTemplateSrv().replace('$some-variable', options.scopedVars);
```

**Comment by tomjamescn** [comment]
I'm too late. @torkelo  thank you!
