### ISSUE TITLE
Alerts tab should not be hidden when alerts are disabled.

### ISSUE THREAD

**Issue by kogent** [grafana/grafana#25612]
**What happened**:
In #25285 the alerts enabled config was made to hide the alerting tab if alerts were disabled to fix #25143. This breaks clustered deployments where only some nodes are desired to run alert queries, by causing the alerting tab to be hidden.

**What you expected to happen**:
The alerting tab to be available.

**How to reproduce it**:
Setup two or more grafana instances using the same database backend, have alerts enabled on 1 or 2 of the instances but not all. Have UI traffic go to only the nodes that do not have alerts enabled.

Alerting tab should be visible.

**Anything else we need to know?**:
Because every node that has alerting enabled runs the alert queries, and some of our datasources cannot handle that amount of queries, we need to run alert queries on less than the full number of nodes running the Grafana UI.

We solve this by running two clusters with the same mysql backend.  One larger cluster services UI requests and one small cluster only runs alert queries.

We need to be able to access the alerting tab on the UI nodes without enabling alerts.

I'm opening this issue in response to suggestion from @marefr in the community slack.

**Environment**:
- Grafana version: 7.0.3

**Comment by torkelo** [comment]
you should not disable alerting in this case, only execute_alerts
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L570
