### ISSUE TITLE
API tokens that can have permissions based on teams/users instead of org role. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#25620]
Currently, API tokens can only be associated with org roles (viewers, editor, admin) for all dashboards and folders. This makes it impossible to give users API tokens that can only access/edit dashboards that they have access to. Instead, they have to resort to using API tokens that have more access than the user has. This makes automation hard when data isolation is important. This is a limitation for Organizations that operate under a "trust no one" security model.

The org role-based API tokens can be used in CI/CD pipelines but then it's up to the operators to solve that for all teams within an org. Having API tokens with the same access as users would enable teams to build/update dashboards way they see fit. 

Disclaimer: So far we have not made any decisions if a solution for this goes into Grafana OSS or Grafana Enterprise

**Comment by ahurtaud** [comment]
Hello,
+1 for this feature.
On our side, we would love to be able to add permissions of an API Token to a folder (or attach the API Token to a team):

![folder_perms](https://user-images.githubusercontent.com/25080995/100465670-0333f680-30d0-11eb-8f64-d5a065af39bd.png)

What do you think?
