### ISSUE TITLE
Table: Support text wrapping 

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25623]
I have a table which presents a long text from database.
The new table plugin does not wrap the text and so I can't use it with the new table.

It would be great if you could preserve the text wrap behavior that the old Table plugin had, or at least, ,allow customization.

**Comment by paregupt** [comment]
This will help. I was using it in 6.x but missing it in 7.x

**Comment by rakhadityap** [comment]
I need this too, and yes it was exist in old table panel and now it's gone in v7

**Comment by Tepew** [comment]
In version 7.0.3 type Table ignore '\n' and information looked inreadble. I must forget about some dashboards..

**Comment by bhozar** [comment]
For long(-ish) fields cutting the rest of the line off is not helpful in the new table. The old table wrapped based on length, which worked well for fields not containing \n. If that could be added in it would allow me to migrate most of the rest of my table panels to the new plugin.

**Comment by vishnukrishnan01** [comment]
Is this issue fixed / the feature available in grafana v7+ ?

**Comment by jehutywong** [comment]
+1

**Comment by scmilburn** [comment]
also trying to display long text from from influx would be nice to wrap cell

**Comment by kumaravel29** [comment]
+1

**Comment by maxless** [comment]
+1

**Comment by bacsog** [comment]
+1

**Comment by pintonunes** [comment]
+1

**Comment by mulhoon** [comment]
+1 This would really help. Sometimes an important bit of text is right at the end of the line.

**Comment by mulhoon** [comment]
+1 
A workaround is to use overrides and set the desired field to **Cell display mode: JSON View**. This shows the full text on hover. Not ideal, but better than not being able to see the text.

**Comment by ViktorReis** [comment]
+1

**Comment by aordines-vdm** [comment]
+1

**Comment by jmk75** [comment]
+1

**Comment by suraj-james** [comment]
It would be great if we can get this back in v8 at least. A lot of demand for this feature from our users. Having line break as an option would be a plus. 

And yes, pagination would also help (as text wrap is not possible with infinite scroll) in increasing the load time. Would be good to add pagination as an option in field options for. 

Thanks!

**Comment by atummid** [comment]
+1

**Comment by x-merlin-x** [comment]
+1

**Comment by everythings-gonna-be-alright** [comment]
+1

**Comment by Fornori** [comment]
+1

**Comment by 09jvilla** [comment]
+1 - this would be really useful. I'm surprised because sometimes I do see the table expand to show me the text when I mouse over, but other times I don't.

**Comment by GabrielMend** [comment]
+ 1

**Comment by ashishkaransingh** [comment]
+1

**Comment by dirkallaert** [comment]
+1
Recently moved dashboards from Kibana to Grafana. Grafana is ok for metrics, but for logs it is not as usable as Kibana. The logs panel is not really an alternative. The table panel is missing word wrapping, highlighting and also the +- filter buttons are not available for long log lines. Using JSON view is sometimes an alternative, but then the +- filter buttons are not available at all.

Word wrapping would really be a great first step. Maybe also add an option to truncate a line after x characters?

**Comment by trader-payne** [comment]
+1

**Comment by moechs** [comment]
+1

**Comment by pedro948** [comment]
+1

**Comment by davidjmorin** [comment]
+1

**Comment by moechs** [comment]
+1

**Comment by vistarsvo** [comment]
+1

**Comment by Romathonat** [comment]
+ 1

**Comment by mehdi-kaytoue** [comment]
+1

**Comment by alifxyd** [comment]
+1

**Comment by viniropke99** [comment]
+1

**Comment by ristoporila** [comment]
+1

We were using https://github.com/grafana/grafana/issues/25623#issuecomment-739885051 mentioned json workaround, but we upgraded to Grafana 8 and this doesn't work correctly anymore. The full text after hovering is 2 characters wide, so impossible to read.

**Comment by easy2stake** [comment]
+1

**Comment by RisunJiang** [comment]
+1

**Comment by staeglis** [comment]
+1

**Comment by philkunz** [comment]
+1

**Comment by CanuckMarc** [comment]
+1

**Comment by Sourve** [comment]
+1

**Comment by welyss** [comment]
+10000

**Comment by tlifschitz** [comment]
+1!!

**Comment by ShilpaSivanesan** [comment]
+1

**Comment by helinmik** [comment]
+1

**Comment by FuzzyThailand** [comment]
+1 this is a must-have

**Comment by tugceozgur** [comment]
+

**Comment by JakUi** [comment]
I second that

**Comment by dmachehin** [comment]
+1

**Comment by jmk75** [comment]
> Or even just show the full text as a info bubble when hovering over the cell

This is already there: Just select JSON format.

**Comment by pconwell** [comment]
While the hover bubble is okay as a stop gap, it is not ideal in my situation because some of the free text fields can be quite lengthy. Additionally, the bubble is not configurable (I cannot set a width, for example) and it does not logically break at white spaces. Once it gets to a certain number of characters (I think 55 characters), it wraps the line regardless if it's in middle of the word, etc.

**Comment by Ryuras2012** [comment]
+1

**Comment by nicoarapaul** [comment]
+1 I need it in v8, I use old table config because I like to be wrapped.

**Comment by juanjoku** [comment]
+1 I'm using the old table too, because this issue.

**Comment by wfjm** [comment]
+1 I've run into the same issue.  
We've 8.x since some time, and popular features, which got lost from 6.x to 7.x, are still missing.

**Comment by wfjm** [comment]
See also https://community.grafana.com/t/table-panel-and-text-wrap/58041/5 .  
The proposal to use table-old via hacking the panel json simply doesn't work for me.  
Even if it would, it would be fragile and could break at any moment.  
The only solution is to add this simple but highly needed feature into 8.x.

**Comment by SAPFMI** [comment]
+1 This feature would be very helpful. Our suggestion would be to provide a pop-up windows, which provides all data in a cell (e.g. double-click).

**Comment by gadol** [comment]
+1

**Comment by Catwoolfii** [comment]
+1

**Comment by jasperjonker** [comment]
I would very much appreciate this feature!

**Comment by JEEVAN28** [comment]
+1

**Comment by szewczyk-m** [comment]
+1

**Comment by pavelnemirovsky** [comment]
+1

**Comment by 1somedreamer** [comment]
+1

**Comment by aga-spb** [comment]
+1

**Comment by konata88** [comment]
+1

**Comment by pva1967** [comment]
+1

**Comment by Man0ell** [comment]
+1

**Comment by galdor** [comment]
Has there been an official comment on the subject by devs ? It would be nice to know if it is going to be fixed one day.

**Comment by yn-alex** [comment]
It feels a bit ignored. But having to hover over the text in order to see the data is very frustrating.
We use a BIG SCREEN with all sorts of data / tables / graphs / gauge metric and when the string inside the tables is long enough the operators can no longer read the data ..

**Comment by galdor** [comment]
Long fields are not the only problem. We use InfluxDB points for alerts, and the message field can contain multiline descriptions with pretty-printed values.  In that situation, the table view is pretty much useless.

**Comment by glep207** [comment]
Have you considered using the Logs plugin? It's quite good a displaying long text.Sent from my Galaxy
-------- Original message --------From: Nicolas Martyanoff ***@***.***> Date: 11/03/2022  15:58  (GMT+00:00) To: grafana/grafana ***@***.***> Cc: glep207 ***@***.***>, Comment ***@***.***> Subject: Re: [grafana/grafana] Table: Support text wrapping  (#25623) 
Long fields are not the only problem. We use InfluxDB points for alerts, and the message field can contain multiline descriptions with pretty-printed values.  In that situation, the table view is pretty much useless.

**Comment by galdor** [comment]
I tried, but it seemed the log plugin can only display one single field per line, while we would like to display multiple attributes in addition to the message. As far as I remember it also wrap the text, but does not interpret newline characters.

A bonus point would be an option to indicate that the content of the table must be printed in monospace font.

**Comment by maxless** [comment]
> I tried, but it seemed the log plugin can only display one single field per line, while we would like to display multiple attributes in addition to the message. As far as I remember it also wrap the text, but does not interpret newline characters.

It does work with newlines while the new table seemingly does not (or I can't find how to enable that with JSON View).

Well, we have to migrate from v6 to v8 to support Elasticsearch 8 so JSON hack is the only option for now. At least it's marginally usable in our case \*sigh\*.

**Comment by sandstrom** [comment]
One solution could be to support the unicode new line character `\u2028` (https://en.wikipedia.org/wiki/Newline#Unicode), and render that as a newline.

**Comment by vdiravka** [comment]
+1

**Comment by hackhowtofaq** [comment]
A temporary workaround.

Use CSV plugin and render your file as csv.

[https://stackoverflow.com/a/67786387](https://stackoverflow.com/a/67786387)

**Comment by msabia92** [comment]
+1

**Comment by Dionis-90** [comment]
+1

**Comment by ZiemniakPL** [comment]
+1

**Comment by kmf** [comment]
Would love this feature

**Comment by hansh0801** [comment]
+1

**Comment by sknaumov** [comment]
I've prepared PR (#53768) to support annotations as a data source for the new table, but without this feature my changes are useless, as annotations often contain multi-line text.

**Comment by psheehymn** [comment]
+1

**Comment by spencer-ze** [comment]
+1

**Comment by NickSmet** [comment]
+1

**Comment by bitzhuxb** [comment]
+1

**Comment by kreyssel** [comment]
+1

**Comment by pax0r** [comment]
+1

**Comment by ElementalWarrior** [comment]
As an aside, if you turn on cell value inspect (I used the override for string columns), you can click the eye icon, and copy the text, which includes escaped newlines that were converted to just white space.

**Comment by wuetz** [comment]
+1111111

**Comment by figotee3** [comment]
+1

**Comment by maleksan** [comment]
+1

**Comment by Orishkevich** [comment]
+1

**Comment by cdiamantis** [comment]
+1

**Comment by mnorkin** [comment]
+1

**Comment by CMLMcGinn** [comment]
+1

**Comment by nantiferov** [comment]
It's usually added to issue template that if you're interested in this feature, just add 👍  to the issue description rather than posting **+1**

<img width="509" alt="image" src="https://user-images.githubusercontent.com/75987872/213663776-0c6bdc44-d150-4f3c-ab04-b6881ed42fe0.png">

**Comment by sawo1337** [comment]
After removing the option to cache query results in variables, this is yet another option that makes the newer Grafana versions a downgrade as compared to previous ones. Please implement this, it renders the new table panel useless for a lot of people.

**Comment by FrederikNygaardSvendsen** [comment]
+1

**Comment by Sebastiaan76** [comment]
+1, this is such an obvious thing for the table visualization. Why won't any of the devs even comment on this?

**Comment by jinnerbichler** [comment]
This feature would help us as well.
+1

**Comment by ArrEssJay** [comment]
Another upvote for this. This is a basic table/cell formatting feature that's sorely missing.

**Comment by colin-lee** [comment]
+1, waiting so long

**Comment by supilee** [comment]
@gilkgit, we are looking into it. It's not forgotten and also on our list to investigate on how it can be supported. 
The REACT table being used is not supporting this though, so it will be tricky. We will update here as soon as we have figured out whether or not it can be supported at all

**Comment by gualber98** [comment]
+1

**Comment by sawo1337** [comment]
> @gilkgit, we are looking into it. It's not forgotten and also on our list to investigate on how it can be supported. The React table being used is not supporting this though, so it will be tricky. We will update here as soon as we have figured out whether or not it can be supported at all

2023 and text can't be wrapped in a table? Surely this should be possible?

**Comment by flostoeck** [comment]
+1

**Comment by zibinli** [comment]
+1

**Comment by freddyaway** [comment]
+1
No one is assigned 😢

**Comment by kevinlinxc** [comment]
+1

**Comment by Tafsiralam** [comment]
+1
I am using the Amazon Athena plugin to query and visualize Athena data metrics within Grafana. Everything looks acceptable to me except for the text that does not wrap. To see the complete message either I have to extend the column width or download the full logs. It would be great if we have the text wrap feature in the Athena table.

<img width="1981" alt="Screenshot 2023-06-09 at 3 23 08 PM" src="https://github.com/grafana/grafana/assets/36539677/e625c8ce-beaa-4a7d-902b-e2fc9161f8b6">

**Comment by GollaSaiVenkatesh** [comment]
please look into this, it is a very much required feature

**Comment by kangbobi** [comment]
use datatable

**Comment by sawo1337** [comment]
> use datatable

good idea! although that's quite an old plugin and to be deprecated due to Angular.

**Comment by hemantsingh011** [comment]
must feature to have
+1

**Comment by lbonifazi-totalperform** [comment]
+1

**Comment by liverun** [comment]
My use case is using Grafana to visualize logs forwarded by Fluentd and stored in Loki.
Same as @Tafsiralam

Lack of cell wrapping is frustrating.

**Comment by Slime-Raihon** [comment]
I used a stylesheet as a stopgap measure, as it did not seem feasible with the standard Grafana functionality.
I applied "white-space: normal" only to the "message" column.

![image](https://github.com/grafana/grafana/assets/141822781/17f42c40-c241-454c-bdea-e1fecdfa777a)

Here is an example from Stylus.
```CSS
@-moz-document url-prefix("https://******.com/d/TIYeHqRgZ/syslog") {
    .css-tt7ugn-cellContainerOverflow:last-of-type > div {
        line-height: 1.15;
        white-space: normal;
    }
}
```

**Comment by jHumeLPL** [comment]
Incredible that this feature request has been this active for 3 years and yet still.... no text wrap in cells.  That's bananas.  Does anyone have some code from a Dynamic Text plugin table with word wrap that they can share?  That's the only thing I can think of since it does not appear this is something Grafana is interested in implementing.

**Comment by JoergPf** [comment]
+1 
Hi Grafana, user feedback matters. If you don't look into such a big feature request, you will also overlook other valuable user input. And this usually becomes a problem after a while.

**Comment by liyong7-tal** [comment]
+1
Hope this feature can be added

**Comment by jorijinnall** [comment]
+1 too !

**Comment by borkempire** [comment]
+1

**Comment by qwe5456** [comment]
Hello everyone I just time travelled back from the future and this feature is still unavailable at Oct 10, 2032

**Comment by Jens-Rydholm-Humly** [comment]
This would be very helpful.

**Comment by ericsjones** [comment]
_sigh_... +1

**Comment by ericsjones** [comment]
_sigh_... +1

**Comment by samantaroy** [comment]
+1 please!

**Comment by CMLMcGinn** [comment]
Been so long I've almost forgotten our original use case!

**Comment by dconnolly-sfdc** [comment]
+1, need this capability

**Comment by CptHolzschnauz** [comment]
+1, please.

**Comment by rjemanuele** [comment]
+1 yes, please

**Comment by Itzikg1** [comment]
+1 100%

**Comment by deathsaber** [comment]
+1 Would love this feature

**Comment by RamiSillanpaa** [comment]
It's year 2024 and wrapping still does not work.

+1

**Comment by CanuckMarc** [comment]
[![image](https://github.com/grafana/grafana/assets/40550860/7a6e229b-f29c-40ee-92cc-26eddd19e05b)
](https://www.reddit.com/r/reactiongifs/comments/6gq6go/mrw_bethesda_is_attempting_to_bring_back_paid_mods/)

**Comment by BlackMetalz** [comment]
bumpppppppp. Need this feature implement or dashboard look like sucks
![image](https://github.com/grafana/grafana/assets/3434274/869c91c8-552e-4d0e-981f-b40e94e5dd7e)

**Comment by CommanderTso** [comment]
+1

**Comment by kangbobi** [comment]
> Hi there, I am a proposing a [PR](https://github.com/grafana/grafana/pull/82872) that fixes the visualization of the content of long strings when user moves the cursor over the cell.
> 
> I attach here a video before the fix, and other one with the final result applying the change. [before-fix.webm](https://github.com/grafana/grafana/assets/5576272/edf01f77-ac50-4dc0-b661-8a3caacb0980) [after-fix.webm](https://github.com/grafana/grafana/assets/5576272/a75195ca-5f2e-4389-b18f-fa423802798f)
> 
> I hope it can be useful

is it posible to make wrap text without user move moves the cursor ?

**Comment by SAPFMI** [comment]
Hi Alvaro,

this looks good to me. The only question is: How does it looks like with longer text?

Here an example text (Windows Event):

A user's local group membership was enumerated.

Subject:
     Security ID:         S-1-2-34
     Account Name:        ABCD0104$
     Account Domain:      AZURE
     Logon ID:       0x123

User:
     Security ID:         S-1-2-34-12345678-12345678-12345678-1234
     Account Name:        ProductNameABC
     Account Domain:      ABCD0104

Process Information:
     Process ID:          0xea0
     Process Name:        C:\Program Files\ABC Software\SoftwareName\SubFolder\Program.exe

Regards,
Frane

**Comment by ahuarte47** [comment]
> > Hi there, I am a proposing a [PR](https://github.com/grafana/grafana/pull/82872) that fixes the visualization of the content of long strings when user moves the cursor over the cell.
> > I attach here a video before the fix, and other one with the final result applying the change. [before-fix.webm](https://github.com/grafana/grafana/assets/5576272/edf01f77-ac50-4dc0-b661-8a3caacb0980) [after-fix.webm](https://github.com/grafana/grafana/assets/5576272/a75195ca-5f2e-4389-b18f-fa423802798f)
> 
> is it posible to make wrap text without user moves the cursor ?

Hi @kangbobi, automatic text wrapping would require adjusting the height of all cells in the row. The longer the text, the greater the height needed. In some cases, the table may grow excessively, making proper scrolling challenging, isn't that so?

**Comment by beau-tang** [comment]
Hi all, better than nothing, enable cell options > cell value inspect on the column containing the long text. The eyeball icon will appear when you hover over the text: 

![image](https://github.com/grafana/grafana/assets/162541400/eb8b57ff-dfc7-459b-8ca0-d3e48a9e842d)

Click that and the full contents is visible in a modal:

![image](https://github.com/grafana/grafana/assets/162541400/82f15661-4d94-4413-bd6e-cbed6aa5a153)

**Comment by vistarsvo** [comment]
> Hi all, better than nothing, enable cell options > cell value inspect on the column containing the long text. The eyeball icon will appear when you hover over the text:
> 
> 
> Click that and the full contents is visible in a modal:
> 

Yes, value inspect in overrides is a good feature, but...
If your table has 100+ lines and you need to quickly lookup some text, how many clicks you need to do?

Also, the main problem is text wrapping into table header.

**Comment by darknetehf** [comment]
> Yes, value inspect in overrides is a good feature, but... If your table has 100+ lines and you need to quickly lookup some text, how many clicks you need to do?

It is possible to filter lines by using **variables** in your dashboard. Here is an example. I created a simple dashboard for Python logs with  a combo box to filter lines by logging **level**, and optionally look up lines containing some arbitrary text (here, an event ID string).

The Loki query looks like this:

    `{job="fluentd"} |= `$event_id` | logfmt | levelname =~ `$level_name`

At this point I have pretty much given up on using tables to review logs in Grafana, I have come to the conclusion that a few filters would be sufficient for my purpose.
Splunk does it nicely but it's not FOSS. ELK (Elastic Search/Logstash/Kibana) is a good option but requires more resources than the Fluentd/Loki/Grafana stack I have set up.

![image](https://github.com/grafana/grafana/assets/143291838/3e73c587-b75b-48b6-924d-34fa6f63748a)

**Comment by sbatchu0108** [comment]
+1

**Comment by srindal** [comment]
We use the old table plugin to display alerts on office monitors. The following missing features in the new table plugin have prevented us from upgrading: "Colored rows" and "text wrap". I saw colored rows last week at grafanacon, so now I only miss word wrap. I am aware that word wrap comes with performance issues when combined with very large complicated tables. But we have small tables with a 8 columns and typically < 20 rows. 
![billede](https://github.com/grafana/grafana/assets/9130818/331c8d93-5f40-4d71-8127-d3f5ed52d270)
There are plenty of great looking and advanced features in the new table plugin that is targeted at desktop users. My use case is office monitors.

**Comment by codeincarnate** [comment]
Hey folks! We've heard you on this one and we're in progress for an implementation of this in #86895 🥳. Apologies for the long wait 🙏 , we're getting close and we could use your feedback 😄 

Currently, in this implementation text wraps on one column which is either auto-detected or can be configured to use a specific field with field overrides. This has in part been done for performance reasons, we're simulating the text layout to make this work and that's not cheap 💸 . There's a drawback with this though, if more than one field might have text that is either longer or shorter this approach isn't great since we're not looking at the text of every field.

So we're wondering how common this case is 😃. Do folks normally expect text to wrap on more than one field? Or is it good enough to have text wrapping restricted to a single field? Very curious to see what would be most beneficial for folks. Thanks for any feedack!

**Comment by srindal** [comment]
The case that I have presented have text-wrap spread all over the table - which I think must be the natural look for a multiline table. If you just allow one cell to be multiline, it leads to two problems with how the table looks:

* The single multiline cell will be tall and narrow
* The other cells will be wide and have lots of unused space

I respect that it might be hard to make a perfect solution, but I do believe that for the table to look good, all cells (or a number of cells) must allow text-wrap, if it's allowed. 

Hoping that you will come up with a great solution, thanks. This one is much appreciated 🙏

**Comment by psheehymn** [comment]
One column would be better than the current none, but we have use cases where we need multiple columns to wrap and we'd still have to look for alternatives for those. It would be most ideal to allow any (or at least several) columns to wrap.

**Comment by CMLMcGinn** [comment]
We have several use cases where more than one column would be appreciated. At present we are having to exclude tables from our reports and use Excel, which is defeating the point of having a centralised, flexible reporting tool.

**Comment by ch-plattner** [comment]
I'm excited to see this feature is in progress. Thanks for reaching out to the community for feedback.

We have a use case for text wrapping on multiple fields. We use the table to display structured logs that adhere to a predefined schema, with certain fields like "message" and "params", a json map of key-value pairs. We expect both of these fields to wrap (ideally with "params" shown as pretty-printed json, though that is out of scope of this issue).

**Comment by appi101** [comment]
How do I get a build to try this out?

**Comment by codeincarnate** [comment]
@appi101 this should get an official release in Grafana 11.1. For Grafana Cloud I believe it should roll out within the coming days 😄

**Comment by codeincarnate** [comment]
An update for folks here, we did merge in changes for text wrapping. It's currently limited to single column as we wanted to have it out there at least in limited form. It seems clear from the comments above that multi-column text-wrapping is also desirable so we'll be following up with that soon!

If there's any other feedback please post here and I will definitely be looking here and elsewhere for ongoing feedback for this feature 😸

**Comment by nabelekt** [comment]
This is the first time I am using this feature, so I am not sure if headers normally also wrap, but they are not in my case

![Image](https://github.com/user-attachments/assets/6fd5cc41-5ee7-4800-962f-60c7ac967502)
