### ISSUE TITLE
How to improve Grafana performance ?

### ISSUE THREAD

**Issue by GhostComputing** [grafana/grafana#2562]
Here is my scenario:
     
 - thousands of metrics that already aggregates from every host

 - every time I need to know is the sum of those metrics (apply sum combine)

When I use Grafana to review those combined metrics, I have to wait for a very long time . If I need to know the detail of metrics (such as the value in specific period), I still wait for a very long time.

Can Grafana cache the value automatically and just load the cached value every time I access (not need to be real time) ?

Or any ways to improve the performance of Grafana ?

**Comment by torkelo** [comment]
I cant see how this is a Grafana performance issue, sounds like a performance issue with your time series store. 

Grafana is built for metric queries and time series stores, Graphite can usually handle all times of queries and time ranges in 25-100ms, in some rare expensive queries that target hundreds of series it can take up to 1-2 seconds. 

What time series store are you using? What does the query look like? How many data points does query return? Are you using roll ups?

**Comment by Dieterbe** [comment]
> in some rare expensive queries that target hundreds of series it can take up to 1-2 seconds. 

maybe if you don't have a high write load or have a fast io subsystem (SSD's) and/or low query volume. i don't think you can generalize like this.
i've seen graphite instances taking tens of seconds to respond to queries, and i've heard others mention similar findings.  this can happen if you saturate your storage / have >10 concurrent queries / query for large time ranges.

i agree that you should look at your storage (graphite) though, grafana can't do much.
you may be able to do some graphite tuning, or pre-aggregate your series.
