### ISSUE TITLE
Annotation popup is shown as only a small empty box (elasticsearch)

### ISSUE THREAD

**Issue by lark** [grafana/grafana#2563]
Version: official grafana 2.1.1 debian amd64 package.

It seems that this is caused by annotation title field contains email address. Chrome developer console spits errors such as

```
Error: [$sanitize:badparse] The sanitizer was unable to parse the following block of html: <EMAIL_ADDRESS_HERE> blah blah
```

It works in 1.8.1. There is no requirement or change mentioned in doc that title and text field must be in html sanitized format.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master!
