### ISSUE TITLE
Allow tooltip to show up upon hover in edit mode

### ISSUE THREAD

**Issue by jericvizmanos** [grafana/grafana#25637]
**What would you like to be added**:
Allow tooltip to show up upon hover in edit mode

**Why is this needed**:
Once you enter edit mode, it's no longer easy to know the title or any info of the polystat cards. No information is showing up upon hovering over them. 

Outside Edit Mode:
<img width="858" alt="Screen Shot 2020-06-16 at 9 55 44 AM" src="https://user-images.githubusercontent.com/58444570/84804399-901e4400-afb7-11ea-9b1a-adaf7c04d877.png">

Inside Edit Mode:
<img width="721" alt="Screen Shot 2020-06-16 at 9 53 59 AM" src="https://user-images.githubusercontent.com/58444570/84804408-944a6180-afb7-11ea-8765-635b3998407f.png">

**Comment by torkelo** [comment]
Can you open this here: https://github.com/grafana/grafana-polystat-panel
