### ISSUE TITLE
regression: Grafana 7.0 cannot apply a unit override on a float field.

### ISSUE THREAD

**Issue by drook** [grafana/grafana#25645]
**What happened**:
Regression: grafana 7.0 doesn't apply unit overrides on a float field (see the image below, testFloat column).

![image](https://user-images.githubusercontent.com/2329493/84854595-76463500-b07b-11ea-9d02-a4d4e2387a06.png)

**What you expected to happen**:
6.x version was able to apply a unit override on a float field, 7.0 does this only for integers.

**How to reproduce it (as minimally and precisely as possible)**:
Try to apply a unit override on a table field in 7.0.

**Environment**:
- Grafana version:
Version 7.0.3 (commit: 00ee734baf, branch: HEAD)
- Data source type & version:
Clickhouse datasource 1.9.5
- OS Grafana is installed on:
Linux Centos 7.7
- User OS & Browser:
Windows 10, Firefox 77.0.1/Chrome 83.0.4103.97

**Comment by torkelo** [comment]
It does when I test it: https://play.grafana.org/d/U_bZIMRMk/table-panel-showcase?viewPanel=5&orgId=1 

There is no float internal type in Grafana or javascript, only number. So as long as clickhouse returns the values as numbers it should work. Make sure it's not float numbers wrapped in quotes (strings)

**Comment by drook** [comment]
Well, as far as I can see it's not wrapped in ant type of brackets (I'm attaching part of the CSV below):

````
"Payment_code","type","price","number","testInt","testFloat"
buy_success_group_1_forever,Full,3990,1,1,1
buy_success_org.findmykids.app_month_229_trial_1,Monthly_trial,229,1.5,1,1.5
buy_success_group_3_monthly_trial,Monthly_trial,229,1.5,1,1.5
buy_success_group_3_trial_month,Monthly_trial,229,1.5,1,1.5
buy_success_group_1_activation_full,Full,2490,1,1,1
buy_success_group_3_5y,Full,1990,1,1,1
buy_success_group_4_5y,Full,1490,1,1,1
buy_success_group_5_month,Monthly,99,3,3,3
buy_success_org.findmykids.app_month_229_1,Monthly,229,3,3,3
buy_success_group_2_minutes_large,minutes_large,579,1,1,1
buy_success_group_5_monthly_trial,Monthly_trial,99,1.5,1,1.5
buy_success_org.findmykids.app_month_229_trial_2,Monthly_trial,229,1.5,1,1.5
buy_success_subscription_monthly_id_1,Monthly,229,3,3,3
buy_success_call_group_1_minutes_monthly,minutes_Monthly,2990,3,3,3
buy_success_group_5_minutes_small,minutes_small,45,1,1,1
group_4_app_monthly_2019,Monthly,169,3,3,3
group_4_minutes_large_2019,minutes_large,240,1,1,1
buy_success_call_group_3_minutes_monthly,minutes_Monthly,1490,3,3,3
buy_success_activation_full,Full,1990,1,1,1
buy_success_org.findmykids.app_month_229_2,Monthly,229,3,3,3
buy_success_org.findmykids.app_year_990_trial,Yearly_trial,1290,0.5,0,0.5
````

**Comment by hoboroten** [comment]
I'm having the same problem. Grafana version 7.0.4 (in k8s cluster), datasource - clickhouse.
