### ISSUE TITLE
Prometheus histogram_quantile aggregation by more than one label plots incorrectly

### ISSUE THREAD

**Issue by albertyfwu** [grafana/grafana#25643]
**What happened**:
The result of

```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service"}[$interval])) by (le, grpc_method))```

was not the same as plotting histogram_quantile separately for each value of `grpc_method`:

```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service",grpc_method="GetGridFile"}[$interval])) by (le, grpc_method))```

and

```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service",grpc_method="PostAgvState"}[$interval])) by (le, grpc_method))```

![image](https://user-images.githubusercontent.com/1498227/84842788-e52f7980-affa-11ea-8dc5-999dee702543.png)

**What you expected to happen**:
I expect that the time series values should be equal.

**How to reproduce it (as minimally and precisely as possible)**:
Plot

```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service"}[$interval])) by (le, grpc_method))```

and

```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service",grpc_method="GetGridFile"}[$interval])) by (le, grpc_method))```

and

```histogram_quantile(0.9, sum(rate(grpc_request_duration_seconds_bucket{service="$service",grpc_method="PostAgvState"}[$interval])) by (le, grpc_method))```

**Anything else we need to know?**:
I previously filed this [bug](https://github.com/prometheus/prometheus/issues/7402) in the `prometheus` project, but it appears that the issue is not from Prometheus.

**Environment**:
- Grafana version: Grafana v7.0.3 (00ee734baf)
- Data source type & version: Prometheus 2.17.2
- OS Grafana is installed on: 
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
I think the problem is that you're setting the format to **Heatmap** instead of **Time series**.

**Comment by albertyfwu** [comment]
@sakjur You are right. Sorry about that.
