### ISSUE TITLE
grafana 2.2.0-pre Dashboard Link variable values into Repeat Panel

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#2564]
When having a dashboard with - Settings - Links type dashboard enabled and "add current variable values" spawning into a dashboard which uses Repeat Panel on for example "host" it doesnt repeat the panels from the $host selection from "parent" dashboard. (this worked in 2.1)

**Comment by discoduck2x** [comment]
using influx 0.9.2 if that matters

**Comment by torkelo** [comment]
I think this was fixed 4 days ago, https://github.com/grafana/grafana/commit/0d8303cf5d1d22b8cdaba1ab9a41e36c47cf06db

Can you try a more recent build if 2.2

**Comment by discoduck2x** [comment]
tried the latest from this morning, same thing. some more details:
1. in the parent dashboard i select say 2 hosts, then click the dashboard link
2. the linked dashboard with repeat panels open, but in the host variable field at the top i see my selected hosts from #1 above however as they have dashes in their names they get \- , i recall this was an issue for influx with template variabels and was solved by /$host/ right? my hostnames TEST-SE-01 becmes TEST\-SE\-01+(other selected hostnames)
3. if i click the host dropdown nothing is selected however i can of course reselec there and the repeat works, just seems the /$host/ isnt passed properly in the link?

**Comment by torkelo** [comment]
ok, the fix in https://github.com/grafana/grafana/commit/0d8303cf5d1d22b8cdaba1ab9a41e36c47cf06db contained a subtle bug :(  

Fixed now, will push out new 2.2 builds now

**Comment by discoduck2x** [comment]
works gr8 - nice job @torkelo and awesome product!
