### ISSUE TITLE
Send alerts to different places based on template variable?

### ISSUE THREAD

**Issue by eddieparker** [grafana/grafana#25644]
I'd like to be able to send the alert e-mail to different locations based on a template variable.

The reason for this is that I have a graph that covers many different products, each of which have a different e-mail alias.  The 'alert' query I already respects template variables, and depending on which one is alerting, I'd like it to send an e-mail to the appropriate list.

If this is already possible I apologize, I just couldn't figure out how to set it up.

**Comment by marefr** [comment]
Duplicate of #6557
