### ISSUE TITLE
Grafana shouldn't allow trying to render unsaved panels

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#25648]
**What happened**:
When trying to render an unsaved panel, the image renderer plugin times out. I've found that the reason is actually that the render URL leads to an invalid panel, where Grafana pops up an alert that it is indeed invalid. 

**What you expected to happen**:
I expect for Grafana to not allow trying to render an unsaved panel, since it simply doesn't work.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel and before saving it, hit Share -> Direct link rendered image. The renderer should time out after a minute or so.

**Comment by torkelo** [comment]
Removing milestone and moving to backlog

**Comment by thisisobate** [comment]
Investigated and confirmed: issue still exist on main

**Comment by thisisobate** [comment]
@hugohaggmark I nominate this issue to be our mob candidate for this week! 😀

**Comment by hugohaggmark** [comment]
@thisisobate move it to the mob column so we can keep track of it 😉
