### ISSUE TITLE
Support description(hints) for variables

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25657]
Support description(hints) for variables -
Use case:
I have a dashboard with multiple variable dropdowns.
Some of the users of this dashboard are struggling to understand what the drop-downs are doing.
It would have been helpful if I could add description for each variable which will be presented upon hovering over the variable name.

**Comment by sakjur** [comment]
Please write a description and let me know so I can reopen and categorize this.

**Comment by gilkgit** [comment]
> Please write a description and let me know so I can reopen and categorize this.
@sakjur - Added description.
Perfect - this goes to show how important description is (which I can't add to the dashboard variables)
:)

**Comment by sakjur** [comment]
> Perfect - this goes to show how important description is (which I can't add to the dashboard variables)

:joy: Haha, yes! Thank you for the expansion.

**Note:**
I think this would be an interesting task for someone in the community, but make sure to reach out to us before so we can discuss details a little.
