### ISSUE TITLE
grafana 2.2.0-pre Timepicker Custom

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#2565]
Chooseing a timepicker defined time works, when chosing custom and changing back to time xx:xx it doesnt update the dashboard

**Comment by torkelo** [comment]
cant replicate this, can you describe in more detail the steps you did?

**Comment by discoduck2x** [comment]
Timepicker relative time options: today,5m,15m,30m,1h,2h,3h,6h,12h,24h,2d,7d,30d
1. if i choose any, like last 2h, that works
2. then i choose from timepicker Custom- and change the time manually to back into the future (!?)
nothing happens to the graph timewise, the thimepicke in the top right shows the new setting X hours ago, however if i click the manual refresh button it then refreshes with the previous setting from #1 above (2h ago int this case)

using influx if that matters think not though

**Comment by torkelo** [comment]
thanks for reporting this (and clarifying the issue). Found the bug and fixed it!
