### ISSUE TITLE
Allow configuring default timezone via config file

### ISSUE THREAD

**Issue by brancz** [grafana/grafana#25654]
**What would you like to be added**:

It is possible to configure the default timezone for dashboards via the UI `Configuration > Preferences`, however, it would be nice to have this be configurable via files as well.

**Why is this needed**:

We run all our Grafana instances fully read only and 100% provisioned from files via the datasource and dashboard provisioning features. A lot of dashboards in the community are written using the "default" timezone, which due to lack of configurability in files ends up being "browser", but we'd like all dashboards to default to "UTC".

**Comment by RichiH** [comment]
Good timing; I added to this to today's internal UX feedback session re time picking.
