### ISSUE TITLE
Table: Use text matching to color cell

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25658]
I have a table that presents some text which might represent an error.
In case of error in that text, I want to present the text in red, else green or yellow (depends).
I didn't see any straight-forward way for doing that.

**Comment by peterholmberg** [comment]
Related #25341

**Comment by supilee** [comment]
Please do the following:
1. in Edit mode go to: Value Mappings
2. enter the value you want to be shown in a different color
3. choose the color you want and update
4. go to cell options --> cell type  and select "Colored Text" from the drop down list.

https://user-images.githubusercontent.com/110845248/219969147-a409c88c-fd27-40c7-beb5-385e87e2d3be.mov
