### ISSUE TITLE
Explore: log.level field set to error doesn't color the level bar red

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#25678]
**What happened**:
It's unclear what the colored bar prefix is supposed to mean. I think it should highlight different log levels, but the mechanism that is used to find the log level is not documented in [Explore docs](https://grafana.com/docs/grafana/latest/features/explore/).
I have some log entries that have a field `log.level` set to `ERROR`, but the bar is gray, so I don't know what is its meaning.
![log_prefix](https://user-images.githubusercontent.com/22418250/84947138-63227c00-b0f2-11ea-9eec-3a775950fbd5.png)

**What you expected to happen**:
Field `log.level` to be used to highlight log entry as error (red bar prefix)?

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Maybe provide a configurable field name to be used as log level?

**Environment**:
- Grafana version: Grafana v7.0.3 (00ee734baf)
- Data source type & version: elasticsearch 7.6.0
- OS Grafana is installed on: docker container grafana/grafana
- User OS & Browser: Win10 Firefox
- Grafana plugins: no
- Others: no

**Comment by ivanahuckova** [comment]
@cdalexndr  I have added documentation #28975 to make it more clear how do we extract and determine log level. I hope it helps - so you can adjust logs in a way that Grafana will be able to determine its log level. There is also already also an issue regarding supporting custom log levels #25585 - so if you think something like this would be helpful, please feel free to upvote it.

In your case, easy and fast fix would be to add to log line one of the critical/error expressions that Grafana recognizes. 

/duplicate  #25585

**Comment by cdalexndr** [comment]
Elasticsearch uses `log.level` field to store the log level.
Elasticsearch is widely used.
Shouldn't `log.level` be checked by default before fallback to `unknown` log level?
It would make Grafana more user friendly, by supporting a common framework.

**Comment by ivanahuckova** [comment]
@cdalexndr Would you mind creating new discussion for this enhancement request https://github.com/grafana/grafana/discussions/new.

**Comment by cdalexndr** [comment]
@ivanahuckova done: https://github.com/grafana/grafana/discussions/39356
