### ISSUE TITLE
Gauge didn't work before upgrade to 7.0.3

### ISSUE THREAD

**Issue by marciocamurati** [grafana/grafana#25679]
**What happened**: When I try to add a new gauge, it appear like an empty graph.

**What you expected to happen**: Show the gauge with the correct format.

**How to reproduce it (as minimally and precisely as possible)**: Try to create a new Panel with Gauge visualization.

![alt text](https://iili.io/J6Imyg.gif)

**Environment**:
- Grafana version: 7.0.3
- OS Grafana is installed on: Docker

**Comment by torkelo** [comment]
That is very strange, no other reports like this and unable to replicate, must be something strange with your browser? Can you try to upgrade your browser (try a  different one), or try incognito mode (without plugins). check chrome dev console for js errors: 

Maybe something broken with your install? 
Can you replicate here: https://play.grafana.org/
