### ISSUE TITLE
Editable Automatically Added Dashboards

### ISSUE THREAD

**Issue by FlavioF** [grafana/grafana#2567]
Hi,

I am adding automatically builds dashboards as json files using this configuration:
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards

How can I make this dashboards editable by default? I can't use the 'save as' option to make it editable since it is duplicating the dashboards (and I can't delete the not editable dashboards).

Thank you.

**Comment by torkelo** [comment]
json dashboards cant be saved back (which is why they are set to editable false), do you want to make transient edits which you can later discard or export to json?

**Comment by FlavioF** [comment]
Yes, I want to make transient edits because frequently I need to add new stuff (temporarily or permanently) to a json dashboards. But since I am using docker and my containers can die frequently I don't want to be always importing manually all the default json dashboard that I have.

**Comment by kportertx** [comment]
@FlavioF 

I would like to be able to edit these dashboards so that I can export the edited copy to commit to a git repo. I do not need to be able to save the dashboard, just export the modified version. Is this what you had in mind?

**Comment by FlavioF** [comment]
@kportertx 

Yes, it is the kind of feature I am looking for. I already know the workaround but it is to hard to manage when we have a lot of dashboards. It could work if I could delete the old dashboards (at least). 

However it would be nice if I could save this changes to the dashboard for the case when I want to made temporarily changes.

@torkelo 
If you need any help implementing this feature let me know.

Thank you.

**Comment by yagilm** [comment]
+1 
would be nice to be able to edit these graphs (now it's not even possible to star them)

**Comment by Dieterbe** [comment]
+1

**Comment by kmur911** [comment]
what was the resolution for this ticket? I'm currently still unable to edit automatically imported json dashboards in grafana 4.4.3, is the workaround mentioned by @kportertx of creating a copy of each dashboard to save and export still the best option?
