### ISSUE TITLE
Pie chart hover shown outside

### ISSUE THREAD

**Issue by Vicchi21** [grafana/grafana#25670]
I created a Pie chart/Donut chart in Grafana. when i hover on it, the tooltip is shown somewhere outside the chart area.

**Comment by torkelo** [comment]
Can you open in https://github.com/grafana/piechart-panel ?

**Comment by Vicchi21** [comment]
<img width="906" alt="Error" src="https://user-images.githubusercontent.com/48007736/84913078-bf2bd700-b0d7-11ea-91c1-b82dabc41f01.png">
