### ISSUE TITLE
InfluxDB: Query editor defaults to raw and toggle is stil a bit strange

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#25686]
Adding a new InfluxDB query it default to raw editor: 

![Screenshot from 2020-06-18 09-30-06](https://user-images.githubusercontent.com/10999/84991157-6cd5cf00-b146-11ea-80f1-46a64331f329.png)

* After hitting toggle edit mode, it am still in raw editor mode but now I get a default query
* After hitting toggle edit mode one more time I get the UI builder

**Comment by ryantxu** [comment]
fixed

**Comment by Niranajn0528** [comment]
Hi,
Tried uploading multiple datasets in csv upload but failing each time with below error.
Error:
Failed to upload the selected CSV: error in csv.from(): failed to read metadata: missing expected annotation datatype. consider using the mode: "raw" for csv that is not expected to have annotations.

 Tried modifying the data to raw file and and annotations but still stuck with the above error.
I have a small question, while uploading the csv file we don't have  any option like raw mode right?

![Image](https://github.com/user-attachments/assets/520335dd-d6f7-42a7-a356-686da795d9cb)

Can someone help me to move forward with this issue.
Thanks!
