### ISSUE TITLE
Table Panel - Date/Time format Overrides still not working consistently? (7.1.0~e836f2dfpre)

### ISSUE THREAD

**Issue by therealcodlord** [grafana/grafana#25687]
This whole report is to do with the Table Panel and Unit Override of date/time formats. There were a number of issues logged for this sort of problem, uncluding #25195 I thought that this should now be fixed in the latest nightly build but I was asked to raise this as a new issue so....

**What happened**:
With a MySQL datasource there still does not seem to be any change to a date/time display by choosing a Unit override (e.g. it does not work/does not change the display at all).

With a Test Grafana random walk datasource or a normal Prometheus query the two predefined date formats seem to work but entering a custom date time format such as UK format `DD/MM/YYYY` has no affect. 

With a Prometheus **Instant** query things get even stranger (see "Anything else we need to know?" below).

**What you expected to happen**:
That the display would show the date/time in the supplied format (custom or one of the 2 predefined formats) regardless of datasource.
 
**How to reproduce it (as minimally and precisely as possible)**:
For MySQL - Add a table panel with Table query of `select now() as Time` - adding date/time Unit override to `time` has no affect.
For Grafana Random Walk - Add a table panel and select Grafana datasource - adding a date/time Unit to `Time` has some affect but custom date/time formats are not applied.
For Prometheus - Add a table panel with a query of almost any metric, say `node_boot_time_seconds`  - adding a date/time Unit to `Time` has some affect but custom date/time formats are not applied.

**Anything else we need to know?**:
For a Prometheus INSTANT query the `Time` field is shown by default as e.g. `2020-06-18 08:48:39`
If I select Unit override `YYYY-MM-DD HH:mm:ss` the value is displayed as `08:48:39` (no date).
If I select Unit override `MM/DD/YYYY h:mm:ss a` the value is displayed as `08:48:39 am` (no date).
If I enter a manual format such as `DD/MM/YYYY` it accepts that custom format but the displayed value goes back to being shown as `2020-06-18 08:48:39`.
If I enter a manual format such as `HH:mm` it does NOT seem to accept that custom format, so the 
Unit dropdown value reverts back to `YYYY-MM-DD HH:mm:ss` and the displayed value is shown as `08:48:39`.

**Environment**:
- Grafana version: grafana_7.1.0~e836f2dfpre_amd64.deb
- Data source type & version: MySQL 10.3.22-MariaDB / Prometheus 2.7.1
- OS Grafana is installed on: Ubuntu 19.10
- User OS & Browser: Ubuntu 20.04 / Firefox 77.0.1
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
I see at least three different scenarios here, so I'll break down my investigation of the issue in the individual parts.

> For MySQL - Add a table panel with Table query of select now() as Time - adding date/time Unit override to time has no affect.

Confirmed, you have to provide the time as `unix_timestamp()` for date/time units to work. This is likely a bug.

> If I select Unit override YYYY-MM-DD HH:mm:ss the value is displayed as 08:48:39 (no date).
> If I select Unit override MM/DD/YYYY h:mm:ss a the value is displayed as 08:48:39 am (no date).

This seems to be intentional to some degree, there is a specific "today" format specified for these units. I'm not sure if this is intentional for the unit or just elsewhere where this unit is used. Maybe @torkelo could shed some light on that.

https://github.com/grafana/grafana/blob/4853770db3f209dd958bde2ff96f9b84133f62b9/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts#L341-L342

> If I enter a manual format such as DD/MM/YYYY it accepts that custom format but the displayed value goes back to being shown as 2020-06-18 08:48:39.
> If I enter a manual format such as HH:mm it does NOT seem to accept that custom format, so the unit dropdown value reverts back to YYYY-MM-DD HH:mm:ss and the displayed value is shown as 08:48:39.

It seems that formatting the `Time` field specifically only works when you're providing a valid time format, otherwise it quietly falls back to the default YYYY-MM-DD HH:mm:ss. Note that for custom time formats you'll have to prepend the custom format with `time:`, otherwise it'll be parsed as a suffix for the numeral that's in the field, so `DD/MM/YYYY` should be `time:DD/MM/YYYY`. You can see what happens by manipulating the `foo` unit for this query: `SELECT unix_timestamp() as time, unix_timestamp()*1000 as foo;` (use table format and table panel)

**Comment by therealcodlord** [comment]
O.K. So confirming that most of this issue is just a user-error type of issue where I assumed I could just enter custom formats like `DD/MM/YYYY HH:mm` but in actual fact I have to enter custom formats like `time:DD/MM/YYYY HH:mm`. I can confirm if I enter `time:DD/MM/YYYY HH:mm` then it works for Grafana & Prometheus data sources (even Prometheus Instant).

However, I would say this is a likely assumption by many users given:
a) The old table panel you could just enter custom formats like `DD/MM/YYYY HH:mm`
and
b) The pre-defined dropdown values are just shown as `YYYY-MM-DD HH:mm:ss` (so why would a user not think that's how they should enter custom formats).
and
c) The results of entering "invalid" custom formats is inconsistent across data sources and data source settings (like Prometheus instant).

Suggestion: Why not show the values in the dropddown (or at least have the resulting value) shown as `time:YYYY-MM-DD HH:mm:ss` so it's consistent and more obvious to users that's how to enter custom formats? And/or show an error/help text if a user enters an invalid format.
And/or have a tooltip explanation or link to relevant documentation on custom formats?


With MySQL, as you say if I select `unix_timestamp(now())` then I can format the result as expected using `time:YYYY-MM-DD HH:mm:ss` but the resulting value is a 1970 date not "now".

**Comment by torkelo** [comment]
The old table had a custom "time column" option, which makes the UI a bit easier. While the new table is just solving this via the unit option. 

But agree 100% we need to improve UI & docs for setting custom time formats 

> Suggestion: Why not show the pre-defined date/time formats in the dropddown (or at least have the resulting value) shown as time:YYYY-MM-DD HH:mm:ss so it's consistent and more obvious to users that's how to enter custom formats? And/or show an error/help text if a user enters an invalid format.
And/or have a tooltip explanation or link to relevant documentation on custom formats?

They are different, one is a custom value, the other is the predefined time units. 

Will open a new issue to improve the UX for custom units

**Comment by torkelo** [comment]
> With MySQL, as you say if I select unix_timestamp(now()) then I can format the result as expected using time:YYYY-MM-DD HH:mm:ss but the resulting value is a 1970 date not "now".

Might have to multiply it by 1000 then, as Grafana is working with millisecond epocs

**Comment by therealcodlord** [comment]
> Might have to multiply it by 1000 then, as Grafana is working with millisecond epocs

Confirmed, that works thanks I should have figured that from what @sakjur said!

**Comment by reuvygroovy** [comment]
Can you explain to me how to override a date value returned in Influx so that I could only see this format: "YYYY-MM-DD"?

**Comment by Husnain51** [comment]
Same issue here.... I am using grafana v8.1.2 cant override date/time :/  
![grafana issue](https://user-images.githubusercontent.com/66380322/133068053-b7079d11-f04f-4449-be1e-8a9c7b82bba9.PNG)

**Comment by tonmoyBoss** [comment]
Any update ,still input is not working Graphana 9

**Comment by reuvygroovy** [comment]
This works for me as mentioned here: https://community.grafana.com/t/custom-units-date-time/37792/3

Before format:
![image](https://user-images.githubusercontent.com/1325158/199408950-00580bf5-2e14-4ddd-b5eb-1edbc5ab31a8.png)

After:
![image](https://user-images.githubusercontent.com/1325158/199408914-d4b76549-9314-4b95-99b4-ffb399ad6c04.png)

**Comment by bertreyking** [comment]
> Might have to multiply it by 1000 then, as Grafana is working with millisecond epocs

Confirmed, that works thanks. 
- my datasource is prometheus, the execution result unit of query is seconds(s), and the grafana time unit is milliseconds(ms).
- grafana version: v9.3.14
