### ISSUE TITLE
Alert notifications in imported dashboards don't work

### ISSUE THREAD

**Issue by cameronattard** [grafana/grafana#25683]
**What happened**:

I am importing some dashboards from one Grafana installation to another. These dashboards contain alerts with alert notifications, like so:

```
        "notifications": [
          {
            "id": 2
          },
          {
            "id": 5
          }
        ]
```

I have ensured that on the new Grafana server, the alert notifications with these IDs match up identically.

However, after I import the dashboard and save it (to ensure alerts resume), alert notifications never trigger, even if the alert transitions to the alerting state. The UI shows the alert notifications configured for the alert, but the logs show that Grafana never even attempts to send the alerts.

I have noticed that when I remove the notification channels from the alert, save, re-add them, and save again, it begins working. I also noticed that after doing this, the dashboard JSON schema refers to the channels by UID instead of ID:

```
        "notifications": [
          {
            "uid": "HyK3ZqmGz"
          },
          {
            "uid": "qITWGqmMk"
          }
        ]
```

**What you expected to happen**:

Alert notifications in imported dashboards should work.

**How to reproduce it (as minimally and precisely as possible)**:

Export dashboard from source Grafana, import into target Grafana, save dashboard, and manipulate thresholds to ensure alert fires.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: Source: v5.3.1, Destination: v6.7.4
- OS Grafana is installed on: Source: Ubuntu 14.04, Destination: official Grafana docker image (Alpine?)

**Comment by sakjur** [comment]
Does it work if you set the `uid` in the source? Using per-instance ID:s is not recommended when provisioning even when you're aligning the instances.

**Comment by cameronattard** [comment]
Setting `uid` does indeed work. I've written a script to convert `id` to `uid` in the json model as a workaround.

**Comment by sakjur** [comment]
Great! I'll close this, as there is a workaround and I think the solution would've been that we would save the `uid` on the model (which we're already doing).
