### ISSUE TITLE
Grafana HA: Not able to export the existing sqlite3(grafana 6.7 version metadata) to mysql(Grafana 7.0.3 version)

### ISSUE THREAD

**Issue by raonelakurti** [grafana/grafana#25685]
Existing Configuration:
I have a grafana 6.7 is running on a compute instance with default configuration.(I have 40mb of data under grafana.db(sqlite3))

As a part of Grafana HA configuration, I have grafana is running on two instances and mysql is running on one instance.

1. I'm facing few a challenge to convert sqlite3 database into mysql. How can I export the sqlite3 data and import it into mysql instance?
2. Apart from updating [database] in defaults.ini with
type = mysql
host = 10.3.1.10:3306
name = grafanametrics
user = grafanaadmin
password = 'P@ssword1'

Does it require any other configuration to connect to mysql?
3. When I've tried converted sqlite3 database and import into mysql, grafana is failing to start.

Error:

ing"
t=2020-06-18T05:18:20+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2020-06-18T05:18:20+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2020-06-18T05:18:20+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2020-06-18T05:18:20+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2020-06-18T05:18:20+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2020-06-18T05:18:20+0000 lvl=info msg="App mode production" logger=settings
t=2020-06-18T05:18:20+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=10142
t=2020-06-18T05:18:20+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=mysql
t=2020-06-18T05:18:20+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2020-06-18T05:18:20+0000 lvl=info msg="Executing migration" logger=migrator id="Add index user.login/user.email"
t=2020-06-18T05:18:20+0000 lvl=eror msg="Executing migration failed" logger=migrator id="Add index user.login/user.email" error="Error 1170: BLOB/TEXT column 'login' used in key specification without a key length"
t=2020-06-18T05:18:20+0000 lvl=eror msg="Exec failed" logger=migrator error="Error 1170: BLOB/TEXT column 'login' used in key specification without a key length" sql="CREATE INDEX `IDX_user_login_email` ON `user` (`login`,`email`);"
t=2020-06-18T05:18:20+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: Failed to roll back transaction due to error: %!s(<nil>): Error 1364: Field 'id' doesn't have a default value"

**Comment by sakjur** [comment]
You have to start Grafana up towards an empty MySQL database first so that it can populate MySQL properly. After that there's an ongoing thread on our community site for migrating Grafana from SQLite to MySQL, see https://community.grafana.com/t/migrating-grafana-data-to-new-database/2454
