### ISSUE TITLE
Bug using Query Variables and Regex Operator with Stackdriver Datasource

### ISSUE THREAD

**Issue by allanwilson** [grafana/grafana#25684]
**What happened**:
No results.  Same query in Stackdriver (Cloud Monitoring) Works

The VM Instance names of a dataproc cluster is ${cluster_name}-(some postfix).

The cluster_name query variable allows me to select a cluster_name, however, using the cluster name in the query show below no results are returned.

RAW QUERY:
![image](https://user-images.githubusercontent.com/3739601/84981282-6832fb80-b0f1-11ea-840f-62153c9c30da.png)

**What you expected to happen**:
Expect to get cpu stats from the dataproc cluster

The time interval is also correct.  

Example output from Cloud Monitoring Dashboard
![image](https://user-images.githubusercontent.com/3739601/84982082-25722300-b0f3-11ea-9e49-70373310df72.png)

MQL Syntax, however, this is based on a string and not a query variable.

fetch gce_instance
| metric 'compute.googleapis.com/instance/cpu/utilization'
| filter
    (metric.instance_name
     =~ 'listening\\-data\\-task\\-2020\\-06\\-12\\-03\\-iunk7qczybspq.*')
| group_by 1m, [value_utilization_mean: mean(value.utilization)]
| every 1m
| group_by [], [value_utilization_mean_mean: mean(value_utilization_mean)]

**How to reproduce it (as minimally and precisely as possible)**:
Query Variable Definition
![image](https://user-images.githubusercontent.com/3739601/84980802-4422ea80-b0f0-11ea-9384-5b1bb9a52b2c.png)

Sample Values
![image](https://user-images.githubusercontent.com/3739601/84980973-af6cbc80-b0f0-11ea-8d85-572f27b686f8.png)

Query definition in Grafana
![image](https://user-images.githubusercontent.com/3739601/84981887-c6141300-b0f2-11ea-983f-8570059e8dbe.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version:  6.7.1
- Data source type & version:  Stackdriver Metrics
- OS Grafana is installed on:  Debian Linux
- User OS & Browser: macOS Mojave 10.14.6 and Chrome 83.0.4103.106 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The raw query looks correct, so the variable is interpolated. Can you see anything wrong with the raw query Grafana sends to Stackdriver?

**Comment by torkelo** [comment]
Can you copy paste the raw query? Your using a regex operator in the Filter expression, can you try to change this to an equality operator instead?

**Comment by allanwilson** [comment]
Hi Torkelo

The RAW Query output is really odd as it doesn't seems to update.

Current cluster_name variable: 
![image](https://user-images.githubusercontent.com/3739601/85030448-b4eef480-b13a-11ea-885b-5c662c3fca84.png)

Still using the =~ query
![image](https://user-images.githubusercontent.com/3739601/85030505-c1734d00-b13a-11ea-8998-47d1b231ee00.png)

RAW Query still shows from an older attempt:
![image](https://user-images.githubusercontent.com/3739601/85030537-ca641e80-b13a-11ea-8a6c-581c7234351b.png)

Query inspector shows the correct query and cluster_name value

![image](https://user-images.githubusercontent.com/3739601/85030642-eebffb00-b13a-11ea-80b3-384160ce4739.png)

Yet no results.

Switching to an Equality operator

![image](https://user-images.githubusercontent.com/3739601/85030752-12834100-b13b-11ea-8e44-ee81c74d54b2.png)

No results

If I switch this to a text variable the query will change to the starts_with( ) function.

I'll post that next....

**Comment by allanwilson** [comment]
One more screenshot before switching to a text string instead of a variable.

I expanded the Query Inspector to get both the Grafana Query and RAW Query

![image](https://user-images.githubusercontent.com/3739601/85031322-c1c01800-b13b-11ea-84bb-a6e3c04d4f43.png)

**Comment by torkelo** [comment]
So the query looks correct, but no response from Stackdriver, strange. Then feels like a strack driver api issue? or something wrong with the filters condition unrelated to the variable ?

**Comment by allanwilson** [comment]
This is for the same cluster and time period in Stackdriver

fetch gce_instance
| metric 'compute.googleapis.com/instance/cpu/utilization'
| filter
    (metric.instance_name
     =~
     'seed\\-to\\-artist\\-seed\\-nn\\-2020\\-06\\-17\\-09\\-kkdvzjijc3j3o.*')
| group_by 1m, [value_utilization_mean: mean(value.utilization)]
| every 1m
| group_by [], [value_utilization_mean_mean: mean(value_utilization_mean)]

![image](https://user-images.githubusercontent.com/3739601/85037560-c6d49580-b142-11ea-97de-0c3833cecfdb.png)

I have a few more things to gather still and upload.

**Comment by allanwilson** [comment]
Using a text box variable and inputting the cluster name.

=~ operator

Object
request:Object
url:"https://grafana.savagebeast.com/api/tsdb/query"
method:"POST"
body:"{"from":"1591889040242","to":"1592493840242","queries":[{"refId":"A","intervalMs":300000,"datasourceId":40,"metricType":"compute.googleapis.com/instance/cpu/utilization","crossSeriesReducer":"REDUCE_MEAN","perSeriesAligner":"ALIGN_INTERPOLATE","alignmentPeriod":"stackdriver-auto","groupBys":[],"view":"FULL","filters":["metric.label.instance_name","=~","seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o","AND"],"aliasBy":"","type":"timeSeriesQuery","projectName":"discovery-analytics-235"}]}"
response:Object
results:Object
A:Object
refId:"A"
meta:Object
alignmentPeriod:3600
groupBys:Array[0]
labels:Object
rawQuery:"aggregation.alignmentPeriod=%2B3600s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type%3D%22compute.googleapis.com%2Finstance%2Fcpu%2Futilization%22+metric.label.instance_name%3Dmonitoring.regex.full_match%28%22seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o%22%29&interval.endTime=2020-06-18T15%3A24%3A00Z&interval.startTime=2020-06-11T15%3A24%3A00Z&view=FULL"
series:null
tables:null
dataframes:null

Adding a ".*" to the end of the text

error:"{ "error": { "code": 400, "message": "Field filter had an invalid value of \"metric.type=\"compute.googleapis.com/instance/cpu/utilization\" metric.label.instance_name=monitoring.regex.full_match(\"seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o\\.\\*\")\": Could not parse filter \"metric.type=\\\"compute.googleapis.com/instance/cpu/utilization\\\" metric.label.instance_name=monitoring.regex.full_match(\\\"seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o\\\\.\\\\*\\\")\"; unsupported escape sequence in a string literal at line 1, column 1, token 'seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o\\.\\*'", "status": "INVALID_ARGUMENT" } } "
refId:"A"
meta:Object
series:null
tables:null
dataframes:null
message:"{ "error": { "code": 400, "message": "Field filter had an invalid value of \"metric.type=\"compute.googleapis.com/instance/cpu/utilization\" metric.label.instance_name=monitoring.regex.full_match(\"seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o\\.\\*\")\": Could not parse filter \"metric.type=\\\"compute.googleapis.com/instance/cpu/utilization\\\" metric.label.instance_name=monitoring.regex.full_match(\\\"seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o\\\\.\\\\*\\\")\"; unsupported escape sequence in a string literal at line 1, column 1, token 'seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o\\.\\*'", "status": "INVALID_ARGUMENT" } } "

Sample Instance Names:
seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o-m 
seed-to-artist-seed-nn-2020-06-17-09-kkdvzjijc3j3o-w-0

**Comment by allanwilson** [comment]
curl \
>   "https://monitoring.googleapis.com/v3/projects/${PROJECT_ID}/timeSeries?aggregation.alignmentPeriod=%2B3600s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type%3D%22compute.googleapis.com%2Finstance%2Fcpu%2Futilization%22+metric.label.instance_name%3Dmonitoring.regex.full_match%28%22hourly-listener-summar-2020-06-14-13-wustw5tygasdk%22%29&interval.endTime=2020-06-18T17%3A15%3A27Z&interval.startTime=2020-06-11T17%3A15%3A27Z&view=FULL" \
>   --header "Authorization: Bearer ${TOKEN}" \
>   --header 'Accept: application/json' \
>   --compressed
{
  "unit": "10^2.%"
}

**Comment by allanwilson** [comment]
This form works.  I had to append a  " .* " to the end of the cluster name string.
curl \
  "https://monitoring.googleapis.com/v3/projects/manalytics-241/timeSeries?aggregation.alignmentPeriod=%2B3600s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.perSeriesAligner=ALIGN_INTERPOLATE&filter=metric.type%3D%22compute.googleapis.com%2Finstance%2Fcpu%2Futilization%22+metric.label.instance_name%3Dmonitoring.regex.full_match%28%22hourly-listener-summar-2020-06-14-13-wustw5tygasdk.*%22%29&interval.endTime=2020-06-18T17%3A15%3A27Z&interval.startTime=2020-06-11T17%3A15%3A27Z&view=FULL" \
  --header "Authorization: Bearer ${TOKEN}" \
  --header 'Accept: application/json' \
  --compressed

**Comment by allanwilson** [comment]
> So the query looks correct, but no response from Stackdriver, strange. Then feels like a strack driver api issue? or something wrong with the filters condition unrelated to the variable ?

Actually it looks like Grafana needs to add the regex operators to the end of the query string '.*' otherwise  ~= is behaving like a = operator.

**Comment by torkelo** [comment]
You have to do that, Grafana cannot do that automatically, would break other usecases

**Comment by allanwilson** [comment]
Is there a recommended way to append the .* to a value that comes back for a query variable?

**Comment by xa4a** [comment]
I'm experiencing the same error message:

```
Field filter had an invalid value of "... metric.label.brand=monitoring.regex.full_match(\"foo\\.com\")"; 
unsupported escape sequence in a string literal at line 1, column 1, token 'foo\.com'
```

I'm using a variable that's of type query and is fetched from Google Cloud Monitoring label value. It looks like when a label value contains a dot (period ".") it's escaped with \\. to be considered a regexp. 

Google's filter, however, seem to be stricter and fails on the "foo\\.com" regexp with ` unsupported escape sequence`.

I can reproduce the error message by setting the filter explicitly to `metric.label.brand ~= foo\.com` which fails, but `foo.com` (a different regex) and `foo\\.com` both work. The latter is the expected behavior.
