### ISSUE TITLE
Extensibility for custom script tags & integrations

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2569]
We would like to see the ability to add in custom script tags into Grafana, so external integrations can be easily added. 

An example of an integration would be Intercom, which would allow real-time support and messages within a Grafana instance:
https://app.intercom.io/a/apps/nzwuctwv/add_integration/add_your_users

**Comment by torkelo** [comment]
I added this by adding support for google tag manager, google tag manager is created for exactly this purpose (manage custom tags for pages and tricker tracking codes and events).

**Comment by mattttt** [comment]
Nice! I totally forgot about that.
