### ISSUE TITLE
[Feature Request] Allow choosing multiple calculations to display in Stat Panel

### ISSUE THREAD

**Issue by CasualSuperman** [grafana/grafana#25696]
**What would you like to be added**: The Graph panel's legend has the option to display the Min, Max, Current, Avg, and Total for each metric. The Stat panel forces you to choose a single metric to display. I would like to have the ability to choose and display multiple aggregations in the Stat Panel.

**Why is this needed**: Currently this behavior _could_ be mimicked by duplicating the Stat panel for each type of aggregation, but this would display the same sparkline N times - having these in a combined panel could show a single sparkline. It would also avoid having to update multiple panels if the query changes.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
