### ISSUE TITLE
Add the "Basic" single color based display mode for bar guages in tables

### ISSUE THREAD

**Issue by rpthms** [grafana/grafana#25704]
**What would you like to be added**:
Currently the bar guages in table cells can only be displayed as the Retro LCD style or the Gradient style. Adding the option of the single colored "Basic" display mode, which is available for bar guage panels, would also be a good option.

**Why is this needed**:
The Basic display mode is IMO more helpful in recognizing the anomalies in a series. Values which are below or above a certain threshold will be displayed in a completely different color.

**Comment by jutley** [comment]
I recently ran into this issue as well. Gradient and Retro LCD displays show a bunch of colors, and it takes more work to recognize which color we should actually pay attention to. The Basic display is the best in my opinion, because it makes the color (and associated meaning) very obvious.
