### ISSUE TITLE
armv6/armhf: grafana fails to start: segmentation fault

### ISSUE THREAD

**Issue by geigi** [grafana/grafana#25719]
**What happened**:
Grafana doesn't start on a Raspberry Pi Zero.
It immediately fails to start with a *segmentation fault* message.

**What you expected to happen**:
Grafana starting normally.

**How to reproduce it (as minimally and precisely as possible)**:
First I tried to run grafana via the official docker container on Raspbian Buster. But it didn't start without any message whatsoever. 
Next I tried the official grafana Debian repository and installed grafana 7.0.3. Starting it caused a *segmentation fault* message immediately. I then tried 7.0.0 from the repository which produced the same error.
Finally I tried v.6.7.4 from the repository, which also failed to start but with the message *Illegal instruction*.

**Anything else we need to know?**:
This is the armv6/armhf platform. Arm64 is working fine on a Raspberry Pi 4.
If there is anything I can help you with I'm glad to do so :) 

**Environment**:
- Grafana version: 7.0.3, 7.0.0, 6.7.4
- Data source type & version: -
- OS Grafana is installed on: Raspbian (now Raspberry Pi OS)
- User OS & Browser: -
- Grafana plugins: -
- Others: armv6/armhf

**Comment by aknuds1** [comment]
Do you see a stacktrace from the segfault?

**Comment by geigi** [comment]
Not in stdout or stderr. Is there a cli option I need to use or can I find the stacktrace elsewhere?

**Comment by aknuds1** [comment]
I'm actually not sure. When I have segfaults in Go, I always get a stacktrace. You can try via the catchsegv tool though, if you are able to: `catchsegv grafana-server`.

**Comment by aknuds1** [comment]
Can you paste the output you get in the terminal after running Grafana (and it then segfaults)?

**Comment by aknuds1** [comment]
What's the output of the following command? 

```
ldd $(which grafana-server)
```

**Comment by marefr** [comment]
Regarding docker and ARMv6 it's currently not supported, see [feature request](https://github.com/grafana/grafana/issues/16689). Have you followed the instruction for ARMv6 at https://grafana.com/grafana/download?platform=arm?

**Comment by geigi** [comment]
> Regarding docker and ARMv6 it's currently not supported
I missed that, thanks :)

Just noticed my error while reading the instructions again: I installed the wrong package: **grafana** (armv7) instead of **grafana-rpi** (armv6) from the repository... 

I'm curious: Are two different packages necessary because armv6 and armv7 both report armhf as architecture? Could the installation of **grafana** on armv6 be prevented?

Anyway I'm happy that grafana-rpi is also provided in the repository! Thanks for your help :)

**Comment by aknuds1** [comment]
I don't know the reason for the package naming.

**Comment by marefr** [comment]
Maybe @xlson can bring some context to this?

**Comment by xlson** [comment]
The reason for the name is that the armv7 arch is the same as the one for armv6, that causes a conflict. An alternative solution to the different name would be a separate repo for armv6. Not sure if there is any other options that would simplify things.

**Comment by geigi** [comment]
Thanks for the clarification :)
