### ISSUE TITLE
Return TimeRange on Variable Refresh, no matter Refresh mode.

### ISSUE THREAD

**Issue by AlexanderBrandborg** [grafana/grafana#25715]
**What would you like to be added**:
As a datasource plugin developer, whose plugin is not shipped with Grafana, I need to have Grafana send me the current time range, when I enter `metricFindQuery` during a variable refresh, no matter the refresh type. 

Right now the timeRange only appears in the `options` object  if the Refresh mode is `On time range change`. Otherwise, for the other modes, it is set to undefined.

I believe that `updateQueryVariableOptions` in `public/app/features/variables/query/actions.ts` controls this behavior, and it is only a matter of removing an if-check that keeps the timeRange undefined for the other modes.

**Why is this needed**:
When I enter `metricFindQuery` I need to perform a query via HTTP towards my data service to get my variable values, which always needs a timeRange. As my plugin is external to Grafana I don't have access to `timeSrv` and thus I cannot query for the timeRange myself. I am dependent upon the timeRange returned to me in the `options` object, regardless of which refresh mode has been selected.

If there is a reason why timeRange needs to be undefined in some cases, I'd like to know. Otherwise this seems like a rather simple fix :- )
I can submit it as a PR, I just need to know if that if appropriate.

**Comment by sakjur** [comment]
🤔 If the variable doesn't update or only updates on dashboard load and the user then expands the time range, your variable wouldn't update accordingly. If your variable is sensitive to the time range shown (such as listing "currently living pods in Kubernetes" or something like that) you'd get strange behavior when you go back in time if you depend on the original time range.

However, that's a logical problem and not necessarily a practical one. I'm not sure if there's a particular problem with setting the time range at all times. @mckn do you know?

**Comment by torkelo** [comment]
Can you open a PR with this change?

**Comment by mckn** [comment]
@AlexanderBrandborg is this still an issue or is it resolved?

**Comment by AlexanderBrandborg** [comment]
@mckn I have found a workaround on my end, but it is not pretty.
So this isn't urgent, but I'd like to see the change in future versions of Grafana :- )

**Comment by boiss-dev** [comment]
hey hey,
@AlexanderBrandborg Could you maybe explain your workaround please ?

thanks

**Comment by AlexanderBrandborg** [comment]
> hey hey,
> @AlexanderBrandborg Could you maybe explain your workaround please ?
> 
> thanks

Hey, sorry for a late reply.
It's been a bit since I implemented this, but it's part of an open source project, so you can find it at: https://github.com/humio/humio2grafana/blob/master/src/MetricFindQuery.ts

Note that I'm rather shaky on this solution, it seems to be working through manual testing, but I wouldn't make it load bearing.

**Comment by torkelo** [comment]
think this is fixed
