### ISSUE TITLE
Minimum refresh interval blocks dashboard from importing using api

### ISSUE THREAD

**Issue by Kirchen99** [grafana/grafana#25717]
**What happened**:
settings GF_DASHBOARDS_MIN_REFRESH_INTERVAL=30s blocks importing dashboards using api
`POST /api/dashboards/db`

**What you expected to happen**:
setting minimum refresh interval to 30s

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Grafana 7.0.3 with GF_DASHBOARDS_MIN_REFRESH_INTERVAL=30s, try to import a Dashboard with less interval

`docker run -d -p 3000:3000 -e GF_DASHBOARDS_MIN_REFRESH_INTERVAL=30s  grafana/grafana:7.0.3`
dashboard.json:
```
{
  "dashboard": {
    "id": null,
    "uid": null,
    "title": "Production Overview",
    "tags": [ "templated" ],
    "timezone": "browser",
    "schemaVersion": 16,
    "version": 0,
    "refresh": "25s"
  },
  "folderId": 0,
  "overwrite": false
}
```
```
curl -i -X POST -H "Content-Type: application/json" http://admin:admin@localhost:3000/api/dashboards/db --data-binary "@dashboard.json"
HTTP/1.1 400 Bad Request
Cache-Control: no-cache
Content-Type: application/json
Expires: -1
Pragma: no-cache
X-Frame-Options: deny
Date: Fri, 19 Jun 2020 14:43:06 GMT
Content-Length: 51

{"message":"Dashboard refresh interval is too low"}
```

**Anything else we need to know?**:
Logs: 
```t=2020-06-19T13:35:38+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/db status=400 remote_addr=127.0.0.1 time_ms=37 size=51 referer=```

Response from Grafana Api:
```{"err":"Unexpected status code returned from Grafana API (got: 400, expected: 200, msg:{\"message\":\"Dashboard refresh interval is too low\"})"}```

related to this one: https://github.com/grafana/grafana/issues/23099
**Environment**:
- Grafana version: 7.0.3
- OS Grafana is installed on: K8s 1.15
- User OS & Browser: Chrome

**Comment by Kirchen99** [comment]
I saw the code to change refresh interval for provisioned dashboard to minimum refresh interval. Is it not desired also for imported dashboard?

**Comment by Kirchen99** [comment]
Why do we want Grafana not to reject dashboard via api:

Our developers make dashboards and upload them in Git. Then a pipeline is triggered and it uploads the dashboards into a kubernetes cluster as configMap. In the cluter there is a controller, which watches the configMaps and post the dashboards into Grafana via api. 

1. The developers have no contact with the api. They don't know why is a valid dashboard json being rejected by Grafana and they get totally crazy.
2. The developers are not sensitive with refresh interval. 5s and 30s are same for them. They just want to see the dashboard in Grafana.

So in our situation, we don't want json be rejected by Grafana via api.

**Comment by sakjur** [comment]
> The developers have no contact with the api. They don't know why is a valid dashboard json being rejected by Grafana and they get totally crazy.

Is there no way for you to share the result of their pipelines with the developers? We can't fix every possible issue where getting the response from the API would make it easier to debug.

> The developers are not sensitive with refresh interval. 5s and 30s are same for them. They just want to see the dashboard in Grafana.

While that makes sense for your developers, it doesn't necessarily make sense for every developer. And while your current nuisance is the refresh interval, there might be other validations on the API in the future that would end up causing you the same problem all over again. Making sure your developers have access to logs relevant to debug their CI/CD jobs is the only viable long term solution to this problem.

**Comment by Kirchen99** [comment]
I agree with you thant we can't fix every possible issue where getting the response from the API would make it easier to debug.

But why should it be an issue only for api? 

It is not an issue for importing https://github.com/grafana/grafana/pull/23959
and it is not an issue for provisioned dashboards: https://github.com/grafana/grafana/blob/3b383149db7408b1669159ad2edad9c141498ece/pkg/services/dashboards/dashboard_service.go#L220

For consistency shouldn't Grafana reject all dashboards with lower refresh interval or change the refresh interval to minimum refresh interval and accept them?

**Comment by sakjur** [comment]
Ah, gotcha. That makes sense then. I disagree with our solution for the provisioning as well here, but you're correct that the API should mirror that behavior. I'll reopen and assign this to the appropriate team.

**Comment by sakjur** [comment]
If someone wants to beat us to fixing this, https://github.com/grafana/grafana/issues/25717#issuecomment-646660719 pretty much describes what should be done in a PR. (cc @marefr)

**Comment by torkelo** [comment]
could be fixed by https://github.com/grafana/grafana/issues/22579

**Comment by sakjur** [comment]
@torkelo Would that solve the discrepancy between provisioning and the API?

**Comment by torkelo** [comment]
no, but would make it possible to validate the json externally using the tool in a CI build for example
