### ISSUE TITLE
Incorrect escaping of regex in annotations

### ISSUE THREAD

**Issue by lukhas** [grafana/grafana#25712]
**What happened**:

We are using an Annotation query on an `events` db to get more context about a given host (or hosts) in a dashboard. When using a regex in the Variable (like `*-front`), the Annotation query using that variable gets incorrectly escaped by Grafana, while it is handled correctly in the graph panel query (ie. the regexp gets passed to InfluxDB).

**What you expected to happen**:

Grafana should not escape the annotation query.

**How to reproduce it (as minimally and precisely as possible)**:

Using Grafana with Influxdb as data and annotation:
Annotation query: `SELECT text FROM backup  WHERE host =~ /$host/ AND $timeFilter order by time asc`.

Our dashboard URLs look like this: `https://(...)/serveurs?orgId=1&var-host=hva[l]a` for the screenshot and logs below, can also reproduce with * or any special character.

The dashboard graphs all correctly list all the hosts matching that regexp, but the annotations are empty, see https://imgur.com/a/4rYyre5.

The relevant logs, with the regex in the query:

```
Jun 19 12:20:22 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:22 +0200] "GET /query?db=events&epoch=ms&q=SELECT+text+FROM+backup++WHERE+host+%3D~+%2Fhva%5C%2Aa%2F+AND+time+%3E%3D+now%28%29+-+12h+order+by+time+asc HTTP/1.1" 200 57 "-" "Grafana/7.0.3" 7ba31d40-b216-11ea-8c42-b083fec27838 1207
Jun 19 12:20:22 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:22 +0200] "GET /query?db=events&epoch=ms&q=SELECT+message+FROM+kernel_errors++WHERE+host+%3D~+%2Fhva%5C%2Aa%2F+AND+time+%3E%3D+now%28%29+-+12h+order+by+time+asc HTTP/1.1" 200 57 "-" "Grafana/7.0.3" 7ba4f09a-b216-11ea-8c43-b083fec27838 870
Jun 19 12:20:22 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:22 +0200] "GET /query?db=telegraf&epoch=ms&q=SELECT+100-mean%28%22usage_idle%22%29+AS+%22non-idle%22+FROM+%22cpu%22+WHERE+%28%22host%22+%3D~+%2Fhva%2Aa%2F%29+AND+time+%3E%3D+now%28%29+-+12h+GROUP+BY+time%281m%29%2C+%22host%22 HTTP/1.1" 200 8369 "-" "Grafana/7.0.3" 7ba91e41-b216-11ea-8c45-b083fec27838 14524
```

Note the escaping of the variable handled differently for both queries. It looks like it's escaped once more in the annotation query (`db=events`).

The same logs, without the regex:

```
Jun 19 12:20:31 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:30 +0200] "GET /query?db=telegraf&epoch=ms&q=SHOW+TAG+VALUES+WITH+KEY+%3D+%22host%22 HTTP/1.1" 200 15609 "-" "Grafana/7.0.3" 80e2504e-b216-11ea-8e5b-b083fec27838 71900
Jun 19 12:20:31 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:31 +0200] "GET /query?db=events&epoch=ms&q=SELECT+text+FROM+backup++WHERE+host+%3D~+%2Fhvala%2F+AND+time+%3E%3D+now%28%29+-+12h+order+by+time+asc HTTP/1.1" 200 176 "-" "Grafana/7.0.3" 813266bd-b216-11ea-8e77-b083fec27838 1352
Jun 19 12:20:31 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:31 +0200] "GET /query?db=events&epoch=ms&q=SELECT+message+FROM+kernel_errors++WHERE+host+%3D~+%2Fhvala%2F+AND+time+%3E%3D+now%28%29+-+12h+order+by+time+asc HTTP/1.1" 200 57 "-" "Grafana/7.0.3" 81348860-b216-11ea-8e78-b083fec27838 811
Jun 19 12:20:31 mordu influxd[4769]: [httpd] IP1, IP2, IP3,IP4 - grafana [19/Jun/2020:12:20:31 +0200] "GET /query?db=telegraf&epoch=ms&q=SELECT+100-mean%28%22usage_idle%22%29+AS+%22non-idle%22+FROM+%22cpu%22+WHERE+%28%22host%22+%3D~+%2Fhvala%2F%29+AND+time+%3E%3D+now%28%29+-+12h+GROUP+BY+time%281m%29%2C+%22host%22 HTTP/1.1" 200 8373 "-" "Grafana/7.0.3" 813c62ab-b216-11ea-8e7a-b083fec27838 15015
```

**Environment**:
- Grafana version: 7.0.3 (same behavior on recent 6.x versions too)
- Data source type & version: Influxdb 1.7.8
- OS Grafana is installed on: Debian Stretch 64 bits
- User OS & Browser: Firefox and Chrome on Debian, probably not relevant.
- Grafana plugins: `grafana-image-renderer @ 2.0.0`

**Comment by marefr** [comment]
Using `SELECT text FROM backup WHERE host =~ /${host:raw}/ AND $timeFilter order by time asc` should work.

**Comment by lukhas** [comment]
Oh wow I had no idea this was possible, it solves my issue indeed. Where can I find the documentation for this?

**Comment by marefr** [comment]
https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#raw

**Comment by lukhas** [comment]
In that case I would suggest linking that from the Annotations.

The issue can be closed as far as I'm concerned, thanks!

**Comment by justinsmalley** [comment]
Ran into this issue today and the workaround fixed it for me. As far as I'm concerned it's still a bug however since the raw format option is only required in annotations, not in a panel.
