### ISSUE TITLE
Long queue of requests when data loading time is longer than auto-refresh time

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#25713]
**What happened**:
When the data needs more time to load than the auto-refresh interval is set to, Grafana is making long queue of requests to database without cancelling old requests. Even when the old request finishes and returns data, the data is not being showed in the panel, because it is waiting for the response from the newest request.
With long requests queue page may freeze for a couple of minutes and the only solution is to refresh the page.
![1](https://user-images.githubusercontent.com/19311511/85131727-a89c9180-b237-11ea-83f2-e025b22be83d.jpg)
![2](https://user-images.githubusercontent.com/19311511/85131729-aa665500-b237-11ea-95c1-625663df2feb.jpg)
![3](https://user-images.githubusercontent.com/19311511/85131790-c964e700-b237-11ea-88cf-8335abbbc78e.jpg)

**What you expected to happen**:
The best option would be to set timeout time (for example 1 minute). If the data loading is not completed before next auto-refresh, it won't make another auto-refresh and wait for the timeout. After the timeout it should cancel old requests so it won't make long queue.
Another solution would be to add refresh interval per panel as described in #3514

**How to reproduce it (as minimally and precisely as possible)**:
Make a few panels in which the request times are longer than auto-refresh time.

**Environment**:
Grafana version: 7.0.3
Data source type & version: Influxdb 1.7.9
OS Grafana is installed on: Debian 4.9
User OS & Browser: Opera Gx

**Comment by torkelo** [comment]
To fix this we need to change influx (and other data sources) to use the new fetch function (Observable) on backendSrv
