### ISSUE TITLE
Panels as plugins.

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#2572]
Hello! I want to add custom panel for Zabbix datasource and have some problems. In Grafana 2 panels described in file `public/app/components/settings.js`:
```
...
var defaults = {
      datasources                   : {},
      window_title_prefix           : 'Grafana - ',
      panels                        : {
        'graph':      { path: 'panels/graph',      name: 'Graph' },
        'singlestat': { path: 'panels/singlestat', name: 'Single stat' },
        'text':       { path: 'panels/text',       name: 'Text' },
        'dashlist':   { path: 'panels/dashlist',   name: 'Dashboard list' },
        'triggers':   { path: 'panels/triggers',   name: 'Zabbix triggers' },
      },
...
```
I was successfully added new panel with desired behavior, but to use it I need to rebuild Grafana frontend from sources. It may be hard for end users. Is it possible to use panels as plugins (like datasources)? It seems it was possible in grafana 1.9.

**Comment by torkelo** [comment]
yes, when I built the data source plugin system I intended to extend it to cover panels as well, just havent had time.

**Comment by alexanderzobnin** [comment]
Thanks! This is good news!

**Comment by vsonone** [comment]
@alexanderzobnin, Can you please share some sample/guidelines on adding a custom panel. We have a custom panel that we added in grafana 1.8, and we have to add the same feature in grafana, 2.1.

**Comment by vsonone** [comment]
@torkelo Do you know when the custom panel feature like the one in 1.8 will be available in grafana 2.x

**Comment by alexanderzobnin** [comment]
@vsonone I will try to share this info during a month, when I complete my panel.

**Comment by balda** [comment]
@alexanderzobnin impatient to read!

**Comment by bergquist** [comment]
Support for panels are now available in master but lack documentation.

**Comment by bergquist** [comment]
#3608
