### ISSUE TITLE
Grafana 7.0.3 error 1406: Data too long for column 'basic_auth_password' at row 1"

### ISSUE THREAD

**Issue by RuyCury** [grafana/grafana#25724]
**What happened**:
After changing the secret that contains the data from grafana.ini, to the mysql database information and restarting the pod, he returned the log error "t=2020-06-19T18:10:17+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: Error 1406: Data too long for column 'basic_auth_password' at row 1"" 

**What you expected to happen**:
That after changing the secret that contains the data from grafana.ini, to the information in the mysql database, the pod would start normally.

**How to reproduce it (as minimally and precisely as possible)**:
Insert the mysql database information into the secret that contains the data from grafana.ini, restart the pod, wait for the pod to return an error, look in the log for the error message "t=2020-06-19T18:10:17+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Datasource provisioning error: Error 1406: Data too long for column 'basic_auth_password' at row 1""

**Anything else we need to know?**:
This grafana is a custom grafana, which was created in a custom namespace within openshift. This is not the standard grafana that comes with installing openshift.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: MySql 8.0.17
- OS Grafana is installed on: Openshift 3.11
- User OS & Browser: Windows 10 - Firefox 68.9.0
- Grafana plugins: 
- Others:

**Comment by marefr** [comment]
Please include provisioning file you're using that causes this, replace sensitive information, if any.

**Comment by RuyCury** [comment]
marefr,

Thanks for the reply, below is the yaml and the secret with grafana.ini.

The creation yaml:
`apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: '19'
    kubectl.kubernetes.io/last-applied-configuration: >
      {"apiVersion":"extensions/v1beta1","kind":"Deployment","metadata":{"annotations":{},"creationTimestamp":null,"generation":1,"labels":{"app":"grafana"},"name":"grafana","namespace":"monitoring"},"spec":{"progressDeadlineSeconds":600,"replicas":0,"revisionHistoryLimit":10,"selector":{"matchLabels":{"app":"grafana"}},"strategy":{"rollingUpdate":{"maxSurge":1,"maxUnavailable":1},"type":"RollingUpdate"},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"grafana"},"name":"grafana"},"spec":{"containers":[{"args":["-config=/etc/grafana/grafana.ini"],"image":"docker.io/grafana/grafana:latest-ubuntu","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/","port":3000,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":1},"name":"grafana","ports":[{"containerPort":3000,"name":"grafana-http","protocol":"TCP"}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/api/health","port":3000,"scheme":"HTTP"},"initialDelaySeconds":30,"periodSeconds":10,"successThreshold":1,"timeoutSeconds":7},"resources":{},"terminationMessagePath":"/dev/termination-log","terminationMessagePolicy":"File","volumeMounts":[{"mountPath":"/etc/grafana","name":"grafana-config"},{"mountPath":"/grafana-dashboard-definitions/2/grafana-adiqbh-pagamentos","name":"grafana-dashboard-pagamentos"},{"mountPath":"/grafana-dashboard-definitions/0/grafana-custom","name":"grafana-dashboard-grafana-custom"},{"mountPath":"/grafana-dashboard-definitions/0/prometheus-app","name":"grafana-dashboard-prometheus-app"},{"mountPath":"/grafana-dashboard-definitions/0/prometheus-openshift","name":"grafana-dashboard-prometheus-openshift"},{"mountPath":"/grafana-dashboard-definitions/1/cluster-load","name":"grafana-dashboard-cluster-load"},{"mountPath":"/grafana-dashboard-definitions/1/cluster-storage","name":"grafana-dashboard-cluster-storage"},{"mountPath":"/grafana-dashboard-definitions/1/cluster-status","name":"grafana-dashboard-cluster-status"},{"mountPath":"/var/lib/grafana","name":"grafana-storage"},{"mountPath":"/etc/grafana/provisioning/dashboards","name":"grafana-dashboards"},{"mountPath":"/grafana-dashboard-definitions/0/k8s-cluster-rsrc-use","name":"grafana-dashboard-k8s-cluster-rsrc-use"},{"mountPath":"/grafana-dashboard-definitions/0/k8s-node-rsrc-use","name":"grafana-dashboard-k8s-node-rsrc-use"},{"mountPath":"/grafana-dashboard-definitions/0/k8s-resources-cluster","name":"grafana-dashboard-k8s-resources-cluster"},{"mountPath":"/grafana-dashboard-definitions/0/k8s-resources-namespace","name":"grafana-dashboard-k8s-resources-namespace"},{"mountPath":"/grafana-dashboard-definitions/0/k8s-resources-pod","name":"grafana-dashboard-k8s-resources-pod"},{"mountPath":"/grafana-dashboard-definitions/0/master-api","name":"grafana-dashboard-master-api"},{"mountPath":"/grafana-dashboard-definitions/0/pods","name":"grafana-dashboard-pods"},{"mountPath":"/grafana-dashboard-definitions/0/traffic","name":"grafana-dashboard-traffic"},{"mountPath":"/grafana-dashboard-definitions/0/etcd","name":"grafana-dashboard-etcd"},{"mountPath":"/grafana-dashboard-definitions/0/elasticsearch","name":"grafana-dashboard-elasticsearch"},{"mountPath":"/grafana-dashboard-definitions/0/fluentd","name":"grafana-dashboard-fluentd"},{"mountPath":"/grafana-dashboard-definitions/0/goldpinger","name":"grafana-dashboard-goldpinger"},{"mountPath":"/grafana-dashboard-definitions/0/haproxy","name":"grafana-dashboard-haproxy"},{"mountPath":"/grafana-dashboard-definitions/0/jenkins","name":"grafana-dashboard-jenkins"},{"mountPath":"/grafana-dashboard-definitions/0/capacity","name":"grafana-dashboard-capacity"},{"mountPath":"/etc/grafana/provisioning/datasources","name":"volume-dhjs5","readOnly":true},{"mountPath":"/etc/grafana/ldap","name":"grafana-ldap-config","readOnly":true}]}],"restartPolicy":"Always","schedulerName":"default-scheduler","securityContext":{},"serviceAccount":"grafana","serviceAccountName":"grafana","terminationGracePeriodSeconds":30,"volumes":[{"name":"grafana-config","secret":{"defaultMode":420,"secretName":"grafana-config"}},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-pagamentos"},"name":"grafana-dashboard-pagamentos"},{"name":"secrets","secret":{"defaultMode":420,"secretName":"grafana-proxy"}},{"name":"grafana-tls","secret":{"defaultMode":420,"secretName":"grafana-tls"}},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-grafana-custom"},"name":"grafana-dashboard-grafana-custom"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-prometheus-app"},"name":"grafana-dashboard-prometheus-app"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-prometheus-openshift"},"name":"grafana-dashboard-prometheus-openshift"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-cluster-load"},"name":"grafana-dashboard-cluster-load"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-cluster-storage"},"name":"grafana-dashboard-cluster-storage"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-cluster-status"},"name":"grafana-dashboard-cluster-status"},{"name":"grafana-storage","persistentVolumeClaim":{"claimName":"grafana-storage"}},{"configMap":{"defaultMode":420,"name":"grafana-dashboards"},"name":"grafana-dashboards"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-k8s-cluster-rsrc-use"},"name":"grafana-dashboard-k8s-cluster-rsrc-use"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-k8s-node-rsrc-use"},"name":"grafana-dashboard-k8s-node-rsrc-use"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-k8s-resources-cluster"},"name":"grafana-dashboard-k8s-resources-cluster"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-k8s-resources-namespace"},"name":"grafana-dashboard-k8s-resources-namespace"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-k8s-resources-pod"},"name":"grafana-dashboard-k8s-resources-pod"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-master-api"},"name":"grafana-dashboard-master-api"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-pods"},"name":"grafana-dashboard-pods"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-traffic"},"name":"grafana-dashboard-traffic"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-etcd"},"name":"grafana-dashboard-etcd"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-elasticsearch"},"name":"grafana-dashboard-elasticsearch"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-fluentd"},"name":"grafana-dashboard-fluentd"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-goldpinger"},"name":"grafana-dashboard-goldpinger"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-haproxy"},"name":"grafana-dashboard-haproxy"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-jenkins"},"name":"grafana-dashboard-jenkins"},{"configMap":{"defaultMode":420,"name":"grafana-dashboard-capacity"},"name":"grafana-dashboard-capacity"},{"name":"volume-dhjs5","secret":{"defaultMode":420,"secretName":"grafana-datasources"}},{"name":"grafana-ldap-config","secret":{"defaultMode":420,"secretName":"grafana-ldap"}}]}}},"status":{}}
  creationTimestamp: '2019-12-17T22:14:56Z'
  generation: 47
  labels:
    app: grafana
  name: grafana
  namespace: monitoring
  resourceVersion: '205084454'
  selfLink: /apis/apps/v1/namespaces/monitoring/deployments/grafana
  uid: a886ae55-211a-11ea-ace9-005056a4ae15
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: grafana
      name: grafana
    spec:
      containers:
        - args:
            - '-config=/etc/grafana/grafana.ini'
          env:
            - name: GF_PATHS_CONFIG
              value: /etc/grafana/grafana.ini
          image: 'docker.io/grafana/grafana:7.0.3-ubuntu'
          imagePullPolicy: IfNotPresent
          name: grafana
          ports:
            - containerPort: 3000
              name: grafana-http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /api/health
              port: 3000
              scheme: HTTP
            initialDelaySeconds: 3
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 7
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /etc/grafana
              name: grafana-config
            - mountPath: /grafana-dashboard-definitions/0/grafana-custom
              name: grafana-dashboard-grafana-custom
            - mountPath: /grafana-dashboard-definitions/0/prometheus-app
              name: grafana-dashboard-prometheus-app
            - mountPath: /grafana-dashboard-definitions/0/prometheus-openshift
              name: grafana-dashboard-prometheus-openshift
            - mountPath: /grafana-dashboard-definitions/1/cluster-load
              name: grafana-dashboard-cluster-load
            - mountPath: /grafana-dashboard-definitions/1/cluster-storage
              name: grafana-dashboard-cluster-storage
            - mountPath: /grafana-dashboard-definitions/1/cluster-status
              name: grafana-dashboard-cluster-status
            - mountPath: /var/lib/grafana
              name: grafana-storage
            - mountPath: /etc/grafana/provisioning/dashboards
              name: grafana-dashboards
            - mountPath: /grafana-dashboard-definitions/0/k8s-cluster-rsrc-use
              name: grafana-dashboard-k8s-cluster-rsrc-use
            - mountPath: /grafana-dashboard-definitions/0/k8s-node-rsrc-use
              name: grafana-dashboard-k8s-node-rsrc-use
            - mountPath: /grafana-dashboard-definitions/0/k8s-resources-cluster
              name: grafana-dashboard-k8s-resources-cluster
            - mountPath: /grafana-dashboard-definitions/0/k8s-resources-namespace
              name: grafana-dashboard-k8s-resources-namespace
            - mountPath: /grafana-dashboard-definitions/0/k8s-resources-pod
              name: grafana-dashboard-k8s-resources-pod
            - mountPath: /grafana-dashboard-definitions/0/master-api
              name: grafana-dashboard-master-api
            - mountPath: /grafana-dashboard-definitions/0/pods
              name: grafana-dashboard-pods
            - mountPath: /grafana-dashboard-definitions/0/traffic
              name: grafana-dashboard-traffic
            - mountPath: /grafana-dashboard-definitions/0/etcd
              name: grafana-dashboard-etcd
            - mountPath: /grafana-dashboard-definitions/0/elasticsearch
              name: grafana-dashboard-elasticsearch
            - mountPath: /grafana-dashboard-definitions/0/fluentd
              name: grafana-dashboard-fluentd
            - mountPath: /grafana-dashboard-definitions/0/goldpinger
              name: grafana-dashboard-goldpinger
            - mountPath: /grafana-dashboard-definitions/0/haproxy
              name: grafana-dashboard-haproxy
            - mountPath: /grafana-dashboard-definitions/0/jenkins
              name: grafana-dashboard-jenkins
            - mountPath: /grafana-dashboard-definitions/0/capacity
              name: grafana-dashboard-capacity
            - mountPath: /etc/grafana/provisioning/datasources
              name: volume-dhjs5
              readOnly: true
            - mountPath: /etc/grafana/ldap
              name: grafana-ldap-config
              readOnly: true
            - mountPath: /grafana-dashboard-definitions/3
              name: grafana-dashboard-cpsqa-h35s7
              readOnly: true
            - mountPath: /grafana-dashboard-definitions/3/cpshomolog
              name: grafana-dashboard-cpshomolog-kmjn7
              readOnly: true
            - mountPath: /grafana-dashboard-definitions/3/cpsprod
              name: grafana-dashboard-cpsprod-mkpxu
              readOnly: true
            - mountPath: /grafana-dashboard-definitions/2/grafana-adiqbh-pagamentosdebito
              name: grafana-dashboard-pagamentosdebito-71l87
              readOnly: true
            - mountPath: /grafana-dashboard-definitions/2/grafana-adiqbh-paineldebitohml
              name: grafana-dashboard-paineldebitohml-53niw
              readOnly: true
            - mountPath: >-
                /grafana-dashboard-definitions/2/grafana-adiqbh-consultatransporte-prd
              name: grafana-dashboard-consultatransporte-prd-f4nbr
              readOnly: true
            - mountPath: /grafana-dashboard-definitions/2/grafana-adiqbh-pagamentos
              name: grafana-dashboard-pagamentos-pn4qn
              readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: grafana
      serviceAccountName: grafana
      terminationGracePeriodSeconds: 30
      volumes:
        - name: grafana-config
          secret:
            defaultMode: 420
            secretName: grafana-config
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-pagamentos
          name: grafana-dashboard-pagamentos
        - name: secrets
          secret:
            defaultMode: 420
            secretName: grafana-proxy
        - name: grafana-tls
          secret:
            defaultMode: 420
            secretName: grafana-tls
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-grafana-custom
          name: grafana-dashboard-grafana-custom
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-prometheus-app
          name: grafana-dashboard-prometheus-app
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-prometheus-openshift
          name: grafana-dashboard-prometheus-openshift
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-cluster-load
          name: grafana-dashboard-cluster-load
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-cluster-storage
          name: grafana-dashboard-cluster-storage
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-cluster-status
          name: grafana-dashboard-cluster-status
        - emptyDir: {}
          name: grafana-storage
        - configMap:
            defaultMode: 420
            name: grafana-dashboards
          name: grafana-dashboards
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-k8s-cluster-rsrc-use
          name: grafana-dashboard-k8s-cluster-rsrc-use
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-k8s-node-rsrc-use
          name: grafana-dashboard-k8s-node-rsrc-use
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-k8s-resources-cluster
          name: grafana-dashboard-k8s-resources-cluster
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-k8s-resources-namespace
          name: grafana-dashboard-k8s-resources-namespace
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-k8s-resources-pod
          name: grafana-dashboard-k8s-resources-pod
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-master-api
          name: grafana-dashboard-master-api
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-pods
          name: grafana-dashboard-pods
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-traffic
          name: grafana-dashboard-traffic
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-etcd
          name: grafana-dashboard-etcd
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-elasticsearch
          name: grafana-dashboard-elasticsearch
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-fluentd
          name: grafana-dashboard-fluentd
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-goldpinger
          name: grafana-dashboard-goldpinger
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-haproxy
          name: grafana-dashboard-haproxy
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-jenkins
          name: grafana-dashboard-jenkins
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-capacity
          name: grafana-dashboard-capacity
        - name: volume-dhjs5
          secret:
            defaultMode: 420
            secretName: grafana-datasources
        - name: grafana-ldap-config
          secret:
            defaultMode: 420
            secretName: grafana-ldap
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-cpsqa
          name: grafana-dashboard-cpsqa-h35s7
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-cpshomolog
          name: grafana-dashboard-cpshomolog-kmjn7
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-cpsprod
          name: grafana-dashboard-cpsprod-mkpxu
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-pagamentosdebito
          name: grafana-dashboard-pagamentosdebito-71l87
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-paineldebitohml
          name: grafana-dashboard-paineldebitohml-53niw
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-consultatransporte-prd
          name: grafana-dashboard-consultatransporte-prd-f4nbr
        - configMap:
            defaultMode: 420
            name: grafana-dashboard-pagamentos
          name: grafana-dashboard-pagamentos-pn4qn
status:
  availableReplicas: 1
  conditions:
    - lastTransitionTime: '2019-12-17T22:14:56Z'
      lastUpdateTime: '2019-12-17T22:14:56Z'
      message: Deployment has minimum availability.
      reason: MinimumReplicasAvailable
      status: 'True'
      type: Available
    - lastTransitionTime: '2020-03-02T18:47:47Z'
      lastUpdateTime: '2020-06-19T04:48:22Z'
      message: ReplicaSet "grafana-5467fdccfb" has successfully progressed.
      reason: NewReplicaSetAvailable
      status: 'True'
      type: Progressing
  observedGeneration: 47
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
`


The secret that contains grafana.ini:
`app_mode = production

#################################### Paths ####################################
[paths]
data = /var/lib/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning

#################################### Server ####################################
[server]
http_addr = 0.0.0.0
router_logging = true

#################################### Database ####################################
[database]
type = mysql
host = 10.134.4.91:3306
name = grafana
user = grafana
#If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
password = "XXXXXX"
#Use either URL or the previous fields to configure the database
#Example: mysql://user:secret@host:port/database
#url =

#################################### Analytics ####################################
[analytics]
reporting_enabled = false
check_for_updates = false

#################################### Security ####################################
[security]
disable_initial_admin_creation = false
admin_user = admin
admin_password = "XXXXXX"

#################################### Users ###############################
[users]
allow_sign_up = true
allow_org_create = false
auto_assign_org = true

#################################### Auth ######################
[auth]
disable_login_form = false
disable_signout_menu = false

#################################### Anonymous Auth ######################
[auth.anonymous]
enabled = false

#################################### Proxy Auth ######################
[auth.proxy]
enabled = true
header_name = X-Forwarded-User

#################################### Basic Auth ##########################
[auth.basic]
enabled = false

#################################### Auth LDAP ##########################
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap/ldap.toml

#################################### Logging ##########################
[log]
level = info
filters = ldap:debug

#################################### Explore #############################
[explore]
enabled = false

#################################### Internal Grafana Metrics ##########################
[metrics]
enabled           = true`

**Comment by torkelo** [comment]
Can you include the data source provisioning yaml file?

**Comment by RuyCury** [comment]
Today this pod already works with sqlite, however we need to change it to mysql due to a business need. Because whenever we need to create a new dashboard, it is necessary to create a configmap for that dashboard. And once it was migrated to mysql, we would no longer need to create the configmaps, as the dashboards would be persisted in the mysql database.

**Comment by RuyCury** [comment]
`mssql.yaml:

apiVersion: 1
datasources:
- orgId: 1
  name: Microsoft SQL Server
  type: mssql
  typeLogoUrl: public/app/plugins/datasource/mssql/img/sql_server_logo.svg
  access: proxy
  url: ADQSQLPRD03.adiq.local
  secureJsonData:
    password: 'XXXXXXXX'
  user: adq_tmp
  database: ADQSTELLA
  basicAuth: false
  isDefault: false
  jsonData:
    encrypt: 'false'
  readOnly: true
- orgId: 1
  name: SQL Server - ADQMONITORAMENTO - HML
  type: mssql
  typeLogoUrl: public/app/plugins/datasource/mssql/img/sql_server_logo.svg
  access: proxy
  url: adqsqlhml02.adiq.local:62003
  secureJsonData:
    password: 'XXXXXXXXXX'
  user: U_ADQSISTEMA
  database: ADQMONITORAMENTO
  basicAuth: false
  isDefault: false
  jsonData:
    encrypt: 'false'
  readOnly: true
- orgId: 1
  name: ADQBH-PRD-ADQMONITORAMENTO
  type: mssql
  typeLogoUrl: public/app/plugins/datasource/mssql/img/sql_server_logo.svg
  access: proxy
  url: ADQSQLPRD03.adiq.local
  secureJsonData:
    password: 'XXXXXXXX'
  user: U_ADQMONITORAMENTO
  database: ADQMONITORAMENTO
  basicAuth: false
  isDefault: false
  jsonData:
    encrypt: 'false'
  readOnly: true
`
`prometheus.yaml:

apiVersion: 1
datasources:
- access: proxy
  basicAuth: true
  basicAuthPassword: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
  basicAuthUser: internal
  editable: false
  jsonData:
    tlsSkipVerify: true
  name: prometheus
  orgId: 1
  type: prometheus
  url: https://prometheus-k8s.openshift-monitoring.svc:9091
  version: 1
- access: proxy
  editable: false
  jsonData:
    tlsSkipVerify: true
  name: Prometheus-Custom
  orgId: 1
  type: prometheus
  url: http://prometheus-operated.app-monitoring.svc.cluster.local:9090
  version: 1

`

**Comment by marefr** [comment]
Please specify basicAuthPassword in secureJsonData, see example file and Secure Json Data section https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file.

```yaml
apiVersion: 1

datasources:
  - name: test
    basicAuth: true
    basicAuthUser: test
    secureJsonData:
      basicAuthPassword: XXX
```
