### ISSUE TITLE
column in the table takes more space than before

### ISSUE THREAD

**Issue by oshamin** [grafana/grafana#25722]
**What happened**:
The new version of Grafana renders tables differently than before. 

The table in the 6.7.4 automatically resized.

![image](https://user-images.githubusercontent.com/4929317/85171476-63945180-b26f-11ea-810a-9ce2029507bf.png)
The same table in the 7.0.3
![image](https://user-images.githubusercontent.com/4929317/85171672-bbcb5380-b26f-11ea-9d93-0f9cd0b43b40.png)

As you can see the scroll bar appeares on the bottom. The are more empty space, so it is used inefficiently.
Right now in the version 7.0.3 to remove the scroll bar i need to extend the width and the same table takes more space.

![image](https://user-images.githubusercontent.com/4929317/85171975-63488600-b270-11ea-8821-ce149baa74ce.png)

Can you return the previous behavior? 

**What you expected to happen**:
I expect the table plugin auto resize the table the same way as it was in version 6.7.4.

**How to reproduce it (as minimally and precisely as possible)**:
Presented.

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/grafana:7.0.3
- Data source type & version: 
- OS Grafana is installed on: docker
- User OS & Browser: chrome
- Grafana plugins: Table
- Others:

**Comment by baur** [comment]
same problem #24759

**Comment by torkelo** [comment]
the new table has virtual rendering of rows (so can handle rendering a lot rows in a performant way), so automatic column sizing is not possible. 

But the new table panel allows manual column resizing
