### ISSUE TITLE
problems with long instance names. Are there grafana functions that 'cut' strings?

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#25730]
Is it already possible to use a simple function to split the variable name and use only the first part. I am testing with the Windows Node dashboard. As you can see, the long nic names are not that useful.

The legent has:
`Sent {{nic}}`

Is there something like
`Sent {{nic.substr(0,5)}}`

![test](https://user-images.githubusercontent.com/13450219/85204531-6fd2ea00-b315-11ea-8afa-4cdbb34a1650.png)

https://community.grafana.com/t/string-operations-on-variables/13197

https://github.com/grafana/grafana/issues/464

**Comment by marefr** [comment]
Duplicate of #8259

**Comment by f1-outsourcing** [comment]
Yes but I do not see a reference what the correct syntax is for shortening my Legend {{nic}}

**Comment by marefr** [comment]
@f1-outsourcing it's a duplicate of an open feature request which means shortening legend is not possible unless you can do it using your data source query language.
