### ISSUE TITLE
Annotations improvement using template variables in the tag query

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#25738]
**What would you like to be added**:
It would be great to see annotations only for **visible** variables (labels) in the tag query.
Now all kind of template variables are triggering an annotation.

**Why is this needed**:
It's used a set of hidden variables on all dashboards in order to keep selected values during jumping from one dashboard to another. So some variables are used as labels on one dashboard and hidden on others dashboards.
It makes using template variables in the tag query useless. Annotation for a specific variable is shown on all dashboards.

e.g.
Here is a dashboard with visible "node_name" (ip-10-178-0-167) and hidden "service_name" (ps_5.7_0.0.0.0_1). Annotation is created for a service_name but show on a dashboard that has no active service_name.
![Screenshot_20200622_135041](https://user-images.githubusercontent.com/25184101/85280186-51452e00-b490-11ea-8dd0-03483d0151db.png)
![Screenshot_20200622_135101](https://user-images.githubusercontent.com/25184101/85280195-55714b80-b490-11ea-8309-05e6a3b04c51.png)
![Screenshot_20200622_135839](https://user-images.githubusercontent.com/25184101/85280288-82bdf980-b490-11ea-8e0c-4a67ed9e21ca.png)

**Comment by marefr** [comment]
I'm sorry, but this request doesn't really make sense to me since the concept of hiding a variable is stricly a UI setting for the variable and this information is not available in the annotation query. Why not remove the service_name tag from annotation query is those dashboard where you've hidden that variable?
