### ISSUE TITLE
Snapshots expire before their TTL

### ISSUE THREAD

**Issue by gummiboll** [grafana/grafana#2574]
Hello!

First of all I want to thank you for a great piece of software and all your hard work on it!

Been running grafana for a couple of months but since a couple of weeks snapshots expire before they should. If I create a (local) snapshot with a TTL of 7 days it disappears during the next night. Have tried running it with log level = Trace but haven't found anything to go on really.

Searched trough the issues and couldn't find anything related to this so Im guessing this might have something to do with my installation but can't find any smoking guns.. 

Ideas?

PS. Currently running grafana 2.1.1

**Comment by torkelo** [comment]
thanks for reporting this! Fixed in master

**Comment by gummiboll** [comment]
Great! Thanks for quick fix! :+1:
