### ISSUE TITLE
duplicate graphics in grafana with prometheus

### ISSUE THREAD

**Issue by ortiga88** [grafana/grafana#25740]
i have the following configruacion in my prometheus yml:

```
global:
  scrape_interval: 15s

scrape_configs:
   - job_name: 'windows-exporter-servidores-pita'
     scrape_interval: 60s
     static_configs:
       - targets: [ 'almariya9182',
                    'almariya2:9182']
                   

     relabel_configs:
       - source_labels: ['__address__']
         separator:     ':'
         regex:         "([^:]+):\\d+"
         target_label:  instance

```

The problem is that I have it like this to remove the test in grafana and that only the server is visible to me, but since they have the same name, then do they duplicate the graphics? Is there any special configuration so that they do not duplicate the graphics?

**Comment by torkelo** [comment]
Please ask questions on the community site https://community.grafana.com

> remove the test in grafana

Remove what? This sounds like a prometheus config question, not a Grafana question
