### ISSUE TITLE
Menus start jumping around if they don't fit within the area

### ISSUE THREAD

**Issue by GlennMatthys** [grafana/grafana#25743]
**What happened**:

Whilst editing panels, when opening long menus that don't fit in the available area, the menu jumps around.

![grafana_long_menus](https://user-images.githubusercontent.com/31989842/85295627-7f326e80-b4a0-11ea-93c6-0b975beba6c6.gif)

In the screen capture the menus seem to jump around slowly. This is because the screen is captured at 10 FPS. In reality it is much faster.

**What you expected to happen**:

The menu doesn't jump around.

**How to reproduce it (as minimally and precisely as possible)**:

Edit a panel, scroll to the bottom of the panel settings, try to edit something that triggers a long menu.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: N/A
- OS Grafana is installed on: CentOS Linux release 7.7.1908 (Core)
- User OS & Browser: Windows 10 Version 1909 (OS Build 18363.900), Chrome Version 83.0.4103.106 (Official Build) (64-bit)
- Grafana plugins: N/A 
- Others:

**Comment by marefr** [comment]
Not able to reproduce using Ubuntu 16.04 and Chrome Version 83.0.4103.97 (Official Build) (64-bit). Tried here https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editPanel=2

Please provide more information. Browser resolution? Any zooming enabled? Does this happen every time you edit panel overrides or in very specific situations?

**Comment by GlennMatthys** [comment]
* Browser window size: 1680x1050
* Zoom set at 100%
* Happens every time when editing panel overrides and scrolled to the bottom

![grafana_long_menus_2](https://user-images.githubusercontent.com/31989842/85367858-5c4c9c80-b52a-11ea-8b9d-24243c45c310.gif)

**Comment by marefr** [comment]
Sorry. Not able to reproduce. Will ask someone else to investigate this.

**Comment by peterholmberg** [comment]
I can reproduce this

**Comment by torkelo** [comment]
think with the new time series panel out in beta I think we will leave this bug unfixed
