### ISSUE TITLE
${__user.login} template not loaded properly on variable Init

### ISSUE THREAD

**Issue by mohamednizar** [grafana/grafana#25757]
**What happened**:
I upgraded from Grafa 6.7 to 7.1 And created a  variable to retrieve some value based on logged user. But the value only getting an update when saving the query, when the dashboard loading after login the value not found either its don't have previous value.

**What you expected to happen**:
The Initiated variable should set on the Dashboard on Load

**How to reproduce it (as minimally and precisely as possible)**:
Query : 
`select security_group_institutions.institution_id from security_users inner join security_group_users on security_group_users.security_user_id = security_users.id inner join security_group_institutions on security_group_institutions.security_group_id = security_group_users.security_group_id where  security_users.username = '${__user.login}'  group by security_group_institutions.institution_id limit 1`
![Screenshot from 2020-06-23 09-25-02](https://user-images.githubusercontent.com/8711284/85359297-7b036100-b533-11ea-94e3-73efece3e091.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1
- Data source type & version: Mysql 5.7
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Ubuntu & Chrome
- Grafana plugins: Default Plugins 
- Others:

**Comment by torkelo** [comment]
We will investigate. 

But I hope you understand that queries like this are not secure, anyone could change the user.login part that is replaced (in the browser). Templating is all done client-side by the user browser so any query can be issued. So do not use user.login as a way to data permission/security filter

**Comment by mohamednizar** [comment]
@torkelo Thank you for your reply!  

Yes, but are enabled only for view-only users. And I tried to the `InsId` from generic_oauth to make it secure, but gGafana support only the org type which is in the Grafana UI, not in the given Data Source. Is it possible to allocate the Org or new InId as users's variable? Then it would be safer and we will free from security issues.

**Comment by torkelo** [comment]
> Yes, but are enabled only for view-only users. And I tried to the InsId from generic_oauth to make it secure, but gGafana support only the org type which is in the Grafana UI, not in the given Data Source. Is it possible to allocate the Org or new InId as users's variable? Then it would be safer and we will free from security issues.

not sure I understand InsId? 

Anything you use in template variables is not secure as a user can fake/change any value

**Comment by mohamednizar** [comment]
`InsId` refers to org ID  which is not created in the Grafana UI.

**Comment by mckn** [comment]
I just verified that this issue will be resolved by the following https://github.com/grafana/grafana/pull/25698

**Comment by mohamednizar** [comment]
I checked with this : https://grafana.com/grafana/download/7.1.0-62bff84bpre?platform=linux , but not found the fixes of my issue.

**Comment by mckn** [comment]
@mohamednizar hmm, try the 7.0.4 version or one of the newer 7.1.0-xx versions. Those should have the working version.

**Comment by salanki** [comment]
This is still not working for me with latest master docker build. `master-62716d16-b558-426c-b6bb-ee87aa198e1a`.

**Comment by mckn** [comment]
@salanki @mohamednizar could you share your dashboard.json or some more details on your setup so I can try to recreate your issue?

**Comment by mohamednizar** [comment]
@mckn here our dashboard JSON.

https://github.com/moe-lk/sis-dashbord/blob/master/school/principal_dashboard.json

**Comment by mohamednizar** [comment]
@mckn here our dashboard JSON.

https://github.com/moe-lk/sis-dashbord/blob/master/school/principal_dashboard.json

**Comment by mohamednizar** [comment]
@mckn  tested with https://grafana.com/grafana/download/7.1.0-9ac43767pre, even working yet.

**Comment by mohamednizar** [comment]
@mckn tested with 7.1-beta1 version, this is not resolved yet.

**Comment by salanki** [comment]
I tested with beta1 too, does not work. Will provide a test dashboard as well. Please reopen issue.

**Comment by mohamednizar** [comment]
Probably the refresh on the dashboard load is not working, but refresh value on a time range is working.

**Comment by salanki** [comment]
Confirming that it works on time change, but not on dashboard load.

<img width="1134" alt="Screen Shot 2020-07-02 at 9 54 56 AM" src="https://user-images.githubusercontent.com/192223/86367638-37eb7100-bc4a-11ea-9d17-64192806be98.png">
<img width="632" alt="Screen Shot 2020-07-02 at 9 54 47 AM" src="https://user-images.githubusercontent.com/192223/86367640-38840780-bc4a-11ea-88b5-7ebe84186afd.png">

Test dashboard: https://gist.github.com/salanki/5e875aab650040383197eb4fe5a5c88c

**Comment by salanki** [comment]
@mckn @dprokop will you repo men this one or do you want us to file a new ticket?

**Comment by dprokop** [comment]
@salanki I have reopened this one and we will spend some time on it :)

**Comment by mckn** [comment]
> @salanki I have reopened this one and we will spend some time on it :)

Thanks @dprokop! I have been busy with other activities so thanks for handling this 🙏

**Comment by mohamednizar** [comment]
@salanki when we get done this? We are waiting without release dashboard to our day to day users.

**Comment by patlachance** [comment]
> But I hope you understand that queries like this are not secure, anyone could change the user.login part that is replaced (in the browser). Templating is all done client-side by the user browser so any query can be issued. So do not use user.login as a way to data permission/security filter

@torkelo any server side variables that could he used to apply such user or team based filtering? We'd like to avoid relying on duplicated dashboards in a folder structure.

**Comment by salanki** [comment]
Duplicated dashboards are not more secure. Anyone can use the Grafana API and execute any query they wish against the datasource. The queries are fully generated in the frontend. Open the network inspector in your browser, load a dashboard and  you will see what I mean.

**Comment by patlachance** [comment]
@salanki: do you mean that any user that can connect to the Grafana API can execute any query on any datasources defined in that Grafana instance, regardless of the permissions one can implement based on teams mapped to folders?

**Comment by torkelo** [comment]
permissions on folders/dashboards are only for who can see/update the dashboards, not related to who can issue what query to a data source

**Comment by patlachance** [comment]
> permissions on folders/dashboards are only for who can see/update the dashboards, not related to who can issue what query to a data source

Got it. But from the comments above, I understand that if a malicious user can see a dashboard, he can then modify the queries on the client-side and pull any data from any datasources the Grafana instance has access to through the Grafana API? Am I right?

**Comment by salanki** [comment]
He can query any datasource that that grafana org has access to, correct. This should be better documented as most people (including me) assume that a view only dashboard means that the data is safe.

**Comment by torkelo** [comment]
yes, any user can issue any possible query  https://grafana.com/docs/grafana/latest/permissions/#data-source-permissions

**Comment by salanki** [comment]
@torkelo: Are there any plans to add some logic to only allow the predefined queries to be executed for a View only user? This is a feature that I would be more than happy to pay for with Grafana Enterprise.

**Comment by patlachance** [comment]
> The problem with query level access checks is that a dashboard can be very dynamic (template variables), so there is no way for the backend to validate that a query is part of a dashboard the user has access to. Variables can be anything (even contain part of queries/filters)

I thought that there was a session opened for each users when they authenticate to Grafana and that this session was then used apply various things such as applying a RBAC model on the webui and any other components involved to process users' requests. The session is not controlled by the backend?

**Comment by torkelo** [comment]
of course there is a session and a RBAC model for everything (who has access to what dashboards, and data sources). Only a user who is a member of an organization can query it's data sources. But the backend cannot know what queries a user is allowed to issue as queries are very dynamic and composed in the frontend based on user selected variables and other dynamic factors like repeated panels and rows
