### ISSUE TITLE
 Unable to set alerts. Throws "tsdb.HandleRequest() error Request failed status: 502 notresolvable"

### ISSUE THREAD

**Issue by gurupalakuru** [grafana/grafana#25750]
What happened: Trying to create alerts for my dashboard panels

What you expected to happen: I expected it work but when I click test rule above error pops up

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:

Environment: Prod

Grafana version: 7.0.3
Data source type & version: Graphite & 0.9.15
OS Grafana is installed on: CentOS Linux release 7.2.1511
User OS & Browser: MacOS 10.13.6 & Chrome Version 83.0.4103.97
Grafana plugins:
Others:
Datasource access is added as browser

**Comment by gurupalakuru** [comment]
I was getting the same error in the older version of grafana which 5.2.2. Upon suggestion updated the grafana version

**Comment by marefr** [comment]
You have network/configuration error. Make sure that Grafana server can connect/communicate with your data source.
