### ISSUE TITLE
Can grafana add a configuration to disable/enable 'chunked transfer encoding' for static resources of plugins?

### ISSUE THREAD

**Issue by Alan-LOL** [grafana/grafana#25756]
**What would you like to be added**: A configuration to **disable/enable** `chunked transfer encoding` for static resources of plugins

**Why is this needed**: Referring to the [/docs/sources/developers/plugins/backend/_index.md](https://github.com/grafana/grafana/blob/6aeb00a85971784b109faf7be29c9ef7a06a2fc4/docs/sources/developers/plugins/backend/_index.md) and what I meet:

![image](https://user-images.githubusercontent.com/19995340/85354459-31b80f00-b53d-11ea-8910-13797898ba60.png)

In my case, I embed several grafana panels(through iframe) into my web page. And the `chunked transfer encoding` static resources is re-fetched from the server by each iframe —— this costs a lot of time to show the page. The other static resources are feteched from the server only once and then cached on the browser —— this is what I need.

I think this can be optimized.

**Comment by marefr** [comment]
How is https://grafana.com/docs/grafana/latest/developers/plugins/backend/#resources related. Have you written your own plugin or using a plugin? What plugin? That screenshot doesn't look to come from a plugin, looks like built in resources.

- What Grafana version? 
- Are you using any reverse proxy in front of Grafana? 
- What browser are you using? Sure you haven't checked Disable cache in chrome developer tools?
- Can you reproduce it [here](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1?)

**Comment by Alan-LOL** [comment]
Hi @marefr, yes there is a nginx in front of Grafana. I think this may be the key point. I will check if the nginx causes the chunked transfer encoding and reply later.

I might misunderstood the [https://grafana.com/docs/grafana/latest/developers/plugins/backend/#resources](https://grafana.com/docs/grafana/latest/developers/plugins/backend/#resources). On the **Resources** paragraph. It says 

> Use chunked transfer encoding to return large data responses in chunks or to enable “basic” streaming capabilities

Thank you for your quick reply!
