### ISSUE TITLE
completely uninstalled, deleted and re-installed - default login not accepted

### ISSUE THREAD

**Issue by Obre** [grafana/grafana#25767]
Hi,

using macOS I have had a grafana installation on my machine but I wanted to start from scratch and completely removed it via brew and also deleted all remaining folder that brew shows after uninstall

now I re-installed again and the "admin" "password" combination from the docs is not working. It just does not log me in locally.

What can I do? using SQLITE in grafana

**Comment by torkelo** [comment]
Maybe the DB is still there? Does your old passwords work?

You can reset admin password using: https://grafana.com/docs/grafana/latest/administration/cli/#reset-admin-password

**Comment by Obre** [comment]
i did that and it had  ✔ everywhere 

restarted grafana

still cannot login with the changed password

**Comment by Obre** [comment]
is there a way in macOS to delete every single trace of grafana easily?

**Comment by JorgeAndArias** [comment]
@Obre did you find a solution? I'm having the same problem

**Comment by jha-pravin** [comment]
I am having the same issue. Unable to find solution

**Comment by jha-pravin** [comment]
I was able to find the solution by completely uninstalling it. I had installed it using Homebrew, So uninstalled using brew uninstall grafana and then manually deleting folders from etc and var folders in mac with intel chip.

**Comment by Swordopolis** [comment]
Removing the grafana.db can get you back to a clean install.  See this issue also open on the topic: https://github.com/grafana/grafana/issues/81033
