### ISSUE TITLE
Remove link-commands in Panel links removes the last in the list when any of the items is removed

### ISSUE THREAD

**Issue by lmaki** [grafana/grafana#25765]
![grafana](https://user-images.githubusercontent.com/3896776/85393931-7d2ae700-b556-11ea-9726-f90352f4d594.gif)

**What happened**: 

In General / Panel links if I press any of the Remove link buttons that are associated to specific links and I have multiple links it removes the last one from the list

**What you expected to happen**: 

The buttons to remove the specific link it is associated with (It is in the end of the specific link item and there are one for each but they don't seem to be contextual)

**How to reproduce it (as minimally and precisely as possible)**: 

1. Create two Panel links, name them First link and Second link 
2. Press the Remove link button for the on the First link item

Actual: it removes the Second link item

Expected: to remove the First link item

**Environment**:
- Grafana version: v6.5.1
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser: Windows 10 Pro + Chrome
- Grafana plugins:
![image](https://user-images.githubusercontent.com/3896776/85392512-4e137600-b554-11ea-8b70-8953b1679625.png)

- Others:

**Comment by marefr** [comment]
Unable to reproduce on Grafana v7.0.3. Please upgrade
