### ISSUE TITLE
timeGroup function group data on Thursday

### ISSUE THREAD

**Issue by sandcoffin** [grafana/grafana#25769]
**Environment**:
- Grafana version: latest version 7.0.1
- Data source type & version: mysql
- OS Grafana is installed on: centOS
- User OS & Browser:
- Grafana plugins:
- Others:

Hi,

i have a question regarding this timeGroup function, when i use

$__timeGroup(updatetime,‘7d’, 0) as time,

The data is grouped weekly but start from Thursday, can it be from Monday as most of users expect ?
Also from the Query Inspector, it seems the time is deviated by 7 hours
I would expect something like
2020-06-22 00:00:00
2020-06-29 00:00:00

![image](https://user-images.githubusercontent.com/16156136/85414346-2e04a680-b596-11ea-8d6d-284d39abf634.png)

**Comment by feiou** [comment]
Same problem for me for both the week and day problem. But my day starts at 20:00 instead of 7:00 and my week starts at Wed instead of Thursday. 

I spent days trying to figure out but still couldn't. Please let me know if there is a fix.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

Grafana UI expects timestamps returned in UTC. Make sure that timestamps returned from your queries correlates with UTC.
