### ISSUE TITLE
Value Mapping on specific Column in Table element is applied to all Columns

### ISSUE THREAD

**Issue by LordVoodoo** [grafana/grafana#25764]
I have setup a new table element with a few columns and added for the column "CoT2" the following value mappings:
-1: Short
0: neutral
1: Long

This works for column "CoT2"  as designed, but the value mapping is also extended to the column "Sortierung".

**What happened:**
Value mapping of one column is applied to all columns.

**What is expected:**
Value mapping assigned to one specific column should only be applied to this specific column.

**Environment:**
Grafana v7.0.3 (00ee734baf), Docker hosted, Debian
MySQL 5.7 Data Source
Client: MacBook Pro 13 (2018), MacOS 10.15.5, Chrome Browser

![image](https://user-images.githubusercontent.com/34675323/85387913-bc9d0780-b545-11ea-81a1-093b73c34fb7.png)

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Can you please include 
- panel json
- query inspector request/reponse
- Any transformations in use?
- Any other value mappings defined other than field override like in panel tab?

**Comment by MaDOS** [comment]
Same issue here. 

**Panel JSON**:
`
{
  "datasource": "PostgreSQL",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "center"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [
        {
          "from": "",
          "id": 0,
          "operator": "",
          "text": "Tag",
          "to": "",
          "type": 1,
          "value": "0"
        },
        {
          "from": "",
          "id": 1,
          "operator": "",
          "text": "Event",
          "to": "",
          "type": 1,
          "value": "1"
        },
        {
          "from": "",
          "id": 2,
          "operator": "",
          "text": "Trigger",
          "to": "",
          "type": 1,
          "value": "2"
        }
      ]
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "loggerid"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Logger Id"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "logger_type"
        },
        "properties": [
          {
            "id": "displayName",
            "value": "Logger Type"
          },
          {
            "id": "mappings",
            "value": [
              {
                "from": "",
                "id": 0,
                "operator": "",
                "text": "Tag",
                "to": "",
                "type": 1,
                "value": "0"
              },
              {
                "from": "",
                "id": 1,
                "operator": "",
                "text": "Event",
                "to": "",
                "type": 1,
                "value": "1"
              },
              {
                "from": "",
                "id": 2,
                "operator": "",
                "text": "Trigger",
                "to": "",
                "type": 1,
                "value": "2"
              }
            ]
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "options": {
    "showHeader": true
  },
  "pluginVersion": "7.0.3",
  "targets": [
    {
      "format": "table",
      "group": [],
      "metricColumn": "none",
      "rawQuery": true,
      "rawSql": "SELECT\n  *\nFROM info_logger",
      "refId": "A",
      "select": [
        [
          {
            "params": [
              "avg_real"
            ],
            "type": "column"
          }
        ]
      ],
      "table": "mat_log_tag_hour",
      "timeColumn": "ts_bucket",
      "timeColumnType": "timestamp",
      "where": [
        {
          "name": "$__timeFilter",
          "params": [],
          "type": "macro"
        }
      ]
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Panel Title",
  "type": "table"
}
`

**Query inspector request/response**:
`
{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1593393309732",
      "to": "1593414909732",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 1488,
          "datasourceId": 1,
          "rawSql": "SELECT\n  *\nFROM info_logger",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "rowCount": 2,
          "sql": "SELECT\n  *\nFROM info_logger"
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "loggerid"
              },
              {
                "text": "logger_type"
              },
              {
                "text": "hostname"
              },
              {
                "text": "ts_started"
              },
              {
                "text": "logfile"
              },
              {
                "text": "DbBatchMaxSize"
              },
              {
                "text": "DbBatchInterval"
              },
              {
                "text": "HealthUpdateInterval"
              },
              {
                "text": "TheoreticalIngestRate"
              }
            ],
            "rows": [
              [
                0,
                0,
                "VM-SSGI-IIM",
                "2020-06-26T11:47:32.907+02:00",
                "D:\\LogFiles\\TLT_TagLog.txt",
                100000,
                5000,
                1000,
                4
              ],
              [
                1,
                2,
                "VM-SSGI-IIM",
                "2020-06-29T09:00:57.05+02:00",
                "D:\\LogFiles\\TLT_TriggerLog.txt",
                50000,
                1000,
                1000,
                2
              ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "rowCount": 2,
              "sql": "SELECT\n  *\nFROM info_logger"
            }
          }
        ],
        "dataframes": null
      }
    }
  }
}
`

**Transformations**: None

**Other value mappings defined**: None

**Another Screenshot**:
![image](https://user-images.githubusercontent.com/632343/85984443-7cc49d00-b9e9-11ea-96df-4591b0467cad.png)

**Additional Information**:
* Override 1 and 2 are the only overrides configured. Everything else is left at defaults
* This happened on a fresh Grafana install. Other than configuring the Datasource and a Dashboard with this Table nothing was changed or created.
* Grafana and Database are installed on the same machine.
* Version: grafana-7.0.3.windows-amd64 zip package
* Data Source: PostgresSQL 12 with TimescaleDb (1.7) enabled
* Operating System: Windows 10 Enterprise LTSC 1809 (Build 17763.316)
* User OS: Same machine as Server
* Browser: Firefox 77.0.1 x64

**Comment by frdve** [comment]
Same issue here, but I think I see the problem, the 'Value Mapping' of the Overrides are being copied into the general Field tab, which then is used for every column.  
I've added this Field mapping in override (without setting a general Field Value mapping): 
![afbeelding](https://user-images.githubusercontent.com/66672043/86326710-649b8a80-bc42-11ea-9146-f1ec8afdd8e5.png)
And when I look into the Field tab, I see the Value mapping there too:
![afbeelding](https://user-images.githubusercontent.com/66672043/86326800-85fc7680-bc42-11ea-9938-d77cc438bd9e.png)

**Comment by frdve** [comment]
Would there be a timing to fixing this issue?
Thanks in advance!

**Comment by torkelo** [comment]
confirmed this is a bug, added an override here https://play.grafana.org/d/aL0DXjdGz/value-mappings-in-overrides?orgId=1 and it got copied to the defaults
