### ISSUE TITLE
Bug: Panels with drilldown link have 1px higher title, can cause layout issues

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2576]
This can cause issues when total span on row is greater than 12 (it wraps to next line)

![image](https://cloud.githubusercontent.com/assets/10999/9407828/454a75b4-480d-11e5-8d05-0f52a7dbe978.png)

**Comment by Dieterbe** [comment]
isn't webpage layout/design so much fun :)

**Comment by torkelo** [comment]
yes :)
