### ISSUE TITLE
Auto Layout Issues when using stat pannel

### ISSUE THREAD

**Issue by hyunyyo** [grafana/grafana#25761]
**What happened**:
I’m using the Grafana version 7.0.3
Using the stat panel and gauge panel, 
When the panel size is adjusted, the number of displayed values changes.

- Datasource & Query
![Datasource](https://user-images.githubusercontent.com/67307487/85368168-b7e84b80-b565-11ea-9655-b14b742d2d68.JPG)

- When Resize pannel
![issues](https://user-images.githubusercontent.com/67307487/85369853-cedc6d00-b568-11ea-9ae4-3cad062eb17b.gif)

**What you expected to happen**:
The number of displayed values should not change

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The same symptom occurs in the gauge panel.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: influxdb 1.8.0
- OS Grafana is installed on: CentOS 7.6
- User OS & Browser: Chrome

**Comment by marefr** [comment]
Not able to reproduce [here](https://play.grafana.org/d/6z-BmaZGk/issue-25761-stat-auto-size?orgId=1) using Chrome v83.0.4103.97.  
- What browser are you using?
- Are you using transformations or any field overrides?
- Do you have auto refresh enabled, i.e. is the influx query sent to server after you resize the panel?
- Please include your dashboad json

**Comment by torkelo** [comment]
Do you have auto refresh enabled? maybe there was a dashboard (time range) refresh and a new query was issued that did not return exactly the same number of series? 

Also unable to replicate, nor anyone else reporting this so a bit strange. Looks like it's being refreshed with new data (and less series)

**Comment by hyunyyo** [comment]
Here some Details
1. Browser : I have tested on multiple browsers (chrome, firefox, edge..)
2. Did not used Transformation and field overrides
3. Yes I used auto refresh(5s), It must be used for monitoring.
   and Collecting performance Metrics every 5 seconds by telegraf
4. Include dashboard json : 
[dashboard_json.txt](https://github.com/grafana/grafana/files/4820670/dashboard_json.txt)

5. I tried your live demo and It is different from my situation
    - Panel > Display > All values (I used Calculate)
    - There is only 2 server data (I have almost 30 servers)

**Comment by torkelo** [comment]
ok, since you have refresh, it must mean your query is returning the different number of series. 

That was what I expected as well as it look like new (different) data coming in as you resized the panel

**Comment by torkelo** [comment]
One thing that can change as you resize the panel is the $__interval variable as it's based on panel width by default. 

Expand the Query Options at the top and define a max data points number, then $__interval will be the same no matter how wide the panel is
