### ISSUE TITLE
Panel Resize Handles

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2577]
Resize handles in bottom right corners. 

![resize2](https://cloud.githubusercontent.com/assets/10999/9408647/e9a367f4-4814-11e5-9f43-e124b4014c85.gif)

**Comment by Dieterbe** [comment]
![borat-two-thumbs-up](https://cloud.githubusercontent.com/assets/20774/9409482/3e02f5a2-481b-11e5-9292-47365201aeb8.jpg)
