### ISSUE TITLE
Dashboard: Loading dashboard settings resets folder id when user/team have admin access to dashboard, but not the folder 

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#25771]
**What happened**:
Entered dashboard settings, then saving dashboard returning 403 unauthorized.

**What you expected to happen**:
Successful save of dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1. A user _user a_ with org role Viewer. 
2. _user a_ is member of  _team b_.
3. A folder _folder c_ with no specific permission for _user a_  or _team b_.
4. A dashboard _dashboard d_ in _folder c_ with _team b_ permission to Admin
5. _user a_ login and opens _dashboard d_
6. _user a_ can successfully save the dashboard
7. _user a_ enters dashboard settings
8. _user a_ can no longer save the dashboard - 403 unauthorized 

**Anything else we need to know?**:
After investigation seems like loading dashboard settings resets the folder selection to empty/zero and by that the 403 unauthorized is returned since the dashboard is trying to be saved in the _General_ folder. 

**Environment**:
- Grafana version: master (1bde4de827) and 7.0.3

**Comment by dprokop** [comment]
@marefr so the question here is. Should the user have possibility to save the dashboard at all? Since he/she is a viewer within a team which has admin rights for a given dashboard.

**Comment by torkelo** [comment]
This scenario is a bit problematic, not sure if we can support this permission setup well without tricky hacks.

**Comment by torkelo** [comment]
>  6. user a can successfully save the dashboard

I am a bit unsure if we should allow a save of a dashboard to a folder you only have view permissions for.

**Comment by dprokop** [comment]
> I am a bit unsure if we should allow a save of a dashboard to a folder you only have view permissions for.

yes, I'm actually concerned with this as well. Not sure how the permissions are designed. If it's team or the user permissions that take precedence in such scenario

**Comment by marefr** [comment]
It's working from an HTTP API/backend perspective. It's definitely an edge case that you can have editor/admin access to a dashboard, but not the folder. However, clearly users are dependent on this feature. I don't understand why dashboard have to make changes to the dashboard model by resetting the folder id when opening the dashboard settings.

**Comment by torkelo** [comment]
It’s just complex to have a drop down with an option that your not allowed to select yourself

**Comment by torkelo** [comment]
For example the folder picker is designed to now show dashboards your now allowed to save to , so this scenario is a bit messy with the folder picker having a value that is not available to choose from

**Comment by torkelo** [comment]
But I think we can solve it

**Comment by dprokop** [comment]
@torkelo @marefr Moving to 7.1
