### ISSUE TITLE
Permission Editor can see folders on which only viewers are allowed but he cannot open dashboards

### ISSUE THREAD

**Issue by schoofsc** [grafana/grafana#25788]
**What happened**:
Settings:
folder has the following permissions (Admin->Admin, Viewer-->View)
User has the role Editor. 

The user  with the role Editor can see the folder and the dashboards in it. When calling one of the dashboards you get the error "Access denied to this dashboard".

**What you expected to happen**:
Settings:
folder has the following permissions (Admin->Admin, Viewer-->View)
User has the role Editor. 

The user does not see the folder at all, because he has no rights to it. 
Or if the rights of the role viewer are inherited by the editor, the dashboards should be accessible.

**How to reproduce it (as minimally and precisely as possible)**:
Create an order with Dashboard and change the permissions. Create a user and change his role to Editor.
Click on the previously created folder and on Dashboards.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.3 (00ee734baf)
- Data source type & version: irrelevant
- OS Grafana is installed on: K8s / officially Helm Chart Version 5.1.4 
- User OS & Browser: macOS Mojave 10.14.6 & Google Chrome Version 83.0.4103.116 (Offizieller Build) (64-Bit)
- Grafana plugins: grafana-piechart-panel, grafana-clock-panel, vonage-status-panel

**Comment by marefr** [comment]
Same problem on 6.7.4 and 6.0.0. Seems like an edge-case not many have noticed.

**Comment by torkelo** [comment]
Think it's correct that he sees it, should be able to open it as well, as an Editor user is also a Viewer
