### ISSUE TITLE
__user variable does not work in variable definitions

### ISSUE THREAD

**Issue by salanki** [grafana/grafana#25784]
**What happened**:
The new user templating variable (#4922) does not expand in queries in variable definitions for the dashboard on load.

**What you expected to happen**:
The variable would expand like anywhere else in queries.

**How to reproduce it (as minimally and precisely as possible)**:
Add a Variable of type query, select a SQL data source, add query `SELECT "${__user.login}`. Set refresh "on dashboard load".

In "preview of values" the value is correctly retrieved. However, on dashboard load, the variable will only contain  the text`${__user.login}`. If, after reloading the dashboard, you enter the variables editor again, the "preview of values" will now show the text `${__user.login}`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master-10e2a910-4c7d-4491-9159-badc2d6a31e6
- Data source type & version: MySQL
- OS Grafana is installed on: Docker
- User OS & Browser: Mac / Safari
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
Will be fixed by https://github.com/grafana/grafana/pull/25698

**Comment by salanki** [comment]
This issue still exists in master `master-62716d16-b558-426c-b6bb-ee87aa198e1a` that is from today (many days after #25698 was merged.

**Comment by salanki** [comment]
<img width="462" alt="Screen Shot 2020-06-30 at 8 09 05 PM" src="https://user-images.githubusercontent.com/192223/86188724-8e9f6080-bb0d-11ea-9760-cc1fde220d1d.png">
<img width="1069" alt="Screen Shot 2020-06-30 at 8 09 29 PM" src="https://user-images.githubusercontent.com/192223/86188739-9c54e600-bb0d-11ea-9d74-f2fd65f687fd.png">
