### ISSUE TITLE
bug? e.replace is not a function (grafana v7.0.3)

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#25782]
**What happened**:
2x Panels using the singlestat visualization (with very similar queries) in a dashboard is blank with Red ! saying e.replace is not a function.  I do see this from time to time on other Line graph panels also.
(not always but does a few times a day when dashboard is on a 5m auto refresh)
**almost always, reloading the page (via chorme) will then get the error-ed graph to show**
(also when i click on the red ! to get the Query explorer, all data is correct and no nulls)

**Here is the query explorer output and the POST request:**
https://pastebin.com/W8KnMWmn

What Grafana version are you using?
7.0.3

What datasource are you using?
Graphite v0.9.12

**Full Error (chrome inspector on windows 10) :**

react-dom.production.min.js:196 
TypeError: e.replace is not a function
    at e.value (template_srv.ts:327)
    at e.value (PanelModel.ts:481)
    at z (fieldDisplay.ts:198)
    at x (fieldDisplay.ts:195)
    at I (fieldDisplay.ts:116)
    at Object.n.getValues (StatPanel.tsx:84)
    at t.value (VizRepeater.tsx:63)
    at mc (react-dom.production.min.js:251)
    at KqkS.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wo (react-dom.production.min.js:120)
fu @ vendors~app.d3489276abe5fda2bd26.js:2

not sure if this helps, but here is SS of the full query:
![image](https://user-images.githubusercontent.com/60830628/85455634-b9187900-b563-11ea-9dbb-59b7ba353088.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Graphite v0.9.12
- OS Grafana is installed on:
# lsb_release -a
Description:    Debian GNU/Linux 8.11 (jessie)
Release:        8.11
Codename:       jessie
- User OS & Browser:
Chrome: 81.0.4044.138   Win10
- Grafana plugins:
Carpetmap (but not used)
- Others:
please let me know anything else i can provide to help.  thanks

**Comment by bob454522** [comment]
I should add, this only happens occasionally on these two panels (when they get refreshed,  either manually or by auto-refresh).  i would say 98% of the time these two panels show the data properly and with no issues.  Here is how they look normally:

![image](https://user-images.githubusercontent.com/60830628/85613644-b5e2c300-b61f-11ea-866c-7618c9840c6d.png)

thanks

**Comment by marefr** [comment]
Are you using template variables or ad-hoc filter variable? Any change you can include the dashboard json model? Replace sensitive information, if any. Thanks

**Comment by bob454522** [comment]
Thanks mare,
im not fully clear on what an ad-hoc filter variable is (i did try to look up) ,  i can say im definitely **not** using template variables in this case though.  (ie on this dashboard, there is no variable drop-down menu at the top for the user to change).

This image is the entire query,  the wildcard in geom_bw-* ,  selects several disks such as 
geom_bw-da1
geom_bw-da2
geom_bw-ada0
geom_bw-nvd1
geom_bw-da3
(and so on).

This query does not change (ie the disks, geom_bw-* do not change)
![image](https://user-images.githubusercontent.com/60830628/85782336-20613500-b6ec-11ea-8cdf-ff695d816633.png)

While i did post the full output from the Query inspector (on pastebin link in OP),  maybe this screenshot below will help also?

![image](https://user-images.githubusercontent.com/60830628/85783275-c7de6780-b6ec-11ea-9239-5812089466b3.png)
and
![image](https://user-images.githubusercontent.com/60830628/85783426-ee040780-b6ec-11ea-81fc-99aa3ed03ab5.png)

I hope that is helpful, or please let me know what else i can provide.  
thank you for your time

**Comment by bob454522** [comment]
Did i not answer your question (re; needing more detail?)  thanks

**Comment by torkelo** [comment]
Can you replicate this and show the exact same query response where  you got this error?

**Comment by torkelo** [comment]
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information. (Need the query response when you get this error)

**Comment by johnydroptables** [comment]
Hello,

I've just found this potential bug too.

Using Zabbix as a data source, I want to create a variable which is a host query.
The hosts are in a zabbix hostgroup named the same as the dashboard so I want to use $__dashboard in the group query field.

I get this 
e.replace is not a function
and this
Template variables could not be initialized: e.replace is not a function

**Comment by sibiryoff** [comment]
Hello, 
Just encountered it when trying to create variable tags. 
Elasticsearch as a datasource.
Tags query: {"find": "terms", "field": "tenant.keyword", "query": {"prefix": {"tenant.keyword": {"value": "at"} } } }
And after that I am getting this error.
(maybe I am doing smth wrong)

**Comment by kiefersmith** [comment]
`Template variable service failed e.replace is not a function`

Just hit this - makes it so I can't see my variables pane...

**Comment by jakkarth** [comment]
After upgrading to Grafana v7.5.16 (c0e2ad126c), I've started getting this error. template_srv.ts line 255.

**Comment by fabiodepascale** [comment]
getting this error since latest upgrade to Grafana v7.5.16 (c0e2ad126c)

**Comment by ryaneyoung** [comment]
Same problem, 9.4.7

**Comment by moxious** [comment]
Another user reports the same issue on Grafana 7.3.4

https://community.grafana.com/t/while-configuring-grafana-im-facing-error-in-dashboard-it-says-e-replace-is-not-a-function/86241

**Comment by davidtinker** [comment]
I just had this problem. Somehow all the charts on my dashboard had lost their data sources. I just had to edit each once and re-select "Prometheus" to fix.

**Comment by mblls** [comment]
I have a similar problem `Error updating options: z.replace is not a function`. I had the same solution as the above comment which is to select the problematic variable and then re-run the query and everything works fine.
