### ISSUE TITLE
Support canceling a running query

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#25783]
**What would you like to be added**:

Some datasources will start queries that may take a long (long!) time to run.  Often these will return cancelation tokens or jobIds that need to be passed back in order to kill the job.  (disconnect is not enough!)

We currently have no good method to cancel the running queries.  

**Why is this needed**:

Timestream and Splunk can both kick off jobs that take a LONG time to run.  we need to support killing these jobs

**Comment by torkelo** [comment]
A bit related to https://github.com/grafana/grafana/pull/25746 

explore has this state for the refresh/run button 
![Screenshot from 2020-06-24 08-38-58](https://user-images.githubusercontent.com/10999/85509388-3391d900-b5f6-11ea-9d91-fe98aa9ee05f.png)

But not suitable for the dashboard. 

Would be nice to have like a query log of all queries (running and old) where you can see all queries issued and timing, and stop running queries. 

Potentially a really nice thing for template variable queries that are a bit invisible and hard to troubleshoot
