### ISSUE TITLE
ERR_TOO_MANY_REDIRECTS

### ISSUE THREAD

**Issue by dfinninger** [grafana/grafana#2578]
When trying to login to the Grafana server I get complaints from Chrome of too many redirects.
This is the error that is in the log file. The entire file contains entries similar to this over the course of half an hour. 

```
2015/08/20 07:58:47 [I] Completed /api/datasources/proxy/1/series 500 Internal Server Error in 4.125301ms
2015/08/20 07:58:47 [I] Completed /api/datasources/proxy/2/series 500 Internal Server Error in 6.409942ms
2015/08/20 07:58:47 [I] Completed /api/datasources/proxy/1/series 500 Internal Server Error in 7.981774ms
2015/08/20 07:58:47 [I] Completed /api/datasources/proxy/1/series 500 Internal Server Error in 10.283371ms
2015/08/20 07:58:47 [I] Completed /api/datasources/proxy/2/series 500 Internal Server Error in 12.966779ms
2015/08/20 07:58:47 [I] Completed /api/login/ping 500 Internal Server Error in 3.647571ms
2015/08/20 07:58:47 [I] Completed /api/login/ping 500 Internal Server Error in 3.066579ms
2015/08/20 07:58:47 [I] Completed /api/login/ping 500 Internal Server Error in 4.825867ms
2015/08/20 07:58:47 [I] Completed /api/login/ping 500 Internal Server Error in 7.820795ms
```

I am using InfluxDB as a data source. And I have not touched anything in the `grafana.ini` file.

**Comment by dfinninger** [comment]
To clarify, this occurs after I login. I get to the login page just fine, then after entering credentials I get the redirect loop error.

**Comment by torkelo** [comment]
what did you specify in grafana option root_url ? and do you any reverse proxy (nginx for example) in front of grafana?

**Comment by dfinninger** [comment]
Sorry for the delay, tackling a few issues at once right now.

I didn't specify anything. It has been left to the defaults:
```
# The full public facing url
;root_url = %(protocol)s://%(domain)s:%(http_port)s/
```

And yes, I have an Nginx reverse proxy that has worked well until now. I turned it off for testing, but the issue remains.

**Comment by torkelo** [comment]
but if your using an nginx proxy you need to specify the proxy ip/ and port in root_url 

root_url should be what you use in the browser (it is used to set session cookie). 

Have you disabled cookies? What browser are you using?

**Comment by dfinninger** [comment]
Chrome. But the issue is repeatable with Safari.
I've deleted the cookie I was using, then I deleted all cookies, then I turned off cookies. Still the same issue.

Also, the Nginx proxy is currently off. It's been off for about two hours and the issue still remains.
But for reference, here's the Nginx config. Pretty bare bones:

```
server {
        server_name localhost;
        location / {
                proxy_pass http://127.0.0.1:3000;
        }
}
```

Any other info you need?

**Comment by torkelo** [comment]
One reason could be that your hard drive is full or grafana does not have permission to create the session file in the data folder. 

If not that, no idea :(

**Comment by dfinninger** [comment]
I'll check both of those. If that's not it then I can just wipe and reinstall.

What is the directory where the dashboard configs are located? I'd like to not have to recreate those, lol.

**Comment by torkelo** [comment]
dashboards are stored in the sqlite3 database, which is by default at /var/lib/grafana/grafana.db

**Comment by dfinninger** [comment]
Alright, so I decided to try something else and it seems to have worked.

In the `/var/lib/grafana` directory there is the database and a dir called `sessions`. On a whim I deleted the `sessions` dir and bam, problem solved. 

File system is at 45% full and permissions seemed to be fine, so I'm not sure what the issue was.

Anyway, it seems I am back up and operational, so thanks for your help!

**Comment by mohdaliiqbal** [comment]
@dfinninger thanks - you saved me a hassle. removing `sessions` dir solves the problem.

**Comment by madAndroid** [comment]
We were experiencing this same problem in AWS - turning on sticky sessions in the ELB config resolved the issue for us.

**Comment by torkelo** [comment]
@madAndroid if you are running multiple grafana servers behind load balancer you need to switch sessions to mysql, postgres or redis.

**Comment by madAndroid** [comment]
Ah, okay .. thanks! that will make things easier for us to manage

**Comment by tim-massey** [comment]
I'm getting the same issue but running `grafana-server` on port 3000. I tried removing the /sessions dir and restarting the server. Any other suggestions?

**Comment by erSitzt** [comment]
Same problem here, no loadbalancer in front, sessions dir deleted, grafana-server (running on port 300) restarted. Still to many redirects error.

**Comment by tim-massey** [comment]
I think I ended up upgrading to something close to master and it worked.

**Comment by thomasmodeneis** [comment]
Similar issue here, upgrading to 4.1.1 solved the issue.

```
# sudo service grafana-server status
● grafana-server.service - Starts and stops a single grafana instance on this system
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: disabled)
   Active: active (running) since Sun 2017-01-22 20:12:58 CET; 24s ago
     Docs: http://docs.grafana.org
 Main PID: 29957 (grafana-server)
   CGroup: /system.slice/grafana-server.service
           └─29957 /usr/sbin/grafana-server --config=/etc/grafana/grafana.ini --pidfile= cfg:default.paths.logs=/var/log/grafana cfg:default.paths.data=/var/l...

Jan 22 20:13:18 grafana-server[29957]: goexit: CMPQ BX, $4
Jan 22 20:13:18 grafana-server[29957]: 2017/01/22 20:13:18 http: multiple response.WriteHeader calls
Jan 22 20:13:18 grafana-server[29957]: 2017/01/22 20:13:18 [I] Completed 111.111.111.11 admin "GET /login HTTP/1.1" 500 Interna... 3754us
Jan 22 20:13:18 grafana-server[29957]: [Macaron] PANIC: session(release): write /var/lib/grafana/sessions/c/7/c7740d147d513e4a... device
Jan 22 20:13:18 grafana-server[29957]: /usr/local/go/src/runtime/panic.go:423 (0x4cbe19)
Jan 22 20:13:18 grafana-server[29957]: gopanic: d._panic = (*_panic)(noescape(unsafe.Pointer(&p)))
Jan 22 20:13:18 grafana-server[29957]: /go/src/github.com/grafana/grafana/pkg/middleware/session.go:74 (0x64decb)
Jan 22 20:13:18 grafana-server[29957]: /usr/local/go/src/runtime/asm_amd64.s:437 (0x4fc15e)
Jan 22 20:13:18 grafana-server[29957]: call32: JMP        AX
Jan 22 20:13:18 grafana-server[29957]: /usr/local/go/src/reflect/value.go:432 (0x66601a)
```

**Comment by andres-lorenzatti-olx** [comment]
We had the TOO MANY REDIRECT error too in a AWS infra using ASG with 2 grafana instances behind ELB plus NGINX for reverse proxy on front of it.
Sorted problem setting sticky sessions on grafana ELB

**Comment by Kostanos** [comment]
Had the same issue in localhost (local environment) running with:
```
[session]
cookie_secure = true
```

Changing it to false resolved my issue.

Just in case if someone has a similar issue.

**Comment by kmurudi** [comment]
@dfinninger  thanks a ton! the sessions folder deletion worked for me as well!

**Comment by camtarn** [comment]
I had this issue after upgrading from Grafana 6.5 to 8.0. Clearing the Grafana cookies sorted it out.
