### ISSUE TITLE
How to use LDAP and anonymous authentication for another organization ?

### ISSUE THREAD

**Issue by jhon287** [grafana/grafana#2579]
Hello,

Is it possible to mix LDAP and anonymous authentication ?
When I browse to the website I need to put login/password...
How to use the anonymous one ?

Thank you in advance.

**Comment by torkelo** [comment]
for anonymous access you can specify what organization it should be in grafana.ini,  for ldap you can map ldap groups to grafana organizations (and to different organizations using org_id in ldap.toml)

**Comment by jhon287** [comment]
Yes that's what I done...
But how to use it ? Is the URL different for anonymous access ?

#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
enabled = false

# specify organization name that should be used for unauthenticated users
org_name = Anonymous Dashboard

# specify role for unauthenticated users
org_role = Viewer

**Comment by torkelo** [comment]
@jhon287 no, the url is the same. So in order to view dashboards as anonymous you need to make sure you are logged out, then go the grafana root url.

This should probably be set to true:) 
enabled = false

**Comment by jhon287** [comment]
Yes you're right ;) I will change it directly.
Thank you.
