### ISSUE TITLE
An unexpected error happened when add field from calculation in transform.

### ISSUE THREAD

**Issue by KippaZou** [grafana/grafana#25796]
**What happened**:

- An unexpected error happened when add field from calculation in a table transform. I can't return to the former page and have to refresh the page.

<img width="805" alt="image" src="https://user-images.githubusercontent.com/31032511/85522805-b76cb500-b638-11ea-8b3a-d5d51acc5035.png">

**What you expected to happen**:

- Even if the error happened, I can return to the former page other than refresh the page.

**How to reproduce it (as minimally and precisely as possible)**:

- Add field from calculation in a table.
- Select reduce row mode and then select another calculation except total.
- Click any field name and the error will happen.

<img width="519" alt="image" src="https://user-images.githubusercontent.com/31032511/85523605-c9028c80-b639-11ea-8a2f-d1ae529d4d1b.png">

**Anything else we need to know?**:

I upgrade grafana from v6.7.3 to v7.0.3 and the visualization is table(old).

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Mysql
- OS Grafana is installed on: Unbuntu
- User OS & Browser: safari
- Grafana plugins: mysql
- Others:

**Comment by marefr** [comment]
Are you still using the old table panel? If so, think you want to keep using the table transform function. If you want to use the transform feature please use the new table panel. Let me know the outcome.

**Comment by torkelo** [comment]
Think this is fixed in later patch releases
