### ISSUE TITLE
data not correct as query inspector

### ISSUE THREAD

**Issue by lcasi** [grafana/grafana#25800]
**What happened**:

panel data is not same as query inspector response data

![image](https://user-images.githubusercontent.com/47807658/85533992-92317400-b643-11ea-8f03-e3c6fa92c2b7.png)

**What you expected to happen**:

as picture, the value of "2020-06-24 08:00:00" should be 37, same as query response data.

**How to reproduce it (as minimally and precisely as possible)**:
precisely
**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.5.0
- Data source type & version:
 ClickHouse
- OS Grafana is installed on:
docker

**Comment by torkelo** [comment]
Maybe a bug in Clickhouse?

**Comment by marefr** [comment]
Can you by any change include the full query inspector request/response here? Remove sensitive information, if any. Do you have any table transformation applied?

**Comment by lcasi** [comment]
> Can you by any change include the full query inspector request/response here? Remove sensitive information, if any. Do you have any table transformation applied?

full query inspector request/response:

```json
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "query=SELECT%20%20%20%20%20(intDiv(toUInt32(time_iso)%2C%2086400)%20*%2086400)%20*%201000%20as%20t%2C%20%20%20%20%20count(DISTINCT%20ip)%20%60IP%20num%60%20FROM%20xxx.infra_net_all%20WHERE%20%20%20%20%20time_iso%20%3E%3D%201591841397%20and%20time_iso%20%3C%201593050999%20%20%20%20%20and%20http_code%20%3D%20412%20GROUP%20BY%20t%20ORDER%20BY%20t%20FORMAT%20JSON"
  },
  "response": {
    "meta": [
      {
        "name": "t",
        "type": "UInt64"
      },
      {
        "name": "IP num",
        "type": "UInt64"
      }
    ],
    "data": [
      {
        "t": "1591833600000",
        "IP num": "92"
      },
      {
        "t": "1591920000000",
        "IP num": "122"
      },
      {
        "t": "1592006400000",
        "IP num": "107"
      },
      {
        "t": "1592092800000",
        "IP num": "107"
      },
      {
        "t": "1592179200000",
        "IP num": "104"
      },
      {
        "t": "1592265600000",
        "IP num": "89"
      },
      {
        "t": "1592352000000",
        "IP num": "108"
      },
      {
        "t": "1592438400000",
        "IP num": "82"
      },
      {
        "t": "1592524800000",
        "IP num": "69"
      },
      {
        "t": "1592611200000",
        "IP num": "75"
      },
      {
        "t": "1592697600000",
        "IP num": "67"
      },
      {
        "t": "1592784000000",
        "IP num": "86"
      },
      {
        "t": "1592870400000",
        "IP num": "704"
      },
      {
        "t": "1592956800000",
        "IP num": "181"
      },
      {
        "t": "1593043200000",
        "IP num": "8"
      }
    ],
    "rows": 15,
    "statistics": {
      "elapsed": 0.39355915,
      "rows_read": 2641810685,
      "bytes_read": 17277706218
    }
  }
}
```
![image](https://user-images.githubusercontent.com/47807658/85645562-aec5be80-b6cc-11ea-8bf0-82cc094ff149.png)


table set:

![image](https://user-images.githubusercontent.com/47807658/85645519-8c33a580-b6cc-11ea-891e-fb0d5fd6280b.png)

**Comment by torkelo** [comment]
And if you change column style from number to string ? (As your values are strings)

**Comment by lcasi** [comment]
> And if you change column style from number to string ? (As your values are strings)

I have change the column style from number to string, but it's still not correct.
![image](https://user-images.githubusercontent.com/47807658/85721212-be242680-b723-11ea-8d5d-d9eb44896a71.png)

![image](https://user-images.githubusercontent.com/47807658/85721367-e0b63f80-b723-11ea-9482-85a7ca425380.png)

**Comment by torkelo** [comment]
I would open the issue with the Clickhouse plugin : https://github.com/Vertamedia/clickhouse-grafana 

Think they are applying some parsing here that could be the cause of the problem
