### ISSUE TITLE
2.1.0 to 2.1.2 rpm upgrade overwrites the ldap.toml file

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#2580]
I just upgraded from 2.1.0 to 2.1.2 using rpm -Uvh and it overwrote the ldap.toml config file.

$ service grafana-server stop && rpm -Uvh grafana-2.1.2-1.x86_64.rpm && service grafana-server start
OKopping Grafana Server ...                                [  OK  ]
warning: grafana-2.1.2-1.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 3dd18bdd: NOKEY
Preparing...                ########################################### [100%]
   1:grafana                ########################################### [100%]
### Upgrading Notice ### 
-- New grafana install home is /usr/share/grafana
-- Please move sqlite3 database to /var/lib/grafana/
-- Notice: service name && binary changed to grafana-server
Starting Grafana Server: .... OK

$ pwd
/etc/grafana
$ ls -l
total 28
-rw-r--r-- 1 root root 7038 Aug  5 12:06 grafana.ini
-rw-r--r-- 1 root root 5887 Aug  5 11:18 grafana.ini.orig
-rw-r--r-- 1 root root 7040 Aug  5 11:18 grafana.ini.rpmnew
-rw-r--r-- 1 root root 1242 Aug 20 03:36 ldap.toml

**Comment by torkelo** [comment]
thank you for reporting this! Dam, missed to mark this file as a config file in the deb and rpm packages.
