### ISSUE TITLE
Import dashboard screen should auto populate Folder with "General" by default or remember last folder used.

### ISSUE THREAD

**Issue by bbfoto** [grafana/grafana#25814]
**What would you like to be added**:
Since upgrading from 6.3 to 6.5 user reports not having permission to import dashboards.
They are assigned Editor role in the main org.

Turns out when they import the json, they did not specify a Folder.
past behavior for this scenario was that the dashboard was imported successfully into the "General folder" if no folder specified.

It appears that now they have to specify a folder. if they want the dashboard imported to the root of the dashboard menu they need to specify "General", which is fine but they didn't know and got "permission-denied" response.

I'm torn between calling this an enhancement or a ui/ux bug... or might it be a config thing? (I did look for obvious config options, but nothing jumped out at me)

IMHO - The import dashboard flow should auto-populate the Folder field with either the last folder used by the user or General. Bare minimum, the Folder field entry should have an indication that Folder value is required for non Admin roles.

**Why is this needed**:
usability improvement.

**Comment by marefr** [comment]
Please upgrade to a newer version. This is working on Grafana v7.0.3 at least.
