### ISSUE TITLE
Slack: Support chat.postMessage for posting notifications

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#25817]
**What would you like to be added**:
Support  using [chat.postMessage](https://api.slack.com/methods/chat.postMessage) for the Slack notification URL, so long as an auth token is also provided.

**Why is this needed**:
Slack doesn't allow overriding channel for incoming Webhooks now.

https://api.slack.com/messaging/webhooks (custom integration webhooks are legacy and should be replaced with apps)
> You cannot override the default channel (chosen by the user who installed your app), username, or icon when you're using Incoming Webhooks to post messages. Instead, these values will always inherit from the associated Slack app configuration.

If user want to send slack message to multiple channel, user need one incoming Webhook per one channel.
It is hard to maintain these webhooks.
Grafana already has ability to use token, so let's use token to post message.

**Comment by aknuds1** [comment]
I don't see how your link to legacy custom integrations is relevant, since you can still use incoming webhooks with Slack apps (which are the non-legacy, current method). I will have to test and see if I can verify the problem of being unable to post to multiple channels.

**Comment by mtanda** [comment]
Slack integration spec is complex, I didn't understand well.
But I verify I can't override channel by newly created Incoming webhooks.

**Comment by aknuds1** [comment]
I've edited the issue to reflect the intent of your corresponding PR.
