### ISSUE TITLE
Plugin build fails when targeting canary

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#25816]
When I try to build a plugin with canary, it fails with a `tsconfig.conf` related issue.  I have seen the issue on a few plugins, here is the simplest way to reproduce:

https://github.com/grafana/simple-datasource/compare/with-canary

![image](https://user-images.githubusercontent.com/705951/85638884-fea87500-b63b-11ea-86d5-8b663d570449.png)

**Comment by ryantxu** [comment]
@stevenvachon @dprokop any ideas?  Did anything change with the tsconfig setup in 7.1?

**Comment by dprokop** [comment]
Nope, nothing that I recall

**Comment by dprokop** [comment]
Maybe TS update?

**Comment by stevenvachon** [comment]
The file hasn't been touched since 4/20

**Comment by ryantxu** [comment]
Any insight on what might be happening -- we should make sure this is solved soon since it will break every plugin when we release 7.1 beta :grimacing:

**Comment by dprokop** [comment]
@ryantxu I'm on it tomorrow morning

**Comment by dprokop** [comment]
For some reason with canary toolkit is run in linked mode. Investigating
