### ISSUE TITLE
Divide Multiple Series

### ISSUE THREAD

**Issue by timtrinidad** [grafana/grafana#2581]
This may be a question for Graphite, but I wanted to check here first to see if it's possible with the existing Graphite API.

I have the following set of metrics:

stats.db1.threads_connected
stats.db1.max_connections

stats.db2.threads_connected
stats.db2.max_connections

... and so on (an arbitrary number of dbs).

Is there way to get a graph that shows the % of threads connected (threads_connected / max_connections), grouped by db name?

I've tried groupByNode (which only seems to support seriesfunctions with one series argument rather than 2 as required by divideSeries), and straight divideSeries (which doesn't like multiple series per argument).

**Comment by torkelo** [comment]
something like this could work:

`reduceSeries(mapSeries(stats.*.*,1),"asPercent",2,"threads_connected","max_connections")`

**Comment by timtrinidad** [comment]
Awesome - that looks exactly like what I'm looking for! It's not currently available on our current version of 0.9, but I'll look to upgrade for this.

Thanks again!
