### ISSUE TITLE
Cannot add back Metric for Elasticsearch table query after removing it when the Metric has type Raw Document

### ISSUE THREAD

**Issue by gabipetrovay** [grafana/grafana#25822]
**What happened**: The user can remove the Metric from an Elasticsearch query when the type is of type Raw Document

**What you expected to happen**: There should not be a plus (add) button on the Metric line when the type is Raw Document

**How to reproduce it (as minimally and precisely as possible)**:
- add an Elasticsearch table query
- choose Raw Document for the Metric type
- click the + (`addMetricAgg()`) at the end of the line
- the - (`removeMetricAgg()`) button appears. click it
- the Metric row is gone and cannot be added anymore

**Anything else we need to know?**:

**Environment**:
- Grafana version: `Grafana v7.0.3 (00ee734baf)`
- Data source type & version: Elasticsearch (online Grafana [demo dashboards](https://play.grafana.org/d/000000107/elasticsearch-metrics-filter?editPanel=2&orgId=1); source version not visible)
- OS Grafana is installed on: N/A
- User OS & Browser: Chrome latest
- Grafana plugins: N/A

**Comment by simianhacker** [comment]
This is no longer a valid bug, the React refactor fixed it.

**Comment by Elfo404** [comment]
@simianhacker good catch, thanks! closing this as it's fixed by #28033
