### ISSUE TITLE
Limit the maximum unit for single-number durations

### ISSUE THREAD

**Issue by pabigot** [grafana/grafana#25831]
Issue #8781 originally requested a feature that may have been misinterpreted when it was closed.  That feature is to be able to place a limit on the unit scale for durations expressed as a single number.

Consider these durations:

Seconds | Detailed Duration
------- | -----------------
24 | 24 s
2364 | 39 min, 24 s
63564 | 17 h, 39 min, 24 s
409164 | 4 d, 17 h, 39 min, 24 s
1618764 | 2 wk, 4 d, 17 h, 39 min, 24 s
22354764 | 8 mo, 2 wk, 4 d, 17 h, 39 min, 24 s
116962764 | 3 a, 8 mo, 2 wk, 4 d, 17 h, 39 min, 24 s

The table below shows possible representations of various durations using Grafana's unit/scale table.  The rightmost column corresponds to what is normally generated by `toDuration`.  The inner columns show what would be generated if the maximum unit were constrained to the unit identified in the column header:

Value | min | h | d | wk | mo | a
----- | --- | - | - | -- | -- | -
24 | 24.00 s | 24.00 s | 24.00 s | 24.00 s | 24.00 s | 24.00 s
2364 | 39.40 min | 39.40 min | 39.40 min | 39.40 min | 39.40 min | 39.40 min
63564 | 1059 min | 17.66 h | 17.66 h | 17.66 h | 17.66 h | 17.66 h
322764 | 5379 min | 89.66 h | 3.736 d | 3.736 d | 3.736 d | 3.736 d
1532364 | 2.554e+4 min | 425.7 h | 17.74 d | 2.534 wk | 2.534 wk | 2.534 wk
22268364 | 3.711e+5 min | 6186 h | 257.7 d | 36.82 wk | 8.591 mo | 8.591 mo
116876364 | 1.948e+6 min | 3.247e+4 h | 1353 d | 193.2 wk | 45.09 mo | 3.706 a

My understanding of the original issue was that the requestor wanted to get the values in column `d`.

This is needed because values like 2.5 weeks or 8.6 months are harder to understand than 17.7 days and 257.7 days.

[This comment](https://github.com/grafana/grafana/issues/8781#issuecomment-629682524) shows what might be involved in providing this capability.

**Comment by mvadu** [comment]
I would love this one too.. Regarding the UI question raised in the quoted comment, can we not add more [durations here](https://github.com/grafana/grafana/blob/529be0f513d2c86e29022fbe87c8ac72cbf3c762/packages/grafana-data/src/valueFormats/categories.ts#L370)? 
```
      { name: 'duration (min)', id: 'dtdurationmins', fn: toDurationUptoUnit('m') },
      { name: 'duration (hours)', id: 'dtdurationhours', fn: toDurationUptoUnit('H') },
      { name: 'duration (days)', id: 'dtdurationdays', fn: toDurationUptoUnit('d') },
      { name: 'duration (weeks)', id: 'dtdurationweeks', fn: toDurationUptoUnit('wk') },
      { name: 'duration (months)', id: 'dtdurationmonths', fn: toDurationUptoUnit('M') },
      { name: 'duration (years)', id: 'dtdurationyears', fn: toDurationUptoUnit('y') },
```

Usecase for me: I am tracking the remaining time left for a very long running contract. So my query is calculating delta from now to a future date. (e.g. `1767139200000 - time()`) I do not care exact hour/minutes in this case since its a future dated. I want to get this shown in number of weeks or months.
