### ISSUE TITLE
Table Plugin round float64 values to integer

### ISSUE THREAD

**Issue by Slach** [grafana/grafana#25839]
**What happened**:
when I try to reproduce https://github.com/Vertamedia/clickhouse-grafana/issues/199
I make a query to clickhouse data source plugin which returns float64 values
Table plugin shows these values as integer
Query inspector shows these values as float64
![image](https://user-images.githubusercontent.com/105560/85723208-75ad3e80-b70c-11ea-951e-ddaab4cdd063.png)

And "Field" tab "decimals" doesn't change this behavior
![image](https://user-images.githubusercontent.com/105560/85723490-bc029d80-b70c-11ea-9c28-d0b997005b9d.png)

**What you expected to happen**:
float64 values show "AS IS" or "decimals" should applied

**How to reproduce it (as minimally and precisely as possible)**:
Look to 
https://github.com/Vertamedia/clickhouse-grafana/issues/199#issuecomment-649519257

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: vertamedia-clickhouse-datasource, latest master 
- OS Grafana is installed on: Alpine Linux 3.11
- User OS & Browser: Chrome
- Grafana plugins: vertamedia-clickhouse-datasource

**Comment by ryantxu** [comment]
This looks like an issue with the clickhouse plugin... what should grafana do differently?
In the example you show, it looks like the first column is time, right?

reopen with more info if there is something that should happen in grafana and not in the clickhouse plugin
