### ISSUE TITLE
Slack notifications: Need to upgrade to new API

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#25847]
**What happened**:
For our Slack notifications, we need to upgrade to new [Slack API](https://api.slack.com/methods/chat.postMessage), since our current logic is designed for custom integrations web hooks, which are legacy and might be dropped.

The new chat.postMessage API is basically compatible with the current payloads we send, _but_ the _channel_ field (corresponding to our _Recipient_ field) is required, and we must include an `Authorization: Bearer $OAUTH_ACCESS_TOKEN` header corresponding to our _Token_ field.

Since two previously optional fields are required when upgrading to the new API, we have to think about how to deal with backwards compatibility.

See #25817, which stems out of the fact that we need to use the new API.

**Comment by martinaparikova** [comment]
Hi @aknuds1 , we stopped receiving Slack notifications from our Grafana dashboards using webhooks a few days ago. I assume it is connected to this issue? Do you have any estimation of when it will be fixed? Or can we do something on our end?

**Comment by aknuds1** [comment]
@martinaparikova Can you please create an issue describing your problem, and with enough details so I can reproduce?

**Comment by martinaparikova** [comment]
@aknuds1 Here is is, thank you! https://github.com/grafana/grafana/issues/25932

**Comment by aknuds1** [comment]
Made a PR to resolve this issue https://github.com/grafana/grafana/pull/32511.
