### ISSUE TITLE
Can't remove 5s database auto-refresh interval

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#25842]
**What happened**:
The 5s auto-refresh interval is still available for the dashboard after removing it from the dashboard configuration. All other default intervals can be removed.

This is happening on the 7.0.3 version. The version 6.7.4 works fine. It's been reproduced on play.grafana.org as well.

**What you expected to happen**:
That the 5S auto-refresh interval is no longer available after being deleted.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open the dashboard settings screen
2. Remove the 5s interval from the Auto-refresh box in the General settings tab
3. Save the dashboard
4. Reload the dashboard and click on the auto-refresh interval picker. 5s is still available there.

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: N/A
- OS Grafana is installed on: CentOS7
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment]
Please configure https://grafana.com/docs/grafana/latest/administration/configuration/#min-refresh-interval
