### ISSUE TITLE
Chore: Remove LegacyForms from Grafana core

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#25841]
A followup on #22862

After the new forms were implemented we were left with a few places where we still used the LegacyForms. These need to go.

[See the current amount of LegacyForms in use](https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1)

To find where they are used, simply search `LegacyForms` in the codebase. Some of these might need some further UX work though. To handle possible API changes, have a look at Forms in [@grafana/ui](https://developers.grafana.com/ui/canary/index.html?path=/story/*)

- [x] Dashboard folder permissions #28564 
- [x] Dashboard feature #28707

There are still some (internal) components in @grafana/ui that does not import LegacyForms, but rather import the sepaate components as a relative path. These are the components:

- [ ] ClipboardButton
- [ ] TagsInput (Where is this even used?)
- [ ] ColorPicker (The input field and Y-axis Switch)

These need more extensive UX/UI work
- [ ] DataSourceHttpSettings
- [ ] CustomHeadersSettings

**Comment by ryantxu** [comment]
I assume you mean "stop using them in grafana core" -- removing them from GrafanaUI should not happen without a few versions with a clear deprecation path.

**Comment by tskarhed** [comment]
Yes, they will still be usable for quite some time.
