### ISSUE TITLE
Dashboard: Data source requests in-flight putting save dashoard request and other requests in pending state

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#25859]
**What happened**:
Saving a dashboard and save dashboard modal hangs for a while. Not feedback is provided to the user what's going on. This also sometimes leads to user being logged out.

**What you expected to happen**:
Save dashboard request should happen instantly.and not interfere with data sources queries taking long time to complete.

**How to reproduce it (as minimally and precisely as possible)**:
1. Save a copy of the gdev dashboard: Panel tests - Slow Queries & Annotations
2. Open saved copy
3. While panels are loading, save the dashboard (opens save modal) and click Save button.
4. Save modal hangs and as can be seen in animation the save dashboard request are sent directly but put in pending state waiting for other requests to complete:
![save_dashboard_slow](https://user-images.githubusercontent.com/1668778/85841120-e9e3f280-b79d-11ea-97dc-ed7d601fb798.gif)

**Anything else we need to know?**:
Regarding that users can get logged out in this scenario I think that could happen if user auth token are rotated in data source query after save dashboard request have been put in pending state.

There are other things happening if for example going into dashboard settings when multiple lengthy dashboard queries are in progress.

Folder picker is spinning until queued get folders request is finished:
![image](https://user-images.githubusercontent.com/1668778/85841710-cbcac200-b79e-11ea-9f90-f59973205216.png)

Permissions view show dashboard doesn't have any permissions until queued get permission request is finished:
![image](https://user-images.githubusercontent.com/1668778/85841740-d9804780-b79e-11ea-895e-63f5b04eb7ad.png)

**Environment**:
- Grafana version: master (10715a1c79) and 7.0.4
- User OS & Browser: Chrome v83

**Comment by torkelo** [comment]
This has been a problem since v1 of Grafana, would probably require a big change to backenSrv so we do not use up all concurrent requests for data queries so other api requests do not get stuck in pending 

Do not think the change from angular http to fetch made any difference but maybe a subtle one that i cannot this of. The main problem of api calls being stuck in pending waiting for data queries to complete has been with Grafana since the start

**Comment by torkelo** [comment]
Will try to och explore ways to fix this in https://github.com/grafana/grafana/pull/25746  

But not sure we can get it done for 7.1,

There is a quick hacky fix of cancelling a In flight data query request if a non query api request comes in and all concurrent request slots are taken

**Comment by marefr** [comment]
Yeah just tried on older Grafana instance (6.3.5). One thing that was better in older versions was that the Save button changes to Saving... when clicked:
![image](https://user-images.githubusercontent.com/1668778/85864292-a2bd2800-b7c4-11ea-9f60-30350ee48a2b.png)

Clicking on cancel closes the modal, but it doesn't cancel the pending save dashboard request.

**Comment by Ultraseamus** [comment]
Being able to tell Grafana to only use all but one of the available concurrent request slots for data queries would be nice. Having big chucks of the UI become unresponsive when there are queries pending is not a good experience. If our data store is acting slow, users can actually become somewhat trapped on the home dashboard, waiting for the queries to finish before they can even view a list of the other available dashboards. Grafana kind of DOSs itself.
