### ISSUE TITLE
Elasticsearch: Add support for paginating logs in Explore

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#25876]
**What would you like to be added**:
Explore pagination.

**Why is this needed**:
Currently, only the most recent **500** number of log entries are shown and there is no way to navigate to the next batch of entries while keeping the time filter.

Using explore logs with elasticsearch.

**Comment by cdalexndr** [comment]
related: https://github.com/grafana/grafana/issues/28844

**Comment by Elfo404** [comment]
Closing this as it should be fixed by https://github.com/grafana/grafana/pull/33259.

also https://github.com/grafana/grafana/pull/32422 allows to set a different limit for log queries
