### ISSUE TITLE
Elasticsearch: Show an indicator of current displayed entries in Explore

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#25877]
**What happened**:
In the explore view only the most recent 500 entries are shown without any indication that there are any more entries in the selected timeline. 
This can make the user believe that there are no more entries in the selected timeline.

**What you expected to happen**:
Show an indicator of current displayed entries (like `showing recent 500 of 1999 entries`) and/or implement pagination (https://github.com/grafana/grafana/issues/25876).

**How to reproduce it (as minimally and precisely as possible)**:
Elasticsearch logs with a grafana timeline filter that shows more than 500 log entries.
Any entry after the **500** count will not be displayed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.3 (00ee734baf)
- Data source type & version: elasticsearch 7.8.0
- OS Grafana is installed on: docker
- User OS & Browser: Win10, Firefox 77.0.1
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Closing this as duplicated of https://github.com/grafana/grafana/issues/28844 which got a little bit more attention.
