### ISSUE TITLE
Gauge Color and Value Color are not behaving the same way.

### ISSUE THREAD

**Issue by aFacelessMan** [grafana/grafana#25870]
**What happened**:
When I create a gauge from the SingleStat Math Visualization, the color of the gauge and the color of the value do not abide by the same rules apparently.

**What you expected to happen**:
I would expect to have the gauge "bar" and the value to be at the same color and follow the same logic for coloring

**How to reproduce it (as minimally and precisely as possible)**:
Appears to happen on every gauge I create from SingleStat Math.

**Anything else we need to know?**:
This is occurring in both 6.7.3 and in 7.0.3

**Environment**:
- Grafana version:6.7.3/7.0.3
- Data source type & version: ElasticSearch
- OS Grafana is installed on: K8s, RHEL 7
- User OS & Browser: MacOS and Brave
- Grafana plugins:
- Others:
<img width="1161" alt="Screen Shot 2020-06-26 at 2 34 07 PM" src="https://user-images.githubusercontent.com/58482524/85890807-160e6c00-b7bc-11ea-99e0-f1062b2c8c0d.png">
<img width="1295" alt="Screen Shot 2020-06-26 at 2 41 44 PM" src="https://user-images.githubusercontent.com/58482524/85890814-1870c600-b7bc-11ea-9e72-31a2fc38dd6c.png">

**Comment by torkelo** [comment]
Please open a bug report with the SingleStat Math plugin: https://github.com/black-mirror-1/singlestat-math
