### ISSUE TITLE
Variables: Can't see hide option content in variable settings

### ISSUE THREAD

**Issue by KippaZou** [grafana/grafana#25879]
**What happened**:
- Can't hide option content in variables.

![image](https://user-images.githubusercontent.com/31032511/85942201-74715100-b95a-11ea-964c-bd469abbbfb3.png)

**What you expected to happen**:

- Hide option content in variables is displayed.

**How to reproduce it (as minimally and precisely as possible)**:

- Add variable and try to select hide option.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu
- User OS & Browser: safari
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What version of safari are you using? Can you upgradE?

**Comment by KippaZou** [comment]
> What version of safari are you using? Can you upgradE?

 The version is 13.1.1 (14609.2.9.1.3)

**Comment by torkelo** [comment]
problem is here:
Looks easy to fix, just add text to the labels 
https://github.com/grafana/grafana/blob/master/public/app/features/variables/editor/VariableEditorEditor.tsx#L184
