### ISSUE TITLE
Still showing the OLD VERSION NUMBER

### ISSUE THREAD

**Issue by Sofianov** [grafana/grafana#25872]
it is a simple bug and a bit annoying because it is there since a long time.

Whatever you update you still show old version number 
![image](https://user-images.githubusercontent.com/36585529/85917750-f46dbd00-b86d-11ea-8cb5-ef1883245930.png)

I am using ARM V7 version

Thank you

If you need more details  my email is flashsofian@gmail.com

**Comment by torkelo** [comment]
Unable to replicate: 

<img width="820" alt="Screen Shot 2020-06-28 at 08 23 40" src="https://user-images.githubusercontent.com/10999/85939821-b679a300-b918-11ea-82fb-82752c258376.png">

Try doing a full page reload? Have you restarted grafana-server? Visit a config page check footer , what version does it show?

**Comment by Sofianov** [comment]
That is very strange !! I have also restarted the server and set cache to
zero. this ghost been on since several 7xx version

thanks

[image: image.png]
