### ISSUE TITLE
7.0.4 Data Link repeated variable is not interpolated for the current value but instead shows "All"

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#25881]
I have a chart panel repeated for some variable.
I use data-links to navigate to some drill down dashboard.
When the variable shows "All" (so that the panel is repeated), the data-link interpolates the $variable to "all". Only when I chose a specific value for that variable (and then the "repeat" is "off") the variable is interpolated correctly for the data-link.

I also tried to repeat a "row" and store the panel as non-repeated in the row, and still I get the same results.

**Comment by torkelo** [comment]
@peterholmberg sorry for taking over this fix but I stumbled on it when doing ts null fixes, but then I remembered that we need this in a separate PR in order to cherry pick it https://github.com/grafana/grafana/pull/26147
