### ISSUE TITLE
Couldn't create stacked chart for Azure Log Queries

### ISSUE THREAD

**Issue by networkandcode** [grafana/grafana#25886]
Grafana version: 7.0
Stacked graphs are not working with Azure Logs queries, I tried different queries I can view normal graphs, but not stacked ones
![image](https://user-images.githubusercontent.com/30622440/85982030-a9ba8500-b9d4-11ea-9a0e-85a918cbd7ac.png)

![image](https://user-images.githubusercontent.com/30622440/85982577-9f4cbb00-b9d5-11ea-950e-d7359c058df6.png)

Sample query:
Perf
| where CounterName == 'cpuUsageNanoCores'
| where TimeGenerated >= ago(10m) 
| summarize sum(CounterValue) by Computer
| project now(), Computer, sum_CounterValue

**Comment by torkelo** [comment]
Try set null value option to null as zero. 

What does your query return?

**Comment by networkandcode** [comment]
no difference with null as zero when X Axis is in series mode, however I see is something like the following when I set the mode as Time
![image](https://user-images.githubusercontent.com/30622440/85986012-1769af80-b9db-11ea-9729-99e6cbfc7ad8.png)

I was actually looking to generate a straight vertical bar with blocks for each legend

**Comment by networkandcode** [comment]
I think this helps though, I could minimize the panel a bit
