### ISSUE TITLE
Issue with ldap connection/logging

### ISSUE THREAD

**Issue by wingZero21** [grafana/grafana#2588]
Hi,

I am attempting to connect to ldap via the ldap.toml file however when attempting login it seems to be failing.

I have enabled the verbose log however it does not seem to be logging out into the grafana.log.

Any ideas on what might be causing this issue to occur?

Details:
```
2015/08/24 09:23:46 [login.go:98 LoginPost()] [E] Invalid username or password: Invalid Username or Password
2015/08/24 09:23:46 [I] Completed /login 401 Unauthorized in 6.070595ms
2015/08/24 09:23:46 [I] Completed /api/login/ping 401 Unauthorized in 569.691µs
```

**Comment by torkelo** [comment]
This could be caused by failure (access denied) when trying to bind to the ldap server. Make sure the bind_dn and bind_password are valid.

**Comment by wingZero21** [comment]
Hi,

Detailed below is the current bind setup with the domain. I have tested authenticating with the user on another application and the credentials seem to be valid.

Does the config allow for spaces in the ou structure and a . within the username?

Also where does the verbose output go is this going to a different log somewhere?

```
bind_dn = cn=ldap.grafana,dc=this,dc=is,dc=a,dc=domain
bind_password = "************"
```

**Comment by torkelo** [comment]
added some more logging to bind failures

**Comment by wingZero21** [comment]
Hi,

This looks to be working now.
