### ISSUE TITLE
loki: Log level inference false matches

### ISSUE THREAD

**Issue by carlpett** [grafana/grafana#25887]
**What happened**:
When exploring logs from Loki, the log level is guessed from the line content (I assume?), which we're seeing misclassifying under certain circumstances. For example:

Classified as error (from [fluxcd](https://github.com/fluxcd/flux/)):
`{"caller":"sync.go:605","cmd":"kubectl apply -f -","err":null,"method":"Sync","output":"helmrelease.helm.fluxcd.io/[...lots of data...]`

Classified as trace (from GKE stackdriver-metadata-agent):
`I0629 08:00:00.385780       1 trace.go:897] Failed loading config; disabling tracing: open /export/hda3/trace_data/trace_config.proto: no such file or directory`

**What you expected to happen**:
In the first example, probably `unknown`? This would require deeper inspection of the line than just string-contains, though.
In the second example, if klog format is supported, should pick up `info` (leading `I`), otherwise unknown.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Loki
- OS Grafana is installed on: GKE Linux
- User OS & Browser: Linux/FF76
- Grafana plugins: -
- Others: -

**Comment by ivanahuckova** [comment]
@carlpett I have added documentation https://github.com/grafana/grafana/pull/28975 to make it more clear how do we extract and determine log level. I hope it helps - so you can adjust logs in a way that Grafana will be able to determine its log level. There is already also an issue regarding supporting custom log levels https://github.com/grafana/grafana/issues/25585 - so if you think something like this would be helpful, please feel free to upvote it, as with parsing of log messages, it would be very hard and error-prone to specify all the rules in a way that it would work for everyone.
