### ISSUE TITLE
Grafana 7.x cannot change the format date by setting the unit in

### ISSUE THREAD

**Issue by gaimereil** [grafana/grafana#25884]
**What happened**:
![image](https://user-images.githubusercontent.com/6457935/85977188-acd26700-ba0e-11ea-858e-e409847e5381.png)
![image](https://user-images.githubusercontent.com/6457935/85977213-bb208300-ba0e-11ea-8494-f72fd58cddae.png)
I try to change the format like the captures, but it doesn't work.
**What you expected to happen**:
work as the described in the release note.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Postgresql 10
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: table
- Others:

**Comment by gaimereil** [comment]
![image](https://user-images.githubusercontent.com/6457935/85977401-1eaab080-ba0f-11ea-8b9a-aafabd9e26df.png)
additional capture.

**Comment by torkelo** [comment]
What format is your data field in? Can you  open query inspector and show the result of your raw query?

**Comment by marefr** [comment]
Was just looking at this. Probably string. Used the following:
```json
{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1593398551994",
      "to": "1593420151994",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 60000,
          "maxDataPoints": 871,
          "datasourceId": 61,
          "rawSql": "SELECT CURRENT_TIMESTAMP as \"a\", CURRENT_TIMESTAMP as \"b\"",
          "format": "table"
        }
      ]
    }
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "executedQueryString": "SELECT CURRENT_TIMESTAMP as \"a\", CURRENT_TIMESTAMP as \"b\"",
          "rowCount": 1
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "a"
              },
              {
                "text": "b"
              }
            ],
            "rows": [
              [
                "2020-06-29T08:42:32.010701Z",
                "2020-06-29T08:42:32.010701Z"
              ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "executedQueryString": "SELECT CURRENT_TIMESTAMP as \"a\", CURRENT_TIMESTAMP as \"b\"",
              "rowCount": 1
            }
          }
        ],
        "dataframes": null
      }
    }
  }
}
```

Think this worked on earlier Grafana versions, but need to verify that.

**Comment by therealcodlord** [comment]
This seems to be the same issue that is still a problem for some people and still being discussed in this (CLOSED) issue:
https://github.com/grafana/grafana/issues/24917

I am running the latest (at time of writing) nightly build grafana_7.1.0~62bff84bpre_amd64 and with a MySQL datasource the date/time formatting only seems to work if I select UTC `seconds since` date/time values e.g. by doing:
`select UNIX_TIMESTAMP(datetime)*1000 as 'Date/Time' from...`

And then either choose one of the pre-defined date/time formats or enter a custom format with the `time`: prefix like:
`time: DD/MM/YYYY`

You didn't have to do **either** of those things with on the old table panel for date formatting to work with MySQL which is why users are reporting this and having issues. I don't know if that means there are still bugs in the new table panel or if the above method is now just the way it is? e.g. does the new table panel **ONLY** support UTC `seconds since` date/times being selected? If so this should be made clear in documentation.

**Comment by gaimereil** [comment]
> What format is your date field in? Can you open query inspector and show the result of your raw query?

![image](https://user-images.githubusercontent.com/6457935/86070919-777e5580-bab0-11ea-85ee-c6fa08ad98c6.png)

**Comment by therealcodlord** [comment]
In my case the source MySQL field is `datetime`.

**Comment by gaimereil** [comment]
In postgresql, the datatyppe is timestamptz

**Comment by frdve** [comment]
In MS SQL, I can fix this by setting the name of the field to 'time' in the query, but just as this example, I have 2 columns where the time mapping should happen and I cannot set 2 fields to 'time'.  
In the example below, the 'dg.Lastreceivedheartbeat' which is mapped to 'time' formats correctly to a time format, but the 'dg.CreatedOn' not...

```
SELECT 
  dg.SerialNumber AS 'DucoGateway',
  dg.CreatedOn AS 'First data',
  dg.Lastreceivedheartbeat AS time

FROM 
  DucoGateways AS dg
```
![afbeelding](https://user-images.githubusercontent.com/66672043/86327613-e344f780-bc43-11ea-89f0-2a2b0d21314f.png)
(note, I changed the title of the 'time' column in overrides to 'Last heartbeat')

**Comment by torkelo** [comment]
@ryantxu think we need to improve (or add) date in strings type & parsing to DataFrame , not sure where this should be though

**Comment by frdve** [comment]
A little note which I don't know is important, but this bug is categorized under area/backend/db/postgres, but this is probably a general issue and not only postgres?

**Comment by torkelo** [comment]
yes, think it's a general issue

**Comment by marefr** [comment]
>  improve (or add) date in strings type & parsing to DataFrame

To begin with, when selecting unit for parsing date it should parse strings.

**Comment by torkelo** [comment]
yes think you are right

**Comment by PabblRepos** [comment]
Grafana 7.0.5 on ElasticSearch 6.0 DataSource:
- Time formatting is not working if @timestamp is NOT the last bucket.
- Time formatting is working if @timestamp is the LAST bucket.
However, when time is within the current day, YMD are omitted.

**Comment by bhozar** [comment]
I'm seeing the same issue on 7.1 on the new table panel. Not a problem in 7.1 on the old table panel.

Datesource: ElasticSearch 7.8

Query inspector shows: @timestamp:"2020-07-17T19:21:26.201Z"

**Comment by JohnnyBee2** [comment]
I confirm:
Grafana 7.1
Datesource: ElasticSearch 7.8
@timestamp: "2020-07-21T06: 19: 52.000Z"
