### ISSUE TITLE
Feature Requests: Hide panel dropdown in grafana

### ISSUE THREAD

**Issue by ajayit28** [grafana/grafana#25894]
**What would you like to be added**:
I want to hide/remove the dropdown which appears on hovering mouse on panels when viewing in kiosk mode. Below are the screenshots of dropdown which I want to hide.

![image](https://user-images.githubusercontent.com/19976903/86001602-bf5b9900-ba2c-11ea-8771-1b367f15c878.png)

**Why is this needed**:

I want to hide these options to show to end-users.

**Comment by marefr** [comment]
Duplicate of #7450
