### ISSUE TITLE
Add globalTag by templating

### ISSUE THREAD

**Issue by HallsHalls** [grafana/grafana#2589]
My database use OpenTSDB, I have a new issues to add globalTags .
For example, I have many graph and those of  metric's tag  was  Hostname=*  , if I want to lookup one machine. I must change every graph every Tags. So I want to add globalTags to help me resolve this problem.

At this time , i found that there have templating. 

And already try to use ,but it doesn't work.
````java
tag_names(cpu)               (work ,but nothing react)
tag_values(cpu, hostname)    (dosen't work)
````

```json
Query = tag_names(system.cpu.idle{Hostname=*})

{"type":"LOOKUP","metric":"system.cpu.idle","tags":[{"key":"Hostname","value":"*"}],"limit":25,"time":1.0,"results":[],"startIndex":0,"totalResults":0}
```

**Comment by torkelo** [comment]
You need to enable the OpenTSDB setting `tsd.core.meta.enable_realtime_ts ` for the OpenTSDB lookup api to work

**Comment by HallsHalls** [comment]
yeah. got it
