### ISSUE TITLE
Viewer Role - Prevent user from creating new dashboard

### ISSUE THREAD

**Issue by BabuBhatt** [grafana/grafana#2590]
Hi,
First of all, thank you for creating the viewer user role for grafana!

While playing around in grafana as a viewer I realized that I was able to create new dashboards (and graphs within this temp dashboard). I'd like to prevent viewers from being able to create new dashboards as this will allow them to get into the "backend" of grafana. Can the viewer role be locked down so that they will not be able to create/import new dashboards;

![snap](https://cloud.githubusercontent.com/assets/13943455/9438866/310bc09a-4aa5-11e5-9d71-8c03f0810ae4.png)

This will be helpful in situations where grafana is presented to management/non-technical users or setup in a public kiosk environment.

**Comment by torkelo** [comment]
Ok, these buttons are hidden now. 

Just a heads up, the Viewer role does not prevent someone who knows http to make any query against you time series store. Grafana will just proxy the metric request, so a user with Role viewer can send any metric request to Graphite, or InfluxDB (what ever you have) if they really wanted to.
