### ISSUE TITLE
Panel Inspect: Crash when applying transform makes the current dataframe disappear

### ISSUE THREAD

**Issue by tskarhed** [grafana/grafana#25904]
**What happened**:
1. Apply the Outer join transform
2. Open the panel inspector
3. Change dataframe to antyhing other than the first two
4. Crash
![Peek 2020-06-29 17-16](https://user-images.githubusercontent.com/1438972/86023855-86bbbf80-ba2c-11ea-96c3-3a5fde5534ed.gif)

**What you expected to happen**:
If the Data Frame does not exist after the transformation, it should default ot the seriesToColumns option.

**Comment by dprokop** [comment]
Fixed with #25924
