### ISSUE TITLE
Value groups/tags regexp/substring support

### ISSUE THREAD

**Issue by nikut** [grafana/grafana#2591]
I'm really liking the new multi-value template variables and repeating rows/panels in 2.1.3 but the value groups/tags feature seems to be lacking some important functionality. 

Basically we have a bunch of hosts named according to the pattern "service-servertype-instancenumber" (or something similar to that) and we collect OS metrics from them using collectd and store it in Graphite. I would like to use the "service" part of the hostname as a tag and have it match all servers starting with that string. However I cannot find any way to use a part of a Graphite node as a tag.

No matter what I try, I cannot get this approach working:

``Tags query: aliasSub(collectd.*, "^(\w+)-.*", "\1")``
``Tag values query: collectd.$tag-*``

This gives me no tags at all. I also tried entering the list of "service" tags manually:

``Tags query: {serviceA,serviceB}`` (and other variations of this theme)

For some reason I can only get one service working this way, the others simply do not show up as tags.

Is there a way to achieve this currently? If not, I would like to submit this as a feature request. Thanks!

**Comment by torkelo** [comment]
are you sure graphite returns anyting for this metric find query? `aliasSub(collectd.*, "^(\w+)-.*", "\1")`

If you do not see any tags, that is probably because graphite does not return anything for `aliasSub(collectd.*, "^(\w+)-.*", "\1")`, and that is because that is not a valid graphite metric exploration (find) query. You cannot use graphing functions in metric find queries (only wildcard and glob expressions)

**Comment by nikut** [comment]
You may well be right, but if that is the case, how can I use a part of a Graphite node as a tag? Could we have a regexp similar to the "Value options" section?

**Comment by torkelo** [comment]
@nikicat no, but you can request regex feature graphites metric find api. 

Or switch your metric layout so that it has a dot

**Comment by nikut** [comment]
I still think a regexp similar to the "Value options" section to take only a part of the elements returned by the tags query would be really useful. I can think of many situations where one might want to group/tag metrics based on a part of a Graphite node or other metric element. 

I don't see this as being limited to Graphite alone, I believe it would be useful with other backends as well. One of the strengths of Grafana is that it's so flexible and able to fit into many kinds of existing metrics infrastructures and not having this possibility kind of goes against that.

It may not always be possible to design the metrics layout so that it would provide suitable tags "out of the box" and having to change an existing layout in order to be able to make use of a new feature would be quite an undertaking.

If that's not possible, could we at least have the possibility to manually enter a list of tags? That would solve my current use case.

**Comment by Qtax** [comment]
@torkelo, same problem for ElasticSearch I guess.

Eg. you want to base your tags on available server names. So as tags query you have to start from the server names. You get a list of server the first server in each group: `web-01`, `app-01`, `db-01`. But you cannot use these in the tag values query to get all servers of the group. I.e. you can't search for something with `web-01` when you want to get `web-*` = `web-01`, `web-02`, `web-03`, etc.

If you allowed some kind of editing of the names returned by the tags query (eg a regex replace, client side, `name.replace(/-\d+$/, "")`), we could end up with `web`, `app`, `db` instead. Those could easily be used in the values query to find all server names containing those values.

Or just allow us to enter tag names without a query. The tags values query could still be used as today.

**Comment by jimpriest** [comment]
Running into similar issues.  Value groups/tags  could definitely be documented a bit better.

**Comment by epa095** [comment]
For what it is worth we are in exactly the same situation as others here. Why have the "regex-extract" for the values but not for the tags? Without being familiar with the code it seems like it should be easy enough to enable the same post-processing for the tags as for the values, and it would make a world of difference for us.
