### ISSUE TITLE
Loki: Legend formatting not using scopedVars (repeated vars) 

### ISSUE THREAD

**Issue by jk2K** [grafana/grafana#25919]
**What happened**:

Legend configuration is not work when using Repeat by variable

![image](https://user-images.githubusercontent.com/4025839/86080132-bfa77300-bac4-11ea-9bfd-3a5631867694.png)

**What you expected to happen**:

Legend work,

![image](https://user-images.githubusercontent.com/4025839/86079773-ddc0a380-bac3-11ea-99d5-91e9e74cdb6c.png)

similar to

![image](https://user-images.githubusercontent.com/4025839/86079870-1c565e00-bac4-11ea-8a2a-78f82e08210e.png)

**How to reproduce it (as minimally and precisely as possible)**:

- Prometheus
- Grafana 7.0
- Stat Panel
- Repeat by variable, 

**Anything else we need to know?**:

same problem: [Extract labels values from prometheus metrics](https://community.grafana.com/t/extract-labels-values-from-prometheus-metrics/2087/13)

**Environment**:
- Grafana version: docker grafana/grafana:7.0.3
- Data source type & version: docker prom/prometheus:v2.19.1
- OS Grafana is installed on: docker
- User OS & Browser: macOS 10.14.6, chrome Version 83.0.4103.106
- Grafana plugins: no
- Others:

**Comment by torkelo** [comment]
Problem is here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts#L240 

The scopedVars is not passed to result transformer and this replace function (that does the interpolation)
