### ISSUE TITLE
Azure monitor - dimension as variable

### ISSUE THREAD

**Issue by mazhead** [grafana/grafana#25911]
**What would you like to be added**: 
Azure monitor -> dimension as variable. Information can be found also in this issue https://github.com/grafana/azure-monitor-datasource/issues/125 
Not sure which repository to open issues in (here or there).

**Why is this needed**: 
This would be useful when filtering out for example scale sets or selecting a specific disk.

I did not find any documentation on this and testing out did not bring any results.

**Comment by florianrusch** [comment]
@mazhead I think this is the right repo to post the issue (see [README.md](https://github.com/grafana/azure-monitor-datasource#azure-monitor-data-source-for-grafana-deprecated---now-included-in-core-grafana) of the other)

And btw, I found a solution 🎉 
You can write in the query field of the variable a Kusto Query (Azure Log Analytics Query).

In my case for a dimension on a custom metric:

```kusto
app('<ID_OF_APP_INSIGHTS>').customMetrics
| where name == "any_metric_where_dimension_exists"
| summarize by tostring(customDimensions.my_dimension)
```

But now I'm struggling at the usage of the variable. E.g. if you use the service `Application Insights` for a graph, you can just do one group by...in my case I will do a group by on a dimensions A and also filter the datapoints on a second dimension B via a variable which seems to be not supported...too bad. Looks like I also have to write a Kusto Query here instead 😕

**Comment by papagian** [comment]
@mazhead does the above suggested solution solves your issue? Can we close this issue?

**Comment by mazhead** [comment]
@papagian / @florianrusch  I am not able to make it work :/ 

I am mainly working with scale sets and I want ultimately be able to make per VM (template variable selector).

Problem is that in the dimension I will need the Resource Name and ResourceID in a format: ResourceName_ResourceID

The Kusto Query gives me the ResourceID what is fine (for example 0 / 1 / 2).
![image](https://user-images.githubusercontent.com/1275672/86749689-ba56a500-c03d-11ea-9b15-d5e02b2fd1ba.png)

I have the ResourceName from another query: ResourceNames($ResourceGroup,Microsoft.Compute/virtualMachineScaleSets)
![image](https://user-images.githubusercontent.com/1275672/86749569-a4e17b00-c03d-11ea-8a6d-a9ee86af5764.png)

But in the final query (this case CPU usage):
![image](https://user-images.githubusercontent.com/1275672/86750015-f38f1500-c03d-11ea-899d-d5ab6cde88d7.png)

When I look inside the query editor I get:
rawQuery:"%24filter=VMName+eq+%27%7BCORRECT_RESOURCE_NAME%7D_%7BCORRECT_RESOURCE_ID%7D%27&

The problem to me seems that grafana adds %7B (what is the '{') character to the query but in fact it should only expand.

**Comment by mazhead** [comment]
When I use the "old / do not use" format:
[[ResourceName]]_[[VM]]
It works, so maybe this issue should be transferred to a bug about '{' '}' been send to AzureMonitor query.

**Comment by Elfo404** [comment]
@mazhead I think you might be using the wrong syntax.
When interpolating variables inside an expression (which is your case) the correct syntax is `${variableName}`.
In your case, it should be `${ResourceName}_${VM}`.

This might help https://grafana.com/docs/grafana/latest/variables/templates-and-variables/#variable-syntax
