### ISSUE TITLE
Stats panel not showing legend if row is equal to 1

### ISSUE THREAD

**Issue by danielbjornadal** [grafana/grafana#25927]
**What happened**:
Stats panel not showing legend if row is equal to 1
![image](https://user-images.githubusercontent.com/7441428/86102638-0f357100-babc-11ea-9298-4a03352bcdd8.png)

**What you expected to happen**:
That legend shows on 1 row
![image](https://user-images.githubusercontent.com/7441428/86102928-6d625400-babc-11ea-95bf-e29d03dd1aa6.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a stats panel
2. Create a prometheus query that contains 1 row (example: `(sum by (namespace,deployment) ((kube_deployment_status_replicas != 0) - kube_deployment_status_replicas_unavailable) == 0) OR on() vector(99)`)

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Prometheus 2.17.2
- OS Grafana is installed on: Docker image from official Grafana repo
- User OS & Browser: Chrome 81.0.4044.138 (Official Build) (64-bit)

**Comment by torkelo** [comment]
specify `${__series.name}` in Field -> Display name. 

But will also be solved in a better way with https://github.com/grafana/grafana/pull/25676
