### ISSUE TITLE
Template variables not working in automatically loaded dashboards

### ISSUE THREAD

**Issue by kportertx** [grafana/grafana#2592]
I'm using:

```
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards
```
These dashboards have template variables that are set to automatically update on each dashboard reload, but they don't seem to reload. Even stranger is that I created a copy of one of the dashboards and the template variables still do not reload. I suspect user error but cannot find my error.

**Comment by torkelo** [comment]
can you show me the json of the dashboard (maybe redacted for sensitive info). Does the template variables have `refresh: true`

**Comment by kportertx** [comment]
I actually just found the issue. Some of my metrics are not coming in and the template variables in this case depended on these metrics. Missed this all of Friday and didn't become obvious until shortly after asking. Thanks for your quick response.
