### ISSUE TITLE
Query options max data points is not respected when interval should be larger than 1d.

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#25933]
**What happened**:

Interval computed by `Query Options` cannot be larger than `1d`. It implies that an answer might return more data points than `max data points`.

**What you expected to happen**:

If `max data points` is set, it should be respected. This limitation seems both arbitrary and error prone. 

Example: My use case was to compute an aggregate over the whole time range and display it using a bar gauge. As I was not expecting to get more than one data point I used _last not null_ reducer which resulted in displaying a bogus value.

**How to reproduce it (as minimally and precisely as possible)**:

In _Query options_ :
 1. Set `Max data points` to 1
 1. Set `Relative` time to 48h

![image](https://user-images.githubusercontent.com/1764725/86113437-8d4c4480-bac9-11ea-8b00-925462b73b02.png)

Observe that computed interval is `1d` rather than 48h. Same thing happen when a large time range is set (ie. this does not come from setting a relative time).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3

**Comment by torkelo** [comment]
the max data points and interval are not exact, as the interval is rounded to an even value (for example 1.12d is not something Grafana will do)

**Comment by torkelo** [comment]
related to this https://github.com/grafana/grafana/issues/6724

**Comment by cykl** [comment]
Then _Max data points_  might not be an accurate description of this setting as max usually implies an upper bound. I can see two options:

 - Rename the setting / improve the tooltip.
 - Rework the rounding the ensure that max is respected.
