### ISSUE TITLE
SHIT UI 7.x versions....

### ISSUE THREAD

**Issue by Nurlan199206** [grafana/grafana#25943]
grafana 7.x release worse than 6.x....

why i must expand every shit menu? 

![Снимок экрана 2020-06-30 в 20 42 19](https://user-images.githubusercontent.com/22808731/86140283-85fd5900-bb12-11ea-9dab-c2baca59fe32.png)

![Снимок экрана 2020-06-30 в 20 43 26](https://user-images.githubusercontent.com/22808731/86140314-8d246700-bb12-11ea-8212-fa170d864dfc.png)

**Comment by torkelo** [comment]
First negative feedback on 7.0 UI changes :) this one we already know of.  we will add expand all action the sidemenu, was cut from 7.0 due scope to get the release out.
