### ISSUE TITLE
Upgrading 2.1.3-1 breaks custom URL (CentOS)

### ISSUE THREAD

**Issue by poblabs** [grafana/grafana#2594]
On CentOS 6, I upgraded from 2.1.1-1 to 2.1.3-1 and my custom URL of http://domain/stats URL broke. Config file still showed it as being /stats, but I was getting a 404 error on the app.js file. 

I performed a yum history undo, and I'm back to a working 2.1.1-1

Just wanted to report it. 

Thanks

**Comment by torkelo** [comment]
did you restart the grafana-server after upgrade? This sounds like you were still running the old binary
