### ISSUE TITLE
[Enhancement] Datasource Provisioning : File or global reference to certificates

### ISSUE THREAD

**Issue by m-a-leclercq** [grafana/grafana#25945]
Hi team !

This enhancement request is on the management of the datasource provisioning and the way it handles tls certs and keys for multiple datasources. 

**What would you like to be added**: 
I would like to be able to either :
- reference a file on disk for `tlsCACert`, `tlsClientCert`, and `tlsClientKey` props (nested inside `secureJsonData`)
- define a global value for `tlsCACert`, `tlsClientCert`, and `tlsClientKey` props (this would require a way to override these values in each datasource if needed)

**Why is this needed**:
The datasource provisioning current model makes `datasource.yml` very redundant in its current state (most grafana installations are going to use only one value for these props). Since the whole content of the certs needs to be dumped inside the yml file, it makes it very difficult to adjust manually using command line editors such as vim. 
Our current prod installation of Grafana has over 120 datasources that are all secured using these 3 props, this, in turn means our datasources.yml file is over 25 MB and restarting grafana takes around 25-30 seconds because of this.  (I understand this is another issue, I imagine the provisioning blindly reinjects all data without checking if what's in the DB is already correct)

Thank you for your time and input on this enhancement request !

**Comment by papagian** [comment]
> reference a file on disk for tlsCACert, tlsClientCert, and tlsClientKey props (nested inside secureJsonData)

This is already supported by #25075 and #25692 and will be included in the next release.

**Comment by m-a-leclercq** [comment]
Alright, looks good to me. Thanks!

**Comment by skensell201** [comment]
What version did this feature come in? Substitute in tlsCACert path to file
Example
apiVersion: 1
datasources:    
  - name: "name_datasource"
...
    secureJsonData:
      password: verystrongpass
      tlsCACert: /certs/mycerts/ca.pem

**Comment by erikschul** [comment]
@papagian 

There's no documentation of how to reference certificate files, if that's a supported feature.
I'm provisioning data sources as Kubernetes ConfigMaps and mount Kubernetes secrets as certificate files.

https://grafana.com/docs/grafana/latest/administration/provisioning/

Is @skensell201 's example correct? Could this be added to the documentation?
