### ISSUE TITLE
Feature Request: Embed query result within text panel

### ISSUE THREAD

**Issue by BabuBhatt** [grafana/grafana#2595]
Apologies if this has been suggested/mentioned before;

I require the ability to embed query results within text panels (similar to single-stat panels). This will give me the freedom to format the layout of metrics by using html/markup. For example I would be able to display min/max/avg/current values within a html table. This could be implemented by users referencing a query variable within the text panel (similar to template variables, e.g. $variable).

**Comment by Jorge-Rodriguez** [comment]
:+1:

**Comment by The-Nik** [comment]
Nice idea :)

**Comment by sslupsky** [comment]
I believe you can do this ... i tried displaying a local variable ($variable) in a text panel and it works.  What would be nice though is if we could query a string from the database and display it in a text panel.  This would be very helpful useful for templating titles and descriptions and observations for panels and dashboards.

**Comment by teo96** [comment]
+1

**Comment by torkelo** [comment]
there is a table panel that can be used, if you need to display metrics data in custom panel, 
http://docs.grafana.org/plugins/development/ :)
