### ISSUE TITLE
Templating: Multi-value variable rendrered using __value instead of __text after selection changes

### ISSUE THREAD

**Issue by MatheusKProt** [grafana/grafana#25959]
**What happened**:
On the variable __text is replaced by the __value.
![tela](https://user-images.githubusercontent.com/13322757/86208116-510af980-bb46-11ea-930f-9e580a1c1d21.gif)

**What you expected to happen**:
Keep the __text.

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/13322757/86207611-4ac84d80-bb45-11ea-86f0-b64b7ffb02d1.png)
![image](https://user-images.githubusercontent.com/13322757/86208501-0fc71980-bb47-11ea-9277-dd6b5d10c5f7.png)
![image](https://user-images.githubusercontent.com/13322757/86207692-6cc1d000-bb45-11ea-9963-a201e198f161.png)

**Anything else we need to know?**:
This only happens with the multi-value selected.

**Environment**:
- Grafana version: v7.0.5 (efbcbb838b)
- Data source type & version: PostgreSQL
- OS Grafana is installed on:  Debian GNU/Linux 9.12 (stretch)
- User OS & Browser: Windows Google Chrome
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
[Example dashboard](https://gist.github.com/papagian/7542838840af6f73dcc35cca0b772eb8) to reproduced.

There is a similar open [issue](https://github.com/grafana/grafana/issues/25711) for MySQL datasource. Probably the solution will apply for both.
