### ISSUE TITLE
UI - Add note to Data Source panel that Elasticsearch does not support metrics

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#2596]
ref. #1392 Grafana doesn't support Elasticsearch for metrics. However, the **Edit Data Source** window doesn't indicate this -- it's the exact same as for another data source that _does_ provide metrics (such as influxDB).  

Suggest that a note is added to remind the user that Elasticsearch cannot provide metrics to save confusion when trying to build a dashboard and Elasticsearch not appearing on the data source dropdown list.

**Comment by torkelo** [comment]
instead of dong this decide to do this, https://github.com/grafana/grafana/issues/1034#issuecomment-137467692 

:)

**Comment by rmoff** [comment]
Awesome :+1:
