### ISSUE TITLE
Uncaught (in promise) RangeError: Maximum call stack size exceeded in 7.0.4/7.05

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#25975]
I have complex dashboard containing large amount of template variables, tens of rows where each row might contain number amount of different panels, sometime with repeating rows. This worked perfectly in 6.4.3 and 7.0.3.

When same dashboard is run in 7.0.4 and I switch time range from last 1h to last 3h as example the Maximum call stack size exceeded error is thrown and dashboard completely freeze and/or never recover.

From Console I can one or error like below. 
runtime.js:423 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at new j (runtime.js:423)
    at Object.u [as wrap] (runtime.js:23)
    at Object.e (adapter.ts:29)
    at app.7b506073f46893460c0d.js:2
    at new Promise (<anonymous>)
    at Object.<anonymous> (app.7b506073f46893460c0d.js:2)
    at Object.setValueFromUrl (adapter.ts:29)
    at actions.ts:459
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)

To narrow down the problem I removed all the rows and panels. Thus only template variables are left and it still failed when time range is changed. 
To further narrowed the issue down I removed half of the template variables and once I remove "variable type" prometheus adhoc" the time range change started to work.

But once AdHoc was removed the the first time range change works but when going to settings/variables result similar errors (seems that templates are updated) result.

runtime.js:263 Uncaught (in promise) RangeError: Maximum call stack size exceeded
    at Generator._invoke (runtime.js:263)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at Ot (app.7b506073f46893460c0d.js:2)
    at i (app.7b506073f46893460c0d.js:2)
    at app.7b506073f46893460c0d.js:2
    at new Promise (<anonymous>)
    at Object.<anonymous> (app.7b506073f46893460c0d.js:2)
    at Object.setValue (adapter.ts:24)
    at actions.ts:239
    at c (runtime.js:45)

With full dashboard all queries will after second error like

tti-polyfill.js:4 GET http://address:port/api/v1/query?query=removedquery&time=1593601626&timeout=90s net::ERR_INSUFFICIENT_RESOURCES

Sounds that the is some major regression between 7.0.3 and 7.0.4 in template variable population which make Grafana 7.04 -> unusable.

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

**Comment by jtorkkel** [comment]
7.1.0-beta2 fails too.

I suspect this happens when number of variable in single template variables is large, like few hundreds. Having tens of template variable each having on average few hundreds variable result few thousand variables probably resulting OOM.

**Comment by torkelo** [comment]
could be fixed by https://github.com/grafana/grafana/pull/26137

**Comment by torkelo** [comment]
Grafana v7.0.6 released with a fix for this, hope it solves it!

**Comment by jtorkkel** [comment]
Works now, thanks
