### ISSUE TITLE
Prometheus api warnings are invisible to end-users

### ISSUE THREAD

**Issue by vsliouniaev** [grafana/grafana#25972]
**What would you like to be added**:

When prometheus is not able to fetch data from all downstreams it displays a warning message in its interface and returns a warning as part of the API response. This message is not visible to end-users without going into the query inspector. Theoretically the API could return this information in more cases than just inability to fetch remote-read data.

**Why is this needed**:

Incomplete data can cause someone to make decisions based on a calculation involving only a part of the data.

**Comment by bohandley** [comment]
We can see the importance of this and will revisit this when we have capacity.

**Comment by vsliouniaev** [comment]
I don't believe that going into the query inspector really counts as a workaround, since the information is not visible by default and may produce incorrect data.

**Comment by bohandley** [comment]
I hear you on that @vsliouniaev, I will tag issue on a possible Q4 goal our squad is discussing, which is around more accurate Prometheus error handling. Thank you!
