### ISSUE TITLE
Select database depending on zoom

### ISSUE THREAD

**Issue by markusr** [grafana/grafana#2597]
I am using grafana with influxdb 0.9.
I have one database which contains the measured data (seconds resolution) and then 2 continuous queries to down sample the data to 1 hour and 1 day.

It would be nice to have a single graph. If want to see the monthly overview grafana will query the 1 day database. If I zoom in first the 1 hour values are shown and then at the highest zoom level the second data.

The edges (where to use which database) could be given manually or determined automatically.

**Comment by torkelo** [comment]
What does your continous queries look like? I am waiting for some best practice generic way to do roll ups in InfluxDB 0.9 to implement some convention so that grafana will change the query based on time period to query a different retention policy. 

ping @pauldix any progress on this? I feel the user experiance for InfluxDB really sucks in grafana due to no generic / standard rollups scheme.

**Comment by markusr** [comment]
I use this:
```
CREATE CONTINUOUS QUERY "60min_means" ON "archive" BEGIN SELECT mean(value) INTO "archive"."policy_forever"."60min" FROM "live"."policy_2weeks"."data" GROUP BY time(60m), * END
```
I keeping the live data only for 2 weeks to save space.

**Comment by torkelo** [comment]
That is only for one measurement?
But if you have 10 000 measurements, do you need to create 10 000 Continous Queries? What happens with the tags?

**Comment by markusr** [comment]
This is for all measurements (series, tag combination) in ```"live"."policy_2weeks"."data"``` . The tags are kept. 

From https://influxdb.com/docs/v0.9/query_language/continuous_queries.html :
```To preserve all tags in your downsampled data, add a , * clause to the GROUP BY clause of the continuous query. ```

**Comment by torkelo** [comment]
Please put some pressure on InfluxDB to build a more generic way to do rollups (with conventions, few rules, etc). Then Grafana can take advantage of that and change retention policy depending on current time range. 

But for users to create a CQ for each measurement and roll up, and with not best practice or conventions from InfluxDB makes this feature really hard to do well in Grafana.
