### ISSUE TITLE
${__cell} and ${__cell_name} are not parsed in links in Grafana v7

### ISSUE THREAD

**Issue by frdve** [grafana/grafana#25986]
**What happened**: 
${__cell} and ${__cell_name} are not parsed in links.  This worked before Grafana 7.0

Configuration of links with data from table cells before Grafana 7.0
![afbeelding](https://user-images.githubusercontent.com/66672043/86211412-a8c15900-bb76-11ea-9209-a52403e645c0.png)

Configuration of links with data from table cells in Grafana 7.0
![afbeelding](https://user-images.githubusercontent.com/66672043/86212896-25edcd80-bb79-11ea-92a7-0c1bbccd1cea.png)
Cell text is not used in links...
![afbeelding](https://user-images.githubusercontent.com/66672043/86211146-29cc2080-bb76-11ea-9498-150e7fafb6a7.png)

**What you expected to happen**:
The links should be created with the info within the cells.  These links should change the variables.

**How to reproduce it (as minimally and precisely as possible)**:
Use ${__cell} or ${__cell_name} from a table in a link or title

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: MS SQL
- OS Grafana is installed on: Linux
- User OS & Browser: Windows/Firefox
- Grafana plugins: 
- Others:

**Comment by papagian** [comment]
I'm unable to reproduce it.
Does this happen for any column?
What is the content of these columns? Do they contain any special characters?
Can you share the query?

**Comment by torkelo** [comment]
For the new table panel and data links you refer other cells by the Field name (column name), example `${__data.fields[Min]}`

**Comment by frdve** [comment]
Thank you.  Using the new syntax did the trick.
