### ISSUE TITLE
Enhanced alias support for InfluxDB queries

### ISSUE THREAD

**Issue by mikechack** [grafana/grafana#2599]
When making a query to InfluxDB to a measurement that has multiple values such as "select sum(value1), sum(value2)....." - InfluxDB returns the column names as [sum,sum]. Would it be possible to auto generate a select statement such as the following select sum(value1) as sum.value1, sum(value2) as sum.value2 ? While it is possible to manually edit the query, I think it would be much more powerful if the structured query editor could handle this case.

**Comment by torkelo** [comment]
implemented :)

**Comment by torkelo** [comment]
Sorry, wrong issue

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9761585/0ab892f0-56fe-11e5-9763-969ee6b66369.png)

Implemented!
