### ISSUE TITLE
Docs: foldersFromFileStructure is not a valid option in dashboard.yml

### ISSUE THREAD

**Issue by ansjcy** [grafana/grafana#25995]
**What happened**:
Hi, I'm trying to provision the Grafana dashboards and keep the folder structure at the same time. On the documentation I found (https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards) both `foldersFromFilesStructure` and `foldersFromFileStructure` are used in the example. I'm confused about which one is the correct option to use. 

**How to reproduce it (as minimally and precisely as possible)**:
Tried `foldersFromFileStructure` but it doesn't seem to work.

**Anything else we need to know?**:
Feels like a documentation error.

**Environment**:
- Grafana version: 7.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
Thank you for reporting this. `foldersFromFilesStructure` is the correct one.
