### ISSUE TITLE
Change plot colour and axis in Explore view

### ISSUE THREAD

**Issue by millettmb** [grafana/grafana#26001]
**What would you like to be added**:
Currently, when viewing a graph in a dashboard, you can click on the coloured line near each query to change the colour of the line, as well as changing whether the query is plotted against the left or right y-axis, as seen below.
![image](https://user-images.githubusercontent.com/36942530/86318469-56b32d00-bc75-11ea-8f7e-13887128caab.png)

However, when using the Explore view, you cannot click on the coloured line to change the colour of the line, or whether it plots against the left or right y-axis.
![image](https://user-images.githubusercontent.com/36942530/86318589-b4477980-bc75-11ea-9838-31703a5f551b.png)

I would like to have the colour/y-axis popup to also work in Explore view.

**Why is this needed**:
Currently the explore view is difficult to use when comparing two values of varying magnitudes. This can be skirted around by multiplying or dividing values, but this is a bodgie fix at best. 

It could also be considered an accessibility issue, as it may be difficult to discern between queries if their colours are too similar.

**Comment by Elfo404** [comment]
relates to https://github.com/grafana/grafana/discussions/54158

**Comment by ifrost** [comment]
> relates to #54158

Discussion has been converted to an issue:  #73440

**Comment by ifrost** [comment]
We are not planning to work on this issue in the foreseeable future. Please upvote or comment if you would like it to be prioritized.
