### ISSUE TITLE
BUG: Datasource named -- Grafana -- was not found

### ISSUE THREAD

**Issue by baur** [grafana/grafana#26000]
**What happened**:

Welcome page

plugin_loader.ts:265 Error loading panel plugin: welcome SyntaxError: Unexpected token '<'
    at eval (<anonymous>)
    at le (system.js:4)
    at system.js:4
    at system.js:4
    at S (system.js:4)
    at x (system.js:4)
    at system.js:4

![image](https://user-images.githubusercontent.com/2898361/86313237-7848f000-bc46-11ea-8e78-b0be298f1e05.png)

Add new panel 

Uncaught (in promise) {message: "Datasource named -- Grafana -- was not found"}message: "Datasource named -- Grafana -- was not found"__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
k @ app.f079ffb601538975475e.js:2
i @ app.f079ffb601538975475e.js:2
Promise.then (async)
k @ app.f079ffb601538975475e.js:2
i @ app.f079ffb601538975475e.js:2
Promise.then (async)
k @ app.f079ffb601538975475e.js:2
o @ app.f079ffb601538975475e.js:2
(anonymous) @ app.f079ffb601538975475e.js:2
h @ app.f079ffb601538975475e.js:2
r.value @ app.f079ffb601538975475e.js:2
value @ app.f079ffb601538975475e.js:2
mc @ vendors~app.f079ffb601538975475e.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.f079ffb601538975475e.js:2
Wo @ vendors~app.f079ffb601538975475e.js:2
gc @ vendors~app.f079ffb601538975475e.js:2
ic @ vendors~app.f079ffb601538975475e.js:2
(anonymous) @ vendors~app.f079ffb601538975475e.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.f079ffb601538975475e.js:2
Wo @ vendors~app.f079ffb601538975475e.js:2
Ko @ vendors~app.f079ffb601538975475e.js:2
Yo @ vendors~app.f079ffb601538975475e.js:2
ac @ vendors~app.f079ffb601538975475e.js:2
notify @ vendors~app.f079ffb601538975475e.js:2
t.notifyNestedSubs @ vendors~app.f079ffb601538975475e.js:2
t.handleChangeWrapper @ vendors~app.f079ffb601538975475e.js:2
b @ vendors~app.f079ffb601538975475e.js:2
(anonymous) @ vendors~app.f079ffb601538975475e.js:2
dispatch @ vendors~app.f079ffb601538975475e.js:2
(anonymous) @ app.f079ffb601538975475e.js:2
c @ vendors~app.f079ffb601538975475e.js:2
(anonymous) @ vendors~app.f079ffb601538975475e.js:2
forEach.e.<computed> @ vendors~app.f079ffb601538975475e.js:2
s @ app.f079ffb601538975475e.js:2
i @ app.f079ffb601538975475e.js:2
Promise.then (async)
s @ app.f079ffb601538975475e.js:2
i @ app.f079ffb601538975475e.js:2
(anonymous) @ app.f079ffb601538975475e.js:2
(anonymous) @ app.f079ffb601538975475e.js:2
(anonymous) @ app.f079ffb601538975475e.js:2
(anonymous) @ vendors~app.f079ffb601538975475e.js:2
(anonymous) @ vendors~app.f079ffb601538975475e.js:2
value @ default~DashboardPage~SoloPanelPage.f079ffb601538975475e.js:1
mc @ vendors~app.f079ffb601538975475e.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.f079ffb601538975475e.js:2
Wo @ vendors~app.f079ffb601538975475e.js:2
gc @ vendors~app.f079ffb601538975475e.js:2
ic @ vendors~app.f079ffb601538975475e.js:2
(anonymous) @ vendors~app.f079ffb601538975475e.js:2
KqkS.t.unstable_runWithPriority @ vendors~app.f079ffb601538975475e.js:2
Wo @ vendors~app.f079ffb601538975475e.js:2
Ko @ vendors~app.f079ffb601538975475e.js:2
Yo @ vendors~app.f079ffb601538975475e.js:2
ue @ vendors~app.f079ffb601538975475e.js:2
Er @ vendors~app.f079ffb601538975475e.js:2

![image](https://user-images.githubusercontent.com/2898361/86313019-e7721480-bc45-11ea-9734-ea6bf47bfec0.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Exract ZIP file
- change port 
- run

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0-beta1
- Data source type & version: -
- OS Grafana is installed on: Windwos OS
- User OS & Browser: Chrome
- Grafana plugins: - 
- Others: -

**Comment by aknuds1** [comment]
Thanks for reporting, but this bug is fixed for the upcoming beta2 release.
