### ISSUE TITLE
Frequently logs me out when using MySQL+Galera

### ISSUE THREAD

**Issue by Wilm0r** [grafana/grafana#26008]
**What happened**:
On console refresh I get logged out very frequently.

Logs show me this around the time:

```
t=2020-07-02T07:57:48+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="Error 1213: Deadlock: wsrep aborted transaction"
t=2020-07-02T07:57:48+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=401 remote_addr=2001:470:7852:1000::6b6 time_ms=36 size=26 referer="https://prom.gaast.net/d/000000001/dump1090?orgId=1"
t=2020-07-02T07:57:48+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=2001:470:7852:1000::6b6 time_ms=0 size=26 referer="https://prom.gaast.net/d/000000001/dump1090?orgId=1"
t=2020-07-02T07:57:48+0000 lvl=info msg="Successful Logout" logger=http.server User=
t=2020-07-02T07:57:48+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/logout status=302 remote_addr=2001:470:7852:1000::6b6 time_ms=0 size=29 referer="https://prom.gaast.net/d/000000001/dump1090?orgId=1"
t=2020-07-02T07:57:49+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=wilmer path=/api/datasources/proxy/1/api/v1/query_range remote_addr=2001:470:7852:1000::6b6 referer="https://prom.gaast.net/d/000000001/dump1090?orgId=1" error="http: proxy error: context canceled"
t=2020-07-02T07:57:49+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=wilmer method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=2001:470:7852:1000::6b6 time_ms=1199 size=0 referer="https://prom.gaast.net/d/000000001/dump1090?orgId=1"
```

Core of the issue seems to be a Galera deadlock issue.

When I look at Grafana's TCP sockets around the time it happens, I see 5+ MySQL sockets open simultaneously, connecting to a mix of all my 3 Galera replicas.

I wonder whether reloading the console and particular all the graph data proxy'd through Grafana, kicks off several session ticket refreshes simultaneously and going through different Galera instances, making it pretty easy to hit a deadlock situation.

I've fixed this now by hardcoding my Grafana to connect to one specific Galera replica, but it would be nicer not to.

No clue whether the way these refreshes (assuming my guess on that is correct, of course) are indeed done in a way that causes legitimate deadlocks, or whether Galera is at fault here.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Prometheus 2.18.1
- OS Grafana is installed on: Docker image running on Debian stable
- User OS & Browser: Happens with Firefox on both Linux and iOS
mariadb-server-10.3               1:10.3.23+maria~buster
galera-3                          25.3.29-buster

**Comment by marefr** [comment]
Reading https://severalnines.com/database-blog/avoiding-deadlocks-galera-setting-haproxy-single-node-writes-and-multi-node-reads seems Galera has known limitations which is hard for Grafana to do anything about. Thanks, but we'll close this. As also explained in the referenced article another workaround is to use HAProxy.
