### ISSUE TITLE
Feature: Change Panel Edit link to Panel View link

### ISSUE THREAD

**Issue by robshep** [grafana/grafana#26014]
**What happened**: Telegram notification has an Edit Link (  ?editPanel=N )

**What you expected to happen**: URL should take me to view a panel ( ?viewPanel=N )

Some of our teelgram recipients are not editors.

**How to reproduce it (as minimally and precisely as possible)**: Setup a telegram notification channel and link an alert configuration

**Anything else we need to know?**:

**Environment**: Docker
- Grafana version: 7.0.4
- Data source type & version: influx
- OS Grafana is installed on: Docker? Alpine I think.
- User OS & Browser: Linux, Firefox
- Grafana plugins: N/A
- Others:

**Comment by robshep** [comment]
https://github.com/grafana/grafana/blob/5a4f69080702ad33145d5b09e13ee9ccc8cc9800/pkg/services/alerting/eval_context.go#L115

**Comment by mattparkes** [comment]
We also have this issue with the Slack integration.

I think it relates to this issue: https://github.com/grafana/grafana/issues/15439

With the changes to the UI made in v7.0, the `editPanel` view does not seem like a suitable default, as so much screen realestate is lost to the sidebar and bottom section. I'd much rather go straight to `viewPanel` and then click _Edit_ if I want to edit the panel (which I really can't understand why anyone would do more than occasionally).

**Comment by McAnix** [comment]
+1 on this as it affects my business users who don't have edit permissions.

**Comment by papovyr** [comment]
+1

**Comment by robertlestak** [comment]
+1 we similarly have business users who need to see alerts but do not have edit permissions.

**Comment by ksiebel** [comment]
+1

**Comment by williamdunstanmorris** [comment]
+1

**Comment by e-power** [comment]
+1

**Comment by Trofym** [comment]
+1

**Comment by mattparkes** [comment]
Can we please get a response from the maintainers if this is planned or not? It's seemingly a 4 character fi and if someone indicated that it was being considered, it might stop the annoying +1 spam.

**Comment by ikkemaniac** [comment]
It's working for me o 7.2.0-beta1
