### ISSUE TITLE
Table Panel: Add back pagination option  

### ISSUE THREAD

**Issue by jayemce** [grafana/grafana#26022]
Referencing https://github.com/grafana/grafana/issues/25969

**What would you like to be added**:
Table pagination

**Why is this needed**:
When working (reading/analyzing) tables with lots of records (example of 2000+) it is cumbersome to constantly scroll. It is much more comfortable to paginate. In addition the pagination allows to understand where exactly we are looking at the table, beginning, somewhere in the middle or end.
The table in V7 requires constant scrolling and when arriving at the bottom of the panel, to see the remaining records, the panel must be resized again and again to allow further scrolling ....

-> Feedback from my operations team using it every day.
-> With V7, operations started exporting the tables as CSV to allow for comfortable analysis.
-> We have switched back to V6 tables.

Having paginate as an option is a +.

**Comment by paregupt** [comment]
Totally agree. Having a scroll bar on a panel is not the best approach. Would love to have it back.

![image](https://user-images.githubusercontent.com/8773072/87073900-f4a57b00-c1d2-11ea-9593-b991f5f3eb10.png)

**Comment by daldoyle** [comment]
This would definitely be nice to have back. One issue with scrolling panels in general is when they are on a scrollable page, the user can get confused and/or experience poor UX when their cursor ends up scrolling the table when they meant to scroll the page. It does seem like there are some checks for this so that it doesn't snag the scroll as you're moving down the page, but on some layouts it's tricky to find a way to mouse out of the table to ensure that you're scrolling the page.

**Comment by craigta** [comment]
It is able to make use of the pagenation feature when copy/pasting an 'old' style table. But not when creating a net new table in the new format. Can the regression be fixed for new table?

**Comment by Nelluru-Hemasree** [comment]
How data links work in table panel?
How to pass current row data on clicking along with url?

**Comment by liangliangxiao** [comment]
Why do not support table paging？Disappointed ！😢

**Comment by baur** [comment]
In my case I'd like to use top row to drilldown panel via table DataLink
When user cursor ends up scrolling the table, the page being scrolled up, this time detail row is scrolls up and becomes invisible, very sad.

Team,
Please, return table pagination #32157 and ability to hide fields but still reference them in data links #24092

**Comment by caoqiang-github** [comment]
Hello, I'd like to ask about the progress of the pagination repair now, or are there any plans for the resolution at present?

**Comment by rgrullon** [comment]
We have a request from a paying customer regarding the progress of this issue. Is there any status changes I can provide? Thank you

**Comment by nbfowler** [comment]
Please bring back paging.

**Comment by torkelo** [comment]
Yay! we just merged paging, will be in the coming 8.5 release. 

Sorry that everyone had to wait so long for this.
