### ISSUE TITLE
Prometheus: Dashboard filters cause query failures when used on dashboards with dashboard variables of type "custom"

### ISSUE THREAD

**Issue by siebenmann** [grafana/grafana#26029]
**What happened**:

If you add filters to a dashboard (for example through the table 'filter for value' and 'filter out value' feature on rows) and your dashboard has a dashboard variable of type "custom" (to pick one option from a list, for example), Prometheus queries that use that dashboard variable will fail. The queries fail because Grafana is attempting to apply a Prometheus {} label filter to the custom variable value.

The effect of this is to turn a query such as ``count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/"} < (5*1024*1024*1024) or vector(0)) - 1``
into ``count(node_filesystem_avail_bytes{fstype!="rootfs",mountpoint="/",probe!="icmp"} < (5{probe!="icmp"}*1024*1024*1024) or vector(0)) - 1``. Here the 5 in the ``5*1024*1024*1024`` portion is the custom variable, but the substituted string becomes ``5{probe!="icmp"}`` instead of just ``5`` when the filter is added. Prometheus rejects this query with a syntax error:

```
"invalid parameter 'query': 1:104: parse error: unexpected \"{\" in aggregation"
```

**Environment**:
- Grafana version: 7.0.5, but the bug has been present in a number of earlier versions
- Data source type & version: Prometheus 2.19.2
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox on Fedora 31
- Grafana plugins: flant-statusmap-panel, natel-discrete-panel

**Comment by robbybb** [comment]
I have a similar problem using variables that is worse than a query failure.  It actually consistently causes prometheus to crash:
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: created by net/http.(*Transport).dialConn
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: /usr/local/go/src/net/http/transport.go:1338 +0x941
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: goroutine 2609 [select]:
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: net/http.(*persistConn).writeLoop(0xc151ab8000)
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: /usr/local/go/src/net/http/transport.go:1885 +0x113
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: created by net/http.(*Transport).dialConn
Oct 07 10:44:32 prom-devopsdev1-1 prometheus[6157]: /usr/local/go/src/net/http/transport.go:1339 +0x966
Oct 07 10:44:32 prom-devopsdev1-1 systemd[1]: prometheus.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Oct 07 10:44:32 prom-devopsdev1-1 systemd[1]: Unit prometheus.service entered failed state.
Oct 07 10:44:32 prom-devopsdev1-1 systemd[1]: prometheus.service failed.

The way to get recreate this is to have variables that if selected invalidate other variable options for other variables (In my case it's a standard grafana dashboard with variables cluster, datacenter, keyspace).  I have 3 clusters in 3 different datacenters with 3 different keyspace names.)  You don't have to click on an invalid option to bring down prometheus -- just select the drop down and down goes prometheus.  It's a nasty bug.  You can recreate this on most of the popular cassandra dashboards found on the grafana dashboard site.
