### ISSUE TITLE
Can't remove text or field name from InfluxDB query WHERE clause.

### ISSUE THREAD

**Issue by KevinUrbanski** [grafana/grafana#26027]
Hello there.

In Grafana 7, when text or a field is entered into the WHERE clause, you cannot remove these values under certain conditions.  It seems off the start, when one field is added when comparing with '>' or '<', you can't remove the field.  If you switch to any other comparison (ex. =, !=) you can then remove the field.  When two fields are added in the where clause, you can't remove the second no matter what.

![2020-07-02 13_38_51-Equipment Explorer - Grafana](https://user-images.githubusercontent.com/45699554/86392588-b3104f80-bc69-11ea-936e-37526a5c0d78.png)

-Kevin

**Comment by torkelo** [comment]
Able to replicate this.

there is also a bug with the group by + button dropdown, after you selected one tag it is empty and shows no values

**Comment by torkelo** [comment]
Opened fix here: https://github.com/grafana/grafana/pull/26031

**Comment by KevinUrbanski** [comment]
Thanks a lot, Torkel.
