### ISSUE TITLE
InfluxDB Flux plugin - use of 'map' causes internal server error

### ISSUE THREAD

**Issue by JoshuaKahn** [grafana/grafana#26040]
**What happened**:
I was trying to create an aggregate of values across multiple InfluxDB 2.0 tables and graph them. The query used to do this works in InfluxDB 2.0's data explorer (showing tables and graphs), but it causes an internal server error after the Flux function `map` is used, with no graph appearing (it says there's an error log, but I'm using grafana via a Docker container. Opening the container's CLI and going to var/log/grafana yields no results.)

![image](https://user-images.githubusercontent.com/35244044/86419336-ec03ff00-bd11-11ea-8689-5cd321b5b053.png)

**What you expected to happen**:
With data looking like this: 
![image](https://user-images.githubusercontent.com/35244044/86418530-8f074980-bd0f-11ea-87c9-5022a9c1f602.png)

I was able to create a mean aggregate using this:
```
from(bucket: "MyBucket")
  |> range(start: -1d, stop: 1d)
  |> filter(fn: (r) => r["_measurement"] == "AvgData")
  |> filter(fn: (r) => r["_field"] == "Mean Information")
  |> group(columns: ["_time", "_field"], mode:"by")
  |> mean()
  |> map(fn: (r) => ({
  time: r._time,
  MeanAggregate: r._value
  }))
```
Which can create a graph in InfluxDB 2.0's data explorer:

![image](https://user-images.githubusercontent.com/35244044/86419290-cbd44000-bd11-11ea-8fe5-384670a9565b.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a set of example data set up like the image above, then try entering the flux query into both the InfluxDB data explorer and Grafana.

**Anything else we need to know?**:
I'm guessing this is either because `map` functionality is not implemented yet, or because there's something strange occurring with the use of names here.

**Environment**:
- Grafana version: v7.1.0-beta2
- Data source type & version: InfluxDB, specifically using the Flux query language
- OS Grafana is installed on: Installed as Docker Container within Ubuntu Virtual Machine
- User OS & Browser: Metrics page Viewed using Microsoft Edge (Chromium version) on Windows 10
- Grafana plugins: None other than default
- Others:

**Comment by papagian** [comment]
Can you share your server logs?

**Comment by JoshuaKahn** [comment]
I tried to view them within the docker container (specifically `var/log/grafana`), but found no log files to attach.

**Comment by papagian** [comment]
how do you run the container? can you share your configuration?

**Comment by JoshuaKahn** [comment]
> how do you run the container? can you share your configuration?

The container is set up using `docker run -d --name=grafana -p 3000:3000 grafana/grafana:7.1.0-beta2`.

The data source setup looks like this: 
![image](https://user-images.githubusercontent.com/35244044/86447876-1e831b80-bd55-11ea-8b36-d0d0a9cbb262.png)

**Comment by JoshuaKahn** [comment]
This issue is still present in version 7.1.0-beta3.

**Comment by ryantxu** [comment]
Can you post what the raw CSV response looks like when you query in chronograph?

The easiest way to fix issues is to have a sample response that breaks something :)
https://github.com/grafana/grafana/tree/master/pkg/tsdb/influxdb/flux/testdata

**Comment by JoshuaKahn** [comment]
> Can you post what the raw CSV response looks like when you query in chronograph?
> 
> The easiest way to fix issues is to have a sample response that breaks something :)
> https://github.com/grafana/grafana/tree/master/pkg/tsdb/influxdb/flux/testdata

Did you mean this? This is the CSV output of the query in InfluxDB 2.0's Data Explorer, which named the file `chronograf` so I think it's the right app.
[testData.zip](https://github.com/grafana/grafana/files/4916485/testData.zip)

**Comment by papagian** [comment]
> The container is set up using `docker run -d --name=grafana -p 3000:3000 grafana/grafana:7.1.0-beta2`.

can you send the output of:
`docker logs grafana`

**Comment by JoshuaKahn** [comment]
> > The container is set up using `docker run -d --name=grafana -p 3000:3000 grafana/grafana:7.1.0-beta2`.
> 
> can you send the output of:
> `docker logs grafana`

When making the request that fails, I was able to get this out using `docker logs grafana`: 

```t=2020-07-14T05:02:34+0000 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="arrow/array: column \"time\" expected length >= 1 but got length 0" stack="/usr/local/go/src/encoding/json/encode.go:326 (0x777049)\n/usr/local/go/src/runtime/panic.go:969 (0x43bf05)\n/root/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20200629181129-68b1273cbbf7/array/table.go:290 (0xad1a91)\n/root/go/pkg/mod/github.com/apache/arrow/go/arrow@v0.0.0-20200629181129-68b1273cbbf7/array/table.go:240 (0xad1514)\n/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.71.0/data/arrow.go:41 (0xb01072)\n/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.71.0/data/arrow.go:680 (0xb096a9)\n/root/project/pkg/tsdb/models.go:138 (0xc391e7)\n/root/project/pkg/tsdb/models.go:161 (0xc3938e)\n/usr/local/go/src/encoding/json/encode.go:477 (0x7699a9)\n/usr/local/go/src/encoding/json/encode.go:358 (0x769021)\n/usr/local/go/src/encoding/json/encode.go:714 (0x76b48b)\n/usr/local/go/src/encoding/json/encode.go:759 (0x76b92a)\n/usr/local/go/src/encoding/json/encode.go:915 (0x76ce85)\n/usr/local/go/src/encoding/json/encode.go:801 (0x76bef3)\n/usr/local/go/src/encoding/json/encode.go:759 (0x76b92a)\n/usr/local/go/src/encoding/json/encode.go:915 (0x76ce85)\n/usr/local/go/src/encoding/json/encode.go:915 (0x76ce85)\n/usr/local/go/src/encoding/json/encode.go:358 (0x769021)\n/usr/local/go/src/encoding/json/encode.go:330 (0x768b3f)\n/usr/local/go/src/encoding/json/encode.go:161 (0x768021)\n/root/project/pkg/api/common.go:131 (0x1695f0f)\n/root/project/pkg/api/common.go:80 (0x16959a2)\n/root/project/pkg/api/metrics.go:92 (0x16ba921)\n/usr/local/go/src/reflect/value.go:460 (0x49d25a)\n/usr/local/go/src/reflect/value.go:321 (0x49c763)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975bbb)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x975599)\n/root/project/pkg/api/common.go:37 (0x16e14cd)\n/usr/local/go/src/reflect/value.go:460 (0x49d25a)\n/usr/local/go/src/reflect/value.go:321 (0x49c763)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975bbb)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x975599)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x976b48)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:112 (0x162325c)\n/root/project/pkg/middleware/request_tracing.go:25 (0x162324f)\n/usr/local/go/src/reflect/value.go:460 (0x49d25a)\n/usr/local/go/src/reflect/value.go:321 (0x49c763)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975bbb)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x975599)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x976b48)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:112 (0x1622a30)\n/root/project/pkg/middleware/request_metrics.go:36 (0x1622a1b)\n/usr/local/go/src/reflect/value.go:460 (0x49d25a)\n/usr/local/go/src/reflect/value.go:321 (0x49c763)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975bbb)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x975599)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x976b48)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:112 (0x16228e2)\n/root/project/pkg/middleware/recovery.go:160 (0x16228d5)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:79 (0x9769f0)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x9758e7)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x975688)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x976b48)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:112 (0x161fc6b)\n/root/project/pkg/middleware/logger.go:34 (0x161fc56)\n/usr/local/go/src/reflect/value.go:460 (0x49d25a)\n/usr/local/go/src/reflect/value.go:321 (0x49c763)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x975bbb)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x975599)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/context.go:121 (0x976b48)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/router.go:187 (0x987bc6)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/router.go:294 (0x98257d)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.3.9/macaron.go:220 (0x97b8fa)\n/usr/local/go/src/net/http/server.go:2807 (0x706152)\n/usr/local/go/src/net/http/server.go:1895 (0x701bcb)\n/usr/local/go/src/runtime/asm_amd64.s:1373 (0x46f310)\n"```

**Comment by kylebrandt** [comment]
I'm guessing this is happening because the resulting in a data frame does not have equal length fields, which arrow (how this data is encoded) is not allowed. If that is the case, there is the issue with the flux datasource creating the Frame which I think @ryantxu can look into?

Secondarily, there is avoiding the panic and getting an error instead for which I have created https://github.com/grafana/grafana-plugin-sdk-go/issues/203
