### ISSUE TITLE
InfluxDB 0.9 doesn't support dollar ($x) notation for aliases anymore

### ISSUE THREAD

**Issue by kmoppel** [grafana/grafana#2604]
In InfluxDB 0.8 one could alias different splits of a series with $1 etc., but currently for dot-separated series names this feature seems to be unavailable.

E.g. having a query returning data from a measurement (series) named "avg_sproc_runtime_per_db.mydb1.mean", I would like to just display the name of the database with "$1"

I know that in 0.9 series of Influx one is supposed to be using tags for data modelling and aliasing them is supported but for performance reasons we're still using the old way of modelling, and as the old way will be still supported by the InfluxDB would be very nice to have it in Grafana also.

**Comment by torkelo** [comment]
influxdb 0.9 is keys based, so you can use alias replace patterns for keys. If you want to use metric name and use that to name series and group by use Graphite or InfluxDB 0.8 :) 

Seriously I think I might do this one day if it gets +1 votes, or someone submits a PR. Seems like a lot of InfluxDB 0.9 users are having issues with series naming (not using keys etc)

**Comment by berglh** [comment]
+1 

This is super annoying. Currently shipping metrics from a stack with StatsD and InfluxDB backend plugin. Yes, I could ship the metrics directly to InfluxDB with using the HTTP API, but this is TCP and the UDP feature of StatsD gives me a high performance metrics receiver where missing a datapoint isn't that critical. 

There is no tag support for the InfluxDB plugin for StatsD currently. At least having this feature returend for period seperated $[0-9] aliases would ease the migration. We're currently stuck in limbo. InfluxDB 0.9 makes a lot of sense while the rest of the community catches up with InfluxDB 0.9 and Grafana. I should really learn node.js and help fix this feature in the StatsD/InfluxDB plugin.

**Comment by EliSnow** [comment]
@berglh, InfluxDB has the capability to receive metrics through UDP using the same line protocol you use with the HTTP API. You have to configure the `[[udp]]` section in `config.toml`.

**Comment by torkelo** [comment]
fixed https://github.com/grafana/grafana/commit/ead451a97987e49b417ff57944f7d70ef4f6d5f2

**Comment by kmoppel** [comment]
Niiice. Thanks @torkelo !
