### ISSUE TITLE
Cloudwatch: Custom endpoint URL in CloudWatch data source

### ISSUE THREAD

**Issue by lwierzbi** [grafana/grafana#26041]
**What would you like to be added**:

In CloudWatch data source, we would like to have possibility to override default AWS endpoint URL with custom value.

**Why is this needed**:

In one of our scenarios, we want to use custom endpoint URL instead of default one (as we already can do in AWS CLI). 
Change should be rather simple: passing additional parameter from data source configuration to SDK on init, and adding optional field in Cloudwtch datasource view in UI.

**Comment by aocenas** [comment]
@kaydelaney or @bergquist can't the aws sdk already to that in some way from some config file like the credentials?
