### ISSUE TITLE
built-in variable  in the query do not work when open/refresh dashboard

### ISSUE THREAD

**Issue by garyyang85** [grafana/grafana#26046]
Version: 7.1 beta2
I have a dashboard with a variable definition, which want to use the built-in "__user.login" to filter namespace only start with my username. 
Query: query_result(kube_namespace_created{namespace=~".${__user.login}"})
Regex: /.namespace="([^"])./

It only works when I edit the variable, click in the “query” input, and then click blank field, the " Preview of values" works, and then back to dashboard, it looks good.  The namespace I can select are all with my username prefix.

But when the first time I open the dashboard, or refresh the dashboard, it will send request like below(consider build in variable as common string):
http://localhost:3000/api/datasources/proxy/1/api/v1/query?query=kube_namespace_created%7Bnamespace%3D~%22.*%24%7B__user.login%7D%22%7D&time=1593767534

**Comment by papagian** [comment]
How to reproduce it

- start prometheus:
`make devenv sources=prometheus`
- create a user having `fake-prometheus-data:9091` username
- login with `fake-prometheus-data:9091`
- import [this](https://gist.github.com/papagian/7198954c0270254d33ff526ca6a077e2) dashboard
- I login with a different user and navigate to the dashboard; the template values are the previous ones, I have to go to the template for been refreshed.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/26637
