### ISSUE TITLE
V7.1 beta2 Text Panel HTML alignment

### ISSUE THREAD

**Issue by FortDigital** [grafana/grafana#26054]
Under 7.1 beta 2 Html Formats like this and overhands the inner panel div:

![image](https://user-images.githubusercontent.com/62287745/86473694-4e242a80-bd39-11ea-8f77-a58104d7dc6c.png)

Under 7.0 It formats like this:

![image](https://user-images.githubusercontent.com/62287745/86473666-3e0c4b00-bd39-11ea-8f36-e291bbd6d51f.png)

Html in question:

`<a href="http://www.fort-digital.com" target="_blank"><img src="https://www.fort-digital.com/wp-content/uploads/2020/04/FD-FINAL-Dark-BG-e1587590680251.png" height="100%"></a> Check out our github for more information and to raise issues: <a href="https://github.com/FortDigital/covid-19">https://github.com/FortDigital/covid-19</a>`

**Environment:**
Grafana version: 7.1 beta 2
Data source type & version: Influxd/Flux Builtin
OS Grafana is installed on: Ubuntu
User OS & Browser: Windows 10/Chrome
Grafana plugins: N/a
Others:

**Comment by torkelo** [comment]
What do you mean overhands the inner div? 

What html does the old panel product vs new?

**Comment by FortDigital** [comment]
Possibly the way ive worded it sorry. The HTML used in the panel is the same in both cases, but you can see in the screenshots that under 7.1 it renders past the outline of the panel wheras in 7.0 it fit itself inside the panel. Im making a leap that its because the way the 'Inner' of the panel is constructed has changed but thats pushing past my expertise :)

**Comment by FortDigital** [comment]
Hopefully these screenshots help:
![image](https://user-images.githubusercontent.com/62287745/86475422-8aa55580-bd3c-11ea-8f37-a42d5ab93d91.png)

This should be the same size as its parent above:
![image](https://user-images.githubusercontent.com/62287745/86475484-aad51480-bd3c-11ea-8314-653dfef42e7e.png)

In 7.0 there was a 'Height Helper' which at a guess was keeping things in line?:

![image](https://user-images.githubusercontent.com/62287745/86475529-c6401f80-bd3c-11ea-9a66-a7de9f1b5f3b.png)

Stays the same size as parent:

![image](https://user-images.githubusercontent.com/62287745/86475569-d821c280-bd3c-11ea-978c-4e90fb5c8560.png)

![image](https://user-images.githubusercontent.com/62287745/86475616-eec81980-bd3c-11ea-8226-31f04f94cf5e.png)
