### ISSUE TITLE
TimeSeries: stats.current to be set although not a number.

### ISSUE THREAD

**Issue by jimbom** [grafana/grafana#26053]
**What would you like to be added**:
In function `getFlotPairs`, in file time_series2.ts, the variable `stats.current` is only set if `allIsNull == false`. But `allIsNull` is only set to `true` if `currentValue` is not a number. I think it should be set even though `currentValue` is not a number

**Why is this needed**:
I can’t see any reason to not set `stats.current` although it is not a number.

https://github.com/grafana/grafana/blob/master/public/app/core/time_series2.ts

```
        if (_.isNumber(currentValue)) {
          this.stats.total += currentValue;
          this.allIsNull = false;
          nonNulls++;
        }
```

```
    if (result.length && !this.allIsNull) {
      this.stats.avg = this.stats.total / nonNulls;
      this.stats.current = result[result.length - 1][1];
      if (this.stats.current === null && result.length > 1) {
        this.stats.current = result[result.length - 2][1];
      }
    }
```

**Comment by torkelo** [comment]
TimeSeries class is only designed for numbers

**Comment by torkelo** [comment]
It is a legacy class, the new DataFrame type handled multiples types

**Comment by jimbom** [comment]
Thanks! 

The returned data from getFlotPairs is of type any[], and is filled with the string values. For now I just got the latest value myself (which may be both strings and numbers).

I can see that this class is deprecated, but I am updating an old plugin. Maybe I will try to change to using DataFrame instead. I will look into it!
