### ISSUE TITLE
Grafana 7.0.5 does not show suggestions/auto-complete when the SimpleJSON data source is used

### ISSUE THREAD

**Issue by ayamshanov** [grafana/grafana#26050]
**What happened**:
* Grafana 7.0.5 does not show suggestions/auto-complete when the SimpleJSON data source is used.

**What you expected to happen**:
Showing suggestions/auto-complete when the SimpleJSON data source is used.

**How to reproduce it (as minimally and precisely as possible)**:
* Open https://play.grafana.org/
* Click edit on any panel with a graph
* Select SimpleJson as a datasource
* Try to configure any metrics from the data-source (it always shows an only dropdown field with "table/timeserie").

**Anything else we need to know?**:
* N/A

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: ??? (play.grafana.org)
- OS Grafana is installed on: ??? (play.grafana.org)
- User OS & Browser: Windows 10 / Chrome 83
- Grafana plugins: ???  (play.grafana.org)
- Others: N/A

**Comment by ayamshanov** [comment]
![26050](https://user-images.githubusercontent.com/20258957/86466401-bedd3e00-bd5d-11ea-85bf-ebfeaa030e9c.gif)

**Comment by papagian** [comment]
@bergquist Should we close this issue and open in it in the simpleJSON datasource repo?

**Comment by ivanahuckova** [comment]
@papagian @bergquist I have created a [PR fix](https://github.com/grafana/simple-json-datasource/pull/156) for this in simpleJSON repo. There is also an [issue](https://github.com/grafana/simple-json-datasource/issues/155) for that. Therefore I am closing this in favour of those.
