### ISSUE TITLE
Multi-valued variables add escaping causing queries to return no data

### ISSUE THREAD

**Issue by aplovich** [grafana/grafana#26059]
**What happened**:
When I use a multi-valued dashboard variable in a panel query there are added escaping chars.  This is causing the queries using multi-valued variables to return no data.

Decoded url field from the query inspector for a single-valued variable:
`api/datasources/proxy/14/api/v1/query?query=probe_success{instance="130.202.115.15"}&time=1593829194`
This returns data

Decoded url field from the query inspector for multi-valued variable:
`api/datasources/proxy/14/api/v1/query?query=probe_success{instance="130\\.202\\.115\\.15"}&time=1593830211`
This returns no data

**How to reproduce it (as minimally and precisely as possible)**:
Create a multi-valued variable that's populated with a label value which includes periods, and query a Prometheus datasource using it.

**Environment**:
- Grafana version: Grafana v7.0.1 (ef5b586d7d)
- Data source type & version: Prometheus, version 2.18.1
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Fedora / Firefox

**Comment by torkelo** [comment]
Yes, this is correct , for multi valued filters Prometheus only supports regex so you need to use regex filter operator and Grafana needs to regex escape each value
