### ISSUE TITLE
Docs: grafana.ini should be defaults.ini in developer guide?

### ISSUE THREAD

**Issue by eloekset** [grafana/grafana#26068]
**What happened**:
Reading developer docs. Found a sentence saying that **custom.ini** will override **grafana.ini** located in the **conf** folder, but there is no **grafana.ini** in the **conf** folder.

**What you expected to happen**:
I find **defaults.ini** in the **conf** folder. Maybe this is the file that should be mentioned instead of **grafana.ini**?

**Anything else we need to know?**:
I looked at the history of **defaults.ini** to see if it maybe has been renamed from **grafana.ini** in the past, but it seems like it's always been **defaults.ini**. Maybe **defaults.ini** is called **grafana.ini** in a build output, but it's misleading to refer to **grafana.ini** in sources?

I'm referring to line 128-132 in this file: https://github.com/grafana/grafana/edit/master/contribute/developer-guide.md

**Comment by papagian** [comment]
thank you for reporting this!
your assumption is correct: the file containing the defaults is actually the `defaults.ini`. For changing these defaults you need to define overrides in `custom.ini` or `grafana.ini` depending on your operating system. You should not make changes in the `default.ini` file. Instead you can copy `sample.ini` file (also located under `conf` directory), rename it to `custom.ini` (or `grafana.ini`) and uncomment the configurations you would like to changes. For additional information you can also check [the configuration page](https://grafana.com/docs/grafana/latest/administration/configuration/#config-file-locations).
