### ISSUE TITLE
Docs feedback: /enterprise/_index.md

### ISSUE THREAD

**Issue by juliocvidal** [grafana/grafana#26069]
At this paragraph 
"Building on everything you already know and love about Grafana, **Grafana Enterprise adds enterprise data sources**, advanced authentication options, more permission controls, 24x7x365 support, and training from the core Grafana team."

What do you mean by **enterprise data sources** here?

Are there any data sources that are not possible to be used with Grafana open source version?

It seems to me that you actually wanted to write that "Grafana Enterprise adds enterprise data sources **plugins**".
Is this correct?

I would highly appreciate if you confirm this information because this will define which version my company will decide to use. Or if we are going to look for another provider. 
Thanks. :)

**Comment by juliocvidal** [comment]
**asas**

**Comment by torkelo** [comment]
Yes, we mean enterprise data source plugins.
Here is a complete list and info: 
https://grafana.com/grafana/plugins?enterprise=1 

Will update docs! thanks for the feedback!
