### ISSUE TITLE
Multi-select variables are incorrectly interpolated in links / URL with multi-select variables is incorrectly parsed

### ISSUE THREAD

**Issue by Muraliprasath** [grafana/grafana#26077]
Hi Team, 

Kindly address the below issue, we have the fix for the same but we this needs to added to the github repo itself,
Kindly let me know if any details required,

Fix has to be made in below file, in grafana repo, we have to create a custom formatting in format() in the below file
public/app/features/templating/template_srv.ts

Workaround is like we could have below fn, which will format the customization as to satisfy the requirements,
**CustomFormatVariable**(value: any, variable: any) {
    value = _.map(value, (val: any, index: number) => {
      if (index !== 0) {
        return **'var-'** + variable + '=' + val;
      } else {
        return val;
      }
    });
    return value.join('**&**');
  }

Currently supported formats are glob,regex, pipe, csv, lucene, distributed.. but these format wont solve the below issue,

Let say we are in dashboardA it has template variables field server which as 3 values server1, server2, server3. 
When we try to create a link to another dashboard we have to pass the mutliple selected template variable to dashboardB. whereas in dashboardB whatever template variables selected in dashboardA has to be selected in dashboardB as well, since we are passing those value through the URL as below

We dont have any advance template variable formatting to support below format, because grafana only supports below format for using the values from url to the template variable.
Url should have '&' sign and then var-<variable_name>=<value_selected>

&var-servers=test.1**&var-servers=**test2&var-servers=test3

Example: 
https://play.grafana.org/d/cJtIfcWiz/template-variable-formatting-options?orgId=1

https://play.grafana.org/d/cJtIfcWiz/template-variable-formatting-options?orgId=1**&var-servers=test.1&var-servers=test2&var-servers=test3**

**Comment by dprokop** [comment]
@Muraliprasath to confirm that I understand correctly:

1. You have a **Dashboard A** with variable `variableA` that allows multiselect
2. You have **Dashboard B** which also has `variableA` that accepts the same values
3. In **Dashboard A** you create a data link that needs to set **Dashboard B's** `variableA` to have the same values, as the ones selected in **Dasboard A**

**Comment by Muraliprasath** [comment]
> @Muraliprasath to confirm that I understand correctly:
> 
> 1. You have a **Dashboard A** with variable `variableA` that allows multiselect
> 2. You have **Dashboard B** which also has `variableA` that accepts the same values
> 3. In **Dashboard A** you create a data link that needs to set **Dashboard B's** `variableA` to have the same values, as the ones selected in **Dasboard A**

Yes, this is the correct use case we would like to have.

**Comment by torkelo** [comment]
This is still a unsolved problem in Grafana, https://github.com/grafana/grafana/issues/21459

**Comment by dprokop** [comment]
Thanks @torkelo, haven't seen the other issue

**Comment by Muraliprasath** [comment]
@torkelo , @dprokop - 
This issue can be resolved by creating a customFormatingfn
Workaround is like we could have below fn, which will format the customization as to satisfy the requirements,

File Path : public/app/features/templating/template_srv.ts 
In formatValue Funcion, we can create a custom case something similar like **distributed**, and we will the below formatting fn

CustomFormatVariable(value: any, variable: any) {
value = _.map(value, (val: any, index: number) => {
if (index !== 0) {
return **'var-'** + variable + '=' + val;
} else {
return val;
}
});
return value.join(**'&'**);
}

Above piece of code, is working fine, while mutli selecting variables.
Kindly share your comments over this.

Regards,
Murali Prasath V

**Comment by madnanadnan** [comment]
> @torkelo , @dprokop -
> This issue can be resolved by creating a customFormatingfn
> Workaround is like we could have below fn, which will format the customization as to satisfy the requirements,
> 
> File Path : public/app/features/templating/template_srv.ts
> In formatValue Funcion, we can create a custom case something similar like **distributed**, and we will the below formatting fn
> 
> CustomFormatVariable(value: any, variable: any) {
> value = _.map(value, (val: any, index: number) => {
> if (index !== 0) {
> return **'var-'** + variable + '=' + val;
> } else {
> return val;
> }
> });
> return value.join(**'&'**);
> }
> 
> Above piece of code, is working fine, while mutli selecting variables.
> Kindly share your comments over this.
> 
> Regards,
> Murali Prasath V

How do you call the function for the needed formatting? I.e. what is the use case that you use in formatValue()?

**Comment by Muraliprasath** [comment]
Currently we have below formatting option like glob,json,distributed etc..

Under following path, we will create with new formatter named customxyz and will use the above formatter function, then we can consume like ${var_name: custom_xyz}, we will get a new formatter used.

Usecase - If we do a link from one dashboardA to another dashboardB, if we want to pass the template variables, following format needs to be supported,
?var_name=xy&var_name=yz&var_name=zx


public/app/features/templating/**formatRegistry.ts**

Usage as below, same way we can have ${var_name: }
${var_name:glob}
${var_name:regex}
${var_name:pipe}
${var_name:csv}
${var_name:json}
${var_name:distributed}
${var_name:lucence}
${var_name:glob}
..
..
..
..
