### ISSUE TITLE
"An unexpected error happened" when applying transformation

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#26073]
**What happened**:
I created a panel, and put in query `sum(etcd_object_counts)`. I then selected type "Table". Then I clicked "transformation" tab. I select "reduce", which switches the table to be showing the max, but there is no configuration:
![2020-05-07_16-00-54](https://user-images.githubusercontent.com/623453/86544060-bbba8d00-bed8-11ea-8155-552b5fa3047b.png)

Next I click the "query" tab again, followed by "transformation", which leads to this error page:

![2020-05-07_16-01-27](https://user-images.githubusercontent.com/623453/86544078-d2f97a80-bed8-11ea-8860-47c759de3773.png)

**What you expected to happen**:
Can apply transformations

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

**Environment**:
- Grafana version: `grafana/grafana:7.0.2`
- Data source type & version: prometheus
- OS Grafana is installed on: Kubernetes COS
- User OS & Browser: Linux Chrome 83.0.4103.116
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Does this also happen with the latest Grafana version (7.0.5)?

**Comment by torkelo** [comment]
Think this was fixed in 7.0.3
