### ISSUE TITLE
global built-in variables: __dashboard and __dashboard.name are not available in the text panel

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#26083]
I want to use the relatively new global variable __dashboard to open git hub issues.
When I try to use the variable in the panel it is not being replaced, I've tried both the `$` and the `[[]]` substitution none worked

How I just reproduce it:

* Edit a text panel and add ${__dashboard.name} in the text - Should work
* Exit the edit panel
* Edit the same panel again, remove and add the ${__dashboard.name} now it does not work

**Comment by torkelo** [comment]
try 7.0.5

**Comment by amnonh** [comment]
I've checked in 7.0.5 it seems to work and then fail again (I believe it only works the first time, you make a change, and then it will not try to replace the variable)
I think it should be re-openned
![image](https://user-images.githubusercontent.com/2118079/86602268-158b8780-bfab-11ea-8e96-e8e0bb95ee83.png)

**Comment by ryantxu** [comment]
hymmm -- rather than having a pile of scattershot environment variables that all need to be added to everywhere (and are not in any suggest context!)  maybe we should add a single gobal one?
```
${__env.dashboard.uid}
${__env.user.name}
${__env.timeRange.from}
${__env.timeRange.from[ms]}
${__env.timeRange.from[YYYY]}
```
if we use a proxy object we can support many options without pre-defining them upfront like is required for the root scope

**Comment by amnonh** [comment]
@torkelo can you please re-open, I don't think it is solved

**Comment by torkelo** [comment]
@ryantxu like the single object & proxy idea! 

@amnonh it works when I test it 

```
${__dashboard.name}
```

interpolates fine in the text panel when I test

**Comment by amnonh** [comment]
How I just reproduce it:
* Edit a text panel and add `${__dashboard.name}` in the text - Should work
* Exit the edit panel
* Edit the same panel again, remove and add the `${__dashboard.name}` now it does not work

**Comment by amnonh** [comment]
@torkelo can you please see the way I reproduced it?

**Comment by torkelo** [comment]
thanks updated the main description with the way to reproduce it
