### ISSUE TITLE
Loki not working in Grafana 7.0+ version

### ISSUE THREAD

**Issue by anishvarghese** [grafana/grafana#26081]
**What happened**:
Not able to connect loki to the grafana 7.0 +

**What you expected to happen**:
https://community.grafana.com/t/loki-not-working-in-grafana-7-0/31399/2

**How to reproduce it (as minimally and precisely as possible)**:
https://community.grafana.com/t/loki-not-working-in-grafana-7-0/31399/2

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
No other reports, and it's working in our env. See you get a 404 response, make sure your loki server is running and your entering the correct url.And make sure your running the latest version of loki

**Comment by torkelo** [comment]
If you still have problems, please report on details the network requests
