### ISSUE TITLE
Alerting: "Alert Rule Result Error" still appearing after removing all alerts

### ISSUE THREAD

**Issue by der-eismann** [grafana/grafana#26082]
**What happened**: I removed all of our Grafana alerting rules because they were throwing errors all the time and we are relying on alertmanager anyway. So I deleted all of them through the UI, but we keep getting the errors:
```
t=2020-07-06T11:18:10+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=15 name="3D Authentications alert" error="Could not find datasource Data source not found" changing state to=alerting
t=2020-07-06T11:18:20+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=16 name="Process States PAYPAL alert" error="Could not find datasource Data source not found" changing state to=alerting
t=2020-07-06T11:18:20+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=19 name="Process States PAYPAL alert" error="Could not find datasource Data source not found" changing state to=alerting
t=2020-07-06T11:18:30+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=17 name="3D Authentications alert" error="Could not find datasource Data source not found" changing state to=alerting
t=2020-07-06T11:18:40+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=18 name="Process States CREDIT_CARD alert" error="Could not find datasource Data source not found" changing state to=alerting
t=2020-07-06T11:19:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=14 name="Process States CREDIT_CARD alert" error="Could not find datasource Data source not found" changing state to=alerting
```

**What you expected to happen**: I expected that the errors would disappear after deleting all alerting rules, but it looks like they are still saved somewhere.

**How to reproduce it (as minimally and precisely as possible)**: I have absolutely no idea. The alerting rules were probably quite old, I'm not sure in which version they were created.

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Prometheus 2.19.1
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Fedora 32 & Chrome 83

**Comment by der-eismann** [comment]
After looking at the sqlite DB I see that the entries in the `alert` table all have `org_id = 4`, but we only have one `org` with the ID 1. Not sure how this happened, but maybe this is why I can't see them in the UI. I'll try to delete them from the DB.

**Comment by dprokop** [comment]
@der-eismann did you manage to solve it? I asked @papagian for help and I got this response `... wherever we look for a datasource we query using both the id and the org_id so changing the alert in the DB to contain the correct org_id must fix it`

**Comment by der-eismann** [comment]
Well first I changed the org_id to 1, but I didn't check for errors, I just checked if the alert appears in the UI now, which wasn't the case. So after all I just deleted all entries from the alert table and disabled alerting completely for Grafana. I guess this was just some weird edge case, feel free to close the ticket :slightly_smiling_face:
