### ISSUE TITLE
Add Search to Org Switcher

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2609]
Juggling multiple orgs can be a bit cumbersome when the list gets long.

Currently:
![screenshot 2015-08-27 12 54 48](https://cloud.githubusercontent.com/assets/2886187/9527082/e480279e-4cba-11e5-8c31-70343e1f2055.png)

With that, it would be nice to introduce a search box, like the dashboard picker:

![image](https://cloud.githubusercontent.com/assets/2886187/9527213/b0422f3a-4cbb-11e5-8bd0-754f147f35fd.png)

Thoughts?

**Comment by tmonk42** [comment]
I dig it!

**Comment by torkelo** [comment]
Good suggestion. I doubt that this is an issue for 99.9% of users though but is pretty easy to add I think

**Comment by cemo** [comment]
:heart:

**Comment by toni-moreno** [comment]
:+1

**Comment by Othyus** [comment]
+1, very helpful for us
