### ISSUE TITLE
Receiving only 6 metrics values in Slack alert even more than 6 conditions are true

### ISSUE THREAD

**Issue by sabir-piludiya** [grafana/grafana#26099]
**What happened**:
I have setup the alert with slack. I have more than 10 metrics with **or** condition. when condition becomes true, only 6 metrics values in Slack alert is received even it satisfy more than 6 conditions.

**What you expected to happen**:
There should include all the condition metrics in slack alert. like more than 6.

**Environment**:
- Grafana version: latest
- Data source type : Prometheus
- OS Grafana is installed on: Kubernetes

**Comment by dprokop** [comment]
Duplicate https://github.com/grafana/grafana/issues/16662
