### ISSUE TITLE
Creating new folder redirects to 404 error page

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#26108]
**What happened**:

Whenever I create a new folder, the folder gets created (good) and I get redirected to a 404 error page (bad). I can simply navigate back but it is a bug, nevertheless.

**What you expected to happen**:

No redirection to 404 page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new folder

**Anything else we need to know?**:

**Environment**:

- Grafana version: v7.0.5 (efbcbb838b)
- OS Grafana is installed on: Vanilla Grafana Docker image
- User OS & Browser: Windows, Chrome
- Grafana plugins: No
- behind reverse proxy Nginx

See this comment for more details: https://github.com/grafana/grafana/issues/26108#issuecomment-654944818

![gif](https://user-images.githubusercontent.com/24834206/86746729-8d08f780-c03b-11ea-8574-752093f370e8.gif)

**Comment by peterholmberg** [comment]
@trallnag I am unable to reproduce this. Do you have a custom root url perhaps?

**Comment by trallnag** [comment]
@peterholmberg 

This is indeed the case, I am running Grafana behind an Nginx behind AWS Load Balancer. Here is the relevant part from my `grafana.ini`:

```
[server]
domain = ${DOMAIN}
root_url = https://%(domain)s/promstack/grafana/
serve_from_sub_path = true
```

And here the relevant part from the `nginx.conf`:

```
events {}
http {
  server {
    listen 80 default_server;

    location /promstack/grafana/ {
      proxy_pass http://grafana:3000/;
    }
  }
}
```

**Just to clarify:** The Grafana tab bar on the left is still visible, so I can go back without any problem. So it is not critical for me.

I have another Grafana instance running in a Docker Swarm again behind an Nginx and I have the same issue there:

![gif2](https://user-images.githubusercontent.com/24834206/86804229-096cfc00-c077-11ea-861f-884277686687.gif)

`grafana.ini`:

```
[server]
domain = ${PROMSTACK_NS_SANITIZED}.${DTR_NS_SANITIZED}.docker.intranet.cnb
root_url = https://%(domain)s/grafana/
serve_from_sub_path = true
```

`nginx.conf`:

```
events {}
http {
  server {
    listen 80 default_server;
    server_name _;
    return 301 https://$host$request_uri;
  }

  server {
    listen 443 ssl;
    ssl_certificate /cert;
    ssl_certificate_key /key;

    location /grafana/ {
      proxy_pass http://grafana:3000/;
    }
  }
}
```

The docker swarm load balancer passes everything (including ssl) through to the nginx
