### ISSUE TITLE
When viewing template variables, Grafana can easily get caught in a rapid, endless loop of trying to refresh every panel on the dashboard

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#26101]
This is 100% reproduceable on the live demo site/any dashboard with template variables. For example: https://play.grafana.org/d/000000002/influxdb-templated

**What happened**: When trying to edit template variables, Grafana started spamming out thousands of queries in an attempt to refresh every panel many times over (despite none of them being visible at the time).

**What you expected to happen**: For no refresh call to be sent out when in the dashboard edit view, the panels to register as not visible, and (failing all of that) for each panel to only try to refresh once.

**How to reproduce it (as minimally and precisely as possible)**: After changing a template variable value and seeing the URL update to reflect that change, go into the dashboard options page, which defaults you to "general", and then switch over to view "Variables". At this point the page will appear to hang, Dev Tools will reveal hundreds, or even thousands of requests being made to your datasource in rapid succession.

**Anything else we need to know?**: This is very easy to reproduce and seems very, very bad. Not only does it hang the browser, it hammers your datasources.

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: Seen with ES and InfluxDB
- OS Grafana is installed on: Windows and whatever the Live demo site runs on

**Comment by Ultraseamus** [comment]
@torkelo I am curious to know how the priority gets decided on. In my mind, this bug is about as bad as it gets. It is easy to trigger accidentally, when you do it appears as the site locking up/becoming unresponsive, while (hidden from most) it is very aggressively sending out queries to every datasource that dashboard uses. Which gets much worse with bigger dashboards (the example I posted was a single panel, so only hundreds of queries were generated). It is not hard to imagine this bug taking down people's data-stores.

This being marked as priority/important-soon seemed reasonable, until I noticed that another, more recent bug about a harmless 404 redirect after making a new folder got marked as priority/critical.

**Comment by torkelo** [comment]
> This being marked as priority/important-soon seemed reasonable, until I noticed that another, more recent bug about a harmless 404 redirect after making a new folder got marked as priority/critical.

Think that was mislabeled, this is way more critical!

**Comment by torkelo** [comment]
have identified 2 problems causing this, fix incoming tomorrow

**Comment by torkelo** [comment]
Fix PR is up

**Comment by Ultraseamus** [comment]
That's great to see, thanks!

Will this be released not just as part of 7.1, but also as a patch to 7.0 (7.0.6, presumably)?

**Comment by torkelo** [comment]
Maybe , 7.1 stable is out next week but this could warrant a 7.0.6

**Comment by Ultraseamus** [comment]
@torkelo So I took the changes from your PR and applied them to a private fork of 7.0.5. It did fix the issue going into the Variable page... but it created a much worse problem. :/

Now whenever I change the value half of an adhoc filter, it gets into an even more aggressive loop that crashes my browser every time.

I believe the bug in your code is as follows:

`function getUrlValueForComparison(value: any): any {
    if (isArray(value)) {
      if (value.length === 0) {
        value = undefined;
      } else if (value.length === 1) {
        value = value[0];
      }
    }

    return value;
  }`

If the value is an adhoc filter it comes in the above function (always as an array) to be compared, it gets flattened if it is an array of size 1. The trouble is that you are then taking that flattened return value (no longer a valid representation of the adhoc variable) and dispatching it out in templateVarsChangedInUrl:

` // Check for template variable changes on a dashboard
      if (state.location.path === this.lastPath) {
        const changes = findTemplateVarChanges(state.location.query, this.lastQuery);
        if (changes) {
          const dash = getDashboardSrv().getCurrent();
          if (dash) {
            dispatch(templateVarsChangedInUrl(changes));
          }
        }
        this.lastQuery = state.location.query;
      } else {
        this.lastQuery = {};
      }`

That series of function calls fails, and the code is left in a tight loop where it just keeps coming back to this bridge_srv function, seeing that the adhoc variable has been updated, and attempting to dispatch it out all over again.

I was able to get it working by keeping your comparison logic in place, but keeping the old "changes[key] = query[key];" in place.

**Comment by torkelo** [comment]
Thanks for testing and investigating!! 

Luckily 7.0.6 release has not started yet

**Comment by torkelo** [comment]
Grafana v7.0.6 released with a fix for this, hope it solves it!

**Comment by Ultraseamus** [comment]
@torkelo We are getting close... but I do have another related bug for you. It's all part of the same thing in my mind (the same failure pattern and the same code is involved), but I could file this as a new bug.

This one can be replicated on the following dashboard with a few edits: https://play.grafana.org/d/000000002/influxdb-templated

1) Switch the graph to a "Stat" panel.
2) Add a Data Link with this string: d/000000002/influxdb-templated?${__all_variables}&var-adhoc=hostname%7C%3D%7C${__field.name}
3) Make sure to leave it defaulted to not opening a new tab, and attempt to use that Data Link.

It results in the same endless loop we've been seeing. This time around, instead of the adhoc variable being flattened by the comparison logic, it actually comes in flattened (as a string instead of a string array).


I've not had the chance to really dive into this one yet. I know it used to work, but I am not sure exactly when it broke. An interesting detail is that it works fine so long as the adhoc variable in question already has a value. In that case, the state.location.query comes in with an array of values for that adhoc variable, and everything works fine.

Ever since the 7.0 update I'm not very familiar with how template variables work behind the scenes. I don't know what the full update path looks like for adding an adhoc variable directly versus doing it with a Data Link. Even trying to follow the update logic I end up getting a little lost. So I don't have a specific fix just yet.

But, it seems to me like the best fix here might be to make it so an adhoc variable can be dispatched from this function we've been looking at not as an array, and still have it work.

Just to back up my assumption that this is all about the adhoc variable being represented as an array, if I make this code change, it works properly:

```
if (!isEqual(newValue, oldValue)) {
      changes[key] = [query[key]];
      count++;
    }
```

Even if you don't have time for this one at the moment, or consider it lower priority, I'd appreciate any pointers you may have, ideally for a way to fix this downstream. But, a way to get this variable flowing in as an array would also be fine.

Thanks!

**Comment by Ultraseamus** [comment]
Figured it out.

The logic you created here:

```
function getUrlValueForComparison(value: any): any {
    if (isArray(value)) {
      if (value.length === 0) {
        value = undefined;
      } else if (value.length === 1) {
        value = value[0];
      }
    }

    return value;
  }
```

Also needs to have been implemented here:

```
const isVariableUrlValueDifferentFromCurrent = (variable: VariableModel, urlValue: any): boolean => {
  // lodash isEqual handles array of value equality checks as well
  return !isEqual(variableAdapters.get(variable.type).getValueForUrl(variable), urlValue);
};
```

The first pass through actually works fine. The variable gets updated properly (because in the adhoc overrides, the update gets cast to an array). But on the second pass through this function needs to detect that the variable has not changed, but it can't since it is comparing a string to an array. Anywhere variables are being checked for differences like that, this logic would be needed.

Something like this (just copy/pasted from bridge_srv)

```
function getUrlValueForComparison(value: any): any {
  if (isArray(value)) {
    if (value.length === 0) {
      value = undefined;
    } else if (value.length === 1) {
      value = value[0];
    }
  }

  return value;
}

const isVariableUrlValueDifferentFromCurrent = (variable: VariableModel, urlValue: any): boolean => {
  const oldValue = getUrlValueForComparison(variableAdapters.get(variable.type).getValueForUrl(variable));
  const newValue = getUrlValueForComparison(urlValue);

  // lodash isEqual handles array of value equality checks as well
  return !isEqual(oldValue, newValue);
};
```

I suspect you would not want to release a 7.0.7 for this, but without it, updating adhoc filters with Data Links is broken.

**Comment by zoltanbedi** [comment]
Hi @Ultraseamus is this fixed? if not can you open a pr maybe?

**Comment by Ultraseamus** [comment]
@zoltanbedi: So far as I know, this one has not been addressed yet. I have it fixed in my personal branch, but it is presumably still broken in the official branch.

I can look at creating a PR for it.

**Comment by zoltanbedi** [comment]
That would be awesome. I would really appreciate it.
