### ISSUE TITLE
Issue with getting ldap working, conflicting info in ldap verbose output

### ISSUE THREAD

**Issue by fanirama** [grafana/grafana#2611]
Hello,
I'm trying to get ldap working and I'm seeing  conflicting info being reported and am unsure if this is a bug or something else config wise and looking for some assistance to resolve this. 

Config file has - 
verbose_logging = true
search_filter = "(uid=%s)"
search_base_dns = ["dc=MYCOMPANY,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "mail"

 #   Map LDAP groups to Grafana org roles
[[servers.group_mappings]]
group_dn = 'systems'
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "cn=compliance"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "hr"
org_role = "Viewer"

---------------------------------------------------------------------------------------

Console log shows - 

2015/08/27 15:45:21 [I] Ldap User Info: (*login.ldapUserInfo)(0xc20825dd50)({
 DN: (string) (len=48) "uid=jdoe,ou=People,dc=MYCOMPANY,dc=com",
 FirstName: (string) (len=9) "John",
 LastName: (string) (len=8) "Doe",
 Username: (string) (len=9) "jdoe",
 Email: (string) (len=28) "jdoe@MYCOMPANY.com",
 MemberOf: ([]string) (len=5 cap=8) {
  (string) (len=46) "cn=mycomp,ou=Group,dc=MYCOMPANY,dc=com",
  (string) (len=50) "cn=systems2,ou=Group,dc=MYCOMPANY,dc=com",
  (string) (len=48) "cn=systems,ou=Group,dc=MYCOMPANY,dc=com",
  (string) (len=63) "cn=IM,ou=MyMisc,dc=MYCOMPANY,dc=com",
  (string) (len=60) "cn=mycomp,ou=IM Rosters,ou=MyMisc,dc=MYCOMPANY,dc=com"
 }
})

2015/08/27 15:45:21 [I] Ldap Auth: user jdoe does not belong in any of the specified ldap groups, ldapUser groups: [cn=mycomp,ou=Group,dc=MYCOMPANY,dc=com 
cn=systems2,ou=Group,dc=MYCOMPANY,dc=com 
cn=systems,ou=Group,dc=MYCOMPANY,dc=com        
cn=IM,ou=MyMisc,dc=MYCOMPANY,dc=com                                                   
cn=mycomp,ou=IM Rosters,ou=MyMisc,dc=MYCOMPANY,dc=com]

2015/08/27 15:45:21 [login.go:98 LoginPost()] [E] Invalid username or password: Invalid Username or Password
2015/08/27 15:45:21 [I] Completed /login 401 Unauthorized in 11.731058ms
2015/08/27 15:45:21 [I] Completed /api/login/ping 401 Unauthorized in 1.74992ms

I can confirm that jdoe does belong in each of the listed ldap groups. 
It is picking up the proper ldap groups for the passed in user but is then reporting that the user is not found in any of those ldap groups and erroring out. 
How do I correct this issue? 
I've tried both grafana 2.1.3 and the grafana 2.2.0-pre1 release. 

Thanks,

**Comment by calebcall** [comment]
Try and change your group_dn config to include the full thing and not just the cn. (e.g. group_dn = "cn=mycomp,ou=Group,dc=MYCOMPANY,dc=com" )

**Comment by torkelo** [comment]
in the `[[servers.group_mappings]]` section `group_dn' must match the full DN exactly as ldap returns it. 

You onbly specified a string on 2 cases and a cn path in one :)

**Comment by fanirama** [comment]
Hi, thanks for the replies. The typo was a cut/paste error as I removed my corp info. I did have cn= proper syntax in the actual toml file. Also, I did try with the full DN and without before as well with no success. 

Essentially here's what's happening -

(1) with the full DN -
# Map LDAP groups to Grafana org roles
[[servers.group_mappings]]
group_dn = 'cn=systems,ou=Group,dc=MYCOMPANY,dc=com'
org_role = "Admin"
org_id = 1
 
 and no other servers.group_mappings, I'm getting - 
2015/08/28 09:47:31 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: UNIQUE constraint failed: org.name
2015/08/28 09:47:31 [I] Completed /login 500 Internal Server Error in 16.212318ms

(2) without the full DN -
[[servers.group_mappings]]
group_dn = 'cn=systems'
org_role = "Admin"
org_id = 1

2015/08/28 09:48:03 [I] Ldap Auth: user jdoe does not belong in any of the specified ldap groups, ldapUser groups: [cn=mycomp,ou=Group,dc=MYCOMPANY,dc=com cn=systems2,ou=Group,dc=MYCOMPANY,dc=com cn=systems,ou=Group,dc=MYCOMPANY,dc=com cn=IM,ou=MyMisc,dc=MYCOMPANY,dc=com
 cn=mycomp,ou=IM Rosters,ou=MyMisc,dc=MYCOMPANY,dc=com]
2015/08/28 09:48:03 [login.go:98 LoginPost()] [E] Invalid username or password: Invalid Username or Password
2015/08/28 09:48:03 [I] Completed /login 401 Unauthorized in 11.784752ms
2015/08/28 09:48:03 [I] Completed /api/login/ping 401 Unauthorized in 1.405854ms

Is there a way to make grafana report even more verbose output.
Again, thanks for all your help. The product is fantastic.

**Comment by fanirama** [comment]
Hi torkelo, after checking some more, I think the issue is that the code is checking for MemberOf whereas my ldap is returning values only when queried for "UniqueMember".

How would I make the edit to get it to search on UniqueMember instead or in addition to MemberOf?

I attempted to edit ldap.go and settings.go and ldap_user.go but I'm in completely unfamiliar territory here. 
I added "a.server.Attr.UniqueMember,"  in the searchForUser function and tried returning that in &ldapUserInfo and edited ldap_user.go to be thus 

--- 

package login

type ldapUserInfo struct {
        DN        string
        FirstName string
        LastName  string
        Username  string
        Email     string
        MemberOf  []string
        UniqueMember  []string
}

func (u *ldapUserInfo) isMemberOf(group string) bool {
        if group == "*" {
                return true
        }

        // for _, member := range u.MemberOf {
        for _, member := range u.UniqueMember {
                if member == group {
                        return true
                }
        }
        return false
}

----

But not having any luck. Can you pls assist?

**Comment by torkelo** [comment]
no, I think your memberOf was correct (and ldap was returning memberships in this attribute)

```
# Map LDAP groups to Grafana org roles
[[servers.group_mappings]]
group_dn = 'cn=systems,ou=Group,dc=MYCOMPANY,dc=com'
org_role = "Admin"
org_id = 1
```

this should work, but very strange error about unique org name

**Comment by fanirama** [comment]
hi, thanks for your help but it is all resolved now.

 I believe I needed another org to be created and something in grafana.db was interfering and I was shuttling between these errors eventually - 
[login.go:101 LoginPost()] [E] Error while trying to authenticate user: UNIQUE constraint failed: org.name
and after putting some print statements I saw that it was matching the DN but failing with - 
[login.go:101 LoginPost()] [E] Error while trying to authenticate user: Cannot remove last organization admin


and so I just deleted my grafana.db and added another org to the toml file as : 

[[servers.group_mappings]]
group_dn = "*"
org_role = "Admin"
org_id = 2


and after restart, a new grafana.db got populated and everything is working (for now ;) 

I backed out all my code changes and your original code works correctly. 

Thanks much.

**Comment by fanirama** [comment]
Oops.. maybe I spoke too soon.. I had user try to log in and the error is back -

2015/08/28 16:03:52 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: Cannot remove last organization admin

My entire toml file is 
----
verbose_logging = true

[[servers]]
host = "ldap.MYCOMPANY.com"
port = 389
use_ssl = false
ssl_skip_verify = false

search_filter = "(uid=%s)"
search_base_dns = ["ou=People,dc=MYCOMPANY,dc=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=systems,ou=Group,dc=MYCOMPANY,dc=com"
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "*"
org_role = "Admin"
org_id = 2

**Comment by knepperjm** [comment]
@fanirama any resolution?  This issue appears to still be an issue?
