### ISSUE TITLE
Alerting: Prometheus firing state is incorrect 

### ISSUE THREAD

**Issue by alavrovinfb** [grafana/grafana#26117]
Grafana triggered and sent a notification for "No Data" state, but Alert test rule shows that `firing: false`. 
`
{
"firing": false,
"state": "no_data",
"conditionEvals": "false = false",
"timeMs": "2.485ms",
"logs": [
{
"message": "Condition[0]: Query",
"data": {
"from": 1594062705363,
"queries": [
{
"refId": "A",
"model": {
"expr": "rate(process_cpu_seconds_total{job=\"kubernetes-apiservers\"}[5m])",
"format": "time_series",
"hide": true,
"intervalFactor": 2,
"legendFormat": "{{instance}}",
"refId": "B"
},
"datasource": {
"id": 1,
"name": "Prometheus"
`
**What you expected to happen**:
Firing should show propper state `true` if alert notification triggerd
**How to reproduce it (as minimally and precisely as possible)**:
 - Configure alert and notification for dashboard with no data
 - Test alert rule  

**Environment**:
- Grafana version: grafana:6.5.1
- Data source type & version: Prometheus 2.17.2
- OS Grafana is installed on: docker container, 
- User OS & Browser: Ubuntu 20.4, firefox
- Grafana plugins: no
- Others: -

**Comment by ivanahuckova** [comment]
Hello @alavrovinfb the alerting state for Prometheus is consistent with the [documentation](https://grafana.com/docs/grafana/latest/alerting/create-alerts/#no-data--error-handling). You can set up the NO DATA behaviour however you want - see below example when I set it up to **Ok**, **No data**, **Alerting** state. If you don't want notification to be sent, you can simply choose *Keep Last State* and change to NO DATA won't have any effect on alerting. 

![image](https://user-images.githubusercontent.com/30407135/94707159-665d1300-0343-11eb-9eee-de3759717a16.png)
