### ISSUE TITLE
Download all groups in CSV (version 7)

### ISSUE THREAD

**Issue by alexwbai** [grafana/grafana#26129]
Hi, I have a query that has grouped a bunch of values.  In the previous version I could download everything and now it seems that I have to selectively choose.  I'd like to select all the tags and export as CSV (ie. select *)  Is this possible?

<img width="1688" alt="image" src="https://user-images.githubusercontent.com/30630653/86797080-41efe400-c03d-11ea-821d-cd156d766f6d.png">

**Comment by torkelo** [comment]
Use the transformer to join the series to one table based on time
