### ISSUE TITLE
Unsigned external plugin

### ISSUE THREAD

**Issue by m9i** [grafana/grafana#26123]
**What happened**: After adding grafana-simple-json-datasource into paths.plugins `(allow_loading_unsigned_plugins="grafana-simple-json-datasource")` and the nrestarting the grafana-server actually nothing happened in the status of plugin and it is still unsigned. I read the previous issue related to this, and I wanted to make sure is it possible to sign this external plugin in this version or not. 

**Environment**:
- Grafana version: 7.0.5
- OS Grafana is installed on: Ubuntu18.4, Centos7
- User OS & Browser: Firefox
- Grafana plugins: simple-json-datasource

**Comment by torkelo** [comment]
The status does not change, it's still unsigned 

The setting just allow you to start & run unsigned plugins
