### ISSUE TITLE
A more helpful information, when accessing a dashboard while not logged in

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#26120]
Hey everybody,

we used Grafana without anonymous login. Now we have a organization for visitors in our Grafana instance.
Before this change users got redirected to the login page, if they are not logged in.
If they now want to access a dashboard, where you need to be logged in, you only get the error message "Dashboard not found".
Many users can't find the problem with this message and ask for help.

Is there a chance to add more information to this error message like ""Dashboard not found, maybe you need to login."?

Thanks in advance!

Best regards,
Patrick

**Comment by dprokop** [comment]
@Foxeronie can you provide us with some more information about the dashboard permissions setup and the organization? I'm not sure how exactly reproduce your setup.

Also, please provide Grafana version that you are using.

**Comment by Foxeronie** [comment]
Hey dprokop,

we use ldap for authentication.
The dashboard, where you need to be logged in, is in organization with id 1.
The mapping looks like this:

```
[[servers.group_mappings]]
group_dn = "cn=it,ou=group,ou=rgy,o=domain,c=de"
org_role = "Editor"
org_id = 1
```

We also have a new visitor organization with this mapping:

```
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
org_id = 55
```

In grafana.ini we set the anonymous auth section to this:

```
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = Visitors

# specify role for unauthenticated users
;org_role = Viewer
```

If I now open the link 'https://grafana.domain.de/d/000000014/specific-host-metrics?orgId=1&refresh=1m' I get the error message in the top right corner "Dashboard not found"

![Screenshot from 2020-07-08 15-22-51](https://user-images.githubusercontent.com/10115997/86924019-2b29ba00-c12f-11ea-9699-364cc7537592.png)

Now I sign in and open the link again and now everything is loading.
We have this with Grafana 6.7.4 and 7.0.5

If you need additional information please let me know.

Thanks in advance.

Best regards,
Patrick

**Comment by marefr** [comment]
@Foxeronie when your users gets the Dashboard not found error does their URL's include the `orgId` query string parameter with a value of the non-anonymous organization, e.g. as seen in https://play.grafana.org/d/0KapoFkMk/1-new-features-in-v7-0?orgId=1&refresh=5s?

**Comment by Foxeronie** [comment]
Yes, the ```orgId``` parameter is set.

```https://grafana.domain.de/d/ac35aw3r3c54w/specific-host-metrics-with-telegraf?orgId=1&refresh=1m```

**Comment by marefr** [comment]
@Foxeronie thanks. I think we should be able to fix this. Will open a PR

**Comment by analytically** [comment]
This breaks our previously working anonymous Grafana.

**Comment by marefr** [comment]
@analytically how? Please specify details. Maybe easier to open a separate bug report issue?
