### ISSUE TITLE
Unable to build Grafana from Source, struck at build.go

### ISSUE THREAD

**Issue by sahilbabbar** [grafana/grafana#26122]
**What happened**: Unable to build Grafana's v6.7.3 cde from source. Ran into the following error:

```
PS C:\SB\code\mm-grafana-ui\grafana> go run build.go build
Version: 0.0.1-alpha, Linux Version: 0.0.1, Package Iteration: 1594124694alpha
rm -r ./bin/windows-amd64/grafana-server.exe
rm -r ./bin/windows-amd64/grafana-server.exe.md5
go version
go version go1.14.4 windows/amd64
Targeting windows/amd64
go build -ldflags -w -X main.version=0.0.1-alpha -X main.commit=e03e0b1 -X main.buildstamp=1594037092 -X main.buildBranch=HEAD -mod=vendor -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server
# runtime/cgo
gcc_libinit_windows.c: In function 'x_cgo_sys_thread_create':
gcc_libinit_windows.c:57:12: error: implicit declaration of function '_beginthread' [-Werror=implicit-function-declaration]
   57 |  thandle = _beginthread(func, 0, arg);
      |            ^~~~~~~~~~~~
cc1: all warnings being treated as errors
go: failed to remove work dir: GetFileInformationByHandle C:\Users\ebbsaah\AppData\Local\Temp\go-build182830434\NUL: Incorrect function.
exit status 2
exit status 1
```

**What you expected to happen**:  Since GCC is added in `PATH` and `gcc --version` is giving appropriate output, the build process should have been succeeded. 

```
PS C:\SB\code\mm-grafana-ui\grafana> gcc --version
gcc (GCC) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**How to reproduce it (as minimally and precisely as possible)**: 
- Download Grafana Source v6.7.3.
- Run `yarn install`.
- Run `go run build.go build`.

**Anything else we need to know?**: GCC was installed using MSys2. 

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Source Code
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: NA
 - Others: NA

**Comment by aknuds1** [comment]
From reading [this issue](https://github.com/go-flutter-desktop/go-flutter/issues/162) it seems to be a GCC on Windows issue. Try TDM-GCC as documented [here](https://github.com/golang/go/wiki/InstallFromSource#install-c-tools).

**Comment by aknuds1** [comment]
Closing since it's a failure to build from the Go compiler's side, most likely depending on your toolchain.
