### ISSUE TITLE
Unable to run frontend from source, Grafana Toolkit Error

### ISSUE THREAD

**Issue by sahilbabbar** [grafana/grafana#26124]
**What happened**: After succesfull `yarn install`, `yarn start` fails:
```
PS C:\SB\code\mm-grafana-ui\grafana> yarn start
yarn run v1.18.0
$ grafana-toolkit core:start --watchTheme
error: unknown option '--watchTheme'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**What you expected to happen**: Frontend to be served.

**How to reproduce it (as minimally and precisely as possible)**:
- Run `yarn install`.
- Run `yarn start`.

**Anything else we need to know?**: Here, I'm trying to build and serve Grafana from source code on Windows 10. I am able to successfully build the backend via `go run build.go build`.

**Environment**: 
- Grafana version: 6.7.3
- Data source type & version: Source Code
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: NA
- Others: NA

**Comment by dprokop** [comment]
@sahilbabbar can you please share information about your node and yarn version?

**Comment by sahilbabbar** [comment]
**Versions**
- **Yarn:** 1.18.0
- **Node:** 12.18.2

**Comment by zqa2048** [comment]
hi,you can  
1、```yarn cache clean``` 
2、 ```yarn install --pure-lockfile``` 
3、 ```yarn start ```

**Comment by zoltanbedi** [comment]
Is this still an issue? If so I think we can reopen it and investigate. Closing now.
