### ISSUE TITLE
Grafana/ui: Segment control does not allow passing html attributes

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#26131]
https://github.com/grafana/grafana/blob/0e4850f203338fe8f052e92da9b03002074bdaef/packages/grafana-ui/src/components/Segment/Segment.tsx#L13

This creates problem for example with testing where you cannot add custom `test-id` or add `id` to reference from `<label for="">`.

**Comment by krvajal** [comment]
What html attributes do you expect to be able to pass, should it be treated as a `div` or do you have a specific subset in mind?
