### ISSUE TITLE
Grafana removes the 5s auto-refresh interval from json config

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26132]
**What happened**:

We have provisioned dashboards saved in json which have the following settings for auto-refresh: `5s,10s,30s,1m,5m,15m,30m,1h,2h,1d` (the default ones). When I change a page (or save the dashboard) the `5s` is removed from the `refresh_intervals` list, however, the `"refresh": "5s"` stays. We have not changed the minimum refresh interval, so I expect the default will be 5s as written in docs: https://grafana.com/docs/grafana/latest/administration/configuration/#min-refresh-interval

**What you expected to happen**:
I expect that the `5s` from the `refresh_intervals` list is not removed. We want to keep the lowest refresh rate to 5s.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run grafana (I run in docker `docker run -d -p 3000:3000 grafana/grafana`)
2. Create new dashboard (or import the one below)
3. Check that "5s" is missing from the `refresh_intervals`

(also check GIF)

![chrome-capture](https://user-images.githubusercontent.com/8693064/86804982-7f2d9380-c088-11ea-8ad5-e8d688123251.gif)

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 2,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "dataLinks": []
      },
      "percentage": false,
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "5s",
  "schemaVersion": 25,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "dubxEyMGz",
  "version": 1
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest Grafana v7.0.5 (efbcbb838b)
- Data source type & version: random walk
- OS Grafana is installed on: Docker
- User OS & Browser: macOS / Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@nikobearrr thanks for reporting this, it's indeed a strange behaviour and a bug that we going to investigate.

**Comment by peterholmberg** [comment]
Been investigating this but can't really figure out what's happening, everthing seems to be the way they're supposed to when you open dashboard settings. But when you change a section, then suddenly the 5s is gone. As early as in `SettingsCtrl::onRouteUpdated` the 5s is gone on the DashboardModel. Been looking at `DashboardModel::getSaveModelClone` to see if anything is happening there but can't find anything.

**Comment by nikobearrr** [comment]
Hey @peterholmberg, I saw in 7.1.0-beta3 there is this issue: https://github.com/grafana/grafana/pull/26150. Could it be related?

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/26615
