### ISSUE TITLE
Docs should suggest nodeenv or nvm for node

### ISSUE THREAD

**Issue by jsoref** [grafana/grafana#26144]
**What would you like to be added**:

**Why is this needed**:
#20041 identified that it's pretty easy to try to follow the instructions and have the build fail

```sh
$ yarn install --pure-lockfile
yarn install v1.22.4
[1/5] 🔍  Validating package.json...
error grafana@7.2.0-pre: The engine "node" is incompatible with this module. Expected version ">=12 <13". Got "14.4.0"
```

I can do:
```sh
$ brew install node@12
...
==> Pouring node@12-12.18.2.mojave.bottle.tar.gz
==> Caveats
node@12 is keg-only, which means it was not symlinked into /usr/local,
because this is an alternate version of another formula.

If you need to have node@12 first in your PATH run:
  echo 'export PATH="/usr/local/opt/node@12/bin:$PATH"' >> $HOME/.bash_profile

For compilers to find node@12 you may need to set:
  export LDFLAGS="-L/usr/local/opt/node@12/lib"
  export CPPFLAGS="-I/usr/local/opt/node@12/include"

==> Summary
🍺  /usr/local/Cellar/node@12/12.18.2: 4,295 files, 58.8MB
```
And note that it doesn't result in me getting the version of node that is desired by `yarn`:
```sh
$ node --version
v14.4.0
```

https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md#macos at least tried to give instructions.

I think that on linux it's even harder to ensure the version of node, so nodeenv or nvm is probably even more important...

**Comment by zoltanbedi** [comment]
@grafana/docs-squad fyi

**Comment by oddlittlebird** [comment]
@marcusolsson, does this go in the Developer guide?

**Comment by marcusolsson** [comment]
Yes, I think we should at least mention nvm somewhere in the Developer guide.

**Comment by oddlittlebird** [comment]
In that case, I recommend one of the engineers take this action item on. We are not very familiar with the Developer guide.

**Comment by GrafanaWriter** [comment]
This issue hasn't had activity in more than six months. In another week, I will close it.

If you comment or otherwise update it, we'll reset the clock.

**Comment by jsoref** [comment]
Still seems important

**Comment by jsoref** [comment]
@marcusolsson: could you find someone to do this?

**Comment by zoltanbedi** [comment]
@jsoref please open a PR for use if you feel strong about this.
