### ISSUE TITLE
[Grafana 2.2] Custom Time Ranges Don't Take Effect/Persist

### ISSUE THREAD

**Issue by deepyaman** [grafana/grafana#2614]
Selecting one of the preset "Last *" time ranges updates the dashboard immediately. However, upon selecting "Custom" and submitting a time range, nothing happens. Furthermore, if "Auto-Refresh" is on, the time range displayed on the dropdown menu reverts to the previously selected "Last *" time range (i.e. the time range reflected on the graphs).

As far as I can tell, updateTimeRange (in public/app/features/panel/panelHelper.js) isn't even getting called when a custom time range is selected. I haven't investigated the root of the problem thoroughly yet.

Tested with included Grafana data source and local Graphite data source.

**Comment by torkelo** [comment]
what commit / build date are you running from?

Recently fixed an issue with the time picker:
https://github.com/grafana/grafana/issues/2565
https://github.com/grafana/grafana/commit/abd7c15ba871204c4c269ba597f42efe8748f3b8

**Comment by torkelo** [comment]
I think this is fixed

**Comment by deepyaman** [comment]
Thank you! I missed finding this fix when searching yesterday.
