### ISSUE TITLE
Postgres exporter - New metrics are not being exposing to endpoint

### ISSUE THREAD

**Issue by srkfru** [grafana/grafana#26155]
**What happened**:
I am following the below link to add new metrics for Postgres. All configurations are showing good and Postgres exporter service also running fine without throwing any error. Not sure why i am not able to find custom metric details in endpoint.

https://github.com/wrouesnel/postgres_exporter

**What you expected to happen**:
This should have to show custom metric details in endpoint.

**How to reproduce it (as minimally and precisely as possible)**:

[Unit]
Description=Prometheus exporter for Postgresql
Wants=network-online.target
After=network-online.target

[Service]
User=postgres
Group=postgres
WorkingDirectory=/local_path/postgresql/postgres_exporter
EnvironmentFile=/local_path/postgresql/postgres_exporter/postgres_exporter.env
ExecStart=/usr/local/bin/postgres_exporter \
--web.listen-address=ip_address:9187 \
--web.telemetry-path=/metrics \
--extend.query-path=/local_path/postgresql/postgres_exporter/metrics.yaml
--disable-default-metrics=true \

Restart=always

[Install]
WantedBy=multi-user.target
**Anything else we need to know?**:

**Datasource Details**
DATA_SOURCE_NAME="postgresql://monitor:postgres@localhost:5432/postgres?sslmode=disable"

PG_EXPORTER_AUTO_DISCOVER_DATABASES=true
**Logs:**
No such error in the log file. Instead it is showing extented query are being uploaded from thes path *web.telemetry-path=/metrics --extend.query-path=/lowes/postgresql/postgres_exporter/metrics.yaml

**Environment**:
- Grafana version: 6.4.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Closing this as it's more of a prometheus data ingestion configuration / setup question rather than a Grafana bug report 

Please ask questions on the community site https://community.grafana.com
