### ISSUE TITLE
Support add user, team and org in provisioning

### ISSUE THREAD

**Issue by yangliuyu** [grafana/grafana#26153]
**What would you like to be added**:
In the current version, only dashboards, datasources and notifiers are supported in provisioning, want more configuration can be configured in provisioning such as users, teams, orgs and assign permission for folder or dashboard.

**Why is this needed**:
We have lots of projects need to deploy and configure grafana server, so we want it to be done automatically. But there is no internet access, and none of puppet, ansible are installed.  With provisioning, everything is ready after installing will be great.

**Comment by dprokop** [comment]
Similar feature requests: 
Teams provisioning: https://github.com/grafana/grafana/issues/21678
Orgs/users provisioning: https://github.com/grafana/grafana/issues/12119

**Comment by yangliuyu** [comment]
Hope can be supported like dashboard, datasources and notifiers via conf file besides API
<img width="1260" alt="Screen Shot 2020-07-09 at 10 37 30 AM" src="https://user-images.githubusercontent.com/1361821/86990926-63350980-c1d0-11ea-9dec-0fcc32a9e83d.png">
