### ISSUE TITLE
Graph: Improve the visibility of the threshold line 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#26152]
**What would you like to be added**: 

We would like to be able to customise threshold line thickness, or to have the threshold line ‘always on top’ (example below).  

![image](https://user-images.githubusercontent.com/54800912/86900811-1ab41800-c10c-11ea-9746-1e096852a62f.png)

**Why is this needed**:

We use the threshold feature for analysing response times, but as you can see below, if a chart has a lot of servers / series, the threshold line disappears behind the graph lines.    

![image](https://user-images.githubusercontent.com/54800912/86900875-2f90ab80-c10c-11ea-831d-9bced135b687.png)

#AK

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
