### ISSUE TITLE
Panel with "%" in legend causes invalid explore link

### ISSUE THREAD

**Issue by mem** [grafana/grafana#26169]
**What happened**:

selecting "explore" from the panel's takes me to an explore view with an empty query

**What you expected to happen**:

selecting "explore" from the panel's takes me to an explore view with that panel's query

**How to reproduce it (as minimally and precisely as possible)**:

create a panel where the legend contains a "%", select explore. See attached video for reference.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: prometheus (hosted prometheus)
- OS Grafana is installed on: Linux
- User OS & Browser: Linux / Chrome
- Grafana plugins: worldmap, synthetic monitoring
- Others:

![report](https://user-images.githubusercontent.com/189701/86942063-f05d5d00-c101-11ea-947d-36846366d2f6.gif)

**Comment by mem** [comment]
For the record, the reason why explore is not showing anything after changing the legend is because the query uses $__interval.

**Comment by ivanahuckova** [comment]
Closed in https://github.com/grafana/grafana/pull/28697
