### ISSUE TITLE
Gauge Panel when edited does not render properly

### ISSUE THREAD

**Issue by vmanju123** [grafana/grafana#26166]
**What happened**:
Gauge Panel when edited does not render properly

**What you expected to happen**:
Gauge Panel when edited should render properly

**How to reproduce it (as minimally and precisely as possible)**:
Edit Gauge Panel to make some changes, Close and check the gauge UI is rendered properly , when page is refreshed it does render properly again

**Anything else we need to know?**:
No

**Environment**:
- Grafana version:6.5.2
- Data source type & version:Elastic Search 7.2
- OS Grafana is installed on:Ubuntu 18.04
- User OS & Browser: windows + chrome browser
- Grafana plugins: built in plugins
- Others:
Before Editing

![image](https://user-images.githubusercontent.com/61594112/86936365-e50f2f00-c10b-11ea-9e5f-e0b589a8a780.png)

After Editing
![image](https://user-images.githubusercontent.com/61594112/86936432-fe17e000-c10b-11ea-88bf-da5a2c7efe3f.png)

**Comment by torkelo** [comment]
No other similar reports, and unable to replicate. 

Can you replicate this consistently? Tried Grafana 7.0? 

Any errors in the chrome dev console?

**Comment by vmanju123** [comment]
happens consistently on my server on ubuntu 18.04 and grafana 6.5

Tried in 7.0 and it doesn't happen there.

There are few errors in chrome dev console, anything particular to look for ?

thanks

**Comment by torkelo** [comment]
not that I can think of, closing this as it looks to be fixed
