### ISSUE TITLE
Guage Panel when there are multiple Gauges in single panel does not render as image properly, one first gauge is rendered as image

### ISSUE THREAD

**Issue by vmanju123** [grafana/grafana#26167]
**What happened**:
Gauge is setup to render as multiple gauges using same data source with different values
screenshot below
![image](https://user-images.githubusercontent.com/61594112/86936904-9ca44100-c10c-11ea-9211-a687d48636cb.png)

Edit - click Share - Direct link render as image

![image](https://user-images.githubusercontent.com/61594112/86937195-f3aa1600-c10c-11ea-95d9-137ad5f9d95c.png)

**What you expected to happen**:
When rendered as image all guages should appear

**How to reproduce it (as minimally and precisely as possible)**:
define a query for a gauge with atleast 2 gauges in same panel from same datasource, render as image and check

**Anything else we need to know?**:

**Environment**:
- Grafana version:
6.5.2
- Data source type & version:
Elastic database 7.2
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser: windows + chrome browser
- Grafana plugins: built in plugins
- Others:

**Comment by torkelo** [comment]
Unable to replicate, what types of queries do you use? are they all returned in one query or are you using mixed data source and querying multiple Elastic data sources? 

Can you show the network results of your queries? (open chrome dev tools network tab and hit refresh)

**Comment by vmanju123** [comment]
the problem after re-compiling code, please close this out, thanks

**Comment by zoltanbedi** [comment]
Thank you @vmanju123.
