### ISSUE TITLE
Query panel disappear after switching from one graphite datasource to another

### ISSUE THREAD

**Issue by MalKeshar** [grafana/grafana#26174]
**What happened**:
Query panel disappear after switching from one graphite datasource to another

Please, take a look on the attached screenshots. 
Before 
![Screenshot_20200708_194947](https://user-images.githubusercontent.com/13730780/86948528-eebd8480-c155-11ea-90af-da58b0a0d8b9.png)
and after
![Screenshot_20200708_183703](https://user-images.githubusercontent.com/13730780/86948525-ed8c5780-c155-11ea-810e-eb0925e1636d.png)
 switching datasources. 
Panel have disappeared.

Browser debug console shows

```
    XHR POST https://grafana.xxx.xxx/api/datasources/proxy/14/render
    [HTTP/1.1 200 OK 219ms]

error parsing target: Method not found reduceSeries graphite_query.ts:57:14
```

Switching back to previous datasource does not fix problem. Browser debug console shows up next error

```
    Uncaught (in promise) TypeError: t is undefined
        r promiseToDigest.ts:3
        value query_ctrl.ts:64
        t query_ctrl.ts:41
```

**What you expected to happen**:
I expect normal switch to new datasource
**How to reproduce it (as minimally and precisely as possible)**:
* Setup dashboard with reduceSeries function in query. 
* Switch to graphite datasource with carbonapi>=0.12.6 as backend

**Anything else we need to know?**:
Switching graphite api version in datasource settings from 1.1.x to 1.0.x fix the problem

**Environment**:
- Grafana version: 6.7.2, 6.7.3, 6.7.4
- Data source type & version: graphite datasource native plugin
- OS Grafana is installed on: ubuntu 14.04
- User OS & Browser: Firefox 78.0.1
- Graphite backend - carbonapi 0.12.6/0.13.0

**Comment by aocenas** [comment]
In graphite data source there is a definition of what functions exist for which version so switching the data sources with different version can throw something off there if a function in existing query does not exist in the new version (and I assume that is why it is switched to raw editor mode). I would say we should allow to have unknown (for the particular version) functions in the editor and just show error when executing (probably directly from Graphite which should say something like "unknown function" or something like that.)
