### ISSUE TITLE
Docs: Image rendering documentation enhancement

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#26173]
Since Grafana 7.0 there is a lack of understanding how you configure the image rendering plugin. The [image rendering documentation](https://grafana.com/docs/grafana/latest/administration/image_rendering/) also needs enhancements in general.

**Comment by marefr** [comment]
Think there should be a link to [configuration of the plugin](https://grafana.com/docs/grafana/latest/administration/configuration/#plugingrafana-image-renderer) from https://grafana.com/docs/grafana/latest/administration/image_rendering/#install-grafana-image-renderer-plugin

**Comment by achatterjee-grafana** [comment]
@AgnesToulet is working on the doc improvements.
