### ISSUE TITLE
Reorder rows under dashboard settings via drag an and drop

### ISSUE THREAD

**Issue by tuxinaut** [grafana/grafana#2617]
It is not possible to reorder dashboard `rows` under dashboard settings via drag and drop for now. It'd be nice if that were possible.

**Comment by PhilippWendler** [comment]
This is possible in Grafana 5. However, it took a very long time for me to find this feature, only after I read https://github.com/grafana/grafana/issues/6535#issuecomment-352442322 I looked around until I eventually found it. The drag handle is almost invisible on my screen.

Would it be possible to make the row title also a drag handle? That was the first thing I attempted.

**Comment by j-ulrich** [comment]
For everyone still not finding how to reorder row:
You have to **collapse them** before the drag handle becomes visible at the right side:
![Collapsed rows have a drag handle](https://user-images.githubusercontent.com/1260380/39814959-bb9c5862-5396-11e8-8678-a363675e324d.png)
At least for me in Grafana 5.2

**Comment by douglasg14b** [comment]
Ph jeez, it being on the far left seems like a poor UI choice with the width of many monitor setups.

**Comment by slyt** [comment]
It's nearly invisible with the dark theme.

![image](https://user-images.githubusercontent.com/5429371/120707834-6be59c80-c480-11eb-8037-9f5f7023e353.png)
