### ISSUE TITLE
Package doesn't seem to be served when pointing to jessie source

### ISSUE THREAD

**Issue by arthurlogilab** [grafana/grafana#2618]
Using ```deb https://packagecloud.io/grafana/stable/debian/ jessie main``` I get 

```
root@grafana:~# apt-get install grafana
Reading package lists... Done
Building dependency tree       
Reading state information... Done
E: Unable to locate package grafana
```

Is the package served there ?

**Comment by torkelo** [comment]
there is only a package for debian/wheezy but it will work in jessie as well (the are the same, and packagecloud make it really hard to mark a single package as available in multiple distro versions)

**Comment by torkelo** [comment]
just follow the docs guide:

```
Add the following line to your /etc/apt/sources.list file.

`deb https://packagecloud.io/grafana/stable/debian/ wheezy main`
```

**Comment by arthurlogilab** [comment]
@torkelo thanks for your reply, this is what I did, but I think having a jessie source would be a cleaner fix (or the documentation should mention this explicitly)

**Comment by Tyguy7** [comment]
I added that line to my sources.list file, but it still doesn't work on precise 32bit.

**Comment by torkelo** [comment]
@Tyguy7 only 64bit packages are provided by the official repositories / downloads, for 32bit you will have to build your own packages.
