### ISSUE TITLE
Links returned by "Local Snapshot" does not honor root_url

### ISSUE THREAD

**Issue by mapshen** [grafana/grafana#26180]
**What happened**: We run Grafana on host `abc.internal` with `root_url` set to `http://abc.public/grafana/`. Through nginx, end users can reach Grafana via http://abc.public/grafana/. When a user tries to share a dashboard with "Local Snapshot" in the UI , it returns a URL containing `abc.internal`, like http://abc.internal/dashboard/snapshot/kAp8ZPyDcFMhhip6XWAbxdp5rjpvW6WH. It is very annoying as our end users cannot access `abc.internal`. However, if you go to http://abc.public/grafana/dashboard/snapshots, snapshots there are listed correctly with `abc.public`.

**What you expected to happen**: The returned URLs should use the URL set in `root_url`. That is to say, in the above example, it should return  http://abc.public/dashboard/snapshot/kAp8ZPyDcFMhhip6XWAbxdp5rjpvW6WH, not  http://abc.internal/dashboard/snapshot/kAp8ZPyDcFMhhip6XWAbxdp5rjpvW6WH.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set `root_url` to something other than localhost name.
2. Open any dashboard in the UI.
3. Click on "Share dashboard" at the top.
4. In the popup, change to the "Snapshot" tab.
5. Click on "Local Snapshot" and wait for the returned URL.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: 6.5.2
- OS Grafana is installed on: Red Hat Enterprise Linux Server release 7.6 (Maipo)

**Comment by torkelo** [comment]
This is fixed in Grafana 7.0

**Comment by mapshen** [comment]
@torkelo thanks for you swift reply!

I went through the release notes again but still couldn't seem to find where it was mentioned. Would you mind pointing me to the issue/PR? I also searched through the old issues before opening this one but didn't see a similar problem reported.

**Comment by mapshen** [comment]
@torkelo I just tested 7.0.6, and the bug still exists.

**Comment by torkelo** [comment]
Ah, read your issue again. You need to set root_url to the public facing url

**Comment by mapshen** [comment]
I did...

>What happened: We run Grafana on host abc.internal with root_url set to http://abc.public/grafana/. Through nginx, end users can reach Grafana via http://abc.public/grafana/. When a user tries to share a dashboard with "Local Snapshot" in the UI , it returns a URL containing abc.internal, like http://abc.internal/dashboard/snapshot/kAp8ZPyDcFMhhip6XWAbxdp5rjpvW6WH. It is very annoying as our end users cannot access abc.internal. However, if you go to http://abc.public/grafana/dashboard/snapshots, snapshots there are listed correctly with abc.public.

**Comment by mapshen** [comment]
@torkelo can we reopen this?

**Comment by mapshen** [comment]
@torkelo Any chance to take a look at this issue? Like I said in the title and the description, `root_url` is set but not used for generated local snapshots.

**Comment by mapshen** [comment]
@torkelo Is there anything I could do to get this bug addressed? Any help is very much appreciated.

**Comment by torkelo** [comment]
I cannot replicate any problem, the links in the share modal is correct for me, it's using root_url 

<img width="777" alt="Screen Shot 2020-07-23 at 21 04 34" src="https://user-images.githubusercontent.com/10999/88328063-2ae10f80-cd28-11ea-9a7c-f1930b950566.png">

**Comment by mapshen** [comment]
@torkelo My apologies, you've been right!!!

I went back and triple checked our settings and found out a bug in our ansible role that caused the internal url to be set as `root_url`. After fixing that, this started to work as expected on both 6.5.2 and 7.0.6.

Again, thanks so much for the help!

**Comment by torkelo** [comment]
That is great to hear!
