### ISSUE TITLE
TypeError: Cannot read property 'ldapValue' of undefined

### ISSUE THREAD

**Issue by baur** [grafana/grafana#26197]
**What happened**:

LDAP -> Test user mapping -> type UserName -> RUN

![image](https://user-images.githubusercontent.com/2898361/87024257-b0c66c00-c1fa-11ea-9942-3987708479b0.png)

![image](https://user-images.githubusercontent.com/2898361/87023815-1b2adc80-c1fa-11ea-8f60-eb4c061cd7c8.png)

react-dom.production.min.js:196 TypeError: Cannot read property 'ldapValue' of undefined
    at o (LdapUserMappingInfo.tsx:23)
    at la (react-dom.production.min.js:154)
    at Su (react-dom.production.min.js:259)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
    at KqkS.t.unstable_runWithPriority (scheduler.production.min.js:18)
    at Wo (react-dom.production.min.js:120)
    at Ko (react-dom.production.min.js:121)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

LDAP -> Test user mapping -> type UserName -> RUN

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1 beta2
- Data source type & version:
- OS Grafana is installed on: Windows OS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by baur** [comment]
this error also was reproduced on v6.7.2 (423a25fc32)

**Comment by torkelo** [comment]
@alexanderzobnin any Ideas what this could be ?

**Comment by AgnesToulet** [comment]
Hello, I can't reproduce this error. Which LDAP DS are you using? Can you post the LDAP-related request response (hiding all the sensitive values in it)? (`/api/admin/ldap/<username>`)

**Comment by baur** [comment]
@AgnesToulet, 
try
domain\username

![image](https://user-images.githubusercontent.com/2898361/88254839-53411d80-ccd8-11ea-90dd-46cbd8670caa.png)
