### ISSUE TITLE
Explore: Saved/Shared Queries

### ISSUE THREAD

**Issue by rrajkomar** [grafana/grafana#26192]
It would be nice if we could save a query to be reused by other users at a later time.

Note I've seen other issues that look related and were closed but they did not fit the need exposed here : 
https://github.com/grafana/grafana/issues/18467
https://github.com/grafana/grafana/issues/16325

Indeed my suggestiosn here is not to provide tha ability to display the query result on a dashboard but to be able to save a predefined query on the explore view.

**Comment by dprokop** [comment]
@rrajkomar thank you for this feature request. We are considering introducing a shared query feature in the future, but I cannot tell exactly what the ETA is. There are multiple problems to be solved such as support for template variables, permissions etc.

Can you please provide some more information about your specific use case for this feature?

**Comment by torkelo** [comment]
Think this is asking for sever side persistence of explore query history

**Comment by rrajkomar** [comment]
Actually @torkelo I wasn't necessarily thinking of savinf the entire query history to a database.
More like choosing specific recurring queries ( for example "get all warning or higher log entries within the last 24 hours") and being able to save them

**Comment by torkelo** [comment]
Super confused , is that not exactly what explore query history does?

**Comment by rrajkomar** [comment]
Well, I guess in a way the query history could answer the need.
Though it would probably be a bit much, as any user could run a bunch of queries which may not be wanted in the feature I'm talking about.
I guess using the starred queries in the history could work as well although a user might star a query that is not wanted in the shared queries..

Is the query history specific to user or instance-wide ?
What about the starred queries ?

The idea here is to be able to share only the very important ones between users.

**Comment by dprokop** [comment]
@rrajkomar currently query history is only implemented client-side, meaning it's user-specific.

**Comment by rrajkomar** [comment]
In that case, for what I'm proposing a server side storage would be indeed necessary.
But I insist on the fact that the idea here is not to save all query histories to the server side.
Only specifically selected ones (or ones created specifically fotr the purpose of being shared).

**Comment by thomasboyt** [comment]
I think this missing feature is particularly an issue for Loki. It takes a lot of clicks to just get to "most recent logs for a service":

1. Click "Explore"
2. Click the data source dropdown at the top
3. Click a Loki data source
4. Click "Log browser" to open the label selector
5. Click the service's label
6. Click "Show logs"

I would prefer if I could just save a query and have it show up in, say, the side nav when I hover over "Explore". This would match my expectations from other log monitoring software I've used - everything from Papertrail to New Relic to Logentries has the concept of "saved queries" to make browsing easier. This is, I think, particularly important for applications where you want to keep a set of queries around to monitor specific jobs or requests. Ideally, these saved queries could also be reused for things like e.g. alerting or quickly picking a query to show on a dashboard panel.

For now, I've just bookmarked a few queries I'm using for logs. I suppose if I wanted to share them with other users in an organization, I could make a dashboard panel with text using a Markdown link for each one, though that doesn't feel particularly elegant.

**Comment by ivanahuckova** [comment]
We already have design for this ready, but we don't know in which release is this going to be added.

**Comment by baseely** [comment]
Hello @ivanahuckova and @ifrost Do we have an estimate when this feature be released ?

**Comment by yuejiang-code** [comment]
Honestly it's quiet embarrassing that grafana doesn't have this feature in 2023. All the other logging solutions allow you to save a query and share it with others so queries are easily accessible. there's no way i can remember which query to use from query history.

**Comment by ifrost** [comment]
Replaced by https://github.com/grafana/grafana/issues/77974
