### ISSUE TITLE
Grafana 2.2-pre with Influx 0.9 "host" tag value as IP address

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#2619]
Using influxdb 0.9.3 with templating for hostnames:
SHOW TAG VALUES FROM processor WITH KEY = host
my hosts are ip addresses and when i have for example two hosts 10.1.1.2 and 10.1.1.20
they both get selected when i select my host 10.1.1.2
i group by "host=~/$host/" 

perhaps this is just a influx query regex issue?

**Comment by Sotfo** [comment]
Maybe you shoud try "host=~/$host$/"

**Comment by torkelo** [comment]
you group by `host=~/$host/` ? you mean you filter by that statement, and group by time and host?

**Comment by discoduck2x** [comment]
@torkelo yes thats correct sry for wrong desc

**Comment by discoduck2x** [comment]
@Sotfo ,"host=~/$host$/" that works, ,, but its not the default influx query editor - should it be @torkelo

**Comment by torkelo** [comment]
@discoduck2x the query editor should suggest  /$host/ when you click the tag value and a dropdown / typeahead appears.

**Comment by discoduck2x** [comment]
@torkelo , yes it does,, but that seems to be the problem right? as @Sotfo suggestion solves it - but i dont know what else that might break. Are you able to replicate?

**Comment by torkelo** [comment]
@discoduck2x that is strange, not sure why it solves it, unless there is something strange with the influxdb query syntax that I do now know. 

Can you show the raw query sent to influxdb in the two cases? (open chrome dev tools network tab to inspect the raw query sent to inflxudb)

**Comment by torkelo** [comment]
I could not replicate any problem here. IP address in a multi select works fine without doing anything special with the query. 

![image](https://cloud.githubusercontent.com/assets/10999/9585693/bded21f2-5018-11e5-929d-c8d363138405.png)

**Comment by Sotfo** [comment]
@torkelo  seems like he has two host:
10.1.1.2
10.1.1.20
and of course when you select host:10.1.1.2 another host 10.1.1.20 also match "host=~/$host/", so add $  could fix this.

**Comment by discoduck2x** [comment]
@torkelo , exactly what @Sotfo has described:
![image](https://cloud.githubusercontent.com/assets/12600004/9599475/8ce02ba0-5094-11e5-9c83-67e98dfba8cb.png)

**Comment by torkelo** [comment]
I think it might be a problem with how the $host value turns into a regex multi value pattern like 
`(10\.60\.0\.4)|(10\.60\.0\.40)`

**Comment by discoduck2x** [comment]
@torkelo , sorry to bother again bout this , but do you think it will be fixed ? i can go with the workaround but would be nice that the dropdown in query editor was 100%

**Comment by torkelo** [comment]
yes, will fix soon
