### ISSUE TITLE
Setting decimals on axis to "1" shows 2 decimals on the tooltip

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26201]
**What happened**:
When I have a dashboard and I override the default (auto) decimals and put "1" I get a numer like XX.YY in the graph

**What you expected to happen**:
I expect:
- if I put 0 decimal to see XX
- if I put 1 decimal to see XX.Y

currently when:
- I put 0 decimal I see XX.Y
- I put 1 decimal I see XX.YY

**How to reproduce it (as minimally and precisely as possible)**:
Change any dashboard graph to Decimal: 1 on the axis

I have used this dashboard to reproduce it: https://play.grafana.org/d/000000016/graph-styles?orgId=1

This is how it looks with auto:

![Screenshot 2020-07-09 at 16 07 20](https://user-images.githubusercontent.com/8693064/87038157-66df8500-c1fe-11ea-8876-441b80e408c3.png)
y-axis: XX
tooltip: XX

I want to see numbers like XX.Y so I put "decimals: 1"

![image](https://user-images.githubusercontent.com/8693064/87038237-81196300-c1fe-11ea-9532-4f986b5c6b91.png)
y-axis: XX.Y
tooltip: XX.YY

Now the Y-axis shows XX.Y, but the tooltip shows XX.YY

so I set it to "decimals: 0"

![image](https://user-images.githubusercontent.com/8693064/87038359-a908c680-c1fe-11ea-917f-c146e7bf8865.png)
y-axis: XX
tooltip: XX.Y

It works as expected when I put "Y-axis decimal: 1" and also "Legend decimal: 1"

So, it might not be a bug, but I would expect to see the same Y-axis and tooltip since the "auto" looks the same for both.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.6 (9f4a172a76)
- Data source type & version: Graphite
- User OS & Browser: macOS / Chrome

**Comment by torkelo** [comment]
This is by design, the hover tooltip will always show 1 more decimal than Y-axis ticks as you want more precision when you hover to see the actual values.  

If you set the legend decimals (an option under legend) you can override this behavior
