### ISSUE TITLE
summarize stacked tooltip bug

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2620]
when using stacking on 2 graphite series with summarize function on one of them the tooltip goes crazy like this :

![grafana-stack-sum-bug](https://cloud.githubusercontent.com/assets/8385646/9565014/42f66348-4eb8-11e5-8c6b-338708baa5a7.gif)

**Comment by torkelo** [comment]
thanks for reporting this, fixed!

**Comment by rschitz** [comment]
wow that was fast, thanks!
