### ISSUE TITLE
user search works only on page 1

### ISSUE THREAD

**Issue by atartareanu** [grafana/grafana#26209]
**What happened**:
searching a user (/admin/users) will only work if you are on page 1. Even if you search for an user present on page 2 it will not work unless you are on page 1.

**What you expected to happen**:
user search should work no matter which page are you in.

**How to reproduce it (as minimally and precisely as possible)**:
just search for an user in other page except 1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: no need for this case
- OS Grafana is installed on: Windows 2019
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
thanks for reporting this: 

Bug is here: https://github.com/grafana/grafana/blob/3d98641a45540d7a89c5c4e398f5a1786711e849/public/app/features/admin/state/reducers.ts#L156 

Need to reset page to 0 when ever the search query changes
