### ISSUE TITLE
grafana table gradient gauge incorrect data

### ISSUE THREAD

**Issue by daldoyle** [grafana/grafana#26211]
**What happened**:
When making a table of data from Elasticsearch and trying to use the gradient gauge, it appears that multiple columns having the same aggregation function don't work properly. The last column with the same aggregation function seems to be referenced for drawing the scale maybe, but the current column's data is used. That's just a guess though. In the gif below you can see I have multiple Sum aggregation function columns, but the gradient gauge is clearly incorrect on the column I have it set on. If I disable the other Sum columns it suddenly starts working again.

![Kapture 2020-07-09 at 13 09 17](https://user-images.githubusercontent.com/7233444/87069697-a8176b00-c1e5-11ea-9076-fb9183fd3d18.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: ElasticSearch 7.X and driver that comes with Grafana
- OS Grafana is installed on: CentOS7
- User OS & Browser: Firefox 78.0.2

**Comment by torkelo** [comment]
You need to set a min & max on the field. The auto mode for min & max is based on all fields, which is why it looks better when you hide the other sum field

**Comment by daldoyle** [comment]
Okay, thanks. That at least explains what is going on. Is that the intended / desired behavior? I am trying to think of a use case where the gauge considering data from every column would be desired vs just the one it is configured on. I think this implies I cannot have more than one gauge per table, and I can only use the gauge display on the column with the largest values if I want to use auto scaling?
