### ISSUE TITLE
When I'm researching application logs in Loki, for some apps the auto-completion works and for others it doesn't

### ISSUE THREAD

**Issue by JnMik** [grafana/grafana#26213]
I'm not sure if this is a Grafana or a Loki bug, feel free to tell me to move it somewhere else if this is not the right place.

**What happened**:
If you start typing {container_name:"xxxx in the query bar, the auto-completion sometimes does not work. 
But if you type it all, and launch the query, results are returned so it suggests the autocomplete should have found the label. 

**What you expected to happen**:
I expect the auto-completion to work for every existing label values, at least for the selected time range.

**Anything else we need to know?**:
I believe it could be time related. The application that does not show up in the auto-completion has not reported anything in the last day. Even if I increase the time range in the top corner right before writing the query, it still not autocomplete.

**How to reproduce it (as minimally and precisely as possible)**:
Not quite sure, have a Grafana and a Loki running collecting logs of containers, and maybe see if it autocomplete works for  application that does not log frequently. 

**Environment**:
All the application lives in containers in Kubernetes
- Grafana version: Grafana v7.0.3 (00ee734baf)
- Data source type & version: Loki 1.5.0

Anyone else have this issue ?  
Thanks !

**Comment by JnMik** [comment]
Seems to be related to this call

/api/datasources/proxy/2/loki/api/v1/label/job/values?start=1594316315407000000&end=1594316325407000000

**Comment by JnMik** [comment]
It feels like the start date is generated based of current date minus few hours or something, 
could it respect the time range we set in the time range selector instead ?

**Comment by aocenas** [comment]
Yeah I think the issue is that we get the values for autocomplete only once, seems like we don't react to time range change so even if you change it you don't get any older values than those from the initial timerange.

**Comment by JnMik** [comment]
Great ! 
Thanks for the investigation. 

It happened so often someone calling me out on "Why is this application not tracked by loki ?" while clearly it is tracked, just didn't verbose logs in the last few hours. Every time it makes me doubt if the system is still functioning correctly hehe

**Comment by DSLCODE** [comment]
Hello, I found that when creating a new dashboard in grafana and adding variables (using loki as the data source), the refresh time range change is invalid, and the value of the variable is not refreshed according to the time range. Is this a current bug?

**Comment by ivanahuckova** [comment]
@DSLCODE yes, it is a current bug. Thanks for bringing it to our attention. I have created an issue https://github.com/grafana/grafana/issues/26943 for this and I will work on PR to fix it.

**Comment by DSLCODE** [comment]
> @DSLCODE yes, it is a current bug. Thanks for bringing it to our attention. I have created an issue #26943 for this and I will work on PR to fix it.

Thank you for your confirmation
