### ISSUE TITLE
Snapshot theme not applied if not logged in

### ISSUE THREAD

**Issue by beetlejuice1976** [grafana/grafana#2621]
Hi,

I have noticed the following behavior.

Context: I created a snapshot with light theme.

If I'm logged in Grafana on my browser, then open a new tab in my browser and access the snapshot -> snapshot will be displayed in light theme -> OK
If I'm logging out, and go to the snapshot tab -> snapshot will be displayed in the default theme (dark) -> not OK
And if I open the snapshot on a different browser where I'm not logged in Grafana at all, it will open in default theme (dark) -> not OK

**Comment by torkelo** [comment]
snapshot does not contain the theme, the theme is only an option on your user. So when you logout it will be shown with the default theme.

**Comment by The-Nik** [comment]
Where can I set the global default theme to light? Is it even possible?

**Comment by torkelo** [comment]
@The-Nik this option is currently only available in the user profile settings, there is no global option
