### ISSUE TITLE
Sign In / Login in  ignoring root_url option in v7.1.0-beta2 and 7.0.6

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#26228]
**What happened**:
Signing in from any area of Grafana does not work if grafana is running from a root URL containing a longer path. Sign Out and all other links within Grafana seem to work fine.

**What you expected to happen**:
Sign In button should contain the link including the root_url option from the grafana.cfg file.

**How to reproduce it (as minimally and precisely as possible)**:
Add a root URL to grafana.ini similar to this:
root_url = https://server.onmydomain.com/grafana

Go to sign into Grafana. Hovering over the Sign In link shows:
https://server.onmydomain.com/d/nsFkdjs3f/dashboard?orgid=1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0-beta2
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser:Win10/Chrome83
- Others: Nginx as a reverse proxy

**Comment by froehl** [comment]
It's the same with me, but already with the version **7.0.6**:
![image](https://user-images.githubusercontent.com/9552216/87143334-394e1680-c2a6-11ea-8603-06e21e107e94.png)

The login link is not created using option root_url. All other links are working.

root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/

**Environment:**
Grafana version: 7.0.6
OS Grafana is installed on: Ubuntu 18.04
User OS & Browser:MacOS/Firefox78.0.1/Safari
Others: Nginx as a reverse proxy with SSL termination

**Comment by dprokop** [comment]
Investigating

**Comment by Dalvany** [comment]
Hello, it seems to happen also with 7.0.6 version

**Comment by torkelo** [comment]
This is impacting 7.0.6 as well https://github.com/grafana/grafana/issues/26280

**Comment by essbo** [comment]
Impacting 9.3.2 aswell
