### ISSUE TITLE
Request feature to have business logic apply on multiple data sources

### ISSUE THREAD

**Issue by AkashSrivastava** [grafana/grafana#26221]
I know there is an option of using "mixed" to gather data from multiple data sources (eg. two mysql database) show it as table in the panel. I want a feature where we can apply business logic like joining the two tables and only giving values based on the join condition. Right now I can't find a way to join two tables from two DBs.

This is needed because it has the capability to join tables from same data source in a sql query, but not from two databases using a SQL query.

**Comment by torkelo** [comment]
You can use the new Transform feature in Grafana v7.0 for this https://grafana.com/docs/grafana/latest/panels/transformations/
