### ISSUE TITLE
bad links when working through reverseproxy (docker).

### ISSUE THREAD

**Issue by Anzic23** [grafana/grafana#26227]
**What happened**:
the link to some objects is not correct when working through reverse proxy.
**What you expected to happen**:
the authorization page opens.
**How to reproduce it (as minimally and precisely as possible)**:
use reverseproxy.
**Anything else we need to know?**:
no
**Environment**:
- Grafana version: v7.0.6 (9f4a172a76)
- Data source type & version: influxdb 1.8.0
- OS Grafana is installed on: Synology Docker
- User OS & Browser: Windows 10 & Chrome 83.0.4103.116
- Grafana plugins:
- Others:
![Температура и CO2 - Grafana - Google Chrome 2020-07-10 09-13-53](https://user-images.githubusercontent.com/37106885/87124090-bcfd0880-c290-11ea-8211-488e75df910d.gif)

**Comment by aocenas** [comment]
Hey @Anzic23, did you configure the [root_url](https://grafana.com/docs/grafana/latest/administration/configuration/#root-url) option correctly? That should be used to create the correct url for the link.

**Comment by niemalsnever** [comment]
This seems to not only affect the Docker Image. I'm running two Grafana instances on two different machines and access them through a reverse proxy. On one machine the reverse proxy is an Apache2 webserver, on the other it's an nginx webserver. On both instances I noticed, that the link to the Sign In page is broken and does not respect the root_url option. It used to work before Grafana 7.0.6.

So to hijack this issue like that.

**Comment by torkelo** [comment]
This is a duplicate , been reported before (think there is a fix merged as well)

**Comment by torkelo** [comment]
You need to set the root_url option to your public url
