### ISSUE TITLE
label_values not work

### ISSUE THREAD

**Issue by woodliu** [grafana/grafana#26222]
**What happened**:
We have multi-org in one grafana, and when i set up `Variables` like `label_values(up,instance)`， i can get value in `Main Org`，but can't in Non-`Main Org`, I set the same datasource for all the orgs.
By the way , i can get the right value from `label_values(instance)`, this is strange.
**What you expected to happen**:
I can get the same value in all orgs.
**How to reproduce it (as minimally and precisely as possible)**:
Always
**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.4.4
- Data source type & version: prometheus(thanos query), the metrics is ok in thanos query
- OS Grafana is installed on: redhat 7.6
- User OS & Browser: win10 & chrom
- Grafana plugins: 
- Others:

**Comment by woodliu** [comment]
I see the org will be abandoned in the future, i switch to use team/user permission to support my work, that is ok if this issue be igored

**Comment by woodliu** [comment]
I find when i use a new created dashboard，i can get the value... The reason may cased by `import dashboard`?

**Comment by torkelo** [comment]
> We have multi-org in one grafana, and when i set up Variables like label_values(up,instance)， i can get value in Main Org，but can't in Non-Main Org, I set the same datasource for all the orgs.

There is no difference in query execution between orgs, make sure the data source is configured the same in both orgs
