### ISSUE TITLE
Allow a user-text with Custom Variables

### ISSUE THREAD

**Issue by mzealey** [grafana/grafana#26258]
**What would you like to be added**:

Currently I understand that variables with Custom type only allow you to specify a comma-separated list of values eg `80,443,143`. It would be nice to have an extension to this so that the value displayed to the user could be different for example `80;HTTP (port 80),443;HTTPs (port 443)` etc.

**Why is this needed**:

There are many cases where we want to provide filters but the raw values we would be checking against in sql or graphite queries are not particularly user-friendly.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
