### ISSUE TITLE
Different intervals on a dashboard

### ISSUE THREAD

**Issue by dstreppa** [grafana/grafana#2625]
Actually the time interval is bound to the entire dashboard. It should be nice to have an indipendent interval for each row.

**Comment by torkelo** [comment]
Each panel can have its own interval, (set in the time range tab).

Look at second row in this dashboard:
http://play.grafana.org/dashboard/db/new-features-in-v20

**Comment by dstreppa** [comment]
Thank you @torkelo, the time override is useful, but it is not exactly what I meant. I was thinking about an entire menu (maybe smaller), with the scroll and the zoom out.

**Comment by dstreppa** [comment]
Probably not as default, it should be activated via menu.
