### ISSUE TITLE
Panel sizes are bigger in &.X than they were in 6.X

### ISSUE THREAD

**Issue by lukaszgryglicki** [grafana/grafana#26267]
**What would you like to be added**:

1. Hi, I'm using about 70 Grafana dashboards in about 60 projects. When I've tried to migrate from 6.X to 7.X I've noticed that, by default, all GUI elements are slightly bigger, so most items which were perfectly packed on the 6.X GUI now don't fit anymore and vertical scroll-bars are shown.
Is there a way of telling Grafana 7.X to use the same UI elements sizes as they were in 6.X?

**Why is this needed**:

To allow backwards compatibility with 6.X.

cc @torkelo

**Comment by torkelo** [comment]
There was never any big change in element sizes in 7.0, maybe a pixel here or there but nothing major that I recall, maybe you hit browser zoom? 

Can't find any elements that changed in dashboards, panel titles & panel sizes are the same, so is the dashboard header. 

But even if we did a change, there is no option to change it back (maybe via code change if we changed something by mistake or that had bigger breaking impact than we anticapted)

**Comment by lukaszgryglicki** [comment]
Hmmm, browser zoom is at 0 (this was the first thing I've checked) but still when I use the same set of dashboards on 7.X they don't fit, while in 6.X they fit perfectly. dashboard JSONs are the same, only Grafana version changes... Anyway, I'll wait for few more fixes before attempting to switch to 7.X again. Thanks for the info.
