### ISSUE TITLE
Ability to Share Dashboards Between Organisations  

### ISSUE THREAD

**Issue by wizzfizz94** [grafana/grafana#26261]
**What would you like to be added**:
The ability to share dashboards between organisations. A use case would be i create a dashboard now i want to share it across organisation A and B but not C and point the same dashboard at separate data sources for each organisation it is shared with. 

**Why is this needed**:
This is need because often organisations want access to the same dashboards but keeping copies on each organisation becomes unmaintainable as we make changes. While in some cases this could be simplified by placing users under the same organisation we also wish to utilise the multi tenanting features of organisations to keep the access of different organisational data separate.

**Comment by torkelo** [comment]
> This is need because often organisations want access to the same dashboards 

Organizations are designed for multi-tenancy (so isolated customers / companies). 

If you want to sync dashboards across orgs I suggest building automation tooling that uses the HTTP API

**Comment by wizzfizz94** [comment]
>Organizations are designed for multi-tenancy (so isolated customers / companies).
Yes but it'd still be very useful to share dashboard structures but load different configs into them. That is, sync dashboard layout, panels, queries but load different data sources. Multi tenancy is a still possible and required for the feature to be useful. 

For example if I'm a company selling data analytics to farmers I'm going to want to the same dashboards for all my different farm organisations because they essentially are going to have data relating to the same topics (rainfall, etc). Instead i have to make these multiple times for each client. Seems like a common use case.

>If you want to sync dashboards across orgs I suggest building automation tooling that uses the HTTP API
I guess i'll pursue this. Maybe incorporate at some point.
