### ISSUE TITLE
Autocomplete not working (2.1.3)

### ISSUE THREAD

**Issue by vaisakhb** [grafana/grafana#2627]
Upgraded grafana today from 2.0.2 to 2.1.3.
Datasource: Opentsdb

 When metric name is entered its resulting in "Completed /api/query 500 Internal Server Error " (Autocomplete is working though. red icon is seen on the top left of the graph but it disappears in a few seconds) and when a tag is entered autocomplete is not working and resulting in error " Completed /api/search/lookup 400 Bad Request"
tsd log says : "12:26:43.971 WARN  [HttpQuery.logWarn] - [id: 0xe2503236, /10.10.210.169:46063 => /10.10.210.49:4242] Bad Request on /api/search/lookup?m=custom.mem.free%7BHost%3D*%7D: Invalid search query type supplied"

**Comment by torkelo** [comment]
what version of OpenTSDB do you have?

You need to enable this OpenTSDB setting for autocomplete to work in Grafana 2.1 
`tsd.core.meta.enable_realtime_ts`     (this option will enable the OpenTSDB lookup api that Grafana 2.1 uses),
