### ISSUE TITLE
data outside time range message

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#26279]
**What happened**: Get a message Data outside time range

**What you expected to happen**: To show no data or an option to change the message

**How to reproduce it (as minimally and precisely as possible)**: When grouping data by day, by default grafana will set the time to 00:00. But if the time now is for example 12PM and the timepicker is set to show the last 3 hours, the hour 00:00 will not show up on our timerange. 

**Anything else we need to know?**:
This is related to my previous bug #24625  where i explained that this happens with Influx as well.
This happens to us when within the same dashboard we want to display both hourly summary data and daily summary data, simultaneously, using different group by methods.
For example, we want to show a daily summary of the data, but when use the variable $__interval, even when we choose a timespan of 7 days it many times will not default to a minimum interval of 1d. so we need to hard code the minimum value which causes this problem.

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: Influx DB
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome
- Grafana plugins:
- Others:
![image](https://user-images.githubusercontent.com/1325158/87281939-698ef280-c4fc-11ea-9c73-36f22bf60d18.png)

**Comment by yonigaliz** [comment]
we upgraded to v7.2.0-beta1.  
the message still appears.
![image](https://user-images.githubusercontent.com/56247038/93456399-51fe2c80-f8e6-11ea-9562-c6b67c736d9b.png)

**Comment by muppet3000** [comment]
What is the correct way to resurrect this issue? I'm also still seeing the issue on the latest version of the docker image (7.4.2).

Screenshot below:
![image](https://user-images.githubusercontent.com/10612068/108630210-94aace80-745b-11eb-8dab-ba5498205593.png)
