### ISSUE TITLE
Loki: label_values() - Use series API instead of labels API 

### ISSUE THREAD

**Issue by pcbl** [grafana/grafana#26281]
**What would you like to be added**:
When using a Loki Datasource I would like to filter the results of the Query on the query itself(instead of the regex property). On that light I could use for example the " Value group/tags" to filter and so on. I actually opened an issue on Loki, but they mentioned that this seems to be an improvement to be done on Grafana.

Please refer to https://github.com/grafana/loki/issues/2319 to get more info.

**Comment by aocenas** [comment]
I think this is duplicate of https://github.com/grafana/grafana/issues/25205 and https://github.com/grafana/grafana/issues/20311 so I am closing this but feel free to reopen if you think this is different issue.
