### ISSUE TITLE
Return more OAuth information for users in the REST API

### ISSUE THREAD

**Issue by rikimaru0345** [grafana/grafana#26284]
The users API does not return much information about the used OAuth Provider.
https://grafana.com/docs/grafana/latest/http_api/user/#search-users

Grafana returns its internal user id (the ID in Grafanas own database), but it does not return the ID of the Google Account that was used to login. 

**What would you like to be added**:

Add an "oauth_data" object to the response, that at least contains:
- the name of the OAuth Provider the user used to login
- and the corresponding "internal ID" for that user (the "unique ID" one can use at the provider to find the user) 

**Why is this needed**:

The unique Google IDs identify a user even when they have logged in using a different email address (using an alias email, or secondary email).

Another example where IDs are important is the scenario where a Google User `abc@company.com` logs in using `abc+grafana@company.com`...

Since email addresses alone are not enough of a unique identifier, being able to get the "internal ID" of a user for whatever OAuth provider the user used to login solves all of those problems.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
