### ISSUE TITLE
Intermittent "unauthorized" errors with v 2.1.1

### ISSUE THREAD

**Issue by efrecon** [grafana/grafana#2628]
I am getting intermittent unauthorized errors looking like the following one when talking to a KairosDB installation:

    Completed /api/datasources/proxy/1/api/v1/datapoints/query 401 Unauthorized in 5.079508ms

I *think* that these are the reason why some of "my" curves disappear from time to time (they reappear on reload, most of the time). I wonder if this would be related to [#1861](https://github.com/grafana/grafana/issues/1861), or a duplicate? @torkelo mentioned there that he was working on a fix, what is the state of this fix?

**Comment by torkelo** [comment]
the KairosDB datasource is not calling the data source proxy the right way (like the the other data sources), this is likely caused by a session timeout, but this is handled via special call mechanism in the frontend that renews the session

**Comment by torkelo** [comment]
will fix soon

**Comment by efrecon** [comment]
Tack (Thank you) Torkel.
