### ISSUE TITLE
Graph Panel: Unnecessary scroll on dashboard legend

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26295]
**What happened**:
When I put my mouse on a dashboard sometimes I hit an invisible scroll. I opened an issue regarding a scroll which shouldn't have been there ( https://github.com/grafana/grafana/issues/23795 ) which is now fixed. But it seems there is still something going on.

**What you expected to happen**:

Not to be able to scroll in a dashboard

**How to reproduce it (as minimally and precisely as possible)**:
1. Use provided panel json
2. Put your mouse on the legend for "last 24h"
3. Scroll up/down and see it move

I can reproduce it 100%, it's probably not the biggest deal breaker though. Here is a gif where I try to show what happens:

![grafana-scroll](https://user-images.githubusercontent.com/8693064/87316170-7af4f080-c536-11ea-955c-509a40a1bf2c.gif)

panel json:

```
{
  "gridPos": {
    "h": 5,
    "w": 8,
    "x": 0,
    "y": 0
  },
  "id": 9,
  "links": [],
  "maxDataPoints": 100,
  "targets": [
    {
      "refId": "A",
      "target": "alias(integral(grafana.usagestats.all.stats.orgs.count), 'last 24h')"
    }
  ],
  "title": "title",
  "type": "graph",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "short",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "mappings": [
        {
          "op": "=",
          "text": "N/A",
          "value": "null",
          "id": 0,
          "type": 1
        }
      ],
      "nullValueMode": "connected"
    },
    "overrides": []
  },
  "options": {
    "dataLinks": []
  },
  "pluginVersion": "7.0.6",
  "renderer": "flot",
  "yaxes": [
    {
      "label": null,
      "show": true,
      "logBase": 1,
      "min": null,
      "max": null,
      "format": "short",
      "$$hashKey": "object:461"
    },
    {
      "label": null,
      "show": true,
      "logBase": 1,
      "min": null,
      "max": null,
      "format": "short",
      "$$hashKey": "object:462"
    }
  ],
  "xaxis": {
    "show": true,
    "mode": "time",
    "name": null,
    "values": [],
    "buckets": null
  },
  "yaxis": {
    "align": false,
    "alignLevel": null
  },
  "lines": true,
  "fill": 1,
  "linewidth": 1,
  "dashLength": 10,
  "spaceLength": 10,
  "pointradius": 2,
  "legend": {
    "show": true,
    "values": true,
    "min": true,
    "max": true,
    "current": true,
    "total": true,
    "avg": true,
    "alignAsTable": true
  },
  "nullPointMode": "null",
  "tooltip": {
    "value_type": "individual",
    "shared": true,
    "sort": 0
  },
  "aliasColors": {},
  "seriesOverrides": [],
  "thresholds": [],
  "timeRegions": [],
  "timeFrom": null,
  "cacheTimeout": null,
  "interval": null,
  "fillGradient": 0,
  "dashes": false,
  "hiddenSeries": false,
  "points": false,
  "bars": false,
  "stack": false,
  "percentage": false,
  "steppedLine": false,
  "timeShift": null,
  "datasource": null
}
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.6 (9f4a172a76)
- User OS & Browser: macOS Catalina 10.15.5 (19F101) / Chrome 83.0.4103.116 (Official Build) (64-bit)

**Comment by ivanahuckova** [comment]
Hello @nikobearr, I am not sure if I would classify this as an issue. The scroll in legend appears only if the dashboard panel is too short. The same way, we get the scrollbar in legend if the panel is too narrow. Let me review it with UX team and I'll get back to you. 🙂
![Kapture 2020-07-15 at 16 38 40](https://user-images.githubusercontent.com/30407135/87558736-b9ff7f00-c6b9-11ea-99b4-2a03349a8128.gif)

**Comment by nikobearrr** [comment]
Hi @ivanahuckova , as you can see from the json and the gif the space for the legend is enough. It seems to only happen when height is 5 and there is only 1 series. However as I said, it's a very small thing

**Comment by torkelo** [comment]
This looks like not a bug, tested this and the legend is overextending it's area and so you get a scrollbar
