### ISSUE TITLE
Panel Links: Update panel links icons as they are barely visible

### ISSUE THREAD

**Issue by JensRantil** [grafana/grafana#26308]
I have multiple dashboards where I've added a "Link" on the dashboard for further drill-down in another graph. In theory, this is great! However, the problem is that the link (marked with a red square) is barely visible on the panels:

![image](https://user-images.githubusercontent.com/730342/87343600-6bcd6d00-c54d-11ea-8731-01182ecb008b.png)

I've told at least 10 people about the links and none of them have noticed it before I tell them.

**Feature request:** Somehow make the links more visible and stick out.

**Comment by dprokop** [comment]
@sarlinska could we get some help from the UX squad here in 7.2?

**Comment by torkelo** [comment]
making this part of https://github.com/grafana/grafana/issues/31080
