### ISSUE TITLE
Cloudwatch: Allow serialised query execution for Insights Panels

### ISSUE THREAD

**Issue by JohnKLewisPA** [grafana/grafana#26307]
**What would you like to be added**:
I would like to be able to add a concurrency limit and queue up requests from panels in the same dashboard for cloudwatch insights queries.

**Why is this needed**:
AWS limits concurrency of insights requests to 4, and have a "soft cap" of 10 concurrent requests. If the dashboard has more than 8-9 queries even with the upper limit some panels fail to refresh based on a 400 from CW Insights.

**Comment by StephenKing** [comment]
This issue would be fixed by #28176, I think

**Comment by aocenas** [comment]
Yes this should be implemented and enabled by default in Grafana v8. It is implemented on the backend so there is single queue for all queries in a single account and region but if there are multiple grafana instances or queries come from other sources there still could be an issue.
