### ISSUE TITLE
backround color of light login is black

### ISSUE THREAD

**Issue by x70b1** [grafana/grafana#26309]
**What happened**:

I set the `light` theme as default. The background of the login page is black. This seems to be wrong. 
I'm not sure if it was already in 7.1.0-beta1. But it was in 7.1.0-beta2 too.

![2020-07-13-21:17:43-screenshot](https://user-images.githubusercontent.com/10016267/87344261-645a9380-c54e-11ea-9cba-b5b3c51f6235.png)

**Environment**:
- Grafana version: 7.1.0-beta3
- OS Grafana is installed on: Debian 10
- User OS & Browser: testet on Firefox and Chromium

**Comment by ivanahuckova** [comment]
Hello @x70b1, Grafana theme has no impact on login screen. For both themes, you get the same login page that should look like this: 
![image](https://user-images.githubusercontent.com/30407135/87563777-e9b18580-c6bf-11ea-878a-cef00ccd017d.png)

Login screen customisation/change of background is possible only in [enterprise version](https://grafana.com/docs/grafana/latest/enterprise/white-labeling/). If you are on enterprise version, please reach out to Grafana maintainer/admin regarding this.

**Comment by x70b1** [comment]
Well, thats wrong.
I tested it again. I used the docker images from docker hub.

Version 7.0.6 - I used the default settings on the latest stable. Everything works.
```
[users]
default_theme = dark
```
![2020-07-15-19:21:20-screenshot](https://user-images.githubusercontent.com/10016267/87576010-0904de80-c6d1-11ea-85db-a93fad3749e3.png)

Version 7.0.6 - The latest stable version. The `light` theme changes the login to a white page. As expected.
```
[users]
default_theme = light
```
![2020-07-15-19:21:43-screenshot](https://user-images.githubusercontent.com/10016267/87576012-099d7500-c6d1-11ea-8877-59b0a545a8bf.png)

Version 7.1.0-beta3 - this leads to the black background as described on my first post. The same for the `master` image from docker hub.
```
[users]
default_theme = light
```
![2020-07-15-19:22:30-screenshot](https://user-images.githubusercontent.com/10016267/87576013-0a360b80-c6d1-11ea-8206-a04f9a2da5a3.png)

**Comment by ivanahuckova** [comment]
Yes, you are correct. Sorry for the confusion! I just tested this and could replicate the issue. Thanks for creating it, we will look at it!

**Comment by ivanahuckova** [comment]
Thanks again for creating this issue! 🙏 I have created a fix for this.

**Comment by x70b1** [comment]
Thx :sunglasses:
