### ISSUE TITLE
display name of stat panel is missing

### ISSUE THREAD

**Issue by x70b1** [grafana/grafana#26310]
**What happened**:

I updated to 7.1.0-beta3. The stat panel now dont show the `display names`.
It would be cool if they come back. 

**Environment**:
- Grafana version: 7.1.0-beta3
- OS Grafana is installed on: Debian 10
- User OS & Browser: testet on Firefox and Chromium

**Comment by ivanahuckova** [comment]
Hello @x70b1, please use the[Enhancement request template ](https://github.com/grafana/grafana/issues/new?labels=type%3A+feature+request&template=2-feature_request.md). Also, have you seen this PR #25676 that adds the option show name instead of value and more?

**Comment by x70b1** [comment]
Okay, at this topic you are right. 
The linked feature is responsible for the behavior. But it was a bit unexpected to me. 

Thanks a lot!
