### ISSUE TITLE
Heatmap with time-series buckets skips bucket titles too enthusiastically in 7.0

### ISSUE THREAD

**Issue by epvuc** [grafana/grafana#26317]
I have a heatmap using time-series buckets constructed from graphite queries against a series of 15 servers (just polling load average) so I can see a stack of 15 horizontal tracks whose cell colors indicate load average over time, one for each server.

Looks like https://github.com/grafana/grafana/pull/24351 did this, but a sparse set of text labels doesn't make that much sense compared to a sparse set of numbers where you can infer the intermediate values. 

**What happened**:
In 6.7, this heatmap showed all 15 bucket titles on the y-axis.  In 7.0.6 it is skipping every other (or more) bucket label. It looks like this is to avoid vertically crowding text, because if I greatly expand the panel to be very tall, it eventually shows all of them. But it's going much too far, because the text wasn't crowded in 6.7 without skipping labels. 

![ss](https://user-images.githubusercontent.com/4994138/87382872-e2b63600-c54c-11ea-8edf-0feb22b895d5.png)

This doesn't seem to be browser-dependent at least between safari, firefox on windows, firefox on linux, and edge on windows 10.

**What you expected to happen**:
The bucket labels should preferentially all be displayed unless there are too many stuffed into too small a vertical space. And even then it might be best to do it anyway, and let the user choose to skip labels as needed.

**How to reproduce it (as minimally and precisely as possible)**:
Create a heatmap panel, set the type to time-series buckets, and apply a query that produces 10+ results. (see following panel json).  Something as simple as the fofllowing (with a graphite datasource) is enough:

`aliasByNode(averageSeries(librenms.*.processors.processor.hr.*.usage), 1)"`

**Anything else we need to know?**:

**Environment**: 
- docker container from dockerhub "grafana/grafana"latest"
- Grafana version: 7.0.6 
- Data source type & version: graphite 0.9.x
- OS Grafana is installed on: alpine 3.11.6 
- User OS & Browser: ubuntu 16.04 + firefox, windows10 + firefox, osx + safari
- Grafana plugins: heatmap, graphite
- Others:

Here is the panel json that produced the screenshot image: 

```
{
  "cards": {
    "cardPadding": null,
    "cardRound": null
  },
  "color": {
    "cardColor": "#b4ff00",
    "colorScale": "sqrt",
    "colorScheme": "interpolateRdYlGn",
    "exponent": 0.5,
    "mode": "spectrum"
  },
  "dataFormat": "tsbuckets",
  "datasource": "myserver.net",
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "gridPos": {
    "h": 8,
    "w": 12,
    "x": 5,
    "y": 0
  },
  "heatmap": {},
  "hideZeroBuckets": false,
  "highlightCards": true,
  "id": 8,
  "legend": {
    "show": false
  },
  "pluginVersion": "6.6.2",
  "reverseYBuckets": true,
  "targets": [
    {
      "refCount": 0,
      "refId": "A",
      "target": "aliasByNode(averageSeries(librenms.server1_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "B",
      "target": "aliasByNode(averageSeries(librenms.server2_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "C",
      "target": "aliasByNode(averageSeries(librenms.server3_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "D",
      "target": "aliasByNode(averageSeries(librenms.server4_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "E",
      "target": "aliasByNode(averageSeries(librenms.server5_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "F",
      "target": "aliasByNode(averageSeries(librenms.server6_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "G",
      "target": "aliasByNode(averageSeries(librenms.server7_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "I",
      "target": "aliasByNode(averageSeries(librenms.server8_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "J",
      "target": "aliasByNode(averageSeries(librenms.server9_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "K",
      "target": "aliasByNode(averageSeries(librenms.server10_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "L",
      "target": "aliasByNode(averageSeries(librenms.server11_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "M",
      "target": "aliasByNode(averageSeries(librenms.server12_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "N",
      "target": "aliasByNode(averageSeries(librenms.server13_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "H",
      "target": "aliasByNode(averageSeries(librenms.server14_pri.processors.processor.hr.*.usage), 1)",
      "textEditor": true
    },
    {
      "refCount": 0,
      "refId": "O",
      "target": "aliasByNode(librenms.switch.processors.processor.cpm.1.usage, 1)",
      "textEditor": true
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "CPU",
  "tooltip": {
    "show": true,
    "showHistogram": false
  },
  "type": "heatmap",
  "xAxis": {
    "show": true
  },
  "xBucketNumber": null,
  "xBucketSize": null,
  "yAxis": {
    "decimals": 0,
    "format": "percent",
    "logBase": 1,
    "max": null,
    "min": null,
    "show": true,
    "splitFactor": null
  },
  "yBucketBound": "middle",
  "yBucketNumber": null,
  "yBucketSize": null
}
```

**Comment by epvuc** [comment]
This change happened between 7.0.3 and 7.0.4: 

**7.0.3:**
<img width="598" alt="grafana703" src="https://user-images.githubusercontent.com/4994138/87463483-50eb0f00-c5c6-11ea-9c57-21ed97946cca.png">

**7.0.4**
<img width="602" alt="grafana704" src="https://user-images.githubusercontent.com/4994138/87463495-57798680-c5c6-11ea-9d8f-bb853bf3c3da.png">

**Comment by ivanahuckova** [comment]
fyi @alexanderzobnin

**Comment by dguendisch** [comment]
Also found here: https://community.grafana.com/t/heatmap-w-time-series-buckets-rendering-problem/33503

**Comment by lucasnodari** [comment]
I am also having this problem, 

This is after updating grafana:

![missing](https://user-images.githubusercontent.com/6663084/88120198-c6437a80-cb98-11ea-909d-81997e541493.png)

This is before, on version 7:

![correct](https://user-images.githubusercontent.com/6663084/88120377-23d7c700-cb99-11ea-9582-be90683699e2.png)

It can be seen that the labels do not overlap each other, but even so, all of them are meaningful and need to appear.

**Comment by mveroone** [comment]
I had to rollback to 7.0.3 here, it was very disturbing.
I'm not very comfortable with the code, but maybe it can be as simple as lowering `DEFAULT_Y_TICK_SIZE_PX` in https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/heatmap/rendering.ts ?

**Comment by epvuc** [comment]
I've tried fidling with rendering.ts a bit but I don't really know what I'm doing enough to make a useful patch. Just changing the tick size doesn't work.

**Comment by mveroone** [comment]
I Believe you cannot change the file directly, it must be compiled or
something like that...

**Comment by lrstanley** [comment]
Please take a look at PR https://github.com/grafana/grafana/pull/27016 -- I reduced the height of the ticks by a bit more than 50%, which should make it hide them when they're quite a bit smaller.

**Comment by mmedvede** [comment]
I think this new behavior should be optional. Even partially hiding labels makes the heatmap misleading. For example you may think there are only 3 rows, while there are actually 30. I would rather see all labels crowded, ugly, and unreadable vs just a subset of labels.

**Comment by lucasnodari** [comment]
@mmedvede totally agree with this, I use heatmaps a lot, not seeing a label hides some important information
