### ISSUE TITLE
Elasticsearch timestamps shows wrong in Logs view

### ISSUE THREAD

**Issue by pvillarragut** [grafana/grafana#26322]
I have a grafana dashboard with Log visualization of a Elasticsearch datasource. I have set the dashboard and the user profile timezone configuration to UTC. 

**What happened**:
The time displayed in Logs graph is UTC- 2 hours. Instead,  if I change the visualization to a Table type the timestamp shows correctly UTC times. 

**What you expected to happen**:
Timestamp showed in log visualizations has to be the same that in a table or graph . 

**How to reproduce it (as minimally and precisely as possible)**:
You can see this behavior easily with  Grafana Explore dashboard. 

Here we can see the correct timestamps in UTC timezone:

![Screenshot from 2020-07-14 12-48-47](https://user-images.githubusercontent.com/11637021/87417433-74b35280-c5d0-11ea-8b24-81cb53a3ea80.png)

Now If I change the view to logs the date is UTC - 2h (but the graph  remains with the correct time):

![Screenshot from 2020-07-14 12-50-45](https://user-images.githubusercontent.com/11637021/87417587-b8a65780-c5d0-11ea-836b-5aa8b4c01773.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Tested in Grafana 6.7.3 and 7.0.3
- Data source type & version: Elasticsearch Data Source querying data to  AWS Elasticsearch Service version 6.4 
- OS Grafana is installed on: k8s 1.16
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
Could be an issue of how we handle timezone in logs panel when we changed user preferences from allowing just UTC/local to allow any timezone.

At the same time in logs panel we show time in the other timezone as title (so will show on hover), question is whether we should keep that behavior somehow or just remove the on hover version altogether.

**Comment by aocenas** [comment]
I can't really reproduce this on the version you mentioned nor on current master. If this is still happening for you please also post an elastic response data.

**Comment by apollo13** [comment]
@aocenas I am seeing this as well. As an example:
![Screenshot from 2021-08-20 19-21-42](https://user-images.githubusercontent.com/81547/130270742-2f80cc41-ef1b-49d7-87ae-3e9a9ef0c446.png)

The count metrics are generated (properly I think) from Elasticsearch and displayed as such. When Grafana displays the timestamp field, it seems to take it as local time though, because it misses a Z at the end maybe? The response data ist:
```
"_source": {
    "gl2_accounted_message_size": 461,
    "level": 7,
    "gl2_remote_ip": "10.7.220.110",
    "gl2_remote_port": 49219,
    "streams": [
      "000000000000000000000001"
    ],
    "gl2_message_id": "01FDJ6QGGMNTM0Y7VVWVQX37VS",
    "txId": "kbv6cu78-95bz",
    "source": "xxxxx",
    "message": "Removing transaction: TxData [txId=kbv6cu78-95bz, ip=10.7.220.110, txExecTime=243ms]",
    "gl2_source_input": "5a0ea3942ab79c00012d35ed",
    "userId": "cm",
    "full_message": "Removing transaction: TxData [txId=kbv6cu78-95bz, ip=10.7.220.110, txExecTime=243ms]",
    "service": "ro-gate",
    "thread_name": "http-nio-8080-exec-9",
    "clientIp": "10.7.220.110",
    "gl2_source_node": "fd7a6e0a-b84e-4b80-bef4-83e16778f5ce",
    "logger_name": "yyyy",
    "timestamp": "2021-08-20 16:36:28.819"
  }
```

Looking at the mapping configuration, the field is configured like this:
```
        "timestamp": {
          "type": "date",
          "format": "uuuu-MM-dd HH:mm:ss.SSS"
        }
```

This is done by graylog, probably under the assumption that all timestamps are ment to be UTC anyways. Does that make any sense?

**Comment by apollo13** [comment]
Ok so the main problem here is probably that explore doesn't seem to accept that this timestamp is UTC. If I set the datasource to use a timestamp field with no special format then elasticsearch will return `2021-08-20T16:36:28.819Z` -- Then Grafana properly picks this up and converts it as wanted.

Adding a `"docvalue_fields" : [{"field": "timestamp", "format": "date_time"}]` to the query generated by elasticsearch return the following (correct) extra-data in the response: 
```
            "fields" : {
              "timestamp" : [
                "2021-08-20T16:36:28.819Z"
              ]
            },
```

Maybe grafana should use that to determine the time value of a log?
