### ISSUE TITLE
unable to create new / edit dashboards with instana-datasource and Grafana v7.0.4+

### ISSUE THREAD

**Issue by schmidtl** [grafana/grafana#26328]
**What happened**:
With instana-datasource we are not able to create or edit dashboards anymore.

During creation we are forced to save a new dashboard immediately, leading to the edit the dashboard, 
which can not be opened to edit mode. This worked up to v7.0.3.

![instana-ds](https://user-images.githubusercontent.com/1536583/87429947-ca91f580-c5e4-11ea-9883-54bb17e84f07.gif)

From the logs:
```
t=2020-07-14T12:02:36+0000 lvl=eror msg="Dashboard not found" logger=context userId=1 orgId=1 uname=admin error="Dashboard not found" remote_addr=172.29.0.1
t=2020-07-14T12:02:36+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/uid/undefined status=404 remote_addr=172.29.0.1 time_ms=1 size=33 referer="http://localhost:3000/d/mVd1FvnMz/new-dashboard-copy?orgId=1&editPanel=2"
```

**What you expected to happen**:
Successfully create and edit dashboards while using instana-datasource

**How to reproduce it (as minimally and precisely as possible)**:
- create new dashboard
- select instana-datasource

**Environment**:
- Grafana version: 7.0.4+
- Data source type & version: instana-datasource 2.7.2
- OS Grafana is installed on: docker || Grafana Cloud Starter
- User OS & Browser: macOS Catalina 10.15.5 & Chrome 83.0.4103.116 
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
Can you check chrome dev console for errors? Any network error? This error is the same we had before when a plugin loads a html angular template file that returns 404 error

**Comment by schmidtl** [comment]
Hi Torkel,
we had no issues o console or network, we also just realized that 
instead resolving <div ng-include src="'queryAndType.html'"/> 
to <script type="text/ng-template" id="queryAndType.html"> 
internally, a GET queryAndType.html was executed.
/Lars

**Comment by schmidtl** [comment]
HI Torkel,
by properly closing our div as `<div ng-include src="'queryAndType.html'"></div>` the problem is solved now.

Herewith the corresponding PR for our plugin:
https://github.com/grafana/grafana-plugin-repository/pull/683

Thank you and best regards
/Lars
