### ISSUE TITLE
Auto add new devices from influxdb DB to existing grafana chart

### ISSUE THREAD

**Issue by bfaliszek** [grafana/grafana#26324]
**What would you like to be added**: Auto add new devices from influxdb DB to existing grafana chart

**Why is this needed**: I have several devices sending measurement data to InfluxDB. I visualize this data using grafana.
All of the devices have their unique function and a set of various parameters these measures.  Most of them are repeated on all devices. Currently, all new devices must be added manually to the charts. Is there a way to automatically add to the existing chart data from a new device that will only appear in the database?

![1](https://user-images.githubusercontent.com/1752244/87421738-b8f62100-c5d7-11ea-8b13-d0fc0048a6c6.png)
![2](https://user-images.githubusercontent.com/1752244/87421747-bb587b00-c5d7-11ea-9c6b-698410d082f4.png)

**Comment by ivanahuckova** [comment]
@bfaliszek, wouldn't template variables with repeated panels show this problem?  More resources on this: 
- https://grafana.com/docs/grafana/latest/variables/templates-and-variables/#examples-of-templates-and-variables
- https://grafana.com/docs/grafana/latest/variables/repeat-panels-or-rows/

**Comment by torkelo** [comment]
You can use wildcard (regex) expressions in your query or use template variable to define more dynamic queries
