### ISSUE TITLE
Grafana: Better handling of crashes when Grafana catches an error

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#26333]
**What happened**: Grafana catches an unexpected error and renders the call stack on a white background.

**What you expected to happen**: I expect something about the current state to be made available to the user. If not the whole dashboard (with only the failed section error'd out), at least the save button, or a copy of the current Dashboard JSON. Maybe both, so the user doe snot lose everything they were working on, and has a chance to fix it through JSON editing.

**How to reproduce it (as minimally and precisely as possible)**: How to reproduce the crash is not important. There have been numerous crashes reported (some fixed, others not). Recently there have been several crashes having to do with transformations. Often there are crashes when data of an unexpected format is returned. Sometimes I have seen template variables get misconfigured in a way where the dashboard always crashes on load.

**Anything else we need to know?**: There will always be crashes, but there is no reason why Grafana can't handle them more gracefully. I've had users who lost hours because they were working on changes (forgot to save constantly) and then ran into a crash. They get shown the call stack, and their changes are lost. But by looking at the source, I know there is no reason for this to be the case. These errors were caught, the users changes are still in memory, as is the current state of the dashboard. But none of that is presented to the user.

It can be difficult to explain to my users. React crashes are so bad and disruptive, that even if they are less frequent, they make the whole service seem less stable. You can never get rid of all crashes, but the crash experience can be made a lot less jarring without a huge amount of work.

**Environment**:
- Grafana version: 6.x, 7.x

**Comment by dprokop** [comment]
@Ultraseamus thanks for this report. I agree the error messages can be improved and I like the idea of exposing the dashboard JSON for easier recovery after the crash. I'll put this into our backlog and we will prioritize this work for the upcoming releases.
