### ISSUE TITLE
LDAP: Signup LDAP user manually in current organisation

### ISSUE THREAD

**Issue by papovyr** [grafana/grafana#26338]
Hi,
As of right now there is no way create ldap user in Grafana

Only way to create user from ldap is enabling signup for ldap (GF_AUTH_LDAP_ALLOW_SIGN_UP)
And asking user to login once and then and then adding user to appropriate team.
This becomes even more hard when when you need to associate user with deferent ORGs 
I don't like idea of keep LDAP signup enabled (GF_AUTH_LDAP_ALLOW_SIGN_UP) as this can be potential security risk 
But i need very granular control to decide which ldap user can have access to Gardena, which orgs and teams (By manually adding ldap user to org)

I suggest to add button on Grafana UI (Test user mapping in LDAP) which will allow to create user in current ORG
or on create user add dropdown to decide where backend source is for that user (ldap, local , etc ...)

Thank you,

**Comment by alexanderzobnin** [comment]
@papovyr You can create user manually with the LDAP username and then set Org and user role. After that, user can log in with LDAP username and password. Does this fit your case?

**Comment by papovyr** [comment]
@alexanderzobnin yes correct, 
Id like to see this behavior not only for LDAP but also for other login methods like  AZUREAD etc ...

**Comment by alexanderzobnin** [comment]
@papovyr It works in the same way for all external auth providers. If you create user in grafana with the same login, then user can sign in with an external auth (LDAP, OAuth, Azure, SAML, etc).

**Comment by torkelo** [comment]
you can also create a ldap group and restrict login to only this group, then GF_AUTH_LDAP_ALLOW_SIGN_UP would not pose any security risk
