### ISSUE TITLE
Grafana Play: Loki data source doesn't work

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26334]
**What happened**:

I wanted to see what Loki can do so I opened the Explore and selected Loki on play.grafana.org. I am not sure what exactly I should write in there to see some data. There was a cheat sheet, which I clicked and a very weird error came out

![image](https://user-images.githubusercontent.com/8693064/87464158-b4eff080-c623-11ea-98ab-acb1f346f46f.png)

I also got a scroll because the message was too wide.

**What you expected to happen**:

I am not sure what should have happened, but at least see a more reasonable error

**How to reproduce it (as minimally and precisely as possible)**:
1. open explore https://play.grafana.org/explore
2. Select Loki
3. from "Loki Cheat Sheet" click `{job="default/prometheus"}` (or write it in the query)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.6 (9f4a172a76)
- User OS & Browser: macOS / Chrome

**Comment by ivanahuckova** [comment]
Hi @nikobearrr and thank you for creating this issue. 🙏 Yes you are right, Loki data source at https://play.grafana.org is currently not working. Regarding error messaging, we have an open PR that fixes Loki error handling and errro messages https://github.com/grafana/grafana/pull/26291.

**Comment by marefr** [comment]
@ivanahuckova maybe we should delete the loki data source on play since it doesn't work. And then we can close this?

**Comment by ivanahuckova** [comment]
I don't have rights to delete it, but @Duologic told me that he is going to delete it, together with Loki-1. We can then close the issue.

**Comment by ivanahuckova** [comment]
Deleted 🙂
