### ISSUE TITLE
Dashboard variable regexp filter shall apply at load time

### ISSUE THREAD

**Issue by smyru** [grafana/grafana#26335]
**What would you like to be added**:
The regexp set on a dashboard data source variable should automatically update the filtered set, when filtered data changes.

**Why is this needed**:
Currently when one sets a regexp filter on a data source, the filter is applied to the data at update/save action, and the set controlled by the pattern would stay unchanged, until an operator edits each and every dashboard that sets the variable with such a filter. This is very tedious for larger machine parks.

***Real life example:***
I have a variable with a regexp that filtered out servers being part of our staging env. Due to data center works, the set of servers changed, yet the pattern (`container_.*`) was still the same. Nevertheless the filtered set keeps reflecting state of the past and to reflect the DC change each dashboard with the variable has to be updated one by one.

**Comment by dprokop** [comment]
@smyru thanks for reporting. Any chance you could show us your variable configuration and provide some infor about Grafana version you are using ? 

I've just tested it against the latest version and it seems like the variable is being updated correctly when the variable [Refresh](https://grafana.com/docs/grafana/latest/variables/variable-types/add-query-variable/#enter-query-options) option is set to _.

@hugohaggmark is there something I might be missing here?

**Comment by hugohaggmark** [comment]
> @smyru thanks for reporting. Any chance you could show us your variable configuration and provide some info about Grafana version you are using?
> 
> I've just tested it against the latest version and it seems like the variable is being updated correctly when the variable [Refresh](https://grafana.com/docs/grafana/latest/variables/variable-types/add-query-variable/#enter-query-options) option is set to _on Dashboard Load_.
> 
> @hugohaggmark is there something I might be missing here?

I agree with you @dprokop , would be great if @smyru could share Panel JSON and refresh should be enough.

**Comment by dprokop** [comment]
@smyru friendly ping :)

**Comment by smyru** [comment]
We are currently running 6.4.2 of 443a0ba. 

The variable section is defined as follows:
`  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "text": "all",
          "value": "all"
        },
        "datasource": "graphite",
        "definition": "FOOBAR.*",
        "hide": 0,
        "includeAll": false,
        "label": "Datacenters",
        "multi": false,
        "name": "dc",
        "options": [
          {
            "selected": true,
            "text": "all",
            "value": "all"
          },
          {
            "selected": false,
            "text": "container_z20-04",
            "value": "container_z20-04"
          },
          {
            "selected": false,
            "text": "container_z20-07",
            "value": "container_z20-07"
          },
          {
            "selected": false,
            "text": "container_r10-10",
            "value": "container_r10-10"
          },
          {
            "selected": false,
            "text": "container_r11-04",
            "value": "container_r11-04"
          },
          {
            "selected": false,
            "text": "container_l09-02",
            "value": "container_l09-02"
          },
          {
            "selected": false,
            "text": "container_l09-03",
            "value": "container_l09-03"
          },
          {
            "selected": false,
            "text": "container_l15",
            "value": "container_l15"
          },
          {
            "selected": false,
            "text": "container_gs23-01",
            "value": "container_gs23-01"
          },
          {
            "selected": false,
            "text": "container_gs23-02",
            "value": "container_gs23-02"
          },
          {
            "selected": false,
            "text": "reference",
            "value": "reference"
          },
          {
            "selected": false,
            "text": "scm_staging",
            "value": "scm_staging"
          },
          {
            "selected": false,
            "text": "staging",
            "value": "staging"
          }
        ],
        "query": "FOOBAR.*",
        "refresh": 0,
        "regex": "(all|reference|staging|scm_staging|container_.*)",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]`

**Comment by hugohaggmark** [comment]
@smyru from your JSON it seems like the variable is using `"refresh": 0` which means it will only be refreshed when you update the variable. Try changing refresh to On Dashboard Load. Let me know if this doesn't solve your challenge.

All the best

**Comment by smyru** [comment]
Doh. I did not acknowledge presence of this option until now. Nevertheless "Never" seems to be default, when I create variables. OK, I guess, it's safe to drop my ticket as Invalid.
