### ISSUE TITLE
Query option Relative Time does not gets applied with Absolute time range

### ISSUE THREAD

**Issue by oligu** [grafana/grafana#26346]
**What happened**:
In a dashboard I have a panel which only shows the last 5 minutes of data. For this I set the `Relative time` in the `Query options` of that panel to `5m`. This works perfectly fine, as long as I select a `Relative time range` for the whole dashboard (e.g. `Last 1 hour`, ...). However, when I select an `Absolute time range` for the dashboard (e.g. `2020-07-15 00:00:00 to 2020-07-15 01:00:00`), the panel in question does not shows the last 5 minutes, but the same time range as the rest of the dashboard.

**What you expected to happen**:
The panel always shows only the last 5 minutes.

**How to reproduce it (as minimally and precisely as possible)**:
Have 2 Graph panels on a dashboard. Set `Relative time` in one of them. Set an `Absolute time range` for the dashboard.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.6 (9f4a172a76)
- Data source type & version: PostgreSQL with TimescaleDB
- OS Grafana is installed on: Ubuntu 18.04.4 LTS
- User OS & Browser: Windows10, Vivaldi 3.1.1929.45 (Stable channel) (32-bit)
- Grafana plugins: 
- Others:

**Comment by ivanahuckova** [comment]
Yes, this is current correct behaviour. As mentioned in [documentation]:(https://grafana.com/docs/grafana/latest/panels/queries/#query-options)

> You can override the relative time range for individual panels, causing them to be different than what is selected in the dashboard time picker in the top right corner of the dashboard. This allows you to show metrics from different time periods or days on the same dashboard.

This means that only relative time range can be overridden. But there is an open feature request to [add ability to override the dashboard time with Absolute Time Range per panel](https://github.com/grafana/grafana/issues/22163). So feel free to upvote it and maybe write down why would it be useful for you. 🙂

**Comment by oligu** [comment]
Thanks for the clarification @ivanahuckova. I'll check out #22163.
