### ISSUE TITLE
Table Panel: Add a way to auto size table panel

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#26343]
I have a few dashboards which shows a bunch of tables.
The rows count of each table varies.
My issue is that sometimes I get empty tables or tables that are almost empty and users have to scroll down over them.
I can't set their size too small since sometimes they do have lots of rows and for that case it will be hard to use.

For me, it would be best to allow both - 
1. Hide table panel for tables that are empty
2. Set max size for a table panel but allow it to shrink to fit actual rows number

For our dashboard it will be super valuable so I'm guessing others will find it useful too.

(For 1 I can sometimes use a repeated variable for workaround but still it would be useful)

**Comment by paregupt** [comment]
would pagination help? like, show 10 items per page. That is what I was using in v6.

**Comment by gilkgit** [comment]
> would pagination help? like, show 10 items per page. That is what I was using in v6.

IMO it won't improve the experience much- for empty tables I would still show the entire table panel.
for me the only thing pagination would change is pages instead of scrolling (with the same panel size).

**Comment by dprokop** [comment]
Duplicate https://github.com/grafana/grafana/issues/24901
