### ISSUE TITLE
Alerting: Control over `no_data` state change notifications

### ISSUE THREAD

**Issue by marionclelland** [grafana/grafana#26347]
**What would you like to be added**:
Toggle (similar to `Disable Resolve Message`) to allow control over other notification types; specifically `no_data` state change.

**or**

Something in message into PagerDuty to state which type of notification is being sent, e.g. `alerting`, `no_data` etc.

**Why is this needed**:
We are managing a department-wide monitoring and alerting solution where DevOps squads contribute their own alerts.  The default alerting configuration in Grafana is to change state to `no_data` when there is no data or all null.  This triggers a state change which triggers a notification to our PagerDuty service as there is no control to prevent this notification nor is there anything in the incoming message to PagerDuty that it is a state change to `no_data` rather than `alerting`.  

We do not want callout engineers being called out for this state unless a DevOps squad has explicitly decided that `no_data` should cause an alert, in which case they would set `alerting`.  Having a default that always calls out engineers does not work for us where we have no means to control what happens.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
