### ISSUE TITLE
InfluxDB: support flux queries in template variables

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#26357]
**What would you like to be added**:
When using InfluxDB with flux query support, we should also be able to author template variable queries in flux 

**Why is this needed**:
to support template variables ;)

**Comment by rafecolton** [comment]
I'm assuming this is referring to not being able to use flux queries to define variables?

<img width="1774" alt="Screen Shot 2020-07-17 at 4 08 47 PM" src="https://user-images.githubusercontent.com/1058475/87837298-d9c4ad80-c847-11ea-94d9-e2cf9da42251.png">

**Comment by rafecolton** [comment]
Would love to see a fix for this, right now we are having to use InfluxQL tag queries to set the variables. Let me know if I can help with the testing in any way.

**Comment by pprkut** [comment]
This was working with the separate beta plugin. Considering that, not sure I would qualify this as a feature request :-/

**Comment by MatinF** [comment]
Would really like to see this supported as well, ideally incl. a basic example of usage

**Comment by MatinF** [comment]
A brief note on this: 

I've attempted to set up both Flux and InfluxQL as query languages for my InfluxDB Cloud 2.0 instance. This works overall, though a bit clunky. 

I can then e.g. get a list of variables in my dropdown using the InfluxQL query, in my case e.g. `SHOW MEASUREMENTS`. 

However, when I try to parse a variable in a panel Flux query, I get an error that seems to indicate that the Flux query somehow only parses 5 characters out of 8 in my variable. Not sure if I'm using an incorrect syntax or if this is a bug with the Flux/Grafana variable support?

![variable_issue_flux](https://user-images.githubusercontent.com/26184427/89716649-1438ea80-d9af-11ea-9816-630b31f1ba0e.PNG)

**Comment by MatinF** [comment]
FYI, I've gotten a bit further with this and I'm now able to handle most of my Flux query needs incl. display of multiple measurements via below query. I'm still missing the ability to create a variable list based on Flux, but the rest seems to be working.

```
from(bucket: "test-bucket-new")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => contains(value: r["_measurement"], set: ${devices:json}))
  |> filter(fn: (r) => r["_field"] == "WheelBasedVehicleSpeed")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

**Comment by omarmussa** [comment]
Enabling this feature is **really** important for supporting more elaborate variables since joins are supported in Flux but not InfluxQL.  Query language should just be selectable in the same way that it is for dashboard data queries.

**Comment by kvn-tylr** [comment]
This is a feature I really need as well.  I need to populate a text panel with a value from InfluxDB 2.0 OSS using Flux.  When we were using MySQL, it was easy.  Just have a variable with a select and put the variable in the text panel.  However, since I populate variables using Flux, this trick doesn't work.  I thought about creating a separate data source pointed at the same InfluxDB only using InfluxQL instead, but InfluxQL isn't supported with InfluxDB 2.0 OSS.  Therefore, since Text Panels can't be populated using queries, and variables can't be populated using Flux, I simply have no way to do what I was doing before with either MySQL or InfluxQL.

We really need this, or else we're losing functionality and putting InfluxDB 2.0 upgrades in a serious bind.

**Comment by kvn-tylr** [comment]
Update:  We upgraded to 7.2 beta1, and I can now populate variables with Flux queries.  I can do the same trick as before.

Thanks.

**Comment by MatinF** [comment]
> Update: We upgraded to 7.2 beta1, and I can now populate variables with Flux queries. I can do the same trick as before.
> 
> Thanks.

Can you share the query syntax you've used for your Flux variables query?

**Comment by kvn-tylr** [comment]
Sure.  I attached a snip so you can see the entire edit page.  Below is the entire query.  I've only been at this for 3 months now, so I'm sure my query could be better.

import "strings"

st = time(v: strings.replace(v: "${startTime}", t: " ", u: "T", i: 1) + ".000000Z")

from(bucket: "iib_events")
  |> range(start: st)
   |> filter(fn: (r) =>
    r.localTransactionId == "${tid}" and
    r.eventCounter == "${eventCounter}"
  )
 |> map(fn: (r) => ({
      event: r._value
  }))

![flux_variable_query](https://user-images.githubusercontent.com/70764342/92935254-283c9580-f40e-11ea-8add-39f5a4ee3c94.JPG)

**Comment by kvn-tylr** [comment]
Here's another one for a drop down list.

from(bucket: "iib_events")
|> range(start: v.timeRangeStart, stop:v.timeRangeStop)
|> distinct(column: "brokerName")

![image](https://user-images.githubusercontent.com/70764342/92938684-7d7aa600-f412-11ea-8fc1-9eca3c6c73d0.png)

**Comment by ryantxu** [comment]
Template variables are supported in 7.2 -- lets open a new issue if there are remaining problems
