### ISSUE TITLE
Annotations: Flexible annotation tag matching

### ISSUE THREAD

**Issue by hackery** [grafana/grafana#26352]
Currently the tag match selection is either "any" or "all". I often find use cases where more flexible boolean combination would be useful - e.g.

- ( outage OR maintenance OR deployment ) AND ( qa OR uat )
- ( outage OR maintenance OR deployment ) AND ( production )

Simple AND/OR combinations can be done by creating multiple annotation queries on the `~Grafana~` datasource with different filters by expanding out OR over AND, but it gets unwieldy quickly:

- Match All: outage, qa
- Match All: outage, uat
- Match All: maintenance, qa
- Match All: maintenance, uat
- Match All: deployment, qa
- Match All: deployment, uat
- ...

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
