### ISSUE TITLE
Table Panel: Add option to display cell values as strings

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#26362]
In previous Grafana versions you could set a "Column Style" to "String", this option no longer exists, so if a value comes in as "0007", Grafana will treat it as a numeric value, and display it as "7".

The only workaround I have found is to display it as a JSON value, but that is not ideal.

**Environment**:
- Grafana version: 7.0.6

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/27097 , that adds a string unit that you can use (in an override)
