### ISSUE TITLE
WHERE dropdown shows templating variables in the tag key field?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2636]
I'm using the Templating feature (which is awesome, btw) with Grafana and InfluxDB.

In the *WHERE* clause section, the dropdown will show all the valid tag names and values for an InfluxDB datasource.

However, for the key (i.e. tag name) part of this, the dropdown will also show templating variable values (e.g. `/$Hostname/`):

![screenshot 2015-09-01 10 53 07](https://cloud.githubusercontent.com/assets/243499/9593924/6e8122aa-5098-11e5-94a1-ded8e0043b40.png)

This doesn't really make sense, since my understanding is you would normally use variables in the value (i.e. tag value) part of a WHERE clause.

Of course, if there is a valid use-case for using templating variables in the key part of the WHERE dropdown, please let me know.

**Comment by torkelo** [comment]
Thanks for reporting this, noticed this yesterday as welö.
