### ISSUE TITLE
Registry: Allow short-lived background services

### ISSUE THREAD

**Issue by sakjur** [grafana/grafana#26364]
**What happened**:
When starting a background service by implementing `Run(context.Context) error` and immediately returning `nil` (to avoid running the service) the service will stop other services from starting up.

It is possible to work-around this by idly waiting for `<-ctx.Done()` when Grafana is shutting down, but it'd be reasonable to allow services to shut themselves down without returning an error and not break unrelated services.

These lines are likely responsible:

https://github.com/grafana/grafana/blob/6619cc4b816e6778b68a46ba6c1404f7af845bb4/pkg/cmd/grafana-server/server.go#L129-L132

We should avoid triggering shutdown mode unless we actually get a `<-ctx.Done` signal.

**What you expected to happen**:
The service is cleanly shut down.

**How to reproduce it (as minimally and precisely as possible)**:
Implement a BackgroundService and return `nil` as the first step of the service execution.

(cc @marefr)

**Comment by marefr** [comment]
> We should avoid triggering shutdown mode unless we actually get a <-ctx.Done signal.

Yes. But wouldn't it be enough to skip shutdownInProgress if err returned is nil?

**Comment by sakjur** [comment]
@marefr That should be enough here, yes. If we need to set `shutdownInProgress` we could do that elsewhere on `ctx.Done`.

**Comment by ahlaw** [comment]
Hi, can I take this issue?

**Comment by aknuds1** [comment]
@ahlaw Go ahead.
