### ISSUE TITLE
Grafana-UI: More 'Dashboard link' icons

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#26366]
**Current situation:**
![icons-old](https://user-images.githubusercontent.com/1107939/87645759-3c398300-c74e-11ea-83b3-8a679c929472.png)

There are only 7 icons available for **Dashboard links** in Grafana 7.0.6.

**What would you like to be added**:
![icons-new](https://user-images.githubusercontent.com/1107939/87645241-7ce4cc80-c74d-11ea-8aa7-918400355463.png)

**Why is this needed**:

Because a good icon says more than n words ☺.

_____________________
Ref #13288 (keep this enhancement issue open, otherwise you may forget it)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
