### ISSUE TITLE
Static resources respond very slowly

### ISSUE THREAD

**Issue by nondevops** [grafana/grafana#26371]
**What happened**:
http://grafana.devops.press:3000/public/build/vendors~app.d3489276abe5fda2bd26.js
This link request returns slowly and takes 17 seconds to respond

**What you expected to happen**:
I want to load resource links very quickly

**How to reproduce it (as minimally and precisely as possible)**:
http://grafana.devops.press:3000/public/build/vendors~app.d3489276abe5fda2bd26.js
Request the link in the browser

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/12181410/87672499-a598b080-c7a5-11ea-9bf9-862444f09de2.png)

**Environment**:
- Grafana version:v7.0.3 (00ee734baf)
- Data source type & version:none
- OS Grafana is installed on:centos7
- User OS & Browser:chorme83/windows10x64
- Grafana plugins:none
- Others:

**Comment by ivanahuckova** [comment]
Hi @nondevops, I have tested this on [grafana.play](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) and the time is significantly shorter. So the problem might be on your server. 
![image](https://user-images.githubusercontent.com/30407135/87771065-23999d80-c820-11ea-8786-dc4aa22c4028.png)

**Comment by Mokaffe** [comment]
Hi, I met the same question that load resource very slowly. Any update?
