### ISSUE TITLE
Graph Panel Field Override ${__field.name} is not just the name

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#26370]
**What happened**:

When using a Field Override for Display name with the Graph or Table panel -- , when using `${__field.name}`, the expanded value includes the labels, not just the name.

**What you expected to happen**:

`${__field.name}}` to only expand to the name property, in the following example, to 'Avg Available MBytes Memory' (as per documentation at https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#display-name). 

Example:

![image](https://user-images.githubusercontent.com/1692624/87667571-962f4e00-c738-11ea-805a-ff71d0b78194.png)

Query Inspector shows the following for Fields in the DataFrame structure:

```
"fields": [
      {
        "name": "TimeGenerated",
        "type": "time",
        "config": {
          "links": [
            {
              "url": "REMOVED",
              "title": "View in Azure Portal",
              "targetBlank": true
            }
          ]
        }
      },
      {
        "name": "Avg Available MBytes Memory",
        "type": "number",
        "config": {
          "links": [
            {
              "url": "REMOVED",
              "title": "View in Azure Portal",
              "targetBlank": true
            }
          ]
        },
        "labels": {
          "Computer": "grafana-vm",
          "K8SContainer": "Memory"
        }
      }
    ]
```

**Environment**:
- Grafana version: 7.1

**Comment by dprokop** [comment]
@kylebrandt this is a consequence of https://github.com/grafana/grafana/pull/24024 and the way we calculate the field name when labels are there. It's a correct behaviour showing the real identity of the series.

**Comment by kylebrandt** [comment]
Re-opening this as I don't think it is correct, and has consequences. As per the documentation:

"You can use expressions like ${__series.name} or ${**field.name} to use only series name or field name in title"

I would expect series.name to be the identity of the series, and field.name to be the field's name as per that documentation. Also, practically, need a way to access the field name only.

**Comment by ryantxu** [comment]
We need some way to get the underlying field name regardless of the display structure -- in particular so you can better construct the field display name!

Currenlty:
`__field.name` = the calculated display name.  Originally `__field.title` but that confused too many people on why it is different than name

Maybe:
__field.rawName 
__field.originalName 
??? 


Side note...  should `__series.name` be deprecated and removed from docs?  It is just a duplicate of __field.name, right

**Comment by kylebrandt** [comment]
`field.name` not being the name property of the field seems like pain for the future - I think the disconnect will make documentation and explaining things harder and result in confusion. Can we not walk that back?

Maybe field.id ? Where id = name + labels

**Comment by kylebrandt** [comment]
To illustrate, how do we document, for example `__field.rawName` I think would be something like:

Inverse definition: "rawName returns the name of the field without any labels"

Non-inverse, but circular: "rawName returns the only the name portion of the field's name"

So in trying define it, if we have to define what it is not, that is a bad sign. But maybe there is a better way to define it?

**Comment by kylebrandt** [comment]
fixed in https://github.com/grafana/grafana/pull/26531
