### ISSUE TITLE
Allow dynamic queries based on ec2_instance_attribute Platform value

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#26372]
**What would you like to be added**:

I have one panel called memory used:

![image](https://user-images.githubusercontent.com/12910496/87677421-a3b4fa00-c771-11ea-83d7-b72ddb7f71ee.png)

However the Windows machines have a different metric called: 

![image](https://user-images.githubusercontent.com/12910496/87677521-c3e4b900-c771-11ea-838d-96b20e5a596c.png)

I can create 2 queries but I cannot hide the other dynamically. Would it be possible to essentially use the ec2 instance attribute and the platform value to derive the query?

**Why is this needed**:

It enables me to create 1 panel which will show memory stats but will be seamless as to which OS it is reporting on.

**Comment by ivanahuckova** [comment]
@torkelo @hugohaggmark @dprokop is this currently possible with referencing one template variable in second variable? 

If not, this is probably not a Cloudwatch specific feature request and this mapping from a template variable feature could be used for more data sources.

**Comment by torkelo** [comment]
No this type of dynamic query is not possible. 

Maybe request the metric names be named the same between OSes in this case

**Comment by waqark3389** [comment]
@torkelo @ivanahuckova - thanks for taking a look at this. I renamed them instead. For anyone else that comes across this:

Change via: 

```
			"mem": {
				"measurement": [
					{"name": "mem_used_percent", "rename": "Memory % Commited Bytes In Use", "unit": "Percent"}
				],
```

In the cloudwatch agent config
