### ISSUE TITLE
InfluxDB w/flux: Self Sign Certificate support for TLS Connection

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#26388]
See https://github.com/grafana/influxdb-flux-datasource/issues/111

Currently the plugin throws error when a new datasource is created with TLS Connection but self sign certificate. The plugin seems to be throwing error x509: cannot validate certificate for ...

We should implement a skip verify TLS button for this plugin like the v1 plugin.

**Comment by ryantxu** [comment]
cc @seanlok @rafecolton

**Comment by rafecolton** [comment]
Alright, we're upgraded to 7.1 now and would love to see a fix for this. Let me know if I can help in any way with the testing

**Comment by aocenas** [comment]
@ryantxu I am closing this in favor of https://github.com/grafana/grafana/issues/29303 seems like the whole Auth section is missing when using Flux right now.
