### ISSUE TITLE
time_range_test failure on x86 after v7.0.0

### ISSUE THREAD

**Issue by kaey** [grafana/grafana#26389]
**What happened**:

Running `go test ./...` in alpine linux on x86 results in failures. Full build log available here:

https://tpaste.us/PMBQ

These is a regression introduced in v7.0.0.

I previously filed #25287 which mentioned that problem. While one problem was fixed there this one remain unfixed in v7.1.0

**What you expected to happen**:

no failures

**How to reproduce it (as minimally and precisely as possible)**:

`go test ./...` on x86 host

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.0, problem first appeared in v7.0.0
- Data source type & version: n/a
- OS Grafana is installed on: Alpine linux edge
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by marefr** [comment]
I created an issue in the external library where the errors happens https://github.com/timberio/go-datemath/issues/5
