### ISSUE TITLE
Successful health check should give a GREEN alert

### ISSUE THREAD

**Issue by wz2b** [grafana/grafana#26384]
**What would you like to be added**:

When you configure a data source, and click "Save & Test" I would like the Alert box that is created to be of type [Success](https://react-bootstrap.github.io/components/alerts/) so that it shows up green.  Currently, even if you return `backend.HealthStatusOk` the check health message is red.

**Why is this needed**:
It's a little disorienting that the health check success message is in an angry, frightening color.  In react terms, I think it should be variant="success" for HealthStatusOK, and variant="danger" for any other status.  If this is themed, maybe it doesn't have to be danger, it can just be "warning."

As long as we're touching this code, I'd also like to ask that you set `dismissable={"true"}`

My memory tells me this changed since the introduction of Grafana version 7.

**Comment by ivanahuckova** [comment]
@marefr can you please look at this. I think that you were working on this. Also, I don't think that any of our native data sources are using `/health` endpoint yet, so I don't think I have a quick way how to check it out.

**Comment by marefr** [comment]
@wz2b what data source are you referring to, a custom one you've built?

**Comment by torkelo** [comment]
It's green 
![Screenshot from 2020-08-09 08-47-25](https://user-images.githubusercontent.com/10999/89726651-07eb7680-da1d-11ea-9033-254c9b0e5d77.png)
