### ISSUE TITLE
{__dashboard} expands to the dashboard name, instead of the dashboard UID.

### ISSUE THREAD

**Issue by matthubb** [grafana/grafana#26381]
**What happened**:

`{__dashboard}` expands to the dashboard name, instead of the dashboard UID.

**What you expected to happen**:
`{__dashboard}` used to expand to the dashboard UID and was [documented as such](https://grafana.com/docs/grafana/latest/variables/global-variables/#dashboard):

> **$__dashboard**
> > Only available in Grafana v6.7+
> 
> This variable is the UID of the current dashboard. `${__dashboard.name}` is the name of the current dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
1. Visit https://play.grafana.org/d/27c0IFkGk/data-link-with-dashboard-variable and check the links for the values in the  `web_server_01` column.
2. Observe that the link renders to: `https://play.grafana.org/d/data%20link%20with%20dashboard%20variable/data%20link%20with%20dashboard%20variable`

Or create a data link similar to `https://play.grafana.org/d/${__dashboard}﻿/${__dashboard.name}`.

**Environment**:
- Grafana version: Playgound - Grafana v7.1.0 (8101355285)

**Comment by torkelo** [comment]
the documentation looks incorrect, try ${__dashboard.uid}

**Comment by matthubb** [comment]
This change breaks dashboards already using `{__dashboard}` as was documented.

If your fix-forward is to update the docs, it would be nice for it to have a mention in the change log (I looked, but didn't find).

**Comment by torkelo** [comment]
Yes,I agree , this is indeed a
breaking change needs big notice in changelog

**Comment by oddlittlebird** [comment]
So, is this a change that shouldn't have happened (bug) or do I need to update the documentation?

**Comment by torkelo** [comment]
I think we should update docs, and if a many are impacted by the breaking change we might need to some migration
