### ISSUE TITLE
Stats panel showing NaN when the value is 0

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#26385]
**What happened**:
Creating a stats panel with unit of `seconds`
with metric value of 0,
it is showing NaN

**What you expected to happen**:

showing `0`

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/21690857/87721254-62bde500-c773-11ea-8412-1c16a3767edd.png)

**Environment**:
- Grafana version: v7.0.5

**Comment by ivanahuckova** [comment]
Thank you for creating the issue @fredwangwang. I could reproduce on [grafana.play](https://play.grafana.org/) on Grafana v7.1.0.

Interestingly, other units such as **hours** work: 
![image](https://user-images.githubusercontent.com/30407135/87760374-f2b16c80-c80f-11ea-8cb0-eb11c7745a8f.png)

But when switching to **seconds**, we get NaN:
![image](https://user-images.githubusercontent.com/30407135/87759966-64d58180-c80f-11ea-8052-f5e9112d1138.png)

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/27376
