### ISSUE TITLE
In-built SSL Support?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2639]
I'm wondering if having SSL support in-built to Grafana would be in scope?

Or is the current recommendation to use a reverse-proxy in front of Grafana, to provide SSL? If so, would it be possible to provide a sample generic config in the docs, to get started?

**Comment by linuxbutler** [comment]
Hi victorhooi

I use a similar setup, with apache in front of Grafana. 
My steps: 

open /etc/grafana/grafana.ini
edit: 
root_url = %(protocol)s://%(domain)s:%(http_port)s/
to be:
root_url = %(protocol)s://%(domain)s:%(http_port)s/dashboard-solo

(the "dashboard-solo" is the extra bit). 

Then in Apache, in your vhost, add the following:
ProxyRequests Off
ProxyPass /dashboard-solo http://127.0.0.1:3000
ProxyPassReverse /dashboard-solo http://127.0.0.1:3000

Then you can just browse to your vhost.example.com/dashboard-solo and all is good.

**Comment by torkelo** [comment]
http://docs.grafana.org/installation/configuration/#cert_file

**Comment by victorhooi** [comment]
Awesome, thanks for that @torkelo 

I can confirm I was able to create a self-signed certificate and keyfile using the steps at http://www.akadia.com/services/ssh_test_certificate.html.

Then I edited `conf/defaults.ini` to set:
```
protocol = https
cert_file = server.crt
cert_key = server.key
```
and placed `server.crt` and `server.key` in the same directory as the `grafana` binary, ran `grafana`, and boom:

<img width="837" alt="screenshot 2015-09-01 21 25 38" src="https://cloud.githubusercontent.com/assets/243499/9602932/03503af4-50f0-11e5-96ca-6432819a5823.png">

You should totally advertise that Grafana supports SSL out of the box =)!

I tried Googling for "grafana ssl", and got a bunch of third-party pages, rather than an official Grafana page saying "Here is how you enable SSL".

**Comment by hubby2004** [comment]
As a side note, if after you switch to https and add the certificates sometimes the server might fail to restart. If that's the case, just add the absolute path for the cert and key after you copy them to conf:
```
    cert_file = /usr/share/grafana/conf/server.crt 
    cert_key = /usr/share/grafana/conf/server.key
```
I hope this helps. Thanks @torkelo!

**Comment by MattFaus** [comment]
Note that if you're using Let's Encrypt or `certbot` for a CA-issued (so you can get a legit green lockbox icon and avoid those annoying red X warnings), you need to point to the `fullchain.pem` file for the `cert_file` setting, like: `cert_file = /etc/letsencrypt/live/domain.tld/fullchain.pem`

**Comment by amalleo25** [comment]
@victorhooi 
Changing conf/defaults.ini will work but I think the preferred method is to edit /etc/grafana/grafana.ini and uncomment the lines you want to change.

**Comment by michaelahess** [comment]
@MattFaus I tested with a self made cert and it works fine. My Let's Encrypt cert that works fine with Apache doesn't. Grafana simply won't restart. Copying the pem files from letsencrypt/archive.... to the Grafana directory works great. So the soft link Let's Encrypt creates is the problem or possibly the way I'm entering the path in the grafana.ini file? Syntax in the ini:

cert_file = /etc/letsencrypt/live/xxx.domain.xxx/fullchain.pem

I even tried a soft link from that to the grafana directory and got no luck. Any thoughts?

**Comment by retorquere** [comment]
I'm trying to set up grafana with a letsencrypt cert but I'm getting 

```
Fail to start server" logger=server error="cert_key cannot be empty when using HTTPS
```

when I provide only `cert_file = /etc/letsencrypt/live/domain.tld/fullchain.pem`

**Comment by kevgrig** [comment]
@retorquere cert_key is the privkey.pem file

**Comment by savagexiv** [comment]
How would you use Let's Encrypt to generate a SSL cert for Grafana? Do you need a domain name to use Let's Encrypt certs as grafana is only accessible through internal DNS or an internal IP

**Comment by daniellee** [comment]
@savagexiv  A quick google search turned this up: https://community.letsencrypt.org/t/certificates-for-intranet-sites/25892 The Let's Encrypt discourse site is probably a good place to ask that question.
