### ISSUE TITLE
tsdb/influxdb/flux test failure on s390x after v7.1.0

### ISSUE THREAD

**Issue by kaey** [grafana/grafana#26390]
**What happened**:

Running `go test ./...` in alpine linux on s390x results in failure. Full build log available here:

https://tpaste.us/6V8n

These is a regression introduced in v7.1.0, problem was not present in v7.0.6.

**What you expected to happen**:

no failures

**How to reproduce it (as minimally and precisely as possible)**:

`go test ./...` on s390x host

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.0
- Data source type & version: n/a
- OS Grafana is installed on: Alpine linux edge
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by ivanahuckova** [comment]
@marefr do we support s390x? I can see that there is a [feature request for binary and docker image support for s390x](https://github.com/grafana/grafana/issues/24273).
@kaey, there was recently another [s390x test case failure issue](https://github.com/grafana/grafana/issues/26092), but with different test(s) and in v7.0.5 but the user was able to figure out the solution. Can you check it out?

**Comment by aknuds1** [comment]
@ivanahuckova We don't build packages/images for s390x at least. Any support is probably best effort. I don't even know how to test on this architecture, since we don't have any hardware.

**Comment by aknuds1** [comment]
@kaey Might you be able to provide a PR fixing this issue?

**Comment by kaey** [comment]
I do not care about s390 either, I maintain grafana updates in alpine linux and simply forwarding you issues I encounter.
If it's not supported I'll disable it.

IBM usually sponsors hardware if you want to support it in future.

**Comment by aknuds1** [comment]
Aha, thanks for explaining that @kaey. We are in touch with IBM already, I will make a note to see if there's anything we can do about this.

**Comment by ryantxu** [comment]
Interesting -- I bet it is an issue with apache arrow encoding.

**Comment by sid226** [comment]
@ryantxu https://github.com/grafana/grafana-plugin-sdk-go/issues/212

**Comment by mellieA** [comment]
Closing based on comment https://github.com/grafana/grafana/issues/26390#issuecomment-659990532
