### ISSUE TITLE
Strange behavior of legend selection

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#26394]
**What happened**: Clicking on legend show data that is connected with clicked legend item but the values shown are not correct.

**What you expected to happen**: The values shown with and without legend clicked should be the same. 

**How to reproduce it (as minimally and precisely as possible)**: I am unable to describe the way to reproduce this problem.

**Without legend clicked (focus on yellow color)**
![image](https://user-images.githubusercontent.com/29247982/87767494-06160500-c81b-11ea-9d3d-0140f5c85875.png)

**With legend clicked (focus on yellow color)**
![image](https://user-images.githubusercontent.com/29247982/87767537-162de480-c81b-11ea-8653-ac803714e51b.png)

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: Elasticsearch 7.8
- OS Grafana is installed on: Windows 2016 Server
- User OS & Browser: Windows 10 2004, Chrome 84

**Comment by torkelo** [comment]
could be that your stacking null values and there is interpolation going on. What is your min doc count? try to set that to 0, and set graph display option "null value" to null as zero. Does that change things? 

Can you include the raw query response? (Check query inspector)

**Comment by GrzegorzLyp** [comment]
After changing Min Doc Count = 0 the strange error appears:

![image](https://user-images.githubusercontent.com/29247982/87848300-1c859480-c8df-11ea-8b75-f178e9c7ca52.png)

![image](https://user-images.githubusercontent.com/29247982/87848303-2b6c4700-c8df-11ea-8135-d2ba11d6e553.png)

![image](https://user-images.githubusercontent.com/29247982/87848307-38893600-c8df-11ea-964f-9b54cbe51c94.png)

![image](https://user-images.githubusercontent.com/29247982/87848314-463ebb80-c8df-11ea-9b3a-4be3642c2b26.png)

**Comment by torkelo** [comment]
I mean min_doc count 0 on the date histogram

**Comment by GrzegorzLyp** [comment]
I have changed the proposed value and it works fine. Thank You for the support. Case can be closed. Maybe some hint could appear in grafana interface as the proposed value for this parameter :)
