### ISSUE TITLE
Search for metrics (similar to dashboard search)

### ISSUE THREAD

**Issue by bhawna2909** [grafana/grafana#264]
It  is mentioned in the grafana wiki that "Using elasticsearch for searching metrices" is still in pipeline. So it means that at present we cannot import elasticsearch indexes just like we do in kibana and use lucene based queries on it ?

**Comment by utkarshcmu** [comment]
Can there be a global search instead, searching words in Dashboard names, Panel titles, Metric Queries, Aliases, Tags?

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by TWHOI** [comment]
Another use case is: "Is my metric used somewhere or can I delete it?"
