### ISSUE TITLE
Grafana 7.1 Time Region not respecting Timezone

### ISSUE THREAD

**Issue by danieldonoghue** [grafana/grafana#26402]
**What happened**:

Configuring a Time Region on my graph panels assumes UTC for the `from` and `to` times.

![Screenshot 2020-07-17 at 13 00 27](https://user-images.githubusercontent.com/27728290/87780366-dd980600-c82e-11ea-8127-88dec2500e11.png)

**What you expected to happen**:

Enter Time Regions values in the configured timezone so that I don't have to change them when the clocks change.

**How to reproduce it (as minimally and precisely as possible)**:

1. configure your timezone to be anything other than UTC. I.E., UTC+2 (system default for me)
2. edit a graph panel
3. enter a time region
4. observe the incorrect start and end position of the time region on the graph.

**Environment**:

Grafana Docker image grafana/grafana:latest (7.1.0 at time of testing).

**Comment by ivanahuckova** [comment]
@danieldonoghue yes, that is correct default behaviour. As mentioned in tooltip, all configured time regions refer to UTC. But I think we could add this information do docs as well, as it is [not mentioned there](https://grafana.com/docs/grafana/latest/panels/visualizations/graph-panel/#time-regions). +cc @oddlittlebird 
![image](https://user-images.githubusercontent.com/30407135/87784855-5c913c80-c837-11ea-8021-fc6a87863bcf.png)

**Comment by pseudocoder** [comment]
Could we reopen this - having the time regions with no option to consider timezone or daylight saving makes then ineffective for many real-world cases.

**Comment by pseudocoder** [comment]
A simple option to say "align with time axis" would make sense, so if I enter 01:00 as the region then that always lines up with 01:00 on the time axis no matter what. Options around timezones should apply to the axis / overall time display.

**Comment by ivanahuckova** [comment]
@pseudocoder There is already a feature request for this https://github.com/grafana/grafana/issues/14400.
