### ISSUE TITLE
Elasticsearch datasource with ApiKey via browser Access not working

### ISSUE THREAD

**Issue by LukasKucharski1887** [grafana/grafana#26403]
**What happened**:
Setting up an elasticsearch datasource with browser access and ApiKey as authorization header does not work. In servermode it works as expected.

![image](https://user-images.githubusercontent.com/39726245/87779458-1a62fd80-c82d-11ea-87ae-7b2364a15016.png)

**What you expected to happen**:
I expect both modes working. Browser mode has the advantage, that we do not need to gain access to elasticsearch for the grafana server, e.g. using vpn is sufficient for customers.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an api key in elasticsearch: https://www.elastic.co/guide/en/elasticsearch/reference/current/security-api-create-api-key.html
- Setup the datasource with custom http header key "Authorization" and value 'ApiKey Base64EncodedApiKey'" + "with credential set to true (we want the header to be sent to elasticsearch)
- save+test

**Anything else we need to know?**:
After testing the datasource I do not see the header "Authorization" with the ApiKey from the datasource and get an BasicAuth window.
Modifing the request, e.g. devtools in Firefox that way, that I add the header and resend the request works fine (for testing).
Testing the ApiKey itself is quite easy in the shell:
curl -XGET -H "Authorization: ApiKey Base64EncodedApiKey==" "https://myElasticsearch:9243/myindex/_mapping"
Encoding: echo -n "ApiKeyId:ApiKey" | base64

Of course Elasticsearch need cors-settings enabled:
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-headers: "X-Requested-With, Content-Type, Content-Length, Authorization"
http.cors.allow-credentials: true

**Environment**:
- Grafana version: Grafana v7.0.4 (c4d8d0c2ae)
- Data source type & version: Elasticsearch core
- OS Grafana is installed on: official Docker image
- User OS & Browser: mac, linux, windows, different browsers and versions, e.g. Chrome 83.0.4103.116 on Mac 10.15.4 
- Grafana plugins: Default only
- Others: Elasticsearch 7.7.0 and surely all other 7+

**Comment by torkelo** [comment]
Custom headers should only be visible when access mode is set to server, it does not work for browser access.

**Comment by torkelo** [comment]
created issue to hide custom headers when access is set to browser  https://github.com/grafana/grafana/issues/26422

I would try to move away from browser access mode, it will likely be removed in a future release

**Comment by LukasKucharski1887** [comment]
Do you plan to enable api-access instead of basic auth for elasticsearch datasource in a future release of grafana @torkelo ?

**Comment by torkelo** [comment]
not sure what you mean api access? 

We plan to remove the direct browser access mode, so you accessing Elasticsearch has to go through the grafana-server backend, as that will provide better security (for example not leaking api keys or basic auth passwords to all Grafana users which browser access does). And it means we no longer need to duplicate the elasticsearch response parsing code in both frontend and backend

**Comment by pawelpruszynski-tomtom** [comment]
@LukasKucharski1887 did you solve the issue?
