### ISSUE TITLE
Sort order of legends

### ISSUE THREAD

**Issue by linuxbutler** [grafana/grafana#2640]
Hi Torkel

I am not sure if I am missing an obvious setting, but I googled around and couldn't find a conclusive answer. 

I am using grafana-2.1.0-1.x86_64 and InfluxDB 0.9.3

On all my panels, I am struggling to order the legends in a consistent way. Every time I (re)load the page, the legends appear in a different order. Eg: 
![image](https://cloud.githubusercontent.com/assets/8770033/9598545/e75e4fce-508c-11e5-8615-8a150276397f.png)

It would be ideal if I could specify somehow to order by [ none | alphabetically asc | alphabetically desc ]

I think the ideal place to put this would be Edit Panel -> Axis & Grid -> Legend -> Sort Order

However, optionally I would also like to override the sort order. For example, in the image above, I would like to have the order as: 
total
dead
disk-sleep
idle
locked
running 
sleeping
waiting
zombie

So you can see the order is sorted alphabetically, but I promoted the "total" legend to be first. 
For me, it would make sense the add this option to Display Styles -> Series specific option:
![image](https://cloud.githubusercontent.com/assets/8770033/9598740/5c5f946c-508e-11e5-8695-63c7ab1a29ec.png)

Something like "sort order override". Then I can put "total" as 1st, and the rest of the series are ordered alphabetically asc or desc. 

Hope this makes sense!
Thanks again!

**Comment by torkelo** [comment]
you can specify sort order by clicking on the legend column headers.

Also I would heavily advice against showing avg, min, max on the same legend as these will in many cases be incorrect. For example say your query is `select mean(value) ... `

That is InfluxDB is going to apply average to get the number of values down to one value per pixel. The legend values are calculated by Grafana client side, so if your query has the `mean` function then you can show `avg` in the legend, if you have `max` then the max legend value will be accurate. 

But they cannot be accurate at the same time.

**Comment by gnydick** [comment]
there is no metric name header to click to sort on, seems like a no-brainer of a choice to do it

**Comment by stmax82** [comment]
@torkelo maybe I'm missing something but I think this should be reopened - if the legend only contains the metric names, there is no column header that can be clicked to sort them...

**Comment by Prestaul** [comment]
By editing the json for a panel directly I can add `"sort": "current", "sortDesc": false` under `legend`, which sorts both my legend and the stack order of series in my chart. There really needs to be an independent way to sort the stack order and the legend order.

I want to be able to define the stack order based on values (e.g. largest on top) but sort the legend consistently between charts (e.g. sort aliases alphabetically).

**Comment by bduffany** [comment]
Can this be re-opened? Doesn't seem to be fixed

**Comment by pumano** [comment]
any news on this?

**Comment by muzyka-viacheslav** [comment]
+1
I tried all the proposed workarounds above, and nothing works, unfortunately.
Data sorting is very important, have no idea why it has so little priority in your backlog guys.

**Comment by pumano** [comment]
@muzyka-viacheslav I got it via JSON patching as @Prestaul wrote. But looks like it's not hard to add in UI, and I want to add it, via pull request, if I found some spare time.

**Comment by muzyka-viacheslav** [comment]
@pumano unfortunately, panel JSON direct changes don't work for me.
Here is the configuration of the legend: 
`"legend": {
      "displayMode": "table",
      "placement": "right",
      "calcs": [
        "sum",
        "max"
      ],
      "sortBy": "sum",
      "sortDesc": true
    }`

**Comment by pumano** [comment]
Try to change `"sortDesc": true` to `"sortDesc": false`

**Comment by parthgajaria** [comment]
Modifying the json works to sort a table view of the legend, but there’s no way to sort the regular legend view by metric either ascending or descending

**Comment by pumano** [comment]
@parthgajaria its possible via UI, check settings where you change miltiple value to show or single, then you can choose increasing or decreasing.

**Comment by parthgajaria** [comment]
> @parthgajaria its possible via UI, check settings where you change miltiple value to show or single, then you can choose increasing or decreasing.

@pumano that isn't for Legend, that's for the hover tooltip

**Comment by endlesslycurious** [comment]
To me if the legends don't get sorted consistently then its easy to make the mistake of looking at one chart seeing an interesting metric then looking at the same colour on another chart (graphing different metrics for the same objects) and think your looking at the same object when your not. 
![image](https://user-images.githubusercontent.com/61634041/116345965-0fff6800-a79e-11eb-8111-32f3d43e8650.png)
For example on the CPU chart the interesting blue spike is the prometheus container but the blue line on the next Memory chart is actually a promtail container. If these containers were sorted by name in the legend then I'd expect them to have the same colour on two charts which would make it more intuitive to me when looking for patterns.

**Comment by shohei-ihaya** [comment]
> By editing the json for a panel directly I can add "sort": "current", "sortDesc": false under legend, which sorts both my legend and the stack order of series in my chart. There really needs to be an independent way to sort the stack order and the legend order.

I cannot sort the order of legends by editing json shown above ( at grafana 10.2.3 )

Any ideas?

**Comment by evadim** [comment]
If someone search for solution how to add sort via the UI here it is:

- Enter dashboard edit mode,
- Click on **Legend headers** you want to sort (for example **Max**),
- Press **Save Dashboard**

If you switch to diff tab you can see something like this:
```diff
-          "showLegend": true
+          "showLegend": true,
+          "sortBy": "Max",
+          "sortDesc": true
```
Tested in `Grafana v11.6.0 (d2fdff9ee4)`
