### ISSUE TITLE
Custom JS tabs menu  not responding since move to 7.1.0 (from 6.6.2)

### ISSUE THREAD

**Issue by dannyman00123** [grafana/grafana#26406]
**What happened**:
Upgrading to 7.1 has disabled JavaScript query execution in custom text panel.

**What you expected to happen**:
Simple "Tabs" menu to cycle between "Dashboard explanations" for my multi-visualisation dashboards no longer responding to the button presses.

**How to reproduce it (as minimally and precisely as possible)**:
The below is an example html object I would use. **I operate with disable_sanitize_html=True**

https://www.w3schools.com/howto/howto_js_tabs.asp
We essentially use a customised version of the above, with no change to the JS itself.

**Anything else we need to know?**:
Worked fine on 6.6.2. Upgrade to 7.1.0 this morning and noted this change.

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 18.0.4
- User OS & Browser: Windows 10 Chrome,Internet Explorer and Edge
- Grafana plugins: Text Plugin
- Others:

**Comment by freudwasright** [comment]
+1
Happened to me as well, upgraded from Grafana version: 7.0.3 to 7.0.1 and the code within the <script> tags cannot be seen, js cant be executed on button click.

**Comment by dannyman00123** [comment]
@freudwasright reverting back to 7.0.0 should fix the issue then?

**Comment by freudwasright** [comment]
@dannyman00123 I think it should, but then what's the point in upgrading your software if features disappear.

**Comment by dannyman00123** [comment]
Probably connected to the following changes made in v7.1.0-beta1

TextPanel: Adds proper editor for markdown and html. #25618, @hugohaggmark
TextPanel: Removes Angular Text Panel. #25504, @hugohaggmark
TextPanel: Removes text mode. #25589, @hugohaggmark

**Comment by dprokop** [comment]
@dannyman00123 @freudwasright sorry guys for the trouble. We have migrated the Text panel to React, we must have missed something obvious. Investigating.

**Comment by dprokop** [comment]
React's dangerously injected HTML (https://reactjs.org/docs/dom-elements.html#dangerouslysetinnerhtml) is not evaluating script tags, hence you panels are not working. A good overview can be found here: https://codesandbox.io/s/2rwqy2m0r?file=/src/index.js

Trying to find a workaround.
