### ISSUE TITLE
How to combine other dashboards into one dashboard?

### ISSUE THREAD

**Issue by MichaelScofield** [grafana/grafana#2641]
Say I have a cpu1-dashboard and a cpu2-dashboard, how can I create a "cpu-all-dashboard" that combine cpu1 and cpu2 dashboards without copy-paste the 2 dashboards into the "all" dashboard?

Thanks!

**Comment by torkelo** [comment]
export both dashboards to json, combine them in a text editor :)

**Comment by MichaelScofield** [comment]
Thanks for the reply. 

Yes, of course it can be done like that. But if one dashboard ever changed, I have to do the "export-combine-import" again. What I really want is, embedded one dashboard into another. Just like "Add Panel-> Graph", I can do "Add Panel -> Dashboard" and show another dashboard in place.

Sorry if my title made some misunderstandings, I have changed it to make it more precise to my requirements.

**Comment by MichaelScofield** [comment]
hi @torkelo can you reopen this issue?

**Comment by torkelo** [comment]
@MichaelScofield I am not sure, why would you want this?

**Comment by MichaelScofield** [comment]
@torkelo I have ten cpus to monitor, each cpu generates all kinds of metrics that I want to show them in its own dashboard, cpu1-dashboard, cpu2-dashboard, ...

In the meantime, I also want to have a unique dashboard that shows all the cpus' metrics, so I can see the whole picture.

**Comment by torkelo** [comment]
@MichaelScofield but should that not be 3 dashboards? one cpu specific dashboard and one overview dashboard?

**Comment by MichaelScofield** [comment]
@torkelo 
I have updated the comment. Yes there're 3 dashboards, and all I want is changing one specific dashboard would not have to change the overview dashboard.

**Comment by torkelo** [comment]
But the overview dashboard would be different now? Containing more overview style graphs?

**Comment by MichaelScofield** [comment]
Yes exactly! The overview dashboard will also be changed according to the specific dashboard! It will contain the new graph that the changed specific dashboard introduced.

**Comment by torkelo** [comment]
what I was saying is that an overview dashboard should not contain other dashboards it should contain overview style graphs. and dashboard links to the more specific dashboards.

**Comment by torkelo** [comment]
making overview dashboards by embedding other dashboards does not make sense, just make one big dashboard with collapsed rows in that case.

**Comment by MichaelScofield** [comment]
Yes... that big dashboard with collapsed rows embedded with other dashboards is just what I need. ;-)

**Comment by MichaelScofield** [comment]
Is there a way to achieve that big overview dashboard?

**Comment by torkelo** [comment]
yes, using rows and collapse them. you wont need embedding other dashboards in this case, you can just have one big dashboard since your overview dashboard is not really an overview dashboard but a dashboard with other dashboards. So you can just skip the whole thing and create one big dashboard in that case :)

**Comment by MichaelScofield** [comment]
That's what I'm doing now, thanks for all these replies and your patience!

**Comment by torkelo** [comment]
np, sorry for being problematic, just trying to understand your use case. I think I will keep this closed as I think this can be solved in other ways.

**Comment by rightfold** [comment]
This would be very useful for the following use case:

- System being monitored consists of multiple services.
- Each service has its own dashboard with panels specific to that service.
- Generic dashboards for CPU usage, memory usage, disk I/O etc, with a template variable that can be one of the services.

Embedding the generic dashboards in the service dashboards, with the template variables set to the respective services, would be great to have.

**Comment by rumelia** [comment]
Hi, can this issue be reopened?

**Comment by unaiur** [comment]
We have a wiki in front of Grafana that combines multiple dashboards in one single wiki page using frames. That allow us to have generic AWS/SQS and AWS/DynamoDB dashboards that receives the required parameters in the URL. Also, we use generic dashboards to monitor load balancers and host fleets for each service without having to repeat the dashboards again and again.

**Comment by ajaywazir** [comment]
Hi,
I am trying to have one dashboard that shows couple of other dashboards. I try to use panel plugins like Ajax/Text/HTML etc and try to display another dashboard (or a dashboard snapshot) inside IFRAME in these panel. All the while being on the same machine and target iframe is also local. However, no matter what I do, it says, localhost refused to connect, when I try to link the iframe to a dashboard or dashboard link or a local dashboard snapshot using e.g 
<iframe src="http://localhost:8800/d/e1X5QVgiz/meter-status?orgId=1">Cannot load </iframe>

However this link works in the panel
<iframe src="https://snapshot.raintank.io/dashboard-solo/snapshot/y7zwi2bZ7FcoTlB93WN7yWO4aMiz3pZb?from=1493369923321&to=1493377123321&panelId=4" width="650" height="300" frameborder="0"></iframe>
I wonder why?
Ajay

**Comment by arielb135** [comment]
Any update on this? we are using kubernetes and deploy a dashboard per microservice - but i want to combine them to one big dashboard - if it could be dynamic - it would be even better (meaning - loop over existing dashboards and combine them)

**Comment by amytleonard** [comment]
Still looking for this feature, for high-level dashboards (think enterprise) to not have to update code every time one of the lower level dashoards changes it's panel config.  Any updates?

**Comment by ryantxu** [comment]
I tried this a while ago... may be relevant:
https://github.com/grafana/grafana/pull/15620

**Comment by g10guang** [comment]
Link maybe satisfy this feature.

![image](https://user-images.githubusercontent.com/18458140/66732441-8c697900-ee8e-11e9-8f54-f0061a79db37.png)

![image](https://user-images.githubusercontent.com/18458140/66732595-2cbf9d80-ee8f-11e9-98d2-6622276e49cb.png)

Click the button will jump to anohter dashboard.

Or we can use variable feature.

![image](https://user-images.githubusercontent.com/18458140/66732673-6a242b00-ee8f-11e9-8018-b29b0b9e1e8d.png)

![image](https://user-images.githubusercontent.com/18458140/66732656-5aa4e200-ee8f-11e9-9258-3ed5bf2ff6a6.png)

**Comment by prashant1rana** [comment]
This is a very important feature, which can be used in different scenarios like:
1. You have 3 different panels and you want to create 4 dashboards with different combinations as
Dashboard #1 : Panel #1 + Panel #2
Dashboard #2 : Panel #2 + Panel #3
Dashboard #3 : Panel #3 + Panel #1  
Dashboard #4 : Panel #1 + Panel #2 + Panel #3

Now you wanna play Grafana playlist on a Kiosk/TV.  

Current way: Create 4 new dashboard and create new panels for each dashboard.
Isue: If you wanna change something for Panel #2.. You will have to update Dashboard #1, #2 and #4. That is not user friendly at all, beacause you are gonna end up with more than 20 dashboard if you are gonna monitor a medium size system.

What would be awesome:-
1. Option to create panels and name them.
2. Creating dashboard with new panels or you can import above created panels.
3. On run time, dashboard will get the updated content using panel_Id
4. If you wanna change panel #2, you don't need to change anything in any dashboard.

If you ask me, this feature was expected by default.

**Comment by blakebarnett** [comment]
I was thinking another way to achieve this that might not be such a big change would be to have rows use their own set of variables, so each row could have a separate drop-down for selecting specifics that only affect that row.

**Comment by Deepak-trinesis** [comment]
I am not sure if comments on closed thread are checked, may be we want to reopen this issue or create a new one with details mentioned by @prashant1rana
