### ISSUE TITLE
Get Grafana current / logged user team

### ISSUE THREAD

**Issue by Daniel-Mompean** [grafana/grafana#26421]
we would like to filter the user’s access according to their team (even if the variable returns only one team)

example: we have a “cluster” variable in our dashboard, the “test” user belongs to the “europe” team, so the “test” user will only see information from the “cluster” or “europe” variable

this variable could bring only one team to which it belongs, or bring separated by “;”

we want to use the team as a filter in queries

we currently have to have duplicate dashboards per cluster, which makes support and maintenance difficult

this resource would be very useful

**Comment by torkelo** [comment]
This won't work as templating is all processed in the browser, so any user could modify the http request query sent to the backend. 

So using templating for security (filtering data) is not possible.

**Comment by Daniel-Mompean** [comment]
Again pls,

we would like to filter user access according to their team (even if the global variable returns only one team)

example: the user "test" belongs to the "europe" team, so the user "test" will only see information from the "europe" cluster

the idea is to have a global variable that brings the team of the current / logged user, this variable can bring only one team to which it belongs or separate by ";"

we want to use the team (in a global variable) as a filter in queries (the user is not allowed to change)

Currently, we need to have duplicate panels per cluster, which makes support and maintenance difficult

this feature would be very useful

**Comment by torkelo** [comment]
It would not be secure though as any user could see the teamId in the http request and change it

**Comment by Daniel-Mompean** [comment]
if we create the team with a cluster name, and retrieve it in a global variable, we can join it with the table's cluster field (database)

it will not be possible to change via http

we are using Grafana on a global scale, this is mandatory for our project

![cluster](https://user-images.githubusercontent.com/68402165/87828714-e2bb7c00-c853-11ea-9643-6547955bc46e.PNG)

**Comment by torkelo** [comment]
Sure it will as it will be part of the query, and queries are sent via http, so any user can change the query to anything else
