### ISSUE TITLE
Grafana MSI Installer does not upgrade cleanly

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#26423]
**What happened**:
After installing and UPDATING grafana (OSS) on windows several times using the MSI installer, I noticed it does not cleanly upgrade the old version but rather installs each version seperately in windows although its overriding the installation directory.

Also the `INSTALLDIR` (*Speicherort*) information is missing from the MSI installation (column is empty).

![grafik](https://user-images.githubusercontent.com/33002073/87818523-fcb48900-c86a-11ea-95b8-3b9d43232400.png)

> 
>
> **⚠ Uninstalling an "older" version via windows software panel will UNINSTALL THE LATEST VERSION**
> 

**What you expected to happen**:
The MSI installer should have a unique product GUID (?) and be able to detect its running an upgrade.

**How to reproduce it (as minimally and precisely as possible)**:
- Install `grafana-7.0.6.windows-amd64.msi` all default settings
- Install `grafana-7.1.0.windows-amd64.msi` all default settings

Now you got two entries in apps list, easily reproducible in e.g. Windows Sandbox:

![grafik](https://user-images.githubusercontent.com/33002073/87819102-012d7180-c86c-11ea-82a4-8e00e76d2210.png)

**Environment**:
- Grafana version: 6.6.2 till 7.1.0 ongoing
- OS Grafana is installed on: Windows 10 x64 2004

**Comment by aknuds1** [comment]
Thanks for reporting this issue; I am looking into the Windows installer building currently in any case, so makes sense I look at this too.

**Comment by aknuds1** [comment]
Assigning to @briangann since according to @daniellee, he should be able to solve it.

**Comment by marefr** [comment]
Fix for this will be included in Grafana v7.4.0 planned to be released tomorrow.
