### ISSUE TITLE
Units: nanosecond unit to scale to hours 

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#26428]
**What happened**:

Have a metric in nanoseconds, select unit: ```Time\ nanoseconds (ns)```. It will display as minutes even though the value is more than 1 hour.

![image](https://user-images.githubusercontent.com/43188411/87828821-6f7f2d80-c886-11ea-80f1-c80151b8d489.png)
![image](https://user-images.githubusercontent.com/43188411/87828665-17482b80-c886-11ea-896a-42f25f633e22.png)

**What you expected to happen**:

I expect it to show as hours when it's more than 1 hour and even days when it's more than 1 day.

**Environment**:
- Grafana version: 7.1.0 Alpine Docker
- Data source type & version: InfuxDB 1.8.1

**Comment by torkelo** [comment]
Currently this unit does not re-scale the value above minutes https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts#L34
