### ISSUE TITLE
Get Grafana current / logged user team

### ISSUE THREAD

**Issue by Daniel-Mompean** [grafana/grafana#26424]
we would like to filter user access according to their team (even if the global variable returns only one team)

example: the user "test" belongs to the "europe" team, so the user "test" will only see information from the "europe" cluster

the idea is to have a global variable that brings the team of the current / logged user, this variable can bring only one team to which it belongs or separate by ";"

we want to use the team (in a global variable) as a filter in queries (the user is not allowed to change)

currently, we need to have duplicate panels per cluster, which makes support and maintenance difficult

we are using for global systems, with great expectations with Grafana

this feature would be very useful

**Comment by aknuds1** [comment]
Isn't this a uplicate of #26421?

**Comment by Daniel-Mompean** [comment]
can we have the opportunity to chat before closing the ticket?

**Comment by aknuds1** [comment]
If you think Torkel is wrong in closing the original ticket, I would present him with a convincing argument, that the issue should be re-opened, there.

**Comment by Daniel-Mompean** [comment]
maybe I wasn't clear on the first ticket

we want to use the user team (in a global variable) as a filter in queries (the user is not allowed to change)

currently, we need to have duplicate dashboards per cluster, which makes support and maintenance difficult

we are using for global systems, with great expectations with Grafana

this feature would be very useful
