### ISSUE TITLE
Stacked + percent needs to handle selected/deselected metrics

### ISSUE THREAD

**Issue by heliodor** [grafana/grafana#26432]
**What would you like to be added**:
When the visualization settings are "stacked" + "percent", there should be an additional toggle to choose how the percent is calculated. There should be at least these two choices:
- Compute the percent of a given metric from the total of all metrics regardless of what's shown/hidden on the chart legend
- Computer the percent of a given metric from the total of only the metrics that are chosen as visible by the user on the chart legend 

**Why is this needed**:
Example:
Say you're looking at a stacked percent chart of CPU usage that shows "idle", "user", "system", and more, you click on "idle" to see the details of how much it dipped. You click it to select only that metric and suddenly, because it's the only one selected, it's just a flat 100% line.

Say, you have a thin zig-zagging metric through the middle of the chart because of the stacking. You click it to see how it varied over time, but again, it becomes an uninformative 100% flat line.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
