### ISSUE TITLE
create index for alerts

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2643]
see https://github.com/raintank/grafana/issues/230

step 1 is for the backend to receive the dashboard jsons upon save, so we can parse for alerting rules and maintain the index. any idea how this could work @torkelo ? i don't know much about dashboard saving...for raintank i see a post to `https://app.raintank.io/api/dashboards/db/` but people can enable all kinds of stores for their dashboards (like ES, influx, sql, ...) does it go through the api in all cases?

**Comment by torkelo** [comment]
dashboards are always stored in the Grafana DB, not in ES or in Influx, that was in only pre 2.0 

Maybe create a DashboardUpdated event and publish that whenever a dashboard is updated/created, 

like this:
https://github.com/grafana/grafana/blob/master/pkg/api/signup.go#L45

but publish here: 
https://github.com/grafana/grafana/blob/master/pkg/api/dashboard.go#L107

then create a new alerting service under services that subscribe to the event:
Like this for example:
https://github.com/grafana/grafana/blob/master/pkg/services/notifications/notifications.go#L31

**Comment by bergquist** [comment]
This have already been solved. Closing this.
