### ISSUE TITLE
Inspect query mixes all queries from dashboard

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26434]
**What happened**:

The queries in the inspect panel are mixed from all the dashboard

**What you expected to happen**:

When I select a panel, click on Inspect -> Query I expect only to see/refresh the specific panel's query

**How to reproduce it (as minimally and precisely as possible)**:

1. open https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&refresh=5s
2. set auto-refresh rate 5s (if not set)
3. inspect a panel (e.g. https://play.grafana.org/d/000000056/graphite-templated-nested?inspect=3&inspectTab=query&orgId=1&refresh=5s )
4. click refresh/wait 
5. observe multiple queries are rendered 

![query-refresh-1](https://user-images.githubusercontent.com/8693064/87848728-ed2d5280-c8f3-11ea-9139-01240b483c29.gif)

![query-refresh-2](https://user-images.githubusercontent.com/8693064/87848734-f7e7e780-c8f3-11ea-8ea2-e0f448aa188f.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: graphite
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Yes, query inspector listens to queries, so you have to disable auto refresh when you use it

**Comment by torkelo** [comment]
not ideal, and could  be improved in the future
