### ISSUE TITLE
7.1.0: scrolling and scaling issues on mobile devices (iOS)

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#26439]
**What happened**:
Since update to version 7.1.0 scrolling and scaling on mobile devices (iPhone, iPad) does not work properly.
Dashboards are not scaled correctly on 7.1.0.
Text in text fields is not scaled correctly on 7.1.0.
Scrolling hangs extremely, on Smartphones unusable.

**What you expected to happen**:
Smooth scrolling like on 7.0.6 or earlier versions. 

**How to reproduce it (as minimally and precisely as possible)**:
Update to 7.1.0

Scaling comparison between versions:
![grafana-compare-7-71](https://user-images.githubusercontent.com/14274103/87867348-5791d180-c98c-11ea-97a5-0e6c375e8cde.gif)

**Anything else we need to know?**:
I have used Safari under iOS.

**Environment**: 
- Grafana version: 7.1.0
- Data source type & version: N/A
- OS Grafana is installed on: docker / Ubuntu
- User OS & Browser: iOS13.6 / iPadOS13.6
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
The text panel issue is still left: https://github.com/grafana/grafana/issues/26591 
But the scrolling should be fixed in 7.1.1
