### ISSUE TITLE
Cannot explore elasticsearch logs

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#26437]
**What happened**:
Cannot explore logs.
Logs datasource is viewed as metrics (query, metric, group by) instead of logs (only query).

**What you expected to happen**:
Explore elasticsearch logs datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Create elasticsearch logs datasource.
Try to explore logs.

**Anything else we need to know?**:
The `Metrics/Logs` switch button is now missing. **Button was present in v7.0.3**.
![explore-btn](https://user-images.githubusercontent.com/22418250/87855793-41036000-c923-11ea-9b66-9f359ee1a078.png)
Without this button I cannot switch to logs.

**Environment**:
- Grafana version: v7.1.0 (8101355285)
- Data source type & version: Elasticsearch 7.8.0
- OS Grafana is installed on: docker
- User OS & Browser: win10, Firefox
- Grafana plugins:
- Others:

**Comment by kaydelaney** [comment]
Hey there, this is just a consequence of the change introduced in Grafana 7.1 removing the Explore mode switcher from the toolbar. To view logs, just choose 'Logs' from the 'Metric' dropdown in the query builder:
<img width="338" alt="image" src="https://user-images.githubusercontent.com/45561153/87928349-91da9c00-ca7c-11ea-83e8-75dec83c5923.png">

**Comment by cdalexndr** [comment]
Should be added to documentation.

**Comment by isuldor** [comment]
Here's one such section that still describes the old Metrics/Logs switcher (including a screenshot of it):
https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#querying-logs-beta

**Comment by taidv** [comment]
When I used Logs from metrics to query Logs, it only shows the id from Elasticsearch so the de-dup feature does not work. Does anyone know a workaround? 
![Screen Shot 2020-09-10 at 13 23 38](https://user-images.githubusercontent.com/8085635/92681540-daba1d00-f368-11ea-8174-67ad5746c876.png)

**Comment by stevekatsaras** [comment]
> 
> 
> When I used Logs from metrics to query Logs, it only shows the id from Elasticsearch so the de-dup feature does not work. Does anyone know a workaround?
> ![Screen Shot 2020-09-10 at 13 23 38](https://user-images.githubusercontent.com/8085635/92681540-daba1d00-f368-11ea-8174-67ad5746c876.png)

I have found a workaround!
When you are setting up the Elasticsearch Datasource, in the "Message field name", enter "_source" (without the double quotes). Save that.
In the Explore screen, select "Logs" in the metrics dropdown, and now you should be able to see all the Elasticsearch logs.

**Comment by zoltanbedi** [comment]
This is added to documentation so closing now.
