### ISSUE TITLE
7.1.0: JavaScript in Text panel not working

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#26435]
**What happened**:
After update to 7.1.0 my scripts in Text Panel inserted in <script></script> tags stopped working. They are also not colored properly.

**What you expected to happen**:
Scripts should execute as before (in v7.0.0).

**Environment**:
Grafana version: 7.0.3
Data source type & version: Influxdb 1.7.9
OS Grafana is installed on: Debian 4.9
User OS & Browser: Opera Gx

**Comment by dprokop** [comment]
Fixed by #26413
