### ISSUE TITLE
Grafana is showing the blue welcome panel on a provisioned Home dashboard

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26447]
**What happened**:

After being able to set the dashboard through an environmental variable ( https://github.com/grafana/grafana/issues/26441 ), now I am facing another issue. In between my dashboard the "Welcome panel" where it says "Basic", "Grafana fundamentals", "Add your first data source" appears. I can click on "Remove this panel" and it will disappear but only temporary. If I got to the provisioned dashboard itself (http://localhost:3000/d/main/main) the welcome panel is not there. So somehow it is injected into my own dashboard.

**What you expected to happen**:
Not see the "Welcome panel" in my provisioned main dashboard

**How to reproduce it (as minimally and precisely as possible)**:
1. Provision a dashboard (e.g. main.json)
2. Set the provisioned dashboard as main (I have set it through env variable)
3. Open grafana and check that there is the blue "Welcome panel" which cannot be removed

Step by step to reproduce it:
1. Create Dockerfile and main.json as follows, place them in the same folder

Dockerfile:

```
FROM grafana/grafana:7.1.0

ADD main.json /etc/grafana/provisioning/dashboards/main.json
```

main.json:

```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 1,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "-- Grafana --",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "percentage": false,
      "pluginVersion": "7.1.0",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "Main",
  "uid": "main",
  "version": 1
}
```

2. Run grafana with default dashboard:

this is how to set the variable:
`GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/main.json`

full command to run Dockerfile:

```docker build -t grafana . && docker run -p 3000:3000 --env GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/main.json --name grafana grafana```

3. Open http://localhost:3000 and login with admin/admin
4. Observe "Welcome panel" in main dashboard

![image](https://user-images.githubusercontent.com/8693064/87958003-097eea00-cac2-11ea-8d7b-8bc4d6382fe1.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- OS Grafana is installed on: docker
- User OS & Browser: win10 chrome / macOS chrome

**Comment by nikobearrr** [comment]
Hi @aknuds1 , I have added step-by-step on how to reproduce it. Perhaps that can help you with the investigation.

**Comment by amnonh** [comment]
Just tested it with both v7.1.3 and v7.1.5 problem exists

**Comment by amnonh** [comment]
One more issue that could be related, when using `GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH` the home dashboard starts without the setting and save button

**Comment by kopaygorodsky** [comment]
I installed grafana using helm (prometheus-operator). Deploy a dashboard in ConfigMap and later specify "GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/tmp/dashboards/x.json" in grafana container. Seems env var is ignored, nothing in logs about `Config overridden from Environment variable`.

**Comment by amnonh** [comment]
Any updates? It seems like a small issue, but setting the home dashboard is such a required UX

**Comment by tu-nv** [comment]
I also face this issue. I believe its a big issue because it directly affects the user experience!

**Comment by neel5481** [comment]
I also face similar issue where "Welcome Panel" appears in between the dashboard and asking user to add datasource and all which makes very bad user experience.

**Comment by amnonh** [comment]
This issue makes #10266 useless

**Comment by amnonh** [comment]
Hey guys, I've added a trivial fix with this PR: #28710
Can you please try to push it? Having a home dashboard will be a huge jump forward in usability and this bug is what stands in the way of that

**Comment by ryantxu** [comment]
Can you take another try at the PR?  it has 275 changes and a bunch of conflicts... that makes it hard to review :)
![image](https://user-images.githubusercontent.com/705951/97765678-43ec2000-1ad0-11eb-9124-9a5dc8de8e79.png)

**Comment by amnonh** [comment]
It should have been 4 lines, I'll take a look
