### ISSUE TITLE
legend bug when using cumulative stacking

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2644]
tooltip values are good but not legends :

![grafana-stack-legend-bug](https://cloud.githubusercontent.com/assets/8385646/9616819/78f052ac-5100-11e5-8f5a-5e9e29c471a3.gif)

**Comment by torkelo** [comment]
legend values are not supposed to be affected by stacking

**Comment by rschitz** [comment]
I think it would make sense that legend values reflect tooltip values, that's why i selected cumulative in the first place. I often diff series and stack them to make a cleaner visual since colors are separated.

**Comment by torkelo** [comment]
yes, I kind of agree with you. But stacking and cumulative tooltip has been in Grafana since v1, if I change so it also effects the legend it will break/change thousands of dashboards, not sure I want to do that.

**Comment by rschitz** [comment]
I understand. I just discovered today that cumulative tooltip is also affected by hidden queries, makes my life even harder :)
