### ISSUE TITLE
Dashbard: Lazy loading panels does not work in Safari / iOS

### ISSUE THREAD

**Issue by rafale77** [grafana/grafana#26442]
**What happened**:
Not sure if this has been reported before: I upgraded my grafana instance from 7.0.6 to 7.1.0 and lost 3 or my 8 panels from the dashboard. I can see that they are actually still there but are just completely blacked out. Reverted back to 7.0.6 and they become visisble again.
**What you expected to happen**:

No disappearance in panel display.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade to 7.1.0 on a large graphite database dashboard with more than 5 panels

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: graphite
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser: macOS Safari, iOS Safari
- Grafana plugins: N/A

**Comment by torkelo** [comment]
You have to add the dashboard json , along with all queries and responses for us to troubleshoot this.

Are you using template variables and repeated panels? Any error in the chrome dev console? Any graphite queries that return empty results? Anything strange with those queries (check query inspector)

**Comment by rafale77** [comment]
So this is interesting. I just retested it and it works fine on firefox on the same mac, so it is a browser specific issue with safari which I tested on both iOS and 2 different macOS. This should narrow down the problem quite a bit.
I am also not seeing any error on the safari dev console...

**Comment by CaptainQwark** [comment]
We noticed the same problem on multiple iOS devices, and it looks like the graphs that are not on screen in the initial page, are not loaded when scrolling down. (the page scrolls but show just empty space)

**Comment by torkelo** [comment]
Wonder if this is an issue in 7.0 as well, as it seems to be an issue with no scroll events on safari, and we have not updated the scrollbar component we use to capture scroll events

**Comment by CaptainQwark** [comment]
@torkelo Everything works fine for us again on iOS (13.5.1) after downgrading to 7.0.6.

**Comment by torkelo** [comment]
Ok, strange, wonder what we changed for Safari to not emit scroll events

**Comment by cdmonk** [comment]
This is happening to me as well.

Grafana version: 7.1.0
Data source type & version: influx
OS Grafana is installed on: Ubuntu 18.04.3 LTS as a Docker container
User OS & Browser: iOS Safari, iOS Chrome (iOS 9.x on iPad 3 which is used as a wall mounted display)
Grafana plugins: N/A

My dashboard only has 4 panels. The rest of the UI elements appear to render correctly, just no panels.
Rolling back to 7.0.6 fixed it.

**Comment by torkelo** [comment]
Anyone who can please test fix PR https://github.com/grafana/grafana/pull/26495

**Comment by cdmonk** [comment]
Docker image grafana/grafana-dev:7.2.0-880340f7pre-ubuntu resolves this issue for me. Thanks!!

**Comment by iwittkau** [comment]
I just pulled the current master tag from docker hub (v7.2.0-100f200dpre (ad4f8b7091)): works as expected now. 👍🏻
