### ISSUE TITLE
Attempting to edit a panel returns TypeError: undefined is not an object (evaluating 't.title.trim') on 7.0.3

### ISSUE THREAD

**Issue by sumocomputers** [grafana/grafana#26444]
**What happened**:
Attempting to edit 2 of my panels results in an error "TypeError: undefined is not an object (evaluating 't.title.trim')"

**What you expected to happen**:
To be able to edit the panel with no error

**How to reproduce it (as minimally and precisely as possible)**:
Select Edit on the Panel

**Anything else we need to know?**:
Other panels can be edited fine, and I think it may have been fine with 6.5.2, not sure.
Tried duplicating panel, and editing that one results in error also
See attached screenshot

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: InfluxDB (1.7.10)
- OS Grafana is installed on: macOS 10.15.6
- User OS & Browser: macOS 10.15.5 & Safari 13.1.1, Brave v1.9.76
- Grafana plugins: Discrete v0.0.9, Pie Chart v1.3.9, World Map 0.2.1 + Core
- Others:

![Grafana-03](https://user-images.githubusercontent.com/656453/87882681-a8b6bb00-c9b6-11ea-926a-18e2cf758345.jpeg)

**Comment by torkelo** [comment]
Can you upgrade to 7.0.6 or 7.1 ? If problem still presists I will re-open

**Comment by sumocomputers** [comment]
Seems to be fixed with 7.1
