### ISSUE TITLE
Cannot set default home dashboard path through environment variable

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#26441]
**What happened**:

I am trying to set the `default_home_dashboard_path` configuration through environment variable, but it does not seem to work. Based on the guide here: https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables I expect I have the correct syntax.

**What you expected to happen**:

I would expect to be able to set it through the variable through env variable

**How to reproduce it (as minimally and precisely as possible)**:

1. Use docker
2. Set `GF_AUTH_DEFAULT_HOME_DASHBOARD_PATH` in the environment section to `/etc/grafana/provisioning/dashboards/all/main.json`. 
3. Start grafana
4. Observe it's not using the main.json as default dashboard

**Anything else we need to know?**:

In the logs of grafana I can see every other env variable i use in an info message "Config overridden from Environment variable", but nothing about `GF_AUTH_DEFAULT_HOME_DASHBOARD_PATH`. Perhaps I have not put the right name?

I have made sure that `/etc/grafana/provisioning/dashboards/all/main.json` exists

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- OS Grafana is installed on: Docker

**Comment by aknuds1** [comment]
Thanks for reporting this. The problem is the documentation places default_home_dashboard_path in the wrong section; it should be in _dashboards_, not _auth_. If you try setting GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH instead, it should work.

**Comment by nikobearrr** [comment]
Hi @aknuds1, I can confirm that after changing the variable it worked. Now that I have put my main dashboard on main I see the "welcome panel" inside my dashboard, but I think that is a separate issue so I will open a new ticket for that
