### ISSUE TITLE
Docs feedback: /packages_api/runtime/backendsrv.md

### ISSUE THREAD

**Issue by wz2b** [grafana/grafana#26459]
There is a link on the documentation page for BackendSrv that links to BackendSrvRequest.md but it's a 404.  There is a similar issue in [/packages_api/runtime/datasourcesrv/](https://grafana.com/docs/grafana/latest/packages_api/runtime/datasourcesrv/) where it tries to link to [DataSourceApi.md](https://grafana.com/docs/grafana/latest/packages_api/runtime/datasourcesrv/data/datasourceapi.md) which is also a 404.  If I find any others I will add them here.

**Comment by oddlittlebird** [comment]
@mckn, assigned because this is in the auto-generated docs.

@robbymilo, how did this get past the automated testing?

**Comment by mckn** [comment]
Yeah, I have this on my radar. Will fix it asap.
