### ISSUE TITLE
tooltip reports bad values when using z-index

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2645]
legend is good but tooltip value apears cumulative:

![grafana-tooltip-zindex-bug](https://cloud.githubusercontent.com/assets/8385646/9617387/062f0644-5102-11e5-96eb-e11ca65f62dd.gif)

**Comment by torkelo** [comment]
seems to have been fixed when I fixed this issue, https://github.com/grafana/grafana/issues/2620
