### ISSUE TITLE
Some global variables become unset after refresh

### ISSUE THREAD

**Issue by ez314** [grafana/grafana#26468]
**What happened**:
`${__dashboard.uid}` and `${__org}` are set when loading the page, but not after refreshing the data.

**What you expected to happen**:
`${__dashboard.uid}` and `${__org}` should always exist, even after refreshing data.

**How to reproduce it (as minimally and precisely as possible)**:
1. Put `${__dashboard.uid}` anywhere, such as in a link. Save.
2. Reload the webpage. At this point, the variable should have been converted to the dashboard uid, such as `i5Hh-QnMk`.
3. Press the "Refresh Dashboard" button at the upper right, not the browser reload.
4. Check your variables again. They now say `${__dashboard.uid}` (or `$%7B__dashboard.uid%7D`)

**Anything else we need to know?**:
This affects `__dashboard` and `__org`, but not all global variables. `__to` and `__from` are still working as expected.

**Environment**:
- Grafana version: 7.0.6
- Data source type & version: Tested with InfluxDB and default
- OS Grafana is installed on: RHEL 
- User OS & Browser: Windows 10, Chrome 84
- Grafana plugins: default plugins
- Others:

**Comment by torkelo** [comment]
This should be at least partially fixed in 7.1 , still an issue with it https://github.com/grafana/grafana/issues/26083
