### ISSUE TITLE
role_attribute_path SyntaxError when path contains a URL

### ISSUE THREAD

**Issue by rally25rs** [grafana/grafana#26469]
**What happened**:

Using`generic_oauth` to integrate with `Auth0`

By the OpenID Connect specification, custom attributes must be namespaced, and per Auth0:

> Auth0 will always enforce namespacing when performing OIDC-conformant login flows, meaning that any custom claims without HTTP/HTTPS namespaces will be silently excluded from tokens.

Based on this, I have to prefix my custom claims in my id_token with a url:
```
{
  ...
  "https://foo.com/grafana_role": "Editor"
  ...
}
```

To use this value as my role, I have tried in my `grafana.ini`

```
role_attribute_path = https://foo.com/grafana_role
role_attribute_path = "https://foo.com/grafana_role"
role_attribute_path = \"https://foo.com/grafana_role\"
```

None of which seem to work.

With `"https://foo.com/grafana_role"` Grafana reports
```
lvl=eror msg="Failed to search user info JSON response with provided path" logger=oauth.generic_oauth attributePath=https://foo.com/grafana_role err="SyntaxError: Unknown char: '/'"
```

**What you expected to happen**:

It should use the attribute name `"https://foo.com/grafana_role"` and not cause a SyntaxError.

**How to reproduce it (as minimally and precisely as possible)**:

(see above)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.4
- Data source type & version:
- OS Grafana is installed on: official Grafana docker image w/ tag `6.7.4`
- User OS & Browser: OSX, Chrome
- Grafana plugins: none
- Others:

-----

_workaround:_

I eventually had to use `["https://foo.com/grafana_role"][0]` to get something to work

**Comment by marefr** [comment]
I'm using below configuration with auth0 and it works as expected so I'll close this.
```int
role_attribute_path = contains("https://myapp.example.com/roles", 'admin') && 'Editor' || 'Viewer'
```
