### ISSUE TITLE
"Inspect data" tool missing rows when inspecting table

### ISSUE THREAD

**Issue by DanSHenry** [grafana/grafana#26460]
**What happened**:

When using the data inspector on a table, rows are missing that are otherwise present when viewing the table on a dashboard. This is also causing the CSV export to be missing the same rows. Screen shot below.

![image](https://user-images.githubusercontent.com/5855850/87962340-04e81080-ca85-11ea-9ea6-83345465a96f.png)

In this case its just one row but we've seen up to 5. In this case it also appears to be the last row

**What you expected to happen**:

All rows present in the table on the dashboard should be present in the table in the data inspector

**How to reproduce it (as minimally and precisely as possible)**:

Use the data inspector tool on a table. A lot of the details are missing from my photo because the details are confidential but its a dashboard with 1 panel, a table, that uses a few variables to filter the data in the table.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: MySQL 
- OS Grafana is installed on: RHEL
- User OS & Browser: Windows, Chrome
- Grafana plugins: N/A
- Others:

**Comment by ivanahuckova** [comment]
@DanSHenry Would you be able to share also results from the Query tab?

**Comment by damonchien** [comment]
I have the same problem and the results from the Query tab is no problem
If I use the transform and inspect data choose "Apply panel transformations"
then the missing data will be back
so it's a compatibility problem?

**Comment by DanSHenry** [comment]
I've found the issue appears to happen when there are 2 rows with the exact same timestamp, the data inspector will pick 1 of them at random each time its opened

**Comment by DanSHenry** [comment]
I think it may be because of this option but it cannot be changed:
![image](https://user-images.githubusercontent.com/5855850/88562697-03779480-cfff-11ea-8f3c-dd0fcc06cb75.png)

**Comment by DanSHenry** [comment]
> @DanSHenry Would you be able to share also results from the Query tab?

Id like to avoid that but let me know if the additional color i've just added helps in replicating or solving the issue.

**Comment by qrtalaci** [comment]
Reported in #26784:

The table contains 306 rows but in the Inspect/Data tab only two rows are displayed (and the data appears in the .csv export)

![Grafana_export_to_CSV](https://user-images.githubusercontent.com/639291/89338748-53a8c380-d69d-11ea-810b-981e337b7738.gif)
The dashboard JSON and the network data are attached in the .zip:
[json_har.zip](https://github.com/grafana/grafana/files/5024256/json_har.zip)

**Comment by Tomy8s** [comment]
We are also seeing this issue after updating:

![ezgif-7-9b895a3189c9](https://user-images.githubusercontent.com/15101089/89404106-59d88780-d711-11ea-96a6-d14df3b510cd.gif)

I think this should be raised as a bug.

**Comment by g-k-r** [comment]
same issue here. table is showing aggregated monthly data. i.e. all time values are intentionally identical. exported csv only contains a single row.
Grafana v7.1.1 (3039f9c3bd)

**Comment by chrisnew** [comment]
Same here. We downgraded Grafana to 7.0.x for now since our non-tech guys just love the export function.

**Comment by torkelo** [comment]
I think I know what is going on here, the join by time transform is removing all duplicate rows where time is the same

**Comment by trybol** [comment]
Raw query:
![image](https://user-images.githubusercontent.com/25016502/91847380-b8364e80-ec5a-11ea-85a5-47a86336dea9.png)

And the situation is the same without any transformations:
![image](https://user-images.githubusercontent.com/25016502/91848660-15ca9b00-ec5b-11ea-8332-af9e7b3af8d8.png)

**Comment by torkelo** [comment]
Still unable to replicate this, very strange

**Comment by hila3000** [comment]
Happened to me as well, inspect->data of a table panel always returns one row.

For example when the table is being built by this query-
sum by(container, pod, namespace) (kube_pod_container_status_running{namespace!~"default|istio-system|kube-public|kube-system", container="reloader"})

This is a fairly straightforward query, metric that exists publicly, not related to internal metrics we implemented.

Screenshot here:
https://ibb.co/cwBNbMr

Inspect->Panel Json output:
`{
  "type": "table",
  "title": "Panel Title",
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 8
  },
  "id": 4,
  "targets": [
    {
      "expr": "sum by(container, pod, namespace) (kube_pod_container_status_running{namespace!~\"default|istio-system|kube-public|kube-system\", container=\"reloader\"})",
      "legendFormat": "",
      "interval": "",
      "refId": "A",
      "format": "table",
      "instant": true
    }
  ],
  "options": {
    "showHeader": true
  },
  "datasource": "US-Prometheus",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": null
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "pluginVersion": "7.1.3",
  "timeFrom": null,
  "timeShift": null
}`

**Comment by torkelo** [comment]
was able to replicate now

**Comment by hila3000** [comment]
Great! Hope you can figure out what's wrong easily enough :)

**Comment by F4ncyMooN** [comment]
There is a work around here. 
1. You can add a transformation: Filter by name
2. Filter out Time field

**Comment by hila3000** [comment]
The issue is closed, does this mean a fix was pushed? if so, what is the image version number?

**Comment by torkelo** [comment]
7.2-beta1

**Comment by hila3000** [comment]
When is a GA version expected to get released with this fix?

**Comment by torkelo** [comment]
next week

**Comment by qrtalaci** [comment]
It is accidentally added to 7.1-beta1 milestone instead of 7.2-beta1

**Comment by hila3000** [comment]
@F4ncyMooN The workaround doesn't work, the rows are ok now, but many of the fields are missing.
@torkelo Great, next week has arrived but not finished yet :) I hope it'll get released this week as many of our product team awaits it.

**Comment by F4ncyMooN** [comment]
> @F4ncyMooN The workaround doesn't work, the rows are ok now, but many of the fields are missing.
> @torkelo Great, next week has arrived but not finished yet :) I hope it'll get released this week as many of our product team awaits it.

maybe you forget to select "Apply panel transformations"
![image](https://user-images.githubusercontent.com/16536745/94104111-d7df2200-fe68-11ea-90c3-c991488b2ff0.png)

**Comment by dpajin** [comment]
unfortunately, I don't see this issue in the list of bug fixes in 7.2.0 release notes?

**Comment by torkelo** [comment]
sorry, missed adding "add to changelog" label on https://github.com/grafana/grafana/pull/27422
