### ISSUE TITLE
Error message on folder creation error

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#26478]
**What happened**:
When trying to create a folder with a name already used by a dashboard, we get a 500 error, with {"message":"Folder API error"}. 

**What you expected to happen**:
Getting a 400 error with an explanatory message

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a dashboard named foo by hand (in the “General” folder)
2. POST to /api/folders { “title”:”foo”} will fail with a 500
3. Delete or rename the dashboard
4. POST /api/folders will succeed

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Interesting, will try to reproduce.

**Comment by aknuds1** [comment]
I can reproduce it in v7.0.3. Checking other versions.

**Comment by aknuds1** [comment]
Made a [fix](https://github.com/grafana/grafana/pull/26498) for it.
