### ISSUE TITLE
Data column name is now part of field name in 7.1 with Azure Log Analytics

### ISSUE THREAD

**Issue by djryanj** [grafana/grafana#26470]
**What happened**: 

In Grafana 6.7 with Azure Log Analytics (Azure Monitor) as a data source, the data table column name that Grafana used was transparently removed from the UI with no extra effort, which resulted in clean looking legend labels like this:

![image](https://user-images.githubusercontent.com/33379396/87989725-c9a70b00-ca9f-11ea-8063-d39a8eaca225.png)

Part of the labels have been removed in this image but are identical; for example, whole names might be APP-01 and APP-02. **Note that the fact that the query returns multiple data sets is not relevant.** The same occurs if selecting even a single VM (see sample KQL below).

In 7.1 (possibly 7.0), the move to dataframes has resulted in the labels now including the metric name, like this:

![image](https://user-images.githubusercontent.com/33379396/87989799-ed6a5100-ca9f-11ea-9d5b-85081c460024.png)

Again, the part after the "avg_CounterValue" would be identical like "APP" as in the first image above.

In Azure's native Log Analytics tool, the data table returned looks like this:

![image](https://user-images.githubusercontent.com/33379396/87989933-2b677500-caa0-11ea-8296-2eae8d4db0ea.png)

This is consistent with the data format in the query inspector in 6.7:

![image](https://user-images.githubusercontent.com/33379396/87990080-8600d100-caa0-11ea-900f-be5a70a0623b.png)

But in the query inspector in 7.1, we see:

![image](https://user-images.githubusercontent.com/33379396/87990166-b3e61580-caa0-11ea-847c-4719315a4107.png)

And we can see where the series labels are coming from. This "intelligent assembly" of the dataframe data has removed flexibility in how we can display metric labels on panels.

Using a field selector in the display name options does not work, as using ${__field.name} only returns the exact same column name as before, and ${__series.name} results in labels like "Series (A)", and ${__cell_N} or variants like ${**cell_N} do not resolve.

**What you expected to happen**:

No change to the label names from 6.7.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a Windows VM in Azure and ensure that it is logging performance counters to Log Analytics workspace
2. Connect Grafana 7.1 Azure Monitor (0.3.0) datasource to that Log Analytics workspace
3. In a graph panel, using Log Analytics as a data source, use the following KQL (replace "testVM" as needed to match the VM name created/available in step 1):

```
Perf  
| where $__timeFilter(TimeGenerated)   
| where ObjectName == "Memory" and CounterName == "% Committed Bytes In Use" and Computer contains "testVM"  
| summarize avg(CounterValue) by bin(TimeGenerated, $__interval), Computer  
| sort by TimeGenerated asc
```

**Anything else we need to know?**:

Possible unacceptable workarounds:

- Use Azure Monitor data source instead of Log Analytics, Part 1: This is not possible for all desired panels. Azure does not expose memory statistics (what the KQL above extracts) via the Azure Monitor datasource; it's only in Log Analytics making KQL the only method to access it.
- Use Azure Monitor data source instead of Log Analytics, Part 2: Dynamic panels are desired, and using KQL with a partial match allows for no effort in dashboarding should a VM be added or removed that matches the name format.
- Use Transformations to rename the columns: Again, since the requirement is to have dynamic panels and transformations are a very manual effort that would need to be repeated for many panels on many dashboards. 

- This may also just be me misunderstanding what's possible with dataframes and maybe I've missed something obvious.

**Environment**:
- Grafana version: v7.1.0 (8101355285)
- Data source type & version: Azure Log Analytics (Azure Monitor v0.3.0)
- OS Grafana is installed on: Docker (Linux)
- User OS & Browser: Windows 10, Firefox 78.0.2 64-bit
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
@kylebrandt @ryantxu any ideas here?

**Comment by kylebrandt** [comment]
I believe the following should display what you are after: (e.g. using `${__field.labels.Computer}` in Field Standard options for display name:

![image](https://user-images.githubusercontent.com/1692624/88056746-08d06d00-cb2f-11ea-8601-98a74e16a0a2.png)

I don't think this would work for the $object case with template in my example.

(Apologies for short reply, going to look into this a little more later today).

**Comment by djryanj** [comment]
@kylebrandt yes, that does work as a workaround. Still not ideal but it gets us back on our feet.

I have never seen any reference to a ${__field.labels.X} anywhere in the Grafana documentation for datasources and didn't know that was possible. I can see it in the API reference but I have always wondered if there was a way to access other metadata. Could this be added to the Azure datasource docs as a minimum?

**Comment by kylebrandt** [comment]
> @kylebrandt yes, that does work as a workaround... 

Thank you for confirming that it works for you

> I have never seen any reference to a `${__field.labels.X}` anywhere in the Grafana documentation for datasources and didn't know that was possible. I can see it in the API reference but I have always wondered if there was a way to access other metadata. Could this be added to the Azure datasource docs as a minimum?

Yes I will document this at https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#display-name, and reference it in the Azure Logs Analytics data source documentation as well.

> Still not ideal but it gets us back on our feet.

I have noticed that our default display in the case of labels is {v} if there is one label pair in labels, or {k=v,k=v} if more than one label pair. Perhaps we should extend this logic for display in regards to the name component in the field as well? In other words, if the frame or set of frames has multiple series, but all those series share the same name, that by default, do not display the field name. @ryantxu ?

**Comment by kylebrandt** [comment]
This is now documented at https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#display-name , and overrides have multiple matchers now - so I believe this is solved.
