### ISSUE TITLE
Variables: Expose ENV server variables in templating system

### ISSUE THREAD

**Issue by tliefheid** [grafana/grafana#26474]
**What would you like to be added**:

When using the data link i want to reference to another grafana dashboard. It would be really usefull if you could use a var (which will be provided by default) so the dashboards are more generic, when sharing them between environments.

example:

i have 2 environments: acc.company.com and company.com
i created a dashboard on acc.company with a drilldown link to another dashboard on acc.company.

now i imported the dashboard in the other environment and it still is using the drilldown link to acc.company link.

If we could replace this with either a var or something else (like reuse the current dns name and only update the endpoint) it would be really usefull

**Why is this needed**:

make sharing the dashboards more easy and keeping dashboards as generic as possible

**Comment by torkelo** [comment]
would making some serve side env variables available via templating solve your case?
like 
export GF_VARIABLE_DOMAIN=acc.company.com

then in grafana ${__env.domain}

**Comment by TomL-dev** [comment]
We deploy grafana in a container as part of a docker-compose file.
Added a var to the `environment` section for the container. I didn't see the var (GF_VARIABLE_DOMAIN) anywhere.

However, i noticed that when you don't provide a full link, it will automagically use the same domain

old drilldown link: 
https://acc.company.com/d/dashboard-id/abc&orgId=1&refresh=1m

new:
/d/dashboard-id/abc&orgId=1&refresh=1m

it will open the link on the same domain, no need for exporting extra vars

**Comment by TomL-dev** [comment]
running Grafana v7.0.3 btw

**Comment by iilei** [comment]
Would this feature also mitigate the issues with using [variables in queries for alerts](https://community.grafana.com/t/template-variables-are-not-supported-in-alert-queries-while-setting-up-alert/2514)?

**Comment by darkleaf** [comment]
up

**Comment by mdvictor** [comment]
This feature request has been open for a long time with few received upvotes or comments, so we are closing it. We're trying to limit open GitHub issues in order to better track planned work and features.
This doesn't mean that we'll never ever implement it or that we will never accept a PR for it. A closed issue can still attract upvotes and act as a ticket to track feature demand/interest.
Thank you for taking the time to create this issue!
