### ISSUE TITLE
7.1.0 Error "field sorting for a wide time series frame called on a series that is not a wide frame" when no data to display

### ISSUE THREAD

**Issue by lenssoliang** [grafana/grafana#26473]
**What happened**:
An error happen when there is no any data in the time period selected.
![image](https://user-images.githubusercontent.com/20389631/88006062-6370c580-cb3d-11ea-9e18-bce1e700d836.png)

**What you expected to happen**:
The visuals can normally display "0" when no data, instead of a error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a source of Azure Monitor, and config to connect to Application Insights
2. Add a "Stat" and set the query as below.
![image](https://user-images.githubusercontent.com/20389631/88006322-edb92980-cb3d-11ea-99ff-82b4522d0719.png)
3. Change the time period to make sure there is no data to display

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.0
- Data source type & version: Azure Monitor (0.3.0) - Application Insights
- OS Grafana is installed on: Linux
- User OS & Browser: Win10 & Microsoft Edge
- Grafana plugins: Azure Monitor (0.3.0)
- Others:

**Comment by torkelo** [comment]
@kylebrandt Any ideas what this could be?

**Comment by lenssoliang** [comment]
Thanks guys to fix this issue. And when this change will GA?
