### ISSUE TITLE
Snapshots have problems with rendering panels inside collapsed rows

### ISSUE THREAD

**Issue by Quinteger** [grafana/grafana#26483]
**What happened**: panels under collapsed rows don't render (they appear but with no grid) or render with grid but with no data; see details below.

**What you expected to happen**: panels under collapsed rows render normally just like panels outside rows.

**How to reproduce it (as minimally and precisely as possible)**:

On my home machine (win10) I was able to reproduce it by doing following:

- Download, extract and launch a portable win10 version of Grafana (worked with versions 7.0.5, 7.0.6, 7.1.0)
- Create a dashboard with 2 Random Walk panels and save it
- Create a snapshot and see that it properly rendered both panels
- Add a row and hide one of the panels inside it, collapse the row
- Create another snapshot and observe that the panel inside a row failed to render (has no grid)
- Make sure that increasing the snapshot timeout doesn't help

On my cloud machine, which runs on RHEL 7.8 and has Grafana 7.0.6 installed (downloaded the RPM manually, then sudo yum install), I observed the following:

- If all panels are inside rows, they render, but only if they have no dashboard variables in their queries, and when I open a row inside a snapshot, I get one "Annotation Query Failed, Query missing annotation definition" error popup per panel inside that row, no matter whether they rendered correctly or not
- If they have a dashboard variable in their query, they appear as a grid with "No data"
- This applies even if the variable is a manually entered custom set of values (not querying InfluxDB or something like that)
- Clicking on a variable picker inside the snapshot generates an exception in the js console

**Anything else we need to know?**:

- Cloud Grafana uses InfluxDB 1.8.0 as it's primary data source, which is installed on the same machine and is saved as localhost:8086 in Data sources. Most of the panels use InfluxDB, with a couple of Prometheus panels (which uses the same InfluxDB as persistent storage), but I reproduced similar problems using a new dashboards with 2 Random Walk panels
- After generating the snapshot, the link that's shown starts with localhost:3000 for some reason (possibly related?), obviously it doesn't work and needs to be corrected to work

**Environment**:
- Grafana version: 7.0.5, 7.0.6, 7.1.0
- Data source type & version: None (win10), InfluxDB 1.8.0 (RHEL 7.8)
- OS Grafana is installed on: win10, RHEL 7.8
- User OS & Browser: Chrome
- Grafana plugins: -
- Others: -

**Comment by Quinteger** [comment]
> - Add a row and hide one of the panels inside it, collapse the row
> - Create another snapshot and observe that the panel inside a row failed to render (has no grid)

Update to this case: putting both panels inside a row makes them render correctly, but putting only one is a problem.

**Comment by ivanahuckova** [comment]
Thanks @Quinteger for creating this issue. Yes, I was also able to replicate this.
![image](https://user-images.githubusercontent.com/30407135/88072297-29bbb100-cb75-11ea-9eac-8ba193b4147b.png)

When I publish snapshot to https://snapshot.raintank.io/, I get also following error `Cannot read property 'then' of null`. 
![image](https://user-images.githubusercontent.com/30407135/88072431-4e178d80-cb75-11ea-95aa-759927284ab1.png)

**Comment by ivanahuckova** [comment]
Also, the error is the same as in https://github.com/grafana/grafana/issues/17783.

**Comment by torkelo** [comment]
We cannot solve this, snapshots is only for visible panels

**Comment by Quinteger** [comment]
@torkelo As I mentioned they do sometimes render in collapsed rows, it depends on circumstances. Which means that the behavior needs to be made more consistent.

Also, random annotation errors are probably not part of the design either.

Sorry if I sound rant-y, the snapshot feature turned out to be of big value to me.

**Comment by torkelo** [comment]
Yea, your right. Grafana could remove collapsed rows and panels that did not complete query

**Comment by evictorero** [comment]
This is still an issue (10.2), panels inside collapsed rows are not supported in snapshots.
