### ISSUE TITLE
Hovering over table cell with URL causes text to move to left

### ISSUE THREAD

**Issue by Atomicbeast101** [grafana/grafana#26496]
**What happened**:
Whenever I hover the mouse over the table cell, it causes the text content to move to the left. It resets itself when I move the mouse cursor outside of the cell. This doesn't happen to cells that doesn't have a URL link assigned to it.
Before:
![](https://i.imgur.com/dmGCaME.png)
After:
![](https://i.imgur.com/Ph0bT5x.png)

**What you expected to happen**:
Text content in cell doesn't move when mouse cursor hovers it.

**How to reproduce it (as minimally and precisely as possible)**:
Create a table cell with random values and assign a URL to one column.

**Anything else we need to know?**:
This doesn't happen in previous v7 updates.

**Environment**:
- Grafana version: v7.1.0
- Data source type & version: Prometheus v2.17.1
- OS Grafana is installed on: Ubuntu v20.04

**Comment by torkelo** [comment]
Problem is here somewhere, https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/FilterableTableCell.tsx 

Loses it's centering when hoving. 

To test this use a table with ad-hoc filterable data (elasticsearch terms query without date histogram) or prometheus instant query should also do it

**Comment by IPv777** [comment]
Same problem here, but we dont have any link on text...
Here's a short video of the problem : https://youtu.be/h4wTHBoEsNU

**Comment by michelengelen** [comment]
@IPv777 I think the problem is not with URLs as it happens when the ad-hoc filtering buttons are shown as described by @torkelo already.

The hover state currently sets another class which has `display: inline-flex;` and `justify-content: space-between` as properties. This is what causes the strange behaviour.

I will have a look to find a solution for this.

**Comment by michelengelen** [comment]
I do have a simple solution for this. If we would add these styles to the `tableCellWrapper` styles:

```css
display: inline-flex;
align-items: center;
```

... and this to the `tableCell` styles:

```css
display: inline-flex;
align-items: center;
```

and remove the `tableCellWrapper` styles definition in the `FilterableTableCell` component it will result in this:

### text left
![Screenshot 2020-09-01 at 15 45 01](https://user-images.githubusercontent.com/32863416/91859608-f2a7e780-ec6a-11ea-92e5-4445152b7a62.png)

### text centered
![Screenshot 2020-09-01 at 15 44 32](https://user-images.githubusercontent.com/32863416/91859632-fa678c00-ec6a-11ea-8d6d-ef70e6ffd7f8.png)

### text right
![Screenshot 2020-09-01 at 15 45 27](https://user-images.githubusercontent.com/32863416/91859660-00f60380-ec6b-11ea-82d4-2d5fa22eeb63.png)


WDYT @torkelo ?

**Comment by torkelo** [comment]
looks good!
