### ISSUE TITLE
Some Angular panel plugins can ruin a frontend application in 7.1.0

### ISSUE THREAD

**Issue by diafour** [grafana/grafana#26494]
Hello from plugin author.

As you know, there are panel plugins based on Angular. These plugins should be slightly updated to work with 7.0. The worst that happens after update from 6.x is that panels with particular visualization are not working.

Now, 7.1.0 is released with merged #24779 and the situation is much worse. An Angular based plugin with `variableSrv` argument in constructor ruins an entire application:

![image](https://user-images.githubusercontent.com/66000380/87915981-78434f80-ca90-11ea-81e8-3d3b26f54a57.png)
"An unexpected error happened. TypeError: Cannot read property 'emit' of undefined" in action.

At the moment, 3 plugins are affected:

There are fixes for two plugins waiting for review in `grafana-plugin-repository`: 
https://github.com/grafana/grafana-plugin-repository/pull/686 michaeldmoore-multistat-panel
https://github.com/grafana/grafana-plugin-repository/pull/680 flant-statusmap-panel

And an issue in another plugin: https://github.com/alexandrainst/alexandra-trackmap-panel/issues/18

I put this together in one issue, so users can google it and understand what happens. If you use these plugins, you should upgrade them from latest commit or wait until PRs in `grafana-plugin-repository` are merged.

**Comment by torkelo** [comment]
Sorry for this, it's tricky with the old angular system, we had no control over what internal angular services plugins used. variableSrv was never designed for or deliberately exposed to plugins (unlike templateSrv which is the way approved way to access variables).  

We will get the the plugin updates published asap
