### ISSUE TITLE
Always 3 hours shift

### ISSUE THREAD

**Issue by Jajalava** [grafana/grafana#26492]
**What happened**:
Relative time range is configured for a panel. But when there is an absolute range, always 3 hours shift is applied.

For example: I want to see http_requests_total graph for today on
I configure options like: query: sum(http_requests_total) , Relative time 0d/d, Time shift 0d/d:

It works fine, the query goes from today's date 00:00:00 to tomorrow's date 00:00:00:
![image](https://user-images.githubusercontent.com/42749454/88080256-832cdb80-cb87-11ea-932e-b85ab7980642.png)

BUT, when I zoom in (any absolute time range), the range always starts at 03:00:00:
![image](https://user-images.githubusercontent.com/42749454/88080455-c424f000-cb87-11ea-971f-2d70750db495.png)

![image](https://user-images.githubusercontent.com/42749454/88080623-fb939c80-cb87-11ea-8a2b-6256a9f5a966.png)

**What you expected to happen**:
I need a time series for this calendar day and correct info for absolute time range (or disable absolute time range at all)
Example, today is 21.07, when the relative time selected, time series goes from 21.07 00:00:00 to 22.07 00:00:00, when absolute time range is selected, time series interval changes respectively.

**Environment**:
- Grafana version: 7.1
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins: no
- Others:

**Comment by torkelo** [comment]
you timeshift value `0d/d` is not a valid time shift, cannot round the time shift amount (the /d part)

**Comment by Jajalava** [comment]
But I have the same issue with correct value (case from grafana portal) How do I get all data for yesterday in a correct way?
![image](https://user-images.githubusercontent.com/42749454/88104207-c8163980-cbaa-11ea-93ff-9b47bc30f1b1.png)

**Comment by torkelo** [comment]
Is there even data for that time slot? Can You use query inspector? Is the time range wrong in query? 

Do you have a custom timezone set?

**Comment by Jajalava** [comment]
Yes, so for example let's take http_requests_total with absolute time range.
There is data for the period:
![image](https://user-images.githubusercontent.com/42749454/88208826-74632900-cc5a-11ea-9b01-06c2d0393340.png)

Query url: "api/datasources/proxy/3/api/v1/query_range?query=sum(http_requests_total)&start=1595203200&end=1595289600&step=120"
![image](https://user-images.githubusercontent.com/42749454/88208958-a7a5b800-cc5a-11ea-9651-01c0426301d5.png)

As you can see that start in query is equal to 2020-07-20 03:00:00:
![image](https://user-images.githubusercontent.com/42749454/88209294-2dc1fe80-cc5b-11ea-951a-af253a4b6c72.png)


No custom time zone.

**Comment by Jajalava** [comment]
So, is there any way to show data for yesterday and also correctly show data for absolute time range?

**Comment by torkelo** [comment]
Not yet, but think there exists feature requests for that
