### ISSUE TITLE
Legend label formatting

### ISSUE THREAD

**Issue by appleciderjack** [grafana/grafana#26508]
**What would you like to be added**:
When printing out legend values in Prometheus data source, we often refer to {{ instance }} for cluster of machines.
However, in some environment, this can get really long, it would be nice if we are able to write 

{{ instance.split('.')[0] }} to get the prefix out.

I understand once upon a time, javascript expressions were allowed, but was later on removed, and users were encourage to use label_replace on PromQL itself, however, this can get pretty large for large dashboards.

I understand that this may be feature creeping toward supporting any expression or cause vulnerabilities, do let us know if there are ways to do it via deployment customization (using extra dashboard js functions predefined and only allow those function to be called)

**Why is this needed**:
For shops that only use prometheus for different groups of customers, inserting label_replace everywhere can make the PromQL query itself hard to read. It would be great if Grafana comes with its own strict set of DSL for Legend templates.

Thanks Grafana team!

**Comment by ivanahuckova** [comment]
@appleciderjack @Tomica-G  we plan is to introduce a Transform for regex renames. I am closing this issue in favour of https://github.com/grafana/grafana/issues/22360.
