### ISSUE TITLE
7.1 and Azure Monitor units are inconsistent

### ISSUE THREAD

**Issue by djryanj** [grafana/grafana#26502]
**What happened**:

After upgrade from 6.7.3 to 7.1, panels using Azure Monitor datasource (0.3.0), unit display is inconsistent when displaying data that uses Azure Monitor vs Log Analytics as the sub data source.

![image](https://user-images.githubusercontent.com/33379396/88110536-99c43a00-cb69-11ea-9a1f-f7fa5e3a7716.png)

Top panel is Log Analytics, bottom is Azure Monitor. Note that the 2 panels are not displaying the same metrics so ignore the inconsistency in the data.

Similarly, units that previously adjusted themselves automatically for range (e.g. Bytes -> KBytes -> MBytes etc.) are no longer doing so:

![image](https://user-images.githubusercontent.com/33379396/88110902-3981c800-cb6a-11ea-9897-b21024506f8f.png)

In addition, you cannot update/fix the axis label (#26497) on panels that existed prior to the upgrade.

Note that creating a new panel allows you to select the axis label properly and it will update regardless of sub-data source.

**What you expected to happen**:

Units should display consistently.

**How to reproduce it (as minimally and precisely as possible)**:

**Using Grafana 6.7**

1. Create panel displaying data from Azure Monitor datasource
2. Create panel displaying data from Azure Log Analytics datasource
3. Upgrade Grafana to 7.1

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.0 (8101355285)
- Data source type & version: Azure Monitor (v0.3.0)
- OS Grafana is installed on: Docker (Linux)
- User OS & Browser: Windows 10, Firefox 78.0.2 64-bit
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
@djryanj thanks for creating the issue. The [PR fixing this](https://github.com/grafana/grafana/pull/26429) was already merged and will be part of 7.1.1 release.
