### ISSUE TITLE
Cloudwatch data source: Show dimension keys for AWS/FSx

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#26505]
**What would you like to be added**:

dimension_keys(AWS/FSx) to work and show keys such as Filesystem ID

**Why is this needed**:
Will be able to see dimension_keys for FSx

**Comment by sunker** [comment]
Fixed in https://github.com/grafana/grafana/pull/26662

**Comment by sunker** [comment]
Fixed in https://github.com/grafana/grafana/pull/26662
