### ISSUE TITLE
Grafana-UI: missing css prop warning for Form elements

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#26512]
**What happened**:
After upgrading @grafana/ui to 7.1.x in a plugin the following Typescript error appeared:
```
Property 'css' is missing in type '{ value: string; placeholder: string; onChange: (event: ChangeEvent<HTMLInputElement>) => void; }' but required in type 'Pick<Props, "type" | "key" | "label" | "value" | "cite" | "data" | "form" | "slot" | "span" | "style" | "summary" | "title" | "pattern" | "children" | "prefix" | "suffix" | ... 347 more ... | "addonAfter">'.
```
Seems like this happens for UI elements using `Pick` to extend interfaces. 

Could be related to the latest Typescript upgrade as it didn't happen before. Also might be relevant: https://github.com/emotion-js/emotion/issues/1249.

**What you expected to happen**:
The error shouldn't show.

**How to reproduce it (as minimally and precisely as possible)**:
Use @grafana/ui 7.1.x in a plugin. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.x
- Typescript: 3.9.3

**Comment by Clarity-89** [comment]
Adding [this declaration](https://github.com/emotion-js/emotion/blob/master/packages/core/types/index.d.ts#L82) to index.d.ts seems to fix the issue.

**Comment by wz2b** [comment]
<Input> and &lt;Switch&gt; have this problem.  For some reason, &lt;Select&gt; does not.  (&lt;Select&gt; also doesn't accept ref={register})

**Comment by Clarity-89** [comment]
> Select> also doesn't accept ref={register}).


For Select you need to use `InputControl`, an example can be found in the [storybook](https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-example-forms--async-validation) under `controls` heading. It is a wrapper for react-hook-form [Control](https://react-hook-form.com/api/#Controller) component.

**Comment by daniellee** [comment]
Adding this import fixed it for me:

```ts
import {} from '@emotion/core';
```

Ref: https://github.com/emotion-js/emotion/issues/693#issuecomment-448088489

**Comment by DislayPS** [comment]
Following on this issue please. I'm trying to use Checkbox on Grafana 7.1.x and Typescript tells me it's missing a bunch of properties

**Comment by JorundMartinsen** [comment]
I'm getting this again, in 8.0.1


**How to reproduce it (as minimally and precisely as possible)**:

https://codesandbox.io/s/zealous-silence-x2drv

1. Create a new panel plugin using grafana toolkit.
```cmd
npx @grafana/toolkit plugin:create my-plugin
```
2. Update package.json dependencies 
```json  
"devDependencies": {
    "@grafana/data": "8.0.1",
    "@grafana/toolkit": "8.0.1",
    "@grafana/ui": "8.0.1",
    "emotion": "10.0.27"
  }
```
3. Update SimplePanel.tsx
```ts
import React from 'react';
import { PanelProps } from '@grafana/data';
import { SimpleOptions } from 'types';
import { Form, Input, TextArea } from '@grafana/ui';

interface Props extends PanelProps<SimpleOptions> {}

export const SimplePanel: React.FC<Props> = () => {
  return (
    <Form<any> onSubmit={() => {}}>
      {({ register }) => (
        <>
          <Input {...register('name')} />
          <TextArea {...register('comment')} />
        </>
      )}
    </Form>
  );
};
```
4. run `yarn; yarn build`
5. Output should be
```
  ERROR in C:/Users/joeru/source/repos/EcoMATE Cloud Plugins/Panel/my-plugin/src/SimplePanel.tsx
  ERROR in C:/Users/joeru/source/repos/EcoMATE Cloud Plugins/Panel/my-plugin/src/SimplePanel.tsx(14,12):
  TS2741: Property 'css' is missing in type '{ onChange: ChangeHandler; onBlur: ChangeHandler; ref: RefCallBack; name: string; }' but required in type 'Pick<Props, "onSubmit" | "accept" | "acceptCharset" | "action" | "allowFullScreen" | "allowTransparency" | "alt" | "as" | "async" | "autoComplete" | "autoFocus" | "autoPlay" | ... 347 more ... | "invalid">'.
```
