### ISSUE TITLE
Disabling query removes the wrong legent entry when using InfluxDB

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#2651]
Hello,

If you disable a query, it always removes the last entry in legend. Graph is ok. It only happens if backend is set to InfluxDB, it works under Graphite.

All metrics enabled:
![influxdb-remove-wrong-legend-01](https://cloud.githubusercontent.com/assets/4689252/9630168/a80a1fe6-5178-11e5-8222-2cfaa6b9aaf9.png)

1st metric disabled. Notice that the last record in legend gets removed:
![influxdb-remove-wrong-legend-02](https://cloud.githubusercontent.com/assets/4689252/9630175/b6c7f0da-5178-11e5-9c65-f08db30476d5.png)

Grafana version 2.1.3

Matej

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master
