### ISSUE TITLE
Ad-hoc filters with prometheus and (label_replace) regex doesn't work

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#26526]
**What happened**:
Similar to #14802.

Started off with this instant query in a table:
```
sum by (cluster, nodepool) (
    label_replace(
        kube_node_info,
        "nodepool", "$1", "node", "(.*-.{8})-.*"
    )
)
```
Selected "filter for value cluster=some-12345678-cluster" and Grafana produce the following (incorrect) query:
```
sum{cluster="some-12345678-cluster"} by (cluster, nodepool) (
    label_replace(
        kube_node_info,
        "nodepool", "$1", "node", "(.*-.{cluster="some-12345678-cluster"})-.*"
    )
)
```

**What you expected to happen**:
Produce this query:
```
sum{cluster="some-12345678-cluster"} by (cluster, nodepool) (
    label_replace(
        kube_node_info,
        "nodepool", "$1", "node", "(.*-.{8})-.*"
    )
)
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.2.0-e7b4c2b3pre (7417ff015d) (aka ops-tools)

**Comment by Duologic** [comment]
I think this feature could provide more flexibility to the user, top of my mind:

* turn off the query modification per panel
* provide a $filter.<column_name> variable, which the dashboard can use where it wants
* only filter out the current table on the front end, no querying

Also, are there docs somewhere that explain this feature?

**Comment by ivanahuckova** [comment]
@Duologic good point, I don't think this is documented anywhere. +cc @oddlittlebird

**Comment by oddlittlebird** [comment]
I'm not sure if you are talking about the regex thing or Prometheus ad hoc filters. If the latter, I literally merged [Add ad hoc filters](https://grafana.com/docs/grafana/latest/variables/add-ad-hoc-filters/) yesterday. Any improvements or examples you could ad would be much appreciated!

**Comment by Duologic** [comment]
> I'm not sure if you are talking about the regex thing or Prometheus ad hoc filters. 
The latter

> Any improvements or examples you could ad would be much appreciated!
I have only encountered this feature through the table panel, it was from [here](https://grafana.com/docs/grafana/latest/panels/visualizations/table-panel/#table-panel) I started looking for docs on the magnifier glass I clicked but didn't find it.

**Comment by itsmylife** [comment]
I think this is now working as it should be. 
I set the ad-hoc filter with `job`.
Used the following query:

```
sum by (instance) (
    label_replace(
        process_cpu_seconds_total,
        "instance_replaced", "$1", "instance", "(.*)"
    )
)
```

The query executed is:

```
sum by (instance) (
    label_replace(
        process_cpu_seconds_total{job="prometheus-random-data"},
        "instance_replaced", "$1", "instance", "(.*)"
    )
)
```

So it was correct and I am closing this issue.
