### ISSUE TITLE
v7.1.0 unable to load HTML, in text panel

### ISSUE THREAD

**Issue by navalchand** [grafana/grafana#26527]
**What happened**:
HTML page is not loading completely in v7.1.0, its just shows in text format. Tried all possible recommendations, v5.3.4 works fine.

**What you expected to happen**:
Expecting similar results to v5.3.4

**How to reproduce it (as minimally and precisely as possible)**:
Can use below HTML to reproduce the same

**Exp 1**: Works with v5.3.4
```
<iframe width="1530" height="450" frameborder="0" scrolling="no" src="https://s.tradingview.com/embed-widget/mini-symbol-overview/?locale=in#%7B%0A%20%20%22width%22%3A%20980%2C%0A%20%20%22height%22%3A%20610%2C%0A%20%20%22symbol%22%3A%20%22BINANCE%3ABTCUSDT%22%2C%0A%20%20%22interval%22%3A%20%225%22%2C%0A%20%20%22timezone%22%3A%20%22Etc%2FUTC%22%2C%0A%20%20%22theme%22%3A%20%22light%22%2C%0A%20%20%22style%22%3A%20%221%22%2C%0A%20%20%22locale%22%3A%20%22in%22%2C%0A%20%20%22toolbar_bg%22%3A%20%22%23f1f3f6%22%2C%0A%20%20%22enable_publishing%22%3A%20false%2C%0A%20%20%22allow_symbol_change%22%3A%20true%2C%0A%20%20%22studies%22%3A%20%5B%0A%20%20%20%20%22MASimple%40t-basicstudies%22%2C%0A%20%20%20%20%22MAWeighted%40tv-basicstudies%22%0A%20%20%5D%2C%0A%20%20%22container_id%22%3A%20%22tradingview_6aef4%22%0A%7D"></iframe>
```
**Exp 2**: Not able to load in both versions
```
<!-- TradingView Widget BEGIN -->
<div class="tradingview-widget-container">
  <div id="tradingview_48bd6"></div>
  <div class="tradingview-widget-copyright"><a href="https://in.tradingview.com/symbols/NASDAQ-AAPL/" rel="noopener" target="_blank"><span class="blue-text">AAPL Chart</span></a> by TradingView</div>
  <script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>
  <script type="text/javascript">
  new TradingView.widget(
  {
  "width": 980,
  "height": 610,
  "symbol": "NASDAQ:AAPL",
  "interval": "D",
  "timezone": "Etc/UTC",
  "theme": "light",
  "style": "1",
  "locale": "in",
  "toolbar_bg": "#f1f3f6",
  "enable_publishing": false,
  "allow_symbol_change": true,
  "container_id": "tradingview_48bd6"
}
  );
  </script>
</div>
<!-- TradingView Widget END -->
```

**Exp 3**: Works with v5.3.4
```
<iframe width="900" height="800" frameborder="0" scrolling="no" src="//plotly.com/~naval/9.embed"></iframe>
```

**Anything else we need to know?**:
The same works with HMTL [Plug in](https://grafana.com/grafana/plugins/aidanmountford-html-panel/installation), but unable to pass template variables. [Open issue](https://github.com/aidanmountford/aidanmountford-html-panel/issues/4)

**Environment**:
- Grafana version: v7.1.0
- Data source type & version: Postgresql
- OS Grafana is installed on: Raspbian
- User OS & Browser: Mac/Chrome and safari
- Grafana plugins: 
- Others:

**Comment by navalchand** [comment]
PS: Ref https://github.com/grafana/grafana/issues/14284

**Comment by jim-stroup** [comment]
This would be a huge help to us as well - Grafana's annotation hover-over feature renders HTML annotations, but the plug-in does not.

**Comment by Clarity-89** [comment]
Hi, thank you for submitting the issue. It has been fixed in https://github.com/grafana/grafana/pull/26413 and will be released in 7.1.1.

**Comment by navalchand** [comment]
Hey

Updated to v7.1.1, still its just shows as text. Tried above 3 cases.

**Comment by aknuds1** [comment]
@Clarity-89 Can you test if it's fixed in the 7.1.1 release? :point_up:

**Comment by Clarity-89** [comment]
Works for me with 7.1.1. @navalchand make sure to have `disable_sanitize_html = true` under `[panels]` in your custom config:
```
//custom.ini
[panels]
disable_sanitize_html = true
```
If you're using docker image via docker compose, you'll need to set `- GF_PANELS_DISABLE_SANITIZE_HTML=true` in the `environment` section.

**Comment by navalchand** [comment]
@Clarity-89 , thanks. Works now

**Comment by jim-stroup** [comment]
This works for me as well - thanks @aknuds1 !
