### ISSUE TITLE
grafana-cli lockfile

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#26522]
**What would you like to be added**:

a lock file where all installed plugins and there versions (or semantic versions) listed. So users can easily install all of them or upgrade only one. Especially this is useful in cloud where you run custom grafana image, e.g.
```
FROM grafana/grafana

COPY grafana-cli.conf grafana-cli.conf
RUN grafana-cli
```

**Why is this needed**:

grafana community grows pretty fast and there are a lot of third-party plugins already and updating all of them with `grafana-cli` becomes pretty hard. Users can automate this themself, but will be awesome if this feature will come as built-in solution.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
