### ISSUE TITLE
Docs feedback: /features/datasources/influxdb.md

### ISSUE THREAD

**Issue by jessegeens** [grafana/grafana#26521]
In the docs for adding an InfluxDB data source, only fields for InfluxQL are shown. It would be nice to also give an overview for the details of flux, the new query language.

**Comment by oddlittlebird** [comment]
I'm happy to update the docs, but I will need an SME to help create the content.

**Comment by wsromek** [comment]
Please have a look if this makes sense: https://github.com/grafana/grafana/pull/27045. Have a great day! :)

**Comment by ivanahuckova** [comment]
Closed in https://github.com/grafana/grafana/pull/27045
