### ISSUE TITLE
Graph component improvement

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#26523]
**Why is this component needed**:

Will be great if Graph component will allow to render points with info from data source. This is especially useful for tracing/logging and integrating this in one all-in-one-observability tool. Since logs and traces can not be presented as a timeline (line/area) they can be displayed as a separate points on board
___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
<img width="1343" alt="Снимок экрана 2020-07-22 в 16 04 21" src="https://user-images.githubusercontent.com/10380560/88180105-87173700-cc35-11ea-9a66-d8d906523cc7.png">

___
- [x] Post screenshots possible.
- [ ] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by torkelo** [comment]
We will add something like this soon with the coming exemplars and improved annotation support, to follow progress on new graph component  https://github.com/grafana/grafana/issues/27848
