### ISSUE TITLE
Legend showing randomly in some Gauge panels

### ISSUE THREAD

**Issue by Atomicbeast101** [grafana/grafana#26525]
**What happened**:
The v7.1.0 update has caused some Gauge panels to display legend when it previously hasn't. 

To give you an example, all 6 gauge panels don't have any legend defined, but the first two shows it anyways while the rest doesn't.
![](https://i.imgur.com/ffkwV8z.png)
Here's screenshots of the first two panels:
![](https://i.imgur.com/c0iqQ6G.png)
![](https://i.imgur.com/aQgLo4y.png)
The remaining panels looks like this (notice there's no legend listed, same as the two above):
![](https://i.imgur.com/jQzU4O5.png)

**What you expected to happen**:
No legend should be shown when no content is listed under "Legend" field in Edit Panel view.

**How to reproduce it (as minimally and precisely as possible)**:
Having multiple Gauge panels with similar metrics (or random in this case) and update the version from v7.X to v7.1.0.

**Anything else we need to know?**:
This wasn't the issue in versions below v7.1.0

**Environment**:
- Grafana version: v7.1.0
- Data source type & version: Prometheus v2.17.1
- OS Grafana is installed on: Ubuntu v20.04

**Comment by torkelo** [comment]
Can you include your panel json? (for the panel that shows the legend)

**Comment by Atomicbeast101** [comment]
Sure, here's the panel JSON for the first panel with legend showing:
```
{
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "percent",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 70
          },
          {
            "color": "red",
            "value": 90
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 5,
    "w": 4,
    "x": 0,
    "y": 18
  },
  "id": 11,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "showThresholdLabels": false,
    "showThresholdMarkers": true,
    "orientation": "auto"
  },
  "pluginVersion": "7.1.0",
  "targets": [
    {
      "expr": "100 * (vpnActiveSessions{site=\"XXXXX\",instance=\"X.X.X.X\"} / 10000)",
      "legendFormat": "",
      "refId": "A"
    }
  ],
  "title": "XXXXX (Group A) - # of Sessions",
  "type": "gauge",
  "timeFrom": null,
  "timeShift": null,
  "datasource": null
}
```
Here's another panel JSON for the non-legend one:
```
{
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "percent",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "#EAB839",
            "value": 70
          },
          {
            "color": "red",
            "value": 90
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 5,
    "w": 4,
    "x": 8,
    "y": 18
  },
  "id": 27,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "showThresholdLabels": false,
    "showThresholdMarkers": true,
    "orientation": "auto"
  },
  "pluginVersion": "7.1.0",
  "targets": [
    {
      "expr": "100 * (sum(vpnActiveSessions{site=\"XXXXX\"}) / 10000)",
      "refId": "A"
    }
  ],
  "title": "XXXXX - # of Sessions",
  "type": "gauge",
  "timeFrom": null,
  "timeShift": null,
  "datasource": null
}
```

**Comment by torkelo** [comment]
Can can you include the raw response? From query inspector and from the table in panel inspector

**Comment by Atomicbeast101** [comment]
Panel with legend:
```
{
  "request": {
    "url": "api/datasources/proxy/5/api/v1/query_range?query=100%20*%20(vpnActiveSessions%7Bsite%3D%22XXXXX%22%2Cinstance%3D%22X.X.X.X%22%7D%20%2F%2010000)&start=1594992600&end=1595597400&step=1800",
    "method": "GET"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "instance": "X.X.X.X",
            "job": "vpn",
            "mib": "vpn",
            "region": "NA",
            "site": "XXXXX"
          },
          "values": [
            (removed due to long list...)
          ]
        }
      ]
    }
  }
}
```

**Comment by hideaki-t** [comment]
Hi,

I have the same issue with node_exporter + Node Exporter Full dashboard.
it seems https://github.com/rfrail3/grafana-dashboards/issues/61 is related to this issue.

for temporary workaround, I changed the format of the affected panels from `Time series` to `Table`

**Comment by debian-d** [comment]
I figured out how to fix it. If you go to overrides under the editor on the right side, and then filter by field, then select "display name" for the override policy, it will blank it out since it will try to change the name to a blank value. This lets it to full screen.

**Comment by swiffer** [comment]
@torkelo - I'm still experiencing this after upgrading to 7.1.2.

**Comment by supasteev0** [comment]
@torkelo - Also still experiencing the same issue on v7.1.3 in a custom dashboard containing gauge panels with no legend configured. Happy to provide more information if needed.
