### ISSUE TITLE
Queries with indipendent data source

### ISSUE THREAD

**Issue by dstreppa** [grafana/grafana#2653]
I am using Grafana 2.1.3 and all the queries of a graph are related to the same data source. It should be useful to have an indipendent data source for each query.

**Comment by torkelo** [comment]
this will be one of the big new features in 2.2 , it is already implemented: 
https://github.com/grafana/grafana/issues/436#issuecomment-131497699

You can use 2.2 today,  pre release builds are here:
http://grafana.org/download/builds.html
