### ISSUE TITLE
Grafana 7.1 error to define Elasticsearch bucket script

### ISSUE THREAD

**Issue by cesarmacias** [grafana/grafana#26532]
Hi,

When create aggregation with bucket script, cant define the script only can define the variables, this problem appear since the update from 6.7 to 7.1

Grafana version: 7.1
Datasource: Elasticsearch 7.X
Panel: Table

**Comment by priyanshu-pirimid** [comment]
Yes, having the same issue, Team forgot or hid the Script. Can someone please let me know about this, if something has changed?

**Comment by ivanahuckova** [comment]
Thanks for creating an issue. I have created a PR  #26552 to fix this.
