### ISSUE TITLE
Enable rendering bars for different series side by side on Graph visualization

### ISSUE THREAD

**Issue by gilkgit** [grafana/grafana#26544]
I need something like this on the Graph visualization so I'd be able to layer it with other charts
![image](https://user-images.githubusercontent.com/55378597/88271431-cc903e80-ccdf-11ea-8be4-5d92e7ddab17.png)

I'll explain my scenario:
I'm trying to migrate our existing A/B testing charts from a different charting tool to Grafana.
Our current A/B testing error results charts display on the same chart both Percentages as line charts and Totals as bar for the two tests.
The percentage in the line chart is not stacked so you'd be able to see which is worse without hovering, and the Totals are not stacked either, otherwise it would cause confusion. On that other tool we can set the bar chart side by side for different A/B series.
I couldn't set the bars in Grafana's Graph visualization side-by-side, so currently they either hide one another or are stacked so you have to hover to see which is bigger.

**Comment by ivanahuckova** [comment]
@gilkgit there is actually already a [feature request](https://github.com/grafana/grafana/issues/870) for this.
