### ISSUE TITLE
No "back to dashboard" text when sidebar is opened

### ISSUE THREAD

**Issue by matejzero** [grafana/grafana#2654]
I noticed today, that when I'm viewing a graph (click on the graph title in dashboard -> View), that there is no 'Back to dashboard' button when sidebar is opened. Later today, 2 more co-workers stopped by my office and told me they also noticed the bug.

Sidebar shown:
![back-to-dashboard-01](https://cloud.githubusercontent.com/assets/4689252/9631756/5c7f70fc-5183-11e5-9502-b9ff0462bda9.png)

Sidebar hidden:
![back-to-dashboard-02](https://cloud.githubusercontent.com/assets/4689252/9631760/614fc186-5183-11e5-8be4-8028616b0cdf.png)

Matej

**Comment by torkelo** [comment]
this is by design, the sidebar is open there is not enough room for the back to dashboard link

**Comment by torkelo** [comment]
(in some cases)

**Comment by matejzero** [comment]
Aaa, ok. I guess I didn't think of people with less than 1080p resolution.
Thanks for clarifying.
