### ISSUE TITLE
Connexion error when adding datasource type influxdb (flux)

### ISSUE THREAD

**Issue by wuillg** [grafana/grafana#26541]
**What happened**:

![image](https://user-images.githubusercontent.com/67151448/88259091-e6bb2400-ccc1-11ea-9cdd-04973935509e.png)

Post "http://localhost:9999/api/v2/query?org=my-org": dial tcp 127.0.0.1:9999: connect: connection refused

**What you expected to happen**:

Successful connection to influxdb from grafana
I try my query on postman and via curl and anything work.

- Data source type & version:
Influxdb Version 2.0.0 (86796dd)
- OS Grafana is installed on:
Docker:  docker run -d --name=grafana -p 3000:3000 grafana/grafana:7.1.0
- User OS & Browser:
Chrome

**Comment by poldown** [comment]
The URL should just be "http://localhost:9999", without the path...

**Comment by wuillg** [comment]
Update: 
I tried both http://localhost:9999 and http://localhost:9999/api/v2

**Comment by ivanahuckova** [comment]
Hello @wuillg, I wasn't able to reproduce this issue. Setting up Influxdb v2 data source with Grafana worked for me. 

Could you please share the logs from Grafana with us. Also, could you please you try to run query and see if it returns any results (even though the data source throws `Error reading InfluxDB`)?

**Comment by wuillg** [comment]
Hello,

here the log from grafana

`Post "http://localhost:9999/api/v2/query?org=my-org": dial tcp 127.0.0.1:9999: connect: connection refused`

And the flux query I tried to run:

`from(bucket:"goflex")
        |> range(start: 2020-01-01T00:00:00Z, stop:2020-01-01T00:30:00Z)
        |> filter(fn: (r) => r._measurement == "house_data")
        |> aggregateWindow(every: 1h, fn: mean)`

I did exactly the same from Postman and it is working. I don't understand...

I have installed influxdb and grafana via docker...

Thank you for your help

**Comment by ivanahuckova** [comment]
As you are using Docker containers for your setup, you need to be aware how the networking stack works with Docker. You can find more information [here](https://community.influxdata.com/t/cannot-connect-to-influx-datasource-from-grafana/8048). There are also a bunch of step-by-step guides. Also, for questions, it is the best to ask at [grafana community site](https://community.grafana.com/).
