### ISSUE TITLE
Can`t change refresh type in variables via API

### ISSUE THREAD

**Issue by nkondratyk** [grafana/grafana#26542]
**What happened**:
I am using the service which is generating Grafana dashboard JSON and push it to Grafana API. When I am generating variables - it doesn`t apply changes in UI. More details you can find in section - How to reproduce it 

**What you expected to happen**:
When I specified "refresh": 2 in json object - variable refresh should be "on time range change"

**How to reproduce it (as minimally and precisely as possible)**:
Here is the section which describes JSON object of one variable:
`
{
  "allValue": null,
  "current": {
    "selected": false,
    "text": "All",
    "value": "$__all"
  },
  "datasource": "Prometheus",
  "definition": "",
  "hide": 0,
  "includeAll": true,
  "index": -1,
  "label": "pod",
  "multi": true,
  "name": "pod",
  "options": [],
  "query": "label_values(up{service=\"prometheus\"}, pod)",
  "refresh": 1,
  "regex": "/.*/",
  "skipUrlSync": false,
  "sort": 0,
  "tagValuesQuery": null,
  "tags": [],
  "tagsQuery": null,
  "type": "query",
  "useTags": false
}
`
If key "refresh" is 1 - variable refresh should be "on dashboard load" and it works via API
![image](https://user-images.githubusercontent.com/34338539/88270103-cbf6a880-ccdd-11ea-9edc-13e391315a36.png)

If key "refresh" is 2 - variable refresh should be "on time range change" and it doesn`t work, I still see "on dashboard load" 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.3
- Data source type & version: Prometheus 2.17
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Google Chrome Version 84.0.4147.89
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
Unable to replicate this, if I change it to 2 and reload the dashboard I get the correct value in the dropdown
<img width="747" alt="Screen Shot 2020-07-24 at 08 09 25" src="https://user-images.githubusercontent.com/10999/88365049-20089800-cd85-11ea-83c0-0095db77586b.png">

@ivanahuckova could you replicate this?
