### ISSUE TITLE
Cloudwatch Datasource - MS Teams Alerting - Allow the use of variables in the alert message

### ISSUE THREAD

**Issue by waqark3389** [grafana/grafana#26557]
**What would you like to be added**:

See screenshot for clarity below. We should be able to specify a variable inside the message bit of the alert. If you have lots of series that are returned then it is not clear which one fired the alert without going into Grafana. 

![image](https://user-images.githubusercontent.com/12910496/88321027-6d015580-cd16-11ea-9698-f8c3adce8978.png)

**Why is this needed**:

See above

**Comment by ivanahuckova** [comment]
@waqark3389, there is already a feature request for this #7121.
