### ISSUE TITLE
Annotations List Panel Doesn't Render HTML Annotations

### ISSUE THREAD

**Issue by jim-stroup** [grafana/grafana#26550]
**What happened**:
The Annotations List Panel does not render HTML formatted annotations.

**What you expected to happen**:
I expect the text to be HTML formatted (e.g. permit hyperlinks, thumbnails, etc.) 

**How to reproduce it (as minimally and precisely as possible)**:
Insert a simple HTML formatted annotation via Grafana's HTTP API for annotations. Then try to view that same annotation in Grafana's Annotation List panel.

**Anything else we need to know?**:
See screenshots for reference.

![annotations_issue_2](https://user-images.githubusercontent.com/64607347/88289075-b1630600-ccc2-11ea-91ab-1da1fda7a7e3.jpg)

![annotations_issue](https://user-images.githubusercontent.com/64607347/88289053-aa3bf800-ccc2-11ea-8e6d-3b5b8f933708.jpg)

**Environment**:
- Grafana version:  v7.1
- Data source type & version:  N/A
- OS Grafana is installed on:  Ubuntu 18.04.4 LTS
- User OS & Browser:  Windows 10/Edge Chromium
- Grafana plugins:  Annotation List Panel
- Others: N/A

**Comment by torkelo** [comment]
This is a community panel , and is no longer supported https://github.com/ryantxu/annotations-panel

**Comment by Nowaker** [comment]
@jim-stroup How do you even enable HTML on annotations themselves? I can see you have links in your annotations but all I can get is this junk:

![image](https://user-images.githubusercontent.com/611746/117043100-673b9600-acd2-11eb-9403-fdc6d9a54718.png)

**Comment by nikolaev-rd** [comment]
@torkelo Can your reopen this issue? Because now [Annotations List Panel — Native Plugin](https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/annolist), and issue still exist.
