### ISSUE TITLE
missing ValueMappingsEditor and ThresholdsEditor export 

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#26554]
**What happened**:

in `@grafana/ui@6.7` there is export ValueMappingsEditor and ThresholdsEditor  from `@grafana/ui/components`. in `@grafana/ui@7` this exports are missing.
I have checked that code exists in bundle `7.0.x` and `7.1.0`, but exports is missing.

**What you expected to happen**:

export ValueMappingsEditor and ThresholdsEditor

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Will be pleased if storybook will be plugin developers friendly and ccomponents will be exports starting from `@grafana/ui` specifier.
<img width="1174" alt="Снимок экрана 2020-07-23 в 20 27 28" src="https://user-images.githubusercontent.com/10380560/88318148-fcad0100-cd22-11ea-9224-1dea86da2699.png">

This actually solves problem above since story will not work as expected (export is missing)

Tip: enhance webpack storybook config with
```
{
    resolve: {
            alias: {
                  "@grafana/ui": path.resolve(__dirname, "<relative path to grafana-ui dir>")
            }
    }
}
```

with webpack@5 you could define [`exports` field](https://github.com/webpack/webpack/pull/10953) and use self-referencing by default 

**Environment**:
- Grafana version: 7
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vankop** [comment]
I will send a fix..

**Comment by torkelo** [comment]
These are not designed to be used directly but via the field config system. 

```
export const plugin = new PanelPlugin<StatPanelOptions>(StatPanel)
  .useFieldConfig()
```

useFieldConfig allows you to add thresholds (part of standard field config options). same with value mappings 

You can also add custom thresholds as part of panel options

**Comment by CrashLaker** [comment]
Hi all.

So how can I solve this?
I just got here from starting out a new project [here](https://grafana.com/tutorials/build-a-panel-plugin/#3).
`npx @grafana/toolkit plugin:create my-plugin`

which gave me `package.json`
```
"@grafana/data": "^7.0.0",
"@grafana/toolkit": "^7.0.0",
"@grafana/ui": "^7.0.0",
```

error:
Missing ThresholdsEditor ThresholdsEditorNew
