### ISSUE TITLE
time range dialog throws "Error: Invalid date: Invalid Date" when clicking "To" when "From" is empty starting Grafana 7.0.0

### ISSUE THREAD

**Issue by arno01** [grafana/grafana#26553]
Time range dialog throws "Error: Invalid date: Invalid Date" when clicking "To" when "From" is empty starting Grafana 7.0.0

Grafana: 7.1.0

![image](https://user-images.githubusercontent.com/3791945/88302903-b184f500-cd06-11ea-85a8-2fdf10ef6d97.png)

To reproduce:

Empty the "From" and click to "To" or anywhere else.

![image](https://user-images.githubusercontent.com/3791945/88302979-c8c3e280-cd06-11ea-997a-8f331f58bfe0.png)

**Comment by ivanahuckova** [comment]
Yes, I could reproduce this on grafana.play as well. 
![image](https://user-images.githubusercontent.com/30407135/88304713-e6924700-cd08-11ea-830d-510d6ff0fbeb.png)
