### ISSUE TITLE
I don't see how to format large numbers with commas in v7.0.5

### ISSUE THREAD

**Issue by EngineeringGirl** [grafana/grafana#26566]
Ah-low, 
I was wondering where or when this feature will be added and if so where is it placed? The issue was brought up in June 2017,  by golly you think it would be easy to spot the feature for formatting large numbers but it is not. 
Reference:
https://community.grafana.com/t/format-large-numbers-with-commas/1213
https://community.grafana.com/t/how-to-format-single-stat-panel-to-add-comma-separators/6035 and much more
Please direct me to the settings or feature in v7.0.5 of grafana for formatting large numbers with commas, thank ye gents. 

Environment:
Grafana version: Grafana v7.0.5 
Data source type: Influx
OS Grafana is installed on: Windows 10
User OS & Browser: Windows 10/ chrome
Grafana plugins: none, only Table panel for now

**Comment by torkelo** [comment]
The locale format seems to do the job 

<img width="1081" alt="Screen Shot 2020-07-24 at 07 24 11" src="https://user-images.githubusercontent.com/10999/88363026-d9b03a80-cd7e-11ea-90fc-7f5c9ac746a9.png">
