### ISSUE TITLE
"Display" menu item of editing panel sidebar (and other items) are not shown if chart is not visible

### ISSUE THREAD

**Issue by antergen** [grafana/grafana#26568]
**What happened**:
Items of sidebar are not shown while chart is not visible

**What you expected to happen**:
all available items of sidebar are shown while editing the panel

**How to reproduce it (as minimally and precisely as possible)**:
get a small display (or increase a scale) and make chart "hidden" when you enter the editing mode of the panel

**Anything else we need to know?**:
![1](https://user-images.githubusercontent.com/11833838/88364046-7fb57200-cd8a-11ea-8569-1ca028b381c9.jpg)
![2](https://user-images.githubusercontent.com/11833838/88364044-7e844500-cd8a-11ea-9611-15e458dbac6d.jpg)
**Environment**:
- Grafana version:  v7.0.4 (c4d8d0c2ae)
- Data source type & version:   
- OS Grafana is installed on:
- User OS & Browser:  Win, chrome, Mac, Safari
- Grafana plugins:
- Others:

**Comment by Yogendra0Sharma** [comment]
Hi @antergen  can I take this issue?

**Comment by torkelo** [comment]
There is no way to fix this currently, it only happens for angular panels. We have a check where we do not render panels with no width or height dimensions. we need this check for other reasons. 

And for old angular panels the side bar is populated by the angular panel loading, it's not a problem for our new react based panels
