### ISSUE TITLE
Is it possible to show all the values of an interval with a scroll or something like that?

### ISSUE THREAD

**Issue by mbarragan** [grafana/grafana#2656]
I have too many values in an interval that not all of them are shown. Below you can find an example:

![screenshot](https://cloud.githubusercontent.com/assets/9413404/9633401/04cf88c4-518d-11e5-8456-15a4ed87bb91.png)

Is there any option in order to show all the values?

**Comment by torkelo** [comment]
no, this is currently not possible.
