### ISSUE TITLE
Unable to add Graph from dashboard if use InfluxDB v0.9

### ISSUE THREAD

**Issue by aaich** [grafana/grafana#2657]
Hi,

If I select my data source as InfluxDB v0.9, I am not being able to add Graph to my dashboard. In console I can see a "Metric measurement is missing" error.

I am new to Grafana, and I have installed following http://docs.grafana.org/project/building_from_source/

Any help would be appreciated. 

<img width="896" alt="screen shot 2015-09-02 at 10 34 24 am" src="https://cloud.githubusercontent.com/assets/14094052/9634110/3f14082c-515e-11e5-9002-0e76b7540ca8.png">

**Comment by torkelo** [comment]
you need to open the panel in edit mode and specify a metric query (you click the panel title to open panel menu)

https://www.youtube.com/watch?list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2&v=sKNZMtoSHN4

**Comment by aaich** [comment]
Thank you for your response. I think I found the issue, if we have only one default data source and that is Influx 0.9, then if we try to create a new Dashboard, and add Graph, then this "Metric measurement is missing" error comes. 

The way I resolved - I removed the default flag from the InfluxDB, then I created the Graph and edited, and selected InfluxDB as data source, and created the metrics.
