### ISSUE TITLE
Can not login to grafana 7.1.0 from Firefox 

### ISSUE THREAD

**Issue by TomasVojacek** [grafana/grafana#26575]
**What happened**:
Can not login to grafana from firefox.
Grafana log shows:
t=2020-07-24T08:06:01+0000 lvl=info msg="Successful Login" logger=http.server User=xxxx@example.com
t=2020-07-24T08:06:02+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
t=2020-07-24T08:06:02+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=172.21.0.2 time_ms=0 size=37 referer=https://myurl.example.com/grafana/login
t=2020-07-24T08:06:02+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="user token not found"
**What you expected to happen**:
Login to grafana.
**How to reproduce it (as minimally and precisely as possible)**:
install grafana from docker
image:grafana/grafana:latest
(grafana/grafana:7.1.0)
Try login from firefox as admin.
**Anything else we need to know?**:

- downgrade to image version grafana/grafana:7.0.6 resolved problem
- adblock and extended tracking protection was disabled but problem was not resolved.
- Bug is not present in Chrome

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: timescaledb
- OS Grafana is installed on: Linux docker
- User OS & Browser: Firefox 87
- Grafana plugins: N/A
- Others:

**Comment by ivanahuckova** [comment]
Hello @TomasVojacek, this might be possible duplicate of https://github.com/grafana/grafana/issues/25444. [Clearing the cookies should resolve the problem](https://grafana.com/docs/grafana/latest/installation/upgrading/#cookie-path).

**Comment by TomasVojacek** [comment]
> Hello @TomasVojacek, this might be possible duplicate of #25444. [Clearing the cookies should resolve the problem](https://grafana.com/docs/grafana/latest/installation/upgrading/#cookie-path).

Clearing cookies resolved problem.

**Comment by ivanahuckova** [comment]
awesome!
