### ISSUE TITLE
Bucket Selector in group by 

### ISSUE THREAD

**Issue by priyanshu-pirimid** [grafana/grafana#26576]
Hey, I think there is a need for bucket selector query in grafana because many of the times we need to filter the data that comes from aggregation. I am currently facing an issue regarding this, Or if the feature is there and I don't know, please let me know about it.

I am filtering the data based on unique_count. I only want to  display data if it is greater than 2(let's say)

**Comment by ivanahuckova** [comment]
@priyanshu-pirimid if you would like a new feature to be added, please follow the [Enhancement request template](https://github.com/grafana/grafana/issues/new?labels=type%3A+feature+request&template=2-feature_request.md). If you have a question, [community site](https://community.grafana.com/) is the best place to ask. 🙂
