### ISSUE TITLE
Format multiline strings in json explorer

### ISSUE THREAD

**Issue by massiung** [grafana/grafana#26584]
**What would you like to be added**:
When a json element contains newline characters, the json explorer currently collapses them in the UI, though the newlines are only visible in the source code by using dev tools in the browser. I would like to see those newlines in the UI.

**Why is this needed**:
One example where this would be very helpful is when using the Query inspector. Currently, when I run a query and want to see what the exact request to the datasource was, I am forced to open dev tools (see images below).

<img width="805" alt="Screenshot 2020-07-24 at 14 26 47" src="https://user-images.githubusercontent.com/20955674/88391258-1ea59280-cdba-11ea-886c-282079e9839c.png">
<img width="347" alt="Screenshot 2020-07-24 at 14 27 38" src="https://user-images.githubusercontent.com/20955674/88391265-22d1b000-cdba-11ea-8d87-c55a03ec9ceb.png">

**Comment by torkelo** [comment]
Can you open PR with your fix?
