### ISSUE TITLE
increase() in grafana display incorrect values: how to avoid?

### ISSUE THREAD

**Issue by wangjinhe** [grafana/grafana#26599]
We are using increase() in Graph range selector dashboards to query number of changes in timerange. 

But  using increase()  in grafana display incorrect values.

Original query:

increase(http_server_requests_seconds_count{application="service-order",exception="None",method="GET",status="200",uri="/v0/order/{tenant_id}/count",}[1m])

in Prometheus  is right:

![1](https://user-images.githubusercontent.com/12496272/88451985-aad4ba00-ce8d-11ea-9245-4ea3d365ca8a.png)

in grafana is error:

![2](https://user-images.githubusercontent.com/12496272/88451979-9c869e00-ce8d-11ea-8d13-d8fed58a2ad2.png)

Environment:

Grafana version: 6.3.2
Prometheus version: 2.11.1
Data source type & version: Prometheus
OS Grafana is installed on:  Linux
User OS & Browser: Chrome
Grafana plugins:
Others:

**Comment by torkelo** [comment]
Prometheus table shows the result of an instant query, if you need the same change to table and instant switch in query editor.

The legend in the graph the max is calculated based on what the Prometheus range query returns, you can use the query inspector to see the raw values Prometheus returns
