### ISSUE TITLE
Enhance InfluxDB query support

### ISSUE THREAD

**Issue by lexh** [grafana/grafana#2659]
There are at least two features of the InfluxDB query language which are not supported by Grafana. 

- Regex negation https://github.com/influxdb/influxdb/issues/3160: `SELECT * FROM some_measurement WHERE host_name !~ /grafana\.org/`
- Complex WHERE clauses: `SELECT * from some_measurement WHERE time > now() - 1h AND (foo='bar' OR baz='quux')`

The first one seems simple enough to implement, the second might require a bit more effort. Also, it occurs to me that the first case could be avoided by rewriting the regex to include the negation, but this wouldn't really work for template variables.

**Comment by torkelo** [comment]
the first one is already implemented in master, the second one is more complex, you could as well just duplicate the query and specify another where condition?

**Comment by lexh** [comment]
Yes, you are right. The difference is that doing it in a single query would yield a single series for Grafana to plot, where as what you've suggest is just plotting two series on the same graph, unless I'm misunderstanding.

`select * from some_measurement where key1='value1' and (key2='value2' OR key2='value3')` gives all results from `some_measurement` matching the `WHERE` clause as a single result set. Making two queries would give two result sets.

**Comment by torkelo** [comment]
true, but you could do, `select * from some_measurement where key1='value1' and key2=~/value2|value3&/`

And then you have the rawQuery option also

**Comment by lexh** [comment]
Good call. That had not occurred to me.
