### ISSUE TITLE
Graph: Field data links are deleted after upgrade from 7.1 to 7.1.1

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#26592]
**What happened**: All Field data links in dashboard are deleted after upgrade from 7.1 to 7.1.1

**What you expected to happen**: Not deleting data lionks.

**How to reproduce it (as minimally and precisely as possible)**: On 7.1 add Field data links and upgrade to 7.1.1

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: Elasticsearch 7.8
- OS Grafana is installed on: Windows 2016 Server
- User OS & Browser: Windows 10 2004, Chrome 84

I am sure that it happend because in the morning I was presenting by Grafana dashboard and data links worked great on version 7.1. In the afternoon I upgraded version to 7.1.1 and all Field data links disappeared. Probably adding units to Field settings is the problem.

**Comment by torkelo** [comment]
Unable to replicate this, here is an old dashboard (build a few months ago) with data links still intact: https://play.grafana.org/d/uptmjHzGk/data-links-cell-value-datalink?orgId=1 

Can you include your panel json?

**Comment by GrzegorzLyp** [comment]
The below version is unfortunately fixed since the users need to use it. I don't have version from the moment of the problem.

`{
  "aliasColors": {},
  "bars": true,
  "dashLength": 10,
  "datasource": "Elasticsearch-2",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "links": [
        {
          "title": "Details",
          "url": "d/mVpt78MGk/dpa-2-0-beta-statement?orgId=1&var-queryhash=${__series.name}﻿&var-dpaname=﻿${dpaname}&﻿${__url_time_range}"
        }
      ]
    },
    "overrides": []
  },
  "fill": 1,
  "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "legend": {
    "alignAsTable": true,
    "avg": false,
    "current": false,
    "hideEmpty": true,
    "hideZero": true,
    "max": false,
    "min": false,
    "rightSide": true,
    "show": true,
    "sideWidth": null,
    "sort": "total",
    "sortDesc": true,
    "total": true,
    "values": true
  },
  "linewidth": 1,
  "nullPointMode": "null as zero",
  "pluginVersion": "7.1.1",
  "pointradius": 2,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": true,
  "targets": [
    {
      "bucketAggs": [
        {
          "$$hashKey": "object:100",
          "fake": true,
          "field": "stmt",
          "id": "5",
          "settings": {
            "min_doc_count": "1",
            "order": "desc",
            "orderBy": "1",
            "size": "0"
          },
          "type": "terms"
        },
        {
          "$$hashKey": "object:3244",
          "fake": true,
          "field": "queryhash",
          "id": "4",
          "settings": {
            "min_doc_count": 1,
            "missing": null,
            "order": "desc",
            "orderBy": "1",
            "size": "0"
          },
          "type": "terms"
        },
        {
          "$$hashKey": "object:1932",
          "fake": true,
          "field": "mdate",
          "id": "3",
          "settings": {
            "interval": "$timeinterval",
            "min_doc_count": "0",
            "trimEdges": 0
          },
          "type": "date_histogram"
        }
      ],
      "metrics": [
        {
          "$$hashKey": "object:1914",
          "field": "value",
          "id": "1",
          "meta": {},
          "settings": {
            "missing": null
          },
          "type": "sum"
        }
      ],
      "query": "dpa: $dpaname AND waittype: $waittype AND username: $username AND hostname: $hostname AND programname: $programname",
      "refId": "A",
      "timeField": "mdate"
    }
  ],
  "thresholds": [],
  "timeRegions": [],
  "title": "Zapytania",
  "tooltip": {
    "shared": false,
    "sort": 1,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "$$hashKey": "object:2017",
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "$$hashKey": "object:2018",
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  },
  "dashes": false,
  "description": "",
  "fillGradient": 0,
  "hiddenSeries": false,
  "interval": "",
  "lines": false,
  "percentage": false,
  "points": false,
  "steppedLine": false,
  "timeFrom": null,
  "timeShift": null
}`

**Comment by torkelo** [comment]
You need to get json with data links that after dashboard load disappear

**Comment by ryantxu** [comment]
@GrzegorzLyp was this fixed, or you just can't reproduce?

**Comment by GrzegorzLyp** [comment]
I can't get json definitions from the moment of problem. Because my solutions becomes production one, we will introduce version options, so next time similar problem appear I will be able to give more details. For now I am building custom extensions with ReactJS and new extensions building tools, so I won't install new versions for some time. Thanks for Your support.

**Comment by GrzegorzLyp** [comment]
The situation happen again with 7.1.5 upgrade from 7.1.1.
I attach the JSON Model of dashboard after upgrade. Every graph on this dashboard except to last one should have at least one data link named "Filter" to set the dashboard variable. They all disappeared.


[Dashboard.zip](https://github.com/grafana/grafana/files/5144463/Dashboard.zip)

**Comment by torkelo** [comment]
Bug fix here: https://github.com/grafana/grafana/pull/27295

Thanks for providing all the extra info and reporting this!
