### ISSUE TITLE
Alias Pattern issue with influxdb 0.9.3

### ISSUE THREAD

**Issue by Midori-ch** [grafana/grafana#2660]
Hi,
After upgrade influxdb 0.9.2 to 0.9.3 that I found alias pattern 
$tag not working (But $m and $col is ok). 
Is there any setting that I need to change when db upgrade?
![alias](https://cloud.githubusercontent.com/assets/11845196/9650160/955e059c-5231-11e5-84de-243401dfe75c.png)

**Comment by torkelo** [comment]
what does influxdb return? (open chrome dev tools)

**Comment by Midori-ch** [comment]
Hi torkelo,
FYI,
![alias](https://cloud.githubusercontent.com/assets/11845196/9651852/334d202e-5248-11e5-8c0a-1f1aad0ba375.png)

**Comment by torkelo** [comment]
Cant replicate this. I test with v2.1.3 and master and `$tag_<tagname>` works fine with InfluxDB 0.9.3

![image](https://cloud.githubusercontent.com/assets/10999/9668127/0af14c12-5280-11e5-9fc5-28c2c639c8b5.png)

Are you sure you have grouped by the instance tag?

**Comment by Midori-ch** [comment]
Hi torkelo,
Thanks for your effort. It's works fine when influxdb not upgrade.
The incident only happen with $tag_<keywords>.  Maybe something I missed. 
Thank you again.
$tag
![i](https://cloud.githubusercontent.com/assets/11845196/9674889/e5add11e-52e8-11e5-9c00-59711ad990d4.png)

$col
![ok](https://cloud.githubusercontent.com/assets/11845196/9674906/32eb7a08-52e9-11e5-9b89-37f3432bf088.png)

**Comment by torkelo** [comment]
I don't see a group by in your query

**Comment by Midori-ch** [comment]
Hi, torkelo
I'm confused. Because I don't need group by in influxdb 0.9.2.
![old](https://cloud.githubusercontent.com/assets/11845196/9678502/a34a3c56-5318-11e5-8841-803f7bf97ead.png)

**Comment by torkelo** [comment]
@Midori-ch must have been a bug in InfluxDB 0.9.2  or you are confusing fields with tags. 

Tags are not returned unless you group by the tag (if you do not group by a tag, the series will be merged to single series). 

From your influxdb response screenshot it looks like instance is NOT a tag but a field.

**Comment by Midori-ch** [comment]
Hi torkelo, 
After added group by in metrics. It's works ! Thank you so much !!!!
