### ISSUE TITLE
There is a lot of data in the dropdown box. Compared with the old version, the new version shows much slower speed

### ISSUE THREAD

**Issue by zhukaiqiang** [grafana/grafana#26609]
![企业微信截图_2ebb429c-2762-4f37-a599-594072be6691](https://user-images.githubusercontent.com/20986844/88500727-18065d80-cffc-11ea-8fd1-d997d57c2a63.png)

There is a lot of data in the dropdown box. Compared with the old version, the new version shows much slower speed

**Comment by torkelo** [comment]
Ok, we will add virtualized rendering to improve speed. But it's showing the same result as before, and faster in our testing

**Comment by torkelo** [comment]
Just out of curiosity how many items do you have in the list? Tested with 10K and works pretty well

**Comment by holooooo** [comment]
I got 1200 item in select.When I click select, page will get stuck completely 😢
