### ISSUE TITLE
Filters floating at the top of the page when scrolling the dashboard

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#26605]
**What would you like to be added**:
An option to leave filters floating at the top of the page when scrolling the dashboard.

**Why is this needed**:
If a user is looking at a large dashboard with a lot of panels and wants to change the filter value in the middle of the page, the page has to be scrolled back to the top. Leaving a filters list floating at the top of the page while scrolling would make this change much more convenient.

**Comment by torkelo** [comment]
Dupe of https://github.com/grafana/grafana/issues/11166
