### ISSUE TITLE
Latest build of grafan - not working on IOS device

### ISSUE THREAD

**Issue by peterd550** [grafana/grafana#26602]
**What happened**:
Latest build of grafana - not working on IOS device - only have of the dashboard works

**What you expected to happen**:
Latest build of grafan - to working on IOS device
only half the dash board page is rendering
**How to reproduce it (as minimally and precisely as possible)**:
install the latest grafana and premethous
**Anything else we need to know?**:
The dash board working in Windows 10. latest browsers
**Environment**:
- Grafana version: latest
- Data source type & version: latest
- OS Grafana is installed on: riparian
- User OS & Browser: IOS 13 firefox chrome and safari
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed in 7.1.1 most likely but would help if you included version you are using
