### ISSUE TITLE
Table Panel converts string like "32E11" to number

### ISSUE THREAD

**Issue by negbie** [grafana/grafana#26606]
Table Panel converts string like "32E11" to number like you can see in the screenshot:

![table_num](https://user-images.githubusercontent.com/20154956/88477995-f1392000-cf44-11ea-8aa6-def850f30e7f.png)

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: Clickhouse (latest)
- OS Grafana is installed on: Debian (buster)
- User OS & Browser: Chrome (latest)

**Comment by negbie** [comment]
Could it be that the Clickhouse Datasource causes this?

**Comment by negbie** [comment]
Ok it can be reproduced with Postgresql datasource aswell. See screenshot below
![table_num_pg](https://user-images.githubusercontent.com/20154956/88520699-38321e80-cff4-11ea-90e1-f1ff1960e4f7.png)

**Comment by negbie** [comment]
Please notice that string +4912345 will be shown in table panel as 4912345. If I should open a seperate issue for that please tell me.

**Comment by torkelo** [comment]
My guess is that something is wrong here https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/dataframe/processDataFrame.ts#L204 

If anyone wants to help investigate & fix please do :)

**Comment by negbie** [comment]
As a temporary fix someone can create a Cell display mode override and use JSON view.
