### ISSUE TITLE
HTTP redirect to HTTPS when SSL enabled?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2661]
Should Grafana redirect to https, if a user attempts to access the server using http, when SSL is enabled?

**Comment by torkelo** [comment]
no, since it will only be listening on http, if you want redirect, nginx can do that very easily

**Comment by torkelo** [comment]
sorry, meant https

**Comment by moizmmz** [comment]
I'm trying to redirect HTTP traffic through HTTPS, but I'm facing a few problems. For me, Grafana runs on two ecs instances, and although I can locate the nginx.conf file on them, I can't find the grafana.ini file. But Grafana seems to be working perfectly. Second, on following the code given on the Grafana website (https://grafana.com/docs/installation/behind_proxy/), redirect doesn't work.
