### ISSUE TITLE
InfluxDB: v2 Cuts off right side graph lines when datapoints exceed maxDataPoints, need to show warning that maxDataPoints exceeded 

### ISSUE THREAD

**Issue by fixator10** [grafana/grafana#26625]
**What happened**:

Grafana incorrectly guesses query options for non-fullwidth panels (InfluxDBv2), and fills not entire panel

**What you expected to happen**:

Grafana fills entire panel

**How to reproduce it (as minimally and precisely as possible)**:

1. Add panel that takes info from InfluxDBv2
2. Set time range to 24h or more
3. Save dashboard and reload page

**Environment**:
- Grafana version: Grafana v7.1.1 (3039f9c3bd)
- Data source type & version: InfluxDBv2 beta14 Version 2.0.0 (f54848f)
- OS Grafana is installed on: 
```
NAME="Arch Linux"
PRETTY_NAME="Arch Linux"
ID=arch
BUILD_ID=rolling
ANSI_COLOR="38;2;23;147;209"
HOME_URL="https://www.archlinux.org/"
DOCUMENTATION_URL="https://wiki.archlinux.org/"
SUPPORT_URL="https://bbs.archlinux.org/"
BUG_REPORT_URL="https://bugs.archlinux.org/"
LOGO=archlinux
```
- User OS & Browser: `Windows 10 (version 10.0.19041)` | `Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 OPR/69.0.3686.77`
- Grafana plugins: Default core plugins + `Grafana Image Renderer`
- Others: [video](https://moeka.is-a-good-waifu.com/AXvW7Lf.mp4)
[Live](https://ene.fixator10.ru/stats/d/XiQo3iVGk/ene?orgId=1&from=now-24h&to=now)

**Comment by torkelo** [comment]
Don't think this is a Grafana problem, something happens with how influxdb query process the query with time range > 12h

**Comment by torkelo** [comment]
Or wait there is likley a Grafana bug here

**Comment by torkelo** [comment]
There is definitely some bug here: 

Take this view:
https://ene.fixator10.ru/stats/d/XiQo3iVGk/ene?viewPanel=10&orgId=1&from=now-24h&to=now 

Now reduce the width of the panel and you can see that action eating in to the right side of the Graph:

Full width works
<img width="1677" alt="Screen Shot 2020-07-28 at 06 45 48" src="https://user-images.githubusercontent.com/10999/88620334-06759200-d09e-11ea-95f6-4d4b52a8e895.png">

Less width: bug
<img width="1057" alt="Screen Shot 2020-07-28 at 06 45 58" src="https://user-images.githubusercontent.com/10999/88620348-0ffefa00-d09e-11ea-825a-9b649f1ec547.png">

My guess is that the backend somehow incorrectly uses maxDataPoints to limit values in the DataFrame?

thoughts @kylebrandt @ryantxu ?

**Comment by torkelo** [comment]
Your query is returning raw data points (no group by time), so long time range is hitting the maxDataPoints limit. 

you need to add a group by time using $__interval variable to limit number of data points as you increase time range. 

```
from(bucket: "Ene")
 |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
 |> filter(fn: (r) =>
   r._measurement == "-" and
   r._field == "Unique Users"
 )```

**Comment by torkelo** [comment]
I think here we need to use the new meta notice feature to send a data warning from the backend that shows up as a warning icon in the panel header that the maxDataPoints property was exceeded and not all data points where returned

**Comment by fixator10** [comment]
But shouldn't maxDataPoints be by default equal to the width of panel?
After page load ("servers" panel):
![img](https://moeka.is-a-good-waifu.com/3ruE3Uu.png)
After clicking on max data points field and out:
![img](https://moeka.is-a-good-waifu.com/9KxrB8Q.png)

**Comment by aknuds1** [comment]
Looking into this.

**Comment by ryantxu** [comment]
The issue here is that the query does not use the interval... so maxDataPoints will cut things off -- I think this should be solved with adding better notices in 7.2

**Comment by fixator10** [comment]
> The issue here is that the query does not use the interval... 
Thanks for the tip. Added `|> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)`, seems to be working as expected now.

I think this line or somethink like this should be added to `Sample Query` button

**Comment by torkelo** [comment]
@ryantxu is this fixed in master/7.2?

**Comment by torkelo** [comment]
Is this fixed? more work needed?

**Comment by aknuds1** [comment]
@fixator10 Do you consider the issue fixed? Can we close it?

**Comment by fixator10** [comment]
Well, i fixed it for myself, but it would be nice if grafana had so sort of representation of maxdatapoints limit hit and, as i said before, perhaps add `aggregateWindow` call to sample query in grafana

**Comment by aknuds1** [comment]
@ryantxu WDYT? Can we close it?

**Comment by aknuds1** [comment]
Ping @ryantxu

**Comment by gabor** [comment]
in grafana 7.5.0 we improved the warning-notice that explains that you reached max-data-points, and we recommend to use `aggregateWindow()`, so this issue should be resolved now.
