### ISSUE TITLE
SSRF in grafana <=7.0.3

### ISSUE THREAD

**Issue by ishratshahriyar** [grafana/grafana#26623]
Grafana allows any user to add data sources. When a user puts the data source host and port he can save and test. 
For Mysql Data Source:
When a user puts host as localhost and a closed port it returns 
"dial tcp 127.0.0.1:20: connect: connection refused"

When a user puts an open port but which can't handle HTTP, returns
"commands out of sync. Did you run multiple statements at once?"

When a user puts an open port that handles HTTP requests it connects and didn't show any errors.
Also, other data source returns responses and attackers can find an open port using the data source response messages.

The issue is in the error messages, They are so straight forward as the response message/code.
That makes it vulnerable. By implementing a custom error message like "success" and "failed" will make it harder to guess the open port.
Hope it will help. If you need any more information feel free to ask.

**Comment by EmreOvunc** [comment]
Is there any progress on the subject?
