### ISSUE TITLE
Allow base64 encoded image in markdown of text panel

### ISSUE THREAD

**Issue by fredwangwang** [grafana/grafana#26629]
**What would you like to be added**:

Adding the capability to display embedded picture in the markdown document.

**Why is this needed**:
Showing the picture makes the explanation of certain concepts much easier. So it would be helpful in case the text panel is used to explain some concepts on the dashboard.

**Comment by bhozar** [comment]
@fredwangwang I have no problems using with using BASE64 encoded images within the text panel, and it works if it is set to markdown or to HTML. For markdown you have to include it as HTML IMG tags though. Can also include IMG tags to normal images.

**Comment by fredwangwang** [comment]
@bhozar hmm, could you show me how to get it working with \<img\> tag?

I got this example here:
```html
<img src="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUA
    AAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO
        9TXL0Y4OHwAAAABJRU5ErkJggg==" alt="Red dot" />
```

And when I rendered as Markdown:
![image](https://user-images.githubusercontent.com/21690857/88680359-a2f36080-d0ad-11ea-9ab2-b915aba33f81.png)

When rendered as html:
![image](https://user-images.githubusercontent.com/21690857/88680401-b272a980-d0ad-11ea-8737-afc7ba801706.png)

None of the two works as expected..

**Comment by bhozar** [comment]
Ah, sorry, I have just worked out why it is working on my Grafana 7.1. I have  a setting in the grafana.ini file:

`[panels]
disable_sanitize_html = true
`

This has allowed me to use Base64 images, and iframes in the text panels.

**Comment by peterholmberg** [comment]
@fredwangwang did the above solve your issue? Reopen this issue if not.
