### ISSUE TITLE
Fix incorrect login URL in UI when anonymous login is enabled

### ISSUE THREAD

**Issue by holgerbrandl** [grafana/grafana#26639]
**What happened**:

When running grafana on a non-default port e.g. 3007 the login link
![image](https://user-images.githubusercontent.com/200952/88625876-e2b84900-d0a9-11ea-99af-d809a68f9e85.png)
is using the wrong port and wrong host (localhost). It always points to localhost:3000 which is not correct.

Grafana itself is working correctly running a remote host on port 3007.

**What you expected to happen**:

It should open the login page

**How to reproduce it (as minimally and precisely as possible)**:

```

docker pull grafana/grafana:7.0.6

docker run -d  -e "GF_AUTH_ANONYMOUS_ENABLED=true" -e "GF_SECURITY_ADMIN_PASSWORD=whatever"  --name=test_grafana -p 3007:3000 grafana/grafana:7.0.6
```

Open it and try to navigate to the login-page as shown in the screenshot.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.6
- OS Grafana is installed on: Ubuntu Linux
- User OS & Browser: Chrome
- Grafana plugins: None

**Comment by aknuds1** [comment]
Does this still happen in v7.1.1?

**Comment by karlism** [comment]
@holgerbrandl, please update Grafana to newer version, I'm guessing this is related to https://github.com/grafana/grafana/issues/26228

**Comment by torkelo** [comment]
yes, this should be fixed
