### ISSUE TITLE
InfluxDB Flux: Grafana truncates flux queries to 10 tables (dataframes) maximum

### ISSUE THREAD

**Issue by cheeseandcereal** [grafana/grafana#26632]
**What happened**:
When writing queries which return more than 10 tables/series, only the first 10 are retrieved

**What you expected to happen**:
Grafana should not be truncating the number of tables/series which are able to be returned by flux queries

**How to reproduce it (as minimally and precisely as possible)**:
Create a database `testing` in influxdb and write the following data to it:
[test.txt](https://github.com/grafana/grafana/files/4984748/test.txt)

Open up explore in grafana and perform the following flux query:
```
from(bucket: "testing/autogen")
  |> range(start: 2020-05-20T18:40:00Z, stop: 2020-05-20T18:42:00Z)
```

Change the time range in grafana to be absolute:
From: `2020-05-20 18:40:00`
To: `2020-05-20 18:42:00`
With the UTC timezone

Observe that only 10 series are there, and 2 series (namely 8 and 9) are missing from the query results

Performing the same flux query above with chronograf shows that there are actually 12 tables returned by this query

**Screenshots**:
Grafana Query
![image](https://user-images.githubusercontent.com/11189778/88597615-7cd1b000-d01c-11ea-9cbb-e831715c5402.png)

![image](https://user-images.githubusercontent.com/11189778/88598290-d5ee1380-d01d-11ea-8cfd-f48f07ab664d.png)

![image](https://user-images.githubusercontent.com/11189778/88598361-fd44e080-d01d-11ea-9733-bf28c350e15d.png)

Chronograf Query:
![image](https://user-images.githubusercontent.com/11189778/88597983-434d7480-d01d-11ea-8603-ddda04cb3ba9.png)

**Environment**:
- Grafana version: Grafana v7.1.1 (3039f9c3bd)
- Data source type & version: InfluxDB v1.8.1 using flux
- OS Grafana is installed on: Linux Ubuntu 20.04

**Comment by ddemin** [comment]
Same problem, but it worked in old standalone plugin
