### ISSUE TITLE
use template variable for data source

### ISSUE THREAD

**Issue by th3333** [grafana/grafana#26631]
Hi, I wonder how, or if I can, use template variable for "data source", so that I could create graphs from multiple data sources (but with the same metric)?

I know there may not be such a feature yet, if that is the case, please advise if there is plan to add it, or how I can request.

**Comment by torkelo** [comment]
You can create a variable of the type Data source , https://grafana.com/docs/grafana/latest/variables/add-data-source-variable/ 
Can be used to dynamically change the data source, or repeat panels for each data source
