### ISSUE TITLE
Regression in v7.1 - variables not selectable on iOS mobile device (Chrome & Safari) 

### ISSUE THREAD

**Issue by mattheworiordan** [grafana/grafana#26630]
**What happened**:

The first variable drop down on all dashboards using an iOS mobile device with Chrome or Safari (in landscape or portrait) is not selectable as it slides under the dashboard title.

**What you expected to happen**:

The variable to appear beneath the dashboard title like it does in the desktop, even when sized to a mobile viewport size.

**How to reproduce it (as minimally and precisely as possible)**:

Visit any dashboard page that uses variables on an iOS device (13.5.1), with Chrome or Safari.

Safari view:

![F6CAD1A2-48E4-4576-92EE-7ABA336BAAC8_1_105_c](https://user-images.githubusercontent.com/43789/88596499-20db4b80-d05d-11ea-964b-afc0e3957a07.jpeg)

Chrome view: 

![76CF8330-F323-4D3C-B133-9BB810DE5C02_1_105_c](https://user-images.githubusercontent.com/43789/88596129-4fa4f200-d05c-11ea-9798-0517fb7c3897.jpeg)

The same page with Chrome on Mac OS X with the viewport sized to a standard mobile view where the first variable `environment` appears beneath the title "Realtime Data Center"

![screenshot_2020-07-27_10-51-42_pm](https://user-images.githubusercontent.com/43789/88596223-8549db00-d05c-11ea-9863-78aa572fcb87.png)

**Anything else we need to know?**:

**Environment**:

- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: InfluxDB 1.7.10
- OS Grafana is installed on: Ubuntu 20.04 docker image
- User OS & Browser: iOS 13.5.1 , iPhone X, with Chrome or Safari
- Grafana plugins: 

Alert list
Azure Monitor
Bar gauge
CloudWatch
Dashboard list
Elasticsearch
Gauge
Getting Started
Google Cloud Monitoring
Grafana Image Renderer
Graph
Graphite
Heatmap
Home links
InfluxDB
Jaeger
Logs
Loki
Microsoft SQL Server
MySQL
News
OpenTSDB
Plugin list
PostgreSQL
Prometheus
Singlestat
Stat
Table
Table (old)
TestData DB
Text
Zipkin

**Comment by aknuds1** [comment]
Can you please try v7.1.1 and see if it solves the issue for you?
