### ISSUE TITLE
Data links from a single column 

### ISSUE THREAD

**Issue by vishnukrishnan01** [grafana/grafana#26648]
I am using a grafana table with data link to open a url using the table value (${__value.text}) .But this gets applied on all columns .I want to  to apply the data link to one particular column

grafana table view (right now the datalink gets applied on all columns ,I only need it  on the commit id column 

![image](https://user-images.githubusercontent.com/62671132/88656594-2df44b00-d0ee-11ea-9787-cb0e02eca9c8.png)

Datalink created as 

https://url.com/${__value.text}

**Comment by torkelo** [comment]
Use an override rule and select your column, then add the data link https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#override-a-field

**Comment by vishnukrishnan01** [comment]
Thank you so much
