### ISSUE TITLE
How to build grafana v7 from source? 

### ISSUE THREAD

**Issue by starlightme** [grafana/grafana#26642]
Excuse me. I try to build grafana v7 from source. But it says no Go source files. Seems the install from source code page is removed in the   [tutorial webpage](https://grafana.com/docs/grafana/v7.0/project/building_from_source/)   

```
(base) ➜  go go get github.com/grafana/grafana
go: downloading github.com/grafana/grafana v1.9.1
go: downloading github.com/grafana/grafana v6.1.6+incompatible
go: github.com/grafana/grafana upgrade => v6.1.6+incompatible
go get github.com/grafana/grafana: no Go source files
```

Thanks a lot!

**Comment by aknuds1** [comment]
Please read the [developer guide](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md). In the future, please direct support questions to the community [forum](https://community.grafana.com) or [Slack](http://slack.raintank.io/).

**Comment by starlightme** [comment]
Thanks. I update go to 1.14. But still not ok...

Ok. I will direct support questions to the community forum or Slack. Thanks again.

![image](https://user-images.githubusercontent.com/9046253/88642617-4a46b680-d0f3-11ea-8b88-5e55abe12404.png)
