### ISSUE TITLE
Remove URL Alert Link

### ISSUE THREAD

**Issue by D3spereaux** [grafana/grafana#26643]
https://stackoverflow.com/questions/59835357/is-there-anyway-to-remove-the-url-link-from-grafana-notifications-in-telegram
Is there any solution for this question?
I'm tried to research a lot but don't know how to config to remove the URL when alert notification to Telegram channel.
#################################################
My Telegram Bot alert show information at this moment:
[Alerting] CPU Utilization
Message: MHz usage is above warning threshold: > 7500.
- - - - - - - - - - - - - - - - - - - -
URL: http://localhost:3000/d/U1UkZfnMz/host?tab=alert&editPanel=24&orgId=1
Metrics:
MHz Usage: 13844.000

**Environment**:
- Grafana version: v7.0.4
- Data source type & version: InfluxDB + Telegraf
- User OS & Browser: Vivaldi, Chrome
- Others:

**Comment by aknuds1** [comment]
Please use the community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io/) for support questions, GitHub is for bugs and feature requests. Thanks!
