### ISSUE TITLE
permission of folder

### ISSUE THREAD

**Issue by Railymm** [grafana/grafana#26644]
![image](https://user-images.githubusercontent.com/36024321/88642034-8af20000-d0f2-11ea-8193-4e8361aba6f7.png)

If any user has the edit permission in the folder, other users with the view permission also can edit dashboards of the folder.

Like the above graph, the user 19012757 can edit the dashboards in the folder. I want to know why. Any wrong in my configuration?

**Comment by aknuds1** [comment]
Please direct questions to the community [forum](https://community.grafana.com) or [Slack](http://slack.raintank.io). If you have any bugs or feature requests, create a GitHub issue.
