### ISSUE TITLE
Use datasource multi-select variable in metric alias to create separate metric names

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#26645]
**What would you like to be added**:
I would like to use a multi-select variable in the alias of a metric, such that I can use the individual metrics separately. This may also hold for other types of multi-select variables and other datasource types.
![image](https://user-images.githubusercontent.com/6523124/88641198-24072380-d0bf-11ea-92de-c0b99423d9a3.png)
And here is my influxdb metric query for datasource $SelectedCT with $SelectedCT in the alias:
![image](https://user-images.githubusercontent.com/6523124/88641488-96780380-d0bf-11ea-87c9-ec6f9fc9325f.png). 
Note that even with multi-select, only the first selection item is shown, i.e. "**B** (_CT7_)".

**Why is this needed**:
Each datasource points to influxdb on a different host machine, the database tags on each host are similar so don't distinguish the datasource name itself. So the datasource name is the only usable distinction between the metric names.
Without this the metric alias will look like CT7:Isum for single select (which does work), and like { CT4, CT7}:Isum for multi-select. The only work-around for multi-select I can think of is to create metric queries for each individual datasource, which takes time to get right&update and is prone to typing errors. Moreover, all queries will then probably be issued, also when the datasources are not selected, wasting precious bandwidth and CPU/memory resources on my sensor nodes.

See also [my issue](https://github.com/algenty/grafana-flowcharting/issues/211) for the flowcharting plugin, but I think this can be solved more generically in grafana itself so that it would also work in e.g. the graph panel.

Kind regards,
Dennis

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited engagement from the community and/or the Grafana team. 

Fear not, this is not necessarily the end of the line for this feature request. Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so both the Grafana team and the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. We understand that closing issues can feel like a disappointment. The reality is that we can't get to them all. Should you wish to connect to discuss this feature, our workflow, or anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
