### ISSUE TITLE
AWS CloudWatch Log Monitoring by Grafana 7+

### ISSUE THREAD

**Issue by pakita** [grafana/grafana#26657]
Please can you confirm if Grafana 7+ is capable to provide alarm notification for CloudWatch logs?
I can see requested data by suing Query Mode "CloudWatch Logs" and using native Closu Watch query, for instance
 " fields  @timestamp, @message
| sort @timestamp desc
| filter @message like 'myPattern'
| filter eventName like 'myEvent' 
 but I can not find a way to establish monitoring and alarm notification for "stats count(@message) by eventName like 'myEvent' when I switch query mode to 'CloudWatch Metrics'
I expected similar functionality as Grafana/Loki provides but am I wrong?
Thank you,

**Comment by aknuds1** [comment]
Please direct questions to our community [forum](https://community.grafana.com) or [Slack](http://slack.raintank.io). We use GitHub for bugs and feature requests. Thanks!
