### ISSUE TITLE
Not able to create alert on Status Panel Plugin

### ISSUE THREAD

**Issue by Rishikesh287** [grafana/grafana#26653]
We are using **Grafana + Influx DB on Windows 10** . Version are mentioned below - 

**grafana - 6.6 
influxdb - 1.8.0-1**

We have a requirement  to send alert from **Status Panel Plug In** . But we don't find option to create mail alert  in  **Status Panel Plug In**.  
Earlier we had found that in the ****issue #15059** - Creating alert is not available for Table panel** . (https://github.com/grafana/grafana/issues/15059#issue-403037770) .  In the reply seaction, we come to know that this feature will be added in future release of Grafana .

 **My Query**  :-  Is this feature is still not available in Grafana ?  And if it is available ,could you please mention in which  version of Grafana .

**Comment by torkelo** [comment]
Only core graph panel supports alert rules, and in the future no panel will have this feature as we are moving alert rules out of dashboard panels to allow you to define alert rules as standalone entities.

**Comment by Rishikesh287** [comment]
Thank you for the confirmation .

**Comment by lealceldeiro** [comment]
@torkelo If possible, could you tell us, what's the approximate release date for this enhancement?

**Comment by torkelo** [comment]
There is no plans to introduce this, we plan to move the alerting rule definition out of dashboard panels and make alert rules their own thing
