### ISSUE TITLE
Alerting do not become Ok when no data

### ISSUE THREAD

**Issue by lenssoliang** [grafana/grafana#26664]
**What happened**:
It still alerting when the value is no data

**What you expected to happen**:
The alerting should be Ok when it is no data

**How to reproduce it (as minimally and precisely as possible)**:
From below screen-shot, the exceptions count is 87 on 10:00 yesterday. So it raise a alerting. But no any exception after that. 
By the condition, it will alert when the exceptions count is above 50 in past 1 hour. 
So I expect the alerting should be Ok for now. But it still alerting.
![image](https://user-images.githubusercontent.com/20389631/88745299-4743d880-d17c-11ea-9b81-ea85e788c732.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you hit Test Rule button, what is the result?

**Comment by lenssoliang** [comment]
@torkelo 
![image](https://user-images.githubusercontent.com/20389631/88761644-1aa2b780-d1a2-11ea-9cbd-9156765ca941.png)

**Comment by torkelo** [comment]
what data source are you using? The alerting state looks correct as your query is erroring 

@kylebrandt what does that error mean? "Field sorting on a wide time series frame called on a series that is not wide"

**Comment by lenssoliang** [comment]
I am using Application Insights.
Maybe this problem will be fixed alongside with https://github.com/grafana/grafana/issues/26473 ?

**Comment by torkelo** [comment]
yes, this looks like it's fixed in 7.1.1

**Comment by lenssoliang** [comment]
#26473 do not list in release notes?
![image](https://user-images.githubusercontent.com/20389631/88772564-8a6d6e00-d1b3-11ea-826f-5f12baf21c85.png)
