### ISSUE TITLE
Loki: Show query autocomplete suggestions for exact matches

### ISSUE THREAD

**Issue by Rydez** [grafana/grafana#26661]
When writing a Loki query, the autocomplete/typeahead removes exact matches:

The suggestion is given for incomplete text here:
![Screenshot from 2020-07-28 12-29-21](https://user-images.githubusercontent.com/21091975/88694443-89164580-d0ce-11ea-8d8b-4b3fb4637c88.png)

The suggestion is removed for an exact match here: 
![Screenshot from 2020-07-28 12-29-38](https://user-images.githubusercontent.com/21091975/88694517-a6e3aa80-d0ce-11ea-8fdd-2ba26cc91fab.png)

(Maybe there's a duplicate issue, but I couldn't find it)

Perhaps this was intentional, because if there's an exact match then the user doesn't need help completing the word anymore. However, it would be nice to leave the exact match suggestion because then the user doesn't have to go back to the beginning of the word to place a quotation mark. Plus the suggestions are nice to have as a sanity check that the user has typed in the correct word.

**Comment by Rydez** [comment]
If this is something the Grafana team thinks should be changed, I could take a stab at it :+1:.

**Comment by torkelo** [comment]
sounds like a good idea

**Comment by torkelo** [comment]
not a bug really

**Comment by davkal** [comment]
Yeah, this conflicts with the last change (not auto-selecting the first suggestion any more) and should be re-introduced again.

**Comment by aocenas** [comment]
So just FYI we were actually fixing this in the other direction here https://github.com/grafana/grafana/issues/24504. So I would say the PR by @rdubrock makes sense cause it keeps showing suggestions only for cases where the suggestion would insert some additional text (in this case the quotes) but maybe does not make sense in general as for other users that was confusing.
