### ISSUE TITLE
Logs visualization and Explore trim Loki log lines

### ISSUE THREAD

**Issue by lukipro** [grafana/grafana#26668]
**What happened**: Loki log lines shown in Grafana (Explore or Logs visualiztion) are trimmed to 16384 characters.

**What you expected to happen**: Whole log lines are displayed.

**How to reproduce it (as minimally and precisely as possible)**: Put a log line longer than 16384 into Loki, then try to visualize it in Grafana.

**Anything else we need to know?**: If I run a raw query against Loki for a log line which is longer that 16384, I get the whole log line. It is just that Grafana trims it in the browser.

**Environment**:
- Grafana version: v7.0.3
- Data source type & version: Loki v1.3.0
- OS Grafana is installed on: Docker image: grafana/grafana:7.0.3
- User OS & Browser: Browsing Grafana in Google Chrome 83.0.4103.116, running MacOS Catalina, 10.15.5
- Grafana plugins: N/A
- Others:

**Comment by ivanahuckova** [comment]
I have tested this and I was able to visualise logs with 100,000+ characters on locally running loki + grafana. Could you maybe check and share with us, how many characters does that log have in query response in dashboards panel inspect? 
![image](https://user-images.githubusercontent.com/30407135/88805311-46786a00-d1af-11ea-9121-8ae7daf4cd2e.png)

![Kapture 2020-07-29 at 15 02 33](https://user-images.githubusercontent.com/30407135/88804027-9f470300-d1ad-11ea-9447-90cf04eb0668.gif)

**Comment by lukipro** [comment]
Thanks Ivana, I just did the same test as you and was able to view a log line of 100.000 characters. 👍 
Let's close this issue.
It turned out that my log lines are indeed 16384 characters long. These logs are just very long JSONs. It's the escape '\' which extend them to over 17k.
