### ISSUE TITLE
Panel > "Edit": Address confusion/visibility between "Apply" + "Save" Buttons

### ISSUE THREAD

**Issue by ximsandthings** [grafana/grafana#26660]
**Why is this component needed**:
To avoid users missing the "Save" button and clicking "Apply" assuming that this will save their changes in the panel. The "Apply" button is currently the top-most, right-most, and only colored button (bg and text) on the Edit mode screen. It really stands out, which appears to imply finality and authority higher than that of "Save" which is far less distinguishable in placement and color, yet a more powerful/permanent action.

Possible Solutions:
- Save button as right-most, and/or
- Save button is colored, a more urgent color than than "Apply"
___
 - [ ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
As far as I could tell this is only relevant to the "Edit" mode of a Panel.
![image](https://user-images.githubusercontent.com/67602382/88688115-050c8f80-d0c7-11ea-954a-0121fe00c97e.png)
___
- [x] Post screenshots possible.
- [x] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by callumj** [comment]
I want to upvote this. Can we get some documentation and tooltip so users know what each of this does? "Save" and "Apply" are two very similarly worded things. If anything "Apply" should be "Preview" or "Return to Dashboard".

"Save" should also be in some glowing state when there are changes that have not yet been persisted.
