### ISSUE TITLE
Multi selected datasource variable in metric alias only shows first datasource metric with weird name

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#26672]
**What happened**:
I have a variable defined in the dashboard for selecting one or more datasources, and use this in metric queries for voltage, current and power. I use the variable name in the metric alias.
When I do multi-select, I only see the graph for the first selected datasource and it shows it with the label {CT4,CT7}:L?-rms_median instead of CT4:L?-rms_median, with ? one of 1,2,3.
My datasource variable:
![image](https://user-images.githubusercontent.com/6523124/88796571-2e4e1e00-d1a2-11ea-9e2c-276b788638c9.png)
My Metric query:
![image](https://user-images.githubusercontent.com/6523124/88901032-8c393f00-d250-11ea-8ecb-568fc79fbc7a.png)
The resulting graph panel with multi-select:
![image](https://user-images.githubusercontent.com/6523124/88796606-3ad27680-d1a2-11ea-9aee-f3a6de38be1b.png)

**What you expected to happen**:
I expected to see the graphs CT4:L?-rms_median and CT7:L?-rms_median in the graph instead of {CT4,CT7}:L?-rms_median with ? one of [1,2,3].

**How to reproduce it (as minimally and precisely as possible)**:
- create multiple influxdb datasources with different names, e.g. CT4 and CT7
- create dashboard datasource variable e.g. $SelectedCT with multi-select that can select these datasources
- create a graph panel
  - create metric query that uses $SelectedCT as datasource
  - use $SelectedCT in alias for this metric query
- select multiple datasources and watch the graph panel

**Anything else we need to know?**:
I created an enhancement ticket in #26645 for multi-selected datasources, but realized that using only the first multi-select metric in the graph panel is actually a bug.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Grafana ships with built in support for InfluxDB (> 0.9.x).
- OS Grafana is installed on: Armbian 20.02.1 Buster
- User OS & Browser: Ubuntu 18.04.4 LTS / mozilla firefox 78.0.2+build2-0ubuntu0.18.04.1 amd64
- Grafana plugins: agenty-flowcharting-panel  marcuscalidus-svg-panel  natel-plotly-panel  simpod-json-datasource
- Others:

**Comment by torkelo** [comment]
You have to repeat graph for every data source you have selected in the data source. 

Multi data source variables are a very special case and have to be paired with repeated rows or panels
