### ISSUE TITLE
How can I give grafana user appropriate permission so that it can start successfully?

### ISSUE THREAD

**Issue by Soh4il** [grafana/grafana#26675]
Problem

when I deployed this grafana dashboard first time, its working fine. after sometime I restarted the pod to check whether volume mount is working or not. after restarting, I getting below error.

```
mkdir: can't create directory '/var/lib/grafana/plugins': Permission denied
GF_PATHS_DATA='/var/lib/grafana' is not writable.
You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migration-
from-a-previous-version-of-the-docker-container-to-5-1-or-later
```

**Comment by aknuds1** [comment]
Please direct support questions to our community [forum](https://community.grafana.com) or [Slack])(http://slack.raintank.io). Thanks!

**Comment by Soh4il** [comment]
It's ok,, thanks!
