### ISSUE TITLE
[InfluxDB 0.9.x] Override Relative Time with '1M' doesn't work

### ISSUE THREAD

**Issue by diiidiii** [grafana/grafana#2667]
I tried to use the override relative time option with '1M'. When i use it with the dashboard from your website it works (http://play.grafana.org/dashboard/db/graphite-carbon-metrics) (graphite as datasource). Now I try it with InfluxDB and it doesn't work:
![2015-09-03 13_11_35-grafana - influxdb - internet explorer](https://cloud.githubusercontent.com/assets/12936217/9656996/5b62e93c-523d-11e5-8bf0-18d4c61105c7.png)
Is it a problem of InfluxDB? 
When i use development tools of my browser i can extract the following query:
> q=SELECT+mean(value)+FROM+%22system_load1%22+WHERE+%22host%22+%3D+'iqtsdb01'+AND+time+%3E+now()+-+1M+GROUP+BY+time(30m)

**Comment by torkelo** [comment]
what do you want to do? minute, months ?

**Comment by torkelo** [comment]
`m = minute`
`mon = month`

**Comment by diiidiii** [comment]
Yes i want months. With 'mon' it also doesn't work:
![2015-09-04 10_12_48-grafana - influxdb - internet explorer](https://cloud.githubusercontent.com/assets/12936217/9679296/abc496e0-52ed-11e5-85b4-34cb1beaf91c.png)

**Comment by torkelo** [comment]
hm.. your right, it should be capital `M` , seems like InfluxDB does not support month as a relative time range, 

https://influxdb.com/docs/v0.9/query_language/spec.html

**Comment by diiidiii** [comment]
Yep, you're right... i opened influxdb/influxdb#3991
