### ISSUE TITLE
Add folder name into page title between dashboard name and Grafana

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#26676]
**Why is this component needed**:

Right now page title consists of dashboard name and " - Grafana". Usually I'd create some folders to classify different topics of dashboards and have to manually modify the code each time Grafana upgrades.
___
 - [ Y ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
Pages' title
___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ Y ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by peterholmberg** [comment]
This is available in Grafana 7.2.0

**Comment by evandeng2009** [comment]
However this is not what I mean, this feature only add folder name below dashboard name, doesn't make any sense for this request. What I want is for dashboard page title, like "dashboard_name - folder_name - Grafana". Again I changed this code in DashboardPage.js
