### ISSUE TITLE
Text panel content underlaps other panels/rows if content is larger than panel size

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#26677]
**What happened**:
when content is larger than the text panel size, the content underlaps bellow the other panels and rows.
![image](https://user-images.githubusercontent.com/1184220/88828454-2c488700-d1c3-11ea-9ce4-37cb3aaceac0.png)

**What you expected to happen**:
Text panel to have a scroll bar, as on earlier Grafana released, and content not overlapping.

**How to reproduce it (as minimally and precisely as possible)**:
Crate a text panel with content, shrink the box smaller than the content, have it above any other panels.

**Environment**:
- Grafana version: 7.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10 :Chrome/Edge/Firefox

**Comment by aknuds1** [comment]
Is this Grafana v7.1.1?

**Comment by aknuds1** [comment]
This is fixed in #26612. Should be released with 7.1.2.
