### ISSUE TITLE
Use percent (0.0-1.0) with Decimals on Y Axes results wrong labels

### ISSUE THREAD

**Issue by tiansh** [grafana/grafana#26685]
**What happened**:
![render result of percent (0.0-1.0) unit with Decimals 3](https://user-images.githubusercontent.com/6500326/88878251-06e56880-d217-11ea-8294-e4f891b1e2af.png)

The labels on Y axes shows N digits where N is the value configured as Decimal operation. But the last two digits will always be zero.

**What you expected to happen**:
Either show (N-2) decimals or make a value like 99.850% possible should be acceptable.

**How to reproduce it (as minimally and precisely as possible)**:
* Setup a panel
* Write a query which result percent values in 0.9~1.
* Choice Unit percent (0.0-1.0), Decimal 3

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.1 (3039f9c3bd)
- User OS & Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:78.0) Gecko/20100101 Firefox/78.0
- Others: I'm working on https://play.grafana.org/ for above screenshot.

**Comment by torkelo** [comment]
If you hardcode decimal count to 3 Grafana will show 3 decimals, if you want auto decimal leave decimals option empty

**Comment by torkelo** [comment]
probably because for unit 0.1 as percent the value is multiplied by 100 before presenting, so will always have two trailing 00
