### ISSUE TITLE
Default line limit set on Loki data source is not actually used in Grafana explorer

### ISSUE THREAD

**Issue by swisspol** [grafana/grafana#26688]
**What happened**:
Set default line limit in data source to 2500.

**What you expected to happen**:
Actual line limit used in Grafana Explorer is 1612.

**How to reproduce it (as minimally and precisely as possible)**:
- Have the Loki data source line limit default set to 2500 (from JSON provisioning)
- Visit https://{redacted}/explore and make sure Loki data source is selected
- Enter a query
- Line limit shown in in the UI is set to 1612 instead of 2500

![image](https://user-images.githubusercontent.com/627915/88884924-667a4e80-d1ec-11ea-840c-908f848558aa.png)

**Anything else we need to know?**:
If you set the line limit override field in the query to 5000, it will now show "Limit: 5000 (502 returned)". Then empty the field and execute the query again: it now shows "Limit: 2500 (502 returned)".

(No matter what, this doesn't impact the query results but that's because of #26687)

**Environment**:
- Grafana version: Grafana 7.1.1
- Data source type & version: Loki 1.5.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Chrome

**Comment by aocenas** [comment]
Could be a regression after unification of the interface in Explore, as we removed the manual switch between metrics and logs it is possible it is not clear what limit to send with the query, whether the screen width which is important for metrics/graphs or just the maxLines limit which is important to logs. Right now Explore does not know what the query will return so maybe this limit decision needs to be moved inside the datasource.
