### ISSUE TITLE
User removed from org when logging in via generic OAuth

### ISSUE THREAD

**Issue by imran20487** [grafana/grafana#26689]
**What happened**:
When the user logs in to Grafana via generic OAuth, they are removed from the non-default organisation they are part of.

**Expected**:
The user is able to switch to the organisation he is part of after logging in.

**How to reproduce**:
As the Grafana admin, add user1 with a new organisation: user1 added successfully to the new organisation
Now user logs in with generic OAuth: user1 doesn't see the new organisation as part of his list of organisations. And as Grafana admin when I look at the user1's profile the organisation is gone and when I look at the organisation, the user1 is removed. 

**Environment**:
- Grafana v6.7.3
- OAuth configuration in grafana.ini: 
```
[auth.generic_oauth]
enabled = true
client_id = ${OAUTH_CLIENT_ID}
client_secret = ${OAUTH_CLIENT_SECRET}
scopes = openid email corpds:ds:groups corpds:ds:dsid corpds:ds:email corpds:ds:username corpds:ds:firstName corpds:ds:lastName
auth_url = https://corp.com/oauth2/auth
token_url = https://corp.com/oauth2/token
api_url = https://corp.com/userinfo
email_attribute_path = email
role_attribute_path = contains("corpds:ds:groups", '1234567') && 'Admin' || 'Viewer'
```

**Comment by aknuds1** [comment]
Can you please rewrite your issue description according to our standard template? That would make it much easier for us to reproduce the problem you're seeing. Thank you.

**Comment by imran20487** [comment]
> Can you please rewrite your issue description according to our standard template? That would make it much easier for us to reproduce the problem you're seeing. Thank you.

Updated with standard template

**Comment by aknuds1** [comment]
Thanks, trying to reproduce.

**Comment by aknuds1** [comment]
I tried to reproduce with GitLab OAuth, since I already have that set up and couldn't reproduce your problem. I'm on version v6.7.4, but it should only contain an avatar security fix versus v6.7.3, so shouldn't make any difference.

**Comment by aknuds1** [comment]
@alexanderzobnin Do you know if this issue might correspond to #22605?

**Comment by aknuds1** [comment]
I tried to reproduce with generic OAuth now (using GitLab as provider), and the issue still doesn't happen for me. I wonder if there's another configuration parameter of yours, that you haven't listed, that would make the difference.

**Comment by aknuds1** [comment]
Have you set `users.auto_assign_org` to true in your configuration? Might you have the same issue as in #22605?

**Comment by imran20487** [comment]
> Have you set `users.auto_assign_org` to true in your configuration? Might you have the same issue as in #22605?

`users.auto_assign_org` is by default true. Yeah, I think it is the same issue as [#22605](https://github.com/grafana/grafana/issues/22605) and I don't see any official fix for this.

We would like to have more than 3 orgs and using `auto_assign_org_id` would assign to only 1 static org, this would not solve our problem where a user can be a part of multiple orgs.

Thats all the configuration I have for generic OAuth as mentioned in the description. Do I need to specify anymore configuration that I am missing perhaps? Could you share your configuration used for generic OAuth

FYI, I am not using `[auth.ldap]`

**Comment by aknuds1** [comment]
@imran20487 OK thanks - I guess I should close this as a duplicate of #22605 then and we can continue the discussion there.

**Comment by aknuds1** [comment]
Closing as duplicate of #22605.

**Comment by imran20487** [comment]
@aknuds1 As you said above that you were not able to reproduce this issue, could you please tell me what is your configuration in grafana.ini?

**Comment by aknuds1** [comment]
@imran20487 I wonder if I'm not able to reproduce since I'm not using `role_attribute_path`. I'm reading through the conversation in #22605 to wrap my head around the nature of the problem.

**Comment by imran20487** [comment]
> @imran20487 I wonder if I'm not able to reproduce since I'm not using `role_attribute_path`. I'm reading through the conversation in #22605 to wrap my head around the nature of the problem.

Yes, you are right, by removing `role_attribute_path`, I am not able to reproduce the issue. Of course with this we need to manually assign role for each user from UI.

**Comment by aknuds1** [comment]
@imran20487 I think #22605 will end up being the solution, although in which exact form I don't know yet.
