### ISSUE TITLE
x-axis text/series name overlapped in Bar chart/Series mode

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#26692]
Series names are overlapping when we use graph chart in series mode. Request to give some options for orientations or auto-adjust feature.  

![image](https://user-images.githubusercontent.com/65600879/88909445-bbfc3d00-d278-11ea-9969-3924c96b5624.png)

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/3591
