### ISSUE TITLE
Template variable Value is stored in JSON export

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#26693]
The first template variable value is stored in JSON export, even when we don't save the dashboard with current filters.

![image](https://user-images.githubusercontent.com/65600879/88913080-edc3d280-d27d-11ea-9208-15c4508769ea.png)

**Comment by aknuds1** [comment]
Please rewrite the issue using our standard issue template, so we can reproduce your problem. Thank you!

**Comment by torkelo** [comment]
This is fine, will be reset when loaded based on current value

**Comment by satyatechy** [comment]
> This is fine, will be reset when loaded based on current value
It is difficult for us when we share the JSON file over mail with other organizations, our 1st filter value is visible in JSON.

**Comment by torkelo** [comment]
If you want to share with other organizations you should use share feature then all variable option values should be cleared
