### ISSUE TITLE
Hide/disable Panel's Inspect(Panel JSON&Data) and Dashboard's share->Export(Save to file & View JSON) in anonymous mode

### ISSUE THREAD

**Issue by evandeng2009** [grafana/grafana#26697]
**What would you like to be added**:
As issue subject states.
**Why is this needed**:
In anonymous mode, anyone can access panel's "inspect" and dashboards->share->Export to download data and dashboard/panel's JSON. Downloading data is somehow acceptable but JSON not coz it shows everything including the SQL/query statements which expose table structure or fields.
I see hide_version in config file is available so those above should be.

**Comment by torkelo** [comment]
Hiding this in the UI won't make any difference if a user wants access to the query they can see that in the network and dashboard json model.

All queries are dynamically composed and sent from the browser so the browser always have access to the full query and every user who is part of an organization can issue any possible query for the data sources added to that org. 

https://grafana.com/docs/grafana/latest/installation/security/#limit-viewer-query-permissions

**Comment by torkelo** [comment]
we are working on ways of improving this query model so that only a predefined list of queries can be executed for non-editor users

**Comment by dionyziz** [comment]
Is this issue tracked somewhere? Has there been any progress in improving the query model? I am also interested.

Additionally, I would also be interested in hiding the UI for simplicity purposes. I don't care what an adversarial user can do, but I want my every day users to have a clean, non-technical UI with fewer options. Is there a way to achieve this?

**Comment by NicoChang96** [comment]
It's this problem solved? 
Still following
Make this feature,please

**Comment by shaunroselt** [comment]
I'd also like the ability to disable/enable the Inspect feature or individually JSON within Inspect.

We do not want people to be able to `Inspect` and then view `JSON`. Viewing `Data` is fine for us though.

**Comment by Ono-T1m** [comment]
backup first
/usr/share/grafana/public/build/1454.49a7182e33cc461774bd.js
line to remove :
const f = []
                  if (t.plugin && !t.plugin.meta.skipDataQuery) {
                    const t = (0, q.t)('panel.header-menu.inspect-data', '')
                    f.push({ text: t }),
                      e.meta.canEdit && f.push({ text: 'Query' })
                  }
                  const v = (0, q.t)('panel.header-menu.inspect-json', '')
                  f.push({ text: v })
                  const C = (0, q.t)('panel.header-menu.inspect', '')
                  g.push({
                    type: 'submenu',
                    text: C,
                    iconClassName: 'info-circle',
                    shortcut: 'i',
                    subMenu: f,
                  })

save and restart grafana-server service

**Comment by Ono-T1m** [comment]
> backup first /usr/share/grafana/public/build/1454.49a7182e33cc461774bd.js line to remove : const f = [] if (t.plugin && !t.plugin.meta.skipDataQuery) { const t = (0, q.t)('panel.header-menu.inspect-data', '') f.push({ text: t }), e.meta.canEdit && f.push({ text: 'Query' }) } const v = (0, q.t)('panel.header-menu.inspect-json', '') f.push({ text: v }) const C = (0, q.t)('panel.header-menu.inspect', '') g.push({ type: 'submenu', text: C, iconClassName: 'info-circle', shortcut: 'i', subMenu: f, })
> 
> save and restart grafana-server service



> It's this problem solved? Still following Make this feature,please

https://github.com/grafana/grafana/issues/26697#issuecomment-1451974572

**Comment by Kronox89** [comment]
It's this problem solved?
Still following
Make this feature,please

**Comment by Ono-T1m** [comment]
> 

still not in current ver

**Comment by endrelovas** [comment]
I have one question. Is a Viewer able to execute "special" queries reaching other information than a predifined one? Is he allowed to execute any query?
