### ISSUE TITLE
Select component hidden when the dropdown goes up

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#26709]
While working on a datasource query editor, I got confused by the hidden options when the popup goes up:
![image](https://user-images.githubusercontent.com/705951/88980670-14cbd580-d279-11ea-8199-f27748abaeda.png)

vs down:
![image](https://user-images.githubusercontent.com/705951/88980715-2614e200-d279-11ea-8f3b-db196a9b9447.png)

When things go up, we can not scroll to the top few items

**Comment by torkelo** [comment]
We failed to fix this due to Zindex issues with the split panes component and select , only solution we have right now is to force drop downs to go down
