### ISSUE TITLE
Grafana Bar Gauge - x-Axis Sorting by le for prometheus data source

### ISSUE THREAD

**Issue by ashutoshraina** [grafana/grafana#26707]
**What happened**:

While visualizing a histogram based on prometheus, the X-Axis is populated with the bucket ( le label ).
The X-Axis is not sorted by ```le``` causing the histogram to look weird.

![image](https://user-images.githubusercontent.com/1003532/88956376-1d5ce580-d252-11ea-8f83-4fc37d07ee13.png)

There was no combination of sort operator that could be used to get this to work.

**What you expected to happen**:
The X-Axis is sorted in increasing order.

**How to reproduce it (as minimally and precisely as possible)**:
Take a prometheus histogram with multiple buckets and plot it using the bar gauge.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.7.3 (a04ef6cefc) ( Also seen in 7.1 )
- Data source type & version: Prometheus 
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome, Mac
- Grafana plugins: Bar Gauge
- Others:

**Comment by torkelo** [comment]
Sadly prometheus does not have a sort feature for this, 

Duplicate of https://github.com/grafana/grafana/issues/17245

**Comment by andrew-pickin-epi** [comment]
But Grafana sorting is displaying the buckets in order it's just alphabet not numeric. 

If the datasource is of type Prometheus just sort by bucket numerically!

In the real world Prometheus is the most common used datasource, but this makes histograms/bar gauges unusable

**Comment by brightbyte** [comment]
So, there's just no solution for this? Prometheus Histograms are just unusable in Grafana?
