### ISSUE TITLE
More flexible chained variables (preferably conditionals)

### ISSUE THREAD

**Issue by Francis-Valcke** [grafana/grafana#26729]
**What would you like to be added**: Variables that assume a value based on the value of another variable. I know there are chained variables already for query variables. I am asking for the same possibility for other variables or being able to decide de the value of a new variable conditionally on the value of an existing variable.

**Why is this needed**: I want to be able to switch between environments using just one variable. The problem is because of inconsistent naming that sometimes I need for example "production" and other times I need "prod" in my panels to show the production environment. Ideally I would like to be able to just select "production" on top and that I can further transform this variable where needed for example with a conditional or through a chained variable. I would like to be able to define a conditional based on another variable say $env, and based on the value define diffrent outcomes. When $env is set to production, i should be able to transform this into prod. This would be a very powerful tool.

**Comment by torkelo** [comment]
Think features like this will likely need to wait for a future scripted/dynamic dashboard feature
