### ISSUE TITLE
Application Insight Query Analytics show only limited columns as series of Graph 

### ISSUE THREAD

**Issue by aricamf** [grafana/grafana#26723]
**What happened**: Application Insight Query Analytics of Grafana 7.1.1 showed only the datetime column as series of Graph but all others will be missing

**What you expected to happen**: All columns should be visible as series

**How to reproduce it (as minimally and precisely as possible)**: 
In my side,
1. connect to application insight source
2. create a query and change to Insights Analytics
3. run
let statRecords1 = traces | where $__timeFilter() | where customDimensions.STATISTICS == 'CS.SucessfullyCompleted' | project timestamp, agent = tostring(customDimensions.AgentId), calcRecordId = tostring(customDimensions.CalcRecordId), scheduledTime = todatetime(customDimensions.ScheduledTimeUtc), firstUpdatedTime = todatetime(customDimensions.FirstUpdateTimeUtc), completedTime = todatetime(customDimensions.CompletedTimeUtc); 
let 
statRecords2 = statRecords1 | project timestamp, queueWaitTime = totimespan(firstUpdatedTime - scheduledTime)/1s, agent; statRecords2 

![grafana 7 1 1](https://user-images.githubusercontent.com/36829174/89027707-8c733080-d35d-11ea-9b26-a4a48d10d291.jpg)

But in application insights on azure
![image](https://user-images.githubusercontent.com/36829174/89027776-b7f61b00-d35d-11ea-8e90-777b3d597d71.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: Azure Application Insight
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

**Comment by kylebrandt** [comment]
Is format as set to time series? (That part of screen is cropped).

**Comment by aricamf** [comment]
> Is format as set to time series? (That part of screen is cropped).

Hi Kylebrandt

I read the release notes multiple times and eventually figured out the reason. After I added "order by timestamp asc" to my query, everything was displayed as expected. Yes, I need to have at least one time series and one numeric and also "The result must also be sorted in ascending order by the datetime column.".

Thanks
