### ISSUE TITLE
Org Settings - Not saving (Address fields)

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#2672]
Org name is able to be updated, but the address lines are not. See gif:

![](https://cloud.githubusercontent.com/assets/2886187/9673387/c193e75e-5271-11e5-8670-9de6ca968555.gif)

**Comment by woodsaj** [comment]
https://github.com/grafana/grafana/blob/master/pkg/models/org.go#L36-L39

Then UpdateOrgCommand only accepts Name as an input field.  The other fields defined in the model need to be added.

**Comment by torkelo** [comment]
oh, finally someone noticed ;) 

will fix, any other fields to add while I am at it? @matt any thoughts on this?

**Comment by mattttt** [comment]
Address 1, 2
City, State, Zip, Country

We'll add in additional logic after to change state & zip based on country. Right now, text fields will be just fine.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9734688/6a0d8f0e-5635-11e5-8c40-6e8b751f9dc8.png)
