### ISSUE TITLE
Flux: Connections to the InfluxDB Flux datasource are never closed

### ISSUE THREAD

**Issue by sneddrs** [grafana/grafana#26731]
**What happened**:

When using the InfluxDB datasource with Flux, anytime I refresh dashboard  page with uses this datasource, or move between dashboards, a handful of new TCP connections are opened between Grafana and InfluxDB, the stay in ESTABLISHED state and never close unless either InfluxDB or Grafana are restarted.  Over time this can lead to an exhaustion of file handles.

**What you expected to happen**:

I would expect either for connections to be reused, or for them to be closed after use.

**How to reproduce it (as minimally and precisely as possible)**:

1) Create a datasource which connects to InfluxDB using Flux.
2) Create a dashboard which queries the datasource.
3) Monitor the number of connections on the InfluxDB server

    netstat -atn | grep ":8086"
    netstat -atn | grep ":8086" | wc -l

4) Refresh the dashboard page, or navigate between 2 dashboards.  The number of ESTABLISHED TCP connections will constantly increase and never decrease

**Anything else we need to know?**:

I compared the code for InfluxQL compared to the Flux and I can see that with InfluxQL the connection is always closed, but there is no Close() method called in the Flux code (except in the test).

Under - /grafana/pkg/tsdb/influxdb
[root@apps3 influxdb]# grep -Rn "Close()" *
flux/executor_test.go:47:	defer server.Close()
influxdb.go:86:	defer resp.Body.Close()

I am not a Go programmer, or familiar with this codebase, but if I add the following to the Query function, it seems to resolve the issue.

defer runner.client.Close()

Happy to submit the pull request if this seems sensible.

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: InfluxDB (build in)
- OS Grafana is installed on: CentOS 7.8
- User OS & Browser: MacOS 10.15
- Grafana plugins: Just the built in plugins
- Others:

**Comment by aknuds1** [comment]
Sounds problematic, thanks for reporting.

**Comment by coussej** [comment]
Using 7.3.1 I still see a grafana crash every few days. The logs mention `http: Accept error: accept tcp [::]:80: accept4: too many open files; retrying in 1s`, so I assume it's related to the issue here (this started when we started alerting with flux.

I still see connections leaks in 7.3.1 using the `netstat -atn | grep ":8086" | wc -l` command, going from 40 to 255 in just 15mins.

**Comment by sneddrs** [comment]
What OS version are you running, out of interest?  I can see no issue on a server running containers under CentOS 7.8, but do see the same issue still occurring under an OEL 6.10 server (I even double-checked they are running the same binaries by comparing hashes). I'll investigate further.

**Comment by coussej** [comment]
Ubuntu 18.04

**Comment by drgrandios** [comment]
This is a "me too" comment - I'm running the 7.3.1 Grafana docker image on an OpenMediaVault 4.1.3 system (which is basically Debian Stretch) connected to an InfluxDB 2.0.0 docker image on the same host. Amount of connections constantly increases and after about 1 day the Dashboard only shows "no data" in any panel until I restart the Grafana docker image.
