### ISSUE TITLE
Templating error when use global variable in variable query

### ISSUE THREAD

**Issue by Daniel-Mompean** [grafana/grafana#26736]
**What happened**: We receive templating error (Template variables could not be initialized: pq: syntax error at or near "$") when we use use ${__user.id} (global variable) in variable queries.

**What you expected to happen**: We expect get the result of ${__user.id} (global variable)

**How to reproduce it (as minimally and precisely as possible)**: Put "select ${__user.id}" in Query field of Variables (PostgreSQL data source)

**Anything else we need to know?**: It's very important to us (using in global scale)

**Environment**: UAT
- Grafana version: v7.1.0
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Chrome
- Grafana plugins: Core
- Others:
![grafana1](https://user-images.githubusercontent.com/68402165/89055829-78b1d500-d331-11ea-893b-7b64c38e1e45.PNG)
![grafana2](https://user-images.githubusercontent.com/68402165/89055924-997a2a80-d331-11ea-8bef-dbdaabc4792d.PNG)

**Comment by aknuds1** [comment]
Supposed to be fixed in #26637, which should be released with v7.1.2.
