### ISSUE TITLE
Allow setting different thresholds on table visualizations 

### ISSUE THREAD

**Issue by PyvesB** [grafana/grafana#26733]
Hello! 👋🏻 

**What would you like to be added**:

I have built a table that takes in data from two different queries and displays results using a merge transform. Here's a simplified view of the table:
<img width="1006" alt="Screenshot 2020-07-31 at 16 58 21" src="https://user-images.githubusercontent.com/10694593/89047901-5cbd2c00-d34f-11ea-9bc6-5dee8e0f4b9e.png">
 
The idea is that I have a number of services with jobs that can either succeed or fail.

I would like a visual representation of when the number of failures goes above a given threshold, for example above 50 orange, above 100 red. However, this doesn't work as the threshold is unique and applies to all numerical values, and would lead to successes being displayed as red for example:
<img width="1011" alt="Screenshot 2020-07-31 at 16 59 38" src="https://user-images.githubusercontent.com/10694593/89048669-701cc700-d350-11ea-8c86-b937037f0329.png">

**Why is this needed**:

Allowing to set different thresholds on different data sources would allow to build richer tables and convey the most important information more clearly.

**Comment by orena1** [comment]
You can do it with Overrides, it allow you to select a single column and to apply whatever properties that you like:
![image](https://user-images.githubusercontent.com/8983713/90590958-8baa1d80-e1ea-11ea-932a-b353544fb180.png)

**Comment by PyvesB** [comment]
Thanks a lot for the guidance @orena1, I didn't know this could be achieved with overrides! This does work as expected, I'll therefore close this issue. 👍🏻
