### ISSUE TITLE
Plugin builds break whenever rxjs has a new release

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#26748]
When rxjs has a new release, plugins get unhappy ;(
https://github.com/ReactiveX/rxjs/releases

See also https://github.com/grafana/grafana/issues/26038

The workaround is to remove:
```
rm -rf node_modules/@grafana/data/node_modules/rxjs
```

but we should figure out something that will not happen with each new rxjs release

**Comment by ryantxu** [comment]
This is an incredibly annoying issue to deal with, there must be something we can change to make it not happen with every rxjs release

**Comment by aknuds1** [comment]
Agree it needs fixing!

**Comment by torkelo** [comment]
any ideas for how to fix this, the root cause?

**Comment by ryantxu** [comment]
@stevenvachon -- any ideas?  

![image](https://user-images.githubusercontent.com/705951/92640860-c0157480-f292-11ea-826e-176700c84853.png)

I can add:
```
  "resolutions": {
    "rxjs": "6.6.2"
  }
```
To the plugin package.json and that works -- If I put 6.6.3 it complains.   

I would love to find a solution that does not require anything in the plugin package.json!

**Comment by stevenvachon** [comment]
Have you tried reaching out to the rxjs team? It might be something simple that we are expected to know.
