### ISSUE TITLE
Custom units not working with Heatmap visualization in 7.1

### ISSUE THREAD

**Issue by vvuk** [grafana/grafana#26747]
**What happened**:

Trying to use a custom unit as added in PR #20763 (issue #2968).  But there is no option to add a custom unit in the dropdown; I'm forced to select one of the predefined ones:

![image](https://user-images.githubusercontent.com/194965/89082611-57f27b00-d343-11ea-8ca5-d186a1555a3f.png)

**What you expected to happen**:

Let me add a unit. (in my case, dBmV)

**How to reproduce it (as minimally and precisely as possible)**:

Create simple panel.  Type in an unknown unit, or try to use the `si:...` syntax.

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: InfluxDB
- OS Grafana is installed on: Ubuntu, via official grafana docker container

**Comment by ryantxu** [comment]
you sure?  Can you also try with 7.1.1?
![image](https://user-images.githubusercontent.com/705951/89087968-f930ff80-d34a-11ea-8e5a-9065f50b57b6.png)

In 7.1.1 you should also be able to configure the unit from:
![image](https://user-images.githubusercontent.com/705951/89087996-106fed00-d34b-11ea-9375-03c27bb1bd9d.png)

**Comment by vvuk** [comment]
Ahh -- sorry, my confusion.  I'm using the Heatmap visualization; it doesn't seem to be supported there.  Works fine in Graph.
