### ISSUE TITLE
Improve user stats

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#26744]
We need to rethink how we query for the role based user counts:

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/stats.go#L83 

and 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/stats.go#L195 

We count a user role more than once if he is Admin in 2 orgs, and Editor in 3 orgs we count that as 3 editors and 2 admins, but if it's the same user we should only count this as 1 Admin  (the highest role in any org). So a single user id should only be counted once and not be included as part of the number of any of the other stats. 

So Total users =  admins +  editors + viewers
Same for active users. 

To fix this we might have to abandon the current combined mega SQL stats query and make this a separate query that does this calculation or figure out an in-expensive way to do it in current method.

**Comment by adeverteuil** [comment]
This script should work for now.

```
# change login and url values accordingly
login=admin:admin
url=http://localhost:3000

active=$(( $(date +%s) - (3600 * 24 * 30) ))
(
    echo -e "ROLE\tLOGIN\tEMAIL\tLASTSEENAT\tLASTSEENAGE"
    curl -s -u $login $url/api/users \
    | jq -r ".[]|\"\(.id)%\(.login)%\(.email)%\(.lastSeenAt)%\(.lastSeenAtAge)\"" \
    | while IFS=% read user_id user_login user_email user_lastseen user_lastseen_age; do
        if [ $(date +%s -d $user_lastseen) -lt $active ]; then
            break
        fi
        # We can do '|sort[0]' because "Admin" < "Editor" < "Viewer"
        user_role=$( \
            curl -s -u $login $url/api/users/$user_id/orgs \
           | jq -r "[.[].role]|sort[0]" \
        )
        echo -e "$user_role\t$user_login\t$user_email\t$user_lastseen\t$user_lastseen_age"
    done
) | column -t -s$'\t'
```

Sample output:

```
ROLE    LOGIN  EMAIL            LASTSEENAT                 LASTSEENAGE
Admin   admin  admin@localhost  2020-07-31T16:36:20-04:00  < 1m
Admin   asdf   asdf             2020-07-29T11:24:29-04:00  2d
Editor  fdsa   fdsa             2020-07-31T16:33:52-04:00  3m
```

Only users seen in the past 30 days should be listed. Users should be listed only once with their highest org role.

If the report looks good, append this aggregator after `column -t -s$'\t'` and run it again:

```
 | awk '{print $1}' | tail --lines=+2 | sort | uniq -c
```

The final output is a deduplicated count of Viewers, Editors and Admins:

```
      2 Admin
      1 Editor
```

**Comment by sakjur** [comment]
@torkelo I'm having some trouble reproducing the described behavior. I'll explain why 👇 

> We count a user role more than once if he is Admin in 2 orgs, and Editor in 3 orgs we count that as 3 editors and 2 admins, but if it's the same user we should only count this as 1 Admin (the highest role in any org). So a single user id should only be counted once and not be included as part of the number of any of the other stats.

Are we sure that's the exact behavior? The query is

```sql
SELECT COUNT(DISTINCT u.id)
FROM user AS u, org_user
WHERE u.last_seen_at > ... AND ( org_user.user_id=u.id AND org_user.role='...' );
```

The `DISTINCT u.id` only counts the admin once for me even though they are admin in multiple organizations.
_However_ if someone is admin in one organization and editor in another they'll count as both an admin and an editor, so it's still a bug where the statistics are exaggerated by <200% (which is a lot better than n times for n organizations, but still bad).

**Comment by torkelo** [comment]
Yea, was probably wrong on how that worked. 

But as we change this we have to keep performance in mind , as these queries are part of GetaSystemStats that are part of metrics collection so might have to have a seperate solution for that compare to api that shows this
