### ISSUE TITLE
dial tcp 127.0.0.1:500 Connection Refused webhook

### ISSUE THREAD

**Issue by mtetreault** [grafana/grafana#26741]
**What happened**:
I have configured a notification channel of the webhook type. When the alarm is firing I got the following log.

```
t=2020-07-31T17:59:36+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=GrWb9b4Gk error="Post \"http://localhost:5000/alerts\": dial tcp 127.0.0.1:5000: connect: connection refused"
```
My webhook is a Python 3.x Flask application.
```python
#!/usr/bin/env python3

from flask import Flask, request
from urllib.parse import unquote_plus
import json
import re

alert_data = {
  'annotations': {
    'description': '',
    'summary': '',
  },
  'generatorURL': '',
  'labels': {
    'alertname': '',
    'metric': '',
  },
  'startsAt': '',
}
app = Flask(__name__)
data = {}

def parse_request(req):
  payload = req.get_data()
  payload = unquote_plus(payload.decode("utf-8"))
  payload = re.sub('payload=', '', payload)
  payload = json.loads(payload)

  return payload

@app.route('/alerts', methods=['POST'])
def alerts():
  print("Alert received...")
  payload = parse_request(request)
  print(payload)

  # Check if all required keys exists
  for key in alert_data:
    if payload[key] is None:
      return ("Error in JSON", 500, None)

    print("before type check", key)
    if type(payload[key]) is dict:
      for entry in payload[key].keys():
        print("check: ", key, "-", entry)
        if payload[key][entry] is None:
          return ("Error in JSON", 500, None)
  return ("", 200, None)

if __name__ == '__main__':
  app.run(host='0.0.0.0', debug=True, use_reloader=True)

```
The webhook has been tested using Postman and nmap list the port 5000 as opened. There are no sign of communication on wireshark

**What you expected to happen**:
I would be expecting grafana to be able to successfully send the json to the webhook.

**How to reproduce it (as minimally and precisely as possible)**:
Use the flask application above and configure grafana to send a webhook to ip:5000/alerts

**Anything else we need to know?**:
**Environment**:
- Grafana version: branch v7.1.1 commit: 3039f9c3bd2796a0a410544ad2e0e1ed4426a8db
- Data source type & version: data source: MySQL, Not sure where to grab the version information
- OS Grafana is installed on: Ubuntu 19.10  - eoan
- User OS & Browser: Ubuntu, Google Chrome
- Grafana plugins: none (those that comes bundled with grafana when you build)
- Others:

**Comment by aknuds1** [comment]
How do you run Grafana?

**Comment by mtetreault** [comment]
I am building the docker image and then I run it using:
`docker run -d -p 3000:3000 --name grafana grafana/grafana:dev`

I got this to work by changing the webhook port to 9890.

**Comment by aknuds1** [comment]
I think the problem is that your Docker container doesn't have access to your Flask server which runs on localhost. This isn't a Grafana issue, but a problem with how you're using Docker.
