### ISSUE TITLE
FR: Support field in where clause in InfluxDB query editor

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#2674]
With the influx query editor it isn't possible to select "value" in the where clause. This would be very useful for me. At the moment i do not use the editor to solve this problem:
![2015-09-04 14_03_08-grafana - meg-pxy - internet explorer](https://cloud.githubusercontent.com/assets/12936217/9683154/c35df600-530d-11e5-952d-c398389c251d.png)

**Comment by torkelo** [comment]
Did not know you can do that, thought WERE was for tag filters. I really do not like the InfluxDB query language, so hard to create a nice UI experiance for :(

**Comment by diiidiii** [comment]
Here you can see an example: https://influxdb.com/docs/v0.9/query_language/data_exploration.html#the-where-clause

> SELECT * FROM response_times WHERE value > 500 AND region='us-west'

**Comment by syepes** [comment]
I am also trying to filter on the actual metric values:
![influxdb](https://cloud.githubusercontent.com/assets/333081/10040716/64db5a8e-61de-11e5-9c95-cefa68635393.png)

But this workaround does not really work as the filtered value 9000 is sent to InfluxDB as a string:
```
[query] 2015/09/23 10:28:00 SELECT mean(value) / 100.000 AS "cpu" FROM "ESXi"."raw"."cpu_coreUtilization_average-percent" WHERE instance = 'avg' AND value > '9000' AND time > now() - 1h GROUP BY time(1s), server
```

Would it be possible if Grafana had some kind of option/knob to specify the value type (String, Int) that should be sent to InfluxDB.

Best regards,
Sebastian

**Comment by torkelo** [comment]
just curious, Do you want to remove cpu spikes from the graph?

**Comment by syepes** [comment]
@torkelo This was just illustrate a simple example, but in other use case I use this kind of filtering to show only values above a certain value...
Did you have any suggestion?

**Comment by torkelo** [comment]
no, the influxdb editor needs to be remade a 3rd (or is it 4th time). It just such a messy and complex query language to build an editor for, will take time to get the editor flexible and yet easy to use, it is really tricky to implement a good editor as well, and no help from InfluxDB.

**Comment by syepes** [comment]
@torkelo No worries, for the meantime my main storage engine Graphite and InfluxDB still can't outperform it.

**Comment by victorhooi** [comment]
Just putting in my 2 cents - I really like the InfluxDB data model. The ability to apply arbitrary tags is incredibly useful. Although I guess it can make things trickier from the editor perspective (what Torkelo said).

Another plus for me is that he InfluxDB project is active, and constantly being improved - I know they're hoping to unveil a new storage engine either this week or next.

@torkelo You mentioned no help from InfluxDB. That's not good =(. This is just an anecdote, but thye've been pretty responsive to me when I've posted questions (even basic ones!) on their mailing list:

https://groups.google.com/forum/#!forum/influxdb

Do you think it's worth posting there, with some of your issues, and seeing if you get a response? I'm sure lots of Grafana users would reply as well, saying that they use InfluxDB and Grafana, and would love to see better integration as well.

**Comment by torkelo** [comment]
@victorhooi I agree tags are nice, but the query language is so limiting, I mean it supports 1% of the types of queries Graphite support, and still it's so much more a low level complex query language with no built in support for metric resolution or roll ups :)  (mixing resolution with group by was a mistake)

But it is active and I think they will solve some pain points. The reason they aren't helping with Grafana is that they are developing their own UI (Chronograph), but still they are offering Grafana hosting so it's a strange situation. I have reached out to InfluxDB so we can work more closely together and help improve the experience in Grafana. 

50% of Grafana users use InfluxDB, I think they would get a better experience with Graphite, if they want to use InfluxDB I want to support that and make their experience as kick ass as possible. Working on that right now via a big update to the Editor that will hide some of the ugly query stuff and transform it into something nicer :) 

https://github.com/grafana/grafana/issues/2802#issuecomment-144930770
![image](https://cloud.githubusercontent.com/assets/10999/10222614/3eeac7ec-6855-11e5-9d50-a3d4366755c2.png)

**Comment by victorhooi** [comment]
Aha, I'm glad to hear you've reached out - hopefully it'll all work out.

Two other good features of InfluxDB:

1. InfluxDB allows data-points at arbitrary intervals (rather than say, every 1 second). In this case, we're graphing database queries in a logfile, which can happen at any time, rather than at fixed discrete intervals.
2. You can add arbitrary amounts of data to each data-point - so you can put the whole database query in as a string, you can put the duration of the operation as an integer, you can put other metrics as other fields etc.

So the data model is awesome - but yeah, I find the querying pretty confusing, so I'm really glad for Grafana, that it's able to hide some of that =).

That looks awesome mate (Editor update) - can't wait to see it out! I'm sure there's heaps of other people excited about it as well =).

**Comment by torkelo** [comment]
that data model flexibility comes an incredible cost to storage requirement & performance, current InfluxDB requires more storage than Elasticsearch  (which requires multiple orders of magnitude more storage than Graphite). But InfluxDB is working on a new storage engine which might be production ready in a year or so, but Paul has been working personally on it so it could be really awesome :)

**Comment by haidaraM** [comment]
Any new on this issue ?

**Comment by daniellee** [comment]
@haidaraM we have not received any PR's for this and it is not on the short term [roadmap](https://github.com/grafana/grafana/blob/master/ROADMAP.md).

**Comment by haidaraM** [comment]
Ok. Thank you for your reply

**Comment by Esity** [comment]
I would argue that this one should be closed out. InfluxQL does not support filtering based on field values and only tag values. This means that Grafana would have to parse all the requests and make decisions on that which is unrealistic. 

If you have something you want to filter on, you should probably add it as a tag(but please consider cardinality before just adding everything as a tag)

**Comment by gabor** [comment]
this issue is basically another perspective for https://github.com/grafana/grafana/issues/4744 so i will close this one and add a comment to https://github.com/grafana/grafana/issues/4744 to emphasize the choose-field-from-WHERE-dropdown use-case

**Comment by forzagreen** [comment]
InfluxQL _does_ support filtering on field values.
Unfortunately, the query editor in Grafana converts numerical and boolean values to strings, i.e. `99` becomes `"99"`, and `true` becomes `"true"`
