### ISSUE TITLE
Influxdb/Flux: limit for the number of series should be configurable

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#26758]
**What would you like to be added**: 
An option to configure the max number of series InfluxDB should return (with flux)

**Why is this needed**:
We use Telegraf agent who monitors all our certificates and we use Grafana to keep track of the expiration date, but the limitation is to 10, and 50 with the next release https://github.com/grafana/grafana/pull/26746

**Comment by kchervonets** [comment]
We also have this problem, 50 is not even enough for us.

**Comment by bland328** [comment]
Glad to see this getting a bit of attention, and just wanted to emphasize _(per my closed duplicate https://github.com/grafana/grafana/issues/28337)_ that it would also be excellent for Grafana to somehow alert the user in the case that InfluxDB/Flux or any other datasource returns more results than Grafana is configured to accept.

I'll split this off into its own feature suggestion, if that's more appropriate.

**Comment by agolovenko** [comment]
This is a very annoying and counterintuitive feature to **silently** cut-off time series basically at any value. Makes pretty much unusable grafana for our use case (> 100 series). Either make the limit configurable or even better - remove it completely. This issue should get more attention IMHO

**Comment by Aqualie** [comment]
Is there any work being done to implement this? I'm also hitting the new 50 cap this should be make configurable

**Comment by doransmestad** [comment]
I also just hit this. Took me a little bit to figure out what was going wrong due to the silent nature of this.  My use case is monitoring latency of Ceph OSDs (per OSD), which results in many more than 50 series.  Interestingly this works in InfluxQL, but not our new Flux-based queries.  The same query works perfectly in Influx's web UI.

**Comment by oliveres** [comment]
Guys, where is 50-series limit hardcoded? Thx

**Comment by Eraac** [comment]
@oliveres https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/flux/flux.go#L42

**Comment by oliveres** [comment]
> @oliveres https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/flux/flux.go#L42

Thank you for the exact reply. But I cannot find this in my deb package installation.
