### ISSUE TITLE
New Stats Panel does not show Legend when there is a single stat

### ISSUE THREAD

**Issue by hannahchan** [grafana/grafana#26752]
Previously in Grafana 6.7.2, the new Stats panel showed the Legend text or the query that was used to create the panel.

![Screen Shot 2020-08-01 at 10 29 55 pm](https://user-images.githubusercontent.com/22674140/89101826-fa475700-d446-11ea-9e01-0bcae8d3f092.png)

In the latest version of Grafana, 7.1.1 and Stat panel plugin version 7.1.1 this is what you see. The Legend text is now missing.

![Screen Shot 2020-08-01 at 10 23 59 pm](https://user-images.githubusercontent.com/22674140/89101838-13e89e80-d447-11ea-8fc8-68a828f9e2be.png)

I can't figure out what combination of settings I need to set to get this back.

**Comment by torkelo** [comment]
What data source are you using and what are your panel settings (panel json helps )

**Comment by hannahchan** [comment]
I'm using Prometheus. A copy of the Panel JSON is below.

```json
{
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "percentunit",
      "displayName": "${__series.name}",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "grey"
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 3,
    "w": 2,
    "x": 0,
    "y": 17
  },
  "id": 12,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "mean"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "textMode": "auto",
    "colorMode": "value",
    "graphMode": "none",
    "justifyMode": "auto"
  },
  "pluginVersion": "7.1.1",
  "targets": [
    {
      "expr": "sum(increase(http_requests_received_total{job=~\"${job:regex}\", controller=~\"${controller:regex}\", action=~\"${action:regex}\", method=~\"${method:regex}\", code=~\"2.*\"}[$__range])) /\nsum(increase(http_requests_received_total{job=~\"${job:regex}\", controller=~\"${controller:regex}\", action=~\"${action:regex}\", method=~\"${method:regex}\", code=~\".+\"}[$__range]))",
      "instant": true,
      "legendFormat": "% Successes (2xx)",
      "refId": "A"
    }
  ],
  "type": "stat",
  "datasource": null
}
```

**Comment by therealcodlord** [comment]
I noticed a change in behaviour in one of my (single value) stat panels between v7.1.0 and v7.1.1 and this sounds like the same issue.

v7.1.0
Single stat `Stat` panel would show (before the metric) either the `Legend` field (if it was a Prometheus query) or the `Display name` field for Prometheus or other data sources such as MySQL.

v7.1.1
Single stat `Stat` panel now shows nothing apart from the metric value.
For `Time series` query if you specify the `Legend` field (Prometheus queries) then that is shown as a hover tool-tip popup only (`Display name` seemingly ignored). For `Table` query the `Legend` field is seemingly ignored but `Display name` is displayed as a tooltip popup.

Similar case for other data sources such as MySQL where my stat panel used to show the contents of `Display name` but now it's just displays that as tooltip popup. For both `Table` and `Time series` queries.

**Comment by Eraac** [comment]
Probably linked to this https://github.com/grafana/grafana/issues/26583

**Comment by hannahchan** [comment]
I just tried this out on one of the nightly builds `7.2.0-549f1ed2pre` and it appears to be fixed. I think we can close this now.

**Comment by aknuds1** [comment]
@hannahchan Great :) Please ping us again if it turns out to not be fixed after all.
