### ISSUE TITLE
Create release tarball for version 1.9.1

### ISSUE THREAD

**Issue by mattbostock** [grafana/grafana#2675]
Hello,

In older versions on the 1.9.x branch you pushed a release tarball, for example for [version 1.5.2](https://github.com/grafana/grafana/releases/tag/v1.5.2).

I'd like to use version 1.9.1 as we're not yet ready to upgrade to version 2. Could you please push a release tarball for version 1.9.1 to GitHub?

Thanks,
Matt

**Comment by torkelo** [comment]
whats wrong with the 1.9.1 download links on http://grafana.org/download/ ? 
http://grafanarel.s3.amazonaws.com/grafana-1.9.1.tar.gz

**Comment by mattbostock** [comment]
I wasn't aware that that was a release version rather than just the source. Thanks!
