### ISSUE TITLE
Document the X-Grafana-Org-Id HTTP header

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#26769]
Document the X-Grafana-Org-Id HTTP header in the API docs.

Added by PR https://github.com/grafana/grafana/pull/8122
Referenced here: https://community.grafana.com/t/organization-state-in-the-api/7954

**Comment by torkelo** [comment]
This is an internal header the frontend uses

**Comment by torkelo** [comment]
But could be added to api auth docs https://grafana.com/docs/grafana/latest/http_api/auth/

**Comment by marefr** [comment]
> Also needs to be added in the data source settings, because you can update it in the UI as well.

@oddlittlebird what do you mean? The only way in the UI is to use the org switcher or what am I missing here?

**Comment by oddlittlebird** [comment]
Loki and Prometheus at least allow you to add custom HTTP headers

**Comment by marefr** [comment]
@oddlittlebird that's a completely different feature than this. Should probably be its own issue, something like "Document custom data source HTTP headers"
