### ISSUE TITLE
Grafana/Loki/Promtail : Transformation "Labels to fields" don't for syslog messages cached by promtail

### ISSUE THREAD

**Issue by BriceNeo** [grafana/grafana#26767]
**What happened**:
IHello, I use promtail to distributed syslog message to loki and visualize them by Grafana. In the syslog configuration of promtail, we can extract, as label, the different information from the syslog message like : severity code, facility code, app_name, ip, etc. I tried to display them with the table panel of Grafana. I want to use the transformation "labels to fields" but it doesn't work, my table stay the same : 
![image](https://user-images.githubusercontent.com/69154707/89202732-629a5380-d581-11ea-8bb9-6439a25e4884.png)

Even if I have multiple indexed label : 
![image](https://user-images.githubusercontent.com/69154707/89202911-aee59380-d581-11ea-809d-ca8b75837540.png)

**What you expected to happen**:
I expected that the table after the transformation have a collumn for each indexed label (severity code, facility code, app_name, etc). 

**How to reproduce it (as minimally and precisely as possible)**:
1/ Launch loki
2/ Take this configuration to launch promtail :
server:
http_listen_port: 9080
grpc_listen_port: 0
positions:
filename: /tmp/positions.yaml

clients:

url: http://loki:3100/loki/api/v1/push
scrape_configs:

job_name: syslog
syslog:
listen_address: 0.0.0.0:1514
idle_timeout: 3600s

relabel_configs:

source_labels: ['__syslog_message_hostname']
target_label: host
source_labels: ['__syslog_message_severity']
target_label: level
source_labels: ['__syslog_message_app_name']
target_label: app_name
source_labels: [__syslog_message_facility]
target_label: facility

3/ Send syslog message in RFC5424 in TCP on the port 1514

4/Open Grafana take your Loki source as a datasource 

5/ create a table pannel with a query : {job="syslog"}

6/ add the transformation : "labels to fields" and observe that nothing happen with this transformation

**Environment**:
- Grafana version: 7.1
- Data source type & version: Loki
- OS Grafana is installed on: AWS EC2 (linux type OS)

**Comment by torkelo** [comment]
This transform was designed to only work with time series and labels on a Value field. But it should be extended to work with Loki logs as well

**Comment by BriceNeo** [comment]
Thanks for your quick reply,
Ok I understand, I will check the evolution of this issue.

**Comment by szilardk** [comment]
i have a similar configuration:
grafana: 7.5.4
loki: 2.2.1
logql: {filename=~"server.log"} |= "loaded job" | json
Visualisation: Table
Transform: Label to Query

it is working correctly and extracts the json and displays it in the table. each json attribute as column in the table
@BriceNeo try to update the grafana version
