### ISSUE TITLE
external_labels from prometheus not able to use as filter in Grafana Dashboard variables.

### ISSUE THREAD

**Issue by PavanVasist** [grafana/grafana#26764]
**What happened**:
We are adding external_label to prometheus. This external_label we wanted to use it as variable in grafana(Grafana v7.0.5 (efbcbb838b)) dashboard. But, in grafana, when we declare it, not able to fetch the external labels as variables{Eg - for a label - [cluster="galaxy'], created variable with query - label_values(cluster)}. But in any of the fetched metrics we can see this as a label. Can you please help here, am i configuring something wrong.

**What you expected to happen**:
The label_values(cluster) has to get filtered and preview should have ---> galaxy as one of the values.

**How to reproduce it (as minimally and precisely as possible)**:
Install Prometheus and configure [external_labels](https://prometheus.io/docs/prometheus/latest/configuration/configuration/). Now Use grafana and set Prometheus as DataSource and try creating variable against one of the external_label.

**Anything else we need to know?**:
Adding relavant screenshots - 
![image](https://user-images.githubusercontent.com/13401050/89183623-22ed5f00-d5b5-11ea-8fa4-82cd0968a3a8.png)
Trying to add one of the external_label - *cluster="galaxy"* as variable but no preview of the values.
![image](https://user-images.githubusercontent.com/13401050/89183903-97280280-d5b5-11ea-885a-948d8aeffaa3.png)
Checked with other labels, preview works fine.
![image](https://user-images.githubusercontent.com/13401050/89184139-f5ed7c00-d5b5-11ea-9f6d-6ff97a32f132.png)
As we can see within the metric label is getting applied and filtering with the label works fine.

**Environment**:
- Grafana version: Grafana v7.0.5 (efbcbb838b)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: Nothing
- Others: ---

**Comment by torkelo** [comment]
Grafana issues the queries the same, so if your not getting any label values for a label it must be a prometheus issue
