### ISSUE TITLE
Docs feedback: /linking/dashboard-links.md

### ISSUE THREAD

**Issue by ikkemaniac** [grafana/grafana#26765]
Looks like the # of dashboard links are hard coded limited to 7 (```search?limit=7``` call). If i'm correct, please add a note to the documentation.

**Comment by oddlittlebird** [comment]
@dprokop , can you confirm?

**Comment by oddlittlebird** [comment]
@torkelo or @dprokop, can you confirm? If so, then I will update the documentation.

**Comment by dprokop** [comment]
I don't think this is valid anymore
