### ISSUE TITLE
Enable HSTS when serving HTTP only (SSL is offloaded)

### ISSUE THREAD

**Issue by toote** [grafana/grafana#26770]
**What would you like to be added**:

Per the [documentation about the `strict_transport_security` settings](https://grafana.com/docs/grafana/latest/administration/configuration/#strict_transport_security), they are only in effect when/if HTTPS is set to true. Would it be possible to have those options not depend on other options? After all, they are just HTTP headers.

**Why is this needed**:

Using grafana's standard docker images, we have a setup in which the container only serves through HTTP and SSL is offloaded to a transparent reverse proxy in front of it. This makes it a lot easier to handle certificates used to serve grafana, but it is a downside that we can't enable this very simple security setting that should be completely independent.

**Comment by torkelo** [comment]
If you use a HTTPS proxy it's best that it adds this header I think

**Comment by dnmvisser** [comment]
> If you use a HTTPS proxy it's best that it adds this header I think

Yes I fully agree, but for instance on AWS their load balancers don't support setting headers.

**Comment by torkelo** [comment]
ok, then it can make sense to allow this
