### ISSUE TITLE
Dashboard is not displaying

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2677]
there is a dashboard created using grafana version 2.0.2. When I click on the dashboard, it instantly shows then disappears, it becomes an empty page.

I do see these errors in the log:

2015/09/04 11:20:15 [I] Completed /i/themes/theme_23/css/4_1.css 404 Not Found in 2.150236ms
2015/09/04 11:21:06 [I] Completed /i/css/apex.min.css 404 Not Found in 2.10373ms
2015/09/04 11:21:06 [I] Completed /i/themes/theme_23/css/4_1.css 404 Not Found in 2.409287ms
2015/09/04 11:21:06 [I] Completed /i/libraries/jquery-ui/1.8.22/themes/base/jquery-ui.min.css 404 Not Found in 2.197151ms
2015/09/04 11:21:06 [I] Completed /i/libraries/apex/minified/desktop_all.min.js 404 Not Found in 2.118876ms
2015/09/04 11:21:06 [I] Completed /i/libraries/apex/minified/legacy.min.js 404 Not Found in 2.030623ms
2015/09/04 11:21:07 [I] Completed /i/f_spacer.gif 404 Not Found in 2.060626ms
2015/09/04 11:21:17 [I] Completed /i/css/apex.min.css 404 Not Found in 1.532499ms
2015/09/04 11:21:17 [I] Completed /i/libraries/jquery-ui/1.8.22/themes/base/jquery-ui.min.css 404 Not Found in 1.1022ms
2015/09/04 11:21:17 [I] Completed /i/themes/theme_23/css/4_1.css 404 Not Found in 1.081261ms
ctcprcapplan001:/app/data.2/grafana-2.0.2/data/log # cd ..

Any ideas, what might be causing this?

**Comment by torkelo** [comment]
looks like you have some custom panels or html in that dashboard that have broken it, do you? 

I mean those js and css files are not used by Grafana, so something custom must be added to the dashboard or to your browser.

**Comment by gsaray101** [comment]
how would I go back and edit it? I cannot even do that.

**Comment by gsaray101** [comment]
Hi Torkel,

How would I edit the dashboard, is there a way to do that?

**Comment by gsaray101** [comment]
is the dashboard stored in a db table, which table?

**Comment by torkelo** [comment]
@gsaray101 yes dashboards are stored in the db, in the dashboard table

**Comment by gsaray101** [comment]
I am trying to update the dashboard table with the update json file, I keep getting this error:


Error: near line 1: unrecognized token: "1d"

my sql like this:

update dashboard set data='{"annotations":{"list":[]},"editable":true,"hideControls"

do I need to escape double quotes?
