### ISSUE TITLE
Image Renderer

### ISSUE THREAD

**Issue by GuruGuhanG** [grafana/grafana#26774]
Hi,

Was using Grafana v6.3.0 till v7.0.0 was launched and till the update, I never had any issue with images/screengrab of the alerts being sent to me via mail based on the set thresholds. 
Now I am unable to get any image/screengrab of the alert message in the mail. I have whitelisted image renderer as mentioned in the documentation. But, no luck. 

Can we fix this issue. 

Thanks
![image](https://user-images.githubusercontent.com/60170862/89258592-106f3600-d646-11ea-93a7-17aa2764b201.png)

**Comment by torkelo** [comment]
Have you installed the image renderer? Any details in Grafana server log file ?

**Comment by GuruGuhanG** [comment]
Yes I have; used the CLI command;
grafana-cli plugins install grafana-image-renderer

getting the following message now :
t=2020-08-04T08:46:56+0000 lvl=eror msg="Failed to get browser version" logger=plugins.backend pluginId=grafana-image-renderer err=map[]

**Comment by aknuds1** [comment]
Can you please provide your operating system details?

**Comment by aknuds1** [comment]
You might want to read about the [requirements](https://github.com/grafana/grafana-image-renderer/#dependencies) of the image renderer plugin, I suspect you're missing dependencies in your system.

**Comment by GuruGuhanG** [comment]
NAME="Ubuntu"
VERSION="18.04.4 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.4 LTS"
VERSION_ID="18.04"

**Comment by aknuds1** [comment]
@GuruGuhanG Have you installed the [dependencies](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin-and-remote-rendering-service)?

**Comment by GuruGuhanG** [comment]
@aknuds1 yes I have am still getting the error

**Comment by GuruGuhanG** [comment]
what to do next ?

**Comment by aknuds1** [comment]
Have you put the following in the Grafana config, and checked the log for rendering logs?

```
[log]
filters = rendering:debug`
```

Hopefully you'll see an error message about launching the Chromium browser.

**Comment by aknuds1** [comment]
Read the [troubleshooting](https://grafana.com/docs/grafana/latest/administration/image_rendering/#troubleshoot-image-rendering) documentation for more tips.

**Comment by GuruGuhanG** [comment]
We are looking into this log file /var/log/grafana/grafana.log
![MicrosoftTeams-image](https://user-images.githubusercontent.com/60170862/89397128-13912180-d72d-11ea-96a5-aa8eb39220ce.png)
Following is what we got-->
t=2020-08-05T07:10:08+0000 lvl=info msg="Registering plugin" logger=plugins name="Grafana Image Renderer"

**Comment by aknuds1** [comment]
You don't get any "Rendering failed" error message? Have you tried running `ldd` on chrome-linux/chrome as instructed [here](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin-and-remote-rendering-service)?

**Comment by GuruGuhanG** [comment]
Yes and it showed me all the installed libraries. I did not see any uninstalled libraries meaning all of them mentioned are there..

**Comment by aknuds1** [comment]
How are you running Grafana, in a Docker container?

**Comment by GuruGuhanG** [comment]
No not Docker Container but in a VM

**Comment by aknuds1** [comment]
If you run `./chrome-linux/chrome --version` in the grafana-image-renderer directory, what does it say?

**Comment by GuruGuhanG** [comment]
Chromium 79.0.3945.0

**Comment by aknuds1** [comment]
So, if getting the browser's version works, it's very strange that the plugin fails with this message: "Failed to get browser version". I guess some more in-depth troubleshooting is needed.

**Comment by GuruGuhanG** [comment]
hmm... how do we proceed next ?

Shall i reinstall all the dependencies once again and check for error logs ?

**Comment by aknuds1** [comment]
I don't have any answer for now, but I don't think reinstalling deps are going to make any difference.

**Comment by GuruGuhanG** [comment]
Hi @aknuds1 is there any way we can get this up and running ?

**Comment by aknuds1** [comment]
I would recommend for now to ask for support in the community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io), since we haven't seen any evidence of a bug in Grafana yet.

**Comment by torkelo** [comment]
Closing  this as it looks to be an environment issue (as no other similar reports) , will re-open if more reports come in or new info is presented

**Comment by Habam** [comment]
One dependency missing for Centos7
`sudo yum install alsa-lib`

**Comment by laertis** [comment]
@habam

> # Error log when start grafana
> `t=2020-12-03T08:46:48+0000 lvl=eror msg="Failed to get browser version" logger=plugins.backend pluginId=grafana-image-renderer err=map[]`
> 
> ## Try to query version of chrome under plugin folder
> ```
> ~> ./chrome-linux/chrome --version
> ./chrome-linux/chrome: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory
> ```
> 
> ## Also, keep seeing error logs
> ```
> t=2020-12-03T08:49:31+0000 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=2 error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libasound.so.2: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
> t=2020-12-03T08:49:31+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses=[xxx@xxx.com] singleEmail=false
> ```
> 
> # Solution
> One dependency is missing for Centos7 (not listed in the [troubleshooting document](https://grafana.com/docs/grafana/latest/administration/image_rendering/#grafana-image-renderer-plugin-and-remote-rendering-service))
> 
> ```
> sudo yum install alsa-lib
> ```

you are a lifesaver

For Amazon Linux 2023 and Grafana 7.2.0 this worked for me
- `sudo yum install atk at-spi2-atk cups-libs libdrm libxkbcommon libXcomposite libXdamage libXrandr libgbm pango alsa-lib`

> FYI: With grafana 7.5.17 there was no need for installing any dependencies. grafana-image-renderer worked out of the box after installing it with grafana-cli
