### ISSUE TITLE
How to properly limit data from data source responses?

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#26789]
I think I may be ignorant about existing mechanisms, so this perhaps part feature request or part question.

When a query returns "too much stuff", it can crash a user's browser or cause major hangups. Since we don't have auto-save (https://github.com/grafana/grafana/issues/174), when this happens in can result in a user losing some of their progress. So this is bad. Even with auto save, this sort of experience wouldn't be good either.

Currently, the only common control I am aware of is max data points in query options ([docs](https://grafana.com/docs/grafana/latest/panels/queries/#query-options)):

> Max data points - If the data source supports it, sets the maximum numbers of data points for each series returned. If the query returns more data points than the max data points setting, then the data source consolidates them (reduces the number of points returned by aggregating them together by average or max or other function).

However this doesn't really protect the browser from queries that return too much data:
 
  1. I don't understand max data points in terms of how one should implement it. The description kind of sounds like reduction to me?
  2. In terms of protecting the browser, this won't help in all cases because one can return a rather large number of series even if they individually don't have many data points.
  3. For table like queries, I'm not sure how one should limit them currently? (Max cells seems reasonable, as a table could be too wide and/or too long). Bytes might be another option, as one could in theory have a very large response in a small number of cells (although in practice I have not run into this one).
  4. In cases where a table query is transformed to series, it seems that maybe we need two limits to apply?
  5. The number of cells produced by a heatmap structure also could overload the browser in my past experience (https://github.com/grafana/grafana/issues/16875)

**Comment by torkelo** [comment]
1) I don't understand max data points in terms of how one should implement it. The description kind of sounds like reduction to me?

Max data points have its origins in Graphite. As this is a fundamental feature in the graphite api. However, in Graphite Max data points are also paired with a runtime consolidation function. By default, this is using average. This allows the api caller to always control the number of data points PER series. The user can control the runtime consolidation (aggregation) function by adding a consolidate function. 

Max data points was always only used by Graphite (and Zabbix I think). The rest of all data sources only used __interval to control (limit) time series data points. But how grafana calculated interval was by dividing panel width / time range. So you would never get more than one data point per pixel no matter the time range. But this left no control over how many data points you really cared about. So in 7.0 I did something I wanted to do for along time, expose max datapoints and make it relevant in how __interval was calculated so users of InfluxDB, Elasticsearch, SQL had a time range agnostic way of saying "I only want 5 data points no matter the time range". 

The docs on **Max data points is** misleading and needs to be updated. Will do. 

> 2 In terms of protecting the browser, this won't help in all cases because one can return a rather large number of series even if they individually don't have many data points.
 
Yes, **Max data points** is only about limiting per series points. 

3 > think we could use max data points as a row limit at least? Column limit is trickier.

**Comment by Ralung** [comment]
Hi @torkelo,

"I only want 5 data points no matter the time range", could you share some references about how to implement this?

I am using Google BigQuery and I would like to limit the total of data points no matter the time range.
Like 1k data points if last 7 days, 10k data points if last 30 days, 20k data points if over last 30 days.

Best regards
