### ISSUE TITLE
Alert rule saved in database should refer to related datasource by uid instead of id

### ISSUE THREAD

**Issue by huaphuoctruong** [grafana/grafana#26787]
**What would you like to be added**:
The rule saved in `alert` table are now query it's datasource by datasourceId and it will be failed when the datasource is provisioned again (like container restart) because it ID is changed.

**Why is this needed**:
People can set a fixed uid to the datasource in provision file and the relationship between the alert rule saved in database and new provisioned datasource will be retained. Currently, I have to go to my database and manually update the datasourceId of each alert rule to make it worked again after any container restart or stack redeploy...

**Comment by torkelo** [comment]
the alert rule should be deleted and re-created if the dashboard is removed and recreated, did this not happen? 

thoughts @bergquist ?

**Comment by torkelo** [comment]
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.

**Comment by huaphuoctruong** [comment]
The dashboard is not provisioned but manually created and saved in mysql database. Only the datasource is provisioned
