### ISSUE TITLE
Unable to download file from Text panel inlined script

### ISSUE THREAD

**Issue by serputko** [grafana/grafana#26782]
**What happened**: After upgrading grafana from 6.7.4 to 7.1.1 script in Text panel is not able to download pdf file. At the same time i know that script is executed fine as pdf could be opened in new window without problems, but can't be downloaded

**What you expected to happen**: Expect ability to download files from scripts in Text panel

**How to reproduce it (as minimally and precisely as possible)**:

1. Set disable_sanitize_html = true in defaults.ini file to execute scripts in Text panel
2. Create new dashboard
3. Add new Text panel
4. Set Mode field to HTML
5. Add this demo pdf generator code to content field. 
It creates new pdf file, download it and also open in new tab(just to prove that script works)

```
<script>
    function exportToPDF(element) {
        _export(element);

        async function _export(element) {
            let tempText;
            if (element != null) {
                tempText = element.innerText;
                element.innerText = 'Loading...';
            }

            await init();

			
			var dd = {
				content: [
					'First paragraph',
					'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
				]
				
			}
      pdfMake.createPdf(dd).open();
			pdfMake.createPdf(dd).download('file.pdf', function() { alert('your pdf is done'); });
            
        }

        async function init() {
            $("<style type='text/css'> .chart-text-color{ color: #000000 !important; } </style>")
                .appendTo("head");
            let scripts = [];
            if (window.pdfMake === undefined) {
                scripts.push(
                    jQuery.getScript('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.41/pdfmake.min.js')
                        .then(() => {
                            return jQuery.getScript('https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.41/vfs_fonts.js');
                        }));
            }
            if (window.domtoimage === undefined) {
                scripts.push(
                    jQuery.getScript('https://cdnjs.cloudflare.com/ajax/libs/dom-to-image/2.6.0/dom-to-image.min.js'));
            }
            return Promise.all(scripts);
        }

    }
</script>
<style>
    .status-button {
        color: black;
        background-color: whitesmoke;
        cursor: pointer;
        padding-left: 10px;
        padding-right: 10px;
        align-content: center;
        margin: 10px;
    }
</style>
<span class="status-button" onclick="exportToPDF(this)">Export to PDF</span>
```
6. Save dashboard
7. Click on Export to pdf button in Text panel
![image](https://user-images.githubusercontent.com/16308826/89283283-9181f980-d655-11ea-935d-9d5c66094d5b.png)
8. You should get pdf generation alert
![image](https://user-images.githubusercontent.com/16308826/89283362-b70f0300-d655-11ea-9ca2-93066e89c857.png)
and also pdf file should be opened in new tab
![image](https://user-images.githubusercontent.com/16308826/89283402-c726e280-d655-11ea-9410-072f1482b693.png)
**BUT pdf is not downloaded**

9. If you do the same steps in grafana 6.7.4 you will get  pdf generation alert, pdf opened in new tab and also pdf downloaded
![image](https://user-images.githubusercontent.com/16308826/89283655-2a187980-d656-11ea-97da-40fb941e6b1b.png)

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: does not matter
- OS Grafana is installed on: Windows 10
- User OS & Browser: IE, FF, Chrome

**Comment by peterholmberg** [comment]
Confirmed it does not download the pdf

**Comment by jackw** [comment]
Having looked into this it appears to be an issue with the version of `pdfmake` that is being used. If I update the script to fetch the latest version (0.1.70) `https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.70/pdfmake.min.js` and `https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.70/vfs_fonts.js` then it behaves as expected and I can download the generated pdf file. As such I'm going to go ahead and close this issue.
