### ISSUE TITLE
Export to CSV does not work properly in Grafana v7.1.x

### ISSUE THREAD

**Issue by qrtalaci** [grafana/grafana#26784]
**What happened**: tried to export data (>1000 rows) of one table into .csv, but only two rows displayed (and can be exported) in the Inspect/Data tab 

**What you expected to happen**: all records can be found in the .csv

**Environment**:
- Grafana version: v7.1.0, v7.1.1
- Data source type & version: InfluxDB v1.8.0
- OS Grafana is installed on: Docker (19.03.12) container on CentOS 7.8
- User OS & Browser: Windows10, Chrome Version 84.0.4147.105 (Official Build) (64-bit)
- Grafana plugins: many, https://github.com/kumaravel29/sankey-panel, https://gep.net.telekom.intra/plugins/agenty-flowcharting-panel/, etc.

![image](https://user-images.githubusercontent.com/639291/89289012-da867d80-d656-11ea-8ca0-b474c414daeb.png)

![image](https://user-images.githubusercontent.com/639291/89288713-62b85300-d656-11ea-84a8-aef5adbe8dd2.png)

**Comment by torkelo** [comment]
That is very strange, the second report of this, we have yet to replicate it 

https://github.com/grafana/grafana/issues/26460 

Any errors in the chrome dev tools?

**Comment by torkelo** [comment]
Can you include raw network results from your query and your panel json? (in the linked issue)
