### ISSUE TITLE
InfluxDB Flux language data source suffers from serious issues with InfluxDB OSS v2

### ISSUE THREAD

**Issue by mjf** [grafana/grafana#26780]
**What happened**:

The *InfluxDB Flux data source* (core, still beta) does not work properly for *InfluxDB OSS v2* and seems to be suffering from many miscellaneous issues especialy with complex *Flux* language queries (including imports of modules etc). Also dashboard variable queries are broken (perhaps completely). Although the data source is working for the simplest *Flux* queries for panels, tables etc., the variable queries are claiming access errors making the data source effectively unusable for almost anything.

**What you expected to happen**:

To use the *Flux* language queries in *Grafana* (finally)...

**How to reproduce it (KISS)**:

Just try to work with the *Flux* data source (be core or the plugin) and achieve something... It's real pain to get at least something work at least as well as it works for the *InfluxQL*...

**Anything else we need to know?**:

It's perfectly OK that one have to try the *Flux* queries in the *InfluxDB OSS v2* query editor and then copy/paste to *Grafana*, or to use `curl`, or the *CLI* or whatever. That's not the case at all...
The problem is that almost everytime you try to get your already **working** queries in *Grafana* it's broken in some way!
You can not therefor replace existing dashboards based on the *InfluxQL* language (with all it's limitations) to much more expressive *Flux* language (often needed to achieve things that can not be easily done with the *InfluxQL*). People who are going to switch to *InfluxDB OSS v2* (quite soon) are stuck now and can't work on their *Grafana* stuff...

From my point of view, the *Flux* data source is even **no *beta*** yet. I'm sorry for that. And there are more
quite serious *Flux*-related bug reports hanging around too. The situation around *InfluxDB v1.x* vs *InfluxDB OSS v2* vs *Flux* language vs *Grafana* should be clarified to the people who are looking forward to use the *Flux* language in *Grafana* for the *Flux* language is with us for quite a long time (IMHO). Thanks.

**Environment**:

- Grafana version: v7.1.1
- Data source type & version: *InfluxDB* (core, beta), *InfluxDB Flux [beta]* plugin too (the latter is broken completely atm.)
- OS Grafana is installed on: *CentOS v8*
- User OS & Browser: *Fedora*, *Firefox*
- Grafana plugins:

  ```sh
  # grafana-cli plugins ls
  installed plugins:
  grafana-influxdb-flux-datasource @ 7.0.0
  ```

- Others:

  ```sh
  # influxd2 version
  InfluxDB 2.0.0-beta.15 (git: f54848f443) build_date: 2020-07-23T18:27:19Z
  ```

**Comment by torkelo** [comment]
Sorry to read this, we will try to put more effort into this. We have more work on flux coming up in 7.2 

Template variable queries:
https://github.com/grafana/grafana/issues/26357

Issue with max data points
https://github.com/grafana/grafana/issues/26484

Do you have any other issue to report? some error or query that does not work?

**Comment by mjf** [comment]
@torkelo `|> yield(name: "something")` seems to have no effect, for example. (But, should it have? Is it a feature and are we supposed to do overrides or something? There is no good documentation for the data source yet...)

The issue is rather general (IMHO). The *Flux data source* is simply not working and broken in many ways. It should be at least carefuly reviewed and consulted with the *InfluxDB OSS v2* documentation. Working variables are a must to have in most cases! I would recomment to embed the syntax highlighting editor for variables too. There is also some bug with variables UI that you loose your query already saved if something fails.

The simplest *Flux* queries "somehow" work for panels (at least not throwing an error), anything more complex fails (but works in *InfluxDB OSS v2* as such). The data source should provide at least the same functionality as the *InfluxQL data source*.

From my point of view there is no need for UI tweaking (simple editor with syntax highlighting is good-enough to start with, just embed it for dashboard variables too, please). Concentrate on pure functioning and documentation.

**Comment by torkelo** [comment]
Do you have an example of a query that does not work?

**Comment by mjf** [comment]
@torkelo Concerning the variables... I realized that the data source does not accept returns without the time column (as well as if one wanted to create a table panel and do something with it like using links etc., you can not). I can easily get the desired list in *InfluxDB WUI*'s *Data Explorer* but not in *Grafana* ending in `no time column in timeSeries` even in table panel. Sample query may be (redacted):

```js
import "strings"

from(bucket: "${bucket}")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) =>
        r["_measurement"] == "${measurement}" and
        r["host"] == "${host}" and
        r["title"] != "")
    |> keyValues(keyColumns: ["title"])
    |> keep(columns: ["_value"])
    |> unique()
    |> map(fn: (r) =>
        ({
            r with _value: strings.replaceAll(v: r["_value"], t: "/", u: "\\/")
        })
    )
```

At least for the dashboard variables (once working) it could make sense (IMHO) to be able to get the values only, without the time column. But I may be wrong. I do not understand the *Grafana*'s internals enough yet (BFU).

(OT: this painful *Flux* way we are trying to somehow workaround another long-pending issue/feature request #5329 by abusing collector to create regular expressions and store them in *InfluxDB* such a way that they still look quite pretty in panel titles and a variable could be created for *Flux* matches where the slashes must be, of course, escaped, but only the slashes. There is no `${variable:escape_only_slashes}` yet in *Grafana*.) :smiley:

**Comment by coussej** [comment]
@torkelo I believe these ones will also be relevant for Influx v2:

v.windowPeriod in alerting: 
#26695

Clean up logging:
#26848

**Comment by MatinF** [comment]
I think the ability to use Grafana variables and templating with Flux is vital. We would like to use InfluxDB Cloud 2.0 with Grafana Cloud. This seems like a great combination for our use case, yet it's hindered by the lack of variable support. There seems to be a PR for this, but not sure what the ETA is for getting this resolved?

**Comment by aknuds1** [comment]
What's the main problem, the Flux language or InfluxDB v2? I.e., do you have the same problems with InfluxDB v1.8 and the Flux language?

**Comment by aknuds1** [comment]
@torkelo Are the bugs here located in the back-end code?

**Comment by MatinF** [comment]
The tests I have performed were done with the following setup:
1) Registered free user on InfluxDB Cloud 2.0 (which uses Flux)
2) Registered Grafana Cloud starter user 
3) In Grafana connected to my InfluxDB Cloud 2.0 data source with Flux settings

When doing the above, basic Flux queries work, e.g. below:

```
from(bucket: "test-bucket-new")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "958D2219")
  |> filter(fn: (r) => r["_field"] == "EngineFuelRate")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```
However, if I create a simple ad hoc variable list with values to replace the hardcoded `_measurement` value, `958D2219`, then it won't work. Instead, only part of the characters seem to be parsed, see below query and screenshot:

```
from(bucket: "test-bucket-new")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == ${devices_v2})
  |> filter(fn: (r) => r["_field"] == "EngineFuelRate")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```
![image](https://user-images.githubusercontent.com/26184427/90165078-6fe0ea80-dd98-11ea-9e9f-58d491f3b978.png)

![image](https://user-images.githubusercontent.com/26184427/90165110-7a02e900-dd98-11ea-803a-f6a38037fda5.png)

As a start, fixing this downside would be great. As a 2nd step, being able to use Flux queries in the variable generation settings would be ideal.

**Comment by kchervonets** [comment]
@aknuds1 I created this bug https://github.com/grafana/grafana/issues/26814 but then closed it because the current one mentioned the variables, I was not able to create them at all.

**Comment by MatinF** [comment]
Is there any other information that we can provide to ensure this proceeds? We wish to release our guide towards our users for setting up Grafana Cloud + InfluxDB Cloud, but this is currently blocking that release

**Comment by MatinF** [comment]
It seems with the latest commits, it is now possible to use Flux queries to display selected variables. 

It would be great with documentation on how to achieve the following:

1) To create variables via Query using Flux. For example, I can use InfluxQL with the query `SHOW MEASUREMENTS` to create a drop-down with all measurements listed. But it is unclear how to achieve this via Flux

2) If using the below Flux query, I get the expected result when selecting one variable value at a time - but if selecting multiple values at the same time, I do not get the expected result. A Flux query example with multi-select variables would be very helpful:

```
from(bucket: "test-bucket-new")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "${devices}")
  |> filter(fn: (r) => r["_field"] == "WheelBasedVehicleSpeed")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

**Comment by nanicpc** [comment]
for using the template variables on queries i did this:
`
|> filter(fn: (r) => r["field_name"] =~ /^${template_variable}$/)
`

but the variables themselves I had to  get them from other source.

but it doesn't work with multiple values and only works with all if you put "all" as *

**Comment by MatinF** [comment]
I managed to get Flux variables working "so-so" by using the Custom variables type and adding my measurement entries manually. It's a short-term fix, though it would be more professional to be able to use an InfluxDB query to simply list my measurements - though I've had no luck with that.

As you say, I've also been unable to handle the multiple template variables from Flux - I would assume, though, that by using the "right query" it would be possible to make the query flexible enough to handle multiple entries. It would make it far more versatile for various use cases.

**Comment by MatinF** [comment]
Quick update: I'm still unable to get Flux queries to yield Variable Lists in Grafana. However, I solved the multi-variable usage in my Flux query as follows:

```
from(bucket: "test-bucket-new")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => contains(value: r["_measurement"], set: ${devices:json}))
  |> filter(fn: (r) => r["_field"] == "WheelBasedVehicleSpeed")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

**Comment by peterholmberg** [comment]
@MatinF has this been resolved with ryans fix?

**Comment by MatinF** [comment]
Yes, I am now able to use Flux queries to create variable lists in Grafana, so this issue can be closed.

My main pending issue with Flux in Grafana is on the Alerts, where I'm unable to get it set up correctly - and there are no clear guides on how to set up a proper query panel when one wants to use alerts. I've described that issue here: https://github.com/grafana/grafana/issues/26695

**Comment by peterholmberg** [comment]
Thanks for updating us!
