### ISSUE TITLE
SimpleJson data source: Selection of metric is not possible

### ISSUE THREAD

**Issue by faarbaek** [grafana/grafana#26783]
**What happened**:
The drop down for selecting metric for a SimpleJson datasource  is not shown in the "Edit panel" view (when adding/editing query
![image](https://user-images.githubusercontent.com/17161470/89299305-bfbc0500-d666-11ea-955c-e88dd40a5eb1.png)

**What you expected to happen**:
That the drop down was visible and a list of available metrics was shown.

**How to reproduce it (as minimally and precisely as possible)**:
Create a SimpleJson data source. Then create a new dashboard, select "new panel". Select the SimpleJson data source. Drop down to select metric is not shown.

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 7.1.1 (has been an issue since version 7.0.4)
- Data source type & version: SimpleJson
- OS Grafana is installed on: Official docker image running in Azure App Service
- User OS & Browser: Windows/Chrome 84.0.4147.89
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,grafana-azure-monitor-datasource,natel-plotly-panel,goshposh-metaqueries-datasource,ryantxu-ajax-panel,grafana-worldmap-panel,simpod-json-datasource
- Others:

**Comment by aknuds1** [comment]
Please rewrite the issue description using our standard template.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/simple-json-datasource

**Comment by torkelo** [comment]
https://github.com/grafana/simple-json-datasource/pull/156 

will publish 1.4.1 soon

**Comment by torkelo** [comment]
1.4.1 published https://grafana.com/grafana/plugins/grafana-simple-json-datasource 

please report if it solved this issue

**Comment by tynor88** [comment]
@torkelo I can confirm it works again in Grafana 7.1.1. Thanks for the fix!
