### ISSUE TITLE
CloudWatch Logs Insights Panels: rendered Links do not interpolate Log Group variable.

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#26792]
**What happened**:
Created a variable for log group and applied to cloud watch logs insights queries/panels. The links to CloudWatch do not interpolate the variable.

**What you expected to happen**:
The variable should be interpolated in the rendered links to CloudWatch.

**How to reproduce it (as minimally and precisely as possible)**:
The attached screenshot shows the configuration causing the problem. Simply put Log Groups in a variable and use it in a panel. The rendered links do not interpolate the variable. I tried `$LogGroup` and `[[LogGroup]]` syntax. 

![Screen Shot 2020-08-04 at 2 12 44 PM](https://user-images.githubusercontent.com/2402929/89346799-81224c80-d65e-11ea-8fc8-fcbd3ee03d12.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Tested on Grafana 7.1.0 and 7.1.1.
- Data source type & version: CloudWatch
- OS Grafana is installed on: ECS/Fargate
- User OS & Browser: Chrome/Safari
- Grafana plugins: Quite a few

Related: [#25604 CloudWatch Logs: Adds template variable support to log groups](https://github.com/grafana/grafana/pull/25604)

**Comment by mchene** [comment]
@kaydelaney

**Comment by mchene** [comment]
Seems to be similar issue than https://github.com/grafana/grafana/issues/25099.
