### ISSUE TITLE
Standardize the admin role names

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#26790]
**What would you like to be added**:

The documentation and UI currently use a variety of terms to describe admin roles:
* Admin user
* Server admin
* Grafana admin  (this is the flag you set in the server config)
* Super admin 
* Organization admin

In reality we have two real admin roles:  grafana and org admin, but we do not really want to promote "Org admin" as a common term as we figure out what to do with orgs.

I suggest we use:
* Server admin -- this use has access to the "Server admin" page
* Admin -- this role has access to the "Configuration" page within an org

**Why is this needed**:

So we have consistent terms in the UI and documentation that are easy to explain

**Comment by ryantxu** [comment]
cc: @oddlittlebird

**Comment by oddlittlebird** [comment]
I fully support this. We currently call the Server admin "Grafana Admin," which is both vague and confusing. Ryan's proposed change would make things simpler and easier to understand.

**Comment by torkelo** [comment]
:+1:

**Comment by ndeevy** [comment]
Hi @ryantxu  Could I try to tackle this issue?

**Comment by achatterjee-grafana** [comment]
@oddlittlebird, do you want to take this up as you have most recently worked on users roles etc.

**Comment by oddlittlebird** [comment]
This change needs to happen in the Grafana UI, then the docs will be changed. I have already removed "super admin" and everything else similar, but "Grafana Admin" is in the UI. It should be Server Admin.

**Comment by ryantxu** [comment]
Closing... i'm sure we will revist
