### ISSUE TITLE
Grafana dashboard viewing is different on chrome and IE browser and due to it it shows something extra on IE browser

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#26793]
**What happened**:Grafana dashboard viewing is different on chrome and IE browser and due to it it shows something extra on IE browser

**What you expected to happen**:format should be same in both the brower

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.1.0
- Data source type & version:SQL Server 2017
- OS Grafana is installed on: desktop
- User OS & Browser:IExplore and Chrome
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Please fill in the sections of the issue template.

**Comment by karamjeetkaurpreeti** [comment]
> Please fill in the sections of the issue template.

Added

**Comment by aknuds1** [comment]
You need to fill in more details about how to reproduce, which differences you are seeing and the browser versions.

**Comment by torkelo** [comment]
> format should be same in both the brower 

What do you mean? 

Please elaborate

**Comment by karamjeetkaurpreeti** [comment]
it it shows something extra on IE browser

On chrome mostly it does not show the menu and the time filter

**Comment by torkelo** [comment]
ok, "extra". that is very informative.

Now... can you describe this "extra" in more detail? 

But closing this as Grafana does not support IE anyway (only Edge)

**Comment by karamjeetkaurpreeti** [comment]
Is there any customized setting we can do on internet explore so that it will show same result on both the brower.
