### ISSUE TITLE
Upgrading from 6.6.2 -> 7.1.1. Table panel no longer features "Rows displayed per page" setting

### ISSUE THREAD

**Issue by dannyman00123** [grafana/grafana#26801]
**What happened**:
Upgrading table panels from default to the 7.1.1 Table Panel now shows all records returned with a scroll bar.

**What you expected to happen**:
Old setting of "Rows per page" vs "Scroll" to still be available

**How to reproduce it (as minimally and precisely as possible)**:
Create any table panel 

**Anything else we need to know?**:
Not necessarily sure this is a bug, this is probably intentional so I apologise if this isnt a bug.

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: Clickhouse 
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome, Firefox
- Grafana plugins: Standard Table Panel
- Others:

**Comment by torkelo** [comment]
the new table panel has a virtualized scrolling so pagination is no longer needed for performance reasons:

there is a feature request to add back pagination 
https://github.com/grafana/grafana/issues/26022

**Comment by Aricliang** [comment]
#26022
