### ISSUE TITLE
`noDataFound` will be always true if the first condition got no data and all `Operator`s are `or`

### ISSUE THREAD

**Issue by Alex-Hou** [grafana/grafana#26802]
**What happened**:

NoData Alert triggered when only the first condition got no data.

**What you expected to happen**:

Trigger the alert according to other conditions that already have data.

**How to reproduce it (as minimally and precisely as possible)**:

- set multiple alert  conditions and set the operators to `or`
- let the first query return empty result

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version: victoria metrics
- OS Grafana is installed on: linux
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

https://github.com/grafana/grafana/blob/754668cd518f74a1ac910e4725ad2ed0ddc31e1c/pkg/services/alerting/eval_handler.go#L50-L56

![image](https://user-images.githubusercontent.com/8463839/89412691-16eed200-d75a-11ea-8159-7b8694755f4d.png)

**Comment by torkelo** [comment]
@bergquist this looks like a bug?

**Comment by marefr** [comment]
Based on the existing tests seems like the implemented logic is the opposite according to what you suggest:
https://github.com/grafana/grafana/blob/cc42a91c99dabc81c4811067e79c63001dc97d37/pkg/services/alerting/eval_handler_test.go#L185-L207

At first I didn't think it was a bug. But after consideration it would make most sense to change the logic for no data:
```go
if cr.Operator == "or" {
	firing = firing || cr.Firing
	noDataFound = noDataFound && cr.NoDataFound
} else {
	firing = firing && cr.Firing
	noDataFound = noDataFound || cr.NoDataFound
}
```

The risk is that no data problems wouldn't be noticed. 

@torkelo @bergquist pinging you here to confirm we should change this.

**Comment by jessabe** [comment]
We are going to go ahead and close this issue, as Alerting NG should soon be fixing this. Please let us know though if you'd like us to have a look at it again, though.
