### ISSUE TITLE
Alias patterns broke in 2.1.3

### ISSUE THREAD

**Issue by mabushey** [grafana/grafana#2680]
The Alias patterns info box expands to show "$tag_hostname = replaced with the value of the hostname tag" and "You can also use [[tag_hostname]] pattern replacemant syntax". Putting either of these in the "Alias pattern" text box just results in the literal text of "$tag_hostname" or "[[tag_hostname]]" in the legend. If I group by host and I have 10 servers, I get 10 "undefined" items in the legend.

**Comment by torkelo** [comment]
Cant replicate this. I test with v2.1.3 and master and `$tag_<tagname>` works fine with InfluxDB 0.9.3

![image](https://cloud.githubusercontent.com/assets/10999/9668127/0af14c12-5280-11e5-9fc5-28c2c639c8b5.png)

Are you sure you have grouped by the hostname tag?

**Comment by mabushey** [comment]
Thanks for the info! I was able to figure out that [[tag_host]] and $tag_host are correct, not [[tag_hostname] or $tag_hostname.

**Comment by areski** [comment]
![image](https://cloud.githubusercontent.com/assets/53455/23703131/a5dc85da-03fe-11e7-9b84-50b104a88b81.png) I suppose it's still need to be replaced in the alias patterns info.

**Comment by daniellee** [comment]
@areski what need's to be replaced? $tag_hostname to $tag_<tagname>? (hostname is just an example tag name).

**Comment by areski** [comment]
@daniellee you are right it s just an example, false alert, all good then

**Comment by gjuric** [comment]
Since I got stuck on this one as well I propose that `$tag_hostname` in the alias pattern info be replaced with:

```
$tag_example_tag = replaced with the value of the <i>example_tag</i> tag
```

**Comment by daniellee** [comment]
@gjuric good idea. Done - fb99ddf2955e60551cbaae23e358ee4e33136e1c
