### ISSUE TITLE
Time/date unit hides today's date

### ISSUE THREAD

**Issue by Revellski** [grafana/grafana#26803]
**What happened**:

Convert field of EPOCH milliseconds to date/time unit. If date matches today's date, YYYY-MM-DD is omitted.

**What you expected to happen**:

When using date/time unit of type _YYYY-MM-DD HH:mm:ss_ or _MM/DD/YYYY h:mm:ss a_ one would expect literal use, f.e.:

1970-01-01 00:00:00

**How to reproduce it (as minimally and precisely as possible)**:

1. Select field with value current time in EPOCH timestamp
2. Overrides > Select Unit **Date & Time** >  _YYYY-MM-DD HH:mm:ss_ OR _MM/DD/YYYY h:mm:ss a_
3. If timestamp matches today's date, YYYY-MM-DD bit is omitted.

![grafana](https://user-images.githubusercontent.com/15960896/89413045-ca42d100-d730-11ea-9ab6-98a93ce3b49d.gif)

**Anything else we need to know?**:
This causes inconsistent view for multiple dates when some matche today's day.

**Environment**: 
- Grafana version: 7.0.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: CentOS 7
- User OS & Browser: FF 78.0.2
- Grafana plugins: n/a
- Others: n/a

**Comment by torkelo** [comment]
There is a special logic for this format that hides date if it's today. 

You can override this by specifing `time:YYYY-MM-dd HH:mm:ss` in the unit picker
