### ISSUE TITLE
Allow creating a dashlist of scripted dashboards

### ISSUE THREAD

**Issue by eliperelman** [grafana/grafana#2681]
It appears that only database dashboards can currently have entries in a dashlist. It would be nice if you could specify a dashlist type of scripted and add entries to it. Either that, or having a generic dashlist which is a collection of URLs.

Thoughts?

**Comment by matschaffer** [comment]
Would also appreciate this.

Being able to save scripts as database dashboards seems like a possible route.

Of course such a feature should probably be restricted a bit since it's basically javascript injection as a feature.

**Comment by mtanda** [comment]
+1

If Grafana can return JSON result of scripted dashboard, we can use this work around.
https://github.com/grafana/grafana/issues/791#issuecomment-123182273

**Comment by anryko** [comment]
+1

**Comment by IzakMarais** [comment]
+1

**Comment by torkelo** [comment]
scripted dashboards (as they are today) will likely be deprecated and replaced with something that is stored in db (but solves same dynamic use case). So closing this
