### ISSUE TITLE
Export users and teams

### ISSUE THREAD

**Issue by i0x71** [grafana/grafana#26813]
Hi,
It would be great to have a way to export all your teams and users.

Thanks

**Comment by torkelo** [comment]
export in what format? there are HTTP APIs you can use

**Comment by torkelo** [comment]
Think there could be some generic backup and restore feature?

**Comment by i0x71** [comment]
Im just looking for a way to migrate users between grafana instances rather than have to manually setup per dashboard permissions/teams/users
