### ISSUE TITLE
datasource - secure json data storage

### ISSUE THREAD

**Issue by jbguerraz** [grafana/grafana#26822]
Hello!
First of all, thank you for Grafana! :+1: 
JSONData and SecureJSONData storage are not the same. Secure one is accepting only a _simplified JSON_ (`map[string]string`) while the JSONData one accepts _full JSON_ (`map[string]interface{}`}.
Is there a good reason about it ? or could both secure and non secure storages be _full JSON_ (`map[string]interface{}`) ?
We're now working on a  datasource plugin for Druid and this limitation is making things more complex than _it should_

**Comment by torkelo** [comment]
The UI needs to know what secure properties have been set (to show that), it's for storing secrets, so there should be no need for storing complex objects 

secure properties are never returned to the frontend, but frontend still need to know what has been set. 

Could you provide a reason for storing complex objects encrypted?

**Comment by jbguerraz** [comment]
Hi @torkelo 
Thank you for your answer!
We added a tab on data source settings to configure some query related defaults, using the same component we can then find when editing a query.  So we have two sections, "Connection" and "Query", we wished to store connection related data (object) into `JSONData.connection`,  connection related secure data in `SecureJSONData.connection` and then query's related data into `JSONData.query` and, you got it, query's related secure data in `SecureJSONData.query`.  So basically this is comfy for easy isolation. We can use a prefix to workaround it (but we then need processing data at writing and reading), but since that was not obvious that SecureJSONData would not allow JSON storage, I diged deeper, noticed the golang code and tadam, here we are :)

**Comment by torkelo** [comment]
the whole point of secureJSONData is that is not accessible in the browser, only by the backend tsdb & proxy layers.  

How would use use the SecureJSONData.connection and SecureJSONData.query objects? is this a backend plugin?

**Comment by jbguerraz** [comment]
Yes, from backend.

**Comment by jbguerraz** [comment]
@torkelo @marefr what kind of additional information / evidence would you need?

We've already implemented a workaround, so that's pretty good now, but, FWIW, a few thoughts to share:
anyway it needs some action IMHO, either we think the secure data could be a JSON object, then its storage should become a `map [string] interface {}` or we think it couldn't (or shouldn't) be a JSON object but string key/value pairs, so we'd better name it `SecureKVData`, this way it's self-explanatory / obvious that you can't store secure JSON but secure key / value pairs (the main pita here is time wasted trying to figure out why a JSON storage wouldn't store any JSON).
