### ISSUE TITLE
Elasticsearch term filter results all named "Count" in bar gauge panel

### ISSUE THREAD

**Issue by matthenning** [grafana/grafana#26826]
**What happened**:

When using a term filter query with a bar gauge panel the alias pattern is ignored and every column is named "Count"

![panel_config](https://user-images.githubusercontent.com/5699183/89520524-47784f80-d7de-11ea-9bf0-db5969f5a714.png)

**What you expected to happen**:

I expect the columns to have the name shown in the query preview:

![preview](https://user-images.githubusercontent.com/5699183/89520572-54953e80-d7de-11ea-8515-f0d450013a8e.png)

**How to reproduce it (as minimally and precisely as possible)**:

See panel config in screenshots

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version: Elasticsearch 7.8.0
- OS Grafana is installed on: RHEL 7.5
- User OS & Browser: Win 10, Chrome 83.0.4103.116 (Official Build) (64-bit)
- Grafana plugins: 
```
# grafana-cli plugins ls
installed plugins:
agenty-flowcharting-panel @ 0.9.0
briangann-datatable-panel @ 1.0.2
btplc-peak-report-panel @ 0.2.4
btplc-status-dot-panel @ 0.2.4
btplc-trend-box-panel @ 0.1.9
farski-blendstat-panel @ 1.0.2
grafana-image-renderer @ 2.0.0
corpglory-multibar-graph-panel @ 0.2.3
grafana-piechart-panel @ 1.6.0
grafana-polystat-panel @ 1.2.0
michaeldmoore-annunciator-panel @ 1.0.5
michaeldmoore-multistat-panel @ 1.4.1
natel-discrete-panel @ 0.1.0
natel-plotly-panel @ 0.0.6
petrslavotinek-carpetplot-panel @ 0.1.1
snuids-radar-panel @ 1.4.4
vonage-status-panel @ 1.0.9
yesoreyeram-boomtable-panel @ 1.3.0
```
- Others:

**Comment by matthenning** [comment]
The issue doesn't seem to be bound to the visualization type but rather to the terms filter.
Pie charts are getting no data at all.
Could it be related to the fact that the aggregations are not present in the field list?

![image](https://user-images.githubusercontent.com/5699183/89537189-46a0e700-d7f9-11ea-9134-07d84a317293.png)

**Comment by torkelo** [comment]
could be related to https://github.com/grafana/grafana/issues/25343 

you should be able to fix this with a display name (in field tab): `${__cell_0}`

This is a temporary solution, we want a better automatic solution

**Comment by matthenning** [comment]
Thank you, that workaround works for now.

**Comment by lukejs97** [comment]
I'm confused, why does putting `${__cell_0}` in the Display Name work? For me it causes the chart to say "No data". I'm using a piechart and grouping the counts of each text value for a single field. I'm guessing I have to use something other than "__cell_0", but I can't tell what that would be from the context. Here's what I'm seeing:
![piechart](https://user-images.githubusercontent.com/59946439/170712280-b08cc0e5-1c80-41fe-8ae4-337638bb2a90.png)
