### ISSUE TITLE
"Replace all fields" only works for a single Transform

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#26834]
**What happened**:
Added four series to a Graph panel, then added two Transforms: A+B and C+D. Both transforms have a "Replace all fields" button... but when I click on one of these "Replace all fields" buttons, it makes _all_ other series invisible, not just the series involved in this particular transform. 

One net result of this behavior is that we cannot use "Replace all fields" for more than one transform.

Video recording of issue:
![transform-replace_all_fields-bug](https://user-images.githubusercontent.com/10763196/89546562-ba7bc900-d7d2-11ea-898e-af578aab6a3f.gif)

**What you expected to happen**:
Customer and I expected:

- "Replace all fields" should only make the input series _in that transform operation_ invisible
- "Replace all fields" could then work on more than one transform

**How to reproduce it (as minimally and precisely as possible)**:

- create new dashboard graph panel with 4 series
- create two "Binary operation" transforms: A+B and C+D
- toggle the "Replace all fields" button for one then both of these transforms

**Anything else we need to know?**:
More justification for this change...
Customer comment:

> what you described is exactly my understanding of what was occurring. When I selected the "Replace all Fields" I anticipated that the queried data would disappear, but that my transform data would remain. The way I designed my data for Grafana was to easily group like values together, so splitting into multiple queries does go against the logic I designed my source data table with. When I think about how that logic would have to be strung together, it does seem easy for an undesired output to be chosen. Maybe a feature or tool that toggles display would be a good solution to the replace the "Replace all  Fields" button. Something similar to an override where you can select the visibility of a metric maybe?

my response:

> from my perspective, it seems like the "Replace all fields" button should only replace the input series _for that transform_. That seems more desirable & flexible than making all other series invisible, whether or not they were involved in that transform... if a user wants to do that, they have other ways of accomplishing that
> 
> whereas with the current functionality of this button, it is not possible to accomplish what you are trying to do (making more than one transform visible while hiding their input series)

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: TestData

**Comment by ethirolle** [comment]
ZenDesk reference: ticket 15220

**Comment by torkelo** [comment]
The transforms are applied in order, so if you have a transform first in the chain with replace all fields checked. Then the second transform will not have any fields to operate on (besides the field resulting from the first add field calculation transform). 

If you want to add multiple chained add field calculation transforms and then filter out fields. Adda  "Organize fields" as the last transform
