### ISSUE TITLE
Investigate storing dashboard JSON base64 encoded or as a blob

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#26836]
**What happened**:
We store dashboard JSON in the database as un-encoded text, which is troublesome since encoding issues can occur (e.g. because the JSON isn't purely encoded in UTF-8), leading to data loss/corruption. To avoid such issues, and ease troubleshooting, we should store dashboard JSON base64 encoded instead. To support existing databases, we should add a column with base64 encoded content and support also databases lacking content in this column.

As an alternative we could also consider storing JSON in a blob type column instead, to avoid the whole text encoding problem.

We also need to figure out if there's any need to query the dashboard JSON directly as text.

Furthermore, I think we should test that the JSON is valid before storing it in the database, so we can be certain that what gets stored can also be deserialized. Could it be an option to store BSON (MongoDB uses this), or some other binary format for space efficiency and ensuring validity?

**Comment by bergquist** [comment]
The Blob idea sounds interesting. I think that should be backward compatible and make it easier to extract all dashboards. We should definitely test that before we make any decision.

**Comment by ying-jeanne** [comment]
For now i am going to close the issue, since the design was there since a while, there is no clear evidence that it causes a lot of issue. If it causes any problem in the future, please attach the use case and feel free to reopen the issue. :) glad to do some improvement after the use cases.
