### ISSUE TITLE
Make $__interval accessible from interval variables 

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#26832]
**What would you like to be added**:

Make it possible to use variables / the `$__interval` variable in other variables, especially the interval variable type.

OR

<del>Allow the `$` character to be passed from a variable to the final query. Currently characters like `$` and `\` are removed from the interval variable type, as you can see in the screenshot.</del>

(It is possible to use $ in a variable. It is just that function/method, whatever does the expansion, only goes through the string once)

![image](https://user-images.githubusercontent.com/24834206/89540558-7c47cf00-d7fd-11ea-8a8a-ba301a4ddbbe.png)

This would allow the usage of the `$__interval` variable alongside a few fixed intervals like `15m` and `1h`.

**Why is this needed**:

The global variable `$__interval` ensures that there are never more datapoints than pixel. This prevents over/underfetching and gives us always the highest resolution no matter how far zoomed in or zoomed out we are.

This is a very nice behavior (ignoring all the stuff around `rate` in Prometheus) but sometimes when I come across a graph like in the next screenshot I would like to average the data over a longer interval. For example 10 minutes. Currently I have to either change the value manually if I am using `$__interval` or forgo it completely and use custom interval variables only, which are not as good as `$__interval` at ensuring the best possible resolution.

![image](https://user-images.githubusercontent.com/24834206/89541290-7b636d00-d7fe-11ea-89ef-c0a6a60fa68f.png)

![image](https://user-images.githubusercontent.com/24834206/89541322-83bba800-d7fe-11ea-812c-c02f02cca44e.png)

With the proposed enhancement I could use `$__interval` as the default value and if the need arises quickly increase the range to get a more smoother graph.

I could of course put a variable into the `min step` but this would lead to underfetching in combination with `$__interval`.

**Comment by torkelo** [comment]
interval only makes sense on the panel level as only there do we have things like max data points, and options for how to divide the time range

**Comment by trallnag** [comment]
Ah and Grafana probably expands variables in a single run before sending it off to the data source? So the following is not possible even if `$__interval` could actually be a valid variable value.

```
rate(metric[$myinterval])
-> rate(metric[$__interval])
-> rate(metric[<whatever is calculated>])
-> gets send to datasource
```

This would require the variables to be expanded again. What happens instead I assume:

```
rate(metric[$myinterval])
-> rate(metric[$__interval])
-> gets send to datasource which of course returns client error
```

**Comment by torkelo** [comment]
yea, there only a single interpolation pass.

**Comment by trallnag** [comment]
ok I assume the value doesn't outweigh the cost
