### ISSUE TITLE
Reaching files limit in 24 hours

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2684]
Grafana crashes with the following error in every 24 hours. I have 2 grafana instances behind a load balancer on AWS. Both of them crash in about 24 hours. And throw this error:

2015/09/05 19:23:33 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:33 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:33 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:33 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:34 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:34 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:34 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:34 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/0/601be9fd0509a257: too many open files)
2015/09/05 19:23:36 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/8/c/8cdd8eba3f0694dc: too many open files)
2015/09/05 19:23:36 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/c/9/c9d862f882330727: too many open files)
2015/09/05 19:23:39 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/a/6ae0112902f7a805: too many open files)
2015/09/05 19:23:40 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/a/6ae0112902f7a805: too many open files)
2015/09/05 19:23:40 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/a/6ae0112902f7a805: too many open files)
2015/09/05 19:23:40 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/a/6ae0112902f7a805: too many open files)
2015/09/05 19:23:40 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=open /var/lib/grafana/sessions/6/a/6ae0112902f7a805: too many open files)

Are we not closing the HTTP connections in the code somewhere? I am not sure.

**Comment by utkarshcmu** [comment]
I am not sure whether its a legitimate bug or not. Or am I missing any setting on my linux box?

**Comment by Dieterbe** [comment]
the `lsof` utility can provide more info on open files.
can you try `lsof -p <pid of grafana>` ?

**Comment by torkelo** [comment]
@utkarshcmu strange, how many users are there? Any usage of the HTTP api by automation tools? (The http api authenticated with api token should not create sessions, but could be a bug). 

The sessions folder should be automatically cleaned. But if you have more than 1000 users who use Grafana within the session time limit you could hit the default Linux open file limit of 1024.

Google ulimit linux open files  to learn how to raise the limit.

**Comment by torkelo** [comment]
Also did not notice it the first time I read your issue. Since you are using 2 INSTANCES of Grafana you MUST change the session store from the default FILE based to something that works in a distributed (multi instance) setup. 

You can use MySQL or Redis or Postgres as session store.
