### ISSUE TITLE
AzureMonitor: support for Azure Stack

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#26842]
**What would you like to be added**:

Support for Azure Monitor queries for an Azure Stack instance.

**Why is this needed**:
This is the last cloud type that the Azure Monitor plugin doesn't support yet (already have support for public Azure, Azure China, Azure Gov and Azure Germany).

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can't see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
