### ISSUE TITLE
Useless logging from (In)Flux datasource

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#26848]
Logs are being filled with, useless info-level entries (>1/s) from the flux datasource (with just the pointer to the query). This pollutes the logging of actual useful information.

<img width="747" alt="image" src="https://user-images.githubusercontent.com/9944663/89615579-38011100-d887-11ea-8346-91668566de2d.png">

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: InfluxDB

**Comment by aknuds1** [comment]
Looks like this should be debug level logs at least, looks too verbose for info.

**Comment by aknuds1** [comment]
Made a [PR](https://github.com/grafana/grafana/pull/26850) for this.
