### ISSUE TITLE
Enhancement request： the zipkin datasource support mutiple dimension query.

### ISSUE THREAD

**Issue by czs1993** [grafana/grafana#26846]
**What would you like to be added**:
1、Zipkin Data Source supports multi-dimensional query criteria such as Tags, remoteServicename, minDuration, maxDuration, spanname, etc
2、Zipkin Data Source supports Dependencies query。

**Why is this needed**:
Actually integrating Trace queries through Grafana without having to deploy another Zipkin UI service,

**Comment by davkal** [comment]
Which of the dimensions do you most care about. Which ones do you rarely use? @czs1993

**Comment by czs1993** [comment]
SpanName、Tags 、Duration  are more useful for locating problems.
