### ISSUE TITLE
Y-axis tick marks too coarse when using unit "percent (0-1.0)" with no decimals

### ISSUE THREAD

**Issue by rvdheij** [grafana/grafana#26857]
**What happened**:
Using a chart for percentages in the 0.0 - 1.0 range, so that unit is appropriate for the Y-axis. This shows the values on the Y-axis as 25.00% which is a bit silly. When I specify "Decimals: 0" it drops the tick marks at 25, 50 and 75% but only shows 0% and 100% (without the .00 though).
![image](https://user-images.githubusercontent.com/11174694/89634425-a81e8f80-d8a5-11ea-9664-eb45044b02d9.png)
![image](https://user-images.githubusercontent.com/11174694/89634469-bec4e680-d8a5-11ea-9fbe-3327be9845ed.png)

**What you expected to happen**:
I expect the Y-axis to be divided into 4-5 parts with tick marks and numbers. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
It appears the logic around the formatting of the numbers is done with a mix of raw values (between 0 and 1) and the scaled values (0-100).

**Environment**:
- Grafana version:- 7.0.3

**Comment by aknuds1** [comment]
Can you please try with the latest Grafana, 7.1.3, and see if you still have the problem?

**Comment by rvdheij** [comment]
Will do, thanks.
PS I can bypass with a math(*100) and then use "percent (0-100)" as the unit. It also helps to set Y-Max to 1.1 (giving me 60.0% etc which is less silly).

**Comment by rvdheij** [comment]
Hej Arve, it's also in version=7.1.3 commit=5723d951af
While playing with it, I see the discontinuity is when the specified number of decimals goes from 1 to 0. With 1 decimal I still have the range in 5 major intervals, with 0 decimal it falls to one interval.

**Comment by torkelo** [comment]
This unit is messing with the graph decimals and ticks logic. Can you multiply by 100 and use the other percent unit?

**Comment by rvdheij** [comment]
Yes Torkel, as stated I can work around the issue by multiplying with 100 and using the other unit. This one was convenient because my metrics are in seconds, so the non_negative_derivative over 1 second came handy.
I opened the issue because I figured you might want to clean this up, not because I'm out of options. Maybe the 0.0-1.0 showing 0-100 wasn't such a brilliant design after all.

**Comment by belm0** [comment]
this bugs still exists in v7.2.0, please remove "needs more info"

the problem is this:  "Decimals" is being applied to _both_ the source value (before conversion to display value) and the display value formatting.

E.g. for "percent (0-1.0)" unit, "Decimals:2", and source value of .12345:
  * source value will be rounded to 0.12
  * source value will be converted (x100) to 12
  * display format will also be told to use 2 decimals, yielding "12.00 %"

This is not expected.  It's expected that "Decimals" is applied to the final display value only.  In the example above, expected output is "12.34 %".

**Comment by rvdheij** [comment]
I've simply avoided using the feature since it was attracting more surprises than I needed. For example, do thresholds apply to the 0-1.0 value or the 0-100 value? What will the hover-over display show?
Because of issues with the derivative() function in InfluxDB, I have been moving away from counters and mostly use gauge-type metrics for the charts. When I have to add logic to compute the ratio, I can add the factor in as well for the percentage.
I would not mind to see the "0-1.0" unit get deprecated.

**Comment by gelicia** [comment]
This is closed, but I think it is no longer an issue. Percentages do not show decimals by default, and do not require adding 0 for decimal 

Example: https://community.grafana.net/d/krvbzsw/kristina-demos?orgId=1&from=now-30d&to=now&timezone=utc&editPanel=62
