### ISSUE TITLE
Failing upgrade process on postgreSQL from Grafana 6.1 to 7.1.

### ISSUE THREAD

**Issue by philippelegaldeloitte** [grafana/grafana#26856]
**What happened**:
We are experiencing an issue migrating from 6.1 to 7.1. 
The Grafana server runs a Grafana container on K8. DB runs postgresQL Engine version 11.8

msg=“Connecting to DB” logger=sqlstore dbtype=postgres
msg=“Starting DB migration” logger=migrator
msg=“Executing migration” logger=migrator id=“Add is_disabled column to user”
msg=“Executing migration failed” logger=migrator id=“Add is_disabled column to user” error=“pq: column “is_disabled” of relation “user” already exists”
msg=“Exec failed” logger=migrator error=“pq: column “is_disabled” of relation “user” already exists” sql="alter table “user” ADD COLUMN “is_disabled” BOOL NOT NULL DEFAULT FALSE "
msg=“Server shutdown” logger=server reason=“Service init failed: Migration failed err: Failed to roll back transaction due to error: %!s(): pq: current transaction is aborted, commands ignored until end of transaction block”

What is the fix for this issue ? has it been resolved ?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.1 to 7.1
- Data source type & version: postgresQL Engine version 11.8
- OS Grafana is installed on: container running on K8
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Does it also fail if you try to upgrade to v6.7.4?

**Comment by philippelegaldeloitte** [comment]
What are the expected benefits of migrating to v6.7.4 when I want to migrate to 7.1 ?

**Comment by aknuds1** [comment]
The reason we ask you to try upgrading to 6.7.4 first is to see if that also fails. It's a smaller upgrade and presents less changes that could go wrong.

**Comment by philippelegaldeloitte** [comment]
Thank you 

Where can I find the postgreSQL upgrade script to 6.7.4 ? 
Where can I find the postgreSQL upgrade script to 7.1.x ? 
I am worried if I spend time deploying v6.7.4 I can still face the same problem v6.7.4 -> v7.1.x

**Comment by aknuds1** [comment]
You haven't run any particular script to upgrade to 7.1 have you? To my knowledge, to upgrade to v6.7.4 it should be enough to run the new Grafana version on the database, so it migrates the schema. You might want to back up the database first though, just in case something goes wrong.

**Comment by daurelio-deloitte** [comment]
@aknuds1 still the same issue
```
t=2020-08-07T11:34:43+0000 lvl=info msg="Starting DB migration" logger=migrator
t=2020-08-07T11:34:43+0000 lvl=info msg="Executing migration" logger=migrator id="Add is_disabled column to user"
t=2020-08-07T11:34:43+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: Failed to roll back transaction due to error: %!s(<nil>): strconv.Par
```

**Comment by aknuds1** [comment]
OK thanks, then we have at least a smaller upgrade to consider before it goes wrong.

**Comment by aknuds1** [comment]
Don't you get a log message in v6.7.4 though, as to why the migration fails? The failed migration on v7.1 logs such a message.

**Comment by daurelio-deloitte** [comment]
@aknuds1 the logging statement I showed is the upgrade from 6.1.6 to 6.7 as suggested.

**Comment by philippelegaldeloitte** [comment]
@aknuds1 :
Migration from 6.1.6 to 6.6.2 is failing. 

```
                                              
t=2020-08-07T12:04:39+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=postgres                                     
t=2020-08-07T12:04:39+0000 lvl=info msg="Starting DB migration" logger=migrator                                                
t=2020-08-07T12:04:39+0000 lvl=info msg="Executing migration" logger=migrator id="Remove index org_id_epoch from annotation tab
le"                                                                                                                            
t=2020-08-07T12:04:39+0000 lvl=eror msg="Server shutdown" logger=server reason="Service init failed: Migration failed err: Fail
ed to roll back transaction due to error: %!s(<nil>): strconv.ParseInt: parsing \"\": invalid syntax"
```

**Comment by aknuds1** [comment]
@daurelio-deloitte Yes I got that, but it's interesting that the upgrade to v6.7 doesn't log the actual error.

**Comment by philippelegaldeloitte** [comment]
@aknuds1 : Any suggestions as to what should be our next steps ? 
FYI, Grafana metadata is stored in its own database schema.

**Comment by aknuds1** [comment]
@philippelegaldeloitte I think if I were you, I would try to figure out why the user.is_disabled column already exists in your database, since it was only introduced in Grafana v6.3.x (and you are migrating from v6.1.x). Can you simply drop that column from your database schema?

**Comment by aknuds1** [comment]
For more support questions I would ask in the community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io), since it shouldn't be a bug in Grafana (rather there's an inconsistency in your database).

**Comment by marefr** [comment]
We're going to close this based on earlier discussions. 

We suggest you to update the `migration_log` table manually to resolve your current problem:
```sql
update migration_log set success = 1 where migration_id = 'Add is_disabled column to user'
```
