### ISSUE TITLE
Variable __url_time_range does not behave correctly in "render  value as link"

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#26865]
**What happened**:
I've tried to use the ```__url_time_range``` variable inside a table (render value as a link)
**What you expected to happen**:
I expect it to be replaced with something like  ```MyUrl&from=now-6h&to=now``` 
**How to reproduce it (as minimally and precisely as possible)**:
From Grafana playground:
1. get a dashboard with a table [link](https://play.grafana.org/d/Zzlfq17mk/influx-table-merge?editPanel=2&orgId=1)
2. add a formatting option as follows
![image](https://user-images.githubusercontent.com/12230314/89650798-3d7c4c80-d8c3-11ea-8a58-32023d3d0c6c.png)
This is the link I've used, it points to another playground dsh
```
https://play.grafana.org/d/000000137/influxdb-group-by-variable?orgId=1&var-groupBy=datacenter&${__url_time_range}
```
3. Once you open the link, the current time range won't be used in the opened dashboard (last 15, 30minutes or whatever)
4. the link looks like this ```https://play.grafana.org/d/000000137/influxdb-group-by-variable?orgId=1&var-groupBy=datacenter&$%7B__url_time_range%7D```

**Issue**:
Looks like, for this variable, the curly brackets are wrongly converted into an HTML string } → %7D
The same does not happen when using variables like ```__from``` or ```__to``` (ie ```MyUrl&from=${__from}```)

the variable ```__url_time_range``` behaves correctly when used as a panel link (you can put the same link of point 2 as a panel link, it will work correctly

**Environment**:
Grafana Playground, the same happens in Grafana 6.8

**Comment by torkelo** [comment]
This variable is not available in the old table panel. 

This variable is available in data links in the new table panel
