### ISSUE TITLE
Folder names are not shown in the "Recently viewed Dashboards" view at grafana home

### ISSUE THREAD

**Issue by scardena** [grafana/grafana#26869]
**Why is this component needed**:
We have several dashboards with the same name for different environments. They are separated in different "Folders". in the _Recently viewed dashboards_ view, I can see only the name of the dashboards, but since they all have the same name across different folders, it would be nice to have the folder name displayed somewhere, so we can know from what environment is a specific folder, without the need to go to the /dashboards endpoint.
___
 - [ ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
home page
___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by michelengelen** [comment]
Hi @scardena 

Would something like this be what you are looking for?

![Screenshot 2020-08-11 at 10 44 48](https://user-images.githubusercontent.com/32863416/89877007-c2b37a00-dbbf-11ea-8907-e2da38fc3c4d.png)

I would also add a link to the folder title that routes to the dashboard folder of the specific dashboard.

If it is ok, I would commit it and open up a PR

**Comment by scardena** [comment]
@michelengelen looks great! thanks!
