### ISSUE TITLE
Not possible to configure strict_transport_security when running http

### ISSUE THREAD

**Issue by dnmvisser** [grafana/grafana#26867]
I'm running the latest grafana container (7.1.2) behind a TLS terminating load balancer.
The container is running without TLS, on port 3000.

I supply this env var to the container:

```
GF_SERVER_ROOT_URL=https://my.site.org/metrics
GF_SERVER_SERVE_FROM_SUB_PATH=true
GF_SECURITY_STRICT_TRANSPORT_SECURITY=true
GF_SECURITY_STRICT_TRANSPORT_SECURITY_MAX_AGE_SECONDS=31536000
```

But i'm not seeing any HSTS related response headers.

According to https://grafana.com/docs/grafana/latest/administration/configuration/#strict_transport_security:

>Set to true if you want to enable HTTP Strict-Transport-Security (HSTS) response header. This is only sent when HTTPS is enabled in this configuration. HSTS tells browsers that the site should only be accessed using HTTPS.

Which leads me to believe that the HSTS headers will _only_ be emitted when the container itself is running HTTPS?
Is there a way to make this work? Perhaps force HSTS headers for containers that are behind TLS terminating systems?

**Comment by aknuds1** [comment]
Looks like a dup of #26770?

**Comment by aknuds1** [comment]
Closing as dup of #26770.
