### ISSUE TITLE
Unable to import dashboard from Grafana.com

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#26860]
**What happened**:
Error every time on trying to import a dashboard from grafana.com, as captured on this screen:
![image](https://user-images.githubusercontent.com/1184220/89640024-97bae480-d8a6-11ea-9421-523bda9a3780.png)

**What you expected to happen**:
Successful import of dashboard. I don't load from Grafana often, so cannot say which update may of changed it.

**How to reproduce it (as minimally and precisely as possible)**:
'+' menu > Import > paste ID number > Load.

**Anything else we need to know?**:
Proxies through Nginx, but we have been doing that with Grafana for the past 2 years and was previously working.

**Environment**:
- Grafana version: 7.1.3
- OS Grafana is installed on: Ubunti 18.04
- User OS & Browser: Chrome

**Comment by wbrowne** [comment]
Thanks for reporting this issue @bhozar. Would you be able to provide more response information on the `grafana/api/gnet/dashboards/*` call? Also if possible, would you also mind trying to reproduce in a different browser?

**Comment by aknuds1** [comment]
Looking into this.

**Comment by aknuds1** [comment]
I just tried importing the dashboard with ID 12552 (as in your example) with latest master, and it doesn't fail. I tested both with and without nginx proxy. Closing the issue, but please get back to us with more info in case it still happens to you with the most recent Grafana version.
