### ISSUE TITLE
Alerting: PagerDuty de-duplication key too simple, may cause incorrect incident de-duplication

### ISSUE THREAD

**Issue by alavrovinfb** [grafana/grafana#26863]
**What happened**:
I have two Grafana instances in different clusters, both Grafanas have the same PG account and integration key configured. Both instances have the same dashboards configured. (through import-export).

If alerts with the same alert ID but from different Grafana instances are triggered, only one incident shows up in Pager Duty. It is caused by de-duplication on the PG side (note that the same ID can have different alerts).

**What you expected to happen**:
All alerts should be shown in PG. The dedup key should be unique or more complex.

The current dedup key is created by the following scheme: `bodyJSON.Set("dedup_key", "alertId-"+strconv.FormatInt(evalContext.Rule.ID, 10))`.

https://github.com/grafana/grafana/blob/9c81c7aa4462057abec2cc2426d575843cb6b2b4/pkg/services/alerting/notifiers/pagerduty.go#L223

We can probably create a more complex key, something like this: `alerId+dashboardId+panelId`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create fresh identical Grafana instances in two similar environments.
2. Configure identical PagerDuty notification channels in the Grafana instances. 
3. Create or import dashboards with alerts.
4. Trigger alerts with the same alert ID on the Grafana instances. Check the alert ID through the Alerting API.
5. Check Pager Duty incidents, only one should present. 

**Environment**:

- Grafana version: grafana:6.5.1
- Data source type & version: Prometheus 2.17.2
- OS Grafana is installed on: docker container,
- User OS & Browser: Ubuntu 20.4, firefox
- Grafana plugins: no
- Others: -

**Comment by aknuds1** [comment]
We don't support Grafana 6.5. Please try 6.7.4 or 7.1.3.

**Comment by alavrovinfb** [comment]
How as I see from the code mentioned Grafana versions also affected by this issue.
https://github.com/grafana/grafana/blob/9c81c7aa4462057abec2cc2426d575843cb6b2b4/pkg/services/alerting/notifiers/pagerduty.go#L223
This code in the master

**Comment by aknuds1** [comment]
OK, we'll have a look when time allows.

**Comment by aknuds1** [comment]
Are you able to provide a PR to solve the issue?

**Comment by alavrovinfb** [comment]
> Are you able to provide a PR to solve the issue?

I can probably do this.

**Comment by alavrovinfb** [comment]
PR [26972](https://github.com/grafana/grafana/pull/26972) has been raised.
Also, I can implement the ability to override `dedup_key` through alert tags, the same way as for PG attributes `group`, `class` etc. in separate PR.

**Comment by marefr** [comment]
> Also, I can implement the ability to override dedup_key through alert tags, the same way as for PG attributes group, class etc. in separate PR.

@alavrovinfb that to me would be a better solution than current PR since users can opt-in to use it. Higher chance of accepting a PR with this change than the current one I just closed.
