### ISSUE TITLE
grafana got unexpected data from Prometheus

### ISSUE THREAD

**Issue by husoule** [grafana/grafana#26864]
**What happened**:
I adjusted the prometheus  parameters --query.lookback-delta=10s. If I play with Prometheus directly, I see the latest result being less then now + lookback-delta. This is as expected。 But via grafana, it got  the latest result  data of future 5m.

For the same URL, directly requesting prometheus and requesting from grafana, the data obtained is different.
![image](https://user-images.githubusercontent.com/5336915/89651155-14c17a80-d8f6-11ea-9bc3-1075a82631d6.png)

![image](https://user-images.githubusercontent.com/5336915/89651328-581be900-d8f6-11ea-947f-087fde3a3016.png)

**What you expected to happen**:

Expect the same data

**Environment**: 
- Grafana version:  v6.5.3
- Prometheus version: v2.18.1

**Comment by torkelo** [comment]
Can't think of a reason for this. Grafana does not read or modify the result, it's just a http proxy. 

You will have to capture the network request and response grafana server makes as well to see what is happening there.

**Comment by aknuds1** [comment]
Does this happen if you try one of the latest supported Grafana versions (v6.7.4 or v7.1.3 respectively)?

**Comment by husoule** [comment]
It is q problem about thanos query . I have filed a new issue https://github.com/thanos-io/thanos/issues/3001

**Comment by torkelo** [comment]
maybe, closing this for now, if you have more info indicating this is a Grafana issue let me know
