### ISSUE TITLE
Grafana persistence  valoume has added but not getting any data in volume /grafana/data/

### ISSUE THREAD

**Issue by prashantnitt07** [grafana/grafana#26862]
find grafana deployment ymal file.

grafana version : 7.0.3 

---------------------

spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      k8s-app: grafana
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        k8s-app: grafana
        task: monitoring
    spec:
      containers:
      - env:
        - name: INFLUXDB_HOST
          value: monitoring-influxdb
        - name: GF_SERVER_HTTP_PORT
          value: "3000"

- name: GF_SECURITY_ADMIN_PASSWORD
          value: admin
        - name: GF_SERVER_ROOT_URL
          value: /
        image: grafana/grafana:7.0.3
        imagePullPolicy: IfNotPresent
        name: grafana
        ports:
        - containerPort: 3000
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /grafana/data/
          name: grafanapvc
      dnsPolicy: ClusterFirst
      nodeSelector:
        node-role.kubernetes.io/master: ""
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master

- effect: NoSchedule
        key: node-role.kubernetes.io/master
      volumes:
      - hostPath:
          path: /etc/ssl/certs
          type: ""
        name: ca-certificates
      - name: grafanapvc
        persistentVolumeClaim:
          claimName: grafanapvc
      - configMap:
          defaultMode: 420
          items:
          - key: grafana.ini
            path: grafana.ini
          name: grafana-config
        name: config

**Comment by prashantnitt07** [comment]
/grafana - this is local storage which is mounted in linux machine

**Comment by aknuds1** [comment]
Please rewrite the issue using our standard bug template.

**Comment by aknuds1** [comment]
Also try Grafana 7.1.3, since 7.0.3 is unsupported.

**Comment by torkelo** [comment]
`/grafana/data/`

is not a standard grafana data path, `/var/lib/grafana` is
