### ISSUE TITLE
Drone: Missing build metric stats 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#26878]
The old CircleCI frontend test executed this script: 
https://github.com/grafana/grafana/blob/master/scripts/circle-test-frontend.sh 

Which in turn executed this script to record and publish some code stats 
https://github.com/grafana/grafana/blob/master/scripts/ci-frontend-metrics.sh

To be shown here, we used this to track bigger refactoring & migration tasks 
https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1

After drone CI migration these are no longer being executed and reported.

**Comment by torkelo** [comment]
@aknuds1 could need some help on this one. 

you will need GRAFANA_MISC_STATS_API_KEY added to drone for these scripts to be able to publish the stats

**Comment by aknuds1** [comment]
@torkelo Will look into this.

**Comment by aknuds1** [comment]
This should be implemented.
