### ISSUE TITLE
Rendered template variable value is not updated when saved

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#26874]
**What happened**: After changing the value of a Custom hidden template variable, the new value appears to be saved but is not used in variable substitutions.

**What you expected to happen**: The new value of the variable is used in all references.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a single panel (doesn't matter what it is) referencing a template variable `$test`. In this case here's a simple Text example:

![grafana-bug-example-dash](https://user-images.githubusercontent.com/814226/89692940-12055c00-d8db-11ea-9c04-be92b9a364be.png)

2. Add the template variable `test` with value Type: Custom, Hide: Variable, and set the value to `value1`. Click "Add" and then "Save Dashboard":

![grafana-bug-value1](https://user-images.githubusercontent.com/814226/89692966-22b5d200-d8db-11ea-9f29-c76be1ef223f.png)

3. See that the value is saved:

![grafana-bug-value1-saved](https://user-images.githubusercontent.com/814226/89692990-3103ee00-d8db-11ea-990c-33ac8f7db34b.png)

4. Click Back arrow and see that the template variable is rendered:

![grafana-bug-value1-rendered](https://user-images.githubusercontent.com/814226/89693002-39f4bf80-d8db-11ea-9723-bfb557a98499.png)

5. Edit the template variable and change its value to `value2`. Click "Update" and then "Save Dashboard":

![grafana-bug-value2](https://user-images.githubusercontent.com/814226/89693044-555fca80-d8db-11ea-808c-df5e866ace31.png)

6. See that the value is updated:

![grafana-bug-value2-saved](https://user-images.githubusercontent.com/814226/89693057-5db80580-d8db-11ea-9ad2-adff0876a099.png)

7. Click back arrow and see that the rendered template is updated:

![grafana-bug-value2-rendered](https://user-images.githubusercontent.com/814226/89693074-66104080-d8db-11ea-8ef0-e97b7d8bc4d0.png)

8. Refresh the page. See that the value has reverted to `value1`:

![grafana-bug-value-reverted](https://user-images.githubusercontent.com/814226/89693094-79231080-d8db-11ea-8d12-184caeba79da.png)

9. Go to edit the template variable, see that it says `value2`, inconsistent with what is being rendered:

![grafana-bug-value-inconsistent](https://user-images.githubusercontent.com/814226/89693119-8809c300-d8db-11ea-8e40-78c23b5fea2e.png)

**Anything else we need to know?**: Deleting the variable, saving, and then re-adding the variable seems to fix it.

**Environment**:
- Grafana version: 7.0.4 and 7.1.3
- Data source type & version: n/a
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Safari 13.1.2
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @timpalpant did you forget to check the "Save current variables as dashboard default" checkbox when saving?
![image](https://user-images.githubusercontent.com/562238/90378811-220b0180-e07a-11ea-8830-d9ec8bc0470e.png)

Closing this issue for now. We can always reopen this issue later if the need arises.

All the best
