### ISSUE TITLE
TLS handshake error from x.x.x.x:XXXX: remote error: tls: unknown certificate

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#26887]
**What happened**: When we are trying to access grafana using https we got TLS handshake error in /var/log/messages and also in systemctl status of grafana service

**What you expected to happen**:  We shouldn't get the above error in/var/log/messages.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Grafana rpm with https
2. Login to Grafana gui and launch any dashboards
3. We are getting below error in /var/log/messages.
**"TLS handshake error from x.x.x.x:XXXX: remote error: tls: unknown certificate"**

**Environment**:
- Grafana version: 6.6.2 and 7.1.1
- Data source type & version: n/a
- OS Grafana is installed on: Red Hat Enterprise Linux 7.6
- User OS & Browser: chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by aknuds1** [comment]
Closing as dup of #26798.
