### ISSUE TITLE
Azure Monitor Insights Analytics service does not let to group series

### ISSUE THREAD

**Issue by dtrefilo-Quest** [grafana/grafana#26882]
**What happened**:
After update from 6.x version to 7.x App Insights KQL queries do not support series grouping. Before the upgrade, the series were displayed as separate lines, now all mixed into one. In my opinion, this new limitation effectively makes this datasource useless for the most real-world applications.

![grafana](https://user-images.githubusercontent.com/9788835/89732175-af849b00-da55-11ea-871f-d90e909b6fae.PNG)

The same query in the Azure Data Explorer:

![log-analytics](https://user-images.githubusercontent.com/9788835/89732374-0ccd1c00-da57-11ea-87d2-4c0db0003ee4.PNG)

**What you expected to happen**:
Multiple series on the chart graph with the possibility of legend formatting similar to the Azure Data Explorer or Grafana 6.x.

**How to reproduce it (as minimally and precisely as possible)**:
Write any "summarize by" query using Insights Analytics service. The query used on the chart above:
```
customMetrics
| where timestamp >= now(-24h)
| where name == "CpuUsage"
| where customDimensions.BatchAccountName == "odmeprododmwusbautility"
| summarize sum=sumif(value, value <= 2000.0) / avg(valueCount) by gr=tostring(customDimensions.CustomerPartitionId), bin(timestamp, 5m)
| order by timestamp
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.1
- Data source type & version: Azure Monitor built-in
- OS Grafana is installed on: Centos 7, docker container grafana/grafana:7.1.1
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: grafana-piechart-panel,petrslavotinek-carpetplot-panel,digrich-bubblechart-panel
- Others:

**Comment by torkelo** [comment]
Strange, the grouping I assume is done by the azure insights query engine, so not sure why it's returning a different result in Grafana. 

@kylebrandt any ideas? Could it be that we are not creating a unique time series for each dimension in 7.0?

**Comment by kylebrandt** [comment]
@dtrefilo-Quest It needs to be ascending `order by timestamp asc`. If you hover over the exclamation next to the panel title, it will show this information.  

@torkelo This needs to be more visible I think (this is a frame warning notification). What is happening is since the time grouping is failing, the table view is being returned instead. More on this issue in https://github.com/grafana/grafana/issues/26786

**Comment by dtrefilo-Quest** [comment]
@kylebrandt Thank you, `order by timestamp asc` helped.
