### ISSUE TITLE
Grafana does not support multiple column in the filter?

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#26886]
**What happened**:In Grafana I am not able to get 2 column data in one filter to show data.

**What you expected to happen**:I want to get data in the dashboard from 2 columns from filter.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:desktop
- Grafana version:7.1.0
- Data source type & version:SQL Server 2017
- OS Grafana is installed on:
- User OS & Browser:Chrome and edge
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
For support questions please use our community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io). Closing this as we use GitHub for bug reports and feature requests.
