### ISSUE TITLE
Wrong graph values due to Bytes-based calculations for Y-Axis / Unit / Data(Metric) using 1000 instead of 1024

### ISSUE THREAD

**Issue by bugla** [grafana/grafana#26894]
**What happened**:
Some or all Bytes-based calculations for Y-Axis / Unit / Data(Metric) are using 1000 instead of 1024 for calculations creating graphs with wrong values, whenever the y-axis unit factor shown is not exactly the unit factor of the input data.

I have an InfluxDB data source that gets operating system metrics from Telegraf including harddisk metrics. 
One incoming value (which is correct and correctly transmitted to Grafana) is Free_Megabytes from win_disk (speaking in Telegraf term). All that works fine. The input values make it correctly and without issue to Grafana (i.e. the input source is not relevant for this ticket).

If I create a graph panel and set the relevant unit setting in Grafana accordingly:
Panel / Y-Axis / Unit / Data(Metric): megabytes
and have enough free disk space so the y-axis shows GB units instead of MB units, it becomes clear, that in some place in Grafana the steps between B->KB->MB->GB->TB->PB are calculated by multiplying/dividing by 1000 instead of by 1024 (as they should be, because that's the standard in IT for Byte-based data).

Example: I have incoming data in (correctly calculated with 1024 factor between unit sizes) of 814.607 MB, i.e. a number 814607.
Grafana correctly notices that it makes more sense to display the number in GB, but while doing so it divides incorrectly by 1000 instead of 1024, resulting in (rounded) 815GB instead of the correct 796GB, which is quite a significant difference.

**What you expected to happen**:
I expect Byte-based calculations with an axis unit setting of "Data(Metric): <something_based_on_bytes>" to use 1024 as a multiplier/dividend as it is standard in IT (if I would want a 1000 factor, I would simply not choose Data(Metric): <something_with_bytes>, so everything should be fine for everyone if this is corrected).

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph panel, give it a 6 digit int as an input, e.g. 814607 (directly or from a source of your choice) and configure Panel / Y-Axis / Unit / Data(Metric): megabytes.
The graph will show 815GB (= 814607 / 1000 (rounded)) instead of 796GB  (= 814607 / 1024 (rounded)).

**Anything else we need to know?**:
Unfortunately there is no workaround for this (like adding a corrective factor to the select), because the unit factor shown in the graph (MB,GB,...) varies with the input number (which makes sense) and doing some complicated "if ..." calculation is not possible (neither in the select query (at least not with InfluxQL) nor in a subsequent transform configuration).
Fortunately this issue should be easy to fix for someone who is familiar with the Grafana source code (which I am not).

**Environment**:
- Grafana version: grafana-7.1.1
- Data source type & version: influxdb-1.8.1-1
- OS Grafana is installed on: Windows10 Version 1809 (Build 17763.1369)
- User OS & Browser: Windows10 Version 1809 (Build 17763.1369); Firefox 79.0
- Grafana plugins: (nothing relevant)
- Others: -

**Comment by sakjur** [comment]
**Data (Metric)** uses the metric/SI prefixes where the prefix is adjusted for every third power of ten. This is widely used by some vendors. You're looking for the **Data (IEC)** where the prefix is instead adjusted for every tenth power of two per [IEEE 1541](https://en.wikipedia.org/wiki/IEEE_1541-2002).
