### ISSUE TITLE
Grafana 2 remove organization

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#2689]
Hi,

is there a way to remove an organization from Grafana 2 (I'm using 2.1.1 currently). I've created one too many organizations, but I don't see a delete option, I can only rename it. :cry:

I don't want to delete it from the sqlite DB, because I don't know if there are any references to the row somewhere else.

Thanks,
Roland

**Comment by torkelo** [comment]
its implemented in next release grafana v2.2 (release in end of september). but you must be grafana admin

**Comment by rlueckl** [comment]
Thanks! :smile:

**Comment by yesman85** [comment]
@torkelo was this ever implemented? Even in the latest version I can't find the option anywhere.

**Comment by mattttt** [comment]
@yesman85 Yep, it's there. Here's a quick animated gif:

![delete-org](https://cloud.githubusercontent.com/assets/2886187/17819902/290f1010-6618-11e6-8934-bd5f52cda194.gif)

**Comment by yesman85** [comment]
That's odd, I can't see the admin menu, even though my user Role is set to Admin.

**Comment by yesman85** [comment]
Sorry my bad, Admin role is not the same as Grafana Admin! I can see it now.
