### ISSUE TITLE
Kiosk mode doesn't work after oauth redirect

### ISSUE THREAD

**Issue by nike61** [grafana/grafana#26899]
**What happened**:
When using oauth and kiosk mode the kiosk mode doesn't work on first login after redirect.
I think the problem is that kiosk mode only works when kiosk parameter is passed to the end of uri (but after redirect the kiosk parameters appears at the begging of url parameters).
**How to reproduce it (as minimally and precisely as possible)**:

1. Open link with kiosk mode (http://192.168.44.26/grafana/explore?&left=[%22now-1h%22,%22now%22,%22Loki%22,{%22expr%22:%22{stream=%22stdout%22}%22},{%22ui%22:[true,true,true,%22none%22]}]&orgId=1&kiosk)
2. Login with external oauth provider
3. Grafana redirects to http://192.168.44.26/grafana/explore?kiosk=&left=[%22now-1h%22,%22now%22,%22Loki%22,{%22expr%22:%22{stream=%22stdout%22}%22},{%22ui%22:[true,true,true,%22none%22]}]&orgId=1. 
If you try to open http://192.168.44.26/grafana/explore?left=[%22now-1h%22,%22now%22,%22Loki%22,{%22expr%22:%22{stream=%22stdout%22}%22},{%22ui%22:[true,true,true,%22none%22]}]&orgId=1&kiosk everything works fine
4. Kiosk mode doesn't work

**Comment by sakjur** [comment]
Thank you for reporting this, I'll try to see if I can reproduce it. Looking at your steps to reproduce it looks like the URL parameters are being parsed somewhere in the chain, is it possible that that's being done by your OAuth provider? Which OAuth provider are you using?

**Comment by baur** [comment]
@sakjur, this case not related only with OAuth, it can be reproduced wiht default login
1. Log out 
2. go http://localhost:3000/d/LzwfKLlZz/dash?orgId=1&kiosk
3. login in
4. redirects http://localhost:3000/d/LzwfKLlZz/dash?kiosk=&orgId=1

**Comment by baur** [comment]
@sakjur , @peterholmberg 
v7.3.0-beta2 (fce221a7d3) 
same problem!

**Comment by torkelo** [comment]
This is a backend bug caused by Golang's Encode of query parameters, transforms a &kiosk parameter to &kiosk=   (which frontend parses as an emtpy string value and not a boolean true value) 

https://github.com/grafana/grafana/blob/master/pkg/middleware/auth.go#L60

**Comment by marefr** [comment]
Some additional discussions about the Encode method in https://github.com/golang/go/issues/30025
