### ISSUE TITLE
Azure AD OAuth2 with/without app roles: Changing roles possible but not successful

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#26895]
**What happened**:

With Grafana configured for Azure AD Oauth2 as an Grafana Admin I can still change the roles of other users (including users managed in Azure AD) but the changed roles are actually not persistent. The change is only "successful" in the interface of the admin. When the user logs in again his role will not have changed. This happens regardless if I have configured app roles in the manifest or not.

**What you expected to happen**:

If this behavior is expected (Grafana Admin cannot change roles of Azure AD users) I would have expected the corresponding fields to be grayed out / errors thrown.

And maybe information about this behavior in the documentation. Though I'm not very experienced in Azure AD / OAuth, so maybe this is perfectly normal behavior.

**How to reproduce it (as minimally and precisely as possible)**:

1. Login as Azure AD user x (default role viewer)
2. Login as Grafana Admin
3. Change user x role to Admin
4. Login as user x

Role will still be viewer.

**Anything else we need to know?**:

Watch the gif

![gif2](https://user-images.githubusercontent.com/24834206/89781423-93dfca00-db13-11ea-800e-de4773efaa16.gif)

**Comment by sakjur** [comment]
Thank you for reporting this 🙂 I think the behavior itself is correct, handling of roles is [deferred to Azure AD's manifest](https://grafana.com/docs/grafana/latest/auth/azuread/#create-the-azure-ad-application) in the Azure AD provider. That being said: We should make this clearer in the documentation and improve the UX here.

**Comment by Jguer** [comment]
This has been fixed in Grafana 9.0 with the new user role picker

![image](https://user-images.githubusercontent.com/8071073/178760085-1a36be97-84b4-47ea-a6e3-81f6f4668a6b.png)
