### ISSUE TITLE
Transform "Series to rows" not working for Prometheus table

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#26901]
Grafana 6.x was able to merge multiple Prometheus Table instant queries into the single table result where each label and value had own column.

In Grafana 7 this is not possible at the moment. Grafana 7.1 provide two documented options
1. Merge - not always working due [#26890](https://github.com/grafana/grafana/issues/26890)
2. Series to rows - only working for time series, but not very usable when query result contains more than single label (this error)

**Expected behavior:**
Each query added to single table containing all labels and "common" value (can be then filtered using Filter by name). [https://grafana.com/docs/grafana/latest/panels/transformations/#series-to-rows](https://grafana.com/docs/grafana/latest/panels/transformations/#series-to-rows) extract: 
`Use this transformation to combine the result from multiple time series data queries into one single result. This is helpful when using the table panel visualization.`
`The result from this transformation will contain three columns: Time, Metric, and Value. The Metric column is added so you easily can see from which query the metric originates from. Customize this value by defining Label on the source query.
`
**Actual behavior:**
No transformation done when Format is table.
If format is time series then metric column contain either query legend value or full list of returned label key=values when legend not set but this is not very usable when query response contains multiple 
![image](https://user-images.githubusercontent.com/19704268/89791421-fb097880-db2b-11ea-82fa-2bacffc6572a.png)

**Proposed options:**
A. Implementation should be extended to support Prometheus Table data resulting Grafana 6.x style output. This would be similar to merge in most cases, but actually Merge is intended to merge multiple queries into single line, but often it result separate line when label set are different.
B. Documentation should be updated to indicate that Series to row is not working for Prometheus Table, and works only for queries explicit setting the legend values

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Grafana version: 7.1.2
- Data source type & version: Prometheus / Table
- OS Grafana is installed on: Windows and Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
The "Series to row" transformation is for translating time series data into table style data (which is stated in the documentation) so it works as intended.
You're correct in the assumption that the "Merge" transformation should work for this operation and the problem you're encountering with that is a bug that we intend to fix.
