### ISSUE TITLE
"Merge" transformer is overly simplistic, does not replicate "old-table" merge

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#26908]
**What happened**: Using the image below to explain. The first query aggregates on Country and Age, and generates a metric "Sum", the second query aggregates on just "Age", and generates a metric "Count".

![image](https://user-images.githubusercontent.com/19274602/89844882-ce585f80-db31-11ea-9d33-c32b7cf3c13a.png)

As can be seen, the merge only works for the first instances of each "AgeGroup".

**What you expected to happen**: The desired functionality was present in the "old-table", where the metric generates form the second query would be merged into every matching row of the first query. "Count" should be present on every row of "AgeGroup", not just the first instances of each value.

**How to reproduce it (as minimally and precisely as possible)**: So far as I can tell, the test datasources used on the live demo site are all too limited to demonstrate this (I consider this limitation as a bit of a bug in and of itself). All that is needed to reproduce the problem is a datasource that can generate 2 different dimensions (with enough variety so the overlap between them is not 1:1), and 2 different metrics. Then try to merge the two queries as explained above.

**Anything else we need to know?**: This is a regression from "old-table", one that is preventing us from upgrading many of our panels.

- Grafana version: 7.1
- Data source type & version: Elasticsearch

**Comment by torkelo** [comment]
@mckn any ideas how hard this will be?

**Comment by Ultraseamus** [comment]
Just to throw in my 2-cents on the tags applied: I think this is more of a bug than a feature request. The point of the Merge Transform was to mimic the "old table", and it does not do that for this fairly standard use case.

What it does instead is clearly incorrect. It arbitrarily picks a subset of the rows to apply the merge to, and the end result is misleading.

I am working on a fix in my own repo, and it is clear what is going wrong. "dataFrameIndexByKey" ends up looking something like this:

0 - 17: 3
25 - 34: 2
25 - 34Canada219: 6
35 - 49: 1
35 - 49Canada166: 5
35 - 49Germany146: 4
50 or over: 0

Then it comes to the second query, which has a value to join for "25-34". It matches the second item in this list, but it has no real way of matching the 3rd because of how it was formed. The second query knows nothing about the Country, it can't rebuild that key to see that it is also a match.

Also, it returns out of the merge function as soon as it finds the first match (so even if it could match that key, it would never have the chance).

I have not fixed it yet, but I think the easiest approach would be to walk through the logic still present for the "old table". It is a bit more complex, and have to be converted to work with Data Frames, but that way it would match the old functionality perfectly; and it's just a good starting point anyways because the way the "old table" performed merges has been proven, we rely on it in many of our panels.

**Comment by mckn** [comment]
> Just to throw in my 2-cents on the tags applied: I think this is more of a bug than a feature request. The point of the Merge Transform was to mimic the "old table", and it does not do that for this fairly standard use case.
> 
> What it does instead is clearly incorrect. It arbitrarily picks a subset of the rows to apply the merge to, and the end result is misleading.
> 
> I am working on a fix in my own repo, and it is clear what is going wrong. "dataFrameIndexByKey" ends up looking something like this:
> 
> 0 - 17: 3
> 25 - 34: 2
> 25 - 34Canada219: 6
> 35 - 49: 1
> 35 - 49Canada166: 5
> 35 - 49Germany146: 4
> 50 or over: 0
> 
> Then it comes to the second query, which has a value to join for "25-34". It matches the second item in this list, but it has no real way of matching the 3rd because of how it was formed. The second query knows nothing about the Country, it can't rebuild that key to see that it is also a match.
> 
> Also, it returns out of the merge function as soon as it finds the first match (so even if it could match that key, it would never have the chance).
> 
> I have not fixed it yet, but I think the easiest approach would be to walk through the logic still present for the "old table". It is a bit more complex, and have to be converted to work with Data Frames, but that way it would match the old functionality perfectly; and it's just a good starting point anyways because the way the "old table" performed merges has been proven, we rely on it in many of our panels.

I agree that this sounds like a bug. It should work the same way as the old table-mode did so lets see if we can add a couple of tests and get this into the new transform.

Thanks for reporting this and any help to resolve the issue would be great!

**Comment by mckn** [comment]
> @mckn any ideas how hard this will be?

hmm, hopefully not to hard. I have to check the implementation again but if I don't remember incorrectly the current flow of the code should still work but we just need to tweak the way we create the key and merge rows.

**Comment by Ultraseamus** [comment]
@mckn I implemented a fix for this in my private fork. You are right that the current implementation basically works with small changes. I basically just made dataFrameIndexByKey accept an array of indices:

`dataFrameIndexByKey: Record<string, [number]>`

And when there is a collision, instead of generating a new key for that row, I add it to the existing key's array. In my tests so far that has worked well. I've only looked at the scenario where there is a single column name that multiple queries can be joined on. I don't know if there is a more complex case than that? I do wonder if I am oversimplifying things, since I don't understand the old key generation approach at all (generating unique keys for new rows seems completely counter-intuitive for merge logic).

If that approach sounds sensible, I could look at creating a PR. I'm not really set up for it at the moment, but I do have one or two other fixes/features that I could look at pulling into the master branch.

On a related note: One of my users has a use-case where they write 3 or more queries, and merge them, but intentionally one of those queries does not have a matching column, and should not be merged. The way it works today is that the merge Transformer does nothing in that case, since not all queries can be merged, it merges none of them. I would argue that people would expect merge to reduce 'N' queries into as few tables as it possibly could, maybe I'll add that into a new feature request? It is probably one of the next things I am going to work on.

**Comment by mckn** [comment]
Hello, sorry for the delayed response. I have been focusing on another project for a couple of weeks. 

> @mckn I implemented a fix for this in my private fork. You are right that the current implementation basically works with small changes. I basically just made dataFrameIndexByKey accept an array of indices:
> 
> `dataFrameIndexByKey: Record<string, [number]>`
> 
> And when there is a collision, instead of generating a new key for that row, I add it to the existing key's array. In my tests so far that has worked well. I've only looked at the scenario where there is a single column name that multiple queries can be joined on. I don't know if there is a more complex case than that? I do wonder if I am oversimplifying things, since I don't understand the old key generation approach at all (generating unique keys for new rows seems completely counter-intuitive for merge logic).
> 
> If that approach sounds sensible, I could look at creating a PR. I'm not really set up for it at the moment, but I do have one or two other fixes/features that I could look at pulling into the master branch.

It would be perfect if you could contribute with a PR to resolve these issues 🎉 🙌 . There are a couple of scenarios where it gets kind of complex to merge different data sets but if you open a PR I will help out to tweak the transform so it supports all of them.

> 
> On a related note: One of my users has a use-case where they write 3 or more queries, and merge them, but intentionally one of those queries does not have a matching column, and should not be merged. The way it works today is that the merge Transformer does nothing in that case, since not all queries can be merged, it merges none of them. I would argue that people would expect merge to reduce 'N' queries into as few tables as it possibly could, maybe I'll add that into a new feature request? It is probably one of the next things I am going to work on.

Hmm, this is a good point! I can see scenarios where it is both good and bad to get a partial merged result. What do you think about this @torkelo?

**Comment by mckn** [comment]
@Ultraseamus I am starting to look into this issue now and it would be awesome if you could provide me with one example on the data before the merge is applied.

If I understood you correctly the input data is something like the following?

**Query A:**
| Country       | AgeGroup   | Sum  |
|---------------|------------|------|
| United States | 50 or over | 998  |
| United States | 35 - 49    | 1193 |
| Mexico        | 0 - 17     | 1675 |
| Germany       | 35 - 49    | 146  |
| Canada        | 35 - 49    | 166  |
| Canada        | 25 - 34    | 219  |


**Query B:**
| AgeGroup   | Count |
|------------|-------|
| 0 - 17     | 1     |
| 18 - 24    | 3     |
| 25 - 34    | 2     |
| 35 - 49    | 4     |
| 50 or over | 2     |
