### ISSUE TITLE
dashed option for threshold lines

### ISSUE THREAD

**Issue by cartw** [grafana/grafana#26913]
**What would you like to be added**:
An option to draw threshold lines on graph panels as dashed rather than solid lines.

**Why is this needed**:
With multiple series on a graph it is pretty much impossible to pick a colour for a threshold line that will never be used by a data series, and in some situations this can make it hard to distinguish the thresholds from the data. I think adding the option to draw the threshold line as dashed would be a useful addition.

**Comment by Eraac** [comment]
As a workaround you can do the opposite, via series overrides set `dashes: true`

**Comment by cartw** [comment]
Sure, but dashed wiggly lines for data series are harder to discern than dashed horizontal lines for thresholds. Is it dashed or am I missing data? Also for templating heavy dashboards series overrides may not be practical.

**Comment by just-doit** [comment]
I would love to have that option, too.

**Comment by EmandM** [comment]
I would also like to have this option

**Comment by sean-rossignol** [comment]
Have there been any updates on this issue?  I would definitely benefit from this change as well.
