### ISSUE TITLE
API: Add validation for dashboard JSON

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#26910]
**What happened**:
If the dashboard JSON is for some reason corrupted in the database (migration from other database)
the dashboard is not loaded properly (missing title etc.) but there is no other error message informing the user.

**What you expected to happen**:
There should be at least an error informing the user about the failure to load the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
Modify the `data` column in `datasource` table and store an invalid JSON.

**Anything else we need to know?**:

**Environment**:
- Grafana version: master

**Comment by ying-jeanne** [comment]
[response_when_json_not_valid.txt](https://github.com/grafana/grafana/files/5602695/response_when_json_not_valid.txt)
[response_when_json_valid.txt](https://github.com/grafana/grafana/files/5602696/response_when_json_valid.txt)
[the_content_of_data.txt](https://github.com/grafana/grafana/files/5602701/the_content_of_data.txt)

when backend encode response with no valid JSON, the entire data is skipped, the error is not handled properly, response 200

**Comment by pi0neerpat** [comment]
In Grafana v7.3.4, I do get an error message when attempting to load a corrupted JSON dashboard - however it isn't helpful
 
`An unexpected error happened. InternalError: too much recursion`

Also, this prevents me from fixing the JSON error, as I am blocked from making any changes. Should I make a new issue for this?
