### ISSUE TITLE
Panel displays name as "Value" when using ${__field.name} variable

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#26915]
**What happened**:

![image](https://user-images.githubusercontent.com/43188411/89875877-7a4b8a80-dbc6-11ea-9aa7-fe339db54fd5.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/43188411/89875819-6a33ab00-dbc6-11ea-8637-560eabcd3b82.png)

**How to reproduce it (as minimally and precisely as possible)**:

- Create a stat panel (or graph, gauge, bar...)
- Write any query.
- Enter Display Name: ```${__field.name}``` under Field section.
- It'll display the name as "Value".
- Remove the variable and keep Display Name empty. It's fine now.

**Anything else we need to know?**:

This was fine at v7.1.0.

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: InfluDB

**Comment by torkelo** [comment]
you need to set it to  `${__field.displayName}`  but this is not needed in your case as that is the default, you just need to change text mode option to Value and name (text mode optionb in the first tab in the right side menu)

**Comment by andutt** [comment]
@torkelo thanks for this, your response provided a fast fix to a broken dashboard after upgrade.

**Comment by monrealis** [comment]
My dashboard started displaying `Value` after Grafana's upgrade (prometheus datasource, bar gauge). When I started diffing JSONs of the newly created panel with that of the old version, I found that `"displayName": "${__field.name}",` was causing the problem, which was absent in the newly created panel. I am sure I did not manually enter this in the old version, it was saved by Grafana itself.
