### ISSUE TITLE
Panel's ID changes to 23763571993 in edit mode

### ISSUE THREAD

**Issue by oklk** [grafana/grafana#26924]
**What happened**:

When using the "id" prop of the panel in a plugin. The ID changes to 23763571993 in edit mode.

```js
import React from 'react';
import { PanelProps } from '@grafana/data';

export const Panel: React.FC<PanelProps> = ({ id }) => {
  console.log(id);

  return <div>{id}</div>;
};
```

![grafana-id-2-bug](https://user-images.githubusercontent.com/56425069/89891977-48422480-dbd6-11ea-95f3-18194482fc90.gif)

**What you expected to happen**:

The id should be the same as panelId (the actual panel ID)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a panel plugin
2. Add this code in the Panel file
```js
import React from 'react';
import { PanelProps } from '@grafana/data';

export const Panel: React.FC<PanelProps> = ({ data, id }) => {
  console.log('panelId', data.request?.panelId);
  console.log('id', id);

  return (
    <div style={{ textAlign: 'center' }}>
      <h1>{data.request?.panelId}</h1>
      <h1>{id}</h1>
    </div>
  );
};
```
3. Add the panel plugin to your grafana
4. Create a new panel in grafana and select the newly create panel plugin

**Anything else we need to know?**:

If you refresh (f5) inside the edit mode, the panelId also gets changed to 23763571993
![grafana-id-edit-bug](https://user-images.githubusercontent.com/56425069/89890820-49725200-dbd4-11ea-9ec6-315ebf27ef52.gif)

Also found this searching on google
<https://github.com/grafana/grafana/pull/22131/files#r378413699>

**Environment**:
- Grafana version: v7.1.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04 LTS
- User OS & Browser: Ubuntu 20.04 LTS, Chrome 84.0.4147.105
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
Does that happen after saving the dashboard?

**Comment by oklk** [comment]
Yes it does. As you can see in the last gif, I'm refreshing.

**Comment by oklk** [comment]
Out of curiousity, I checked the panel data (inspect json), and saw that the JSON data shows the id is 2 in the normal view, and 23763571993 in edit mode.
Edit mode
![Screenshot from 2020-08-11 14-56-47](https://user-images.githubusercontent.com/56425069/89899736-023f8d80-dbe3-11ea-9785-e7a4dc37cda8.png)

Normal mode
![Screenshot from 2020-08-11 14-56-29](https://user-images.githubusercontent.com/56425069/89899747-04a1e780-dbe3-11ea-975c-cc2ef48c817e.png)

**Comment by sakjur** [comment]
It seems to be intentional and has something to do with Redux. I'll forward this to someone who knows our frontend better than I do to clarify if this is a bug or not.
 https://github.com/grafana/grafana/blob/1f4a04436c63c672bc7035349d3cfca6cdbb41b8/public/app/core/constants.ts#L14

**Comment by dprokop** [comment]
It's a temporary id for the panel clone, restored later in redux action when changes are saved. It's not persisted, or at least it should not be. Just checked against latest version and it seems like the id of the original panel is correct.

**Comment by oklk** [comment]
Could the panel id be something other than a number?
Would be easier to check against something like null or undefined.
