### ISSUE TITLE
keycloak saml using apache mellon- authproxy

### ISSUE THREAD

**Issue by prabhinmp** [grafana/grafana#26928]
<VirtualHost *:443>
ServerName grafana.xxx.com
SSLEngine On
SSLCertificateFile /etc/httpd/conf.d/ssl/xxx.cer
SSLCertificateKeyFile /etc/httpd/conf.d/ssl/xx.key
SSLCACertificateFile /etc/httpd/conf.d/ssl/RootWcdGlobalsign.cer
SSLCertificateChainFile /etc/httpd/conf.d/ssl/IntermediateWcdGlobalsign.cer

RequestHeader set X-WEBAUTH-USER %{MELLON_user}e env=MELLON_user
    RequestHeader set X-WEBAUTH-USER %{MELLON_email}e env=MELLON_email
    RequestHeader set X-WEBAUTH-USER %{MELLON_username}e env=MELLON_username
    RequestHeader set X-Forwarded-Proto "https"
<Location / >

MellonEnable info
MellonEndpointPath /mellon/
MellonSPMetadataFile /etc/httpd/saml2/mellon_metadata.xml
MellonSPPrivateKeyFile /etc/httpd/saml2/mellon.key
MellonSPCertFile /etc/httpd/saml2/mellon.crt
MellonIdPMetadataFile /etc/httpd/saml2/idp_metadata.xml

AuthType Mellon
MellonEnable auth
Require valid-user
           ProxyPass "/"  "http://localhost:3000/"
    ProxyPassReverse "/"  "http://localhost:3000/"
ErrorLog /var/log/httpd/grafana-sso.stg.example.cloud-error.log
CustomLog /var/log/httpd/grafana-sso.stg.example.cloud-access.log combined
LogLevel debug
SSO: keycloak saml

From grafana its getting redirect tot keycloak , after successful login at SSO the user is not logged in grafana. Can you please suggest . 

Im not sure what should be the value for headers in my case.
Please help on this.

below is my grafana.ini
auto_signup = true
enabled = true
header_name = X-WEBAUTH-USER
header_property = username

**Comment by sakjur** [comment]
Please ask questions on [community.grafana.com](https://community.grafana.com) . GitHub is only for bug reports and feature requests.
