### ISSUE TITLE
Flux queries (like pivot) contain metadata columns "result" and "table"

### ISSUE THREAD

**Issue by loganmc10** [grafana/grafana#26927]
**What happened**:

When using functions like |> pivot(), the resulting table contains 2 extra columns: "result", and "table", these columns cannot be removed using a function like drop(), the only way to remove them is using a transformation to hide them, but then I can't use alerts because they are incompatible with transformations.

**What you expected to happen**:

Either automatically remove/hide these columns, or have a way to do it in the query editor, rather than using a transformation.

**How to reproduce it (as minimally and precisely as possible)**:

Use the pivot function in a flux query, look at the resulting table

**Anything else we need to know?**:

I am using InfluxDB 2 (beta)

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: InfluxDB 2 OSS, Flux query language
- OS Grafana is installed on: Docker
- User OS & Browser: Chrome, Windows
- Grafana plugins: None
- Others:

**Comment by kchervonets** [comment]
You can remove them using
Transform -> Organize fields -> there is an eye icon, it will hide the fields

**Comment by loganmc10** [comment]
Yes that it what I do now, but then I can't use any alarms

**Comment by ryantxu** [comment]
Fixed by #27081

@loganmc10 can you check the latest nightly builds?  will be included in 7.2

**Comment by loganmc10** [comment]
Unfortunately I don't really have a dev/test environment setup, but I trust you! I look forward to 7.2
