### ISSUE TITLE
force sidemenu hide

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2692]
Is it possible to force sidemenu hide since we don't need it once grafana org and sources are configured?

**Comment by torkelo** [comment]
Yes,  click the arrow on the top of the side menu to close it. It should. It appear again.

**Comment by rschitz** [comment]
it doesn't survive a logout

**Comment by torkelo** [comment]
@rschitz true, but that is because you open the sidemenu to logout :) Which means when you login it will be open, since that was the last state. If you do not log out it should remain closed

**Comment by rschitz** [comment]
ok i get it, is it global setting or per user ?

**Comment by torkelo** [comment]
no its stored in browser localStorage
