### ISSUE TITLE
Table - make it possible to pass in a custom renderer 

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#26920]
### What would you like to be added?
Make it possible to use a custom Cell renderer for the `<Table />` component in `@grafana/ui`.

**Example:**
```javascript
const data = new MutableDataFrame({
    fields: [
      {
        name: 'Status',
        type: FieldType.string,
        values: [
            'active',
            'active',
            'unavailable',
        ],
        // An idea for how we could set it is to pass an optional "render" property to a field
        render: (status) => <StatusComponent status={status} /> 
      },
    ],
  });
```

---

### Why is this needed?
Currently if we would like to use the `<Table />` component from our UI library we can only choose from the following options to display a value for a given cell:
- `ColorText`
- `ColorBackground`
- `LcdGauge`
- `BasicGauge`
- `GradientGauge`
- `JSONView` 

**It can easily happen though that we would like to have a custom way for visualising values in a certain field**, for example displaying a colorised dot for certain status values.

**Comment by peterholmberg** [comment]
@leventebalogh what's the latest on this? Are you working on it?
