### ISSUE TITLE
Adding a new user with an already-existing name returns 500 instead of 409

### ISSUE THREAD

**Issue by Toniob** [grafana/grafana#26934]
**What happened**:
I sent an api request to create a new user whose name already exists. Grafana replied with a 500 error code.

**What you expected to happen**:
Grafana send a 409 HTTP code, like it does for new teams for example.

**How to reproduce it (as minimally and precisely as possible)**:
Create a user. Try creating a user with the same name again.

**Anything else we need to know?**:
There may be other api endpoints with the same issue. Those endpoints should send a meaningful http status code instead of a 500.

**Environment**:
- Grafana version: 7.1.3

**Comment by Toniob** [comment]
Hi,
Thanks for the fast patch. It's great to see that Grafana is taken care of.

I had a similar issue when trying to add a user to a team if that user is already in the team (endpoint : `/api/teams/:teamId/members`). The api returns a 400 http code. Maybe some guidelines should be written, and http codes should be defined, in order to the api to have a consistent behavior ?

**Comment by sakjur** [comment]
@Toniob We're looking at increasing the consistency of the API overall :+1:
