### ISSUE TITLE
Influxdb query editor don't persist the changes

### ISSUE THREAD

**Issue by aferrari-technisys** [grafana/grafana#2694]
Hi, I'm using Grafana with Influxdb and Performance Co-Pilot as metric shipper.

The CPU metric send by PCP is not easy to represent into Grafana, to convert this numers to % is needed apply some Math operations, the doc of PCP say that we need apply this:

%usr = 100 * kernel.all.cpu.user / ( hinv.ncpu * 1000)

Of course to add all this math into SELECT field on Grafana I go to Manual query editor, write the query and the preview show perfectly the result.

The issue come when, i leave the Editor mode, any of the params persist, all go back to the query loaded  from normal editor like mean(value).

I made a quick video to show the issue:
https://youtu.be/Ys4WSvlrPRY

Thanks!
Ale

**Comment by aferrari-technisys** [comment]
I found my mistake, I press PEN icon again "to accept changes" but really this reset to wizard mode, for this reason I loose the changes.

**Comment by bstaten** [comment]
Are you sending your pcp data to the Influxdb? Do you have any documentation on how to do that. I am trying to use PCP, Grafana, and Influxdb and was looking for some documentation/help on how to configure this.
