### ISSUE TITLE
missing upgrade to 7.1  section in upgrading documentation

### ISSUE THREAD

**Issue by UrielCh** [grafana/grafana#26944]
**What would you like to be added**:

add a *upgrade to 7.1* section to https://grafana.com/docs/grafana/latest/installation/upgrading/
add a *Breaking change* section to https://grafana.com/docs/grafana/latest/guides/whats-new-in-v7-1/

*foldersFromFileStructure* had been renamed to *foldersFromFile****s****Structure* in dashboard provisioning

For me this change do not fix my configuration, I had to move my dashboards json files to the parent folder to make it starts.

**Why is this needed**:

I have just try to upgrade my grafana from 7.0.6 to 7.1.0 and my dashboard configuration is not valid any more.

Relative issues:
* #25995 update doc
* #26223 active breaking change following
* [810ec4c](https://github.com/grafana/grafana/commit/810ec4c5f8ec5bf028d2de015fbb1779ff8fd94d) change in code

**Comment by zoltanbedi** [comment]
@grafana/docs-squad fyi

**Comment by achatterjee-grafana** [comment]
Thanks @zoltanbedi

**Comment by marefr** [comment]
> I do not know if the backport will fail

That's not really the problem. It's that we don't automatically re-publish docs from v7.x branches.

**Comment by GrafanaWriter** [comment]
We won't be updating docs beyond 8.x.x. Closing this issue.
