### ISSUE TITLE
We found a bug in grafana Super Admin password in clear

### ISSUE THREAD

**Issue by Tchoupiy** [grafana/grafana#26942]
We found a bug 

We found a bug that displays the superadmin password in clear
![image](https://user-images.githubusercontent.com/54705587/89987217-f48b1600-dc7d-11ea-96a8-2079be81f6c6.png)

**Comment by torkelo** [comment]
Looks to be an issue with the data source plugin your using, what plugin is that?

**Comment by Tchoupiy** [comment]
Im using zabbix !
![image](https://user-images.githubusercontent.com/54705587/89990543-d5db4e00-dc82-11ea-9794-cfdd1ff01f6e.png)

**Comment by aknuds1** [comment]
And the request involves logging the user in, right? So the password included in the request is from the _Password_ field?

**Comment by Tchoupiy** [comment]
No its ok i made a mistake we think its an request to grafana but its on zabbix !
The request is legit !

My bad 

Thanks
