### ISSUE TITLE
Custom Docker build Fails while running exec:webpack

### ISSUE THREAD

**Issue by jayaraj** [grafana/grafana#26959]
**What happened**:
Docker Build Fails on Step 12/36 : RUN ./node_modules/.bin/grunt build
...................
...................
Running "exec:webpack" (exec) task
/usr/src/app

[
  ModuleNotFoundError: Module not found: Error: Can't resolve 'vendor/angular-other/angular-strap' in '/usr/src/app/public/app'

**What you expected to happen**:
Successful docker build 

**How to reproduce it (as minimally and precisely as possible)**:
Clone latest repo
sudo docker build --build-arg "GRAFANA_VERSION=latest" -t custom -f Dockerfile . 

**Anything else we need to know?**:
Logs :
Running "exec:webpack" (exec) task
/usr/src/app
[
  ModuleNotFoundError: Module not found: Error: Can't resolve 'vendor/angular-other/angular-strap' in '/usr/src/app/public/app'
      at /usr/src/app/node_modules/webpack/lib/Compilation.js:925:10
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:401:22
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
      at /usr/src/app/node_modules/neo-async/async.js:2830:7
      at /usr/src/app/node_modules/neo-async/async.js:6877:13
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:213:14
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
  resolve 'vendor/angular-other/angular-strap' in '/usr/src/app/public/app'
    Parsed request is a module
    using description file: /usr/src/app/package.json (relative path: ./public/app)
      Field 'browser' doesn't contain a valid alias configuration
      resolve as module
        /usr/src/app/public/app/node_modules doesn't exist or is not a directory
        /usr/src/app/public/node_modules doesn't exist or is not a directory
        /usr/src/node_modules doesn't exist or is not a directory
        /usr/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
        looking for modules in /usr/src/app/node_modules
          using description file: /usr/src/app/package.json (relative path: ./node_modules)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /usr/src/app/package.json (relative path: ./node_modules/vendor/angular-other/angular-strap)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.tsx doesn't exist
              .es6
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.es6 doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.json doesn't exist
              .svg
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.svg doesn't exist
              as directory
                /usr/src/app/node_modules/vendor/angular-other/angular-strap doesn't exist
        looking for modules in /usr/src/app/public
          using description file: /usr/src/app/package.json (relative path: ./public)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /usr/src/app/package.json (relative path: ./public/vendor/angular-other/angular-strap)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap.tsx doesn't exist
              .es6
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap.es6 doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap.json doesn't exist
              .svg
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/public/vendor/angular-other/angular-strap.svg doesn't exist
              as directory
                /usr/src/app/public/vendor/angular-other/angular-strap doesn't exist
        looking for modules in /usr/src/app/node_modules
          using description file: /usr/src/app/package.json (relative path: ./node_modules)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /usr/src/app/package.json (relative path: ./node_modules/vendor/angular-other/angular-strap)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.tsx doesn't exist
              .es6
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.es6 doesn't exist
              .js
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.js doesn't exist
              .json
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.json doesn't exist
              .svg
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/angular-other/angular-strap.svg doesn't exist
              as directory
                /usr/src/app/node_modules/vendor/angular-other/angular-strap doesn't exist,
  ModuleNotFoundError: Module not found: Error: Can't resolve 'vendor/bootstrap/bootstrap' in '/usr/src/app/public/app'
      at /usr/src/app/node_modules/webpack/lib/Compilation.js:925:10
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:401:22
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:130:21
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:224:22
      at /usr/src/app/node_modules/neo-async/async.js:2830:7
      at /usr/src/app/node_modules/neo-async/async.js:6877:13
      at /usr/src/app/node_modules/webpack/lib/NormalModuleFactory.js:214:25
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:213:14
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:26:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/ModuleKindPlugin.js:30:40
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:44:7
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:13:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:14:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/Resolver.js:285:5
      at eval (eval at create (/usr/src/app/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:25:1)
      at /usr/src/app/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:67:43
  resolve 'vendor/bootstrap/bootstrap' in '/usr/src/app/public/app'
    Parsed request is a module
    using description file: /usr/src/app/package.json (relative path: ./public/app)
      Field 'browser' doesn't contain a valid alias configuration
      resolve as module
        /usr/src/app/public/app/node_modules doesn't exist or is not a directory
        /usr/src/app/public/node_modules doesn't exist or is not a directory
        /usr/src/node_modules doesn't exist or is not a directory
        /usr/node_modules doesn't exist or is not a directory
        /node_modules doesn't exist or is not a directory
        looking for modules in /usr/src/app/node_modules
          using description file: /usr/src/app/package.json (relative path: ./node_modules)
            Field 'browser' doesn't contain a valid alias configuration
            using description file: /usr/src/app/package.json (relative path: ./node_modules/vendor/bootstrap/bootstrap)
              no extension
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/bootstrap/bootstrap doesn't exist
              .ts
                Field 'browser' doesn't contain a valid alias configuration
                /usr/src/app/node_modules/vendor/bootstrap/bootstrap.ts doesn't exist
              .tsx
                Field 'browser' doesn't contain a valid a

**Environment**:
- Grafana version:7.2.0-pre
- Data source type & version:
- OS Grafana is installed on: ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by AnushaBoggarapu** [comment]
Were you able to solve it, facing same issue?

**Comment by jayaraj** [comment]
Thanks, Was able to solve. as git ignore was preventing to check in vendor folder inside public. This will be an issue for only those who custom build and missing the vendor files present inside public folder

**Comment by xlson** [comment]
Sounds like this is resolved then, I'm happy to hear that.

**Comment by noufalpp1988** [comment]
> Thanks, Was able to solve. as git ignore was preventing to check in vendor folder inside public. This will be an issue for only those who custom build and missing the vendor files present inside public folder

Can you please specify the resolution steps in detail. I get same error with grafana during docker build.

**Comment by jayaraj** [comment]
> > Thanks, Was able to solve. as git ignore was preventing to check in vendor folder inside public. This will be an issue for only those who custom build and missing the vendor files present inside public folder
> 
> Can you please specify the resolution steps in detail. I get same error with grafana during docker build.

Can you explain me what you are building. Have you customised it. or is it just a build made from zipped code downloaded from github.

**Comment by ramondepieri** [comment]
I was having the same issue, and worst. That looked like a random issue, because sometimes the build pass and others the build fail. I don´t understand the reason, but you need to have the "public/vendor" folder and all the files in your public folder. Sometimes this files are auto generated, others not. So I copied this file from some installation that I had, past in my repository, remove the "vendor" from .gitignore and commit all "public/vendor" files. This solved the problem
