### ISSUE TITLE
API input validation

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#2695]
The api is not really doing any input validation, but probably should.

Would something like https://github.com/go-validator/validator be appropriate?

**Comment by torkelo** [comment]
well most api operations are using the binding package from macaron that has some basic validation, and if not using that there is some manual validation. 

https://github.com/macaron-contrib/binding/blob/master/binding.go#L285

But go-validator is probably better. The problem I have with the current validation is that the fieldNames in error message are capital case (they match the golang struct prop name and not the json representation).

For example if I 
```
POST /api/user/signup
{
}
```
Response
```
[
    {
        "fieldNames": [
            "Email"
        ],
        "classification": "RequiredError",
        "message": "Required"
    }
]
```

This response is from the macaron binding package, but do not like that Email in fieldNames is capitalized. 

This validation is from the attribute on the struct

```go
type SignUpForm struct {
	Email string `json:"email" binding:"Required"`
}
```

**Comment by woodsaj** [comment]
Oh, i didnt realize that the macaron.binding package could do validation.
http://macaron.gogs.io/docs/middlewares/binding#validate

It even goes a step further and has helpers for validating common input strings like URL and email.
Maybe we can submit a patch to macaron.binding validator to use json names if they are present in the struct tags.

**Comment by torkelo** [comment]
yea, that could be a good option. There also seems to be some hooks in the binding validator code so maybe its possible to extend / modify the behavior.
