### ISSUE TITLE
MixedDatasource: error on one data source prevents showing available data from other data sources

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#26955]
**What happened**:
I select multiple datasources from which one becomes non-responsive. I get a "Network Error: bad gateway (502)" error in the panel and no data is shown in the panel.

**What you expected to happen**:
I expected the data from the available datasources to be shown, and the error to be more specific, e.g. mentioning the failing datasource.

**How to reproduce it (as minimally and precisely as possible)**:
* add multiple datasources, e.g. on different embedded devices
* add metric queries for all of these datasources in e.g. the graph panel
* disconnect/shutdown one of the (embedded) devices

**Anything else we need to know?**:
I verified this behaviour on the flowcharting panel and the graph panel.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: influxdb bundled with grafana
- OS Grafana is installed on: armbian/debian buster
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @bijwaard , just to clarify you're using the Mixed data source for this right? 
![image](https://user-images.githubusercontent.com/562238/90232981-b62c5d00-de1d-11ea-9f5b-2bc319dcbcd3.png)

**Comment by bijwaard** [comment]
Hi @hugohaggmark , thanks for your response!
Yes, I'm using the Mixed data source.

**Comment by hugohaggmark** [comment]
Thank you @bijwaard getting back, I can repro this and it is by design but I think this makes sense so I'll add it to our backlog.

**Comment by bijwaard** [comment]
Thanks @hugohaggmark, great that most developments are agile these days;-)
