### ISSUE TITLE
Autoscaling Y axis problem

### ISSUE THREAD

**Issue by octapudus** [grafana/grafana#26966]
Hello,

I'm trying to do a visualization of a BTC price.

Basically my problem is that i am trying to see the last 6 hours of the chart,  (price variation 11400-11600)
but the chart on my actual focus (which is "last 6hours") it is not scaled!
The scale is considering all the data in my Database (which is going from 10000), which is no sense, in this way i obtain a flat chart...
![image](https://user-images.githubusercontent.com/58390904/90048721-2cbd4380-dcd4-11ea-8d80-e01567107e30.png)

There is any way to set something like "Autoscale only on the period of time that i'm looking" or i have to do it manually all the time?

**Comment by torkelo** [comment]
Must be that you are not filtering the data with the time range in your query (Depending on your data source there are different macros or options to include dashboard time range in your query)

**Comment by octapudus** [comment]
how exactly can i filter?
do you have any example?
