### ISSUE TITLE
feat: Elasticsearch & templating (variable queries, etc)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2696]

**Comment by torkelo** [comment]
Progress on this
![image](https://cloud.githubusercontent.com/assets/10999/10012872/698514ee-610c-11e5-9d0d-978978596ca9.png)

2 types of metric find queries are working now (used for templating and metric/field lookup in query editor).

`{"find": "terms", "field": "@hostname"} `
`{"find": "fields", "type": "string"}` 

The json string syntax is not pretty or readably, but that can be improved later with a UI. For now just looking at getting the features working and json will allow easy parsing and turning into a elasticsearch query. Want to add the ability to filter term values by lucene query and also fields by doc type, but think that can wait for another github issue and Grafana release. 

The main thing that is not working is multi select (All or selecting multiple values in variable). The only formats currently supported are regex values and wildcard. So All does work actually if you set all format to wildcard. 

Its the multi select that needs a new format compatible with lucene.

**Comment by torkelo** [comment]
Does anyone know of a elasticsearch lucene querystring syntax that would work with multi select? 

`@hostname:[[variable_value]]`

So variable_value will be replaced with something. And the only thing I can find is the AND syntax but that does not work as that need to include the field name. Glob expressions are not supported, and regex needs to target a single field not all fields like the query string filter allows.

**Comment by felixbarny** [comment]
Have you tried `@hostname:(host1 OR host2 OR host3)`?

**Comment by torkelo** [comment]
@felixbarny nice that works!

**Comment by torkelo** [comment]
Added new templating all format and multi select format: `lucene`

![image](https://cloud.githubusercontent.com/assets/10999/10018342/3c50a8e2-6136-11e5-8e73-2fa3b05744b9.png)

**Comment by pewpewp3w** [comment]
Hello, cool feature, big thanks

But have one problem: with query like `{"find": "terms", "field": "hostname"}`I got ES query `...."aggs": {   "1": {   "terms": {  "field": "hostname",  "order": {  "_term": "asc"   }   }   }   }`, which returns only first 10 found terms. Is it possible to change ES default 10 limit to another value?

**Comment by torkelo** [comment]
did not know ES had a default limit of 10

**Comment by felixbarny** [comment]
Size=0 means unlimited

**Comment by felixbarny** [comment]
Should we create a separate issue for the terms size?

**Comment by torkelo** [comment]
Yes!  Please do, so I don't forget it :)

**Comment by felixbarny** [comment]
Just found out that this also works: `{"find": "terms", "field": "@hostname", "query": "lucene: query"}`

**Comment by kartiksomani** [comment]
Hi, I have got n number of fields coming from an elasticsearch data source, and I want  one query corresponding to each value. So I should see n lines, 1 for each field, on the graph. n is not fixed. Is this possible using templates?

**Comment by torkelo** [comment]
@kartiksomani not sure you can do that in the Elasticsearch http api, each field requires it's own aggregation definition in the query so it not just templating. You might be able to do create a template variables with all fields and then repeat a graph for each field

**Comment by tymofii-polekhin** [comment]
Hello, can i use filters inside such query `{"find": "terms", "field": "host"}`?
I have 2 different clusters reporting, with `cluster` field in each document, which is a variable in grafana: `{"find": "terms", "field": "cluster"}`.
Can i use this to variable to filer out query for hosts, to get only hosts from specific cluster?
Something like this: `{"find": "terms", "field": "host", "filter":{"cluster":"$cluster"}}`?
Thanks!

**Comment by torkelo** [comment]
think "query": "my query"  should work, not sure

**Comment by Mormaii** [comment]
I don't see an option of multi select with elasticsearch. I've got my templating working with elasticsearch using a query like this one:

{"find": "terms", "field": "hostname", "query": "hostname:*clavc*"}

But if I enable multi select it won't graph multiple servers on the same graph.

**Comment by Mormaii** [comment]
The templating interval doesn't work either.

![screenshot from 2016-09-16 18-32-23](https://cloud.githubusercontent.com/assets/4213727/18601855/dd556b4e-7c3b-11e6-9e86-a8d6a0d69594.png)

The interval is set to $interval with 6hs and it still shows as a 30s one

**Comment by Mormaii** [comment]
@torkelo Worked perfectly by renaming the variable.

**Comment by faxm0dem** [comment]
thanks for fixing the limit, but it turns out I need the limit to be configurable :-)

**Comment by LeThuyVN** [comment]
{"find": "terms", "field":"$value"} ?????????? we have list of fields, how to parameter ($value) for field?

**Comment by faxm0dem** [comment]
@LeThuyVN using another template variable

**Comment by LeThuyVN** [comment]
may you specify it? many thanks

**Comment by faxm0dem** [comment]
* Template variable `rack`:
```json
{"find": "terms", "field": "rack", "query":"*"}
```
* Template variable `host`:
```json
{"find": "terms", "field": "hostname", "query": "hostname:$host"}
```

**Comment by LeThuyVN** [comment]
hii faxm0dem,
In your answers, the value in "field" is static, and you have to change it manually, in my question, I want to create dynamic value for field, when the variable change the value in field will change automatically.

**Comment by LeThuyVN** [comment]
hii towolf,
I want to create dynamic value for field, when the variable change the value in field will change automatically. Like

$field {"find": "fields", "type": "keyword"} >>> List all fields we have with type = keyword
when we chose value of fields we have corresponding results for $query
$query {"find": "terms", "field": "$field"}

for example if $field is source.keyword
$query is /usr/share/filebeat/customerLogs/counters1
/usr/share/filebeat/customerLogs/counters2
/usr/share/filebeat/customerLogs/counters3
/usr/share/filebeat/customerLogs/counters4
.....

similar if the value of $field changes to hostname.keyword, server.keyword, ... we have values for $query

**Comment by faxm0dem** [comment]
did you try? is there an error message? let us discuss this elsewhere, contact me privately or on IRC

**Comment by ThuyLeVn** [comment]
thanks, may you go https://community.grafana.com/t/elasticsearch-template-filter-field/1411, we can disscuss more about this issue. Here, I feel very mess now
