### ISSUE TITLE
OAuth2: GenericOAuth should handle GZIP/DEFLATE compressed payloads in JWT

### ISSUE THREAD

**Issue by billoley** [grafana/grafana#26967]
If the JWT header indicates zip=GZIP or zip=DEF, then the JWT payload needs to be uncompressed after base64 decode and before unmarshalling to the UserInfoJson struct.

OAuth2 token providers can choose to compress the payload portion of the JWT and this change would improve the generic OAuth2 implementation's compliance with the standard.

**Comment by sakjur** [comment]
[JSON Web Encryption/RFC7516 4.1.3](https://tools.ietf.org/html/rfc7516#section-4.1.3) defines the `zip=DEF` header and further points to the [IANA Web Encryption Compression Algorithms](https://www.iana.org/assignments/jose/jose.xhtml#web-encryption-compression-algorithms) list for further compression algorithms which doesn't include GZIP, I also don't see any movement on the [jose-reg-review@ietf.org](https://mailarchive.ietf.org/arch/browse/jose-reg-review/?q=GZIP) mailing list for the inclusion of GZIP in that list.

Is `GZIP` defined as part of JOSE somewhere else?

**Comment by billoley** [comment]
io.jsonwebtoken:jwt supports both DEF and GZIP -- that's what I'm using in Java
https://github.com/jwtk/jjwt/blob/master/impl/src/main/java/io/jsonwebtoken/impl/compression 
Added in 2015 under issue: https://github.com/jwtk/jjwt/issues/52 with no discussion about standards vis-a-vis GZIP.

I'm OK dropping GZIP.  I have agreement that our authorization layer can switch to using the more compliant DEF and it will be seamless in any case.

**Comment by sakjur** [comment]
👍 Thank you for the reference. You can keep the GZIP algorithm, I just wanted to know where it came from. Prior implementation in JJWT is sufficient proof of usefulness for me.
