### ISSUE TITLE
Can't run "yarn start" after building Grafana from source on Windows 10 64

### ISSUE THREAD

**Issue by ladamiak** [grafana/grafana#26975]
After building Grafana from source on Windows 10 with "go run build.go build" I can't run the "yarn start" for getting my dev environment up and running.

I get this error log:

```
C:\Users\***\go\src\github.com\grafana-7.1.3-master>yarn start
yarn run v1.22.4
$ grafana-toolkit core:start --watchTheme
error: unknown option '--watchTheme'
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by sakjur** [comment]
Did you run `yarn install --pure-lockfile` before running `yarn start`? It's the most common reason why `yarn start` doesn't work (I forget about it probably 90% of the time after pulling the latest commit 🙈)

**Comment by ladamiak** [comment]
Thanks @sakjur , but yes... I did, many time, but I always get this error:
`error An unexpected error occurred: "https://registry.yarnpkg.com/rxjs/-/rxjs-6.5.5.tgz: ESOCKETTIMEDOUT".`

Already tryed the "yarn add file:C:\rxjs-6.5.5.tgz -W" but I get the same error. No matter what, I always get this error.

When I try to get this file from browser I can download it normaly.

**Comment by peterholmberg** [comment]
you should only have to run `yarn start`. In the terminal output above you've run `yarn run yarn start`
