### ISSUE TITLE
change time range cause js error

### ISSUE THREAD

**Issue by jinlongwang** [grafana/grafana#26977]
**What happened**:
Recently I upgraded grafana to 7.0, and there is a dashboard. When I switch the time range, js reports an error, causing the page to be inoperable
![image](https://user-images.githubusercontent.com/2275120/90094130-bbc36d80-dd5f-11ea-8605-cdb5ff6091af.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.0-beta2 (4959658136)
- Data source type & version: opentsdb
- OS Grafana is installed on:  Mac & Win
- User OS & Browser:  chrome
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Try latest 7.1.3 release

**Comment by torkelo** [comment]
will re-open if you continue to have this problem. And please add the dashboard json

**Comment by jinlongwang** [comment]
hi, @torkelo 7.1.3 continue to have this problem. the dashboard is has lot of variable but it's ok on grafana 6.3.4.

and 

when i visit this dashaboard without variable it's ok; 

like
`https://xxxx/d/j8KqGaTik/indicatordashboard?orgId=1`

but when i pass variable by url this problem will show up

like
`https://xxxxx/d/j8KqGaTik/indicatordashboard?orgId=1&from=now-15m&to=now&var-kafka_consumer_group2=&var-kafka_topic=qrec_rel_cascade_rough_train_data&var-training_ps=bm_vip_yehao_b38&var-training_ps=bm_vip_yehao_b38&var-training_model0_md5=a38c73453ae61d1dfa5cad5d57725354&var-training_model0_name=qrec_dr_r2s_recall_14807_v18_r547567_0&var-training_model5_md5=None&var-kafka_cluster=data.etl.kafka.recommend_training5.monitor&var-kafka_topic2=&var-from=1597219720000&var-job_id=547567&var-training_newuser_model0_md5=45e02b6a2f56a5756895997bd7698358&var-training_model3_md5=None&var-to=1597228222000&var-kafka_cluster2=&var-training_model4_md5=None&var-model_id=qrec_dr_r2s_recall_14807_v18_r547567&var-training_model9_md5=None&var-training_model8_md5=None&var-training_model6_md5=None&var-kafka_consumer_group=qrec_dr_r2s_recall_14807_v18_r547567&var-training_model1_md5=None&var-training_model7_md5=None&var-data_source=default&var-training_model_name_prefix=qrec_dr_r2s_recall_14807_v18_r547567&var-training_model2_md5=None&var-training_group=bm_vip_yehao_b&refresh=15m`


there is dashboard json:


[IndicatorDashboard-1597229408022.txt](https://github.com/grafana/grafana/files/5067648/IndicatorDashboard-1597229408022.txt)

**Comment by jinlongwang** [comment]
hi， @torkelo i found this problem because i passed same variable twice
![image](https://user-images.githubusercontent.com/2275120/90121979-4079b000-dd8f-11ea-91f6-5bb553a7c65a.png)

if i delete one var-training_ps it will be ok
