### ISSUE TITLE
CodeEditor: No Copy option in Content textbox when right clicking

### ISSUE THREAD

**Issue by peawet08** [grafana/grafana#26988]
Hi!

**What happened**:
Whilst editing a text panel I wanted to copy and paste the text to another panel.  I highlighted the text (HTML or Markdown) and right clicked on the highlighted text and the resulting right click option did not display an option to copy the text.  I was able to use Ctrl+C to copy it though.
I tried other textboxes on the page and they did allow me to select copy.

**What you expected to happen**:
The Copy Option should be available whilst in a textbox

**How to reproduce it (as minimally and precisely as possible)**:
As described above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.3
- Data source type & version:: None, just text
- OS Grafana is installed on:  Centos 7
- User OS & Browser:  Chrome or New Edge
- Grafana plugins:
- Others:

![2020-08-13 12_04_09-](https://user-images.githubusercontent.com/6518323/90128116-39867980-dd5e-11ea-996c-d7ff3ed5c3a2.gif)

**Comment by peterholmberg** [comment]
this is because this is not a regular textbox but a code editor compoenent made by https://github.com/react-monaco-editor/react-monaco-editor

**Comment by torkelo** [comment]
Does not look like there is much we can do right now, the problem in the editor component https://github.com/microsoft/monaco-editor/issues/1084
