### ISSUE TITLE
dashboard export for sharing externally : subpar experience for dashboards where datasource is templated out

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#26986]
Hello,
the [metrictank dashboard](https://github.com/grafana/metrictank/blob/master/dashboards/main/metrictank.json) uses a template variable for datasource, such that the user can easily dynamically switch the datasource, and *all* queries on the dashboard use the selected datasource.

When exporting this dashboard for external use, the experience isn't so smooth though, because:

1) upon import of the dashboard, you _have_ to choose a graphite datasource, but it will effectively be ignored because no panel uses it. really if all queries run against a templated datasource value, there is no point bothering the user to ask for a datasource to use. this is a confusing experience, especially because grafana.com requires that uploaded dashboards are exported with "export for external sharing", even though this complicates things for no good reason (for a dashboard where datasource is templated out)
2) it makes the dashboard json confusing. It adds:
```
+  "__inputs": [
+    {
+      "name": "DS_METRICTANK",
+      "label": "metrictank",
+      "description": "",
+      "type": "datasource",
+      "pluginId": "graphite",
+      "pluginName": "Graphite"
+    }
```
and then makes many changes like this:
```
-      "datasource": null,
+      "datasource": "${DS_METRICTANK}",
```
these changes are applied to panels that are empty (I think they represent rows), and on panels that then have child panels that have the proper values, e.g. like so:

```
    {
      "collapsed": true, 
      "datasource": "${DS_METRICTANK}",
      "gridPos": {
        "h": 1,       
        "w": 24,
        "x": 0,       
        "y": 7   
      },               
      "id": 38,         
      "panels": [  
        {
          "aliasColors": {},
          "bars": false,
          "dashLength": 10,
          "dashes": false, 
          "datasource": "$datasource",
          ...
```
this is quite misleading as this datasource isn't actually used

**Comment by sakjur** [comment]
It seems to me that adding the datasource selector could be a (default?) option when importing a dashboard? That would still reduce the quality for your particular case, but it'd improve other dashboards which isn't doing what you're doing 🤔

Besides that: Do you have any suggestion for how to label this better? I'm a bit at a loss, it feels like this is more a feature request than a bug, but also more a discussion than a feature request.

**Comment by Dieterbe** [comment]
>It seems to me that adding the datasource selector could be a (default?) option when importing a dashboard? 

I don't follow. are you talking about the "import" menu where you choose the datasource (that already exists and is enforced, which is my problem), or are you saying that imported dashboards should get a variable selector to choose a data source? (that makes things possibly more confusing for users. or at least distracting for cases where only 1 data source makes sense)

> Besides that: Do you have any suggestion for how to label this better? I'm a bit at a loss, it feels like this is more a feature request than a bug, but also more a discussion than a feature request.

i don't know what kindof labeling taxonomy makes sense within Grafana. and i don't really have a preference, I care more about the problem being discussed, and hopefully leading to an improvement.

**Comment by sakjur** [comment]
> I don't follow. are you talking about the "import" menu where you choose the datasource (that already exists and is enforced, which is my problem), or are you saying that imported dashboards should get a variable selector to choose a data source? (that makes things possibly more confusing for users. or at least distracting for cases where only 1 data source makes sense)

I mean somewhere in between those two: That one option in the menu would be to add a template variable dropdown. And then I'm saying that that wouldn't solve anything for you, but it could improve the experience for getting a dropdown added automatically to dashboards which aren't adding a dropdown by default.
