### ISSUE TITLE
support "year-on-year statistics" and "month-on-month statistics" in one graph

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2698]

**Comment by torkelo** [comment]
????????????

**Comment by godfreyhe** [comment]
one graph show two lines for comparing
1. year-on-year statistics: one is the data of some year, and another is from the same period a year ago. such as two lines of 2014 and 2013
2. month-on-month (or  quarter-on-quarter) statistics: one is the data of some month, and anther is  from the previous month. such as two lines of July 2014 and June 2014

**Comment by srinathganesh** [comment]
any update to this?
