### ISSUE TITLE
Testing: Switch to React Testing Library

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#26989]
Recently, while writing some tests for a component using @grafana-ui's `Form` component with Enzyme, I thought that this way of testing is very inefficient and time-consuming. Then I wrote the same tests with [React testing Library](https://github.com/testing-library/react-testing-library) and had a much better experience. Since the talks of switching to RTL has been going on for quite a while now, I think now would be a good time to have a discussion about this. 

Enzyme vs RTL: 
I made a [gist ](https://gist.github.com/Clarity-89/0e484d76cb612f396c76173c9e55b383) where I wrote the same tests using both libraries and using RTL was a much better experience. 

Pros of using RTL:
- A more integration-minded testing approach where the components are being tested from the user interaction perspective vs focusing on the implementation details. This makes tests less brittle. 
- Better support for components with async logic, no need to use `act` in most of the cases or do smth like `wrapper.update()` to trigger state changes.
- Works really well with react-hook-form, which is the base for @grafana-ui `Form` component and is a [recommended way](https://react-hook-form.com/advanced-usage#TestingForm) to test RHF.
- Lots of queries to get DOM elements, particularly by text, which requires some extra code to do in Enzyme.
- Can be used together with Enzyme until the tests are refactored. It's a dev dependency, so shouldn't impact the production build.

Cons:
- May require custom queries to get elements by `aria-label`, the preferred way is to use `data-testid`.

This issue is intended to be a starting point for discussion so feel free to please some comments, I probably have missed some details.

**Comment by rdubrock** [comment]
FWIW I'm pretty sure that RTL's `getByLabelText` will match elements with an `aria-label` attribute, but isn't the recommended way to do it since users can't actually see the text. It sort of breaks the core RTL concept of testing your code the same way your users would use your code (relying on `data-testid` has the same issue).

Another pro to toss on the pile: code that gets tested by RTL will end up more accessible since it's queries are based on browser accessibility features.

**Comment by stevenvachon** [comment]
It seemed to me that this was already happening with newly created test suites. If it's not too much work, it'd be nice to update existing tests too.

**Comment by Clarity-89** [comment]
> If it's not too much work, it'd be nice to update existing tests too.

A quick search shows that we have a lot of tests with Enzyme in the OSS alone, so I think a good first step would be to install RTL and use it for writing new tests, while at the same time gradually refactor the old Enzyme tests.

**Comment by s-h-a-d-o-w** [comment]
Having used predominantly RTL in projects recently and preferring it, I'm still not sure that this should be a binary choice and Enzyme should be fully dropped.

I would merely make RTL the preferred choice and ensure that people have everything they need to work with it (i.e. keep jest versions up to date, also in grafana toolkit).
But I would recommend not to try using RTL where Enzyme would be more suitable. Also not refactor already existing Enzyme tests unless it seems apparent that they would be more straightforward or more robust with RTL.

**Comment by s-h-a-d-o-w** [comment]
Oh and about this:

> May require custom queries to get elements by aria-label, the preferred way is to use data-testid.

If it is actually preferred [**not** to use `data-testid`](https://testing-library.com/docs/dom-testing-library/api-queries#bytestid) if you can at all avoid it:

> In the spirit of the [guiding principles](https://testing-library.com/docs/guiding-principles), it is recommended to use this only after the other queries don't work for your use case. Using data-testid attributes do not resemble how your software is used and should be avoided if possible. That said, they are way better than querying based on DOM structure or styling css class names. Learn more about data-testids from the blog post "Making your UI tests resilient to change"

It seems to me that if there is no way to refactor a given component in a way that the test can be done without using `data-testid`, it might be a use case for Enzyme.

**Comment by torkelo** [comment]
Nice! 

I think we should go with this and start phasing out enzyme. Seems many have had issues with enzyme after hooks was introduced and seems like there are many advantages to react testing library

**Comment by stevenvachon** [comment]
We use `aria-label` for E2E tests. We could reuse those for unit (ReactDOM) and integration (jsdom) tests.
