### ISSUE TITLE
Regression: alerting with clickhouse-grafana datasource broke between grafana 7.0.5 and 7.1.3

### ISSUE THREAD

**Issue by Farfaday** [grafana/grafana#26992]
**What happened**:
We have alerting configured with clickhouse-grafana datasource that was working fine with 7.0.5.
Upgrading to 7.1.3 set all the alerts in "Query returned no data" status.
No config change from our side between the two versions.
We are using the environment variable "GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=vertamedia-clickhouse-datasource" and the graphs using the clickhouse-grafana datasource are displayed.

**What you expected to happen**:
Alerting should work.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version: ClickHouse datasource version 2.1.0
- OS Grafana is installed on: docker container grafana/grafana
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sakjur** [comment]
ClickHouse is a community plugin, could you please start with opening an issue with their issue tracker ( https://github.com/Vertamedia/clickhouse-grafana/issues ). In case this is a backwards incompatible change we introduced the additional information which can be produced by the maintainer of a plugin makes it possible for us to track down and fix the bug in a much more efficient manner than if we were to try to reproduce this ourselves.
