### ISSUE TITLE
Direct mode causes Cross Site Scripting errors(Elasticsearch)

### ISSUE THREAD

**Issue by warroyo** [grafana/grafana#2699]
I have multiple ES servers behind a load balancer, when I try to use direct mode when configuring a data source I am seeing the below error in the console.

`XMLHttpRequest cannot load https://myesvip.com/logstash-2015.09.08/_stats. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://my.grafana.com:3000' is therefore not allowed access.`

I believe the origin header should not be set to the server address when using direct access.

**Comment by torkelo** [comment]
this is set by the browser and there is no possibility to override this (other than opening chrome with special flags that disable security settings).

If you want to use ES in direct mode from Grafana you need to add CORS headers to the load balancer that informs chrome (or any browser) that this web service can be used from other domains (for example your grafana install)
