### ISSUE TITLE
Text Panel Rendering fails when clicking "Direct link rendered image"

### ISSUE THREAD

**Issue by dattasoumya92** [grafana/grafana#26996]
**What happened**: Text Panel's Direct link rendered image getting timed out after 60 seconds with below message:

> Grafana / Server Error
> Sadly something went wrong
> Rendering failed.
> 
> Check the Grafana server logs for the detailed error message.

**What you expected to happen**: Display the rendered image of the text panel with its content.

**How to reproduce it (as minimally and precisely as possible)**: 

1. Launch a grafana instance (v7.1.3) with [Grafana-Image-Renderer](https://grafana.com/grafana/plugins/grafana-image-renderer) plugin installed. 
2. Create a text panel in a dashboard. Add any text in the content and give any title in the panel title. 
3. Then save the dashboard. 
4. Now from the panel's menu option, click on share and click on "Direct link rendered image" in the link tab.

A new tab will open and it will timeout after 60 seconds with a message "rendering failed".

GIF > 
![text_panel_rendering_issue](https://user-images.githubusercontent.com/69461309/90187061-d1c04500-ddd6-11ea-81d1-d3f577154dbf.gif)

The gif shows the aforementioned issue, when the new tab opens, it loads until the error page comes after 60 seconds timeout.

**Anything else we need to know?**: I used only a text panel with a title and a single line content in a single dashboard, not using any datasource.

**Environment**:
- Grafana version: v7.1.3
- Data source type & version: no datasource used.
- OS Grafana is installed on: Installed using grafana docker-ubuntu image on windows 10 machine.
- User OS & Browser: Windows 10 and Chrome Browser Latest version.
- Grafana plugins: [Grafana-Image-Renderer](https://grafana.com/grafana/plugins/grafana-image-renderer)
- Others:

**Comment by torkelo** [comment]
This is due to text panel not being a data panel 

The way that Grafana communicates to the browser rendering the image is via this line:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L250

But that happens only for data panels. Not sure the best way to solve this for non data panels (that can have async logic in them)

**Comment by dattasoumya92** [comment]
> This is due to text panel not being a data panel
> 
> The way that Grafana communicates to the browser rendering the image is via this line:
> https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelChrome.tsx#L250
> 
> But that happens only for data panels. Not sure the best way to solve this for non data panels (that can have async logic in them)

Hi,

Not sure if it helps, i would to like to point out that it works fine with a Grafana instance of version 7.0.6 i.e., the text panel rendered properly with the content. So, may be something went wrong starting from v7.1.0

Thanks

**Comment by torkelo** [comment]
We migrated this panel to react in 7.1
