### ISSUE TITLE
Grafana 7 unresponsive for long time (+100x longer than 6.4) when dashboard changed/exited (example Dashboards/Home pressed)

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#26991]
**What happened**:
Grafana 7 (all versions) freeze for long time when exiting complex dashboards.
Simply login as **admin/editor** and load large/complex dashboards with large amount of template variables and repeating panels (under collapsing raws), all panels are closed (rows). 
Once template variables populated select dashboards/Home from left side of the UI (link refer to grafana http://host:port) result longer than 1min freeze.

Based on debugger the freeze is in event handling, no network etc activity seen.
![image](https://user-images.githubusercontent.com/19704268/90124186-ab63c080-dd68-11ea-90e4-bf4f90a9c6e1.png)
All time spent on 
![image](https://user-images.githubusercontent.com/19704268/90125009-f6320800-dd69-11ea-8876-7d29cce9cc11.png)
and each DashboardModel.ts get stuck for few seconds here.
![image](https://user-images.githubusercontent.com/19704268/90126325-2a0e2d00-dd6c-11ea-9063-fcaf88e692ca.png)

Sounds that Grafana try to identify if changes has been done which fails/timeouts or just take long time (sometimes ask if changes should be saved, sometimes switch directly to home screen but always takes long time).
Save freeze also seen when save as used (freeze after save when needs to switch to new dashboards)

In Grafana 7 freeze is not seen in **reader** mode.

In Grafana 6.x this freeze is not seen in admin/editor mode, exiting takes based on debug/performance 1s (same complex dashboard from 7.1.2/7.1.0 imported to 6.4.3 (table-old changed back to table before import). 

Slowness seems to correlate with the complexity of the dashboards and total number of dashboards panels which would be rendered if row would be opened.
- Removing 3 most complex RAW which contained +1000 panels or Bar gauges reduce the freeze to half alone. 
- By default all our template variable use "all" values, If most influential template variable it configured to show 2 service instead of all(+200) the exit takes few second.
- With small Grafana 7 dashboards there is no visible freeze, switch take 1s based on performance.

Note: 
In Our dashboard all panels are under collapsing rows so by default nothing is shown. Each row can contain few dashboards but due repeating rows in individual panel there can be hundreds or even thousands of panels opened if all content would be selected to be shown. Thus total number of panels in all rows when everything would be shown is probably 100k. 

This hints that there are something which is 100x slower in Grafana 7 or something is done 100x more frequently than in 6.x. 

I suspect that code which is checking if something has changed is sub optimal and maybe scan through all possible panel/template variable combination instead of having more intelligence to detect the changes.

**What you expected to happen**:
Should not take longer than 1 second

**How to reproduce it (as minimally and precisely as possible)**:
No exact repro step identified, related to total number of panel combination which would be shown if all rows are expanded.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.10, 7.12
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows 10, Linux
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Hi @jtorkkel and thanks for reporting this, this seems super interesting. We did a massive migration of the templating system from Angular => React between 6.x and 7.0 so I'd really like to find and solve this issue but I need your help.

You write that there is no network activity seen when you navigate back to Home but before you navigate back to Home do you still have any pending http requests or are they all finished?

**Comment by torkelo** [comment]
you have a row with a 1000 panels?

**Comment by jtorkkel** [comment]
@torkelo, Some complex row has max 6 panel (graph and bar gauge, like JVM memory and GC metrics next to each other as many panels needed to understand memory status), Many rows has just 1 or few panels.
But many panel use repeating rows where template variable control how many are repeated. If I have more than 1 panel for row I repeat panel vertical, otherwise horizontally.

Same dashboard has also rows which has few panels but do not use repeating rows (rates etc. ) and aggregate all service instance using same template variable "All".

And same dashboards has alert row where panel use repeating but only list the service instance which alerts within timerange or at the moment.

As said by default rows are collapsed, and each template variable would list "All". Due large number of template variable and value sin template variable loading dashboard or switching time frame take few seconds.

So user can select which row to expand and through template variable config to select if all service instance are to be shown/aggregate or just specific one.

Imagine you have 300 service instance instance in your system.

User can open system row which aggregate all traffic from 300 service instance and see overall system status/rates etc.
User can open system alert row which use repeating panels and show which of the 300 service has alerted.
 
Then based on alerting you want to deep dive into few specific service instance. You select the desired service instances from  template variable (search, select --> all is not selected any more) and then expand desired row having repeating rows for more detailed dashboards. If row has 6 panels vertically then each line contain 6 service specific panels and next service panels are in next line. If panels are repeated horizontally, then panels are repeated maybe max 4 horizontally and if more instance selected they continue to next line. 

Intend is to allow user use to select "all" vs "limited number of  services" to be shown in different part of the dashboards.

If you want to deep dive only to 1 service instance then I use link to another dashboards which has disabled all and allow only "single" selection.

If you do accidentally leave "all" to template variable and expand the row it take long tome to render worst case 1800 (300x6) panels but that is human mistake and not intended use of panel. Pressing "d C" will collapse all dashboards and you can fix selection.

When you have tens of such rows in dashboards to enable deep dive to different part of the system within same dashboard the total number of dashboards when all rows would be expanded using template variable "all" would be huge. 

In practice this large dashboard works very fast when you open only few rows and do not select all service when row containing repeating panels is opened considering large number of rows with panels repeating resulting huge total size of panels when all expanded. Large dashboard is to enable deep diving to all part of the system.  

The only issue is that closing dashboard is super slow in admin/editor due the behavior change in Grafana 7. Seems that internally system expands all rows when closing and try to identify changes in configuration/about or in template variables which probably result the slowness. Or maybe something is called again and again recursively resulting logarithmic slowness. 
Closing is used when you switch the dashboards or use links to other dashboards (new tab not opened) or press home as example. In Grafana 6 close was fast.

In reader mode all works as no savings in exit.

**Comment by jtorkkel** [comment]
@hugohaggmark , I waited 10 second before exit to secure that dashboard and template variable loading is complete.  Debugger also confirm it.

**Comment by hugohaggmark** [comment]
> @hugohaggmark , I waited 10 second before exit to secure that dashboard and template variable loading is complete. Debugger also confirm it.

thank you for the update @jtorkkel

**Comment by dario-l** [comment]
I have very simple dashboard [1902](https://grafana.com/grafana/dashboards/1902) and after upgrading from 6.x to 7.2 I see that grafana is much more less responsible that in 6.x. Firefox, Chrome, no difference. This simple dashboard freezes like a hell. 😞

**Comment by mahadi** [comment]
Same for me upgrading to grafana 7 always freezes my dashboard for many seconds ~5-10s. I did a quick performance trace with the developer tools and it reports long delays when leaving a panel's grapharea. Triggering event is onmouseout.
My dashboard only has 5 panels.

**Comment by ashharrison90** [comment]
i've created a test dashboard locally with 400 timeseries panels, and after scrolling through to load every single panel it can be slow to exit, but nothing like 1.5min. more on the order of 5-10 seconds. with no scrolling, it's more or less instant since only the first 30 or so panels are rendered.

@jtorkkel @dario-l are either of you still seeing this problem in grafana 8? we've made a number of performance optimizations since this issue was created, so i'm wondering if we can close this or not. wdyt? 😄

**Comment by dario-l** [comment]
Hi @ashharrison90 
Right now I'm using version 8.1.2 and it's great. I see not any lags. Dashboard the same. Thanks

**Comment by ashharrison90** [comment]
@dario-l that's great, glad you're enjoying the product 🙌 

with that in mind i'm going to close this issue

**Comment by jtorkkel** [comment]
Sorry, did not notice the question earlier.
Just downloaded 8.1.5 and still freeze for 2min while exiting large dashboard. 
Regression started in 7.0.0 and no progress since.

Freeze time increase exponentially when dashboard gets larger, when template variable size increase and dashboards contains row with repeating panels utilizing large template variables. 
So if you make your test dashboard larger you should be able to detect it.

The problem is that template variables has "all" as default value resulting that each row and each repeating panel is scanned through in exit, based on analysis millions of times.

If in largest template variable the all is disabled then by default only one value is selected by default and exit will be much faster.  But then practically impossible to select all few hundred services on dashboards which aggregates all template variables like total rate.

I have tried to workaround the problem by duplicating template variables. Allowing all for dashboards which aggregate data and disabling all which has repeating row. This complicated the dashboards but make exit faster as less looks to be scanned.

**Comment by ashharrison90** [comment]
@jtorkkel ah ok, let's track the problem using that issue then, thanks! 👍
