### ISSUE TITLE
Can't create graph because of Invalid date in 'Time ns' column

### ISSUE THREAD

**Issue by MichaelWGibson** [grafana/grafana#26997]
**What happened**:
Installed and set up Loki
Installed and set up Grafana
Added Loki as a Grafana datasource
Sent some log events to Loki
Graph won't work in a panel because the 'Time ns' field is set to 'Invalid Date'
Click explore from the graphs heading and the graph works perfectly

**What you expected to happen**:
Time ns & graphing field to work in panel, not just explore

**How to reproduce it (as minimally and precisely as possible)**:
Add Loki as datasource
Create a dashboard
Click add a panel
Select a Log label to query for
The panel says 'Unable to graph data, switch to table view'
Click switch to table view.

**Anything else we need to know?**:
I can inspect the json Loki s returning and the relevant part looks like this
`
{
          "stream": {
            "ExceptionDetail": "[(Type: System.Exception), (HResult: -2146233088), (Message: Test), (Source: null)]",
            "level": "error"
          },
          "values": [
            [
              "1597364358980135800",
              "Test\r\nTest\r\n\r\n"
            ],
            [
              "1597363037564108600",
              "Test\r\nTest\r\n\r\n"
            ],
            [
              "1597362649327833500",
              "Test\r\nTest\r\n\r\n"
            ],
            [
              "1597362589091270600",
              "Test\r\nTest\r\n\r\n"
            ],
            [
              "1597356858390625800",
              "Test\r\nTest\r\n\r\n"
            ],
            [
              "1597356485359122500",
              "Test\r\nTest\r\n\r\n"
            ]
          ]
        }

Right after selecting a log label I get
![BrokenGraph](https://user-images.githubusercontent.com/32117195/90210784-331eee80-ddac-11ea-8b82-8983a9b70285.PNG)

When I click switch to table view this what the panel looks like
![brokenPanel](https://user-images.githubusercontent.com/32117195/90210421-1e8e2680-ddab-11ea-913d-a6b76b72a652.png)

Clicking on the graph title -> explore
![workingExplore](https://user-images.githubusercontent.com/32117195/90210422-1f26bd00-ddab-11ea-8b90-85e4f06d35a8.png)

`

**Environment**:
- Grafana version: v7.1.3
- Data source type & version: Loki v1.6.0
- OS Grafana is installed on: Windows
- User OS & Browser: Windows/Chrome
- Grafana plugins: None
- Others:

**Comment by sakjur** [comment]
The graph shown in the explore view is not a regular graph, you'll have to apply some LogQL to get a similar result in a regular graph panel. You should get something like the graph in explore if you apply the following:

```
count_over_time({level="error"}[$__interval])
```

I'm closing this for now, let me know if this fixes your problem or if it still remains when doing so 🙂
