### ISSUE TITLE
Add source tarballs for prerelease (beta/rc/...) builds

### ISSUE THREAD

**Issue by rafalyesware** [grafana/grafana#2700]
Hi Torkel,

Would it be possible to include a source tarball that corresponds to the latest builds on the downloads page?  For releases one can always get this from the GitHub page, but for prereleases, there isn't enough information given to tell what exact version of the source was used to build the binary package.  In either case, I would think it would be very handy to have right along the build packages.

Thanks!
--rafal

**Comment by torkelo** [comment]
closing this for lack of interest
