### ISSUE TITLE
Can not login in 7.1.3 with Safari 11.1.2

### ISSUE THREAD

**Issue by yangliuyu** [grafana/grafana#27007]
**What happened**:
When upgrade our grafana server from 6.6.2 to 7.1.3, can not login with safari 11.1.2. Safari works with 6.6.2 and chrome works with both version.

**What you expected to happen**:
Can login grafana 7.1.3 with safari 11.1.2

**How to reproduce it (as minimally and precisely as possible)**:
Launch grafana server with docker
```
docker run -p 3000:3000 grafana/grafana:7.1.3
```
and open safari with http://localhost:3000 input username and password with both 'admin' then click "Log in", then click Skip, the browser redirect to login page.
![grafana713](https://user-images.githubusercontent.com/1361821/90240543-03c7ba80-de5c-11ea-958a-ffc48770b880.gif)

**Anything else we need to know?**:
logs:
```
t=2020-08-14T10:24:32+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2020-08-14T10:24:37+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=172.17.0.1 time_ms=0 size=29 referer=http://localhost:3000/login
```
![Screen Shot 2020-08-14 at 6 25 58 PM](https://user-images.githubusercontent.com/1361821/90240443-d549df80-de5b-11ea-9797-433de3feaac0.png)

safari login successfully in grafana 6.6.2
![Screen Shot 2020-08-14 at 6 30 53 PM](https://user-images.githubusercontent.com/1361821/90240901-aa13c000-de5c-11ea-9d3d-bd55a629f6ae.png)
![grafana662](https://user-images.githubusercontent.com/1361821/90241104-fbbc4a80-de5c-11ea-8614-ae12c2fbcb93.gif)

We also use tv browser to open grafana pages, these browser worked well with grafana 6.6.2 and they can not be upgraded.

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: Mac 10.13.6 and Safari 11.1.2
- Grafana plugins: N/A
- Others:

**Comment by sakjur** [comment]
Grafana only supports recently updated versions of web browsers. We'd accept a reasonable patch for fixing the login screen, but browsers outside of [our list of supported browsers](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers) not working is not considered a bug.

Since you're unable to upgrade MacOS+Safari to a later version I'd recommend installing Firefox or Google Chrome which are still receiving updates for older versions of MacOS.

**Comment by yangliuyu** [comment]
@sakjur could you please give some clue about the different login logic between 6.6.2 and 7.x (I'm not familiar with the go code), and I can try to fix it

**Comment by yangliuyu** [comment]
@sakjur we also use some android browsers running in TV device and we can not upgrade these browsers to latest version(chrome kernel).

After change credentials parameter to `same-origin` as in #27153 , I found another problem, datasource page can perform the datasource query well but data page hung in loading.

Datasource page in Android TV browser works fine.
![image](https://user-images.githubusercontent.com/1361821/91410660-cdd1ff80-e879-11ea-9122-9113ddb4c56d.png)

Data page in Android TV browser hangs in loading.
![Kapture 2020-08-27 at 15 17 37](https://user-images.githubusercontent.com/1361821/91410760-fa861700-e879-11ea-9ccb-74c8255fe33e.gif)

Data page in Mac chrome desktop browser workd find.
![Kapture 2020-08-27 at 15 22 13](https://user-images.githubusercontent.com/1361821/91410623-c14da700-e879-11ea-9136-c24b0655bfe9.gif)

**Comment by sakjur** [comment]
@yangliuyu I'm not sure there's enough RAM on the Android TV device to display the dashboard 🤔

**Comment by yangliuyu** [comment]
@sakjur quite sure it has enough RAM😄，we have used grafana from 6.4 to 6.6.2 for more than 1 year, all works fine except version 7.x

**Comment by yangliuyu** [comment]
I'm confirmed that the data is returned from backend api, but the fontend did not parse the response data and display it correctly.
![Screen Shot 2020-08-27 at 6 45 41 PM](https://user-images.githubusercontent.com/1361821/91433248-95d8b580-e895-11ea-82d9-d0f00b8f2d51.png)

The datasource query works on HTTP GET Method
![Screen Shot 2020-08-27 at 6 53 02 PM](https://user-images.githubusercontent.com/1361821/91434002-c2410180-e896-11ea-8efd-bfaf752dc736.png)

**Comment by yangliuyu** [comment]
https://github.com/grafana/grafana/blob/9893b8c53d77079e135e361cd32899c2d3671610/public/app/core/services/backend_srv.ts#L191 seems problem from here

**Comment by sakjur** [comment]
Is that the TV's browser? Android 6.0 and Chrome 44 are both five years old, it's not considered a bug that Grafana dropped support for it, since our list of [supported web browsers](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers) defines that only current releases of the browser is supported.

We tend to recommend avoiding running Grafana on in-TV browsers as TV vendors are seemingly unwilling to ever provide any kinds of reasonable updates for their software once the model has been superceded by a newer one.

**Comment by yangliuyu** [comment]
@sakjur TV browser with fullscreen mode is a low cost for BI solution which don't need a pc or raspberrypi for running a browser. Some people still using and like it😄 #25507 .I think we may fix it as best as we can. If it is too difficult we may change to another solution which is installing the [chrome android version](https://apkpure.com/google-chrome-fast-secure/com.android.chrome/versions) and active the fullscreen mode.
