### ISSUE TITLE
Insights Analytics data (time series) are repeated during timeline

### ISSUE THREAD

**Issue by eduardoluizm** [grafana/grafana#27013]
**What happened**:

Hi, I don't know if is it a bug or some configuration that I can't change.

Well, I'm trying to create a Graph using a Application Insights data from azure. When I use the service "Insights Analytics" the values on columns are repeated during timeline, as you can see bellow, when I transform it to Time Series.

![image](https://user-images.githubusercontent.com/3385836/90286016-564cab00-de4b-11ea-940a-6c84dcf3fc09.png)

**What you expected to happen**:

If I use a service type "Application Insights" it works, but I have no options to improve my query as I wish.

![image](https://user-images.githubusercontent.com/3385836/90285837-fc4be580-de4a-11ea-9a3f-7186b009ed73.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

- Grafana version: 7.1.3
- Data source type & version: Azure Analytics/Insights
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows/Edge
- Grafana plugins: Graph
- Others:

**Comment by torkelo** [comment]
What do you mean by. "When I use the service "Insights Analytics" the values on columns are repeated during timeline" ? 

Can you show query response and expected result in graph & table vs actual

**Comment by eduardoluizm** [comment]
No problems. When I chose Azure Monitor, has two service types for Insights.

![image](https://user-images.githubusercontent.com/3385836/90397094-b58a0580-e06d-11ea-9d84-8c135f5f5939.png)

Application Insights has defined metadata options as you can see below.
![image](https://user-images.githubusercontent.com/3385836/90397197-df432c80-e06d-11ea-9ea6-6e4546163c78.png)

When I open Query Inspector, is possible to see that each serie doesnt not repeat "last value".
![image](https://user-images.githubusercontent.com/3385836/90397306-0e599e00-e06e-11ea-9719-5c6bb7466a76.png)

It doesnt ocurrs when i chose "Insights Analytics". With this, I can customize my own query, I can use parse, project, multiples filters, etc..  We need to select format as "Time Series" to create one serie for each grouped data and here is the problem.
![image](https://user-images.githubusercontent.com/3385836/90397656-8de76d00-e06e-11ea-8147-9b3361fb3d2e.png)

When I click on Query Inspector, you can see that for each serie (column) the last value is repeated until the end.
![image](https://user-images.githubusercontent.com/3385836/90397805-c5561980-e06e-11ea-9cb9-2f7e5309b13d.png)


I hope it can help you.
Thanks

**Comment by kylebrandt** [comment]
@eduardoluizm Thank you for the detail in your last comment. This was a mistake in the selected mode for time series processing, and your feedback helped me find it. 

I have made a PR so there will not be repeated values and they will be null instead (like you are seeing with application insights).
