### ISSUE TITLE
Logging: output has a typo "lvl=eror" should be "lvl=error"

### ISSUE THREAD

**Issue by ruizmarlon** [grafana/grafana#27015]
**What happened**: Viewing output of grafana logs using loki shows a typo for grafana logs `lvl=eror`

**What you expected to happen**: Expected output to be spelled correctly as `lvl=error`

**How to reproduce it (as minimally and precisely as possible)**: Use grafana to setup dashboard -> loki source  and view grafana job logs.

**Anything else we need to know?**: It is possible this is being caused by loki but I'd check grafana first.

**Environment**: k8s helm chart grafana-5.5.5
- Grafana version: 7.1.1
- Data source type & version: loki chart loki-stack-0.39.0 app version v1.5.0, prometheus v2.17.2
- OS Grafana is installed on: ubuntu arm64 (raspberry pi4)
- User OS & Browser: Mac Mojave / Firefox 78.0.1
- Grafana plugins: loki, prometheus
- Others:

<img width="1218" alt="eror" src="https://user-images.githubusercontent.com/43421777/90307540-20d4ab80-dea5-11ea-9cc6-b5a4dd2b5d5a.png">

**Comment by zoltanbedi** [comment]
Thanks for reporting this @ruizmarlon but this is intended. See https://github.com/grafana/grafana/issues/25052#issuecomment-633438395

**Comment by ruizmarlon** [comment]
ok, thank you for the quick response.
