### ISSUE TITLE
Stat panel with prometheus should show name as label

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#27019]
**What would you like to be added**:
When using Prometheus and aggregating over a label:
`count by (svr) (scylla_scylladb_current_version)` 
The name appears as the `{svr="4.1.1."}` There should be a way to set the name as `4.1.1`

**Why is this needed**:
Making the new feature - show Name only useful for Prometheus

**Comment by torkelo** [comment]
use `{{srv}}` in the legend format in the prometheus query editor
