### ISSUE TITLE
Postgres - Materialized Views are not handled like tables

### ISSUE THREAD

**Issue by farthinder** [grafana/grafana#27017]
**What happened**:
Postgres materialized views don't show up as selectable tables and neither does their columns when setting up a panel. 
Inputting the names of the tables and columns manually does work  

**What you expected to happen**:
I expected that when setting up  a new panel, when in the query definition tab that the "From" field should be populated with "new_mview" and the the columns "timestamp" and "valueColoumn" should be populated as possible columns to select.

**How to reproduce it (as minimally and precisely as possible)**:
This is my sample definition for a materialized view that I expected Grafana to find:
```
CREATE MATERIALIZED VIEW public.new_mview
TABLESPACE pg_default
AS 
SELECT now() AS timestamp, 100 as valueColoumn
WITH DATA;
```

**Anything else we need to know?**:

I looked at the discovering query that Grafana sends to the DB-server:

```
SELECT quote_ident(table_name) FROM information_schema.tables WHERE
table_schema IN (
  SELECT
    CASE WHEN trim(s[i]) = '"$user"' THEN user ELSE trim(s[i]) END
  FROM
    generate_series(
      array_lower(string_to_array(current_setting('search_path'),','),1),
      array_upper(string_to_array(current_setting('search_path'),','),1)
    ) as i,
    string_to_array(current_setting('search_path'),',') s
) ORDER BY table_name
```
This query seems to be built by: [meta_query.ts](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/postgres/meta_query.ts )

This returns normal tables and "normal views" but not materialized views. To query postgres for the materialized views you can use the query:
`select * from pg_matviews;`

I raised a forum post about the problem here: https://community.grafana.com/t/postgres-materialized-view-autocomplete/35081

**Environment**:
- Grafana version: v7.1.3
- Data source type & version: Postgres 10.12
- OS Grafana is installed on: Ubuntu 20 LTS
- User OS & Browser: OSX, Firefox
- Grafana plugins: Default only
- Others:

**Comment by farthinder** [comment]
While looking in to this I noticed that this discovery query and it´s findings doesn't seem to get logged to the log file even when:
```
[log]
level = debug
[log.file]
level = debug
[database]
log_queries = true
```

Not sure if that can be considered a bug, but I expected that to be part of the output.

**Comment by mdvictor** [comment]
I will close this as it has been fixed by [this](https://github.com/grafana/grafana/pull/62867)

**Comment by jasonvasquez** [comment]
Hello - while testing in grafana 9.5.13, I can see that regular views are indeed visible, but postgres _materialized_ views are not visible. Is that expected?
