### ISSUE TITLE
Table: add the possibility to filter table data

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#27025]
Table panel does not support data filtering currently. We would like to add possibility to filter data in a Excel-like way:

![image](https://user-images.githubusercontent.com/2376619/90367303-fe8b8b00-e068-11ea-9b51-ceaeb2e5cda0.png)

### Some more inspiration on filtering approaches in data grid libraries

react-data-grid:
![image](https://user-images.githubusercontent.com/2376619/90367464-2f6bc000-e069-11ea-89de-2b4a7971e952.png)

ag-grid:
![image](https://user-images.githubusercontent.com/2376619/90367599-4a3e3480-e069-11ea-938c-3bd7f08e88f3.png)

DevExtreme data-grid:
![image](https://user-images.githubusercontent.com/2376619/90367713-67730300-e069-11ea-832c-d4710313ca35.png)

ant-d table filtering:
![image](https://user-images.githubusercontent.com/2376619/90367862-870a2b80-e069-11ea-913c-14cb9ba2fdd5.png)

[Doc with design iterations](https://docs.google.com/document/d/1rmsrQN7-Rslu8n3AlyAF9D5ZvRKYhaKQFs8S55QOfVM/edit?usp=sharing)

**Comment by dprokop** [comment]
@torkelo any input on some specifics regarding this RA?

**Comment by torkelo** [comment]
No specifics, would keep it simple at first. Just a filter icon and a drop down to select values (with multi select ability)

**Comment by dprokop** [comment]
Torkelo:
1. Possibly a field config option to enable/disable filtering in the table
2. Should we have search/regex filter or just multi select

**Comment by hugohaggmark** [comment]
Just to be super clear, do we want to enable/disable filtering per field or do we want to enable/disable filtering per table?
@dprokop @torkelo

**Comment by torkelo** [comment]
yes, the option needs to be a field config option so you can enable only for a specific column
