### ISSUE TITLE
jQuery dialog in HTML panel does not work

### ISSUE THREAD

**Issue by rmunoz10** [grafana/grafana#27020]
**What happened**:
Dialog seems not responsive. Oddly, if I edit the html text, say adding a space after </script>, the dialog activates and works as expected.

**What you expected to happen**:
Dialog should be hidden on initial refresh. Then it should open when button is clicked.

**How to reproduce it (as minimally and precisely as possible)**:
I have included the panel json below

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.6 and 7.1.2
- Data source type & version: n/a
- OS Grafana is installed on: centos 7
- User OS & Browser: Firefox

- This shows dialog not working
![Selection_268](https://user-images.githubusercontent.com/26364789/90334874-ab4d0600-df9e-11ea-95cd-e1934247d2e9.png)

- This shows dialog working
![Selection_269](https://user-images.githubusercontent.com/26364789/90335007-ad639480-df9f-11ea-9422-1c2255d535df.png)

Panel Json is:
{
  "datasource": null,
  "content": "<link rel=\"stylesheet\" href=\"//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css\">\n<script src=\"https://code.jquery.com/ui/1.12.1/jquery-ui.js\"></script>\n\n<script>\n//   $(function() {\n      $( \"#dialog-1\" ).dialog({\n         autoOpen: false,  \n      });\n      $( \"#opener\" ).click(function() {\n         $( \"#dialog-1\" ).dialog( \"open\" );\n      });\n//   });\n</script>\n\n\n<div>  \n<button id = \"opener\">Open Dialog</button>\n</div>      \n\n\n<div id = \"dialog-1\" title = \"Dialog Title goes here...\">This my first jQuery UI Dialog!</div>\n\n         ",
  "gridPos": {
    "h": 6,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 150,
  "mode": "html",
  "options": {},
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "type": "text"
}

**Comment by torkelo** [comment]
We do not provide support for custom js code in text panel, will have to figure this out or ask for help on community site. 

 https://community.grafana.com
