### ISSUE TITLE
Templating: Remove repeated panels and rows from save model 

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#27028]
**What happened**:
Large Grafana dashboards are often based on 
- dynamic template variables which are loaded on Dashboard load or every time time range change, even datasource is dynamic
- utilize template variables to populate the dashboards. 
- dashboards panels are grouped under collapsed rows, which result that all panels are typically hidden/collapsed.
- Under rows some panels are repeated panel or repeated rows (each panel has one to up to template variable number of instances)

Outcome is that dashboard is fully dynamic, configuration changed when time range is changed or any row is expanded/collapsed.

Currently when dashboard is saved the template variable values are also stored. This means that configuration file contain all template variable values when multi is enabled and custom all value is for example ".*", otherwise it contain selected values or default value (first or all).

In addition each panel configuration contain resolved template variable values instead of just template agnostic configuration like when template variable values would be empty.

When repeating panels are used then first panel contain repeated panel config and for each repeated panel new panel config refer to parent is created. Parent contains the first template variable and each repeated panel contains different resolved variable name. This approach is probably desired when panels are always visible.

However when rows are used the behavior change. When repeating panels under row (not repeating row) are used and row is collapsed the panel configuration is not updated as template variables changes. This is correct behavior because it is not possible to update all hidden panels all the time, dashboard would become unresponsive. 
When row is expanded the config is correctly dynamically updated regardless of the current config as it is always wrong.
In dashboard save however the config is mixed because some rows contain config it had last time it was expanded, some rows are up to date but collapsed and maybe some rows are expanded. 
If user expanded row at time range A when it contained 100 repeated panel the all 100 panels with variable are saved, the saved values are only valid for specific time range A, when time range change to B the panel configuration is out of date.

When dashboard is saved there are two options
- Save current time range
- Save current variable values as dashboard default
I have not seen "any" behavior change if "Save current variable values as dashboard default" is checked or unchecked. Seems that dashboard always saves all template variables and panels using template variables even when option in "unchecked".

Currently dashboard size becomes unnecessary large when collapsed rows contain large number of dynamic repeating panel are saved, and normally panel config is outdated anyway when everything is dynamic.

**What you expected to happen**:
There should be option to save dashboard without template variables vales (large dashboards with dynamic template variables), not sure if small static dashboard without rows and dynamic repeating panels need saving option not to update template variables.
This would reduce the size of the dashboard and make loading faster. There is no value saving outdated wrong config.

**How to reproduce it (as minimally and precisely as possible)**:
Just create dashboard with template variables, rows and repeating panes which use template variable for repeat.

**Environment**:
- Grafana version: 6.4.3 and 7.1.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux, Windows 10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Example row config with repeating panels (two repeating panels due template variable $serviceall has values service-v1 and service-2)**

```
  "panels": [
    {
      "collapsed": true,
      "datasource": null,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 73307,
      "panels": [
        {
          "datasource": "$promsource",
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 0,
            "y": 1
          },
          "id": 73305,
          "repeat": "serviceall",
          "scopedVars": {
            "serviceall": {
              "selected": true,
              "text": "service-v1",
              "value": "service-v1"
            }
          },
          "targets": [
            {
              "expr": "sum(rate(http_server_requests_seconds_count{dnsname=~\"$serviceall\"}[$range])) by (status)",
              "interval": "",
              "legendFormat": "{{status}}",
              "refId": "A"
            }
          ],
          "title": "rate $serviceall",
          "type": "graph",
          "tooltip": {
            "shared": true,
            "sort": 0,
            "value_type": "individual"
          },
          "type": "graph",
        },				
        {
          "datasource": "$promsource",
          "gridPos": {
            "h": 8,
            "w": 12,
            "x": 12,
            "y": 1
          },
          "id": 73310,
          "repeat": null,
          "repeatIteration": 1597600779279,
          "repeatPanelId": 73305,
          "scopedVars": {
            "serviceall": {
              "selected": true,
              "text": "service-v2",
              "value": "service-v2"
            }
          },
          "targets": [
            {
              "expr": "sum(rate(http_server_requests_seconds_count{dnsname=~\"$serviceall\"}[$range])) by (status)",
              "interval": "",
              "legendFormat": "{{status}}",
              "refId": "A"
            }
          ],
          "title": "rate $serviceall",
          "type": "graph",
        }
      ],
      "title": "ROW containing repeat panel",
      "type": "row"
    },
]
```

**Comment by torkelo** [comment]
For variables that have refresh on "Dashboard Load", or time range change we can clean and remove options before saving

**Comment by torkelo** [comment]
If anyone wants to help with this: Here is where the save model is built https://github.com/grafana/grafana/blob/cb82cf110fa05bbf92087375cdd21937564c05e7/public/app/features/dashboard/state/DashboardModel.ts#L236

**Comment by torkelo** [comment]
actually this is already implemented: 
https://github.com/grafana/grafana/blob/master/public/app/features/variables/query/adapter.ts#L38 

If the refresh is on dashoard load or time the values are never saved in the dashboard model

**Comment by torkelo** [comment]
Actually to solve this just call cleanUpRepeats: 
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/DashboardModel.ts

**Comment by torkelo** [comment]
Or maybe not use that. Simplest is filter out rows and panels with repeat and a sourceId https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/DashboardModel.ts#L205

**Comment by jtorkkel** [comment]
Any estimate when this gets fixed. 2min freeze make Grafana 7.x usage painful.
