### ISSUE TITLE
Polystat Plugin crashing repeatedly for azure monitor data source 

### ISSUE THREAD

**Issue by rakeshmohapatra** [grafana/grafana#27037]
1. While adding multiple data sources like azure monitor and log analytics polystat is crashing.
2. If there is no value received from output of a log analytics query then ploystat is failing with error which lead to data loss for unsaved activities.

Version used:
Grafana: v7.1.3
AzureMonitor Plug-in:  0.3.0
Polystat Plug-in : 1.2.0

Note: I have another instance with Grafana version v7.0.5 and it is working perfectly.

**Comment by kylebrandt** [comment]
closing in favor of https://github.com/grafana/grafana-polystat-panel/issues/143
