### ISSUE TITLE
Cannot parse json file name with two '.' correctly.

### ISSUE THREAD

**Issue by HermesCheng** [grafana/grafana#2703]
When I use a json file as 'default_route' value in config.js and this json file name [1] has two ".", it cannot work correctly.
I will get error like [2] in browser console.

[1] json file name: test-v1.0.json
[2] GET XHR http://10.0.0.73:8080/app/dashboards/test-v1/0.json

**Comment by torkelo** [comment]
seems to be a bug in 1.9.x , working in 2.x though :)
