### ISSUE TITLE
Floating stacked values in graph

### ISSUE THREAD

**Issue by McAnix** [grafana/grafana#27033]
**What happened**:
I get floating stacked values when a previous item is missing for that period

![image](https://user-images.githubusercontent.com/5427047/90403054-a83a3e80-e0a0-11ea-8646-c5fb07722a5c.png)

**What you expected to happen**:
The graph entries for 08/08, 08/10, and 08/16 to start at zero. 

**How to reproduce it (as minimally and precisely as possible)**:
Select a dataset with values missing at midrange intervals, then use stacked bars to present data. 

**Anything else we need to know?**:
I've tried null_as_zero, null, and connected on stack values. 
I've tried (un)hiding null or zero values. 
This emulates a line/area graph in "continuous" representation, which is inaccurate. 

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: MariaDB 10.4
- OS Grafana is installed on: Ubuntu 18.04.5 LTS 
- User OS & Browser: Mac OS 10.15.6 (19G73) on Chrome 84.0.4147.125
- Grafana plugins: 
- Others:

**Comment by FireEmerald** [comment]
This bug is really annoying as it breaks the whole stack functionality:
![sample](https://user-images.githubusercontent.com/1107939/96691834-aaad6300-1385-11eb-8c08-1e5c46d967d8.gif)

**Comment by FireEmerald** [comment]
The issue is even worse. If you turn on stacked bars, you may get bars shown where no data exists at all:
![sample](https://user-images.githubusercontent.com/1107939/96847978-1e1da600-1454-11eb-96ac-c787bb309cc0.gif)
Note that on the 26.09. 14:00 there are **0** errors in the data source.
