### ISSUE TITLE
v7.1.3 - Align Y-Axis setting does not align two Y-Axes

### ISSUE THREAD

**Issue by David00** [grafana/grafana#27039]
**What happened**: Enabling the `Align Y-Axes` option does not align the Y-axes in my "Graph" that has display: Bars enabled.

**What you expected to happen**: The two Y-axes should have the same scale, with the same minimum and maximum values.... in other words, they should be aligned. 40 on y-axis number 1 should be at the same height as 40 on y-axis number 2.

**How to reproduce it (as minimally and precisely as possible)**: Plot two different data sets where one data set has higher values then the other. Assign each data set to a separate y-axis, then try to align the axes.

**Anything else we need to know?**: See GIF below:

![y-axes-bug-sumbission](https://user-images.githubusercontent.com/17997328/90455046-c9535d00-e0a9-11ea-996f-ba2e1afdcb01.gif)

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: InfluxDB v1.7.9
- OS Grafana is installed on: Raspbian 10
- User OS & Browser: Windows 10 - Firefox 79
- Grafana plugins: InfluxDB
- Others:

**Comment by torkelo** [comment]
Looks correct, both y-axis share the same zero line

https://github.com/grafana/grafana/pull/10994
https://github.com/grafana/grafana/issues/2740
