### ISSUE TITLE
How to run grafana with git repo?

### ISSUE THREAD

**Issue by hakuna0829** [grafana/grafana#27036]
Hello, Everyone.

I am new with Grafana.
So, I want to know something related to its usage.
I'd like to clone from grafana git repo and run it in localhost:3000.
But it doesn't work as I want.

Here are something I've tried.
- git clone https://github.com/grafana/grafana.git
- cd grafana && yarn
- yarn start
![Uploading image.png…]()

Then it runs without any errors, but there is not specified url to visit app like above image.
I can see default url is localhost:3000 in conf/default.ini, but it doesn't work in my browser.

My dev environement 
- Windows 10
- VS code

If you know the solution or link for it, let me know soon.
Thanks

**Why is this needed**:

**Comment by ryantxu** [comment]
Check:
https://grafana.com/docs/grafana/latest/developers/contribute/

Likely what you are looking for:
https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md
