### ISSUE TITLE
InfluxDB cloud - Cannot get all Buckets

### ISSUE THREAD

**Issue by nghhung** [grafana/grafana#27030]
Hi, 
I have connected Grafana with InfluxDB cloud and I saw it shows 2 buckets

https://share.getcloudapp.com/eDuBwk4z

but I have 4 buckets : 
https://share.getcloudapp.com/jkuZYr5q

It only shows: System Bucket
https://share.getcloudapp.com/YEuoQN71

How can I connect to all Buckets? 
Thanks

**Comment by peterholmberg** [comment]
Hello, questions like these are better posted on community.grafana.com
