### ISSUE TITLE
Listing all organization with pagination. Pagination doesn't work.

### ISSUE THREAD

**Issue by b-tarczynski** [grafana/grafana#27044]
**What happened**: Using Grafana API for searching all organization with pagination, turns out that pagination not working.
Using this request: curl http://admin:admin@grafana:3000/api/orgs?page=1&perpage=2.
It returned all of my organizations:
[
  {
    "id": 1,
    "name": "Main Org."
  },
  {
    "id": 8,
    "name": "abc"
  },
  {
    "id": 12,
    "name": "cbaa"
  },
  {
    "id": 2,
    "name": "service1"
  },
  {
    "id": 13,
    "name": "service10"
  },
  {
    "id": 16,
    "name": "service100"
  },
  {
    "id": 17,
    "name": "service102"
  },
  {
    "id": 14,
    "name": "service13"
  }
]

**What you expected to happen**: It should return array with 2 organization:
[
  {
    "id": 1,
    "name": "Main Org."
  },
  {
    "id": 8,
    "name": "abc"
  }
]

**How to reproduce it (as minimally and precisely as possible)**: Add some organizations and try to list them with pagination.
(curl http://admin:admin@grafana:3000/api/orgs?page=1&perpage=2)

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v7.1.0 (8101355285)
- Data source type & version: sqlite3
- OS Grafana is installed on: Ubuntu 18.04.5 LTS (Bionic Beaver)
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Closing as dup of #26171.

**Comment by b-tarczynski** [comment]
Thanks for the response. I searched for similar issue, but only in open issues. Sorry for duplicate.
