### ISSUE TITLE
Feature request: Add scrollbar to legend when in table mode if its higher than the graph

### ISSUE THREAD

**Issue by szop85** [grafana/grafana#2704]
Hello,

I'd like to know if there is an option to adjust the panel height automatically with growing number ob nodes? Currently it seem's like my graph isn't adjusting after a specific height with the number of nodes. Please see my screenshot.

![screen shot 2015-09-09 at 09 37 14](https://cloud.githubusercontent.com/assets/2103595/9755972/b817dc08-56d6-11e5-9a21-456e4ffa946d.png)

An much nicer alternative would be to have a scrollbar on the right legend side, so it would be the same height like the graph.

Cheers,
David

**Comment by pdf** [comment]
Scrollbars might work well, I'd be happy with even just a 'hide when > x items' option like graphite.

**Comment by torkelo** [comment]
this was fixed long ago
