### ISSUE TITLE
Cannot read property 'length' of undefined

### ISSUE THREAD

**Issue by dwsorge** [grafana/grafana#27049]
Hello,

I am using the heatmap plugin and I am getting "Cannot read property 'length' of undefined".
I am also using MetaQuery.

The query inspector is returning data which is coming from InfluxDB.

When I view in Chrome the error is: Cannot read property 'length' of undefined
When I view in IE the error is: Cannot read property 'length' of undefined or null reference

I am using Grafana v7.1.3
MetaQuery 0.0.3

This is working with Grafana v6.2.5 and MetaQuery 0.0.1 but this issue is blocking our upgrade.

![image](https://user-images.githubusercontent.com/69860150/90531886-9611dc00-e144-11ea-9b5b-132ebd31e3fe.png)

**Comment by torkelo** [comment]
You will have to report this to https://github.com/GoshPosh/grafana-meta-queries
