### ISSUE TITLE
Grafana date range not showing in Citrix and Production properly

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#27040]
**What happened**:Grafana Date range is not showing properly in citirx environment and production environment chrome.

**What you expected to happen**:date should be there to select

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:Grafana
- Grafana version:7.1.0 and old version
- Data source type & version:sql server 2017
- OS Grafana is installed on:desktop
- User OS & Browser:windows and chrome
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
Hello, please add steps to reproduce this issue please.

**Comment by karamjeetkaurpreeti** [comment]
Publish with Json file on the production.

**Comment by peterholmberg** [comment]
That is not enough sadly, need more information on how to reproduce.

**Comment by karamjeetkaurpreeti** [comment]
I simple publish on my web page.

**Comment by karamjeetkaurpreeti** [comment]
We are showing with the help of Iframe on th brower but date range selection shows in starting but after page laod it is not showing.
