### ISSUE TITLE
Create custom Grafana playground dashboards

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#27042]
We would like to be able to create a custom 'playground' dashboard for our users to check out. 

This would be identical to the playground examples used throughout the Grafana documentation and e.g. the official [Grafana playground](https://play.grafana.org/d/000000012/grafana-play-home).

This seems like it would be really useful as part of promoting Grafana to more users - but I've not been able to find any guides on setting this up. Specifically, the features would be:

1) Allow users to open the playground and view the dashboard without logging in
2) Show queries and allow users to modify panels - while ensuring that changes are cleared upon refresh
3) Not exposing the data source or details related to this

Thanks,
Martin

**Comment by torkelo** [comment]
1) Enable anonymous access (easy to do in your grafana server ini file) 
2) set ini option viewers_can_edit to true to allow anonymous & Viewer role users to make transient edits  (ie cannot save) https://grafana.com/docs/grafana/latest/administration/configuration/#viewers_can_edit
3) This is impossible, the data source needs to be accessible to query and show data. You do not need to expose data source credentials but query access is something Grafana needs.

**Comment by MatinF** [comment]
@torkelo Thank you. I am using a Grafana Cloud Starter account - is there any way to modify things like the anonymous access and the option `viewers_can_edit` for this type of instance? I've not been able to see a place where I can modify the raw `INI` file behind my cloud instance.

**Comment by torkelo** [comment]
you can email support and ask, viewers_can_edit is usually only for public instances which is why we do not provide a UI option for it in Grafana Cloud
