### ISSUE TITLE
No data being displayed past 1 day

### ISSUE THREAD

**Issue by Jazz2k** [grafana/grafana#2705]
I'm running Grafana as a VM using collectd and no influxdb, just flat files. I don't get any data past 1 day. We have had this setup on a previous server exactly the same and this was working fine.

I'm using the default retention policies so not sure what is the issue. Any ideas?

Thanks, Lloyd

**Comment by torkelo** [comment]
not sure, could be many things, but its not likely a grafana issue as no one has had any problem like this (that ended up being caused by grafana, always a config issue with the time series store). 

To be sure inspect the response from InfluxDB using chrome dev tools.
