### ISSUE TITLE
Add External Plugin Project to Grafana Plugins

### ISSUE THREAD

**Issue by karthikjagadeeswaran** [grafana/grafana#27062]
Hi Everyone,
        I want to add my plugins as a project to grafana plugins. Because in future grafana released new version it won't affect my plugins when i get pull the code. Is there any possibility to do ?

**Comment by peterholmberg** [comment]
Hello, I'm not sure I understand what you want to accomplish? Do you want to submit your plugin in the plugin repository? https://github.com/grafana/grafana-plugin-repository

**Comment by karthikjagadeeswaran** [comment]
No, I don't want to push my plugins. I found a way to solve the problem
build the plugin and place the deployment code into the data/plugins folder
