### ISSUE TITLE
Raw query shows on hovering Stat panel

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#27061]
**What happened**:

When you hover the Stat panel you can see the raw query

**What you expected to happen**:

To not see the raw query

**How to reproduce it (as minimally and precisely as possible)**:

1. Create stat panel
2. Create query: `sumSeries(keepLastValue(apps.$app.*.counters.requests.count, 15))` (I used this page https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1)
3. Hover on it
4. Observe raw query

![image](https://user-images.githubusercontent.com/8693064/90597074-67a60680-e201-11ea-97fe-026b71767f40.png)

**Environment**:
- Grafana version: Grafana v7.1.3 (5723d951af)

**Comment by torkelo** [comment]
this is the series name, use alias in your query to change the series name
