### ISSUE TITLE
Fill below to

### ISSUE THREAD

**Issue by Wanty5883** [grafana/grafana#27064]
![gif](https://user-images.githubusercontent.com/36901782/90611787-7a233e80-e207-11ea-9eac-799acbc3f90e.gif)

**What happened**:
Series overrides "Fill below to" does not work anymore
**What you expected to happen**:
Using "Fill below to" in Series overrides to be usable.
**How to reproduce it (as minimally and precisely as possible)**:
Add "Fill below to" as a Series overrides.
**Anything else we need to know?**:
I did work as intended before though I did not notice since when I have this issue. The graph where I did set "Fill below to" before does work properly, if I try to edit or delete / add the same setting it does produce the same bug
**Environment**:
- Grafana version: 7.0.4
- Data source type & version: InfluxDB v1.8.1
- OS Grafana is installed on: Linux - Unraid
- User OS & Browser: Windows 10, Chrome & Firefox
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
There is no super easy way to fix this without spending a lot of time rewriting and changing angular code. 

The temp work around is to collapse and expand the Series overrides section in the sidemenu, after expanding it again the fill bellow to series names will be there

**Comment by Wanty5883** [comment]
That worked for me, thanks for the tip !
