### ISSUE TITLE
Refresh value only honoured when using 'now' for TO: value, but manual editing of URL (&refresh=5m) works

### ISSUE THREAD

**Issue by spmatich** [grafana/grafana#27060]
**What happened**:
setting Time window on a dashboard.
FROM: "2020-08-19 09:55:43" and TO: 2020-08-19 19:55:43
Select 5m from Refreshing Every:
Click apply
Browser loads FROM and TO: but refresh is not applied. When I manually edit the address URL and add the refresh value for 5m to the browser URL (ie &refresh=5m), the refresh seems to be honoured along with the FROM and TO.
But when I select now as the TO: value, then refresh is honoured in the way I expect

**What you expected to happen**:
Expect refresh value to be honoured when using values of TO: other than now

**How to reproduce it (as minimally and precisely as possible)**:
See instructions above

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.1.6
- Data source type & version: postgresql (timescaleDB) PostgreSQL 9.6.13 on x86_64-pc-linux-musl, compiled by gcc (Alpine 8.3.0) 8.3.0, 64-bit
- OS Grafana is installed on: Linux (k8s) 4.18.0-25-generic #26-Ubuntu SMP Mon Jun 24 09:32:08 UTC 2019 x86_64 GNU/Linux
- User OS & Browser: WIn2012R2 & Chrome Version 84.0.4147.125 (Official Build) (64-bit)
- Grafana plugins: 
- Others:

**Comment by peterholmberg** [comment]
I'm not able to reproduce this on 7.1.3, could you upgrade to the latest version and see if the issue persists?

**Comment by spmatich** [comment]
> I'm not able to reproduce this on 7.1.3, could you upgrade to the latest version and see if the issue persists?
Ok, I have tried a newer grafana version (7.0.0) and I can see the auto-refresh is now in a separate widget.

Select autorefresh 5m from the dropdown then select FROM timestamp and TO timestamp and click apply.  The autorefresh is cleared. If the autorefresh is selected after the time window is applied then it persists. So selecting FROM and TO timestamps and clicking apply will clear the autorefresh in version 7 grafana. This behaviour is by design?

**Comment by spmatich** [comment]
The reason I am raising this comes from a use case where I have where I set a TO window in the future and enabled autorefresh. If I just have 'now' as the TO value it does not affect autorefresh when I apply the time window. But say I have 'now' as the TO value, autorefresh enabled, and Im running my browser in a gui session that continues in the background. From time to time I log back into my gui session and check the grafana dashboard, so far so good. But if FROM is a timestamp and TO is 'now' autorefresh keeps plugging away in the background, pulling ever more data over time with each refresh, so the browser memory usage grows indefinitely. If the time window behaviour is honoured with TO==now but not with TO==<some timestamp> that could potentially confuse a few low-lifes like myself :). Admittedly the behaviour in v7 is better than it was with v6. With v7 you dont have to manually edit the url to apply a refresh interval with a fixed TO value. But, if you do have a fixed TO value, other than 'now', the autorefresh value is cleared when applying the time window. Maybe this is fixed in v7.1.3, which I dont have access to at the moment.

**Comment by peterholmberg** [comment]
Could you upload a gif of you reproducing this? Tried setting autorefresh then time range but it still honors the autorefresh when hitting apply

**Comment by spmatich** [comment]
So I have the following sequence on, Grafana 7.0.0

1. grafana-sequence1.gif
Start with fixed timestamp for FROM and TO and autorefresh value of 5m
2. grafana-sequence2.gif
Then set fixed timestamp for FROM and TO set to now, dont touch autorefresh, apply time range. 
3. grafana-sequence3.gif
Note autorefresh value is not cleared after step 2. Then set fixed timestamp for FROM and TO, dont touch autorefresh, apply time range
4. grafana-sequence4.gif
Note autorefresh value is cleared, after step 3, and have to manually re-apply it

1 ![grafana-sequence1](https://user-images.githubusercontent.com/55971503/90835239-64d91c00-e38f-11ea-9394-e4e9dbb0f04b.png)
2 ![grafana-sequence2](https://user-images.githubusercontent.com/55971503/90835237-64408580-e38f-11ea-9f95-4d4986876afb.png)
3 ![grafana-sequence3](https://user-images.githubusercontent.com/55971503/90835235-63a7ef00-e38f-11ea-83b9-fe3f2cf22fc5.png)
4 ![grafana-sequence4](https://user-images.githubusercontent.com/55971503/90835233-630f5880-e38f-11ea-9a98-8f1fadccafc9.png)

**Comment by torkelo** [comment]
This seems to work now
