### ISSUE TITLE
Elasticsearch test connection not working

### ISSUE THREAD

**Issue by yehosef** [grafana/grafana#2707]
using the Pre 2.5 release.  Put in elasticsearch query properties and clicked "test connection" and there is an orange popup that says "Data source does not support test connection feature."

I assume you can just test going to the url.  You'll get the basic server info, which shows that it's elasticsearch and you can get through.

**Comment by torkelo** [comment]
strange, what commit / version are you running (you see this on login view)

It should be working,  are you sure you restarted grafana-server after updating to latest grafana?
![image](https://cloud.githubusercontent.com/assets/10999/9759893/c09bf322-56f0-11e5-9474-c98e9a3e7f12.png)

**Comment by yehosef** [comment]
You're right.. I had the wrong version.. Thanks!

**Comment by cjy0125** [comment]
I encounter the similar problem with 
Version: 2.5.0, Commit: v2.5.0+1-g287d8ca, Build date: 2015-10-28 08:43:28 +0000 UTC
![image](https://cloud.githubusercontent.com/assets/2188025/11360212/5ef8e77a-92bd-11e5-99bf-a7b99cd8e0a9.png)

I had check the elasticsearch works fine and can be connect from the host which installed Kibana and Grafana.
Any idea for troubleshooting this issue?

Thanks.

**Comment by torkelo** [comment]
since you use access method `direct` (meaning the data source is accessed directly from the browser), you need to enable cors in elasticsearch config

**Comment by cjy0125** [comment]
Thanks, it works now.
