### ISSUE TITLE
Consolidate template interpolation

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#27079]
**What would you like to be added**:

There's currently three (more?) ways to interpolate a template variable for plugins.

1. Panel plugins: `replaceVariables()`
1. Data source plugins: `getTemplateSrv().replace()`
1. Data source plugins with backend: `applyTemplateVariables()`

We should consolidate this so that the API is the same across all plugin types, i.e. same name, same signature.

**Why is this needed**:

Providing multiple APIs for the same thing is confusing for plugin developers. We should have a consistent API to do this across all plugin types.

**Comment by torkelo** [comment]
the reason panels have a different way is that replaceVariables always includes scoped variables, something many data sources always forget to pass.

**Comment by marcusolsson** [comment]
Are you saying that scoped variables are required for _both_ panels and data sources, but that data sources often forget to pass them? Or are scoped variables for data sources sometimes optional?

If it's the former, then a common interface would make it required for both?
