### ISSUE TITLE
Data link docs are incomplete, missing variables

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#27094]
https://grafana.com/docs/grafana/latest/linking/data-links/ has no list of variables that can be used only in data links (and no link to where to find them) 

The templating section there is a page for URL variables, but there is no such variable type (in the same sense as the others). 

The variables listed are only available in data links urls you cannot define a URL variable like you can with the other template variable types in that docs section. 

Think the URL Variables page: https://grafana.com/docs/grafana/latest/variables/variable-types/url-variables/  could be merged and deleted and content copied to the data links page as that is the only place where these can be used currently.

**Comment by dprokop** [comment]
friendly ping @oddlittlebird :)

**Comment by oddlittlebird** [comment]
The URL variables topic is linked to the Data links topic in the first paragraph. The Data links topic links to the URL variables topic in step 5 of the Add a data link task.

I gave a lot of thought to where the URL variables topic should go when I reorganized the variable section about a month ago.

Here's the thing with URL variables: you don't need to make a data link to use them. Case in point, right here I added one of the examples to a Play dashboard: https://play.grafana.org/d/000000012/grafana-play-home?viewPanel=2&orgId=1?from=now-6h&to=now

No data link required. Thus, these do not fit in just the "data link" category, so it does not make sense to merge the two topics.

As a user, if I want to use a variable in a data link, does it make more sense to look in Variables or in Data links? 
As a user, if I want to make a link to a URL with specific parameters, where will I look for that information?

It's a tough call. To try and thread that needle, I put this topic in with similar content (other variables) and cross-linked the URL variables topic with the Data links topic.

There are undoubtedly opportunities to enhance this section, but the solution proposed in this issue does not make sense.

**Comment by torkelo** [comment]
The data variables on that page can only be used in data links

The only thing that make sense that page is how to set template variables and time via url , but that should not be under the section of variable types I feel

**Comment by torkelo** [comment]
I think it could make more sense maybe if page was renamed data variables but still super confusing that these are not on the docs page for the feature where they are only used from (data links).

The whole point of a data link is to refer to data using a variable expression , so 99% of the reason to want to view data links docs is to find out to refer to data in when building a link 

But I agree is a it tricky. But Url variables is a confusing place I feel for these data variables to live

**Comment by oddlittlebird** [comment]
The content refers to variables that can be used in URLs. While data links are the only feature that uses them (currently), the variables apply to more than just data links. 

We come back to "where will the user look for variables they will use in a URL." I can argue both ways, but I settled on grouping these variables with the rest of the variables and providing a cross-reference link. 

Going the other direction would mean putting reference content in a mostly task topic (please, no) or putting unlike content in with the rest of the linking content (again, please no).

**Comment by oddlittlebird** [comment]
I'm going to take a stab at improving this and moving a few things around. Stay tuned.
