### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by bwilder** [grafana/grafana#2709]
Need a way to configure PNG snapshot expiry/cleanup system-wide. As it stands, there's no easy way to even tell which graphs have been configured to store snapshots.

**Comment by torkelo** [comment]
could you describe more what you are talking about? 

> even tell which graphs have been configured to store snapshots.

what?

**Comment by bwilder** [comment]
Fast response, thanks! 

On my linux host, I found /var/lib/grafana/png growing out of control. I'm assuming is where all snapshots are stored, but I don't seem to be able to find specifics in documentation. I've been searching for more information all morning and came up with no out-of-the-box way to limit the size of the directory or expire the contents after x time period. You seem to allude to this situation in the post - https://github.com/grafana/grafana/issues/2172. 

ATM, it seems that the best way to manage the directory is to create a cron job to wipe the contents every x time period.

Am I missing something?

**Comment by bwilder** [comment]
WRT "...even tell which graphs have been configured to store snapshots." 

Per http://docs.grafana.org/reference/sharing/, sharing is configured per dashboard (not graph). Our organization has 10's of dashboards, but there's no way to know which dashboard is configured to save these snapshots, which makes tracking down the problem extremely tedious.

**Comment by torkelo** [comment]
the pngs are from when you share a png, you are absolutely right there needs to be some integrated cleanup here. 

Will fix asap, there is already an issue for it though: https://github.com/grafana/grafana/issues/2172

**Comment by torkelo** [comment]
but a cron job would do the job for now

**Comment by bwilder** [comment]
Thanks!
