### ISSUE TITLE
Cannot reference value from other column in Data link

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#27091]
https://github.com/grafana/grafana/issues/25187

I have created Override in Table panel for Data Links. Created a new Data Link and as value set `${__cell_0:raw}` to reference url in first column. However, the value is not parsed. In old table panel this was possible.

**Environment**:
- Grafana version: 451af74728cbd121663ae0e61b08e3212388b0c1

**Comment by torkelo** [comment]
Use this syntax  `${__data.fields[2]} ` docs are bad here (and in the wrong place), https://github.com/grafana/grafana/issues/27094

**Comment by simPod** [comment]
@torkelo thanks! But what if I hide column that contains the link (index 0) using Transformations and want to reference it's value? Seems impossible now.
