### ISSUE TITLE
Max and Min overrides have no effect

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#27101]
I set Min and Max overrides in Table panel

![image](https://user-images.githubusercontent.com/327717/90791597-b17a1400-e309-11ea-8fa0-ba68e46d0c56.png)

It seems to have no effect. What should it do?

**Environment**:
- Grafana version: 999009bd57deaabea37a1c04024b876c1b02edfe

**Comment by torkelo** [comment]
Unable to replicate, has the expected effect for me: https://play.grafana.org/d/U_bZIMRMk/table-panel-showcase?orgId=1&editPanel=2

**Comment by simPod** [comment]
What is the effect? I don't see any

![image](https://user-images.githubusercontent.com/327717/90822869-5cec8e00-e335-11ea-9161-dcc4cec37909.png)

**Comment by torkelo** [comment]
They impact the bar gauge (if I set the default min/max, or an override for that column that sets min & max)

**Comment by torkelo** [comment]
For a normal column value there is no impact, have to use the cell display mode that actually use the min / max. The default cell mode does not

**Comment by torkelo** [comment]
to be clear min / max are just the min & max value range for the field. Used in like axis (graph in stat panel for example), to determine gauge position in gauges

**Comment by simPod** [comment]
Interesting, thanks for explanation. Though it is not very clear from docs nor override desc what it really does.
