### ISSUE TITLE
Data Link disappears after upgrade

### ISSUE THREAD

**Issue by loganmc10** [grafana/grafana#27107]
**What happened**:

The last 2 times I've upgraded Grafana (using Docker), a data link I have in one of my panel just disappears, and I have to recreate. It persists over reboots, just not over upgrades

**What you expected to happen**:

I would expect the data link to persist between upgrades

**How to reproduce it (as minimally and precisely as possible)**:

Create a data link in a time series panel. It went away after upgrading from 7.1.3 to 7.1.4

**Anything else we need to know?**:

This is the data link (bucket name changed): https://mys3bucket.s3-us-west-2.amazonaws.com/${__data.fields[file_name]}

**Environment**:
- Grafana version: 7.1.4
- Data source type & version: InfluxDB 2
- OS Grafana is installed on: Docker (Ubuntu host)
- User OS & Browser: Chrome/Windows
- Grafana plugins: None
- Others:

**Comment by ryantxu** [comment]
Can you attach the panel/dashboard JSON for the panel with issues?

**Comment by loganmc10** [comment]
Sure here is the JSON:
[panel.txt](https://github.com/grafana/grafana/files/5105781/panel.txt)

Here is the live panel as well:
https://iot.bacoosta.com/d/58vVrW4Mz/traffic-cam?orgId=1&refresh=5m

The data link shows up as "View Picture" when you click on one of the data points

**Comment by loganmc10** [comment]
Didn't happen after the latest update to 7.2
