### ISSUE TITLE
Grafana doesn't display graph if any value has an & in the name

### ISSUE THREAD

**Issue by Jazz2k** [grafana/grafana#2710]
Currently i'm trying to monitor an ESXi cluster: T&D_Cluster but every time i try and specify the cluster name in Grafana, it errors and i'm unable to get grafana to show data as it doesn't like the & symbol in the name.

Is there any way to get around this? I've tried specifying a variable without the & and i cannot rename our ESXi Cluster.

I'm running latest 2.1.3 version.

Nothing ins JS error and in response I get: "IndexError: list index out of range" at the end.

Thanks, Lloyd

**Comment by torkelo** [comment]
What data source are you using, what is the metric query?

**Comment by Jazz2k** [comment]
Using Graphite as the data source. This gets the data using collectd from the vCenter server. One of the Vmware clusters is called T&D_Cluster (Don't ask, before my time ;) ).

**Comment by torkelo** [comment]
Stil not sure what the issue is, can you show the graphite query, the graphite response and the grafana display?

**Comment by Jazz2k** [comment]
See attached. 1 is when i put it in and doesn't complain, i click back to dashboard and then go back to Edit and then that's when it complains. 3 shows error. I can select any other cluster name and it shows correctly but doesn't like the '&' character.

![1](https://cloud.githubusercontent.com/assets/14195004/9810173/6dacd006-5866-11e5-894f-f98dbc1e2dba.PNG)
![2](https://cloud.githubusercontent.com/assets/14195004/9810174/6db016b2-5866-11e5-9ca9-26e0c2c5e4c5.PNG)
![3](https://cloud.githubusercontent.com/assets/14195004/9810175/6dbf62fc-5866-11e5-9622-c875f090e63b.png)
