### ISSUE TITLE
Consistent default log format

### ISSUE THREAD

**Issue by dirkschneemann** [grafana/grafana#27106]
**What would you like to be added**:
A consistent default log format which:
* Does not contain whitespace in the keys.
* Quotes all values.

In the current default log format, keys can contain whitespace characters. Quoting of values depends on whether the value contains whitespace characters or not.

Example from starting up Grafana:
```t=2020-08-20T16:04:14+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl= socket=```
The values of keys `t` and `lvl` are not quoted as they don't contain whitespace. The value of `msg`, however, is quoted because it contains whitespace between the words.

Example from an alerting rule changing its state:
```t=2020-08-20T16:04:15+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=291 name="Max Response Time Alert" changing state to=no_data```
The key `changing state to` contains spaces between the words. The values of keys `t`, `lvl` and `logger` do not contain whitespace and hence are not quoted. In contrast, the values of keys `msg` and `name` are quoted.

**Why is this needed**:
This inconsistent format makes it difficult to write log parsers in common log management tools. If the format was consistent, as in keys never contain whitespace and values are always quoted, this would be simplified a lot as one could apply a generic `key="value"` pattern.

**Comment by torkelo** [comment]
if you want to use a log parser use the json format

**Comment by dirkschneemann** [comment]
That's a fair work-around indeed.

**Comment by torkelo** [comment]
but the format looks strange, thinks it's our logging here. The log formatter is assuming no white space in keys. But not safe assumption. But the log framework that provides this format does not have a fix.
