### ISSUE TITLE
HTML does not render correctly in the text panel

### ISSUE THREAD

**Issue by Coro365** [grafana/grafana#27114]
**What happened**:
HTML does not render correctly in the text panel.

**How to reproduce it (as minimally and precisely as possible)**:
![Screen Shot 2020-08-21 at 13 47 56](https://user-images.githubusercontent.com/6727442/90853427-0de63d80-e3b5-11ea-9c3d-65e2a64ef24c.png)

**Environment**:
- Grafana version: v7.1.4 (82a235b54c)
- OS Grafana is installed on: Debian
- User OS & Browser: macOS 10.15.6 & Chrome

Thanks!

**Comment by torkelo** [comment]
html mode only allows non security sensitive html tags, 

disable security via this setting https://grafana.com/docs/grafana/latest/administration/configuration/#disable_sanitize_html
