### ISSUE TITLE
Datasource - Browser access with Auth and Credentials not working 

### ISSUE THREAD

**Issue by DagW** [grafana/grafana#27127]
**What happened**:
Added a new simple-json-datasource, and because of networking choose `Access: Browser`.  
I check the box for Basic Auth, and enter the credentials.  
I then check the box "With Credentials" to also send auth with CORS requests.  

When I press `Save and test` I get an error `NetworkError when attempting to fetch resource.`

I open up the dev-tools Network-tab and see I get a 401 on the CORS preflight request, and that the request did not contain any Auth-headers.

**What you expected to happen**:
The requestheader with Authentication to be present in the CORS request to the datasource.

**How to reproduce it (as minimally and precisely as possible)**:
Host a basic auth-protected simple-json-datasource on another domain, try to add it as a datasource with auth.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.0.5
- Data source type & version: simple-json-datasource
- OS Grafana is installed on: Centos7
- User OS & Browser: Firefox on Ubuntu
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
there is no way to send authorization credentials in the preflight request, you need to allow the preflight OPTIONS request so browser knows it's allowed crom a CORS perspective
