### ISSUE TITLE
Ordering for repeated panels/rows

### ISSUE THREAD

**Issue by matschaffer** [grafana/grafana#2712]
Building on #1888, it would be useful to be able to order repeats based on something like max or average value rather than what appears to be alphabetical currently.

The use case is that in a repetition, I'd want to see the largest values near the top of the display and any smaller (possibly spurious) values below the fold.

I can work around with custom variables and hard-coding the list, but then I have to make sure the list is up to date.

I'll also dig in to what I can do with scripted dashboards and report back.

**Comment by mtanda** [comment]
+1
This is nice feature! (but it is hard to support...)

**Comment by Akeru** [comment]
@matschaffer Did you make any progress on this ? I'd be interrested too

**Comment by matschaffer** [comment]
For now I've started just automating dashboard creation against the grafana
API with ruby.

I don't have auto-ordering worked out yet since manual ordering is working
out fine for now.

Since its one line of script per row in the dashboard, reordering is an
easy operation.

On Wednesday, 2 March 2016, Axel Bodart <notifications@github.com> wrote:

> @matschaffer <https://github.com/matschaffer> Did you make any progress
> on this ? I'd be interrested too
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/2712#issuecomment-191218932>.
>


-- 

-Mat

matschaffer.com

**Comment by mtanda** [comment]
link related issue, https://github.com/grafana/grafana/issues/5171

**Comment by torkelo** [comment]
the order needs to happen in the templating query, most TSDBs do not allow metric query value sorting in the metric exploration (metric find) style queries.
