### ISSUE TITLE
Cannot reference value from other hidden column in Data link

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#27123]
I'm using `{__data.fields[0]}` as Data Link value to reference link in the first column.

Then the first column is hidden (it's purpose is to only provide link value) using Transformations. The Data Link no longer references first (hidden) column but the first visible (second).

Related to https://github.com/grafana/grafana/issues/27091

**Comment by simPod** [comment]
I still can't find any docs about `${__data.fields[0]}` 🤔

**Comment by simPod** [comment]
@hugohaggmark can you elaborate on closing? The issue should have been resolved in linked PR but seems it has not. Thank you.

**Comment by hugohaggmark** [comment]
@simPod as Torkel stated this issue is a duplicate of #24092 and therefore we close this.

**Comment by hugohaggmark** [comment]
Duplicate of #24092
