### ISSUE TITLE
Ability to use custom wildcard for templating "All option"

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#2713]
I'm creating a templating variable that is populated by keys discovered in a graphite target (e.g. `servers.*.db*`, such as `servers.amsterdam.db1001`).

It is used to allow a dashboard to show multiple graphs, all overlaying data from all servers, or to focus in a single server (without clicking on it in each legend, especially when the legend is intentionally hidden as it would be too large).

The problem is that the "All option" doesn't use the provided wildcard. It uses `*` instead of `db*`, nor does it allow input of a custom value. Thus rendering the only (theoretically) working option "glob". However "glob" will result in the template value holding a manual listing all db servers separated by comma, which can be a great many. So many that the request to graphite fails (presumably due to query string exhaustion).

Being able to set the "All" value manually, or have it be copied from the input query (e.g. `db*`) would fix this problem.

I can sort of demonstrate this in Grafana Playground:

<img width="764" alt="screen shot 2015-09-10 at 06 58 39" src="https://cloud.githubusercontent.com/assets/156867/9781219/ad644040-5789-11e5-9144-3c744ba9b64b.png">
<img width="759" alt="screen shot 2015-09-10 at 06 58 42" src="https://cloud.githubusercontent.com/assets/156867/9781221/b3697eb0-5789-11e5-8b8a-142d13e692fb.png">
<img width="1102" alt="screen shot 2015-09-10 at 07 00 08" src="https://cloud.githubusercontent.com/assets/156867/9781223/ba839c4e-5789-11e5-80a5-fe189208e347.png">

**Comment by utkarshcmu** [comment]
Isn't "regex wildcard" option same as what is needed in the issue?

**Comment by timgriffiths** [comment]
Just hit this as well, what @Krinkle is trying to say i think is whatever value you write into the "All value" field will not persist, it just goes back to the default value. think it's a bug, not a feature request

Steps to replicate (and you can do this on the grafana play page as well)

1. Create a new template variable
2. Tick All value
3. Set a Glob value 
4. Hit apply
5. Edit the value again and you will see it's change back to the default.

**Comment by jsargiot** [comment]
> After all, it has an input field there. Which doesn't seem to be working at the moment.

Exactly my thought.

+1 to make "All value" editable.

**Comment by torkelo** [comment]
this is working in Grafana 3.0 :)
