### ISSUE TITLE
Sharing rendered images does not work because of google_analytics_ua_id

### ISSUE THREAD

**Issue by eunkyungkim** [grafana/grafana#2714]
# Fail case
grafana/conf/default.ini
```
google_analytics_ua_id = UA-xxxxxxxx-x
```
![2015-09-10 4 40 47](https://cloud.githubusercontent.com/assets/2121264/9782790/c48e217c-57da-11e5-8073-d0b41ecd1ce1.png)

grafana.log
```
2015/09/10 16:38:25 [I] PhantomRenderer::renderToPng url http://grafana.qostore.daumkakao.io:3000/dashboard-solo/db/adsindexer?panelId=1&fullscreen&from=1439278477484&to=1441870477484&width=1000&height=500
2015/09/10 16:38:25 [I] Completed /dashboard-solo/db/adsindexer 404 Not Found in 2.290548ms
2015/09/10 16:38:40 [I] Completed /render/dashboard-solo/db/adsindexer 404 Not Found in 15.005874908s
```

# Success case
grafana/conf/default.ini
```
google_analytics_ua_id = 
```
Image is displayed from url if google_analytics_ua_id is set blank
![2015-09-10 4 53 09](https://cloud.githubusercontent.com/assets/2121264/9783008/735dd66a-57dc-11e5-8f4e-317100607ab4.png)

grafana.log
```
2015/09/10 16:48:16 [I] PhantomRenderer::renderToPng url http://grafana.qostore.daumkakao.io/dashboard-solo/db/adsindexer?panelId=1&fullscreen&from=1439278477484&to=1441870477484&width=1000&height=500
2015/09/10 16:48:16 [I] Completed /dashboard-solo/db/adsindexer 404 Not Found in 1.341048ms
```

Url (/dashboard-solo/db/adsindexer) is error both fail and success case.
I used grafana version 2.1.3

**Comment by torkelo** [comment]
strange, http://play.grafana.org/dashboard/db/graph-styles  is using google analytics id and png rendering works

**Comment by bananayong** [comment]
In our case, we used grafana in company private network.
So, we need to set http_proxy environment variable.

cc. @eunkyungkim
