### ISSUE TITLE
Grafana plugins too long to download in China region

### ISSUE THREAD

**Issue by yogeek** [grafana/grafana#27149]
**What happened**:

cf. Initial description here :
https://github.com/integr8ly/grafana_plugins_init/issues/3

This is quite problematic because grafana pod is very long to be ready...

Is there a possibility to use any mirror site to download plugins currently ?

Thank you

**Comment by torkelo** [comment]
thanks for the info. 

Not sure we can do anything quick to fix this, Would suggest pre-downloading plugins and mounting that volume
