### ISSUE TITLE
feat: Elasticsearch Pipeline Aggregations

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#2715]
Support for the upcoming ES 2.0 [pipeline aggregations](https://www.elastic.co/guide/en/elasticsearch/reference/2.0/search-aggregations-pipeline.html) would be awesome.

Especially the derivative and moving average aggregations are interesting.

**Comment by yehosef** [comment]
+1 - this would be amazing, as even kibana doesn't support it yet

**Comment by yehosef** [comment]
also opened #3163 as an alternative

**Comment by yehosef** [comment]
notice - you can do raw queries in grafana - I just didn't know how.  see #3163  for details.

Still would be important to support this naturally - but it seems we have a work around for the short term

**Comment by bangert** [comment]
apparently raw queries are gone for 2.6. Does anybody have a prototype for pipeline aggregation support laying around?

**Comment by bergquist** [comment]
Im currently working on moving average for the ES datasource https://github.com/grafana/grafana/pull/3476

**Comment by torkelo** [comment]
moving average and derivative support is now merged to master!
![image](https://cloud.githubusercontent.com/assets/10999/11743096/0d9d696e-a005-11e5-892e-dee5a9327c42.png)

You can via the eye hide the base metric (that the pipeline aggregation is based on)

**Comment by torkelo** [comment]
Right now only window and model are the only support options, will add more soon:
![image](https://cloud.githubusercontent.com/assets/10999/11743116/3541e210-a005-11e5-91b0-ec5ccd7b751d.png)

**Comment by superdump** [comment]
Shiny!

**Comment by bergquist** [comment]
@felixbarny Would be great to hear your opinions on this.

**Comment by felixbarny** [comment]
will try this out later this day or tomorrow

**Comment by felixbarny** [comment]
Derivatives are working great so far. The only thing missing is the [units option](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-pipeline-derivative-aggregation.html#_units). For example, this lets you always display requests/minute no matter at which rate you report the total number of requests - so this is super important.

**Comment by torkelo** [comment]
@felixbarny I failed to that option to do anything, there was no change in the values returned from elasticsearch when I changed unit to "second" or "day" or "month".

**Comment by felixbarny** [comment]
That's strange. You checked for `normalized_value`, right? The `value` doesn't change.

**Comment by torkelo** [comment]
no, missed that part

**Comment by torkelo** [comment]
@felixbarny using normalized_value it worked, added unit option ,https://github.com/grafana/grafana/issues/3512
