### ISSUE TITLE
Dashboard in different organizations 

### ISSUE THREAD

**Issue by vivekgautam91** [grafana/grafana#27165]
**I have used single datasource in multiple organization for my different dashboards and made these dashboards public**:

**I am able get the access of all the dashboards which is public irrespective of organization **:

**I want the dashboards to be limited to organization level only**

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version:
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by torkelo** [comment]
what do you mean by "I have made these dashboards public:" ?
