### ISSUE TITLE
panel editor lost important shortcut: toggle legend

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#27179]
**What happened**:
The "toggle legend" shortcut seems to have been removed from Grafana 7 *panel editor*

When there are many series, it was useful to temporarily enable legend, select some series of interest, and hide the legend again.  It should possible to do this without navigating to the corresponding setting button.

**What you expected to happen**:
Where possible, shortcuts available on the regular panel view should also be available in the editor.

**Environment**:
- Grafana version: 7.1.4

**Comment by torkelo** [comment]
you can still use the shortcut p l from edit mode. 

But this extended panel menu where you have access to some panel specific actions is not available in the new edit mode

**Comment by belm0** [comment]
@torkelo I'm observing that the "p l" shortcut does not work in the Edit Panel, which is why I filed this bug.

Perhaps I'm misunderstanding.

**Comment by belm0** [comment]
Screenshot showing that "p l" is not listed in the panel dropdown.

![Screen Shot 2020-08-25 at 8 36 53 PM](https://user-images.githubusercontent.com/1708631/91169714-c217f900-e712-11ea-94d6-d4e181a1d740.png)

**Comment by belm0** [comment]
@torkelo please reopen this as it's a valid regression-- see above

**Comment by belm0** [comment]
I believe this regression was closed due to misunderstanding-- @hugohaggmark would you take a look?

"pl" shortcut is dearly missed during panel development
