### ISSUE TITLE
Time interval is not refreshing for links

### ISSUE THREAD

**Issue by ricardoimagu** [grafana/grafana#27172]
Hello Grafana Team,

**What happened**:
After upgrading to 7.1.3 we are experiencing this issue: the time variable is not updating for links. If time range is changed, all the variables in the dashboard are updated automatically except for the links. The time variable for the link continue without change, and the only way to update de time variable for links is:
1. Update time range
2. Refresh window
3. Use the link

**What you expected to happen**:
Once you change the time range, all the time variables in the dashboard should update. Before the upgrade when I used the link, it delivered a report based time according to the time range chosen. There was no need to refresh the window before using the link, all the graphs and the link took the new time range. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Configure a link on your dashboard (time dependent).
2. Choose a time range - > click on the link.
3. Choose another time range -> click on the link (yo will see that the link is not refreshing and you will have the same result as before changing the time range.) 

**Anything else we need to know?**:
If you refresh the window afeter changing the time range the issue is fixed.

**Environment**:
- Grafana version: Grafana v7.1.3 (5723d951af)
![dashboard after refreshing time interval](https://user-images.githubusercontent.com/33670861/91082250-0a99be80-e60e-11ea-8a24-23f64c630ec0.png)
![same link result everytime now-24](https://user-images.githubusercontent.com/33670861/91082251-0a99be80-e60e-11ea-8671-d2bf23c76046.png)

- Data source type & version: Zabbix Server / Zabbix MySQL
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows / Chrome
- Grafana plugins: The core plugins
- Others:
![dashboard before refreshing time interval](https://user-images.githubusercontent.com/33670861/91082248-09689180-e60e-11ea-9fec-d81a0723733a.png)

**Comment by torkelo** [comment]
thanks for opening an issue. 

This has been reported before (https://github.com/grafana/grafana/issues/26694) and fixed (https://github.com/grafana/grafana/pull/26845) 

will be included in 7.2
