### ISSUE TITLE
Storybook: Finalize icon component

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#27183]
**Component status**:
Icons are used all over Grafana as icon buttons, button decoration, explanatory visual element, etc. The existing component should be enhanced with better documentation. Also I'm not sure whether the component is extendable and uses theme for spacing etc.

- [x] Component has a story in Storybook.
- [x] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [x] It is extendable (rest props are spread, styles with className work, and so on).
- [x] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [x] Works with both light and dark theme.

**Documentation**
In my opinion the icon component needs some screenshots with examples how the icon is typically used in Grafana and an explanation of the different sizes we use.

- [x] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by peterholmberg** [comment]
Closing this since we have sufficient docs now.
