### ISSUE TITLE
Pushover: support for different priority for OK

### ISSUE THREAD

**Issue by alexhk** [grafana/grafana#27190]
If a Pushover alert of the priority EMERGENCY is sent I am woken up even if my iPhone is on silent or do not disturb. That is the way it is meant to be.  However, the OK notification for the same alert is still sent out using EMERGENCY priority, waking me up again :/

@Hofls implemented the option to choose a different sound for the OK alert a while ago, which is great. Now with the new EMERGENCY priority enabled on iOS by Apple for Pushover it would be great if we could choose a separate PRIORITY (i.e. default) for the OK alert too.

**Comment by hugohaggmark** [comment]
This seems like a reasonable suggestion @alexhk would be outstanding if we could get an external contribution on this one

**Comment by marefr** [comment]
Needs to add a new field to this file to support this: https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/pushover.go

**Comment by acaire** [comment]
I'd like to work on this one if no-one else is?

**Comment by aknuds1** [comment]
@acaire go ahead!

**Comment by alexhk** [comment]
@acaire are you still working on this?

This doesn't seem a difficult change, but I haven't contributed to Grafana so installing the building environment and setting everything up seems like a lot for just this change. I may still do it if nobody else does. Alternatively I could provide the changed file here in the issue and somebody else could test it.

**Comment by acaire** [comment]
@alexhk Definitely! Apologies, life has just got in the way - I believe I wrote all the changes but struggled to make the tests pass (after setting up the build environment as you mentioned 😉 ).  I'll square it away this weekend if that works for you?

**Comment by alexhk** [comment]
@acaire Hey, no worries, take your time!! Thanks for helping out, Grafana is awesome.
