### ISSUE TITLE
Feature: Panel Time Range override, support future dates

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#2719]
Is it possible to add future time in the time rang section? So that if we have a forecast chart, it will show the forecasted data rather than applying custom date
![time_over_write](https://cloud.githubusercontent.com/assets/3009225/9790920/a261cb00-57a6-11e5-9a70-8a8a72e30b4a.png)
 on top to every chart but only one chart.

**Comment by mtanda** [comment]
+1

**Comment by simisimis** [comment]
+1

**Comment by pakozm** [comment]
+1

**Comment by enric-sinh** [comment]
+1

**Comment by bbczeuz** [comment]
+1

**Comment by pakerfeldt** [comment]
+1

**Comment by mtanda** [comment]
@bergquist this issue and https://github.com/grafana/grafana/issues/2223 can be closed by https://github.com/grafana/grafana/pull/6309

**Comment by javaenthugm** [comment]
+1
