### ISSUE TITLE
alerts are not  get deleted after dashboard deletion and keeps in alerting state  

### ISSUE THREAD

**Issue by pratik141** [grafana/grafana#27193]
**What happened**: alert rules keep trying to notify even after dashboard got deleted

**What you expected to happen**: get error `t=2020-08-25T10:23:03+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=127 name="Alert Graph - EXTN_S_0006 alert" error="Could not find datasource Data source not found" changing state to=alerting"`

**How to reproduce it (as minimally and precisely as possible)**: 
- create a dashboard then alert
- keep the state alerting of the alert rule
- delete the dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version:
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Thanks for reporting this @pratik141 but I can't repro this on lastest `master` or in `Grafana 7.1.5`. Could you please upgrade to 7.1.5?

I'm going to close this for now but we can always reopen this is if fresh evidence point to this still being an issue in Grafana.
