### ISSUE TITLE
Stacked charts rendered incorrectly when sorted by descending value

### ISSUE THREAD

**Issue by zombar** [grafana/grafana#27199]
**What happened**: When sorting a stacked a chart with `y-min` set to `auto` in descending order, the chart isn't rendering the largest elements properly. In the screenshot below we can see that the green entry should occupy the most space in the chart because the value is the largest, but instead it appears cropped.

![grafana_bug](https://user-images.githubusercontent.com/13188505/91188928-c11ea180-e6e9-11ea-91a8-011b681d4b47.png)

**What you expected to happen**:

If we sort the legend in ascending order, the elements in the charts are rendered as expected with the green entry occupying the most space in the chart in line with the `current` value in the legend.

![grafana_bug2](https://user-images.githubusercontent.com/13188505/91189569-7fdac180-e6ea-11ea-8729-b00463d352df.png)

Note that if we set `y-min` to `0`, the issue no longer appears.

**Anything else we need to know?**:

We speculate that Grafana is sizing the stacks by the coefficient and not the exponent when sorting in descending order, if we sort in reverse order then it appears to be fine. To replicate this issue you'll need to graph elements several orders of magnitude apart on a stacked chart.

**Environment**:
- Grafana version: 7.0.4
- Data source type & version: Prometheus
- User OS & Browser: MacOS & Chrome

**Comment by torkelo** [comment]
looks correct to me (given auto y-axis min & max)

**Comment by torkelo** [comment]
if you sort in descending value the y-axis range will be limited to a small range (but with high values), so the auto y-axis will focus in on this small range

**Comment by torkelo** [comment]
If you think Grafana is doing something wrong let me know, stacking on descending order will result in a y-axis that your seeing and is correct

**Comment by zombar** [comment]
> if you sort in descending value the y-axis range will be limited to a small range (but with high values), so the auto y-axis will focus in on this small range

Thanks, that seems reasonable - just wanted to be sure.
