### ISSUE TITLE
Operators AND / OR in Alerts works strange

### ISSUE THREAD

**Issue by YellowNagger** [grafana/grafana#27200]
**What happened**:
Hello, today detected some strange behavior in alerts.

If we set only one WHEN we get 1 match
<img width="769" alt="Снимок экрана 2020-08-25 в 17 54 51" src="https://user-images.githubusercontent.com/9288297/91190956-db15af80-e6fc-11ea-837b-eeafcd0e1cf9.png">

If we set WHEN + OR, we get 12 matches.

<img width="803" alt="Снимок экрана 2020-08-25 в 17 54 32" src="https://user-images.githubusercontent.com/9288297/91190966-dcdf7300-e6fc-11ea-8025-0f3103ca8e14.png">

But if set WHEN + AND we also get 12 matches, and it will send information for all this matches, but in fact, i want get only matches which satisfy both cases. In our case it's 1 match, because in solo WHEN we have only 1 match.
<img width="787" alt="Снимок экрана 2020-08-25 в 17 53 53" src="https://user-images.githubusercontent.com/9288297/91190970-de10a000-e6fc-11ea-8a16-6cab6c95edcc.png">
**What you expected to happen**:
When we used operators AND, we get only matches which satisfy both cases.

**How to reproduce it (as minimally and precisely as possible)**:
I think u can reproduce it without any problems by screens.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v6.7.4 (8e44bbc5f5)
- Data source type & version: Clickhouse
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome last
- Grafana plugins: Don't know
- Others:

**Comment by hugohaggmark** [comment]
@YellowNagger not sure it's supposed to work like that. I think each query is evaluated by it self and then the `OR`/`AND` just decides if both evaluationsit evaluates each query.'

I'm closing this for now. We can always reopen this if this issue gets more upvotes.
