### ISSUE TITLE
Missing dimension for AWS/Events namespace

### ISSUE THREAD

**Issue by saragee3** [grafana/grafana#27202]
**What happened**: The `EventBusName` dimension is missing from the AWS/Events namespace

**What you expected to happen**: The EventBusName dimension should be an option under the AWS/Events namespace. Using the aws cli, running `aws cloudwatch list-metrics --namespace "AWS/Events"` command shows two dimensions so there seems to be a discrepancy with Grafana and AWS.

running aws command:

```
            "Dimensions": [
                {
                    "Name": "EventBusName",
                    "Value": ...
                },
                {
                    "Name": "RuleName",
                    "Value": ...
                }
            ]
```

grafana:

<img width="511" alt="Screen Shot 2020-08-25 at 11 38 17 AM" src="https://user-images.githubusercontent.com/15040665/91214130-83108600-e6c7-11ea-944b-5b7fd8dcca11.png">

**How to reproduce it (as minimally and precisely as possible)**:
- Add a new CloudWatch query to a dashboard
- Select AWS/Events as the namespace
- See that EventBusName does not show up on dimension keys list

**Anything else we need to know?**: Only rules within the default EventBridge bus generate results. This is an issue because when a developer creates a new EventBridge bus, the rules within that bus are not detected.

**Environment**:
- Grafana version: 6.4.5
- Data source type & version: CloudWatch
- OS Grafana is installed on: ubuntu
- User OS & Browser: macOS & Chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Probably need changes in here: https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go

**Comment by tomdaly** [comment]
Just created a draft PR to fix this, but it looks like you might want to contact AWS support about this @saragee3 - the official [AWS docs for CloudWatch events](https://docs.aws.amazon.com/AmazonCloudWatch/latest/events/CloudWatch-Events-Monitoring-CloudWatch-Metrics.html) state the only metric is `RuleName`, so I'd recommend contacting AWS to see if this is a problem with the docs or with the actual implementation.

Once you have a response then I can change the PR to ready to get your issue fixed 🚀

**Comment by tomdaly** [comment]
@saragee3 bump
