### ISSUE TITLE
Modify URL link of datasource in grafana dashboard 

### ISSUE THREAD

**Issue by vivekgautam91** [grafana/grafana#27208]
![status](https://user-images.githubusercontent.com/58827632/91285512-ee7f5400-e7aa-11ea-80a4-c5af34d3f1b7.png)

**I want to modify the url which we are getting from the datasource(Prometheus) to specific format.For example my URL is showing "https://www.example1.com" in my dashboard so i want to modify it to "example1" to show in my dashboard,Is there any way to do it.Like we can see in the attached pic i need to remove https from the url.**:

**To improve the dashboard visibility for the clients  **:

**Comment by vivekgautam91** [comment]
> ![status](https://user-images.githubusercontent.com/58827632/91285512-ee7f5400-e7aa-11ea-80a4-c5af34d3f1b7.png)
> 
> **I want to modify the url which we are getting from the datasource(Prometheus) to specific format.For example my URL is showing "https://www.example1.com" in my dashboard so i want to modify it to "example1" to show in my dashboard,Is there any way to do it.Like we can see in the attached pic i need to remove https from the url.**:
> 
> **To improve the dashboard visibility for the clients **:

**Comment by vivekgautam91** [comment]
Can anyone please help me on this.

**Comment by hugohaggmark** [comment]
Hi , we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
