### ISSUE TITLE
Support Influxdb 0.9 TOP Aggregate

### ISSUE THREAD

**Issue by Jhors2** [grafana/grafana#2721]
Hello,
Influxdb recently introduced a TOP aggregate that works a lot like highestAverage in graphite. However, the implementation changes the values typically returned. Let's say you want to see the top 5 server utilization grouped by datacenter:

select top(value, server, 5) from cpuUtil where $timeFilter group by time(60s),datacenter

This query will return JSON like:

```
{
"results": [
{
"series": [
{
"name": "CpuUtil",
"tags": {
"datacenter": "losAngeles"
},
"columns": [
"time",
"top",
"server",
],
"values": [
[
"2015-09-10T18:35:00Z",
8.45611008e+07,
"server1"
],
[
"2015-09-10T18:35:00Z",
9.2930048e+06,
"server2",
],
[
"2015-09-10T18:35:00Z",
6.32203946667e+06,
"server3",
],
[
"2015-09-10T18:35:00Z",
4.6465024e+06,
"server4",
],
[
"2015-09-10T18:35:00Z",
3.09766826667e+06,
"server5",
]
},
{
"name": "cpuUtil",
"tags": {
"pop": "Amsterdam"
},
"columns": [
"time",
"top",
"server",
],
"values": [
[
"2015-09-10T18:35:00Z",
126702.933333,
"server4",
],
[
"2015-09-10T18:35:00Z",
126702.933333,
"server2",
],
[
"2015-09-10T18:35:00Z",
63351.4666667,
"server3",
],
[
"2015-09-10T18:35:00Z",
63351.4666667,
"server1",
]
[
"2015-09-10T18:35:00Z",
63351.4666667,
"server12",
]
]
},
]
}
]
}
]
```

The obvious problem is, we want to get at the tag value returned for "server" to display in the legend, however I don't believe that is possible at this time. Can you add support please?

**Comment by otoolep** [comment]
@corylanou

**Comment by corylanou** [comment]
Hmm, it feels like we should probably return the tags that are in the results as well.  That shouldn't be too hard really.  @pauldix thoughts?

**Comment by pauldix** [comment]
Tags are associated with the series itself, so in the example result set it doesn't make sense. There are multiple servers in the result of each series so a single tag wouldn't map. In fact, each of the series returned would be best represented as a scatter plot of a different color (all dots in the same series the same color).

This is because the points may or may not be connected to each other. For example if you have a group by time of 10m, and top of 2, you could have 2 totally different servers in each 10m window.

It's more like you want to have two queries in one. The first, which executes a top function on some window of time, and then a second that looks for those specific values and groups by the tags. For example:

```sql
-- query 1
select top(value, host, 2) from cpu where time > now() - 10m group by region
-- results show server1, server2 in region west and server3, server4 in region east

-- query 2
select max(value) from cpu where time > now() - 4h and
  server = 'server1' OR
  server = 'server2' OR
  server = 'server3' OR
  server = 'server4'
group by time(1m)
```

It would be good to have a shorthand to represent that kind of query. Not sure what the cleanest way to do it would be though. It'll probably look janky any way we do it.

**Comment by torkelo** [comment]
I am not sure I understand this query: 
```
select top(value, host, 2) from cpu where time > now() - 10m group by region
-- results show server1, server2 in region west and server3, server4 in region east
```

When I see this query I see that it has an aggregation function TOP and group by 10m, and group by region. So we should get a series per region (west, and east) in 10m chunks that has 2 values for each host with the highest value FOR THAT 10m bucket, or am I missunderstanding this? 


Another style of query is Give me the top 5 servers with the highest average the last hour (that is group by and, filter by the average for the whole time range)

Might look something like this 
```sql
select mean(value) from cpu 
  where time > now() - 1h 
  group by host(top 5, mean(value), desc)
```

This query (with imaginary syntax) would aggregate by mean, group by host, but only show the top 5 hosts based on the average for that host for the entire time period of the query (1h)

Is this style of query related to the new TOP aggregate or is the above scenario unrelated?

**Comment by torkelo** [comment]
@Jhors2 I might be very confused so I hope paul can clarify, but I am not sure the influxdb top function is in any way analogous to Graphite's highestAverage. highestAverage is a sort and filter function that sorts and and filters series (never touching data values).  The TOP function in inflxudb looks like an aggregation function that sorts and limits data points.

**Comment by corylanou** [comment]
I'm not familiar with the `highestAverage` function, but I wrote the `TOP` function, and it is indeed an aggregate function that then sorts and limits points, exactly as you described.

**Comment by pauldix** [comment]
@torkelo you're right about the first query, it just limits the number of data points in each window of time.

I like the syntax of your imaginary query, but think I would modify it a little bit to something like:

```sql
select mean(value) from cpu
where time > now() - 1h
group by time(1m), top(mean(value), host, 5, 10m)
```

Which would be a nice shorthand way of saying, look at the average for all hosts in the last 10 minutes, then for the top 5, give me their series as a mean over each minute for the last hour.

**Comment by YBinnenweg** [comment]
:+1:

**Comment by pavel-odintsov** [comment]
Hello!

@pauldix sorry for writing to closed ticket.

I tried your recommendation for my data:
```
select mean(bits_incoming) from hosts_traffic where time > now() - 1h group by time(1m), top(mean(bits_incoming), host, 5, 10m)
```

But got unexpected error:
```
ERR: error parsing query: only time() calls allowed in dimensions
```

Also I tried to use mean() as top's argument but failed:
```
select top(mean(bits_incoming), "host", 5) from hosts_traffic
```

And this call also failed with error:
```
ERR: error parsing query: only fields or tags are allowed in top(), found mean(bits_incoming)
```

Is there is any way to get top working with Grafana?

I'm using InfluxDB 1.1.1.

**Comment by pavel-odintsov** [comment]
Hi guys!

If you need any help / information / testing from my side I would be glad to help.

**Comment by ryantxu** [comment]
![image](https://user-images.githubusercontent.com/705951/60134617-c20a1b00-9754-11e9-87f0-cbf68613252f.png)

I think this is supported... if not, we can reopen with more description
