### ISSUE TITLE
Variable cannot be used as table substitution in mysql datasource when "ALL" is added

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#27210]
**What happened**:

I want to create a dashboard where a query is based on a variable. I created a variable called `table` and added value `my_table`. I added a query `SELECT * FROM $table`. I got Error 1064 as my variable was put as `'$table'` instead of `$table` in the query resulting in `SELECT * FROM 'my_table'` which is invalid mysql syntax. This only happens when "Include All option" is added. Otherwise it works fine.

**What you expected to happen**:

I expect to be able to use the variable in my query

**How to reproduce it (as minimally and precisely as possible)**:

1. Add mysql datasource
2. Create variable
- Name: table
- Type: Custom
- Values: my_table
- Include All option: True
3. Create dashboard to the datasource as follow: `SELECT * FROM $table`
4. Observe that grafana has interpolated the `$table` into `'$table'`

**Anything else we need to know?**:
Perhaps related to https://github.com/grafana/grafana/issues/27119
However, it allso happens when "Multi-value" is selected

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: mysql
- OS Grafana is installed on: docker

**Comment by torkelo** [comment]
Since it's a multi value the default will be to quote the value, to disable the quoting, try  ${table:raw}
