### ISSUE TITLE
The maximum number of values under a single variable is 500

### ISSUE THREAD

**Issue by zio-pzl** [grafana/grafana#27217]
hello!
I set a global variable, and then when the dashboard is displayed, the drop-down box of this variable can only display 500 values at most. In fact, the value of this variable has exceeded 500, and the parameters passed to the back-end through grafana only have these 500 values. Is this grafana's restriction or something? Thank you
![image](https://user-images.githubusercontent.com/49870898/91289552-14b1ed80-e7c5-11ea-92a1-74c8fe313025.png)

**Comment by torkelo** [comment]
Depends on the data source and your variable query. 

What data source are you using?

**Comment by zio-pzl** [comment]
I use the ES data source.
You mean I didn't get all the data when I used the query statement?

**Comment by torkelo** [comment]
add a size option in your variable query
