### ISSUE TITLE
Alerts on InfluxDB Flux datasources only use the first series

### ISSUE THREAD

**Issue by verminity** [grafana/grafana#27218]
**What happened**:
When adding an alert to a graph backed by a Flux query that has multiple series the alert will only trigger if the first series breaks the condition 

**What you expected to happen**:
The alert should be triggered if any series breaks the condition

**How to reproduce it (as minimally and precisely as possible)**:
Create a multi-series graph against an InfluxDB Flux datasource. I used:

```
from(bucket: "servers")
  |> range(start: -10m)
  |> filter(fn: (r) =>
      r["_measurement"] == "cpu" and
      r["cpu"] == "cpu-total" and
      r["_field"] == "usage_idle"
  )
  |> group(columns: ["host"], mode: "by")
  |> aggregateWindow(every 1m, fn: mean)
```

Add an alert to the graph - e.g `WHEN avg() OF query(a, 5m, now) IS BELOW 10`

Save the panel

Click "Test Rule". In the returned object the `Condition[0]: Query Result` object will have a single element in the `data.series` array and there will be a single "Condition[0]: Eval:" object when there should be one per series.

**Anything else we need to know?**:

I have reproduced this bug with 7.1.4, 7.1.5 and the nightly Grafana builds against Influx 2 and Influx 1.8.

I have tried more complex queries that change the series names to be unique and minimise the information returned and the result is consistent. 

**Environment**:
- Grafana version:
Most testing done on 7.1.4. Reproduced on 7.1.5 and nightly.
- Data source type & version:
InfluxQL Flux (built-in)
- OS Grafana is installed on:
Redhat
- User OS & Browser:
Windows 10, Chrome
- Grafana plugins:
None other than built-in
- Others:

**Comment by Eraac** [comment]
I think the problem is worst, on my side it's seems to use the first series AND only the first point

My result here (with 15 points)
![image](https://user-images.githubusercontent.com/5497623/91440832-80e92b80-e86f-11ea-871d-03576ab55b45.png)

and the result in "Test Rule"
![image](https://user-images.githubusercontent.com/5497623/91440887-952d2880-e86f-11ea-8d64-93cd2cd8b65c.png)

**Comment by ryantxu** [comment]
@kylebrandt any ideas?  looks like with any query it gets one point in the series 

![image](https://user-images.githubusercontent.com/705951/92336667-e56a6e80-f057-11ea-9934-9c3a357b98dd.png)

**Comment by kylebrandt** [comment]
@ryantxu Can you show the dataframe structure for the query result?

**Comment by kylebrandt** [comment]
@ryantxu Actually nevermind, I can repro this with Azure Monitor datasource with the service of the same name. So I assume this is a frame per series model and there is an issue somewhere there.

**Comment by kylebrandt** [comment]
I suspect this may be because the query duration selected in the alerting condition (e.g. `query(A, 5m, now)` is not getting the same as what is seen in the visualization. If this changed to a longer period of time, or shifted back in time (10m to 5m, with 5m instead of now), does is still behave like this?

**Comment by ryantxu** [comment]
I see what the root issue is.  For alerting, maxDataPoints and interval are not sent to the actual request:
![image](https://user-images.githubusercontent.com/705951/92535183-82a9dc00-f1eb-11ea-8dd1-010a79ac9963.png)

In this case, it stops the query after one point.  We need to fix two things:
* maxDataPoints = 0 should be treated as unlimited
* the alert engine should pick a reasonable "interval" based on the time range.  I expect other datasources fail in weird ways when given an interval of zero.
