### ISSUE TITLE
Documentation Elasticsearch datasource logs explore

### ISSUE THREAD

**Issue by melchiormoulin** [grafana/grafana#27215]
Hello in https://grafana.com/docs/grafana/latest/features/datasources/elasticsearch/#querying-logs-beta
it said that we can switch between logs and metrics with the button but this button no longer exist.
https://grafana.slack.com/archives/C05675Y4F/p1596658860428300?thread_ts=1596646902.426300&cid=C05675Y4F

**Comment by zoltanbedi** [comment]
Hi @melchiormoulin, you are right. We have removed the buttons in 7.1 and made explore smarter so you don't have to manually select the mode but maybe we forgot to update the docs in some places 😅
If you or someone else can fix that that would help us a lot.

**Comment by melchiormoulin** [comment]
Hello @zoltanbedi , 
Thank you for your answer, i let someone with a better documentation knowledge do this.

**Comment by ahlaw** [comment]
Hi, can I take this issue? It appears [InfluxDb](https://grafana.com/docs/grafana/latest/features/datasources/influxdb/#querying-logs-beta) also has this issue. Should the docs be updated with a note about the 7.1 update?

**Comment by zoltanbedi** [comment]
Hi @ahlaw please do and the influx page as well. Nice catch! 👍
