### ISSUE TITLE
The query detail results is inconsistent with the query display

### ISSUE THREAD

**Issue by crazythinking** [grafana/grafana#27219]
As the following image, i config the query from ES;
![query](https://user-images.githubusercontent.com/5145888/91291515-c18d6a00-e7c7-11ea-8149-f347f4352171.jpg)

and I saw the query json as flowing:
'''

{
    "request": {
      "url": "api/datasources/proxy/4/_msearch?max_concurrent_shard_requests=5",
      "method": "POST",
      "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":[\"logstash-scac-online-sv-pit-2020.08.25\",\"logstash-scac-online-sv-pit-2020.08.26\"]}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1598349290997,\"lte\":1598435690997,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"tradeType.keyword: \\\"net.engining.scac.flow.Ca0220Flow\\\" AND tradeStatus.keyword: *\"}}]}},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"1d\",\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1598349290997,\"max\":1598435690997},\"format\":\"epoch_millis\"},\"aggs\":{}}}}\n"
    },
    "response": {
      "took": 184,
      "responses": [
        {
          "took": 183,
          "timed_out": false,
          "_shards": {
            "total": 2,
            "successful": 2,
            "skipped": 0,
            "failed": 0
          },
          "hits": {
            "total": {
              "value": 10000,
              "relation": "gte"
            },
            "max_score": null,
            "hits": []
          },
          "aggregations": {
            "2": {
              "buckets": [
                {
                  "key_as_string": "1598313600000",
                  "key": 1598313600000,
                  "doc_count": 8
                },
                {
                  "key_as_string": "1598400000000",
                  "key": 1598400000000,
                  "doc_count": 1150845
                }
              ]
            }
          },
          "status": 200
        }
      ],
      "$$config": {
        "url": "api/datasources/proxy/4/_msearch?max_concurrent_shard_requests=5",
        "method": "POST",
        "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":[\"logstash-scac-online-sv-pit-2020.08.25\",\"logstash-scac-online-sv-pit-2020.08.26\"]}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"@timestamp\":{\"gte\":1598349290997,\"lte\":1598435690997,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"tradeType.keyword: \\\"net.engining.scac.flow.Ca0220Flow\\\" AND tradeStatus.keyword: *\"}}]}},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"1d\",\"field\":\"@timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1598349290997,\"max\":1598435690997},\"format\":\"epoch_millis\"},\"aggs\":{}}}}\n"
      }
    }
  }

'''
you can see the result from ES have 2 rows data, the doc_count are "8" and "1150845" , but i want get the sum of the doc_count, not the average, so what is the problem, is it a bug?

**Comment by torkelo** [comment]
Change the Calculation option in the side options section.

![Screenshot from 2020-08-26 17-32-49](https://user-images.githubusercontent.com/10999/91324339-3f4e7700-e7c2-11ea-8a79-43a98d2809a4.png)

**Comment by crazythinking** [comment]
thanks for your help
