### ISSUE TITLE
`make run` script fails to run the web server

### ISSUE THREAD

**Issue by manashegde** [grafana/grafana#27212]
I followed the instructions mentioned here https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md and installed all the necessary requirements. 

Once i run 'make run' command i see below error
![image](https://user-images.githubusercontent.com/5063167/91270375-29c35800-e796-11ea-9607-587f45453a7f.png)

Environment
Windows 10 professional (x64)

**Comment by xlson** [comment]
@AgnesToulet perhaps you have some idea what this issue could be related to?

**Comment by xlson** [comment]
Actually, looking at the logs it loks like you are running a non-standard build of make ([this](https://www.npmjs.com/package/make) I presume?). Internally we are using gnu-make which I think you should be able to install via cygwin or something similar.

**Comment by AgnesToulet** [comment]
I'm on Windows 10 Pro too and I installed [Make for Windows](http://gnuwin32.sourceforge.net/packages/make.htm) to be able to run the make commands.

**Comment by xlson** [comment]
I hope this helps. I will close this issue for now, let us know how it goes.

**Comment by manashegde** [comment]
@xlson It really helped thanks a lot
