### ISSUE TITLE
database host not resolved with getaddrinfo

### ISSUE THREAD

**Issue by rockandska** [grafana/grafana#27220]
version: 6.7.2

Hi,

It seems that Grafana do not use `getaddrinfo` to resolve the address of the database host provided in configuration (`/etc/grfana/grafana.ini`).
I have specific configuration in `/etc/gai.conf` who add precedence configuration to choose ipv4 first over ipv6 and works as it does with many software but not with grafana. In the log I clearly see grafana trying to reach the database over Ipv6.

Any chance to use `getaddrinfo`  in every place who need to resolve hostname ?

Regards

**Comment by rockandska** [comment]
It seems that it could be changed by adding `netcgo` build tag

**Comment by xlson** [comment]
Grafana uses the go resolver by default, unfortunately it is slightly different than the glibc implementation. Could you try switching resolver yourself and see if that solves your issue? You can switching resolver by setting an environment variable before starting Grafana.

```
export GODEBUG=netdns=cgo   # force cgo resolver
```

Let me know if this solves your issue.

**Comment by rockandska** [comment]
Did not try it yet, but since on windows it always uses glibc implementation (cf go documentation), having `netcgo` in build tag will provide consistency for the resolver across all platforms too.

Is there any real advantages to use internal go resolver instead of glibc ?

I will give you a feedback as soon as possible

**Comment by rockandska** [comment]
Adding it in a systemd override.conf doesn't seems to help.
netdns (even with cgo) seems to don't respect rules inside `/etc/gai.conf` ([a Tyk user reported a similar case](https://community.tyk.io/t/tyk-ignoring-ipv4-preference-for-dns-lookup/1995))

**Comment by rockandska** [comment]
Sorry, I re-test it and seems to works as it does.
I had set it to `Environment=GODEBUG="netdns=cgo"` instead of `Environment=GODEBUG=netdns=cgo` in my override.

**Comment by xlson** [comment]
I'm glad it worked. I think the go dns resolver is slightly faster and less resource intensive. It works for the vast majority of users so I don't think it would make sense to switch to cgo by default at this time, but we'll keep an eye on things.
