### ISSUE TITLE
Migrate core datasources to fetch API

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#27222]
Core data sources to migrate to observables:
- [x] Google Cloud Monitoring (#28847) 
- [x] Cloudwatch (#28865) 
- [x] Elastic (#30009)
- [x] Graphite (#31928)
- [x] InfluxDB (https://github.com/grafana/grafana/pull/28555)
- [x] Jaeger (#31969)
- [x] Loki (#27265)
- [x] MSSQL (#28809)
- [x] MySQL (#27649)
- [x] OpenTSDB (#29992)
- [x] Postgres (#27478)
- [x] Zipkin (#30829)
- [x] Prometheus (#27090)
- [x] Tempo (#31618)

**Why is this needed**:

[datasourceRequest](https://grafana.com/docs/grafana/latest/packages_api/runtime/backendsrv/#datasourcerequest-method) method is now deprecated in favour of [fetch](https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L67) method. This was introduced in https://github.com/grafana/grafana/pull/26043

For some inspiration please take a look at [Test Datasource](https://github.com/grafana/grafana/blob/64bc85963b2b2afe86ad3c61510b9b1e41e9fb7a/public/app/plugins/datasource/testdata/datasource.ts) or @hugohaggmark [PR migrating prometheus data source](https://github.com/grafana/grafana/pull/27090)

**Comment by mckn** [comment]
@zoltanbedi are you working on migrating the Jaeger datasource to the fetch API?

**Comment by zoltanbedi** [comment]
@mckn not right now but can do that next week.

**Comment by mckn** [comment]
> @mckn not right now but can do that next week.

Ok ok, it is up to you :) If you don't have the time I can give it a shot at the end of next week. Just wanted to check so we don't work on the same thing independently.

**Comment by mckn** [comment]
Done and done
