### ISSUE TITLE
"Forgot password" link not honouring root_url

### ISSUE THREAD

**Issue by ntavares** [grafana/grafana#27226]
**What happened**:
When using root_url (e.g. to change the base uri for grafana), the login form presents a "broken" link for "Forgot your password?" .... it links to /user/password/send-reset-email, instead of {root_url}/user/password/send-reset-email

Grafana is (docker image) Grafana v7.1.5 (9893b8c53d)

**Comment by xlson** [comment]
Thanks for reporting this issue!

Note: can be verified using the `nginx_proxy` docker block in devenv.
