### ISSUE TITLE
Error Loading News when adding rss link

### ISSUE THREAD

**Issue by runultra** [grafana/grafana#27234]
**What happened**: error loading news error displayed when trying to add an rss feed link to news feed
<img width="601" alt="Screen Shot 2020-08-26 at 5 01 56 PM" src="https://user-images.githubusercontent.com/54156332/91356569-e11f9500-e7bd-11ea-8d68-f7a22da1b3da.png">

**What you expected to happen**: load the rss feed

**How to reproduce it (as minimally and precisely as possible)**: add https://status.slack.com/feed/rss to a news feed url

**Anything else we need to know?**: other rss feeds work

**Environment**:
- Grafana version: 7.0.6
- Data source type & version: news (rss)
- OS Grafana is installed on: ubuntu 16.04
- User OS & Browser: MacOS & Chrome
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
works for me, try enabling the proxy option 

![Screenshot from 2020-08-27 13-56-13](https://user-images.githubusercontent.com/10999/91439372-1d5dfe80-e86d-11ea-981c-da8f1439ac07.png)

**Comment by runultra** [comment]
Interesting, With and without proxy this did not work yesterday. Today it is working (with Proxy enabled)

Thanks @torkelo!

**Comment by hakro** [comment]
Hi there,

I'm getting the same issue as well. Tested on Version 7.4.2 and 7.4.5, with both Proxy enabled or not.

I Tested with the slack link mentioned above, and with a link from Medium : https://laurent-bel.medium.com/feed

The panel prints : Error Loading News, But I see nothing in the logs.

Cheers.

**Comment by trogau** [comment]
@hakro: If you look at the browser web developer console you'll probably see an error message relating to CORS headers. The current version of the plugin ships with a hard-coded CORS proxy (https://cors-anywhere.herokuapp.com/). 

If you visit that URL you'll see a message saying it is no longer available by default to random users; you can click a button there to temporarily allow your system access. Then you should be able to add your RSS URL, enable the CORS switch, and it should work (as long as your RSS is well-formed).

**Comment by MaartenMol** [comment]
> @hakro: If you look at the browser web developer console you'll probably see an error message relating to CORS headers. The current version of the plugin ships with a hard-coded CORS proxy (https://cors-anywhere.herokuapp.com/).
> 
> If you visit that URL you'll see a message saying it is no longer available by default to random users; you can click a button there to temporarily allow your system access. Then you should be able to add your RSS URL, enable the CORS switch, and it should work (as long as your RSS is well-formed).

Is there a more permanent solution to this?

**Comment by tyleraharrison** [comment]
Why was this issue closed? I am still having this happen and this CORS problem was the solution.

**Comment by qcasey** [comment]
This issue is the first to appear when googling this problem.

> Is there a more permanent solution to this?

As of today, it appears the proxy toggle was removed because the **public** CORS proxy server was depreciated (#37841). However self hosting that CORS proxy still works for me. 

People here can try with mine first to see if the method works, using `https://cors.letterq.org/<RSS URL>` for the panel.

Hosting your own:

```compose
version: '3.1'

services:
  cors:
    image: redocly/cors-anywhere@sha256:f70cba287d76a1031ee8aa453f9fdb83e7bf65aff7c226960b1886a060e80def
    restart: unless-stopped
    ports:
      - 3039:8080
```
