### ISSUE TITLE
Add a datasource for Impala

### ISSUE THREAD

**Issue by xiaoshengMr** [grafana/grafana#27239]
**What would you like to be added**:
grafana add  impala dataSource
**Why is this needed**:
We use olap impala store data and want to show data in grafana ,find not datasource and plugin can support the impala 
Or We hope community can provide the way to solve the program

**Comment by xlson** [comment]
This would probably best be added by someone in the community as a datasource plugin for Grafana. I will leave this as an open feature request for now.

**Comment by xiaoshengMr** [comment]
Community can support  the tutorial document about custom datasource plugin ？
