### ISSUE TITLE
Setting templating variables with URL params #2

### ISSUE THREAD

**Issue by madshall** [grafana/grafana#2723]
Hi,

I'm passing the value for variable via URL param. The issue is that the text of the dropdown is correct, but the corresponding item is not really selected. This become a problem if I click on the dropdown and then remove focus from it without selecting anything - the value resets.

**Comment by torkelo** [comment]
What version of Grafana are you using?

**Comment by madshall** [comment]
We're currently using version 2.1.0.

**Comment by torkelo** [comment]
I think this issue is fixed in 2.1.3
