### ISSUE TITLE
Grafana date filter is not showing in chrome but visible in IE

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#27238]
**What happened**:

**What you expected to happen**:
date filter should be visible
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:6.2.O(beta 2)
- Data source type & version:sql server 2017
- OS Grafana is installed on:windows
- User OS & [Browser:Chrome](url)
- Grafana plugins:
- Others:

[Date filter.docx](https://github.com/grafana/grafana/files/5134137/Date.filter.docx)

**Comment by torkelo** [comment]
Try latest Grafana (7.1.5) 

Will re-open if problem remains, but no other reports like this
