### ISSUE TITLE
[DOCS] Misleading/incomplete documentation about session storage and Grafana HA configuration

### ISSUE THREAD

**Issue by carlosjgp** [grafana/grafana#27244]
**What happened**:
Reading this tutorial
- https://grafana.com/docs/grafana/latest/tutorials/ha_setup/
- https://github.com/grafana/grafana/blob/master/docs/sources/tutorials/ha_setup.md

I can't find the `[sessions]` configuration section
https://grafana.com/docs/grafana/latest/administration/configuration

searching through Grafana's forum I found this
- https://community.grafana.com/t/grafana-v6-and-user-session-session-storage/16887

https://community.grafana.com/t/grafana-v6-and-user-session-session-storage/16887
> We use a cache for this and by default Grafana’s database is used, but in HA you might want to setup memcached or redis to do this instead so you don’t overload the database with queries for these tokens.

**What you expected to happen**:
I'm not sure how to configure Grafana HA

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by xlson** [comment]
Hi,

You should only need to configure memcached for HA when using the auth proxy. There is a remotecache that you can setup, read more about configuring it [here](https://grafana.com/docs/grafana/latest/administration/configuration/#remote_cache) but you should be able to run without it for now. This might change in the future.

**Comment by carlosjgp** [comment]
thanks for your response @xlson

I tried to deploy Grafana helm chart with 2 replicas with Github Auth mechanism without `[remote_cache]` and it causes an infinite redirection

I understand that [auth proxy](https://grafana.com/docs/grafana/latest/auth/auth-proxy/) is different from the [auth provider Github](https://grafana.com/docs/grafana/latest/auth/github/)

I can't see any reference to `remote_cache` on any of them either and the original references this tutorial
> https://grafana.com/docs/grafana/latest/tutorials/ha_setup/

which refers to configuration block `[sessions]` which does not exist anymore

The link provider to `[remote_cache]` does not explain what that configuration block is doing... `cache` could be about queries to the datasources.
But it does not explains what data is being stored here or why could this be required
![screenshot-grafana com-2020 08 27-13_32_08](https://user-images.githubusercontent.com/1277613/91442511-dde1e300-e869-11ea-94ab-682efe964b60.png)

Only the experience and using Google and reading other people with the same issue throughs some clarity about the requirements to run Grafana on HA

I don't think this issue should have been closed without amending the documentation for that tutorial and adding more documentation or clarifying the exiting one

This is my experience as DevOps operating Grafana

**Comment by xlson** [comment]
Thank you for the feedback and details about your problem. I'll have to dig into this, I wouldn't have thought you needed to configure the remote cache for GitHub OAuth to work in HA.

**Comment by torkelo** [comment]
What did you use for your main Grafana DB? MySQL or Postgres? If you run grafana in HA you need one of those

**Comment by carlosjgp** [comment]
> What did you use for your main Grafana DB? MySQL or Postgres? If you run grafana in HA you need one of those

I do not use any database I have no need of one since Dashboards and Datasources are ConfigMaps, Annotations are just PromQL queries and users are managed by Github OAuth
This is a deployment on Kubernetes using the Grafana Helm chart
https://github.com/helm/charts/tree/master/stable/grafana
(I just saw it has been deprecated)

And I just deploy Grafana using Github OAuth and 2 replicas and ingress `grafana.<env>.<company domain>`
The observed behaviour has been that when loading Grafana page and click on the link to login using Github
the error 302 too many redirects happen. But downscaling to 1 replica everything works correctly.

After that configuring [`remote_cache`](https://grafana.com/docs/grafana/latest/administration/configuration/#remote_cache) allows to deploy multiple multiple replicas.

I see how "shared" storage might be required to validate that the user has been authenticated by the other instance but it's unclear reading the documentation which one is

By the way, I'm using Nginx Ingress in case you are wondering

Thanks for the time to look at this.

**Comment by xlson** [comment]
@carlosjgp The lack of a shared database would explain your problems. Grafana is not designed to run in HA without a shared database. This is unlikely to change anytime soon.

I'm not entirely sure how the documentation is unclear. As you say, it specifies multiple times that you need to setup a shared database, either mysql or postgres. Do you have any suggestions for how we could improve the wording?

To me, the need for a shared DB (either MySQL or Postgres) is clear in the first section of the HA guide:
> Setting up Grafana for high availability is fairly simple. You just need a shared database for storing dashboard, users, and other persistent data. So the default embedded SQLite database will not work, you will have to switch to MySQL or Postgres.

**Comment by carlosjgp** [comment]
Fair enough but documentation still makes reference to "Stateless sessions"
https://grafana.com/docs/grafana/latest/tutorials/ha_setup/
> You can also choose to store session data in a Redis/Memcache/Postgres/MySQL which means that the load balancer can send a user to any Grafana server without having to log in on each server
![screenshot-grafana com-2020 09 14-17_05_12](https://user-images.githubusercontent.com/1277613/93109929-90100c00-f6ac-11ea-89b2-84f986137e30.png)

And as I explained above I'm not using the DB to store users or dashboards that's why I'm not deploying the database the documentation says or at least suggests, that it could be done with Redis or Memcache... so I understood that the MySQL or Postgres DB was not required but it looks like it's always required.

Personally I found that section misleading it also because it makes reference to a configuration section that doesn't exist anymore

**Comment by torkelo** [comment]
it's an old tutorial. It's pretty clear that you need Postgres/MySQL for a HA setup. 

There is this update in as well:

> After Grafana 6.2 you don’t need to configure session storage since the database will be used by default. If you want to offload the login session data from the database you can configure remote_cache

But yes, the session paragraph can need an update. Will fix!

**Comment by efasel** [comment]
Hi!

I was following the documentation for [Set up Grafana for high availability – User sessions](https://grafana.com/docs/grafana/latest/administration/set-up-for-high-availability/#user-sessions):
> If you want to offload the login session data from the database you can configure remote_cache

But the [previous comment](https://github.com/grafana/grafana/issues/27244#issuecomment-692195081) indicates that the documentation is outdated. :-\ 

We are in a similar situation as described in some comment above and have no need for a database, e.g. all dashboards are dynamically created on startup. Still it would be nice to run more than one instance of grafana for higher availability and zero downtime deployments. But this would require to store the user session somewhere else outside of grafana itself. But only the user sessions.

If I understand it correctly this is simply not possible. What a pity. Would have been nice. 

By the way: otherwise great product, thanks!
