### ISSUE TITLE
Auth-proxy does not work with OAuth2_Proxy

### ISSUE THREAD

**Issue by lyndon160** [grafana/grafana#27251]
**What happened**:
Grafana defaults to prefered username in cookie even when auth header with username attached is provided. This makes it not possible to use AuthProxy with some Identity aware proxies like OAuth2_proxy.

Using postman accessing Grafana directly and manually setting X-Forwarded-Email header gives the correct response. So I know that part is configured correctly.

When going through chrome and hitting the proxy, Grafana returns  {"message": "Invalid username or password"}. I can see in the logs that it's got the value (prefered_username) from a stored cookie (given by the proxy), instead of the header that was passed. This also takes it through another flow in Grafana which doesn't allow auto-sign up, presumably because it thinks you've already signed up and are using a cookie.

I have used Louketo proxy with a very similar setup previously and it worked. Just the cookie contents are different, and not picked up by Grafana.

Is there any way I can configure Grafana to respect the  GF_AUTH_PROXY_HEADER_NAME over everything else?

**What you expected to happen**:

To login and auto create a user based on the X-Forwarded-Email. This is detailed here: https://grafana.com/docs/grafana/latest/auth/auth-proxy/

**How to reproduce it (as minimally and precisely as possible)**:

Using the following config + identity provider config in docker-compose, hit the proxy and see the 401 error.

Grafana with the following envs
`
      GF_AUTH_PROXY_ENABLED: "true"
      GF_AUTH_PROXY_HEADER_NAME: X-Forwarded-Email
      GF_AUTH_PROXY_HEADER_PROPERTY: email
      GF_AUTH_PROXY_AUTO_SIGN_UP: "true"
      GF_AUTH_PROXY_ENABLE_LOGIN_TOKEN: "false"
      GF_AUTH_PROXY_HEADERS: "Name:X-Forwarded-Email Email:X-Forwarded-Email"
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: Admin

`
https://github.com/oauth2-proxy/oauth2-proxy
OAuth2_proxy (latest) with the following envs

`    OAUTH2_PROXY_UPSTREAMS: http://grafana:3000/
      OAUTH2_PROXY_REDIRECT_URL: http://grafana.localhost:8080/oauth2/callback
      OAUTH2_PROXY_HTTP_ADDRESS: 0.0.0.0:4180
      OAUTH2_PROXY_REVERSE_PROXY: "true"
      OAUTH2_PROXY_PASS_USER_HEADERS: "true"
      OAUTH2_PROXY_COOKIE_DOMAIN: grafana.localhost
      OAUTH2_PROXY_PREFER_EMAIL_TO_USER: "true"
`

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version:
- OS Grafana is installed on: Using the main Grafana docker image, linux
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: Using Auth Proxy mode in Grafana

**Comment by torkelo** [comment]
Grafana sets no username cookie for auth proxy paths, sure this is not a problem in your oauth2 proxy?

**Comment by lyndon160** [comment]
I’ve use the whoami container to print out the headers. The X-Forward-Email header there so it should work. The value set there is my email address. Copying this value exactly to postman and making a request directly to Grafana avoiding the proxy gives the desired effect.

In the Grafana debug logs, it shows a failed login attempt using a uuid which is only present in the cookie provided by the Proxy under field called preferred user. That’s how I know that it’s reading the Cookie and ignoring the header which contains my email address. The problem with this is not that the preferred username field is wrong, but that Grafana is treating it as a different login flow, which does not do auto sign up.

I’ll copy the output from whoami when I’m next at my computer. I’ll also paste in the Grafana logs.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by lyndon160** [comment]
When Grafana logs when logging in via oauth2_proxy:

grafana           | t=2020-08-28T11:30:23+0000 lvl=dbug msg="Failed to authorize the user" logger=context username=<uuid in proxy cookie under preferred user>
grafana           | t=2020-08-28T11:30:23+0000 lvl=eror msg="Invalid username or password" logger=context error="No password provided"
grafana           | t=2020-08-28T11:30:23+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=401 remote_addr=172.29.0.1 time_ms=0 size=42 referer=http://grafana.localhost:8080/


When using postman (with X-Forwarded-Email set) to avoid the proxy:

grafana           | t=2020-08-28T11:31:02+0000 lvl=dbug msg="Trying to log user in" logger=auth.proxy username= ignoreCache=false
grafana           | t=2020-08-28T11:31:02+0000 lvl=dbug msg="Getting user ID via auth cache" logger=auth.proxy cacheKey=auth-proxy-sync-ttl:85c0264fde27aa06580444537a627ad0
grafana           | t=2020-08-28T11:31:02+0000 lvl=dbug msg="Failed getting user ID via auth cache" logger=auth.proxy error="cache item not found"
grafana           | t=2020-08-28T11:31:02+0000 lvl=dbug msg="Got user ID, getting full user info" logger=auth.proxy userID=2
grafana           | t=2020-08-28T11:31:02+0000 lvl=dbug msg="Successfully got user info" logger=auth.proxy userID=2 username=<my email adddress>
grafana           | t=2020-08-28T11:31:02+0000 lvl=dbug msg="Updating last user_seen_at" logger=context userId=2 orgId=1 uname=<my email adddress> user_id=2



whoami response behind proxy:

Hostname: 643ad30a0a95
IP: 127.0.0.1
IP: 172.29.0.2
RemoteAddr: 172.29.0.7:56836
GET / HTTP/1.1
Host: whoami.localhost:8080
User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.105 Safari/537.36
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9
Accept-Encoding: gzip, deflate, br
Accept-Language: en-US,en;q=0.9
Authorization: Basic <redacted>
Cache-Control: no-cache
Cookie:
<redacted> includes {"PreferredUsername":"<uuid>"}
Pragma: no-cache
Sec-Fetch-Dest: document
Sec-Fetch-Mode: navigate
Sec-Fetch-Site: none
Sec-Fetch-User: ?1
Upgrade-Insecure-Requests: 1
X-Forwarded-For: 172.29.0.1, 172.29.0.4
X-Forwarded-Host: whoami.localhost:8080
X-Forwarded-Port: 8080
X-Forwarded-Email: <my email>
X-Forwarded-Preferred-Username: <my email>
X-Forwarded-Proto: http
X-Forwarded-Server: 2f2f4ff3cb8e
X-Forwarded-User: <my email>
X-Real-Ip: 172.29.0.1

**Comment by marefr** [comment]
Based on error message "Failed to authorize the user" basic authentication fails. Please try disable basic auth:

```ini
[auth.basic]
enabled = false
```

**Comment by lyndon160** [comment]
@hugohaggmark @marefr @torkelo thanks for your help. Disabling basic auth worked. By default OAuth2_Proxy passes through the preferred username in the authorisation header which Grafana was picking up, hence the confusion around the cookie in the initial description above.

**Comment by marian-gheorghe** [comment]
@lyndon160 I am facing a similar issue with yours (see linked above), any idea what am I doing wrong, maybe this functionality is broken in grafana in the meantime ?
