### ISSUE TITLE
"Edit" not taking to editing tabs

### ISSUE THREAD

**Issue by YemaneZewdu** [grafana/grafana#27256]
I am using the latest Grafana (just installed today) in Chrome on Mac Catalina OS with Elasticsearch. I clicked on "Edit" under the Panel Title but it is not opening the General, Metric, Axes, ... tabs section as expected. I also tried it in Safari but the same result. 

Is there something I missed?

Thank you

**Comment by torkelo** [comment]
What are you seeing then? Nothing? Any errors in chrome web console?

**Comment by YemaneZewdu** [comment]
Thanks for your reply. This is what I see in edit mode. I am totally new to this. I apologize for any inconvenience or silly errors.

Thank you!
<img width="1792" alt="Screen Shot 2020-08-28 at 9 19 32 AM" src="https://user-images.githubusercontent.com/28067788/91565291-fad0f180-e90f-11ea-8491-7d174e5b9610.png">

**Comment by torkelo** [comment]
That is the edit mode, seems like you have hidden the side option, click show options button in top right to show side bar pane

**Comment by YemaneZewdu** [comment]
Thanks for your reply. Are the General and Metrics tabs removed on the latest UI? 

Thank you

**Comment by torkelo** [comment]
Metric is the same just named query ,

General is not made that but same stuff can be found in the side bar
