### ISSUE TITLE
36h in timepicker display 2d

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2725]
![grafana-36h-bug](https://cloud.githubusercontent.com/assets/8385646/9801252/3a9861de-5812-11e5-8895-32877366719e.gif)

**Comment by torkelo** [comment]
Looks like a bug

**Comment by torkelo** [comment]
oh, and thanks for reporting this

**Comment by rschitz** [comment]
My pleasure to contribute even with such little details ;)

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/issues/2761
