### ISSUE TITLE
Unable to Import csv export  in Excel (German Locale) with new lines inside Values

### ISSUE THREAD

**Issue by atummid** [grafana/grafana#27268]
**What happened**:
Download the csv file from Table panel with some of the columns having  **new line character** in them.
Unable to import it  in Excel inside windows 10 machine with German locale

**What you expected to happen**:
Excel should open the file successfully.
At least after doing Text to Column wizard it should open correctly.(required in german locale where it expects ; and NOT ,)
Instead , it got jumbled up even after that wherever we have newline inside the column/cell value

**How to reproduce it (as minimally and precisely as possible)**:
Have a Table to populate with data containing new line characters
export as csv and open in windows 10 using German locale in Excel and use Text to Column COnversion.
You see data jumbled up and not formatted properly

**Also Users are extremely unhappy with the upgrade from 6 to 7 because they cannot open file diretly anymore as it want semicolon as seperator. Can we make it global configuration  or give choice to user while download or detect user locale and accordingly use appropriate delimiter**

**Anything else we need to know?**:
This Occurred only in German locale.

**Environment**:
- Grafana version:v7.1.5  hosted on SUSE sp4
- Data source type & version: Postgres V10
- OS Grafana is installed on:
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: Table Plugin
- Others:

**Comment by torkelo** [comment]
If anyone wants to help investigate / fix this: https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/utils/csv.ts#L195

**Comment by atummid** [comment]
Again ...when semicolon is used as delimiter and then open the file in CSV in german locale then even having a new line has no issues at all. More than fixing the code it has more to with passing the locale from browser onto backend and use that to determine the correct delimiter is the way . The function seems correct and nothing has to be changed but the delimiter itself ...

**Comment by tomdaly** [comment]
Hi, this is an interesting bug and I think I have a possible solution for this - PR incoming

**Comment by atummid** [comment]
Thanks for quick reply.loking forward to this. We had to rollback the upgrade just bcoz of this .No matter how many fancy things are there innew version and if existing things break users don't want it

**Comment by atummid** [comment]
![image](https://user-images.githubusercontent.com/48974304/91685250-72ed2080-eb77-11ea-8414-76faa844ad6a.png)
May be this Dialect is what we are missing in this v7 ?
