### ISSUE TITLE
Improve performance and error handling in retrieving Cloudwatch Metrics

### ISSUE THREAD

**Issue by seanlok** [grafana/grafana#27260]
**What would you like to be added**:
Improve the efficiency to read metrics from cloudwatch as bigger AWS account with larger resources will cause the API call to be throttled even with a default dashboard. And also to make sure the new limit are adjusted to 500, as the [new limit](https://aws.amazon.com/about-aws/whats-new/2020/03/amazon-cloudwatch-now-provides-more-metric-data-faster-with-getmetricdata-quota-increase/) is announced in March 2020. 

**Why is this needed**:
This is currently very hard to read and retrieve the data from cloudwatch. Even a 30 min interval will get throttled: 
![image](https://user-images.githubusercontent.com/29034723/91540788-e1e73100-e94d-11ea-8d2b-5a845ab3b666.png)

**Comment by torkelo** [comment]
There is not much Grafana can do here, this limit and performance problem on the AWS side. 

For a larger AWS account, you need to introduce more dimensions that limit the queries. This started dashboard is just to get smaller setups started. 

Do you have any concrete idea on what Grafana can do better in terms of error handling or performance?

**Comment by torkelo** [comment]
Closing due to lack of updates. 

Please do not be discouraged, we can re-open if we get more information.
