### ISSUE TITLE
Problem with CSV export from Table panel when I try used field(value) mean

### ISSUE THREAD

**Issue by trybol** [grafana/grafana#27261]
**What happened**: 
I have problem in 7.1.3 is with exports csv files.
It does not export all the rows…

When I used:
![image](https://user-images.githubusercontent.com/25016502/91542620-6ae67400-e91e-11ea-91a3-8f35557174bd.png)

everything looks ok and I can export all rows from query.

But when I'm trying add for example mean, max or stddev:
![image](https://user-images.githubusercontent.com/25016502/91542996-a1bc8a00-e91e-11ea-8a5c-ee1be734b10f.png)

I see only one row:
![image](https://user-images.githubusercontent.com/25016502/91543238-b0a33c80-e91e-11ea-8cb8-14cbe29a2940.png)

**What you expected to happen**:
I need export all results from query to csv file.

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: InfluxDb 1.8.2
- OS Grafana is installed on: CentOS Linux release 7.8.2003
- User OS & Browser: Chrome
- Grafana plugins: - 
- Others: -

**Comment by torkelo** [comment]
Can you show the raw query result from query inspector? 

Can you add this to https://github.com/grafana/grafana/issues/26460
