### ISSUE TITLE
Disable raintank snapshot

### ISSUE THREAD

**Issue by martbhell** [grafana/grafana#2727]
It would be nice to be able to disable the possibility to make raintank snapshots, less confusion for users of a grafana  instance that runs on a server that does not have Internet access.

**Comment by jbergler** [comment]
+1

**Comment by drawks** [comment]
Yeah, there can be some serious data disclosure concerns here. Currently blackholing raintank is the only way to "disable" this and that leads to confusing errors for users.

**Comment by The-Nik** [comment]
+1 Yes for using Grafana in a company, you need to be able to disable this function and hide the button.

**Comment by AlexAkulov** [comment]
+1

**Comment by rlueckl** [comment]
+1
