### ISSUE TITLE
data does not change with the mouse

### ISSUE THREAD

**Issue by lightClouds917** [grafana/grafana#27277]
**What happened**:
When the mouse moves, data does not change with the mouse
**What you expected to happen**:
When the mouse moves, the data moves with the mouse
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/33415199/91631841-57ff9c80-ea0f-11ea-8984-5fdfaff782a0.png)
![image](https://user-images.githubusercontent.com/33415199/91631857-6cdc3000-ea0f-11ea-8ba0-4308082a1b73.png)
![image](https://user-images.githubusercontent.com/33415199/91631870-80879680-ea0f-11ea-8f65-fdbbb2aeef91.png)
![image](https://user-images.githubusercontent.com/33415199/91631906-c5abc880-ea0f-11ea-8f80-082f51873ef6.png)
 
I do not know what is mean about 23:00:00,why it appear in every point. And when mouse romove,it will not change.

I am a new user,and i do not find any description about it ,  thank you for your answer

**Environment**:
- Grafana version: Grafana v7.1.5 (9893b8c53d)
- Data source type & version: PostgreSQL 9.6.10 on x86_64-redhat-linux-gnu
- OS Grafana is installed on:
- User OS & Browser: chrom
- Grafana plugins: postgresql
- Others:

**Comment by lightClouds917** [comment]
And i want to know what is mean about this ,and how to fix it :
![image](https://user-images.githubusercontent.com/33415199/91632117-399aa080-ea11-11ea-8c2b-f1ca599d0cbe.png)

**Comment by torkelo** [comment]
could be caused by not all series having the same number of data points, or not sorted in same order. 

We are working on Graph panel and hope to improve the hover tooltips in the new coming visualizations
https://github.com/grafana/grafana/issues/6946.

**Comment by striver619** [comment]
use grafana.aarch64 0:7.1.5-1, no problem
