### ISSUE TITLE
Explore does not Graph wide time series data

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#27275]
**What would you like to be added**:
Explore to graph [wide time series dataframes](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/#wide-format). The table panel will Graph a "wide" dataframe, for example with a Frame structure like:

```json
[
  {
    "length": 2,
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {}
      },
      {
        "name": "",
        "type": "number",
        "config": {},
        "labels": {
          "host": "a"
        }
      },
      {
        "name": "",
        "type": "number",
        "config": {},
        "labels": {
          "host": "b"
        }
      }
    ]
  }
]
```

We only see the table:

![image](https://user-images.githubusercontent.com/1692624/91601506-c83aef00-e937-11ea-895c-3c6fee419e32.png)

However, the Graph panel will display it:

![image](https://user-images.githubusercontent.com/1692624/91601548-d8eb6500-e937-11ea-8745-d7113aaafb7b.png)

**Why is this needed**:
Azure datasource, and in the future SQL will return time series in a single frame like this.

**Reference**:

Docs Reference: https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/#wide-format

Base64 Frame used in the example with the gdev data source:

```
QVJST1cxAAD/////GAIAABAAAAAAAAoADgAMAAsABAAKAAAAFAAAAAAAAAEDAAoADAAAAAgABAAKAAAACAAAAFAAAAACAAAAKAAAAAQAAAB4/v//CAAAAAwAAAAAAAAAAAAAAAUAAAByZWZJZAAAAJj+//8IAAAADAAAAAAAAAAAAAAABAAAAG5hbWUAAAAAAwAAACQBAACMAAAABAAAAPr+//8UAAAAaAAAAGgAAAAAAAADaAAAAAIAAAAoAAAABAAAAOz+//8IAAAADAAAAAAAAAAAAAAABAAAAG5hbWUAAAAADP///wgAAAAYAAAADAAAAHsiaG9zdCI6ImIifQAAAAAGAAAAbGFiZWxzAAAAAAAACv///wAAAgAAAAAAAAAAAH7///8UAAAAaAAAAGgAAAAAAAADaAAAAAIAAAAoAAAABAAAAHD///8IAAAADAAAAAAAAAAAAAAABAAAAG5hbWUAAAAAkP///wgAAAAYAAAADAAAAHsiaG9zdCI6ImEifQAAAAAGAAAAbGFiZWxzAAAAAAAAjv///wAAAgAAAAAAAAASABgAFAAAABMADAAAAAgABAASAAAAFAAAAEQAAABMAAAAAAAACkwAAAABAAAADAAAAAgADAAIAAQACAAAAAgAAAAQAAAABAAAAFRpbWUAAAAABAAAAG5hbWUAAAAAAAAAAAAABgAIAAYABgAAAAAAAwAEAAAAVGltZQAAAAAAAAAA/////+gAAAAUAAAAAAAAAAwAFgAUABMADAAEAAwAAAAwAAAAAAAAABQAAAAAAAADAwAKABgADAAIAAQACgAAABQAAAB4AAAAAgAAAAAAAAAAAAAABgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAEAAAAAAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAQAAAAAAAAAAAAAAADAAAAAgAAAAAAAAAAAAAAAAAAAAIAAAAAAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAkRNqJoqALxYYbbEemIAvFgAAAAAAAPA/AAAAAAAAAEAAAAAAAAAIQAAAAAAAABBAEAAAAAwAFAASAAwACAAEAAwAAAAQAAAALAAAADgAAAAAAAMAAQAAACgCAAAAAAAA8AAAAAAAAAAwAAAAAAAAAAAAAAAAAAAAAAAKAAwAAAAIAAQACgAAAAgAAABQAAAAAgAAACgAAAAEAAAAeP7//wgAAAAMAAAAAAAAAAAAAAAFAAAAcmVmSWQAAACY/v//CAAAAAwAAAAAAAAAAAAAAAQAAABuYW1lAAAAAAMAAAAkAQAAjAAAAAQAAAD6/v//FAAAAGgAAABoAAAAAAAAA2gAAAACAAAAKAAAAAQAAADs/v//CAAAAAwAAAAAAAAAAAAAAAQAAABuYW1lAAAAAAz///8IAAAAGAAAAAwAAAB7Imhvc3QiOiJiIn0AAAAABgAAAGxhYmVscwAAAAAAAAr///8AAAIAAAAAAAAAAAB+////FAAAAGgAAABoAAAAAAAAA2gAAAACAAAAKAAAAAQAAABw////CAAAAAwAAAAAAAAAAAAAAAQAAABuYW1lAAAAAJD///8IAAAAGAAAAAwAAAB7Imhvc3QiOiJhIn0AAAAABgAAAGxhYmVscwAAAAAAAI7///8AAAIAAAAAAAAAEgAYABQAAAATAAwAAAAIAAQAEgAAABQAAABEAAAATAAAAAAAAApMAAAAAQAAAAwAAAAIAAwACAAEAAgAAAAIAAAAEAAAAAQAAABUaW1lAAAAAAQAAABuYW1lAAAAAAAAAAAAAAYACAAGAAYAAAAAAAMABAAAAFRpbWUAAAAAQAIAAEFSUk9XMQ==
```

Go snippet to make a frame an encoded Frame like that (in case the time being far in the past is annoying):

```go
package main

import (
	"encoding/base64"
	"fmt"
	"log"
	"time"

	"github.com/grafana/grafana-plugin-sdk-go/data"
)

func main() {
	frame := data.NewFrame("",
		data.NewField("Time", nil, []time.Time{time.Now().UTC().Add(-time.Minute), time.Now().UTC()}),
		data.NewField("", data.Labels{"host": "a"}, []float64{1, 2}),
		data.NewField("", data.Labels{"host": "b"}, []float64{3, 4}),
	)
	b, err := frame.MarshalArrow()
	if err != nil {
		log.Fatalf("failed to encode frame: %v", err)
	}
	sEnc := base64.StdEncoding.EncodeToString(b)
	fmt.Println(sEnc)
}
```

**Comment by aocenas** [comment]
@kylebrandt is this something that already breaks some data sources or is this just something we should be supporting in the future, if so is there some time frame for it?

**Comment by kylebrandt** [comment]
> @kylebrandt is this something that already breaks some data sources or is this just something we should be supporting in the future, if so is there some time frame for it?

This is currently used with the the Azure data source. So with 7.1.x, there are response using the Azure core data source that will render in the graph panel but not Explore. That being said, I am unsure if / how well those Azure services were supported in Explore before - so I can't really say if this is breaking in the sense that it has been a regression.

**Comment by kylebrandt** [comment]
Works for me with the fix, thanks @aocenas 

![image](https://user-images.githubusercontent.com/1692624/96877187-55d22100-1447-11eb-89b7-282ef9f62c44.png)
