### ISSUE TITLE
AWS Cloudwatch Datasource should be able to use the instance/container role attached, without AssumeRole

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#27279]
**What would you like to be added**:
Allow the Cloudwatch DataSource to retrieve credentials from the AWS instance profile (as part of the Instance or ECS task role) that is attached. This eliminates the need to AssumeRole when running Grafana directly inside AWS within the same account.

**Why is this needed**:
The current implementation offers 3 ways to get AWS credentials. Two of them involve the use of actual credentials which isn't secure for production use. The last method is an AssumeRole method, but this requires additional policies and roles just to read Cloudwatch metrics even if you're in the same account. if the role/policies attached to the instance/container-task have the necessary IAM actions allowed, Grafana's AWS SDK should be able to use those permissions directly w/o the need to use AssumeRole.

**Comment by papagian** [comment]
This is already supported by having an IAM role attached to the instance and selecting [`Credentials file`](https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#aws-credentials) as authentication provider    (and not having set neither environment variables nor credentials file)
@zswanson Can you verify that this works for your case?

**Comment by zswanson** [comment]
@papagian Ok I see the issue. I had tried that previously but had assumed I could leave it all blank - that gave me a 500 err. Now realize that it *requires* setting the default region, which was not clear. And the documentation only mentions this option in the context of an actual credentials file.
