### ISSUE TITLE
`make run` command throwing error

### ISSUE THREAD

**Issue by manashegde** [grafana/grafana#27278]
I followed the instructions mentioned here https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md and installed all the necessary requirements.

Once i run 'make run' command i see below error

````
[Bra] 08-29 22:52:10 [DEBUG] Running: go [run build.go -dev build-server]
Version: 7.2.0-pre, Linux Version: 7.2.0, Package Iteration: 1598721732pre
go build -ldflags -w -X main.version=7.2.0-pre -X main.commit=1a69bcfeff -X main.buildstamp=1598648602 -X main.buildBranch=master -o ./bin/grafana-server.
exe ./pkg/cmd/grafana-server
# github.com/grafana/grafana/pkg/cmd/grafana-server
c:\go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
C:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: error: export ordinal too large: 87294
collect2.exe: error: ld returned 1 exit status

exit status 2
exit status 1
[Bra] 08-29 22:52:28 [ WARN] Fail to execute command: go [run build.go -dev build-server] - exit status 1
make: *** [Makefile:54: run] Interrupt
````

Environment:
Windows 10 Professional
available disk space on C drive 23GB (could that be an issue?)

**Comment by hugohaggmark** [comment]
Hi @manashegde, we use GitHub for issues and feature requests. For these types of questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
