### ISSUE TITLE
Now delay now- not recognizing the s (seconds) time unit

### ISSUE THREAD

**Issue by nsaven** [grafana/grafana#27282]
**What happened**:
After upgrading from 7.1.3 to 7.1.5, the dashboard time setting (Now delay now-) no longer recognizes the s (second) time unit.

**What you expected to happen**:
Dashboard should reflect the time delay when using the s (second) time unit.

**How to reproduce it (as minimally and precisely as possible)**:
Set a time delay of 30s as show below.
![image](https://user-images.githubusercontent.com/58316227/91649105-1e7c6f00-eaab-11ea-88c0-d51d5415a8a7.png)

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Elasticsearch 7.8.1
- OS Grafana is installed on: RHEL8
- User OS & Browser: Windows10, Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
Unable to replicate 
![Screenshot from 2020-08-30 06-56-06](https://user-images.githubusercontent.com/10999/91651511-e7e42b80-ea8d-11ea-882b-de386ef12405.png)

**Comment by torkelo** [comment]
you have to change the time range after setting the now delay
