### ISSUE TITLE
Allow self-signed certificate for auth.proxy

### ISSUE THREAD

**Issue by alexandrsemak** [grafana/grafana#27286]
**What would you like to be added**:

Allow self-signde certificate for auth.proxy.
Grafana auth.proxy reject self-signde certificate:

```
x509: certificate signed by unknown authority
ErrorPage 500 Internal Error Internal Error
```

I understood that certificate bundle under `/etc/pki/ca-trust/extracted/pem/` resolving issue but what about just Allow self-signde certificate ?

**Comment by hugohaggmark** [comment]
Hi @alexandrsemak, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best

**Comment by alexandrsemak** [comment]
Hello @hugohaggmark so add feature:

```
tlsConfig:
  insecureSkipVerify:
```

I thought it is right place

**Comment by hugohaggmark** [comment]
Thanks @alexandrsemak it would be nice if you could explain more about this feature request and what your intended use-case is. The more details the better and we can always reopen this issue if there is a lot more feedback from the community.
