### ISSUE TITLE
Grafana Oauth integration redirection issue

### ISSUE THREAD

**Issue by VeenaThimmegowda** [grafana/grafana#27288]
**What happened**: Installed Grafana 7.1.3 version with keycloak/generic_oauth configuration. After keycloak authentication 504 Gateway Timeout page was loaded  instead of redirecting to grafana Home dashboard page.

**What you expected to happen**: After keycloak authentication it should redirect to grafana Home dashboard page

**How to reproduce it (as minimally and precisely as possible)**:
1. install Grafana 7.1.3 as container using helm
2. Configure auth.generic_oauth and ingress configuration
grafana.ini configuration
_[server]
    protocol =  https
    root_url = "https://grafana.test.com/graf"
[auth]
    ;signout_redirect_url = https://<keycloak_url>/auth/realms/<realm_name>/protocol/openid-connect/logout?redirect_uri=https://grafana.test.com/graf
    disable_login_form = false
    disable_signout_menu = false
[auth.generic_oauth]
    ;role_attribute_path = 
    allow_sign_up = true
    api_url = https://<keycloak_url>/auth/realms/<realm_name>/protocol/openid-connect/userinfo
    auth_url = https://<keycloak_url>/auth/realms/<realm_name>/protocol/openid-connect/auth
    client_id = grafana
    client_secret = xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
    enabled = true
    introspect_url = https://<keycloak_url>/auth/realms/<realm_name>/protocol/openid-connect/token/introspect
    name = <realm_name>
    scopes = openid
    tls_client_ca = /etc/grafana/keycloak/keycloak.crt
    tls_skip_verify_insecure = true
    token_url = https://<keycloak_url>/auth/realms/<realm_name>/protocol/openid-connect/token_

3. In the browser, try to login to grafana via oauth

![image](https://user-images.githubusercontent.com/38758323/91668960-9e97e880-eb2e-11ea-9bce-2b489be0312b.png)

![image](https://user-images.githubusercontent.com/38758323/91668979-cbe49680-eb2e-11ea-8f43-1989ab59dc70.png)

![image](https://user-images.githubusercontent.com/38758323/91668989-e880ce80-eb2e-11ea-9e4a-24d228fc53ae.png)

**Anything else we need to know?**: Grafana and Nginx ingress controller logs.
**Grafana logs:**
_t=2020-08-30T20:13:11+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2020-08-30T20:13:19+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=302 remote_addr=xx.xx.xx.xx time_ms=0 size=311 referer=https://grafana.test.com/graf/login
t=2020-08-30T20:13:21+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2020-08-30T20:13:26+0000 lvl=info msg="state check" logger=oauth queryState=010f864aa7057c5e4da33ff65e0464a330875e3f06a94397e29ec91c62d8066b cookieState=010f864aa7057c5e4da33ff65e0464a330875e3f06a94397e29ec91c62d8066b
t=2020-08-30T20:13:31+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2020-08-30T20:13:41+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0_

**Nginx ingress controller  logs:**
_{"type":"log","level":"INFO","facility":"23","time":"2020-08-30T20:13:19+00:00","timezone":"Etc/UTC","process":"nginx","system":"CITM Ingress Controller","systemid":"ing-citm-ingress-controller-sbcxl","host":"btll136-vmbedg-01","log":{"message":"[xx.xx.xx.xx] - - [GET /auth/realms/cpro/protocol/openid-connect/auth?access_type=online&client_id=grafana&redirect_uri=https%3A%2F%2Fgrafana.test.com%2Fgraf%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid&state=YgsyYts-O-lkFBhrmwZOf1CfZd0DEn2Xf4eiX9SSO24%3D HTTP/2.0] 200 1180 [https://grafana.test.com/] [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0] 1505 0.013 [sticky-veet-ckey-ckey-8443] xx.xx.xx.xx:8443 3190 0.014 200"}}
{"type":"log","level":"INFO","facility":"23","time":"2020-08-30T20:13:26+00:00","timezone":"Etc/UTC","process":"nginx","system":"CITM Ingress Controller","systemid":"ing-citm-ingress-controller-sbcxl","host":"btll136-vmbedg-01","log":{"message":"[xx.xx.xx.xx] - - [POST /auth/realms/cpro/login-actions/authenticate?session_code=fvfr3YBQlNh6cCNQuc-rewtSxHtbQ1BD2PPL3UC4PZY&execution=5b5e6446-4281-4701-9a47-67ec5678a421&client_id=grafana&tab_id=vHU49wbtsUs HTTP/2.0] 302 0 [https://keycloak.test.com/auth/realms/cpro/protocol/openid-connect/auth?access_type=online&client_id=grafana&redirect_uri=https%3A%2F%2Fgrafana.test.com%2Fgraf%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid&state=YgsyYts-O-lkFBhrmwZOf1CfZd0DEn2Xf4eiX9SSO24%3D] [Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:80.0) Gecko/20100101 Firefox/80.0] 1201 0.106 [sticky-veet-ckey-ckey-8443] xx.xx.xx.xx:8443 0 0.106 302"}}
{"type":"log","level":"ERROR","facility":"23","time":"2020-08-30T20:14:26+00:00","timezone":"Etc/UTC","process":"nginx","system":"CITM nginx","systemid":"ing-citm-ingress-controller-sbcxl","host":"btll136-vmbedg-01","log":{"message":"91#91: *3 upstream timed out (110: Connection timed out) while reading response header from upstream, client: xx.xx.xx.xx, server: grafana.test.com, request: 'GET /graf/login/generic_oauth?state=YgsyYts-O-lkFBhrmwZOf1CfZd0DEn2Xf4eiX9SSO24%3D&session_state=b1541182-005c-4d20-80bc-cd8628750aa5&code=48679dfd-d1f5-4864-bc27-2e313a225351.b1541182-005c-4d20-80bc-cd8628750aa5.26ffd520-8cd9-44d0-86b6-06bad331774c HTTP/2.0', upstream: 'https://xx.xx.xx.xx:3000/login/generic_oauth?state=YgsyYts-O-lkFBhrmwZOf1CfZd0DEn2Xf4eiX9SSO24%3D&session_state=b1541182-005c-4d20-80bc-cd8628750aa5&code=48679dfd-d1f5-4864-bc27-2e313a225351.b1541182-005c-4d20-80bc-cd8628750aa5.26ffd520-8cd9-44d0-86b6-06bad331774c', host: 'grafana.test.com', referrer: 'https://keycloak.test.com/'"}}_

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: n/a
- OS Grafana is installed on:  CentOS Linux 7
- User OS & Browser: chrome,Mozilla and microsoft edge
- Grafana plugins: n/a
- Others: n/a

**Comment by marefr** [comment]
How are you proxy from nginx to Grafana. Using http://localhost:3000/? I think you want to change protocol to http in Grafana configuration settings and proxy using http://localhost:3000 in case you want to offload ssl to nginx. Let me know if that works. Closing this for now since it looks like a configuration error.

**Comment by ahmedTouati** [comment]
> How are you proxy from nginx to Grafana. Using http://localhost:3000/? I think you want to change protocol to http in Grafana configuration settings and proxy using http://localhost:3000 in case you want to offload ssl to nginx. Let me know if that works. Closing this for now since it looks like a configuration error.

Can you please put more details because I faced the same issue

**Comment by neerajjain92** [comment]
@VeenaThimmegowda How did you fix this?
@ahmedTouati  Did you get any solution for this ?

**Comment by neerajjain92** [comment]
@marefr Can you please re-open this issue, I am also facing the same issue
