### ISSUE TITLE
Date Format 'YYYY-MM-DD' to be added as part of Units in field configuration

### ISSUE THREAD

**Issue by suraj-james** [grafana/grafana#27296]
**What would you like to be added**:

We would like to have an extra option of Date Format as only 'YYYY-MM-DD' as part of units without the time. 

As of now only the below formats are supported with having a combination of date and time. 
![image](https://user-images.githubusercontent.com/59333642/91716751-ddb94e80-ebad-11ea-9292-d0aff8459c08.png)

However, this option was available in the older version of Grafana:
![image](https://user-images.githubusercontent.com/59333642/91719835-9fbf2900-ebb3-11ea-95a8-54556ba89830.png)

Also, can we have a possibility to set the date format in a custom way ex. DD-MM-YYYY, MM-DD-YY, etc. 

**Why is this needed**:

We have data as milestones that do not pertain to any time value but are solely made using days. 
The time value is also recorded along with the date and stored in the DB, but we do not want to display the time.

**Environment**:
Grafana version:v7.1.5 hosted on SUSE sp4
Data source type & version: Postgres V10
OS Grafana is installed on:
User OS & Browser: Windows 10 & Chrome
Grafana plugins: Table Plugin

**Comment by hugohaggmark** [comment]
Is this at all related to the work you're doing right now with date formats @torkelo?

**Comment by therealcodlord** [comment]
@suraj-james have you tried entering a custom date format with the `time:` prefix, so like this:

`time: YYYY-MM-DD`

You did not have to use this formatting in Grafana v6 but I think this is how it should be done now, see here:
https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#unit

**Comment by hugohaggmark** [comment]
Thank you @therealcodlord that is the correct solution here, I was looking for it yesterday but couldn't find it, thanks again. 

I'm going to close this for now @suraj-james but we could always reopen this feature request if it gets more upvotes.

**Comment by suraj-james** [comment]
@therealcodlord Thank you for the input, this will definitely help us (especially for the custom format mentioned above).

@hugohaggmark, we have more than 200 reports with many fields in them that use this filter ('YYYY-MM-DD'). It would be easy if we could have a this as an option (as in the older version), rather than conveying the custom format usage to all our 3000+ users.
What is the threshold are you looking forward in the upvotes?

**Comment by hugohaggmark** [comment]
@suraj-james not sure what that threshold would be, but there would have to be more demand for this specific format than this issue I guess.

We used to receive lots of PRs regarding adding custom units in Grafana and that took us some time reviewing for each new PR. So we decided that we would introduce custom units instead, so users could define units on the fly. So sorry that `YYYY-MM-DD` is not part of the out of the box units. 

You can open a PR that adds the 'YYYY-MM-DD' format and we could take it from there?

**Comment by therealcodlord** [comment]
Personally, I don't think Grafana should really be adding more custom formats as different countries/use cases will need all sorts of different formats but:

1) Why not allow users to define their own custom formats in Grafana settings which are then available throughout Grafana? Why do I need to enter my desired formats multiple times in different dashboards/panels?

2) When you pick a one of the pre-defined date formats from the dropdown it just appears as for example: `MM/DD/YYYY h:mm:ss a` so it would seem common-sense that I can input a different format in the box and have it work but that is not the case, I have to enter it with the prefix `time:`. And no tooltip or help or anything to tell people this is how it should be or even that it's possible to enter custom formats. Why is the user interface not consistent? Pre-defined formats are shown one way but custom formats must be entered differently. It just does not seem user-friendly to me.

**Comment by hugohaggmark** [comment]
@therealcodlord thank you for that great feedback, that would merit its own feature request issue I think.
