### ISSUE TITLE
Time variable not updating in the dashboard external link

### ISSUE THREAD

**Issue by dattaSagar** [grafana/grafana#27294]
Created a Grafana dashboard. Added a dashboard external link. To the link added time variables from:'${__from:date}',to:'${__to:date}' to fetch time values to pass through the URL to open another external dashboard.
On clicking the link from the dashboard it successfully open the external link and link had proper time values as per time picker selection. 

Now we changed the value in timepicker and clicked on the link again. 
Expectation: New time values should have been passed in the URL while opening then external link from grafana, instead its passing the old selected value.

Workaround: After changing the value in datepicker, the Grafana tab needs to refreshed and then if we click on the external link it sends the correct value in the fields.  

Steps:

1. [Tab 1]: Open Grafana, Go to Dashboard https://play.grafana.org/d/rUpVRdamz/dashboard-links-with-variables?orgId=1&from=now-15m&to=now
2. Check the time picker is set to "Last 15 minutes". Click on "Grafana Dashboard" Following URL generates and opens in [Tab 2]
"https://play.grafana.org/d/3SWXxreWk/grafana-dashboard?from=now-15m&to=now&var-app=backend&var-server=backend_01&var-server=backend_03&var-interval=1h"
3. Go back to [Tab 1] and change time picker "Last 1 hour" and click on  "Grafana Dashboard" Following URL generates and opens in [Tab 3] "https://play.grafana.org/d/3SWXxreWk/grafana-dashboard?orgId=1&from=now-15m&to=now&var-app=backend&var-server=backend_01&var-server=backend_03&var-interval=1h"

*NOTE: both the links the time interval is same even after time picker is changed.

4. This is workaround or can be said the expected result/url: Refresh the [Tab 1] and click "Grafana Dashboard" this time the following URL is generated which is expected and correct. https://play.grafana.org/d/3SWXxreWk/grafana-dashboard?orgId=1&from=now-1h&to=now&var-app=backend&var-server=backend_01&var-server=backend_03&var-interval=1h

![Grafana](https://user-images.githubusercontent.com/40453184/91713632-c1b2ae80-eba7-11ea-8135-e15db2d52d64.gif)

- Grafana version:7.1.5

**Comment by hugohaggmark** [comment]
Thank you @dattaSagar for reporting this issue, I've added it to our bugs backlog to be solved

**Comment by hugohaggmark** [comment]
Closing this issue for now because I suspect it was fixed by #27926 in Grafana 7.2.1. If you can confirm this @dattaSagar it would be awesome.

All the best

**Comment by ivog** [comment]
@hugohaggmark  Can this issue be reopened? On grafana 8.1.0 this still seems to be an issue
