### ISSUE TITLE
Issues renewing IAM credentials for alerts on CloudWatch data source (tsdb.HandleRequest, NoCredentialProviders)

### ISSUE THREAD

**Issue by matschaffer** [grafana/grafana#27293]
**What happened**:

Since upgrading to Grafana v7.2.0-3f6b253fpre (c5cd9c5648) we've been getting some spurious error alerts regarding issues with our CloudWatch data source.

**What you expected to happen**:

I'd expect Grafana to have a retry loop to get new credentials if the previous IAM have expired (or are close to expring)

**How to reproduce it (as minimally and precisely as possible)**:

Not exactly sure, but probably any cloudwatch alert will hit this eventually.

**Anything else we need to know?**:

You should be able to see the alert history at https://grafana.safecast.cc/d/W7c552kZz/api-overview?orgId=1&editPanel=14&tab=alert&refresh=5m

Example alerts in slack

<img width="771" alt="Screen Shot 2020-08-31 at 18 05 53" src="https://user-images.githubusercontent.com/690/91703395-11e43d80-ebb5-11ea-86d3-ca6b084a8414.png">

**Environment**:
- Grafana version: Grafana v7.2.0-3f6b253fpre (c5cd9c5648)
- Data source type & version: CloudWatch
- OS Grafana is installed on: Amazon Linux
- User OS & Browser: Alerting

**Comment by marefr** [comment]
Please include what type of authentication you're using and/or data source configuration (please replace any sensitive information).

**Comment by matschaffer** [comment]
![Screen Shot 2020-09-01 at 9 25 23](https://user-images.githubusercontent.com/690/91781361-194b2b80-ec35-11ea-930c-7403519d0253.png)

It's running on EC2, no `~/.aws/credentials` so I assume it's using the metadata endpoint.

This config has been the same for well over a year now. I think we first noticed this sort of error around August 19th.

Checking with @robouden who should be able to confirm the timing of our last upgrade.

**Comment by marefr** [comment]
Maybe related/will be fixed by #25548. Suggest we return to this when that have been merged to master.

**Comment by sunker** [comment]
@matschaffer do you still have the same problem?

**Comment by matschaffer** [comment]
Looks like the last time we saw it was Sept 17th. We run grafana on master, go guessing the PR did the trick.

Thanks!

**Comment by sunker** [comment]
Great! Thanks @matschaffer
