### ISSUE TITLE
Add an API to import/export dashboards

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#273]
Unless I'm mistaken there is no programatic way to _easily_  export/import user generated dashboards. Such API would be useful to pair with tooling (e.g. config management) so user generated dashboard are automatically managed.

**Comment by torkelo** [comment]
implemented in Grafana 2.0

**Comment by fengjuZhang** [comment]
Automatic Http API import

**Comment by fengjuZhang** [comment]
There is no Http API import, I need to automatically generate the instrument panel by Http

**Comment by torkelo** [comment]
Here is a http api to create / update dashboarda

**Comment by fengjuZhang** [comment]
where

**Comment by fengjuZhang** [comment]
If I have a JSON I can directly generate the dashboard through the HTTP request.

**Comment by torkelo** [comment]
check the http api docs :)

**Comment by torkelo** [comment]
docs.grafana.org

**Comment by fengjuZhang** [comment]
thanks

**Comment by LuboVarga** [comment]
I have running grafana installed from rpm (latest version, 3.1.0), but it seems it is ignoring config file /etc/grafana/grafana.ini. I have modified it to enable json dashboards like this:
```
[dashboards.json]
;enabled = true
;path = /usr/share/grafana/public/dashboards
```
Given directory contains some json and js files. Accessing generated (*.js) dashboards is working and simple (also without moddification of settings file). I just open http://localhost:3000/dashboard/script/dashboardgenerator.js?environment=test8 and it is working. But when I want to provision dashoard to be visible in menu of grafana (in upper left menu with list of dashboards), I do not know, where should I put my dashboards. I need to make possible to search through available dashboards and not only to guess what parameter should be passed to my javascript.

Is it possible to somehow import dashboard and make it visible in dashboard list? (and by import I mean some programmatic way, not by playing in grafana web interface and importing things by hand)

**Comment by Djidiouf** [comment]
Hi LuboVarga, I just used 
```
#################################### Dashboard JSON files ##########################
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards
```

And as soon as I put a json dashboard in that folder, it appears on the dashboard list in Grafana. Perhaps try to have only .json in it and see what happens.

**Comment by LuboVarga** [comment]
Thanks @Djidiouf, it is working now. I am not sure, if I had wrong path (now it was wrong), or I have tried other than json suffixes.

Just for the record, I have solved provisioning of dashboards from saltstack through provisioning json/request files, curl and by using [http api](http://docs.grafana.org/http_api/dashboard/):
```
curl -X POST -d @/usr/share/grafana/public/dashboards/projection.json.dashboard.request 'http://localhost:3000/api/dashboards/db' --header 'Content-Type: application/json' --header 'Authorization: Bearer eyJrIjo_THIS_IS_API_KEY_joxfQ==' -sw 'STATUSCODE=%{http_code}' | grep 'STATUSCODE=200'
```
Dashboards get saved into `/var/lib/grafana/grafana.db` file (where are also other things, like api keys or data sources configured).

**Comment by mojili** [comment]
I solved the problem like this:
1- first create your datasource like this (In my case I used the combination of collectd, prometheus and grafana)

curl --user admin:admin 'http://IPADDR:3000/api/datasources' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"name":"test","type":"prometheus","url":"http://localhost:9090","access":"proxy","basicAuth":false}'

2-For adding the customized json dashboard, edit grafana.ini file and enable Dashboard json file section like below:
;#################################### Dashboard JSON files ##########################
[dashboards.json]
enabled = true
path = /var/lib/grafana/dashboards

3- then copy dashboard json file to /var/lib/grafana/dashboards (you need to restart the service)
