### ISSUE TITLE
Support new CloudWatch metrics for Amazon ElastiCache for Redis

### ISSUE THREAD

**Issue by longjun2013** [grafana/grafana#27304]
**What would you like to be added**:
 
AWS announced [new CloudWatch metrics for Amazon ElastiCache for Redis](https://aws.amazon.com/about-aws/whats-new/2020/06/announcing-new-cloudwatch-metrics-elasticache-redis/) on Jun 10, 2020. 

Some of the new key metrics include used memory as percentage of the available cache node memory, cache hit ratio, memory fragmentation ratio, Redis commands latencies and aggregated latencies per data structure.

**Why is this needed**:

So far grafana doesn't support these new metrics based on [this code](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L76).

Do we have a plan to support it in the near future? Thank you.

**Comment by marefr** [comment]
As a workaround you should be able to manually input metrics and dimensions. We'll need help from the community to implement this.
