### ISSUE TITLE
Panel Settings / Series Override: Add button to duplicate override entry

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#27305]
**What would you like to be added**:

Button to duplicate a "series override" entry similar to how queries can be duplicated.

**Why is this needed**:

Sometimes I am overriding multiple series with almost the same attribute values. Currently I have to set all the attributes manually or copy and paste the entry in the JSON view. It currently looks like this:

![image](https://user-images.githubusercontent.com/24834206/91760190-33ecb880-ebd3-11ea-8aa1-fcc7765f059f.png)

A button that duplicates the entry would be helpful:

![image](https://user-images.githubusercontent.com/24834206/91760318-70201900-ebd3-11ea-82f5-55fb36ab5240.png)

**Comment by hugohaggmark** [comment]
Thanks @trallnag for reporting this request, I think it's a brilliant suggestion. Added it to our backlog!

**Comment by bob454522** [comment]
I wanted to be sure that this Feature Req didnt get lost in the shuffle, accidently -
Above it shows that:
 @hugohaggmark moved this from Needs triage to Feature requests in Platform Backlog on Sep 1, 2020

However i went through every "Projects" subsection and could not find this FR mentioned anywhere.
(and the "Platform Backlog" section is now blank / closed, so it is not in there).  I also searched through all of the recent release notes, and did not find this FR as Added.
So im not sure if it got lost, or was deleted intentionally.  (or that im not properly searching for it, in github)-  i care as i feel this is a very useful PR.

(please forgive this post if this feature request was intentionally removed by the grafana team).

thanks,
LOVE GRAFANA!!!!!

**Comment by hugohaggmark** [comment]
@pkolyvas is this a feature request we should move to GitHub Discussions?

**Comment by torkelo** [comment]
We can close this one as it's for the old graph panel that we are no longer extending / adding features to
