### ISSUE TITLE
Error: ✗ plugin is not supported on your architecture and OS.

### ISSUE THREAD

**Issue by Bboy486** [grafana/grafana#27303]
**What happened**:
Cannot install grafana image renderer

**What you expected to happen**:
Install on Raspian on Raspberry pi

**How to reproduce it (as minimally and precisely as possible)**:
sudo grafana-cli plugins install grafana-image-renderer
Error: ✗ plugin is not supported on your architecture and OS.

**Anything else we need to know?**:

**Environment**: Linux
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: 
- OS Grafana is installed on Raspian
- User OS & Browser: N/A
- Grafana plugins: grafana image renderer
- Others:

**Comment by hugohaggmark** [comment]
@Bboy486 I know little about Raspberry pi and Raspian but reading the docs [https://grafana.com/grafana/plugins/grafana-image-renderer](https://grafana.com/grafana/plugins/grafana-image-renderer) it doesn't seem to be supported. Also, this memory requirement seems a bit over the top for a Raspberry pi [https://grafana.com/docs/grafana/latest/administration/image_rendering/#memory-requirements](https://grafana.com/docs/grafana/latest/administration/image_rendering/#memory-requirements)

I'm going to close this for now, but if this issue gets more upvotes, we can consider reopening it.

All the best

**Comment by Bboy486** [comment]
Bummer I was trying to use it with Pushover https://prnt.sc/u9qpt1
