### ISSUE TITLE
grunt build error with latest git version

### ISSUE THREAD

**Issue by StefanSa** [grafana/grafana#2730]
Hi,
i get with the latest git version this error with "grunt".

Running "tslint:source" (tslint) task
>> public/app/core/directives/array_join.ts[6, 1]: missing 'use strict'
>> public/app/core/directives/array_join.ts[18, 11]: missing whitespace
>> 2 errors in 6 files
Warning: Task "tslint:source" failed. Use --force to continue.

any help here ?

**Comment by fg2it** [comment]
@StefanSa already fixed. By the way, you can indeed use '--force' option to ignore that kind of error. If you are trying to build packages, running
```bash
sed -i 's/grunt("release")/grunt("--force","release")/' build.go
```
from your local working directory should do the trick.

**Comment by torkelo** [comment]
oh, yea, forgot to link to this issue in this commit https://github.com/grafana/grafana/commit/7535677ed44757ecfa160471f250ebe87140cc56
