### ISSUE TITLE
Explore with Loki: ability to display only certain columns/fields from log lines

### ISSUE THREAD

**Issue by judemorrissey** [grafana/grafana#27318]
**What would you like to be added**:
In summary, please add the ability to view only certain (parsed?) fields of Loki log lines in the Explore view.

**Why is this needed**:
We recently started moving all our logs from an ELK stack to use Grafana/Loki/Fluentd. As we start finalizing our pipeline and have started getting our logs into Loki for viewing in Grafana, we identified that being able to show only certain fields (e.g. only container id, server type, and log message) would really help the readability of our otherwise dense JSON log lines. This feature request is very similar to how Kibana's Discover.

Please refer to the clip below illustrating what Kibana's Discover view would look like with two arbitrary columns selected to be displayed (clipped from [this image](https://lagoon.readthedocs.io/en/latest/images/kibana_example2.png))
![image](https://user-images.githubusercontent.com/5974771/91887448-a72c1400-ec3f-11ea-9e3b-16b66f4fba97.png)

Potentially related to #22271, as some of the commenters have mentioned something similar to this issue, e.g. [this](https://github.com/grafana/grafana/issues/22271#issuecomment-590893570) and [this](https://github.com/grafana/grafana/issues/22271#issuecomment-598740586)

Thank you!

**Comment by aocenas** [comment]
There was a contribution to add similar functionality to explore https://github.com/grafana/grafana/pull/26178. Please check if that would solve your issue.

**Comment by judemorrissey** [comment]
@aocenas thank you so much for the reply! yes, #26718 looks to be exactly the thing we need, thanks so much for pointing this out, i will close this issue now, cheers!
