### ISSUE TITLE
serve_from_sub_path not reflected in google analytics reports

### ISSUE THREAD

**Issue by nicks** [grafana/grafana#27319]
**What happened**:

I currently serve grafana from a subpath. The config looks like this:

```
[server]
root_url = https://mydomain/grafana
serve_from_sub_path = true
[analytics]
google_analytics_ua_id = my-google-analytics-id
```

**What you expected to happen**:
I expect visits to the grafana pages to be reported to google analytics under the /grafana path, e.g., `/grafana/d/HSr2fnSGk/global-usage`

Instead, google analytics paths are reported as `/d/HSr2fnSGk/global-usage`

**How to reproduce it (as minimally and precisely as possible)**:

see above

**Anything else we need to know?**:

nope, thanks for building a great product! :hugs: 

**Environment**:
- Grafana version: 7.1.1

**Comment by hugohaggmark** [comment]
Hi @nicks, have you followed this https://support.google.com/analytics/answer/1012243?hl=en? Let me know if that doesn't work.

**Comment by nicks** [comment]
@hugohaggmark hmmmm...I'm not sure how that would work? We need to be able to distinguish visits to the main page ('/', which is served from a separate server) from visits to the main grafana page ('/grafana/', which is currently reported as '/')

**Comment by nicks** [comment]
fwiw, I'm pretty sure the bug is this line:
https://github.com/grafana/grafana/blob/master/public/app/core/services/analytics.ts#L30
which reports the root-relative URL, rather than the path of the absolute URL

**Comment by hugohaggmark** [comment]
@nicks have you tried my suggestion? It worked for me.

**Comment by hugohaggmark** [comment]
See this [https://github.com/grafana/grafana/issues/14091](https://github.com/grafana/grafana/issues/14091) and this [https://github.com/grafana/grafana/pull/14132](https://github.com/grafana/grafana/pull/14132)

**Comment by nicks** [comment]
@hugohaggmark Nope! that doesn't fix it. The issues you're pointing to are about subdomains, NOT subpaths, so I think you're misunderstanding what the problem is.

Let me try to explain it differently:
1) Server A is serving traffic at http://mydomain.com/, and reports GA visits as "/"
2) Grafana is serving traffic at http://mydomain.com/grafana/, and reports GA visits as "/" (this is incorrect, it should be reporting them as "/grafana/")

GA filters don't work here. In fact, no GA-side solution here will work, because GA simply have enough information to distinguish between cases (1) and (2). Does that make sense?

**Comment by hugohaggmark** [comment]
@nicks thank you for clarifying this, I can confirm this is a bug. This line should consider appSubUrl: https://github.com/grafana/grafana/blob/master/public/app/core/services/analytics.ts#L30
