### ISSUE TITLE
ERR_HTTP2_PROTOCOL_ERROR, ERR_CONNECTION_CLOSED in table view visualization

### ISSUE THREAD

**Issue by czomo** [grafana/grafana#27313]
**What happened**:
After upgrading Grafana to the newest version 7.1.5 I am receiving ERR_HTTP2_PROTOCOL_ERROR and ERR_CONNECTION_CLOSED on panels which are using table visualization.
Traceback from devtools:
`2.4141596c10e564d57dfb.js:1 Failed to load resource: net::ERR_HTTP2_PROTOCOL_ERROR
bootstrap:126 Uncaught (in promise) ChunkLoadError: Loading chunk 72 failed.
(error: https://grafana.de/public/build/72.4141596c10e564d57dfb.js)
    at Function.i.e (https://grafana.de/public/build/runtime.4141596c10e564d57dfb.js:1:2262)
    at https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:1561479
    at https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:1011001
    at e.fire (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:1133360)
    at e._getOrCreateMode (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:813590)
    at e._createModeAndGetLanguageIdentifier (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:813270)
    at t._selector (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:812884)
    at new t (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:811580)
    at e.create (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:812806)
    at Object.Mm [as createModel] (https://grafana.de/public/build/default~code-editor.4141596c10e564d57dfb.js:2:1004514)
codicon.a609dc0f.ttf:1 Failed to load resource: net::ERR_CONNECTION_CLOSED
/api/datasources/proxy/2/api/v1/query`

**What you expected to happen**:
Table which pvc prediction should appear.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install Grafana 7.1.5
2. Create dashboard using using table visualization with following query, use Prometheus as a source(I guess some pvc are nedded)
`predict_linear(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~"$persistentvolumeclaim", namespace=~"$namespace", instance=~"$instance"}[3h], 2 * 24 * 3600) / predict_linear(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~"$persistentvolumeclaim", namespace=~"$namespace", instance=~"$instance"}[3h], 2 * 24 * 3600)`

**Anything else we need to know?**:
I noticed similar behavior but this time on graph visualization but it only occurs on chrome.

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Prometheus
- OS Grafana is installed on: 
- User OS & Browser: Linux Firefox 78.0.2 (64-bit), Chrome Version 85.0.4183.83
- Grafana plugins: Loki
- Others: No changes to ingress

**Comment by hugohaggmark** [comment]
Thanks for reporting this @czomo, to simplify our investigation could you share your dashboard json? It seems you're using variables and we would like to look at those querys too.

![image](https://user-images.githubusercontent.com/562238/91962064-52a29a80-ed0c-11ea-8af8-ca98321fb185.png)

![image](https://user-images.githubusercontent.com/562238/91962090-5cc49900-ed0c-11ea-8772-49ee8a67b5f6.png)

Click on view JSON
![image](https://user-images.githubusercontent.com/562238/91962149-6f3ed280-ed0c-11ea-8859-734317eba780.png)

Click on Copy to Clipboard and paste it in this issue after you've removed any sensitive data. Thank you

**Comment by hugohaggmark** [comment]
I'm going to close this issue for now because we've not received any feedback to our initial questions. If reporter supplies more proof in this issue, we'll of course reopen it.

All the best

**Comment by czomo** [comment]
The problem seems to be solved since the last time I looked at it, but this is the dashboard I used.`{
  "__inputs": [
    {
      "name": "DS_PROMETHEUS",
      "label": "prometheus",
      "description": "",
      "type": "datasource",
      "pluginId": "prometheus",
      "pluginName": "Prometheus"
    }
  ],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "7.1.5"
    },
    {
      "type": "panel",
      "id": "graph",
      "name": "Graph",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "prometheus",
      "name": "Prometheus",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "table-old",
      "name": "Table (old)",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "${DS_PROMETHEUS}",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "description": "Kubernetes persistent volume inode and disk usage",
  "editable": true,
  "gnetId": 6739,
  "graphTooltip": 1,
  "id": null,
  "iteration": 1602060223169,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "${DS_PROMETHEUS}",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 16,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 5,
      "legend": {
        "alignAsTable": true,
        "avg": true,
        "current": true,
        "max": true,
        "min": true,
        "rightSide": true,
        "show": true,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "1 / kubelet_volume_stats_capacity_bytes * kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$persistentvolumeclaim\", namespace=~\"$namespace\", instance=~\"$instance\"}",
          "format": "time_series",
          "intervalFactor": 1,
          "legendFormat": "{{persistentvolumeclaim}} - {{namespace}}",
          "refId": "A"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Disk Usage",
      "tooltip": {
        "shared": true,
        "sort": 2,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "percentunit",
          "label": null,
          "logBase": 1,
          "max": "1",
          "min": "0",
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "columns": [],
      "datasource": "${DS_PROMETHEUS}",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fontSize": "100%",
      "gridPos": {
        "h": 14,
        "w": 24,
        "x": 0,
        "y": 16
      },
      "id": 8,
      "links": [],
      "pageSize": null,
      "repeat": null,
      "repeatDirection": "h",
      "scroll": true,
      "showHeader": true,
      "sort": {
        "col": 8,
        "desc": true
      },
      "styles": [
        {
          "alias": "Namespace",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "link": false,
          "mappingType": 1,
          "pattern": "namespace",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Persistent Volume Claim",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "persistentvolumeclaim",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Node",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "node",
          "thresholds": [],
          "type": "string",
          "unit": "short"
        },
        {
          "alias": "Is going to fill up in 48 hours time?",
          "align": "auto",
          "colorMode": "row",
          "colors": [
            "rgba(50, 172, 45, 0.97)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(245, 54, 54, 0.9)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "link": false,
          "mappingType": 2,
          "pattern": "Value",
          "rangeMaps": [],
          "thresholds": [
            "0.5",
            "0.99"
          ],
          "type": "string",
          "unit": "short",
          "valueMaps": []
        },
        {
          "alias": "",
          "align": "auto",
          "colorMode": null,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "dateFormat": "YYYY-MM-DD HH:mm:ss",
          "decimals": 2,
          "mappingType": 1,
          "pattern": "/.*/",
          "thresholds": [],
          "type": "hidden",
          "unit": "short"
        }
      ],
      "targets": [
        {
          "expr": "predict_linear(kubelet_volume_stats_used_bytes{persistentvolumeclaim=~\"$persistentvolumeclaim\", namespace=~\"$namespace\", instance=~\"$instance\"}[3h], 2 * 24 * 3600) / predict_linear(kubelet_volume_stats_capacity_bytes{persistentvolumeclaim=~\"$persistentvolumeclaim\", namespace=~\"$namespace\", instance=~\"$instance\"}[3h], 2 * 24 * 3600)",
          "format": "table",
          "instant": true,
          "intervalFactor": 1,
          "refId": "A"
        }
      ],
      "title": "Is going to fill up in 48 hours time?",
      "transform": "table",
      "type": "table-old"
    },
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "${DS_PROMETHEUS}",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 13,
        "w": 24,
        "x": 0,
        "y": 30
      },
      "hiddenSeries": false,
      "id": 6,
      "legend": {
        "alignAsTable": true,
        "avg": true,
        "current": true,
        "max": true,
        "min": true,
        "rightSide": true,
        "show": true,
        "sort": "current",
        "sortDesc": true,
        "total": false,
        "values": true
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "null",
      "percentage": false,
      "pluginVersion": "7.1.5",
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "expr": "1 / kubelet_volume_stats_inodes * kubelet_volume_stats_inodes_used{namespace=~\"$namespace\", persistentvolumeclaim=~\"$persistentvolumeclaim\", instance=~\"$instance\"}",
          "format": "time_series",
          "intervalFactor": 1,
          "legendFormat": "{{persistentvolumeclaim}}",
          "refId": "A"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Inode Usage",
      "tooltip": {
        "shared": true,
        "sort": 2,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "percentunit",
          "label": null,
          "logBase": 1,
          "max": "1",
          "min": "0",
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "refresh": "1m",
  "schemaVersion": 26,
  "style": "dark",
  "tags": [
    "kubernetes"
  ],
  "templating": {
    "list": [
      {
        "allValue": ".*",
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "definition": "",
        "hide": 0,
        "includeAll": true,
        "label": "Namespace",
        "multi": false,
        "name": "namespace",
        "options": [],
        "query": "label_values(kube_pod_info, namespace)",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": ".*",
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "definition": "",
        "hide": 0,
        "includeAll": true,
        "label": "Instance",
        "multi": false,
        "name": "instance",
        "options": [],
        "query": "label_values(kubelet_volume_stats_inodes, instance)",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": null,
        "current": {},
        "datasource": "${DS_PROMETHEUS}",
        "definition": "",
        "hide": 0,
        "includeAll": true,
        "label": "Persistent Volume Claim",
        "multi": false,
        "name": "persistentvolumeclaim",
        "options": [],
        "query": "label_values(kubelet_volume_stats_inodes{namespace=~\"$namespace\", instance=~\"$instance\"}, persistentvolumeclaim)",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 1,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "timezone": "browser",
  "title": "Kubernetes Persistence Volumes",
  "uid": "ChNm4Mvik",
  "version": 1
}`
