### ISSUE TITLE
grafana issue long queries to mysql

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#27339]
**What happened**:
After I upgrade grafana to 7.1.5, grafana began to issue queries to mysql that never seems to end. (our script that check for long queries killed them after awhile)
And those query were making mysql use all server CPU.

This is the query that was causing issue :
`SELECT role AS bitrole, active, COUNT(role) AS count FROM
    (SELECT active, SUM(role) AS role
     FROM (SELECT
               u.id,
               CASE org_user.role
                   WHEN 'Admin' THEN 4
                   WHEN 'Editor' THEN 2
                   ELSE 1
                   END AS role,
               u.last_seen_at>'2020-07-29 13:37:46.94542' AS active
           FROM `user` AS u LEFT JOIN org_user ON org_user.user_id = u.id
           GROUP BY u.id, u.last_seen_at, org_user.role) AS t2
     GROUP BY active, id) AS t1
GROUP BY active, role`

**How to reproduce it (as minimally and precisely as possible)**:
upgrade to 7.1.5

**Anything else we need to know?**:
For information, I have ~19 000 rows in 'user' and ~950 000 rows in 'org_user'.

**Environment**:
- Grafana version: 7.1.5
- OS Grafana is installed on: centos7
- database : mysql

**Comment by bergquist** [comment]
ping @sakjur

**Comment by marefr** [comment]
@deathwarrior60 for now quick workaround would be to downgrade to 7.1.4.. Another workaround should be to [Disable total stats](https://grafana.com/docs/grafana/latest/administration/configuration/#disable_total_stats) and possibly also [disable reporting of anonymous usage statistics](https://grafana.com/docs/grafana/latest/administration/configuration/#reporting_enabled). Please note thought that navigating to Server Admin/Stats will trigger the same problematic query (I think). Please try this out and let us know if this resolves your current problem.

**Comment by marefr** [comment]
@deathwarrior60 if you could connect to your MySQL instance and execute the following and report back the output would also be super helpful:
```sql
> explain extended SELECT role AS bitrole, active, COUNT(role) AS count FROM (SELECT active, SUM(role) AS role FROM (SELECT u.id, CASE org_user.role WHEN 'Admin' THEN 4 WHEN 'Editor' THEN 2 ELSE 1 END AS role, u.last_seen_at>'2020-07-29 13:37:46.94542' AS active FROM user AS u LEFT JOIN org_user ON org_user.user_id = u.id GROUP BY u.id, u.last_seen_at, org_user.role) AS t2 GROUP BY active, id) AS t1 GROUP BY active, role;
```

Thanks in advance

**Comment by deathwarrior60** [comment]
Hello, 
I tried to set 

[metrics]
disable_total_stats=false

[analytics]
reporting_enabled=false

But it doesn't solve the issue.

Here's the result of the explain :
<!DOCTYPE html>
<html>
<head>
  <title></title>
</head>
<body>
<table border="1" style="border-collapse:collapse">
<tr><th>id</th><th>select_type</th><th>table</th><th>partitions</th><th>type</th><th>possible_keys</th><th>key</th><th>key_len</th><th>ref</th><th>rows</th><th>filtered</th><th>Extra</th></tr>
<tr><td>1</td><td>PRIMARY</td><td>&lt;derived2&gt;</td><td>NULL</td><td>ALL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>16468788102</td><td>100</td><td>Using temporary; Using filesort</td></tr>
<tr><td>2</td><td>DERIVED</td><td>&lt;derived3&gt;</td><td>NULL</td><td>ALL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>16468788102</td><td>100</td><td>Using temporary; Using filesort</td></tr>
<tr><td>3</td><td>DERIVED</td><td>u</td><td>NULL</td><td>ALL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>18174</td><td>100</td><td>Using temporary; Using filesort</td></tr>
<tr><td>3</td><td>DERIVED</td><td>org_user</td><td>NULL</td><td>ALL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>NULL</td><td>906173</td><td>100</td><td>Using where; Using join buffer (Block Nested Loop)</td></tr></table>
</body>
</html>

**Comment by marefr** [comment]
@deathwarrior60 thanks. Did you by any change forgot to restart Grafana after applying the configuration changes? 

That's a lot of rows processed :open_mouth: This is helpful. We're looking into it.

**Comment by deathwarrior60** [comment]
No, I restarted grafana after applying the configuration changes :)

**Comment by marefr** [comment]
@deathwarrior60 you want to disable total stats:
```ini
[metrics]
disable_total_stats=true
```
