### ISSUE TITLE
ScopedVars in react plugin

### ISSUE THREAD

**Issue by polovmak** [grafana/grafana#27334]
**What would you like to be added**:
I was trying to manipulate my query from react plugin and the only solution was to create dashboard variables and after change them buy getLocationSrv.Update() but firstly it throws an error and secondly I need different variables for each instance of my plugin.
Is there any way how to add scopedVars but in react? Because in Angular I've already seen a solution using this.panel.scopedVars

**Why is this needed**:
To manipulate query from your react plugin

**Comment by wbrowne** [comment]
This is part of a related issue #29647 of managing plugin variables, so will close this one
