### ISSUE TITLE
PanelHeader: $__dashboard.name does not work in panel title

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#27335]
**What happened**:
I'm using the $__dashboard in a panel, but instead of the dashboard name I see undefined
![image](https://user-images.githubusercontent.com/2118079/91987991-6ca5a280-ed37-11ea-8342-f631a873595b.png)

**What you expected to happen**:
That the dashboard name will appear.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel and add $__dashboard to the title.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5 (but I don't think it's a regression)
- Data source type & version: N/A
- OS Grafana is installed on: docker
- User OS & Browser: fedora/chrome
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
use ${__dashboard.name}

**Comment by amnonh** [comment]
I should have mentioned that I tried and it does not work, but the documentation states something else, please reopen

**Comment by amnonh** [comment]
See
![image](https://user-images.githubusercontent.com/2118079/91994906-d1fd9180-ed3f-11ea-87a1-f75fb6d03f7e.png)
