### ISSUE TITLE
Drilldown with multi selected varibles is not working as expected

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#27330]
Using an URL:  /d/UID/dashboardname?&var-Account=$Account&var-Region=$Region&from=$__from&to=$__to in a dashboard where $Region will have multi selected regions region1 and region2

When we drill down the landing page having elastic search panels and the URL resolved as below https://localhost:3000/d/UID/dashboardname?orgId=9&var-Account=1234&var-Region=region1,%20region2&from=1599022469888&to=1599026069889 . 

The multi-selected regions appearing as region1,region2 in the variable region on the landing page which is not supporting elastic search datasource panels.

**Comment by hugohaggmark** [comment]
Hi @satyatechy, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

Have you tried using `$Region:lucene`?
https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/

**Comment by satyatechy** [comment]
Tried advanced variable format options but no luck. It looks like an issue.

my msearch query:{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"indexname"} {"size":1000,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":"1599025914004","lte":"1599047514004","format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"@tenant_id:123 AND region:(\"region1,region2\")"}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"docvalue_fields":["@timestamp"]}

**Comment by hugohaggmark** [comment]
If you want us to look at this @satyatechy please file a proper issue with issue template and proper repro steps. I'm going to close this issue for now but will reopen it when you can supply proper repro steps and using our issue template.
