### ISSUE TITLE
Unable to connect Grafana v7.1.5 to InfluxDB v1.8.2 (Flux)

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#27331]
I'm trying to connect Grafana to InfluxDB v1.8.2 (Flux), but I get below error:
```
Post "http://localhost:8086/api/v2/query?org=root": dial tcp 127.0.0.1:8086: connect: connection refused
```

**Steps to reproduce:**
1) Use Windows Docker Desktop and install `grafana/grafana:latest`, `influxdb:latest` and `chronograf`:

```
docker pull influxdb:latest
docker pull chronograf:latest
docker pull grafana/grafana:latest

docker network create influxdb

docker run -p 8086:8086 --name=influxdb --net=influxdb -v C:/ProgramData/InfluxDB:/var/lib/influxdb influxdb -config /var/lib/influxdb/influxdb.conf 
docker run -d --name=chronograf -p 8888:8888 --net=influxdb --restart=always chronograf --influxdb-url=http://influxdb:8086
docker run -d -p 3000:3000 grafana/grafana
```
In the `influxdb.conf` file I've set `flux-enabled = true` and `flux-log-enabled = true`. Via the Chronograf admin viewer, I've created a bucket (`new-test-bucket`), a username `root` and password `root` with `ALL` access.

If I download Grafana for Windows I am able to connect by using the below details:

```
Type: Flux 

Url: http://localhost:8086
Organization: root
Token: root
Default bucket: new-test-bucket
```
However, when I try to follow these same steps via the docker installed Grafana build, I get the error instead. It looks like in this case, that it is trying to use an URL style including `/api/v2/`, which I'm assuming might be part of the issue?

Any inputs will be really helpful!

Martin

**Comment by aknuds1** [comment]
This looks like a support question, rather than a bug report. Please use our community [forum](https://community.grafana.com) or [Slack](http://slack.raintank.io). That said, I think you're running your Grafana container in a different network than Influx (the default rather than "influxdb"), so it can't connect to it.
