### ISSUE TITLE
Grafana timing out when querying Elastic datasource 

### ISSUE THREAD

**Issue by veer123prathap** [grafana/grafana#27346]
Hi there, I’m looking for some help diagnosing a timeout issue in our production Grafana.

We are running Grafana version 6.7, running on OpenShift 3.11. We are pulling data from Elastic search.

We are consistently hitting a timeout in Grafana when querying this Datasource after 30 seconds. The user is met with an error message that says 504 Gateway Time-out The server didn't respond in time. In the Grafana pod logs we see corresponding log lines like http: proxy error: context canceled.

It appears that there is some timeout configured somewhere in Grafana that we are hitting, but we’re at a loss for where it might be. Any suggestions?

**Comment by hugohaggmark** [comment]
Hi @veer123prathap, we use GitHub for issues and feature requests. For questions we kindly request that you ask your question at the [community site](https://community.grafana.com/) or in our external [Slack   here](https://grafana.slack.com/)

All the best
