### ISSUE TITLE
Assistance with graphing sparse points in Grafana?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2735]
I am attempting to graph how long database operations take in Grafana/InfluxDB.

The duration is stored in a field named `duration_in_miliseconds`.

These points do not occur regularly - rather, there is a point for each database operation.

If I try to graph the points directly in Grafana using say, mean, I get a flat line around zero:

![screenshot 2015-09-14 17 33 13](https://cloud.githubusercontent.com/assets/243499/9844438/b3018186-5b06-11e5-9c2c-1e46d71df2b5.png)

The query that is being sent to InfluxDB looks like this:

```
SELECT mean("duration_in_milliseconds") AS "duration_in_milliseconds" FROM "operations" WHERE "project" = 'test' AND time > 1439750000s and time < 1439751267s GROUP BY time(100ms)
```

If I run that from the InfluxDB shell, I do get a bunch of empty times with no values - I'm guessing this is due to the GROUP BY clause, correct?
```
> SELECT mean("duration_in_milliseconds") AS "duration_in_milliseconds" FROM "operations" WHERE "project" = 'test' AND time > 1439750000s and time < 1439751267s GROUP BY time(100ms) LIMIT 100
name: operations
----------------
time                    duration_in_milliseconds
2015-08-16T18:33:20Z
2015-08-16T18:33:20.1Z
2015-08-16T18:33:20.2Z
2015-08-16T18:33:20.3Z
2015-08-16T18:33:20.4Z
2015-08-16T18:33:20.5Z
2015-08-16T18:33:20.6Z
2015-08-16T18:33:20.7Z
2015-08-16T18:33:20.8Z
2015-08-16T18:33:20.9Z
2015-08-16T18:33:21Z
2015-08-16T18:33:21.1Z
2015-08-16T18:33:21.2Z
2015-08-16T18:33:21.3Z
2015-08-16T18:33:21.4Z
2015-08-16T18:33:21.5Z
2015-08-16T18:33:21.6Z
2015-08-16T18:33:21.7Z
2015-08-16T18:33:21.8Z
```

If I query without any aggregations, I can see the values I put in:

```
> SELECT duration_in_milliseconds FROM "operations" WHERE "project" = 'test' AND time > 1439750000s and time < 1439751267s
name: operations
----------------
time                            duration_in_milliseconds
2015-08-16T18:33:40.244Z        1723
2015-08-16T18:34:38.395000064Z  2231
2015-08-16T18:36:37.286000128Z  1164
2015-08-16T18:36:37.286000128Z  1144
2015-08-16T18:36:37.286000128Z  1211
2015-08-16T18:36:37.287000064Z  1230
2015-08-16T18:36:37.287000064Z  1269
2015-08-16T18:36:37.287000064Z  1186
2015-08-16T18:36:37.287000064Z  1288
2015-08-16T18:36:37.287000064Z  1159
2015-08-16T18:36:37.287000064Z  1228
2015-08-16T18:36:37.288Z        1230
2015-08-16T18:36:37.288Z        1161
2015-08-16T18:36:37.288Z        1174
2015-08-16T18:36:37.288Z        1327
2015-08-16T18:36:37.288Z        1477
2015-08-16T18:36:37.288Z        1304
2015-08-16T18:36:37.288Z        1231
2015-08-16T18:36:37.288Z        1152
2015-08-16T18:36:37.288Z        1494
2015-08-16T18:36:37.288999936Z  1232
2015-08-16T18:36:37.288999936Z  1187
2015-08-16T18:36:37.288999936Z  1183
2015-08-16T18:36:37.288999936Z  1104
```

My question is, is there a way to graph this in Grafana, without resorting to plotting the raw points? (I don't want to swamp the browser with millions of points).

I tried playing with the fill field under Group By, but none of those options had any effect.

**Comment by torkelo** [comment]
try fill(null)  in the query, and in the display options in Grafana set null point mode = connected

**Comment by victorhooi** [comment]
Hmm, I did try `fill(null)` previously, and I think Null Point Mode = connected is the default.

I just checked again, and it's still showing me the zero line:

<img width="1265" alt="screenshot 2015-09-14 17 53 41" src="https://cloud.githubusercontent.com/assets/243499/9844780/98a94758-5b09-11e5-9ea2-3aee91059b5a.png">

![screenshot 2015-09-14 17 53 48](https://cloud.githubusercontent.com/assets/243499/9844783/9ccb8ad0-5b09-11e5-8d98-9a0e9da9a4cf.png)

**Comment by torkelo** [comment]
Then maybe its a InfluxDB Query issue, I do not think you can have mean aggregation function and group by time that is so low that it will generate a bunch of nulls, what is the mean of 4.5 and null?, maybe `last` will work better?

**Comment by torkelo** [comment]
or disable fill

**Comment by victorhooi** [comment]
Hmm, perhaps I'll ping the InfluxDB guys.

Using `last` seems to be an improvement - below you can see last (top graph) versus raw values (bottom graph):

![screenshot 2015-09-14 18 17 35](https://cloud.githubusercontent.com/assets/243499/9845301/38daa5e8-5b0d-11e5-9b64-bdd439babd79.png)

**Comment by torkelo** [comment]
The problem with last is when you view a large timespan with many values the query will only use one value for each time bucket

**Comment by victorhooi** [comment]
@torkelo The mystery is solved! =)

It turns out the `duration_in_milliseconds` was getting stored as a string in InfluxDB.

Grafana will graph string values returned by InfluxDB - which is why I was still getting some points - but then InfluxDB will return zero/null for functions, apparently:

https://groups.google.com/d/msg/influxdb/eJrxPvzJdww/cArxvC4dCwAJ

Anyhow, I did an explicit conversation to int before storing, and the graph is working as expected now:

<img width="1274" alt="screenshot 2015-09-15 09 21 20" src="https://cloud.githubusercontent.com/assets/243499/9864275/2f0ea8a6-5b8b-11e5-89d1-381af09829eb.png">

I'm guessing Grafana's ability to graph string values as numbers - is that something you explicitly want?
