### ISSUE TITLE
Grafana 2.5.0-pre - Dashboart title error  ?

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#2736]
![image](https://cloud.githubusercontent.com/assets/12600004/9844883/31d72596-5ac7-11e5-8dad-1c6ddc528ac6.png)

**Comment by torkelo** [comment]
this was fixed this morning, building new pre release builds now, should be new builds available soon

**Comment by discoduck2x** [comment]
@torkelo just tried the latest version and cant start , getting:  [log.go:75 Fatal()] [E] Failed to detect generated css or javascript files in static root (%!s(MISSING)), have you executed default grunt task?
(centos 7 rpm install)

**Comment by torkelo** [comment]
did you try the latest release build or did you use build from master yourself?

**Comment by discoduck2x** [comment]
@torkelo  i downloaded https://grafanarel.s3.amazonaws.com/builds/grafana-2.5.0-pre1.x86_64.rpm

**Comment by torkelo** [comment]
detected the problem, fixed https://github.com/grafana/grafana/commit/d7bfb727b0e55be4a4143530bb49e986c3ffed12 

building new builds now

**Comment by discoduck2x** [comment]
@torkelo  still getting the same issue with the build from 1:47 PM

**Comment by torkelo** [comment]
damit, really sorry, did not test last fix fully :( 

Should have a new (hopefully working build) soon.
