### ISSUE TITLE
App plugin marked as signed but data source can't start

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#27364]
**What happened**:
Signed application plugin with data source included can't run data source backend.

![Screenshot from 2020-09-03 12-30-57](https://user-images.githubusercontent.com/4932851/92133728-6257d700-ee11-11ea-8177-5cef5e3e84ab.png)

**What you expected to happen**:
Backend data source up and running.

**How to reproduce it (as minimally and precisely as possible)**:
Get the [latest Zabbix plugin version](https://github.com/alexanderzobnin/grafana-zabbix/releases/download/v4.0.1/alexanderzobnin-zabbix-app-4.0.1.zip), install it and run Grafana.

**Anything else we need to know?**:
That's happened because grafana scans plugins folder and loads plugins from every folder containing the `plugin.json` file. Then grafana checks every plugin for valid signature. So if app has tree similar to this:
```
example-app
|-- example-datasource
|  |-- plugin.json
|  |-- datasource_executable
|-- example-panel
|  |-- plugin.json
|-- plugin.json
|-- MANIFEST.txt
```
then datasource will be treated as unsigned, however plugin has correct MANIFEST file with all files insluded.

Logs from grafana:
```
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Scanning external plugins directory" logger=plugins dir=/var/lib/grafana/plugins
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=alexanderzobnin-zabbix-datasource
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Invalid Plugin Signature" logger=plugins pluginID=alexanderzobnin-zabbix-datasource pluginD
ir=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix state=unsigned
t=2020-09-03T15:17:03+0000 lvl=eror msg="Failed to load plugin" logger=plugins error="plugin \"alexanderzobnin-zabbix-datasource\" i
s unsigned" pluginPath=/var/lib/grafana/plugins/alexanderzobnin-zabbix-app/datasource-zabbix
t=2020-09-03T15:17:03+0000 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=alexanderzobnin-zabbix-app
t=2020-09-03T15:17:04+0000 lvl=dbug msg="Verifying contents of plugin manifest" logger=plugins plugin=alexanderzobnin-zabbix-app
```

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Zabbix
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
@ryantxu @aknuds1 have you thought anything about this? is it logical to sign an app and included plugins in one manifest? I would guess signing the included data source separately should validate as data source properly signed?

**Comment by ryantxu** [comment]
@marefr I think it *could* be done either way, but having a single manifest for the app makes more sense so that it validates everything at once and either marks everything as signed or nothing.

The core problem we have now is that signing verification and walking are tied together.  There are a few band-aids we could do to fix this, and it is worth thinking about this while also solving https://github.com/grafana/grafana/issues/27871.  Perhaps:
1. add metadata about parent/child plugins in [PluginBase](https://github.com/grafana/grafana/blob/master/pkg/plugins/models.go#L49)
2. move the signing validation out of the walk function
3. when validating signatures, replace a backend plugin metadata with some kind of phantom datasource (that will not actually run)

**Comment by marefr** [comment]
> having a single manifest for the app makes more sense so that it validates everything at once and either marks everything as signed or nothing.

Yes and no. An app is not really treated as a bundle right now. In theory you could have a data source plugin with multiple apps and panels or a panel plugin with data source and app plugins. Not sure how common that is though :) 

Given the existing plugins are currently scanned one by one in Grafana the easiest thing would be to continue require each plugin to have a manifest even though multiple plugins are packaged in the same zip/package. Will require some more work in packaging plugins, but I think it's worth it short term (next release). Longer term, looking at plugin management/manager think we can come up with a proper/better solution.

**Comment by aknuds1** [comment]
@wbrowne and I will work on this soon. I just came back from holidays!

**Comment by aknuds1** [comment]
Looking at this again.
