### ISSUE TITLE
Change the secondary button style in Grafana to match Figma

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#27360]
While the new form styles were implemented, some styles were updated with the Figma design, others weren't. In the Design System Knights, we discussed this and didn't see a reason why the secondary button style shouldn't be adapted from the Figma design. So we decided that the Secondary button should be changed to match [Figma](https://www.figma.com/file/I34UgAga9JvqjlxfKYZnve/Design-System?node-id=1155%3A7). 
The main change is the background gradient in the dark theme, the hover state and potentially the border color.

With the new button style, the buttons will look
_less disabled
_less like they are already pressed

**Comment by jessover9000** [comment]
@torkelo and @dprokop , any opinions or insight about why the secondary buttons look the way they look and not the way @Ijin08 designed them? we are curious! 🙃

**Comment by torkelo** [comment]
part of v8 theme work
