### ISSUE TITLE
Key/Value variable selector with "multi-value" enabled displays values instead of keys

### ISSUE THREAD

**Issue by serg472** [grafana/grafana#27372]
I am trying to create a key/value variable from a postgres query (classic show "names" use "ids" selector):

` SELECT * FROM ( VALUES('field1', 1), ('field2', 2) ) AS t (__text, __value)`

I am expecting it to surface "field1, field2" options to users while providing me numerical "1,2" values in queries.

This works as expected for a single select variable, but when enabling multi select it shows numerical values to users:
<img width="244" alt="Screen Shot 2020-09-03 at 3 08 59 PM" src="https://user-images.githubusercontent.com/1200229/92179093-e0f44a80-edf8-11ea-96be-0352990c987a.png">
<img width="261" alt="Screen Shot 2020-09-03 at 3 20 14 PM" src="https://user-images.githubusercontent.com/1200229/92179156-02553680-edf9-11ea-9fdf-96ade204b8de.png">

Sounds like multiselect widget is not aware of key/value variables.

**Environment**:
- Grafana version: v7.1.3 (5723d951af)
- OS Grafana is installed on: CentOS 7
- User OS & Browser: MacOS, Chrome
- Grafana plugins: None

Thanks

**Comment by hugohaggmark** [comment]
@serg472 I think this was resolved in 7.1.5, can you please check?

**Comment by serg472** [comment]
Yes it is fixed in 7.1.5. Thank you!
