### ISSUE TITLE
Add remove all filters for adhoc filters

### ISSUE THREAD

**Issue by adigov** [grafana/grafana#27371]
This is a feature request.

When we are adding adhoc filters please add a delete/trash can icon at the end so that it deletes all adhoc filters that are applied

**Comment by adigov** [comment]
something like this:
![image](https://user-images.githubusercontent.com/960211/92180969-1307ab80-edfd-11ea-9236-21160f1f68c6.png)

**Comment by hugohaggmark** [comment]
Could probably be looked into at the same time #25529

**Comment by Notedop** [comment]
need this simple feature, would improve user experience a lot...
