### ISSUE TITLE
Dashboard Data Type - Degradation between versions 6.X and 7.X

### ISSUE THREAD

**Issue by rpourzand** [grafana/grafana#27374]
Hello, 

I am reporting this issue because I believe it might be a degradation/bug. The issue did not occur on Grafana 6.3, but it does occur on 7.1.5 with the same data source, data, and dashboard query. Can you please let me know if anything changed that would cause this?

**Description**

The Y-axis data type which should be a short value is defaulting to the start of the Unix epoch in 7.1., but not in 6.3

Here is a picture of what this looks like using Grafana 6.3. As you can see the values are properly represented as short (counts): (note I've masked IPS)

![6 3](https://user-images.githubusercontent.com/29593086/92185395-b8744c80-ee08-11ea-8e0b-aeefc8706426.png)

Here is what it looks like with Grafana 7.1
 
![7 1](https://user-images.githubusercontent.com/29593086/92185447-da6dcf00-ee08-11ea-84e6-a2ba1b0b46a5.png)

The data sources are coming from the same table and JSON query. 

I expect to see values instead of "1969-12-31 16:00:00"

**What I did to debug**
I attempted to add some null handling to the query because I assumed it was a null issue, but that did not help
I attempted to manually change the Y axes data type to "short", but that also did not help. 

Short of sending you all my data and DDL and query to repro the dashboard, I haven't had a chance to create a minimal repro yet. I can create a minimal repro if this issue is not clear.

**Environment**:
- Grafana version: [ec2-user@ip-172-31-70-123 sbin]$ ./grafana-server -v
Version 7.1.5 (commit: 9893b8c53d, branch: HEAD)
- Data source type & version: MySQL 
- OS Grafana is installed on: RHEL
- User OS & Browser: Mac / Chrome
- Grafana plugins: grafana-piechart-panel and  sudo grafana-cli --pluginUrl https://github.com/CorpGlory/grafana-multibar-graph-panel/archive/0.2.5.zip plugins install multibar-graph-panel

**Comment by torkelo** [comment]
Are you using a custom graph panel? Can you show your panel json ?

**Comment by torkelo** [comment]
This is a bug in this community graph panel

**Comment by rpourzand** [comment]
thank you! this is good to know.
