### ISSUE TITLE
Grafana 5.3 with SQL server 2016 supported

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#27379]
**What happened**:Is grafana 5.3 version supported sql server 2016

**What you expected to happen**:should be connected

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:desktop
- Grafana version:5.3
- Data source type & version:sql server 2016
- OS Grafana is installed on:window 10
- User OS & Browser:Chrome AND ie
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
Please direct support questions to the community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io).
