### ISSUE TITLE
Docs: Do not update latest docs from master

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#27384]
Updating latest docs directly from master has it's pros & cons. 

Pros 
* Doc fixes & improvements get released right away without any additional cherry pick / merge step.

Cons
* New settings and features get's added to the docs of the current stable release before they are available in the coming release (we usually work around this by adding release notices to new features/settings that inform from what version they where added)

If we are to change this so we do no longer update latest docs from master we need to make a number of changes

* [ ] Update the git sync action so that it syncs latest  grafana release branch to latest in website repo (https://github.com/grafana/grafana/blob/master/.github/workflows/publish.yml#L26) 
* [ ] Create new github action job to sync master with a `vnext`  folder in website repo
* [ ] Update the script that creates new releases to copy from vnext to latest https://github.com/grafana/website/blob/master/scripts/grafana-docs-release.sh

We also need to update all doc links and alias in master from `latest` to `vnext` as currently the docs checked in this repo is designed to only update the latest docs (that have latest in the URL). 

If anyone comes up with a simpler change or better solution to the root cause I am welcome to suggestions 

thoughts? 
@RichiH @robbymilo @oddlittlebird @daniellee

**Comment by RichiH** [comment]
This is the best trade-off IMO. We get to edit & update docs along with code, have a place where anyone running beta releases can look up information, and keep the released docs clean without the overhead of manually tagging, and untagging, docs as not applicable yet.

**Comment by oddlittlebird** [comment]
A lot of the doc changes we make are not tied to upcoming Grafana versions. We want content to appear immediately most of the time. Would this change still allow us to do that?

I would prefer some sort of toggle so that I could choose to apply changes to the vnext holding area and have the default be to appear in the current docs.

**Comment by torkelo** [comment]
> I would prefer some sort of toggle so that I could choose to apply changes to the vnext holding area and have the default be to appear in the current docs.

That will not be possible, for changes to show up directly they would have to be merged to the current stable release branch

**Comment by oddlittlebird** [comment]
Then please do not make this change. Most of the changes people make to the docs are to current content.

**Comment by torkelo** [comment]
@robbymilo does this sound like a good plan?

**Comment by torkelo** [comment]
@robbymilo does this sound like a good plan?

**Comment by robbymilo** [comment]
I like the idea of having a different section for beta/pre-release/vnext docs - I think it makes sense from an end-uer standpoint. 

>
> We also need to update all doc links and alias in master from latest to vnext
>

Not sure how well this would work in practice. There are quite a few variations of links in use - relref, markdown link, absolute vs relative (ex. `../../` in the link). It would be difficult to create a script that can handle all use cases.

I also see some potential confusion for docs authors - they would need to have a clear understanding for making PRs and which branch to target. For example, what if their PR contains beta and current documentation?

**Comment by oddlittlebird** [comment]
> I also see some potential confusion for docs authors - they would need to have a clear understanding for making PRs and which branch to target. For example, what if their PR contains beta and current documentation?

That's why we have professional writers overseeing the docs nowadays. If we have clear guidelines, then we can enforce them.

> Not sure how well this would work in practice. There are quite a few variations of links in use - relref, markdown link, absolute vs relative (ex. ../../ in the link). It would be difficult to create a script that can handle all use cases.

This is another case where clear guidelines would help. Right now, the only guidance on links is "use relref for internal links." If we know of other rules or best practices, then we can enforce them. Also, @osg-grafana had a suggestion about moving the older versions of the docs to other branches, which might cut down on some of the complication.

**Comment by achatterjee-grafana** [comment]
@oddlittlebird can you clarify "moving the older versions of the docs to other branches"? I assumed that other releases had a corresponding branch that had the relevant documentation. The master was the latest or the current branch? Thank you.

**Comment by osg-grafana** [comment]
> @oddlittlebird can you clarify "moving the older versions of the docs to other branches"? I assumed that other releases had a corresponding branch that had the relevant documentation. The master was the latest or the current branch? Thank you.

Yes, to have release branches that contain the documentation that went out with given releases. It is an expected workflow that master contains that which is under development rather than being that and an archive of past releases.

**Comment by torkelo** [comment]
>  It is an expected workflow that master contains that which is under development rather than that and an archive of past releases. 

There is no archive, not sure what you mean?

**Comment by oddlittlebird** [comment]
> There is no archive, not sure what you mean?

She is referring to the folders containing past releases.

**Comment by oddlittlebird** [comment]
Tagging @briangann for visibility

**Comment by 56quarters** [comment]
For what it's worth Read The Docs has a scheme that seems to strike a good balance between making changes available quickly and not confusing users with unreleased features: https://docs.readthedocs.io/en/stable/versions.html#version-warning

**Comment by kavirajk** [comment]
We Loki squad also thinking something similar to this. We keep getting questions on public slack about features we haven't even released. Loki users often things "latest" meaning latest released version.

We propose a solution 
latest -> always points to latest public version
nightly -> points to master branch.

More details here! https://github.com/grafana/loki/issues/3317

Meaning, 

We just rename our current "latest" directory to "nightly" and create some kind of symlink to latest released version (when we do public release every-time)

NOTE: name "nightly" doesn't matter here. It can be anything unless we have clear separation between unstable master branch docs vs latest stable released version. And user coming to docs page should land on latest stable version by default.

/cc @robbymilo @torkelo

**Comment by oddlittlebird** [comment]
@kavirajk, with your solution, would we still be able to update the public docs easily?

**Comment by kavirajk** [comment]
@oddlittlebird I can't think of anything changes in terms of updating public docs with that approach :)

**Comment by robbymilo** [comment]
I am all for moving forward with this. Best to keep `latest` at the most recent stable release due to lots of redirects currently in place, and then add a `next/nightly` dir in the website repo. This would also allow us to start with the grafana repo and then implement in other repos.

Website notes:
- The `latest` dir would be the only dir in (upcoming) site-wide search index
- The github edit link and version selector in the sidebar would need to be updated, as well as the archived version banner

From there, the master branch version of the [sync workflow](https://github.com/grafana/grafana/blob/master/.github/workflows/publish.yml) would need to be updated to point to the new dir, and then the release branch would point to the `latest` dir (workflow file would need to be updated on every release). We'd also need to update the release scripts and make sure the templates work properly.

**Comment by achatterjee-grafana** [comment]
This would be great! How soon @robbymilo can we can get the master branch version to point to the new directory.

**Comment by osg-grafana** [comment]
@undef1nd asks, ""...if say I make a PR and set its milestone as 8.0, should I merge this PR or should I wait for the 8.0 release day?)"

**Comment by achatterjee-grafana** [comment]
Spoke to Daniel about this yesterday. Longterm, we would want to come up with a solution where we should be able to create a single PR and apply one or more labels. This will let us auto-merge the changes to the branches specified as labels.

**Comment by osg-grafana** [comment]
For more information, see https://git-scm.com/book/en/v2/Git-Basics-Tagging.

**Comment by achatterjee-grafana** [comment]
The issue has been fixed, via PR https://github.com/grafana/website/pull/3934.
