### ISSUE TITLE
segmented loading when use auto refresh

### ISSUE THREAD

**Issue by songjiao** [grafana/grafana#27381]
**What would you like to be added**:
support segmented loading when use auto refresh
**Why is this needed**:
A dashboard refresh every 30s with time range last 24h. when trigger the query every 30s, it's will query the whole last 24h's data. It's will be much faster if only query last 10m's data and merge the new data to old data.

**Comment by torkelo** [comment]
This is not possible as a lot of queries require the full-time range (moving average, and many other query functions).

But for data sources that support streaming partial updates work. Think there is an old feature request to support this in other cases
