### ISSUE TITLE
Explore: page title is not set

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#27387]
**What happened**:
Explore does not set page title, rather the title from the previous page remains.

**What you expected to happen**:
Page title like "Explore - Grafana"

**How to reproduce it (as minimally and precisely as possible)**:
1. go to some page, like a dashboard
2. go to Explore

**Environment**:
- Grafana version: 7.1.4

**Comment by ivanahuckova** [comment]
Fixed by https://github.com/grafana/grafana/pull/34651
