### ISSUE TITLE
Docs: Table field options are documentated on the wrong page 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#27388]
The table-specific field options should be part of the table visualization docs

* Cell mode
* Column alignment
* Column width 

Are all table specific and not part of the standard field config options 

https://grafana.com/docs/grafana/latest/panels/field-configuration-options/#cell-display-mode

**Comment by oddlittlebird** [comment]
No, they should not be part of the table visualization docs. When the field config options go out of beta, the field config options will be broken up into separate topics and probably reorganized. As it is, we need more specific table-related task docs, but the content you are referring to does NOT belong in the Visualizations section.

**Comment by torkelo** [comment]
These options (Cell mode, Column alignment, Column width) are table display settings (that are field level settings, or what we call field custom (visualization specific) options). 

These should be part of the table visualization docs in my view as they fundamental to how you configure this visualization and are ONLY relevant when you interested in table visualization settings. 

Is there an argument to spit the table specific visualization settings on two pages? We will introduce many visualization specific settings in the coming graph panels and want them part of the visualization docs.

**Comment by oddlittlebird** [comment]
Yes. The Visualizations as they currently exist are incomplete. They are an odd mishmash of concept and reference documentation. Concept (what a type of visualization is, what it is for, and so on) documentation is ideally kept separate from task documentation. The tasks in this case are Change column width, Filter table columns, and so on. Unless the tasks are extremely short, they should be separate topics. 

As I said in the note, as soon as the field configuration feature is out of beta, I will break up the topic and reorganize it a bit. I will do that as soon as your current PR against that topic is sorted out.

The other issue is that I was told the custom field configuration section might apply to non-table visualizations in the future. BTW, if it won't, then we really need to rename that section. "Custom" is misleading in this case, anyway.

**Comment by torkelo** [comment]
> The other issue is that I was told the custom field configuration section might apply to non-table visualizations in the future. BTW, if it won't, then we really need to rename that section. "Custom" is misleading in this case, anyway. 

No custom is ALL visualization specific and should be in the visualization doc page. The heading `Custom` is bad. should be the visualization type name

**Comment by oddlittlebird** [comment]
That would help. It still needs to be a task and crosslinked, but that would help.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/27579
