### ISSUE TITLE
date/time and y-axis 1 & y-axis two don't line up on zero line on same panel

### ISSUE THREAD

**Issue by aleks-mariusz** [grafana/grafana#2738]
Two quick issues:

Issue A - On a graph utilising two Y-axis, when using negative transform on both sides, the zero line does not line up from the left Y-Axis 1 to the right Y-Axis 2.  This should really automatically line up horizontally, if not at least have a setting to force these to line up.

Issue B - On a single panel with two graphs vertically aligned, the date/time from the x-axis major-lines do not line up.  This likely is caused by the width of the legends being different, however there should be an option to force these to line up. This makes correlating events across two lined up graphs difficult.

![screen shot 2015-09-14 at 16 49 46](https://cloud.githubusercontent.com/assets/2719694/9854711/194d4e48-5b02-11e5-8c76-60055407e7f1.png)

**Comment by torkelo** [comment]
Issue 1, you can get them to align, but the only way is to enter the same Grid min/max for left Y and right Y, its very tricky to align 0 if both axes have an auto min/max range. 

Issue 2: They are not aligned as your Y-axis are different widths. You can enabled shared cross hair in Dashboard settings to get a shared red line that will show on all graphs as you hover over a graph.

**Comment by aleks-mariusz** [comment]
Can we have a feature request where there is a checkbox to align zero's on both y-axis's then please ?

**Comment by torkelo** [comment]
yes, you can create a feature request, I think for this there already is one, but not 100% sure

**Comment by aleks-mariusz** [comment]
did a qiuck search but didn't see anything related to zero line alignment.. opened up feature request "issue" here:

https://github.com/grafana/grafana/issues/2740

**Comment by jonathanstrong** [comment]
A note about feature discoverability: just came across this and the "shared cross hair" setting is a HUGE deal to me - but have used grafana (+influx) daily for 2 years and had never found it. Looking back, I guess I had expected something like this to be in the panel edit dialog, which doesn't make sense since it's not dashboard-wide, but it is where the vast majority of appearance settings are. Just my two cents, thanks for your work on this great program.
