### ISSUE TITLE
Docs: Add version notice to Group by docs

### ISSUE THREAD

**Issue by biqqles** [grafana/grafana#27386]
**What you expected to happen**: I upgraded from v7.0.5 to v7.1.5, hoping to see the new ["Group By" transformation](https://grafana.com/docs/grafana/latest/panels/transformations/#group-by) advertised in the docs.

**What happened**: Sadly the transformation isn't listed in the Transformations tab. Has it been removed? Merged into another transformation? Was it ever there? :thinking: 

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: InfluxDB, version 1.8.2
- OS Grafana is installed on: Linux 4.19
- User OS & Browser: Linux 4.19, Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
It's coming in v7.2

**Comment by torkelo** [comment]
@mckn can you update the group by docs with a version notice?

**Comment by biqqles** [comment]
> It's coming in v7.2

Good to know, and thanks for the quick response.

**Comment by mckn** [comment]
> @mckn can you update the group by docs with a version notice?

Yes, thanks for opening this issue @biqqles 🙏
