### ISSUE TITLE
Preserve old images on dockerhub

### ISSUE THREAD

**Issue by marcindulak** [grafana/grafana#27380]
**What would you like to be added**:

Docker [announced](https://www.docker.com/pricing/resource-consumption-updates) that starting from November 1st 2020

```
If an image has not been pulled or pushed within 6 months, the image will be
marked “inactive.” Any images that are marked as “inactive” will be scheduled for
deletion. Only accounts that are on the Free individual or organization plans will be
subject to image retention limits. 
```

**Why is this needed**:

This may affect the images from https://hub.docker.com/u/grafana, and it would be great if the old images can be preserved.

In the same announcement we read:

```
If you have a Free account, you can easily upgrade to a Pro or Team account
starting at $5 per month with an annual plan.
```

This issue is created in order to know what to expect after November 1st.

**Comment by marefr** [comment]
@aknuds1 assigned you in case you have any input/thoughts about this to kick off the discussions

**Comment by hugohaggmark** [comment]
@torkelo I assigned you to see what we need to do

**Comment by hugohaggmark** [comment]
Thank you @marcindulak for reporting this ⭐

**Comment by aknuds1** [comment]
I noticed this change in DockerHub's terms yesterday too.

**Comment by aknuds1** [comment]
It's also possible to apply for an [OSS plan](https://www.docker.com/community/open-source/application).

**Comment by torkelo** [comment]
This is now handled (we are on a paid plan)
