### ISSUE TITLE
Chore: Enable and fix eslint-plugin-react-hooks warning and errors in the monorepo

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#27391]
After https://github.com/grafana/grafana/pull/26094 merged the we can start to work on enabling eslint-plugin-react-hooks for the packages and the main app.
As of today (2020.09.04.) there are ✖ 169 problems (86 errors, 83 warnings) in the whole monorepo after enabling the rules.
The plan is to fix these warnings continuously.

- [x] grafana-toolkit 26problems total -  React Hook "useSpinner" cannot be called at the top level. React Hooks must be called in a React function component or a custom React Hook function - This error should be silenced by leaving an override in the root eslintrc
- [x] grafana-ui has 58 problems total (I think this should be separated to storybook errors and component errors) Fixing the component errors we must make sure that we can not create any regressions.
  - [x] storybook errors
  - [x] component errors
  - [x] ~uPlot - 25 warnings.~ added to the eslintignore 
- [x] jaeger-ui-components 4 problems total
- [ ] public folder 81 problems total This is where things can get south real quick so we should focus not to create any regressions here (it is probably a good idea to divy this up to smaller chunks and not to do the whole in one pr)

To see the errors simply remove the overrides property in the eslintrc file and run yarn lint.

**Comment by Clarity-89** [comment]
Tried running the check for the enterprise repo, the files for which are symlinked to `public/app/extensions`, but seems like eslint is using `.gitignore`, where this directory is excluded. I think we might need a separate `.eslintignore` file here.
