### ISSUE TITLE
grafana-server.exe on windows is not working ? its not starting .. no error logs also

### ISSUE THREAD

**Issue by mrinalnathdigitate** [grafana/grafana#27398]
I am using grafana on windows from a zip

I start grafana-server.exe from the command prompt and nothing happens

**Environment**:
- Grafana version: grafana-7.1.5
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aknuds1** [comment]
I've tested the Grafana 7.1.5 zip archive on Windows 10, version 2004. The server launches without problems.

**Comment by mrinalnathdigitate** [comment]
can you please help debug the problem ?

Regards,
Mrinal

Mrinal Nath
Digitate | A Tata Consultancy Services Venture
m:  9011038440
e:  mrinal.nath@digitate.com

**Comment by aknuds1** [comment]
As I wrote already, please use our community forums or Slack, since we don't provide support via GitHub.
