### ISSUE TITLE
[Feature request] Stat Panel:  value mappings with variable

### ISSUE THREAD

**Issue by mmurae** [grafana/grafana#27401]
**What would you like to be added**: Stat Panel: variable in value mappings 

**Why is this needed**: Works in Singlestat Panel, in new Stat Panel,  variable seems like a string.

![image](https://user-images.githubusercontent.com/43579328/92293046-e8018280-eef6-11ea-9707-53083f929df0.png)
![image](https://user-images.githubusercontent.com/43579328/92293142-7d047b80-eef7-11ea-8d33-dd81a950aa4f.png)

**Comment by marefr** [comment]
Duplicate of #26654
