### ISSUE TITLE
influx stacked bars don't work with null value = null

### ISSUE THREAD

**Issue by stevenh** [grafana/grafana#27406]
![image](https://user-images.githubusercontent.com/104239/92323952-bc84b200-f034-11ea-86c0-dd8bc9b57c19.png)

**What happened**:
Only the last stack appears to have an accurate representation of the data, all others only show few items for time time period.

**What you expected to happen**:
Each bar should represent the stacked values of that time, however instead only the last time group seems to display correctly. This can be seen by hovering over other groups which clearly show more than the few items..

**How to reproduce it (as minimally and precisely as possible)**:
- Created a graph using influx data source
- Selected Draw Modes = Bars
- Selected Stacking = Stacked

SELECT max("value") FROM measurement WHERE $timeFilter GROUP BY value_tag, time($__interval) fill(null)

**Anything else we need to know?**:
Selecting percent seems to trigger stacks to show the values.
![image](https://user-images.githubusercontent.com/104239/92324051-d7a3f180-f035-11ea-9593-ffbc58d13d22.png)

**Environment**:
- Grafana version: Grafana v6.7.4
- Data source type & version: influx
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome Windows 10
- Grafana plugins:
- Others:

**Comment by stevenh** [comment]
I just selected Null value = `null as zero` and I get what I would expect to see with it set to `null`  
![image](https://user-images.githubusercontent.com/104239/92324140-ad9eff00-f036-11ea-9c79-eb0b0eb31beb.png)

**Comment by torkelo** [comment]
For stacking Grafana needs a non null value, suggest fill(0) in your query

**Comment by fyang13** [comment]
This is not obvious to most users, should document be updated with "null as zero" as requirement for Bar gauge panel?
