### ISSUE TITLE
template value tags regression: does not deselect "All"

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#27415]
**What happened**:
On a template variable with "Multi-value", "Include all", and "Value groups/tags" enabled, when a tag is selected in the dropdown the "All" item of the variable is not deselected.

This worked fine in grafana 6.x.

![Screen Shot 2020-09-07 at 11 30 57 AM](https://user-images.githubusercontent.com/1708631/92343210-17cea700-f0fe-11ea-864c-db7e8d988c59.png)
![Screen Shot 2020-09-07 at 11 31 47 AM](https://user-images.githubusercontent.com/1708631/92343215-1b622e00-f0fe-11ea-8a99-d567f97fd885.png)

**What you expected to happen**:
When tags are selected, "All" is deselected.

**Environment**:
- Grafana version: v7.1.5
- User OS & Browser: OS X / Chrome

**Comment by marefr** [comment]
Reproduced here by enable all values: https://play.grafana.org/d/000000024/templating-value-groups. Not sure though whether this was working before templating migration.

**Comment by belm0** [comment]
It was working in 6.x, we'd relied on it for months.

**Comment by kaydelaney** [comment]
Tags are unfortunately an experimental feature and won't be supported in the future. Closing this since it's a feature that's set to be removed.
