### ISSUE TITLE
Feature Request: Allow anchors or equality with template variables

### ISSUE THREAD

**Issue by Inisfair** [grafana/grafana#2741]
Using InfluxDB 0.9 as data source with Grafana 2.1.3.  Noticed an issue where some of the dynamic dashboards built using templates do not always work as expected because the use of regular expressions when template variables are used in the query sometimes matches on substrings.

For example, In my data set I may have "web", "external web", "web analytics" within a collection of series.  When "web" is selected as an option all of the metrics from all 3 sets are included which make the charts inaccurate.

Ideally I should be able to specify an exact match using the = equality operator instead of the RE operator =~ OR specify the use of a RE anchor like /^$Variable/, /$Variable$/ or /^$Variable$/ for beginning/end/exact matches if the RE operator is required.

**Comment by torkelo** [comment]
In 2.5 (vNext) the auto suggestion is  `/$varname$/  , you can use this today , hm.. maybe it should be `/^$varname$/`  ,  hm.. or maybe with the alternate syntax (that is still valid in Grafana), `/^[[varname]]$/

There is no equality regex operator in InfluxDB

**Comment by Inisfair** [comment]
I meant that in the Grafana UI when you are building a query, it automatically sets the RE operator on the query and forces you to use the RE syntax.  I was suggesting to use the variable directly (would only work for single select template variables) so that instead of "tag =~ /$varname/" being the only valid option you can build in the GUI that you would also have the option of "tag = $varname". It seems even if you manually write the query like the later if fails to treat $varname as a variable without the RE markers around it.

It's OK for me personally to go into the raw query mode and edit the query to add the RE anchors (for now) but that's not true for all of the end users of the dashboards we are building who are not all technical.  I'll manually adjust the graphs that are having this issue to use the exactly match syntax because there would still be overlap using either the ends with or beings with syntax.

I didn't know about the alternate syntax, that is good to know.

**Comment by torkelo** [comment]
you do not have to go into raw query mode, just write `$varname` in the editor tag value field, its just the auto complete that suggest regex because most users expect to All varaible value to work
