### ISSUE TITLE
error:"tsdb.HandleRequest() error Could not find executor for data source type: taosdata-tdengine-datasource"

### ISSUE THREAD

**Issue by axiao43** [grafana/grafana#27418]
**What happened**:
### **does not support alerting queries** 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version: TDengine
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Closing due to no details.
