### ISSUE TITLE
Cog icon for folders in dashboard list is unclear and the position should be changed

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#27428]
**What happened**:
When you hover over a folder in the Grafana dashboard list/search, a little cog icon is shown on the very right of the list item (next to the caret).
![image](https://user-images.githubusercontent.com/53754871/92394774-6c841900-f122-11ea-9139-a6834610b7f8.png)
Upon clicking on the cog, you are taken to the inside of that folder. 

**What you expected to happen**:
The cog icon confuses me because I associate a cog with settings, so I expect that list view to enable me to modify something. However, what that link does is basically "go to folder X" with no option to change any settings. So the cog icon should be changed to something that resembles this "go to folder" mechanism. I recommend the "folder-upload" icon from the Unicons library. Also I suggest adding a text link caption to that icon saying "Go to folder" for extra clarity. Since the icon only appears on hover the link shouldn't clutter the view much.

**Positioning of the icon**
Testing the added link text in Figma, I don't think it looks right when it's next to the caret – the proximity of the caret to the link text falsely suggests that the caret is related to the link. (second row)
![image](https://user-images.githubusercontent.com/53754871/92396624-9c80eb80-f125-11ea-9ac8-eef4ac62d89e.png)
The distance between the list items on the left and the cog icon on the right is quite far, so by arranging the icon there we make it quite hard for our users to reach and hit a single icon. Chances are that users are navigating that list with their cursor on the left-hand side of the screen, so we're making it easier for them if we show the icon/link close to the folder name. If the icon and link are right next to the title though, users might have trouble distinguishing "go to folder" from the main title link which expands/collapses the folder. Just putting more whitespace like in the first row of the design test looks weird. So I suggest adding a pipe icon like in the third row. Opinions are welcome though :)

**Comment by torkelo** [comment]
Yea, this cog was a terrible UX choice. This is a much better idea. 

@Clarity-89 want to take a quick stab at this?

**Comment by Clarity-89** [comment]
Sounds good, I'll take a look at this.
