### ISSUE TITLE
Automatically graph multiple tagged values from InfluxDB?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2742]
I'm attempting to store metrics around database operations in InfluxDB and graph these in Grafana.

I am storing these in a measurement named `operations`.

Each database operation has a operation type - for example, `command`, `query`, `insert` etc. - these are stored in a tag named `operation`.

In Grafana, I can graph each of these as a separate series like so:

<img width="1268" alt="screenshot 2015-09-15 09 30 53" src="https://cloud.githubusercontent.com/assets/243499/9864408/a7fff336-5b8c-11e5-8797-99494656a976.png">

However, my question is - is there a way for Grafana to *automatically* graph a particular measurement, and create separate lines/series for each tag value?

**Comment by torkelo** [comment]
yes, just group by the tag :)

**Comment by RobWin** [comment]
Thx :) !!
