### ISSUE TITLE
Hosting grafana on IIS on windows

### ISSUE THREAD

**Issue by kristiansneskov** [grafana/grafana#2743]
First, thanks for the amazing effort to create grafana. I was very happy to see that it just works as described in the docs. I can run it fine as a service using port 3000 as default.
I am running v 2.1.3

I am now attempting to host the static files in a web server; and I am constrained to use windows so that means IIS. Based on the docs it seems I should just host the root folder (ie the unzipped grafana-2.1.3 folder in my case). And I figured I needed to use the public/views/index.html as my default document. However, I encounter an error when loading that page:  
![capture](https://cloud.githubusercontent.com/assets/10999377/9870247/a2ab9eaa-5b8a-11e5-9880-29a4c13dc3a3.PNG)

I expect that it does not resolve the AppSubUrl variable. 
Note I have no network connectivity on the machine that I am setting this up on. The idea is that grafana dashboards will be available in-house only.
Is there something obvious I am missing here? 
Thank you in advance!

**Comment by torkelo** [comment]
if you want to host is using IIS you need to let IIS act as a reverse proxy to the backend. You still need to run the grafana-server daemon, it is the grafana backend component that can server the the http api and the HTML views. 

You can use nginx, or IIS but only as proxies.

**Comment by kristiansneskov** [comment]
Ah yes of course. It works now! 
Thanks!
