### ISSUE TITLE
Singlestat: show error if query returns more than one series

### ISSUE THREAD

**Issue by maddenca** [grafana/grafana#2745]
I use a singlestat panel to show the average value of many metrics matching a Graphite wildcard metric string.  If any of the individual metrics has exclusively null values the panel shows N/A. But if each individual metric has at least one non-null value it calculates correctly.

It can be annoying because a stale metric (ex: a server that was decommissioned and is no longer updating but you still want to retain for historical purposes) can cause N/A.  Or, if some metrics only arrive in portions of the day, changing the time window may result in singlestat flipping from N/A to some value, to N/A, depending on if any underlying metric happens to be exclusively null or not.  Using a transform isn't possible because it would impact the calculated singlestat summary value, and I'm not aware of a way to exclude a metric that is exclusively nulls.

**Comment by torkelo** [comment]
I cant replicate this, can you show the query and the graphite response?

**Comment by maddenca** [comment]
#### Here is an example where singlestat avg is N/A:

**Request form data**
target=highestAverage(netapp.perf7.nl.sdt-7dot1a.cifs.vscan.*.scanrequests_completed%2C%205)&from=-5min&until=now&format=json&maxDataPoints=100
Name	

**Response data**
[{"target": "netapp.perf7.nl.sdt-7dot1a.cifs.vscan.vfiler0.scanrequests_completed", "datapoints": [[null, 1442321400], [null, 1442321460], [null, 1442321520], [null, 1442321580], [null, 1442321640]]}, {"target": "netapp.perf7.nl.sdt-7dot1a.cifs.vscan.sdt-vfiler1.scanrequests_completed", "datapoints": [[0.45, 1442321400], [0.633333333333333, 1442321460], [0.688524590163934, 1442321520], [0.576271186440678, 1442321580], [0.766666666666667, 1442321640]]}]


#### Then change to a different time window when one of them isn't exclusively nulls and then singlestat avg is .3:

**Form data**
target=highestAverage(netapp.perf7.nl.sdt-7dot1a.cifs.vscan.*.scanrequests_completed%2C%205)&from=1442314436&until=1442314869&format=json&maxDataPoints=100

**Response data**
[{"target": "netapp.perf7.nl.sdt-7dot1a.cifs.vscan.vfiler0.scanrequests_completed", "datapoints": [[null, 1442314440], [null, 1442314500], [null, 1442314560], [null, 1442314620], [0.229508196721311, 1442314680], [0.433333333333333, 1442314740], [null, 1442314800], [null, 1442314860]]}, {"target": "netapp.perf7.nl.sdt-7dot1a.cifs.vscan.sdt-vfiler1.scanrequests_completed", "datapoints": [[0.7, 1442314440], [0.533333333333333, 1442314500], [0.7, 1442314560], [0.644067796610169, 1442314620], [0.737704918032787, 1442314680], [0.716666666666667, 1442314740], [0.683333333333333, 1442314800], [0.593220338983051, 1442314860]]}]

**Comment by maddenca** [comment]
I realized that singlestat seems to want only a single series as input.  If you give it more than one, as in my example above, it only evaluates the data points in the first series and silently discards any additional series.  So the NA is when the 1st series was exclusively nulls, and it had a value when some of them were not nulls.  The values in the 2nd series were never even looked at.

Apparently I have been using singlestat incorrectly for a while, oblivious that it was silently discarding metrics.  I can use a workaround using graphite maxSeries/minSeries/averageSeries so that the panel has only one input series, but maybe singlestat should accept multiple series as input?  Or if that is not desired, maybe it could error if multiple series are passed so the graph designer knows he's doing something that won't work as expected?

**Comment by torkelo** [comment]
You right singlestat should probably show an error if a query returns more than one series.

**Comment by utkarshcmu** [comment]
PR - #2817

**Comment by utkarshcmu** [comment]
Scenario:
My query is same for Single Stat and the Line Graph shown below:

<img width="1287" alt="screen shot 2015-09-24 at 9 37 52 am" src="https://cloud.githubusercontent.com/assets/1019609/10065303/606568aa-62a1-11e5-8835-1bd7d2cf46bc.png">

In the warning message I return the number of series returned from the query, so that will help in debugging the query. 

What do you guys think, whether should we show this as an error or just a warning because there will be other graphs on the dashboard too? Let me know what you guys think, I'll make the changes as needed.

**Comment by maddenca** [comment]
@utkarshcmu, Great you are working on this!  Can you instead throw the error message in the panel itself in a similar way to this?
![image](https://cloud.githubusercontent.com/assets/917241/10075654/24f2bba2-62d7-11e5-8ad6-6ec0cb70f784.png)

**Comment by utkarshcmu** [comment]
Update:

Here are some previews:

<img width="213" alt="screen shot 2015-09-24 at 11 13 45 pm" src="https://cloud.githubusercontent.com/assets/1019609/10081409/7308f3ac-6312-11e5-98db-76f37b32ed52.png">

<img width="1008" alt="screen shot 2015-09-24 at 11 13 52 pm" src="https://cloud.githubusercontent.com/assets/1019609/10081415/778ccb74-6312-11e5-98dd-3df4705b68dc.png">

<img width="961" alt="screen shot 2015-09-24 at 11 16 53 pm" src="https://cloud.githubusercontent.com/assets/1019609/10081421/7b39e6a8-6312-11e5-9dba-fd084544112d.png">

What do you guys think about this? PR is #2817

**Comment by maddenca** [comment]
I like it!

**Comment by utkarshcmu** [comment]
Then lets ping grafana's master. @torkelo ping :)
What is your opinion on this fix?
