### ISSUE TITLE
grafana 7.1, ES group by doesn't work

### ISSUE THREAD

**Issue by YiGene** [grafana/grafana#27468]
this can be reproduced from grafana link as well
https://play.grafana.org/d/000000030/elasticsearch-custom-templated-query?orgId=1&var-host=server1&var-host=server2 

ElasticSearch - Custom Templated query, if we choose host server1+server2 then the dashboard should only show these 2 servers, but acutally it is showing all servers
![image](https://user-images.githubusercontent.com/14907021/92568119-450f8680-f2b1-11ea-911c-a5eb73ae98cd.png)

the old version of grafana do not have this issue

**Comment by torkelo** [comment]
Works fine when I test 

![Screenshot from 2020-09-09 10-07-45](https://user-images.githubusercontent.com/10999/92572159-5bebb400-f284-11ea-9ad2-07065c661be8.png)

https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?orgId=1&var-source=All&var-host=server%2020&var-host=server-5

**Comment by YiGene** [comment]
thanks torkelo, i find the reaon, we need set the min doc count to 1 when we add term group by
