### ISSUE TITLE
Add support for GCP Filestore

### ISSUE THREAD

**Issue by tomer-amir** [grafana/grafana#27471]
**What would you like to be added**:
Support for GCP Filestore monitoring

**Why is this needed**:
To monitor Filestore 😜 
Things like free disk space and more...

**Comment by marefr** [comment]
Can't you already do that with the [Cloud Monitoring data source](https://grafana.com/docs/grafana/latest/features/datasources/cloudmonitoring/#using-google-cloud-monitoring-in-grafana)? Please specify details for us to be able to understand feature request.

**Comment by tomer-amir** [comment]
I checked again and I think that it's called `File` for some reason which confused me...
sorry! 😅
