### ISSUE TITLE
Annotation rendering performance problem (6000+ annotations in a graph)

### ISSUE THREAD

**Issue by itsx** [grafana/grafana#27474]
**What happened**:
We have a **performance issue** with Grafana **annotations**. In our Docker dashboard we render annotations for specific docker containers events (start, stop, create). These events are loaded from Elasticsearch datasource with a query in Annotation settings of the dashboard. Normally annotations works perfect. 
Recently, one of our containers went through a continuous restarting loop and generated about **6000** events in a short period of time.
We found out, that for this case our Docker dashboard cannot handle rendering of so much annotations. It takes about **2.5 minutes to render all annotations in one graph** (we have 4 graphs).

**What you expected to happen**:
Annotations are rendered smoothly for any number of generated events (annotations).

**Anything else we need to know?**:
- Elasticsearch query used to load annotations from Elasticsearch is fast (tested in Kibana and also directly in Chrome developer tools)
- Browser jumps to 100% CPU usage during the loading of the graphs with annotations.

**Environment**:
- Grafana version: Grafana v6.5.2, Grafana v7.1.1
- Data source type & version: 
    annotations: Elasticsearch  6.0+
    metrics: Prometheus 
- OS Grafana is installed on:
    docker container (grafana:6.5.2)
- User OS & Browser:
  Ubuntu 18.04.2 LTS
  Version 84.0.4147.105 (Official Build) Built on Ubuntu , running on Ubuntu 18.04 (64-bit)
- Grafana plugins: 
- Others

Small number of annotations (timespan 24h). Everything is Ok
![annotations-okee](https://user-images.githubusercontent.com/15692136/92594713-77b28280-f2a3-11ea-8e69-c941efb72283.png)

Huge amount of annotations (timespan 7d - includes timespan when container was restarting).  One graph from the dashboard
loaded annotation after cca 2.5minutes, other graphs are still loading: 
![annotations-graph1ee](https://user-images.githubusercontent.com/15692136/92594835-b0525c00-f2a3-11ea-9896-16200fd2064c.png)

**Comment by torkelo** [comment]
yes, annotations rendering is a bit slow, but not designed for these many as well.

You can limit annotation counts using a size property in your annotation query

**Comment by torkelo** [comment]
We are working on new graph panel/components that will be much faster as well that should improve a lot on the current performance
