### ISSUE TITLE
please make log y-axis working with negative transform

### ISSUE THREAD

**Issue by aleks-mariusz** [grafana/grafana#2747]
I understand that by definition, logarithmic scales only support positive values however is there any way to make a tweak so that when using negative transform with the way logarithmic scales are implemented so you can see a positive logarithmic scale and a negative logarithmic scale ?

**Comment by aleks-mariusz** [comment]
Wanted to expand on this @torkelo , explaining my use case to hopefully provide more focus on this feature requests.  Currently, for graphs that have two metric "directions' (in/out traffic, read/write data, etc), i plot one "direction on the first axis" and plot the second "direction" on the 2nd axis with a negative transform function.  That way i can have data in one directino "upwards" and data in the other direction "downwards" (since they are zero minimum but zero is at the top of the graph on the 2nd axis).

What i'd really like to do is use logarithmic scale for stuff like traffic, data reads.. however this only works with the first axis (since they have all positive values).  If i try to do it on the second axis (which have positive values transformed into negative values), it hides all the values since logarithmic scale can only be positive (and my values are/were originally positive)..

So what i would like as a feature request (or a bug fix, dependign on how you look at it), is to have the negative y-axis transform work in conjunction with logarithmic scale please.

**Comment by RichiH** [comment]
@aleks-mariusz please have a look at https://github.com/grafana/grafana/issues/3619 ; I suspect that's what you want but confirmation would be appreciated.

**Comment by aleks-mariusz** [comment]
It sounds like it would work but real test will be to test it to see if it enables the use of log scale with negative transformed values, which is what i'm mainly after.

**Comment by RichiH** [comment]
The point is to calculate a normal logarithm and then flip the axis.

From what I can tell, you don't want a negative logarithm, you just want a logarithm the result of which is transformed into negative values..

**Comment by aleks-mariusz** [comment]
correct.. thanks

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3619 should solve it

**Comment by zolop** [comment]
Is this really solved? I am using grafana-3.0.0-beta41460495445 with elastic search. When I create chart with two metrics, set "Transform: negative-Y" on one of them and set scale to log, I don't see the chart with negative values, because y axis starts at 0.

**Comment by hryamzik** [comment]
@zolop nope, only stacking is implemented.

**Comment by frymaster** [comment]
@torkelo this does not appear to be solved, any chance of reopening?

**Comment by rewwade** [comment]
I think everyone knows that the logarithm of a negative number is not possible, however we're not actually doing pure math here. Consider it rather as "the logarithm of the magnitude of the distance of the point below the X axis for the purpose of display only".

Within narrower bounds of definition the solution isn't exactly difficult.

```
if raw_y >= 0:
    fin_y = log(raw_y)
else
    fin_y = -1 * log(abs(raw_y)
```

**Comment by rewwade** [comment]
I think everyone knows that the logarithm of a negative number is not possible, however we're not actually doing pure math here. Consider it rather as "the logarithm of the magnitude of the distance of the point below the X axis for the purpose of display only".

Within narrower bounds of definition the solution isn't exactly difficult.

```
if raw_y >= 0:
    fin_y = log(raw_y)
else
    fin_y = -1 * log(abs(raw_y)
```

**Comment by wrossmann** [comment]
I think everyone knows that the logarithm of a negative number is not possible, however we're not actually doing pure math here. Consider it rather as "the logarithm of the magnitude of the distance of the point below the X axis for the purpose of display only".

Within narrower bounds of definition the solution isn't exactly difficult.

```
if raw_y >= 0:
    fin_y = log(raw_y)
else
    fin_y = -1 * log(abs(raw_y)
```

**Comment by brianclemens** [comment]
@torkelo This is definitely not solved

**Comment by mkaluza** [comment]
+1
Just bumped into that as well. I think there are few more solutions here - if we are sure we have only positive values (like events), we could have 4 axes instead of 2: left+, left-, right+, right- with '+' being positive up, and '-' beind positive down, all of them being non negative only. This way there would bo no need for any negative numbers.

How about that?

**Comment by logan893** [comment]
+1
Please reopen this issue, this is not fixed for inverted Y using log scale.

**Comment by mauriciosl** [comment]
+1 to reopen this issue

**Comment by grunzwei** [comment]
have a graph with inputs and outputs.
left inputs as positive values and used series transform to make outputs negative, so they're easily distinguishable on the same graph.
worked. yey. happy.

due to high values changed axis from linear to log2. 
bam, all values went back to being positive. boo. sad.

this is 100% broken, and very annoying:
so either you see the graph linearly, or you give up on the negative transform, or you make the query do the negative values and log, but lose clarity and meaning in the axis...

tried the different solutions involving stacks - not helpful. also, i don't want to stack anything.

**Comment by odiraneyya** [comment]
This kinda sucks.
