### ISSUE TITLE
Ability to clone existing user along with access rights

### ISSUE THREAD

**Issue by blindrood** [grafana/grafana#27473]
We have multiorganisational grafana installation. Whenever new user appears I have to create one and then go through all organisations and add user to these, then add to specific group/team. I'd like to have it simplified. Either via copy existing user or maybe by creating predefined templates with accesses to all organisations

**Comment by marefr** [comment]
Thanks, but this should be pretty straight forward to implement by using the Grafana HTTP API and not a feature we need to build into Grafana.
