### ISSUE TITLE
Index with Weekly-Pattern breaks Alerts

### ISSUE THREAD

**Issue by gellweiler** [grafana/grafana#27485]
Hi, we encountered the following issue in our environement. This may be releated to this [issue](https://github.com/grafana/grafana/issues/12731).

We have an elastic data source with a weekly index pattern. That works fine for creating visualizations. However it does not work with alerts.

![Bildschirmfoto 2020-09-09 um 22 19 14](https://user-images.githubusercontent.com/3253331/92649043-b61f6000-f2ea-11ea-966a-5bb7aa5036f1.png)

If you click on the "Test Rule" button in an alert section you can see that the index is complete garbage:

![Bildschirmfoto 2020-09-09 um 22 19 08](https://user-images.githubusercontent.com/3253331/92649235-fed71900-f2ea-11ea-81c7-7e876b1e2a0e.png)

When we change the index pattern to one without a weekly pattern:

![Bildschirmfoto 2020-09-09 um 22 26 15](https://user-images.githubusercontent.com/3253331/92649552-80c74200-f2eb-11ea-98b9-5684e1c957ed.png)

Everything works fine (the "Test Rule" button works and we receive alerts):

![Bildschirmfoto 2020-09-09 um 22 27 29](https://user-images.githubusercontent.com/3253331/92649753-cbe15500-f2eb-11ea-804d-c3a8d657038b.png)

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Some Linux?
- User OS & Browser: Mac OS & Firefox
- Grafana plugins: ?

Thank you for developing and supporting this great open source app.

Appologies if this is a duplicate of an already reported issue, I was'nt able to find an existing bug report.

Greetings

Sebastian

**Comment by marefr** [comment]
Confirmed bug. Somewhat an edgecase that we haven't taken into account. If anyone is interested in contributing a fix for this that would be helpful. 

This is the date formatting function that needs changes: https://github.com/grafana/grafana/blob/ee91fc365e8f2e66ab8890b49d0eb026d42b971d/pkg/tsdb/elasticsearch/client/index_pattern.go#L249
Here's related tests: https://github.com/grafana/grafana/blob/master/pkg/tsdb/elasticsearch/client/index_pattern_test.go

**Comment by tomdaly** [comment]
hey @marefr I'd be interested in picking up this ticket, is the issue that the function only expects `[*]pattern` or `pattern[*]`, and the edge case is having multiple `[]` brackets in one string?

**Comment by marefr** [comment]
@tomdaly yes exactly.
