### ISSUE TITLE
Dashboard Level Datasource

### ISSUE THREAD

**Issue by jsabin** [grafana/grafana#2748]
When developing a new product, we use dashboards in a development environment. When the product is put in production (hosting model), we switch our dashboards from a development datasource to a production datasource. It would be nice to be able to do this on a per dashboard level rather than having to change each graph in every dashboard.

Perhaps this request could be fulfilled using this feature request:
Datasource as variable? #816

**Comment by torkelo** [comment]
not ideal, but a temp work around, export the dashboard as json, search replace in editor, then import it :)

**Comment by jsabin** [comment]
That's yucky.

One thought I had is for each graph you could specify a data source or specify "dashboard data source". Then in the dashboard properties you could specify a data source.

**Comment by jozic** [comment]
+1

**Comment by utkarshcmu** [comment]
+1 

I agree its not an ideal case but it can be a good feature if we can set datasource on the dashboard level.

**Comment by utkarshcmu** [comment]
@torkelo I think this can be a really useful feature. Here are the use cases:
1. Testing multiple datasources behind Grafana.
2. If one datasource dies, then we do not have to go to each and every panel and change the name of the datasource. We can just go to dashboard settings and change the datasource for the whole dashboard. [I know we can always change the datasource URLs etc in the datasources].
3. When running a backup datasource and a single switch can point to the other datasource. 
4. May be two different datasources show views of two different systems but have same queries.

In all these cases, this feature will be useful. Are u willing to accept a PR which implements this feature?

**Comment by feraudet** [comment]
+1
Really need this feature

**Comment by torkelo** [comment]
New template variable is now available (Data source)
![image](https://cloud.githubusercontent.com/assets/10999/14895241/f756942e-0d77-11e6-910a-091c0c470caf.png)

You pick the data source type and the variable will be automatically populated with all your data sources of that type. You can also provide a regex filter. When you add a new data source it will be automatically available in the variable values dropdown (if it passes the regex filter that is)

You can pick the variable in the panel data source selection:
![image](https://cloud.githubusercontent.com/assets/10999/14895284/279246ce-0d78-11e6-8cb5-acd25b54a9cc.png)

You can also have other query template variables use the template variable: 
![image](https://cloud.githubusercontent.com/assets/10999/14895305/4e1450c6-0d78-11e6-9d31-8d0fcf702d58.png)

**Comment by Aakansha-Talati** [comment]
Is there any way that we can provide the environment variable for setting up the datasource and Dashboard while building its docker container? I do not find any environment variable available for the grafana datasource. I am using Grafana version 4.5.x. Any help is appreciated.
