### ISSUE TITLE
With OpenTSDB backend, tag value suggestions repeats the same value many times

### ISSUE THREAD

**Issue by MichaelS11** [grafana/grafana#2749]
Versions:

Grafana version: 2.1.3, commit: v2.1.3, build date: 2015-08-24 01:02:44 

OpenTSDB version [2.2.0-SNAPSHOT] built from revision 97d3950 in a MINT state, Built on Tue Sep 08 13:22:15 GMT-700 2015.

Summary:

With OpenTSDB backend, when adding a tag, the suggestion for the value field repeats the same value many times.

Details:

The Grafana being used is in proxy mode. It has a metric called oracle.general.metrics. It has 3 tags with keys: db_name, inst_id, and name. When adding the tag with the key inst_id, then click the value to get suggestions, it returns the same value many times. To get the suggestions, it issues the following query:

../api/datasources/proxy/2/api/search/lookup?m=oracle.general.metrics%7Binst_id%3D*%7D

Request 1:

Would it be possible to filter out duplicate values when presenting the suggestions to the user?

Request 2:

Would it be possible to raise or have a configuration setting to raise the limit of data returned on search queries?

Request 3:

Since there is a limit on amount of data returned for search queries, it would be helpful if it would take in account previous tags used. For example, if the tag db_name was set to mydbname and name was set to host_cpu_utilization____ already, then when looking up suggestions for inst_id, use the following query instead:

../api/datasources/proxy/2/api/search/lookup?m=oracle.general.metrics%7Binst_id%3D*,name%3Dhost_cpu_utilization____,db_name%3Dmydbname%7D

Thank you for your time!

**Comment by torkelo** [comment]
You should open an issue with OpenTSDB for 1 and 2,  

For 3 I think there already is an issue for that

**Comment by Dieken** [comment]
@MichaelS11 @torkelo 

Request 1:  this isn't a bug of OpenTSDB, notice the output below,  it contains an array of different *tsuid* which has same metric name and *different* tag values,  it's Grafana's fault to not deduplicate on tag keys and values.

```
$ curl 'http://localhost:4243/api/search/lookup?m=sys.cpu' -s | /root/jsonpp.pl
{
   "limit" : 25,
   "metric" : "sys.cpu",
   "results" : [
      {
         "metric" : "sys.cpu",
         "tags" : {
            "cluster" : "default",
            "fqdn" : "172.17.0.2",
            "instance" : "0",
            "type" : "percent",
            "type_instance" : "user"
         },
         "tsuid" : "C23F10000001000001000002000002000003000005000004000015000005000014"
      },
      {
         "metric" : "sys.cpu",
         "tags" : {
            "cluster" : "default",
            "fqdn" : "172.17.0.2",
            "instance" : "1",
            "type" : "percent",
            "type_instance" : "user"
         },
         "tsuid" : "C23F10000001000001000002000002000003000005000004000015000005000020"
      },
      {
         "metric" : "sys.cpu",
         "tags" : {
            "cluster" : "default",
            "fqdn" : "172.17.0.2",
            "instance" : "2",
            "type" : "percent",
            "type_instance" : "user"
         },
         "tsuid" : "C23F10000001000001000002000002000003000005000004000015000005000025"
      },
      .........
```

Request 2:  OpenTSDB does have this feature,  you can append "&limit=1000000"  to the lookup request, default limit is 25 which is often too small.

Request 3:  Could you reference the issue here?  I would like to subscribe on that.

**Comment by Dieken** [comment]
Request 1 seems very easy to fix:

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/opentsdb/datasource.js

```javascript
    OpenTSDBDatasource.prototype._performMetricKeyValueLookup = function(metric, key) {
      if(!metric || !key) {
        return $q.when([]);
      }

      var m = metric + "{" + key + "=*}";

      return this._get('/api/search/lookup', {m: m}).then(function(result) {
        result = result.data.results;
        var tagvs = [];
        _.each(result, function(r) {
          tagvs.push(r.tags[key]);     //  !!!!! <---- use indexOf() to judge just like _performMetricKeyLookup()
        });
        return tagvs;
      });
    };
```

**Comment by MichaelS11** [comment]
@torkelo 

Could you please open this back up? Like @Dieken mentioned, request 1 and 2 are not a OpenTSDB issues.

Also would like to know where request 3 is at, if you would be so kind?
