### ISSUE TITLE
how to set up a table dashboard with multiple columns

### ISSUE THREAD

**Issue by YiGene** [grafana/grafana#27496]
i tried to use the table plugin but it only show 1 column.

compared to this one from the play site:  https://play.grafana.org/d/12bP2ddWz/server-details?orgId=1
is this actually a table plugin?

server-details
![image](https://user-images.githubusercontent.com/14907021/92696985-47d7ad80-f37d-11ea-9557-9d90119eb318.png)

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

You can see here that the panel to the right is a table panel: https://play.grafana.org/d/12bP2ddWz/server-details?editPanel=3&orgId=1. To the left is graph panel.
