### ISSUE TITLE
Allow saving query to be reused in multiple panels and dashboards

### ISSUE THREAD

**Issue by mraja-zume** [grafana/grafana#27490]
**What would you like to be added**: Save a query with variables that can be selected when designing new panel

**Why is this needed**: We create dashboards for different level of users in factory. Two dashboards may have 20-90% same information.
At the time of creation, we have to create/copy-paste same query in the panel
At the time of change, we have to remember all places same query is used and then change it. If it was a template then changing in one place would change everywhere.
Additionally you could show where the query is used.

**Comment by marefr** [comment]
Duplicate of #27491
