### ISSUE TITLE
Allow math on Transformed values

### ISSUE THREAD

**Issue by mraja-zume** [grafana/grafana#27492]
**What would you like to be added**: Right I can get min, max, avg etc on query but not on transformed values. Allow math on Transform series. Additionally, show transformed data in query inspector.
![2020-09-09 15_39_51-Window](https://user-images.githubusercontent.com/53663549/92662087-f06d0b00-f2b2-11ea-924d-c42cac682e19.png)

**Why is this needed**: So we can get same advantage we get on query and effectively use transform.

**Comment by torkelo** [comment]
Strange that should work like any other series

**Comment by marefr** [comment]
Please include details of queries and transform for us to be able to investigate this.

**Comment by mraja-zume** [comment]
I did a bit more investigation and looks like math is working, but since there were a lot of nulls and 0s, avg is not being calculated. May be we should change the description to filter nulls and/or 0s.

But query inspector should show transform series as well, right?

**Comment by marefr** [comment]
Still haven't provided any details. So closing this since math is working as expected. This is somewhat related https://github.com/grafana/grafana/issues/5161.
