### ISSUE TITLE
Docs feedback: /installation/docker.md

### ISSUE THREAD

**Issue by ikkemaniac** [grafana/grafana#27506]
1) Docker images no longer seem to be named using the commit hash of branchs `master` nor `v7.2.x` but use an arbitrary/different hash-like sequence example: 
[grafana/grafana-dev:7.2.0-31b135cdpre](https://hub.docker.com/layers/grafana/grafana-dev/7.2.0-31b135cdpre/images/sha256-c7c6bc1e2d31039ad3ee85411bf6947d739f5dd10628cbcba0c5dc68d0ede338?context=explore) but it's claimed commit hash is not part of the grafana/grafana repo:
```
$ git log 31b135cd
fatal: ambiguous argument '31b135cd': unknown revision or path not in the working tree.
```

The other way proves the same:
```
$ git log grafana/master
* ee91fc365e - (grafana/master) Changelog: 7.2.0-beta1 update (#27498) (3 hours ago)
* be8bc512cb - Chore: latest.json for v7.2.0-beta1. (#27481) (20 hours ago)
* 027a11210d - Chore: change log for v7.2.0-beta1. (#27480) (21 hours ago)
* 964fb8a5b1 - Docs: What's new in 7.2  (#27462) (21 hours ago)
* b01a64e146 - Update Input.mdx (#26226) (22 hours ago)
```
None of the hashes above exist in tags on [dockerhub](https://hub.docker.com/r/grafana/grafana-dev/tags?)

2) image naming convention does not follow master branch.
example: [Yesterdays V7.2.0-beta1 release](027a11210d8f89da0a7d40110a6e4b24a3508233)  seems to be build as [grafana/grafana-dev:7.3.0-648d9af7pre](https://hub.docker.com/layers/grafana/grafana-dev/7.3.0-648d9af7pre/images/sha256-254c3bd2e10e9f92ff1d6e5fc7bccfe7967e01fbe5f30ca7fe014230c00e7a1f?context=explore)
this is based on timing, as mentioned before the naming does not contain a valid commit hash.
all subsequent builds are now carrying the `v7.3.0xxxxpre` name while i couldn't find a `v7.3.x` branch and `master` is still `v7.2.0xxxxpre`

**Comment by aknuds1** [comment]
Thanks, I've made a PR to fix the Docker docs: #27508.
