### ISSUE TITLE
Dashboard: Templating error when datasource is renamed

### ISSUE THREAD

**Issue by ikkemaniac** [grafana/grafana#27519]
**What happened**:
Dashboard throws an error when a datasource is renamed. 

The dashboard was imported from another grafana instance. It was exported to a json file using the 'external' export switch.

The correct datasource was selected. In this case it is the default datasource (did not test with non-defaults)

The datasource was renamed

When loading the dashboard the following error pops up and no data is displayed

error:
```
Templating
Template variables could not be initialized: Datasource named <original-data-src-name> was not found
```

**What you expected to happen**:
1) not fail, the datasource name should only be an attribute for the user/gui. I would expect the datasource uid to be linked
2) allow the user to change the 'template variable' somewhere in the dashboard settings. (aka show the datasource dropdown selection just like when you import the dashboard). I could not find an easy way to change it so i deleted and re-imported the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
create datasource
import templated dashboard
save dashboard
change datasource name @ `/datasources`
visit dashboard

**Anything else we need to know?**:
dashboard exported on 7.1.0-pre 
dashboard imported on 7.2.0-beta1

**Environment**:
- Grafana version: 7.2.0-beta1
- Data source type & version: InfluxDB
- OS Grafana is installed on: Linux-amd64
- User OS & Browser: Linux-amd64-FF
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
related to an old issue where Grafana does not scan and update every data source when you rename a data source:
https://github.com/grafana/grafana/issues/1664
