### ISSUE TITLE
grafana can only show data points without 24 hours from now

### ISSUE THREAD

**Issue by CBKevin** [grafana/grafana#2751]
i have this issue with Grafana 1.8 previously and I upgraded to grafana 2.1 yesterday. Same thing happened. When i set the time range to any time past the 24 hours, say 25 hours from now, no data points will display on my graphs.I double checked the storage-schema.conf file, the below is my storage-schema.conf setting, wonder if i miss any settings

[carbon]
pattern = ^carbon\..*
retentions = 1m:31d,10m:1y,1h:5y

[highres]
pattern = ^highres.*
retentions = 1s:1d,1m:7d

[statsd]
pattern = ^statsd.*
retentions = 1m:7d,10m:1y

[default]
pattern = .*
retentions = 10s:1d,1m:7d,10m:1y

[g3]
pattern = ^acq.g3*
retentions = 1s:1d,1m:7d,10m:30d

**Comment by torkelo** [comment]
Strange, no one else has reported this. 

Can you open chrome dev tools inspect the raw query to graphite and graphites response?

**Comment by Pooja2589** [comment]
@torkelo Can you please post the solution over here because even i am facing the same issue where i can see graphs for past one week in Graphite dashboard but it only shows 24 hour data in Grafana.

**Comment by torkelo** [comment]
Maybe there are nulls between each point? Try enable points ? See any thing ? What does the query inspector in metrics tab say? (Will show you raw graphite response)

**Comment by egnappahz** [comment]
I got the same problem, And I have no clue why it does that. I work with whisper files and the info is all there. it just refuses to visualise for anything larger than 24 hours.
I'll keep looking...

**Comment by egnappahz** [comment]
Never mind, found it. I leave this piece of text here to help out people that search for this problem.

Take a good look at your retention settings in storage-schemas.conf (of your carbon service), it needs to be specificly tailored for your check.
For me, the check speed was completely diffrent from my normal checks, which gave the created whisper file the wrong format. You can make "regex sections" to target your check in that conffile to do it the automatic/clean way.
Or you can resize your whispers on the fly manually to quickfix this with "whisper-resize.py" with a pattern like "15s/1y" (which is checkspeed/retention. )
