### ISSUE TITLE
TestData: Migrate TestData Query Editor to react 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#27526]
Would be really useful to migrate test data query editor to react so we can more easily add things and integrate the static data frame definition feature of https://github.com/marcusolsson/grafana-static-datasource into the testdata backend scenarios as being able to define a data frame is very useful for testing scenarios (e2e tests, dev test dashboards,  and replicating issues) 

If this query editor was in react we could also then use the new annotation support that is using the normal query editor: 

https://github.com/grafana/grafana/pull/27375

**Comment by Clarity-89** [comment]
Is it [this](https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource/testdata) datasource? I was just thinking to work on some migrations while there's not that many front-end enterprise features, so I could take a look into this.

**Comment by torkelo** [comment]
yes, there is an "embryo" of a react query editor, but not used. 

here is the angular query editor: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/testdata/query_ctrl.ts
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/testdata/partials/query.editor.html
