### ISSUE TITLE
Wrong requests in the dashboard

### ISSUE THREAD

**Issue by Thegritche** [grafana/grafana#2752]
Hello
I use a OpenTSDB datasource with this url https://opentsdb.iot.runabove.io/api/query in the http settings

But In the dashbooard I have an error because the url is changed as https://opentsdb.iot.runabove.io/api/query/api/query with a double /api/query.

Whats happend ?
How can I change this ?

**Comment by torkelo** [comment]
You must have specified the wrong URL in the Grafan data source view. 

Go the data soruce edit view and specify the correct root OpenTSDB url

**Comment by Thegritche** [comment]
OK 
I put only https://opentsdb.iot.runabove.io/api/query in the data source edit and now in the inspector I have the good one url  https://opentsdb.iot.runabove.io/api/query
But the dashboard give me a data request error and nothing is show in the response tab
![graf1](https://cloud.githubusercontent.com/assets/11075303/9935372/84dbeab0-5d56-11e5-81b0-6d791f90d96f.png)
and
![inspect1](https://cloud.githubusercontent.com/assets/11075303/9935387/9fc3944a-5d56-11e5-9a82-1bdcc4b7c28e.png)

**Comment by torkelo** [comment]
https://opentsdb.iot.runabove.io/api/query is not the correct ROOT url, you should enter ROOT url of your OpenmTSDB install
