### ISSUE TITLE
Elasticsearch: Disable alias field for queries that do not have date histogram 

### ISSUE THREAD

**Issue by tatdatpham** [grafana/grafana#27521]
**What happened**: 
Alias is not working without Date Histogram in query

**What you expected to happen**: 
Alias work without time series is set or not

**How to reproduce it (as minimally and precisely as possible)**:
Alias is not working without Date Histogram
![vgca-01](https://user-images.githubusercontent.com/3429970/92808838-48585e80-f3e6-11ea-8502-466798b21f40.png)

But if i set Date Histogram, alias worked
![vgca-02](https://user-images.githubusercontent.com/3429970/92808910-56a67a80-f3e6-11ea-9538-2ee46b3b1276.png)

**Anything else we need to know?**:
I try to join/merge beetween 2 query in to single table with field "org.L", but two query have same field "Count" (alias is not worling) so join/merge transformations is wrong. It show two column (org.L, count) instead of (org.L, Total A, Total B)

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: ES 7.9.0
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome latest
- Grafana plugins: Table Panel
- Others:

**Comment by torkelo** [comment]
The alias field is only used for time series (date histogram queries). For non time-series results, there are no aliasing options. 

You can use the "organize fields" transform to rename a fielod

**Comment by tatdatpham** [comment]
> The alias field is only used for time series (date histogram queries). For non time-series results, there are no aliasing options.
> 
> You can use the "organize fields" transform to rename a fielod

Thank for your response!

I try to use "**organize fields**" in transform, but it doesn't work because it's still only one field **count** instead of 2 two. **count** 

![vgca](https://user-images.githubusercontent.com/3429970/92882829-7b2c4200-f43a-11ea-909f-6d98daee7733.PNG)

Have anothe war to work around that?

**Comment by torkelo** [comment]
ah, you have two queries. Dam, need to make join handle duplicated field names (add number or something to make them distinct)

**Comment by tatdatpham** [comment]
> ah, you have two queries. Dam, need to make join handle duplicated field names (add number or something to make them distinct)

Here is my query: 
![image](https://user-images.githubusercontent.com/3429970/92890624-7b7c0b80-f441-11ea-8ea9-5b2b67d5c5e2.png)

> add number or something to make them distinct
I don't really understand what your mean.

**Comment by aocenas** [comment]
@torkelo 

> ah, you have two queries. Dam, need to make join handle duplicated field names (add number or something to make them distinct)

Is there existing issue or PR for this so we can link it here. At the same time if this is solved by transforms I feel like we could just remove the Alias option from the query editor so I would keep this open to decide on that later on.
