### ISSUE TITLE
Add option to Hide "Bucket Bound" in Heatmap Panel

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#27529]
**What would you like to be added**:

Can we add an option to Hide the bucket bound. "Request Rate" text in the left side.
Also, notice legend text is overlapped. A small bug, I didn't want to open a new issue.

![image](https://user-images.githubusercontent.com/43188411/92882961-157b8e00-f419-11ea-8400-debf08cc1e40.png)

**Why is this needed**:

I couldn't find an option to hide to bucket bound. Sometimes we don't need it and we may find to keep things as simple as possible.

**Comment by marefr** [comment]
Use the Data format time series instead of time series buckets. Time series buckets is only supported for certain data sources and queries, e.g. Prometheus or Elasticsearch.
