### ISSUE TITLE
Make Table Panel Great

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#27530]
**What would you like to be added**:

Hi, I think we should be able to:

* Resize row height.
* Use banded columns or banded rows.
* Set a color for each row. (not based on values.)
* Disable row/column borders (make it like logs panel.)
* Colorize a row based on a value (text or numeric) in the column (feature, cell).
*  Sort by multiple columns (sort by column A then by column B)

**Why is this needed**:

Tabular data is everywhere yet table panel is so limited.

**Comment by torkelo** [comment]
> Sort by multiple columns (sort by column A then by column B)

You can do this already (hold shift when clicking on column headers).

> Resize row height.

Might add cell & row size property (Small / medium / large) in the future . 

> Set a color for each row. (not based on values)

Not currently easy as options are defined by field/column. But possible if there is demand for this feature request  

> Disable row/column borders (make it like logs panel.)

Please create a feature request for this option. Will take it into consideration if there is enough demand. 

Closing this as options with many feature requests are problematic as they do not help us know how much demand there are for individual features

**Comment by captain47** [comment]
would love to see banded rows at least.
