### ISSUE TITLE
using staircase as an option causes mouse-over pop-up to be lagging behind cursor position

### ISSUE THREAD

**Issue by aleks-mariusz** [grafana/grafana#2754]
The little bubble that follows the metric, it lags behind if following a staircase, if the staircase is set as a series-specific option

Steps to re-produce:
1 create new graph, 
2 set up two metrics
3 under display style, set one of the metrics with a series-specific option: staircase: true
4 mouse over graph, the little bubble following the stair case metric lags by half the distance as the non-staircase metric...

likely cause: the extra points needed for staircase likely causes the mouse position calculation to be off (since it lags behind linearly by about half the width from the left edge of the graph)

See the following reproducing dashboard made from this json:

    {
      "id": null,
      "title": "reproducing issue 2754",
      "originalTitle": "New dashboard",
      "tags": [],
      "style": "dark",
      "timezone": "browser",
      "editable": true,
      "hideControls": false,
      "sharedCrosshair": false,
      "rows": [
        {
          "height": "250px",
          "panels": [
            {
              "title": "reproducing issue 2754",
              "error": false,
              "span": 12,
              "editable": true,
              "type": "graph",
              "id": 1,
              "datasource": null,
              "renderer": "flot",
              "x-axis": true,
              "y-axis": true,
              "y_formats": [
                "short",
                "short"
              ],
              "grid": {
                "leftLogBase": 1,
                "leftMax": null,
                "rightMax": null,
                "leftMin": null,
                "rightMin": null,
                "rightLogBase": 1,
                "threshold1": null,
                "threshold2": null,
                "threshold1Color": "rgba(216, 200, 27, 0.27)",
                "threshold2Color": "rgba(234, 112, 112, 0.22)"
              },
              "lines": true,
              "fill": 1,
              "linewidth": 2,
              "points": false,
              "pointradius": 5,
              "bars": false,
              "stack": false,
              "percentage": false,
              "legend": {
                "show": true,
                "values": false,
                "min": false,
                "max": false,
                "current": false,
                "total": false,
                "avg": false
              },
              "nullPointMode": "connected",
              "steppedLine": false,
              "tooltip": {
                "value_type": "cumulative",
                "shared": true
              },
              "timeFrom": null,
              "timeShift": null,
              "targets": [
                {
                  "target": "carbon.agents.grafana-play01-a.cache.queries"
                },
                {
                  "target": "carbon.agents.grafana-play01-a.cache.queues"
                }
              ],
              "aliasColors": {},
              "seriesOverrides": [
                {
                  "alias": "carbon.agents.grafana-play01-a.cache.queries",
                  "steppedLine": true
                }
              ],
              "links": []
            }
          ],
          "title": "Row",
          "collapse": false,
          "editable": true
        }
      ],
      "nav": [
        {
          "type": "timepicker",
          "collapse": false,
          "notice": false,
          "enable": true,
          "status": "Stable",
          "time_options": [
            "6h",
          ],
          "refresh_intervals": [
            "1d"
          ],
          "now": true
        }
      ],
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "templating": {
        "list": []
      },
      "annotations": {
        "list": []
      },
      "schemaVersion": 6,
      "version": 0,
      "links": []
    }

**Comment by torkelo** [comment]
Thanks for reporting this and pasting a dashboard :) Will fix soon.
