### ISSUE TITLE
Dashboard/Settings/JSON Model vs url:port/api/dashboards/uid/:uid

### ISSUE THREAD

**Issue by philfleck** [grafana/grafana#27545]
Hi,

i dont know if this behavior is pretended or not. Let me describe the problem:

I am accesing shared panels via their ids, which i automatically extract from the api `url:port/api/dashboards/uid/:uid`. When using repeated panels, only panels will show in the APIs json for a saved version of the dashboard. Once a new panel is spawned (due to the repeat), the JSON in `Dashboard-setting/JSON Model` is correctly updated the panel is shown there. But when accing it over the api for external embedding, the new panel does not show up.

I dont know if that is solveable. I usually running the newest versions within docker (dockerub grafana/grafana).

Is it pretended to work that way?
Can i save/update the dashboard from api?
Is there a differen api to retrieve the current dashboard (like it is shown within the jsonmodel)?
Is there some sort of autosave(didnt find any)? or way to setup a cronjob or similar to write-through the dashboard?

I hope there is doable solution, since our enviroment is highly automated.

So far grafana works realy great. Keep up the great work!

best -p

**Comment by marefr** [comment]
Repeating is a UI thing based on template variables which also is a UI thing so it's currently impossible to evaluate template variables in the API and return repeated panel. The only solution I can imagine is to use Headless Chrome or similar to extract the dashboard json model from the UI.

**Comment by marefr** [comment]
Please ask questions on our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by philfleck** [comment]
Sure thanks, i was not sure if it is a bug or not. Last question, and we can close it. Is there maybe a hidden flag or something, when calling the UI like `http://1.1.1.1:3000/d/xxx/yyy?orgId=1&refresh=1m` to save the dashboard, instead of manually pressing the save button.

Thanks a lot.

**Comment by marefr** [comment]
No
