### ISSUE TITLE
The "Logs" button has gone from Explore since version 7.0.6

### ISSUE THREAD

**Issue by muhmud** [grafana/grafana#27556]
**What happened**:
When I go to Explore I only get the Metrics view for logs. There used to be a button to select "Logs", so that I could see the raw logs records.

**What you expected to happen**:
An ability to see the logs, just like what was possible in version 7.0.6 & prior

**How to reproduce it (as minimally and precisely as possible)**:
Go to Explore in any version of Grafana after 7.0.6

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest docker version
- Data source type & version: Elastic Search, latest docker version
- OS Grafana is installed on: Amazon Linux 2 using docker
- User OS & Browser: Chrome on Manjaro Linux
- Grafana plugins: None
- Others: N/A

On version 7.0.6 & before:

![image](https://user-images.githubusercontent.com/7550982/92988040-a6766600-f4fa-11ea-87a7-f77285f3bbaf.png)

Since version 7.0.6:

![image](https://user-images.githubusercontent.com/7550982/92988053-c27a0780-f4fa-11ea-84ae-cfc77de04301.png)

**Comment by torkelo** [comment]
The visualization mode in explore is now determined by the query. So select metric: Logs in the elasticsearch query editor to get the logs viewer
