### ISSUE TITLE
Chained variable does not work with wildcards

### ISSUE THREAD

**Issue by rabun788** [grafana/grafana#27553]
**What happened**:
The chained variable does not work when the "All" option is picked.

**What you expected to happen**:
Using the [chained variable functionality](https://grafana.com/docs/grafana/latest/variables/variable-types/chained-variables/), I expect my "All" option to change the chained variable. 

**How to reproduce it (as minimally and precisely as possible)**:
var a is a prom query that has results and the All option is enabled.
var b is a prom query that has results and the All option is enabled.
var c is a prom query that uses both var a and var b in the same query.
<img width="1100" alt="Screen Shot 2020-09-11 at 1 20 39 PM" src="https://user-images.githubusercontent.com/5399846/92954912-474d1e80-f432-11ea-90c0-cd064650aa3d.png">
<img width="1057" alt="Screen Shot 2020-09-11 at 1 21 35 PM" src="https://user-images.githubusercontent.com/5399846/92954914-47e5b500-f432-11ea-9c46-118e69c3b40f.png">
<img width="1089" alt="Screen Shot 2020-09-11 at 1 21 48 PM" src="https://user-images.githubusercontent.com/5399846/92954913-47e5b500-f432-11ea-8547-403427c82739.png">

![grafana-variable-bug](https://user-images.githubusercontent.com/5399846/92955482-33ee8300-f433-11ea-9344-3212346a287c.gif)

**Anything else we need to know?**:
no

**Environment**:
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: prom:latest
- OS Grafana is installed on: cos image in gcp
- User OS & Browser: mac catalina 10.15.6 (19G2021) + chrome
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
Without knowing the query response of your third (envoy) variable I can't see if this is working as intended or not. Your third variable does not have multi selected, so wont change it's value unless it's still valid

**Comment by torkelo** [comment]
and if you go from selecting a specific value to All the current value is still valid so this looks like it's working as intended (as the envoy query will return the current value when you go from specific value to All)

**Comment by torkelo** [comment]
will re-open if you have more info & I have misunderstood something. 

Example: 
A => All, A, B,C
 B => All, D, E
C ==> A=$A B=$B   , returns Muu, Buu, Duu, Euu   

If you go from specific value of A or B to All, the query C just returns more values and the current selected value is still ok

**Comment by rabun788** [comment]
my end goal is to have the envoy_cluster_name to look like `"__fe_.*}__svc_.*"`.

Do you have another way to do this?

**Comment by torkelo** [comment]
Sure just use you two first variables and skip the third

**Comment by torkelo** [comment]
Or define a custom/constant variable.

Your last variable is also a query so will never look like that, will fetch labels based on the regex
