### ISSUE TITLE
Grafana date filter is taking future to old date.

### ISSUE THREAD

**Issue by karamjeetkaurpreeti** [grafana/grafana#27569]
**What happened**:Date filter is not coming correct

**What you expected to happen**:Date should be select in right way

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:chrome and development
- Grafana version:6.2
- Data source type & version:sql server 2017
- OS Grafana is installed on:winodws
- User OS & Browser:
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/69211669/93077727-dc584d80-f6a6-11ea-9beb-11cbf37bb63f.png)
![image](https://user-images.githubusercontent.com/69211669/93077752-e7ab7900-f6a6-11ea-8f7b-4476412663fd.png)

**Comment by papagian** [comment]
Sorry, I don't fully understand the problem. Can you describe in more detail what are you trying to achieve and what is the unexpected behaviour? Do you mean that you can select a To date that is prior to the From date?

**Comment by karamjeetkaurpreeti** [comment]
Do you mean that you can select a To date that is prior to the From date?-Right

**Comment by papagian** [comment]
Closing this, since it does not break anything selecting a wrong time range (only the graphs will no contain any data)
