### ISSUE TITLE
Unable to Add Local InfluxDB 2.0 as Data Source

### ISSUE THREAD

**Issue by rajivenkatesh** [grafana/grafana#27560]
**What happened**:

Unable to add local InfluxDB v 2.0 as data source.

**What you expected to happen**:

Successfully establish a connection.

**How to reproduce it (as minimally and precisely as possible)**:

[Check this post for details]( https://community.grafana.com/t/trouble-adding-influxdb-2-0-as-datasource/36490)

Have latest Influx db v 2.0 in LXC 1 and latest grafana in LXC 2, running on default ports in proxmox server. No firewall rules in place to block connectivity between containers. Tried to add influx as source in grafana and instantly displayed "Error reading InfluxDB" upon clicking 'Save & Test'. (Also tried with InfluxDB Azure instance and getting the same result).

[Screenshot](https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/3/3eaa93db342cde2e24fac1d2e6547877a5093caf.png)

HTTP Request Payload
`{"datasource":{"id":1,"orgId":1,"name":"InfluxDB","type":"influxdb","typeLogoUrl":"","access":"proxy","url":"http://influx.cosmos:9999/api/v2","password":"","user":"","database":"","basicAuth":true,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":true,"jsonData":{"defaultBucket":"temp","httpMode":"POST","organization":"Infiverse","version":"Flux"},"secureJsonFields":{"token":true},"version":16,"readOnly":false},"id":1,"message":"Datasource updated","name":"InfluxDB"}`

HTTP Response
`{"results":{"test":{"error":"parse error on line 1, column 1: bare \" in non-quoted-field","refId":"test","series":null,"tables":null,"dataframes":null}},"message":"parse error on line 1, column 1: bare \" in non-quoted-field"}`

**Anything else we need to know?**:

**Environment**:
- Grafana version: `Grafana v7.1.5 (9893b8c53d)`
- Data source type & version: `InfluxDB Version 2.0.0 (50964d7)`
- OS Grafana is installed on: ` Ubuntu 20.04 LTS`
- User OS & Browser: `Microsoft Edge - Version 86.0.622.11 (Official build) beta (64-bit)`
- Grafana plugins: `None`
- Others:

**Comment by papagian** [comment]
The connection UTL should be: `http://localhost:9999` instead of `http://localhost:9999/api/v2`.
