### ISSUE TITLE
Feature Idea: Scrollable Table Legends

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#2756]
For panels with many series, especially those that benefit from the table legend, the ability to have a scrollable legend can keep dashboards tidy and condensed.

For example, this panel height is unnecessarily high to support the legend: 
![image](https://cloud.githubusercontent.com/assets/2886187/9918876/73810ac6-5c97-11e5-8260-97a3a97ce020.png)

To mitigate this, adding the ability to scroll within the legend could help immensely. This would be especially useful where the legend data does not need always be seen - but can be access easily. 

![image](https://cloud.githubusercontent.com/assets/2886187/9918962/ed4bfcc6-5c97-11e5-883a-e51a57367b69.png)

**Comment by tmonk42** [comment]
https://github.com/grafana/grafana/issues/1277

**Comment by mattttt** [comment]
@tmonk42 Ack, I'll close this and add a +1 to that. Thanks!
