### ISSUE TITLE
InfluxDB 9.4 TOP fuction

### ISSUE THREAD

**Issue by jgerschk** [grafana/grafana#2757]
Is there an open issue to add support within the Query Editor for this function now that 9.4 is out and this is available in that version?

I did not see an issue specifically related to the editor -- but discussion on the usage of the top function only.

**Comment by torkelo** [comment]
I do not think the TOP function works great for graphing, since it only sorts and limits Nr points in each time bucket. But will add it. 

https://github.com/grafana/grafana/issues/2721

**Comment by jgerschk** [comment]
@torkelo Thanks!  While I agree from a graphing point of view it does, however if we do get the table view feature, it might make sense then to have it for table views.  Just thinking out loud.  

Thanks again for all the work done on this amazing product.
