### ISSUE TITLE
Heatmap sometimes shows incorrect value in tooltip.

### ISSUE THREAD

**Issue by mplzik** [grafana/grafana#27571]
![heatmap-issue](https://user-images.githubusercontent.com/4592597/93078225-6c3bce80-f68a-11ea-81cc-809569630de5.gif)

**What happened**:
Heatmap is showing tooltips that don't correspond to the cell color -- e.g. a colored cell doesn't show any tooltip and the brightest cell shows smaller number than a cell adjacent to it. In some cases, an empty cell shows a tooltip with a value.

**What you expected to happen**:
Tooltip values should correspond to the current cell's state.

**How to reproduce it (as minimally and precisely as possible)**:
Non-deterministic. This happens randomly -- in some cases I was able to get proper values. Might be somehow related to handling of (I didn't try fixing the time, though.)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.5 (9893b8c53d)
- Data source type & version: Prometheus (cortex-backed)
- OS Grafana is installed on: Kubernetes/linux
- User OS & Browser: Google Chrome | 83.0.4103.116 (Official Build) (64-bit)
- Grafana plugins: Heatmap is the core plugin
- Others:

**Comment by papagian** [comment]
Can you share the response data from the query inspector when this happens?

**Comment by mplzik** [comment]
I'll try to capture such event and post the results here; unfortunately it seems like the query inspector is not updated along with the heatmap itself, so I'm not sure if the data I'll post will capture the right moment.

**Comment by mplzik** [comment]
I didn't manage to replicate anymore. I'll re-open this issue if I happen to have more data.
