### ISSUE TITLE
"Explore" link in panel menu not honouring root_url

### ISSUE THREAD

**Issue by tiagomotasantos** [grafana/grafana#27588]
![explore](https://user-images.githubusercontent.com/16366502/93185716-af9f4700-f735-11ea-9890-d60ff66616a8.gif)

**What happened**:
When opening "Explore" link from panel menu (with command + click to open in a new tab) the "graph" part of the URL is missing (root_url).

**What you expected to happen**:
Expected "graph" to stay in the URL.

**Environment**:
- Grafana version: 7.1.3
- User OS & Browser: macOS & Chrome

**Comment by papagian** [comment]
to reproduce you have to run grafana behind a proxy (nginx) or serve grafana from subpath like:
`GF_SERVER_SERVE_FROM_SUB_PATH=true GF_SERVER_ROOT_URL=http://localhost:3000/grafana make run`

**Comment by AlekSi** [comment]
Seems to be similar to https://github.com/grafana/grafana/issues/27226
