### ISSUE TITLE
Provisioning: editable field in dashboard yaml configuration has no effect

### ISSUE THREAD

**Issue by FireEmerald** [grafana/grafana#27585]
**What happened**:
`/provisioning/datasources/sources.yaml` and dashboard from provisioning:
![sample](https://user-images.githubusercontent.com/1107939/93172213-b3799c00-f72a-11ea-9984-522d233832a0.gif)

**What you expected to happen**:
The dashboard which was imported via provisioning should **not** be editable, if editable is set to **false**.

**How to reproduce it**:
Use the shown config in a fresh grafana setup. See [source](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards).

**Anything else we need to know?**:
Reference to #20676 (_Improve dashboard provisioning docs_).

**Environment**:
- Grafana version: 7.1.5
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome 85.0.4183.102

**Comment by papagian** [comment]
We have either to enforce editable value in the YAML to the created dashboards (by overriding the editable field inside the dashboard JSON) or to update the documentation appropriately.

**Comment by papagian** [comment]
Thank you for reporting this! Support for this was removed in d6faa3d06f606410070b38ae78fc6665836358eb. I will update the documentation appropriately.
