### ISSUE TITLE
Tag suggestion broken with new release of Opentsdb

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2758]
Opentsdb 2.1.1 was released 4 days back:
https://github.com/OpenTSDB/opentsdb/releases/tag/2.1.1

They made some changes in the lookup API and I think because of that the tag suggestion is broken in Grafana. It is not working for me. Can someone please take a look by pointing their Grafana installation to the new release of Opentsdb?

**Comment by utkarshcmu** [comment]
The tag suggestions were working for me for Opentsdb 2.1.0 version.
https://github.com/OpenTSDB/opentsdb/releases/tag/v2.1.0

**Comment by utkarshcmu** [comment]
Looks like someone is already tracking this:
https://github.com/OpenTSDB/opentsdb/issues/568

**Comment by torkelo** [comment]
Have you enabled OpenTSDB setting `tsd.core.meta.enable_realtime_ts=true`

**Comment by utkarshcmu** [comment]
Yes, the OpenTSDB setting is enabled. But the opentsdb's new released version broke the tag suggestions in Grafana.
