### ISSUE TITLE
Field config: implement slider editor

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#27592]
In the new graph panel, there are plenty of field config properties that are candidates to be controlled via slider editor. An example of such property is fill-opacity:

![image](https://user-images.githubusercontent.com/2376619/93195420-87214800-f749-11ea-9a08-629082dedf41.png)

Another is line width, point radius, etc.

For easier control of such properties it would be nice to have a slider type of config editor rather than using select component. 

From API perspective this would be a following method in both `FieldConfigEditorBuilder` and `PanelOptionsEditorBuilder` builders:

```
.addSlider({
  settings: {
    min: number,
    max: number,
    step: number,
  },
  ...
})
```

Settings have a similar API to `NumberFieldConfigSettings`, but the range and step are required.

TODO:
- [ ] Let @marcusolsson and plugins team know the new control is added to the API
- [ ] Include info about new API in change log

Ref #27572

**Comment by isaozlerfm** [comment]
Hi @dprokop will work on this one 👍

**Comment by dprokop** [comment]
Thanks @isaozlerfm, let me know if there is anything unclear here.
