### ISSUE TITLE
Limit Decimal Places / Precision in Y-Axis

### ISSUE THREAD

**Issue by willhughes** [grafana/grafana#2759]
It'd be great if there were a way to limit the precision of the Y-Axis.  For some reason I randomly get behavior like the attached image with 15 digits after the decimal point. 

![image](https://cloud.githubusercontent.com/assets/614319/9927293/c426d702-5d60-11e5-9731-38333de9dcb4.png)

I looked around at the other issues and the closest I can find is talking about doing this for the legend, which this isn't. 

I'm running Grafana 2.1.3 (via RPM), the counter is from Graphite.

**Comment by torkelo** [comment]
Since you have only a single series with no change, the auto detection of series min/max becomes very narrow compared to the scale of the series which causes the auto decimal precision to be out of wack. You can fix it by specifying a Grid Min value

**Comment by willhughes** [comment]
Thanks, and yes - that would be a work around. 

Controlling the decimal places shown would be handy for other scenarios too - eg for tracking integer values (write failures, visitor counts, etc) - where there's no point in having an axis that shows fractions.

**Comment by agaon** [comment]
Just encountered the same situation in Grafana 2.5, and although @torkelo workaround works, it would be nice if the Decimal selection for the legend would also work on the Y-axis.

**Comment by yehosef** [comment]
+1 - not sure how to set the minimum grid level - I see setting the min/max Y, but I don't want to do that as the value might change (eg today it's hovering steady at 1MB and tomorrow it'll be steady at 10MB)

**Comment by farzadpanahi** [comment]
Is it possible to have Y-axis with no decimals? I have a graph that is counting the number of connection attempts. So my values are like 0, 1, 2, 3, ... Decimal is irrelevant in this case. How can I make Y-axis show only integer numbers?

**Comment by hwinkel** [comment]
is there any solution for that. we also have a y-axis just counting things.

**Comment by torkelo** [comment]
One workaround can bring to set your a axis min and max

**Comment by drewhemm** [comment]
Also just want a count of objects in the y-axis, decimals have no meaning when you are counting whole items, such as server instances:

![screenshot from 2016-07-20 11-15-18](https://cloud.githubusercontent.com/assets/4614943/16983121/42e08be6-4e6b-11e6-8694-c3601a21dbb5.png)

Setting mix and max values doesn't help. The only thing which forces the alignment of values with whole numbers in the y-axis is setting the 'Scale' to 'log (base 2)':

![screenshot from 2016-07-20 11-18-14](https://cloud.githubusercontent.com/assets/4614943/16983216/ab230800-4e6b-11e6-9e59-5a935c510d7c.png)

I don't believe that is the correct solution...

**Comment by torkelo** [comment]
solved by https://github.com/grafana/grafana/pull/6051

**Comment by kbrownlees** [comment]
For anyone stumbling on this issue, the fix in #6051 appears to have been reverted (not available in 4.4.1 at least), #8187 is the new issue which currently has milestones of 4.5 & 5.0.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/6051 has nothing to do with decimal option

**Comment by kbrownlees** [comment]
You closed this issue with https://github.com/grafana/grafana/issues/2759#issuecomment-247438209 saying:

> solved by #6051

While it was not the 'solution', it appears to have been the work around while there was no solution? #8187 appears to be the actual solution, but it has not been released yet.

**Comment by scalp42** [comment]
@drewhemm did you ever figure it out?

**Comment by crawforde** [comment]
Having problems with this. Some plots have integers on the y axis. Some use decimals. All the settings appear to be the same.

**Comment by shravan-Quovantis** [comment]
> Since you have only a single series with no change, the auto detection of series min/max becomes very narrow compared to the scale of the series which causes the auto decimal precision to be out of wack. You can fix it by specifying a Grid Min value

please explain it in detail

**Comment by shravan-Quovantis** [comment]
> Is it possible to have Y-axis with no decimals? I have a graph that is counting the number of connection attempts. So my values are like 0, 1, 2, 3, ... Decimal is irrelevant in this case. How can I make Y-axis show only integer numbers?

Just put 0 in the field of decimal for y axis and apply

**Comment by kf6spf** [comment]
Having a related problem for stock price on the Y Axis ... Grafana always wants to use K donation so with decimals set to 2 I get values like 3.01K instead of 3014.34. If I set it to 6 decimals, I can get 3.01434K ... but that's not right either.

**Comment by leeoniya** [comment]
you can set Decimals: 2 and a custom `prefix:$` for the unit.

![image](https://github.com/grafana/grafana/assets/43234/69f4dad2-c88f-405c-b88f-9bbaae35c487)

![image](https://github.com/grafana/grafana/assets/43234/6bb88de2-f2b2-4d20-a2d9-cf2cf5192644)

**Comment by kf6spf** [comment]
Ah! Didn't see the prefix: option. Very nice. Thanks!
