### ISSUE TITLE
Filter by Days and time ranges

### ISSUE THREAD

**Issue by amirs111** [grafana/grafana#2760]
Hi,
I wrote script that gives me averages of CPU usages, latency, etc.
Now I want to the ability to filter it by days and time ranges.
For example:
Sun-Thu + 8:00-17:00

In the Grafana there is the ability to take only the "Last X days" or hours.
In the "custom" time range, it's possible to enter a specific time range, but still not what I'm looking for.
Any idea if it's possible ?

In the JSON file these are the available options:

"nav": [
    {
      "type": "timepicker",
      "collapse": false,
      "notice": false,
      "enable": true,
      "status": "Stable",
      "time_options": [
        "15m",
        "1h",
        "6h",
        "12h",
        "24h",
        "2d",
        "7d",
        "30d"
      ],

**Comment by torkelo** [comment]
This is tricky, TSDB do not support gaps int the requested time range, it has be be a from and end date. Either absolute or relative. 

What you want to do is not only limit the query but the time axis to not show time between 17-08:00 right?

**Comment by amirs111** [comment]
Yes.
Do you know if it will be supported ?
So I guess the only option is to connect to the DB and take it from there ?
