### ISSUE TITLE
Alert not working with variable database

### ISSUE THREAD

**Issue by BastelBaus** [grafana/grafana#27608]
**What happened**:
Grafana cannot run alert rules with database given as variable
see screenshots
![grafana_bug](https://user-images.githubusercontent.com/44684710/93269085-9edee780-f7ae-11ea-8f55-c3318f8ef179.gif)

**What you expected to happen**:
Should run also with variable as database

**How to reproduce it (as minimally and precisely as possible)**:
* set up normal pannel
* configure database variable

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: influx 1.8
- OS Grafana is installed on: CentOS7
- User OS & Browser: Edge
- Grafana plugins: none
- Others: -

**Comment by torkelo** [comment]
Alet rules does not support any template variables

**Comment by BastelBaus** [comment]
Thanks a lot, I understood. Could be a future feature to allow this.
Nevertheless, great tool you have ! Thanks for all this effort you spent !
