### ISSUE TITLE
User with viewer role should be able to admin team and add members

### ISSUE THREAD

**Issue by F4ncyMooN** [grafana/grafana#27609]
**What happened**:
When upgrade grafana from 6.2.5 to 7.1.3
I found viewer can't see setting option in the left sidebar even when I grant this viewer with team admin privilege and open viewer_can_edit + editor_can_admin option in grafana.ini
And when I grant editor privilege to this user, he can add team members.

**What you expected to happen**:
Team admin with any overall privilege could add team members.

**How to reproduce it (as minimally and precisely as possible)**:
1. Grant one user to overall viewer role.
2. Grant him some team's admin role.
3. Then this user can't add team member.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.3
- Data source type & version: any
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: none
- Others:

**Comment by F4ncyMooN** [comment]
I believe it is because of code change.
https://github.com/grafana/grafana/commit/f3fb178efa95ef227fff7b5d6d2a4e5aaa37b9e7?branch=f3fb178efa95ef227fff7b5d6d2a4e5aaa37b9e7&diff=split

```
	if (c.OrgRole == m.ROLE_EDITOR || c.OrgRole == m.ROLE_VIEWER) && hs.Cfg.EditorsCanAdmin 
=>
	if c.OrgRole == m.ROLE_ADMIN || (hs.Cfg.EditorsCanAdmin && c.OrgRole == m.ROLE_EDITOR) {
```

**Comment by torkelo** [comment]
Do not think this is a bug, editor_can_admin still require editor role

**Comment by F4ncyMooN** [comment]
So team admin requires overall admin privilege to add members?

**Comment by torkelo** [comment]
editor should be enough

**Comment by F4ncyMooN** [comment]
I think if one user is team admin, he should add team even no matter he is viewer or editor.
There should be 3 ways to show this setting icon:
1. is admin
2. is editor + editor_can_admin
3. is team admin
