### ISSUE TITLE
Unsaved changes warning after variable drop-down values changed

### ISSUE THREAD

**Issue by RobotLimeLtd** [grafana/grafana#27613]
**What happened**:
Navigating to a new dashboard after using another causes a prompt to save the previous dashboard, even though the only "change" is a selection from a drop-down filter.

**What you expected to happen**:
Unless I've actually changed the dashboard settings or edited the values/config of a panel, I simply expect the next dashboard to load without any prompt to save.  The prompt to save should not appear through normal use of the filters I've created.

**How to reproduce it (as minimally and precisely as possible)**:

1. Navigate to a dashboard that has one or more drop-down selectors (configured via "variables" in the dashboard settings) that filter the dashboard view.
1. Change the value in one of the drop-down selectors to filter the dashboard view (e.g. a server name).
1. Try to open a different dashboard.

**Anything else we need to know?**:

All our dashboards are provisioned, which makes the save prompt somewhat redundant anyway.

**Environment**:
- Grafana version: 7.1.2
- Data source type & version:  Prometheus 2.21.0, AlertManager 2.21.0
- OS Grafana is installed on:  RedHat 7
- User OS & Browser:  macOS / Google Chrome
- Grafana plugins:  Alertmanager
- Others: n/a

**Comment by torkelo** [comment]
Try saving the dashboard. It could be that the panels / dashboard have old schema. Some schema changes are executed during panel load. 

We hope to improve dirty checking: https://github.com/grafana/grafana/issues/24663

**Comment by RobotLimeLtd** [comment]
Dashboards are provisioned, so we can't save them.   Did you mean "save" or "export"?
