### ISSUE TITLE
Explore OpenTSDB: React error when populating metric name from auto-complete

### ISSUE THREAD

**Issue by neilfordyce** [grafana/grafana#27618]
**What happened**:
Explore gets a React error when I click on a metric from an OpenTSDB datasource `An unexpected error happened`
```Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7Bcode%2C%20message%2C%20details%2C%20trace%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.```

![grafana-opentsdb-explore-bug](https://user-images.githubusercontent.com/2376906/93334736-501c6680-f81d-11ea-8eb3-6b2f6df8f006.gif)

**What you expected to happen**:
Clicking auto-complete metric populates metric name field with metric and executes query.  

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to /explore 
1. Pick an OpenTSDB data source from the data source drop-down
1. Put cursor in the “metric name” field
1. Start typing metric and with metric name partially complete pick one of the entries from auto-complete
1. Get a React error

**Anything else we need to know?**:
It executes an OpenTSDB query without filling in the value of the metric from the auto-complete, resulting in a HTTP 400.  It seems like it maybe failing to map that to the UI properly.  

**Environment**:
- Grafana version: Tested in 7.2.0-beta1 and 6.7.4
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on: Alpine docker images
- User OS & Browser: Mac OS Catalina & Firefox 
- Grafana plugins: None
- Others:

**Comment by papagian** [comment]
I'm unable to reproduce exactly this but if I type a non existing metric which results in `"No such name for 'metrics':` 400 error response then I get the following error:
`Uncaught Error: Objects are not valid as a React child (found: object with keys {code, message, details, trace}). If you meant to render a collection of children, use an array instead.`

**Comment by mengxuexue** [comment]
I met the same problem. Do you know the reason？
