### ISSUE TITLE
Grafana is not showing data with Elasticsearch, Filebeat, Logstash and Grafana.

### ISSUE THREAD

**Issue by coolgooseman** [grafana/grafana#27619]
**What happened**:
I setup Elasticsearch together with Filebeat, Logstash and Grafana. I will include the yml file used at the end of the issue.

**What you expected to happen**:
I expected the Grafana to make the dashboards.

**How to reproduce it (as minimally and precisely as possible)**:
By having the same setup as me.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Elasticsearch 7.9.1 / Logstash 7.9.1 / Filebeat 7.9.1
- OS Grafana is installed on: Windows server 2019
- User OS & Browser: Windows server 2019 and Chrome
- Grafana plugins: /
- Others: /

[yml.zip](https://github.com/grafana/grafana/files/5232169/yml.zip)
![image](https://user-images.githubusercontent.com/71011796/93337939-143bce00-f82a-11ea-861c-bed8148ec58a.png)

![image](https://user-images.githubusercontent.com/71011796/93337973-1d2c9f80-f82a-11ea-9dd9-9a5a5fb2dd09.png)
![image](https://user-images.githubusercontent.com/71011796/93338013-2ae22500-f82a-11ea-97fc-b390cec95970.png)

**Comment by torkelo** [comment]
use query inspector to show raw response from Elasticsearch

**Comment by coolgooseman** [comment]
I will do that tomorrow when i have acces to my computer again

**Comment by coolgooseman** [comment]
![image](https://user-images.githubusercontent.com/71011796/93428763-4dbf1880-f8c0-11ea-91db-a1d7a877273c.png)

**Comment by torkelo** [comment]
No result from elasticsearch. So not sure what could cause that. Does indices exist? is the timestamp field correct?

**Comment by coolgooseman** [comment]
Not sure what you mean by both. Sorry im relatively new to all of this.

**Comment by torkelo** [comment]
It does not look like you have any data in your indices, or they do not exist,  Elasticsearch is not returning any data

**Comment by coolgooseman** [comment]
There is data in the logs. I think this means that there is an issue with Logstash retrieving them and sending them to Elasticsearch.
