### ISSUE TITLE
Update process start grafana service everytime

### ISSUE THREAD

**Issue by Rohlik** [grafana/grafana#27611]
**What happened**:
When I updating Grafana via `yum` or `rpm` command it will try run Grafana service during post-install process even when it was disabled and stopped before I initiated the update command.

**What you expected to happen**:
If Grafana service is not running before update process then it should not be started during post-install procedure.

**How to reproduce it (as minimally and precisely as possible)**:
`service grafana-server stop` - Grafana is stopped now.
`yum update -y grafana`
`service grafana-server status` - Grafana is running.

**Anything else we need to know?**:
Sometimes, for example in our environment, is Grafana service managed by cluster and it is not suitable to be start automatically during package update process.

**Environment**:
- Grafana version: 7.1.5
- OS Grafana is installed on: RHEL7

**Comment by torkelo** [comment]
you can control this by changing RESTART_ON_UPGRADE in sysconfig 

https://github.com/grafana/grafana/blob/master/packaging/rpm/sysconfig/grafana-server#L17

**Comment by Rohlik** [comment]
Thank you.
