### ISSUE TITLE
Grafana returns Invalid API key with Authorization headers

### ISSUE THREAD

**Issue by githubcdr** [grafana/grafana#27617]
**What happened**:

Grafana is always throwing error "message": "Invalid API key" when a Authorization header is added to the request. I'm missing an option to tell Grafana to ignore this header.

**What you expected to happen**:

I'd expect Grafana to ignore this header when not explicitly configured to do authentication.

**How to reproduce it (as minimally and precisely as possible)**:

```
docker run -d -p 3000:3000 --name grafana grafana/grafana

$ curl -H "Authorization: Bearer yodo" http://127.0.0.1:3000
{"message":"Invalid API key"}
```

**Anything else we need to know?**:

I tried with disable auth.basic, but I always get this result.

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: docker
- OS Grafana is installed on: docker
- User OS & Browser: Opera
- Grafana plugins: none
- Others:

**Comment by Morriz** [comment]
And even when it would be configured to handle auth, could it not transparently use the JWT without verification? we have a SSO solution up front (Istio) that validates the token already. The receiving service should be configurable to use it as is imo.

**Comment by papagian** [comment]
Can you provide some use cases that this would be useful?

**Comment by Morriz** [comment]
Is my SSO "termination" use case not telling enough? Why would we want microservices to each be configured to talk to an idp when we have an auth proxy? Wasteful

**Comment by papagian** [comment]
@Morriz Maybe I'm missing something but if you are using an auth proxy (and it's configured to set the `X-WEBAUTH-USER`) header then you can [query](https://grafana.com/docs/grafana/latest/auth/auth-proxy/#interacting-with-grafanas-authproxy-via-curl) the grafana api using that header.

**Comment by githubcdr** [comment]
@papagian in some cases I have no control of headers that are sent to Grafana.

**Comment by torkelo** [comment]
If you have a need to completely disable API keys, then that would be a new feature request

**Comment by Morriz** [comment]
> @Morriz Maybe I'm missing something but if you are using an auth proxy (and it's configured to set the `X-WEBAUTH-USER` header) then you can [query](https://grafana.com/docs/grafana/latest/auth/auth-proxy/#interacting-with-grafanas-authproxy-via-curl) the grafana api using that header.

I wish to only use oidc as that is becoming more of a standard I think.

I would start seeing auth as something done up front, like mutual tls is also taken care of by sidecars/meshes. It would be nice if grafana supported oauth2 WITHOUT using it's own client to verify the JWT, and just consumes it's claims.

So may I ask why this issue is closed?

**Comment by torkelo** [comment]
It was opened as a feature request to disable api keys auth, search for that, if not then open a feature request to disable this Grafana auth feature

**Comment by arcivanov** [comment]
> And even when it would be configured to handle auth, could it not transparently use the JWT without verification? we have a SSO solution up front (Istio) that validates the token already. The receiving service should be configurable to use it as is imo.

We have an identical issue with Grafana behind istio/envoy filter/oauth2 proxy where via `AuthorizationPolicy` and `RequestAuthentication` **istio** verifies the tokens and oauth2 proxy supplies them from the request. Thus the tokens must be present per request.

I guess I could add another envoy filter specifically for Grafana to remove that Authorization Bearer header, but since nobody enabled it to begin with it's a bizarre behavior especially with authentication disabled.

**Comment by arcivanov** [comment]
Actually we solved the issue by using `VirtualService` header filters:

```
  - match:
    - uri:
        prefix: /grafana
    rewrite:
      uri: /grafana
    route:
    - destination:
        host: grafana.monitoring.svc.cluster.local
        port:
          number: 3000
      headers:
        request:
          remove:
          - Authorization
```

**Comment by Morriz** [comment]
@arcivanov @torkelo I created a separate issue for delegation of oauth to be done by a trusted proxy: #28566

**Comment by arcivanov** [comment]
@Morriz Over here we don't want to delegate OAuth to grafana. We want Grafana to be absolutely authentication-oblivious. We don't even care about authorization that much, as that part will be handled by Istio policies. We just wanted Grafana to stop caring about the Bearer token.

**Comment by Morriz** [comment]
> @Morriz Over here we don't want to delegate OAuth to grafana. We want Grafana to be absolutely authentication-oblivious. We don't even care about authorization that much, as that part will be handled by Istio policies. We just wanted Grafana to stop caring about the Bearer token.

You obviously did not read what I posted ;)

**Comment by arcivanov** [comment]
> > @Morriz Over here we don't want to delegate OAuth to grafana. We want Grafana to be absolutely authentication-oblivious. We don't even care about authorization that much, as that part will be handled by Istio policies. We just wanted Grafana to stop caring about the Bearer token.
> 
> @arcivanov you obviously did not read what I posted ;)

I did. You want `allow claims consumption without doing client lookup`. It's great, but I want even less than that - simply disregard all of the token :smile:

**Comment by Morriz** [comment]
aha, but those mechanics are already in place I reasoned, so nothing to be done there. I would not propose removing that, as it gives authn/authz for free :)

**Comment by arcivanov** [comment]
Yes, it's nice, if it works. It doesn't, so the next best thing is for it to be turned off entirely :)
