### ISSUE TITLE
Grafana-server CPU load spikes

### ISSUE THREAD

**Issue by teemuku** [grafana/grafana#27610]
**What happened**:
Grafana-server CPU Load spiking with regular intervals. Typically load stays up for about one hour, goes back to normal and spikes again after about 5 hours. Spikes begin and end without any user actions.
![grafana_load](https://user-images.githubusercontent.com/70326653/93299482-cd37e380-f7fd-11ea-8914-356ee204795c.JPG)

**Anything else we need to know?**:
During the spikes, nothing special in system journal or in Grafana logs. Grafana log level set to "debug", provides no additional information, mostly only "Start walking disk" messages.
Other metrics such as RAM/disk/cpu/network usage seem to be unaffected by this, only the load is spiking.
Grafana-server is setup with IaaC-tools and this load spiking has been present since the beginning (in a smaller scale), so no obvious or sudden cause for this. Load has increased over time, most likely as new orgs/dashboards have been added.

**Environment**:
- Grafana version: v7.1.3
- Data source type & version: InfluxDB v.1.8.0
- OS Grafana is installed on: Linux CentOS 7 VM (2 vCPUs & 8GB RAM & SSD)
- Grafana plugins: -
- Others: 
Grafana ~60 Organizations
Dashboard provisioning enabled

**Log example**:
```
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_linux_cpu path=/var/lib/grafana/dashboards/shared/linux_cpu.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_linux_memory path=/var/lib/grafana/dashboards/shared/linux_memory.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_linux_disk path=/var/lib/grafana/dashboards/shared/linux_disk.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_linux_network path=/var/lib/grafana/dashboards/shared/linux_network.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_linux_summary path=/var/lib/grafana/dashboards/shared/linux_summary.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_windows_cpu path=/var/lib/grafana/dashboards/shared/windows_cpu.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_windows_memory path=/var/lib/grafana/dashboards/shared/windows_memory.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_windows_disk path=/var/lib/grafana/dashboards/shared/windows_disk.json
Sep 16 05:38:40 grafana01 grafana-server[12682]: t=2020-09-16T05:38:40+0300 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=shared_14_windows_network path=/var/lib/grafana/dashboards/shared/windows_network.json
```

**Comment by papagian** [comment]
What is the value of `updateIntervalSeconds` (how often Grafana will scan for changed dashboards) in the dashboard provisioning? Can you try. increasing it and checking if the spike interval is affected?

**Comment by teemuku** [comment]
> What is the value of `updateIntervalSeconds` (how often Grafana will scan for changed dashboards) in the dashboard provisioning? Can you try. increasing it and checking if the spike interval is affected?

It seems to be at default value "10". Is there some reason why it's by default doing it so often? Isn't it a bit unnecessary to scan every 10 seconds. I will change the interval to scan every 5 minutes or so, and report back the results, thank you.

**Comment by papagian** [comment]
`10` is not actually a default value but just the value used in the dashboard provisioning configuration [example](https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards). We should consider changing the example to set a more realistic value.

**Comment by teemuku** [comment]
Changing the `updateIntervalSeconds` value from 10 >> 300 seems to have removed the load spikes completely, and also lowered cpu utilization. I'll check again at the end of today if there has been any spikes, if not I'll close this issue. Thanks for the help!

**Comment by teemuku** [comment]
Confirming, that `updateIntervalSeconds` tweak has resolved this issue, thanks for the help. Closing the issue.
