### ISSUE TITLE
Code Coverage to be supported with plugin build script

### ISSUE THREAD

**Issue by TheWhiteMountain** [grafana/grafana#27623]
**What would you like to be added**:
Support generating code coverage when building grafana plugin.

**Why is this needed**:
When building grafana plugin the tests are also running, but it is not possible to generate coverage. It is possible to generate coverage by running tests by using the flag --coverage, as "grafana-toolkit plugin:test --coverage". In this case in order to build and generate the coverage then we need to run both "grafana-toolkit plugin:test --coverage" and "grafana-toolkit plugin:build" which means the tests will run twice, a thing that can be avoided by supporting --coverage with the build script.

**Comment by gassiss** [comment]
Hey! This seemed to be pretty trivial so I went ahead and opened a PR. Hope that's ok!
