### ISSUE TITLE
assigned metric color lost if metric name is renamed

### ISSUE THREAD

**Issue by aleks-mariusz** [grafana/grafana#2762]
Whenever i have a bunch of colors custom picked for metrics, any time i rename the metric (or make other changes to it), the color i picked is thrown away and a new random one is assigned.

Steps to reproduce:
1. create new dashboard with below json value
2. pick a custom color
3. edit graph, metrics 'tab', change alias() parameter
4. the color is discarded and a new random one is assigned

Likely cause, treats new named metric as a different metric so assigns it a new color.
Possible solution? don't treat it as a new metric, however that needs to be done, perhaps don't assign it a new entity/object? or maintain reference to old one and realize it's not a different metric ? 

---- reproducing json ---

    {
      "id": null,
      "title": "Issue #",
      "originalTitle": "New dashboard",
      "tags": [],
      "style": "dark",
      "timezone": "browser",
      "editable": true,
      "hideControls": false,
      "sharedCrosshair": false,
      "rows": [
        {
          "height": "250px",
          "panels": [
            {
              "title": "Issue",
              "error": false,
              "span": 12,
              "editable": true,
              "type": "graph",
              "id": 1,
              "datasource": null,
              "renderer": "flot",
              "x-axis": true,
              "y-axis": true,
              "y_formats": [
                "short",
                "short"
              ],
              "grid": {
                "leftLogBase": 1,
                "leftMax": null,
                "rightMax": null,
                "leftMin": null,
                "rightMin": null,
                "rightLogBase": 1,
                "threshold1": null,
                "threshold2": null,
                "threshold1Color": "rgba(216, 200, 27, 0.27)",
                "threshold2Color": "rgba(234, 112, 112, 0.22)"
              },
              "lines": true,
              "fill": 1,
              "linewidth": 2,
              "points": false,
              "pointradius": 5,
              "bars": false,
              "stack": false,
              "percentage": false,
              "legend": {
                "show": true,
                "values": false,
                "min": false,
                "max": false,
                "current": false,
                "total": false,
                "avg": false
              },
              "nullPointMode": "connected",
              "steppedLine": false,
              "tooltip": {
                "value_type": "cumulative",
                "shared": true
              },
              "timeFrom": null,
              "timeShift": null,
              "targets": [
                {
                  "target": "alias(carbon.agents.grafana-play01-a.cache.queries, 'xyz')"
                }
              ],
              "aliasColors": {
                "bar": "#E5A8E2",
                "foo": "#962D82",
                "abc": "#705DA0"
              },
              "seriesOverrides": [],
              "links": []
            }
          ],
          "title": "Row",
          "collapse": false,
          "editable": true
        },
       {
          "title": "New row",
          "height": "250px",
          "editable": true,
          "collapse": false,
          "panels": []
        }
      ],
      "nav": [
        {
          "type": "timepicker",
          "collapse": false,
          "notice": false,
          "enable": true,
          "status": "Stable",
          "time_options": [
            "6h",
          ],
          "refresh_intervals": [
            "30s",
          ],
          "now": true
        }
      ],
      "time": {
        "from": "now-6h",
        "to": "now"
      },
      "templating": {
        "list": []
      },
      "annotations": {
        "list": []
      },
      "schemaVersion": 6,
      "version": 0,
      "links": []
    }

**Comment by torkelo** [comment]
yes, colors are stored per metric name (when you change them), the metric name is the only unique thing to associate a series by (beside its index, but that can also change depending on sorting and some tsdb return series in non deterministic order).

In graph style tab you can set series override rules, you can specify a regex override rule and set color on regex.
