### ISSUE TITLE
Pass refresh rate while navigating from one dashboard to another via dashboard links

### ISSUE THREAD

**Issue by aliaslam63** [grafana/grafana#27621]
I am currently browsing Grafana dashboard via external hyperlink which includes multiple query string parameters containing refresh rate. Once dashboard is browsed, it includes links to navigate to other dashboards. Somehow, I am able to pass multiple values(dashboard name, date range(to,from) etc) via Grafana variables to linked dashboards but unable to pass refresh rate.

**This leads to uneven configurations while navigating between different linked dashboards.I need to re adjust the refresh rate.**
**Can you please implement this request of allowing refresh rate to be passed while navigating to linked dashboards or let me know if it is already possible.**

I have found another link: https://github.com/grafana/grafana/issues/5727 . Is this same request as mine ?

**Comment by torkelo** [comment]
not sure refresh rate is a good thing to preserve, feels very specific to a dashboard. 

Closing this issue, just because it is closed does not mean it will never be implemented. It can still act as a feature request and gain +1/up votes in order to see user interest in the feature. Just means it's not something the core team plans to work on in next 1+ year. We are trying to limit the number of open issues to better manage & plan work.

**Comment by ummarbhutta** [comment]
@torkelo , Thanks for your feedback, as long as refresh is concerned I think it is quite similar to other options already available like

1. Time Range
2. Template variables (very specific to a dashboard, but still can be passed to a link URL)

The request here is to provide an additional toggle button like `Auto refresh configuration` , would be really helpful.

**Comment by PortingCode** [comment]
@ummarbhutta 
I have a similar issue.

I've got the panel A with dashboard link.
After I click the link button, the template variables won't be transferred to the dashboard directly.
I have to refresh the page of the panel A firstly. Then click the link button, the dashboard will get the  template variable.

I suppose that the template variables should be automatically transferred to the target dashboard, right?
Could you guide me how to enable the auto transfer？

Here is the details about my settings.
1. the configuration of template variable of dashboard
![image](https://user-images.githubusercontent.com/43814606/94238112-712e3700-ff42-11ea-893b-cfbc4ec8bc85.png)
2. the Auto refresh configuration of dashboard and the panel.
![image](https://user-images.githubusercontent.com/43814606/94238308-c10cfe00-ff42-11ea-94e8-5f28e835907e.png)
