### ISSUE TITLE
Stat panel in Grafana v7.1.5 shows value in case the panel title is empty

### ISSUE THREAD

**Issue by talbz** [grafana/grafana#27626]
**What happened**: Since Grafana v7.1.5, in Stat panel. In case I have a panel title - all is ok. In case I don't have panel title, the query or value appears in the panel.

**What you expected to happen**: I would expect that the value / query will not appear regardless of the existence of panel title.

**How to reproduce it (as minimally and precisely as possible)**: Create a Stat panel, define value mappings, delete the panel title and see that the query or value appears in the panel. Change the panel title to foo, and see that it returns to work as expected. 

**Anything else we need to know?**: It's new in 7.1.5 and reproduces in play.grafana.com

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Prometheus latest
- OS Grafana is installed on: Linux I assume
- User OS & Browser: MacOS, Chrome 85
- Grafana plugins: 
- Others:

Without panel title 
![image](https://user-images.githubusercontent.com/34829710/93372116-1ae33900-f85c-11ea-8205-ac3e1d0e3f84.png)

With panel title foo
![image](https://user-images.githubusercontent.com/34829710/93372145-25053780-f85c-11ea-8646-3dee8510e30c.png)

See my original report here: https://community.grafana.com/t/stat-panel-in-grafana-v7-1-5-shows-value-in-case-the-panel-title-is-empty/36648

**Comment by torkelo** [comment]
This is by design, if you want only value you can select that value in text mode
<img width="388" alt="Screen Shot 2020-09-16 at 19 46 42" src="https://user-images.githubusercontent.com/10999/93373304-752ccb80-f855-11ea-97e8-e9ed09cf971c.png">

**Comment by talbz** [comment]
Oops, sorry, RTFM. Thanks @torkelo.
