### ISSUE TITLE
Large amount of time series with a common prefixes cause "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by tomsanbear** [grafana/grafana#27631]
![The Gif](https://user-images.githubusercontent.com/4356511/93431920-c85b5880-f8ff-11ea-8d90-2ab22ca60aab.gif)

**What happened**:

As part of the performance testing of my Thanos install, I am using the [avalanche](https://github.com/open-fresh/avalanche) utility to stress test labels and time series. While running queries against the dataset, the grafana instance fails very ungracefully when doing the type ahead for the "avalanche..." metrics. In this case all the time series generated have the "avalanche" prefix.

**What you expected to happen**:

Grafana should not crash, and/or disable type ahead for large amounts of metrics.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy prometheus & grafana, scrape metrics from the avalanche container, or something else that generates large amounts of time series (was observed for over 10,000 time series). 
2. Type the letter 'a' in the explore view

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: prometheus
- OS Grafana is installed on: k8s, grafana/grafana:7.1.5 docker image
- User OS & Browser: Chrome & OSX
- Grafana plugins: N/A
- Others: N/A

**Comment by Nexucis** [comment]
Same problem with Grafana v7.2.0 :(

It would be nice, when there is such kind of error, it doesn't block the whole page. Like it would be nice to still have access to the settings of the dashboard.

**Comment by Nexucis** [comment]
It can be helpful for example to still have access to the setting in order to rollback the dashboard version to a previous one that was working before.

Instead of making multiple different query for example.
