### ISSUE TITLE
Cannot access Azure Monitor behind a proxy: Bad Gateway

### ISSUE THREAD

**Issue by gerbermarco** [grafana/grafana#27634]
**What happened**:

We use Grafana on Red Hat and plan to use the Azure Monitor plugin to query Azure Monitor. Our Grafana environment runs behind a proxy. When we want to connect to Azure Log Analytics or Application Insights we get the following error message: 
_"1. Application Insights: Bad Gateway: Cannot connect to Application Insights REST API. 2. Azure Log Analytics: Bad Gateway: Cannot connect to Azure Log Analytics REST API."_

**What you expected to happen**:

The connection to the according APIs in Azure should be successful right after clicking on "Save and test" in Grafana. So sort out any access or permission issues, we reproduced setup with Grafana Docker container running on a regular computer without proxy, where we could add the Azure Monitor data source successully with the same credentials/secret.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add Azure Monitor plugin and fill in the according information to access Azure Monitor, Log Analytics, etc.
2. Press "Save and test"
3. Error message _"1. Application Insights: Bad Gateway: Cannot connect to Application Insights REST API. 2. Azure Log Analytics: Bad Gateway: Cannot connect to Azure Log Analytics REST API."_ appears in the same window

**Anything else we need to know?**:

We have the variables HTTP_PROXY and HTTPS_PROXY set in our environment, although it seems to be ignored from Grafana. Also we don't see any hits in the proxy log, which also looks like the proxy is being ignored from Grafana. From the OS and Grafana itself we can access the internet via proxy.

**Environment**:
- Grafana version: 7.1.x
- Data source type & version: Azure Monitor
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Microsoft Windows Server 2019 Datacenter, Google Chrome Version 83.0.4103.61

**Comment by papagian** [comment]
I'm unable to reproduce it. Can you share the grafana server error logs and your proxy configuration?

**Comment by papagian** [comment]
Can you open chrome dev tools and check network tab, track the following requests and share the responses?

/grafana/api/datasources/proxy/<datasource ID>/azuremonitor/subscriptions
/grafana/api/datasources/proxy/<datasource ID>/appinsights/beta/apps
/grafana/api/datasources/proxy/<datasource ID>/loganalyticsazure/

**Comment by gerbermarco** [comment]
> I'm unable to reproduce it. Can you share the grafana server error logs and your proxy configuration?
Here's the error in the backend:
_t=2020-09-21T15:45:29+0200 lvl=info msg=Requesting logger=data-proxy-log url=https://api.applicationinsights.io/beta/apps/75dd0ccb-61a8-419f-bc6c-8be8310fb478/metrics/metadata
t=2020-09-21T15:45:40+0200 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="Post \"https://login.microsoftonline.com/67809b88-5d87-4f90-80d9-e1e87631bd35/oauth2/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
t=2020-09-21T15:45:40+0200 lvl=info msg=Requesting logger=data-proxy-log url="https://management.azure.com/subscriptions?api-version=2019-03-01"
t=2020-09-21T15:45:59+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/8/appinsights/beta/apps/75dd0ccb-61a8-419f-bc6c-8be8310fb478/metrics/metadata remote_addr=10.90.36.38 referer=https://our-lab-url.ch/datasources/edit/8/ error="http: proxy error: dial tcp 20.40.144.187:443: i/o timeout"
t=2020-09-21T15:45:59+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/8/appinsights/beta/apps/75dd0ccb-61a8-419f-bc6c-8be8310fb478/metrics/metadata status=502 remote_addr=10.90.36.38 time_ms=30055 size=0 referer=https://our-lab-url.ch/datasources/edit/8/
t=2020-09-21T15:45:59+0200 lvl=info msg=Requesting logger=data-proxy-log url=https://api.applicationinsights.io/beta/apps/75dd0ccb-61a8-419f-bc6c-8be8310fb478/metrics/metadata
t=2020-09-21T15:46:10+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/8/azuremonitor/subscriptions remote_addr=10.90.36.38 referer=https://our-lab-url.ch/datasources/edit/8/ error="http: proxy error: dial tcp 51.107.60.33:443: i/o timeout"
t=2020-09-21T15:46:10+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/8/azuremonitor/subscriptions status=502 remote_addr=10.90.36.38 time_ms=60062 size=0 referer=https://our-lab-url.ch/datasources/edit/8/
t=2020-09-21T15:46:10+0200 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="Post \"https://login.microsoftonline.com/67809b88-5d87-4f90-80d9-e1e87631bd35/oauth2/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
t=2020-09-21T15:46:10+0200 lvl=info msg=Requesting logger=data-proxy-log url="https://management.azure.com/subscriptions/undefined/providers/Microsoft.OperationalInsights/workspaces?api-version=2017-04-26-preview"
t=2020-09-21T15:46:29+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/8/appinsights/beta/apps/75dd0ccb-61a8-419f-bc6c-8be8310fb478/metrics/metadata remote_addr=10.90.36.38 referer=https://our-lab-url.ch/datasources/edit/8/ error="http: proxy error: dial tcp 20.40.144.187:443: i/o timeout"
t=2020-09-21T15:46:29+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/8/appinsights/beta/apps/75dd0ccb-61a8-419f-bc6c-8be8310fb478/metrics/metadata status=502 remote_addr=10.90.36.38 time_ms=30028 size=0 referer=https://our-lab-url.ch/datasources/edit/8/
t=2020-09-21T15:46:40+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/8/azuremonitor/subscriptions/undefined/providers/Microsoft.OperationalInsights/workspaces remote_addr=10.90.36.38 referer=https://our-lab-url.ch/datasources/edit/8/ error="http: proxy error: dial tcp 51.107.60.33:443: i/o timeout"
t=2020-09-21T15:46:40+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/8/azuremonitor/subscriptions/undefined/providers/Microsoft.OperationalInsights/workspaces status=502 remote_addr=10.90.36.38 time_ms=71137 size=0 referer=https://our-lab-url.ch/datasources/edit/8/
t=2020-09-21T15:47:10+0200 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="Post \"https://login.microsoftonline.com/67809b88-5d87-4f90-80d9-e1e87631bd35/oauth2/token\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
t=2020-09-21T15:47:10+0200 lvl=info msg=Requesting logger=data-proxy-log url="https://management.azure.com/subscriptions/undefined/providers/Microsoft.OperationalInsights/workspaces?api-version=2017-04-26-preview"
t=2020-09-21T15:47:40+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/8/azuremonitor/subscriptions/undefined/providers/Microsoft.OperationalInsights/workspaces remote_addr=10.90.36.38 referer=https://our-lab-url.ch/datasources/edit/8/ error="http: proxy error: dial tcp 51.107.60.33:443: i/o timeout"
t=2020-09-21T15:47:40+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/8/azuremonitor/subscriptions/undefined/providers/Microsoft.OperationalInsights/workspaces status=502 remote_addr=10.90.36.38 time_ms=60029 size=0 referer=https://our-lab-url.ch/datasources/edit/8/_

> Are you able to verify as well if you can query the datasource when you don't use the proxy?
Unfortunately in our current environment we can open straight access to public internet via firewall, that's also why we need to use proxy for security reasons.

**Comment by gerbermarco** [comment]
> Can you open chrome dev tools and check network tab, track the following requests and share the responses?
> 
> /grafana/api/datasources/proxy//azuremonitor/subscriptions
> /grafana/api/datasources/proxy//appinsights/beta/apps
> /grafana/api/datasources/proxy//loganalyticsazure/

We can see the requests being made to your listet endpoints, although because we don't get out via proxy we don't get any repsonse. After the timeout, the request in the devtools gets the status code 502.

**Comment by papagian** [comment]
How you have configured `HTTP_PROXY` and `HTTPS_PROXY`? Have you tried restarting grafana after you have set them?
Here are [some guidelines addressing this in linux](https://github.com/grafana/grafana/issues/1691#issuecomment-102164444). Unfortunately I'm not very familiar with Windows for suggesting the appropriate ones there.
Note also that if you are having username/password in the proxy, these should be URL encoded.

**Comment by gerbermarco** [comment]
We found the issue! We've set the system wide proxy only, but not in `/etc/sysconfig/grafana-server`. After setting `HTTP_PROXY` and `HTTPS_PROXY` in `/etc/sysconfig/grafana-server` as described [in this guideline](https://github.com/grafana/grafana/issues/1691#issuecomment-102164444) it worked immediately. Thank you so much for your help!

**Comment by papagian** [comment]
thank you for the update; great to hear that your issue is resolved!
I thought you were running on windows, don't you? Is there a `/etc/sysconfig/grafana-server` there?
I'm asking because users have asked how to fix this in windows
and it would be nice to have some guidelines for them as well.

**Comment by gerbermarco** [comment]
No, we run Grafana on RHEL 7. But I come from the Windows world so I might be able to support you in return.

As long as there is no specific proxy configuration inside Grafana, you can set a Windows system wide proxy with `netsh winhttp set proxy <proxy>:<port>` (Powershell) as described [here](https://docs.microsoft.com/en-us/windows/security/threat-protection/microsoft-defender-atp/configure-proxy-internet#configure-the-proxy-server-manually-using-netsh-command). Keep in mind that this will affect all applications including Windows services which use WinHTTP with default proxy on this machine. If you need an overview over the different proxy types in Windows, [this](https://securelink.net/en-be/insights/windows-proxy-settings-explained/) article might be helpful.
