### ISSUE TITLE
Table sorting/thresholds ES raw data incorrectly

### ISSUE THREAD

**Issue by egg82** [grafana/grafana#27640]
**What happened**:
Table sorting with values < 0 on Grafana dashboard using ES is completely out of whack.

**What you expected to happen**:
Numbers to be sorted properly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an Elasticsearch index and add properties with type "double".
2. Add values < 0. I added values to the index as strings, but numbers work as well.
3. Create a table with "Raw data" metric.
4. Add thresholds for extra fun.

```
curl -X PUT "http://localhost:9200/test?pretty"
curl -X PUT "http://localhost:9200/test/_mapping?pretty" -H 'Content-Type: application/json' -d'
{
  "properties": {
    "test_val": {
      "type": "double",
      "index": true
    }
  }
}
'
```

**Anything else we need to know?**:
Video of issue: https://www.youtube.com/watch?v=4k9yKiPNEJo
Public dashboard: https://stats.egg82.ninja/d/X2eIbGdMz/twitter?orgId=1

**Environment**:
- Grafana version: both `7.1.5` & docker latest `dfd940ed4dd82a6369cb057fe5ab4cc8c774c1c5b943b2f4b618302a7979de61`
- Data source type & version: Elasticsearch 7.9.1
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Windows 10.0.18363 (Nov '19), Chrome 85.0.4183.102, Firefox 80.0.1, Edge 85.0.564.51
- Grafana plugins:
```
agenty-flowcharting-panel @ 0.9.0
briangann-datatable-panel @ 1.0.2
btplc-status-dot-panel @ 0.2.4
btplc-trend-box-panel @ 0.1.9
corpglory-progresslist-panel @ 1.0.5
digrich-bubblechart-panel @ 1.2.0
fatcloud-windrose-panel @ 0.7.0
flant-statusmap-panel @ 0.3.2
grafana-piechart-panel @ 1.6.0
grafana-polystat-panel @ 1.2.1
gretamosa-topology-panel @ 1.0.0
jdbranham-diagram-panel @ 1.6.2
mtanda-histogram-panel @ 0.1.6
natel-plotly-panel @ 0.0.6
neocat-cal-heatmap-panel @ 0.0.3
petrslavotinek-carpetplot-panel @ 0.1.1
simpod-json-datasource @ 0.2.1
snuids-radar-panel @ 1.4.4
snuids-trafficlights-panel @ 1.4.5
zuburqan-parity-report-panel @ 1.2.1
```
- Others:

**Comment by torkelo** [comment]
This is casued by the data for the numeric fields are actually returned by Elasticsearch as strings and not numbers. So Grafana sorts them as strings

**Comment by egg82** [comment]
> This is casued by the data for the numeric fields are actually returned by Elasticsearch as strings and not numbers. So Grafana sorts them as strings

I thought so, as well, but there's two things that don't make sense:
1. It happens when data is inserted as both numbers and strings
2. The newly-sorted data doesn't make sense even sorted as strings. Even positive numbers aren't sorted correctly

**Comment by aocenas** [comment]
@egg82 
> It happens when data is inserted as both numbers and strings

What is the usecase for having the data with 2 different types in single column? In that case it is hard to say what should the sorting do. We could convert the string to numbers but we may not know when to do that (like what if some values are not actually numbers). Seems like best solution would be to send all just as a numbers.

**Comment by egg82** [comment]
@aocenas 
> What is the usecase for having the data with 2 different types in single column?

That is not the case with my dataset, nor is it the case with the example provided. My statement was that it happens regardless of data type. I've tried using strings, and I've tried using numbers (not together) and neither one works- independently of each other.

Regardless, ElasticSearch seems to treat numbers and strings the same on its end.

**Comment by ivanahuckova** [comment]
This issue needs an investigation to find out if it is Elastic's or table panel's issue.

**Comment by Elfo404** [comment]
Feels like we are being hit by https://github.com/tannerlinsley/react-table/issues/2909 in the Table panel, need to investigate a bit more.

**Comment by mckn** [comment]
It feels like @Elfo404 is on to something with this issue. However I think we might be able to implement our own sorting by using the `orderByFn`: https://react-table.tanstack.com/docs/api/useSortBy#table-options

**Comment by Elfo404** [comment]
@mckn ooops, forgot to update here, sorry. I talked about this with @dprokop and moved this to your backlog.

**Comment by torkelo** [comment]
think this https://github.com/grafana/grafana/pull/34722  might fix this as well
