### ISSUE TITLE
[Feat Req]: Showing time as value/stat in singlestat panel

### ISSUE THREAD

**Issue by alexiri** [grafana/grafana#2764]
I'd like to create a Singlestat panel with the time of the last data point in an InfluxDB table (ie. "last update time"). Unfortunately, InfluxDB doesn't allow you to do a query only for a time, and Grafana doesn't let you choose which field to display in a Singlestat panel. Is there some solution for this?

**Comment by torkelo** [comment]
not currently

**Comment by The-Nik** [comment]
Maybe you need to store the time as an extra column in InfluxDB: {time_index, value, time}. So you can use the time as a common field.

**Comment by estebanrolando** [comment]
can at least have the time showed in the hoover pop up like for graphs? So I will see the last value in the DB, and if I hoover over the value will see the time for that datapoint. 
Of course I would prefer to be able to show the time in the panel.

**Comment by geckogecko** [comment]
+1 I am also waiting for this feature

**Comment by andymelichar** [comment]
+1 this would be a nice improvement.

**Comment by MachEleven** [comment]
+1

**Comment by torkelo** [comment]
Implemented in https://github.com/grafana/grafana/pull/9298 

You can now select "Time of last point" as Stat (ops there is no check that the last point is null, this needs to be filtered out in the query). 

3 new unit date formats are available (no custom date formats)

![image](https://user-images.githubusercontent.com/10999/30694232-6bdcefb2-9ed3-11e7-968b-5092fcb881de.png)
