### ISSUE TITLE
Extracting HELP metadata and use as variable

### ISSUE THREAD

**Issue by BentCoder** [grafana/grafana#27642]
Hi,

I've seen this post https://grafana.com/blog/2020/06/15/how-we-made-working-with-prometheus-easier-with-metric-metadata-in-grafanas-explore-view/ and want to find out if it is possible for us to extract, for instance, `HELP` metadata as shown below.

Thanks

Given this is what I have in Prometheus:
```
# HELP app_find_user_http_404_response Number of HTTP 404 responses
# TYPE app_find_user_http_404_response counter
app_find_user_http_404_response{title="Find User - HTTP 404 response"} 3
```
Then I would like to extract just `Number of HTTP 404 responses` from `HELP` and use it as a "variable". e.g.: `Graph X > General > Description = $help`.

**Comment by zoltanbedi** [comment]
Please direct support questions to the community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io). Thank you.
