### ISSUE TITLE
When I use Graph withTimescaleDB, 'Null value'' is invalid

### ISSUE THREAD

**Issue by fan233** [grafana/grafana#27650]
Grafana version:grafana-7.2.0-beta2.windows-amd64
Data source type & version:Postgres12
OS Grafana is installed on:Windows10
User OS & Browser:Windows10 & Chrome
Grafana plugins:Graph

**What would you like to be added**:
When I use Graph withTimescaleDB, 'Null value' cannot control line is 'null'、'connect' or 'null as zero'.Add this feature,please.
![image](https://user-images.githubusercontent.com/32827492/93576066-ffe40680-f9cc-11ea-83b0-d69877c70a37.png)

**Why is this needed**:
My data will stop collecting at a certain time.But the above picture may cause viewer misunderstanding.

**Comment by papagian** [comment]
can you please provide the following information (so as we will be able to verify the issue easier):

- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
also, could you please provide the response data from the query inspector?

**Comment by fan233** [comment]
> can you please provide the following information (so as we will be able to verify the issue easier):
> 
> * Grafana version:
> * Data source type & version:
> * OS Grafana is installed on:
> * User OS & Browser:
> * Grafana plugins:
> * Others:



> 此外， 您能提供查询检查员的响应数据吗？

**Comment by fan233** [comment]
> can you please provide the following information (so as we will be able to verify the issue easier):
> 
> * Grafana version:
> * Data source type & version:
> * OS Grafana is installed on:
> * User OS & Browser:
> * Grafana plugins:
> * Others:

The details have been updated in the question

**Comment by fan233** [comment]
> can you please provide the following information (so as we will be able to verify the issue easier):
> 
> * Grafana version:
> * Data source type & version:
> * OS Grafana is installed on:
> * User OS & Browser:
> * Grafana plugins:
> * Others:

The details have been updated in the question

**Comment by fan233** [comment]
> 此外， 您能提供查询检查员的响应数据吗？

![image](https://user-images.githubusercontent.com/32827492/93735452-7d975480-fc0f-11ea-8a67-4fa0fe33bc57.png)

**Comment by hugohaggmark** [comment]
@fan233 it looks like your data is ordered in desc time and can't see any `null` values in the output in the response data so I'm not sure I understand what the issue is here. Can you please give us some more information of what you expect?

**Comment by fan233** [comment]
> @fan233 it looks like your data is ordered in desc time and can't see any `null` values in the output in the response data so I'm not sure I understand what the issue is here. Can you please give us some more information of what you expect?
Can this information help you?
If using prometheus  'Null value' can be used normally.And inspect data like this.
![image](https://user-images.githubusercontent.com/32827492/94248334-ea348b00-ff50-11ea-8ee6-28b564fb4b75.png)

But if using Postgres  inspect data like this.
![image](https://user-images.githubusercontent.com/32827492/94248476-1e0fb080-ff51-11ea-93b4-39384cd8b77a.png)
Query SQL
SELECT
  $__time(time),
  device_name as metric,
  voltage as value
FROM
  voltage
WHERE
  $__timeFilter(time)
ORDER BY time asc

**Comment by hugohaggmark** [comment]
@fan233 thank you for a quick reply, in the postgres case I still can't see any null values but I can in the prometheus case. Are you saying that your Postgres query returns null values?

**Comment by fan233** [comment]
> @fan233 thank you for a quick reply, in the postgres case I still can't see any null values but I can in the prometheus case. Are you saying that your Postgres query returns null values?

No,I mean when I use Prometheus Database Graph`s 'Null value'  can be used normally.I can choose to set the line is 'null'、connected or 'null as zero'. But when I use PostgreSQL, Graph`s line always connected，can’t set  'null'、connected or 'null as zero' by "Null value".

**Comment by hugohaggmark** [comment]
@fan233 not sure I follow, if your Postgres request doesn't include any null values how is that Graph suppose to work with null values that doesn't exist?

**Comment by fan233** [comment]
> @fan233 not sure I follow, if your Postgres request doesn't include any null values how is that Graph suppose to work with null values that doesn't exist?

Sorry, The above reply is wrong. I re-describe my problem. Graph has such a features.Take Prometheus as an example.
![image](https://user-images.githubusercontent.com/32827492/94390736-15ec8680-0186-11eb-9637-189deec9fd57.png)
![image](https://user-images.githubusercontent.com/32827492/94390784-3ae0f980-0186-11eb-8152-90a9923e7ce1.png)
![image](https://user-images.githubusercontent.com/32827492/94390821-50562380-0186-11eb-98e1-729b2c3ea7a4.png)
But this features fails when using PostgreSQL.The line is always connected.Regardless of whether the setting'Null value' is 'null' or 'null as zero'.Could the "Null value" features work properly when using PostgreSQL? Like using Prometheus.

**Comment by hugohaggmark** [comment]
@fan233 yes I know the Graph has this feature, but your query needs to return actual `null` values and your example below from Postgres did not include any null values
![image](https://user-images.githubusercontent.com/32827492/94248476-1e0fb080-ff51-11ea-93b4-39384cd8b77a.png)

**Comment by hugohaggmark** [comment]
Just to clarify the Graph feature only work on `null` values
https://grafana.com/docs/grafana/latest/panels/visualizations/graph-panel/#stacking-and-null-value

and make sure you're grouping you data with `$__timeGroup(dateColumn,'5m', NULL)`
https://grafana.com/docs/grafana/latest/features/datasources/postgres/#macros

Let me know if that works out for you

**Comment by fan233** [comment]
> Just to clarify the Graph feature only work on `null` values
> https://grafana.com/docs/grafana/latest/panels/visualizations/graph-panel/#stacking-and-null-value
> 
> and make sure you're grouping you data with `$__timeGroup(dateColumn,'5m', NULL)`
> https://grafana.com/docs/grafana/latest/features/datasources/postgres/#macros
> 
> Let me know if that works out for you

Thank you, it worked.
Must use $__timeGroup(dateColumn,'5m', NULL)  and  select a large time range Graph can display correctly. Inappropriate time range cannot be displayed correctly.
