### ISSUE TITLE
Hidden variables not shown in Dashboard settings after upgrade to Grafana version 7.1.5

### ISSUE THREAD

**Issue by rdxmb** [grafana/grafana#27659]
**What happened**:

After upgrade from Grafana 6.6.2 to 7.1.5, the hidden Variables on my main Dashboard cannot be shown or edited in the Dashboard Settings. However, the Dashboard itself looks fine, even if panels are repeated by those variables.
New panels, however, cannot use one of the variables in an new panel.

**What you expected to happen**:

Variables used by panels in the dashboard can be shown and edited via Dashboard settings.

**How to reproduce it (as minimally and precisely as possible)**:

Create a dashboard with hidden variables in Grafana 6.6.2 , upgrade to version 7.1.5.

**Anything else we need to know?**:

**Environment**: Grafana in Docker
- Grafana version: 7.1.5
- Data source type & version: influxdb 1.8.1
- OS Grafana is installed on: Docker/Kubernetes
- User OS & Browser: Kubuntu 20.04, FF 80.0.1
- Grafana plugins: Blendstat, Status By Group Panel, Status Panel

Panels repeated by variables (working in both versions!)
![dashboard-hosts-repeated-by-variables](https://user-images.githubusercontent.com/30314040/93607043-1d16d600-f9c9-11ea-9e28-5dade49933bb.png)

Dashboard Settings:
![dashboard-settings-variables](https://user-images.githubusercontent.com/30314040/93607057-2142f380-f9c9-11ea-8b00-fd6618a9741f.png)

Creating new panels in 6.6.2
![panel-where-variable](https://user-images.githubusercontent.com/30314040/93607071-243de400-f9c9-11ea-8fa1-ad339bbe213a.png)

Creating new panels in 7.1.5
![panel-without-variable](https://user-images.githubusercontent.com/30314040/93607086-29029800-f9c9-11ea-951c-dd750d39a8f1.png)

**Comment by rdxmb** [comment]
hm, just restored the old backup and upgraded again - cannot reproduce. Indeed, I had some errors while working with the old GrafanaStatusPanel Plugin (v. 1.0.9), maybe something crashed then.
Closing this issue.

**Comment by andrewmcdonald-oxb** [comment]
Hello, I've encountered the same problem. I think it happened after we upgraded to 7.0.1. My variables are missing and the variables config screen says there are none, though the repeating graph template appears to work as before. I just can't make any edits to the variables, or select them in new plots.

Could one of the Grafana devs comment if possible? Is this a known issue?

**Comment by rdxmb** [comment]
@andrewmcdonald-oxb did you also update your plugin?

**Comment by andrewmcdonald-oxb** [comment]
Hi @rdxmb, which plugin are you referring to? I'm pulling data from an InfluxDB source into standard Graph panels, but I believe both of those plugins are simply bundled into the core installation.

**Comment by rdxmb** [comment]
Ok, so this is the same issue but maybe has another reason.
