### ISSUE TITLE
1 ldap group to multiple org

### ISSUE THREAD

**Issue by mag009** [grafana/grafana#2766]
seem that a user have to log out and log back in to sync each individual group.

would it be possible to use : 

one group_dn  for an list of org_id = ["org_1", "org_2]
and also would it be possible to be able to use name instead of id..

**Comment by torkelo** [comment]
ldap sync is only on login, all orgs are synced on login. 

Only id is used, more robust as names change the id will not

**Comment by mag009** [comment]
well example  if I do that in my config same user to give him access to 3 different org_id user have to login and log back in 3 times to get access to all 3 org : 

 [[servers.group_mappings]]
 group_dn = "cn=userA"
 org_role = "Admin"
 org_id = 2

 [[servers.group_mappings]]
 group_dn = "cn=userA"
 org_role = "Admin"
 org_id = 3

 [[servers.group_mappings]]
 group_dn = "cn=userA"
 org_role = "Admin"
 org_id = 4

**Comment by torkelo** [comment]
that sounds like a bug in that case :) will take a look

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master (and in upcoming 2.5 release)

**Comment by yesoreyeram** [comment]
@torkelo Is this working or broken ? I am using version 4.5.2 . This is not working for me. I couldn't assign multiple orgs for a DN.
