### ISSUE TITLE
For Flux Support

### ISSUE THREAD

**Issue by AmanMishra1321** [grafana/grafana#27664]
On reading an of InfluxDB Grafana Dashboard [https://www.influxdata.com/blog/how-grafana-dashboard-influxdb-flux-influxql/](url)
They are telling that it is also available in grafana 7 version but on selecting it in grafana 7.1.5 they are telling that it is currently available in grafana beta version

**Comment by papagian** [comment]
"Support for flux in Grafana is currently in beta" does not mean that is available in grafana beta version
but that Flux support in grafana version is currently beta meaning that there can be some issues when using Flux that they should be filed as github issues.
