### ISSUE TITLE
Docs: tsdoc @links are not rendered in docs

### ISSUE THREAD

**Issue by squarebracket** [grafana/grafana#27661]
**What happened**: [The `@link` included in `TemplateSrv.replace`'s tsdoc](https://github.com/grafana/grafana/blob/master/packages/grafana-runtime/src/services/templateSrv.ts#L17) is not rendered into the [corresponding docs page](https://grafana.com/docs/grafana/latest/packages_api/runtime/templatesrv/#replace-method). I imagine this also happens for all other `@link`s.

**What you expected to happen**: The docs page would say:
> Replace the values within the target string. See also [InterpolateFunction](https://grafana.com/docs/grafana/latest/packages_api/data/interpolatefunction/)

(note the link)

**How to reproduce it (as minimally and precisely as possible)**:
- `cd docs && make docs`
- open http://localhost:3002/docs/grafana/latest/packages_api/runtime/templatesrv/#replace-method

**Anything else we need to know?**: I think the last time I was messing around with tsdoc, it wasn't able to render out `@link`s. So maybe this is still impossible. Would certainly be a bummer, though, and at the very least it should be rendering the non-hyperlinked name.

**Environment**:
- Grafana version: master
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by papagian** [comment]
Also in [grafana.com](https://grafana.com/docs/grafana/latest/packages_api/runtime/templatesrv/#replace-method) the link is missing.

**Comment by squarebracket** [comment]
That's what I said... We linked the same page... ?

**Comment by hugohaggmark** [comment]
@mckn can you verify this when you have time?
