### ISSUE TITLE
Graph legend overflows panel after upgrading to Safari 14

### ISSUE THREAD

**Issue by DimaRabkin** [grafana/grafana#27676]
**What happened**:
After upgrading Safari to version 14.0, the graph's tags in the dashboards are out of the graph scope.
Safari 14:
<img width="1853" alt="image" src="https://user-images.githubusercontent.com/8135387/93751075-2b513600-fc05-11ea-8942-cc91338fc027.png">

Chrome (like Safari's previous version):
<img width="1856" alt="image" src="https://user-images.githubusercontent.com/8135387/93751128-415ef680-fc05-11ea-8b64-dfd6bf290a57.png">

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: Influx
- OS Grafana is installed on: Amazon EC2
- User OS & Browser: macOs Safari 14
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Do you get the same on https://play.grafana.org/d/6dorQldGz/graph-with-many-series-in-legend?orgId=1   ? 

I think we fixed this after 7.0.3,  can you try to upgrade to the latest stable?

**Comment by DimaRabkin** [comment]
yes

<img width="467" alt="image" src="https://user-images.githubusercontent.com/8135387/93754903-1aa3be80-fc0b-11ea-8c8c-3c1a726e9c6b.png">


but when I decrease the graph:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/8135387/93754942-28f1da80-fc0b-11ea-8c22-b9ac88a15f8c.png">

**Comment by bolbat** [comment]
Also the same problem on latest mobile Safari on iOS 14

**Comment by torkelo** [comment]
Was able to replicate this

**Comment by alen-z** [comment]
Same here.

Safari: Version 14.0 (15610.1.28.1.9, 15610)
Grafana: 7.2.0
