### ISSUE TITLE
allow_sign_up setting is not updated according to ini file

### ISSUE THREAD

**Issue by LeonidVasilyev** [grafana/grafana#2767]
I use version 2.1.3, installed on Ubuntu through APT.
I set `allow_sign_up=false` within grafana.ini, and restart service using `sudo service grafana-server restart`.
![image](https://cloud.githubusercontent.com/assets/1970951/9939112/3e406f2a-5d71-11e5-819d-e02ad98acbfb.png)

After that I'm still able to sign up using new e-mail. Within admin section settings are not updated. Logs seems to contain no relevant information.

![image](https://cloud.githubusercontent.com/assets/1970951/9939131/57488c5a-5d71-11e5-9137-6775df849642.png)

**Comment by torkelo** [comment]
cannot replicate
![image](https://cloud.githubusercontent.com/assets/10999/9943911/72191e10-5d84-11e5-8956-bc2d7b48b1df.png)


I am sure you just forgot to remove the `;`  in front of the line, it means the setting is commented out (all setting in grafana.ini are commented out so defaults are used)

**Comment by LeonidVasilyev** [comment]
@torkelo it's definitely not the case, I checked that.
But anyway it's okay now. Settings updated after VM restart (I forgot to mention that Ubuntu runs within VM) rather that grafana restart.
If machine restart is required I think It's good idea to mention that on settings page or within ini file.

**Comment by torkelo** [comment]
a machine restart is not required. a simple restart of grafana-server is all that is needed. There must have been some problem when you tried to restart the server, maybe it did not restart or you entered the wrong restart command :)

**Comment by LeonidVasilyev** [comment]
@torkelo indeed grafana-server wasn't restarted. For some reason `sudo service grafana-server restart` didn't work, yet printing following messages:
```
grafana-server stop/waiting
grafana-server start/running
```
I was able to successfully restart Grafana by running `sudo /etc/init.d/grafana restart` command.
