### ISSUE TITLE
Bar chart does not stay on screen

### ISSUE THREAD

**Issue by bhargaviaaa** [grafana/grafana#27709]
**What happened**:
Bar chart goes down
**What you expected to happen**:
Bar chart should be remain on screen always
**How to reproduce it (as minimally and precisely as possible)**:
In Prometheus give scrape interval as 10m. Bar chart goes down and comes up. It does not stay on screen continuously.
**Anything else we need to know?**:

**Environment**:
- Grafana version:6.7
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS
- User OS & Browser: Windows & Mizilla
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Must be an issue with your prometheus query or time range. 

If you think there is something wrong with the graph, show the response from your prometheus query along with the graph. (Via in query inspector)

**Comment by bhargaviaaa** [comment]
![grafana-bar-graph](https://user-images.githubusercontent.com/57214636/93974026-d7745780-fd92-11ea-85ac-b02ee4c7828e.png)

Prometheus response:
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/1/api/v1/query_range?query=OracleDBExporter_tablespace_bytes%7Binstance%3D%22xxxx%3Adddd%22%7D&start=1600825320&end=1600838760&step=3360"
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy1",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "209715200"
            ],
            [
              1600832040,
              "209715200"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy2",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "629145600"
            ],
            [
              1600832040,
              "629145600"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy4",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "524288000"
            ],
            [
              1600832040,
              "524288000"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy5",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "314572800"
            ],
            [
              1600832040,
              "314572800"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy6",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "314572800"
            ],
            [
              1600832040,
              "314572800"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy7",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "25165824"
            ],
            [
              1600832040,
              "25165824"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy8",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "25165824"
            ],
            [
              1600832040,
              "25165824"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy9",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "104857600"
            ],
            [
              1600832040,
              "104857600"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy10",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy11",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "56623104"
            ],
            [
              1600832040,
              "56623104"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy12",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy13",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "52428800"
            ],
            [
              1600832040,
              "52428800"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy14",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "230686720"
            ],
            [
              1600832040,
              "230686720"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy15",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy16",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "67108864"
            ],
            [
              1600832040,
              "67108864"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy17",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy18",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "67108864"
            ],
            [
              1600832040,
              "67108864"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy19",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "134217728"
            ],
            [
              1600832040,
              "134217728"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy20",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "16777216"
            ],
            [
              1600832040,
              "16777216"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy21",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "134217728"
            ],
            [
              1600832040,
              "134217728"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy22",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "33554432"
            ],
            [
              1600832040,
              "33554432"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy23",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "136314880"
            ],
            [
              1600832040,
              "136314880"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy24",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy25",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy26",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "67108864"
            ],
            [
              1600832040,
              "67108864"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy27",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy28",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy29",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy30",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "67108864"
            ],
            [
              1600832040,
              "67108864"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy31",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy32",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy33",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "67108864"
            ],
            [
              1600832040,
              "67108864"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy334",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy35",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "67108864"
            ],
            [
              1600832040,
              "67108864"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy36",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "262144000"
            ],
            [
              1600832040,
              "262144000"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy37",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "209715200"
            ],
            [
              1600832040,
              "209715200"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy38",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "83886080"
            ],
            [
              1600832040,
              "83886080"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy39",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "31457280"
            ],
            [
              1600832040,
              "31457280"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy40",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "272629760"
            ],
            [
              1600832040,
              "272629760"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy41",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "629145600"
            ],
            [
              1600832040,
              "629145600"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy42",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "524288000"
            ],
            [
              1600832040,
              "524288000"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy43",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "314572800"
            ],
            [
              1600832040,
              "314572800"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy44",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "346030080"
            ],
            [
              1600832040,
              "346030080"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy45",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "52428800"
            ],
            [
              1600832040,
              "52428800"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy46",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy47",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy48",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy49",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "536870912"
            ],
            [
              1600832040,
              "536870912"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy50",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "16777216"
            ],
            [
              1600832040,
              "16777216"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy51",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "1287651328"
            ],
            [
              1600832040,
              "1287651328"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy51",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "524288000"
            ],
            [
              1600832040,
              "524288000"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy52",
            "type": "TEMPORARY"
          },
          "values": [
            [
              1600825320,
              "419430400"
            ],
            [
              1600832040,
              "419430400"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy53",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "33554432"
            ],
            [
              1600832040,
              "33554432"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy54",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy54",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "268435456"
            ],
            [
              1600832040,
              "268435456"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy55",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "134217728"
            ],
            [
              1600832040,
              "134217728"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy56",
            "type": "PERMANENT"
          },
          "values": [
            [
              1600825320,
              "134217728"
            ],
            [
              1600832040,
              "134217728"
            ]
          ]
        },
        {
          "metric": {
            "__name__": "OracleDBExporter_tablespace_bytes",
            "instance": "xxxx:dddd",
            "job": "OracleDBExporter",
            "tablespace": "yyy57",
            "type": "UNDO"
          },
          "values": [
            [
              1600825320,
              "618659840"
            ],
            [
              1600832040,
              "618659840"
            ]
          ]
        }
      ]
    }
  }
}
