### ISSUE TITLE
QueryField: Inconsistent cursor position on Firefox

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#27707]
**What happened**:

On Firefox the cursor positions is seemingly random when the user clicks a `QueryField`.

![queryfield](https://user-images.githubusercontent.com/8396880/93891152-6463d600-fceb-11ea-83c6-672023b59afa.gif)

**What you expected to happen**:

Cursor is positioned at the end of the query. This works on Safari and Chrome.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two queries with a Prometheus data source
1. Type a query text in each field
1. Click back and forth on each field

**Anything else we need to know?**:

**Environment**:
- Grafana version: master
- Data source type & version: Prometheus (or any other data source using QueryField
- OS Grafana is installed on: macOS 10.15.6
- User OS & Browser: macOS 10.15.6 and Firefox 81

**Comment by marcusolsson** [comment]
Looks like a duplicate of https://github.com/grafana/grafana/issues/26760

**Comment by torkelo** [comment]
closing as there is already an issue
