### ISSUE TITLE
docker container “grafana/grafana” runs grafana as root

### ISSUE THREAD

**Issue by stapelberg** [grafana/grafana#2770]
root privileges are not necessary to run grafana, right?

In order to reduce the attack surface as far as possible, I think it’d be a good idea to not run grafana as root in the Docker container.

What do you think?

**Comment by torkelo** [comment]
not sure, its pretty common. But it would be great with a PR that improved the docker container. please open a ticker in the docker container repo

**Comment by stapelberg** [comment]
> please open a ticker in the docker container repo

Did you mean Pull Request? If not, which repository do you mean? I was referring to https://github.com/grafana/grafana/blob/master/docker/production/Dockerfile. Is that not the file which creates the “grafana/grafana” docker container?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana-docker
