### ISSUE TITLE
Architecture / services documentation needs an update

### ISSUE THREAD

**Issue by joanlopez** [grafana/grafana#27705]
**What would you like to be changed**:

The [Architecture / Services documentation](https://github.com/grafana/grafana/blob/master/contribute/architecture/services.md) should be updated.

**Why is this needed**:

Because on the [how to register a service section](https://github.com/grafana/grafana/blob/master/contribute/architecture/services.md#register-a-service) it refers the `server.go` file under `pkg/cmd/grafana-server` which no longer exists.

It might be replaced by `pkg/server/server.go` but I'm not sure because there are few of them imported on the `main.go` file. So probably there's some kind of criteria to determine it.

Thanks!

**Comment by aknuds1** [comment]
I made a refactoring that required moving pkg/cmd/grafana-server/server.go to pkg/server/server.go. I guess you are right in that the documentation needs to be updated correspondingly. Do you want to make a PR?

**Comment by joanlopez** [comment]
> Do you want to make a PR?

Done, thanks!
