### ISSUE TITLE
Cannot use field name with `.` (dot) in time field name when setting an elastic datasource

### ISSUE THREAD

**Issue by gadol** [grafana/grafana#27702]
**What happened**: Trying to set a new datasource of elastic index (which is not I'm not in charge of, hence the reason I can't change field names), and the time field name of the index has a `.` in it's name.
When I'm pressing `Save & Test` I get the following error: 'No date field named Date.Epoch found'.
But I'm certain the field exist, it's the same field used as time filer field in Kibana's index pattern

**What you expected to happen**: The datasource will work the same as every elastic index

**How to reproduce it (as minimally and precisely as possible)**: creating a new datasource which has a `.` in it's time field name

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2
- Data source type & version: elastic 6.8
- OS Grafana is installed on: Linux (using docker)
- User OS & Browser: Windows with chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@gadol thanks for reporting this. I have tried to reproduce this scenario with the mappings configured like below and it seems to work OK:
```json
    "properties": {
        "@hostname": {
            "type": "keyword"
        },
        "@location": {
            "type": "geo_point"
        },
        "@metric": {
            "type": "keyword"
        },
        "@source": {
            "type": "keyword"
        },
        "@tags": {
            "properties": {
                "hostname": {
                    "type": "keyword"
                },
                "source": {
                    "type": "keyword"
                }
            }
        },
        "@value": {
            "type": "float"
        },
        "time": {
            "properties": {
                "stamp": {
                    "type": "date",
                    "format": "epoch_millis"
                }
            }
        }
    }
```

Unfortunately I'm not Elastic expert. Maybe @marefr you can help with this one?

**Comment by dprokop** [comment]
@gadol can you share your index mappings config with us?

**Comment by gadol** [comment]
Unfortunately I cannot post the whole mapping (plus it's huge), but this is the relevant part:
```
"properties" : {
    "Date"
        "properties" : {
            "DateFormat": {
                "type" : "keyword",
                "fields" : {
                    "raw" : {
                        "type" : "keyword"
                    }
                },
                "Epoch" : {
                    "type" : "date",
                    "ignore_malformed" : true
                }
            }
        },
...
```

I also tried using just Date as the `Time field name` which also returned `No date field name ProccessingDate found`

querying in Kibana's discover with a query such as the following works fine: `Date.Epoch:[ 2020-09-30T00:00:00 TO 2020-09-30T22:00]`

**Comment by gadol** [comment]
Hi there @marefr I didn't get your operations and what is the status of the issue
Do you guys think it is a bug within grafana or something else related to my setup?

**Comment by zoltanbedi** [comment]
I think this is related to #27989

**Comment by gadol** [comment]
I'm sorry to announce that my problem was that the elastic was on another domain than the Kibana and the person that gave me the details didn't tell me that.
After fixing the domain of the elastic the problem was solved.

I am sincerely sorry for wasting your time, and am grateful for your help
