### ISSUE TITLE
Query variable executed as {1,2,3} instead of (1|2|3) when used in second variable

### ISSUE THREAD

**Issue by alexhk** [grafana/grafana#27717]
These are two identical dashboard template variables of the type query (identical for demonstration):

taglist1
taglist2

They are working as expected when used in the panels query with `WHERE "name" =~ /^$taglist1$/ `, the query inspector shows the query executed correctly with `"name" =~ /^(1|2|3)$/`.

However, when a third variable (type text for the sake of demonstration) is used to select between `$taglist1` and `$taglist2` in the actual panel query, the query is executed with curly brackets and comma instead: `"name" =~ /^{1,2,3}$/`  and hence won't work.

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Ubuntu Server 18.04
- User OS & Browser: Win 10 64bit, Firefox

**Working:**

![Screenshot_2020-09-23 01_ CALIBRATION - Grafana](https://user-images.githubusercontent.com/1495412/93976679-9cb1f580-fd79-11ea-9733-e268a1ee1681.png)

**Not working:**

![Screenshot_2020-09-23 01_ CALIBRATION - Grafana(1)](https://user-images.githubusercontent.com/1495412/93977422-bf90d980-fd7a-11ea-9477-a90923aba6ff.png)

**Variable:**

![Screenshot_2020-09-23 01_ CALIBRATION - Grafana(2)](https://user-images.githubusercontent.com/1495412/93977456-d0414f80-fd7a-11ea-8264-06a191f50d26.png)

**Comment by torkelo** [comment]
If you use variables in other settings like this (inside another variable) you need to force a specific interpolation format. so Use `${taglist1:regex}` to tell grafana to interpolate the multi-value using regex formatting and escaping

**Comment by alexhk** [comment]
Wow, thanks a lot for your help, and sorry for the dust.
