### ISSUE TITLE
oauth2: token expired and refresh token is not set

### ISSUE THREAD

**Issue by dkozar** [grafana/grafana#27725]
Hi,

I've built a custom plugin which authorizes the user using Azure AD. The plugin uses Forward OAuth Identity:

![forward-oauth-identity](https://user-images.githubusercontent.com/1078403/93997714-9e84b480-fd8b-11ea-8b6f-d60fd342d4c4.jpg)

Grafana retrieves the JWT token from Azure AD and everything works as expected (Grafana sends the token with each data request to our backend).

However, after the token expires (in 15 mins or so), Grafana is not able to refresh the token. Here is the error in the log:

`{"error":"oauth2: token expired and refresh token is not set","logger":"data-proxy-log","lvl":"eror","msg":"Failed to retrieve access token from OAuth provider","provider":"oauth_azuread`

I believed that a [previous fix](https://github.com/grafana/grafana/pull/26885) by @seanlaff fixed the issue. However, after installing Grafana 7.1.5, I'm still seeing the same issue.

My plugin uses Grafana's proxy (BackendSrv) and is not calling the data server directly. Here's how I'm doing requests to our data store:

```js
getBackendSrv()
    .datasourceRequest({
        url,
        method,
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        data,
    })
```

This is how the Authentication is configured on the AD side:

![image](https://user-images.githubusercontent.com/1078403/93998238-28cd1880-fd8c-11ea-9e21-031a47008e54.png)

Here's how the `plugin.json` route is configured:

```
"tokenAuth":{
   "url":"https://login.microsoftonline.com/{{ .JsonData.tenantId }}/oauth2/v2.0/token",
   "params":{
      "grant_type":"client_credentials",
      "client_id":"{{ .JsonData.clientId }}",
      "client_secret":"{{ .SecureJsonData.clientSecret }}",
      "resource":"resource-url-here"
   }
}

```

**Detailed log**:

```
{"logger":"sqlstore.xorm","lvl":"info","msg":"[SQL] SELECT `id`, `user_id`, `auth_token`, `prev_auth_token`, `user_agent`, `client_ip`, `auth_token_seen`, `seen_at`, `rotated_at`, `created_at`, `updated_at` FROM `user_auth_token` WHERE ((auth_token = ? OR prev_auth_token = ?) AND created_at \u003e ? AND rotated_at \u003e ?) LIMIT 1 []interface {}{\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", 1598120048, 1600107248} - took: 0s","t":"2020-09-21T19:14:08.269905+01:00"}
{"body":"","datasource":"xxxxx-datasource","logger":"data-proxy-log","lvl":"info","method":"GET","msg":"Proxying incoming request","orgid":1,"t":"2020-09-21T19:14:08.2709023+01:00","uri":"/api/datasources/proxy/4/xxxxxxxxxxxxxxxxxxxx","userid":2,"username":"xxxxxxxxxxxxxxxxxxxx"}
{"error":"invalid character '\u003c' looking for beginning of value","logger":"data-proxy-log","lvl":"eror","msg":"Failed to get access token","t":"2020-09-21T19:14:08.4484743+01:00"}
{"logger":"data-proxy-log","lvl":"info","msg":"Requesting","t":"2020-09-21T19:14:08.4484743+01:00","url":"https://xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
{"logger":"sqlstore.xorm","lvl":"info","msg":"[SQL] SELECT `id`, `user_id`, `auth_module`, `auth_id`, `created`, `o_auth_access_token`, `o_auth_refresh_token`, `o_auth_token_type`, `o_auth_expiry` FROM `user_auth` WHERE `user_id`=? ORDER BY `created` DESC LIMIT 1 []interface {}{2} - took: 0s","t":"2020-09-21T19:14:08.449379+01:00"}
{"error":"oauth2: token expired and refresh token is not set","logger":"data-proxy-log","lvl":"eror","msg":"Failed to retrieve access token from OAuth provider","provider":"oauth_azuread","t":"2020-09-21T19:14:08.4753794+01:00","userid":2,"username":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"}
{"logger":"context","lvl":"eror","method":"GET","msg":"Request Completed","orgId":1,"path":"/api/datasources/proxy/4/xxxxx","referer":"http://localhost:3000/d/eaYnTFdGz/demo-2?orgId=1\u0026from=now-1h\u0026to=now\u0026refresh=30s","remote_addr":"[::1]","size":0,"status":500,"t":"2020-09-21T19:14:08.6646505+01:00","time_ms":395,"uname":"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx","userId":2}
{"logger":"sqlstore.xorm","lvl":"info","msg":"[SQL] SELECT `id`, `user_id`, `auth_token`, `prev_auth_token`, `user_agent`, `client_ip`, `auth_token_seen`, `seen_at`, `rotated_at`, `created_at`, `updated_at` FROM `user_auth_token` WHERE ((auth_token = ? OR prev_auth_token = ?) AND created_at \u003e ? AND rotated_at \u003e ?) LIMIT 1 []interface {}{\"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", \"xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx\", 1598120051, 1600107251} - took: 0s","t":"2020-09-21T19:14:11.8170849+01:00"}
{"logger":"sqlstore.xorm","lvl":"info","msg":"[SQL] SELECT\n\t\tu.id             as user_id,\n\t\tu.is_admin       as is_grafana_admin,\n\t\tu.email          as email,\n\t\tu.login          as login,\n\t\tu.name           as name,\n\t\tu.help_flags1    as help_flags1,\n\t\tu.last_seen_at   as last_seen_at,\n\t\t(SELECT COUNT(*) FROM org_user where org_user.user_id = u.id) as org_count,\n\t\torg.name         as org_name,\n\t\torg_user.role    as org_role,\n\t\torg.id           as org_id\n\t\tFROM `user` as u\n\t\tLEFT OUTER JOIN org_user on org_user.org_id = u.org_id and org_user.user_id = u.id\n\t\tLEFT OUTER JOIN org on org.id = org_user.org_id WHERE u.id=? []interface {}{2} - took: 0s","t":"2020-09-21T19:14:11.8170849+01:00"}
```

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Custom data source, similar to Azure Monitor data source
- OS Grafana is installed on: Windows 10 (local installation)
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Azure monitor data source + this plugin
- I installed Grafana locally using [Windows installer](https://grafana.com/grafana/download?platform=windows)

Thanks! 😄

**Comment by seanlaff** [comment]
Do users log into your grafana with an azure oauth login? The tokenAuth in plugin.json is an orthogonal feature to oauth pass-thru I believe. oauth-pass-thru will take the token from the grafana login and send it through when the user makes a request, which shouldn't require tokenAuth settings in the plugin.

**Comment by dkozar** [comment]
> Do users log into your grafana with an azure oauth login? The tokenAuth in plugin.json is an orthogonal feature to `oauth pass-thru` I believe. `oauth-pass-thru` will take the token from the grafana login and send it through when the user makes a request, which shouldn't require tokenAuth settings in the plugin.

1. Yes, they log in using the OAuth too. Here's a snippet from `defaults.ini`:

```
#################################### Azure AD OAuth #######################
[auth.azuread]
name = Azure AD
enabled = true
allow_sign_up = true
client_id = xxxxxxxxxxxxxxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxx
scopes = openid email profile xxxxxxxxxxxxxxxxxx
auth_url = http://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxx/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxx/oauth2/v2.0/token
allowed_domains =
allowed_groups =
```

(these are the same `client_id` and `client_secret` that the admin sets in plugin configuration via ConfigEditor)

2. I see. However, the token fetched at login time expires at some point. How to use the refresh token to make Grafana exchange it for a new auth token (after any of the requests fails with 4xx)?

Currently the dashboard graphs stop working, displaying an error. Logging out and in to Grafana helps. However, we would like this to happen automatically, behind the scenes.

Thanks!

**Comment by papagian** [comment]
In the shared logs I see this error that seems related:
`{"error":"invalid character '\u003c' looking for beginning of value","logger":"data-proxy-log","lvl":"eror","msg":"Failed to get access token","t":"2020-09-21T19:14:08.4484743+01:00"}`

**Comment by dkozar** [comment]
> In the shared logs I see this error that seems related:
> `{"error":"invalid character '\u003c' looking for beginning of value","logger":"data-proxy-log","lvl":"eror","msg":"Failed to get access token","t":"2020-09-21T19:14:08.4484743+01:00"}`
> 
> \u003c unicode character must be the less than sign (<)

Yes, I noticed that too. However, I believe this has nothing to do with my implementation.

I was wondering, could you (the Grafana team) setup a dummy Azure app with AD auth, just to try it out?
As said, the login works nicely, the token is indeed being sent with each request, however this stops working after the token expires.
So, you'd have to wait for some time in order to detect the issue.

Thanks, much appreciate! 😄

**Comment by dkozar** [comment]
It's possible that the less than sign (<) could be the beginning of the server response at some point (400 bar request)?

**Comment by dkozar** [comment]
Any ideas what could have happened here?

I'd like to know if the error is possibly on our side. Much appreciate! 😄

**Comment by seanlaff** [comment]
@dkozar I think it would be good to verify if the refresh token that grafana gets from azure on the first login is valid. You could query the sql db directly, but the token is encrypted (not sure where to get the secret used to decode, but Im sure its somewhere) You could try kicking up the log level, but I don't think that token is logged b/c security concerns.

**Comment by dkozar** [comment]
@seanlaff thanks! I changed the log level to "debug" (previously I wasn't aware how to do that). Here's the (hopefully) more detailed log:

```
t=2020-10-01T14:29:47+0000 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=abcde-datasource url=
t=2020-10-01T14:29:47+0000 lvl=dbug msg="Data source URL doesn't specify protocol, so prepending it with http:// in order to make it unambiguous" logger=datasource type=abcde-datasource url=
t=2020-10-01T14:29:47+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=2 orgid=1 username=Foo.Bar@foobar.com datasource=abcde-datasource uri=/api/datasources/proxy/1/abcde method=POST body="{\"foo\":\"bar\"}"
t=2020-10-01T14:29:47+0000 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="invalid character '<' looking for beginning of value"
t=2020-10-01T14:29:47+0000 lvl=info msg=Requesting logger=data-proxy-log url=http://foobar.com/api
t=2020-10-01T14:29:47+0000 lvl=eror msg="Failed to retrieve access token from OAuth provider" logger=data-proxy-log provider=oauth_azuread userid=2 username=Foo.Bar@foobar.com error="oauth2: token expired and refresh token is not set"
t=2020-10-01T14:29:47+0000 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="invalid character '<' looking for beginning of value"
t=2020-10-01T14:29:47+0000 lvl=info msg=Requesting logger=data-proxy-log url=http://foobar.com/api
t=2020-10-01T14:29:47+0000 lvl=eror msg="Failed to retrieve access token from OAuth provider" logger=data-proxy-log provider=oauth_azuread userid=2 username=Foo.Bar@foobar.com error="oauth2: token expired and refresh token is not set"
t=2020-10-01T14:29:47+0000 lvl=eror msg="Failed to get access token" logger=data-proxy-log error="invalid character '<' looking for beginning of value"
t=2020-10-01T14:29:47+0000 lvl=info msg=Requesting logger=data-proxy-log url=http://foobar.com/api
t=2020-10-01T14:29:47+0000 lvl=eror msg="Failed to retrieve access token from OAuth provider" logger=data-proxy-log provider=oauth_azuread userid=2 username=Foo.Bar@foobar.com error="oauth2: token expired and refresh token is not set"
t=2020-10-01T14:29:49+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=Foo.Bar@foobar.com method=POST path=/api/datasources/proxy/1/abcde status=500 remote_addr=10.10.10.10 time_ms=279 size=0 referer="https://foobar.com/my-dashboard?orgId=1"
t=2020-10-01T14:29:49+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=Foo.Bar@foobar.com method=POST path=/api/datasources/proxy/1/abcde status=500 remote_addr=10.10.10.10 time_ms=279 size=0 referer="https://foobar.com/my-dashboard?orgId=1"
t=2020-10-01T14:29:50+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=Foo.Bar@foobar.com method=POST path=/api/datasources/proxy/1/abcde status=500 remote_addr=10.10.10.10 time_ms=384 size=0 referer="https://foobar.com/my-dashboard?orgId=1"
t=2020-10-01T14:29:52+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2020-10-01T14:30:02+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
t=2020-10-01T14:30:12+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=0
```

**Comment by dkozar** [comment]
> The `tokenAuth` in plugin.json is an orthogonal feature to `oauth pass-thru` I believe.

@seanlaff where can find more details on how the `tokenAuth` works? I'm aware that I could safely remove `tokenAuth` from `plugin.json`, and everything continues to work as expected. I believe need to switch on the `oauth pass-thru`, because otherwise no token is sent to the server.

**Comment by seanlaff** [comment]
@dkozar `OAuth Pass thru` as I referred to it us the `Forward OAuth Identity` box you have checked in the datasource config ui- which should be all that is needed to have the AD `access token` passed along to your datasource when grafana makes the request. If memory serves the lifecycle works like this->

1) User logs into grafana via oauth
2 ) grafana persists the `access token`, `refesh token`, and `expiry` to db
3) Any time a user triggers a request via the datasource with `Forward OAuth Identity` enabled, grafana will read the token
4) If the token is expired, grafana attempts the refresh flow
5) if the refresh flow gives a new token, replace the one on disk with that
6) forward the `acces token` to the datasource

My concern is at step 1 and 2, the refresh token being sent by AD is invalid. 

Other possibilites
- AD oauth is "peculiar" (this is not uncommon) and the typical oauth flow doesn't totally work (theres code in grafana to deal with some common providers and their inconsistencies)

**Comment by dkozar** [comment]
@seanlaff many thanks for the insights! Your input helped me finding the missing piece:

**Azure AD doesn't return a refresh token as the result of OAuth flow unless the `offline_access` scope is not added.**

Docs: https://docs.microsoft.com/en-us/azure/active-directory/develop/v2-permissions-and-consent#offline_access

My current `Azure AD OAuth` section in `defaults.ini`: 

#################################### Azure AD OAuth #######################
[auth.azuread]
name = Azure AD
enabled = true
allow_sign_up = true
client_id = xxxxxxxxxxxxxxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxx
scopes = openid email profile **offline_access** xxxxxxxxxxxxxxxxxx
auth_url = http://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxx/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/xxxxxxxxxxxxxxxxxxxxxxxxx/oauth2/v2.0/token
allowed_domains =
allowed_groups =

It seems like everything works fine now. I'm seeing the token logged in the log (with log level _debug_).

I'd suggest to put the `offline_access` scope into the docs, somewhere close to the `Forward OAuth Identity` feature, because these two are tightly related. :)
