### ISSUE TITLE
Pass nginx error message to the frontend

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#27734]
**What would you like to be added**:
Pass nginx/proxy error message to the frontend.

**Why is this needed**:
There has been couple of cases when the long URL is causing nginx in front of hosted prometheus to throw a `414 URI TOO LONG` error, but the error message is not ending up in the panel because the proxy seems to just close the connection midway.  E.g. https://github.com/grafana/grafana/issues/24611#issuecomment-627950729

**Comment by marefr** [comment]
I'm not sure we can do anything about this since nginx closes the connection. The suggestion in regards to Prometheus is to configure it to use POST instead of GET.

**Comment by hugohaggmark** [comment]
@ivanahuckova should we close this issue? Doesn't seem there is much we can do except preventing user from entering long queries but only with nginx?

**Comment by ivanahuckova** [comment]
Just wondering..., maybe we could add a error/console.warn or some other information for user, if they run very long urls and if they have problems with getting data, long urls might be the cause. But yeah, as it is not possible, closing this issue.
