### ISSUE TITLE
Control Bar / Top Bar optimizations for Mobile Devices (Smartphones)

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#27747]
**What happened**:
On mobile devices the "control bar" on the top of the dashboards does not scale correctly.
Especially when using smaller displays (tested with iPhone X, iPhone 7, iPhone SE)

**What you expected to happen**:
Better scaling, tile of the bar into two rows to get possibility to control without scrolling left/right.

**How to reproduce it (as minimally and precisely as possible)**:
Open any dashboard with a smartphone.

Scrolled left:
![IMG_3648](https://user-images.githubusercontent.com/14274103/94107318-7e153280-fe3d-11ea-99b0-33640a8d2822.jpeg)

Scrolled right:
![IMG_3649](https://user-images.githubusercontent.com/14274103/94107325-840b1380-fe3d-11ea-880a-fcbb103b5684.jpeg)

**Environment**:
- Grafana version: 7.x

**Comment by torkelo** [comment]
This should be fixed in master & v7.5
