### ISSUE TITLE
conf/defaults.ini doesn't pass as valid INI file for Python INI parser

### ISSUE THREAD

**Issue by kmoppel** [grafana/grafana#2774]
So basically just adding e.g. a "[global]" section before "app_mode" key would fix the issue.

configparser.MissingSectionHeaderError: File contains no section headers.
file: '/ssd/code/temp/grafana-2.5.0-pre1/conf/defaults.ini', line: 7
'app_mode = production\n'

https://docs.python.org/3/library/configparser.html

**Comment by torkelo** [comment]
cant change this now without breaking existing stuff
