### ISSUE TITLE
There is unexpected value in heatmap

### ISSUE THREAD

**Issue by lhy1024** [grafana/grafana#27745]
**What happened**:

There is unexpected value in a heatmap.
![image](https://user-images.githubusercontent.com/19542290/94100704-d578ca00-fe60-11ea-9066-a0a470d23779.png)

**What you expected to happen**:

we can found there are not value greater than 16.

![image](https://user-images.githubusercontent.com/19542290/94100718-df023200-fe60-11ea-8c15-716f4e9efba1.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I define bucket with the below code.
```
                readQPSStat = prometheus.NewHistogram(
		prometheus.HistogramOpts{
			Namespace: "pd",
			Subsystem: "scheduler",
			Name:      "read_qps_hist",
			Help:      "Bucketed histogram of the batch size of handled requests.",
			Buckets:   prometheus.ExponentialBuckets(1, 2, 13),
		})
```

I add data to the bucket with the below code.
```
readQPSStat.Observe(qps)
```

**Environment**:
- Grafana version: 7.1.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@lhy1024 can you share the data returned by the query?

**Comment by lhy1024** [comment]
> @lhy1024 can you share the data returned by the query?

![image](https://user-images.githubusercontent.com/19542290/94112913-aec68d80-fe78-11ea-8d6f-be1ca77e8013.png)

![image](https://user-images.githubusercontent.com/19542290/94112844-96ef0980-fe78-11ea-9f18-1a0847a95249.png)
```
"Time","1","2","4","8","16","32","64","128","256","512","1024","2048","4096","+Inf"
2020-09-24 12:13:30,24,0,1.3333333333333321,1.3333333333333321,0,0,0,0,0,0,0,0,0,0
2020-09-24 12:13:45,22.666666666666664,0,2.666666666666668,1.3333333333333321,0,0,0,0,0,0,0,0,0,0
2020-09-24 12:14:00,4780,0,2.6666666666660603,0,0,0,0,0,0,0,0,0,0,0
2020-09-24 12:14:15,7168,0,1.3333333333330302,1.3333333333330302,0,0,0,0,0,0,0,0,0,0
2020-09-24 12:14:30,7162.666666666666,0,0,1.3333333333339397,0,0,0,0,0,0,0,0,0,0
2020-09-24 12:14:45,2394.6666666666665,1.333333333333485,1.3333333333330302,1.333333333333485,0,0,0,0,0,0,0,0,0,0
2020-09-24 12:15:00,1.3333333333333333,1.3333333333333333,1.3333333333333335,0,0,0,0,0,0,0,0,0,0,0


```

**Comment by dprokop** [comment]
@lhy1024 I think the issue you are encountering is caused by using the wrong data format configuration. Since your data already returns buckets you should use the **Time series buckets** data format option in the heatmap configuration: https://grafana.com/docs/grafana/latest/panels/visualizations/heatmap/#buckets

![image](https://user-images.githubusercontent.com/2376619/94119122-bf620e00-fe4e-11ea-8c5d-b38c8a33e8b6.png)

**Comment by lhy1024** [comment]
> @lhy1024 I think the issue you are encountering is caused by using the wrong data format configuration. Since your data already returns buckets you should use the **Time series buckets** data format option in the heatmap configuration: https://grafana.com/docs/grafana/latest/panels/visualizations/heatmap/#buckets
> 
> ![image](https://user-images.githubusercontent.com/2376619/94119122-bf620e00-fe4e-11ea-8c5d-b38c8a33e8b6.png)

Thanks!
