### ISSUE TITLE
Exporting table with "Instant" Prometheus flag to CSV shows only one record

### ISSUE THREAD

**Issue by alen-z** [grafana/grafana#27749]
**What happened**: Exporting CSV shows only 1 line. Prometheus used as source.

![image](https://user-images.githubusercontent.com/7421289/94118526-f2f06880-fe4d-11ea-82c4-66c8cf75c92a.png)

**What you expected to happen**: Export data as seen in the table. Multiple rows with multiple columns as in previous versions.

**How to reproduce it (as minimally and precisely as possible)**: I think it is related to "Instant" flag. Table visualization.

**Anything else we need to know?**: -

- Grafana version: v7.1.5
- Data source type & version: Prometheus (Instant flag)

**Comment by dprokop** [comment]
This issue was [fixed](https://github.com/grafana/grafana/pull/27422) in 7.2.

**Comment by alen-z** [comment]
Appreciate the quick response. Updating.
