### ISSUE TITLE
Variables: Make variable queries cancellable with Observables

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#27746]
**What would you like to be added**:
We want to create a new addition to the datasource api like the addition for annotations added by @ryantxu in this PR:https://github.com/grafana/grafana/pull/27375
API proposal:
```ts
export interface VariableSupport<TQuery extends DataQuery = DataQuery> {
 query:(query: TQuery, options?: any): Observable<MetricFindValue[]>;
 tagKeys?(options?: any): Observable<MetricFindValue[]>;
 tagValues?(options?: any): Observable<MetricFindValue[]>;
}


export abstract class DataSourceApi<
  TQuery extends DataQuery = DataQuery,
  TOptions extends DataSourceJsonData = DataSourceJsonData
> {
...

/**
 ... ... ...
*/
  variables?: VariableSupport<TQuery>;
/**
   * Variable query action.
   *
   * @deprecated -- prefer using {@link VariableSupport}
   */
  metricFindQuery?(query: any, options?: any): Promise<MetricFindValue[]>;

  /**
   * Get tag keys for adhoc filters
   *
   * @deprecated -- prefer using {@link VariableSupport}
   */
  getTagKeys?(options?: any): Promise<MetricFindValue[]>;

  /**
   * Get tag values for adhoc filters
   *
   * @deprecated -- prefer using {@link VariableSupport}
   */
  getTagValues?(options: any): Promise<MetricFindValue[]>;
}
```

With this new api in place we'll need to upgrade the internals of the variable system to use this new api. This will be a bigger effort and I think we should look into Redux-Observable again because I think it's a perfect fit for the variables system. 

Only when we have a variables system that uses this new api can we start migrating our datasource plugins.
- [ ] Google Cloud Monitoring
- [ ] Cloudwatch
- [ ] Elastic
- [ ] Graphite
- [ ] InfluxDB
- [ ] Jaeger
- [ ] Loki (#27265)
- [ ] MSSQL 
- [ ] MySQL (#27649)
- [ ] OpenTSDB
- [ ] Postgres (#27478)
- [ ] Zipkin
- [ ] Prometheus (#27090) 

**Why is this needed**:
We have a challenge with long running variable queries because they are not cancellable and that makes a suboptimal user experience working with variables.

**Comment by torkelo** [comment]
would wait with tagKeys & tagValues, until know how we want ad-hoc filters to evolve. Feels like ad-hoc filters are in need of a big re-think. 

The other thing would be to explore how we can make the main variable query function have same signature as the main query method: 
```
  /**
   * Query for data, and optionally stream results
   */
  abstract query(request: DataQueryRequest<TQuery>): Promise<DataQueryResponse> | Observable<DataQueryResponse>;
```

That way we might be able to re-use runRequest for variable queries. And a data source can just pipe a variable query to the main query function. 

Another idea would be to have a mapping translation function to translate DataFrame to MetricFindValue and have Grafana call the main query function. The problem is translating the variable query to DataQueryRequest DataQuery,  maybe we can use the app property to mark queries coming from the variable system? https://github.com/grafana/grafana/blob/a3465e8bfebf292c5cb221a4d77a400e98758940/packages/grafana-data/src/types/datasource.ts#L451

**Comment by hugohaggmark** [comment]
> would wait with tagKeys & tagValues, until know how we want ad-hoc filters to evolve. Feels like ad-hoc filters are in need of a big re-think.
> 
> The other thing would be to explore how we can make the main variable query function have same signature as the main query method:
> 
> ```
>   /**
>    * Query for data, and optionally stream results
>    */
>   abstract query(request: DataQueryRequest<TQuery>): Promise<DataQueryResponse> | Observable<DataQueryResponse>;
> ```
> 
> That way we might be able to re-use runRequest for variable queries. And a data source can just pipe a variable query to the main query function.
> 
> Another idea would be to have a mapping translation function to translate DataFrame to MetricFindValue and have Grafana call the main query function. The problem is translating the variable query to DataQueryRequest DataQuery, maybe we can use the app property to mark queries coming from the variable system?
> 
> https://github.com/grafana/grafana/blob/a3465e8bfebf292c5cb221a4d77a400e98758940/packages/grafana-data/src/types/datasource.ts#L451

Good suggestion, would not be happy to keep the `Promise<DataQueryResponse> | Observable<DataQueryResponse>` as a result for this new api though, but I really like the transform function as it's done in AnnotationSupport.

**Comment by hugohaggmark** [comment]
I think the `options` part in the `metricFindQuery` is tricky to remove though?

**Comment by torkelo** [comment]
why? all that it contains is part of DataQueryRequest   (time range)

**Comment by hugohaggmark** [comment]
Variables and searchFilter too I think?

**Comment by torkelo** [comment]
Variables are also part of DataQueryRequest (scopedVars), searchFilter will need to be added somehow, maybe to scopedVars if possible

**Comment by hugohaggmark** [comment]
Ok ok, didn't know about scopedVars in DataQueryRequest. Then is seems a lot more doable :)

**Comment by hugohaggmark** [comment]
So something like this then
```ts
export interface VariableSupport<TQuery extends DataQuery = DataQuery> {
 query:(request: DataQueryRequest<TQuery>): Observable<DataQueryResponse>;
 toVariables: (response: Observable<DataQueryResponse>): Observable<MetricFindValue[]>
}
```

**Comment by hugohaggmark** [comment]
Maybe even this could work?
```ts
export interface VariableSupport<TQuery extends DataQuery = DataQuery> {
 toVariables: (response: Observable<DataQueryResponse>): Observable<MetricFindValue[]>
}
```

**Comment by torkelo** [comment]
question is do we need the query function? if you use this new variable support it would then be interesting have Grafana just use the main query function by default (With some property to the query function knows that it's a metric find query (as we need that in some cases where metric find queries need special logic)

For the mapping function can it be DataFrame -> MetricFindValue  (but Observable)

**Comment by hugohaggmark** [comment]
I just added a comment that removed query but then I deleted it :) because of how would the data source know that this is a variable query? But if you think that the `app` prop is sufficient then maybe the interface could look something like:
```ts
export interface VariableSupport<TQuery extends DataQuery = DataQuery> {
 toVariables: (data: Observable<DataFrame>): Observable<MetricFindValue[]>
}
```

I think from an API perspective having the query in VariableSupport makes it more explicit but I can see that it requires more stuff for the data source implementation.

**Comment by hugohaggmark** [comment]
ping @marcusolsson you might be interested in this as well :)
