### ISSUE TITLE
after 7.2 upgrade bar gauge panel doesnt show legend

### ISSUE THREAD

**Issue by sammy** [grafana/grafana#27751]
**What happened**:
Upgraded to Grafana 7.2 and my bar gauge panels stopped showing the configured legend, see screenshot below, legend used to appear to the left of each bar

![image](https://user-images.githubusercontent.com/37764/94121808-10bfcc80-fe52-11ea-85ba-8bd9da0677e1.png)

**What you expected to happen**:
Legend to continue to appear on the left of each bar after upgrading to 7.2

**How to reproduce it (as minimally and precisely as possible)**:
Create a bar gauge panel with a basic query, and set a legend for the query. Configured legend doesnt show anywhere

**Anything else we need to know?**:

**Environment**: Linux, Browsers; Chrome (83.0.4103.116), Firefox (80.0.1)
- Grafana version: 7.2
- Data source type & version: Prometheus, 2.21.0
- OS Grafana is installed on: Docker image, from stable helm chart
- User OS & Browser: Arch Linux, Chrome and Firefox browser
- Grafana plugins: -
- Others: -

**Comment by dprokop** [comment]
@sammy thanks for reporting this issue.

I've tried to reproduce this issue using the following setup, but without a success:

![image](https://user-images.githubusercontent.com/2376619/94125753-11a72d00-fe57-11ea-995d-8c7ed1be5399.png)

Can you share your Panel Data from Inspect->JSON->Panel Data?

**Comment by torkelo** [comment]
Can you include your panel json? what's your display name setting?

**Comment by sammy** [comment]
Here is the json:

`{
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "min": 0,
      "max": 50,
      "decimals": 0,
      "displayName": "",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "dark-green",
            "value": null
          },
          {
            "color": "light-green",
            "value": 10
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": []
  },
  "gridPos": {
    "h": 20,
    "w": 12,
    "x": 0,
    "y": 1
  },
  "id": 2,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "displayMode": "gradient",
    "showUnfilled": true
  },
  "pluginVersion": "7.2.0",
  "targets": [
    {
      "expr": "sort_desc(sum(increase(configapi_request{status_code=\"200\",datacenter=\"$datacenter\"}[$__range])) by (request_path))",
      "legendFormat": "{{request_path}}",
      "interval": "",
      "instant": true,
      "refId": "A",
      "intervalFactor": 1
    }
  ],
  "title": "Successfull requests",
  "transparent": true,
  "type": "bargauge",
  "timeFrom": null,
  "timeShift": null,
  "datasource": null
}`

**Comment by sammy** [comment]
So interesting part, if I recreate the panel from scratch everything shows up properly, but I cant fix the existing panel for some reason :man_shrugging: 

I guess we can close this

**Comment by torkelo** [comment]
you have an empty displayName property, can you try editing that in the UI? just add white space, that should make it Grafana remove the displayName property

**Comment by sammy** [comment]
I already removed all old panels so i cant try that with the display name. thanks for the help!
