### ISSUE TITLE
mod_auth_kerb causes graphs to not show. 

### ISSUE THREAD

**Issue by superjeb** [grafana/grafana#2775]
Upon configuration of mod_auth_kerb over grafana the graphs will not show and errors are seen relating to authentication on the UI,   authentication works to graphite which is on the same server.  
Only the graphs will not show. 

Config
<Location />
AllowOverride None
 Order allow,deny
 Allow from all
 Require valid-user
 AuthType Kerberos
 AuthName "Name"
 KrbMethodNegotiate on
 KrbMethodK5Passwd on
 Krb5Keytab /etc/http.keytab
 KrbAuthRealms DOMAIN.COM
KrbServiceName Any
 </Location>

**Comment by torkelo** [comment]
so whats the response from graphite via grafana proxy?

**Comment by torkelo** [comment]
Not sure what this could you need to provide more details, what request is failing, what are the headers sent to grafana, are you using the proxy feature? what headers are grafana sending to graphite? I have know idea what scenario as you provide very little info

**Comment by superjeb** [comment]
POST http://FQDN:3000/api/datasources/proxy/1/render net::ERR_UNEXPECTED

This is what i get all the way down.

**Comment by torkelo** [comment]
ok, maybe troubleshoot it to get more information on what is going on, where the error is coming from, is it apache, graphite, grafana? what headers are sent, etc
