### ISSUE TITLE
Table Panel: Tooltip showing full content of cell on hover (if cell is too small)

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#27761]
**What would you like to be added**:

A tooltip shows the complete content of a cell and appears while hovering above a cell in the Table panel (if the cell itself is too small to render the complete value and cuts it off instead). Additionally it should be possible to mark the content of the tooltip and copy it.

It should work just like the already existing Table tooltips:

![image](https://user-images.githubusercontent.com/24834206/94147360-7a050700-fe75-11ea-886c-defcd9194ac2.png)

**Why is this needed**:

I want to visualize the label values of certain metrics in a table. Some of these values are quite long. And so they are cut off. Most of the time I want this behavior, but sometimes I need the complete value for example to investigate logs. To get the complete value I have to manually increase the column width until the complete value is visible. This is a bit cumbersome. In addition this changes the dashboard by introducing an override. So to reset everything, I have to reload the dashboard without saving or manually remove the override again.

![image](https://user-images.githubusercontent.com/24834206/94147849-247d2a00-fe76-11ea-8a55-5e0fe0cae160.png)

Having a tooltip show up would help with that

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/27669 (but will not work for the last cell)

**Comment by trallnag** [comment]
Perfect timing as it seems, I will close this issue preemptively

**Comment by trallnag** [comment]
Perfect timing as it seems, great to see. I will leave this issue open since it will be closed automatically on merge I assume
