### ISSUE TITLE
Change the order of component tabs in Storybook: Docs first, Canvas second

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#27763]
Currently in the Storybook we have the Canvas tab appear first after clicking a component.
![image](https://user-images.githubusercontent.com/53754871/94149781-9e161780-fe78-11ea-9b64-444af7d99a20.png)

 In the UX feedback session we have gotten the feedback that this is confusing and the docs tab is easily overlooked for more novice users. So I would like these tabs switched out so that the docs appear first.

**Comment by richard-chim** [comment]
Looks like in v6.0 you can change the order (making `Docs` come first) by adding this in `.storybook/preview.js`:

```
export const parameters = {
  previewTabs: {
    'storybook/docs/panel': { index: -1 },
  }
};
```

![image](https://user-images.githubusercontent.com/44983719/106999548-65eee180-6754-11eb-8032-d989c2f99148.png)

Via https://stackoverflow.com/questions/59933162/how-to-disable-docs-tab-in-storybook.

**Comment by torkelo** [comment]
This would be very annoying from a developer perspective who wants to view the component and all its states

**Comment by thisisobate** [comment]
I agree with you @torkelo 

But just like @jessover9000 mentioned, I think alot of novice developers would find it really helpful to view the docs first before going to the canvas.

I think the best approach would be for us to create documentation for all grafana/ui components before changing the order of component tabs.
