### ISSUE TITLE
Orgs: Remove org deprecation notice in backend

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#27769]
Deprecation message of orgs was partially removed in #26853. We missed that there's also a message in the backend being logged when Grafana starts that also needs to be removed.

Code: https://github.com/grafana/grafana/blob/f0a586a9143b40530a3025fbe88faeab6460dc82/pkg/services/sqlstore/sqlstore.go#L119-L141

**Comment by torkelo** [comment]
Ah, good! forgot about that one
