### ISSUE TITLE
6.6.2 - Admin credentials not working, even after running: grafana-cli admin reset-admin-password

### ISSUE THREAD

**Issue by wcedmisten** [grafana/grafana#27772]
**What happened**:
I upgraded the installed grafana chart (chart version 5.0.7, app version 6.6.2) with `helm upgrade --install.` This restarted the grafana pod, but didn't create a new secret with admin credentials. The  admin credentials from the kubernetes secret did not allow me to log in. I then tried running `helm uninstall` and `helm install` to fully reinstall the grafana release. This did not resolve the problem either. I then tried resetting the password with grafana-cli. The `grafana-cli admin reset-admin-password` command gave feedback indicating that the admin password was successfully changed, but these credentials do not work either.

**What you expected to happen**: Credentials created with `grafana-cli admin reset-admin-password` allow me to log in as admin.

**How to reproduce it (as minimally and precisely as possible)**:

```
$ kubectl exec -it  test-grafana-68d8797f47-m72j9 -c grafana bash
bash-5.0$ pwd
/usr/share/grafana
bash-5.0$ grafana-cli --version
Grafana cli version 6.6.2
bash-5.0$ grafana-cli admin reset-admin-password adminpassword
INFO[09-24|17:31:50] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[09-24|17:31:50] Starting DB migration                    logger=migrator

Admin password changed successfully ✔
```

**Anything else we need to know?**: N/A

**Environment**: Kubernetes
- Grafana version: 6.6.2
- Helm chart version: 5.0.7
- Data source type & version: N/A
- OS Grafana is installed on: docker image grafana/grafana:6.6.2
- User OS & Browser: Ubuntu 18.04.4 LTS & Mozilla Firefox 80.0.1
- Grafana plugins: None

(Password field contains adminpassword)
![image](https://user-images.githubusercontent.com/4565200/94179480-8cc60e80-fe6a-11ea-8705-e6a0231b42af.png)

**Comment by wcedmisten** [comment]
After extracting and analyzing the `/var/lib/grafana/grafana.db` file, it appears that the (hashed) admin password stored in this database is also not changing after running `grafana-cli admin reset-admin-password`

**Comment by dprokop** [comment]
@wcedmisten can you please share grafana logs with us and maybe the request details from the network tab in your browser dev tools?

**Comment by marefr** [comment]
@wcedmisten In general, this feels like a helm problem and should be reported at https://github.com/grafana/helm-charts. If you can provide information that shows this is a Grafana problem we will accept/investigate it. I'll close this for now, but will reopen if you provide information that shows this is a Grafana problem.

In addition, no information how you persist the state of the database, like using SQLite or MySQL or Postgres,  and how you handle the state when upgrading Grafana to a new version. Would suggest login using the default admin username/password `admin/admin`.

**Comment by dprokop** [comment]
Also, another helm related issue: https://github.com/grafana/grafana/issues/20852

**Comment by papagian** [comment]
probably [this suggestion](https://github.com/helm/charts/issues/7891#issuecomment-572767968) posted in the repository @marefr has referenced can help to resolve the issue.

**Comment by marefr** [comment]
Agree with @dprokop that it could be related to referenced issue, but since you're running in Docker/kubernetes/helm you don't use Grafana debian package  Therefore feels like some other problem, possibly the one @papagian refer to.

**Comment by wcedmisten** [comment]
Thank you for the responses, I appreciate the help.

I believe what I described is two separate issues: 

- One caused by the helm chart (https://github.com/grafana/grafana/issues/20852). This caused me to initially lose my admin password.
- One caused by grafana itself (https://github.com/grafana/grafana/issues/12638). This prevents me from resetting the admin password, now that it is lost.

For background, I have no configured database, so grafana is using the default sqlite3 database for state persistence. I am surprised that this database is found under `/var/lib/grafana/grafana.db`, and not under `/var/lib/grafana/data`, as my grafana.ini paths section specifies.

```
$ cat /etc/grafana/grafana.ini
[analytics]
check_for_updates = true
[grafana_net]
url = https://grafana.net
[log]
level = debug
mode = console
[paths]
data = /var/lib/grafana/data
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
provisioning = /etc/grafana/provisioning
```

One user suggests symlinking `/var/lib/grafana/data` and `/var/lib/grafana/data/logs` to `/var/lib/grafana/` to fix the admin reset issue.
```
ln -s /var/lib/grafana  /usr/share/grafana/data
ln -s /var/log/grafana /usr/share/grafana/data/logs
```

The documentation says:
> data
> Path to where Grafana stores the sqlite3 database (if used), file-based sessions (if used), and other data. This path is usually specified via command line in the init.d script or the systemd service file.

Does this imply the path needs to exist already for this configuration to work? Maybe that is a bug with the helm chart, because the default value for paths.data is `/var/lib/grafana/data`, which doesn't exist in my container. I'm guessing grafana will not create this directory if it is not found.

```
$ ls /var/lib/grafana/data
ls: /var/lib/grafana/data: No such file or directory
```

**Comment by wcedmisten** [comment]
It turns out this was an unrelated issue. the reset-admin-password command was working correctly.
