### ISSUE TITLE
7.2 - bar gauge panel doesnt show legend

### ISSUE THREAD

**Issue by raul338** [grafana/grafana#27770]
**What happened**:

Im using to show single metrics with two queries (current/max values)
![image](https://user-images.githubusercontent.com/7199046/94167147-8cc21080-fe62-11ea-82ab-4a0703c53176.png)

**What you expected to happen**:
Keep it like grafana 7.1.5
![image](https://user-images.githubusercontent.com/7199046/94167836-5933b600-fe63-11ea-91bf-a91c89f1cab8.png)

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/7199046/94169715-841f0980-fe65-11ea-9e04-2e500d15428d.png)
![image](https://user-images.githubusercontent.com/7199046/94169766-94cf7f80-fe65-11ea-8e97-88586879f387.png)

**Anything else we need to know?**:
If I set a display name like suggested in #27751 it works when im using a single query. Here with two queries it shows like this
![image](https://user-images.githubusercontent.com/7199046/94169995-de1fcf00-fe65-11ea-849a-df1296c799d2.png)

While in 7.1.5 it was showns like this
![image](https://user-images.githubusercontent.com/7199046/94169880-ba5c8900-fe65-11ea-87ac-332b484332f7.png)

None of both results is useful for our use case

<details>
<summary>Panel JSON</summary>

```json
{
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "min": 0,
      "displayName": "En Cliente",
      "thresholds": {
        "mode": "percentage",
        "steps": [
          {
            "color": "light-orange",
            "value": null
          },
          {
            "color": "dark-orange",
            "value": 50
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 3,
    "w": 5,
    "x": 14,
    "y": 1
  },
  "id": 23763571993,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "last"
      ],
      "fields": "/^En Cliente$/"
    },
    "orientation": "horizontal",
    "displayMode": "basic",
    "showUnfilled": true
  },
  "pluginVersion": "7.2.0",
  "targets": [
    {
      "expr": "sum(solicitudes{tipo=\"abiertas\",estado=\"Pendiente de Cliente\"}) by (estado)",
      "interval": "",
      "legendFormat": "En Cliente",
      "refId": "A"
    },
    {
      "expr": "sum(solicitudes{tipo=\"abiertas\"})",
      "interval": "",
      "legendFormat": "Total",
      "refId": "B"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "type": "bargauge",
  "datasource": null
}
```

</details>

**Environment**:
- Grafana version: 7.2.0
- Data source type & version:  Prometheus 2.21.0
- OS Grafana is installed on: Docker on Centos 8
- User OS & Browser: Firefox 81 / Linux x64
- Grafana plugins: Blendstat (unused)
- Others: None

**Comment by torkelo** [comment]
And if you remove the displayName does the legend come back then? (it just enter a value in display name then remove it)

**Comment by raul338** [comment]
No, it renders as the first image

**Comment by dprokop** [comment]
Similar https://github.com/grafana/grafana/issues/27751

**Comment by torkelo** [comment]
Unable to replicate, can you set Fields to "All numeric fields" , and clear the display name setting?

**Comment by raul338** [comment]
Setting "Numeric fields" shows both bars with legend, as there are 2 queries

If I only use one query, it stops showing legend
![imagen](https://user-images.githubusercontent.com/7199046/94275637-92306100-ff1d-11ea-9b73-0e87b974b431.png)

<details>
  <summary>Panel JSON</summary>

```json
{
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "min": 0,
      "max": 10,
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "light-orange",
            "value": null
          },
          {
            "color": "light-orange",
            "value": 4
          },
          {
            "color": "semi-dark-orange",
            "value": 6
          },
          {
            "color": "dark-orange",
            "value": 8
          },
          {
            "color": "dark-red",
            "value": 10
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 3,
    "w": 5,
    "x": 11,
    "y": 10
  },
  "id": 23763571993,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "last"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "displayMode": "gradient",
    "showUnfilled": true
  },
  "pluginVersion": "7.2.0",
  "targets": [
    {
      "expr": "sum(solicitudes{tipo=\"abiertas\",estado=\"Pendiente de Cliente\"}) by (estado)",
      "interval": "",
      "intervalFactor": 1,
      "legendFormat": "Pendiente Cliente",
      "refId": "A"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "",
  "type": "bargauge",
  "datasource": null
}
```

</details>

**Comment by torkelo** [comment]
That is correct, if you only have one result/bar then it won't show a gauge, then you have to use the display name to force showing a legend for single gauge scenario (or use panel title)

**Comment by raul338** [comment]
> then you have to use the display name to force showing a legend for single gauge scenario

Setting display name and `Fields` shows also Time, like I posted before.
![imagen](https://user-images.githubusercontent.com/7199046/94169880-ba5c8900-fe65-11ea-87ac-332b484332f7.png)

Should I open a new issue for that?


Using the title solve this but the legend had a larger font

**Comment by nebular** [comment]
can variables be used in the displayName? tried with no luck and I would like to always show the header with a custom field like {{filename}}
