### ISSUE TITLE
Transform outer join - error when the metric name of the two tables is the same

### ISSUE THREAD

**Issue by cesarmacias** [grafana/grafana#27781]
I have Grafana 7.1.5 and the data is in Elasticsearch 7.X 
When make two queries to apply transform outer join from one field, but the join repeat the values of one table twice because the metric name is the same.
The first query is to count when have one condition and the second for another condition like "error" and "correct"

![image](https://user-images.githubusercontent.com/492320/94217399-886c1680-fea7-11ea-9498-78771e02abb5.png)

if not make the outer join the values of counter are different  between the two queries:

![image](https://user-images.githubusercontent.com/492320/94217558-e993ea00-fea7-11ea-9946-93d230fba973.png)

![image](https://user-images.githubusercontent.com/492320/94217570-f87a9c80-fea7-11ea-8a26-9d38813bfda6.png)

If tried to make transform organize fields, only appear one metric, because the metric fields have the same name:

![image](https://user-images.githubusercontent.com/492320/94217691-41325580-fea8-11ea-80a1-bc8c326ae238.png)

**Comment by cesarmacias** [comment]
Update the case:

After update to grafana 7.2, the problem persist have the same error:

![image](https://user-images.githubusercontent.com/492320/94219960-9a50b800-fead-11ea-8b5a-2e0a368d7413.png)

![image](https://user-images.githubusercontent.com/492320/94219995-aa689780-fead-11ea-8827-f75e122f0c52.png)

**Comment by dprokop** [comment]
Tested this with the following input to DirectDatasource:

DS1:
```
"field1","value"
abc,1
bcd,2
```

DS2:
```
"field1","value"
abc,4
bcd,6
```

The resulting table is: 
![image](https://user-images.githubusercontent.com/2376619/94243366-99547080-ff17-11ea-83ef-382541c05ce6.png)

Which indeed seems to be wrong.

**Comment by torkelo** [comment]
Unable to replicate the original issue 
![Screenshot from 2020-10-01 10-58-47](https://user-images.githubusercontent.com/10999/94789418-2cd4e800-03d5-11eb-81f1-edd091c190bf.png)
![Screenshot from 2020-10-01 10-58-52](https://user-images.githubusercontent.com/10999/94789424-2e9eab80-03d5-11eb-84b1-76ecf9bd7f8d.png)

**Comment by torkelo** [comment]
Here is a test dashboard where I am unable to replicate the problem https://play.grafana.org/d/AGS-2BKGz/elasticsearch-join-issue?orgId=1

**Comment by cesarmacias** [comment]
Hello,

The problem appear when handle not timeseries, the data are group by a term field.

**Comment by cesarmacias** [comment]
Hello,

After Upgrade to 7.2.1 the problem persist, when select field to outer join appear only one name:

![image](https://user-images.githubusercontent.com/492320/95777595-1c9df200-0c8c-11eb-917a-ff286a1cec1b.png)

because the metric "Unique Count" do in both series:

![image](https://user-images.githubusercontent.com/492320/95777817-8a4a1e00-0c8c-11eb-91a8-9d5093ea4471.png)

The new table joined repeat the vales of one series and not show the different values.

**Comment by OscarLopezEns** [comment]
As the user above stated, the issue can be replicated if you Group by Term instead of by Date Histogram. In fact, when this happens the "Alias" gets overridden.

![image](https://user-images.githubusercontent.com/24829017/97019250-f5a1b480-1504-11eb-9b12-849849e333ed.png)

**Comment by JorgeMarinC** [comment]
Same problem here, but only when grafana is installed in a docker container with ubuntu 20.04 image. The grafana built in container from DockerHub dont have this bug.
