### ISSUE TITLE
Migration SQLite to PostgreSQL

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#27791]
After migration from DB SQLite to PostgreSQL have trouble with 

t=2020-09-25T12:20:41+0300 lvl=eror msg="Failed to save dashboard" logger=context userId=16 orgId=1 uname=admin error="pq: duplicate key value violates unique constraint \"dashboard_version_pkey\"" remote_addr=10.9.0.6

and this problem not in save dashboard. Always where first id not 1. When I try many times (eq how id`s) I can save.
How migrat:
1) do dump sql with change type
sqlite3 grafana.db .dump | sed -e 's/`//g' | sed -e 's/BLOB/bytea/g;s/, for /, "for" /g' | sed -e 's/ user / "user" /g' | sed -e 's/ limit / "limit" /g;s/ order / "order" /g' | sed -e 's/INTEGER PRIMARY KEY AUTOINCREMENT/SERIAL PRIMARY KEY/' | sed -e 's/PRAGMA foreign_keys=OFF;//' | sed -e 's/unsigned big int/BIGINT/g' | sed -e 's/UNSIGNED BIG INT/BIGINT/g' | sed -e 's/BIG INT/BIGINT/g' | sed -e 's/UNSIGNED INT(10)/BIGINT/' | sed -e 's/BOOLEAN/SMALLINT/g' | sed -e 's/boolean/SMALLINT/g' | sed -e 's/UNSIGNED BIG INT/INTEGER/g' | sed -e 's/INT(3)/INT2/g' | sed -e 's/DATETIME/TIMESTAMP/g' > $file
2) del 
- migration log
- sequence
- sqlite sequence
- all Create Tables
- all Create Index
3) change all data from number to text where type boolean
4) hex to str https://github.com/haron/grafana-migrator/blob/master/hex_to_str.py 
5) start grafana on clean database and stop
6) insert data in db

How Grafana check Id? I catch sql queries and in it id push Grafana

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: 
- OS Grafana is installed on: OEL 7
- User OS & Browser: any
- Grafana plugins: 
- Others:

**Comment by Tiny-Paws** [comment]
Which version of PostgreSQL are you using ?
Your problem might be related to this known bug which has been around in Postgre from version 9-ish to 12 iirc
https://www.postgresql.org/message-id/flat/15865-17940eacc8f8b081%40postgresql.org

**Comment by Tepew** [comment]
PostgreSQL 12.2

**Comment by aocenas** [comment]
My PD knowledge may be a bit rusty but could it be that the sequences aren't set to correct value? Ie that the sequence for example is set to initial value of 1 even though the ID's in the table already have different values and so when inserting it will get a new ID value which can already be in the table. As far as i know sequences can get desynchronized from the table and can be manually reset. This would probably explain why it starts working after trying to save multiple times.

@Tiny-Paws the linked bug seem to concern creating resources in the DB so I would assume if that was the culprit it would fail during the migration itself not later during runtime.

**Comment by aocenas** [comment]
@marefr do you know if we have some guide for this sort of migration?

**Comment by marefr** [comment]
@aocenas we have https://grafana.com/blog/2020/01/13/how-to-migrate-your-configuration-database/ but only for MySQL. In general would suggest checking the [Grafana Community site](https://community.grafana.com/), think this question have come up multiple times there.

**Comment by Tepew** [comment]
https://community.grafana.com/t/downgrading-from-7-to-6-database-migration-issues/37025 it`s look same but without answer
https://community.grafana.com/t/grafana-ha-setup-errors-failed-to-save-dashboard/36302 same erorr but not same case
https://community.grafana.com/t/failed-to-create-user/9275 same erorr but not same case
not find multiple times. If you find I will be happy

**Comment by aocenas** [comment]
Not sure how much we can help right now, but what you could try is, after the migration, check the values of the sequences that generate the primary keys https://www.postgresql.org/docs/current/functions-sequence.html to see if they are correctly set to next unique value or start from zero. That way at least you could figure out if the problem is with the sequences and find out how to fix that.

**Comment by Tepew** [comment]
Sequence start from 0. But when I try set sequence not 0 problem didn`t go away and Grafana set new id as
id + set sequence
f.e.
in table 4 rows - set sequence 4
in Grafana I see problem with save before I do save 3 times and on 4 Grafana save but in Databse I see that id not 5. Id is
4+3=7
how Grafana check and set id? Problem in id set. If I can say Grafana start from id 4 all problems go away.

**Comment by aocenas** [comment]
The thing is grafana does not set the ID, it is left blank and database is responsible for assigning a new ID. That's what SERIAL PRIMARY KEY type is for. It creates a sequence that is then used to assign incremental IDs automatically while handling concurrent inserts.

When doing the migration, I do not know what the contents of the dump file are. I assume they are just create and insert statements but with specific IDs and I think in that case the sequence associated with the ID column isn't advanced by those inserts. So I still think advancing the sequence to correct value should fix this issue.

After moving the sequence to the right number, try inserting a dashboard through a DB CLI and see if that works and if that assigns correct ID.

**Comment by Tepew** [comment]
`I do not know what the contents of the dump file are`
in first message I write want in dump
`but with specific IDs`
Where are specific IDs I can find?
`After moving the sequence to the right number, try inserting a dashboard through a DB CLI and see if that works and if that assigns correct ID.`
ID`s from all tables start from 1 after migration. 
Open test dashboard 'Hypervisor' and try to save. Result - Error. How correct set sequence and how correct insert dashboard?
```
select id,version from dashboard where title='Hypervisor';
 id | version
----+---------
 74 |      18
(1 row)
```

**Comment by marefr** [comment]
Maybe this can bring some clarity to what Andrej referring to, basically you need to restart the auto increment columns in all tables so they begin counting from the last inserted primary key/id. This seems to be a popular solutin: https://stackoverflow.com/a/5343914 

With that I would think doing something like this should reveal the current (next) sequence number used for the dashboard_version table:
```sql
select pg_get_serial_sequence('dashboard_version', 'id');
```

**Comment by Tepew** [comment]
From dump I delete this
`INSERT INTO "sqlite_sequence" VALUES('migration_log',239);
INSERT INTO "sqlite_sequence" VALUES('user',55);
INSERT INTO "sqlite_sequence" VALUES('dashboard',86);
INSERT INTO "sqlite_sequence" VALUES('dashboard_provisioning',0);
INSERT INTO "sqlite_sequence" VALUES('data_source',8);
INSERT INTO "sqlite_sequence" VALUES('api_key',0);
INSERT INTO "sqlite_sequence" VALUES('dashboard_version',778);
INSERT INTO "sqlite_sequence" VALUES('dashboard_acl',83);
INSERT INTO "sqlite_sequence" VALUES('login_attempt',491);
INSERT INTO "sqlite_sequence" VALUES('org',2);
INSERT INTO "sqlite_sequence" VALUES('org_user',56);
INSERT INTO "sqlite_sequence" VALUES('server_lock',2);
INSERT INTO "sqlite_sequence" VALUES('user_auth_token',400);
INSERT INTO "sqlite_sequence" VALUES('plugin_setting',1);
INSERT INTO "sqlite_sequence" VALUES('dashboard_snapshot',1);
INSERT INTO "sqlite_sequence" VALUES('user_auth',58);
INSERT INTO "sqlite_sequence" VALUES('preferences',1);
INSERT INTO "sqlite_sequence" VALUES('team',12);
INSERT INTO "sqlite_sequence" VALUES('playlist',1);
INSERT INTO "sqlite_sequence" VALUES('playlist_item',20);
INSERT INTO "sqlite_sequence" VALUES('team_member',39);
INSERT INTO "sqlite_sequence" VALUES('star',22);
INSERT INTO "sqlite_sequence" VALUES('dashboard_tag',47);
INSERT INTO "sqlite_sequence" VALUES('alert_notification',1);
INSERT INTO "sqlite_sequence" VALUES('alert',4);
INSERT INTO "sqlite_sequence" VALUES('tag',2);
INSERT INTO "sqlite_sequence" VALUES('annotation',8);
INSERT INTO "sqlite_sequence" VALUES('alert_notification_state',4);
INSERT INTO "sqlite_sequence" VALUES('temp_user',2);`
test on star
Starred dasboard - failed. Go to DB and set sequence
`select setval('star_id_seq', 22);`
Starred again - failed. Saterred again and succes. ID is
24
2 - fail
22 - setval
Plese don`t close request before test on jther base.

**Comment by Tepew** [comment]
Test on other base. It`s work fine.
My mistake that I set sequnce in first time only for table dashboard and didn`t understand why don`t work. Didn`t work because Grafana use for dashboard not one table. If I test on table Star keys close so much faster.

**Comment by adrianovieira** [comment]
What if we use **pgloader** (https://github.com/dimitri/pgloader) to migrate from sqlite3 to postgresql-9.6+?

e.g.:

```bash
pgloader --debug --logfile /tmp/etl.log /work/grafana.db postgres://user:pass@mypgserver/grafana
```
the only one error we got was:
```
ERROR:  multiple primary keys for table "cache_data" are not allowed
```

Please, let me know what do you think!?
