### ISSUE TITLE
Grafana rounds floats to integers on graphs with elasticsearch plugin

### ISSUE THREAD

**Issue by ruslan-k** [grafana/grafana#27793]
Grafana rounds floats on graph and with elasticsearch data source

For example let's take system_cpu_usage from 0 to 1, let's see data in Kibana values are shown as floats

![image](https://user-images.githubusercontent.com/12158992/94254585-a7ae8680-ff2f-11ea-9352-f0e87dc62ee2.png)

In Grafana instead of loats we get 0
![image](https://user-images.githubusercontent.com/12158992/94253425-fce99880-ff2d-11ea-9833-c5ee2d152c05.png)

In Query inspector we also see integers instead of floats:
![image](https://user-images.githubusercontent.com/12158992/94252764-11796100-ff2d-11ea-950e-a37f008cb4cb.png)

Datasource configuration
![image](https://user-images.githubusercontent.com/12158992/94254839-feb45b80-ff2f-11ea-9e9d-1d06a71e02f5.png)

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Elasticsearch Data Source, Elasticsearch version 7.8.1
- OS Grafana is installed on: rhel 7.2.0
- User OS & Browser: Ubuntu 18.04, Chrome 85.0.4183.83
- Grafana plugins: Elasticsearch Data Source - Native Plugin

**Comment by dprokop** [comment]
@ruslan-k thanks for reporting. in the panel inspector, can you please open the Data options, disable the Formatted data option and share the result with us?

![image](https://user-images.githubusercontent.com/2376619/94255259-3f0fdb80-ff28-11ea-8024-9d79a7f5189a.png)

**Comment by ruslan-k** [comment]
Disabled formatted data just returns timestamp instead of data, but values are still rounded
![image](https://user-images.githubusercontent.com/12158992/94256238-2dcbcc80-ff32-11ea-9693-f0713965a861.png)

**Comment by dprokop** [comment]
And what about raw data returned from the query?

**Comment by ruslan-k** [comment]
Same, value is 0
`  "response": {
    "took": 31,
    "responses": [
      {
        "took": 31,
        "timed_out": false,
        "_shards": {
          "total": 24,
          "successful": 24,
          "skipped": 0,
          "failed": 0
        },
        "hits": {
          "total": {
            "value": 8640,
            "relation": "eq"
          },
          "max_score": null,
          "hits": []
        },
        "aggregations": {
          "2": {
            "buckets": [
              {
                "1": {
                  "value": 0
                },
                "key_as_string": "1601009760000",
                "key": 1601009760000,
                "doc_count": 10
              },
              {
                "1": {
                  "value": 0
                },
                "key_as_string": "1601009820000",
                "key": 1601009820000,
                "doc_count": 24
              },
              {
                "1": {
                  "value": 0
                },
                "key_as_string": "1601009880000",
                "key": 1601009880000,
                "doc_count": 24
              },
              {
                "1": {
                  "value": 0
                },
                "key_as_string": "1601009940000",
                "key": 1601009940000,
                "doc_count": 24
              },
              {
                "1": {
                  "value": 0
                }.....
`

**Comment by ruslan-k** [comment]
We had type long for values, instead of float. Changing type to to float resolved the issue.
