### ISSUE TITLE
Fullscreen mode tech change!

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2779]
The fullscreen mode has been a source of a lot of small bugs because it is using css fixed position to blow up single panel and hide all others (using mainly css), this was great because it allowed entering and exiting fullscreen/edit mode very fast (very little html rendering / code that needs to execute between fullscreen change). 

But its a big source of complexity, like if you have a submenu (with annotations or template variables) the full screen mode needs to compensate and push things down, and scrolling in fullscreen mode has been a source of many bugs (and non reachable dropdowns). 

Well I found a much better, simpler (and still FAST) way to switch between dashboard and fullscreen view/edit that does not use css fixed/absolute position. Simply all other rows and panels are hidden (css display:none), and the panel in fullscreen has its width set to 100%. Normal scrolling and content layout rules apply! So now you can open dashboard settings while in fullscreen/edit view! 

This change was really important for the new timepicker (https://github.com/grafana/grafana/issues/2761)
![image](https://cloud.githubusercontent.com/assets/10999/9966575/eb066544-5e3d-11e5-8ff4-f961cbd01e1f.png)

This timepicker must be usable in fullscreen mode, and it should push the fullscreen/edit panel down, and for that I had to ditch the css fixed position. 

Great Progress, lots of small workaround and fixes for fixed position could be removed! And should solve some still open issues around scrolling/non reachable dropdowns in fullscreen.

**Comment by Dieterbe** [comment]
very nice!

**Comment by discoduck2x** [comment]
Awesome!
