### ISSUE TITLE
Datetime local (No date if today)

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#27803]
**What would you like to be added**:
It would be nice to get the Datetime local (No date if today) unit.

**Why is this needed**:
There is "No date if today" option available in Datetime ISO and Datetime US units, but not in Datetime local unit.

**Comment by aocenas** [comment]
Sorry I am not exactly sure what setting do you mean, can you elaborate a bit which setting do you mean?

**Comment by szerwi** [comment]
Hi. I mean value's unit that is available in all panel types.
![image](https://user-images.githubusercontent.com/19311511/94570253-f2e9d180-026e-11eb-97b4-554f3e834d91.png)

**Comment by aocenas** [comment]
Ah thanks for clarifying that. @dprokop or @torkelo do we want to add that or is there some reason this isn't there already (we seem to have the same options in 7.2)?

**Comment by torkelo** [comment]
Feature request can be implemented by the community easily: 

Here is the place to add function:
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/dateTimeFormatters.ts#L373

and here to add to units list:
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts#L187

**Comment by tushutripathi** [comment]
@torkelo @aocenas  I'll have a go at it if that's okay?

**Comment by torkelo** [comment]
Of course!

**Comment by tushutripathi** [comment]
Great, I have submitted a PR #28011
