### ISSUE TITLE
Data Source ->Test Connection  always return success

### ISSUE THREAD

**Issue by wyzssw** [grafana/grafana#2780]
even i set http url to http://1.2.3.4:0000 or else which ip:port not available.grafana always return success:

```
Http settings

Url 
http://1.2.3.4:0000
Access 
Basic Auth Enable  
```

```
Test results

Success
Data source is working
```

**Comment by torkelo** [comment]
what data source are you using?

**Comment by wyzssw** [comment]
```
type influxDB 0.9.x
```

**Comment by wyzssw** [comment]
grafana-2.1.3-1

**Comment by torkelo** [comment]
strange, tried to replicate this in master and in 2.1.3, got test failures every time the ip or port was incorrect

**Comment by torkelo** [comment]
Can you check chrome dev tools (f12), and view the test request and response?

**Comment by gcetusic** [comment]
Got the same issue in 2.1.3 with InfluxDB 0.9.4
It seems there's an error in how Grafana handles faulty connections:

cetko@lorkhan:~$ curl -vvv 'http://locahost:8086/query?db=test&epoch=ms&p=test&q=SHOW+MEASUREMENTS+LIMIT+1&u=test' -H 'Pragma: no-cache' -H 'Origin: http://localhost:3000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:3000/datasources/edit/1' -H 'Connection: keep-alive' -H 'Cache-Control: no-cache' --compressed
* Could not resolve host: locahost
* Closing connection 0
curl: (6) Could not resolve host: locahost
cetko@lorkhan:~$ 
cetko@lorkhan:~$ curl 'http://192.168.1.1:8086/query?db=test&epoch=ms&p=test&q=SHOW+MEASUREMENTS+LIMIT+1&u=test' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost:3000/datasources/edit/1' -H 'Origin: http://localhost:3000' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.132 Safari/537.36' --compressed
curl: (7) Failed to connect to 192.168.1.1 port 8086: Connection refused

**Comment by gcetusic** [comment]
@torkelo What about this issue? Was it fixed?
