### ISSUE TITLE
Investigation: make sure we unsubscribe properly in react components.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#27800]
**What happened**:
During the review of the following PR (#27729) we (@hugohaggmark and @peterholmberg) noticed that we get the following warnings when running the end-to-end tests:

```
Running:  query-editor.spec.ts 
MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 preprocessor:close listeners added to [EventEmitter]. Use emitter.setMaxListeners() to increase limit
```

Given the following [comment](https://github.com/grafana/grafana/pull/27729#discussion_r494041719) I wanted to open this issue to make sure that we dig into this issue so we don't have a potential memory leak where we create a lot of subscriptions that never is unsubscribe. With that said, the error being displayed above is from Cypress and could be a warning on that environment.

**What you expected to happen**:
All event listeners is unsubscribed on `componentWillUnmount`.

**Comment by torkelo** [comment]
think this is fixed
