### ISSUE TITLE
7.2.0 - Cannot log in

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#27802]
**What happened**:
At login page I type login & password and click "Log in" button. There is a dialog saying "Logged in", but after redirection to home page, I am not logged to my account.

**What you expected to happen**:
The user should be logged in.

**How to reproduce it (as minimally and precisely as possible)**:
Described above

**Anything else we need to know?**:
The problem happens on browser Opera Gx 71.0.3770.175 and Google Chrome 85.0.4183.121. Logging in works fine on Edge 85.0.564.51.
Tested on Grafana 7.2.0 and 7.1.3.

I access grafana site via domain and HTTPS protocol
In Grafana config I have set:
cookie_samesite = none
cookie_secure = true

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on:  Debian 4.9
- User OS & Browser: Windows 10, Google Chrome and Opera Gx
- Grafana plugins: -
- Others: -

**Comment by leowang029** [comment]
Maybe you could clear browser cookies and storage data, and then try login again.

**Comment by szerwi** [comment]
> Maybe you could clear browser cookies and storage data, and then try login again.

I've tried clearing storage data and using incognito mode, but it is not working as well.

**Comment by aocenas** [comment]
Can you share your grafana logs after setting log level to debug https://grafana.com/docs/grafana/latest/administration/configuration/#log. Also can you check if there is any error log in the browser when this happens?

**Comment by szerwi** [comment]
@aocenas here is the fragment of the logs:
https://pastebin.com/MWTErLWe

Screenshot of what the developers console in browser shows:

![Zrzut ekranu 2020-09-28 175734](https://user-images.githubusercontent.com/19311511/94456878-1d2a8900-01b4-11eb-9726-ef1a445c5be7.jpg)

**Comment by aocenas** [comment]
Just to confirm, because based on this log line `t=2020-09-28T17:47:18+0200 lvl=info msg="Successful Login"` I would assume you are logged in, what do you see after the redirect? Do you see some error message? Are you redirected back again to login page? Could this be just an issue with permissions? Subsequent log messages would suggest that maybe the user that logs in does not have a permissions to see their home dashboard (not sure how that happens but could be a pointer to what is actually wrong.)

**Comment by szerwi** [comment]
After logging in, I am being redirected to home page, but the icon in bottom left corner is still showing me to log in. I also do not have access to other dashboards that are available to that user (home dashboard is available for everyone, even anonymous users).
It cannot be problem with permissions, because the same user is working fine on Edge browser.

**Comment by aocenas** [comment]
@dprokop can your team take a look? I feel this may be frontend issue considering it's browser dependent but not sure. Also I feel we had something like this in the past.

**Comment by bassmaster187** [comment]
I've got the same problem after updating from 6.3.5 to 7.2.0 on Chrome 85.0.4183.121.
Using "Private Mode" in Chrome solve the problem. Maybe this helps?

**Comment by szerwi** [comment]
@bassmaster187 incognito mode did not help in my case.

**Comment by mckn** [comment]
> @dprokop can your team take a look? I feel this may be frontend issue considering it's browser dependent but not sure. Also I feel we had something like this in the past.

I'm on it!

**Comment by mckn** [comment]
> @bassmaster187 incognito mode did not help in my case.

Have you tried to clear the cookies as @bassmaster187 suggested?

**Comment by mckn** [comment]
hmm, I am able to recreate this. I will have a look at it.

**Comment by mckn** [comment]
@szerwi could you attach a screen shot of the google chrome developer tools when viewing the login response headers? Like the example I attach below.

<img width="1664" alt="Skärmavbild 2020-10-06 kl  10 16 23" src="https://user-images.githubusercontent.com/172951/95176413-22dc2c00-07bd-11eb-826c-fd20325a4771.png">

**Comment by szerwi** [comment]
@mckn Here you are. I've only blured my IP address in "General" section.
![image](https://user-images.githubusercontent.com/19311511/95208799-e3780480-07e9-11eb-9251-36b6fb432928.png)

**Comment by mckn** [comment]
> @mckn Here you are. I've only blured my IP address in "General" section.
> ![image](https://user-images.githubusercontent.com/19311511/95208799-e3780480-07e9-11eb-9251-36b6fb432928.png)

Ah, perfect! If you highlight the small little yellow triangle at the end of the "Set-Cookie" line. What does that say? Because it looks like the `cookie_secure` value in your configuration is set to `false`.

**Comment by szerwi** [comment]
@mckn It says "This Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is required in order to use "SameSite=None"."

**Comment by mckn** [comment]
> @mckn It says "This Set-Cookie was blocked because it had the "SameSite=None" attribute but did not have the "Secure" attribute, which is required in order to use "SameSite=None"."

So make sure that you only have one `cookie_secure` value in your configuration and that it is set to `true`.

**Comment by szerwi** [comment]
@mckn There is only one cookie_secure value in my configuration file and it is set to true. Should I change the cookie_samesite to anything else?

**Comment by mckn** [comment]
> @mckn There is only one cookie_secure value in my configuration file and it is set to true. Should I change the cookie_samesite to anything else?

hmm, no - it should work with that configuration.

**Comment by szerwi** [comment]
@mckn I have also checked it on Microsoft Edge browser (logging in works fine on that browser). All the headers are the same, the only difference is that on Edge there is no warning which is on Opera / Chrome.

**Comment by mojatt** [comment]
I tried changing "cookie_secure" in my config (not running https) to true and the issue is still apparent. :(

**Comment by marefr** [comment]
Have you read/considered these upgrade notes?
- https://grafana.com/docs/grafana/latest/installation/upgrading/#important-changes-regarding-samesite-cookie-attribute
- https://grafana.com/docs/grafana/latest/installation/upgrading/#cookie-path

**Comment by szerwi** [comment]
@marefr Thanks, it seems that changing cookie_samesite from none to disabled fixed the problem :)

**Comment by marefr** [comment]
Thanks
