### ISSUE TITLE
Setup vs. set up

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#27819]
**What would you like to be added**: Review the usage of setup vs. set up in the Grafana technical documentation. Correct as necessary.

"setup" is a noun. 
- **Correct:** We need a highly available setup.
- **Incorrect:** Quickly setup your system.

"set up" is a verb.
- **Correct:** Quickly set up your system.
- **Incorrect:** We need a highly available set up.

**Why is this needed**: Currently the usage is inconsistent and frequently incorrect. This change will improve the quality of the documentation.

**Comment by philnichol** [comment]
Can I pick this one up?

**Comment by philnichol** [comment]
@oddlittlebird hope you don't mind I went ahead and raised a PR.

**Comment by oddlittlebird** [comment]
Don't mind in the least. :)

Incidentally, the setup vs. set up confusion is rampant throughout the software world. If you felt like running this check on other documentation repositories, you'll probably find lots to fix.
