### ISSUE TITLE
Feature: Other unit for specific metric

### ISSUE THREAD

**Issue by RaymiiOrg** [grafana/grafana#2781]
I measure storage on a few machines in GB, and also accounts. Each account has a quota of storage. I now have a graph with actual used, free, provisioned and provisionable space, each with the unit GB. That all works fine. I want to add the account numbers, and that can be 16 accounts, or 500 accounts, but with the current legend that shows up as 16 or 500 GiB. I don't want that, I just want it to appear in the legend as 16 or 500. It is not even visible on the graph, because of the low amount, (terrabytes of storage), and that is also fine with me. So this might be a double feature request, showing a stat on the legend with a different unit and not graphing it.

**Comment by RaymiiOrg** [comment]
Here's a picture of my graph so to make it more clear:

![selection_2015-09-20-003](https://cloud.githubusercontent.com/assets/1927494/9979602/4bcc99ec-5f75-11e5-9ba5-2401151aa8ce.png)

**Comment by RaymiiOrg** [comment]
Also, the terrabyte unit would be handy in my case. Here's the same graph without the accounts number:

![selection_2015-09-20-004](https://cloud.githubusercontent.com/assets/1927494/9979610/b723238c-5f75-11e5-99dd-beca238b3aef.png)

**Comment by torkelo** [comment]
you can do this by moving the accounts series to the right y axis

![image](https://cloud.githubusercontent.com/assets/10999/9979781/266b8c4a-5f7e-11e5-907c-350f0aa000f2.png)

**Comment by RaymiiOrg** [comment]
Super, thanks :+1: :smile:
