### ISSUE TITLE
Apply lazy numbering

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#27822]
**What would you like to be added**: Apply lazy numbering throughout the Grafana documentation.

In almost all cases, our documentation should use lazy numbering, also called [repetitive numbering](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-markdown-guide.md#numbered-lists).

In some cases, we cannot do this because of code blocks or other items inserted in the list. However, in many cases, we can. Review the usage and apply where possible.

**Why is this needed**: Saves work when it comes time to update lists.

**Comment by DECarreras** [comment]
I'd like to work on this for Hacktoberfest. Any specific areas/folders in the documentation to start?

**Comment by DECarreras** [comment]
UPDATE: Should I stick to the files under **docs/** folder only? There are a few other miscellaneous .md files elsewhere but I'm not sure I should touch those?

**Comment by oddlittlebird** [comment]
Mostly the stuff in the docs folder and contribute folder will apply.
