### ISSUE TITLE
Remove vague link text

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#27824]
**What would you like to be added**:

Replace unhelpful link text, such as "here" or "documentation", throughout the Grafana technical documentation. "here" is probably the biggest offender.

Link text should be descriptive, preferably the title of the page or section being linked to.

Examples:
- **Incorrect:** For more information, go [here](https://grafana.com/docs/grafana/latest/administration/image_rendering/).
- **Correct:** For more information about setting up image rendering, refer to [Image rendering](https://grafana.com/docs/grafana/latest/administration/image_rendering/).

**Why is this needed**: To improve the quality of our technical documentation.

**Comment by Shikachuu** [comment]
If it's still free may I sign up? :smile:

**Comment by oddlittlebird** [comment]
Have at it!

**Comment by darrylsepeda** [comment]
Seems there is no update, may I be the assignee?
