### ISSUE TITLE
Remove italic format from tables

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#27821]
**What would you like to be added**:

Some tables have the text in the first column italicized. This is incorrect. Remove that formatting.

**Why is this needed**: Make the documentation formatting more consistent.

**Comment by RiyaGoel27** [comment]
Can I work on this?

**Comment by oddlittlebird** [comment]
Go for it!

**Comment by RahilRehan** [comment]
I can fix these.

**Comment by RahilRehan** [comment]
Some first columns have queries etc in them,  should I un-italisize them?
Example:
![query](https://user-images.githubusercontent.com/29269254/94758510-f2f6e800-03ba-11eb-86f0-410896246ade.PNG)

**Comment by oddlittlebird** [comment]
Yes, please do. Those should not be italicized. Queries like those should be code format instead.

**Comment by jartigag** [comment]
i could resume this. may i?

**Comment by RahilRehan** [comment]
please proceed @jartigag
