### ISSUE TITLE
Make note format consistent

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#27820]
**What would you like to be added**: Currently the notes, warnings, cautions, and tips (mostly notes) in the Grafana documentation are inconsistently formatted. Review usage and make consistent throughout.

**Correct:**
```
> **Note:** Note that this note is indented, in sentence case, and has the colon inside the bold formatting.
```

**Incorrect:**
```
**NOTE:**
_Note:_
**Note.**
**Note**:
```

**Why is this needed**: Make the documentation more consistent and professional. Raise the quality of our technical documentation.

**Comment by RahilRehan** [comment]
I can work on this one.
