### ISSUE TITLE
Add aggregate method (OpenTSDB branch:next)

### ISSUE THREAD

**Issue by HallsHalls** [grafana/grafana#2782]
Hi,I found that the lastest OpenTSDB branch can support many aggregates method and we can add all of this ; That would be great !

the photo is screenshot form the native  TSD query page

![2015-09-20 17 13 06](https://cloud.githubusercontent.com/assets/9986416/9980027/d5dc4f38-5fbb-11e5-9ba9-7672489e404d.png)

**Comment by torkelo** [comment]
how does this relate to this issue ? https://github.com/grafana/grafana/pull/1646

**Comment by HallsHalls** [comment]
@torkelo yeah, all of those

**Comment by torkelo** [comment]
ok, will close this then, as there already is #1646
