### ISSUE TITLE
Autocomplete in custom config editor

### ISSUE THREAD

**Issue by dkozar** [grafana/grafana#27836]
I've build a custom ConfigEditor, which has a couple of fields.

Initially, although the values have never been set, the autocomplete adds some values:

![image](https://user-images.githubusercontent.com/1078403/94339834-dcd0dc80-fff4-11ea-9d5e-7aa76e15da96.png)

This could be frustrating, especially for the user installing the plugin.
I've also made sure that autocomplete is "off:

![image](https://user-images.githubusercontent.com/1078403/94339844-038f1300-fff5-11ea-8922-f6ee8713258e.png)

It looks like the autocomplete kicks in on some browsers (Chrome, Firefox). It doesn't happen on Edge.

Probably it's not enough to switch it off on the fields, and the autocomplete [should be switched off on the form also](https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion):

`<form method="post" action="/form" autocomplete="off">`

Now, I realized that the values autocomplete adds are actually the username/password which I use for logging into Grafana.

So, I temporarily removed the last (secure) field, and the autocomplete didn't kick in on the previous field:

![image](https://user-images.githubusercontent.com/1078403/94339935-c8411400-fff5-11ea-8fc8-107f58c83c30.png)

So I guess, there is some browser logic in place: when it spots the password field, it assumes this is a password to enter the site, and populates it with a password, and also populates the previous field with username.

**Comment by aocenas** [comment]
Not sure right now if this is a bug report or a question and if question what exactly is it. Do you think there is something Grafana should do about this autocomplete behaviour?

**Comment by dkozar** [comment]
Sorry for not being clearer. It is a question for others if they are experiencing the same issue.

At the same time, it's a proposed fix. Since I didn't managed to fix it by putting `autocomplete="off"` to the input element itself - based on the docs I linked above - putting the `autocomplete="off"` on a form element might switch the autocomplete.

However, the plugin builder (i.e. me) doesn't have control over the piece of code rendering the `<form>` element (we're using `<FormField>` and `<SecretFormField>`elements only, which render the children of `<form>` element).

**Comment by aocenas** [comment]
Hmm so not sure we have any guidelines for this and also not sure if removing the autocomplete is the desired behavior even though I agree it could be annoying.

@dprokop or @jessover9000 do we have any opinion on this from UX perspective?

**Comment by dkozar** [comment]
Thanks for the answer @aocenas. Well, in this particular case the autocomplete happens because the browser thinks it found the password field, it assumes the previous filed is username, so it auto-fills in the username/password. So, it's pretty chaotic and unpredictable.

If I remove the secure field, this doesn't happen.

**Comment by dprokop** [comment]
@dkozar this is quite weird, to be honest, and I can't recall any reports on that or experiencing this behavior. Can you try providing `autocomplete="new-password"` (ref: https://developer.mozilla.org/en-US/docs/Web/Security/Securing_your_site/Turning_off_form_autocompletion) to your secret field and see if the autocompletion will still kick in?

**Comment by dkozar** [comment]
@dprokop thanks, it worked! 👍 🥇 

Before:

![Snag_42a2327](https://user-images.githubusercontent.com/1078403/94673985-70fdb500-030f-11eb-87c6-2080247c4b88.png)

With `autocomplete="new-password"` on "Client secret" field:

![Snag_42a3a58](https://user-images.githubusercontent.com/1078403/94673995-74913c00-030f-11eb-9d96-76dcb12d288c.png)
