### ISSUE TITLE
Query text time series does not display the text

### ISSUE THREAD

**Issue by netbix** [grafana/grafana#27832]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.0
- Data source type & version:
- OS Grafana is installed on: centos 7
- User OS & Browser:
- Grafana plugins: zabbix 4.0.1
- Others:

![immagine](https://user-images.githubusercontent.com/66208491/94318845-ae69e780-ff89-11ea-90aa-685b9bbe2f13.png)

I have downgrade to 7.1.5 and work (the photo is related to version 7.1.5) in version 7.2.0 nothing is displayed

**Comment by aocenas** [comment]
@alexanderzobnin can you take a look at this? Don't have zabbix set up so not sure how to try to reproduce this.

**Comment by ghost235** [comment]
The same with zabbix 5.0.1.

But in the "Query inspector" in grafana the values are present. Seems its a grafana "display" issue.

**Comment by alexanderzobnin** [comment]
Hi! What's a panel you're using? Can you show panel configuration?

**Comment by netbix** [comment]
i updated grafana to 7.2.0 again and now here's the problem:
![image](https://user-images.githubusercontent.com/66208491/95241018-83935500-080d-11eb-87ba-51ca3d8d8eb2.png)

**Comment by netbix** [comment]
![image](https://user-images.githubusercontent.com/66208491/95241224-c0f7e280-080d-11eb-89ff-e64be9532301.png)

**Comment by netbix** [comment]
hostname and system information in zabbix exist
![image](https://user-images.githubusercontent.com/66208491/95241584-42e80b80-080e-11eb-9624-c57284077115.png)

**Comment by netbix** [comment]
![image](https://user-images.githubusercontent.com/66208491/95242619-b50d2000-080f-11eb-97e6-46cc32bfd493.png)

**Comment by netbix** [comment]
I have downgrade grafana to 7.1.5 and this is query isspect 

{
  "request": {
    "url": "api/datasources/1/resources/zabbix-api",
    "method": "POST",
    "data": {
      "datasourceId": 1,
      "method": "history.get",
      "params": {
        "output": "extend",
        "history": "1",
        "itemids": [
          "62728"
        ],
        "sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1601989112,
        "time_till": 1602010712
      }
    }
  },
  "response": {
    "result": [
      {
        "clock": "1601990728",
        "itemid": "62728",
        "ns": "993149437",
        "value": "Linux va 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64"
      },
      {
        "clock": "1601994328",
        "itemid": "62728",
        "ns": "412969488",
        "value": "Linux va 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64"
      },
      {
        "clock": "1601997928",
        "itemid": "62728",
        "ns": "897866529",
        "value": "Linux va 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64"
      },
      {
        "clock": "1602001528",
        "itemid": "62728",
        "ns": "702534913",
        "value": "Linux va 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64"
      },
      {
        "clock": "1602005128",
        "itemid": "62728",
        "ns": "764696895",
        "value": "Linux va 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64"
      },
      {
        "clock": "1602008728",
        "itemid": "62728",
        "ns": "138734680",
        "value": "Linux va 4.15.0-118-generic #119-Ubuntu SMP Tue Sep 8 12:30:01 UTC 2020 x86_64"
      }
    ]
  }
}

**Comment by netbix** [comment]
I have upgrade to grafana 7.2.1 but the problem persist
![immagine](https://user-images.githubusercontent.com/66208491/95793241-71ba2200-0ce5-11eb-8843-03dfaaadab30.png)

Zabbix 4.4.10

**Comment by netbix** [comment]
I have upgrade grafana to 7.3.1 but the problem persist

**Comment by netbix** [comment]
I have resolve, in the text filter i have put * and delete .... refresh et voila !
![immagine](https://user-images.githubusercontent.com/66208491/98037724-4fb34b80-1e1c-11eb-8019-d68d79c54fa3.png)
