### ISSUE TITLE
Not clear 100% on Y-Axis in the graph

### ISSUE THREAD

**Issue by ShadowScorpion** [grafana/grafana#2784]
Hi, I got the next issue. There is screenshot with graph and you will see what the minimum and maximum value are 100%. Why in Y-Axis it show me only 99.9975%? Can someone help me fix this?
![grafana](https://cloud.githubusercontent.com/assets/4012947/9989150/cc27f62e-605e-11e5-9cc8-4d2c04268c72.PNG)

P.S. In configuration "Left Y Axis" I set maximum value 100.
And I have the same graph from other server, and with the same 100% values, but Y Axis is ok.

**Comment by torkelo** [comment]
What is you Y min value? 

Also what is your metric query?  

If you want 100% you need to set Grid min to zero. otherwise the auto grid min/max will kick in.

![image](https://cloud.githubusercontent.com/assets/10999/9989213/f3be89b2-6056-11e5-9be3-50e242d6c0a1.png)

**Comment by ShadowScorpion** [comment]
Thank you! It's really helped me!
