### ISSUE TITLE
Failed to login using github: Error getting team memberships

### ISSUE THREAD

**Issue by razuos** [grafana/grafana#27845]
**What happened**:
While trying to signup to my grafana instance using github-oauth, an error occurred:

![Screenshot from 2020-09-27 23-34-49](https://user-images.githubusercontent.com/25522009/94384957-3aab1480-011a-11eb-8284-eb009d541cca.png)

Looking at the logs i can see that this error is related:

```
grafana-666c9764dd-bznxb grafana t=2020-09-28T02:32:29+0000 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="Error getting user teams: Error getting team memberships: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#list-teams-for-the-authenticated-user\"}"
grafana-666c9764dd-bznxb grafana t=2020-09-28T02:32:29+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=10.228.0.202 time_ms=1485 size=1744 referer=https://github.com/
```

It seems like the instance is reaching the wrong endpoint or i dont have any associated teams with my account (which i have).

**What you expected to happen**:

Being able to sign up using github-oauth.

**How to reproduce it (as minimally and precisely as possible)**:

These are my environment variables:

```
- name: GF_SERVER_ROOT_URL
  value: https://grafana.mydomain/
- name: GF_SECURITY_ADMIN_USER
  value: ####
- name: GF_SECURITY_ADMIN_PASSWORD
  value: ####
- name: GF_AUTH_GITHUB_ENABLED
  value: "true"
- name: GF_AUTH_GITHUB_ALLOW_SIGN_UP
  value: "true"
- name: GF_AUTH_GITHUB_CLIENT_ID
  value: ####
- name: GF_AUTH_GITHUB_CLIENT_SECRET
  value: ####
- name: GF_AUTH_GITHUB_SCOPES
  value: user:email;read:org
- name: GF_AUTH_GITHUB_AUTH_URL
  value: https://github.com/login/oauth/authorize
- name: GF_AUTH_GITHUB_TOKEN_URL
  value: https://github.com/login/oauth/access_token
- name: GF_AUTH_GITHUB_API_URL
  value: https://api.github.com/user
- name: GF_AUTH_GITHUB_ALLOWED_ORGANIZATIONS
  value: ####
```

**Anything else we need to know?**:

I'm trying to only allow a private organization.

EDIT: I've also tried to singup using an anonymous tab on my browser, just to make sure.

**Environment**:
- Grafana version: v7.1.1 (3039f9c3bd)
- Data source type & version: N/A
- OS Grafana is installed on: Official docker image on kubernetes
- User OS & Browser: Ubuntu 20.04, Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by edijsdrezovs** [comment]
Any news on this one?

**Comment by razuos** [comment]
None as far as i know, still doesn't work

**Comment by marefr** [comment]
Are you sure you have configured the correct permissions in github? See https://docs.github.com/en/rest/reference/teams#list-teams-for-the-authenticated-user for details

**Comment by dsotirakis** [comment]
@razuos Hello! Thanks for raising the issue, is this still the case or can this be closed?

**Comment by kminehart** [comment]
I'm going to try to reproduce this one.

**Comment by kminehart** [comment]
This definitely happens on 7.1.1.

```
EROR[08-16|18:23:26] login.OAuthLogin(get info from github)   logger=context userId=0 orgId=0 uname= error="Error getting user teams: Error getting team memberships: {\"message\":\"Not Found\",\"documentation_url\":\"https://docs.github.com/rest/reference/teams#list-teams-for-the-authenticated-user\"}"
EROR[08-16|18:23:26] Request Completed                        logger=context userId=0 orgId=0 uname= method=GET path=/login/github status=500 remote_addr=172.17.0.1 time_ms=1000 size=1744 referer=http://localhost:3000/
```

**Comment by kilotone** [comment]
- name: GF_AUTH_GITHUB_SCOPES
  value: user:email;read:org
  
The semicolon in the value above causes the error.
