### ISSUE TITLE
Url redirect when running https

### ISSUE THREAD

**Issue by PhilSmithABB** [grafana/grafana#27857]
**What would you like to be added**:
When running with https grafana should be able to configure a HTTP redirect for the same hostname but for a different port. For example: I'm running my instance of grafana at https://www.example.com/ on port 443, grafana would also be able to listen on port 80 so requests to http://www.example.com get redirected to https.

**Why is this needed**:
Running a separate webserver process, such as IIS, just to issue a redirect from http to https wastes server resources and increases maintenance overheads.

**Comment by torkelo** [comment]
Think use cases like this is best handled by putting a fully-featured reverse proxy in front of Grafana (like nginx). But will leave this open as a feature request

**Comment by jonnor** [comment]
This feature is still relevant. It is a rather large increase in complexity to have to run an HTTP proxy for this purpose alone. For example, many platform-as-a-service options (such as Heroku, Dokku, etc) will have an HTTP proxy that terminates TLS, but not have an enforce-https-redirect option. Therefore, it would be very nice if the logic was in Grafana, then one can just switch it on with an environment variable.
Would you accept a contribution that adds the necessary code into Grafana?

**Comment by jonnor** [comment]
Was also requested in https://github.com/grafana/grafana/issues/10175
