### ISSUE TITLE
Table Header is not moving when we scroll towards right when at 100% Zoom level in browser.

### ISSUE THREAD

**Issue by dheeruymv** [grafana/grafana#27856]
![Capture](https://user-images.githubusercontent.com/65417565/94419883-fa42a980-01a0-11eb-89a1-5a0696f028a3.PNG)

Attached the screenshot where at 100% zoom level, the table header is not moving along with the table content. 

If we reduce the zoom level, it would be difficult to read the details. I couldn't get any info on this in any of the threads, so raising a bug for it.

This comes under usability, when the end user see's it is difficult to co-relate the data/content with header

**Environment**:
- Grafana version: 6.2.2
- Data source type & version: Mysql(Maria DB)- 10.3.20-MariaDB
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10, Chrome

**Comment by torkelo** [comment]
switch to new table panel (open panel edit and click the table panel in the visualization selector)

**Comment by dheeruymv** [comment]
> switch to new table panel (open panel edit and click the table panel in the visualization selector)

@torkelo : It is not working. Please find the screenshot.

do we need to switch to new grafana version? Please correct me, if i am doing anything wrong here.

![image](https://user-images.githubusercontent.com/65417565/94533913-68e53d00-025d-11eb-985e-eb0ccaf3281e.png)

**Comment by torkelo** [comment]
you need to upgrade to 7.x to be able to switch to new table panel

**Comment by dheeruymv** [comment]
> you need to upgrade to 7.x to be able to switch to new table panel

Thanks for the info.
