### ISSUE TITLE
7.2: stackdriver query render the wrong project

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#27855]
**What happened**:
The project selector inside Stackdriver query always render the default one, no matter of project is really use

**What you expected to happen**:
To see the current project selected

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a stackdriver datasource (probably with GCE authentification)
2. Create panel with the DS
3. Create a query and try to select another project
4. Query send to stackdriver use the project selected, but the UI display the default project

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: stackdriver
- OS Grafana is installed on: kubernetes + official helm chart
- User OS & Browser: Chrome 85.0.4183.102 + MacOS 10.14.6

**Comment by baelish** [comment]
To add to this when using the GCE Default service account in our GKE container I can see the local project perfectly well but when I select a different project things are not working. (I have granted the service account permissions for several accounts). The data source page does state you need to create one data source per project but this does seems odd considering that when you add a metric you can select the project you want to use.

**Comment by bjakubski** [comment]
I have the same issue. GCE authentication, service account with access to multiple projects.
The UI selector is "fixed" to the project grafana is running in. As OP mentioned queries are sent to selected project (even if project shown is different), but also any change in query parameters will reset the project to the "default" one.

I've tested also grafana 7.1.0 and problem does not exist there

**Comment by jvasallo** [comment]
We are seeing something similar as mentioned. The dropdown for us is fixed to the default project in the StackDriver settings. Here is a view of what we are seeing, hope this helps!
![](https://i.imgur.com/9nqLjZv.gif)
