### ISSUE TITLE
Add division formula to [Edit Panel -> Transform -> Add field from calculation -> Calculation]

### ISSUE THREAD

**Issue by HongChenTW** [grafana/grafana#27853]
**What would you like to be added**:

Division to `Add field from calculation` Calculation support list.

**Why is this needed**:

For example, if we want to calculate percentage of 2 queries(A query/B query), currently it can only be fulfilled with [MetaQueries](https://github.com/GoshPosh/grafana-meta-queries) datasource plugin and the plugin is not compatible with grafana well since we upgraded to grafana 7.1.5.

Also, is grafana planning to have a multi-datasource with multi-query mechanism like MetaQueries? I think it's extremely helpful and flexible to be not limited by queries result for rendering panel.

**Comment by aocenas** [comment]
You can use division if you use binary mode in the transformation:
![Screenshot from 2020-09-29 17-40-03](https://user-images.githubusercontent.com/1014802/94581093-f4b99200-027a-11eb-9d79-271d47e7f3c7.png)

Also you can use mixed data source to add queries from different data sources to single panel:
![Screenshot from 2020-09-29 17-40-20](https://user-images.githubusercontent.com/1014802/94581139-056a0800-027b-11eb-81ee-22b9cf9660d4.png)

Will close this but please reopen if this does not provide the functionality you want.
