### ISSUE TITLE
Elasticsearch: add support for filters aggregation 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2785]

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/9996596/054c7320-6088-11e5-86cc-9eb3449bf394.png)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/10000852/e6a3f0da-609e-11e5-9e7c-d4efdfad8f7c.png)

**Comment by aodj** [comment]
Tried this out in the latest snapshot. It's so nice!
