### ISSUE TITLE
default time range value on grafana

### ISSUE THREAD

**Issue by ShadowScorpion** [grafana/grafana#2786]
Hi, help me in setting default time range on dashboard of grafana. Have grafana some setting, which can set the default time range?
Because for example if i set 2 days and again go to link of dashboard, it again show me for the 2 days data, but need set some default value for example 7 days (which i exactly set it by default)

**Comment by torkelo** [comment]
I do not really understand your English. 

You can change time range in the time picker, and Save that will then become the default when someone opens the dashboard again.

**Comment by ShadowScorpion** [comment]
Sorry about that.
So my question in steps :
1) Setting time range on 7 days :
	( How I can set this time range to default value? )
![timerange7d](https://cloud.githubusercontent.com/assets/4012947/9990704/ff4c743c-606b-11e5-876a-0a4abdcec85d.PNG)
2) Change to 2 hour (for example)
3) Close the tab in browser 
4) Open again and receive again 2 hour time range, but need 7 days.

So, question how I can set it by default?

**Comment by torkelo** [comment]
by saving the dashboard  :)

**Comment by Culmert** [comment]
Old thread, but I was going nuts over this until I realized that:
  _You have to check the checkbox "Save current time range" when saving the dashboard._ 
Pretty obvious once you see it, but it took me about 8 weeks of mild irritation before I finally noticed...

**Comment by andbuitra** [comment]
@Culmert So that's what that button was supposed to do... Welp haha. Thank you for helping me notice it! :)

**Comment by Jostar1024** [comment]
Can we change the default time range, i.e. from `now-6h` to `now`, when creating a new dashboard ?

**Comment by phplego** [comment]
Same problem here.

Version: Grafana v6.2.5 (6082d19)

There is no option "Save current time range"
![image](https://user-images.githubusercontent.com/3162688/62130283-5ed65000-b2e1-11e9-9d96-353d97113c26.png)

![image](https://user-images.githubusercontent.com/3162688/62130329-74e41080-b2e1-11e9-84bb-8e6cc7f6fc7d.png)


The time range **resets to 7 days every time I open the dashboard. No metter was it saved or not**

**Comment by sumanthkethe** [comment]
Same problem, unable to change the default time - it always defaults to 6 hours when closing and opening the browser.

**Comment by sumanthkethe** [comment]
Even after clicking the save checkbox, once you come back to the dashboard by going to home page or some other folder, it's defaulting to 6 hours

**Comment by WelterRocks** [comment]
Same here. Seems to have something to do with the JSON model. If you open the preferences for the dashboard, switch to the JSON model tab and than scroll to the end (maybe, or search for "time"), you can change the value and save the model. For example:

`  "time": {
    "from": "now-6h",
    "to": "now"
  },`

**Comment by alice-deryl** [comment]
I know this issue is closed, but unfortunately I'm still having the exact same problem.  I have done exactly as above, ie I set

"time": { "from": "now-30d", "to": "now" }

then saved the dashboard because I want the dashboard to open on the last 30 days by default.  But when I close the dashboard and reopen, it has reset to 'Last 6 hours' on the timepicker, and the json file has also changed to 

"time": { "from": "now-6h", "to": "now" }.

Driving me crazy!  Any help appreciated
