### ISSUE TITLE
Grafana Transform problem with metrics same name

### ISSUE THREAD

**Issue by cesarmacias** [grafana/grafana#27865]
**What happened**:

When order or merge two tables, if have one same metric name (Example Unique Count) but to different field in the transform table only appear the metric name without the field name:

![image](https://user-images.githubusercontent.com/492320/94464766-81cdef80-0184-11eb-84e2-3bf1c7f922db.png)

![image](https://user-images.githubusercontent.com/492320/94464829-990cdd00-0184-11eb-95e3-666faa94f755.png)

And cant change the name of the column independently, because both appear only once, or apply override.

**What you expected to happen**:

the name of column have to be metric name + field name

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Elasticsearch 7.X
- OS Grafana is installed on: Red Hat 7.8

**Comment by torkelo** [comment]
Can you try latest master (7.3 nightly) https://github.com/grafana/grafana/pull/27963
