### ISSUE TITLE
NewsPanel: Should refresh list on dashboard refresh or time range change

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#27869]
Currently the only way to refresh news panel is to reload the dashboard. 

The list should update on dashboard refresh or time range change

**Comment by ryantxu** [comment]
See also:
https://github.com/grafana/grafana/issues/17361

**Comment by limpasha** [comment]
Hi! I think this feature would be really useful as I consider using "News plugin" for displaying alerts from our custom alerting system. Thus integrating it via RSS seems like the best way to do it.

Are there any updates on it?
