### ISSUE TITLE
Loss of login session (cookie expiry) also causes loss of URL

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#27874]
**Current (undesired) behavior**
I keep a number of Grafana tabs open at all times. Grafana regularly loses my session when a cookie expires, which isn't unusual. Unfortunately this means that when I log back in, I'm directed to the Home screen rather than the URLs I had been at previously and have to spend some time reconfiguring my tabs to have the right dashboards.

**Desired behavior**
"Re-authenticate" behavior maintains the originally requested URL and sends the user there once logged in. This actually works as expected if I have a URL for a dashboard and I'm not logged in—navigating to that URL with a "hard" page request from the browser gets intercepted with the "login" page, but then proceeds to the correct page. However, an expired cookie and AJAX refresh (not full-page refresh) sends me to a login page that does not then proceed to the original page.

**Steps to reproduce the problem**
1. Go to a dashboard 
2. Delete Grafana cookie 
3. Refresh dashboard with Grafana dashboard "refresh" button (not browser refresh) 
4. Log in when prompted

Version: grafana v7.1.5

**Comment by torkelo** [comment]
Think it's due this line https://github.com/grafana/grafana/blob/master/public/app/core/services/backend_srv.ts#L43 

on 401 response we just send the user to that page that then redirects to login. Think if we instead did a full page reload the backend should redirect the user to the login page with the correct page remembered
