### ISSUE TITLE
Alerting: Allow more states on execution error or timeout

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#27877]
**What would you like to be added**:
Allow to use the same possible alert states during an `If execution error or timeout` that are available for `If no data or all values are null`

**Why is this needed**:
In our case, we use a separate alert that checks the availability of databases. When it fires, we need all other alerts not to fire.

The problem is that if the error state is set to `Keep Last State` and the alert fired at the time of the loss of connection with the database:
 - the message is enriched with execution error information - this makes the AlertManager think that the alert state has changed
 - alerts continue to hang on the board and distract from the `database` alert. I will clarify that you can use inhibition rules - but in this case, notifications on suppressed alerts after  `database` alert completion will come with a  `resolve_timeout` delay

**Comment by torkelo** [comment]
>  and the alert fired at the time of the loss of connection with the database:

Why did it fire?

**Comment by M0rdecay** [comment]
"No Data" and "OK", yes.

**Comment by marefr** [comment]
Thanks. Sorry, but this request doesn't make sense to me so I'm closing it. Maybe you can find some other way to get around this limitation you've seen to have identified. In addition, we're currently working on next gen alerting engine where I think we're leaning towards simplifying the states even more, but we'll see what that ends up in eventually.
