### ISSUE TITLE
Drilldown Title doesn't handle variable like General Title

### ISSUE THREAD

**Issue by rschitz** [grafana/grafana#2787]
![2015-09-21_14-01-14](https://cloud.githubusercontent.com/assets/8385646/9991352/9dcd68c6-6069-11e5-86bc-bfec2e2e89a1.gif)

**Comment by torkelo** [comment]
this was fixed in 2.1.3 , and in master (next release 2.5) the drill down links are easier to reach, 

![](
https://cloud.githubusercontent.com/assets/10999/9976491/58765064-5ee6-11e5-8fa2-69b9e7def545.gif)

**Comment by rschitz** [comment]
this is on 2.1.3

**Comment by torkelo** [comment]
sorry, missed the fact that the issue was only in the hover tooltip and not in the normal drilldown link. Have fixed the issue in latest  master. Thanks for reporting this, and for including a gif animation that showcases the problem!

**Comment by rschitz** [comment]
Your Welcome. Just tested with Grafana version: 2.5.0-pre1, commit: v2.1.2+409-g9de016b, build date: 2015-09-21 12:07:03 : same behavior
