### ISSUE TITLE
Inconsistent z-index behavior for small screens

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#27876]
In a wide dashboard view, the z-index can cover the next panel:

![image](https://user-images.githubusercontent.com/705951/94500494-4e0abe00-01b4-11eb-8b14-2b7a43fa64e0.png)

With the same panel in the more narrow view, it gets clipped:
![image](https://user-images.githubusercontent.com/705951/94500515-5fec6100-01b4-11eb-8553-842b22a0a7fd.png)

**Comment by torkelo** [comment]
Strange, can you create a dashboard on play site that replicates this? I was unable to

**Comment by Sulomus** [comment]
This issue still persists! Could this be please solved?

Using Grafana Cloud.
