### ISSUE TITLE
The way dashboards are stored in the database could be massively improved

### ISSUE THREAD

**Issue by Jerome-Paddick** [grafana/grafana#27873]
Currently in the database, for each dashboard: every panel, request, alert etc for the entire dashboard are stored in a single piece of json in a single field in the db.  the same json you can find in the "JSON Model" on the frontend.

This seems really restricting from a features point of view for a number of reasons:
- panels or alerts cannot be reused across dashboards
- if there are multiple dashboards with the same panel, then they have to be updated one by one
- adding or removing a panel to a dashboard programmatically is a massive pain and can easily break the entire dashboard

**What would you like to be added**:

Make a panels and alerts table, and link them to the dashboard by a many to many relationship, The json can be created on the fly which admittedly would be a slightly heavier request

**Why is this needed**:

Easier to create and maintain dashboards, reuse of panels and alerts, more scalable projects

**Comment by torkelo** [comment]
Agree! 

We are working on reusable (shared) panels between dashboards (and will have separate database table). https://github.com/grafana/grafana/issues/1803

Same for new alerting system, alert rules will be created and edited outside of dashboards (so not part of a dashboard or panel json).

**Comment by Jerome-Paddick** [comment]
Good stuff, looking forward to it
