### ISSUE TITLE
Grafana 7.1.5 version login not working in Google Chrome. After entering username, password and hit login-> just redirects to login page again n again..

### ISSUE THREAD

**Issue by VinayDanda** [grafana/grafana#27889]
![grafana_7 1 5-issue](https://user-images.githubusercontent.com/33858700/94556688-22064000-027b-11eb-9c75-4b9778610c74.PNG)
![grafana_7 1 5-afterlogin-page](https://user-images.githubusercontent.com/33858700/94556826-5aa61980-027b-11eb-84fb-76f62b64009c.PNG)

**What happened**: Grafana 7.1.5 version login not working in Google Chrome. After entering username, password and hit login-> just redirects to login page again n again..

**What you expected to happen**: Login to happen properly.

**How to reproduce it (as minimally and precisely as possible)**: Try 7.1.5 version in Google Chrome

**Anything else we need to know?**: Its working properly in updated Firefox, Microsoft Edge browsers. Problem only in chrome.

**Environment**: 
- Grafana version: 7.1.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Windows, Chrome
- Grafana plugins:
- Others:

**Comment by mojatt** [comment]
Issue is also apparent in  v6.7.4 (8e44bbc5f5). An issue with latest Chrome version?

**Comment by folhabranca** [comment]
same here with Grafana 7.2.0 and Chrome 85

**Comment by torkelo** [comment]
probably same issue as others report in https://github.com/grafana/grafana/issues/27802 

Check your cookie_secure or your cookie_samesite option
