### ISSUE TITLE
Flux and Transformations: unable to join by Time with mixed Query

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#27882]
**What happened**:
When adding a normal influxdb query and a flux query to the same panel, with the same time interval, I tried creating a trasnformation to join them by time and display them in a table. I get a table with the correct timestamps, but the column where the flux values are supposed to be show are empty. 

In the transformation debugger I see the following input for the normal query:

![image](https://user-images.githubusercontent.com/9944663/94536838-1860e600-0243-11eb-9476-d7464e316cba.png)

For the flux query:

![image](https://user-images.githubusercontent.com/9944663/94537019-375f7800-0243-11eb-9896-740395fec050.png)

In the transformation result, the flux values are all null. The join on Time seems to have worked because both the time column and the value columns all have the same number of rows as the input, only the values are null.

![image](https://user-images.githubusercontent.com/9944663/94537593-5f4edb80-0243-11eb-9de0-ec5b015848c3.png)

**What you expected to happen**:
The values to show up.

**How to reproduce it (as minimally and precisely as possible)**:
Create a normal influxDB query and a Flux query for the same intervals, and then add a transformation to join by Time.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Influxdb 1.8 / Flux
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome

**Comment by coussej** [comment]
Turns out you're not even able to plot a graph with a mixed query.

A workaround would me to ad the following before you yield the flux result. There has to be an explixit **Time** column for it to work, the default _time column doesnt work with mixed queries.
```
...
|> map(fn: (r) => ({Time: r._time, YOUR_SERIES_NAME: r._value }))
|> yield()
```

**Comment by torkelo** [comment]
Try the merge transform. 

What is the result from all your queries? (the table structure)

**Comment by coussej** [comment]
Hi @torkelo , 

the merge transform is the reason it's not working "out of the box", but after some consideration I'm thinking this might be the expected behaviour. Simple example to reproduce:

Query A (InfluxQL):
```
SELECT mean("value") FROM "WP1_fill_level" WHERE $timeFilter GROUP BY time($__interval) fill(null)
```

Query B (Flux, same data at same interval):
```
from(bucket: "simulation_tanksystem")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "WP1_fill_level")
  |> aggregateWindow(every: v.windowPeriod, timeSrc: "_start", fn: mean)
```

When configuring these two queries, the merge transform doesn't give any option, because both results don't have any colums in common. The time column is a normal flux query is called `_time`, not `Time`:

![image](https://user-images.githubusercontent.com/9944663/95310351-9a2cc100-088c-11eb-89d0-8691208238d0.png)

When adding the following line to the end of the flux query, the merge succeeds, but it still does not give you any option to select a column to merge on:
```
  |> map(fn: (r) => ({Time: r._time}))
```

**Comment by torkelo** [comment]
merge will join on all columns with matching name

**Comment by torkelo** [comment]
if you only want to join on one field use seriesToColumns
