### ISSUE TITLE
Support CloudFront Additional Metrics

### ISSUE THREAD

**Issue by Jeinhaus** [grafana/grafana#27891]
In 2019 CloudFront introduced optional "Additional Metrics" to CloudFront Distributions that expose metrics such as "Cache Hit Rate", "Origin Latency" and "Error Rate". Here's the introductory [blog post](https://aws.amazon.com/about-aws/whats-new/2019/12/cloudfront-realtime-metrics/?nc1=h_ls).

**What would you like to be added**:

It would be great if the CloudWatch Grafana data source could expose these Additional Metrics if they are available for a given Distribution.

**Why is this needed**:

Monitoring and Alerting of all of the exposed CloudFront metrics.

**Comment by torkelo** [comment]
Think it needs to be added here: https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L44
