### ISSUE TITLE
7.2 Time series. Export time series to CSV returns one column only

### ISSUE THREAD

**Issue by suekag-lukyanov** [grafana/grafana#27896]
**What happened**: For query output in 'Time series' format,  in Tabular visualization with transformation 'Time series to Columns', the action 'Inspect => Data' returns one column only (1st column from transformed tabular view).

**What you expected to happen**:   action 'Inspect => Data' has to return all columns (up to 1600 columns).

**How to reproduce it (as minimally and precisely as possible)**: use Tabular visualization with transformation 'Time series to Columns' for  'Time series'. Data set example: ('2020-01-01', '100.00', 'server A'), ('2020-01-02', '101.00', 'server B'),...

**Anything else we need to know?**: no problem when the query output format is 'Table'.

**Environment**:
- Grafana version: Grafana v7.2.0 (efe4941ee3)
- Data source type & version: Linux rpm repo with baseurl=https://packages.grafana.com/oss/rpm
- OS Grafana is installed on: Linux CentOS 7.8.2003
- User OS & Browser: Windows 10, Google Chrome Version 85.0.4183.102
- Grafana plugins: 
  - grafana-image-renderer
  - grafana-worldmap-panel
  - larona-epict-panel
  - natel-plotly-panel
  - savantly-heatmap-panel
  - grafana-simple-json-datasource
  - ilgizar-candlestick-panel
  - mtanda-histogram-panel
  - ryantxu-ajax-panel
  - simpod-json-datasource

- Others: none.

![example1](https://user-images.githubusercontent.com/47668749/94569903-866ed280-026e-11eb-824b-5e6e90371c22.png)

**Comment by torkelo** [comment]
Can you switch to new table panel? (open panel edit and switch to table visualization), then apply join or merge transform
