### ISSUE TITLE
Inspect: No way to view raw data for angular panels 

### ISSUE THREAD

**Issue by suekag-lukyanov** [grafana/grafana#27899]
****What happened**:  when the numeric values in panels with "Graph" and "Table" visualization have values greater than 10, the action 'Inspect => Data' returns integers (without the mantissa).

**What you expected to happen**:   action 'Inspect => Data' has to return numeric values in the same format as it configured in the relevant panel.

**How to reproduce it (as minimally and precisely as possible)**: use Tabular visualization. 'Table transformation' selector's value is not important. Data set example: ('2020-01-01', '100.01', 'server A'), ('2020-01-02', '100.02', 'server B'),...

**Anything else we need to know?**: no problem when numeric data has values less than 10.

**Environment**:
- Grafana version: Grafana v7.2.0 (efe4941ee3)
- Data source type & version: Linux rpm 
- OS Grafana is installed on: Linux CentOS 7.8.2003
- User OS & Browser: Windows 10, Google Chrome Version 85.0.4183.102
- Grafana plugins: 
  - grafana-image-renderer
  - grafana-worldmap-panel
  - larona-epict-panel
  - natel-plotly-panel
  - savantly-heatmap-panel
  - grafana-simple-json-datasource
  - ilgizar-candlestick-panel
  - mtanda-histogram-panel
  - ryantxu-ajax-panel
  - simpod-json-datasource

- Others: none.

***
Numeric data in Graph panel has correct format:
![Wrong rounding  Example 2 1](https://user-images.githubusercontent.com/47668749/94573726-a6a09080-0272-11eb-8c0d-4b87404bd263.png)

Numeric data in 'Inspect' has the wrong format (rounded up to integer part):
![Wrong rounding  Example 2 2](https://user-images.githubusercontent.com/47668749/94573720-a607fa00-0272-11eb-9d8d-ae0bf2db70c2.png)

***

Numeric data has correct settings in Tabular panel (type=Number, Decimals=2):
![Wrong rounding  Page 1](https://user-images.githubusercontent.com/47668749/94573732-a7d1bd80-0272-11eb-9b61-834d34092787.png)

Numeric data in 'Inspect' has the wrong format (rounded up to integer part):
![Wrong rounding  Page 2](https://user-images.githubusercontent.com/47668749/94573727-a7392700-0272-11eb-9a77-0ae024654569.png)

**Comment by lafrech** [comment]
Same here, with the same limit at 10.

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian Buster (official Grafana package)
- User OS & Browser: Debian Buster + Firefox / Windows 10 + Firefox
- Grafana plugins: None


The graph and query (Inspect -> query) show correct data. Only Inspect -> data and exported CSV are incorrect.

I can't tell if this happened before 7.2.0 and I'm not sure I can't downgrade to test that without screwing up my production instance.

**Comment by torkelo** [comment]
Thanks for reporting this! Need to improve the inspect drawer for angular panels so you can select result and view raw data.

**Comment by hugohaggmark** [comment]
@suekag-lukyanov just I a quick question about this before we start to dig into it.
I'm using the following data:
![image](https://user-images.githubusercontent.com/562238/96080007-62d69980-0eb6-11eb-897e-7e5e2dcdecf2.png)

The default is using "Formatted data" which as you state is incorrect for Graph/Table (Angular versions) Panels as the decimals are incorrect.
![image](https://user-images.githubusercontent.com/562238/96080105-a0d3bd80-0eb6-11eb-8865-37019092d21e.png)

If you turn off "Formatted data" you will see the raw data.
![image](https://user-images.githubusercontent.com/562238/96080094-94e7fb80-0eb6-11eb-9e33-ba932f765462.png)

Just to clarify this issue is about making the "Formatted data" part described above behave as configured in the Panel, right?

**Comment by lafrech** [comment]
I confirm that unticking "Formatted data" solves it for me: the decimals are displayed and exported in the .csv file.

The issue I described happens with the box ticked (default).

I wonder how I didn't see that before. I'm pretty sure I tried that button.

**Comment by hugohaggmark** [comment]
> I confirm that unticking "Formatted data" solves it for me: the decimals are displayed and exported in the .csv file.
> 
> The issue I described happens with the box ticked (default).
> 
> I wonder how I didn't see that before. I'm pretty sure I tried that button.

@lafrech no worries we added the "Formatted/Raw" toggle fairly recently :)

**Comment by mckn** [comment]
After looking into this and having a chat with @hugohaggmark we suggested that the solution to this issue is to migrate to the new table panel. We have planned to introduce an auto-migrate button in this pannel in the `7.4` release so we will be able to close this issue when that one is in place.

**Comment by mckn** [comment]
Closing this issue since the way to resolve this is to migrate to the new table panel available in `7.4`.
