### ISSUE TITLE
Error when testing a rule for an alert based on CloudWatch Logs query that returns no data

### ISSUE THREAD

**Issue by daveychu** [grafana/grafana#27905]
**What happened**:
Error when testing a rule for an alert based on CloudWatch Logs query:

> "tsdb.HandleRequest() failed to convert dataframe "CloudWatchLogsResponse" to tsdb.TimeSeriesSlice: input frame is not recognized as a time series"

The error only happens if there's no data in the period checked.

**What you expected to happen**:
No error, Condition[0]: Eval: false

**How to reproduce it (as minimally and precisely as possible)**:
- Create new panel with Graph visualization
- Under query, select Cloudwatch as data source
- Point query A to a valid log group and edit the query to:
`fields @timestamp, log
| sort @timestamp desc
| stats count(log) by bin(30s)`
- Create alert with condition "WHEN sum() OF query(A, 10s, now) IS ABOVE 0
- Test rule when there are no logs in the period: Error described in this report
- Test rule when there are logs in the period: Condition[0]: Eval: true

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.0.3 (00ee734baf)
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Linux
- User OS & Browser: macOS & Chrome
- Grafana plugins: 
- Others:

**Comment by tolik-u** [comment]
It was fixed in one of the recent version, I updated to 7.2.0  and it fixed the problem

**Comment by aknuds1** [comment]
Closing since it seems to be fixed. Please let us know if it still happens for you in newer versions.
