### ISSUE TITLE
ui-feature-request: move current time range back/forward

### ISSUE THREAD

**Issue by edannenberg** [grafana/grafana#2790]
Apologies if this is already on the roadmap, I'd like to request 2 buttons between the zoom out button and time range selector that enable quick navigation with the current selected time range. 

For example, if the time range is set to last 7d hitting the "move back" button should update the dashboard to show all stats from 2 weeks ago for a 7 day span.

**Comment by torkelo** [comment]
yes, something like this has been reported before :) 
similar to this https://github.com/grafana/grafana/issues/119
