### ISSUE TITLE
Custom data source plugin: "module.js" must be renamed to "module" in order to work

### ISSUE THREAD

**Issue by dkozar** [grafana/grafana#27901]
**What happened**:

I created a custom data source plugin. I've run the `yarn build` command, which created the `dist` folder. I published the plugin by uploading the content of `dist` folder to a remote folder:

`/usr/share/grafana/public/app/plugins/datasource/my-datasource`

This is the contents of the folder:

![image](https://user-images.githubusercontent.com/1078403/94578646-e3b75380-026f-11eb-9738-907a1d66585f.png)

At this point the plugin doesn't actually work. I'm getting the following error:

`Unexpected token '<' Evaluating https://my-server.com/public/app/plugins/datasource/my-datasource/module Loading app/plugins/datasource/my-datasource/module`

![image](https://user-images.githubusercontent.com/1078403/94580605-077b9900-0272-11eb-8a9c-d8ff00dedf2c.png)

However, if I remove the `.js` extension of the `module` file, it starts working as expected:

![image](https://user-images.githubusercontent.com/1078403/94582112-cab0a180-0273-11eb-8367-507ccd6df6b0.png)

**What you expected to happen**:

Plugin working normally without the need of removing the `.js` extension.

**How to reproduce it (as minimally and precisely as possible)**:

- Build a Grafana data source as described [in the tutorial](https://grafana.com/tutorials/build-a-data-source-plugin/#8).
- Create a Grafana instance on Linux server, for instance using the one [offered here](https://azuremarketplace.microsoft.com/en-in/marketplace/apps/grafana-labs.grafana_oss)
- Upgrade Grafana to the latest version [as described here](https://grafana.com/docs/grafana/latest/installation/debian/)
- build your plugin and upload it to Grafana's plugins folder

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Custom data source, similar to Azure Monitor data source
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Azure monitor data source + this plugin

**Comment by torkelo** [comment]
You need to place your custom plugin in the external plugins folder /var/lib/grafana/plugins

**Comment by dkozar** [comment]
Thanks @torkelo, this indeed solved my problem.

Confirming that the path `/var/lib/grafana/plugins` was a right place for my custom plugin.

One note for other users having the same problem: when updating the contents of your custom plugin folder, Grafana must be restarted in order for changes to kick in: `sudo service grafana-server restart`
