### ISSUE TITLE
Chained variables not solved on dashboard load

### ISSUE THREAD

**Issue by nachopv** [grafana/grafana#27910]
**What happened**:
We do have dashboard with multiple chained variables. As stated as best practice [here ](https://github.com/grafana/grafana/issues/9185), in order to prevent the queries of the chained variables we have to following  refresh policy on the variables definition
- Root variable : On dashboard load
- Chained variables : Never

This setup fails when sharing a dashboard link parametrizing the var values. Because we do see that only the root variable is resolved. All  the chained variables are not calculated and therefore the dashboard does not show data

I.E. https://mydomain/d/uid/dashboard-name?orgId=1&var-platform=WAS&var-tenant=global

This screenshot shows that only the root variable is calculated

![image](https://user-images.githubusercontent.com/70150083/94606408-b59b3900-029a-11eb-8a58-74da85b55f5c.png)

**What you expected to happen**:

We would expect that as long as the variables are chained and the root variable is calculated, all the chianed variables to the root variables are calculated too

**How to reproduce it (as minimally and precisely as possible)**:
I attach a sample dashboard with the setup. In order to reproduce it locally 
- just change the queries of the 2 variables 
- change some filter values in order to populate the querystring with variables
- Reload the dashboard

**Anything else we need to know?**:
Dashboard sample attached
[chained-vars-test.txt](https://github.com/grafana/grafana/files/5301399/chained-vars-test.txt)

**Environment**:
- Grafana version: 7.1.3 . Confirmed is happening too on 6.7.3
- Data source type & version: : InfluxDB 5.0.0 ( Influx server 1.8.2 )
- OS Grafana is installed on: CoreOS
- User OS & Browser: Windows 10  &  Chrome 85
- Grafana plugins: None

**Comment by torkelo** [comment]
not sure what you mean, does the chained variables loose their value on reload? Unable to replicate that. 
https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&var-app=fakesite&var-server=web_server_01&var-server=web_server_02&var-interval=1h

**Comment by nachopv** [comment]
Hi @torkelo 

You were missing to set up "server" variable to refresh = "Never" or "On Time Range" in order to reproduce it
Remember we avoid using On dashboard Load for "server" variable to prevent the "server" query to be executed twice on load ( we do it only on the root variable )

![image](https://user-images.githubusercontent.com/70150083/94699398-9227cb00-033a-11eb-90a5-47db0963dbd8.png)

**Comment by nachopv** [comment]
Hi @torkelo  

Did you get a chance to reproduce the issue with my last update regarding the config?

**Comment by torkelo** [comment]
It works even with server set to never, think we might have fixed this in 7.2

**Comment by nachopv** [comment]
Hi @torkelo 
Great, we ll give it a try
Did you test it on the same dashboard playground?
I do see both variables still set to "On Dashboard Load"

**Comment by nachopv** [comment]
Hi @torkelo 
You are right the version fixes the issue when  the the nested vars are set to "Never"
In order to ease things up to regular users editing dashboards , wouldn't it make sense too to  prevent loopings if nested variables are set to "On Time Range"
I mean to have a control to only trigger  1 query per variable when time range is changed
