### ISSUE TITLE
Preserve percentage formatting during CSV export ("Download CVS" button)

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#27913]
**What would you like to be added**:
When use Download CSV option, preserve the percentage format of columns that were formatted as percentages in the table view.

The CSV format supports numbers in percentage format (like `99.5%`), per my tests with importing and exporting CSV files from Excel.

Here is a screencap showing how this does NOT happen right now in the Grafana UI:

![image](https://user-images.githubusercontent.com/10763196/94612621-5aa11c00-0271-11eb-8d88-dfe757b014b3.png)

**Why is this needed**:

For better consistency with formats chosen explicitly in Grafana table view, and easier export/import of these data into Excel or other external tools.

**Comment by torkelo** [comment]
If you switch to new table panel, in 7.2 you can download csv with formatting preserved
