### ISSUE TITLE
is there a "pattern" on how to use influxdb's continous queries, retention policies with grafan atm?

### ISSUE THREAD

**Issue by nonsenz** [grafana/grafana#2792]
hi,

atm i am a bit confused about the state of influxdb continuous queries, retention policies and grafana's way to deal with them. am i wrong, or would be the ideal solution to rollup all influxdb data into less fine grained retention policies via cqs and then query those when changing the time range in grafana automaticaly?
is this possible by using something like 

    select mean(value) from "$timeRange".cpu_value where ...

after i create a continuous query and retention policy for all those time ranges? or this complete nonsense and one should solve this another way?

right now the only way for me to display my crowded dashboard for a timespan > 1d is to have a template variable with a bunch of resolutions (like 10s, 1m, 10, 1h...) and use this variable inside the "group by time" field. and change it accordingly. any ideas?

i am using influxdb 0.9.4.1 and grafana 2.1 right now.

**Comment by torkelo** [comment]
They first introduced generic continous queries in 0.9.4 so will try to use that with retention periods in order to create convention rules so that the right retention policy is used depending on time range
