### ISSUE TITLE
Issue with overriding configuration variables

### ISSUE THREAD

**Issue by mmedal** [grafana/grafana#2793]
Hey Guys,

Running into an issue overriding configuration options when using Version: 2.5.0-pre1, Commit: v2.1.2+294-gb61b7f0 from the grafana-docker build. I'd like to allow anonymous viewing of dashboards, so I attempted to run: `docker run -d -p 3000:3000 -v /var/lib/grafana:/var/lib/grafana -name grafana -e GF_AUTH_ANONYMOUS_ENABLED=true grafana`

However, I was still required to login and upon browsing to the admin panel in grafana, it still showed anonymous auth was disabled.

I next tried to mount the `/etc/grafana` directory and edit the grafana.ini file directly before running the container (this time with `docker run -d -p 3000:3000 -v /var/lib/grafana:/var/lib/grafana -v /etc/grafana:/etc/grafana -name grafana grafana`):

    #################################### Anonymous Auth ##########################
    [auth.anonymous]
    # enable anonymous access
    ;enabled = true

but was still required to login and the admin panel showed that var as being false still.

What am I missing here? Thanks!

**Comment by torkelo** [comment]
that is strange, when I try i with the official docker container, it works.

`docker run -d -p 3000:3000 -e GF_AUTH_ANONYMOUS_ENABLED=true grafana/grafana`

![image](https://cloud.githubusercontent.com/assets/10999/10011482/02b86218-60fb-11e5-8d94-0feae0622822.png)

**Comment by mmedal** [comment]
Interesting, so it appears to be an issue with 2.5.1pre (I did a docker build after cloning the grafana-docker repo locally). When running from grafana/grafana (v 2.1.3), I don't have any problems either. 2.5.1 is obviously not a stable release, but my issue still might be worth looking into as you move forward. I'll change my Dockerfile to build with the current stable release. Thanks!

**Comment by rayprill** [comment]
I see the same with 2.5.0-pre1, commit: v2.1.2+434-g4100c98.
I'm not using docker, though.  Directly running from an rpm deployment and I'm trying to set the override in /etc/grafana/default.ini, and it has no effect.
We want anonymous auth so we can front it with auth at a proxy.

**Comment by torkelo** [comment]
@rayprill are you sure you uncommented the config line (remove the `;`) no one has reported any issue with setting config options, so its a bit strange.

**Comment by rayprill** [comment]
@torkelo thanks much for replying, Torkel.  I'm pretty sure I am doing it correctly.  I am modifying the file at /etc/grafana/grafana.ini with the following:
    [auth.anonymous] 
    # enable anonymous access
    enabled = true
    # specify organization name that should be used for unauthenticated users
    org_name = TestOrganization
    # specify role for unauthenticated users
    org_role = Viewer

Is this correct?  Are my expectations of what anonymous login means correct?  I expect to get to a home screen.  Instead, when I hit http://<myaddr>:3000 it redirects to <myaddr>:3000/login with the following screen:
![grafana 2 5 0-pre1](https://cloud.githubusercontent.com/assets/5552912/10235058/f484141c-6866-11e5-8864-ecf468c4ee19.jpg)

**Comment by torkelo** [comment]
And you are sure there is an organization nmaed TestOrganization ?  no errors in grafana.log about not finding this org?

**Comment by rayprill** [comment]
Ah, thanks again Torkel.  Yes, under admin rights I added that org and it works now.
This begs the question about being able to configure a default organization.  I have the same question as the OP of https://github.com/grafana/grafana/issues/1823 so I can take it up there.  But for now, considering this "problem" of mine a non-issue.  Thanks.
