### ISSUE TITLE
Templating: Share repeated panel in collapsed row results in panel not found

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#27946]
**What happened**:
Panel link is broken. Cause error like `Panel with id 6 not found`.

**What you expected to happen**:
Open the panel which is shared by link.

**How to reproduce it (as minimally and precisely as possible)**:
1. create new dashboard
2. add query type template variable with `On Dashboard Load` option and `Multi-value` option
3. check one template variable value
4. add a panel with panel repeat option, select the step 2 template variable as panel repeat variable
5. move repeated panels inside collapsed row
6. save dashboard
7. expand row
8. check multiple template variable value
9. get panel link which are generated by 8 step (not first panel)
10. open panel link in another browser tab

**Anything else we need to know?**:
I share reproducible dashboard, the Prometheus endpoint is `http://demo.robustperception.io:9090/`.
https://gist.github.com/mtanda/af673739c996e387726d4153c9d16f00

Open this link will reproduce the bug.
http://localhost:3000/d/oFyir-KMk/test-panel-repeat?orgId=1&var-repeat_key=All&from=1601502591231&to=1601524191232&viewPanel=6

**Environment**:
- Grafana version: 7.3.0-pre (0c70308870e1748063b66274941772deba8cb76d)
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by mtanda** [comment]
I think this bug is caused by inconsistent panel id between shared state and open state.

When loading dashboard, panel id is taken by this function (if it is not set).
https://github.com/grafana/grafana/blob/v7.2.0/public/app/features/dashboard/state/DashboardModel.ts#L330-L348

The shared dashboard JSON doesn't include panel id 6 definition because it is generated by panel repeat.
Grafana can't lookup the panel id 6 panel from JSON, and generated panel id could be differ.

**Comment by torkelo** [comment]
Thanks for reporting this. Feels tricky to solve. Might need some fundamental change to how collapsed rows work and repeated panels.

**Comment by mtanda** [comment]
The idea `Evaluating panel repeats even for collapsed rows`, doesn't solve this issue.
If template variable values are server_A, server_C and share server_C link with `viewPanel=2` param.
And, when opening the link if template variable values are server_A, server_B, server_C, the panel id 2 might show server_B graph.
Embed actual scoped variable value is important to get same panel.

**Comment by NyanKiyoshi** [comment]
I think it's the same issue as the following:

1. Have two multi-choice variables with at least two values
2. Have a repeating row with mixed panels:
2.1. A non-repeating one
2.2. A repeating one
3. Collapse the rows
4. Untick a value of the repeating row's variable if all are selected
5. Apply
6. Tick a new value for repeating row's variable
7. Collapse the generated row
8. Cannot see the non-repeating panel

Reproducible Grafana Dashboard: https://gist.github.com/NyanKiyoshi/418bd4314278ad19fb7887089e251ba2 (tried in 7.2.1 and 7.3.4 on Firefox and Chrome). Behavior recorded [here](https://i.imgur.com/5S7qs8v.gif).
