### ISSUE TITLE
how can i limit the group by result?

### ISSUE THREAD

**Issue by jujaryu** [grafana/grafana#2794]
I'm using grafana2.1 with influxDB. Query looks like

SELECT count(value)
FROM test
GROUP BY time($interval) appstart

ant it return >50 results(graph line), most of result is below 3. But what i need is

count(value) > 10.

Maybe in SQL, will works like 

SELECT count(value) AS CNT
FROM test
WHERE CNT > 10
GROUP BY time($interval) appstart

but i don't know how to do in grafana with influxDB.

Waiting for reply

Thank you.

**Comment by torkelo** [comment]
it depends on what you want to  do,  you group by appstart tag, so you get 50 series with different value of appstart? 

So you have 50 series. Do you want to filter the values in each series or do you want sort and limit the NUMBER of series. Say you want to show the TOP 5 series? Or do you only want to limit the values in EACH series to only contain values above a certain threshold. 

```sql
SELECT count(value) AS CNT
FROM test
WHERE CNT > 10
GROUP BY time($interval) appstart
```

I think you can do something like this in InfluxDB. But you would still have a 50 series, the above only filters the values.
