### ISSUE TITLE
Is master branch broken?

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2795]
Error Reproduction steps:

1.Clone the repo from master branch.
2.Build the backend and frontend.
3.Run ./grafana
4.Create New Dashboard -> Add a graph.
5.You ll see an error while loading the graph.

This is the error which I am seeing:
<img width="807" alt="screen shot 2015-09-22 at 7 17 14 am" src="https://cloud.githubusercontent.com/assets/1019609/10009432/63b2714a-60fa-11e5-923c-11b7a76511e8.png">

**Comment by utkarshcmu** [comment]
@torkelo : Graphs are working with a real datasource, so this is not a blocker. But If we just build Grafana right from scratch without any added datasource, the fake or the dummy graphs(like random walk) which used to be there in the blank installation are broken. We do not see those anymore, instead see the above error.

**Comment by torkelo** [comment]
thanks for reporting this, fixed
