### ISSUE TITLE
Allow newlines in template variable query field

### ISSUE THREAD

**Issue by trallnag** [grafana/grafana#27952]
**What would you like to be added**:

Allow the use of newlines in the template variable (Prometheus) query field.

**Why is this needed**:

Most of the time the queries I use for template variables are very short. So I don't need newlines. But for example when I want to calculate the top x series over the whole time range (as recommended [here](https://www.robustperception.io/graph-top-n-time-series-in-grafana)) the queries can get quite long.

But using newlines gives me the following error:

![image](https://user-images.githubusercontent.com/24834206/94785140-74587580-03cf-11eb-9994-6537d8a2d714.png)

Therefore, my queries look like this:

![image](https://user-images.githubusercontent.com/24834206/94785182-82a69180-03cf-11eb-9d81-a0827847027b.png)

I think it would be enough to simply remove all newlines in the query before processing it further.

**Comment by torkelo** [comment]
Prometheus supports newlines in query. So must be something wrong in your syntax?

**Comment by trallnag** [comment]
Here is a recording. The syntax is correct as you can see:

![gif4](https://user-images.githubusercontent.com/24834206/95314907-24c3ef00-0892-11eb-8a2e-fd091f34b6f0.gif)

I don't know what could be special about my environment. Vanilla Google Chrome and the latest Grafana release. Since you are assuming that it should work I guess this is more of a bug than a feature request?

**Comment by torkelo** [comment]
ah, I see it's these custom query syntaxes grafana has.

**Comment by aocenas** [comment]
Not sure how many datasources use the `label_values` I assume at least Loki also uses this so they should be checked/fixed together with this.

**Comment by skeagy** [comment]
I ran into this problem today. Had a complex multi-line promql query (with embedded newlines) that works fine in a panel, and wrapped it in a query_result() in a query variable, and it failed. I took out the newlines to make an ugly mess, but it worked. Using Grafana 9.4.3
