### ISSUE TITLE
Build: move canary channel/tag from npm to github registry

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#27953]
**What would you like to be added**:
Currently we publish a new package to the canary tag/channel in the npm registry on every commit to master. This is really useful when developing plugins and you want to stay in sync with the latest changes in master. Especially close to shipping a new major/minor release.

To make this possible we have a script that is kind of error prone. The reason is that we need to deprecate/unpublish npm packages in the canary tag/channel before publishing a new package to prevent hitting the npmjs registry limit. At multiple time this logic has failed and as a result the whole build in master will fail.

**Why is this needed**:
Earlier this year @dprokop looked into moving the canary tag/channel from npmjs to the github npm registry but that feature of github was not ready to be used since it was in beta. Now it is released as a stable version and what I can see free for public projects. So the suggestion is to move the canary tag/channel to github npm registry to prevent hitting any upper limit and there for simplify the build pipline in master.

https://github.com/features/packages

**Comment by mckn** [comment]
@dprokop @aknuds1 @torkelo @stevenvachon @ryantxu 

Please ping others that might be interested in this migration.

**Comment by dprokop** [comment]
With publishing to Github Packages repository, we won't need to care about deprecating/unpublishing canary versions, as this was done only to limit the number of packages that are listed on NPM.

**Comment by aknuds1** [comment]
Anything to make this process more robust would be great.

**Comment by stevenvachon** [comment]
I can write this today in JavaScript -- gets it done. Ultimately, it'd probably be best to have it implemented in Go.

**Comment by mckn** [comment]
@stevenvachon did you have a look at this?

**Comment by stevenvachon** [comment]
@mckn no, haven't yet found the time for it.
