### ISSUE TITLE
Prometheus - http: proxy error: context canceled

### ISSUE THREAD

**Issue by dupondje** [grafana/grafana#27957]
**What happened**:

After upgrading grafana from 7.1.5 to 7.2.0, some dashboards don't load completely anymore.
But the strange thing is that it seems to stop sending out ajax calls to the backend (Prometheus) to get its data.

**What you expected to happen**:

Dashboards load fine when downgrading to 7.1.5.

**How to reproduce it (as minimally and precisely as possible)**:

Open some random dashboard with a lot of Prometheus queries.

**Anything else we need to know?**:

The logs show the following:
grafana-server[39288]: t=2020-10-01T13:02:59+0200 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=127.0.0.1 referer="xxx/system-metrics-linux?orgId=1&var-disk_device=All&var-interface=All&from=now-2d&to=now" error="http: proxy error: context canceled"

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Prometheus/Thanos
- OS Grafana is installed on: Debian 10
- User OS & Browser: Firefox Arch Linux
- Grafana plugins: /
- Others:

**Comment by vke** [comment]
The same behavior. Grafana 7.2.0 (no custom plugins), Prometheus 2.21.0, FreeBSD 12.1, Firefox 81

**Comment by aocenas** [comment]
Seems like an issue with grafana backend proxy rather than Prometheus itself. @marefr assigning this to backend team.

**Comment by marefr** [comment]
How long time does your queries take that gets cancelled? Using Chrome Developer Tools inspecting the requests being made from the dashboard, can you see if they're cancelled?

**Comment by marefr** [comment]
Pinging @hugohaggmark as well since it may be related to the changes made in regards to browser request cancellation/maximum queries allowed at the same time.

**Comment by hugohaggmark** [comment]
**Background:** 
In 7.2 we did add a queue for the backend requests so if you haven't configured http2 for your Grafana instance you should see that only 5 concurrent data source requests are being handled at any given time. As part of 7.2 we also made Prometheus data source cancelable changing to an api using Observables, could it be that the requests get the same `requestId` and now those are really canceled?

I've had a similar question about what happens if one of the request in the queue fails and as far as I've tested the rest of the queue will continue to process. Would be great to see screenshots from Chrome Developer Tools network tab for 7.1.5 and 7.2 as @marefr mentioned.

**Comment by czomo** [comment]
Strange, I faced http2 problems even in 7.1.5 version. To bad I didn't have time at all to investigate but now it seems working.

@hugohaggmark From which version of grafana requires http2?
See #27313, I linked my dashboard.

**Comment by hugohaggmark** [comment]
> Strange, I faced http2 problems even in 7.1.5 version. To bad I didn't have time at all to investigate but now it seems working.
> 
> @hugohaggmark From which version of grafana requires configured http2?
> See #27313, I linked my dashboard.

Sorry for confusion @czomo, what I meant to say is if you have http2 configured there is no queuing of requests. The queing in 7.2 only applies to those that have NOT configured http2 which is standard. Hope that clarifies my previous comment.

**Comment by dupondje** [comment]
![image](https://user-images.githubusercontent.com/723195/95317818-f5af7c80-0895-11eb-8ee1-d220167edeea.png)

They get cancelled ...

**Comment by dupondje** [comment]
I've tried enabling http2 on my reverse proxy in front of Grafana, but it still gives me cancelled requests.
Something is really broken :-(

**Comment by hugohaggmark** [comment]
> I've tried enabling http2 on my reverse proxy in front of Grafana, but it still gives me cancelled requests.
> Something is really broken :-(

Then I think we can rule out the queue, thank you. Looking at your screenshot, do I get this correctly that your 5th request is always cancelled or are there more requests?

**Comment by dupondje** [comment]
@hugohaggmark : there are way more requests indeed. It does a bunch of requests (like 20-50) and then it gives 'Cancelled'.

Not sure if its always the case, but seems like it has always issues with graphs that contain +10 queries.

**Comment by hugohaggmark** [comment]
> @hugohaggmark : there are way more requests indeed. It does a bunch of requests (like 20-50) and then it gives 'Cancelled'.
> 
> Not sure if its always the case, but seems like it has always issues with graphs that contain +10 queries.

Ok, thank you I'll try to repro this locally. 

**Questions?**
How long time does the requests that get cancelled take? 
Is it always the same graph panels that are experiencing this issue?

**Comment by dupondje** [comment]
They don't even get started it seems. So its not that they get cancelled due to timeout.

It seems to be (as far as I tested different cases), always triggered by graphs with +10 queries.
There is also no other way to get things refreshed etc by just doing F5. Seems like everything hangs.

I can even simulate it by just opening 1 graph (the one with a lot of queries).
Opening it, it does 23 queries, and then, Canceled ... Nothing shown.

![image](https://user-images.githubusercontent.com/723195/95329235-ed137200-08a6-11eb-9eee-07b47e11b608.png)

**Comment by hugohaggmark** [comment]
I can't repro this locally using A-Z queries in the same graph panel. I have 2 graph panels in the same dashboard with A-Z amount of queries. One querying local prometheus and another panel querying remote test prometheus.

**Comment by dupondje** [comment]
The panel I have is one with 158 queries.
The other that is broken has 159 queries.

Yes quite a lot :) But on 7.1.5 it works smooth.

**Comment by hugohaggmark** [comment]
> The panel I have is one with 158 queries.
> The other that is broken has 159 queries.
> 
> Yes quite a lot :) But on 7.1.5 it works smooth.

Wow, not sure that is optimal! Very curious why this works in 7.1.5 and not 7.2

**Comment by torkelo** [comment]
> The panel I have is one with 158 queries.

:exploding_head: :vomiting_face:  that's a lot of network request, wish Prometheus had request batching :)

I have heard of like 5 or ten queries in a single panel but never anything like this :)

**Comment by torkelo** [comment]
You do know Prometheus supports regex label matching? what could cause you to need so many queries?

**Comment by dupondje** [comment]
@torkelo : Yea its huge, but never seen any issues with it I must say :)

The root cause of this is in fact caused by the collector we use: Telegraf.
For MySQL it creates multiple metrics for each command:
- mysql_com_admin_commands
- mysql_com_alter_table
- mysql_com_xxx
- and so on

So that means each command need its own query.
In an ideal world it would be mysql_com{which="alter_table"}, but its not ...

**Comment by dupondje** [comment]
After some debugging with @hugohaggmark we've found out the root cause :)

The root cause is that the following graph query:      
``` 
    {
      "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
      "format": "time_series",
      "intervalFactor": 1,
      "legendFormat": " Delete Multi"
    },
```   

Gets converted into
```   
            {
          "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
          "format": "time_series",
          "intervalFactor": 1,
          "legendFormat": " Delete Multi",
          "refId": "NA"
        },
``` 

Now with the new backend code the refId is used, and when it notices a duplicate refId, the request gets cancelled.
This causes the canceled requests.

Changing the JSON to have unique refId's make everything work again!

**Comment by xuanyuanaosheng** [comment]
I have found the workaround:
{ "datasource": "Prometheus", "expr": "100 - (avg(irate(node_cpu_seconds_total{instance=\"10.67.250.60:9100\",mode=\"idle\"}[5m])) * 100)", "interval": "", "legendFormat": "10.67.250.60 CPU", "refId": "717" }

As you see, we have 717 query requests, the refId could be any char, so we can use int data to avoid the bug.

Suggest to use int instead of normal letter.

**Comment by jeremybz** [comment]
This is hitting us as well, and as mentioned above editing the refID to an integer in the JSON is a workaround.  Is there a fix in the works for this?

**Comment by marefr** [comment]
There's workarounds and officially we still don't support more than [26 queries per panel ](https://github.com/grafana/grafana/issues/4978) so I'll close this.

**Comment by gilearn** [comment]
> 经过一些调试@hugohaggmark我们已经找到了根本原因:)
> 
> 根本原因是以下图形查询：
> 
> ```
>     {
>       "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
>       "format": "time_series",
>       "intervalFactor": 1,
>       "legendFormat": " Delete Multi"
>     },
> ```
> 
> 转换为
> 
> ```
>             {
>           "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
>           "format": "time_series",
>           "intervalFactor": 1,
>           "legendFormat": " Delete Multi",
>           "refId": "NA"
>         },
> ```
> 
> 现在，使用新的后端代码，将使用 refId，当它注意到重复的 refId 时，请求将被取消。这将导致取消的请求。
> 
> 更改JSON以具有唯一的refId，使一切恢复正常工作！
Dear, please advise, which file do I need to change?


> 经过一些调试@hugohaggmark我们已经找到了根本原因:)
> 
> 根本原因是以下图形查询：
> 
> ```
>     {
>       "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
>       "format": "time_series",
>       "intervalFactor": 1,
>       "legendFormat": " Delete Multi"
>     },
> ```
> 
> 转换为
> 
> ```
>             {
>           "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
>           "format": "time_series",
>           "intervalFactor": 1,
>           "legendFormat": " Delete Multi",
>           "refId": "NA"
>         },
> ```
> 
> 现在，使用新的后端代码，将使用 refId，当它注意到重复的 refId 时，请求将被取消。这将导致取消的请求。
> 
> 更改JSON以具有唯一的refId，使一切恢复正常工作！



> After some debugging with @hugohaggmark we've found out the root cause :)
> 
> The root cause is that the following graph query:
> 
> ```
>     {
>       "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
>       "format": "time_series",
>       "intervalFactor": 1,
>       "legendFormat": " Delete Multi"
>     },
> ```
> 
> Gets converted into
> 
> ```
>             {
>           "expr": "irate(mysql_com_delete_multi{name=~\"$name\"}[5m])",
>           "format": "time_series",
>           "intervalFactor": 1,
>           "legendFormat": " Delete Multi",
>           "refId": "NA"
>         },
> ```
> 
> Now with the new backend code the refId is used, and when it notices a duplicate refId, the request gets cancelled. This causes the canceled requests.
> 
> Changing the JSON to have unique refId's make everything work again!

Dear, please advise, which file do I need to change?

**Comment by gilearn** [comment]
Dear, can you tell me, which file do I need to change?  thank you
