### ISSUE TITLE
CloudWatch Logs: Implement query queueing

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#27969]
Amazon CloudWatch Logs imposes certain limits, or quotas, on the usage of various API endpoints and features. One of these limits is the limit on query concurrency, which has a default of 4, but can be increased to 10 on request. If a user attempts to start a query while the maximum number of concurrent queries are running, an error will be returned. In order to prevent CloudWatch Logs panels, or CloudWatch Logs queries sent in Explore, from returning errors in the case where the concurrent queries limit is reached, it is necessary to implement a queueing system that only dispatches a “Start Query” request when we are under the concurrent query limit.

**Comment by aknuds1** [comment]
Moving this to the next 7.3.0 milestone, since we need to review the PR more.

**Comment by aknuds1** [comment]
Closing, as we agreed earlier and considering it's implemented by #28176.
