### ISSUE TITLE
Stat panel - No Data after upgrade to v7.2

### ISSUE THREAD

**Issue by asm19** [grafana/grafana#27971]
I don't know if this is a bug but I can't solve it. After updating to grafana 7.2 I no longer have data in some fields of stat panels. This only happens if the query mode is "Text". I already changed the format of the unit and I can't solve it.

**Environment**:
- Grafana version: 7.2
- Grafana plugins: alexanderzobnin-zabbix v4.0.0
Zabbix Version: 5.0.4

![1](https://user-images.githubusercontent.com/1648981/94822560-b5b24a80-03fa-11eb-968b-e59be42e5fce.png)

![2](https://user-images.githubusercontent.com/1648981/94822571-b814a480-03fa-11eb-9107-1f4055c3fd92.png)

**Panel json**:
{
  "datasource": "Zabbix",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "unit": "none",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "rgb(166, 164, 166)",
            "value": null
          }
        ]
      },
      "mappings": [
        {
          "$$hashKey": "object:3896",
          "from": "3",
          "id": 0,
          "text": "Active-Passive",
          "to": "3",
          "type": 2
        }
      ],
      "nullValueMode": "connected"
    },
    "overrides": []
  },
  "gridPos": {
    "h": 3,
    "w": 6,
    "x": 0,
    "y": 10
  },
  "id": 23763571993,
  "links": [],
  "maxDataPoints": 100,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "textMode": "auto",
    "colorMode": "background",
    "graphMode": "none",
    "justifyMode": "center",
    "fieldOptions": {
      "calcs": [
        "lastNotNull"
      ]
    }
  },
  "pluginVersion": "7.2.0",
  "targets": [
    {
      "application": {
        "filter": "HA Availability"
      },
      "functions": [],
      "group": {
        "filter": "Fortigate"
      },
      "host": {
        "filter": "XXXX-XXXX-XXXX"
      },
      "item": {
        "filter": "Ha System Mode"
      },
      "mode": 2,
      "options": {
        "showDisabledItems": false,
        "skipEmptyValues": false
      },
      "proxy": {
        "filter": ""
      },
      "queryType": 2,
      "refId": "A",
      "resultFormat": "time_series",
      "table": {
        "skipEmptyValues": false
      },
      "tags": {
        "filter": ""
      },
      "trigger": {
        "filter": ""
      },
      "triggers": {
        "acknowledged": 2,
        "count": true,
        "minSeverity": 3
      }
    }
  ],
  "title": "HA System Mode",
  "transparent": true,
  "type": "stat",
  "transformations": [],
  "cacheTimeout": null,
  "interval": null
}

**Comment by torkelo** [comment]
can you use query inspector and check the raw response, and in the inspect drawer data tab you can inspect the raw data as well

**Comment by asm19** [comment]
**### Grafana v7.1.5**:

{
  "request": {
    "method": "POST",
    "url": "https://zabbix-XXXXXXXXX.com/zabbix/api_jsonrpc.php",
    "data": {
      "jsonrpc": "2.0",
      "method": "history.get",
      "params": {
        "output": "extend",
        "history": "1",
        "itemids": [
          "31330"
        ],
        "sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1601962784,
        "time_till": 1601969984
      },
      "id": 1,
      "auth": "68f98d59107e97635f2cffb8f31ae4a6"
    }
							  
  },
  "response": {
    "jsonrpc": "2.0",
    "result": [
      {
        "itemid": "31330",
        "clock": "1601964006",
        "value": "3",
        "ns": "9834494"
      },
      {
        "itemid": "31330",
        "clock": "1601967605",
        "value": "3",
        "ns": "937419114"
      }
    ],
    "id": 1
  }
}

![1](https://user-images.githubusercontent.com/1648981/95172870-d6d6ba80-07af-11eb-9d82-e635598524c1.png)

**### Grafana v7.2**:

{
  "request": {
    "method": "POST",
    "url": "https://zabbix-XXXXXXXXX.com/zabbix/api_jsonrpc.php"",
    "data": {
      "jsonrpc": "2.0",
      "method": "history.get",
      "params": {
        "output": "extend",
        "history": "1",
        "itemids": [
          "31330"
        ],
        "sortfield": "clock",
        "sortorder": "ASC",
        "time_from": 1601962671,
        "time_till": 1601969871
      },
      "id": 1,
      "auth": "4062d1c3b60a076957842a84ee5ce00d"
    },
    "hideFromInspector": false
  },
  "response": {
    "jsonrpc": "2.0",
    "result": [
      {
        "itemid": "31330",
        "clock": "1601964006",
        "value": "3",
        "ns": "9834494"
      },
      {
        "itemid": "31330",
        "clock": "1601967605",
        "value": "3",
        "ns": "937419114"
      }
    ],
    "id": 1
  }
}

![2](https://user-images.githubusercontent.com/1648981/95172932-e8b85d80-07af-11eb-82a2-54bc543ac965.png)

I just find a difference in v7.2, line:

"hideFromInspector": false

**Comment by har1ey** [comment]
Similar problem..

Grafana version: 7.2
Grafana plugins: alexanderzobnin-zabbix v4.0.1
Zabbix API version: 4.0.6

**Comment by joaoedsonjunior** [comment]
Similar problem

**Comment by alexanderzobnin** [comment]
Confirmed. Text data is not working with Stat and Table panels. It looks like panels expect to get only numeric data, even if Last value selected.

**Comment by myriad007** [comment]
I'm confused. So how come it was working perfectly prior to Grafana's last update?

**Comment by juannvalencia** [comment]
Thank you Alexander for your great work!

**Comment by hugohaggmark** [comment]
I can confirm this, but if I change the Fields settings from __Numeric Fields__ to __All Fields__ or a specific field it works as expected:
![image](https://user-images.githubusercontent.com/562238/97403451-be604880-18f4-11eb-95a2-424eb708ec41.png)

Not sure if this is an intended change, do you know more about this @torkelo

**Comment by marefr** [comment]
@torkelo any input?

**Comment by torkelo** [comment]
this is expected the stat panel will only show numeric fields by default

**Comment by Positronico** [comment]
Not sure if I understood this correctly, @torkelo. Reading @hugohaggmark message and yours it appears to be possible to make stat panel show non-numeric values, but changing Field options doesn't help.

Can you confirm this is not a "default option" for stat panels but a drop of functionality?

**Comment by cawhite6** [comment]
@torkelo @alexanderzobnin  - That's great this is expected behavior, any chance there is a workaround to display the Text/String values that were working and has now been dropped (Table or Stat Panel)? Pretty big issue for our distro of zabbix/grafana to our client(s) access.

**Comment by torkelo** [comment]
Changing field option to select the field you want does not help? 

Strange, it works when I test

**Comment by torkelo** [comment]
Text data works fine in table and stat panel in my tests

**Comment by cawhite6** [comment]
> Text data works fine in table and stat panel in my tests

So this is specific to Zabbix plugin then....I'll open that with alexander
