### ISSUE TITLE
legend names in snapshots get messed up

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#27973]
Grafana v7.2.0 (efe4941ee3) (datasource: metrictank)
dashboard looks like this....
![dash](https://user-images.githubusercontent.com/20774/94826769-53644480-0410-11eb-9220-278d59b0faf4.png)
snapshot looks like this....
![snap](https://user-images.githubusercontent.com/20774/94826719-45162880-0410-11eb-85fb-e397b090b168.png)

**Comment by torkelo** [comment]
Unable to replicate this

**Comment by torkelo** [comment]
The only thing I can think that can cause this is an old snapshot

**Comment by Dieterbe** [comment]
https://snapshot.raintank.io/ it's probably due to this not having been updated
