### ISSUE TITLE
Interval templating is not applied on metric in the 'group by time($interval)' section

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#2797]
I'm using the yesterday's build of grafana (2.5) with a InfluxDB 0.9.4.1

I have an interval template defined with the default and I was expecting that this value would be applied on the fly on each metric in the group by time($interval)' part.

I have tried to add quote or '/' but nothing works.

Is is a bug or a missing feature ? Am I wrong ?

**Comment by torkelo** [comment]
can you describe what you mean by "Interval templating is not applied" , is $interval not replaced with the current interval (which Grafana calculates automatically based on time range)

**Comment by sbouchex** [comment]
I have declared a "interval" variable in my Dashboard and I was expecting to see this interval used in the current interval applied to my metric. The query does contain time($interval) by default, so I expect that $interval is replaced by the value declared in the popup.

No ?

**Comment by torkelo** [comment]
interval is a built in automatic variable in grafana , and is automatically set based on time range. You can try entering your interval variable in the group by time field below your queries  (in the metric tab)

**Comment by shawnahall71** [comment]
I came to exactly the same conclusion that @sbouchex did after reading the Grafana [templating reference](http://docs.grafana.org/reference/templating/#interval).  If it would be helpful I can take a shot at a pull request for that page.

**Comment by andyxning** [comment]
@torkelo @shawnahall71 The doc should be updated to point that:
> interval is a built in automatic variable in grafana , and is automatically set based on time range. You can try entering your interval variable in the group by time field below your queries (in the metric tab)

This make my life bright again after searching for more than 2 hours. :(

**Comment by offero** [comment]
Can we add a selector on a dashboard to manually change the interval? I have no choice but to adjust the interval when I query larger time ranges because grafana cuts off the data coming back (probably too much).

**Comment by torkelo** [comment]
cut's of data? what?

**Comment by offero** [comment]
Where the time range is too large and I have a group by query, the graph does not show all of the groups and data point for them. But if I increase the size of the group by time interval, then all of the categories for the query show up with all of the data points. I usually have to manually figure out how large to increase the time interval.

I use influxdb with grafana.

**Comment by offero** [comment]
I do have InfluxDB 1.2.0

My config says:

>   max-row-limit = 10000

**Comment by torkelo** [comment]
ok, please upgrade, they fixed that in later versions (the default should be 0/unlimited)

**Comment by offero** [comment]
Will do. Thanks!
