### ISSUE TITLE
Elasticsearch annotations don't work with field names that contain periods

### ISSUE THREAD

**Issue by seanhoughton** [grafana/grafana#27989]
summary by @gabor: in elasticsearch annotations, when entered field-names contain periods (`.`), we assume it's a nested structure, and recursively try to find the real field. so if it is a not-nested field that has a `.` in it's name, it does not work. even if we change this, we need to be careful with backward-compatibility. (the related code: https://github.com/grafana/grafana/blob/66b54e2dbd10fd399e2034b3367bbb579b8a0635/public/app/plugins/datasource/elasticsearch/datasource.ts#L330-L341 )

---
**What happened**:

I'm using an elasticsearch datasource for annotations and would like to use my fields for the "start" and "end" time. The field names are `p4.start_time` and `p4.end_time`.

Note - periods are allowed, but are probably not a great idea. However, because many datasources may already contain fields with period names it would be really useful to support either automatically handling it or escaping the periods somehow with quotes or other escape character.

Note: the "beat" tools that the elastic group created makes fairly heavy use of field names containing periods.

**What you expected to happen**:

The field values work in the annotation

**How to reproduce it (as minimally and precisely as possible)**:

Create an elasticsearch document with text and/or date fields that contain periods (but are not "object" type). Attempt to use this document as an annotation's start, end, or data field value.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 
v7.1.1 (3039f9c3bd)

- Data source type & version:
Elasticsearch annotation (built in)

- OS Grafana is installed on:
Ubuntu / Kubernetes

- User OS & Browser:
Chrome

- Grafana plugins:
none

**Comment by trobers** [comment]
I suspect it has something to do with the following issue: https://github.com/grafana/grafana/issues/5043

We have the same problem with annotation tags and nested fields. In our case the annotation appears but the tags are not filled.

**Comment by seanhoughton** [comment]
The problem seems to be on this line (https://github.com/grafana/grafana/blob/185442115caf82b797816c47a9c1396426139f95/public/app/plugins/datasource/elasticsearch/datasource.ts#L249)
```
        const fieldNames = fieldName.split('.');
```

If the code used a split function that respected quoting then users could be more explicit about where real object fields need to be resolved and where the field name just contains a period character.

**Comment by gabor** [comment]
hi, the elasticsearch naming convention doc at https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html says:
"
Do not use dots (.) in individual field names. Dots are reserved for grouping related fields into subdocuments.
"

based on this it seems the current behavior of the elasticsearch-datasource is aligned with elastic best practices. and, changing the current behavior would break backward-compatibility. considering these two reasons, we are not planning to support this scenario currently.

(if you think we are interpreting something incorrectly, feel free to respond and we can discuss it. thanks!)

**Comment by gabor** [comment]
hi, the elasticsearch naming convention doc at https://www.elastic.co/guide/en/beats/devguide/current/event-conventions.html says:
"
Do not use dots (.) in individual field names. Dots are reserved for grouping related fields into subdocuments.
"

based on this it seems the current behavior of the elasticsearch-datasource is aligned with elastic best practices. and, changing the current behavior would break backward-compatibility. considering these two reasons, we are not planning to support this scenario currently.

(if you think we are interpreting something incorrectly, feel free to respond and we can discuss it. thanks!)
