### ISSUE TITLE
Graph panel does not render if a series has the alias "constructor"

### ISSUE THREAD

**Issue by mr-ns** [grafana/grafana#27982]
**What happened**:
I have a dataset of multiple time series that I am attempting to plot in a graph panel. If one of the time series is named "constructor" the graph panel shows nothing. This appears to be the same root cause as issue #14961.

**What you expected to happen**:
I expect the graph panel to render data even if a time series is named "constructor".

**How to reproduce it (as minimally and precisely as possible)**:
Create a time series where the metric name (i.e., alias) is "constructor" and attempt to plot that in the graph panel.

**Anything else we need to know?**:
There are a number of places in the JavaScript where `alias` is used as an index into various (associative) arrays. Any time this happens if the alias is "constructor" you get Object.constructor instead of the array value. See, for example:
- https://github.com/grafana/grafana/blob/v7.1.3/public/app/plugins/panel/graph/data_processor.ts#L82
- https://github.com/grafana/grafana/blob/v7.1.3/public/app/plugins/panel/graph/module.ts#L321
- https://github.com/grafana/grafana/blob/v7.1.3/public/app/plugins/panel/graph/module.ts#L314

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: PostgrSQL (whatever version comes with Grafana 7.1.3)
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Linux (Fedora 30), Firefox version 76
- Grafana plugins:
```
bash$ sudo -u grafana grafana-cli plugins ls
installed plugins:
alexanderzobnin-zabbix-app @ 3.12.4
briangann-datatable-panel @ 1.0.2
briangann-gauge-panel @ 0.0.6
flant-statusmap-panel @ 0.2.0
grafana-groupedbarchart-panel @ 1.0.0
grafana-piechart-panel @ 1.6.0
ilgizar-candlestick-panel @ 0.0.1
kentik-app @ 1.4.0
mxswat-separator-panel @ 1.0.0
natel-plotly-panel @ 0.0.6
petrslavotinek-carpetplot-panel @ 0.1.1
sumo-logic-metrics-datasource @ 0.1.0
vonage-status-panel @ 1.0.9
```

**Comment by mr-ns** [comment]
As far as I know this issue still exists, although to be fair I have not tested it with more recent Grafana releases.

**Comment by leeoniya** [comment]
the Graph (old) panel has been deprecated for 2 years and will be removed in G11. please open a new issue with repro steps / screen rec if this bug exists in the TimeSeries panel.
