### ISSUE TITLE
[data sources] Without entering any values data source getting saved  

### ISSUE THREAD

**Issue by VishalLahane** [grafana/grafana#27991]
**What happened**:
- Go to configuration then data sources 
- Click on data source (any) don't fill any value or Save & Test 
- Message popups up "Datasource added"
-  the data sources list getting filled with this empty data sources.

**What you expected to happen**:
- There should be some restriction or setting that user not allow to save data source unless fill all required values & click on Save

**How to reproduce it (as minimally and precisely as possible)**:
- Go to configuration then data sources 
- Click on data source (any) don't fill any value or Save & Test 
- Message popups up "Datasource added"
-  the data sources list getting filled with this empty data sources.

**Anything else we need to know?**:
-  We should have some restriction setting or block user not entering required details  

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Comes with grafana built-in
- OS Grafana is installed on: Windows/CentOS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

Screenshots:

![image](https://user-images.githubusercontent.com/16710051/94889185-ed6fcf80-0498-11eb-8ff5-fb040ed58c77.png)

**Comment by torkelo** [comment]
Thanks for the feedback. When you add a data source in the first step it already adds the data source. We need it added in order to test connection details.

But we can improve this
