### ISSUE TITLE
Multiselect not working

### ISSUE THREAD

**Issue by tegge** [grafana/grafana#2801]
If got a template variable for example:
servers.$server.metric.value

and select 2 Servers it gets me 0 Datapoints. If i only select one server it works. 
Selecting two servers via s64{3,4} works too.

Am i doing wrong, or is it a bug?

Grafana version: 2.5.0-pre1, commit: v2.1.2+420-gf632b3b, build date: 2015-09-22 14:29:41

**Comment by torkelo** [comment]
whats your datasource, query, template variable settings etc????

**Comment by tegge** [comment]
Well, looks like its not clearly intentional. I used Multi format "regex value" and just clicked on the Checkboxes for the Values i need.
This didnt work, but when i'd changed Multi format to "glob"  it worked like expected.

How to use the regex-feature?

**Comment by torkelo** [comment]
it depends on you data source, if you use graphite you should use glob as it graphite does not support regex. InfluxDB does not support globs but regex :)

**Comment by tegge** [comment]
Feature-Request:
exclude globbing option if influxdb is the datasource
exclude regex option if Graphite is the datasource
:)

**Comment by torkelo** [comment]
this was implemented today (well not exclude, but the right option is selected when you switch data source)

**Comment by tegge** [comment]
I see  f632b3b

But thats not in the latest deb-package?

**Comment by torkelo** [comment]
yes it is

**Comment by tegge** [comment]
5:28:04 PM... :D New Build.. got the build from 3:20 PM

**Comment by torkelo** [comment]
it should have been in the older build as well
