### ISSUE TITLE
Multiple hover tooltip issue

### ISSUE THREAD

**Issue by octapudus** [grafana/grafana#28018]
Hello,
I tried with Mysql and Influx DB.

With mysql its working well and tooltip show the values of the points on hover the chart zone.
in the case of InfluDB this does not happen.

In the case of InfluxDB (all datas are stored as string)  you see the list of variables in format: "name_table.column:" and then nothing, no any value.
in order to see the value i need to select "Hover tooltip Mode -> single", but i need to have it multiple

So the issue is in the multiple hover tooltip.

please confirm that you see the same issue

Thanks,

**Comment by torkelo** [comment]
You need to include your grafana version, data source version, query, and the raw query results from your query, your panel config (panel json)

**Comment by torkelo** [comment]
And for the Graph the values needs to be numbers not strings
