### ISSUE TITLE
Relative URL in links instead of absolute

### ISSUE THREAD

**Issue by linkdd** [grafana/grafana#28023]
**What would you like to be added**:

Links should be relative like assets (the ``<base/>`` element is already present in the rendered page).

**Why is this needed**:

I have a Grafana dashboard that should be exposed through different reverse proxies (each one with its own base URL).
The reverse proxies are patching the response from Grafana to fix the `href` attribute on the `<base/>` element.
But since links are absolute (starting with a `/`), they are not impacted by the patch.

I guess that would mean not using `setting.AppSubUrl` and removing the first `/` when constructing URLs like in this code: https://github.com/grafana/grafana/blob/master/pkg/api/index.go#L145

But I'm not sure about the impact of that change.

**Comment by torkelo** [comment]
Sorry Grafana can not be fully run like this (redirects and other backend generated urls need to use AppSubUrl. And there are situations there base.url is not respected by browsers when Grafana needs absolute url

**Comment by torkelo** [comment]
But you could open a feature request to support multiple domain names (one per org) or something like that

**Comment by linkdd** [comment]
Could the AppSubUrl be overwritten via a custom HTTP Header then ? So the Reverse Proxy could just set that header.
