### ISSUE TITLE
Frontend improve build performance

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#28035]
Webpack performance is not great, would be interesting exploring snowpack or a build system using esbuild (snowpack uses it under the hood)

**Comment by leeoniya** [comment]
another option is https://github.com/swc-project/swc

**Comment by torkelo** [comment]
Looks like esbuild has some advantages, like is as fast as swc and has minification https://twitter.com/youyuxi/status/1257660498906165255?s=21
