### ISSUE TITLE
Docs feedback: /variables/variable-examples.md

### ISSUE THREAD

**Issue by danfoxley** [grafana/grafana#28036]
Links are broken.

**Comment by oddlittlebird** [comment]
Which links? I just tested them all, and they seem to be working fine.

**Comment by achatterjee-grafana** [comment]
@aknuds1, can you specify which link is broken? All of them worked for me. TY.

**Comment by danfoxley** [comment]
Well, they all work for me now too. Sorry for the false alarm. (I'd have to think it was not working at the time, the links loaded but reported an error).
