### ISSUE TITLE
Error due to typescript files in the latest build

### ISSUE THREAD

**Issue by Srungaram** [grafana/grafana#2804]
I am getting the below error displayed in grafana browser console

 GET http://localhost:4000/public/app/core/core.js?bust=1442941278960 
require.js:165 Uncaught Error: Script error for: app/core/core
http://requirejs.org/docs/errors.html#scripterror

This may be because it is expecting core.js file but source folder has core.ts 
Please help.

**Comment by torkelo** [comment]
did you run grunt?

**Comment by Srungaram** [comment]
Yes, just found out your comment from the old issues that says to remove public/css folder. I did and it worked. Thanks!
