### ISSUE TITLE
table panel column disappears for prometheus query in outer join

### ISSUE THREAD

**Issue by alanmiller** [grafana/grafana#28041]
**What happened:**
I created a table panel with the following 2 prometheus queries that are "outer joined" on a volume field.

**query 1**:
`label_replace(windows_logical_disk_size_bytes{instance =~ "$server", volume !~ "HarddiskVolume.+", volume !~ "T:"},"IPAddress","$1","instance","(.*):9182")`
**query 2**: 
`( (100 - (100 * (windows_logical_disk_free_bytes{instance =~ "$server",volume !~ "HarddiskVolume.+", volume !~ "T:"}/windows_logical_disk_size_bytes))) > $threshhold )`

**What you expect to happen:**
Regardless of whether the 2nd query returns any results, I would expect to see the "% Used" column in the panel.
Instead this behaviour is seen:

The queries/join appears to work as the table is populated ($threshold is set to 0)
![table1](https://user-images.githubusercontent.com/1309167/95132624-1492ff00-072e-11eb-9afb-f0f93dbe7e9c.png)

When $threshold is set to 20 (query returns a result) the table displays the '% used' column with empty cells as expected.
![table2](https://user-images.githubusercontent.com/1309167/95132674-283e6580-072e-11eb-9657-fd227c88e881.png)

When $threshold is set to a value  that doesnt return any results (ie: 30) the '% used' column disappears.
![table3](https://user-images.githubusercontent.com/1309167/95132716-37bdae80-072e-11eb-98f8-abd09718a07a.png)

**Anything else we need to know?**
I am using the label_replace() in the first query as a workaround for issue #24744 Without it, I get duplicate columns for the instance field.
 
**How to reproduce:**
As described above. Create a table panel populated by 2 prometheus queries that are outer joined. If the 2nd query doesnt return any results the number of columns displayed in the table changes.

**Environment:**
Grafana version 7.0.0
Data source type & version: Prometheus 2.14.0
OS Grafana is installed on: CentOS release 6.7
User OS & Browser: MacOSX, Chrome 85.0.4183.83
Grafana plugins: Table
Others:

**Comment by aknuds1** [comment]
Can you please rewrite the issue description following the standard bug template?

**Comment by alanmiller** [comment]
@aknuds1 Does that correspond to the standard template?

**Comment by aknuds1** [comment]
This looks much better, thanks.

**Comment by torkelo** [comment]
This is not a Grafana bug/issue, As Prometheus returns nothing when there is no label match, just an empty result so nothing for Grafana to join to.
