### ISSUE TITLE
Can not load Notification Channel edit view

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#28051]
**What happened**:
Can not load Notification channel edit view from Notification channels list view

**What you expected to happen**:
Notification channel edit view will be opened when I click on the channel row

**How to reproduce it (as minimally and precisely as possible)**:
1) Add new notificartion channel - email/slack
2) Go to channels list view if you are not there
3) Click on the added notification channel
4) if step 3 loaded the edit view then go back to list view 
5) Click  on the added notification channel again

Those steps give me 100% fail rate  for 10 times.

After some time  I can open the channel again and repeat the failure

**Anything else we need to know?**:
We are provisioning notification channels trough API not via provisioning module of Grafana ( for now ).
Problem appeared after upgrade to 7.2 from 7.1.5
https://devclass.com/2020/09/29/grafana-7_2/ warned about issues  we have  now

![image](https://user-images.githubusercontent.com/4919667/95189271-511a3580-07d6-11eb-9e1c-7e687ef7c185.png)

**Environment**:
- Grafana version: v7.2.0 (efe4941ee3)
- Data source type & version: Influxdb 1.8.3
- OS Grafana is installed on: RH 7.8
- User OS & Browser: Chrome 85.0.4183.121
- Grafana plugins: image-rendering-plugin
- Others:

**Comment by aknuds1** [comment]
In "How to reproduce":

1. Please specify what you mean by "grafana upgrade". Do you have to upgrade from 7.1.5 to 7.2 for the problem to happen?
2. Please specify with enough details how to reproduce the issue, so we can see the bug for ourselves.

**Comment by gjemp** [comment]
updated

**Comment by aknuds1** [comment]
I can reproduce this when I use the official 7.2.0 release. Doesn't happen to me when I try from source though, which is strange. Thanks, will relay it on.

**Comment by aknuds1** [comment]
Actually doesn't happen consistently for me, only once so far, even though I've tried many times.

**Comment by gjemp** [comment]
I use Win 10 64bit Prof.

**Comment by dprokop** [comment]
@peterholmberg are you investigating this one?

**Comment by vilinski** [comment]
page reload helps :confused:
