### ISSUE TITLE
Elasticsearch: Raw data query doesn't render ad-hoc filter selection in table panel

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#28054]
**What happened**:
When doing a raw data query using Elasticsearch and visualize in table panel doesn't render ad-hoc filter selections in cells.In this example I'm hovering the _index column/first row:
![image](https://user-images.githubusercontent.com/1668778/95201037-a6a71000-07df-11eb-8c88-91bf9c9ae142.png)

**What you expected to happen**:
Ad-hoc filter selection to be shown on hover of cell like in this example using the old table panel and raw document (legacy) query:
![image](https://user-images.githubusercontent.com/1668778/95201116-be7e9400-07df-11eb-92f1-6f7ac8a8759a.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Using gdev dashboards and devenv elastic7 docker block
1. Navigate to `Datasource tests - Elasticsearch v7` dashboard
1. Edit the ES log query to use raw data query and the new table panel

**Anything else we need to know?**:
Looking into this seems like data frame response doesn't include the `filterable` config of fields.

**Environment**:
- Grafana version: 7.2 / master (0a2ef086b3)
- Data source type & version: Elasticsearch

**Comment by torkelo** [comment]
Looks like there is no filterable: true set on any field config  https://github.com/grafana/grafana/blob/0a2ef086b3a92e6362427c4479157aae5b4d7f01/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L573
