### ISSUE TITLE
Client Script based variable calculation

### ISSUE THREAD

**Issue by dylan-asos** [grafana/grafana#28052]
**What would you like to be added**:

The ability to calculate a variable from client script. 

Variable Type : 'Script'
Input : Panel to craft some javascript

![image](https://user-images.githubusercontent.com/16137664/95190242-e9102300-07c6-11eb-9182-5200ccd73111.png)

**Why is this needed**:

Currently, we have variables set to 'query' that will execute against a data source in order to returns values. This is often lookup data or some other calculation based on another variable choice. 

E.g. in this example, a KQL to calculate a name, based on whether the $Environment variable is either prod or nonprod.

```
let InsightsNaming = datatable( Environment: string, InsightsName: string)
["nonprod","non-prod-resource", 
"prod", "prod-resource" ]; 
InsightsNaming
| where Environment == "$Environment" 
| distinct  InsightsName;

```

In a number of these cases, we shouldn't need to execute a query against a data source in order to calculate the result, a script option would let us calculate the variables, which would 

* speed up dashboard load times
* reduce the amount of query load on data sources and
* reduce number of queries being proxied by the Grafana datasources api

**Comment by torkelo** [comment]
The challenge here would be what scripting language and how to make this secure (allowing arbitrary javascript as part of dashboard definition is not secure)

**Comment by dylan-asos** [comment]
@torkelo yep for sure.  A large number of scenarios I'm seeing are these table / simple lookup's based on another variable . 

So requirements could be reworded as - the ability to represent a data structure client side which has rows/is a collection, which I can select from and set another variable - rather than 'define and run any script'

Variable Type : 'Collection'
Input a -> Panel to create field names / add row values / give collection a name
Input b -> Panel to define a predicate? FieldName == @VariableName

**Comment by yesoreyeram** [comment]
@dylan-asos  - I have a workaround for this use case with the [infinity data source plugin](https://yesoreyeram.github.io/grafana-infinity-datasource/wiki/template-variables.html#variables).   Just a simple key value pair lookup for two column table. Let us know if this helps or if you have any feedback. 

Example: 

`CollectionLookup(pd,prod-server,np,nonprod-server,dev,dev-server,$Nested)` . Last value should be the key to lookup. 

![image](https://user-images.githubusercontent.com/153843/95761926-ec168200-0ca4-11eb-8758-ff5885564180.png)
![image](https://user-images.githubusercontent.com/153843/95768582-79aa9f80-0cae-11eb-97c1-4b4537c9d330.png)

**Comment by dylan-asos** [comment]
OK great @yesoreyeram I'll give this a go - looks like it'll do what I'm trying to achieve + doesn't require any core changes to Grafana.

**Comment by dylan-asos** [comment]
Happy to close this - the infinity data source approach does what I want and comes with a well defined API for working with it, minimising any security issues as mentioned by @torkelo. 

The approach can be extended - more functions can be added for building up variables, allowing us to minimise our dependency on something like the Azure Monitor API for this purpose.
