### ISSUE TITLE
Notification channel Back route does not have the subpath

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#28056]
**What happened**:
back button in notification channel edit view does not count in the root_url path where the proxy subPath is defined to make the routing correctly
 serve_from_sub_path = True

**What you expected to happen**:
I will be routed back to list view from where i got there.

**How to reproduce it (as minimally and precisely as possible)**:
Preconditions:
in grafana.ini define root_url with subpath  and set serve_from_sub_path = True

1) Open Notification channels list view
2) Click on any channel , wait until the view is loaded
3) Click on Back button 

**Anything else we need to know?**:

**Environment**:
Grafana version: v7.2.0 (efe4941)
Data source type & version: Influxdb 1.8.3
OS Grafana is installed on: RH 7.8
User OS & Browser: Chrome 85.0.4183.121
Grafana plugins: image-rendering-plugin
Others: yum installed grafana

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/public/app/features/alerting/EditNotificationChannelPage.tsx

**Comment by peterholmberg** [comment]
The issue is in this component https://github.com/grafana/grafana/blob/master/public/app/features/alerting/components/NotificationChannelForm.tsx

**Comment by randall-fulton** [comment]
I can take a stab at this.

**Comment by veera83372** [comment]
Can I  pick this one?

**Comment by aknuds1** [comment]
@veera83372 Sure.

**Comment by gjemp** [comment]
hei, installed the 7.3.1 today, and the case still exists

**Comment by aknuds1** [comment]
@gjemp thanks for letting us know, I reopened the issue so the frontend team can have another look.

**Comment by jackw** [comment]
I've double checked this on master and I cannot reproduce it. Looking at the fix I believe it will arrive in the next release. Once that's happened I'd suggest updating to 7.3.2 @gjemp and trying again.
