### ISSUE TITLE
Setting any field display name for a bar gauge makes panel render “No data”

### ISSUE THREAD

**Issue by devopsix** [grafana/grafana#28060]
**What happened**:

Using a template variable (`$__cell_0`) for the display name of a PostgreSQL table query based bar gauge field makes the panel show “No data”.

**What you expected to happen**:

Using a template variable (`$__cell_0`) for the display name should cause the bars being labelled as the value in the query result's first column.

**How to reproduce it (as minimally and precisely as possible)**:

Given a table “data” in a (PostgreSQL) database:

| name | value |
|---|---|
|`'foo'`|1|
|`'foo'`|2|
|`'foo'`|3|
|`'bar'`|1|
|`'bar'`|2|
|`'baz'`|1|

Create a Bar Gauge Panel (“All Values”, field “value”) based on this query:

```
SELECT name, count(value) AS value FROM data GROUP BY name ORDER BY value DESC
```

Enter anything into the “Display Name” field.

![image](https://user-images.githubusercontent.com/58369032/95219684-f98bc200-07f5-11eb-8c04-13a458a240eb.png)

![image](https://user-images.githubusercontent.com/58369032/95219734-05778400-07f6-11eb-897f-5c02e76de9ee.png)

**Anything else we need to know?**:

The panel renders three bars and all bars are labelled “count” as long as the “Display Name” field is empty. As soon as anything is entered into the “Display Name” field, the panel shows “No data”.

See [attached ZIP file](https://github.com/grafana/grafana/files/5334761/bar-gauge-labels.zip) for a full working example.

Did work as expected in 7.0.0 through 7.0.2. Haven't tried older versions.

Issue also exists in `grafana:master` image as of 2020-10-06T16:40:00 (`sha256:3afe6ac03caad7e3800a0ce10377203accbec8bed9b907100d6669e8f1f9d531`).

**Environment**:
- Grafana version: 7.2.0 (affects 7.0.3 and above)
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: Whatever the `grafana:7.2.0` docker image uses
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: None.

**Comment by mckn** [comment]
@devopsix does it work if you change the `${__cell_0}`?

**Comment by devopsix** [comment]
@dprokop Unfortunately, no. The issue also seems to exist with `${__cell_0}`.

**Comment by dprokop** [comment]
@devopsix just tested against master and v7.2.0, and also agains your provided zip (btw, thanks for this, it's super helpful!).

Indeed it seems there is something wrong, investigating

**Comment by dprokop** [comment]
Identified the problem, but can't see a way to solve it yet.

When picking a Field to be displayed:
![image](https://user-images.githubusercontent.com/2376619/95578326-01d14080-0a34-11eb-8131-81263e47f58d.png)
the field to be rendered is picked by [regex name matcher](https://github.com/grafana/grafana/blob/13915758532438a64812808276171d8c6d5567a0/packages/grafana-data/src/transformations/matchers/nameMatcher.ts#L59). But this matcher is performed against field display name which may be configured to something else (like _$__cell_0_ in the provided example) resulting in No data message as we are matching /^value$/ regex against $__cell_0 display name.

**Comment by torkelo** [comment]
yea, for this I think you need to show all numeric fields, not pick field by name

**Comment by devopsix** [comment]
@dprokop and @torkelo thank you for quick response on this! Selecting fields by numeric type instead of a anme regex perfectly solves this issue for me.

It might be helpful to users if disfunctional options would be removed from the “Fields” dropdown when the display name is being overridden (“name” and “value” both lead to “No data” in the example). But that rather seems to be a feature request.

**Comment by neerajjain92** [comment]
Still facing the issue, why is this closed ?

**Comment by yankee42** [comment]
I have a query where my key is an integer. Something like this:
```sql
select num "key", num*5 "value" from generate_series(1, 10)n(num)
```
Selecting "numeric fields" naturally did not work as Grafana then also tries to display my key as values.

I needed to read the issue multiple times until I understood that I could fix this the following way:
```sql
select key::text "key", value from (
    select num "key", num*5 "value" from generate_series(1, 10)n(num)
)x
```
I hope this helps anyone finding this ticket :-).
