### ISSUE TITLE
Elasticsearch: Error when adding ad-hoc filters in explore with table panel

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#28076]
**What happened**:
This is a follow up to https://github.com/grafana/grafana/pull/28064#pullrequestreview-503419967, Ad-hoc filters don't work in explore with the Table Panel.

When adding an ad-hocc filter:
<img width="647" alt="image" src="https://user-images.githubusercontent.com/1170767/95314602-6bf9b200-0889-11eb-88a5-c703063445b9.png">
this error happens:
<img width="606" alt="image" src="https://user-images.githubusercontent.com/1170767/95314679-803daf00-0889-11eb-846a-fb8d7696eea0.png">

**What you expected to happen**:
Ad-hoc filters should work correctly

**How to reproduce it (as minimally and precisely as possible)**:

1.  Using devenv elastic7 docker block
2. Navigate to Explore
3. Edit the ES log query to use raw data query
4. Click on any ad-hoc filter icon <img src="https://user-images.githubusercontent.com/1170767/95315089-f6daac80-0889-11eb-8049-b8e537967c55.png">

**Comment by svennergr** [comment]
I think we are facing two issues here:
1. [This line](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/types.ts#L32) is missing, that the `onCellFilterAdded` can also be `undefined`. Leading to just trying to call the method [in here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Table/CellActions.tsx#L29). I will double check with user-essentials and create an issue for them.
2. The ElasticSearch datasource is indeed missing a `modifyQuery` method. I will create an PR to fix this.
