### ISSUE TITLE
Dynamic Thresholds

### ISSUE THREAD

**Issue by biancalana** [grafana/grafana#2807]
Would be nice to have different thresholds depending on selected values in template. 

I have some cases where depending on selected object (ie: a lun from a storage) the SLA requirements change so would be perfect to adjust the thresholds depending on template value.
Its something like series specific overrides for Axes & Grid thresholds.

**Comment by torkelo** [comment]
good idea :)

already an issue for it 
https://github.com/grafana/grafana/issues/922
