### ISSUE TITLE
Cloudwatch custom metric results in server error when query metricFindQuery

### ISSUE THREAD

**Issue by markuman** [grafana/grafana#28075]
**What happened**:

Querying aws cloudwatch custom metrics results in a 500er server error when try to get the list of available metric names.

![grafanabug](https://user-images.githubusercontent.com/3920157/95314022-13c6ae00-0891-11eb-803b-25e96e1c14b0.gif)

Server log 

```
/grafana.....de ecs/grafana/f05454fc888745d99c4f82f261266df8 t=2020-10-07T09:30:21+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=markuman method=POST path=/api/tsdb/query status=500 remote_addr=10.103.11.8 time_ms=27 size=34 referer="https://grafana......de/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22AWS%20CloudWatch%22,%7B%22namespace%22:%22fluentd_metrics%22,%22metricName%22:%22%22,%22expression%22:%22%22,%22dimensions%22:%7B%7D,%22region%22:%22default%22,%22id%22:%22%22,%22alias%22:%22%22,%22statistics%22:%5B%22Average%22%5D,%22period%22:%22%22,%22matchExact%22:true%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D"

```

Browser Payload

```json
{"from":"1602059279729","to":"1602062879731","queries":[{"refId":"metricFindQuery","intervalMs":1,"maxDataPoints":1,"datasourceId":2,"type":"metricFindQuery","subtype":"metrics","region":"eu-central-1","namespace":"fluentd_metrics"}]}
```

Browser response 

```json
{"message":"Metric request error"}
```

**What you expected to happen**:

Autocomplete existings metric names and its dimensions.  
When a dimension is set, the autocomplete works again for its value.

**How to reproduce it (as minimally and precisely as possible)**:

Try to access aws cloudwatch custom metric.

**Anything else we need to know?**:

It works in the past.  But I cannot say for sure in which version it failed.  
Out past used versions. I believe 7.0.x it works fine.  
```
7.0.0
7.0.3
7.0.6
7.1.3
```

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Official Docker Container
- User OS & Browser: Firefox 81

**Comment by aknuds1** [comment]
Can you please paste more logs? The log message you pasted only states that 500 is returned to the client, and there are probably logs before that describing the cause.

**Comment by markuman** [comment]
@aknuds1 Ok, I've found the relevant log line

```
/grafana.lekker.de ecs/grafana/7c3c125fa82e4b159dfca195ce64c070 t=2020-10-08T08:23:30+0000 lvl=dbug msg="Listing metrics pages" logger=tsdb.cloudwatch
/grafana.lekker.de ecs/grafana/7c3c125fa82e4b159dfca195ce64c070 t=2020-10-08T08:23:30+0000 lvl=eror msg="Metric request error" logger=context userId=2 orgId=1 uname=markuman error="unable to call AWS API: InvalidParameter: 1 validation error(s) found.\n- minimum field size of 1, ListMetricsInput.Namespace.\n" remote_addr=10.103.11.11
```

**Comment by aknuds1** [comment]
Thanks, that helps.

**Comment by aknuds1** [comment]
Will try to reproduce.

**Comment by mitchmckenzie** [comment]
Also seeing this on our grafana 7.2 instance.
![image](https://user-images.githubusercontent.com/1819482/95462561-4928d580-093d-11eb-9ea8-e8f8e63b627d.png)

**Comment by mitchmckenzie** [comment]
@aknuds1 Were you able to reproduce this issue?  I tried a new custom metric and am now getting the same response @markuman is getting in the original post.
