### ISSUE TITLE
Error connecting to loki when using Mozilla firefox because of wrong timestamp

### ISSUE THREAD

**Issue by mielemilos** [grafana/grafana#28077]
An error is shown when connection to loki using the grafana web interface
`Loki: Bad Request. 400. invalid query, through < from (1602063114.464 < 1602068953.975) `

**What you expected to happen**:
A working connection, no error

**How to reproduce it (as minimally and precisely as possible)**:
installed using docker-compose: https://raw.githubusercontent.com/grafana/loki/v1.6.0/production/docker-compose.yaml
**Have an incorrect time setting on the client system (something in the future)** 
login using firefox 
nagivate to explore or add datasource
add loki with http://loki:3100

**Anything else we need to know?**:
Chrome works fine

**Environment**:
- Grafana version: v7.2.0 (efe4941ee3)
- Data source type & version: loki:1.5.0
- OS Grafana is installed on: linux
- User OS & Browser: linux (fedora 32) mozilla firefox 81.0.1 (64-bit)
- Grafana plugins: none/default
- Others:

**Comment by aknuds1** [comment]
Could you also add to the _How to reproduce it _ section how to trigger the bug? You're missing that part.

FWIW, I just tested you docker-compose.yml (although I changed _latest_ with _7.2.0_) and I can query Loki in Firefox without problems (via a table panel).

**Comment by mielemilos** [comment]
I found the trigger: an incorrect time on the client.
when exploring I see the following call:

1. http://localhost:3000/api/datasources/proxy/1/api/prom/label?start=1602077290738000000&end=1602080890739000000
2. http://localhost:3000/api/datasources/proxy/1/api/prom/label?start=1602080290873000000
3. http://localhost:3000/api/datasources/proxy/1/api/prom/label/job/values?start=1602077290738000000&end=1602080890739000000

The first and last work, but 2 gives an error 
After setting the time correctly (1602069844173000000 in this example) all calls return correctly.

Not sure if this is a bug or by design but it seems weird that a client-time-error triggers a connection-error in the ui.


Also why is the second call using a different timestamp for the start value?
1. 1602077290738000000
2. 1602080290873000000
3. 1602077290738000000

**Comment by aknuds1** [comment]
As I asked though, can you update the issue description as follows? 

> Could you also add to the How to reproduce it section how to trigger the bug? You're missing that part.

**Comment by mielemilos** [comment]
I added the line (in bold): Have an incorrect time setting on the client system

**Comment by aknuds1** [comment]
And what do you do after the last step listed, "add loki with http://loki:3100"? Trigger the bug through some query?

**Comment by mielemilos** [comment]
no, it pops up
Correct time:
![image](https://user-images.githubusercontent.com/6410323/95328357-c0128f80-08a5-11eb-8211-4bc3b5c3e224.png)
Time in the future:
![image](https://user-images.githubusercontent.com/6410323/95328434-d7ea1380-08a5-11eb-8eaa-e8a1ebc3e6ce.png)

**Comment by aknuds1** [comment]
But why do you say in the issue description that you get the following error in the UI:

> Loki: Bad Request. 400. invalid query, through < from (1602063114.464 < 1602068953.975)

Your screenshot contradicts the above.

**Comment by mielemilos** [comment]
You're right, this is what happend the first time and this is an older version of both grafana and loki.

The error returned has the same message but a 500 http return code.

After that I installed the submitted version locally and got the error as submitted.
I'll remove these screenshots and try to properly recreate the error

**Comment by aknuds1** [comment]
If you get a 400 error, I don't see why it's a bug? The client sends an invalid time and Loki responds with an error. What else should happen?

**Comment by mielemilos** [comment]
That's a good question. In this case I had not selected a date and got an error suggesting that loki was down and that grafana was not able to connect to it. This was also the case when trying to add loki as a datasource and that might give the user a wrong impression.

But as i'm trying to re-reproduce to get a screenshot I, of course, cannot get the error back.
So let's close this for now, i'll keep playing around.

And I'll leave it to you if you think that the datasource-add-scenario is worth a feature request :thinking:

**Comment by aknuds1** [comment]
I don't see how the error message you posted indicates that Loki is down, rather that there's an error connecting to it.
