### ISSUE TITLE
Table panel column headers collide with each other when use zoom-in in browser 

### ISSUE THREAD

**Issue by yuvalman** [grafana/grafana#28081]
**What happened**:
In a table panel,
When I zoom-in the browser, the columns headers of the table collide with each other and we can not see the headers clearly. 
here is a recording of the bug:
![table_columns_headers_bug](https://user-images.githubusercontent.com/25984852/95320277-efbf9880-08a1-11eb-9f9b-855cc4f86a33.gif)

**What you expected to happen**:
I expect that when I zoom-in in the browser, I could see the column headers clearly.

Suggestion: maybe you can give the option to have a multiline option to the column headers (similar to the question described here: https://community.grafana.com/t/table-in-grafaha-v7-multiline-cell-records/32889)

**How to reproduce it (as minimally and precisely as possible)**:

1.  Create a new **table** panel dashboard with a few columns (their column header should be a long string).
2.  Increase the zoom in the browser until you see the bug occur.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.7.4 
- Data source type & version: built-in InfluxDB with Flux query type
- OS Grafana is installed on: Ubuntu 18.04.3 LTS (GNU/Linux 4.15.0-88-generic x86_64)
- User OS & Browser: Windows 10 18363 & chrome 85.0.4183.121
- Grafana plugins: none
- Others: none

**Comment by aknuds1** [comment]
v6.5.x is unsupported at this point. Have you tried v7.2.x instead?

**Comment by yuvalman** [comment]
I've tried with v6.7.4.
We get the same bug: 
![table_columns_headers_bug_6_7_4](https://user-images.githubusercontent.com/25984852/95560059-6040f380-0a21-11eb-954e-4f1b1b77a3da.gif)

I would like to suggest another solution besides the one I suggested before:
Add the option to dynamically change column headers row height when the header string is longer than the cell width.

Please let me know if you need anything else.

**Comment by dprokop** [comment]
This issue was fixed in Grafana 7. Please update to the latest version if possible.
