### ISSUE TITLE
test packages in stable repositories

### ISSUE THREAD

**Issue by carazzim0** [grafana/grafana#28099]
**What happened**: Grafana on Debian upgraded to `7.3.0~test` due to unattended-upgrades

**What you expected to happen**: No packages called "test" in stable repositories 😉 

**How to reproduce it (as minimally and precisely as possible)**:
```
cat /etc/apt/sources.list.d/grafana.list
# This file is managed by Puppet. DO NOT EDIT.
# grafana
deb http://packages.grafana.com/oss/deb stable main
```

`apt policy grafana` lists "test" package and automatically installs it, if no apt pinning is in place.

```
root@xxx:# apt policy grafana
grafana:
  Installed: 7.2.0
  Candidate: 7.2.0
  Version table:
     7.3.0~test 1
          1 http://packages.grafana.com/oss/deb stable/main amd64 Packages
 *** 7.2.0 500
          1 http://packages.grafana.com/oss/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
     7.1.5 1
          1 http://packages.grafana.com/oss/deb stable/main amd64 Packages
     7.1.4 1
          1 http://packages.grafana.com/oss/deb stable/main amd64 Packages
...
```
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: /
- OS Grafana is installed on: Debian
- User OS & Browser: /
- Grafana plugins: /
- Others: /

**Comment by aknuds1** [comment]
@carazzim0 Thanks for reporting this! I'll see if I can remove it.

**Comment by aknuds1** [comment]
I see why it happens now, it's a bug in some new CI logic :man_facepalming: Will do my best to clear it up.

**Comment by aknuds1** [comment]
Hi, can you just see if the version is gone now please? I've tried pruning it from the repo, but not 100% sure if I did everything required.

**Comment by carazzim0** [comment]
Hi @aknuds1, thanks for looking into this.

I setup the repository on a new Debian server and the package is still listed in the releases file, but is not available to be installed via `apt`.

Releases file:
```
root@dalaran:/var/lib/apt/lists# grep Filename packages.grafana.com_oss_deb_dists_stable_main_binary-amd64_Packages
Filename: pool/main/g/grafana/grafana_7.3.0~test_amd64.deb
Filename: pool/main/g/grafana/grafana_7.2.0_amd64.deb
Filename: pool/main/g/grafana/grafana_7.1.5_amd64.deb
```

`apt download grafana` fails:

```
xxx@dalaran:~$ apt download grafana
Get:1 https://packages.grafana.com/oss/deb stable/main amd64 grafana amd64 7.3.0~test [53.0 MB]
Err:1 https://packages.grafana.com/oss/deb stable/main amd64 grafana amd64 7.3.0~test
  File has unexpected size (53020240 != 53038324). Mirror sync in progress? [IP: 2a04:4e42:3::729 443]
  Hashes of expected file:
   - SHA512:2490821371031bbe81106c53ea7fdd0e454529321548c12bdbcf3ee2868a90932f4448b6a250d0ddc74c993ca7e8892e23088c980f5856fef5bad24fcca38f8e
   - SHA256:6e4867a836c4d5c23cd0a4858f17293f330b7ed85cafaf8cfc956d6f538d48bf
   - SHA1:557dbdf1eed5ed339b6db930d9086ed74d76b8b9 [weak]
   - MD5Sum:6f96b3de9c52cc37378878da0456d8ad [weak]
   - Filesize:53038324 [weak]
E: Failed to fetch https://packages.grafana.com/oss/deb/pool/main/g/grafana/grafana_7.3.0~test_amd64.deb  File has unexpected size (53020240 != 53038324). Mirror sync in progress? [IP: 2a04:4e42:3::729 443]
   Hashes of expected file:
    - SHA512:2490821371031bbe81106c53ea7fdd0e454529321548c12bdbcf3ee2868a90932f4448b6a250d0ddc74c993ca7e8892e23088c980f5856fef5bad24fcca38f8e
    - SHA256:6e4867a836c4d5c23cd0a4858f17293f330b7ed85cafaf8cfc956d6f538d48bf
    - SHA1:557dbdf1eed5ed339b6db930d9086ed74d76b8b9 [weak]
    - MD5Sum:6f96b3de9c52cc37378878da0456d8ad [weak]
    - Filesize:53038324 [weak]
```

So there still must be something wrong :/

**Comment by aknuds1** [comment]
Thanks for the update. We are in the process of syncing the repo metadata, will let you know when it's done.

**Comment by carazzim0** [comment]
FYI: the test version was also pushed to RPM / YUM repositories.

```
srv02 :: yum --showduplicates list grafana
...
grafana.x86_64                                                                7.1.4-1                                                                          grafana
grafana.x86_64                                                                7.1.5-1                                                                          grafana
grafana.x86_64                                                                7.2.0-1                                                                          grafana
grafana.x86_64                                                                7.3.0~test-1                                                                     grafana
```

**Comment by aknuds1** [comment]
Yeah, I'm aware it was uploaded to RPM, and I tried to prune it from there too. As I remember it, RPM repo structure is trickier to figure out, but I thought removing the package was enough. Let me check.

**Comment by rpthms** [comment]
I think along with removing the test package from the repo, we should also create new packages that are actually just 7.2.0 but with the epoch set to 1 to force a downgrade on all the folks who accidentally upgraded to 7.3.0~test.

**Comment by aknuds1** [comment]
@rpthms How do you technically set the epoch to 1? I'm not an RPM expert.

**Comment by rpthms** [comment]
It's not really an RPM thing. Most package manager support epochs to force a downgrade for whatever reason. Are you creating your packages using FPM? I think there's a flag called --epoch which could be used. I'll need to check

**Comment by aknuds1** [comment]
We are using FPM yes.

**Comment by aknuds1** [comment]
@rpthms FPM has an `--epoch` flag, do you know what the default value is?

**Comment by rpthms** [comment]
According to this blog, RPM doesn't use an epoch by default (https://utcc.utoronto.ca/~cks/space/blog/linux/RPMEpochNumbers?showcomments). So just setting it to 1 should be okay. 

In Debian's case, the default epoch is 0 (https://www.debian.org/doc/debian-policy/ch-controlfields.html#version)

**Comment by aknuds1** [comment]
@rpthms The question is if FPM has a default for `--epoch`. I couldn't really tell yet.

**Comment by rpthms** [comment]
@aknuds1 If I'm reading this pull request correctly, the epoch is null or not used by default: https://github.com/jordansissel/fpm/pull/1053

**Comment by rpthms** [comment]
Whoops sorry, wrong issue. This is the right one: https://github.com/jordansissel/fpm/issues/381

**Comment by aknuds1** [comment]
@rpthms According to FPM's changelog, --epoch's default value (1) was removed in 2013.

**Comment by rpthms** [comment]
Does Grafana have packages that are older than 2013? If not, I guess we could go with --epoch=1.

**Comment by aknuds1** [comment]
@rpthms So in practical terms, if we bump the epoch of the 7.2.1 to 1, it will downgrade 7.3.0-test? And we have to keep that epoch for all future packages (so they can upgrade 7.2.1)?

**Comment by rpthms** [comment]
Yes, for the package manager the epoch holds the final say and can override the package versioning schemes. So 1:7.2.1 would be preferred over 7.3.0. 

> And we have to keep that epoch for all future packages

Yes, once you start using the epoch, you cannot decrease it or remove it. If you do that then future packages will not be considered as upgrades by the package manager.

**Comment by aknuds1** [comment]
Right. I think there could be some risk to changing our RPM package name (due to bumped epoch), so that has to be taken into consideration also.

**Comment by aknuds1** [comment]
Do you know how the epoch eventually affects the RPM name?

**Comment by rpthms** [comment]
Unfortunately, I'm not too sure about RPM. I'm more of a Debian guy. Right now I have an Ubuntu box in front of me, so I can let you know how the epoch affects package names there:

Using busybox-static as an example.

Version: 1:1.30.1-4ubuntu6.2
FileName: /var/cache/apt/archives/busybox-static_1%3a1.30.1-4ubuntu6.2_amd64.deb

**Comment by rpthms** [comment]
@aknuds1 I just tried running a CentOS 8 VM and I can see that the epoch does not show up in the RPM file name

Using bind-export-libs as an example (which has an epoch of 32!)

Version: 32:9.11.13-6.el8_2.1
FileName: /var/cache/dnf/BaseOS-e497ce4923b1f449/packages/bind-export-libs-9.11.13-6.el8_2.1.x86_64.rpm

Output of `yum info bind-export-libs`:
```
[root@li2118-59 ~]# yum info bind-export-libs
Last metadata expiration check: 0:05:21 ago on Thu 08 Oct 2020 08:44:29 AM UTC.
Installed Packages
Name         : bind-export-libs
Epoch        : 32
Version      : 9.11.13
Release      : 6.el8_2.1
Architecture : x86_64
Size         : 2.9 M
Source       : bind-9.11.13-6.el8_2.1.src.rpm
Repository   : @System
From repo    : BaseOS
Summary      : ISC libs for DHCP application
URL          : http://www.isc.org/products/BIND/
License      : MPLv2.0
Description  : BIND (Berkeley Internet Name Domain) is an implementation of the DNS
             : (Domain Name System) protocols. This package set contains only export
             : version of BIND libraries, that are used for building ISC DHCP.

Available Packages
Name         : bind-export-libs
Epoch        : 32
Version      : 9.11.13
Release      : 6.el8_2.1
Architecture : i686
Size         : 1.2 M
Source       : bind-9.11.13-6.el8_2.1.src.rpm
Repository   : BaseOS
Summary      : ISC libs for DHCP application
URL          : http://www.isc.org/products/BIND/
License      : MPLv2.0
Description  : BIND (Berkeley Internet Name Domain) is an implementation of the DNS
             : (Domain Name System) protocols. This package set contains only export
             : version of BIND libraries, that are used for building ISC DHCP.
```

**Comment by rpthms** [comment]
So, I guess only the Debian package names are getting affected by the epoch.

**Comment by carazzim0** [comment]
I can mainly speak for Debian systems only.
Either way on someone's end something will break or must be adjusted manually. 
* Introducing epochs will break people's already existing version pinnings.
* By mistake upgraded versions should / must / can be downgraded by hand once the repo has been fixed

So please keep that in mind.

**Comment by aknuds1** [comment]
From checking around, bumping the epoch doesn't look like a safe alternative. It will probably also affect the .deb filenames if I'm not mistaken?

@carazzim0 Sounds from what you're saying as if bumping the epoch isn't a good choice.

**Comment by aknuds1** [comment]
Our current plan is to sync our Deb and RPM repos today so they are pruned of v7.3.0-test. When 7.3.0 is released (ETA for beta1 middle of next week), that should upgrade 7.3.0-test regardless right?

**Comment by rpthms** [comment]
Epochs are not really that dangerous. They're just a part of the package versioning scheme. Almost every distro in existence have packages with epochs in them. If we use epochs, then the user doesn't have to do anything but run a package upgrade to get rid of the non-stable package. I would argue that's the simplest course of action that we could take, but hey I'm also fine with doing a manual downgrade.

**Comment by aknuds1** [comment]
I'm also worried that filename changes will break e.g. our download pages, it's difficult to foresee what might break in our processes.

**Comment by RalfJung** [comment]
> So, I guess only the Debian package names are getting affected by the epoch.

The package name is not affected by the epoch in Debian, just the version number is.

**Comment by lcheylus** [comment]
Same issue this morning for me after `apt upgrade` on my Grafana server => version 7.3-test installed.

Temporary fix waiting for repository sync => desinstall Grafana v7.3-test and force install version 7.2

```
$ sudo apt remove grafana
$ sudo rm /var/lib/apt/lists/packages.grafana.*
$ sudo apt update
$ apt-cache policy grafana|head -10
grafana:
  Installed: (none)
  Candidate: 7.3.0~test
  Version table:
     7.3.0~test 500
        500 https://packages.grafana.com/oss/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
     7.2.0 500
        500 https://packages.grafana.com/oss/deb stable/main amd64 Packages

$ sudo apt install grafana=7.2.0
$ dpkg -l grafana
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  grafana        7.2.0        amd64        Grafana
```

**Comment by rpthms** [comment]
> > So, I guess only the Debian package names are getting affected by the epoch.
> 
> The package name is not affected by the epoch in Debian, just the version number is. In your example, the package name is still "busybox-static".

Yeah, I did mean the file name instead of the package name. Thanks for pointing that out.

**Comment by drohhyn** [comment]
Problem solved for me on Ubuntu 18.04.5 LTS

**Comment by lcheylus** [comment]
Grafana Debian repository correctly synchonized for version 7.2.0.

```
$ sudo rm /var/lib/apt/lists/packages.grafana.*
$ sudo apt update
(...)
Hit:6 https://repos.influxdata.com/debian buster InRelease                                                                                                                                   
Fetched 30.4 kB in 6s (5,061 B/s)                                                                                                                                                                                                                                              
Reading package lists... Done
Building dependency tree       
Reading state information... Done
All packages are up to date.
$ sudo apt-cache policy grafana|head -10
grafana:
  Installed: 7.2.0
  Candidate: 7.2.0
  Version table:
 *** 7.2.0 500
        500 https://packages.grafana.com/oss/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
     7.1.5 500
        500 https://packages.grafana.com/oss/deb stable/main amd64 Package
```

**Comment by aknuds1** [comment]
The OSS Deb repo should be fixed now, but I hear enterprise might still need syncing.

**Comment by aknuds1** [comment]
The RPM repos (OSS/enterprise) should be back to normal.

**Comment by aknuds1** [comment]
The enterprise Deb repo should be fixed.

That concludes our measures in rectifying this mistake. So sorry again! Hopefully we will avoid this from happening again in the future, as our CI systems have matured significantly.
