### ISSUE TITLE
Grafana dashboard panel with multiple timeseries strips off some of the timeseries data on hover over

### ISSUE THREAD

**Issue by debashish-github** [grafana/grafana#28093]
**What happened**:
I have a dashboard panel with about 60 different timeseries data .
I have set up the hover tooltip to show all series with sort as descending.
But when I hover over the timeseries it only shows first few items. 

**What you expected to happen**:
Need to see all the items in the timeseries in the hover over panel
**How to reproduce it (as minimally and precisely as possible)**:
Create a panel with more than 60 timeseries .
Set the hover over to display all timeseries.
hover over all the time series.
**Anything else we need to know?**:

**Environment**:
- Grafana version:6.6.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Windows
- User OS & Browser: Windows - Google Chrome
- Grafana plugins:
- Others:
![hover_over_issue](https://user-images.githubusercontent.com/16272363/95395618-0d562780-08cd-11eb-816b-fca1b675aa12.JPG)

**Comment by aknuds1** [comment]
Can you try upgrading to v7.2.0, or at the very least 6.7.4? We don't support 6.6 any longer.

**Comment by torkelo** [comment]
Can be solved by adding a limit the tooltip #12611

**Comment by debashish-github** [comment]
But adding a limit will only limit the number of items. What I want is some kind of a scroll bar that I can pull up or down to see all the values. Is this possible ?

**Comment by debashish-github** [comment]
Any answers for this ? There should be some key short cuts to scroll through the scroll bar for the hover over panel .. no ?
