### ISSUE TITLE
[Feat Req] Support streaming from InfluxDB

### ISSUE THREAD

**Issue by m5x** [grafana/grafana#28097]
**What would you like to be added**:

Support for streaming in InfluxDB input data source plugin.

**Why is this needed**:

For efficient real-time monitoring of high frequency sources.

**Comment by torkelo** [comment]
Can you link to info on InfluxDB's query streaming capable API?

**Comment by m5x** [comment]
I haven't found any so it seems that for the InfluxDB 2.0 it is not yet documented. However it was planned for this year so it might already be implemented. I asked [a question](https://community.influxdata.com/t/stream-events-in-influxdb-2-0/12974/4) on InfluxDB  community forums, hopefully someone will be able to provide more info.

**Comment by gabor** [comment]
@m5x unfortunately it seems streaming did not happen in InfluxDB2 yet, so there's nothing we can do on grafana-side for now. if things change and InfluxDB gets the streaming-support, we can reopen this feature request.

**Comment by ryantxu** [comment]
Note if you are feeding influx with telegraf, in grafana 8 you can use:
https://grafana.com/tutorials/stream-metrics-from-telegraf-to-grafana/

When we find a query that keeps returning data, we can hook into a similar system
