### ISSUE TITLE
Hash sum mismatch while upgrading

### ISSUE THREAD

**Issue by NorbertRonecker** [grafana/grafana#28107]
**What happened**:
On a Ubuntu 18.04 Server upgrades fail because of some hash sum failures.

# apt-get upgrade --yes
[...]
E: Failed to fetch https://packages.grafana.com/oss/deb/pool/main/g/grafana/grafana_7.3.0~test_amd64.deb  Hash Sum mismatch

**What you expected to happen**:
Upgrade of everything.

**How to reproduce it (as minimally and precisely as possible)**:
1. LC_ALL=C apt upgrade --yes

**Anything else we need to know?**:
Apt sources are configured as described in the [docs](https://grafana.com/docs/grafana/latest/installation/debian/).

**Environment**:
- Grafana version: -> 7.3.0
- Data source type & version: 
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: 
- Grafana plugins: 
- Others:

**Comment by quinox** [comment]
I blacklisted this version to make it not block other updates:
```bash
$ cat /etc/apt/preferences.d/broken_software

Package: grafana
Pin: version 7.3.0~test
Pin-Priority: -1
```

**Comment by aknuds1** [comment]
I must've missed this one. Closing as dup of #28099, since it's already discussed there.
