### ISSUE TITLE
Panel with queries from different sources not working

### ISSUE THREAD

**Issue by priyanr** [grafana/grafana#28114]
When a panel configured with query from different source in my case query A is application insights and query B is azure log anlytics. In query inspector no data is returned. It seems for different sources grafana is making two requests to 
/api/ds/query one for application insights and one for log anytics i can see in browser one query is getting blocked. Tried in both chrome and firefox same result chrome its showing cancelled. This was working fine before , i am not sure which version was running before as this was in kubernetes and when kubernetes cluster upgraded and restarted i think it downloaded a new container version. Attached the screenshot of network call from browser

Grafana version  v7.2.0

![grafana](https://user-images.githubusercontent.com/355365/95458178-dfcbb580-0982-11eb-80d4-a42adcf57af0.png)

**Comment by kylebrandt** [comment]
Can replicate on my local instance with currentish master:

![image](https://user-images.githubusercontent.com/1692624/95493947-2c0afb80-096b-11eb-8659-09196184da22.png)

Same when using mixed datasource.

**Comment by hugohaggmark** [comment]
Seems like the requests get the same `requestId` for some reason so when the second one starts the first request ends up here and cancels:
https://github.com/grafana/grafana/blob/d18178294364112cd28950bcbb3c7727ed6a847f/public/app/core/services/backend_srv.ts#L326

I'm not familiar with these data sources so I'm going to need some time to find where the root cause is.

**Comment by hugohaggmark** [comment]
I will continue this investigation on Monday, lot's of other things have come in between :(

**Comment by kylebrandt** [comment]
> I will continue this investigation on Monday, lot's of other things have come in between :(

Thanks, I think this was different data sources that were brought together, so maybe something there.

The following looks pretty sketchy:

https://github.com/grafana/grafana/blob/670b8512bfb7a9b343d7e0ce34bb09857493e807/public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts#L81-L109

**Comment by kylebrandt** [comment]
FYI if I do something after the deep clone like:

```
      // Initialize the list of queries
      let q = byType[target.queryType];
      if (!q) {
        q = _.cloneDeep(options);
        q.requestId += q.requestId + Math.random().toString(36).substring(2, 15) + Math.random().toString(36).substring(2, 15);
        q.targets = [];
        byType[target.queryType] = q;
      }
      q.targets.push(target);
```

The request is no longer cancelled.

**Comment by kylebrandt** [comment]
@hugohaggmark I think this might not have resolved the issue fully. While it is no longer cancelled, it seems like data is lost.

For example with the following there is no data in the fields it seems:

![image](https://user-images.githubusercontent.com/1692624/95859501-b6b57700-0d2c-11eb-93e7-ddc46dc869a0.png)

However, if I disable one of the two queries, than I get data:

![image](https://user-images.githubusercontent.com/1692624/95859596-d9e02680-0d2c-11eb-927b-6af366df3d83.png)

![image](https://user-images.githubusercontent.com/1692624/95859625-e6647f00-0d2c-11eb-9772-92f9dc676c93.png)

**Comment by hugohaggmark** [comment]
> @hugohaggmark I think this might not have resolved the issue fully. While it is no longer cancelled, it seems like data is lost.
> 
> For example with the following there is no data in the fields it seems:
> 
> ![image](https://user-images.githubusercontent.com/1692624/95859501-b6b57700-0d2c-11eb-93e7-ddc46dc869a0.png)
> 
> However, if I disable one of the two queries, than I get data:
> 
> ![image](https://user-images.githubusercontent.com/1692624/95859596-d9e02680-0d2c-11eb-927b-6af366df3d83.png)
> 
> ![image](https://user-images.githubusercontent.com/1692624/95859625-e6647f00-0d2c-11eb-9772-92f9dc676c93.png)

Oh noes, I'll look into it ASAP.

**Comment by priyanr** [comment]
I can confirm its working in  7.3.1 release. Thank you guys
