### ISSUE TITLE
Feature Request : Duplicate Button for Template Variables

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2811]
Copy template variables via duplicate button like show below:

<img width="983" alt="screen shot 2015-09-23 at 5 14 09 pm" src="https://cloud.githubusercontent.com/assets/1019609/10044203/afcf50d0-6216-11e5-9ba1-db9655c32489.png">

**Comment by utkarshcmu** [comment]
<img width="738" alt="screen shot 2015-11-14 at 12 25 24 pm" src="https://cloud.githubusercontent.com/assets/1019609/11165678/dee5dd4e-8aca-11e5-9c8a-2ecbd524e729.png">

Adding so many details again and again. Typing in all the fields when creating multiple variables is a pain. It would be great if we can have that Duplicate button as it will **pre-fill** all fields. So, that the user will just change whatever is needed.

This will surely make the creation of template variables super user-friendly.

**Comment by toni-moreno** [comment]
+1

**Comment by utkarshcmu** [comment]
There is already a PR open for this feature. #2812 

Feel free to review it and hopefully it can be merged soon. :)

**Comment by utkarshcmu** [comment]
Closed bcoz #2812 is merged.
