### ISSUE TITLE
Error occurs when using global variable $__user in MySQL query variable

### ISSUE THREAD

**Issue by awarm** [grafana/grafana#28125]
**What happened**: After place __user global variable in field "Query" with MySQL datasource and leave this field, Grafana send two alert: "Validation - e.replace is not a function",  and "Templating - Template variables could not be initialized: e.replace is not a function"

**What you expected to happen**: User Grafana user id in MySQL query

**How to reproduce it (as minimally and precisely as possible)**: Create dashboard variable, choose Type: Query. Select data source MySQL. In Query field place "SELECT $__user;" and leave field Query.

**Anything else we need to know?**: no

**Environment**:
- Grafana version: Grafana v7.2.0 (efe4941ee3)
- Data source type & version: build in MySQL datasource 
- OS Grafana is installed on: docker
- User OS & Browser: Windows 10 + Chrome
- Grafana plugins:
- Others:
![Снимок](https://user-images.githubusercontent.com/12966796/95498739-f1c24e00-09ac-11eb-9836-862336a47e8c.PNG)

**Comment by torkelo** [comment]
@aknuds1 did you replicate this? needs investigation label needs to be paired with it being added to squad board as well. This looks like a frontend issue

**Comment by aknuds1** [comment]
@torkelo I think I was planning to try to reproduce this one, and forgot. Probably why I didn't add it to a board yet. There were a lot of issues to get through this week.

**Comment by torkelo** [comment]
you can work around this error by specifying `${__user.login}`  

The bug is that __user is an object, and we pass this to the custom mysql interpolate function, this does not handle objects (rigtly). We should check if value is an object here: https://github.com/grafana/grafana/blob/master/public/app/features/templating/template_srv.ts#L115 and if so transform it to string using `${value}`

**Comment by torkelo** [comment]
Fix PR https://github.com/grafana/grafana/pull/28171
