### ISSUE TITLE
A possibility to switch off the "smart" functionality of the PromQL query's editor

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#28134]
**What would you like to be added**:
I really need to re-open https://github.com/grafana/grafana/issues/20929.

**Why is this needed**:
When there are more complex queries within the query editor (`Edit Panel`), those long responses, cursor jumps make it unusable.

`Grafana v7.2.0 (NA)`

**Comment by aknuds1** [comment]
@davkal Please have a look.

**Comment by Elfo404** [comment]
Hi @hawran , we are not planning to provide this option anytime soon, we would rather fix the performance issues that causes this. We have an open issue to improve autcompletes architecture and performance (https://github.com/grafana/grafana/issues/24959) and hopefully it will also solve this kind of issues.
