### ISSUE TITLE
Notifier ShowWhen struct not working as expected

### ISSUE THREAD

**Issue by ericayosh** [grafana/grafana#28132]
**What happened**:
I am creating a new notifier and want to provide a way for users to select an Auth Provider, either a Credential Profile, AWS ARN, or Access Key & Secret. These same options are available for customers setting up the CloudWatch DataSource today. 

**What you expected to happen**:
In the code for the notifier, I used the [ShowWhen](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifier.go#L80-L84) struct to display the relevant auth fields,  based on the Auth Provider the user selects. 

The fields displayed using `ShowWhen` only appear when the other required fields (Notification Channel Name and SNS Topic) are *not* already filled in. Once I remove either of these fields the ShowHide elements appear on the page. 

Further, if fill in the Topic and name, and change the Auth Provider selection, the `ShowWhen` elements are not refreshed. If I remove either the Name or the Topic and change the Auth Provider selection the page does automatically refresh the boxes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The `ShowWhen` elements for the Pushover notifier channel do not have either of these issues. [[link](https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/pushover.go#L153-L174)]

**Environment**:
- Grafana version: 7.3.0
- Data source type & version: n/a
- OS Grafana is installed on: mac
- User OS & Browser: 
   * macOS High Sierra 10.13.6
Reproduced the issue in the following browsers:
   * Safari 13.1.2
   * Chrome 86.0.4240.75
   * Firefox Quantum 68.11.0esr 
   
- Grafana plugins: n/a
- Others:

**Comment by peterholmberg** [comment]
Thanks for reporting this, I have opened a PR that I hope resolves this.
