### ISSUE TITLE
Proxy Auth and Organizations

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#2814]
I try to realize this scheme: 
- users comes from external application and authorized via proxy auth.
- users auto sign up into Grafana.
- each user can create, edit and save their own dashboards.
I configure Grafana for this case:
```
...

#################################### Users ####################################
[users]
allow_sign_up = true
allow_org_create = true
auto_assign_org = false
auto_assign_org_role = Viewer

...

#################################### Basic Auth ##########################
[auth.basic]
enabled = false

#################################### Auth Proxy ##########################
[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true
```

This config works, users properly authenticates, but I have a problem: each user is created in organization with same name, but **dashboards shares between all users**.

![screenshot 2015-09-23 22 09 47](https://cloud.githubusercontent.com/assets/4932851/10055622/f044ebd8-623f-11e5-945d-9a87722335f8.png)

Is it bug?

**Comment by torkelo** [comment]
not sure that is possible, dashboards belong to a an organization, they all users must in this case belong to the same org. Can you show content of org_user table and dashboard table? For dashboard table only title and org_id columns are interesting

**Comment by alexanderzobnin** [comment]
```
sqlite> select * from org_user;
1|1|1|Admin|2015-09-17 21:18:52|2015-09-17 21:18:52
2|2|2|Admin|2015-09-23 18:25:08|2015-09-23 18:25:08
3|3|3|Admin|2015-09-23 18:25:10|2015-09-23 18:25:10
4|4|4|Admin|2015-09-23 18:26:25|2015-09-23 18:26:25
5|5|5|Admin|2015-09-23 18:31:15|2015-09-23 18:31:15
6|6|6|Admin|2015-09-23 18:40:02|2015-09-23 18:40:02
7|7|7|Admin|2015-09-23 18:41:13|2015-09-23 18:41:13

sqlite> select title, org_id from dashboard;
Annotations|1
grafana-zabbix.org|1
Grafana-Zabbix demo|1
user5|3
user3|3
user4|3
```
Strange, dashboards user5, user3, user4 assigned to organization with id 3. But each theese dashboards has been saved by corresponding users.

**Comment by alexanderzobnin** [comment]
@torkelo sorry, seems this problem in my apache config.
