### ISSUE TITLE
A possibility to switch off a panel within a dashboard (to not to query).

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#28140]
**What would you like to be added**:
I have got a bunch of related panels within a dashboard, all displaying data on most occasions.
It would be nice to have an option to switch a (selected) panel off so it does not query a data source.

Without going to "edit panel", hence this option should be a visible "property" of the panel.

Persistence (a cookie?) would be the icing on the cake.

**Why is this needed**:
When I need to track down some exceptional behaviour, one, particular panel of the dashboard is mostly enough (hopefully) when exploring data to solve the problem.

**Comment by torkelo** [comment]
You can place then in a row and collapse the row

**Comment by hawran** [comment]
Hi,
I've just been notified about the `v` shortcut (view).
AFAIR I stopped to use it as it had seemed as if panels (on the background) still queried data sources.

If really is the panel on the foreground the only panel querying a data source I can live with that and this issue can be closed.

**Comment by torkelo** [comment]
Queries in the background should not be queried

**Comment by hawran** [comment]
> You can place then in a row and collapse the row

Yep, this is another option, thank you for reminding me.

**Comment by aknuds1** [comment]
Should this issue still be open, given the method @torkelo provided?
