### ISSUE TITLE
generated query ignores timezone in timepicker

### ISSUE THREAD

**Issue by EBZ-Krisemendt** [grafana/grafana#28146]
**What happened**:
$__timefilter(column) translates to UTC

**What you expected to happen**:
$__timefilter(column) translates to CEST

**How to reproduce it (as minimally and precisely as possible)**:
create a query using "WHERE $__timefilter(column)"
set dashboard timezone to CEST
pick 'Last 6 hours' (or any other range that ends at 'now()')
hover timepicker to check if timerange is correct
display 'query-inspector'
you should see the filter translated to wrong timeframe (UTC instead of CEST)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.2.0 (efe4941ee3)
- Data source type & version: PostgreSQL 12.4 (Ubuntu 12.4-1.pgdg20.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 9.3.0-10ubuntu2) 9.3.0, 64-bit
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Win10 & Firefox
- Grafana plugins: none
- Others: none

**Comment by torkelo** [comment]
data points and time range filters are always UTC. 

The timezone setting is just a display setting
