### ISSUE TITLE
Bar Group by 60/90 Days

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#28170]
**What happened**:
When selecting 60/90 days in the time packer, when viewing a bar graph, there is a single/merged "mush" of color, with no clear distinction between time periods.
![Bars90Days](https://user-images.githubusercontent.com/1325158/95672879-df166780-0bac-11eb-9046-9036abdde119.png)

**What you expected to happen**: I expected to see distinct delineated time periods and values, as I get with 30 days.
![Bars30Days](https://user-images.githubusercontent.com/1325158/95672885-e63d7580-0bac-11eb-8a02-065cc361903a.png)

**How to reproduce it (as minimally and precisely as possible)**:
Change the time period from 30 to 90 days.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: SQL Server 2016
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Make sure you group your data consistently (ie same space between data points).

Please show your query, and your raw query results

**Comment by reuvygroovy** [comment]
You're right, sorry.
![image](https://user-images.githubusercontent.com/1325158/95673733-14728380-0bb4-11eb-9342-3b55018ef577.png)

Problem is we are trying to show a minimal daily rate, but when we select the 7-30 days time picker range, it groups by hours, and we cannot show a minimum day count unless we hard code it. But then we run into a problem with larger dates.

**Comment by torkelo** [comment]
Not sure @reuvygroovy what your trying to do. The graph says meetings by day, so I assume your query has a group by day clause? You can use an interval variable you want to be able to change the group by time interval using a variable. https://grafana.com/docs/grafana/latest/variables/variable-types/add-interval-variable/. Then use that variable in your min interval & group by time SQL clause. That way you can have a dynamic group by time interval

@aknuds1 why label it a frontend bargauge issue, not a bar gauge nor really a frontend issue but a query issue.

**Comment by reuvygroovy** [comment]
My **query** has a group by $__interval param, but the problem is that when the timepicker has 30 days selected, grafana calculates the minimum interval to be 10m.
