### ISSUE TITLE
Annotations List Panel aka annolist (alpha) - all annotations are shown disregard "Within Time Range" setting

### ISSUE THREAD

**Issue by leonsery** [grafana/grafana#28172]
**What happened**:
All annotations are shown disregard "Within Time Range" setting

**What you expected to happen**:
Only annotations within current timerange should be shown

**How to reproduce it (as minimally and precisely as possible)**:
1. Create some annotation
2. Observe it in annolist panel
2. Change current timerange several days ago, for example - to yesterday
3. The annotation still shown!!!

**Anything else we need to know?**:
On below image:
1. Within Time Range is ON
2. Current Time Range  is 2020-10-07 00:00:00 to 2020-10-07 23:59:59 (Oct 7)
3. All annotations are created Oct-8 and Oct-11, but still shown!!!

![image](https://user-images.githubusercontent.com/27145550/95680206-7cd75a00-0be0-11eb-94e2-6ba451793e70.png)

**Environment**:
- Grafana version:  6.1.3
- Data source type & version: Grafana
- OS Grafana is installed on: Linux
- User OS & Browser: Mac/Chrome
- Grafana plugins: Annotations List (alpha)
- Others:

**Comment by aknuds1** [comment]
I can reproduce the bug.
