### ISSUE TITLE
Plugins compatibility breaks with renamed methods in kbn utility

### ISSUE THREAD

**Issue by diafour** [grafana/grafana#28175]
**What happened**: 7.2.0 and 7.2.1 breaks compatibility with plugins that use `kbn` utility. A call to `kbn.interval_to_ms` might prevent the execution of `issueQuery` and the plugin got no data without any messages.
Some methods in the `kbn` utility was renamed during refactoring in https://github.com/grafana/grafana/pull/26907. This breaks compatibility with third-party plugins. The later PR https://github.com/grafana/grafana/pull/27347 put `@deprecated` on these _renamed_ methods. 

**What you expected to happen**: deprecate original methods, not renamed ones.

**How to reproduce it (as minimally and precisely as possible)**: extend `MetricsPanelCtrl` and call `kbn.interval_to_ms` in overridden `updateTimeRange`. The call to undefined method stops execution without any message and prevents a call to `issueQueries`.

**Anything else we need to know?**:  The workaround for other plugin authors:
```
    // Grafana 7.2 workaround
    if (typeof kbn["intervalToMs"] === "function") {
       kbn.interval_to_ms = kbn.intervalToMs;
    }
```

**Environment**:
- Grafana version: 7.2.0, 7.2.1
- Data source type & version: Prometheus
- OS Grafana is installed on: docker image grafana/grafana:7.2.1
- User OS & Browser: Chrome
- Grafana plugins: flant-statusmap-panel 0.3.2
- Others:

**Comment by torkelo** [comment]
Hi, sorry about this. Would have been good with some backward compatible function wrappers for the old names
