### ISSUE TITLE
Cannot use MySQL through Unix socket

### ISSUE THREAD

**Issue by X-dark** [grafana/grafana#2818]
It seems there is no way to configure a MySQL backend with a connection through a Unix socket instead of a TCP one. The driver supports it.

**Comment by X-dark** [comment]
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/sqlstore.go#L116 enforces tcp.

**Comment by jbergstroem** [comment]
Could we perhaps backpor this to 2.x as well?

**Comment by bergquist** [comment]
@jbergstroem 3.0 rc1 will be released any day now. I rather see that people move forward then keeping different versions alive in such young project.

**Comment by jbergstroem** [comment]
@bergquist gotcha. I personally wouldn't deploy rc's or betas in an environment where I rely on it being available which is why I suggested merging into 2.x.
