### ISSUE TITLE
Elasticsearch Query Bug Bad!!!

### ISSUE THREAD

**Issue by herozabbix** [grafana/grafana#28186]
## the  follow is good:
![image](https://user-images.githubusercontent.com/56722758/95724676-3b5eb180-0ca9-11eb-83f2-9d67fa61c656.png)

## the follow is bad:
- Do not use >、<、>=、<= in Query
![image](https://user-images.githubusercontent.com/56722758/95724777-59c4ad00-0ca9-11eb-84e6-41952eecb7e6.png)

**Comment by peterholmberg** [comment]
What are you trying to show here? If this is some bug please follow the bug template with steps to reproduce.

**Comment by herozabbix** [comment]
> What are you trying to show here? If this is some bug please follow the bug template with steps to reproduce.

Grafana gets ES data. Using mathematics in query does not work. I can only use Field: Value to query, Using >, <, >= none of these works

**Comment by peterholmberg** [comment]
Again, please follow the bug issue template and provide minimum steps to reproduce.

**Comment by herozabbix** [comment]
> Again, please follow the bug issue template and provide minimum steps to reproduce.

 Look this new issue: [https://github.com/grafana/grafana/issues/28189](url)
