### ISSUE TITLE
Not able to login to Grafana

### ISSUE THREAD

**Issue by adityaakella123** [grafana/grafana#28187]
What happened?
We are not able to login to Grafana despite necessary services started for Grafana and the error is as below when tried to login using http://hostname:3000/  as mentioned. We have added port 3000 to inbound rules also. Despite following some links from github like 
“https://github.com/grafana/grafana/issues/2578” on troubleshooting the issue, we couldn’t find any fix for this.

What was expected to happen?
Successful login to grafana using http://hostname:3000/

Current version we are using : 7.1.0
1. Installed grafana
2. Started grafana as service and successfully running
3. Not able to login using using http://hostname:3000 and showing error as ERR_TOO_MANY_REDIRECTS

Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):
Grafana - 7.1.0
OS: Windows 10
environment : 64 bit

Configuration information:
32 GB RAM
500 GB hard disk

Thanks in advance for help

![grafana error](https://user-images.githubusercontent.com/65285851/95725101-d39e6b80-0c94-11eb-9b5c-4fd25442c721.jpg)

**Comment by peterholmberg** [comment]
Which browser and version are you using?

**Comment by adityaakella123** [comment]
Hi,

I am using google chrome and version is 86.0.4240.75. Same issue even with Microsoft edge as well and its version is 85.0.564.70

Please let me know if this helps

Regards,
Aditya

**Comment by torkelo** [comment]
Make sure your root_url setting matches the public URL you want to access grafana with in your browser.

**Comment by torkelo** [comment]
Also could be related to similar issues in : https://github.com/grafana/grafana/issues/27802
