### ISSUE TITLE
Elasticsearch Query Bug Bad!!

### ISSUE THREAD

**Issue by herozabbix** [grafana/grafana#28189]
**What happened**:
>Grafana gets ES data. Using mathematics in query does not work. I can only use Field: Value to query, Using >, <, >= none of these works

**What you expected to happen**:
>According to the given including mathematical operations >, <, >=...The query returns the correct data

**How to reproduce it (as minimally and precisely as possible)**:
1. create elastarch datasource
2. create dashboard
3. use Singlestat chart
4. use Query field > num 

**Anything else we need to know?**:
- The follow is valid.
![image](https://user-images.githubusercontent.com/56722758/95728661-597ae080-0cae-11eb-825b-486907a9d070.png)

- The follow is invalid.
![image](https://user-images.githubusercontent.com/56722758/95728696-6566a280-0cae-11eb-8315-6ec274a6d7f8.png)

## How should I do?

**Environment**:
- Grafana version:
> v6.7.2
- Data source type & version:
> elasticsearch 7.4.2
- OS Grafana is installed on:
> kubernetes 1.16
- User OS & Browser:
> win & chrome
- Grafana plugins:
> Singlestat
- Others:

**Comment by torkelo** [comment]
That is not proper Lucene syntax for filtering on numeric values.

Check Elasticsearch query documentation for lucene query syntax help

**Comment by herozabbix** [comment]
> That is not proper Lucene syntax for filtering on numeric values.
> 
> Check Elasticsearch query documentation for lucene query syntax help

Can you give me an example? Thank you very much

**Comment by torkelo** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/7.9/query-dsl-query-string-query.html#query-string-syntax
