### ISSUE TITLE
React allowDetails props in log panel is confusing

### ISSUE THREAD

**Issue by PPACI** [grafana/grafana#28188]
Hi Grafana.

**What happened**:

I was looking on what could be done to implement #22271.

After digging, I found that getting the "show detail" button on log panel is conditionned to the `allowDetails` props in the components. 

It appears that setting `allowDetails`  to true in props doesn't allow details.

**What you expected to happen**:

Be able to see details in log panel.

**How to reproduce it (as minimally and precisely as possible)**:

Use the default code.

**Anything else we need to know?**:

https://github.com/grafana/grafana/blob/4a523c3248941207e7914de168c61f79bd9ff7d2/public/app/plugins/panel/logs/LogsPanel.tsx#L35

The button will appear when set to `false`.

This come from the fact that the button will only appear if `!allowDetails` as shown in the following code.

https://github.com/grafana/grafana/blob/e962f02fbc48623ac54d324211edb9c18412cf73/packages/grafana-ui/src/components/Logs/LogRow.tsx#L174

So I have multiple questions regarding that.

1. Could we have a quickfix for #22271 by setting this props to false ? I'm aware that parsed Field filtering will not work without passing event handler in props. Maybe we could hide them if the event handler is null ?
2. could this props be renamed to `hideDetails` ou change to condition to `allowDetails` (removing the !)

**Comment by PPACI** [comment]
I've edited my issue to conform to the template.

**Comment by torkelo** [comment]
Can you ask this on https://github.com/grafana/grafana/issues/22271 or in a PR ?
