### ISSUE TITLE
401 on admin API endpoints even when correct password specified

### ISSUE THREAD

**Issue by redbaron4** [grafana/grafana#28191]
**What happened**: Trying to access HTTP Admin API gives me `401 Unauthorized` in 7.1.3. My password is correct (I have double checked)

```
# curl -k -XGET -H "Content-Type: application/json" https://admin:grafana123@10.44.0.254/grafana/api/admin/settings
{"message":"Unauthorized"}
```

**What you expected to happen**: HTTP Admin API should be accessible using Basic Auth as shown in [docs](https://grafana.com/docs/grafana/latest/http_api/admin/)

**How to reproduce it (as minimally and precisely as possible)**: Try to access admin API using command line and curl

**Anything else we need to know?**: I had trouble logging in after upgrading to 7x from 6x and so changed my password using admin cli. After issue was resolved (involved clearing cookies), I changed my password back to old password

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Graphite
- OS Grafana is installed on: Scientific Linux - 7.6
- User OS & Browser: Scientific Linux & cURL
- Grafana plugins: None
- Others:

**Comment by torkelo** [comment]
Maybe something with your setup or proxy? Just tried that same curl command and it works for me. 

Does other api calls work with basic auth? (make sure it's not disabled in config)

**Comment by redbaron4** [comment]
Indeed! My Nginx (reverse proxy ahead of grafana) config had been changed to strip Auth header. I must have done it when debuging the old login issue. Stopped stripping the headers and now everything is working correctly.

Thanks @torkelo !
