### ISSUE TITLE
grafana combina cmdb and second-times caculation expression

### ISSUE THREAD

**Issue by tristan-tsl** [grafana/grafana#28207]
**What would you like to be added**:
compose the cmdb to manage the so many confusion dashboard
second-times caculation expression

**Why is this needed**:
cmdb refactor our confusion manage way, make multi-meta system clear, and after compose the command system, it will be more interesting
second-times is very useful in my work, also it very interesting

**Comment by tristan-tsl** [comment]
i think the system is just be component by data and command, data' operation and status, the status have things and events, in other words is metrics and tracing, the cmdb is the key in use

**Comment by peterholmberg** [comment]
I don't understand what you're requesting here?

**Comment by tristan-tsl** [comment]
oh, i have lost of dashboard, but it dispaly not well, maybe i think grafana could deal with it by use cmdb
