### ISSUE TITLE
Grafana-UI: Add Card component

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#28209]
**What would you like to be added**:
Implement the [designs](https://www.figma.com/file/ITCsaXtsANM17oRtU6GQS9/Component-Playground?node-id=712%3A0) for Card/List component and add it to grafana-ui.

**Comment by torkelo** [comment]
@Clarity-89 for reference here is my last failed attempt at this: https://github.com/grafana/grafana/blob/resource-card/packages/grafana-ui/src/components/ResourceCard/ResourceCard.tsx 

Mostly failed due to a UI design that I felt happy with for all use cases, and a struggled a bit making the component code feel good as well

**Comment by Clarity-89** [comment]
> @Clarity-89 for reference here is my last failed attempt at this: https://github.com/grafana/grafana/blob/resource-card/packages/grafana-ui/src/components/ResourceCard/ResourceCard.tsx
> 
> Mostly failed due to a UI design that I felt happy with for all use cases, and a struggled a bit making the component code feel good as well

Thanks for the link, this looks pretty similar to [what I've got so far](https://github.com/grafana/grafana/pull/28216). In general I'd like the Card not to care much about it's actions or images, but would be able to align them as needed and provide some wrapper styles that would make sure content looks good, kinda similar to [how Ant Design does it](https://ant.design/components/card/#components-card-demo-meta). If we limit the use cases to the ones in designs, I think this is possible to achieve. I'd also like to have the wrapper html tag to be customisable so the card can be used as `li` if needed. What I'm currently not sure about is how to handle the case where the card itself should be an `a` with href or a div with `onClick` as that will probably require an extra nested element. Also anchor tags are often wrapped inside `li`s, so have to account for that as well.
