### ISSUE TITLE
Documentation: should root_url include trailing slash?

### ISSUE THREAD

**Issue by candlerb** [grafana/grafana#28200]
## Documentation issue ##

At https://grafana.com/docs/grafana/latest/administration/configuration/#serve_from_sub_path it shows:

```
root_url = http://localhost:3000/grafana
```

At https://grafana.com/tutorials/run-grafana-behind-a-proxy/#1 it shows:

```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
```

It's unclear whether root_url should include the trailing slash or not.  Please can these be made consistent?

**Comment by torkelo** [comment]
It does not matter, grafana will handle both the same way

**Comment by candlerb** [comment]
In that case, can the documentation say this?
