### ISSUE TITLE
Grafana Simple Json Datasource Plugin have no Keycloak tokens 

### ISSUE THREAD

**Issue by pargmayticer** [grafana/grafana#28202]
I ve tried serval thing. But the Simple Json Datasource Plugin is not be able to send/or get the Token from KeyCloak.
Even if I login in Grafana with KeyCloak. The Request says me it set cookies which saves the Keycloak tokens I need.
I can login with KeyCloak without Problems.
But they are not here. Further more I ve enable in the Simple Json Datasource Plugin the Forward Oauth Identity.
The Grafana is running in Docker Container, the Keycloak instance is running on a Server.

**Comment by peterholmberg** [comment]
If you think this is an issue with the simple json datasource I'd suggest opening an issue in https://github.com/grafana/simple-json-datasource

**Comment by torkelo** [comment]
Grafana does not support forwarding keycloak tokens
