### ISSUE TITLE
Lazy variables

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#28212]
**What would you like to be added**:

When making dashboards it is useful to have several `Type=query` variables which can help you filter the data shown on the dashboard.

However the variables generation can take a bit of time if the time range selected is large.

In my case, most variables are used with a default custom "All" value (generally a `.*` regexp) and only changed when investigating.

So I think it would be great if those variables options could be populated only when the user click on the list arrow.

**Why is this needed**:

it would reduced dashboard loading times which grow exponentially as the time range widen.

Consequently it would reduce pressure put on the datasource(s).

**Comment by peterholmberg** [comment]
Lazy loading variables is unfortunately not viable when you have repeating panels and/or rows dependent on variables.

**Comment by sylr** [comment]
Then maybe forbid repeating over variables marked as lazy.
