### ISSUE TITLE
Grafana API access denied issue

### ISSUE THREAD

**Issue by m4ce** [grafana/grafana#2821]
Hi,

I keep receiving 'Access denied' when targeting the following API endpoints using an API key with admin rights.

/api/orgs
/api/users
/api/admin/settings

Is this the expected behavior? I'm using Grafana 2.1.3.

Thanks,
Matteo

**Comment by torkelo** [comment]
They require grafana admin permissions (not the same as a single organization admin), right now api keys can't be given admin rights for the whole grafana install (so you can't delete users and orgs using api key) you can use basic auth with a user with grafana admin rights , then you can use those api actiona
