### ISSUE TITLE
Templating: No error when Datasource does not exists on dashboard load

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#28215]
I had a dashboard with variable loading data from Postgres datasource. Variable update method is set to on Dashboard load.

I renamed the datasource from `A` to `B` but variable still tries to load data from datasource `A` (that does not exists anymore).

![image](https://user-images.githubusercontent.com/327717/95855070-22f9a000-0d58-11eb-8ebe-302b4d82df9a.png)

**However, no error is shown.**

----------------

It is necessary to access dashboard through url with variables included

https://localhost/grafana/d/hash/dbname?var-name=a

Accessing this displays the error properly https://localhost/grafana/d/hash/dbname

![image](https://user-images.githubusercontent.com/327717/95855248-5fc59700-0d58-11eb-9eda-b8cd99e17028.png)

v7.3 dev

**Comment by simPod** [comment]
Well the issue lays probably somewhere else, even though the datasource name is now fixed, the dashboard is still stuck on loading services. Will investigate.

**Comment by simPod** [comment]
The variable `B` loads data from Postgres and in the query uses value from variable `A`.

That stucks the dashboard load. I have to either 

omit `A` from the query  
or change `B` not to use the existing variable.

**Comment by simPod** [comment]
I suspect this https://github.com/grafana/grafana/pull/27917

**Comment by simPod** [comment]
Dependency variable of type Constant have constantly state NotStarted

**Comment by simPod** [comment]
Can confirm the issue is not in add777ad401554417c2f6beec33d66b2ed038c94 which i just before #27917 was merged.

**Comment by hugohaggmark** [comment]
@simPod can you please share you dashboard.json or describe the variables involved and their types and dependencies?

**Comment by simPod** [comment]
@hugohaggmark 

Variable `a`: Constant, value `Foo`
Variable `b`: Query (Postgres datasource), query `SELECT $a`

Changing query of `b`

```diff
- SELECT $a
+ SELECT 1
```

allows dashboard to load

----------------

I'll try to get the json eventually

**Comment by hugohaggmark** [comment]
@simPod thank you, I think I can repro it now

**Comment by hugohaggmark** [comment]
I think I got this now, will have a PR up soon. Thank you again @simPod
