### ISSUE TITLE
Table Panel horizontal scrollbar unusable when table is at bottom of dashboard

### ISSUE THREAD

**Issue by itldo** [grafana/grafana#28228]
I'm posting an issue that I have encountered,
but was initially described by someone else at

  https://community.grafana.com/t/horizontal-panel-scroll-bar-mixed-with-dashboards-scroll-bar/31237

I searched for an existing issue, but found none.

**What happened**:
The horizontal scrollbar of a Table panel is unusable when the Table
is at the bottom of the dashboard. The scrollbar appears but does not respond.
A workaround is to place a dummy Text panel at the bottom of a dashboard.

**What you expected to happen**:
I expected to be able to use the Table's horizontal scrollbar, but can't.

**How to reproduce it (as minimally and precisely as possible)**:
Place a Table wider than its view port as the bottom-most Panel on a dashboard,
Then try to scroll it horizontally.

**Environment**:
- Grafana version: 7.0.1 and later to at least 7.2.1
- OS Grafana is installed on: Debian 7
- User OS & Browser: Wihdows 10, Firefox 71.0 (64-bit), Chrome Version 86.0.4240.75

**Comment by torkelo** [comment]
thanks for reporting this! fixed https://github.com/grafana/grafana/pull/28250

**Comment by itldo** [comment]
Thank you!
