### ISSUE TITLE
Add EL7 RPMs to correct Repo Path

### ISSUE THREAD

**Issue by kemra102** [grafana/grafana#2823]
Can the Yum repo the project provides be updated to explicitly have a path to EL7 binaries?

e.g. currently only `https://packagecloud.io/grafana/stable/el/6/$basearch` exists so automation tools like Chef/Puppet that calculate Yum repo paths based on Yum variables such as `releasever` do not work.

It would be good to have a `https://packagecloud.io/grafana/stable/el/7/$basearch` as well for these purposes.

**Comment by torkelo** [comment]
Sure, now that packagecloud has changed their pricing this can be done. Before this was not possible as it was super expensive if each release required duplicate packages uploaded for each distro and version.

**Comment by torkelo** [comment]
Will remember to do this for next grafana release
