### ISSUE TITLE
Samsung Tizen throwing Uncaught ReferenceError: Proxy is not defined

### ISSUE THREAD

**Issue by freman** [grafana/grafana#28238]
**What happened**:

Pages render fine now, a blank dashboard with nothing on it renders perfectly as a blank dashboard.
However if we have any panels on the board we get the error Uncaught ReferenceError: Proxy is not defined

![image](https://user-images.githubusercontent.com/506680/95931002-66f9ad00-0e0b-11eb-91f8-b0e32313702d.png)

**What you expected to happen**:

Page to render with a panel

**How to reproduce it (as minimally and precisely as possible)**:

I'm afraid this appears to be another one of those samsung tizen issues, so I'm open to suggestions on being precise but it's basically just launch grafana on any page.

**Environment**:
- Grafana version: Grafana v7.2.1 (72a6c64532)
- User OS & Browser: Samsung Tizen OS (TIZEN-3.0-TRUNK2017-KantM-RELEASE_20191025.1)

**Comment by torkelo** [comment]
We sadly do not support this old browser, Grafana needs Proxy support

**Comment by freman** [comment]
When did this change? It was working until recently.

**Comment by freman** [comment]
Is this an option?

https://github.com/GoogleChrome/proxy-polyfill

**Comment by zoltanbedi** [comment]
I have a branch with a proxy polyfill in it can you check if that is working for you? https://github.com/grafana/grafana/tree/zoltan/proxy-polyfill
