### ISSUE TITLE
Problem displaying strings which are very large numbers.

### ISSUE THREAD

**Issue by ShubhamKJha** [grafana/grafana#28239]
**What happened**:
Grafana is converting all numeric strings to Numbers and losing a few digits at the end.

**What you expected to happen**:
The intended use of the field is as a string. There should have been an option to keep it like that.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version:
- OS Grafana is installed on: Docker
- User OS & Browser: Windows & Chrome
- Grafana plugins:
- Others:

The numbers being displayed
![image](https://user-images.githubusercontent.com/34163329/95936175-9d76fe00-0df2-11eb-860e-e0fef5a4b5d7.png)

The numbers as in JSON view
![image](https://user-images.githubusercontent.com/34163329/95936210-b089ce00-0df2-11eb-8120-2c05cbce52e6.png)

**Comment by torkelo** [comment]
In Grafana 7.2 there is a new "String" unit that you can use in an override to disable Grafana's tendency to parse strings to numbers
