### ISSUE TITLE
Fixes for shorten url

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#28248]
Short url issues that should be tabled before stable release: 
- [x] The last_seen_at column is currently not updated when visiting a short link - I would suggest creating an issue for this to resolve between beta and stable release? Having this updated would make it easier later to create a cleanup up deleting short urls not visited/used for example.

- [x] The UX for creating a short URL when sharing a dashboard seems to invite to creating a lot of short URLs - clicking on the different switches generates a new one each time.

> ⬆️  I have opened this discussion in UX feedback session and generally there was a consensus from devs that this shouldn't be problem and other UX issues should be rather tackled - where to place to toggle/button. 

- [x] Unify explore and dashboard solution

- [ ] I'm a bit concern with "reusing short urls for paths we've already seen -- see above; creating an index for page => uid lookups would probably exacerbate our storage consumption problem more than it would help". 

- [ ] From a security perspective we want to make sure that no malicious URL's/paths can be provided when creating a short URL and/or that could lead to redirecting to somewhere outside of Grafana root_url.

**Comment by aknuds1** [comment]
Hope you don't mind I set the milestone @ivanahuckova.

**Comment by johnatannvmd** [comment]
Before generation:
![image](https://user-images.githubusercontent.com/4918448/96156944-5a17af00-0f1a-11eb-92de-4d2551bb567d.png)

After generation:
![image](https://user-images.githubusercontent.com/4918448/96156996-6ac82500-0f1a-11eb-8e37-4cc3b4cfd0a6.png)

**Comment by aknuds1** [comment]
> Before generation:
> ![image](https://user-images.githubusercontent.com/4918448/96156944-5a17af00-0f1a-11eb-92de-4d2551bb567d.png)
> 
> After generation:
> ![image](https://user-images.githubusercontent.com/4918448/96156996-6ac82500-0f1a-11eb-8e37-4cc3b4cfd0a6.png)
> 
> Shortlink from the explore same without "/"

@ivanahuckova I'm not sure if the above is a bug report or not?

**Comment by johnatannvmd** [comment]
We use reverse proxy before Grafanas

```
[server]
# Protocol (http, https, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 0.0.0.0

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = grafana-beta.<redacted>

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://grafana-beta.<redacted>
```

**Comment by johnatannvmd** [comment]
> @ivanahuckova I'm not sure if the above is a bug report or not?

Oh, did not saw you reply. Should I make a separate issue?

**Comment by ivanahuckova** [comment]
@johnatannvmd yes please, could you create an issue and we'll fix it asap. Thanks for sharing this with us!!!

**Comment by johnatannvmd** [comment]
> @johnatannvmd yes please, could you create an issue and we'll fix it asap. Thanks for sharing this with us!!!

Should I remove my messages for clean history? :)

**Comment by aknuds1** [comment]
@johnatannvmd I would think it doesn't matter.

**Comment by ivanahuckova** [comment]
@aknuds1 @marefr regarding:

>The last_seen_at column is currently not updated when visiting a short link - I would suggest creating an issue for this to resolve between beta and stable release? Having this updated would make it easier later to create a cleanup up deleting short urls not visited/used for example.

I was wondering, if anyone has time for that or if I should tackle this. 

Also regarding 

> I'm a bit concern with "reusing short urls for paths we've already seen -- see above; creating an index for page => uid lookups would probably exacerbate our storage consumption problem more than it would help".

> From a security perspective we want to make sure that no malicious URL's/paths can be provided when creating a short URL and/or that could lead to redirecting to somewhere outside of Grafana root_url.

Not sure what should be the next steps.

**Comment by aknuds1** [comment]
Yeah I'm not sure @ivanahuckova, maybe @marefr would be the best person to answer this? I feel as if I lack insight into this part of the system.

**Comment by marefr** [comment]
@ivanahuckova @aknuds1 Looking into it

**Comment by marefr** [comment]
@ivanahuckova as a first step I'm looking into updating the last seen at on visit. Will open a PR soon

**Comment by marefr** [comment]
Created a separate issue for clean up of non-visited short URL's #28594. Also did some additional testing yesterday so will close this issue.
