### ISSUE TITLE
add "save and back to dashboard" and "discard changes and back to dashboard" buttons in the edit view

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2824]
Sometimes, I go into the edit view of the graph, and make some changes for more infos depend on the exist graph in the dashboard, but I don't want to save the change to the dashboard or change the graph when back to dashboard. But it will be fine adding a "discard changes and back to dashboard" button.

**Comment by torkelo** [comment]
good idea, 

https://github.com/grafana/grafana/issues/1081
