### ISSUE TITLE
add feature: Drilldown / detail link should support each lines of the graph

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2825]
grafana had support drilldown / detail link in the graph general tab so far which is very easy jump to another dashboard. I have many general and details dashboards, and want to click one of legends in a general dashboard (such as cluster infos) and jump to the detail dashboard (such as details of a machine or a table) for more details with hostname, tablename or any other parameters of the tag values. It will be more easy to find the questions.

**Comment by torkelo** [comment]
good idea! 

Will close as there is already an issue for this, https://github.com/grafana/grafana/issues/1232
