### ISSUE TITLE
Enhance "Transformations / Add field from calculation" to support Raw Data Metric for Elasticsearch

### ISSUE THREAD

**Issue by scroodj** [grafana/grafana#28255]
Grafana v7.2.0
**What would you like to be added**:
I would like to have an ability to add a new field  based on operation between Used and Total in my case
![image](https://user-images.githubusercontent.com/6392717/95982185-193b6f80-0e20-11eb-84eb-ba28c81d2fdc.png)

but if i use Raw Data Metric "Operation" field for "Add field from calculation" is empty.
![image](https://user-images.githubusercontent.com/6392717/95982734-c44c2900-0e20-11eb-93df-f175dc9f3ae7.png)
I wish to see there a list of all fields from the document or certain number of fields defined in previous transformation (e.g. Filter by name) ,
**Why is this needed**:
It's very common practice for us to use Raw Data to display Elasticsearch documents in a Table Panel, especially  with those bunch of new Transformation features in Grafana v7.x.

**Comment by Dutchy-** [comment]
I encountered yesterday that this was not possible. I even wrote a forum topic about it:
https://community.grafana.com/t/add-field-from-calculation-table-panel-es-datasource/39804

It is very counter-intuitive that this does not work, I hope this will be supported in a future release.

**Comment by torkelo** [comment]
Troubleshooted this and found it related to a bug in Elasticsearch raw data parsing: https://github.com/grafana/grafana/issues/29431
