### ISSUE TITLE
Cannot get the contents of Variables parameter after upgrading to 7.2.x version

### ISSUE THREAD

**Issue by Enternalcode** [grafana/grafana#28252]
Hi!
In the 6.5.x version, I can get custom Variables parameters from the scopedVars requested by the page, but after upgrading to 7.2.x I found that these variables in the scopedVars field disappeared.
![image](https://user-images.githubusercontent.com/38741725/95977247-389bc200-0e4b-11eb-8650-f7dc675f0068.png)

![image](https://user-images.githubusercontent.com/38741725/95977292-48b3a180-0e4b-11eb-9ffd-c352b128925f.png)

**Comment by peterholmberg** [comment]
Could you provide some minimum steps to reproduce as per the bug issue template please.

**Comment by Enternalcode** [comment]
Thank you for your replay.
In a brief overview, the function I need to implement now is: 
I use the simple json plugin in grafana, send some parameters to the server interface through the simple json plugin, and return the data to grafana after the server processes.

The problem I encountered:
1.In the 6.5 version of grafana, grafana will put those parameters of the drop-down list in the scopedVars field, and then send it to the server by request.
2.But when I upgraded the grafana version to 7.2.1, grafana no longer put thost parameters in the drop-down list in the scopedVars field, and other fields in the request did not include these parameters. So I cannot get these parameters in the background interface.

Do you have any ideas to get these parameters? Thanks in advance.

**Comment by Enternalcode** [comment]
The problem was solved after upgrading the simple json plugin.
