### ISSUE TITLE
Unable to use any visualization options (except "Table" and "Logs")

### ISSUE THREAD

**Issue by Darktortue** [grafana/grafana#28259]
**What happened**: I can't use any visualization options except for "Table" and "Logs"

**What you expected to happen**: Being able to use any visualization options (i mostly want to use graph)

**How to reproduce it (as minimally and precisely as possible)**: Go to your Dashboard, edit a panel, select different visualization options, check the error

**Anything else we need to know?**: Grafana gets its logs from Loki (data source) which gets its logs from Promtail.

**Environment**:
- Grafana version: 7.2.1
- Data source type & version: Loki
- OS Grafana is installed on: Debian 9.13
- User OS & Browser: Ubuntu 20.04 & Firefox 81
- Grafana plugins:
- Others: The logs that i need to display are in json-format

![Peek 14-10-2020 15-51](https://user-images.githubusercontent.com/11302315/95999143-e7cd9e80-0e35-11eb-9c55-1e33ce8becf3.gif)

**Comment by torkelo** [comment]
For the stat panel you have to select a field, it defaults to "numeric fields" and there no numeric fields in a log line. 

For the Graph you need to write a time series query

**Comment by peterholmberg** [comment]
This is not a bug per se. I believe this is because we can not graph the log data at the moment. We'd need to convert the log data to a DataFrame which the graph and other panels can process.

**Comment by torkelo** [comment]
just wrap your query in a rate(yourquery[5m]) function you will be able to use the graph
