### ISSUE TITLE
Panel Alerts sit above Dashboard Search

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#28266]
**What happened**:
Whilst browsing through dashboards - panels without installed plugins render their error alerts above the dashboard search. They have no way of being closed and obscure text and prevent clicking to switch dashboard.

![Kapture 2020-10-14 at 16 42 11](https://user-images.githubusercontent.com/73201/96005884-3468a800-0e3d-11eb-968b-c4b611174091.gif)

**What you expected to happen**:
For the alerts to be hidden by the dashboard search so they don't prevent reading dashboard names or selecting a dashboard to view.

**How to reproduce it (as minimally and precisely as possible)**:
- Open a dashboard with a panel that uses a plugin that isn't installed.
- Open the dashboard search

**Anything else we need to know?**:
It looks like the [grafana-ui/alert](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Alert/Alert.tsx#L96-L98) component has a z-index set which is higher than the dashboard search z-index. A solution could be that the call site dictates the layer an alert lives on rather than this css property living inside this component?

z-indexes can become unwieldy over time. In the past I've tackled scaling z-indexes across applications by using an array of strings and retrieving a strings index for use as the value. This approach allows a design system to define names for each layer, the code can be explicit in its usage, and z-index values are kept as small/low as possible. It also means that if new layers are introduced they can be slotted in where needed and the existing indexes will update as necessary.

I don't know if this idea is something that could help us keep check of our z-indexes in the future but thought I'd throw it out there for consideration.

**Environment**:
- Grafana version: Grafana v7.3.0-pre (3fed829b8b)
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Mac OSX Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by maknik** [comment]
@torkelo Can I take this issue?
