### ISSUE TITLE
feat: Elasticsearch templating: add term filter to all queries when selecting a value

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#2826]
Another cool feature for the ES templating feature would be an option that grafana automatically includes a term filter to all requests when selecting a value. For example, if you have a template variable `host` (like `{"find": "terms", "field": "host"}`), when you select `server1`, grafana adds a `"term": {"host": "server1"}` filter to all queries. When All is selected, no filter has to be applied (a `match_all": {}` filter would be fine too).

**Comment by torkelo** [comment]
You could do this with the license query that you have on all es queries? modifying the query like this does not fit with how the templating system works (string substitution)

**Comment by felixbarny** [comment]
What do you mean by 'license query'?

**Comment by felixbarny** [comment]
Ah, probably you mean lucene. I could to that but I'd have to repeat that same set of variables in all dashboards and all graphs over and over again.

**Comment by torkelo** [comment]
I do not think what this issue proposes is feasible. You might not want it added to all queries etc. So having you specify which queries by having for example: "host:$host" in the lucene query for those graphs you want to be affected when you specify a template variable makes sense to me
