### ISSUE TITLE
Cloudwatch datasource missing HTTP API Gateway metrics

### ISSUE THREAD

**Issue by karlatkinson** [grafana/grafana#28263]
**What would you like to be added**:
I'm not sure why AWS have done this but HTTP API Gateway metrics are named slightly differently it seems than the REST ones.

REST: https://docs.aws.amazon.com/apigateway/latest/developerguide/api-gateway-metrics-and-dimensions.html
HTTP: https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-metrics.html

Instead of `4xxError` its `4xx` and instead of `5xxError` its `5xx`
Dimensions use `ApiId` instead of `ApiName`.

**Why is this needed**:
To be able to monitor both the REST & HTTP API Gateways

**Comment by aknuds1** [comment]
Can you please clarify what you want to be added? I can't really grok your request as it's currently written.

**Comment by karlatkinson** [comment]
@aknuds1 
There is the REST & HTTP type API gateway in AWS. These both share the same cloudwatch metrics namespace. 
If you compare the two links I've posted, the metric names are slightly different. ie. REST uses `4XXError` where as HTTP uses `4xx`.

Looks like the metrics you can choose in the dropdown in Grafana for an API Gateway are here? https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/metric_find_query.go#L47

Which works great for REST but means you can't use it for the HTTP metrics as for the example, `4xx` is not allowed as a choice.
I've no idea why AWS decided to use different names 
But think we need to add `4xx`, `5xx` & `DataProcessed` to the metric names.
`ApiId` & `Route` into the dimensions.

**Comment by aknuds1** [comment]
Could you make a PR adding the metrics you're suggesting? I'm not sure how this would work technically based on the AWS docs you provided.

**Comment by karlatkinson** [comment]
@aknuds1 no problem, have created a PR.
