### ISSUE TITLE
Docs feedback: /developers/plugins/metadata.md

### ISSUE THREAD

**Issue by submersibletoaster** [grafana/grafana#28273]
Some descriptions of the behavior of `includes` in `plugin.json` would be really helpful. The examples in https://github.com/grafana/simple-app-plugin are interesting - but contain hardcoded paths. The simple-app config page seemed to be added to navigation without being included here at all.

The description column for each `includes` object property is a bit of a wasteland.

**Comment by peterholmberg** [comment]
Not sure I follow, which `includes` are you referring to here? Is this an issue with the simple-app-plugin or with Grafana?

**Comment by submersibletoaster** [comment]
Apologies - that was very unclear. I'm talking about the definitions of metadata keys in plugin.json described at https://grafana.com/docs/grafana/latest/developers/plugins/metadata/
