### ISSUE TITLE
Azure Insights Analytics, unsupported analytics column type decimal

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#28278]
**What happened**:
When  using the `todecimal()` function in Insights Analytics queries, you get this error: 
`unsupported analytics column type decimal` 
![image](https://user-images.githubusercontent.com/49911675/96089299-385a0000-0ef9-11eb-8b3e-4a7aaed59e8d.png)

**What you expected to happen**:
Getting a result to the query. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a new query using Azure Monitor data source, and Insights Analytics service. 
The query should return a number, use `todecimal()` on that number

**Anything else we need to know?**:
Replacing `todecimal()` by `toreal()` works. 

**Environment**:
- Grafana version: 7.2.1
- Data source type & version: Azure Monitor
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
Same as https://github.com/grafana/azure-data-explorer-datasource/pull/170
