### ISSUE TITLE
Issue in Alert setup for Heap utilization in Grafana

### ISSUE THREAD

**Issue by nehas247** [grafana/grafana#28281]
Hi All,

I am facing difficulties in Alert setup of Grafana. I have done the settings put the conditions and rule but I am not receiving emails. I tried testing the rule and got below error message. Please suggest some solutions.
![TestRuleError](https://user-images.githubusercontent.com/38423756/96106310-b36ee680-0ef8-11eb-89cb-494017c2ec64.PNG)

**Comment by kylebrandt** [comment]
Can you please provide some information such as the datasource, query, and grafana version?

**Comment by nehas247** [comment]
Datasource is Graphite, Grafana version is v6.3.
![Query1](https://user-images.githubusercontent.com/38423756/96226668-9f86bb80-0fb0-11eb-8ba0-907d1a4a732b.png)
![Query2](https://user-images.githubusercontent.com/38423756/96226675-a1507f00-0fb0-11eb-8e34-82b6efc02743.png)

3.

**Comment by torkelo** [comment]
The error means one of your graphite queries are returning an error

Read this guide on how to troubleshooting alerting issues: https://grafana.com/docs/grafana/latest/alerting/troubleshoot-alerts/
