### ISSUE TITLE
Logarithmic Y axis does not handle small values well

### ISSUE THREAD

**Issue by johanfforsberg** [grafana/grafana#2829]
I'm using Grafana to view data (from InfluxDB) about pressure for high vacuum, and these pressures are typically on the order ~1e-9 mBar. It's possible to set the axis to log10 which is usual for this type of data, and the plot looks OK but unfortunately neither the axis scale or the autoscaling works as expected. Looks like Grafana assumes values to be larger than or on the order of 1.

Grafana version: 2.1.3

**Comment by torkelo** [comment]
Not sure I understand your case. Can you show an screenshot? Have you tried setting Grid min/max? 

Log10 scale starts at 1

**Comment by johanfforsberg** [comment]
Thanks for replying,

I'm attaching a screenshot showing what I see. As visible from the popup, the values range around 1e-9-1e-8. The Y axis shows 0, while I would expect it to show ticks from e.g. 5e-10 to 1e-7 or something like that.

Setting Grid Max/Min manually (I did this for the screenshot) is the only way I've found to get the graph to look reasonable, leaving it at auto just makes it go from 0 to 10.

Not sure what you mean by "log10 scale starts at 1", technically a log10 scale could go arbitrarily close to zero. Perhaps the log10 scale in grafana does not expect non-integer values?

Using linear axes works as expected, it's just that vacuum pressure is more readable at a log scale since it can reach over many orders of magnitude.

![grafana_log_axis](https://cloud.githubusercontent.com/assets/1274600/10123131/6954a980-6530-11e5-9663-269e37cf453d.png)

**Comment by torkelo** [comment]
You are right for very small decimals it the y axis ticks are not optimial. 

I you find a better way to define the y axis ticks let me know. 
https://github.com/grafana/grafana/blob/master/public/app/panels/graph/graph.js#L417

**Comment by johanfforsberg** [comment]
Usually looks something like the linked image (ignoring the minor ticks):

http://inspirehep.net/record/1313183/files/P_vs_time.png

The scale just continues with negative exponents below 10^0. 

After a quick look at the code it seems like it hard-codes that the ticks should start at 1 (=10^0), but it should really start at axis.min. (Also, tick at 0 should not be needed in a log scale as it only contains values > 0)
