### ISSUE TITLE
Shorten url corrupted after generation

### ISSUE THREAD

**Issue by johnatannvmd** [grafana/grafana#28297]
Before generation:
![image](https://user-images.githubusercontent.com/4918448/96156944-5a17af00-0f1a-11eb-92de-4d2551bb567d.png)

After generation:
![image](https://user-images.githubusercontent.com/4918448/96156996-6ac82500-0f1a-11eb-8e37-4cc3b4cfd0a6.png)

Shortlink from the explore same without "/"

We use reverse proxy before several grafana servers

```
[server]
# Protocol (http, https, socket)
protocol = http

# The ip address to bind to, empty will bind to all interfaces
http_addr = 0.0.0.0

# The http port  to use
http_port = 3000

# The public facing domain name used to access grafana from a browser
domain = grafana-beta.<redacted>

# Redirect to correct domain if host header does not match domain
# Prevents DNS rebinding attacks
enforce_domain = true

# The full public facing url you use in browser, used for redirects and emails
# If you use reverse proxy and sub path specify full url (with sub path)
root_url = https://grafana-beta.<redacted>
```

**Comment by ivanahuckova** [comment]
@marefr @aknuds1 the `url := path.Join(setting.AppUrl, "goto", shortURL.Uid)` cuts of 1 `/` in `https://`. I am wondering, if we should just build url on frontend and remove it's creation from the backend, or should we just fix it on backend? Thoughts?

**Comment by aknuds1** [comment]
@ivanahuckova Ah, I think it should possibly be `fmt.Sprintf("%s/%s", setting.AppUrl, path.Join("goto", shortURL.Uid))`. I'll have to test.

**Comment by aknuds1** [comment]
@ivanahuckova Yep, can confirm.

**Comment by aknuds1** [comment]
Thanks! Have a [fix](https://github.com/grafana/grafana/pull/28300).
