### ISSUE TITLE
feat: Support multiple playlists

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2830]
Instead of having one single playlist, Grafana can have a list of playlists to choose from. Users can make their own playlists and manage them. Playlists will be common to all users like dashboards and they can have similar permissions like Editor/Admin/Viewer.

**Comment by torkelo** [comment]
Yes! would be great :) 

there is already an issue for this and a PR awaiting review and merge, so maybe in Grafana 3.0 (next release is 2.5, beta release soon)
