### ISSUE TITLE
Add select filter drop down does not listen to onpaste

### ISSUE THREAD

**Issue by blaues0cke** [grafana/grafana#28307]
**What happened**: When adding new select fields or aggregations to a select, the filter does not update when some text is pasted into the filter input. So when you paste "sum", the "sum" aggregation is not proposed. But when you type "sum", it is.

**What you expected to happen**: The "sum" aggregation should be proposed when pasting the string `sum`.

**How to reproduce it (as minimally and precisely as possible)**: Create a new query, press on the "+" in the select row, **paste** `sum`.

**Environment**:
- Grafana version: Grafana v7.2.1 (72a6c64532)
- OS Grafana is installed on: Version 86.0.4240.80 (Official Build) (x86_64)
- User OS & Browser: macOS 10.15.6 (19G73)

**Video**:

![Screen Recording 2020-10-15 at 22 56 31](https://user-images.githubusercontent.com/5159398/96185306-fac99700-0f39-11eb-9e19-6318a4198325.gif)

**Comment by nikasvan** [comment]
This seems to be fixed on latest master branch.

![Alt Text](https://p83.f1.n0.cdn.getcloudapp.com/items/qGuvqjnl/Screen%20Recording%202020-10-27%20at%2006.12.16%20PM.gif?source=viewer&v=14d8d113e099654333c7785698bf0171)
