### ISSUE TITLE
AWS CloudWatch with multiple queries are duplicating values in graph

### ISSUE THREAD

**Issue by MaikiGirardi** [grafana/grafana#28301]
When i use AWS Cloudwatch Data Source the values showed in graph become duplicated. I'm using multiple queries and filtering by instanceid. This issue was observed after upgrade to last update.

Above the example: 
![image](https://user-images.githubusercontent.com/20565056/96163376-33dd1980-0ef0-11eb-936b-7a96e7d1c1b3.png)

**Comment by peterholmberg** [comment]
Could you provide your response (clear it from sensitive data) from the panel inspector please?

**Comment by MaikiGirardi** [comment]
I don't know if it's all you need, but let's try

this is from this panel:

![image](https://user-images.githubusercontent.com/20565056/96306708-927cc300-0fd6-11eb-849d-1dc2de42a6ac.png)

![image](https://user-images.githubusercontent.com/20565056/96306775-b4764580-0fd6-11eb-8bac-6f20e7849498.png)

Here the files:

[Query.txt](https://github.com/grafana/grafana/files/5394216/Query.txt)
[DataFrameStructure.txt](https://github.com/grafana/grafana/files/5394217/DataFrameStructure.txt)

**Comment by aknuds1** [comment]
Please also rewrite the issue description using the standard bug template.

**Comment by MaikiGirardi** [comment]
**What happened**:

When i create a Panel and use 2 queries (A and B), grafana is duplicating the values for as much queries i add on screen.

**What you expected to happen**:

Only show the value one time, it's duplicated.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add new panel to a dashboard
2. Select AWS DS
3. Select: namespace=AWS/ECS, Metric Name=Network Out, Dimension/InstanceID= {your ID} and put a unique alias to see the difference.
4. Duplicate the query ou create a new one with the same parameters and you will see duplicating.

Here the GIF to see what's happening.
![BUGGrafana-7 3 0-beta1](https://user-images.githubusercontent.com/20565056/96468949-0dc2bc80-1203-11eb-9675-09c577ab1f00.gif)

**Anything else we need to know?**:

On version 7.2.1, this problem does not exists. 

```Important: For some reason i was on v7.3.0-beta1 after install a feel days ago from and didn't see this, so i downgraded the version and my application becomes normal again.```

**Environment**:
- Grafana version: 7.3.0-test
- Data source type & version: AWS CloudWatch(7.3.0-test)
- OS Grafana is installed on: Linux 5.4.17-2011.3.2.1.el8uek.x86_64 (Oracle Linux Server release 8.2)
- User OS & Browser: Windows 10 (Edge/Chrome)
- Grafana plugins: 
- Others:

**Comment by MartiUK** [comment]
![image](https://user-images.githubusercontent.com/1244603/97338608-823bd200-1879-11eb-9535-976e4a05f153.png)
Old visits and Open visits are separate queries to Cloudwatch, same region, same namespace, but different metrics.

**Comment by GregoryOrciuch** [comment]
Today I noticed same issue in my dashboards which use Cloudwatch, so started to look for the issue and here it is. I can help somehow but need some instruction on what needs to be provided.

**Comment by corycomer** [comment]
Also started having this issue. Same scenario, using CloudWatch as the datasource, multiple queries in the graph. One thing I noticed is that this did not start happening until I enabled the Legend on the graph. Beforehand, the graph was using 3 queries, and producing 1 line per query for a total of 3 lines. After enabling the Legend and setting it to the display on the right hand side, it is now using 3 queries and showing 3 lines for each query for a total of 9 lines, duplicating lines exactly as the other users above have shown.  

If you go in and edit the graph, and hide any 2 of the queries so only 1 query is visible, it will produce 1 line for that single query. If you unhide one of the other queries, so there are 2 queries visible, it produces 2 lines per query for a total of 4 lines now. I tried reverting the changes made by disabling the Legend, but the issue still persists. 

This is using Grafana v7.3.0 (bf8837f6f8)

**Comment by aknuds1** [comment]
I think I've reproduced this issue, by following the reproduction steps provided by @MaikiGirardi. I.e., I created two identical queries, with distinct aliases and I get 4 data points in the graph, 2 per query/alias. From my debugging, the duplication must happen in the front-end, since the back-end sends unique results, one per query.
