### ISSUE TITLE
Stat panel: Override threshold with value

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#28313]
**What would you like to be added**:
The ability to override style (dynamically set through threshold) when overriding values of a `Stat` panel

**Why is this needed**:
When a `Stat` panel uses an inverted scale (in which values above a specific value are shown green, and under which colours are being used to indicate problems), in case of a lack of data, which can be considered legitimate in case the query filters on problematic values, the corresponding `null` value seems somehow interpreted as the equivalent of `0`, displaying the overriden `null` value in the colour associated with said `0`.
It would be nice to be able to associate an overriden value with a chosen style in the thresholds list.

**Comment by peterholmberg** [comment]
This will be possible in Grafana 7.3.0

https://github.com/grafana/grafana/pull/28039

**Comment by Berbe** [comment]
I just tested `v7.3.0` and I cannot find a way to associate a `null` -> `Overriden value` to an overriden colour.

@peterholmberg Would you mind explaining to me how to do so?

**Comment by Berbe** [comment]
Could you reopen this?

I would like to have a way to override `no value` with a specific colour, on top of overriding the value:
![Grafana-v7 3 0_Override-color_no-value](https://user-images.githubusercontent.com/4251220/97699814-1345bf80-1aab-11eb-9a47-5a02f55bd70e.png)
