### ISSUE TITLE
Templating: Custom variable input box switch to area input

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#28312]
The custom varuable now supports key value pairs after this PR https://github.com/grafana/grafana/pull/27829 

Would be nice to expand the input to be a text area so it's easier to edit many entries. 

Here is the editor for custom variables:
https://github.com/grafana/grafana/blob/master/public/app/features/variables/custom/CustomVariableEditor.tsx#L47

**Comment by darrylsepeda** [comment]
Hi @torkelo, may I confirm if this task is just changing input text into textarea?
I will work on this issue

**Comment by darrylsepeda** [comment]
Hello @torkelo, can you please help to review this PR?
thanks in advance
