### ISSUE TITLE
Grafana 7 Error: tsdb.HandleRequest() error time: invalid duration $inter 

### ISSUE THREAD

**Issue by Daly123456** [grafana/grafana#28317]
![image](https://user-images.githubusercontent.com/46686877/96249532-38173e80-0fa5-11eb-8372-c10b2aa1e241.png)
i setted an alert on cpu but i always get this error here :
Error: tsdb.HandleRequest() error time: invalid duration $inter 

and i couldn't receive any alerts

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
Please fill in the template with minimum steps to reproduce, Grafana version etc.

**Comment by Daly123456** [comment]
Grafana 7.2.0
Grafana+influx+telegraf
Graph panel

**Comment by torkelo** [comment]
related to this feature request https://github.com/grafana/grafana/issues/6557
