### ISSUE TITLE
InlineForm component label ids not unique 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#28315]
Getting these errors: 
![Screenshot from 2020-10-16 10-41-20](https://user-images.githubusercontent.com/10999/96243782-83315180-0fa5-11eb-8466-824fb6ec973e.png)

Also the new test data query editor is issuing a lot of repeated api calls: 
![Screenshot from 2020-10-16 11-01-32](https://user-images.githubusercontent.com/10999/96243812-8cbab980-0fa5-11eb-8bf6-01fb40f953ef.png)

**Comment by Clarity-89** [comment]
This is not really a bug with inline labels but test data query editor. Will need to make sure the ids are different there based on the query refId.
