### ISSUE TITLE
GrafanaTheme: Move theme objects to grafana/data

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#28319]
The types are in grafana/data but the actual theme objects are in grafan/ui making it tricky to access them in grafana/data both in the real code & unit tests.

**Comment by dprokop** [comment]
Agree, this makes sense @torkelo !

**Comment by torkelo** [comment]
related problem the display processor, has the wrong type, theme is optional but it should not be. 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/displayProcessor.ts#L44
