### ISSUE TITLE
Plugins: Failed to load multiple versions of plugins

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#28324]
**What happened**:
Upgraded to 7.3.0-beta1 and Grafana failed to start with the following error message:
```
EROR[10-16|09:58:48] Server shutdown                          logger=server reason="Service init failed: failed to scan external plugins directory '/home/marcus/go/src/github.com/grafana/grafana/data/plugins': Plugin with ID \"grafana-worldmap-panel\" already exists"
Service init failed: failed to scan external plugins directory '/home/marcus/go/src/github.com/grafana/grafana/data/plugins': Plugin with ID "grafana-worldmap-panel" already exists
[Bra] 10-16 09:58:48 [ WARN] Fail to execute command: ./bin/grafana-server [-packaging=dev cfg:app_mode=development] - exit status 1
```

**What you expected to happen**:
Grafana to start without throwing error and exit.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install raintank-worldping-app plugin
1. Install grafana-worldmap-panel plugin
1. Start Grafana

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.0-beta1 / master (6002df580f)
- Grafana plugins: raintank-worldping-app, grafana-worldmap-panel

**Comment by aknuds1** [comment]
Working on this now.
