### ISSUE TITLE
API Create Datasource

### ISSUE THREAD

**Issue by bw123** [grafana/grafana#2833]
I'm on 2.1.pre trying to POST to /api/datasource to create a new datasource using the body from the documentation. The response from the server: requires ID
    {
        "name":"test_datasource",
        "type":"graphite",
        "url":"http://mydatasource.com",
        "access":"proxy",
        "basicAuth":false
    }
Do I need to specify the ID or is it created by the server. I tried to specify it and it returns: "Datasource Updated" but the datasource does not appear anywhere.

Any help would be appreciated...

**Comment by torkelo** [comment]
Try updating to 2.1.3
