### ISSUE TITLE
Have to hardcode path to sqlite3 db file

### ISSUE THREAD

**Issue by joelbreton** [grafana/grafana#28331]
**What happened**:
grafana upgraded from 7.0.3 to 7.2.1 via apt fails to start with this error:
"Service init failed: failed to connect to database: failed to create SQLite database file \"grafana.db\": open grafana.db: permission denied"

**What you expected to happen**:
Grafana 7.2.1 should startup without having to update grafana.ini

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana 7.03 via apt
configure to use sqlite3 as the DB
Upgrade to 7.2.1 via apt update && apt upgrade grafana

**Anything else we need to know?**:
I noticed that the only way I can get around this error is to hard-code the full path to the DB file in grafana.ini like this:
```
[database]
type = sqlite3
# For "sqlite3" only, path relative to data_path setting
#;path = grafana.db
path = /var/lib/grafana/grafana.db
```
Notice the comment about the path being relative... This doesn't seem to be the case though. Config item "data" is commented out near the top of the ini with the value "/var/lib/grafana" which I assume means that the default value.

Is this a new bug since 7.0.3 or am I missing something to configure this correctly?

**Environment**:
- Grafana version: 7.0.3 upgraded to 7.2.1
- Data source type & version:
- OS Grafana is installed on: Ubuntu 18.04.5 LTS
- User OS & Browser: Windows 10
- Grafana plugins: 
- Others: Grafana was installed using apt

**Comment by aknuds1** [comment]
Can you please rewrite the issue using the standard bug template? I just tried v7.2.1 now, running it from the unpacked tar archive, and it creates data/grafana.db as one would expect. You'll have to give enough info as to how to reproduce your problem.

**Comment by joelbreton** [comment]
Thanks for the tips @aknuds1 .  Hopefully the updates I made are ok.

**Comment by aknuds1** [comment]
Yeah, much better thanks.

**Comment by aknuds1** [comment]
If possible, could you test with a clean installation also, as opposed to upgrading? I doubt that the upgrade would make any difference, would just like to see if you can reproduce also without the upgrade step.

**Comment by joelbreton** [comment]
OK, I'll test and report back, thanks

**Comment by aknuds1** [comment]
I just tried to reproduce in an Ubuntu 18.04 Docker container:

```
docker run --rm -ti -p3000:3000 ubuntu:18.04 /bin/bash
apt-get update
apt-get install -yq curl
curl -fLO https://dl.grafana.com/oss/release/grafana_7.2.1_amd64.deb
dpkg -i grafana_7.2.1_amd64.deb
service grafana-server start
```

As you can see from this log message, it creates the database at /var/lib/grafana/grafana.db:

```
t=2020-10-16T15:25:45+0000 lvl=info msg="Creating SQLite database file" logger=sqlstore path=/var/lib/grafana/grafana.db
```

I think something must be wrong in your config.

**Comment by joelbreton** [comment]
OK, clean install on my standard image also works properly. I compare the default ini to the one I have which is not working, and found this extra line:
`connection_string=file:/var/lib/grafana/grafana.db`
With that line removed, and default settings for the path, Grafana now starts up properly.

Thanks for your help @aknuds1 , was in fact a config issue on my end.

**Comment by joelbreton** [comment]
Was a config issue.
