### ISSUE TITLE
graphite query editor: find request failure invisible in UI

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#28336]
Grafana v7.2.1 (72a6c64532)

**What happened**:

When using graphite, and using the query editor, which triggers find requests in the background, if the find request fails, nothing is visible in the UI.
the only tell is this in the grafana logs:
```
grafana_1        | t=2020-10-16T18:38:08+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/proxy/3/metrics/find status=400 remote_addr=172.25.0.1 time_ms=2 size=40 referer="http://localhost:3000/dashboard/new?editPanel=2&orgId=1"
```
but as the user in the UI nothing is visible (or more precisely, the panel doesn't update, it shows whatever the last drawn panel was)

**What you expected to happen**:

I expect to see an error in the UI

**How to reproduce it (as minimally and precisely as possible)**:

it's hard to deliberately generate a find error, but it can be done e.g. with https://github.com/grafana/metrictank/pull/1926 to autocomplete on a number of series that exceeds the limit

**Comment by Elfo404** [comment]
Query editor related errors that don't block the user from performing queries should not appear in the UI.

What we could do is printing them in the console maybe so that users are not required to check grafana logs.

**Comment by Dieterbe** [comment]
> Query editor related errors that don't block the user from performing queries should not appear in the UI.

they do, though? if the find fails, grafana won't execute the render request. not sure what exactly you mean with "block", technically the user can still execute a query if they somehow realize the problem (for which there is no indication), and manually correct the problem (e.g. by going into raw edit mode)

it's very poor UX to not tell user when metric expansion fails and that prevents the render from executing, as that is precisely what the query editor is supposed to assist with.

**Comment by aocenas** [comment]
Don't know much about Graphite query editor so not sure what `find requests` is. Is that a request that populates some options inside the query editor?

**Comment by Dieterbe** [comment]
yes, it essentially provides the autocomplete to build the complete query pattern, node by node (node is a graphite term, but is essentially a "word" in between dots, e.g. stats.this_metric.has.five.nodes)

**Comment by aocenas** [comment]
Yeah in that case query editor should handle that. Don't think we have common UI pattern for that will have to see how we show errors for example in prometheus if we cannot get labels for autocomplete or for the metric dropdown. The simplest case would be to just show the error toast/notification in upper right corner. QueryEditors can always implement some more appropriate error messages right next to their elements if proximity is appropriate but doing the error notification should be the least common denominator in this so we do not silently ignore errors.
