### ISSUE TITLE
Support symlinks in plugins/datasource

### ISSUE THREAD

**Issue by jwhited** [grafana/grafana#2834]
path/filepath Walk() does not follow symlinks.

**Comment by jwhited** [comment]
I don't mind submitting a PR for this. Definitely nice to have when developing plugins in their own repo

**Comment by jmaitrehenry** [comment]
+1

**Comment by jmaitrehenry** [comment]
For now, I mount plugin with a mount, ex:
mount -o bind /usr/share/grafana-zabbix/zabbix /usr/share/grafana/public/app/plugins/datasource/zabbix

It's not really elegant but it works.

**Comment by mtanda** [comment]
+1
