### ISSUE TITLE
Graph vis has broken legend space/insets in 7.3.0 beta1

### ISSUE THREAD

**Issue by dguendisch** [grafana/grafana#28347]
**What happened**:
Two graph panels in 7.2.1:
![image](https://user-images.githubusercontent.com/30311254/96371799-e8cb3c80-1163-11eb-820d-d845e800d29f.png)

The same panels in 7.3.0 beta 1:
![image](https://user-images.githubusercontent.com/30311254/96371804-f4b6fe80-1163-11eb-92b0-57bdebd1f6c9.png)

**What you expected to happen**:
Panel/legend space not to be wasted with emptiness.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/28314
