### ISSUE TITLE
Git raises CRLF warning for public/app/plugins/datasource/influxdb/specs/datasource.test.ts

### ISSUE THREAD

**Issue by KamalGalrani** [grafana/grafana#28345]
**What happened**:
While commiting, git throws the following warning
```
warning: CRLF will be replaced by LF in public/app/plugins/datasource/influxdb/specs/datasource.test.ts.
The file will have its original line endings in your working directory.
```

**Environment**:
- Grafana version: master
- OS Grafana is installed on: Ubuntu 16.04

**Comment by ivanahuckova** [comment]
This might be an issue with your git config. You can learn more here: https://stackoverflow.com/questions/5834014/lf-will-be-replaced-by-crlf-in-git-what-is-that-and-is-it-important
