### ISSUE TITLE
Dashboard won't reload if time range changes before full reload

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#28354]
**What happened**:

When we change the time multiple time in dashboards (e.g. move forward / backwards), grafana is no longer loading the data, the spinners run and grafana is 'blocked', not running any queries.

**What you expected to happen**:

it works like before

**How to reproduce it (as minimally and precisely as possible)**:

open a dashboard, navigate in time multiple times.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.0-beta1
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Linux / Chrome and Windows / Chrome (2 different users reported this)

**Comment by roidelapluie** [comment]
To reproduce it:

Press t + arrow to change timerange , and do it again **before dashboard is fully reloaded**

**Comment by roidelapluie** [comment]
Note: it appears to be a frontend issue, as I can see a lot of queries made to the backend, while frontend shows the spinning icon on all the graphs:

![reload](https://user-images.githubusercontent.com/291750/96423362-858be980-11f9-11eb-88b6-36f10a805f05.png)

**Comment by hugohaggmark** [comment]
@roidelapluie I think this is fixed by https://github.com/grafana/grafana/pull/28323. It would be great if you had the possibility to confirm this as I can't repro the reported issue on master.

**Comment by roidelapluie** [comment]
> @roidelapluie I think this is fixed by #28323. It would be great if you had the possibility to confirm this as I can't repro the reported issue on master.

The latest nightly does not seem to have the issue, but I am short in time to confirm that this particular change was the issue. Thanks!

**Comment by hugohaggmark** [comment]
We closed this issue because we believe that #28323 fixes this, we can always reopen this issue if are assumptions were wrong.

All the best
