### ISSUE TITLE
Azure: Problem with Microsoft.NetApp/../../volumes

### ISSUE THREAD

**Issue by seanluce** [grafana/grafana#28350]
When trying to create a panel for Azure metric 'Microsoft.NetApp/netAppAccounts/capacityPools/volume' the below error message is displayed:

**The Resource 'Microsoft.NetApp/netAppAccounts/capacityPools' under resource group 'my.rg' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix**

Seems like the API call is missing '/volumes'.

Creating panels for Azure metric 'Microsoft.NetApp/netAppAccounts/capacityPools' works as expected.

**Comment by torkelo** [comment]
Please include all the network requests made by Grafana when building the query & the responses. Not sure why this particular metric would fail. Maybe some response from the Azure API that is wrong?

**Comment by seanluce** [comment]
Thank you, Torkelo. I am not sure how to include the information that you have requested.

The problem occurs when I try to select a 'Metric Namespace' from the dropdown after selecting a volume.

Picture of error: https://ibb.co/D1mhB6B

It is a bit suspect that the error does not reference the path to '../volumes' but only to the parent resource '../capacityPools' considering that the resource in question is a volume.

**Comment by migel0** [comment]
Hi
I hope give you some light.

It seems Grafama request/looking for volumes into   'Microsoft.NetApp/netAppAccounts/capacityPools
instead
/Microsoft.NetApp/netAppAccounts/${NetApp accountNAME}/capacityPools

An example of the request made over Azure Portal could be
![image](https://user-images.githubusercontent.com/42206588/96715420-d63f4600-13a3-11eb-9da2-6af5b7171601.png)

```
relativeUrl: "/subscriptions/43534-543534-543-534-53453/resourceGroups/MygreatnetappResorucegroup/providers/Microsoft.NetApp/netAppAccounts/MyNetappGreatresourcename/capacityPools/cp-standard/volumes/mymarvelous-vol-/providers/microsoft.Insights/metrics?timespan=2020-10-20T11:00:00.000Z/2020-10-21T11:15:00.000Z&interval=PT15M&metricnames=XregionReplicationRelationshipTransferring&aggregation=average&metricNamespace=microsoft.netapp%2Fnetappaccounts%2Fcapacitypools%2Fvolumes&autoadjusttimegrain=true&validatedimensions=false&api-version=2019-07-01"
```

**Comment by wbrowne** [comment]
If I understand the problem correctly, I believe this issue is addressed in [this fix](https://github.com/grafana/grafana/pull/28369), which will be part of Grafana 7.3.0 stable

**Comment by seanluce** [comment]
My apologies, but I don't think that fix referenced will address the issue. The API call seems to be incorrect as mentioned by migel0.

**Comment by wbrowne** [comment]
Thanks @seanluce. We'll try to take a look as soon possible

**Comment by seanluce** [comment]
> Thanks @seanluce. We'll try to take a look as soon possible

@wbrowne, is there anything I can do to assist with this effort? I have access to Azure NetApp Files in my Azure sub and I can follow directions reasonably well. Thank you.

**Comment by wbrowne** [comment]
Sorry, we haven't gotten around to this one yet at @seanluce, so in the meantime, if you would like to investigate further that would be great! You could get more request+response details from the `Query Inspector` panel in the top right-hand side of the [image you provided](https://ibb.co/D1mhB6B). If you could share them then that would be a great start!

**Comment by seanluce** [comment]
There is an API call made when building the query. This API call is meant to enumerate the MetricNamespaces for the resource. In this case the resource is: 'ANF-SouthCentralUS-Acct/SouthCentralUSAuto/slucenfs4' (netappaccount/capacitypool/volume)

From the inspector:
url: "api/datasources/proxy/1/azuremonitor/subscriptions/REDACTED/resourceGroups/SouthC.rg/providers/Microsoft.NetApp/netAppAccounts/capacityPools/ANF-SouthCentralUS-Acct/volumes/SouthCentralUSAuto/providers/microsoft.insights/metricNamespaces?api-version=2017-12-01-preview"

1. 'ANF-SouthCentralUS-Acct' should be between 'netAppAccount/' and 'capacityPools' as it is the name of the account. 
2. 'SouthCentralUSAuto' should follow 'capacityPools/' as it is the name of the capacitypool.
3. The volume name is missing completely from the path.

It should look like this:
url: "api/datasources/proxy/1/azuremonitor/subscriptions/REDACTED/resourceGroups/SouthC.rg/providers/Microsoft.NetApp/netAppAccounts/ANF-SouthCentralUS-Acct/capacityPools/SouthCentralUSAuto/volumes/slucenfs4/providers/microsoft.insights/metricNamespaces?api-version=2017-12-01-preview"

It is as if each name is shifted one field to the right from where it should be.

**Comment by seanluce** [comment]
Compare to the Capacity Pool query builder which works correctly:

url:"api/datasources/proxy/1/azuremonitor/subscriptions/REDACTED/resourceGroups/SouthC.rg/providers/Microsoft.NetApp/netAppAccounts/ANF-SouthCentralUS-Acct/capacityPools/SouthCentralUSAuto/providers/microsoft.insights/metricNamespaces?api-version=2017-12-01-preview"

Account name follows 'netAppAccounts/'. Pool name follows 'capacityPools/'.

**Comment by seanluce** [comment]
The problem seems to be in this file: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/url_builder.ts

It seems the logic only allows for resources that are 1 or 2 levels deep. Azure NetApp Files Volumes introduce a third level. rn[0] and rn[1] are referenced. The volume name is rn[3].

        `${baseUrl}/${subscriptionId}/resourceGroups/${resourceGroup}/providers/${md}/${rn[0]}/${service}/${rn[1]}` +
        `/providers/microsoft.insights/metricNamespaces?api-version=${apiVersion}`

**Comment by jotasixto** [comment]
@wbrowne any planning to address this? Is there a possible solution date?
Thanks!

**Comment by seanluce** [comment]
Hello @wbrowne! Any update on this issue? I have a number of customers who are waiting for this fix.

Thanks!

**Comment by pckls** [comment]
Hopefully #32661 is sufficient to fix this.
