### ISSUE TITLE
Curly braces messes with query syntax highlighter

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#28365]
**What happened**:

Here the following prometheus query:

```
sum(
    label_replace(
      delta(
        container_memory_working_set_bytes{
          env=~"$k8senv",
          k8s_cluster=~"$k8scluster",
          namespace=~"$k8snamespace",
          instance=~"(?i:$k8snode)",
          container_name!~"(|POD)",
          pod_name=~"($k8spod)(-[0-9a-f]{7,10})?(-[a-z0-9]{5})?",
          pod_name!~"($k8spod)-[0-9]{10}(-[a-z0-9]{5})?",
          container_name!=""
        }[$delta:]
      ),
      "pod_group",
      "$1",
      "pod_name",
      "([a-zA-Z0-9-]+?)(-[0-9a-f]{7,10})?-([a-z0-9]{5}|\\d+)"
    )
) by (pod_group)
```
It renders like that:

<img width="841" alt="k8s-pods-2-thanos_-_Grafana" src="https://user-images.githubusercontent.com/153052/96449319-f55b9d80-1214-11eb-9358-df48440a0c0e.png">

**What you expected to happen**:

Syntax highlighting not being messed up by strings containing curly braces.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2
- Data source type & version: prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
I was able to reproduce on grafana.play.

**Comment by sylr** [comment]
Resolved with new editor.
