### ISSUE TITLE
Displaying Notification: TypeError: e.notifiers.find(...) is undefined

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#28361]
**What happened**:
<details>
  <summary>TypeError: e.notifiers.find(...) is undefined</summary>

```JavaScript
Uncaught (in promise) TypeError: e.notifiers.find(...) is undefined
    notificationChannelLoaded reducers.ts:83
    Redux 4
        s
        produce
        s
        s
    reducer root.ts:51
    Redux 3
        b
        $/</</<
        dispatch
    t actions.ts:73
    c runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    f EditNotificationChannel.f2a0afafed9b2a22c90c.js:1
    o EditNotificationChannel.f2a0afafed9b2a22c90c.js:1
reducers.ts:83:56
```
</details>

**What you expected to happen**:
No exception

**How to reproduce it (as minimally and precisely as possible)**:
Displaying a Notification (from `Notification channels` list): `/alerting/notification/<ID>/edit`

**Anything else we need to know?**:
Seems to be a regression from 7.2.0, on which this exception is not encountered (all configuration otherwise equivalent)

**Environment**:
- Grafana version: 7.2.1
- OS Grafana is installed on: GNU/Linux Debian
- User OS & Browser: GNU/Linux Debian equivalent Mozilla Firefox 78.3.0esr
- Others: No exception with 7.1.5 nor 7.2.0

**Comment by ivanahuckova** [comment]
@peterholmberg I've seen that you have done a [migration to react](https://github.com/grafana/grafana/pull/25980) in 7.2.0-beta, but I couldn't find any change that happened between 7.2.0 and 7.2.1.  Do you have any idea what could have caused this issue. 

Also, I wasn't able to recreate the issue. Can I just pass it to platform/backlog project or are there any other information that you need for the investigation?

**Comment by hugohaggmark** [comment]
@mckn didn't you fix something similar to this issue?

**Comment by mckn** [comment]
> @mckn didn't you fix something similar to this issue?

hmm - not regarding the notification channels. I fixed a similar error but in the adhoc variables.

**Comment by hugohaggmark** [comment]
@mckn thank you, @peterholmberg can you have a look if it's related to the new Notification Channel work?

**Comment by Berbe** [comment]
The problem also appears in v7.2.2... but not in v7.3.0 anymore.
<details>
  <summary>v7.2.2</summary>

```JavaScript
Uncaught (in promise) TypeError: e.notifiers.find(...) is undefined
    notificationChannelLoaded reducers.ts:83
    Redux 4
        s
        produce
        s
        s
    reducer root.ts:51
    Redux 3
        b
        $/</</<
        dispatch
    t actions.ts:73
    c runtime.js:45
    _invoke runtime.js:271
    t runtime.js:97
    f EditNotificationChannel.f2a0afafed9b2a22c90c.js:1
    o EditNotificationChannel.f2a0afafed9b2a22c90c.js:1
reducers.ts:83:56
```
</details>

I hope this could help you pinpointing the source of the trouble, in order to prevent future regressions.

**Comment by tskarhed** [comment]
Closing this since it hasn't been an issue since 7.2.2. If something new pops up, don't hesitate to add it to the issue!
