### ISSUE TITLE
Quality Control 7 tools

### ISSUE THREAD

**Issue by kyoujuro** [grafana/grafana#28367]
**What would you like to be added**: 
Quality Control 7 tools

**Why is this needed**:
A lot of Manufacturing industry tend to use Quality Control 7 tools.
In particular, X-Control Chart is often used.
This is the first request, so it may not be enough, but please check it.
Best Regards.

**Comment by ivanahuckova** [comment]
Hello @kyoujuro, could you please rewrite this using the standard template that you can find by clicking on **new issue** and **Enhancement request**? 

Thank you!

**Comment by ivanahuckova** [comment]
Hello @kyoujuro, could you please provide more information and details for this enhancement request.

**Comment by kyoujuro** [comment]
Sorry for lack of the information.
Quality Control is use such as  Ishikawa diagram, chart control.

X-Control Chart uses an average value and a range of value(maximum value and mini value).
And, upper control limit(UCL) and lower control limit(LCL) are drawn horizontally to form the group. Dot the characteristic value of them.
Although it is possible to create a control chart by setting it in Grafana, many workers at the manufacturing site want to create it with only simple operations.
Therefore, while DX is in fashion, if you introduce it,
I think that it will be used even more in the manufacturing industry.
I may not be able to create it immediately due to lack of ability,
Perhaps I will create it and send you a pull request.
In that case, please check it.

**Comment by ivanahuckova** [comment]
Maybe you can check out following plugins:  
- https://grafana.com/grafana/plugins/agenty-flowcharting-panel ->  It allows you to basically draw up in draw.io what you are after, and then you can associate the objects with data. It's also really well documented. 
- https://github.com/yesoreyeram/grafana-infinity-panel -> may also fit.

You can maybe also check on https://community.grafana.com/ if there are any other panels that people in people in manufacturing industry use.

Also, this feature request is not directly related to Grafana therefore I am going to close it. But it would be awesome if you decided to create plugin or shared on the community site if you find plugin that works for your situation. It might help other people in manufacturing industry as well!
