### ISSUE TITLE
Graphite - Filter by query transformation does not work

### ISSUE THREAD

**Issue by ivonutar** [grafana/grafana#28373]
This question is already asked in https://community.grafana.com/t/transformation-filter-data-by-query-doesnt-seem-to-work/37441, but should be created as Issue in here as well.

**What happened**:

I have a dashboard with multiple panels. One panel is making 4 different queries and shows them in the Graph. I want other 4 panels each to show one of the queries. I use Simple JSON datasource as a datasource for the big panel and --Dashboard-- for the small panels. As I understood it, transformation "Filter by query" is the way to go. I have a problem there:

When I try to use this transformation, I don't see any queries to choose from (see screenshots). As you can see, there are 5 refIds available, but I cannot see any in the Transform tab. 

This issue is also reproducible in play.grafana.com. It works for some datasources, eg. in "1-new-features-in-v7-0" for "default" - but not if the source panel datasource is changed to anything else ("-- Grafana --" for example). Therefor I think it might be an issue with datasources.

**What you expected to happen**:
I expect to see a list of queries from source panel to choose from.

**How to reproduce it (as minimally and precisely as possible)**:
In play.grafana.com, open demo/1-new-features-in-v7-0 dashboard (https://play.grafana.org/d/0KapoFkMk/1-new-features-in-v7-0). In "Transform:calculations" panel, set datasource to "-- Grafana --" and add A and B queries. Then open panel "Reduce transformer", choose "-- Dashboard --" datasource and use "Transform:calculations" panel as source panel. Then add Transformation "Filter data by query" (and delete the original Reduce). Now you don't see the queries A and B to choose from. In default setting (with original datasource in "Transform:calculations") you can see the 5 queries and choose some of them for your panel.

**Environment**:
- Grafana version: 7.2.1 (the one on play.grafana.com)
- User OS & Browser: Ubuntu, Chrome

**Comment by ivanahuckova** [comment]
Hello @ivonutar and thank you for creating issue! This is definitely a bug. Also, just checking - have you experienced it with any other data source besides Graphite and Simple JSON that you think we should look at?

**Comment by ivonutar** [comment]
Ahoj @ivanahuckova, ďakujem za odpoveď:) 

I did not test it with any other datasources - I only played with it on play.grafana.com. You can also see it on https://play.grafana.org/d/000000045/big-dashboard, and probably on some others. In fact, I was only sucessful with the "new-fatures-in-v7" one, and only with its original datasource setting. 

Is the functionality in any way connected to datasource at all? I did not see any warnings/errors in js console that it cannot find RefID parameter in the available queries, or any other signs of a problem (besides not seeing the queries). How does Grafana look for this list of refId?

**Comment by ivanahuckova** [comment]
🙂 hahaha, nemas zac! 

Yes, it is directly connected to data sources as they process response and create data frames/table model/time series. You can learn more here - https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/. And for the *filter by query transformation* to work, data source needs to pass refId, so the reference to query that create the frame/model. And in graphite and simple JSON, we are not passing refId and therefore all refIds are undefined and *filter by query transformation* does not work. 

I have added this to our backlog and we'll look into it.

**Comment by ivonutar** [comment]
Thank you for the answer! But that is quite weird - as you can see in the screenshot (https://i.stack.imgur.com/ax5rE.png)
, the Simple JSON datasource has the refId attribute for every query available. So the only problem is that this refId is not getting propagated?

I have two additional questions:

1. Is there some way how I can fix this issue on my local installation, preferably without recompiling Grafana? Or, if this is only issue of the datasource plugin, can you give me some hint on where to look for for possible implementation of this feature? (I am currently looking on SimpOD JSON datasource source code, so if the change is something as trivial as passing variables, it might be easy to implement)

2. Do you have a list of supported datasource plugins for this feature?

**Comment by ivanahuckova** [comment]
You can always use our query inspect to see if refId was passed to query results as transforms only have access to the query results.
![Kapture 2020-10-20 at 13 57 43](https://user-images.githubusercontent.com/30407135/96583031-6a45da80-12dc-11eb-82d7-79044840a28b.gif)

It has to be fixed in SimpleJSON data source - refId needs to be passed to the result. You can check out implementations in Loki datasource: [resultToTableModel]([url](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts#L188)) or [resultToDataFrames](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts#L340). But basically, you just need to add a refId field to table/dataFrame.

**Comment by ivonutar** [comment]
Yes, I just thought about it and found out that is really the only thing needed :D Thank you though, this might still be an issue for other datasource plugins - but in Simple JSON datasource, it is indeed just a thing of adding one parameter to the response.

**Comment by ivanahuckova** [comment]
I have created issue for SimpleJSON data source https://github.com/grafana/simple-json-datasource/issues/164 as it is separate data source. I am leaving this one for graphite.

**Comment by ivonutar** [comment]
I think this is not an issue with the datasource plugin. Developer creating the server backend that creates responses should be adding refId to the response. Simple JSON Datasource plugin is just the connection layer.

**Comment by ivanahuckova** [comment]
Yes, you are probably right. Then it should be at least added to documentation. Modified the issue.

**Comment by torkelo** [comment]
Graphite issues all queries in one request, and the response does not allow Grafana to correlate which result came from which query. So filter by refId (query) is currently not supported for Graphite.
