### ISSUE TITLE
Save As dialog for a dashboard is wonky

### ISSUE THREAD

**Issue by tulanian** [grafana/grafana#2837]
In 2.1.3 the Save As... dialog appends "copy" to the end of the existing dashboard name and moves the cursor to the end of the text after each edit (e.g. put cursor in middle of word, hit backspace, char disappears and cursor jumps to end). Makes editing names very, very annoying.

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by tulanian** [comment]
It's a pleasure reporting bugs in grafana because they get fixed so quickly!
