### ISSUE TITLE
Unable to create external snapshot

### ISSUE THREAD

**Issue by hdhruna** [grafana/grafana#28380]
This question is already asked in https://community.grafana.com/t/unable-to-create-external-snapshot/38146, but should be created as an Issue in here as well.

**What happened**:
We have multiple dashboards configured on our primary grafana server of which we want to create a snapshot on a secondary grafana server. When we try to create the snapshot we received a status code 500 in grafana logs.

```
t=2020-10-19T13:27:52+0000 lvl=eror msg="Failed to create external snaphost" logger=context userId=1 orgId=1 uname=admin error="Create external snapshot response status code 401"
t=2020-10-19T13:27:52+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/snapshots status=500 remote_addr=202.88.214.160 time_ms=107 size=48 referer="https://primary.grafana.com/d/09ec8aa1e996d6ffcd6817bbaff4db1b/kubernetes-api-server?orgId=1&refresh=10s"
```
Snapshot is created when `external_snapshot_url=https:/USERNAME:PASSWORD@secondary.grafana.com` is set in `grafana.ini` on our primary grafana server.

**What you expected to happen**:
Grafana snapshot should be created
**How to reproduce it (as minimally and precisely as possible)**:
Set `GF_SNAPSHOTS_EXTERNAL_SNAPSHOT_URL=https:/USERNAME:PASSWORD@secondary.grafana.com` environment variable

**Environment**:
- Grafana version: v7.0.3 (00ee734baf) on both primary & secondary
- Data source type & version: Prometheus v2.18.2
- User OS & Browser: Arch Linux, Chromium

**Comment by torkelo** [comment]
Make  sure you have enabled public_mode on the snapshot server to allow another Grafana to create snapshots there:
https://grafana.com/docs/grafana/latest/administration/configuration/#public_mode

**Comment by torkelo** [comment]
The error is a 401 from your public grafana, so it's authentication related

**Comment by hdhruna** [comment]
As I mentioned, it works when I pass the same value within `grafana.ini`, is there an issue when we pass username:password in the URL? Also, the secondary grafana server is hosted in Aiven.

**Comment by hdhruna** [comment]
Thank you @torkelo 
For anyone else using Aiven's Grafana service, make sure you set Access Route to `public`
