### ISSUE TITLE
Plural of units in single stat panel

### ISSUE THREAD

**Issue by The-Nik** [grafana/grafana#2838]
Is there any posibility to activate plural for the units in the singlestat panel?
Example:
Current: 4.32 week
Correct: 4.32 weeks

A workaround would be to use always the plural form because plural is more often correct than the singular way. Where can I edit this terms in the source code? I didn't find the correct line :/

**Comment by The-Nik** [comment]
Any idea about the line in code where I can change manually "week" to "weeks" as a first workaround?

**Comment by torkelo** [comment]
closed in favor of this, https://github.com/grafana/grafana/issues/2971
