### ISSUE TITLE
Add instrumentation of database connectivity

### ISSUE THREAD

**Issue by aned** [grafana/grafana#28384]
**What would you like to be added**:
DB sync status (for Grafana setup in HA mode)  should be available at /metrics (for prometheus to scrape)
There is nothing useful available at /api/health, 
```
{
"commit": "efe4941ee3",
"database": "ok",
"version": "7.2.0"
}
```
the ```"database": "ok"``` doesn't change when there is underlying mysql db sync issues. 

**Why is this needed**:
It’s a critical operational data point, if Grafana cluster is behind a Load Balancer, it's crucial to maintain all Grafana instances in sync. If mysql DB sync fails - a corresponding metric should be updated at /metrics.

**Comment by marefr** [comment]
I'm not sure this is something Grafana can keep track of. Wouldn't monitoring the database itself be the proper solution to your problem? I'm not really sure what you mean with "mysql db sync issues".

**Comment by aned** [comment]
The underlying "mysql sync DB" is in HA setup as well and for the sake this example it can be assumed as always available. 
The problem can occur when there is some connectivity issues from Grafana to "mysql sync DB" (acl/iptables, routing, etc). 
Without this metric we would have no idea which grafana instances in HA cluster are having issues to sync.

**Comment by wbrowne** [comment]
Hey @aned. Would you mind describing more in detail your current HA Grafana setup? I'm curious to better understand what you mean by "sync issues" (do you mean replication across database instances, syncronization between Grafana and the database, etc.)

[This](https://github.com/grafana/grafana/pull/28349) work may be related - is this the kind of information you're looking for?

**Comment by aned** [comment]
Thanks for pointing to [PR](https://github.com/grafana/grafana/pull/28349)  @wbrowne  !
We just need to monitor whether the synchronization btw Grafana and MySQL happened on all instances in the Grafana cluster (so all the dashboards/datasources are in sync on all instances)
I think the  [PR](https://github.com/grafana/grafana/pull/28349) should address it.
Any chance to make it available via /metrics vs `/api/health` + `exporter` ?

**Comment by wbrowne** [comment]
@aned https://github.com/grafana/grafana/pull/28349 solves the issue of verifying that there's a valid connection between Grafana and the database, nothing related to synchronization. I'm still uncertain about the exact problem you're trying to solve - are you perhaps more interested in the topic of database slave lag?

Instances of Grafana are synchronized through the database itself. Perhaps [the HA Grafana docs](https://grafana.com/docs/grafana/latest/administration/set-up-for-high-availability/) will give you the information you need

**Comment by aned** [comment]
For example, there are 3 grafana instances in HA cluster. One of the instances becomes blocked to access mysql "sync DB" (acl update, network routing, etc). 
A load balancer will round-robin users btw 2 "healthy" (read synced) and 1 "unhealthy" instance (not synced). The end result will be discrepancies for end users (depending on which instance load balancer put them). 
Currently there is no way to proactively monitor this scenario (well, #28349 will help by verifying that there's a valid connection between Grafana and the database, it would be beneficial if this new metric was available via /metrics)

**Comment by marefr** [comment]
@aned changed the title to reflect instrumentation of database connectivity is requested as feature, .e.g. each time a database connection is tried to be established it will increase a success or failure counter. Is this what you need/want?

**Comment by aned** [comment]
Yes @marefr, that makes total sense.
