### ISSUE TITLE
Annotations List Panel - Spacing of items is broken

### ISSUE THREAD

**Issue by rjvtww** [grafana/grafana#28389]
**What happened**:

Before 7.1.5, the annotations list panel would display annotations with good spacing between each item, and the time stamp would be displayed at the far right. Currently, with the latest version, elements are crammed together and dont look very pleasing

![image](https://user-images.githubusercontent.com/69891597/96558610-378bea00-12bc-11eb-888b-7d976621a2df.png)

**What you expected to happen**:

The elements in a row (in one annotation) should be properly spaced

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Built-in annotations
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows, Chrome

**Comment by ivanahuckova** [comment]
I was able to reproduce this on current master - Grafana v7.4.0-pre (89ebb97fca) - as well.
![image](https://user-images.githubusercontent.com/30407135/96564878-f8619700-12c3-11eb-98b7-0882d4113af8.png)

**Comment by torkelo** [comment]
this is an alpha panel so no need to patch this in 7.3.1
