### ISSUE TITLE
grafana/toolkit: Datasource with backend plugin template throws Typescript errors when building

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#28395]
**What happened**:
Created a new **data source with backend** plugin using grafana/toolkit (next version). When running `yarn build` the build failed due to the following errors:

![image](https://user-images.githubusercontent.com/2376619/96580404-821b5f80-12d8-11eb-8953-941940102664.png)

**What you expected to happen**:
I expect the plugin to build correctly.
**How to reproduce it (as minimally and precisely as possible)**:
1. Bootstrap a data source with backeng plugin using grafana/toolkit: `npx @grafana/toolkit@next plugin:create dataource-be`
2. Run `yarn install`
3. Run `yarn build`
4. See Typescript errors being thrown

**Environment**:
- Grafana version: doesn't matter
- Data source type & version:  doesn't matter
- OS Grafana is installed on: Mac OS Catalina (latest)
- User OS & Browser: Chrome
- Grafana plugins: -
- Others: -

**Comment by dprokop** [comment]
Problem introduced most probably with field color mode type changes in https://github.com/grafana/grafana/pull/28039

**Comment by dprokop** [comment]
@jackw confirms similar issue on latest channel

**Comment by dprokop** [comment]
@jackw I guess when u used latest you might have encountered this: https://github.com/grafana/grafana/issues/28341 ?

**Comment by jackw** [comment]
> @jackw I guess when u used latest you might have encountered this: #28341 ?

Yep, that's the error I was getting. 👍

**Comment by scraton** [comment]
A solution I found from [here](https://github.com/grafana/github-datasource/blob/master/package.json) suggests the need to remove `node_modules/@grafana/data/node_modules`. I guess the types from that package interfere with the build process? Setting up my `package.json` to following got the build working for `7.2.2`:

```json
  "scripts": {
    "build": "rm -rf node_modules/@grafana/data/node_modules; grafana-toolkit plugin:build",
    "test": "rm -rf node_modules/@grafana/data/node_modules; grafana-toolkit plugin:test",
    "dev": "rm -rf node_modules/@grafana/data/node_modules; grafana-toolkit plugin:dev",
    "watch": "rm -rf node_modules/@grafana/data/node_modules; grafana-toolkit plugin:dev --watch"
  },
```

**Comment by marefr** [comment]
Is this the same as https://github.com/grafana/grafana-starter-datasource-backend/issues/16?

**Comment by dprokop** [comment]
Fixed with https://github.com/grafana/grafana-starter-datasource-backend/commit/fe65385fa5f01ee0c4e49038a355147f28f6d748. Will require removinf `resolutions` entry in package.json when #28657 is released
