### ISSUE TITLE
Provide mechanism to define sort order for template values

### ISSUE THREAD

**Issue by seppyk** [grafana/grafana#2839]
Using Grafana 2.1.3...

When creating a template variable, there's no issue with returning the set of matched template values.  However, it seems to always be sorted in ascending order both for the matched values in the template edit value and also, more importantly, in the drop-down select for users. 

It would be nice if administrators could customize the order of the displayed template values (ascending, descending, or perhaps even a custom order).

**Comment by mrclark32493** [comment]
This could be useful in my case, were we have multiple instances that I would like to check, I have a list i.e. instance1 instance10 instance11 instance2 instance21 instance22, it would be nice to have them in true ascending order.

**Comment by mhite** [comment]
Agree. This would be great. I have the same issue as @mrclark32493. Specifically, a list of CPU numbers that are dynamicalled queried and displayed as 0, 1, 10, 11, 2, etc. I would love for an option to not only sort as strings, but also integer sorting.

**Comment by kierangirvan** [comment]
We would also benefit from this with a similar situation to @mrclark32493.

**Comment by RichiH** [comment]
Thanks to @mtanda for noticing that my issue was a dupe.

The keyword @mrclark32493 et al are looking for is "numerical sorting".

**Comment by tonydaly** [comment]
Any update on this issue? Would be willing to help out as it's quite frustrating.

**Comment by mtanda** [comment]
@bergquist I create PR for this. The feature could be included in 3.1 release?

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/5129
