### ISSUE TITLE
Default graphite version mismatch

### ISSUE THREAD

**Issue by cinaglia** [grafana/grafana#28415]
**What happened**:
When creating a new graphite data source, the UI indicates that the Graphite version is `1.1.x` by default. However, tags support is not enabled when querying because the fallback version is [set to `0.9`](https://github.com/grafana/grafana/blob/185442115caf82b797816c47a9c1396426139f95/public/app/plugins/datasource/graphite/datasource.ts#L41). 

This means I can't get the [seriesByTag editor](https://github.com/grafana/grafana/pull/9436) by default unless I manually select the `1.1` version in the data source (even if it's already selected) and save it.

**What you expected to happen**:
I expected that these two defaults ([1](https://github.com/grafana/grafana/blob/185442115caf82b797816c47a9c1396426139f95/public/app/plugins/datasource/graphite/datasource.ts#L41), [2](https://github.com/grafana/grafana/blob/19d27351e9233a814bc6a512c0a98cc0f47e61d8/public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx#L47)) were the same, either `1.1` or `0.9`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a graphite data source (do not select a version).
2. Perform a query in explore & see that the tags UI is not enabled.
3. Update data source to set graphite version to 1.1.
4. Perform query & verify that tag UI is enabled.

**Proposed solution**:
The safest bet would be to change default version to 0.9 everywhere:

Before:
https://github.com/grafana/grafana/blob/19d27351e9233a814bc6a512c0a98cc0f47e61d8/public/app/plugins/datasource/graphite/configuration/ConfigEditor.tsx#L47

After:
```js
graphiteVersions.find(item => item.value === options.jsonData.graphiteVersion) ?? graphiteVersions[0];
```

If we're felling particularly adventurous, we could change it to `1.1`. Though I unfortunately do not have any data about how many people are still on `0.9`.

**Comment by cinaglia** [comment]
I'd be more than happy to provide a patch for this. Though, I'd need some guidance on whether we want the default to be latest (1.1) or 0.9.

**Comment by ivanahuckova** [comment]
@torkelo @Dieterbe any idea about which one should be default?

**Comment by torkelo** [comment]
1.1 should be the default

**Comment by ivanahuckova** [comment]
@cinaglia I can add a fix for this.
