### ISSUE TITLE
[Feature Request]: Minimize the confusion regarding saving/updating Variables

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#28428]
When a user forgets to check the __Save current variables__ toggle/checkbox the resulting state of the dashboard when refreshed is unexpected. Grafana needs to make this flow less error prone and easier to understand for the user.

Fixes: #18916

Related issues:
#20703
#20600
#27158
#28089
#26874
#21870
#16600
#15006
#13320
#10748

**Save Dashboard Modal in different versions**
__6.4.3__
![image](https://user-images.githubusercontent.com/562238/96707148-c6ba0000-1397-11eb-9161-943cedcce703.png)

__Grafana v7.4.0-pre (8032b43838)__
![image](https://user-images.githubusercontent.com/562238/96592829-1a214500-12e9-11eb-87dc-0b1ae9143dc2.png)

**Comment by jessover9000** [comment]
Can you explain what the use cases are – when would the user want to turn this on or off? In the older version I guess "on" was the default, does the 7.4 pre screenshot mean we decided to have it off by default? I must say I feel like the deactivated checkbox here is pretty easy to miss.

**Comment by hugohaggmark** [comment]
> Can you explain what the use cases are – when would the user want to turn this on or off? In the older version I guess "on" was the default, does the 7.4 pre screenshot mean we decided to have it off by default? I must say feel like the deactivated checkbox here is pretty easy to miss.

Significant questions @jessover9000, I'll try to answer them. First of the __6.4.3__ screenshot was incorrect, so I've updated it. The checkbox/toggle has always been unchecked/off by default. Now for the challenge we're facing, and this is going to get technical.

In this example, we have a saved dashboard with a Constant Variable named `var` with the value `X`.
![image](https://user-images.githubusercontent.com/562238/96707689-7ee7a880-1398-11eb-80e0-1078a32566e0.png)

This is what a simplified JSON representation (I've omitted some props that don't add value for the explanation) of that variable looks like:
```json
{
  "current": {
    "text": "X",
    "value": "X"
  },
  "name": "var",
  "query": "X"
}
```

Let's edit the variable and change the value to `Y`:
![image](https://user-images.githubusercontent.com/562238/96708207-3086d980-1399-11eb-95c6-63a744fc1fdc.png)

Let's also look again at the simplified JSON representation:
```json
 {
    "current": {
      "text": "Y",
      "value": "Y"
    },
    "name": "var",
    "query": "Y"
  }
```

All the previous `X` values in the JSON have changed to `Y` as expected. **[OK]**

Let's see what happens if we save the dashboard after this change. There are now two different paths illustrated by the checkbox/toggle. Either we keep the current value in the JSON as the new current value or not.

This is the resulting simplified JSON if we __DO NOT__ check/toggle the __Save current variables__ checkbox/toggle:
```json
{
  "current": {
    "text": "X",
    "value": "X"
  },
  "name": "var",
  "query": "Y"
}
```  
Notice how the __current__ node still has an `X` value? This happens when you __DO NOT__ check/toggle the __Save current variables__ checkbox/toggle. To add even more confusing for the user when we edit the variable now, this is what we see:
![image](https://user-images.githubusercontent.com/562238/96709418-f4ed0f00-139a-11eb-88da-5fe243ec71fd.png)

This is because when we edit the variable we're editing the query prop in the JSON (`"query": "Y"`). Also the query prop is always updated when saving the dashboard regardless of the __Save current variables__ checkbox/toggle.

This is how all the Variables work (except for AdHoc variables). Another parameter that adds to the all this confusion is that Constant variables are hidden by default so you don't actually see what the current value is in the UI. 

If I were to change the hide of the variable to none/blank as this:
![image](https://user-images.githubusercontent.com/562238/96710419-5661ad80-139c-11eb-9717-01807f9e4e93.png)

then you can at least notice in the UI there is a difference between the __current__ value and the __query__
![image](https://user-images.githubusercontent.com/562238/96710574-8c9f2d00-139c-11eb-8898-8b5c99e468ed.png)

I hope this answers your questions and feel free to try it out yourself.

I can see a couple of issues with the current implementation:

- The decision the user has to act on is in the wrong context. As a user I can do a lot of things before I decide to save a dashboard and by then I might have forgotten that I changed variable values. Maybe we should move this decision closer to variable changes?
- The checkbox is as you already stated nearly visible, maybe it should be closer to the save button with a question mark icon like what does this mean?

**Comment by jessover9000** [comment]
Ok, thanks for the in-depth explanation, this helped a lot! 💡 One thing is not 100% clear to me yet: If I edit the value, why would I consciously NOT want to save the change as a user? Because I'm just testing something?

**Comment by hugohaggmark** [comment]
> Ok, thanks for the in-depth explanation, this helped a lot! 💡 One thing is not 100% clear to me yet: If I edit the value, why would I consciously NOT want to save the change as a user? Because I'm just testing something?

I don't have a suitable answer for this one, defaulting to always having the checkbox/toggle on/checked would be an easy fix but I just don't have enough data to support that assumption. Maybe @torkelo has more info?
> 
> Also, after your explanation I'm wondering why the "Hide variable" is a dropdown and not a checkbox :D Need to check what other options there are in the UI!

There are 3 states, hide the whole variable (label and drop down), just the label or not at all.

**Comment by nikobearrr** [comment]
Hi @jessover9000 and @hugohaggmark, I just saw this thread and read your messages.
From an user perspective (and my POV), I can give you the answer for:

> One thing is not 100% clear to me yet: If I edit the value, why would I consciously NOT want to save the change as a user? Because I'm just testing something?

We have some templated dashboards where we have set the default option. Let the options be A, B, C. When I open the dashboard I would like to always see option A as default. Sometimes I will look at B and/or C, but mostly A. So I would not like B or C to become the default. Thus I wouldn't like to persist the selection of the variable.

It is like the time picker/default dashboard time interval. I want to have 6h as default, but sometimes I would go as far as 30-60-180d. But I definitely don't want 180d as default.

I hope my answer can give you some insight on that specific use-case

**Comment by hugohaggmark** [comment]
@nikobearrr thank you so much for adding your point of view

**Comment by hugohaggmark** [comment]
> We have some templated dashboards where we have set the default option. Let the options be A, B, C. When I open the dashboard I would like to always see option A as default. Sometimes I will look at B and/or C, but mostly A. So I would not like B or C to become the default. Thus I wouldn't like to persist the selection of the variable.

@nikobearrr yes your use case makes perfect sense, but how about any hidden variables like Constants? Constants are hidden per default so wouldn't it make more sense to always update the dashboard default value for a Constant or any other hidden variable? What would the use case be for using hidden variables otherwise if not to update the default value by updating the query value?

This is something that I think could solve a lot of user confusion out there. The same goes for TextBox variables, I've seen the same confusion from users about those.

I'd love to hear more from the community about this.

**Comment by nikobearrr** [comment]
@hugohaggmark I am not sure of how the flow is with modal/popups when you update the hidden variable/constants. However, in order to update a constant (hidden variable) you need to go to settings -> variables -> _specific variable_ -> update the value -> click save. I'd say that should save it on the dashboard as default. It takes a couple of extra [specific] steps to get into the position of updating it.

Now when I read the previous messaging perhaps I have mixed the context with hidden variables and the visible ones. My previous comment was targeting the visible ones when you have set something it shouldn't be automatically saved in case you change the value. Regarding the hidden variables I think the steps to update one are very specific (you need to go in the menu, update and save) which I think makes perfect sense as it is today.

**Comment by hugohaggmark** [comment]
@nikobearrr thank you. Some thoughts from me below:

> @hugohaggmark I am not sure of how the flow is with modal/popups when you update the hidden variable/constants. However, in order to update a constant (hidden variable) you need to go to settings -> variables -> _specific variable_ -> update the value -> click save. I'd say that should save it on the dashboard as default. It takes a couple of extra [specific] steps to get into the position of updating it.

_I agree, that was what I was trying to suggest in my comment above for all hidden constants. I can't think of any specific use case for hidden variables where this would not be the preferred way._

> 
> Now when I read the previous messaging perhaps I have mixed the context with hidden variables and the visible ones. My previous comment was targeting the visible ones when you have set something it shouldn't be automatically saved in case you change the value. Regarding the hidden variables I think the steps to update one are very specific (you need to go in the menu, update and save) which I think makes perfect sense as it is today.

_The challenge with Constant variables (TextBox & hidden variables) is that you need to check the __Save current variables__ toggle/checkbox when you save or it will __NOT__ save the new value as dashboard default._

**Comment by simonc6372** [comment]
Just bumped into this while researching something and felt compelled to add my view. 

From my perspective, if I change anything in the "dashboard settings" area, I would expect them to be explicitly saved when I click on "save", so to default yes. 

If I've changed a variable selection from the drop downs, I would not expect them to be saved, so that should default to no, as that is part of the dashboard usage / interaction, not dashboard design.

**Comment by hugohaggmark** [comment]
A part of this whole confusion is a bug that is beautifully explained #18916.
