### ISSUE TITLE
Can I add or update graph automatically ?

### ISSUE THREAD

**Issue by GhostComputing** [grafana/grafana#2842]
According to the grafana doc, it seems that I need to add or update graph manually ?

**Comment by torkelo** [comment]
you can create dashboards and graphs via the HTTP api if you want to program a system that builds dashboards and graphs automatically. 

But there is no AI in Grafana that figures out how you want to visualized your millions of metrics :(

**Comment by GhostComputing** [comment]
I use **grafana scripts**. When I add new metric, the deploy tool (**ansible**) will re-generate the dashboard script again, just like:

      .....
      target.push({"target": "abj-front-21.emqtt_stat.established_count"});
      target.push({"target": "abj-front-22.emqtt_stat.established_count"});
      return dashboard

and I don't know is it a efficient way or not .

**Comment by torkelo** [comment]
sounds ok, an alternative is to build the dashboards and push to Grafana using the HTTP api

**Comment by GhostComputing** [comment]
but I found that when I access the stat like : `http://grafan_url/dashboard/script/emqtt.js` and saved in grafana, the scripts will not longer take effect, so next time I need to edit the stat on the website, any solution ?

**Comment by torkelo** [comment]
Well if you save a dashboard generated from a script that dashboard will be saved as it looks then, you need to open the scripted dashboard to regenerate  it

**Comment by joehoeller** [comment]
Anytime I push a new dashboard into dashboard.rows, it updates the array but not the DOM. 
Help??
