### ISSUE TITLE
Variable interpolation with advanced format doesn't provide reasonable default

### ISSUE THREAD

**Issue by Techmaster21** [grafana/grafana#28439]
**What happened**: When using a SQL query that relies on variable interpolation and advanced formatting, when no values are selected, templating produces an error instead of a reasonable default:
![bug](https://user-images.githubusercontent.com/1794313/96736854-a469b780-1382-11eb-90ad-54b7cee6eccd.jpg)

**What you expected to happen**: I expect a reasonable default to be selected (for :sqlstring for instance, `''`)

**How to reproduce it (as minimally and precisely as possible)**: Create a variable named suites with type Custom, add some sqlstrings (e.g. 'test1','test2','test3'), and allow multi select. Then add another variable that uses the following query with a SQL datasource:
```sql
SELECT 'test' 
WHERE 'test' 
IN (${suites:sqlstring});
```
Now go back to the dashboard, and select 0 values for the suites value

**Anything else we need to know?**: Being able to disallow selecting nothing for multi select would equally suit my needs

**Environment**:
- Grafana version:  v7.1.5
- Data source type & version:  PostgreSQL 11.2 
- OS Grafana is installed on: Alpine Linux 3.12.0
- User OS & Browser: Windows 10 64bit,  Chrome 86.0.4240.75
- Grafana plugins: PostgreSQL

**Comment by ivanahuckova** [comment]
Regarding:

>Being able to disallow selecting nothing for multi select would equally suit my needs

I would say that this is definitely a feature request and if you think it could be useful for you and other users, it would be awesome if you created a new feature request for this as it is not directly connected to this bug.

**Comment by marefr** [comment]
@Techmaster21 please do something like `WHERE '${suites} = '' OR 'test' IN (${suites:sqlstring})` as a workaround

**Comment by mdvictor** [comment]
I've tested this and it seems to be working fine now. I'll close for now, but if any other problems arise, please do reopen and let us know.

Thank you for opening this issue!
