### ISSUE TITLE
Viewer user can access templating/annotations edit panels and run queries

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#2843]
When accessing grafana as user with Viewer privileges (either authenticated and assigned the role, or as an anonymous user) I can access the annotations edit panels by appending `?editview=annotations` to the URL directly (even though the icons to do so aren't there).

From the panel I can add and edit existing annotations, including running a data source query. 

I'd expect a Viewer to not be able to do this.

**Comment by torkelo** [comment]
Sure I can stop this view from being displayed but a Viewer will still be able to issue any data source query if they really wanted to as Graphite, InfluxDB, OpenTSDB etc none support per series / op permisssion. If you expose it to a Grafana user all read operations will be possible.
