### ISSUE TITLE
Do not update "next" npm tag for previous release versions

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#28448]
This is a release/deployment bug that will only happen infrequently, but worth fixing now that we have seen the stars align.

The current "next" tag should point to "7.3.0.beta1", but because 7.2.2 was released, it took over the "next" slot.  This should not happen.

![image](https://user-images.githubusercontent.com/705951/96786845-ae50e200-13a5-11eb-849c-a1d8d7e75e25.png)

Maybe related... but part of the problem is that with toolkit, even if I set an explicit version:
```
  "devDependencies": {
    "@grafana/data": "7.3.0-beta.1",
    "@grafana/runtime": "7.3.0-beta.1",
    "@grafana/toolkit": "7.3.0-beta.1",
    "@grafana/ui": "7.3.0-beta.1"
  }
```

yarn.lock includes:
```
"@grafana/toolkit@7.3.0-beta.1":
  version "7.3.0-beta.1"
  resolved "https://registry.yarnpkg.com/@grafana/toolkit/-/toolkit-7.3.0-beta.1.tgz#de968aef9c59415b7cd0f218b3761bd39945979b"
  integrity sha512-VHJuuxsncH20nEfuyB5Bg4//2K9HjTzpSTWLXLTCV59I7QLiUYna+SD7mdG06xjtxKqt7wI8nWXfPo/AZmpqUA==
  dependencies:
    "@babel/core" "7.9.0"
    "@babel/preset-env" "7.9.0"
    "@grafana/data" next  <<<<<<<<<<<<<<<<<<<<<<<<<<<<< NEXT
    "@grafana/eslint-config" "2.0.3"
    "@grafana/tsconfig" "^1.0.0-rc1"
    "@grafana/ui" next  <<<<<<<<<<<<<<<<<<<<<<<<<<<<< NEXT
    "@types/command-exists" "^1.2.0"
    "@types/execa" "^0.9.0"
```

**Comment by aknuds1** [comment]
Thanks for bringing this up, I guess it was overlooked initially!
