### ISSUE TITLE
function names with underscore are not displayed properly in the documentation

### ISSUE THREAD

**Issue by chinhodado** [grafana/grafana#28443]
On this page

https://grafana.com/docs/grafana/latest/datasources/prometheus/#templating

the functions `label_names`, `label_values`, etc. are not displayed properly. See screenshot below. It's also not possible to search for them on the page with CTRL-F

![image](https://user-images.githubusercontent.com/1388219/96765977-62ec0300-13a8-11eb-96bd-289c0f5713e8.png)

**Comment by ivanahuckova** [comment]
@oddlittlebird @achatterjee-grafana Bug in documentation intorduced in https://github.com/grafana/grafana/commit/15b593365fe4a5734e8914597e9c71322217ef75
