### ISSUE TITLE
Add a warning when the metric storage layer has availability issues

### ISSUE THREAD

**Issue by lfroment0** [grafana/grafana#28456]
**What would you like to be added**:
During high traffic events, the metrics database setup queried by grafana to plot graphs can be impacted. 
It can make request suffer from increased latency or even partial or complete metrics unavailability in the worst case.
In order to raise awareness among the users of a grafana installation, it would be nice to be able to display the current health status when the system is under stress, e.g. as a banner at the top of dashboards.

One way of doing this would be to add a service status endpoint in the configuration, which grafana would query every X minutes to get a new system health status. The response from this query could hold a message to be displayed. In this way, the status can be updated by hand in some other system.

The other way I see, would be to let grafana make use of it's own latency and error rate metrics and depending on thresholds set in configuration, let grafana display disclaimers that requests are showing signs of system degradation. 

 
**Why is this needed**:

This is particularly handy in bigger organisations which need to communicate to their engineers that there is some issue with the current setup and that metrics that those users rely on might be impacted because of some issue in the system.

**Comment by wbrowne** [comment]
Thanks for creating this issue @lfroment0! This has been a topic of discussion for a while as an idea to explore (see for example https://github.com/grafana/grafana/issues/20362 as a baseline idea to support this type of thing). I doubt this is something we will look at in the immediate future but will keep it open for now.
