### ISSUE TITLE
Test data source doesn't populate panel JSON queries/targets

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#28461]
**What happened**:
Tested an alert rule using the test data source and received an error:
![image](https://user-images.githubusercontent.com/1668778/96855520-21695f80-145d-11eb-8808-c252ba48b706.png)

**What you expected to happen**:
Successfully being able to test alert rule.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new dashboard 
2. Add new panel
3. Change data source to test data
4. Save the dashboard
5. Edit panel and add an alert rule
6. Test the rule

**Anything else we need to know?**:
Inspecting the panel JSON seems like there are no targets. Changing for example the alias field in query editor makes the targets property to be populated. Hopefully this is only a problem with the test data source, but needs to be verified.

**Environment**:
- Grafana version: master (a0932f4d2a)
- Data source type & version: test data source

**Comment by torkelo** [comment]
you have to modify the query for the default model to be populated. This is true for every data source in Grafana (as far as I know).

**Comment by torkelo** [comment]
Closing this as it's only test data source that has this where it's unique in that it has a valid query in the default state, if any real data source has this we need to fix it
