### ISSUE TITLE
"Unexpected error happened" following Loki -> Tempo flow

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#28463]
![Screenshot 2020-10-22 at 10 56 46](https://user-images.githubusercontent.com/444037/96856016-64273980-1455-11eb-8889-0d6e26925486.png)

**What happened**:

Follow the metric->logs->tempo flow, get unexpected error when clicking on a trace id in explore.

**What you expected to happen**:

Showing the trace.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.4.0-5134pre (a0932f4d2a)
- Data source type & version: 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
fyi @aocenas

**Comment by tomwilkie** [comment]
Theory is this only happens when a custom time range is selected.
