### ISSUE TITLE
Graph content too narrow, x-axis too long

### ISSUE THREAD

**Issue by msiler** [grafana/grafana#2846]
I've noticed that in my graph panels, there is a big gap between the actual lines being plotted and the edge of the graph. Here's a screenshot:
![grafana](https://cloud.githubusercontent.com/assets/5897071/10169406/8555c508-6696-11e5-8db2-f7b9b676e2db.png)

The rightmost quarter of that graph is empty. The lines ought to go all the way to the edge. Obviously there could be differences in the data that explain why the lines don't all reach as far to the right, but at least the longest plot line should be against the right side of the panel. This happens pretty consistently in my dashboard, so it could be something I'm doing wrong, though I don't know what. This is with it set to show the last 5 minutes, auto-updated every 5 seconds. 

Do I have something setup improperly? Or is this a bug?

**Comment by torkelo** [comment]
Usually caused by a time difference between your local machine and your TSDB server, make sure you have the correct time set on both

**Comment by msiler** [comment]
Both have ntp running and report the exact same time.

**Comment by torkelo** [comment]
@msiler you can check if you open chrome dev tools what the query issued is and the the time for the latest data point. 

If you have last 5min, grafana will set the time window to that, but if your TSDB only returns data that is now up to the last minute there will be a gap. This could be due to data not having been collected/sent to your TSDB yet etc

**Comment by msiler** [comment]
Sorry, I misread your original comment. I thought you meant a time difference between the machine feeding data to my TSDB and the machine running grafana. I assumed (apparently incorrectly) that grafana would display things using it's host machine time, not the browser time. My machine running the browser was not running ntp and does have different time. Sorry for the confusion. Thanks!
