### ISSUE TITLE
Legends under chart panels are rendered incorrectly in Safari and do not scroll

### ISSUE THREAD

**Issue by yednaps** [grafana/grafana#28475]
**What happened**: Long legends under chart panels are rendered outside of the panel boundaries in Safari and do not scroll properly

<img width="2560" alt="grafana-legend-issue" src="https://user-images.githubusercontent.com/1047967/96884037-11e31a00-144f-11eb-815b-717bcd35ff9e.png">

**What you expected to happen**: Prior to updating to 7.2.0, legends under chart panels scrolled fine in Safari. The issue is not seen on other browsers (I checked in Firefox)

**How to reproduce it (as minimally and precisely as possible)**: On the grafana play Traffic In/Out panel, I disabled the "to the right" option for the legend and saw the same issue.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.2
- Data source type & version: graphite, OpenTSDB, Postgres
- OS Grafana is installed on: Centos 7.7
- User OS & Browser: macOS 10.15.7, Safari 14.0
- Grafana plugins: 
- Others:

**Comment by ivanahuckova** [comment]
Hell @yednaps, this was fixed in https://github.com/grafana/grafana/pull/28254 and was part of 7.3.0-beta release.

**Comment by yednaps** [comment]
Thanks! Sorry I missed it when I searched
