### ISSUE TITLE
New table cell behaviour problematic when expanded/hovered cell is wide and far right

### ISSUE THREAD

**Issue by dguendisch** [grafana/grafana#28479]
**What happened**:
The really nice new table cell behaviour introduced with #27669 is unfortunately problematic when the resp. cell is wide and is far to the right of the table (i.e. the last column). In this case the hover expands beyond my screen and beyond the scrollable area in the browser, so I cannot click the loupe icons anymore.
![image](https://user-images.githubusercontent.com/30311254/96899219-ef71f080-1490-11eb-89af-45539915ae93.png)

This was working fine in 7.2 as obviously there was not cell expansion, so the loupe icons were still visible:
![image](https://user-images.githubusercontent.com/30311254/96899350-192b1780-1491-11eb-993a-3f3e77b9309e.png)

**What you expected to happen**:
I know that I can always circumvent by resizing my columns, but it's pretty cumbersome just to resize to see the loupe icons.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.0-beta2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
I can scroll right then I can access the filter icons., sadly I do not see a solution for this (that would break the new hover behavior where you do not see content that does not fit). I would move columns that you want to filter on left.
