### ISSUE TITLE
FR: Global search of Panel Titles + Series Aliases + Queries

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#28485]
**What would you like to be added**:
A global search function that searches Panel titles (and optionally- Series Aliases and Queries)

Similar to using chrome's Find function (ctrl-F) when on a dashboard, and assuming you have scrolled the entire length of the DB so that all of it has dynamically loaded/can be searched) - **but a search for ALL dashboards**

**Why is this needed**:
on larger dashboards (or when one has many dashboards), it can be difficult to find a panel that _you know you have created_ (or a query or series alias).  

I also think this would help greatly with designing duplicate dashboards (meaning ones that are organized differently, but may contain many of your already existing Panels / queries).

Personally i find this to be such a needed feature, that i wrote a very sloppy bash script that dumps the Dashboard table (from grafana.db),  then (awk,sed,grep,tr) cleans up / formats the output such that i get output of every Dashboard + (row) + Panel Titles + Queries - so that i can run grep over that output (and generally find what i was looking for).

thank you
(LOVE grafana!)

**Comment by dprokop** [comment]
/duplicate https://github.com/grafana/grafana/issues/264

Related issues: https://github.com/grafana/grafana/issues/15257, https://github.com/grafana/grafana/issues/20319
