### ISSUE TITLE
Add edit button option for repeated panels 

### ISSUE THREAD

**Issue by moisesvega** [grafana/grafana#28486]
**Why is this component needed**:

The edit button option has been removed [here](https://github.com/grafana/grafana/issues/21142), I understand the case but I feel like it should be an option for the owner of the dashboard. 

One use case that I used often is that I repeat rows for specific variables and create 7 ~ 10 panels for each row and sometimes while debugging I always just edit the panel that is causing issues and add more queries into it so it is easier to visualize the issue if that panel is 10 row and the last panel I need to go back for the first row and panel. This is counter intuitive and made me not use repeated at all maintaining 10 rows with 7~10 panels on it pretty much the same is not feasible either. 

My proposal is just add an option in the repeated section that allows to enable this edit button on the repeated rows/panels

![Screen Shot 2020-10-22 at 12 43 31 PM](https://user-images.githubusercontent.com/518028/96922274-7a88c180-1464-11eb-860a-186f689fcedb.png)
___
 - [ ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by torkelo** [comment]
Allowing editing is also very counter intuitive as can make changes that will not take effect. Don't think an option for this is a good idea. 

The solution that I think could work is to allow edit source panel from any repeated panel

**Comment by moisesvega** [comment]
Yeah that sounds better! The idea was to be able to edit any repeated channel if this one will change the main query is fine, the main use case here is able to go play around with that specific panel ( add more queries update the main query etc, etc)

**Comment by annelaurefroment** [comment]
I think the option to open the query from any of the repeated panels in Explore would work in this use-case, it does allow to add more queries and dig deeper into an issue spotted on one of the repeated panels.
![image](https://user-images.githubusercontent.com/49911675/119611715-a1113f80-be2d-11eb-95c7-9030c11a5be9.png)

**Comment by moisesvega** [comment]
Explore is great when I want to share or finding new metrics or create a new query on top of the query without having any context. 

When you have a dashboard with repeated panels and rows most likely you need context between rows and unique panels. With explore is kind of imposible to try to add more the query and go back and see the context that you need.

Another issue is that for dynamic dashboard with repeated-rows and repeated-panels it just take times to load using explore you are outside of this context and going back it will just take time. 

So it is not about exploring just one panel but allowing to update a set of repeated panels to compare with the context of the dashboard that contains different repeated panels and/or rows.
