### ISSUE TITLE
Stat Panel: Value is behind the graph

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#28482]
**What happened**: Font color is not same across the panel if different cell background color. Would be good to be able to set font color. It is harder to read if font color is different.

![image](https://user-images.githubusercontent.com/66313770/96905683-13d1cb00-1499-11eb-8dff-64e9781a0823.png)

![image](https://user-images.githubusercontent.com/66313770/96905940-6c08cd00-1499-11eb-8a1a-79c0703096e4.png)

**What you expected to happen**: Same font color across dashboard / panels.

**How to reproduce it (as minimally and precisely as possible)**: Setting thresholds in any panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.0-beta2
- Data source type & version: /
- OS Grafana is installed on: Debian 9
- User OS & Browser: Windows 10, Chrome 86.0.4240.75
- Grafana plugins: /
- Others: /

**Comment by edin008** [comment]
Another issue I noticed in Stat panel, number is behind the graph. I don't know if this is by design or a bug.

![image](https://user-images.githubusercontent.com/66313770/96907485-92c80300-149b-11eb-8318-5169ac04a6af.png)

![image](https://user-images.githubusercontent.com/66313770/96907797-04a04c80-149c-11eb-8c31-ac85f666ca4b.png)

**Comment by ivanahuckova** [comment]
@edin008 
>Font color is not same across the panel if different cell background color.

This is not a bug. It was introduced in https://github.com/grafana/grafana/pull/28305 and main goal is to make sure that the contrast between the background color and the font color is readable for everyone. 

>Another issue I noticed in Stat panel, number is behind the graph. I don't know if this is by design or a bug.

This has been like this for a while now. @grafana/grafana-frontend-platform is that on purpose?

**Comment by dprokop** [comment]
> This has been like this for a while now. @grafana/grafana-frontend-platform is that on purpose?

@ivanahuckova this seems like a bug
