### ISSUE TITLE
Mechanism to quickly move back/forward in timeline using the current resolution

### ISSUE THREAD

**Issue by dsw6** [grafana/grafana#2850]
It would be nice if there was a mechanism to move back/forward in the graph timeline using the current time resolution (ex:  1 hour).  For example, if the graph is showing 1 hour of data, hitting the back option would jump back to the previous hour.  This would enable users to quickly move backward/forward in the timeline, without having to zoom out.  Zooming out changes the resolution of the graph, which can make it difficult to spot the desired information.

**Comment by torkelo** [comment]
good idea! 

Will close as there is already a similar issue, https://github.com/grafana/grafana/issues/119
