### ISSUE TITLE
metricFindQuery - allow returning key/value pairs for the select

### ISSUE THREAD

**Issue by scottlepp** [grafana/grafana#28501]
**What would you like to be added**:
metricFindQuery only allows for returning an array of {text}. Allow array of {text, value}, which will in turn set the display value and value prop on the select option.

**Why is this needed**:
A typical case with selects is to set a display value with an underlying value/key that is used as the actual filter value.  In plugins this causes more effort/workarounds to use query type template variables as filters.

Same problem with ad hoc variables.

**Comment by torkelo** [comment]
This is already possible, many data sources return text and value property in metricFindValue, so it's up to each data source. 

Looks like the MetricFindValue type is wrong, missing a value property. 
https://github.com/grafana/grafana/blob/c3917e652519f926a7da12be5dccf8d96a9eaff1/packages/grafana-data/src/types/datasource.ts#L501

**Comment by scottlepp** [comment]
I tried also returning a value prop, as I did see a value prop when using templatesrv.getVariables() to read the variable values, though "value" was the "text" value and not the value prop that I returned.

**Comment by scottlepp** [comment]
@torkelo shall we leave this open to fix the type?
