### ISSUE TITLE
Sigv4 authentication returns 403 when running Grafana in Docker

### ISSUE THREAD

**Issue by deesweet** [grafana/grafana#28519]
**What happened**:

When attempting to set up an AWS Elasticsearch data source using the new AWS Sigv4 Auth feature, requests from a running Grafana Docker container to the Elasticsearch cluster fail with a 403 unauthorized error. 

The Elasticsearch cluster we are attempting to use as a datasource is running in a [private VPC](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html), and has both [encryption at rest](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/encryption-at-rest.html) (encrypted with our own [CMK](https://docs.aws.amazon.com/kms/latest/developerguide/concepts.html#master_keys)), and node-to-node encryption enabled. The security groups are properly configured to permit inbound network access to the cluster (if they weren't, of course, the requests would time out rather than returning a 403).

<img width="400" alt="Screen Shot 2020-10-23 at 5 31 43 PM" src="https://user-images.githubusercontent.com/22627069/97064571-b81c4600-155b-11eb-9b59-c41211b85ca5.png">

I have turned on debug logging and nothing particularly helpful appears in the logs. Interestingly, when I select the **Explore** option in the panel menu and try to query the data source, I see the error `Credential should be scoped to correct service: 'es'`

<img width="400" alt="Screen Shot 2020-10-23 at 5 31 53 PM" src="https://user-images.githubusercontent.com/22627069/97064560-9c18a480-155b-11eb-97ab-30f50b2e638e.png">

I have tested this on Grafana running as an ECS Fargate service using both the **AWS SDK Default** option with an IAM role that has access to the cluster, and with the **Access & Secret Key** option using an IAM user I created for testing, both with the same result. I've also tried in Grafana running in Docker locally on my Mac (using a VPN to to get network access to the cluster) using the **Access & Secret Key** option with those same static credentials, with the same result.

When I set up a proxy using [aws-es-proxy](https://github.com/abutaha/aws-es-proxy) and use the proxy URL for the data source, using both an IAM role and the static IAM user credential, requests to the cluster are successful. Also, if I enable open access in the cluster's access policy, requests from Grafana to the cluster are successful.

**What you expected to happen**:

Adding an AWS Elasticsearch Cluster as a data source, then selecting the Sigv4 Auth option, and entering either an IAM role or static credentials should result in requests to the cluster completing successfully, rather than returning a 403 Unauthorized error.

**How to reproduce it (as minimally and precisely as possible)**:

- Start Grafana in a Docker container (the Alpine Linux version) with Sigv4 auth enabled
- Add an AWS Elasticsearch cluster as a data source
- Click the slider to enable Sigv4 Auth. Select one of the following options:
  - *Running as an ECS Fargate service*: **AWS SDK default**, enter the default region, then leave the **Assume Role ARN** blank to (I assume) use the task role assigned to the running ECS task:
    <img width="300" alt="Screen Shot 2020-10-23 at 5 31 21 PM" src="https://user-images.githubusercontent.com/22627069/97064721-ee0dfa00-155c-11eb-8ee0-e19abf80cddf.png">
  - *Running locally or as an ECS Fargate service*: **Access & Secret Key**, then enter the Access Key ID, Secret Access Key, and default region of an IAM user with access to the cluster:
    <img width="300" alt="Screen Shot 2020-10-23 at 6 20 43 PM" src="https://user-images.githubusercontent.com/22627069/97065570-29132c00-1563-11eb-8684-4b595cf5f790.png">

- Click **Save & Test**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.0-beta2
- Data source type & version: AWS Elasticsearch 6.7 (VPC)
- OS Grafana is installed on: Docker (Alpine Linux version)
- User OS & Browser: macOS Chrome 86.0.4240.111
- Grafana plugins: Elasticsearch
- Others:

PR where this feature was introduced: https://github.com/grafana/grafana/pull/27552/

**Comment by aknuds1** [comment]
Thanks! I've assigned it to @wbrowne, who worked on this. He might already have a fix, I'm not 100% sure.

**Comment by deesweet** [comment]
@aknuds1 perfect, thanks for the speedy response! I'm happy to help with whatever testing/verification is needed

**Comment by aknuds1** [comment]
Have you tried Will's [PR](https://github.com/grafana/grafana/pull/28481)?

**Comment by deesweet** [comment]
@aknuds1 just pulled it down and tested locally with static IAM user credentials and it seems to have fixed the issue! I will give it a shot in ECS Fargate and see if it works with the task role.

**Comment by deesweet** [comment]
@aknuds1 just tested with ECS Fargate with a task role and the issue seems fixed there as well

**Comment by aknuds1** [comment]
Awesome.

**Comment by aknuds1** [comment]
I've made it so Will's PR closes this issue.

**Comment by deesweet** [comment]
@aknuds1 Perfect - thanks again to you and @wbrowne this is an awesome feature!

**Comment by wbrowne** [comment]
Thanks for logging this @deesweet and also for the great detail in your issue. Also cheers to @aknuds1 for pointing in the right direction!

Very glad to be of help ❤️
