### ISSUE TITLE
Console logging should not use formatting codes when output is not a terminal

### ISSUE THREAD

**Issue by ctdk** [grafana/grafana#2851]
The colorful console log output is very nice, but it causes some problems when that output is being redirected somewhere. One option could be to add a config flag to turn that off optionally, but another is to use this golang isatty implementation at https://github.com/mattn/go-isatty. With this, if it is writing to a file it would turn off the formatting codes.

This definitely comes up when running grafana with file logging turned off and using upstart's logging facility - upstart captures the standard out/error from grafana, but then it has the formatting codes, which makes parsing the log files more of a headache.

**Comment by robison** [comment]
This is also a problem when using daemontools to manage the process (and capturing logging from stdout, like upstart).

**Comment by torkelo** [comment]
There is a file log as

**Comment by ctdk** [comment]
@torkelo: Yes there is, but it doesn't address the situation where an external monitor is managing the process and capturing the output. In our use case, we turned off file logging because it duplicated the output in upstart *and* upstart would capture anything printed out by grafana if it died suddenly.

**Comment by torkelo** [comment]
I see, did not think about that. It looks like a simple config option under [log.console] and conditional here https://github.com/grafana/grafana/blob/master/pkg/log/console.go#L69 would solve it

**Comment by ctdk** [comment]
PR submitted: https://github.com/grafana/grafana/pull/2870
