### ISSUE TITLE
Compress ZIP distributives for Windows

### ISSUE THREAD

**Issue by oblalex** [grafana/grafana#28513]
Hello there!

**What would you like to be added**: Is it possible to add compression for ZIP distributives for Windows (`*.windows-amd64.zip`)?

**Why is this needed**: Currently, they take 170Mb, but can be compressed to only 50.

Thank you

**Comment by aknuds1** [comment]
Thanks, will look into this.

**Comment by aknuds1** [comment]
You're right, I can confirm that Zip compression wasn't enabled. Sorry! Have a fix for the next release.

**Comment by aknuds1** [comment]
BTW, I would recommend that you reported this as a bug instead of feature request :) It is really a bug, and is more easily acted on if reported as such.

**Comment by oblalex** [comment]
Got it, I thought it's not related to the functionality itself, hence not a real bug. Anyway, thank you!

**Comment by aknuds1** [comment]
Thank you for reporting the issue :)
