### ISSUE TITLE
Parsed Fields section does not offer any fields from the log entry

### ISSUE THREAD

**Issue by sdwire** [grafana/grafana#28522]
**What happened**: After using a regex Parser in fluent-bit to extract individual fields from nginx logs, those log entries appear to have all of the isolated fields properly parsed and stored in Loki. But when I find the log entry in the Grafana explore window and expand it to see the individual labels and fields, I see only the `ts` and `tsNs` fields available as individual fields in the Parsed Fields section.

<img width="1284" alt="2020-10-24 12_58_26-Grafana" src="https://user-images.githubusercontent.com/11800061/97087715-0aac3f80-15fa-11eb-9ed5-96bc0911f9e1.png">

**What you expected to happen**: I expect to see the "Parsed Fields" section include all of the parsed fields, including `agent`, `code`, `host`, etc.

**How to reproduce it (as minimally and precisely as possible)**:

In nginx, My access log is configured like this:
```
	log_format access '$remote_addr - $remote_user [$time_local] '
	    '"$request" $status $body_bytes_sent '
	    '"$http_referer" "$http_user_agent" "$host" '
	    '$request_time $upstream_response_time $pipe';
```

Fluent-bit daemonset on Kubernetes reads stdout from all containers using this:
```
[INPUT]
    Name              tail
    Path              /var/log/containers/*.log
    Parser            docker
    Tag               kube.*
    Refresh_Interval  5
    Mem_Buf_Limit     128MB
    Skip_Long_Lines   On
[PARSER]
    Name        docker
    Format      json
    Time_Key    time
    Time_Format %Y-%m-%dT%H:%M:%S.%L
[PARSER]
    Name   json
    Format json
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
[PARSER]
    Name   nginx
    Format regex
    Regex ^(?<remote>[^ ]*) (?<host>[^ ]*) (?<user>[^ ]*) \[(?<time>[^\]]*)\] "(?<method>\S+)(?: +(?<path>[^\"]*?)(?: +\S*)?)?" (?<code>[^ ]*) (?<size>[^ ]*)(?: "(?<referer>[^\"]*)" "(?<agent>[^\"]*)" "(?<host>[^\"]*)" (?<request_seconds>[^ ]*) (?<upstream_seconds>[^ ]*) (?<pipe>[^ ]*))
    Time_Key time
    Time_Format %d/%b/%Y:%H:%M:%S %z
[FILTER]
    Name                kubernetes
    Match               kube.*
    Kube_Tag_Prefix     kube.var.log.containers.
    Kube_URL            https://kubernetes.default.svc:443
    Kube_CA_File        /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    Kube_Token_File     /var/run/secrets/kubernetes.io/serviceaccount/token
    Merge_Log           On
    K8S-Logging.Parser  On
    K8S-Logging.Exclude On
[OUTPUT]
    Name loki
    Match *
    Url http://monitoring-loki:3100/api/prom/push
    TenantID ""
    BatchWait 1
    BatchSize 1048576
    Labels {job="fluent-bit"}
    RemoveKeys kubernetes,stream
    AutoKubernetesLabels false
    LabelMapPath /fluent-bit/etc/loki_labelmap.json
    LineFormat json
    LogLevel info
```

In the Pod definitions, I include the following annotation targeting my nginx containers so they will use the `nginx` parser to interpret stdout using my regex expression (and this appears to work):
```
annotations:
  fluentbit.io/parser_stdout-{containername}: nginx
```
**Anything else we need to know?**:
My nginx stdout does include some non-access-log lines when the container first starts up. So, the earliest entries in the stream don't have all of the fields parsed out in the log entry. I don't know that there's much I can do to avoid this, since my annotation to choose the nginx regex parser can only isolate things by container + stdout.

**Environment**:
- Grafana version: 7.2.0 (from kube-prometheus-stack:9.4.10)
- Data source type & version:
-- loki (from https://grafana.github.io/loki/charts:0.31.1)
-- fluent-bit (from https://kubernetes-charts.storage.googleapis.com/ - v2.10.1)
- OS Grafana is installed on: Linux (from kube-prometheus-stack - v9.4.10)
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins: only those built in
- Others:

**Comment by sdwire** [comment]
Upon investigation, there's an even simpler means to reproduce that doesn't involve the regex parser or anything specific to nginx.

I'm using traefik as an ingress controller, and its log files are already JSON formatted and don't need any special parser override. Those are exhibiting the same behavior in the Grafana explorer:
<img width="1302" alt="2020-10-24 17_06_57-Grafana" src="https://user-images.githubusercontent.com/11800061/97093649-c5990500-161b-11eb-9749-9c542efc93f7.png">

We can see that the `level`, `msg`, and `time` fields have been extracted from the `log` JSON object, but the Explore panel doesn't present those fields in its list of Parsed Fields.

**Comment by ivanahuckova** [comment]
Hello @sdwire! For parsing, we are using `JSON.parse()`. I think that there might be just simple problem problem with escaping and therefore we are no able to parse the log message. It would be very helpful, if you would share what does the response exactly look like - ideally using our **Query Inspector**. It would be really helpful.
![image](https://user-images.githubusercontent.com/30407135/97611544-9ec14100-1a16-11eb-8de7-c5ef30170628.png)

**Comment by sdwire** [comment]
Sure! Here's an example:

![image](https://user-images.githubusercontent.com/11800061/97700503-55a6d680-1a82-11eb-990e-5e1efee93fd2.png)

**Comment by sdwire** [comment]
`"{"level":"debug","log":"{\"level\":\"debug\",\"msg\":\"Skipping Kubernetes event kind *v1.Endpoints\",\"time\":\"2020-10-30T11:31:43Z\"}
","msg":"Skipping Kubernetes event kind *v1.Endpoints","time":"2020-10-30T11:31:43Z"}"`

**Comment by ivanahuckova** [comment]
Could I ask you to send the log line one more time, but now from the network tab and specifically from the **Response tab** to see how many `\` are in `"` escaping. There is probably 1 `\` missing for the `"`, but I would like to see if there could be something that we could do in frontend.
![image](https://user-images.githubusercontent.com/30407135/97742690-ea422080-1ae4-11eb-851c-c7274825ef8c.png)

Otherwise, I would suggest to try to add extra escaping form `"` as that might solve your problem. We have Loki json-formatted logs and Parsed fields are working for them as expected.

**Comment by sdwire** [comment]
Uploaded the HAR file from the network tab (renamed with a .txt extension).  One thing I noticed was that the `msg` field contains an embedded newline character at the end of it. Wonder if that could be causing the failure.

[grafana.local.edifyhub.com.har.txt](https://github.com/grafana/grafana/files/5469897/grafana.local.edifyhub.com.har.txt)

If that's the problem, then I'll need to figure out how to convince fluent-bit's JSON parser not to embed that newline.

**Comment by sdwire** [comment]
OK...   It looks like it's actually the Fluent-bit [Kubernetes filter](https://docs.fluentbit.io/manual/pipeline/filters/kubernetes).  When `Merge_Log` is turned on, the `Merge_Log_Trim` is supposed to remove newlines, and it's supposed to be on by default.  But it doesn't seem to be working - even if I explicitly set `Merge_Log_Trim` to true in my config.

So...   I'm going to solve this a different way, with explicit Parser filters configured for each container.

While it would be nice-ish for Grafana to tolerate this weirdness, I don't think this is a Grafana defect now.

**Comment by ivanahuckova** [comment]
Thank you so much for sending this. Yes I totally agree that Grafana should be more flexible in this, but in many cases, if escaping is not done properly, there is pretty much nothing that we can do on frontend. I am going to close this issue for now, but will open new feature request to investigate, if there is anything we can do on frontend to tolerate newline/escaping weirdness. Also I am glad you were able to figure it out! 🙂
