### ISSUE TITLE
CHANGELOG.md is missing when building plugin `grafana-toolkit plugin:build`

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#28523]
**What happened**:
CHANGELOG.md is missing when building plugin.

**What you expected to happen**:
CHANGELOG.md to be a part of dist/ folder.

**How to reproduce it (as minimally and precisely as possible)**:
Try to build plugin using `grafana-toolkit plugin:build` and check that `CHANGELOG.md` is not included.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
7.2.0
- Data source type & version:
- OS Grafana is installed on:
Mac
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mckn** [comment]
@mikhailredis what is your thinking behind including the CHANGELOG.md in the dist folder? We are including the README.md but currently not the CHANGELOG.md.

**Comment by mikhailredis** [comment]
@mckn, CHANGELOG.md was included in the `dist` folder to be displayed on the plug-in page. Looks like it was removed in the recent versions 7.2/7.3.

Please compare version 1.2.0 and 1.2.1 for https://grafana.com/grafana/plugins/redis-datasource. Tab `Change Log` exists for version 1.2.0 and is missing for 1.2.1.

Thank you.

**Comment by mckn** [comment]
> @mckn, CHANGELOG.md was included in the `dist` folder to be displayed on the plug-in page. Looks like it was removed in the recent versions 7.2/7.3.
> 
> Please compare version 1.2.0 and 1.2.1 for https://grafana.com/grafana/plugins/redis-datasource. Tab `Change Log` exists for version 1.2.0 and is missing for 1.2.1.
> 
> Thank you.

Ah, suuper! Will have a look at it.
