### ISSUE TITLE
InfluxDB: tags with dot notation can not be used in ALIAS BY

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#28529]
**What happened**:
tags with dot notation can not be used . does not resolve the tag value.
![image](https://user-images.githubusercontent.com/4919667/97149829-f55c2000-1775-11eb-85c1-5079e0206bf7.png)

**What you expected to happen**:
Tag values on graph will be displayed
**How to reproduce it (as minimally and precisely as possible)**:
1)  create test data to influxdb : **test,key.tests=1 value=1**
2) add new panel to show the added data 
3) group the query by tag **key.tests**
3) set panel Alias By to  **$tag_$key.tests**

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.1
- Data source type & version:  Influxdb 
- OS Grafana is installed on: RH 7.9
- User OS & Browser: Version 86.0.4240.111
- Grafana plugins: image-rendering -plugin
- Others:

**Comment by hugohaggmark** [comment]
Thank you for reporting this @gjemp

**Comment by gjemp** [comment]
do you have any workaround  for that cause  measuremets that come from telegraf docker kubernetes plugin to influx have dot notation tags and it makes impossible to use them .... :(

**Comment by hugohaggmark** [comment]
@gjemp but it's "only" the alias of the series that doesn't work right?  The queries work using dot notations in tags AFAIK.

**Comment by gjemp** [comment]
yes, but due that you can not show data on graph by tag values cause it is not able to resolve the tagname and the value behind that name for the particular data

**Comment by hugohaggmark** [comment]
I understand, but you can always open a PR trying to fix this.

Here is the line that needs better handling of dot notation:
https://github.com/grafana/grafana/blob/96e6524a7d68f3b341d66d940eff78723b9858ef/public/app/plugins/datasource/influxdb/influx_series.ts#L86

**Comment by gabor** [comment]
@gjemp there is an alternative syntax for tags-in-aliases ( https://grafana.com/docs/grafana/latest/datasources/influxdb/#alias-pattern ),
could you try using `[[tag_key.tests]]` ? it should work.

**Comment by gabor** [comment]
closing this for now. if the recommended alternative `[[alias]]` syntax is not suitable, we can reopen the discussion.

**Comment by QuinnBast** [comment]
Using `[[tag.otherTag]]` just makes the alias show up literally as `[[tag.otherTag]]` as my series name.

Instead I have to use a `Transform` with a "Rename by regex" to get the series name correct. However, doing this means that when I create a data link on the same data set I get cannot get the correct values from my tag names into the data link URL as the `${__series.name}` variable in the data link pulls the entire series name from the influx query and is not using the applied Transform.

**Comment by gabor** [comment]
hi @QuinnBast , i have just tested this and it works for me. for example, if you have a tag named `some.thing`, you should use this alias `[[tag_some.thing]]` . does this work for you?

**Comment by gabor** [comment]
@QuinnBast check this part of the documentation for a detailed description: https://grafana.com/docs/grafana/latest/datasources/influxdb/#alias-patterns

**Comment by QuinnBast** [comment]
Ahhh I didn't realize you had to put` tag_` in front while using the `[[ ]]` notation. Thanks!

**Comment by lambdaq** [comment]
and I thought `[[ ]]` was to be deprecated.
