### ISSUE TITLE
Dashboard delay appears to not be used

### ISSUE THREAD

**Issue by baaym** [grafana/grafana#2853]
The dashboard timepicker 'delay' setting appears to not be used. I tried setting this value because one of my servers has a clock difference (about a minute), but none of the graphs (even after a page refresh) seemed to show anything different. It's especially an issue with the singlestat graphs, which have a transformNull(0) applied to them, and constantly shows '0' for these graphs.

Since I also couldn't find documentation for that specific field, I might also be using this feature incorrectly. If that's the case, please let me know ;)

Grafana version: 2.1.3

**Comment by torkelo** [comment]
Strange, id does work for me. 

You can verify that it works by checking what request is sent to graphite (chrome dev tools / networks tab). After you change the now delay you if to pick another relative time option for it to take effect.

**Comment by baaym** [comment]
Thanks! It indeed works after toggling between a different range and back. It's a bit hidden that way, but at least I can get it to work now :)
