### ISSUE TITLE
Programmatic way of adding dashboard?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2854]
I'm using Grafana and InfluxDB for some internal graphing in my organisation.

The idea was to distribute a Dockerfile, which had everything setup already, to make it easier for people to get up and running.

One of those steps would be to add a dashboard to the Grafana instance.

I know you can export a dashboard as JSON - however, is there some programmatic way of importing a dashboard into a running Grafana instance? (i.e. a command that could be done in a Dockefile).

We're using the default SQLite database, so I suppose it might be possible to script something to write directly into that, but that seems horribly hacky.

Hence, hoping you might have a better suggestion/solution =).

**Comment by torkelo** [comment]
Yes there is a HTTP api, 
http://docs.grafana.org/v2.1/reference/http_api/

**Comment by anryko** [comment]
I have a similar situation but have chosen different approach of solving it. I use Grafanas scripted dashboard functionality and generate dashboards dynamically based on the metrics present in influxdb.
