### ISSUE TITLE
Certain longer (length of query) Loki queries seem to break the URL

### ISSUE THREAD

**Issue by slim-bean** [grafana/grafana#28568]
**What happened**:

```
{cluster="us-central1",job="loki-prod/query-frontend"} |= "metrics.go" | logfmt | line_format "dur={{printf \"%-11.11s\" .duration}}\tbytes={{printf \"%-6.6s\" .}}\tthrough={{printf \"%-6.6s\" .throughput_mb}}\tlen={{printf \"%-4.4s\" .length}}\torg={{printf \"%-4.4s\" .org_id}}\t{{.query}}"
```

As an example, if you run this query and then copy and paste the URL from the browser address bar, you are unable to open the link in a new window.

Shortened links also seem broken.

If you close and re-open your browser the window will come up blank.

This also appears to impact the behavior of the back button (not necessarily surprising as the url seems to be involved with the back button operation)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:

master v7.4.0-5409pre (b3ac4eb899)

- Data source type & version:

Loki

- OS Grafana is installed on:
- User OS & Browser:

OS Windows

Firefox: 82.0

Chrome: 86.0.4240.111

- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
Seems like this could be connected to https://github.com/grafana/grafana/issues/28571

**Comment by aocenas** [comment]
Seems like this has to do with how we encode/parse the url with connection to the new logql syntax. In https://github.com/grafana/grafana/blob/ce1f7908c867531745363c1a9a6f70cec485c199/public/app/core/utils/explore.ts#L211 I get error
```
explore.ts:199 URIError: URI malformed
    at decodeURI (<anonymous>)
    at safeParseJson (explore.ts:197)
    at parseUrlState (explore.ts:218)
    at updateChildRefreshState (reducers.ts:536)
    at exploreReducer (reducers.ts:627)
    at combination (redux.js:459)
    at root.ts:51
    at p (<anonymous>:1:36402)
    at v (<anonymous>:1:36684)
    at <anonymous>:1:40069
```
so we do not return anything. The weird thing is that the text there actually isn't encoded anymore and could be just JSON.parsed.

**Comment by slim-bean** [comment]
I'm still seeing this issue in our master build on ops-tools. I came back here to see the status of this ticket, but I think this issue is still present. I can provide an example that recreates it, pls ping me!

**Comment by slim-bean** [comment]
I'm very sorry, I was wrong, the issue was related to my no-script plugin (which was behaving similarly when i first had this issue and I made a poor assumption) Apologies!
