### ISSUE TITLE
Explore: Queries dissapear when interacting with multiple query windows

### ISSUE THREAD

**Issue by slim-bean** [grafana/grafana#28571]
**What happened**:

![dissapearing_labels](https://user-images.githubusercontent.com/10332331/97319792-949b1900-1843-11eb-80a3-4f38399a5cbf.gif)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:

master v7.4.0-5409pre (b3ac4eb899)

- Data source type & version:

prometheus

- OS Grafana is installed on:
- User OS & Browser:

windows

Firefox 82

Does not happen on Chrome

- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
strange bug :)

**Comment by slim-bean** [comment]
indeed :) I was not able to reproduce on chrome either.

Also, hitting the back button returns both queries to their respective windows  ¯\_(ツ)_/¯

**Comment by aocenas** [comment]
I was actually able to reproduce it on chrome/ubuntu right now.
