### ISSUE TITLE
Gotify support as Notification Channel

### ISSUE THREAD

**Issue by Leosirth** [grafana/grafana#28572]
**What would you like to be added**:
I would like to have [Gotify](https://github.com/gotify/server) supported as Notification Channel

**Why is this needed**:
Right now is possible to use Webhook to send alerts to Gotify, but this lack the following features:

-  the possibility to send image (supported by [Markdown](https://gotify.net/docs/msgextras#clientdisplay) in Gotify)

- setting the priority of the alert (used by clients to behave differently):
![image](https://user-images.githubusercontent.com/800911/97319513-426eed80-186d-11eb-8e23-0a4b8eaf3789.png)

- have the possibility to set the following parameters supported by [Gotify](https://gotify.net/docs/)

> A message has the following attributes: content, title, creation date, application id and priority.

**Comment by torkelo** [comment]
Think your best path to support this is to first att support for external notification channel plugins  https://github.com/grafana/grafana/issues/16004 
t
