### ISSUE TITLE
Data source timeout field in config editor

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#28581]
**What would you like to be added**:
This is related to #28580. Any data source plugin (HTTP, SQL, etc) could benefit from a custom timeout that overrides the global timeout (#15054) and defaults to it.

**Why is this needed**:
Some panels are configured to pull in so much data that—currently hardcoded—default timeouts are not long enough.

**Comment by hugohaggmark** [comment]
@stevenvachon friendly reminder to please add labels to your issues so that the person on issue triage doesn't have to

**Comment by smalukav** [comment]
Related to #31871

**Comment by wbrowne** [comment]
Will close as looks to be solved with #31871
