### ISSUE TITLE
Short URL: Cleanup non-visited short URL's

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#28594]
**What would you like to be added**:
A cleanup job for deleting short URL's that haven't been visited.

**Why is this needed**:
Database should not consist of data that's not in use/not needed.

**Additional details**:
Suggestion: Delete all rows in the short_url database table where `last_seen_at` is zero and `created_at` is older than for example 24 hours.  

Ref #28248

**Comment by ivanahuckova** [comment]
> Suggestion: Delete all rows in the short_url database table where last_seen_at is zero and created_at is older than for example 24 hours.

Yes that makes sense! Just wondering if 24 hours isn't too strict. I can imagine sharing the link on slack on friday and the person would want to access it next week. So maybe expanding the time to more hours would make sense. 

Also, we should figure out how long do we want to keep link. E.g. if `last_seen_at` is older than X. But no idea what it should be. Maybe month? Longer? Shorter?

And lastly, do we want to set limit on number of shorten urls. e.g. if we have more than 100 000, delete the one that has  oldest `last_seen_at`. 

+fyi @davkal
