### ISSUE TITLE
Grafana UI Card Component 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#28591]
We did the first pass on a new unified card component that looks very promising. https://github.com/grafana/grafana/pull/28216

But it has a few issues that I think we should explore before start using it more. 

A) Big API

```typescript
export interface Props extends ContainerProps {
  /** Main heading for the Card **/
  heading: ReactNode;
  /** Additional data about the card. If array is supplied, elements will be rendered with vertical line separator */
  metadata?: ReactNode | ReactNode[];
  /** Card description text */
  description?: string;
  /** List of tags to display in the card */
  tags?: string[];
  /** Optional callback for tag onclick event */
  onTagClick?: OnTagClick;
  /** Indicates if the card and all its actions can be interacted with */
  disabled?: boolean;
  /** Image or icon to be displayed on the let side of the card */
  image?: ReactNode;
  /** Main card actions **/
  actions?: ReactElement[];
  /** Right-side actions */
  secondaryActions?: ReactElement[];
  /** Link to redirect to on card click. If provided, the Card inner content will be rendered inside `a` */
  href?: string;
  /** On click handler for the Card */
  onClick?: () => void;
}
```

One thing that stands out to me here is onTagClick feels strange, makes me think tags should be an element like the actions?  

It's kind of messy to use with props that take in element arrays:
```react
 <Card
        heading={<a href={ruleUrl}>{renderText(rule.name)}</a>}
        image={
          <Icon size="xl" name={rule.stateIcon as IconName} className={`alert-rule-item__icon ${rule.stateClass}`} />
        }
        metadata={[
          <span key="state">
            <span key="text" className={`${rule.stateClass}`}>
              {renderText(rule.stateText)}{' '}
            </span>
            for {rule.stateAge}
          </span>,
          rule.info ? renderText(rule.info) : null,
        ]}
        actions={[
          <Button variant="secondary" icon={rule.state === 'paused' ? 'play' : 'pause'} onClick={onTogglePause}>
            {rule.state === 'paused' ? 'Resume' : 'Pause'}
          </Button>,
          <LinkButton variant="secondary" href={ruleUrl} icon="cog">
            Edit alert
          </LinkButton>,
        ]}
      />
````

Originally I thought this design was necessary to fulfill requirements (I made a variant of the card last year that had same API as above). But we are getting more experience using child elements as part of the API instead (in new graph for example). 

Which would open the door for an API like this: 

```jsx
<Card header="Hello">
  <Card.Figure>
    ....
  </Card.Figure>
  <Card.Tags>
   ...
  </Card.Tags>
  <Card.Actions>
    ...
  </Card.Actions>
<Card>
```

The component would have to look for those specific child elements and render them in the correct part of the tree (not use children as you usually do). 

This would make usage of the component read better and clean up API a bit, it would hurt discoverability but if we had good examples in the storybook that should help with that. 

B) Improve responsive layout

Think the new design works great for smaller screens but for wider screens having the actions below makes for really poor use of space. 
![Screenshot from 2020-10-27 12-57-31](https://user-images.githubusercontent.com/10999/97298633-02e7d780-1854-11eb-9d9c-854665dcb670.png)

**Comment by Clarity-89** [comment]
Agree with the API restructuring idea. It would help to simplify the API and delegate the props to the actual components that use them. The UI tweaks will probably need some input from the UX team.
