### ISSUE TITLE
Explore: History seems to update timestamps every time

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#28605]
Looking at the Redux actions it seems like when updating history we update all the timestamps of all the items for some reason:
![Screenshot from 2020-10-28 16-30-17](https://user-images.githubusercontent.com/1014802/97458482-07d38680-193b-11eb-9af5-a15630994f45.png)

**Comment by ivanahuckova** [comment]
I looked into this briefly and I think it is Redux-i related bug. Basically in https://github.com/grafana/grafana/blob/master/public/app/core/utils/explore.ts#L320 we are adding new queries at the beginning. And it moves everything down and in Redux it seems like we have done a bunch of changes, but the change was just adding a new object to the first place in array. Not sure if it has any perf implications.
![Kapture 2020-10-28 at 17 20 24](https://user-images.githubusercontent.com/30407135/97465189-13767b80-1942-11eb-9b94-bef00bb9138e.gif)

**Comment by aocenas** [comment]
Ah ok got it, I did not notice that also the queries changed in the diff (cause I did not expand it) so I thought that the timestamps changed for the same history items. Right now that's expected and should not be an issue, my bad for not looking more closely. Thanks for looking at it.
