### ISSUE TITLE
Dashboard variable fills slow if more than 250k unique values on PostgreSQL (TimescaleDB)

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#28600]
**What happened**: on PostgreSQL (TimescaleDB) dashboard variable fills slow if more than 250k unique values, on InfluxDB there is no problem with same 250k unique values, variable fills without a problem

**What you expected to happen**: dashboard variable fills fast on PostgreSQL (TimescaleDB) even if more than 250k unique values

**How to reproduce it (as minimally and precisely as possible)**: have a PostgreSQL (TimescaleDB) table with column of 250k unique values and try to fill dashboard variable with "select column from table"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.0-beta2
- Data source type & version: PostgreSQL (TimescaleDB)
- OS Grafana is installed on: Debian 9
- User OS & Browser: Windows 10, Chrome 86.0.4240.111
- Grafana plugins: /
- Others: /

**Comment by hugohaggmark** [comment]
Thank you for reporting this @edin008 we'll investigate this closer. In the meantime I would be super glad if you could share your dashboard.json with PostGres and InfluxDb so we can rule out any other issues? Thank you again

**Comment by edin008** [comment]
> Thank you for reporting this @edin008 we'll investigate this closer. In the meantime I would be super glad if you could share your dashboard.json with PostGres and InfluxDb so we can rule out any other issues? Thank you again

I made new dashboard with both datasources. I cannot share full json, here is basic dashboard json with altered names inside. [Variable load InfluxDB vs PostgreSQL.txt](https://github.com/grafana/grafana/files/5453780/Variable.load.InfluxDB.vs.PostgreSQL.txt)

InfluxDB query: show tag values from table with key=value (no problem wih 250k unique values)
PostgreSQL query: select value from table limit 20000 (limit because 250k unique values makes grafana unresponsive, images below.

![image](https://user-images.githubusercontent.com/66313770/97474156-16766980-194c-11eb-8c0c-399a7b35f787.png)
![image](https://user-images.githubusercontent.com/66313770/97474303-43c31780-194c-11eb-9a11-f5dd5e85a39d.png)

**Comment by hugohaggmark** [comment]
Awesome information @edin008, I'll investigate further.

**Comment by hugohaggmark** [comment]
I've managed to repro this and here is the comparision between InfluxDB and Postgres:

__InfluxDB__

623 kB payload:
![image](https://user-images.githubusercontent.com/562238/97582927-9fe27600-19f6-11eb-9e83-d35838c44c91.png)

updateVariableOptions takes 1 second:
![image](https://user-images.githubusercontent.com/562238/97582896-93f6b400-19f6-11eb-9ea3-30abdb6bb3c9.png)

__Postgres__
2.1 MB payload:
![image](https://user-images.githubusercontent.com/562238/97583193-f2bc2d80-19f6-11eb-8412-a43d2cebf012.png)

updateVariableOptions takes 34 seconds:
![image](https://user-images.githubusercontent.com/562238/97583145-e637d500-19f6-11eb-8504-fdbc907caea5.png)

I will continue to investigate why updateVariableOptions takes 33 seconds longer for Postgres

**Comment by hugohaggmark** [comment]
I found the issue on this line:
https://github.com/grafana/grafana/blob/5a83fc574aaf73a8143f921c84dff6a8b59e0549/public/app/plugins/datasource/postgres/response_parser.ts#L76

[Using a Set instead speeds up this operation 33times](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set) to 1 second:

![image](https://user-images.githubusercontent.com/562238/97670327-40cc4200-1a86-11eb-980f-d1ef4fc9a5d6.png)
