### ISSUE TITLE
Alerting: Automatically add tags to alert annotations

### ISSUE THREAD

**Issue by ad-m** [grafana/grafana#28610]
**What would you like to be added**:

I would like automatically add tags to annotations created by alerts. 

Now alerts have tags:

![obraz](https://user-images.githubusercontent.com/3618479/97468723-e330dc00-1945-11eb-95b9-f6e84d16e7f4.png)

What surprised me was that these information are not used as tags for the annotations. As a result, alert annotations are not tagged in any way. Tags is only one way to show cross-dashboard annotation: 
![obraz](https://user-images.githubusercontent.com/3618479/97468938-1d9a7900-1946-11eb-81ea-4a5239498d23.png)

As a result, it is not possible to show alert annotations that are not related to the current dashboard. 

**Why is this needed**:

I would like to show alert annotations that come from a different dashboard (a specialized dashboard for alerts), which requires the annotations to be correctly tagged.

There is #6552, but about alert rule tagging, but I am interested only in auto-tagging annotations created by alert.

**Comment by wbrowne** [comment]
Thanks for creating this issue @ad-m. We're currently doing some rework of Alerts at Grafana and I think this particular problem can be encapsulated in the topic of #6552, therefore I'll close this issue for now

**Comment by positron96** [comment]
@ad-m Hi. I have exact same question - I want to filter annotations by tags from alerts, but it seems that alert tags are not propagated to annotations. Can you tell if you managed to solve your problem? I've read issue 6552, but I don't see how it solves this task.

**Comment by msvechla** [comment]
@wbrowne Can we re-open this issue? Its not a duplicate. 

<img width="492" height="250" alt="Image" src="https://github.com/user-attachments/assets/2b25cc18-07e5-47ec-92ac-00a67236ee12" />

Alert annotations created by Grafana Alerting do not contain any tags. They should contain the same tags as the alert itself.

<img width="1167" height="100" alt="Image" src="https://github.com/user-attachments/assets/6684c1bb-778a-41fa-9b32-004ebf70aa5f" />

As this is a small change, I created a PR here: https://github.com/grafana/grafana/pull/116244
