### ISSUE TITLE
Timepicker parse error?

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#2861]
I want to just have a time range 08:00-now and it works by setting time range: now/d+8h
but it shows a "parse error" in the top right time picker corner, but hte graphs time range do work

![image](https://cloud.githubusercontent.com/assets/12600004/10214266/caae4572-6816-11e5-9677-83f06f1e52c8.png)

**Comment by torkelo** [comment]
thanks for reporting this, fixed
