### ISSUE TITLE
MSSQL data type hierarchyid causes grafana to crash

### ISSUE THREAD

**Issue by ahornercenteredge** [grafana/grafana#28616]
**What happened**:
Using the MSSQL data source. When a query includes a column of type hierarchyid, the data fails to load with error "Failed to fetch." This failure also appears to crash the grafana process as the attached logs show an entry for "Starting Grafana" after the MSSQL connection is initialized for the query.
[grafana.log](https://github.com/grafana/grafana/files/5454206/grafana.log)

```
t=2020-10-28T14:45:48-0400 lvl=dbug msg="Parsing MSSQL URL" logger=tsdb.mssql url=127.0.0.1:14309
t=2020-10-28T14:45:48-0400 lvl=dbug msg="Recognized as ODBC URL format" logger=tsdb.mssql url=127.0.0.1:14309
t=2020-10-28T14:45:48-0400 lvl=dbug msg="Generating connection string" logger=tsdb.mssql url=127.0.0.1:14309 host=127.0.0.1 port=14309
t=2020-10-28T14:45:50-0400 lvl=info msg="Starting Grafana" logger=server version=7.2.2 commit=ad9d408ac2 branch=HEAD compiled=2020-10-21T03:26:59-0400
t=2020-10-28T14:45:50-0400 lvl=info msg="Config loaded from" logger=settings file="C:\\Program Files\\GrafanaLabs\\grafana/conf/defaults.ini"
```

**What you expected to happen**:
I expected to load all columns including the hierarchyid column represented as a string.

**How to reproduce it (as minimally and precisely as possible)**:
Setup an MSSQL database with a table that includes a column of type hierarchyid. Add the MSSQL instance as a datasource and attempt to query the table.

**Anything else we need to know?**:
Definition of the type in Microsoft docs: https://docs.microsoft.com/en-us/sql/t-sql/data-types/hierarchyid-data-type-method-reference?view=sql-server-ver15

**Environment**:
- Grafana version: v7.2.2 (ad9d408ac2)
- Data source type & version: Microsoft SQL Server (Core)
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Windows 10 Pro & Google Chrome (latest)
- Grafana plugins: 
installed plugins:
farski-blendstat-panel [33m@[0m 1.0.2
grafana-clock-panel [33m@[0m 1.1.1
grafana-googlesheets-datasource [33m@[0m 1.0.0
grafana-piechart-panel [33m@[0m 1.6.1
magnesium-wordcloud-panel [33m@[0m 1.1.3
michaeldmoore-multistat-panel [33m@[0m 1.4.1
yesoreyeram-boomtable-panel [33m@[0m 1.4.0
yesoreyeram-boomtheme-panel [33m@[0m 0.1.0

**Comment by marefr** [comment]
I cannot find "Failed to fetch" error in the log file you provided. Can you please specify the whole error log message you're referring to. 

I cannot find anything referring to hierarchyid in https://github.com/denisenkom/go-mssqldb which is the library we're using to connect to MSSQL. Not sure we can help you with this, but depends on what the error message in question is.

**Comment by ahornercenteredge** [comment]
![image](https://user-images.githubusercontent.com/30184296/99082001-98dc6b80-2591-11eb-97d1-2ff1c6dd4b4d.png)
This is where I saw the "failed to fetch" error.

**Comment by marefr** [comment]
I don't find any detailed error in the log you've provided that could be related to your problem so I'll close this as lack of information. When you receive failed to fetch you may be able to use chrome developer tools and the network tab to see the details of the failed request and/or inspect the Grafana server log for information after you've received this error.
