### ISSUE TITLE
Plugins signing: Signed community plug-in displays renderPluginNotice()

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#28628]
**What happened**:
After upgrade to Grafana 7.3 Signed plugin display Unsigned Notice.

![Screen Shot 2020-10-28 at 8 42 51 PM](https://user-images.githubusercontent.com/47795110/97523358-48dd9200-195f-11eb-98ed-8e0f44eeb17f.png)

**What you expected to happen**:
The Notice should not be displayed.

**How to reproduce it (as minimally and precisely as possible)**:

Install `redis-app` plugin.

**Anything else we need to know?**:

@dprokop There is a missing check for signed community plug-ins in renderPluginNotice(): 
```
    if (!plugin) {
      return null;
    }

    if (plugin.meta.signature === PluginSignatureStatus.internal) {
      return null;
    }
```

**Environment**:
- Grafana version: Grafana 7.3
- Data source type & version: App 1.0.1
- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins: Redis-app
- Others:

**Comment by hugohaggmark** [comment]
Confirmed on Grafana v7.4.0-pre (4301121b9d)

**Comment by aknuds1** [comment]
This is related to @wbrowne's recent work, right?

**Comment by hugohaggmark** [comment]
Yes, and @dprokop's work

**Comment by dprokop** [comment]
On it in a bit. It's ok the notice is there, but the copy is wrong

**Comment by hugohaggmark** [comment]
@dprokop also have a look at #28629
