### ISSUE TITLE
Docs: Docs for elasticsearch query editor

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2862]

**Comment by gsaray101** [comment]
Hi Torkel,

When in elasticsearch data source coming to Grafana?

**Comment by torkelo** [comment]
@gsaray101 in version 2.5  (beta soon, pre release builds are available on the builds page), http://grafana.org/download/builds.html

**Comment by bobrik** [comment]
@torkelo how soon is soon? :)
