### ISSUE TITLE
Grafana alert not send message resolved when state change to status OK

### ISSUE THREAD

**Issue by nittayakaiyang** [grafana/grafana#28630]
****What happened:**
Hi! Grafana Team I'm using Line notification. When state change to alerting, notification can be sent but when state change to OK, I cannot receive resolve message. In state history tab I can see every state change and I see state change to OK not No Data
I make sure Uncheck Disable Resolve Massage

****What you expected to happen**:**
When the state change from alerting to OK, I receive notification work fine.

****How to reproduce it (as minimally and precisely as possible)**:**
I don't know it

****Anything else we need to know?**:**
**My alerting configulation and log is below**
**My Alert configulation**
Evaluate every 1m For 1m
WHEN last() OF query(A, 1m, now) IS ABOVE 1
If no data or all values are null SET STATE TO **No Data**
If execution error or timeout SET STATE TO **Alerting**

**MY Configulation on Notification Channel**
Default (send on all alerts): Check
Include image: Uncheck
Disable Resolve Message: Uncheck
Send reminders: Uncheck

_Time 2020-10-28T22:29:30+0700 I received message alert but Time 2020-10-28T22:36:30+0700, I didn't receive resolve message ._
**My log change state**
t=2020-10-28T22:28:30+0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=19 newState=pending prev state=ok
t=2020-10-28T22:29:30+0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=19 newState=alerting prev state=pending
t=2020-10-28T22:29:30+0700 lvl=info msg="Executing line notification" logger=alerting.notifier.line ruleId=19 notification=MY_Line_Noti
t=2020-10-28T22:29:30+0700 lvl=info msg="Creating Line notify" logger=alerting.notifier.line ruleId=19 notification=MY_Line_Noti
t=2020-10-28T22:36:30+0700 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=19 newState=ok prev state=alerting
t=2020-10-28T22:36:30+0700 lvl=info msg="Executing line notification" logger=alerting.notifier.line ruleId=19 notification=MY_Line_Noti

****Environment**:**
- Grafana version: Grafana v6.5.2 (742d165)
- Data source type & version: Prometheus v2.11.1
- OS Grafana is installed on: RHEL 7.7
- User OS & Browser: Windows10 and Chrome Browser
- Grafana plugins: -
- Others: Alert to Line

Thank You for your support 

![grafana_graph](https://user-images.githubusercontent.com/58244064/97527899-02c81300-19df-11eb-8563-cd72918db556.JPG)
![Notification Setting](https://user-images.githubusercontent.com/58244064/97527908-078cc700-19df-11eb-9061-4dbd058e5d31.png)
![state history](https://user-images.githubusercontent.com/58244064/97527918-0bb8e480-19df-11eb-9ffc-f9659fb234e9.JPG)

**Comment by hugohaggmark** [comment]
/duplicate #12781
@nittayakaiyang this issue seems to be fixed in https://github.com/grafana/grafana/pull/27639
