### ISSUE TITLE
Explore search UX: buggy cursor behaviour (2)

### ISSUE THREAD

**Issue by Diggsey** [grafana/grafana#28649]
![grafana_issue2](https://user-images.githubusercontent.com/451321/97574609-694f3000-19e3-11eb-9312-7347fc92510f.gif)

**What happened**:
Mouse pointer switches to an IBeam outside of the textbox's clickable area.

**What you expected to happen**:
The IBeam is supposed to give visual feedback for when you can select text. If the cursor is an IBeam then clicking should focus the textbox, and cause the text cursor to jump to the location of the mouse pointer.

**How to reproduce it (as minimally and precisely as possible)**:
Click near the border of the textbox.

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Loki
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None

**Comment by ivanahuckova** [comment]
@Diggsey I was able to reproduce this. I have added this issue to the Editor project and we will probably look at it soon.

**Comment by Diggsey** [comment]
Thanks 👍
