### ISSUE TITLE
UI  interface hung/busy/high download volume when using group by terms with elasticsearch

### ISSUE THREAD

**Issue by de1150423** [grafana/grafana#28650]
**What happened**:
We experience in some scenarios when using elasticsearch datasource high data download volumes (40mb/s over vpn) when adding a group by term. The UI is unresponsive during  that time and we receive multiple times suggestions regarding the term. Even if you click on one selected item (i.e. agent.hostname) we get at least 2 or 3 following suggestions. 

**What you expected to happen**:
When we setup a query and add a group by term we expect that it returns quickly the suggested fields without freezing up the UI. we expect that we get 1 suggestion and not multiple time after time. 

**How to reproduce it (as minimally and precisely as possible)**:
1.) Create a new graph
2.) Create query for elasticsearch metricbeat or filebeat  as sources. Narrow down the search criteria to only a small subset of data ... like a single host (agent.hostname: <value> or host.name: <value>).
3.) Add Group by Term : host.name (experience delay and unresponsiveness)
4.) select yellow suggestions for host.name  (experience delay and unresponsiveness)
5.) select yellow suggestions for host.name  (experience delay and unresponsiveness)
6.) select yellow suggestions for host.name  (experience delay and unresponsiveness)
7.) save graph  
8.) change term or settings  (experience delay and unresponsiveness)

**Anything else we need to know?**:
we have read up on previous issue and have found similar issues that should have been fixed in earlier versions. Those have been related to the min doc settings = 1 instead of 0. 

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: Elasticsearch 6.x 
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Windows 10 / Chrome or Firefox
- Grafana plugins: default plugins 
- Others:

**Comment by gdub** [comment]
Related, fixed issue: #8321

**Comment by Elfo404** [comment]
closing this as I wasn't able to reproduce the described unresponsiveness, could you try this out on a newer version and see if it still happens?
