### ISSUE TITLE
Explore search UX: Ctrl + Shift + Z does not redo

### ISSUE THREAD

**Issue by Diggsey** [grafana/grafana#28658]
**What happened**:
Pressed `Ctrl + Shift + Z`. Nothing happened.

**What you expected to happen**:
`Ctrl + Shift + Z` should behave the same as `Ctrl + Y` as both are shortcuts for redo. Both shortcuts work in normal textboxes.

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Loki
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None

**Comment by zoltanbedi** [comment]
This is a "bug" in slate editor. it doesn't have this hotkey there we should upgrade slate-hotkeys package to latest to resolve this issue.

**Comment by Elfo404** [comment]
@ivanahuckova did https://github.com/grafana/slate/pull/2 fix this? can we close it?

**Comment by ivanahuckova** [comment]
It was merged but it is too much work to publish modified slate-hotkeys package and then change the dependency in slate-react and then publish it again for this small fix. So it isn't fixed.

**Comment by gabor** [comment]
this will get fixed when we do https://github.com/grafana/grafana/issues/44985
