### ISSUE TITLE
Feature: support milliseconds when using openTSDB datasource

### ISSUE THREAD

**Issue by tomcfoglio** [grafana/grafana#2865]
Is there a way to make grafana query openTSDB using ms? If not is, is it on your roadmap?

on it's HTTP query API openTSDB has the "msResolution" parameter (which I believe Grafana does not use).

Looking at Grafana source I found this:

grafana/public/app/plugins/datasource/opentsdb/datasource.js - line 197

_.each(md.dps, function (v, k) {
        dps.push([v, k * 1000]);
      });

If I am not mistaken Grafana is converting openSTDB timestamps from seconds to ms. Instead of forcing the conversion a setting parameter could be added to the datasource (maybe).

**Comment by torkelo** [comment]
if it supports ms, grafana can use that instead.

**Comment by utkarshcmu** [comment]
+1

**Comment by utkarshcmu** [comment]
Please review and if it looks good then it can be merged. :)

**Comment by utkarshcmu** [comment]
Here are some screenshots showing how #3124 is implemented:

User has to enable millisecond resolution at the datasource level as shown below, by default it is turned off, also user can turn it off whenever they want to:

<img width="740" alt="screen shot 2015-11-23 at 10 52 29 pm" src="https://cloud.githubusercontent.com/assets/1019609/11359932/4c3d4820-9235-11e5-9b9d-af56c108bc2c.png">

Once the datasource has millisecond resolution flag enabled, he can see graphs with millisecond precision:

<img width="1080" alt="screen shot 2015-11-23 at 10 57 53 pm" src="https://cloud.githubusercontent.com/assets/1019609/11359997/ba4ee2c4-9235-11e5-9a69-850b2b1e129c.png">

Once user disables the millisecond resolution flag from the datasource settings, he will again go back to the default resolution (seconds) and the data is shown back in seconds:

<img width="601" alt="screen shot 2015-11-23 at 11 01 05 pm" src="https://cloud.githubusercontent.com/assets/1019609/11360061/2270f34c-9236-11e5-9b3d-59b77c169d6a.png">

**The best part is that this setting can be toggled depending on the need of the resolution**
