### ISSUE TITLE
Query editor: Selecting from dropdown button should not clear the undo history of the textbox

### ISSUE THREAD

**Issue by Diggsey** [grafana/grafana#28653]
![image](https://user-images.githubusercontent.com/451321/97577183-fba50300-19e6-11eb-90ff-e832d3f18aea.png)

**What happened**:
Selecting a label from the dropdown will clear the undo history of the textbox.

**What you expected to happen**:
Selecting a label should be equivalent to typing into the textbox: ie. it should extend the undo history. Pressing ctrl+Z should recover the previous query.

**How to reproduce it (as minimally and precisely as possible)**:
Change the label via the dropdown. Attempt to undo.

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Loki
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: None

**Comment by ivanahuckova** [comment]
@Diggsey our plan is to spend more time on improving query editor experience. I have added this issue to the Editor project and we will probably look at it soon.

**Comment by ivanahuckova** [comment]
This is fixed by new Monaco editor.
