### ISSUE TITLE
Change the delimiter for multi-value selection in templating 

### ISSUE THREAD

**Issue by ivarmedi** [grafana/grafana#2866]
RIght now the templating function generates a text with a '+' delimiter based on the selections made in the dropdown:

```
"templating": {
    "list": [
      {
        "allFormat": "regex wildcard",
        "current": {
          "tags": [],
          "text": "memcache1:11211 + memcache2:11211",        <------
          "value": [
            "memcache1:11211",
            "memcache2:11211"
          ]
        },
[...]
```

It would be nice to be able to change ` + ` to `|` for example, to make it work with the Prometheus datasource.

**Comment by torkelo** [comment]
there is a pipe all & multi format already

**Comment by torkelo** [comment]
its in master (new for upcoming v2.5 release)
