### ISSUE TITLE
No data displayed when zooming in and using fill(previous)

### ISSUE THREAD

**Issue by jeroenst** [grafana/grafana#28665]
**What happened**:
When I zoom in in a graph, data points disappear because there are no values in the database in the shown time window which is correct.
But also when I add the fill(previous) function to the query no data is shown.

**What you expected to happen**:
When I zoom in and use fill(previous) I would expect to see a line generated from a value even when it's written to the database before the beginning of the graph.

The WHERE $timeFilter is prohibiting the query returning any results.

To overcome this issue I already made this query:
select value from (SELECT last("value") as value FROM "autogen"."livingroom.setpoint" WHERE $timeFilter GROUP BY time($__interval) fill(previous)),(SELECT last("value") as value FROM "autogen"."livingroom.setpoint")

This query returns the correct result, but because the time is outside (before) the graph time range, the line is not shown, although the legend shows the name and the value.

Setpoint values, which change not very often, suffer the most of this issue.

I could however do an insert of the same value every second to the database so graph will be correct but the database will grow although no new information is available. My iot devices only report values at startup and when values change to prevent network and database flooding.

If the line would be displayed, my issue is solved although I would like to have this in the gui options instead of creating a query manually for each graph.

**How to reproduce it (as minimally and precisely as possible)**:
Create a graph with fill(previous) or adapt my select statement and use a datasource with data points only before the time window of the graph.

**Anything else we need to know?**:
I don't know if this is a bug or a feature request, and I also couldn't find any bug related to this problem. So I'm sorry if this issue is duplicate or in the wrong section.

**Environment**:
- Grafana version: 7.3.0
- Data source type & version: influxdb 1.6.4
- OS Grafana is installed on: linux mint 20
- User OS & Browser: ubuntu 20.04 chrome
- Grafana plugins: -
- Others: -

**Comment by hugohaggmark** [comment]
Hi @jeroenst, do I understand this correctly that you want to zoom in on a graph where there are no values except for the filled values?

**Comment by jeroenst** [comment]
@hugohaggmark yes this is correct.

I also heard that more people and even a company (1000+ employees) would like this feature.

**Comment by jeroenst** [comment]
Here you have an example what's going wrong.

![download](https://user-images.githubusercontent.com/2833940/97672788-ee415480-1a8a-11eb-8d39-24b7e307249e.png)

**Comment by jeroenst** [comment]
Is there any news on this?

**Comment by hugohaggmark** [comment]
@jeroenst back from holidays, no news so far though. Leaving this open and let's wait for more feedback from the community.

**Comment by torkelo** [comment]
This seems like an InfluxDB issue that cannot be solved in Grafana, fill previous only work if there is a data point within time range.

**Comment by jeroenst** [comment]
> This seems like an InfluxDB issue that cannot be solved in Grafana, fill previous only work if there is a data point within time range.

No its not, see my previous comments and please reopen this issue.

Grafana doesn't plot a line even when there is a datapoint in the past, see the query I adapted.

**Comment by marijneken** [comment]
I'm very new to Grafana (as in just installed it 2 days ago). And I already ran into this issue. My (naive) expectation was that if I zoomed into a graph, I would in fact, see a zoomed in version of what I saw before when zoomed out. Wouldn't that be very logical?
It looks like the fill(previous) function is fully capable of filling the value to the right (in the future) of the graph. When I toggle it, I see it draws a little horizontal line from the last point to the current time. I see no reason why it couldn't do so for the past. Even without a data point.
Like I said, I'm coming from this with no experience of how this is supposed to work. Just with what I think almost everyone would expect.

**Comment by andrey-skat** [comment]
+1, I have data outside time interval, but grafana only uses it, if it is in the current time frame.

**Comment by Rolandwalraven** [comment]
+1, I experience the same problem. Especially with setpoint's which can be unchanged for days.

**Comment by jeroenst** [comment]
@torkelo this affects multiple users, please reopen.

Thank you.

**Comment by torkelo** [comment]
There is no easy solution, this is how Grafana always worked. You query for the time range you select , if the query does not return the datapoints for that zoomed in time range no lines will be drawn.

We might add a new zoom mode I the future where you can zoom in without issuing a new query (so just see same data but with different time range)

**Comment by jeroenst** [comment]
Maybe it's an easy solution to make first datapoint in graph the first datapoint of the query when no data for that specific time is available?

Maybe this even solves https://github.com/grafana/grafana/issues/30200 and https://github.com/grafana/grafana/issues/29858 because it wouldn't surprise me if this is caused for the same reason.

**Comment by torkelo** [comment]
> Maybe it's an easy solution to make first datapoint in graph the first datapoint of the query when no data for that specific time is available?

first data point in query? not sure what you mean, the problem is that the query does return this data point it's not there

**Comment by andrey-skat** [comment]
@torkelo I found many similar issues on home assistant forum. They try to make workarounds, but I think it's a presentation problem, not data. Even simple built-in graphs from home assistant dashboard do not have this issue.

Maybe there should be an option to make another request to get the last data point from outside of the time interval?

Also similar issue exists for future data. In that case, I think, option to use last data point to fill future data may be helpful.

**Comment by jeroenst** [comment]
> > Maybe it's an easy solution to make first datapoint in graph the first datapoint of the query when no data for that specific time is available?
> 
> first data point in query? not sure what you mean, the problem is that the query does return this data point it's not there

In My adapted query the datapoint is there. See my first post.

**Comment by marijneken** [comment]
> @torkelo I found many similar issues on home assistant forum. They try to make workarounds, but I think it's a presentation problem, not data. Even simple built-in graphs from home assistant dashboard do not have this issue.

Exactly my thought. To me this is a presentation problem. The fact that there is not previous data point shouldn't matter. The function is called "fill(previous)". So in my mind, that would "fill" the missing data with "previous" data. And by that I mean in the visual presentation, not the actual data. It's as simple as holding the value, right?

> Also similar issue exists for future data. In that case, I think, option to use last data point to fill future data may be helpful.

From what I've seen, the fill(previous) function actually already does this. Or am I mistaken? I thought for sure that I saw it draw a horizontal line into the future, past my last data point. Because of this, I was even more confused why it wouldn't do the same for the past.

**Comment by andrey-skat** [comment]
> > Also similar issue exists for future data. In that case, I think, option to use last data point to fill future data may be helpful.
> 
> From what I've seen, the fill(previous) function actually already does this. Or am I mistaken? I thought for sure that I saw it draw a horizontal line into the future, past my last data point. Because of this, I was even more confused why it wouldn't do the same for the past.

Right now one of my graphs show this :)

![image](https://user-images.githubusercontent.com/1966129/104335724-ba5fc200-5504-11eb-8ea3-4ffb4e59f5a9.png)

**Comment by torkelo** [comment]
Maybe if your using flux you can timeshift the query a bit to include data from before the selected time window?

**Comment by andrey-skat** [comment]
> Maybe if your using flux you can timeshift the query a bit to include data from before the selected time window?

But it will be a different shift every time for every graph? Also, I don't want to extend the interval itself, if I select 6 hours interval, I expect to see only 6 hours.

**Comment by torkelo** [comment]
>  Also, I don't want to extend the interval itself, if I select 6 hours interval, I expect to see only 6 hours.

yea but your asking InfluxDB to return a data point outside the time range, then you need to extend the range

**Comment by andrey-skat** [comment]
> > Also, I don't want to extend the interval itself, if I select 6 hours interval, I expect to see only 6 hours.
> 
> yea but your asking InfluxDB to return a data point outside the time range, then you need to extend the range

And this is the presentation issue we are talking about :)

When I use the option `fill(previous)` I want grafana to take previous data even it outside the time range. In the case of Home Assistant + InfluxDB, HA sends data only if it changed. So if the data point doesn't exist in the current interval, it means, that data didn't change and the current value is equal last data point in the previous interval. 

And we are asking about the improvement of `fill(previous)` feature, which will make another query for the latest data point outside time interval to fill missing values correctly :)

**Comment by jeroenst** [comment]
@torkelo do you have enough information to investigate and solve this problem?

**Comment by torkelo** [comment]
It's an influxdb issue, nothing Grafana can do.

> The function is called "fill(previous)". So in my mind, that would "fill" the missing data with "previous" data.

Fill function is executed in the influxdb query layer. If you think it's not working as you think then report issue to influxdb

**Comment by jeroenst** [comment]
So influx db is returning a value for every point in the graph between the values to create a line in the graph, instead that grafana draws a line between 2 values?

**Comment by torkelo** [comment]
> So influx db is returning a value for every point in the graph between the values to create a line in the graph

Yes. It takes 2 data points for a line.

> instead that grafana draws a line between 2 values?

?? Not sure I understand the question.

**Comment by jeroenst** [comment]
Forget my last question, it's not relevant. I found a feature request for this problem on the influx bugtracker:

https://github.com/influxdata/influxdb/issues/6878

**Comment by bburns** [comment]
I had the same problem with Postgres and the discrete graph plugin - zoom in too much and there's no data on the left side. So made a union query that added in the data on the left edge - 

```sql

-- this union query gets the regular data for the graph,
-- then tacks on the value for the left edge.

-- first define some variables
WITH
  -- the left edge of the graph
  starttime AS (VALUES (to_timestamp(cast(${__from}/1000 as bigint))::timestamp)),
  -- the history view path
  pathvar AS (VALUES ('availability'))
-- select time, value from a subquery
-- (done so can have a single point where need the value name)
SELECT time, value AS "Availability" FROM (
  -- first a straightforward query for time and value for the 
  -- given device, path, and timestamp
  SELECT time, value
  FROM history_text
  WHERE
    device = 'Line$line' and
    path = (table pathvar) and -- references the pathvar variable
    $__timeFilter("time")
  -- now tack on the time and value for the left edge	with a UNION query
  UNION
  SELECT time, value FROM
    -- need this subquery so can order the results by time descending,
    -- so can get the last value before the left edge.
    (SELECT
      (table starttime) as time, -- references the starttime variable
      value
    FROM history_text
    WHERE
      device = 'Line$line' and
      path = (table pathvar) and
      time < (table starttime)
    ORDER BY history_text.time desc
    LIMIT 1
    ) AS subquery1 -- name is required but not used
ORDER BY time
) AS subquery2
```

**Comment by bauermww** [comment]
> I had the same problem with Postgres and the discrete graph plugin - zoom in too much and there's no data on the left side. So made a union query that added in the data on the left edge -
> 
> ```sql
> -- this union query gets the regular data for the graph,
> -- then tacks on the value for the left edge.
> 
> -- first define some variables
> WITH
>   -- the left edge of the graph
>   starttime AS (VALUES (to_timestamp(cast(${__from}/1000 as bigint))::timestamp)),
>   -- the history view path
>   pathvar AS (VALUES ('availability'))
> -- select time, value from a subquery
> -- (done so can have a single point where need the value name)
> SELECT time, value AS "Availability" FROM (
>   -- first a straightforward query for time and value for the 
>   -- given device, path, and timestamp
>   SELECT time, value
>   FROM history_text
>   WHERE
>     device = 'Line$line' and
>     path = (table pathvar) and -- references the pathvar variable
>     $__timeFilter("time")
>   -- now tack on the time and value for the left edge	with a UNION query
>   UNION
>   SELECT time, value FROM
>     -- need this subquery so can order the results by time descending,
>     -- so can get the last value before the left edge.
>     (SELECT
>       (table starttime) as time, -- references the starttime variable
>       value
>     FROM history_text
>     WHERE
>       device = 'Line$line' and
>       path = (table pathvar) and
>       time < (table starttime)
>     ORDER BY history_text.time desc
>     LIMIT 1
>     ) AS subquery1 -- name is required but not used
> ORDER BY time
> ) AS subquery2
> ```

Hello bburns, 
I'm new with Grafana and Influxdb.
Can you post an example how the query in Grafana msut look like with your work arround.
My default query is 

SELECT last("value") FROM "state" WHERE ("entity_id" = 'v0_0') AND $timeFilter GROUP BY time($__interval) fill(previous)

I can not get it up and running.
Thank's for your help
Matthias

**Comment by bburns** [comment]
> Hello bburns, I'm new with Grafana and Influxdb. Can you post an example how the query in Grafana msut look like with your work arround. My default query is
> 
> SELECT last("value") FROM "state" WHERE ("entity_id" = 'v0_0') AND $timeFilter GROUP BY time($__interval) fill(previous)
> 
> I can not get it up and running. Thank's for your help Matthias

Hi - sorry, I'm not familiar with Influxdb - the syntax is different than Postgres.

And regarding my previous code, I wasn't familiar with the LAG function, but that might be better/simpler than doing a UNION query.

**Comment by jrc** [comment]
> I had the same problem with Postgres and the discrete graph plugin - zoom in too much and there's no data on the left side. So made a union query that added in the data on the left edge -

Thanks @bburns, that was exactly what I needed!!

FWIW, I was able to write the second SELECT like this:

```
SELECT
  [deleted]
-- Carry last value forward to left edge
-- Based on https://github.com/grafana/grafana/issues/28665#issuecomment-955752544
UNION
(SELECT
  $__timeFrom()::timestamp AS "time",
  [deleted]
FROM metrics
WHERE
  time < $__timeFrom()::timestamp AND
  [deleted]
ORDER BY metrics."time" DESC
LIMIT 1)
```

**Comment by ocervinka** [comment]
I work around this issue by querying Influx DB for data in a time range wider than Grafana would normally do.

```
SELECT last(temperature) FROM state WHERE entity_id = 'trv_kitchen' AND time >= '${__from:date}' - 24h GROUP BY time($__interval) fill(previous)
```

When you select a time range in Grafana e.g.  "Last 4 hours" it fetches 4h + 24h of data which is enough to pick up changes in my sparse data from Home Assistant to draw a full graph (from very left to right) even when the selected time range has just a few or no data points.

It's a very simple workaround as it uses the usual single query and only replaces `$timeFilter` by `time >= '${__from:date}' - 24h` or similar.
