### ISSUE TITLE
Add field from calculation transformation not working on Cloudwatch Datasources since 7.3

### ISSUE THREAD

**Issue by Bio2hazard** [grafana/grafana#28678]
**What happened**:
Add field from calculation transformation no longer aggregates series correctly when using cloudwatch as a datasource.

**What you expected to happen**:
Add field from calculation is expected to work on cloudwatch as it does on other datasources and prior to 7.3.

**How to reproduce it (as minimally and precisely as possible)**:
Add any cloudwatch metrics query with 2 or more stats, or add more than 1 cloudwatch metrics query.
Go to Transform Tab > add a Add field from calculation transformation.

![field_from_calculation_grafana_bug](https://user-images.githubusercontent.com/2462038/97633534-7b37cf80-19f1-11eb-9d6c-42ebb8d71700.gif)

**Anything else we need to know?**:
I assume it is related to the data frame changes as it seems to treat everything as unique data frames.

**Environment**:
- Grafana version: Grafana Enterprise v7.3.0 (bf8837f6f8)
- Data source type & version: Cloudwatch built-in
- OS Grafana is installed on: Docker / ECS
- User OS & Browser: Windows 10, Firefox 82.0.2
- Grafana plugins: dozens of other plugins working OK
- Others:

**Comment by aknuds1** [comment]
I'm having a look.

**Comment by aknuds1** [comment]
I think I can reproduce the issue, looking into it.

**Comment by torkelo** [comment]
Try 7.3.1, related to this issue https://github.com/grafana/grafana/issues/28301

**Comment by Bio2hazard** [comment]
@torkelo I tested with both the 7.4 beta and now with Grafana v7.3.1 (6668161a88) and the Add field from calculation transformation still exhibits this bug. Please re-open.

**Comment by ethirolle** [comment]
Re-opening this issue on behalf of @Bio2hazard and @davidnewhall, per the above comment (+ support ticket [18358](https://grafana.zendesk.com/agent/tickets/18358))

**Comment by torkelo** [comment]
Very strange, unable to replicate this

**Comment by torkelo** [comment]
will try more

**Comment by aknuds1** [comment]
I think I could reproduce the issue @torkelo. I saw a clear difference between v7.2.2 and master.

**Comment by torkelo** [comment]
If you can replicate can you show the result in table format pre & post adding the transform ?

**Comment by aknuds1** [comment]
@torkelo I will try.

**Comment by aknuds1** [comment]
@torkelo Here are my screenshots of version 7.2.2 versus master.

## Version 7.2.2 without transform
![screenshot-pre-7 2 2](https://user-images.githubusercontent.com/281303/97888277-472f1800-1d2b-11eb-8b18-b4443a06a06b.png)

## Version 7.2.2 with transform
![screenshot-post-7 2 2](https://user-images.githubusercontent.com/281303/97888276-46968180-1d2b-11eb-9fa7-3a20bb786f52.png)

## Master revision without transform
![screenshot-pre-master](https://user-images.githubusercontent.com/281303/97888273-45655480-1d2b-11eb-8744-ca64688df934.png)

## Master revision with transform
![screenshot-post-master](https://user-images.githubusercontent.com/281303/97888275-46968180-1d2b-11eb-9e1f-ef58105ae420.png)

**Comment by torkelo** [comment]
@aknuds1 thanks for that! unable to replicate still 

Without any transformations added can you copy the raw data frame structure from the inspector / JSON / DataFrame 

![Screenshot from 2020-11-02 18-39-44](https://user-images.githubusercontent.com/10999/97900348-cf68e980-1d3a-11eb-8d30-a8de97653c37.png)
