### ISSUE TITLE
Gauge panel metric font colour

### ISSUE THREAD

**Issue by trueuto** [grafana/grafana#28673]
**What would you like to be added**: Possibility to have font colour of the metric value on the Gauge set to a single colour ('static') and not reflecting the threshold's colour. Make the possibility for the Gauge panel to look similarly to how the old Singlestat panel looked like.

**Why is this needed**: To provide better visibility/readibility of the dashboard with many Gauges. 

How Gauge panel looks like:
![Gauge](https://user-images.githubusercontent.com/49986151/97611210-25c1e980-1a16-11eb-96e1-ac1d8484761d.png)

How I would like to make it look like:
![Singlestat-gauge](https://user-images.githubusercontent.com/49986151/97611212-26f31680-1a16-11eb-89f1-2b818133a7f8.png)

**Comment by hugohaggmark** [comment]
I think this might be a duplicate but I can't seem to find it, do you remember @torkelo?

**Comment by trueuto** [comment]
I have been looking for similar report prior to posting this one but could
not find anything related.

pt., 30 paź 2020, 06:39 użytkownik Hugo Häggmark <notifications@github.com>
napisał:

**Comment by trueuto** [comment]
Hi,

are there any news regarding the case?

Regards
trueuto

**Comment by oscarkilhed** [comment]
Duplicate of #12507
