### ISSUE TITLE
Prometheus query entry deletes parts of query under certain conditions

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#28677]
**What happened**:
In #28675, I mentioned a class of issues where switching between queries would delete text. After some experimenting, I've found a somewhat reliable way to reproduce this.

**What you expected to happen**:
Selecting a different entry should not delete parts of your query.

**How to reproduce it (as minimally and precisely as possible)**:
These are the basic steps:
 - Create a new panel
 - Type arbitrary characters into the query entry
 - Select a portion of the query with your mouse by clicking, dragging and releasing. Then select another entry, such as "legend format"
 - Alternatively, start with the cursor in the "legend format" entry and select a part of the query

However, it is inconsistent. The following things seem to help:
 - making the query longer
 - adding many queries to the panel
 - switching focus or performing the selection while the "Loading Metrics..." text appears on the left.
 - releasing the mouse button to confirm the selection while the mouse is outside of the entry

**Anything else we need to know?**:
 - Under Firefox, this deletion can be undone with `ctrl-z`, which does not work under chrome. However, it will re-delete itself when the entry is deselected.
 - These steps might seem weird, but this happens a lot when you are fast and click on things while they still resize under you.

**Environment**:
- Grafana version: 7.3.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian/Ubuntu
- User OS & Browser: Debian/Fedora, Chrome/Firefox
- Grafana plugins: N/A
- Others: N/A

-----------
GIF courtesy of @jsedy7:

![bug demonstration gif](https://user-images.githubusercontent.com/8748774/97670753-3199c400-1a87-11eb-8c4a-905e70dbfa51.gif)

**Comment by hugohaggmark** [comment]
Hi again @NotAFile, so is this issue an replacement of #28675 or is it another bug?

**Comment by jsedy7** [comment]
Hello, I think that only complements previous problem. I have same problem.

**Comment by hugohaggmark** [comment]
I understand that, but it makes it a lot harder for us as maintainers of Grafana if issues are almost the same. Maybe @NotAFile can combine these two into the same issue?

**Comment by jsedy7** [comment]
> I understand that, but it makes it a lot harder for us as maintainers of Grafana if issues are almost the same. Maybe @NotAFile can combine these two into the same issue?

I understand and I'm sorry. I think, that should be this issue closed for duplication reason and used first one.

**Comment by NotAFile** [comment]
> Hi again @NotAFile, so is this issue an replacement of #28675 or is it another bug?

This issue contains the reproduction steps for occasionally deleting parts of the query text. The other issue contains reproduction steps for the cursor jumping unintentionally.

I can't say if they're the same issue on a technical level, but they require significantly different steps to create and have significantly different results.

**Comment by hugohaggmark** [comment]
Thank you for clarifying @NotAFile and @jsedy7 will keep both then.

**Comment by NotAFile** [comment]
A gif demonstrating this behavior was posted on another issue, linking it here so it doesn't get lost:

https://github.com/grafana/grafana/issues/28675#issuecomment-719329670

**Comment by zoltanbedi** [comment]
@NotAFile can you please try with latest master if this pr fixed this issue as well? https://github.com/grafana/grafana/pull/28622

**Comment by zoltanbedi** [comment]
Im going to close this as fixed in #28622, let us know if it is not the case and we can reopen this issue.

**Comment by NotAFile** [comment]
I didn't get to try master, but I can confirm I am no long able to reproduce this under the fresh 7.3.2 release. Thanks a lot!

**Comment by zoltanbedi** [comment]
Thanks for confirming!

**Comment by dandua98** [comment]
I can consistently reproduce this as recently as v7.5.1, steps to reproduce:

- Open the edit view for an existing panel
- Select a part of the query for the panel from the query editor, **before** the metrics have loaded, i.e it should say "Loading metrics..." on the tab to the side of the query editor (see image below). This will be easier to reproduce on a larger source where loading metrics would take a few moments.
![image](https://user-images.githubusercontent.com/24802378/127256061-934e406a-29e4-4574-8eb6-80938151d909.png)
- Once metrics have loaded, the previously selected portion of the query will be deleted
