### ISSUE TITLE
Nightly RPM's not RPM's?

### ISSUE THREAD

**Issue by kvesterling** [grafana/grafana#2868]
-bash-4.1$ rpm -Uvh grafana-2.5.0-pre1.x86_64.rpm
error: grafana-2.5.0-pre1.x86_64.rpm: not an rpm package (or package manifest): 
-bash-4.1$ 

Seems that a number of them are corrupted/unusable...

Meanwhile the .deb packages just work! (big smiles!)

**Comment by robison** [comment]
I'd suggest taking another look at your download. I'm able to examine/install it without issues.

robbie@host:~$ rpm -qip grafana-2.5.0-pre1.x86_64.rpm
warning: grafana-2.5.0-pre1.x86_64.rpm: Header V4 RSA/SHA1 Signature, key ID 3dd18bdd: NOKEY
Name        : grafana                      Relocations: /
Version     : 2.5.0                             Vendor: Grafana
Release     : pre1                          Build Date: Thu 01 Oct 2015 02:43:14 PM UTC
Install Date: (not installed)               Build Host: b90a256630a7
Group       : default                       Source RPM: grafana-2.5.0-pre1.src.rpm
Size        : 66034954                         License: Apache 2.0
Signature   : RSA/SHA1, Thu 01 Oct 2015 02:43:29 PM UTC, Key ID 30a3d7723dd18bdd
Packager    : contact@grafana.org
URL         : http://grafana.org
Summary     : Grafana
Description :
Grafana
robbie@host:~$
