### ISSUE TITLE
Query editor combo box (Select) pops upwards and underneath graph component

### ISSUE THREAD

**Issue by prichards-wmko** [grafana/grafana#28683]
Environment:
Grafana 7.3
Data source: custom back-end data source, https://github.com/KeckObservatory/epics-grafana-datasource
OS: CentOS 7
User OS/browser: Chrome 83

When a combo box("Select" component) in the query parameters has many entries, clicking on it will sometimes make it pop upwards (vs downwards).  The component Z order is apparently underneath the graph itself, obscuring the top of the combo box.

My QueryEditor.tsx specifies the combo this way:

        <div className="gf-form-inline" style={{ marginTop: 8 }}>
          <InlineFormLabel width={10} className="convert-units" tooltip={<p>Convert units.</p>}>
            Units conversion
          </InlineFormLabel>
          <Select
            width={30}
            placeholder={'(none)'}
            defaultValue={0}
            options={this.unitConversionOptions}
            value={query.unitConversion}
            allowCustomValue={false}
            onChange={this.onUnitConversionChange}
          />
        </div>

![combo pop under](https://user-images.githubusercontent.com/40406449/97652074-ad512d80-1a01-11eb-9ef6-1a5bac40c1ac.png)

**Comment by hugohaggmark** [comment]
I can confirm that we have challenges with the Select component in Grafana UI. There should already be an issue for this though, do you know @dprokop?

**Comment by hugohaggmark** [comment]
@prichards-wmko you can force the menu to bottom, I know this is not optimal at all but might be better? __`menuPlacement="bottom"`__

**Comment by prichards-wmko** [comment]
I implemented the menuPlacement option as you suggested and it works adequately.  Thanks!

**Comment by torkelo** [comment]
The decision to update Select component do default  to down instead of auto

**Comment by hugohaggmark** [comment]
Default was changed to down instead of auto in #29837
