### ISSUE TITLE
Build: building frontend package docs doesn't work on windows.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#28685]
**What happened**:
When running `yarn packages:docsExtract` it will fail due to the underlying command not being supported on Windows.

https://github.com/grafana/grafana/blob/master/packages/grafana-data/package.json#L21

**What you expected to happen**:
It should extract the packages docs meta data that will be used to generate docs.

**How to reproduce it (as minimally and precisely as possible)**:
Run the following command on a windows machine: `./scripts/ci-reference-docs-build.sh`.

**Anything else we need to know?**:
I suggest to move all of these steps from a bash script into a grafana-toolkit command.

**Environment**:
- Grafana version: master
- Data source type & version: n/a
- OS Grafana is installed on: windows
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by hugohaggmark** [comment]
After discussing this with @mckn we concluded that Grafana Toolkit itself needs to have better support for Windows first before tackling this issue.
