### ISSUE TITLE
Bar graph spacing

### ISSUE THREAD

**Issue by retzkek** [grafana/grafana#2869]
Would it be possible for bar spacing to be added as a chart option, much like line width, etc? In particular, I'd like to have no spacing between bars on some graphs. I was using stair-stepped lines with fill to create the same effect, but the single-series tooltip works differently with lines and bars - you have to hover over the line, while you can hover anywhere over a bar. 

For now I'm using graphs with both lines and bars selected to produce the effect I want, but there's still flickering of the tooltip as I move between bars.

![image](https://cloud.githubusercontent.com/assets/1627510/10228105/b3cc1576-6836-11e5-8fc9-f74e10be2c6f.png)
![image](https://cloud.githubusercontent.com/assets/1627510/10228201/04526068-6837-11e5-9596-7a957a6ae75d.png)

**Comment by torkelo** [comment]
Not sure this is needed, 

whats the difference with the tooltip between bars and lines?

**Comment by retzkek** [comment]
With lines you have to hover over the actual line, if you hover over the filled area below the line you won't get the tooltip. With bars you can hover anywhere over the bar, which I think is more intuitive. 

Thanks anyways, I've been really loving grafana (and our users have been too)!

**Comment by torkelo** [comment]
but if you enable the all series tooltip you should see the tool for all series no matter where you hover. Have you tried it? 
![image](https://cloud.githubusercontent.com/assets/10999/10229912/c40eceee-687a-11e5-8f16-e570206ab8f9.png)

**Comment by retzkek** [comment]
Yes, I use it for most graphs, but as the number of series increases it becomes less informative (for example, the graph I attached actually has over 20 series, most very small, but still important to be included).
