### ISSUE TITLE
Bar Gauge panel doesn't show legend with only one time series

### ISSUE THREAD

**Issue by fraform** [grafana/grafana#28693]
**What happened**:
When my metric query returns only one time series the legend is not showed.

![2020-10-30_09:53:36](https://user-images.githubusercontent.com/34766291/97689422-d4f4d400-1a9b-11eb-934e-c7b137ddfb2c.png)

**What you expected to happen**:
Legend appears.

![2020-10-30_09:53:29](https://user-images.githubusercontent.com/34766291/97689451-e211c300-1a9b-11eb-8ea7-fa14c5e5aea9.png)

**How to reproduce it (as minimally and precisely as possible)**:
This is my setting for metric config.

![2020-10-30_10:38:08](https://user-images.githubusercontent.com/34766291/97689566-0cfc1700-1a9c-11eb-8b84-48a41aab4b59.png)

**Anything else we need to know?**:
With previous versions it works (sorry but I don't remember the exact version).

**Environment**:
- Grafana version: 7.2.2
- Data source type & version: Prometheus 2.7.1
- OS Grafana is installed on: Debian 10.6
- User OS & Browser: Debian 10.6 + FF 82.0.2
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
this is by design, you have to set Display name property in the field tab if you want to force a legend when there is only one bar

**Comment by fraform** [comment]
Hi torkelo and thanks for reply.
The problem with your proposed approach is that the display name is static, but in my case depends on metric output, and i don't know when my query returns only one time series and consequetly i don't know the name of field.

**Comment by torkelo** [comment]
you can use variables like ${__series.name} to use series name

**Comment by fraform** [comment]
Gosh you're right.. With this variable it works. Thanks.

**Comment by zoltanbedi** [comment]
Seems like the issue is resolved. We can reopen it if you think that is not the case.

**Comment by 09jvilla** [comment]
Thank you! I had this same question. :)

**Comment by Routhinator** [comment]
At the least, this needs to be documented somewhere. Stumbling into this issue in 2023 - I don't know what the solution is anymore because there's no "Field Tab"

**Comment by Routhinator** [comment]
Ok, turns out Display name is now configured from Sidebar > All tab > Standard Options group

**Comment by glmdev** [comment]
After grepping around in the source code, I stumbled upon [these docs](https://github.com/grafana/grafana/blob/main/docs/sources/panels-visualizations/configure-standard-options/index.md#display-name) which all my Google-fu failed to find the first time.

Setting the value to `${__field.labels}` worked for me.

**Comment by chkp-zackwh** [comment]
Chiming in here to mention that the fix above using ${__series.name} is unintuitive and I only discovered it by this coming up in google. Beyond that, using this approach does not maintain alterations to the legend from the query options.

**Comment by belps96** [comment]
> Chiming in here to mention that the fix above using ${__series.name} is unintuitive and I only discovered it by this coming up in google. Beyond that, using this approach does not maintain alterations to the legend from the query options.

Agreed. Until there is a better solution(if they ever make one), you can set the display name value to be something like:

${__field.labels.name1}:${__field.labels.name2} 

This gives you the same result as if your query legend was set to {{name1}}:{{name2}}. Probably doesn't help you if you've got multiple queries within the panel which each need a different legend though.

**Comment by danielmotaleite** [comment]
Thanks all, For me, the `${__field.labels.horizontalpodautoscaler}` was the one that did what i wanted, a real example is always useful!

But yes, searching around how to do this and the only useful info was this issue and yet the user is totally clueless how to do this via the interface!

while the https://github.com/grafana/grafana/blob/main/docs/sources/panels-visualizations/configure-standard-options/index.md#display-name show the fields, it is hard to reach find.

I suggest a pointer in grafana itself, in the "Display name" to the documentation, users shouldn't need to spend this long to solve this issue.
