### ISSUE TITLE
Grafana v7.3.0 - unable to view single graph on iOS

### ISSUE THREAD

**Issue by tomlut** [grafana/grafana#28695]
**What happened**:
Right clicking a graph in a dashboard and selecting "View" results in a blank screen.

**What you expected to happen**:
A view of the single graph.

**How to reproduce it (as minimally and precisely as possible)**:
Right clicking a graph and selecting "View" results in a blank screen using any apple iOS device.

**Anything else we need to know?**:
Still works perfectly fine on a desktop PC running Firefox. Issue only occurred after updating to Grafana v7.3.0

Dashboards still display correctly. It is only the single graph view.

**Environment**:
- Grafana version: 7.3.0
- Data source type & version: InfluxDB 1.8.3
- OS Grafana is installed on: HassOS 4.15 (buildroot)
- User OS & Browser: iOS 13.7, Safari
- Grafana plugins: Carpet Plot.
- Others:

**Comment by nikobearrr** [comment]
Hi, I am also observing the same issue on Windows10 with Chrome 83.0.1403.106 (64 bit). That was not an issue with 7.2.2
Is this fix going to address win/chrome or is it iOS specific?
