### ISSUE TITLE
Rendering scale factor default is not set when using environment variable

### ISSUE THREAD

**Issue by stehla** [grafana/grafana#28698]
**What happened**:
Setting the environment variable GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_VIEWPORT_DEVICE_SCALE_FACTOR does not affect the rendering scale of a panel, when using panel_header > share > direct link rendered image

**What you expected to happen**:
The value given in GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_VIEWPORT_DEVICE_SCALE_FACTOR would have become the default rendering scale when using panel > share > direct link rendered image  

**How to reproduce it (as minimally and precisely as possible)**:

* Set environment variables in docker-compose.yml
```
...
environment:
  GF_LOG_FILTERS: rendering:debug
  GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_VIEWPORT_DEVICE_SCALE_FACTOR: 3
...
 ```
* Startup Grafana, Navigate to a dashboard

* Choose a panel and follow panel_header > share > direct link rendered image

* check docker logs to see that the deviceScaleFactor i still set to 1 in the request made to the grafana image renderer
<pre>
user@hostname:~$ docker logs --tail 1 grafana_container  
2020-10-30T11:07:01+0000 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://renderer:8081/render?<b>deviceScaleFactor=1.000000</b>&domain=grafana&encoding=&height=500 ...
</pre>

* recieve a rendered image with a scale factor of 1

Additionaly the docker logs indicate that the environment variable has been set properly
```
user@hostname:~$ docker logs grafana_container | grep SCALE
t=2020-10-30T11:06:04+0000 lvl=info msg="Config overridden from Environment variable" logger=settings
var="GF_PLUGIN_GRAFANA_IMAGE_RENDERER_RENDERING_VIEWPORT_DEVICE_SCALE_FACTOR=3"
```

**Environment**:
- Grafana version: 7.3.0
- OS Grafana is installed on: Grafana Docker Image
- User OS & Browser: Ubuntu 20.04 LTS & Chromium
- Grafana plugins: Grafana Image Renderer in Docker

**Comment by hugohaggmark** [comment]
Added this to @grafana/backend-platform but please change it back to us if this issue turns out to be Frontend related.

**Comment by wbrowne** [comment]
@stehla Thanks for raising this issue. I'm just curious, was this working originally and stopped working after a Grafana upgrade?

**Comment by marefr** [comment]
@stehla You're using the remote rendering using Docker so please refer to https://github.com/grafana/grafana-image-renderer/blob/master/docs/remote_rendering_using_docker.md#configuration-file. We're planning to update the Grafana documentation to make this more clear.

**Comment by stehla** [comment]
@marefr Thanks, for the reply. But there has probably been a misunderstanding. I have been using this configuration-file for the grafana-image renderer. Especially these values in `/usr/src/app/config.json`
```
...
"width": 1000,
"height": 500,
"deviceScaleFactor": 3,
...
```
But they seem to have no effect when rendering requests come from the grafana WebUI, since these values are set in the HTTP-request to some value set inside of grafana maybe. This I was hoping to change with the environment varaiable in Grafana, but maybe this is only used when it is supplied with an installed renderer-plugin. Is there a way around this maybe?

**Comment by stehla** [comment]
> @stehla Thanks for raising this issue. I'm just curious, was this working originally and stopped working after a Grafana upgrade?

Unfortunately, I have not been able to make this work, yet

**Comment by marefr** [comment]
@stehla oh now I understand. You have to provide the `scale` query string parameter in the URL currently. see the docs for reference https://grafana.com/docs/grafana/latest/dashboards/share-panel/#direct-link-rendered-image

Let me know if this doesn't work.

**Comment by Huangvivi** [comment]
Seems it was not fixed?
<img width="2560" alt="image" src="https://github.com/grafana/grafana/assets/36916471/60d0289e-b436-40f9-8818-d13f00ebee8a">
