### ISSUE TITLE
Loki: spinner in explore stops early

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#28718]
**What happened**:
In Explore we run instant query as well and if that takes longer than the range query then the spinner is not showing as loading.
![spinner](https://user-images.githubusercontent.com/13729989/97802068-5174e780-1c41-11eb-872b-4c158a52550e.gif)

**What you expected to happen**:
It should show the spinner when instant query takes longer.
**How to reproduce it (as minimally and precisely as possible)**:
in code add delay rxjs operator to instant query.

**Comment by ivanahuckova** [comment]
This should not be an issue anymore as in Loki as we are running only instant or range query, not both. Moreover, when processing query response, we don't assume that loading was finished, but rely on actual loading state - see https://github.com/grafana/grafana/pull/30367.
