### ISSUE TITLE
Dashboard: Minimum dashboard refresh interval should be based on time range selection

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#28717]
**What would you like to be added**:

I would like to be able to have a fixed minimum refresh interval based on the timerange seleciton. 
if I select:
- "last 24h" I would like the minimum refresh to be "5s"
- "last 2d" I would like the minimum refresh to be "30s"
- "last 7d" I would like the minimum refresh to be "1min"

The best would be if I have a dashboard with last 24h and 5s refresh interval, I choose 7d and it will become 1min interval. Then when I switch back to 24h it comes back to 5s. But realistically, staying at 1min would be good as well.

**Why is this needed**:

Some dashboards are set to last 24h with 5s refresh interval. When I look for the last 7d I don't need the stats to refresh and query every 5s, a minute would be sufficient.
For my specific use-case a global enforcement (for the whole grafana cluster/all users) of such setting would be enough.

**Comment by marefr** [comment]
What data source are you using? In most data sources you can already specify the min time interval - have you tried this?

**Comment by nikobearrr** [comment]
HI @marefr, I am using Graphite and mysql primarily. 
I am not aware about such configuration, but perhaps I need to read the docs.
I do not want to completely disable 5s intervals, but if I select "last 7days" it makes no sense to ask the graphite instance every 5s for last 7d - the change won't be visible.

**Comment by marefr** [comment]
Thanks. I do understand that you're asking about different minimum refresh rates based on time range now. Sorry for my confusion..That makes sense as a feature request. Related to #22493  

----

Just to clarify my earlier discussion about min time interval even though it's not applicable here. Configuring this will make sure that Grafana will calculate an interval based on the current time range selected, meaning lower interval with smaller time ranges and higher interval with bigger time ranges.

**Graphite**
Graphite API actually accepts a max data points argument that Grafana provides with every query request. The value of this is the width in pixels of the panel. Graphite handles this automatically for you.

**MySQL:**
You can define the min time interval in the data source configuration 
![image](https://user-images.githubusercontent.com/1668778/98140501-cce6cb00-1ec5-11eb-8da2-1cb7783bbbd1.png)
You can override this on a panel by panel basis as well
![image](https://user-images.githubusercontent.com/1668778/98141670-28fe1f00-1ec7-11eb-8c31-d86c9f987334.png)

**Comment by marefr** [comment]
We'll keep this open for some time to see if it receives more interest/activity.
