### ISSUE TITLE
Logs: Investigate if we could be more tolerating with wrong escaping and newlines in Grafana

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#28731]
**What would you like to be added**:
Connected to #28522. We could investigate if there are any ways how to tolerate wrong escaping/newlines in logs. I have looked into the escaping and couldn't find any solution, but not sure about the newlines.  It would be awesome if Grafana would be more flexible in this, but again, needs investigation if possible. 
[example of log line with newline character](https://github.com/grafana/grafana/files/5473775/grafana.local.edifyhub.com.har.1.txt)

**Comment by secustor** [comment]
We have the use case of multiple quotes in a message block. This could maybe solved using a regex with look behind. 
![image](https://user-images.githubusercontent.com/17493763/98013289-7cef0200-1dfa-11eb-97c2-5bce71dc65fb.png)

**Comment by ivanahuckova** [comment]
Closing this in favour of https://github.com/grafana/grafana/issues/28731
