### ISSUE TITLE
annotation creation/edit/deletion on non editable dashboards

### ISSUE THREAD

**Issue by DEvil0000** [grafana/grafana#28738]
As brief summary: I can add annotations but not edit or delete them on a non editable (readonly) dashboard.
I expect adding annotation beeing also disabled when the dashboard is non editable.

**What happened**:
I can create but not edit or delete annotations on a non editable (readonly) dashboard.

**What you expected to happen**:
I would expect non editable (readonly) means annotations can not get added/inserted.

**How to reproduce it (as minimally and precisely as possible)**:
* create dashboard with graph
* set dashboard setting 'editable' = false
* save & reload
* click on the graph and add annotation
* hover to the bottom of the new annotation and try to edit/delete it

**Environment**:
- Grafana version: 7.2.0 (quite sure this is also true for latest versions)
- Data source type & version: prometheus (but should not matter)
- OS Grafana is installed on: ubuntu 20.04 (but should not matter)
- User OS & Browser: chrome (but should not matter)
- Grafana plugins: piechart, image renderer (but should not matter)

**Comment by torkelo** [comment]
not sure this is correct, you should be able to add  AND delete annotations to a noneditable dashboard

**Comment by torkelo** [comment]
annotation events are not part of the dashboard definition but more the data

**Comment by DEvil0000** [comment]
> not sure this is correct, you should be able to add AND delete annotations to a noneditable dashboard

thats exactly what i expected but what was not the case. i don't care if it is allowed or not but add and delete should act the same
