### ISSUE TITLE
Support for the Microsoft.AppConfiguration/configurationStores namespace

### ISSUE THREAD

**Issue by Ginginho** [grafana/grafana#28733]
**What would you like to be added**: Support for the App Configuration namespace, Microsoft.AppConfiguration/configurationStores

**Why is this needed**:
The absence of app configuration metrics prevents Grafana being a complete monitoring platform for our Azure environment

**Comment by marefr** [comment]
Please provide more detailed information. I have no idea if this is related to Azure Monitor data source or something else.

**Comment by Ginginho** [comment]
My apologies; per the [product documentation](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported), Azure Monitor exposes the following metrics for the Microsoft.AppConfiguration/configurationStores namespace:

- HttpIncomingRequestCount
- HttpIncomingRequestDuration
- ThrottledHttpRequestCount

My hope is that Microsoft.AppConfiguration/configurationStores can be added as a supported namespace for Azure Monitor which I believe are defined here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/supported_namespaces.ts.

**Comment by marefr** [comment]
Thanks

**Comment by bhozar** [comment]
@marefr any chance this can be merged soon please?

**Comment by marefr** [comment]
@joshhunt will have a look when time allows
