### ISSUE TITLE
Tags have stoped working with enabled "all" option since Grafana v7.1.5

### ISSUE THREAD

**Issue by anastas-makar** [grafana/grafana#28740]
**What happened**:

When "All" checkbox is ticked, and than tag is chosen, it works just the same way as if only "All" was chosen.

Example from grafana demo:

![screencast-nimbus-capture-2020 11 02-14_08_24 (1)](https://user-images.githubusercontent.com/57357389/97863097-818eba00-1d17-11eb-8c28-2ace60247925.gif)

Demo:

https://play.grafana.org/d/000000024/templating-value-groups?orgId=1

It worked OK in previous versions.

**What you expected to happen**:

"All" checkbox should be unchecked when any tag is selected, the result should be rendered only for selected tag, not for all possible options.

**How to reproduce it (as minimally and precisely as possible)**:

Combine tags with "All" option in Grafana v7.1.5. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: 
- OS Grafana is installed on: ubuntu, but the bug can be also reproduced on grafana demo
- User OS & Browser: windows, ubuntu & chrome, yandex, firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Try upgrading to v7.3  

We will remove the tags feature soon, possibly in 7.4 or v8 (it's marked experimental)
