### ISSUE TITLE
Influxdb group by time (1y) not supported

### ISSUE THREAD

**Issue by jchauncey** [grafana/grafana#2874]
So Ive noticed that grafana tries to build a group by time query that sends 1y as the param to the function. But Influxdb 0.9 does not support this as a possible value --https://influxdb.com/docs/v0.7/api/query_language.html#group-by.

Here is the query that my current grafana2 instance is trying to send (i ran this through a url decoder to make it easier to read)

query?db=deis&epoch=ms&p=root&q=SELECT last(value) FROM "memory.usage.percent" WHERE "container" =~ /deis\-informant/ AND time > now() - 5m GROUP BY time(1y), "container"&u=root

**Comment by torkelo** [comment]
its a bug that sometimes happen when panel span gets set to null, bug in panel repeat when no min span is set.

**Comment by daviesalex** [comment]
We hit this, and setting a minimum span was effective as a workaround (thank you!). However, as this is a bug with a fairly non-obvious workaround, has this issue been closed because the issue is fixed or because it wont be fixed?

It feels that setting no minimum span should not cause this problem...

**Comment by bricewge** [comment]
I too have been bitten by this bug. Even though the workaround is simple it'll be nice if it didn't appear in the first place.

**Comment by Papyruse** [comment]
+1 !

**Comment by stevenh** [comment]
Just tripped over this as well.

The thing that seemed to be the cause of the span being set to null was the selection of the panel repeat option and then changing the template variable for said variable.

**Comment by binarytemple-bet365** [comment]
+1.. not very obvious .... corrected it via the pane settings but it's going to trip up anyone who tries out templates (which is going to be anyone who uses it for any length of time).

**Comment by bergquist** [comment]
@binarytemple-bet365 which versions of influxdb and grafana are you using?

**Comment by torkelo** [comment]
This bug is fixed in master /v4

**Comment by binarytemple-bet365** [comment]
@bergquist - grafana-3.1.1, influxdb-0.13.0
