### ISSUE TITLE
Icon: Add color prop

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#28746]
**What would you like to be added**:
Add color prop to Icon component, so the color can be updated not just via css, but also via prop.

**Comment by torkelo** [comment]
what is the use case for this?

**Comment by ivanahuckova** [comment]
This came up from the discussion on frontend weekly call. Some users are wondering how to update the color of the icon and it is not clear that you can do it using css. Moreover, it can be extra work to create className and then pass it as `className` prop compared to just passing colors.  

Adding color prop would make it easier for developers to update color of their icon. They could still use css as well, but this would be more straight forward.
