### ISSUE TITLE
Icon: Remove usage of font awesome icons where possible

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#28745]
Another round of going through all the font awesome icons and removing them if possible. It would be great to also document where the icons are still implemented and why they can't be removed, so we can tackle it before 8.0 deprecation.

**Comment by ivanahuckova** [comment]
Where it is used:
- In documentation, specifically section [Installing Grafana](https://github.com/grafana/grafana/blob/master/docs/sources/_index.md) - could be maybe replaced with svgs/images? 
- We use it as spinner icon. We should figure out a new spinner icon. I have refactored all usages of `fa-spin` to  use `<Spinner />`
- We use font awesome for [LoginServices icons](https://github.com/grafana/grafana/blob/master/public/app/core/components/Login/LoginServiceButtons.tsx#L10). I have checked and in unicons there are following icons missing: **Microsoft**, **Gitlab**,  **Okta**. We should reach out to unicons if they could add them.
- Htlm templates in [dropdownTypeahead](https://github.com/grafana/grafana/blob/master/public/app/core/directives/dropdown_typeahead.ts#L15), [dropdownTypeahead2](https://github.com/grafana/grafana/blob/master/public/app/core/directives/dropdown_typeahead.ts#L146), [tip](https://github.com/grafana/grafana/blob/master/public/app/core/directives/misc.ts#L14), [MetricSegment](https://github.com/grafana/grafana/blob/master/public/app/core/services/segment_srv.ts#L22), 

- I am not really sure about this [processAclItems](https://github.com/grafana/grafana/blob/master/public/app/core/reducers/processsAclItems.ts#L19) and [the same is here as well](https://github.com/grafana/grafana/blob/master/public/app/core/utils/acl.ts#L19). 
- Some font awesome icons are used in [AlertTab](https://github.com/grafana/grafana/blob/master/public/app/features/alerting/AlertTabCtrl.ts#L114) and we need to find replacement for  victorops `fa fa-pagelines` - unicons don't have leaf, pagerduty `fa fa-bullhorn`, hipchat `fa fa-mail-forward`, teams `fa fa-windows`

**Comment by ivanahuckova** [comment]
So for the next steps we should check with Unicons team if they plan to create/could create for us following missing icons:
- [ ] Spinner that spins
- [ ] Microsoft
- [ ]
- [ ]
- [ ]

- [ ]

**Comment by ivanahuckova** [comment]
@jessover9000  do we have feedback form unicons team regarding requested icons?

**Comment by jessover9000** [comment]
They are on it, as far as I know they wanted to add them this week. If nothing has happened by Monday I will check with them again.
