### ISSUE TITLE
Gauge panel values scaled wrongly

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#28759]
**What happened**:
After update from 7.2.2 to 7.3.1, the gauge panel values are being scaled incorrectly. Longer values are too small and shorter values are too big.
This is how it looks on 7.3.1:
![7 3 1](https://user-images.githubusercontent.com/19311511/97898915-d68ef800-1d38-11eb-9bef-23ae9b7fb325.jpg)

**What you expected to happen**:
This is how it looked on 7.2.2:
![7 2 2](https://user-images.githubusercontent.com/19311511/97898931-de4e9c80-1d38-11eb-827b-f70f44b6ec85.jpg)

**How to reproduce it (as minimally and precisely as possible)**:
Create gauge panel with long and short value

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10 Opera Gx
- Grafana plugins: -
- Others: -

**Comment by szerwi** [comment]
I have updated to 7.3.2, but the problem is still there. Long values are ok, but short values are still way too big.
7.3.2:
![7 3 2](https://user-images.githubusercontent.com/19311511/99072802-064dc380-25b5-11eb-9a53-45dfaa83cbba.jpg)

7.2.2:
![7 2 2](https://user-images.githubusercontent.com/19311511/99072808-06e65a00-25b5-11eb-92b4-0f420ddf99ee.jpg)

I have also found another problem. When there is no data in selected timerange, the thresholds on gauge panel are not working.

**Comment by szerwi** [comment]
@torkelo Should I create new issue for that bug or will you reopen that one?

**Comment by torkelo** [comment]
Sure, maybe short values could tweaked a tiny bit

**Comment by leeoniya** [comment]
would stacking the value and units be too drastic a change? even in the long versions, the experience seems sub-optimal (too tiny), considering all the empty space available above.
