### ISSUE TITLE
grafana 2.1.3 "401 Unauthorized" errors with scripted dashboard

### ISSUE THREAD

**Issue by adeconsulting** [grafana/grafana#2875]
We're using grafana 2.1.3 with influxDB 0.9.2.1 to display a scripted dashboard.  The O.S. is Ubuntu 12.04.5 LTS.

As others have posted here, we're also seeing "401 Unauthorized" errors in grafana.log.

    2015/10/02 14:42:16 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 4.646019ms
    2015/10/02 14:42:16 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 5.451658ms
    2015/10/02 14:42:16 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 3.397495ms
    2015/10/02 14:42:16 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 6.142511ms

In our case, the dashboard usually displays fine the first time, it's during auto-refresh that we see the errors occur and panels show N/A with the message "Timeseries data request error".  The auto-refresh interval is set to one minute.  The browser is Firefox 41.0.1.

We're using the default settings in grafana.ini except for "allow_org_create = false" and "org_name = Support".

Please let us know if there's any other information you need!

**Comment by torkelo** [comment]
are you using multiple grafana servers behind load balancer? are you using default sqlite3 database and default session storage?

**Comment by arussellsaw** [comment]
+1 on this issue, using a single grafana instance unproxied (though influxdb is proxied via grafana server). using google account auth. default session and sqlite3 db.

**Comment by adeconsulting** [comment]
We are using a single grafana instance, with no load balancer, and the default configuration.  Comments in grafani.ini state that the default database is sqlite3, and session storage is file.

**Comment by torkelo** [comment]
could have been session timeouts, might have been solved by this, https://github.com/grafana/grafana/commit/c831369974f0cbbacd72678184a7fa73589d7a41

**Comment by sweigert** [comment]
when will this be released?

**Comment by torkelo** [comment]
@sweigert yes

**Comment by raviagarwal101** [comment]
I am seeing this issue in grafana-2.5.0-1.x86_64 as well. Is this fixed as part of it?

The server randomly throws many 
```
2016/04/22 05:56:08 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 346.994µs
2016/04/22 05:56:08 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 198.479µs
2016/04/22 05:56:08 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 207.505µs
2016/04/22 05:56:08 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 196.537µs
2016/04/22 05:56:08 [I] Completed /api/datasources/proxy/2/query 401 Unauthorized in 192.723µs
```
and javascript console shows:
`Failed to load resource: the server responded with a status of 401 (Unauthorized)`

If you think this is fixed in grafana 2.5, then may be we should reopen this ticket or file a new one?

**Comment by torkelo** [comment]
It looks like you data source is returning 401. Try 2.6 or 3.0 beta

**Comment by raviagarwal101** [comment]
Well it happens with all datasources (InfluxDB, Graphite and CloudWatch) and not all the time, sometimes it works without any issues and sometime this error. So definitely not an issue with data sources I believe?

**Comment by raviagarwal101** [comment]
Tried 2.6 as well, but same error

```
2016/04/27 10:26:02 [I] Completed 172.17.68.39 admin "GET /api/datasources/proxy/2/query HTTP/1.1" 401 Unauthorized 31 bytes in 222us
2016/04/27 10:26:02 [I] Completed 172.17.68.39 admin "GET /api/datasources/proxy/2/query HTTP/1.1" 401 Unauthorized 31 bytes in 213us
2016/04/27 10:26:02 [I] Completed 172.17.68.39 admin "GET /api/datasources/proxy/2/query HTTP/1.1" 401 Unauthorized 31 bytes in 222us
2016/04/27 10:26:02 [I] Completed 172.17.68.39 admin "GET /api/datasources/proxy/2/query HTTP/1.1" 401 Unauthorized 31 bytes in 321us
2016/04/27 10:26:03 [I] Completed 172.17.68.39 admin "GET /api/datasources/proxy/2/query HTTP/1.1" 401 Unauthorized 31 bytes in 255us
```

**Comment by stevenh** [comment]
We're currently seeing this, is there anything we can do to help debug?

```
Aug  6 18:46:46 influxdb-3 docker: t=2016-08-06T18:46:46+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/query status=401 remote_addr=10.50.10.11 time_ns=0 size=26
```

Some requests are succeeding some failing, only just started happening and it seems to be random

**Comment by stevenh** [comment]
So our issue seems to be we have two grafana noted and they where being load balanced, this seems to be the cause of the 401's as since disabling one of the nodes in the LB we've seen no 401 response codes.
