### ISSUE TITLE
Not able to import FormLabel and FormField in 7.x.x grafana/ui

### ISSUE THREAD

**Issue by Muraliprasath** [grafana/grafana#28753]
Hi Team,
Kindly address the following queries,

We are planning to Migrate from Grafana 6 to Grafana 7, facing the following issues,
1. Not able to import the formfields and formlabel,
2. I have noticed we have support for Legacy Forms - Input, Switch, Select, Kindly let us know whether these legacy forms are available only for short duration, is there any future plans for removing these legacy components.

Regards,
Murali Prasath V

**Comment by torkelo** [comment]
We have a number of Form components  (https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/index.ts#L147) 
* Input
* Select 

For inline forms use these component https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/index.ts#L152
