### ISSUE TITLE
Error while trying to authenticate user: UNIQUE constraint failed: org.name

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#2876]
We are getting an error when new users are trying to log in saying "Error while trying to authenticate user: UNIQUE constraint failed: org.name".  Looking at the org table in the db, it looks like it's trying to create a new org with the name of the org they should be assigned to.  We're using ldap auth.  Here's our configs and what I'm seeing:

```
ldap.toml:
# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "CN=g.acl.group1,OU=Groups,OU=CO_Accounts,DC=domain,DC=com"
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "CN=g.acl.group1,OU=Groups,OU=CO_Accounts,DC=domain,DC=com"
org_role = "Admin"
org_id = 2

[[servers.group_mappings]]
group_dn = "CN=g.acl.group2,OU=Groups,OU=CO_Accounts,DC=domain,DC=com"
org_role = "Admin"
org_id = 2

[[servers.group_mappings]]
group_dn = "CN=g.acl.group3,OU=Groups,OU=CO_Accounts,DC=domain,DC=com"
org_role = "Editor"
org_id = 1

[[servers.group_mappings]]
group_dn = "CN=g.acl.*,OU=Groups,OU=CO_Accounts,DC=domain,DC=com"
org_role = "Viewer"


from the db:
sqlite> select * from org;
1|0|Org1||||||||2015-06-26 17:29:26|2015-06-26 18:05:58
2|0|Org2||||||||2015-06-26 18:06:16|2015-06-26 18:06:16
8|0|||||||||2015-10-02 21:58:18|2015-10-02 21:58:18

from grafana.log:
2015/10/02 15:56:11 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: UNIQUE constraint failed: org.name
```

In this case, the user is part of g.acl.group3, so should be added to Org1 as an editor, but it looks like it's actually trying to create a new org but due to the unique constraint restriction (rightfully so) it's failing and creating a blank org.

**Comment by calebcall** [comment]
Sorry, left out I'm using version 2.1.3

**Comment by torkelo** [comment]
can you enable verbose ldap logging so we can see the ldap groups returned from ldap? So we know that it exactly matches `CN=g.acl.group3,OU=Groups,OU=CO_Accounts,DC=domain,DC=com`

**Comment by calebcall** [comment]
Yeah, I'll get that enabled and get some logging to share.

**Comment by calebcall** [comment]
Enabled verbose logging and it does show this user as part of that group:

```
# grep 'John\ Smith\|g.acl.group3' /var/log/grafana/grafana.log
 DN: (string) (len=83) "CN=John Smith,OU=NOC,OU=Information_Technology,OU=CO_Accounts,DC=domain,DC=com",
 Username: (string) (len=10) "John Smith",
  (string) (len=60) "CN=g.acl.group3,OU=Groups,OU=CO_Accounts,DC=domain,DC=com",
#
```

**Comment by calebcall** [comment]
Any thoughts on this?

**Comment by torkelo** [comment]
no, its strange, its trying to create an org for some reason.
