### ISSUE TITLE
Alias Name changes the trend display

### ISSUE THREAD

**Issue by JBSullivan** [grafana/grafana#28766]
Hello I have the following problem under Grafana 7.2.0 and InfluxDB. As soon as I edit the Alias name in the 5th of five trend lines, the trend is drawn to 0.

If you leave the alias field empty, which of course looks stupid if you see a data point name instead of the clear name in Legend, the trend curve is displayed correctly again.

This is about the red line of the sun's course. Pay attention to the field " Alias By".

![2020-11-03 07_43_43-](https://user-images.githubusercontent.com/44617472/97956441-ef36f680-1da8-11eb-8655-c211176315de.png)
![2020-11-03 07_43_16-](https://user-images.githubusercontent.com/44617472/97956442-efcf8d00-1da8-11eb-98e0-8939b147dd98.png)

**Comment by marefr** [comment]
At the bottom screenshot you have right y-axis enabled, but at the top you doesn't. As you can see the min/max value of the right y-axis is much smaller than the left y-axis and why you see this behavior. Please change any of them to include or not include a right t-axis.
