### ISSUE TITLE
Docs feedback: /administration/cli.md

### ISSUE THREAD

**Issue by vvuk** [grafana/grafana#28763]
`--homepath` is in the wrong place on the `grafana-cli` command line example; it needs to be after `grafana-cli`, as executing the command as written gives:

```
Incorrect Usage: flag provided but not defined: -homepath

NAME:
   Grafana CLI admin reset-admin-password - reset-admin-password <new password>

USAGE:
   Grafana CLI admin reset-admin-password [command options] [arguments...]

OPTIONS:
   --help, -h  show help (default: false)

Error: ✗ flag provided but not defined: -homepath
```

**Comment by marefr** [comment]
Seems like this section is incorrect https://grafana.com/docs/grafana/latest/administration/cli/#reset-admin-password

It's correct in this section https://grafana.com/docs/grafana/latest/administration/cli/#override-homepath-value so we should probably link to this section from https://grafana.com/docs/grafana/latest/administration/cli/#reset-admin-password

**Comment by marefr** [comment]
@grafana/docs-squad can you have a look at my comment and see if it makes sense. Thanks

**Comment by oddlittlebird** [comment]
Not really understanding what you are saying, @marefr . Let's chat about it after the holiday.

**Comment by achatterjee-grafana** [comment]
Fixed inconsistency in PR: https://github.com/grafana/grafana/pull/31404
