### ISSUE TITLE
Custom Dashboard Variable: preview does not show correct values when values are URL's 

### ISSUE THREAD

**Issue by mermino** [grafana/grafana#28762]
![Screen Shot 2020-11-02 at 12 30 41 PM](https://user-images.githubusercontent.com/6807784/97922063-bb0ff700-1d10-11eb-8514-4b730f430b8c.png)

**What happened**:
Creating a custom dashboard variable with URL's as values does not properly show under "Preview of Values"

**What you expected to happen**:
Preview of Values should show correct values

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard and go to the dashboard settings.
Select "Variables" in the left nav
Add a Variable
Select Type: Custom
In the "Values separated by comma" enter random URLs including the "http(s)://" (see attached screenshot)
Notice that the preview of values only shows the protocol.

**Anything else we need to know?**:
This was not a bug in Grafana 6.6.1

**Environment**:
- Grafana version: 7.3.0. this was working fine in Grafana 6.6.1
- Data source type & version: N/A
- OS Grafana is installed on:  Ubuntu 18.04
- User OS & Browser: Mac OS, Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
preview only shows the options not the current selected state, and you can only change the current selected value via URL  so this is correct

**Comment by torkelo** [comment]
Sorry read the issue incorrectly

**Comment by torkelo** [comment]
@hugohaggmark think this PR https://github.com/grafana/grafana/pull/27829 added a regression where custom variable values can now not contain `:` do we need to revert that or is there a way we can fix this?

**Comment by mckn** [comment]
@hugohaggmark do you think it would be ok to force the `key-value` syntax being added in the #27829 to require a space to be detected?

e.g `key : value`

**Comment by HigH-HawK** [comment]
Or maybe assign another character as delimiter. In #27829 it was mentioned to use the pipe | character instead of colon. I think the pipe character is rarely used, so should be better as delimiter.

**Comment by hugohaggmark** [comment]
> Or maybe assign another character as delimiter. In #27829 it was mentioned to use the pipe | character instead of colon. I think the pipe character is rarely used, so should be better as delimiter.

I agree with @HigH-HawK but maybe @mckn suggestion could work too. I'm working on something else today so I can't fix this now. @mckn do you have time to fix it?
