### ISSUE TITLE
unable to add tags to grafana alerts 

### ISSUE THREAD

**Issue by som-kanade** [grafana/grafana#28768]
unable add tags in alert rules 
grafana version >> 7.0.3
the tags disappear after saving 
can someone help here ?

**Comment by torkelo** [comment]
Unable to replicate, adding a name and value then hit the add button, then save. If I reload they are still there 
![Screenshot from 2020-11-06 10-34-04](https://user-images.githubusercontent.com/10999/98350430-9e7b0400-201b-11eb-85a0-1ea9b6517469.png)
