### ISSUE TITLE
"Hide empty" not working while using fill(0)

### ISSUE THREAD

**Issue by prawnsalad** [grafana/grafana#2877]
Using influxdb as the datasource and the series as `/requests.proxied\..*\.counter/`, fill(0) is needed to keep the graph displaying correctly. However as all non-values are now 0 and not null, the "Hide empty" value does not hide those series names with no data in the current time frame.

**Comment by torkelo** [comment]
yeam that is how hide empty works, hides all null series :) use fill(null) instead, or +1 vote the issue that already exists for adding "hide null" option
