### ISSUE TITLE
Instrument time in seconds instead of milliseconds

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#28770]
When we switched to instrument Grafana with Prometheus we wanted to be backward compatible with the graphite instrumentation we had in place. Today Prometheus is by far the most popular way to instrument Grafana so we should adjust Grafanas instrumentation to align more with how Prometheus monitors applications. 

Might be possible to convert some of the values from `seconds` to `ms` in the graphite bridge.

This could be considered a breaking change but it would be fairly easy to update the names for any Prometheus monitoring. Graphite monitoring might require some thought.

https://prometheus.io/docs/practices/naming/#base-units

**Comment by rvdheij** [comment]
Not sure this is in the same area, but I would enjoy ```$__interval_s``` in addition to ```$__interval_ms``` 
I know it's just an extra *1000 but it would be nice to avoid. I wonder whether it could or should be tied to the units for the Y-axis.
