### ISSUE TITLE
Issue with Plugin installtion through grafana CLI for Windows ENv

### ISSUE THREAD

**Issue by shkhan26** [grafana/grafana#28781]
Hi Team,

While installing the IBM APM plugin datasource on Grafanav7.1.5 on Windows env,  I am  getting mentioned exceptions

Tried multiple options but same issue ---

C:\Program Files\GrafanaLabs\grafana\bin>grafana-cli.exe plugins install ibm-apm
-datasource
←[31mError←[0m: ←[31m?←[0m Failed to send request: Get "https://grafana.com/api/
plugins/repo/ibm-apm-datasource": context deadline exceeded (Client.Timeout exce
eded while awaiting headers)

Downloading the plugin n installing manually

C:\Program Files\GrafanaLabs\grafana\bin>grafana-cli.exe plugins install "C:\Use
rs\Administrator\Downloads\ibm-apm-datasource.json"
←[31mError←[0m: ←[31m?←[0m Failed to send request: Get "https://grafana.com/api/
plugins/repo/C:%5CUsers%5CAdministrator%5CDownloads%5Cibm-apm-datasource.json":
context deadline exceeded (Client.Timeout exceeded while awaiting headers)

Environment**:
- Grafana version: Grafana v7.1.5 
- Data source type & version: IBM APM 8.4.1 IF 10
- OS Grafana is installed on: Windows 2012 R2
- User OS & Browser: Chrome/ IE
- Grafana plugins:  ibm-apm-datasource

**Comment by aknuds1** [comment]
I can't find any plugin called ibm-apm:

```
 .\bin\grafana-cli.exe plugins install ibm-apm
Error: ✗ Failed to find requested plugin, check if the plugin_id is correct: 404 not found error
```

Closing until more concrete evidence of a bug is provided.

**Comment by aknuds1** [comment]
Aha, I see now you mean ibm-apm-datasource. Your formatting made it look like ibm-apm. However, I can install it just fine, so there's probably a problem in your environment making it impossible for grafana-cli to download it.

**Comment by shkhan26** [comment]
Thank you very much, but I am still getting the mentioned error while installing with command promt/power cli both ways.. even Proxy is opened - 

C:\Program Files\GrafanaLabs\grafana\bin>grafana-cli.exe plugins install ibm-apm-datasource
←[31mError←[0m: ←[31m?←[0m Failed to send request: Get "https://grafana.com/api/
plugins/repo/ibm-apm-datasource": context deadline exceeded (Client.Timeout exce
eded while awaiting headers)



PS C:\Program Files\GrafanaLabs\grafana\bin> .\grafana-cli.exe plugins install ibm-apm-datasource
Error: âœ— Failed to send request: Get "https://grafana.com/api/plugins/repo/ibm-apm-datasource": context deadline exceeded (Client.Timeout exceeded while a
waiting headers)


Also please suggest if I download the ibm-apm-datasource.json, how we can install using that as well.

I tried that option 
grafana-cli.exe plugins install "C:\Users\Administrator\Downloads\ibm-apm-datasource.json"

**Comment by aknuds1** [comment]
I can recommend using the Grafana community [forums](https://community.grafana.com) or [Slack](http://slack.raintank.io) for support requests. We use GitHub issues for bug reports and feature requests.

**Comment by shkhan26** [comment]
Thanks, I have already raised the ticket there. Thank you for the support

**Comment by shkhan26** [comment]
Thanks it's solved i set http proxy in command promt it was uable to go to site for downloadng .. Thanks for the support
