### ISSUE TITLE
oauthPassThru option visible for data source plugins?

### ISSUE THREAD

**Issue by dkozar** [grafana/grafana#28794]
**What would you like to be added**:

We're wondering if the `oauthPassThru` option could be made visible for the following data source plugins:

- Azure Monitor datasource
- Prometheus

This value is being edited by the _Forward OAuth Identity_ switch which is present in `HttpProxySettings` control, but this control is not present in any of the standard data source config editors:

![image](https://user-images.githubusercontent.com/1078403/98032892-9436eb00-1e0c-11eb-9945-04d925c82e50.png)
 
https://github.com/grafana/grafana/blob/da6056d5e1b0824c80fcfc1c1ca3270738581af0/packages/grafana-ui/src/components/DataSourceSettings/HttpProxySettings.tsx#L38

**Why is this needed**:

In certain scenarios, we'd like Grafana to send the fetched token (returned by OAuth flow) with every API request.
We would modify the API so it rejects request not having a proper token.

Thanks! :)

**Comment by marefr** [comment]
You can already use this for Prometeheus. Azure Monitor is a bit different since it's not implemented as a HTTP data source like Prometheus for example - would suggest you open a separate feature request for Azure Monitor and describe the use case. Thanks
