### ISSUE TITLE
plugin.json supported features field

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#28792]
**What would you like to be added**:
A `supportedFeatures` (or similarly named) field for listing/mapping Grafana features that a plugin supports:
```json
"supportedFeatures": {
  "template_variables": {
    "metric_names": true,
    "metric_values": true
  },
  "annotations": true,
  "aliasing": {
    "metric_names": true,
    "metric_values": true,
  },
  "ad_hoc_filters": false,
  "alerting": true
}
```

Any undefined features can be parsed as an "unknown" state; for handling features added to Grafana after a plugin has last been updated.

**Why is this needed**:
This would be useful for generating a visual for Grafana UIs and plugin pages on grafana.com/plugins. It's currently not clear during configuration which features are supported; requiring extra digging. Even if there were a table stating a feature's status as unknown, one could take a quicker action. Ideally with our official plugins, we could keep this data current.

We could also use it internally for keeping track of the state of our plugins.

**Comment by torkelo** [comment]
not sure what the templating sub features (names & values) & alias options mean? aliasing should not needed anymore as Grafana can do this now via the display name option

**Comment by stevenvachon** [comment]
The feature list here is not yet exact. I mostly copied from https://grafana.com/grafana/plugins/grafana-dynatrace-datasource

**Comment by marcusolsson** [comment]
I'm worried that this will encourage more configuration, where plugin authors need to specify the all the features they intend to use up-front instead of just using them. How do we determine what features need to be "turned on" in the plugin.json?

Typically, supported features are currently top-level boolean properties. The ones I can think of right now include:

- alerting
- annotations
- backend
- logs
- metrics
- tracing

Is this proposal suggesting that we move the existing feature properties into the `supportedFeatures` object?

If I understand the description correctly, setting these to true also doesn't mean that they are actually using the features. Only that the plugin author wants to display it on Grafana.com. Also, there's nothing that stops the list from growing with more features. Most community plugins don't have (and probably won't have) this information, which can create confusion as to a plugin supports the feature or not.

Instead of having to manually add metadata, I'd be interested in having a way where plugins can generate a list of supported features based on the functions they actually use. For example, if a data source implements `metricFindQuery` then it supports annotations, or if it calls getTemplateSrv, it supports template variables etc.

**Comment by stevenvachon** [comment]
> Is this proposal suggesting that we move the existing feature properties into the supportedFeatures object?

Yes, I think that would clean up the file schema.

> I'd be interested in having a way where plugins can generate a list of supported features based on the functions they actually use

Perhaps we could automate the properties via @grafana/toolkit and/or grafana-plugin-sdk-*, but still using _plugin.json_.

**Comment by ryantxu** [comment]
I am strongly against adding this to the static plugin.json file.

Perhaps adding a describe features function to the runtime module?  Then it could actually enumerate what is possible based on current settings

**Comment by stevenvachon** [comment]
> Perhaps adding a describe features function to the runtime module? Then it could actually enumerate what is possible based on current settings

Like a REST API endpoint?

**Comment by ryantxu** [comment]
a function on the plugin module.

Let me back up to ask why we should add more details?

**Comment by stevenvachon** [comment]
1. Customers know upfront which expected features are not supported
2. We have an accurate record of how incomplete each of our plugins are

**Comment by stevenvachon** [comment]
> a function on the plugin module.

That means JavaScript, which I don't know will tell us which backend features are implemented.

**Comment by ryantxu** [comment]
again, my question is for what purpose.  If I read your  description, it is for building a matrix that can be published on the website.  My biggest concern is that the static values are rarely correct and depend on the setup and which version you are running.  Perhaps this is something e2e could inspect and save... :thinking: 

In the specific examples listed, ideally they are all supported automatically just by having a query editor.

**Comment by stevenvachon** [comment]
> ideally they are all supported automatically just by having a query editor.

Yeah, but we currently have plugins with a query editor and, for example, no support for annotations. It's useful for us and for customers to know and track that.

> Perhaps this is something e2e could inspect and save... 

That might get specific to each plugin, which is as easy to skip and more difficult to implement than a static matrix. It's worth investigating if this is data that we all care about.

**Comment by marcusolsson** [comment]
I agree that being to display and check for supported capabilities would be really useful. My fear is that authors of community and third-party commercial plugins won't be able to keep up with the changes to this matrix. Any plugin that's not actively maintained by a team at Grafana Labs will likely fall behind and potentially be wrong. 

If the matrix is only accurate for a small subset of all plugins, I'm not sure how much value it would provide.

> That means JavaScript, which I don't know will tell us which backend features are implemented.

For backend plugins, could the SDK add a flag to the binary to output metadata? The Grafana Toolkit could then collect the metadata from the runtime module and the backend binary and write it to the plugin.json?

**Comment by marefr** [comment]
> For backend plugins, could the SDK add a flag to the binary to output metadata? 

Maybe. But not sure it makes sense in it's current state. Currently, backend plugin only supports capabilities backed by the plugin type itself, like datasource and query data capability. You currently have to specify the `backend` plugin.json property for a backend plugin. We're going to discuss the current usage of plugin types and potentially how we could simplify that and if so this requirement may be needed.
