### ISSUE TITLE
Display problem with graph panel (Sun and Moon datasource)

### ISSUE THREAD

**Issue by Schrolli91** [grafana/grafana#28804]
**What happened**:
Display problem in graph panel with the Sun and Moon datsource
https://grafana.com/grafana/plugins/fetzerch-sunandmoon-datasource

If you can see on the image, there are some wrong lines.
When i do a refresh (F5) of the browser window all is ok - but after some time (auto-timed refreshes) this error occurs.
![image](https://user-images.githubusercontent.com/6043382/98092368-e0267600-1e86-11eb-97f7-79825b6c4071.png)

it's even worse here
![image](https://user-images.githubusercontent.com/6043382/98093382-28926380-1e88-11eb-82df-9fbf833ecde3.png)

This problem only happens with data from this datasource but its maintainer said:
> The addon just passes datapoints to Grafana. I doubt that the issue is caused by the addon.

See: https://github.com/fetzerch/grafana-sunandmoon-datasource/issues/29

**What you expected to happen**:
Clean graph (screenshot made after a F5 browser window refresh)
![image](https://user-images.githubusercontent.com/6043382/98093209-ec5f0300-1e87-11eb-86e5-97bfe4531d60.png)

**How to reproduce it (as minimally and precisely as possible)**:
- I have installed the plugin via CLI
- Built a dashboard and create a graph panel
- Used the Sun and Moon datasource to display these values

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Sun and Moon v0.1.6
- OS Grafana is installed on: Debian (Raspbian) in docker container
- User OS & Browser: Latest stable Chrome on Linux Mint/Win 10
- Grafana plugins: Sun and Moon - Datasource

**Comment by torkelo** [comment]
Can you show the data in panel inspector / JSON / DataFrame when you see this?

**Comment by Schrolli91** [comment]
Do you mean the `Inspect` on the panel with the wrong lines and go to the tab `JSON` and select `Panel data` here?
I'll try that tomorrow

**Comment by torkelo** [comment]
Yes

**Comment by Schrolli91** [comment]
Here you can find the json from the `Panel data`
https://pastebin.com/QEaqfN7D

In the moment of dump these data the graph shows this:
![image](https://user-images.githubusercontent.com/6043382/98220034-0f53ea80-1f4e-11eb-9c7b-63fda16c2757.png)

**Comment by torkelo** [comment]
This is a bug in the data source, it sometimes returns data out of order 
![Screenshot from 2020-11-06 10-47-20](https://user-images.githubusercontent.com/10999/98351803-7b515400-201d-11eb-9624-11b6bd02af1f.png)
