### ISSUE TITLE
7.3.1 Stat panel: ${__field.labels.*} not evaluated in data links

### ISSUE THREAD

**Issue by MartinRoenneburg** [grafana/grafana#28805]
**What happened**:

In Grafana 7.2 I use Stat Panels with Data Links depending on (prometheus-) labels.
(drill down to other dashboards ... )

<img width="279" alt="Bildschirmfoto 2020-11-04 um 10 32 22" src="https://user-images.githubusercontent.com/32619064/98094644-d94d3280-1e89-11eb-9bf3-bf541ddd01be.png">

I updated to 7.3.1 and the ${__field.labels.*} are no longer evaluated in Field Data Link.

<img width="268" alt="Bildschirmfoto 2020-11-04 um 10 33 32" src="https://user-images.githubusercontent.com/32619064/98094671-e1a56d80-1e89-11eb-95cf-996af5ebf568.png">

The popup also shows no longer the field.label - options. 

**What you expected to happen**:

Data Links including ${__field.labels.*}.

**How to reproduce it (as minimally and precisely as possible)**:

Add a data link to a Stat panel that includes variables set via the above method:
var-hostname=${__field.labels.hostname}

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1 
- Data source type & version: Prometheus 2.19.2
- OS Grafana is installed on: Windows
- User OS & Browser: Win10 & Google Chrome
- Grafana plugins: 
- Others:

**Comment by dprokop** [comment]
This seems like it might be a Prometheus data source specific, just checked on master and the labels are correctly suggested with test data source.
