### ISSUE TITLE
"Back to Dashboard" missing from panel fullscreen view

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#2880]
Hi,

in reference to #2424 and #1756

I'm missing the "Back to Dashboard" button from the panel fullscreen view. According to the mentioned issues it was missing for a short time, but was re-added. I'm running 2.1.3 (2015-08-24) but can't find the button.

EDIT: I see that the code for the "Back to Dashboard" function is included in the source but it is not displayed in the browser (tested with FF 41 and Chrome 45 under LinuxMint 17.1 MATE)

See: http://i.imgur.com/R5jXClp.png

**Comment by torkelo** [comment]
its hidden if you have sidemenu open

**Comment by rlueckl** [comment]
Thanks, but I don't really understand this. It would make sense if there was a "Back to Dashboard" function in the side menu, but it doesn't make sense the way it's implemented now.

**Comment by torkelo** [comment]
I know, will be fixed, there is already an issue. It was a temporary fix that hides the link so the menu fits on smaller screens when the side menu is open

**Comment by rlueckl** [comment]
Thanks! :)
