### ISSUE TITLE
Dashboard snapshot cannot be saved since it's too long

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#28815]
A user in our hosted service is having problems storing a dashboard snapshot due to the size of the dashboard. 

```
error: Error 1406: Data too long for column 'dashboard_encrypted' at row 1
msg :  "Failed to create snapshot"
```

Seems like we using `DB_BLOB` instead of `DB_TEXT` as a datatype for encrypted dashboard snapshots. The Blob datatype is limited to 65535 bytes (64 KB). A `MEDIUMBLOB` is 16777215 bytes (16 MB) and a `LONGBLOB` is 4294967295 bytes (4 GB). So I suggest we change it to `MEDIUMBLOG`

**Comment by marefr** [comment]
We need to do something similar to this, but for mediumblob https://github.com/grafana/grafana/blob/5916ef94d0d7ca4bde47cb8478c3fb55fd829063/pkg/services/sqlstore/migrations/dashboard_snapshot_mig.go#L52-L54

**Comment by anas-aso** [comment]
I still have this issue on `Grafana v7.5.5 (b5190ee547)`. Any idea how can I fix/workaround it ?
