### ISSUE TITLE
Add support for Phone Number formatting in field overrides

### ISSUE THREAD

**Issue by runebaas** [grafana/grafana#28812]
**What would you like to be added**:
The ability to select "Phone Number" in field overrides when editing a query, possibly as a Unit or separate override option

**Why is this needed**:
To nicely format phone numbers

I'd be happy to do the work

**Comment by marefr** [comment]
Can you please describe in more detail the use case of it. This feels like something the data source should provide. What panel do you need this for?

**Comment by runebaas** [comment]
Sure. 

We are sending text messages in 50+ countries from multiple phone numbers each. We have a dashboard to visualize the flow of the messages. We are using the graph and the table panel on that dashboard. The datasource for the dashboard is cloudwatch.

Right now the phone numbers show up as strings in the table (e.g. `41751234567`), which would be a lot easier to read when written as `+41 75 123 45 67`.

This could be done by the data source, but formatting phone numbers should be the task of the visualization tool and not the log message in my opinion. Opinions may differ of course.
