### ISSUE TITLE
Using Local formate in "Field Unit" gives a MaximumFractionDigits value out of range error

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#28814]
Changing the Unit under Field to "local format" gives a "MaximumFractionDigits value out of range" error. The same thing happens if applied under overrides. The same error does not happening if using other Unit..

![image](https://user-images.githubusercontent.com/8969659/98109071-44543480-1e9d-11eb-848f-7754e7829797.png)

**Environment**:
- Grafana version: Grafana 7.2.2
- Data source type & version: MS SQL
- OS Grafana is installed on: Windows azure
- User OS & Browser: Google Chrome and Edge
- Grafana plugins: Table

********************************************** SQL *********************************************************
{
  "datasource": "SCADA_HIS",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": null,
        "filterable": false
      },
      "unit": "none",
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 19,
    "w": 24,
    "x": 0,
    "y": 11
  },
  "id": 11,
  "links": [],
  "options": {
    "showHeader": true
  },
  "pluginVersion": "7.3.0",
  "targets": [
    {
      "alias": "",
      "format": "table",
      "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \n\nIIF(AVG(VALUE) <20 , 0, AVG(VALUE)) 'DCStroemMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_IDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'APO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
      "refId": "A"
    },
    {
      "alias": "",
      "format": "table",
      "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \nIIF(AVG(ABS(VALUE)) <18, 0, AVG(VALUE)) 'DCEffektMiddel'\n\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_BJS-BWT_P1'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'PORP'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
      "refId": "B"
    },
    {
      "alias": "",
      "format": "table",
      "hide": true,
      "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \nIIF(AVG(VALUE) <0, 'Import', 'Eksport') 'Powerdirection'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_BJS-BWT_P1'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'PORM'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
      "refId": "D"
    },
    {
      "alias": "",
      "format": "table",
      "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \n\nAVG(VALUE) as  'DCSpaendingMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_UDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'KVPO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
      "refId": "E"
    }
  ],
  "title": "24 h gennemsnit",
  "transformations": [
    {
      "id": "seriesToColumns",
      "options": {
        "byField": "time"
      }
    }
  ],
  "type": "table"
}

*************************************************data ******************************************************

[24 h gennemsnit-data-2020-11-04 13_02_24.xlsx](https://github.com/grafana/grafana/files/5487617/24.h.gennemsnit-data-2020-11-04.13_02_24.xlsx)

**Comment by marefr** [comment]
I was able to reproduce it temporarily and then saved a dashboard of the reproduction [here](https://play.grafana.org/d/qNiytchGk/issue-28814-maximumfractiondigits-value-out-of-range-error?orgId=1). Used Google Chrome. However, loading the dashboard now it's no longer happening. The error message logged in the console I unfortunately didn't catch before I reloaded the browser window.

I think this code is what fails, but not exactly sure:
https://github.com/grafana/grafana/blob/5916ef94d0d7ca4bde47cb8478c3fb55fd829063/packages/grafana-data/src/valueFormats/valueFormats.ts#L142

Update:
Manually changed the panel JSON incorrectly to 

```json
"transformations": [
    {
      "id": "seriesToColumns",
      "options": {
        "byField": "time"
      }
    }
  ],
```

Then changed it to the correct upper case Time
```json
"transformations": [
    {
      "id": "seriesToColumns",
      "options": {
        "byField": "Time"
      }
    }
  ],
```

Then error is thrown:
![image](https://user-images.githubusercontent.com/1668778/98116436-8c2c8900-1ea8-11eb-862d-7a17f112327d.png)


```
react_devtools_backend.js:2450 RangeError: maximumFractionDigits value is out of range.
    at Number.toLocaleString (<anonymous>)
    at X (valueFormats.ts:142)
    at Object.display (displayProcessor.ts:90)
    at ta (DefaultCell.tsx:13)
    at la (react-dom.production.min.js:154)
    at Su (react-dom.production.min.js:259)
    at yc (react-dom.production.min.js:230)
    at hc (react-dom.production.min.js:229)
    at ic (react-dom.production.min.js:223)
    at react-dom.production.min.js:121
```

Update 3::
This doesn't make sense. Was able to receive the error again just by loading above dashboard. Maybe depends on the data returned, maybe negative values?

@HenrikRolandHansen if you can reproduce this can you include the query inspector output. You can find it a button to open it in the query tab and then copy to clipboard and include here, see screenshot below:
![image](https://user-images.githubusercontent.com/1668778/98117347-e417bf80-1ea9-11eb-807a-e802e380a297.png)

**Comment by HenrikRolandHansen** [comment]
Hi Marco
Here is the copy of the query'sm, with the error reproduced .

/Henrik

{
  "request": {
    "url": "api/tsdb/query",
    "method": "POST",
    "data": {
      "from": "1603892931086",
      "to": "1604497731086",
      "queries": [
        {
          "refId": "A",
          "intervalMs": 600000,
          "maxDataPoints": 1255,
          "datasourceId": 5,
          "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \n\nIIF(AVG(VALUE) <20 , 0, AVG(VALUE)) 'DCStroemMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_IDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'APO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
          "format": "table"
        },
        {
          "refId": "B",
          "intervalMs": 600000,
          "maxDataPoints": 1255,
          "datasourceId": 5,
          "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \nIIF(AVG(ABS(VALUE)) <18, 0, AVG(VALUE)) 'DCEffektMiddel'\n\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_BJS-BWT_P1'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'PORP'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
          "format": "table"
        },
        {
          "refId": "E",
          "intervalMs": 600000,
          "maxDataPoints": 1255,
          "datasourceId": 5,
          "rawSql": "SELECT\n$__timeGroup(HIST_TIMESTAMP, '24h') as time, \n\nAVG(VALUE) as  'DCSpaendingMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE $__timeFilter(HIST_TIMESTAMP)\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_UDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'KVPO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY $__timeGroup(HIST_TIMESTAMP, '24h')\nOrder BY 1",
          "format": "table"
        }
      ]
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "refId": "A",
        "meta": {
          "executedQueryString": "SELECT\nFLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400 as time, \n\nIIF(AVG(VALUE) <20 , 0, AVG(VALUE)) 'DCStroemMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE HIST_TIMESTAMP BETWEEN '2020-10-28T13:48:51Z' AND '2020-11-04T13:48:51Z'\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_IDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'APO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY FLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400\nOrder BY 1",
          "rowCount": 8
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "time"
              },
              {
                "text": "DCStroemMiddel"
              }
            ],
            "rows": [
              [
                1603843200000,
                0
              ],
              [
                1603929600000,
                0
              ],
              [
                1604016000000,
                0
              ],
              [
                1604102400000,
                0
              ],
              [
                1604188800000,
                0
              ],
              [
                1604275200000,
                0
              ],
              [
                1604361600000,
                0
              ],
              [
                1604448000000,
                0
              ]
            ],
            "type": "table",
            "refId": "A",
            "meta": {
              "executedQueryString": "SELECT\nFLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400 as time, \n\nIIF(AVG(VALUE) <20 , 0, AVG(VALUE)) 'DCStroemMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE HIST_TIMESTAMP BETWEEN '2020-10-28T13:48:51Z' AND '2020-11-04T13:48:51Z'\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_IDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'APO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY FLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400\nOrder BY 1",
              "rowCount": 8
            }
          }
        ],
        "dataframes": null
      },
      "B": {
        "refId": "B",
        "meta": {
          "executedQueryString": "SELECT\nFLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400 as time, \nIIF(AVG(ABS(VALUE)) <18, 0, AVG(VALUE)) 'DCEffektMiddel'\n\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE HIST_TIMESTAMP BETWEEN '2020-10-28T13:48:51Z' AND '2020-11-04T13:48:51Z'\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_BJS-BWT_P1'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'PORP'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY FLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400\nOrder BY 1",
          "rowCount": 8
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "time"
              },
              {
                "text": "DCEffektMiddel"
              }
            ],
            "rows": [
              [
                1603843200000,
                0
              ],
              [
                1603929600000,
                0
              ],
              [
                1604016000000,
                0
              ],
              [
                1604102400000,
                0
              ],
              [
                1604188800000,
                0
              ],
              [
                1604275200000,
                0
              ],
              [
                1604361600000,
                0
              ],
              [
                1604448000000,
                0
              ]
            ],
            "type": "table",
            "refId": "B",
            "meta": {
              "executedQueryString": "SELECT\nFLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400 as time, \nIIF(AVG(ABS(VALUE)) <18, 0, AVG(VALUE)) 'DCEffektMiddel'\n\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE HIST_TIMESTAMP BETWEEN '2020-10-28T13:48:51Z' AND '2020-11-04T13:48:51Z'\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_BJS-BWT_P1'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'PORP'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY FLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400\nOrder BY 1",
              "rowCount": 8
            }
          }
        ],
        "dataframes": null
      },
      "E": {
        "refId": "E",
        "meta": {
          "executedQueryString": "SELECT\nFLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400 as time, \n\nAVG(VALUE) as  'DCSpaendingMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE HIST_TIMESTAMP BETWEEN '2020-10-28T13:48:51Z' AND '2020-11-04T13:48:51Z'\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_UDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'KVPO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY FLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400\nOrder BY 1",
          "rowCount": 8
        },
        "series": null,
        "tables": [
          {
            "columns": [
              {
                "text": "time"
              },
              {
                "text": "DCSpaendingMiddel"
              }
            ],
            "rows": [
              [
                1603843200000,
                -0.0501800320932791
              ],
              [
                1603929600000,
                -0.042640722216293996
              ],
              [
                1604016000000,
                -0.04191666663003465
              ],
              [
                1604102400000,
                -0.05711805502004508
              ],
              [
                1604188800000,
                -0.05377777771403392
              ],
              [
                1604275200000,
                -0.06183333257989337
              ],
              [
                1604361600000,
                -0.04671994403853774
              ],
              [
                1604448000000,
                -0.03957160288009751
              ]
            ],
            "type": "table",
            "refId": "E",
            "meta": {
              "executedQueryString": "SELECT\nFLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400 as time, \n\nAVG(VALUE) as  'DCSpaendingMiddel'\n\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\nJOIN eta_user.eta_user30.E_ANA_1M  eta\nON eta.TABLE_INDEX = eta_key.TABLE_INDEX\nWHERE HIST_TIMESTAMP BETWEEN '2020-10-28T13:48:51Z' AND '2020-11-04T13:48:51Z'\nAND eta.TABLE_INDEX = (SELECT TABLE_INDEX\nFROM eta_user.eta_user30.E_ANA_1M_KEY eta_key\n WHERE\neta_key.DEVICE = 'U_UDL'  AND eta_key.DEVICE_TYPE = 'P1'  AND eta_key.ID = 'KVPO'  AND eta_key.SUBSTATION = 'BJS_HVDC'  )\nGroup BY FLOOR(DATEDIFF(second, '1970-01-01', HIST_TIMESTAMP)/86400)*86400\nOrder BY 1",
              "rowCount": 8
            }
          }
        ],
        "dataframes": null
      }
    }
  }
}

**Comment by marefr** [comment]
@HenrikRolandHansen thanks. Can you try disable the query "E" and see if you still can reproduce it?

**Comment by HenrikRolandHansen** [comment]
If I disable "E" then I can't reproduce the error with the remaining queries and same time period. But when I change the time period  to 90 days I get the same error again with the remaining queries.

**Comment by marefr** [comment]
Thanks. I'll let another team investigate this further.

Until then,

**Comment by HenrikRolandHansen** [comment]
Thanks

**Comment by mckn** [comment]
I can reproduce this issue, will look into resolving it.
