### ISSUE TITLE
Grafana special data source "Dashboard" not working for repeated rows

### ISSUE THREAD

**Issue by R-Studio** [grafana/grafana#28821]
**UseCase / What happened**
I want to make a dashboard with a row foreach "Customer"("Customer" is a Grafana template variable).
I use a Grafana table inside the row with a queryfilter "Customer". To make the dashboard fast and efficient I want to use the data in this table for all following Grafana Panels in the same row.

**But here is the issue:** In the first Grafana row the panels with the special Grafana data source "Dashboard" are working, but in the repeated rows not. I think because the panels want the data of the table in the first row instead of the table in the same row. (see the error in the screenshot)

![image](https://user-images.githubusercontent.com/7498854/98123222-da925580-1eb1-11eb-9217-20b706550abb.png)

**What you expected to happen**:
I expect that the panels in the repeate rows are working and uses the data from the table in the same row. (Datasource "Dashboard")

**How to reproduce it (as minimally and precisely as possible)**:
* create a dashboard with a template variable (array)
* create a row that is repeated for each template variable
* create a table with some data and filtered with the template variable
* create a panel that the data source is this table
* all the panels in the repeated rows doesn't work

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: I use the built-in datasource "Dashboard"
![image](https://user-images.githubusercontent.com/7498854/98124158-17128100-1eb3-11eb-915e-c618a68bdc9f.png)
- OS Grafana is installed on: Container
- User OS & Browser: Windows, Chrome

**Comment by torkelo** [comment]
This use case is sadly not supported and likely will not be as this dashboard query needs the panel id to look up its results

**Comment by R-Studio** [comment]
> This use case is sadly not supported and likely will not be as this dashboard query needs the panel id to look up its results

What do you think about the following idea/feature request?
- In the template variables **add a variable type "Table"**. In this variable type you can write a **query that gets a table of data**.
- In the panels and rows you can select this **template variable as a data source but you can filter on this table data** (for example with other template variables to make this more dynamic and support repeating)

With this feature you are able to send only one query and all other panels using this data and also support repeating and filtering on this data.

I am really a fan of Grafana and I hope this can be a useful feature for a upcoming release. But if you think this is not useful than ignore this comment. 
Anyway thanks for the reply and Grafana! :-)
