### ISSUE TITLE
Feature Request: Panel Border to be red/green/yellow depending on the last datapoint value.

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2882]
We can set a threshold on a graph (either on a single series or multiple series combination, we can discuss on that) and depending on the last datapoint, we can set the panel border to turn red/green/yellow.

<img width="617" alt="screen shot 2015-10-06 at 5 15 28 pm" src="https://cloud.githubusercontent.com/assets/1019609/10307616/010326e8-6c4e-11e5-97f6-6c05dc9d7e36.png">

If this feature is needed by enough people, I can work on a PR.

**Comment by torkelo** [comment]
there already is an issue for exactly this so I will close this one, 

also could be solved as we get started on alerting, https://github.com/grafana/grafana/issues/2209
