### ISSUE TITLE
Heatmap visualization bug - bucket rectangles are much taller than they should be

### ISSUE THREAD

**Issue by HappyCerberus** [grafana/grafana#28824]
For some peculiar reason the height of the rectangle ends up being 75 pixels, which leads to weird artifacts in the heatmap (light lines peeking around dark values).

This seems to happen consistently when using the Format `Time Series Buckets`.

![visual bug](https://i.imgur.com/U7Lf2Gb.png)

**Comment by marefr** [comment]
Please use the [bug report template](https://github.com/grafana/grafana/issues/new?labels=type%3A+bug&template=1-bug_report.md) and update your issue description. Thanks
