### ISSUE TITLE
P/R #25275:  user.email was removed from global variables.

### ISSUE THREAD

**Issue by aidanmountford** [grafana/grafana#28840]
user.email was removed from global variables. 

The position taken was "there is no use case" and you wanted to limit the data exposed. 

I submit that the data is exposed in the client regardless (when logged on) and as such this only serves to limit the functionality.

The use case I have is quite simple (and clearly others do as well).   I pull data from multiple systems, many of which do not allow for federated authentication (Some use shortened logons, others require globally unique usernames across a large shared platform and don't permit email addresses as a username) 

The only useful "Key" that allows a user to be uniquely identified across the dozen or so systems is their email address. 
We are using Grafana to create user specific dashboards (ie user logs on - and they see data specific to them).   

The use of "Login Name" is not an acceptable substitute because it cannot be guaranteed to be the same in all system that we are integrating, furthermore, because we are a group of companies, the domain portion for a user may change depending on what their org unit is.   As such we cannot simply use "loginid" and append the domain portion.

Happy to re-resubmit a PR to put this back

A

**Comment by marefr** [comment]
To ease navigating to the PR #25275

I've asked another team to have a look at this.

**Comment by aidanmountford** [comment]
@mckn  

Thank you, you are a star!

A
