### ISSUE TITLE
Grafana Explore: date histogram not reflective of date/time picker

### ISSUE THREAD

**Issue by stevekatsaras** [grafana/grafana#28844]
**What happened**:

I have configured an Elasticsearch datasource to Grafana. In the "Explore" screen, I am attempting to search the Elasticsearch index over a large timeframe (screenshot has 3 hours) and I would like to display the logs. I set the "Metrics" to "Logs". When I run the query, I can see the raw logs listed (limited to either 500 or 1000) and a date histogram that only graphs the last 2-3 minutes (approx). I am assuming the 2-3 minute date histogram is due to the max raw logs all being indexed in the short timeframe.

**What you expected to happen**:

I am okay with a limit of 500 or 1000 on the display of the raw logs, but I think the date histogram is misrepresented. I think the date histogram should still show the exact timeframe that is set in the date/time picker and the logs results should contain a heading that says something like "most recent 1000 records" or something like that.

Eg. if the date/time picker says "Last 3 hours", the date histogram should display the last 3 hours.
In the elasticsearch query, the "date histogram" aggregation can allow you to perform that even though you put a size on the result set of the logs returned.

**How to reproduce it (as minimally and precisely as possible)**:

1. Add an elasticsearch datasource in Grafana.
2. Navigate to the "Explore" screen
3. Choose your index, pick a large timeframe, set the "Metric" to logs and "run query"

NOTE: ensure you have a large amount of data in your Elasticsearch index.

<img width="1277" alt="2020-11-05_11-15-47" src="https://user-images.githubusercontent.com/43257211/98182573-387a7800-1f5a-11eb-84fc-1b4b1a81a74e.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.5
- Data source type & version: Elasticsearch v7.9
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by marefr** [comment]
looks like you're using an interval of 10s - have you tried to increase this?

If that doesn't make a difference maybe you can use the chrome developer tools to capture the query request details and include in here?

**Comment by stevekatsaras** [comment]
> 
> 
> looks like you're using an interval of 10s - have you tried to increase this?
> 
> If that doesn't make a difference maybe you can use the chrome developer tools to capture the query request details and include in here?

I have tried increasing the interval to 1m ... same outcome. Please see attached screenshot. I have set the relative time range to the "Last 12 hours" and the date histogram interval to "1m" and the date histogram displayed is about 2.5 minutes. Interestingly, when I captured the request via Chrome Developer Tools, the request payload looked like this:

<img width="1280" alt="2020-11-06_12-17-13" src="https://user-images.githubusercontent.com/43257211/98314760-ca51b600-202a-11eb-8b09-465dd7633a25.png">

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"filebeat-maximo-prod-*"}
{"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1604582412327,"lte":1604625612328,"format":"epoch_millis"}}}]}},"sort":{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},"script_fields":{},"aggs":{"2":{"date_histogram":{"interval":"15s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":1604582412327,"max":1604625612328},"format":"epoch_millis"},"aggs":{}}}}
```

**Comment by marefr** [comment]
Thanks. Looks like something isn't working as expected. Will let someone investigate this.

**Comment by aocenas** [comment]
@stevekatsaras With elastic we do 2 queries, as you can see in the request one normal document query and then separate aggregation for the date_histogram with the range you selected and should be without any limit and then we show in the histogram what ever came in the aggregation. Can you confirm that the aggregation returns only the visible part of the histogram and if so that there actually is more data in your elastic server (from you description I assume it's the case but want to make sure there is no misunderstanding)

**Comment by stevekatsaras** [comment]
> 
> 
> @stevekatsaras With elastic we do 2 queries, as you can see in the request one normal document query and then separate aggregation for the date_histogram with the range you selected and should be without any limit and then we show in the histogram what ever came in the aggregation. Can you confirm that the aggregation returns only the visible part of the histogram and if so that there actually is more data in your elastic server (from you description I assume it's the case but want to make sure there is no misunderstanding)

The Elasticsearch index that Grafana is performing the query & aggregation contains 30 days worth of data. To give you an example, we are running a filebeat agent that is tailing WebSphere application logs in production. It is a highly chatty system with events flowing almost every few seconds.

The screenshot and the aggregation query is only returning a visible part of the date histogram. Has this query been tested in Elasticsearch? I am requesting 12 hours worth of data in the date histogram and with an interval of 15s, I am curious whether Elasticsearch is putting some sort of limit.

**Comment by aocenas** [comment]
Right, the query seems to be right in the sense that we send correct timestamps for both aggregation and docs query. At the same time my assumption would be that the `"size":500` should only be applied to the docs query not the aggregation but maybe that's what's wrong and the size limit should be scoped differently. @Elfo404 do you know whether the size limit actually applies to aggregation part and if so how to limit only the docs query?

**Comment by stevekatsaras** [comment]
> 
> 
> Right, the query seems to be right in the sense that we send correct timestamps for both aggregation and docs query. At the same time my assumption would be that the `"size":500` should only be applied to the docs query not the aggregation but maybe that's what's wrong and the size limit should be scoped differently. @Elfo404 do you know whether the size limit actually applies to aggregation part and if so how to limit only the docs query?

Any updates on this?

**Comment by Elfo404** [comment]
@aocenas @steakunderscore I investigated this a bit, it looks like the histogram is built on the actual logs and not on the result of the aggregations.
We are not running 2 queries, but the query uses `extended_bounds` in the `date_histogram` aggregation, which means that along with logs (limited to 500) we'll also get a histogram containing the number (note: only the number) of matching documents over the whole time frame. But this is not enough to build the histogram as we won't be able to correctly display the log level since we are missing that piece of information.

Something we could possibly do is performing 2 queries, the first one would be the same we are performing right now without the extended bounds option as it won't be used, and the second one should have a `terms` aggregation over the configured `logLevel` field AND the same `date_histogram` aggregation of the first query. That way we would be able to get all the needed data.

We still need to check how to (and if we can) structure the dataframes for the ExploreLogPanel. This needs for sure more investigation.

**Comment by aocenas** [comment]
@davkal interesting point @Elfo404 mentions is that with the secondary aggregation query currently we don't even group by log level. I wonder if this worked before? I always thought that elastic was doing the aggregation query and got the correct grouping/coloring.

**Comment by ebabani** [comment]
This worked in Grafana 7.0.5. On that version the histogram did not have a breakdown by log level, it was just total documents over time.

**Comment by stevekatsaras** [comment]
> 
> 
> This worked in Grafana 7.0.5. On that version the histogram did not have a breakdown by log level, it was just total documents over time.

So is it right to assume then that latter versions of Grafana v7.0.5 have changed in terms of how it functionally works?

**Comment by stevekatsaras** [comment]
> 
> 
> > This worked in Grafana 7.0.5. On that version the histogram did not have a breakdown by log level, it was just total documents over time.
> 
> So is it right to assume then that latter versions of Grafana v7.0.5 have changed in terms of how it functionally works?

So is there any progress on this? Have the defect been identified? Is there a timeframe on when this will likely get fixed?

**Comment by aocenas** [comment]
@stevekatsaras We are not actively working on it at the moment. We fix bugs in each release based on priority and this may get fixed this release but I cannot say that with certainty right now.

**Comment by cdalexndr** [comment]
This issue is making log navigation really hard. 
If the graph was working, I could select a time range by dragging over a region on the graph, but now I have to manually enter start/end time ranges. 
Note that I **have** to select a new time range in order to view other entries beside the 500 shown.

This issue together with **fixed 500 doc limit** and **no pagination** support makes Grafana a bad candidate for elasticsearch log exploring (in favor of Kibana).

**Comment by diranged** [comment]
I believe this same issue is happening in the Grafana/Loki plugin. The histogram reflects _at most_ the amount of data returned by the query (default of 1000 log messages). If we set the picker to 1hr and we set our query-limit to something small like `100`, you can see we get a narrow histogram that is far smaller than 1 hour:

![image](https://user-images.githubusercontent.com/768067/106019973-15062b80-6078-11eb-89d8-752affd5e103.png)

Changing the result count to `500` changes the histogram timeline:

![image](https://user-images.githubusercontent.com/768067/106020013-23544780-6078-11eb-8e8e-11b6d49f4428.png)

This is a very unexpected and unintuitive behavior. I think it is reasonable to expect that the actual queries returned to the browser and printed out are going to be vastly different from the values that populate the histogram. The histogram should be populated with the actual count-data that the query returned.

Can we get this bug elevated in priority a bit?

**Comment by stevekatsaras** [comment]
Any progress on this issue?
This bug appears to be much wider than my initial post re: elasticsearch. Can we have this escalated? In my organisation, it's becoming very cumbersome to search an analyse the data ... it's not providing a pleasant experience to our users.

**Comment by Elfo404** [comment]
@grafana/observability-squad I'm removing the elasticsearch label as this seems to be a broader issue that in fact affects multiple datasources.

We are doing some research on how to improve that histogram visualization, but this behavior is indeed confusing/annoying.

> This worked in Grafana 7.0.5. On that version the histogram did not have a breakdown by log level, it was just total documents over time.

as per https://github.com/grafana/grafana/issues/28844#issuecomment-729591097 the reason this worked is that we were using a different visualization that only showed the number of entries over the specified time frame, not their level.

I feel we might need to define a generic interface to provide all the data needed for the histogram panel.

**Comment by M0rdecay** [comment]
Given this issue https://github.com/grafana/grafana/issues/22271, we now have no tool for working with logs :(
If the above issue is resolved, we would have the opportunity to build our own dashboards for analyzing logs

**Comment by stevekatsaras** [comment]
I'm curious why this issue has not been assigned yet, considering how many people are coming forward to verify this - with other datasources, not just Elasticsearch. I know in our organisation, it's making log search very difficult. I recommend raising the priority on this, assigning it to a development team and seeing how we can resolve it and get it released in the next version.

**Comment by aocenas** [comment]
Duplicate: https://github.com/grafana/grafana/issues/19949
