### ISSUE TITLE
possible to enable anonymous bind for ldap/active directory

### ISSUE THREAD

**Issue by mhiller** [grafana/grafana#2885]
I have everything working great with a user account to initiate the bind.However my company allows anonymous bind (since everything is internal) and its the preferred method by our infrastructure team for non-windows integrated apps.. Maybe i missed it but is there a way to enable this ? if not can you count this as a feature request ?

Thanks.

**Comment by torkelo** [comment]
You should be able to do this, 
http://docs.grafana.org/installation/ldap/#single-bind-example

**Comment by torkelo** [comment]
or leave bind_dn and bind_password empty

**Comment by mhiller** [comment]
ill give leaving it empty a go. Single bind through an exception from our DC. will report back.
