### ISSUE TITLE
Unable to verify external plugins in docker image 7.2.2

### ISSUE THREAD

**Issue by restlessankyyy** [grafana/grafana#28858]
**What happened**: Unable to migrate external plugin while upgrading 6.6.2 to 7.2.2

**What you expected to happen**: Plugins name: agenty-flowcharting-panel, larona-epict-panel, grafana-kubernetes-app, digiapulssi-breadcrumb-panel, jeanbaptistewatenberg-percent-panel,  simpod-json-datasource, ibm-apm-datasource, vonage-status-panel, jdbranham-diagram-panel, marcuscalidus-svg-panel, flant-statusmap-panel, should appear as signed and should be usable.

**How to reproduce it (as minimally and precisely as possible)**: Install grafana 7.2.2 on docker and install the described plugin 

**Anything else we need to know?**:

**Environment**: Docker 20
- Grafana version: 7.2.2
- Data source type & version: NA
- OS Grafana is installed on: Ubuntu and Centos
- User OS & Browser: Chrome / firefox / MS EDGE
- Grafana plugins: agenty-flowcharting-panel, larona-epict-panel, grafana-kubernetes-app, digiapulssi-breadcrumb-panel, jeanbaptistewatenberg-percent-panel,  simpod-json-datasource, ibm-apm-datasource, vonage-status-panel, jdbranham-diagram-panel, marcuscalidus-svg-panel, flant-statusmap-panel
- Others: [NA]([url](url)) 

![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/23651587/98231567-de2ee680-1f5c-11eb-920b-c42dd0bcabe9.png)

**Comment by aknuds1** [comment]
This isn't a bug though, as those plugins aren't signed. You can still use them, right? We don't have a community plugin signing story in place yet, I'm not sure exactly when it will be ready, most likely sometime next year.

**Comment by aknuds1** [comment]
Actually,  I spoke too fast about community plugin signing not being available yet. I haven't tried it, but it's apparently [supported](https://www.npmjs.com/package/@grafana/toolkit?activeTab=readme#sign-your-plugin) in grafana-toolkit already.
