### ISSUE TITLE
Embedding whole dashboards in other web sites

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#2887]
I would like to embed a whole Grafana dashboard (and not just a single graph) alongside non-time series data on my company's per-service dashboards. Would (or could) there be a way to embed a whole dashboard in another page without using an IFrame?

If our per-service dashboard were also an Angular app, would that make it easier to embed Grafana components into it?

**Comment by torkelo** [comment]
no, sorry grafana is not an angular library its a big application with backend frontend parts. You have to use an iframe :(
