### ISSUE TITLE
Make CloudWatch query timeout configurable

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#28878]
**What would you like to be added**:
Currently the query timeout is hardcoded in the datasource, but different users could have different requirements, so it would be useful for the timeout to be configurable from the CloudWatch data source configuration page.

**Comment by tommywo** [comment]
Yes, please. That would be useful. :)

**Comment by aocenas** [comment]
The timeout in question https://github.com/grafana/grafana/blob/0ae8a85828a511b12659b95e2f50de623217b51d/pkg/tsdb/cloudwatch/live.go#L140

**Comment by aocenas** [comment]
Closing this as we are not suing the "live" code path anymore and will be removed.
