### ISSUE TITLE
Dashboard Links with multiple tags

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#28870]
**What happened**:
The dropdown didn't return any links/related items

**What you expected to happen**:
A dropdown list

**How to reproduce it (as minimally and precisely as possible)**:
Configure multiple tags as follows:
![image](https://user-images.githubusercontent.com/1325158/98251205-1ba56b00-1f81-11eb-907c-33bf37dbaf3e.png)

**Anything else we need to know?**:
This is what happens and what you get when you click on the link:
![image](https://user-images.githubusercontent.com/1325158/98251162-0b8d8b80-1f81-11eb-96e4-fcdf0f180297.png)

**Environment**:
- Grafana version: 7.1
- Data source type & version: SQL Server
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Works when I test, you must have dashboards with all tags specified

**Comment by reuvygroovy** [comment]
We have
In fact when i split them into two different tags they each have a relevant menu.

**Comment by reuvygroovy** [comment]
Can anyone else test this? It doesn't work for me.

**Comment by reuvygroovy** [comment]
After following up on the [forum](https://community.grafana.com/t/multiple-tags-in-one-link/42551/10), this is reproducible, although the people who commented claimed this is by design, but to me it seems like a bug, or at least a feature that should be implemented.

Would love for the Grafana team to input their 2 cents since this confuses me greatly.
