### ISSUE TITLE
Admin/Editor users getting "Permission to edit panel denied" errors on some panels

### ISSUE THREAD

**Issue by bhozar** [grafana/grafana#28879]
**What happened**:
Anyone logged in as an editor or admin is unable to edit all panels. Going direct to the &editPanel URL throws a message: "*Permission to edit panel denied*". Clicking the title bar only displays limited items, and excludes edit: 
![image](https://user-images.githubusercontent.com/1184220/98261530-77b9c080-1f7c-11eb-948b-f1c7f90a9595.png)

Closest Issue item I could find is: https://github.com/grafana/grafana/issues/27302 but that applies to non-admin/editor users getting the error.

**What you expected to happen**:  Admins and editors should be able to edit the panel. All other panels are editable. 

**How to reproduce it (as minimally and precisely as possible)**: Have the issue on a couple of panels on dashboards, but cannot get any others to break.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 18/04
- User OS & Browser: Win10/Chrome
- Grafana plugins: None on this dashboard

**Comment by marefr** [comment]
Is the panel in question repeated by a variable? 

Otherwise, please provide the dashboard permissions applied to this dashboard and if applicable the permissions of the folder the dashboard is stored in.

**Comment by torkelo** [comment]
If the panel menu does not include the edit option, it could be that is'a repeated panel, only the source panel can be edited
