### ISSUE TITLE
Bar Gauge panel does not auto size with zero-value rows

### ISSUE THREAD

**Issue by Malcolm** [grafana/grafana#28883]
**What happened**:

Currently pulling data from PostgreSQL, if my dataset contains a 0-value the bars in the gauge do not auto size correctly.

In the attached GIF you can see the bars resize correctly on initial query, then when adding a new column with a 0 value the auto sizing of bars does not work correctly.  In my template, with real data, I see the behavior on the initial query result if there is a zero value.

![DemoRecording](https://user-images.githubusercontent.com/7921/98290958-62db2e00-1f78-11eb-8664-78b83f386637.gif)

Below is my production query, under the Display option I've set Calculation to "Max" (the union is to ensure I see all days of the week if a day isn't returned):

```sql
select
  time,
   case
      when day = '1' then 'Sun'
      when day = '2' then 'Mon'
      when day = '3' then 'Tue'
      when day = '4' then 'Wed'
      when day = '5' then 'Thu'
      when day = '6' then 'Fri'
      when day = '7' then 'Sat'
      end as day,
      max
from
(
  select 
    now() as time,
    to_char(to_timestamp(clock), 'D') as day,
    max(value_max)
  from
    trends_uint
  where
    itemid='xxxx' and clock >= 1601510400 AND clock <= 1604188799
  group by to_char(to_timestamp(clock), 'D')
  union
  select * from (VALUES (now(), '1', 0),(now(), '2', 0),(now(), '3', 0),(now(), '4', 0),(now(), '5', 0),(now(), '6', 0),(now(), '7', 0)) as t (time, day, max)
  order by day
) data
```

![Live Example](https://user-images.githubusercontent.com/7921/98291006-738ba400-1f78-11eb-8e51-e10d7ea004b0.png)

**What you expected to happen**:

For the bars to resize and color correctly 🙂

**How to reproduce it (as minimally and precisely as possible)**:

1. Create new Bar Gauge graph
1. Populate with data that contains zero values
1. If the expected behavior is observed add a 0-value return to a new row

**Environment**:
- Grafana version: v7.3.1 (6668161a88)
- Data source type & version: PostgreSQL Data Source - Native Plugin
- OS Grafana is installed on: Debian Buster
- User OS & Browser: Windows 10 & [Chrome 86.0.4240.183, Edge 86.0.622.56, Firefox 82.0.2]
- Grafana plugins: alexanderzobnin-zabbix-app:4.0.1
- Others:

**Comment by torkelo** [comment]
Here is where min max are calculated https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/field/fieldOverrides.ts#L192

**Comment by torkelo** [comment]
Fix merged to master! thanks for bringing this to our attention
