### ISSUE TITLE
Is it possible to have a metric filter based on YYYY-MM-DD for graph grouping?

### ISSUE THREAD

**Issue by dbuscaglia** [grafana/grafana#2888]
Rapidly, stat metric names could grow to the point where we would want to programmatically target just a smaller subset, is this currently possible?

**Comment by torkelo** [comment]
?? Could you describe what you are talking about? Please :)

Data source? Whats scenario? I mean ALL metric queries in grafana are already filtered by date range, that is of course needed (unless you have a manual entered influxdb query without where $timeFilter)

**Comment by dbuscaglia** [comment]
Yes, I would be happy to.  In fact, I could try and submit a patch for it.  The issue is, I want to essentially have a date wildcard.  I have a set of metrics per unique process ID that will grow very large over time.  Thus, I want to shard them by date in graphite, so when I do a wildcard graph grouping, it will only be interested in the date, where at most, a group of 30 or so metrics, will live.  A simple dropdown that says (Today) or some date filter that then would generate .YYYY-MM-DD. based on the current date would be awesome.
