### ISSUE TITLE
Stat panel center align doesn't work with longer text

### ISSUE THREAD

**Issue by kustodian** [grafana/grafana#28894]
**What happened**:
Stat panel that is displaying text doesn't align the text center if the text is a little longer:
![image](https://user-images.githubusercontent.com/1949229/98351746-68d71a80-201d-11eb-98e6-eea85de67a94.png)

If the text is shorter it looks good:
![image](https://user-images.githubusercontent.com/1949229/98351815-7f7d7180-201d-11eb-8339-a663375f8a28.png)

**What you expected to happen**:
The text should always be aligned center.

**How to reproduce it (as minimally and precisely as possible)**:
Here is the panel configuration:
```
{
  "datasource": "prometheus",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "dark-green",
            "value": null
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "gridPos": {
    "h": 2,
    "w": 3,
    "x": 0,
    "y": 3
  },
  "id": 253,
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "lastNotNull"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "textMode": "name",
    "colorMode": "value",
    "graphMode": "none",
    "justifyMode": "center"
  },
  "pluginVersion": "7.1.5",
  "targets": [
    {
      "expr": "node_gcp_info{job=\"node\", instance=~\"$node:$port\"}",
      "interval": "",
      "legendFormat": "{{ machine_type }}",
      "refId": "A"
    }
  ],
  "title": "Machine Type",
  "type": "stat",
  "timeFrom": null,
  "timeShift": null
}
```
I'm not sure how to exactly create panel with a static text like in the example.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10 x64/Chrome
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
I'm trying to understand what an alternative alignment would be possible (given that it's one word that does not fit in the panel).
How you would expect the text in the above first example to be aligned?

**Comment by kustodian** [comment]
The font size should be reduced so it can fit. That's what actually happens when I start to reduce the vertical size of the panel, but I can't reduce the size more than this, so I can see that it happens while I do the resizing while holding the right mouse button.

**Comment by mckn** [comment]
I have verified this behavior please have a look at attached video:


![Uploading Kapture 2020-11-06 at 15.46.41.gif…]()
