### ISSUE TITLE
Display plugin signature details

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#28900]
In #28899 we are implementing support for exposing the new plugin signature detail fields via the API.  The details of the plugin signature then need to be exposed in the UI.

@sarlinska has put together mockups for this

**Comment by marefr** [comment]
@dprokop I moved this to 8.0 milestone

**Comment by jackw** [comment]
Closing this as badges for signature signed / unsigned, signature level and org are now visible in plugin details view.
