### ISSUE TITLE
Minor spelling mistake.

### ISSUE THREAD

**Issue by snus-kin** [grafana/grafana#28903]
Hi, feel kinda bad making an issue for this but just thought I'd bring up that 'connect' is misspelt as 'conncet' here.

https://github.com/grafana/grafana/blob/2aafa3987960952cd558fc727978646f59faacc9/public/app/plugins/datasource/grafana/components/QueryEditor.tsx#L117

**Comment by papagian** [comment]
thank you for reporting it
