### ISSUE TITLE
Grafana on Apache2 Server

### ISSUE THREAD

**Issue by JulianDeb12** [grafana/grafana#2891]
Hi 
I installed Grafana on my Apache2 Server in  usr/share/grafana but now i can't get to the login page which url do I have to use?

**Comment by torkelo** [comment]
The root url should redirect you to login page. 

Is grafana-server running and is apache2 directly configured as a reverse proxy for the grafana-server web server?

**Comment by JulianDeb12** [comment]
I fixed it I was directly first but now I managed it with proxy thanks for your answer.
