### ISSUE TITLE
Y unit labels are randomly assigned to left or right

### ISSUE THREAD

**Issue by robomotic** [grafana/grafana#28911]
**What happened**:
Line chart with two different unit scales for example kWh on left and Celsius on right.

**What you expected to happen**:

The unit scales get randomly assigned either to left or right for both lines.

**How to reproduce it (as minimally and precisely as possible)**:

Please check my description here: https://community.grafana.com/t/bug-in-graph-panel-y-unit-label/38114

**Anything else we need to know?**:

No

**Environment**:
- Grafana version: v7.2.1 (72a6c64532)
- Data source type & version: InfluxDb
- OS Grafana is installed on: Raspbian
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: None

**Comment by torkelo** [comment]
We have no other reports like this, very strange. 

Can you include the panel json and query response? (panel.json)

**Comment by robomotic** [comment]
Sure here we go, I did a limit 10 otherwise the query output will be massive.

`
{
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/5/query",
    "params": {
      "db": "Glasgow2020",
      "q": "SELECT top(\"HeatMeter_kWh\", 2) AS \"HeatSupply\" FROM \"delta30m\" WHERE time >= 1576713600000ms and time <= 1582747200000ms GROUP BY time(1h) fill(null) LIMIT 10;SELECT top(\"BMS_Outdoor_T\", 2) AS \"Temperature\" FROM \"delta30m\" WHERE time >= 1576713600000ms and time <= 1582747200000ms GROUP BY time(1h) fill(null) LIMIT 10",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms",
    "hideFromInspector": false
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "delta30m",
            "columns": [
              "time",
              "HeatSupply"
            ],
            "values": [
              [
                1576713600000,
                0
              ],
              [
                1576717200000,
                0
              ],
              [
                1576720800000,
                0
              ],
              [
                1576724400000,
                0
              ],
              [
                1576728000000,
                0
              ],
              [
                1576731600000,
                0
              ],
              [
                1576735200000,
                0
              ],
              [
                1576738800000,
                300
              ],
              [
                1576742400000,
                250
              ],
              [
                1576746000000,
                400
              ]
            ]
          }
        ]
      },
      {
        "statement_id": 1,
        "series": [
          {
            "name": "delta30m",
            "columns": [
              "time",
              "Temperature"
            ],
            "values": [
              [
                1576713600000,
                5
              ],
              [
                1576715400000,
                5
              ],
              [
                1576717200000,
                5
              ],
              [
                1576719000000,
                5
              ],
              [
                1576720800000,
                5
              ],
              [
                1576722600000,
                5
              ],
              [
                1576724400000,
                5
              ],
              [
                1576726200000,
                5
              ],
              [
                1576728000000,
                5
              ],
              [
                1576729800000,
                5
              ]
            ]
          }
        ]
      }
    ],
    "executedQueryString": "SELECT top(\"HeatMeter_kWh\", 2) AS \"HeatSupply\" FROM \"delta30m\" WHERE time >= 1576713600000ms and time <= 1582747200000ms GROUP BY time(1h) fill(null) LIMIT 10;SELECT top(\"BMS_Outdoor_T\", 2) AS \"Temperature\" FROM \"delta30m\" WHERE time >= 1576713600000ms and time <= 1582747200000ms GROUP BY time(1h) fill(null) LIMIT 10"
  }
}
`
And attached the panel json data.

[grafana_unit_bug.txt](https://github.com/grafana/grafana/files/5523855/grafana_unit_bug.txt)

Please also notice how the Y axis on the right is also missing all the numbers.

Let me know if you need more info.

**Comment by eRudy** [comment]
Hello,

Same issue here, I get this:
![image](https://user-images.githubusercontent.com/5659571/99586757-6e067300-29e8-11eb-9aad-96717eb7ca0a.png)

while I set overrides which should change units :

![image](https://user-images.githubusercontent.com/5659571/99586848-8f675f00-29e8-11eb-8d40-50a04d388fc4.png)

And, Y axes units keep changing, even if I change set them to Ampers and Volts.

![image](https://user-images.githubusercontent.com/5659571/99587155-f9800400-29e8-11eb-8692-3742922ac29b.png)

I used an older version, and just upgraded to 7.3.3, same thing 😕

**Comment by torkelo** [comment]
Try removing the field overrides, and only use the legacy options in the first tab

**Comment by eRudy** [comment]
> Try removing the field overrides, and only use the legacy options in the first tab

I tried, in that case I can't have two different units. Left Y becomes "none", all series are associated to it, and right Y can be set to whatever we want, but no serie is associated to it.

**Comment by robomotic** [comment]
I can confirm same issue for me.

**Comment by dprokop** [comment]
@eRudy @robomotic I hope I understand your issue correctly. Just played with the latest version of Grafana and I'm able to get two separate Y-axis(left and right) and have different units[1]. Have you set your desired series to be displayed on the right y-axis [2]?

I also suggest trying out the [Time Series](https://grafana.com/docs/grafana/latest/panels/visualizations/time-series/#time-series-panel) beta panel which soon gonna replace the current graph panel. It solves the problem you are describing - it automatically assigns all but the first series to the right y-axis. And you can override that behaviour and set left y-axis to show all you different units [1, time series panel example]


[1]
```
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 357,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fieldConfig": {
        "defaults": {},
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "A-series"
            },
            "properties": [
              {
                "id": "unit",
                "value": "accG"
              }
            ]
          },
          {
            "matcher": {
              "id": "byName",
              "options": "B-series"
            },
            "properties": [
              {
                "id": "unit",
                "value": "areaMI2"
              }
            ]
          }
        ]
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "7.5.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [
        {
          "alias": "B-series",
          "yaxis": 2
        }
      ],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A"
        },
        {
          "hide": false,
          "refId": "B"
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Legacy graph",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "accG",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "areaMI2",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 10,
            "gradientMode": "none",
            "hideFrom": {
              "graph": false,
              "legend": false,
              "tooltip": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "never",
            "spanNulls": true
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "accG"
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "B-series"
            },
            "properties": [
              {
                "id": "unit",
                "value": "areaMI2"
              },
              {
                "id": "custom.axisPlacement",
                "value": "left"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 3,
      "options": {
        "graph": {},
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltipOptions": {
          "mode": "single"
        }
      },
      "pluginVersion": "7.5.0-pre",
      "targets": [
        {
          "refId": "A"
        },
        {
          "hide": false,
          "refId": "B"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Time Series panel",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 27,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Y-axis problem legacy graph",
  "uid": "HfO-cMlGz",
  "version": 3
}
```

[2] 
![image](https://user-images.githubusercontent.com/2376619/112995574-aa529880-916b-11eb-80f3-50636dab3d9c.png)
