### ISSUE TITLE
Panel link does not support non english simbols in URL

### ISSUE THREAD

**Issue by vryzhevsky** [grafana/grafana#28938]
**What happened**: Create panel and add link in links sections with russian simbols. Resulting link url skips russian simbols.
![image](https://user-images.githubusercontent.com/30687522/98554111-67be1b80-22b1-11eb-9344-7224a8794d36.png)

**What you expected to happen**:  Link url must be correct

**How to reproduce it (as minimally and precisely as possible)**:
Create new dashboard
Create panel inside dashboard
Go to links section of panel
Create new link with non english simbols
![image](https://user-images.githubusercontent.com/30687522/98553723-faaa8600-22b0-11eb-8dd6-eed4ecd39399.png)

**Anything else we need to know?**: no

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: any
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: any
- Others:

**Comment by papagian** [comment]
The russian characters need to be URL encoded. Check [here](https://play.golang.org/p/WDyH7GZkULS) for an example how to encode them.

**Comment by vryzhevsky** [comment]
> The russian characters need to be URL encoded. Check [here](https://play.golang.org/p/WDyH7GZkULS) for an example how to encode them.

How to use it in Grafana???

**Comment by papagian** [comment]
change the link to something like:
`http://grafana?var-ruvar=<url encoded russian characters>&var-engvar=test_variable`
eg:
`http://grafana?var-ruvar=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82+%D0%BC%D0%B8%D1%80&var-engvar=test_variable`

**Comment by vryzhevsky** [comment]
> change the link to something like:
> `http://grafana?var-ruvar=<url encoded russian characters>&var-engvar=test_variable`
> eg:
> `http://grafana?var-ruvar=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82+%D0%BC%D0%B8%D1%80&var-engvar=test_variable`

It is impossible because this can go from dashboard variable wich can go from query for datasourse. There is no place for manual encoding this value. I placed direct value in this case just for simplifying.

**Comment by hugohaggmark** [comment]
> > change the link to something like:
> > `http://grafana?var-ruvar=<url encoded russian characters>&var-engvar=test_variable`
> > eg:
> > `http://grafana?var-ruvar=%D0%9F%D1%80%D0%B8%D0%B2%D0%B5%D1%82+%D0%BC%D0%B8%D1%80&var-engvar=test_variable`
> 
> It is impossible because this can go from dashboard variable wich can go from query for datasourse. There is no place for manual encoding this value. I placed direct value in this case just for simplifying.

Have you tried to use [percentencode](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#percentencode)

**Comment by vryzhevsky** [comment]
This works, thank you!

**Comment by hugohaggmark** [comment]
> This works, thank you!

Glad I could help!
