### ISSUE TITLE
Leaving grafana open in a tab results in Timeseries data request error, refresh fixes

### ISSUE THREAD

**Issue by joshrendek** [grafana/grafana#2893]
When I leave Grafana open in a tab and after a while going back to that tab, all graphs are dead and the "Timeseries data request error" is shown.

Grafana v2.1.3
InfluxDB 0.9.x set to proxy

Refreshing brings all graphs back up and everything works again.

Here is example debug data from the Chrome network tab:

```
Failed to load resource: the server responded with a status of 401 (Unauthorized)
app.bd986dd5.js:11 Objectmesssage: "InfluxDB Error: undefined"__proto__: Object(anonymous function) @ app.bd986dd5.js:11
app.bd986dd5.js:11 Object(anonymous function) @ app.bd986dd5.js:11
```

**Comment by torkelo** [comment]
whats your authentication settings, sessions store settings?

**Comment by joshrendek** [comment]
Session settings:

```
session	
cookie_name	grafana_sess
cookie_secure	false
gc_interval_time	
provider	file
provider_config	sessions
session_life_time	86400
```

Auth is set to basic.

I setup a playlist last night to switch between dashboards and this morning its still working as well.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/commit/c831369974f0cbbacd72678184a7fa73589d7a41
