### ISSUE TITLE
Sigv4 returns 403 when running from EKS with IAM role for service Accounts

### ISSUE THREAD

**Issue by carlosfrancia** [grafana/grafana#28931]
We are running Grafana from an AWS EKS cluster (v1.18) and connecting to AWS Elastic Search service version 7.7.

We are using Service accounts and IAM roles in our pod (https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts.html)

At the moment we are successfully connecting to ElasticSearch with aws-sigv4-proxy as a sidecar container using the proxy URL as URL:

![image](https://user-images.githubusercontent.com/28731961/98538214-56114f80-2282-11eb-9bf2-1a057dc74ebe.png)

When we change to use the ElasticSearch endpoint and enable Sigv4:

![image](https://user-images.githubusercontent.com/28731961/98538563-d9cb3c00-2282-11eb-899a-f65bb1f4ff0f.png)

We get 403:

![image](https://user-images.githubusercontent.com/28731961/98538625-f5364700-2282-11eb-9fdf-bc1de7e960d7.png)

Not relevant error other than request completed with 403 response:

`info msg="Request Completed" logger=context userId=39 orgId=1 uname=----- method=GET path=------- status=403 remote_addr=------- time_ms=3175 size=141 referer=https://grafana.------`

**What happened**:

Can't use Sigv4 in our Elastic Search Data Source when running Grafana from Eks with IAM roles for Service Accounts

**What you expected to happen**:

Able to use new Sigv4 feature and remove our aws-sigv4-proxy

**How to reproduce it (as minimally and precisely as possible)**:

Add Grafana to an EKS cluster with a service account and IAM role and try to connect to ES using Sigv4.

For clarity: and in case it helps: https://docs.aws.amazon.com/eks/latest/userguide/specify-service-account-role.html

**Comment by aknuds1** [comment]
@wbrowne Is this related to what you worked on?

**Comment by wbrowne** [comment]
Thanks for creating this issue @carlosfrancia, would be happy to take a look. Would you be able to provide response info from the browser? I'm not super familiar with service accounts - but I'm assuming you're using the `Assume Role` option for authentication?

**Comment by carlosfrancia** [comment]
Hey @wbrowne thank you for you quick response. So we are no assuming a role ourselves but we are using IAM roles for service accounts within EKS. That means we create our role, link it to our Service Account and our Pod gets the required credentials, they are stored in AWS_WEB_IDENTITY_TOKEN_FILE and AWS_ROLE_ARN environment variables. In order to send the Sigv4 request to ElasticSearch we send the request to a aws_sigv4 proxy (https://github.com/awslabs/aws-sigv4-proxy) which is signing our requests and sending them to ES. 

You can find a technical overview of IAM roles for service accounts in here: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-technical-overview.html. Note also that this are the minimum supported aws sdk versions: https://docs.aws.amazon.com/eks/latest/userguide/iam-roles-for-service-accounts-minimum-sdk.html. 

From the above you can see:

"The containers in your pods must use an AWS SDK version that supports assuming an IAM role via an OIDC web identity token file."

Hope it helps

**Comment by wbrowne** [comment]
Thanks for the further info @carlosfrancia - will find some time to go further into the details. In the meantime, one thing that would be helpful to debug further would be to provide the Grafana backend response info IE the info from the 403 response you mentioned. That will usually give more insight into the response we get from AWS (if that is indeed where the problem lies).

**Comment by carlosfrancia** [comment]
Hey @wbrowne I am using Chrome and the response from the 403 is: `User: arn:aws:sts::XXXXXXXX:assumed-role/XXXXXt/i-XXXXXXXX is not authorized to perform: es:ESHttpGet`. I think the request is reaching ES but it's not being signed. Let me know if there is anything else I can do to help

**Comment by carlosfrancia** [comment]
Hey @wbrowne did a bit investigation my side. The issue is that role role being assumed is not the Pod'd role but the instance's role (which is incorrect and isn't authorised). 

The problem seems to be here: https://github.com/grafana/grafana/pull/27552/files?file-filters%5B%5D=.go#diff-6c28df9ff45e6a4894e4fedfc6e3b823cb5d5cc6f78af7f3431186ed18e4f327R102 

`defaults.CredChain` method can't be used with web identity token: https://github.com/aws/aws-sdk-go/issues/3218

**Comment by wbrowne** [comment]
Yeah @carlosfrancia, I had a feeling the default authentication is not the right approach in this case. As you want to sign the request as the K8s Pod instead, would it make sense for you to specify the Pod IAM Role ARN in the field for `Assume Role ARN` in the SigV4 options (presumably using the same `AWS_ROLE_ARN` you used with the proxy before)? This is a similar approach to what is done in the AWS proxy (see [Grafana](https://github.com/grafana/grafana/pull/27552/files?file-filters%5B%5D=.go#diff-6c28df9ff45e6a4894e4fedfc6e3b823cb5d5cc6f78af7f3431186ed18e4f327R91) vs [AWS](https://github.com/awslabs/aws-sigv4-proxy/blob/1d33032a68a187a96360bea986c1fe01b4e4a5af/main.go#L43)).  I'm not familiar with web identity so let me know if this makes sense for your case

**Comment by wbrowne** [comment]
More info: Just found https://github.com/awslabs/aws-sigv4-proxy/pull/19 which seems to suggest upgrading the AWS SDK dependency >= `1.23.13` will allow the default credentials chain to use the web identity token file. However, Grafana is already running `1.33.12` 🤔

**Comment by carlosfrancia** [comment]
Hey! I already tried specifying POD IAM Role ARN but I am getting 502 I am afraid. I also checked the sdk version and you are far ahead so that's not a problem.

I think I would look into using `session.NewSession()` as suggested in here: https://github.com/aws/aws-sdk-go/issues/3218#issuecomment-627684419

**Comment by wbrowne** [comment]
Howdy @carlosfrancia. I have a [branch](https://github.com/grafana/grafana/tree/sigv4-web-identity) with a potential fix if you want to try it out and let me know 😄

**Comment by carlosfrancia** [comment]
Hey @wbrowne are you able to push the branch to a public docker image? I would be happy to try it out for you

**Comment by wbrowne** [comment]
@carlosfrancia https://wbrowne.s3.eu-central-1.amazonaws.com/grafana-sigv4-web-identity.tar

**Comment by carlosfrancia** [comment]
@wbrowne Sorry for the confusion, for me to test I would need the Docker image  in a public repository, are you able to push this image to the Grafana Docker repo (which I can trust)? Otherwise I can wait until the next beta release candidate and test it out for you. 

By the way, had a quick look at the change and it looks good to me.

**Comment by aknuds1** [comment]
> @wbrowne Sorry for the confusion, for me to test I would need the Docker image in a public repository, are you able to push this image to the Grafana Docker repo (which I can trust)? Otherwise I can wait until the next beta release candidate and test it out for you.

Is this because you have to point EKS at a Docker registry?

**Comment by carlosfrancia** [comment]
Yes, we actually mirror a docker image from a trusted public docker repo and we pull from our mirror in our eks cluster

**Comment by wbrowne** [comment]
@carlosfrancia let me see what I can do. Can you provide the details for your setup so I make sure to prep the correct image?

**Comment by carlosfrancia** [comment]
Sure, we pull from Grafana official image from https://index.docker.io/r/grafana/grafana that's all we do, then we point to the image from our deployment kubernetes file with out configuration. Somehow I am getting 404 from https://index.docker.io/r/grafana/grafana but that's maybe something you can look at?

**Comment by wbrowne** [comment]
Okay, I have tagged the image in our repo - `grafana/grafana:sigv4-web-identity`. Let me know how you get on!

**Comment by carlosfrancia** [comment]
@wbrowne I can confirm that is working!! 🎉

**Comment by wbrowne** [comment]
Great news @carlosfrancia! Thanks a lot for testing it out and raising this issue in the first place. I'll get a fix merged and you'll hopefully see it in the next patch release 😄
