### ISSUE TITLE
Font color Bug in stats panel

### ISSUE THREAD

**Issue by suikast42** [grafana/grafana#28932]
I updated my container today to grafana 7.3.1

The stats panel in full color mode had in the pririo version I have used ( 7.1.3 ) always the font color white. 
Now ith depends on the foreground color. Sometimes its white and somtetimes it's black. 

![image](https://user-images.githubusercontent.com/5046525/98540652-924aad00-228e-11eb-8dcb-72a00f68de04.png)
![image](https://user-images.githubusercontent.com/5046525/98540709-a2628c80-228e-11eb-91b3-b257e20b22ab.png)

**Environment**:
- Grafana version: 7.3.1

**Comment by torkelo** [comment]
This is tweaked in coming 7.3.2
