### ISSUE TITLE
Add a React-compatible datetime picker to the UI library

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#28943]
**What would you like to be added**:
Add a datetime picker to the UI library, so that plugin developers can include this component in new plugins based on React js library.

**Why is this needed**:
To allow adding a datetime picker to custom plugins.

Per customer comment:

> I have a custom panel plugin and I need to add a time picker in the options menu. In the Angular framework I was able to add an input field of type datetime-local in the options html. However in the react framework I don't see any equivalent to this. 

Screenshot of Angular-based datetime picker, which might serve as inspiration for what is needed:
![image](https://user-images.githubusercontent.com/10763196/98572516-b9e84800-2283-11eb-8311-33672e81eb2a.png)

**Comment by zoltanbedi** [comment]
This looks like a simple https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/datetime-local you can use the Input component from Grafana with a type `datetime-local`.
