### ISSUE TITLE
Change row color based on the single panel color

### ISSUE THREAD

**Issue by AGirin** [grafana/grafana#2895]
We are using grafana dashboards on a regular basis. What we have come up with is dashboard of dashboards.

This global view dashboard uses single stats panels to display most significant metric from the dashboard underneath. We set some thresholds and if panel turns orange or red we can click on it and go to more detailed dashboard.

What we find is that this global view dashboard becomes larger and larger as we add more compontes to it. So here is something that would be nice to have:

It wold be nice to have ROWs change their colors based on the color of single panels on that row. This way we can minimize all rows and still have a nice view and if one of the panels on that row goes orange or red row color would change to that color. This way we save a lot of screen space and still able to see issues if they arise.

![capture](https://cloud.githubusercontent.com/assets/5177657/10350588/78b5797c-6d0a-11e5-9a66-79eef8556c6f.PNG)

I hope this makes sense.

**Comment by torkelo** [comment]
but a row that is collapsed does not have any panels loaded, so how can it change color when there is no panel loaded (no metric queries)?

**Comment by torkelo** [comment]
might be handled by

**Comment by torkelo** [comment]
sorry, might be handled by alerting at some point in the future

**Comment by AGirin** [comment]
Maybe it makes sense to enable the option to load panels in the background? Anyway - thanks for looking at this.
