### ISSUE TITLE
Variables: Chained query variables using __value/__text not consistently resolved from dashboard link 

### ISSUE THREAD

**Issue by stefan-kr** [grafana/grafana#28965]
**What happened:**
In Grafana 7.3.1 I setup nested query variables in dashboards using __text and __value  columns using PostgreSQL as a data source. When the variables are passed via a dashboard link they are not resolved consistently. Often but not always the content of the __value column is shown instead of the __text column. This also breaks the proper resolution of nested variable hierarchy.

__value instead of __text content:
![grafana-7-3-1-variable-issue-a](https://user-images.githubusercontent.com/47065443/98655671-04c79580-2340-11eb-9ce2-ac73b15ea9bf.png)
Wrong resolution of hierarchy:
![grafana-7-3-1-variable-issue-b](https://user-images.githubusercontent.com/47065443/98655682-08f3b300-2340-11eb-8c0b-9ed2e666f837.png)
Wrong resolution of hierarchy in case a varialbe is assigned the "All"-value:
![grafana-7-3-1-variable-issue-c](https://user-images.githubusercontent.com/47065443/98655691-0abd7680-2340-11eb-9190-107da717b99f.png)

**What you expected to happen:**
Only display the content of the __text column for nested variable columns. Resolve dependencies between the nested columns as expected. Using deep nested variable hierarchies and passing the values via the dashboard link worked like a charm in 6.7.

**How to reproduce it (as minimally and precisely as possible):**

- Setup PostgreSQL data source:
```
CREATE TABLE hierarchy_level_1 (
	level_1_id int PRIMARY KEY,
	level_1_name text
);

CREATE TABLE hierarchy_level_2 (
	level_2_id int PRIMARY KEY,
	level_2_name text,
	level_1_id int,
	CONSTRAINT level_2_to_level_1_fk
		FOREIGN KEY (level_1_id)
		REFERENCES hierarchy_level_1(level_1_id)
);

INSERT INTO hierarchy_level_1 (level_1_id , level_1_name ) VALUES
	(1, 'testA'),
	(2, 'testB');
	
INSERT INTO hierarchy_level_2 (level_2_id, level_2_name, level_1_id ) VALUES
	(1, 'testA1', 1),
	(2, 'testA2', 1),
	(3, 'testA3', 1),
	(4, 'testB1', 2),
	(5, 'testB2', 2);
```

- Setup nested variables:
```
"templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": true,
          "tags": [],
          "text": [
            "testA"
          ],
          "value": [
            "1"
          ]
        },
        "datasource": "Master Data",
        "definition": "SELECT level_1_id __value, level_1_name __text FROM hierarchy_level_1;",
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": "Level 1",
        "multi": true,
        "name": "level1",
        "options": [],
        "query": "SELECT level_1_id __value, level_1_name __text FROM hierarchy_level_1;",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      },
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "All",
          "value": "$__all"
        },
        "datasource": "Master Data",
        "definition": "SELECT level_2_id __value, level_2_name __text FROM hierarchy_level_2 WHERE level_1_id IN ($level1)",
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": "Level 2",
        "multi": true,
        "name": "level2",
        "options": [],
        "query": "SELECT level_2_id __value, level_2_name __text FROM hierarchy_level_2 WHERE level_1_id IN ($level1)",
        "refresh": 2,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
```
- Refresh dashboard link with variables several times: https://my-grafana-domain.io/grafana/d/k7VHcXhMk/issue-with-variables?orgId=1&var-level1=1&var-level2=3

**Anything else we need to know?:**
There seems to be some kind of race condition as there is no consistent behaviour. When I refresh a dashboard link with a 4 level variable hierarchy several times, often different variables show the content of the __value column (except the one on the top level). Also hierarchies which have resolved almost immediately in Grafana 6.7 take several seconds to be resolved in 7.3.1.

**Environment:**
- Grafana version: 7.3.1 (Docker container grafana/grafana:7.3.1-ubuntu)
- Data source type: PostgreSQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Firefox, Chrome, Edge

**Comment by torkelo** [comment]
Can you try 7.3.4 ? We think this is fixed. Please ping me if you still having the same issue

**Comment by stefan-kr** [comment]
> Can you try 7.3.4 ? We think this is fixed. Please ping me if you still having the same issue

Yes, it works without any problem with 7.3.4. Thank you very much for fixing it!
