### ISSUE TITLE
"Template variables could not be initialised" error in specific dashboard

### ISSUE THREAD

**Issue by EliMutchnik** [grafana/grafana#28979]
**What happened**:
After upgrading to Grafana 7.1.1 we are getting Templating error on every refresh of the dashboard:
`Templating
Template variables could not be initialized: block: 01EPQVDJDHERZYD91X373RGZF6: get postings entry: invalid checksum`

![image (1)](https://user-images.githubusercontent.com/509879/98678435-3bfd6d00-2367-11eb-948d-53961d15115e.png)

- Grafana version: 7.1.1
- OS Grafana is installed on: "Debian 9" 
- User OS & Browser: macOS 10.15.7
- Data Sources: PostgresDB & Prometheus

**Comment by torkelo** [comment]
This looks like backend error in your variable query, check your query and grafana server log
