### ISSUE TITLE
Flux query returning "dead has unknown data type boolean" error

### ISSUE THREAD

**Issue by Tomica-G** [grafana/grafana#28976]
**What happened**:
The Flux query returns an error in Grafana:

`dead has unknown data type boolean`

The query in question:
```
import "influxdata/influxdb/monitor"
import "experimental"
from(bucket: "****")
|> range(start: -2w)
|> filter(fn: (r) => r._measurement == "ingress")
|> group(columns: ["train"])
|> monitor.deadman(t: experimental.subDuration(d: 135m, from: now() ))
|> filter(fn: (r) => r.dead == true)
```

![flux_dead](https://user-images.githubusercontent.com/56955081/98677396-3ef36000-235d-11eb-8f09-756792f63009.png)

**What you expected to happen**:
No error message. Should show the dead nodes.

**Environment**:
- Grafana version: 7.3.1-1 
- Data source type & version: Influxdb Version = 1.8.3
- OS Grafana is installed on: Amazon Linux 2 - Latest x86_64
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ryantxu** [comment]
What do the results of this query look like when plugged direclty in to chronograph?  The CSV?

The error is from the influx client:
https://github.com/influxdata/influxdb-client-go/blob/master/api/query.go#L388

The best way to fix is to have a small sample of output that we can build a test around.  Like:
https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/flux/testdata/simple.csv

**Comment by Tomica-G** [comment]
I'm adding a requested result in .csv 


[2020-11-11-00-07 Chronograf Data.zip](https://github.com/grafana/grafana/files/5523728/2020-11-11-00-07.Chronograf.Data.zip)

**Comment by ivanahuckova** [comment]
Closed in https://github.com/grafana/grafana/pull/29310
