### ISSUE TITLE
Datasources: Support pagination in data query UX controls

### ISSUE THREAD

**Issue by srclosson** [grafana/grafana#28978]
A problem becoming increasingly relevant in the enterprise plugins is the large datasets being used by customers. The API's for these controls always support pagination, but since the controls don't support pagination, we end up doing these monolithic requests that take both time and resources, and are not really sustainable.

This is a request to have plugin UX components support pagination, and allow us to interact with API's both through pagination or through a search (which will also send an asynchronous resource request to the backend).

**Comment by torkelo** [comment]
would be interesting to know more in what way the platform needs to support pagination. like next and prev buttons for every panel? 
@ryantxu  any ideas what this could imply?

**Comment by mckn** [comment]
@srclosson this sounds like an awesome idea! Do you have any examples or some more context on how this would work? I can think of several places where we would need pagination so not sure which of those you are referring to.

**Comment by srclosson** [comment]
@toddtreece @scottlepp I know both of you have run into this recently. Would either of you be able to document your use cases?

**Comment by srclosson** [comment]
@mckn, For dynatrace, this would be awesome! Currently, we have to query all of the metrics, but this can be very cumbersome. Dynatrace natively supports pagination. This is a good example:

https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/get-all-metrics/

You can see there is a page size, and then a `nextPageKey`. If the control even just had forward/backward buttons that when clicked executed a function, it would allow us to handle most situations.

**Comment by mckn** [comment]
> @mckn, For dynatrace, this would be awesome! Currently, we have to query all of the metrics, but this can be very cumbersome. Dynatrace natively supports pagination. This is a good example:
> 
> https://www.dynatrace.com/support/help/dynatrace-api/environment-api/metric-v2/get-all-metrics/
> 
> You can see there is a page size, and then a `nextPageKey`. If the control even just had forward/backward buttons that when clicked executed a function, it would allow us to handle most situations.

This is great! Thanks!
