### ISSUE TITLE
CLI: Admin password can fail if it contains some characters

### ISSUE THREAD

**Issue by Porkepix** [grafana/grafana#28996]
**What happened**: Password in the .ini file didn't worked, neither did it then by using `grafana-cli admin reset-admin-password`

**What you expected to happen**: Password should have been correctly set

**How to reproduce it (as minimally and precisely as possible)**:
Have `admin_password`in `grafana.ini` to include parentheses, same with `grafana-cli admin reset-admin-password`.
This shouldn't cause the error you can see below. At the very least if password have characters restrictions, this should be documented.

**Anything else we need to know?**:
CLI result:
```
$ sudo grafana-cli admin reset-admin-password '('
/usr/sbin/grafana-cli: eval: line 39: syntax error near unexpected token `('
/usr/sbin/grafana-cli: eval: line 39: `/usr/share/grafana/bin/grafana-cli --homepath=/usr/share/grafana       --config=/etc/grafana/grafana.ini       --pluginsDir=/var/lib/grafana/plugins       --configOverrides='cfg:default.paths.provisioning=/etc/grafana/provisioning                         cfg:default.paths.data=/var/lib/grafana                         cfg:default.paths.logs=/var/log/grafana                         cfg:default.paths.plugins=/var/lib/grafana/plugins' admin reset-admin-password ('
```

**Environment**:
- Grafana version: 7.3.1
- OS Grafana is installed on: Linux
- Grafana plugins: None, fresh install

**Comment by Porkepix** [comment]
New try with yet another password generated from KeePassXC :
```
sudo grafana-cli admin reset-admin-password '#"U:n;O.R7Gi^:1~y+1Y'
INFO[11-10|18:06:37] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[11-10|18:06:37] Starting DB migrations                   logger=migrator
Error: ✗ new password is too short
```

**Comment by papagian** [comment]
I'm unable to reproduce it:
```
# ./bin/grafana-cli admin reset-admin-password '('
INFO[11-11|10:30:31] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[11-11|10:30:31] Starting DB migrations                   logger=migrator
Error: ✗ new password is too short
# ./bin/grafana-cli admin reset-admin-password '(admin)'
INFO[11-11|10:30:41] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[11-11|10:30:41] Starting DB migrations                   logger=migrator

Admin password changed successfully ✔

# ./bin/grafana-cli admin reset-admin-password '#"U:n;O.R7Gi^:1~y+1Y'
INFO[11-11|10:31:30] Connecting to DB                         logger=sqlstore dbtype=sqlite3
INFO[11-11|10:31:30] Starting DB migrations                   logger=migrator

Admin password changed successfully ✔
```

How have you instal/run grafana and can you share your grafana.ini?

**Comment by Porkepix** [comment]
Nothing special: it's installed through https://github.com/cloudalchemy/ansible-grafana/ which uses the .deb.
I didn't do fine tuning/configuration yet so it uses default set values.

**Comment by papagian** [comment]
I was able to reproduce it in ubuntu by installing grafana using the deb package.

**Comment by aknuds1** [comment]
@papagian Does it happen because of the CLI wrapper shell script?

**Comment by papagian** [comment]
yes, I believe that that the problem is in this line:
https://github.com/grafana/grafana/blob/040cfe074f2a99bff78523f13041418142445136/packaging/wrappers/grafana-cli#L39

note in the below error that left quote is missing before the new password value:
`/usr/sbin/grafana-cli: eval: line 39: `/usr/share/grafana/bin/grafana-cli --homepath=/usr/share/grafana       --config=/etc/grafana/grafana.ini       --pluginsDir=/var/lib/grafana/plugins       --configOverrides='cfg:default.paths.provisioning=/etc/grafana/provisioning                         cfg:default.paths.data=/var/lib/grafana                         cfg:default.paths.logs=/var/log/grafana                         cfg:default.paths.plugins=/var/lib/grafana/plugins' admin reset-admin-password ('
`
