### ISSUE TITLE
Improve GCP IAP session expiry scenario with Grafana UI

### ISSUE THREAD

**Issue by mcallaghan-bsm** [grafana/grafana#28997]
**Why is this component needed**:

The current handling of IAP session expiry results in a very poor user experience.
It would seem, for grafana instances configured for GCP IAP integration for Google Authentication, the session can timeout, and then the grafana UI goes crazy with a bunch of "Unauthorized" dialogues, AND (in Chrome), a dialogue prompt is thrown up blocking all Chrome windows until the users clicks  "Leave" or "Cancel" (and the dialogue continues to throw forever unless they hit "Prevent" and leave)

I believe this is because it is trying to navigate back to login page to re-authenticate through IAP.

![2020-11-10_102933](https://user-images.githubusercontent.com/48924626/98709463-67289200-2350-11eb-8ef5-3c277d443405.png)

___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

Consider the configuration of Grafana with Google IAP (Identiy Aware Proxy) integration:
https://medium.com/google-cloud/practical-monitoring-with-prometheus-grafana-part-iv-d4f3f995cc78

![2020-11-10_122958](https://user-images.githubusercontent.com/48924626/98709567-8d4e3200-2350-11eb-9bf5-16695612644f.png)

TIP: read: https://cloud.google.com/iap/docs/sessions-howto#expired_session_responses

___
- [x] Post screenshots possible.
- [x] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by nohn** [comment]
This happens with any authentication using some kind of session mechanism happening in some frontend proxy, for example OAuth module in NGINX, Apache as well as commercial "HTTPS VPNs".

**Comment by dm3ch** [comment]
Still actual for any kind of Identity Aware Proxy usage, for example use with Cloudflare Access to secure you self-hosted grafana
