### ISSUE TITLE
Variables: Textbox variable always updates the default value when saving the dashboard

### ISSUE THREAD

**Issue by rdxmb** [grafana/grafana#28991]
**What happened**:

When saving a dashboard, the value of variables are saved as dashboard default values, regardless the checkbox `Save current variable values as dashboard default` is chosen or not.

**What you expected to happen**:

Will only save as default when chosen.

**How to reproduce it (as minimally and precisely as possible)**:

* create a dashboard with variables
* change the value in the dashboard
* save without activating the checkbox
* reload or logout/login

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.3.1
- Data source type & version: influxdb 1.8
- OS Grafana is installed on: Docker official image

**Comment by torkelo** [comment]
Not able to replicate. if you reload the variable state will still be part of the URL. You have to remove your current variable value selection from the URL

**Comment by rdxmb** [comment]
@torkelo Thanks for your answer. This is not the problem. Please see what's happening here:

![1-create-var](https://user-images.githubusercontent.com/30314040/98722518-6fed8800-2391-11eb-9b69-801a4357520e.gif)
![2-change-var](https://user-images.githubusercontent.com/30314040/98722537-77149600-2391-11eb-874e-435057bc5cc7.gif)
![3-shorten-url](https://user-images.githubusercontent.com/30314040/98722551-7da30d80-2391-11eb-9316-58466624cda8.gif)
![4-result](https://user-images.githubusercontent.com/30314040/98722569-8398ee80-2391-11eb-82e1-97c253b528b9.gif)

**Comment by rdxmb** [comment]
> Using the variable type text box is just an example here to demonstrate. This can also be reproduced with Query, for example.

**Comment by hugohaggmark** [comment]
> > Using the variable type text box is just an example here to demonstrate. This can also be reproduced with Query, for example.

I can't repro this for a Query variable, would like if @rdxmb could explain more about this case. Thank you

**Comment by rdxmb** [comment]
@hugohaggmark cannot reproduce with query by now. Maybe this was a special case I do not remember. Thanks for fixing this in Textbox :+1:
