### ISSUE TITLE
AlertingNG: Create minimal instance state tracker

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#28995]
The instance state tracker ingests the output from evaluations to determine the state of an alert instance. It is different from the evaluator in that it can determine the state for alert instances based on previous evaluations. It therefore can detect changes in state, and save them.

Once we have the scheduler and are logging evaluations (https://github.com/grafana/grafana/issues/28994), we will want to do something at least slightly more interesting, like only log on instance state changes.

More design is needed on this component, but we can build the foundation of a saving instance states by not supporting things like unknown, FOR, and have an instance tracker the saves changes per instance on the boolean of firing or not.

**Comment by ryantxu** [comment]
@kylebrandt is this still valid?  we keep moving the milestone, but I assume it is already done

**Comment by kylebrandt** [comment]
Done+ curiosity of @davidmparrott
