### ISSUE TITLE
AlertingNG: Support Per Query Relative Time Ranges.

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#29000]
In the case of alerting (although we may want to look at this elsewhere) the time range is:

 - Per Query
 - Always Relative (e.g. 5m-ago to now)

The current backend for alerting accepts integer of seconds for this:

```
"relativeTimeRange": {
          "From": 2592000,
          "To": 0
 }
```

This way people will be able to compare a query that was from a previous period to the current period.

This probably depends on https://github.com/grafana/grafana/issues/27703, unless we want to do it everywhere, but then we would have to figure out how it fits in with the global timeshift that applies to all queries. So might make sense to try it in the case of alerting first.

Expect we will add it the query bar:

![image](https://user-images.githubusercontent.com/1692624/98717826-998bbc80-235b-11eb-90a6-ebab2c725f25.png)

**Comment by peterholmberg** [comment]
Closed via https://github.com/grafana/grafana/pull/33689
