### ISSUE TITLE
The alert interval does not follow the set of Evaluate every

### ISSUE THREAD

**Issue by xieziqiang** [grafana/grafana#29012]
**What happened**:
I hava 30 alert rules, [Evaluate every] is set to 5m. And the alert scheduler does not run every 5 minutes, the interval will always be greater than 5 minutes.
I found a same report: #22375

**What you expected to happen**:
 I expect the alert scheduler to run close to the set of [Evaluate every]

**How to reproduce it (as minimally and precisely as possible)**:
Configure multiple alerts with the same evaluation period (I have 30 alerts，Evaluate every 5m For 0m) 

**Anything else we need to know?**:
`
func (s *schedulerImpl) Tick(tickTime time.Time, execQueue chan *Job) {
	now := tickTime.Unix()

	for _, job := range s.jobs {
		if job.GetRunning() || job.Rule.State == models.AlertStatePaused {
			continue
		}

		if job.OffsetWait && now%job.Offset == 0 {
			job.OffsetWait = false
			s.enqueue(job, execQueue)
			continue
		}

		// Check the job frequency against the minimum interval required
		interval := job.Rule.Frequency
		if interval < setting.AlertingMinInterval {
			interval = setting.AlertingMinInterval
		}

		if now%interval == 0 {
			if job.Offset > 0 {
				job.OffsetWait = true
			} else {
				s.enqueue(job, execQueue)
			}
		}
	}
}
`
By the source code, I found When the interval reached, you still need to wait for the offset. When the offset is large, you will have to wait a long time before alert eval.

For example:
Say frequency is 5m, and we have 30 rules, and a rule has index 20
offset = ((300000 / 30) * 20) / 1000  = 200

It means that when the interval reached, I have to wait 200 seconds before alert eval.

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: ClickHouse 20.8.4
- OS Grafana is installed on: centos7.6
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
We are in the process of implementing a new alerting engine #28994 where this might be relevant.
