### ISSUE TITLE
Plugins: Refactor plugins package and get rid of globals

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29022]
We have many uses of globals variables left in backend go packages. These were quite common in many early go programs but are obviously not a great idea. We have started to stop using global variables and now use instances instead (like normal sane languages).

We have started to get rid of the globals by introducing the [PluginsManager](https://github.com/grafana/grafana/blob/master/pkg/plugins/plugins.go#L56) in the plugins package. 
But the package still has many globals that we should move into the PluginsManager struct (or some other struct). 

https://github.com/grafana/grafana/blob/master/pkg/plugins/plugins.go#L27

**Comment by aknuds1** [comment]
Agree 100%, and the work is under way :) Already have a PR that I'm splitting up to deal with middleware globals.
