### ISSUE TITLE
randomly apache+grafana takes 15 minutes to respond 

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#2902]
Hi I have an apache server listening on 80/443 ports  in front of a grafana server listening on  localhost:8080 and Graphite as Backend in the same host ( datasource as proxy ) .

Apache acts as a auth proxy and sometimes seems to freeze but finally responds HTTP 200 15  minutes after. 

You can see a in the following gist a filtered access.log ( only has response times greater than 15 minutes) , the last field is response time in microseconds (%D LogFormat )

https://gist.github.com/toni-moreno/3ef281c27651bbef1a01

The Graphite Back-end seems be working OK, its apache access_log has as a greatest response time 1.5 seconds in all hits.  The grafana logs doesn't show nothing important except some HTTP 500 but not related to these frozen hits.

We are working with:
* Grafana version: 2.1.0-pre1, commit: v2.0.2+534-g8daec7b, build date: 2015-07-15 14:57:52 
* apache 2.2.15-39
* RHEL 6.6

There is way to debug/locate the origin of this frozen hits?

Thank you very much

**Comment by toni-moreno** [comment]
Hi @torkelo 

As  previously commented in https://github.com/grafana/grafana/issues/2225 will be grateful if you can add something like response time in a access.log . I have not other way to debug / locate where the bottleneck happens, and this would be 

Thank you very much

**Comment by torkelo** [comment]
@toni-moreno made router_logging = true work :) now you should be able to see what request is taking time.

**Comment by torkelo** [comment]
@toni-moreno what are you using for session store?

**Comment by toni-moreno** [comment]
Hi @torkelo thank you very much for this fix. 

I will update in testing servers this week and I will  do it in production next week. 

I've seen that latest  Nightly Builds from RH/Centos is from "24/8/2015 10:17:46" ??. There is also one from "10/10/2015 21:17:30" .   is the fix included in this build?

 I'm using file as a session store. Could be better change this to memory?

**Comment by toni-moreno** [comment]
Hi @torkelo I've upgraded my testing platform with 2.5 version.

I'm seeing now response time, thank you very much. I will upgrade production in a few days in order to locate the 15 minutes "frozen" hits 

Now we see the following log

```
2015/10/28 17:00:42 [I] Completed /render 200 OK in 1.009688339s
2015/10/28 17:00:42 [I] Completed /render 200 OK in 1.681680079s
2015/10/28 17:00:43 [I] Completed /render 200 OK in 1.875913175s
2015/10/28 17:00:43 [I] Completed /render 200 OK in 1.937721866s
2015/10/28 17:00:43 [I] Completed /render 200 OK in 2.316984552s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 1.299809255s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 1.285863763s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 2.346413804s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 1.951850024s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.686839802s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.014659941s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.080559295s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.238959337s
```
A couple of suggestions:

1)  would be important if some extra data could be reported in order to identify exactly  the slow request , something like:

* __user__ who is doing the request
* __org__ which user belongs to 
* __dashboard__ that is doing the request
* __panel__ which renders the returned data.
* __datasource__ from which we are sending the request.
* __target/query__  detailed on the request.

2) would be interesting if you can report time always in the same unit ( ms by example or microseconds as apache does) in this way users can automate the  log parsing and send to the metrics backend.

Thank you very much again

**Comment by toni-moreno** [comment]
Hi  @torkelo  , would you like to have a new feature request with these two last suggestions?

**Comment by torkelo** [comment]
@toni-moreno yes, a PR with that would be great

**Comment by toni-moreno** [comment]
@torkelo :) I was referring to an issue rather than a PR. ( I would like to code a lot Grafana ) but I'm deploying collectd+other self made agents/Graphite/Grafana for near 6000 linux/windows servers and... there is no enough time in my clock to spend. We @sbengo and I would like to help you as much as we can.  We will open a new Issue now  ok?.

**Comment by torkelo** [comment]
yes, its ok :)
