### ISSUE TITLE
Linear autoscale for different units

### ISSUE THREAD

**Issue by robomotic** [grafana/grafana#29026]
**What would you like to be added**:
I would like to have the ability to plot two different series with different units in linear scale to keep the same shape.
This is an example that Excel handles automatically for example normalizing the ranges of kwh and Celsius to be displayed in the same chart.

![image](https://user-images.githubusercontent.com/315964/98813296-db7c3780-241b-11eb-9a7e-d71ef60d066d.png)

In Grafana the same linear plot looks like this:

![image](https://user-images.githubusercontent.com/315964/98813457-12524d80-241c-11eb-96c0-c40029852a51.png)

**Why is this needed**:
This is a very common feature in other packages such as Tableau/Excel/Matplotlib and is very useful for many industries.
One workaround I use currently is to transform for example the energy in log10 and keep the temperature linear but this of course destroys the shape for the energy.

**Comment by papagian** [comment]
It seems related to #28911

**Comment by peterholmberg** [comment]
We are in the process of implementing a new Graph component where this might be relevant. I've added a reference to this issue in https://github.com/grafana/grafana/issues/27848
