### ISSUE TITLE
[Chore] Settings: Complete refactoring of backend settings global variables to instance 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29021]
We have many uses of globals variables left in backend go packages. These were quite common in many early go programs but are obviously not a great idea. We have started to stop using global variables and now use instances instead (like normal sane languages). 

https://github.com/grafana/grafana/blob/master/pkg/setting/setting.go#L226

Refactoring all settings to use an instance Cfg struct that we pass around/inject into other services was started a long time ago but was never picked up / completed.  
https://github.com/grafana/grafana/pull/11777

Would be good to continue this refactoring as I see PRs sometimes continue to add new global setting variables instead of adding them to the Cfg struct.

**Comment by aknuds1** [comment]
I'm moving many setting global usages to setting.Cfg in a mega PR that I'm splitting up.

**Comment by aknuds1** [comment]
This has partially been dealt with in my [PR](https://github.com/grafana/grafana/pull/29605) to convert middleware to use local state.

**Comment by osluf** [comment]
@idafurjes I see some movement at https://github.com/grafana/grafana/issues/31033, and a closed https://github.com/grafana/grafana/pull/47236. Is this still available to work (as a contributor?).

**Comment by idafurjes** [comment]
@osluf go for it

**Comment by ribeiromiranda** [comment]
@osluf I also want to contribute to this settings refactoring, how is it going?

Analyzing the code, I think the following improvements are important:
* Separate loading of .ini file from struct Cfg
* Remove global variables
* Remove direct calls to Raw *ini.File and pass to struct Cfg

I started refactoring in the branch settings https://github.com/galgotech/grafana/tree/settings

**Comment by CloudInnovator** [comment]
@osluf Any progress? Beginner contributor here...

**Comment by rmhowe425** [comment]
@dinholufe @idafurjes @CloudInnovator Is this issue still being worked or can I grab it?
