### ISSUE TITLE
[Bug] Exponent issue in table display

### ISSUE THREAD

**Issue by Davidffry** [grafana/grafana#29035]
**What happened**:
In table Panel, when the result is a String with 0370994E-03 for exemple, the interpretation of the result is 371

**What you expected to happen**:
the string display in the table panel is 0370994E-03

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/31964077/98839771-3f1b5a80-2446-11eb-80da-c42c643c37bd.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3
- Data source type & version: Thruk - latest
- OS Grafana is installed on: CentOs
- User OS & Browser: Windows - Chrome
- Grafana plugins: Table / thruk
- Others:

**Comment by torkelo** [comment]
Add a field override for the column, then set the unit property to the string unit .This will force Grafana to treat the string as string and not a number

**Comment by Davidffry** [comment]
Thanks

**Comment by daniellee** [comment]
Also noted that when I tried with `0370994E03`, `0370994e3` and `0370994E+03`and they all produced the correct result so the formatting can't handle the `-` in your string.
