### ISSUE TITLE
es datasource query question

### ISSUE THREAD

**Issue by PragueJoker** [grafana/grafana#29047]
![grafana](https://user-images.githubusercontent.com/16395724/98905305-28ccd780-24f6-11eb-97f2-b3133456dd7e.png)

I don’t know why filters don’t work, but it’s okay to configure it in kibanan. Can you give me the answer? I asked this question in the community but no one responded to me. My English is not good.

**Comment by papagian** [comment]
Please, for being able to investigate it, you have to provide the following information:

Environment:

- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

Also, the Dashboard JSON that can be found in the dashboard settings JSON model view would be helpful

**Comment by PragueJoker** [comment]
> 为了能够进行调查，请提供以下信息：
> 
> 环境：
> 
> * Grafana版本：
> * 数据源类型和版本：
> * OS Grafana安装在：
> * 用户操作系统和浏览器：
> * Grafana插件：
> * 其他：
> 
> 此外，可以在仪表板设置JSON模型视图中找到的Dashboard JSON将很有帮助。
> 最后，您能否解释发生了什么以及预期发生了什么？

**Comment by PragueJoker** [comment]
> Please, for being able to investigate it, you have to provide the following information:
> 
> Environment:
> 
> * Grafana version: 7.3.1
> * Data source type & version: elasticsearch & 6.6.1
> * OS Grafana is installed on: mac docker 
> * User OS & Browser:mac & chrome
> * Grafana plugins:
> * Others:
> 
i think this version should have some question,because when i give back grafana version:6.7.0 is ok
