### ISSUE TITLE
CloudWatch Datasource configuration to add query filter

### ISSUE THREAD

**Issue by o20ne** [grafana/grafana#29045]
**What would you like to be added**: 
During configuration of CloudWatch Datasource, add in configuration for "Query" and "Regex" filter so all data extracted from this datasource would filter/limit to these configurations.

Current CloudWatch configuration fields does not have a way to implement ARN Query.
![Screenshot 2020-11-12 at 11 20 08 AM](https://user-images.githubusercontent.com/4899711/98891389-0f696280-24d9-11eb-878a-63e4a3a9fd9c.png)

Related to https://github.com/grafana/grafana/pull/14803, query and regex filter.

**Why is this needed**:
Within organisation support in Grafana, different organisation is only allow to view specific CloudWatch resources data.

This feature would allow Organisation Datasource to be configured with ARN query/filter targeting the resources.

**Comment by sunker** [comment]
Thanks for reporting this @o20ne! 

I'm afraid I don't understand how this would work. What is an ARN Query and how would we use it? Would it filter data returned from the API or would it filter resources? 

Thanks!

**Comment by o20ne** [comment]
Hi @sunker,

I believed I used the wrong term, sorry for the confusion.

The key mechanism is AWS Resource Group "Get Resource" APIs with filter.
https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/API_GetResources.html

It would filter resources, in this use case, it is CloudWatch "log groups" and "metrics".

AWS mechanism of listing log groups and metrics doesn't allow filtering by tags, this prevents tenancy model which uses tags to identify the ownership.

The goal of this feature is to allow "Organisation" level CloudWatch filter so we can control what resources the users can see.

**Comment by sunker** [comment]
Okay, I get it! I think it sounds like a pretty good feature to have. Let's wait for some time and see if there are more users who'd like this feature to be implemented.

**Comment by vickyyyyyyy** [comment]
We're not sure if we are able to achieve this with the current API. However, if this is a feature that the community still wants, please re-open this in discussions and we may revisit it further if it gets more traction. Thanks!
