### ISSUE TITLE
Alerting: storage / domain model 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#2904]
Just brainstorming ideas / concepts. 

```
Dashboard
Panel
  Queries
       1: refId: #A

  Alerting
     AlertRuleId: 1
      Query: {refId: "#A"}
      Aggregate: Avg
      QueryRange: 5m
      CheckInterval: 100s
      Critical: 100
      Warn: 50
      Notify: ['ops', 'ceo']      
---

db

alert_rule
  id
  dashboard_id
  panel_id  
  query   (json encoding of panel.targets[i])
  query_ref_id
  warn_level
  crit_level
  check_interval
  query_range
  title 
  description 
  current_state

alert_rule_state_history

alert_rule_notify
  alert_rule_id  
  notify_group_id
 
SaveDashboard

  alertDefs = getAlertRules(Dashboard)

**Comment by utkarshcmu** [comment]
Different type of alert rules will make Grafana more powerful. Obviously, basic rule should be a threshold check with options like >=,<=,=,etc. It will check that the last datapoint is above/below/equal to the value set in the rule. But an advanced rule could be "standard deviation", i.e. if the last datapoint is deviating by more than 5%(+5% or - 5%) of the moving average of all data points in last 1 hour.

**Comment by torkelo** [comment]
@utkarshcmu that is something you can do in the metric query itself

**Comment by torkelo** [comment]
@bergquist updated the description a bit 

So the general idea is to handle this on dashboard save. On dashboard save look for panels with alerting rules, then extract them and update alert rule tables in the database.

**Comment by bergquist** [comment]
@torkelo only having warn_level and error_level seems to minimal (assuming its a number). I think it would be a good idea to have something like 

```
alert_rule
  id
  dashboard_id
  panel_id  
  query   (json encoding of panel.targets[i])
  query_ref_id
  check_interval
  query_range
  title 
  description 
  current_state
  checks: [
    value
    operand
    ,
    value
    operand
  ]
```
Or maybe there is a reason for only having one prop for warn and one for crit?

**Comment by torkelo** [comment]
@bergquist I agree with having simple thresholds is a big limiting factor but I think for v1 it will be fine. 

I think the step beyond thresholds is to allow some kind of scripting language so you can define more dynamic thresholds and alerts. for example: 

```
Alert Critical When Std(Query(#A)) > 10  && TimeOfDay(not 00:00 -- 04:00) 
```

Something like that, I imagine to be the v3 of v4 of alerting, where you can specify different thresholds based on time of day or time of week expressions (to ignore times when imports, or integrations usually run etc, or to work around seasonality), also be able to base threshold on another query. 

But I think starting with simple warn and critical levels is pretty good as well, we can have a nice ui where you can drag and specify the limits etc. Make it very easy to use.

**Comment by bergquist** [comment]
v0.1
[x] super basic gui for adding alerts
[ ] make sure deleting panels deletes the alert
[ ] make sure deleting a dashboard deletes all alerts
[ ] convert dashboard thresholds to alerting thresholds
[ ] api for listing listing all alerts.

**Comment by torkelo** [comment]
still a lot of mixed naming. AlertRule in some places, but referred to in many other places as Alert, and AlertId, this needs to be normalized to RuleId or AlertRuleId.  AlertState and api associated seems to be the main places that still use the old name, 

Alert => is to me to something created from an alert rule, and alert is something you can acknowledge etc.

**Comment by bergquist** [comment]
closing this

**Comment by torkelo** [comment]
Think we need to rethink the alerting storage model. Think fixed thresholds is to limiting and dynamic thresholds would require quite a substantive change. 

Think a more dynamic alert rule model could look something like this

```json
{  
  "alert": {
    "name": "Majority servers down",
    "frequency": 60,
    "notify": ["group1", "group2"],
    "expressions": [
        {
          "left": [
            {
              "type": "query",
              "refId": "A",
              "timeRange": {"from": "5m", "to": "now-1m"},
            },
            {
              "type": "function",
              "name": "max"              
            }
          ],
          "operator": ">",
          "right": [
            {
              "type": "constant",
              "value": 100
            }            
          ],
          "level": 2,
        }
    ]
  },

  "alert": {    
    "name": "Majority servers down dynamic",
    "frequency": 60,
    "notify": ["group1", "group2"],
    "expressions": [
        {
          "left": [
            {
              "type": "query",
              "refId": "A",
              "timeRange": {"from": "5m", "to": "now-1m"},
            },
            {
              "type": "function",
              "name": "max"              
            }
          ],
          "operator": ">",
          "right": [
            {
              "type": "query",
              "refId": "A",
              "timeRange": {"from": "now-1d-5m", "to": "now-1d"},
            },
            {
              "type": "function",
              "name": "max"              
            }   
          ],
          "level": 2,
        }
    ]
  }
    
}
```

**Comment by bergquist** [comment]
defaultValues = {
   frequency: 10,
   warning: { op: '>', level: 10 },
   critical: { op: '>', level: 20 },
   query: {
     refId: 'A',
     from: '5m',
     to: 'now',
   },
   transform: {
     type: 'aggregation',
     method: 'avg',
   },
 };

**Comment by bergquist** [comment]
```javascript
notifcationSender: {
  id: 1,
  name: "NOC email",
  type: "email",
  parameters: { ... }
}

notificationGroup: {
   id: 3,
   name: "ops",
   users: [1, 2, 3],
   parentGroup: 1,
   senders: [1, 3]
}
```

**Comment by torkelo** [comment]
notification: {
  id: 1,
  name: "NOC email",
  type: "email",
  settings: {
    smtp,
    ignoreWarn: true
  }
}

notification: {
  id: 2,
  name: "Alerting system X",
  type: "webhook",
  settings: {
    ignoreWarn
    url, 
    authentication
  }
}

notification: {
   id: 3,
   type: "group",
   name: "ops",
   settings: {   
     warn: [2],
     crit: [1, 2]
   }
}

**Comment by bergquist** [comment]
Closing this since have locked the schema for now in the alerting branch
