### ISSUE TITLE
Non-recognisable behaviour in font colouring

### ISSUE THREAD

**Issue by mieseprem** [grafana/grafana#29050]
**What happened**:
We upgraded our Grafana instances to 7.3.2 (from 7.2.1). On many of our dashboards we have a lot of single stats with blue backgrounds (just plain information) and green - yellow - red (with threshold good - warning - bad). In 7.2.1 all single stats have the same font color. But now with 7.3.2 the yellow ones switches to black. This behaviour makes the dashboards more difficult to interpret, as it makes "out of the corner of your eye pattern recognition" more difficult (more than just business value changes).

This was mentioned in #28932 too. But now with 7.3.2 it is still flipping to black on yellow background.
Origin of this behaviour seems to be #28305

![grafik](https://user-images.githubusercontent.com/50367822/98911927-b04e2280-24c5-11eb-9fd4-27856ff1217c.png)

**What you expected to happen**:
Font color in "Green", "Yellow" and "Red" should be equal or manually setable. 

**How to reproduce it (as minimally and precisely as possible)**:
Single Stat -> Color Mode: background -> Color Scheme: by threshold -> choose basic colors "Green", "Yellow", "Red"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Win 10, Firefox 82
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you need to make the yellow color darker, Grafana evaluates the brightness of the background to know if the value can be white or black and still be readable

**Comment by mieseprem** [comment]
If I understood this correctly, the thresholds from where the colour changes was adjusted with each patch. Simply choosing a fixed value is not good, because then there is the risk that the font colour will change again after the next patch.
