### ISSUE TITLE
Grafana Table thresholds - option to set foreground and background colors

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#29063]
**What would you like to be added**:  The current table threshold settings allow one to set the background color of a cell or row, or the foreground color. We would like the option of setting both and selecting the color of each independently of each other.

**Why is this needed**:
 Boomtable allows teams to set both independently of each other.  We are trying to migrate teams from boom table to the grafana table and they are requesting this feature.

**Comment by torkelo** [comment]
This is sadly not something that is for consideration right now. No other request like this, and would complicate the new table panel by a lot. The threshold model only have a single color associated with each threshold. So I do not see us adding this, nor a clear reason why you would want this. Not sure I understand the use case/problem that is solved by controlling the foreground and background. Grafana will set the foreground color automatically (if you color the background of the cell) to make sure the text in the cell is readable

**Comment by torkelo** [comment]
Closing this, for now, if you have more details and use cases for why setting foreground and background colors are useful we can re-open. 

We have had no such feature request for the old or new table so seems like an edge case that is not very common
