### ISSUE TITLE
feature-request: toggle gradient/plain color in table cell background 

### ISSUE THREAD

**Issue by pfischer64** [grafana/grafana#29074]
since grafana 7.0 there is by default a gradient in the background of a colored table cell. 

Sometimes this does not look straight :-)

So I suggest a new option for table cells: toggle plain color/gradient

**Comment by pfischer64** [comment]
the css created this code:

**background: linear-gradient(120deg, rgb(21, 147, 18), rgb(25, 115, 14));**

![grafana7 32 gradient](https://user-images.githubusercontent.com/43639627/100339525-43b14880-2fda-11eb-99a4-543aafe4c3d6.png)

**Comment by lealceldeiro** [comment]
Any plans to release this any time soon?
