### ISSUE TITLE
Inconsistent unselection using value groups / tags

### ISSUE THREAD

**Issue by giovanni-ferrari** [grafana/grafana#29070]
(https://user-images.githubusercontent.com/26001122/98970282-09db3f00-2510-11eb-8fe3-92de402e052c.gif)

**What happened**:
Selecting two tags causes the corresponding variable values to be selected. Once one of the two tags is unselected, all the variable values are unselected 

**What you expected to happen**:
Variable values should be selected, in accordance at the current selected tags

**How to reproduce it (as minimally and precisely as possible)**:
Can be reproduced here ( https://play.grafana.org/d/000000024/templating-value-groups?orgId=1 ) following the steps in the attached GIF

**Anything else we need to know?**:

**Environment**:
- Grafana version: master branch
- Data source type & version:
- OS Grafana is installed on: docker container / linux
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins:
- Others:
![bug tags]

**Comment by hugohaggmark** [comment]
The tags feature is an experimental feature that will be deprecated/removed in a future Grafana version so we'll close this now.
