### ISSUE TITLE
Stat panel type locks up browser when constant 0 value is returned in grafana 7.3.2

### ISSUE THREAD

**Issue by kalebris** [grafana/grafana#29073]
**What happened**:
Upgraded to 7.3.2 from 7.3.1 and a few dashboards started to lock up the browsers.

**How to reproduce it (as minimally and precisely as possible)**:
The easiest way is to setup a prometheus datasource (doesn't even need to work)
create a new graph panel
to the query just simply put in 0
change the graph type to Stat

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.2
- Data source type & version: prometheus (but I suspect this is datasource independent as the original issue was with elasticsearch)
- OS Grafana is installed on: debian, reproduce on ubuntu/docker
- User OS & Browser: Windows10, Firefox and chrome behaves the same way
- Grafana plugins: none
- Others:

![0-stat-broken](https://user-images.githubusercontent.com/9818278/98975383-f16a2500-250d-11eb-99d4-0626bd5e9f44.gif)

**Comment by torkelo** [comment]
Thanks for reporting this! fix soon merged!

**Comment by eulers-identity** [comment]
I can confirm my browser crashes when metric value 0 comes in from OpenTSDB data source too.

**Comment by torkelo** [comment]
Fixed in Grafana 7.3.3 released today
