### ISSUE TITLE
Graph panel: bars and points are not aligned

### ISSUE THREAD

**Issue by leppeles** [grafana/grafana#29081]
I recently upgraded to grafana version 7.3.1 from 7.0.0 and it seems like the visualization changed a bit. I use the graph with bars and points shown, and the points were used to sit at the center of the bars, like a rounded top. Now they are on the edge of the bars, far right, making it looking wierd.
Any advice?
Thanks in advance!

![image](https://user-images.githubusercontent.com/36412525/98999735-8d108b00-2538-11eb-9458-ff227914f3c7.png)

**Comment by papagian** [comment]
Can you share the panel JSON?

**Comment by torkelo** [comment]
We changed this back to how it was always in Grafana , with bars starting at the data point , centering had other issues

**Comment by leppeles** [comment]
Thanks, I think I'll just downgrade then.
