### ISSUE TITLE
Explore: Issues writing LogQL queries using international keyboard layout

### ISSUE THREAD

**Issue by cinaglia** [grafana/grafana#29080]
**What happened**:
I've recently started noticing a weird behavior when writing LogQL queries around quotes using the `U.S. International - PC` keyboard layout on mac:

![Kapture 2020-11-12 at 15 02 10](https://user-images.githubusercontent.com/95875/98990204-1ce21500-24f8-11eb-8d24-1be7a12ee04e.gif)

Note that it only manifests within the "log pipeline" portion of the query. It works as expected when working within the "log stream selector" section.

I've not been able to replicate this using a different keyboard layout.

**How to reproduce it (as minimally and precisely as possible)**:
1. Switch to the `U.S. International - PC` keyboard on a Mac
2. Open Explore & type `{name="test"} |= "`.
3. The query editor should now start to misbehave.

**Environment**:
- Grafana version: 7.3.x
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS/Chrome (International keyboard)

**Comment by theophileds** [comment]
Hey there,

I still encounter this issue while using the US International keyboard on Grafana v9.1.6
