### ISSUE TITLE
LDAP Login Overwrites Organization role for user

### ISSUE THREAD

**Issue by mottati** [grafana/grafana#29083]
**What happened**:
After an LDAP user has logged in the first time, and the Grafana administrator has modified their account to have a role of Admin, a subsequent login by that user will cause role to be downgraded, presumably back to the role associated with the group_mappings associated with the LDAP configuration that allowed that user to login in the first place. 

Here is an example of this. The "show" command is a on line script containing this line:
`curl -s --user admin:admin http://localhost:3000/api/org/users/ | jq '.[] | select ( .userId == 2)'`

```
 ldap.user$ ./show ; # After initial login as ldap.user
{
  "orgId": 1,
  "userId": 2,
  "email": "ldap.user@mycompany.com",
  "name": "LDAP User",
  "avatarUrl": "/avatar/1d72ada0cf1950e82b2b6a38f72cc317",
  "login": "ldap.user",
  "role": "Viewer",
  "lastSeenAt": "2020-11-11T19:01:15Z",
  "lastSeenAtAge": "< 1m"
}
 ldap.user$ ./show ; # After the Grafana administrator had changed the role to Admin 
{
  "orgId": 1,
  "userId": 2,
  "email": "ldap.user@mycompany.com",
  "name": "LDAP User",
  "avatarUrl": "/avatar/1d72ada0cf1950e82b2b6a38f72cc317",
  "login": "ldap.user",
  "role": "Admin",
  "lastSeenAt": "2020-11-11T19:01:15Z",
  "lastSeenAtAge": "2m"
}
 ldap.user$ ./show ; # After logging off, and in again as ldap.user
{
  "orgId": 1,
  "userId": 2,
  "email": "ldap.user@mycompany.com",
  "name": "LDAP User",
  "avatarUrl": "/avatar/1d72ada0cf1950e82b2b6a38f72cc317",
  "login": "ldap.user",
  "role": "Viewer",
  "lastSeenAt": "2020-11-11T19:01:15Z",
  "lastSeenAtAge": "2m"
}
```
The group mapping that permits the initial login is this:
```
[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"
```

**What you expected to happen**:
I would expect the group mapping to be honored at first login (e.g. the user record and org affiliation created) however I would also expect that once the user had been created, it would no longer be modified as a side effect of logging in.

**How to reproduce it (as minimally and precisely as possible)**
- Deploy fresh grafana with LDAP configured and (at least) this group mapping
```
[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"
```
- Login as <ldap.user> with LDAP credentials.
- View new user permissions within the Main org (either with curl or web UI)
- Logout from  <ldap.user>
- Login as admin
- Modify the account of <ldap.user> to be an Org admin.
- Login as <ldap.user>
- view account of <ldap.user>

**Anything else we need to know?**:

**Environment**:
- Grafana version:  grafana/grafana:7.3.1
- Data source type & version: NA
- OS Grafana is installed on: Docker image run from MacOS
- User OS & Browser: Chrome
- Grafana plugins: No modifications to the Docker image
- Others:

**Comment by aknuds1** [comment]
Looks related to https://github.com/grafana/grafana/issues/22605.

**Comment by xlson** [comment]
This is intended behavior. As long as there is at least one group mapping the the LDAP config LDAP has control over org roles and any modifications made between logins will reset the next time the user logs in. 

You can sidestep this behavior by removing all group mappings from the LDAP config.

**Comment by mottati** [comment]
> You can sidestep this behavior by removing all group mappings from the LDAP config.

Thank you, that solves our problem.
