### ISSUE TITLE
Chained children variables don't update when passing parent variables through the dashboard URL query string

### ISSUE THREAD

**Issue by binsur** [grafana/grafana#29085]
**What happened**:
Consider two chained template variables, $pool chained to $server. (aka $pool is the parent to $server)

$pool is set up to pull values from a graphite data source of "stats.*"

$server is set up to pull values from a graphite data source of "stats.$pool.*"

Refresh is configured as "On Dashboard Load" for both variables.

When the dashboard is pulled up and the $pool template variable is changed, the $server dropdown list is updated appropriately.  

However, when the dashboard is referenced via a link and the var-pool=something variable set in the query string, the $pool value is correctly set but the $server dropdown options are not updated.  The values in the drop down for $server contain whatever was saved as the default for the dashboard.

**What you expected to happen**:
I expect that when a I link to dashboard and include a parent template variable in the URL query string that all children chained variables are updated according to the parent passed in via the query string.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up a template variable
2. Set up a second template variable that is depending on the first
3. Pull up the dashboard and pass the first variable in via the query string (var-parent-variable-name=whatever).  
4. The second child template variable is not updated to reflect the appropriate parent variable passed.

As of this bug report, it can also be produced on the Grafana Playground:

https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?orgId=1&var-source=site&var-host=All

Notice that the "host" dropdown contains ALL hosts and not just the hosts related to "source:site"

**Anything else we need to know?**:
n/a

**Environment**:
- Grafana version: Grafana v7.3.1 (6668161a88)
- Data source type & version:
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows / Chrome
- Grafana plugins: Relatively large number
- Others:

**Comment by papagian** [comment]
Thanks for reporting this.
Just to clarify: the issue you are reporting is that when one navigates for instance to:
`https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?editPanel=1&orgId=1&var-source=backend`
the `host` variable contains the options `server 20` and `server"21`  while it shouldn't.

**Comment by binsur** [comment]
> Thanks for reporting this.
> Just to clarify: the issue you are reporting is that when one navigates for instance to:
> `https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?editPanel=1&orgId=1&var-source=backend`
> the `host` variable contains the options `server 20` and `server"21` while it shouldn't.

Yep, that's exactly what I'm reporting :)

**Comment by xujiaxj** [comment]
We have the same issue here with Grafana v7.3.1 (6668161a88). Any update?

**Comment by timpalpant** [comment]
#28897, #29048, and #28965 seem like they may be other variations on this issue. @papagian could you consider them for deduping to help clarify impact?

**Comment by papagian** [comment]
Unfortunately I'm not the best person to tell: I have forwarded it to the frontend.

> #28897, #29048, and #28965 seem like they may be other variations on this issue. @papagian could you consider them for deduping to help clarify impact?

Unfortunately I'm not the best person to tell: I have forwarded to the frontend team.

**Comment by hugohaggmark** [comment]
@binsur yes you're correct this was a bug fixed in 7.3.2 by #28798 so try upgrading your Grafana instance. Regarding the dashboard in Grafana Play, that is using Elastic search and we seem to have issues with our Elastic instance now and then. Try this instead:
1. https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&var-app=country&var-server=IE&var-interval=1h correct variables are set
2. Changing the var-app to `backend` instead you can see that it will reload correct options
https://play.grafana.org/d/000000056/graphite-templated-nested?orgId=1&var-app=backend&var-server=All&var-interval=1h

I'm going to close this now, but we can reopen it again if more evidence in this case comes up.

Allt the best
