### ISSUE TITLE
Allow Azure AD Auth types for MSSQL Data Source

### ISSUE THREAD

**Issue by extide** [grafana/grafana#29089]
**What would you like to be added**:
Ability to configure a SQL Server Datasource using Azure AD Login credentials such that I can login to the [TDS endpoint for the Common Data Source](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query)

Perhaps this can already be done today with some crafty provisioning config files?

**Why is this needed**:
I am specifically looking to connect Grafana to Dynamics 365. Microsoft has recently released a [TDS endpoint for the Common Data Source](https://docs.microsoft.com/en-us/powerapps/developer/common-data-service/cds-sql-query) -- which is essentially a SQL endpoint allowing you to access your Dynamics data -- but it ONLY supports Azure AD authentication. This would greatly simplify the existing working setups that I have which all require an intermediate datastore of some sort that Grafana connects to -- this feature would eliminate that extra step, and it should be very low effort as the support is there on the library and most of the implementation would be wiring up some UI. You can even leave this option behind a 'AllowPreviewLogin' setting in the config file so that it takes a little bit of effort to enable.

I checked out the MSSQL library you guys are using, and it seems that they [do have some support for this](https://github.com/denisenkom/go-mssqldb#azure-active-directory-authentication---preview).

**Comment by initions-erb** [comment]
Any update on this? - Especially when using Azure Managed Grafana this feature is badly missed!

**Comment by oscarkilhed** [comment]
We've started working on this but it will likely take a while. We've just recently upgraded the azure SDK to the latest version, that in turn will allow us to upgrade our outdated MSSQL driver. When the new driver is in place we will be able to implement this.

**Comment by oscarkilhed** [comment]
Fixed in: #73597
