### ISSUE TITLE
Dashboard Links: Variables not updated on variable/timerange change

### ISSUE THREAD

**Issue by Thaillie** [grafana/grafana#29099]
**What happened**:
After changing the variables and time range on my dashboard A I expected the dashboard link to reflect the new variables.
But when I click on the link I am directed to the linked dashboard B with the variables/time range dashboard A had at the time of loading.

**What you expected to happen**:
I expected the variable in the dashboard link to match the variables/time range currently selected, instead of the states they had when the dashboard first loaded.

**How to reproduce it (as minimally and precisely as possible)**:
I have setup 2 dashboards with almost the same variables.
Dashboard A:
host: "list of hostnames loaded from influxdb"
summarize: "type interval, so timeranges"
downtimes: "annotation toggle"

Dashboard B:
host: "list of hostnames loaded from influxdb"
summarize: "type interval, so timeranges"

They both have the "engineering" tag and share the same dashboard link settings as the screenshot below.
![image](https://user-images.githubusercontent.com/15648719/99076633-baeae380-25bb-11eb-9d3e-5716133ae568.png)

**Anything else we need to know?**:
Not really, everything is listed above.

**Environment**:
- Grafana version:
Grafana v7.1.5 (9893b8c53d)
- Data source type & version:
InfluxDB ﻿﻿1.8.3
- OS Grafana is installed on:
Debian 9
- User OS & Browser:
Mac OS Catalina & Firefox 82.0.2
- Grafana plugins:
None, only the default "Core" ones
- Others:

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/issues/27294
