### ISSUE TITLE
Browser stops responding when Stat panel receives 0 value as Prometheus query result

### ISSUE THREAD

**Issue by basroovers** [grafana/grafana#29090]
**What happened**:
As soon as I use a Prometheus query in Stat panel with a 0 value, the browser stops responding and eventually crashes.

![image](https://user-images.githubusercontent.com/2011325/99070624-e0bebb00-25b0-11eb-979b-06007d56d5f7.png)

**What you expected to happen**:
I expected the Stat panel to render a 0 value

**How to reproduce it (as minimally and precisely as possible)**:
Create a new dashboard, add a Stat panel and run a Prometheus query which results in a 0 value.
In my case the query was: "sum(kube_pod_status_phase == 0)"

**Anything else we need to know?**:
It works fine with the Graph panel.

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Prometheus 2.18.0
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Windows 10 (2204) & Edge 86
- Grafana plugins: None
- Others: None

**Comment by transacid** [comment]
![stats](https://user-images.githubusercontent.com/113231/99077133-917e8780-25bc-11eb-8ea7-2578f04b9622.png)
here's a screenshot from the firefox js debugger with a breakpoint where the loop occurs.
