### ISSUE TITLE
Removal of HTTP Headers fail

### ISSUE THREAD

**Issue by TomL-dev** [grafana/grafana#29096]
**What happened**:

After removing a custom HTTP header in a Prometheus datasource, clicking save&test, the header was removed. save&test succeeded
When then selecting the datasource again, the header was present again

**What you expected to happen**:

after removing the header, it should be removed permanently, not come back after refresh/reload

**How to reproduce it (as minimally and precisely as possible)**:

- create prometheus datasource (haven't tested with other datasources)
- add custom http header with value
- save & test -> success
- refresh/reload datasources
- open recently created datasource
- remove custom header with bin icon
- save & test -> success
- refresh/reload page
- header is still there

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.0
- Data source type & version: Prometheus
- OS Grafana is installed on: based on official docker image
- User OS & Browser: mac + chrome
- Grafana plugins: 
- Others: using Postgres as a database: `postgres:11.2-alpine`

**Comment by papagian** [comment]
the PUT request payload when testing the datasource (after removing the header) still contains the header:
```
{"id":154,"orgId":1,"name":"Prometheus-29096","type":"prometheus","typeLogoUrl":"","access":"proxy","url":"http://localhost:9090","password":"","user":"","database":"","basicAuth":false,"basicAuthUser":"","basicAuthPassword":"","withCredentials":false,"isDefault":false,"jsonData":{"httpHeaderName1":"X-Foo"},"secureJsonFields":{"httpHeaderValue1":true},"version":12,"readOnly":false}
```

**Comment by TomL-dev** [comment]
i tried to fix it myself, but got completely lost in the rabbithole (api and the webcomponents stuff). If you could provide some info i would like to fix it, if you guys aren't working on it already

**Comment by gabor** [comment]
this is happening with the influxdb datasource too.
