### ISSUE TITLE
Elasticsearch phantom zero

### ISSUE THREAD

**Issue by jordanpurinton** [grafana/grafana#29108]
**What happened**: Running into issues in Grafana 7.2.3 where there is a phantom zero appearing for values in my Elasticsearch documents when the value of that field is `0`.

**What you expected to happen**: Only one `0` to show up.

**How to reproduce it (as minimally and precisely as possible)**: Try displaying a field via `raw data` mode in Elasticsearch in Grafana and you will (hopefully) see an extra `0`.

**Anything else we need to know?**: This also happens with the value mapping as well. The value appears to be outside of the underlying `<div>` as well.

**Environment**:
- Grafana version: 7.2.3
- Data source type & version: Elasticsearch 7.0
- OS Grafana is installed on: Linux
- User OS & Browser: Mac/Chrome

<img width="300" alt="Screen Shot 2020-11-13 at 11 11 44 AM" src="https://user-images.githubusercontent.com/12102971/99094150-6e92aa00-25a1-11eb-81ea-a27319f1515a.png">
<img width="127" alt="Screen Shot 2020-11-13 at 10 01 56 AM" src="https://user-images.githubusercontent.com/12102971/99094152-6fc3d700-25a1-11eb-9e60-c4663f56e738.png">

**Comment by dprokop** [comment]
@jordanpurinton thanks for reporting this bug. I can reproduce it on master and we will fix the underlying issue which is this condition: https://github.com/grafana/grafana/blob/566cd2c6af8dc95b00b79d30e124b9517739f446/packages/grafana-ui/src/components/Table/DefaultCell.tsx#L52
