### ISSUE TITLE
Panel options overlayed by titlebar when no title is set

### ISSUE THREAD

**Issue by CerealZ** [grafana/grafana#29103]
**What happened**:
The dropdown:
![grafik](https://user-images.githubusercontent.com/16158507/99084092-cabbf500-25c6-11eb-8c71-73fde4b0e5eb.png)
of a panel is being overlapped by the title bar of a panel beneath it.
How it looks like (cursor is on the "Remove" option):
![grafik](https://user-images.githubusercontent.com/16158507/99083367-bdead180-25c5-11eb-84b4-d37f46b11acb.png)

The titlebar is getting the focus and everything under it isn't clickable  anymore. Instead you will start dragging the lower panel.

**What you expected to happen**:
The same behaviour as when at least one of the panels has a panel title: the dropdown with the options should be always on top.

**How to reproduce it (as minimally and precisely as possible)**:
- Create 2 (or more) panels
- Leave both panel titles empty
- Resize them small enough to overlap their dropdowns
- Hover over the titlebar area of the lower panel while the dropdown of the upper panel is open (see screenshot above)

**Environment**:
- Grafana version: 7.3.1
- OS Grafana is installed on: Windows 10 x64
- User OS & Browser: Windows 10 x64, Chrome, Firefox & Edge
- Grafana plugins: Any Panel plugin

**Comment by papagian** [comment]
What do you mean exactly by `everything under it isn't clickable anymore`? I can reproduce the visualisation issue but the drop downs are working for me.

**Comment by CerealZ** [comment]
When the title bar appears visually, it intercepts all mouse events in the area and thus blocks input. Now if you somehow have a configuration where the "Remove" button is completely hidden, it cannot be pressed anymore.

**Comment by torkelo** [comment]
We have another issue for this one , on mobile now so can't find it , it's on the frontend platform squad project bugs list
