### ISSUE TITLE
CloudWatch: namespace in search expression should be quoted if match exact is enabled

### ISSUE THREAD

**Issue by chrs-myrs** [grafana/grafana#29109]
**What happened**:
When I try to create a chart with one dimension set, and another with a wildcard, on a custom namespace, I get a 400 error from the cloudwatch api.

Data is clearly in cloudwatch
![image](https://user-images.githubusercontent.com/2414664/99079380-c76d3d00-25b7-11eb-9e5c-29d858a835ef.png)

This illustrates the problem, you can see the filtered list of dimension values, but selecting `*` does not show the chart as you would expect.  However taking off exact match does work, but this is not suitable for our use case.
![2020-11-13_14-12-59](https://user-images.githubusercontent.com/2414664/99098086-67cf5b80-25d0-11eb-8c43-a1f594088f22.gif)

**What you expected to happen**:
You would expect a series to be shown for each of the unique values of the second dimension.

**How to reproduce it (as minimally and precisely as possible)**:
Can't reproduce, but the critical configurations are: -
* Custom namespace on AWS
* Containing a metric with 2 dimensions that may not have data in the last 24 hours
* This metric has multiple combinations of dimensions for the same metric name/namespace, to enable drilling into the data
* Exact match enabled

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Cloudwatch
- OS Grafana is installed on: CentOs
- User OS & Browser: Ubuntu FireFox
- Grafana plugins: All standard + PagerDuty
- Others:

**Comment by papagian** [comment]
I have difficulty reproducing it. Could you please copy and share the request/response from the query editor (the provided gif is helpful but it's hard to spot each detail) and also the server logs (if you have access to them).

**Comment by chrs-myrs** [comment]
Here is the request/response
```{
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1602794962088",
      "to": "1603123712295",
      "queries": [
        {
          "intervalMs": 300000,
          "maxDataPoints": 1275,
          "datasourceId": 12,
          "type": "timeSeriesQuery",
          "namespace": "Test-API Cache by Minute",
          "metricName": "ResponseTime",
          "expression": "",
          "dimensions": {
            "EndpointCategoryLevel1": [
              "Applications",
              "Boxsets"
            ],
            "EndpointCategoryLevel2": [
              "*"
            ]
          },
          "region": "eu-west-1",
          "id": "",
          "alias": "{{EndpointCategoryLevel1}} - {{EndpointCategoryLevel2}}",
          "statistics": [
            "Average"
          ],
          "period": "86400",
          "matchExact": true,
          "refId": "A",
          "datasource": "Prod"
        }
      ]
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "ValidationError: Invalid SEARCH parameter: {Test-API Cache by Minute,\"EndpointCategoryLevel1\",\"EndpointCategoryLevel2\"} MetricName=\"ResponseTime\" \"EndpointCategoryLevel1\"=(\"Applications\" OR \"Boxsets\")\n\tstatus code: 400, request id: 6b721a44-614e-458a-8b81-c7ea1f123cc2",
        "refId": "A",
        "series": null,
        "tables": null,
        "dataframes": null
      }
    },
    "message": "ValidationError: Invalid SEARCH parameter: {Test-API Cache by Minute,\"EndpointCategoryLevel1\",\"EndpointCategoryLevel2\"} MetricName=\"ResponseTime\" \"EndpointCategoryLevel1\"=(\"Applications\" OR \"Boxsets\")\n\tstatus code: 400, request id: 6b721a44-614e-458a-8b81-c7ea1f123cc2"
  }
}```

**Comment by papagian** [comment]
Thanks for sharing the query. The problem is not the wildcard value but the namespace that contains spaces.
It should be quoted in the line 91:
https://github.com/grafana/grafana/blob/c863fd3da968142da3c0d54d0a09b45a6473acdf/pkg/tsdb/cloudwatch/metric_data_query_builder.go#L90-L98

Note that if `MatchExact` is false then it's correctly quoted:
https://github.com/grafana/grafana/blob/c863fd3da968142da3c0d54d0a09b45a6473acdf/pkg/tsdb/cloudwatch/metric_data_query_builder.go#L102
