### ISSUE TITLE
v7.3.1. won't show panel view in Safari brower

### ISSUE THREAD

**Issue by xieweikang666** [grafana/grafana#29116]
**What happened**:

v7.3.1  can not see grafana data **view** in Safari browser

**What you expected to happen**:

After jumping to other page,the select data can be what i take,not show the default value

**How to reproduce it (as minimally and precisely as possible)**:

- Useing Safari broswer
- Check anyone of panel
- just open the panel view
- the view won't render only show blank

**Anything else we need to know?**:

**Environment**:

- Grafana version: 7.3.1

- Data source type & version: Prometheus

- OS Grafana is installed on: based on official docker image

- User OS & Browser: mac + safari

**Comment by torkelo** [comment]
Fixed in 7.3.2

**Comment by xieweikang666** [comment]
> Fixed in 7.3.2

wow thanks!
