### ISSUE TITLE
Feature request: TTL for dashboards

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2911]
We have about 200+ dashboards in our Grafana setup and I am very sure that not more than 50 dashboards are used actively. People create temporary dashboards every once in a while and then leave them to hang around with no one using them anymore. Setting a TTL of 10/15/30/60 days should not be a bad option. This will clean up unused dashboards and will keep Grafana clean.

I am not sure whether there should be a default TTL or not. Or by default the dashboard should never expire.

**Comment by Dieterbe** [comment]
Instead of building this into grafana, a separate program that uses the api to clean up old dashboards could work too.

**Comment by zp-markusp** [comment]
Hi @dieterbe I think the request goes more into the direction to specify a ttl for a specific dashboard. Also in our use case we create many temp dashboards in grafana 1.9 for example to analyse incidents and attach those dashboards to the ticket. This kind of dashboards can/should be deleted after a while but permanent dashboards should exist forever. 
This option was existing in 1.9 and I would be surprised that this feature didn't managed it to come to 2.x

Markus

**Comment by kamaradclimber** [comment]
Interested in this as well. We will probably use a tag for temporary dashboards but it won't solve the issue in general.

**Comment by iksaif** [comment]
Same here.

**Comment by bergquist** [comment]
I think the rules for a dashboards lifecycle can differ a lot from different organisations and it will be hard to create general rules. Something that might make it easier for people to delete old/unused dashboards would be know when was the last time a dashboard was viewed. Which would be very easy to add to the dashboard table.

**Comment by utkarshcmu** [comment]
How about adding "last_viewed/last_active" column in "dashboard" table? This way an admin can know which dashboards are being used recently. 

Use Case: We have been using Grafana for over an year now and there are over 200 dashboards and I am very sure that not more than 50 dashboards are being used actively. So, as an admin, I would like to keep my Grafana dashboard list clean. 

If we can add "last_viewed/last_active" column in the "dashboard" table, then as an admin I can know which dashboards were not used in last 6 months or so and can archive them.

**Comment by bergquist** [comment]
@utkarshcmu "last_viewed" sounds like a good idea.
