### ISSUE TITLE
InfluxDB: Variable with Flux Query doesn't show all the values (limited to 151)

### ISSUE THREAD

**Issue by salvapinyol** [grafana/grafana#29110]
**What happened**:
I have created a dashboard variable with this Flux query:

from(bucket: "snmp/autogen")
  |> range(start: -1y)
  |> filter(fn: (r) => r._measurement == "DEVICE" and r._field == "uptime")
  |> keyValues(keyColumns: ["agent_host"])
  |> group()

And the variable gets populated with 151 values.

**What you expected to happen**:
The query executed in the grafana's explore returns the correct number of values (291), so in the variable I expect to have all the 291 values.

**How to reproduce it (as minimally and precisely as possible)**:
Create a variable with a Flux query that returns more than 151 values.

**Anything else we need to know?**:
No
**Environment**:
- Grafana version: 7.3.1
- Data source type & version: InfluxDB 2.0.1
- OS Grafana is installed on: Red Hat EL 7.0
- User OS & Browser: Windows & Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@ryantxu any ideas what could cause this? 

I think it's due to maxDataPoints not being set for variable queries and getting some default value:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts#L296

**Comment by xxxmailk** [comment]
I have the same issue 

it's my configurations for template variables.

![image](https://user-images.githubusercontent.com/20572882/103057742-4902b280-45db-11eb-830d-90e5d728d151.png)

and this is the data in grafana explore.
![image](https://user-images.githubusercontent.com/20572882/103057857-a5fe6880-45db-11eb-9efb-63a0d05f0976.png)

**Comment by gabor** [comment]
@salvapinyol i could not reproduce this with grafana 8.0.2, could you try it with the newest grafana version?

here is what i did:
1. i added a variable to a dashboard backed by an influxdb flux query. the query returns 200 values.
2. i opened the dashboard, and the variable-selector, when opened, showed me all the 200 items.

**Comment by salvapinyol** [comment]
Tested with 8.0.2 and it works.

@gabor thanks!
