### ISSUE TITLE
The Stat panel shows the title incorrectly if there is a description

### ISSUE THREAD

**Issue by krzysion** [grafana/grafana#29112]
The Stat panel shows the title incorrectly if there is a description and the panel size is small.

Grafana 7.1.5
![7 1 5](https://user-images.githubusercontent.com/36912975/99113590-d2dc5a80-25ef-11eb-87cc-50d92204c6e4.png)

Grafana 7.2.x, 7.3.x
![7 2 x, 7 3 x](https://user-images.githubusercontent.com/36912975/99113647-e687c100-25ef-11eb-83a5-5833d16d8e9a.png)

**Environment**:
- 7.2.x ,7.3.x:

**Comment by torkelo** [comment]
Thanks for reporting this.

Need to change the hover icon caret down (angle down) to be absolutely positioned so that it does not affect title centering:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx#L201

**Comment by krvajal** [comment]
I will try to fix it today
