### ISSUE TITLE
v7.3.1 link Tag take with wrong params

### ISSUE THREAD

**Issue by xieweikang666** [grafana/grafana#29115]
**What happened**:

Jump to the detail data page by the Link Tag won't jump with the right params ,only show default values,not the right exact values

**What you expected to happen**:

After jumping to other page,the select data can be what i take,not show the default value

**How to reproduce it (as minimally and precisely as possible)**:

- create prometheus datasource (haven't tested with other datasources)
- add table data link Tag (link to other grafana page(with params)),and **the other grafana page should set Variable items**
- click the link Tag and jump 
- select the Variable item and check if the data is right 

**Anything else we need to know?**:

**Environment**:

- Grafana version: 7.3.1
- Data source type & version: Prometheus
- OS Grafana is installed on: based on official docker image
- User OS & Browser: mac + chrome
- Grafana plugins:
- Others: using Postgres as a database: `postgres:11.2-alpine`

**Comment by torkelo** [comment]
Try 7.3.2 https://github.com/grafana/grafana/pull/28798
