### ISSUE TITLE
Bug: Elasticsearch Datasource Test Connection did not use UTC

### ISSUE THREAD

**Issue by Kuermel** [grafana/grafana#2913]
Version: grafana_2.5.0-pre1_amd64.deb 8.10.2015 17:44:15

When testing a Elasticsearch data source the current local time (UTC + 2) is used. The Elasticsearch indexes typically use UTC time.

**Comment by torkelo** [comment]
are you refering to the index time patterns?

**Comment by Kuermel** [comment]
![elasticsearch datasource test error](https://cloud.githubusercontent.com/assets/6574969/10573764/222d45ca-7652-11e5-9693-fa40cd1590f2.jpg)

local Time: 11:10 UTC+2

latest Elasticsearch Index : tstat-2015.10.19.09

The Test use the local Browser-Time but Elasticsearch use UTC-Time for there Indexes.
