### ISSUE TITLE
Gauge: Tweak gauge value font size for small (short) values 

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#29130]
**What happened**:
Same issue (#28759) was reported by me a few weeks ago and there was a fix released in 7.3.2 version, but it is not working as expected.
First problem is that short values like "0" in gauge panels are too big.
The second problem that I found is that gauge thresholds are not working when there is no data in selected timerange.

This is how it looks on 7.3.2 version (no data in "Indeks UV" panel):
![7 3 2](https://user-images.githubusercontent.com/19311511/99193284-51640400-2778-11eb-8bfe-78c812fa5751.jpg)

**What you expected to happen**:
This is how the same situation looked on 7.2.2 version:
![7 2 2](https://user-images.githubusercontent.com/19311511/99193286-51fc9a80-2778-11eb-9ecf-9beab33d0396.jpg)

**How to reproduce it (as minimally and precisely as possible)**:
Create gauge panel with short value like "0" and select timerange with no data in specific field.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.2
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10 Opera Gx
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
If you want this fixed you might have to do it yourself as the current state is pretty good: 
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Gauge/Gauge.tsx#L111

**Comment by szerwi** [comment]
@torkelo I think I will have a try. I am setting up the dev environment :) What is the best approach for this issue? Should I only make the maxSize parameter smaller or make the maxSize dependent on gauge or panel size?

**Comment by szerwi** [comment]
I have submited PR: #29197
