### ISSUE TITLE
Panel Override: use capture groupe results from regex matcher in Display Name field.

### ISSUE THREAD

**Issue by tarag** [grafana/grafana#29133]
**What would you like to be added**:

When using a regex matcher in Panel Overrides, I would like to use the result of capture groups inside the regex to provide the value for replacement of the field.

E.g:

<img width="397" alt="Screenshot 2020-11-16 at 08 34 49" src="https://user-images.githubusercontent.com/11686092/99224519-c53cf580-27e6-11eb-8c4e-ee767e690300.png">

**Why is this needed**:

When graphing numerous series that follow the same naming pattern, this allows displaying human friendly name with a single override instead of having to define one per series.

It seems that there are some open issues to be able to do that using aliasing for various datasource, but this could profited a unified way to do it: #5212

**Comment by torkelo** [comment]
This is probably better done in transform

**Comment by tarag** [comment]
I can't use transform for the queries where this feature would be useful because I get this message: _"Organize fields only works with a single frame. Consider applying a join transformation first."_

If I perform a join, then I get one line for each series so I am back to specify the name for each one by one.

This is what the query looks like (InfluxDB): `SELECT mean("value") FROM /^F(1|2|3|4|5)_Appt_($Zone)_Zone_(Principale|Secondaire)_TH_TEMP/ WHERE $timeFilter GROUP BY time($__interval) fill(previous)`

**Comment by torkelo** [comment]
I mean a new regex rename transform
