### ISSUE TITLE
PanelMenu and click event with fractional coordinates

### ISSUE THREAD

**Issue by liviutinta** [grafana/grafana#29138]
**What happened**:
As per [crbug.com/989958](crbug.com/989958), "click" event will become a PointerEvent in Chrome (instead of a MouseEvent) as per [Pointer Event specification](https://github.com/w3c/pointerevents/pull/317), [HTML specification](https://github.com/whatwg/html/pull/5324) and [UI events specification](https://github.com/w3c/uievents/pull/259). When the ClickPointerEvent flag is enabled (now it is disabled by default, you can enable it with Chrome command line flag --enable-blink-features=ClickPointerEvent) the "click" event's coordinates will become fractional (as per Pointer Event specification) instead of integer.

There was a report of PanelMenu stop opening when clicked (see [Comment 18 on crbug.com/989958](https://bugs.chromium.org/p/chromium/issues/detail?id=989958#c18)). 

The root cause is with [this technique](https://github.com/grafana/grafana/commit/1afc590c703731cd2026fb8286388e1db6afc09f) of comparing "click" and "mousedown" events coordinates.

One way of fixing the issue is to round "click" event's clientX, clientY coordinates [when reading "click" event's clientX and clientY coordinates](https://github.com/grafana/grafana/blob/8c7e7e6d221338756380340a68b3f21187995ece/public/app/features/dashboard/dashgrid/PanelHeader/PanelHeader.tsx#L55).

**What you expected to happen**:
PanelMenu opens when clicked.

**How to reproduce it (as minimally and precisely as possible)**:
Open https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 when running Chrome with --enable-blink-features=ClickPointerEvent.
Click on Feature Showcase PanelMenu (as per [Comment 18 on crbug.com/989958](https://bugs.chromium.org/p/chromium/issues/detail?id=989958#c18)). 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.2 (b8ad4eaab3)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@liviutinta thank you so much for this detailed description. Maybe you are interested in proposing a PR with a fix for this issue? If not we will work on it.
