### ISSUE TITLE
Alert list panel: Option to invert sort order in recent changes mode

### ISSUE THREAD

**Issue by skrabadiloseidon** [grafana/grafana#29156]
**What would you like to be added**:
Add an option to invert the alert list panel sort order when set to "Recent state changes" mode.

**Why is this needed**:
The current order is confusing, new entries are added at the bottom, nobody looks at the bottom for new entries.
New and important alerts are scrolling out of the box and you will never notice them.

![alarm_panel](https://user-images.githubusercontent.com/941984/99390227-91da9380-28d8-11eb-8a9d-acb8f3b99642.png)

**Comment by dboslee** [comment]
@skrabadiloseidon @dprokop I will take this. 

Heres the current options. 
https://github.com/grafana/grafana/blob/e313c0cea0ea0852161006f3338f871c0cafed5d/public/app/plugins/panel/alertlist/module.ts#L19-L23

I plan on adding a "Time (desc)" and "Time (asc)" and sorting based on the alert.newStateDate. If there is any input on changing the default value, currently set to 1, or the order of these options let me know.

**Comment by skrabadiloseidon** [comment]
@dboslee Adding a "Time (desc)" and "Time (asc)" and sorting is a good solution.

**Comment by dprokop** [comment]
> @skrabadiloseidon @dprokop I will take this.

@dboslee great, thanks! Let me know when you have a PR ready for a review
