### ISSUE TITLE
Hidden dependent variables don't update

### ISSUE THREAD

**Issue by tobiasdirksen** [grafana/grafana#29152]
**What happened:**
If you have a dependent hidden variable it doesn't update correctly, if you excluded the variable from the url and change the other variable value in the url and refresh. The problem has begun since our update from 7.2.x to 7.3.1.

**What you expected to happen:**
I expect that the hidden dependent variable updates accordingly when the dashboard is refreashed.

**How to reproduce it (as minimally and precisely as possible):**
Create two variables as below. The first one should just be a simple variable with a few options. The second variable should be hidden and dependent on the first one. I have tried with both a postgres and a sql server variable.
![billede](https://user-images.githubusercontent.com/7211545/99376632-79ad4900-28c5-11eb-9e4e-2a3b8763991a.png)

If I change the variable value in the dropdown everythings works as expected. Both the url and the variable value gets updated:
![working](https://user-images.githubusercontent.com/7211545/99377691-cba29e80-28c6-11eb-807c-0961f1918e9d.gif)

However, often I need to change the variable value by using a link, e.g., in a table. Previously I have just made a link with the new variable value, and excluded the dependent variable from the link like this: http://ip-address/d/dashboard_id/dashboard_name?orgId=1&var-test=b
and the dependent variable has updated accordingly. This doesn't work anymore c.f. below
![error](https://user-images.githubusercontent.com/7211545/99378296-8e8adc00-28c7-11eb-891e-9b340ee1c276.gif)

**Environment:**
- Grafana version: 7.3.1
- OS Grafana is installed on: Ubuntu 18.04.5 LTS
- User OS & Browser: Windows 10 Enterprise 18.03. Edge (86.0.622.61)/Firefox (82.0.2)/Chrome (86.0.4240.111)
- Grafana plugins: No plugin is used

**Comment by torkelo** [comment]
Update to 7.3.2 for fix

**Comment by tobiasdirksen** [comment]
Have updated to 7.3.3, but I'm still having the exact same problem.
