### ISSUE TITLE
fail to initialize orm engine: Sqlstore::Migration failed: connection refused

### ISSUE THREAD

**Issue by mkubarycz** [grafana/grafana#2915]
I am attempting to run using the postgres backend, but I end up with some odd Sqlstore::Migration error.  Details below.  It seems like my postgres container is linked correctly, but the Migrator code still tries to connect to localhost.  Thoughts?
 
Startup script
```
docker run -it --rm --name postgres-1 postgres:9
docker run -it --rm --name grafana-1 -p 80:3000 \
  -e GF_SERVER_ROOT_URL=http://xxx.com  \
  -e GF_SECURITY_ADMIN_PASSWORD=xxx  \
  -e GF_DATABASE_TYPE=postgres \
  -e GF_DATABASE_HOST=postgres:5432 \
  --link postgres-1:postgres \
  grafana/grafana:2.1.3
```

Log
```
2015/10/09 15:15:26 [I] Starting Grafana
2015/10/09 15:15:26 [I] Version: 2.1.3, Commit: v2.1.3, Build date: 2015-08-24 08:02:44 +0000 UTC
2015/10/09 15:15:26 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
	Environment variables used:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/10/09 15:15:26 [I] Database: postgres, ConnectionString: user=root password= host=postgres port=5432 dbname=grafana sslmode=disable
2015/10/09 15:15:26 [I] Migrator: Starting DB migration
2015/10/09 15:15:26 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: dial tcp 127.0.0.1:5432: connection refused
```

**Comment by mkubarycz** [comment]
Quick update.  After some search time, it seems that that password being unset was the issue.  Seems like that is not valid in a connection string.  Maybe look to see if the password is whitespace.  If so, just excluding it from the connection string should solve the problem

**Comment by torkelo** [comment]
you dont have a user / password for you postgres server?

**Comment by michalbachowski** [comment]
@torkelo If you use local socket or cert auth yes - you might have not password. Moreover you might even have no username (PostgreSQL will use "common name" from certificate).

@mkubarycz Seems like a similar issue to https://github.com/go-xorm/xorm/issues/285 maybe the suggested workaround will help:
>So I think if you use single quote as empty password or remove empty value k/v pair, it will ok.

So just using:
```password = ''```

This should do the trick.

**Comment by claenjoy** [comment]
mmm,  grafana not start properly at the boot.

mine does the same at every reboot of the server(debian jessie 8.2)
after 1/2 min of the boot I restart the grafana-server service, the service start to run normally.

I have a password on postgres and it does the same issue with or without single quote,

Probably it's waiting for another service to finish .

http://pastebin.com/PsjZhxU5

**Comment by bergquist** [comment]
@claenjoy In 2.6 grafana does not wait for postgres before starting. So it fails and have to be restarted. In next version grafana will restart on failure so it wont be noticed. But if you want to be more explicit about it you can set grafana to wait for postgres to start. 

https://github.com/grafana/grafana/pull/3105/files

**Comment by claenjoy** [comment]
@bergquist  thanks for this, it works !

**Comment by youerning** [comment]
grafana have a bug is if the sepcial charactor like # in password,the grafana server cannot start properly

**Comment by Punkoivan** [comment]
@youerning it's not a bug (now, in 2017 for sure) - 
http://docs.grafana.org/installation/configuration/#password
