### ISSUE TITLE
Line graph datapoints connected in wrong order

### ISSUE THREAD

**Issue by Willshield** [grafana/grafana#29166]
**What happened**:

I created a line graph chart, and the data ponints are often not connected in the timeseries order. The connection order changes when I change the "Null value" option. Here are some strange figures I got:

![Grafana-bug4 5](https://user-images.githubusercontent.com/13013769/99417589-5fda2900-28fa-11eb-9997-92daa1a82c3b.png)
![Grafana-bug4 6](https://user-images.githubusercontent.com/13013769/99417593-610b5600-28fa-11eb-8e7a-cd29779701dd.png)
![Grafana-bug4 7](https://user-images.githubusercontent.com/13013769/99417594-61a3ec80-28fa-11eb-8d51-2b4de8f12152.png)
![Grafana-bug4 8](https://user-images.githubusercontent.com/13013769/99417597-623c8300-28fa-11eb-81f4-d8d38cf289dd.png)
![Grafana-bug4 9](https://user-images.githubusercontent.com/13013769/99417599-62d51980-28fa-11eb-9f37-473687fc70cb.png)

**What you expected to happen**:
The timeseries data connected in timeseries order on line graphs

**How to reproduce it (as minimally and precisely as possible)**:
Visualize a metric from InfluxDB. You need a datapoint in each minute, but make one of them missing. Then group by time(2m) and also group by a tag or two. Try to use fill(none) in the query.
I usually had some missing datapoints when this happened, so make sure, that the metric is not continuous. 

**Anything else we need to know?**:
If I change the visualization to table, the order also wrong:
![Grafana-bug4](https://user-images.githubusercontent.com/13013769/99417602-636db000-28fa-11eb-8f4f-b133dcc34ffe.png)
![Grafana-bug4 2](https://user-images.githubusercontent.com/13013769/99418263-1fc77600-28fb-11eb-97b6-eac5a46c7855.png)
But when I check the query inspector, the data points arrive in good order:
![Grafana-bug4 0a](https://user-images.githubusercontent.com/13013769/99418749-9d8b8180-28fb-11eb-98cb-289982b8fa2f.png)

If I change the time grouping and remove the fill(none) I see these datapoints:
![Grafana-bug4 0b](https://user-images.githubusercontent.com/13013769/99420612-b4cb6e80-28fd-11eb-841a-07c8517004fa.png)

**Environment**:
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: InfluxDB
- OS Grafana is installed on: Amazon Linux
- User OS & Browser: Windows, Chrome
- Grafana plugins: -
- Others:

**Comment by torkelo** [comment]
What transform are you using?

**Comment by EdeHeltovics** [comment]
Same here.

**Comment by ncsiki** [comment]
I've exactly the same issue!

**Comment by Willshield** [comment]
This transformation was on my chart. It does nothing. It maybe stuck when I deleted the ones I tried.
![transform](https://user-images.githubusercontent.com/13013769/100764057-39d27f80-33f6-11eb-87f4-056019d8e058.png)

After I removed this, the connection order seems good.

**Comment by hugohaggmark** [comment]
Closing this issue as it seems to be resolved when removing empty transform.
