### ISSUE TITLE
render url is prepending instead of appending

### ISSUE THREAD

**Issue by calebcall** [grafana/grafana#2916]
When I click the Share button for a graph, then click the "Direct link rendered image" button, render gets prepended to the url instead of appended (see screenshot).
![render-url](https://cloud.githubusercontent.com/assets/1132262/10399861/a22c5eb0-6e72-11e5-9931-54d6c47b7b11.png)

What could be causing this.  I'm on version 2.1.3.  I've defined root_url as https://dashboard.mydomain.com (which, as you can see, is what we access to get to grafana.  Is there a config somewhere else we need to define that might be misconfigured?

**Comment by torkelo** [comment]
thanks for reporting this. Was an issue when the domain name contained the word dashboard. Fixed in master / upcoming release.

**Comment by calebcall** [comment]
Interesting. Thanks for fixing.
