### ISSUE TITLE
Explore: URLs from 7.0.4 open an extra query editor in 7.3.2

### ISSUE THREAD

**Issue by timpalpant** [grafana/grafana#29172]
**What happened**: Explore URLs from Grafana 7.0.4 open a second, blank query editor when opened in 7.3.2. This seems to apply for all datasources.

Here is an example using a MySQL datasource:
![duplicate-queryeditor](https://user-images.githubusercontent.com/814226/99454638-b3e20f00-28f4-11eb-9a73-5b928abb859f.png)

The original Explore URL was:
https://grafana704/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Arbiter%22,%7B%22datasource%22:%22Arbiter%22,%22format%22:%22time_series%22,%22timeColumn%22:%22job_creation_time%22,%22metricColumn%22:%22none%22,%22group%22:%5B%5D,%22where%22:%5B%7B%22type%22:%22macro%22,%22name%22:%22$__timeFilter%22,%22params%22:%5B%5D%7D%5D,%22select%22:%5B%5B%7B%22type%22:%22column%22,%22params%22:%5B%22id%22%5D%7D%5D%5D,%22rawQuery%22:false,%22rawSql%22:%22SELECT%5Cn%20%20job_creation_time%20AS%20%5C%22time%5C%22,%5Cn%20%20id%5CnFROM%20reinstall_jobs_archive%5CnWHERE%5Cn%20%20$__timeFilter(job_creation_time)%5CnORDER%20BY%20job_creation_time%22,%22table%22:%22reinstall_jobs_archive%22,%22timeColumnType%22:%22timestamp%22%7D,%7B%22mode%22:%22Metrics%22%7D,%7B%22ui%22:%5Btrue,true,true,%22none%22%5D%7D%5D

But after opening this URL in Grafana 7.3.2, it is changed to:
https://grafana732/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Arbiter%22,%7B%22datasource%22:%22Arbiter%22,%22format%22:%22time_series%22,%22timeColumn%22:%22job_creation_time%22,%22metricColumn%22:%22none%22,%22group%22:%5B%5D,%22where%22:%5B%7B%22type%22:%22macro%22,%22name%22:%22$__timeFilter%22,%22params%22:%5B%5D%7D%5D,%22select%22:%5B%5B%7B%22type%22:%22column%22,%22params%22:%5B%22id%22%5D%7D%5D%5D,%22rawQuery%22:false,%22rawSql%22:%22SELECT%5Cn%20%20job_creation_time%20AS%20%5C%22time%5C%22,%5Cn%20%20id%5CnFROM%20reinstall_jobs_archive%5CnWHERE%5Cn%20%20$__timeFilter(job_creation_time)%5CnORDER%20BY%20job_creation_time%22,%22table%22:%22reinstall_jobs_archive%22,%22timeColumnType%22:%22timestamp%22%7D,%7B%22datasource%22:%22Arbiter%22,%22mode%22:%22Metrics%22,%22format%22:%22time_series%22,%22timeColumn%22:%22job_creation_time%22,%22metricColumn%22:%22none%22,%22group%22:%5B%5D,%22where%22:%5B%7B%22type%22:%22macro%22,%22name%22:%22$__timeFilter%22,%22params%22:%5B%5D%7D%5D,%22select%22:%5B%5B%7B%22type%22:%22column%22,%22params%22:%5B%22id%22%5D%7D%5D%5D,%22rawQuery%22:false,%22rawSql%22:%22SELECT%5Cn%20%20job_creation_time%20AS%20%5C%22time%5C%22,%5Cn%20%20id%5CnFROM%20reinstall_jobs%5CnWHERE%5Cn%20%20$__timeFilter(job_creation_time)%5CnORDER%20BY%20job_creation_time%22,%22table%22:%22reinstall_jobs%22,%22timeColumnType%22:%22timestamp%22%7D%5D

**What you expected to happen**: Explore opens with a single query editor, as it did in 7.0.4.

**How to reproduce it (as minimally and precisely as possible)**: Copy an explore URL in Grafana 7.0.4. Open the explore URL in Grafana 7.3.2 (after upgrading or on another instance with the same datasource configured).

**Anything else we need to know?**: This can make it difficult to use Explore URLs that have been previously saved in playbooks.

**Environment**:
- Grafana version: 7.0.4 -> 7.3.2
- Data source type & version: any
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: any
- Grafana plugins:
- Others:

**Comment by timpalpant** [comment]
I bisected releases and this starts occurring in 7.1.1

**Comment by timpalpant** [comment]
Based on the release notes, https://github.com/grafana/grafana/pull/26349 seems relevant

**Comment by timpalpant** [comment]
Reverting #26349 does seem to fix this issue on 7.3.2

**Comment by torkelo** [comment]
URLS from older Grafana versions are not 100% backward compatible. 

So if there is no easy way to support both new and old urls I think we can close this
