### ISSUE TITLE
Loki: Add support for alerting

### ISSUE THREAD

**Issue by dream0708** [grafana/grafana#29175]
The  Loki datasource does not support alerting queries

**Comment by orionstudt** [comment]
Is there going to be some documentation for this going up? For instance, is there any additional configuration or setup required? Is this at all related to the Loki `ruler` component or is that not even necessary when using Loki with Grafana?

**Comment by ivanahuckova** [comment]
You can find all information regarding alerting in our documentation: https://grafana.com/docs/grafana/latest/alerting/
