### ISSUE TITLE
Dashboard List panel: migration is incomplete

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#29182]
Ref @marefr `Search recent dashboard seems to be correct where's the dashboard panel list doesn't feel right`:

![image](https://user-images.githubusercontent.com/2376619/99501322-e3882a00-297b-11eb-9642-de47d906f680.png)
![image](https://user-images.githubusercontent.com/2376619/99501338-e7b44780-297b-11eb-987a-bd0c6bda618a.png)

**Comment by torkelo** [comment]
@kaydelaney can you take a look at this when you have time? 

Sorting the search results based on the ids from the impression service was how the old implementation made sure the recent dashboards list was in the correct order: https://github.com/grafana/grafana/blob/v7.3.3/public/app/plugins/panel/dashlist/module.ts#L137
