### ISSUE TITLE
Legend is overridden when the time is on 2 lines

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#29190]
**What happened**: I'm displaying a simple graph and the time is on 2 lines (because the graph is not wide enough) and the legend is overridden.

![image](https://user-images.githubusercontent.com/2684878/99511890-200e5280-2989-11eb-9e3b-b7010e5d6e6f.png)

**What you expected to happen**: I would prefer to have the legend shifted a bit lower to avoid this ugly display.

**How to reproduce it (as minimally and precisely as possible)**: Just add a narrow graph

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.3
- Data source type & version: Home made (but does not matter)
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@sbouchex thanks for reporting this issue. I've just tried reproducing it, but couldn't end up in the described situation. 

Is this something you are experiencing repetitively?

**Comment by sbouchex** [comment]
sporadic issue...
