### ISSUE TITLE
Upload tarballs to GCS with correct content type

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#29193]
**What happened**:
Upload tarballs to GCS with content type application/x-gzip, since otherwise Firefox downloads them with extension .tar.tar (Chrome gets it right OTOH). Also check other file types.

**Comment by idafurjes** [comment]
The bug was fixed on the Firefox side.

**Comment by aknuds1** [comment]
It's not a bug on Firefox' side per se (since the MIME type wasn't set correctly in GCS), but I'm guessing that Firefox uses the real file extension now instead of deducing it from the MIME type.
