### ISSUE TITLE
401 error if Grafana window is not visible for more than 5 minutes

### ISSUE THREAD

**Issue by abligh** [grafana/grafana#2919]
Summary
------------

If the Grafana window is not visible for more than 5-10 minutes, it produces continuous 401 errors. If the window is visible, it does not.

Details
---------

I'm running Grafana with InfluxDB and an Apache SSL proxy on Ubuntu 14.0.4

    $ dpkg --list | egrep 'grafana|influx|apache2'
    ii  apache2                             2.4.7-1ubuntu4.6                 amd64        Apache HTTP Server
    ii  apache2-bin                         2.4.7-1ubuntu4.6                 amd64        Apache HTTP Server (binary files and modules)
    ii  apache2-data                        2.4.7-1ubuntu4.6                 all          Apache HTTP Server (common files)
    ii  grafana                             2.1.0                            amd64        Grafana
    ii  influxdb                            0.9.5-nightly-bc569e8            amd64        Distributed time-series database

I'm accessing it using Chrome Version 45.0.2454.101 (64-bit) on OS-X Mavericks.

If I leave Chrome on the Grafana dashboard, with Chrome visible, it will stay refreshing seemingly indefinitely. The OS-X screensaver kicking in does not affect things.

If I maximise another application (e.g. Mail) over the Chrome window, then (after about 5-10 minutes) return to Chrome, the previous Grafana screen is shown briefly, and then Grafana attempts to refresh, leading to a continuous stream of 401 errors.

I see this in the Grafana log (many many similar lines):

    2015/10/10 09:46:06 [I] Completed /api/datasources/proxy/1/query 401 Unauthorized in 200.508µs
    2015/10/10 09:46:06 [I] Completed /api/datasources/proxy/1/query 401 Unauthorized in 166.839µs
    2015/10/10 09:46:06 [I] Completed /api/datasources/proxy/1/query 401 Unauthorized in 480.754µs

I believe what is happening is this:
* When the Grafana window is visible (even 'behind' a screen-saver), Chrome is regularly polling Grafana which is renewing the session cookie.
* When the Grafana window is fully covered, Chrome minimises the refresh of its window, therefore does not poll the Grafana server in the same manner, and thus the session cookies is renewed

However, tailing the apache2 access log shows that it does in fact poll at least the proxy interface. It's possible that the polling of the proxy interface is insufficient to renew the session cookie or similar. During this period nothing appears the grafana log (until the 401s appear), but lines do appear the apache access log:

    10.1.16.22 - - [10/Oct/2015:09:54:59 +0100] "GET /api/datasources/proxy/1/query?epoch=ms&q=SELECT+no...
    10.1.16.22 - - [10/Oct/2015:09:54:59 +0100] "GET /api/datasources/proxy/1/query?epoch=ms&q=SELECT+me...
    10.1.16.22 - - [10/Oct/2015:09:54:59 +0100] "GET /api/datasources/proxy/1/query?epoch=ms&q=SELECT+me....

I am using file based session storage in Grafana.

This is completely repeatable. It does not appear to happen if Grafana is at the front.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master and in next build (building new 2.5 pre release now packages now)

**Comment by abligh** [comment]
Thanks!

**Comment by abligh** [comment]
I can confirm that the build from yesterday is far far better - I now never see 401. It also seems to have fixed occasionally periodic marking of stats as unavailable for a single refresh. Thanks a million.

There's one tiny nit. If you set autorefresh to 30 seconds, then attempt to replicate this bug, then when you return to the Grafana page (by Apple-Tab'ing it back in or whatever) the last graphs are shown very briefly (as before) then all graphs switch to 'no datapoints' until the remainder of the 30 second period has elapsed. They then right themselves. With autorefresh on there's no simple way to refresh the page manually (as far as I can tell), so you are left waiting for between 0 and 30 seconds. I don't know whether it would be possible to work out if a refresh has *actually* not been done for more than 30 seconds and if so cause a manual refresh?
