### ISSUE TITLE
ShareModal: Form updates to share link

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29191]
Todo
* [ ] Remove the template variable option and close #21131
* [ ] Change the time range option to instead be "Lock time range"  with a description "Will transform a relative to now time range to a fixed absolute time range". Only show this if the current time range is relative to now. 
* [ ] Update form styles to new form components. 

Code https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/ShareModal/ShareLink.tsx 
 
Current modal: (found in dashboard share & panel share) 
![Screenshot from 2020-11-18 10-35-32](https://user-images.githubusercontent.com/10999/99512537-deca7280-2989-11eb-86e6-8cf8d1172a97.png)

**Comment by oscarkilhed** [comment]
I'll update the styles for the "Snapshot" and "Export" tabs as well

**Comment by oscarkilhed** [comment]
![image](https://user-images.githubusercontent.com/468940/105057199-44fc7000-5a75-11eb-9fa2-5ca0e9b1e2b8.png)
The embed tab has the same time range switch as link, I'm guessing we should treat this the same as the link tab?
