### ISSUE TITLE
Long error messages are incorrectly displayed

### ISSUE THREAD

**Issue by hemdrup** [grafana/grafana#29196]
Not so much about the message but how it looks.  new datasource -> elastic
<img width="2045" alt="Screenshot 2020-11-18 at 11 24 35" src="https://user-images.githubusercontent.com/21049979/99518640-21dc1400-2991-11eb-9ecc-464ef4d62624.png">ce

<img width="2125" alt="Screenshot 2020-11-18 at 11 24 42" src="https://user-images.githubusercontent.com/21049979/99518628-1daff680-2991-11eb-9519-9b09fc0c48db.png">

**Comment by hemdrup** [comment]
Using the wrong installation guide on the Grafana website https://grafana.com/docs/grafana/latest/installation/ using Brew. Where there was no docker setup, and thins like devenv sources=influxdb,loki to setup the data

I later learned that this was the correct guide:
https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md

What i think the error is; is that it can’t find Docker or the data. As it’s just a blank brew install 
I just wanted to report how the error was visually not inside the error message area (The red part)

**Comment by thisisobate** [comment]
Alright. Would take a look at this.
