### ISSUE TITLE
grafana6.7.4 Serious bug

### ISSUE THREAD

**Issue by uranus829** [grafana/grafana#29195]
new system:centos7.9
grafana version:6.7.4
open zabbix plugins error:
Cannot read property 'FormField' of undefined Evaluating http://192.8.29.12:3000/public/plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module.js Loading plugins/alexanderzobnin-zabbix-app/datasource-zabbix/module
![1](https://user-images.githubusercontent.com/46716344/99518512-a2b80180-29cb-11eb-89da-090b926a5b57.png)
![2](https://user-images.githubusercontent.com/46716344/99518519-a5b2f200-29cb-11eb-975d-f44d0f2d56bb.png)

**Comment by torkelo** [comment]
Need to use a newer version of Grafana (try 7.3)

**Comment by uranus829** [comment]
The function of table paging in version 7 is removed, I want to return to the old version。

**Comment by torkelo** [comment]
ok, have to downgrade the plugin to one that is compatible with 6.7

**Comment by uranus829** [comment]
How to downgrade zabbix version?thank you!
![image](https://user-images.githubusercontent.com/46716344/99533877-858e2d80-29e1-11eb-9b82-b98b3967b416.png)
