### ISSUE TITLE
Adding trailing / to a KairosDB datasource URL breaks 

### ISSUE THREAD

**Issue by burtonator** [grafana/grafana#2920]
If you add a URL like:

http://example.com/

As your datasource URL for KairosDB it won't work.

The datasource URL includes two / characters in a row.

This results in a 404.

The 404 doesn't include CORS headers so then you get errors about CORS.

This confused me and I spent like 20 minutes trying to debug CORS issues.

Maybe add a lib so that building URLs doesn't ever generate this type of bug?

**Comment by bergquist** [comment]
moved to https://github.com/grafana/datasource-plugin-kairosdb/issues/3
