### ISSUE TITLE
Docs: Merge index & overview pages and other menu related issues

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29204]
With the new file based menu system you now see the index pages (many are just about empty). 

Update from robby, you can add `menuTitle = "My custom menu title"` to customize the side menu page title. Can be useful to show shorter more readable page titles in the menu. This might not work in dev environment right away robby adding support for it now. 

* [ ] Getting started page is almost empty (_index.md), either make this the Getting started with Grafana page and remove that one or make it contain a list of all gettings started guides.
* [ ] Duplicate Panels page under Panels 
* [ ] Alerting and Alerts overview seems like the same page (overview page can be removed, and alias added to the index page) 
* [ ] Administration _index.md is bit empty as well 
* [ ] All the sub pages under HTTP API should not be listed in the menu (better accessed from the index page). See below how to disable a page listing in menu. 
* [ ] Move HTTP API section under Developers 

Add 
```
[_buid]
list = false 
```

to the frontmatter to disable listing a page in the menu. 

Bugs:
*  [ ] Transformations opens two sections 
![Screenshot from 2020-11-18 15-20-42](https://user-images.githubusercontent.com/10999/99541902-af2f6080-29b1-11eb-816f-f4eb837c3d2f.png)

* [ ] Having all the variable type pages start with Add makes it hard to find the one you are looking for in the menu.
![Screenshot from 2020-11-18 15-24-01](https://user-images.githubusercontent.com/10999/99542250-22d16d80-29b2-11eb-9170-35949cee57d5.png)

**Comment by achatterjee-grafana** [comment]
All great suggestions. I will get working on this.
