### ISSUE TITLE
Allow template variable expansion for datasource template variables.

### ISSUE THREAD

**Issue by tcolgate** [grafana/grafana#29208]
**What would you like to be added**:
I'd like to be able to use a template variable to select a datasource.

**Why is this needed**:
I'd like to be able to have an "environment", template variable, with static values (staging and production), and allow the user to select this, with the result that it automatically selects appropriate prometheus, loki and jaeger datasource. e.g.
User select "staging" for a custom variable, which then automatically results in 3 hidden datasource variables selecting
$environment = staging
$traces -> "Traces - staging"
$metrics -> "Metrics - staging"
$logs -> "Logs - staging"

Panels then use $traces, $metrics and $logs. Selecting "production" would result in the obvious alteration.

Using $environment in the "instance name filter" regexp does not seem to work (which is not unreasonable, since the variable expansion mechanism is a big ambiguous within regexp).

I'm not aware of other mechanisms for achieving this.

**Comment by dprokop** [comment]
@hugohaggmark does anything come to your mind that could currently solve the problem? Otherwise, this seems like a feature request.

**Comment by hugohaggmark** [comment]
@tcolgate @dprokop not sure I understand what the root issue is here. The "instance name filter" regexp works fine I think, but you must name your data sources with a convention. 

I created [this dashboard ](https://play.grafana.org/d/Vwb-aboMz/allow-template-variable-expansion-for-datasource-template-variables?orgId=1) that I think shows how this works.

**Comment by tcolgate** [comment]
Aha!, OK, I did try a bunch of variations, but I think the surrounding it in parens is what I was missing, thanks!
