### ISSUE TITLE
Don't store the default admin password in the conf file.

### ISSUE THREAD

**Issue by burtonator** [grafana/grafana#2921]
I think this is a usability bug.

99% of the time people are going to probably start the grafana-server without changing the config file first.

It's unclear that it's initialized on startup and so is present in the config file.

I changed it and them promptly forgot what it was.. so I locked myself out of my own install.

MAYBE just FORCE the users to login change the admin password immediately after first setup?

**Comment by daniellee** [comment]
The user is now asked to change the default password on first login.
