### ISSUE TITLE
OAuth assign Server Admin Permission

### ISSUE THREAD

**Issue by alex1989hu** [grafana/grafana#29211]
**What would you like to be added**:
Grafana `v7.3` provides option to automatically assign **Grafana Server Admin** permission to specific **LDAP Group**. But this is not possible if you want to use **OAuth** authentication.

**Why is this needed**:
It is only possible to map roles *(e.g. Admin, Viewer)*, but it has less privilege than **Grafana Server Admin**.

So the feature request is about to provide **OAuth** option to automatically assign **Grafana Server Admin** permission like we currently have for roles.

**References**:
Grafana Server Admin - https://grafana.com/docs/grafana/latest/permissions/#grafana-server-admin

LDAP to configure Grafana Server Admin `grafana_admin` option - https://grafana.com/docs/grafana/latest/auth/ldap/

OAuth Role mapping - no Grafana Server Admin option - https://grafana.com/docs/grafana/latest/auth/generic-oauth/#role-mapping

**Comment by alex1989hu** [comment]
This PR contains the resolution of the request I created: https://github.com/grafana/grafana/pull/23661

Unfortunately it is closed, no progress.

**Comment by akromish** [comment]
Would be very useful if mapping to server admin is possible. We're using auth.okta to configure roles, and it would be preferable to map a certain okta group to the 'Server Admin' role.
