### ISSUE TITLE
Allow ability to do joins on LogQL

### ISSUE THREAD

**Issue by vjsamuel** [grafana/grafana#29214]
**What would you like to be added**:
Currently LogQL has robust features in being able to do counting and various aggregations on metric fields in the log lines. On PromQL, currently we have the ability to use state metrics to do joins so that metrics can be enriched at query time with additional labels that describe the source. It would be beneficial if we could do the same with LogQL.

**Why is this needed**:
There can be external labels that define the log line more than just the labels that are coming with the log line. being able to joins allows a more robust querying experience.

https://www.section.io/blog/prometheus-querying/ provides a good read on how it is being used on PromQL today.

**Comment by vjsamuel** [comment]
cc: @cyriltovena

**Comment by dprokop** [comment]
@vjsamuel Could you please open a feature request in https://github.com/grafana/loki project?
