### ISSUE TITLE
Metric name in alerts always displayed as "Value {}"

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#29213]
**What happened**: All metric names in alerts are being displayed as: `Value {}` (apparently for `CloudWatch` datasource only)

**What you expected to happen**: The label to be showed as it's visible, e.g. in the graph's legend.

**How to reproduce it (as minimally and precisely as possible)**: When an alarm enters pending/error state, the "Metric name" value is always `Value {}`

**Anything else we need to know?**: Data from `CloudWatch` datasource where `Alias` field is set to `{{label}} (XXX)` (_XXX_ is just some text).
Issue observed both on `Email` alerts and `Alert list` panel. Broken on `7.3.2` and `7.3.3` (seemed to be working fine in versions `7.3.1` and earlier as the update from `7.3.1` to `7.3.2` was performed in the afternoon of Nov 12).
**UPDATE**: confirming the issue appeared in `7.3.2` as after downgrading to `7.3.1` it's working as expected.
The screenshot below shows the "broken" PENDING states metric name happening from the 13th of November.

![grafana-alerts](https://user-images.githubusercontent.com/15344273/99566180-78af1100-29c4-11eb-9c4c-142431c14f3f.png)

**Environment**:
- Grafana version: 7.3.2 and 7.3.3
- Data source type & version: CloudWatch
- OS Grafana is installed on: linux (docker)
- User OS & Browser: windows 10 / chrome 86
- Grafana plugins: n/a
- Others: official grafana docker image

**Comment by wbrowne** [comment]
Thanks for creating this issue @salavessa. Unfortunately, I haven't been able to reproduce. Could you share the JSON payload output from testing the alert rule?

**Comment by salavessa** [comment]
Thanks for looking into it.
Attached is the JSON payload output from testing the same alert rule both in grafana 7.3.1 (good labels) and 7.3.2 (bad labels).
[731-and-732-alert-test.zip](https://github.com/grafana/grafana/files/5641800/731-and-732-alert-test.zip)

**Comment by wbrowne** [comment]
Thanks for the extra info @salavessa! Do you by any chance have `Field` changes or `Overrides`? I was experimenting a bit and noticed different behaviour between `7.3.1` and master. It didn't highlight the main issue you're seeing, but I'm just curious as I dig a bit deeper

**Comment by salavessa** [comment]
No `Field` changes or `Overrides`, but I do have the following panel's `Series overrides`: _Alias or regex:_ `/storage|memory/i` = `Y-axis: 2`. Everything else is pretty much the standard "static" selections.

**Comment by salavessa** [comment]
Not sure if it helps but I'm able to reproduce this with completely clean grafana `7.3.2`, `7.3.3` and `7.3.4` containers. Steps below:
1. run container, e.g. `docker run -d --name=grafana -p 3000:3000 grafana/grafana:7.3.2`
2. add new `CloudWatch` datasource (I'm using `AWS SDK Default` and `Assume Role ARN`)
3. create Dashboard + Add new panel
  3.1. select the `Cloudwatch` datasource created before
  3.2. set `Expression` field to something like: `SEARCH('{AWS/RDS,DBInstanceIdentifier} MetricName="CPUUtilization"','Average',300)`
4. `Create Alert` and set the condition value (e.g. to 50)
5. save Dashboard
6. edit dashboard panel and `Test rule` in Alert: the series have "bad labels": `"name": "Value {}"`

**Comment by wbrowne** [comment]
Thanks for the extra info @salavessa. Hopefully, a fix coming your way soon!
