### ISSUE TITLE
synchronize language for Legend & Tooltip

### ISSUE THREAD

**Issue by ianvanhoven** [grafana/grafana#29215]
**What would you like to be changed**:
The features for boolean metric options "Hide in tooltip" and "Legend" are effectively identical, just differing in which object you're choosing to either show or hide. Suggest making the "Legend" feature have the same verbiage as its tooltip cousin -- namely...
- "Hide in Legend?" T/F
- "Hide in Tooltip?" T/F

**Why is this needed**:
Consistency.

<img width="611" alt="Screen Shot 2020-11-18 at 3 34 35 PM" src="https://user-images.githubusercontent.com/19738254/99601111-a0e24400-29b3-11eb-9869-fbc2de6a12f5.png">

**Comment by torkelo** [comment]
We are soon going to introduce our new Graph panel that will be using our new field override system, so this old graph panel will be deprecated
