### ISSUE TITLE
Docs feedback: /panels/visualizations/logs-panel.md

### ISSUE THREAD

**Issue by michael-doubez** [grafana/grafana#29224]
Hello,

In section "Log level", there is a bad link in `See supported log levels and mappings of log level abbreviation and expressions.`

It links to `https://grafana.com/docs/grafana/latest/panels/visualizations/explore/#log-level/` 

But it should be `https://grafana.com/docs/grafana/latest/explore/#log-level`

It must be related to the relative ref

    <a href="../explore/#log-level/">supported log levels and mappings of log level abbreviation and expressions</a>

**Comment by oddlittlebird** [comment]
I just tested it, and it is working now.
