### ISSUE TITLE
Floating hover over panel displays incorrect time if one series is missing data

### ISSUE THREAD

**Issue by abligh** [grafana/grafana#2922]
This bug concerns the 'hover over' that shows when hovering over charts (at the top it shows the date of the point concerned, and below that it shows the value of each series plotted) - sorry I don't know the proper terminology.

If a chart displays multiple series, and one of those series is missing data (for instance because the data series starts AFTER the time in question), then the hover over shows the correct data, but the wrong date. As far as I can tell it always shows the earliest date for which every series has data.

This is pretty annoying as if you have an existing working graph, then add some other data series to be graphed (where the data is only now being recorded), the hover-over date stops working for the existing series - i.e. if you hover over the original data in the period before the new data is collected, it shows you the date you started collecting the new data.

My datasource is influxdb and I am running the latest nighty build of grafana (well today's prerelease) and:

    # dpkg --list | egrep 'influx|grafana|apache'; uname -a
    ii  apache2                             2.4.7-1ubuntu4.6                 amd64        Apache HTTP Server
    ii  apache2-bin                         2.4.7-1ubuntu4.6                 amd64        Apache HTTP Server (binary files and modules)
    ii  apache2-data                        2.4.7-1ubuntu4.6                 all          Apache HTTP Server (common files)
    ii  grafana                             2.5.0-pre1                       amd64        Grafana
    ii  influxdb                            0.9.5-nightly-bc569e8            amd64        Distributed time-series database
    Linux panopticon 3.13.0-65-generic #106-Ubuntu SMP Fri Oct 2 22:08:27 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

With an OS-X 10.6 Chrome client, Version 45.0.2454.101 (64-bit)

**Comment by abligh** [comment]
It would seem that in order to demonstrate the bug, the 'new' data series needs at least one point displayed on the chart.

**Comment by torkelo** [comment]
just use fill(0) in your influxdb query

**Comment by abligh** [comment]
fill(0) doesn't really help because that will display zero when there is no data. I don't want it to do that (as in this case zero would indicate something wrong as opposed to no data).


On 10 Oct 2015, at 23:02, Torkel �degaard <notifications@github.com> wrote:

> Closed #2922.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Alex Bligh

**Comment by abligh** [comment]
Actually there is a more significant problem with fill(0). The new stat is recorded relatively infrequently, so I see a sort of impulse graph with spikes if I use that. I'm actually using fill(previous), but there is (obviously) no previous point.

One answer would be to artificially insert a previous point with value zero, but that doesn't work as I'd need to insert one with every possible tag (the tags in my case being UUIDs which are dynamically generated).

On 10 Oct 2015, at 23:02, Torkel �degaard <notifications@github.com> wrote:

> Closed #2922.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Alex Bligh
