### ISSUE TITLE
Error 422 on db POST when query do not exist while creating an Alert

### ISSUE THREAD

**Issue by gustavo80br** [grafana/grafana#29221]
Steps to reproduce:

1. Create two queries, A and B and save the dashboard
2. Remove the query A and save the dashboard
3. Create an alert and save

The interface will give you no error informing any problem. User have the sensation of dashboard saved, because no error message was thrown. The save button will become unresponsive after that.

Under the hoods, a POST call to db endpoint is returning 422 with the message "No query(A) found", because when you create an Alert, the default is for the A query, but the A query do not exist. The workaround is to change the query letter and then save. 

I took some time to realize what was happening. I think would be better if after save, on error 422, the error message to be presented to the end user, so that he can go direct to the problema and solve it (query not found).

Thanks! Great software, really amazing work. Will help to fix it if I can.

**Comment by torkelo** [comment]
Closing this as this will be fixed by new alerting engine
