### ISSUE TITLE
Feature request: Allow option to disable auto-refresh above a maximum time range

### ISSUE THREAD

**Issue by phreakocious** [grafana/grafana#2924]
Hi, I was hoping to add this myself but it was a bit beyond me.  When a dashboard has a ton of data points, going to long time ranges combined with a short auto-refresh interval can cause lots of browser hanging and needless updates .  Maybe allow for minimum auto-refresh interval based on the time range?

Thanks, grafana is awesome.

**Comment by torkelo** [comment]
hanging? what data source do you use? Graphite is equally fast no matter the time range, InfluxDB is slower due to no rollups, but all should not hang the browser that means you have a InfluxDB query without group by time or some other data source that returns why to much data.  

Auto refresh is turned on for absolute time ranges, so when you zoom out it should be disabled.

**Comment by torkelo** [comment]
updated above comment, should say "Auto refresh is turned off", So when you zoom in or out it auto refresh should be disabled. But if you pick "Last 90 days" and set auto refresh then that is what you have selected.

**Comment by phreakocious** [comment]
This would be with graphite and is specifically when changing the 'Last X days' setting.  A typical case for me would be creating a a dashboard with say, a 2 hour view and a 1 minute auto refresh.  If someone views that dashboard and changes that to 7 or 14 days, the amount of data evaluated goes way up.  This results in much higher CPU usage from the browser to deal with the extra data.  All of that is fine and understandable, but the refreshes at 1 minute are probably not providing much value in the graphs for the amount of data displayed vs the amount of CPU thrashing and browser unhappiness.  Remembering to disable auto refresh manually before doing this is currently what I tell people but if it could be done 
automatically, that would be helpful.

Thanks again!

**Comment by phreakocious** [comment]
Oh, to your other point about something returning 'way too much data' ... Is there some guidance as to how much is too much or does it just come down to experiment and see?

**Comment by torkelo** [comment]
All the official data sources if used correctly should never return more data points than there are pixels in the graph, more is just unnecessary. For example with graphite we send a maxDataPoints that will be set to the graph width in pixels for each graph (so a graph with full span will get more data points than a very small graph). The same hold for InfluxDB IF you use `group by time ($interval)` grafana will set the interval variable so you approximately get 1 data point per pixel. OpenTSDB and KairosDB have some other ways to do the same, cant remember now.

**Comment by phreakocious** [comment]
I see, sounds like the moral of the story is... Don't put too many metrics on a single dashboard.

**Comment by torkelo** [comment]
@phreakocious not att all, you can have 20-30 graphs in grafana and it will load in under a second no matter how big the time range is. If you have a a fast time series store and correctly configured queries that don't return million of data points that is,  as I said in the above comment it is important the the time series query sensible group by time / summarize so at max only 1 data point per pixel is returned

**Comment by torkelo** [comment]
You must be using graphite 0.9.12, that does not support maxDataPoints and without that it makes Grafana feature graphite will return way to much data. I suggest you update Graphite

**Comment by phreakocious** [comment]
Yes, you totally nailed it.  Sadly we diverged from main graphite at 0.9.9 and are overdue to port the custom stuff forward.  Thanks a bunch for making sense of this!
