### ISSUE TITLE
Tempo datasource doesn't clear errors correctly

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#29242]
**What happened**:
Using the Tempo datasource I searched for a trace and received an error.  Everything behaved as expected here.

However, if I searched a second time for the same trace id two things happened that could be cleaned up:
- The spinner immediately went from red to blue indicating that the query had completed.  (It hadn't)
- The original error message was never cleared during the search.

The consequence of this is that the user thinks that the second query immediately errored while it is still ongoing.

![image](https://user-images.githubusercontent.com/2272392/99705029-3094fa80-2a67-11eb-8a7f-639e6e2dfee9.png)

**What you expected to happen**:
- The spinner should continue until the second query returns successfully or not
- The error should be cleared when the query starts

**How to reproduce it (as minimally and precisely as possible)**:
In Grafana Explore using the Tempo datasource:
- Search for a trace that will fail (404 is fine)
- Search for the same trace again
- Note that the error is not cleared when you start the second search and the spinner immediately goes back to blue before the query comes back.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana v7.4.0-6940pre (993adb72e0)
- Data source type & version:  Tempo (unsure on version)
- OS Grafana is installed on:  Docker/Kubernetes
- User OS & Browser: Ubuntu/Chrome
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
Fixed in #30367 Thank you @ivanahuckova
