### ISSUE TITLE
Can not show tacked values individually when use InfluxDB 0.9.x datasource

### ISSUE THREAD

**Issue by xqliang** [grafana/grafana#2925]
Stacked values always show cumulatively.

    dpkg --list | egrep 'grafana|influxdb'                                                                                 
    ii  grafana                            2.1.3                         amd64        Grafana
    ii  influxdb                           0.9.4.2                       amd64        Distributed time-series database

**Comment by torkelo** [comment]
there is a display option to stack individually in display styles tab :)

**Comment by xqliang** [comment]
My statement is not clear, I mean whatever I choose cumulatively or individually, it always show cumulatively.

**Comment by torkelo** [comment]
@xqliang you are talking about the hover tooltip? 

If not then you should not use stack as stack will stack values, the cumulatively / individual option is for the hover tooltip.

**Comment by xqliang** [comment]
Sorry, I understand wrong with the cumulative / individual option. Thank you.
