### ISSUE TITLE
Latest from the blog panel: blog links point to my local grafana host instead of grafana.com

### ISSUE THREAD

**Issue by systemcrash** [grafana/grafana#29252]
**What happened**:

I clicked a link. 

**What you expected to happen**:

It points to correct URI

**How to reproduce it (as minimally and precisely as possible)**:

Click on any 'blog' link in Grafana `Latest from the blog` panel

**Anything else we need to know?**:

nope.

**Environment**:
- Grafana version: 7.3.3 (was OK in 7.2.2)
- Data source type & version:
- OS Grafana is installed on: Docker img
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
thanks for reporting this, it's a bug in the RSS feed. We will fix asap.

**Comment by qkombur** [comment]
Tested with my local install of Grafana. RSS feed should be working now.

**Comment by torkelo** [comment]
This should be fixed now, the links are absolute

**Comment by systemcrash** [comment]
Fixed.
