### ISSUE TITLE
Grafana dashboard/browser tab freezes when null data is returned for Stat panel graph

### ISSUE THREAD

**Issue by mrmantas** [grafana/grafana#29259]
**What happened**:
Upon opening a dashboard containing this Stat panel (Datasource - Graphite), Grafana browser tab freezes, has to be forcefully closed to recover. No interaction with the browser tab are working.

**What you expected to happen**:
Stat panel should show No Data (like in case when empty array is returned) or 0 value

**How to reproduce it (as minimally and precisely as possible)**:
Have a metric in Graphite which contains only null values. Add a Stat panel which shows some value from that metric and enable Stat panel graph for this panel.
This would be an response query result that causes the freeze (taken from query inspector):
![image](https://user-images.githubusercontent.com/12285603/99773272-dfdbdb00-2b14-11eb-8d52-4ab90d241e07.png)

If there are any non-null values, or Array is empty, everything is working as expected and a value or No Data is shown

**Anything else we need to know?**
Workaround is to disable Graph mode Stat panel graph / sparkline mode for this panel.
I believe this issue was not present with grafana version6.

**Environment**:
- Grafana version: Grafana v7.3.2
- Data source type & version: Graphite
- OS Grafana is installed on: RHEL
- User OS & Browser: Windows, Chrome/Firefox
- Grafana plugins: all default grafana labs plugins

**Comment by dprokop** [comment]
Please upgrade to 7.3.3, this bug was fixed in [that release](https://github.com/grafana/grafana/blob/master/CHANGELOG.md#733-2020-11-17) by https://github.com/grafana/grafana/pull/29077
