### ISSUE TITLE
Stop Loki Live tail when a close message is received

### ISSUE THREAD

**Issue by alanhe** [grafana/grafana#29257]
**What would you like to be added**:
In the Explore page, choose a Loki data source, compose a LogQL and click the Live button.
When Loki meets some error and send a close message, e.g.:
https://github.com/grafana/loki/blob/master/pkg/querier/http.go#L229

The Grafana UI does not exit from the Live tail mode. It may confuse users by thinking the WebSocket connection is still on, but they are, in fact, not getting new data anymore.

It will better if:
1. Grafana exits the Live mode automatically when a close message is received.
2. The *reason* of why the server interrupts the WebSocket connection can be shown in the alert-container.

**Why is this needed**:

**Comment by ivanahuckova** [comment]
There was done a work around live tailing (https://github.com/grafana/grafana/pull/30517, https://github.com/grafana/grafana/pull/29438) and this shouldn't be an issue in the next (7.4) release. Please feel free to reopen if you still encounter this issue.
