### ISSUE TITLE
Overriding panel positions in mobile version

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#29264]
**What would you like to be added**:
Ability to override panel positions in the mobile version of the site

**Why is this needed**:
Default version:
![Screenshot_1](https://user-images.githubusercontent.com/43705385/99781191-972e1d00-2b28-11eb-9ecd-7f4f1a075943.png)

But in the mobile version I can't influence their position in any way
![photo_2020-11-20_12-04-29](https://user-images.githubusercontent.com/43705385/99781189-95645980-2b28-11eb-8f5c-7cf0c11dbbeb.jpg)

**Comment by torkelo** [comment]
What order are they in the dashboard json model? (Check settings / JSON model). 

When I test the mobile order is the same as in the desktopt version going from left to right
