### ISSUE TITLE
Grafana UI only displays data for 5 days (parameter) in dashboard

### ISSUE THREAD

**Issue by heartTorres** [grafana/grafana#29268]
**What happened**:
I have installed prometheus, grafana and thanos. The grafana gets its data from Thanos Query.
When I do query from grafana UI with 5 days parameter, the data shown in the UI is complete. But when I query beyond 5 days the graph is incomplete, for example for 3 weeks
**What you expected to happen**:
If I query for 3 weeks data, the dashboard should be completed. See screenshots below.

**Complete graph when I only use 5 days of data:**
<img width="1335" alt="Screen Shot 2020-11-20 at 7 06 53 PM" src="https://user-images.githubusercontent.com/65100615/99793499-bf873d00-2b63-11eb-9ec5-9a6b5d7e8147.png">

**Incomplete graph when I use more more than 5 days or even weeks of data:**
As you can see in the first image, I have data from 11/16. But it was not shown here when using weeks of date range.
<img width="1339" alt="Screen Shot 2020-11-20 at 7 07 57 PM" src="https://user-images.githubusercontent.com/65100615/99793510-c1e99700-2b63-11eb-973d-3a0ee5478bc2.png">

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: rancher/grafana-grafana 6.7.4
- Data source type & version: Thanos v.0.15
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
probably a thanos issue, check what the query returns using panel menu > inspect -> query inspector
