### ISSUE TITLE
SQLStore: customise the limit of retrieved datasources per organisation

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#29262]
**What would you like to be added**:
Change this limit and make it configurable:
https://github.com/grafana/grafana/blob/ab078133bfe9771f06bd21712f7ad6f9113c8a61/pkg/services/sqlstore/datasource.go#L70

**Why is this needed**:
This is short-term solution until we get [pagination](https://github.com/grafana/grafana/issues/29260).

**Comment by divbhasin** [comment]
Hi, new contributor here 👋 I can give this a shot. @papagian just to clarify, when you say to make the limit configurable, do you mean that it could be something that a user can specify in their .ini config file, or would it be something controlled through the UI?

**Comment by papagian** [comment]
> Hi, new contributor here 👋 I can give this a shot. @papagian just to clarify, when you say to make the limit configurable, do you mean that it could be something that a user can specify in their .ini config file, or would it be something controlled through the UI?

something that a user can specify in their .ini config file

**Comment by papagian** [comment]
`GetDatasources()` is called by the api and also by the alerting service.

I think we only have to apply this limit when the call is coming from the api.
Otherwise, in the extreme case that the `dsName` is empty  and the default datasource it’s not in the first 5000 (or whatever the limit is)
this function will return an error:
https://github.com/grafana/grafana/blob/22788d1d861094170b993d3f1a659d2a79876826/pkg/services/alerting/extractor.go#L33-L55
