### ISSUE TITLE
Pagination: Improve generic pagination component for grafana/ui

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29260]
Develop a wrapper around https://github.com/react-component/pagination , similar to how 
https://github.com/ant-design/ant-design/blob/master/components/pagination/Pagination.tsx  has done it but A LOT fewer options, only options that we really will need. 

We have many pages that require pagination, think the only place that use it now is the server admin user list. We do have a Pagination component already in grafana/ui but it's super duper simple .

We need it do be able to handle this 
![Screenshot from 2020-11-20 08-54-54](https://user-images.githubusercontent.com/10999/99774592-4c9fa700-2b0e-11eb-974f-57f51389ff74.png)

And when too many pages do this:
![Screenshot from 2020-11-20 08-56-56](https://user-images.githubusercontent.com/10999/99774687-6e009300-2b0e-11eb-88a2-4f8ebcfcb57c.png)

We may also try to just solve those use cases with the component we have instead of using rc-pagination as the base. 

Here is our current Pagination component:
https://developers.grafana.com/ui/latest/index.html?path=/story/buttons-pagination--with-pages 

And in the code: 
https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Pagination/Pagination.tsx

This how bad our current pagination component is:
![Screenshot from 2020-11-20 09-02-35](https://user-images.githubusercontent.com/10999/99775209-39410b80-2b0f-11eb-8fcf-4f90ed4d5d8c.png)

**Comment by thisisobate** [comment]
So this is what I imagine scrolling to page 6 would look like:  
![image](https://user-images.githubusercontent.com/29557702/100340340-4fe9d580-2fdb-11eb-9695-ab47ff1de0d0.png)
Wdyt? @torkelo

**Comment by torkelo** [comment]
@thisisobate 

Not sure what you mean by scrolling to page six? (there is no scroll, I assume clicking page 6?) 

That state looks incorrect to me, if you are currenly on page six you would have page 2,3,4 to the left of page 6 button

![Screenshot from 2020-11-26 13-15-56](https://user-images.githubusercontent.com/10999/100350015-8dedf600-2fe9-11eb-95f9-6d69ebcb7922.png)

**Comment by thisisobate** [comment]
Okay.
Thanks for the clarification!

**Comment by thisisobate** [comment]
> think the only place that use it now is the server admin user list

@torkelo I Just discovered server admin user list doesn't have pagination either. 

https://user-images.githubusercontent.com/29557702/104387026-94531580-5536-11eb-9206-16185a068751.mov


I'm considering opening an issue right away but since we have many pages that require pagination, I think it's best to note down those pages before proceeding to create an issue that would handle adding pagination to all of them.

**Comment by torkelo** [comment]
the server admin page does have pagination

**Comment by thisisobate** [comment]
wow...interesting.
Maybe I didn't test pagination in the server admin page using the appropriate method - I replicated the `tr` section multiple times via the chrome debugger tool.

Any idea on what I could have done instead?

**Comment by torkelo** [comment]
@thisisobate the pagination is done in the React code that defines the view (html markup). If you update the browser html with the chrome dev tools that have no impact on the react code that takes the list of users and generates the HTML. 

To se what the page looks like with many users you need to create many users

**Comment by thisisobate** [comment]
Alright. Thanks for the explanation @torkelo 😀🙌
