### ISSUE TITLE
Logs Explore View Histogram Usability

### ISSUE THREAD

**Issue by keatontaylor** [grafana/grafana#29277]
**What would you like to be added**:
When using the histogram at the top of the explore view for Loki logs. It currently shows the logs automatically sorted for maximum time range for the logs retrieved by the query.

Example:
- Line limit set to 1000
- 1000 log lines received in the last 5 min

Even if I set the time range to 6hrs, the histogram will only show a 5 min window since I met the total line limit. 

It appears the the histogram is being populated from only the maximum line limit. Ideally, it would make more sense for the histogram to be populated similar to the count_over_time.

**Why is this needed**:
Similar to Kibana the histogram should be a view of your total logs over the time range, not the view for the maximum log lines received. This allows the end user to quickly identify a spike or decrease in log lines over the time interval (say if it was set to a full day) regardless if the line limit is exceeded.

**Comment by aocenas** [comment]
This is a duplicate (mostly) of https://github.com/grafana/grafana/issues/19949 where we track this issue. Added a bit more context for the issue here https://github.com/grafana/grafana/issues/19949#issuecomment-732046749
