### ISSUE TITLE
Missing label cause lable_value return empty

### ISSUE THREAD

**Issue by wenerme** [grafana/grafana#29271]
**What happened**:

Missing label cause lable_value return empty

![image](https://user-images.githubusercontent.com/1777211/99818323-0b98a880-2b89-11eb-8d6c-0ee6c903fa41.png)

label_names()
![image](https://user-images.githubusercontent.com/1777211/99818407-266b1d00-2b89-11eb-86d5-4a1fea629daf.png)

label_values() return empty

![image](https://user-images.githubusercontent.com/1777211/99818466-3c78dd80-2b89-11eb-8932-ca97bcfcc120.png)

I upgrade from 7.3.1 to 7.3.3, then downgrade to 7.3.2, 7.3.1, then restore to 7.3.3.
Before first upgrade, everything works, the backend is thanos query frontend.

**What you expected to happen**:

label_values return values

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.3
- Data source type & version: thanos query frontend
- OS Grafana is installed on: docker, alpinelinux 3.12 kernel 5.4
- User OS & Browser: chrome 87
- Grafana plugins: poly
- Others:

**Comment by aocenas** [comment]
I am not able to reproduce it not in 7.3.0 nor in 7.3.3. Not sure right now whether you have a problem with a specific version or you are saying that it stopped working because of the multiple downgrades upgrades? Can you specify which version it worked and in which version it stopped working?

Also did you try to get values for different metrics? Changing the dashboard time range? Trying the same thing with a Prometheus backend?

Can you let me know if any of that changed your results?

**Comment by wenerme** [comment]
@aocenas tried different time range, no luck. I think the problem is not related to backend, here is some result

exp| result
----|----
label_names|`__name__`,access_mode,action,addr,address,alertmanager,apiservice,branch,broadcast,bucket,buildDate,cache,call,cause,check,chip,chip_name,class,cluster,cluster_ip
label_values(job)|apiserver,http,ingress-nginx-controller-metrics,kube-prometheus-alertmanager,kube-prometheus-kube-state-metrics,kube-prometheus-operator,kube-prometheus-prometheus,kubelet,node-exporter,ping,printer,prometheus,synology<br/>__remove some__
label_values(up, job) | None
metrics(up)|alertmanager_dispatcher_aggregation_groups,go_memstats_lookups_total,kube_daemonset_updated_number_scheduled,kube_deployment_spec_strategy_rollingupdate_max_surge,kube_deployment_spec_strategy_rollingupdate_max_unavailable,kube_deployment_status_replicas_updated,kube_poddisruptionbudget_created,kube_poddisruptionbudget_status_current_healthy,kube_poddisruptionbudget_status_desired_healthy,kube_poddisruptionbudget_status_expected_pods,kube_poddisruptionbudget_status_observed_generation,kube_poddisruptionbudget_status_pod_disruptions_allowed,kube_statefulset_status_replicas_updated,kube_statefulset_status_update_revision,kubelet_cgroup_manager_duration_seconds_bucket,kubelet_cgroup_manager_duration_seconds_count,kubelet_cgroup_manager_duration_seconds_sum,nginx_ingress_controller_ingress_upstream_latency_seconds,nginx_ingress_controller_ingress_upstream_latency_seconds_count,nginx_ingress_controller_ingress_upstream_latency_seconds_sum<br/>__no__ up

But in explore, query `up` return correct values, contain `job` label.

Newer grafana seems limit the metric size,  maybe caused by this ?

**Comment by wenerme** [comment]
Downgrade thanos from 0.17.0 to 0.16.0, works now, I don't know why. what's behind `label_values(up, job)`
