### ISSUE TITLE
Add metric value to alertmanager labels

### ISSUE THREAD

**Issue by lucasRolff** [grafana/grafana#29274]
**What would you like to be added**:

I'd love to have the metric value available as a label, until we have more "rich text" support ( #5848 ).

e.g. if I have alert measuring requests per second and I say `if requests_per_second > 10000`, but the req/s is 15k, I'd like to know this value.

**Why is this needed**:

It allows us to use this as a part of the alerting template. In some cases we want to check if a value is greater than zero, and trigger an alarm based on this, however it's additionally useful to know if the value is 1 or 300 at the time of alerting.

**Additional info**:

Without having any experience in Golang, I managed to get the desired functionality in https://github.com/grafana/grafana/blob/master/pkg/services/alerting/notifiers/alertmanager.go by doing:

```diff
diff --git a/pkg/services/alerting/notifiers/alertmanager.go b/pkg/services/alerting/notifiers/alertmanager.go
index bc0b9ea6f2..7c05082c9a 100644
--- a/pkg/services/alerting/notifiers/alertmanager.go
+++ b/pkg/services/alerting/notifiers/alertmanager.go
@@ -5,6 +5,7 @@ import (
        "regexp"
        "strings"
        "time"
+       "fmt"

        "github.com/grafana/grafana/pkg/bus"
        "github.com/grafana/grafana/pkg/components/simplejson"
@@ -136,7 +137,9 @@ func (am *AlertmanagerNotifier) createAlert(evalContext *alerting.EvalContext, m
                                tags[replaceIllegalCharsInLabelname(k)] = v
                        }
                }
+               tags["value"] = fmt.Sprint(match.Value)
        }
+
        for _, tag := range evalContext.Rule.AlertRuleTags {
                tags[tag.Key] = tag.Value
        }
```

Now, I'm not sure whether "fmt" is optimal, and I don't know whether all data store backends would be compatible with using `fmt.Sprint` (from what I can see it handles conversions of floats and integers to strings at least, as well as string -> string).

I added the code prior to the `for _, tag := range evalContext.Rule.AlertRuleTags`, simply if people decide to override `value`, it should obviously be overwritten.

If anyone with some Golang experience (and Grafana experience), have any feedback, or would like to do a PR to get this fixed, I'd be super happy!

I know this feature could become obsolete again when rich text is available, but it looks like a bigger task.

**Comment by filippog** [comment]
I believe this feature request has value, and it got some reactions too from the community, any chance it can be picked up and/or commented?
