### ISSUE TITLE
Alerting: webhook GET method

### ISSUE THREAD

**Issue by tabinurie** [grafana/grafana#29289]
**What would you like to be added**:
GET method webhook as an alerting

**Why is this needed**:
I want to send alerts for services which only accepts GET method.

**Comment by marefr** [comment]
Please describe which these services are. In my head it doesn't make sense to use GET for Webhooks

**Comment by tabinurie** [comment]
Actually, it's not a 'service' but a 'device' like a rotary beacon light which behaves as a web server. The device will alert by sounds when it receives the specific HTTP GET command.

**Comment by tabinurie** [comment]
Actually, it's not a 'service' but an audio 'device' which behaves as a web server. The device will alert by sounds when it receives the specific HTTP GET command.

**Comment by marefr** [comment]
Sorry, but this is not something we want to support at the moment. I'm going to close this. Closing it doesn't mean it can be picked up later should there be a lot of activity/upvotes for it. I would recommend setting up a service that would proxy to your audio device service if you need that.
