### ISSUE TITLE
Streaming Data Source Across Multiple Entities

### ISSUE THREAD

**Issue by Simonl9l** [grafana/grafana#29284]
- Questions should be posted to: https://community.grafana.com --> I'd post another question but these are NEVER responded to.

**What happened**:
Trying to develop a streaming data source based on a Time Series across multiple entities. Have reviewed [this](https://grafana.com/docs/grafana/latest/developers/plugins/working-with-data-frames/#working-with-data-frames) and [this](https://grafana.com/docs/grafana/latest/developers/plugins/build-a-streaming-data-source-plugin/)

This documentation seem to only cover a single Entity/Row. 

Based in other work using the MySQL (memsql) data source, where the Format is set to Time Series, with Entity Name, and a gauge is displayed on the panel per Entity. I note in the Query Inspector, that if there are multiple entities in the SQL result set, that the data source creates a Data Frame for each entity.

I am currently creating a CircularDataFrame for each entity and with each data change, invoking a `subscription.next` for each data frame. However I only get a single gauge.

I also not in the Query Inspector Json Data Frame structure, the MySQL example shows the data frame for each entity in the Data viewer the ability to see a single frame or all merged by Time Series.

I have no clue how  embark on making the multiple data gauge scenario work, and the documentation here is beyond sparse.

Pointers to the mysql implementation appreciated or other guidance recommendations. 

**Environment**:
- Grafana version: 7.3
- Data source type & version: Self Developed
- OS Grafana is installed on: Linux/Alpine container
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
For streaming data I would suggest a single data frame with multiple fields for each entity.

if you have a dataframe for each entity you must push all entities in every update

**Comment by Simonl9l** [comment]
@torkelo Thanks for the replay - v quick to close mind...

...its also really grand to get responses but how is one supposed to figure all this out - more documentation would be most helpful ?

I'm not entireley following:

1. If each entity has multiple values those are the multiple fields?
1. So does one really need to have a different frame for each value, with fields for each entity, with the rows for each time in the series being the values of the field for each entity? 
1. New Entities may just "show up" in the source stream, do I just add another field when they do ?
1. Also if on this case I do have multiple frames (one for each filed), do I just `subscribe.next` for each one as I get data for each time in the series for it to appear or do I need to do more...how do I make Grafana aware of each frame for the Observable? 
1. How to I tell Grafana it's a time series not a table?

Thanks for any and all help to get a somewhat newbie going.

**Comment by torkelo** [comment]
Time series and tables are the same data structure , an entity can be another field in the same data frame (if they share the same time axis) as long as data share time points they can all exist in the same data frame.

What you pass to Subscriber next needs to contain all the data or if you send only some entities in each response set a unique key property for each and Grafana will merge all the packets

**Comment by Simonl9l** [comment]
Ah so the key on the `subscribe.next` "is the key" ! Where would I find this documented ? 

So if I did have a data frame per entity, I should use that EntityId as the key as you mention...not the query refId (as generically documented) or should is be a compound of query.refId and the EntityId? Such that of that Entity is used for other query for other frames etc it does not conflict?

**Comment by Simonl9l** [comment]
So based on the above, if I have a frame per entity, and key it by queryId-EntityId, Grafana does render the desired multiple gauges !

In the Query Inspector I see each frame...however I only see a single row of data, even after multiple updates, using a CircularDataFrame will 1000 entries, and if I select "Series Joined by Time" (than each series/frame), it does not seem to join them even though multiple entries have exactly the same time stamps?

**Comment by Simonl9l** [comment]
@torkelo thanks - I seem to have things working using frames a column store we a columnist per entity and Frame per attribute/query.

Curiously is there a way to detect that a query/observable is not longer is use, such that once can terminate any socket connections cleanly from upstream services? I don't find anything in the documentation.

**Comment by torkelo** [comment]
Yes, when you create your observable you can inside it return an unsubscribe function that Grafana will call when the stream is closed.

Google rxjs unsubscribe for more details

**Comment by Simonl9l** [comment]
@torkelo  - Thank for getting back to me. 

The learning cure is a tad overwhelming, I did however get it to work, and to help the community, here is my solution. It augments [this](https://grafana.com/docs/grafana/latest/developers/plugins/build-a-streaming-data-source-plugin/) from the limited documentation - and might be good to add this:
```js
query(options: DataQueryRequest<MyQuery>): Observable<DataQueryResponse> {
  const streams = options.targets.map(target => {
    const query = defaults(target, defaultQuery);

    return new Observable<DataQueryResponse>(subscriber => {
        subscriber.add(() => {
          this.unsubscribe(query, subscriber);
        });
...
      });
    });
  });

  return merge(...streams);
}

private unsubscribe(query: MyQuery, subscriber: Subscriber<DataQueryResponse>) {
...
  }
```

Also of help, if you have say, a dashboard the has two panels, each using this data source, and you refresh, this triggers a new `query` for the refresh, and as the new subscription is created for each `target` (panel), the prior subscription (for that `target`) receives it's unsubscribe callback.

This has the net effect of the subscription for the data source never going to zero. As those new subscription are created you'd need to update the requisite frames for any cached data in the data source, and `next` on the new subscriptions as per your specific datasource use case.

If you close the dashboard, you just get the requisite unsubscribes for each `target`/`subscription`, that then do go to zero and from that the data source can close the connections to clean up the back end!

I believe we can now close this issue!  Thanks for the continued assistance!
