### ISSUE TITLE
Gaps in graphs when different update times / averaging is used

### ISSUE THREAD

**Issue by DieterTHeck** [grafana/grafana#29286]
This graph is the outcome of one series with moving average 20 and one without.
When selecting for instance last 24 hours, the time selection should be done after processing, i.e. take a bit more data points in initially to create running averages and then cap to the selected time.

![Screenshot_2020-11-21 Grafana - Home Assistant](https://user-images.githubusercontent.com/58054042/99876188-6ec02480-2bf5-11eb-8ff4-8d3bb4fdeb93.png)

**Comment by torkelo** [comment]
Time selection is done before processing and is unaware of details of query logic
