### ISSUE TITLE
Docs feedback: /dashboards/json-model.md

### ISSUE THREAD

**Issue by catherineluse** [grafana/grafana#29282]
I think these steps are outdated.

I think that this step:

> Click on Manage dashboard menu on the top navigation bar

should be changed to:

> In the top navigation menu, go to the dashboard settings by clicking [gear icon].

Or something like that.

**Comment by oddlittlebird** [comment]
Ugh, yes. There are a lot of those buried in docs that the team hasn't gotten to. It's on our backlog to do a major overhaul and write some coherent topics about managing dashboards. If someone were to fix this and any others like it, that would make less work for us when we get there.
