### ISSUE TITLE
tsdb.HandleRequest() error Post "http://localhost:9090/api/v1/query_range": dial tcp [127.0.0.1:9090](http://127.0.0.1:9090/): connect: connection refused

### ISSUE THREAD

**Issue by nitin194** [grafana/grafana#29296]
**What happened**:
All of a sudden alerts started coming with below error note.

tsdb.HandleRequest() error Post "http://localhost:9090/api/v1/query_range": dial tcp [127.0.0.1:9090](http://127.0.0.1:9090/): connect: connection refused

**What you expected to happen**:
This error shouldn't come

**How to reproduce it (as minimally and precisely as possible)**:
It is recurring with random alerts not all of them.

**Anything else we need to know?**:
We checked that Prometheus is running properly on 9090 port and is able to fetch the metrics from other servers as well. But this alert is coming intermittently and sometimes clears also.

We also checked grafana logs and found this snippet but doesn’t seem relevant to this particular error

t=2020-11-23T08:48:30+0800 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/dBA3kjnZo/nykaa-eretailweb-tg-tg?orgId=1&panelId=15"
t=2020-11-23T08:48:30+0800 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="http://localhost:3000/d-solo/dBA3kjnZo/nykaa-eretailweb-tg-tg?orgId=1&panelId=15&render=1" error="Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"
t=2020-11-23T08:48:30+0800 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=129 error="Rendering failed: Error: Failed to launch chrome!\n/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome: error while loading shared libraries: libXcomposite.so.1: cannot open shared object file: No such file or directory\n\n\nTROUBLESHOOTING: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md\n"

**Environment**:
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: prometheus2-2.20.1-2.el7
- OS Grafana is installed on: cpe:2.3:o:amazon:amazon_linux:2
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: grafana-image-renderer @ 2.0.0, grafana-piechart-panel @ 1.6.0, snuids-trafficlights-panel @ 1.4.5
- Others: [Error-Image](https://imgur.com/HVOV0cp)

**Comment by nitin194** [comment]
I even tried to update the both the versions to below but no fate. Please help.

Grafana  to v7.3.3
Prometheus2 to v2.22.2-1.el7

**Comment by torkelo** [comment]
Seems like a network/connection issue reaching Prometheus from Grafana. Not sure what we can troubleshoot more from here. Do you have any network monitoring in place between these services that can also monitor connectivity issues? 

The log error seems unrelated but still a problem that could be good to fix, the image renderer plugin is trying to capture an image but fails to start chrome due to missing libraries.

**Comment by aknuds1** [comment]
Was going to write basically the same thing as @torkelo, that most likely the problem isn't in Grafana, but in the environment it runs, so it can't connect to Prometheus.

**Comment by aknuds1** [comment]
For support running Grafana I'd recommend using our community [forums](https://community.grafana.com) or [Slack](http://raintank.io), since we use GitHub issues for bug reports and feature requests.

**Comment by nitin194** [comment]
Hey, @torkelo and @aknuds1 thank you for your suggestions. Prometheus runs on port 9090 but it isn't like this error is coming on all the alerts but on some random alerts. We have also asked for support on [forums](https://community.grafana.com/t/grafana-and-prometheus-issue/39610/2)  as well. Waiting for someone to pick this up. Very strange issue because it was working very well till yesterday and it is also working fine on other accounts.

**Comment by nitin194** [comment]
Never Mind ... It is resolved by replacing Data Source Prometheus URL in Grafana UI from http://localhost:9090 to http://<server-ip>:9090

**Comment by DICKSON78** [comment]
I have the same situation

**Comment by ArxXx** [comment]
> I have the same situation

Since I need it for a basic test exercise, changing "Access" from "default/server" to Browser works

**Comment by wentzel** [comment]
Same problem for me. I am running Grafana and Prometheus with Docker Compose. I guess that could have to do with it (I'm a beginner with all of these things so I don't really know what I'm doing 😃 ). I solved it by replacing "localhost" with the IP adress of the machine that is running all of them.

**Comment by brunopenha** [comment]
> Same problem for me. I am running Grafana and Prometheus with Docker Compose. I guess that could have to do with it (I'm a beginner with all of these things so I don't really know what I'm doing 😃 ). I solved it by replacing "localhost" with the IP adress of the machine that is running all of them.

This one works for me - thanks : )

**Comment by arvindsis11** [comment]
> Same problem for me. I am running Grafana and Prometheus with Docker Compose. I guess that could have to do with it (I'm a beginner with all of these things so I don't really know what I'm doing 😃 ). I solved it by replacing "localhost" with the IP adress of the machine that is running all of them.

this is working ...thanks

**Comment by Banzaika** [comment]
I solved it by replacing "localhost" with the container name of prometheus that is running all of them.

**Comment by stuffedleaves** [comment]
Hi, I have the same problem. I tried replacing URL in Grafana UI from http://localhost:9090/ to http://server-ip:9090/ , but now I get the same error with the server ip. Please help.

**Comment by kilonzi** [comment]
if both Grafana and Prometheus are running on same Kubernetes cluster, then 
run
`kubectl get services`
Look for the service that exposes Cluster IP and Port: 9090/TCP,8080/TCP, get the name -- mine is 
`prometheus-kube-prometheus-prometheus`
then the URL is 
`http://prometheus-kube-prometheus-prometheus:9090`

**Comment by ZadokUr** [comment]
> I solved it by replacing "localhost" with the container name of prometheus that is running all of them.

This worked for me. Replaced changed `http://localhost:9090` to `http://prometheus:9090`

**Comment by abrahimcse** [comment]
I encountered an issue where Prometheus API requests were being refused. The problem was resolved by replacing localhost with the actual server IP where Prometheus is installed. 
http://localhost:9090/ 
http://server-ip:9090/ (where Prometheus installed)

**Comment by Diogoribeirott** [comment]
conseguir inserindo o nome do container tbm, muito obrigado galera <3 
Substituído alterado http://localhost:9090parahttp://[PROMETHEUS_CONTAINER_NAME]:9090
no meu caso foi http://prometheus:9090 e funcionou  segue o codigo do prometheus e grafana  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - "./src/main/resources/prometheus.yml:/etc/prometheus/prometheus.yml"
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      -  "3000:3000"
    
      
volumes:
  pgdata:
