### ISSUE TITLE
partial file errors on static assets

### ISSUE THREAD

**Issue by donpdonp** [grafana/grafana#2929]
my nginx proxy was passing all urls to the python app at :3000.

/app/app.bd986dd5.js was failing the transfer because the HTTP response was only a partial file. a random percentage of the file gets delivered.

```
$ curl  http://commons/app/app.bd986dd5.js 
curl: (18) transfer closed with 804363 bytes remaining to read

$ curl  http://commons/app/app.bd986dd5.js 
curl: (18) transfer closed with 236427 bytes remaining to read

```
by having  nginx serve the static files directly, i could work around the problem.

**Comment by torkelo** [comment]
python app? What version of Grafana are you using?

**Comment by donpdonp** [comment]
its the stock install of grafana on ubuntu.

```
$ dpkg -l grafana
ii  grafana                  2.1.3             amd64             Grafana
```

**Comment by torkelo** [comment]
you should try a reinstall or something, thousands are running 2.1.3 without any issues with partial files. Maybe a bug in the nginx version you have that is causing issues with the nginx reverse proxy?
