### ISSUE TITLE
Typescript: Use const enums where possible

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#29293]
**What would you like to be added**:

switch from using `enum` to `const enum` where possible:

https://www.typescriptlang.org/docs/handbook/enums.html#const-enums

**Why is this needed**:

there are currently 74 TypeScript `enum`s in the Grafana codebase:

https://github.com/grafana/grafana/search?q=%22export+enum%22

each of these generates a JavaScript backing object that is then used to reference into. in the overwhelming majority of cases (where enums are static and do not need to be iterated), this is unecessary perf and byte overhead. the simple fix is to switch to using `const enum`, which compiles down to the final value. you can see the difference in the generated output by removing `const` from this demo:

https://www.typescriptlang.org/play?ts=4.0.5#code/KYDwDg9gTgLgBAYwgOwM72MgrgWzgMQgjgG8AoOSuADTgF44BWAGgqoE164A2VquAFpcA7KwC+ZMgBtg8EF0IQAdNQDcQA

**Comment by torkelo** [comment]
Should be possible for most enums, for some we do iterate over the keys

**Comment by leeoniya** [comment]
babel blocker: https://github.com/babel/babel/issues/8741

**Comment by leeoniya** [comment]
possible unblocker: https://github.com/dosentmatter/babel-plugin-const-enum
