### ISSUE TITLE
Staircase shows additional horizontal line from last point to random point in the beginning

### ISSUE THREAD

**Issue by AronVa** [grafana/grafana#29298]
**What happened**: When plotting a staircase (visualization: graph, display: not staircase, series override: staircase line TRUE) Grafana plots an additional line from the last datapoint to a random, first datapoint, going through the whole of my graph.

**What you expected to happen**: Just a staircase, without the additional horizontal line.

**How to reproduce it (as minimally and precisely as possible)**: Plot a staircase.

**Anything else we need to know?**: Besides the staircase, 2 additional series were plotted on the graph, just points, no lines in between.

**Environment**:
- Grafana version: Grafana v7.1.5 (9893b8c53d)
- Data source type & version: InfluxDB Version (f02f110)
- OS Grafana is installed on: Do not know
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: None
- Others:

![image](https://user-images.githubusercontent.com/74901230/99945675-50813280-2d75-11eb-8709-459c679f58c4.png)

![image](https://user-images.githubusercontent.com/74901230/99945733-73134b80-2d75-11eb-80d8-192958837c5a.png)

**Comment by torkelo** [comment]
Hard to see on the screenshot, can you isolate the problem more? With only one series? which series has staircase? when does it appear? is the points the series you also have staircase on for? I cannot see. 

Please investigate as much as possible when this triggers and what the data is that will trigger it

**Comment by AronVa** [comment]
Hi Torkelo
Thanks for the swift reply.

This happens for both series which are on a 15 min basis and have staircase override TRUE, they are named "imbalance_price_down" and "imbalance price_up" in data zoom-in, they are named  "Realized Down Price" and "Realized Up Price" in Graph legend.

It only appears when the two other series (light red and green points in graph, 1 min basis, lots of null values) are queried as well. When I delete the queries for the two other series from the graph, the problem doesn't occur anymore.

**Comment by torkelo** [comment]
try changing null value mode to null as zero or connected. 

Null values and series with different periods can mess with staircase mode. 

We are working on a new graph panel / component so closing this as it feels like an edge case we can live with until the new panel comes (soon in v7.4)

**Comment by AronVa** [comment]
Updated to null value connected and the problem is solved, thanks a lot!
