### ISSUE TITLE
LDAP Login works not for all Users

### ISSUE THREAD

**Issue by bjoernhoeferacp** [grafana/grafana#29307]
What happened?
I have configured a grafana container in Azure (Container Instance) to use my Companies LDAP Server. Login for a few users work. But most users are not able to login.
The Users that work: The Grafana Admins (via LDAP)
The Users that do not work: All other Roles

What was expected to happen?
All Users should be able to login

Steps to reproduce the problem:
1. Deploy Grafana and configure it accordingly
2. Login

Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):
grafana 6.7.3

Configuration information:
ldap.toml:
[[servers]]
host = "10.150.72.xx 10.150.72.yy"
port = 636
use_ssl = true
start_tls = false
ssl_skip_verify = true
root_ca_cert = "/etc/grafana/AG_SubCA_Bundle.pem"
bind_dn = "CN=xyz,OU=5_Service Accounts,OU=Benutzer,OU=Admin,DC=sbg,DC=xy-ag,DC=at"
bind_password = "nononon"
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["DC=sbg,DC=xy-ag,DC=at"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "sAMAccountName"
member_of = "memberOf"
email = "mail"
[[servers.group_mappings]]
group_dn = "CN=PRG_MON_CoreServices_ADMIN,OU=Monitoring,OU=Azure,OU=Benutzergruppen,OU=Admin,DC=sbg,DC=xy-ag,DC=at"
org_role = "Admin"
grafana_admin = true
[[servers.group_mappings]]
group_dn = "CN=PRG_MON_CoreServices_EDIT,OU=Monitoring,OU=Azure,OU=Benutzergruppen,OU=Admin,DC=sbg,DC=xy-ag,DC=at"
org_role = "Editor"
[[servers.group_mappings]]
group_dn = "CN=PRG_MON_CoreServices_VIEW,OU=Monitoring,OU=Azure,OU=Benutzergruppen,OU=Admin,DC=sbg,DC=xy-ag,DC=at"
org_role = "Viewer"

----- end ldap.toml ------

---- start grafana.ini ---- 

All default excpet:
[auth.ldap]
enabled = true
config_file = /var/lib/grafana/ldap.toml
allow_sign_up = true

[log]
mode = console file
level = debug
filters = ldap:debug

---- end grafana.ini -----

---- error message ----
t=2020-11-23T14:21:00+0000 lvl=dbug msg="LDAP users found" logger=ldap users="([]*models.ExternalUserInfo) (len=1 cap=1) {\n (*models.ExternalUserInfo)(0xc000d4a5a0)({\n  OAuthToken: (*oauth2.Token)(<nil>),\n  AuthModule: (string) (len=4) \"ldap\",\n  AuthId: (string) (len=99) \"CN=Höfer Björn,OU=1_Standardbenutzer xx AG,OU=Benutzer,OU=Admin,DC=xxx,DC=xy-ag,DC=at\",\n  UserId: (int64) 0,\n  Email: (string) (len=20) \"BJOERN.HOEFER@ACP.AT\",\n  Login: (string) (len=5) \"61512\",\n  Name: (string) (len=13) \"Björn Höfer\",\n  Groups: ([]string) {\n  },\n  OrgRoles: (map[int64]models.RoleType) {\n  },\n  IsGrafanaAdmin: (*bool)(<nil>),\n  IsDisabled: (bool) false\n })\n}\n"
t=2020-11-23T14:21:00+0000 lvl=eror msg="User does not belong in any of the specified LDAP groups" logger=ldap username=12345 groups=[]
t=2020-11-23T14:21:00+0000 lvl=dbug msg="unable to login with LDAP - skipping server" logger=ldap host="10.150.72.yz 10.150.72.xy" port=636 error="Invalid Username or Password"
t=2020-11-23T14:21:00+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password" remote_addr=x.20.48.y
t=2020-11-23T14:21:00+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=x.20.48.y time_ms=141 size=42 referer=http://10.154.15.xy:3000/login

**Comment by aocenas** [comment]
@aknuds1 is this something for backend squad?

**Comment by bjoernhoeferacp** [comment]
Any news cause my customer is getting a bit stressed... PM is also having a hard time cause this problem seems to be a little "milestone-problem"... 
Sorry, I know that these is no premium-area support case - but maybe you can give us a short heads up or something we can maybe try to change to help you identifying the problem.

Thanks a lot, 

Björn

PS: Love your product 💯

**Comment by aknuds1** [comment]
I wonder if the enterprise team, f.ex. @alexanderzobnin can help out with this, since they seem to have the most LDAP experience.

**Comment by bjoernhoeferacp** [comment]
Any help is warmly welcome :-)

**Comment by woodsaj** [comment]
The logs state that the user is not found in any of the groups used in the group_mappings
```
User does not belong in any of the specified LDAP groups
```

From the docs, https://grafana.com/docs/grafana/latest/auth/ldap/#nestedrecursive-group-membership

> For troubleshooting, by changing member_of in [servers.attributes] to “dn” it will show you more accurate group memberships when debug is enabled.

**Comment by bjoernhoeferacp** [comment]
Hi, so far my user or the group is not nested or anything.

As we get the Groups from ActiveDirectory - is the example below applicable?

Interesting fact: 
If a admin user logs in (where the group-membership works) - you see all groups to whom he/she belongs.
If my user logs in (I should be in the Editors Group) you see no group at all.

As proposed - I've changed the setting in [servers.attributes].

Please find the debug below:
`t=2020-11-30T10:06:55+0000 lvl=dbug msg="LDAP users found" logger=ldap users="([]*models.ExternalUserInfo) (len=1 cap=1) {\n (*models.ExternalUserInfo)(0xc00055cbd0)({\n  OAuthToken: (*oauth2.Token)(<nil>),\n  AuthModule: (string) (len=4) \"ldap\",\n  AuthId: (string) (len=99) \"CN=Höfer Björn,OU=1_Standardbenutzer Company,OU=Benutzer,OU=Admin,DC=sbg,DC=company,DC=at\",\n  UserId: (int64) 0,\n  Email: (string) (len=20) \"BJOERN.HOEFER@ACP.AT\",\n  Login: (string) (len=99) \"CN=Höfer Björn,OU=1_Standardbenutzer Company,OU=Benutzer,OU=Admin,DC=sbg,DC=company,DC=at\",\n  Name: (string) (len=13) \"Björn Höfer\",\n  Groups: ([]string) {\n  },\n  OrgRoles: (map[int64]models.RoleType) {\n  },\n  IsGrafanaAdmin: (*bool)(<nil>),\n  IsDisabled: (bool) false\n })\n}\n"
t=2020-11-30T10:06:55+0000 lvl=eror msg="User does not belong in any of the specified LDAP groups" logger=ldap username="CN=Höfer Björn,OU=1_Standardbenutzer Company,OU=Benutzer,OU=Admin,DC=sbg,DC=company,DC=at" groups=[]
t=2020-11-30T10:06:55+0000 lvl=dbug msg="unable to login with LDAP - skipping server" logger=ldap host="10.150.72.xy 10.150.72.zz" port=636 error="Invalid Username or Password"
t=2020-11-30T10:06:55+0000 lvl=eror msg="Invalid username or password" logger=context userId=0 orgId=0 uname= error="Invalid Username or Password" remote_addr=172.20.48.xx
t=2020-11-30T10:06:55+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=POST path=/login status=401 remote_addr=172.20.48.xx time_ms=204 size=42 referer=http://10.154.15.xy:3000/login`

**Comment by alexanderzobnin** [comment]
@bjoernhoeferacp Since you configured `bind_password`, admin bind is using first to get user information. If authentication with provided `bind_dn` and `bind_password` failed, then Grafana uses login and password provided by user to get that info. Can you confirm that account you set up in `[[servers]]` section is valid and can get access to the required users and groups?
```
bind_dn = "CN=xyz,OU=5_Service Accounts,OU=Benutzer,OU=Admin,DC=sbg,DC=xy-ag,DC=at"
bind_password = "nononon"
```

So as @woodsaj mentioned, the main problem is that user info fetched from LDAP server does not contain any groups. So I guess it's related to the access rights somehow.

**Comment by bjoernhoeferacp** [comment]
Hi, that hint lead to the knowledge that the User we try to query the LDAP was somehow limited.

We've finally got an service user who can access the LDAP unrestricted - and now everything works.

Thanks so far.
