### ISSUE TITLE
CloudWatch: Basic metric math returning 400

### ISSUE THREAD

**Issue by chrs-myrs** [grafana/grafana#29300]
**What happened**:
This series is not recognised in metric math expressions, it's hard to see why.
![image](https://user-images.githubusercontent.com/2414664/99953284-fa15f300-2d78-11eb-83cc-0092b6ac3ee5.png)

**What you expected to happen**:
For query D to mirror query C, as it does with other metrics

**How to reproduce it (as minimally and precisely as possible)**:
* Add a valid series on CloudFront requests, with the dimensions set
* Add a math expression repeating the series

**Anything else we need to know?**:
Here is the query inspector
```{
  "request": {
    "method": "POST",
    "url": "api/tsdb/query",
    "data": {
      "from": "1598348873304",
      "to": "1606128473304",
      "queries": [
        {
          "intervalMs": 7200000,
          "maxDataPoints": 1275,
          "datasourceId": 12,
          "type": "timeSeriesQuery",
          "namespace": "AWS/CloudFront",
          "metricName": "Requests",
          "expression": "",
          "dimensions": {
            "DistributionId": [
              "<<redacted>>"
            ],
            "Region": [
              "Global"
            ]
          },
          "region": "us-east-1",
          "id": "cf_requests",
          "alias": "",
          "statistics": [
            "Sum"
          ],
          "period": "86400",
          "refId": "C",
          "matchExact": true,
          "hide": false,
          "datasource": "Prod"
        },
        {
          "intervalMs": 7200000,
          "maxDataPoints": 1275,
          "datasourceId": 12,
          "type": "timeSeriesQuery",
          "namespace": "",
          "metricName": "",
          "expression": "cf_requests",
          "dimensions": {},
          "region": "eu-west-1",
          "id": "",
          "alias": "test",
          "statistics": [
            "Average"
          ],
          "period": "86400",
          "refId": "D",
          "matchExact": true,
          "hide": false,
          "datasource": "Prod"
        }
      ]
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "C": {
        "refId": "C",
        "meta": {
          "gmdMeta": [
            {
              "Expression": "",
              "ID": "cf_requests",
              "Period": 86400
            }
          ]
        },
        "series": [],
        "tables": null,
        "dataframes": [
          "<<redacted>>"
        ]
      },
      "D": {
        "error": "ValidationError: Error in expression 'queryD': ID 'cf_requests' not found\n\tstatus code: 400, request id: 3965d794-031d-465e-93f7-327810450d91",
        "refId": "D",
        "series": null,
        "tables": null,
        "dataframes": null
      }
    },
    "message": "ValidationError: Error in expression 'queryD': ID 'cf_requests' not found\n\tstatus code: 400, request id: 3965d794-031d-465e-93f7-327810450d91"
  }
}```

**Environment**:
Grafana version: 7.3.3
Data source type & version: Cloudwatch
OS Grafana is installed on: CentOs
User OS & Browser: Ubuntu & FireFox
Grafana plugins: All standard + PagerDuty
Others:

**Comment by aocenas** [comment]
@papagian or @aknuds1 do you know if this kind of referencing between queries should be supported or not?

**Comment by aknuds1** [comment]
@aocenas I don't know anything about this sorry. From what I hear @sunker will be back to work on CloudWatch next week though, and it's not our team's responsibility any longer.

**Comment by chrs-myrs** [comment]
It's the same with many different queries, I just tried to simplify it as much as possible to isolate the error.  Apologies for not making that clear above

**Comment by sunker** [comment]
@chrs-myrs, that error - "ValidationError: Error in expression [...]" comes from the CloudWatch api, not Grafana. Could you please try to run the two queries in the CloudWatch console and see if you get the same error there? Make sure all parameters are the same as they were in Grafana. That would be very helpful, thanks.

**Comment by chrs-myrs** [comment]
Sorry I can't recreate this now I try again, will close the issue, perhaps a temporary cloudwatch issue, or perhaps as the screenshot above shows the metric math query is in the default region which is different to us-east-1

**Comment by patzluke** [comment]
experiencing a same error. Please someone??

![image](https://user-images.githubusercontent.com/73647804/162357231-925d904c-c415-4c58-911e-44e10640a1e0.png)

**Comment by patzluke** [comment]
Experiencin the same issue. please anyone help

![image](https://user-images.githubusercontent.com/73647804/162357340-cd0485b0-78fa-4ec6-bd12-3a14f009de40.png)

**Comment by sunker** [comment]
> Experiencin the same issue. please anyone help
> 
> ![image](https://user-images.githubusercontent.com/73647804/162357340-cd0485b0-78fa-4ec6-bd12-3a14f009de40.png)

@patzluke what Grafana version are you on?

**Comment by patzluke** [comment]
> 

the latest version 8.4 based on grafana values.yaml helm installation

**Comment by sunker** [comment]
Okay. Can you please report a new issue for this @patzluke?

**Comment by patzluke** [comment]
Ok will do.
