### ISSUE TITLE
Show dashboards in datasource that who is using this datasource

### ISSUE THREAD

**Issue by yxyx520** [grafana/grafana#29318]
**What would you like to be added**:
Show dashboards in datasource that who is using this datasource.
**Why is this needed**:
Sometime we will try to clear datasource which is abandon, but we do not know which dashboard is still using this datasource, so sometime we will delete a using datasource by mistake.

**Comment by zoltanbedi** [comment]
This is an enterprise feature. https://grafana.com/docs/grafana/latest/enterprise/usage-insights/#data-source-insights
