### ISSUE TITLE
Can not filter annotation for each graph

### ISSUE THREAD

**Issue by vinhlh** [grafana/grafana#2931]
In Graphite, we can use `drawAsInfinite(stats.vnfas.deploy.count)` to draw a deploy line on per graph.
We have many ventures, so we need to draw per deploy line for per graph.

In Grafana, it seems Annotation is our solution to draw deploy lines. But there are option to filter per deploy line for per graph.

**Comment by torkelo** [comment]
yea, would be great! 

Will close as there is already an issue for this. https://github.com/grafana/grafana/issues/717
