### ISSUE TITLE
Support customizable explore start page

### ISSUE THREAD

**Issue by alanhe** [grafana/grafana#29321]
**What would you like to be added**:
I want to customize the explore start page to show some information like our TTL settings per Loki cluster, and to whom our users can turn to when they have difficulty writing LogQL. But this cannot be done without re-compiling Grafana because the messages are hard-coded in the TS files:

https://github.com/grafana/grafana/blob/cfaca42e973fa86efb62f10ed01586fbd582953a/public/app/plugins/datasource/loki/module.ts#L14

I'm worried my modifications will make it hard to upgrade Grafana in the future.

I would like Grafana to support loading Markdown files by configurations and render them as HTML fragments, so that I can replace the "Loki Cheat Sheet" area with information more close related to our users.

Thanks.

**Why is this needed**:

**Comment by davkal** [comment]
Could be interesting for Grafana 8.

**Comment by gelicia** [comment]
What is being asked here sounds like something that would be better accomplished in a dashboard, and have that be what can be referenced for users wanting more information. We do not intend to work on this, but if you have more information to add on how this could help you, please create a [discussion](https://github.com/grafana/grafana/discussions) to help our team understand and prioritize what we can do to help. Thank you!
