### ISSUE TITLE
Documentation on customized panels

### ISSUE THREAD

**Issue by twollmann** [grafana/grafana#2932]
First of all I have to thank you for this awesome piece of software. I really like the look of the user interface and think that grafana is the perfect solution for modern dashboards.

We are currently implementing a management dashboard based on our ganglia monitoring solution. Since ganglia has built in support for graphite time series database it seemed obvious to use grafana for a fancy dashboard. However there is demand to include a geo map in the dashboard which brings us to the limitations of grafana.

I've been searching for almost a whole day to figure out how to develope custom panels for the dashboard without any success. It'd be awesome if you could add some documentation about the plugin/panel interface.

**Comment by torkelo** [comment]
I think I will close this, and make it part of this, https://github.com/grafana/grafana/issues/2572
