### ISSUE TITLE
elasticsearch  datasource has the problem with time zone

### ISSUE THREAD

**Issue by WebbingXu** [grafana/grafana#29320]
I intend to aggregate data from elasticsearch, and the elasticsearch index pattern is like "log-20201124.10", the 10 means time. I have already set grafana timezone to browser timezone(UTC+0800)，however grafana will   minus 8, so the index becomes "log-20201124.02", it's not my intention.
Is there any settings to change this behavior or it's a bug?

**Comment by aocenas** [comment]
Closing this as there is a duplicate feature request for this https://github.com/grafana/grafana/issues/29409
