### ISSUE TITLE
Map custom template names and values to display and used value

### ISSUE THREAD

**Issue by eliperelman** [grafana/grafana#2933]
Attempting to create a `custom` templating for a scripted dashboard, but running into some usability issues:

```js
var bound95 = {
  "text": "95% Bound",
  "value": "MEAN(value) + (1.96 * STDDEV(value) / 5.477)",
  "selected": true
};

return {
  "allFormat": "glob",
  "current": bound95,
  "datasource": null,
  "includeAll": false,
  "label": "Aggregate",
  "multi": false,
  "multiFormat": "regex values",
  "name": "aggregate",
  "options": [
    bound95,
    {
      "text": "Mean",
      "value": "MEAN(value) as value",
      "selected": false
    }
  ],
  "query": "",
  "refresh": true,
  "refresh_on_load": true,
  "type": "custom"
}
```

The point of this is so users can easily swap the aggregation method of the InfluxDB data I am displaying:

`SELECT $annotation from measure WHERE ...`

The Grafana UI only seems to display whatever value is present in the `query` property, completely ignoring the options passed in `options`. Attempting to set `query` to comma-separated `name`s works, but is ugly as you see the whole aggregation rather than the name. Using the UI to create the templated variable and looking at the JSON seems to set the `text` and `value` properties to the same value:

![aggregate](https://cldup.com/q7MVvDxvEc-3000x3000.png)

Am I missing something, or is there no way to currently use the custom template option to create these variable which have a different display value than their consumed value?

**Comment by torkelo** [comment]
set refresh to false, if it is true it will look at the query and update options when you load the dasbboard, but if it is false it should not update the options unless you go into template edit view.

**Comment by eliperelman** [comment]
@torkelo perfect!
