### ISSUE TITLE
Row height should show currently selected height

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2934]
In Grafana, you can set the height of a row.

However, there is no way to tell what the currently selected height is:

![screenshot 2015-10-13 09 49 46](https://cloud.githubusercontent.com/assets/243499/10440990/c36916f2-718f-11e5-92a9-cf593222ace2.png)

It would be nice if there a simple indicator that told you what the currently selected height is.

**Comment by mattttt** [comment]
:+1:

**Comment by thuck** [comment]
@torkelo Considering the way grafana displays the size now this should be closed, no?
