### ISSUE TITLE
Explore: Prometheus table labels values shown are wrong

### ISSUE THREAD

**Issue by mjtrangoni** [grafana/grafana#29342]
**What happened**:
Running a PromQL query on prometheus 
```bash
  prometheus, version 2.21.0 (branch: release-2.21, revision: 184a871638fcf87a1cf1ba1425907bff40930a44)
  build user:       root@runner-oDDrudUt-project-136-concurrent-0
  build date:       20201002-10:55:04
  go version:       go1.15.2
```
like this,
```sql
avg_over_time(metric_name{instance="XX.XX.XX.XX",keyspace="YYYYY",table="ZZZZZ"}[7d])
```
return this

| Element	| Value |
| --------- | ------ |
| {cluster="clustername",dc="YYY",dse="XXXX",insight_filtered="true",instance="XX.XX.XX.XX",job="dse",keyspace="YYYYY",rack="XXXXX",table="ZZZZZ"} | 8.69692517577919 |
| {cluster="clustername",dc="YYY",dse="XXXX",instance="XX.XX.XX.XX",job="dse",keyspace="YYYYY",rack="XXXXX",table="ZZZZZ"} | 	9 |

The only one difference is the label **insight_filtered="true"**.

Now running the same query on Grafana explore shows,

![image](https://user-images.githubusercontent.com/261502/100104180-23f91380-2e66-11eb-8726-0fa8967d559b.png)

If you see, **insight_filtered="true"** is shown on both metrics, which is wrong.

**What you expected to happen**:

*insight_filtered*  should be shown as "" where no label is set.

**How to reproduce it (as minimally and precisely as possible)**:

Various prometheus metrics with and without a boolean value, and run that PromQL query. 

**Anything else we need to know?**:

Let me know if I should share something else.

**Environment**:
- Grafana version: Grafana v7.3.3 (2489dc4d3a)
- Data source type & version: Prometheus
- OS Grafana is installed on: CentOS Linux release 8.2.2004 (Core)
- User OS & Browser: Windows 10 & Google Chrome 87.0.4280.66 (Official Build) (64-bit)
- Grafana plugins: none
- Others: none

**Comment by ivanahuckova** [comment]
Fixed in #30831
