### ISSUE TITLE
Loki: Loki Explore live tail view crashes after some time

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#29348]
**What happened**:

While piping live view of a quite active log stream through a filter, such as `|= "MARK"`  or `|= "foo count"`, after between 5 and 10 mins the live view will crash with the following. 

error: 
An unexpected error happened
TypeError: r is null

    in t
    in WithTheme(undefined)
    in s
    in div
    in div
    in Collapse
    in t
    in t
    in h
    in t
    in x
    in t
    in t
    in main
    in div
    in t
    in div
    in div
    in t
    in WithTheme(undefined)
    in x
    in t
    in t
    in div
    in div
    in div
    in t
    in t
    in div
    in t
    in x
    in r
    in Unknown
    in t
    in Unknown
    in h
    in Unknown
    in Unknown
    in t
    in t
    in l

**What you expected to happen**:
Not to crash :-) 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.3 
- Data source type & version: Loki from hosted logs. 
- OS Grafana is installed on: hosted
- User OS & Browser: firefox and chorme. 
- Grafana plugins: n/a
- Others:
![image](https://user-images.githubusercontent.com/8004654/100125121-514cbe00-2e74-11eb-8179-e95378a6364d.png)

**Comment by ivanahuckova** [comment]
@simonc6372 in Grafana, we are going to improve experience when connection is abnormally closed, but the main issue remains (but is documented) on [hosted loki side](https://github.com/grafana/deployment_tools/issues/6223).
