### ISSUE TITLE
Ability to export a dashboard (not just individual graphs)

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2935]
It would be cool if there was a way to export an entire dashboard (i.e. all the graphs together) as a PNG.

Currently, you are only able to export individual graphs one by one.

**Comment by torkelo** [comment]
dupe of https://github.com/grafana/grafana/issues/2085 :)

**Comment by victorhooi** [comment]
Aha, whoops - that'll teach me for not making my search terms more specific...lol.

Sorry - I used "dashboard export" and skimmed the list quickly. Thanks!
