### ISSUE TITLE
Docs: Fix step-by-step heading format

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#29355]
**What would you like to be added**: 

Currently, some headings are also steps in procedures. The format is not consistent. We need the heading format made consistent per the [Grafana documentation style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md#headings).

This means both the step number format (Step 1., Step 2.) and that everything should be sentence case, not title case.

**Correct**

Step 1. Install the software
Step 2. Run the software

**Incorrect**

Step 1: Install the software
Step 1 - Install the software
Step 1-Install the software
Step 1
1. Install the software

**Note:** The last incorrect example above applies only to headings. It is correct in the context of ordered lists or other non-heading uses.

**Why is this needed**: To make the documentation consistent and professional.

**Comment by aleemosman** [comment]
I'd love to try this. Can you assign this to me @oddlittlebird 

You want the headings format t be fixed according to grafana style guide. 

https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md#headings

Which file needs to be fixed? Is it a particular file that needs correction? Pls share.

**Comment by oddlittlebird** [comment]
Any and all files in the doc folder that have step-by-step headings.

**Comment by aleemosman** [comment]
Got it, I'll work on this and send pull requests.

**Comment by aleemosman** [comment]
I have a couple of questions. There are  words like "Graphite, User, Password etc." . Should I change it to sentence case? 

Second doubt is instructions also have steps after the heading, I have changed that from 
1-
1-
1-
to
Step 1.
Step 2. etc. Is this the right format or do you want instructions to be as is? These changes were made in the recent PR I made.

**Comment by oddlittlebird** [comment]
Heading guidance is in the [Grafana documentation style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-style-guide.md#headings).

Headings should be title case. Proper nouns, such as Graphite or Grafana, stay capitalized. If the text is directly referencing text in the UI, then match UI capitalization.

Ordered list guidance is in the [Grafana markdown style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/documentation-markdown-guide.md#numbered-lists). The repetitive numbering is preferred; do not change it. (Unless it has a hyphen, then change it to correct markdown with a period.)

**Comment by oddlittlebird** [comment]
Closed by #29670
