### ISSUE TITLE
 root_url  is not working with docker mode

### ISSUE THREAD

**Issue by thirdcountry** [grafana/grafana#29370]
**What happened**:
I set `domain=xxx.com` , and enabled   `root_url` with default  in `grafana.ini`
and then restarted grafana 
but the setting page still show wrong configurtion with root_url  like '10.1.1.6:3000'

**What you expected to happen**:

the root_url should like this: http://xxx.com:3333

**How to reproduce it (as minimally and precisely as possible)**:

1. run grafana with docker  `docker run -d -p 3000:3000 -v  grafana.ini:/etc/grafana/grafana.ini grafana `
1. view configurtion on settting page

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana:latest  with docker
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:  CentOS Linux release 7.8.2003 (Core)
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
@thirdcountry thanks for the report, but just to clarify is this affecting anything else? Or is this just about settings page not reflecting actual configuration?

**Comment by thirdcountry** [comment]
Affected the link in the invitation registration, 
From the actual results, the root_url can't be changed on the Settings page
and nothing else.

**Comment by ethpi** [comment]
Similar problem for me:

I use grafana for monitoring a BBB server, set up with [https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/](https://bigbluebutton-exporter.greenstatic.dev/installation/all_in_one_monitoring_stack/) : grafana 7.1.1 with docker and a reverse proxy on the same server as BBB.

Every thing seems to work fine. But when I send an invitation to a new user, in the sent mail the url to sign in contains `example.com`. I changed the suitable lines in `grafana.ini` like shown in [https://grafana.com/tutorials/run-grafana-behind-a-proxy/](https://grafana.com/tutorials/run-grafana-behind-a-proxy/). Allthough I changed the `domain` from `example.com` to my used domain and set `serve_from_sub_path = true`
the value of `root_url` (shown in admin/settings) is `https://example.com/my_sub_path` .

values set in `grafana.ini`:

```
domain = my.domain.tld
root_url = %(protocol)s://%(domain)s:%(http_port)s/monitoring/
serve_from_sub_path = true
```

values shown in admin/settings:

```
domain = my.domain.tld
root_url = https://my.domain.tld/monitoring/
serve_from_sub_path = true
```
You can see that in `root_url` the sub path is applied, but the domain is still `example.com` .

What am I doing wrong?

**Comment by ethpi** [comment]
Second problem, I hope it belongs to this issue:

At the login page the link in "Forgot your password?" leads to `https://my.domain.tld/user/password/send-reset-email` WITHOUT my subpath, allthough the other links in Grafana contain my subpath  and work fine. 

My login page: `https://my.domain.tld/monitoring/login`
"Forgot your password?"-link: `https://my.domain.tld/user/password/send-reset-email` 

If I insert my subpath by hand in my browser, I can load the suitable page and send a mail. (The sent mail contains again the incorrect domain `example.com` instead of my domain.)

Maybe the "Forgot your password?"-link contains a leading slash? Or an absolut link instead of a relative?

**Comment by marefr** [comment]
This is user configuration error I think. Following our docs it's recommended to use environment variables when using docker, see https://grafana.com/docs/grafana/latest/administration/configure-docker. Second, you're trying to overwrite grafana default configuration which is not recommended, see https://grafana.com/docs/grafana/latest/administration/configuration/#config-file-locations
