### ISSUE TITLE
Forgotten username feature to send username to email 

### ISSUE THREAD

**Issue by deepminimal** [grafana/grafana#29374]
**What would you like to be added**: I would like to have a button with "Remind Login" based on email 

**Why is this needed**:

We have many users who are invited to register by email. Users can forget their login.

**Comment by torkelo** [comment]
Not sure what you mean? store email in browser/cookie so we can remind users?

**Comment by deepminimal** [comment]
Hello @torkelo

After some time users forgot their username and want to remind username by email. 
We can only reset the password. I would to restore username (login) to Grafana. 
![image](https://user-images.githubusercontent.com/18044597/100346517-09a17000-2ff5-11eb-9ca6-01117ba019a3.png)

**Comment by tharun208** [comment]
@torkelo I like to work on this
