### ISSUE TITLE
Security: Use sha256 instead of sha1 when generating user invite codes

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#29384]
G401 (CWE-326):  Use of weak cryptographic primitive
`pkg/services/notifications/codes.go:40`

We use different parts of the invite links based on positions of the string, which we need to update as well.
https://github.com/grafana/grafana/blob/master/pkg/services/notifications/codes.go#L61

This code is quite old so some tests would be nice :)

**Comment by mellieA** [comment]
@bergquist there's an external pr linked to this waiting for review. The contributor is refreshing it and hoping for feedback on #42334

**Comment by bergquist** [comment]
@mellieA merged! Sorry for the slow response
