### ISSUE TITLE
Enhancement: Add "Microsoft.Network/natGateways" to Azure Monitor

### ISSUE THREAD

**Issue by JoeyLemur** [grafana/grafana#29383]
**What would you like to be added**:  Support for the "Microsoft.Network/natGateways" namespace in Azure Monitor

**Why is this needed**:  My company needs to monitor the metrics for our NAT Gateways in Azure.

This _should_ just be a matter of adding the namespace to the SupportedNamespaces class in supported_namespaces.ts -- I did exactly that in my local repo, compiled it, and everything seems to work as expected.  The only problem is that I cannot test the Bytes metric:  for some reason, we don't have any data there in our Azure subscriptions (the Azure portal shows nothing as well), so I'm a little wary of just throwing in a pull request and getting yelled at.  :)

**Comment by aocenas** [comment]
Hey @JoeyLemur if you already implemented this it's always better to create a PR even if it is not complete or you need help with it we still appreciate that. Also definitely no one will yell at you :D though we may be slow at times so feel free to ping people if it does not get attention.
