### ISSUE TITLE
Security: Downloaded plugin zip files should be verified with sha256 instead of md5. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#29389]
`G401 (CWE-326):  Use of weak cryptographic primitive`
 `pkg/cmd/grafana-cli/services/api_client.go:97`

The checksum comes from the grafana.com API so we would have to verify that it has a sha256 checksum of the plugin as well.

**Comment by aknuds1** [comment]
Looking into this.

**Comment by aknuds1** [comment]
@ryantxu @cinaglia Can you please let us know if the plugin API can send SHA256 checksums for plugin versions, in addition to MD5?

**Comment by aknuds1** [comment]
Apparently the API has to be modified to return also SHA256 checksum to the client, in order to enable us to fix this issue.

**Comment by aknuds1** [comment]
For reference, the grafana.com API has to implement support for SHA256 checksums. See [issue](https://github.com/grafana/grafana-com/issues/2097).

**Comment by jkirkwood** [comment]
I just added sha256 support to the grafana.com plugins API. I also back-filled sha256 sums for all plugin versions that had download urls/md5 sums set.

**Comment by aknuds1** [comment]
@jkirkwood Amazing, thanks. I guess we can continue with this issue then,.
