### ISSUE TITLE
SplitPaneWrapper uiState has invalid types

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#29388]
https://github.com/grafana/grafana/blob/aebe8985c57f7b24b7245066d85e1bf3b5b58313/public/app/core/components/ThreePaneSplit/SplitPaneWrapper.tsx#L16 types here are wrong.

My `uiState` looks like this

![image](https://user-images.githubusercontent.com/327717/100239736-072a1200-2f32-11eb-9ecc-b1f694880ac0.png)

it takes also string value `45%`. This currently causes `topPaneSize` to be `NaN`.

**Comment by simPod** [comment]
The value `"45%"` is stored in `window.localStorage`

**Comment by simPod** [comment]
I don't see where it originates from. `updatePanelEditorUIState()` is not called

**Comment by torkelo** [comment]
@peterholmberg can you take a look at this?

**Comment by torkelo** [comment]
Also the component name seems to be different from the filename? should the component not also be named ThreePaneSplit ?

**Comment by peterholmberg** [comment]
> Also the component name seems to be different from the filename? should the component not also be named ThreePaneSplit ?

I renamed it as it's not exclusively three panes.
