### ISSUE TITLE
AlertingNG: Figure out ngalert package structure and interfaces

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#29386]
Under `pkg/services/ngalert` packages and separation of concerns need some attention.

Once we have the stub for the scheduler merged (and maybe instance saving), that would probably be a good time to rearrange things I think.

But we need to figure out what we want the layout to be, so we can collect some ideas in this issue.

**Comment by papagian** [comment]
Closing it since the package has undergone major changes since then.
