### ISSUE TITLE
kbn.parseDate(...).getTime is not a function

### ISSUE THREAD

**Issue by everychengxuan** [grafana/grafana#2938]
Hello, I downloaded the appliance 2.1.1 grafana  to install on a Centos6.5. but, i can't add graph,Prior to this step are normal， I have the message:
   kbn.parseDate(...).getTime is not a function
Can you help me ?
Thanks.
![error](https://cloud.githubusercontent.com/assets/15099868/10445390/9739569a-71a4-11e5-9451-5dcfd449c636.png)

**Comment by torkelo** [comment]
Please redirect your query to the Zabbix team or the developers responsible for their plugin.

**Comment by christianchristensen** [comment]
See: https://github.com/alexanderzobnin/grafana-zabbix/issues/107
