### ISSUE TITLE
Security: Research if we can have lower file permissions for log files.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#29387]
What do other projects do? Seems like a good security practice but can also be annoying for operators. 

`G302 (CWE-276):  Expect file permissions to be 0600 or less`

`/pkg/infra/log/file.go:126`
`/pkg/infra/log/file.go:122`
`/pkg/api/http_server.go:189`

**Comment by aknuds1** [comment]
I would say it also depends on whether there are currently any dependencies on these files having laxer permissions than 0600.

**Comment by bergquist** [comment]
Closing this for now. Anyone who wants to run Grafana in a secure mode should log to stdout/stderr
