### ISSUE TITLE
Specifying time ranges - browser time rather than server time?

### ISSUE THREAD

**Issue by mintyc** [grafana/grafana#2939]
We'd like to look at the last 8 hours of data but find that time is specified relative to the client pc's clock rather than the measurement time or the time of the grafana server or even the database server time.

Assuming we cannot synchronise a client to the servers time how can we avoid the problem.

Ideally I'd like the query at the influxdb to be couched in terms of time now() but can't seem to achieve this.

e.g. Some bright spark put a client pc a whole day ahead of the actual time used at the server and we retrieved no data. If the specification of from: now-8h to: now had been executed at influxdb I think it would have worked, but I'm guessing grafana passes a set of absolute times through to influx and so uses the client pc's offset?

**Comment by torkelo** [comment]
You can set Browser time or UTC, this setting is currently set in each dashboard but will be moved to a profile and org option.
