### ISSUE TITLE
Table panel, wrong display when field (number data type) is zero with Elasticsearch

### ISSUE THREAD

**Issue by fsa1803** [grafana/grafana#29394]
**What happened**:
I'm using Table panel with Elastisearch datasource and raw data as metric.
When value is 0 (zero) the value in the table panel put 0 as prefix. With other values this not happened
![image01](https://user-images.githubusercontent.com/66841577/100254306-6c85ff00-2f42-11eb-8044-4da763502a39.png)

![image02](https://user-images.githubusercontent.com/66841577/100254598-cf779600-2f42-11eb-91da-6f7590585c3d.png)

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Elasticsearch 7.8
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Windows 10, Chrome and Edge
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
What is your panel json ? and what is the raw response from elastic?

Could not replicate with some test data 
![Screenshot from 2020-11-25 17-38-28](https://user-images.githubusercontent.com/10999/100256901-9db3fe80-2f45-11eb-9276-64ae4ce4e9d4.png)

**Comment by fsa1803** [comment]
![image03](https://user-images.githubusercontent.com/66841577/100262945-28e4c280-2f4d-11eb-800d-aef46639286b.png)


![image04](https://user-images.githubusercontent.com/66841577/100262828-faff7e00-2f4c-11eb-8d01-4191141686ba.png)

[panel.txt](https://github.com/grafana/grafana/files/5598341/panel.txt)

**Comment by fsa1803** [comment]
torkelo, I did further tests. In version 7.1.0 the problem is not present. In version 7.2.2 the behavior is as shown in the following images. In the first image the filter is shown correctly, in the second the zero is added and the + and - signs are not shown. I think the problem is related to ad hoc filters

![image_722_1](https://user-images.githubusercontent.com/66841577/100324102-02fc0400-2fc7-11eb-98d0-30aa637b2842.png)

![image_722_2](https://user-images.githubusercontent.com/66841577/100324111-07282180-2fc7-11eb-96ac-b81974eb4fc6.png)

**Comment by pfischer64** [comment]
This seems to be the same issue as 29410

https://github.com/grafana/grafana/issues/29410

**Comment by torkelo** [comment]
Very strange, trying really hard with a field with ad hoc filters and zero and unable to replicate.

**Comment by torkelo** [comment]
@pfischer64 what version of Grafana are you running?

**Comment by pfischer64** [comment]
it's the most recent Version 7.3.3

**Comment by pfischer64** [comment]
@torkelo: It's quite easy to reproduce this behavior: 
1. Just create/use in Grafana an Elasticsearch data-source with some documents containing integer fields. Be sure that at least one document has as integer field with the value 0. 
2. Now create in Grafana dashborad with a table-panel. 
3. Select logs or raw data as your metric.  Result will be double 00 instead of 0. 
4. When you try to get rid of this double 00, e.g. using value mappings, a trailing 0 remains, it is concatenated to the mapped value.

**Comment by torkelo** [comment]
Was able to reproduce now in a production build, we should have a fix soon

**Comment by torkelo** [comment]
Ok, we actually fixed this in 7.3.4 (released 2 days ago), explains why I could not replicate it. Updating changelog now as the the changelog name for the PR fix was not descriptive 

https://github.com/grafana/grafana/issues/29108

**Comment by pfischer64** [comment]
Thank you very much for the very fast reaction and of course the fix @torkelo! 

It works in Grafana 7.3.4 as expected.
