### ISSUE TITLE
no Data & Error Handling should have an evaluation period

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/grafana#29397]
**What would you like to be added**:

![image](https://user-images.githubusercontent.com/5786097/100260034-3dbf5700-2f49-11eb-80b2-347f3166a8a2.png)

This should include an evaluation period such as already exists for alerting in general:

![image](https://user-images.githubusercontent.com/5786097/100260767-1a48dc00-2f4a-11eb-9343-50274bf8d72f.png)

**Why is this needed**:

It is not always required to sent alerts if there is, lets say a downtime of < 1 second. 

In most cases Prometheus is ran in a replication of 2 with a Thanos or Cortex implementation. There is this edge case were a rollingupdate can still cause a "no data" alert because of slow prometheus startup times. Replica 1 goes down for the upgrade. It is not ingesting samples during this time so it has a gap in data. Replica 1 is now back online, so replica 2 goes down for the upgrade. Grafana now triggers a no data alert because replica 1's gap in data.

The real solution is to run Prometheus with 3 replications. Although having a evaluation period of even ~10 seconds would resolve this issue much better.

**Comment by torkelo** [comment]
why does not the For property already solve this? Is there no data for over 5m? Then you will have to raise that value

**Comment by wiardvanrij** [comment]
@tofurky Good question ;) 

The no Data & Error Handling part ignores the alert itself and it's evaluation period & "for".
There is simply no option to define for the no data part.

**Comment by wiardvanrij** [comment]
Solved by https://github.com/grafana/grafana/pull/65574

**Comment by jmaixl** [comment]
^ am also wondering about whether using the No Data / Error states will be changed to also have an evaluation period.
