### ISSUE TITLE
Error "Cannot remove last organization admin" when login with LDAP User

### ISSUE THREAD

**Issue by commarla** [grafana/grafana#2940]
Hi,

I am testing Grafana version: 2.5.0-pre1, commit: v2.1.2+467-g7dc923a, build date: 2015-10-01 16:36:38 and I have this error when I try to log in with a user from ldap.

First login is working fine then I create a new Org  and if I logout and log in again I have this error in the log file : 
2015/10/13 12:57:49 [I] Ldap User Info: (*login.ldapUserInfo)(0xc2082dc930)({
 DN: (string) (len=50) "CN=PSEUDO,OU=Utilisateurs,OU=AAAAA,DC=BBBBB,DC=CCCCC",
 FirstName: (string) (len=7) "Laurent",
 LastName: (string) (len=9) "NOMNOMNOM",
 Username: (string) (len=7) "PSEUDO",
 Email: (string) (len=30) "Laurent.NOMNOMNOM-ext@XXXXXXX.fr",
 MemberOf: ([]string) (len=18 cap=32) {
  (string) (len=63) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=59) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=60) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=72) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=59) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=57) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=65) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=66) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=58) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=58) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=56) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=61) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=62) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=55) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=60) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=55) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=61) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
  (string) (len=54) "CN=XXXXXXXXXXXXXXXXXXXXXXXXXXXX,
 }
})

2015/10/13 12:57:49 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: Cannot remove last organization admin
2015/10/13 12:57:49 [I] Completed /login 500 Internal Server Error in 100.856778ms

I can't log in at all and I have to log in admin to delete the newly created Org to be able to log in with the ldap user again.

You can find ldap.toml and grafana.ini in attachements.
PS : I can't upload any file for now.

Thanks for your help.

Regards,

Laurent

**Comment by commarla** [comment]
http://hastebin.com/ufodifofix.coffee

http://hastebin.com/urudopurew.coffee

**Comment by torkelo** [comment]
Ldap will sync orgs, so you should not create orgs manually that are not mapped in the ldap.toml, then they will be removed from the user. In order to not make created orgs orphaned Grafana will not allow the last org admin to be removed from the list of org users. 

To fix this install latest Grafana 2.5 (pre release) and go to grafana admin view and delete the organization (or add a mapping for it in ldap.toml)

**Comment by commarla** [comment]
Hi,

I have tried that but I am still unable to log in. I have added a group_mapping in first position that match my user: 

> [[servers.group_mappings]]
> group_dn = "CN=LOGINNAME,OU=Utilisateurs,OU=AAAA,DC=BBBB,DC=CCCC"
> org_role = "Admin"
> org_id = 11

And still have the same in the log : 
> 2015/10/22 08:53:59 [I] Ldap User Info: (*login.ldapUserInfo)(0xc2080455e0)({
>  DN: (string) (len=50) "CN=LOGINNAME,OU=Utilisateurs,OU=AAAA,DC=BBBB,DC=CCCC",
>  FirstName: (string) (len=7) "Laurent",
>  LastName: (string) (len=9) "COM",
>  Username: (string) (len=7) "LOGINNAME",
>  Email: (string) (len=30) "EMAIL@COMPANY.FR",
>  MemberOf: ([]string) (len=19 cap=32) {
>   (string) (len=63) "CN=GU_GIE_H_DIR_00032_MEMBRE,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=59) "CN=GU_GIE_A_HYMF_SW_BURA,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=60) "CN=GU_GIE_A_XIPP_DW_FCHRS,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=59) "CN=GU_GIE_A_BURC_TRANSIT,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=57) "CN=GU_GIE_A_BSTG_TLDIS,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=65) "CN=GU_GIE_A_SPE1_CAT_LO_NANTES,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=66) "CN=GU_GIE_A_BSTG_VSPHERE-CLIENT,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=58) "CN=GG_CAT_A_PMD_CAMPRTO,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=58) "CN=GG_CAT_A_PMD_CAMPVTO,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=50) "CN=GU_GIE_A_TIP,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=56) "CN=GU_GIE_A_BURP_V345,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=61) "CN=GU_GIE_A_SPE1_XX_CATE_V,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=62) "CN=GU_GIE_A_PGPUNIVERSALGIE,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=55) "CN=LS_GIE_DROITS_COM,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=60) "CN=GU_GIE_A_WBSS_STANDARD,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=55) "CN=GU_CAT_A_NOT_OUTL,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=58) "CN=GU_GIE_A_TIP_PILOTES,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=61) "CN=GU_GIE_A_SPE1_TS_PROD_M,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC",
>   (string) (len=54) "CN=GU_CAT_F_EXTERNE,OU=Groupes,OU=AAAA,DC=BBBB,DC=CCCC"
>  }
> })
> 
> 2015/10/22 08:53:59 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: Cannot remove last organization admin
> 2015/10/22 08:53:59 [I] Completed /login 500 Internal Server Error in 96.828724ms


I have checked the id in DB to be sure : 
> [root@HOSTNAME GRAFANA-DEV]# sqlite3 var/grafana.db
> SQLite version 3.3.6
> Enter ".help" for instructions
> sqlite>
> sqlite>
> sqlite> .dump org
> BEGIN TRANSACTION;
> CREATE TABLE `org` (
> `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
> , `version` INTEGER NOT NULL
> , `name` TEXT NOT NULL
> , `address1` TEXT NULL
> , `address2` TEXT NULL
> , `city` TEXT NULL
> , `state` TEXT NULL
> , `zip_code` TEXT NULL
> , `country` TEXT NULL
> , `billing_email` TEXT NULL
> , `created` DATETIME NOT NULL
> , `updated` DATETIME NOT NULL
> );
> INSERT INTO "org" VALUES(1, 0, 'PUC', '', '', '', '', '', '', NULL, '2015-10-02 08:42:47', '2015-10-02 12:19:47');
> INSERT INTO "org" VALUES(4, 0, 'TestCR', '', '', '', '', '', '', NULL, '2015-10-05 14:30:10', '2015-10-05 14:30:10');
> INSERT INTO "org" VALUES(5, 0, 'TestXB', '', '', '', '', '', '', NULL, '2015-10-06 06:32:33', '2015-10-06 06:36:36');
> INSERT INTO "org" VALUES(6, 0, 'FB TEST', '', '', '', '', '', '', NULL, '2015-10-08 09:20:39', '2015-10-08 09:20:39');
> INSERT INTO "org" VALUES(11, 0, 'LCO', '', '', '', '', '', '', NULL, '2015-10-13 14:46:45', '2015-10-13 14:46:45');
> CREATE UNIQUE INDEX `UQE_org_name` ON `org` (`name`);
> COMMIT;
> sqlite> .tables
> api_key             dashboard_tag       org                 star
> dashboard           data_source         org_user            temp_user
> dashboard_snapshot  migration_log       quota               user
> sqlite> .dump org_user
> BEGIN TRANSACTION;
> CREATE TABLE `org_user` (
> `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
> , `org_id` INTEGER NOT NULL
> , `user_id` INTEGER NOT NULL
> , `role` TEXT NOT NULL
> , `created` DATETIME NOT NULL
> , `updated` DATETIME NOT NULL
> );
> INSERT INTO "org_user" VALUES(1, 1, 1, 'Admin', '2015-10-02 08:42:47', '2015-10-02 08:42:47');
> INSERT INTO "org_user" VALUES(2, 1, 2, 'Viewer', '2015-10-02 12:14:38', '2015-10-02 12:14:38');
> INSERT INTO "org_user" VALUES(5, 4, 2, 'Admin', '2015-10-05 14:30:10', '2015-10-05 14:30:10');
> INSERT INTO "org_user" VALUES(6, 1, 3, 'Viewer', '2015-10-05 14:39:41', '2015-10-05 14:39:41');
> INSERT INTO "org_user" VALUES(7, 4, 3, 'Admin', '2015-10-05 14:39:56', '2015-10-05 14:39:56');
> INSERT INTO "org_user" VALUES(8, 1, 4, 'Viewer', '2015-10-06 06:30:18', '2015-10-06 06:30:18');
> INSERT INTO "org_user" VALUES(9, 5, 4, 'Admin', '2015-10-06 06:32:33', '2015-10-06 06:32:33');
> INSERT INTO "org_user" VALUES(10, 6, 2, 'Admin', '2015-10-08 09:20:39', '2015-10-08 09:20:39');
> INSERT INTO "org_user" VALUES(11, 1, 5, 'Viewer', '2015-10-08 10:56:35', '2015-10-08 10:56:35');
> INSERT INTO "org_user" VALUES(12, 1, 6, 'Viewer', '2015-10-08 11:00:16', '2015-10-08 11:00:16');
> INSERT INTO "org_user" VALUES(15, 1, 7, 'Viewer', '2015-10-09 11:25:28', '2015-10-09 11:25:28');
> INSERT INTO "org_user" VALUES(20, 11, 5, 'Admin', '2015-10-13 14:46:45', '2015-10-13 14:46:45');
> CREATE INDEX `IDX_org_user_org_id` ON `org_user` (`org_id`);
> CREATE UNIQUE INDEX `UQE_org_user_org_id_user_id` ON `org_user` (`org_id`,`user_id`);
> COMMIT;
> sqlite> .dump user
> BEGIN TRANSACTION;
> CREATE TABLE `user` (
> `id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
> , `version` INTEGER NOT NULL
> , `login` TEXT NOT NULL
> , `email` TEXT NOT NULL
> , `name` TEXT NULL
> , `password` TEXT NULL
> , `salt` TEXT NULL
> , `rands` TEXT NULL
> , `company` TEXT NULL
> , `org_id` INTEGER NOT NULL
> , `is_admin` INTEGER NOT NULL
> , `email_verified` INTEGER NULL
> , `theme` TEXT NULL
> , `created` DATETIME NOT NULL
> , `updated` DATETIME NOT NULL
> );
> INSERT INTO "user" VALUES(1, 0, 'admin', 'admin@localhost', 'MCO MEP Outils Supervision', 'PASSWORD', '9Wdi1VsVW3', 'vHfSEh5ZVn', '', 1, 1, 0, '', '2015-10-02 08:42:47', '2015-10-02 12:19:13');
> INSERT INTO "user" VALUES(2, 0, 'puc', 'EMAIL', 'puc RO user', 'PASSWORD', 'SNSMhNR7so', '4iVzHQEnA2', '', 1, 0, 0, 'dark', '2015-10-02 12:14:38', '2015-10-06 13:55:40');
> INSERT INTO "user" VALUES(3, 0, 'xxxx', 'EMAIL', 'Roussin', 'PASSWORD', 'J04vnZQ78H', 'Cjp3OQqccx', '', 4, 0, 0, '', '2015-10-05 14:39:41', '2015-10-05 14:40:13');
> INSERT INTO "user" VALUES(4, 0, 'yyyyy', 'EMAIL', 'Xavier', 'PASSWORD', 'Y8l73EwxOx', 'OozhQ4oGr7', '', 5, 0, 0, '', '2015-10-06 06:30:18', '2015-10-20 12:13:31');
> INSERT INTO "user" VALUES(5, 0, 'LOGINNAME', 'EMAIL', 'LCO', '', '', '', '', 11, 0, 0, '', '2015-10-08 10:56:35', '2015-10-08 10:56:35');
> INSERT INTO "user" VALUES(6, 0, 'zzzzz', 'EMAIL', 'Simon', '', '', '', '', 1, 0, 0, '', '2015-10-08 11:00:16', '2015-10-08 11:00:16');
> INSERT INTO "user" VALUES(7, 0, 'aaaaa', 'EMAIL', 'Alain', '', '', '', '', 1, 0, 0, '', '2015-10-09 11:25:28', '2015-10-09 11:25:28');
> CREATE UNIQUE INDEX `UQE_user_login` ON `user` (`login`);
> CREATE UNIQUE INDEX `UQE_user_email` ON `user` (`email`);
> COMMIT;
> sqlite>

I can see my user (id 5) admin of org id 11 (named LCO).

Is there the right place to ask about my issue?

Thanks,

Regards,

Laurent
