### ISSUE TITLE
Light/Dark theme plugin logos

### ISSUE THREAD

**Issue by stevenvachon** [grafana/grafana#29400]
**What would you like to be added**:
Add the following fields to the [plugin.json logos schema](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#logos):

* `large_dark`
* `large_light`
* `small_dark`
* `small_light`

**Why is this needed**:
We currently have only `large` and `small` fields. These are fine for graphics that display clearly on both light and dark themes, but not, for example, monochrome graphics (containing only black or white).

**Comment by torkelo** [comment]
Think we can get rid of (deprecate) the small/large, most logos as svg or some mid res png anyway

**Comment by stevenvachon** [comment]
Small/large aren't necessarily for handling resolution or file size, but more for different visuals. For SignalFx, for example, they have both "SignalFx" and "SFx" logos.

**Comment by torkelo** [comment]
> Small/large aren't necessarily for handling resolution or file size, but more for different visuals. SignalFx, for example have both "SignalFx" and "SFx" logos; each with different applications.

Ok, think we only use the small one, never the large one

**Comment by stevenvachon** [comment]
I see the small one used in the panel editor's data source select field and the large one used on the data source list/config pages.

**Comment by torkelo** [comment]
Strange I looked there and could only see it used the small property
