### ISSUE TITLE
$__rate_interval smaller than $__interval

### ISSUE THREAD

**Issue by lhopki01** [grafana/grafana#29403]
**What happened**: 
I set Max data points to 24 and my time range to 24h.  I use the `$__rate_interval` variable but it is set to `615s` which is smaller than `$__interval` variable which is set to `1h`.

**What you expected to happen**:
The documentation says that `$__rate_interval` is `max( $__interval + Scrape interval, 4 * Scrape interval)` so I would expect it to be `1h+15s` as that is greater than `5*15s`.  I don't understand where `615s` comes from.  I also notice that `615s` seems to be the upper bound of `$__rate_interval` even with larger time ranges.

**How to reproduce it (as minimally and precisely as possible)**:
Set Max data points to 24 and time range to 24h.  I use the `$__rate_interval` variable.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.2
- Data source type & version: Prometheus v2.20.1
- OS Grafana is installed on: Linux
- User OS & Browser: Linux , Firefox
- Grafana plugins: Core ones
- Others:

**Comment by zoltanbedi** [comment]
I can not reproduce this. Tried in play.grafana.com with the details you provided and got 7215s. Did you perhaps changed the scrape interval in the data source config of Prometheus?

**Comment by lhopki01** [comment]
This looks like a user error on my part.  I can't reproduce this and see correct values now.
