### ISSUE TITLE
grafana 7.3.4 still missing from OSS Deb repo

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#29408]
The OSS repo still does not provide the grafana 7.3.4 package. The enterprise repo ist fine, as is the manual download via https://dl.grafana.com/oss/release/grafana_7.3.4_amd64.deb. https://packages.grafana.com/oss/deb/dists/stable/main/binary-amd64/Packages.bz2 does not contain any reference to version 7.3.4.

**Comment by aknuds1** [comment]
Yeah sorry, it's a known issue. We're experiencing a persistent error in Google Cloud Storage, and it's taking a while to diagnose and ultimately fix.

**Comment by aknuds1** [comment]
It's fixed! Looks as if Google Cloud Storage fixed the problem on their end somehow, since when I re-published now it worked.
