### ISSUE TITLE
panel component should disable auto-refresh if zoomed in, and end-points aren't going to change

### ISSUE THREAD

**Issue by aleks-mariusz** [grafana/grafana#2941]
I really like the auto-refresh feature, however if the end-points of a graph are static (such as after zooming in), it just reloads the same graph periodically needlessly.  I read in another issue #1813 that this is supposed to be disabled but using 2.1.3, i still see this happening.

may be there should be some logic to determine whether to refresh, and add some conditions (such as, are we zoomed in, e.g. the endpoints not changing because we aren't at the latest data).. or are we editting a graph (issue #1421), etc..

**Comment by torkelo** [comment]
this has been fixed in master and in the 2.5 pre release builds.
