### ISSUE TITLE
X509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by jmvitali** [grafana/grafana#2942]
Hello,
I'm working to try configuring Grafana to work with a Cerberus authentication server (c.f.: https://github.com/AmadeusITGroup/Cerberus).

To implement this king of thing, I try to use the auth.google configuration with this kind of following:
[auth.google]
enabled = true
allow_sign_up = true
client_id = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
scopes = https://cerberus.domain.net/cerberus/api/user.all_info.json
auth_url = https://cerberus.domain.net/cerberus/oauth/authorize
token_url = https://cerberus.domain.net/cerberus/oauth/token
api_url = https://cerberus.domain.net/cerberus/api/user.all_info.json
allowed_domains = domain.net

I tried to install the latest Grafana version (v2.1.3) from a build and by compile directly the code from master branch.

When a user would like to sign-in, the following error is returned on the server console:
2015/10/13 14:42:03 [I] Listen: http://0.0.0.0:8000
2015/10/13 14:43:26 [I] Completed /login/google 302 Found in 788.712µs
2015/10/13 14:43:31 [login_oauth.go:41 OAuthLogin()] [E] login.OAuthLogin(NewTra                                                    nsportWithCode): Post https://cerberus.domain.net/cerberus/oauth/token: x509: cert                                                    ificate signed by unknown authority.

Could you please provide me your feedback for this kind of configuration and the potential source cause of this certificate issue?

Do you know how I can solve this issue?

Thanks in advance,
JM

**Comment by jmvitali** [comment]
For information, I tried to update locally the Master code tagged "v2.1.3" with the path proposed in the commit https://github.com/grafana/grafana/commit/1c5f135b7fc07eab428e93b4fdce435e08d04799, but the certificate issue is still there :(

**Comment by torkelo** [comment]
not sure, the google oauth and github oauth not nested with generic oauth services yet.

But looking at the error you might need to add your oauth service cert as a trusted CA on the server, https://github.com/grafana/grafana/issues/1776#issuecomment-93288541
