### ISSUE TITLE
Ability to create an API key for a different org without switching user context

### ISSUE THREAD

**Issue by semyon2105** [grafana/grafana#29435]
**What would you like to be added**:
Ability to create an API key for a different org without switching user context.

**Why is this needed**:
I have a service that manages orgs in Grafana using a single Grafana admin service account. Currently, to perform some action in an org, I have to create a token using this admin service account and then use this token to call the APIs. Because of the fact that org context is server side in Grafana, there is a race condition inbetween changing the user context and creating a token, if I'm running multiple instances of my service.

For example, if `instance 1` tries to create a token for org "A" and `instance 2` is creating the token for org "B" at the same time, we can end up creating tokens for org "A" in both instances of the service because `instance 1` switched to org context A before `instance 2` sent the "Create API key" request.

One solution is to allow specifying `orgId` in `POST /api/auth/keys` request. The request would be fulfilled if the current user is an admin of the org, otherwise it must be forbidden.

I could also use some form of distributed locking in my service to control concurrent access to the admin account but it would be way more convenient to have this use case supported on Grafana side.

**Comment by daniellee** [comment]
@semyon2105 this feature already exists but is not documented. It took a bit of digging to find it but this was recently brought up in this issue:

https://github.com/grafana/grafana/issues/26769

The feature was added a couple of years in Grafana 4.3.0 but never documented unfortunately: https://github.com/grafana/grafana/pull/8122

We would prefer to document this feature rather adding a new admin API.

Closing this as the feature already exists but can re-open if the header solution does not work for your use case.
