### ISSUE TITLE
Elasticsearch: Raw data mode adds all fields as string

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29431]
When using Raw data mode the data frame field type is set to string even for number fields. 

This makes it so that a number of transformations and visualizations will now suggest or show the field (if they filter for number fields for example). Related bug report: https://github.com/grafana/grafana/issues/28255

Here is the bug: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/elastic_response.ts#L625

**Comment by dagwieers** [comment]
This has hurting us as well, as it doesn't make it possible to have thresholds and different colors when using Raw data.

Thanks for opening this issue !
