### ISSUE TITLE
upon importing json dashboard, all metrics on all graphs have id A

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#2943]
i have a dashboard that i exported at one point
https://github.com/raintank/grafana/blob/2dc9ae2d7151ac58958dbfc0a479113875eabb9f/alerting.json

when i import it now, all metrics on all graphs have id A:
(tested with raintank/grafana master, haven't tested with upstream grafana yet, but should be the same)
![same-ids](https://cloud.githubusercontent.com/assets/20774/10467187/62fd9e28-71c6-11e5-917c-bbc9c543f6c6.png)

**Comment by torkelo** [comment]
fixed!

**Comment by Dieterbe** [comment]
thanks T!
