### ISSUE TITLE
Prometheus: Field display name has no effect 

### ISSUE THREAD

**Issue by igor9292** [grafana/grafana#29437]
![image](https://user-images.githubusercontent.com/5008309/100458887-93286f00-30d5-11eb-97ce-1fe169210c07.png)

I haven't found a way to change this ...

Can you tell me how to do this?

grafana 7.3.3

**Comment by torkelo** [comment]
thanks for reporting this, will fix

**Comment by torkelo** [comment]
@zoltanbedi 

This is a pretty critical issue, I missed this in the review: 

This line should not set displayName but a separate property named displayNameFromDS , this property is a bit special as it make sure you can override the data source display name without using a field override rule  
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/result_transformer.ts#L142

**Comment by zoltanbedi** [comment]
got it. Fixing this asap.

**Comment by torkelo** [comment]
@zoltanbedi no rush, it's late friday, we are not going to do a patch release until tuesday. But just wanted to get his on your radar
