### ISSUE TITLE
Link to Prometheus graph in edit mode not always working

### ISSUE THREAD

**Issue by slovdahl** [grafana/grafana#29444]
**What happened**: Clicking the Prometheus link in edit mode (to get to the PromQL console for the corresponding query) opens the main Grafana page instead.

<img width="1013" alt="bild" src="https://user-images.githubusercontent.com/1417619/100480252-69813f00-30f9-11eb-919e-2887f366027c.png">

**What you expected to happen**: The link opens the PromQL console with the right corresponding query.

**How to reproduce it (as minimally and precisely as possible)**:
1. Load a graph in edit mode
2. Without doing anything else, click the Prometheus link

![grafana-prometheus-click](https://user-images.githubusercontent.com/1417619/100480483-12c83500-30fa-11eb-92e2-113cdfaee8ee.gif)

**Anything else we need to know?**:

I _think_ this started happening when upgrading from Grafana 6.4.3 to 7.2.1. It's still happening with Grafana 7.3.2.

After clicking around and e.g. editing the query, the link eventually starts working.

**Environment**:
- Grafana version: 7.2.1, 7.3.2
- Data source type & version: Prometheus 2.22.0
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: MacOS and Ubuntu 20.04, Firefox 83.0
- Grafana plugins: -
- Others: -

**Comment by Mario-Hofstaetter** [comment]
I've observed this too several times, but since it will eventually work again have not yet created this issue.

**Comment by ivanahuckova** [comment]
Thanks for creating the issue @slovdahl! I was able to re-create the issue and I have found the root of the problem, so the fix is coming soon. 🙂

**Comment by yashumitsu** [comment]
Just a little note: this also happens after switching between Query and Transform/Alert tabs. Reloading the page helps.

**Comment by asilcock-sbg** [comment]
I can't find this link in the UI on Grafana 8.5, does anyone know whether it's been removed or just moved to somewhere else?
