### ISSUE TITLE
cloudwatch.go: params.InstanceIDs undefined

### ISSUE THREAD

**Issue by liavkoren** [grafana/grafana#2944]
Hi. I'm trying to build grafana on OS X 10.9.5 following following the build-from-source documentation. Running `go get github.com/grafana/grafana` raises a 
```
src/github.com/grafana/grafana/pkg/api/cloudwatch/cloudwatch.go:115: params.InstanceIDs undefined (type *ec2.DescribeInstancesInput has no field or method InstanceIDs)
``` 
error. I have go version go1.4.2 darwin/amd64 installed.

**Comment by torkelo** [comment]
Use godep restore  (read the building from source guide on the docsame site)

**Comment by liavkoren** [comment]
That worked. Also, front-end assets compiled correctly, which didn't happen last time I built from source. Good work. :+1:

**Comment by huseyinkozan** [comment]
Same here:
go get github.com/huseyinkozan/grafana

go1.5.1 on Ubuntu 14.04 x86_64
GOPATH=~/.../go-works
GOROOT=/opt/go

**Comment by huseyinkozan** [comment]
Build success after this change :
```
-               params.InstanceIDs = reqParam.Parameters.InstanceIds
+               params.InstanceIds = reqParam.Parameters.InstanceIds
```
