### ISSUE TITLE
Provide a way to execute backend server codes directly without generating a grafana-server.exe and executing it then

### ISSUE THREAD

**Issue by Terry-Su** [grafana/grafana#29459]
**What would you like to be added**:
Provide a way to execute server codes directly without generating a grafana-server.exe and executing it then like:
![image](https://user-images.githubusercontent.com/23733477/100542209-b4c75900-3283-11eb-8a70-62ad619c6993.png)

**Why is this needed**:
If this is supported, we're able to debug backend server codes in vscode using breakpoints! which is really convenient. Now we've to debug with text logs, which is not friendly to display complex object.

**Comment by sakjur** [comment]
I have been running `pkg/cmd/grafana-server` in debug mode successfully in Goland on MacOS. Not sure about working with VSCode and Windows, have you tried following [VSCode Go's debugging instructions](https://github.com/golang/vscode-go/blob/master/docs/debugging.md) for that package?

**Comment by Terry-Su** [comment]
@sakjur  yes, finally being able debug on linux system. however, maybe it's the reason of go version, debugging by running `pkg/cmd/grafana-server`  in vscode on windows fails. Thanks.

**Comment by schirgitom** [comment]
Does anyone know here how to debug the backend in VS Code on a Windows Machine?
Thanks, Thomas

**Comment by honganan** [comment]
Record the steps to debug in Goland on Mac:
1. go run build.go setup
2. go run build.go build
3. run a `Go build` in Goland with:
    Package path: github.com/grafana/grafana/pkg/cmd/grafana
    Program Args: server

**Comment by Ahsan-Aziz-Ishan** [comment]
Here is the complete guideline on how to setup debugger on GoLand:

[Debug-Grafana-Backend-On-GoLand](https://github.com/Ahsan-Aziz-Ishan/Debug-Grafana-Backend-On-GoLand)
