### ISSUE TITLE
[Feature Request] Official AlertManager datasource

### ISSUE THREAD

**Issue by loganmc10** [grafana/grafana#29453]
**What would you like to be added**:

There is an unofficial datasource for querying AlertManager (https://grafana.com/grafana/plugins/camptocamp-prometheus-alertmanager-datasource), but it's falling behind (doesn't seem like it's actively maintained).

**Why is this needed**:

I'm using Grafana Cloud, and the centralized/included AlertManager is very nice. However it would be nice to be able to create dashboards inside Grafana showing things like the active alerts.

**Comment by Elfo404** [comment]
Hi @loganmc10 
Thanks for taking the time to report this.
We are not currently planning to add this, I'd suggest you taking part in maintenance of that datasource or forking it.
