### ISSUE TITLE
Per user dashboard authorization granularity

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#2945]
Now that there is a DB backend to Grafana and LDAP integration it seems users owning the dashboards they create would be the next logical step?
The roles we have are already a huge step in terms of authorization but I think they fall short of the last mile which is linking dashboards to their creators.
The user story would read something like this:
As a Grafana admin I'd like *any* of my Grafana user to be able to create dashboards (from any of the data sources available), save them, and have the option to make it available to everybody else with read only permissions (aka "public") or keep it to themselves (aka "private")
At the moment in order to let all "my" (LDAP based) users save the dashboards they create and have "protected" dashboards that can't be overwritten I'm going to have a "sandbox" grafana with everybody "editor" and a "protected" grafana with only a selected few editors.

Related to https://github.com/grafana/grafana/issues/246

**Comment by torkelo** [comment]
This has already been requested. It has not gotten may you +1 votes so it's not a feature with high priority right now nor sure that it will ever be , but maybe

**Comment by jaimegago** [comment]
@torkelo I haven't been able to find an -open- issue similar to this, I find it surprising that there isn't more interest for dashboard granular authorization. Could you please refer me to the issue requesting this?

**Comment by simonhf** [comment]
@torkelo I would also like this feature and also cannot find the other open issue similar to this.

Assuming that this feature does not happen for a long time, how can I effectively script something up so that some important graphs never get messed up by various users? I saw that there's a scripting ability? Would it be possible to rig some kind of cron job to automatically restore important graphs on a regular basis? How could this work?

**Comment by jaimegago** [comment]
@simonhf There is a create/update API and a get API so one could have a script running every so often that could be the "protector", it's way more "hacky" than having per dashboards authorization though as it adds several more coordination non grafana steps to deal with the "protected" dashboards transport. We had a similar discussion a while back with @edasque on https://github.com/grafana/grafana/issues/273 but that was before there was an HTTP API and more importantly before Grafana had a relational DB  back end that should make dashboard ownership and related features possible. 
I imagine the script something like this:
-The script has a set of protected dashboard available as input (both name and content)
-When executed goes and downloads via "get" API the dashboards and compares to what it knows
- If changes are detected it replaces the "messed" up dashboard with what it has in store

You can see that immediately the question of "how are those protected dashboard" made available to the script comes to mind.

**Comment by simonhf** [comment]
@jaimegago Yep, that's the kind of thing I'd like to do. However, I haven't been able to find very much info on the HTTP API. Do you have any links for me that would help with a simple implementation? Thanks!

**Comment by jaimegago** [comment]
@simonhf http://docs.grafana.org/reference/http_api/

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1128

**Comment by jaimegago** [comment]
@simonhf you should add your +1 to https://github.com/grafana/grafana/issues/1128
