### ISSUE TITLE
Prometheus custom query parameters are not added to alert queries

### ISSUE THREAD

**Issue by alinbalutoiu** [grafana/grafana#29468]
**What happened**:
There is a prometheus datasource in Grafana. It is configured with `Custom query parameters` to be `tenant=test`. Alert queries will not include those custom query parameters.

**What you expected to happen**:
When using `Custom query parameters` for a prometheus datasource, this should be passed to all queries executed against the datasource (including alert queries).

**How to reproduce it (as minimally and precisely as possible)**:
- Setup prometheus datasource;
- Setup [prom-label-proxy](https://github.com/prometheus-community/prom-label-proxy) in front of prometheus which will enforce a given label to the prometheus queries;
- Create an alert for any of the metrics from that datasource and test the rule

**Anything else we need to know?**:

The error returned:
```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "14.763ms",
  "error": "readObjectStart: expect { or n, but found B, error found in #1 byte of ...|Bad request|..., bigger context ...|Bad request. The \"tenant\" query parameter must be p|...: ",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1606739235227,
        "queries": [
          {
            "refId": "A",
            "model": {
              "expr": "test_metric",
              "interval": "",
              "legendFormat": "",
              "refId": "A"
            },
            "datasource": {
              "id": 1,
              "name": "Prometheus"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1606739535227
      }
    }
  ]
}
```

It means that the query doesn't include the custom query parameter specified.

Probably linked to the issue mentioned here: https://github.com/grafana/grafana/pull/19121#issuecomment-549336191

Tested also with `Grafana v7.4.0-7512pre (097dcc456a)` which should include [this fix](https://github.com/grafana/grafana/issues/28907) but the custom query parameters are still not passed for alert queries.

**Environment**:
- Grafana version: `v7.3.3 (2489dc4d3a)`
- Data source type & version: Prometheus
- OS Grafana is installed on: docker image
- User OS & Browser: Windows 10, Chrome Version 86.0.4240.198
- Grafana plugins: default
- Others:

**Comment by scoof** [comment]
It should be possible to work around this when/if https://github.com/prometheus-community/prom-label-proxy/pull/54 is merged

**Comment by byteswift** [comment]
Is it fixed?
