### ISSUE TITLE
add feature: diff legend names when same metric names with diff aggregators in one graph

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#2946]
same metric names with different aggregators in one graph as below:

![selection_007](https://cloud.githubusercontent.com/assets/8777671/10476061/08fad1fe-727d-11e5-8650-229823a6df44.jpg)

It's better the alias contains the aggregator name to distinguish each other

**Comment by torkelo** [comment]
This is due to a limitation in openTSB api :( where you c grafana cannot always correlate series returned to query sent. 

This fixed in OpenTSDB master so it will be fixed in a future version of Grafana when that OpenTSDB feature is released. There already is an issue for this so will close this
