### ISSUE TITLE
Gauge font size too big with threshold markers enabled

### ISSUE THREAD

**Issue by MilesTEG1** [grafana/grafana#29460]
**What happened**: Since the update I made to grafana, my gauges values are too big for the gauges. (screenshot at the end)

**What you expected to happen**: smaller fonts for the values.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.4 (14c494085e)
- Data source type & version: Synology SNMP via Telegraf & InfluxDB
- OS Grafana is installed on: Docker Synology (last version 18.09.0-0513)
- User OS & Browser: macOS Big Sur & Ms Edge (same with firefox and Safari)
- Grafana plugins: Pie Chart + Worldmap panel
- Others: none

Screenshot of what I get now :
![image](https://user-images.githubusercontent.com/29298312/100551026-72e7e400-327e-11eb-918f-7e8db9a4dc6b.png)

Screenshot of what I had before  :
![image](https://user-images.githubusercontent.com/29298312/100551612-0d95f200-3282-11eb-81a2-4ba4faad5ac1.png)

**Comment by torkelo** [comment]
If anyone wants to help with tweaking the font size logic: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Gauge/Gauge.tsx#L111

**Comment by chihsuan** [comment]
I can reproduce this in both **v7.3.4** and **v7.3.5** that installed via Docker  but not in master branch. 🤔

More details about how to reproduce it:

1. Create a new panel and select the **"default"** as data source
2. Choose **Gauge** Visualization
3. Turn on the **"Show threshold labels"** option on "Display" part
4. Switch to "Field" tab and change the unit to **"Celsius"**  and fill the **"Display name"** with "Drive 1 (To 4)"


**Environment:**

User OS & Browser: macOS & (Firefox and Chrome)

**v7.3.4**
![Screen Shot 2020-12-17 at 2 32 25 PM](https://user-images.githubusercontent.com/4344253/102452847-08a0b300-4076-11eb-8c9f-454f35fab862.png)

**v7.3.5**
![Screen Shot 2020-12-17 at 2 32 29 PM](https://user-images.githubusercontent.com/4344253/102452868-13f3de80-4076-11eb-9353-9e043a8dd74f.png)

**master branch**
![Screen Shot 2020-12-17 at 2 32 41 PM](https://user-images.githubusercontent.com/4344253/102452898-253ceb00-4076-11eb-881e-c3440585316d.png)

**Comment by thisisobate** [comment]
Hi @MilesTEG1 
It seems like this issue has been fixed in later versions of Grafana- couldn't replicate on Grafana play.
Would proceed to close this but in case you still enter encounter this issue, feel free to reopen it.

**Comment by MilesTEG1** [comment]
Hello,
There is some better display, but it is not yet perfect. 
I'm currently using Grafana v7.5.2 (ca413c612f).
This is what I currently have :
![image](https://user-images.githubusercontent.com/29298312/113156975-c4a77780-923a-11eb-8dce-0887922d22c4.png)

I have to remove the unit °C to have a decent display.
