### ISSUE TITLE
grafana-7.1.3 graph field values are not updating

### ISSUE THREAD

**Issue by AVESH-RAI** [grafana/grafana#29466]
all the fields are shown as "values" "values" "values" instead of original fields in the graph.

Legend is shown as value. The following query is applied:

[sum(node_memory_MemTotal)](url) - sum(node_memory_MemFree) - sum(node_memory_Buffers) - sum(node_memory_Cached)

This was working in the previous releases of grafana. But it not working in Grafana - 7.1.3 release.

**This image is from newer grafana release**

[
<img width="666" alt="grafana" src="https://user-images.githubusercontent.com/3483683/100587697-eb9a7f00-3316-11eb-8093-b4b67739c4f7.PNG">
](url)

**This image is from older grafana release:**

<img width="669" alt="grafana-old" src="https://user-images.githubusercontent.com/3483683/100588155-85fac280-3317-11eb-90d5-411bc7aae13b.PNG">

**Comment by torkelo** [comment]
What data source are you using?
Can you update your data source (if it's a plugin) and the update Grafana to 7.3

**Comment by AVESH-RAI** [comment]
DataSource is **prometheus** .

With Grafana 7.3.4 also its not working.

**Here is the image for Grafana 7.3.4**

![image](https://user-images.githubusercontent.com/3483683/100832469-f1ff3700-348d-11eb-8618-c55c69567a84.png)

**Comment by zoltanbedi** [comment]
So I've checked this and the last version where we showed the query instead of Value was 6.7.3. I wonder how others didn't find this. I think this is not a critical issue I would also say that maybe this was an intended change. You can work this around by adding name to your legends.

I'm not sure if we want to fix this or not? @davkal

**Comment by davkal** [comment]
Let's fix this by reintroducing the query itself as the legend item if the label set is empty.
