### ISSUE TITLE
unicons bundle is 2.17MB

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#29478]
i'm guessing most users don't need 99% of it.

![image](https://user-images.githubusercontent.com/43234/100684233-8909a900-333f-11eb-97d7-7c7f7a15a352.png)

![image](https://user-images.githubusercontent.com/43234/100684547-2c5abe00-3340-11eb-9f98-918311af9507.png)

cc @ivanahuckova

**Comment by torkelo** [comment]
wow, that seems insane for a few svgs.

**Comment by ivanahuckova** [comment]
Yeah, I agree! 🤯 It seems like in the last 2-3 months they have added a lot of new code. Maybe we check their [repo](https://github.com/Iconscout/unicons) to see why is that and help them reduce it down.

**Comment by torkelo** [comment]
hm.. all svgs in the unicons svg folder for just the line variant is 4.7mb , hmm seems crazy, but should minify a lot. Wonder what font awesome is. 

When checking a product build of 7.3 I cannot see a unicons webpack chunk.
