### ISSUE TITLE
Annotations exception when showing dashboard on 2.5.0-pre1

### ISSUE THREAD

**Issue by baaym** [grafana/grafana#2947]
I was looking at the live demo of Grafana 2.5.0-pre1, and when clicking around I received an exception when opening a dashboard: http://play.grafana.org/dashboard/db/annotations

The exception is:
*Annotations error
Cannot read property 'from' of undefined*

**Comment by torkelo** [comment]
thanks for reporting this! :star: 

Fixed in master, Will push out new 2.5 pre release build now (should be up in 5min)
