### ISSUE TITLE
Annotations clean up job should delete annotations tags

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#29484]
Currently, the annotation clean up job in Grafana only deletes rows from the `annotation` table. It should also delete all rows in  `annotation_tag` that refers to the delete annotations. Otherwise, the annotation_tag table will grow endlessly. 

https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/annotation_cleanup.go

**Comment by dafydd-t** [comment]
The `annotation_tag` table contains ids for in the `tags` table. This does not grow so rapidly (many tags are reused), so we will not be deleting records from `tags` as part of this ticket. This simplifies the scope a bit.
