### ISSUE TITLE
Improve keyboard navigation on the Change Password page

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#29495]
**What would you like to be added**:
I would like to be able to skip the password change form after logging in with the *admin* password, by quickly navigating with Tab and pressing Enter when the *Skip* button is focused. Currently, this is not possible. When the *Skip* button is focused pressing Enter doesn't do anything.

![Kapture 2020-12-01 at 13 35 58](https://user-images.githubusercontent.com/2376619/100741753-5e206300-33da-11eb-950e-7cab088e8140.gif)

**Comment by thisisobate** [comment]
Would look into this
