### ISSUE TITLE
X-Ray: Update data link to set datasourceName or title in datasource

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#29506]
This is a reminder to fix this in the X-Ray data source before the 7.4 release. 
https://github.com/grafana/x-ray-datasource/blob/17961da4d6c4c244892718707b7436a0cb1f7902/src/DataSource.ts#L234 

Reference for how loki does it:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/result_transformer.ts#L399

I am going to try to update Explore to only use datasource uid internally, then we can get rid of datasourceName in the internal link, and just test title (to datasourceName).

**Comment by torkelo** [comment]
@aocenas Is there any change needed here? looks like x-ray sets the title of the link: https://github.com/grafana/x-ray-datasource/blob/master/src/DataSource.ts#L231

**Comment by aocenas** [comment]
I think we should add the `datasourceName: 'x-ray'` or something like that there to be consistent. Will do a PR for that.

**Comment by aocenas** [comment]
I mean I am not sure if title or datasourceName is interchangeable? They will have different values so not sure if it make sense to just have one?

**Comment by torkelo** [comment]
@aocenas if there is no datasourceName the title will be used

**Comment by aocenas** [comment]
In any case this will be fixed in https://github.com/grafana/x-ray-datasource/pull/60/files#diff-55f5543444b39114e63df73b26b73bb97f951f0b8e3290e96d148cbc8ac91418R30

**Comment by aocenas** [comment]
closed in https://github.com/grafana/x-ray-datasource/pull/60
