### ISSUE TITLE
Template repeating panel - Max span setting

### ISSUE THREAD

**Issue by sknolin** [grafana/grafana#2950]
Using template variables with repeating panels I'd like to set a not just a minimum span, but also a maximum.

The reason is I need to mix 2 types of panel in one row. In my case it's switch port data - so throughput in mb/s, plus things like number of broadcast packets or discards. These can't be one metric, they use different calculations. But it really make sense to have them on one row.

I set the throughput metric to a span of say '4' - since it's the only graph, that leaves room for 3 more metrics on that row, right? It doesn't, if you just pick one metric for the repeated panel, it uses a span of 12 and shows up on the next line.

I'd like to add - the repeating templated variable feature is great. I can see it taking the place of some scripted dashboards we've had to make.

Scott

**Comment by hau21um** [comment]
Faced same issue, some way to overcame this?

**Comment by hau21um** [comment]
What I suggest is to 

- introduce also maxSpan for templating 
- or respect span from "General Option"  when there is null in maxSpan.

Now when I've panel A repeating only twice and B repeating 6 times, both with span==3 and nisSpan==3, what happen is  tat As visually spans to 2x6, Bs to 6x3 and are mixed on row like ABABBBBB (Ordering AABBBBBB would make even more sense to me)

I'm excited with Grafana look, but if those two cosmetic things would be solved, then look will be even more cool for me ;-)
Milos

**Comment by misko321** [comment]
+1 This would be extremely useful when creating a dashboard with a lot of singlestats, to make them more compact.

**Comment by nizq** [comment]
+1

**Comment by hzhaop** [comment]
+1

**Comment by daianmartinho** [comment]
+1

**Comment by Althasandrian** [comment]
+1

**Comment by sfitts** [comment]
Some combination of this plus a "default span" (to override the panel's default behavior of wanting to fill a row) would be a big help.  As it is using repeat panels with single stat tends to end up with a bunch of single stat panels filling multiple rows (when they could easily compress down to one based on min-span).

**Comment by macgyver603** [comment]
+1

**Comment by Cougar** [comment]
What about counting number of all panels and then calculating span size? Right now it looks like the calculation is always 12 divided by amount of repeated panels but should be 12 minus sum of other panel sizes before division.

**Comment by antonbrixtoroe** [comment]
1+

**Comment by torkelo** [comment]
Mixing repeated panels and non repeated panels on the same "row" is tricky in Grafana as there is no such thing as rows really,  panels can cross "rows". So figuring out spacing is a bit tricky and messy. 

We don't want to make the repeat feature more complicated than it already is. Hope to address more dynamic dashboard layouts with a revamped scripted dashboard feature in v8 or after v8
