### ISSUE TITLE
Docs: Cloudwatch query variables wrongly formatted

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#29503]
The same issue as https://github.com/grafana/grafana/pull/29027, but now in [Cloudwatch template documentation](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#templated-queries)

![image](https://user-images.githubusercontent.com/30407135/100769161-f5e27900-33fb-11eb-9e39-2df57d67ec5c.png)

**Comment by oddlittlebird** [comment]
@ivanahuckova, I don't see any changes in the Cloudwatch that don't correspond to replacing italic with code format. Where is the problem? Can you help me find what the correct value should be?

**Comment by ivanahuckova** [comment]
@oddlittlebird I have created a [PR with fix](https://github.com/grafana/grafana/pull/29677). The problem was with unnecessary `_\__` which shouldn't be there. There was the same issue in prometheus template variables that was fixed in #29027.
