### ISSUE TITLE
Feature Request: Compare panel on two different timelines

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#2951]
I think this feature will be super useful if we can compare a particular panel for two different timings. The ideal scenario would be a split screen with a particular graph/panel with two different selected timings. Here is a sample screenshot:

<img width="1425" alt="screen shot 2015-10-14 at 10 07 56 pm" src="https://cloud.githubusercontent.com/assets/1019609/10490713/18fef920-72c0-11e5-81d8-713408b8320a.png">

The first panel is showing the same graph from 6:00 AM to 12:00 PM and the second one is showing from 12:00 PM from 18:00 PM.

**Comment by torkelo** [comment]
would it not be better to have the timeshifted graph be under the first so the time axis aligns, 

Also maybe something like this can be useful? https://github.com/grafana/grafana/issues/300#issuecomment-39940894

Also Graphite has a very useful timeShift function that allows you to mix series (or the same series) from different time ranges on the same panel

**Comment by bergquist** [comment]
@utkarshcmu does #4063 satisfy the needs for this issue?

**Comment by utkarshcmu** [comment]
Yeah that works. Closing this issue then. Thanks @bergquist
