### ISSUE TITLE
UI Problems/flashing when selecting functions editing a panel query.

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#29517]
**What happened**: UI makes it difficult to select functions. Keeps snapping back and forth.

**What you expected to happen**: Consistent UI experience allowing easy election of menu values.

**How to reproduce it (as minimally and precisely as possible)**:
See video.
![Flashing-Menu](https://user-images.githubusercontent.com/2402929/100809536-2cfc5e80-33eb-11eb-9f39-a6bf57d1e0a6.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: Graphite
- OS Grafana is installed on: Fargate
- User OS & Browser: macOS Catalina w/ Safari and Chrome (both browsers do this)
- Grafana plugins: A lot.

**Comment by davkal** [comment]
Looks more like a frontend issue to me: Dropdowns temporarily extend the viewport.

**Comment by mckn** [comment]
This will probably be resolved if we migrate this Query Editor to using the react components. Will add it to the observability board @davkal. If that is okay with you?

**Comment by torkelo** [comment]
This one could be hard to solve, need to extend the scroll area of the queries section when any dropdown is opened

**Comment by mckn** [comment]
> This one could be hard to solve, need to extend the scroll area of the queries section when any dropdown is opened

Shouldn't this behavior go away with the new cascader?

**Comment by davidnewhall** [comment]
I don't think I've seen this happen in recent versions. I'll consider it resolved.
