### ISSUE TITLE
Filter variable with tags included All value option

### ISSUE THREAD

**Issue by taisytran** [grafana/grafana#29528]
**What happened**: option `All` is always selected automatically whatever tag is even selected
<img width="507" alt="Screen Shot 2020-12-02 at 5 49 06 PM" src="https://user-images.githubusercontent.com/16373463/100864305-6656cc00-34c8-11eb-913c-743293915e05.png">

**What you expected to happen**: Option `All` will be unselected once tags are selected

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a variable with tags query with enabling multi-value` and `include all option`
2. on Dashboard page, select variable with tag

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: Prometheus v2.22.0
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Chrome

**Comment by ivanahuckova** [comment]
I was able to reproduce this issue on https://play.grafana.org/d/000000024/templating-value-groups?orgId=1

**Comment by mckn** [comment]
Thanks for reporting this! I totally agree that it should work the way you describe it. However, the support for tags are deprecated and will be removed. See this issue for more information: #29602
