### ISSUE TITLE
Use CDN to serve up JS libraries

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#2954]
Would it be possible to have an option to use a CDN to serve up some of the JS libraries?

For example, angular.js could be served from:

https://cdnjs.com/libraries/angular.js/

And likewise for the other libraries.

For us, we're using a Grafana instance across geographically disparate teams - we can have the instance close to one team, but then it makes it slow for everybody else.

We could alleviate this somewhat if the JS assets were at least served from a CDN - this will also mean some files may be pre-cached for some users (i.e. other projects that use that CDN), and also will take load off the Grafana server from serving JS files.

**Comment by torkelo** [comment]
If you are using a official build it should only a single optimised js file that is only loaded once. But your right a CDN option cloud still make sense.

**Comment by kokarn** [comment]
Sounds like a good idea. No real drawback. Jsdelivr could probably do the
same thing with one merged file for you without much hassle.

jsdelivr.com
https://github.com/jsdelivr/jsdelivr/

**Comment by zqhong** [comment]
You can use nginx's rewrite to achieve it.

This repository simply implements it:
https://github.com/zqhong/grafana-cdn/tree/master

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/6844
