### ISSUE TITLE
Flow Charting plugin Inspect Abnormal display

### ISSUE THREAD

**Issue by bbker** [grafana/grafana#29561]
**What happened**: Flow Charting plugin Inspect Abnormal display

**What you expected to happen**: Grafana version 7.0.3 is displayed normally

**As the picture shows**:

![](https://s3.ax1x.com/2020/12/03/DTxSsS.png)

**Environment**:
- Grafana version: 7.3.0 or up
- OS Grafana is installed on:Windows Server 2016
- User OS & Browser:Windows Edge\Chrome
- Grafana plugins:FlowChart plugin version:0.9.0

**Comment by ivanahuckova** [comment]
Hello @bbker, this is a problem with Flow Charting plugin which is not part of Grafana core plugins. Please report the issue directly in the [Flow Charting repo](https://github.com/algenty/grafana-flowcharting).
