### ISSUE TITLE
Docker image build with option build-docker-full gives error no such file or directory

### ISSUE THREAD

**Issue by VishalLahane** [grafana/grafana#29569]
**What happened**:
Build image with  build-docker-full
Run the image : docker run --name grafana -d  -p 3000:3000 grafana/grafana:dev
See the logs: docker logs grafana 

**Below error it shows:**

lvl=eror msg="Failed to read plugin provisioning files from directory" logger=provisioning.plugins path=/etc/grafana/provisioning/plugins error="open /etc/grafana/provisioning/plugins: no such file or directory
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

Build image with  build-docker-full
Run the image : docker run --name grafana -d  -p 3000:3000 grafana/grafana:dev
See the logs: docker logs grafana 

**Anything else we need to know?**:
NA
**Environment**:
- Grafana version:  7.3.4
- Data source type & version:
- OS Grafana is installed on: Docker 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
@VishalLahane jut to confirm, I can close this issue as it was fixed in https://github.com/grafana/grafana/pull/29570?

**Comment by VishalLahane** [comment]
@ivanahuckova please close the issue
