### ISSUE TITLE
Enhance datasource SigV4 auth to allow excluding some header to be signed 

### ISSUE THREAD

**Issue by alvinlin123** [grafana/grafana#29566]
**What would you like to be added**:
This is a followup issue for https://github.com/grafana/grafana/pull/27552

It would be nice if we can allow user to configure the SigV4 auth to exclude certain headers to be included in the signing process. 

**Why is this needed**:

Some headers gets modified hop-by-hop. One such example I discovered is `x-request-id`, some gateway might drop rthe client passed in value for `x-request-id` and generate a new ID. 

This is a problem because consider the following case: 
1. Grafana SigV4 signed a `x-request-id` with value 'ID-1234`
1. Grafana sends the request to remote data source. 
1. The gateways between Grafana and the remote data source ignores the `x-request-id` from the caller, and generate a new ID. 
1. Now, the auth will fail because what Grafana signed is different from what remote data source sees.  

In fact, `x-request-id` is just an example; there may be other headers suffers same problem; hence, it would be nice if we can allow customer to configure what headers to be excluded from sigV4 signing process.

**Comment by alvinlin123** [comment]
Another idea I just thought of is, instead of have a configuration for customer to put headers to exclude, maybe Grafana can just sign a fixed set of headers?

**Comment by wbrowne** [comment]
@alvinlin123 Thanks for creating this issue as it highlights a useful feature. It's something we have already discussed and would likely end up supporting exclude headers via the config

**Comment by bergquist** [comment]
@wbrowne Do you think we can solve this by convention instead? So ex only sign Host + Auth headers.

**Comment by wbrowne** [comment]
@bergquist Possibly.. Though I'm unsure of how that affects the request signing verification on AWS' side - IIRC it was quite finicky when I removed certain headers. Using their proxy as a reference, they use a [header exclude list](https://github.com/awslabs/aws-sigv4-proxy/blob/1a2c06073da1f0f4b1e9636b9c13b1df694361db/handler/proxy_client.go#L126).

**Comment by alvinlin123** [comment]
@wbrowne the more I think about it, the more I think, the more I feel it is better user experience if Grafana signs fix set of headers. Having customer to configure an exclusion list may be troublesome as customers probably does not know what header they should exclude. 

I think @bergquist  makes more sense because it allows customers to think less, and make things "just works". 

Signing a fixed set of headers shouldn't affect signing verification on AWS side because the authorization token in the `Authorization` header has a list of headers that was signed. AWS has [public documentation on how SigV4 works](https://docs.aws.amazon.com/general/latest/gr/sigv4-create-canonical-request.html).
