### ISSUE TITLE
Snapshot: add support to capture annotations as well

### ISSUE THREAD

**Issue by The-Nik** [grafana/grafana#2956]
My idea:
Currently, in a snapshot are no annotations. I like to share them too. A fine way would be to have some checkboxes in the snapshot-creation area to select which data the snapshot should include.

Possible options are:
* Annotations (maybe a further distiction by the single once)
* Templating
* Data range (timebox)

Anyone else need this?

**Comment by rsmets** [comment]
A snapshot that captures the templating as well would be handy, I agree.

**Comment by mtanda** [comment]
+1

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/pull/3635 is merged.
Snapshot is supported for annotation.
