### ISSUE TITLE
plugin.json templating enhancement : Expose connection Url

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#29560]
**What would you like to be added**:

Current plugin.json templating implementation is only supporting JsonData & SecureJsonData fields. It would be very helpful to have the ability to ability to use Url as well

**Why is this needed**:

When the authentication server is self-hosted, it is necessary to dynamically choose the url based on the datasource url.

**Comment by torkelo** [comment]
what url? the url you specify in the datasource settings.

**Comment by sbouchex** [comment]
Yes, that url (from the DataSourceSettings). I have defined a config editor using the DataSourceHttpSettings component and I want to use the defined url to point to the right authentication server.

**Comment by hugohaggmark** [comment]
@sbouchex I think you need to supply more information about the use case you're thinking about.
