### ISSUE TITLE
Grafana/ui: SegmentAsync component cannot be disabled

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#29573]
**What happened**:

I have defined a SegmentAsync component (in a datasource panel) and I have added disabled={true} to disable it.

Example : 
```
<SegmentAsync
         disabled={true}
          loadOptions={() => this.props.datasource.getall()}
          onChange={this.handleChangeProperty}
          allowCustomValue={true}
          value={this.state.property}
          placeholder="Select an Property"
/>
```

**What you expected to happen**:

The component should be disabled and clicking on the component should not open the menu.

**How to reproduce it (as minimally and precisely as possible)**:

Just define it

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: custom
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: custom
- Others:

**Comment by ivanahuckova** [comment]
Thanks @sbouchex for creating this issue. I was able to replicate it.
