### ISSUE TITLE
Text fields cursor cannot be moved using mouse in firefox

### ISSUE THREAD

**Issue by siddharthasahu** [grafana/grafana#2957]
Firefox 41
Grafana 2.1.3

I'm not able to navigate the text cursor position using mouse in any of the text fields. Clicking to position the text cursor does not have any effect.

On chrome, they work properly.

**Comment by torkelo** [comment]
can you test on http://play.grafana.org ? its running 2.5 per release builds

**Comment by siddharthasahu** [comment]
Nopes. Does not work here either.

**Comment by utkarshcmu** [comment]
Similar to #1123

**Comment by wyzssw** [comment]
![grafana](https://cloud.githubusercontent.com/assets/4242774/10532933/2ab2095a-73f6-11e5-9112-9d359883e00d.jpg)
grafana can not show all the datasources  in graph--metrics edit table
