### ISSUE TITLE
Cloud - Worldping visual UI bug - card not expanding with the list

### ISSUE THREAD

**Issue by hemdrup** [grafana/grafana#29571]
https://ops.grafana.net/ <- Grafana internal site
https://ops.grafana.net/d/000000115/worldping-home?orgId=1 

The card does not seem to expand with the long list. Which properly also why the other card is laying on top.

**Environment**:
- Grafana version: v7.3.3 (2489dc4d3a)
- User OS & Browser: Mac Big sur, Firefox

<img width="528" alt="Screenshot 2020-12-03 at 13 48 14" src="https://user-images.githubusercontent.com/21049979/101020383-b5573c80-356e-11eb-9e21-05ed53eda0e8.png">

<img width="1834" alt="Screenshot 2020-12-03 at 13 45 41" src="https://user-images.githubusercontent.com/21049979/101020390-ba1bf080-356e-11eb-98ac-ee010fd0ebe8.png">

**Comment by torkelo** [comment]
looks like a bug in the worldping plugin & the endpoints panel. It is extending outside its bounds. 

Cannot find this endpoints panel in the synthetic monitoring app: https://github.com/grafana/synthetic-monitoring-app

**Comment by torkelo** [comment]
ah, this is the old worldping, looks like it is missing scrollable property: https://github.com/raintank/worldping-app/blob/master/src/panels/endpoint-list/module.js#L13
