### ISSUE TITLE
Dashboard: Row panels should be html editable

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#29576]
**What would you like to be added**:
Row panels are used to collect and collapse panels, they do have a text description, but it is very limited. It would be better to allow HTML so more formatting and options can be used

As a side note, it can also be used for anchoring which is super helpful with links.

**Why is this needed**:
when header rows are used for sections it will be useful to support HTML formatting.

**Comment by hugohaggmark** [comment]
Related #29456

**Comment by mckn** [comment]
Thanks for opening this request however I will close this one since I can't see that we will support this in the near future. I can also see that this might be a bit tricky when it comes to security concerns.

Please try to give a bit of a better explanation of how you would like to use this and we can try to suggest another way of doing this.

**Comment by amnonh** [comment]
Please re-open,
See these few examples (I did a trivial change just to make it work, but it should work like the text box)
This is how row header looks like today:
![image](https://user-images.githubusercontent.com/2118079/101240852-8cfc4900-36fa-11eb-8877-ca3db6e7844e.png)

This is an example with minor formatting (using html):
![image](https://user-images.githubusercontent.com/2118079/101240860-9980a180-36fa-11eb-8d3c-571e92166e77.png)

This is not just size and color, this can also be used for html-anchoring, so when using links in panels, you can link to a section, not just a page

This is an example of what you can do with multiple lines, when the same, above row is closed:
![image](https://user-images.githubusercontent.com/2118079/101240890-d0ef4e00-36fa-11eb-92b6-c3b9480ab7d4.png)

So you get a text when the row is closed, but it's gone when the row is opened.
