### ISSUE TITLE
Tooltips in dashboards are getting truncated

### ISSUE THREAD

**Issue by siddharthasahu** [grafana/grafana#2958]
The length of tooltips in graphs seems to have a fixed length, so metrics with long paths in graphite are getting truncated and I cannot see the corresponding value.

Screenshot:
![screenshot_20151015_152828](https://cloud.githubusercontent.com/assets/867424/10510672/eec283ba-7351-11e5-9390-958d224debd9.png)

Please make the tooltips dynamic, so they take up atleast all the screen space available.

Thanks

**Comment by torkelo** [comment]
use the graphite alias functions to get shorted legend names :) There are many ways in graphite to get short readable series names!
