### ISSUE TITLE
Human readable Series Labels

### ISSUE THREAD

**Issue by WiR3D-kNiGhT** [grafana/grafana#2959]
Hi, firstly thanks for grafana, its fantastic.  

I'm using (our application) -> statsd -> influx -> grafana. 
And I'm trying to figure out how to map labels for series on the graph to a more human readable format. We currently have a unique reference used in the stats and we have a human readable value in our system, im trying to figure out how to send the human readable value across and how to map it, or how to do a lookup for the human readable value. 

Any ideas?

![grafana](https://cloud.githubusercontent.com/assets/4290536/10515406/a0e95a40-7353-11e5-828a-7d28be07ef4a.jpg)

**Comment by torkelo** [comment]
store it in a tag then you can use that in the alias pattern
