### ISSUE TITLE
Random Orphan Hover tooltip created and stick permanently on dashboard

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#29601]
**Current Behavior:**
When large dashboard is used and mouse is moved around the dashboard during dashboard load/time range change, sometimes orphan tooltip remains permanently into the dashboard in fixed position.

This is similar issue than https://github.com/grafana/grafana/issues/18533 which was fixed into 6.x.
First time seen in 7.3.4. I have not seen this earlier in 7.x, so with high probabity regression introduced between 7.3.3 and 7.3.4.
See better picture from #18533 which also shows the background. 

![image](https://user-images.githubusercontent.com/19704268/101133922-47645100-3612-11eb-939f-496d4bd64930.png)

**Expected Behavior:**
Orphan tooltips are not permanently added to the dashboards.

** Repro step:**
In 6.x this was easy to reproduce by moving mouse after time range changed (result all template variables o be resolved) and dashboard is reloading. 
Probably once template variables are resolved the all dashboards are reloaded and hover tooltip from previous time range is not correctly removed.
In 7.3.4 I cannot systematically reproduce the issue but after 15min of heavy use one tooltip stays permanently in dashboard.

**Removing tooltip:**
- Grafana needs to be reloaded, switching dashboard is not enough.

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: Prometheus
- OS Grafana is installed on: WIndows 10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
I wasn't able to reproduce this, but I'll pass it to @grafana/grafana-frontend-platform squad for more investigation.

**Comment by hugohaggmark** [comment]
I'm going to close this as I can't repro this issue. We can always reopen this if more users are affected or if there is a consistent way of reproducing the issue.
