### ISSUE TITLE
Deprecation: features planned to be removed in Grafana 8

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#29602]
This is an epic issue to list features that we currently have planned to remove from Grafana 8. We will try to list each feature with a brief explanation of the decision to remove the feature.

 ### Tags for template variables (https://github.com/grafana/grafana/pull/30160)
Was originally added to support [Worldping](https://worldping.raintank.io/) since the underlying datasource Graphite did not support it out-of-the-box. If we fast forward to today, Graphite has a good support for tags and the template variable tags functionality in Grafana has not got the attention it deserves makes us leaning towards removing it

**Comment by blasco991** [comment]
but why? This was a really nice feature to have :(

**Comment by torkelo** [comment]
It was added at a time when time series databases did not support tags. There is no longer a great need for it. It's very complicated and messy, hard to use / setup and an edge case use case. 

We want to remove it to simplify the templating variables code to make it easier to maintain and more bug free and easier to use.

**Comment by bro-ee** [comment]
It's very useful feature if using other (non-timeseries db), like postgresql and need to filter it... Is it possible to leave this feature or at least make it optional?

**Comment by dkroboth-oneweb** [comment]
The tag service is actually a very useful way to select a subset of tags, particularly if don't want to increase the cardinality of the data set,

**Comment by torkelo** [comment]
@dkroboth-oneweb the same thing you can do with the removed tags feature can be done by creating two separate variables, one that queries for the tags, and then another that queries for the values and filters using the tags variable.

**Comment by dkroboth-oneweb** [comment]
@torkelo, it works yes, the UX is not as intuitive as you lose the visual link between immediate action and response, and I think it clutters the display somewhat:

tags:
![image](https://user-images.githubusercontent.com/77800211/120631892-5f3c5680-c436-11eb-9a49-940aab2700b1.png)
no tag:
![image](https://user-images.githubusercontent.com/77800211/120631778-3fa52e00-c436-11eb-992e-89e7983cb6eb.png)
