### ISSUE TITLE
Live Tailing: If retrying connection, let user know in better way than message in console

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#29609]
**What happened**:
Related to https://github.com/grafana/grafana/pull/29438. We would like to keep retrying a connection in a case of abnormal error, but let users know that something wrong is happening. However, this is tricky because we can't throw error cause retrying wouldn't work and we can use AppEvents outside of Grafana app.

**Comment by matyax** [comment]
Nothing to do here for now.
