### ISSUE TITLE
Flexible permissions for the Grafana Explore

### ISSUE THREAD

**Issue by OlegMuron** [grafana/grafana#29621]
**What would you like to be added**:
Currently, only Admin and Editors users have access to the Grafana Explore.
It will be great if Grafana Explore has some similar access settings as **[Dashboard and Folder Permissions](https://grafana.com/docs/grafana/latest/permissions/dashboard_folder_permissions/#dashboard-and-folder-permissions)**

**Why is this needed**:
In our company, we have more than 600 developers in different Teams and  Departments. 
Each user has custom access to different Dashboards and Folders in the Grafana. Unfortunately, our DevOps could not give to all developers editor roles.

**Comment by ivanahuckova** [comment]
Thanks for creating this feature request. I am adding this issue to out  added it to our backlog. However, I am wondering, if using the [viewers_can_edit ](https://grafana.com/docs/grafana/latest/permissions/organization_roles/#viewer-role) setting wouldn't be something you are looking for. If you set this setting to true, then users with the Viewer role can also make transient dashboard edits, meaning they can modify panels and queries but not save the changes (nor create new dashboards). This is also used for example in our [grafana.play ](https://play.grafana.org/).

**Comment by lovelski** [comment]
Same request, Same problem !!!

**Comment by gelicia** [comment]
Hello, the Explore team looked at this issue and for now have decided the current functionality where you can set `viewers_can_edit` to give non-editors access to explore should serve the majority of users' needs here. Additionally, you can set permissions by datasource on the enterprise version if that is more what you would like to limit access to.

We are going to be closing the ticket for now as we do not intend to build out any further access restrictions, but if `viewers_can_edit` does not solve your use case, please create a [discussion](https://github.com/grafana/grafana/discussions) to help us understand what we can do to help and prioritize a fix.
