### ISSUE TITLE
Grafana plugins for UI behavior

### ISSUE THREAD

**Issue by BertHartm** [grafana/grafana#29626]
**What would you like to be added**: The ability to create plugins that add menu items or otherwise change grafana UI behavior outside of panels and datasources.

**Why is this needed**:
I would like to add a button to grafana to allow saving the current dashboard json to github. This is rather custom to my workflow, so I expect to write a plugin, but it doesn't appear that plugins can affect general behavior, but are limited to a particular scope.

I can try to inject javascript and css and do this inside the browser, but that really constrains potential behaviors since I have no access to the React data model.

**Comment by pkolyvas** [comment]
@BertHartm - Thanks for submitting this idea.

I think there are two possible feature requests here. The first is an plugin framework that would allow you to extend Grafana functionality in a way you can't now - particularly UI behaviour. That's not on our roadmap at the moment. 

The other feature request is having a GitOps-friendly workflow to ingress and egress your dashboard JSON into a VCS (like GitHub). That is something we're currently designing and we'd welcome you to add your use cases and workflows here to help inform our plans if you'd be willing: https://github.com/grafana/grafana/discussions/37917
