### ISSUE TITLE
grafana can not show all the databases ，only show three

### ISSUE THREAD

**Issue by wyzssw** [grafana/grafana#2963]
![dbss](https://cloud.githubusercontent.com/assets/4242774/10533030/02289976-73f7-11e5-832a-bb824b86bef3.jpg)

graph---metrics tab，can not show all databases
![dbs](https://cloud.githubusercontent.com/assets/4242774/10533003/bd5ef39e-73f6-11e5-9743-4dab494e22ab.jpg)

**Comment by torkelo** [comment]
fixed in master

**Comment by torkelo** [comment]
and in 2.5 pre release builds, http://grafana.org/download/builds.html

**Comment by wyzssw** [comment]
thanks
