### ISSUE TITLE
Prometheus: Add interpolation of nested template variables in Legend

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#29639]
**What happened**:
I'm using a prometheus query with a `sum` aggregation function and the `by` is a variable.
I.e. `by` can be cluster, shard, dc etc'

I want to add to each graph some comment:
If I use just {{[[by]]}} (the nested variable) it works:
![Screenshot from 2020-12-06 18-27-33](https://user-images.githubusercontent.com/2118079/101286067-34f43e00-37f1-11eb-98c6-73115ba9d3e2.png)

But when I add text I get:
![Screenshot from 2020-12-06 18-27-59](https://user-images.githubusercontent.com/2118079/101286083-476e7780-37f1-11eb-99d5-1052143b013e.png)

**What you expected to happen**:
Each of the graph should have a legend from both text and value, but I can get either.

**How to reproduce it (as minimally and precisely as possible)**:
You need a metric with a label, create a parameter from that label and define an aggregaor variable like `by` to have the name of the label.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4 (but I dont' think it's a version specific)
- Data source type & version: prometheus
- OS Grafana is installed on: docker
- User OS & Browser: fedora/chrome
- Grafana plugins: NA
- Others: NA

**Comment by ivanahuckova** [comment]
@amnonh we are currently not interpolating nested template variables. It might seem that it is working when you are using `{{[[by]]}}`, but it is just listing all labels as it wasn't able to interpolate that nested variable. 

Here it might seem that it is working:
![image](https://user-images.githubusercontent.com/30407135/106582059-dbd02e80-6543-11eb-80eb-7ac4ef37029b.png)

But here you can see that non-existing variable leads to listing all labels as well:
![image](https://user-images.githubusercontent.com/30407135/106582209-0621ec00-6544-11eb-9a4f-03ab48632e19.png)

Therefore I am changing this from bug to feature request.
