### ISSUE TITLE
Option required to disable Grafana admin ability to create new users via UI  

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#29648]
**What would you like to be added**:

As a security enhancement, we would like to have an option to disable creation of new users via UI .  

When we enable an alternative method of authentication (LDAP, OAUTH, SAML), we would like to be able to disable the creation of new local users, and enforce IAM with LDAP/OAUTH/SAML only.   

To implement this, we would like an option to disable the ability for an admin to create a new local user  (as per https://grafana.com/docs/grafana/latest/manage-users/add-or-remove-user/ ) 

**Why is this needed**:
This is required as a security enhancement - an admin having the ability to create local users in Grafana is seen as a security risk by some organisations.

**Comment by aengusrooneygrafana** [comment]
hold fire on this - we think we can achieve this with '# disable creation of admin user on first start of grafana'

**Comment by aengusrooneygrafana** [comment]
Actually we still have an issue and need further investigation.  We could disable grafana/server admin for all users via ldap.toml config, however 'Invite user' also allows local users to be created.

**Comment by aengusrooneygrafana** [comment]
Note:  speaking with Mitch, limiting the ability to create local users / groups etc will be picked up as part of RBAC changes for Grafana 8.

**Comment by linoman** [comment]
This topic is already being discussed for a major rework. You can follow the progress at the enterprise [issue](https://github.com/grafana/grafana-enterprise/issues/5233).
