### ISSUE TITLE
on viewPanel page, the share icon should share the panel URL, not dashboard

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#29641]
**What happened**:
1. user is on a viewPanel page
2. user clicks on top-nav "share" icon, expecting it to share the panel view
3. the generated link is for the dashboard, not the panel

**What you expected to happen**:
Maybe very experienced Grafana users will know that 1) the top-nav share link is **always** for the dashboard, even if you're on a panel view; and 2) panels have their own share link, inside the panel menu.  However, for the other 90% of people, this is confusing.

When on panelView, the top-nav share link should be for the panel, not the dashboard.

**Environment**:
- Grafana version: 7.3.4

**Comment by alebricio** [comment]
Hi there! 👋🏼 If it's okay, I'd like to work on this starting today.

**Comment by divbhasin** [comment]
Hi, new contributor here :wave: I did not see any recent activity on this one so I submitted a PR.
