### ISSUE TITLE
Plugins: Be able to create new variables from plugin code 

### ISSUE THREAD

**Issue by pwSteve** [grafana/grafana#29647]
Hello,

Our company want to migrate the panels from AngularJS to React and it is only one thing missing. We want to create a template variable in the code from a data source. We could do this with VariableSrv, but now in React with TemplateSrv is it not possible.

I saw on 7.3 on @grafana/runtime Reference, that exists already this: https://grafana.com/docs/grafana/latest/packages_api/runtime/templatesrv/
but you can only get the variables and replace a value, but need also to create a variable.

Do you planned to implement this in the future?

**Comment by torkelo** [comment]
There is no way do create new variables from plugin code in v7.x 

Ẃe do not have any such plans. Can you define the use case for this?

**Comment by pwSteve** [comment]
The use case for our company is that we create a language variable, always when you choose our datasource, automatically he will create this variable on the dashboard with the data from an api. With this variable the user can choose in which language, he gets the text. For example the signal names are than in German or French.

This language will also automatically updated when a new language is added by the api.

We also have now 18 Panels that use this variable to know in which language we visualize the edit mode.

**Comment by tolzhabayev** [comment]
closing as stale
