### ISSUE TITLE
[Feature Request] better Methods for organizing dashboards

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#2964]
Currently, dashboards appear as a unorganized list to the user. Label seems not a satisfactory method for organizing way. When a user wants to see a graph of a specific metric, even though there is already a graph, he can not find it if he is not the creator of the graph. If we can organize graph in a better way, I can find the graph for a metric, even though the graph is not created by me.

There seems already an issue proposing using folder as an organizing way. It seems a nice solution.

**Comment by mattttt** [comment]
We've been discussing this a lot internally and there definitely is room for improvement here. 

Couple questions for you @liyichao: 
- In your use case, how much are the dashboard groups tied to Org structure? 
 - Do you have a need to restrict dashboards to only certain users/groups of users?

**Comment by liyichao** [comment]
There is only one group right now, we currently have not see a need to restrict access.

**Comment by torkelo** [comment]
@liyichao good idea! 

Will close as there is already a very similar issue, https://github.com/grafana/grafana/issues/1611
