### ISSUE TITLE
Explore link of stackdriver datasource no longer works after upgrade from v6

### ISSUE THREAD

**Issue by billcchung** [grafana/grafana#29643]
**What happened**:

The `Explore` link no longer works after upgraded from v6 (v6.7.4 in my case),
the panel was configured as stackdriver datasource before upgrade:
![Screen Shot 2020-12-07 at 16 03 44](https://user-images.githubusercontent.com/5371682/101319753-ce7d2780-38a5-11eb-9654-59a23edfef62.jpg)

and after the upgrade, the link no longer opens `Explore` page, from the console it has errors:
```
datasource.ts:313 Uncaught (in promise) TypeError: Cannot convert undefined or null to object
    at Function.entries (<anonymous>)
    at t.value (datasource.ts:313)
    at t.value (datasource.ts:345)
    at datasource.ts:359
    at Array.map (<anonymous>)
    at t.value (datasource.ts:359)
    at explore.ts:102
    at c (runtime.js:45)
    at Generator._invoke (runtime.js:271)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
value @ datasource.ts:313
value @ datasource.ts:345
(anonymous) @ datasource.ts:359
value @ datasource.ts:359
(anonymous) @ explore.ts:102
c @ runtime.js:45
...
```
![Screen Shot 2020-12-07 at 15 53 51](https://user-images.githubusercontent.com/5371682/101319957-303d9180-38a6-11eb-8fbc-4a8a4f2d9409.jpg)

after some checking, we noticed the dashboard json has extra json contents added after click `Edit` (edit the panel):
```
          "metricQuery": {
            "aliasBy": "{{metric.label.method}} -> {{metric.label.route}}: {{metric.label.code}}",
            "alignOptions": [
              {
                "expanded": true,
                "label": "Alignment options",
                "options": [
                  {
            ...
            "lastQueryError": "",
            "metricKind": "DELTA",
            "metricType": "....",
            "perSeriesAligner": "ALIGN_SUM",
            "service": "",
            "unit": "1",
            "usedAlignmentPeriod": 60,
            "valueType": "INT64"
          },
          "queryType": "metrics",
```

So we think these contents were missing from the upgrade, and the typescripts are looking for these, currently the workaround is edit the panel, save the dashboard (so the extra contents being saved), then the `Explore` link should work again.

**What you expected to happen**:
After clicking on the `Explore` link, it should open `Explore` page with the metric options set from the panel.

**How to reproduce it (as minimally and precisely as possible)**:
1. install grafana v6.7.4
1. configured stackdriver data source and a panel with the datasource
1. upgrade grafana to v7.3.4
1. check the dashboard with the panel (without clicking any `edit` link), click on the `Explore` link, the error should show, and UI did not redirect.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v6.7.4 -> v7.3.4
- Data source type & version: Stackdriver 
- OS Grafana is installed on: docker grafana/grafana:7.3.4 
- User OS & Browser: macOS Catalina 10.15.7, Chrome Version 87.0.4280.88 (Official Build) (x86_64)
- Grafana plugins: 
- Others:

**Comment by andresmgot** [comment]
I can confirm that the issue is still present when using a panel created in v6.x in both v7.x and v8.0.0. I can try and send a quick patch.
