### ISSUE TITLE
Panel show switch

### ISSUE THREAD

**Issue by yujiapingyu** [grafana/grafana#29646]
**What would you like to be added**:
Function of panel show switch.

**Why is this needed**:
When use variables, we may need to control whether the panel is displayed based on variables. For example, when V = "some condition", we want panel1 and Panel2 to show, otherwise we want the panel to be hidden. It seems impossible to do this right now.

**Comment by torkelo** [comment]
Hi, thanks for create this feature request.

It's similar to https://github.com/grafana/grafana/issues/4470 

But we won't add conditional logic like this that hides panel (makes them impossible find / edit). The solution for this use case will be new scripted / programmatically defined dashboard that we hope to introduce next year
