### ISSUE TITLE
Improve error message when renderer payload is too large

### ISSUE THREAD

**Issue by dafydd-t** [grafana/grafana#29655]
**What would you like to be added**:
When a payload is sent to a renderer running outside of the grafana instance, the server might respond with an error because the payload is bigger than the configured limit. We should handle this error gracefully explaining the cause of the error.

The example we have of this is where the renderer is running behind nginx, and the nginx instance returns `413 request entity too large`. 

**Why is this needed**:
[See relevant slack conversation here](https://raintank-corp.slack.com/archives/CVD7EPRAN/p1607339074189900)

cc @bergquist

**Comment by peterholmberg** [comment]
Please assign labels and projects when creating new issues @dafydd-t
