### ISSUE TITLE
Cloud monitoring: request sent to the backend with undefined queryType

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#29667]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. create new dashboard
2. add new panel
3. select a cloud monitoring (stackdriver) datasource
4. select a service (eg `Compute`) without selecting anything else eg project, metric
5. request fails because `queryType` is undefined
6. in the query editor select `Metrics` as `QueryType` (now the request has a valid queryType and succeeds)

**Anything else we need to know?**:

**Environment**:
- Grafana version: master (commit 874f2fafb2fa4c56423773902af419335390f140)
- Data source type & version: Google cloud monitoring
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
I think this has to do with this line: 
https://github.com/grafana/grafana/blob/922f36b386e21393fddffa22031c5b645e8369ca/public/app/plugins/datasource/cloud-monitoring/components/QueryEditor.tsx#L21

Seems like a typo was introduced in [this](https://github.com/grafana/grafana/commit/546f569e0c467d4ba748b4f390ad289b9c74bec6#diff-71862e079d75143b30ed8b1ed31035e4c988a541e201d9d72cdba5e4af478037) commit

**Comment by sunker** [comment]
Actually I can fix this - I'm already making changes to this file in another PR that will be merged soon
