### ISSUE TITLE
Field from calculation/Reduce Row not working when datasource is cloudwatch

### ISSUE THREAD

**Issue by luanhdeandrade** [grafana/grafana#29666]
<img width="1679" alt="image" src="https://user-images.githubusercontent.com/50885837/101389551-5eb86e00-38a0-11eb-84e3-7d39ddce26fe.png">

**What happened**: Many field values returned

**What you expected to happen**: Only the reduced value to be returned (with the total amount)

**How to reproduce it (as minimally and precisely as possible)**:

Create a panel with cloudwatch metrics as data source 
Set visualization as Gauge 
Add a query returning a time series 
Add a field from calculation -> Reduce Row (Total) over the series you added 
Set the "Period" for the query to "1d" 
In Display -> Show set as "All fields"

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.2.1
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Amazon Linux / Docker
- User OS & Browser: MacOs/ Safari
- Grafana plugins:
- Others:

**Comment by luanhdeandrade** [comment]
Also happening with 7.3.4 version

**Comment by torkelo** [comment]
Use the reduce transform. Reduce row only reduces a single row (sum across all fields for one time point for example)

**Comment by luanhdeandrade** [comment]
Thanks for the fast response. I see that I am unable to view the field (in the fields drop down list) if I don't combine: "reduce row" and "reduce" transformations. Is this the expected behavior?
Thanks

**Comment by torkelo** [comment]
not sure I understand

**Comment by luanhdeandrade** [comment]
I think I had a problem with the field names being refreshed into the lists. When I removed all transformations and added again, it seemed to work

**Comment by luanhdeandrade** [comment]
Sorry to necrubump this, but I don`t know why the field "error rate" doesn't show here:

<img width="1661" alt="image" src="https://user-images.githubusercontent.com/50885837/101502798-25d7d200-3950-11eb-9400-e231590fdf82.png">

**Comment by luanhdeandrade** [comment]
This is working
<img width="1655" alt="image" src="https://user-images.githubusercontent.com/50885837/101504568-21acb400-3952-11eb-8d07-55e0036e38aa.png">

<img width="1262" alt="image" src="https://user-images.githubusercontent.com/50885837/101504681-40ab4600-3952-11eb-9cab-f9e8bcd25bc1.png">

And error rate field is now appearing
