### ISSUE TITLE
Templated dashboards for KairosDB don't work with variable tag names. 

### ISSUE THREAD

**Issue by burtonator** [grafana/grafana#2966]
Tag names can't be templated it seems.

The following is supported:

hostname=$hostname

but if I do something like

$role = true

That won't work.  In fact, as soon as I click the + button , the entire chart goes away, so does the line I just added, and the chart is blank.  

I've duplicated this a number of times and I get the same problem every time.

I don't get anything logged in the JS console.

I've confirmed that the actual tags are there.  If I use them manually they work.  It's just that I can't make them templated.

**Comment by bergquist** [comment]
closed by https://github.com/grafana/datasource-plugin-kairosdb/issues/2

**Comment by vguhesan** [comment]
+1 voting for this feature
