### ISSUE TITLE
instead of looking at a dashboard on the tv, I am looking at a login page???

### ISSUE THREAD

**Issue by f1-outsourcing** [grafana/grafana#29675]
grafana-7.3.4-1.x86_64

wtf is going on this year????? I used to be able to run whole year without incidents now every week there is something.

(and no I cannot get a dump from firefox, because the developers from firefox thought it was not necessary to enable this in a 'headless' environment.)

====
to reproduce:
just leave an on premisses grafana install on for a week with a remote db influx+promotheus

**Comment by f1-outsourcing** [comment]
When I login, I am having straight away the dashboard in display mode, that was already running.

**Comment by RichiH** [comment]
Hi.

I will be closing this issue for several reasons:

1. You submitted the same issue in the past, and were told it's a duplicate: https://github.com/grafana/grafana/issues/28636
2. Your issues usually ignore all our guidance for producing useful bug reports. Things which might be obvious to you are not obvious to others and unless we all follow established processes to externalize mental context, reproducing and triaging issues becomes next to impossible.
3. Frankly, your behavior on this and other repositories is generally unfriendly, abrasive, and aggressive. While I understand that software not doing what you want it to do can be stressful, there are also humans on the other end of your input field and in particular with Open Source software some basic courtesy is to be expected from all sides.

**Comment by f1-outsourcing** [comment]
@RichiH 

I am giving you enough info, to look into the problem. If you do not understand them, that is your problem. Then the grafana team should put someone with more knowledge on reviewing issues. 
If you have enough background knowledge you should be able to work with them. 

As you wrote yourself "guidance for producing useful " it is guidance.

Frankly it is quite lower grade level behaviour to judge this issue based on other issues, you do get that I hope. I am not your buddy, nor your friend, nor your teacher, nor your bully ;)
Be a professional. You make it look like it is my fault grafana is not able to show a dashboard for a week.
Whether or not this is opensource software is irrelevant. Your development is going into a direction where your product becomes 'in-stable', hardly something the core dev team would want to see. Instead of waiting until you get more people complaining about similar issues you might want to act on this now. 

Is your testing team now running seamonkey and/or firefox headless on a grafana server with remote databases?

**Comment by RichiH** [comment]
One of the most important aspects of community work is to protect said communities from disruptive actors. While no one is the bad guy in their own mental movie, the effect on the receiving side is what matters in communication. We have tried to explain this in the past, but failed. As such, we are dis-inviting you from this community.

You are welcome to continue using our software for free.

You are, however, not welcome to participate in our community in any media or any form going forward.
