### ISSUE TITLE
Support for unix socket for postgresql backend

### ISSUE THREAD

**Issue by giimsland** [grafana/grafana#29676]
**What would you like to be added**:
I would like to have support for using unix socket to connect to a postgresql database instance as backend for Grafana

**Why is this needed**:
In cases where you cannot connect to IP/URL, it would be nice to utilize unix sockets. This is for instance useful when running Grafana GCP Cloud Run, and you cannot use private IPs.

**Comment by aknuds1** [comment]
Are you sure it isn't already working? I tested now (with `host = /var/run/postgresql` in conf/custom.ini), and it appears to be working.

Please try that, and let us know if it doesn't work.

**Comment by giimsland** [comment]
I should have been more clear. This issue is happening when supplying configuration through environment variables when running Grafana in a container.

I can see its supported for mysql (confirmed working) in https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/sqlstore.go, line 182-184.

There's no option for postgresql to support for the postgresql type (starting on line 202).

**Comment by aknuds1** [comment]
@giimsland I don't see what difference it should make whether you use environment variables or not. Can you post the environment variable(s) in question please?

**Comment by aknuds1** [comment]
The code you linked to btw, for connecting to Postgres, works wrt. connecting to Unix sockets. I just tried and can confirm.

**Comment by giimsland** [comment]
The variables in use are GF_DATABASE_TYPE="postgres", GF_DATABASE_HOST="/cloudsql/some:connection:name"

When using these, the service is unable to start with errors:
net.SplitHostPort failed for '/cloudsql/some:connection:name
Invalid host specifier '/cloudsql/some:connection:name'

**Comment by aknuds1** [comment]
Aha, I'm guessing this is a bug in our parsing logic due to the multiple colons in the path.

**Comment by aknuds1** [comment]
Can you open a bug report instead?

**Comment by giimsland** [comment]
Sure.
