### ISSUE TITLE
Migrate core datasources to VariableSupport API

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#29674]
Core data sources to migrate to new VariableSupport API:
- [ ] ~~Google Cloud Monitoring~~ (partially migrated in #28217 needs to migrate to use Observables in data source) 
- [ ] ~~Cloudwatch~~
- [ ] ~~Elastic~~
- [ ] ~~Graphite~~
- [ ] ~~InfluxDB~~
- [ ] ~~Jaeger~~
- [ ] ~~Loki ~~
- [ ] ~~MSSQL ~~
- [ ] ~~MySQL ~~
- [ ] ~~OpenTSDB~~
- [ ] ~~Postgres ~~
- [ ] ~~Zipkin~~
- [ ] ~~Prometheus (partially migrated in #28217 needs to migrate to use Observables in data source) ~~
- [ ] ~~Tempo~~
- [ ] ~~TimeStream~~
- [ ] ~~Azure~~
- [ ] ~~Grafana~~

**Comment by mckn** [comment]
Closing this one if favor or the following issues:

https://github.com/grafana/grafana/issues/40122
https://github.com/grafana/grafana/issues/40124
https://github.com/grafana/grafana/issues/40125
https://github.com/grafana/grafana/issues/40126
