### ISSUE TITLE
The text box is too small! (variables)

### ISSUE THREAD

**Issue by STEELBADGE** [grafana/grafana#29672]
**What would you like to be added**:

Please make the text input variable box a configurable size. Either an explicit size when setting it up or allow us to chose between small/medium/large.

**Why is this needed**:

The current text input variable is set to 192px which is far too small, for example:

![](https://globalnoc.github.io/tsds-grafana/assets/img/search-template-var.png)

I feel like this was a deliberate decision decision so we don't create a generic query box for our dashboards and users only input a targeted value which is then used in the underlying query.

However for data sources like Elastic & especially when building log search dashboards you  want to give the user a bit more flexibility in what they input and far better to leave it up to the designer of the dashboard to decide how large the text input should be.

**Comment by STEELBADGE** [comment]
I made a PR to make this configurable! 

https://github.com/grafana/grafana/pull/29794

Hopefully when that is merged we can close this.

@peterholmberg

**Comment by hugohaggmark** [comment]
Hi @STEELBADGE I'm bringing this issue and PR up on our weekly PR meeting and we'll take it from there.

**Comment by jorijinnall** [comment]
Hi, the PR might be reopened. I don't see why we don't merge this change that would be really helpful to let the dashboard designer do what he wants on this.

My use is that I want to provide a field where the user fill a SQL request and then all my panels directly executes this SQL request to display computed results

**Comment by duane-impulse** [comment]
+1

**Comment by ivanortegaalba** [comment]
@Ijin08 @thanos-karachalios  let me ping you here.

This feature request comes from this PR https://github.com/grafana/grafana/pull/29794

The request is about making the text box for the variable resizable/bigger to be able to write SQL queries for example.

We could solve this from different fronts:
* Have a configuration width field (PR suggestion) so the configuration form displays a new option to set that value.
* The width just adapts to the text context, until a max width (@torkelo proposal)
* We can have a boolean in the text variable configuration to make it a text area, so it can be resizable by the user (just an idea)

Any thoughts on this?

**Comment by jorijinnall** [comment]
I vote for this one "The width just adapts to the text context, until a max width (@torkelo proposal)"

But the third option looks to be a good one too

**Comment by axelavargas** [comment]
Hey team, I'm shifting this to the 'Future' column for now. It's unlikely we'll tackle this in the short term. During our ongoing [migration](https://github.com/grafana/grafana/issues/73874) to render dashboards with [Grafana Scenes](https://github.com/grafana/scenes), we've already updated the variable picker. It's not perfect yet, but it's a step in the right direction! 😊

![image](https://github.com/grafana/grafana/assets/239999/2d73b555-b8d6-482f-ab79-821c09b27a3f)

**Comment by mdvictor** [comment]
This is going to be fixed in our new architecture soon. I will close this issue for now, but do let us know if we can help any further.

Thank you for your issue!

**Comment by qin-nz** [comment]
@mdvictor Can you give the commit-id, or release version. So we can know which version can fix this.

**Comment by jorijinnall** [comment]
@mdvictor could you provide a release or another that we can follow ?

**Comment by mdvictor** [comment]
Hey folks, sorry for the late response! This was fixed as part of the migration to the new Scenes based architecture. We're planning to launch this in G11 behind a toggle and roll it out to everyone as we ensure the new architecture is stable.

**Comment by Spinestars** [comment]
> Hey folks, sorry for the late response! This was fixed as part of the migration to the new Scenes based architecture. We're planning to launch this in G11 behind a toggle and roll it out to everyone as we ensure the new architecture is stable.

Is this implemented in G11?

**Comment by QtRoS** [comment]
@mdvictor is this feature now available in the latest version of Grafana? 🙏

**Comment by QtRoS** [comment]
Looks like TextBox's width is still [hardcoded](https://github.com/grafana/grafana/blob/31b71f79dd3a1e00cd269a95d2505d5b8358c7c3/public/app/features/variables/textbox/TextBoxVariableEditor.tsx#L37). No signs of related [feature flags](https://github.com/grafana/grafana/blob/6ca3d8a27ac630a106619950d2d2df041b0bffff/pkg/services/featuremgmt/registry.go#L0-L1) too. So there is no solution ATM?

**Comment by STEELBADGE** [comment]
I fixed this 5 years ago and this hasn't been merged :(

**Comment by genericname01** [comment]
I really need this feature. Why can't this be merged? Some of our users are asking for it

**Comment by STEELBADGE** [comment]
![image](https://github.com/user-attachments/assets/c0bf14b4-7b93-46fe-9f6c-434d736fe4d2)

**Comment by torkelo** [comment]
the max width is 30*8 (240px) for the new dynamic width input (That changes width based on input). that max width could be increased I think to 40 or 45

https://github.com/grafana/scenes/blob/main/packages/scenes/src/variables/components/VariableValueInput.tsx#L33

**Comment by a-abella** [comment]
Making a log query dashboard is a challenge with such a small text box for query input.
