### ISSUE TITLE
Pop-up button “add annotation” on click on graph

### ISSUE THREAD

**Issue by ypashkova** [grafana/grafana#29681]
Hello!

Pop up button “add annotation” appears when i click on the graph.
In the [documentation ](https://grafana.com/docs/grafana/latest/dashboards/annotations/#annotations) i see that adding annotation available by holding down Ctrl/Cmd+Click. But now it appears just by click, without ctrl/cmd.

![image](https://user-images.githubusercontent.com/75675399/101481901-ea94cd80-3966-11eb-8226-9dea95403ea5.png)

It seems like a bug, because it prevents me from zooming time range. This button constantly appears when I want to zoom the graph.

Version where it appears - 6.7.3 Updated to 7.1.5. The problem is still there. On 7.3.1 is also present.

On version 6.0.2 it doesn’t appear

How do I get rid of this? Is it normal behaviour?

Tnanks

**Comment by peterholmberg** [comment]
Hi, I just tried this on play.grafana.org and it works there. Can you see if it works for you?

https://play.grafana.org/d/aw0AkS5Gz/grafana-issue-triage?viewPanel=8&orgId=1&from=1607275268147&to=1607384094771

**Comment by ypashkova** [comment]
Hi!
Pop-up button “add annotation” appears when i clicked :(

![image](https://user-images.githubusercontent.com/75675399/101483293-04371480-3969-11eb-91c4-a38c0cc1cbfa.png)

**Comment by peterholmberg** [comment]
Yeah, that's true. For zooming I click (and hold) and drag the cursor.

**Comment by ypashkova** [comment]
I don't understand. Is it normal that button appears or not?

**Comment by peterholmberg** [comment]
If you ctrl/cmd + click you will open the add annotation overlay, if you just click you select a data point. This is as intended.
