### ISSUE TITLE
Database: Using Unix socket for Postgres fails when path has non-port-separator colons

### ISSUE THREAD

**Issue by giimsland** [grafana/grafana#29680]
**What happened**:
When supplying environment variable GF_DATABASE_HOST as /cloudsql/some:connection:name for postgresql, the container is unable to start with the following errors:

```
net.SplitHostPort failed for '/cloudsql/some:connection:name
Invalid host specifier '/cloudsql/some:connection:name'
```

**What you expected to happen**:
I expected Grafana to accept unix socket as hostname for postgresql

**How to reproduce it (as minimally and precisely as possible)**:
Using Cloud Run, with latest image from grafana. Supply postgresql database configuration, with unix socket in GF_DATABASE_HOST(make sure the socket path has multiple colons, f.ex. /cloudsql/some:connection:name).

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest
- Data source type & version: postgresql11, backend
- OS Grafana is installed on: ubuntu container image
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by aknuds1** [comment]
Discussed this with my colleague and it dawned on us that also the last colon in the specifier is not a part separator, the whole string is a filesystem path. I think we will have to add a port field to the Postgres data source settings UI, to disambiguate since a colon isn't necessarily a port separator.

Adding that port field is a breaking change though, so we'll add that as a feature request that we will solve for a future release (7.4? 8?). In the meantime we're thinking of making the workaround that we'll only interpret the part after the last colon if it is numerical.

**Comment by aknuds1** [comment]
@giimsland What do you think of the workaround of protecting the colons with backslashes, i.e. so they're not interpreted as port separators? F.ex `/cloudsql/some\:connection\:name`.

**Comment by aknuds1** [comment]
Sorry, I just realized now that the issue is for Postgres as Grafana's database backend, not as data source. Let me think on the database backend case.

**Comment by aknuds1** [comment]
@giimsland I made a draft PR with a solution similar to the one for MySQL, i.e. we consider the host specifier a Unix socket path if it starts with a slash. The drawback is that the PR doesn't yet support combining Unix socket paths with port specifiers. WDYT?

https://github.com/grafana/grafana/pull/29725

**Comment by gfrankliu** [comment]
What about using database.url configuration? Will something like below work?
```
[database]
url = postgres:///db_name?host=/cloudsql/project:region:cloudsql_instance_name&user=db_user&password=db_pass
```

If port is needed, it can be added `&db_port=5432`

**Comment by joshuajung** [comment]
Is there a viable work-around for this issue? I'm also trying to connect to a Cloud SQL database from Google Cloud Run via a socket connection string and running into the `net.SplitHostPort failed` error. Thank you!

**Comment by gfrankliu** [comment]
The workaround is to create a symlink in your entrypoint script, and you can then set ENV GF_DATABASE_HOST to that symlink so the filename won't have colon anymore.

**Comment by gfrankliu** [comment]
I switched to use mysql db type of Cloud SQL for Grafana, which does NOT have this issue. The issue is only with Postgres driver.

**Comment by mgreenw** [comment]
Still hitting this issue & the symlink workaround isn't great. Would love if #29725 or similar is merged.

**Comment by bperun123** [comment]
From my terraform google_cloud_run_v2_service config:
```
env {
        name  = "GF_DATABASE_URL"
        value = "postgres:///grafana-db?host=/cloudsql/myproject-218021:europe-west1:pg-instance&user=myuser&password=${var.pg_myuser_password}"
}
```
Solved this issue.
Thanks  @gfrankliu !!!

**Comment by gfrankliu** [comment]
Glad it works! Can you open another ticket to make sure the value of "GF_DATABASE_URL" is somewhat redacted in the logs since password is in the string, just like what grafana did for GF_DATABASE_PASSWORD?
