### ISSUE TITLE
Round axis units

### ISSUE THREAD

**Issue by henry-spanka** [grafana/grafana#2969]
Hey, is it possible to not only round the legend and the tooltip to like 2 decimals, but also the Axis units?

Please take a look at the screenshot. It's okay if it just says 512.00MB like in the tooltip.
Data is in bytes and unit also set to bytes.

![Example Screenshot](https://cloud.githubusercontent.com/assets/10375269/10559211/66e07e20-74eb-11e5-9bf1-a2f4d2b13128.png)

**Comment by torkelo** [comment]
The axis units are dynamic, there is currently an edge case when that automatic decimals can cause issues, you can fix that by adding more series or setting grid min/max. Is the combo when you have a single series and y-axis min/max set to auto. There is already an issue to improve this edge case (and for overriding the auto decimals)
