### ISSUE TITLE
Tooltip/Hint (left upper corner of graph) visible in kiosk or kiosk=tv mode

### ISSUE THREAD

**Issue by raphaelgeng** [grafana/grafana#29702]
**What would you like to be added**:
It would be very good to see the graph description/hint/tooltip also in the kiosk or kisok=tv mode. 

**Why is this needed**:
This is in my opinion the viewer mode and gives the graph designer/creator the possibility to provide a explination for the graph/view.

Thank you very much!

Best Ragard
Raphael

**Comment by torkelo** [comment]
duplicate of #27099
