### ISSUE TITLE
Elasticsearch: Refactor ID generation logic

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#29713]
**What would you like to be added**:
follow up of https://github.com/grafana/grafana/pull/29652
Find a better way to generate (and assign) IDs to metrics and buckets aggregations in the elasticsearch datasource.

**Why is this needed**:
There are a few places where we assign default ids for newly created metric and bucket aggregation. These IDs should all depend on what is in the current query rather than having naive defaults as we do now as the current solution might lead to IDs overlapping each other and breaking the parsing logic. Ideally, the only place where default IDs will be hardcoded should be when handling the init action when generating a new query.

**Comment by matyax** [comment]
@Elfo404 Hi! Do you think we should work on this one?
