### ISSUE TITLE
Dashboard: Save dashboard not visible after making a dashboard editable

### ISSUE THREAD

**Issue by DenysBez** [grafana/grafana#29719]
**What happened**:
1. Step: Navigate to dashboard settings, General Tab, Editable turn off, Click Save Dashboard. Everything works as expected
2. Step: Navigate to dashboard settings, General Tab, click Make Editable, Click Save Dashboard. 

**What you expected to happen**:
I expect to see Save Dashboard button and be able to update existed dashboard and make it editable since I have all permissions for that. However, only Save As... button present. When I click Save As... , it shows the name of dashboard with Copy postfix. When I delete postfix and try to save, it fails with the message "A dashboard or a folder with the same name already exists".  

**Environment**:
- Grafana version: Grafana v7.3.4 (14c494085e)
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
think we can fix this as part of https://github.com/grafana/grafana/pull/27561

A temporary workaround is to exit dashboard settings mode and save it from there or go back to dashboard settings then it will work

**Comment by dprokop** [comment]
@DenysBez We are migrating the dashboard settings to react currently and we gonna address this issue with that work. I'm closing this issue and thanks a lot for your contribution!
