### ISSUE TITLE
Hide panel depending on the value of selected variable in Grafana

### ISSUE THREAD

**Issue by selsabil94** [grafana/grafana#29712]
**What would you like to be added**:
Hide some panel by specific value of a variable. Accordingly to selected value, specific panel is supposed to appear on the dashboard. In other words, if selected variable is not equal to some value, the pannel should be hidden.

**Why is this needed**:
Using repeat panel option can't be the solution because it just dynamically creates new panels. So actually it is not possible to do so.

**Comment by peterholmberg** [comment]
Similar to https://github.com/grafana/grafana/issues/4470
