### ISSUE TITLE
non-AWS S3 access BUG or Issue

### ISSUE THREAD

**Issue by IamAliBaba** [grafana/grafana#29716]
Hi ,
We have non-AWS S3 and having issue with ImageUploader .

our S3 **path_style_access**  is   **https://s3.xxxxxxx.com/bucket/key  not https://bucket.s3.xxxxxxx.com/key** .

I have this configuration on grafana.ini

[external_image_storage.s3]
endpoint = https://s3.XXXXXX.com
path_style_access = https://s3.XXXXX.com/BUCKET/KEY
bucket = XX-grafana-bucket
region = us
;path =
access_key = XXXXX
secret_key = XXXXX

i changed **path_style_access** to our custom but it still trying to connect to this one ` **https://bucket.s3.xxxxxxx.com/key**

LOG:

t=2020-12-09T07:16:37-0500 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=7 error="RequestError: send request failed\ncaused by: Put \"**https://xxx-grafana-bucket.s3.xxxxxx.com/gSvYnzqm8MDUnpMyIk7X.png**\": x509: certificate is valid for *.xxxxxxxx.com, xxxxxxxx.com, not xx-grafana-bucket.s3.xxxxxxx.com"

Seems BUG.

Thanks.

**Comment by papagian** [comment]
`path_style_access ` is what we pass to `S3ForcePathStyle` which expect [boolean](https://github.com/grafana/grafana/blob/f326b79cc1ebded6a33e54ed23d82e320473620e/pkg/components/imguploader/s3uploader.go#L68).
According to the aws-sdk [docs](https://docs.aws.amazon.com/sdk-for-go/api/service/s3/s3manager/#GetBucketRegion):
> This is not compatible with Amazon S3's FIPS endpoints. To override this behavior to use Virtual Host style addressing, provide a functional option that will set the Request's Config.S3ForcePathStyle to aws.Bool(false).

So can you try changing `path_style_access` to false in your configuration and check if this resolves the problem?

**Comment by IamAliBaba** [comment]
[external_image_storage.s3]
endpoint = https://s3.xxx.com
path_style_access = false
##https://s3.xxxxx.com/BUCKET/KEY
bucket = bip-grafana-bucket
region = us
;path =
access_key = xxxxxx
secret_key = xxxxx

t=2020-12-16T04:30:22-0500 lvl=dbug msg="calling remote rendering service" logger=rendering renderer=http url="http://hub.xxxxxx.local:8081/render?deviceScaleFactor=1.000000&domain=dash.xxxxxx.com&encoding=&height=500&renderKey=0DvR4fNZqJsv62FO8gtp52LFyhBIn8LO&timeout=15&timezone=&url=https%3A%2F%2Fdash.bipmedia.com%2Fd-solo%2Fcv4pve-metrics-alert%2Fbip-servers-alerts%3ForgId%3D1%26panelId%3D59%26render%3D1&width=1000"
t=2020-12-16T04:30:26-0500 lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=26 error="RequestError: send request failed\ncaused by: Put \"https://xxxx-grafana-bucket.s3.xxxx.com/33vnEU4ItigGvxB2skaT.png\": x509: certificate is valid for *.xxxxx.com, xxxxx.com, not xxxxx-grafana-bucket.s3.xxxxxx.com"

After changing it to false , was the same issue.

root@dash:~# grafana-server  -v
Version 7.3.4 (commit: 14c494085e, branch: HEAD)

**Comment by papagian** [comment]
According to the [grafana docs](https://grafana.com/docs/grafana/latest/administration/configuration/#external_image_storages3):
> path_style_access
Set this to true to force path-style addressing in S3 requests, i.e., http://s3.amazonaws.com/BUCKET/KEY, instead of the default, which is virtual hosted bucket addressing when possible (http://BUCKET.s3.amazonaws.com/KEY)

which is in accordance with the AWS [docs](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Config).

So I think for your path style addressing model like yours this should be set to true.
Note also that in the error you get the request is following the virtual hosted addressing: `https://xxxx-grafana-bucket.s3.xxxx.com/33vnEU4ItigGvxB2skaT.png` (the bucket is part of the domain).

**Comment by IamAliBaba** [comment]
thank you , changing it to True worked.

Can you please update Grafana docs ?

**Comment by wbrowne** [comment]
Glad the issue was solved @IamAliBaba - I will therefore close this. 

The docs are actually already up to date (see https://github.com/grafana/grafana/issues/29716#issuecomment-748463066) - I think there just may have been some confusion over the issue in the beginning.

**Comment by IamAliBaba** [comment]
this part is confusing 
![image](https://user-images.githubusercontent.com/26478599/102769650-639b1880-439c-11eb-893a-a873eacac285.png)
