### ISSUE TITLE
char '-' in field value cannot be fetched in templating

### ISSUE THREAD

**Issue by starkDbl07** [grafana/grafana#2972]
I have host entries consisting of '-' characters. Using Tempting with following query throws error and cannot fetch data.

__show tag values from "disk.disk_octets.read" with key = "instance" where host = '$server'__

Failed to run query for variable values: InfluxDB Error Response: error parsing query: found \-, expected identifier, string, number, bool at line 1, char 89

How can I escape the '-' char in field values or is there any other solution to this?

**Comment by torkelo** [comment]
Can you inspect the raw query Grafana sends (chrome dev tools network tab).  No need to escape as it is already enclosed in string quotes.

**Comment by starkDbl07** [comment]
Chrome Network Tab:

__https://<grafanaserver>:3000/api/datasources/proxy/8/query?epoch=ms&q=show+tag+values+from+%22disk.disk_octets.read%22+with+key+%3D+%22instance%22+where+host+%3D+%27influx%5C-02%27__



Influxdb Log:

__[http] 2015/10/19 09:51:13 202.79.32.184 - admin [19/Oct/2015:09:51:13 +0545] GET /query?db=server&epoch=ms&q=show+tag+values+from+%22disk.disk_octets.read%22+with+key+%3D+%22instance%22+where+host+%3D+%27influx%5C-02%27 HTTP/1.1 400 116 - Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.71 Safari/537.36 bcd591a2-7616-11e5-abe1-000000000000 1.150771ms__



The problem is solved if I remove the __%5C__ before the '-' manually in the URL:
https://grafana.wlink.com.np:3000/api/datasources/proxy/8/query?epoch=ms&q=show+tag+values+from+%22disk.disk_octets.read%22+with+key+%3D+%22instance%22+where+host+%3D+%27influx-02%27

So, in my opinion the problem is addition of '\' (%5C) for escaping '-' in the URL.

**Comment by starkDbl07** [comment]
how can i mitigate this?

**Comment by torkelo** [comment]
use a regex operator in your influxdb query, its not ideal but currently the templating system escapes the template variable value so you can use it in a influxdb regex operator condition

**Comment by torkelo** [comment]
will close in favor of this issue that aims to solve the root cause of this problem, https://github.com/grafana/grafana/issues/2918
