### ISSUE TITLE
Disable query button has no effect on Flux queries

### ISSUE THREAD

**Issue by DragonQ** [grafana/grafana#29731]
**What happened**: Disable query button has no effect on Flux queries.

**What you expected to happen**: Disable query button should disable the query.

**How to reproduce it (as minimally and precisely as possible)**: Click disable query button on any query.

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: InfluxDB 2.0.1
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10, Firefox 83.0
- Grafana plugins: Only the default ones
- Others: N/A

![Disabled query](https://user-images.githubusercontent.com/3251396/101671247-25246600-3a4c-11eb-8b7c-85e0c937f499.png)

**Comment by buwangchuxinlijing** [comment]
I had the same problem：
![Uploading BQ63PS6`YNX]OJ$OIZIH0GU.png…]()

**Comment by gabor** [comment]
fixed in https://github.com/grafana/grafana/pull/31324
