### ISSUE TITLE
Testcase for grafana is failing

### ISSUE THREAD

**Issue by ravisalamani** [grafana/grafana#2976]
I have built grafana from source for ubuntu 15.04 ppc64le.
When I try to run testcase for grafanna I am getting following error.
<pre>
.[grafana]$ go run build.go test
Version: 2.5.0-pre1, Linux Version: 2.5.0, Package Iteration: pre1
GOPATH=/home/test/src/github.com/grafana/grafana/Godeps/_workspace:/home/test
go test -short -timeout 60s ./pkg/...
# github.com/grafana/grafana/pkg/middleware
pkg/middleware/middleware_test.go:194:8: error: âcreateUserCmdâ declared and not used
    var createUserCmd *m.CreateUserCommand
        ^
ok      github.com/grafana/grafana/pkg/api      0.129s
?       github.com/grafana/grafana/pkg/api/cloudwatch   [no test files]
?       github.com/grafana/grafana/pkg/api/dtos [no test files]
?       github.com/grafana/grafana/pkg/api/static       [no test files]
ok      github.com/grafana/grafana/pkg/bus      0.076s
?       github.com/grafana/grafana/pkg/cmd      [no test files]
ok      github.com/grafana/grafana/pkg/components/apikeygen     0.256s
ok      github.com/grafana/grafana/pkg/components/renderer      0.114s
ok      github.com/grafana/grafana/pkg/events   0.069s
?       github.com/grafana/grafana/pkg/log      [no test files]
ok      github.com/grafana/grafana/pkg/login    0.161s
?       github.com/grafana/grafana/pkg/metrics  [no test files]
FAIL    github.com/grafana/grafana/pkg/middleware [build failed]
ok      github.com/grafana/grafana/pkg/models   0.161s
ok      github.com/grafana/grafana/pkg/plugins  0.268s
?       github.com/grafana/grafana/pkg/services/eventpublisher  [no test files]
ok      github.com/grafana/grafana/pkg/services/notifications   0.136s
ok      github.com/grafana/grafana/pkg/services/search  0.191s
ok      github.com/grafana/grafana/pkg/services/sqlstore        1.044s
ok      github.com/grafana/grafana/pkg/services/sqlstore/migrations     0.137s
?       github.com/grafana/grafana/pkg/services/sqlstore/migrator       [no test files]
?       github.com/grafana/grafana/pkg/services/sqlstore/sqlutil        [no test files]
ok      github.com/grafana/grafana/pkg/setting  0.180s
?       github.com/grafana/grafana/pkg/social   [no test files]
ok      github.com/grafana/grafana/pkg/util     0.119s
exit status 2
exit status 1
</pre>

**Comment by torkelo** [comment]
what version of Go are you using? It seems to work for me locally and on circleci

**Comment by ravisalamani** [comment]
$ go version
go version go1.4.2 gccgo (GCC) 6.0.0 20150511 (experimental) linux/ppc64le

can you please look into it

**Comment by MelGHub** [comment]
@ravisalamani : Have you been able to complete the grafana build on ppc64le?
I followed these steps-->http://docs.grafana.org/project/building_from_source/
however when I run the "grunt" , I get an error as follow:
Version 3.0.2
Loading "Gruntfile.js" tasks...ERROR
>> Error: Cannot find module 'brace-expansion'
Warning: Task "default" not found. Use --force to continue.

Aborted due to warnings.

Looking at the Gruntfile.js file,  it is only for windows?
