### ISSUE TITLE
Allow easy configuration of data sources via configuration management tools

### ISSUE THREAD

**Issue by nohn** [grafana/grafana#2977]
Grafana 1.9 allowed configuration of data sources via configuration management tools like Puppet as described on http://docs.grafana.org/v1.9/installation/ by manipulating textual configuration files.

Grafana 2.1 lacks such an easy way or is missing an appropriate documentation, instead documentation only tells how to configure data sources via the GUI.

**Comment by torkelo** [comment]
I know 2.x made this more difficult, originally I wanted a config option as well (still do), but almost all puppet / chef / etc recipes have been able to define data sources using the HTTP api.

**Comment by kartiksomani** [comment]
Has this feature been added in 2.9+ ? It would be great to have data sources added using json or ini.

**Comment by mtanda** [comment]
Grafana 5.x support datasource provisioning. Can close this.
