### ISSUE TITLE
Docs: Missing steps in Azure AD app roles documentation

### ISSUE THREAD

**Issue by mjiderhamn** [grafana/grafana#29783]
**What happened**:

The instructions at https://grafana.com/docs/grafana/latest/auth/azuread/ are missing a few steps to make the Application roles visible to Grafana.

**What you expected to happen**:

1. On the App registration, "Expose an API" tab, click "Set" after "Application ID URI" and set a URI (such as the default)
2. Staying on that tab, click "Add a scope" to add a custom scope. Copy the scope URI for later user in grafana.ini
3. Go to API permissions tab. Click "Add a permission" and then the "My APIs" tab, select your Application, "Delegated permissions", check your custom scope created above and click "Add permissions". If this option is not available, wait a few minutes after adding the custom scope.
4. In grafana.ini, `[auth.azuread]` section, `scopes` add the URI of the scope we created in the second step.

**Comment by hugohaggmark** [comment]
Thank you for reporting this @mjiderhamn, any chance that you could open a PR that fixes this?

**Comment by achatterjee-grafana** [comment]
Hi Josh@joshhunt, would you take a look at this when you have a moment? If you let me know what information is potentially missing and need to get added, we can work on this together. Thanks for your help!

**Comment by joshhunt** [comment]
This one is actually not related to the Azure Monitor data source, but rather improving the documentation for using Azure AD OAuth as an auth provider for Grafana as a whole https://grafana.com/docs/grafana/latest/auth/azuread/

**Comment by achatterjee-grafana** [comment]
We have updated the https://grafana.com/docs/grafana/latest/auth/azuread/ topic recently. 

Closing.
