### ISSUE TITLE
Bar Gauge: Title is not shown for data with one result/label/legend

### ISSUE THREAD

**Issue by XooR** [grafana/grafana#29784]
Grafana 7.3.4 have this bug and also 7.3.5 where dirty fix doesn't work.

To reproduce it you need to make `Bar Gauge` panel and to set it to **instant** some Prometheus query like:

```
topk(1, irate(node_disk_io_time_seconds_total{instance=~"$node:$port"}[5m]))
```

In Legend field to type: `Disk Utilization /dev/{{ device }}`

**What happened**:

It doesn't show in title what we typed in Legend

**What you expected to happen**:

That it's shown with template string replaced with it's values.

In 7.3.4 it was possible to type random string in "Field", "Display name" and it would show it in Title of that panel as specified in "Legend" even though it should have shown what we specified in "Field"->"Display name". With 7.3.5 version that hack is no longer possible.

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: Prometheus  2.18.1
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome/Firefox

Example screenshot:
![image](https://user-images.githubusercontent.com/120429/101934715-42893980-3bde-11eb-8f10-657c374816db.png)

With hack which is possible on version 7.3.4 and doesn't work on 7.3.5:
![image](https://user-images.githubusercontent.com/120429/101934850-75cbc880-3bde-11eb-994e-c9e618e87a83.png)

**Comment by hugohaggmark** [comment]
Thank you for reporting this @XooR , confirmed on Grafana Play 
https://play.grafana.org/d/a9fgLx1Gz/new-dashboard-copybar-gauge-title-is-not-shown-for-instant-queries-29784?orgId=1

Doesn't seem to be Prometheus specific, I added Bar Gauge with a Graphite query in the Grafana Play dashboard above and same result. Seem to relate to the number of rows we're showing, this might be by design so this issue might be transformed into a feature request instead. I'll keep you posted.

**Comment by torkelo** [comment]
This is by design, change the text mode to name and value to always show legend (name) even for single series results

**Comment by torkelo** [comment]
Ah for bar gauge there is no text mode , but you can set display name in field tab to have the same effect

**Comment by kustodian** [comment]
It doesn't support variable substitution, so it's not the same effect.

![image](https://user-images.githubusercontent.com/1949229/102051214-7d5cbe80-3de4-11eb-8350-61ddc54bdca8.png)

**Comment by torkelo** [comment]
you  can enter  ${__series.name}  in the display name field to use the series name you defined in the Prometheus legend

**Comment by kustodian** [comment]
Is this the official way of how this should be done, or are you planning to make some changes in the future? Also, it would be nice if this `${__series}` variable is documented somehow as a tooltip or something.
