### ISSUE TITLE
InfluxDB: use $interval in as general template variable (in title for example)

### ISSUE THREAD

**Issue by svetomir** [grafana/grafana#2978]
Hi,

Is it possible to show what $interval is set by grafana itself (automatically) in the graph title?

Something like on the picture bellow:
![image](https://cloud.githubusercontent.com/assets/6276860/10578404/3f36d986-7672-11e5-8c50-577a484630f5.png)

If it is not possible right now, it would be a  nice option to have in the future.

Thanks,
Svetomir

P.S. I couldn't find similar issue, so I'm sorry in case I reopened...

**Comment by torkelo** [comment]
not right now as the $interval is not a real template variable. You can work around this right now (not ideal), by creating a new template variable (template variable type interval), specify how many interval steps  (points) you want and use that in the influxdb query

**Comment by svetomir** [comment]
Hi,

I've been using workaround so far, but as you said it is not ideal.

Lots of my users gets confused with it and most of them asked that graph titles contain information like: 
<graph_name (sum by 5mins)> or <graph_name (mean by 1hr)>
This is hard to workaround right now if you have such multiple graphs on the same dashboard.
Therefore, it would be great if $interval value can be accessed and read per each graph.

Thanks a lot for the reply, and I hope you could make this feature available in the future.

Regards,

Svetomir

**Comment by RKelln** [comment]
:+1:   
It could just be an additional display option (shown after the title) something like the relative time adjustment.

**Comment by francisdb** [comment]
A more general issue for this: https://github.com/grafana/grafana/issues/3567

**Comment by aocenas** [comment]
This seems as a more generic issue not only for influx and as there already is such issue #3567 I am closing this as duplicate.
