### ISSUE TITLE
Incorrect display of bigint values (issue with alternative solution)

### ISSUE THREAD

**Issue by pihomeserver** [grafana/grafana#29791]
**What happened**:
when i perform a request on my DB (postgresql) on a column that stores bigint (defineds as nt8 or string), the displayed value is incorrect (+1 or -1 of the real value, on a random basis)

Here is the select in the database with correct values
<img width="425" alt="Capture d’écran 2020-12-09 à 14 06 27" src="https://user-images.githubusercontent.com/3817578/101979805-89b80e80-3c60-11eb-85a2-a5d288e5f695.png">

Here is the same result displayed in a table panel
<img width="981" alt="Capture d’écran 2020-12-09 à 14 06 48" src="https://user-images.githubusercontent.com/3817578/101979806-8ae93b80-3c60-11eb-8225-443d0d6d95c9.png">

**What you expected to happen**:
The value stored should be the one displayed in the table

**How to reproduce it (as minimally and precisely as possible)**:
Define a column as int8 or string in any table
In that column store a bigint value like : 17869259090142773
Request the value from grafana. The displayed value will be 17869259090142772

You can also open the browser console and execute the command parseInt(17869259090142773)
It will display the incorrect value

**Anything else we need to know?**:
**To solve the issue**, i added an override on the column, with a unit set to string. Then the displayed value is correct

**Environment**:
- Grafana version: v7.3.3 (2489dc4d3a)
- Data source type & version: Postgresql 13.1 in the official container
- OS Grafana is installed on: Running in a docker container (official one) in a Linux 4.19.0-13-amd64 #1 SMP Debian 4.19.160-2 (2020-11-28) x86_64 virtual machine
- User OS & Browser: Mac OS Big Sur 11.0.1 and Brave Version 1.17.75 Chromium: 87.0.4280.88 (Build officiel) (x86_64)
- Grafana plugins: Official ones + Boom Table (v13) + Dynamic Image Panel
- Others:

**Comment by hugohaggmark** [comment]
/ duplicate #13451
