### ISSUE TITLE
Dashboard solo (i.e. embed sharing) returning 404

### ISSUE THREAD

**Issue by doganyazar** [grafana/grafana#2979]
Share Panel-> Embed 
The given link in the iframe returns 404 with the correct payload. 

Example from the play.grafana.org
<iframe src="http://play.grafana.org/dashboard-solo/db/graphite-carbon-metrics?panelId=1&fullscreen&from=1445242814320&to=1445264414320" width="450" height="200" frameborder="0"></iframe>

So if you click the link, it loads the correct payload but 404 is returned rather than 200
http://play.grafana.org/dashboard-solo/db/graphite-carbon-metrics?panelId=1&fullscreen&from=1445242814320&to=1445264414320

```
$ curl -i "http://play.grafana.org/dashboard-solo/db/graphite-carbon-metrics?panelId=1&fullscreen&from=1445242814320&to=1445264414320"
HTTP/1.1 404 Not Found
Server: nginx
Date: Mon, 19 Oct 2015 14:23:22 GMT
Content-Type: text/html; charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Set-Cookie: grafana_sess=37930a86de319657; Path=/; HttpOnly

<!DOCTYPE html>
....
```

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master
