### ISSUE TITLE
If you're seeing this Grafana has failed to load its application files

### ISSUE THREAD

**Issue by yonglezhu** [grafana/grafana#29790]
I just download grafana-7.3.5.linux-amd64.tar.gz，then
tar xf grafana-7.3.5.linux-amd64.tar.gz
cd grafana-7.3.5
./bin/grafana-server web

then vist http://ip:3000/ ，I see the error message:If you're seeing this Grafana has failed to load its application files.
I didn't modify the config file ,nor use any reserve proxy either

grafana-server 7.3.5 on centos 7.6 x64
browser: ie 11 on windows server 2012R2 x64

**Comment by papagian** [comment]
Thank you for reporting this.
I'm unable to replicate it.
Can you load grafana successfully from the centos where it's running the server?
Also, what happens if you try accessing grafana from the windows machine using a different browser. 
Finally, the IP of the centos machine is public or private?

**Comment by yonglezhu** [comment]
> Thank you for reporting this.
> I'm unable to replicate it.
> Can you load grafana successfully from the centos where it's running the server?
> Also, what happens if you try accessing grafana from the windows machine using a different browser.
> Finally, the IP of the centos machine is public or private?

yes，chrome is ok

**Comment by papagian** [comment]
thank you for your reply;
I'm closing it because Internet Explorer 11 [is only fully supported](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers) in Grafana versions prior v6.0.
