### ISSUE TITLE
The moment user selects **Type**  dropdown value as **system** , the variables screen is getting closed automatically

### ISSUE THREAD

**Issue by sunnygadumadeinvizag** [grafana/grafana#29798]
**What happened:**

When user opens any dashboard with existing template variables, on the template variables screen, the moment user selects **Type**  dropdown value as **system** , the variables screen is getting closed automatically.

What you expected to happen: The moment when user selects **Type**  dropdown value as **system**  user should be able to stay on the variables page.

How to reproduce it (as minimally and precisely as possible): 
1) Go to https://play.grafana.org/dashboards
2) Open **Prometheus - Demo Dashboard** dashboard
3) Click on "Settings" icon
4) Select "Variables" screen
5) Select **node** variable
6) Select **Type**  dropdown value as **system**

After step-6, "node" variable screen is getting closed automatically without even clicking on "Update" button.

Anything else we need to know?: It is happening in grafana 7.2 version as well

Environment: play.grafana.org

Grafana version:  from Grafana v7.2.0
Data source type & version:
OS Grafana is installed on: It hapeens in play.grafana as well
User OS & Browser:
Grafana plugins:
Others:

**Comment by hugohaggmark** [comment]
Hi @sunnygadumadeinvizag and thank you for reporting this. This issue was fixed in #29178 and will be released in Grafana v7.4.0. If you'd like to try it out you can try out the lastest from master.
