### ISSUE TITLE
Documentation: Logs Panel Page Has Missing link to Log Levels.

### ISSUE THREAD

**Issue by STEELBADGE** [grafana/grafana#29799]
**What happened**:

When I click the link for ``See supported log levels and mappings of log level abbreviation and expressions`` in the Logs Panel doc it gives me a 404.

**What you expected to happen**:

It should take me to the ``See supported log levels and mappings of log level abbreviation and expressions`` page if it still exists.

**How to reproduce it (as minimally and precisely as possible)**:

https://grafana.com/docs/grafana/latest/panels/visualizations/explore/#log-level/

From https://grafana.com/docs/grafana/latest/panels/visualizations/logs-panel/ the *Log Panel* section.

**Comment by hugohaggmark** [comment]
Thank you for reporting this @STEELBADGE.

Change needs to be done in https://github.com/grafana/grafana/blob/master/docs/sources/panels/visualizations/logs-panel.md for anyone that wants to contribute. Thank you
