### ISSUE TITLE
Plugins: Be able to reload data sources

### ISSUE THREAD

**Issue by joanlopez** [grafana/grafana#29809]
**What would you like to be added**:

Add support to reload data sources from the plugin's code.

**Why is this needed**:

Currently, you can create new data sources from plugin's code (e.g. performing HTTP requests to the Grafana API). 
However, as data sources are being fetched on the initial load, you need to somehow force the data sources to be reloaded, otherwise the new ones created through the API calls won't appear into the data sources lists.

**Additional information**:

Until v7.3.x you can force that reload by running a similar code to:
https://github.com/grafana/grafana/blob/v7.3.5/public/app/features/datasources/state/actions.ts#L211

However, that workaround won't be compatible with v7.4.x due to the `DataSourceSrv` changes.
So, we definitely need a new way to perform that data sources reload.

**Proposal**:

As discussed with @torkelo, the proposed way to achieve those reloads would be to update Grafana core, add `reload` function to `DataSourceSrv` that calls `/api/frontend/settings` and updates its internal state.

**Comment by torkelo** [comment]
Making this part of https://github.com/grafana/grafana/issues/30728
