### ISSUE TITLE
Escaping Lucene special characters doesn't work as it should

### ISSUE THREAD

**Issue by volter** [grafana/grafana#2981]
https://lucene.apache.org/core/2_9_4/queryparsersyntax.html#Escaping%20Special%20Characters

Special characters are escaped by backslashes.

A search for referrer:http\\:* should translate to "query": "referrer:http\\\\:*". However, in Grafana it translates to "query":"referrer:http\\:*", which is invalid syntax.

**Comment by volter** [comment]
And I lost all my backslashes!

**Comment by torkelo** [comment]
ok, so close?

**Comment by volter** [comment]
No, I wasn't clear there, sorry! My report now looks like it should! I had to escape the backslashes there too! :D

**Comment by volter** [comment]
Please re-open the issue.

**Comment by torkelo** [comment]
The query box is for a lucene query, I cannot escape lucene query characters that would make it impossible to enter lucene queries! Or am I missunderstanding this???

**Comment by volter** [comment]
Imagine a field in an ES document that has the following content: Unix::Something

The colon is a special character in Lucene und must therefore be escaped, so that it is not interpreted as the delimiter between a field name and the field content expression. In Kibana, I would therefore write: Unix\\:\\:Something

However, this must be rewritten to Unix\\\\:\\\\:Something before it is submitted. I guess that's a JSON requirement.

**Comment by torkelo** [comment]
the problem was the json enconding was not applied to the lucene query portion
