### ISSUE TITLE
GraphNG: superfluous getConfig() calls during init

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#29817]
i placed a couple `console.log` calls into `UplotConfigBuilder.ts / getConfig()`. for a panel with 6 charts, getConfig() is called 12 times. during window resize i also see 6 calls (should it be 0 since we're bypassing re-init to call `.setSize()` directly?).

![image](https://user-images.githubusercontent.com/43234/102097947-2c50c880-3dec-11eb-90ee-5ec8e94ac195.png)

![image](https://user-images.githubusercontent.com/43234/102097847-0cb9a000-3dec-11eb-8667-79d973bc918b.png)

**Comment by torkelo** [comment]
adding this to https://github.com/grafana/grafana/issues/30564
