### ISSUE TITLE
Alerting: PagerDuty: add current state into the payload

### ISSUE THREAD

**Issue by Eraac** [grafana/grafana#29812]
**What would you like to be added**:

In the payload send to Pagerduty, add the information about the current state "alert", "ok", "no_data"

**Why is this needed**:

Our alerts are sent to PagerDuty and Slack

Actually when an alert is fired, in PagerDuty we can't see the difference between an alert which is really trigger or if the source return "no data". Grafana have these different states but not PagerDuty.

Slack -> Message are formatted with "[No Data]" prefix 
PagerDuty -> Someone on-call is notified (even at night), because we can't say the difference (between "alert" and "no data")

We don't want to disable "no data" state because is an useful information, but we don't want to wake up someone at night

In PagerDuty we can ignore or change the priority based on the payload with event rules. So the goal is to setup a event rule based on the state to ignore or set alert in low priority

**Comment by aknuds1** [comment]
Thanks, this looks pretty good so far, I will try to review it in depth soon.
