### ISSUE TITLE
Elastic: "parse_exception: Unparseable number" when testing alerts

### ISSUE THREAD

**Issue by keomabrun** [grafana/grafana#29826]
**What happened**:

Alert query does not return data.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

* create a graph with ElasticSearch as data source
* create an alert
* run "test"
* inspect query result
![image](https://user-images.githubusercontent.com/11633612/102120483-e4a95b80-3e42-11eb-887d-64e7714b5dda.png)

**Anything else we need to know?**:

This looks very much like https://github.com/grafana/grafana/issues/22014

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: ElasticSearch v7.7 (hosted on AWS)
- OS Grafana is installed on: Debian Buster
- User OS & Browser: Debian Buster
- Grafana plugins: None
- Others: None

**Comment by mrceyhun** [comment]
I'm also facing with same problem in alerting. I would like to add one detail to reproduce the problem, as a complement to @keomabrun 

- Time Field of ElasticSearch data source has "Long" type mapping in ElasticSearch. When it has "date" type mapping, I'm not getting this error.

**Comment by keomabrun** [comment]
Indeed I just checked and I do also use "Long" type on the mappings. This is actually an issue on my side that I'm going to fix.

**Comment by Elfo404** [comment]
https://github.com/grafana/grafana/pull/22173/ indeed fixed the very same issue when issuing query using the proxy, this also needs to be done in the backend.

a good starting point would be looking at 
https://github.com/grafana/grafana/blob/b79e61656ab4f5144d727d50df781f53d71fccf8/pkg/tsdb/elasticsearch/time_series_query.go#L186
