### ISSUE TITLE
CI: Improve Grafana offering at the GCP Marketplace 

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#29828]
**What would you like to be added**:

A new, improved Grafana image that can be distributed over the Google Cloud Platform Marketplace. 

There is already a [Grafana image](https://console.cloud.google.com/marketplace/product/click-to-deploy-images/grafana?filter=category:monitoring) available at GCP. Included in this offer is a debian vm with grafana installed on in. Basic auth with randomly generated password is used for access to Grafana. The Grafana version used in this image is usually lagging behind since updates are handled manually. This image, and the deployment of it, is handled by Google. Their deployment scripts can be found here:
https://github.com/GoogleCloudPlatforhttps://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/vm#google-click-to-deploy-imagesm/click-to-deploy/tree/master/vm/chef/cookbooks/grafana
https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/vm/packer/templates/grafana
https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/vm/tests/solutions/spec/grafana

**Suggested solution**
The new marketplace offering should include features that makes it quick and easy to get started with Cloud Monitoring in Grafana. It should also automate the relase process so that every time a new major or minor version of Grafana is released, it's being pushed to the GCP Marketplace. 

The new image should have the following features: 
* Grafana installed
...and using provisioning we should enable:
* TLS and HTTPS
* Google OAuth
 * The Cloud Monitoring datasource. It should be configured to use [GCE Auth](https://grafana.com/docs/grafana/latest/datasources/cloudmonitoring/#configure-the-data-source-with-provisioning).
* Cloud Monitoring related dashboards. All of these dashboards are not yet created, but will be within the next couple of weeks

[This](https://cloud.google.com/marketplace/docs/partners/vm) guide walks through the steps necessary to create and distribute a marketplace offering. Please note that we already an account and projects necessary to get started (talk to Erik about this). 

In a nutshell one needs to create a VM, install the features mentioned above, delete the VM but keeping the boot disk, clean up the disk and create a licensed image using the preserved disk. Then a deployment package needs to be created. It's very important that once a vm is created from the Marketplace offering image, it must be [setup to run as service account](https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#using). Ideally this service account is defined by the user upon launching of the instance (in the wizard) so that they can pick a service account that they know is granted access to projects that have metric data. This is related to GCE Auth that is mentioned earlier in this document. 

Still to investigate:
* How to manage deployment packages? It seems like google uses [Chef](https://github.com/GoogleCloudPlatform/click-to-deploy/tree/master/vm#google-click-to-deploy-images)
* How to setup the instance to run as service account   

At last, as soon as this new marketplace offering is in place we need to contact Google and ask them to remove the existing offer.

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can’t see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
