### ISSUE TITLE
InfluxDB: Reserved words not quoted

### ISSUE THREAD

**Issue by fatmcgav** [grafana/grafana#2983]
It appears that Grafana is not quoting some reserved InfluxDB words. 

Example here: https://github.com/influxdb/influxdb/issues/3787

Gist with further logs, dashboard and metric here: https://gist.github.com/fatmcgav/56eab3b31ce50207ac2a

**Comment by torkelo** [comment]
fixed in master and in 2.5 pre release builds (grafana.org/download/builds.html)
