### ISSUE TITLE
"Annotated Intervals": Allow interval selection by annotation-style query

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#2984]
Synopsis
=============
If "Interval Selection" is enabled for an annotation, then its widget will provide a drop-down which allows you to pick a start and, conditionally, an end time from the times of the matching annotations.

Details 
===============

### New options for annotations:

I've provided some suggested parameter names merely to simplify explanation. 

1. "Enable Interval Selection", (*interval_selection_enabled*) checkbox
   - When this is enabled, the following fields are revealed.
2. "Specific Start Time Query" (*starttime_query*) text field
   - If set, provides the query which will be used to populate the options in the "start-time" annotation drop-down. If unset, the query will be taken by default from the main annotation query.
3. "Specific End Time Query" (*endtime_query*) text field
   - If set, provides the query which will be used to populate the options in the "end-time" annotation drop-down. If unset, the query will be taken by default from the starttime_query, if set, or from the annotation query otherwise.
4. "Selection Constraint" (*interval_selection_constraint*) single select
   - "Limit to visible Interval" (*visible_annotations*)
   - "Unlimited" (*all_annotations*)
5. "End Time Selection Range" (*endtime_selection_range*) numeric field
   - If this is set to 0 (zero), the default, then start-time selection and end-time selection will have separate drop-downs, with the only qualifier to end-times being that they must start after the currently selected start time.
   - If this is set to 1, then end-time will be selected as the next matching annotation time *after* the selected start time, with no drop-down to override.
   - If this is set to non-zero, then the end-times will be selectable from a drop-down of N matching times after the selected start time, with the default.

Optional Scope
============
These are tangentially related ideas which might make sense as separate requests. They are included here to show some of the possibilities for enhanced workflow.

### Navigation
To support this capability, parameters from selected annotation intervals must be retained in the session, including how many end times were skipped over in the end selection. With this data, it would be very easy to provide backward and forward navigation over annotation spans. Specifically, if you selected a time of interest (C,E), then paginating left would take you to (B,D) and paginating right would take you to (D,F). This could make it trivial to navigate between named or annotated testing or measurement times.

### Active Annotation
In order to dynamically create different views or call out interesting contrasts, it would be helpful to allow insertion of custom annotations from the UI. This is, of course, out of scope for this ticket, but it is at least worth mentioning as a supporting idea.

### Expanded Selection
The drop-downs could manage internal pagination of possible times. For example, if the first option was "[ --prior events-- ]" or something similar, clicking it could cause the drop-down to refresh with said options. The same can done at the end of the option list with "[ --later events-- ]" or something similar.

**Comment by Dieterbe** [comment]
dup of #2985
