### ISSUE TITLE
AzureMonitor: rename sections to Metrics, Logs and App Insights

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#29847]
The current dropdown of options in the Azure Monitor data source has four entries:

![image](https://user-images.githubusercontent.com/434655/102225291-5935d600-3ee7-11eb-953f-0dd90ed996d8.png)

It is quite confusing for users and doesn't map well to the metaphors of the Grafana UI.

The proposal is to:
- Azure Monitor -> Metrics
- Azure Log Analytics -> Logs
- Application Insights -> Application Insights

**Comment by joshhunt** [comment]
Split out the request to merge Insights Analytics and Logs to new ticket https://github.com/grafana/grafana/issues/30184
