### ISSUE TITLE
QueryEditor: Middle mouse copy does not work

### ISSUE THREAD

**Issue by leahoswald** [grafana/grafana#29850]
**What happened**:
If I copy&paste a query in the query editor (data source = prometheus) from one query line to another I get an error like this: "_"1:14: parse error: unexpected character: '\\ufeff'"_". If I view the copied string in another editor (vim) it looks like this:

`label_replace<feff><feff><feff>(<feff><feff>node_systemd_unit_state<feff><feff>{<feff><feff><feff>state<feff><feff>=<feff><feff>"active"<feff><feff><feff>}<feff><feff><feff>,<feff><feff> "node"<feff><feff>,<feff><feff> "$<feff><feff>1<feff><feff>"<feff><feff>,<feff><feff> "instance"<feff><feff>,<feff><feff> "<feff><feff>(<feff><feff>node\\d+<feff><feff>)<feff><feff><feff>.<feff><feff>*"<feff><feff>)`

instead of:

> label_replace﻿(﻿node_systemd_unit_state﻿{﻿state﻿=﻿"active"﻿}﻿,﻿ "node"﻿,﻿ "$﻿1﻿"﻿,﻿ "instance"﻿,﻿ "﻿(﻿node\\d+﻿)﻿.﻿*"﻿)

But the extra characters are not displayed in the grafana query editor. So it isn't easy to fix.

**What you expected to happen**:
Don't copy these extra formatting? characters, so copy&past between query lines will working.

**How to reproduce it (as minimally and precisely as possible)**:
Copy a query from one query line to another with prometheus as data source.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.35
- Data source type & version: prometheus 2.22.0
- OS Grafana is installed on: Debian 10
- User OS & Browser: Archlinux Firefox 83

**Comment by jritter-secu** [comment]
I am having this issue as well. 
I am using Prometheus and Grafana to graph collectd information. My PromQL query works in Prometheus query editor UI, but not in grafana UI. When I type it into the Grafana query editor, versus copy-paste, the error goes away, but the data is still empty.

Query: sum(rate(collectd_processes_ps_cputime_syst_total{exported_instance="$SourceMachine"﻿,instance="10.10.10.10:9103",job="collectd",processes="myprocessname"}[1m]))

- Grafana version: 7.3.6
- Data source type & version: Prometheus 2.24.0
- OS Grafana and Prometheus is installed on: CentOS 7
- Grafana install method: via RPM from grafana repo, specifically 7.3.6-1
- User OS & Browser: MacOS 10.15.7, Chrome 87.0.4280.141

**Comment by shdubsh** [comment]
I am not able to get the same result with Ctrl+C and Ctrl+V, but it shows up using Select and Middle-Click.
One way to reproduce is to select the query from the Edit Panel of a Dashboard and middle-click it into a separate tab Explore view.

Grafana version: 7.1.3
Prometheus data source
User OS & Browser: Fedora 33 -- Chromium 87.0.4280.88

**Comment by leahoswald** [comment]
> I am not able to get the same result with Ctrl+C and Ctrl+V, but it shows up using Select and Middle-Click.

Right, I discovered that the other day too. That explains why it has "randomly" worked for me^^

**Comment by andir** [comment]
I've had that for years now. I just never bothered opening an issue because it seems to be the new industry practice to break middle-mouse-copy (all developers using Macs these days?). GitLab is also very good at breaking middle mouse copy in the gists equivalent.

**Comment by hawran** [comment]
Hi,
I can confirm the same issue for `Grafana v7.5.4 (NA)`:
1. `Ctrl-A` within `grafana` and `Ctrl-V` to `thanos`: `OK`.
2. `LeftMouse` selection within `grafana` and `MiddleMouse` to `thanos`: `Error executing query: 1:4: parse error: unexpected character inside braces: '\ufeff'`
3. `Ctrl-A` within `grafana eXplore Panel` and `Ctrl-V` in `grafana PromQL editor`: `"1:4: parse error: unexpected character inside braces: '\\ufeff'"`.
Copied from promql editor to vim: `up{<feff>namespace<feff>=<feff>"staging"<feff>, <feff>app<feff>=<feff>"prometheus"<feff>}`

```
Ubuntu 20.04.2 LTS
Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:87.0) Gecko/20100101 Firefox/87.0
```

**Comment by akosiaris** [comment]
I occasionally have this issue as well. Haven't really debugged it much but `U+FEFF` is the Byte Order Mark (BOM). For more see https://en.wikipedia.org/wiki/Byte_order_mark but the gist is: 

* it's not particularly useful in UTF-8 (aside from saying "hey, what follows is unicode", which can be accomplished other means too), 
* it's useful as the first character in a UTF-16 (and UTF-32 - padded with obligatory zeroes at the prefix - but UTF-32 is uncommon overall) stream in order to denote endianess.
* Pre Unicode 3.2, it was allowed to be interpreted as "zero-width non breaking space" when met at the middle of a data file/stream.

I can reproduce this in grafana 8.1.3 and a prometheus query editor window, but NOT an elasticsearch lucene query editor, a PostgreSQL query editor window (can't even copy from that for some reason) and a graphite query editor. So something specific to the prometheus plugin?

I have no idea why a middle click would add Byte Order Marks though.

**Comment by glintik** [comment]
Hello guys,

I've prepared a fix that removes byte order mark (BOM aka U+FEFF) symbol on copy and paste.

**Comment by cronolio** [comment]
docker 8.2.2  explore tab still with these <feff>

**Comment by glintik** [comment]
> docker 8.2.2 explore tab still with these

@cronolio Can you please describe detailed steps how to reproduce your case? I've just checked 8.2.2 and don't see BOM chars in clipboard anymore.

**Comment by cronolio** [comment]
debian 10 as a host
Docker version 20.10.7, build f0df350 not swarm mode
image: grafana/promtail:2.3.0
image: grafana/loki:2.3.0
image: grafana/grafana:8.2.2
i have created a gist here with configs related to logs https://gist.github.com/cronolio/2a15e6d1ffb82ca72cc03af2b1fa141d
in grafana loki added as data source (just url http://loki:3100)
so i go to grafana explore tab  like 127.0.0.1:3000/explore and i manually write a query for example `job="systemd",syslog_identifier="kernel"` and perform this query. after it i copy (with mouse right click and select "copy" in context menu) my query line and past it into nano text editor, there is not visible these `<feff>` but some glitches arroud "=" (required to press arrow key twice to move cursor). if i open this file with vi i see this `{<feff>job<feff>=<feff>"systemd"<feff>,<feff>syslog_identifier<feff>=<feff>"kernel"<feff>}`

**Comment by glintik** [comment]
> debian 10 as a host Docker version 20.10.7, build f0df350 not swarm mode image: grafana/promtail:2.3.0 image: grafana/loki:2.3.0 image: grafana/grafana:8.2.2 i have created a gist here with configs related to logs https://gist.github.com/cronolio/2a15e6d1ffb82ca72cc03af2b1fa141d in grafana loki added as data source (just url http://loki:3100) so i go to grafana explore tab like 127.0.0.1:3000/explore and i manually write a query for example `job="systemd",syslog_identifier="kernel"` and perform this query. after it i copy (with mouse right click and select "copy" in context menu) my query line and paste it into nano text editor, there is not visible these `<feff>` but some glitches arroud "=" (required to press arrow key twice to move cursor). if i open this file with vi i see this `{<feff>job<feff>=<feff>"systemd"<feff>,<feff>syslog_identifier<feff>=<feff>"kernel"<feff>}`

Thank you for details. What browser name and version?

**Comment by cronolio** [comment]
> 
> Thank you for details. What browser name and version?

firefox-esr | 78.15.0esr-1~deb11u1

**Comment by glintik** [comment]
@cronolio I didn't work for a long time with linux desktop environment and forgot that Middle Mouse Button doesn't use general clipboard. That's why my fix didn't touch Middle Mouse Button action. 
Unfortunately, copy-on-select and Middle Mouse Button can not be handled in a pretty way(read - without tricks).
Roots of this issue are in slate-react editor that used in Query input field. slate-react inserts BOMs(FEFF chars) for its internal use. That's why it's inserted into string when text is selected in Linux. I hope, slate-react will be replaced with proper good alternative some time. At this time, you can use Ctrl-C/V and right click menu.

**Comment by cronolio** [comment]
ctrl-v/c, shift-insert/ctrl-insert, middle mouse, right click context menu - doesn't matter `<feff>` is everywhere.

**Comment by cronolio** [comment]
@glintik your fix, this file clipboard.ts, is this happens on client side (in my case firefox), or it is something server side? in my firefox i have some additional settings for security reason, for example i have `dom.event.clipboardevents.enabled fasle` so web-site scripts can't modify my copy&paste

**Comment by glintik** [comment]
> @glintik your fix, this file clipboard.ts, is this happens on client side (in my case firefox), or it is something server side? in my firefox i have some additional settings for security reason, for example i have `dom.event.clipboardevents.enabled fasle` so web-site scripts can't modify my copy&paste

You are right, clipboard data modified in `clipboard.ts`:
```
      if (copiedText && clipEvent.clipboardData) {
        clipEvent.clipboardData.setData('Text', copiedText);
      }
```

**Comment by cronolio** [comment]
so, since grafana is the only one website where is such problems i don't going to enable `dom.event.clipboardevents.enabled` and will wait for real solutions - don't add these unprintable special control symbols into text field at all

**Comment by hawran** [comment]
> Hi, I can confirm the same issue for `Grafana v7.5.4 (NA)`:
> ...

Hi, still experiencing the same problem (Grafana `v8.2.5` (NA), thanos `v0.23.1`):

1. `Ctrl-A` within `grafana` and `Ctrl-V` to `thanos`: `OK`.
2. `LeftMouse` selection within `grafana` and `MiddleMouse` to `thanos`: `Error executing query: 1:4: parse error: unexpected character inside braces: '\ufeff'`

With `Use experimental editor` enabled you can see culprits (the red dots) within the expression:
![211126-154156 grafana-2-thanos MiddleMouse](https://user-images.githubusercontent.com/25924718/143597927-db7924f1-3bd2-4ca6-af4a-3f6678227474.png)

Well, not sure if it is grafana's problem.

**Comment by WesleyBlancoYuan** [comment]
Hi, with 8.0.6 I see similar things: not with paste, but when I type in query editor, I see these strange extra space, which makes typing really hard. Chrome Version 105.0.5195.102 (Official Build) (64-bit). 

When I press delete/backspace, I have to press multiple times, even I only typed one char. So actually I was deleting the added extra space.

**Comment by blessli** [comment]
> Hi, with 8.0.6 I see similar things: not with paste, but when I type in query editor, I see these strange extra space, which makes typing really hard. Chrome Version 105.0.5195.102 (Official Build) (64-bit). Queries don't work.
> 
> Only when I copy/paste query into Prometheus I can find out the spaces added; removing the spaces and copy/paste back to Grafana makes the query working again.
> 
> When I press delete/backspace, I have to press multiple times, even I only typed one char. So actually I was deleting the added extra space.

I also encountered this problem today. My solution is: 
write the prom statement on the prometheus web page, then click the execute button until it is successfully executed, and then paste this statement on a pannel of grafana
