### ISSUE TITLE
"Annotated Intervals": Allow interval selection by annotation-style query

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#2985]
# Synopsis

If "Interval Selection" is enabled for an annotation, then its widget will provide a drop-down which allows you to pick a start and, conditionally, an end time from the times of the matching annotations.
# Details 
### New options for annotations:

I've provided some suggested parameter names merely to simplify explanation. 
1. "Enable Interval Selection", (_interval_selection_enabled_) checkbox
   - When this is enabled, the following fields are revealed.
2. "Specific Start Time Query" (_starttime_query_) text field
   - If set, provides the query which will be used to populate the options in the "start-time" annotation drop-down. If unset, the query will be taken by default from the main annotation query.
3. "Specific End Time Query" (_endtime_query_) text field
   - If set, provides the query which will be used to populate the options in the "end-time" annotation drop-down. If unset, the query will be taken by default from the starttime_query, if set, or from the annotation query otherwise.
4. "Selection Constraint" (_interval_selection_constraint_) single select
   - "Limit to visible Interval" (_visible_annotations_)
   - "Unlimited" (_all_annotations_)
5. "End Time Selection Range" (_endtime_selection_range_) numeric field
   - If this is set to 0 (zero), the default, then start-time selection and end-time selection will have separate drop-downs, with the only qualifier to end-times being that they must start after the currently selected start time.
   - If this is set to 1, then end-time will be selected as the next matching annotation time _after_ the selected start time, with no drop-down to override.
   - If this is set to non-zero, then the end-times will be selectable from a drop-down of N matching times after the selected start time, with the default.
# Optional Scope

These are tangentially related ideas which might make sense as separate requests. They are included here to show some of the possibilities for enhanced workflow.
### Selected Interval Display Format

A simple way of selecting data from an annotation which can frame the current view would be helpful. By default, this could simply be the full annotation content.
### Navigation

To support this capability, parameters from selected annotation intervals must be retained in the session, including how many end times were skipped over in the end selection. With this data, it would be very easy to provide backward and forward navigation over annotation spans. Specifically, if you selected a time of interest (C,E), then paginating left would take you to (B,D) and paginating right would take you to (D,F). This could make it trivial to navigate between named or annotated testing or measurement times.
### Active Annotation

In order to dynamically create different views or call out interesting contrasts, it would be helpful to allow insertion of custom annotations from the UI.
### Expanded Selection

The drop-downs could manage internal pagination of possible times. For example, if the first option was "[ --prior events-- ]" or something similar, clicking it could cause the drop-down to refresh with said options. The same can done at the end of the option list with "[ --later events-- ]" or something similar.

**Comment by Dieterbe** [comment]
curious what kind of practical uses this would enable? do you have navigational problems that this would solve?

**Comment by jshook** [comment]
Yes, this would solve some navigational problems for me. I use grafana as a primary communication and analysis tool for a variety of detailed tests. Creating views into data that are scenario or configuration specific is currently tedious. I do parallel testing for direct *simultaneous* comparisons. However, this is not enough to support comparisons across time or scenario as well. I use both. For now, I spend lots of time micro-managing timelines and reference points.

I would rather emit metrics data that can automatically frame the measurement times by parameter. If this were possible, I would be able to automate much more of the overall process. For example, I could use "targetload=80" as a time selection option, whether interactively, or via API. That level of detail wasn't provided in the request above, but it should follow naturally.

**Comment by jshook** [comment]
In addition, this would ease communication among peers when sharing or discussing results. Specifying a time frame by name [ the content of an annotation that is configured for time selection ] is much more direct and meaningful. This is further enhanced by the possibility that the data was generated from the instrumented systems-- empirical by design.

Even in the case that annotations are added as conceptual reference points, it is still better than having to use decontextualized timestamps.

**Comment by torkelo** [comment]
i really struggle understand anything about this issue. Can you show some mock ups and some work flow images?

**Comment by jshook** [comment]
The basic gist of it is: "Allow selection of start and end time by annotation." I might provide some mock-ups at a later time.

**Comment by torkelo** [comment]
@jshook I think a better option for such a specific edge case scenario would be a have a scripted dashboard that queries your data source and builds a dashboard with links to dashboard with different time ranges for each test run

**Comment by jshook** [comment]
I try not to file requests for what I would consider edge cases. My wish is to use Grafana as a platform, and less like an API or toolkit as much as possible. Sure, scripting is necessary for automation. I'd just like to keep the necessary automation as lean as possible, with data-set and dashboard concerns in the right place. This is, no doubt, a power feature, but not out of the realm of usefulness for many users.

**Comment by torkelo** [comment]
@jshook I agree, but scripting or using the API to build dashboards are really great for more advanced edge cases, because it allows the core product to be more simple and not littered with very complex features like this. But if it gets a lot of +1 votes it could be interesting

**Comment by Dieterbe** [comment]
interestingly enough, i just found myself desiring something akin to this feature (tell me if i got it wrong)
basically, i have a script that runs a few benchmarks, and i have a corresponding dashboard to viz the data. i insert events into influxdb for the start of the benchmark script, and for each individual benchmark start and end.
it would be nice if the dashboard would have a from corresponding to the "script start" event (for which there is an annotation), and a to corresponding to the end of the last benchmark run event (for which there is an annotation). if the latter event doesn't exist yet (because perhaps you're looking at the dash while the tests are still ongoing) then it could use something sensible for to (like now).
the suggested UI elements here seem a bit overkill for my use, i would only need to set an annotation query for from and to, so that it can find the proper annotation that will set the from/to time.

**Comment by jshook** [comment]
You've described it exactly. My needs are basic as well, but the feature requests captures a bigger picture of what I wish for.

**Comment by rmoff** [comment]
+1 for the same use case described above - I am running capacity tests and have grafana providing multiple views on top of the results. I want a way to switch between the time period encompassing test <x> without having to manually enter the times (or zoom out / click & drag in). 

Currently I am storing the test start/end dates and displaying them as annotations - what I would love to be able to do is for grafana to understand the start/end as a time range that I can then select automatically. The big productivity killer at the moment is switching between test results - either reconfiguring the time parameters, or saving multiple copies of the dashboard with fixed times. 

![2015-11-27_13-22-27](https://cloud.githubusercontent.com/assets/3671582/11442092/3f2525cc-950a-11e5-957c-afe4333df449.png)

![2015-11-27_13-24-28](https://cloud.githubusercontent.com/assets/3671582/11442094/4304d44e-950a-11e5-9b7b-1fb0972b6b50.png)

In terms of interface it'd be either as part of the existing time picker as a dropdown menu within it (most logical, to me), or similar to the existing templating dropdown option.

**Comment by torkelo** [comment]
this is supported by region annotations (http://docs.grafana.org/reference/annotations/#adding-regions-events) ,

**Comment by Dieterbe** [comment]
How does that control the time range though ?

**Comment by torkelo** [comment]
Might have misunderstood this issue, re reading the issue description a couple of times as actually fail to understand it completely :)

**Comment by jshook** [comment]
The whole point of the issue is to set the current time range of the view from annotations of interesting events.

Suppose that you want to show someone some test results from test "A" by simply telling them "select the range annotation 'test results A' "

**Comment by torkelo** [comment]
it seems unrelated to the annotations feature, feels more like a "time range" selector that allows you to query a database for ranges.

**Comment by jshook** [comment]
It is directly related to tying the annotations feature to time range
selection. That's the whole idea.
