### ISSUE TITLE
API: Provide way to return non-dataframe response when using /api/datasources/proxy

### ISSUE THREAD

**Issue by indygriffiths** [grafana/grafana#29868]
**What would you like to be added**:

With the move around Grafana 7.2 to return Cloudwatch query data in Apache Arrow encoded dataframe format, this has broken our API integration that uses the [datasource proxy](https://grafana.com/docs/grafana/latest/http_api/data_source/#data-source-proxy-calls) endpoint to fetch data from Cloudwatch through Grafana as the `series` field is no longer populated. I wasn't able to find an appropriate changelog entry around the data structure of the response changing.

Might be a long shot, but it would be fantastic if this API endpoint for proxying calls, or just the `tsdb/query`, was able to return the old-style data (kinda like `toLegacyResponseData` does within `processDataframe.ts`) using some sort of parameter we can pass in.

**Why is this needed**:
In our case,  there doesn't appear to be any libraries in our language for the Apache Arrow format to be able to decode dataframes returned by this API endpoint, meaning we'll most likely have to re-architect our API integration around this new format

**Comment by hugohaggmark** [comment]
Hi @indygriffiths and thanks for taking the time to create this issue. Not sure this is something we're going to provide as `tsdb/query` is AFAIK for Grafana internal usage only.

**Comment by aknuds1** [comment]
I've discussed this with @torkelo and we won't be implementing legacy support for the time series format. We are open to supporting returning data frames as JSON though instead of the binary Arrow format, at some point in the future, on the other hand.
