### ISSUE TITLE
Supporting AWS Secrets Manager for Database passwords

### ISSUE THREAD

**Issue by aodhan-domhnaill** [grafana/grafana#29860]
**What would you like to be added**:

I would prefer to use AWS Secrets manager for database credentials do they can be [automatically rotated](https://aws.amazon.com/blogs/security/rotate-amazon-rds-database-credentials-automatically-with-aws-secrets-manager/)

Looks like we'd need to add AWS Secrets manager support into 

https://github.com/grafana/grafana/blob/ab078133bfe9771f06bd21712f7ad6f9113c8a61/pkg/models/datasource.go#L78-L80

That get's used in various places, for example [here](https://github.com/grafana/grafana/blob/a078e40238dc760d40071b4abcc236ba4f161a64/pkg/tsdb/postgres/postgres.go#L90)

**Why is this needed**:

Improve security on databases with non-static passwords

**Comment by aidan-plenert-macdonald** [comment]
Demo'ed what I was thinking in https://github.com/grafana/grafana/pull/29920. It appears that Grafana will retry failed DB connections, so it's just a matter of making sure connection strings are recreated dynamically.

**Comment by chaitan94** [comment]
Gently bumping this up :smile:! Any chance this feature will be added?

**Comment by chaitan94** [comment]
I came up with a workaround for this, using the HTTP API of Grafana to [update existing data sources](https://grafana.com/docs/grafana/latest/http_api/data_source/#update-an-existing-data-source).

I implemented it as a simple python script that can be run as a scheduled job.

I made into a gist in case anyone else might find it useful :smile:: https://gist.github.com/chaitan94/cc8594ca0343e07e8c4a8f580d18e99f
