### ISSUE TITLE
dashboard api not working

### ISSUE THREAD

**Issue by kerush** [grafana/grafana#2986]
On version 2.1.3 I am having troubles posting a dashboard. To prove you the problem, I can reproduce the scenario by getting an existing dashboard and posting it again:

$ curl -X GET http://admin:admin@server:3000/api/dashboards/db/latency-rollups-copy > dash.json
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  7202    0  7202    0     0  70333      0 --:--:-- --:--:-- --:--:-- 87829

$ cat dash.json | wc 
      0     148    7202

$ curl -X POST http://admin:admin@server:3000/api/dashboards/db -d @dash.json 
[{"fieldNames":["Dashboard"],"classification":"RequiredError","message":"Required"}]

**Comment by torkelo** [comment]
It looks like you are not posting the correct json, look at the http api docs:
http://docs.grafana.org/reference/http_api/#create-update-dashboard

you cant just post the same json back, the POST request requires more info (how to handle overwrites if the dashboard has been updated by someone else)
