### ISSUE TITLE
BarGauge: Changing Display Name Returns No Data when selecting a specific column

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#29877]
Queries are in Table format not Time Series. You can see the raw data in the table view, "vehicle_id" and some duration. I want to show the durations as values and vehicle_id (first column) as a series name.

![displayname (0)](https://user-images.githubusercontent.com/43188411/102352083-78e8ff00-3fb8-11eb-9ba2-d6c26b2584e1.gif)

**How to reproduce it (as minimally and precisely as possible)**:

- Select a certain field in Bar Gauge > Display > Fields
- Change "Display Name"
- It'll return No Data.

**What you expected to happen**:

It should display the display name I typed just as it does when "All Fields" selected.

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Postgres 9.6
- OS Grafana is installed on: Windows 10 - 64 bit.
- User OS & Browser: Chrome

**Comment by hugohaggmark** [comment]
Confirmed on Grafana v7.3.6 (ea06633c34).  Repro steps is correct above but to clarify you need to change the Field to something other than `Numeric Fields` or `All Fields` for the bug to appear.
![image](https://user-images.githubusercontent.com/562238/102357482-a761dc80-3fae-11eb-9e10-5607271b4d58.png)

**Comment by torkelo** [comment]
@dprokop or @ryantxu I remember having this reported or encountering this before, looks like we did not solve it?

**Comment by torkelo** [comment]
Unable to replicate in 7.5
