### ISSUE TITLE
Grafana Enterprise encoding/xml SAML vulnerability

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#29875]
This release fixes vulnerabilities in Grafana Enterprise only.

Grafana OSS is not affected, this release is for janitorial reasons only: To keep released versions synchronized.

Grafana Enterprise customers were notifier earlier this week prior to this vulnerability been publicly disclosed by Mattermost
Grafana Cloud instances were patched prior to this vulnerability been publicly disclosed by Mattermost.

This patch release applies GHSA-4hq8-gmxx-h6w9

For more information, see https://mattermost.com/blog/coordinated-disclosure-go-xml-vulnerabilities/

**Comment by hugohaggmark** [comment]
Friendly reminder to add labels to new issues @bergquist
