### ISSUE TITLE
Add more heights > 700px 

### ISSUE THREAD

**Issue by burtonator** [grafana/grafana#2987]
I have a 30" 1080p display... Additionally 4k displays are going to be commodity here soon.

Maybe add an option for a custom height? Or at least add a few more heights.

I have a cluster with 45 (growing to 150) boxex and I'd like to see a chart and table of the hosts.   Right now I can't because the chart becomes too small and then I can't scroll down to see my remaining hosts when I use a table to display them.

**Comment by torkelo** [comment]
if you select row editor then you can enter a custom height

**Comment by torkelo** [comment]
but I will try to add a few more options to the quick row height selection, 
Also in the upcoming 2.5 you can resize panels by using the resize handle in the lower right 
https://github.com/grafana/grafana/issues/2577
