### ISSUE TITLE
Template variables with custom values with support for key/value mapping and custom "All" value not working as expected

### ISSUE THREAD

**Issue by lealceldeiro** [grafana/grafana#29887]
**What happened**:

For *custom* *multi-selection* template variables with [support for *key*/*value* mapping](https://github.com/grafana/grafana/pull/27829) and variables with custom "All" option (for example a *regex*) used in a panel link **the elements in the variable drop-down are incorrectly displayed and not assigned properly in the URL**, meaning:

- if a multiple selection was done, the elements displayed in the drop-down now are the *value*s and not the *key*s and in the URL the variables take the value in the format `var-MY_VAR={value, valueN}`.
- if "All" is selected then the custom value is displayed and assigned in the URL to the variable like `var-MY_VAR=custom_regex`.

**What you expected to happen**:

For *custom* *multi-selection* variables with *key*/*value* pairs and variables with custom "All" option (for example a *regex*) used in a panel link **the elements in the variable drop-down are correctly displayed and assigned properly in the URL**, meaning:

- if a multiple selection was done, the elements displayed in the drop-down must be the *key*s and not the *value*s and in the URL the variables take the value in the format `var-MY_VAR=value&var-MY_VAR=valueN`.
- if "All" is selected then "All" is displayed in the variable drop-down and assigned to the URL to the variable like `var-MY_VAR=All`.

**How to reproduce it (as minimally and precisely as possible)**:

In a dashboard A (`https://play.grafana.org/d/000000012`):

- Create a variable `FOOD` with custom values `Burger : 1, Carrots : 2` and custom `"All"` value `[1-2]` 
- Create a panel link to the same dashboard like `https://play.grafana.org/d/000000012?var-FOOD=${FOOD}`
- Save the changes

Scenario 1:
- Select as a *FOOD* the elements *Burger* and *Carrots*
- Navigate to the created link
- The URL shown is like `https://play.grafana.org/d/000000012?var-FOOD={1,2}`

Scenario 2:
- Select as a *FOOD* the element *All*
- Navigate to created link
- The URL shown is like `https://play.grafana.org/d/000000012?var-FOOD=[1-2]`

![Grafana_Variables_issue](https://user-images.githubusercontent.com/15990580/102367641-ab97f500-3fc2-11eb-8031-848363db5f56.gif)

**Anything else we need to know?**:

- This does not happen if I create a *Dashboard link* using the very same link and I mark the option *Variable values*.
- I can't use the `${__all_variables}` alternative because there are some values I need to specifically modify.

**Environment**:
- Grafana version: 7.3
- Data source type & version: Prometheus
- OS Grafana is installed on: not sure, running on the cloud
- User OS & Browser: just a regular user, reproducible in  Chrome and Firefox
- Grafana plugins: not relevant, the panel link using the test variable was created in a "Dashboard list" and "Polystat" visualizations

**Comment by lealceldeiro** [comment]
After further testing it doesn't seem to be related to the fact that the template variable support key/value mapping but to the fact that it's a *multi-selection* variable.

**Comment by hugohaggmark** [comment]
Confirmed on Grafana Play https://play.grafana.org/d/F_dOclJMz/template-variables-in-panel-links?orgId=1

**Comment by torkelo** [comment]
When building the link url Grafana is just interpolating the expression, and in this case, we will use the same logic as interpolating it anywhere else, ie using the custom all value. 

There is some special logic for the dashboard links that use "include all variables" , and the panel link variable `${__all_variables}` , they will be interpolated using the same URL state the dashboard currently has. 

there is no trivial way to fix multi-valued (or custom all value) variables when interpolating a URL string as Grafana needs to know the key as well. 

See this feature request: https://github.com/grafana/grafana/issues/21459
