### ISSUE TITLE
Deleting "General" folder causing empty grafana state

### ISSUE THREAD

**Issue by andrei-karpliuk** [grafana/grafana#29880]
**What happened**:
Moved all dashboards into custom folder and deleted "General" folder. 
After refresh I see empty list: 
![image](https://user-images.githubusercontent.com/45938185/102355463-8c926680-3fb4-11eb-8c5a-65e0b5f360da.png)

**What you expected to happen**:
In case General is default and mandatory folder:
- I expect to see disabled delete button 
- or notification about my deletion aborted
- or popup to define new default folder.   
In case General is ordinary folder: 
- Correct deletion and remained folders with all created dashboards. 

**How to reproduce it (as minimally and precisely as possible)**:
![general_deleted](https://user-images.githubusercontent.com/45938185/102357481-09264480-3fb7-11eb-9b40-f65811e6fac8.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.5 (11f305f88a) and  v7.0.3 (00ee734baf)
- Data source type & version:  
- OS Grafana is installed on: Mint 20.10 (with docker container) and CentOS (with docker container)
- User OS & Browser: Firefox 83.0 (64-bit)
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Confirmed on Grafana v7.3.5 (11f305f88a)

**Comment by hugohaggmark** [comment]
Taking a deeper look into this and you can't get/update/delete the General folder from the API so this is just UX. If you remove the General folder you can always recreate it by creating a new dashboard and choosing General. I'm going to open a PR that disables the button in the UI.
