### ISSUE TITLE
Wrong version pushed to dockerhub for grafana:latest

### ISSUE THREAD

**Issue by argibbs** [grafana/grafana#29897]
**What happened**:
Pulled grafana latest for amd64 and got a 6.7.5 build, not 7.3.6

**What you expected to happen**:
To get 7.3.6

**How to reproduce it (as minimally and precisely as possible)**:
docker pull grafana/grafana:latest

```
$ docker pull grafana/grafana:latest
latest: Pulling from grafana/grafana
Digest: sha256:4635410ea61c746d27052d2d2380ed402f55acbe1c5a5885ef79fbcb44e979b3
```

This maps to the digest listed for 6.7.5 not 7.3.6

**Comment by hugohaggmark** [comment]
Hmm, I can't reproduce this. Could you please try again?

**Comment by aknuds1** [comment]
Sorry, it was a temporary glitch and has been fixed.

**Comment by hugohaggmark** [comment]
Closing this issue then. Thank you for reporting this @argibbs ⭐

**Comment by argibbs** [comment]
Thanks for the rapid fix guys.
