### ISSUE TITLE
Table Cell display mode dosn't appear on snapshot.raintank.io

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#29894]
**What happened**: The Cell display mode dosn't appear on snapshot.raintank.io. The format of the numbers and date is also incorrect.

**Environment**:
- Grafana version: v7.3.5 (11f305f88a)
- Data source type & version: Random Walk (anyway, it doesn't matter)
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome 87.0.4280.88
- Grafana plugins: Table

The snapshot: https://snapshot.raintank.io/dashboard/snapshot/lz5tbHckXSh38wrTyhmxlYh2gUirf25V?orgId=2

![image](https://user-images.githubusercontent.com/2911588/102460647-97e2a200-4047-11eb-84b3-ee5e2fff4739.png)

The original tables:

![image](https://user-images.githubusercontent.com/2911588/102460623-8ef1d080-4047-11eb-8b72-7ab2ecbc257e.png)

**Comment by hugohaggmark** [comment]
Hmm, seems to work when creating a local snapshot on Grafana Play:

Snapshot:
https://play.grafana.org/dashboard/snapshot/6oTJjxNMPyIMU5dKAFprpSMip3Dkx5XI?orgId=1

Original
https://play.grafana.org/d/pfBF8lJMz/snapshots-with-transforms-and-overrides?orgId=1

**Comment by torkelo** [comment]
This was fixed in 7.3.3 patch release https://github.com/grafana/grafana/pull/29031 

But we have not updated the snapshot server yet, doing now but need to migration the snapshot table and it's taking for ever so rolled the upgrade back

**Comment by torkelo** [comment]
Updated, so should work again
