### ISSUE TITLE
Name:Value Pairs in 'Custom' Type Variables

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#29909]
I was using 'custom' type variable in grafana 7.3.1, upgraded to 7.3.5 now it doesn't work as expected.

**What you expected to happen**:

This is how it was before, names shown but the variable using the value.
![image](https://user-images.githubusercontent.com/43188411/102504925-75c24180-4092-11eb-9e0d-1415c041751b.png)

**What happened**:

Now, it doesn't work as name:value pairs but values only.

![image](https://user-images.githubusercontent.com/43188411/102505143-b15d0b80-4092-11eb-9673-2581191fae84.png)

**How to reproduce it (as minimally and precisely as possible)**:

- Add Variable, Set Type: Custom
- Paste this: (1 Gün: 1 day, 7 Gün: 7 day, 10 Gün: 10 day, 15 Gün: 15 day, 1 Ay: 1 month, 2 Ay: 2 month, 3 Ay: 3 month, 6 Ay: 6 month)

I've tried removing Turkish characters (ü) and adding ""

**Environment**:
- Grafana version: 7.3.5
- OS Grafana is installed on: Windows 10

**Comment by dprokop** [comment]
@mertbakir we have introduced slight changes to the key/value pars in Custom variables. Please see this comment for more details: https://github.com/grafana/grafana/pull/28896#issuecomment-723180678

Also- sorry for not making this clear in the changelog.

**Comment by mertbakir** [comment]
> @mertbakir we have introduced slight changes to the key/value pairs in Custom variables. Please see this comment for more details: [#28896 (comment)](https://github.com/grafana/grafana/pull/28896#issuecomment-723180678)
> 
> Also- sorry for not making this clear in the changelog.

Thanks, it worked now. I've a question which is kind of related to the topic. Is it possible create key : value pair dropdown using a query which returns 2 columns?

```
SELECT name, value
FROM foo
```
