### ISSUE TITLE
Singlestat: Support InfluxDB Explore  (Tag / Tag values queries)

### ISSUE THREAD

**Issue by mattdlh** [grafana/grafana#2990]
I am using grafana with influxdb successfully, but was wondering how I can display a list of tag values. Essentially just show the text output from the following influx query: 

show tag values from int WITH KEY = "test"

It looks like grafana can only display values and shows N/A when I input the above query.

**Comment by torkelo** [comment]
singlestat panel only accepts metric queries at this point

**Comment by torkelo** [comment]
when a query like that returns multiple tag values what should be shown? the first?

**Comment by mattdlh** [comment]
Actually I got it to work with

```
SELECT value FROM "measurement" WHERE 'testkey' = "key"
```

However, it only displays one text value. It would be nice to have another text value and string them together. But I am able to do what I need to with just one at a time.

**Comment by torkelo** [comment]
That query return fields not tag values, so it's not the same thing at all

**Comment by torkelo** [comment]
And it will return  ALL values, could be millions so you could crash the browser, you should add top 1 or limit 1

**Comment by mattdlh** [comment]
Ah, yeah so I ended up restructuring the tables to store what I needed as text values instead of trying to have grafana read the tag values.

And thanks, will add LIMIT 1
