### ISSUE TITLE
Prometheus query input disappears when editing

### ISSUE THREAD

**Issue by jpdstan** [grafana/grafana#29919]
![Kapture 2020-12-17 at 12 17 57](https://user-images.githubusercontent.com/5893781/102539237-498ecc80-4062-11eb-8b07-e2f23f4cc955.gif)

**What happened**:
When editing Prometheus queries, sometimes we'll notice strange behavior with text disappearing. It seems to happen across keyboard operations, such as copy/pasting, navigating between words, navigating to start/end of line, etc.

Notice how in the video, some text seemed to disappear when the user navigating via keyboard macro to the beginning of the line. This is just one of many situations we've seen this bug.

**What you expected to happen**:
For text to not disappear

**How to reproduce it (as minimally and precisely as possible)**:
Within a Prometheus panel, try copying and pasting queries from one query box to another. And then clicking into the query boxes and navigating within them. I haven't found an algorithm to this yet but it doesn't take long for it to occur.

**Anything else we need to know?**:
This has happened across multiple users' accounts, most of whom to our knowledge use Chrome. This seemed to occur after we upgraded from 6.x.x to 7.x.x

**Environment**:
- Grafana version: 7.3.3
- Data source type & version: Prometheus 
- OS Grafana is installed on: macOS
- User OS & Browser: macOS Catalina, Chrome
- Grafana plugins:
- Others:

**Comment by jpdstan** [comment]
@dprokop #21764 might not be a duplicate after all - we're experiencing this even with panels that do NOT have auto-refresh. example:

https://user-images.githubusercontent.com/5893781/104078578-bb76b380-51d3-11eb-95ba-651a95300d65.mov

**Comment by jpdstan** [comment]
@dprokop Please re-open this issue - we're still seeing this issue on `7.3.6` on Chrome browsers. It doesn't seem to have anything relation to the auto-refresh feature.

**Comment by aocenas** [comment]
@jpdstan yeah that behavior is definitely bad, we did a bunch o fixes to our input component in Grafana 7.4. We will try to investigate but as these kind of issues are sometimes hard to reproduce could you check with newer Grafana version if you are still seeing this behavior?

**Comment by jpdstan** [comment]
@aocenas we haven't seen it since the upgrade a couple days. we'll re-open this issue if we see it again. thanks!
