### ISSUE TITLE
Graph panel shows different data depending on panel length

### ISSUE THREAD

**Issue by deliaiuga** [grafana/grafana#29913]
**What happened**:

I am using Grafana in conjuction with Influx DB.
About the data: In Influx I am writing once per hour metrics related to issues in a github repository. 

In Grafana I have a graph panel that shows the sum of of opened bugs on a time basis.
The query is the following:  **SELECT sum("number") FROM "issues" WHERE ("label" = 'bug' AND AND "state" = 'opened') AND $timeFilter GROUP BY time($interval) fill(previous)**

, where _number_ is  the total number of bugs in the repo at that moment.

At the creation time, the panel seemed correct; then I created other panels and rearranged and shorten them, and then I noticed the issue.
![image](https://user-images.githubusercontent.com/26602758/102515092-fa628f00-4095-11eb-92f8-1c0d93c22d83.png)

In the second panel, the peaks from 20:00 and 12:00 hour actually have double the value that they should.

**What you expected to happen**:

Accurate data to be shown on the graph regardless of its length,

**How to reproduce it (as minimally and precisely as possible)**:

1. Insert data in Influx(Integer values)
2. Create a graph panel and retrieve data with the query specified above(length aprox half of dashboard)  --> data should be succesfully displayed
3. Create a graph panel and retrieve data with the query specified above(length aprox quarter of dashboard)  --> inacurrate data should be displayed.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.3.4
- Data source type & version: Influx DB 1.7
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10/Google Chrome
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
This is due to interval which gets lower the shorter the panel (less data points needed for smaller graphs),

So if your query is using a group by time interval then that should explain it.

You can adjust the max data points in Query options above your queries to fine tune the interval calculations
