### ISSUE TITLE
how to make all the null values as non-null values on graph

### ISSUE THREAD

**Issue by freelancersam2020** [grafana/grafana#29917]
Hi all
Hope you are going well.
Currently I am using graph panel to show influxDB data on it.
By the way, there are lots of null values in data read from the database.
So I want to show null values as non-null values.
So I did the setting like this on the panel.
After doing the setting like this, the later part was kept continuous, but null values of first part was not treated!
So I hope you would give me help for this problem.
Thank you.:)

**Comment by torkelo** [comment]
There has to be a datapoint at the start of the graph for Grafana to connect to ,

Cant invent new data points that does not exist , only connect lines between points that does
