### ISSUE TITLE
After upgrade to grafana-7.3.6-1 Grafana dosen't work on IE

### ISSUE THREAD

**Issue by spaceboy666** [grafana/grafana#29928]
After upgrade to 7.3.6-1.x86_64 on RHEL6 and RHEL7 without web proxy, Grafana is no longer accessible from IE (11.0 & 9.0) 

For IE 11 it shows:

"If you're seeing this Grafana has failed to load its application files 
1. This could be caused by your reverse proxy settings.
 2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.
 3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build
 4. Sometimes restarting grafana-server can help
"
For IE 9 it loads part of the code, but website is empty.

In Grafana logs, when i am using FF or Chrome it shows normal output without any errors. From IE there is no entry in logs at any level of debugging. 

Config:
$ grep -v -E '^;|^#|^$' /etc/grafana/grafana.ini 
[paths]
logs = /var/log/grafana
plugins = /var/lib/grafana/plugins
[server]
protocol = https
http_port = 443
root_url = https://monitoring.home.lan
cert_file = /etc/grafana/cert.pem
cert_key = /etc/grafana/cert.key
[database]
log_queries =
[session]
[dataproxy]
[analytics]
check_for_updates = true
[security]
[snapshots]
[dashboards]
[users]
default_theme = light
[auth]
[auth.anonymous]
enabled = true
org_name = Grafana
org_role = Viewer
[auth.github]
[auth.google]
[auth.generic_oauth]
[auth.grafana_com]
[auth.proxy]
[auth.basic]
[auth.ldap]
[smtp]
enabled = true
host = 127.0.0.1:25
from_address = root@monitoring.home.lan
ehlo_identity = monitoring.home.lan
[emails]
[log]
mode = console file
level = debug
filters = rendering:debug
[log.console]
[log.file]
log_rotate = true
daily_rotate = true
max_days = 7
[log.syslog]
[alerting]
[metrics]
[metrics.graphite]
[tracing.jaeger]
[grafana_com]
[external_image_storage]
[external_image_storage.s3]
[external_image_storage.webdav]
[external_image_storage.gcs]
[external_image_storage.azure_blob]
[external_image_storage.local]

**Comment by torkelo** [comment]
Grafana v6+ is not supported on IE

**Comment by donghuzi1** [comment]
浏览器：ie11
版本：7.3.2
不显示报出问题：If you're seeing this Grafana has failed to load its application files 



1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarnbuild

4. Sometimes restarting grafana-server can help
请问是什么原因导致的？
