### ISSUE TITLE
LDAP: Cannot connect using LDAPS 

### ISSUE THREAD

**Issue by michaelroth** [grafana/grafana#2992]
I cant't get LDAPS with Active Directory working. With LDAP it's working fine, but it's not secure.

In the Logfile I can see the following messages when I try to login with LDAPS

2015/10/21 08:36:19 [login.go:101 LoginPost()] [E] Error while trying to authenticate user: LDAP Result Code 200 "": read tcp 128.130.30.21:636: connection reset by peer
2015/10/21 08:36:19 [I] Completed /login 500 Internal Server Error in 4.919193ms

LDAPS is working in my Confluence Installation with the same Credentials I use in Grafana
I tried ldapsearch on Commandline, it works as it should.

**Comment by torkelo** [comment]
Strange, it should work. Think others have used LDAPS but not sure. I do not have a ldaps server to test with right now so any help on this would be great.

**Comment by martbhell** [comment]
I'm using LDAPs with Grafana 2.1.3.

Our ldap.toml config (seems I'm not verifying the cert, should probably do that):

<pre>
[[servers]]
host = "ldapserver"
port = 636
use_ssl = true
ssl_skip_verify = true
bind_dn = "uid=bind-account,dc=snip"
bind_password = ''.."
search_filter = "(&(objectClass=posixAccount)(objectClass=inetOrgPerson)(uid=%s))"
search_base_dns = ["cn=users,dc=snip"]
</pre>

**Comment by miroth70** [comment]
My ldap.toml config looks like that, I have to use  Microsoft Active Directory.

>[[servers]]
>host = "ldapservername"
>port = 636
>use_ssl = true
>ssl_skip_verify = true
>bind_dn = "******@intern.tuwien.ac.at"
>bind_password = '********'
>search_filter = "(sAMAccountName=%s)"
>search_base_dns = ["OU=people,OU=TU,DC=intern,DC=tuwien,DC=ac,DC=at"]

I don't think that my config is the problem because it works very well without SSL activated.

**Comment by utkarshcmu** [comment]
@miroth70 LDAPs is working fine with me, I tested it with different combinations of config parameters and it works perfectly. 

Here is my config, I hope this helps:

```
#Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# Ldap server host
host = "ldap.myserver.com"
# Default port is 389 or 636 if use_ssl = true
port = 636
# Set to true if ldap server supports TLS
use_ssl = true
# set to true if you want to skip ssl cert validation
ssl_skip_verify = true

# Search user bind dn
bind_dn = "cn=BindUser,dc=mydc,dc=yourdc,dc=com"
# Search user bind password
bind_password = 'idontknow'

# Search filter, for example "(cn=%s)" or "(sAMAccountName=%s)"
search_filter = "(id=%s)"

# An array of base dns to search through
search_base_dns = ["dc=mydc,dc=yourdc,dc=com"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "cn"
surname = "givenName"
username = "id"
member_of = "memberOf"
email =  "mail"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=admins,ou=groups,dc=mydc,dc=yourdc,dc=com"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
#group_dn = "cn=users,dc=grafana,dc=org"
group_dn = "*"
org_role = "Editor"
```

I saw the original post up there and I see that you are facing "Connection Reset" error. Please check your configuration settings again.

Someone else faced a similar error: https://forum.gitlab.com/t/solved-ldaps-to-ad-connection-reset/1161

**Comment by miroth70** [comment]
My Active Directory Admin told that there is a problem with the ciphers, Grafana and the Active Directory cannot negotiate the cipher suite.

**Comment by zstyblik** [comment]
@michaelroth, please, can you provide more information? I mean, there really isn't much to go on. We're using LDAPS against AD and it works just fine. I did give a look to `go-ldap` and found:

```golang
// CipherSuites is a list of supported cipher suites. If CipherSuites
// is nil, TLS uses a list of suites supported by the implementation.
CipherSuites []uint16
```

Although, I admit I'm not sure what to make out of it.

**Comment by michaelroth** [comment]
After Upgrading to Grafana 3 it works now.


Am 08.06.2016 um 08:59 schrieb Zdenek Styblik:
>
> @michaelroth <https://github.com/michaelroth>, please, can you provide 
> more information? I mean, there really isn't much to go on. We're 
> using LDAPS against AD and it works just fine. I did give a look to 
> |go-ldap| and found:
>
> |// CipherSuites is a list of supported cipher suites. If CipherSuites 
> // is nil, TLS uses a list of suites supported by the implementation. 
> CipherSuites []uint16 |
>
> Although, I admit I'm not sure what to make out of it.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/grafana/grafana/issues/2992#issuecomment-224505634>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AJu6izwsifxqwKycBol1xm1FGICMAKD9ks5qJmhkgaJpZM4GSvae>.
>

-- 
--------------------------------------------------------------------------
Michael Roth                           email roth@zid.tuwien.ac.at
Certified Project Management Associate Tel. (++43-1) 588 01 - 42091
Red Hat Certified Technician           Fax. (++43-1) 588 01 - 42099
Brandschutzwart gemäß TRVB O 117
Zentraler Informatikdienst (ZID)
Technische Universitaet Wien
Wiedner Hauptstr. 8-10, A-1040 Wien
DVR-Nummer 0005886

**Comment by zstyblik** [comment]
@michaelroth, I see. That's great! Can we close the issue then?

**Comment by michaelroth** [comment]
Yes, please close the issue.


Am 08.06.2016 um 13:18 schrieb Zdenek Styblik:
>
> @michaelroth <https://github.com/michaelroth>, I see. That's great! 
> Can we close the issue then?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub 
> <https://github.com/grafana/grafana/issues/2992#issuecomment-224560234>, 
> or mute the thread 
> <https://github.com/notifications/unsubscribe/AJu6i1QpJF0ud1ScBJ73nMVF9Iwo0oTsks5qJqUWgaJpZM4GSvae>.
>

-- 
--------------------------------------------------------------------------
Michael Roth                           email roth@zid.tuwien.ac.at
Certified Project Management Associate Tel. (++43-1) 588 01 - 42091
Red Hat Certified Technician           Fax. (++43-1) 588 01 - 42099
Brandschutzwart gemäß TRVB O 117
Zentraler Informatikdienst (ZID)
Technische Universitaet Wien
Wiedner Hauptstr. 8-10, A-1040 Wien
DVR-Nummer 0005886
