### ISSUE TITLE
v7.3.6 Elasticsearch "Content-Type header is missing" response for all panel queries

### ISSUE THREAD

**Issue by jveldboom** [grafana/grafana#29929]
**What happened**:
Not entirely sure if this was caused by the update to v7.3.6, but our AWS Elasticsearch data source no longer returns queries within panels. When updating the data source, it is able to reach Elasticsearch to validate the index so can validate Grafana can access ES properly. The Chrome console shows the response being:

```json
{"error":"Content-Type header is missing","status":406}
```

Also, here is the son from the query inspector:
```json
{
  "request": {
    "url": "api/datasources/proxy/40/_msearch?max_concurrent_shard_requests=5",
    "method": "POST",
    "data": "{\"search_type\":\"query_then_fetch\",\"ignore_unavailable\":true,\"index\":\"lead-times\"}\n{\"size\":0,\"query\":{\"bool\":{\"filter\":[{\"range\":{\"timestamp\":{\"gte\":1608275645611,\"lte\":1608297245612,\"format\":\"epoch_millis\"}}},{\"query_string\":{\"analyze_wildcard\":true,\"query\":\"*\"}}]}},\"aggs\":{\"2\":{\"date_histogram\":{\"interval\":\"15s\",\"field\":\"timestamp\",\"min_doc_count\":0,\"extended_bounds\":{\"min\":1608275645611,\"max\":1608297245612},\"format\":\"epoch_millis\"},\"aggs\":{}}}}\n",
    "hideFromInspector": false
  },
  "response": {
    "error": "Content-Type header is missing",
    "status": 406,
    "message": "Content-Type header is missing"
  }
}
```

**How to reproduce it (as minimally and precisely as possible)**:
- We only have a single ES data source at the moment but this issue is happening on every query.

**Environment**:
- Grafana version: v7.3.6 (ea06633c34) under Grafana Cloud
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome
- Grafana plugins: n/a

**Comment by wbrowne** [comment]
Thanks for creating this issue @jveldboom. I have an idea what caused this. I have a [branch](https://github.com/grafana/grafana/tree/sigv4-content-type) as a potential fix - would you be able to test it out to verify it fixes the issue you're seeing? Unfortunately it would take some time to setup the correct environment to reproduce on my end at the moment

**Comment by wesleyforti** [comment]
Same error here.
I have downgraded to v7.3.5 and it did not work.
I am running grafana as docker image on AWS ECS.
ES is AWS ElasticSearch service running version 7.4

**Comment by akitty** [comment]
I tested this branch and it seems to work better talking to aws elasticsearch.
However there are other headers that I need to set in order to talk the elasticsearch. Should those be added to the permitted headers too?
The headers are securitytenant and possibly kbn-xsrf.
Sources: https://opendistro.github.io/for-elasticsearch-docs/docs/security/access-control/multi-tenancy/ and https://docs.search-guard.com/latest/kibana-multi-tenancy

**Comment by wbrowne** [comment]
@wesleyforti `7.3.4` should work in this case as the allowlist was introduced in `7.3.5`.

@akitty Thanks for checking it out. Yep indeed - thanks for bringing those to my attention 😄  Let me go ahead and add those

**Comment by wbrowne** [comment]
Have added a commit with those changes @akitty if you want to try it again. If all looks good, I'll open a PR
