### ISSUE TITLE
Docs feedback: /variables/advanced-variable-format-options.md

### ISSUE THREAD

**Issue by mdicss** [grafana/grafana#29933]
When I click on 'Variables types' in the documentation overview on the left, I only get some scrambled output.
So far, I could not find the documentation of the different variable types in the documentation, only in the sources and there, I don't find something about type 'system'.

**Comment by dprokop** [comment]
@mdicss thanks for the feedback, we really appreciate it!

Looking at the [variable types page](https://grafana.com/docs/grafana/latest/variables/variable-types/) it seems like you get a pretty good high-level overview of the variables available in Grafana. More details about particular variable types are available when you click on the link in the table(i.e. [query variable](https://grafana.com/docs/grafana/latest/variables/variable-types/add-query-variable/#add-a-query-variable)).

We are always open to improvement suggestions, so it would be great if you could provide some more about your expectations. I'm gonna loop in @oddlittlebird as Diana is our docs rock star ⭐ and I'm sure she will help you with any docs issues that you encounter:)

> I don't find something about type 'system'.

Can you explain a little bit more what do you mean by this?

**Comment by oddlittlebird** [comment]
@mdicss, can you show me a screenshot of the "scrambled output"? You should be seeing something like this in the side menu. We don't have system variables, do you mean [Global variables](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/)?

![image](https://user-images.githubusercontent.com/52059945/102795751-1b5f0480-4362-11eb-9cdb-08ccee851bc1.png)

**Comment by mdicss** [comment]
Hi Diana
Thank you for your reply. Now, in 2021, I can no longer reproduce the problem. I can look at the documentation e.g. of 'Global Variables'.
I was looking for a way to use (linux) sytem variables in dashboards. In the dashboard-editor, I see the type 'system' for variables (grafana 7.3.1):
![image](https://user-images.githubusercontent.com/43135155/103539171-de355f00-4e97-11eb-8e07-39c4f41ffa55.png)
Any explanation for this type?

**Comment by oddlittlebird** [comment]
Yes, they are detailed in the [Add ad hoc filters](https://grafana.com/docs/grafana/latest/variables/variable-types/add-ad-hoc-filters/) topic.

You can see an example in the [Elasticsearch Metrics dashboard](https://play.grafana.org/d/000000014/elasticsearch-metrics?orgId=1) on Grafana Play.

**Comment by mdicss** [comment]
Hi Diana
Sorry for the screenshot, it's tricky do do a screenshot of the dropdown. I wanted to ask about the 'system' in the dropdown (not the highlighted 'Ad hoc filters'). This does not work and until now, I didn't find anything about using system/environment variables in dashboards.

**Comment by oddlittlebird** [comment]
Please open a separate issue to discuss system variables, or ask about them on community.grafana.com.
