### ISSUE TITLE
Maintain scroll position when exiting fullscreen edit/view mode

### ISSUE THREAD

**Issue by ert56** [grafana/grafana#2993]
I have one dashboard with around 33 panels. 

Now when i scroll down and click on the view option , then click "Back To Dashboard", the page scroll to the top of the page.

While i have so many panels so going to top of the page and then scrolling down to find the same panel is little inconvinient. 

Can we have something to maintain the scroll position. This is little urgent?

**Comment by torkelo** [comment]
Grafana dashboards are mainly designed so that all panels should be in view and should not require that much scrolling. But I can see some edge cases where this long dashboards are really useful and where this issue is irritating.

**Comment by shanky05** [comment]
Can you please fix it asap. Its very much required.

**Comment by shanky05** [comment]
@torkelo  any update on this feature??

**Comment by torkelo** [comment]
@shanky05 no, its been like this from Grafana v1 so its not a high prio issue, that is why I labels "nice to have" and state "help wanted" , to mark that a PR would be great and accepted

**Comment by torkelo** [comment]
this was implemented inv 5
