### ISSUE TITLE
ValueMappings: Support string value mappings when value can be parsed as a number (For example IP Address) 

### ISSUE THREAD

**Issue by neilschelly** [grafana/grafana#29949]
**What happened**:
Matfching rules for Value=>Text mappings are not working for strings in a table. It appears that it's interpreting the IP addresses as numbers and ignoring everything beginning with the second `.` character. I have tried both setting the table's default Units to String, as well as using field overrides to do it. That made no difference.

**What you expected to happen**:

I expect to be able to put an IP address in the Value field and a replacement string in the Text field to see my replacement string in the table instead of the IP address.

**How to reproduce it (as minimally and precisely as possible)**:

This table is constructed of Prometheus metrics with the labels shown as columns. All 3 columns in my screenshot are the same underlying data, but I created this to show the difference in behavior. The first column has no overrides. The second one is matching against "169.254.antyhing" to show that it matches every value that begins with `169.254`. The third column shows that `169.253` is not a match.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.6 (ea06633c34)
- Data source type & version: Prometheus 2.18.1
- OS Grafana is installed on: Ubuntu Bionic
- User OS & Browser: Debian Buster, Firefox 78.6.0esr (64-bit)
- Grafana plugins: Core, Grafana Image Renderer, Pie Chart, Status Map, worldPing
- Others:

![image](https://user-images.githubusercontent.com/3343289/102819310-3dc44280-43a1-11eb-9c8d-8b5d0321a206.png)

**Comment by neilschelly** [comment]
@dprokop This doesn't appear to be a duplicate of #25070. My value=>text mappings are getting saved fine. The values just don't match against the data correctly. It's as if they are being interpreted as floats and all data starting with a second `.` character is ignored so that it can be casted as a float.

**Comment by dprokop** [comment]
I believe it is as it relates, as you described, to mapping not being applied to string fields. I think the issue I'm linking to is not about saving, but the mapping itself.

Feel free to re-open if you disagree.

**Comment by neilschelly** [comment]
I believe this is a different bug. I can do value mapping with strings, and I have examples exactly like that in #25070 working fine (single-digit number is in a text field and I can do value mapping to another string). The first comment on that ticket also said it could reproduce the same problem and noted that the value mapping doesn't get saved. I do not have that problem either.

In my case, I am getting value mappings that replace the data, but the matching isn't working as expected. There appears to be some casting as a float either in the data or the match value that isn't obvious. When a match "works," my replacement string will replace it fine.

Let me be more clear about what issue I'm having... assume I have a data field that is an IP address, like `169.254.111.69`:

* These values *will* match, and replacement will happen:
    * `169.254`
    * `169.254.`
    * `169.254.111.69`
    * `169.254.123.123`
    * `169.254.ANYTHINGELSE` (ANYTHINGELSE can be anything)
    * `169.254ANYNAN` (ANYNAN can be anything that doesn't start with a number)
*  These values will *not* match, and no replacement will happen:
    * `16`
    * `169.25`
    * `169.2545`

Since any data that is an IP address beginning with `169.254.` will match an value mapping that starts with `169.254.`, it's not working for me. I cannot distinguish between the different IP addresses.

**Comment by neilschelly** [comment]
@dprokop I don't have permissions to re-open the ticket, but I don't see any real overlap between this and the other bug (which works fine for me.

If you'd prefer I put all this in that ticket, I can. I don't know enough about how the table value mapping works under the covers to know if this might be fixed at the same time.

**Comment by dprokop** [comment]
@neilschelly thanks for all the details. I'll re-open this then and investigate some more!

**Comment by torkelo** [comment]
Currnely value mappings try to parse the value as float: https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/utils/valueMappings.ts#L18 

Which succeeded for IP address
