### ISSUE TITLE
Using template variable when all selected for repeating graph gives all values in data link

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#29942]
**What happened**:
Used a data link on a repeated panel to launch a new window for one host but instead grafana wanted to do all hosts.

**What you expected to happen**:
For the data link on the repeated panel to use $Host for the individual panel, not "all"

**How to reproduce it (as minimally and precisely as possible)**:
1) Create dashboard with "Host" as a template variable, allowing "All" hosts to be selected.
2) Select the graph to repeat for each $Host.
3) Enable data links for each panel and add var-Host=${Host} to the URL
4) Select "All" to show all hosts.
5) Click on data link and get taken to a URL where "var-Host" is the complete set of values for $Host.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.3.7
- Data source type & version: Influxdb 1.8.3
- OS Grafana is installed on: CentOS 6.10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
@yellowpattern thanks for reporting this issue. It should be fixed in the next version of Grafana (7.4.0) with this PR https://github.com/grafana/grafana/pull/29757
