### ISSUE TITLE
Advanced variable format options issue v.7.3.6

### ISSUE THREAD

**Issue by nikola-farshore** [grafana/grafana#29943]
**What happened**:
URL: .....&var-MultiDeviceId=A&var-MultiDeviceId=B
'${MultiDeviceId:raw}' variable format returns:
('A,B')

**What you expected to happen**:
URL: .....&var-MultiDeviceId=A&var-MultiDeviceId=B
'${MultiDeviceId:raw}' variable format should return:
('{A,B}') 

**Environment**:
- Grafana version: Version 7.3.6 (commit: ea06633c34, branch: HEAD)
- Data source type & version: PostgreSQL 11 - Timescale
- OS Grafana is installed on: Centos 7
- User OS & Browser: macOS Big Sur 11.0.1 / Firefox 84.0 (64-bit)

**Comment by dprokop** [comment]
@nikola-farshore thanks for opening the issue. Do you mind sharing the query you are trying to use the `${MultiDeviceId:raw}` in? I think the format is OK and it hasn't been changed for a while. I'm also trying to figure out why the [docs](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#raw) contains `{}` in the raw syntax description.

**Comment by nikola-farshore** [comment]
`SELECT 
  $__timeGroup("tm", $__interval, 0) as "time", 
  AVG("hist") as "Hourly Avg" 
FROM 
  historicalavgmultiple('${MultiDeviceId:raw}') 
GROUP BY 1 
ORDER BY 1;`

In the previous version/s, list of variables passed to function were wrapped into `{}` so PostgreSQL recognized it as array list.

**Comment by dprokop** [comment]
@nikola-farshore thanks for a quick reply. Trying to uderstad what's going on. When you say "In the previous version/s" what versions do you mean?

**Comment by nikola-farshore** [comment]
Not sure about previous grafana version to be honest, but we were using advanced variable format for a while, so it must be v6 and v7 as well, up to v.7.3.6.

I found old screenshot, so you can check it as a reference:
![Screenshot 2020-12-21 at 13 25 18](https://user-images.githubusercontent.com/53433107/102777198-6c85ed00-4390-11eb-9a8a-d9e3efe3fe80.png)

**Comment by dprokop** [comment]
@nikola-farshore thanks a lot for the screenshot. Seems like it's v7 so i'm gonna dig a little bit deeper. Maybe there has been some changes to the Postgres datasouce that I'm not aware of. I'll let you know when I figure this out.

**Comment by nikola-farshore** [comment]
Alright, thank you. Do you have any alternative to pass multiple variables `(A, B)` from URL to function in array format `'{A,B}'` ?

**Comment by dprokop** [comment]
@nikola-farshore try :glob format

**Comment by nikola-farshore** [comment]
> @nikola-farshore try :glob format

@dprokop thank you, it works.

**Comment by dprokop** [comment]
@nikola-farshore it looks like the regression was introduced with this change: https://github.com/grafana/grafana/pull/26466/files#diff-99398d3bb68cd46ea23efea4904dd42ee6378dba8822a6a5dc4798d308fededcL230

@torkelo I'm not sure how the raw should behave, whether it should work as currently on the master or as in the docs. Can you help with clarifying the designed behaviour? It seems to me like the current master's behaviour is the correct one as it represents the actual raw value, but looking at the number of upvotes in this issue it seems like we might have unintentionally broken people's querie.

**Comment by torkelo** [comment]
If you want curly braces around the multi-formatted value use the glob format `${variableName:glob}`
