### ISSUE TITLE
Docs: Update "Add support for annotations" docs

### ISSUE THREAD

**Issue by joanlopez** [grafana/grafana#29953]
**What would you like to be added**:

Update the [Add support for annotations](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/) docs section to include the new standard way to add plugins support for annotations.  

**Why is this needed**:

Thanks to @kminehart, I figured out nowadays it's super super easy to add plugins support for annotations, so I think we definitely need to add that information in our "Developers" docs. It's extremely valuable! 👏 

Thanks!

**Comment by oddlittlebird** [comment]
Hi @joanlopez , do you have the content for this PR? Is this something you are comfortable writing and submitting yourself?

**Comment by joanlopez** [comment]
Sure thing, I'll work with @marcusolsson on it. Thanks!! 🙏

**Comment by tolzhabayev** [comment]
@joanlopez since it's documented now https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/#add-annotations-support-to-your-data-source could you close the issue if not relevant anymore? 🙏

**Comment by tolzhabayev** [comment]
Closing this one @joanlopez - since it's documented now under: https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/#add-annotations-support-to-your-data-source There will be another issue open for docs about backend plugins.
