### ISSUE TITLE
[Macaron] PANIC: assignment to entry in nil map

### ISSUE THREAD

**Issue by dummybyte** [grafana/grafana#2996]
Hi,
My database is mysql for grafana dashboards. So if the json in "data" column is changed/modified or a new entry is added to the table shouldn't a new dashboard be created or existing dashboard be updated?
If I am trying to add a new row or change an existing row it is throwing an error
[Macaron] PANIC: assignment to entry in nil map

**Comment by torkelo** [comment]
You should use the HTTP api to create new dashboards, not poke around the database :)  if you try to create a dashboard manually using SQL you need have valid json in data, and if you make changes you must make sure the json is correct
