### ISSUE TITLE
Regression in v7.3.5 leads to incorrect Value column name in Table panel

### ISSUE THREAD

**Issue by dannykopping** [grafana/grafana#29977]
**What happened**:

It appears there has been a regression in the Table panel display between 7.3.4 and 7.3.5. I believe I've tracked this regression down to this commit:
https://github.com/grafana/grafana/commit/70bf01f4f9acdf552bc3e4e2638055f666c3e3f1

**What you expected to happen**:

In v7.3.4, a `table` panel using a Prometheus datasource and two transforms (_Series to rows_ and _Filter by name_) resulted in the following:
![7 3 4](https://user-images.githubusercontent.com/373762/103071533-72681200-45cc-11eb-93a2-a18ca2540b8e.png)

Note the "Value" column in the output.
This "Value" column was also selectable in the _Filter by name_ transform:
![image](https://user-images.githubusercontent.com/373762/103072030-82342600-45cd-11eb-8803-f1ad9db1f47b.png)

In other words, regardless of the data this "Value" column could be selected.

**How to reproduce it (as minimally and precisely as possible)**:

Using the [Prometheus - Demo Dashboard](https://play.grafana.org/d/000000029/prometheus-demo-dashboard?tab=transform&orgId=1&refresh=5m&editPanel=1&theme=dark) (play.grafana.net uses v7.3.6 currently):

1. Convert the visualisation to a table
2. Add a _Series to rows_ transform
3. Add a _Filter by name_ transform

Note the "Value" column now takes on the value of the first entry in the given data:
![image](https://user-images.githubusercontent.com/373762/103072180-c7585800-45cd-11eb-9fb4-92f9d2bc43be.png)
![image](https://user-images.githubusercontent.com/373762/103072224-db9c5500-45cd-11eb-923f-94db9d465345.png)

If we change the query to now change the output (i.e. change from `iowait` to something else (in this case `idle`):
```promql
sum by(mode)(irate(node_cpu_seconds_total{job="node", instance=~"$node:.*", mode!="iowait"}[5m])) > 0
```
We then see the first value showing up at the column name:
![image](https://user-images.githubusercontent.com/373762/103072342-071f3f80-45ce-11eb-9e9f-ec0f62d0d4bf.png)

**Anything else we need to know?**:

One can programmatically select the "Metric" and "Value" columns across both v7.3.4 and v7.3.5 using `\b(?!(?:Time)\b).*` as the pattern in the _Filter by name_ transform.

**Comment by hugohaggmark** [comment]
Adding this to @grafana/observability-squad because of the referred commit, feel free to pass it over to us again.

**Comment by zoltanbedi** [comment]
Hi @dannykopping,
So this was a bug introduced by https://github.com/grafana/grafana/pull/27737 and fixed in https://github.com/grafana/grafana/pull/28842. So I'm not sure if we want to "fix" this or not. Thoughts @davkal?

**Comment by torkelo** [comment]
think this is a bug in series to rows transform, it should not getFieldDisplayName for both the frame and value field

**Comment by torkelo** [comment]
Have fix here: https://github.com/grafana/grafana/pull/30054

**Comment by dannykopping** [comment]
Many thanks!
