### ISSUE TITLE
Annotations: Viewer can open "Add Annotation" modal (but they cannot create annotation, which is correct) 

### ISSUE THREAD

**Issue by Grrrolf** [grafana/grafana#29972]
**What happened**:
Users with the role viewer are allowed and able to create annotations but when they click the save-button they receive the message "Access denied to this dashboard".

![annotations](https://user-images.githubusercontent.com/10052794/103011272-f1603a80-4539-11eb-8b09-152acec74190.gif)
 
**What you expected to happen**:
The expected behaviour is that once the user with viewer role clicks the save-button that the annotation is saved. The alert pop-up should then say: "Annotation added" and have a green background.

**How to reproduce it (as minimally and precisely as possible)**:
* Log in as a user with the role viewer
* open a dashboard with a graph panel
* click the graph panel and select 'add annotation'
* add a description
* click save-button

**Anything else we need to know?**:
I found this issue: https://github.com/grafana/grafana/issues/9991
This issue is labeled as a a feature request, however, it does not mention that a viewer can already add an annotation, but cannot save it.

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: data source used -- grafana -- with query randomwalk to create the graph panel
- OS Grafana is installed on: ms windows os version 10
- User OS & Browser: ms windows os version 10 - firefox
- Grafana plugins: default plugins
- Others: none

**Comment by torkelo** [comment]
Strange, viewers should not be allowed to add annotations. Must be a bug that this add annotation view is open: 
https://github.com/grafana/grafana/issues/9991

**Comment by Grrrolf** [comment]
This turned 180 degrees, not what I expected ;-)
I have upvoted https://github.com/grafana/grafana/issues/9991.

99% of our Grafana users are viewers and they start asking us authorization for creating annotations in graph panels. However, we do not want to give them editor access since an editor has access to data we do not want viewers have access to. Also, there are rules and regulations that dictate us not giving them from access to data they should not have access to.

**Comment by torkelo** [comment]
Just to double check. 

@Grrrolf how do you limit access to data for viewers? 

There are no data source permissions unless you run Grafana Enterprise. Viewers can still access all data (issue any query).
https://grafana.com/docs/grafana/latest/permissions/#data-source-permissions

**Comment by Grrrolf** [comment]
@torkelo, viewers in our Grafana have default viewer access. I know that the more technical viewers are able to change the underlying queries, we have not yet considered limiting access to data on data source level. _Quick question: If we limit access to a data source, may I assume that the dashboards/panels still work?_

**Comment by torkelo** [comment]
>  Quick question: If we limit access to a data source, may I assume that the dashboards/panels still work?

They work for users who have access to the data source but will show a small error for users without query access to that data source
