### ISSUE TITLE
Grafana world map panel shows provinces only in USA, not for all countries.

### ISSUE THREAD

**Issue by RuchaBapat** [grafana/grafana#29979]
We are using Grafana world map panel. We have a database having mapping of ips to countries, country iso codes, provinces and province iso codes. We are using maxmind database. When we try to use province iso codes mapped with states column in Grafana wolrd map panel, map only shows provinces in USA not in all countries. 

Is there any specific format or names Grafana expects from province iso codes? If yes, where can we find that? 

- Grafana version: v6.7.4
- Data source type & version: Azure data explorer
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome and firefox
- Grafana plugins: World map panel 0.2.1

**Comment by hugohaggmark** [comment]
Thank you for reporting this repo is for the main Grafana app, for plugins might I suggest you report this issue in that repo https://github.com/grafana/worldmap-panel/issues. Thank you!
