### ISSUE TITLE
Docs feedback: /dashboards/share-panel.md

### ISSUE THREAD

**Issue by linucks** [grafana/grafana#29982]
The iframe just below the following link (https://grafana.com/docs/grafana/latest/dashboards/share-panel/#embed-panel
) where the documentation states: "Below there should be an interactive Grafana graph embedded in an iframe:", displays the following message:

```
If you're seeing this Grafana has failed to load its application files

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarn build

4. Sometimes restarting grafana-server can help
```

The iframe element that displays the error is:

<iframe src="https://snapshot.raintank.io/dashboard-solo/snapshot/y7zwi2bZ7FcoTlB93WN7yWO4aMiz3pZb?from=1493369923321&amp;to=1493377123321&amp;panelId=4" width="650" height="300" frameborder="0"></iframe>

**Comment by hugohaggmark** [comment]
Thank you for taking the time to report this @linucks and I know that we upgraded the snapshot server recently, so this seems to be resolved now as I can't see any error message.

**Comment by hugohaggmark** [comment]
![image](https://user-images.githubusercontent.com/562238/103193149-cb40ee80-48db-11eb-9994-4703ad666ee8.png)
