### ISSUE TITLE
MySQL: Support SSL connections

### ISSUE THREAD

**Issue by stanhu** [grafana/grafana#2998]
Currently it looks like SSL connections are only supported with PostgreSQL. While the go-sql-driver does support TLS/SSL, Grafana and xorm don't appear to support it at the moment. It sounds like the `tls` parameter will be needed, and `RegisterTLSConfig` will need to be called:
- https://github.com/go-sql-driver/mysql#tls
- https://godoc.org/github.com/go-sql-driver/mysql#RegisterTLSConfig

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/3584
