### ISSUE TITLE
grunt phantomjs-related warning message

### ISSUE THREAD

**Issue by vkroz** [grafana/grafana#2999]
Environment: MacOS Yosemite

```
cd $GOPATH/src/github.com/grafana/grafana 
grunt

.....
Running "phantomjs" task
Warning: Unable to read "./node_modules/karma-phantomjs-launcher/node_modules/phantomjs/lib/location.js" file (Error code: ENOENT). Used --force, continuing.
.....
```

**Comment by torkelo** [comment]
ping @fg2it

**Comment by fg2it** [comment]
@torkelo i will look into that but I won't be able to do so before a few days.
@vkroz can you confirm phantomjs was installed ? should see some log before the warning.

**Comment by fg2it** [comment]
@vkroz can you tell me if you have the `location.js` file in `$GOPATH/src/github.com/grafana/grafana/node_modules/phantomjs/lib/` ?

**Comment by torkelo** [comment]
Can you run npm install again? any errors? Try upgrading nodejs

**Comment by fg2it** [comment]
@torkelo i think i understand what is happening (not yet why) : the install location of phantomjs node module seems to be `./node_modules` and not `./node_modules/karma-phantomjs-launcher/node_modules`. Would be nice to understand why and to find a way to rely `node` to find the correct path.

**Comment by vkroz** [comment]
@fg2it @torkelo 
Details as you requested: 
```
$ phantomjs -v
2.0.0
$ which phantomjs
/usr/local/bin/phantomjs
```

Actually it's turned out this is not a blocking error. After completing install steps according to http://docs.grafana.org/project/building_from_source/ guide I was able to run graphana server. But error is scary on first sight and better to be removed (or documented :) )

**Comment by fg2it** [comment]
@vkroz thanks for the details. It confirms my hypothesis.
You can in deed `--force` but something is hidden : you won't have the correct `phantomjs` binary in the end, so you will miss the ability to create png of your dashboard. So, a warning, with the ability to ignore it, have my vote. But, you should not have this warning. 

Your node module list is a bit strange, it seems most of the modules are not installed. To help me diagnose, could you, from `$GOPATH/src/github.com/grafana/grafana/` run, in order, `npm ls` then `npm install` and again `npm ls` and provide the output ?

**Comment by justin8** [comment]
FYI, mine has the full set of packages installed by npm install and still gets this issue. If you cd in to `node_modules/karma-phantomjs-launcher` and run `npm install` it installs in the right location and the build can continue.

**Comment by fg2it** [comment]
@justin8 thanks for your feedback. Could you provide the log printed during your `npm install` ?

**Comment by felixbuenemann** [comment]
Same issue here, it's because npm 3.0+ dedups node modules by default and stores them in a flat directory structure. I'll make a PR with a fix.

**Comment by felixbuenemann** [comment]
For those that encountered the issue, please test if it's fixed in current master and report back, so this issue can be resolved.

**Comment by krise3k** [comment]
Same issue on grafana@v2.6.0-beta1
I think it's because npm3 don't install peer dependencies https://docs.npmjs.com/files/package.json#peerdependencies

After adding  `"phantomjs": "^1.9",` to grafana `package.json`, it's working fine.

**Comment by nlamirault** [comment]
My task to build Grafana 2.5 on Alpine Linux [1] have same issue.

[1] : https://circleci.com/gh/portefaix/docker-grafana/15

**Comment by grobie** [comment]
I ran into the same issue.

HEAD: c0cf0cb802adad24252ce1307c4c896edd566870
grunt-cli v0.1.13
grunt v0.4.5


```
{ grafana: '3.0.0-pre1',
  npm: '3.5.2',
  ares: '1.10.1-DEV',
  http_parser: '2.6.0',
  icu: '56.1',
  modules: '47',
  node: '5.3.0',
  openssl: '1.0.2e',
  uv: '1.8.0',
  v8: '4.6.85.31',
  zlib: '1.2.8' }
```

**Comment by marcopeise** [comment]
same issue with grafana version: "3.0.0-pre1" here.

npm install log had two warnings:
npm WARN EPEERINVALID karma-phantomjs-launcher@0.2.1 requires a peer of phantomjs@>=1.9 but none was installed.
npm WARN EPEERINVALID eslint-config-standard@4.4.0 requires a peer of eslint-plugin-standard@^1.1.0 but none was installed.

After adding ```"phantomjs": "^1.9"``` and ```"eslint-plugin-standard": "^1.1.0"```, to grafana package.son (dependencies), it worked to build.

complete decencies are now:
```
"dependencies": {
    "es5-shim": "^4.4.1",
    "grunt-jscs": "~1.5.x",
    "grunt-sync": "^0.4.1",
    "karma-sinon": "^1.0.3",
    "lodash": "^2.4.1",
    "sinon": "1.16.1",
    "systemjs-builder": "^0.14.15",
    "tslint": "^3.2.0",
    "typescript": "^1.7.5",
    "phantomjs": "^1.9",
    "eslint-plugin-standard": "^1.1.0"
  }
```

**Comment by torkelo** [comment]
fixed in master with recent commit

**Comment by wangmzdl** [comment]
build from version v4.0.1, it's still there

**Comment by gaozhidf** [comment]
got same problem today when i follow guide to get source code and build

ubuntu 16.0.4
node v6.9.1
npm 4.0.5

**Comment by ikrabbe** [comment]
still broken or again broken

**Comment by daniellee** [comment]
@ikrabbe works on my machine :wink: so I think it is probably something to do with your environment.

What error did you get? The same as the original error from Oct 22, 2015?

**Comment by ikrabbe** [comment]
yes its the same error warning about a missing location.js
Meanwhile I removed node_modules and did the whole setup procedure again. Now it works.

**Comment by daniellee** [comment]
Sounds like you didn't follow the instructions for building from source: http://docs.grafana.org/project/building_from_source/#building-grafana-from-source
