### ISSUE TITLE
Ability to shift time in timepicker

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#300]
In zabbix timepicker has nice ability to shift time back and forth:

![zabbix](http://puu.sh/81Omv.png)

On the top you choose time range, on the bottom you may shift timespan. This is quite useful to compare current day with previous or even current hour today with the same hour yesterday.

I think it would be nice to have the same thing in grafana as well.

**Comment by worrel** [comment]
+1 for the ghosted overlay timeshift graph like the image above.  Makes comparing between timeshifted data much easier.

**Comment by markusr** [comment]
+1, The ghosted overlay timeshift is nice but a shift time forward and backward button would be already a good start.

**Comment by Dieterbe** [comment]
IMHO graphite's `timeShift()` is not a good solution.  while useful, it does alter the timestamps. so when you want to know at what exact time something happened and you hover over a point it gives you a datetime you still have to do the mental work of subtracting 7 days or whatever, which is really annoying if you have to go back into a previous month.

**Comment by torkelo** [comment]
@Dieterbe timeShift (alter timestamps) is the only solution when you want different time periods on the same graph.

**Comment by Dieterbe** [comment]
that's unfortunate.  i see that more as a limitation in flot that should be addressed.

**Comment by torkelo** [comment]
@Dieterbe but how would you solve it? multiple time axis? how to know which series belong to which time axis?

**Comment by Dieterbe** [comment]
well,
* in all the timeshifts i have ever done (and i think the same applies here) there's always plenty of common stuff to put in the x-axis labels. if you're comparing 2 days you can put the times. if you're comparing weeks you can put day names (but not date or day of the month cause it would differ for the series), if you're comparing months, you can put days of the month.
* if you want full date+time to be shown on the axis for both graphs, then with flot yes you probably need 2 xaxis. how to relate one to the other.. maybe through by coloring the xaxis or its labels in the same color as the graph. not sure if it's possible in flot but it should be.

**Comment by krise3k** [comment]
+1

**Comment by max3163** [comment]
+1

**Comment by trent** [comment]
+1

**Comment by friesoft** [comment]
+1

**Comment by hurtauda** [comment]
+1

**Comment by martintamke** [comment]
+1

**Comment by TAiS46** [comment]
+1

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)
