### ISSUE TITLE
[FeatureRequest] LogsPanel: Add option to change maximum number of Rows to render

### ISSUE THREAD

**Issue by mizeng** [grafana/grafana#30001]
**What happened**:
I can only see 500 lines of logs in LogsPanel. When I tried to tune "Query options", either "Max data points" or "Interval" does not work. (Interval can not be changed)

**What you expected to happen**:
There's an option can tuned to change the output line number of logs.

**How to reproduce it (as minimally and precisely as possible)**:
Just create a LogsPanel dashboard, and choose Loki data source, use a query that contains >500 line logs.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: Loki, LogsPanel
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mizeng** [comment]
![Screen Shot 2020-12-29 at 9 01 37 AM](https://user-images.githubusercontent.com/8059086/103251792-50e49d00-49b5-11eb-816b-462e8bda7867.png)

**Comment by hugohaggmark** [comment]
@mizeng thank you for taking the time to create this issue. I think we have a hard limit for that one here:
https://github.com/grafana/grafana/blob/375e8e4fd051a5c821c2b477634c73166d0694ab/packages/grafana-ui/src/components/Logs/LogRows.tsx#L14

We could probably add this option to the panel so I'll change this to a feature request and assign @grafana/observability-squad

**Comment by mizeng** [comment]
it took me hours to find this..  Thanks for comments, and very looking forward to this configurable param.

**Comment by ivanahuckova** [comment]
Added in https://github.com/grafana/grafana/pull/29356. It will be part of the next (7.4) release.
