### ISSUE TITLE
Stat Panel doesn't like Last

### ISSUE THREAD

**Issue by neel-m** [grafana/grafana#30007]
**What happened**: Using a Stat panel to provide a total number across a number of series (from InfluxDB). The numbers don't add up correctly

I have a measurement that has 33 unique tag values.  The values are increasing counters of modem data errors for each of the data channels.  I want a single number to be a total of all of the errors.  Since the numbers are total counters, I use LAST from InfluxDB to get the data for each channel.  I also tell it to only get one data point (but it still gets a minimum of two, more for longer time periods).  The numbers that InfluxDB returns appear to be correct (they match what the modem UI says).  I have attached a sample query output.  I then tell Grafana to take the Last value.  This appears to work sometimes.  I have also told it to use MAX, which should really be the same (assuming that is within a series).

When I use a graph, the results look like what I expect.  When I change the visualization into a Stat panel, it gets interesting.  With no Transform, I get 33 numbers that look correct.  The largest number is about 44.5 million.  (It works for both Last and Max).  The trouble comes when I apply a Transform to the data (to reduce the 33 numbers to a single number).  If I have Last in the Display Calculation and (anything really, but say Total) in the Transform calculations, I get 0 for the total.  If I change Display Calculation to Max (which should give the same data, since the last value should be the highest), I get a number.  Sometimes that number looks close to what it should be, but it isn't.  It appears to be the max of the series not the total (remember the I selected Total for the Transform calculation).  Other times I get a number that appears to be double that (it is probably adding the two values from InfluxDB (instead of using the last one, or max one)).

Here is the query data (JSON as txt to be able to upload it)
[query_data.txt](https://github.com/grafana/grafana/files/5752353/query_data.txt)

Here is the panel JSON
[panel.json.txt](https://github.com/grafana/grafana/files/5752358/panel.json.txt)

Previously I was using this same dashboard on: v7.0.1 (ef5b586d7d)
The transform UI crashes on that version, so I moved to an instance running: Open Source
v7.3.4 (14c494085e).  I see there is a newer version available, but did not see anything that said this issue was solved.  I will try it anyway.

**What you expected to happen**: The Transform calculation to add up the last values from each of my 33 series and get a number around 46mil instead of 45 (when it appears to be taking the max) or 90 (when it appears to be taking the max channel and summing the 2 values that are in the query results).

**How to reproduce it (as minimally and precisely as possible)**:
If the enclosed query data and panel.json are not enough, I will have to figure out a way to reproduce this issue.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: InfluxDB (Core)
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10, Edge
- Grafana plugins: none for this
- Others:

**Comment by neel-m** [comment]
Maybe I am not holding it right, but I have been unable to figure out exactly how to hold the Stat Panel.  It seems like it could be a really great thing.  How I want to use it seems simple enough and it seems like that should be something it should support.  I want it to aggregate the information from more than one series.  This seems to confuse it and so it gives strange results. 

Here is a simple repo:
Enable TestDataDB
Select it
Set it up for Random Walk (CSV doesn't seem to support multiple series)
2 series
0.5 spread
0 noise
Set query options for 10 data points to make the math easier
Set Visualization for Graph to see the data, mine is 25-26 and 47-49
Now set the Visualization for Stat
I see the two series and select Last to show the Last value (26 and 47)
Click on Display all values to see the numbers, got back to calculate
Click on Transform (it defaults to Series to rows and Max)
Remove Max and add Total.
I expected to get 26+47=73, instead I get 571.
That is some seriously new math, since I am not sure how you can get 571 from adding up those numbers.

**Comment by hugohaggmark** [comment]
Hi @neel-m  and thank you so much for taking the time to write such a detailed issue with excellent repro steps. I'll try to explain why this is the expected behaviour. Firstly, I've created a [dashboard on Grafana Play as an example using CSV metrics ](https://play.grafana.org/d/vXNQQXxMk/stat-panel-doesnt-like-last-30007?orgId=1)so the values don't change with dashboard refresh.

In that example, we have 2 series with the following values:
A: 
ts1 | ts2 | ts3 | ts4 | ts5| ts6
--: | --: | --: | --: | --: | --:
10 | 20 | 90 | 30 | 50|0

B:
ts1 | ts2 | ts3 | ts4 | ts5| ts6
--: | --: | --: | --: | --: | --:
11 | 22 | 19 | 32 | 15| 1

And in the Graph legend you can see the following aggregations:

A:
min | max | avg | current | total
--: | --: | --: | --: | --:
0 | 90 | 33 | 0 | 200

B:
min | max | avg | current | total
--: | --: | --: | --: | --:
1 | 32 | 17 | 1 | 100

When you select the Last value in the Stat Panel you should see the last value from both series:
![image](https://user-images.githubusercontent.com/562238/103332389-05d89180-4a6a-11eb-8a87-3b48a7a6f884.png)

When you add the Reduce transformation you reduce the A & B series into a single Series, let's call it X-Series with two fields that have two `Total` values.

X: 
ts1 | ts2 
--: | --: 
200 | 100

Finally, when the statpanel then shows the Last value, it will take `100` value from the X-series. I hope this explains what is going on.

Also, you can easily debug any input/ouput of a transform by clicking the little beetle icon in the transform UI.
![image](https://user-images.githubusercontent.com/562238/103332648-1d644a00-4a6b-11eb-9e82-cce605cc2027.png)

**Comment by Frogmore42** [comment]
Thanks for the tips.  The docs were less than complete on the TestDataDB and I found no other information on the internet about how to use it.

So, what is the way to get the behavior I want?
If I limit the series to provide a single number, I still get two, which means the summed result will be about double what the real answer is.

Perhaps another transformation or option to the current one?

If you give me a pointer to the general location of the code, I would be willing to see if I can create a PR to solve my issue.

It seems like the ability to add up the results of a previous calculation of a set of series is a feature that would be useful for many situations.

**Comment by neel-m** [comment]
Thanks for answering and providing the link to the playground and the debug.  That is really helpful and for the tip on how to create multiple series with CSV.  Using that information, I was able to figure out how to get the Stat panel to do what I want.  It turns out the mental model I had for how it worked was incorrect.  There is one thing that one needs to understand in order to get expected results:

1. Precedence/order of operations

I assumed that Transforms operated after Display --> Show --> Calculate, but that is incorrect.  Transforms are done first, which does make sense, but was not obvious (to me, at least).  Now that I have read the documentation, it is stated there: https://grafana.com/docs/grafana/latest/panels/transformations/

> Transformations process the result set of a query before it’s passed on for visualization.

With that critical piece of information, it now becomes easy to achieve what I want/need.  I just need two transformations and one display calculation.

1. Series to rows, Last (not null) to get the latest value from each series
2. Series to rows, Total (to add the multiple lastest values together)
3. Display, Calculate, looks like either Last or Total would work here based on the data I am seeing, seems like Last might be the more correct.

It's still a little odd (to me) that transform always returns two items, but it works fine.  Part of the reason this was confusing is that it worked fine using it the "wrong" way for data that was different.  I have another set of metrics that are not cumulative, so for these, it is necessary to sum the individual series values to get a total value for each series and then total those to get the desired number.  So, total for one transform and also for Display Calculate works fine.  Since they are the same function, doing only one will return the same results either way.

Anyway, thanks for providing the critical piece of information I needed, and the tips on how to understand what Grafana is doing.
