### ISSUE TITLE
Please reopen #2940

### ISSUE THREAD

**Issue by commarla** [grafana/grafana#3001]
Hi
I have answered to the issue #2940
https://github.com/grafana/grafana/issues/2940

Can you reopen it?

Thanks,

**Comment by commarla** [comment]
Nevermind I found my problem.

My bad.

Thanks

**Comment by ARKII** [comment]
Hey, I have encountered this problem.
Can you give me some information or tips to figure it out?

**Comment by zstyblik** [comment]
@arkii, I have encountered this as well. It helped to remove all organizations I've created. I have no idea what the fix nor what to make of #2940 though.

**Comment by arkii** [comment]
@zstyblik ,  I think this line `auto_assign_org = true` in grafana.ini, helped to prevent this problem.

**Comment by zstyblik** [comment]
@arkii that's not the problem, unfortunately.

@torkelo, if grafana super admin is enabled, shouldn't it be automatically added to organizations created by a admin(admin, but not super admin) user?

It seems to me this comes from combination of Grafana super user, LDAP, absence of `[[servers.group_mappings]]` for organization in question and organization created by admin the `joe`, but not super admin the `admin`. When admin the `joe` signs out, he cannot sign in until super admin `admin` is added into newly created organization.

But may be one shouldn't be using super admin in the first place and have it disabled :)

**Comment by arkii** [comment]
got it, thanks.

**Comment by anhlqn** [comment]
I ran in to the same issue on Grafana 3.1.0, and setting `auto_assign_org = true` resolved the issue.

I had group search filter configured, but whenever a new user signed in, a new org named after the user's email would be created, and user could not sign in with error message:

> msg="Error while trying to authenticate user" logger=context userId=0 orgId=0 uname= error="Cannot remove last organization admin"

I had to delete the org so that the user could log in.
