### ISSUE TITLE
Variables: Support chained variables for data sources using object queries

### ISSUE THREAD

**Issue by jbguerraz** [grafana/grafana#30013]
**What happened**:

When variable query is an object, with nested objects, then selecting a value of a variable doesn't refresh chained variables values.

**What you expected to happen**:

Chained variables are refreshed next to a change.

**How to reproduce it (as minimally and precisely as possible)**:

CF https://github.com/grafadruid/druid-grafana/blob/master/CONTRIBUTE.md
Add a Druid datasource using URL http://broker:8082
Import dashboard.json available in repository root directory.
Comment workarounds line 35 and 42 from `src/VariableQueryEditor.tsx` (or checkout https://github.com/grafadruid/druid-grafana/commit/54c4db89fb132b7d2d27fb974da113c126e4261f )
Go to dashboard, change country, city isn't refreshed.

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/861556/103363996-d9019a00-4abc-11eb-9db7-e533886794ca.png)

![image](https://user-images.githubusercontent.com/861556/103364007-e028a800-4abc-11eb-9e71-6835f84e4150.png)

See https://github.com/grafana/grafana/blob/master/public/app/features/variables/utils.ts#L52

A quick workaround would be to stringify the object (JSON.stringify), otherwhise, maybe traverse the object recursively to lookup for variables.

NB: Here it's a SQL query, which could drive you wondering why such a nested structure is used; Druid uses JSON for queries (or eventually SQL), which then can produce rather complex JSON like this:

```{
  "queryType": "groupBy",
  "dataSource": "sample_datasource",
  "granularity": "day",
  "dimensions": ["country", "device"],
  "limitSpec": { "type": "default", "limit": 5000, "columns": ["country", "data_transfer"] },
  "filter": {
    "type": "and",
    "fields": [
      { "type": "selector", "dimension": "carrier", "value": "AT&T" },
      { "type": "or",
        "fields": [
          { "type": "selector", "dimension": "make", "value": "Apple" },
          { "type": "selector", "dimension": "make", "value": "Samsung" }
        ]
      }
    ]
  },
  "aggregations": [
    { "type": "longSum", "name": "total_usage", "fieldName": "user_count" },
    { "type": "doubleSum", "name": "data_transfer", "fieldName": "data_transfer" }
  ],
  "postAggregations": [
    { "type": "arithmetic",
      "name": "avg_usage",
      "fn": "/",
      "fields": [
        { "type": "fieldAccess", "fieldName": "data_transfer" },
        { "type": "fieldAccess", "fieldName": "total_usage" }
      ]
    }
  ],
  "intervals": [ "2012-01-01T00:00:00.000/2012-01-03T00:00:00.000" ],
  "having": {
    "type": "greaterThan",
    "aggregation": "total_usage",
    "value": 100
  }
}
```

CF https://druid.apache.org/docs/latest/querying/groupbyquery.html

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: Druid v0.0.0
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Chrome
- Grafana plugins: Druid
- Others: Nothing :) 

I'd be happy to provide a PR in order to deliver a quick fix using `JSON.stringify` and/or maybe discuss a better fix and deliver with brand new Variables API in Grafana 8 ?

**Comment by torkelo** [comment]
Thanks for reporting this, think your right we need to stringify the query object to detect variables

**Comment by jbguerraz** [comment]
@torkelo right, here it is: https://github.com/grafana/grafana/pull/30056
Thank you!
