### ISSUE TITLE
Default "login_maximum_lifetime_duration" value doesn't match documentation

### ISSUE THREAD

**Issue by wywywywy** [grafana/grafana#30019]
In the example `grafana.ini` file, it says -

> The maximum lifetime (duration) an authenticated user can be logged in since login time before being required to login. Default is 30 days (30d). This setting should be expressed as a duration, e.g. 5m (minutes), 6h (hours), 10d (days), 2w (weeks), 1M (month).

But in the code, the `login_maximum_lifetime_duration` is defaulted to `7d`.

https://github.com/grafana/grafana/blob/375e8e4fd051a5c821c2b477634c73166d0694ab/pkg/setting/setting.go#L1038-L1049

**Comment by wywywywy** [comment]
@Hansuuuuuuuuuu @marefr 

Commit 8d971ab2f2a834d7dd1b48073d5a67480a6a9809
PR #27150

**Comment by papagian** [comment]
thank you for reporting this!
