### ISSUE TITLE
[FeatureRequest] Grafana Toolkit: Example custom plugin with ModuleFederationPlugin 

### ISSUE THREAD

**Issue by EnricoBeltramo** [grafana/grafana#30026]
I tried to create a custom plugin with Module Federation provided by webpack 5, but I'm not able to instert it.
I added follow custom webpack configuraton file:
`
const HtmlWebpackPlugin = require("html-webpack-plugin");
const ModuleFederationPlugin = require("webpack").container
  .ModuleFederationPlugin;
const path = require("path");

module.exports.getWebpackConfig = (config, options) => {
    let newConf = {
      ...config,
      plugins: [...config.plugins,
        new ModuleFederationPlugin({
            name: "app1",
            // adds react as shared module
            // version is inferred from package.json
            // there is no version check for the required version
            // so it will always use the higher version found
            shared: {
              react: {
                import: "react", // the "react" package will be used a provided and fallback module
                shareKey: "react", // under this name the shared module will be placed in the share scope
                shareScope: "default", // share scope with this name will be used
                singleton: true, // only a single version of the shared module is allowed
              },
              "react-dom": {
                singleton: true, // only a single version of the shared module is allowed
              },
            },
          }),
        new HtmlWebpackPlugin({
            template: "./public/index.html",
          }),
        ],
    };
    // console.log("config", newConf)
    return newConf;
  };
`

but I have follow error:

- Bundling plugin in dev mode  Trace: TypeError: Cannot read property 'includes' of undefined
      at ModuleFederationPlugin.apply (D:\Progetti\Inventio\InMindSO\InMind\grafanaplugins\my-grafana-plugin\node_modules\webpack\lib\container\ModuleFederationPlugin.js:45:49)

Looks to be a webpack compatibility issue

**What would you like to be added**:
Compatibility with webpack 5 and ModuleFederationPlugin

**Why is this needed**:
Is possible to add a working example with ModuleFederationPlugin?

**Comment by hugohaggmark** [comment]
Hi @EnricoBeltramo, do I understand correctly that you're trying to use a webpack 5 plugin together with a custom Grafana plugin created by grafana toolkit? 

AFAIK we're still using webpack 4 so this will probably not addressed before we upgrade to webpack 5.

**Comment by EnricoBeltramo** [comment]
Yes, I have a plugin where part of view is dynamically loaded depending of data read from datasource. Is planned in future the upgrade of grafana to webpack 5?

**Comment by tolzhabayev** [comment]
Not relevant anymore due to https://github.com/grafana/grafana/issues/70042
