### ISSUE TITLE
Data not showing past 1 day in Grafana but is fine in Graphite

### ISSUE THREAD

**Issue by glenrfoster** [grafana/grafana#3002]
I've got a very strange problem where the data points in Grafana are stopping at 1day. I've attached a screenshot to show the data coming through fine in Graphite for 2 days and then the same query in Grafana but only showing one day. The render request is sending -2d but the returned json only has 1 day of data in it. Does anyone have any ideas what I might be doing wrong?

Thanks in advance!

![grafana1](https://cloud.githubusercontent.com/assets/15244703/10660150/bb8fc214-789c-11e5-85ba-fdd9bda82086.PNG)
![graphite](https://cloud.githubusercontent.com/assets/15244703/10660149/bb8ea546-789c-11e5-8ba2-306f3436b9f8.PNG)

**Comment by torkelo** [comment]
Not sure, but since graphite is not returning the data it is a graphite issue. Check your graphite storage schemas, also check the graphite server's time and make sure it is correct.

**Comment by glenrfoster** [comment]
Hi Torkel,

The screenshot of Graphite shows that it is returning data for both days so it would appear to be a Grafana issue. Is there any more information I can provide that might help debug it?

Thanks,

Glen

**Comment by glenrfoster** [comment]
Sorry, you're right! I thought the graphite view was 48 hours but it's actually just 24 hours. I'll go back to the drawing board!

Glen
