### ISSUE TITLE
Accessing another datasources credentials from a plugin backend

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#30036]
**What would you like to be added**:
Some sort of way for a plugin backend to get credentials for another datasource. Or otherwise a way for it to make POST requests to another datasource, that include credentials.

**Why is this needed**:
Cloud Alerting UI plugin allows users to pick a prometheus datasource (usually  cortex) and manage alerting & recording rules on it. This requires the plugin to make POST requests to the selected datasource, which is forbidden for prom when using built-in datasource proxy: https://github.com/grafana/grafana/blob/master/pkg/api/pluginproxy/ds_proxy.go#L241
Currently we work around this by adding a "Ruler" datasource for each prometheus datasource, which has all the same credentials copied. But configuring this ruler datasource can be a hurdle for users who want to use Cloud Alerting with their existing prom datasources, it would be neat to get rid of this workaround

I thought one idea would be add a custom backend to Cloud Alerting plugin that would provide an alternative proxy for prom datasources. But this would require the backend to somehow get auth credentials for arbitrary datasources to be able to make requests to them. Seems currently this is not supported by the plugin system. Any other ideas are welcome as well!

Note that this is not critical, but nice to have

**Comment by domasx2** [comment]
@ryantxu, @marefr , maybe you have some thoughts on this? Thanks!

**Comment by ryantxu** [comment]
My thought is that plugins should be able to query other datasources -- I don't think the credentials should be passed to other plugins, but we should be able to query

**Comment by domasx2** [comment]
> My thought is that plugins should be able to query other datasources -- I don't think the credentials should be passed to other plugins, but we should be able to query

Would work, as long as it's not subject to the same limitations that datasource proxy  endpoint has

**Comment by torkelo** [comment]
I think the main problem with reusing the same data source and credentials is security, the data source should only use a read-only API key that cannot modify things as any user can issue any possible http request using those credentials (via the proxy)

**Comment by domasx2** [comment]
> I think the main problem with reusing the same data source and credentials is security, the data source should only use a read-only API key that cannot modify things as any user can issue any possible http request using those credentials (via the proxy)

Yeah, If datasource has a read-only API key configured, my proposed approach wouldn't work, good point. I guess then we can't really get away from using additional datasource to hold credentials that allow writing

**Comment by torkelo** [comment]
Creating an additional data source also opens up security issues as that will also be open to any user to access (even viewers).

The way we solved this before was via "app routes" , and app can store credentials (settings) per org that can be accessed via these routes:
https://github.com/grafana/kentik-app/blob/master/src/plugin.json#L8

**Comment by domasx2** [comment]
routes can be configured for datasource plugins as well, we allow only Admin to POST, PUT or DELETE via the additional data source: https://github.com/grafana/alerting-ui-plugin/blob/master/src/datasources/ruler/plugin.json#L9

Datasources are very handy for credentials storage, as they also come with UI to view/manage.

**Comment by torkelo** [comment]
ah, that is great. Yea a data source is much better for this as you can have multiple per org (which you cannot for app settings)

**Comment by domasx2** [comment]
Gonna abandon this idea for now, closing hte issue. Thanks for the input!
