### ISSUE TITLE
Fix enterprise2 package build

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#30037]
**What happened**:
Enterprise2 package step interferes with enterprise package step (and vice versa), due to the build pipeline tool seemingly trying to sign both enterprise and enterprise2 packages at the same time:

```
Invoking rpm with args: [--addsign dist/grafana-enterprise-7.4.0~2080pre-1.x86_64.rpm dist/grafana-enterprise2-7.4.0~2080pre-1.x86_64.rpm]
```

We need to fix so the packaging steps don't interfere with each other.

**Comment by torkelo** [comment]
enterprise2 ? what is that?

**Comment by aknuds1** [comment]
@torkelo It's [this](https://drone.grafana.net/grafana/grafana-enterprise/2091/1/30) type of failure.
