### ISSUE TITLE
Ability to not connect data points in a graph panel plot if time between them exceeds specified value

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30047]
**What would you like to be added**:
The option to not connect data points in a graph panel plot if the time between those points exceeds a time difference specified in the panel options.

**Why is this needed**:
For data where we have large gaps over time, it is often not desirable for us to have the data points at the beginning and end of the gap connected.

For example, I want to avoid the long line seen across the gap here:
![image](https://user-images.githubusercontent.com/7028403/103582681-957fa500-4e9b-11eb-80b9-02ece57d1ecd.png)

**Comment by torkelo** [comment]
For gaps, it's up the query & data source to insert null values to inform the Graph where missing data exists

**Comment by torkelo** [comment]
Most data sources can do this, what data source are you using?

**Comment by nabelekt** [comment]
I should be more clear: I want the option to not connect across gaps, not where there is data "missing", but where there is no data at all. I.e., I want what the graph would show if we inserted a row of all null values with a datetime in the middle of the gap.

For example:

If my data looks like:
![Screenshot 2021-01-05 120347](https://user-images.githubusercontent.com/7028403/103687863-2fa02580-4f4e-11eb-8149-2cd2b0efd7c8.png)

I get:
![image](https://user-images.githubusercontent.com/7028403/103687911-45ade600-4f4e-11eb-8521-df94dd788e72.png)


And if my data looks like:
![image](https://user-images.githubusercontent.com/7028403/103687944-56f6f280-4f4e-11eb-9fcb-fcea5e0f087c.png)

I get:
![image](https://user-images.githubusercontent.com/7028403/103687986-670ed200-4f4e-11eb-9fdd-64eed206adf8.png)


I need the ability for the data to look like the first, but display like the second in Grafana. With the unconnected gap time difference being a parameter.

**Comment by torkelo** [comment]
That has to be done in the data source / query. Possibly in a transform (Insert nulls). Not in the graph

**Comment by xhci** [comment]
I just wanted to call this out, but the proposed solution doesn't work well when collecting evented data. We don't have any kind of recurring collection job - it's all done in realtime using AWS Timestream.

It would be great to have a solution for line graphs to "produce gap if no data seen for sensor within n minutes."

**Comment by matthieu-labas** [comment]
> That has to be done in the data source / query. Possibly in a transform (Insert nulls). Not in the graph

A transform sounds nice. Would you know if there are any transform available for that? I didn't find anything that looked like it (v9.2.5).
