### ISSUE TITLE
Automatically scroll to top of multi-page table panels

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30043]
In a multi-page table panel, sized so that there is overflow and a scroll bar, it would be nice if the panel would automatically scroll to the top when clicking on a page number.

What I currently have to do while looking for something is:
- Scroll to the bottom while looking, click page number, scroll to the top, scroll to the bottom while looking, … on repeat

What I want to be able to do is:
- Scroll to the bottom while looking, click page number, scroll to the bottom while looking, … on repeat

 I hope this could be a toggle option for the panel, not something forced.
 

Additionally, could we have the ability to eliminate overflow/scrolling so that the number of table pages is determined by the size of the panel in addition to the number of rows?

**Comment by torkelo** [comment]
Think this must refer to the old table panel, the new table panel does not have pagination  (only scroll)

**Comment by nabelekt** [comment]
How does one find this "new table panel"? Is it in 7.3.6 or a future release?

**Comment by torkelo** [comment]
introduced in 7.0 , the old table is hidden / deprecated. You can switch a old panel to it by clicking on the table visualization in the picker. 

We are adding a migration button in 7.4 and v8 it will be automatic

**Comment by nabelekt** [comment]
Ok, I see the new table now. Is there any way, with this new table panel, to use thresholds like we could with the old table panel? In the old one I was able to color the entire table row based on a threshold value:
![image](https://user-images.githubusercontent.com/7028403/103799639-96821500-5008-11eb-9de9-472382cec743.png)

I don't see any way to do that with the new table panel. I hope that this functionality hasn't been lost...

**Comment by torkelo** [comment]
Yes you can have thresholds, checkout the cell display mode , as override rule you can customize each column. 

You cannot have thresholds that govern a full row as they are only set per field (column)
