### ISSUE TITLE
Set thresholds based on variable selection

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30045]
**What would you like to be added**:
The ability to select different groups of thresholds based on dashboard variable selection.

**Why is this needed**:
With dashboard variables, we have the ability to change data series displayed in panels such as the graph panel. Certain threshold values may apply to one/some series, but be not at all applicable for other series. So, the threshold values should be able to change with the data selection.

**Comment by torkelo** [comment]
Duplicate (there is an old issue for this) use variables in graph thresholds

**Comment by nabelekt** [comment]
Maybe this is the older issue: #922 ?

**Comment by BorisTrnka** [comment]
> 
> 
> Duplicate (there is an old issue for this) use variables in graph thresholds

hi torkelo, a bit disappointing ... would be fine to note also duplicate to which issue - like nabelekt did ...
BTW: it's a duplicate to an issue opened in 2014 (!!!) with quite a lot of +1s ... isn't it a time to work on it already?
