### ISSUE TITLE
Grey border at the bottom of embedded graphs with light theme

### ISSUE THREAD

**Issue by mattiash** [grafana/grafana#3004]
If you use an iframe to embed a grafana graph with a light theme into a webpage, there is an ugly grey border at the bottom of the iframe. If you use the dark theme, the border is still there, but it is black which makes it less conspicuous.

See an example at:

http://codepen.io/anon/pen/PPQZrq

**Comment by mattiash** [comment]
I used the Chrome Developer tools to look at the problem. It seems to be some javascript code that sets the min-height of a div with class panel-container. If I increase that min-height by 8 pixels, the border disappears.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
