### ISSUE TITLE
Series to rows transformation does nothing

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30042]
I am not able to get the `Series to rows` transformation in a simple `Table` panel to do anything for me. `Transformation input data` and `Transformation output data` look identical.

&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/7028403/103577439-12a61c80-4e92-11eb-94d7-36afc4f52a63.png)

&nbsp;&nbsp;&nbsp;&nbsp;![image](https://user-images.githubusercontent.com/7028403/103577445-15a10d00-4e92-11eb-9780-65dcdee9c955.png)

**Environment**:
- Grafana version: _7.3.6_
- Data source type & version: _PostgreSQL 12_
- OS Grafana is installed on: _Windows 10_
- User OS & Browser: _Windows 10, Chrome_
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This transform is for time series, will merge many time series together into in Table with a time , metric name and value column

**Comment by nabelekt** [comment]
I suppose I can do what I want with a Stat panel for now, though the issue hopefully resolved under #23305/#29476 makes a table much more desirable.
