### ISSUE TITLE
Ability to specify plot width and x-position in graph panels

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30044]
**What would you like to be added**:
The ability to force plot width and x position in graph panels.

**Why is this needed**:
When we have multiple graph panels showing different data across the same time period, it can be difficult to correlate across graphs when the plots are misaligned. The plot size and position is effected by the number of decimals in the y-axis, y-axis units, having one vs two y-axes, size of the legend, etc, so the actual plots are often misaligned.

The `shared crosshair` option does help to overcome this issue, but does not get us all the way there.

**Comment by leeoniya** [comment]
this will be possible in the new graph panel.

duplicate of https://github.com/grafana/grafana/issues/4469

**Comment by nabelekt** [comment]
Closing as duplicate of #4469
