### ISSUE TITLE
In graph panel legend, put series names and color indicators with statistics

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30050]
**What would you like to be added**:
In graph panels, in legends located below plots, it would be helpful to have the names of the series and line color indicators located to the right with the statistics, or the statistics located to the left with the series names and color indicators. 

I.e., I want to avoid the distance between the series names and min values seen here:
![image](https://user-images.githubusercontent.com/7028403/103592512-7f301400-4eb0-11eb-84a6-8871fdc4602c.png)

**Why is this needed**:
For better readability

**Comment by torkelo** [comment]
Disable the table layout option and you will get this

**Comment by nabelekt** [comment]
Can we not have both? The table layout is far more readable.
