### ISSUE TITLE
unstable output order

### ISSUE THREAD

**Issue by jelmd** [grafana/grafana#30051]
I've the following panel definition, which results in a matrix with 64 timeseries:
```
# grafana 7.3.6
  "panels": [
    {
      "datasource": null,
      "gridPos": {
        "h": 14,
        "w": 8,
        "x": 0,
        "y": 0
      },
      "id": 24,
      "interval": "2s",
      "options": {
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "showThresholdLabels": false,
        "showThresholdMarkers": true
      },
      "pluginVersion": "7.3.6",
      "targets": [
        {
          "expr": "sort_by_label(DCGM_FI_DEV_GPU_UTIL, \"gpu\")",
          "format": "time_series",
          "interval": "",
          "legendFormat": "{{gz}} {{gpu}}",
          "refId": "A"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "GPU Utilization",
      "type": "gauge"
    }
  ]
```

However, the generated `Gauge` panel is not useful at all, because the order of the charts gets changed on every update and users get the impressions, that they are looking on random data.

So the first thing is to make the output stable e.g. by sorting wrt. `Legend` label, and perhaps in a future version to add an option to allow sorting by any labels using the given order of label names.

**Comment by jelmd** [comment]
![gauge0](https://user-images.githubusercontent.com/4813414/103601134-4a03e000-4f09-11eb-9d5c-2ed61f85c18a.png)
![gauge1](https://user-images.githubusercontent.com/4813414/103601145-50925780-4f09-11eb-81c3-674d8245de10.png)

**Comment by torkelo** [comment]
What data source are you using? Maybe an issue with your "sort_by_label" query? The stat panels (gauge, bar gauge, stat panel) rely on the query (data source) to return consistently sorted data.

https://github.com/grafana/grafana/issues/17245
