### ISSUE TITLE
Sorry for this, we will investigate. The best short term solution is to use a refresh page browser plugin: https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=sv

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#30052]
Sorry for this, we will investigate. The best short term solution is to use a refresh page browser plugin: https://chrome.google.com/webstore/detail/easy-auto-refresh/aabcgdmkeabbnleenpncegpcngjpnjkc?hl=sv

@torkelo  When will this problem be solved?

**Comment by torkelo** [comment]
Can you link to the issue? Not sure this this title is very good.

Duplicate of the memory leak issue ?
