### ISSUE TITLE
Flux: Missing Data with more "complex" statements

### ISSUE THREAD

**Issue by schamock** [grafana/grafana#30060]
**What happened**:
When using Flux I'm getting only partial data when using statements like "derivative".
Timeselection is "last 7 days" (-> 29.12. 14:00 - 5.1. 14:00), but the graphs stops at about 29.12. 20:15.
What I found out after a bit more testing: The Graph always stops after 6:11:40 (measured from the beginning of the graph), no matter which time range I select.

When copying the code from the query explorer to the InfluxDB interface I'm getting the whole data for the 7 days -> statements seams to be ok, gut Grafana stops showing the data

**What you expected to happen**:
Having the complete data for the whole 7 days in this example

**How to reproduce it (as minimally and precisely as possible)**:
With a standard Telegraf setup (e.g. using [[inputs.diskio]]) use the following Flux-statement:

```
from(bucket: "telegraf")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "diskio")
  |> filter(fn: (r) => r["_field"] == "read_bytes")
  |> filter(fn: (r) => r["host"] == "some_host")
  |> filter(fn: (r) => r["name"] == "some_device")
  |> derivative(unit: 10s, nonNegative: false)
```

Diagramm type: Graph

**Anything else we need to know?**:
I'm willing to hand over more information or data if needed. Please tell me if something is missing.

**Environment**:
- Grafana version: 7.3.6 (ea06633c34)
- Data source type & version: InfluxDB2 2.0.3 (fe04d34)
- OS Grafana is installed on: raspbian (most current) and raspbian x64 for InfluxDB
- User OS & Browser: MacOS Safari and Chrome
- Grafana plugins: none
- Others:

**Comment by schamock** [comment]
I found a solution for my specific case: When inserting
`  |> aggregateWindow(every: v.windowPeriod, fn: max)
`
after the derivative statement then I have no more problem. So my assumption is, that there is some kind of limit regarding the result lines when using Flux in Grafana. The aggregateWindow reduces the lines and the problem is solved.
Is this some kind of intentional limitation? If so, there should be some kind of warning, if data is dropped because of to many results.

**Comment by papagian** [comment]
Can you share the query results from the query inspector?

**Comment by schamock** [comment]
Sure, please find the to files attached (with and without the aggregateWindow)

[without_aggregatewindow.txt](https://github.com/grafana/grafana/files/5775260/without_aggregatewindow.txt)
[with_aggregateWindow.txt](https://github.com/grafana/grafana/files/5775261/with_aggregateWindow.txt)

**Comment by cgfoed** [comment]
@schamock : please read my last post at this issue and see if it solves your problem:
https://github.com/ae3e/ae3e-plotly-panel/issues/11#issuecomment-756222919

**Comment by schamock** [comment]
@cgfoed that was a good tip! But I still think it would be convenient if there would be a warning if data due to this limitation is lost...

**Comment by cgfoed** [comment]
true that! Please like my feature request ^^
https://github.com/grafana/grafana/issues/30136

Would be great if you'd close this issue here. Thx!

**Comment by schamock** [comment]
Yeah makes sense. I'll close this one
