### ISSUE TITLE
Grafana Server Doesn't Redirect With Subpath When Logging In

### ISSUE THREAD

**Issue by BeauRussell** [grafana/grafana#30068]
I am currently using Grafana v5.0.3 (commit: 91162f3) and have it installed on an instance with Prometheus and NGINX proxying between the two. Everything is working as intended, there's only one weird instance of when I log into grafana, I'm redirected to `http://<AWS instance>/` instead of `http://<AWS instance>/grafana/`. It still logs in successfully, though, because when I navigate back to /grafana/ everything works fine, pages direct to eachother correctly and I can pull data easily. Anyone have any ideas why there would be a problem with JUST the login?

grafana.ini Server block:

    [server]
    # Protocol (http, https, socket)
    protocol = http
    
    # The ip address to bind to, empty will bind to all interfaces
    ;http_addr =
    
    # The http port  to use
    ;http_port = 3000
    
    # The public facing domain name used to access grafana from a browser
    domain = <AWS Instance URL>
    
    # Redirect to correct domain if host header does not match domain
    # Prevents DNS rebinding attacks
    ;enforce_domain = false
    
    # The full public facing url you use in browser, used for redirects and emails
    # If you use reverse proxy and sub path specify full url (with sub path)
    root_url = %(protocol)s://%(domain)s/grafana/
    serve_from_sub_path = true

This also seemed to only set in after I set up google authentication on the instance, but now it happens with any login, through google, or with a direct password.

**Comment by torkelo** [comment]
This should be fixed in later versions of Grafana, please try and upgrade

**Comment by carvendy** [comment]
@torkelo fixed in 7.5.0?

**Comment by torkelo** [comment]
yes
