### ISSUE TITLE
Progressive rendering in graphs

### ISSUE THREAD

**Issue by amvaidya** [grafana/grafana#30071]
**What would you like to be added**:
When we try to plot data points for a long duration on the grafana graph panel, the panel waits till all the data is available before it is rendered.
A useful feature may be "progressive rendering" where the latest data points are rendered first and as historical data points become available, those are rendered. The x and y axes should also adjust accordingly.

**Why is this needed**:
It is very useful to start analyzing the most recent data while the historical data is being retrieved and rendered. This is available in Splunk and we have found it very useful

**Comment by torkelo** [comment]
Grafana already supports this, but only some data sources take advantage of it. Which data source would you like this added to?

**Comment by amvaidya** [comment]
Thanks @torkelo. I am requesting this for the Prometheus datasource

**Comment by amvaidya** [comment]
@torkelo - Can you please comment if this is possible or if you need more information?

**Comment by torkelo** [comment]
The Prometheus query api does not support this (as far as I know)
