### ISSUE TITLE
Vertical Bar Gauge "Scale" seems incorrect

### ISSUE THREAD

**Issue by sumocomputers** [grafana/grafana#30084]
**What happened**:
When displaying a vertical bar gauge, the height of the bar graphs does not seem to follow a linear scale. A bar with a value of 20 is very very short, and a bar with a value of say 40 is very tall, as in many many times taller than the height of the bar with a value of 20.

See attached screenshot(s)

**What you expected to happen**:
As an example, if you have one bar with a value of 20, it should approximately be half the height of a bar with a value of 40, assuming 40 is the max.

**How to reproduce it (as minimally and precisely as possible)**:
Hopefully the screenshot(s) show how to reproduce

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: InfluxDB v1.7.10
- OS Grafana is installed on: macOS 10.15.7
- User OS & Browser: macOS 11.1, Safari
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/656453/103786381-3b90f380-4ff1-11eb-9041-ebfdb2acc97c.png)

![image](https://user-images.githubusercontent.com/656453/103786412-42b80180-4ff1-11eb-96a2-0ea9586a4387.png)

**Comment by torkelo** [comment]
This is because you have not set a min & max so Grafana will automatically calculate a min/max based on the  data. Set min to 0 if you want that

**Comment by leeoniya** [comment]
@torkelo i think this would be a sensible default for bars. i ran into this as well while working on the new bars panel. it's not always easy to notice this, but i can't think when a 0 baseline would not be majority expectation.
