### ISSUE TITLE
Add Sigv4/AMP login information to Prometheus docs

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#30083]
AWS Managed Prometheus users currently experience friction when trying to connect to their Prom workspaces from Grafana, since there are a few steps involved and the documentation is spread out. We can reduce the friction by adding specific configuration instructions to our docs, similar to those we have for the [Elasticsearch plugin](https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#amazon-elasticsearch-service).

**Acceptance criteria**
Given I have an active Amazon Managed Service for Prometheus workspace
And I have self-installed Grafana
When I visit the Prometheus documentation and follow the instructions
I can connect to AMP from Grafana using IAM keys.

**Comment by aocenas** [comment]
Seems to be done in https://github.com/grafana/grafana/pull/30232
