### ISSUE TITLE
"On Time Range Change" Should Include "Dashboard Load"

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30092]
**What happened**:

I've defined variables that are dependent on time. They don't get loaded on "dashboard load" when I select update "on time range change" and I had to hit the refresh button to activate the variable, and the panels dependent on the variable.

```
SELECT ...
FROM ...
WHERE "create_datetime" >= $__timeFrom()
```

**What you expected to happen**:

I always thought, "Dashboard Load" option as a subset of "On Time Range Change"
> On Time Range Change > Dashboard Load > Never

I think "On Time Range Change" should include "Dashboard Load". That's what I was expecting naturally or you may choose to add another option like "On Time Range Change and Dashboard Load".

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a variable that is dependent on dashboard time.
2. Set update option as: "on time range change".
3. Use the variable in a panel.
4. Your panel will not load on dashboard load.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: Postgres
- OS Grafana is installed on: Windows 10 64 Bit
- User OS & Browser: Chrome & Windows
- Grafana plugins: -

**Comment by torkelo** [comment]
Unable to replicate this, the logic for update is the same for both on load and on time range change

**Comment by mertbakir** [comment]
> Unable to replicate this, the logic for update is the same for both on load and on time range change

You are right, I tried with a simplified dashboard and I'm unable to replicate it too. 
I had roughly 10 variables (type: query), each one is dependent on another. And the panels are dependent on the last variable.

**Does grafana generates variables in order (does the second one waits for the first one?).**

I get this error on load, but not on refresh or time change.

```
Templating
Template variable service failed pq: syntax error at or near ")"
```

```
SELECT DISTINCT "id"
FROM table
WHERE 
    ...
    "client_id" = $client_id AND
    "shift_id" in (${shift_id:csv}) AND
    "name" in (${name:sqlstring}) AND
    $__timeFilter("create_datetime")
````

When I remove this row, the error is gone.

```
    "name" in (${name:sqlstring}) AND
```

query for the name variable:

```
SELECT DISTINCT name
FROM table 
WHERE 
    ...
    "client_id" = $client_id AND
    "shift_id" in (${shift_id:csv})
```

**Comment by mertbakir** [comment]
I'm going to close this since there is no such issue. My bad, I misinterpreted the case. I solved the issue by simplifying my queries. I'm guessing it was because of size limit of templating variables.
