### ISSUE TITLE
Template variable preview shows only the first 20 results and there is no option to see more results

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#30099]
**What happened**: Template variable preview shows only the first 20 results and there is no option to see more results whereas in dashboard view variable dropdown list it shows all the results. It will be difficult to validate while writing the query.

**What you expected to happen**: Show all the template variable results in query preview and also include show more option. 

**How to reproduce it (as minimally and precisely as possible)**: Create a template variable either a query or custom. Check the results you'll see only the first 20 in the result preview.

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/65600879/103860176-4d51c400-50e1-11eb-9ec7-787d6bb37b6c.png)

**Environment**: 
- Grafana version: 7.2 and above
- Data source type & version: Elastic
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windws 10, Chrome
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
I'm able to reproduce it in 7.3.6 on Windows 10 (there is no Show more link)

**Comment by hugohaggmark** [comment]
Thank you for taking the time to report this, but we fixed in this #29332 scheduled for release in Grafana 7.4.0.
