### ISSUE TITLE
Graph panel neglects to render a bar at the edge of the time range

### ISSUE THREAD

**Issue by tewe** [grafana/grafana#30103]
**What happened**:

The maximum value displayed in the legend is larger than the tallest bar in the chart.

I could track this down to the legend including data at the edge of the time range, for which no bar is rendered. As far as the hover tooltip is concerned, there is an invisible bar.

![CleanShot 2021-01-07 at 11 19 27@2x](https://user-images.githubusercontent.com/645412/103881809-3a3bf580-50db-11eb-9ee6-bf93e7d146c1.png)

**What you expected to happen**:

- All data in the range is visible
- The values in the legend match the graph

**How to reproduce it (as minimally and precisely as possible)**:

Fiddle with the time range.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.5 (11f305f88a)
- Data source type & version: Elasticsearch 6.7.2

**Comment by papagian** [comment]
Thank you for reporting this. Can you please share the response from the query inspector.

**Comment by tewe** [comment]
The data from the screenshot above is gone, but here is the response for a case where the _minimum_ is affected because a very small bar is missing.

![CleanShot 2021-01-12 at 11 23 42@2x](https://user-images.githubusercontent.com/645412/104302462-1c9ad180-54c9-11eb-9b07-70b1b4e9c993.png)

**Comment by papagian** [comment]
@torkelo does #30227 fixes this?

**Comment by torkelo** [comment]
It might

**Comment by hugohaggmark** [comment]
This is confirmed and replicated in https://play.grafana.org/d/MV7ijsPMz/graph-panel-missing-bar-test?orgId=1

**Comment by torkelo** [comment]
think this is due to the data point is outside the time range window

**Comment by tewe** [comment]
@torkelo yes, there is data outside the time range. The issue is that it is partially rendered in the graph, and included in the sum total, as originally reported. I changed the title to reflect that.
