### ISSUE TITLE
Mixed datasource with variable datasources doesn't work

### ISSUE THREAD

**Issue by frdve** [grafana/grafana#30100]
**What happened:**

I have a variable datasource '$cloud' for Azure Data Explorer to select the correct environment and want to enrich this with data from another datasource (JSON API).  
![afbeelding](https://user-images.githubusercontent.com/66672043/102975616-a4ac3d80-4500-11eb-93dc-4d5961d15f56.png)
The $cloud variable datasource is parsed correcly in the title of the query field, but for the execution, it gives an error that $cloud is not found.  Also, related to this issue, it is not updated when I change the variable field.
Everything works when i use the $cloud datasource directly without the mixed datasources option. 

**What you expected to happen:**

The datasource variable should be used by the query

**How to reproduce it (as minimally and precisely as possible):**

- Create a Azure Data Explorer datasource variable with at least 2 options
- Create a panel with the datasource set to -- MIXED --
- Add a query using the variable as the datasource
- Change the variable

**Anything else we need to know?:**

**Environment:**

- Grafana version: Grafana v7.3.6 (ea06633c34)
- Data source type & version: Azure Data Explorer Datasource
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: Azure Data Explorer Datasource
- Others:

_Originally posted by @frdve in https://github.com/grafana/grafana/issues/23799#issuecomment-750019819_

**Comment by torkelo** [comment]
Strange, unable to replicate with other data sources. Maybe only an issue with ADX ?

**Comment by torkelo** [comment]
@sunker or @mckn when you have time can do you a quick test of this issue? (create data source variable of type ADX), then switch to mixed data source and add a query that has the variable as data source (should be at the top in the data source picker). For me it works for other data sources but I do not have ADX setup locally

**Comment by frdve** [comment]
I can reproduce it all the time, so maybe it's indeed something with ADX.  
Thanks for looking into it!

**Comment by joshhunt** [comment]
@frdve I was able to replicate this on v7.1.5 (9893b8c53d), but then upgraded to master and the problem was resolved, so it appears this has since been fixed.

Try with the 7.4 beta when it comes out shortly and report back if the issue still persists
