### ISSUE TITLE
Only associated annotations on a repeated panel

### ISSUE THREAD

**Issue by 00pur** [grafana/grafana#30107]
**What would you like to be added**:
I've also seen PR 18812 and PR 717, but I'm not sure if it fits all the needs if it is ready.
A solution is still needed for associated annotations on a repeated panel and I have a simple idea to make this work.
There is a good solution to query the MySQL database for annotations with multi-value variables, as described here:
https://grafana.com/docs/grafana/latest/datasources/mysql/#annotations
In the Template function it is possible to define repeated panels with one variable.
I think there is an easy way to filter out annotation records for a panel on the front-end if there is a field with the same name as the panel repeat variable in the result.
All records associated to the panel have the value in this field and match the panel variable value.
So, only the field name in the SQL query needs to be configured to have the associated panel repeat variable value for this great function.
This is the same way as an optional name for the end date/time field enable the new annotations feature since version v6.6+

Example with a template variable named **hostname**:
SELECT
UNIX_TIMESTAMP(event_time) AS time,
event_info AS text,
CONCAT(loaction, ',', rack) AS tags,
server_name AS **hostname**
FROM my_server_annotations
WHERE $__timeFilter(event_time) AND server_name  IN([[**hostname**]])
ORDER BY event_time ASC

Panels that do not have a repeat variable should get all annotations, because there the host in the metric can be used for grouping and there are targets for all hosts in that panel.

I also wrote a comment on PR 717 two days ago with the same idea.

**Why is this needed**:
We want to display only related annotations on a repeated panel, since the panels are per server are supposed to display information from that server and other information belongs to the other server on another panel.
If the annotations are displayed on each panel, it would be very confusing.

**Comment by torkelo** [comment]
will need panel level annotations: https://github.com/grafana/grafana/issues/717

**Comment by 00pur** [comment]
Can you give any idea on how the logic could be for the annotations query to use multi-value variable [[varname]] 
This result always end in an confusing output on repeated panels.

If there are panel level annotations, they will be much more expensive for the backend because there will be one ore more queries per panel. Put the result for all panels to the associated panel on the matching field and it is simple as possible.

It there a time plan for the panel level annotations?
The #717 is open since 2014 and #18812 stucks on merging since Nov 24, 2020
