### ISSUE TITLE
New Panel: Show discrete / state over time 

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30129]
**What would you like to be added**:

Official support for a panel similar to [Statusmap](https://grafana.com/grafana/plugins/flant-statusmap-panel)

**Why is this needed**:

Often, we have a time-series representing a state or mode of something. To represent these, I usually end up creating something like this:
<img width="1840" alt="Screen Shot 2021-01-07 at 10 13 38 PM" src="https://user-images.githubusercontent.com/7028403/103977087-b3683680-5135-11eb-99bd-ca80701dceea.png">
Obviously not ideal.

Unfortunately, [Statusmap](https://grafana.com/grafana/plugins/flant-statusmap-panel) seems pretty buggy in Grafana v7.3.6.

**Comment by leeoniya** [comment]
native support for this is on the roadmap. it will be a full rewrite of https://grafana.com/grafana/plugins/natel-discrete-panel atop the new graph component.

i think this type of chart is called a Timeline.

most likely won't land before 8.0.

**Comment by nabelekt** [comment]
Ah, https://grafana.com/grafana/plugins/natel-discrete-panel is actually what I was looking for when I found Statusmap.

Glad to hear that it will be made native, and hopefully more Grafana-esque. I'll see if I can get the plugin to work for me in the meantime.

And thanks for the terminology note.

Should this issue be closed then?

**Comment by leeoniya** [comment]
> and hopefully more Grafana-esque

yeah, that's a given :)

> And thanks for the terminology note.

i've also seen it called "swim lane", "job scheduling". "duty cycle" (or discrete) is a close cousin. gantt is similar, but more complex (typically with a tree and table). if you find anything more common, let me know!

> Should this issue be closed then?

leave it open, unless someone finds an existing dupe.

**Comment by leeoniya** [comment]
we now have Status history and State timeline panels native in v8-beta3.
