### ISSUE TITLE
Minor typo in tooltip for InfluxDB annotations editor "bellow"

### ISSUE THREAD

**Issue by LindsayHill** [grafana/grafana#3012]
Very minor typos in tool tip for Column Mappings in public/app/plugins/datasource/influxdb/partials/annotations.editor.html  and public/app/plugins/datasource/influxdb_08/partials/annotations.editor.html.

"...to specify the column names bellow." - should be "below"

**Comment by torkelo** [comment]
thanks, fixed!

**Comment by LindsayHill** [comment]
Thanks - super quick!
