### ISSUE TITLE
PanelChrome: Warning message or indication if max data points is reached

### ISSUE THREAD

**Issue by cgfoed** [grafana/grafana#30136]
**What would you like to be added**:
There should be a warning message or some kind of visual representation inside a graph that indicates if data from a query where dismissed by Grafana due to "max data points" setting
Could be a small ⚠️ with a hover hint as well.... (?)

**Why is this needed**:
To reduce confusion on why data series ends even is query is correct -> hence to reduce the number of people opening issues like "where is my data" ;)
The setting is not completely obvious to beginners.

**Comment by torkelo** [comment]
think this makes sense, should maybe also warn if max data points is higher than some reasonable limit (Some queries / data sources can disregard it )
