### ISSUE TITLE
Docs: Single Stat Panel typos/incomplete

### ISSUE THREAD

**Issue by LindsayHill** [grafana/grafana#3014]
In this file: grafana/docs/sources/reference/singlestat.md there are a couple of issues in this section:

    2. `Font Size`: You can use this section 
    3. `Values`: The Value fields let you set the function (min, max, average, current, total) that your entire query is reduced into a single value with. You can also set the font size of theand font-size (as a %) of the metric query that the Panel is configured with. This reduces the entire query into a single summary value that is displayed.
    4. `Postfixes`: The Postfix fields let you define a custom label and font-size (as a %) to appear *after* the value

The "Font Size" item is incomplete. In the 'Values' section, there is a problem here: "......set the font size of theand font-size..."

Suggestion: Consolidate the "font-size" references from 3 & 4 into 2?

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/pull/3020
