### ISSUE TITLE
Replace DI framework with Wire

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#30144]
**What happened**:
The Grafana dependency injection framework should be replaced with something more robust, to deal with issues like the following:

* Change in service ordering can cause segfaults
* The DI graph is only initialized for the first Grafana server instance - a problem when writing integration tests, since you want to create a fresh Grafana server instance for each test

We are switching to Google [Wire](https://github.com/google/wire), since it's compile time instead of run-time, which should make it a lot more robust.

## Notes

We could in the future also consider Cortex' strategy of manually wiring up services, and their [service model](https://github.com/cortexproject/cortex/blob/master/pkg/util/services/README.md) (ported from Guava).

According to @torkelo the important part isn't DI per se, but the service registry so that enterprise extensions can replace services/implementations.

## Division of work

To speed up work on this PR, we'll divide the migration of tests between each other:

- [x] pkg/services/ngalert => @aknuds1
- [x] pkg/tests/testinfra => @marefr 
- [ ] pkg/tests/api/alerting => @aknuds1

**Comment by torkelo** [comment]
Wire looks like it can handle the DI part, but we still need something like a service container (So enterprise can replace services/implementations). Not sure how that will work with Wire.

**Comment by aknuds1** [comment]
Thanks @torkelo for the reminder, need something that works with Enterprise of course.

**Comment by marefr** [comment]
Instead of reinventing the wheel might be a good idea to talk with Cortex maintainers about their module manager and whether that could be beneficial for us to use or not:
https://github.com/cortexproject/cortex/blob/813e1565b94c1ce8ee40925afbb5d2e5a68d0f8f/pkg/cortex/cortex.go#L313
https://github.com/cortexproject/cortex/blob/813e1565b94c1ce8ee40925afbb5d2e5a68d0f8f/pkg/cortex/modules.go#L802

**Comment by aknuds1** [comment]
I've migrated pretty much all the services, apart from their tests. Something still isn't working though, as I can't log into Grafana (just get redirected back to the login page).

**Comment by aknuds1** [comment]
Alright, it all works now AFAICT, apart from tests, they need porting over.
