### ISSUE TITLE
Which is the best way to show +40 series on same graph?

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3016]
Hi, I have a graph with a query that will return +50 dynamic series (series name can't be pre-established).
 
The series over exceed the size of graph on:
· The tooltip doesn't show all series value.ts imposible to compare with tooltip (not all series are shown) 
· It's impossible to compare the graph and legends (due to scroll).

IE, query returning 45:
![image](https://cloud.githubusercontent.com/assets/13196237/10689281/1d2ebe20-797a-11e5-80fe-a565057b6fd5.png)

Is there some way to split automatically a full query on different graphs like number of series or to see it better (remembering there is no possible way to pre-establish the series name)??
IE: query returns 50 series, shown on 3 graphs (20, 20, 10)

Thanks for all

**Comment by torkelo** [comment]
You can sort and filter whole series ,for ex top 20 series if you use graphite

**Comment by simPod** [comment]
@sbengo How did you create dynamic series?
