### ISSUE TITLE
OpenAPI/swagger specification for Grafana HTTP API

### ISSUE THREAD

**Issue by IndiscriminateCoding** [grafana/grafana#30164]
**What would you like to be added**:
OpenAPI/swagger specification for Grafana HTTP API

**Why is this needed**:
It would be quite useful to:
* Have HTTP API documented in standard way
* Being able to auto-generate HTTP client to access Grafana from such specification

**Comment by papagian** [comment]
Thank you for filing this. We have plans to standardise the API and we have considered some alternatives so far.

**Comment by madansu** [comment]
Hi !
Any updates on this ?

**Comment by sdboyer** [comment]
Fixed by #40528

**Comment by yosiasz** [comment]
is this doco still valid?
![image](https://github.com/grafana/grafana/assets/900951/29e5d868-effd-4143-a585-aa2be829d347)

I got to /swagger-ui on my self hosted OSS grafana v9.1.5 and I don't see anything

**Comment by malaclypse** [comment]
I second this, where can I access the spec on a self-hosted Grafana OSS 9.4.3 instance? Both endpoints don't work. I hope it's not available just for Enterprise or Cloud customers?

**Comment by papagian** [comment]
@yosiasz  is it possible you hit this #69757? this is fixed in `10.2.x` but maybe your instance is running an older version

**Comment by papagian** [comment]
> I second this, where can I access the spec on a self-hosted Grafana OSS 9.4.3 instance? Both endpoints don't work. I hope it's not available just for Enterprise or Cloud customers?

@malaclypse it was enabled by default in 9.5.0 by #63489
before that you have to [enable the feature toggle: `swaggerUi`](https://grafana.com/docs/grafana/v9.4/setup-grafana/configure-grafana/feature-toggles/#beta-feature-toggles)

**Comment by lawwu** [comment]
Link to the OpenAPI spec: https://github.com/grafana/grafana/blob/main/public/api-merged.json
