### ISSUE TITLE
Dashboard links - dashboards title are not fully readable

### ISSUE THREAD

**Issue by HakamSaffour** [grafana/grafana#30190]
**What happened**:
updated Grafana from V7.0.1 to V7.3.6

**What you expected to happen**:
Previous dashboards created on V7.0.1 to be working without any problem on V7.3.6

**How to reproduce it (as minimally and precisely as possible)**:
I updated my Grafana from V7.0.1 to V7.3.6, and I observed that the dashborad names … ‘Dashboard links - dashboards’ … are not fully displayed as shown below:

![image](https://user-images.githubusercontent.com/11553465/104188433-852a7580-5419-11eb-9597-9d3f7862cb3c.png)

I deleted the link and created it again as shown below:

![image](https://user-images.githubusercontent.com/11553465/104188467-8f4c7400-5419-11eb-93b1-8dd94d15056a.png)

But this did not help to solve the problem, any advise?

**Anything else we need to know?**:
How to fix it?

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: MS SQL
- OS Grafana is installed on: Windows
- User OS & Browser: Windows / Firefox
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Seems to work as expected for me using Grafana v7.3.6 and 

Chrome Version 87.0.4280.141:
![Screenshot from 2021-01-11 15-28-34](https://user-images.githubusercontent.com/1668778/104194643-dd657580-5421-11eb-86b1-54df42cc6841.png)

Firefox 84.0.2:
![Screenshot from 2021-01-11 15-32-31](https://user-images.githubusercontent.com/1668778/104195094-77c5b900-5422-11eb-88e1-d531af1e66fd.png)

What browser version are you using and what screen resolution? Any other you can provide to help us reproduce this?

**Comment by ssko1** [comment]
I'm encountering the same issue and can provide more details:

Resolution: 3440 x 1440
Chrome: Version 87.0.4280.88
Safari: Version 14.0.2 (15610.3.7.1.10, 15610)

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Fargate
- Grafana plugins: Many


The odd thing is that it renders fine for a split second, but re-renders to show half of the menu off-screen.

https://user-images.githubusercontent.com/3389517/104244711-dcc7e180-5417-11eb-8fa2-a070c2e67f1a.mov

**Comment by HakamSaffour** [comment]
Resolution: 2048 x 1080 (second monitor (1600 x 900)
Chrome: Version 87.0.4280.141 (Official Build) (64-bit)
FireFox: Version 84.0.1 (64-bit)

Environment:

    Grafana version: 7.3.6
    Data source type & version: MS SQL
    OS Grafana is installed on: Windows Server 2016 (using Grafana Standalone Windows Binaries(64 Bit))
    Grafana plugins: Many

Same observation as @ssko1 :
it renders fine for a split second, but re-renders to show half of the menu off-screen.

**Comment by marefr** [comment]
Thanks. Someone of our frontend devs will have a closer look at this.

**Comment by hugohaggmark** [comment]
@ssko1 @HakamSaffour I'm trying to repro this but without any luck.  I could use some more info or more clues on what might be the culprit in this case:
- Can you check your browser console if there's anything logged there
- Can you reproduce this behavior on any new dashboards? If not can you share the dashboard.json of the dashboard with the issue without any sensitive data? 

Click the share Dashboard icon 
![image](https://user-images.githubusercontent.com/562238/104322714-8f19aa80-54e5-11eb-9878-bd2be9a3ecce.png)

Click the Export tab, click export for sharing externally and the View JSON
![image](https://user-images.githubusercontent.com/562238/104322324-1fa3bb00-54e5-11eb-8086-d364c9320456.png)

Finally Copy to Clipboard
![image](https://user-images.githubusercontent.com/562238/104322460-4bbf3c00-54e5-11eb-877a-9f8a5cf8c3ca.png)

Thank you

**Comment by HakamSaffour** [comment]
I created a new dashboard, and the problem is solved (at least on the new dashboard)

![image](https://user-images.githubusercontent.com/11553465/104339289-b9746380-54f7-11eb-8bab-a3b801f39dc1.png)

![image](https://user-images.githubusercontent.com/11553465/104339442-e0cb3080-54f7-11eb-9ba7-c5eaebbd4b4b.png)

Here is the json file of a dashboard with off-screen menu


[Dashboard with Links.zip](https://github.com/grafana/grafana/files/5803296/Dashboard.with.Links.zip)

**Comment by hugohaggmark** [comment]
Thank you @HakamSaffour I can now confirm that this is a bug in Grafana v7.4.0-pre (94783cfe99). 

It seems to depend on the length of the name of the drop down. If you add an `s` to the name of the new dashboard @HakamSaffour to be `More Dashboards` as in the original dashboard, you should see the same issue again, right?

We've recently added some fixes to this placement because of other issues, so it looks like it's still not perfect.

**Comment by HakamSaffour** [comment]
Hello @hugohaggmark 
Yes, it depends on the length of name of drop down menu

![image](https://user-images.githubusercontent.com/11553465/104425190-a78ad300-5580-11eb-842e-178b76b68051.png)
