### ISSUE TITLE
'Datapoints outside time range' with non negative derivate

### ISSUE THREAD

**Issue by jordmoz** [grafana/grafana#3021]
Grafana 2.1.3. InfluxDB 0.9.4.1.

Query: SELECT non_negative_derivative(mean(value)) FROM "disk_read" WHERE "host" =~ /$env$/ AND type = 'disk_time' AND $timeFilter GROUP BY time($interval), "host"  ORDER BY time ASC

This metric comes from collectd's disk plugin.

Occasionally this will result in a datapoints outside time range error.  It only does it for derivative and non negative derivative functions.  I have run this with and without order by.  Again, it doesn't do it every refresh.  Maybe 1 out of 4.

**Comment by torkelo** [comment]
maybe a bug in InfluxDB, anyway I think that warning is removed in master

**Comment by scibi** [comment]
I've got the same issue on Grafana 2.5.0 with influxdb 0.9.4.2. It seams to be random - for different hosts, different metrics and different time ranges (all data from collectd). There is no issue when I'm not using derivative.

**Comment by torkelo** [comment]
maybe a bug with influxdb or maybe just influxdb returns some timepoints slighly outside the request time range?

**Comment by scibi** [comment]
I guess this is InfluxDB bug: influxdb/influxdb#4237 It's already fixed in master so I hope new version will be released soon.
