### ISSUE TITLE
ElasticSearch datasource sends invalid JSON payload from browser client to server

### ISSUE THREAD

**Issue by NickGraham101** [grafana/grafana#30224]
**What happened**:
When configuring a panel with ElasticSearch as the datasource the JSON payload that is sent from the browser to the Grafana server is invalid.  As a result it's intercepted by our firewall and never reaches the server.  Browser tools show that request is being sent to https://our.hostname.com/grafana/api/datasources/proxy/59/_msearch, the request payload is:

```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"our-logstash*"}
{"size":0,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1609853809869,"lte":1610458609869,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"app_Name:redacted-app-name AND level:warn AND message:Couldn't deserialise StandardMetaData AND Environment : PROD"}}]}},"aggs":{"2":{"date_histogram":{"interval":"10m","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":1609853809869,"max":1610458609869},"format":"epoch_millis"},"aggs":{}}}}
```

Pasting this payload into https://jsonlint.com/ confirms it's invalid as there is no comma separating the 1st object from the 2nd.

**What you expected to happen**:
The browser sends a valid JSON payload.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a panel with an ElasticSearch datasource
2. Capture the request payload using the browser's DevTools
3. Paste the payload into JSONLint

To fully replicate the error you would need to route traffic through an Azure AppGateway.  The request will be blocked by mandatory rule 200002 `JSON parsing error: parse error: trailing garbage\\x0a` but I think that would be excessive for the purposes of investigating this issue.  The rule is a standard OWASP rule so other firewalls may also be affected

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: ElasticSearch, esVersion: 70
- OS Grafana is installed on: Alpine linux container (grafana/grafana:7.3.1 image running as Kubernetes pod on AKS, Kubernetes version 1.18.8)
- User OS & Browser: Windows 10, Edge
- Grafana plugins: vonage-status-panel, flant-statusmap-panel, simpod-json-datasource, grafana-piechart-panel
- Others: traffic is routed from the browser through an Azure AppGateway with standard firewall rules applied to a Grafana pod running on Azure Kubernetes

**Comment by nbowes24** [comment]
This is being caused by the line here: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.ts#L263

It's joining the two JSON objects with new line creating an invalid JSON object.

**Comment by marefr** [comment]
It's according to Elasticsearch multisearch api: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-multi-search.html#search-multi-search-api-desc. So works as intended

**Comment by NickGraham101** [comment]
@marefr the Elastic documentation you've linked to says that "Content-Type header should be set to application/x-ndjson".  The Content-Type header that's getting passed from the client to Grafana is application/json.  Whilst that may not cause issues for Grafana it isn't correct for the payload and because of that will potentially cause issues for anything that sits inbetween the client and Grafana, which in this case is our App Gateway.  Is it possible to change the Content-Type to application/x-ndjson?

**Comment by marefr** [comment]
We're still support Elasticsearch v2.x and unsure whether that content type is supported on those versions. It's [not mentioned](https://www.elastic.co/guide/en/elasticsearch/reference/2.4/search-multi-search.html#search-multi-search-api-desc) for that version, but [is mentioned](https://www.elastic.co/guide/en/elasticsearch/reference/5.6/search-multi-search.html#search-multi-search-api-desc) in the v5.x docs.

Changes needed in the following files to support this:
- https://github.com/grafana/grafana/blob/2ef1b8653ddae5e7414f2f3f2ded271469b31ecb/pkg/tsdb/elasticsearch/client/client.go#L186
- https://github.com/grafana/grafana/blob/2ef1b8653ddae5e7414f2f3f2ded271469b31ecb/public/app/plugins/datasource/elasticsearch/datasource.ts#L106

**Comment by chadlwilson** [comment]
Hi @Elfo404 is it possible to get this fix backported into `v7.5.x` for potential release in `7.5.4`? Would be great to get a fix for this without a major Grafana version upgrade.

**Comment by Elfo404** [comment]
Honestly, I'm a bit reluctant to have this included in a patch release as it might break for people using a proxy that's not configured to handle this content type, but I'm definitely not an expert there.

wdyt? cc. @marefr

**Comment by marefr** [comment]
I agree with @Elfo404. In addition, we probably need to highlight this as a breaking change in the changelogs if we haven't already.

**Comment by chadlwilson** [comment]
OK, thank you @Elfo404 and @marefr for the consideration - much appreciated. I understand.
