### ISSUE TITLE
Logs: Unify display of detected-fields/labels

### ISSUE THREAD

**Issue by Diggsey** [grafana/grafana#30221]
Current UI:
![image](https://user-images.githubusercontent.com/451321/104317161-7dc8a200-54d5-11eb-8aa6-b687a10877e9.png)

**What would you like to be added**:

Allow the same actions to be performed (filter-in, filter-out, show-this-field, ad-hoc statistic) for all fields regardless of whether they are labels or parsed fields. 

**Why is this needed**:

When viewing logs you don't care about the distinction. Currently there's no way to show the value of a label instead of the log message without altering the query, which is very limiting.

Filter-in/out could be more difficult for parsed fields, but an approximate solution using `|=` and `!=` would be fine as a starting point.

**Comment by Phara0h** [comment]
To compete with kibana this really needs to be the minimum.

**Comment by gabor** [comment]
notes for the implementation:

the list of fields in the "parsed fields" section (currently the section is called "detected fields") contains things from the following sources:
- things parsed out in javascript from the log-message
- dataframe-fields that are not the timestamp&logmessage&other_system_fields
    - in elasticsearch these are the fields of the returned log-items
        - they may contain links if the data-links feature was used in the datasource
    - in loki these are dataframe-fields created in javascript, based on the dervied-fields feature used in the datasource

**Comment by gabor** [comment]
additional implementation notes:

- adding the [eye] icon to `labels`: seems straightforward to implement
- adding the [+]/[-] buttons to `detected field`:
    - for javascript-parsed fields: will be complicated, but technically possible (might require API changes)
    - for from-dataframe fields:
        - elastic: seems straightforward to implement
        - loki: seems impossible (these fields were generated by javascript-regular-expresions, not clear how a loki-filter-expression could be constructed from it)

**Comment by stevendungan** [comment]
Design Doc: https://docs.google.com/document/d/1XvZ0KDBG_f7d1fdhGQI6ykMqsK631yvlbegSGbLe__4/edit?usp=sharing
