### ISSUE TITLE
Annotation disappearing on edit mode and when open option menu

### ISSUE THREAD

**Issue by xandr2** [grafana/grafana#30229]
**What happened**:
Annotation disappeared when I go to "edit" menu or when I open  "Show option" sidebar. After "refresh dashboard" it appears.

**What you expected to happen**:
As it works on an older version (for example 6.6.2), annotation always showed on a graph.

**How to reproduce it (as minimally and precisely as possible)**:
Just go to edit mode on graph with annotation.

**Anything else we need to know?**:
![annotation](https://user-images.githubusercontent.com/14262685/104337304-02c7b180-54fe-11eb-8118-556a9430863e.gif)
![invisible_annotations](https://user-images.githubusercontent.com/14262685/104337318-06f3cf00-54fe-11eb-9234-e1f273c526a7.gif)

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Confirmed on https://play.grafana.org/d/000000010/annotations?editPanel=1&orgId=1 for Grafana v7.3.6 (ea06633c34). Also, solving this issue might also solve this #18670.

**Comment by hugohaggmark** [comment]
Fixed by #32834 and released in Grafana 8.0.0-beta1
