### ISSUE TITLE
Clock speed and rotational acceleration units

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30236]
**What would you like to be added**:

I realize that we can add custom units as needed, but we'd like to see the following added to the list of unit options:

Clock Speed: kHz, MHz, GHz, THz, ... (Hz already exists under Rotational Speed)
Rotational Acceleration: deg/s^2, rad/s^2

**Why is this needed**:

Same as existing units

**Comment by nabelekt** [comment]
Related:
#617
#2968 (looks like micron and micrometer are also requested there)

**Comment by torkelo** [comment]
Just open a PR is you want new units: 

https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts
