### ISSUE TITLE
Auto-refresh setting in dashboard settings do not work as expected

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#30237]
Relates to https://github.com/grafana/grafana/blob/master/CHANGELOG.md#700-2020-05-18:
```
Dashboard: A global minimum dashboard refresh interval is now enforced and defaults to 5 seconds.
```

If I type `1s` or `3s` as options into the `Auto-refresh` field in a dashboard's settings options, they are automatically removed, as I think is intended. However, if I type `.5s` or `.7s` in, these are not removed.

Additionally, this settings seems to have no actual impact. If I have `5s,10s,30s,1m,5m,15m,30m,1h,2h,1d` in the `Auto-refresh` field, save and reload the dashboard, the time range dropdown gives relative time ranges as `Last 5 minutes`, `Last 15 minutes`, ...

Requesting that this field be entirely removed, or a fix made so that it works as expected. If kept, a note should be added explaining its functionality and what range of values are allowed.

Note that there is some desire to return previous behavior: https://community.grafana.com/t/auto-refresh-lower-than-5s/32384/11

Running Grafana 7.3.6, Windows 10, Chrome 87.0.4280.88.

**Comment by torkelo** [comment]
> However, if I type .5s or .7s in, these are not removed.

It looks like .5s is parses as 5s which is why it is not removed 

> Additionally, this settings seems to have no actual impact. If I have 5s,10s,30s,1m,5m,15m,30m,1h,2h,1d in the Auto-refresh field, save and reload the dashboard, the time range dropdown gives relative time ranges as Last 5 minutes, Last 15 minutes, ...

Why do you think the auto refresh options impact the relative time ranges? 

> Note that there is some desire to return previous behavior: https://community.grafana.com/t/auto-refresh-lower-than-5s/32384/11

But you can do that, just set a very low limit

**Comment by nabelekt** [comment]
> It looks like .5s is parses as 5s which is why it is not removed
Should that be addressed? If so, why close the ticket?

> But you can do that, just set a very low limit
I am not sure what you mean here. If not for the `.5s` bug already mentioned, how can one set a value lower than `5s`? Or are you saying that this should be done in the `grafana.ini` file?
