### ISSUE TITLE
Cannot add query in METRICS section.

### ISSUE THREAD

**Issue by rolandovillca** [grafana/grafana#3023]
I have installed Grafana 2.1.3 version, and i have created my first dashboard, and tried to add data,,, but when i click on ADD QUERY nothings happen,,, I cannot guess what is happening, and no clues or advice messages/alerts are displayed to end user (at least it shoud say, that dont exist a soruce db sqlite, tempdb, mysql,, or any configuration missing,,, or something like that)..

Only this unclear message exists and it doesnt change, hope you will give a hand.

This is just a test data source that generates random walk series. If this is your only data source open the left side menu and navigate to the data sources admin screen and add your data sources (you need to be logged in to do this). You can change data source using the button to the left of the Add query button.

**Comment by torkelo** [comment]
you need to add a data source

http://docs.grafana.org/datasources/overview/
![](http://docs.grafana.org/img/v2/add_Graphite.jpg)
