### ISSUE TITLE
Dashboard: After changing time range in panel edit & view, the modifed time range is not applied to rest of dashboard when going back

### ISSUE THREAD

**Issue by JayVee2** [grafana/grafana#30246]
Hi,

just wanted to comment behaviour described in topic. In Previous versions when a panel was in “View” mode and time range setting were changed, then those new time range settings were applied to all panels on dashboard. ow when resetting fomr View mode, this panel keeps newly applied time range, all other panels show previous time range.

See also: [https://community.grafana.com/t/v7-3-6-when-panel-in-view-then-modifed-time-range-settings-are-applied-for-current-panel-only-not-for-dashboard/41519](url)

Regards,
-jayvee.

**Comment by torkelo** [comment]
Yea, not sure what the best solution is here, as loading all panels could be very time consuming some dashboards with many panels with slow queries. So making be a manual option to trigger a dashboard wide refresh feels like a good idea. 

So maybe we should add a modal to ask user if they want to trigger a refresh and update all dashboards when leaving edit or view mode with an updated time range

**Comment by torkelo** [comment]
Related to https://github.com/grafana/grafana/issues/28966

**Comment by torkelo** [comment]
fixed in v8
