### ISSUE TITLE
export Raw Document (legacy) not working in grafana v7.3.5

### ISSUE THREAD

**Issue by tianyunS** [grafana/grafana#30244]
Hi,

**What happened**:
I am using "Raw Document (legacy)" metric in Table to get the raw document in JSON format from Elasticsearch.
![image](https://user-images.githubusercontent.com/11883822/104411173-47f6ec80-55ad-11eb-9426-4177daab852a.png)

when I select Inspect >> Data and click "Download CSV" button the data file is like
![image](https://user-images.githubusercontent.com/11883822/104411288-7248aa00-55ad-11eb-97f1-9b89cc452b80.png)

The data in the download excel file:
A
--
[object   Object]
[object   Object]
[object   Object]
[object   Object]
[object   Object]
[object   Object]

**What you expected to happen**:
I want to export the raw document  as the same as Grafana v5.4.3

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: Elastic Search 6.0+
- OS Grafana is installed on:  AWS EC2
- User OS & Browser: Windows 10
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Use the new Raw data metric for the new table

**Comment by tianyunS** [comment]
hi @torkelo,
I am not able to see the Object (Array in JSON) if I select the new Raw data metric.
![image](https://user-images.githubusercontent.com/11883822/104436887-7be40900-55d1-11eb-9ee5-e3195ad13cf2.png)

is there any option/workaround to see the complete raw document in JSON format?
