### ISSUE TITLE
Grafana can't connect with Oracle database

### ISSUE THREAD

**Issue by miguelgomezaguirre** [grafana/grafana#30260]
**What happened**:
We're trying to connect with an Oracle DB from Grafana and it keep spinning in the test but never returns a message with a successful connection. Then when we try to run a query in a dashboard it returns 504

![image](https://user-images.githubusercontent.com/21964052/104496175-65c94f00-55b7-11eb-9b1d-322e943e0f85.png)
![Capture](https://user-images.githubusercontent.com/21964052/104496779-30713100-55b8-11eb-893b-aefc3f39820d.PNG)

**What you expected to happen**:
A successful message that the DB is connected properly.

Do you have a clue about what is happening here? Or where we can find something?

Thank you.

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- User OS & Browser: Windows & Chrome
- Grafana plugins: Oracle DB plugin

**Comment by marefr** [comment]
Are you referring to using this plugin? https://grafana.com/grafana/plugins/grafana-oracle-datasource

**Comment by miguelgomezaguirre** [comment]
Hi @marefr , yeah, exactly that one.

**Comment by marefr** [comment]
Since this is an enterprise plugin we suggest using your support contract to get in contact with Grafana Labs for further help.
