### ISSUE TITLE
viewers_can_edit should allow drafting new dashboards (but not saving)

### ISSUE THREAD

**Issue by james-callahan** [grafana/grafana#30265]
**What would you like to be added**:
If the `viewers_can_edit` setting it on, viewers should be able to create new dashboards (but not save them).

**Why is this needed**:
For situations where dashboards are deployed/managed from version control systems, `viewers_can_edit` allows administrators to disallow users from saving or modifing dashboards, while still allowing them to draft changes to existing dashboards (which they can then export to json and submit as a pull request).
However the 'new dashboard' button doesn't exist for them, so to draft a new dashboard, they have to pick an existing dashboard, erase everything out of it, and then start on their new one.

**Comment by torkelo** [comment]
Agree with this, think this has gotten lost some time in the last year or so, it used to work. It looks like you cannot add panels anymore either, only edit

**Comment by hugohaggmark** [comment]
According to the docs https://grafana.com/docs/grafana/latest/permissions/organization_roles/#viewer-role this is by design. This shouldn't be a bug then, but a feature request instead, correct @torkelo?

**Comment by torkelo** [comment]
Maybe not a bug then but think with this option enabled it should be possible to create new dashboards and add panels (but not save anything)

**Comment by hugohaggmark** [comment]
Gotcha, thank you for confirming that

**Comment by james-callahan** [comment]
Additionally: would it be possible to `import` a dashboard without "saving" it?
e.g. to ephemerally check out a published dashboard before committing it to version control?
