### ISSUE TITLE
Grafana 7.3.6 (win Version) and Android 10 WebView

### ISSUE THREAD

**Issue by JBSullivan** [grafana/grafana#30261]
Hello all,
I have updated Grafana from 7.2.1 to 7.3.6. I have a website running Grafana Trends in an iframe (embedded = true).

This website is also loaded via an app on Android 10 (integrated in this app). Under Grafana 7.2.1, all Grafana iframe trends were displayed in the app.

Under Grafana 7.3.6, the Grafana login window always appears in the iframe. When I log in, the content of the iframe flashes briefly and the Grafana login screen is displayed again.

In the Grafana Settings, however, it is displayed that I am logged in under Grafana Android 10 WebView. However, trend diagrams are no longer displayed under Android :(

![image](https://user-images.githubusercontent.com/44617472/104506888-47c71300-55e6-11eb-820c-6c63cf5decc6.png)

![image](https://user-images.githubusercontent.com/44617472/104506684-033b7780-55e6-11eb-8f74-17e03da1739d.png)

**Comment by JBSullivan** [comment]
Addendum: The problem does not only occur in the Android app, but is exactly the same in the mobile Android version of Google Chrome.

It works under Android 5.5.1.

**Comment by marefr** [comment]
Maybe something related to the auth cookie, like same-site attribute issues? https://grafana.com/docs/grafana/latest/installation/upgrading/#important-changes-regarding-samesite-cookie-attribute 

Or are you using anonymous access?

**Comment by JBSullivan** [comment]
Today it did not work on Android 5.5.1 too.

Here are my settings

![image](https://user-images.githubusercontent.com/44617472/104616283-654db880-568a-11eb-9f14-96c4af84afaf.png)

**Comment by JBSullivan** [comment]
Since my first posting, Grafana all day log out on all devices using Google WebView. Sometimes you can login (no jumping iframes), sometimes not. But if you logged in, a few hoursy later you are logged out again.

Config is modifyd to this. The problem is well known on the web. Some people solved it to modify the config like this. In my case it did not work :( 

[users]
# disable user signup / registration
allow_sign_up = false

[auth.anonymous]
# enable anonymous access
enabled = false

**Comment by papagian** [comment]
@JBSullivan 
It seems that for some reason the website cannot read the grafana session cookie.
What is the value of the [cookie_samesite](https://grafana.com/docs/grafana/latest/administration/configuration/#cookie_samesite) configuration?
Also can you share your grafana logs?

**Comment by marefr** [comment]
Would suggest continuing this discussion on the [community site](https://community.grafana.com/) since it feels more like a configuration error. We have provided suggestions in regards to the cookie samesite attribute, but haven't received any response to that.
