### ISSUE TITLE
Profile page - sessions - revoke access button is unclear, in terms of what it does.

### ISSUE THREAD

**Issue by hemdrup** [grafana/grafana#30279]
I found this weird little button. I had to click it, to understand what the button is for.

- It's not clear what the button does. I suggest changing to the text button "revoke access" or with a tooltip explenation. 
- The button is not aligned to the right

**Environment**:
- Grafana version: v7.3.6 (ea06633c34)
- User OS & Browser: Firefox
- Others: Dark theme

<img width="469" alt="Screenshot 2021-01-14 at 14 08 58" src="https://user-images.githubusercontent.com/21049979/104595088-5f4bdd80-5672-11eb-8da3-ca9ad58d3f90.png">
<img width="722" alt="Screenshot 2021-01-14 at 14 08 52" src="https://user-images.githubusercontent.com/21049979/104595090-5fe47400-5672-11eb-8918-b0fd4289e111.png">
<img width="1603" alt="Screenshot 2021-01-14 at 14 08 30" src="https://user-images.githubusercontent.com/21049979/104595093-5fe47400-5672-11eb-8031-7ac7b2d9bc99.png">

**Comment by marefr** [comment]
Looking in master (unreleased) right now it looks like this so think it's already resolved:
![image](https://user-images.githubusercontent.com/1668778/104600447-4bf04080-5679-11eb-948f-7e0d1325840d.png)
