### ISSUE TITLE
Slim Docker image

### ISSUE THREAD

**Issue by skhalash** [grafana/grafana#30288]
**What would you like to be added**:

Having an Alpine-based slim Docker image with only the minimum set of dependencies.

**Why is this needed**:

We are using Grafana in our project. We also periodically scan the Docker images we are using for potential security vulnerabilities. While triaging a yet another CVE coming from the Grafana image we realized that the following block https://github.com/grafana/grafana/blob/master/packaging/docker/Dockerfile#L33 from the Dockerfile brings in a large number of dependencies (>12k apk packages comparing to just 20 when it's not executed). As far as I understand from [the following PR](https://github.com/grafana/grafana/pull/20214), those dependencies are only needed to support Oracle premium datasource backends.

I am not sure about how often Oracle backends are used as Grafana datasources, but it seems to be quite an exotic case. Even if it's not, IMHO it would make sense to have a slim image with required dependencies only (for most common datasource backends) in order to reduce the attack surface. What do you think?

**Comment by aknuds1** [comment]
It's an interesting proposition, we'll try to discuss it when time allows.
