### ISSUE TITLE
Influxdb Query Editor: allow multiple measurements (columns) in FROM

### ISSUE THREAD

**Issue by azrdev** [grafana/grafana#3028]
InfluxQL allows multiple measurements in a from_clause, separated by commas. If I insert a query like `SELECT mean(value) FROM swap_in,swap_out WHERE $timeFilter GROUP BY time($interval)` into the manual query input, it shows both measurements. However, the graphical editor does not recognize that anymore, let alone allow me to edit it (interactively select one or multiple series).

**Comment by torkelo** [comment]
this is implemented in master and in 2.5 pre release builds, 
![Uploading image.png…]()
