### ISSUE TITLE
Filter data sources in explore to only show ones I can query

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#30299]
![image](https://user-images.githubusercontent.com/444037/104716260-97f5c080-571f-11eb-9c31-de1545e98343.png)

When I select the ruler, ruler-logs or alertmanager datasources, I get an empty query editor.  We should just not show them.

![image](https://user-images.githubusercontent.com/444037/104716329-b8257f80-571f-11eb-8a4f-30756fb136d6.png)

**Comment by cunyat** [comment]
Hi, would like to help here, I'm going to investigate a little and make a proposal : )

**Comment by torkelo** [comment]
@cunyat think I have an ok solution, https://github.com/grafana/grafana/pull/31144

**Comment by cunyat** [comment]
Oh, I was just learning how datasource works! :sweat_smile: 
Hope I can help with any other issue soon : )

**Comment by torkelo** [comment]
@cunyat sorry for taking over this one (not something I usually do), just been very very involved in redoing the data source picker, and DataSourceSrv.List , and this was a tricky one to fix without breaking other things

**Comment by cunyat** [comment]
Don't worry, i got a great example : )
