### ISSUE TITLE
Panels don't load if scrolling down too fast

### ISSUE THREAD

**Issue by timyllym** [grafana/grafana#30300]
How to reproduce:
1. Open e.g. https://play.grafana.org/d/avzwehmz/demo-wind-farm?orgId=1
2. Click browser reload button
3. Scroll down right away while the page is still loading
4. Scroll back up
5. Some panels have not been loaded and they remain unloaded

Expected:
Panels are loaded when I scroll back up

Tested on:
MacOS Mojave 10.14.6
Chrome 87.0.4280.141
Grafana 7.3.7

![recorded](https://user-images.githubusercontent.com/13029109/104716610-d5af1500-5730-11eb-8665-26a7208bdc3a.gif)

**Comment by hugohaggmark** [comment]
@timyllym great catch, and I can confirm this is an issue! Not sure this will be a top priority on our backlog though, as it seems like a real edge case. We'll see what we can do.

**Comment by wapophis** [comment]
Still happens on mobile views when panels are grouped in rows and there IS more than one row

**Comment by hugohaggmark** [comment]
> Still happens on mobile views when panels are grouped in rows and there IS more than one row

Hi @wapophis care to open a new issue with reproducible steps and dashboard json because this issue is closed. Thank you 🙏

**Comment by wapophis** [comment]
> > Still happens on mobile views when panels are grouped in rows and there IS more than one row
> 
> Hi @wapophis care to open a new issue with reproducible steps and dashboard json because this issue is closed. Thank you pray

Registered, i'll register the test case soon #42820
