### ISSUE TITLE
The program 'car' is currently not installed

### ISSUE THREAD

**Issue by JernejJerin** [grafana/grafana#3030]
Hi!

Just installed Grafana on Ubuntu 15.04 and then tried to run it as a init.d service. Now when running `sudo service grafana-server start` nothing gets displayed in terminal so I reckoned I will first check logs under `/var/log/grafana/grafana.log` if everything went ok. As it turned out, there was a issue. The log outputted the following:

```
The program 'car' is currently not installed. You can install it by typing:
sudo apt-get install ucommon-utils
```

After installing missing package and rerunning `grafana-server-start`, the log now outputs that the server has started successfully.

**Comment by utkarshcmu** [comment]
Hello @JernejJerin ,

I am able to install Grafana using the instrunctions in the docs:

[Grafana Docs](http://docs.grafana.org/installation/debian/)

`$ wget https://grafanarel.s3.amazonaws.com/builds/grafana_2.1.3_amd64.deb`
`$ sudo apt-get install -y adduser libfontconfig`
`$ sudo dpkg -i grafana_2.1.3_amd64.deb`

I agree that the message **Starting grafana-server** is not being shown when we run `$ sudo service grafana-server start` but the service starts for me and does not ask to install "car".

**Comment by torkelo** [comment]
systemd does not print anything when a service starts :(
