### ISSUE TITLE
Grafana v7.4 Release Plan

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#30313]
Release Coordinators: @ivanahuckova with support from @grafana/observability-squad

## 1.1. Publish What's new in Grafana draft article
**Who:** @grafana/docs-squad 
**When:** Wednesday Jan 20th 2021
**What:**

 - [x] Create Google doc and share with maintainers 
 - [x] Write draft article 
 - [x] Open a PR in grafana repository
 - [x] Examine staging site
 - [x] Publish to grafana.com
 - [x] Check with marketing on release date sync

## 1.2. Beta 1 Release
**Preconditions:**

-  [x] 1.1. Publish What's new in Grafana draft article

**Who:** @Elfo404 with support from @grafana/observability-squad 
**When:** Wednesday Jan 20th 2021
**What:**

 - [x] Checkout new release branch, v7.4.x, from head of origin/master
 - [x] Update versions to the next version to be released
 - [x] Update package.json to contain the new “what's new” and “release note” links.
 - [x] Commit everything and push release branch
 - [x] Checkout master branch
 - [x] Update version in package.json to point to the next pre-release, i.e. v7.5.0-pre /  v8.0.0-pre and commit
 - [x] Open a PR
 - [x] Checkout release branch, create and push beta release tag and wait for ~~CircleCI~~ Drone release build to finish
 - [x] Run automated verification tests
 - [x] Verify the front-end packages
 - [x] Update the changelog in master
 - [ ] ~Create community site release note topic~ we do not create topic on discourse anymore, release notes are published on the docs site
 - [x] Create a new release on GitHub
 - [x] Create and upload Hosted Grafana images
 - [x] Update latest.json
 - [x] Close the milestone

## 2. Docs

**Who:** @grafana/docs-squad 
**When:** Before stable release
**What:**

 - [x] Identify missing docs for changes and new features, create issues if needed
 - [x] Open a PR
 - [x] Publish to production (website repo)

## 3 Release blog post

**Who:** grafana/marketing
**When:** Before stable release
**What:**

 - [ ] ~Use final what's new article as template and create new release blog post~ not relevant as release blog came first this time around
 - [ ] ~Remember to change relative links from What's new article to absolute ones~ not relevant as release blog came first this time around
 - [x] Write final blog post article 
 - [x] Open a PR in website repo

## 4. Stable Release
**Preconditions:**

 - [x] Beta released and no critical bugs left to fix for the stable release

**Who:** @Elfo404 
**When:**  Thursday Feb 4th 2021
**What:**

 - [x] Cherry pick bug fixes into release branch (important for the stable release)
 - [x] Create and push stable release tag and do the actual release

**Comment by oddlittlebird** [comment]
Docs Squad does not write the blog post, Marketing does. @aligerrard
