### ISSUE TITLE
Docs feedback: /datasources/prometheus.md

### ISSUE THREAD

**Issue by rehevkor5** [grafana/grafana#30318]
The content of "Provision the Prometheus data source" does not document how to control the various parameters that are available for that data source, for example "scrape interval" which can be seen in the UI. The "provisioning docs page" https://grafana.com/docs/grafana/latest/administration/provisioning/#datasources does not explain this either.

**Comment by bohandley** [comment]
We will look into this as a low priority status to see if this is still an issue.
