### ISSUE TITLE
allow options to restrict the list of timezones

### ISSUE THREAD

**Issue by Gauravshah** [grafana/grafana#30325]
**What would you like to be added**:
Ability to restrict the list of timezones that show up on dashboard Time Range option

**Why is this needed**:
Adding timezone capabilities has been great addition, It helps look at dashboards with more clarity. But a company that exists in only few countries, it makes sense not to confuse the customers and show timezones of only those countries for which it makes sense. Otherwise it adds to confusion.

I think adding a restriction list in the `Preferences` Section would help or may be in the grafana.ini

**Comment by Gauravshah** [comment]
@aocenas we are planning to do the following:


- add a new setting https://github.com/grafana/grafana/blob/master/conf/sample.ini
- read the setting here https://github.com/grafana/grafana/blob/ba158e72dfdba35acf6e71051ae28281f32355cc/pkg/setting/date_formats.go
- Include the settings ex (https://github.com/grafana/grafana/blob/ba158e72dfdba35acf6e71051ae28281f32355cc/pkg/api/frontendsettings.go)
- use it here https://github.com/grafana/grafana/blob/v7.3.x/packages/grafana-data/src/datetime/timezones.ts

we are thinking to use `date_formats` section since that already has default_timezone.
looking to add:
```
visible_timezones: "America/Los Angeles","Asia/Kolkata"
```

Still thinking if  `UTC` & `browser` should be part of implicit allow or part of the list or separate config.

**Comment by aocenas** [comment]
@Gauravshah Great that you want to work on this. Let me first just loop some people who can help validate this, before you start coding.

@dprokop or @hugohaggmark can you take a look at this and say whether it makes sense to implement as proposed?

**Comment by Gauravshah** [comment]
thanks @aocenas will wait for validation

**Comment by Gauravshah** [comment]
@aocenas @dprokop @hugohaggmark any thoughts ?

**Comment by natellium** [comment]
Hey @Gauravshah, sorry for the late reply. Awesome that you want to work on this! Feel free to get started and we'll be happy to help reviewing :)

**Comment by Gauravshah** [comment]
@natellium does the design look good to you in terms of using settings and which sections should the settings belong to ?

**Comment by hugohaggmark** [comment]
@pkolyvas is this a feature request we should move to GitHub discussions?
