### ISSUE TITLE
the location of graph-tooltips is ambiguous sometimes

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#3032]
when there are many lines, the tooltip's location is ambiguous.

1) sometimes, it will show at top, only a few line-values can be shown. as below:

![selection_010](https://cloud.githubusercontent.com/assets/8777671/10720787/03037bea-7bd6-11e5-9dfe-fad868b29700.jpg)

2) sometimes, the tooltips will show at below, which is more better. as below:

![selection_011](https://cloud.githubusercontent.com/assets/8777671/10720791/0869017c-7bd6-11e5-8b59-4e3752f5b0b1.jpg)

**Comment by torkelo** [comment]
fixed (for the first image) in master and in 2.5
