### ISSUE TITLE
Customizing the name of the "All" custom variable

### ISSUE THREAD

**Issue by gianpietro1** [grafana/grafana#30335]
An excellent complement to [this PR](https://github.com/grafana/grafana/pull/27829) would be the possibility to rename the "All" custom variable that appears when switching on the "Include All" option:
![image](https://user-images.githubusercontent.com/10046142/104830526-f7ea8500-584d-11eb-8082-a74cea359c0b.png)

Since the filter for this option can be customized, sometimes "All" does not describe well what it provides. Anyway, my actual use case is more related to language, so another possibility would be to know where to translate this.
![image](https://user-images.githubusercontent.com/10046142/104830535-12bcf980-584e-11eb-8218-7c4b9d338360.png)

The final objective would be to be able to re-label the "All" custom variable, so it can be replaced by any configurable name.
![image](https://user-images.githubusercontent.com/10046142/104830611-50ba1d80-584e-11eb-88f8-b7ae9f924ef8.png)

**Comment by DmitrySidorow** [comment]
![Screenshot_1](https://user-images.githubusercontent.com/43705385/104848236-15265e80-58f5-11eb-8fb9-45b1b878f545.png)
you can change it in json model of dashboard. I don't know why this function is hidden

**Comment by gianpietro1** [comment]
@DmitrySidorow this is great, thanks a lot!!!

**Comment by jacksongoode** [comment]
This doesn't work now

**Comment by yusufgungor** [comment]
I can confirm that editing json is still not working
