### ISSUE TITLE
Add way to auto-resize the share iFrame for easier scripting

### ISSUE THREAD

**Issue by kokarn** [grafana/grafana#3034]
Hello! 
First of all, great app. Great support, good looks and a great community.

Secondly, I'm looking at building a internal control panel for a bunch of project's we're working on. 
In there I want to add either a single panel or a whole dashboard, no problem there. (Apart from hiding the topmenu, but that's not a big issue at the moment and it's getting worked on I think IIRC).

The only thing that's a bit annoying at the moment is the fact that you have to specify the height of the iframe so it looks good/avoids scroll. And if some admin edits the dashboard linked there will be some scrolling again.

I'd like the ability on the parent page to resize the iframe in some way depending on the content.

Most easy seems to be the [iframe-resizer](http://davidjbradshaw.github.io/iframe-resizer/) lib and then i can just work against that on the parent page hosting the iframe.

If that's a no go there are some other ways discussed [here](http://stackoverflow.com/a/5911870/1223319).

Thanks!

**Comment by torkelo** [comment]
Its just a normal iframe, so the parent page is free to use any lib to auto resize it :)

**Comment by kokarn** [comment]
Yes i know, but there is no way for the parent frame to know the height of the content and thus auto-resizing to the correct height. Something inside the iFrame needs to "publish" that.

**Comment by torkelo** [comment]
the height the iframe content is what ever you set the size of the iframe to, so it is totally up to the parent page

**Comment by kokarn** [comment]
Yes, i know. Sorry for being so bad with my explanation. 
Let me post some pictures to highlight the issue.

Say i have 2 pages, both contain dashboards. 

I set the height on the iframe to the perfect height for the first dashboard.
![First page](https://i.imgur.com/Yk8K6AJ.png)

Now, on the second page, the iFrame would be the wrong height.
![Second page](https://i.imgur.com/ZzUfcMr.png)

This could either be fixed by explicitly setting the height on every iFrame every time somebody updates the dashboard which seems very annoying if everything else can be scripted or by the iFrame providing what the height will be for the full length of the content.

Because it's so easy for the iFrame to provide that data it would be much appreciated :)
If you have any questions you can always take them in swedish on IRC ;)

**Comment by torkelo** [comment]
I thought you meant the embed feature on the panel (that is single panel embedding (http://docs.grafana.org/reference/sharing/#embed-panel) that iframe view always takes up the whole iframe widht and height. There is NO support for embedding a full dashboard

**Comment by kokarn** [comment]
Oh, really? I had no idea. 
Works great except for that part with the height anyways.
Thanks for the quick responses <3

**Comment by torkelo** [comment]
well of course you can iframe any web app, I was just saying that embedding panels is a supported feature.

**Comment by kokarn** [comment]
Yeah, i must've mixed up the panel embed with the dashboard share in my head :)

**Comment by benitogf** [comment]
Hello sorry about the necromancy, but this issue it's similar to mine, I have been using a lot the text panels to embed iframes, which is awesome, but haven't been able to handle the height changes on the panel resize propagating to the iframe too, maybe someone has found a way? alternatively adding a new "iframe" panel that gives this kind of feature by default would ease integrating different applications into grafana which is a very good thing imho, cheers and thanks for this wonderful project :1st_place_medal:
