### ISSUE TITLE
ColorPicker: Remove enableNamedColors property it does no seem to be used 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#30356]
Think this was mainly for legacy uses and does not look like it's wired up anymore so let's remove it .

Remove this prop:
https://github.com/grafana/grafana/blob/bedd662c0727fbfd02578f84852f5afdfeb4ba19/packages/grafana-ui/src/components/ColorPicker/ColorPickerPopover.tsx#L19

**Comment by thisisobate** [comment]
I tried searching for the `enableNamedColors property` throughout the entire codebase and I realized that this property is still in use.

These are some of them:
https://github.com/grafana/grafana/blob/bedd662c0727fbfd02578f84852f5afdfeb4ba19/packages/grafana-ui/src/components/ThresholdsEditorNew/ThresholdsEditor.tsx#L163
https://github.com/grafana/grafana/blob/bedd662c0727fbfd02578f84852f5afdfeb4ba19/packages/grafana-ui/src/components/VizLegend/VizLegendSeriesIcon.tsx#L15
https://github.com/grafana/grafana/blob/bedd662c0727fbfd02578f84852f5afdfeb4ba19/packages/grafana-ui/src/components/OptionsUI/color.tsx#L19

@torkelo Does it mean this property doesn't have any real effects on the components that use it?

**Comment by torkelo** [comment]
The property does work as intended
