### ISSUE TITLE
Moving Average issue

### ISSUE THREAD

**Issue by floppy84** [grafana/grafana#3036]
Hi,

I open this ticket because i got an issue or a misunderstanding on how to.

So i graph a value during time on first query.
On second query i graph the same data but with a timeshift of 7d 14d 21d 28d ::

![image](https://cloud.githubusercontent.com/assets/3499449/10730253/1fda0b9e-7bef-11e5-8eb6-8eaf0b08c1b3.png)

Until this week end all worked fine. but until the change of time (French Hour), i got a gap on my graphe like you see at the end of graphe ::

![image](https://cloud.githubusercontent.com/assets/3499449/10730166/a7ac006e-7bee-11e5-82be-901ded8e2134.png)

My question is, is there a way to mange this change of time.

Thanks
regards

**Comment by torkelo** [comment]
not sure, probably due to the change to winter time.

**Comment by torkelo** [comment]
Since this is a graphite issue I will close it, but I suspect this is working as it should but if you want to know more ask in `#graphite` channel on freende

**Comment by floppy84** [comment]
Ok i open the issue on graphite thanks
