### ISSUE TITLE
Migrate gauge with sparklines removes sparklines

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#30368]
**What happened**:
Migrating gauge panel removes spark lines.

**What you expected to happen**:
Keep same functionality as old gauge.

**How to reproduce it (as minimally and precisely as possible)**:
Old gauge with spark lines.
Migrate to new gauge.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.5 (11f305f88a)
- Data source type & version: Elasticsearch 7.0+
- OS Grafana is installed on: docker
- User OS & Browser: Win10 + Firefox
- Grafana plugins:
- Others:

**Comment by cdalexndr** [comment]
Note that `Stat` visualization has spark values as expected.

**Comment by torkelo** [comment]
Yes, if you need sparkline use the stat panel. 

Or you can create a community panel with both gauge + sparkline. The core gauge wont support this combo. You can also create two panels that share the same query result (using the -- Dashboard -- data source), one with gauge and one with a small graph
