### ISSUE TITLE
Prometheus link sometimes links back to Grafana home page

### ISSUE THREAD

**Issue by benhannel** [grafana/grafana#30366]
**What happened**:
Clicking the "Prometheus" link in the Edit Panel interface sometimes takes me back the grafana home page. Copying the link address confirms it is explicitly linking to the home page of our Grafana dashboards.
![image](https://user-images.githubusercontent.com/2576534/104949781-5c9fff80-5974-11eb-83ff-9216625ee0f6.png)

The problem is intermittent and reproduces nondeterministically. Sometimes refreshing fixes it, sometimes it does not.

**What you expected to happen**:
I expected it to take me to prometheus with the given query pre-populated.

**How to reproduce it (as minimally and precisely as possible)**:
I'm afraid I don't know the exact sequence of steps, because even with the same query on the same panel, sometimes it reproduces and sometimes it doesn't.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.2.0 (efe4941ee3)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (not sure exact distro)
- User OS & Browser: macOS 10.15.6. It has reproduced on both Chrome and Firefox.
- Grafana plugins: None
- Others:

**Comment by benhannel** [comment]
Potentially related: #29417

**Comment by benhannel** [comment]
A hard refresh (Shift+Refresh in chrome/firefox) usually resolves the issue.

**Comment by zoltanbedi** [comment]
I think this is fixed in https://github.com/grafana/grafana/pull/29543
Please let us know if it is not the case.
