### ISSUE TITLE
Grafana plugin doesn't read environment variables

### ISSUE THREAD

**Issue by lucassardois** [grafana/grafana#30382]
**What happened**:
I followed the [tutorial](https://grafana.com/tutorials/build-a-panel-plugin/#1) to setup a Grafana panel plugin project.
I passed my environment variables to my Dockerfile using `REACT_APP_API_URL=http://api.local` the same as for others containers.

**What you expected to happen**:
I excepted the Grafana plugin to be able to access the `process.env.REACT_APP_API_URL` variable. But it was empty.
In fact, `process.env` is empty.

**How to reproduce it (as minimally and precisely as possible)**:
1. Follow the panel plugin tutorial
2. Put everything in a container
3. Try to access an env variables from `SimplePanel` component such as `console.log(process.env)` in the render function.

**Environment**:
- Grafana version: 7.3.4
- OS Grafana is installed on: Linux/Docker
- User OS & Browser: Linux Mint & Chrome

**Comment by aocenas** [comment]
So front end code does not get env vars by default. `process.env` is basically synthetically created by `DefinePlugin`. I don't think we actually state anywhere that env vars should be available for frontend plugins. You also usually don't want to propagate them to frontend as they may contain secrets. @marcusolsson or @dprokop do we state anywhere that some env vars should be propagated to frontend or that plugin developers should use them?

**Comment by marcusolsson** [comment]
As @aocenas mentioned, if it would be possible, any plugin would be able to access information about your system which would have serious security implications.

I'm not aware of any docs that makes this clear. Maybe we should consider adding a Security page in the plugin documentation.

**Comment by aocenas** [comment]
In that case I am going to close this. @lucassardois if you want some specific variables to be propagated and used by the plugins in general please create a separate feature request issue for it.
