### ISSUE TITLE
Query: Redirect "not found" dashboard to Home?

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3038]
If a dashboard(for example "d56" in the following image) does not exist, we see the following screen:

<img width="1436" alt="screen shot 2015-10-26 at 7 07 56 am" src="https://cloud.githubusercontent.com/assets/1019609/10730992/60dd2bec-7bb0-11e5-9404-be073eb1d3b0.png">

Displaying error is orange on the right is perfect, but shouldn't we redirect the URL to the HOME Url?

Because anyway after seeing the page, user has to go to the list of existing dashboards and select a dashboard from it. So, we can save his 2 clicks and redirect him to the home dashboards, making the UI more friendly.

**Comment by torkelo** [comment]
the user can access that from the dashboard picker/search
