### ISSUE TITLE
How to aggregate metrics of a folder having other sub-folders?

### ISSUE THREAD

**Issue by vatsalmevada** [grafana/grafana#3039]
For example this is how I am storing my metrics: 

dir1.dir2.metric1,dir1.metric2,dir1.metric3 

Not if I want to aggregate all three metric1,metric2 and metric3 and find highest value then how can I do the same?

I tried following and I am it's failing:  
highestMax(dir1.*, 1) 

Is it even possible? If yes then any suggestions please.

**Comment by torkelo** [comment]
Not sure, its best to organize metrics you want to do wild card operations on in the same level. 

but you should be able to use the `group` function. 

query: A: `dir1.*`
query: B: `dir1.dir2.*`
query: C: `group(#A, #B)` -> highestMax(1)

![image](https://cloud.githubusercontent.com/assets/10999/10733940/2c9be098-7c01-11e5-8dfd-ddf12ec0d090.png)

You see how you can use the eye to hide a query (so query A and B is only used in query C and not issued by themselves)

**Comment by vatsalmevada** [comment]
Thanks that was helpful. However in my case dir2 is under dir1 when I try aggregation on dir1.* it seems that the graph loading fails with following response: 
  
![capture](https://cloud.githubusercontent.com/assets/3255813/10751427/3a00aeee-7ca6-11e5-98a0-73214ecbc079.PNG)

**Comment by torkelo** [comment]
Ok, maybe graphite does not support wildcards when you have both leaf and sub nodes in same level.  since this is a graphite error I will have to redirect you to the graphite project support channels (#graphite irc node on freenode or the graphite-web project on github)

**Comment by vatsalmevada** [comment]
ok thanks ...
