### ISSUE TITLE
LogQL comments do not work in Grafana: `#` leads to `syntax error: unexpected IDENTIFIER`

### ISSUE THREAD

**Issue by AndiDog** [grafana/grafana#30391]
**What happened**:

Official example for [LogQL comments](https://github.com/grafana/loki/blob/master/docs/sources/logql/_index.md#comments):

```
{app="foo"} # anything that comes after will not be interpreted in your query
```

does not work in Grafana 7.3.0 using "Explore" mode and Loki as data source. It produces the error

```
parse error at line 1, col 13: syntax error: unexpected IDENTIFIER
```

**What you expected to happen**:

I can add comments freely inside LogQL queries.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.0 (bf8837f6f8)
- Data source type & version: Loki

**Comment by ivanahuckova** [comment]
Hello @AndiDog the comments support was implemented in Loki ~2 weeks ago in https://github.com/grafana/loki/pull/3126. I have tested this with loki instance that has this change and and it works as expected. Please make sure that your loki instance  is up to date and includes this change.
