### ISSUE TITLE
Feat Req: alert notification channel permission for Team

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#30406]
**What would you like to be added**:
Grafana can set permission for dashboard/folder/datasource for Team.
I want to set permission for alert notification channel.

**Why is this needed**:
Alert notification could cause data leak.
If teamA set teamB's notification channel accidentally.
It could cause data leak.
As Grafana admin, I want to set alert notification permission.

**Comment by mtanda** [comment]
I think it is valid behavior, if some team member can open a dashboard, they can get alert notification by their notification channel.

The implementation idea is
1. Grafana backend alert engine lookup teams which are allowed for the alert's dashboard
2. Grafana backend alert engine lookup teams which are allowed for the alert's notification channel
3. Check whether same team is existed in dashboard permission and notification channel permission

**Comment by aocenas** [comment]
Not sure who to ping so trying @sakjur @kylebrandt @marefr maybe? Seems like this could be interesting point for the new alerting.

**Comment by sakjur** [comment]
:+1: This seems like a crossing of new alerting and new access control, I think this leans more heavily to the access control project than the alerting project? 🙂

Scopewise, this could fall into Grafana Enterprise territory, since teams don't provide data-level separation in the open source distribution of Grafana, so the concern for introducing a data leak by using another team's notifier is heavily reduced.

**Comment by kylebrandt** [comment]
With alerting NG, I would like to consider redoing the structure of notifications something like:

![image](https://user-images.githubusercontent.com/1692624/105501066-be70aa00-5c91-11eb-993b-05c292049ab5.png)

But not sure if/when we can handle the scope of that with Alerting NG (current plan is to get more into notifications in March). They may stay more like they are now.

**Comment by yuri-tceretian** [comment]
This will be a part of efforts for implementing fine-grained access control to Grafana alerting

**Comment by yuri-tceretian** [comment]
Basically, this is related to https://github.com/grafana/alerting-squad/issues/274 becasue it is blocked due to the same problem (needs better API for notification policies)
