### ISSUE TITLE
Empty tags in Kairos DB query yields invalid JSON object in query

### ISSUE THREAD

**Issue by khalaan** [grafana/grafana#3040]
When setting up a vanilla query with no tag filtering with the latest Grafana (2.1.3) and latest Kairos DB (1.0.0) the tags attribute to the query is an array [] rather than an object {}. I am submitting a pull request with a $.extend() around the angular.copy just to ensure we are an object inside of tags.

**Comment by bergquist** [comment]
KariosDB datasource is moved to https://github.com/Kratos-ISE/grafana-kairosdb-datasource-plugin
