### ISSUE TITLE
Ie11 browser running error

### ISSUE THREAD

**Issue by jifeng122333** [grafana/grafana#30412]
**What happened**:  Ie11 browser running error

**What you expected to happen**:

If you're seeing this Grafana has failed to load its application files 

SCRIPT1002: 语法错误
vendors~app.ddf7518003180e1ca7bc.js (2,4982534)

1. This could be caused by your reverse proxy settings.

2. If you host grafana under subpath make sure your grafana.ini root_url setting includes subpath. If not using a reverse proxy make sure to set serve_from_sub_path to true.

3. If you have a local dev build make sure you build frontend using: yarn start, yarn start:hot, or yarnbuild

4. Sometimes restarting grafana-server can help

 

**Environment**:
- Grafana version: v7.3.7 (1e261642f4)

**Comment by torkelo** [comment]
IE11 is not supported
