### ISSUE TITLE
dashboard permission doesn't apply for snapshot

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#30415]
**What happened**:
I can open dashboard snapshot, the dashboard itself is not allowed to open for me.

**What you expected to happen**:
The Grafana should deny to open the dashboard snapshot.

**How to reproduce it (as minimally and precisely as possible)**:
- Create two Team, TeamA, TeamB
- Create two User, UserA, UserB
- Assign UserA to TeamA, UserB to TeamB
- Create a dashboard
- Set permission of the dashboard for TeamB
- UserB take a snapshot for the dashboard
- UserA open snapshot list page, and open dashboard snapshot

**Anything else we need to know?**:
I tested it in Grafana Cloud.

**Environment**:
- Grafana version: Grafana v7.3.7 (1e261642f4)
- Others: Grafana Cloud

**Comment by torkelo** [comment]
Unable to replicate this, I can only see my own snapshots. Unless my org role is Admin then I can see all. But if the user has an org role of Viewer or Editor they should only be able to see their own snapshots.

Are you seeing something else? What org roles do you users UserA, UserB have?

**Comment by mtanda** [comment]
Sorry, the actual reproduce step is using same User.
UserB is login from `Grafana.com`, the role is Admin, but the user doesn't join any Team.
UserA is login from SAML, the role is Editor, the user join TeamA.

I use Admin user (UserB) to create dashboard, set permission, take snapshot.
And, signout from Grafana, login by SAML, then check snapshot.
The identity of UserA and UserB are same, but the privilege is changed by login method.

I expect that, when user lost permission for dashboard, the user lost permission for snapshot too.

**Comment by mtanda** [comment]
Now, I understand something, snapshot list API take current user, and search own snapshot.
https://github.com/grafana/grafana/blob/v7.3.7/pkg/api/dashboard_snapshot.go#L284-L289

When opening snapshot, there is no Team permission check, anyone who know the snapshot url can open snapshot.
https://github.com/grafana/grafana/blob/v7.3.7/pkg/api/dashboard_snapshot.go#L139-L173

**Comment by mtanda** [comment]
@torkelo 

I make a PR to change behavior.
https://github.com/grafana/grafana/pull/30472

I think proposed behavior is consistent for delete API.
https://github.com/grafana/grafana/pull/10996

**Comment by torkelo** [comment]
snapshots are designed to be accessed by whoever has the link

**Comment by mtanda** [comment]
Okay, Current behavior is intended.
I close issue and PR.
