### ISSUE TITLE
permissions: add access permissions to a single data source

### ISSUE THREAD

**Issue by iAmSOScArEd** [grafana/grafana#30422]
**What would you like to be added**: 数据源（Datasource）增加访问权限

**Why is this needed**:
安全问题，因为有不希望其他人能够访问到的数据源，但是在新建Dashboard的时候可以选择所有的数据源。即使在不知道字段的情况下，也可以通过查询information_schema查询出所有的表和字段，所以希望增加数据源访问权限配置功能

**Comment by daniellee** [comment]
I used google translate and I think you are asking about data source permissions.

This is a feature in Grafana Enterprise: https://grafana.com/docs/grafana/latest/enterprise/datasource_permissions/

and is not a feature we will be adding to open source Grafana.

**Comment by daniellee** [comment]
Closing this feature request as fine grained database permissions is not something we will add to Grafana. Coarse-grained permissions are implemented in Grafana Enterprise and fine-grained permissions should be handled in your database (like with [MySQL grant](https://dev.mysql.com/doc/refman/8.0/en/grant.html)).
