### ISSUE TITLE
Beta Time series panel: point size hidden when set to "never"

### ISSUE THREAD

**Issue by howardjohn** [grafana/grafana#30454]
**What happened**:

I converted my panel to the new time series panel, and got massive points on hover:
![2021-20-01_09-32-47](https://user-images.githubusercontent.com/623453/105212749-b59d9e00-5b02-11eb-84e0-b9dbd059d0f1.png)

In the settings, there is no config for point size:
![2021-20-01_09-32-36](https://user-images.githubusercontent.com/623453/105212753-b6363480-5b02-11eb-9cb4-2287bd74cdab.png)

If I change the points to always appear, now the point size config shows up (and works):
![2021-20-01_09-32-39](https://user-images.githubusercontent.com/623453/105212751-b6363480-5b02-11eb-93aa-2b3a8550b06b.png)

Also, I am not sure if this is a bug or some issue on my end, but I converted my panel, which had "reasonable" point sizes:

<details>

```json
{
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "datasource": "Prometheus",
  "fill": 1,
  "gridPos": {
    "h": 7,
    "w": 6,
    "x": 18,
    "y": 7
  },
  "id": 4,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": false,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "null",
  "percentage": false,
  "pointradius": 5,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "expr": "go_goroutines{app=\"istiod\"}",
      "format": "time_series",
      "intervalFactor": 2,
      "legendFormat": "Number of Goroutines",
      "refId": "A",
      "step": 2
    }
  ],
  "thresholds": [],
  "timeFrom": null,
  "timeRegions": [],
  "timeShift": null,
  "title": "Goroutines",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "format": "short",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  },
  "options": {
    "alertThreshold": true
  },
  "fieldConfig": {
    "defaults": {
      "custom": {}
    },
    "overrides": []
  },
  "pluginVersion": "7.4.0-beta1",
  "fillGradient": 0,
  "hiddenSeries": false
}
```
</details>

I then switch this to the new panel type, and the point sizes were automatically set to a large size.

**What you expected to happen**:

The size of points on hover is easily configurable without having to go through (small) hoops like enabling point size temporarily.

**How to reproduce it (as minimally and precisely as possible)**:

Just make a time series panel, configure point size, and set to "never"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0-beta1

**Comment by ryantxu** [comment]
Thanks for reporting!  will take a look

**Comment by ryantxu** [comment]
I have reproduced... I guess we could/should clear the point size on migrations.  This is using the configured point size, but in flot that was not used on hover

![Peek 2021-01-20 10-48](https://user-images.githubusercontent.com/705951/105222266-22b73080-5b0f-11eb-8dd9-fc4af1f39c0f.gif)
