### ISSUE TITLE
Prometheus: Min step value requires unit if used in alert but not on querying.

### ISSUE THREAD

**Issue by bart2001** [grafana/grafana#30464]
**What happened**
- I want to create alert based on number on my critical docker swarm service containers.
- After clicking `Test rule` on Alert tab, error appeared. 
```json
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "4.520ms",
  "error": "tsdb.HandleRequest() error time: missing unit in duration \"100\"",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1611187489137,
        "queries": [
          {
            "refId": "A",
            "model": {
              "expr": "count by (container_label_com_docker_swarm_service_name) (container_tasks_state{clustername=\"kr-develop\", container_label_com_docker_swarm_service_name=~\".*service-api.*\", state=\"running\"})",
              "format": "time_series",
              "instant": false,
              "interval": "100",
              "legendFormat": "{{ container_label_com_docker_swarm_service_name }}",
              "refId": "A"
            },
            "datasource": {
              "id": 4,
              "name": "Prometheus"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1611187789137
      }
    }
  ]
}
```

**What you expected to happen**:
- Alert should be firing (Not firing at the moment)
- Test Rule should be passed

**How to reproduce it (as minimally and precisely as possible)**:
- query: `count by (container_label_com_docker_swarm_service_name) (container_tasks_state{clustername="kr-develop", container_label_com_docker_swarm_service_name=~".*service-api.*", state="running"})`
- Alert configuration
![image](https://user-images.githubusercontent.com/18025021/105256230-ae40c800-5bc8-11eb-8f27-680274ce7a9c.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.6 (as docker)
- Data source type & version: Prometheus 2.23.0 (as docker)
- OS Grafana is installed on: CentOS Linux release 7.4.1708
- User OS & Browser: macOS Catalina & Chrome 87.0.4280.141
- Grafana plugins: (not related to the issue) alexanderzobnin-zabbix-app,grafana-clock-panel,grafana-simple-json-datasource
- Others:

**Comment by aocenas** [comment]
Seems like the issue is with the min step value in the query:
![Screenshot from 2021-01-22 15-50-34](https://user-images.githubusercontent.com/1014802/105505749-9f8e0a00-5cc9-11eb-8356-ff6b78dc67b4.png)

It seems to need unit otherwise it errors out but only for alerts.

Here we require unit in the backend: https://github.com/grafana/grafana/blob/2069630cb32be1a3158bcfcc0d2a896018f3641a/pkg/tsdb/prometheus/prometheus.go#L170

But seems like on frontend we just assume seconds https://github.com/grafana/grafana/blob/185442115caf82b797816c47a9c1396426139f95/public/app/plugins/datasource/prometheus/datasource.ts#L319.

This should be unified.

**Comment by bart2001** [comment]
Is this bug? I changed `Min step` value to `1m` and alert `Test Rule` works!

**Comment by aocenas** [comment]
@bart2001 yeah I would say so, this should be unified in some way. Either require the unit in Min step when querying or default to seconds in alerting so it behaves the same.
