### ISSUE TITLE
Timepicker broken in snapshots

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#3046]
The new timepicker is broken in snapshots:
For example: 
![screenshot 2015-10-26 14 40 57](https://cloud.githubusercontent.com/assets/2886187/10738845/abbd0daa-7bef-11e5-952e-264b9e58cc63.png)
![screenshot 2015-10-26 14 40 50](https://cloud.githubusercontent.com/assets/2886187/10738846/abc32d5c-7bef-11e5-886c-25491a64e66f.png)

Previously, it looked like:
![screenshot 2015-10-26 14 42 11](https://cloud.githubusercontent.com/assets/2886187/10738860/c05f072c-7bef-11e5-9a52-1912299ac10a.png)

Ref: https://app.raintank.io/dashboard/snapshot/AEiNkio7vPufq0W3eUbxOdnxOBIe8z1p

**Comment by torkelo** [comment]
its fixed in master, 19 days ago
https://github.com/grafana/grafana/commit/f680c15283bab6e45d4909a9ef0620049cf8a938
