### ISSUE TITLE
Display dashboard metadata in settings panel

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3047]
It would be great if we can have the following information attached with each dashboard, if available:

1. Created by - Name/UserId/Email
2. Last saved by - Name/UserId/Email
3. Last saved - Timestamp/Browser Time.

If user is not logged in and has changed the dashboard, then we can show "anonymous" in last saved by field.

The need for this arose because we have more than 140 Dashboards and we have no idea now who initially created them and who saved them the last time and when.

We can have this information in the "Manage Dashboard" dropdown somewhere.

**Comment by addshore** [comment]
+1 this should be great!

**Comment by utkarshcmu** [comment]
How about this?

<img width="1370" alt="screen shot 2015-11-18 at 3 40 06 pm" src="https://cloud.githubusercontent.com/assets/1019609/11258045/cbf06324-8e0a-11e5-9f35-d54029836b89.png">

**Comment by addshore** [comment]
Looks good IMO

**Comment by utkarshcmu** [comment]
"Created By" field is left to close this issue now.

**Comment by utkarshcmu** [comment]
Closing and tracking the progress in #3841
