### ISSUE TITLE
Allow local min and max in dataframe

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#30475]
Follow up of https://github.com/grafana/grafana/pull/27276#issuecomment-697226108

**What would you like to be added**:

Allow to compute gauges locally in column so it can show comparison of rows based on column value.

**Why is this needed**:

Currently, the gauge takes values from the whole dataset. That means if they're columns `A` and `B`, the min and max value is calculated from all values from both columns.

Though, when you need the gauge to show relations between only values in column `A`, it is not possible as values from `B` are also included in.

I propose that we should distinguish current `min` and `max` from local `min` and `max` attributes. That said, current min and max should be renamed to `globalMin` and `globalMax` which can create space for local `min` and `max` attributes.

These are partial solutions of solving the problem though not prod ready I think.

https://github.com/grafana/grafana/pull/27276/files  
https://github.com/simPod/grafana/commit/4c0f51094a5c6632e3e65a8662d603c7904d6a60

**Comment by torkelo** [comment]
You can use this function to get the local min & max for a field https://github.com/grafana/grafana/blob/1d689888b0fc2de2dbed6e606eee19561a3ef006/packages/grafana-data/src/field/scale.ts#L68

**Comment by simPod** [comment]
I'll look into it for my use case, thanks!

But

Does it make sense to show gauge in a table based on min+max of all values?

Let's say I want to visualise column `A` using a gauge. Though I have also columns `B` `C` `D` which also contain values in different units. Eg. `D` is in `0-1 %`. So it kind of messes up with my gauge that is intended for column A.

I still believe global min and max are not proper/the only way to render gauge in tables.

**Comment by simPod** [comment]
@torkelo I still believe this was closed kind of early. Have you followed referenced issue?

**Comment by torkelo** [comment]
we have this for that: https://github.com/grafana/grafana/issues/26383

**Comment by simPod** [comment]
Thank you for the reference
