### ISSUE TITLE
7.4.0-beta1 Decimals displayed incorrectly

### ISSUE THREAD

**Issue by krzysion** [grafana/grafana#30479]
7.2.x, 7.3.x:

![2021-01-21 10_15_03-PostgreSQL Database - Grafana](https://user-images.githubusercontent.com/36912975/105329582-9883d080-5bd1-11eb-9776-c7c5f68a2e6f.png)

7.4.0-beta1:

![2021-01-21 10_12_46-PostgreSQL Database - Grafana](https://user-images.githubusercontent.com/36912975/105332376-d9c9af80-5bd4-11eb-84a6-e1e0ab331f0e.png)

![2021-01-21 07_59_51-Clipboard](https://user-images.githubusercontent.com/36912975/105332437-e9e18f00-5bd4-11eb-8f11-612c8597dab2.png)

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: Prometheus 2.23.0

**Comment by rovo89** [comment]
I noticed similar things: https://github.com/grafana/grafana/pull/30262#issuecomment-764597588

**Comment by ryantxu** [comment]
Thanks for reporting @krzysion -- this will get resolved before release.
