### ISSUE TITLE
Update list views to new convention (data sources, user list, api keys)

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#3048]
We want to iterate the existing list pages to better resemble the new styles built for alerting. This would allow for greater filtering and bulk actions. 

To keep this active on the grafana project, this is a stub for @nchristus to work from (though he'll be developing within /nchristus/grafana/

The current alert page on: https://github.com/nchristus/grafana
![5a0d85c6-7103-11e5-81e5-368287920ca4](https://cloud.githubusercontent.com/assets/2886187/10742623/7ba0fb12-7c04-11e5-840b-fe3ac6ff83fc.png)

The pages we'd like to adapt to the new convention:

/datasources
![screenshot 2015-10-26 17 13 24](https://cloud.githubusercontent.com/assets/2886187/10742703/e3ca8f00-7c04-11e5-90e3-4258396e7c2c.png)

/org/users
![screenshot 2015-10-26 17 12 40](https://cloud.githubusercontent.com/assets/2886187/10742727/f6594d82-7c04-11e5-8738-4de8b651a318.png)

and Pending Users (expanding/collapsing)
![screenshot 2015-10-26 17 12 31](https://cloud.githubusercontent.com/assets/2886187/10742735/05d1418e-7c05-11e5-8e5c-de799511b049.png)

/org/apikeys
![screenshot 2015-10-26 17 12 47](https://cloud.githubusercontent.com/assets/2886187/10742739/099a3398-7c05-11e5-9bec-4de116ebef60.png)

As you can see, the existing lists are quite simple, and we'll need to include filtering and other basic functionality. Let's discuss sometime tonight/tomorrow.

**Comment by mattttt** [comment]
Talked to @nchristus on the phone a bit ago. Starting on the datasources view, and treating it as a proper semantic table (rather than the list view used in alerting).

**Comment by nchristus** [comment]
Progress on cleaning up the data sources table. Any initial feedback, @mattttt?

![grafana_data-sources](https://cloud.githubusercontent.com/assets/136611/10780583/eb0d0dd4-7d0c-11e5-85cc-9c92f702b4bf.png)

**Comment by mattttt** [comment]
@nchristus Looking good so far. Once we get the select boxes and filtering in place, then we'll bounce it off @torkelo for early code review.

**Comment by nchristus** [comment]
Added filter controls and checkboxes.

*Data sources:*
![updated-list-views_data-sources](https://cloud.githubusercontent.com/assets/136611/10836942/e4f6b80c-7e81-11e5-9b07-bbb64919641a.png)

*API keys:*
![updated-list-views_api-keys](https://cloud.githubusercontent.com/assets/136611/10836945/eb869dcc-7e81-11e5-98db-0790e7fc8a69.png)

Branch: https://github.com/nchristus/grafana/tree/updated-list-views

@mattttt let me know your thoughts. I can start applying this to the other screens, but would love your feedback on this initial progress first.

**Comment by torkelo** [comment]
:+1:

**Comment by mattttt** [comment]
Yea, this is looking solid so far. @torkelo: Did you take a look at the code as well? If so, then please continue @nchristus!

**Comment by mattttt** [comment]
@nchristus We also need to talk responsiveness, so let me know if we want to do it now or after we roll it out to a couple other screens. Specifically because it ties into a forthcoming table panel, which we'd love to reuse as much code as we can here.

**Comment by torkelo** [comment]
did not find a branch for at nchristus/grafana

**Comment by torkelo** [comment]
ah now I found it sorry :)

**Comment by nchristus** [comment]
**Org Users**
![updated-list-views_org-users](https://cloud.githubusercontent.com/assets/136611/10910333/7bf5cd1c-8204-11e5-982e-ea5affe7d3c7.png)

@mattttt what are your thoughts on the 'pending invites' panel?

**Comment by mattttt** [comment]
Chatted with @nchristus today. Action items to submit a PR this week:

1. Set 1000px for all tables for consistency. 
2. For pending invites, add column headers and decide whether it's a table or a list (like alert panel)
3. Convert Org list to table view on Profile page. 
4. Check boxes need (get angularized)
5. Add check boxes to users
6. Grafana Admin Users and Orgs pages.

**Comment by mattttt** [comment]
For Alerting and Pending Invite pages w/ accordion:
![grafana_-_home](https://cloud.githubusercontent.com/assets/2886187/11247855/e6f25462-8deb-11e5-90a3-397415882b53.png)

**Comment by nchristus** [comment]
Action items 1–6 addressed, updates pushed to 'updated-list-views' branch, screenshots below.

![updated-list-views_data-sources](https://cloud.githubusercontent.com/assets/136611/11290977/1c7fc446-8f01-11e5-9eb6-8053807d8adb.png)
![updated-list-views_api-keys](https://cloud.githubusercontent.com/assets/136611/11290980/1c8e12b2-8f01-11e5-96b3-607cd0c2cd46.png)
![updated-list-views_global-orgs](https://cloud.githubusercontent.com/assets/136611/11290981/1c8eaca4-8f01-11e5-8338-7077567568c4.png)
![updated-list-views_global-users](https://cloud.githubusercontent.com/assets/136611/11290983/1c8ffab4-8f01-11e5-87a5-2821379508b0.png)
![updated-list-views_org-users-pending](https://cloud.githubusercontent.com/assets/136611/11290978/1c8dcac8-8f01-11e5-913b-f932871f504a.png)
![updated-list-views_org-users](https://cloud.githubusercontent.com/assets/136611/11290979/1c8dca14-8f01-11e5-9e47-5dacc398c149.png)
![updated-list-views_profile](https://cloud.githubusercontent.com/assets/136611/11290982/1c8e8ad0-8f01-11e5-985f-ca66b423efda.png)

@mattt please review and we'll work on getting the PR submitted.
