### ISSUE TITLE
Can we have Page Title on Panel Edit/View Screen

### ISSUE THREAD

**Issue by shanky05** [grafana/grafana#3050]
Can we have Page Title on Panel Edit/View Screen. 

For instance i have around 13 rows in a single dashboard , with 3 panels each.

Now when i go for an edit/view of a panel we actually down know the title under which that panels falls.

**Comment by torkelo** [comment]
Page title? When you edit a panel you edit a panel, if you need to know which row the panel is in you need to specify that in the panel title :)
