### ISSUE TITLE
Grafana remote rendering issue with HA setup in Kubernetes

### ISSUE THREAD

**Issue by zameeransari** [grafana/grafana#30515]
What happened:
I'm running Grafana 7.3.6 and using remote rendering service which is always rendering Grafana dashboard:
![image](https://user-images.githubusercontent.com/5148363/105387170-45466800-5c3b-11eb-8998-07148aeb8497.png)

Environment:
- Grafana version: 7.3.6
- Backend: MySQL
- Data source type & version: MySQL 5.7
- OS Grafana is installed on: Azure Kubernetes Service version 1.15 with alpine base image
- Helm chart used: grafana/grafana:7.3.6
- Grafana plugins: remote rendering
- SSL enables: Yes
- Load Balancer: Azure private Load Balancer
- Reverse proxy:  Nginx
- Image renderer version: grafana/grafana-image-renderer:2.0.0

Remote rendering configuration in HELM chart values.yaml:
env:
   GF_RENDERING_SERVER_URL: http://grafanaimagerendererservice.grafana.svc.cluster.local:8081/render
   GF_RENDERING_CALLBACK_URL: http://grafana.grafana.svc.cluster.local
   

Server setting:
grafana.ini:
  server:
    domain: my-dev.mydns.com
    root_url: https://my-dev.mydns.com/monitoring
    serve_from_sub_path: true
###################################################################################################
Grafana remote rendering deployment YAML:
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafanaimagerenderer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafanaimagerenderer
  template:
    metadata:
      labels:
        app: grafanaimagerenderer
    spec:
      containers:
      - name: grafanaimagerenderer
        image: grafana/grafana-image-renderer:2.0.0
        ports:
        - containerPort: 8081
        env:
        - name: IGNORE_HTTPS_ERRORS
          value: "true"        
        - name: ENABLE_METRICS
          value: "true"                  
        - name: LOG_LEVEL
          value: "debug"                            
        - name: RENDERING_MODE
          value: "clustered"
        - name: RENDERING_CLUSTERING_MODE
          value: "context"
        - name: RENDERING_CLUSTERING_MAX_CONCURRENCY
          value: "5"
        - name: RENDERING_DUMPIO
          value: "true"          
        - name: RENDERING_ARGS
          value: "--no-sandbox,--disable-setuid-sandbox,--disable-dev-shm-usage,--disable-accelerated-2d-canvas,--disable-gpu,--window-size=1280x758"  
##################################################################################################################################################
Grafana remote rendering service deployment YAML:
apiVersion: v1
kind: Service
metadata:
  name: grafanaimagerendererservice
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: grafanaimagerenderer
####################################################################################################################################################	
Grafana remote image renderer logs:
{"mode":"context","maxConcurrency":5,"level":"info","message":"using clustered browser"}
{"config":{"chromeBin":"/usr/bin/chromium-browser","args":["--no-sandbox","--disable-setuid-sandbox","--disable-dev-shm-usage","--disable-accelerated-2d-canvas","--disable-gpu","--window-size=1280x758"],"ignoresHttpsErrors":true,"acceptLanguage":null,"width":1000,"height":500,"deviceScaleFactor":1,"maxWidth":3080,"maxHeight":3000,"maxDeviceScaleFactor":3,"mode":"clustered","clustering":{"mode":"context","maxConcurrency":5},"verboseLogging":false,"dumpio":true},"level":"debug","message":"Browser initialized"}
{"collectDefaultMetrics":true,"requestDurationBuckets":"1,5,7,9,11,13,15,20,30","level":"info","message":"Metrics enabled"}
{"level":"info","message":"HTTP Server started, listening at http://localhost:8081"}
[0121/164951.141048:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.

DevTools listening on ws://127.0.0.1:37113/devtools/browser/46031fdf-b32b-45ca-88be-b72815a56963
[0121/164951.153747:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 38: Permission denied (13)
[0121/164951.331000:WARNING:dns_config_service_posix.cc(341)] Failed to read DnsConfig.

DevTools listening on ws://127.0.0.1:43027/devtools/browser/ea8f08ca-1dba-40c0-ba37-89d14306a33b
[0121/164951.339334:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 65: Permission denied (13)
{"message":"::ffff:172.20.59.34 - - [21/Jan/2021:16:50:24 +0000] \"GET /metrics HTTP/1.1\" 200 - \"-\" \"Prometheus/2.16.0\"\n","level":"debug"}
{"message":"::ffff:172.20.59.34 - - [21/Jan/2021:16:51:24 +0000] \"GET /metrics HTTP/1.1\" 200 - \"-\" \"Prometheus/2.16.0\"\n","level":"debug"}
{"url":"http://grafana.grafana.svc.cluster.local/d-solo/L1-ZAlpGk/lorem-ipsum-oor-overview?orgId=1&from=1608655891670&to=1611247891670&var-site=lorem%20ipsum&var-equipment=EP00124125&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta&render=1","level":"debug","message":"Render request received"}
[0121/165133.251019:ERROR:zygote_host_impl_linux.cc(259)] Failed to adjust OOM score of renderer with pid 86: Permission denied (13)
{"file":"/tmp/34903d92.png","level":"debug","message":"Deleting temporary file"}
{"message":"::ffff:172.20.59.18 - - [21/Jan/2021:16:51:36 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=grafana.grafana.svc.cluster.local&encoding=&height=500&renderKey=rmxSbG1M2unAFWpYd57mA7MbKECZEOEO&timeout=60&timezone=Asia%2FCalcutta&url=http%3A%2F%2Fgrafana.grafana.svc.cluster.local%2Fd-solo%2FL1-ZAlpGk%2Florem-ipsum-oor-overview%3ForgId%3D1%26from%3D1608655891670%26to%3D1611247891670%26var-site%3Dlorem%2520ipsum%26var-equipment%3DEP00124125%26panelId%3D2%26width%3D1000%26height%3D500%26tz%3DAsia%252FCalcutta%26render%3D1&width=1000 HTTP/1.1\" 200 83158 \"-\" \"Grafana/7.3.6\"\n","level":"debug"}
{"url":"http://grafana.grafana.svc.cluster.local/d-solo/L1-ZAlpGk/lorem-ipsum-oor-overview?orgId=1&from=1608655891670&to=1611247891670&var-site=lorem%20ipsum&var-equipment=EP00124125&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta&render=1","level":"debug","message":"Connection closed"}
#####################################################################################################################################################
Grafana pod log:
t=2021-01-21T16:51:33+0000 lvl=info msg=Rendering logger=rendering renderer=http path="d-solo/L1-ZAlpGk/lorem-ipsum-lorem-ipsum?orgId=1&from=1608655891670&to=1611247891670&&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta"
t=2021-01-21T16:51:36+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/favicon.ico status=302 remote_addr=172.20.59.5 time_ms=0 size=40 referer="https://my-dns.mydns.com/monitoring/render/d-solo/L1-ZAlpGk/lorem-ipsum-oor-overview?orgId=1&from=1608655891670&to=1611247891670&var-site=lorem%20ipsum&var-equipment=EP00124125&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta"
t=2021-01-21T16:51:36+0000 lvl=info msg="Request Completed" logger=context userId=2 orgId=1 uname=zameer.ansari method=GET path=/login status=302 remote_addr=172.20.59.5 time_ms=16 size=46 referer="https://my-dns.mydns.com/monitoring/render/d-solo/L1-ZAlpGk/lorem-ipsum-oor-overview?orgId=1&from=1608655891670&to=1611247891670&var-site=lorem%20ipsum&var-equipment=EP00124125&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta"
###################################################################################################################################################

Also tried to disable serve_from_sub_path: false [mentioned here](https://github.com/grafana/grafana/issues/21925) but it got stuck in redirect loop. Is anyone stuck this kind of unexpected behavior with Grafana remote rendering service? please suggest what is wrong I'm doing here.

**Comment by aocenas** [comment]
Can you specify in a bit more detail what is happening and what do you expect to happen? It's not clear to me whether the screenshot of the dashboard is what you want to render or the issue is that it always render that particular dashboard when you wan't different one.

**Comment by mwmahlberg** [comment]
@zameeransari It would be nice if you could add how you solved this problem...
