### ISSUE TITLE
New-table panel does not show "no data to show" when there is no data. 

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#30545]
**What happened**:
The old table panel used to show the string "no data to show" when there was no data. 
The new table panel instead shows the column headings for the data, but does not show "no data to show" leaving some users confused if there is in fact any data or not. 
See screen shots. 
![image (3)](https://user-images.githubusercontent.com/8004654/105499029-cc85f100-5cb8-11eb-9978-7b6451e90bbe.png)

**What you expected to happen**:
The new-table panel to have a clear visual clue such as saying "no data to show" when there is no data.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7 
- Data source type & version: Azure logs analytics. 
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by torkelo** [comment]
Anyone who wants to pick and help with this issue here is the component: https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/Table.tsx#L114

**Comment by jackw** [comment]
@simonc6372 do you have any instructions that would help me reproduce this bug as so far I've not managed to reproduce it locally.

**Comment by VishalLahane** [comment]
@jackw https://github.com/grafana/grafana/issues/30904 I think same issue right (duplicated )?
