### ISSUE TITLE
Import/export dashboard with/without default values

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#30542]
When exporting/importing a dashboard, the dashboard JSON model could be big and contain a lot of default values. As a user, I would like to choose to export a dashboard without the default values and, if needed, apply default values if missing when importing a dashboard. This will help me to easier understand what a dashboard contains and ease comparing changes between dashboards and/or dashboard versions. 

Dashboard-schemas defined in [CUE](https://cuelang.org/) today: https://github.com/grafana/grafana/tree/master/dashboard-schemas

**Comment by marefr** [comment]
Duplicate of #13887
