### ISSUE TITLE
Oauth users not being assigned correct role with environment variable GF_USERS_AUTO_ASSIGN_ORG_ROLE

### ISSUE THREAD

**Issue by Burke9077** [grafana/grafana#30555]
**What happened**:

I'm deploying grafana through Docker 100% as code, no configuration after deploying so the grafana instance and all of its config can be deployed through a pipeline. I'm using environment variables to set all the config options, but one doesn't seem to be working. I'm seeing GF_USERS_AUTO_ASSIGN_ORG_ROLE mentioned in the output logs, but new users who sign in with oauth aren't assigned as "Editor", but "Viewer" instead. I've tried setting this to Admin too, no luck. I've tried with single quotes around 'Editor', but that doesn't work either.

Below is redacted example of my Docker run command:

```
sudo docker run -d \
  --restart=always \
  --user 1000 \
  --net=host \
  --name=grafana \
  -v /data/grafana/var/lib/grafana:/var/lib/grafana \
  -v /data/certs:/data/certs \
  -v /data/grafana/etc/grafana/provisioning:/etc/grafana/provisioning \
  -e "HTTP_PROXY=${MY_PROXY_INFO}" \
  -e "HTTPS_PROXY=${MY_PROXY_INFO}" \
  -e "NO_PROXY=${MY_NOPROXY_INFO}" \
  -e "GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/home.json" \
  -e "GF_SERVER_PROTOCOL=https" \
  -e "GF_SERVER_CERT_FILE=/data/certs/cert.crt" \
  -e "GF_SERVER_CERT_KEY=/data/certs/key.key" \
  -e "GF_SERVER_ENABLE_GZIP=true" \
  -e "GF_SERVER_ROOT_URL=https://${MY_GRAFANA_URL}" \
  -e "GF_SERVER_DOMAIN=${MY_GRAFANA_URL}" \
  -e "GF_SECURITY_ADMIN_USER=grafana_admin" \
  -e "GF_SECURITY_ADMIN_PASSWORD=${random_id.grafana_admin_password.hex}" \
  -e "GF_AUTH_AZUREAD_NAME=Azure AD" \
  -e "GF_AUTH_AZUREAD_ENABLED=true" \
  -e "GF_AUTH_AZUREAD_CLIENT_ID=${var.azure_ad_oauth_id}" \
  -e "GF_AUTH_AZUREAD_CLIENT_SECRET=${var.azure_ad_oauth_secret}" \
  -e "GF_AUTH_AZUREAD_SCOPES=openid email profile" \
  -e "GF_AUTH_AZUREAD_AUTH_URL=https://${MY_AZUREAD_URL}/authorize" \
  -e "GF_AUTH_AZUREAD_TOKEN_URL=https://${MY_AZUREAD_URL}/token" \
  -e "GF_USERS_ALLOW_ORG_CREATE=false" \
  -e "GF_USERS_AUTO_ASSIGN_ORG=true" \
  -e "GF_USERS_AUTO_ASSIGN_ORG_ROLE=Editor" \
  -e "GF_USERS_VIEWERS_CAN_EDIT=true" \
  -e "GF_USERS_EDITORS_CAN_ADMIN=true" \
  grafana/grafana:7.3.6
```

I do see these options popping up in the docker logs for this container indicating the options are at least getting passed along:

```
t=2021-01-22T16:02:05+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_ALLOW_ORG_CREATE=false"
t=2021-01-22T16:02:05+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_AUTO_ASSIGN_ORG=true"
t=2021-01-22T16:02:05+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_AUTO_ASSIGN_ORG_ROLE=Editor"
t=2021-01-22T16:02:05+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_VIEWERS_CAN_EDIT=true"
t=2021-01-22T16:02:05+0000 lvl=info msg="Config overridden from Environment variable" logger=settings var="GF_USERS_EDITORS_CAN_ADMIN=true"
```

**What you expected to happen**:

Expected with GF_USERS_AUTO_ASSIGN_ORG_ROLE set to Editor and oauth configured and working that new users would be added as Editors, but all new oauth users are added as Viewer instead.

**How to reproduce it (as minimally and precisely as possible)**:

Always tough to debug issues related to oauth... Need a working oauth setup and then set GF_USERS_AUTO_ASSIGN_ORG_ROLE to something other than Viewer.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.6
- Data source type & version: N/A -- grafana core config
- OS Grafana is installed on: Running in a docker container -- the official docker image unmodified (grafana/grafana:7.3.6)
- User OS & Browser: Mac OS & Chrome
- Grafana plugins: None
- Others: N/A

**Comment by ivanahuckova** [comment]
@marefr Is this the same/similar/related to https://github.com/grafana/grafana/issues/22820? I see that it still has `needs investigations` label. Any thoughts what could the issue be, or any suggestions how to fix this?

**Comment by marefr** [comment]
@ivanahuckova I don't think it's the same. Looks related to this code: 
https://github.com/grafana/grafana/blob/0079a275afcc1dfe85f169ad0ddd67f6ef2b53b0/pkg/login/social/azuread_oauth.go#L99-L101

Reading the documentation, https://grafana.com/docs/grafana/latest/auth/azuread/#create-the-azure-ad-application, and the following:
> Add definitions for the required Application Roles for Grafana (Viewer, Editor, Admin). Without this configuration, all users will be assigned the Viewer role.

Based on the documentation it works as expected I would say. Please _Add definitions for the required Application Roles for Grafana_. But it would make more sense if the default role was taken from `GF_USERS_AUTO_ASSIGN_ORG_ROLE` if no definitions have been defined in provider.
