### ISSUE TITLE
dashboard: disallow viewer-role users to modify and see queries

### ISSUE THREAD

**Issue by luchaninov** [grafana/grafana#30552]
summary by @gabor: issue originally created for sql datasources, but the problem is generic: currently a viewer-role user can basically execute arbitrary queries against the datasources. for some use-cases this is not suitable.

---

**What would you like to be added**:

Don't expose databases directly to any user:

* Don't show query to viewers (in `/api/tsdb/query` param `queries.{n}.rawSql`)
* Don't allow to run any queries to viewers (changing query in `/api/tsdb/query` )

It is documented:
https://grafana.com/docs/grafana/latest/enterprise/datasource_permissions/

> By default, data sources in an organization can be queried by any user in that organization. For example, a user with the
> Viewer role can issue any possible query to a data source, not just queries that exist on dashboards they have access to.

**Why is this needed**:

Because viewers should have access only to "views" that are allowed for them.

Yes, DB admins can create read-only users and views. But it makes things very complicated and is not always possible.

For example Google Data Studio and Tableau don't expose queries and don't allow to run any query like `DROP TABLE user;`.

Queries in request can be encrypted or better only uid/hash should be sent.

**Comment by torkelo** [comment]
> Because viewers should have access only to "views" that are allowed for them.

This is currently not possible as Dashboards and queries can be very dynamic (composed dynamic variables or query fragments) so there is no way to fully validate that the user cannot issue a specific query 

> Queries in the request can be encrypted or better only uid/hash should be sent.

This could be technically possible if we disabled all the dashboard variable templating features. We are looking at ways to support this. 

> For example Google Data Studio and Tableau don't expose queries and don't allow to run any query like DROP TABLE user;.

We could perform some security checks & searches to find expressions like that, afraid that a skilled SQL user can find ways around those string searches & patterns but might be a good idea still for some basic securiy.

**Comment by strawberrybiscuits** [comment]
I met this issue, I tried drop table/database and it failed . But _delete from xxx_ and  _select sleep(n)_ executed well.Maybe you need add another security checks.

**Comment by septatrix** [comment]
I think this shares the same underlying problem as #21856, #32043 and to some extent also #18157 - or at least they seem solvable with a common fix: Send query and variables separately to the backend. Unless the user is in the query editor the query should be checked if it is valid¹ and afterwards the variables should be put into the query (preferably using parameterized queries to prevents code injection). This could be extended in the future to also perform sanity checks on the variables like checking if they are inside of a predetermined set or range though that is not necessary for solving most of the current security nightmares.

¹Preferably the client should send the query and the id of the dashboard it is on such that the backend can lookup quickly if the query exists on that dashboard. However it would also be possible in theory to only submit the panel id instead of the query. In this case the backend can simply use the stored query and does not even have to check it.

**Comment by septatrix** [comment]
@torkelo what are your thoughts regarding my proposal? Maybe it would also be beneficial to create a discussion thread to explore some possible ideas and solutions.

**Comment by MrFiestaxxl** [comment]
For us this issue is a dealbreaker as it is possible to use any other data source configured. The proposal to check in the backend if this SQL matched the stored one should be that hard. To contain variables is on another table.

**Comment by codeincarnate** [comment]
This is something we're definitely looking into. The context around this has changed a fair amount and the fundamentals of this should be handled with [Grafana Public Dashboards](https://grafana.com/docs/grafana/latest/dashboards/dashboard-public/) related code. That being said it may take some time to get to a final solution.

**Comment by MrFiestaxxl** [comment]
As for my company we went the route to build an middleware in between grafana and database to prevent this

**Comment by rruckley** [comment]
Is this being looked at, we're being asked about such issues by our security team.

**Comment by codeincarnate** [comment]
This is currently being looked at, it does however mean large architectural changes. The majority of Grafana datasources allow for queries to be edited directly in the front-end, so this means potentially significant underlying changes.

**Comment by natellium** [comment]
Hello! Thank you for submitting a feature request. We’ve reviewed your request and have decided not to implement this feature. As @gabor mentioned above this would mean a fundamental change in how Grafana behaves and we won't be considering it in the foreseeable future. We'd recommend looking into the alternatives offered above instead.

Thank you again for the request! Even when we make the decision not to pursue a feature, the submission encourages conversations and ideas within our development team to continue making improvements, so please keep sharing!
