### ISSUE TITLE
Login screen doesn't support keepass2 / keefox

### ISSUE THREAD

**Issue by Carles-Figuerola** [grafana/grafana#3055]
When my keepass2 / keefox fills the fields on grafana's login page, the login button is disabled until I manually do a character change on both username and login fields.

![Login screen](http://i.imgur.com/NWEfQCE.png)

This is the html for the page:

![inspect page](http://i.imgur.com/HbaWcSF.png)

**Comment by sbouchex** [comment]
@Carles-Figuerola, with version 2.6.0-pre1 (nighly build), it's working fine.

**Comment by bergquist** [comment]
I'm closing this since we are soon releasing 2.6
