### ISSUE TITLE
Feature Request: Editable tags UI for Opentsdb query

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3056]
Currently, we have to delete the tag by clicking on the "x" button and apply it again. This is just a usability issue. Instead we should be able to just edit the tag value instead of reapplying the whole tag name/value combination.

<img width="1277" alt="screen shot 2015-10-27 at 1 09 08 pm" src="https://cloud.githubusercontent.com/assets/1019609/10771077/110841e0-7cac-11e5-81ee-3fa33a3fbd33.png">

Making the above tags editable.

**Comment by torkelo** [comment]
this should be easy, InfluxDB and Cloudwatch editors uses UI components that can reused for this.

**Comment by utkarshcmu** [comment]
Fixed in #3234

**Comment by utkarshcmu** [comment]
Thanks @torkelo :)

Closing this issue as #3234 is merged.
