### ISSUE TITLE
Please provide released grafana source code.

### ISSUE THREAD

**Issue by xaque208** [grafana/grafana#3057]
In the pre 2.x series, the source was available as grafana-x.y.z.tar.gz on s3.  Now that no longer seems to be the case.  I'm looking to port grafana to non-linux, so I would like just the source, and not the compiled linux version.

**Comment by kokarn** [comment]
You posted this on the GitHub repo? Isn't thus where the source is or are
you looking for something not hosted here?

**Comment by adamcstephens** [comment]
GitHub provides source tarballs of releases here:  https://github.com/grafana/grafana/releases

**Comment by torkelo** [comment]
Yea, github provides source tarballs, 
https://github.com/grafana/grafana/releases

Latest release:
https://github.com/grafana/grafana/archive/v2.1.3.tar.gz
