### ISSUE TITLE
Environment Variables required for some machines like Synology NAS running docker.

### ISSUE THREAD

**Issue by YerBabiE** [grafana/grafana#30579]
Environment variables for docker containers would be nice as machines like Synology NAS's do not allow you to get to the .ini files easily or at all. It would be great to enable public access to URL's etc but at the moment it can't be done.

**Why is this needed**:

Some devices running docker have GUI and interfaces that do not allow access to underlying files etc.

**Comment by papagian** [comment]
@YerBabiE 
Are you looking for a way to configure grafana using environment variables? If yes, that's possible; please check [here](https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables) for details.

**Comment by YerBabiE** [comment]
The doco states:
'Anonymous authentication
You can make Grafana accessible without any login required by enabling anonymous access in the configuration file.'

So this does not work as an environment variable:
GF_AUTH.ANONYMOUS_ENABLED true etc.....

**Comment by papagian** [comment]
It should be `GF_AUTH_ANONYMOUS_ENABLED=true` so you can start the container like:
```
docker run \
-e GF_AUTH_ANONYMOUS_ENABLED=true \
--rm -p 3000:3000 grafana/grafana
```
