### ISSUE TITLE
Some queries don't work in Query variables (7.4.0 beta 1)

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#30595]
**What happened**:
After the last update queries with functions like **count, cast** throw an error
![Screenshot_5](https://user-images.githubusercontent.com/43705385/105697911-3e0eab00-5f16-11eb-8f23-b3ead0082bc7.png)

**Environment**:
- Grafana version: 7.4.0 beta 1
- Data source type & version: postgeSQL 12 + timescaleDB 2.0-rc1
- OS Grafana is installed on: ubuntu 20.04
- User OS & Browser: windows 10, chrome
- Grafana plugins:
- Others:

**Log:**
[log.log](https://github.com/grafana/grafana/files/5866110/log.log)

**Comment by DmitrySidorow** [comment]
I rolled back to 7.3.7 and everything works as expected

**Comment by ivanahuckova** [comment]
fyi @hugohaggmark

**Comment by hugohaggmark** [comment]
Thank you @ivanahuckova

**Comment by hugohaggmark** [comment]
@DmitrySidorow thank you for taking time to report this, just to be clear does this query work for you `SELECT cast(count(*) as text) FROM carriage_list WHERE type=2` or do you have issues with CAST as well?

**Comment by DmitrySidorow** [comment]
> @DmitrySidorow thank you for taking time to report this, just to be clear does this query work for you `SELECT cast(count(*) as text) FROM carriage_list WHERE type=2` or do you have issues with CAST as well?

casting to text fixes that problem

**Comment by hugohaggmark** [comment]
> > @DmitrySidorow thank you for taking time to report this, just to be clear does this query work for you `SELECT cast(count(*) as text) FROM carriage_list WHERE type=2` or do you have issues with CAST as well?
> 
> casting to text fixes that problem
> ![Screenshot_7](https://user-images.githubusercontent.com/43705385/105710930-dd3c9e00-5f28-11eb-85db-c9c40c7cef8a.png)

Ok, thank you @DmitrySidorow so when does CAST not work?

> **What happened**:
> After the last update queries with functions like **count, cast** throw an error

**Comment by DmitrySidorow** [comment]
> > > @DmitrySidorow thank you for taking time to report this, just to be clear does this query work for you `SELECT cast(count(*) as text) FROM carriage_list WHERE type=2` or do you have issues with CAST as well?
> > 
> > 
> > casting to text fixes that problem
> > ![Screenshot_7](https://user-images.githubusercontent.com/43705385/105710930-dd3c9e00-5f28-11eb-85db-c9c40c7cef8a.png)
> 
> Ok, thank you @DmitrySidorow so when does CAST not work?
> 
> > **What happened**:
> > After the last update queries with functions like **count, cast** throw an error

cast(car_num as integer) - does not work
cast(cast(car_num as integer) as text) - works

**Comment by hugohaggmark** [comment]
Thank you @DmitrySidorow, I suspected as much.
