### ISSUE TITLE
Let us save a collection of panels outside of dashboards

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30591]
**What would you like to be added**:

I would like to be able to create panels, save them outside of dashboards. Name it "Panel Collection" for now. Then re-use this panels (with queries of course, I'm not only talking about saving the styling) inside dashboards from that collection. Like pre-defined widgets.

**Why is this needed**:

Let's say I've created a hundred different panels for a similar use case and one customer (or team) is interested in couple of those panels while another customer is interested in other panels. It would be really useful to define the panels beforehand and use them later in dashboards. That way,  no one needs to re-write the similar code or edit the similar panel for a certain styling over and over again.

Also, this feature should be useful for teams or customers who doesn't know SQL & Grafana. They can just select from the pre-defined widgets and create their own customized dashboard. It would help other teams to accept and use Grafana company wide. This would make Grafana really strong in BI besides time-series analytics.

I believe, I explained the idea well enough, but if you have questions we can talk about it. I would be happy if Grafana Team considers this feature. You may come up with better ideas.

**Comment by ivanahuckova** [comment]
Hello @mertbakir, I have a good news for you, we are actually working on the reusable panels/panel library/sharing of panels. Here is the [epic](https://github.com/grafana/grafana/issues/29610) for it. Also, this is the [related issue](https://github.com/grafana/grafana/issues/1803).
