### ISSUE TITLE
Cannot scroll vertically in dashboard Settings pages (7.4.0-beta1)

### ISSUE THREAD

**Issue by svet-b** [grafana/grafana#30593]
**What happened**:
When viewing any of the dashboard Settings pages (including General, Variables, etc) and the extent of the content is greater than the vertical size of the window, vertical scrolling does not work properly. Tested in Chrome and Safari, with slightly different behavior:
- In Safari, the page does not scroll at all
- In Chrome, the page scrolls most of the way, but the bottom of the page cannot be brought into view. E.g. the "Delete Dashboard" button in the "General" page, or the "Update" button when editing a template variable

**What you expected to happen**:
To be able to scroll and see all the content

**How to reproduce it (as minimally and precisely as possible)**:
1. In Chrome or Safari, open a dashboard and go to the Settings page
2. Shrink the window vertically, so the content extends beyond the bottom of the window (this can also be step 1)
3. Try scrolling down

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: N/A
- OS Grafana is installed on: Linux or macOS
- User OS & Browser: macOS 11.1; Chrome 88.0.4324.96 or Safari 14.0.2
- Grafana plugins: N/A

**Comment by ivanahuckova** [comment]
Yes, I was able to reproduce this as well. @grafana/grafana-frontend-platform we should definitely fix this before stable release.
