### ISSUE TITLE
Overrides: Then switching between visualisations, overrides throw error

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#30604]
This is in Grafana 7.3.6

**What happened**:
When switching between table panel with overrides and graph panel, clicking on overrides throw error.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create query and use table visualisation
2. Add overrides 
3. Switch visualisation to graph
4. This trows error, you are not able to use/clear overrides

![Kapture 2021-01-25 at 17 09 48](https://user-images.githubusercontent.com/30407135/105731957-4247c200-5f30-11eb-924a-c3bddfdc8967.gif)

![image](https://user-images.githubusercontent.com/30407135/105732323-9e124b00-5f30-11eb-8aff-ee8a5d4ff06e.png)
![image](https://user-images.githubusercontent.com/30407135/105732359-a4a0c280-5f30-11eb-9123-224a1f214e16.png)

**Comment by torkelo** [comment]
This is fixed in master & 7.4 
Related PRs
https://github.com/grafana/grafana/pull/30389
https://github.com/grafana/grafana/pull/30197
