### ISSUE TITLE
Setup of derivative

### ISSUE THREAD

**Issue by GalaxyGorilla** [grafana/grafana#3060]
Hi, I have a measurement which I query as

  SELECT mean(value) FROM "measurement" WHERE $timeFilter GROUP BY time($interval)

which is a (strict) monotonely increasing function. I actually want to have the derivative of 'value' but trying 

  SELECT derivative(value) FROM "measurement" WHERE $timeFilter GROUP BY time($interval)

I get 'aggregate function required inside the call to derivative'. Next try:

  SELECT derivative(mean(value)) FROM "measurement" WHERE $timeFilter GROUP BY time($interval)

which gives me the zero function. What am I doing wrong?

**Comment by torkelo** [comment]
try SELECT derivative(mean(value), 1s) FROM "measurement" WHERE $timeFilter GROUP BY time($interval)
or SELECT derivative(mean(value), 10s) FROM "measurement" WHERE $timeFilter GROUP BY time($interval)

depending on the rate you want. Also try setting a lower limit for group by time interval to the rate of which you write metrics (for example `>10s`) if you write every 10s. 

if you still have issues please open an issue in the influxdb repo (or ask in their mailing list).
