### ISSUE TITLE
Influx: Incomplete graphs on wider screens when using Flux

### ISSUE THREAD

**Issue by davkal** [grafana/grafana#30607]
**What happened**:

When using a Flux query with `aggregateWindow` with `v.windowPeriod` on multi-day data on a wide screen, the resulting graph is incomplete (works fine on small displays)

**What you expected to happen**:

All requested data should be drawn.

**How to reproduce it (as minimally and precisely as possible)**:

0. Have an Influx datasource
1. Add a dashboard and graph panel with a Flux query where you know you have multiple days of data, and make sure to use `aggregateWindow(every: v.windowPeriod)`
2. View panel on wide screen (e.g, 2560 px wide)
3. Adjust the timepicker to an odd `From`, say `now-5d`
Result: Only part of the series is drawn (and if the query returns multiple series, only the first series is shown)

**Anything else we need to know?**:

On my 2560 px screen, the max datapoint calculated is 2110, while for the range of `now-5d` the auto window period is `2m`. This is clearly off since 5 days of data on a 2m window are: 5 * 24 * 60 / 2 = 3600 datapoints. The query stats panel shows `Total number rows | 3166`, which happens to be 3600 / 1.5. [And 1.5x happens to be the max data cutoff point for the influx/flux backend engine](https://github.com/grafana/grafana/blob/a2a6b9448ff0516a50738ac53fea28a3365d016f/pkg/tsdb/influxdb/flux/executor.go#L30).

**Comment by davkal** [comment]
> On my 2560 px screen, the max datapoint calculated is 2110, while for the range of now-5d the auto window period is 2m. This is clearly off since 5 days of data on a 2m window are: 5 * 24 * 60 / 2 = 3600 datapoints. The query stats panel shows Total number rows | 3166, which happens to be 3600 / 1.5. And 1.5x happens to be the max data cutoff point for the influx/flux backend engine.

@torkelo  something must be odd in the maxDatapoints and Interval interplay. It seems to be calculated somewhere else before being handed to the influx/flux go backend, so I suspect other datasources that have a maxDatapoints cut off might suffer too?

FYI My hotfix here just raises the maxDatapoints factor from 1.5 to 2.

**Comment by R-Studio** [comment]
It looks like the same issue as: https://github.com/grafana/grafana/issues/26484 
_The issue occurs also on the newest version of Grafana v7.4.0._

**Comment by davkal** [comment]
@R-Studio do you mind posting a commenting with your screen width, the time range in the time picker, the max datapoints (MD) that Grafana is calculating and displaying above the query editor, as well as the actual windowing period that is being sent in the query (see the query inspector). We might have to adjust this further in an upcoming patch release.

**Comment by R-Studio** [comment]
@davkal here the requested information:
Screen width: 2560x1440p
Timerange: last 2 days

**Comment by davkal** [comment]
Ah, you're not using the automatic windowing via `aggregateWindow(every: v.windowPeriod)`. Is Grafana somehow setting the `30s` windowing? (Do you mind checking the whole request object in the query inspector?) Or is this just coming from Influx? If the latter is the case, perhaps we have to raise the limit considerably. I the meantime I think you can fix your data display by using ` aggregateWindow(every: v.windowPeriod)` to adjust the interval between datapoints. It's pretty obvious that otherwise you're requesting more data than can be displayed by your screen: 2560px can't display 3570 datapoints.

**Comment by R-Studio** [comment]
@davkal No the 30s are the granularity in that the metrics are written (each 30s one metric point are stored in the InfluxDB)
Since Grafana 7.4.1 something is changed, because "aggregateWindow" is working now as expected.

**Comment by davkal** [comment]
Looks like it's all working then.
