### ISSUE TITLE
Decimals: Graph tooltips are less precise with decimals = auto

### ISSUE THREAD

**Issue by rovo89** [grafana/grafana#30619]
**What happened**:
I tried out how decimals are displayed in 7.4.0-beta1 and had rather surprising results: https://github.com/grafana/grafana/pull/30262#issuecomment-764597588
With https://github.com/grafana/grafana/pull/30519, the situation has improved a lot and it's pretty good now (almost perfect!), but the Graph panel now shows numbers in the tooltip without any decimals when decimals are set to *auto*.

With nightly build Grafana v7.5.0-10813pre (80294b2dbf):
![grafana_30519](https://user-images.githubusercontent.com/1573299/105807285-fafc1880-5fa5-11eb-80b7-a3dcdac17a13.PNG)

With Grafana 7.3.7:
![grafana_737](https://user-images.githubusercontent.com/1573299/105346638-2b2e6a80-5be6-11eb-9828-752a122e7f29.PNG)

**What you expected to happen**:
The tooltip formats the number exactly like the Stats panel, i.e. 4.57 GB in the first panel, 457 GB in the second and 45.7 GB in the third. The axis uses "appropriate" decimals, in this case no decimals are totally sensible.

Apart from that, I would generally expect that the fixed number of decimals also applies to the tooltips - but Graph always displays one decimal more than configured. It's not very important, I just think it's strange.

Note that the new Time Series panel is working fine in all of these things.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Graph panel. Use Static datasource to have a value like 4,567,890,123. Set unit to *bytes(SI)* and decimals to *auto*.

**Environment**:
- Grafana version: nightly build v7.5.0-10813pre (80294b2dbf)
- Data source type & version: Static
- OS Grafana is installed on: Linux
- User OS & Browser: Windows / Chrome
- Grafana plugins: nothing relevant
- Others:

**Comment by rovo89** [comment]
The same applies to the min/max values in the legend (if enabled).

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/30519

**Comment by rovo89** [comment]
@torkelo I don't think so - as mentioned, I'm using a nightly build which includes #30519:
https://github.com/grafana/grafana/commits/80294b2dbf1685d632c000bcc7d923dc6b3b7b67

**Comment by rovo89** [comment]
Working fine again with Grafana v7.5.0-10890pre (f109f06485), thanks!
