### ISSUE TITLE
7.4 Variable Regex Ignored Capture Group

### ISSUE THREAD

**Issue by nickbabcock** [grafana/grafana#30617]
**What happened**:

In 7.4, specifying regex capture group does not apply.

![image](https://user-images.githubusercontent.com/2106129/105793667-299ad480-5f4f-11eb-8c6f-6baef9d9d758.png)

**What you expected to happen**:

The above values should have been `cpu`, `gpuati`, and `superio` (as they were pre-grafana 7.4)

[This can be seen using my dashboard templates](https://grafana.com/grafana/dashboards/11587)

**Anything else we need to know?**:

[Downstream issue](https://github.com/nickbabcock/OhmGraphite/issues/188)

If this WAD, let me know how I should update my community dashboards to be compatible with pre and post grafana 7.4. Also (if WAD) ensure to document this in the release notes as I didn't see it mentioned.

**Environment**:
- Grafana version: 7.4
- Data source type & version: Prometheus

**Comment by hugohaggmark** [comment]
Thanks for taking time to report this @nickbabcock, I'm looking into this ASAP.

**Comment by hugohaggmark** [comment]
Hmm, funny thing is that the query variable `value` is set correctly but the `text/label` is not. So your dashboards should still work @nickbabcock, anyway I'll have a fix for the text/label up soon.
