### ISSUE TITLE
Using dynamic daily ElasticSearch index for annotations

### ISSUE THREAD

**Issue by ranef** [grafana/grafana#3061]
We are using ElasticSearch to store alerts generated by our monitoring system. I would like to use these  alerts as the source for dashboard annotations
When i define the annotations I need to fill the ElasticSearch index however we are using a daily index with a dynamic name  generated automatically  according to the system date (e.g index-2015.10.27)

Can I define this index in Grafana so that the alerts are fetched only from today's index?

e.g something like index-(sysdate(), YYYY.MM.DD)

Thanks!

**Comment by torkelo** [comment]
this is now implemented, annotations will now use the index patterns defined in data source edit view. So new elastic annotations will not have an index field in the annotation settings. Old annotations will still have that field, but if you remove the text from index field input the field will be removed from the view

**Comment by ranef** [comment]
Excellent, Thanks!
When will this feature be released in a formal version?

**Comment by torkelo** [comment]
sometime next week
