### ISSUE TITLE
Variables: Width of Flux query textarea too small

### ISSUE THREAD

**Issue by rovo89** [grafana/grafana#30622]
**What happened**:
Since 7.4.0-beta1, the textarea for the Flux query in the variable definition screen is too small:
![image](https://user-images.githubusercontent.com/1573299/105810945-1b2ed600-5fac-11eb-9703-549709262a6d.png)

Compare to 7.3.7:
![image](https://user-images.githubusercontent.com/1573299/105811260-a314e000-5fac-11eb-94c6-fade88c96380.png)

**What you expected to happen**:
The textarea is wide enough to properly edit the query, i.e. about as wide as the *Regex* input below it.

**How to reproduce it (as minimally and precisely as possible)**:
Install latest Grafana beta / nightly build, set up InfluxDB 2.x datasource, create new variable in any dashboard using the Flux query language.

**Environment**:
- Grafana version: 7.4.0-beta1, still present in nightly build v7.5.0-10813pre (80294b2dbf)
- Data source type & version: InfluxDB/Flux
- OS Grafana is installed on: Linux
- User OS & Browser: Windows / Chrome
- Grafana plugins: none relevant
- Others:

**Comment by torkelo** [comment]
Unable to replicate this on linux + chrome. Can you include what chrome version you used?

**Comment by rovo89** [comment]
Sure, it happens on these browsers on Windows:
- Chrome 87.0.4280.141 (Official build) (64-Bit)
- Chrome 88.0.4324.104 (Official build) (64-Bit)
- Firefox 84.0.2 (64-bit)
- Edge 88.0.705.50 (Official build) (64-bit)

At least on Chrome, it's still working fine for another installation of Grafana 7.3.7.

Dev tools show explicitly defined width of 381px:
![image](https://user-images.githubusercontent.com/1573299/105818464-43700200-5fb7-11eb-830a-add207053036.png)

This was 1036px in Grafana 7.3.7, though I guess this is calculated somehow rather than hard-coded. In the query editor for panels, the editor is correctly shown with full width.
