### ISSUE TITLE
CloudWatch: Migrate queries that use more than one stat

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#30629]
**Background**
Before grafana 6.5, the cloudwatch datasource used the GetMetricStatistics api that had support for more than one stat per api request. In 6.5, we moved away from GetMetricStatistics in favor of the GetMetricData api. GetMetricData only supports one stat per query, so in case more than one stat is used i the editor, one query per stat will be executed in the backend.

**Solution**
Each query in the panel should support one stat only. Therefore, we should migrate queries in the panel and/or annotation queries that has more than one stat to multiple queries instead. E.g:
Before migration             |  After migration
:-------------------------:|:-------------------------:
![Screenshot from 2021-01-26 09-15-08](https://user-images.githubusercontent.com/2388950/105819045-f2144280-5fb7-11eb-90f6-d06add327076.png)  |  ![Screenshot from 2021-01-26 10-33-58](https://user-images.githubusercontent.com/2388950/105827374-33a9eb00-5fc2-11eb-9985-b13122dcd33c.png)

**Why?**
* The query editor should mirror the API that is consumes. It's pointed out clearly in the [datasource docs](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#pricing) that the GetMetricData api is being used. Since the GetMetricData api doesn't support multiple stats per query, it gets confusing when that seems to be the case in Grafana. 
* At the moment, the Id and the Expression fields are being hidden when more than one statistic is selected. This is bad UX and causes confusion among our users. If only one stat was allowed per query row in Grafana, we would be able to introduce two different modes for querying metrics - one visual query builder and then one raw mode for math expressions (very much like in Cloud Monitoring where there's the visual query editor mode and the MQL editor mode).
* In order to support multiple stats per query row in Grafana we need to transform a query row into multiple queries. Once we've received a response from Cloudwatch, each query response is transformed into a query row. This adds lots of complexity to the Cloudwatch backend. If multiple stats queries were migrated to single stat queries, we could remove the [query transformer](https://github.com/grafana/grafana/blob/master/pkg/tsdb/cloudwatch/query_transformer.go) which would make the cloudwatch backend much cleaner. 

**How?**
* In a dashboard, Cloudwatch query rows that use more than one stat must be migrated to one query row per stat. When migrating, the new query rows need to get a new ref id, so this migration might have to be done at another level than within the plugin module.ts. When playing around with this, I put the migration code in DashboardModel.ts but that does not seem right. Maybe the @grafana/grafana-frontend-platform can help me here?
* Users can have alerting rules in the db that are based on the old schema, so the exact same migration must be done in the backend as the one that is done in the frontend. 
* Every part of the cloudwatch datasource that deals with multiple stats needs to be refactored. Although it's a comprehensive refactoring, the outcome is going to be much cleaner code that is easier to follow. 

**Breaking changes** 
* It's possible that users have created alert rules based on a query row that has multiple stats. There's no plan to migrate those alerting rules. Therefore, the behavior might change for those users. That being said, I would probably not make sense to have an alert rule that triggered when for example the `avg` reached a certain limit when multiple statistics are selected for the query. Consequently I doubt the will be a big problem for the Cloudwatch users. 
* If an annotation query has more than one stat, it will be migrated into one annotation per stat. If that's the case, the annotation name will no longer be unique. Therefore, the migrated annotation name will be `[previous name] - [statistic]`. For example, an annotation that has two stats, `Sum` and `Average` and the name `My annotation`, it will be migrated to two stats - `My annotation - Sum` and `My annotation - Average`. 

Would love to get some feedback on this. Are there's any other possible pitfalls that has not been discussed here etc.

**Comment by sunker** [comment]
@mtanda would be great if we could get your feedback on this

**Comment by marefr** [comment]
As discussed before, for me personally I would find it a bit weird to have alert rules for a query using multiple stats. For example minimum and average evaluated based on same condition like greater than. Maybe someone else could provide information in what circumstances using such an alerting query would make sense and/or is useful and used by many users.

Regarding breaking changes. If CloudWatch backend would find a query with multiple stats it has to handle it:
- Return an error (resulting in alert rule failure and should make user aware of the breaking change)
- Log an error (not resulting in alert rule failure, but might result in a broken alert not taking certain condition into consideration.

Regarding migrations, think you have to discuss alternatives with @grafana/grafana-frontend-platform

**Comment by hugohaggmark** [comment]
> However, it has been possible to use a multi-value template variable in this field and setup panel repeat for this field. See this issue. That will no longer work.

@sunker how are you going to prevent this?

**Comment by sunker** [comment]
@hugohaggmark I just tested migrating a multi-value template variable that's being repeated, and it actually works just fine. So no breaking change will be introduced here actually. I'll update the description above.

**Comment by sunker** [comment]
> In a dashboard, Cloudwatch query rows that use more than one stat must be migrated to one query row per stat. When migrating, the new query rows need to get a new ref id, so this migration might have to be done at another level than within the plugin module.ts. When playing around with this, I put the migration code in DashboardModel.ts but that does not seem right. 

@hugohaggmark can you help me with this?

**Comment by hugohaggmark** [comment]
> > In a dashboard, Cloudwatch query rows that use more than one stat must be migrated to one query row per stat. When migrating, the new query rows need to get a new ref id, so this migration might have to be done at another level than within the plugin module.ts. When playing around with this, I put the migration code in DashboardModel.ts but that does not seem right.
> 
> @hugohaggmark can you help me with this?

Sure, maybe DashboardMigrator is a better place? https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/DashboardMigrator.ts

**Comment by mtanda** [comment]
@sunker From a user point of view, If query editor becomes more better, the change is acceptable for most of use case.

If possible, would you consider to add batch edit mode in query editor?
Sometimes, I create graph panel which use two or more Statistic from `Minimum`, `Maximum`, `Average`, `pNN.NN`.
If Grafana split One multiple stat query to Multiple one stat query, batch edit mode will help to change common dimension parameters.

**Comment by sunker** [comment]
> Sure, maybe DashboardMigrator is a better place? https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/DashboardMigrator.ts

It seems like the DashboardMigrator is mainly used for migrating the dashboard schema. I guess we could put it there, but probably not ideal. Wouldn't is be possible to have the [DataSourcePlugin](https://github.com/grafana/grafana/blob/b5d7f1e7d894e69674323d18e4bc523dff5b7247/packages/grafana-data/src/types/datasource.ts#L26) expose a `setMigrationHandler` function, very much like the [PanelPlugin](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/panel/PanelPlugin.ts#L208). Then the datasource plugin could add it's own handler to migrate the dashboard json. The handler would only be able to manipulate those targets that have the same datasource.type as the calling datasource.

**Comment by sunker** [comment]
> @sunker From a user point of view, If query editor becomes more better, the change is acceptable for most of use case.
I agree! However, this issue does not really address how to improve ux specifically, but rather to prepare to that change.

> If possible, would you consider to add batch edit mode in query editor?
> Sometimes, I create graph panel which use two or more Statistic from `Minimum`, `Maximum`, `Average`, `pNN.NN`.
> If Grafana split One multiple stat query to Multiple one stat query, batch edit mode will help to change common dimension parameters.
Not sure what you mean by `batch edit`? If you want to query multiple stats, but don't want to copy the same query row for each stat, you can use row repeat in the panel editor.

**Comment by hugohaggmark** [comment]
> > Sure, maybe DashboardMigrator is a better place? https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/state/DashboardMigrator.ts
> 
> It seems like the DashboardMigrator is mainly used for migrating the dashboard schema. I guess we could put it there, but probably not ideal. Wouldn't is be possible to have the [DataSourcePlugin](https://github.com/grafana/grafana/blob/b5d7f1e7d894e69674323d18e4bc523dff5b7247/packages/grafana-data/src/types/datasource.ts#L26) expose a `setMigrationHandler` function, very much like the [PanelPlugin](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/panel/PanelPlugin.ts#L208). Then the datasource plugin could add it's own handler to migrate the dashboard json. The handler would only be able to manipulate those targets that have the same datasource.type as the calling datasource.

Yeah, I forgot about that one. I'm not very familiar with `setMigrationHandler` so I'm afraid I'll not be that much help here. Maybe @dprokop can help out?

**Comment by mtanda** [comment]
@sunker about batch edit mode, my idea is editing two or more query at once.
The vscode multi cursor feature is similar for my idea.
https://code.visualstudio.com/docs/editor/codebasics#_multiple-selections-multicursor

By changing data model, queries in one graph panel could have many common part.
![image](https://user-images.githubusercontent.com/224552/105998096-a2d12d80-60ef-11eb-9809-4348cdcedd06.png)
I don't want to change dimension value for each query one by one.

Sorry, please forget this idea, it is out of topic.
