### ISSUE TITLE
Visual bugs at login page

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#30620]
**How to reproduce it (as minimally and precisely as possible)**:
![Screenshot_3](https://user-images.githubusercontent.com/43705385/105809351-95665700-5fba-11eb-86cd-1e6fa2c721f2.png)

Large padding on all devices. The login panel also overlaps the footer text on the tablet

**Environment**:
- Grafana version: 7.4.0 beta 1
- User OS & Browser: samsung tab a 10.1 + chrome

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/30443
