### ISSUE TITLE
Time Series panel: Decimals configuration for axis (vs. fields)

### ISSUE THREAD

**Issue by rovo89** [grafana/grafana#30621]
**What would you like to be added**:
I would like to set the precision per y-axis independently from the precision used for the fields (which is used e.g. for the tooltip and min/max in the legend). Currently, the *decimals* setting of the first field using the axis seems to be used to format the tick values.

**Why is this needed**:
Here is an example with one static value 4,567,890,123 with unit *bytes(SI)* and decimals = 4:
![image](https://user-images.githubusercontent.com/1573299/105809084-5b408980-5fa9-11eb-8444-421d7256ea51.png)

While this strictly follows the settings, the decimals for the axis values feel unnecessary and clunky. I would really differentiate here between the values and the ticks. The **values** are some exact numbers, shortened to display them in a human-readable way. The **ticks** are specifically calculated be round numbers, so they're easier to grasp, they just give you an approximate range of the values between the lines. Displaying them with such precision sabotages these efforts.

If the axis always used decimals = *auto*, it would be totally fine for me. Alternatively, there could be another *decimals for axis* field in the axis (and field overrides) configuration to configure the exact precision for the tick values. It would default to the usual *decimals* setting.

**Comment by torkelo** [comment]
Fixed in master (nightly) and  in stable release the auto decimals is much improved so should not be that much need to set the decimals on these to independetly

**Comment by rovo89** [comment]
@torkelo: I'm using nightly already, the screenshot is from Grafana v7.5.0-10813pre (80294b2dbf). Should have mentioned that.

Indeed, the **auto decimals** are perfect there. 👍 However, there can be situations where we want to configure a **fixed decimals** for the values. Why else would there be a configuration for that? And in that case, I would still like the axis to show 0 B / 2 GB / 4 GB, i.e. use *auto* decimals, because that's much easier to read than 0 B / 2.0000 GB / 4.0000 GB for these known-to-be-round numbers.

**Comment by torkelo** [comment]
ok, re-open it as a feature request to see how important this is

**Comment by rovo89** [comment]
Thanks! It was indeed meant as a feature request. And from your response, I get that the additional configuration might be overkill / too much effort, so I've changed the title to reflect that always using *decimals = auto* for the axis tick values would be great.
