### ISSUE TITLE
Live tailing also scroll the main view

### ISSUE THREAD

**Issue by cyriltovena** [grafana/grafana#30634]
**What happened**:

Trying to read the bottom of my page but I'm fighting with the auto scroll of loki live-tailing

**What you expected to happen**:

I can freely scroll my main page while loki data is refreshing.

**How to reproduce it (as minimally and precisely as possible)**:

Just tail some logs with multiple queries editor.

https://user-images.githubusercontent.com/1053421/105837387-a3a57a80-5f9c-11eb-8a03-e8213e1b658e.mov

**Environment**:
- Grafana version: Grafana v7.5.0-10872pre (10aabe8ce3)
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Thanks Cyril, I will look at it.
