### ISSUE TITLE
Panel: Cannot disable test data source query when there is only a single query

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#30646]
**What happened**:
![Kapture 2021-01-26 at 16 17 32](https://user-images.githubusercontent.com/1173299/105865020-cd898c00-5ff2-11eb-897f-dc70805ad576.gif)

**What you expected to happen**:
Single queries should also be capable of being disabled

**Environment**:
- Grafana version: Verified on master and 7.3.7
- Data source type & version: TestData DB
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS + Google Chrome v87
- Grafana plugins: TestData DB

**Comment by torkelo** [comment]
This looks like a backend issue, the backend http request is not responding, just hanging

**Comment by wbrowne** [comment]
>This looks like a backend issue, the backend http request is not responding, just hanging

@torkelo  Yeah it looks that way but actually, the frontend never issues a call to `api/ds/query`. Have tried to trace it locally, but just seems to get stuck somewhere in the JS

**Comment by papagian** [comment]
I confirm that no request is sent to the backend in that case.

**Comment by torkelo** [comment]
yea, it was a frontend issue, fixed :)
