### ISSUE TITLE
Data source name doesn't update in query editor when data source variable is used with mixed data source

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#30657]
**What happened**:

I found a display bug in the query editor when using a data source variable inside the `-- Mixed --` data source.

**What you expected to happen**:

The name of the data source is either the variable name (`$ds`) and doesn't change when a different data source is selected, or the data source name is dynamically updated when a different data source is selected.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a data source variable `$ds`.
2. Create a panel.
3. Select the `$ds` data source.
4. Select the `-- Mixed --` data source.
5. The currently selected `$ds` value becomes the data source name for query A.
    ![Screenshot 2021-01-26 15-49-46](https://user-images.githubusercontent.com/3270755/105904387-13dcec00-5fef-11eb-8e66-5308c0ba6623.png)
![Screenshot 2021-01-26 15-50-08](https://user-images.githubusercontent.com/3270755/105904457-25be8f00-5fef-11eb-8287-65c0eebca2e0.png)

6. On the `ds` variable value selector, select a different data source.
7. The query and the data presented in the panel is updated but the data source name (_Lab servers_) in the query editor is not.
8. When I return to the dashboard and re-open the query editor, the data source name is updated to the currently selected data source.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.7
- Data source type & version: data source variable
- OS Grafana is installed on: Linux, binary tarball
- User OS & Browser: Firefox 84 on Fedora 33
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/32090
