### ISSUE TITLE
Downsampling- and retention-aware $__rate_interval for Thanos-backed prometheus data sources.

### ISSUE THREAD

**Issue by krya-kryak** [grafana/grafana#30662]
**What would you like to be added**:
$__rate_interval should take downsampling policies into account for Thanos-backed prometheus datasources. "Zooming into the past" should not fail to produce meaningful results due to `$__rate_interval` being set, for example, to `150s` when retention policy only keeps one datapoint per hour.

**Why is this needed**:
Currently `$__rate_interval` is defined as `max( $__interval + Scrape interval, 4 * Scrape interval)`, which is fine for pure prometheus data sources. However, if datasource performs downsampling and separate retention policies for each downsampling level, that could be insufficient for a query to "just work" for all the use cases.

Say, we have a Thanos installation set as a Prometheus datasource. Thanos retention policies are set as follows:
RAW: 30 days
5 Minute: 90 days
1 Hour: 3 years
One has a panel with a query `rate(metric_name{}[$__rate_interval])`. It would work fine for the "Last N days" queries, but it would fail if one wishes to see a graph for a single day set 5 months into the past, the actual query would be something like:
`rate(metric_name{}[150s])`
But this specific datasource only has datapoints every 3600 seconds, which leads to empty result.
It would be marginally better to send a query like 
`rate(metric_name{}[7200s])`
and actually have sensible data displayed. After all, downsampled data is there for people to use.

**Comment by davkal** [comment]
We thought long and hard about this. I don't think retention policies should be a query client's (like Grafana) concern. If you need the rate interval to adjust for historic data, I suggest to configure a second datasource with a longer scrape interval as a workaround. It's not ideal, but should work.

**Comment by krya-kryak** [comment]
Thanks for reaching a decision, David.
I do appreciate the reasoning behind it.
