### ISSUE TITLE
Changed Metrics List behavior makes Metrics unusable

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/grafana#30679]
**What happened**: Metrics list stops working, freezes with larger amount of metrics

**What you expected to happen**: Metrics list does not freeze and allows to load portions of the metrics based on the text entered.

**How to reproduce it (as minimally and precisely as possible)**:
Connect to a database with over 100.000 Metrics. Grafana will try to load all metrics at once and populate some sort of cache. Due to the large amount of Metrics, this will take much longer and makes the list instable.

**Anything else we need to know?**:
In 6.7.3 Grafana Version with simpod-json-datasource 0.1.8.0 everything worked fine:
On each key entry the Metrics List run a new query against the DataSource. That allowed us to limit the number of items returned with one query and let the user select the desired name by entering more and more characters.

Without this behaviour we cannot limit the list of returned metrics resulting from api/datasources/proxy/2/search/ query and as such the whole system becomes instable / unsable.

Please kindly add a configuration possibility to enforce the previous "each key entry runs its own search query" behavior.

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: https://grafana.com/grafana/plugins/simpod-json-datasource 0.2.3.0
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Not sure what you are referencing, a query variable ? What is slow? Selecting a value in the variable drop down?

**Comment by KrisztianKaszas** [comment]
I have a database with up to 100.000 time series. If I click on the Metrics selection list (e.g. in Exploration gui or in a panel editor) a /search query is being initiated, that is querying all metric names causing a traffic of ca. 500 Kbyte of data.

While querying data the Metrics control shows a wait symbol (for 5 Seconds or maybe longer). After that I can select one metric by typing. This is not fluent anymore.

Once a metric has been selected and I want to change it to another metric and I click again on the Metrics control, the control should change its border to blue and let me change the selection. For like 5 another seconds the Metric control does not react at all. After that five second the user can change the selection... 

It seems, the Metrics control requests all available metrics at once, than it caches them, than on each key press it filters the cached list without calling the /search API.

In 6.x versions with simpod-json-datasource 0.1.8.0 the behaviour was different. The metrics control called upon each key press a new metrics search via /search API.

That was maybe not efficient (too many datasource calls), but that worked, if the /search request response was limited e.g. to 100 results (in the datasource implementation) and it was much more fluent compared to now. 

So in a case with limited /search response (lets assume 100 names in one response), while the user typed in a metric name, additional metric names were getting loaded via new /search API calls. That caused maybe more handshakes between the datasource and Grafana, but in much smaller chunks. To find a specific metric, the traffic was most of the time less than now, since only a small part of the list had to be loaded in order to find a particular object.

On top of that, by caching the whole list, besides negative performance effects on an overpopulated list, the list won't receive updates (e.g. if in the meanwhile new time series metrics were added to the datasource). 

So please kindly consider to let the Grafana administrator decide whether to cache Metrics lists and risk low performance due to large lists, or whether to apply the old behaviour and run a /search with each key press in Metrics control to get a new portion of names.

Best Regards
Krisztian

**Comment by hugohaggmark** [comment]
@KrisztianKaszas https://grafana.com/grafana/plugins/simpod-json-datasource is an external data source plugin so I think I need some clarification. Do you mean that using simpod-json-datasource 0.1.8.0 in Grafana 6.x differs from using using simpod-json-datasource 0.1.8.0 in Grafan 7.x?

I need to know exactly what we should investigate. Thank you!

**Comment by KrisztianKaszas** [comment]
@hugohaggmark  I am now using **Grafana 7.3.7** with **SimPod Json DataSource 0.2.3**. In this combination the Metrics List only runs the /search API call the first time, when the list is loaded. After that, on any key press, the Metrics list tries to filter itself by the entered string. Thies leads to the issue, I have to provide thousands of metrics at once, which makes the list unresponsive.

The behaviour was **different** in previous Grafana + SimPod Json DataSource combinations, such as:
- **Grafana 6.7.3 + SimPod 0.1.8**
- **Grafana 6.4.4 + SimPod 0.1.7**

In all of these two mentioned combinations the Metrics List run a /search API call on every key press. As such I could limit the items returned to the list e.g. on the first 100 items, since upon entering more characters the /search API could send more exact search criterias to the source system.

**Comment by hugohaggmark** [comment]
@KrisztianKaszas then this might be an issue with SimPod Json DataSource 0.2.3 and you should create an issue [in their repo](https://github.com/simPod/GrafanaJsonDatasource).

**Comment by ivanahuckova** [comment]
@KrisztianKaszas I see that you have created the issue in SimPod Json DataSource therefore I am closing this issue.
