### ISSUE TITLE
TestData: Add Support for Multiple Series with Different Labels

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#30678]
**What would you like to be added**:
Many data sources support queries like `host={*}`, and multiple series (or numbers) will be returned from the same query with different labels (but associated with the same RefID).  (https://grafana.com/docs/grafana/latest/getting-started/timeseries-dimensions/ for more on this).

However, we do not simulate this well with our test data source. It will usually return one thing per query (randomwalk has a series count, but they will use same labels). 

So I would like to change the follow scenarios such that you can replicate the query editor within a query ("refId"):
 - Load Apache Arrow Data
 - Predictable CSV Wave and Predictable Pulse
 - (Maybe Random walk, but this could be complicated, and would not want it to be a blocker).

So there would be something like a plus button, that after would look something like the following (except my inspect html edit skills make it look ugly):

![image](https://user-images.githubusercontent.com/1692624/106005114-e2613080-6081-11eb-9ddf-0ac62a7a1b8a.png)

Such that RefID/Query "A" will return two series one with labels `{a=b}` and another with `{a=c}`.

**Why is this needed**:

- Be able to simulate data returns from systems like prometheus or other things where we are using a label based model
- Be able to simulate data for conditions with Expressions and Alerting NG.

**Comment by kylebrandt** [comment]
Note: Might be a fairly big change in models (become an array)? and backend would need to support change as well. So would want to wait on https://github.com/grafana/grafana/pull/29916 I think.

**Comment by ryantxu** [comment]
With https://github.com/grafana/grafana/pull/29916 this will be pretty easy... without it, no idea
