### ISSUE TITLE
X-axis time scrolling is broken due to commit b52f9fed68

### ISSUE THREAD

**Issue by faxm0dem** [grafana/grafana#30686]
This commit https://github.com/grafana/grafana/commit/b52f9fed68 breaks the time scrolling, when new data arrives e.g. through streaming datasources.

**Comment by torkelo** [comment]
no it still works as it did, https://play.grafana.org/d/nP8rcffGk/1-new-features-in-v7-4?viewPanel=29&orgId=1

the time range needs to be relative

**Comment by faxm0dem** [comment]
Well, my time range is relative, so there must be something else wrong here !
I see on your example there is a dot toggling "streaming start/stop", I guess I'm missing that in my case. How do I enable that ?
@torkelo

**Comment by faxm0dem** [comment]
For the record, @torkelo answered on another channel that the trick was to set the **state** when calling the subscriber:

```typescript
subscriber.next({
  [...]
  state: LoadingState.Streaming,
});
```
