### ISSUE TITLE
Variables: Value with custom all value does not show the text representation `All` when used in panel title 

### ISSUE THREAD

**Issue by Gauravshah** [grafana/grafana#30685]
**What happened**:
when rendering variable on panel title it renders variable value

**What you expected to happen**:
we were expecting it to render variable text. This was the case prior version 7.x

**How to reproduce it (as minimally and precisely as possible)**:
create a variable with `all` option
add custom value for all with `_some_text_`
set title as `abc - ${app_type}`

**Anything else we need to know?**:
we expect the title to show up as `abc - all`
but we see `abc - _some_text_`

we have tried using `abc - ${app_type:raw}` & `abc - ${app_type:text}`

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: NA
- OS Grafana is installed on:
- User OS & Browser: Mac OSX, Brave, chrome
- Grafana plugins:
- Others:

**Comment by Gauravshah** [comment]
this would break repeated dashboards mentioned in this blog https://grafana.com/blog/2019/07/17/ask-us-anything-how-to-alias-dashboard-variables-in-grafana-in-sql/

**Comment by torkelo** [comment]
Working when I test: https://play.grafana.org/d/c9ouF7LMk/key-value-variable-in-title?orgId=1 
server variable is a key value (text & value) variable, and the panel title gets interpolated to the text property

**Comment by torkelo** [comment]
Hm.. seeing the problem with custom all though

**Comment by Gauravshah** [comment]
@torkelo didn't realise the problem was limited to `all`. Thank you for updating it

**Comment by Gauravshah** [comment]
thank you @hugohaggmark
