### ISSUE TITLE
Azure Monitor: Dashboard JSON uses Azure workspace UUID instead of workspace name.

### ISSUE THREAD

**Issue by ArsalanMacknojia** [grafana/grafana#30692]
**Issue**:
I've created a Grafana dashboard to display **Azure Metrics** and **Logs** and exported that dashboard as a JSON file. I wanted to use that template to create multiple dashboards for different **Azure Resource Groups** and **Workspaces**. However, I noticed in the JSON **Azure Resource Group** is referred using **resource group name** but **Workspace** is referred using **workspace UUID**. 

e.g. 
```
          "azureLogAnalytics": {
            "query": "AzureDiagnostics\n| where ResourceProvider == \"MICROSOFT.DBFORPOSTGRESQL\"\n| where LogicalServerName_s == \"$ResourceName\"\n| where TimeGenerated >= $__timeFrom() and TimeGenerated <= $__timeTo()\n| project TimeGenerated, Message, errorLevel_s\n| limit 50",
            "resultFormat": "table",
            "workspace": "e52a46d2-d3b2-45c4-954f-46a78e4d0f1a"
          },
```

The issue is workspace name is known but workspace UUID is randomly generated during runtime and can't be used in dashboard JSON. 

**Expectation**:
Dashboard JSON should accept Workspace name just like it accepts Resource Group name instead of UUID.

**Dashboard**
As evident Diagnostics Log panel is failing because dashboard JSON expects workspace UUID instead of name.

<img width="1193" alt="Screen Shot 2021-01-27 at 3 52 48 PM" src="https://user-images.githubusercontent.com/36348596/106072191-95e71680-60bc-11eb-8106-3e94564b827a.png">

**Environment**:
- Grafana version: v7.3.6
- Data source type & version: Azure Monitor v0.3.0
- User OS & Browser: MacOS, Chrome
- Others:

**Comment by sysintelligent** [comment]
Hey @ivanahuckova, I see you removed the 'bug' label. The problem is critical as the end-user has to manually set up the configuration for log every time they check it. This is like a show-stop bug at least in my opinion. May I ask what's the plan and when we can get this 'feature'? Thanks.

**Comment by ArsalanMacknojia** [comment]
Hi @ivanahuckova, I agree with @sysintelligent. Kindly treat this as a bug if it prioritizes the request. Manually fixing the dashboard is not ideal specially for the end-user.

**Comment by sysintelligent** [comment]
Hi @ivanahuckova, any updates on the issue?

**Comment by joshhunt** [comment]
@ArsalanMacknojia @sysintelligent To make sure I understand correctly - the issue is that you have Workspaces named the same across multiple resource groups, and you switch the resource group via a template variable to view workspaces in each of the resource groups, but because Grafana saves the Workspace UUID (as opposed to the name), this fails?

This is a thorny one. We're working on a re-work of the Logs datasource to switch to the resource-centric queries, so we'll keep this one in mind.

**Comment by ArsalanMacknojia** [comment]
Hi @joshhunt,
I want to use Azure Workspace **name** in template JSON instead of **UUID**. Azure workspace is created during the runtime so UUID is unknown, however, the workspace name is predetermined so I can store that in template JSON.

Currently, Grafana accepts resource group name in template JSON but for workspace it ask for UUID. I hope this clarifies the issue.

**Comment by ArsalanMacknojia** [comment]
Hi @joshhunt,
I want to use Azure Workspace name in JSON template instead of UUID. Azure workspace is created during the runtime so UUID is unknown, however, the workspace name is predetermined so I can store that in JSON template.

Currently, Grafana accepts resource group name in JSON template but for workspace, it asks for UUID. I hope this clarifies the issue.

**Comment by joshhunt** [comment]
@ArsalanMacknojia Ahh so you're saving the dashboard to JSON and then using that as a template, changing that outside of Grafana and them importing it back in?

It's a tricky one because the Azure API addresses Workspaces by UUID, but resources and resource groups by name. We _need_ that UUID so we can actually request the data - just a name is not enough. This isnt a bug, but just how the Azure API works.

A template variable query looks like it could be helpful for this, but none exists for this yet (despite what the documentation says...), so I'll tag this as a feature requests and we'll keep it in mind for the upcoming work.

**Comment by joshhunt** [comment]
Actually @ArsalanMacknojiaIt - I know its not ideal, would doing cross-workspace queries achieve this? 

https://docs.microsoft.com/en-us/azure/azure-monitor/logs/cross-workspace-query#identifying-workspace-resources

So you select any workspace UUID in the Grafana UI, but in the KQL query you can use the `workspace("contosoretail-it")` syntax to query a specific resource by name. You could then find-replace that when you template it. This is what Grafana Azure Monitor the documentation is referring to, which confused me.

Another approach would be for you to call the Azure Monitor API yourself to find a workspace by name and insert that UUID into the structure.

**Comment by ArsalanMacknojia** [comment]
Hi @joshhunt, 
Thanks for responding back. I changed the KQL query to specify the workspace name and got the logs but it only worked when I manually selected a valid workspace UUID in Grafana UI which defeats the purpose. The end-user won't be able to manually edit the dashboard.

The second solution should work but it's not scalable in my case without a secondary application that calls the Azure endpoints and updates all the dashboards. Seems like this is the only option as of now.

I appreciate the help. Hopefully, passing workspace names will be an option in the future. :)

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can't see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
