### ISSUE TITLE
different edit permission with different browser (chrome & safari)

### ISSUE THREAD

**Issue by bigHave** [grafana/grafana#30694]
**What happened**:
I have edit permission with dashboard D-A.   
I have a panel P-A inside dahboard D-A.   
I tried to edia panel P-A,  however, when I open grafana with chrome, I can not edit panel P-A.   
I just can't see edit option:
![image](https://user-images.githubusercontent.com/9249583/106090509-4b6da480-6165-11eb-84e4-182d46115bf2.png)

but instead I open grafana with safari, everything works fine, I can edit panel P-A.  

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
so far, no way to reproduct it .   
may be a bug with special user and dashboard?

**Anything else we need to know?**:

**Environment**:
- Grafana version:
v6.7.4
- Data source type & version:
prometheus & 2.19.2
- OS Grafana is installed on:
debian 
- User OS & Browser:
Macos
- Grafana plugins:
graph
- Others:

appreciated for any replys.

**Comment by torkelo** [comment]
Maybe you have anonymously enabled and did not login? We have no similar reports, so most likely something wrong on your end. 

In your profile you can see your org & org role 
<img width="1034" alt="Screen Shot 2021-01-28 at 07 56 47" src="https://user-images.githubusercontent.com/10999/106101602-67118480-613e-11eb-90ec-20164362acbc.png">

Try upgrading to 7.3

**Comment by torkelo** [comment]
Sorry for closing right away, will re-open if you can replicate reliably and have eliminated all possible reasons on your end. Just that no one else reported this for such an old release that many hundreds of thousands of users have used for over a year makes it unlikely that is a Grafana bug

**Comment by bigHave** [comment]
I see, thx for replying.
