### ISSUE TITLE
Query statement doesn't restrict group by statement

### ISSUE THREAD

**Issue by timur-orudzhov** [grafana/grafana#30719]
**What happened**:

I have a chart with a straightforward configuration:

![image](https://user-images.githubusercontent.com/3646772/106185471-e9885b80-61b3-11eb-89ae-fd5d1beb42e1.png)

**What you expected to happen**:

I've faced strange behavior that my query statement `logger: sentmail` does not restrict group by statement and no matter which query I write I will get all values for **utm_campaign** that are in index, but with another **logger**.

I was trying to find the root of the problem and looked at the query, but unfortunately, I have no idea why this behaves that way. Maybe it will help you:

```
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": 1606770000000,
              "lte": 1607374799000,
              "format": "epoch_millis"
            }
          }
        },
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "logger: sentmail"
          }
        }
      ]
    }
  },
  "aggs": {
    "3": {
      "terms": {
        "field": "utm_campaign.keyword",
        "size": 500,
        "order": {
          "_count": "desc"
        },
        "min_doc_count": 0
      },
      "aggs": {
        "2": {
          "date_histogram": {
            "interval": "1d",
            "field": "@timestamp",
            "min_doc_count": 0,
            "extended_bounds": {
              "min": 1606770000000,
              "max": 1607374799000
            },
            "format": "epoch_millis"
          },
          "aggs": {}
        }
      }
    }
  }
}
```

Regarding to [es docs](https://www.elastic.co/guide/en/elasticsearch/reference/current/filter-search-results.html) **query** statement should restrict **aggs** statement, but it doesn't.

I've also checked some queries via kibana: `logger: sentmail and utm_campaign: some_not_related_value_to_sentmail` and I didn't get anything. Maybe the problem is a query generated by Grafana. Thanks for your attention.
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana v7.3.7 (1e261642f4)
- Data source type & version: ElasticSearch v 7.8.0
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Strange, works here: https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated?editPanel=1&orgId=1&var-source=All&var-host=server1

**Comment by Elfo404** [comment]
Hi @timur-orudzhov , thanks for reporting this.
I suspect this is related to `min_doc_count`.

Weirdly i see from the screenshot you have `Min Doc Count: 1` in your `Terms` bucket aggregation, but the query you pasted shows something different:

```json
    // [...]
    "terms": {
        "field": "utm_campaign.keyword",
        "size": 500,
        "order": {
          "_count": "desc"
        },
        // HERE:
        "min_doc_count": 0
      },
```

can you try from the query editor to change that value back to 1? (maybe try setting something else like 5, leave the field and then change it back to 1 to trigger the onChange cycle if the UI is stuck to something inconsistent)
Or also updating directly the dashboard JSON model from the dashboard's settings page?

**Comment by timur-orudzhov** [comment]
@torkelo @Elfo404 thanks for your replies. the root of the problem is the value in `min_doc_count`, 0 – lead to the appearance of improper values (that not satisfy query)

**Comment by Elfo404** [comment]
Awesome! glad it solved the issue.

**Comment by timur-orudzhov** [comment]
I've also reproduced that behavior in the playground:

![image](https://user-images.githubusercontent.com/3646772/106274983-3288f000-6246-11eb-9b97-4487225ec641.png)

**Comment by Elfo404** [comment]
I think this is the correct behavior when `min_doc_count=0`: https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html#_minimum_document_count_4

The confusion comes from the fact that elasticsearch (and kibana) both uses `1` as defaults for terms aggregations while we use `0`.

The difference between 7.3 and 7.4 (what we have in the playground) is that now when you delete the `min_doc_count` field in the query editor we stop setting it back to `0` (Grafana default) but we omit it from the query, therefore it fallbacks to Elasticsearch's default (`1`)
