### ISSUE TITLE
DataSourceSrv is not updated after creating a new data source via HTTP API

### ISSUE THREAD

**Issue by asimonok** [grafana/grafana#30728]
**What happened**:
DataSourceSrv is not updated after creating a new data source via HTTP API call. And need to refresh the page to be able to get added data source from DataSourceSrv.get(). Until the page is refreshed or updating the added data source, I'm getting the following error `Datasource named [Data Source Name] was not found`.

**What you expected to happen**:
After creating a new data source via HTTP API call, I'm able to get the added data source via `DataSourceSrv.get()`

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a new data source
2. Return back without updating it
3. Try to get the data source via `DataSourceSrv.get()`

**Anything else we need to know?**:
I use `backendSrv.get('/api/datasources')` for getting the list and for each item use `DataSourceSrv.get()` for making query.
Also on the attached screen, I use the default method for adding a data source and this problem is reproduced too.

**Environment**:
- Grafana version: v7.3.7
- Data source type & version:  redis-datasource
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OS, Chrome 87.0.4280.141
- Grafana plugins: redis-app

![data-source-srv-problem-1](https://user-images.githubusercontent.com/15867703/106243075-bed0ee00-6219-11eb-9979-9f342bfb0907.gif)

**Comment by torkelo** [comment]
A temporary workaround: 

```
  return getBackendSrv()
    .get('/api/frontend/settings')
    .then((settings: any) => {
      config.datasources = settings.datasources;
      config.defaultDatasource = settings.defaultDatasource;
      getDatasourceSrv().init();
    });
```

Plan is to add a reload function to DataSourceSrv https://github.com/grafana/grafana/issues/29809

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/29809

**Comment by mikhailredis** [comment]
@torkelo Thank you, we will use a workaround until `reload()` will be implemented.
Feel free to close.
