### ISSUE TITLE
Table: JSON Tooltip closes when too long

### ISSUE THREAD

**Issue by Northbadge** [grafana/grafana#30727]
**What happened**: Expanding a sub-json in the tooltip causing it to exceed the window size instantly closes the tooltip  
![HMMxqaGpPJ](https://user-images.githubusercontent.com/17266534/106234122-116ad400-6233-11eb-8d11-cb6bde37a6dc.gif)

**What you expected to happen**: Uhm, a scrollbar I guess? 

**How to reproduce it (as minimally and precisely as possible)**: Get a really really long json, and try to display it in table view. [Here's the one I used](https://pastebin.com/2ZAQHgd7)

**Anything else we need to know?**: I'm out of my element, but maybe `CustomScrollbar` can be added in [JSONViewCell.tsx](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/JSONViewCell.tsx) like in [Table.tsx](https://github.com/grafana/grafana/blob/master/packages/grafana-ui/src/components/Table/Table.tsx)? 

Also, the positioning of the tooltip is way off to the right, probably because of the length as well, should I open another issue for that? 

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: postgresql 12
- OS Grafana is installed on: Ubuntu 20.04 LTS
- User OS & Browser: Windows 10 19042.746 / Chrome 87.0.4280.141
- Grafana plugins: The defaults
- Others:

**Comment by ivanahuckova** [comment]
@Northbadge thanks for creating this issue. Regarding:
>Also, the positioning of the tooltip is way off to the right, probably because of the length as well, should I open another issue for that?

Yes, that would be awesome. Could you please do that.
