### ISSUE TITLE
TextPanel: Panel title with variable doesn't update when changing variable value

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#30729]
**What happened**:
When a TextPanel has a panel title that contains a variable the title isn't updated when changing variable value.

**What you expected to happen**:
Panel title with variable values should always interpolate to the correct variable values. 

**How to reproduce it (as minimally and precisely as possible)**:
Try it out here:
https://play.grafana.org/d/c9ouF7LMk/key-value-variable-in-title?orgId=1&var-server=20

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: NA
- OS Grafana is installed on: Grafana Play
- User OS & Browser: Mac OSX, chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Probably due to the text panel not listening to data/refresh events.
