### ISSUE TITLE
Template variables dependent on parent variables break at 6 or 7 levels of depth

### ISSUE THREAD

**Issue by featur3creep** [grafana/grafana#3073]
We have metric names going many layers deep:
var1.var2.var3.var4.var5.var6.var7.actual_metric_data_lies_here

We have templated dropdown boxes that do:
var1 -- * (with a regex)
var2 -- $var1.*
var3 -- $var1.$var2.*

and so on.

I've tried this with "refresh on load" turned on and turned off, but if I make a change in var1, then var2, var3, var4, it seems that the dropdown contents stop refreshing around var6 and var7.

My current workaround is saving and refreshing, but this isn't ideal.  Is this expected behavior?  Am I missing a magic setting somewhere?  Having the ability to add a "refresh dropdowns" button would be a nice fix, but I still don't understand why the templating isn't working as expected.

**Comment by torkelo** [comment]
this is due to need of syncing of updating of dependent variables https://github.com/grafana/grafana/issues/2722
