### ISSUE TITLE
Variable selection is not confirmed when clicking another dropdown 

### ISSUE THREAD

**Issue by xhautaper** [grafana/grafana#30735]
**What would you like to be added**:

When selecting several multi-value variables in a row variable selection of variable should be confirmed when clicking on another dropdown. Currently values of a variables are confirmed only when clicking outside of a dropdown menu, as shown below,

**Why is this needed**:

This would improve filtering of variables

![GifMaker_20210129121919620](https://user-images.githubusercontent.com/61575628/106263527-2ba1b380-622d-11eb-8cc7-cd78cec9f727.gif)

**Comment by ivanahuckova** [comment]
I was able to reproduce this also on [play](https://play.grafana.org/d/000000002/influxdb-templated?orgId=1&var-datacenter=America&var-host=10.1.100.1&var-summarize=1m).

**Comment by DmitrySidorow** [comment]
Really annoying thing, hope it will be fixed
