### ISSUE TITLE
Let us choose the thousand separator

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30733]
**What would you like to be added**:

I would like to be able to select a thousand separator for each panel. e.g. space, comma, dot and none (default).

**Why is this needed**:

I don't want to use "short" option as a unit because customers wouldn't understand that. "none" options looks bad for big numbers, so I need a thousand separator. "Locale Format" seems fine but there are other panels which separates decimal points with a dot. When thousand separator also a dot the dashboard becomes confusing.

Here is an example Locale Format:

![image](https://user-images.githubusercontent.com/43188411/106253890-26426a00-6229-11eb-9579-6a4e8e6eab73.png)

Decimal Points:

![image](https://user-images.githubusercontent.com/43188411/106254587-efb91f00-6229-11eb-8306-6a35bccd8c37.png)

Custom Unit:

Also, "custom units" have no formatting. They are like "none" with a suffix. I would like to be able to select the thousand separator for "custom units" too. I would like to display that as "9 427 foo" or "9,427 foo"

![image](https://user-images.githubusercontent.com/43188411/106255111-a3baaa00-622a-11eb-9655-f154a27c7427.png)

**Comment by ivanahuckova** [comment]
Hello @mertbakir, we have already a very similar opened issue https://github.com/grafana/grafana/issues/21436. Would you mind adding the information you shared in this issue there and I will close this. Thank you!
