### ISSUE TITLE
cannot collapse rows by clicking on its name anymore

### ISSUE THREAD

**Issue by frederic-jomedia** [grafana/grafana#3074]
since 2.5 I cannot close a row by clicking its title.
If the row is close I can open it by clicking the title 
Using the menu still work

**Comment by torkelo** [comment]
already reported and fixed :)
https://github.com/grafana/grafana/issues/3065

**Comment by torkelo** [comment]
will do a 2.5.1 release early next week unless some critical issue is discovered which will warrant an immediate release

**Comment by frederic-jomedia** [comment]
sorry for the noise. Amazing release ..again !
