### ISSUE TITLE
table panel no longer supports data time format

### ISSUE THREAD

**Issue by Gauravshah** [grafana/grafana#30751]
**What happened**:
New table panel doesn't support datetime formatting for overrides

**What you expected to happen**:
older panel ( before grafana 7.x) supported table formatting

**How to reproduce it (as minimally and precisely as possible)**:
- create a new panel with sample data
- go to overrides
- choose column for time
- choose unit as datetime
- No option to set format

**Anything else we need to know?**:
previous version of table panel:
<img width="392" alt="Screenshot 2021-01-29 at 10 59 48 PM" src="https://user-images.githubusercontent.com/620559/106307822-aca08100-6214-11eb-9029-bdedf800a78f.png">
newer version of table panel:
<img width="393" alt="Screenshot 2021-01-29 at 11 00 36 PM" src="https://user-images.githubusercontent.com/620559/106307860-b7f3ac80-6214-11eb-9bee-a647c71e0bdd.png">

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: chrome brave
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can can set custom units which include custom date formats:

https://grafana.com/docs/grafana/latest/panels/field-options/standard-field-options/#custom-units

Example:

 ```
time:YYYY-MM-DD
```

**Comment by Gauravshah** [comment]
Apologies. I was not able to find the documentation.
