### ISSUE TITLE
Grafana Developer guide Problem

### ISSUE THREAD

**Issue by ccyaml** [grafana/grafana#30759]
I couldn't sign up on Grafana's official website, so I came to GitHub to ask questions. sorry!
![image](https://user-images.githubusercontent.com/78244312/106345403-e5128e80-62ea-11eb-9bf2-dfa1f19594e8.png)
What can I do if I don't want `yarn start` keep running? 
I want to build the assets every time when I change the code，because i want to get the assets when this run end.
 if  `yarn start`  keep running,  I don't know when the run ends.
thanks!

**Comment by torkelo** [comment]
If you want to Rebuild frontend assets then yarn start needs to keep running
