### ISSUE TITLE
Docker Image Database configuration

### ISSUE THREAD

**Issue by safaci2000** [grafana/grafana#30757]
**What would you like to be added**:

Currently the docker image is hard coded to use sqlite.  It is a perfectly fine default but there is no way to override the value without pushing your own custom grafana.ini.  

**Why is this needed**:

It would make it easier to run grafana in K8s and even a docker-compose stack if the database_url could be overridden via the environment.

**Comment by torkelo** [comment]
All ini options can be set via env variables https://grafana.com/docs/grafana/latest/administration/configure-docker/

**Comment by safaci2000** [comment]
Thanks, I missed the link.  This is what I over looked: https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables
