### ISSUE TITLE
additional horizontal scroll on mobile devices

### ISSUE THREAD

**Issue by Gauravshah** [grafana/grafana#30753]
**What happened**:
opened https://play.grafana.org/ on iphone 6s & iphone X
we see both horizontal and vertical scroll

**What you expected to happen**:
expect only vertical scroll

**How to reproduce it (as minimally and precisely as possible)**:
open it on any mobile device ( chrome simulator also works)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Mobile Safari
- Grafana plugins:
- Others:

screenshots
![IMG_6018](https://user-images.githubusercontent.com/620559/106313130-8da5ed00-621c-11eb-8552-68ce65dda3b9.PNG)

**Comment by Gauravshah** [comment]
this doesn't happen on grafana 6.5.2
but it does happen on grafana 6.7.5
I believe the issue is because the time dropdown shrunk earlier and now it no longer shrinks
  
<img width="311" alt="Screenshot 2021-01-30 at 10 41 35 AM" src="https://user-images.githubusercontent.com/620559/106347870-97f4d500-6276-11eb-8bc1-47b876a2a43d.png">

**Comment by torkelo** [comment]
Will be fixed in 7.5 , https://github.com/grafana/grafana/pull/30588
