### ISSUE TITLE
Bug: Save button missing on Home dashboard

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3075]
As the home dashboard is editable now, we should be able to save it as well. But I do not see a save button even though I am logged in as admin.

<img width="578" alt="screen shot 2015-10-28 at 11 41 56 am" src="https://cloud.githubusercontent.com/assets/1019609/10799228/f7139e7a-7d68-11e5-94ba-325e1d0cdda9.png">

**Comment by torkelo** [comment]
It's not save able but you can use save as
