### ISSUE TITLE
Grafana v7.4.0-beta1: value mappings in override applying to all columns

### ISSUE THREAD

**Issue by sensej-j** [grafana/grafana#30764]
Hello together,
I wanted to report an Bug.

The value overrides all values in the table, see pictures below

Grafana  Version: Grafana v7.4.0-beta1
In version 7.3.7 everything works

![Image1s](https://user-images.githubusercontent.com/78264478/106358319-e4d6bb00-630b-11eb-9fd0-adf2197ef9c4.jpg)
![Image2](https://user-images.githubusercontent.com/78264478/106358326-eacc9c00-630b-11eb-8d2d-afb90819872a.jpg)

**Comment by torkelo** [comment]
Did you migrate this table from the old to the new table?

**Comment by sensej-j** [comment]
this affects both variants (new table and migration).
I checked again in version 7.3.7, the bug is also there

**Comment by sensej-j** [comment]
Transform "Merge"
![Test_Mapping_Value](https://user-images.githubusercontent.com/78264478/106596302-17272900-6555-11eb-930e-fd35fe430d09.jpg)
