### ISSUE TITLE
Grafana v7.4.0-beta1: Streaming data is not displayed on the Graph panel

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#30769]
**What happened**:

Streaming data from the backend data source is not displayed on the Graph panel. Legend is updating.

![Screen Shot 2021-01-31 at 2 41 16 PM](https://user-images.githubusercontent.com/47795110/106400325-7b6daf80-63d2-11eb-8c66-859b7908e99b.png)

Data Source was created following https://grafana.com/docs/grafana/latest/developers/plugins/build-a-streaming-data-source-plugin/ and is working in 7.3.X.

**What you expected to happen**:

Streaming data should be displayed as in 7.3.X: https://grafana.com/api/dashboards/12980/images/8896/image

**How to reproduce it (as minimally and precisely as possible)**:

1) Use `grafana/grafana:7.4.0-beta1` or master Docker image and install Redis-datasource
```
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=redis-datasource" grafana/grafana:7.4.0-beta1
```

2) Import Streaming dashboard

3) Start Redis

```
docker run -p 6379:6379 redis
```

**Anything else we need to know?**:

The New Time-series panel is not displaying data as well.

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: Redis Data Source
- OS Grafana is installed on Docker
- User OS & Browser: Chrome
- Grafana plugins: Graph plugin and 
- Others:

**Comment by ryantxu** [comment]
Any info in the console?  Are you able to try with master or 7.4.x?  I just tested both with the streaming client:
![image](https://user-images.githubusercontent.com/705951/106425551-e0e48f00-6418-11eb-9c8c-f36409150c01.png)
and things seem OK.

**Comment by mikhailredis** [comment]
@ryantxu There is nothing in the Console. I tried both master and 7.4.0-beta1 Docker builds.

**Comment by torkelo** [comment]
Make sure the data is returned with state: LoadingState.Streaming

**Comment by mikhailredis** [comment]
@ryantxu @torkelo Thank you, `LoadingState.Streaming` was missing.
