### ISSUE TITLE
Docs feedback: /permissions/_index.md

### ISSUE THREAD

**Issue by adr31** [grafana/grafana#30765]
Install grafana

**Comment by adr31** [comment]
Install grafana

**Comment by ivanahuckova** [comment]
Hello @adr31, if you would like to create issue, please follow one of the templates here - https://github.com/grafana/grafana/issues/new/choose. This issue unfortunately doesn't have enough information, so I am going to close it for now. Please feel free to reopen if you add all necessary information.
