### ISSUE TITLE
Table: JSON Tooltip positioned issues 

### ISSUE THREAD

**Issue by Northbadge** [grafana/grafana#30761]
**What happened**: The json tooltip is positioned off to the right, it cannot be accessed (unless you flick your cursor over quick enough)
![image](https://user-images.githubusercontent.com/17266534/106352045-0d19e600-631b-11eb-85a4-60df2546692a.png)

**What you expected to happen**: Tooltip edge to be near the cursor, or maybe on the cell's edge

**How to reproduce it (as minimally and precisely as possible)**: Get a really really long json, and try to display it in table view. [Here's the one I used](https://pastebin.com/2ZAQHgd7)

**Anything else we need to know?**: 

**Environment**:
Grafana version: 7.3.7
Data source type & version: postgresql 12
OS Grafana is installed on: Ubuntu 20.04 LTS
User OS & Browser: Windows 10 19042.746 / Chrome 87.0.4280.141
Grafana plugins: The defaults
Others:

**Comment by M0rdecay** [comment]
one more case:
JSON display mode works incorrectly, when height of the displayed block is greater than height of the window:
![2021-03-20 20-08-44](https://user-images.githubusercontent.com/50422107/111879971-d6c32380-89b9-11eb-9683-4d84af017762.gif)

**Anything else we need to know?**:
Reproduced in Google Chrome, but works fine in Firefox

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: Elasticsearch
- OS Grafana is installed on: docker
- User OS & Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit) on Windows 10

**Comment by Northbadge** [comment]
> one more case:
> JSON display mode works incorrectly, when height of the displayed block is greater than height of the window:
> ![2021-03-20 20-08-44](https://user-images.githubusercontent.com/50422107/111879971-d6c32380-89b9-11eb-9683-4d84af017762.gif)
> 
> **Anything else we need to know?**:
> Reproduced in Google Chrome, but works fine in Firefox
> 
> **Environment**:
> 
> * Grafana version: 7.4.5
> * Data source type & version: Elasticsearch
> * OS Grafana is installed on: docker
> * User OS & Browser: Google Chrome Version 89.0.4389.90 (Official Build) (64-bit) on Windows 10

That looks more like #30727

**Comment by M0rdecay** [comment]
> That looks more like #30727

Hmm, you`re right
@torkelo should i move my case to #30727?
