### ISSUE TITLE
Pass template variable in API query

### ISSUE THREAD

**Issue by hobbsh** [grafana/grafana#3076]
Hi,

I generate most of our graphs dynamically based on host names with the template variable changing based on the host's location. It would be great it template variables in general could be passed in a query string via the API to grab dynamic dashboards. Is this at all possible?

**Comment by torkelo** [comment]
You can  set variables via URL,  is that what you asking?

**Comment by hobbsh** [comment]
I might be misunderstanding what the API is capable of. I was assuming I could retrieve a snapshot via the API based on template variables available to that dashboard - so it would mean passing a variable like "location" to a dashboard so it can return the correct templated dashboard. 

Is this or possibly something like snapshot generation via the API something on the Grafana roadmap?

**Comment by hobbsh** [comment]
What I was after is the render API and this is possible to pass the template variable in the query string (var-"variable"). 
```
http://localhost:3000/render/dashboard-solo/db/facility-overview?panelId=7&fullscreen&width=1000&height=500&var-location=dc1
```
Sorry for the confusion.

**Comment by 3naziya** [comment]
Hi ,
Can I pass variable in the snapshot queries to fetch dashboard data dynamically
