### ISSUE TITLE
(question): Why did You delete gitlab-datasource project ?

### ISSUE THREAD

**Issue by lukasmrtvy** [grafana/grafana#30774]
Hello, why did You delete gitlab-datasource project ? ( http://github.com/grafana/gitlab-datasource )
Thanks

**Comment by torkelo** [comment]
It is not deleted, it's a private repo (Grafana Enterprise plugin)

**Comment by lukasmrtvy** [comment]
@torkelo but it was opensourced.., isnt ? That project was public for sure..

**Comment by lukasmrtvy** [comment]
FYI
Is possible to use meltano ( opensource, by gitlab, https://meltano.com/plugins/extractors/gitlab.html, https://meltano.com/plugins/loaders/postgres.html and https://grafana.com/docs/grafana/latest/datasources/postgres/, You will get even more info from Gitlab API and more flexible query.
