### ISSUE TITLE
Feature request: Make LDAP group membership searchable by UID or other field

### ISSUE THREAD

**Issue by swissdave** [grafana/grafana#3078]
Our LDAP directory uses UIDs to uniquely identify users as well as manage group memberships. These UIDs however are generally not known to the end users, who instead user login IDs which are mapped to their "cn". The LDAP also works in a POSIX like manner to represent group membership. Currently Grafana LDAP uses the "username" as entered by the user to search for group memberships (when a POSIX system is used). The change would be to configure a value from the returned LDAP user to do this, e.g.

```
## %s here is replaced by the value of the "uid" returned below. This could be configured to be the "cn" as today or anything else
group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
## An array of the base DNs to search through for groups. Typically uses ou=groups
group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "cn"
email =  "email"
uid = "guid" ##### New field
```

The code in question is below, where username is passed all the way through from the entry screen:

```
filter := strings.Replace(a.server.GroupSearchFilter, "%s", username, -1)
```

**Comment by swissdave** [comment]
Any chance of getting this pull request merged to solve this? https://github.com/grafana/grafana/pull/3135

**Comment by swissdave** [comment]
Hi, what needs to be done to get this merged?  we can't use the LDAP features in our organisation without it.

**Comment by aparcar** [comment]
Any news?

**Comment by cubranic** [comment]
This works for me in v5. Our LDAP server uses, AFAIK, a pretty standard POSIX schema. I uncommented `group_search_filter` as @swissdave did above, but I also changed `username` in `[servers.attributes]` from `cn` to `uid`.
