### ISSUE TITLE
Interval Variable is not submit to API anmyore

### ISSUE THREAD

**Issue by KrisztianKaszas** [grafana/grafana#30785]
**What you expected to happen**: Interval variable and its selected value is submit to API via scopedVars

**How to reproduce it (as minimally and precisely as possible)**:
Add simpod-json-datasource as datasource.
Add a new Dashboard
Add a new Variable with Type "Interval" to the dashboard, you may use the default list that is beeing provided.
Save
Refresh Dashboard
Capture API data via Fiddler.
Note that the variable is not present in scopedVariables anymore.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: simpod-json-datasource 0.2.3
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 and Chrome
- Grafana plugins:
- Others: In Grafana 6.4.4 with simpod-json-datasource 0.1.8 this feature worked.

Behavior 6.4.4 vs. 7.3.7 and Workaround:
![Grafana_Interval_Variable](https://user-images.githubusercontent.com/48984814/106461630-52622300-6495-11eb-956c-df15efa92673.gif)

**Comment by torkelo** [comment]
you will have to open an issue with this data source plugin , https://github.com/simPod/GrafanaJsonDatasource 

I do not think Grafana has changed any behaviors here
