### ISSUE TITLE
Variable is escaped in a wrong way using Multi-value and/or Include All option

### ISSUE THREAD

**Issue by juergenthomann** [grafana/grafana#30782]
**What happened**:
I tried to create a dashboard with a variable that contains URLs like http://www.example.com/status. When using this variable to create a template panel with Repeat Options no data is shown. The Panel works without problems, when Multi-value and Include All Option is disabled.

Query (in Panel): sum(probe_http_duration_seconds{target="$site"})
URL in Query Inspector: api/datasources/proxy/1/api/v1/query_range?query=sum(probe_http_duration_seconds%7Btarget%3D%22http%3A%2F%2Fwww%5C%5C.example%5C%5C.com%2Fstatus%22%7D)&start=1611573600&end=1612178400&step=600"

I guess that the dots are escaped even if they shouldn't be.

**What you expected to happen**:
Panels should show the data. The Query is not wrong, it just shows no data

**How to reproduce it (as minimally and precisely as possible)**:
- Create dashboard with a variable that contains URLs with dots, Multi-Value and Include All option selected
- Use variable in query
- I used repeat-options, but it seems that is even without broken. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7 and 7.4.0-beta1
- Data source type & version: Prometheus 2.24.1
- OS Grafana is installed on: Docker container (without Ubuntu in Tag)
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by juergenthomann** [comment]
When I replace target="$site" with target=~"$site" it works, so there is a workaround. So I would guess that the variable is escaped for regex even if I don't use a regex query

**Comment by torkelo** [comment]
when Multi-value and Include All Option are enabled Grafana will default to regex escaping the value to support multi-value formatting, you can disable this using for example `${site:raw}`
