### ISSUE TITLE
Time Series panel "all" tooltip stickyness

### ISSUE THREAD

**Issue by kristjansb** [grafana/grafana#30798]
Have been experimenting with the new time series panel and very happy with the new features. Realizing work is still underway to reach feature parity with the original Graph panel, wanted to share an observation before 7.4.0-stable.

**What happened**: The "all series" tooltip behavior in the new GraphNG Time Series panel doesn't quite match the original Graph panel. Using multiple series with sparse timestamps, the "all series" tooltip in the Time Series panel only shows values for the current instant. Cursor positioning is also a little more sensitive compared to value read outs in the Graph panel.

**What you expected to happen**: Using multiple series with sparse timestamps, the "all series" tooltip used to always show the last/current value in the tooltip pop-up.

**How to reproduce it (as minimally and precisely as possible)**: Using the TestData DB data source, add two queries, the first using the random walk scenario with two series, and the second using the CSV Metric Values with default input. Use the Time series panel type and set Tooltip mode to "All". Compare tooltip behavior with original Graph panel.
![image](https://user-images.githubusercontent.com/7348565/106497703-62293980-648c-11eb-8532-3530e38321a1.png)
![image](https://user-images.githubusercontent.com/7348565/106498213-1034e380-648d-11eb-8b66-8a458c8ebd7a.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0-beta1
- Data source type & version: TestData DB
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome on Windows 10
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
>  Using multiple series with sparse timestamps, the "all series" tooltip used to always show the last/current value in the tooltip pop-up.

Yes, but this was sort of a bug that MANY complained about. So I think the current behavior of only showing values for data points the time range you hover over is better

**Comment by torkelo** [comment]
So think we will keep this new behavior, see if there is many that want the old behavior we can reconsider

**Comment by kristjansb** [comment]
> So think we will keep this new behavior, see if there is many that want the old behavior we can reconsider

Makes sense. Personally I rely on the `last` value in the tooltip quite often for panels from a MySQL data source with multiple series and sparse timestamps. Can use $__timeGroup() to normalize timestamps if this is the new behavior.

It might be nice to be able to toggle the tooltip value behavior between instant & last to allow migrating to the new panel while supporting existing use cases. I especially like the soft min/max and support for more reducers in the legend component.

I might open a new issue / feature request after 7.4.0-stable, or just continue using the Graph panel where the feature is being relied upon.
