### ISSUE TITLE
Suggestion: Darker background-color on tooltip (light theme)

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3079]
Hi!

Just upgraded to new Grafana version 2.5. I'm using light theme and just realized that the tooltip background-color changed from "grey" to "white". Actually I liked the older tooltip style, but I agree that is better to have a non-contrast theme based (the really important are the graphs).

The fact is that the color is so similar than graph BG color, so it's quite hard to differentiate.

![image](https://cloud.githubusercontent.com/assets/13196237/10815061/eccdae58-7e29-11e5-8220-287907f8e4e7.png)

Would be awesome if the background - color is a bit darker!

Thanks for all!

**Comment by torkelo** [comment]
thanks for reporting this, fixed! 

![image](https://cloud.githubusercontent.com/assets/10999/10817323/5051aca4-7e39-11e5-9622-496917d20aa4.png)

**Comment by monestri** [comment]
Can't say I'm a fan of this change. The change from dark text to light text for just the tooltip is not consistent with the rest of the theme.

**Comment by bulletfactory** [comment]
Agreed. The problem we were running into was the tooltip bg was so similar to the graph bg that it blended in too much. 

I think this is worth revisiting to make consistent for the theme. This can be assigned to me.
