### ISSUE TITLE
Plugin install fails in Dockerized Grafana when using custom URL + Docker Compose

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#30793]
**What happened**:
When starting Grafana Docker container with Docker Compose, Grafana may fail to start, and throws an error like:

```
Error: ✗ failed to download plugin archive: Failed to send request: parse " https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip": first path segment in URL cannot contain colon
```

This happens under these circumstances:

- installing more than one plugin
- one of the plugins is installed via URL, like `https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip;vonage-status-panel"`
- using Docker Compose to pass options (via YAML file) and start the container

**What you expected to happen**:
Grafana starts up without errors.

**Cause:**
It turns out the problem is caused because Docker Compose parses the list of plugins, and forms a comma-delimited list **_with a space after each comma_**.

That space before the URL causes Grafana to throw an error like:

```
Failed to send request: parse " https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip": first path segment in URL cannot contain colon
```

**How to reproduce it (as minimally and precisely as possible)**:
I can reproduce the error easily with this docker run command, where I have inserted a space after the comma and before the plugin URL:

```
docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource, https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip;vonage-status-panel"  grafana/grafana
```

Results in this log from the Docker container:

```
installing grafana-clock-panel @ 1.1.1
from: https://grafana.com/api/plugins/grafana-clock-panel/versions/1.1.1/download
into: /var/lib/grafana/plugins
✔ Installed grafana-clock-panel successfully
Restart grafana after installing plugins . <service grafana-server restart>
installing grafana-simple-json-datasource @ 1.4.1
from: https://grafana.com/api/plugins/grafana-simple-json-datasource/versions/1.4.1/download
into: /var/lib/grafana/plugins
✔ Installed grafana-simple-json-datasource successfully
Restart grafana after installing plugins . <service grafana-server restart>
installing vonage-status-panel @
from: https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip
into: /var/lib/grafana/plugins
Error: ✗ failed to download plugin archive: Failed to send request: parse " https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip": first path segment in URL cannot contain colon
```

**Anything else we need to know?**:

Example of Docker Compose YAML that causes this error:
![image](https://user-images.githubusercontent.com/10763196/106477391-1d92a380-6476-11eb-8bbf-d82277c098b6.png)

**Environment**:
- Grafana version: 7.3.7 Enterprise (Docker image)
- Grafana plugins: any plugin installed via URL, like `https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip;vonage-status-panel"`

**Comment by papagian** [comment]
instead of:
`docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource, https://github.com/Vonage/Grafana_Status_panel/archive/v1.0.10.zip;vonage-status-panel"  grafana/grafana
`
the valid command is:
`docker run -d -p 3000:3000 --name=grafana -e "GF_INSTALL_PLUGINS=grafana-clock-panel,grafana-simple-json-datasource,vonage-status-panel"  grafana/grafana`

**Comment by jdejesus517** [comment]
This is still an issue for enterprise customers who develop and maintain their own plugin repositories internally.

**Comment by ethirolle** [comment]
@papagian, re-opening this issue because it refers specifically to an issue that happens with Docker Compose. When using `docker-compose` command, user is not constructing & sending the `docker run` commands, compose is taking care of this. So I don't think your earlier comment closes this issue. Thanks!!

**Comment by wbrowne** [comment]
@ethirolle Can you see if you can reproduce from version 8?

**Comment by wbrowne** [comment]
Here's the fix that went into v8 https://github.com/grafana/grafana/pull/32506

**Comment by ethirolle** [comment]
Confirmed that issue no longer occurs on Grafana 8.1.1, so I think we are good to close this issue.
