### ISSUE TITLE
Feature Request: CloudWatch: Support multiple AWS Credentials

### ISSUE THREAD

**Issue by b3cft** [grafana/grafana#3080]
Hi, we operate multiple AWS accounts but only one Grafana cluster for all environments.

Would be even more fantastic if the the AWS credentials files could be enumerated to allow multiple credentials to be chosen when creating a source... e.g.
```
[mgmt]
aws_access_key_id = mgmt-id
aws_secret_access_key = mgmt-secret
region = eu-west-1

[dev]
aws_access_key_id = dev-id
aws_secret_access_key = dev-secret
region = eu-west-1

[preprod]
aws_access_key_id = preprod-id
aws_secret_access_key = preprod-secret
region = eu-west-1

[prod]
aws_access_key_id = prod-id
aws_secret_access_key = prod-secret
region = eu-west-1
```

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/10816354/8dda7364-7e32-11e5-8064-43c39b7c6668.png)


Implemented and merged to master via #3053

:)

**Comment by b3cft** [comment]
Thanks very much :-)

**Comment by hartfordfive** [comment]
@b3cft How did you setup the permissions in IAM for Grafana to be able to access CloudWatch metrics for your multiple accounts?

**Comment by b3cft** [comment]
In each account I'm monitoring, I have created an AWS user and used the AWS Provided Policy `CloudWatchReadOnlyAccess`. Then added each Access Key, and Secret Key into credentials file as above.
