### ISSUE TITLE
Time Overrides vs shared panel queries

### ISSUE THREAD

**Issue by dannygoulder** [grafana/grafana#30807]
**What happened**:
I added a shared panel query to a SingleStat panel (source panel was a Graph panel).  After configuring a relative time override on the SingleStat panel (there is none on the Graph panel), one of two things happens:
1. The singlestat panel uses the dashboard time range instead of the override
2. The override applies instead to both panels (you can trigger this by viewing the SingleStat panel in full-screen and refreshing the dashboard - after returning to the dashboard the time override is apparent on the graph panel until the next refresh)

**What you expected to happen**:
I expected the time override to apply only to the singlestat panel and leave the source panel without an override.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel with a data source (the graph panel is a good illustration).  Create a second panel using the first as a dashboard/shared data source, and configure a time override on the second panel.  Observe that the time override is tied to the data source instead of the panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7 (also verified on play.grafana.org)
- Data source type & version: tested with influxdb and graphite datasources, assume it applies to any
- OS Grafana is installed on: RHEL7, whatever play.grafana.org is using
- User OS & Browser: Microsoft Edge Chromium, Win10
- Grafana plugins: none applicable
- Others:

**Comment by hugohaggmark** [comment]
Not sure how that would work, the time shift is connected to/tied to the query, or am I wrong about this @torkelo?

**Comment by torkelo** [comment]
This use case is not supported, if you share query results from another panel you will use its time range
