### ISSUE TITLE
Feature Request: Align right-hand edges of all graphs in dashboard regardless of which have right-hand Y axes.

### ISSUE THREAD

**Issue by alphatron** [grafana/grafana#3081]
If you have graphs where some have right-hand axes and some do not, or the axes have different units, the right-hand side of the data in the graphs do not correctly align. This makes it hard to line up events happening in real-time, especially when the graphs have smaller widths.
It would therefore be useful for all the graphs to have their data areas set to the smallest area so that they are correctly aligned.

[Version identified in: Version: 2.1.3, Commit: v2.1.3, Build date: 2015-08-24 09:02:44 +0100 BST]

**Comment by torkelo** [comment]
you can enable shared cross hair in dashboard setting if you want to make it easier to compare times between graphs.

**Comment by torkelo** [comment]
sorry, for closing this, but its really complicated to implement, and will likely slow down dashboard rendering due to second pass measuring width of graphs and elements (something that is really slow)

**Comment by alphatron** [comment]
No probs - something to think about when you can't get to sleep ;)
Good tip about the cross-hair, I didn't notice that - thanks.
Also - great product - I love it.
