### ISSUE TITLE
Can not disable user via API

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#30828]
**What happened**:
Can not disable user via API
```
echo -ne "user:password" | base64 --wrap 0

curl -X PUT -H "Authorization: Basic <base64 pass and user>" 'https://localhost:3000/api/users/101' -H "Content-Type: application/json" -k -s -d '{"name": "test","isDisabled": false}' | jq .
{
  "message": "Validation error, need to specify either username or email"
}

curl -X PUT -u user:password 'https://localhost:3000/api/users/101' -H "Content-Type: application/json" -k -s -d '{"name": "test","isDisabled": false}' | jq .
{
  "message": "Validation error, need to specify either username or email"
}
```
With token (this didn`t work but onlly for info)
```
curl -X PUT -H "Authorization: Bearer <token>" 'https://localhost:3000/api/users/101' -H "Content-Type: application/json" -k -s -d '{"name": "test","isDisabled": false}' | jq .
{
  "message": "Permission denied"
}
```

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: PGSql 12
- OS Grafana is installed on: OEL 7
- Grafana plugins: zabbix-grafana

**Comment by papagian** [comment]
> **What happened**:
> Can not disable user via API
> 
> ```
> echo -ne "user:password" | base64 --wrap 0
> 
> curl -X PUT -H "Authorization: Basic <base64 pass and user>" 'https://localhost:3000/api/users/101' -H "Content-Type: application/json" -k -s -d '{"name": "test","isDisabled": false}' | jq .
> {
>   "message": "Validation error, need to specify either username or email"
> }
> 
> curl -X PUT -u user:password 'https://localhost:3000/api/users/101' -H "Content-Type: application/json" -k -s -d '{"name": "test","isDisabled": false}' | jq .
> {
>   "message": "Validation error, need to specify either username or email"
> }
> ```

The error message is misleading; `login` or `email` is expected. So for updating a user one can use:
```
curl -X PUT -u user:password 'http://localhost:3000/api/users/2' -H "Content-Type: application/json"  -d '{"login": "example" ,"name": "ABC"}' | jq .
```
However, changing the disabled status of the user is not currently supported.




> With token (this didn`t work but onlly for info)
> 
> ```
> curl -X PUT -H "Authorization: Bearer <token>" 'https://localhost:3000/api/users/101' -H "Content-Type: application/json" -k -s -d '{"name": "test","isDisabled": false}' | jq .
> {
>   "message": "Permission denied"
> }
> ```

There is a distinction between server administrators and organisation administrators.
Only server admins can perform this operation. But the api tokens (with admin role) are generated as organisation administrators.
There is [a feature request](https://github.com/grafana/grafana/issues/16424) for creating user level api keys
