### ISSUE TITLE
Row not collapsing in 2.5

### ISSUE THREAD

**Issue by xneo64** [grafana/grafana#3082]
With new 2.5 release I'm unable to collapse the rows by clicking on their respective title bar. "Collapse now" from the side menu still works though. 

If the row is collapsed, clicking the name will expand it as expected. 

IIRC the 2.5-pre1 version didn't have this behaviour/bug?

**Comment by torkelo** [comment]
already fixed, and already reported twice :)

a simple search on the word `collapse` would have shown these issues at the top :) 
https://github.com/grafana/grafana/issues/3065
https://github.com/grafana/grafana/issues/3074

**Comment by xneo64** [comment]
sorry, pebkac!
