### ISSUE TITLE
Configurable mouse hint digits

### ISSUE THREAD

**Issue by Superberti** [grafana/grafana#30830]
**What would you like to be added**:
Hi, maybe it's possible that this is already configurable and I haven't found it right yet:
It would be nice, if I would be able to configure the number of digits in the mouse hint over the diagram. Or the hint value should have the same number of digits as the left/right axis.
![grafana_hint_digits](https://user-images.githubusercontent.com/16542302/106617037-83faed00-656e-11eb-8a76-38e1b5cf3114.png)

**Why is this needed**:
Right now the hint is not very helpful as the value seems to be rounded up to the next integer value. So the diagram may be much more precise than the hint.

**Comment by torkelo** [comment]
Set the decimals option under Legend section, it controls the tooltip 

The auto decimals should be improved in v7.4
