### ISSUE TITLE
Datasource provisioning Issue.

### ISSUE THREAD

**Issue by greenrose12** [grafana/grafana#30838]
**What happened**:

When I'm provisioning a datasource via a config file I get the following when trying to create a dashboard using that datasource:

<img width="1265" alt="Screenshot 2021-02-02 at 16 12 52" src="https://user-images.githubusercontent.com/78417853/106628885-28326300-6572-11eb-87d2-3cef09d918c2.png">

Then when I save and test the datasource:

<img width="1002" alt="Screenshot 2021-02-02 at 16 13 58" src="https://user-images.githubusercontent.com/78417853/106628984-41d3aa80-6572-11eb-8225-4a29295f0b20.png">

I am then able to use it to create a dashboard:

<img width="1267" alt="Screenshot 2021-02-02 at 16 13 30" src="https://user-images.githubusercontent.com/78417853/106629052-56b03e00-6572-11eb-910c-f23199c4488e.png">

**What you expected to happen**:

I would expect that if I set up a datasource by using the datasource provisioning method, it would be ready for me to start creating dashboards without the need to save and test the datasource.

**How to reproduce it (as minimally and precisely as possible)**:

create an Elasticsearch datasource via config and try to use it, to create a dashboard without saving and testing it.

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: Elasticsearch Version 7.0
- OS Grafana is installed on: Docker for Mac
- User OS & Browser: MacOS Mojave 10.14.6 and Chrome
- Grafana plugins: none
- Others: n/a

**Comment by papagian** [comment]
@greenrose12
thank you for reporting this.
Can you share the provisioning yaml config?

**Comment by marefr** [comment]
Feels like a user configuration error. What documentation have you followed? This one https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#configure-the-data-source-with-provisioning? We'll consider reopen when you provide us with config files and more details.
