### ISSUE TITLE
Explore: Wrong results shown when closing a split pane

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#30834]
Seems like sometimes if you close a pane data from the closed pane is still shown. Probably only happens on some error condition when there is no previous result for the pane that is left open.

Error in the tempo pane:
![image (1)](https://user-images.githubusercontent.com/1014802/106623353-d17a5880-6574-11eb-872f-bae8bf548f00.png)

Closing the loki pane but logs are still visible.
![image](https://user-images.githubusercontent.com/1014802/106623375-d63f0c80-6574-11eb-9df8-2c258d30a3d6.png)

Would wait for https://github.com/grafana/grafana/pull/29173 as that may fix this.

**Comment by gelicia** [comment]
Cannot repro, assuming this was fixed by the linked ticket. Closing.
