### ISSUE TITLE
Render to PNG issue with nginx proxying

### ISSUE THREAD

**Issue by tomasv** [grafana/grafana#3083]
Hey guys!

First of all, great tool! Big thank you for it! :+1: 

I ran into this small issue though.
In my setup there's `nginx` forwarding to `grafana` like this:
```
...
  location /grafana {
    rewrite ^/grafana(/.*)$ $1 break;
    proxy_pass http://localhost:3000;
  }
...
```

Grafana `root_url` is specified as:
```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
```

The setup is: externally the URL is `https://mydomain/grafana` which forwards to `localhost:3000`.

Everything works, except for PNG graph rendering.
Logs show this:
```
2015/10/29 12:03:02 [I] PhantomRenderer::renderToPng url http://localhost:3000/grafana/dashboard-solo/db/XXX?panelId=1&fullscreen&from=1446116580862&to=1446120180862&width=1000&height=500
2015/10/29 12:03:02 [I] Completed /grafana/dashboard-solo/db/XXX 404 Not Found in 1.505715ms
2015/10/29 12:03:02 [I] Completed /grafana/css/grafana.dark.min.4adfdad8.css 404 Not Found in 1.241804ms
2015/10/29 12:03:02 [I] Completed /grafana/app/app.bd986dd5.js 404 Not Found in 1.169132ms
```

The issue is that `/grafana` at the start of those urls must not be there for it to work.

I'm a bit stumped at this point. Not sure if it is a bug or something is misconfigured on my part, because
everything except for PNG rendering works.
Is forwarding done incorrectly in nginx? Should `root_url` not have `/grafana` at the end in my case? Or is it a bug? :smile: 

I'm running Grafana 2.1.3.

**Comment by torkelo** [comment]
Try 

```
 location /grafana {
    proxy_pass http://localhost:3000/;
  }
```

Notice the trailing slash!  Then root_url in grafana should be the public url you see in the browser
for example
```
root_url = http://nginx/grafana
```

where nginx is the host and port use use in the browser when accessing grafana

**Comment by tomasv** [comment]
@torkelo seems you were (almost) right.
Though unfortunately it's still not quite right:
```
2015/10/29 14:07:47 [I] Completed //css/grafana.dark.min.4adfdad8.css 404 Not Found in 2.148664ms
2015/10/29 14:07:47 [I] Completed //app/app.bd986dd5.js 404 Not Found in 2.028738ms
```

That extra `/` messes it up and now nothing renders properly at all. :smile: 

Changed nginx to:
```
location /grafana {
    proxy_pass http://localhost:3000/;
}
```

root_url:
```
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana
```

**Comment by torkelo** [comment]
that does not look right, root_url should be the url you see in the browser ! not the internal grafana-server port

**Comment by tomasv** [comment]
@torkelo I tried with `root_url = http://localhost:8080/grafana` as well, same thing. `8080` is where nginx is.

**Comment by torkelo** [comment]
try this

```nginx
location /grafana/ {
    proxy_pass http://localhost:3000/;
}
```

and 
```
root_url = http://localhost:8080/grafana
```
That works for me

**Comment by tomasv** [comment]
Amazing, it works now! :clap: 
Thanks for helping. :smile: 

Now everything works, logs are clean, but I'm seeing completely white PNGs, but that's another issue. :smile:

**Comment by torkelo** [comment]
depending on your OS / version you need to install font libs for phantomjs, for debian is `sudo apt-get install -y libfontconfig`

**Comment by torkelo** [comment]
or white that is strange, not sure what could cause that

**Comment by tomasv** [comment]
I took the url from logs:
```
2015/10/29 14:34:08 [I] PhantomRenderer::renderToPng url http://localhost:8080/grafana/dashboard-solo/db/feed-stats?panelId=1&fullscreen&from=1446107646921&to=1446129246921&var-country=cz&width=1000&height=500
```

Opened it, and the graph does render well, but I noticed that it does return 404:
<img width="834" alt="screen shot 2015-10-29 at 16 40 02" src="https://cloud.githubusercontent.com/assets/206971/10821566/c03cfe16-7e5b-11e5-8735-9feb9c171750.png">

Could it be that `phantomjs` does not handle that well? (I'm guessing here, still checking the font avenue right now :smile:)

**Comment by torkelo** [comment]
no, that is not it. the 404 is just a wrong status code for /dashboard-solo route ,

**Comment by tomasv** [comment]
@torkelo I managed to get everything working.

I was running everything in Vagrant, forwarding 8080 to 80th port inside a VM running nginx.
Once I switched `root_url` to what nginx was actually listening on it all started to work. :smile: 

Thanks a lot for the help! :bow:

**Comment by kierangirvan** [comment]
I'm having the same issue - I've using Apache to forward requests from port 80 onto grafana i.e.
