### ISSUE TITLE
the loki cheat sheet in "Explore" view has a bad link in it. 

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#30836]
In explore view, when you select a Loki Datasource, it displays a cheat sheet. 

On that cheat sheet there is a link to a LogQL docs page 
![image](https://user-images.githubusercontent.com/8004654/106625750-dfc57600-656e-11eb-80a0-467db4075557.png)
 
This link is incorrect, and shows a 404 error. 
https://github.com/grafana/loki/blob/master/docs/logql.md#filter-expression 

**Environment**:
- Grafana version:  7.x 
- Data source type & version: loki 
- OS Grafana is installed on: n/a
- User OS & Browser: n/a 
- Grafana plugins: n/a 
- Others:

**Comment by zoltanbedi** [comment]
Hi @simonc6372,
I can see this working in adminops and in master as well, pointing to the right url so I'm going to close this now.

**Comment by kasimon** [comment]
For the record, this should have been solved by #29037, although I'm not sure in which release the fix actually shipped.

**Comment by zoltanbedi** [comment]
You are right, thanks @kasimon it is released as part of 7.4.0
