### ISSUE TITLE
Retro LCD mode improvement

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#30841]
Hello!
We have a panel with battery state. But the emergency interval is always highlighted when the battery is OK
![Screenshot_2](https://user-images.githubusercontent.com/43705385/106641393-34c9b200-6598-11eb-900c-dde5d73b0a3b.png)

Would like to see something like this
![Screenshot_2](https://user-images.githubusercontent.com/43705385/106641723-968a1c00-6598-11eb-9772-003ba6fddafc.png)

**Comment by torkelo** [comment]
This would not make sense for normal scale (where it goes from good to bad) 

This would be like an inverted mode where cells would be lit from max to current value instead of min to current value

**Comment by torkelo** [comment]
however, an inverted mode would not work for you as then it would be red on the far right as well 

So not sure how to solve your case

**Comment by pkkrusty** [comment]
What about a mode where just a single bar is highlighted and moves within the defined range, illuminating just the bar that corresponds?

**Comment by pkkrusty** [comment]
Similar to https://github.com/ASOS/grafana-bidirectional-bar-gauge-panel

**Comment by pkkrusty** [comment]
My use case is a solar installation, where my range goes from positive 15kW to negative 15kW with warning ranges on either end of that range, with a different color for positive and negative normal ranges.  So at a glance I can see where within the range the inverter currently is. Right now everything below the value is illuminated, which kind of works, but isn't ideal.

**Comment by pkkrusty** [comment]
Similar to the solution proposed and accepted for gauges with neutral point.
