### ISSUE TITLE
Grafana v7.3.7 Alert with image

### ISSUE THREAD

**Issue by Michsh** [grafana/grafana#30859]
Hi,
    I need to send chart image inside email (this worked in previous versions). This is a fresh Grafana  and i cannot send charts images inside email.

Direct link rendered image : worked
grafana-image-renderer : create image local, more see logs
my grafana notification settings
![image](https://user-images.githubusercontent.com/8654261/106732001-d55fb680-6618-11eb-87c1-dd916c97b23b.png)

mail test works ok    (see image)
![image](https://user-images.githubusercontent.com/8654261/106731658-64b89a00-6618-11eb-9698-b050059d2ad0.png)

I set in grafana.ini
allow_loading_unsigned_plugins =true
[external_image_storage]
# Used for uploading images to public servers so they can be included in slack/email messages.
# you can choose between (s3, webdav, gcs, azure_blob, local)
provider =local

and my grafana-image-renderer plugin shows like in image:
![image](https://user-images.githubusercontent.com/8654261/106732415-58810c80-6619-11eb-89cf-b5fc437f54e2.png)

**I expected **:
  To send chart image inside email

**Grafana Log**:
t=2021-02-03T11:57:42+0200 lvl=info msg="New state change" logger=alerting.resultHandler ruleId=7 newState=alerting prev state=ok
t=2021-02-03T11:57:42+0200 lvl=dbug msg="Rendering alert panel image" logger=alerting.notifier ruleId=7 urlPath="d-solo/5fCgjnggz/solar_baterie?orgId=1&panelId=85"
t=2021-02-03T11:57:42+0200 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/5fCgjnggz/solar_baterie?orgId=1&panelId=85"
t=2021-02-03T11:57:43+0200 lvl=dbug msg="Scheduler: Putting job on to exec queue" logger=alerting.scheduler name="I1: Alarme alert" id=6
t=2021-02-03T11:57:43+0200 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=6 name="I1: Alarme alert" changing state to=keep_state
t=2021-02-03T11:57:43+0200 lvl=dbug msg="Job Execution completed" logger=alerting.engine timeMs=6.159 alertId=6 name="I1: Alarme alert" firing=false attemptID=1
t=2021-02-03T11:57:44+0200 lvl=dbug msg="Rendered alert panel image" logger=alerting.notifier ruleId=7 path=/var/lib/grafana/png/GCFObTFFJ5IfHcfAtxB1.png took=2.039317408s
t=2021-02-03T11:57:44+0200 lvl=dbug msg="Uploading alert panel image to external image store" logger=alerting.notifier ruleId=7 path=/var/lib/grafana/png/GCFObTFFJ5IfHcfAtxB1.png
t=2021-02-03T11:57:44+0200 lvl=dbug msg="Uploaded alert panel image to external image store" logger=alerting.notifier ruleId=7 url=http://localhost:3000/public/img/attachments/GCFObTFFJ5IfHcfAtxB1.png took=3.482µs
t=2021-02-03T11:57:44+0200 lvl=dbug msg="Sending notification" logger=alerting.notifier type=email uid=TBTUcEYGz isDefault=true
t=2021-02-03T11:57:44+0200 lvl=info msg="Sending alert notification to" logger=alerting.notifier.email addresses="[########]" singleEmail=false

My emails are without images:
![image](https://user-images.githubusercontent.com/8654261/106731549-42bf1780-6618-11eb-8a4a-9a540eaf2f82.png)

**Environment**:
- Grafana version: Grafana v7.3.7 
- Data source type & version: InfluxDB v1.8.4 
- OS Grafana is installed on: 4.19.0-14-amd64 #1 SMP Debian 4.19.171-2 (2021-01-30) x86_64 GNU/Linux
- User OS & Browser: Firefox
- Grafana instaled plugins:
        agenty-flowcharting-panel @ 0.9.0
      blackmirror1-statusbygroup-panel @ 1.1.1
      grafana-image-renderer @ 2.0.0
      grafana-piechart-panel @ 1.6.1
      isaozler-paretochart-panel @ 0.3.1
      michaeldmoore-multistat-panel @ 1.4.1
      natel-discrete-panel @ 0.1.0

Thanks in advance

**Comment by hugohaggmark** [comment]
Possible related to #25506

**Comment by papagian** [comment]
From the [docs](https://grafana.com/docs/grafana/latest/alerting/notifications/#email):
> Be aware that if you use the local image storage email servers and clients might not be able to access the image.
Does this image is accessible from the email server?

**Comment by marefr** [comment]
Please try and change to the default then the image will be embedded in the emails.
```ini
[external_image_storage]
provider = 
```
