### ISSUE TITLE
Loki: Filtering doesn't work correctly for parsed labels

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#30856]
**What happened**:

When using Explore to view Loki Logs in JSON format, after using `| json` parser expression, it is possible to filter for parsed label values. However, the query is modified to use a stream selector, which does not work since it's a parsed label and not a loki label.

**What you expected to happen**:

Filters on parsed labels have to be added as Label Filter Expression, for this grafana explore has to know/remember which labels have been parsed.

**How to reproduce it (as minimally and precisely as possible)**:

- Setup loki to contain any JSON logs with properties
- Query any stream, my example: 
```
{Service="frontendservice"}
```
Example log message (prettified):
```json
    {
        "@t": "2021-02-03T09:32:58.2573405Z",
        "@m": "Request \"WeatherBackend\" from http://localhost:5001/",
        "@i": "e0f0659c",
        "@l": "Debug",
        "Path": "WeatherBackend",
        "ServiceAddress": "http://localhost:5001/",
        "SourceContext": "FrontendService.Controllers.WeatherFrontendController",
        "Controller": "WeatherFrontendController",
        "ActionId": "4edb6d32-0927-4bfd-b45b-fd8eebbf2f87",
        "ActionName": "FrontendService.Controllers.WeatherFrontendController.GetWeatherForecast (FrontendService)",
        "RequestId": "0HM683KDIUR1O:00000001",
        "RequestPath": "/weatherfrontend",
        "SpanId": "b5f6d53dc54a5d4c",
        "TraceId": "378b8f033df64b4a8b0d0d4c4492ae9f",
        "ParentId": "0000000000000000",
        "ConnectionId": "0HM683KDIUR1O",
        "Scope": [
            "WeatherFrontendController"
        ]
    }
```
Screenshot (notice the four actual `Log Labels`):
![grafik](https://user-images.githubusercontent.com/33002073/106727301-9ecf6f00-660b-11eb-8f4d-97b847a13789.png)

- Parse log as JSON, Query: 
```
{Service="frontendservice"} | json
```

![grafik](https://user-images.githubusercontent.com/33002073/106727843-29b06980-660c-11eb-8aec-05fbb3f33020.png)

- "Filter for value" for any of the parsed labels, e.g. `TraceId`, generated explore query: 
```
{Service="frontendservice",TraceId="378b8f033df64b4a8b0d0d4c4492ae9f"} | json
```
![grafik](https://user-images.githubusercontent.com/33002073/106729027-5e70f080-660d-11eb-926b-9f94a379948e.png)

Which obviously does not return any logs since `TraceId` is no label in loki.
Correct result would have been: 
```
{Service="frontendservice"} | json | TraceId="378b8f033df64b4a8b0d0d4c4492ae9f"
```

**Anything else we need to know?**:

Sorry if this is a dupe, didn't know what keywords to search for really.

**Environment**:
- Grafana version: `Grafana v7.3.5 (11f305f88a)`
- Data source type & version: `Loki 2.1.0`
- OS Grafana is installed on: Docker image in WSL2 on Windows 10 `20H2`
- User OS & Browser: Windows 10 `20H2`, Firefox `85.0`
- Grafana plugins: -
- Others: -

**Comment by ivanahuckova** [comment]
Hello @Mario-Hofstaetter, thanks for creating this issue. We are aware of this and we are actively working on this with Loki team https://github.com/grafana/loki/issues/3057. If you are interested, you can also check out this design doc https://docs.google.com/document/d/1DP_piybk4WBs_NWwWuMS4FRQSUK0eeAUY3pT0td7ueQ for the solutions that we are currently considering.

**Comment by ivanahuckova** [comment]
Based on the great tip from @cyriltovena - as a workaround until API is implemented - if parser is used, we can filter any label (normal or extracted) trough this syntax `{app="foo"} | json | cluster="bar" , something="something else"`. If parser is not used, then we know all labels are normal and we can use label filtering. The filtering should be added at the end of the query.
