### ISSUE TITLE
Getting "Concurrent server side render limit reached" while rendering dashboard, with no real render requests

### ISSUE THREAD

**Issue by knuzhdin** [grafana/grafana#30860]
**What happened**:
Grafana with no concurrent render requests (config limit - concurrent_render_limit = 128) after some time (usually 2-3 weeks uptime) starts to generate "render limit reached" images. I tried to kill rendering plugin process - plugin-linux-x64-glibc, but only restart of the grafana server is helping.

**How to reproduce it (as minimally and precisely as possible)**:
Unfortunately, have no idea.
I found no relevant logs (level = debug) at the time of rendering.

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: -
- OS Grafana is installed on: Ubuntu 14.04
- User OS & Browser: curl
- Grafana plugins: rendering with grafana-image-renderer=2.0.0 (https://github.com/grafana/grafana-image-renderer)

**Comment by marefr** [comment]
Probably a concurrent problem in this code https://github.com/grafana/grafana/blob/3a905847e85c2eec23d9d7f61c711949c9fbe680/pkg/services/rendering/rendering.go#L157

**Comment by knuzhdin** [comment]
This effect could be reached if render requests get stuck here:
https://github.com/grafana/grafana/blob/3a905847e85c2eec23d9d7f61c711949c9fbe680/pkg/services/rendering/rendering.go#L188
or here:
https://github.com/grafana/grafana/blob/3a905847e85c2eec23d9d7f61c711949c9fbe680/pkg/services/rendering/rendering.go#L189
at some point rs.inProgressCount > opts.ConcurrentLimit 

is there any way to check this on running grafana-server?

**Comment by knuzhdin** [comment]
@marefr 
Finally I got my hands on this issue. Adding more logging around rendering showed that the usage of regular `++` and `--` operations for `inProgressCount` resulted in this incorrect behavior (for instance, I got 4 concurrent rendering jobs finishing at the same time and decreasing `inProgressCount` variable only by 3).

Using atomic operations helped:
```
--- grafana-7.5.3/pkg/services/rendering/rendering.go	2021-04-07 13:36:01.000000000 +0300
+++ grafana-7.5.3-mod/pkg/services/rendering/rendering.go	2021-05-20 16:39:59.538585871 +0300
@@ -10,6 +10,7 @@
 	"path/filepath"
 	"strings"
 	"time"
+	"sync/atomic"
 
 	"github.com/grafana/grafana/pkg/infra/metrics"
 	"github.com/grafana/grafana/pkg/infra/remotecache"
@@ -45,7 +46,7 @@
 	pluginInfo      *plugins.RendererPlugin
 	renderAction    renderFunc
 	domain          string
-	inProgressCount int
+	inProgressCount int32
 
 	Cfg                *setting.Cfg             `inject:""`
 	RemoteCacheService *remotecache.RemoteCache `inject:""`
@@ -155,7 +156,7 @@
 }
 
 func (rs *RenderingService) render(ctx context.Context, opts Opts) (*RenderResult, error) {
-	if rs.inProgressCount > opts.ConcurrentLimit {
+	if atomic.LoadInt32(&rs.inProgressCount) > int32(opts.ConcurrentLimit) {
 		return &RenderResult{
 			FilePath: filepath.Join(setting.HomePath, "public/img/rendering_limit.png"),
 		}, nil
@@ -180,12 +181,10 @@
 	defer rs.deleteRenderKey(renderKey)
 
 	defer func() {
-		rs.inProgressCount--
-		metrics.MRenderingQueue.Set(float64(rs.inProgressCount))
+		metrics.MRenderingQueue.Set(float64(atomic.AddInt32(&rs.inProgressCount, -1)))
 	}()

-	rs.inProgressCount++
-	metrics.MRenderingQueue.Set(float64(rs.inProgressCount))
+	metrics.MRenderingQueue.Set(float64(atomic.AddInt32(&rs.inProgressCount, 1)))
 	return rs.renderAction(ctx, renderKey, opts)
 }
 
```

**Comment by marefr** [comment]
Nice. Would you be interested in opening a pull request with your fixes?

**Comment by knuzhdin** [comment]
> Nice. Would you be interested in opening a pull request with your fixes?

Sure, I tried, but got "remote: Permission to grafana/grafana.git denied to knuzhdin."

**Comment by marefr** [comment]
@knuzhdin you have to fork grafana and there you can create a branch and push it to your fork. Then open a PR here targeting your fork. Make sense?

**Comment by knuzhdin** [comment]
> @knuzhdin you have to fork grafana and there you can create a branch and push it to your fork. Then open a PR here targeting your fork. Make sense?

Yes, thanks, created this PR
