### ISSUE TITLE
Multiple tags for Related Dashboards / Links

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#30864]
**What would you like to be added**:
I posted this as a bug (https://github.com/grafana/grafana/issues/28870), but in the [forums ](https://community.grafana.com/t/multiple-tags-in-one-link/42551)they claimed this is by design. The wording on the site I personally found to be unclear.

**Why is this needed**: We sometimes have a main dashboard that links to sub-dashboards, and this doesn't work as I expected. Also doesn't make sense why the tags need to **exactly** match. Ideally an "OR" logic makes more sense.

**Comment by torkelo** [comment]
You can get or logic by adding more links with a different combination of tags, this would not be possible the other way around
