### ISSUE TITLE
Discord alert does not send when `"name"` field is empty

### ISSUE THREAD

**Issue by elsehow** [grafana/grafana#30875]
**What happened**: Discord alerts do not send when legend is set to `{{hostname}}`.

**What you expected to happen**: Discord alerts should send with the alert's `"name"` field populated with the hostname of the device.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an alert channel for Discord and configure/test it.
- Create a panel, and set the legend to `{{hostname}}`
- Create an alert on that panel. The alert will not trigger, but *will* send an OK message when the issue resolves.

**Anything else we need to know?**:
When sending the alert, the Grafana logs read:

```sh
t=2021-02-03T02:39:02+0000 lvl=info msg="Sending alert notification to" logger=alerting.notifier.discord webhook_url=[my discord webhook]
t=2021-02-03T02:39:02+0000 lvl=eror msg="Failed to send notification to Discord" logger=alerting.notifier.discord error="Webhook response status 400 Bad Request"
t=2021-02-03T02:39:02+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=4UFaaLLGz error="Webhook response status 400 Bad Request"
t=2021-02-03T02:39:02+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=4UFaaLLGz error="Webhook response status 400 Bad Request"
```

Using webhook.site to inspect the payloads, and `curl` to test payloads, I isolated the issue: Discord does not like it when the `"name"` field is blank. Consider the following payload:

```json
{
    "content": "@everyone",
    "embeds": [
      {
        "color": 14037554,
        "description": "",
        "fields": [
          {
            "inline": true,
            "name": "",
            "value": "41.752048"
          },
          {
            "inline": true,
            "name": "",
            "value": "51.155786"
          }
        ],
        "footer": {
          "icon_url": "https://grafana.com/assets/img/fav32.png",
          "text": "Grafana v7.3.7"
        },
        "title": "[Alerting] temp",
        "type": "rich",
        "url": "[my grafana url]"
      }
    ],
    "username": "Grafana"
  }
```
Discord rejects this. If you fill in the `"name"` fields, however, the alert posts correctly.

Eventually, I discovered the root problme: I used the `{{hostname}}` pattern in the panel's legend. For whatever reason, this left the `"name"` field empty.

My suggestion is twofold:
(1) The name field should never be blank in Discord, as that causes notifications to fail in a difficult-to-detect way.
(2)  `{{hostname}}` should populate the `"name"` field with the actual hostname on alert.

**Environment**:
- Grafana version:  7.3.7
- Data source type & version: PromQL (Prometheus 2.24.1)
- OS Grafana is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by papagian** [comment]
@elsehow thank you for reporting this!
I wonder whether the legend appears correctly in the panel or it's empty also there?

**Comment by papagian** [comment]
This field is set [here](https://github.com/grafana/grafana/blob/f326b79cc1ebded6a33e54ed23d82e320473620e/pkg/services/alerting/notifiers/discord.go#L92) and most probably it should be tested to make sure it's not empty.

**Comment by elsehow** [comment]
> I wonder whether the legend appears correctly in the panel or it's empty also there?

`{{hostname}}` does correctly show the hostname in the panel.
