### ISSUE TITLE
bug: incorrectly alterting altert related to notifier with invalid ID: undefined

### ISSUE THREAD

**Issue by kumavis** [grafana/grafana#30881]
**What happened**:

Viewing dashboard, see incorrectly alerting alert in an alert panel.
clicking on the alert enters the edit panel screen for that alert, and immediately brings up the following modal

> Do you want to delete notifier with invalid ID: undefined from the dashboard JSON? 

this panel with its alerts are provisioned here
https://github.com/kumavis/eth2-docker-digitalocean/blob/ac96f68945b42ab8dd5da6822e03bef5f435cfeb/config/grafana/dashboards/more_10_validators.json

![grafana-invalid-notifier](https://user-images.githubusercontent.com/1474978/106822645-6fc40680-66ba-11eb-82bc-8b2134711c0f.gif)

**What you expected to happen**:

- alerts to go to "not alerting" when parameters are within the range
- to not get an unprompted modal for notifier deletion

**How to reproduce it (as minimally and precisely as possible)**:
unsure. somehow get a notifier with undefined id

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.4 (14c494085e)
- Data source type & version: prometheus 
- OS Grafana is installed on: ubuntu
- User OS & Browser: win firefox
- Grafana plugins: none?
- Others:

**Comment by papagian** [comment]
What you get if you run:
`curl http://<user>:<password>@localhost:3000/api/alert-notifications/uid/USY-LmRGz`?
This modal appears when the dashboard JSON refers to a deleted notifier.

What do you mean by "incorrectly alerting alert"?

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
