### ISSUE TITLE
npx install of grafana-toolkit broken

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#30887]
**What happened**:
npx command for installing dependencies fails. Tried 3 different versions of grafana (7.3.6, 7.3.7, 7.4.0-beta1) and 2 different nodejs versions (14 latest stable, 15 latest)

**What you expected to happen**:
Installation of node modules

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana 7.3.6, 7.3.7, or 7.4.0-beta1 and run the npx command for initializing a plugin on a machine with no node_modules installed

**Anything else we need to know?**:
Excerpt using 7.4.0-beta1 and nodejs 15-latest:
```
node -v
v15.8.0

npm -v
7.5.1

npx @grafana/toolkit plugin:create myplugin-panel

--- clipped at ERR! ---
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! Found: react@16.14.0
npm ERR! node_modules/react
npm ERR!   peer react@">=16.3.0" from @emotion/core@10.1.1
npm ERR!   node_modules/@emotion/core
npm ERR!     @emotion/core@"^10.0.27" from @grafana/ui@7.4.0-beta.1
npm ERR!     node_modules/@grafana/ui
npm ERR!       @grafana/ui@"next" from @grafana/toolkit@7.3.7
npm ERR!       node_modules/@grafana/toolkit
npm ERR!         @grafana/toolkit@"*" from the root project
npm ERR!     @emotion/core@"^10.0.9" from @torkelo/react-select@3.0.8
npm ERR!     node_modules/@torkelo/react-select
npm ERR!       @torkelo/react-select@"3.0.8" from @grafana/ui@7.4.0-beta.1
npm ERR!       node_modules/@grafana/ui
npm ERR!         @grafana/ui@"next" from @grafana/toolkit@7.3.7
npm ERR!         node_modules/@grafana/toolkit
npm ERR!   peer react@">=16.6.0" from @grafana/slate-react@0.22.9-grafana
npm ERR!   node_modules/@grafana/slate-react
npm ERR!     @grafana/slate-react@"0.22.9-grafana" from @grafana/ui@7.4.0-beta.1
npm ERR!     node_modules/@grafana/ui
npm ERR!       @grafana/ui@"next" from @grafana/toolkit@7.3.7
npm ERR!       node_modules/@grafana/toolkit
npm ERR!         @grafana/toolkit@"*" from the root project
npm ERR!   29 more (slate-react-placeholder, slate-react, ...)
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"17.0.1" from react-dom@17.0.1
npm ERR! node_modules/react-dom
npm ERR!   react-dom@"17.0.1" from @grafana/ui@7.4.0-beta.1
npm ERR!   node_modules/@grafana/ui
npm ERR!     @grafana/ui@"next" from @grafana/toolkit@7.3.7
npm ERR!     node_modules/@grafana/toolkit
npm ERR!       @grafana/toolkit@"*" from the root project
npm ERR!   peer react-dom@">=16.6.0" from @grafana/slate-react@0.22.9-grafana
npm ERR!   node_modules/@grafana/slate-react
npm ERR!     @grafana/slate-react@"0.22.9-grafana" from @grafana/ui@7.4.0-beta.1
npm ERR!     node_modules/@grafana/ui
npm ERR!       @grafana/ui@"next" from @grafana/toolkit@7.3.7
npm ERR!       node_modules/@grafana/toolkit
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```
**Environment**:
- Grafana version: 7.3.6, 7.3.7, 7.4.0-beta1
- OS Grafana is installed on: RHEL7

**Comment by hugohaggmark** [comment]
@maemigh what type of plugin did you choose, I can't repro this with your steps? What OS are you trying this on?

```log
git npx @grafana/toolkit plugin:create myplugin-panel
? Select plugin type Panel Plugin
✔ Fetching plugin template...
? Plugin name myplugin-panel
? Organization (used as part of plugin ID) org
? Description
? Keywords (separated by comma)
? Author (Hugo Häggmark) Yes
? Your URL (i.e. organisation url)

    Your plugin details
    ---
    Name:  myplugin-panel
    ID:  org-myplugin-panel
    Description:
    Keywords:  []
    Author:  Hugo Häggmark
    Organisation:  org
    Website:

? Is that ok? Yes
✔ Saving package.json and plugin.json files
✔ Cleaning

    Congrats! You have just created Grafana Panel Plugin.

    Grafana Panel Plugin tutorial: https://grafana.com/tutorials/build-a-panel-plugin
    Learn more about Grafana Plugins at https://grafana.com/docs/grafana/latest/plugins/developing/development/

➜  git node -v
v14.15.1
➜  git npm -v
6.14.8
```

**Comment by maemigh** [comment]
@hugohaggmark I put RHEL7 in the comment, I think I need to understand how your git command ended up with things happening:

```
# git npx @grafana/toolkit plugin:create myplugin-panel
git: 'npx' is not a git command. See 'git --help'.

Did you mean this?
	init
```

**Comment by hugohaggmark** [comment]
> @hugohaggmark I put RHEL7 in the comment, I think I need to understand how your git command ended up with things happening:
> 
> ```
> # git npx @grafana/toolkit plugin:create myplugin-panel
> git: 'npx' is not a git command. See 'git --help'.
> 
> Did you mean this?
> 	init
> ```

Oh my bad. Git is the folder I'm running the commands from.

**Comment by maemigh** [comment]
@hugohaggmark What diagnostic steps would you like me to take? 
pasting the command
` npx @grafana/toolkit plugin:create myplugin-panel`
from the website doesn't work and produces the error mentioned above.

You asked what type of plugin I chose, I simply followed the instructions from https://grafana.com/tutorials/build-a-panel-plugin/#2

**Comment by hugohaggmark** [comment]
> @hugohaggmark What diagnostic steps would you like me to take?
> pasting the command
> ` npx @grafana/toolkit plugin:create myplugin-panel`
> from the website doesn't work and produces the error mentioned above.
> 
> You asked what type of plugin I chose, I simply followed the instructions from https://grafana.com/tutorials/build-a-panel-plugin/#2

Can you try the same command but on a different machine? As I mentioned, it works when I run it locally. Can you try the same Node version as I have?
```log
node -v
v14.15.1

npm -v
6.14.8
```

**Comment by dprokop** [comment]
@maemigh:
1. Can you please check if you don't have toolkit installed globally on your machine? Seems like npm tries to use v7.3.7.
2. You can also try clearing npm's cache localy.
3. What happens if you run `npx "@grafana/toolkit"@latest plugin:create myplugin-panel`?

**Comment by maemigh** [comment]
@dprokop @hugohaggmark I went back to nodejs 14 and ran into an issue that looked very similar to https://github.com/grafana/grafana/issues/28019. I was able finish the install following the advice in the last comment: running the command as a non-root user with write access to the path.

**Comment by hugohaggmark** [comment]
@maemigh I'm glad that you managed to install it. I'm going to close this issue now, but we can always reopen it later.
