### ISSUE TITLE
Pencil icon gone from Graphite metric editors

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#3089]
I upgraded my company to Grafana 2.5.0 and now one of our users misses having the pencil icon to switch the Graphite query editor between the boxes and basic text editor. He apparently clicks back and forth a lot between both ways of viewing the metric name. Any objection if I submit a PR to bring it back?

**Comment by torkelo** [comment]
sure, no objection

**Comment by utkarshcmu** [comment]
+1

**Comment by utkarshcmu** [comment]
This can be closed via #3133
