### ISSUE TITLE
[FeatureRequest] StatPanel: Outer alignment

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#30894]
**What would you like to be added**:
I thought I read statpanel was going away, but I'm not finding it in searches. Being able to do an outer align might be nice. ie: text is left aligned and value is right aligned.

**Why is this needed**:
This is with 7.4.0-beta1 bugs affecting the RAM data, but represents the idea.
<img width="124" alt="Screen Shot 2021-02-04 at 19 05 59" src="https://user-images.githubusercontent.com/4478053/106877400-0d9bed80-671c-11eb-9b83-87be40ca22db.png">

**Comment by torkelo** [comment]
Does it not do this already? 

![Screenshot from 2021-02-04 11-56-33](https://user-images.githubusercontent.com/10999/106883323-1ff83600-66e0-11eb-9ac1-8391aa0ddaa4.png)

**Comment by maemigh** [comment]
@torkelo 

It's not,

Using Safari 14.0.3, and this panel json in case I'm missing something:

```
{
  "datasource": "Prometheus",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "axisLabel": "",
        "axisPlacement": "auto",
        "drawStyle": "line",
        "fillOpacity": 0,
        "gradientMode": {
          "label": "None",
          "value": "none"
        },
        "hideFrom": {
          "graph": false,
          "legend": false,
          "tooltip": false
        },
        "lineInterpolation": "linear",
        "lineWidth": 1,
        "pointSize": 5,
        "scaleDistribution": {
          "type": "linear"
        },
        "showPoints": "auto",
        "spanNulls": false
      },
      "color": {
        "mode": "thresholds"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "rgb(255, 255, 255)",
            "value": null
          }
        ]
      },
      "mappings": []
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Total RAM"
        },
        "properties": [
          {
            "id": "unit",
            "value": "bytes"
          },
          {
            "id": "color",
            "value": {
              "fixedColor": "purple",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "CPU Count"
        },
        "properties": []
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Uptime"
        },
        "properties": [
          {
            "id": "unit",
            "value": "dtdhms"
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 4,
    "w": 2,
    "x": 0,
    "y": 4
  },
  "id": 23763571993,
  "options": {
    "reduceOptions": {
      "values": true,
      "limit": 3,
      "calcs": [
        "mean"
      ],
      "fields": ""
    },
    "orientation": "horizontal",
    "text": {
      "titleSize": 12,
      "valueSize": 12
    },
    "textMode": "value_and_name",
    "colorMode": "value",
    "graphMode": "none",
    "justifyMode": "auto"
  },
  "pluginVersion": "7.4.0-beta1",
  "targets": [
    {
      "expr": "count(count(node_cpu_seconds_total{instance=~\"${instance:raw}\"}) by (cpu))",
      "format": "time_series",
      "instant": true,
      "interval": "",
      "legendFormat": "CPU Count",
      "refId": "A"
    },
    {
      "expr": "node_memory_MemTotal_bytes{instance=~\"${instance:raw}\"}",
      "format": "time_series",
      "instant": true,
      "interval": "",
      "legendFormat": "Total RAM",
      "refId": "B"
    },
    {
      "expr": "node_time_seconds{instance=~\"${instance:raw}\"} - node_boot_time_seconds{instance=~\"${instance:raw}\"}",
      "instant": true,
      "interval": "",
      "legendFormat": "Uptime",
      "refId": "C"
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Sys Info",
  "type": "stat"
}
```

**Comment by maemigh** [comment]
@torkelo I admit I did not try resizing the panel to be larger, so it may only appear like this at smaller sizes, but I think the JSON should help replicate?

**Comment by torkelo** [comment]
<img width="345" alt="Screen Shot 2021-02-04 at 12 36 12" src="https://user-images.githubusercontent.com/10999/106887551-96e3fd80-66e5-11eb-9e49-34094e67b825.png">

https://play.grafana.org/d/-_MVnwLMz/stat-panel-issue?orgId=1&from=now-2d&to=now

Seems to work for me (we have fixed the auto decimals issue in 7.4.0 stable, releases today)

**Comment by maemigh** [comment]
@torkelo I got a chance to resize, so I don't think this quite matches what I was requesting, because if you resize your box to be one length of width shorter, then the Uptime and RAM will appear as unaligned as mine. If the value is broken into two lines, I would have wanted both to be right aligned rather than wherever they ended up. ie: from your example "730 d" being right aligned as well as "01:07:44".

I get the same thing as you when lengthening it as you did:
<img width="188" alt="Screen Shot 2021-02-04 at 20 55 00" src="https://user-images.githubusercontent.com/4478053/106889444-57d89b00-672b-11eb-95f2-0feef9f94fde.png">

**Comment by torkelo** [comment]
yea, the text needs to fit

**Comment by maemigh** [comment]
Could this be reopened? The alignment would then match what all word processors do
