### ISSUE TITLE
No Data message displayed on panel is not consistent across all the panels  

### ISSUE THREAD

**Issue by Ajinkya14feb-bmc** [grafana/grafana#30904]
**What happened**: Created a dashboard with multiple panels using different visualization provided by grafana like stat and graph. For some specific time range there was no data present in data source. while checking dashboard I could see different panel is showing "No Data" message in different font and size 

**What you expected to happen**: "No data" message should be consistent across all visualization panels 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a dashboard using multiple panels and select different different visualization.
2. Check dashboard for time range where there is no data present 

**Anything else we need to know?**: 

**Environment**:
- Grafana version: 7.3.1
- Data source type & version: Any
- OS Grafana is installed on: Any
- User OS & Browser:  Any
- Grafana plugins: Stat and Graph
- Others:

**Comment by hugohaggmark** [comment]
Hi @Ajinkya14feb-bmc and thanks for taking the time to write this, I think I'm going to close this as we just fixed this for the Table Panel and I think it would be more effective to open issues for the specific panels that you think are missing this feature.

**Comment by Ajinkya14feb-bmc** [comment]
What about the stat and graph plugin.... stat plugin shows no data message in color that we selected and graph plugin shows in black and small font compared to stat plugin

**Comment by hugohaggmark** [comment]
Sure, we can see if this feature receives more upvotes then we might consider reopening it.

**Comment by Ajinkya14feb-bmc** [comment]
What will be next step now ? will it be fixed in next version ?
