### ISSUE TITLE
Support auto grid min/max when using log scale 

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3090]
When using log scale, it seems the auto grid min/max no longer works.

Here's an example graph using the default "auto" for the axis and a linear scale:

<img width="948" alt="screen shot 2015-10-29 at 20 55 57" src="https://cloud.githubusercontent.com/assets/156867/10831808/87235660-7e7f-11e5-884d-e8b74f207e33.png">

With the lowest value around 1.6s, the Y-axis naturally starts around 1s (not 0).

Here's another one:
<img width="1253" alt="screen shot 2015-10-29 at 21 02 20" src="https://cloud.githubusercontent.com/assets/156867/10831950/5ee34272-7e80-11e5-98e7-054dcd5f8fc0.png">

But then when enabling the log scale, the graph essentially becomes unusable without some minimum value due to the long exponential onramp from 0 to 1 taking up the vast majority of the available screen space.

Log scale 2:
<img width="1258" alt="screen shot 2015-10-29 at 21 03 00" src="https://cloud.githubusercontent.com/assets/156867/10831977/88777702-7e80-11e5-9290-22c203fb0794.png">

Log scale 10:
<img width="1262" alt="screen shot 2015-10-29 at 21 03 23" src="https://cloud.githubusercontent.com/assets/156867/10831981/8b0749d4-7e80-11e5-8411-5bd161319ce3.png">

Log scale 1024:
<img width="1271" alt="screen shot 2015-10-29 at 21 03 09" src="https://cloud.githubusercontent.com/assets/156867/10831982/8b1d5990-7e80-11e5-882e-1720ca353130.png">

I'm not sure if it's possible, but it'd be nice if it would result in something like this. (I've hardcoded a grid minimum of 300ms here).
<img width="1265" alt="screen shot 2015-10-29 at 21 04 57" src="https://cloud.githubusercontent.com/assets/156867/10832028/bba97936-7e80-11e5-96cd-dbf90d37f0b0.png">

---

Part of this was previously mentioned in #2829.

**Comment by torkelo** [comment]
would be nice, 

for anyone with time to give it a try, would love help :) 
https://github.com/grafana/grafana/blob/master/public/app/panels/graph/graph.js#L390

**Comment by bigbenhur** [comment]
Hi,

I'm not familiar enough with git to push this myself, but here's the fix in graph.js for this issue:
`

        function applyLogScale(axis, data) {
          if (axis.logBase === 1) {
            return;
          }
          if (axis.min < Number.MIN_VALUE) {
            axis.min = null
          }

          var series, i;
          var max = axis.max, min = axis.min;

          for (i = 0; i < data.length; i++) {
            series = data[i];
            if (series.yaxis === axis.index) {
              if (max === null || max < series.stats.max) {
                max = series.stats.max;
              }
              if (min === null || min > series.stats.min) {
                min = series.stats.min;
              }
            }
            if (max === void 0) {
              max = Number.MAX_VALUE;
            }
            if (min === void 0) {
              min = Number.MIN_VALUE;
            }
          }

          axis.transform = function(v) { return Math.log(v) / Math.log(axis.logBase); };
          axis.inverseTransform  = function (v) { return Math.pow(axis.logBase,v); };

          min = axis.inverseTransform(Math.floor(axis.transform(min)));
          max = axis.inverseTransform(Math.ceil(axis.transform(max)));

          axis.min = axis.min !== null ? axis.min : min;
          axis.max = axis.max !== null ? axis.max : max;

          axis.ticks = [];
          var nextTick;
          for (nextTick = min; nextTick <= max; nextTick *= axis.logBase) {
            axis.ticks.push(nextTick);
          }
        }
`

I tested it locally and would be grateful if somebody could test/push this code - cheers!

PS - On a related note: The number formatting for small numbers (e.g. 0.0000123) doesn't look good to me. Maybe adding an option to force exponential notation would improve things? By (ab-)using negative decimals for this, a single line in kbn.toFixed(value, decimals) would suffice:

`if (decimals !== null && decimals < 0) return value.toExponential(-decimals);`
