### ISSUE TITLE
Time Series panel: Time labels overlap

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#30906]
**What happened**:
In certain circumstances time labels in time series panel overlap. It is caused by "too frequent labeling"
Time range is set to last 7 days. Here is how Time Series panel looks:
![image](https://user-images.githubusercontent.com/19311511/106905905-eeda2e80-66fc-11eb-8d1b-454b34475f49.png)
This is how old Graph panel looks:
![image](https://user-images.githubusercontent.com/19311511/106906117-26e17180-66fd-11eb-8005-36a18b7f18af.png)

As you can see, in this example, on time series panel time is labelled every 6 hours, whereas on graph panel time is labelled every 8 hours.

**What you expected to happen**:
It should be labelled the same as on graph panel (once every 8 hours in this example)

**How to reproduce it (as minimally and precisely as possible)**:
Create panel which takes full width of the page and then select last 7 days range. I was testing in on FullHD (1920 x 1080) monitor.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: Windows 10 Opera Gx
- Grafana plugins: -
- Others: -

**Comment by leeoniya** [comment]
for anyone who ends up working on this, this function needs to take into account the current label formatting and the visible time range:

https://github.com/grafana/grafana/blob/cbe040b8c659e9cbc8fffff39d728aa621346c81/packages/grafana-ui/src/components/uPlot/config/UPlotAxisBuilder.ts#L99-L109
