### ISSUE TITLE
Elasticsearch: add possibility to overwrite size in aggs

### ISSUE THREAD

**Issue by tle-huu** [grafana/grafana#30903]
Hi,

**What would you like to be added**:

I would like to be able to overwrite the **size** field when doing some aggs requests.

**Why is this needed**:

Currently, the size is automatically set to 0, which means that all the fields of the documents are not reachable, which makes it really hard to try and add hover / data link metadata.

Could it be possible to set the size field and pass it to the ElasticQueryBuilder?

```
[Object
request:Object
url:"api/datasources/proxy/1/_msearch?max_concurrent_shard_requests=5"
method:"POST"
data:"{
       "search_type":"query_then_fetch",
       "ignore_unavailable":true,
       "index":"profiling"} {**"size":0**,"query":{"bool":{"....
```

**Comment by Elfo404** [comment]
Hi @tle-huu thanks for contributing!

could you please describe your query and what are you trying to achieve? are you using a `date_histogram` or `histogram` bucket aggregation?

**Comment by tle-huu** [comment]
Hi @Elfo404 

We are using Grafana to monitor and catch possible regression in our programs metrics on a per commit basis. So each point on the graph corresponds to a commit.

The query is pretty straight forward, we use a max metric (since there can be only one point per data, max or average does not matter), group by Date Histogram.

The think we would like to achieve is to have the **data link** to the specific repo commit when hovering on the points in the graph. In the ElasticSearch json, there is the commit reference, but the Grafana query does not keep it since it only retrieve the metric and the timestamp, thus making it impossible to retrieve the commit reference in the data links variables.

Thanks for you reply

**Comment by aocenas** [comment]
@tle-huu can you also post the query (from Grafana) that you are trying to run and how you data looks like inside Elastic? Personally I don't think this is a problem with size, I think size is used for paging so would prevent you from seeing some data points but if I understand this issue you have multiple values per data point, one of them being commit hash and that is not accessible. I think we just assume timeseries data with single timestamp and single value a drop the rest but more info would help us reproducing this.

**Comment by aocenas** [comment]
Also did you try using annotations for this usecase? I think those are a bit better fit for what I think you are trying to achieve.
