### ISSUE TITLE
Opportunistically query for exemplars

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#30916]
**What would you like to be added**:

With 7.4, we have an option to query for exemplars in explore.  Current behaviour:
- If you turn it on with a version of Prometheus that doesn't support exemplars, the whole query fails
- If you turn it on with one that does, you sometimes see exemplars (when the query has some).

I'm suggesting we _always_ query for exemplars, and then have a toggle to show/hide exemplars when the query succeeds, and grey out the button (with an error message in the tooltip saying the request failed).

We should also persist the state of the toggle in the link.

**Why is this needed**:

So exemplars are move discoverable.

/cc @zoltanbedi @cstyan

**Comment by cstyan** [comment]
seems like a good idea to me
