### ISSUE TITLE
Grafana converts UTC time data twice when Grafana server timezone is not set to UTC

### ISSUE THREAD

**Issue by crockk** [grafana/grafana#30918]
I think I may have encountered what is possibly a bug - but I am unsure if this is intended behavior. There is a lot more context in my [community post regarding this problem](https://community.grafana.com/t/utc-to-local-time-zone-issue-mysql-data-source/42044), so I'm going to leave out some details here for sake of brevity.

**What happened**:
When time range/timezone is set to Browser ((UTC-8:00) in my case) Grafana displays data in UTC

**What you expected to happen**:
Grafana should implicitly be converting the raw data from the database from UTC to local time on application level - not applying any conversions in between (when making the queries on the server).

**How to reproduce it (as minimally and precisely as possible)**:

- Set up MySQL database with some entries in UTC, **datetime data type**
- Set Grafana and MySQL server system timezone to anything except UTC (for example PST)

**Anything else we need to know?**:
Grafana and MySQL were running for approximately two weeks prior to the issue occurring. During this time frame this issue was not present, and seemingly appeared over night. (Server was set to PST for some time before the issue appeared)

What seems to be happening was Grafana was reading the UTC time as PST (-8:00), adding 8 hours to convert it to UTC based on the system time zone, and then subtracting 8 hours before it hit the graph, resulting in a net 0 change.

My time data in MySQL is stored in datetime data type, which is time zone agnostic. It does not store time zone information. It should not be interpreted as the system's time zone, Grafana should interpret it as UTC, which it was, in my case.

Refer to the community post linked about for my queries, screenshots, and further context.

Might be a duplicate of #18120

**Environment**:
- Grafana version: v7.3.7 (1e261642f4)
- Data source type & version: MySQL Community Server 8.0.23
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Pie chart, Synthetic Monitoring
- Others:

**Comment by hugohaggmark** [comment]
Hmm not sure I follow, according to your community post you solve this issue? Anyway, you need to tell Grafana which time zone your data is from with the time zone picker. 
![image](https://user-images.githubusercontent.com/562238/106999232-1b865880-6786-11eb-8547-acd1e6f8843c.png)

Looking at the pictures on the community post you're using the time zone in the browser. It should look like this for UTC
![image](https://user-images.githubusercontent.com/562238/106999183-09a4b580-6786-11eb-8c8a-25366260b36f.png)

I'm going to close this issue for now, but if more evidence points to a bug in Grafana we'll of course reopen this.

**Comment by crockk** [comment]
I'm not sure if you understood the underlying problem - Yes, I fixed the issue, but I shouldn't have to be setting my server's time zone to UTC when it could possibly be running other applications which require the system time zone to PST. Also, I was under the impression that the time zone picker in the browser indicates which time zone you are viewing the data from, not what time zone the data is represented in. My client would not like to view the data in UTC time zone, I doubt anyone does. Additionally, selecting UTC time zone in the browser did not solve the issue, this was one of my many troubleshooting steps.
