### ISSUE TITLE
rendering fails when metric isn't zero filled

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#3092]
Seeking assistance here. We're using Druid as our datasource, and when a metric is not zero filled for an interval, let's say 60s, it appears to break the rendering of a stack line graph for any subsequent time buckets.

Here's an example:
![grafanabug](https://cloud.githubusercontent.com/assets/5559459/10834184/853256c4-7e54-11e5-8216-1aa793d4483e.gif)

In the above example, I am disabling the metric that stopped reporting at 09:02, and then re-enabling it, showing that the data for the remaining metrics properly stacks. When I drill into the metric itself, you can see that data stopped reporting at 09:02, which is when the stack fails to render properly.

It seems like when Grafana encounters a metric that disappears, it crashes out, and doesn't process the remaining metrics to render the graph fully. Druid does not support fill(0) or fill(null), so the metric is not represented after 09:02.

Thoughts?

**Comment by torkelo** [comment]
this is not a bug but a requirement for the stacking to work (not ideal, would like a better stacking code), 
https://github.com/grafana/grafana/issues/2912#issuecomment-152354526
