### ISSUE TITLE
Metric color picker for right-aligned legend breaks legend layout

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3093]
When opening the color picker for a metric in a right-align legend, all other rows (and the legend icon of the current row) suddenly move to the left. Thus overlapping the graph.

The current legend row oddly remains in the correct place, however.

<img width="556" alt="screen shot 2015-10-30 at 07 27 42" src="https://cloud.githubusercontent.com/assets/156867/10840514/ee90cfaa-7ed7-11e5-9cbc-8fc2092cda51.png">
<img width="565" alt="screen shot 2015-10-30 at 07 27 53" src="https://cloud.githubusercontent.com/assets/156867/10840515/eea506a0-7ed7-11e5-8c56-4f6c92250a47.png">

This can be observed at <https://grafana.wikimedia.org/dashboard/db/job-queue-rate>.

<img width="513" alt="screen shot 2015-10-30 at 07 32 31" src="https://cloud.githubusercontent.com/assets/156867/10840556/6777ba64-7ed8-11e5-9d54-87d6a40424d8.png">

**Comment by torkelo** [comment]
thanks for reporting this! fixed
