### ISSUE TITLE
Config regression listening on IPv6 addresses

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#30930]
**What happened**:

After updating to 7.4, grafana listening on IPv6 addresses fail to start, with the following log messages:
```
t=2021-02-05T12:26:29+0100 lvl=eror msg="Stopped HTTPServer" logger=server reason="failed to open listener on address [[::1]]:3000: listen tcp: address [[::1]]:3000: missing port in address"
t=2021-02-05T12:26:29+0100 lvl=eror msg="A service failed" logger=server err="failed to open listener on address [[::1]]:3000: listen tcp: address [[::1]]:3000: missing port in address"
t=2021-02-05T12:26:29+0100 lvl=eror msg="Server shutdown" logger=server reason="failed to open listener on address [[::1]]:3000: listen tcp: address [[::1]]:3000: missing port in address"
failed to open listener on address [[::1]]:3000: listen tcp: address [[::1]]:3000: missing port in address
```

**What you expected to happen**:
 Grafana configs that listened on IPv6 on 7.3 continue to work on 7.4 unless otherwise noted

**How to reproduce it (as minimally and precisely as possible)**:

Use the following config under 7.3 and 7.4:
```
[server]
domain = my-domain.tld
http_addr = [::1]
http_port = 3000
protocol = http
root_url = %(protocol)s://%(domain)s:%(http_port)s/
```

After changing `[::1]` to `::1`, it works under 7.4.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4
- Data source type & version: n/a
- OS Grafana is installed on: debian
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by NotAFile** [comment]
From digging around, this seems related to: https://github.com/grafana/grafana/pull/28585

There, the comments seem to indicate the correct behavior:
https://github.com/taciomcosta/grafana/blob/ae4357e3aff03409cf3bb7d26409c80a371bd5ce/pkg/infra/network/address.go#L11-L14

However, the tests that were submitted there do not include this specific case of a leading colon with square brackets: https://github.com/taciomcosta/grafana/blob/ae4357e3aff03409cf3bb7d26409c80a371bd5ce/pkg/infra/network/address_test.go#L63-L66

**Comment by chadek** [comment]
I got the issue

**Comment by PhilippWendler** [comment]
Note for everybody wo changed the config value and removed the `[]`: this breaks the grafana-image-renderer plugin and leads to leaking processes and continually increasing memory consumption if direct image rendering is used (#31136). A workaround is setting `http_addr` to the empty value (though this will open up the Grafana port from other hosts, so be careful).

**Comment by aknuds1** [comment]
I think that fundamentally IPv6 addresses should not be enclosed in square brackets, except for when you join an address with a port (and the brackets are necessary to disambiguate the colons in the IPv6 address from the colon separating the address from the port. That's why this bug happens. You can see from [this example](https://play.golang.org/p/YjkVFI8A6s7) that `net.JoinHostPort` doesn't do well with an IPv6 address enclosed in square brackets.

I guess we can build in some tolerance though, where we strip enclosing brackets before calling `net.JoinHostPort`.
