### ISSUE TITLE
Time Series Panel: Uncaught Type Error with NaN values

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#30933]
**What happened**:
When switching from the Graph Panel to Time series panel a series with a NaN value (dataframe) there is the following error:

```
uPlot.esm.js:3291 Uncaught TypeError: Cannot read property 'map' of null
    at uPlot.esm.js:3291
    at Array.forEach (<anonymous>)
    at drawAxesGrid (uPlot.esm.js:3245)
    at uPlot.esm.js:3464
    at Array.forEach (<anonymous>)
    at _commit (uPlot.esm.js:3464)
```

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/1692624/107037017-820c7600-6788-11eb-96e5-5aa29edf0609.png)

![image](https://user-images.githubusercontent.com/1692624/107037038-8769c080-6788-11eb-9821-34143c243e29.png)

or using Load Apache arrow data with the time range matching above:

```
QVJST1cxAAD/////kAEAABAAAAAAAAoADgAMAAsABAAKAAAAFAAAAAAAAAEDAAoADAAAAAgABAAKAAAACAAAAFgAAAACAAAAKAAAAAQAAAD8/v//CAAAAAwAAAABAAAAQQAAAAUAAAByZWZJZAAAABz///8IAAAAFAAAAAgAAABBLXNlcmllcwAAAAAEAAAAbmFtZQAAAAACAAAAmAAAAAQAAACC////FAAAAGAAAABgAAAAAAADAWAAAAACAAAALAAAAAQAAAB0////CAAAABAAAAAFAAAAdmFsdWUAAAAEAAAAbmFtZQAAAACY////CAAAAAwAAAACAAAAe30AAAYAAABsYWJlbHMAAAAAAACK////AAACAAUAAAB2YWx1ZQASABgAFAATABIADAAAAAgABAASAAAAFAAAAEQAAABMAAAAAAAKAUwAAAABAAAADAAAAAgADAAIAAQACAAAAAgAAAAQAAAABAAAAHRpbWUAAAAABAAAAG5hbWUAAAAAAAAAAAAABgAIAAYABgAAAAAAAwAEAAAAdGltZQAAAAD/////uAAAABQAAAAAAAAADAAWABQAEwAMAAQADAAAAOABAAAAAAAAFAAAAAAAAAMDAAoAGAAMAAgABAAKAAAAFAAAAFgAAAAeAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAAAAAAAAAAAA8AAAAAAAAADwAAAAAAAAAAAAAAACAAAAHgAAAAAAAAAAAAAAAAAAAB4AAAAAAAAAAAAAAAAAAAAAAA0Rm3ZfFgBYVAmpdl8WALCbAbd2XxYACOP5xHZfFgBgKvLSdl8WALhx6uB2XxYAELni7nZfFgBoANv8dl8WAMBH0wp3XxYAGI/LGHdfFgBw1sMmd18WAMgdvDR3XxYAIGW0QndfFgB4rKxQd18WANDzpF53XxYAKDudbHdfFgCAgpV6d18WANjJjYh3XxYAMBGGlndfFgCIWH6kd18WAOCfdrJ3XxYAOOduwHdfFgCQLmfOd18WAOh1X9x3XxYAQL1X6ndfFgCYBFD4d18WAPBLSAZ4XxYASJNAFHhfFgCg2jgieF8WAPghMTB4XxYAAAAAAAAAAAAAAAAAAAAAAQAAAAAA+H8AAAAAAAAAQAAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAQAAAAAA+H8AAAAAAAAAQAAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAQAAAAAA+H8AAAAAAAAAQAAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAQAAAAAA+H8AAAAAAAAAQAAAAAAAAPA/AAAAAAAA8D8AAAAAAAAAAAAAAAAAAAAAAQAAAAAA+H8AAAAAAAAAQAAAAAAAAPA/AAAAAAAA8D8QAAAADAAUABIADAAIAAQADAAAABAAAAAsAAAAPAAAAAAAAwABAAAAoAEAAAAAAADAAAAAAAAAAOABAAAAAAAAAAAAAAAAAAAAAAAAAAAKAAwAAAAIAAQACgAAAAgAAABYAAAAAgAAACgAAAAEAAAA/P7//wgAAAAMAAAAAQAAAEEAAAAFAAAAcmVmSWQAAAAc////CAAAABQAAAAIAAAAQS1zZXJpZXMAAAAABAAAAG5hbWUAAAAAAgAAAJgAAAAEAAAAgv///xQAAABgAAAAYAAAAAAAAwFgAAAAAgAAACwAAAAEAAAAdP///wgAAAAQAAAABQAAAHZhbHVlAAAABAAAAG5hbWUAAAAAmP///wgAAAAMAAAAAgAAAHt9AAAGAAAAbGFiZWxzAAAAAAAAiv///wAAAgAFAAAAdmFsdWUAEgAYABQAEwASAAwAAAAIAAQAEgAAABQAAABEAAAATAAAAAAACgFMAAAAAQAAAAwAAAAIAAwACAAEAAgAAAAIAAAAEAAAAAQAAAB0aW1lAAAAAAQAAABuYW1lAAAAAAAAAAAAAAYACAAGAAYAAAAAAAMABAAAAHRpbWUAAAAAwAEAAEFSUk9XMQ==
```

![image](https://user-images.githubusercontent.com/1692624/107037242-cbf55c00-6788-11eb-8bff-f265840e2d34.png)

**Anything else we need to know?**:

(I'm not sure about nulls/inf, haven't tested that yet - but might want to check those as well)

The table view of this data looks like:

![image](https://user-images.githubusercontent.com/1692624/107037729-7e2d2380-6789-11eb-861c-1a8afc01aa07.png)

**Environment**:
- Grafana version: dadc8a2e2d
- Data source type & version: testdata

**Comment by leeoniya** [comment]
@kylebrandt NaNs/Infinitys seem like we should be able to prevent these rather than doing an extra data pass to clean? is this something that can occur outside of artificial cases or externally to our own codebase, like from a datasource?

**Comment by leeoniya** [comment]
we can stick something like this into the data pipeline:

```js
function sanitize(arr) {
  for (let i = 0; i < arr.length; i++)
    if (typeof arr[i] != "number" || isNaN(arr[i]) || arr[i] == Infinity || arr[i] == -Infinity)
      arr[i] = undefined;
}
```

this runs in 4ms on my machine for a 1M array of `Math.random()` values.

**Comment by kylebrandt** [comment]
Yes, you can get `NaNs` from datasources. Since things are using arrow, it supports those float values (things JS has, but JSON doesn't).

**Comment by Sinketsu** [comment]
We got the same error in the "Explore" mode. Is it the same problem? 
(From the backend got data like `"values":[[1606395600,"-Inf"],[1606410000,"-Inf"],...`)

**Comment by hugohaggmark** [comment]
I had a look at this today, and the unhandled exception is gone but the time series is not rendered. 
![image](https://user-images.githubusercontent.com/562238/118268463-b39a8900-b4bd-11eb-8899-0cabfc29a926.png)

**Comment by ashharrison90** [comment]
so I also had a look at this today as part of getting to know the codebase 🤓 

what I believe is happening:
- `Graph` component uses `flot` under the covers
- `flot` handled `NaN` values explicitly with this PR: https://github.com/flot/flot/pull/1681/files#diff-4153bd86af29045a5da35da1838255bbc934ef5e58e45ef02113f0a62101ca89R39. it would skip drawing `NaN` values, resulting in the gap in the chart.
- `GraphNG` component uses `uPlot` under the covers
- `uPlot` **does not** handle `NaN` values, and probably never will given [this comment](https://github.com/leeoniya/uPlot/issues/419#issuecomment-751497917)

i thought there was an option somewhere to coerce `NaN` values to `null`/0/whatever you want, but I can't seem to find it so I might be misremembering.

we could preprocess the array before passing it into `uPlot` and coerce `NaN` -> `null`, which does preserve the old behaviour:

![image](https://user-images.githubusercontent.com/20999846/121214252-d464bd00-c876-11eb-99c1-abe2257a69b0.png)

but tbh i don't know enough to know whether that's wise. for larger datasets there will undoubtedly be a performance impact. i'll await a comment from someone more knowledgable.

(disclaimer: everything i've just said could be wrong as i'm a noob)
