### ISSUE TITLE
Feature Request: Option to hide null / zeroe values in  tooltip

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#3094]
Related to this: https://github.com/grafana/grafana/issues/1381

An option to hide null / zero values from the tool tip would be great, both for stacking (when we must use null as zero) and for intermittent graphs, such as points only or partial graphs like the ones below,  which still show in the tool tip even when there is no data in that position

![image](https://cloud.githubusercontent.com/assets/11908736/10840619/c640949c-7ee9-11e5-8db5-b579ffc0ea82.png)

![image](https://cloud.githubusercontent.com/assets/11908736/10840702/8e757e0a-7eea-11e5-8732-a2098bb03db4.png)

**Comment by torkelo** [comment]
there already is an option for hide null, (called hide empty)

**Comment by torkelo** [comment]
will close as there already is an issue for this :)

https://github.com/grafana/grafana/issues/1381

**Comment by linar-jether** [comment]
Hide empty only hides the series if it's all nulls, but if only a part of the series is not null then it stay on the tooltip for all points (even null points, as in the first picture)
