### ISSUE TITLE
UI headers are inconsistent

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#30947]
This is an epic issue to track progress.

Headings in the Grafana UI are inconsistent in style and capitalization. On some pages, they jump heading levels (like an h4 following an h2) or use bold text where there should be a heading.

Go through the Grafana UI and check the following:

- All headings are in sentence case.
- Ampersands are not used to abbreviate "and" unless there is limited space.
- Headings progress in a linear fashion and do not skip levels.
- Text that looks like a heading is a heading. Check for bold text pretending to be a heading.

Contact @grafana/docs-squad if you have questions about the UI text. Please add @grafana/docs-squad as a reviewer if it is likely the docs will need to be updated as a result of the change.

- [ ] Data sources
- [ ] Panels
- [ ] Menus
- [ ] Plugins
- [ ] Please expand and add subitems as necessary

**Comment by hugohaggmark** [comment]
Friendly reminder to add labels to all new issues so people on Issue Triage don't need to. Thank you.

**Comment by torkelo** [comment]
I think you already created an issue for this some time ago https://github.com/grafana/grafana/issues/19267

Can you update that issue with any new details?

But I agree headings are very inconsistent in both style and casing , the style I have asked UX team to come up with a guideline for
