### ISSUE TITLE
Field capitalization is inconsistent

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#30948]
This is an epic issue to track progress. It is intended for Gardening Week, but feel free to submit PRs against it independent of Gardening Week.

Field titles in the Grafana UI are inconsistent in regards to capitalization. Some use title case, others use sentence case. They should all be in sentence case.

Go through the Grafana UI and check the following:

- All fields are in sentence case.
- Ampersands are not used to abbreviate "and" unless there is limited space.

Contact @grafana/docs-squad if you have questions about the UI text. Please add @grafana/docs-squad as a reviewer if it is likely the docs will need to be updated as a result of the change.

- [ ] Data sources
- [ ] Panels
- [ ] Menus
- [ ] Plugins
- [ ] Please expand and add subitems as necessary

**Comment by hugohaggmark** [comment]
Friendly reminder to add labels to all new issues so people on Issue Triage don't need to. Thank you.
