### ISSUE TITLE
Multiple Queries & metrics as count 1, count 2 not working as expected after 7.4 upgrade - Elasticsearch Data source 

### ISSUE THREAD

**Issue by mavasaf** [grafana/grafana#30943]
**What happened**:
when we add multiple queries with Count and Unique Count and use transformations(joins & calculations), Earlier to 7.4 upgrade, we used to get them as Count 1, Count 2, etc,. And with those values, transformations were applied. However since the 7.4 upgrade, they aren't working as expected and breaking.

**What you expected to happen**:
Expected the join and calculation transformations will work even after the upgrade. It was working well until 7.4.beta. 

**How to reproduce it (as minimally and precisely as possible)**:
With 7.3.7 or earlier version - create multiple count queries using elasticsearch datasource. 
you will have count 1, count 2, unique count 1, unique count 2, etc,.
Use transformation to join the count using the common field.
use transformation to make some calculations using count 1, count 2, unique count 1, etc,. 
organize transform and give names to the transformations. 
based on the given names, format using the overrides available. 

Now, Upgrade to 7.4, all these above changes will break. 

**Anything else we need to know?**:
when we tested with 7.4-beta, it was all good. after upgrade to 7.4, it is not working.

**Environment**:
- Grafana version: 7.4
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Windows/Linux
- User OS & Browser: Mac/Windows & Google Chrome
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
I can reproduce this, but I'm not sure it's related to Elasticsearch as I can reproduce the same behavior with other datasources.

As a workaround, I found that using `{{metric}} 1` & `{{metric}} 2` in the Alias field for the ES queries is solving the issue. 

@mavasaf can you check if this works for you while we investigate more?

**Comment by mavasaf** [comment]
Thanks for the quick response @Elfo404.  We have checked the alias option, still it does not work. When I provide the alias pattern as suggested above, nothing changes, in fact, once I move to the transform screen and move back, alias is not saved.

**Comment by Elfo404** [comment]
I think the alias not showing in the input is an unrelated bug that only affects the UI (will open a different issue for that) but the alias itself should be applied as expected:
<img width="1005" alt="Screenshot 2021-02-05 at 18 47 19" src="https://user-images.githubusercontent.com/1170767/107075875-9f6e2e00-67e2-11eb-8e75-b47291b2c4d5.png">

weird thing is I can make it work like this:
<img width="1023" alt="Screenshot 2021-02-05 at 18 50 54" src="https://user-images.githubusercontent.com/1170767/107076258-160b2b80-67e3-11eb-9e11-72fd618e66fa.png">


would you mind sharing your panel json (by clicking on `query inspector` -> `panel json`)?

**Comment by mavasaf** [comment]
ok, I believe this could be the reason. 
When using timestamp as the Date Histogram - you see the count1, count2, etc,.
however when you use Terms, you do not see separate counts, instead you notice only one count. 

![image](https://user-images.githubusercontent.com/68710456/107079682-0c62d300-67a5-11eb-9303-bf9485df0f17.png)


![image](https://user-images.githubusercontent.com/68710456/107079629-f9500300-67a4-11eb-8eb7-2db43c88a366.png)

**Comment by Elfo404** [comment]
oh, i see. Alias doesn't make sense in this case.
Might be related to https://github.com/grafana/grafana/issues/27521

**Comment by Elfo404** [comment]
@mavasaf could you please provide your panel json? I'm trying to consistently reproduce this but I'm having some troubles

**Comment by Elfo404** [comment]
So, this seems like a regression https://github.com/grafana/grafana/pull/30407 introduced.

What happens is that each field in each frame should get assigned a unique `displayName` based on their name, when 2 fields have the same name a unique name should be generated (eg. `[Count, Count]` -> `[Count 1, Count 2]`.)

I've put together a *very naive* fix to this in https://github.com/grafana/grafana/pull/31101 but this is breaking other tests.
