### ISSUE TITLE
Grafana 7.4.0 recreates grafana.db on persitent mounted volume everytime EC2 instance is recreated

### ISSUE THREAD

**Issue by VRevol** [grafana/grafana#30958]
**What happened**:
We deploy grafana in an AmazonLinux2 EC2 instance using Cloud_Init UserData and CFN_init by Cloudformation.
EC2 is part of Autoscaling Group / Launch config (1 instance at a time) but rolling upgrade when code change.

To avoid losing Datasources and Dashboards definition, we use an ElasticFileSystem mounted at boot time where we have data and plugins directories.
grafana.ini config file is changed before grafana-server is started during user data script execution.

Since yesterday we were using a _7.1.something version_, and everything was working fine, Datasources, Dashboards were still present when EC2 is recreated or updated.

Yesterday, we change the version to 7.4.0 while recreating the instance.
Command used:
`yum install -y grafana`

And it seems that now, grafana.db file is recreated from scratch and is empty. Thus I need to manually recreate Datasources and import Dashboards as json (fortunately we have them stored on a gitlab project).

Prior to that grafana version update same DB file was used and it was containing my Datasources and Dashboards.

**What you expected to happen**:
New grafana server on a new instance mount the volume and use DB as it is, DB which contains Datasources and Dashboards.
Without recreating it.

**How to reproduce it (as minimally and precisely as possible)**:
We have a persistent volume with Data & Plugins folders.
We mount it as NFSmount.
We install Grafana using `yum install -y grafana`
We change values for data and plugins paths in grafana.ini file using sed commands
We install worldmap plugin using grafana-cli command specifying the path
We start grafana-server as a service

Even if a grafana.db DB is already present with Dashboards (and Datasources I guess), it seems to recreated first time Grafana starts.

**Anything else we need to know?**:
Would like to avoid having to provision Datasources and Dashboards as it makes them not writable.
Can be exported as json to our SCM, but in this use case we would prefer using the persistent volume as shared folder.

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Cloudwatch and Prometheus
- OS Grafana is installed on: Amazon Linux2 - 4.14.214-160.339.amzn2.x86_64
- User OS & Browser: win10 & Chrome
- Grafana plugins: Worldmap panel
- Others:

**Comment by torkelo** [comment]
Strange, maybe something did no go well with the sed commands? Can you show the output from grafana server log? It will show what data paths are configured, it must have not found the data base file at startup and created a new one. We have no other reports of Grafana overwriting the db file, that would be terrible if it did that.

**Comment by VRevol** [comment]
Indeed that would be terrible :)

I will conduct more tests today and let you know the outcome. In meantime I got this starting logs:

```log
t=2021-02-05T20:22:34+0000 lvl=info msg="Starting Grafana" logger=server version=7.4.0 commit=c2203b9859 branch=HEAD compiled=2021-02-04T11:11:00+0000
t=2021-02-05T20:22:34+0000 lvl=info msg="Config loaded from" logger=settings file=/usr/share/grafana/conf/defaults.ini
t=2021-02-05T20:22:34+0000 lvl=info msg="Config loaded from" logger=settings file=/etc/grafana/grafana.ini
t=2021-02-05T20:22:34+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.data=/var/lib/grafana"
t=2021-02-05T20:22:34+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.logs=/var/log/grafana"
t=2021-02-05T20:22:34+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.plugins=/var/lib/grafana/plugins"
t=2021-02-05T20:22:34+0000 lvl=info msg="Config overridden from command line" logger=settings arg="default.paths.provisioning=/etc/grafana/provisioning"
t=2021-02-05T20:22:34+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2021-02-05T20:22:34+0000 lvl=info msg="Path Data" logger=settings path=/grafana-efs/grafana
t=2021-02-05T20:22:34+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2021-02-05T20:22:34+0000 lvl=info msg="Path Plugins" logger=settings path=/grafana-efs/grafana/plugins
t=2021-02-05T20:22:34+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2021-02-05T20:22:34+0000 lvl=info msg="App mode production" logger=settings
t=2021-02-05T20:22:34+0000 lvl=info msg="Writing PID file" logger=server path=/var/run/grafana/grafana-server.pid pid=2849
t=2021-02-05T20:22:34+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-02-05T20:22:34+0000 lvl=info msg="Creating SQLite database file" logger=sqlstore path=/grafana-efs/grafana/grafana.db
t=2021-02-05T20:22:34+0000 lvl=info msg="Starting DB migrations" logger=migrator```

**Comment by VRevol** [comment]
Hi Torkel,
After several checks, it seems it was related to bad permissions on the mounted filesystem.
Closing the issue as it it working as expected.
