### ISSUE TITLE
Update grafana dashboard via helm in azure

### ISSUE THREAD

**Issue by s0n00im** [grafana/grafana#30950]
**What happened**:
I am making changes to a helm config map and deploying it on the azure cluster. The azure cluster has a grafana pod running. When deploying the helm chart, i update the tile in the abc.json but the same is not reflected in the grafana dashboard.

`apiVersion: v1
kind: ConfigMap
metadata:
  name: abc-config
  namespace: abc
  labels:
     grafana_dashboard: "abc-dashboard"
data:
  abc.json: |-
    {{- $.Files.Get "custom-dashboards/abc.json"  | nindent 4 -}}`

**What you expected to happen**:
I expected the grafana dashboard to show the new title. 

**How to reproduce it (as minimally and precisely as possible)**:
Update the config map and redeploy the helm chart

**Anything else we need to know?**:
This is important. If I restart the grafana pod, I can see the updated dashboard. Once I restart the pod, any future updates for a few minutes are also reflected without another restart of the pods. But after some time, the dashboard stops getting updated and throws the error:
 
`t=2021-02-05T19:22:06+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/1/api/v1/query_range remote_addr=161.170.124.102 referer=https://abc.xyz.com/d/fKMQprYMk/code-generated-dashboard-jon-test error="http: proxy error: context canceled"
t=2021-02-05T19:22:06+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/query_range status=502 remote_addr=ipaddress time_ms=0 size=0 referer=https://abc.xyz.com/d/uid/code-generated-dashboard-test
t=2021-02-05T19:23:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=1 name="Panel Title alert" changing state to=no_data
t=2021-02-05T19:24:01+0000 lvl=info msg="Alert Rule returned no data" logger=alerting.evalContext ruleId=1 name="Panel Title alert" changing state to=no_data
`

**Environment**:
- Grafana version: v6.7.1
- Data source type & version:
- OS Grafana is installed on: mac
- User OS & Browser:chrome
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Would suggest open your issue in the helm repo: https://github.com/grafana/helm-charts

Thanks
