### ISSUE TITLE
Dashboard home page: starred dashboards not correctly sorted

### ISSUE THREAD

**Issue by tomlut** [grafana/grafana#30954]
**What happened**:
Dashboards are no longer sorted alphabetically when this option is selected.

**What you expected to happen**:
Dashboards to be sorted alphabetically

**How to reproduce it (as minimally and precisely as possible)**:
Dashboards / Manage / Sort

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: InfluxDB 1.8.3
- OS Grafana is installed on: HassOS
- User OS & Browser: Windows 10 64b Pro, Firefox 85.0
- Grafana plugins: petrslavotinek-carpetplot-panel, flant-statusmap-panel
- Others:

**Comment by daniellee** [comment]
I can't reproduce when testing locally or when running the latest docker container. I could sort alphabetically - both ascending and descending:

![image](https://user-images.githubusercontent.com/434655/107201163-ea618e80-69f8-11eb-95f8-86ad90d20fc6.png)

My local Grafana has hundreds of dashboards and folders and it is also sorted correctly when I choose the different sort options.

- Are you using the default Sqlite database for Grafana?
- Is this something to do with capital letters? For example, "a dashboard" and "A dashboard"? Can you show a screenshot of the unsorted list?

**Comment by tomlut** [comment]
It sorts fine in the management console:
![dashboard0](https://user-images.githubusercontent.com/10679300/107207034-a1720000-6a21-11eb-8424-cd0ee846d21d.png)

But not in the dashboard home:

![dashboard1](https://user-images.githubusercontent.com/10679300/107207074-ab93fe80-6a21-11eb-94df-11d614825f2e.png)

**Comment by daniellee** [comment]
@tomlut Is the issue title and issue description incorrect and it should instead to refer to the list of the starred dashboards on the Home dashboard instead? Or is there any other issue with sorting in the Manage section?

I can't recreate this with a fresh instance of Grafana but I can recreate it on some of our Grafana instances. Seems to be a frontend bug as the list is correctly sorted when returned from the backend.

API response:
![image](https://user-images.githubusercontent.com/434655/107520737-06f4f680-6bb2-11eb-8457-0181770bac0e.png)

Starred section on the home dashboard:
![image](https://user-images.githubusercontent.com/434655/107520897-31df4a80-6bb2-11eb-9534-77604b6e4e51.png)

**Comment by daniellee** [comment]
This is a bug in the [fetchDashboards function](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/dashlist/DashList.tsx#L22). It can return the dashboards in the wrong order sometimes if a starred dashboard is in the recent dashboards list.

1. A map is created and the recent dashboards are [added to the map first](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/dashlist/DashList.tsx#L53-L58). In my use case above, I had visited the Ultimate Graphite Query guide more recently than StackdriverCore so it gets added to the map in that order.
2. The starred dashboards are added to the same map in a later step and dashboards that are already added to the map are skipped.

So the order of the starred dashboards will actually be the order of the Recently viewed dashboard list (with unstarred dashboards filtered out):

![image](https://user-images.githubusercontent.com/434655/107524305-e9c22700-6bb5-11eb-941b-750e0ef36430.png)

After visiting the StackdriverCore dashboard, the order for starred dashboards changes to have StackdriverCore as the first dashboard:
![image](https://user-images.githubusercontent.com/434655/107524577-386fc100-6bb6-11eb-8415-0dd470f3a1c0.png)

**Comment by daniellee** [comment]
@tomlut I changed the issue description to focus on the sorting bug with starred dashboards on the home page. Let me know if that doesn't seem correct to you.
