### ISSUE TITLE
Color scheme "classic palette" not working

### ISSUE THREAD

**Issue by docolli** [grafana/grafana#30955]
**What happened**:
I have a table with 10 values from 1 to 10.
I have formated it with "color background" and color scheme "classic palette".
Background color of cells are ALL uniform "yellow"

**What you expected to happen**:
Cells are getting different colors, according to definition of "classic palette", since every cell has a different value.

**How to reproduce it (as minimally and precisely as possible)**:
Make (MySQL) table with 10 values from1 to 10 and get data from this table.
Format data as table values and select "table" for panel visualization.
Select "Field" -> "Cell display mode" -> "Color background"
Select "Field" -> ""color scheme" -> "Classic palette"

**Anything else we need to know?**:
If you select "color scheme" -> "Green-Yellow-Red" you get a different color for each table cell.

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu Server 20.04
- User OS & Browser: Windows 10 / Firefox 85
- Grafana plugins: no extra plugins
- Others:

**Comment by dprokop** [comment]
@docolli the "Classic palette" applies the color to the series, not the value. If you want to color your table by values you need to use `bye value` schemes, marked as such in the UI:
![image](https://user-images.githubusercontent.com/2376619/107199903-4a573580-69f7-11eb-87c1-5156a23c79d1.png)
