### ISSUE TITLE
Interpolate tag value in alerting message

### ISSUE THREAD

**Issue by xandr2** [grafana/grafana#30967]
**What would you like to be added**:
Is it possible to add label interpolation to tag value?

**Why is this needed**:
This feature will help filter alerts by tags based on variables. It's a killer feature for using with tools like Opsgenie and others.

<img width="1023" alt="Screen Shot 2021-02-07 at 7 26 23 PM" src="https://user-images.githubusercontent.com/14262685/107154384-5a313400-697b-11eb-8f2a-00dc4cbb7fb4.png">

**Comment by rzhyhanov** [comment]
I need it to

**Comment by sychevsky** [comment]
also needed

**Comment by ilumen07** [comment]
need need need

**Comment by lesha-sign** [comment]
awesome

**Comment by moonchildua** [comment]
I need it to

**Comment by akrymets** [comment]
Such feature would be fantastic!

**Comment by mkjmkumar** [comment]
This is a great feature and can solve problems we are facing to publish alert as PubSub message

**Comment by mkjmkumar** [comment]
Please provide

**Comment by Bilanda** [comment]
Any news for this feature ?
