### ISSUE TITLE
grafana randomly deletes query

### ISSUE THREAD

**Issue by aCLr** [grafana/grafana#30969]
**What happened**:
Grafana randomly delete query or its parts when it edited.

**What you expected to happen**:
I expect that nothing deletes :)

**How to reproduce it (as minimally and precisely as possible)**:
Just edit something.

**Anything else we need to know?**:
Here is a GIF attached. When query deletes I just copied it (ctrl+C). When it appears again I just press ctrl+Z several times.
![gr](https://user-images.githubusercontent.com/6426720/107186428-53df9e00-69f5-11eb-941e-113d1757327b.gif)

**Environment**:
- Grafana version: v7.3.1 (6668161a88)
- Data source type & version: prometheus 7.3.1
- OS Grafana is installed on: ubuntu 20.04.01 (in docker CE 19.03.13)
- User OS & Browser: kde plasma with firefox 84.0.2 (64-bit). UPD: checked with other users: reproduced on any os and browser.
- Grafana plugins: only systems
- Others:

**Comment by torkelo** [comment]
This has been fixed in subsequent patch releases
