### ISSUE TITLE
Missing "Set Now" button in Time Range tab

### ISSUE THREAD

**Issue by testuser7** [grafana/grafana#3096]
Button "Set Now" in new Grafana v2.5.0 is removed. Now we need to write manually "now" in field.

**Comment by torkelo** [comment]
picking any of the relative times like Last 5 minutes, or Last 1 hour will set now. Not ideal, but dont think there need to be a set now button.

**Comment by testuser7** [comment]
My use case is:
- select manually range on graph (specific from point)
- set time range "to" to now

New interface is not so comfortable as old one.
