### ISSUE TITLE
Table: gradient gauge cells are no longer readable

### ISSUE THREAD

**Issue by dirkallaert** [grafana/grafana#30965]
**What happened**:
After upgrading to grafana 7.4.0, values next to gradient gauges in a table are no longer readable:
![image](https://user-images.githubusercontent.com/29406536/107149525-58ef0f80-6959-11eb-9b60-ff4811e2b6c0.png)

**What you expected to happen**:
in earlier versions of Grafana the fields with cell display mode set to gradient gauge were readable:
![image](https://user-images.githubusercontent.com/29406536/107149546-70c69380-6959-11eb-91c9-976c90b0f4d9.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a table
set cell display mode for 1 column to Gradient gauge
set unit to microseconds

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker
- User OS & Browser: Windows & Firefox

**Comment by torkelo** [comment]
Fix coming in v7.4.1
