### ISSUE TITLE
Alerting for different visualizations

### ISSUE THREAD

**Issue by ggiinnoo** [grafana/grafana#30962]
**What would you like to be added**:
I know there is a project called alerting-ng in the grafana repo. But it doesn't clarify if more visualization types are going to be supported.

**Why is this needed**:
Well... It's helpfull.

For example, i have a table that contains data, and it would be nice to create a alert for that table if it hasn't been updated.

Maybe i missed something, if so the documentation might need some updating :)

**Comment by torkelo** [comment]
Our plan is to make alerting rules standalone and separate from dashboard visualizations. 

So you can alert on any query & data.

**Comment by ggiinnoo** [comment]
Thank you for the answer @torkelo, when would you think feature is finalised?
Will it be in version 7.5 for example, or is a part of the the Alerting-ng project.

**Comment by torkelo** [comment]
v8 (june)

**Comment by ggiinnoo** [comment]
Alright. Thank you 😊
