### ISSUE TITLE
Size field for Raw Data is missing after upgrading to 7.4.0

### ISSUE THREAD

**Issue by dirkallaert** [grafana/grafana#30964]
**What happened**:
After upgrading to grafana 7.4.0, the "Size" field is no longer available for Raw Data. 

**What you expected to happen**:
Field should remain available with at least the same max value as previous version of grafana

**How to reproduce it (as minimally and precisely as possible)**:
Reproducable by upgrading to 7.4.0 and downgrading back to 7.3
Add a panel, choose Raw Data

**Anything else we need to know?**:
Grafana 7.3
![image](https://user-images.githubusercontent.com/29406536/107147945-f2fe8a00-6950-11eb-94a1-fc114ddcb864.png)

Grafana 7.4.0:
![image](https://user-images.githubusercontent.com/29406536/107147957-f85bd480-6950-11eb-9c63-5d7f8edb6058.png)

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker
- User OS & Browser: Windows / Firefox
- Grafana plugins: grafana-piechart-panel,grafana-azure-monitor-datasource,mtanda-google-calendar-datasource,alexanderzobnin-zabbix-app,jasonlashua-prtg-datasource,snuids-trafficlights-pan
el,ryantxu-ajax-panel,grafana-worldmap-panel,agenty-flowcharting-panel

**Comment by torkelo** [comment]
@Elfo404 looks like a bug introduced by react migration
