### ISSUE TITLE
Add tresholds functionality to Timeseries grap like in the graph panel

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#30960]
In the graph panel it was posible to make tresholds like in the picture.
![image](https://user-images.githubusercontent.com/8969659/107136482-d5570380-6903-11eb-807d-1df7f31f9792.png)

The Timeseries graph(beta) supports colors with base that seam not to make sence, eg. has no functionality
![image](https://user-images.githubusercontent.com/8969659/107136505-249d3400-6904-11eb-8f17-e5f5733ed827.png)

**Comment by leeoniya** [comment]
we have an active list of bugs & features that still need to be added here: https://github.com/grafana/grafana/issues/30564, please take a look.
