### ISSUE TITLE
Why Pie Chart is Time Dependent?

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#30974]
**What would you like to be added**:

Pie Chart should work with Table panels. All it need is a label column and a value column. It should aggregate the value columns if the label column has duplicates.

**Why is this needed**:

Pie Charts becomes very useless and limited when it's dependent on time series data. I can set a dummy time column as a workaround but it's cumbersome and wouldn't work with "Transformations".

I have a table which holds the source data, then I want to use the same table panel as a source for different panels. In case of pie chart, I need to apply transformations (filter columns) and display it as a pie chart but it wouldn't work because pie chart wants time series data.

**Comment by torkelo** [comment]
the new core (bundled) pie chart panel will support this. 

Coming in 7.5 https://github.com/grafana/grafana/pull/28020
