### ISSUE TITLE
Invalid archive with the source code of 7.3.7 ?

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#30987]
Hello! 
Downloaded the source code from here
![Screenshot_3](https://user-images.githubusercontent.com/43705385/107219519-45f44200-6a22-11eb-976c-1eb212caaf9c.png)

After the build:
![Screenshot_2](https://user-images.githubusercontent.com/43705385/107219341-fdd51f80-6a21-11eb-8bbe-ffc6a5736408.png)

**Comment by torkelo** [comment]
yea, we messed up the version bump for 7.3.7 , use this branch instead https://github.com/grafana/grafana/tree/v7.3.x 

is has backports that has yet to be released
