### ISSUE TITLE
Add icon packages for tables like country flags

### ISSUE THREAD

**Issue by leonv024** [grafana/grafana#30994]
**What would you like to be added**:
I replaced my self build website for monitoring with Grafana, but I am really missing customization features.

One of the features I really miss would be icon packages for tables.
For example; I would like to see the profile picture of users in the table and flag icons for countries.

**Why is this needed**:
It would not only look neat and personal, but could also make the data more clear and easier to read.

**Comment by peterholmberg** [comment]
You can use (field options)[https://grafana.com/docs/grafana/latest/panels/visualizations/table/table-field-options/] for displaying images and for countries the only option I can think of is to use value mappings as an override.
