### ISSUE TITLE
A possibility to switch off the "smart" functionality of the PromQL query's editor.

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#30997]
**What would you like to be added**:
I've been eagerly waiting for `7.4.0` and after a couple of insane hours of trying to edit a couple of queries within the PromQL query's editor I really beg for an option to "switch off" all those "smart" functionalities of the editor (before some big edit operation).
I am not going to repeat myself again so please see https://github.com/grafana/grafana/issues/28134.

NB Disabling(?) a query clicking on the `Disable / enable query` icon does not work. And worse - when a query is disabled, edited and the cursor moved to other query editor, from time to time the cursor jumps back to the previous query editor and this query is enabled again! (for more than one query within a panel)

**Why is this needed**:
To make the PromQL editor really usable.

**Comment by ivanahuckova** [comment]
Hello @hawran! 

Regarding
>NB Disabling(?) a query clicking on the Disable / enable query icon does not work. And worse - when a query is disabled, edited and the cursor moved to other query editor, from time to time the cursor jumps back to the previous query editor and this query is enabled again! (for more than one query within a panel)

I was able to recreate this issue and I think that this specific issue probably dissevers its own github issue as it doesn't seem to be connected to the smart promql functionality. I was able to recreate this also in some of the other data sources. I will open it and mention you there for visibility. 

Regarding
>For more complex or more than one query the editor is not usable and one really must fight with it for expected results.
It is really annoying when you edit something at the end of a query, you pause and before you can continue the cursor jumps at the beginning of the query.

The jumping cursor is unfortunately not connected to the "smart" functionalities. So turning them off wouldn't solve your problem. We have found out, that jumpy-cursor behaviour is connected to the library that we are using in Query Editor - Slate. They have fixed the problem, but in the same release, they have totally changed the API. We are using Query Editor also for external plugins and this migration isn't a small change. We have done some research on if it makes sense to update Slate or try different editor, but this is still WIP. I am not sure what browser do you use, but jumpy-cursor is mostly happening in Firefox browser. I know it is not ideal, but quick fix to better experience would be to try to use other browser (if you use Firefox). It might improve your experience.

**Comment by ivanahuckova** [comment]
I am going to close this issue in favour of https://github.com/grafana/grafana/issues/26760, which is describing the jumpy-cursor behaviour, which is not strictly related to Prometheus, but affects our Prometheus users. Please follow that one for more updates on this issue.

**Comment by hawran** [comment]
> I am going to close this issue in favour of #26760, which is describing the jumpy-cursor behaviour, which is not strictly related to Prometheus, but affects our Prometheus users. Please follow that one for more updates on this issue.

OK, thank you.
