### ISSUE TITLE
No series overrides available in Time Series panel in 7.4

### ISSUE THREAD

**Issue by mahesh-discovery** [grafana/grafana#31009]
**What would you like to be added**:  New Time series panel is very good when we have multiple metrics with different units where we can use multiple Y-axis but this panel doesn't have "Series Overrides" which is available in Graph panel.

**Why is this needed**:  In some case like Splunk queries we do get "_span" additional series and we make that hidden using series overrides. It would be better if we have this feature in Time Series panel.

**Comment by dprokop** [comment]
@mahesh-discovery the overrides are available, but with the [field config.](https://grafana.com/docs/grafana/latest/panels/field-options/). We have unified the time series panel to use the new field options architecture introduced in 7.0.

Axes are created based on the unit configuration, so you need to create unit [overrides](https://grafana.com/docs/grafana/latest/panels/field-options/configure-specific-fields/) for your series and the axes will be automatically rendered based on these settings.

To see how to create multiple y-axes please refer to this panel https://play.grafana.org/d/nP8rcffGk/1-new-features-in-v7-4?orgId=1&from=1612835612364&to=1612857212364&viewPanel=54
