### ISSUE TITLE
Add previous/next period buttons.

### ISSUE THREAD

**Issue by magmax** [grafana/grafana#3101]
Usually I have to see what happened in the previous period of time I'm currently seing, and the way to do that is by using custom time periods, but it require some time to configure the start/end time.

Doing zoom out is not enough, because it is giving me too much information (i.e. from 1h to 6h).

The best solution should be to have a next/prev buttons (maybe showed as arrows) to see the previous/next period block with the same size.

Example: If I'm seing "from last hour to now", by clicking "previous" I should see "from two hours ago to one hour ago", and so on.

**Comment by torkelo** [comment]
we are discussing something like this in this issue, https://github.com/grafana/grafana/issues/119#issuecomment-150326257

**Comment by magmax** [comment]
Sorry, I was looking for it but I didn't found that.

Thank you!
