### ISSUE TITLE
Matchers: Add support to match series by label 

### ISSUE THREAD

**Issue by secustor** [grafana/grafana#31015]
**What would you like to be added**:
I would like to set the color of the statPanel based on a label value rather than the metric value. 

**Why is this needed**:
I have these metrics: 
`nagios_check_ok{check_id="check1", host="xyz", state="unknown"} 1`
`nagios_check_ok{check_id="check2", host="xyz", state="ok"} 1`
`nagios_check_ok{check_id="check3", host="xyz", state="warning"} 1`
`nagios_check_ok{check_id="check4", host="xyz", state="critical"} 1`

I query the metrics with `nagios_check_ok{host="xyz"}`.     
In the stat panel, this will generate 4 stats, one for each metric.    
Now I want to color the stats based on which `state` label value is present.     
E.g. green for `ok` and red for `critical`

I have looked into overwrites, but I haven't found a satisfying solution.

**Comment by torkelo** [comment]
This would be easy to add using a new matcher in the field override system. 

Currently have matchers that only target field name & field type, source query. 

Adding one that match on label name & value makes sense 
https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/transformations/matchers.ts

**Comment by secustor** [comment]
I'm not sure if this requires an UI change as, as far I know every overwrite option has a single matcher field.    

Would you accept a PR to get this in an earlier release then v8.0.0?
