### ISSUE TITLE
Wrong unit(pps) in legend when showing both average and total

### ISSUE THREAD

**Issue by henry-spanka** [grafana/grafana#3102]
When using an unit like packets per second(pps) the total metric has an incorrect unit.

Average's unit is pps(correct).
Totals unit is pps(incorrect). Should only be packets.

![Example](https://cloud.githubusercontent.com/assets/10375269/10847241/5aafd608-7f15-11e5-84f1-c49277b7240d.png)

**Comment by torkelo** [comment]
total and avg use same units, works as intended, sorry

**Comment by torkelo** [comment]
total is not something you can normally show when you have a rate metric (it wont always be accurate)

**Comment by torkelo** [comment]
to get total you need to have a counter and consolidate (aggregate) using sum,  rates aggregate using avg
