### ISSUE TITLE
Loki: Add required flag and url validation to derived fields url field setting

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#31024]
**What would you like to be added**:

Make the url field in derived fields compulsory.
Maybe add url validation as well.

**Why is this needed**:

There was an issue related to that https://raintank-corp.slack.com/archives/C010C1A4KCM/p1612462955113600

**Comment by matyax** [comment]
Right now we can't proceed with these changs until https://github.com/grafana/grafana/issues/54228

**Comment by matyax** [comment]
Superceeded by https://github.com/grafana/grafana/issues/54228
