### ISSUE TITLE
Share Dashboard raintank

### ISSUE THREAD

**Issue by floppy84** [grafana/grafana#3103]
Hi,

Since i made grafana upgrade to 2.5 i can't do an export share with raintank.

![image](https://cloud.githubusercontent.com/assets/3499449/10849257/226fb05a-7f20-11e5-8695-b6f6500e3774.png)

i got this message in log :+1: 
 logs: /var/log/grafana

2015/10/30 16:02:15 [I] Database: sqlite3
2015/10/30 16:02:15 [I] Migrator: Starting DB migration
2015/10/30 16:02:15 [I] Listen: http://0.0.0.0:3000/grafana
2015/10/30 16:02:38 [I] Completed /snapshots-origin.raintank.io/api/snapshots 404 Not Found in 2.461083ms
2015/10/30 16:05:06 [I] Completed /snapshots-origin.raintank.io/api/snapshots 404 Not Found in 1.36796ms
2015/10/30 16:05:23 [I] Completed /snapshots-origin.raintank.io/api/snapshots 404 Not Found in 1.304373ms

**Comment by torkelo** [comment]
must have been a temporary glitch, seems to work now

**Comment by floppy84** [comment]
not for me

**Comment by floppy84** [comment]
Sorry it come from a change  on firewall rule from my side thanks
