### ISSUE TITLE
Order metrics on hovercard by value

### ISSUE THREAD

**Issue by hcooper** [grafana/grafana#3106]
Currently the values displayed in the hover card are in a fixed order. However when there is multiple lines, distinguishing them purely by color is difficult.

It would be good if the hover card could be dynamically reordered based upon the time point currently being hovered over. (i.e. the order of the items in the hover card reflects the order of the lines on the chart).

I'd suspect making this optional would be best, as in other situations a static order is probably preferred.

An example of a hard to read view:

![selection_999 105](https://cloud.githubusercontent.com/assets/131580/10857411/303ca95a-7f0b-11e5-9e16-d89596d065b0.png)

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1189
