### ISSUE TITLE
Show $__interval on the panel

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#31060]
**What would you like to be added**:

 I don't want to set an interval using variables. I want Grafana to decide the time grouping interval dynamically and it does. Yet, I want to see the interval it's using outside of the panel. 

- Something like "relative time" and "time shift" indicators on the upper right corner would be great.
- At least, I should be able show the interval information in the title or in the description.

![image](https://user-images.githubusercontent.com/43188411/107417976-298dfd80-6b27-11eb-9ed9-a40a601dc5bd.png)

**Why is this needed**:

Usually, I need to click 'edit' and see the interval. It would be good to see it outside for ease of use and for users without edit permission.

**Comment by chensi12** [comment]
I want to show the system interval on the panel too, Unfortunately, it does not work。

**Comment by torkelo** [comment]
supported in upcoming 8.4, try nightly build! 
https://github.com/grafana/grafana/pull/43082
