### ISSUE TITLE
Add Percentage in Time Series Panel Legend

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#31063]
**What would you like to be added**:

I would like the see a percentage option in the legend of "time series panel".

![image](https://user-images.githubusercontent.com/43188411/107423058-f2224f80-6b2c-11eb-9df4-00fae1426ddd.png)

It can be useful in a graph like this one:

![image](https://user-images.githubusercontent.com/43188411/107423625-9ad0af00-6b2d-11eb-8e8a-626cb12151ab.png)

**Why is this needed**:

Some times we want to know the share of each element just like pie-chart. Since pie-chart can already do that with the same "Time Series" type query, I thought it would be easy to add that functionality in to the Time Series Panel.

**Comment by torkelo** [comment]
The new time series panel in 7.4 has different percentage (diff between first value and last value) 
![Screenshot from 2021-02-09 22-19-56](https://user-images.githubusercontent.com/10999/107430107-0b270280-6b25-11eb-8d47-dfd4e6fa68d5.png)
