### ISSUE TITLE
Try to reduce number of unnecessary DB requests from Grafana middleware

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#31072]
We should reduce the number of unnecessary DB requests from Grafana middleware, since it degrades performance. Requested by @bergquist.

**Comment by bergquist** [comment]
More metrics on this in a few days :)

**Comment by torkelo** [comment]
yes, and related redo dashboard provisioning so that it is a single SQL call that joins in the provisioning table instead of two separate calls :) 
the fact that dashboard provisioning adds a lot of extra complexity everywhere really messes the code base & performance

**Comment by bergquist** [comment]
I'm sure there is much to improve in the provisioning side. But one query
with joins might not be better than two.

I think... smarter caching of the dashboard hashes might be the biggest
improvement. Provisioning is currently implemented when we assume no cache
when using multiple Grafana instances. As we are moving towards
requiring redis (websockets) for HA I think we can rewrite provisioning to
only touch the database when things change.
