### ISSUE TITLE
Problem with aliases when plotting the same OpenTSDB series twice

### ISSUE THREAD

**Issue by bigkraig** [grafana/grafana#3108]
I have an OpenTSDB that I am plotting twice, once broken up by a tag and another that is the sum of the tag values.

What I want is the series broken up by tags to have the alias "$tag_cluster", and the other with "total".

If I do that, all lines are labeled "total". In fact, if I put anything in the second metric alias it  becomes the alias for everything. Except if its "$tag_cluster"

See here, where I have $tag_cluster as my alias for both metrics:

![screen shot 2015-10-30 at 1 45 46 pm](https://cloud.githubusercontent.com/assets/508403/10858165/218d571a-7f10-11e5-99f7-04c3ac1b27e7.png)

And here it is when I change it to "$tag_cluste":

![screen shot 2015-10-30 at 1 45 34 pm](https://cloud.githubusercontent.com/assets/508403/10858143/02a0b73e-7f10-11e5-8b7d-9f026e5bb47c.png)

**Comment by torkelo** [comment]
this is due top a limitation in OpenTSDB (no way to figure out what series came from which query), this has been reported many times before (please search for issues before posting), 

Anyone the good news is that OpenTSDB 2.2 (out in rc I think) has fixed this so in an upcoming version of grafana this has the potential to be fixed.

https://github.com/grafana/grafana/issues/1876
