### ISSUE TITLE
Cloudwatch metrics not working on Explore

### ISSUE THREAD

**Issue by hakro** [grafana/grafana#31085]
**What happened**:
Cloudwatch metrics return an empty error on Explore, Grafana 7.4.0
An empty red panel appears, and there are no error logs on stdout

EDIT : Found some logs on stdout when running Grafana locally : 
EROR[02-10|11:12:02] Failed to get regions                    logger=tsdb.cloudwatch error="UnauthorizedOperation: You are not authorized to perform this operation.\n\tstatus code: 403, request id: fafcc68b-4c57-4ab4-a1bd-f49df530cd26"

![Screenshot_2021-02-10_11-31-02](https://user-images.githubusercontent.com/3624853/107500269-43b2f480-6b96-11eb-8d02-46009dc2849e.png)

The same query, using the same datasource works fine on dashboards : 
![Screenshot_2021-02-10_11-27-20](https://user-images.githubusercontent.com/3624853/107500355-5a594b80-6b96-11eb-9397-1f9fa802b7d6.png)

**What you expected to happen**:
Be able to query Cloudwatch metrics on Explore.
It works fine on Grafana 7.3.7

![Screenshot_2021-02-10_11-56-09](https://user-images.githubusercontent.com/3624853/107500889-fd11ca00-6b96-11eb-9876-0b4ea0b96812.png)

**How to reproduce it (as minimally and precisely as possible)**:
On Grafana 7.4 go to Explore
Choose an AWS Cloudwatch Datasouce
Choose Query Mode = CloudWatch Metrics
Choose any namespace and try to get any dimensions
A red error panel appears, with no errors in it.
Same query works on a dashboard

**Anything else we need to know?**:
- Same datasource is used everywhere, including with a full AWS Adminstrator permission
- Explore Broken on Grafana 7.4.0
- Explore works fine on Grafana 7.3.7
- Dashboards work well on both

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: AWS Cloudwatch (core)
- OS Grafana is installed on:  Official Grafana Docker image on Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04 & Firefox 85 & Chromium 88
- Grafana plugins: None
- Others: None

**Comment by sunker** [comment]
Thanks for reporting this @hakro. 

I get the empty error message too, but for me the query seems to work. The panel gets populated with data. Is that the case for you too?

**Comment by hakro** [comment]
Hi @sunker 

Actually no, the panel in Explore does not show up at all in my case in 7.4.0.
It works in Dashboards though.
The query I do is really simple. I just try to get the CPU reservation on an ECS cluster.

When trying the same thing in Grafana 7.3.7, with the exact same query and IAM user, it works fine.
Let me know if you need any more info.

Thx
Cheers.

**Comment by sunker** [comment]
Thanks for getting back to me so quickly. 

It's weird. For me the panel is being populated correctly with data - the only problem is the empty error message. Can you try using a different query? 

Anyway, I'll come up with a fix asap.

**Comment by hakro** [comment]
I just upgraded to Grafana **7.4.1**, which was released yesterday, and now I get the same thing as you.
The Panel now does show up with data, but the red banner is still there.
This is happens for any query on Cloudwatch Metrics.
Cloudwatch logs work fine however.

![Screenshot_2021-02-12_14-01-08](https://user-images.githubusercontent.com/3624853/107775270-5cf7a480-6d40-11eb-89be-f64d3a104a75.png)

**Comment by sunker** [comment]
Okay, thanks @hakro! Fix is coming and will hopefully be released mid next week.

**Comment by hakro** [comment]
Outstanding.
Thanks a lot @sunker 

Cheers.
