### ISSUE TITLE
Table: Option to disable virtualized rows 

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#31106]
_I don't know if this is a bug or FR._

When I have a data in a table panel, only rows that are in viewport are present. 

So hitting `cmd+f` and searching for a row that is bellow the viewport border gives 0 results.

Would be a nice to have an option to disable this behaviour. I understand it is great for performance, especially for large datasets but kinda sucks for a table with 100 rows where 25 of them are visible and you cannot search in the rest of it.

Currently one has to scroll to the bottom first in order to search the table panel.

**Comment by torkelo** [comment]
You can enable column filters to search values that are not shown (field option).


Don't think we will disable virtualized rendering it has incredible performance benefits.

Maybe an option to disable it?

**Comment by simPod** [comment]
@torkelo column filters does not help using cmd+f.

But yes, disabling it is ofc not an option. I agree there are performance benefits. But there are usecases where this is helpful and also usecases where it is not. Eg. using `cmd+f` for browser search is not possible with this enabled.

Option for disabling would solve it for all.

**Comment by simPod** [comment]
I used a workaround in order to only slightly modify my Grafana's source code. I set a height to FixedSizeList as `height={rows.length * tableStyles.rowHeight - headerHeight}`

Checked the possible solutions to the view virtualization but it's still too early. The best way would be to render "invisible" elements that are cheap to render but searchable with browser. Seems there's no easy way to do it for now.

**Comment by zoltanbedi** [comment]
Pagination was added as well that could also solve this problem. I'm going to close this issue as it looks like that didn't get much attention.

**Comment by simPod** [comment]
@zoltanbedi I don't really see how the pagination helps the issue 🤔 There's no way to display e.g. 1K rows at once IIRC.

**Comment by zoltanbedi** [comment]
It won't but you were talking about a 100.

**Comment by simPod** [comment]
It was an example of the issue. I have also tables with other row counts than 100.

**Comment by adamhoof** [comment]
Pls reopen
