### ISSUE TITLE
File log rotation broken in 7.4.0

### ISSUE THREAD

**Issue by drewhammond** [grafana/grafana#31102]
**What happened**:

After upgrading to 7.4.0, Grafana stops logging to `grafana.log` when it reaches its rotation time. It continues to log to console, but has a `file already closed` error with every line that would have gone to file:

```
Feb  7 23:26:00 test-server grafana-server[9726]: t=2021-02-07T23:26:00+0000 lvl=info msg="Request Completed" logger=context userId=123 orgId=1 uname=test-user method=GET path=/api/dashboards/home status=200 remote_addr=172.25.1.10 time_ms=1
2 size=79 referer=http://grafana-test.example.com:8080/
Feb  7 23:26:00 test-server grafana-server[9726]: FileLogWriter("/opt/log/grafana/grafana.log"): rotate StartLogger: close /opt/log/grafana/grafana.log: file already closed
```
All logging after that gets double logged in console with the same error

```
FileLogWriter("/opt/log/grafana/grafana.log"): close /opt/log/grafana/grafana.log: file already closed
```

Restarting the process triggers the rotation and file logging works again until the next rotate event.

**What you expected to happen**:

Grafana will rotate its own file logs without errors.

**How to reproduce it (as minimally and precisely as possible)**:

1. Define lower thresholds to reproduce faster

```
[log.file]
level = debug
max_lines = 1000
```
2. Upgrade from 7.3.7 -> 7.4.0
3. Observe failures after grafana.log reaches 1k lines

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: N/A
- Grafana plugins: Can provide if relevant 
- Others: N/A

**Comment by aknuds1** [comment]
Thanks, looking into it.
