### ISSUE TITLE
Bars in bar chart are so thin they're barely visible

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#31110]
So I'm using latest master (with modified background color) and my bar chart looks like this:

![image](https://user-images.githubusercontent.com/327717/107561053-5c46fd00-6bde-11eb-890c-fae448048882.png)

As you can see in the screenshot, there are data displayed, just too thin.

When I change the panel to display lines it shows the data

![image](https://user-images.githubusercontent.com/327717/107561102-6ec13680-6bde-11eb-95d6-9ba0a00dec31.png)

Any idea what might be causing it? The panel has no settings/overrides. Happens with 100 % fresh panel.

I also tried reverting and building Grafana commits to some from August 2020 and the result is the same. Not sure what else might have effect on it. 

Any idea why those bars are so thin? Whan influences their width?

---------------

I also tried converting the dataset to data frames format but the result is the same. My input data is as follows

```json
[{"datapoints":[[57,1610409607000],[76,1610496007000],[43,1610582407000],[88,1610668809000],[111,1610755207000],[67,1610841607000],[95,1610928007000],[79,1611014408000],[47,1611100807000],[44,1611187207000],[69,1611273608000],[41,1611360009000],[70,1611446408000],[85,1611532807000],[89,1611619207000],[95,1611705608000],[95,1611705669000],[95,1611705726000],[95,1611705787000],[95,1611705846000],[95,1611705908000],[95,1611705971000],[95,1611706029000],[95,1611706086000],[95,1611706147000],[95,1611706206000],[95,1611706270000],[95,1611706326000],[70,1611792008000],[67,1611878409000],[52,1611964808000],[84,1612051207000],[60,1612137616000],[62,1612224008000],[71,1612310407000],[77,1612396809000],[70,1612483208000],[94,1612569609000],[61,1612656010000],[61,1612656070000],[54,1612742409000],[41,1612828808000],[47,1612915208000]],"target":"metric1"}]
```

**Comment by torkelo** [comment]
Is this using the old graph? Cannot replicate. Can you share panel json?

**Comment by simPod** [comment]
Yes, it's the graph panel

```json
    {
      "aliasColors": {},
      "bars": true,
      "colorsPerAliasType": {},
      "dashLength": 10,
      "dashes": false,
      "datasource": "JSON",
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 4,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "p95": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": false,
      "linewidth": 1,
      "nullPointMode": "null",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "7.5.0-pre",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "data": "{}",
          "refId": "A",
          "target": "MetricValues",
          "type": "timeseries"
        }
      ],
      "thresholds": [],
      "timeRegions": [],
      "title": "Panel Title",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "$$hashKey": "object:106",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "$$hashKey": "object:107",
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
```

**Comment by torkelo** [comment]
The data has a bunch of duplicate timestamps, think this messes up the bar width calculation

**Comment by torkelo** [comment]
Seems to work ok in new time series panel . 

if you want to fix, here is the part: https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.ts#L531

**Comment by simPod** [comment]
I guess I'm blind, I checked the data even with a script for duplicates but don't see any. 

Anyway thanks, the code line is sufficient. Will look at it

**Comment by torkelo** [comment]
Looked again and was wrong, thought I saw duplicates. Debugged this and have no idea what is going on, everything renders ok it looks like, but see only faint lines with your data.

**Comment by simPod** [comment]
I'll fix it.

**Comment by simPod** [comment]
So I did not 

but

the issue is that the timeStep is too low. There are eg. two values with 46s step while the most values have steps of something around 86000s. Therefore, considering a dataset that has 1000 "daily" values with steps around 1d size and then there are 2 values with step of few seconds, it breaks display for all the data. Not sure if there's a fix to that.

I'll round my data to daily averages.

**Comment by maemigh** [comment]
+1
I have the same issue, thought I was doing something wrong with intervals.
