### ISSUE TITLE
Docs feedback: /datasources/postgres.md

### ISSUE THREAD

**Issue by botenvouwer** [grafana/grafana#31118]
Not all postgres versions are shown (11 and 12 missing):

`postgresVersion: 903 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10`

It is not very clear how to configure version 11 or 12. It seems the option keys are not very logically incremental.

**Comment by achatterjee-grafana** [comment]
Hello, team @grafana/backend-platform, 

Can you take a look and confirm that PostgreSQL v11 and v12 are indeed missing or not supported. Also, what note/doc should be added to this topic: https://grafana.com/docs/grafana/latest/datasources/postgres/

Thank you!

**Comment by marefr** [comment]
10 means version 10 and any version above

**Comment by achatterjee-grafana** [comment]
Fixed with PR https://github.com/grafana/grafana/pull/32612.
