### ISSUE TITLE
Allow unsigned plugin doesn't allow loading them

### ISSUE THREAD

**Issue by wazery** [grafana/grafana#31125]
**What happened**:

We are using the plugin `flant-statusmap-panel` version 0.3.4 and as of that version it's unsigned. 

Recently we upgraded Grafana to version 7.4.0 which disabled allowing unsigned plugins to be loaded unless explicitly configured via `ini` file or environment variable as of the [docs](https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins).

We tried the above configuration option via both environment variables and ini configuration like so:

```
-e 'GF_INSTALL_PLUGINS=https://nexus.private.server/repository/grafana-proxy/flant-statusmap-panel/versions/0.3.4/download;flant-statusmap-panel
-e 'GF_ALLOW_LOADING_UNSIGNED_PLUGINS=flant-statusmap-panel
```

and in `grafana.ini`:

`allow_loading_unsigned_plugins = flant-statusmap-panel`

**What you expected to happen**:

We expected this plugin to be loaded after Grafana multiple restarts, but that never happned and the plugin didn't work at all unless we downgraded Grafana to version `7.0.3`

**How to reproduce it (as minimally and precisely as possible)**:

Use the `allow_loading_unsigned_plugins` to allow `flant-statusmap-panel` and check if that plugin is working or no.

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Prometheus `2.21.0`
- OS Grafana is installed on: Debian Buster
- User OS & Browser:
- Grafana plugins: `flant-statusmap-panel`
- Others:

**Comment by wbrowne** [comment]
>Recently we upgraded Grafana to version 7.4.0 which disabled allowing unsigned plugins to be loaded unless explicitly configured

This is actually only true for backend plugins. Since this is a panel, it should load correctly without any extra configuration, but will display the `unsigned` badge as a notice for the user. When you visit the plugins page in Grafana (`/plugins`) @wazery, do you see an entry for `Statusmap` there? Or is there any information in the logs?

**Comment by wazery** [comment]
@wbrowne yes I can see the plugin name with the `unsigned` label, but that plugin never actually works in the dashboards we have.

**Comment by wbrowne** [comment]
@wazery I was able to confirm the plugin works correctly in Grafana v7.3.7, but not in v7.4.0. Can you try that out? 

There's an open issue with the plugin for adding support for Grafana v7.4.0 [here](https://github.com/flant/grafana-statusmap/issues/169).

**Comment by wbrowne** [comment]
As there's nothing we can do from the Grafana side I'll close this for now. If that changes though, feel free to re-open. Thanks!

**Comment by bassmaster187** [comment]
maybe you should use: GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS for your environment variables
