### ISSUE TITLE
Grafana 7.4 leaks grafana-image-renderer processes

### ISSUE THREAD

**Issue by PhilippWendler** [grafana/grafana#31136]
**What happened**:

After upgrading to Grafana 7.4 and restarting the service, the memory consumption of Grafana and the number of processes/threads (as seen by the OS) starts to rise until all memory is full and the system crashes. Downgrading to version 7.3.7 by simply reinstalling the old packages makes it work again. The only difference in the config used for 7.4 and 7.3.7 is the syntax of `http_addr` due to #30930, everything else is the same (including dashboards).

All the accumulating processes have one of the following command lines:
```
/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome --type=zygote --no-sandbox --headless --headless
/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome --type=gpu-process --field-trial-handle=... --enable-features=NetworkService,NetworkServiceInProcess --disable-features=BlinkGenPropertyTrees,TranslateUI --no-sandbox --disable-breakpad --headless --headless --gpu-preferences=... --use-gl=swiftshader-webgl --override-use-software-gl-for-tests --service-request-channel-token=...
/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome --type=renderer --no-sandbox --allow-pre-commit-input --disable-background-timer-throttling --disable-breakpad --enable-automation --file-url-path-alias=/gen=/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/gen --force-color-profile=srgb --remote-debugging-port=0 --use-gl=swiftshader-webgl --field-trial-handle=... --enable-features=NetworkService,NetworkServiceInProcess --disable-features=BlinkGenPropertyTrees,TranslateUI --lang=en-US --headless --num-raster-threads=1 --service-request-channel-token=... --renderer-client-id=4 --shared-files=v8_context_snapshot_data:100,v8_natives_data:101
```
After a few minutes of running Grafana I have already 40 of these processes that never seem to terminate. With 7.3.7 there are much of fewer of these (never saw more than 5) and they are shortlived.

Here are some plots. I upgraded from 7.3.7 to 7.4 around 13:10 and downgraded again at 13:29 because Grafana already started becoming unresponsive.

Graph with number of OS threads (blue is Grafana):

![image](https://user-images.githubusercontent.com/2545335/107636761-68c66680-6c6d-11eb-848b-818ef825271d.png)

Memory consumption (brown is Grafana):
![image](https://user-images.githubusercontent.com/2545335/107636844-885d8f00-6c6d-11eb-988e-a084153b6bc6.png)

The number of Go threads seems to be fine though (looking at `grafana.*.go.threads` as exported to Graphite):
![image](https://user-images.githubusercontent.com/2545335/107638632-23576880-6c70-11eb-9364-411be440d1bc.png)

Number of Goroutines and GC statistics also look unremarkable.

Weirdly, the usual CPU bursts of Grafana that I see with previous versions are completely gone in 7.4. Maybe this is because some part of Grafana is not even running as expected (alerts would have been my first guess, but graph for `grafana.*.alerting.execution_time_milliseconds.quantile.*` shows no difference between versions):

![image](https://user-images.githubusercontent.com/2545335/107636978-bf33a500-6c6d-11eb-9192-b23630a92ea2.png)

**What you expected to happen**:

Approximately constant number of threads and a memory consumption similar to before.

**How to reproduce it (as minimally and precisely as possible)**:

For me it is reproducible by just upgrading to 7.4. I did so several times and each time the problem immediately started. The system has also been rebooted.

**Anything else we need to know?**:

I enabled [tracing](https://grafana.com/docs/grafana/latest/troubleshooting/diagnostics/#use-tracing), the result is here: [trace.out.zip](https://github.com/grafana/grafana/files/5965378/trace.out.zip)

I also enabled [profiling](https://grafana.com/docs/grafana/latest/troubleshooting/diagnostics/#turn-on-profiling) but I don't know how to proceed. If I visit port 6060 with a web browser, I just get error 404. The [linked Go docs](https://golang.org/cmd/pprof/) explain nothing at all, unfortunately. If you would like me to investigate something specifically, I will be happy to attempt it.

I am exporting the internal Grafana metrics to Graphite and can produce graphs, though I don't know what would be interesting. So if you would like to see something, just tell me what to plot.

Here is response time (`grafana.*.http_request_duration_milliseconds.handler.*.method.*.quantile.*.statuscode.*`):

![image](https://user-images.githubusercontent.com/2545335/107637382-5862bb80-6c6e-11eb-8705-6b6cf028c257.png)

and response status codes (`grafana.*.http_request_duration_milliseconds_count.handler.*.method.*.statuscode.*.count`):

![image](https://user-images.githubusercontent.com/2545335/107637520-8942f080-6c6e-11eb-88a3-24b60ddd87ec.png)

There was no unusual usage of my Grafana instance in this time period (same usage before and after the upgrade).

On the host with my Graphite instance there was no noticeable change in CPU usage etc. during this time.

**Environment**:
- Grafana version: 7.4 via official apt repository
- Data source type & version: Graphite 1.1 for most data, plus two mostly unused InfluxDB instances
- OS Grafana is installed on: Ubuntu 18.04
- Grafana plugins: only grafana-image-renderer 2.0.0
- Others: Grafana is behind an Apache reverse proxy; nothing else is running on this machine (dedicated VM)

**Comment by marefr** [comment]
Thanks a lot for this excellent bug report! 

Trying to look at the trace file I unfortunately get an error _failed to parse trace: no EvFrequency event_. Not sure if this due to some error in enabling the trace diagnostics in Grafana - we'll look into this. 

In regards to profiling I agree the documentation is not great, but it's a quite advanced topic so trying to link to some existing content. We should probably update that link to some other page, for example this one: https://golang.org/pkg/net/http/pprof/

That article describes how you would use `go tool pprof` to collect different profiles. You could actually use curl to collect these as well. To begin with you can view all available profiles by opening http://localhost:6060/debug/pprof/ in your browser.

Then you can use curl to download profiles:
```shell 
curl http://<host>:<profiling port>/debug/pprof/heap > heap1.pprof
# wait for a while when you've noticed memory consumption increased (quite a lot if possible) and extract a new one. If you don't have a lot of time until system crashes try to wait 15-30 seconds between them if possible.
curl http://<host>:<profiling port>/debug/pprof/heap > heap2.pprof
```

Since you're saying _memory consumption of Grafana and the number of processes/threads (as seen by the OS) starts to rise until all memory is full and the system crashes_ collecting the heap profiles could be interesting. 

In regards to your collected metrics, you might have a look at plotting metrics for _*go_memstats_heap*_ in use and allocs - should show similar things as collected heap profile, but over time.

**Some questions:**
- Are you rendering a lot of panels as images using the image renderer plugin? 
- How many alerts do you have?

**Would be useful if you could try upgrading again:**
- When shutting down Grafana 7.3.7, do you still have grafana image renderer processes lying around?
- Collect debug log message/file ([enable debug log level](https://grafana.com/docs/grafana/latest/administration/configuration/#level)) and see if you can find anything interesting, maybe something repeating at high frequency? Please attach and replace any sensitive information. 
- Try running Grafana 7.4 without the image renderer plugin installed (temporary move it outside grafana plugin directory)

**Comment by PhilippWendler** [comment]
> Thanks a lot for this excellent bug report!

Thanks for the feedback! And actually sorry, because when I started writing the issue, I hadn't noticed the grafana-image-renderer processes yet, so I did not think through fully in that direction and instead thought more about a general resource leak in Grafana. That might have been misleading as you will see below.

But now I can add that all calls to "Direct link rendered image" (`/render/d-solo/...`) time out, even immediately after starting Grafana 7.4 when the system is still fully responsive and unloaded.

And there are also respective error messages in the syslog:
```
t=2021-02-11T17:37:34+0100 lvl=eror msg="timeout error - you can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=1 uname= error="timeout error - you can set timeout in seconds with &timeout url parameter"
t=2021-02-11T17:37:34+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/V2fSBzzmz/sosy-lab-machines status=500 remote_addr=2001:... time_ms=63144 size=747 referer=
t=2021-02-11T17:37:48+0100 lvl=eror msg="timeout error - you can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=1 uname= error="timeout error - you can set timeout in seconds with &timeout url parameter"
t=2021-02-11T17:37:48+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/EcvCGIxiz/car-fuel status=500 remote_addr=2a01:... time_ms=62625 size=1784 referer=
t=2021-02-11T17:38:51+0100 lvl=eror msg="timeout error - you can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=1 uname= error="timeout error - you can set timeout in seconds with &timeout url parameter"
t=2021-02-11T17:38:51+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/EcvCGIxiz/car-fuel status=500 remote_addr=2a01:... time_ms=62488 size=1784 referer=
t=2021-02-11T17:39:54+0100 lvl=eror msg="timeout error - you can set timeout in seconds with &timeout url parameter" logger=context userId=0 orgId=1 uname= error="timeout error - you can set timeout in seconds with &timeout url parameter"
t=2021-02-11T17:39:54+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/mhfS9u7mz/dfes25 status=500 remote_addr=2a01:... time_ms=62749 size=1784 referer=
```

(I had seen this briefly previously but attributed it to the overloaded system and then forgotten.)

So I guess a better description of this issue might be that something in Grafana 7.4 breaks image rendering for me and the leaking processes are more like a side effect. This actually also explains the weirdly low CPU usage because nothing is rendered anymore.

> Trying to look at the trace file I unfortunately get an error _failed to parse trace: no EvFrequency event_. Not sure if this due to some error in enabling the trace diagnostics in Grafana - we'll look into this.

Let's try again (maybe it is still useful): [trace.out.zip](https://github.com/grafana/grafana/files/5967121/trace.out.zip)

Is it a problem if I copy a trace file while Grafana is running and it is thus not complete? I am not sure whether I did this before, but now I made sure to stop Grafana correctly before copying the file. (If this is indeed necessary, it could be a good idea to mention this briefly in your docs.)

> Then you can use curl to download profiles:
> 
> ```shell
> curl http://<host>:<profiling port>/debug/pprof/heap > heap1.pprof
> ```

Thanks, this is actually much more convenient for me than using Go and would be a nice addition to your docs.

I downloaded 3 profiles, immediately after a start, after 10 min, and after 20 min: [grafana.pprof.zip](https://github.com/grafana/grafana/files/5967120/grafana.pprof.zip)
(this is actually exactly the same run as the new `trace.out` file).

> In regards to your collected metrics, you might have a look at plotting metrics for __go_memstats_heap__ in use and allocs - should show similar things as collected heap profile, but over time.

No problem (same run as in original post):

![image](https://user-images.githubusercontent.com/2545335/107663743-003ab200-6c8c-11eb-940b-9a75b413077c.png)

It really seems like the main Grafana process indeed does not leak resources.

> **Some questions:**
> 
> * Are you rendering a lot of panels as images using the image renderer plugin?

Right, we do have a script running somewhere that periodically fetches rendered images! I hadn't remembered that.

And when I stop that script, the number of processes stops to grow (no other users are currently requesting rendered images and no alerts are failing). And of course, as soon as I restart it, the number of processes continues to grow again.

> * How many alerts do you have?

20. Some of them are over lots of series (three-digit number).

> **Would be useful if you could try upgrading again:**

As often as you wish ;-)

> * When shutting down Grafana 7.3.7, do you still have grafana image renderer processes lying around?

No (I guess they would be terminated by systemd anyway?).

> * Collect debug log message/file ([enable debug log level](https://grafana.com/docs/grafana/latest/administration/configuration/#level)) and see if you can find anything interesting, maybe something repeating at high frequency? Please attach and replace any sensitive information.

Sorry for not thinking about this before: [grafana.txt](https://github.com/grafana/grafana/files/5967283/grafana.txt)

This log is actually from a different run than the above traces/profiles, and in the middle of it there is a period of about 5min where I had stopped the image-requested script.

It contains these four lines:

```
t=2021-02-11T18:15:55+0100 lvl=dbug msg="(node:1559) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [process]. Use emitter.setMaxListeners() to increase limit" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-11T18:15:55+0100 lvl=dbug msg="(node:1559) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGINT listeners added to [process]. Use emitter.setMaxListeners() to increase limit" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-11T18:15:55+0100 lvl=dbug msg="(node:1559) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGTERM listeners added to [process]. Use emitter.setMaxListeners() to increase limit" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-11T18:15:55+0100 lvl=dbug msg="(node:1559) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 SIGHUP listeners added to [process]. Use emitter.setMaxListeners() to increase limit" logger=plugins.backend pluginId=grafana-image-renderer
```

> * Try running Grafana 7.4 without the image renderer plugin installed (temporary move it outside grafana plugin directory)

I guess by now it is pretty clear that this should cause Grafana to run fine except for the rendering, and of course this is exactly what happens after removing `/var/lib/grafana/plugins/grafana-image-renderer`. :-)

I now re-read the docs for grafana-image-renderer and noticed that they recommend 16 GB of memory. Just for completeness I'll note that I usually run Grafana successfully with 1 GB of memory (currently the VM has 2 GB), and that there is plenty of free memory after a fresh Grafana start, so it seems unlikely that the failing rendering is related to too little memory.

If there is anything I can do to further debug the image rendering, just tell me and I will attempt to do this tomorrow.

**Comment by torkelo** [comment]
The image renderer needs lots of memory as it uses chrome to capture the image, chrome eats memory like nothing else. Specially it you have a queries that return a lot of data

**Comment by marefr** [comment]
Thanks for the detailed information. I think memory limit might be the problem here as well. 

I would suggest trying to enable these settings to hopefully get more information from chromium:
- https://grafana.com/docs/grafana/latest/administration/configuration/#rendering_verbose_logging
- https://grafana.com/docs/grafana/latest/administration/configuration/#rendering_dumpio

Note that above setting will output a lot of information in the logs. 

Something in addition to consider would be to turn off your custom script that generate images temporarily. Then try render a panel using direct link rendered image manually and see if that works and/or that makes things easier to follow output in the logs.

**Comment by PhilippWendler** [comment]
No problem. Here is a log with level debug, both `rendering_verbose_logging` and `rendering_dumpio` set to `true`, and a single (failed) request to direct link rendered image between Grafana start and shutdown: 
[grafana2.txt](https://github.com/grafana/grafana/files/5970097/grafana2.txt)

The following lines of this log contain either `chrome`, `image`, or `render`:
```
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Loading plugin" logger=plugins path=/var/lib/grafana/plugins/grafana-image-renderer/plugin.json
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=grafana-image-renderer isBackend=false
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Plugin is unsigned" logger=plugins id=grafana-image-renderer
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Found plugin" logger=plugins id=grafana-image-renderer signature=unsigned hasRoot=false
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Non-valid plugin Signature" logger=plugins pluginID=grafana-image-renderer pluginDir=/var/lib/grafana/plugins/grafana-image-renderer state=unsigned
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Attempting to add plugin" logger=plugins id=grafana-image-renderer
t=2021-02-12T07:39:11+0100 lvl=info msg="Registering plugin" logger=plugins id=grafana-image-renderer
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Registering backend plugin" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Backend plugin registered" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:11+0100 lvl=dbug msg="Successfully added plugin" logger=plugins id=grafana-image-renderer
t=2021-02-12T07:39:14+0100 lvl=dbug msg="Plugins: Adding route" logger=http.server route=/public/plugins/grafana-image-renderer dir=/var/lib/grafana/plugins/grafana-image-renderer
t=2021-02-12T07:39:14+0100 lvl=dbug msg="starting plugin" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 args=[/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64]
t=2021-02-12T07:39:14+0100 lvl=dbug msg="plugin started" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=2406
t=2021-02-12T07:39:14+0100 lvl=dbug msg="waiting for RPC address" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64
t=2021-02-12T07:39:14+0100 lvl=dbug msg="Found old rendered image to delete" logger=cleanup deleted=48 kept=7288
t=2021-02-12T07:39:14+0100 lvl=dbug msg="Browser initialized" logger=plugins.backend pluginId=grafana-image-renderer config="map[args:[--no-sandbox] chromeBin:/var/lib/grafana/plugins/grafana-image-renderer/chrome-linux/chrome clustering:map[maxConcurrency:5 mode:browser] deviceScaleFactor:1 dumpio:true height:500 ignoresHttpsErrors:false maxDeviceScaleFactor:3 maxHeight:3000 maxWidth:3000 mode:default verboseLogging:true width:1000]"
t=2021-02-12T07:39:14+0100 lvl=dbug msg= logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:14+0100 lvl=dbug msg="DevTools listening on ws://127.0.0.1:33301/devtools/browser/8af1ddce-0b54-4a1f-8656-0fc6c924b956" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:14+0100 lvl=dbug msg="Using browser version" logger=plugins.backend pluginId=grafana-image-renderer browserVersion=HeadlessChrome/79.0.3945.0
t=2021-02-12T07:39:14+0100 lvl=dbug msg="using plugin" logger=plugins.backend pluginId=grafana-image-renderer version=2
t=2021-02-12T07:39:21+0100 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/V2fSBzzmz/sosy-lab-machines?orgId=1&var-hostname=$REDACTED&from=1613108267553&to=1613111867553&panelId=5&width=1000&height=500&tz=Europe%2FBerlin"
t=2021-02-12T07:39:27+0100 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"http://::1:3000/d-solo/V2fSBzzmz/sosy-lab-machines?orgId=1&var-hostname=$REDACTED&from=1613108267553&to=1613111867553&panelId=5&width=1000&height=500&tz=Europe%2FBerlin&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/mFSziAuq8jiwXzSA4ODq.png\" renderKey:\"WOmQYc9Zano0DgseoSmvWjNgpCQZFhbP\" domain:\"::1\" timeout:60 timezone:\"Europe/Berlin\" headers:<key:\"Accept-Language\" value:<values:\"de-DE,de;q=0.8,en-US;q=0.5,en;q=0.3\" > > "
t=2021-02-12T07:39:27+0100 lvl=dbug msg="Render request received" logger=plugins.backend pluginId=grafana-image-renderer url="http://::1:3000/d-solo/V2fSBzzmz/sosy-lab-machines?orgId=1&var-hostname=$REDACTED&from=1613108267553&to=1613111867553&panelId=5&width=1000&height=500&tz=Europe%2FBerlin&render=1"
t=2021-02-12T07:39:27+0100 lvl=dbug msg= logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:27+0100 lvl=dbug msg="DevTools listening on ws://127.0.0.1:41073/devtools/browser/6a533e9b-654c-4242-ab7f-184b283007ba" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:27+0100 lvl=dbug msg="[0212/073927.714361:WARNING:ipc_message_attachment_set.cc(49)] MessageAttachmentSet destroyed with unconsumed attachments: 0/1" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:27+0100 lvl=dbug msg="[0212/073927.714368:ERROR:command_buffer_proxy_impl.cc(124)] ContextResult::kTransientFailure: Failed to send GpuChannelMsg_CreateCommandBuffer." logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:27+0100 lvl=dbug msg="Setting viewport for page" logger=plugins.backend pluginId=grafana-image-renderer width=1000 height=500 deviceScaleFactor=1
t=2021-02-12T07:39:27+0100 lvl=dbug msg="Setting cookie for page" logger=plugins.backend pluginId=grafana-image-renderer renderKey=WOmQYc9Zano0DgseoSmvWjNgpCQZFhbP domain=::1
t=2021-02-12T07:39:28+0100 lvl=dbug msg="[0212/073928.174991:ERROR:validation_errors.cc(76)] Invalid message: VALIDATION_ERROR_DESERIALIZATION_FAILED (network.mojom.CookieManager.3 )" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:39:28+0100 lvl=dbug msg="[0212/073928.175039:WARNING:network_service.cc(202)] Mojo error in NetworkService:Validation failed for network.mojom.CookieManager.3  [VALIDATION_ERROR_DESERIALIZATION_FAILED (network.mojom.CookieManager.3 )]" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:40:29+0100 lvl=info msg="Rendering timed out" logger=rendering renderer=plugin
t=2021-02-12T07:40:30+0100 lvl=eror msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/render/d-solo/V2fSBzzmz/sosy-lab-machines status=500 remote_addr=2001:4ca0:4000:5f::1000 time_ms=68789 size=745 referer=
t=2021-02-12T07:40:42+0100 lvl=dbug msg="Stopping plugin" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:40:42+0100 lvl=eror msg="Render request failed" logger=plugins.backend pluginId=grafana-image-renderer url="http://::1:3000/d-solo/V2fSBzzmz/sosy-lab-machines?orgId=1&var-hostname=$REDACTED&from=1613108267553&to=1613111867553&panelId=5&width=1000&height=500&tz=Europe%2FBerlin&render=1" error="Error: Protocol error: Connection closed. Most likely the page has been closed."
t=2021-02-12T07:40:44+0100 lvl=warn msg="plugin failed to exit gracefully" logger=plugins.backend pluginId=grafana-image-renderer
t=2021-02-12T07:40:44+0100 lvl=dbug msg="plugin process exited" logger=plugins.backend pluginId=grafana-image-renderer path=/var/lib/grafana/plugins/grafana-image-renderer/plugin_start_linux_amd64 pid=2406 error="signal: killed"
t=2021-02-12T07:40:44+0100 lvl=dbug msg="Plugin stopped" logger=plugins.backend pluginId=grafana-image-renderer
```

**Comment by marefr** [comment]
Thanks. Looks like image renderer is trying to set the cookie domain to `::1` and that fails. Seems related to https://github.com/grafana/grafana/issues/30930 as you refer to in the description

**Comment by PhilippWendler** [comment]
Indeed! After changing `http_addr` from `::1` to the empty value, the image rendering works. Thanks!

The value `::` (IPv6 equivalent to 0.0.0.0) also lets it fail (as expected, I guess).

So, if #30930 is fixed and I can change my config back to `[::1]`, this would work for me, but if the `::1`-like notation is going to remain valid, I guess it needs to be normalized somewhere.

Furthermore, it might be good to improve the handling of the image rendering somehow such that failing to renderer would not result in leaking processes and memory consumption.

**Comment by aknuds1** [comment]
@marefr why does the image renderer require IP addresses to be enclosed in square brackets? It's not standard, as you can see on [Wikipedia](https://en.wikipedia.org/wiki/IPv6_address#Representation) for example. It's only necessary to put square brackets around an IPv6 address when you combine it with a port, where colon is the separator (f.ex. `[::1]:8000`).

I.e., I think (please point out if I'm mistaken) that the image renderer should support Grafana being configured with an IPv6 address without square brackets around it.

**Comment by marefr** [comment]
I guess it's the chromium browser not supporting setting a cookie domain to `::1` without brackets

**Comment by PhilippWendler** [comment]
Note that this is not really fixed in general. Yes, it is possible to use `[::1]` again in Grafana 7.4.2, and this will work fine. So I am happy, thanks!

However, if one uses `http_addr = ::1` in the config, this will seem to work fine at first, but will still break direct rendered images and leak rendering processes. I also tried this with grafana-image-renderer 2.0.1. So you might still want to improve the handling of `::1`.

**Comment by aknuds1** [comment]
Agree with @PhilippWendler that the handling of `::1` should be fixed.
