### ISSUE TITLE
Charts glitches: white and gray triangles 

### ISSUE THREAD

**Issue by morigs** [grafana/grafana#31148]
![ezgif com-gif-maker](https://user-images.githubusercontent.com/13474134/107667196-66313480-6ca0-11eb-8035-0b5f86f5799f.gif)

When continuously change time range (one day, then next etc) sometimes randomly charts changes shape (become filled instead of gradient) and white triangles appear. When trying to select new time range using mouse some madness occur 🤣 

Reloading page, remove all site data and cookie doesn't help (but opening in incognito mode does)

There are no error or any other logs in console. The bug is independent of data, it remains even when `No data` appears

**Environment**:
- Grafana version:  v6.4.2 (443a0ba)
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker official image (k8s)
- User OS & Browser: Windows 10 Pro 20H2 (19042.746); MS Edge 88.0.705.63
- Grafana plugins: Alert List, Azure Monitor, Bar Gauge, CloudWatch, Dashboard list, Elasticsearch, Gauge, Getting Started, Graph, Graphite, Heatmap, InfluxDB, Logs, Loki, Microsoft SQL Server, MySQL, OpenTSDB, Plugin list, PostgreSQL, Prometheus, SingleStat, Stackdriver, Table, TestData DB, Text

**Comment by torkelo** [comment]
No other reports like this , and your Grafana version being very old this leads me to think this is something related your browser , maybe some extension? Try upgrading Grafana , try incognito mode , if that works it probably is a browser extension.
