### ISSUE TITLE
[Feature request]: Add advanced variable format to get the key instead of the value

### ISSUE THREAD

**Issue by jtommi** [grafana/grafana#31142]
**What would you like to be added**: Variable format to get the key instead of the value

**Why is this needed**:
This could be great for repeated panels.
Take this example https://play.grafana.org/d/000000025/
Imagine the variables were custom defined as follows:
`backend_01 : Backend 1, backend_02 : Backend 2, backend_03 : Backend 3, backend_04 : Backend 4, etc`
In the panel titles I'd like to see Backend x, not backend_x.
This could be easily done with the advanced formatting, e.g. ${servers:key}

**Comment by philomory** [comment]
This already exists, actually, it's just undocumented. It's `${variable:text}`.

**Comment by jtommi** [comment]
Thanks,
The reversed key/pair is just an error in my description.
Weird that I didn't try the text option, because it's mentioned in the docs, it just doesn't specify that it can be used to get the keys.
