### ISSUE TITLE
Can't change unit in panel

### ISSUE THREAD

**Issue by jsedy7** [grafana/grafana#31141]
**What happened**: Change unit of axes not working correctly. I changed the unit from `short` to `seconds` and no change was made in the graph. No selected unit will be reflected in the graph.  I tried both Y axes (right/left).

**What you expected to happen**: I need to change unit in my graph.

**How to reproduce it (as minimally and precisely as possible)**:  I tried reproduce my issue using another Grafana, but unsuccessfully. 

![grafana](https://user-images.githubusercontent.com/8748774/107646725-9239bf00-6c7a-11eb-9e6e-85dd4efc1ee9.gif)

**Anything else we need to know?**:

**Environment**: Docker container
- Grafana version: Grafana v7.4.0 (c2203b9859) (I tried version from master branch and also not working correctly - Grafana v7.5.0-12052pre (bc261a5219))
- Data source type & version: Prometheus 
- OS Grafana is installed on: Docker container (`grafana/grafana`)
- User OS & Browser: MacOS & Firefox or Safari 
- Grafana plugins: Nothing relevant with issue (PieChart)
- Others:

**Comment by torkelo** [comment]
Think this happens if you have unit in the Field tab (our new unified option model)

**Comment by jsedy7** [comment]
Ok, Is there a way to fix that in my dashboard? 🙂
Or will it be better to wait for the repair? 🙂

**Comment by torkelo** [comment]
Of course just clear or use the unit option in the field tab

**Comment by jsedy7** [comment]
> Of course just clear or use the unit option in the field tab

Thank you, It works! 🙂 

At first I couldn't find the field tab but in the end I managed to find to find it. 😅

**Comment by Marooned-MB** [comment]
Any update for that? Field unit seems to overwrite whatever I pick on Axes option. It can't be cleared. I can pick `None` but this still overrides Axes units. I did not find a way to really clear it. It just picks the last selected unit.

**Comment by amirajoodani** [comment]
i have the same issue with grafana 8.5 . how we can resolve it ?

**Comment by mkfink** [comment]
> i have the same issue with grafana 8.5 . how we can resolve it ?

If anyone's still using an old version of Grafana and wants to fix this, you can remove units from the Field tab by clicking your graph's title > Inspect > Panel JSON. Delete the line `"unit": "whatever",` that should appear near the top inside `"fieldConfig": {...}`.
