### ISSUE TITLE
Failure to send a password reset email is not raised to user

### ISSUE THREAD

**Issue by bclermont** [grafana/grafana#31155]
**What happened**:

A user wanted to reset a password, filled the username click reset and got a positive feed back on the web ui:

```
Welcome to Grafana
Built better together
An email with a reset link has been sent to the email address. You should receive it shortly.
```

But in the logs of grafana server:

```
t=2021-02-12T04:44:08+0000 lvl=eror msg="Async sent email 0 succeed, not send emails: joe@example.com err: Failed to send notification to email addresses: joe@example.com: dial tcp 1.2.3.4:587: connect: connection refused" logger=notifications
```

**What you expected to happen**:

User should get a feedback that don't give them false impression they should look in their inbox, maybe something like `Couldn't send reset link to the email address, please contact your system administrator`

**How to reproduce it (as minimally and precisely as possible)**:

Configure SMTP server to a non working address such as `127.0.0.1`.

**Environment**:

- Grafana version: 7.4.0

**Comment by hugohaggmark** [comment]
I had a look at this today, and parts of this can't really be solved because we send these emails async in a queue in the backend so we don't always receive an error immediately. But I'll make sure we handle the cases when we receive an error.

**Comment by hugohaggmark** [comment]
@grafana/backend-platform I can see that we also support sending emails sync in the backend, but I guess that is not a good option in this case?

**Comment by marefr** [comment]
No because of security. We always want to respond with success to not disclose any information about user found/not found etc.

**Comment by bclermont** [comment]
> not disclose any information about user found/not found etc.

Maybe the success message should be less optimistic to not led users to assume it worked

Maybe something like "If provided information is valid, you will receive an email"

**Comment by hugohaggmark** [comment]
> No because of security. We always want to respond with success to not disclose any information about user found/not found etc.

Oh noes, this means that I should revert my PR then @marefr?

**Comment by hugohaggmark** [comment]
Reverting my PRs. If we're conscious of security in this scenario why do we return an error property with a message like `User not found` from the API @marefr?

**Comment by marefr** [comment]
Not sure what code you refer to. This returns 200 if user is not found https://github.com/grafana/grafana/blob/815603dc195429015678005638e4d4f9f0533d70/pkg/api/password.go#L26
