### ISSUE TITLE
Grafana sending out random alerts

### ISSUE THREAD

**Issue by Bartosz76** [grafana/grafana#31157]
Hello,

I have a problem with Grafana spamming the notification channel members with alerts that violate the alert's rules. It just completely randomly sends out alerts even though the requirements for alerts are not even close to being met.

I have two similar alerts. They are supposed to send out a notification whenever the disk space goes below 10%. It never did, not for a second and yet Grafana totally randomly just sends out notification every two hours or so with the status OK or NO DATA. It just makes no sense and makes the very point of having alerts pointless. Why is it informing me that it's OK or that is has NO DATA? I wanted to be informed whenever the conditions of alerts are met and they have not been met.

<img width="555" alt="grafanaBug1" src="https://user-images.githubusercontent.com/55912424/107739549-6580b880-6d09-11eb-92d4-0c275499e6ba.png">
<img width="566" alt="grafanaBug2" src="https://user-images.githubusercontent.com/55912424/107739562-6ca7c680-6d09-11eb-90e9-0540a1e9b8ce.png">
<img width="216" alt="grafanaBug3" src="https://user-images.githubusercontent.com/55912424/107739570-70d3e400-6d09-11eb-86d6-74122fa3be0a.png">

**Comment by nickhalden** [comment]
I think that's a default graft a behavior, it's probably a heartbeat sent to the webhook notifier

**Comment by Bartosz76** [comment]
> I think that's a default graft a behavior, it's probably a heartbeat sent to the webhook notifier

Is there any way I can stop this from happening? I don't want OK nor NO DATA alerts. I set alerts to be sent out whenever the disk space drops below 10. Thus, I'd like to be informed... when the disk space drops below 10. If we get flooded like that with random alerts we run the risk of getting tired of this spam and one day will simply ignore an actual alert.

**Comment by torkelo** [comment]
Your query returns no data randomly, 

Set the option `If no data or all values are null` to Keep last state to ignore this. 

![Screenshot from 2021-02-12 09-19-26](https://user-images.githubusercontent.com/10999/107744740-85b57500-6d13-11eb-87a1-51cc15852465.png)

**Comment by nickhalden** [comment]
Ah I was gonna point out this
