### ISSUE TITLE
syslog garbled due to ansi(?) colour codes

### ISSUE THREAD

**Issue by tokudan** [grafana/grafana#3115]
Grafana does not seem to check where its default output is going and seems to insert colour codes even when there's no terminal on stdout/stderr. The result is hard to filter syslog similar to this:
Oct 31 13:27:01 ashe grafana-server[2621]: 2015/10/31 13:27:01 #033[1;32m[I] Completed /render 500 Internal Server Error in 215.899752ms#033[0m

In my opinion grafana should only output text when stdout/stderr is not a terminal.

**Comment by torkelo** [comment]
fixed in master and in 2.5.0

**Comment by torkelo** [comment]
disable console log formating in grafana.ini
formatting = true
https://github.com/grafana/grafana/pull/2870

**Comment by torkelo** [comment]
https://github.com/ctdk/grafana/blob/d37e18fdcf9ad3965ce7cfd2fb4c4f0665e94aa7/conf/defaults.ini#L228

**Comment by Dieterbe** [comment]
why does this need to be configured by the user? seems simpler if the code would just check if a terminal is attached or not.
it looks like this code may do exactly that: http://rosettacode.org/wiki/Check_output_device_is_a_terminal#Go

**Comment by torkelo** [comment]
yea, I agree this should not have to be a setting, either detect that terminal or have standard ansi default

**Comment by torkelo** [comment]
Changed the default for the console color formating, it is disabled by default now:
https://github.com/grafana/grafana/commit/88d27fe649a0d312c57581237b2ed1fcdb015e78
