### ISSUE TITLE
Should grafana-toolkit consume the local monorepo versions of grafana-ui and grafana-data?

### ISSUE THREAD

**Issue by amcasey** [grafana/grafana#31185]
Right now, it [depends](https://github.com/grafana/grafana/blob/9629dded42e5457266a2448ce5e9851b2bcb6749/packages/grafana-toolkit/package.json#L31) on version `next` of these packages, causing them to be pulled from npm, rather than linked from the local monorepo.  Their dependencies are also pulled down, possibly creating version conflicts with the hoisted dependencies in the repo root.  One consequence is that `@types/slate` is pulled in as both 0.47.1 and 0.47.2, requiring the TypeScript compiler to waste a bunch of time establishing that the types are equivalent across versions.

**Comment by amcasey** [comment]
Looks like having `grafana-toolkit` pull in an old version of `@grafana/ui` was also the only reason `popper.js` was still available.  Probably, the imports of `popper.js` in `packages/grafana-ui` should be updated to `@popperjs/core`?

**Comment by zoltanbedi** [comment]
It should, there is already a pr for that https://github.com/grafana/grafana/pull/30701 I'm not sure about the popper.js though.

**Comment by amcasey** [comment]
@zoltanbedi Thanks!  I looked for an existing issue, but it didn't occur to me to look for a PR.
