### ISSUE TITLE
Issues editing rearranged queries on 7.4.0

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#31184]
- Grafana version: 7.4.0
- Data source type & version: Postgres
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome
- Stat panel

If I have multiple queries in my panel, some duplicated from others, and then I rearrange them, when I go to edit one, things go haywire. Cursor jumps to the very end, some don't show up in the panel, editing one changes a different one...

I know this worked fine on some 7.3.X versions.

**Comment by torkelo** [comment]
thanks for reporting this, fixed by https://github.com/grafana/grafana/pull/31193 , will come in next patch release on wednesday
