### ISSUE TITLE
Copy Invite doesn't work

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#31187]
**What happened**: I clicked the Copy Invite button. Nothing happened.

**What you expected to happen**: Something along the lines of an invitation being copied.

**How to reproduce it (as minimally and precisely as possible)**:

1. In the Configuration menu, click Users.
2. Click Pending Invites.
3. Click Copy Invite.

**Anything else we need to know?**: We have no documentation about what this is supposed to do.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by rin** [comment]
This successfully copies an invitation link to the clipboad in `Grafana v7.5.0-pre`.

**Comment by oddlittlebird** [comment]
And how does one get it off the clipboard?
