### ISSUE TITLE
Data link variable suggestions extend beyond window boundaries in Chrome

### ISSUE THREAD

**Issue by philomory** [grafana/grafana#31192]
**What happened**:

When I type `$` in a data-link entry window, the list of suggested variables extends past the top of the browser window:

![image](https://user-images.githubusercontent.com/200123/107833663-14d48400-6d38-11eb-9759-54a11c7d2eb9.png)

(Note that the light gray area at the top of the screenshot is the bottom of my bookmarks bar, i.e., the top of the rendering area for the page)

I cannot see all of the suggestions, and I cannot scroll the list. I _can_ use the arrow keys to navigate the selection highlight past the top of the visible area and select invisible options, but it does not scroll them into view.

**What you expected to happen**:

I expect to be able to either see all of the suggestions, or at least have a scrollable list.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard
2. Create a fair number of dashboard variables.
3. Create and edit a panel, giving it a query that returns multiple series.
4. Create a data link.
5. In the data link entry window, type a `$`.

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: InfluxDB 2.0, Flux
- OS Grafana is installed on: Alpine Linux (official docker image `grafana/grafana:7.4.1`)
- User OS & Browser: Windows 10, Chrome 88.0.4324.150
- Grafana plugins: None other than the defaults that ship with the base docker image.
- Others:

**Comment by dprokop** [comment]
I think adding max-height contraint to `DataLinkSuggestions` might solve this. react-popper used for positioning the suggestions popover can have problems with posiitoning non-sized elements
