### ISSUE TITLE
Grafana is loading tag multiple times

### ISSUE THREAD

**Issue by tal-ayalon** [grafana/grafana#31199]
**What happened**:
Tagged 5 dashboards with the same tag. added a 'dashboard link' with the same tag. Now Grafana takes ~7 seconds to load new queries (when choosing a new time range)

**What you expected to happen**:
Querying will stay the same

**How to reproduce it (as minimally and precisely as possible)**:
Create multiple dashboards with the same tag, create a 'Dashboard Link' with same name. Save the dashboard and change the time range.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.2.1
- Data source type & version: Prometheus 2.22.1
- OS Grafana is installed on: GCP K8S
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This is fixed in later version

**Comment by tal-ayalon** [comment]
@torkelo In which version this is fixed?

**Comment by torkelo** [comment]
Try latest 7.3.7 or 7.4.1

**Comment by shay-berman** [comment]
@torkelo can you please specify what is the github issue that fix this issue?
so we will check exactly in which version we should upgrade to.

Also will be nice to see what was the issue and how it was solved.

thanks a lot
