### ISSUE TITLE
Time unit from now not updating local time

### ISSUE THREAD

**Issue by shehrozeee** [grafana/grafana#31202]
**What happened**:
![image](https://user-images.githubusercontent.com/33824420/107909509-65a9cf80-6f26-11eb-961b-fdb9e21b06c4.png)
The page was opened 3 days ago but not refreshed (The laptop may have been put to sleep for days in between), (dashboard data is set to update at 10 sec interval)
looks like the local time is not updated.

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/33824420/107909527-71959180-6f26-11eb-9785-16b3d894380c.png)
The page is just opened and its the same data

**How to reproduce it (as minimally and precisely as possible)**:
Not sure about how it can be reproduced. maybe putting the device in sleep mode for 5 10 minutes and checking the page again without refreshing anything.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.3.6 (ea06633c34)
- Data source type & version: MySql 5.7.21
- OS Grafana is installed on: ubuntu 20 lts
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: installed plugins:
grafana-piechart-panel @ 1.6.1

- Others:

**Comment by torkelo** [comment]
Unable to replicate, maybe something with your data / browser? Grafana has no internal clock, it's just using the system/browser time when printing those dates, so either the time in the data is wrong or the browser/system time has not updated. 

Can you check the data?

**Comment by shehrozeee** [comment]
both images are on different systems at almost the same time. (the data is same as you can see the time difference is same too). is it possible that the browser time was not updated ?

**Comment by shehrozeee** [comment]
I`ll try to reproduce it. if I cant, I`ll close it.

**Comment by torkelo** [comment]
> The page was opened 3 days ago but not refreshed (The laptop may have been put to sleep for days in between) 

You need to refresh for new data to be queries and re-visualized
