### ISSUE TITLE
Problem passing templating params via URL with "Refresh on load" enabled

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3120]
Hi, I'm working with Grafana 2.5.

I have a dashboard with templating feature and **Refresh on load** enabled on each templating var with a metric tree like:
`app1.server1.backend{1,3,5}`
`app1.server2.backend{2,4,6}`

The dashboard params are saved to view `app1.server1.backend1`. When I try to load the dasboard with params via URL (to do the render or see the full dashboard): `app1.server2.backend4`, it doesn't do the query correctly and it shows the `backend2` instead the `backend4`. If I'm not wrong, in case that Grafana doesn't find some param on the query, it returns the first that it finds, so in this case, is returning backend2.

**Testing, I disabled Refresh on load and for now, is working fine.**

Is there any problem on the way that Grafana does the query with **Refresh on load** feature activated when it has several templating params?

Thanks for all!

**Comment by torkelo** [comment]
could you show the template variable queries?  Do you have two template variable queries, one for server and one for backend?

**Comment by sbengo** [comment]
Hi @torkelo, thanks for answer.I couldn't answer you earlier:

Actually I have 5 templating params with their respective querys using Graphite. All with **Refresh on load** enabled:
**app** -> `*` ; {app1, app2}
**server** -> `app.*` ; {server1, server2}
**xx** -> `$app.$server.*` ; {xx1, xx2}
**yy** -> `$app.$server.$xx` ; {yy1,yy2}
**backend** -> `$app.$server.$xx.$yy.*` ;

The backends are splited 
app1.server1.xx1.yy1.backend{1,3,5}
app1.server1.xx2.yyy2.backend{2,4,6}

The dashboard is saved with `app1.server1.xx1.yy1.backend1` as default template params. When I try to show the **backend4** via URL (`app1.server1.xx2.yy2.backend4`):

`mydashboard?panelId=1&fullscreen&from=...&to=...&var-app=app1&var-server=server2&var-xx=xx2&var-yy=yy2&var-backend=backend4`

The dashboard loads on template variables the backend2 instead the backend4.

Thanks!

**Comment by torkelo** [comment]
sounds like this issue then: 
https://github.com/grafana/grafana/issues/2722

Variables that depend on each other needs to update in the correct order

**Comment by sbengo** [comment]
Thanks for the answer @torkelo,

As I said, testing, it's working with "Refresh on load" disabled!
