### ISSUE TITLE
Cannot read property 'stroke' of undefined - Time Series Visualization

### ISSUE THREAD

**Issue by lux4rd0** [grafana/grafana#31203]
When using the time series beta visualization - sometimes the initial load or a refresh of the panel will produce a red error message: "Cannot read property 'stroke' of undefined"

![Cannot read property 'stroke' of undefined](https://user-images.githubusercontent.com/30187533/107911309-ec0fe280-6f21-11eb-890b-437d74e876ed.png)

Edit - a little more information with Safari - "undefined is not an object (evaluating 'a.getSeries()[r].stroke')"

![undefined is not an object (evaluating 'a getSeries() r stroke')](https://user-images.githubusercontent.com/30187533/107912279-dbf90280-6f23-11eb-876d-d9d4327709a5.png)

**What you expected to happen**:

Graph without the error:

![expected results](https://user-images.githubusercontent.com/30187533/107911401-224d6200-6f22-11eb-8a4d-b6ad2df1813c.png)

**How to reproduce it (as minimally and precisely as possible)**:

Refreshing the entire Dashboard resolves the issue (sometimes).

**Anything else we need to know?**:

Only happening so far testing with 1 of several panels on the dashboard. Similar queries, similar data. If I switch to the "graph" visualization instead of the beta "Time series" visualization, I don't get the error.

Using developer tools in Chrome, I get the following output:

![Screen Shot 2021-02-15 at 12 24 47 AM](https://user-images.githubusercontent.com/30187533/107912564-57f34a80-6f24-11eb-9e26-8e39515d8d09.png)

**Environment**:
- Grafana version: - Grafana Enteprise v7.4.1 (07649d1313)
- Data source type & version: Loki
- OS Grafana is installed on: Centos 7 (Docker container)
- User OS & Browser: Mac / Chrome Version 88.0.4324.150 (Official Build) (x86_64), Mac / Safari Version 14.0.3 (16610.4.3.1.4)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you share a panel json? and the query data (from in inspect drawer)?

**Comment by lux4rd0** [comment]
Sure!

Panel JSON:

```
{
  "datasource": "Loki - new array",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 3,
        "fillOpacity": 60,
        "gradientMode": "none",
        "spanNulls": true,
        "showPoints": "never",
        "pointSize": 5,
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "graph": false,
          "legend": false
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "mappings": [],
      "unit": "fahrenheit"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "High"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-purple",
              "mode": "fixed"
            }
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "Low"
        },
        "properties": [
          {
            "id": "color",
            "value": {
              "fixedColor": "dark-blue",
              "mode": "fixed"
            }
          }
        ]
      }
    ]
  },
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "id": 2,
  "interval": "$Group",
  "options": {
    "tooltipOptions": {
      "mode": "multi"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    },
    "graph": {}
  },
  "pluginVersion": "7.4.0",
  "targets": [
    {
      "expr": "avg by (obs_Air_Temperature) (max_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature [$__interval])) * 9/5 + 32",
      "legendFormat": "High",
      "refId": "A"
    },
    {
      "expr": "avg by (obs_Air_Temperature) (min_over_time({app=\"weatherflow\"} | json | type=\"obs_st\" |json | json obs_Air_Temperature=\"obs[0][7]\" | unwrap obs_Air_Temperature [$__interval])) * 9/5 + 32",
      "hide": false,
      "legendFormat": "Low",
      "refId": "B"
    }
  ],
  "timeFrom": null,
  "title": "Air Temperature",
  "type": "timeseries"
}
```

Query data:

`{
  "request": {
    "url": "api/datasources/proxy/60/loki/api/v1/query_range?direction=BACKWARD&limit=2178&query=avg%20by%20(obs_Air_Temperature)%20(max_over_time(%7Bapp%3D%22weatherflow%22%7D%20%7C%20json%20%7C%20type%3D%22obs_st%22%20%7Cjson%20%7C%20json%20obs_Air_Temperature%3D%22obs%5B0%5D%5B7%5D%22%20%7C%20unwrap%20obs_Air_Temperature%20%5B4h%5D))%20*%209%2F5%20%2B%2032&start=1613109600000000000&end=1613455200000000000&step=14400",
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {},
          "values": [
            [
              1613152800,
              "18.392000000000003"
            ],
            [
              1613167200,
              "23.846"
            ],
            [
              1613181600,
              "17.906"
            ],
            [
              1613196000,
              "9.625999999999998"
            ],
            [
              1613210400,
              "6.440000000000001"
            ],
            [
              1613224800,
              "4.298000000000002"
            ],
            [
              1613239200,
              "10.741999999999997"
            ],
            [
              1613253600,
              "12.704"
            ],
            [
              1613268000,
              "10.814"
            ],
            [
              1613282400,
              "4.459999999999997"
            ],
            [
              1613296800,
              "0.46399999999999864"
            ],
            [
              1613311200,
              "0.4819999999999993"
            ],
            [
              1613325600,
              "9.212"
            ],
            [
              1613340000,
              "9.716000000000001"
            ],
            [
              1613354400,
              "4.82"
            ],
            [
              1613368800,
              "2.2099999999999973"
            ],
            [
              1613383200,
              "-0.30999999999999517"
            ],
            [
              1613397600,
              "-0.13000000000000256"
            ],
            [
              1613412000,
              "1.274000000000001"
            ]
          ]
        }
      ],
      "stats": {
        "summary": {
          "bytesProcessedPerSecond": 82879364,
          "linesProcessedPerSecond": 527017,
          "totalBytesProcessed": 18955455,
          "totalLinesProcessed": 120535,
          "execTime": 0.228711395
        },
        "store": {
          "totalChunksRef": 277,
          "totalChunksDownloaded": 277,
          "chunksDownloadTime": 0.024707954,
          "headChunkBytes": 0,
          "headChunkLines": 0,
          "decompressedBytes": 18780962,
          "decompressedLines": 119382,
          "compressedBytes": 2126202,
          "totalDuplicates": 0
        },
        "ingester": {
          "totalReached": 1,
          "totalChunksMatched": 1,
          "totalBatches": 0,
          "totalLinesSent": 0,
          "headChunkBytes": 49205,
          "headChunkLines": 358,
          "decompressedBytes": 125288,
          "decompressedLines": 795,
          "compressedBytes": 14504,
          "totalDuplicates": 0
        }
      }
    }
  }
}`

**Comment by torkelo** [comment]
Strange, unable to replicate. Do you get this problem consistently?

**Comment by dprokop** [comment]
I've also tested this against the master and 7.4.1 version, both in Chrome and Safari, and could not get a reproduction.

**Comment by lux4rd0** [comment]
Thanks for reviewing @torkelo and @dprokop - I've pushed out this dashboard so that you can hit it yourself. Since it's intermittent on when it happens, I've outlined a few steps to hopefully have you get to a place to see it yourself:

https://grafana.lux4rd0.com/d/lux4rd0labs_weatherflow_loki_01/weatherflow-overview-7-day-high-low

Once on the dashboard, you can try to keep refreshing the page - but I've rarely seen that produce the error. What I have seen kind of push the issue is changing the "Group By" drop down variable:

![group_by](https://user-images.githubusercontent.com/30187533/108084440-cc6bdd80-7039-11eb-9f20-23965c12a76f.png)

From the default to any other setting.

It'll usually pop in the error message. Once you get the error - changing the "Group By" to another number never removes the error message. Only a refresh of the dashboard (browser refresh) will (most of the time) get you the expected panel.

That being said, the existence of the "Group By" variable doesn't seem to be specifically the cause of the error hitting the URL with the embedded variable doesn't immediately cause the issue either (still intermittent) - https://grafana.lux4rd0.com/d/lux4rd0labs_weatherflow_loki_01/weatherflow-overview-7-day-high-low?orgId=1&var-Group=6h - and changing the drop down doesn't always cause the error.

Another interesting tidbit is that using the "Refresh Dashboard" has yet to produce the error message for me. But again, once the error message happens - no changing of the "Group By" or changing the time period resolves the issue. Only a Browser Refresh of the page clears it out.

If you can view the dashboard linked above, hopefully you'll be able to see some of the JS errors:

uPlot.esm.js:73 

```
	else {
		for (let i = _i0; i <= _i1; i++) {
			if (data[i] != null) {
				_min = min(_min, data[i]);
				_max = max(_max, data[i]);
			}
		}
	}
```

react-dom.production.min.js:216 

`function Mi(a,b){try{var c="",d=b;do c+=Qa(d),d=d.return;while(d);var e=c}catch(f){e="\nError generating stack: "+f.message+"\n"+f.stack}return{value:a,source:b,stack:e}}function Ni(a,b){try{console.error(b.value)}catch(c){setTimeout(function(){throw c;})}}var Oi="function"===typeof WeakMap?WeakMap:Map;function Pi(a,b,c){c=zg(-1,c);c.tag=3;c.payload={element:null};var d=b.value;c.callback=function(){Qi||(Qi=!0,Ri=d);Ni(a,b)};return c}`

One last thing I just discovered - which might help. The panel has two queries - _if I hide either of them, I don't get the intermittent error._

Thanks!

**Comment by dprokop** [comment]
@lux4rd0 thanks so much for the effort. Would there  be a chance you reproduced this using the latest nightly build  https://grafana.com/grafana/download/7.5.0-11263pre?

Yesterday I've merged major time series panel changes that I think should make this error gone.

**Comment by lux4rd0** [comment]
@dprokop Sure - I grabbed "Grafana v7.5.0-11263pre (e0356f7b13)" and deployed it just now. Same issue right away. Same JS log lines and errors.

```
grafana/grafana-enterprise-dev:7.5.0-11263pre

Uncaught TypeError: Cannot read property '1' of undefined - uPlot.esm.js:73
TypeError: Cannot read property 'stroke' of undefined - react-dom.production.min.js:216
```

**Comment by dprokop** [comment]
Ok @lux4rd0, I'll try coming with a remedy tomorrow! :)

**Comment by Schrolli91** [comment]
I have the exact same problem as mentioned in the initial post.
Mostly if i zoom into the graph, data is gone with the error `Cannot read property 'stroke' of undefined`.
Page refresh will fix it.
