### ISSUE TITLE
Grafana 7.4.1: Local data source specific variables / macros show up as unknown variables 

### ISSUE THREAD

**Issue by R-Studio** [grafana/grafana#31212]
**What happened**:
- All my Dashboards with Influx (InfluxQL) and that uses the Grafana global Variable "$timeFilter" are not working anymore.

**What you expected to happen**:
- Grafana knows this global variable and the query to my InfluxDB is working.

**How to reproduce it (as minimally and precisely as possible)**:
- Use a datasource InfluxDB v2.x with the query language "InfluxQL"
- Write a query with a WHERE-clause and use the variable $timeFilter (...WHERE $timeFilter..)

**Anything else we need to know?**:
- In the Dashboard settings / variables, Grafana list the "timeFilter" as unknown variables.
- This issue occurs since I upgraded to Grafana 7.4.1 (from Grafana 7.4.0).

**Environment**:
- Grafana version: 7.4.1
- Data source type: InfluxDB (InfluxQL)
- OS Grafana is installed on: Container (Kubernetes)
- User OS & Browser: Windows & Chrome

**Comment by torkelo** [comment]
Strange, unable to replicate https://play.grafana.org/d/000000002/influxdb-templated?editPanel=1&orgId=1 

$timeFilter is not a global variable, but a specific InfluxDB macro variable.

**Comment by torkelo** [comment]
Can you show the panel json, raw query? and what's your data source settings?

**Comment by R-Studio** [comment]
@torkelo thanks for your reply. Funny is your query is working but the variable "timeFilter" is also shown as unknown variables in the Dashboard settings:
![image](https://user-images.githubusercontent.com/7498854/107936109-8869d180-6f82-11eb-8fb3-f915fbfbd031.png)

**Panel JSON**
```
{ 
  "datasource": "InfluxDB v2 (InfluxQL)", 
  "description": "DO NOT REMOVE OR RENAME THIS PANEL!\nSource: VM asset infos from CMDB (PowerShell-Script on ScriptRunner", 
  "fieldConfig": { 
    "defaults": { 
      "custom": { 
        "align": null, 
        "filterable": true 
      }, 
      "thresholds": { 
        "mode": "absolute", 
        "steps": [ 
          { 
            "color": "green", 
            "value": null 
          } 
        ] 
      }, 
      "mappings": [], 
      "color": { 
        "mode": "thresholds" 
      } 
    }, 
    "overrides": [ 
      { 
        "matcher": { 
          "id": "byName", 
          "options": "maintenancewindowstart" 
        }, 
        "properties": [ 
          { 
            "id": "custom.width", 
            "value": null 
          } 
        ] 
      } 
    ] 
  }, 
  "gridPos": { 
    "h": 1, 
    "w": 19, 
    "x": 5, 
    "y": 0 
  }, 
  "id": 23763571993, 
  "options": { 
    "showHeader": true, 
    "sortBy": [ 
      { 
        "desc": false, 
        "displayName": "customer" 
      } 
    ] 
  }, 
  "pluginVersion": "7.4.1", 
  "targets": [ 
    { 
      "groupBy": [ 
        { 
          "params": [ 
            "$__interval" 
          ], 
          "type": "time" 
        }, 
        { 
          "params": [ 
            "null" 
          ], 
          "type": "fill" 
        } 
      ], 
      "measurement": "asset_hyperv_local", 
      "orderByTime": "ASC", 
      "policy": "default", 
      "query": "SELECT * FROM \"$rp\".\"asset_vm_cmdb\" WHERE $timeFilter AND \"customer\" =~ /^$customer$/ GROUP BY \"id\" ORDER BY time desc limit 1", 
      "rawQuery": true, 
      "refId": "A", 
      "resultFormat": "table", 
      "select": [ 
        [ 
          { 
            "params": [ 
              "value" 
            ], 
            "type": "field" 
          }, 
          { 
            "params": [], 
            "type": "mean" 
          } 
        ] 
      ], 
      "tags": [] 
    } 
  ], 
  "timeFrom": null, 
  "timeShift": null, 
  "title": "Base Query", 
  "transformations": [ 
    { 
      "id": "organize", 
      "options": { 
        "excludeByName": { 
          "id": true 
        }, 
        "indexByName": { 
          "Time": 0, 
          "costcenter": 4, 
          "cpucount": 12, 
          "customer": 5, 
          "customershort": 6, 
          "description": 7, 
          "dscconfiguration": 8, 
          "fqdn": 9, 
          "gpucount": 10, 
          "hardware": 11, 
          "hypervisor": 14, 
          "id": 1, 
          "location": 15, 
          "maintenancewindowend": 16, 
          "maintenancewindowstart": 17, 
          "orgunit": 18, 
          "os": 19, 
          "owner": 20, 
          "patchday": 21, 
          "patchwave": 22, 
          "patchweek": 23, 
          "plusservice": 24, 
          "ram": 13, 
          "recid": 25, 
          "sla": 26, 
          "status": 27, 
          "storageprofile": 28, 
          "stroageqospolicy": 29, 
          "subscriptionid": 30, 
          "subscriptionname": 31, 
          "updateallowed": 32, 
          "vm": 2, 
          "vmgen": 33, 
          "vmid": 3, 
          "vmmid": 34, 
          "vmname": 35, 
          "vmtag": 36, 
          "vmtype": 37 
        }, 
        "renameByName": {} 
      } 
    } 
  ], 
  "type": "table" 
} 
```

**Raw query:**
```
SELECT * FROM "$rp"."asset_vm_cmdb" WHERE $timeFilter AND "customer" =~ /^$customer$/ GROUP BY "id" ORDER BY time desc limit 1
```


**Datasource settings:**
![image](https://user-images.githubusercontent.com/7498854/107936864-75a3cc80-6f83-11eb-9f57-4503ba132264.png)

**Comment by R-Studio** [comment]
@torkelo right now I noticed not the $timeFilter is the problem but I think the ${__from} and to ${__from} in my template variable query:
`SELECT DISTINCT("customer") FROM "asset_vm_cmdb" WHERE "time" > (${__from} * 1000000) - 24h AND "time" < (${__to} * 1000000)`

**Comment by torkelo** [comment]
```
SELECT DISTINCT("customer") FROM "asset_vm_cmdb" WHERE "time" > (${__from} * 1000000) - 24h AND "time" < (${__to} * 1000000)
```

And what does this get interpolated as? (check network tab). 

The issue with unknown variables is a problem with this feature showing local data source specific variables that are there & interpolated by the data source but not dashboard variables, so it's a bug with the warning (should not show)

**Comment by R-Studio** [comment]
@torkelo I don't know what you mean with "interpolated". In the network tab (development settings) I can see the following query:
`SELECT DISTINCT("customer") FROM "asset_vm_cmdb" WHERE "time" > (1613300829480 * 1000000) - 24h AND "time" < (1613387229480 * 1000000)`

_The "* 1000000" is to convert the epoche timestamp from ms to ns._

So If I understand you correct, the issue with unknown variables is only a display bug, right?

**Comment by torkelo** [comment]
yes

**Comment by torkelo** [comment]
Think we need to filter out $timeFilter from these warnings

**Comment by colramos-amd** [comment]
I am working with MongoDB which uses $ in all of its commands (ex $add, $multiply, $group, $project, ...)

All of these commands are flagged as unknown variables which lags my instance **significantly** whenever I access the variables page. Is there any way to get around this? Could be a problematic bug

**Comment by hugohaggmark** [comment]
> I am working with MongoDB which uses $ in all of its commands (ex $add, $multiply, $group, $project, ...)
> 
> All of these commands are flagged as unknown variables which lags my instance **significantly** whenever I access the variables page. Is there any way to get around this? Could be a problematic bug

Aha, good catch @colramos-amd. Can you open a new issue specific to mongodb and remember to add an example dashboard json and grafana version? Unfortunately there is no way to work around this currently, I know that we had some performance challenges previously that should be fixed by https://github.com/grafana/grafana/pull/31811.
