### ISSUE TITLE
Data Source not showing

### ISSUE THREAD

**Issue by danb21t** [grafana/grafana#3121]
Hi guys,

Forgive my inexperience. I have reinstalled Graphite/Grafana a couple of times now as the data sources are not working correctly.
For background info I am introducing this into my environment to help monitor my storage systems. I have been following the NetApp Graphite/Grafana install guide. I have added the Graphite data source into Grafana successfully (tested with the 'Test Connection' button). However when I log into Grafana now I am unable to see any data sources.

I don't have any idea where to look to find the entry that I previously added successfully.

Cheers
Dan

**Comment by torkelo** [comment]
have you tried creating a new dashboard and adding a graph? 
https://www.youtube.com/watch?list=PLDGkOdUX1Ujo3wHw9-z5Vo12YLqXRjzg2&v=sKNZMtoSHN4
