### ISSUE TITLE
LDAP authentication not working

### ISSUE THREAD

**Issue by vatese** [grafana/grafana#3123]
Hello! I configured LDAP for authentication, but when I try to log in, I get no authentication messages and it just gets stuck in the login screen.

This is my ldap.toml file:

verbose_logging = true

[[servers]]

host = "ldapserver.com"

port = 636

use_ssl = true

ssl_skip_verify = true

search_filter = "(uid=%s)"

search_base_dns = ["OU=Unix,DC=myCompany,DC=com"]

[servers.attributes]
name = "givenName"
surname = "sn"
username = "uid"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "CN=grp_admin"
org_role = "Admin"
org_id = 1

[[servers.group_mappings]]
group_dn = "*"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"

The log returns this:
2015/11/03 12:14:12 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2015/11/03 12:14:12 [I] Database: sqlite3
2015/11/03 12:14:12 [I] Migrator: Starting DB migration
2015/11/03 12:14:12 [I] Login: Ldap enabled, reading config file: /etc/grafana/ldap.toml
2015/11/03 12:14:12 [I] Listen: http://0.0.0.0:3000
2015/11/03 12:14:26 [I] Ldap User Info: (*login.ldapUserInfo)(0xc2081a2150)({
 DN: (string) (len=77) "CN=First Last,OU=XXX,OU=XXX,OU=XXXX,OU=Unix,DC=myCompany,DC=com",
 FirstName: (string) (len=6) "First",
 LastName: (string) (len=6) "Last",
 Username: (string) (len=8) "uid",
 Email: (string) (len=20) "mail",
 MemberOf: ([]string) (len=7 cap=8) {
.........
 }
})

That is all I get, after that it doesn't proceed from the login screen.

Thanks and regards

**Comment by torkelo** [comment]
strange, no one else has reported something like this. The connection to ldap must hang at some point. no idea why.

**Comment by dajose** [comment]
same here...

@vatese did you find the error? 
@torkelo shouldn't grafana report if the ldap hangs at some point?

**Comment by torkelo** [comment]
@dajose yes of course, all ldap errors are logged

**Comment by dajose** [comment]
I didnt mean logged... more like displayed to the user... because current behavior seems that if something fails on ldap (not sure on which step exactly) the UI stays frozen

**Comment by torkelo** [comment]
UI is frozen? Never seen that.  Must be a long timeout for the  connection to ldap, this is the only such report, and not been able to replicate it :(
