### ISSUE TITLE
Logs panel only shows first batch of query results

### ISSUE THREAD

**Issue by afletch** [grafana/grafana#31247]
**What happened**:
When querying a Loki data source and the result is split over multiple objects (i.e. response.data.result is an array or objects - see image attached below), the logs panel only shows the results from the first item in the array. This same limitation applies to the 'data' tab of the query inspector, where this only shows the first item in the results array.

**What you expected to happen**:
All items in the result array should be shown.

**How to reproduce it (as minimally and precisely as possible)**:
Query a (Loki?) data source with a stream query and the results to be displayed in a Log panel, where you know there will be a number of different labels (this may also require a parser expression) resulting in a number of results objects returned.

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: Loki 2.1.0
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS 10.15 / FireFox / Chrome
- Grafana plugins: Logs panel

![image](https://user-images.githubusercontent.com/1830538/108079359-a4df3a00-7066-11eb-966d-6ad7c540f5de.png)

**Comment by aocenas** [comment]
@afletch Thanks for the report, can you post the query you run that can be user to reproduce this?

**Comment by afletch** [comment]
> @afletch Thanks for the report, can you post the query you run that can be user to reproduce this?

`{filename="/var/log/apache2/error_log"} |= "client " | regexp "client (?P<addr>[0-9a-f:.]{6,})]" | addr="$ipaddr"`
$ipaddr is a value set in a dash variable, in this instance an IPv4 address.

The data in Loki that is being targetted and returned has sufficient variations in the labels that there are 4 objects in the results (e.g. in my data, variations in the httpcode label)

I had a second thought and checked with a slightly different time period and now realise that while the Data tab in Inspect Query is indeed only showing the first of the results objects as I originally described, the Logs panel is actually showing data time-ordered from them all, _however_, the Logs panel is only showing 1000 lines despite the max data points being set to 4000 and there being well over 1000 lines being returned in the query from Loki (my earlier assumption these were the same issue came from the coincidence that my first result object had 1000 values).

Therefore I believe there are two issues here:
1. Data tab only shows first object of query results
2. Logs panel doesn't respect the max data points value when displaying the results, instead limiting to 1000.

**Comment by ivanahuckova** [comment]
@afletch thank you so much for all of the details and help. 🙏 Very appreciated! I have created a fix for **Logs panel doesn't respect the max data points value when displaying the results, instead limiting to 1000** and separate issue for **Data tab only shows first object of query results**.
