### ISSUE TITLE
Range picker not working with Azure monitor

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#31255]
**What happened**: After connecting to Azure monitor data source, choose "Azure Log analytics", write query and click run. Changing range picker does not change the actual time range the query is executing. For example, choose "Last 5 minutes" and "Last 7 days" gives the same count while executing the query on Azure portal gives different counts.

**What you expected to happen**: Change range picker should result in different results.

**How to reproduce it (as minimally and precisely as possible)**: Change range picker does not change result.

**Anything else we need to know?**:

**Environment**: windows 10
- Grafana version: 7.3.7
- Data source type & version: Azure monitor
- OS Grafana is installed on: 
- User OS & Browser: Chrome/Firefox
- Grafana plugins: Azure monitor
- Others:

**Comment by joshhunt** [comment]
Hi @shuotli, thanks for reporting. Can you provide an example query that replicates this?

I just tried on v7.3.7 (1e261642f4) with the following query

```kusto
Perf
| where $__timeFilter(TimeGenerated) // Make sure you're using this filter + macro
| where CounterName == "% Processor Time"
| where ObjectName == "Processor"
| summarize avg(CounterValue) by bin(TimeGenerated, 5m), Computer, _ResourceId
| order by TimeGenerated asc
```

and it functioned as expected - when I updated the range picker the query results updated to show the selected range

**Comment by shuotli** [comment]
> Hi @shuotli, thanks for reporting. Can you provide an example query that replicates this?
> 
> I just tried on v7.3.7 with the following query
> 
> ```
> Perf
> | where $__timeFilter(TimeGenerated) // Make sure you're using this filter + macro
> | where CounterName == "% Processor Time"
> | where ObjectName == "Processor"
> | summarize avg(CounterValue) by bin(TimeGenerated, 5m), Computer, _ResourceId
> | order by TimeGenerated asc
> ```
> 
> and it functioned as expected - when I updated the range picker the query results updated to show the selected range

Sure. I connected to an Azure monitor data source and select "Azure log analytics". I wrote the query "AzureActivity | count".
I can see that the result is always "22228" whether I choose "Last 30 minutes" or "Last 12 hours" or "Last 7 days".
I checked on Azure Portal and the correct count should be 0, 6 and 381 respectively.

**Comment by joshhunt** [comment]
You will need to include a `where` filter to actually limit the results to the period specified by the time picker, like shown in the sample query. The datasource provides a `$__timeFilter(TimeGenerated)` as a shortcut to include the current time period.

Try a query like `AzureActivity | where __timeFilter(TimeGenerated) | count` (where `TimeGenerated` is the date column) which should work.

**Comment by shuotli** [comment]
> You will need to include a `where` filter to actually limit the results to the period specified by the time picker, like shown in the sample query. The datasource provides a `$__timeFilter(TimeGenerated)` as a shortcut to include the current time period.
> 
> Try a query like `AzureActivity | where __timeFilter(TimeGenerated) | count` (where `TimeGenerated` is the date column) which should work.

Thank you for clearing this up. It's working for me as well.
I'm also seeing another issue about Azure monitor plugin. When you choose "Azure log analytics" and switch between workspaces, the table scheme in the editor autocomplete dropdown does not change. I also checked network tab and "loganalyticsazure/<workspace id>/metadata" is not queried when switch workspaces. Should I log a new issue for this?
