### ISSUE TITLE
RPM Packages No Longer Compatible with CentOS/RHEL 5

### ISSUE THREAD

**Issue by RangerRick** [grafana/grafana#3126]
Attempts to install Grafana 2.5.0 on a CentOS or RHEL 5 system fail, because the Grafana RPMs are using a V4 GPG signature (likely built on CentOS 6 or 7) which is only compatible with the RPM version provided with CentOS/RHEL6 or higher:

```
$ sudo rpm -Uvh grafana-2.5.0-1.x86_64.rpm 
error: grafana-2.5.0-1.x86_64.rpm: Header V4 RSA/SHA1 signature: BAD, key ID 3dd18bdd
error: grafana-2.5.0-1.x86_64.rpm cannot be installed
$ # unreadable package with a V4 signature
$ rpm -v --checksig grafana-2.5.0-1.x86_64.rpm 
grafana-2.5.0-1.x86_64.rpm:
    Header V4 RSA/SHA1 signature: BAD, key ID 3dd18bdd
    Header SHA1 digest: OK (7c2787ff7e44137135dc7c3a342bdaa81231d962)
    V4 RSA/SHA1 signature: BAD, key ID 3dd18bdd
    MD5 digest: OK (9381380f7a944746fe252242e627ee4e)
$ # readable package with a V3 signature
$ rpm -v --checksig opennms-16.0.4-0.20151030.onms237.jira.nms.7899.1.noarch.rpm 
opennms-16.0.4-0.20151030.onms237.jira.nms.7899.1.noarch.rpm:
    Header V3 DSA signature: OK, key ID 5b9efd43
    Header SHA1 digest: OK (514ab5f88ea4f0a9d6f9818ecb0502f9a59e3eea)
    MD5 digest: OK (8144ae4884b969c839ff27f8a81d9342)
    V3 DSA signature: OK, key ID 5b9efd43
```

We ran into a similar issue building our OpenNMS RPMs recently when we updated our build system, along with a similar issue where the file checksums and payloads inside the RPM were using newer RPM features like xz compression.

The solution to making RPM packages compatible with older RPM versions is to set a few properties (either on the rpm command-line, using `--define`, or by creating an `~/.rpmmacros` file).  Here is what I have in my `~/.rpmmacros` file for building OpenNMS packages:

```
%_source_filedigest_algorithm 0
%_binary_filedigest_algorithm 0
%_source_payload w0.bzdio
%_binary_payload w0.bzdio
%__gpg_sign_cmd %{__gpg} gpg --batch --no-verbose --force-v3-sigs --no-armor --passphrase-fd 3 --no-secmem-warning -u "%{_gpg_name}" -sbo %{__signature_filename} %{__plaintext_filename}
```

**Comment by torkelo** [comment]
I tried to get that to work with fpm (which is used to build rpms), but could not get it to work. 
Anyhow, if RHEL5 is needed you can always build packages from source:
http://docs.grafana.org/project/building_from_source/

**Comment by RangerRick** [comment]
In the meantime, the workaround is to not validate GPG sigatures on install:

```rpm --nosignature -Uvh grafana-2.5.0-1.x86_64.rpm```
or
```yum --nogpgcheck localinstall grafana-2.5.0-1.x86_64.rpm ```
