### ISSUE TITLE
Grafana sending alerts when alert conditions aren't met

### ISSUE THREAD

**Issue by Bartosz76** [grafana/grafana#31261]
Hello,

I can't wrap my head around whether I am doing something wrong or what is going on in general. I set alerts to inform me when the Disk Space for Kafka drops below 20%. I also set Alerting for no data and errors... and I constantly receive [ALERTING] emails for no reason.
For example around 8:29 AM I received that alert again and you can clearly see on the graph that nothing happened at that time. Also, the message of the email does not contain any error message so it was no error and that status of the email is [ALERTING], not [NO DATA] (when there was no data before, alerts sent had the stats [NO DATA]), so it's just... alerting me even though alerting conditions were never met.
Is this a bug or am I doing something wrong?
<img width="530" alt="iop1" src="https://user-images.githubusercontent.com/55912424/108171537-f4237a00-70fb-11eb-8029-9a3e852cff3c.png">
<img width="451" alt="iop2" src="https://user-images.githubusercontent.com/55912424/108171561-fbe31e80-70fb-11eb-9f6f-378ae6ebd125.png">
<img width="226" alt="iop3" src="https://user-images.githubusercontent.com/55912424/108171580-01d8ff80-70fc-11eb-8df7-e3f48f442701.png">
<img width="613" alt="iop0" src="https://user-images.githubusercontent.com/55912424/108172876-aa3b9380-70fd-11eb-9491-6122bdd23f79.png">
The value on the graph you see is 100%, constantly. It didn't change at all and it just keeps alerting.
And when I click on View Your Alert Rule in the email... It just proves that the alert that has just been sent should not have been sent.
<img width="914" alt="iop6" src="https://user-images.githubusercontent.com/55912424/108173230-2d5ce980-70fe-11eb-96bb-dc87a7e1171c.png">

**Comment by papagian** [comment]
I suspect that the evaluation query returns no data and since `if no data or all values are null` is set to `Alerting`
an Alerting notification is sent.
For getting a NoData notification instead this setting should change to `NoData`.
But for investigating further and verifying it we need:
- the state history from the alert tab
- the server logs during the alert was sent

**Comment by Bartosz76** [comment]
> I suspect that the evaluation query returns no data and since `if no data or all values are null` is set to `Alerting`
> an Alerting notification is sent.
> For getting a NoData notification instead this setting should change to `NoData`.
> But for investigating further and verifying it we need:
> 
> * the state history from the alert tab
> * the server logs during the alert was sent

I misled myslf because my No Data alerts were set to Alerting instead of No Data... Thanks to you pointing that out, my issue was fixed. Thank you. :)
