### ISSUE TITLE
Metrics color change upon manual refresh

### ISSUE THREAD

**Issue by ShalomCohen** [grafana/grafana#3127]
Using grafana 2.5.0, we noticed that manual refresh sometimes change the color of the metrics themselvs. Now I know for a fact that there are no new metrics form refresh to refresh (I'm looking at a dashboard with static amount of metrics), on graphs with 2 or 3 metrics I couldn't see it, but on graphs with 10 metrics or so it's easily reproduced.

**Comment by torkelo** [comment]
what data source are you using? Maybe it is returning them in non deterministic order? Color or (unless specified) determined by the order the TSDB returns them

**Comment by ShalomCohen** [comment]
Just using graphite (version 0.9.10), that was not the case with the previous version of grafana - it started with grafana 2.5.0 - o something must have changed

Shalom

**Comment by torkelo** [comment]
nothing has changed in Grafana for series coloring. But graphite 0.9.10 sounds like a very old version (missing the crucial maxDataPoints feature without it I find Graphite unusable in Grafana because it crashes chrome for long time ranges)

**Comment by ShalomCohen** [comment]
Graphite version or it's stability has nothing to do with the color issue, it is an actual issue with grafana 2.5.0 that should be fixed no matter what version graphite uses.

**Comment by torkelo** [comment]
@ShalomCohen the only reason for the color change would be different order of the returned metrics. Can you capture the the data returned from graphite and investigate?

**Comment by ShalomCohen** [comment]
@torkelo Thanks for the explanation of how grafana associate colors to metrics, this can explain a lot and I just verified that indeed we are getting the metric in different order each refresh to the query on graphite directly.
We recently also moved to a cluster mode of 6 nodes with 2 replicas of the metrics - this mean that every query get sent to multiple machines(and 2 different machines hold the same metric at a time) and the first to respond is the one taken(which also impacts the order obviously).
The question I have is why with auto refresh this does not happen, only when manually clicking the refresh button? Does grafana leverages the auto refresh feature of graphite which happens to keep the order while the button queries everything from scratch?

**Comment by torkelo** [comment]
No auto refresh and manual refresh is exactly  the same.

**Comment by ShalomCohen** [comment]
O.K. I was able to see colors changing with auto-refresh as well (only on graphs with more than 5 metrics, which increase the probability of that happening). So it's implementation limitation for us, thanks a lot for the help.

**Comment by torkelo** [comment]
There are sort functions for graphite that might fix the situation for you

**Comment by ShalomCohen** [comment]
@torkelo Your right, I can see that graphite version 0.9.14(fairly new version) have a function sortByName, we are just on the wrong version of graphite :-(
Thanks for the help.
