### ISSUE TITLE
Slack Notification (Alert) doesn't resolve tag value if the tag key contains hyphen (-)

### ISSUE THREAD

**Issue by DimaRabkin** [grafana/grafana#31284]
We have a query defined in this way:
<img width="868" alt="image" src="https://user-images.githubusercontent.com/8135387/108217352-28b72600-713c-11eb-8438-8338c7ff58cd.png">

The query includes alias that uses two tags: `cluster_name` and `operation-global-id`: 
```
[[tag_cluster_name]] - [[tag_operation-global-id]]
```

This is the graph is looks like:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/8135387/108218484-5fda0700-713d-11eb-9f74-70c717c374c1.png">
As you can see, the alias looks good.

When we define an alert to slack on that query, this is how it looks in the slack channel:
<img width="690" alt="image" src="https://user-images.githubusercontent.com/8135387/108218404-48028300-713d-11eb-8a40-1657a3d5544b.png">
The tag without hyphen was resolved but the one with hyphen wasn't

**Environment**:
- Grafana version: 7.3.2
- Data source type & version: Influx
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: Safari / Slack
- Grafana plugins: Slack Notification

**Comment by Mikeburke14** [comment]
We have the same issue

![Screenshot from 2021-02-25 10-33-29](https://user-images.githubusercontent.com/140795/109141080-39c3f080-7755-11eb-9ab4-e105799d46bc.png)

Tag `[[tag_/junos/rpm/probe-results/probe-test-results/@owner]]`

![slack-plugin-bug](https://user-images.githubusercontent.com/140795/109141102-40526800-7755-11eb-8d5b-17c998a5559a.png)

**Environment**

- Grafana version: v7.4.1 (07649d1313)
- Data source type & version: Influx
- OS Grafana is installed on: Debian GNU/Linux 10 (buster)
- User OS & Browser: Chrome / Slack
- Grafana plugins: Slack Notification

**Comment by Mikeburke14** [comment]
Seems like this didn't fix the other use cases such as tags with `/` and `@` in them, I believe if we use this regex it will work`\[\[([\@\/\w-]+)(\.[\@\/\w-]+)*\]\]*|\$\s*([\@\/\w-]+?)*` but it might be worth aligning the regex with all valid influx tags.

Let me know if I should raise this as its own issue ticket.

**Comment by dsotirakis** [comment]
Hi @Mikeburke14, I am not sure that we _should_ support all special characters, we'll have to check if we want that actually.
@marefr thoughts maybe?

**Comment by Mikeburke14** [comment]
Would it be possible to at least allow `/` and `@` since they are valid and come from the [JTI OpenConfig Telemetry Input Plugin](https://github.com/influxdata/telegraf/blob/06c62f263c79b2ce04cf0d98841e58c51ea90ece/plugins/inputs/jti_openconfig_telemetry/README.md) which is part of the influx Git report?

**Comment by dsotirakis** [comment]
@Mikeburke14 seems like we can do for those at least. Feel free to open an issue. Thanks!

**Comment by Mikeburke14** [comment]
Created, Thanks!
