### ISSUE TITLE
Show actual $__rate_interval (and $interval etc) and offer to expand

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#31293]
They work in explore, but they make very little sense in that context and look confusing.  I'd suggest we sub them for their real (computed) values, as we do for variables.  WDYT?

**Comment by torkelo** [comment]
they are needed for calculating step and in the query, they are used for range vectors, not sure what's different in explore that would make these not useful? the same query mechanics apply

**Comment by davkal** [comment]
@tomwilkie why does it not make sense? If I change the time range, the new interval will still be valid if I'm using the variable.

**Comment by tomwilkie** [comment]
Yeah I guess they do make sense...

But I'm going to stick to "they look confusing" - and they make the queries look more complex than they really are.

One thing I will note: I don't know how to find out what their value is for a given query, and often I want to know. 

Finally they prevent me sharing the queries with others, the $__rate_interval etc are Grafana specific - they can't be pasted in the Prometheus UI.

I'll accept I'm probably a niche user here, but Explore is very much aimed at the "show me the query and allow me to fiddle with it" usecase - and I think making that query easily "fiddle-able" should be part of the process.

**Comment by zoltanbedi** [comment]
I like the idea that we show the computed value of the interval and rate_interval variables in some way in explore. maybe hovering over it shows it in a tooltip or something like that.

**Comment by zoltanbedi** [comment]
Looks like we do this for interval but not for rate_interval. We should make sure that we have the same behaviour.

**Comment by davkal** [comment]
Note that in #33018 what's being expanded is a template variable `$interval`, not our builtin variable `$__interval`.

**Comment by beorn7** [comment]
Not sure what the exact overarching UI principles are, but I like the idea of hovering, showing the value, and then perhaps have a button there to fill in the current value explicitly?

Which is a segue to:
> Finally they prevent me sharing the queries with others, the $__rate_interval etc are Grafana specific - they can't be pasted in the Prometheus UI.

Perhaps we can provide an easy way to get the query in the form it's sent to the data source? (Or perhaps there is already a way?) Could be a button or item in the right-click menu "copy expanded query to clipboard" or something.
