### ISSUE TITLE
Bar gauge panel legend placement

### ISSUE THREAD

**Issue by mxmorin** [grafana/grafana#31294]
**What happened**:
When my query returns several lines, the legend is placed in front of the bars.
When it returns only one line (display name is valued at ${__series.name}), the legend is placed above the bars.

![image](https://user-images.githubusercontent.com/58942529/108242465-3c1ebd00-714d-11eb-84ac-3f3efee86149.png)

Is it possible to have the same placement whatever the return and better, provide a field to set it up ?

**What you expected to happen**:
Legend is place at the same place regardless of the number of lines returned or have a field to set the placement

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome

**Comment by dprokop** [comment]
@mxmorin thanks for this issue. The placement is calculated automatically based on the panel size, hence the differences.

I'm gonna classify this as a feature request for now and see if there is more interest in such a feature. In the meantime- we always welcome contributions from the community, and if you wanted to implement such a feature we are happy to review it!

**Comment by mxmorin** [comment]
Thanks for your response.
I think it should be better to add a panel section to deal with legends in the bar gauge panel. 
Differentiating the management of the legend according to the number of values (legend or displayName) as well as the calculation of the placement are rather obscure.
That's why I will suggeset to add a Show field with the values Always, Never, Multiple values only and another Placement with the values Above, In front, Below in order to manage all cases. 
Unfortunately, I don't have the necessary skills to develop this feature.
