### ISSUE TITLE
How to add a new notification type .

### ISSUE THREAD

**Issue by king3379** [grafana/grafana#31304]
**What would you like to be added**:
How to add a new notification type, as shown in the figure below.

![image](https://user-images.githubusercontent.com/20378015/108310217-fa921e80-71ed-11eb-8191-a52d0da0054c.png)

**Why is this needed**:
I want to know how this is added.
I rummaged through the documents and couldn't find it.

**Comment by torkelo** [comment]
Through the code (backend go code)
