### ISSUE TITLE
Feature Request: Install plugins from other sources on custom Dockerfile.

### ISSUE THREAD

**Issue by sgnsys3** [grafana/grafana#31302]
**What would you like to be added**:
Add ability to install plugins from other sources via GF_INSTALL_PLUGINS when building a docker image.
**Why is this needed**:
You can make the ready-to-use Docker image with plugins from other sources.

For example, I want a Docker image with a Monaca data source plugin.
I can build a Docker image with this command

```bash
docker build \
  --build-arg "GRAFANA_VERSION=7.4.1" \
  --build-arg "GF_INSTALL_PLUGINS=https://github.com/openstack/monasca-grafana-datasource/archive/1.2.1.zip;monasca-grafana-datasource,grafana-clock-panel" \
  -t grafana-custom -f Dockerfile .
```

Refer to this document https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-from-other-sources. 
The GF_INSTALL_PLUGINS environment variable is supported to install plugins from other sources but it only supported when container startup.

Refer to this document https://grafana.com/docs/grafana/latest/installation/docker/#build-with-pre-installed-plugins. 
The GF_INSTALL_PLUGINS build arguments are only supported to install plugins from officials Grafana plugins source.

**Comment by marefr** [comment]
Thanks. What stops you from customizing your Dockerfile to achieve what you want? Have you tried this?

**Comment by sgnsys3** [comment]
I'm already trying to customize my Dockerfile without any problem. but When I read the document I think GF_INSTALL_PLUGINS build argument will support install plugins from other sources like when you start the container.

**Comment by xlson** [comment]
@marefr given that this is supported in the official docker image I think it makes sense to add it to the custom one too.

**Comment by marefr** [comment]
Yeah I guess that makes sense
