### ISSUE TITLE
Inspect data: don't duplicate unit on each row

### ISSUE THREAD

**Issue by lafrech** [grafana/grafana#31319]
Hi. I've been playing with the new timeseries panel and it is a great improvement. It is much more powerful in allowing the user to customize each series display. Congratulations for this, already.

**What would you like to be added**:

I'd like the data display not to duplicate the unit on each row. Actually, I don't mind about the display itself, I'm more concerned with the CSV export.

I'd rather get something like this:

```
Time               Temperature (°C)
2020-01-01 01:00   12.51
2020-01-01 02:00   12.82
```

than this

```
Time               Temperature
2020-01-01 01:00   12.51 °C
2020-01-01 02:00   12.82 °C
```

**Why is this needed**:

The former produces a CSV file that is (slightly) easier to parse and easier to use with a spreadsheet software.

I know I can untick "Formatted data" but then I get timestamps instead of dates. And it would be nice to have the unit in the header anyway.

Or is there another way of achieving this that I missed?

**Comment by torkelo** [comment]
you can remove the unit and export raw data in the inspect drawer. 

There currently is no way to have a unit and not impact the formatting of the values, if you juse want to impact the series name you can use use display name option rename the series to include (°C)

**Comment by lafrech** [comment]
Hi. Thank you for your answer.

> if you just want to impact the series name you can use use display name option rename the series to include (°C)

Sure. Not as practical but I don't mind. The unit in the series name is not really an issue to me and duplicating it in the name wouldn't be that bad.

> you can remove the unit and export raw data in the inspect drawer.

Not sure what you mean.

I can remove the unit from the panel, but it's too bad because it's nice to have it displayed when visualizing it.

I can export raw (as opposed to formatted) data but then the datetimes appear as timestamps.

Is there a way to generate this (without dropping the units from the panel axis in the display)

```
Time               Temperature
2020-01-01 01:00   12.51
2020-01-01 02:00   12.82
```

?

This is the point of my feature request.

If this is feasible already and I didn't find how, then please accept my apologies.

If it is not, then I guess I should interpret your answer as a "wontdo".

I guess I'll either drop the units or Ctrl-H the exported CSV.
