### ISSUE TITLE
Dashboard quota for dashboards includes folders

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#31317]
When the dashboard quota service in Grafana queries the database for a total count it includes both dashboards and folders in the query. This means users cannot create the expected amount of dashboards they want when they have folders. Which is quite confusing for end users.

**Comment by marefr** [comment]
Makes sense :+1: We don't support quotas for folders - is that a potential problem?

Some pointer to the code that needs changes. 
- When creating dashboards the quota is checked here:
https://github.com/grafana/grafana/blob/0e63dfafbeb728255ac918b30b497ce9a11a0228/pkg/api/dashboard.go#L256
- There's a couple database queries executed that just counts all rows of a table:
https://github.com/grafana/grafana/blob/0e63dfafbeb728255ac918b30b497ce9a11a0228/pkg/services/quota/quota.go#L67
https://github.com/grafana/grafana/blob/0e63dfafbeb728255ac918b30b497ce9a11a0228/pkg/services/quota/quota.go#L78
- Need to make it possible to query for count of rows in the dashboard table with filter, e.g. `where is_folder = 0`

**Comment by marefr** [comment]
Talked to Carl about it and it's not super important, but would be nice to fix because it creates some support burden.

**Comment by conorevans** [comment]
Hi @marefr I've had a look and should have a PR ready soon. Can you assign this to me please?

**Comment by marefr** [comment]
@conorevans great. Let us know if you need help.

**Comment by ddorman16** [comment]
heya folks. seen a few users bring this issue up as of late - now that we have thousands of active free users. this question was asked today and i believe this is related https://community.grafana.com/t/quota-reached-grafana-cloud-free/46742

**Comment by marefr** [comment]
@ddorman16 yeah there's a [PR](https://github.com/grafana/grafana/pull/32519) open to address this. We just need to allocate some time to get it merged.

**Comment by ddorman16** [comment]
nice. that's great - thanks. I'll follow that PR.
