### ISSUE TITLE
LDAP: full DNs in `memberOf` array with `group_search_filter` enabled

### ISSUE THREAD

**Issue by AlexLov** [grafana/grafana#3132]
Hi,

In our LDAP scheme we have `cn` attribute only for some of existent groups, so I can't correctly filter (with `group_search_filter` parameter) members of groups and authorize them.

Also `cn` may be the same for different groups. For example:
cn=grafana_access,ou=Project1,dc=example,dc=com
cn=grafana_access,ou=Project2,dc=example,dc=com

And I can't map different LDAP projects (i.e. groups) to different grafana projects, because `memberOf` array has only two items ['grafana_access', 'grafana_access'].

Please fill `memberOf` array with full DNs instead of `cn` attribute.

**Comment by jtopper** [comment]
I think I found the same issue here.  https://github.com/grafana/grafana/blob/master/pkg/login/ldap.go#L345 shows that `memberOf` gets populated with the value from `member_of` set under `[servers.attributes]` in the LDAP config file.

I'd thought setting `member_of` to `dn` would do the trick here, but that doesn't seem to be accessible in the same way as the other attributes. In theory this fix should be straightforward enough, but would be backward-incompatible.

**Comment by jpohjolainen** [comment]
This is something we'd need also. To be able to use DN in the uniqueMember group search filter. Now I have to define full path, and it doesn't work for all when we have users in different OUs.
