### ISSUE TITLE
Variables: default DataSource works incorrectly after upgrade to v7.4.2

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#31327]
Hi,
with regard to https://github.com/grafana/grafana/issues/30996 I'm opening this issue as follows:

**What happened**:
After upgrade to 7.4.2 version selecting a _default_ DS (within a query editor) from a **variable** does not work properly.
When there's the `default` DS being selected within the **variable**, it's impossible to select the _default_ DS (i.e. `${variable_name} (default)` item) in the "Data Sources menu".
You need to select other than `default` DS in the **variable** first, then you can select the _default_ DS.

**What you expected to happen**:
One can select the `default` DS the "Data Sources menu" in one go.

**How to reproduce it (as minimally and precisely as possible)**:
See above, please.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Confirmed a bug, thanks @hawran for reporting!
