### ISSUE TITLE
Support for PostgreSQL 13?

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#31339]
Wondering about support for PostgreSQL 13. I noticed that the version dropdown in the data source settings only goes up to 12. We are still on 12, but plan to upgrade to 13 sometime soon. On Grafana v7.4.2.

**Comment by marefr** [comment]
Version 12 should be version 12 and above. Please try it out and let us know if that doesn't work as expected.

**Comment by nabelekt** [comment]
Could the label be chanced from "12" to "12+"? That would make it much more clear.

**Comment by marefr** [comment]
You could suggest a change of the code below, either update to 12+ or adding 13, by opening a pull request:
https://github.com/grafana/grafana/blob/36cb396568ef4c450ccd05537dee5c1b4e510cea/public/app/plugins/datasource/postgres/config_ctrl.ts#L83-L91
