### ISSUE TITLE
Switching workspaces doesn't change the table scheme in the editor autocomplete dropdown

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#31338]
**What happened**:
For Azure monitor plugin, when you choose "Azure log analytics" and switch between workspaces, the table scheme in the editor autocomplete dropdown does not change. I also checked network tab and "loganalyticsazure/<workspace_id>/metadata" is not queried when switch workspaces.
For example, I have ws1 and ws2 in the workspaces dropdown. ws1 has 10 tables and ws2 has 20 tables. When I switch from ws1 to ws2, the table scheme in the query field's autocomplete select still shows 10 table. I expect 20 tables.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
Grafana version: 7.3.7
Data source type & version: Azure monitor
OS Grafana is installed on:
User OS & Browser: Chrome/Firefox
Grafana plugins: Azure monitor

**Comment by sarahzinger** [comment]
Just going through some of our old Azure issues to see what we can close. I believe now that we've switched from the old Log Analytics page to the new Logs page with resource picker, this issue should no longer be an issue. Going to close this for now!
