### ISSUE TITLE
Support for sending arbitrary Alertmanager annotations

### ISSUE THREAD

**Issue by filippog** [grafana/grafana#31345]
Hello,
thank you for Grafana!

**What would you like to be added**:

We're sending Grafana alerts towards Alertmanager and it works great -- however it isn't possible to send arbitrary Alertmanager annotations (`summary` and `descriptions` are sent for all alerts and `image` if enabled, AFAICT). Related work #10989 and #7481 for additional context.

**Why is this needed**:

Being able to send Alertmanager annotations allows to link alerts to runbooks, other dashboards, etc.

From an implementation perspective I'm not super familiar with Grafana's code however I think this feature could be folded into the generic alerts tags. For example by indicating that a tag with certain prefix should be sent as an annotation e.g. `annotate:runbook` as the tag name and `https://...` as the tag value.

**Comment by davidmparrott** [comment]
@filippog you are able to do this with the new grafana alerting system. When you're creating your alerting rule, there are options to add arbitrary tags (and you can even use some [template data](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/template-data/)).
