### ISSUE TITLE
Distribution: deb install fails on Rasperry Pi OS Lite due to missing libfontconfig1

### ISSUE THREAD

**Issue by iORichy** [grafana/grafana#31346]
**What happened**:

Debian install fails on raspberry pi due to missing `libfontconfig1` dependency.

**What you expected to happen**:

Successful install.

**How to reproduce it (as minimally and precisely as possible)**:

```
pi@raspberrypi:~ $ sudo apt-get install -y grafana
Reading package lists... Done
Building dependency tree
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
grafana : Depends: libfontconfig1 but it is not installable
E: Unable to correct problems, you have held broken packages.
```

crazy that it does not seem to be possible to install libfontconfig1 at all:
```
pi@raspberrypi:~ $ sudo apt-get install libfontconfig1
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package libfontconfig1 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'libfontconfig1' has no installation candidate
```

**Anything else we need to know?**:

hi @xlson I just wonder if there are people requested about this issue?
I just run into the same problem: following your tutorial https://grafana.com/tutorials/install-grafana-on-raspberry-pi/#3 but when it comes to install I just get this error

is this something (really) needed by Grafana?

I was able to download and install directly via
curl -o grafana-7.4.0.linux-armv7.tar.gz https://dl.grafana.com/oss/release/grafana-7.4.0.linux-armv7.tar.gz
and start via ./bin/grafana-server but I'm unsure about installation-scripts and system service registration etc.

Thanks for some thoughts and please let me know, if it's just a too stupid comment, so I will delete for sure…

**Environment**:

Debian on Raspberry Pi

- Grafana version: latest
- OS Grafana is installed on:
```
pi@raspberrypi:~ $ uname -a Linux raspberrypi 5.10.11-v7l+ #1399 SMP Thu Jan 28 12:09:48 GMT 2021 armv7l GNU/Linux
pi@raspberrypi:~ $ lscpu Architecture: armv7l Byte Order: Little Endian CPU(s): 4 On-line CPU(s) list: 0-3 Thread(s) per core: 1 Core(s) per socket: 4 Socket(s): 1 Vendor ID: ARM Model: 3 Model name: Cortex-A72 Stepping: r0p3 CPU max MHz: 1500.0000 CPU min MHz: 600.0000 BogoMIPS: 270.00 Flags: half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
```

**Comment by xlson** [comment]
@aknuds1 @marefr I'm not 100% certain, but I'm guessing that we could remove libfontconfig1 as a dependency from the deb and rpm's now that we no longer use phantomjs? I can't really think of any other reason why we'd need a font package for Grafana.

**Comment by iORichy** [comment]
hi @xlson, I'm so sorry not following your progress! I will for sure doing better next time!
Regarding formatting I just don't get why it wasn't display different as it had looked better while typing and I used quotes and code inserts as applyable…
Thanks for all and highly appreciate your good product and outstanding support! Have a nice weekend.

**Comment by marefr** [comment]
@xlson yes think we can remove that :+1:

**Comment by papagian** [comment]
@grafana/grafana-release-eng can you have a look at this?
