### ISSUE TITLE
Grafana 2.5, 401 Unauthorized

### ISSUE THREAD

**Issue by hryamzik** [grafana/grafana#3134]
I use graphite-api with cyanite connected to grafana 2.5 as with a "direct" method.

```
2015/11/04 17:42:54 [I] Completed /api/login/ping 401 Unauthorized in 4.660079ms
2015/11/04 17:44:05 [I] Completed /api/datasources/proxy/1/api/query 401 Unauthorized in 35.73902ms
2015/11/04 17:44:05 [I] Completed /api/datasources/proxy/4/render 401 Unauthorized in 17.467854ms
```

I do not use any datasources in a proxy mode as I had the same errors in logs and a lot of issues with dashboards. So where do these errors come from?

**Comment by torkelo** [comment]
you must have some data sources in proxy mode.

**Comment by torkelo** [comment]
can you double check all data sources? Ḿaybe some other user who has added a new org a a data source that you do not know about?

**Comment by hryamzik** [comment]
We have a single user in an admin mode. No more data sources.

```
sqlite> select * from data_source;
1|1|0|opentsdb|OpenTSDB|direct|https://grafana.internal/opentsdb||||0|||0|null|2015-10-22 16:39:53|2015-11-04 17:42:04
2|1|0|graphite|cyanite|direct|https://grafana.internal/cyanite||||0|||1|null|2015-10-22 16:40:13|2015-11-04 17:42:12
```

**Comment by claenjoy** [comment]
same issues here , 
Url http://localhost:8000/
Access : proxy 
Test Connection : " Success Data source is working"

empty graph
log :
Completed /api/login/ping 401 Unauthorized in 10.95808ms
Completed /api/datasources/proxy/1/render 401 Unauthorized in 175.694µs

**Comment by hryamzik** [comment]
@claenjoy try to move from grafana proxy to nginx one. And there's also a difficult part – remove proxy datasources from @torkelo's mind.

**Comment by claenjoy** [comment]
ah I was selecting wrong metric , not sure why but on graphite I have "icinga" and "icinga2" the first empty , I select "icinga2" and I have all the data on the graph .

but for some reasons I still have this [I] info message on the log : 
[I] Completed /api/datasources/proxy/1/render 401 Unauthorized in 15.300313ms
