### ISSUE TITLE
InfluxDB: Warn user that template variables are not supported in alert rules when using Flux 

### ISSUE THREAD

**Issue by ravi7248** [grafana/grafana#31341]
**What happened**: I created an alert on one of the dashboard  but it giving the error  
```
ALERTING
Error: tsdb.HandleRequest() response error &{invalid: error @1:17-1:23: undefined identifier Bucket A <nil> [] [] 0xc000ebef60}
Feb 18, 2021 08:48:01

PENDING
Error: tsdb.HandleRequest() response error &{invalid: error @1:17-1:23: undefined identifier Bucket A <nil> [] [] 0xc000b13e90}
Feb 18, 2021 07:12:01
```

**What you expected to happen**: I expected to get the alert on my email after one hour or specified time period.

**How to reproduce it (as minimally and precisely as possible)**:
I have used Influx DB 2.0 as data source and used flux query for creating the dashboards and set up the alert for it. I have used the variable in my flux query.

**Anything else we need to know?**:
Query is running fine and its updating the values as well.

**Environment**:
- Grafana version:  7.4.0
- Data source type & version: InfluxDB 2.4.0
- OS Grafana is installed on: Docker Image
- User OS & Browser: Windows 10 and Mozilla firefox
- Grafana plugins:
- Others:
I am mentioning my Influxdb flux query as well.
```
from(bucket: "${Bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cu_kpi")
  |> filter(fn: (r) => r["_field"] == "field_provided")
  |> aggregateWindow(every: 24h, fn: last, createEmpty: false)
  |> yield(name: "last")

from(bucket: "${Bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cu_kpi")
  |> filter(fn: (r) => r["_field"] == "field_provided")
  |> aggregateWindow(every: 1s, fn: last, createEmpty: false)
  |> yield(name: "last")
```
![grafana_alert](https://user-images.githubusercontent.com/32006408/108458781-549ced80-729b-11eb-96d4-525c3b1fc9c1.JPG)

Annotations you can see it showing on Grafana dashboard panel.

![grafana_alert2](https://user-images.githubusercontent.com/32006408/108458605-04be2680-729b-11eb-94d1-1d1d23ee56e8.JPG)
![grafana_alert3](https://user-images.githubusercontent.com/32006408/108458614-05ef5380-729b-11eb-9896-382737df105a.JPG)

**Comment by torkelo** [comment]
Template variables are not supported in alerting queries, looks like a bug in the flux data source for not warning you about this

**Comment by torkelo** [comment]
think this function https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts#L239 is not checking the flux query for template variables
