### ISSUE TITLE
Publish inbuilt dashboards on grafana.com

### ISSUE THREAD

**Issue by tabic** [grafana/grafana#31355]
**What would you like to be added**:

It would be nice if the inbuilt dashboards are published (and automatically updated) on grafana.com

**Why is this needed**:

To properly (automatically) provision those dashboards it would be really helpful if we can pull them from grafana.com

**Comment by ivanahuckova** [comment]
@tabic isn't this same as https://github.com/grafana/grafana/issues/27059? If not, could you please provide more information and detail on your feature request?

**Comment by tabic** [comment]
No. It is the other way around. We provision with external tools from grafana.com and the request is about publishing https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/dashboards/prometheus_2_stats.json and others in this repo to grafana.com

In the meantime we added support for provisioning from any URL, but I guess it would still be nice to have those dashboards on grafana.com

**Comment by ivanahuckova** [comment]
Thank you for the clarification!
