### ISSUE TITLE
[7.4.2] Plugin "Dashboard list", only display the first folder

### ISSUE THREAD

**Issue by Leletir** [grafana/grafana#31357]
Hello,

I'm using Grafana 7.4.2, but the "Dashboard list" plugin is only displaying one folder. Before I was using 7.3.2 and I was able to choose between all the folders available.

Here is some screenshosts to give you more context.

<img width="394" alt="Screenshot 2021-02-19 at 16 59 15" src="https://user-images.githubusercontent.com/16922595/108528662-f0e2e680-72d3-11eb-83ba-927a2bad4197.png">

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: __grafana__
- OS Grafana is installed on: RHEL
- User OS & Browser: Firefox and Chrome
- Grafana plugins: None

**Comment by torkelo** [comment]
Looks like this is due to the fact that you need Edit permissions for the folder to show up in this folder picker (it is usually correct). But for this panel selecting a folder filter should only require view permissions 

https://github.com/grafana/grafana/blob/master/public/app/core/components/Select/FolderPicker.tsx#L61

**Comment by HenrikRolandHansen** [comment]
I have similar issue. The Dashboard list does not list all folders after bug fix #31158.  Only the selected folder is listed. 

If adding new Dashboard list it only shows ALL and it no longer posible to change the folder. My profile is Admin so all folders should be visible.

**Comment by Leletir** [comment]
Hello, 

I have exactly the same problem as @HenrikRolandHansen, and sometimes it gaves me only the choice of "General" folder and sometimes it gave me only the choice of the first folder by alphabetical order ("Admin" in my case).

**Comment by HenrikRolandHansen** [comment]
Just a follow up on this bug: 

#Torkelo are you looking into this problem - Currently from version 7.4.2 it is not possible to create useful dashboards that includes the plugin Dashboard list.

**Comment by Leletir** [comment]
Hi @torkelo, thank you for taking the time to fix the bug, but I'm still having the same bug.

Here is a screenshot of the interface:

<img width="402" alt="Screenshot 2021-03-30 at 20 57 30" src="https://user-images.githubusercontent.com/16922595/113041775-a38f4a00-919a-11eb-8f9b-51502a2dace7.png">

Before I was only able to get the first folder by alphanumeric order. now it's only General

**Comment by torkelo** [comment]
Are you running latest nightly build ? What version?

**Comment by Leletir** [comment]
Hello, no I'm using the 7.5.2 version released just yesterday
