### ISSUE TITLE
StatPanel: Unit "From Now" on time field doesn't work, only in an override

### ISSUE THREAD

**Issue by wasmitnetzen** [grafana/grafana#31358]
**What happened**:
I am trying to display a relative time of the last reading in an InfluxDB measurement. When choosing the unit "From Now" on the field tab of StatPanel, the value stays a formatted absolute timestamp. If you use the override tab to set the unit of the time field to "From Now", it displays a relative time.

**What you expected to happen**:
Both ways work. The first one is easier to discover, I only found the workaround in the issue linked below.

**How to reproduce it (as minimally and precisely as possible)**:
* Add a StatPanel on a measurement
* Choose the field "Time"
* Choose the unit "From Now"
* Notice that the timestamp stays absolute
![image](https://user-images.githubusercontent.com/1819478/108530104-86cb4100-72d5-11eb-8234-1c4d5c617140.png)
![image](https://user-images.githubusercontent.com/1819478/108530256-af533b00-72d5-11eb-82a9-c5982eb4e409.png)
* Add an override and notice that the timestamp becomes relative
![image](https://user-images.githubusercontent.com/1819478/108530152-9480c680-72d5-11eb-9f36-4cd090906b92.png)

**Anything else we need to know?**:
This was already reported [here](https://github.com/grafana/grafana/issues/25139#issuecomment-688182341), but probably overlooked as is was hidden in a related bug report.

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: InfluxDB 1.8.1
- OS Grafana is installed on: Alpine in Docker
- User OS & Browser: Kubuntu 20.04, Firefox 85.0.1
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
Fixed in 7.4.1 https://github.com/grafana/grafana/pull/30979
