### ISSUE TITLE
Allow re-arranging of graph panels with drag-and-drop

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3136]
Then a row is empty, one panel from another row can be dropped into a placeholder "dropzone".

However beyond that, no re-ordering is possible.

The only workaround I've found so far is creating dummy text panels in the new row, then using the "drag-and-drop to switch" feature to essentially move them from the old to the new row, and then removing the dummy panel from the old row.

**Comment by kokarn** [comment]
It's just not auto-resizing. The panel have to fit in the row you want to drop it in. 
Use the `–` to reduce panel size of the panel in the row and the panel you want to drop and you can drop it anywhere you like.

**Comment by torkelo** [comment]
make space on the row, then you can move the panel to that row.

**Comment by Krinkle** [comment]
A single row can have more than one full-width panel. So it should be insertable regardless of whether it fits next to an existing panel, it can always go between or below a panel.

With regards to available space, I tried that but that didn't work. Size isn't a factor.

I only tried at https://grafana.wikimedia.org, though. Trying on latest master at http://play.grafana.org shows that it now creates drop zones when dragging a panel. And it works for any size, it will autosize to the available dropzone. There is no need to make a panel smaller before dragging. Thanks!

**Comment by LuigiClemente-Awin** [comment]
Why has this been closed? I am having the same issue trying to drag and drop graphs at the end of a row, or in between other graphs. Space availability is not the problem here.

**Comment by joelittlejohn** [comment]
Can we reopen this one? The gif attached by @thenayr accurately demonstrates what should be possible but now isn't. It doesn't matter if your panel is small enough, the drop zone never shows. I've tried Chrome 57 and Firefox 52.

Does anyone know what a good workaround for this would be? Is there any way to edit this via some other dialogue? I haven't found anything yet.

**Comment by daniellee** [comment]
@joelittlejohn can you make a gif showing this? I cannot recreate this problem on play.grafana.org.

**Comment by joelittlejohn** [comment]
@daniellee Does this help? http://imgur.com/a/p8taM

**Comment by daniellee** [comment]
@joelittlejohn yes, that definitely helps. I can only replicate this on the home dashboard on play.grafana.org (not locally)? Is it just the home dashboard or is it other dashboards for you too?

Thanks for the gif, investigating now.

**Comment by daniellee** [comment]
Aha, this is not a bug. The controls are hidden.

![image](https://cloud.githubusercontent.com/assets/434655/25343152/79823fae-290e-11e7-991d-dd88657b902d.png)

**Comment by joelittlejohn** [comment]
@daniellee Thanks a lot for looking again!

When I show controls I do now see the 'EMPTY SPACE' drop-zone at play.grafana.org! When I saw no drop-zone appearing I thought this confirmed the bug and I didn't look for simple answers like the controls being hidden :smile: 

I also have Grafana 3.1.1 and 4.1.1 installations here and this bug affects both of those (when controls are definitely **not** hidden) so I guess the solution for those installations is simply to upgrade.

**Comment by daniellee** [comment]
@joelittlejohn An upgrade might help. If you are still having problems then create a simple dashboard with the bug and attach it the dashboard json here. I can test against the latest master with the same browser that you are using to see if the bug is still there.
