### ISSUE TITLE
Overrides: Filtering / Selecting on timeseries is not possible when an override with displayName exists

### ISSUE THREAD

**Issue by int2001** [grafana/grafana#31364]
**What happened**:
Given is an influx-query which is displayed with the new timeseriespanel. If added override to a field on "Display Name" (for better readability) it is not possible to select the field/series as in graphpanel. (See screenshot)

**What you expected to happen**:
I'd like to view only the graph for the selected field/series like it was/is when using the old graphpanel

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot. Simply create the same graph (with timeseries) and then try to select the series "AAA" at the panel. Everything is deselected then.
<img width="1453" alt="Bildschirmfoto 2021-02-20 um 07 55 31" src="https://user-images.githubusercontent.com/1410708/108587107-026ad380-7352-11eb-9d24-0197625d67b1.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: influxdb 1.8.4
- OS Grafana is installed on: debian buster
- User OS & Browser: macos/chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
Thanks for reporting this one! @mckn did this scenario every come up when you developed this? it's a tricky thing given the hide/show logic is an override that acts on the display name, and so the order here becomes important. Is the override that is created from the hide interaction always added last?

**Comment by mckn** [comment]
Ah, no - I totally missed this scenario. Hmm, but i think we should be able to solve this.

**Comment by kdorsel** [comment]
Still seeing this bug in 8.0.3 when using the Display Name in the panel configuration.

![image](https://user-images.githubusercontent.com/2569415/123174011-7b3b8280-d44d-11eb-9139-76efee4e1b45.png)

**Comment by ashharrison90** [comment]
@kdorsel looking at the attached PR,  I don't think it's due to be released until 8.1.0.
