### ISSUE TITLE
Y-max "auto" does not work properly

### ISSUE THREAD

**Issue by krzd7** [grafana/grafana#31369]
**What happened**: I've created a time series with Y-max property set to "auto", but it does not seem to work properly.

**What you expected to happen**: visually, it does not make sense having an "auto" Y-max that considers the maximum value regardless of it being displayed or not on a time series. Auto value for Y-max should change accordingly to what is plotted.

**How to reproduce it (as minimally and precisely as possible)**: I've just created a time series, used a MySQL to grab data and noticed that Y-max auto was defined by the greatest value on my table, regardless of it being actually returned when date time filters are applied.

I have tried a bunch of MySQL queries, including:
```
SELECT
  $__timeGroupAlias(register_date,$__interval),
  COUNT(*) AS "total"
FROM customers
GROUP BY 1
ORDER BY $__timeGroup(register_date,$__interval)
```

I have like 6k customers registered at certain date (last year). If I select "this month" - or any date that does not include the 6k count record - my time series looks flat, even though the data gets filtered and plotted correctly:

![](https://i.postimg.cc/Jz8TwnF7/y-max-auto-issue.gif)

Once I select "this month", I no longer have an entry with 6.000+ customers, so I'd expect the time series Y-max to adjust accordingly. I'm not sure if I'm missing something, but I appreciate any help :)

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: MySQL v5.7
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
>  I've just created a time series, used a MySQL to grab data and noticed that Y-max auto was defined by the greatest value on my table, regardless of it being actually returned when date time filters are applied. 

When you zoom in there is a new query issued, and if your query filters on time range only the data shown should be returned so this should not happen. Can you show the graph & the raw data from query inspector?

**Comment by krzd7** [comment]
Thanks for your response @torkelo , I've added more details.

**Comment by torkelo** [comment]
you do not have a date filter in your SQL query, so it will query return all the data
