### ISSUE TITLE
Time Series panel is refreshing and loosing previous values when edit or scrolling dashboard

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#31368]
**What happened**:

The Time Series panel behaves differently than the Graph panel. When scrolling the dashboard up and down and the Time Series panel is not visible it's refreshing and losing collected values. Graph panel keeps all the values.
Also, when clicking on panel edit and don't change anything, return back to the dashboard, panel is refreshing.

Play.grafana.com working similar because provides historical data filling the whole time-range. In case of Redis Data source, there is no historical values.

**What you expected to happen**:

Be similar to the Graph panel and keeps values. Or this behaviour is expected?

**How to reproduce it (as minimally and precisely as possible)**:

1.  Use the latest version of Redis Data Source or other Streaming datasource
```
docker run -p 3000:3000 ghcr.io/redisgrafana/redis-app:latest
```

2. Import Dashboard with Time-series panels or create new Time-Series panel
```
https://raw.githubusercontent.com/RedisGrafana/grafana-redis-datasource/master/provisioning/dashboards/data-types-7.4.json
```

3. Scroll dashboard up and down or edit the panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Redis Data Source 1.1.0
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins: Redis Data Source
- Others:

**Comment by torkelo** [comment]
Not sure what you mean losing collected values? 

Is there an auto refresh on the dashboard? It's up to the datasource to remember data between refreshes not the panel.

**Comment by mikhailredis** [comment]
@torkelo There is no auto-refresh. Let me demonstrate:

https://user-images.githubusercontent.com/47795110/108610607-ec3a3300-73a4-11eb-8efb-1695eec326f4.mp4

Thinking about it, you are correct that the frontend datasource remembers data, so why it's refreshing for the Time Series panel?

**Comment by torkelo** [comment]
I have tested this with our internal streaming data sources and unable to replicate what you are seeing. What you are seeing in your panels is that they are refreshing as they get into view. This does not happen for me. Have a streaming panel at the top and it keeps streaming and collecting data as I scroll down and back up it is still there and the data received while out of view is there.

**Comment by torkelo** [comment]
wait seing it now, had not switched to time series panel :facepalm:

**Comment by mikhailredis** [comment]
@torkelo thank you, let me know if you need anything else.
