### ISSUE TITLE
Google Bot struggles to index Grafana page

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#31372]
**What happened**:
Googlebot is not properly indexing Grafana page everytime. Sometimes it loads page correctly (not all values in panels are getting downloaded, but the dashboard is loaded so there is correct page title and description available in Google search), but sometimes the dashboard is not getting loaded, so the page title and description in Google search are wrong.

Here is how it looks in Google Search Console when the page is indexed correctly:
![1](https://user-images.githubusercontent.com/19311511/108624902-1133b200-7448-11eb-8099-2748e5d39fa6.png)

And here is how it looks when the page is indexed incorrectly:
![2](https://user-images.githubusercontent.com/19311511/108624912-227cbe80-7448-11eb-848d-a9efcd719882.png)

It seems like it is getting indexed incorrectly because Googlebot cannot load JS scripts:
![3](https://user-images.githubusercontent.com/19311511/108624915-27417280-7448-11eb-8f15-fba8dc2280b3.png)

Here is how it looks in Google search when the page is indexed incorrectly:
![4](https://user-images.githubusercontent.com/19311511/108624931-4b9d4f00-7448-11eb-83b1-84ed69112256.png)

**What you expected to happen**:
I am not sure if the problem is in Grafana, or Google indexing bot. However, the page should be indexed properly everytime.

**How to reproduce it (as minimally and precisely as possible)**:
Grafana has to be available publicly and it has to be added in Google Search Console.

My robots.txt file is set to block /api and /playlists:
```
User-agent: *
Disallow: /api/ 
Disallow: /playlists/
```

Now I've changed it not to block anything. On live view it seems that the problem is still occuring, but I will share full results in a few days, when the Googlebot finishes full indexing.
```
User-agent: *
Allow: /
```

**Anything else we need to know?**:
I'm not 100% sure, but I think that the problem is more common on 7.4.x than on 7.2.x.

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: -
- Grafana plugins: -
- Others: -

**Comment by ryantxu** [comment]
What would you like to have happen when google crawls grafana?  Perhaps it could/should add a sitemap to robots.txt?  https://developers.google.com/search/docs/advanced/sitemaps/build-sitemap#addsitemap

**Comment by szerwi** [comment]
@ryantxu bot should load the page correctly at all attempts. It should load dashboard and all values in panels. I don't know if the problem is on Grafana side or Googlebot side that it is not loading many page's resources. Maybe sitemap will help it in some way.

**Comment by szerwi** [comment]
After allowing bot to access all resources, it is getting indexed properly for over a month. I will reopen the issue when it shows error again.
