### ISSUE TITLE
Table Panel: Ability to move the columns

### ISSUE THREAD

**Issue by MacNale** [grafana/grafana#31377]
**What would you like to be added**:
Once table is rendered in dashboard with many columns, sometimes I wish to change the order of the columns without editing the dashboard.

**Why is this needed**:
Bringing required columns together helps to diagnose the operation problem faster. Following table is small and I can see all the information in one go. It is not a problem. 

![image](https://user-images.githubusercontent.com/14235758/108662647-672e4700-7494-11eb-916f-de414cc78e78.png)

However, I have a table with many columns, unless I scroll back and forth I can;t see the columns. One of the workaround is to either create table with required columns or use transformation in the query editor. For these options, user needs to have required permissions.  I am a 'viewer' and wants to change the order of the columns by just dragging.

**Comment by torkelo** [comment]
Use the transform "Organize fields"

**Comment by MacNale** [comment]
@torkelo Thanks for suggestion.  I dont have edit permission to dashboard. I wish to move around the table column without editing the panel. 
Here is an example - 

![image](https://user-images.githubusercontent.com/14235758/108784373-e3786700-7534-11eb-8690-4dac09304d69.png)
