### ISSUE TITLE
Not able to setup InfluxDB as a data source in Grafana Cloud Pro version

### ISSUE THREAD

**Issue by ravi7248** [grafana/grafana#31380]
**What happened**: Grafana Cloud version giving error **Error reading InfluxDB**

**What you expected to happen**: Data source should be added and able to make the dashboards

**How to reproduce it (as minimally and precisely as possible)**: Signup for the Grafana cloud pro version and try to add **InfluxDB** as a data source and query language as **flux**

**Anything else we need to know?**: I am providing all the credential it required. I am using ec2 instance and there docker container of 
InfluxDB 2.0. In URL I am passing public IP of ec2 and default port no of InfluxDB 2.0
**Environment**:
- Grafana version: Grafana Cloud Pro
- Data source type & version: InfluxDB 2.4.0
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins:
- Others:
![grafana_cloud_full](https://user-images.githubusercontent.com/32006408/108680618-1a8a5080-7514-11eb-882f-997cf9e9b755.JPG)

**Comment by ying-jeanne** [comment]
Hi @ravi7248, Thanks for reporting issue, I tried on my side, and not able to reproduce the issue. I doubt it is an issue for your influxDB setting, could you send the console.log to show more details?

**Comment by ravi7248** [comment]
My EC2 have machine restriction on the inbound and outbound traffic. I gave permission and Now I am able to connect to InfluxDB data source.
