### ISSUE TITLE
Allow specifying (or querying) labels for template values

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3138]
E.g. when creating a custom template variable with values `fooBar` and `baz_quuxInternal`, to be able to have the UI display the checkboxes as "Foo bar" and "Baz".

This is especially common when using repeated rows and a custom variable to reduce duplication, but the top level metrics may not be user-friendly.

One could potentially support this for queried template values (e.g. graphite properties) as well by using a regex (if the replacement is generic). Regex support already exists, but it applies to both the value used and the label. Having it used for the value only would be valuable.

For example, if a graphite query expands `kafka.messagesByTopic.myservice_*` for use in templates, then one may want the user interface to strip the prefix. But when used in the actual panels, the prefix should be included. This can be worked around (in Grafana 2.x and later) now that template variables can be embedded in a metric property, so one could hardcode the prefix in all metrics in all panels and rows, but that's better to avoid.

Once these "label" values exist, it would be useful to be able to access them inside the panels as well. Such when embedding a variable in a Row and/or Panel title. Either we can make it use the label by default (if embedded in a title field), or perhaps with some alternate syntax (e.g. `$$Variable`, or some whatever)

**Comment by torkelo** [comment]
similar to this issue?
https://github.com/grafana/grafana/issues/1032

**Comment by Krinkle** [comment]
Thanks, I was searching with different terminology and didn't find that one (label, templated).
