### ISSUE TITLE
Pending time for No Data alerts

### ISSUE THREAD

**Issue by Bartosz76** [grafana/grafana#31390]
Hello,

I would like to ask if it would make sense to have a pending time option for No Data alerts? Or perhaps it's already available and I just can't figure it out?
I have a data source that keeps having its connection severed every now and again just to have it back up and running moments later. It would really be great if my No Data alerts would wait at least a minute before notifying me about it.
I would like to be notified that there's no data but only if the No Data state lingers for at least a minute.

Take care,

**Comment by torkelo** [comment]
@kylebrandt do you think expressions can solve this?

**Comment by kylebrandt** [comment]
@davidmparrott is going to be working on this shortly (state machine for alert tracking). We know presently Pending/Unknown and keep last state or problematic, so we will be looking to design a system where FOR and No Data can work together.

We considered expressions, but that generally would mean making extra queries or other complexity, so if we can keep as an option and part of the state tracking we think that will be better.

**Comment by Bartosz76** [comment]
@torkelo @kylebrandt 
Okay, so this is a feature that might be available in the future. Thanks a lot, knowing for sure that something is just not available at the current moment is also valuable. :)
Take care,

**Comment by pierreloicq** [comment]
Hi,
I would like to know if something has been implemented since 2021 ?
