### ISSUE TITLE
Wrong legend precision with unit "Percent (0.0-1.0)"

### ISSUE THREAD

**Issue by dguendisch** [grafana/grafana#31397]
**What happened**:
The legend's precision for unit `Percent (0.0-1.0)` seems wrong when using manual decimals/precision.
The precision seems to correctly apply to the metric (which is between 0.0 and 1.0) but in the rendering of the legend axis, the percentage has again the amount of decimals displayed although this percentage unit (0.0-1.0) actually multiplies the metric already by `100`, hence it should "loose" two precision decimals. The rendering however suggests wrongly that you have a higher precision.
See in these two examples how e.g. the decimals in the legend never make any sense (they give a wrong impression of the actual precision):

![image](https://user-images.githubusercontent.com/30311254/108713156-1eb86d00-7518-11eb-89cf-ae20f811ae8c.png)

and another example for precision/decimals of `2`:

![image](https://user-images.githubusercontent.com/30311254/108713260-41e31c80-7518-11eb-8f06-7a2b922bb242.png)

**What you expected to happen**:
The legend's precision for unit `Percent (0.0-1.0)` should reflect the manually selected precision/decimals and take into account that it already multiplies the metric by 100, so the precision in the legend needs to be lowered by 2 decimals.

**How to reproduce it (as minimally and precisely as possible)**:
See screenshots.

**Environment**:
- Grafana version: 7.4.1

**Comment by torkelo** [comment]
There is a separate decimals option for legend and by default, this is  axis decimals +1   (in the new graph panel named Time series this is unified)

**Comment by dguendisch** [comment]
My bad, I wrote this down wrongly. I actually meant the labeling of the y-axes is wrong (not the legend precision), see the highlighted part of the y-axes in the screenshots.
Will that change/fix with the "Time series"?
