### ISSUE TITLE
Using Grafana 2.5,trying to import all dashboards from another graphite node ..not successfull

### ISSUE THREAD

**Issue by cchiremath** [grafana/grafana#3139]
Hi Folks,
i am using grafana 2.5 and i have added a data source to one of my graphite node.
data source is successful but when look for listing the dashboard it does not list any though i have few dashboards in graphite.

any help to fix this issue will be really grateful.

https://revproxy-01.int-tx3.huron-int.com:8002/

Test results

Success
Data source is working

regards,
Chandrashekhar

**Comment by torkelo** [comment]
Dashboard import only works in 'direct' mode (when you configure data sources), and for direct mode to work you need to setup CORS headers.
