### ISSUE TITLE
Does gf-form-dropdown support multi-select?

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#31405]
**Why is this component needed**:

We are adding a feature where we need to have a multi-select dropdown for Azure Monitor datasource dashboard. I see that there is only single select in public/app/plugins/datasource/grafana-azure-monitor-datasource/partials/query.editor.html. I'm wondering if multi-select is supported.
 - [ ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

Selecting multiple workspaces.
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by torkelo** [comment]
No it does not, but https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--multi-select-basic does 

The angular components are no longer being developed / supported. Will likely stop working in v9 (next year)

**Comment by shuotli** [comment]
> No it does not, but https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--multi-select-basic does
> 
> The angular components are no longer being developed / supported. Will likely stop working in v9 (next year)

Looks like https://developers.grafana.com/ui/latest/index.html?path=/story/forms-select--multi-select-basic is in React. But partials/query.editor.html is in Angular. Do you mean there is no way to make a multi-select in that file?
