### ISSUE TITLE
[grafana 2.5] grafana admin can not see data source icon

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#3140]
As a grafana admin, after login, the usual data source icon do not show up which used to be just above the `Dashboards` on the left  toolbar.

Which means, I can not update or add a data source now.

**Comment by torkelo** [comment]
You need to be an organization admin to edit data sources. If you are a grafana admin you can go into the admin views, find your admin user and check the organization role (and update it)

**Comment by liyichao** [comment]
Yeah, But there is a bug. I update myself to organization admin, the frontend shows I succeed and I also click the update button after I update, but when I logout and login again, the `data source` still not showing and I find myself not organization admin.
