### ISSUE TITLE
Support custom display label for derived fields buttons in the explore view

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#31417]
**What would you like to be added**:

Support custom display label for derived fields buttons in the explore view. 

For example: tempo.integration01.foobar.example.org => Tempo Q/A environment

**Why is this needed**:

Derived fields are now showing only the datasource name or the external URL of the system. URL's can be pretty long and not human-friendly, so an option to set a custom display name for the derived field buttons in the explore row details view would be helpful.

**Comment by tharun208** [comment]
@aocenas I like to work on this. can you guide me on this?
