### ISSUE TITLE
When upgrading to 7.4, template variablesrv does not work

### ISSUE THREAD

**Issue by xieziqiang** [grafana/grafana#31418]
**What happened**:
In version 7.3, I can use the following code in HTML panel to modify template variable
```
function changeVariable(key, val) {
        let templateService = angular.element('grafana-app').injector().get('templateSrv');
        let dashboard = angular.element('grafana-app').injector().get('dashboardSrv').dashboard;
        let v = templateService.getVariables().find(({ name }) => name === key);
        v.current = { text: val, value: val };
        dashboard.templateVariableValueUpdated();
        dashboard.startRefresh();
}
changeVariable('testKey','testVal');
```
But when I  upgrading grafana to 7.4 , it does not work. cloud anyone tell me how to modify variable in 7.4？thx

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The best way would be to use update url using the history api

**Comment by xieziqiang** [comment]
@torkelo update url will cause page refresh. Is there any other way to modify variables via JS？

**Comment by torkelo** [comment]
if you use the history api it wont cause a full page reload

**Comment by torkelo** [comment]
or if that does not work add a hidden link to the dom that you click through the code

**Comment by xieziqiang** [comment]
what is histoty api? how to update url via histoty api ? Is there a document?

**Comment by torkelo** [comment]
https://developer.mozilla.org/en-US/docs/Web/API/History_API

**Comment by torkelo** [comment]
but it looks like that won't work. 

So from the html panel you would have to add a link and click it

**Comment by xieziqiang** [comment]
OK, I'll try it. thank you
