### ISSUE TITLE
Question: is it possible to only display annotations on certain graphs?

### ISSUE THREAD

**Issue by danievanzyl** [grafana/grafana#3141]
For example,

I'm comparing two sources from influxdb, and my annotations are from elasticsearch. 
I want source one's annotations only to appear on source one's graph and not on the graph of source two, and then I want source two's annotations appear on its own graph.

Is this possible, or am I missing a setting somewhere?

Thanks for this amazing tool, btw.

Cheers,
Danie

**Comment by torkelo** [comment]
no its not currently possible, there already is an issue to have annotations per graph so I will close this issue
