### ISSUE TITLE
Tooltip on Graph panel does not update for all timestamps

### ISSUE THREAD

**Issue by anirudh-ramesh** [grafana/grafana#31412]
**What happened**:

I'm using the Graph panel with a PostgreSQL datasource on Grafana 7.3.7. In some panels, arbitrarily, the tooltip of the graph only shows the values of the first and last row of each series and not those of timestamps in between.

![Screenshot from 2021-02-23 14-49-51](https://user-images.githubusercontent.com/8345813/108824375-a5884b00-75e7-11eb-950c-37e23e22958a.png)

**What you expected to happen**:

In every graph panel, the tooltip must show the values of the series at every timestamp; not just the first or the last row.

**How to reproduce it (as minimally and precisely as possible)**:

This is occurring arbitrarily, and I'm unable to isolate the configuration that is the root cause of this.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: PostgreSQL 11
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04 with Mozilla Firefox, and Microsoft Windows 10 with Chromium/Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by anirudh-ramesh** [comment]
Related issues:
https://github.com/grafana/grafana/issues/31114
https://github.com/grafana/grafana/issues/31280

**Comment by torkelo** [comment]
related to https://github.com/grafana/grafana/issues/6946 

we hope to fix this in the new time series panel
