### ISSUE TITLE
Templating: KairosDB

### ISSUE THREAD

**Issue by andronux** [grafana/grafana#3142]
Hello,

if I'm not wrong, none of the proposed format (glob, regex, ....) for "all values" and "Multi-value selection" work with the datasource KairosDB.

In a KairosDB query for metrics, the tag/key "host" expect a list for host double quoted separated with a coma.  

"host": ["foo", "foo2"]  

see : https://code.google.com/p/kairosdb/wiki/QueryMetrics

Is this something that you can easily and quickly implement? 

if so, that would be great :D

Thank you.

**Comment by torkelo** [comment]
no, templating feature in Grafana is text based (string substitution), which does not work with KairosDB query api :(
