### ISSUE TITLE
Loki Integration Improvement: Possibility to hide a part of the Log Entry from Loki (to overcome Cardinality issues)

### ISSUE THREAD

**Issue by pcbl** [grafana/grafana#31425]
**What would you like to be added**:
I start by making reference to this topic here: [What to do with externally provided labels without compromising label cardinality?](https://community.grafana.com/t/what-to-do-with-externally-provided-labels-without-compromising-label-cardinality/41750)

Basically In order to avoid cardinality issues with Loki, I have very few Labels and I pack a lot of additional information that I got from a .Net application as additional Information on the Log Entry, allowing me to query using RegEx filters.

Let`s say I have the following Log Entry:
**Service[Level] => This is is the log entry | Field1=[AA] | Field2=[bb] | Field3=[1234] | Field4=[AA] | Field5=[bb] | Field6=[1234] | Field7=[AA] | Field8=[bb] | Field9=[1234]**

My issue is that the additional Fields are, at the first moment, not important as the "**Service[Level] => This is is the log entry**" part. 

So my suggestion would be to add a marker on the Log Entry such as "**$Additional_Info$**", and as soon as grafana have this sentence, it would ignore the remaining part of the log line, while loki would still support querying based on values that are "hidden".

I would have then something like:

**Service[Level] => This is is the log entry $Additional_Info$ | Field1=[AA] | Field2=[bb] | Field3=[1234] | Field4=[AA] | Field5=[bb] | Field6=[1234] | Field7=[AA] | Field8=[bb] | Field9=[1234]**

Where on Grafana I would see:
**Service[Level] => This is is the log entry**

Nevertherless, Grafana should use the full message to calculate "parsed fields" which would be show as follows (Today they are already correctly parsed by Grafana exectly like this):

- Field1=[AA] 
- Field2=[bb] 
- Field3=[1234] 
- Field4=[AA]
- Field5=[bb]
- Field6=[1234]
- Field7=[AA]
- Field8=[bb]
- Field9=[1234]

**Why is this needed**:
This is a very nice feature to avoid too much uneeded information at a first glance. At the the moment I am being somehow "forced" to write those fields on the Log Entry as there´s no other option from Loki where I could add those additional fields not as Labels (for the sake of Cardinality issues) while still supporting Log Stream RegEx query/filter expressions.

**Comment by lrolsen1** [comment]
This would indeed be a very useful addition. Coming from the ELK this is one of the features we are surely missing in Loki/Grafana. Being able to keep the log lines as one-liners and still log all the context we need would be very nice

**Comment by ivanahuckova** [comment]
@pcbl there is a toggle parsed fields feature that might be what you are looking for https://grafana.com/docs/grafana/latest/explore/logs-integration/#labels-and-detected-fields.

**Comment by ivanahuckova** [comment]
Moreover, on the Loki side, you can use `line_format`  expression to rewrite the log line content by using the text/template format. You can learn more here https://grafana.com/docs/loki/latest/logql/#line-format-expression. 

I am closing the issue but feel free to reopen if suggestions won't help.

**Comment by pcbl** [comment]
Hi @ivanahuckova ,

Thanks for the information...

I am not sure that I can achieve this. Or maybe you can help me out?

Original Entry (I am adding a lot of additional fields to it as I need to query them later, but I cannot set them as labels to avoid cardinality issues):
**Service[Level] => This is is the log entry $Additional_Info$ | Field1=[AA] | Field2=[bb] | Field3=[1234] | Field4=[AA] | Field5=[bb] | Field6=[1234] | Field7=[AA] | Field8=[bb] | Field9=[1234]**

I would like to have this visible on Grafana:
[Service[Level] => This is is the log entry](url)

But still being able to **see** (as parsed fields) and **query** the following fields:
- Field1=[AA]
- Field2=[bb]
- Field3=[1234]
- Field4=[AA]
- Field5=[bb]
- Field6=[1234]
- Field7=[AA]
- Field8=[bb]
- Field9=[1234]

From `line_format` I can see that I can reformat the line, but the fields would not be queriable anymore, or am I wrong?

**Comment by ivanahuckova** [comment]
Yes, you are right. This isn't possible with `line_format`. But what about toggle detected fields? Isn't it exactly what you are asking for?

**Comment by pcbl** [comment]
Hey @ivanahuckova,

Indeed it seems to address the Topic. I will double check and get back to you. Thanks again for the heads up!

**Comment by Rydez** [comment]
I'm running into a similar problem and this is the top result on Google. 

Regarding the detected-fields toggle: I must be missing something, because it seems like toggling detected fields doesn't work here. Clicking the eye icon results in logs which only contain the detected field rather than logs which don't contain the detected field. Though, even if there was a way to hide the individual detected fields, I'm wondering if there's a way to make this permanent. It seems like more hassle than it's worth to have to expand a log line and toggle off the fields every time.

 My use case is for the logs panel, and I found `line_format` to be helpful. I can use something like 
 ```
{someLabel="someValue"} |= "detectedField=123" | line_format `{{ regexReplaceAll "(detectedField=[0-9]+)" __line__ "" }}`
``` 
From what I can tell, the line is formatted after applying `|=`. So the query works. The detected fields are not shown in the expanded log, and even though I wish they were, I can imagine that others might prefer them to be hidden
