### ISSUE TITLE
Diff() and percent_diff() not working as intended in alert condition

### ISSUE THREAD

**Issue by Dd-Abraham** [grafana/grafana#31439]
**What happened**:

The data source I'm using is an `ES` index pattern, I do not use a custom query in Grafana. The data gets pushed to `ES` constantly. I'm using a query interval is `2m` is and the min interval in the query options is `2s`.

Query:
![alt text](https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/7/719531f277db6d0fd9554702f2a762eb89ba976f.png)
Alert:
![alt text](https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/b/b30d32809b188c89ba7c34b910b50cb1a063b1f6.png)

What is happening is that the alert condition is not testing the "whole" value amounts for the intervals.
I'll explain, let's say that the alert is tested at `15:35:30` for example, the condition calculates the percentage difference between:

- the amount of data between `15:28:30 - 15:30:00`
and
- the amount of data between `15:33:00 - 15:33:30`

**What you expected to happen**:

What I expected to happen is that, given the `2m` query intervals, the condition should calculate the percentage difference between: 

- the amount of data between `15:28:00 - 15:30:00`
and
- the amount of data between `15:33:00 - 15:35:00`

**How to reproduce it (as minimally and precisely as possible)**:

Just recreate the alert and use the same kind of source.

**Environment**:
- Grafana version: v7.3.4 
- Data source type & version: Elastic Search 7.9.2
- OS Grafana is installed on: CentOS Linux release 7.9.2009 (Core)
- User OS & Browser: Manjaro Linux x86_64 / Version 88.0.4324.182 (Official Build) (64-bit)
- Grafana plugins: None

**Comment by papagian** [comment]
This is related/duplicate of #27469.
