### ISSUE TITLE
Security: Add timeout options for main http server 

### ISSUE THREAD

**Issue by jicanghaixb** [grafana/grafana#31440]
security scan report a moderate security problem: “Slow HTTP denial of service attack“(slow header,slow body,slow read), I see http server code(/pkg/api/http_server.go)
	hs.httpSrv = &http.Server{
		Addr:    net.JoinHostPort(host, setting.HttpPort),
		Handler: hs.macaron,
	}
it use default values，so I can't avoid this problem by configuration
can you add several timeout parameters for http server configuration control？example parameters：ReadHeaderTimeout、ReadTimeout、WriteTimeout、IdleTimeout、MaxHeaderBytes

**Comment by torkelo** [comment]
Looking at what Prometheus does we can do the same, expose an option for ReadTimeout (ini option under [server] named read_timeout) with a default value of 5m (go interval string) 

https://github.com/prometheus/prometheus/blob/main/web/web.go#L233
