### ISSUE TITLE
Add possibility to move one graph and not swap two

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#3144]
Hi,

Currently we can only swap graphs, i.e., the first one will take the place of the other one and vice versa.

Say I have graphs 1, 2, 3 & 4, I can only do 1, 4, 3, 2 when really I meant to move graph 4 between 1 and 2 (1, 4, 2, 3).

Regards.

**Comment by Dieterbe** [comment]
+1 I most often just want to move not replace

**Comment by utkarshcmu** [comment]
+1

**Comment by tgelectify** [comment]
+1

**Comment by addshore** [comment]
+1

**Comment by matn** [comment]
+1

**Comment by xneo64** [comment]
+1

**Comment by torkelo** [comment]
fixed by new grid in Grafana v5
