### ISSUE TITLE
Grafana 7.4.2 Variables query using clickhouse dosn't working

### ISSUE THREAD

**Issue by it1804** [grafana/grafana#31445]
**What happened**:

**What you expected to happen**: Grafana 7.4.2 Variable query using Clickhouse data source not working

**How to reproduce it (as minimally and precisely as possible)**:

    Add clickhouse as datasource
    Add a variable
    Type: Query
    select groupArray(id) from default.test

**Anything else we need to know?**: It works in 7.3.х

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Clickhouse 2.2.3
- OS Grafana is installed on: docker image grafana/grafana:7.4.2
- User OS & Browser: Windows 7, Chrome & Windows 7, Firefox
- Grafana plugins:
- Others:

Chrome error:
Uncaught TypeError: Cannot read property 'length' of undefined  ( operators.ts:34 )

Firefox error:
TypeError: p.fields is undefined ( operators.ts:34 )

**Comment by it1804** [comment]
If you make a request without groupArray(), then everything works:
select id from default.test group by id

**Comment by torkelo** [comment]
Can you open this issue with https://github.com/Vertamedia/clickhouse-grafana as well? We migth need to know what this query is returning (in terms of what exactly they are returning to Grafana)

**Comment by torkelo** [comment]
looks like field is undefined here, https://github.com/grafana/grafana/blob/master/public/app/features/variables/query/operators.ts#L34  

Think I know why

**Comment by svendberg** [comment]
Still seems to be failing in 7.4.5 for Postgres datasource. We can fix it by converting null to '' in the variable query but it's still a breaking change when upgrading from 7.3.7.
