### ISSUE TITLE
query parameter

### ISSUE THREAD

**Issue by iBelow** [grafana/grafana#31449]
**What happened**:

if i set Relative time in query options - 3d (3 days) - i get last data correct for current time
![image](https://user-images.githubusercontent.com/8112733/109015131-e0f94700-76c5-11eb-8dcb-6a94bab773fa.png)

if i change relative time to 4>= days, last data incorrect: 
p.s. (all data's incorrect)
im use only AggregateBy(1d, max) (i need max value for each day)

![image](https://user-images.githubusercontent.com/8112733/109015315-0f772200-76c6-11eb-82c2-f71743adaa5d.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.4.2 (29e75ad97b)
- Data source type & version: zabbix 
- OS Grafana is installed on: Ubuntu server 20.04 LTS
- User OS & Browser: Win10 pro x64 / Chrome 88.0.4324.182
- Grafana plugins: defaults + zabbix 
- Others:
none

**Comment by torkelo** [comment]
A time range like last 3 days to now will query your current time 3 days ago, to the current time. 

if you want to align the start of the time range to the start of a day you can write `2d/d` in the relative time field, or in the dashboard time picker write: `now-2d/d` in the From field

**Comment by iBelow** [comment]
okay, i dont understand, why if i set for example
relative time = **now-4d**, i'm get correct value, 
but if i set
relative time **now-5d or more**, i'm get incorrect values ? 
how i'ts work? 
how i can get last (or max) correct value in table/gaugs and etc for 7d period in panel? 
screens: 

  1.  4d max datas
- ![image](https://user-images.githubusercontent.com/8112733/109133340-f6be4900-7765-11eb-82e4-db841aa81378.png)


 2. 5d maximal 
- ![image](https://user-images.githubusercontent.com/8112733/109133418-0b024600-7766-11eb-9552-06d6ef3a69a3.png)


how i can get last not null or max value for each day in period and correct value for current time?
