### ISSUE TITLE
Capture invalid certificate messages in Grafana Logs 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#31447]
**What would you like to be added**:
Capture invalid certificate messages in Grafana Logs 

Currently we return responses in the front end for invalid certs, e.g. 

![image](https://user-images.githubusercontent.com/54800912/108996180-5ea95c80-769e-11eb-9550-3d14975f05fe.png)

However this is not written to Grafana log.  Requesting for error messages to be written to Grafana log for security review and auditability. 

**Why is this needed**:
To be able to audit invalid connections.

**Comment by torkelo** [comment]
Can you describe what cert you mean? Where are you seeing this error? Can you describe the steps to reproduce?

**Comment by aengusrooneygrafana** [comment]
Hi Torkel!  I've been discussing this with @sakjur ..   Essentially we'd like to prove that Grafana does in fact leverage the Go crypto packages to verify **all** certificates (i.e. requiring approved roots, certification path building, revocation checking, etc).  There is a conversation with more details on this topic here - 

https://raintank-corp.slack.com/archives/CQEHMQQHH/p1613123708102900 

Or see more details on the requirement here (ref CL-170) 

https://docs.google.com/spreadsheets/d/19OH9QtaPJ3To5KzcfLzJi-uwb9R9CZzF/edit#gid=513817000 

If you know of any other way to prove / evidence this, please let me know!  And also please let me know if you require more information on this!  

Thanks, 
Aengus.

**Comment by mjseaman** [comment]
@aengusrooneygrafana are they looking for this to go into _Audit_ Logs, or standard Grafana logs?

**Comment by aengusrooneygrafana** [comment]
They have not specified, but IMHO I think Grafana logs would make more sense as it's monitoring/logging system activity.  Audit logs are more geared towards user activity, unless i'm mistaken?

**Comment by aengusrooneygrafana** [comment]
I am asking the client for more information on their request "If the solution accepts digital certificates, are these certificates verified as per our standards and industry best practices (e.g. requiring approved roots, certification path building, revocation checking via CRL/OCSP/SCVP)?"

**Comment by mckn** [comment]
@aengusrooneygrafana @jongyllen what is the status of this issue? still something you are working on or could we close this one?

**Comment by jongyllen** [comment]
It is something we want to do but we were waiting for more information plus
getting it prioritized in our backlog

**Comment by ivanahuckova** [comment]
@jongyllen are we still waiting for more information? Is this still something we will be working? If so, should we move it to backend platform backlog?

**Comment by jongyllen** [comment]
I think it should. But do not know any timeline. @mjseaman do you have an opinion? (small thing to do but needs some investigation)

**Comment by ivanahuckova** [comment]
@jongyllen is it okay to replace `needs more info` label with `needs investigation` as we are currently not waiting for additional info from users?

**Comment by jongyllen** [comment]
Sure
