### ISSUE TITLE
Inspect is broken - does not show the queries

### ISSUE THREAD

**Issue by elenorebastian** [grafana/grafana#31459]
**What happened**:
Our queries are not showing up. 

**What you expected to happen**:
We expected our queries to show up.

**How to reproduce it (as minimally and precisely as possible)**:
We went to Inspect --> Data and then navigated to the Query tab. The Query tab shows the Query inspector. When we hit Refresh to get a list of the queries that are being run, the 'Loading query inspector... ' just spins forever. 

**Anything else we need to know?**:
This is happening due to a change in this code:
https://github.com/grafana/grafana/commit/a49daf5676bff0ed5651f7a5c419848c807391a1

We are using a relative path.

Also this code:
https://github.com/grafana/grafana/blob/a18e4d8d6437a0cf57e8ddebe61d36d5ce081e25/public/app/core/utils/query.ts#L23-L37

The way we have set up our Prom data source means it is not recognized as a "DataQuery".

This is how our Prometheus data source is configured:

apiVersion: 1
datasources:
  - name: Chronosphere Prometheus
    type: prometheus
    url: /../data/m3
    access: direct
    isDefault: true
    jsonData:
      httpMethod: POST

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: prometheus
- OS Grafana is installed on: same
- User OS & Browser: chrome
- Grafana plugins:
- Others:
 we're using the stock Grafana Docker image (which I think is Alpine Linux?)

**Comment by torkelo** [comment]
Grafana cannot detect that that URL is going against a datasource query endpoint, only those that query our backend data source api's or data source proxy api will show up in the query inspector
