### ISSUE TITLE
grafana silent crash

### ISSUE THREAD

**Issue by shawnhe** [grafana/grafana#3145]
I am using grafana server 2.0.2, and for some reason, (it seems related to the drag/drop feature on the web browser at least in one instance), the grafana-server would crash without any clear indication what  was the cause. It occurred multiple times now, and I am just curious if it's a known issue and already fixed in the newest version, or not. Thanks.

**Comment by torkelo** [comment]
there has been no reports of crashes in any version, but try upgrading. Did you check the grafana-server logs?

**Comment by shawnhe** [comment]
Not too much output in the log, and I am using the default configure options, should I turn on some flag in order to collect more outputs for the troubleshooting purpose of the crash? In case next one occurs?
