### ISSUE TITLE
User deletion in postgres fails

### ISSUE THREAD

**Issue by cheribral** [grafana/grafana#3146]
This fails with a syntax error.  I have a feeling it is because user is a reserved word in postgres, and would have to be double quoted, but I'm not positive that is the issue.  From the logs I have this:
ERROR:  syntax error at or near "user" at character 13
STATEMENT:  DELETE FROM user WHERE id = $1

http://stackoverflow.com/questions/22256124/cannot-create-a-database-table-named-user-in-postgresql

**Comment by utkarshcmu** [comment]
What should be the solution to this, renaming the table to something else OR changing the backend to use quotes?
