### ISSUE TITLE
Deleting users loses historical information about who edited a dashboard

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#31468]
If a user is deleted, then any history of edits that user made to dashboards is lost, and instead the "updated by" is blank. 

As a minimum, the delete user dialogue should warn that historical actions of this user will also be lost. 
Ideally users should be disabled (and hidden from the user page), not deleted. There should be a new page listing disabled users, with the option to delete them from there, along with the accompanying warning message about historical actions also being lost. 

**What happened**:
Deleting a user caused the historical actions that user performed (such as editing a dashboard) to not be attributed to anyone. 

**What you expected to happen**:
Either action attribution should still be possible, or a warning that deleting a user will prevent this from being possible. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a local user. 
Edit a dashboard with that user, 
Delete that user. 
Go back to dashboard versions view

**Anything else we need to know?**:

Before user delete. 
![image](https://user-images.githubusercontent.com/8004654/109140037-1a789380-7754-11eb-94a6-84ef80eb15fd.png)

After user delete
![image](https://user-images.githubusercontent.com/8004654/109140112-2c5a3680-7754-11eb-9809-9ef0a28ebc0d.png)

**Environment**:
- Grafana version:   7.4.2
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a 
- Grafana plugins: n/a 
- Others:

**Comment by conorevans** [comment]
@aknuds1 I would be interested in looking at this, would that be welcomed? If so, to what extent is the description exact with respect to requirements?

 - give warning that deleting user will delete historical data
 - perhaps display "Deleted user" in the "Updated by" column ?

**Comment by MarcoMusso-TomTom** [comment]
As an admin I would really like to see something "<email|username> (deleted)" but I can see some problem in implementing this if that information is "just not there anymore"... Maybe on user deletion a full "search and replace" on dashboard histories?
Sure keeping a list of disabled users would be nice but indeed seems more "impacting".

**Comment by aknuds1** [comment]
@conorevans I'll see what the rest of the team thinks.

**Comment by aknuds1** [comment]
@conorevans the feature request itself will be discussed among stakeholders, to figure out which changes we eventually should make.

**Comment by conorevans** [comment]
> As an admin I would really like to see something "<email|username> (deleted)" but I can see some problem in implementing this if that information is "just not there anymore"... Maybe on user deletion a full "search and replace" on dashboard histories?

I can't imagine Grafana would operate such a data policy - email is typically considered PII. You cannot "sorta" delete the information as a data owner (either Grafana if they are hosting the server, or whichever company is hosting their own Grafana server).
