### ISSUE TITLE
[Feature Request] Time Slider

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#31478]
**What would you like to be added**:

I would like to see a time slider plugin, that is connected with certain or all panels in the same dashboard. 

Connecting the slider can be done like this:
- We can create a variable (datetime) and change the variable manually using the time slider and use the variable in the panels we want to use that datetime variable.

**Why is this needed**:

Probably, this will have other use-cases but here is how I would use it:

I want to show events (status of some location points) in Worldmap panel. I can display the current status in the map but I would like to add the time dimension to the map. So, time slider would be a great.

Example:
https://plotly.com/python/sliders/

**Comment by natellium** [comment]
Hey @mertbakir, thanks for the request! We're now using github discussions to track feature requests and improve how we engage in feature discovery, development and delivery. Therefore I'm closing this issue but if you still want your feature to be considered it'd be great if you could reopen it as a discussion! [Here](https://github.com/grafana/grafana/discussions/36962) is a bit more info about how to open feature requests as discussions.
