### ISSUE TITLE
Expressions: Add alerting support

### ISSUE THREAD

**Issue by ilya-bukinich** [grafana/grafana#31471]
**What happened**: returned error
```
Validation failed
alert validation error: Data source used by alert rule not found, alertName=Panel Title alert, datasource=__expr__
```

**What you expected to happen**: alert setting expected

**How to reproduce it**:  
set up query ```A``` and ```B``` -> set up math expression ```$B / $A``` as query ```C``` -> set up alert condition ```when function() of query C``` ->  Test rule

**Anything else we need to know?**: it would be useful to use math expressions in alert conditions, for example, to expose the ratio of unsuccessful requests to successful ones as SLO

**Environment**:
- Grafana version: 7.4.x
- Data source type & version: Stackdriver, Cloudwatch, TestData DB
- OS Grafana is installed on: Docker
- User OS & Browser: Any

![2021-02-25 15-16-42](https://user-images.githubusercontent.com/60099021/109152815-0d23cf00-777d-11eb-91c7-1ae9671296f1.gif)

**Comment by ivanahuckova** [comment]
@ryantxu Should I add this feature request for alerting support to any project?

**Comment by kylebrandt** [comment]
Next iteration v8 is intended to support alerting and expressions.
