### ISSUE TITLE
Transform add field from calculation - Binary Operation With ElasticSearch

### ISSUE THREAD

**Issue by cesarmacias** [grafana/grafana#31486]
**What happened**: When use transform add field from calculation with elastic to make a binary operation, if the response is empty the new field data is NaN and all others operations that used this new field have the same result NaN

**What you expected to happen**: I expect the empty value in Math operation will be replaced with Zero

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/492320/109198792-a1d20100-776c-11eb-92b3-40f148fcecb6.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Elasticsearch 7.9.3
- OS Grafana is installed on: Centos 7.9

**Comment by ryantxu** [comment]
If you have only one transform is anything different?

just looking the value for "error_cw Unique Count" is empty... so multiply by .4 would be nan right?

**Comment by cesarmacias** [comment]
can be configurable, like in display Graph. Because in some cases its better zero. In the example NaN as response, make useful the metric.

**Comment by ivanahuckova** [comment]
Hello @cesarmacias, you can use series **override + value mappings** and map your empty values to 0 to do this. 
I have used query inspector and checked what is the returning value for empty table cells. In my case it was null. So I mapped all null values to 0. See images below.  
![image](https://user-images.githubusercontent.com/30407135/109512313-440f2300-7aa4-11eb-8fad-e71d12c24271.png)
![image](https://user-images.githubusercontent.com/30407135/109512380-55f0c600-7aa4-11eb-9c76-afe2dfa30d80.png)
