### ISSUE TITLE
Table: Don't change color for cells with data links 

### ISSUE THREAD

**Issue by KBac** [grafana/grafana#31483]
**What would you like to be added**:
Colorful data links.

**Why is this needed**:
In the table panel I have several columns (host, cluster, instance, etc). And I change text color for each column to make the table readable. Then I add data links to each column (links to related dashboards). And as soon as text in the column becomes a link it becomes white. I can change background color, but the table becomes too colorful in this case.
Please support text color feature for data links.

**Comment by KBac** [comment]
One more point for this feature: if background color is white, then you can't see the white link on it, you want to change text color for it.

**Comment by mdvictor** [comment]
Hey @KBac, with the latest version of Grafana
