### ISSUE TITLE
Could I config X,Y axis units in Explore?

### ISSUE THREAD

**Issue by WangMingJue** [grafana/grafana#31492]
**What would you like to be added**:
       I want to custom config X, Y axis units or values in Explore.

**Why is this needed**:
        I got data from Mysql and show in explore. Then I got time data chart, and my data is two values: 0 or 1.
        But I found values of Y axis has 0.800, 0.600 etc. I just need 0 and 1 in the chart.

**Comment by torkelo** [comment]
Explore has no unit/display options, just raw data exploration. For display options use panel edit under dashboard
