### ISSUE TITLE
Loki: Using backticks in query breaks show context and highlighting 

### ISSUE THREAD

**Issue by baurine** [grafana/grafana#31497]
**What happened**:

When filtering the logs by search expression:

1. If use double quote (") to wrap the search content, and the search content can be normal text or regex but doesn't include backslash (`\`), we can always get the "Show context" link and the search content is highlighted.

    ![image](https://user-images.githubusercontent.com/1284531/109266831-8d146c80-7843-11eb-8991-1f15cd8a9b12.png)

    ![image](https://user-images.githubusercontent.com/1284531/109266880-9dc4e280-7843-11eb-84b0-731fa1572755.png)

    ![image](https://user-images.githubusercontent.com/1284531/109281056-c904fd00-7856-11eb-8121-3f130e43841f.png)
    
    ![image](https://user-images.githubusercontent.com/1284531/109281167-ed60d980-7856-11eb-884d-e0c750c42dd4.png)

1. If use backticks (`) instead of double quote (") to wrap the search content, even the content is normal text, not regex, the result logs don't show "Show context" links. 

    For example, filtering by `|= "uuid"` can get "Show context" link, but "|= \`uuid\`" can't get "Show context" link, and "uuid" content isn't highlighted.

    ![image](https://user-images.githubusercontent.com/1284531/109266980-cea51780-7843-11eb-8d91-9296a9ad5ae4.png)

    ![image](https://user-images.githubusercontent.com/1284531/109267001-d795e900-7843-11eb-87e9-724e2380a0d1.png)

1. If use regex and the regex include backslash (`\`), neither use backticks (`) nor double quote (") to wrap it can get "Show context" link.

    ![image](https://user-images.githubusercontent.com/1284531/109271053-ee3f3e80-7849-11eb-95a0-2b78dea51d77.png)

    ![image](https://user-images.githubusercontent.com/1284531/109282611-b986b380-7858-11eb-9420-6834ce198d75.png)

    ![image](https://user-images.githubusercontent.com/1284531/109271080-f7c8a680-7849-11eb-850e-f78e1a43c462.png)

*Conclusion*: only use the double quote (") to wrap, and the search expression doesn't include backslash (`\`), we can get the "Show context" link, and the keywords are highlighted, all others usage can't get the "Show context" link. It really confuses people.

**What you expected to happen**:

The all above usages should get the "Show context" link and the search keywords should be highlighted as well.

**How to reproduce it (as minimally and precisely as possible)**:

Search the loki logs by using "|= \`foo\`", or `|~ "foo\\w"`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.4.0
- Data source type & version: Loki, the version is same as the grafana
- OS Grafana is installed on: linux
- User OS & Browser: macOS / chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Thanks for creating this issue. Yes this is a bug. I was able to recreate it as well.
