### ISSUE TITLE
Setup grafana with graphite

### ISSUE THREAD

**Issue by Tissa1** [grafana/grafana#3149]
Hi,
I want to make daschbord in grafana using the metris from graphite. I was following this link http://docs.grafana.org/datasources/graphite/ but i didn´t succeed to make a connection between them
![grafana](https://cloud.githubusercontent.com/assets/15192053/10993976/6ea48826-8473-11e5-9270-7ed726168a95.png)
should i make some modification in the configuration, or i have another problem ? I appreciate your help

**Comment by torkelo** [comment]
the url you specified there is it accessible from the grafana-server ?  Can you open chrome dev tools (f12) and network tab and inspect the response from graphite?

**Comment by Tissa1** [comment]
how could i know that is accessible from the grafana-server ?
![graf](https://cloud.githubusercontent.com/assets/15192053/10994337/07bf906c-8476-11e5-917a-8c6de8a9d815.jpg)

**Comment by torkelo** [comment]
by testing the url on the same machine that grafana-server is running on :) 

Also the screenshot is not showing the response. only the headers. 

Is your graphite server working? Check error logs etc

**Comment by Tissa1** [comment]
I have no response from graphite.
