### ISSUE TITLE
Not able to get function work

### ISSUE THREAD

**Issue by sandiphw** [grafana/grafana#3150]
Using grafana 2.1.3 with graphite. I am not able to get any function work. After selecting function from drop-down, it is not applied on the metric, instead treating the full string as a metric. For eg if I apply alias function on a metric "some-metric", it show as alias(some-metric,'alias value'). Please see attached files.What I am missing?

Regards,

Sandip

![front21](https://cloud.githubusercontent.com/assets/1787481/10995720/e3cd54f8-84a4-11e5-891f-3833cdbec5ab.jpg)
![front22](https://cloud.githubusercontent.com/assets/1787481/10995723/ec65ab92-84a4-11e5-9547-5b3e70ff456e.jpg)
![front23](https://cloud.githubusercontent.com/assets/1787481/10995725/f0f610fc-84a4-11e5-82b7-1d708e5eaa2e.jpg)

**Comment by torkelo** [comment]
looks like a problem with your graphite install, it does not seem to handle alias function very well. What version of graphite are you running?

**Comment by sandiphw** [comment]
Thanks for your prompt reply. I shall check the graphite version and let you you. By the way, it is not only able to handle any grafana function, not only alias function.
