### ISSUE TITLE
Anonymous access to profile page changes organization preferences

### ISSUE THREAD

**Issue by rovo89** [grafana/grafana#31507]
**What happened**:
Anonymous users can access `<root_url>/grafana/profile`, e.g. by calling the URL directly or shortcut keys `g` `p`. 

Changes done on this page then **affect the whole organization**, as if done by an admin on `<root_url>/grafana/org`. These settings don't seem to be critical, but it's annoying when curious users change them.

For reference, this screen is shown:
![image](https://user-images.githubusercontent.com/1573299/109286400-77427f80-7822-11eb-8450-2a8b54b41e02.png)

**What you expected to happen**:
Depends on whether it's possible to store these settings as cookie and thus apply them for the current browser (session) only.
If this is supported, the "Save" actions should update those instead of the org. preferences. That would be a feature and could be promoted by making the preferences page appear in the menu for anonymous users.

Otherwise, the profile/preferences page shouldn't be accessible at all for anonymous users, even when the URL is known. 

**How to reproduce it (as minimally and precisely as possible)**:
Configure [anonymous authentication](https://grafana.com/docs/grafana/latest/auth/grafana/#anonymous-authentication). Open `<root_url>/grafana/profile` in incognito mode, change the theme. Verify with another user (or a new incognito session) that the theme has changed.

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: n/a
- OS Grafana is installed on: Linux (SLES 15.1)
- User OS & Browser: Windows 10 / Chrome 88.0.4324.190
- Grafana plugins: n/a
- Others: n/a

**Comment by torkelo** [comment]
thanks for reporting this, We will get this fixed. 
https://github.com/grafana/grafana/pull/31516
