### ISSUE TITLE
Bug in standard visualisation Graph

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#31513]
**What happened**:
Bar Colors wrong. Colors in Hoover are correct, also in Table below the graph.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
See: https://www.zoomsoft.de/grafana
Panel named: "Bezug und Ertrag im letzen Monat" wich is a copy of "Bezug und Ertrag in diesem Monat"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3 (also in 7.4.0/1/2)
- Data source type & version: influxdb 1.8
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: macOS Firefox or iPhone or Windows or or or
- Grafana plugins:
- Others:

Failure:
![grafik](https://user-images.githubusercontent.com/79257887/109307300-b384d880-7840-11eb-9c78-eed9221b5896.png)

Correct:
![grafik](https://user-images.githubusercontent.com/79257887/109307399-df07c300-7840-11eb-810a-a0e970575c25.png)

**Comment by torkelo** [comment]
Need to include panel json (settings), and raw data from inspector / data. 

Is stack enabled?

**Comment by UlrichThiess** [comment]
You could find anything on the website, also the json. Yes, stack is enabled.

`{
  "aliasColors": {
    "Bezug": "semi-dark-red",
    "Bezug in kWh": "semi-dark-red",
    "Ertrag": "semi-dark-green",
    "Ertrag in kWh": "semi-dark-green"
  },
  "bars": true,
  "dashLength": 10,
  "dashes": false,
  "datasource": "InfluxDB",
  "decimals": 3,
  "description": "",
  "fieldConfig": {
    "defaults": {
      "custom": {},
      "thresholds": {
        "mode": "absolute",
        "steps": []
      },
      "unit": "kwatth"
    },
    "overrides": []
  },
  "fill": 1,
  "fillGradient": 0,
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 69
  },
  "hiddenSeries": false,
  "hideTimeOverride": true,
  "id": 105,
  "interval": "1M",
  "legend": {
    "alignAsTable": true,
    "avg": true,
    "current": true,
    "hideEmpty": false,
    "hideZero": false,
    "max": true,
    "min": true,
    "rightSide": false,
    "show": true,
    "total": true,
    "values": true
  },
  "lines": false,
  "linewidth": 1,
  "nullPointMode": "null",
  "options": {
    "alertThreshold": true
  },
  "percentage": false,
  "pluginVersion": "7.4.3",
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "alias": "Bezug",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        }
      ],
      "measurement": "vebus/Ac/ActiveIn/L1/P",
      "orderByTime": "ASC",
      "policy": "venus_default",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "integral"
          },
          {
            "params": [
              "/3600/1000"
            ],
            "type": "math"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Ertrag",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        }
      ],
      "measurement": "solarcharger/Yield/Power",
      "orderByTime": "ASC",
      "policy": "venus_default",
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "value"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "integral"
          },
          {
            "params": [
              "/3600/1000"
            ],
            "type": "math"
          }
        ]
      ],
      "tags": []
    }
  ],
  "thresholds": [],
  "timeFrom": "now/y",
  "timeRegions": [],
  "timeShift": "1y/y",
  "title": "Bezug und Ertrag im letzten Jahr",
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "transformations": [],
  "type": "graph",
  "xaxis": {
    "buckets": null,
    "mode": "time",
    "name": null,
    "show": true,
    "values": []
  },
  "yaxes": [
    {
      "$$hashKey": "object:94",
      "decimals": 1,
      "format": "kwatth",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "$$hashKey": "object:95",
      "decimals": 2,
      "format": "kwatth",
      "label": "",
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ],
  "yaxis": {
    "align": false,
    "alignLevel": null
  }
}`

**Comment by torkelo** [comment]
It looks correct, one of the graphs (the Failure) has dynamic axis min value so you do not see the full height of the red bar

**Comment by torkelo** [comment]
Set min 0 on the left y axis options

**Comment by UlrichThiess** [comment]
Thanks a lot. I'm so sorry to waste your time. I never looked left to see the valuerange of the axis. Beg my pardon.
