### ISSUE TITLE
[BUG] Table column alias not working with multiple Elasticsearch queries

### ISSUE THREAD

**Issue by AlrikG** [grafana/grafana#31517]
**What happened**:

I am using an elasticsearch data source and want to use a table with multiple queries grouped by terms. Each query filters some different data from the elastic index and sums it up. The problem with this is to distinguish table columns between the different summary queries. This should be possible by setting a unique alias for each query, but here comes the bug. The alias only works for "data histogram", but not for "terms". Each column has the same name (Sum 1, Sum 2, ...), which is a problem for me.

Working alias with date histogram:
![bug4](https://user-images.githubusercontent.com/1376505/109316401-dff22200-784b-11eb-90f7-c8b7fce8a95f.png)

Alias bug with terms:
![bug3](https://user-images.githubusercontent.com/1376505/109316417-e54f6c80-784b-11eb-9266-0c9c3879fad1.png)

**What you expected to happen**:

The query alias should behave the same way for "term" aggregations as it does for "data histograms" with multiple queries.
"Alias A" instead of "Sum 1"
"Alias B" instead of "Sum 2"

**How to reproduce it (as minimally and precisely as possible)**:

- Create multiple elastic queries
- use "Terms" for Group by
- use "Sum" Metric for each query
- set unique alias for each query
- add outer join transformation to group by common data fields like timestamps or reference names

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3 (010f20c1c8)
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Grafana Playground
- User OS & Browser: Linux Mint 21, Google Chrome 88.0.4324.182

**Comment by ivanahuckova** [comment]
@AlrikG thanks for creating the issue. I was able to reproduce it on grafana.play.

**Comment by ivanahuckova** [comment]
Actually, I have found the duplicate issue https://github.com/grafana/grafana/issues/27521 so closing this issue.
