### ISSUE TITLE
Metrics Field, when loading, is deleting text which is highlighted

### ISSUE THREAD

**Issue by Zauxst** [grafana/grafana#31529]
**What happened**:  
Highlighting text while the metrics are getting loaded is going to delete all that is highlighted. 

**What you expected to happen**: 
1, Not delete highlighted text after the metric has loaded
2. Not load the metrics when the metrics have not changed or when a label is changing

**How to reproduce it (as minimally and precisely as possible)**:
Prereq:
- Prometheus Datasource with over 10k series.

Steps:
1. Edit a visualisation.
2. add a metric, for example: "http_responseCodes_ok_total"
3. The metric will start loading. if you highlight the any text, once the metric is loaded it will delete the text.

**Anything else we need to know?**:
This is very annoying to work with since I always have to ensure the "Metrics" have loaded so I can start changing or copy pasting stuff in or out. I think this problem is a major level issue.

**Environment**:
- Grafana version: v7.3.1
- Data source type & version: Prometheus v2.23.0
- OS Grafana is installed on: Docker
- User OS & Browser: Windows + brave/chrome/firefox
- Grafana plugins: Core + Worldmap Panel, Pie Chart, Diagram, Discrete, DevOpsProdigy KubeGraf, Clock
- Others: This happens in "Explore" as well. You have to hit the auto-refresh. Every time the query is run the "metrics" is changed to "loading metrics...", once it's close to finishing the request it's going to delete the text that is highlighted.

**Comment by ivanahuckova** [comment]
Hello @Zauxst, this issue was fixed by https://github.com/grafana/grafana/pull/28622 in Grafana 7.3.2. Please update your Grafana to version 7.3.2+.

**Comment by Zauxst** [comment]
Thank you very much @ivanahuckova. I'll upgrade to latest version and test.
