### ISSUE TITLE
Always 2 trailing zeros on the y-axis with unit "Percent (0.0-1.0)"

### ISSUE THREAD

**Issue by istvanballok** [grafana/grafana#31536]
**What happened**:

This issue is intentionally a duplicate of #31397 and #31519.

**What you expected to happen**:

Let's take the following estimates of pi: `3.1415`, `3.14159265359` and try to plot them as a percentage.

<img width="1455" alt="image" src="https://user-images.githubusercontent.com/23032437/109459937-10120e80-7a60-11eb-9df2-d25f8e214753.png">

The first 2 panels show that for both percentage units (0-1, 0-100) the decimals (3) are properly displayed on the y-axis, but with the 0-1 variant we always have 2 trailing zeros, and hence we get only 1 significant digit after the decimal point.

The 3rd panel shows the expected behavior: with 3 decimals, I'd expect 3 significant digits after the decimal point. This visualisation can be achieved with the 0-100 variant, but not with the 0-1 variant - this is the behaviour that I'd consider a bug.

**Environment**:
- Grafana version: 7.4.3

**Comment by ivanahuckova** [comment]
@istvanballok I see what you mean. Basically the **Percent 0-1, decimals, always trailing zeroes (bug)** graph is visually less detailed because the values on the x-axis are rounded up and down compared to the graph below it. The graph is basically correct, but again, less detailed on the first sight. I am going to pass it to @grafana/grafana-frontend-platform to determine if this is a bug.

**Comment by dprokop** [comment]
@istvanballok is this the new Time Series panel that you use?

**Comment by istvanballok** [comment]
> is this the new Time Series panel that you use?

@dprokop No, it is the graph panel.

**Comment by hugohaggmark** [comment]
Confirmed in Grafana Play (https://play.grafana.org/d/FsVgn0UGk/always-2-trailing-zeros-on-the-y-axis-with-unit-percent-0-0-1-0-31536?orgId=1)

**Comment by torkelo** [comment]
The problem is that the unit percent is applied after ticks are assigned, so the graph will assign a tick value of 3.142 , and then Grafana will show that using the supplied unit and decimals, so times 100 and 3 decimals becomes 314.200 

There is no real way around this
