### ISSUE TITLE
Option to Disable "Copy shortened link" Button

### ISSUE THREAD

**Issue by midnightconman** [grafana/grafana#31532]
**What would you like to be added**:
I would like a config option to disable short-url api and create shortened link button. We run our grafana instances in "kiosk mode" in a mostly read-only fashion -- so we don't want people having the option of creating short-urls. We would prefer to hide the button and disable the api.

**Why is this needed**:
Without this, people can create short-urls for a read-only grafana instance running in a "kiosk" configuration, which adds entries to the local sqlite db that shouldn't be added (as the instance is read-only).

**Comment by gelicia** [comment]
I'm bringing this up to our dashboards team to figure out if we would want to do something in tandem with their short URL feature.

**Comment by gelicia** [comment]
Got a tip from @ifrost that this might actually be solved. You can append '&kiosk' to the end of an explore URL to run it in kiosk mode, which will hide the short link button. If this doesn't solve your use case, please create a [discussion](https://github.com/grafana/grafana/discussions) with details on what you are looking for.
