### ISSUE TITLE
Grafana 2.x should respect glob order when stacking metrics

### ISSUE THREAD

**Issue by JeanFred** [grafana/grafana#3154]
I want to use Grafana to plot stacked globbed metrics in a specific order.

In particular:
```
aliasByNode(hosts.app.host.memory.memory.{used,free,buffered,cached}.value, 7)
```
using a glob `{used,free,buffered,cached}` (and not a wildcard) as I want the values stacked in that particular order. This used to work with Grafana 1.9.

With Grafana 2.5, the series are always ordered (and stacked) alphabetically.

**Comment by torkelo** [comment]
@JeanFred this is controlled by Graphite, Grafana will use the order that Graphite returns series in, this has always been the case so no difference in this regard between Grafana 2.5 and 1.9 , so please forward this feature requrest to the graphite project :)

**Comment by JeanFred** [comment]
@torkelo Oh I see! At the same time I was upgrading Grafana I also upgraded my Graphite from 0.9.12 to 0.9.13. Something must have changed between these two.  Thanks for the answer!

**Comment by Dieterbe** [comment]
The upcoming graphite release will have some more ordering fixes BTW

**Comment by Dieterbe** [comment]
http://obfuscurity.com/2015/11/Graphite-0.9.14-the-Highlights
