### ISSUE TITLE
RGL future (grafana dependency)

### ISSUE THREAD

**Issue by JamesRamm** [grafana/grafana#31543]
I understand that react-grid-layout is a fairly key dependency of grafana yet the project itself is more or less [dead](https://github.com/STRML/react-grid-layout/issues/1404).

Rather than fragmenting the big community around this project, it could be good to gather round a single fork of the project (under an umbrella organization). 
Is there any interest from the grafana devs in joining a new fork as a maintainer(s)? 

From the amount of ignored issues & PR's, there is clearly huge interest in further improving RGL and a quick browse through the grafana code shows that there are areas of RGL you prefer not to use and reimplement (e.g. responsiveness and for good reason I think), or further functionality could be added or streamlined.

**Comment by torkelo** [comment]
yes, we can definitely help maintain a fork.

**Comment by STRML** [comment]
@torkelo See also https://github.com/react-grid-layout/react-grid-layout/issues/1404#issuecomment-788042105. I love that Grafana uses this lib and I'm sorry I haven't had more time to maintain it. I would be happy to help you or your maintainers get involved and avoid a fork, if you like.
