### ISSUE TITLE
Legend overlaps with X axis info

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#3155]
![image](https://cloud.githubusercontent.com/assets/71193/11002861/6fd9baa4-8496-11e5-992d-15ea16f96627.png)

As in the screenshot above, the TX and RX texts overlaps with the timestamps when the graph is small

**Comment by torkelo** [comment]
can you replicate this consistently? 

I have tried numerous times to replicate it but only seen it once. 
![image](https://cloud.githubusercontent.com/assets/10999/11003007/924c7dc8-84b0-11e5-9beb-648057528db8.png)

**Comment by vitorboschi** [comment]
Yes, I have many dashboards I can do that. You'd just have to resize the dashboard so that date and time are split in two lines (like in your screenshot).

**Comment by torkelo** [comment]
but does the problem always appear? as you can see in the screenshot it looks fine for me.

**Comment by vitorboschi** [comment]
Yes, I can reproduce it in any dashboard that I have here. I'm currently in version 2.5.0

**Comment by vitorboschi** [comment]
It may be related to the browser rendering. 
The problem appears in Google Chrome, but I coudn't  reproduce the problem in Firefox (It doesn't even split date and time on two rows).
I'll try in other machines/browsers and report back my findings

**Comment by torkelo** [comment]
can you still replicate this?

**Comment by vitorboschi** [comment]
Yes, still happens in Grafana 3.1.0

**Comment by haizaar** [comment]
It was happening consistently enough to encourage me to open the original bug. However indeed I can't reproduce it anymore now.

**Comment by haizaar** [comment]
It's back again. Refresh does not solve it (like it didn't last time). Hopefully it will go away soon. What I did is playing with row heights and putting several wide panels on a single row that made it wrap to a next line.

**Comment by torkelo** [comment]
should be fixed in master
