### ISSUE TITLE
Explore: Dedup button on top of Loki log context modal

### ISSUE THREAD

**Issue by ian-llewellyn** [grafana/grafana#31550]
**What happened**:
Using the Loki datascource, after clicking "Show context" for a log line in the Logs area of the Explore UI, the selected Dedup button remains in view (z-index: 3) on top of the context modal (z-index: 2).

**What you expected to happen**:
The selected Dedup button should become invisible behind the log context modal view.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a LogQL query with any filter (ex. |= "level")
2. Click "Show context" on any of the log lines near to the top
3. Witness the overlap

**Anything else we need to know?**:
3rd log line in attached image is obscured by the "none" Dedup button.
![image](https://user-images.githubusercontent.com/451335/109506605-bcbab300-7a95-11eb-8455-9cfed394dd39.png)

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Loki 2.1.0
- OS Grafana is installed on: minikube v1.16 (Kubernetes v1.20.0) on Fedora 32
- User OS & Browser: Chrome on Fedora 32
- Grafana plugins: None
- Others:

**Comment by ivanahuckova** [comment]
@ian-llewellyn the issue was fixed in https://github.com/grafana/grafana/pull/30939 and will be part of 7.5.0 release.
