### ISSUE TITLE
How to serve ES6 module with `grafana-toolkits plugin:dev`?

### ISSUE THREAD

**Issue by smarkm** [grafana/grafana#31555]
I got this tip from [Grafana: packages/grafana-toolkit/README.md | Fossies](https://fossies.org/linux/grafana/packages/grafana-toolkit/README.md) suggests to " remove the ES2016 code from your comments", is there another way to allow load ES module? the plugin:build can work well, so should be have another way to allow it?

**What would you like to be added**:
Serve ES6 module with `grafana-toolkits plugin:dev`

**Why is this needed**:
easy for debug plugin with third part lib

**Comment by yangliuyu** [comment]
I found a workaround but may not be a perfect solution.

Add webpack.config under the project root with:
```javascript
const TerserPlugin = require("terser-webpack-plugin")

module.exports.getWebpackConfig = (config, options) => {
    const compressOptions = { drop_console: false, drop_debugger: false };
    return {
    ...config,
        plugins: [...config.plugins, new TerserPlugin({ terserOptions: { compress: compressOptions } }),],
    }
};
```

Add terser-webpack-plugin in your package.json:
```javascript
  "devDependencies": {
    "@grafana/data": "latest",
    "@grafana/toolkit": "latest",
    "@grafana/ui": "latest",
    "emotion": "10.0.27",
    "prettier": "^2.3.2",
    "terser-webpack-plugin": "^2.3.8"
  },
```
Then try again( yarn && yarn watch).
In my case echarts 4.9.0 works without any modification but echarts 5.1.2 failed with `Unable to dynamically transpile ES module A loader plugin needs to be configured via SystemJS.config({ transpiler: 'transpiler-module' }).` I delete all comments in my code but the error is still there. So I think maybe it's the problem in echarts comments. @ivanahuckova is there any possible to optimize with my scenario which is dependent libs has some es2016 code in comments?

**Comment by night1008** [comment]
I have the same issue, when using echarts 5.1.2

**Comment by starkblaze01** [comment]
I had the same issue, for a workaround disabled all the tests and used the `build` command instead of `dev`
