### ISSUE TITLE
ROADMAP.md is wrong

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#31569]
In the grafana/grafana repository, [ROADMAP.md](https://github.com/grafana/grafana/blob/master/ROADMAP.md) instructs the user to go to the Issues tab and refer to the three pinned issues there to view the current roadmap.

There are no pinned issues.

ROADMAP.md needs to have correct information so that users can find our roadmaps.

Attn: @marcusolsson and @briangann

**Comment by daniellee** [comment]
@oddlittlebird this one is my court. We will be publishing a public roadmap soon and I will update this file then.

**Comment by oddlittlebird** [comment]
@achatterjee-grafana, you might want to follow up with @daniellee

**Comment by IARI** [comment]
Any update on the Roadmap perchance? :)

**Comment by achatterjee-grafana** [comment]
@daniellee, do we know when the roadmap will get updated? Thank you for any clarification!
