### ISSUE TITLE
Add Font Awesome Icons

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#31562]
**What would you like to be added**:

I would like to be able use fontawesome (or some other) icons inside the panels. It would be useful in "Stat" panel, table panel. Emojis/Icons should be set as

- Field > Display Name
- Field > No Value
- Field > Value Mapping
- Transform > Organize Fields

**Why is this needed**:

I have use case, where I'm going to repeat "Current", "Previous" in multiple panels. It would be better to indicate these words with simple icons.

Another use case I can think of is indicating status (crit, warning, ok).

**Comment by therealcodlord** [comment]
I asked for this feature some time ago. At that time I was told Emoji is supported which it is (at least on most devices).

You just need to cut/past the Emoji from somewhere like [http://getemoji.com/](http://getemoji.com/) anywhere you can enter text). I guess it is unlikely that Font Awesome support would be added even though I think it would be great to be able to use the full range of Font Awesome icons in Grafana and not just Emoji.

The old v6 table panel (which is still usable in current versions of Grafana) it's possible to use font awesome icons as you can enable the `Sanitize HTML` option on the `Column Styles` section which will then render any HTML you choose to output. 

So Emoji is quick and easy and already supported so for your current/previous you should be able to use arrow emoji etc.

**Comment by torkelo** [comment]
Yea for emoji just paste it in, we wont add support for custom icons, maybe images ini value mapping or thresholds states

**Comment by mertbakir** [comment]
I'm aware of that we can copy/paste emojis. We can also use unicode characters as icons but full support of Font Awesome could be useful. Icons are eye-catching. Imagine a dashboard for an IoT device, we can find icons for temperature, pressure and other metrics. Emojis doesn't cover that. Also emojis may look unprofessional in some cases.
