### ISSUE TITLE
DashboardPage tests: rewrite tests to react-testing-library

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#31566]
Currently, those tests are implemented with Enzymy making them hard to DOM-test. Rewrite them do RTL should make our life easier going forward.

**Comment by cunyat** [comment]
Hi! I would like to help here, 
I've investigate a bit, would be correct to take SoloPanelPage tests as reference to rewrite DashboardPage?
I tried to adapt a bit and for the moment it works correctly, if this approach is fine for you, I'll progress with this and create a PR :)

**Comment by zoltanbedi** [comment]
Hi @cunyat, please go ahead and do that. Thanks for helping with this.

**Comment by tharun208** [comment]
@zoltanbedi I like to work on this

**Comment by zoltanbedi** [comment]
Hi @tharun208,
thank you for helping! Let us know in our public slack channel if you need help!

**Comment by tharun208** [comment]
@zoltanbedi I raised a PR

**Comment by ashharrison90** [comment]
done by https://github.com/grafana/grafana/pull/36460
