### ISSUE TITLE
Add option to supress invalid data when templating/repeating panels

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#3156]
![image](https://cloud.githubusercontent.com/assets/71193/11003357/1c723564-8499-11e5-9676-2878fcf98dbc.png)
The open list got its data from tab_values query (OpenTSDB backend), however it doesnt't have any way to filter values for the host I selected before, so some of the values are not valid for the current host.
When using repeated panels, I'd like to be able to make Grafana supress invalid values on the list, or at least supress the panels that get no data.

**Comment by torkelo** [comment]
This might be an issue for OpenTSDB or how you setup your template variables.

If your template variables are not setup correctly or OpenTSDB returning non relevant tag values

**Comment by vitorboschi** [comment]
The problem is that tag_values() accepts just a metric name and the tag for which I want the values, but I cannot say something like tag_values(os.net.bytes{host=host1},iface), so that it can limit iface just to values present when host=host1 (or host=$Server, in my case)

**Comment by utkarshcmu** [comment]
@vitorboschi I agree that Grafana templating has no support for filtering template variables based on any tags. Template variables just get all the possible values of a tag name for a given metric. There should be a feature though as it is very useful if we can filter the template variables based on other tags also as you mentioned above.

@torkelo we should reopen this issue and add this issue as a feature request for "enable filtering by other tags in templating".

**Comment by digrich** [comment]
I am also feeling the need to filter tag values by other tags in templating. 

In my case, I am using same opentsdb datasource to monitor machines from multiple environments. Now for the dashboard, I need to filter out hosts by environment tag to have filtered list of hosts on the dashboard.

**Comment by gkoerdt** [comment]
Sorry for reopening this case. But is there now a solution or workaround for this?
We use TSDB and Grafana to visualize our icinga measurements. 

We build a dashboard where we can select the host via dropdown box with “tag_values(rta, host)” and in a second dropdown box we can select the service of the host with “tag_values(In, service)”.
We have thousands of hosts and much more services, so it necessary that it only shows the services of the selected host and not all.

We are evaluating this setup because we have to find an alternative for our RRD system.

**Comment by torkelo** [comment]
then in your service variable only query for services that exist on those hosts.

**Comment by gkoerdt** [comment]
Can you please tell me how i can do it? Here is our current query:
![grafana](https://cloud.githubusercontent.com/assets/20124982/17729466/a61939c4-6464-11e6-9c49-7c7108f4d0ba.PNG)

**Comment by torkelo** [comment]
maybe `tag_values(In, service, host=$host)`

**Comment by utkarshcmu** [comment]
@gkoerdt This should help :

https://github.com/grafana/grafana/pull/5343/commits/f3003a97ef73b7eca2bd6cd2fdd97c40503c3824

**Comment by gkoerdt** [comment]
>> tag_values(In, service, host=$host)  
was the solution!!  Thank you all.
