### ISSUE TITLE
Grafana unable to start after upgrade from 7.3.x to 7.4.x due to "gel" plugin

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#31561]
**What happened**:
After upgrading Grafana from 7.3.7 to 7.4.3, Grafana becomes unable to start up.

Logging gets stuck while trying to load the GEL plugin:

```
t=2021-02-24T17:45:56+0000 lvl=dbug msg="Found plugin" logger=plugins id=gel signature=valid hasRoot=false
t=2021-02-24T17:45:56+0000 lvl=dbug msg="Plugin has valid signature" logger=plugins id=gel
t=2021-02-24T17:45:56+0000 lvl=dbug msg="Attempting to add plugin" logger=plugins id=gel
```

**What you expected to happen**:
Grafana should start after upgrade from 7.3 to 7.4.

**How to reproduce it (as minimally and precisely as possible)**:
I _think_ this can be easily reproduced by upgrading Grafana from a 7.3 version which includes the GEL plugin to 7.4.x (which has moved the GEL plugin to the core).
 
This issue was described exactly by @aknuds1 in this closed issue comment:
https://github.com/grafana/grafana/issues/31061#issuecomment-776562354 
>Ah, I recognize the problem. It's an issue with upgrading from 7.3 to 7.4, where a bundled plugin (GEL) is left behind, that is now in the core. Try removing plugins-bundled\gel-0.6.0.

However, unlike what was assumed in that previous issue, I think the issue affects **_all_ OS**, not just Windows.

**Anything else we need to know?**:
Here is the original GEL plugin repo: https://github.com/grafana/gel-app

I am not sure when that was first added to Grafana. But as noted in the readme:
>**Note**: This is now retired archived, the code is now part of Grafana core in pkg/expr as of https://github.com/grafana/grafana/pull/29072.

Per that PR ^^, this happened in 7.4.0.

Deleting that "plugins-bundled\gel-0.6.0" folder is the successful workaround for this issue, which is proof that the GEL plugin folder causes the problem.

**Environment**:
- Grafana version: 7.3.7 -> 7.4.3
- OS Grafana is installed on: Linux (SUSE Linux Enterprise Server 12 SP5)

**Comment by torkelo** [comment]
@kylebrandt can we add an ignore for this plugin so Grafana does not try to start it?

**Comment by kylebrandt** [comment]
> @kylebrandt can we add an ignore for this plugin so Grafana does not try to start it?

We could I think, perhaps by adding a return around:

https://github.com/grafana/grafana/blob/b99127be82b49a84d44dc6f55faea90679f6d683/pkg/plugins/plugins.go#L192

However, I'm not sure what I did wrong in the first place, as I thought I cleaned up the stuff around the code. If that is true, that it probably means we need to the installer to be able to remove bundled-plugins or else we might just end up hitting this again in the future if we ever remove a bundled plugin.

Thoughts @aknuds1 ?

**Comment by aknuds1** [comment]
@kylebrandt might it be an idea to have a manifest of bundled plugins, so other plugins in plugin-bundled/internal are ignored?

**Comment by torkelo** [comment]
Closing this
