### ISSUE TITLE
The combination of link and image is not working in table

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#31576]
I have a table that I want to use an image as a link
I added a label with a fix value and map it to a base64, it looks correct:
![image](https://user-images.githubusercontent.com/2118079/109617882-98b3ac00-7b3f-11eb-938b-03052c03fac2.png)

**What happened**:
I add a link to the cell, but it does not work
**What you expected to happen**:
Without the image mapping you can see that it is a link
![image](https://user-images.githubusercontent.com/2118079/109618423-31e2c280-7b40-11eb-9b5d-a7956db2da14.png)

**How to reproduce it (as minimally and precisely as possible)**:
Add a table, pick a value and map it to base64 image, add a link to that cell
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5
- Data source type & version: alertmanager
- OS Grafana is installed on: docker
- User OS & Browser: fedora
- Grafana plugins: alertmanager

**Comment by ivanahuckova** [comment]
Thanks for creating the issue. I was able to reproduce it. 
https://user-images.githubusercontent.com/30407135/109944437-8455e780-7cd6-11eb-850b-a11b5ec51d05.mov
