### ISSUE TITLE
Remove gradient color from stat plugin

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana#31577]
Hi :)

Is there a way to remove the automatic gradient of the stats plugin ? 
When I choose a color, it put automatically a gradient on it: 
![image](https://user-images.githubusercontent.com/24936778/109618959-7b2f1400-7b38-11eb-9468-cb48041ba4af.png)

Color that i choose: 
![image](https://user-images.githubusercontent.com/24936778/109618871-60f53600-7b38-11eb-8682-f992f83be412.png)

thx :)

**Comment by torkelo** [comment]
No, there is no option for this

**Comment by eglyn** [comment]
Ok, so sad, gradient is so ugly (in my opinion :D)

Thx for your answer :)
