### ISSUE TITLE
Explore: TypeError: Cannot read property 'emit' of null

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#31585]
**What happened**:
[From Sentry (7 times)](https://docs.google.com/spreadsheets/d/1xpUL9WLO01fX-FxOl-9sb1omobiQeIq3CYDFV6FHd6g/edit#gid=1280620028):
`TypeError: Cannot read property 'emit' of null`
`at emit (core|webpack:///./public/app/features/explore/state/query.ts:666:22)`

**Comment by davkal** [comment]
@grafana/grafana-frontend-platform this is from Explore's processQueryResponse action, and it emits an event to the eventBridge for angular editors, is this still needed?

**Comment by ivanahuckova** [comment]
ping @grafana/grafana-frontend-platform

**Comment by hugohaggmark** [comment]
Hmm, not sure I'll have a look

**Comment by hugohaggmark** [comment]
Seems, like several SQL datasources are listening on those events and the old Table.
