### ISSUE TITLE
Apply regular expression on metric name

### ISSUE THREAD

**Issue by ffosselle** [grafana/grafana#3159]
Hi,

I've been using 2.5 for a couple of weeks now and I'm so in love with the ES support . Thank you for all the effort put in. It is a great addition to an already wonderful product.

I have a question around metric naming. I've been scratching my head how I could shorten the metric names coming out of ES. Please take a look at the example below.  

<img width="804" alt="dashboard example" src="https://cloud.githubusercontent.com/assets/1826475/11014611/eb328872-853e-11e5-8563-2c22c4783f81.png">

The chart is showing two values: sys_mem_virtual_usage_percent and sys_mem_physical_usage_percent. Showing the third piece of the name would already be enough.

Any idea how this can be done on a ES datasource?

Best,
Frederic.

**Comment by torkelo** [comment]
you can use the alias field
