### ISSUE TITLE
$__rate_interval is not supported by Loki datasource

### ISSUE THREAD

**Issue by dannykopping** [grafana/grafana#31593]
**What happened**:
`$__rate_interval` is not supported by the Loki datasource.
Using `rate({app="foo"}[$__rate_interval])` results in:
> parse error at line 0, col 17: not a valid duration string: "$__rate_interval"

**What you expected to happen**:
`$__rate_interval` should not be shown.

**How to reproduce it (as minimally and precisely as possible)**:
Run `rate({app="foo"}[$__rate_interval])` against a Loki datasource in Explore view or in a dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v7.5.0-12932pre (4c0e2c3174)`
- Data source type & version: Loki datasource
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
We should remove "$__rate_interval" option from the autocomplete as "$__rate_interval" option is not needed for Loki.

**Comment by dannykopping** [comment]
> We should remove "$__rate_interval" option from the autocomplete as "$__rate_interval" option is not needed for Loki.

Ah, I seem to have not mentioned autocomplete anywhere in my bug report :slightly_smiling_face:
Thanks for the clarifications @ivanahuckova
