### ISSUE TITLE
support syslog log output

### ISSUE THREAD

**Issue by mischief** [grafana/grafana#3160]
the log driver doesn't support syslog, and this is a poor hack.

```
./bin/grafana-server cfg:log.console.formatting=false  2>&1 | logger -i -p local7.info -t grafana
```

**Comment by piotr1212** [comment]
Your PR is a good improvement, but I would rather see a configurable log library like https://github.com/Sirupsen/logrus which supports multiple outputs like systemd-journal, graylog, sentry, etc. 
Anyway, supporting plain syslog is much better than having only file/stdout!

**Comment by lust4life** [comment]
```
go build -ldflags -w -X main.version=2.6.0 -X main.commit=v2.6.0+6-g655a31c -X main.buildstamp=1450190685 -o ./bin/grafana-server.exe .
# github.com/grafana/grafana/pkg/log
pkg\log\syslog.go:10: undefined: syslog.Writer
```

when build in windows, it shows this. 
https://golang.org/pkg/log/syslog/#pkg-note-BUG

does this mean , it just can not build from win ? 
i just wonder how does the bin zip in here : http://grafana.org/download/  generated ?
thank you for your reply. : )

**Comment by bergquist** [comment]
You should be able to build it on windows. 
Just make sure you have this commit as well https://github.com/grafana/grafana/commit/b63471ebe950cce50b13cf53541a837a67c4ab09

This is our successful build for windows
 https://ci.appveyor.com/project/Torkeldegaard/grafana

**Comment by lust4life** [comment]
@bergquist tks :+1:  it works

**Comment by mischief** [comment]
@lust4life glad i could help :-)
