### ISSUE TITLE
SlackNotifier: Support a single  web hook URL for every channel

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#31609]
**What would you like to be added**:
For Slack notifier, support a single  web hook URL for every channel. 

Requested by a Grafana Labs customer.

**Comment by davidnewhall** [comment]
Every time a Slack notification channel is added, the admin has to copy/paste the Slack Webhook URL into the integration. When using legacy slack webhooks (which work great in Grafana), the admin pastes the same URL into every slack channel integration. A more convenient approach would be to take in a Slack webhook URL once, mark it as default and re-use (or allow selecting) it on any new slack channel. This allows us to keep the secret URL in one place, and reduces exposure.
