### ISSUE TITLE
Chore: remove resolution for `react-use-measure` from package.json

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#31602]
**What would you like to be added**:
When this PR (https://github.com/pmndrs/react-use-measure/pull/38) have been merged and the https://github.com/airbnb/visx/tree/master/packages/visx-tooltip have been updated to use the new version we should remove the resolution added to package.json.

See the referenced PR for more information.

**Comment by hshoff** [comment]
thanks @mckn, visx is also tracking the `react-use-measure` update here: https://github.com/airbnb/visx/issues/1091

**Comment by mckn** [comment]
> thanks @mckn, visx is also tracking the `react-use-measure` update here: [airbnb/visx#1091](https://github.com/airbnb/visx/issues/1091)

Awesome, thanks 🙏

**Comment by mckn** [comment]
Closed by: https://github.com/grafana/grafana/pull/32248
