### ISSUE TITLE
Table: Improve Gradient/Basic Gauge in cell value width so all rows align 

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#31610]
**What happened**:

I have 2 suggestions here, both are small visual details:

- When number of digits are not same across the column, it effects the gradient bar sizes, so some bars becomes smaller. (e.g. 9.30%, 10.30% or 103%, 97% in the image.)
- Even though the max value is 1, and the value surpasses it, bar doesn't seem full. There is a small gap at the end of the bar.

![image](https://user-images.githubusercontent.com/43188411/109682825-d2ac9e80-7b8f-11eb-9e63-2e46c0aafe35.png)

- There is no gap at 100% but at >100%

![image](https://user-images.githubusercontent.com/43188411/109684209-181d9b80-7b91-11eb-9ccc-b025eef2c87b.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3

**Comment by torkelo** [comment]
This will only be a problem for very small columns, it's tricky. Grafana would have to render all values to strings and measure the longest one and use that as a guide and there could be many thousands of rows.

**Comment by torkelo** [comment]
think this is fixed in v7.5

**Comment by torkelo** [comment]
or if you have very narrow column width
