### ISSUE TITLE
Support time filter for MS-SQL BIGINT TimeStamp 

### ISSUE THREAD

**Issue by coderReview** [grafana/grafana#31623]
Support time filter for MS-SQL BIGINT TimeStamp.

Avoid having to do conversions in the query which slows down the performance.

Conversion from BIGINT TimeStamp to Unix Milliseconds

````java
public long ToUnixTimeMilliseconds()
{
   return this.UtcDateTime.Ticks / 10000L - 62135596800000L;
}
````

**Comment by torkelo** [comment]
there already exists macros for time filters:
https://grafana.com/docs/grafana/latest/datasources/mssql/#macros 


$__timeFilter(dateColumn) | Will be replaced by a time range filter using the specified column name.For example, dateColumn BETWEEN ‘2017-04-21T05:01:17Z’ AND ‘2017-04-21T05:06:17Z’
-- | --
$__timeFrom() | Will be replaced by the start of the currently active time selection. For example, ‘2017-04-21T05:01:17Z’
$__timeTo() | Will be replaced by the end of the currently active time selection. For example, ‘2017-04-21T05:06:17Z’

**Comment by coderReview** [comment]
hi @torkelo I don't see how `$__timeFilter(dateColumn)` can used as the column is not a Date column but like UnixEpoch it's a `BIGINT`.

**Comment by coderReview** [comment]
Updated the title and description @torkelo

**Comment by kylebrandt** [comment]
Could you take the macros `$__unixEpochTo()` (and from), and cast them as a BIGINT in your where clause (multiplying by 1000), while still selecting a DATETIME() or whatever in the select clause?

I would hypothesize that this would still be fast at the database level - conversion only for returned items, and not for the filtering/indices.

**Comment by coderReview** [comment]
My suggestion is to have a macro that converts the dates Grafana selects to Time BIGINT format.
Which is the inverse of the above function if you have unix epoch in milliseconds.
Using the macro with math operations doesn't work very well.

**Comment by ivanahuckova** [comment]
@kylebrandt @torkelo what is the status of this issue? Do we need any additional information? I have removed `needs more info` label for now and passed this to backend platform backlog.

**Comment by torkelo** [comment]
It's a feature request
