### ISSUE TITLE
Flux: Query inspector data frame results not decoded

### ISSUE THREAD

**Issue by matteo-zanoni** [grafana/grafana#31620]
**What happened**:
I query data using InfluxDB datasource with Flux query language. Data is returned as expected but when I use the query inspect feature the result appears as dataframes that contain long strings of alphanumeric characters. This makes it impossible to debug/troubleshoot query results.

<img width="830" alt="Schermata 2021-03-02 alle 21 46 13" src="https://user-images.githubusercontent.com/56115369/109712792-c0872c00-7ba0-11eb-8d9f-a9ebb67732ec.png">

**What you expected to happen**:
I expected the response to be an object expandable and readable like the following one:

<img width="830" alt="Schermata 2021-03-02 alle 21 47 59" src="https://user-images.githubusercontent.com/56115369/109712979-f7f5d880-7ba0-11eb-81e3-96708c95ef98.png">

**How to reproduce it (as minimally and precisely as possible)**:
Setup an InfluxDB database with mock data and query it using FLUX

```flux
from(bucket: "db/rp")
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) =>
    r._measurement == "measurement" and
    r._field == "value"
  )
```

The result displayed by the query inspector will be unreadable.
Then query the same dataset with InfluxQL

```influxql
SELECT "value" FROM "db"."rp"."measurement" WHERE $timeFilter GROUP BY *
```

This time the query inspector will output usable response.

**Anything else we need to know?**:
The string format looks like base64 encoded text. Decoding it results in output starting and ending with `ARROW1`, it seems to me it may be an Apache Arrow Dataframe encoded in some way. Just decoding with base64 still results in incomprehensible output (except for some readable strings). I did not investigate further.

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: InfluxDB 1.8.4 using FLUX query language
- OS Grafana is installed on: Docker
- User OS & Browser: MacOS & Safari

**Comment by zoltanbedi** [comment]
@grafana/grafana-frontend-platform this is probably something that you should check.

**Comment by ryantxu** [comment]
I'll remove the "bug" flag, but this should be improved with #32303

**Comment by gabor** [comment]
with https://github.com/grafana/grafana/pull/32303 merged the dataframe-data for the flux-data-source now looks a lot nicer in the query-inspector, i think this can be closed now.
