### ISSUE TITLE
Signup: Don't show sign up page if  sign up is disabled

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#31635]
**What happened**:
We should not display the /signup page if sign up is disabled already on the instance. Disable signup works properly as it gives the error message when you're trying to set it, but not showing the page would probably be better. 

See:
https://raintank-corp.slack.com/archives/C010C1A4KCM/p1614709357074400

**Comment by tharun208** [comment]
@ivanahuckova, I like to work on this. I have a few questions. do we need to render an empty fragment like in `VerifyEmailPage` when the config is disabled? or we need to display either error screens or error popups?

**Comment by ivanahuckova** [comment]
@grafana/grafana-frontend-platform could you please give guidance to @tharun208 on this issue. Thank you! ❤️

**Comment by tskarhed** [comment]
It would make most sense if you were redirected to `/` when trying to reach `/signup`. Maybe add a condition checking the config, and if it is disabled return a `<Redirect to="/"/>`? This is probably possible in `routes.tsx`.

**Comment by tharun208** [comment]
@tskarhed, In `VerifyEmailPage` we are rendering an empty fragment ( https://github.com/grafana/grafana/blob/main/public/app/core/components/Signup/VerifyEmailPage.tsx#L8). can we do the same here or if we want to go with `Redirect` need to change at both the places.

**Comment by tskarhed** [comment]
@tharun208 That's just there to make TypeScript happy. The line above does a redirect.

https://github.com/grafana/grafana/blob/1490c255f10cdb80ec26caf69f511b427756d2a3/public/app/core/components/Signup/VerifyEmailPage.tsx#L9

This was done before we had `react-router` routing. I think putting that logic in `routes.tsx` makes more sense at the moment.
https://github.com/grafana/grafana/blob/1490c255f10cdb80ec26caf69f511b427756d2a3/public/app/routes/routes.tsx#L290

You could take inspiration from this, and then just add a condition that's checking the config.
https://github.com/grafana/grafana/blob/1490c255f10cdb80ec26caf69f511b427756d2a3/public/app/routes/routes.tsx#L337

**Comment by tharun208** [comment]
sure, will raise a pr for the same.
