### ISSUE TITLE
Expression result cannot be used for variable

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#31632]
**What happened**:
I want a variable to hold an expression result, in my example I want the variable to hold the number of scrap processes.
(The motiviation is to use it inside a link as an extra information).
But I get an error
![image](https://user-images.githubusercontent.com/2118079/109793876-e30b5a80-7c1d-11eb-97a3-898be404f9d4.png)

**What you expected to happen**:
The variable will get the value
**How to reproduce it (as minimally and precisely as possible)**:
Add a variable, using prometheus set its expression to `count(up)`
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: prometheus
- OS Grafana is installed on: docker
- User OS & Browser: fedora
- Grafana plugins: prometheus
- Others:

**Comment by ivanahuckova** [comment]
To use results from Prometheus query, you can use `query_result(query)`. You can learn more in the documentation: https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable
