### ISSUE TITLE
Some Dashboards loading slowly

### ISSUE THREAD

**Issue by NathanHochhalter** [grafana/grafana#31657]
**What happened**: A few Grafana DB's are loading much slower than usual for multiple users.

**What you expected to happen**: Typically they take around 5-10 seconds to load, in some instances we're seeing it take over 30 seconds.

**How to reproduce it (as minimally and precisely as possible)**:  Loading MD Summary and CM Details are 2 examples we have right now.  We haven't gone through every DB yet.

**Anything else we need to know?**:  Not at this time

**Environment**:
- Grafana version:Version 6.7.4 (8e44bbc5f5)
- Data source type & version: 
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: None that I know of?
- Others:

**Comment by torkelo** [comment]
Can you open chrome dev tools network tab and identity what requests are slow?

**Comment by Elfo404** [comment]
I'm closing this as there wasn't any update in over 2 weeks. Please feel free to follow up (with the requested info, it would help a lot investigating) if you think you should look further into it.
