### ISSUE TITLE
Expression: 'No data' returned with InfluxDB query

### ISSUE THREAD

**Issue by SanderDelden** [grafana/grafana#31655]
**What happened**:
Using a Expression I want to perform some simple math with my queries, for example: $A / $B
Unfortunately as soon as I add an expression to the panel 'No data' is shown. Removing it again restores the data.

**What you expected to happen**:
Output of the math equation I entered in the Expression query

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel with 2 InfluxDB queries and and a math Expression

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian
- User OS & Browser: Windows & Chrome
- Grafana plugins: InfluxDB
- Others:

**Comment by benganellison** [comment]
would assume it is the same as https://github.com/grafana/grafana/issues/31604

**Comment by kylebrandt** [comment]
fixed by https://github.com/grafana/grafana/pull/31691
