### ISSUE TITLE
Table Panel: Change of colums size disables column filter

### ISSUE THREAD

**Issue by docolli** [grafana/grafana#31654]
**What happened**:
If you filter a column by using the filter and then change the size of a column, the filter gets deactivated, just in the moment when you relase the mouse button.

**What you expected to happen**:
The size of the column changes, but the filter isn't affected.

**How to reproduce it (as minimally and precisely as possible)**:
Make Table panel with option "column filter" enabled. Set this filter to a random value to activate it. Change size of a column.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: MySQL
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 & Firefox 86.0
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
We will keep track of this in #46562
