### ISSUE TITLE
Reduce dashboard search item height

### ISSUE THREAD

**Issue by jonasbleyl** [grafana/grafana#31652]
**What would you like to be added**:
Reduce the height of the dashboards/folders in the search view.

**Why is this needed**:
Usability is majorly affected when having to deal with 100+ dashboards and folders as you aren't able to see as many dashboards in the search at once.

Here is how the sizes have changed across versions. Grafana 5 had the most compact and usable view.

![dashboard-list-size](https://user-images.githubusercontent.com/12758226/109842718-460ee880-7c42-11eb-94a0-9a5d583e1260.png)

**Comment by torkelo** [comment]
Recent is we need to fit in folder & tags, and the height of each card needs to be the same no matter what due to virtualized rendering of rows (Greatly improves the performance of rendering search items) 
![Screenshot from 2021-03-03 20-29-03](https://user-images.githubusercontent.com/10999/109861029-26d28400-7c5f-11eb-8e4e-29fbc7e5066b.png)

But it's unfortunate, will see what we can do

**Comment by jonasbleyl** [comment]
Thanks @torkelo!

Just to confirm, we do mean having the cards be more compact in general, not just if they don't have folders/tags.

Grafana 5 had the same information while being a lot more compact:

![grafana_5_compact](https://user-images.githubusercontent.com/12758226/109949616-7a7eb500-7cd3-11eb-8832-bf8510ed7aaa.png)

**Comment by jonasbleyl** [comment]
Hi @Clarity-89 - It seems that this change has been undone in Grafana 8. Was that an intended change?

**Comment by Clarity-89** [comment]
> Hi @Clarity-89 - It seems that this change has been undone in Grafana 8. Was that an intended change?

Not intended, I will check.

**Comment by Clarity-89** [comment]
@jonasbleyl thank you for pointing this out! Turns out it was a bug that slipped in during refactoring of one of the components. The fix will be available in version 8.0.1.

**Comment by jonasbleyl** [comment]
@Clarity-89 Thank you!
