### ISSUE TITLE
Update subtitle to use regionally appropriate form of Democratising

### ISSUE THREAD

**Issue by conorevans** [grafana/grafana#31660]
**What would you like to be added**:

Configure the subtitle "Democratising Data" to be region-friendly (Democratizing in `en-US`, Democratising elsewhere)

**Why is this needed**:

It follows typical conventions where content is displayed following the linguistic characteristics of a user's region

-----

Note: I would like to take this on for my first contribution.

**Comment by torkelo** [comment]
sure thing! here is the code: https://github.com/grafana/grafana/blob/master/public/app/core/components/Branding/Branding.tsx#L43

**Comment by conorevans** [comment]
Thanks. Can you assign this to me please @torkelo ? I'll get it to it sometime next week probably :)

**Comment by conorevans** [comment]
Hi @torkelo I have a branch ready for a PR, but I cannot create said PR. I've read the `contributing/` folder (including `create-pull-request.md`) and cannot see anything that I haven't followed - I mean it doesn't surprise me that I don't have push access (typically non-maintainers merge from a fork in my OSS experience), but I don't see anywhere that I was prompted to create a fork.. I'd welcome your guidance.

```
[cevans-democratising 4e52373ed5] use ALL_CAPS to signify that translations map is a constant and shouldn't be edited in-place
 1 file changed, 2 insertions(+), 2 deletions(-)

grafana>git push origin HEAD
Enter passphrase for key '<key>':
ERROR: Permission to grafana/grafana.git denied to conorevans.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

**Comment by torkelo** [comment]
Push branch to your fork, from there Github will allow you to open a PR to the main repo

**Comment by conorevans** [comment]
Corresponding PR was closed.
