### ISSUE TITLE
graphite render issue - returning 500 result code

### ISSUE THREAD

**Issue by noelmcgrath** [grafana/grafana#3167]
i have version 2.5.1-pre1.
When i select any daterange e.g. last 15 minutes i get an error. see attached image.

![capture](https://cloud.githubusercontent.com/assets/671790/11022603/c383a456-865a-11e5-8b72-1e867d838f8f.PNG)

looking at chrome you can see the details from calling render which returns a 500.
I am not a python guy, but I believe it is a time issue, which was never there before.
Note: If i select a date that includes date and time(by clicking zoom out) there is no issue

render details
==================
<body style="background-color: #666666; color: black;">
<center>
<h2 style='font-family: "Arial"'>
<p>Graphite encountered an unexpected error while handling your request.</p>
<p>Please contact your site administrator if the problem persists.</p>
</h2>
<br/>
<div style="width: 50%; text-align: center; font-family: monospace; background-color: black; font-weight: bold; color: #ff4422;">

</div>

<div style="width: 70%; text-align: left; background-color: black; color: #44ff22; border: thin solid gray;">
<pre>
Traceback (most recent call last):
  File &quot;/usr/lib/python2.7/dist-packages/django/core/handlers/base.py&quot;, line 112, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File &quot;/var/lib/graphite/webapp/graphite/render/views.py&quot;, line 56, in renderView
    (graphOptions, requestOptions) = parseOptions(request)
  File &quot;/var/lib/graphite/webapp/graphite/render/views.py&quot;, line 312, in parseOptions
    untilTime = parseATTime(queryParams[&#39;until&#39;], tzinfo, now)
  File &quot;/var/lib/graphite/webapp/graphite/render/attime.py&quot;, line 48, in parseATTime
    return tzinfo.localize((parseTimeReference(ref) + parseTimeOffset(offset)), daylight)
AttributeError: &#39;LocalTimezone&#39; object has no attribute &#39;localize&#39;

</pre>
</div>

</center>

**Comment by utkarshcmu** [comment]
I am not able to replicate this issue here. What version of Graphite are you using?

**Comment by torkelo** [comment]
Try updating Graphite to latest 0.9.14

**Comment by noelmcgrath** [comment]
I had  0.9.14 installed. went back and looked at graphite documentation and found it requires pytz for python (see http://graphite.readthedocs.org/en/latest/install.html).
So I installed this and issue resolved. Don't understand why a previous docker container I built for graphite where the dockerfile did not have this dependency worked with no issues.
Man, graphite installation is so painful
