### ISSUE TITLE
TimeSeries Panel: Padding seems comparatively large to graph panel

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#31677]
**What would you like to be added**:
In 7.5.0-beta1, when compared to the existing graph panel, the padding still appears to be large when the panel is small.

<img width="738" alt="Screen Shot 2021-03-04 at 22 17 37" src="https://user-images.githubusercontent.com/4478053/109969848-b8152980-7d37-11eb-9087-09742e26b23b.png">

Both padding of left of Y-axis labels, and padding between bottom of graph and X-axis labels appears a lot larger.

**Why is this needed**:
In order to be a drop in replacement for the graph panel.

**Comment by dprokop** [comment]
@maemigh thanks for reporting this. Until we improve the auto-sizing you can use the fixed-width axis: https://grafana.com/docs/grafana/latest/panels/visualizations/time-series/change-axis-display/#width

**Comment by torkelo** [comment]
this looks improved

**Comment by maemigh** [comment]
@dprokop This is improved, but the bottom axis still appears off. Graph (old) on the left, and time series on the right. Notice how it appears that time series leaves extra space for values below 0% to show, despite the option being Percent (0-100) and Min (and soft min) set to 0.

<img width="716" alt="Screen Shot 2021-06-11 at 13 32 42" src="https://user-images.githubusercontent.com/4478053/121631348-e7b39a80-cab9-11eb-868d-2c8af20877fc.png">

**Comment by leeoniya** [comment]
looks like the space is there due to the tick size. we can reduce this, or remove the x axis ticks. @torkelo thoughts?

**Comment by torkelo** [comment]
@leeoniya yea removing the x  grid ticks looks ok
