### ISSUE TITLE
TestData: QueryEditor sets a bunch of junk properties (unrelevant defaults) 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#31674]
A simple random walk test data scenario looks like this in saved json: (have to modify series count to 2, or set alias for the update to happen)

![Screenshot from 2021-03-04 13-22-03](https://user-images.githubusercontent.com/10999/109963433-b3775380-7cec-11eb-80f6-bce887e86abc.png)

**Comment by kylebrandt** [comment]
FWIW we run into this with other data sources I think. I think the an issue is that two models are combined:
 - Information needed by UX editors (e.g. previous config from previous views etc)
 - What needs to be stored to execute the query

Perhaps it is best to keep them combined, but it does result in data query requests often coming with information that may not be needed. Or with alerts, lots of UI model data ends up getting saved with the query - making it quite large at times (Azure datasource is a large example).

Out of scope for this issue I assume, but figured I would highlight the possible connection.
