### ISSUE TITLE
FR : Ability to configure timeout for querying datasources.

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3168]
We should have a global config somewhere , where we can configure timeout settings for querying backend datasources in milliseconds/seconds.

**Comment by oazabir** [comment]
+1. Needed especially in ElasticSearch as the whole cluster goes down when you run a query that exceeds heap size. ES is very fragile. We need to pass query timeout to keep the cluster running and keep users at bay who select "This year"

**Comment by mbell697** [comment]
+1 Also very useful for some graphite queries, e.g. we have one query that times out a lot that doesn't return much data but requires a lot of calculation by graphite-api. For example running `mostDeviant(something.*, 5)` doesn't return much data but may require crunching the stddev for thousands of input series.

**Comment by timtofan** [comment]
+1, would be nice to be able to increase the timeout to allow some long-running ElasticSearch queries

**Comment by singhh** [comment]
Is it possible to change 502 (BAD GATEWAY) to 504 (Gateway Timeout)? As timeout is happening when Grafana waits for 30sec for data retrieval from Datasource.

**Comment by pparth** [comment]
+1

**Comment by Agronis** [comment]
+1

**Comment by ChanningBJ** [comment]
+1

**Comment by JeromeLi** [comment]
+1

**Comment by hunterlong** [comment]
+1

**Comment by fguillen** [comment]
+1

**Comment by narc-Ontakac2** [comment]
At least with postgresql the situation is worse. Grafana has a timeout and stops waiting for the response afterwards. The query however keeps running. So the statement_timeout in the client connection should be set on the connection accordingly.

**Comment by narc-Ontakac2** [comment]
Any hints on how to implement this? Grepping src for timeout does find a bit too much.

**Comment by eyalzo** [comment]
+1

**Comment by narc-Ontakac2** [comment]
For the problem of abandoned queries running for a long tim postgres has a workaround. You can set the statement timeout for the grafana access user (reader in this example):

db=# alter role reader  set statement_timeout=180000;
ALTER ROLE
db=# select usename,useconfig from pg_shadow ;
 
Not sure if 180s is the actual timeout in grafana. Is it?

**Comment by victor-mendes-eduardo** [comment]
+1

**Comment by GerScau** [comment]
+1

**Comment by franciscbalint** [comment]
+1

**Comment by geanjunior** [comment]
+1

**Comment by narc-Ontakac2** [comment]
Using grafana somewhat longer I found that the hardwired 1m timeout is a good thing. If the query has to finish within a minute it will. And if it takes longer, it is not monitoring but reporting. The only important thing is to make sure the query is killed after the timeout. Orphaned long running queries will otherwise be a problem. 

-1

**Comment by narc-Ontakac2** [comment]
What is a problem is that relational databases response times depend on caching. The typical situation is that if I reexecute a query 3 - 7 times in the morning it is fast enough for the rest of the day. This is quite annoying. 

A way to execute the query once with a substantially longer timeout would help here. An immediate reexecution a number of times after a timeout would do, too.

**Comment by jehutywong** [comment]
+1 for Elassticsearch. While running aggregation to mass data, 60 seconds may not even enough for a 24 hours time range query

**Comment by emanzx** [comment]
+1

**Comment by karolina108** [comment]
+1

**Comment by narc-Ontakac2** [comment]
Another hint for people fighting with RDBMS response times: SQL 2003 has  TABLESAMPLE. You can run queries on a chosen  percentage of the rows. In many cases (such as singlestats) this is good enough.

**Comment by narc-Ontakac2** [comment]
Another hint for people fighting with RDBMS response times: SQL 2003 has  TABLESAMPLE. You can run queries on a chosen  percentage of the rows. In many cases (such as singlestats) this is good enough.
