### ISSUE TITLE
Time series panel: No z-index override available

### ISSUE THREAD

**Issue by zegerhoogeboom** [grafana/grafana#31684]
**What happened**:
In the "classic" graph panel there is a series override option "z-index" which is missing in the new time series panel. Here an image showcasing why this feature is relevant for me (I'd like the green dots to be on top)

![image](https://user-images.githubusercontent.com/5371096/109964278-c4749480-7ced-11eb-965f-3bd5cc0a1eb3.png)

**What you expected to happen**:

I expected there to be a z-index override option.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new time series panel, go to the override tab and add an override: In the list of options there is no option "z-index".

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: NA
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Chrome
- Grafana plugins: NA
- Others:

**Comment by ryantxu** [comment]
Can you try the "organize fields" transform and change the field order? 

![image](https://user-images.githubusercontent.com/705951/110076431-535ace80-7d39-11eb-9408-e79cec54dc71.png)

that seems as easy as a z-index override

**Comment by zegerhoogeboom** [comment]
Thank you @ryantxu, I had actually already tried this with no success. However, I put the field I wanted on top at the top of the list rather than the bottom, now that I was playing around with the transformation more I realized the fields at the bottom go on top in the chart :man_facepalming:.
