### ISSUE TITLE
make build-docker-full fails with an error about git missing.

### ISSUE THREAD

**Issue by jokreliable** [grafana/grafana#31697]
**What happened**:
Building the docker image from master fails with a git error when yarn is first called (see Dockerfile)

**What you expected to happen**:
I expected the build to either continue if git is missing or that git was installed so yarn wouldn't fail. 

**How to reproduce it (as minimally and precisely as possible)**:
git checkout master
make build-docker-full

**Anything else we need to know?**:

**Environment**:
- Grafana version: a7f7f97f0d36574a566ca7e0847d40ea98d61ba0 / master
- Data source type & version: N/A
- OS Grafana is installed on: Debian 10/buster 
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: build fails.

Possible fix: 
```diff --git a/Dockerfile b/Dockerfile
index f373623dd4..ae02839fe1 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -5,6 +5,7 @@ WORKDIR /usr/src/app/
 COPY package.json yarn.lock ./
 COPY packages packages
 
+RUN apk add --no-cache git
 RUN yarn install --pure-lockfile --no-progress
 
 COPY tsconfig.json .eslintrc .editorconfig .browserslistrc .prettierrc.js ./
```

**Comment by ivanahuckova** [comment]
Yes, I was able to reproduce. Thanks @jokreliable for reporting this.
![image](https://user-images.githubusercontent.com/30407135/110114329-bccbf300-7db4-11eb-87b5-fbe073cd42e0.png)

**Comment by dsotirakis** [comment]
Hello @jokreliable, and thanks for spotting this. Does your proposed solution solve the issue for you? I get some random `yarn` errors sometimes, even if I add your suggestion.

**Comment by dsotirakis** [comment]
I think it is more likely a `yarn.lock` or a caching issue. I'll dig a bit deeper and I'll let you know.

**Comment by dsotirakis** [comment]
@jokreliable it was indeed a `yarn` issue, [this PR](https://github.com/grafana/grafana/pull/31603) is a potential fix :)

**Comment by jokreliable** [comment]
to answer the questions from earlier in the thread, yes, it was getting to completion if I installed git first (though, as stated, with tons of warnings from various parts of the code).

Glad to see that it would be solved properly in Yarn.
