### ISSUE TITLE
Cloudwatch: allow use of wildcard (*) in metric name

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#31708]
**What would you like to be added**:
Customer would like to be able to use wildcards when selecting metric names in Cloudwatch query in Grafana UI. In their words:

> I’m wondering if there are any plans or updates around this feature:
> https://community.grafana.com/t/cloudwatch-plugin-using-wildcard-with-metric-name-does-not-work/5015
>
> TLDR: We like the wildcard feature. Can it be extended to use prefixes and suffixes like dev-* or *-database along with the ability to set alerts on them?

More explanation from that Community post:

> I have metrics in Cloudwatch for around 200 devices, that use the following pattern:
> 
>```
> device.dev.cpu.827192
> device.dev.cpu.742124
> device.dev.cpu.494271
> device.dev.cpu.321692
> ```
>
> What I want to do in my dashboard is to have one query, that looks like this: “device.dev.cpu*”
> that will retrieve all metrics which follow the specified pattern.

**Why is this needed**:
Customers **are** able to do wildcards in metric names in Cloudwatch UI. We should provide same ability in Grafana query editor for Cloudwatch. Example from Cloudwatch UI:

![image](https://user-images.githubusercontent.com/10763196/110032551-440e5d80-7d06-11eb-8152-eda06ee89f02.png)

**Comment by sunker** [comment]
Unfortunately, the GetMetricData API does not support wildcards in metric names. Will close this issue now and then we can re-open if the API adds support for this.
