### ISSUE TITLE
Explore search UX: Loki log label are truncated under Firefox 

### ISSUE THREAD

**Issue by jbarotin** [grafana/grafana#31720]
**What happened**:  
- Under Firefox 86.0 / Ubuntu 20.10
- Log Labels are truncated :
![loki_explore_truncate](https://user-images.githubusercontent.com/4245508/110099740-f21b1580-7da1-11eb-91f6-e3bf23b0ab4a.png)

**What you expected to happen**:
- Same with Chrome :
![loki_explore_label_ok_chrome](https://user-images.githubusercontent.com/4245508/110099848-124ad480-7da2-11eb-8e50-8dbdc625809b.png)

**How to reproduce it (as minimally and precisely as possible)**:
- use Firefox. I have also reproduced issue under Windows
- have several labels display on my fist label "filename" is ok

**Anything else we need to know?**: -

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Loki
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Firefox 86.0 / Ubuntu 20.10
- Grafana plugins: -
- Others: -

**Comment by Skaronator** [comment]
This might be already fixed with #30351. Can you check the latest beta release if it has been fixed?

**Comment by ivanahuckova** [comment]
As @Skaronator said, in  #30351 we have replaced cascader button with label browser, so this issue is definitely not present anymore as we are using different components. Therefore I am closing this issue.

**Comment by jbarotin** [comment]
I tested with the "master" version (thanks to docker). Indeed the GUI change completed, so yes this issue has to be closed. Thanks for all your (very quickly) answers.

**Comment by ivanahuckova** [comment]
@jbarotin Yes, the UI has totally changed. If you find there any bugs or if you have any feedback, please let us know and create an issue. Thank you!🙏

**Comment by jbarotin** [comment]
I've installed beta, so here my feedback. I'm aware, it will still evolve. 

Strong points :
- It's very nice when we want to do a complex selection of labels
- More affordable for beginner

Weak points :
- It's a bit more complicated than the old one if we want to select only one label quickly. But, I've no idea to share how to improve that point.
- too much text for a day to day use, "Which labels would you like to consider for your search?" and "Choose the label values that you would like to use for the query. Use the search field to find values across selected labels." should be available through help tooltips

**Comment by ivanahuckova** [comment]
Thank you so much! I'll add it to the list of future possible improvements/areas to focus on.
