### ISSUE TITLE
Query Editor: Text highlighting with keyboard fails in strange ways

### ISSUE THREAD

**Issue by Michael-Sinz** [grafana/grafana#31736]
**What happened**:
I had a query that looked something like:
`sum(node_namespace_pod_container:container_memory_working_set_bytes{cluster=~"speech1-.*", container!="", pod=~"vmss-autoscaler.*"}) by (cluster)`

I then put the text cursor between the `{` and `c` (of cluster), held down the shift key and tried to cursor to the right via the keyboard right arrow.  It failed to move at all.  (I wanted to highlight cluster and replace it with something else)

A second confusion then happened when I held shift and went left.  It highlighted the `{` as expected but I could then no longer go right (to unhighlight the `{`)

Finally, if I put the cursor between the `c` and the `l` of the `cluster`, I could highlight (shift-arrow) to the right as I wanted.  So it was directly related to being between the `{` and `c` that this failed.

Using shift-arrow to the left does not have this problem but shift-arrow to the right has various problems at the `{` character.

More playing found that having the cursor either directly before or directly after the `{` prevented shift-right from working.

The main problem is that highlighting all of `cluster` then requires you to start from the end (cursor between the `r` and `=`) and then highlighting with shift-left.

**What you expected to happen**:
The shift-arrow highlighting works.  It turns out that shift-left works consistently but shift-right has various failures

**How to reproduce it (as minimally and precisely as possible)**:
See above and attached picture:
![image](https://user-images.githubusercontent.com/36865706/110132645-3f868b00-7d80-11eb-9e56-5882b026d664.png)

**Anything else we need to know?**:
Reproduced with Chrome too.

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Thanos
- OS Grafana is installed on: Linux
- User OS & Browser: Windows Edge (latest version)
- Others:

**Comment by ivanahuckova** [comment]
I have checked and this is problem is Slate. In Grafana, we are not adding custom behaviour for shift + arrows. To fix this, we need to upgrade Slate or change the library used in QueryField.

**Comment by maemigh** [comment]
+1
Is this the best way to voice support for specific issues to the Grafana team?

**Comment by ivanahuckova** [comment]
> Is this the best way to voice support for specific issues to the Grafana team?

Yes 🙂

**Comment by Elfo404** [comment]
Closing this as this should have been fixed with the migration to Monaco in 8.3.0.
