### ISSUE TITLE
Docs: API reference doc page not rendering on the Website

### ISSUE THREAD

**Issue by starkblaze01** [grafana/grafana#31739]
**What happened**: The API  Reference page for @grafana/data is not properly formated.

**What you expected to happen**: It should render the table and hide any overflow text on the left side-panel.

**How to reproduce it (as minimally and precisely as possible)**: Visit: https://grafana.com/docs/grafana/latest/packages_api/data/

![image](https://user-images.githubusercontent.com/22374162/110139535-253cc380-7df9-11eb-9bea-556681872711.png)

**Anything else we need to know?**: Maybe apply `text-overflow: ellipsis;` for left side-panel list for names, and some character are missing which is not rendering the table properly.

**Environment**:
- Grafana version: NA
- Data source type & version: NA
- OS Grafana is installed on: NA
- User OS & Browser: macOS Catalina, Google Chrome
- Grafana plugins: NA
- Others: NA

**Comment by ying-jeanne** [comment]
Hi @starkblaze01, thanks for reporting the issue.

**Comment by achatterjee-grafana** [comment]
@mckn, can you take a look at this issue? It is related to packages_api docs. Thank you!
