### ISSUE TITLE
Can't rebuild Frontend with yarn start

### ISSUE THREAD

**Issue by dodo217** [grafana/grafana#31732]
**What happened**:
After Rebooting, i wanted to start the front-end again with "yarn start" to watch for changes to the front-end.
Unfortunately i get the following error message:

![grafana error](https://user-images.githubusercontent.com/77994803/110123909-c4de5f80-7dc1-11eb-82ee-3ad4d5e9e633.PNG)

**What you expected to happen**:
Build the Frontend and show output after file changes

**How to reproduce it (as minimally and precisely as possible)**:
Build front-end with "yarn start" and reboot your server.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5
- OS Grafana is installed on: Ubuntu V-Server 4 GB RAM

**Comment by torkelo** [comment]
Make sure you have executed yarn install before , and if that does not work remove node modules folder and try yarn install again

**Comment by dodo217** [comment]
Already tried to remove node module folder and install & start yarn again, but i had no success with this.

**Comment by dodo217** [comment]
Could it be, that 4 GB RAM is not enough for node?

**Comment by torkelo** [comment]
Maybe

**Comment by hugohaggmark** [comment]
We've failed to reproduce this issue as such we're closing this for now. We can always reopen this if more evidence is provided.

Can you try running this in a different environment?
