### ISSUE TITLE
Feature: Elasticsearch data table panel

### ISSUE THREAD

**Issue by IzakMarais** [grafana/grafana#3174]
@torkelo, I just finished watching your [The future of Grafana](https://www.youtube.com/watch?v=OWlZzh-R_JM) video. You mention that Elasticsearch has a 'data table' panel coming in the near future, but I could not find its GitHub issue to discuss it. 

We currently store only events in Elasticsearch. We would like a panel type that has a tabular display of the events in time order, similar to the _event viewer_ in [Bright](http://www.brightcomputing.com/Linux-Cluster-Management-GUI). The events displayed in the panel should be a function of the current dashboard time range. It would be useful to make the column fields customisable. 

Is this the sort of panel you had in mind in the video above?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/215#issuecomment-154435263
