### ISSUE TITLE
Grafana 7.4.3 variable query against MS SQL fails with "p.fields is undefined"

### ISSUE THREAD

**Issue by nathanpegram** [grafana/grafana#31743]
**What happened**: 
This query has been functioning fine in older versions of Grafana with an existing dashboard, but I rarely update the variable contents. It set to update never as it is an expensive query and I just go in and run it on demand with the update button as needed. I just found that after upgrading to 7.4.3, updating this variable now fails with the message "p.fields is undefined". I tested it in a newly created dashboard with the same result. The same query works fine in a table panel.

**What you expected to happen**:  
Variable contents to update.

**How to reproduce it (as minimally and precisely as possible)**:
Running a simple query like this one against MS SQL: "select distinct JSON_VALUE(version, '$.CTL') from SWVersion"

**Anything else we need to know?**:
Response payload for query: {"results":{"CTL_VER":{"refId":"CTL_VER","meta":{"executedQueryString":"select distinct JSON_VALUE(IFWV, '$.CTL') from SWVersion","rowCount":206},"series":null,"tables":[{"columns":[{"text":""}],"rows":[[null],["\u0005"],["\u000c"],["T0.1.1-1-g0702-d"]...[LOTS OF ROWS]...["v2.3.3-0-gd1a5"]]}],"dataframes":null}}}

Is the null dataframe the problem?

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: MS SQL
- OS Grafana is installed on: ubunt bionic
- User OS & Browser: Mac OS 10.15 and Firefox 85

**Comment by nathanpegram** [comment]
Ah, I just found that if I had a "where [EXPRESSION] is NOT NULL" to the SQL, the variable query updates successfully. I would still consider this a bug as it broke a previously functioning dashboard, but I am fixed up for now.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/31458 

https://github.com/grafana/grafana/issues/31445
