### ISSUE TITLE
Timerange Today shall allow scrolling to „yesterday“ and further back.

### ISSUE THREAD

**Issue by thomasleitner** [grafana/grafana#31748]
**What would you like to be added**: When an arbitrary timerange is selected in a dashboard, there are backward and forward arrows which allow to scroll back and forth in the timescale using the same time window. However when the timerange is set to „Today“ or „This month“ it would also be great to have those backward forward arrows to simply scroll back to „yesterday“ and from there to the day before yesterday and so on. Also,scrolling forward again. Similarly for months and years.  

**Why is this needed**: Data exploration would be much faster for data which is grouped in days, months, years etc.

**Comment by torkelo** [comment]
Good suggestion! very similar to https://github.com/grafana/grafana/issues/13687 so closing this
