### ISSUE TITLE
BarGauge: Gradient mode does not handle percentage based thresholds

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#31756]
**What happened**:

The Bar Gauge and Gauge panels handle threshold percentages differently.

**What you expected to happen**:

The Bar Gauge and Gauge should have consistent behavior, or at least it should be less confusing.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Gauge using a metric where the value is a percentage value (0-1).

![image](https://user-images.githubusercontent.com/9749173/110262278-201f7600-7fab-11eb-97ba-7d0429a516dd.png)

Change the Gauge to a Bar Gauge and observe the threshold renders completely differently.

![image](https://user-images.githubusercontent.com/9749173/110262322-3af1ea80-7fab-11eb-949e-41b759836efe.png)

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: v7.4.3 (010f20c1c8)
- Data source type & version: Bar Gauge (7.4.3), Gauge (7.4.3)
- OS Grafana is installed on: Linux (Kubernetes)
- User OS & Browser: Windows 10 (Chrome)
- Grafana plugins: N/A
- Others: N/A

**Comment by ying-jeanne** [comment]
Hi @uhthomas, Thanks for opening the issue, regarding the issue, when you got to Edit -> Panel -> Display -> display mode -> retro LCD, you might find a representation of bar gauge that consistent with a gauge. 
![image](https://user-images.githubusercontent.com/74549700/110332378-8beff600-8020-11eb-90bd-4e8e636b23b8.png)

I would for now close the issue, feel free to reopen the ticket if it is not what you are looking for.

**Comment by uhthomas** [comment]
I'd probably mark this as a bug. The text on the Bar Gauge renders correctly as green, but the actual bar itself is red, incorrectly.

**Comment by torkelo** [comment]
This due to a bug in BarGauge where it does not handle the thresholds as percentage based. Can fix the above issue by switching to basic bar display mode or switch to absolute thresholds (0.2 instead of 20)

**Comment by uhthomas** [comment]
Thanks @torkelo, this is exactly what I've done as a work around 🙂
