### ISSUE TITLE
Long freeze after tab being in the background

### ISSUE THREAD

**Issue by sfthomas** [grafana/grafana#3175]
I am viewing Grafana in Chrome, and I noticed that the longer the tab is in the background (i.e contents not shown), the longer it freezes when I finally switch back to it.
All metrics are coming from a Graphite database, plus I have a disabled ES annotation on the same dashboard.

Eventually - e.g after leaving it running for the night - the tab crashes, suspectedly because of the same problem.

Attaching a chrome devtools timeline - it is showing that there is a relatively long wait on 'Update Layer Tree'.

![image](https://cloud.githubusercontent.com/assets/1913456/11034617/38bbfe8e-86ed-11e5-9998-2b12829af9fe.png)

**Comment by sfthomas** [comment]
+ INFO - the issue does not seem to happen if I do not turn on auto-refresh.

**Comment by grobie** [comment]
@beorn7 haven't you seen a similar problem?

**Comment by utkarshcmu** [comment]
Update ur chrome to the latest. I had a similar issue with chrome.

**Comment by beorn7** [comment]
@grobie My issues happened with a flaky network connection. Which lead to many pending web sockets. I could solve the problem by going to chrome://net-internals/#sockets and hit "Flush socket pools".

I didn't run into that problem recently, so I can imagine Chrome improved the way dealing with it.

**Comment by daniellee** [comment]
Closing this as it seems like this is not a problem anymore. Can reopen if anyone is still experiencing this issue.
