### ISSUE TITLE
Dashboard variables ignored in InfluxDB queries when Expressions included

### ISSUE THREAD

**Issue by aitormagan** [grafana/grafana#31752]
**What happened**: When creating a panel that contains InfluxDB queries and an expression (the beta feature), dashboard variables are not replaced in the query, provoking a "No Data" scenario.

**What you expected to happen**: Dashboard variables should be replaced in queries even when expressions are included in the panel. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard
2. Create a dashboard variable with type custom. You can call it `query`. Specify tags which can match values in your InfluxDB measurement. 
3. Create a panel
4. Select a InfluxDB Database
5. Create a query and specify a where clause using the dashboard variable
6. Check that data is shown in the preview
7. Save the dashboard
8. Edit the panel you've just created and add a Expression
   i. Operation: Reduce 
   ii. Function: Mean
   iii. Input: A
9. Save the dashboard and update the page
10. Check that "No Data" is shown
11. Open the query inspector
12. Open the tree using the path: `requests.data.queries[0].tags[0]`.
13. Check that the value of `value` is `/^$query$/`. Value has not been replaced, so the "No Data" message makes sense
14. Remove the Expression from the dashboard
15. Save the dashboard
16. Open the query inspector again and check the dashboard variable is now included in the query

**Anything else we need to know?**:
Attached you can find evidences of the issue by following the steps described above. 

![Captura de pantalla 2021-03-07 a las 17 50 43](https://user-images.githubusercontent.com/2526562/110247805-568ad000-7f6e-11eb-9d72-1afcd5257926.png)
![Captura de pantalla 2021-03-07 a las 17 52 33](https://user-images.githubusercontent.com/2526562/110247812-5d194780-7f6e-11eb-806a-c5a4fdfe711d.png)

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Influx 1.8.4
- OS Grafana is installed on: Raspberry PI
- User OS & Browser: Mac OS 11.2.1 & Safari 14.0.3
- Grafana plugins: N/A
- Others: N/A

**Comment by kylebrandt** [comment]
Server side expressions "Expressions" unfortunately do not work with dashboard variables (in the same way alerting does not). The execution path is always through the backend/server of data sources, which currently don't support expanding dashboard variables. Have made a PR to update the documentation to reflect this.

**Comment by achatterjee-grafana** [comment]
Kyle has updated docs via PR https://github.com/grafana/grafana/pull/32646.
