### ISSUE TITLE
Request entity too large

### ISSUE THREAD

**Issue by piotrmach** [grafana/grafana#3176]
When using template variable with  a lot of values (e.g 1000)

![grafana_error](https://cloud.githubusercontent.com/assets/5316564/11036356/65535e28-86f8-11e5-8443-0e1d52f715df.png)
latest Grafana v 2.5.0

**Comment by torkelo** [comment]
do you have a proxy infront of Grafana? (like nginx or apache)?

**Comment by piotrmach** [comment]
yes, nginx... Without it, worked fine.

Closing. Thanks!

**Comment by mikhailov** [comment]
Nginx accepts request max 1MB size:

http://nginx.org/en/docs/http/ngx_http_core_module.html#client_max_body_size

> Syntax:	client_max_body_size size;
> Default:	client_max_body_size 1m;
> Context:	http, server, location
> Sets the maximum allowed size of the client request body, specified in the “Content-Length” request header field. If the size in a request exceeds the configured value, the 413 (Request Entity Too Large) error is returned to the client. Please be aware that browsers cannot correctly display this error. Setting size to 0 disables checking of client request body size.

Try to extend it according to size of request.

**Comment by timtofan** [comment]
I am getting the same error for the same reason while saving the dashboard.
I never pass whole values set in the queries though.

My variable is of type "query" with refresh "on dashboard load".
Hence it seems the values set included into saved dashboard would in fact never be used.

Would it make sense to change saving logic to not include values for query values with any refresh being enabled?

**Comment by torkelo** [comment]
@timtofan yea, I agree. for variables with `refresh on dashboard load` or refresh on time change the values should not be persisted in the dashboard model. 

If you have time please open a new issue for that

**Comment by Vitaliypro** [comment]
I added to nginx.conf in section http:
large_client_header_buffers 4 128k;
client_max_body_size       10m;
client_body_buffer_size    128k;
And everything works fine.

**Comment by taisph** [comment]
Any suggestions for working around around this when the load balancer limits [cannot be changed][1]?

[1]: https://cloud.google.com/load-balancing/docs/quotas#https-lb-header-limits

**Comment by shotarry** [comment]
> I added to nginx.conf in section http: large_client_header_buffers 4 128k; client_max_body_size 10m; client_body_buffer_size 128k; And everything works fine.

Works for me too, thanks.
