### ISSUE TITLE
To check alerts, Grafana used the query writed in "guided form" instead of "text mode"

### ISSUE THREAD

**Issue by castillo92** [grafana/grafana#31777]
**What happened**:

Grafana saved a legacy query I wrote one year ago in "guided mode" and use it to check alerts instead of use the new query writed in "text mode"

**What you expected to happen**:

I expected Grafana use the query from the text mode.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new query
2. Change to "text mode"
3. Modify the query
4. Come back to visual-guided mode. You can see the old query.
5. Create an alert and check the debug info

**Anything else we need to know?**:

I attach below some screenshots to probe my idea

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian latest
- User OS & Browser: Chrome and Firefox 84
- Grafana plugins: None
- Others: None

### **This is my query, I use it in a graph and works great with 1 data/second**
You can see I setup an alert...

![1](https://user-images.githubusercontent.com/37965565/110336627-526db980-8025-11eb-84c8-2822b5718825.png)

### **This is the query I wrote in text mode, because I prefer see it raw**

![2](https://user-images.githubusercontent.com/37965565/110336860-92cd3780-8025-11eb-885d-f980bed464bc.PNG)

### **If I toggle the query to edit "guided mode...**
Appears the parameter "P_Grid", an old name I use up to one year ago

![3](https://user-images.githubusercontent.com/37965565/110336902-9c569f80-8025-11eb-9778-ffdac827c8b8.PNG)

### **If I came back to "text mode" my query dissapear.**

![4](https://user-images.githubusercontent.com/37965565/110337157-e5a6ef00-8025-11eb-9346-0f428cf87376.PNG)

### **But I saw the bug inside Alert Testing rule...**
Were we can find the query in "text mode" but the old parameter in the middle

```
{
  "firing": false,
  "state": "no_data",
  "conditionEvals": "false = false",
  "timeMs": "1.270ms",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1615213538271,
        "queries": [
          {
            "refId": "A",
            "model": {
              "alias": "",
              "groupBy": [
                {
                  "params": [
                    "1s"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "hide": false,
              "measurement": "Medida_Fronius",
              "orderByTime": "ASC",
              "policy": "default",
              "query": "SELECT mean(\"P_FV\") AS \"P_Solar\" FROM \"Potencias\" WHERE (\"Tipo\" = '$Resolucion') AND $timeFilter GROUP BY time($__interval) fill(null)",
              "rawQuery": true,
              "refId": "D",
              "resultFormat": "time_series",
```

### **And here I found the bug:**
Why query the parameter "P_Grid"?
If I query `"SELECT mean("P_FV") AS "P_Solar" FROM "Potencias"......... `
```
              "select": [
                [
                  {
                    "params": [
                      "P_Grid"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "Tipo",
                  "operator": "=",
                  "value": "1s"
                }
              ]
            },
            "datasource": {
              "id": 1,
              "name": "BD_FV_v2 "
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1615213778271
      }
    },
    {
      "message": "Condition[0]: Query Result",
      "data": {
        "series": []
      }
    },
    {
      "message": "Condition: Eval: false, Query Returned No Series (reduced to null/no value)",
      "data": null
    }
  ]
}
```

**Comment by castillo92** [comment]
I try another way... building again the query....

First in guided way and the in text mode:

![6](https://user-images.githubusercontent.com/37965565/110339458-7bdc1480-8028-11eb-8bce-5ab92f3f2d9f.PNG)



And saw that template variables are not supported...

![7](https://user-images.githubusercontent.com/37965565/110339640-aded7680-8028-11eb-87d8-1691be5817b5.PNG)




So.... I hope this information could be usefull to developers if really there is a bug.... But I saw the problem was the way I wrote the template and alert rule can not execute:

```
SELECT mean("P_FV") AS "P_Solar" FROM "Potencias" WHERE ("Tipo" =~ /^$Resolucion$/) AND $timeFilter GROUP BY time($__interval) fill(null)
SELECT mean("P_FV") AS "P_Solar" FROM "Potencias" WHERE ("Tipo" = '$Resolucion') AND $timeFilter GROUP BY time($__interval) fill(null)
```

**Comment by torkelo** [comment]
I am not sure I see a bug here, the guided form does not parse your influx raw text mode query so your raw mode changes are not preserved.  https://github.com/grafana/grafana/issues/26085 

Think if you switch back to textmode without then modifying the text editor form there might be a bug where this new text edit mode is not saved, but this looks fixed in master
