### ISSUE TITLE
Rename tags in Traces to Logs feature.

### ISSUE THREAD

**Issue by Whyeasy** [grafana/grafana#31778]
**What would you like to be added**:

It would be great to be able to rename tags when you go from Traces to Logs.  This way you don't need to add new tags within your traces or your logs and can still find the result you are looking for within Grafana.

As well be able to add the TraceID (in the case of using Loki) at the end of the query as `|=<traceId>`.

So for example:

I have an tag called `host.name` in my trace which is the name of the pod. In my logs I have this tag as `pod`. I would like to be able to add `host.name` as `pod` when I press the `Logs for this span` button. 

**Why is this needed**:

- To make it possible to search on tags from traces in your logs without adding them to either your traces or your logs. 
- Adding the traceID as part of the query limits the logs inside of the query and what is being showed to you.

**Comment by lmickh** [comment]
I'm interest in this as well.  It would be nice to be able to [stick to the OTEL semantic conventions](https://github.com/open-telemetry/opentelemetry-specification/tree/main/specification/resource/semantic_conventions) without having to re-label the from the defaults promtail/Loki use.

**Comment by Thoro** [comment]
I'm also interested in this. Especially using the correct OTEL semconv names for them, and then being able to rename those fields how they are actually named in the Loki streams.

For me an additional feature would be an arbitrary search command that's appended to the query.

For example:

| unpack | traceID=${.TraceID} or request_id="${.http.request_id}

or

|= traceID="${.TraceID}"
