### ISSUE TITLE
dashboard data/panel links to 'javascript:' are not working, even disable_sanitize_html is set to true

### ISSUE THREAD

**Issue by thockar** [grafana/grafana#31783]
In all versions higher than 6.3.7 all links in data/panels to 'javascript:' are no longer working (disable_sanitize_html is set to true).
The resulting URL is 'about:blank' (like  disable_sanitize_html is set to false).

example:
...
"linkUrl": "javascript:newwin=window.open('$actiondash?orgId=1&var-action=set_sample_good&var-action_value=$__cell',$actionsize); newwin.focus();"
...

And - if I'm right,
there is a quote missing in line 97 of public/app/features/panel/panellinks/specs/link_srv.test.ts after 

javascript:alert('broken!

**Comment by torkelo** [comment]
When I set 

```ini
[panels]
# If set to true Grafana will allow script tags in text panels. Not recommended as it enable XSS vulnerabilities.
disable_sanitize_html = true
```

And a link with `javascript:alert('hello');` still works fine

**Comment by thockar** [comment]
but it is not working in table panels

render value as link: enabled
url: javascript:......

**Comment by sgrallert** [comment]
I have the same problem. I set the option "disable_sanitize_html" to true, restart the grafana server and cannot get javascript links in table panels to work.
