### ISSUE TITLE
I have modified the TimePicker component in @ grafana / UI. How can I refer to the TimePicker component I modified in the external plugin

### ISSUE THREAD

**Issue by zhoumin8023** [grafana/grafana#31796]
**Why is this component needed**:
  Timepicker
___
 - [ ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/master/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/master/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by torkelo** [comment]
This is not supported, have to rebuild Grafana with your modification
