### ISSUE TITLE
Feature Request: Bar Gauge - for percents, allow max value to be max displayed instead of 100%

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#31793]
**Current behavior**
In bar gauge, if units are percent, the min is always 0 and the max always 100

**What would you like to be added**:
Customer would like this option: In bar gauge, if units are percent, allow for max value to be the max displayed value of all the bars

**Comment by torkelo** [comment]
duplicate https://github.com/grafana/grafana/issues/24177
