### ISSUE TITLE
Feature Request: Global Date

### ISSUE THREAD

**Issue by gcormier9** [grafana/grafana#3179]
I was wondering if it can be possible when you change a date on a dashboard to have a checkbox that can update the date for all other dashboards.

I am using Grafana to get statistics about hosts. I have dashboard for Memory, CPU, I/O, Network, etc.

Sometimes, when there is a problem with a specific host for a specific date, I look at all the dasboards to see if there is something abnormal during a specific time slot. At the moment, I have to update the date on every dashboard, which I must admit is not too much trouble. However, it would be nice if the date can be automatically updated...

Thank you!
GCorm

**Comment by maddenca** [comment]
@gcormier9 A handy solution I use for maintaining time range when changing dashboards is to use the Links feature:
![graf](https://cloud.githubusercontent.com/assets/917241/11093721/21ee97d4-888c-11e5-9d98-1efd1b130b2c.png)

I created a number of dashboards with varying levels of detail, gave them all the same tag, and used consistent template names.  Then used the Links feature to create a 'Related Dashboards' dropdown list on them all.  If you click that you can then jump between dashboards preserving the timespan and populated template variables.  Works great for me and maybe can also satisfy your use case so thought I'd share.

**Comment by gcormier9** [comment]
Thanks @maddenca! Thanks exactly what I was looking for!
