### ISSUE TITLE
Cannot edit a dashboard/Panel on Google Chrome on Grafana 7.1.0

### ISSUE THREAD

**Issue by vsenapathy** [grafana/grafana#31791]
**What happened**:
Cannot edit a dashboard on Google chrome. Tried the same on Safari and everything is working. I have ad blockers enabled so I disabled it to try on Google Chrome and it doesnt work. Also I am an admin on grafana
![Screen Shot 2021-03-08 at 12 31 40 PM](https://user-images.githubusercontent.com/50638608/110378839-f1d18300-800a-11eb-9103-f7be35b127ad.png)
![Screen Shot 2021-03-08 at 12 31 50 PM](https://user-images.githubusercontent.com/50638608/110378842-f302b000-800a-11eb-82de-46e23f3814ba.png)

**What you expected to happen**:
Should see the drop down menu to edit the panel
![Screen Shot 2021-03-08 at 12 33 25 PM](https://user-images.githubusercontent.com/50638608/110378821-ebdba200-800a-11eb-8a83-392269e9a78f.png)

**How to reproduce it (as minimally and precisely as possible)**:
I am not sure if this has something to with newer version of google chrome blocking something but wanted to know if there is some bug in the below grafana version. Also I have not see this error before so I am trying to understand.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.1.0 (8101355285)
- Data source type & version: Inlflux DB
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac/Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Many see this as fixed in 7.4, 

https://github.com/grafana/grafana/issues/31374
