### ISSUE TITLE
Azure Datasource: Support Azure Billing API 

### ISSUE THREAD

**Issue by secustor** [grafana/grafana#31809]
**What would you like to be added**:
I would like to display Azure cost metrics inside of Grafana. 

**Why is this needed**:
Grafana supports at the moment Azure Monitor, Application Insight and Log Analytics ( Kusto ).      
Adding the Billing API would be another step in the direction of full dashboarding capability for Azure.  

A specific use case is that we show metrics for technical personal already in Grafana, but Product Owners have to switch between Azure Portal for billing information and Grafana for technical insights.

**Comment by secustor** [comment]
I have looked into but found no solution for that except writing some custom software which writes the metrics to logs and interpret it with Log Analytics or a  community Prometheus exporter

**Comment by ricohomewood** [comment]
There was a separate plug-in for this when azure monitor datasource was not part of the core grafana datasources. It was written as an installable plug-in by @yesoreyeram bit I think has sine been deprecated? This was the linked issue: https://github.com/grafana/azure-monitor-datasource/issues/81

**Comment by darthkurak** [comment]
Azure costs in Grafana would be great. It would allows many useful insights and correlation with other metrics already existed. For example: costs per user/request

**Comment by al-lac** [comment]
We would also really like to have Azure costs in Grafana. Is the source code for the datasource of @yesoreyeram still available somewhere?

**Comment by billabongrob** [comment]
If powerBI can do this, certainly grafana can.  :) I'd love to see this, especially if sorting by tag.  @yesoreyeram code has gone missing and it was very helpful!
