### ISSUE TITLE
Enable more customizable jump to loki logs from jaeger traces

### ISSUE THREAD

**Issue by SimonAlthoff** [grafana/grafana#31814]
**What would you like to be added**:
The "trace to log" feature in the jaeger datasource (and maybe others) provides a way to customize the query to the loki data source. This would include the possibility to use span id and trace id as variables to use for the line filter.

**Why is this needed**:
Right now I can only configure the tags I want to use as the loki stream selectors. The log lines that are shown after the jump out are not related to the span id/trace id of the selected span. For logs that are enhanced with the trace id/span id we could jump to a more specific part of the logs by making use of the span id/trace id.

**Comment by SimonAlthoff** [comment]
I just saw that this might be a duplicate of #31778

**Comment by zoltanbedi** [comment]
Thanks for opening this @SimonAlthoff, I think this is a duplicate as you said.
