### ISSUE TITLE
Cannot set datasource to a variable.

### ISSUE THREAD

**Issue by fischerman** [grafana/grafana#31815]
**What happened**:

Datasource variables are not "respected" after selecting them as datasource in panels and other variables. 

Using datasource variables, in general, feels buggy. I've tried to reproduce the most basic scenario.

**What you expected to happen**:

Changing the datasource variable should change the output of the panels.

**How to reproduce it (as minimally and precisely as possible)**:

- Create two Prometheus datasources (EDIT: make one of them the default)
- Create a dashboard
- Create a new variable of type *Datasource* named `ds`
- Create a new panel and put in a query like `up`
- Choose `$ds` as datasource from the drop down menu (i.e. change the datasource of the panel)
- Change the value of `$ds` to the other data source (i.e. change the dashboard variable)
- The output of the panel does not change (still showing the first data source)
- After applying the panel and opening it again, the selected datasource is no longer the variable but the first concrete datasource

**Anything else we need to know?**:

Might be related to #30996

**Environment**:
- Grafana version: Grafana v7.4.3 (010f20c1c8) (Docker)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox
- Grafana plugins: none
- Others:

**Comment by fischerman** [comment]
Hi @torkelo, I did some more testing. The problem appears in conjunction with a default data source (possibly related to #30996). When I test it without a default data source (like you did) there is no problem. I've updated the reproduction steps.

**Comment by hugohaggmark** [comment]
Related to #32143

**Comment by Hsinin** [comment]
> unable replicate any problem here: https://play.grafana.org/d/5eue-XDGz/datasource-variable?orgId=1&editPanel=2

<img width="290" alt="image" src="https://user-images.githubusercontent.com/9530290/169814230-a3da6e1a-a764-4fa3-a158-73f092d4feab.png">
here is $db, but mine is ${db}, Why this difference exists

Grafana version: 8.5.2
mode: development

**Comment by alercelik** [comment]
Having same problem in version 13.0.0

Edit panel JSON's datasource by hand and you are good to go
