### ISSUE TITLE
Showing no InfluxDB data, "Cannot read property 'from' of undefined" JS error.

### ISSUE THREAD

**Issue by ryan-williams** [grafana/grafana#3181]
I have a dashboard that was working fine for a few days pointed at InfluxDB 0.9.4.1 from Grafana `2.5.1-pre1, Commit: v2.5.0+51-gd7ee7cb`.

For some unknown reason it stopped showing all data except for annotations, and the time-range picker gives me JS errors whenever I try to use it:

![](http://f.cl.ly/items/183r2r3U1M3G13052K3h/Screen%20Recording%202015-11-09%20at%2005.53%20PM.gif)

![](http://cl.ly/image/0U3U403E3130/Screen%20Shot%202015-11-09%20at%205.48.43%20PM.png)

I killed all the data in Influx and added some back, and I can't get the dashboard to recover.

**Comment by torkelo** [comment]
Does the relative time ranges work? Why isnt InfluxDB returning data? (check chrome dev tools for request sent to influxdb and response).

**Comment by ryan-williams** [comment]
No network request is fired when I `mouseup` the time-range and the JS error occurs.

I killed the previous database and started over and I'm seeing data correctly when I use the date pickers to navigate to where it is, so I guess it's just a problem with the click+drag time-window selection.

**Comment by torkelo** [comment]
I pushed out a new 2.5.1-pre1 build, try it. Its strange I can click and drag zoom fine. Do you get this error when you click and drag zoom on all dashboards?

**Comment by ashokgowtham** [comment]
Similar issue occurs to me when I try to add annotations for the first time.
This is using graphite as a backend.
Using OSX mavericks, latest master build of grafana compiled from source, testing on chrome as well.
![image](https://cloud.githubusercontent.com/assets/2318286/11364885/03a574c2-92c9-11e5-931e-0596314f841d.png)

**Comment by ashokgowtham** [comment]
The exact location of the error from the debugger panel was:
 ```
   GraphiteDatasource.prototype.query = function(options) {
      try {
        var graphOptions = {
          from: this.translateTime(options.rangeRaw.from, false), //<---here options.rangeRaw is undefined
          until: this.translateTime(options.rangeRaw.to, true),
          targets: options.targets,
          format: options.format,
          cacheTimeout: options.cacheTimeout || this.cacheTimeout,
          maxDataPoints: options.maxDataPoints,
        };
```

**Comment by torkelo** [comment]
please try Grafana 3.0
