### ISSUE TITLE
[Bug] Unable to config timeout in Flux queries, error trying to query

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#31810]
**What happened**:
When doing a query on Flux it returned a timeout error:

```
t=2021-03-09T10:01:29+0000 lvl=warn msg="Flux query failed" logger=tsdb.influx_flux err="Post \"http://hidden:8086/api/v2/query?org=default\": net/http: request canceled (Client.Timeout exceeded while awaiting headers)" query="XXXX"
```

When tried to change the timeout option we didn't found any field on Datasource configuration and the client has no Timeout param:
https://github.com/grafana/grafana/blob/8d39e6640c6516abd7441a2058cada97760ea530/pkg/tsdb/influxdb/flux/flux.go#L70-L95

On the base lib, the timeout seems to be defaulted to `20s`:
https://github.com/influxdata/influxdb-client-go/blob/bfe8bb2634da81520bda469bc030d3af12a56bf6/api/http/options.go#L91-L93

**What you expected to happen**:
Be able to configure the timeout of the flux client in order to avoid time out errors

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: Flux - core | InfluxDB - 1.8.4
- OS Grafana is installed on: RHEL 7.6

**Comment by davkal** [comment]
There is a new feature to set timeouts at the datasource level: #31871

**Comment by davkal** [comment]
Please reopen if this does not help.
