### ISSUE TITLE
[Bug] OpsGenie notification prevents Sensu notification

### ISSUE THREAD

**Issue by manfred-ackermann** [grafana/grafana#31812]
**What happened**:

When adding an OpsGenie notification to an Panel Alert, the notification to Sensu stops working in case an alert fires.

**What you expected to happen**:

Sensu should get the alert notification either OpsGenie notification is added or not.

**How to reproduce it (as minimally and precisely as possible)**:

Prerequisites:
- OpsGenie / Sensu available

Works
1. create a Dashboard/Panel and configure alerting to Sensu
2. get alert fired
3. find Sensu showing the alert
4. get alert cleared
5. find Sensu showing the alert cleared

Doesn't work
1. add OpsGenie notification to above alerting
2. get alert fired
3. find OpsGenie showing the alert
4. find Sensu not showing the alert
5. get alert cleared
6. find OpsGenie showing the alert closed

Works again
1. remove OpsGenie notification to above alerting
2. get alert fired
3. find Sensu showing the alert
4. get alert cleared
5. find Sensu showing the alert cleared

**Anything else we need to know?**:

In my tests also a Slack notificatiob channel was involved and worked all the time.

The Notification show
Send to: "Slack" "OpsGenie" "Sensu Prd Alerts (default)"

May this be related to alphabetical order (left to right)!?

**Environment**:

- Grafana version:

v7.3.5 (11f305f88a)

- Data source type & version:

InfluxDB shell version: 1.5.2

- OS Grafana is installed on:

CentOS Linux release 7.6.1810 (Core)

- User OS & Browser:

MacBook/Linux, Chrome

- Grafana plugins:

Alert list, Azure Monitor, Bar gauge, CloudWatch, Dashboard list, Elasticsearch, Gauge, Getting Started, Google Cloud Monitoring, Graph, Graphite, Heatmap, Homelinks, Jaeger, Logs, Loki, Microsoft SQL Server, MySQL, News, OpenTSDB, Plusin list, PostgreSQL, Prometheus, Singlestat, Stat, Table, Table (old), Tempo, TestData DB, Text, Welcome, Zipkin by Grafana Labs.

Instana by Instana, Inc.

- Others:

**Comment by mellieA** [comment]
@manfred-ackermann Are you still seeing this issue with newer versions of grafana? I'm revisiting some older issues and want to know if it still needs to be researched.

**Comment by manfred-ackermann** [comment]
Hey Melori.

As we move away from Sensu, go all-in on Grafana Alerting with Notification
to OpsGenie/Slack and meanwhile also updated to Grafana 9 with Alerting nG,
I can't even say if the issue still exists.
From our side we have no need for investigation in that regard. But thanks
anyway for following up.

Greetings,
Manfred Ackermann

Am Sa., 23. Juli 2022 um 01:02 Uhr schrieb Melori Arellano <
***@***.***>:
