### ISSUE TITLE
Snapshot Copy Link broken

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3182]
After taking snapshot, I click on "Copy Link" and nothing gets copied to the clipboard.

**Comment by torkelo** [comment]
It seems to work for me, what browser and OS are you using?

**Comment by utkarshcmu** [comment]
"Copy Link" does not work on Firefox (v42.0), which is its latest version. I am using MacOS (Yosemite). 

Fyi, "Copy Link" works in Chrome(v46.0.2490.80).

**Comment by utkarshcmu** [comment]
Copy link works in Firefox. It gets copied to the clipboard.
