### ISSUE TITLE
Grafana installs nssm.exe outside of /grafana install path

### ISSUE THREAD

**Issue by thedeepc** [grafana/grafana#31822]
**What happened**:
When running the Grafana v7.4.3 installer .msi file via the command line with an INSTALLDIR argument, Grafana's nssm.exe was placed outside of the created `/grafana` directory and within a directory called `/svc-7.4.3.0`.
**What you expected to happen**:
When running the installer, we expected that Grafana's nssm.exe file would install within the `/grafana` directory, rather than outside of it, so all of Grafana's files including nssm.exe would be within `/grafana`
**How to reproduce it (as minimally and precisely as possible)**:
Run the installer with the follow command/arguments: `grafana-7.4.3.windows-amd64.msi /q INSTALLDIR="C:\your\install\path\here"`. Notice that two directories are generated: `/grafana`, as expected, and `svc-7.4.3.0`, which is unexpected.
**Anything else we need to know?**:
Here is a screenshot showcasing the circumstance:
![image](https://user-images.githubusercontent.com/22479193/110486005-36682780-80ba-11eb-89a2-d53afe1fb509.png)

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: n/a
- OS Grafana is installed on: Windows Server 2012
- User OS & Browser: Windows Server 2012 & no browser involved at this point
- Grafana plugins: n/a
- Others:

**Comment by ying-jeanne** [comment]
Hi @thedeepc, normally the installation would be in C:\your\install\path\here\GrafanaLabs\ folder, inside you would get grafana and other svc* file. So everything would be in GrafanaLabs folder. Is there any particular reason you would like also all svc* file into grafana specifically?

**Comment by mckn** [comment]
I'm closing this one due to inactivity. Please respond and provide some more information if we should reopen this issue.
