### ISSUE TITLE
Dropdown select field inside collapse, its not rendering properly, its options are hiding, its not extending beyond the collapsable area

### ISSUE THREAD

**Issue by Muraliprasath** [grafana/grafana#31826]
Inside collapse component, when we click on the dropdown field, options are not visible, its rendering in the collapsable area, rest of the part is hidden.

Things are working fine in 7.3.7 Version, when we using 7.4.* its not working.

**Comment by Muraliprasath** [comment]
Expected
![image](https://user-images.githubusercontent.com/39201470/110577888-9bd71980-8189-11eb-8bb7-4187e8c395dc.png)

Actual 
![image](https://user-images.githubusercontent.com/39201470/110578112-0f792680-818a-11eb-803d-f0d7bfb22ca6.png)

**Comment by Muraliprasath** [comment]
@torkelo - Kindly let us know any other info required.

**Comment by torkelo** [comment]
Closing this as we are still missing info on what components are used (Collapse?), will re-open if you can show the component your placing the select inside. 

The select currently does not work in side a container that has overflow: hidden
