### ISSUE TITLE
Notification Message in alerts

### ISSUE THREAD

**Issue by Ashtray0** [grafana/grafana#31839]
**What happened**:
When creating a alert with a notification message containing "<" or ">" the notification via telegram is not transmitted.
If i don't use "<" or ">" everything is fine.
In both cases the green heart in top becomes red and everything looks equal, but the notification is missing.

**How to reproduce it (as minimally and precisely as possible)**:
JSON snippet (didn't work):
`        "executionErrorState": "alerting",
        "for": "1m",
        "frequency": "1m",
        "handler": 1,
        "message": "Austauscher <25%",
        "name": "Kapazität 25%",
        "noDataState": "no_data",
        "notifications": []`
JSON snippet (works):
`        "executionErrorState": "alerting",
        "for": "1m",
        "frequency": "1m",
        "handler": 1,
        "message": "Austauscher 25%",
        "name": "Kapazität 25%",
        "noDataState": "no_data",
        "notifications": []`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.7 (1e261642f4)
- Data source type & version: InfluxQL
- OS Grafana is installed on: Raspberry PI 4B
- User OS & Browser: Windows 10 Firefox 86
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
@Ashtray0 are you still encountering this error? If so, have you tried upgrading to Grafana 8.2+ and migrating to the new Unified Alerting platform? It replaces the legacy alerting system that you are using in 7.3.7.

Closing this for now, but happy to reopen it 👍

**Comment by Ashtray0** [comment]
Issue is fixed for me,  thank you very much
