### ISSUE TITLE
StorageBytes missing from AWS/EFS

### ISSUE THREAD

**Issue by nathan9** [grafana/grafana#31836]
**What happened**:
The [AWS/EFS StorageBytes metric](https://aws.amazon.com/about-aws/whats-new/2021/01/monitor-your-amazon-efs-storage-usage-with-amazon-cloudwatch/) is [missing](https://github.com/grafana/grafana/blob/b79e61656ab4f5144d727d50df781f53d71fccf8/pkg/tsdb/cloudwatch/metric_find_query.go#L75).

**What you expected to happen**:
Should be able to see/graph the AWS/EFS StorageBytes metric.

**How to reproduce it (as minimally and precisely as possible)**:
It's not there. 
![image](https://user-images.githubusercontent.com/1772004/110514838-9e8d2c80-80ff-11eb-98ce-aa2361fdbe70.png)

**Anything else we need to know?**:
[The StorageBytes metric has three dimensions: Total, Standard, IA.](https://docs.aws.amazon.com/efs/latest/ug/efs-metrics.html)

**Environment**:
- Grafana version: 6.7.2
- Data source type & version: AWS
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS 10.15.7, Chrome 88.0.4324.192
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@sunker is there a project board for cloud data sources?

**Comment by sunker** [comment]
Yes @torkelo we've got two - Cloud Datasources Kanban for features and and Cloud Datasources Triage for bugs.
