### ISSUE TITLE
Grafana Constant is changeable in the URL

### ISSUE THREAD

**Issue by mkayontour** [grafana/grafana#31847]
Hello, as stated in the documentation: 

> Constant variables are not flexible. Each constant variable only holds one value, and it cannot be updated unless you update the variable settings.

I expect the constant to be not changeable at all. 

**What happened**:
I try to limit views on dashboards to viewers of specific dashboards and for this I provision multiple grafana instances with the required dashboard. To limit what they can see, I use one variable of type query to get a list of all of their checks and a constant with their name tag. 

This name tag (constant) is used to limit the list of checks which they can choose to display on the dashboard.  

The constant at first is unseen - but when they change the variable it will be displayed in the URL.

**What you expected to happen**:

Now I expect that the constant cannot be overwritten in the URL, but certainly this happens. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a Constant use it as ${constname} in the text field. 
Modify the Dashboard URL &var-constname=someothervalue

And check the text field with the changed constant. 

**Anything else we need to know?**:
You're all doing a great job! :) 

**Environment**:
- Grafana version:  7.4.3
- Data source type & version: Prometheus 
- OS Grafana is installed on: Official Latest Grafana Container
- User OS & Browser: MacOS, Safari, Chrome
- Grafana plugins: Clock

**Comment by hugohaggmark** [comment]
Hi @mkayontour 
Unfortunately, we can't hide variables from the URL because they are part of the state in the variable system.
I'm going to close this issue for now. If this feature receives more feedback, we can of course reopen it. 

All the best

**Comment by mkayontour** [comment]
Ok, thanks for the information. Maybe a hint in the documentation could be helpful for others. Without testing, my customer would have access data which he should not have to. 

I know that if it's crucial we should separate the backend data, but the documentation suggests it's "somehow" a constant.

**Comment by mpnowacki-reef** [comment]
I've ran into a similar issue. I understand that having the variable value displayed in the url is necessary, but maybe it could be overwritten if changed by the user?
