### ISSUE TITLE
plugin architecture for extending capabilities of Grafana

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#3185]
Opening this here to initiate discussion.

At Raintank we are currently using a fork of Grafana to build our openSaaS platform, but the desire has always been to be able to write and ship the modifications as a separate plugin that anyone can add to an existing Grafana deployment.  The time has now come to refactor our code base into this model.

To achieve our goals we first need to extend Grafana to support at least the following.
- ability to register additional http routes which get proxied to an additional backend.
- ability to have additioanl CSS files loaded by the frontend for adding new styles and overwriting existing ones
- ability to add additional Menu items to the left navigation bar
- ability to inject new AngularJS components (directives, routes, controllers, etc...)

**Comment by woodsaj** [comment]
Submitted PR with initial attempt at implementing this feature.  Also created an example Plugin to demonstrate the capabilities.  https://github.com/raintank/grafana-plugin-example

**Comment by torkelo** [comment]
So I have worked on this, based on your PR

progress in the external-plugin branch. 

you can define plugins in grafana.ini (or  custom.ini in dev mode).

```ini 
[plugin.datasource-test]
; custom install dir for single plugin
path = /home/torkel/dev/labb/datasource-plugin

[plugin.external-test]
path = /home/torkel/dev/labb/grafana-plugin-example
```

the updated external plugin is here:
https://github.com/raintank/grafana-plugin-example/tree/refactor

regular data source test 
https://github.com/torkelo/grafana-datasource-plugin-test

new staticRoot config which allows plugins to expose static content no matter where on disk they are. they are exposed via /public/plugins/<plugin_url_name>   (exposing them from the root had some minor complicating issues with requirejs.

**Comment by toni-moreno** [comment]
Hi  @torkelo , there is any example on how can I can take advantage of this new feature?

**Comment by torkelo** [comment]
@toni-moreno yes, I just moved KairosDB and InfluxDB 0.8 out and into their own repos. 
https://github.com/grafana/datasource-plugin-kairosdb and https://github.com/grafana/datasource-plugin-influxdb-08

I do not have a panel example, will add that later today or tomorrow!
