### ISSUE TITLE
SQLite query variable with  key/value pairs

### ISSUE THREAD

**Issue by sensej-j** [grafana/grafana#31855]
Dear Grafana team, 
i want to know if it is possible to create and use a SQLite query variable with the structure (Key1: Value1, Key2: Value2) like the custom variable.

**key:** = should be display name in my dashboard variable
**value:** ID, which is used in the SQL

Maybe there is another way to do that.

Grafana Version: 7.4.3
DS: frser-sqlite-datasource

Many Thanks

**Comment by ying-jeanne** [comment]
Hi @sensej-j, the plugin frser-sqlite-datasource is a third party plugin that we don't maintain, please ask the question in th community forum or https://github.com/fr-ser/grafana-sqlite-datasource/issues if new feature is needed.

We would close the ticket for now.
