### ISSUE TITLE
CloudWatch plugin can't handle DynamoDB correctly

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#3187]
Current implementation can't draw correct graph for ConsumedReadCapacityUnits and ConsumedWriteCapacityUnits.

According to document, the plugin should divide Sum by 60 to getting correct Average value.

http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/MonitoringDynamoDB.html

> Use the Sum statistic to calculate the consumed throughput. For example, get the Sum value over a span of 1 minute, and divide it by the number of seconds in a minute (60) to calculate the average ConsumedReadCapacityUnits per second (recognizing that this average will not highlight any large but brief spikes in read activity that occurred during that minute). You can compare the calculated value to the provisioned throughput value you provide DynamoDB.

**Comment by mtanda** [comment]
Basically average value is calculated by "Sum / SampleCount".

http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/cloudwatch_concepts.html
> The value of Sum / SampleCount during the specified period. By comparing this statistic with the Minimum and Maximum, you can determine the full scope of a metric and how close the average use is to the Minimum and Maximum. This comparison helps you to know when to increase or decrease your resources as needed.

If CloudWatch doesn't change this behavior for DynamoDB, we need to handle in Grafana side.

**Comment by msayler** [comment]
DynamoDB metrics for CloudWatch have been like this for a long time (and it's a major source of random bugs like this). Properly showing these will probably require a change like #3100…

**Comment by mtanda** [comment]
@bergquist Would you reopen this issue?
My PR is reverted, this isn't solved...

**Comment by mtanda** [comment]
@bergquist @torkelo please reopen this issue.

**Comment by torkelo** [comment]
doing metric transformations is up to the time series database & query execution. 

I want metric transformations (like sum, divide, scale, percent etc) in Grafana but has be implemented in a generic fashion so it can apply to all data sources.

**Comment by mtanda** [comment]
This issue is not feature request.
I hope this issue is still open until Grafana get some feature to handle this issue.

**Comment by torkelo** [comment]
but it sounds like a cloudwatch bug with Average?

**Comment by mtanda** [comment]
it is spec of CloudWatch, Average = "Sum / SampleCount".
Please see this comment. https://github.com/grafana/grafana/issues/3187#issuecomment-155355676

If CloudWatch will fix this issue, they need to add another statistics for "Sum / Period"

**Comment by mtanda** [comment]
thanks for reopening this.

**Comment by pfreixes** [comment]
I came across with the same problem, is there any plan to make a workaround for that ?

**Comment by mtanda** [comment]
@pfreixes Without modifying code, we can't fix this issue.

This is past rejected PR, https://github.com/grafana/grafana/pull/3445.
And, this is another dirty patch, https://github.com/mtanda/grafana/commit/0ec79a8ceba1cb9ba440e8329fd2d8b815cdc682.

**Comment by mtanda** [comment]
https://github.com/grafana/grafana/issues/5390 solve this issue.
So close this issue.

**Comment by morganchristiansson** [comment]
#5390 has no work done and doesn't solve anything at this point.

**Comment by abourget** [comment]
Hitting the same issue here.  It's not useable with DynamoDB stats..

**Comment by massimocode** [comment]
We are hitting the same issue as well

**Comment by EXPmiccooper** [comment]
Yes I've just come across this issue myself.

**Comment by mtanda** [comment]
Perhaps, this patch will work well. https://github.com/mtanda/grafana/commit/befc89a95720e9aaf2a330c471cbe27f10b05e5e

**Comment by richie87** [comment]
@mtanda thank you very much, but i dont got the source files.
The only path i could find regarding cloudwatch is: public/app/plugins/datasource/cloudwatch
And within this directory i can only find javascript files. I cant find any similar javascript file to your .go File fix, i mean with the switch case statement.

**Comment by mtanda** [comment]
@richie87 Sorry, you need to build Grafana by yourself.

This is build guide.
http://docs.grafana.org/project/building_from_source/

Most of CloudWatch datasource is implemented by Golang.
There is no easy way to apply patch...

**Comment by mtanda** [comment]
Or, by using meta queries datasource with CloudWatch datasource, you can Divide Sum by Period.
https://github.com/GoshPosh/grafana-meta-queries
