### ISSUE TITLE
Bug: Update v7.3.6 to v7.4.3. The index of Elasticsearch through weekly parse is different

### ISSUE THREAD

**Issue by gfes980615** [grafana/grafana#31885]
**What happened**:
When I update my grafana v7.3.6 to v7.4.3 version, the datasource elasticsearch details setting have something wrong.
test date: 2021/03/11
In v7.3.6 version, index name set [log.]GGGG.WW, pattern set 'weekly'. The result will search log.2021.10 
In v7.4.3 version, index name set [log.]GGGG.WW, pattern set 'weekly'. The result will search log.2021.09

**What you expected to happen**:
I expect they will be the same. (log.2021.10)

**How to reproduce it (as minimally and precisely as possible)**:
Set the same settings on different versions for observation.

**Anything else we need to know?**:
I found that it didn’t write a unit test for the weekly case.

**Comment by Elfo404** [comment]
Thanks for contributing @gfes980615!

This was already reported in https://github.com/grafana/grafana/issues/31634 and fixed with https://github.com/grafana/grafana/pull/31709 so I'm going to close this one
