### ISSUE TITLE
Stat vs SingleStat Value Mapping Behavior

### ISSUE THREAD

**Issue by HorusInfo** [grafana/grafana#31899]
Hello All,

   Environment:
   Grafana version: Version 7.0.1
   Data source type & version: MySQL Embedded DS
   OS Grafana is installed on:  CentOS Linux release 7.8.2003 (Core)
   User OS & Browser: Google Chrome is up to date Version 89.0.4389.82 (Official Build) (64-bit)
   Grafana plugins: Have installed Zabbix 4.0.1 and Pie chart 1.6.0 but not related to this issue
    
    In our organization we use the native component SingleStat and fill the value mapping features like below:

![image](https://user-images.githubusercontent.com/36744399/110792290-f50a8000-8251-11eb-9773-476f67c3492f.png)

   <div style="display: flex; align-items: center; justify-content: center; flex-direction:column;"><img src=https://<MySite>/images/grafana/A2.png width=70><div>

   We use a lor this kind of fields to put a small HTML block and bring some UI enhanced behavior, but since we upgrade from version 5 to 7.0.1 we got the recommendation to move from SingleStat to Stat panel like below.

![image](https://user-images.githubusercontent.com/36744399/110793554-829a9f80-8253-11eb-9fb0-049b02c025f8.png)

  If we accept this recommendation the new Stat does not have the same behavior in Value Mapping text, this component convert in HTML notation (eg &gt; and &lt;) and show the text AS IS.

![image](https://user-images.githubusercontent.com/36744399/110793843-d907de00-8253-11eb-9d04-f29a7561eecf.png)

  The Stat panel can have the same behavior of SingleStat?

   Steps to reproduce:

   Create 2 panel: One SingleStat and Other Stat.
   Create a values mapping in both, and fill with a small HTML block in text field.
   SingleStat process like HTML;
   Stat process like pure Text;

Thanks All
Best regards,

Fabio Dias

**Comment by torkelo** [comment]
HTML values are not supported in the stat panel (And singlestat is going away in v8). 

We hope to add image & color mappings to thresholds and value mappings (but likely post v8)
