### ISSUE TITLE
Grafana + graphite - nonNegativeDerivative returns nothing

### ISSUE THREAD

**Issue by joafri** [grafana/grafana#3189]
Hi,

I'm using the nagios/sensu-plugin "netif-metrics.rb" which sends data like below to graphite:
-bash-4.2$ ruby netif-metrics.rb -s gateway.net
gateway.net.enp1s0.tx_packets 8238989 1447146714
gateway.net.enp1s0.rx_packets 6830313 1447146714
gateway.net.enp1s0.tx_bytes 6150508736 1447146714
gateway.net.enp1s0.rx_bytes 1001682111 1447146714
gateway.net.enp1s0.tx_errors 0 1447146714
gateway.net.enp1s0.rx_errors 0 1447146714
gateway.net.enp1s0.if_speed 1000 1447146714
gateway.net.enp2s0.tx_packets 4878637 1447146714
gateway.net.enp2s0.rx_packets 7923444 1447146714
gateway.net.enp2s0.tx_bytes 843320766 1447146714
gateway.net.enp2s0.rx_bytes 6390956975 1447146714
gateway.net.enp2s0.tx_errors 0 1447146714
gateway.net.enp2s0.rx_errors 0 1447146714
gateway.net.enp2s0.if_speed 1000 1447146714
gateway.net.wlp5s0.tx_packets 8 1447146714
gateway.net.wlp5s0.rx_packets 0 1447146714
gateway.net.wlp5s0.tx_bytes 792 1447146714
gateway.net.wlp5s0.rx_bytes 0 1447146714
gateway.net.wlp5s0.tx_errors 0 1447146714
gateway.net.wlp5s0.rx_errors 0 1447146714
gateway.net.wlp5s0.if_speed 0 1447146714

The data is readable in graphite and grafana but when trying to add the "nonNegativeDerivative" to the search - I get no lines.
Below are two example-searches:
perSecond(nonNegativeDerivative(gateway.freelink.local.net.enp2s0.rx_bytes))
nonNegativeDerivative(gateway.freelink.local.net.enp2s0.rx_bytes)
![skarmbild fran 2015-11-10 11-05-08](https://cloud.githubusercontent.com/assets/7023345/11059608/fc094240-879a-11e5-8ced-8dac8b85530f.png)

**Comment by torkelo** [comment]
check what graphite returns using chrome dev tools (f12 / network tab), it looks like a graphite issue and not a grafana issue

**Comment by joafri** [comment]
Grafana received null on two out of three datapoints which gave error.
