### ISSUE TITLE
Docs feedback: /http_api/dashboard.md

### ISSUE THREAD

**Issue by LloydW93** [grafana/grafana#31895]
In the Create/Update dashboard section (https://grafana.com/docs/grafana/latest/http_api/dashboard/#create--update-dashboard), there's a reference to a `message` property. However, in the example, which claims to be an update, the message field isn't used, but the "title" field has a string that looks a lot like a commit message.

Should the example be setting a `message` property as well as the `dashboard.title` property?

**Comment by wbrowne** [comment]
Good catch @LloydW93. When you first create a dashboard, the message field will be set to `""`. For updates, it will be set as whatever the update note you enter from the save dashboard prompt.

In this case, the JSON represents either create or update so I think adding `"message": "Made changes to xyz",` should suffice here

**Comment by achatterjee-grafana** [comment]
Fixed in PR https://github.com/grafana/grafana/pull/32452.
