### ISSUE TITLE
Disabled Graphite queries re-enabled on edit

### ISSUE THREAD

**Issue by shanson7** [grafana/grafana#31903]
**What happened**:

Editing a disabled query causes it to be re-enabled. This is problematic since we disable the queries to avoid making massive requests to the backend. 

**What you expected to happen**:

Query stays disabled until I manually enable it via the "eye" icon.

**How to reproduce it (as minimally and precisely as possible)**:

Craft a query and click the play button to run it. Click the "eye" icon to disable. Edit the query and watch it get re-enabled.

https://user-images.githubusercontent.com/5024860/110797939-905f1d80-8271-11eb-9f85-e7bb109e011e.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v7.4.1 (07649d1313)`
- Data source type & version: Graphite (Metrictank)
- OS Grafana is installed on: RHEL 7
- User OS & Browser: OSX/Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Fixed in 7.4.3 https://github.com/grafana/grafana/pull/31336
