### ISSUE TITLE
Inner lookup Kusto query returns nothing in Grafana with distinct selection, but works in a log analytics workspace.

### ISSUE THREAD

**Issue by AlexWareUltromics** [grafana/grafana#31918]
**What happened**:
An inner lookup Kusto query worked perfectly fine in log analytics but fails in Grafana. Including multiple columns on a distinct select causes the problem.

**What you expected to happen**:
For the query to run the same way in log analytics as it would in Kusto.

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel and edit the query of said panel to the below:

let EVT = Event | distinct TenantId,RenderedDescription;
StudyOverview_CL | distinct TenantId, SourceSystem, name_s, incoming_d, pending_d, escalation_d
| lookup kind=inner (EVT) on $left.TenantId == $right.TenantId 

It depends on the table being used, but in this example the join is on TenantId and will only return a result if only TenantId is in EVT.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: an Azure Log Analytics workspace.
![Ops Dashboard - Stats - Ops Dashboard - Google Chrome 2021-03-11 17-07-00](https://user-images.githubusercontent.com/67274399/110826786-57cd3d00-828d-11eb-96c6-86d0fa32498f.gif)

- OS Grafana is installed on: Provisioned.
- User OS & Browser: Windows 10
- Grafana plugins: None
- Others: N/A

**Comment by AlexWareUltromics** [comment]
Nobody else had this problem then?

**Comment by joshhunt** [comment]
@AlexWareUltromics Thanks for the report! 

It would be really helpful if we could get a sample query that we could copy-and-paste and run within our environment. Is it possible to reproduce this with the [datatable](https://docs.microsoft.com/en-us/azure/data-explorer/kusto/query/datatableoperator?pivots=azuredataexplorer) operator with just a couple of rows? 

Additionally, what you expect the result to look like - perhaps screenshot of it working properly in Azure Portal - would be helpful.

**Comment by AlexWareUltromics** [comment]
Hi

Sorry, I tried recreating this using data-tables but couldn't reproduce the error. I think the problem lies with the Event table - "Events from Windows Event Log on Windows computers using the Log Analytics agent.". Or it could have to do with the number of columns selected for the query. Below is what I'd expect to see:

![image](https://user-images.githubusercontent.com/67274399/111141355-5f396280-857b-11eb-8d90-46e685a9b188.png)

Sorry I can't be more helpful.

**Comment by joshhunt** [comment]
To be clear - the issue is once you add the second distinct to the EVT query it no longer displays any results, and copy-pasting the same query into Logs Workspace in Azure Portal yields results?

This might be a bit hard for us to investigate without an easy reproduction case to go off. We do have an environment available with a few Azure Monitor resources set up, so if you're able to reproduce this with some more "off the shelf" Azure resources it would be very helpful!

**Comment by mckn** [comment]
I'm closing this one due to inactivity, please re-open if needed.
