### ISSUE TITLE
Encoding for Umlaut characters are not preserved for CSV Export with 'Excel Dialect'

### ISSUE THREAD

**Issue by suraj-james** [grafana/grafana#31916]
**What happened**:
When exporting CSV from table panel using 'Excel dialect' (sep=,) Umlaut characters are not reflecting in the proper format when opened in Microsoft Excel. 

**What you expected to happen**:
The exact representation (encoding) of those characters to reflect in the CSV (Excel Dialect) as seen in the table panel and in the inspect data pane. This however works well for normal CSV Export without 'Excel Dialect'.

**How to reproduce it (as minimally and precisely as possible)**:
![umlaut-csv-export](https://user-images.githubusercontent.com/59333642/110820399-105aa700-82b5-11eb-86bb-55e174979a56.gif)

Any other details:
When the encoding of the CSV file is changed from 'UTF-8-BOM' to 'UCS-2 LE BOM' (using Notepad++), it works well in Microsoft Excel. 

**Environment**:
- Grafana version: 7.3
- Data source type & version: Postgres
- OS Grafana is installed on: SUSE sp4
- User OS & Browser: Windows 10 and Google Chrome
- Grafana plugins: New Table Panel

**Comment by dprokop** [comment]
Possibly related feature request: https://github.com/grafana/grafana/issues/29174

**Comment by kaydelaney** [comment]
Could you share the contents of the CSV itself?

**Comment by mckn** [comment]
I'm closing this one due to inactivity. Please respond and provide some more information if we should reopen this issue.

**Comment by suraj-james** [comment]
> Could you share the contents of the CSV itself?

Actual Table Content: 
ç é â î ô ü ï and ö

CSV Content with Excel Dialect':
Ã§ Ã© Ã¢ Ã® Ã´ Ã¼ Ã¯ and Ã¶

**Comment by conblem** [comment]
Im having the same problem here

**Comment by mbastida123** [comment]
Same issue
![Image](https://github.com/user-attachments/assets/b374cb4b-e6d8-40f9-b3ad-bf5be70b113b)
![Image](https://github.com/user-attachments/assets/2557f5c7-66ab-40b8-8e4b-0bf2176d9177)

@mckn I don't have permissions to reopen the issue

**Comment by ilosilo** [comment]
> Same issue ![Image](https://github.com/user-attachments/assets/b374cb4b-e6d8-40f9-b3ad-bf5be70b113b) ![Image](https://github.com/user-attachments/assets/2557f5c7-66ab-40b8-8e4b-0bf2176d9177)
> 
> [@mckn](https://github.com/mckn) I don't have permissions to reopen the issue
> 
> Well, aparently the issue is not with grafana per se but with excel. If I open the csv with another program it displays fine. I do wonder why the csv from grafana don't display correctly in excel...

I changed downloadDataFrameAsCsv function like this: 

download.ts:
```typescript
export function downloadDataFrameAsCsv(
  dataFrame: DataFrame,
  title: string,
  csvConfig?: CSVConfig,
  transformId: DataTransformerID = DataTransformerID.noop
) {
  const dataFrameCsv = toCSV([dataFrame], csvConfig);
  const bomChar = csvConfig?.useExcelHeader ? String.fromCharCode(0xfeff) : '';

  
  const blob = new Blob([String.fromCharCode(0xfeff), dataFrameCsv], {
    type: 'text/csv;charset=ISO-8859-9',
  });

  const transformation = transformId !== DataTransformerID.noop ? '-as-' + transformId.toLocaleLowerCase() : '';
  const fileName = `${title}-data${transformation}-${dateTimeFormat(new Date())}.csv`;
  saveAs(blob, fileName);
}
``` 

In this case, to download without csv header feature is disabled but our customers doesnt need it.
