### ISSUE TITLE
A way to enable refresh interval for absolute time ranges 

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3192]
If you select a custom time range(not from the quick ranges) from the timepicker menu and select any refresh interval (for testing select 5s), then the dashboard shows the panels/graphs according to the custom time range but does not refresh the dashboard based on the selected refresh interval.

**Comment by utkarshcmu** [comment]
Why do we have this piece of code?
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/timeSrv.js#L96-104

Why do we restrict refresh interval for fixed ranges?
Here is a the use case:

Steps to reproduce the issue because of the above mentioned code:
For example I need to monitor a dashboard for the coming weekend from now-1(on Friday) to Sunday. I will follow the following steps:

1. Choose From: 1 hour back from now but choosing Time from the Time/Date dropdown menu(in this format: 2015-11-11 01:15:11).
2. Choose To: Of 2 days later from now but again choosing from Time/Date dropdown menu.
3. Now select a refreshing interval of 5 mins and click on apply.

This is a valid graph to look at and we could even save it but without a refresh interval because of the code above. :(

Though there is a workaround to get auto refresh:
In from, type now-1h and in to type now+48h, select refreshing interval 5 mins. Click on apply and BOOM!!! you have a dashboard ready for monitoring the weekend with auto refresh enabled. :)

But I do not understand the reason for disabling auto-refresh for custom ranges. This feature used to exist in earlier versions and users in our organization used to save their dashboard on fixed ranges.

**Comment by torkelo** [comment]
the reason is to disable auto refresh when you zoom in , there is no need have refresh enabled when you are zoomed in on a past absolute range. But I can see that it can be a problem with the absolute range extends into the future.

**Comment by tlusk** [comment]
I have a use case where we use grafana to graph performance benchmarking data.  In order to be able to compare between benchmarks side by side we offset the time of all our tests to start at the same time (Jan 1 00:00).  

By not allowing auto refresh for fixed time ranges we aren't able to see the data come in for our benchmarks realtime without manually refreshing the graphs.

**Comment by utkarshcmu** [comment]
I think we should enable the refresh for fixed time ranges and by default set it to off. I think it is off only by default.

**Comment by utkarshcmu** [comment]
@torkelo Can I put the refresh interval back on custom ranges, it will fulfill both the purposes which I and @tlusk mentioned?

**Comment by torkelo** [comment]
sure

**Comment by daniellee** [comment]
This fix got reverted a year ago. Not sure if it was on purpose? Was it to fix #7259? cc @torkelo 

Previous version:

```javascript
 // disable refresh if zoom in or zoom out		
if (!enableRefresh && moment.isMoment(time.to)) {
    this.old_refresh = this.dashboard.refresh || this.old_refresh;
    this.setAutoRefresh(false);		
}
```

https://github.com/grafana/grafana/commit/49fe74228b3f4617afc36122659f7eda2f09536c#diff-8e475507064810b0931c2b283a559dcbL112

New version:

```javascript
// disable refresh if zoom in or zoom out
if (moment.isMoment(time.to)) {
    this.old_refresh = this.dashboard.refresh || this.old_refresh;
    this.setAutoRefresh(false);		
}
```

https://github.com/grafana/grafana/commit/49fe74228b3f4617afc36122659f7eda2f09536c#diff-ce52e230d5ce55532888f88e34d08d8eR141

**Comment by torkelo** [comment]
what's the point of auto refresh of to time is fixed?

**Comment by svage** [comment]
In my company, operators don't need to worry about performance issues that occur at night. So they demand dashboards which use a timerange every day between “7 am” and “6 pm”. In our previous metric visualisation tool "cacti", they were used to see the whole time span completely, filling up through the day. Personally I'm quite happy with the quick values like _today_, but then again I think they have an interesting point there. 

I've tried several things here to accomplish an auto-refreshing timerange between “7 am” and “6 pm”:
- let the operators select their fixed timerange every morning (YYYY-MM-DD HH:MM:SS)
--> becomes a very annoying task every day, plus it's not possible to enable "auto-select" in this scenario (therefore, I created the issue [#4150](https://community.grafana.com/t/dashboard-auto-refresh-not-working-with-time-range/4150) at grafana.com
- try setting a relative timerange like "from now/d+7h to now/d+18h"
--> this way, I can enable "auto-select", but unfortunatelly the "to" time is computed one day in the future, effectively showing the timerange "today at 7am to tomorrow at 18pm"

Any thoughts?

**Comment by samhatchett** [comment]
I was also surprised to see that refresh for fixed time range was removed. My case is monitoring a backfill operation, where data is fetched and/or generated for a past time range. I want to see the results come in for that fixed range, as they are made available, without having to manually refresh.

**Comment by BrutalBirdie** [comment]
Is there any progress?
