### ISSUE TITLE
what Database queries are done from Grafana

### ISSUE THREAD

**Issue by ert56** [grafana/grafana#3193]
I have 2 question:
1) Is there any way from Grafana where we can check what query to made to openTSDB or rather any database. 
2) Can we change the log level in the logs to log more detailed information.

**Comment by torkelo** [comment]
not currently

**Comment by bergquist** [comment]
The possibility to enable file logging for all proxy requests seems like a good feature.

**Comment by mtanda** [comment]
same as https://github.com/grafana/grafana/issues/2289

**Comment by bergquist** [comment]
Available with http://docs.grafana.org/installation/troubleshooting/
and https://github.com/grafana/grafana/issues/7395
