### ISSUE TITLE
Why convert the value of variable input from uppercase to lowercase automatically？

### ISSUE THREAD

**Issue by msober** [grafana/grafana#31934]
**What happened**:
convert the value of variable input from uppercase to lowercase automatically

![image](https://user-images.githubusercontent.com/1792217/110918750-76e3d180-8356-11eb-9334-b17427e58604.png)
![image](https://user-images.githubusercontent.com/1792217/110919797-9b8c7900-8357-11eb-9121-4ee9de10c91b.png)

**What you expected to happen**:

do not convert

**Environment**:
- Grafana version: 7.3.5
- Data source type & version:
- OS Grafana is installed on: mac
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by ying-jeanne** [comment]
Hi @msober, I am not able to reproduce the issue, could you precise where this "table" is? I tested with variable input, seems working correctly.
![image](https://user-images.githubusercontent.com/74549700/110950543-43984700-8344-11eb-9363-5031febdef72.png)

**Comment by msober** [comment]
sorry, it's our code change lead to this bug.
