### ISSUE TITLE
Alert template variables not evaluating

### ISSUE THREAD

**Issue by dgrisham** [grafana/grafana#31958]
**What happened**:

We're using the Docker plugin for Telegraf to monitor our containers, push that data to InfluxDB, then Grafana pulls the Docker container metrics using the following query:

```
from(bucket:"application/docker")
  |> range(start:v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn:(r) => r._field == "exitcode" and r.container_status != "running")
```

That all worked, so I set up an alert to trigger when the exit code is non-null. This works as well -- however, I wanted to include metadata about the failed container in the message, which I did using template variables in the message as demonstrated [in the docs](https://grafana.com/docs/grafana/latest/alerting/add-notification-template/).

<img width="1380" alt="Screen Shot 2021-03-12 at 3 23 09 PM" src="https://user-images.githubusercontent.com/2904811/111004786-ddf98a00-8346-11eb-95f7-4b08d983048d.png">

However, this is the resulting message:

<img width="536" alt="Screen Shot 2021-03-12 at 3 23 54 PM" src="https://user-images.githubusercontent.com/2904811/111004879-03869380-8347-11eb-91ff-576c561b4989.png">

**What you expected to happen**:

For the template variables to be replaced by their respective values, which are shown below the graph and are created via InfluxDB tags.

**How to reproduce it (as minimally and precisely as possible)**:

I'm not sure on this -- I think this feature generally works (I wasn't able to find any recent-ish issues, open or closed, explicitly addressing or solving this). Wondering if there might be something specific to my case that the devs/anyone have insight on. 

Let me know if there's anything else I can add, thanks!

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: InfluxDB 2.0.3
- OS Grafana is installed on: Centos Linux
- User OS & Browser: OSX + Brave Browser
- Grafana plugins: Flux, InfluxDB

**Comment by torkelo** [comment]
Template variables are not supported in alerting , only query result tags/labels

**Comment by dgrisham** [comment]
I'm not sure I understand what you mean -- I'm trying to follow the official docs here: https://grafana.com/docs/grafana/latest/alerting/add-notification-template/

**Comment by torkelo** [comment]
The docs say "alert query data into an alert notification" , so only variables that refer to your query results is supported, not dashboard level variables. 

So if yor query returns tags or labels you can use them in our notification

**Comment by dgrisham** [comment]
@torkelo I'm still not quite sure I see the difference between what I posted and what you're saying. The query result contains the tags of `container_name`, `host`, and `container_status` on the `exitcode`, analogous to the `handler` and `instance` variables in the example in the docs. I'm not setting those at the dashboard level, they're only part of my query result.

**Comment by torkelo** [comment]
If you open query insector and hit the refresh button. Can you paste the binary arrow response here? Or easier might be the inspect drawre and check the JSON  tab, and select DataFrame structure from the select, what does it show?

**Comment by dgrisham** [comment]
Ah nice, I hadn't used the inspector before, this is good to know haha. Here's the output:

```
[
  {
    "length": 357,
    "refId": "A",
    "name": "docker_container_status",
    "meta": {
      "executedQueryString": "from(bucket:\"application/docker\")\n  |> range(start:2021-03-13T18:50:41Z, stop:2021-03-13T19:50:41Z)\n  |> filter(fn:(r) => r._field == \"exitcode\" and r.container_status != \"running\")"
    },
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {}
      },
      {
        "name": "exitcode",
        "type": "number",
        "config": {
          "min": 137,
          "max": 137
        },
        "labels": {
          "com.docker.compose.config-hash": "72f3f2ede044ee76076516ebe3dfe59ac5d6e78a8bf12cc5b9d528b2f77e10d9",
          "com.docker.compose.container-number": "1",
          "com.docker.compose.oneoff": "False",
          "com.docker.compose.project": "live-server",
          "com.docker.compose.project.config_files": "/applications/live-server/live-server.docker-compose.yml",
          "com.docker.compose.project.working_dir": "/applications/live-server",
          "com.docker.compose.service": "live-server",
          "com.docker.compose.version": "1.26.2",
          "container_image": "registry.gitlab.com/lacuna-diagnostics/live-server",
          "container_name": "live-server",
          "container_status": "exited",
          "container_version": "master-latest",
          "engine_host": "ip-10-0-2-122.us-west-2.compute.internal",
          "host": "ip-10-0-2-122.us-west-2.compute.internal",
          "metric": "application/docker",
          "server_version": "1.13.1"
        }
      }
    ]
  }
]
```

**Comment by dgrisham** [comment]
Would it be reasonable to re-open this issue? As far as I can tell this should work.

**Comment by dgrisham** [comment]
@torkelo Would it be reasonable to re-open this issue? As far as I can tell this should work, though I could still be missing something obvious.

**Comment by torkelo** [comment]
Wait your on 7.3 , this feature was added in 7.4

**Comment by dgrisham** [comment]
Ahh good catch, I'll upgrade. Thank you!
