### ISSUE TITLE
Value mappings on Stat panel is broken in 7.5.0-beta1

### ISSUE THREAD

**Issue by x70b1** [grafana/grafana#31959]
**What happened**:

I updated from `v7.4.3` to `7.5.0-beta1`.
The Stat panel seems not to apply my configured value mappings. Everything worked before.

**How to reproduce it (as minimally and precisely as possible)**:

My settings:

![2021-03-13-00:33:13-screenshot](https://user-images.githubusercontent.com/10016267/111009595-5a668a00-8394-11eb-95ed-b299c9267189.png)

`v7.4.3`:

![2021-03-13-00:33:26-screenshot](https://user-images.githubusercontent.com/10016267/111009596-5aff2080-8394-11eb-9953-278f19c9817c.png)

`7.5.0-beta1`:

![2021-03-13-00:26:21-screenshot](https://user-images.githubusercontent.com/10016267/111009593-59355d00-8394-11eb-82f7-613b8b7b1f5d.png)

**Environment**:
- Grafana version: updated `v7.4.3` to `7.5.0-beta1`.
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10 via apt package source
- User OS & Browser: Chromium

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/31924
