### ISSUE TITLE
Metrics Query Editor for Elastic Search takes only @timestamp as the time field name

### ISSUE THREAD

**Issue by bergamoyat** [grafana/grafana#3195]
It is only taking @timestamp as the name for time filed , for Range and Date histograms. I change it into my time filed which is 'timestamp , but when i switch mode and go to the query editor it still shows @timestamp as time field. If i manually edit in query editor and switch mode to 

Setting time to  'timestamp'
![image](https://cloud.githubusercontent.com/assets/6124354/11062385/8083b4a2-877c-11e5-93da-eca1e590fa37.png)

Query editor still shows it as '@timestamp'
![image](https://cloud.githubusercontent.com/assets/6124354/11062407/b419fbaa-877c-11e5-8a22-560d5eeb09a6.png)

Even if we edit the query manually , switching the view back and going back to dashboard will reset it to @timestamp

![image](https://cloud.githubusercontent.com/assets/6124354/11062447/1752eec0-877d-11e5-966b-daa5f9865b4d.png)

**Comment by torkelo** [comment]
what did you set the time field to in the data source edit options. Check that it is correct and then remove the query and readd it.

**Comment by bergamoyat** [comment]
Thanks a ton for the quick reply. That was it , sorry for the false alarm.
