### ISSUE TITLE
grafana_stat_totals_dashboard is reported as 0

### ISSUE THREAD

**Issue by istvanballok** [grafana/grafana#31966]
**What happened**:

The grafana internal metric `grafana_stat_totals_dashboard` is reported as 0, although there are a few dashboards.
Might be related to #15651.

```bash
$ curl -s http://localhost:3000/metrics | grep grafana_stat_totals_dashboard
# HELP grafana_stat_totals_dashboard total amount of dashboards
# TYPE grafana_stat_totals_dashboard gauge
grafana_stat_totals_dashboard 0
# HELP grafana_stat_totals_dashboard_versions total amount of dashboard versions in the database
# TYPE grafana_stat_totals_dashboard_versions gauge
grafana_stat_totals_dashboard_versions 0
```

```bash
$ curl -s http://localhost:3000/metrics | grep grafana_build_info
# HELP grafana_build_info A metric with a constant '1' value labeled by version, revision, branch, and goversion from which Grafana was built
# TYPE grafana_build_info gauge
grafana_build_info{branch="HEAD",edition="oss",goversion="go1.15.6",revision="010f20c1c8",version="7.4.3"} 1
```

**What you expected to happen**:
A non-zero value, similar to this output:

```bash
$ curl -s "localhost:3000/api/search?type=dash-db" | jq .[].id | wc -l
      19
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I noticed this after I imported the official grafana_stats dashboard, which might be a bit outdated: https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource/prometheus/dashboards

**Environment**:
- Grafana version: 7.4.3
- Data source type & version:
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by istvanballok** [comment]
I'm a bit confused because now it reports a non-zero number:
```
$ curl -s http://localhost:3000/metrics | grep grafana_stat_totals_dashboard
# HELP grafana_stat_totals_dashboard total amount of dashboards
# TYPE grafana_stat_totals_dashboard gauge
grafana_stat_totals_dashboard 21
# HELP grafana_stat_totals_dashboard_versions total amount of dashboard versions in the database
# TYPE grafana_stat_totals_dashboard_versions gauge
grafana_stat_totals_dashboard_versions 21
```
Could it be that the counter is initialized lazily, only after the first dashboard is created? In the reported case, I only had 19 provisioned dashboards.

**Comment by Elfo404** [comment]
Hi @istvanballok, thanks for reporting this!

Those stats are updated every 30 minutes (and not when the server starts), so this is actually the expected behavior and you'll get zeros for the first 30 minutes after starting Grafana for the first time.

https://github.com/grafana/grafana/blob/04e9f6c24f32b59f457590bc7827691fa11f1811/pkg/infra/usagestats/service.go#L58

I'm closing this, feel free to follow up with a feature request if you'd like this to change.
