### ISSUE TITLE
Cannot view/edit metric script

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#31965]
**What happened**:
When I try to edit a provisioned dashboard panel, the `Script` field shows `[object Object]` instead of actual value.
![es_script_bug](https://user-images.githubusercontent.com/22418250/111060466-c1279880-84a5-11eb-8b63-2f3d0b46e2fc.png)

**What you expected to happen**:
Show script value.

**How to reproduce it (as minimally and precisely as possible)**:
Snippet from provisioned dashboard:
```
"targets": [
        {
          "alias": "Old",
          "bucketAggs": [
            {
              "$$hashKey": "object:171",
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "5m",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "$$hashKey": "object:169",
              "field": "elasticsearch.node.stats.jvm.mem.pools.old.max.bytes",
              "id": "1",
              "inlineScript": "doc[\"elasticsearch.node.stats.jvm.mem.pools.old.used.bytes\"].value/_value",
              "meta": {},
              "settings": {
                "script": {
                  "inline": "doc[\"elasticsearch.node.stats.jvm.mem.pools.old.used.bytes\"].value/_value"
                }
              },
              "type": "avg"
            }
          ],
          "query": "event.module:elasticsearch AND metricset.name:node_stats",
          "refId": "B",
          "timeField": "@timestamp"
        },
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.4.1 (07649d1313)
- Data source type & version: elasticsearch 7.10.1
- OS Grafana is installed on: docker
- User OS & Browser: Firefox 86.0
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Thanks for reporting this, this was introduced by a recent refacotring. a fix for this was already merged for this in https://github.com/grafana/grafana/pull/31681

As a workaround until the fix is released you can change your metrics settings to: 

```json
"settings": {
   "script": "doc[\"elasticsearch.node.stats.jvm.mem.pools.old.used.bytes\"].value/_value"
}
```
note the missing `inline` property. once the fix is released both formats should work as expected, so you won't have to change it back.


I'm closing this, feel free to comment if it doesn't help you.
