### ISSUE TITLE
Dead-key behaviour break query editor

### ISSUE THREAD

**Issue by MinDBreaK** [grafana/grafana#31968]
**What happened**:
I'm unable to type in query characters like `~`. There is some bad character making some sort of offset and the cursor does  not appear where it should be. 

**What you expected to happen**:
The tilde is inserted correctly and there is no offset.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query on Macos where you need a regex on a label. Press space to insert it. Try to edit the regex, the characters are not inserted on the cursor but 2 characters behind.

**Anything else we need to know?**:
It is probably related to dead-key behavior when you need to press another key to insert it. 
Found one post about it : https://community.grafana.com/t/cannot-type-deadkey-tilde-into-query-editor-on-macos/37154

**Environment**:
- Grafana version: v7.4.3 (010f20c1c8)
- Data source type & version: Loki / Prometheus (Loki) 
- OS Grafana is installed on: Docker grafana/grafana ID fe0c28e2beb32c36b0dee9f0f1df9250b9cb66a713a434f2bd6f3127438042e7 on Ubuntu 20.04
- User OS & Browser: MacOS 11.2.2 (20D80) on Firefox Developer Edition 87.0b8
- Grafana plugins: ~ 
- Others:

**Comment by Elfo404** [comment]
we know of some issues regarding the query field, what's your keyboard layout? I couldn't reproduce this with an `en-US` keyboard.

**Comment by MinDBreaK** [comment]
The keyboard layout is the "french numeric" in macos layout settings

**Comment by Elfo404** [comment]
Thanks for following up. I switched to that same layout and I'm also experiencing some weird things.

**Comment by zoltanbedi** [comment]
I couldn't reproduce this. Can you please try [play.grafana.org](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22exemplar%22:true%7D%5D) or provide some more details?

**Comment by MinDBreaK** [comment]
I just added the screen recording on play.grafana.org where the issue still occur. I'm not sure what I can provide you more than what's in the original ticket. 
Just make sure that you are on the right layout as the dead-key behave differently if you have a US layout or a french one for example. 

https://user-images.githubusercontent.com/15737031/116243598-62716200-a767-11eb-9639-b71a09522691.mp4

**Comment by cykl** [comment]
@zoltanbedi See also https://github.com/grafana/grafana/issues/32500 for a reproducer. 

Please let us know if we can help you to reproduce or locate the issue. Having to switch between keyboard layouts during incident response is very annoying :sweat_smile:
