### ISSUE TITLE
https://packagecloud.io/grafana/stable/el/6/x86_64/repodata/ files does not contain grafana 2.5

### ISSUE THREAD

**Issue by martbhell** [grafana/grafana#3197]
Hi, 

I have downloaded https://packagecloud.io/grafana/stable/el/6/x86_64/repodata/primary.xml.gz and https://packagecloud.io/grafana/stable/el/6/x86_64/repodata/filelist.xml.gz and they do not contain grafana 2.5.0 (but grafana 2.0.1 ..)
Not in the -testing either.

// Johan

**Comment by torkelo** [comment]
strange, the package is there.
https://packagecloud.io/grafana/stable/packages/el/6/grafana-2.5.0-1.x86_64.rpm

**Comment by martbhell** [comment]
Yep. But not in the filelist.  Probably this is why the local mirror we make (because firewalls) doesn't see the new files.

**Comment by torkelo** [comment]
I sent an email to packagecloud asking for help with this issue

**Comment by martbhell** [comment]
The repo looks OK now (it got grafana 2.6). Closing this.
