### ISSUE TITLE
Documentation: Docker user/group should be grafana:root

### ISSUE THREAD

**Issue by wrightsonm** [grafana/grafana#31970]
In relation to this documentation page:

[https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later](https://grafana.com/docs/grafana/latest/installation/docker/#migrate-to-v51-or-later)

I think the modify permissions guidance is no longer valid.

```
# in the container you just started:
chown -R root:root /etc/grafana && \
chmod -R a+r /etc/grafana && \
chown -R grafana:grafana /var/lib/grafana && \
chown -R grafana:grafana /usr/share/grafana
```

should read:

```
# in the container you just started:
chown -R root:root /etc/grafana && \
chmod -R a+r /etc/grafana && \
chown -R grafana:root /var/lib/grafana && \
chown -R grafana:root /usr/share/grafana
```

Relates to issues #28829

**Comment by wrightsonm** [comment]
To alleviate this warning:
t=2021-03-14T18:18:18+0000 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rwxrwxrwx expected=-rw-r-----

The guidance should also include:

chmod 640 /var/lib/grafana/grafana.db

**Comment by achatterjee-grafana** [comment]
@grafana/backend-platform, can you confirm the suggested changes are correct. I can open a PR to update the topic. Thank you!

**Comment by aknuds1** [comment]
@xlson can you confirm, since you made the latest changes wrt. Docker user/group?
