### ISSUE TITLE
Table panel: Support for sorting on multiple columns

### ISSUE THREAD

**Issue by JensRantil** [grafana/grafana#31989]
**What would you like to be added**: Currently I can click the title of a table column and sort by it. However, I click on another table column title the previously clicked column is ignored in the sort. I'd like it to become secondary column for sorting.

**Why is this needed**: Because I have a table where I'd like to sort primarily on one column and then another.

**Comment by JensRantil** [comment]
Related: https://github.com/grafana/grafana/issues/14787#issuecomment-605326583

**Comment by JensRantil** [comment]
A possible workaround for grouping of one column and sorting on another is to use a "Column filiter" for the grouping and then sort on the other column.

**Comment by torkelo** [comment]
This already works, hold down shift key
