### ISSUE TITLE
Once enabled, disabling repeat row breaks templating

### ISSUE THREAD

**Issue by X-dark** [grafana/grafana#3198]
If you try to enable repeat row for a row, it works as expected. But if you then try to disable repeat row (setting its value to empty), setting the templated variable to another value will not affects this row anymore (ie the templated variable get stuck to the last value before disabling repeat row for this row).

**Comment by X-dark** [comment]
Some screenshots.

With repeat row enabled:
![2015-11-10-163547_1402x564_scrot](https://cloud.githubusercontent.com/assets/533161/11066602/3493b7fc-87c9-11e5-8101-2b433e620af0.png)
![2015-11-10-163603_1395x542_scrot](https://cloud.githubusercontent.com/assets/533161/11066603/34baacfe-87c9-11e5-85d8-b85b17650b0a.png)

With repeat row disabled, it stops working:
![2015-11-10-163618_1400x560_scrot](https://cloud.githubusercontent.com/assets/533161/11066604/34c3589a-87c9-11e5-830a-24105fdc72f1.png)

**Comment by X-dark** [comment]
If I remove the ```scopedVars``` section from the JSON it works as before.

**Comment by torkelo** [comment]
this should be fixed in 3.0
