### ISSUE TITLE
Setting Unit on secondary Y-axis is not honored. 

### ISSUE THREAD

**Issue by trygve** [grafana/grafana#31984]
**What happened**:
Set different unit on secondary Y-axis is not honored, it uses the unit on first Y-axis

**What you expected to happen**:
A different unit on 2nd y-axis
**How to reproduce it (as minimally and precisely as possible)**:
Chart 2 series on one graph, use 2 y-axis and change unit on second y-axis

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/19244278/111139984-189b3680-8582-11eb-961f-f52cfcecd0ee.png)

**Environment**:
- Grafana version: 7.4.3
- Data source type & version:
- OS Grafana is installed on: Home assistant OS
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This is due to unfortunate problem mixing old options and our new field (data) driven options. Will be fixed in new time series panel (the current graph panel will soon be deprecated).

**Comment by torkelo** [comment]
you can try to reset the unit to short in the Field tab, but not sure if that will fix it
