### ISSUE TITLE
plugins : version pattern should match pattern used by check-repo-update

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#31983]
**What happened**:

plugin-validator is using the plugin.schema.json file to validate the plugin version. However, the schema is not the same as the one used by the check-repo-update application.

The regexp should be something like : ^(0|[1-9]\\d*)\\.(0|[1-9]\\d*)\\.(0|[1-9]\\d*$|\\%VERSION\\%) to validate the version

**What you expected to happen**:

If the plug in version is 2021.03.0, it should rejected as this version will be rejected afterwards by check-repo-update (when creating a PR)

**How to reproduce it (as minimally and precisely as possible)**:

**Comment by Elfo404** [comment]
@marcusolsson Can you check this?

**Comment by wbrowne** [comment]
@marcusolsson Have brought this over to the plugins platform board for tracking - feel free to move to wherever you think is most appropriate!
