### ISSUE TITLE
[Upgrade] - 2.1.3 to 2.5

### ISSUE THREAD

**Issue by JulienChampseix** [grafana/grafana#3199]
Hi teams,

What the best practise for upgrade grafana running under Ubuntu 14.04.2 LTS ? for avoid to loose current datasources & dashboard. Require to do some backup firstly ?

Originally installed over grafana_2.1.3_amd64.deb.

Moreover the repository link https://packagecloud.io/grafana/stable/debian/ provided under http://docs.grafana.org/v2.0/installation/debian/#apt-repository is not working anymore

Thanks for your highlight.

Julien.

**Comment by torkelo** [comment]
It is working for me, 

Add the following line to your /etc/apt/sources.list file.
    
    deb https://packagecloud.io/grafana/stable/debian/ wheezy main

$ curl https://packagecloud.io/gpg.key | sudo apt-key add -
$ sudo apt-get update
$ sudo apt-get install grafana

**Comment by JulienChampseix** [comment]
@torkelo perfect ! Thanks

**Comment by torkelo** [comment]
Backup of the grafana database is always good  (if you use sqlite3 just make a copy of the db file, if you use mysql or postgres follow their backup procedures)
