### ISSUE TITLE
InfluxDB integral() aggregation does not provide option to specify time unit

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#31996]
**What happened**:
When you want to configure an integral() aggregation using the influxdb GUI query editor, you cannot specifiy the time units over which to integrate. You have to switch to manual editing to enter it:

![image](https://user-images.githubusercontent.com/9944663/111172693-5447f780-85a6-11eb-8353-2515d5ee1726.png)

![image](https://user-images.githubusercontent.com/9944663/111172750-5f9b2300-85a6-11eb-88b9-71f4d33edb54.png)

**What you expected to happen**:
Being able to specify the units in the GUI editor, just like with the reverse derivative() function:
![image](https://user-images.githubusercontent.com/9944663/111172945-8a857700-85a6-11eb-91d8-74e83ad50ea4.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create any influxQL query with an integral aggregation 

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: InfluxDB (with InfluxQL)
- OS Grafana is installed on: Ubuntu
- User OS & Browser: MacOS
- Grafana plugins: /
- Others:

**Comment by gabor** [comment]
technical notes:
- currently when the user chooses `integral` , then we generate a query like `integral("value")`. based on influxdb-docs, this is equal to `integral("value",1s)`
- just switching the code to have a param (like it works with `derivative`) is not enough. we need to handle backward-compatibility. if someone stored a dashboard with a query with parameter-less `integral`, we need to be able to load it even if we modify the code to have a parameter on `integral`
