### ISSUE TITLE
Datalinks that access the value of a specific field does not work correctly when using multiple series.

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#31994]
**What happened**:
Datalinks using the template __$data.fields.[fieldname] does not work for A-Series1 when A-Series is clicked.
![image](https://user-images.githubusercontent.com/468940/111165948-e6003680-859f-11eb-9c4a-2af80e9e6c41.png)

**What you expected to happen**:
The value from series A-Series should appear when A-Series1 is clicked, like it does here when A-Series is clicked
![image](https://user-images.githubusercontent.com/468940/111166329-498a6400-85a0-11eb-8fe1-917e3635c306.png)

**How to reproduce it (as minimally and precisely as possible)**:
Add a datasource with multiple series to a graph panel.
Add a datalink using the suggestion Fields [seriesname]
Click the series on the graph not specified in the datalink

example dashboard: [Test datalinks-1615820777452.txt](https://github.com/grafana/grafana/files/6142396/Test.datalinks-1615820777452.txt)

**Anything else we need to know?**:
When the link is constructed, the [fieldDisplayValuesProxy](https://github.com/grafana/grafana/blob/f97384c2f9de148c69e96e698c52f68f546bcea1/packages/grafana-data/src/field/getFieldDisplayValuesProxy.ts#L13) only has access to the dataframe from the clicked series. So when the series that does not match the template is clicked, it cannot find the field.

You can get around this problem by applying the transform `outer join` so that all your series is combined into a single series with multiple fields.

**Environment**:
play.grafana.com
- Grafana version: 7.5.0-beta1
- Data source type & version: gdev-testdata

**Comment by oscarkilhed** [comment]
@dprokop found and investigated this issue when looking into issue #31200

**Comment by strizhik** [comment]
Hi @oscarkilhed, that's exactly what I need and what I've tried to describe in #31200 ! 

Thanks for making things clearer ;)

**Comment by oscarkilhed** [comment]
> Hi @oscarkilhed, that's exactly what I need and what I've tried to describe in #31200 !

Try using 7.5.0-beta2 and the outer join transform on your two series.
