### ISSUE TITLE
X axis max value not used accordingly in histogram; error in x axis value labeling

### ISSUE THREAD

**Issue by Kater--S** [grafana/grafana#32006]
**What happened**:

When configured as histogram, the max value for the x-axis is not used correctly in the diagram. I can see that changing the value somehow does affect the axis, but the value I set is not reflected in the diagram. Min value is used correctly.

**What you expected to happen**:

Just as the min value, the max value should determine the end of the shown x range. 

**How to reproduce it (as minimally and precisely as possible)**:

Dataset is electrical mains frequency, i.e. values in dataset are currently ranging from 49.9 to 50.1 Hz. To show the histogram, I set X-Axis Mode to Histogram. Parameters are, for example: 50 Buckets, min 49.9, max 50.1. Shown range is then, unexpectedly, 49.9 .. 50.61. With max = 50.2, shown range is 49.9 .. 50.71. With max = 50.0, shown range is not readable because the labels are drawn onto each other. 

I can see that the histogram bars are clipped if the max value is (too) low, but there is much empty space between the bars and the upper end of the diagram. 

Changing the number of buckets has no effect on x axis scaling but changes the histogram as expected.

**Anything else we need to know?**:

Checked in Safari and Chromium browsers.

**Environment**:
- Grafana version: 7.0.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: Linux Debian
- User OS & Browser: macOS 10.14.6 + Safari/Chromium
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
Is this the new panel you are talking about? If not can you try with it?

**Comment by leeoniya** [comment]
> When configured as histogram

this sounds like the old panel. we were discussing its histogram idiosyncrasies just yesterday.

the new Time series panel does not have a histogram mode. i will be starting work on a dedicated Histogram panel soon that will hopefully be much more intuitive for bucket control, and with proper rendering.

**Comment by Kater--S** [comment]
What is meant by old/new panel? I am using the first entry in the "Visualization" menu, titled "Graph". If this is the old panel, how can I try the new one instead?

**Comment by Kater--S** [comment]
PS: With Grafana 7.4.1, I can alternatively use "Time Series" as visualization option. I suppose that is what @leeoniya means. This has, as announced, no histogram mode at all. The problems with the "Graph" option remain in version 7.4.1 just as described ;-)

**Comment by leeoniya** [comment]
> The problems with the "Graph" option remain in version 7.4.1 just as described ;-)

to my knowledge there are no plans to fix deficiencies in the Graph panel. it will be deprecated with Grafana 8 in a few months and replaced with new, dedicated Time series, Bar chart, Histogram and X/Y chart panels.

**Comment by Kater--S** [comment]
Ok, I'm perfectly fine with that. Looking forward to Grafana 8 :-)
