### ISSUE TITLE
HTTP POST support for notification when an alert is created

### ISSUE THREAD

**Issue by hardiksd** [grafana/grafana#32009]
**What would you like to be added**:
The HTTP alerting API does not provide an option to notify when an alert is created. This feature will allow an option to add a webhook to which an alert creation notification can be sent when a user creates an alert in the dashboard panel.

**Why is this needed**:
The alert creation information can be useful to propagate to other systems being used in conjunction with Grafana for monitoring purposes. Additionally, this feature can also allow an admin to maintain a list of alerts being created rather than polling it periodically using the currently supported HTTP API. We are exploring Grafana for embedded systems monitoring and it will be a particularly useful feature for embedded systems scenarios. This would be an admin-level feature that an admin can enable/disable for all the users.

I would be happy to implement and contribute to the project as well but definitely need some direction as I'm going through the Grafana source code at the moment. If there is any other way to achieve this without polling then definitely please point it to me. I wasn't able to find anything to support this in my searches.

**Comment by zoltanbedi** [comment]
@grafana/alerting-squad is this something that you are interested about?

**Comment by davidmparrott** [comment]
There is an internal discussion about exposing more audit information along these lines. We are closing this issue in favor of that effort.
