### ISSUE TITLE
granafa 2.5 how to use Elasticsearch datasource?

### ISSUE THREAD

**Issue by dotNetDR** [grafana/grafana#3200]
[Official Url](http://docs.grafana.org/datasources/elasticsearch/) No more information
![es-documents](https://cloud.githubusercontent.com/assets/926166/11083266/49811f34-8868-11e5-8203-341c8b2ab484.png)
![es-datasource](https://cloud.githubusercontent.com/assets/926166/11083268/4d4e3b88-8868-11e5-8f7d-3e159ca1b4dd.jpg)
![es-display](https://cloud.githubusercontent.com/assets/926166/11083269/50ae6258-8868-11e5-84e9-8f8dc80d219e.jpg)

**Comment by torkelo** [comment]
If you time field is named time, please specify that in the data source options (your first screenshot).

**Comment by torkelo** [comment]
I see you also have a field called timestamp without the `@`,  you can try that as well

**Comment by dotNetDR** [comment]
![isworking](https://cloud.githubusercontent.com/assets/926166/11086373/5e767cfe-888b-11e5-95c0-79413dd94b29.jpg)
![isworking2](https://cloud.githubusercontent.com/assets/926166/11086375/6158d07a-888b-11e5-987e-e4df4f3bf61e.jpg)

Edit data source > Elastic search details > Time field name
remove "@"

**Comment by dotNetDR** [comment]
@torkelo
You are right
thank you~

Best Regards.
