### ISSUE TITLE
Cloudwatch data source region is not saved when creating from API

### ISSUE THREAD

**Issue by kristianpaul** [grafana/grafana#3201]
curl -H "Content-Type: application/json" -H "Authorization: Bearer keyyyyyyyy123==" http://127.0.0.1:3000/api/datasources -X POST -d '{"name":"AWS","type":"cloudwatch","defaultRegion":"us-east-1","access":"proxy"}'

![screen shot 2015-11-11 at 12 15 01 am](https://cloud.githubusercontent.com/assets/326463/11084445/4845c66a-8809-11e5-96c9-cfff85e914a8.png)

As you can see region its missing from the UI, it works well when you create the data source manually.

**Comment by utkarshcmu** [comment]
JSON data which you are sending is slightly different.

Try this URL please:

Request:
```
curl -H "Content-Type: application/json" -H "Authorization: Bearer keyyyyyyyy123==" http://127.0.0.1:3000/api/datasources -X POST -d '{"name":"AWS","type":"cloudwatch","jsonData":{"defaultRegion":"eu-west-1"},"access":"proxy"}'
```
Response:
```
{"id":23,"message":"Datasource added"}
```
Now, the default region should be saved.

**Comment by kristianpaul** [comment]
Doh!, thanks
