### ISSUE TITLE
Cant zoom into time-range

### ISSUE THREAD

**Issue by gouthamve** [grafana/grafana#32010]
**What happened**:

Can't zoom into the time-range in the latest commit

https://user-images.githubusercontent.com/7354143/111273628-56f12e00-8634-11eb-8e8f-444e4ecf74cb.mp4

**How to reproduce it (as minimally and precisely as possible)**:

Open a dashboard and drag to zoom in.

**Environment**:
- Grafana version: Grafana v7.5.0-14319pre (50e5342379)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome on Linux
- Grafana plugins: None

**Comment by Elfo404** [comment]
@dprokop pinging you as I suspect this was introduced by the react router migration

**Comment by dprokop** [comment]
yeah, already on it @Elfo404
