### ISSUE TITLE
Variable ALL is not uselected when tags are used

### ISSUE THREAD

**Issue by 4quarks** [grafana/grafana#32012]
**What happened**:
The ALL variable is not auto-unselected when tags are being used. 

**What you expected to happen**:
Deselect the ALL variable and search exclusively by the tag(s) chosen. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a variable with the "Include All option" enabled and with some tags. Then select the value ALL and choose a tag. 

**Environment**:
- Grafana version: 7.3.3
- Data source type & version: ElasticSearch

![Screenshot from 2021-03-16 09-09-54](https://user-images.githubusercontent.com/47900195/111277369-ac2f3e80-8638-11eb-9f4b-ce14ee7fd9ec.png)
![Screenshot from 2021-03-16 09-16-21](https://user-images.githubusercontent.com/47900195/111277380-ad606b80-8638-11eb-80d3-4d079e6c001d.png)

**Comment by torkelo** [comment]
We are removing value groups/tags feature in v8 (was always an experimental feature, deprecated in v7.4) , so won't fix this
