### ISSUE TITLE
Gauge panels can't resolve labels value anymore

### ISSUE THREAD

**Issue by MohamedMSaeed** [grafana/grafana#32019]
**What happened**:
When I upgraded grafana from v7.3.3 to v7.4.3, Gauge panels can't resolve labels value anymore. In the following 2 screenshots, you can see the difference.

`v7.3.3`
![7 3 3](https://user-images.githubusercontent.com/35697318/111291378-ccb6c300-864f-11eb-9506-3d201b810244.png)

`v7.4.3`
![160876335_345630970147463_8176581838148666998_n](https://user-images.githubusercontent.com/35697318/111290772-279bea80-864f-11eb-931e-f670db226db1.png)

I see that the "alertname" is present when I used query inspector

```
{
  "request": {
    "url": "api/datasources/proxy/1/api/v1/query?query=sum%20by%20(alertname)%20(ALERTS%7Balertstate%3D%22firing%22%7D)&time=1615889206",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "vector",
      "result": [
        {
          "metric": {
            "alertname": "consumer_lag_alarm"
          },
          "value": [
            1615889206,
            "1"
          ]
        }
      ]
    }
  }
}
```

**What you expected to happen**:
It works like v7.3.3

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: prometheus
- OS Grafana is installed on: I'm useing grafana container
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Using labels in the Display name field like this have never been supported. 

The display name variable syntaxes are: 

* `${__series.name}` to show series name 
* `${__field.labels.alertname}` to use a label as display name

**Comment by torkelo** [comment]
In your case you should be able to leave the display name field empty, as you already use `{{alertname}}` in the legend format for the prometheus query, so the series names should already have the alert name label only

**Comment by MohamedMSaeed** [comment]
@torkelo 

Thank you for the clarification. `${__field.labels.alertname}` works perfect.

And Yeah I use `{{alertname}}` in the legend format, it works only if there is more than one alert to show. When it is only one alter, it doesn't show the alertname.

like this screenshot:
![Screenshot from 2021-03-21 15-10-45](https://user-images.githubusercontent.com/35697318/111906103-a8942100-8a57-11eb-80bf-597af6882437.png)

So I'm using "Display name"
