### ISSUE TITLE
Ordering serie names in the legend after transformations

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#32027]
**What would you like to be added**:

It would be nice if there is a possibility to order serie names in the legend regarding their new names after [transformations](https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#rename-by-regex).

**Why is this needed**:

As a picture is worth a thousand words, have a look at a screenshot of a panel with _name transformed_ series:
![210316-121426 grafana transformed-fields-in-legend-ordering rectangle](https://user-images.githubusercontent.com/25924718/111320631-7bb2c900-8667-11eb-835c-f47a81685c69.png)
Pay attention to the yellow rectangle at the bottom of the picture - these are new serie names after transformations.
The original names are as follows:
```
locality-precision-recall,ci_precision_high
locality-precision-recall,ci_precision_low
locality-precision-recall,ci_recall_high
locality-precision-recall,ci_recall_low
locality-precision-recall,precision
locality-precision-recall,recall
```

Desired ordering is as follows:
` precision  precision_ci_high  precision_ci_low  recall  recall_ci_high  recall_ci_low`

---
Or am I missing something?

**Comment by torkelo** [comment]
Can't you use the organize fields transform?

**Comment by hawran** [comment]
> Can't you use the organize fields transform?

Well, I've tried it, in vain:
```
Organize fields
Organize fields only works with a single frame. Consider applying a join transformation first.
```

Not sure what it means exactly.

**Comment by torkelo** [comment]
you can first add the Outer join transform, then use the organize fields transform to change order

**Comment by hawran** [comment]
> you can first add the Outer join transform, then use the organize fields transform to change order

Oh, I see.
I've just tried it and it seems to be working.
Thank you!
