### ISSUE TITLE
Elasticsearch unique count not working as expected for short time durations

### ISSUE THREAD

**Issue by gunplar** [grafana/grafana#32021]
Related issue #4231 and https://community.grafana.com/t/count-unique-and-disregard-duplicate-value/31665/4
From Elasticsearch I'm getting logs with various fields. In Grafana, visualization is graph, the query string just pick out entries with criteria related to other fields.
For short time duration (**last 24 hours, last 2 days etc.**), unique count of this one specific field **user.name** include duplicated values (there is only 2 values in **user.name**: blank and **Testuser**, blank is set to be ignored by default, there are about 60 log entries of **Testuser**, and unique count returns from 52 to 35 depending on slight differences in the time duration). Correct metric (unique count: 1, only one unique value **Testuser** in field **user.name**) is returned with duration **last 1 year**.

What seems to happens is that Grafana will divide the time duration into small chunks (12 hours in case **last 1 year**, 4 mins in case **last 24 hours**), and unique count will be applied in these small chunks. Can we set this chunk as a fixed duration (possibly as a parameter of the HyperLogLog algorithm)?

Grafana v7.3.7

**Comment by torkelo** [comment]
Sounds like you have a date histogram in your query, remove it or set the interval to a larger interval then the time range
