### ISSUE TITLE
Metrics discrepancy for Memory in grafana dashboad.

### ISSUE THREAD

**Issue by akshaysharama** [grafana/grafana#32049]
**What happened**:
We are monitoring pods running in Kubernetes using metric server and analyzing the same in grafana.
As could see, using kubectl top command, seeing mem and cpu info in Mebibyte and Millicore respectively. show in below.
kubectl top pods test-0
NAME                         CPU(cores)   MEMORY(bytes)
test-0   3m           335Mi

Prometheus reading the metrics, and updating the cpu and memory in nanocore and kebibytes respectively. show in below.
kube_metrics_server_pods_mem{pod_name="test-0",pod_namespace="default"}       343748

in kubernetes machine

kubectl get --raw "/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/test-0"
{"kind":"PodMetrics","apiVersion":"metrics.k8s.io/v1beta1","metadata":{"name":"test-0","namespace":"default","selfLink":"/apis/metrics.k8s.io/v1beta1/namespaces/default/pods/test-0","creationTimestamp":"2021-03-17T12:02:21Z"},"timestamp":"2021-03-17T12:01:51Z","window":"30s","containers":[{"name":"test","usage":{"cpu":"2731514n","memory":"343748Ki"}}]}

In grafana, we are query the same, but memory showing as 336 KIB in grafana GUI dashboard.
but if you see Ki and kib both are same only, then how grafana is showing as 336 "KIB" , conversion of  "memory":"343748Ki" to 336 is only when it is in MIB.
<img width="905" alt="grafana" src="https://user-images.githubusercontent.com/53307589/111428865-1f5eb080-871e-11eb-8153-b2420b854c05.PNG">

**What you expected to happen**:
Metric should be shown in proper units.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy metric-server, and monitor any pod, and compare values in kubectl top command as well as in grafana.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.3.1 
- Data source type & version: metric server, and using overall pod overview dashboard(6781)
- OS Grafana is installed on:  ubuntu 16.04.5 server version
- User OS & Browser: google chrome.
- Grafana plugins: using overall pod overview dashboard(6781)

**Comment by torkelo** [comment]
Can you open the query inspector (In inspect drawer) and show the results of the raw query from prometheus?

**Comment by akshaysharama** [comment]
Hi @torkelo, 

{
  "request": {
    "url": "api/datasources/proxy/1/api/v1/query_range?query=kube_metrics_server_pods_mem%7Bname%3D%22VM-1%22%2C%20pod_name%3D~%22test-0%22%7D&start=1615966680&end=1615968480&step=15",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "__name__": "kube_metrics_server_pods_mem",
            "name": "VM-1",
            "instance": "xxx.xxx.xx.xx:xyxz",
            "job": "VM-1-1",
            "pod_container_name": "test",
            "pod_name": "test-0",
            "pod_namespace": "default"
          },
          "values": [
            [
              1615966680,
              "346920"
            ],
            [
              1615966695,
              "347016"
            ],
            [
              1615966710,
              "347016"
            ],
            [
              1615966725,
              "347016"
            ],
            [
              1615966740,
              "347016"
            ],
            [
              1615966755,
              "347124"
            ],
            [
              1615966770,
              "347124"
            ],
            [
              1615966785,
              "347124"
            ],
            [
              1615966800,
              "347124"
            ],
            [
              1615966815,
              "347356"
            ],
            [
              1615966830,
              "347356"
            ],
            [
              1615966845,
              "347356"
            ],
            [
              1615966860,
              "347356"
            ],
            [
              1615966875,
              "347336"
            ],
            [
              1615966890,
              "347336"
            ],
            [
              1615966905,
              "347336"
            ],
            [
              1615966920,
              "347336"
            ],
            [
              1615966935,
              "347440"
            ],
            [
              1615966950,
              "347440"
            ],
            [
              1615966965,
              "347440"
            ],
            [
              1615966980,
              "347440"
            ],
            [
              1615966995,
              "347528"
            ],
            [
              1615967010,
              "347528"
            ],
            [
              1615967025,
              "347528"
            ],
            [
              1615967040,
              "347528"
            ],
            [
              1615967055,
              "347648"
            ],
            [
              1615967070,
              "347648"
            ],
            [
              1615967085,
              "347648"
            ],
            [
              1615967100,
              "347648"
            ],
            [
              1615967115,
              "347752"
            ],
            [
              1615967130,
              "347752"
            ],
            [
              1615967145,
              "347752"
            ],
            [
              1615967160,
              "347752"
            ],
            [
              1615967175,
              "347868"
            ],
            [
              1615967190,
              "347868"
            ],
            [
              1615967205,
              "347868"
            ],
            [
              1615967220,
              "347868"
            ],
            [
              1615967235,
              "347948"
            ],
            [
              1615967250,
              "347948"
            ],
            [
              1615967265,
              "347948"
            ],
            [
              1615967280,
              "347948"
            ],
            [
              1615967295,
              "348060"
            ],
            [
              1615967310,
              "348060"
            ],
            [
              1615967325,
              "348060"
            ],
            [
              1615967340,
              "348060"
            ],
            [
              1615967355,
              "348172"
            ],
            [
              1615967370,
              "348172"
            ],
            [
              1615967385,
              "348172"
            ],
            [
              1615967400,
              "348172"
            ],
            [
              1615967415,
              "348264"
            ],
            [
              1615967430,
              "348264"
            ],
            [
              1615967445,
              "348264"
            ],
            [
              1615967460,
              "348264"
            ],
            [
              1615967475,
              "348368"
            ],
            [
              1615967490,
              "348368"
            ],
            [
              1615967505,
              "348368"
            ],
            [
              1615967520,
              "348368"
            ],
            [
              1615967535,
              "348584"
            ],
            [
              1615967550,
              "348584"
            ],
            [
              1615967565,
              "348584"
            ],
            [
              1615967580,
              "348584"
            ],
            [
              1615967595,
              "348688"
            ],
            [
              1615967610,
              "348688"
            ],
            [
              1615967625,
              "348688"
            ],
            [
              1615967640,
              "348688"
            ],
            [
              1615967655,
              "348684"
            ],
            [
              1615967670,
              "348684"
            ],
            [
              1615967685,
              "348684"
            ],
            [
              1615967700,
              "348684"
            ],
            [
              1615967715,
              "348788"
            ],
            [
              1615967730,
              "348788"
            ],
            [
              1615967745,
              "348788"
            ],
            [
              1615967760,
              "348788"
            ],
            [
              1615967775,
              "348880"
            ],
            [
              1615967790,
              "348880"
            ],
            [
              1615967805,
              "348880"
            ],
            [
              1615967820,
              "348880"
            ],
            [
              1615967835,
              "349124"
            ],
            [
              1615967850,
              "349124"
            ],
            [
              1615967865,
              "349124"
            ],
            [
              1615967880,
              "349124"
            ],
            [
              1615967895,
              "349084"
            ],
            [
              1615967910,
              "349084"
            ],
            [
              1615967925,
              "349084"
            ],
            [
              1615967940,
              "349084"
            ],
            [
              1615967955,
              "349204"
            ],
            [
              1615967970,
              "349204"
            ],
            [
              1615967985,
              "349204"
            ],
            [
              1615968000,
              "349204"
            ],
            [
              1615968015,
              "349304"
            ],
            [
              1615968030,
              "349304"
            ],
            [
              1615968045,
              "349304"
            ],
            [
              1615968060,
              "349304"
            ],
            [
              1615968075,
              "349412"
            ],
            [
              1615968090,
              "349412"
            ],
            [
              1615968105,
              "349412"
            ],
            [
              1615968120,
              "349412"
            ],
            [
              1615968135,
              "349624"
            ],
            [
              1615968150,
              "349624"
            ],
            [
              1615968165,
              "349624"
            ],
            [
              1615968180,
              "349624"
            ],
            [
              1615968195,
              "349616"
            ],
            [
              1615968210,
              "349616"
            ],
            [
              1615968225,
              "349616"
            ],
            [
              1615968240,
              "349616"
            ],
            [
              1615968255,
              "343320"
            ],
            [
              1615968270,
              "343320"
            ],
            [
              1615968285,
              "343320"
            ],
            [
              1615968300,
              "343320"
            ],
            [
              1615968315,
              "343412"
            ],
            [
              1615968330,
              "343412"
            ],
            [
              1615968345,
              "343412"
            ],
            [
              1615968360,
              "343412"
            ],
            [
              1615968375,
              "343532"
            ],
            [
              1615968390,
              "343532"
            ],
            [
              1615968405,
              "343532"
            ],
            [
              1615968420,
              "343532"
            ],
            [
              1615968435,
              "343632"
            ],
            [
              1615968450,
              "343632"
            ],
            [
              1615968465,
              "343632"
            ],
            [
              1615968480,
              "343632"
            ]
          ]
        }
      ]
    }
  }
}

**Comment by ashharrison90** [comment]
hi @akshaysharama 👋 

thanks for raising this!
you've probably figured this out by now, but i believe the issue is to do with the units being set in the Stat panel.

there are 2 different types of unit for bytes:
- SI: 1000 bytes in a kilobyte, 1000 kilobytes in a megabyte, etc.
- IEC: 1024 bytes in a kibibyte, 1024 kibibytes in a mebibyte, etc.

unfortunately the prefix for a kibibyte is `KiB` which is often misread as kilobyte. the actual abbreviation for a kilobyte is `kB`. 

you can see in your screenshot the `KiB` abbreviation, meaning the units are set to the `bytes(IEC)`. if you switch the unit to `bytes(SI)` you'll get the value you're expecting:

![image](https://user-images.githubusercontent.com/20999846/141801332-13084705-1d2e-4e36-bc2a-d1044c5b8891.png)

hope that helps! 😄
