### ISSUE TITLE
Clarify what is hidden when selecting options in "hide variable"

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#32056]
In 7.4.3, when hiding variables, I am presented with "Label" and "Variable". The former hides only the label but shows the variable values. The latter hides it completely. Also, it's sorted alphabetically, not according to usage.

I think it would be better to
* Rename them to "Label only, show values" and "Hide completely"/"Complete variable"
* Put the "Complete variable" on top as that is the common case in my experience.

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Prometheus, 2.24
- User OS & Browser: Brave, Debian

CC @jessover9000 

![image](https://user-images.githubusercontent.com/754723/111455228-d0ad1880-8715-11eb-94e0-92c43cd48608.png)

**Comment by natellium** [comment]
The field doesn't exist anymore, I believe it was replaced by "show on dashboard" similar to the suggestion here. Closing this issue :)
