### ISSUE TITLE
Graph-Bars style strangely overlaps bars

### ISSUE THREAD

**Issue by maxdd** [grafana/grafana#32051]
I would like to plot bars showing kWh per day
The query i'm using is the following

```
from(bucket: "db")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "meas")
  |> filter(fn: (r) => r["_field"] == "PAC")
  |> window(every: 1d)
  |> integral(unit: 1h)

```
**What happened**:

Instead of having "separated" bars in each day i'm getting a sort of overlaps from the starting-day of the data till "now" leading to this strange representation

![image](https://user-images.githubusercontent.com/6155973/111353925-115d5100-8686-11eb-8b54-408e1b721a9c.png)

![image](https://user-images.githubusercontent.com/6155973/111432403-46f15100-86fd-11eb-831d-2cd63c600eb6.png)

**What you expected to happen**:

I would have expected to have single bars far away from one another

**Environment**:
- Grafana version: 7.4.3
- OS Grafana is installed on: docker
- User OS & Browser: Windows/Chrome

**Solution**:
Use time series panel

**Comment by torkelo** [comment]
Can you try the new time series panel?

**Comment by maxdd** [comment]
That's actually fixing the issue O.o, is it on purpose (e.g. due to drop of support for "graph")?

**Comment by torkelo** [comment]
* no we do not add bugs on purpose 
* Yes, the old graph panel will be deprecated in v8 
* multi bars groups are possible in the Bar chart panel (only out in alpha and coming in v8)

**Comment by maxdd** [comment]
Is there a guide for alpha chart? i enabled it but it's not plotting at all with the same query

**Comment by torkelo** [comment]
it does not support time axis right now, it's only for categorical (string) x axis So if you could format your time values as string dates it should work , not sure if influx can do that
