### ISSUE TITLE
FocusedPanel shortcuts don't always work 

### ISSUE THREAD

**Issue by ontari** [grafana/grafana#32076]
**What happened**:
By using the e shortcut, not every panel reacts to this. Some panels only react when pressing e long, some not at all and others are fine.

**What you expected to happen**:
All panels should react immediately when pressing e shortcut.

**How to reproduce it (as minimally and precisely as possible)**:
A Dashboard with some Panels and pressing e key on keyboard when mouse is over a panel.  

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: Prometheus 2.15.2
- OS Grafana is installed on: Linux Docker container
- User OS & Browser: Win 10 / Firefox
- Grafana plugins: default + Ajax panel
- Others: -

**Comment by torkelo** [comment]
I think we need to change how these shortcuts know if a panel is focused, reason that it sometimes is not working is that it only trigger on mouse enter and leave and sometimes these events do not trigger (for example when going in and out of edit mode or when dashboard div it'self does not have focus). 

https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/dashgrid/DashboardPanel.tsx#L70 

Here is where the keybindings live:
https://github.com/grafana/grafana/blob/master/public/app/core/services/keybindingSrv.ts#L213 

Instead, these keybindings should try to look up the div the mouse is over and go up the DOM to find a div with a panel data id
