### ISSUE TITLE
Bar gauge panel value hidden by vertical scroll bar in Firefox

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#32083]
**What happened**:

Firefox: I used a `Bar gauge` panel in orientation `Horizontal` with a few dozen series, it automatically displayed a vertical scrollbar.
**The scrollbar is overlapping and hiding part of the value.**

The default font size is also a little hard to read, but increasing value font size makes the layout worse.
(Dunno if this should be a whole separate issue on its own).

**What you expected to happen**:

The scrollbar must not overlap panel data, a right margin is needed if the scrollbar is visible.

**How to reproduce it (as minimally and precisely as possible)**:

- Use Firefox (on Windows 10 ?)
- Go to https://play.grafana.org , abuse any dashboard, edit or add a panel
- Get some series, I used prometheus:
  - Datasource `demo.robustperception.io`
  - Query: `topk(20, {__name__=~"node_.+"})`
  - Legend: `{{__name__}}`
  - Instant: `True`
![grafik](https://user-images.githubusercontent.com/33002073/111551404-67aeba80-8780-11eb-9233-b26a98931f4d.png)

- Set panel type to `Bar gauge` , Set `Orientation` to **Horizontal**

The scrollbar is overlapping the value:

![9AbsvGCK4F](https://user-images.githubusercontent.com/33002073/111551598-db50c780-8780-11eb-8246-1da7b569e707.gif)

If `Unit` **Misc / short** is used, it becomes worse for the user:

![QNLnFMXsU9](https://user-images.githubusercontent.com/33002073/111551683-0a673900-8781-11eb-89ba-1ba37844fc84.gif)

The value is more hard to read (all default settings, browser zoom is 100%) compared to the series name.

Increasing value font size is not helping either:

![grafik](https://user-images.githubusercontent.com/33002073/111551779-43071280-8781-11eb-8d35-bb6569e5d4f4.png)
![grafik](https://user-images.githubusercontent.com/33002073/111551850-6f229380-8781-11eb-9594-e7646f26ecec.png)

Nor does the Titel font size:

![grafik](https://user-images.githubusercontent.com/33002073/111551877-7ea1dc80-8781-11eb-8163-51603668d141.png)
![spt2MqygNs](https://user-images.githubusercontent.com/33002073/111551916-90837f80-8781-11eb-9511-91b65f24ede3.gif)

## Chromium Edge

Uses a slimmer scrollbar, layout ok, font size is still a little small

![grafik](https://user-images.githubusercontent.com/33002073/111552568-e99fe300-8782-11eb-992f-9d848ff1edf3.png)

Increasing font size yields same bad results as firefox.

## Workaround with Table panel in Firefox

Use new table panel, with cell display mode override, query table mode, and organize fields transformation (much more work to setup...)

![grafik](https://user-images.githubusercontent.com/33002073/111552162-10114e80-8782-11eb-8927-da9c516890ba.png)

**Environment**:
- Grafana version: `Grafana v7.5.0-beta1 (6b83895315)`
- Data source type & version: -
- OS Grafana is installed on: play.grafana.com
- User OS & Browser: Windows 10, 20H2, Build 19042.867, Firefox 86.0.1

**Comment by Bobrsson** [comment]
Hi. This issue has reappeared in v9.3.1 firefox 111.0 (64-bit).[изображение](https://user-images.githubusercontent.com/25799500/225296154-b116ed8b-a31e-4b70-a0ae-5b355cb28b0c.png)
Before that, version v9.0.3 was used - everything was fine.
![изображение](https://user-images.githubusercontent.com/25799500/225296354-dca56d48-6127-4887-9d03-877681155f22.png)

**Comment by zoltanbedi** [comment]
I was not able to reproduce this. Please let us know if this is still an issue and we can investigate.

**Comment by ryan-dyer-sp** [comment]
@zoltanbedi I still see this using grafana 10.3.3 and FF 125.0.3.  LMK if you want this as a new issue.
![image](https://github.com/grafana/grafana/assets/16764971/e1994190-34f8-44e9-8714-3d037b84dac1)

**Comment by zoltanbedi** [comment]
@ryan-dyer-sp yes, please create a new issue for this so the relevant team can pick this up.

**Comment by Navi2016** [comment]
Having the same issue in Grafana 11, but been there for months. Maybe even last years. Both in Firefox and Chrome.

Bar gauge is just a bit too wide so a horizontal scroll appears.

![afbeelding](https://github.com/grafana/grafana/assets/20399169/25545df5-44be-4c82-ad7b-c3c6c0a02023)

**Comment by MedAzizTousli** [comment]
Issue still exists in Grafana v11.5.2.
