### ISSUE TITLE
Create static URLs for templated dashboard views

### ISSUE THREAD

**Issue by seppyk** [grafana/grafana#3208]
Using Grafana 2.1.3...

Looking to see if I am missing something or if this is an absent feature.   If it's an absent feature, consider this an improvement request.  If it's already present, I'd love to know how to manage the following....

I am able to access a particular dashboard via a static URL with the generic format:

http://servername:port:3000/dashboard/db/dashboard_name

However, when the contents of the dashboard can be changed by template values, the dashboard is updated as a single-page HTML document so no static URL to access this view of the dashboard is obviously known.  

I would like support for static URLs for dashboard views, specifically integrated template variables.   

Some examples:

Single-select templates:
http://servername:port:3000/dashboard/db/dashboard_name?sport=Basketball&team=Bulls

Multi-select templates:
http://servername:port:3000/dashboard/db/dashboard_name?sport=Basketball&team=Bulls&team=Celtics&team=Lakers

This would allow for static linking of Grafana dashboard views from external sources.

**Comment by torkelo** [comment]
Click the share button in the top menu and check include template variables, the  you can  see how the url looks when variables are included

**Comment by mattttt** [comment]
I still believe this would be a significant UI improvement (pushing the current state of the dashboard into the URL as changes are made). The share functionality should be supplemental, but the Grafana audience would first look to the URL to copy/paste.

**Comment by torkelo** [comment]
yea, I agree
