### ISSUE TITLE
Raw query editor issue:

### ISSUE THREAD

**Issue by jhhayden** [grafana/grafana#3209]
Small issue.
I have a load avg graph using raw query editor. Five queries (1 for each host). If a host goes offline for any reason, it obviously will show no data being collected. What is interesting is that ALL queries after the affected host suddenly stop displaying data. I am using influxdb v9 and grafana v 2.5.2-pre1

**Comment by torkelo** [comment]
Can you show the influxdb query and response? Maybe a influxdb issue? You can see raw query andresponse in chrome dev tools network tab. Also do you have stack enabled? If so fill (0) could solve it

**Comment by jhhayden** [comment]
Here is the query I was using SELECT mean("value") * 100 AS "value" FROM
"system_load5" WHERE "host" = 'sigProcNFS' AND $timeFilter GROUP BY
time($interval).
All 5 queries are exactly the same except for the host value.

Yes stack is enabled and voila! That is what is causing this!! Thank you. I
actually didn't want this stacked but hadn't noticed that it had been
checked.

Again thank you.

John Hayden
