### ISSUE TITLE
Time series panel: Show current time line in 'graph' or in the new 'time series'

### ISSUE THREAD

**Issue by j-dc** [grafana/grafana#32096]
**What would you like to be added**:
I would like to add the current time as a vertical line to a graph.

'Current time' should most preferably be:  
 - The time the dashboard was loaded/query was executed

But could also be:  
- "a dashboard variable" or a even query (sometimes we need to show a remote systems time)

**Why is this needed**:
1) I am showing predictions and actual measurements on the same graph. A 'current time' line makes this types of visualisations much easier to interpret.
2) I have dashboards with measurements  with a time range (for example:)  from:" now/d"   to:  "now/d".   No longer received data would be much easier to be seen with a 'current time' line.

**Comment by j-dc** [comment]
Using SQL Server I added an annotaion:  SELECT sysdatetimeoffset() as time, 'now' as text

**Comment by mckn** [comment]
> Using SQL Server I added an annotation: SELECT sysdatetimeoffset() as time, 'now' as text

Thanks for this request. However would annotations be sufficient for your needs? Or are you looking for another way of solving this?

**Comment by j-dc** [comment]
I'm sorry for my late answer..  I did not notice your question.
Currently annotations are not sufficient at the moment.  When I don't have a datasource that is capable of rendering the current date-time I'm stuck.

The possibility of adding a 'special' annotation that always shows the 'time of requesting data' could be a solution.
Adding an option to all visualisations to show the 'time of requesting data' could also be a solution.


A few timestamps that could be considered:
 - Static 'time of request' as generated by the datasource. => this is what I do with the work around
 - static 'time of request' as generated by grafana-server 
 - static 'time of request' as generated by the browser
 - Continuously update 'current time' as generated by the browser
 - ...

**Comment by kalin-kozhuharov-exa** [comment]
Alternatively, once #35486 is fixed, this can be implemented as a special region called future, starting from now=query executed  to end_of_graph
