### ISSUE TITLE
line graphs not drawing all values

### ISSUE THREAD

**Issue by justajeffy** [grafana/grafana#3210]
Here's an example of line graphs not drawing correctly.  Notice values not being graphed and strangeness with the value indicators while scrubbing.

![huh](https://cloud.githubusercontent.com/assets/11652559/11102049/443b1f78-8888-11e5-96ef-3f671fa31e5e.gif)

If I switch it to bar graph, it looks correct:

![good](https://cloud.githubusercontent.com/assets/11652559/11102113/a84590b6-8888-11e5-884c-a33b23848e23.gif)

Using Grafana 2.5.  There are 2 queries in this graph.  Both using same Elasticsearch data source.

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/commit/dbe35bfed1c02bb590b11203d729f033776a6eb2
