### ISSUE TITLE
Update Page Title when URL Changes

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#3211]
This more specifically applies to Google Analytics tracking, but is a mild UX bug as well. 

When navigating around the the system, the page title isnt necessarily in sync with the URL displayed. 

To replicate:
Go into a dashboard, and then clicking over to a non-dashboard screen such User Profile. The Page Title remains the Dashboard Title. But if you refresh the page, the Title changes. 

![url title](https://cloud.githubusercontent.com/assets/2886187/11102799/b0142a38-888c-11e5-90a6-09bd25c302f5.gif)

The only reason this is an impact in Google Analytics is when filtering by Page Title, we're seeing a number of different pages falling under the same title.

**Comment by daniellee** [comment]
@mattttt Great news! This is fixed :-)
