### ISSUE TITLE
[ Grafana Image rendering ] Not showing "Direct link rendered image" option for dashboard rendering

### ISSUE THREAD

**Issue by VishalLahane** [grafana/grafana#32113]
As per **documentation** Grafana do support dashboard rendering via  Image rendering. 
Doc link: https://grafana.com/docs/grafana/latest/administration/image_rendering/

I could able to render panel without any issue but not dashboard.

Steps:
1. Go to dashboard.
2. Click on share 
3. Go to Link option
4.  Not able to see "Direct link rendered image" option for dashboard rendering.
![panel_render](https://user-images.githubusercontent.com/16710051/111637669-a9db0900-881f-11eb-8478-b42be61ba079.JPG)

![dashboard_render](https://user-images.githubusercontent.com/16710051/111637664-a8a9dc00-881f-11eb-97be-ad6c5b2c6796.JPG)

If we do not support this option then we need to correct the documentation.

**Comment by zoltanbedi** [comment]
With the share option you can only render panel but not dashboard. I'm not sure where should we mention this. @grafana/docs-squad

**Comment by achatterjee-grafana** [comment]
We will add a note. Thanks for the clarification @zoltanbedi.

**Comment by achatterjee-grafana** [comment]
@marefr, can you clarify if the docs need to change? Thank you.
