### ISSUE TITLE
Time series: fillBelowTo no longer works

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#32139]
spotted in dev dashboard: Panel Tests - Graph NG. nothing useful in console.

looks to have been regressed by multi-series tooltip color fixes: https://github.com/grafana/grafana/pull/32098

![image](https://user-images.githubusercontent.com/43234/111708703-56af8900-8814-11eb-8423-64030383a1eb.png)

**Comment by dprokop** [comment]
Think it's a regression after a6cb9fb295e593c8f9110dbc5d86aeff91225b41, Looking

**Comment by torkelo** [comment]
fixed
