### ISSUE TITLE
Playlist: Migrate edit view to React

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#32145]

**Comment by torkelo** [comment]
@hugohaggmark The dashboard and tags pickers are no trivial. Especially the dashboard picker (https://play.grafana.org/playlists/edit/2) is based on an old version of dashboard search. And using existing dashboard search components could be tricky. 

To keep this migration v1 as simple as possible I would use https://github.com/grafana/grafana/blob/master/public/app/core/components/Select/DashboardPicker.tsx. for the dashboard picker (And not the full dashboard search component). and the then use TagFilter for adding tags https://github.com/grafana/grafana/blob/master/public/app/core/components/TagFilter/TagFilter.tsx

We can then explore (probably post v8) how we can improve DashboardPicker UX to maybe open a modal that reuses our search components.

**Comment by hugohaggmark** [comment]
Fixed by #32218
