### ISSUE TITLE
Add User and Org Preferences (like theme, timezone)

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3214]
json_data column should be added to the user table as well, like we have for datasource table. This will help in saving user preferences as well as global defaults depending on user preferences.

**Comment by utkarshcmu** [comment]
@torkelo Which migrations should we use to add column "data" to **user** and **org** tables?

NewAddTableMigration or AddColumnMigration? Which is preferable?

```
{Name:"data", Type:DB_Text, Nullable:true}
```

**Comment by torkelo** [comment]
Not sure new columns are the best solution, would like a preference table / generic solution that allows for global, org and user level settings.

**Comment by grobie** [comment]
This would be massively helpful. All our dashboards should be in UTC (as we're a company with office in many timezones and matching server times is usually quite helpful).

@torkelo Do you have an idea how you like to see that implemented?

**Comment by utkarshcmu** [comment]
How about this kind of Table for preferences:

| id   | pref_id   | pref_type   | preferences                                                                    |
|-----|-------------|----------------|--------------------------------------------------------------------------|
| 1    | 4            | user           | {"timezone":"utc", "home_dashboard":"cpu-summary"}  |
| 2    | 3            | user           | {"timezone":"utc", "timepicker":{"from":"now-3h","to":"now"}}  |
| 3    | 1            | org             | {"home_dashboard":"app-summary","refresh_every":"never"}  |
| 4    | 0            | global        | {"home_dashboard":"company-summary","timepicker":{"from":"now-1h","to":"now"}}  |

```
id - row id
pref_id - id of user/org , for global we can use 0 or -1
pref_type - to identify whether the preference is for a user/org/global
preferences - saved as JSON text
```

This model is scalable and should not be too hard to implement.

Any thoughts? @torkelo @bergquist

**Comment by torkelo** [comment]
@utkarshcmu looks good, but the home_dashboard should just be a reference to a dashboard id (database id)

**Comment by utkarshcmu** [comment]
:+1: Good catch @torkelo :)

**Comment by torkelo** [comment]
@utkarshcmu btw, if you have time to work on this issue that would be amazing, :heart: , this feature would be so useful (and requested by MANY)

**Comment by utkarshcmu** [comment]
:+1: Sure !! :)

**Comment by utkarshcmu** [comment]
@torkelo Would you like to create a new branch for preferences, where we can develop it independent of master?

**Comment by utkarshcmu** [comment]
Then I can open a PR like #4251 for the preferences branch instead of master.

**Comment by torkelo** [comment]
@utkarshcmu 
Deleted the old preferences branch and created a new one
https://github.com/grafana/grafana/tree/preferences

**Comment by torkelo** [comment]
implemented and merged to master, 

![image](https://cloud.githubusercontent.com/assets/10999/14232934/0f3ac5ce-f96e-11e5-9af5-f6058f482f2c.png)

![image](https://cloud.githubusercontent.com/assets/10999/14232936/140b19f0-f96e-11e5-8606-3a35cb91439e.png)
