### ISSUE TITLE
Failed query if \r erroneously ends up in the query text 

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#32159]
**What happened**:
If somehow, an carriage return character ('\r') ends up in a query URL, it is not shown in the metric query text box, but it is submitted to the backend

**What you expected to happen**: the \r to be displayed in some way 

**How to reproduce it (as minimally and precisely as possible)**:
The following URL has a \r encoded in the first query 
```
https://snctest.grafana.net/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22grafanacloud-snctest-prom%22,%7B%22expr%22:%22probe_all_duration_seconds_sum%7Binstance%3D%5C%22https:%2F%2Fbbc.co.uk%2F%5Cr%5C%22%7D%22,%22requestId%22:%22Q-65a9909a-bc25-4fa2-8f94-a91d2385dbc9-0A%22%7D%5D&right=%5B%22now-6h%22,%22now%22,%22grafanacloud-snctest-prom%22,%7B%22expr%22:%22probe_all_duration_seconds_sum%7Binstance%3D%5C%22https:%2F%2Fbbc.co.uk%2F%5C%22%7D%22,%22requestId%22:%22Q-235f3ec7-3646-4cd0-9f00-02da40f3bcc0-0A%22%7D%5D
```
URL decoded this is 
```
https://snctest.grafana.net/explore?orgId=1&left=["now-6h","now","grafanacloud-snctest-prom",{"expr":"probe_all_duration_seconds_sum{instance=\"https://bbc.co.uk/\r\"}","requestId":"Q-65a9909a-bc25-4fa2-8f94-a91d2385dbc9-0A"}]&right=["now-6h","now","grafanacloud-snctest-prom",{"expr":"probe_all_duration_seconds_sum{instance=\"https://bbc.co.uk/\"}","requestId":"Q-235f3ec7-3646-4cd0-9f00-02da40f3bcc0-0A"}]
``` 
As you can see, there is a `\r` right before the closing quote in the `instance` filter. 

This results in the following 
![image](https://user-images.githubusercontent.com/8004654/111776748-49dd7480-88aa-11eb-8d2d-4060c9282de9.png)

As you can see, there is no indication of any hidden character in the query making it very hard to detect why the query is returning no results. 

Grafana should show some indication there is a non-printable character in the query. 

**Anything else we need to know?**:

**Environment**:
- Grafana version:  7.4.5 
- Data source type & version: n/a 
- OS Grafana is installed on: Grafana Cloud 
- User OS & Browser:  Windows / Firefox 
- Grafana plugins: n/a 
- Others: n/a

**Comment by ivanahuckova** [comment]
This was a result of copying/pasting the alert URL from an excel sheet. Looks like excel introduced the \r, so the only bug from our perspective is that we don't show it.

**Comment by ivanahuckova** [comment]
Problem is that carriage return is invisible character, therefore when we parse URL and get a query text from it, the carriage return is there, but it is not visible. 

This is how it looks when we console.log it:
![image](https://user-images.githubusercontent.com/30407135/112627788-545fb700-8e32-11eb-8e31-d7bb9531bfd1.png)
 
To fix this, we should probably remove this invisible character from the query string.

**Comment by simonc6372** [comment]
I think we should consider fixing this in the UI to display something when a non-printable character is in the query. This would solve the issue for any non-printable character and for all datasources.
