### ISSUE TITLE
[Enhancement request] Fixed Rows

### ISSUE THREAD

**Issue by baur** [grafana/grafana#32157]
**What would you like to be added**:

Fixed ROWs

**Why is this needed**:

Use ROW as drill down panel in same page 
When scroll down table. Row becomes invisible (

![image](https://user-images.githubusercontent.com/2898361/111773726-bc654900-88d8-11eb-83ef-ab5ced56dd4f.png)

**Comment by baur** [comment]
When user cursor ends up scrolling the table, the page being scrolled up, this time detail row is scrolls up and becomes invisible, very sad. 

Team, 
Please, return table pagination #26022

**Comment by torkelo** [comment]
Yea, not sure this I understand this. 

Closing it as we have #26022

sticky rows do not make sense and won't be possible given the grid layout framework
