### ISSUE TITLE
Rendering Flot and drawAsInfinite() visualization problem

### ISSUE THREAD

**Issue by suslikas** [grafana/grafana#3215]
A find some different between "Graphite PNG" and "Float" visualization when i use drawAsInfinite(). When i try show events like:

![graff1](https://cloud.githubusercontent.com/assets/10547842/11114287/597fb1c4-892c-11e5-99ba-a2bf80f77e29.png)

I get result like:

![graff2](https://cloud.githubusercontent.com/assets/10547842/11114307/775b5536-892c-11e5-818f-472a80514dc2.png)

Red dot because I turn on "Series specific override". What i expected, result like this, but it's possible only if i configure Annotation for current Dashboard.

![graff3](https://cloud.githubusercontent.com/assets/10547842/11114358/d87c3ede-892c-11e5-9efc-bdf777da651c.png)

By the way, what i want, work for "Graphite PNG"
![graff4](https://cloud.githubusercontent.com/assets/10547842/11114379/00054086-892d-11e5-9677-a229e63e7f5b.png)

Pkg's:
```
CentOS Linux release 7.1.1503 (Core) 
grafana-2.1.3-1.x86_64
graphite-web-0.9.12-8.el7.noarch
```

**Comment by torkelo** [comment]
yea, you have to use annotations for something equivalent to drawAsInfinite

**Comment by suslikas** [comment]
Yes, but it's for all graphs, not very good in my case, because i try to apply it for monitors on wall, with show graphics from different systems. As workaround now i use this solution with "Series specific override"

![graff6](https://cloud.githubusercontent.com/assets/10547842/11115240/cc67a196-8932-11e5-836f-efcfac7f8bbb.png)

This information for anyone who also have like this problem.
