### ISSUE TITLE
Overwritten numbers in gauge

### ISSUE THREAD

**Issue by zhum** [grafana/grafana#32152]
**What happened**:
On some dashboards (not all) I always get a strange bug: with gauge visualization new numbers not replace old ones like this: ![...](https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/6/6022a947fbe17ede50830a3f8183f73734358db0.png). Present in FireFox and Chrome too.

I use VictoriaMetrics source (via prometheus plugin), grafana 7.4.1. Live dashboard is here: http://a1.lom2.parallel.ru:8089/d/x8FaJxFMk/lomonosov-2-kratko?orgId=1&from=now-2d&to=now&refresh=5m

**What you expected to happen**:

New numbers replace old ones.

**How to reproduce it (as minimally and precisely as possible)**:

I cannot reproduce it on modelling dashboard. I think, this bug appears with many elements on dashboard (not sure).

**Anything else we need to know?**:

I am ready to test experimental patches, send any additional information or data.

**Environment**:
- Grafana version: 7.4.1
- Data source type & version: prometheus (2.0)
- OS Grafana is installed on: Linux Centos 7.9
- User OS & Browser: Linux Mint 20, FF 86.0.1, Chrome 89.0.4389.90
- Grafana plugins: Standart from Grafana labs plus ZabbixBy Alexander Zobnin (not used here)
- Others:

**Comment by ryantxu** [comment]
Most likely you also have single stat math plugin installed -- that will consistently do the behavior you see here
