### ISSUE TITLE
A way to configure $__rate_interval to use 2 * scrape_interval instead of 4 * scrape_interval

### ISSUE THREAD

**Issue by candlerb** [grafana/grafana#32169]
**What would you like to be added**:

The new variable `$__rate_interval` is [defined](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) as
 
`max( $__interval + Scrape interval, 4 * Scrape interval)`

I would like a way to configure it as

`max( $__interval + Scrape interval, 2 * Scrape interval)`

**Why is this needed**:

This is when drawing graphs from Prometheus using `rate(...expr...[$__rate_interval])`

Let's say that the counter data (expr) is being sampled at 1 minute intervals.  And let's say that within one minute, there is a burst.

The problem is, using `rate(...expr...[4m])`, the burst is smeared over a 3-minute window in the graph.  It simply does not reflect accurately what happened from minute to minute.

Using `rate(...expr...[2m])` gives the correct result.  The `[2m]` time range picks up two adjacent samples and computes the rate between them.

Essentially: with the current setup, polling with prometheus at 1 minute intervals ends up being nearly as bad as polling in Cacti with 3 minute intervals.

**Notes**:

It's still possible for a burst to be smeared over two buckets, if it happens to straddle the sampling interval.  I expect that.  But in that case, I don't expect it to be smeared over 3 or 4 minutes.

It's true that if a scrape is missed, this will result in a gap in the graph.  This is fine by me.  Missed data -> gap in graph -> this means I can see that there was missed data.  In practice, I find scrapes are very rarely missed anyway.

As a kind-of workaround, you can set the data source interval in Grafana to be half of the true sampling rate (i.e. `30s` in this case).  However it's still not quite right, as it now calculates

`max($__interval + 0.5 * scrape interval, 2 * scrape interval)`

This means when zoomed out a long way, say where the graph interval is 5m, we now get 5.5m instead of 6m as the rate window.  This isn't too bad, but a 5.5m window sometimes contains 5 points and sometimes contains 6 points, so some points will represent a rate over 4 minutes, and some points will be a rate over 5 minutes, and that's icky.

Finally, this may all become moot, if and when prometheus provides a new rate function which [does what people expect](https://github.com/prometheus/prometheus/issues/3806).  This is apparently [still under consideration](https://github.com/prometheus/prometheus/issues/3806#issuecomment-748522887).

**Comment by aocenas** [comment]
Hey @candlerb did you read this https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/. It should explain why we went with 4 * scrape interval.

Also maybe @beorn7 if you have some thoughts on this, could you chime in?

**Comment by beorn7** [comment]
`$__rate_interval` is meant to be a solution that gives a robust result in most cases. Giving it many knobs to configure would defeat the purpose.

For special cases, there is usual a way even now. For perfect customizability, it would be cool if either PromQL or the Grafana templating allowed arithmetic. I cannot speak for Grafana, but the chances of this happening in PromQL are rising.

Very generally, I recommend to embrace that this is a tough problem to get right. Assuming there is a simple way that solves all trouble ("what people expect") and the Prometheus developers are just too stupid to accept that is unlikely to get you closer to a solution.

**Comment by davkal** [comment]
Agreeing with @beorn7 's assessment here. The tradeoff here is robustness vs resolution, and we're leaning towards robustness. Hence if you like a higher resolution, we recommend adjusting your scrape interval down. 
If that's not an option, here is another approach: you could have two datasources pointing to the same prometheus with different scrape intervals in the datasource settings, then you essentially have control over one part of the `$_rate_interval` variable.
