### ISSUE TITLE
Grafana 7.4.5 datasource configuration InfluxQL for InfluxDB 2.x

### ISSUE THREAD

**Issue by faandg** [grafana/grafana#32183]
**What happened**:
InfluxDB v2 OSS now supports both Flux and InfluxQL.
However, selecting InfluxQL in the datasource configuration does not allow specifying token, organization and bucket for InfluxDB v2.
Instead, it only gives parameters to connect to InfluxDB 1.x (database, user, password).

**What you expected to happen**:
Token, organization and bucket for InfluxDB v2 configurable when selecting InfluxQL.

**How to reproduce it (as minimally and precisely as possible)**:
User scenario: you have InfluxDB 2.0 and want to use InfluxQL as query language instead of Flux.

Create a new datasource, select InfluxQL:
![image](https://user-images.githubusercontent.com/5772741/111881914-0cb0d980-89b3-11eb-8c8f-b403c921c778.png)

Gives you:
![image](https://user-images.githubusercontent.com/5772741/111882031-8ea10280-89b3-11eb-9f8a-36e1ddb46d5a.png)

But for InfluxDB v2 you want the following parameters:
![image](https://user-images.githubusercontent.com/5772741/111881987-5ef1fa80-89b3-11eb-8937-e1295e755d25.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: InfluxDB 2.0.4
- OS Grafana is installed on: official docker image (latest (7.4.5))
- User OS & Browser: Windows 10 & Brave
- Grafana plugins: grafana-clock-panel,grafana-simple-json-datasource,grafana-piechart-panel,grafana-worldmap-panel
- Others:

**Comment by ivanahuckova** [comment]
Hello @faandg, this is possible. Please look at this guide to set up your Influxdb2 data source with InfluxQL: https://ivanahuckova.medium.com/setting-up-influxdb-v2-flux-with-influxql-in-grafana-926599a19eeb There is also an example in  Grafana documentation https://grafana.com/docs/grafana/latest/datasources/influxdb/#influxdb-2x-for-influxql-example.
