### ISSUE TITLE
Grafana UI Tab does not honor themes stylesheet

### ISSUE THREAD

**Issue by josephlim75** [grafana/grafana#32192]
**What happened**:
Grafana UI Tab does not honor themes color changes

**What you expected to happen**:
When changing `brand-gradient-horizontal` in `_variables.xxxx.scss.tmpl.ts`, the tab style should change as expected.  The vertical gradient color is working but not the horizontal

**How to reproduce it (as minimally and precisely as possible)**:
The horizontal `Settings` tab (activeTabStyle) is still using the old gradient theme
![image](https://user-images.githubusercontent.com/21043283/111920652-7e962b00-8a66-11eb-8306-a857f21f07b2.png)

Working Vertical gradient
![image](https://user-images.githubusercontent.com/21043283/111920678-ab4a4280-8a66-11eb-8d77-c82f3c8118b5.png)

**Anything else we need to know?**:
I have look into the code, the Tab.tsx (packages/grafana-ui/src/components/Tabs/Tabs.tsx) is returning a fix styles for `background-image`.  In theory, it should return the a variable from theme
![image](https://user-images.githubusercontent.com/21043283/111920715-e64c7600-8a66-11eb-917d-cb6812bc76d4.png)

**Environment**:
- Grafana version: v7.4.5
- Data source type & version: any datasource
- OS Grafana is installed on:  grafana docker
- User OS & Browser:  Mac OSX
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
As you can see it's not using a theme variable for this element.

We will soon a start a major theme refactoring , should address this
