### ISSUE TITLE
V7.4.3 Templating value groups: removes all values

### ISSUE THREAD

**Issue by sensej-j** [grafana/grafana#32190]
Hello everybody,
if you remove a Tag, then all values are removed

example

![1](https://user-images.githubusercontent.com/78264478/111906026-ef314d80-8a4e-11eb-9957-b2f6597c7266.jpg)

remove Tag Europe

not correct
![2](https://user-images.githubusercontent.com/78264478/111906043-0a9c5880-8a4f-11eb-8139-a7bbd99dd68e.jpg)

correct
![3](https://user-images.githubusercontent.com/78264478/111906116-518a4e00-8a4f-11eb-8e3c-36111f69069e.jpg)

https://play.grafana.org/d/000000024/templating-value-groups?orgId=1&var-host=10.1.100.1&var-host=10.1.100.10&var-host=server1&var-host=server2&var-host=server3&var-host=server4

**Comment by torkelo** [comment]
Ok, this is a experimental feature we are deprecating in v8 so wont fix this
