### ISSUE TITLE
Table Panel 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3219]
Flexible table panel to visualize time series and raw documents. 

http://play.grafana.org/master/dashboard/db/table-panel-showcase

#### Data to Table transforms
* Time series to rows
* Time series to columns
* Annotations (queries in metrics tab will be ignored) table will instead show annotation data
* JSON Data 

#### Display options
* Paging options
* Enable/disable scroll (if scroll is disabled the table panel height will be as high as to fit all page rows)
* Font-size 

#### column styles
* Date formats
* Number threshold coloring
* Unit formats & decimal control

![image](https://cloud.githubusercontent.com/assets/10999/11120124/4fb97e14-894e-11e5-961e-3bec992dbf47.png)

### Try it and give feedback

http://play.grafana.org/master/dashboard/db/table-panel-showcase

It is available in pre release build in of 2.6
http://grafana.org/download/builds.html

**Comment by jmaitrehenry** [comment]
I just play with it and I really love it, and I would like to have it now on production haha!
Do you have a pre-build for 2.6?

**Comment by phagedorn** [comment]
https://grafanarel.s3.amazonaws.com/builds/grafana_2.6.0-pre1_amd64.deb

**Comment by fsauer65** [comment]
Looks great! One question : can it do influxdb tags as columns?

**Comment by snicaise** [comment]
Could be amazing if table include sparklines and bullet graph, something like this http://www.startuplifeblog.com/tag/sparklines/, or like the cover of the book [Information Dashboard Design](http://www.amazon.fr/Information-Dashboard-Design-at-glance/dp/1938377001).

You can find other sample by searching "dashboard design sparkline" on google image.

**Comment by utkarshcmu** [comment]
@torkelo This looks awesome. Played around with it and I am sure that this will be used a lot. 

Does it support annotations? If not then for every annotation, we can have a row in the table between the datapoints depending on the time of the annotation.

You work looks great, inspiring. !!!

**Comment by torkelo** [comment]
@utkarshcmu yes, it has a annotations mode, in the Data to table transform dropdown (if selected then it will only show annotations)

**Comment by cschotke** [comment]
Looks great. Will there be any way to show aggregate values? For example, rows would be server names and columns would be max/min/avg CPU values.

**Comment by alexanderzobnin** [comment]
It's awesome! @cschotke :+1:  It would be great to show realtime data at this table.

**Comment by cemo** [comment]
:heart:

**Comment by godfreyhe** [comment]
It's exciting :+1: 

druid datasource is my datasource, and I am developing druid plugin base on https://github.com/quantiply/grafana-plugins/tree/master/features/druid now. I want to add customer define column in table base on the response results. such as: select * in druid, and result like below:

[ {
  "timestamp" : "2015-11-06T10:00:01.231Z",
  "result" : {
    "pagingIdentifiers" : {
      "test_2015-11-06T18:00:00.000+08:00_2015-11-06T19:00:00.000+08:00_2015-11-06T18:00:03.381+08:00" : 2
    },
    "events" : [ {
      "segmentId" : "test_2015-11-06T18:00:00.000+08:00_2015-11-06T19:00:00.000+08:00_2015-11-06T18:00:03.381+08:00",
      "offset" : 0,
      "event" : {
        "timestamp" : "2015-11-06T18:00:01.231+08:00",
        "allowed" : "true",
        "cmd" : "listStatus",
        "ugi" : "hadoop",
        "src" : "/hbase/archive",
        "dst" : "null",
        "perm" : "null",
        "proto" : "rpc",
        "count" : 1
      }
    }, {
      "segmentId" : "test_2015-11-06T18:00:00.000+08:00_2015-11-06T19:00:00.000+08:00_2015-11-06T18:00:03.381+08:00",
      "offset" : 1,
      "event" : {
        "timestamp" : "2015-11-06T18:00:01.253+08:00",
        "allowed" : "true",
        "cmd" : "listStatus",
        "ugi" : "hadoop",
        "src" : "/hbase/oldWALs",
        "dst" : "null",
        "perm" : "null",
        "proto" : "rpc",
        "count" : 1
      }
    }, {
      "segmentId" : "test_2015-11-06T18:00:00.000+08:00_2015-11-06T19:00:00.000+08:00_2015-11-06T18:00:03.381+08:00",
      "offset" : 2,
      "event" : {
        "timestamp" : "2015-11-06T18:00:06.325+08:00",
        "allowed" : "true",
        "cmd" : "getfileinfo",
        "ugi" : "hadoop",
        "src" : "/tmp/hservice.split",
        "dst" : "null",
        "perm" : "null",
        "proto" : "rpc",
        "count" : 1
      }
    } ]
  }
} ]

I want show all the dimensions (allowed, cmd, ugi ......, which are dynamic) in the table column

**Comment by victorhooi** [comment]
Would it be possible to add sparklines to the table panel? I think that would be pretty awesome =).

(#78 and #251 both mentions sparklines in passing, but they haven't been commented on in some time.)

**Comment by alexiri** [comment]
There's a small rendering bug on mobile devices (or probably anything with a small screen).

![screenshot_2015-11-14-08-30-37](https://cloud.githubusercontent.com/assets/5055697/11163453/dd848ef4-8ad0-11e5-8db0-36eb44ca4fa8.png)

**Comment by torkelo** [comment]
I added support for time series aggregations -> table transform (similar to the graph legend).

![image](https://cloud.githubusercontent.com/assets/10999/11246157/b94bbe6a-8e16-11e5-8611-496815302b7d.png)

**Comment by torkelo** [comment]
Elasticsearch when used with the table panel now works with aggregations without using the date_histogram, so you can get tables like this:
![image](https://cloud.githubusercontent.com/assets/10999/11309874/b602dbf6-8fc6-11e5-9ec9-f48704b487f0.png)

**Comment by alexanderzobnin** [comment]
Great! It's more flexible than table view in last Kibana.

**Comment by jmaitrehenry** [comment]
Yeah ! Now if we can have spark line on a table it will be perfect!

**Comment by biancalana** [comment]
yeah !

spark line which "pins" points displayed on each line aggregated field, some thing like this:
![image002 copy](https://cloud.githubusercontent.com/assets/242632/11311267/dd69161c-8fb5-11e5-9a45-dc58b32f7b70.png)

**Comment by fsauer65** [comment]
That looks great! Something similar for an InfluxDB series with tags would be awesome, (where @source and @hostname are tags and site, server1, etc. are tag values)

**Comment by victorhooi** [comment]
This issue is closed - I raised #3308 for the sparklines in tables - feel free to add your thoughts =).

**Comment by timgriffiths** [comment]
+1 for influxdb 

Be awesome to do something like 
```
select value2, value1, tag0, tag1, tag2 from onyxorders where $timeFilter ORDER BY time DESC LIMIT 10
```

**Comment by msylla** [comment]
Hi ! Merci for this great feature, so awaited

We are testing it right now in our company (master branch) but couldn't make work the "JSON Data - Table to transform" module.

Here is the JSON structure that we do have in our InfluxDB table (in 'value' column)
    [
      {
        "pid": 1908,
        "command": "java",
        "percent_cpu": 12.70
      },
      {
        "pid": 61937,
        "command": "java",
        "percent_cpu": 0.73
      },
      {
        "pid": 32401,
        "command": "collectd",
        "percent_cpu": 0.36
      }
    ]

and the result that we get in the table panel is : 

    [null,1448650798000]
    [null,1448650797000]
    [null,1448650796000]

Are we missing something ? Or does this module isn't done yet ?
![capture1](https://cloud.githubusercontent.com/assets/6760754/11447161/f63771a2-9541-11e5-89b1-f4b7bcd5e3c2.PNG)
![capture2](https://cloud.githubusercontent.com/assets/6760754/11447162/f932b2f4-9541-11e5-86eb-e87389f34d90.PNG)

**Comment by torkelo** [comment]
@timgriffiths this is now possible: 
https://github.com/grafana/grafana/issues/3409

**Comment by KSGBridgeman** [comment]
Not quite there yet for me.  I am pulling a Batch Process Summary and I want to see.

Select processName, sum(totalRecords), sum(totalErrors), avg(TimePerTrx), avg(TrxTime)
where @timestamp in range[yesterday, now]
group by processName

Table would look like:
processName, sum totalRecords, sum totalErrors, avg TimePerTrx, avg TrxTime

**Comment by hydandata** [comment]
Sorry for OT, but @biancalana what tool is featured in that screenshot of yours? it looks rather nice.

**Comment by amoussoubaruch** [comment]
Hi, 

I'm start using grafana with druid and i don't find any documentation for doing template variable. 
Please can you give me some ideas? 

Thanks

**Comment by torkelo** [comment]
Asking this question on a random issue is a bit strange, your best bet is to reach out to druid plugin authors, or try post question in community site

**Comment by tinder-ubhatnagar** [comment]
@abhisant can you please answer @amoussoubaruch , thanks buddy!

**Comment by amoussoubaruch** [comment]
It's good now! I use $NameTemplate
