### ISSUE TITLE
Feature Request: runbooks attached to alerts

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#32195]
**Grafana Runbooks**: Attach Runbook to an alert along with Notification and other settings.

**Why is this needed**: Currently, we notify the Grafana users when an alert is fired. Either we put in the steps to remediate the problem in the Message section OR we just post the URL of the Runbook in the Message section. Everyone uses their own way to write runbooks. Some use Confluence, some Google Docs, etc. and copy these Confluence and Google Doc URLs in the Message Section of the alerts. There is no standard way of storing these runbooks and we have to go to one more platform/URL to read and follow these Runbooks instead of staying within Grafana's ecosystem.

**Proposed Screenshots**:

_Adding a Runbook section in the alert itself._

<img width="657" alt="Screen Shot 2021-03-21 at 9 49 48 PM" src="https://user-images.githubusercontent.com/1019609/111941906-5e2e9680-8a8f-11eb-9aae-49c2c1d0b448.png">

_Attaching a runbook with the alert._

<img width="343" alt="Screen Shot 2021-03-21 at 10 35 07 PM" src="https://user-images.githubusercontent.com/1019609/111944841-c5e7e000-8a95-11eb-86ff-0db78f0b33c6.png">

_Adding a Runbooks nav item in alerting dropdown._

<img width="251" alt="Screen Shot 2021-03-21 at 10 25 05 PM" src="https://user-images.githubusercontent.com/1019609/111944194-4dccea80-8a94-11eb-9635-c803800b8ce7.png">

_Adding a Runbook section in alerting main page._
_(The selected tab should be Runbooks, its just a prototype for now)_

<img width="614" alt="Screen Shot 2021-03-21 at 10 34 15 PM" src="https://user-images.githubusercontent.com/1019609/111944899-e3b54500-8a95-11eb-96a8-dacbb2d29a92.png">

_Creating a Runbook._

<img width="627" alt="Screen Shot 2021-03-21 at 10 34 30 PM" src="https://user-images.githubusercontent.com/1019609/111944965-0182aa00-8a96-11eb-975d-51e2eb3df279.png">

**Comment by torkelo** [comment]
We have a big team now working on a new alerting engine. Will be looking at stuff like this later in the year

**Comment by utkarshcmu** [comment]
Sounds good! 👌

**Comment by peterholmberg** [comment]
This feature is available in Grafana 8 Alerting (unified alerting).

**Comment by gillesdemey** [comment]
Runbook URLs can now be attached to any Grafana alert.
