### ISSUE TITLE
Tabbed view of dashboards to logically group relevant graphs

### ISSUE THREAD

**Issue by avnivamsikrishna** [grafana/grafana#322]
@torkelo  Does Grafana support tabbed view  (or any other way) of logical stacking or grouping graphs.   Currently to add a tab, I have to hard-edit the  /src/app/partials/dashLoader.html and add a list item

By doing so, I am able to have the following view and functionality:

{{Disk IO group of graphs}}
![diskio_grafana](https://cloud.githubusercontent.com/assets/6082425/2720087/ea2f308c-c56a-11e3-8bae-fa4347ef0f23.png)

{{Throughput group of graphs}}
![throughput_grafana](https://cloud.githubusercontent.com/assets/6082425/2720090/ec6c7f80-c56a-11e3-97ab-2b85d49f9f91.png)

So, when a user clicks Disk Usage, he is directed to graphs related to Disk usage, similarly when user clicks on Throughput, the user is directed to graphs related to throughput. 

The problems is:
- As the changes are global, we can not reuse grafana for another scripted dashboard as it contains the global changes made to provide the logical tabbed view.

Is there any other intuitive way  of providing a local tabbed view apart from saving dashboard json to elastic search?

**Comment by gsaray101** [comment]
Or maybe tabs withing the same graph?

**Comment by gsaray101** [comment]
+1 Torkel, implementing this could really help organizing the dashboars. If there are many many apps and many many metrics, you dont want to create bunch dashboard for the same app. Create one and within that organize it more with tabs.

**Comment by JohnArrowwood** [comment]
I currently use collapsed rows in place of "tabs" but I hate the fact that it is vertical.  I came here because I was looking for a way to create horizontal tabs.  So, +1 from me on the ability to add tabs as a grouping element.

**Comment by cholcombe973** [comment]
+1 I could really use this

**Comment by shanky05** [comment]
+1 really useful

**Comment by sbengo** [comment]
Well, +1 :)

As an example, tabs would be like that:
<h5> Tab1 </h5>
![tab1](https://cloud.githubusercontent.com/assets/13196237/11791721/9df4ccba-a2a2-11e5-8ed7-cd3f3d6586a3.jpg)
<h5> Tab2 </h5>
![tab2](https://cloud.githubusercontent.com/assets/13196237/11791722/9e09523e-a2a2-11e5-9604-2bb261bb9485.jpg)

**Comment by lorantkurthy** [comment]
+1

**Comment by goby** [comment]
+1 really useful if dashboard is too large to send tens queries

**Comment by whittin3** [comment]
+1 Would be very useful!

**Comment by shanson7** [comment]
+1 Would allow much cleaner dashboards.

**Comment by rasjoy** [comment]
+1

**Comment by apmits** [comment]
+1

**Comment by tumani1** [comment]
+1

**Comment by m0nhawk** [comment]
+1

**Comment by shreyas-agnihotri** [comment]
+1

**Comment by Keshav97** [comment]
+1

**Comment by wxy1995** [comment]
+1

**Comment by iMbaundso** [comment]
+1

**Comment by liuhuiiris126** [comment]
+1

**Comment by haiyuanhe** [comment]
+1

**Comment by nizamsp** [comment]
+10

**Comment by priyankauppu** [comment]
+1

**Comment by B0go** [comment]
+1

**Comment by torkelo** [comment]
We are introducing dashboard folders which will allow you to group dashboards.

Having tabs on the dashboard is not something the core team plan to implement (we have rows that does fill a very similar role already). Closing this. Does not mean we will not accept a PR if the PR does not add that much complexity or maintainability burden.

**Comment by efvhi** [comment]
sorry about this request being closed , +1 btw

**Comment by realwuffi** [comment]
+1

**Comment by ganzux** [comment]
10 years later and still missing this feature :(

**Comment by iKrushYou** [comment]
+1

**Comment by brianzilliz** [comment]
+1

**Comment by mdashti** [comment]
+1

**Comment by B0go** [comment]
+1

**Comment by melissa-ng** [comment]
+1

**Comment by mspray** [comment]
+1

**Comment by mspray** [comment]
I have to create scenes just to have tabs, and I have to manage everything manually now (variables, date picker, etc.), my dashboards, which had everything I needed (except tabs), are now applications that are much harder to maintain.

[https://grafana.com/blog/2024/10/31/grafana-dashboards-are-now-powered-by-scenes-big-changes-same-ui/](grafana-dashboards-are-now-powered-by-scenes-big-changes-same-ui)

maybe there's hope

+1

**Comment by mehran-prs** [comment]
+1

**Comment by raghav110783** [comment]
+1
This would modernize and simplify the view of dashboard

**Comment by robbydf** [comment]
+1

**Comment by therealhieu** [comment]
+1

**Comment by antonio-wundermart** [comment]
+1, rows and tabs are NOT the same when it comes to UI/UX, and moreover with tabs you can lazy load data only when an user clicks occurs, on the contrary clicking an entire row will load each of the sub panels.

**Comment by Batwam** [comment]
I'm a tab user in Metabase and really miss it in Grafana

**Comment by orkhan-huseyn** [comment]
+1
