### ISSUE TITLE
Odd behavior on panel with over 15 metrics in 1.9.1

### ISSUE THREAD

**Issue by edasque** [grafana/grafana#3220]
I have a panel with 20 or so metrics. Alias & value seem to collide after the 15th metric in odd fashion. I am not seeing the issue in 2.5.x. Is there a way to back port the fix to 1.9.1?

![grafana_-_eco__qastage__-_test](https://cloud.githubusercontent.com/assets/219187/11120750/ebb188ea-891f-11e5-9bf9-e9c3a9a290a1.png)
![grafana_-_eco__qastage__-_test](https://cloud.githubusercontent.com/assets/219187/11120778/0de2c73a-8920-11e5-97e5-5d4bcdc829f0.png)

**Comment by torkelo** [comment]
the limit was increased in 2.0, no backwards are going to done at this point :(
