### ISSUE TITLE
flowcharting plugin dashboard kept open causes grafana memory issue and crash

### ISSUE THREAD

**Issue by lavensj** [grafana/grafana#32205]
Hi,

We've noticed that a dashboard holding a panel, build with the flowcharting plugin, is causing grafana (running on a ubuntu 20.04 LTS server) to steadily grow it's memory usage over a short time! This results in a grafana service crash on the Ubuntu server, when the dashboard is kept open (multiple hours). Important note is that this only happens when the dashboard is opened in Chrome (here on a Windows 10 OS), but seems not to occur when the dashboard is opened in firefox on the same device.

The dashboard only contains one panel, build with the latest version of the flowcharting plugin, fetching data from a mixed data source (see environment description). I've added the dashboard json: 
[dashboard.json.zip](https://github.com/grafana/grafana/files/6181257/dashboard.json.zip)

Environment:
- grafana v7.4.2
- flux & influx datasource (influx v1.8.4) & postgres datasource (v9.6)
- grafana installed on Ubuntu 20.04 LTS
- dashboard opened in Chrome on Windows 10 OS
- grafana plugins: flowcharting plugin (v0.9) (https://grafana.com/grafana/plugins/agenty-flowcharting-panel/)

**Comment by zoltanbedi** [comment]
Hi @lavensj is it possible that you configured your data source like this https://github.com/grafana/grafana/issues/31136#issuecomment-779212458

**Comment by lavensj** [comment]
Hello @zoltanbedi, setting the http_addr parameter in the grafana.ini seems to have fixed the memory issue. Thanks!

**Comment by lavensj** [comment]
After a few days time, the memory did increase on the server and crashed it, hooray-ed a bit too early.

**Comment by lavensj** [comment]
A temporary fix is to use another browser than chrome.
The memory issue is resolved when using edge (chromium version).

Can you look into the difference between using edge vs chrome for the above grafana functionality to fix this issue permanently?

Google Chrome 89.0.4389.90 (Official Build) (64-bit)
Edge Chromium 89.0.774.57 (Official build) (64-bit)

**Comment by zoltanbedi** [comment]
I'm looping in @grafana/grafana-frontend-platform. Is this something related to plugin or grafana?

**Comment by lavensj** [comment]
It should be related to the flowcharting plugin, since it only happens when these are opened.

**Comment by zoltanbedi** [comment]
Then I suggest to open an issue there https://github.com/algenty/grafana-flowcharting/issues
