### ISSUE TITLE
Field override 'Unit' now applies to all cells in a Table

### ISSUE THREAD

**Issue by Duologic** [grafana/grafana#32203]
![2021-03-22-085226_1631x338_scrot](https://user-images.githubusercontent.com/3349855/111957889-e1320a00-8aec-11eb-825a-81fd6b2cb13e.png)

**What happened**:
This table view previously showed the label values of a prometheus data source, now it shows NaN instead. This gives me an indication that the Unit field override is also applied to the label values.

**What you expected to happen**:
I expected to see the label values if the string value can't be casted to the unit.

**How to reproduce it (as minimally and precisely as possible)**:
* Create a Table
* Add a prometheus query (format: table, instant: true)
* Go to Field tab on the right
* Standard options, set Unit: Datetime ISO
* Observe field values become 'NaN'

**Anything else we need to know?**:
This is on the internal Grafana Labs setup that follow the latest master. The same dashboard on the stable release shows the values, that has version Grafana v7.3.3 (2489dc4d3a).

**Environment**:
- Grafana version: v7.5.0-14871pre (d3544d6df1)
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana docker image
- User OS & Browser: Linux/Firefox
- Grafana plugins: n/a

**Comment by torkelo** [comment]
You need to set the unit as an override if you do not want it to affect all columns

**Comment by torkelo** [comment]
this change was to fix issue with not being able to format dates in string fields, https://github.com/grafana/grafana/pull/30979

**Comment by Duologic** [comment]
That makes sense, I bet that it now behaves more consistent even if it breaks something. Feel free to close this.
