### ISSUE TITLE
Piechart doesn't appear on a dashboard.

### ISSUE THREAD

**Issue by Pharmacist12** [grafana/grafana#32211]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

When I try to open a dashboard containing a piechart, it returns the following error:
![Снимок экрана из 2021-03-19 14-57-34](https://user-images.githubusercontent.com/80956119/111987466-51a64e80-8b20-11eb-9210-ead00db26ea0.png)

The n.plot seems to be defined in module.js:

n.plot.plugins.push({init:function(e){var t=null,i=null,r=null,o=null,l=null,a=null,s=!1,c=null,h=[];function d(e,o,l){s||(s=!0,t=e.getCanvas(),i=n(t).parent(),r=e.getOptions(),e.setData(function(e){for(var t=0,i=0,o=0,l=r.series.pie.combine.color,a=[],s=0;s<e.length;++s).
Environment:
- Grafana v4.4.3
- Data source  Zabbix
- Grafana is installed on Ubuntu 
- My OS Centos 7 OS, browser Firefox v
- Grafana plugin that is not working properly is Piechart plugin v1.6.1

**Comment by torkelo** [comment]
please upgrade grafana and make sure your using the latest version of the plugin
