### ISSUE TITLE
Grafana confused over metrics

### ISSUE THREAD

**Issue by rackunits** [grafana/grafana#3221]
While writing some glue between PCP(.io) and Grafana I came across something odd.
When I hover over some graphs I get data from different time stamps: https://www.dropbox.com/s/j9f6if8esychf6y/Screenshot%202015-11-12%2014.16.57.png?dl=0

My datasource is influxdb (InfluxDB 0.9.5-nightly-f0efd1f) with the following data:
https://www.dropbox.com/s/qaip3ay56zyhpl2/Screenshot%202015-11-12%2014.12.37.png?dl=0

The grafana version I'm using is: 2.1.3,

The only reason I can come up with is the sampling interval with which I extracted data from the PCP archives. Note the intervals from host ....1 and 6, they are not at the exact same moment.

**Comment by torkelo** [comment]
Try using Grafana 2.5, There is some issues with the all series tooltip when the series are using different group by time intervals, might have been a small improvement in 2.5
