### ISSUE TITLE
Any newer then 7.2.2 Grafana is not accessible behind F5 loadbalancer, logs added, sequel to the case #30540

### ISSUE THREAD

**Issue by ksuuk** [grafana/grafana#32214]
Hi,

As I'm managing F5, and I didn't have access/rights to grafana server, I could not provide asked logs and because of that my previous issue #30540 was closed. Sorry about that. Now finally I got access to server, enabled debug and router logging and made tests and find the issue. Please check the attached full logs below.

**What happened:**
Since 7.2.2 > * upgrade Grafana is not accessible behind F5 loadbalancer.

**What you expected to happen:**
Grafana instance is fully accessible.

**How to reproduce it (as minimally and precisely as possible):**
We are using hundreds Grafana instances accessible behind F5 loadbalancer with the help of the APM (access policy manager) module, so user sees so called landing page where all Grafana instances are listed as buttons and F5 acts as proxy, for example if user clicks some site Grafana button, new page opens and it's URL is like:

https://grafana.domain.com/f5-w-68737470733a2f2f67726164616e612e6177732d65751d63656e7452616c2d112e70746563$$/

F5 presents URI in HEX, in decoded view it’s - f5-w-<HEX_equivalent_of_backend_FQDN>$$ so it's grafana-site2.internal.test:8080

This all worked fine with grafana-7.2.2 but it does not work with any newer version, seems that Grafana started to make some redirections, as in F5 connection log I can see:
grafana-site2.internal.test:8080f5-h- can not be resolved

Why Grafana tries to make such absolute path redirection? I did read changelog, but I didn’t find any general change, so what could be the reason for such behavior? Grafana config is same as before:

[server]
http_port = 8080
protocol = http
enable_gzip = true
domain = grafana-site2.internal.test
root_url = http://grafana-site2.internal.test:8080/
serve_from_sub_path = true
router_logging = true

[log]
level = debug

Test procedure - install, start, access from F5 grafana server > home > click to one dashboard > stop, collect logs.
Adding two log files, grafana_ok.log (made with v7.2.2) and grafana_nok.log (made with v7.4.5), from logs:

**OK (v7.2.2):**
[grafana_ok.log](https://github.com/grafana/grafana/files/6182153/grafana_ok.log)

t=2021-03-22T11:15:07+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/ status=200 remote_addr=192.168.10.20 time_ms=8 size=56172 referer="https://grafana.domain.com/vdesk/webtop.eui?webtop=/Common/webtop_full&webtop_type=webtop_full"
t=2021-03-22T11:15:08+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/dashboards/home status=200 remote_addr=192.168.10.20 time_ms=1 size=1258 referer=http://grafana-site2.internal.test:8080/

t=2021-03-22T11:15:17+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/dashboards/tags status=200 remote_addr=192.168.10.20 time_ms=1 size=543 referer="http://grafana-site2.internal.test:8080/?orgId=1"

**NOK (v7.4.5):**
[grafana_nok.log](https://github.com/grafana/grafana/files/6182156/grafana_nok.log)

t=2021-03-22T11:17:37+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/ status=200 remote_addr=192.168.10.20 time_ms=8 size=59072 referer="https://grafana.domain.com/vdesk/webtop.eui?webtop=/Common/webtop_full&webtop_type=webtop_full"
t=2021-03-22T11:17:38+0000 lvl=dbug msg="Not adding CSP header to response since it's disabled" logger=http.server
t=2021-03-22T11:17:38+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/dashboards/home status=200 remote_addr=192.168.10.20 time_ms=1 size=1258 referer=http://grafana-site2.internal.test:8080f5-h-/$$/

t=2021-03-22T11:17:39+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/api/search status=200 remote_addr=192.168.10.20 time_ms=2 size=2 referer="http://grafana-site2.internal.test:8080f5-h-/$$/?orgId=1"

So since v7.3.0 any newer grafana version messes up the URI from grafana-site2.internal.test:8080/ to grafana-site2.internal.test:8080f5-h-/$$/  and the connection is therefore broken.

What and why was changed? How to fix it?

**Comment by torkelo** [comment]
no other reports like it, not sure what has changed. Where is the 8080f5-h-/$$/  coming from? Can you show the raw network traffic between loadbalancer and grafana? what request adds this URI?

**Comment by ksuuk** [comment]
@torkelo 

I guess not many are using similar setup. Anyway, user accessing https://grafana.domain.com sees so called landing portal. F5 Portal access patches, or rewrites, links in web content, for example:
HTML patching - Rewrites links in HTML content to redirect to the Access Policy Manager®.
JavaScript patching - Rewrites link content in JavaScript code to redirect requests to the Access Policy Manager.
CSS patching - Rewrites links to CSS files, and within CSS content, to redirect to the Access Policy Manager.

On this landing portal all grafana instances are listed as buttons and F5 acts as proxy, and for example if user click to some site grafana button, new page opens (user newer sees the original destination URL of the end device) and URL what the client sees is like - https://grafana.domain.com/f5-w-68737470733a2f2f67726164616e612e6177732d65751d63656e7452616c2d112e70746563$$/

As F5 presents URI in HEX, in decoded view it’s - f5-w-$$ so on my case the destination URL is something like (adding it here for just to visualize the idea) - https://grafana.domain.com/f5-w-grafana-site2.internal.test:8080/$$/

AS F5 presents URI in HEX, in decoded view it’s - f5-w-<HEX_equivalent_of_backend_FQDN>$$ so it's  the HEX is <grafana-site2.internal.test:8080> and  the destination URL is something like (adding it here for just to visualize the process, this URI does not work in normal usage) - https://grafana.domain.com/f5-w-grafana-site2.internal.test:8080/$$/

So the 8080f5-h-/$$/ is result of the grafana -s interception/URI rewriting and grafana should not do it.

And like I said, this setup worked fine, but doesn't work since v7.3*. I didn't found nothing general in grafana changelog. The only related thing may be the short URL, which came since v7.3*.

**Comment by torkelo** [comment]
I think you will have to try to troubleshoot and find this yourself , unless this is very common issue. Or you have an example with curl that can replicate the problem with us having to setup F5

**Comment by ksuuk** [comment]
@torkelo 



As far I know, I can't replicate F5 APM query with curl.

For clarification - with v7.3 I can't even access the main page:

t=2021-03-23T08:35:47+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=GET path=/$$/ status=200 remote_addr=192.168.10.20 time_ms=6 size=56600 referer=http://grafana-site2.internal.test:8080f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-f5-h-/$$/

As with v7.4.5 I can access main page, but I can't access any dashboards, then already something was changed/fixed between v7.3 > v7.4 and that's whay I was hoping the some developer(s) know or can checks what from since v7.3 - https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-3-0/ causes this error.

But if the developer(s) can't tell which part of the code is causing the problem I pointed out, then this situation is very scary. 

I guess, that I can try to build v7.3 from the source (BTW, I could not find source code from https://grafana.com/grafana/download) and remove changes one by one, but this is very time consuming process.

**Comment by marefr** [comment]
@ksuuk I notice that you have `serve_from_sub_path = true` - why do you have that when your `root_url = http://grafana-site2.internal.test:8080/` doesn't contain a sub path? `serve_from_sub_path = true` should probably only be used in cases when you don't use a reverse proxy in front of Grafana

**Comment by ksuuk** [comment]
@marefr 

I tested with multiple options (also adding nginx between F5 and grafana) and at the moment serve_from_sub_path is removed from config.

**Comment by marefr** [comment]
@ksuuk 

> As with v7.4.5 I can access main page, but I can't access any dashboards

That's good at least. Then you should be able to progress from that. Based on your logs seems like you have some problem with provisioned dashboards - is that why there are no dashboard?
```
t=2021-03-22T11:17:16+0000 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=default path=/var/lib/grafana/dashboards
t=2021-03-22T11:17:16+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:8080 protocol=http subUrl= socket=
t=2021-03-22T11:17:16+0000 lvl=dbug msg="saving new dashboard" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/cim_site-activity.json folderId=0
t=2021-03-22T11:17:16+0000 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=0
t=2021-03-22T11:17:16+0000 lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=default error="Dashboard not found"
t=2021-03-22T11:17:17+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=17
t=2021-03-22T11:17:26+0000 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=default path=/var/lib/grafana/dashboards
t=2021-03-22T11:17:26+0000 lvl=dbug msg="saving new dashboard" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/cim_site-activity.json folderId=0
t=2021-03-22T11:17:26+0000 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=0
t=2021-03-22T11:17:26+0000 lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=default error="Dashboard not found"
t=2021-03-22T11:17:27+0000 lvl=dbug msg="Scheduling update" logger=alerting.scheduler ruleCount=17
t=2021-03-22T11:17:36+0000 lvl=dbug msg="Start walking disk" logger=provisioning.dashboard type=file name=default path=/var/lib/grafana/dashboards
t=2021-03-22T11:17:36+0000 lvl=dbug msg="saving new dashboard" logger=provisioning.dashboard type=file name=default provisioner=default file=/var/lib/grafana/dashboards/cim_site-activity.json folderId=0
t=2021-03-22T11:17:36+0000 lvl=dbug msg="Extracted alerts from dashboard" logger=alerting.extractor alertCount=0
t=2021-03-22T11:17:36+0000 lvl=eror msg="failed to save dashboard" logger=provisioning.dashboard type=file name=default error="Dashboard not found"
```

Given you can access the main page, take that URL and apply the path for one of your dashboards and paste in a new browser tab to force a full page reload. Please include the logs for these requests.

Still suggest what Torkel suggest, use a tool to capture the raw network traffic between loadbalancer and grafana to fully understand what's going on.

**Comment by marefr** [comment]
Complete changelog can be found here: https://github.com/grafana/grafana/blob/master/CHANGELOG.md#7310-2021-03-18

> then already something was changed/fixed between v7.3 > v7.4 and that's whay I was hoping that some developer(s) know or can check what from since v7.3 -

Sorry for being a bit confused. The original issue was about 7.3. Do you mean that there's now a fix in 7.4.x that you would like to understand what it is?

**Comment by ksuuk** [comment]
@marefr 

1) I noticed these dashboard errors in logs too, but like I said, I have no experience of grafana, I just got root access to one of our test grafana which content and dashboards. And all I did was just install different grafana versions with yum (Centos 8 server) and everythinw works fine with v7.2.2, but not with any newer version. But I'll try to capture and analyze traffic from both devices.

2) I opened first issue when grafana v7.2.2 was upgraded to v7.3.5 and then the server administrator downgraded grafana to 7.3.0-beta1 (first newer version after v7.2.2). Now we are using v7.4.5.

**Comment by ksuuk** [comment]
@torkelo @marefr 

Adding my findings (code as pictures, because this page messes it up ).

Error lines:
![errors_start](https://user-images.githubusercontent.com/26193002/112297786-f51d6d80-8c9e-11eb-8c07-5482e74d9a35.png)

F5 request > grafana (403):
![Screenshot 2021-03-24 at 12 55 02](https://user-images.githubusercontent.com/26193002/112299539-922cd600-8ca0-11eb-9001-e405e75d6b73.png)

**Last correct referer.**

grafana response > F5 (4087):
![Screenshot 2021-03-24 at 12 55 11](https://user-images.githubusercontent.com/26193002/112299607-9e189800-8ca0-11eb-8fa0-9a578c28bef2.png)

F5 request > grafana (438):
![Screenshot 2021-03-24 at 12 55 21](https://user-images.githubusercontent.com/26193002/112299668-ac66b400-8ca0-11eb-8fd7-94c763d525a1.png)

**And since now referer is messed up.**

The v7.2.2 reqests are much more shorter and cleaner. Why in newer versions are used such long paths like app:*, angular, moment, runtime etc? I guess that dot and tilde in the path are probably causing the issue:
![Screenshot 2021-03-24 at 12 55 31](https://user-images.githubusercontent.com/26193002/112299695-b5f01c00-8ca0-11eb-95d3-63ac3304177a.png)

Also RFC 3986 says:

For consistency, percent-encoded octets in the ranges of ALPHA (%41-%5A and %61-%7A), DIGIT (%30-%39), hyphen (%2D), period (%2E), underscore (%5F), or tilde (%7E) should not be created by URI producers and, when found in a URI, should be decoded to their corresponding unreserved characters by URI normalizers.
   
Adding screenshots. Please advise? 

v7.4.5:
![v7 4 5_nok](https://user-images.githubusercontent.com/26193002/112298203-6fe68880-8c9f-11eb-9740-38a31eda4599.png)

v7.2.2:
![v7 2 2_ok](https://user-images.githubusercontent.com/26193002/112298258-7c6ae100-8c9f-11eb-81b7-421e6736c41c.png)

**Comment by marefr** [comment]
I'm closing this since we unfortunately cannot help you and would ask you to troubleshoot this yourself. You might try asking for help on our [community site](https://community.grafana.com/). 

One thing you potentially could try if upgrading to 7.4.x is to use the new [CDN functionality](https://grafana.com/docs/grafana/latest/administration/configuration/#cdn_url) that allows you to host/serve all static resources on for example a separate sub domain.

**Comment by JavierCCC** [comment]
Hi, we are currently facing this same issue, we are using Grafana 9 Enterprise behind an nginx reverse proxy (all docker containers). No problems using this Grafana from our WAN network. Same described issue related to the additional subpath being added to urls when using Grafana from the F5 link. We have tons of web applications working with no issue behind F5.
