### ISSUE TITLE
[FeatureRequest] Add option for hidden dashboards

### ISSUE THREAD

**Issue by poodad** [grafana/grafana#32216]
It would be nice to have an option that hides dashboards from non admin users. I have a few dashboards that are called as links (with variables) from other dashboards. If navigated to directly, these dashboards are useless.

I also have dashboards that are meant only to be part of a playlist.

It would be nice if there were an option to hide a dashboard from non admin users. It could be an explicit checkbox in the dashboard's settings, or a dashboard that starts with a magic character (maybe '.' like unix hidden files), or even a folder that is not visible to non admin users.

**Comment by zoltanbedi** [comment]
You can remove all the permissions from a dashboard and then it will be available only for admins https://grafana.com/docs/grafana/latest/permissions/dashboard-folder-permissions/#grant-dashboard-permissions
Is this solves your problem?

**Comment by poodad** [comment]
No, I want it to be available to everyone, just not visible in the dashboard navigation.

**Comment by conorevans** [comment]
I would be willing to have a crack at this @zoltanbedi - would that be welcomed?

**Comment by zoltanbedi** [comment]
Hi @conorevans thanks for the consideration but first let @grafana/grafana-frontend-platform team decide if this feature is something they want to have or not.
If you would like to contribute, try to look for [issues with help wanted label](https://github.com/grafana/grafana/issues?q=is%3Aopen+is%3Aissue+label%3A%22help+wanted%22).

**Comment by hugohaggmark** [comment]
Hi @poodad and thank you for suggesting this. This seems like a very narrow use case, so we'll keep it open for a while and see if receives any more upvotes/feedback.

**Comment by poodad** [comment]
I don't think it is that narrow. Lots of people use playlists and may want
to use dashboards in the playlist that wouldn't ordinarily be used on their
own.

Likewise, lots of people have panels with links to dashboards that pass a
required variable. If the dashboard is navigated to directly, it just shows
the end user lots of "no data" panels which is confusing.

**Comment by hugohaggmark** [comment]
@poodad sure and as I said, we're awaiting more feedback from the community before taking any next steps.

**Comment by jake-bierman** [comment]
Hi, I got pointed to this thread by the grafana support team as they suggested to add our use case here.
This is something we would be interested in as well. 
We have dynamically linked dashboards that will be useless when opened without the correct variables, thus would be nice if we can hide them. We tried removing access but of course then the links wont work. 
Ideally we only want one dash board visible to the user as all the rest are accessed via links and currently when the user access the folder or explore dashboards via the manage tab, they can see many dashboards which would be useless if opened that way.

Thanks Jake

**Comment by anavss** [comment]
Hi @poodad and @jake-bierman 👋🏼 one of our product designers is investigating design improvements to dashboard folder management and navigation in Grafana. I spotted your feature request and wondered if you would be interested in speaking to her? You can [book 20-30min with her here](https://ethn.io/38442).

**Comment by jake-bierman** [comment]
Hi @anavss , I would be happy to speak to her but seems with the time zones I won't be able to schedule a meeting. I would also be happy to communicate via email if interested

**Comment by anavss** [comment]
Hi @jake-bierman, thanks for your interest. Please [send me an email](mailto:ana.vanschalkwyk@grafana.com) and I'll get in touch.
