### ISSUE TITLE
[Feat Req]- Duplicate Overrides + case In-sensitive metric/tag search

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#32228]
(nb: im mainly referencing graphite as datasource in below,  but also influxDB) grafana version = 7.4.3

**[Feature Request] 1: Case insensitive "search as you type" for metrics / tags:**
(some parts of the grafana GUI already feature **Case in-sensitive** "search as you type" ,  such as the Overrides tab -> "+Add override property" (if you start typing "line",  the pop-under *WILL* show "Line" as a match).  
(Prehaps this is more of a graphite limitation,  if so-  maybe grafana could query->graphite both upper and lower case chars for only the first few characters as a user types?)

This would really help speed up metric entries / edits.
example screen gif (v7.4.3):

![outputGIF2](https://user-images.githubusercontent.com/60830628/112030570-6676e800-8b08-11eb-8310-5f0d4b842d01.gif)

**[Feature Request] 2: a Duplicate (button) for "Overrides" entries:**
There are many times we have to create  Overrides entries using regex, which are only different in 1 or 2 elements (ie the regex is slightly different, and/or a different color)  Having the ability to duplicate or clone an existing Override entry would be very helpful.  Currently to make a 2nd Override (very similar to the 1st override), it will take several actions / clicks,  this could be reduced greatly via a clone option.
here is where im referring to (ie have a duplicate/clone button next to the trash icon):
![image](https://user-images.githubusercontent.com/60830628/112031481-64f9ef80-8b09-11eb-92c3-fa9f3f3923c4.png)

(im happy to see more elements moved over to the Override function,  ie as of recnet grafana releases, most of the "Panel -> Series Override" elements have been condensed/move to the "Override" tab -  this is GREAT! )

(i REALLY love the amazing speed and progress of grafana updates + new features) Thank you grafana team!
**LOVE GRAFANA!**

**Comment by zoltanbedi** [comment]
Hi @bob454522,
Thanks for the nice words. Can you please split your feature request into 2 separate issues?

**Comment by bob454522** [comment]
> Hi @bob454522,
> Thanks for the nice words. Can you please split your feature request into 2 separate issues?

I should have went with my gut and made 2x entries from the start-  thanks for letting me know.
**Ive created 2x new posts, and am closing out this one:**
https://github.com/grafana/grafana/issues/32271
https://github.com/grafana/grafana/issues/32270
