### ISSUE TITLE
graph with multiple queries won't stack

### ISSUE THREAD

**Issue by justajeffy** [grafana/grafana#3222]
2 queries in graph, both from same elasticsearch data source.

correct, show, other  - come from query 1
out_show, out_other - come from query 2

You can see here that the values aren't stacking.

![nostack](https://cloud.githubusercontent.com/assets/11652559/11121219/8d1a318a-8922-11e5-909d-4341b7b0c0bb.png)

**Comment by justajeffy** [comment]
to clarify... the values from query 2 don't stack on the values from query 1

each query stacks individually, which is undesirable.

**Comment by torkelo** [comment]
is stack enabled in display options?, and what is your group by time interval?

**Comment by justajeffy** [comment]
stack is enable in display options and group by time is blank

**Comment by torkelo** [comment]
blank? you mean auto?

**Comment by justajeffy** [comment]
if not entering data into that field means auto, then yep.

**Comment by torkelo** [comment]
Does it say "Interval: auto"  in the group by date histogram?

**Comment by justajeffy** [comment]
Ahh.  Yes, both queries say Interval: auto

**Comment by torkelo** [comment]
could be the min_doc_count: 1,   try editing the query in json mode (switch editor mode using the hamburger menu in the right of each query), change min_doc_count from 1 to 0,  do that for both queriues, then make sure "null point mode" in display options is set to null as zero

**Comment by justajeffy** [comment]
min_doc_count isn't in the json.  Not sure where to add it.

**Comment by torkelo** [comment]
sure it is, its in close to date_histogram , I am talking about the query editor json, not the panel json editor, 

Pushing out a new build of 2.6.0-pre1 with a change to elasticsearch to set min_doc_count to 0, should appear on this page in about 2min, http://grafana.org/download/builds.html

**Comment by justajeffy** [comment]
I see.  Very good, thanks.  That seems to help.  Looks like it also might fix my issue #3210
