### ISSUE TITLE
Investigate ability to define API schema in CUE

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#32239]
Investigate whether it's possible to define a schema for our API in CUE.

- [x] Prototype [Smithy](https://awslabs.github.io/smithy/) as Web API interface definition framework => #32901
- [ ] Consider CUE as IDL frontend to Smithy

Status quo is we have a [PR](https://github.com/grafana/grafana/pull/32901) prototyping defining of API schema in Smithy, which can at this stage generate API client Go code and OpenAPI.

**Comment by sdboyer** [comment]
Closing this. It's clear that it's possible for us to define the schema of our API objects in CUE; the more pressing question now is what we actually want that API to be shaped like.
