### ISSUE TITLE
Explorer: When showing context for a line with Loki, the Dedup radio button keeps on showing.

### ISSUE THREAD

**Issue by nvanheuverzwijn** [grafana/grafana#32235]
![image](https://user-images.githubusercontent.com/943226/112045497-4d2e6580-8b21-11eb-9418-6be0db28c707.png)

**What happened**:
When showing context with Loki, the Dedup radio button are still shown over the context
**What you expected to happen**:
Show contxt should overlay everything.
**How to reproduce it (as minimally and precisely as possible)**:
Make a simple query in loki and press show context on a line
**Anything else we need to know?**:
nope
**Environment**:
- Grafana version: v7.4.2 (29e75ad97b)
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: none
- Others:

**Comment by zoltanbedi** [comment]
fixed in https://github.com/grafana/grafana/pull/30939
