### ISSUE TITLE
azuread auth - manual org assignements overwritten at every log in

### ISSUE THREAD

**Issue by nathanpegram** [grafana/grafana#32237]
**What happened**:
Any org assignments done through Grafana are overwritten each time an azuread user logs in. They are set back to have only org 1 viewer access.

**What you expected to happen**:
Manual org assignments preserved.

**How to reproduce it (as minimally and precisely as possible)**:
Log in via azure ad, manually set orgs, log out, log back in, org settings gone.

**Environment**: 
- Grafana version: 7.4.3
- OS Grafana is installed on: Ubuntu Bionic

**Comment by zoltanbedi** [comment]
duplicate of #22605
