### ISSUE TITLE
Table format in instant mode is what we need to get work for CSV export

### ISSUE THREAD

**Issue by saipavankumarreddy** [grafana/grafana#32238]
What happened:  After adding dashboard, I am trying to Download  the metrics by using Download CSV option. But I am getting only one metric value in CSV instead of all the metrics. 

What you expected to happen: I am expecting to get all the metrics and its values in CSV file. 

How to reproduce it (as minimally and precisely as possible):

1. Install grafana 7.1.3 using helm chart or rpm
2. Add any dashboard with query which gives multiple metrics and select Table as format and enable prometheus instant mode as shown in the below screenshot.

![image](https://user-images.githubusercontent.com/24735153/112102255-fe8ad500-8bcd-11eb-9b93-56dc1f51dc0d.png)

3. In the above screenshot we can see only see one  random metric name and value is showing instead of all metric names. 
4. For downloading metrics in CSV file click on Query Inspect --> Select Data --> Download csv.  
5. In the downloaded CSV file I am able to see only one metric.  I am expect to see all the metric values in that csv. Please find the screenshot  CSV file data. 
![image](https://user-images.githubusercontent.com/24735153/112102592-81139480-8bce-11eb-965d-953769b9b080.png)

Expected: I am expecting to see all the metrics and corresponding values in CSV file. 
Note: I preferred to Format is Table only while exporting the CSV file. 

Anything else we need to know?:

Environment:

Grafana version: 7.1.3
Data source type & version:
OS Grafana is installed on:
User OS & Browser: n/a
Grafana plugins:
Others: n/a

**Comment by zoltanbedi** [comment]
Can you try to update your Grafana? I was not able to reproduce your issue in the latest release.

**Comment by saipavankumarreddy** [comment]
@zoltanbedi Can you please share the Grafana version from which you have tried?

**Comment by zoltanbedi** [comment]
sure. it was 7.5.0-beta2
