### ISSUE TITLE
Show the origin dashboard of an alert in the alerting rules page

### ISSUE THREAD

**Issue by TagadaPoe** [grafana/grafana#32246]
**What would you like to be added**:

In the alert rules overview (/alerting/list) I'd like to see in which dashboard the alert is defined, without having to click on the alert rule. I would like to be able sort and/or filter by dashboard, too.

**Why is this needed**:

It would be easier to handle a huge number of alerting rules.

**Comment by torkelo** [comment]
Alert rules will soon be separate from dashboards (create them standalone), so this will not make that much sense
