### ISSUE TITLE
OIDC: Add ID4me auth

### ISSUE THREAD

**Issue by bschoenbach** [grafana/grafana#32254]
**What would you like to be added**:
Support ID4me as OIDC authentication provider.
Further details regarding ID4me protocol see 
https://id4me.org/login-partner-developer-zone/

**Why is this needed**:
Generic OAuth can be configured to work with ID4me approach but it bypasses the concepts idea completely (DNS lookup and OIDC discovery).

See also pre-existing discussions on
https://community.grafana.com/t/additional-id4me-single-sign-on-login-integration-within-grafana/44708

**Comment by bschoenbach** [comment]
@zoltanbedi How I can I create a feature branch for this on the repo. Currently I am working on a branch in my local repo.

**Comment by zoltanbedi** [comment]
@bschoenbach You should work on your own fork and when you are ready you can open a pull request in our repository. See [this guide](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request-from-a-fork) how you can do that

**Comment by bschoenbach** [comment]
@zoltanbedi thx ....done

**Comment by wbrowne** [comment]
Feel free to open a pull request with your changes against the Grafana master branch @bschoenbach
