### ISSUE TITLE
Can't connect to data sources when passwords contain ';'

### ISSUE THREAD

**Issue by kchristensen** [grafana/grafana#3225]
When trying to add an InfluxDB 0.9.x data source in Grafana 2.5.0, if the InfluxDB user password contains a ';', authentication will fail.

This is testable by running `set password for admin = 'foo;bar'` then trying to add an InfluxDB server via Grafana.

**Comment by torkelo** [comment]
are you using direct or proxy access method?

**Comment by kchristensen** [comment]
I'm using the direct access method. InfluxDB is 0.9.4.2, with Nginx doing SSL termination in front of it. I get "authentication failure" errors when I click "Test connection" in Grafana, but if I change my password to something that doesn't contain a semicolon, it works as expected.

The Nginx config is basic, it's literally just a `proxy_pass` to influxdb:8086.

**Comment by torkelo** [comment]
think this is fixed in Grafana 3.0
