### ISSUE TITLE
Mapping Values seems to not working properly

### ISSUE THREAD

**Issue by sevenval-admins** [grafana/grafana#32253]
**What happened**:
Mapping Value 0 to _ok_ doesn´t work, the Panel shows just the metric result value:
![grafana_dash](https://user-images.githubusercontent.com/13047464/112143971-e076a200-8bd8-11eb-9bb9-4aa1d90906f0.png)

**What you expected to happen**:
The Panel should show the parameter assigned to the value

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Visualisation type: Polystat  

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: Prometheus
- OS Grafana is installed on: Run in Docker
- User OS & Browser: MacOS Catalina - Chrome, Firefox, Brave Browser
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
I think the issue is in the plugin see https://github.com/grafana/grafana-polystat-panel/issues/182
