### ISSUE TITLE
Collapse row by clicking a title

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#3226]
Hi, Torkel! In previos Grafana version I could collapse row by clicking row title. Now this feature don't work. Is this bug or feature? It was helpful.

**Comment by utkarshcmu** [comment]
https://github.com/grafana/grafana/issues/3082

This issue can be closed now. :)

**Comment by alexanderzobnin** [comment]
Thanks!

**Comment by torkelo** [comment]
if you want the fix use the 2.6.0-pre release builds, http://grafana.org/download/builds.html

2.6 should be released soon (1-2 weeks), will come with the new table panel :)

**Comment by alexanderzobnin** [comment]
Great!
