### ISSUE TITLE
[Feat Req]- Case In-Sensitive metric/tag search

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#32270]
(nb: im mainly referencing graphite as datasource in below, but also influxDB) grafana version = 7.4.3

**[Feature Request]: Case insensitive "search as you type" for metrics / tags:**
Some parts of the grafana GUI already feature Case in-sensitive "search as you type" , such as the Overrides tab -> "+Add override property" 
If you start typing "line", the pop-under WILL show "Line" as a match.
(Perhaps this is more of a graphite limitation, if so- maybe grafana could query->graphite both upper and lower case chars for only the first few characters as a user types?)

This would really help speed up metric entries / edits.
example screen gif (v7.4.3):

![image](https://user-images.githubusercontent.com/60830628/112219132-9ac6d300-8bf2-11eb-9ac2-c3cdbdfe4adc.png)

(i REALLY love the amazing speed and progress of grafana updates + new features) Thank you grafana team!
LOVE GRAFANA!

**Comment by aocenas** [comment]
We will have to check if the Graphite API allows it, if not it could be a bit problematic.

**Comment by ifrost** [comment]
> (...) Perhaps this is more of a graphite limitation, if so- maybe grafana could query->graphite both upper and lower case chars for only the first few characters as a user types? (...)

Yes, you're right. The query editor relies on `metric/find` Graphite API method which according to [docs](https://graphite-api.readthedocs.io/en/latest/api.html) is case-sensitive.

Unfortunately, querying for both upper and lower case chars would be problematic as in practice it would require requesting every permutation of lower/upper case, e.g. to cover `testmetric.count`, `TestMetric.count` and `TESTMETRIC.count`.

Please bear in mind that Graphite metric names are case-sensitive, meaning`testmetric.count`, `TestMetric.count` and `TESTMETRIC.count` would be treated as 3 separate metrics. Defining metrics with a mix of lower/upper case letters may be prone to typing errors.

<img width="1724" alt="Screenshot 2021-03-25 at 10 27 23" src="https://user-images.githubusercontent.com/745532/112467266-219cbc80-8d67-11eb-95f4-74a28616d1d1.png">
