### ISSUE TITLE
Units: Add siemens (S) as a unit of measure for conductance

### ISSUE THREAD

**Issue by ryanshow** [grafana/grafana#32275]
**What would you like to be added**:

Please add the siemens (symbol "S") unit of measure for conductance (derived SI unit, reciprocal of resistance).

**Why is this needed**:

I'm monitoring a piece of industrial equipment that reports the conductance of a material that it evaluates. I could convert this value to resistance and report the metric in Ohms, but the people who have historically monitored it would be confused by the numbers suddenly being inverted. It would be nice to display it in it's native format.

**Comment by ryantxu** [comment]
FYI you can type any value into the unit picker and it will get used as a suffix.  For si units type "si:whatever"
![image](https://user-images.githubusercontent.com/705951/112272373-5a3e7800-8c39-11eb-886b-4a1d16dff9f4.png)

the list of custom units is pretty extreme... so we are only adding the most standard ones ;)

**Comment by RichiH** [comment]
Stumbled across this while looking for ohm and opened https://github.com/grafana/grafana/issues/36238 as a more generic one.

**Comment by RichiH** [comment]
(turns out the UX confused me, ohm was there already)
