### ISSUE TITLE
[Feat Req]- Duplicate/Clone Overrides

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#32271]
(nb: im mainly referencing graphite as datasource in below, but also influxDB) grafana version = 7.4.3

**[Feature Request]: a Duplicate (button) for "Overrides" entries:**
There are many times we have to create Override entries using regex, which are only different in 1 or 2 elements (ie the regex is slightly different, and/or a different color) 
**Having the ability to duplicate or clone an existing Override entry would be very helpful.** 
Currently to make a 2nd Override (very similar to the 1st override), it will take several actions / clicks, this could be reduced greatly via a clone option.
here is where im referring to (ie have a duplicate/clone button next to the trash icon):

![image](https://user-images.githubusercontent.com/60830628/112219420-f1cca800-8bf2-11eb-8741-7b4f17fec4c2.png)

(im happy to see more elements moved over to the Override function, ie as of recnet grafana releases, most of the "Panel -> Series Override" elements have been condensed/move to the "Override" tab - this is GREAT! )

(i REALLY love the amazing speed and progress of grafana updates + new features) Thank you grafana team!
**LOVE GRAFANA!**

**Comment by zoltanbedi** [comment]
We actually have a feature request like this so I'm going to close this one. See https://github.com/grafana/grafana/issues/27305
