### ISSUE TITLE
Dashboard: import dashboard not working

### ISSUE THREAD

**Issue by Clarity-89** [grafana/grafana#32296]
**What happened**:
When importing dashboard, api returns an error `error: "handler not found", message: "Failed to save dashboard"`. 

**How to reproduce it (as minimally and precisely as possible)**:
1. Go to `dashboard/import`
2. Select dashboard json file or paste json in the field
3. Press `Load`
4. Press `Import`

**Environment**:
- Grafana version: latest master
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@aknuds1 could it be due to the plugins package refactoring? The message feels like it's a bus message without a handler configured

**Comment by marefr** [comment]
Yeah probably. Think we had similar problems last week

**Comment by marefr** [comment]
Verified this is not a problem on v7.5.x branch
