### ISSUE TITLE
Postgres : 'All' value is displayed in repeat mode

### ISSUE THREAD

**Issue by pbrissaud** [grafana/grafana#32292]
**What happened**: I enable repeating for a variable set to 'All' in a single stat panel. I see **n** panel (n values in in my variable) + a panel with the value of 'All'. 

**What you expected to happen**: I expect to not see the panel with the 'All' value  

**How to reproduce it (as minimally and precisely as possible)**:
* Create a Postres datasource
* Create a variable with All options enabled
* Create a single panel with repeat  on this variable
* Save & reload dashboard

**Anything else we need to know?**: 

I add a value to 'All' option to showcase the issue

![Capture d’écran de 2021-03-24 14-57-45](https://user-images.githubusercontent.com/27202456/112325054-a6c69980-8cb3-11eb-9763-8cbe7a15a034.png)

![Capture d’écran de 2021-03-24 14-57-20](https://user-images.githubusercontent.com/27202456/112325038-a3cba900-8cb3-11eb-9e41-ec4b71356655.png)

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Postgres 11
- OS Grafana is installed on: Bitnami Docker Image 7.1.5-debian-10-r21 
- User OS & Browser: SLES 15 SP2 / Firefox 68.8

**Comment by zoltanbedi** [comment]
I was not able to reproduce this in Grafana 7.5.0.
Can you try to upgrade your Grafana?

**Comment by pbrissaud** [comment]
Thanks for your answer. Unfortunately, I work in an air gapped environment and I should wait security check before upgrading Docker image. However, I believe that the next release is close so it won't be long to wait. I will keep you in touch if the bug is still present.

**Comment by pbrissaud** [comment]
I restarted the Kubernetes cluster and my PC and it works ... Odd
