### ISSUE TITLE
[Feature Request] Improve performance logging by adding extra information and always the same unit in response time

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#3229]
Related to https://github.com/grafana/grafana/issues/2902

When trying to study grafana performance now we have response time in the logs , but logs looks like that:

```
2015/10/28 17:00:42 [I] Completed /render 200 OK in 1.009688339s
2015/10/28 17:00:42 [I] Completed /render 200 OK in 1.681680079s
2015/10/28 17:00:43 [I] Completed /render 200 OK in 1.875913175s
2015/10/28 17:00:43 [I] Completed /render 200 OK in 1.937721866s
2015/10/28 17:00:43 [I] Completed /render 200 OK in 2.316984552s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 1.299809255s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 1.285863763s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 2.346413804s
2015/10/28 17:00:44 [I] Completed /render 200 OK in 1.951850024s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.686839802s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.014659941s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.080559295s
2015/10/28 17:00:45 [I] Completed /render 200 OK in 1.238959337s
```

This log doesn't have enough information to do a good performance analysis 

1)  would be important if some extra data could be reported in order to identify exactly  the slow request , something like:
- **user** who is doing the request
- **org** which user belongs to 
- **dashboard** that is doing the request
- **panelid** which renders the returned data.
- **datasource** from which we are sending the request.
- **target/query**  detailed on the request.

2) would be also important if the log can report time always in the same unit ( ms by example or microseconds as apache does) in this way users can automate the  log parsing and send to the metrics backend.

Lots of thanks!

**Comment by szibis** [comment]
+1

**Comment by torkelo** [comment]
this this was fixed in v4
