### ISSUE TITLE
Grafana does not create a telegram notification channel

### ISSUE THREAD

**Issue by Makkinwa** [grafana/grafana#32297]
**What happened**:
So basically I wanted to put my telegram notification channel in my local grafana image using following notifiers.yaml file:

---------------
notifiers:
  - name: telegram
    type: telegram
    uid: telegram
    is_default: true
    settings:
      bottoken: "MY_TOKEN"
      chatid: "MY CHAT ID"
---------------

I put this file in /etc/grafana/provisioning/notifiers/notifiers.yaml but when I look into grafana I don't see my telegram channel

**What you expected to happen**:
I expected to have my telegram notification channel in grafana after restarting pod in k8s because in case of pod failure grafana pod recreates with no alert channels and therefore alerting system does not work
**How to reproduce it (as minimally and precisely as possible)**:
Use my notifiers.yaml file

**Environment**:
- Grafana version: 7.4.3
- OS Grafana is installed on: Linux
- Others:

**Comment by zoltanbedi** [comment]
I was not able to reproduce this in 7.5.0.
I've put the notifiers.yml with the config above to the provisioning folder and after restarting Grafana I can see this telegram notifier in the notification channels. Can you try to upgrade your Grafana?
