### ISSUE TITLE
adhoc variable/filter doesn't show my Prometheus datasource

### ISSUE THREAD

**Issue by jdx-john** [grafana/grafana#32309]
I have a running, valid Prometheus datasource being used by panels and query-variables in Grafana (both are current versions).
I am struggling to understand how to use adhoc variables as a filter, or to even get it set up:

![image](https://user-images.githubusercontent.com/1654627/112462198-b21fd080-8d58-11eb-87ac-0ae3e3290dd5.png)

I expect my prometheus datasource to be listed but only Grafana and some empty line are shown. And then, there is nowhere to actually enter a query/expression anyway (though this might be because no valid datasource is selected).

Is this a bug or user-error?

**Comment by zoltanbedi** [comment]
Hi @jdx-john, 
In which version of Grafana do you see this?

**Comment by jdx-john** [comment]
@zoltanbedi as I said current from a few weeks ago:
- Grafana 7.4..3
- Prometheus 2.25

All my dashboards look great, here's the datasource:

![image](https://user-images.githubusercontent.com/1654627/112624284-54a58580-8e25-11eb-9c47-0728a107d5ed.png)

![image](https://user-images.githubusercontent.com/1654627/112624354-71da5400-8e25-11eb-8da2-05131800cf58.png)

**Comment by zoltanbedi** [comment]
Ahh yes sorry I missed that they are current. I was not able to reproduce it in 7.5.0. Can you try to upgrade your Grafana?
Also when you are on the variable setting page do you see any error in the console?

**Comment by jdx-john** [comment]
Can you explain what you mean by the console, I'm not familiar?
Regarding upgrading, are there any changes which could be relevant - if I have a running system what is the right way to update... I'm on Windows so do I just install on top or are there additional steps? 

I checked some other variable types:
![image](https://user-images.githubusercontent.com/1654627/112638334-0d27f500-8e37-11eb-842a-2bed83601b95.png)

![image](https://user-images.githubusercontent.com/1654627/112638381-1a44e400-8e37-11eb-86d1-e7270fb6bde0.png)

**Comment by zoltanbedi** [comment]
So the blank option you see there is by design. And I can see in the last image you sent that the Prometheus data source is there. So what is the problem exactly?

**Comment by jdx-john** [comment]
Well how does it work? There's nowhere to type in a filter expression and the documentation doesn't explain how I'm supposed to use it. I can't find an example anywhere!

Each of my images is of a _different_ variable type. Prometheus is shown for Query/Datasource types, but not for Adhoc:
![image](https://user-images.githubusercontent.com/1654627/112644210-1025e400-8e3d-11eb-8a35-69917e30e32b.png)

I would love to see an example what a working Prometheus adhoc variable might look like. I basically want to add the filter `{mylabel='something'}` and I cannot see how to, or if there is a bug.

**Comment by zoltanbedi** [comment]
Oh I see what is going on here. So this is only happening with the ad hoc filters variable. And I think this is a bug. This is only happening for a data source that is set to default.

**Comment by mikhailredis** [comment]
@zoltanbedi Could you please take a look at https://github.com/grafana/grafana/issues/32868. It should be fixed for Query as well.
