### ISSUE TITLE
Connecting Grafana to InfluxDB

### ISSUE THREAD

**Issue by adeel26** [grafana/grafana#3231]
Hi All,

I keep getting this error 

{"error":"error parsing query: time dimension must have one duration argument"}

SELECT+mean("value")+AS+"value"+FROM+"temperature"+WHERE+"internal"+GROUP+BY+time(internal)+fill(previous)%0A

Am a beginner so excuse my naivety, the table i am querying is below which is straight from getting started guide of influxdb v.09. and version for is Grafana version: 2.5.0  

temperature,machine=unit42,type=assembly external=25,internal=37

**Comment by torkelo** [comment]
group by time (internal),   that does not look right. Can you change that to `auto`  (the group by time argument) 

![image](https://cloud.githubusercontent.com/assets/10999/11144121/986bc75a-89fa-11e5-9f33-642521674549.png)

**Comment by adeel26** [comment]
thanks for assistance, 

for instance if i want to display internal temperature values 
temperature,machine=unit42,type=assembly external=25,internal=37

how could i structure From and where query ?

**Comment by torkelo** [comment]
select those tags and values in in the where clause

**Comment by adeel26** [comment]
![screen shot 2015-11-13 at 12 21 10](https://cloud.githubusercontent.com/assets/4057322/11145866/1aa6a8b0-8a01-11e5-88b3-2239d6a73129.png)

I did that but no values are shown on grafana

**Comment by torkelo** [comment]
it looks like your query is disabled (the gray color says that, did you click on the eye icon? the eye icon hides/disables the query )

**Comment by mukundparmar** [comment]
I wanna to tell you my story.
I was having same error that error  "{"error":"error parsing query: time dimension must have one duration argument"}". 
I installed grafana version 4.xxx error go back to grafana version 3.xxx some of them worked but not all. Now I go back to 2.xxx it worked so try it.
