### ISSUE TITLE
AzureMonitor: Refactor data links and move to backend

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#32322]
In the Azure Monitor data source plugin, for Metrics and Logs queries, data links are added to the dataframes on the _frontend_ (see [processResponse](https://github.com/grafana/grafana/blob/d71c5f4c4d1f634097c3e55289f0ef5f4ae07c2b/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts/#L102-L131)), which is suboptimal. We should move these into the data source backend, like  [Azure Resource Graph](https://github.com/grafana/grafana/blob/d71c5f4c4d1f634097c3e55289f0ef5f4ae07c2b/pkg/tsdb/azuremonitor/azure-resource-graph-datasource.go/#L199-L212).

This should happen for both Metrics and Logs queries, but as mentioned in https://github.com/grafana/grafana/issues/36242#issuecomment-914273449, we may need to change the URL format for Logs.

 - [x] Metrics
 - [ ] Logs - link construction is async to fetch additional details, which may change once resource-centric queries are introduced

**Comment by iwysiu** [comment]
We're not moving the logs data links at this time, because the existing ones don't work and there's no sense in moving non-working code. They don't currently work because we don't have access to the way that log data links are constructed.

**Comment by vickyyyyyyy** [comment]
closing this in favour of https://github.com/grafana/grafana/issues/36242
