### ISSUE TITLE
Panel Edit: Switching data sources of same type results in wrong querying and wrong data source selector input

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#32320]
**What happened**:
In Panel Edit mode, when switching between data sources of the same type, the name in data source selector/input doesn't change. Also it sometimes queries the old data source and sometimes the new one. Also autocomplete is sometimes off. 

I have also tested this in Explore and there is no problem in Explore. 

**How to reproduce it (as minimally and precisely as possible)**:

Data source in input doesn't change when switching the same type of data source:
https://user-images.githubusercontent.com/30407135/112505049-b0700000-8d8c-11eb-850c-8ced071e70e4.mov

When switched to second data source, it firstly queries correctly `#2` (see url) datasource and then it queries `#36`:
https://user-images.githubusercontent.com/30407135/112507020-97684e80-8d8e-11eb-88ff-b0fde72f451b.mov
**Environment**:
- Grafana version: Grafana v7.5.0-pre (093e5947f4)

**IMPORTANT:** There is no problem in released Grafana 7.5.0, just master.

**Comment by torkelo** [comment]
Fixed by https://github.com/grafana/grafana/pull/32386
