### ISSUE TITLE
Transforms: Outer join issue with duplicate field names not getting the same unique field names as before

### ISSUE THREAD

**Issue by EderRoger** [grafana/grafana#32324]
**What happened**:

We use to have the Transform Outer join working in version 7.3.2, but we decide to migrate to the latest 7.5.0 and we are facing some issues in the Transform outer join fields

**What you expected to happen**:

We expected the fields with the same name to be joined.

**How to reproduce it (as minimally and precisely as possible)**:

In our case, we have two midex datasources(A, B) query and in the outer join  the same name field was named with a "B" regarding the data source "B"

![image](https://user-images.githubusercontent.com/966834/112516184-c7efbe80-8d75-11eb-9ea0-79dc8e5f3e60.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.0
- Data source type & version: 
- OS Grafana is installed on: Linux
- User OS & Browser: Mac OS/Chrome
- Grafana plugins: piechart
- Others:

**Comment by leeoniya** [comment]
probably regressed by https://github.com/grafana/grafana/pull/31121, cc @torkelo

**Comment by EderRoger** [comment]
Thanks, @leeoniya for your reply. I will wait for more updates on this because looks like the issue should be resolved [here]( #31121 ) right?

**Comment by torkelo** [comment]
Can you show data before and after transform?

**Comment by EderRoger** [comment]
Sure. I will show the working version.

Before the transform:

<img width="640" alt="Screen Shot 2021-03-26 at 09 23 14" src="https://user-images.githubusercontent.com/966834/112630953-1011ee00-8e15-11eb-81fc-94bf8eea89ac.png">

After the Transform OuterJoin

<img width="646" alt="Screen Shot 2021-03-26 at 09 23 41" src="https://user-images.githubusercontent.com/966834/112631015-1f913700-8e15-11eb-848c-1cfdac0371db.png">

Our outer join is by name:

![image](https://user-images.githubusercontent.com/966834/112631153-49e2f480-8e15-11eb-9e5f-dda6cc198d85.png)


for the non-working version, you can consider the same data with the transform outer join not grouping properly the two 
Datasource fields. as I showed before

We are using mixed Datasources:

A: Azure Monitor
B: JSON API getting data from our services

<img width="1361" alt="Screen Shot 2021-03-26 at 09 33 33" src="https://user-images.githubusercontent.com/966834/112632311-b6aabe80-8e16-11eb-83fe-eb2f07e2dcca.png">


Thanks in advance

**Comment by EderRoger** [comment]
Hi @torkelo  , do you have any updates on this? 

Thanks in advance

**Comment by EderRoger** [comment]
Hi guys, any updates on this? @leeoniya @torkelo

**Comment by andrewkosykhin** [comment]
Hello everyone,

I subscribe to the question.

Since at version 7.3.10 it still worked: merging several rows by one identical column, but after 7.4.1 everything is broken ((
I found the following commit: https://github.com/grafana/grafana/pull/31121, I think broke it, please rollback / fix

See also:
https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-4-1/
> Transforms: Fixes Outer join issue with duplicate field names not getting the same unique field names as before. #31121, @torkelo
