### ISSUE TITLE
Tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request

### ISSUE THREAD

**Issue by ncc0010** [grafana/grafana#32332]
Hey guys, I've been having some issues attaching alerts to my existing dashboard. I was able to get the test notifications to work and route properly to Slack but once the threshold is in a place to send an alert, nothing happens. When I look under test rule I'm getting "tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request".

Query:
![image](https://user-images.githubusercontent.com/81389391/112543368-a564a200-8d83-11eb-8bc4-e441a6b57945.png)

Alerts:
![image](https://user-images.githubusercontent.com/81389391/112543410-b4e3eb00-8d83-11eb-851e-b4a80350ad2e.png)

Testing Rule:
![image](https://user-images.githubusercontent.com/81389391/112546717-caf3aa80-8d87-11eb-8272-f4d1a069c53a.png)

**What happened**:
The alert didn't work
**What you expected to happen**:
The alert to go off when the threshold is met and send a notification via slack
**Environment**:
- Grafana version: 7.3.6
- Data source type & version: InfluxDB
- OS Grafana is installed on: Ubuntu 20.04.1

**Comment by zoltanbedi** [comment]
I was not able reproduce this in Grafana 7.5.0. Can you try to upgrade your Grafana?

**Comment by ncc0010** [comment]
What is the most recent version?

Nick Coleman
Help Desk Technician
***@***.******@***.***>
334-640-0003

[signature_1914556561]

“Make each day your masterpiece.” – John Wooden


This email is intended only for the person to whom it is addressed and/or otherwise authorized personnel. The information contained herein and attached is confidential and the property of Version3. If you are not the intended recipient, please be advised that viewing this message and any attachments, as well as coping, forwarding, printing, and disseminating any information related to this email is prohibited, and that you should not take any action based on the content of this email and/or its attachments. if you received this message in error, please contact the sender and destroy all copies of this email and any attachment.


From: Zoltán Bedi ***@***.***>
Date: Friday, March 26, 2021 at 7:17 AM
To: grafana/grafana ***@***.***>
Cc: Nicholas Coleman ***@***.***>, Author ***@***.***>
Subject: Re: [grafana/grafana] Tsdb.HandleRequest() error Influxdb returned statuscode invalid status code: 400 Bad Request (#32332)

I was not able reproduce this in Grafana 7.5.0. Can you try to upgrade your Grafana?

**Comment by zoltanbedi** [comment]
7.5.0
