### ISSUE TITLE
Playlists are visible even when user has no access to dashboard

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#32330]
**What happened**:
Users can see all playlists, even if they does not have access to dashboard that is in the playlist.
![image](https://user-images.githubusercontent.com/19311511/112540042-00ad8900-8db2-11eb-9b1f-f901ee7a5fd7.png)
---
![image](https://user-images.githubusercontent.com/19311511/112540074-0b681e00-8db2-11eb-9337-99a562643125.png)

**What you expected to happen**:
Playlists should be hidden if user does not have access to dashboard.

**Environment**:
- Grafana version: 7.5.0
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Debian 4.9
- User OS & Browser: -
- Grafana plugins: -
- Others: -

**Comment by zoltanbedi** [comment]
Possibly related to https://github.com/grafana/grafana/issues/25788

**Comment by torkelo** [comment]
playlists are global currently (do not live in any folder) so any viewer & editor can see them:

https://github.com/grafana/grafana/issues/11978
