### ISSUE TITLE
Bug : Opentsdb alias has a problem for multiple queries with the same metric name

### ISSUE THREAD

**Issue by Othyus** [grafana/grafana#3233]
Hi,
When i define several queries (opentsdb datasource) with one alias per query, 
if queries have the same metric name, only the first alias is used

![alias_problem](https://cloud.githubusercontent.com/assets/9106311/11143813/66a537bc-89f8-11e5-816a-f763791905e2.png)

**Comment by utkarshcmu** [comment]
Duplicate #1876

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/1876
