### ISSUE TITLE
Dashboard crash when editing query of missing/renamed datasource

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#32337]
**What happened**:
When pressing the "expand" icon of a mixed mode query, where MySQL is the datasource and that that has gone missing (renamed), "An unexpected error happened" screen pops up.
 
**What you expected to happen**:
Show query along with the message that the chosen datasource is not available. This works when the panel is not used in Mixed Mode.

**How to reproduce it (as minimally and precisely as possible)**:
Create a mixed mode panel with a MySQL datasource. Then rename that datasource in Grafana settings. Then try to edit the query on the panel.

**Environment**:
- Grafana version: 7.5.0
- Data source type & version: MySQL
- OS Grafana is installed on: RHEL7
- User OS & Browser: Chrome latest
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Unable to replicate this in 7.5.1
