### ISSUE TITLE
Table format for Loki

### ISSUE THREAD

**Issue by loganmc10** [grafana/grafana#32349]
**What would you like to be added**:
The "Format as Table" option for Loki

**Why is this needed**:
Loki's 'sister project' Prometheus has this option. The query syntax is similar so I hope this is possible with Loki. Displaying some data like "top 10 labels by log count over the last 3 hours" isn't really possible currently as far as I can tell.

**Comment by zoltanbedi** [comment]
Can you help us with details?
What query did you use specifically?
Did you try to use transformation(labels to fields)?

**Comment by loganmc10** [comment]
![Capture](https://user-images.githubusercontent.com/848146/112670507-9aaf1900-8e26-11eb-9cac-c939987ee454.PNG)

Sorry I had to black out the device names. Basically I'm trying to create a bar graph that sums the log entries by device_name over the user's specified time interval.

Maybe the "Format as Table" option wouldn't help me? I'm trying to find a way to sort the entries by size, rather than alphabetically, however the "Sort By" transformation doesn't give useful options:
![Capture2](https://user-images.githubusercontent.com/848146/112670789-faa5bf80-8e26-11eb-821c-f952793e5856.PNG)

The other helpful thing would be the ability to only show the top X items, although that may be a limitation in Loki itself, rather than the Grafana visualization.

**Comment by ivanahuckova** [comment]
@loganmc10 this is currently not possible, however you can upvote and follow this feature request https://github.com/grafana/grafana/issues/17245. As it is the same feature request, I am closing this as duplicate.

Regarding possible workarounds on how to achieve this - you can use Table panel + Transformations + Series overrides. See:
**Gauge in table** (you can use sorting here): 
![image](https://user-images.githubusercontent.com/30407135/112838441-59746e80-909d-11eb-9686-342c78e357f6.png)

**Bar gauge:**
![image](https://user-images.githubusercontent.com/30407135/112838582-7d37b480-909d-11eb-8c09-187e63971aeb.png)
