### ISSUE TITLE
Explore > Copy shortened link includes Grafana backend port when Grafana is behind reverse proxy

### ISSUE THREAD

**Issue by urosorozel** [grafana/grafana#32340]
**What happened**:
I'm running Grafana behind reverse proxy I have relevant variables for serving Grafana behind reverse proxy set:
`GF_SERVER_ROOT_URL`
`GF_SERVER_DOMAIN`
`GF_SERVE_FROM_SUBPATH`

I tried to share a query result by going to `Explore` and then clicking on share `Copy shortened link`
unfortunately link is pointing to `GF_SERVER_ROOT_URL` and not to `GF_SERVER_DOMAIN`

**What you expected to happen**:

link should be accessible at reverse proxy frontend

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Grafana with reverse proxy 

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v7.4.3`
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Make sure you set root_url in your ini file to the full browser url (without port), 

https://grafana.com/docs/grafana/latest/administration/configuration/#root_url
