### ISSUE TITLE
Feature request: Two different time-range series data are shown in the same graph

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#3235]
I want to compare the datas of two different time-ranges to get the trend-change in the same graph. 
There are two cases: 
1) year-over-year statistics: over the same period of the previous year. such as: the time series of July 2014 compare with the data of July 2013. (same month, different year)
![qq 20151113233219](https://cloud.githubusercontent.com/assets/8777671/11149775/701de5fc-8a5f-11e5-9c2d-c0ff6a5d09b8.png)

2) link relative (month-over-month) statistics: over the adjacent period of the same year. such as: the time series of august 2014 compare with the data of July 2014. (adjacent month, same year)
![qq 20151113233157](https://cloud.githubusercontent.com/assets/8777671/11149800/9cfa8710-8a5f-11e5-93fe-5734b9d12ecc.png)

**Comment by anryko** [comment]
++

**Comment by leesjensen** [comment]
+1

**Comment by utkarshcmu** [comment]
Duplicate #2951

**Comment by godfreyhe** [comment]
hi @utkarshcmu, It's working with comparing two different timelines on two panels with timeShift. But I want to show the diff time-range series in one panel, and It maybe need two requests with diff time-ranges for opentsdb in one graph, and two x-axises in the graph.

**Comment by utkarshcmu** [comment]
@godfreyhe The reason for specifying duplicate is because both the issues want to comparing trends but in a different way. In this issue, we want to have both the lines plotted in the same graph. But in #2951 I displayed side by side. In the end it does not matter much to me whichever way we choose. We both want to compare timely trends. :)

**Comment by godfreyhe** [comment]
@utkarshcmu I totally agree with you, :+1:

**Comment by vitorboschi** [comment]
+1

**Comment by arunthilak** [comment]
+1 
Hi, 
Is there an indication of when or which release this feature request might be considered?

**Comment by joyhope** [comment]
+1

**Comment by krishnakanthpps** [comment]
+1. Desperately needed feature.

**Comment by grobie** [comment]
For people using prometheus as datasource, it's possible to use the [offset modifier](https://prometheus.io/docs/querying/basics/#offset-modifier) to achieve that result.

**Comment by torkelo** [comment]
this is possible with time series database's like Graphite that have time shift function. 

Might be possible in the future for all time series databases with the advent of this https://github.com/grafana/grafana/issues/3677 

so closing this

**Comment by george-marcel** [comment]
+1

**Comment by sohamnavadiya** [comment]
+1

**Comment by ozandeniz** [comment]
+

**Comment by dark-bytes** [comment]
+1

**Comment by crazyscience** [comment]
👍 +1

**Comment by aboughzela** [comment]
+1

**Comment by hyperbart** [comment]
+1

**Comment by UKSFM99** [comment]
+1

**Comment by deenbandhu-agarwal** [comment]
+1

**Comment by fncmedia** [comment]
+1

**Comment by Sathishruw** [comment]
+1

**Comment by RustamGimadiev** [comment]
+1

**Comment by v-avdeev** [comment]
+1

**Comment by mstraughan86** [comment]
+1, please.

**Comment by justinhilles** [comment]
+1

**Comment by vladimirbarsuk** [comment]
+1

**Comment by MatGit5** [comment]
+1

**Comment by brjborja** [comment]
+1

**Comment by Tyson1986** [comment]
+1

**Comment by nfw999** [comment]
We use this plugin to solve the problem and hope to help you.
https://github.com/AutohomeCorp/graph-compare-panel
![Screenshot1](https://raw.githubusercontent.com/AutohomeCorp/graph-compare-panel/master/dist/screenshots/image-1.png)
![Screenshot1](https://raw.githubusercontent.com/AutohomeCorp/graph-compare-panel/master/dist/screenshots/image-2.png)

**Comment by Byteme71** [comment]
@nfw999 hi, are you confident these time shifts are comparing the correct dates? Such as exactly the week prior and no overlap?

**Comment by nfw999** [comment]
@Byteme71 If the query range is one week and the time shift is one hour, there will be overlap.I don't think it is a problem.The time shift I think is the offset of a curve in the time dimension.

**Comment by Byteme71** [comment]
@nfw999 hm interesting, so I was able to get the correct days to compare by setting it to a 31 day range but I also think it will change with everyone month as there are different amount of days in every month too? Unless I am mistaken, I am a junior :) Thank you very much though!

**Comment by phreakadelle** [comment]
+1
