### ISSUE TITLE
Time Menu on mobile phone (small screen) not readable

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#32369]
Grafana: 7.5.0 on Windows Server

![grafik](https://user-images.githubusercontent.com/79257887/112657505-c9db7f80-8e52-11eb-91ae-de82cf626d69.png)

**Comment by thomasvnl** [comment]
I can confirm this does not only happen on small screens, it seems to depend on the aspect ratio (as well). On a OnePlus Nord the same happens, which has a 21:9 aspect ratio, which renders a viewport screensize of 412px * 915px

**Comment by takkaO** [comment]
Is there any progress on this issue? Version 8.x still have this issue.
The easiest fix would be to improve the CSS?

**Comment by UlrichThiess** [comment]
Unfortunately it is still there. However, only when I am logged in, when I am not logged in, the menu is at the top in one line. After logging in, the menu has two lines and the time selection is displayed too far to the left (the icon is further to the left).

**Comment by takkaO** [comment]
In my environment (e.g. iPhone SE2), this problem occurs all the time, whether I'm logged in or not. 
I think this problem is affected not only by the screen size, but also by the length of the name in the dashboard.

![sample](https://user-images.githubusercontent.com/46308252/144944277-ac522a22-d5a8-4103-a2f8-50a765cc7ace.png)

**Comment by thomasvnl** [comment]
> In my environment (e.g. iPhone SE2), this problem occurs all the time, whether I'm logged in or not. I think this problem is affected not only by the screen size, but also by the length of the name in the dashboard.
> 
> ![sample](https://user-images.githubusercontent.com/46308252/144944277-ac522a22-d5a8-4103-a2f8-50a765cc7ace.png)

Yeah it has to do with the length of the name of the dashboard too

**Comment by thomasvnl** [comment]
> Unfortunately it is still there. However, only when I am logged in, when I am not logged in, the menu is at the top in one line. After logging in, the menu has two lines and the time selection is displayed too far to the left (the icon is further to the left).

That might be because just enough icons disappear whilest logged out to make the dropdown align properly

**Comment by takkaO** [comment]
By modifying the css, we got a temporary solution.
The TimeRangePicker's css is in ```packages/grafana-ui/src/components/DateTimePickers/TimeRangePicker/TimePickerContent.tsx```

I made the following changes to the CSS and built it. 
Note: The changes are not the best solution.

```tsx
@media only screen and (max-width: ${theme.breakpoints.values.lg}px) {
  width: 262px;
}
/* Added code begin */
@media only screen and (max-width: 600px) {
  ${isReversed ? 'left' : 'right'}: -20px;
}
/* Added code end */
```

Here is an example of the application result on iPhone SE2.

![fig](https://user-images.githubusercontent.com/46308252/148671325-3f0ef004-bc87-4f8f-9de0-51237a625ee4.png)

I want to discuss about this solution.
Thank you.
