### ISSUE TITLE
Timeseries Panel beta: Stack series

### ISSUE THREAD

**Issue by gabzim** [grafana/grafana#32371]
**What would you like to be added**:
I currently see no way of stacking metrics in the bar mode for the fields.
**Why is this needed**:
There are many new useful options in this panel that the traditional panel lacks. I would like to leverage them but I can't switch over if I lose the ability to stack fields.

**Comment by dprokop** [comment]
@gabzim stacking comes to tome series panel in Grafana 8

**Comment by leeoniya** [comment]
tracked by https://github.com/grafana/grafana/issues/30564
