### ISSUE TITLE
Data Sources - MySQL add connection params

### ISSUE THREAD

**Issue by cloverzrg** [grafana/grafana#32374]
**What would you like to be added**:
When add a MySQL source, add a input for the connection params, like `charset=utf8mb4&parseTime=True&loc=Asia%2FShanghai`
**Why is this needed**:
The time in the datetime field of my database is in +8 time zone, but grafana is regarded as UTC time zone

**Comment by zoltanbedi** [comment]
Duplicate of https://github.com/grafana/grafana/issues/16539

**Comment by nicolaerosia** [comment]
this was not fixed
