### ISSUE TITLE
Docs feedback: /datasources/add-a-data-source.md

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#32378]
These docs are a couple of years out of date. Would be great to link to these from each data source, but this page is missing the step where you select a data source to add. 

The instructions from the Installation tab of a data source listing page ([example](https://grafana.com/grafana/plugins/grafana-github-datasource/?tab=installation)) might be a head start. 

Configure the Data Source
Accessed from the Grafana main menu, newly installed data sources can be added immediately within the Data Sources section.

Next, click the Add data source button in the upper right. The data source will be available for selection in the Type select box.

To see a list of installed data sources, click the Plugins item in the main menu. Both core data sources and installed data sources will appear.

**Comment by mjseaman** [comment]
CC @osg-grafana @bossinc

**Comment by achatterjee-grafana** [comment]
Fixed in PR https://github.com/grafana/grafana/pull/32462.
