### ISSUE TITLE
Grafana v2.0.0-beta1: Java script error "TypeError: b.datasource.listDashboards is not a function"

### ISSUE THREAD

**Issue by swarup-donepudi** [grafana/grafana#3238]
I added graphite as the data source. Here is the link for the my graphite-web dev environment: http://23.253.105.68:80 . Here is a snapshot of the data source configuration on grafana.

![image](https://cloud.githubusercontent.com/assets/6811012/11164939/91bc6d6c-8ac5-11e5-9bf0-ef56cb14fb7f.png)

Browser : Chrome
I get js error when clicked on "List Dishbaord" button. I am not sure what is wrong here. I am using grafana betaV2.0.0-beta1. I tried switching the access mode to direct and proxy but result did not change. Also, both graphite and grafana are hosted on the same machine but different web servers. The error description does not indicate anything that points CORS as the root cause.

Please help.

![image](https://cloud.githubusercontent.com/assets/6811012/11164948/c5d3562e-8ac5-11e5-975f-cacc3ff86408.png)

TypeError: b.datasource.listDashboards is not a function
    at l.b.listAll (app.8ae07506.js:24)
    at app.8ae07506.js:13
    at e (app.8ae07506.js:13)
    at l.$eval (app.8ae07506.js:12)
    at l.$apply (app.8ae07506.js:12)
    at HTMLButtonElement.<anonymous> (app.8ae07506.js:13)
    at HTMLButtonElement._.event.dispatch (app.8ae07506.js:6)
    at HTMLButtonElement.q.handle (app.8ae07506.js:5)

**Comment by utkarshcmu** [comment]
Loads for me though, I am using the Grafana v2.5 on Chrome. Please upgrade to the latest version. Here is the 

<img width="779" alt="screen shot 2015-11-14 at 11 18 43 am" src="https://cloud.githubusercontent.com/assets/1019609/11165382/f41b4086-8ac1-11e5-8f69-078a4dc7eb22.png">

**Comment by swarup-donepudi** [comment]
@utkarshcmu I have clean installed the new version now. However I get the below error message when I click on "List dashboards button" This seems to be an expected behaviour since the error message is displayed by grafana web interface rather than google developer console.

![ss2](https://cloud.githubusercontent.com/assets/6811012/11167144/15146c64-8b1b-11e5-96e1-d1bef5cc5b13.jpg)
![ss3](https://cloud.githubusercontent.com/assets/6811012/11167145/1524c5dc-8b1b-11e5-88b2-3d37ef646b76.jpg)

**Comment by utkarshcmu** [comment]
@swarup-donepudi Can you please run this query in your browser or from your grafana server(if you are using proxy mode) to your Graphite server and post the output here?

```
http://<your_graphite_url>/dashboard/find/?query=
```

**Comment by swarup-donepudi** [comment]
@utkarshcmu Here is the output

{"dashboards": []}

**Comment by utkarshcmu** [comment]
That means there are no dashboards to import from that Graphite.

**Comment by swarup-donepudi** [comment]
@utkarshcmu I have just created a dashboard on graphite and now the get call responds with below JSON

{"dashboards": [{"name": "router-bids"}]}

However, it does not show up on grafana. I still get the same message.

**Comment by utkarshcmu** [comment]
I am not sure what it is the problem because Graphite dashboard import works with my Grafana/Graphite setup. Did u test the connection between your Grafana setup and Graphite server? Looks like there lies the issue.
