### ISSUE TITLE
Harmonize Legend-Select-Behaviour between Pie Chart & TimeSeries

### ISSUE THREAD

**Issue by tzafke** [grafana/grafana#32382]
**What would you like to be added**:
* in Grafana we can visualize multiple metrics in one timeseries as well as visualizing multiple metrics in a pie chart 
(that's what pie charts do)
* when activating the legend, we can select legend items by clicking them to show / unshow the visualized series / metrics
* the behaviour of this action differs between
  * panel/graph (panel/timeseries) and panel/piechart
  * panel/graph
    * selecting a legend item exclusively shows the selected item (means unselect all others)
    * selecting / unselecting multiple items is possible with holding shift OR ctrl
    (I learned from https://github.com/grafana/grafana/issues/18477 that is works with shift)
  * panel/piechart
    * "clicking" a legend item selects / unselects the single series / metric w/o any effect to the other items
    * to have only two metrics visaulized I need to click (unselect) all the other metrics and the other way around)
* I can understand that both behaviours have their advantages / disadvantages with the number of metrics as the differentiator when to use what
* I propose the following (combined) behavior for both panels
  * having the current pie chart behavior as a default 
    * is very intuitiv
    * in pie charts it should be a very rare usecase to select one item exlusively --> only to have a starting point for "multi-select"
    * but it makes sense to have a feature for "show all again"
  * using the alt key to exclusively select one metric or show all metrics again
  (not using shift, because this also selects the text and expectation for shift is to mark/select everything between 1st selected item to 2nd selected item)
  * having a panel option to generate the current timeseries behaviour. In this case keep it wih ctrl as "multi-select-key"

**Why is this needed**:
* from my perspective the diffent behaviour is confusing for users
* the current pie chart is lacking the feature of "exclusively select" / "select all again" as far is I know
* from my perspective the behaviour of the panel/graph is not intuitiv but an good option for powerusers. Thats why the
  * the feature should be available via ALT
  * there CAN be an panel option to make that default

Version: 7.3.6

**Comment by louislefebvre** [comment]
Hello, did you find a way to achieve this? Thank you

**Comment by mdvictor** [comment]
Hello! I agree that the PieChart should not differ in legend select functionality as to avoid confusion, I'll have a look on fixing this.

**Comment by WEIZIBIN** [comment]
agree
