### ISSUE TITLE
Compiled version of @grafana/ui

### ISSUE THREAD

**Issue by AdvaithD** [grafana/grafana#32393]
**What would you like to be added**:
Publish a compiled version of @grafana/ui to mitigate css import issues

**Why is this needed**:
It seems like @grafana/ui is importing a css file. This doesn't play well with frameworks (e.g: NextJS) with SSR. A compiled dependency will not have references to CSS files / require bundler specific integrations. TL;DR: grafana ui is incompatible with NextJS.

**Comment by torkelo** [comment]
@grafana/ui is not importing anything, but it is built to be run inside Grafana so expects some legacy global css to be there. 

We will soon get rid of this

**Comment by AdvaithD** [comment]
Got it. Thanks for the quick turnaround.
