### ISSUE TITLE
Password field with auto complete enabled

### ISSUE THREAD

**Issue by saipavankumarreddy** [grafana/grafana#32418]
**What happened**: Using the Burp Scanner to scan the Grafana and It is reported Password field with auto complete enabled with Low serverity. 

I got the below response in the scan report. 
Request:

GET /grafanascan/public/build/app.6fac2557b282ba646cbb.js HTTP/1.1
Host: a.b.c.d
Accept-Encoding: gzip, deflate
Accept: */*
Accept-Language: en
User-Agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; Win64; x64; Trident/5.0)
Connection: close
Referer: https://a.b.c.d/grafanascan/login
Cookie: route=1b23fe11a941e2a54bfaf64b6485a23d; redirect_to=%2Fgrafanascan%2Fpublic%2Ffonts%2F

Response:

HTTP/1.1 200 OK
Date: Fri, 26 Mar 2021 18:01:18 GMT
Content-Type: text/javascript; charset=utf-8
Content-Length: 2796475
Connection: close
Accept-Ranges: bytes
Cache-Control: public, max-age=31536000
Last-Modified: Thu, 18 Mar 2021 19:37:53 GMT
Strict-Transport-Security: max-age=15724800; includeSubDomains

/*! For license information please see app.6fac2557b282ba646cbb.js.LICENSE.txt */
(window.webpackJsonp=window.webpackJsonp||[]).push([[42],{"+99A":function(e,t,n){"use strict";n.d(t,"a",(function(){re
...[SNIP]...
</div>\n\n\t<form name=inviteForm class="login-form gf-form-group">\n\t\t<div class=gf-form>
...[SNIP]...
</span>\n\t\t\t<input type=password name=password class="gf-form-input max-width-21" required ng-model=formModel.password id=inputPassword placeholder=password>\n\t\t</div>
...[SNIP]...

**What you expected to happen**: I don't want to see this in Burp scan report. 

**How to reproduce it (as minimally and precisely as possible)**: Use the burp scan tool. 

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version: 7.1.3 
- OS Grafana is installed on:
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Cannot find any recommended / best practice around this. Will setting this to off disable password autocomplete? That feels like bad as well as many users rely on browsers to store & remember credentials.

**Comment by mckn** [comment]
I'm closing this one due to inactivity. Please re-open if needed.
