### ISSUE TITLE
Docs feedback: /administration/set-up-for-high-availability.md

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#32432]
This page makes no reference on how to configure ldap sync (https://grafana.com/docs/grafana/latest/enterprise/enhanced_ldap/#active-ldap-synchronization) in an HA environment. It makes sense to have each node sync on a different time schedule, so a) both nodes don't sync at the same time, and b) so that if one node is down, the sync still runs at least daily.

**Comment by achatterjee-grafana** [comment]
Tagging @osg-grafana, as this is enterprise docs.

**Comment by achatterjee-grafana** [comment]
Ping @GrafanaWriter to triage.

**Comment by chri2547** [comment]
Closing this issue because it's over a year old, in an unresourced area, and not likely to be worked on in the next year.
