### ISSUE TITLE
Docs: broken link at dashboard provisioning page

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#32441]
[Reusable Dashboard URLs](https://grafana.com/docs/grafana/latest/administration/provisioning/#reusable-dashboard-urls) section in the Provisioning docs contains broken link to the `uid` reference:

> If the dashboard in the json file contains an uid, ...

Link URL:
https://grafana.com/reference/dashboard/#json-fields

**Comment by achatterjee-grafana** [comment]
Fixed in PR https://github.com/grafana/grafana/pull/32448.
