### ISSUE TITLE
Best Way to do Grafana+OpenTSDB Load testing

### ISSUE THREAD

**Issue by shanky05** [grafana/grafana#3245]
Hello @torkelo 

Can you please guide me with some guidance on how to start with load testing of Grafana_OpenTSDB.

We basically want to check If there are multiple users accessing the Dashboards how is the performance of graphs . How much time doe it take to make an OpenTSDB query.

Currently i am struggling with Jmeter to do the smae task. is there any thing better than Jmeter

Other query i have is should we test moving from Grafana to OpenTSDB or the other way round . As i have seen some post of InfluxDB+ Grafana where they have installed Jmeter to monitor InfluxDB.

Please suggest?

**Comment by torkelo** [comment]
I am not sure what the best way to load test OpenTSDB is.
