### ISSUE TITLE
Panels not associated with a data source are requiring right query syntax to DS

### ISSUE THREAD

**Issue by baur** [grafana/grafana#32463]
**What happened**:

Panels not associated with a data source are requiring right query syntax to DS

![image](https://user-images.githubusercontent.com/2898361/112935326-5c2a9e80-9145-11eb-87f1-28050bd720e9.png)

**What you expected to happen**:

no error

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: MSSQL
- OS Grafana is installed on: Win10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Could it be that you had this error and you changed panel and it was just a left-over from the previous panel?

**Comment by torkelo** [comment]
was able to replicate, the last query error state is not cleared when changing to a non data panel

**Comment by baur** [comment]
> Could it be that you had this error and you changed panel and it was just a left-over from the previous panel?

That's right, error messge from prev panel
