### ISSUE TITLE
Grafana Y-axis2 in templating

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#3246]
Hello @torkelo 

I want to show B query metrics in Y-axis2(right y-axis), I can do that manually.

But i am using templating, so whenever the value changed via dropdown menu, T-Axis2 disappears. 

I also tried "alias or regex in Display Style", but it doesn't work.

please help on this.

Thanks,
Himanshu

**Comment by torkelo** [comment]
why did alias or regex option not work?

**Comment by Himanshu-pupneja** [comment]
Thank you @torkelo for your response

Attached is the snapshot of two queries.

![image](https://cloud.githubusercontent.com/assets/15123322/11175000/b74a4e58-8c52-11e5-871f-8ca31564b203.png)

And i put below string to "alias or regex option".

/farm_utilization.SJ_GW.user_jobs.$UserName.$PendWindow.job_cnt/. 
And it doesn't work.

Please let me know if i am doing something wrong.

**Comment by torkelo** [comment]
since you use aliasByNode the seriesname is not going to be the full metric path

**Comment by Himanshu-pupneja** [comment]
So, should i also use aliasbynode in regex?
or it won't work at all

**Comment by torkelo** [comment]
no you should specify a regex that will match the series names (as you see it in the legend)

**Comment by torkelo** [comment]
something like /$UserName.$PendWindow.job_cnt/

**Comment by Himanshu-pupneja** [comment]
Tried the same but its not working.

![image](https://cloud.githubusercontent.com/assets/15123322/11175701/fca3056e-8c5a-11e5-9a10-f86475d171a3.png)

can you try the same at your end if possible?
