### ISSUE TITLE
Grafana 5xx response should be 4xx

### ISSUE THREAD

**Issue by ericayosh** [grafana/grafana#32461]
When querying datasources Grafana frequently returns 5xx responses when customer input is invalid. For example, when querying a database that does not exist, or when a CloudWatch logs query is incorrect, CW returns errors such as `mismatched input '<EOF>' expected K_STATS Service:AWSLogs, Status Code: 400` which Grafana than translates as 5xx. 

5xx suggests this is a server side error, that can be retried successfully by the client. 

**What you expected to happen**:
Grafana datasource 4xx responses should not be translated as 5xx. Error messages shown in the Grafana workspace should show the datasource errors, instead of generic Grafana `5xx Server Error`

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: CloudWatch, DataDog, etc.
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by immohsin** [comment]
Can I pick this issue as an outside contributor?

If yes please point me to the appropriate directory. Thanks!

**Comment by sunker** [comment]
@grafana/observability-squad can you provide @immohsin some guidance on how to contribute?

**Comment by gabor** [comment]
from a quick-check, it seems the decision to return a http500 happens in https://github.com/grafana/grafana/blob/main/pkg/api/metrics.go#L79
so it might be more complex to fix this (i think there is not enough info at that point to make the http400/http500 decision).
maybe @grafana/backend-platform has some ideas?

**Comment by dsotirakis** [comment]
Shouldn't we just parse the response `status_code`, instead of manually throw 500??

**Comment by marefr** [comment]
Yeah have to handle this in the Cloudwatch data source code
