### ISSUE TITLE
Grafana fails to load query variables On Dashboard Load, resulting in an empty dropdown variable list and faulty panels

### ISSUE THREAD

**Issue by FatimaNasser** [grafana/grafana#32468]
**What happened**:
We recently upgraded our Grafana version from v6.5.2 to v7.4.0 and it seems like the query variables are no longer resolved on dashboard loads and the preview of the values of these variables are always empty.

**What you expected to happen**:
Please refer to the screenshots attached below. The Campaign dropdown list should have not shown an empty list resulting in erroneous panels. The Campaign list should have been correctly shown by resolving the journey variable appropriately, displaying all the existing campaigns in the understudy ES index.

**How to reproduce it (as minimally and precisely as possible)**:
Our variable journey is supposed to show the list of all existing campaigns in the JourneysMapping ES index. Once the refresh setting of this variable is set to the (“on time range change”) option, everything works well and the list of Campaigns becomes available.

<img width="536" alt="variable-On time range change" src="https://user-images.githubusercontent.com/58142480/112951522-bb83b100-913b-11eb-8dd8-c54328746e48.png">

Whereas when the refresh is set to on dashboard load, the variable doesn’t seem to load correctly and thus none of the existing campaigns appear in the list. This bug is the reason behind the erroneous panels!

<img width="527" alt="variable-On dashboard load" src="https://user-images.githubusercontent.com/58142480/112951569-c9d1cd00-913b-11eb-91eb-4be0a97bfc53.png">

<img width="923" alt="Errorneous Panels" src="https://user-images.githubusercontent.com/58142480/112951786-0998b480-913c-11eb-9e0b-4584b053dd5a.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.4.0
- Data source type & version: Elasticsearch  7.0+
- OS Grafana is installed on: 
- User OS & Browser: Windows Chrome/Firefox/Edge
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
Fixed in https://github.com/grafana/grafana/pull/31721 Please upgrade to 7.5

**Comment by FatimaNasser** [comment]
Thanks a lot for your quick response, I appreciate. We will upgrade to 7.5.
