### ISSUE TITLE
Plugin Dashboard List doesn’t work after upgrade Grafana to 7.5.1-1 

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#32474]
**What happened**:
After upgrade Grafana from 7.4.0 to 7.5.1-1 plugin "dashboard list" does work. When I click Folder doesn’t develop. I see only All.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.1-1
- Data source type & version: MSSQL
- OS Grafana is installed on: CentOS 8
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: Dashboard List
- Others:

**Comment by Elfo404** [comment]
i can reproduce this in master. The "Folder" Select in the panel options doesn't show any option when opened.
(no errors in console)

<img width="316" alt="Screenshot 2021-03-31 at 13 05 36" src="https://user-images.githubusercontent.com/1170767/113141590-cb75c080-9221-11eb-89a7-067efded3a70.png">

**Comment by jackw** [comment]
Can also confirm. It looks to be caused by the FolderPicker menuPosition prop [here](https://github.com/grafana/grafana/blob/master/public/app/core/components/Select/FolderPicker.tsx#L164).
