### ISSUE TITLE
Prometheus: Extend autocomplete limit for labels/metrics 

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#32473]
**What would you like to be added**:
The current limit is 10,000. For autocomplete, we are always showing results based on the first 10,000 results,  as otherwise there could be a problem with browser running out of memory. We could do some testing and probably extend it. We should run some numbers on the current implementation to see at which item count it would actually degrade. I also suggest to use an Intel machine for this, since the new macs are not representative.

**Comment by jpdstan** [comment]
hi, just wanted to raise a suggestion from here https://github.com/grafana/grafana/pull/30199#issuecomment-824207988

**Comment by jpdstan** [comment]
Is there any plan to work on this? So far it's been quite a painpoint for our developers to have to use Metrics Browser to find their metrics. Moreover having the incomplete results in the main search bar is a bit misleading, and makes it look like metrics that exist don't exist. Here's a typical scenario:

https://share.getcloudapp.com/Apu9vm7e

**Comment by ivanahuckova** [comment]
@jpdstan removing of metrics autocomplete limit was just merged #39363 and will be part of the next 8.2 release. 🙂

**Comment by jpdstan** [comment]
Thank you @ivanahuckova !!!
