### ISSUE TITLE
Alerting: Access to query name in notification message template

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#32479]
**What would you like to be added**:

I'd like to have a [global variable](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/) that can be used in [alert notification templating](https://grafana.com/docs/grafana/latest/alerting/add-notification-template/), which will then be substitued **with the name of the query that triggered the alert**.
The default value would be just `A`, but recent grafana versions allow renaming of queries.

Example name in line with current global variables: `$__queryname`

**Why is this needed**:

Alerts do not support dashboard templating variables, so one has to create more static queries for alerting for different servers.
It is desireable that the failing service is identifiable in the notification message.

If a query is however no longer returning data (because the service crashed), 
**it is not possible to use e.g. prometheus labels like `${job}` in the notification template, because the time series does not exist.**

(There is also the limitation that these lables are missing in [OK] notifications, see #30606 , a query name variable could be used to slightly improve on that as well)

A `[No Data]` e-mail would look like this:

![grafik](https://user-images.githubusercontent.com/33002073/112964571-bd07a600-9148-11eb-9329-a3726da8e896.png)

By renaming multiple querys (or just the one query that is used):
![grafik](https://user-images.githubusercontent.com/33002073/112964974-1c65b600-9149-11eb-8799-14401a2e06cd.png)

and alert conditions like e.g. so:
![grafik](https://user-images.githubusercontent.com/33002073/112965042-2f788600-9149-11eb-94d6-941b51eb7622.png)

the notification could be:
![grafik](https://user-images.githubusercontent.com/33002073/112967026-17096b00-914b-11eb-9145-ddb86c8663b3.png)

**Thoughts**

Maybe I'm doing this too complicated. How is this supposed to be done with grafana alerts?
Using just one query for multiple services (series) makes it worse because prometheus timeseries could just disappear (become stale), and the `absent` function is a little bit tricky to use.

**Comment by seaurching** [comment]
Hi, have u found a solution for this?在message里面支持变量的需求,你实现了吗

**Comment by Mario-Hofstaetter** [comment]
@seaurching  No, unfortunately not. We have since moved away from the approach described above.

**Comment by dcl-lily** [comment]
Hope to add this feature, I really need it

**Comment by santihernandezc** [comment]
Hi @Mario-Hofstaetter, about this bit:

> Alerts do not support dashboard templating variables, so one has to create more static queries for alerting for different servers. It is desireable that the failing service is identifiable in the notification message.

I think what you're trying to do can be achieved with a [multi-dimensional alert rule](https://grafana.com/docs/grafana/latest/alerting/alerting-rules/create-grafana-managed-rule/#single-and-multi-dimensional-rule) and some [templating](https://grafana.com/docs/grafana/latest/alerting/fundamentals/annotation-label/variables-label-annotation/). I'd strongly suggest to try that out.

Also, a little comment on templating for `OK` notifications:
> (There is also the limitation that these lables are missing in [OK] notifications, see https://github.com/grafana/grafana/issues/30606 , a query name variable could be used to slightly improve on that as well)

I left a [comment](https://github.com/grafana/grafana/issues/30606#issuecomment-1098437718) on that issue. This is supported since Grafana v8.5.

Let me know if this solves your issue!

**Comment by santihernandezc** [comment]
It has been two weeks since my last message. I'm closing this issue, but feel free to reopen it if needed.

**Comment by Mario-Hofstaetter** [comment]
Been on vacation, since there was little feedback from the community asking for this feature, closing is fine for me.
