### ISSUE TITLE
Renaming query does not change name in alert condition

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#32481]
**What happened**:

When using two (or more) querys `A` and `B` as alert conditions, 
**after renaming all querys, only query `A` has its new name in the alert condition**, the second conditions still shows `B`. If there is a query `C` its name is also not refactored in the alert condition.

**What you expected to happen**:

Changing the name of any query, not just the first one, should rename it in alert conditions.

**How to reproduce it (as minimally and precisely as possible)**:

- Go to any dashboard e.g. <https://play.grafana.org/d/000000012/grafana-play-home?tab=query&orgId=1&editPanel=2> 
- Add second or third queries
![grafik](https://user-images.githubusercontent.com/33002073/112969721-d0694000-914d-11eb-9557-6fe2f7bf6397.png)

- Add alert, add conditions using all queries:
![grafik](https://user-images.githubusercontent.com/33002073/112969841-eb3bb480-914d-11eb-9bc9-b755bf628daf.png)

- Rename the queries:
![grafik](https://user-images.githubusercontent.com/33002073/112970015-0f979100-914e-11eb-9f8d-bef8fed48005.png)

- Only the first query name is refactored in alert conditions:
![AndH0zxuQJ](https://user-images.githubusercontent.com/33002073/112970229-4372b680-914e-11eb-9f5e-8ef2779869d1.gif)

Saving the dashboard fails with an error (which is good):
![grafik](https://user-images.githubusercontent.com/33002073/112970677-bbd97780-914e-11eb-8f50-7ca160a4f72f.png)

**Environment**:
- Grafana version: `Grafana v7.5.1 (4dffb875cf)`
- Data source type & version: Demo with graphite, also with prometheus
- OS Grafana is installed on: <https://play.grafana.org/>
- User OS & Browser: Windows 10 2020H2, Firefox 86

**Comment by torkelo** [comment]
This will be fixed in the coming alerting system where conditions and queries are defined together

**Comment by konrad147** [comment]
Legacy alerting is no longer actively maintained. The described behavior works in unified alerting
