### ISSUE TITLE
Prometheus data somehow duplicated when Instant enabled

### ISSUE THREAD

**Issue by HardcoreWR** [grafana/grafana#32485]
We recently updated Grafana from 7.4.3 to 7.5.0 and I've noticed new weird behavior with Prometheus queries, using a Table format and enabling the Instant button.
It looks like the data that is received from a single query is somehow duplicated.
I do expect that a single query will return 1 set of timeseries, and when setting the Table format + enabling Instant it should give me 1 resultset instead of the same resultset twice.

You can reproduce this on the Grafana Playground as well.

1. Go to: https://play.grafana.org/d/000000012/grafana-play-home?orgId=1
2. Add an empty panel (you can leave the visualization as Graph)
3. Select Prometheus as the DataSource
4. Use the following query: `prometheus_build_info{instance="demo.robustperception.io:9090"}`
5. Check the Graph and you'll see only 1 entry
6. Select the Table format underneath the query and watch the graph, you'll see you still have a single entry
7. Now enable the Instant button and you'll notice there's 2 times the same entries

For any tables I created in 7.4.3 it still works, refreshing the panel to get new datapoints won't duplicate the data.
However, if I select the input field of the query and then click outside the input field it immediately shows the same behavior as described above.

I just rolled back to 7.4.3 and this issue is no longer there.

I have not tested this against other Datasources because I don't have any to test it with :-)

**Comment by torkelo** [comment]
Can replicate this here https://play.grafana.org/d/AbAoMMlGz/prometheus-instant-double-queries?orgId=1

**Comment by eglyn** [comment]
Hi, 

Same here with Prometheus and Grafana, to monitor OpenVPN: 

![Capture d’écran 2021-03-30 132458](https://user-images.githubusercontent.com/24936778/112981378-62c41080-915b-11eb-93b6-e86d69fbbe25.png)
