### ISSUE TITLE
InfluxDB: Server side expression (math) not working with division

### ISSUE THREAD

**Issue by SanderDelden** [grafana/grafana#32484]
**Screenshots**:
Failed division:
![image_2021-03-30_11-54-28](https://user-images.githubusercontent.com/38953576/112972218-52f2ff00-9150-11eb-9515-908cf2277f22.png)

Successful multiplication:
![image_2021-03-30_11-54-49](https://user-images.githubusercontent.com/38953576/112972232-55edef80-9150-11eb-9474-0b3c7ad7869d.png)

**What happened**:
Grafana returns <code>0</code> when performing a server side division expression on 2 InfluxDB queries.

**What you expected to happen**:
Return the result of the divison

**Anything else we need to know?**:
When using a expression (math) with division the result return is <code>0</code>. When using multiplication Grafana returns the expected value.
In another dashboard I use multiple 'stacked' (I'm sorry if this is the wrong term) queries as follows:
```
SELECT * FROM
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null))),
(SELECT percentile("TX",95) from (SELECT non_negative_derivative(sum("ifHCOutOctets"), 1s) * 8 / 1000000 * <redacted> AS "TX" FROM "100d_5m"."Interfaces" WHERE ("ifAlias" =~ /<redacted>/ AND "ifAlias" =~ /<redacted>/) AND $timeFilter GROUP BY time(5m) fill(null)))
```

When doing this Grafana returns <code>NaN</code> instead of <code>0</code> as a result for the expression.

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: InfluxDB 1.8.4
- OS Grafana is installed on: Debian
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: InfluxDB
- Others: N/A

**Comment by kylebrandt** [comment]
Not sure what is going on here. Things I am trying locally give me results I expect:

![image](https://user-images.githubusercontent.com/1692624/113423007-bd4baf80-939b-11eb-907f-d3a3d3c19bf8.png)

And single number math works:

![image](https://user-images.githubusercontent.com/1692624/113423055-d18fac80-939b-11eb-9a8e-b471e032a203.png)

In the your screenshot, `$A` and `$B` are time series, so the time stamps have to line up and it does point-wise math. But since the query time range is the same, and it looks like the metrics are the same, I would expect them to line up (and that it works with multiplication).

**Comment by kylebrandt** [comment]
Maybe your single stat display is truncating the decimals, and it rounds to zero?

**Comment by SanderDelden** [comment]
Hi @kylebrandt 

Turns out the issue was with one of my 'subqueries' not returning any data hence breaking the whole expression. Thank you very much for your input & help on this!

Kind regards,
Sander
