### ISSUE TITLE
Change "White labeling" to "Custom branding" or an alternative

### ISSUE THREAD

**Issue by osg-grafana** [grafana/grafana#32482]
_Originally posted by @mjseaman in https://github.com/grafana/grafana/pull/32451#discussion_r603668539_

**Comment by torkelo** [comment]
@osg-grafana is this a docs issue?

**Comment by torkelo** [comment]
But the feature is in enterprise, so should this issue be in that repo?

**Comment by osg-grafana** [comment]
@oddlittlebird and @achatterjee-grafana, including you for visibility about this doc issue being in the `grafana/grafana` repo instead of Enterprise.

**Comment by achatterjee-grafana** [comment]
Closing.
