### ISSUE TITLE
Coloring in singlestats panel can't handle negative values

### ISSUE THREAD

**Issue by soulgalore** [grafana/grafana#3248]
Hey @torkelo , thanks for the super great software!

In one of our usecases we calculate change in percentage over time and displays the data in a single stats panel. If nothing has changed we show 0%, positive change +X % and negative -Y%. 

I can't get coloring to work if a value is negative, as soon as it goes below 0 the coloring disappears, no matter what values I configure (or at least the ones I have tested). Should it work or am I missing something? For us it would be cool because in some cases negative change is actually positive, so it would be nice make that more understandable :)

Best
Peter

**Comment by torkelo** [comment]
you seem to be right :(

**Comment by rvdheijden** [comment]
Encountered similar problem here, and while upgraded code to solve this would be great, for now we tackled it by setting the base/no-change value to 100% rather then 0.

**Comment by clongbottom** [comment]
+1. There are other use cases for this too with real units, i.e. temperature. Would be great if any number of negative colour points could be specified.

**Comment by arsibaba** [comment]
any update on this? we have a use case here too (company CTC which cannot be done against base 100). We also see no color once the number goes negative.

**Comment by bergquist** [comment]
@arsibaba this should be solved since the release of grafana 3.0.0

**Comment by domoticom** [comment]
any update ? We monitor some freezers (-80 celcius). I would like to show a Gauge with thresholds, but becaue of the negative value i get this error: 
Failed to execute 'arc' on 'CanvasRenderingContext2D': The radius provided (-3.62625) is negative.

PS: as a workaround: is there an option to get an absolute value in a query (like abs() ) ?

Thnx!

**Comment by sslupsky** [comment]
See issue #5234.  There is a work around for integer values.
