### ISSUE TITLE
Grafana : Influx : Flux Datasource : Not returning more than 10 rows

### ISSUE THREAD

**Issue by nachopv** [grafana/grafana#32496]
[dashboard_flux_issue.txt](https://github.com/grafana/grafana/files/6229038/dashboard_flux_issue.txt)

**What happened**:
Flux Datasource not returning more than 10 series despite the database contains more records.
This is happening no matter the panel we use
I use singlestat gruped by tag as an example

**What you expected to happen**:
We would expect fluxql to return as many series as influxql
We have tested on influx directly and  the issue does not happen so the problem is at grafana datasource level

**How to reproduce it (as minimally and precisely as possible)**:

InfluxQL Query
`SELECT sum("Counter") 
FROM "four_weeks"."MEDPAGFA.EFT_Transaction" 
WHERE $timeFilter GROUP BY time($__interval), "Country" fill(none)`

FluxQL Query
`from(bucket: "app_metrics/four_weeks")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "MEDPAGFA.EFT_Transaction")
  |> filter(fn: (r) => r["_field"] == "Counter")
  |> group(columns: ["Country"])
  |> sum()`

**Anything else we need to know?**:

Screenshot and dashboard attached

![image](https://user-images.githubusercontent.com/70150083/112989227-f948ff80-9164-11eb-9d67-2481674b2c42.png)

**Environment**:
- Grafana version: OSS 7.1.3
- Data source type & version: Flux QL ( 1.8 )
- OS Grafana is installed on: RHEL7
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others:

**Comment by Elfo404** [comment]
This was fixed in https://github.com/grafana/grafana/pull/26746 and release in `7.2.0` where the limit was risen to 50.

**Comment by nachopv** [comment]
Hi @Elfo404  
Just to understand it , whats the intention of having such limit on flux datasource but not on influxql datasource?
Is it configurable in further versions when needed?

**Comment by Elfo404** [comment]
hi @nachopv actually I should have provided more info before closing, sorry! 🙏 
in that PR (7.2.0) the limit was set (hardcoded to 50).

that hardcoded limit was then removed in https://github.com/grafana/grafana/pull/31025 which was released in Grafana 7.4.1 so from 7.4.1 version this is configurable on the query level.

Hope this helps!
