### ISSUE TITLE
Add ECS to Cloudwatch Source

### ISSUE THREAD

**Issue by hrzbrg** [grafana/grafana#3251]
Hi,

I saw that in the definition of Cloudwatch metrics ECS is missing
(https://github.com/grafana/grafana/blob/master/pkg/api/cloudwatch/metrics.go)

It would be really awesome to have this included.

Regards
Seb.

**Comment by mtanda** [comment]
As you may know, the definition is only used for suggestion in query editor.
You can make graph for ECS service without the definition.
And, adding the definition is not so difficult, you can try :-)

**Comment by hrzbrg** [comment]
Oh, well I didn't know that :/
But I managed to get it done. Thanks for the hint anyways :)
