### ISSUE TITLE
Inline code text in panel legend wrongly shows as block element

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#32521]
**What happened**:

Writing a panel legend that includes `inline` code where a word is surrounded by a single backtick within a sentence. 

<img width="1174" alt="Screenshot 2021-03-30 at 21 09 19" src="https://user-images.githubusercontent.com/156867/113050354-a55a0d00-919c-11eb-8c8b-ed363cf75eb2.png">

**What you expected to happen**:

For it to render as an inline style, given that it did not use `<div>`, or `<pre>` or three-backtics.

I believe this is a regression, but I don't remember exactly when. Possibly since earlier in Grafana v7.x or maybe v6.x.

**Environment**:
- Grafana version: Grafana v7.4.2
- Example in the first panel on <https://grafana.wikimedia.org/d/000000580/apache-backend-timing>

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/32405
