### ISSUE TITLE
Grafana Alert image not shown even Direct link rendered image works

### ISSUE THREAD

**Issue by hyeyeonCho** [grafana/grafana#32525]
I am trying to get alert feature in Grafana, I think I am almost there but not yet. 

I managed to get image when I click share>Direct link rendered image but when I receive alert email,  images are not shown. 
Is there any idea that I should do to see the image in the email?

**Comment by torkelo** [comment]
Make sure the notification channel setting has "Include Image" checked in the settings. 

Turn on debug loggingg and check the grafana server logs during the time when notification was sent

**Comment by hyeyeonCho** [comment]
@torkelo Hello, It's not working even if I turn on "Include image" in the setting. Even Grafana logo is not shown in the email.
