### ISSUE TITLE
Legend for hostname tooltip wrong

### ISSUE THREAD

**Issue by ealmonte32** [grafana/grafana#32522]
Just a minor thing, when the user places mouse over tooltip it says that for hostname to type `{{hostname}}` but doing this does not replace the label with hostname/agent name, but using `{{agent_hostname}}` does properly.

![image](https://user-images.githubusercontent.com/24350198/113052449-256c7c80-9175-11eb-92f5-68ddca9848ad.png)

**Environment**:
- Grafana version: v7.5.1
- User OS & Browser: Chromium

**Comment by torkelo** [comment]
it depends on your label name, you have a label named agent_hostname so then that is what you have to type
