### ISSUE TITLE
Cannot connect to InfluxDB2 with flux

### ISSUE THREAD

**Issue by CanuckMarc** [grafana/grafana#32529]
**What happened**: Cannot Connect to InfluxDB v2 with Flux

**What you expected to happen**: Connect as it has previously with the same configuration

**How to reproduce it (as minimally and precisely as possible)**:  Create influxdb v2 flux datasource, then enter org, bucket, token, and url details.

**Anything else we need to know?**:  I tested the connection with Node-red and it was successful with the same details.  I also tried using the organization ID instead of the organization name (no difference)

**Environment**:
- Grafana version: 7.2.0
- Data source type & version:  influxdb2  https://us-west-2-1.aws.cloud2.influxdata.com
- OS Grafana is installed on: unsure
- User OS & Browser:  Ubuntu 20.04 & Chrome
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Can you try latest Grafana version (7.5) we have made many updates to InfluxDB to fix connection issues
