### ISSUE TITLE
Loki Alert Skip TLS Verify not honored

### ISSUE THREAD

**Issue by edthamm** [grafana/grafana#32533]
**What happened**:
When configuring an alarm for a Loki datasource I get the following error:
`
 tsdb.HandleRequest() error Get "https://REDACTED/loki/api/v1/query_range?direction=BACKWARD&end=1617171150252446755&interval=1&limit=1000&query=absent_over_time%28%7BREDACTED%3D%22REDACTED%22%2CREDACTED%3D%22REDACTED%22%7D%5B15m%5D%29&start=1617170850252446755&step=1": x509: certificate is valid for REDACTED, not REDACTED`

**What you expected to happen**:

The alert to correctly evaluate.

**How to reproduce it (as minimally and precisely as possible)**:
- Setup Loki with an SSL Certificate that will fail to verify
- Configure the datasource to skip tls verify
- Configure a graph with an alert using loki as datasource
- Test the alert

**Anything else we need to know?**:

The graph draws just fine. In fact any graph draws just fine. It seems to me that the alerting logic does not honor the 'Skip TLS Verify' setting.

**Environment**:
- Grafana version: 7.5.0
- Data source type & version: Loki 
- OS Grafana is installed on: Debian

**Comment by marefr** [comment]
Seems like you have to use the tls config of the loki client:
![image](https://user-images.githubusercontent.com/1668778/114165115-61010680-992c-11eb-8435-b9a41da2e25c.png)

Unfortunately doesn't look like the loki client supports overriding the transport like for example prometheus client supports https://github.com/grafana/grafana/blob/c9e5088e8bca1fe9c3727cb3b52a9fcd488cd12a/pkg/tsdb/prometheus/prometheus.go#L67 

Overriding the transport would apply the TLSConfig to the http client, ref https://github.com/grafana/grafana/blob/c9e5088e8bca1fe9c3727cb3b52a9fcd488cd12a/pkg/models/datasource_cache.go#L229

**Comment by marefr** [comment]
Maybe an issue to raise in the loki repository?

**Comment by edthamm** [comment]
@marefr should I bring it up over there or will one of you take this further?

**Comment by marefr** [comment]
@edthamm we'll talk to them

**Comment by marefr** [comment]
Ref https://github.com/grafana/loki/issues/3608

Seems like a short term workaround may be necessary to resolve this issue.

**Comment by marefr** [comment]
@ivanahuckova think fixing this using the existing exposed [config.TLSConfig](https://github.com/grafana/loki/blob/72dcda165a41e3d71127ac801f9e5260e1cc82a1/pkg/logcli/client/client.go#L48) could make sense short term since Loki issue might not be resolved in a while. Leave it up to you to prioritize
