### ISSUE TITLE
Add query to existing graph panel programmatically

### ISSUE THREAD

**Issue by spynode** [grafana/grafana#3255]
I am trying to create a dashboard with 2 panels. One is custom panel with metric list, where individual items are links. Second panel is Graph. What Grafana JS functions I should use if I want to make queries added or removed from Graph panel upon clicking on links in the custom panel in real time? Is there such possibility in current Grafana JS API to add/remove  query to existing Graph panel on the fly? I am using KairosDB backend plugin. Thanks a lot.

**Comment by torkelo** [comment]
you can update the dashboard model (json) and add queries to the other panel.
