### ISSUE TITLE
Migrating Grafana Dashboard/Graphs

### ISSUE THREAD

**Issue by ravibhooshan** [grafana/grafana#3259]
Hi,
I am using Grafana 2.0.1 with sqllite3 database  for my Graphite setup. I have around 200 graphs.
Now I am planning to migrate grafana from sqlite to mysql, but having issue in migrating all graphs.
I don't want to ask users to use export/import for their each and every graph. 
Other option i am think is converting sqlite database into mysql, in this I wanted to know that will this migrate all dashboard/graphs also.
Please suggest if there is any other easy method to migrate all Dashboards/Graphs from sqlite based Grafana to mysql based grafana.

Thanks,
Ravi Bhushan

**Comment by torkelo** [comment]
migration scripts for moving from sqlite3 to postgres is not something that exist yet :( 

You might be able to use this tool that uses the HTTP api to move dashboards, 
https://github.com/m110/grafcli

**Comment by ravibhooshan** [comment]
Thanks Torkelo.
I was looking for sqllite3 to mysql not postgres.

**Comment by ravibhooshan** [comment]
I finally completed sqlite to mysql migration with all Dashboards. I used method of exporting tables and updating syntax to comply with mysql and then recreated all tables into blank grafna database. My be its not best methos to do, but with my limited knowledge on development, i fond it very simple and easy.
