### ISSUE TITLE
Unable to import dashboard from a datasource

### ISSUE THREAD

**Issue by sbouchex** [grafana/grafana#32599]
**What happened**: I have installed the GitHub datasource and once instance, I try to import the provided dashboard from the user interface but the "Dashboard not found" message is displayed and the dashboard is not imported.

![image](https://user-images.githubusercontent.com/2684878/113297782-57a7e680-92fb-11eb-962b-dbe7ddf2f57c.png)

**What you expected to happen**:
The dashboard should be imported.

**How to reproduce it (as minimally and precisely as possible)**:
- Install the GitHub datasource
- Import the dashboard

**Anything else we need to know?**: I have entered the bug in the grafana application as the issue also occurs on other data source.

The grafana server logs prints:
`t=2021-04-01T15:03:29+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/dashboards/import status=404 remote_addr=10.1.12.145 time_ms=3 size=54 referer=http://hadoop1:3000/datasources/edit/51/dashboards`

**status is 404**

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: GitHub datasource
- OS Grafana is installed on: Linux & Windows
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
fix incoming https://github.com/grafana/github-datasource/pull/120

**Comment by sbouchex** [comment]
@torkelo I'm not sure that the fix is the right one. As I do have another plugin (home made) that expose "dashboards/...." (without the ./ at the beginning of the path and the issue is the same.
