### ISSUE TITLE
Multi-Select option failed working with Prometheus datasource

### ISSUE THREAD

**Issue by tj13** [grafana/grafana#3260]
template variable value is passed  as a whole parameter during the prometheus query. 
<img width="666" alt="2015-11-17 3 20 58" src="https://cloud.githubusercontent.com/assets/14867953/11204969/d4f542f4-8d3e-11e5-9b08-4d571e67c2bf.png">

query string parameters showing as below:
<img width="578" alt="2015-11-17 3 11 10" src="https://cloud.githubusercontent.com/assets/14867953/11204829/8a1b7380-8d3d-11e5-9821-203f3a6a89ea.png">

single select works fine!

<img width="526" alt="2015-11-17 3 15 19" src="https://cloud.githubusercontent.com/assets/14867953/11204936/73eae0ea-8d3e-11e5-9cf1-bce89fc112b3.png">

**Comment by torkelo** [comment]
do you know the syntax for multi values for prometheus? Grafana supports multiple syntax for multiple values (you have selected glob, which prometheus does not seem to support), you find the options in the template variable options view. Multi format (and All format)

**Comment by Rucknar** [comment]
@tj13 Not sure if you got to the bottom of this but if you use the pipe setting instead of glob and set prometheus to use `=~` instead of just `=` it should work fine.

**Comment by tj13** [comment]
@Rucknar thanks for your help. i've already chose add an influxdb, i thinks it's easier to achieve Multi-Select function by add it as the remote storage of prometheus.
