### ISSUE TITLE
Stack grouped series coming from elasitcsearch 

### ISSUE THREAD

**Issue by sfthomas** [grafana/grafana#3261]
If I generate multiple series by using the group function in a query, then I cannot get those series to stack on each other - they just simply hide one another, even if I set the time grouping interval to a fixed value. What I could do is to blow those out to separate quesries, because then they stack well, but that's undesirable. Is there a way to achieve this without the workaround, or is this missing functionality?

![image](https://cloud.githubusercontent.com/assets/1913456/11206010/73074ce0-8d0c-11e5-8d1a-b239b65e2db7.png)

**Comment by torkelo** [comment]
could you try downloading a pre release build for 2.6? I think this has been fixed http://grafana.org/download/builds.html

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3222

**Comment by sfthomas** [comment]
Tried the latest 2.6 just now, but that does not even draw the bars. I can only see something from ES if I use lines or dots.

![image](https://cloud.githubusercontent.com/assets/1913456/11214334/f3c48d00-8d40-11e5-92b6-fd97093ba388.png)

**Comment by torkelo** [comment]
interval 10s must be to low interval. Maybe change null point mode to "null as zero" (in display options)

**Comment by sfthomas** [comment]
Tried a lot of combinations of null point mode & interval, but none of them seems so make the metrics visible. What worked was if I sent in even more events - then the bars showed up.

**Comment by sfthomas** [comment]
Ok, I found the reason for the original problem - I had Negative-Y transform on some of the metrics, and that messed up the stacking. When I removed those transforms, stacking works perfectly inside and across metrics, in 2.5 too.

**Comment by torkelo** [comment]
@sfthomas a great that you managed to get it to work :)
