### ISSUE TITLE
Grafana 2.6-pre1 ES Single Stat  Error

### ISSUE THREAD

**Issue by dahendel** [grafana/grafana#3262]
I created a dashboard in 2.5 that queried ES for single stat panels. In the 2.6 pre1 release I get an error for the same dashboard. Screenshots below.

I am using packetbeat from elasticsearch to gather the metrics.
https://www.elastic.co/products/beats/packetbeat

**2.5 Screenshots:
![25-grafana-es](https://cloud.githubusercontent.com/assets/11720061/11215554/7273ab48-8d0c-11e5-8a23-df52513c2ceb.PNG)

![25-grafana-es-query](https://cloud.githubusercontent.com/assets/11720061/11215654/f882528e-8d0c-11e5-91ec-2d7aa8763aab.PNG

**2.6 Screenshots:
![26-grafana-es-query](https://cloud.githubusercontent.com/assets/11720061/11215648/f0626828-8d0c-11e5-8439-706d35fbf85d.PNG)
![25-grafana-es-error](https://cloud.githubusercontent.com/assets/11720061/11215822/c51772f2-8d0d-11e5-86dd-7bda0793619e.PNG)

**Comment by torkelo** [comment]
This was due to a bug that was recently introduced and fixed 
https://github.com/grafana/grafana/commit/2cbc62d6c0a8b35f427a29db3ed214461829f345

will publish new nightly builds of 2.6 pre1 with the fix now, should be up in in a minute

**Comment by dahendel** [comment]
Thanks for quick response.
