### ISSUE TITLE
Datasource variable, Instance name filter does not support default in regex.

### ISSUE THREAD

**Issue by dessen-xu** [grafana/grafana#32623]
**What happened**:

Datasource variable, does not support default in Instance name filter filed.

![image](https://user-images.githubusercontent.com/41524013/113374291-61832580-939f-11eb-8381-379c361eb6c0.png)

**What you expected to happen**:

It is good in grafana7.3.x

![image](https://user-images.githubusercontent.com/41524013/113374546-ef5f1080-939f-11eb-8462-fd6e1dad0f3d.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.x
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: mac os
- Grafana plugins:
- Others:

**Comment by thisisobate** [comment]
fixed! #32625
