### ISSUE TITLE
Anonymous users cannot share a snapshot even if they have full access

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#32636]
This is a re-open of #32585 That I believe was closed pre-maturly.
I belive the issue with the line:
https://github.com/grafana/grafana/blob/master/public/app/features/dashboard/components/ShareModal/ShareModal.tsx#L35

Pleaes re-open the original issue and we can close this one

**Comment by marefr** [comment]
Please don't open duplicate issues. We'll reopen the other issue instead
