### ISSUE TITLE
Table panel JSON Data, support 2 levels deep json properties

### ISSUE THREAD

**Issue by dahendel** [grafana/grafana#3263]
While creating a table in grafana 2.6 I noticed some fields were missing. Again, I am pulling from ES1.7 and the data is generated from packetbeat, specifically the fields mentioned in the link below.
https://www.elastic.co/guide/en/beats/packetbeat/current/exported-fields.html#exported-fields-http

I am trying to make a table to go along with http error codes panel.
![missing fields](https://cloud.githubusercontent.com/assets/11720061/11216435/c3afcdd0-8d10-11e5-9f66-6eb8e2de3218.PNG)

Thanks of this great feature!

**Comment by torkelo** [comment]
where are you missing this? In the table panel Fields selection or in the query editor? Those properties looks two levels deep, I think the query editor field selection only go one or two levels deep and the json field selection in the table panel currently only allow top level json properties.

**Comment by torkelo** [comment]
Support for more deep json documents will be added shortly

**Comment by dahendel** [comment]
![image](https://cloud.githubusercontent.com/assets/11720061/11218817/c39b86ca-8d1c-11e5-850e-3780d1443e61.png)
