### ISSUE TITLE
Documentation link is broken in a warning when hitting AWS Cloudwatch request limit

### ISSUE THREAD

**Issue by IrinaTerlizhenko** [grafana/grafana#32630]
**What happened**: AWS Cloudwatch request limit was exceeded and Grafana displayed a warning with a broken link to documentation. The link ("documentation" on the attached image below) leads to https://grafana.com/docs/grafana/latest/features/datasources/cloudwatch/#service-quotas that returns HTTP 404.

![image](https://user-images.githubusercontent.com/17529395/113403761-d65e5b80-93af-11eb-90de-ec9eac86899f.png)

**What you expected to happen**: Documentation link leads to an existing page.

**How to reproduce it (as minimally and precisely as possible)**: Set minimal AWS Cloudwatch GetMetricData limit and send enough requests to face AWS throttling. Refresh AWS Cloudwatch panels in Grafana.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.5 (11f305f88a)
- Data source type & version: AWS CloudWatch, version unknown
- OS Grafana is installed on: unknown
- User OS & Browser: Windows 10 Enterprise Version 1909 + Google Chrome Version 89.0.4389.90 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Hello @IrinaTerlizhenko, thanks for spotting this!
