### ISSUE TITLE
Pie Chart: Data links do not seem to work

### ISSUE THREAD

**Issue by slim-bean** [grafana/grafana#32637]
**What happened**:

Trying to add a data link to a pie chart and it doesn't seem to be working.

I can't click anywhere on either the pie chart or the legend to use my link

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

My source for data is another panel on the dashboard, not sure if this could have any impact

![image](https://user-images.githubusercontent.com/10332331/113414392-e4e64c00-938a-11eb-89a0-e9263c14833f.png)

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: Prometheus (technically it's Loki added as a prometheus datasource)
- OS Grafana is installed on: Raspbian 64bit (arm)
- User OS & Browser: Windows/Firefox
- Grafana plugins:
- Others:

**Comment by oscarkilhed** [comment]
This didn't make it into beta, but it's fixed by #31642
