### ISSUE TITLE
Broken image links in some of the documentation

### ISSUE THREAD

**Issue by hc8756** [grafana/grafana#32647]
**What happened**:
I was looking through the files in docs/sources and found that a lot of the image links lead to GitHub's 404 page.

**What you expected to happen**:
I expected to be taken to an image supporting the documentation.

**How to reproduce it (as minimally and precisely as possible)**:
Go to files such as add-notification-template.md or dashboard-folder-permissions.md and try to click on the links.

**Environment**:
- Grafana version: 7.5.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Hello @hc8756, Images are hosted on a separate repo which is the source for https://grafana.com/docs/. 
The image URLs are not supposed to resolve to anything inside this repo.
