### ISSUE TITLE
Drill Down Pop Up Position

### ISSUE THREAD

**Issue by kierangirvan** [grafana/grafana#3264]
If you have a single stat panel on the far right hand side of the screen with a drill down link, the popup indicating the drill down dashboard name prevents the user from clicking.

I've tested a few browsers and appears to only affect Chrome (our version is 43.0.2357.81 m).

The cursor in this screen print is to the right hand side of the browser which results in the label popping up onto of the cursor.

![image](https://cloud.githubusercontent.com/assets/1891193/11218254/04bf4928-8d4c-11e5-909f-945ff31c58b0.png)

**Comment by mattttt** [comment]
@kierangirvan Trying to replicate, but been unable so far. Any chance you can share a snapshot of the dashboard?

**Comment by kierangirvan** [comment]
@mattttt 

Please find attached 2 json exports, 1 of which is a parent dashboard view which contains 12 single stats with a drill down link to a chill dashboard view (second dashboard in zip).  Within Chrome, I'm unable to select (therefore navigating to the drill down dashboard) on the 12th single stat on the parent view due to the auto-hover text that appears.

[example_dashboards.zip](https://github.com/grafana/grafana/files/88628/example_dashboards.zip)

Hopefully this is what you were looking for.

**Comment by daniellee** [comment]
Just tested this and it seems to work now. The text is above the drill down link:

![image](https://cloud.githubusercontent.com/assets/434655/25389095/fa952f18-29cf-11e7-9e77-305dee8abc79.png)
