### ISSUE TITLE
Deleted users not removed from user table

### ISSUE THREAD

**Issue by drawks** [grafana/grafana#3265]
When marking an account as deleted in the UI the user's row is not removed from the user table. This can cause a problem in that the any of the deleted user's data which are constrained as unique by the schema (email, username, etc) effectively blacklists that data from ever being used again.

**Comment by torkelo** [comment]
what version of Grafana are you using? Deleting a user in 2.5 works as expected and removes everything.

**Comment by drawks** [comment]
2.5 configured with ldap for authentication. Steps to reproduce:
1.) log in as ldap user
2.) log out
3.) log in as admin
4.) delete user from step 1
5.) logout
6.) attempt to login as user from step one and receive an error about the email address conflict

**Comment by utkarshcmu** [comment]
@drawks I am not able to reproduce it after following the steps above. It works perfectly to me. I am using LDAP as well.

**Comment by torkelo** [comment]
@drawks what is you [users] auto_assign_org config option? (in grafana.ini)

**Comment by ScottBrenner** [comment]
Seeing this issue as well, any resolution?

**Comment by bergquist** [comment]
@ScottBrenner https://github.com/grafana/grafana/issues/11573

**Comment by venkatamatta** [comment]
not able to delete the users permanently from Grafana v5.2.4, please let me know how to do it and i need to validate with LDAP auth

**Comment by yinyu985** [comment]
I deleted an ldap user user1 in org1 through admin, and then set the auto_assign_org config option to another org2 (I think that when I log in user again, I should log in to the new organization), but when I log in user1 again, there is no In the other organization org2, is this not deleting user1's information in the database?
