### ISSUE TITLE
MSSQL: panic: not implemented makeGoLangScanType for type 240 (Grafana v7.5.2)

### ISSUE THREAD

**Issue by hairyhenderson** [grafana/grafana#32653]
**What happened**:

```
panic: not implemented makeGoLangScanType for type 240
goroutine 561 [running]:
github.com/denisenkom/go-mssqldb.makeGoLangScanType(0xf0, 0xffff, 0x0, 0xc00103c000, 0xffff, 0xffff, 0x0, 0xc000c856d0, 0x5, 0xc000c856e6, ...)
	/root/go/pkg/mod/github.com/grafana/go-mssqldb@v0.0.0-20210326084033-d0ce3c521036/types.go:1115 +0x1191
github.com/denisenkom/go-mssqldb.(*Rows).ColumnTypeScanType(0xc00104c000, 0x6, 0xc00104c000, 0x7ff8b190c978)
	/root/go/pkg/mod/github.com/grafana/go-mssqldb@v0.0.0-20210326084033-d0ce3c521036/mssql.go:750 +0x9c
database/sql.rowsColumnInfoSetupConnLocked(0x2c448e8, 0xc00104c000, 0x7ff8dc94b108, 0x30, 0xc00102eed0)
	/usr/local/go/src/database/sql/sql.go:3043 +0x13d
database/sql.(*Rows).ColumnTypes(0xc000335700, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/go/src/database/sql/sql.go:2970 +0x1a8
github.com/grafana/grafana/pkg/tsdb/sqleng.(*sqlQueryEndpoint).transformToTable(0xc0007fa930, 0xc000459f80, 0xc00102d810, 0xc000335680, 0xc000459f40, 0x5, 0x0)
	/drone/src/pkg/tsdb/sqleng/sql_engine.go:254 +0x24c
github.com/grafana/grafana/pkg/tsdb/sqleng.(*sqlQueryEndpoint).Query.func1(0xc000c85500, 0xc0007fa930, 0xc000459f40, 0xc0007fcc00, 0xfb, 0xc000459f80, 0xc000335680)
	/drone/src/pkg/tsdb/sqleng/sql_engine.go:192 +0x2f9
created by github.com/grafana/grafana/pkg/tsdb/sqleng.(*sqlQueryEndpoint).Query
	/drone/src/pkg/tsdb/sqleng/sql_engine.go:165 +0x45c
```

**What you expected to happen**:

No panic 😉

**How to reproduce it (as minimally and precisely as possible)**:

Uncertain!

**Anything else we need to know?**:

This is similar to https://github.com/grafana/grafana/issues/32327, but in different code.

The panic is coming from https://github.com/grafana/go-mssqldb/blob/master/types.go#L1117. I'm not sure how to solve it.

As a general comment, the `go-mssqldb` module has a _lot_ of `panic`s which should IMO instead be errors. This sort of thing should surface as an error to the end-user at worst, not bring down the entire process.

_(See also https://raintank-corp.slack.com/archives/C67A7JM3K/p1617387926224800 on the Grafana Labs Internal Slack instance)_

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: MS SQL Server (assumed)
- OS Grafana is installed on: Grafana Cloud

**Comment by hairyhenderson** [comment]
cc @marefr @aknuds1 @hugohaggmark since you were involved with #32327/#32347 😅

**Comment by dsotirakis** [comment]
Hello @hairyhenderson, thanks for the heads up - I had a quick look and I can see that the 

```
panic: not implemented makeGoLangScanType for type 240
```

error we are getting, refers to a type 240 (`0xf0`), which is a UDT field type (User-Defined Types). In the aforementioned `switch-case` condition in the code [here](https://github.com/grafana/go-mssqldb/blob/master/types.go#L1117), I can see that there's no case for UDT (`typeUdt` exists though). A potential solution should be to add a case like:

```
case typeUdt:
		return reflect.TypeOf(nil)
```

Not really sure if `nil` is the right thing to put there, but there's no information about the schema.

Also thought about:

```
case typeUdt:
		return reflect.TypeOf(make(map[string]interface{}, 0))
```

but again not entirely sure...

**Comment by hairyhenderson** [comment]
Thanks @dsotirakis - I'm not sure either what the right approach is (maybe we need to raise the issue upstream?).

Even if there's no clear way to support `typeUdt` it would be best if an error like this didn't result in a panic that takes down grafana-server. I wonder if it's possible to wrap calls to this library with a `recover` so that the error can be surfaced to the user?

**Comment by marefr** [comment]
Strange that it did take down grafana-server. We have recovery in place, but I guess since this SQL queries executing in their own goroutine, we need to have recovery in place there as well. Ref: https://github.com/grafana/grafana/blob/61d3900b54ad7af1aa405e09c697b235ed732f8a/pkg/tsdb/sqleng/sql_engine.go#L154

**Comment by hairyhenderson** [comment]
From the affected customer it sounds like the specific type that caused this was `geography`. They managed to work around this by using lat/long directly.

Note that there's an issue upstream in `go-mssqldb` for this sort of thing: https://github.com/denisenkom/go-mssqldb/issues/61

**Comment by datahookinc** [comment]
Same issue. Will implement a work around locally, but would be great to see this natively supported.

**Comment by mdvictor** [comment]
We are still in the process of investigating this and finding a proper fix for it.

**Comment by mdvictor** [comment]
This might potentially be fixed after the migration to the `microsoft/go-mssqldb` driver, which will be done by this [PR](https://github.com/grafana/grafana/pull/73597)

**Comment by alyssabull** [comment]
Closed with fix https://github.com/grafana/grafana/pull/73597.
