### ISSUE TITLE
Explore: Use fixed width for button "Run query"

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#32655]
**What would you like to be added**:

Please consider changing the width of the "Run query" / "Cancel" button to fixed instead of text-length depended, so it is always the same size.

**Why is this needed**:
When the query is executing, the elements to the left site are "wobbling" around, which is at least unpleasant to look at 😄 
If the query takes a second or if you click fast enough, you might actually misclick a wrong button, 

e.g. "Copy shortened link" instead of "time range backward", please see gif

![G2PJ5PWgY1](https://user-images.githubusercontent.com/33002073/113452704-d2a8f400-9404-11eb-8a7a-83d41303bc90.gif)

**Comment by BLasan** [comment]
@connorlindsey Can I work on this?

**Comment by connorlindsey** [comment]
@BLasan Absolutely, PRs are always welcome!

**Comment by connorlindsey** [comment]
Hi @BLasan, how's it going with this issue? Is there anything I can do to help?

**Comment by BLasan** [comment]
Hi, will be taking a look today. If any need, I'll let you know. Thanks :)

**Comment by BLasan** [comment]
@connorlindsey Sorry for the late replies. Does the relevant file locate under the directory "grafana/packages/grafana-ui/src/components" ?

**Comment by connorlindsey** [comment]
@BLasan The components are ExploreToolbar > RunButton > RefreshPicker > ToolbarButton (where > shows a child component). ExploreToolbar and RunButton are in `public/app/features/explore`. RefreshPicker and ToolbarButton are in `packages/grafana-ui/src/components`.

**Comment by glintik** [comment]
Hi @connorlindsey,

As I can see, this bug is months old, but still annoying and I would like to help with the fix. It fixes button width for large(with text) and small screens(icon only).

**Comment by connorlindsey** [comment]
Awesome, thank you for opening that PR @glintik! We'll get that reviewed soon
