### ISSUE TITLE
Incorrect query sent to Elasticsearch when using Text box variable and text box is empty

### ISSUE THREAD

**Issue by dirkallaert** [grafana/grafana#32662]
What happened:
When a text box field variable (via ${textbox:raw}) is added to a Lucene query, the value should be replaced with a wildcard when the text field is empty. This is a variation of issue #17442.

What you expected to happen:
An empty query should always send an "" to Elasticsearch. This can be observed working properly when using the Query field directly. When the Query field is empty, Grafana sends an "" for the Elasticsearch Query_String/Query setting, which results in all documents being returned (no filter). If a Textbox variable is being used to set the Query field, and it is also empty, the same behavior should occur.

How to reproduce it (as minimally and precisely as possible):
Add a Text Box variable to a Dashboard (name it 'lucene'), with a Table, using an Elasticsearch 6+ Datasource that has valid documents that will match your current Time Range.

In the query field, set a search string with a few conditions that still return documents.
e.g. condition1 AND condition2
With a refresh, documents will be returned. 

Now update the Query field to:
 condition1 AND condition2 AND ${lucene:raw}. 
With the Text Box empty, refresh your dashboard. Instead of receiving the same results, no results will be received. The Query Inspector shows that the Elasticsearch query sent is:
condition1 AND condition2 AND

With an asterisk wildcard '*' in the text box, refresh the dashboard. Now the results will be shown again.
 The Query Inspector shows that the Elasticsearch query sent is:
condition1 AND condition2 AND *

Anything else we need to know?:
Workaround is to set '*' as default value, but would be more user-friendly to send correct query when text box is empty and match Kibana behaviour.

Environment:
Grafana version: 7.5
Data source type & version: Elasticsearch 6+
OS Grafana is installed on: CentOS 7
User OS & Browser: NA
Grafana plugins: NA

![image](https://user-images.githubusercontent.com/29406536/113478383-c9616b00-9488-11eb-876c-c9ecdecac862.png)

**Comment by MeetzhDing** [comment]
When using textbox variable, `set value = *`
${text}  == *
${text:lucene} = \*

Why lucene replace result is `\*` ? 
In Query Variable, Custom all value `* `will become `*`
But In TextBox, `*` will be translated to `\*`

eg:
`key: ${textbox:lucene} AND key2: ${query:lucene}`  should be `key:* AND key2:*`

**Comment by svennergr** [comment]
Hi @dirkallaert and @MeetzhDing,

actually this currently works as designed. Lucene formatting does not support any special characters.
For those use cases you could use the `raw`-formatter. If you wish this should become a new feature, feel free to raise a new [feature request in a GitHub discussion](https://github.com/grafana/grafana/discussions/categories/observability).

Thanks!
