### ISSUE TITLE
Any plan on notifier plugins?

### ISSUE THREAD

**Issue by yasharne** [grafana/grafana#32669]
**What would you like to be added**:
I had a PR about 4 months ago on adding the matrix support to the notifiers (#29931). The PR closed as the grafana team was planning notifier plugins but there nothing announced yet

**Why is this needed**:
In our scenario, as we cannot send the notifications directly to the matrix server, we have to use a third-party plugin on the matrix server to accept slack-styled messages and show them in matrix channels, but it fails some times and we miss our important alerts

**Comment by aknuds1** [comment]
Truly sorry it's taking so long to implement notifier plugins, but we're in the middle of a series of much needed deep refactorings to Grafana and these take a while to finish unfortunately. We hope to have these done in time for Grafana 8, and after that it should be much easier to continue implementing such features as notifiers as plugins. Thanks for your understanding.

**Comment by torkelo** [comment]
yes, https://github.com/grafana/grafana/issues/16004 

but no ETA (not on any planned backlog yet)
