### ISSUE TITLE
hyphen with ES templating

### ISSUE THREAD

**Issue by nanowish** [grafana/grafana#3266]
With templated variable with ES datasource, I get truncated datas when they contains hyphen. Data is domain name with hyphen, ex: www.my-domain.com, is truncated to www.my in grafana variable

![capture du 2015-11-17 18-38-05](https://cloud.githubusercontent.com/assets/2698772/11219397/91c8de0c-8d5a-11e5-951c-b7cbdb75517a.png)

In Kibana/ES term domain contains correct data with hyphen.

**Comment by torkelo** [comment]
Hyphens works fine with Elasticsearch, 
![image](https://cloud.githubusercontent.com/assets/10999/11244692/32fa1278-8e0f-11e5-985d-8c1218522a96.png)

It is your regex probably that is filtering them out
