### ISSUE TITLE
Grafana Flux query causes influxdb OOM crash

### ISSUE THREAD

**Issue by holmesb** [grafana/grafana#32660]
**What happened**:
Created Flux query including line:
`|> aggregateWindow(every: v.windowPeriod, fn: mean)`

**What you expected to happen**:
Panel displays query output.  Instead I see:
![image](https://user-images.githubusercontent.com/5072156/113474661-2a794680-9469-11eb-8089-eebe5c1b24c1.png)
And I notice Influxdb pod has out-of-memory crashed:
```
user@~/ $ kubectl get pod influxdb  -w
NAME                        READY   STATUS    RESTARTS   AGE
influxdb   1/1     Running   3          8d
influxdb   0/1     OOMKilled   3          8d
influxdb   0/1     CrashLoopBackOff   3          8d
```

**Anything else we need to know?**:
Same query in Influxdb webui works fine.  If I remove the `aggregateWindow` line, it works fine from Grafana.  Influxdb pod generally uses < 25% of its memory limit.

**Environment**:
- Grafana version: v7.4.3
- Data source type & version: Influxdb (flux)
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome

**Comment by aocenas** [comment]
@holmesb Can you post the whole query that you are trying. Are you using some variables from grafana in that query?

**Comment by holmesb** [comment]
I rewrote the entire query and now I can't reproduce this, sorry I can't be more help if someone else comes across this.
