### ISSUE TITLE
Mappings are not applied for value with custom time format unit

### ISSUE THREAD

**Issue by jkmnt** [grafana/grafana#32663]
**What happened**:

Custom unit 'time: YY-MM-DD' was applied to the metric with the numeric value 0.
The result is '70-01-01' just like expected. The mapping '0'->'Never' was created but it was ignored.
The mapping '70-01-01'->'Never' was ignored too. The displayed string is always '70-01-01'.

**What you expected to happen**:

Mapping should be applied, replacing the value with the provided string. Preferably before the time formatting
AKA '0'->'Never'

**Anything else we need to know?**:

If unit is set to 'Datetime local', mapping '01/01/1970, 03:00:00 AM'->'Never' works (but '0'->'Never' is not).
Visualization: Table, Stat

**Environment**:
- Grafana version:
Grafana v7.4.1 (07649d1313)

**Comment by kaydelaney** [comment]
Seems to be fixed in master.
