### ISSUE TITLE
Improve setup validation in Grafana Tempo datasource

### ISSUE THREAD

**Issue by ad-m** [grafana/grafana#32677]
**What would you like to be added**:

I would like notice that on setup tests of datasources does not verify datasource really. Backends might fail with "404 Not Found", but tests pass and user does not have idea why and is not aware of misconfiguration until it attempt to query.

_Originally posted by @ad-m in https://github.com/grafana/grafana/pull/31618#discussion_r604538555_

I have found misconfiguration on my side which push me to look on code in #31618 . I provides URL like `http://tempo:3100` instead of `http://tempo:3100/tempo`, but it was successfully validated and fail on query. This looks like something - at least - to catch during testing of configuration.

@aocenas shared doubts if there is any API that would give us definite "working" status in Tempo.

**Why is this needed**:

Improve first-time UX experience when new datasource of tempo added to Grafana. It's allows to stop errors early and troubleshoot right direction by user.

It's also related to Grafana 4.4 -> Grafana 4.5 upgrade path, because Grafana 4.4 does not require `/tempo` suffix to URL.

**Comment by gabor** [comment]
unfortunately currently there is no suitable api-endpoint in Tempo to do this. there is an open issue about adding it to Tempo ( https://github.com/grafana/tempo/issues/624 ) , when that happens we can improve the grafana-code too.

**Comment by kvrhdn** [comment]
Hi from the Tempo squad 👋🏻 

Tempo returns a different error message depending on whether the API call is correct or not, i.e.:

- Tempo is configured correctly, but the trace is not found:
```
$ curl localhost:3100/api/traces/A
trace not found in Tempo
```
- Tempo is not configured correctly, this also returns a 404 but the message is different:
```
$ curl localhost:3100/tempo/api/traces/A
404 page not found
```

So we should be able to distinguish the error “trace not found” from “Tempo is not configured correctly” by checking the body of the response. The current implementation only checks if the request failed:
https://github.com/grafana/grafana/blob/b16822302915dfb2f6b0427f23727f2affede995/public/app/plugins/datasource/tempo/datasource.ts#L93-L101

_From investigating a bit, the test request always returns `404 page not found` even if Tempo is configured correctly. So I believe there is something wrong there as well. We would expect a correctly configured Tempo data source to get a response containing `404 trace not found`..._

But in general, would this be a good way to go?

➕  Advantages

- We use the query endpoint to verify the data source is working, this should capture any configuration issues as well
  - A health endpoint might work while the query endpoint itself not
  - I noticed a lot of other data sources do this as well

➖ Disadvantages

-  It's not very explicit... "404 trace not found" = good but "404 page not found" = bad?

An alternative would be to add a separate echo or health endpoint.

Let me know what you think is appropriate and I can cook up a PR :)

**Comment by gabor** [comment]
@kvrhdn i'm not sure, i agree with your arguments 😄  ( pinging @zoltanbedi @aocenas for ideas )
maybe do the http404-thing for now, and later if we find it is not good enough re-visit the issue?

(i assume fixing the http404 to make an unique error-string is less work than adding a new endpoint)

on the other hand, this makes the http404-error-message-string kind of part of the API.

**Comment by kvrhdn** [comment]
> on the other hand, this makes the http404-error-message-string kind of part of the API.

Right, I'll check with the team if we are okay with this.

I'm trying to implement the 404 parsing, it's not very difficult it's just a lot of fiddly string parsing...

**Comment by ad-m** [comment]
I know it's late for a comment like this now, but I figured that getting the datasource engine version identifier correctly allows us to check connections, and at the same time this information (including the corresponding endpoint) is useful in a broader sense.

This need arose from the fact that I have a private instance of Loki. The specific query returns a syntax error and I wonder if this is a problem with the old Loki version and the functionality is not supported yet, or if I actually wrote the query incorrectly.

If Grafana adopts as standard for connection checking, downloading a version (not just in Tempo) as part of a backend check then it is more likely that developers will also specify a minimum back end version for datasource as well.

I have no knowledge if there are any guidelines on how to implement datasource connection checking and where to add a sentence with such a suggestion. If such documentation is available - please give directions.
