### ISSUE TITLE
Session DB configuration "style" should match main db

### ISSUE THREAD

**Issue by drawks** [grafana/grafana#3267]
It is confusing that the `[database]` section of config uses separate and clearly named options regardless of the backend being configured while the `[session]` section uses a single `provider_config` option which contains all the options for the specified backend in a non-obvious and completely different format. It would simplify configuration (and auditing configuration) if both sections used more similar config layout.

Heck, it would be especially cool if you were using the same backend tech for both sections if there were an easy way to specify that both `session` and `database` use the same backend configuration.

**Comment by torkelo** [comment]
I can agree that this might be neddlessly different. The reason that session uses a combined single string connection string is that it also supports other session stores (like file and  in memory, not only databases)

**Comment by drawks** [comment]
It seems like the config options which don't make sense in a given context could just not be consumed in the code path. I mean that is how the existing `[database]` section works... It just, to me, seems that this is needlesly complicated AND as referenced in #3268 it leave you in an either/or situation where the config is exposable fully including credentials OR cannot be easily verified during run time because it must be masked to prevent credentials from being exposed.
