### ISSUE TITLE
Scroll bar overlaps with right-hand legend table values in 7.4+

### ISSUE THREAD

**Issue by tofurky** [grafana/grafana#32676]
**What happened**:

After upgrading from 7.3 to 7.4, right-oriented legend table values are overlapped by the right-hand scrollbar, partially obscuring the right-most values. Issue appeared in 7.4, 7.5 is still affected.

**What you expected to happen**:

Display/rendering behavior of 7.3 is retained, where right-hand scrollbar does not overlap right-hand legend values.

**How to reproduce it (as minimally and precisely as possible)**:

Create graph, set legend to appear as table on right, select e.g. avg/current to appear in legend. (The original graphs were set to span full width of page with a fixed legend width of 500, ~~but in subsequent testing not necessary to reproduce~~)

**Anything else we need to know?**:

Panel screenshots, JSON and HTML are attached below.

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: InfluxDB 1.x
- OS Grafana is installed on: Debian 10 (x86_64)
- User OS & Browser: Ubuntu 20.04 / Chrome 89
- Grafana plugins: N/A
- Others:

Screenshot of 7.3.10 (Unaffected):
![image](https://user-images.githubusercontent.com/4065513/113516232-23c10100-9547-11eb-9a34-498f666aeb45.png)
Screenshot of 7.5.2 (Affected):
![image](https://user-images.githubusercontent.com/4065513/113516025-09d2ee80-9546-11eb-84e1-322f66b2e00e.png)

See attachment (7_4_legend_issue.zip):
[7_4_legend_issue.zip](https://github.com/grafana/grafana/files/6254996/7_4_legend_issue.zip)
Contents:
7.3_panel.html - HTML of the panel element (Unaffected)
7.3_panel.json - JSON of the panel (Unaffected)
7.5_panel.html - HTML of the panel element (Affected)
7.5_panel.json - JSON of the panel (Affected)

**Comment by tofurky** [comment]
maybe similar to #32083

**Comment by torkelo** [comment]
Strange, unable to replicate this (also on ubuntu & chrome)

**Comment by tofurky** [comment]
thanks for taking a look.

further testing shows it may only affect graphs when they have a fixed legend width (500 in my case). simply changing them to have an auto-sized legend width was not enough to get the scrollbar to go away without reloading the graphs.

btw, for completeness my browser did have global fonts set to 'small' instead of 'medium', but i set it to 'medium' and the issue persisted after a browser restart.

here is the graph after i disabled fixed legend width of 500 on the graph in the other screenshots:

![image](https://user-images.githubusercontent.com/4065513/113725901-c8674e00-96c1-11eb-8ea3-ba4a8af4bbab.png)

**Comment by ashharrison90** [comment]
i think i can repro this on mac/chrome:

![image](https://user-images.githubusercontent.com/20999846/121540412-5d5a3080-c9fe-11eb-8993-c2db8fd427aa.png)

there's some left margin set on the table element [here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/VizLegend/VizLegendTable.tsx#L100) which is pushing it behind the scrollbars. removing that margin fixes things: 

![image](https://user-images.githubusercontent.com/20999846/121541387-28021280-c9ff-11eb-9850-b001f6fcd53f.png)

only bit i need pointers on is what the left margin is there for. if it's to space the legend from the graph, i think it should probably live outside of the legend component and go in `legendStyle` in `VizLayout` [here](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/VizLayout/VizLayout.tsx#L46). i'll work on a PR to do that, and probably convert `VizLayout` to use emotion at the same time so we can reuse the theme spacing.

any thoughts?

**Comment by tofurky** [comment]
the padding is still slightly off versus what it was before (running 8.0.3):
![image](https://user-images.githubusercontent.com/4065513/122599379-48078680-d03c-11eb-99bc-09a45b3f2ae2.png)
