### ISSUE TITLE
Custom variable saving bug

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#32670]
**What happened**: 
The Custom variable saves the value even if you don't check the "Save current variable values as dashboard default"

**How to reproduce it (as minimally and precisely as possible)**:
1) Open a variable and select another
2) Save the dashboard without a check "Save current variable values as dashboard default box"
3) Switch to another dashboard and return to the dashboard with variables
4) Open the saved variable - by default, the one with which the dashboard was saved will be selected. It's just visual bug.

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: Postgres 12 + timescaleDB
- OS Grafana is installed on: ubuntu 20
- User OS & Browser: Latest Chrome

**Comment by torkelo** [comment]
this should be fixed in 7.5

**Comment by DmitrySidorow** [comment]
> this should be fixed in 7.5

Checked on 7.5.3, the problem still exists
