### ISSUE TITLE
Error adding RSS-Feed to News-Panel

### ISSUE THREAD

**Issue by strowi** [grafana/grafana#32679]
**What happened**: 
With more an more statuspage.io showing up for external resources, we need a way to integrate those into our monitoring.
Tried adding a TinyTinyRSS Shared-FeedURL a la "https://rss.domain.net/public.php?op=rss&id=10&is_cat=1&q=&key=XXXKEYIDXXX" to the Newspanel. 
URL is accessible through Browser, but doesn't show up in Grafana.

**What you expected to happen**:
Feed should show up in the Newspanel

**How to reproduce it (as minimally and precisely as possible)**:
 - setup a ttrss-instance or use the public demo on https://srv.tt-rss.org/tt-rss/# ( user/pass: demo/demo )
 - click on the top rss-icon to generate a url similiar to the above
 - add that url to grafana

**Environment**:
- Grafana version: 7.4.5
- OS Grafana is installed on: docker
- User OS & Browser: firefox & chrome

regards,
strowi

**Comment by kaydelaney** [comment]
Looks like the feed generated by the site you've linked is an atom feed, which is not supported by the News panel at the moment.
