### ISSUE TITLE
Elasticsearch: Add feature toggle in datasource setting for X-Pack specific features

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#32696]
**What would you like to be added**:
As discussed offline with @simianhacker , we'd like to introduce a toggle in the datasource settings page to enable X-Pack specific features.

**Why is this needed**:

We still don't have any X-Pack only feature in Grafana, but we plan to add some in the near future (I.e. top metrics aggregation). 

We'd use this flag to decide whether to show or not specific features in the query editor in order to prevent users from using features in Grafana that are not supported by their ES backend.

The same setting could be used in the settings editor to show/hide other settings, for example enabling querying on frozen indices (https://github.com/grafana/grafana/issues/18277)

**Comment by Elfo404** [comment]
Given recent license changes in Elasticsearch, starting from Elasticsearch 7.11.0 there will be no OSS distribution anymore, this means X-Pack will be effectively installed and active (and unremovable) in every ES installation (please confirm this is true).

Maybe a better way to handle this might be could be to only show that toggle when the selected version is `< 7.11.0`. Any newer version will assume `xpack=true`.

I've been thinking about not introducing the toggle at all, but I can't see a way to make it play nicely with older OSS distributions.

thoughts? @simianhacker @estermv

**Comment by simianhacker** [comment]
This makes sense to me. I will add support for this to https://github.com/grafana/grafana/pull/33041
