### ISSUE TITLE
Cloudwatch: Alert List - Display cloudwatch alarms (NOT statistics)

### ISSUE THREAD

**Issue by jjshoe** [grafana/grafana#32697]
In cloudwatch, you can have panels which display various drawings of data, a table of logs, and you can include relevant alarms.

Stated another way, given web app hello world, I can have three panels:
1) Requests per second as a line graph
2) Last 100 log messages
3) Alarms for cpu, disk space, and requests per second

In Grafana, I would love support for #3. The visualization for "Alert List" does not seem to support querying AWS cloudwatch in any way.

Supporting requests:
https://github.com/grafana/grafana/issues/19013
https://community.grafana.com/t/show-aws-cloudwatch-alarms-in-table/14879

**Comment by sunker** [comment]
The annotation editor for CloudWatch returns alarms for a given metric and plots them as annotations in the panel. Not exactly what you're looking for but might be useful? 

Read more about annotations in grafana [here](https://grafana.com/docs/grafana/latest/dashboards/annotations/)

**Comment by jjshoe** [comment]
@sunker a list of alarms, and their health, "Good" or "Bad". I imagine this is exactly what alert list, though I don't know, as I couldn't configure it to work with aws.

AWS cloudwatch dashboards let you add a panel listing alarms, and their status. 

Annotations are not what I'm looking for. I'm not looking to graph or plot anything.

**Comment by sunker** [comment]
I see what you mean. Let's keep this feature request open for a while and see if there's more users that shows interest in this.

**Comment by peppermor** [comment]
I would love to see this possible with Cloudwatch. I have dashboard showing state off all monitoring components: Alerts in Icinga, Alertmanager, Grafana what I am missing is alarm list from Cloudwatch
