### ISSUE TITLE
broken dashboard if timepicker.refresh_intervals === null

### ISSUE THREAD

**Issue by vankop** [grafana/grafana#32707]
**What happened**:

broken dashboard if in dashboard settings JSON model add:
```
timepicker: { refresh_intervals: null }
```
![image](https://user-images.githubusercontent.com/10380560/113694548-96151b00-96d8-11eb-965a-8897af6e3084.png)

This happed because in `TimeSrv.ts` line 155 
`      refreshIntervals: this.dashboard?.timepicker?.refresh_intervals` refreshIntervals = null and in `getRefreshFromUrl` is default parameter `refreshIntervals = defaultIntervals` that is skipped..

UPD: to correct reproduce this you need query parameter `refresh=<value>`

**What you expected to happen**:

valid dashboard

**How to reproduce it (as minimally and precisely as possible)**:

set in JSON model `timepicker.refresh_intervals = null`

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: any
- OS Grafana is installed on: official docker image
- User OS & Browser: any
- Grafana plugins: any
- Others:

**Comment by vladprokopenko** [comment]
@kaydelaney Can I take this up if anyone else is not working on it? :)
