### ISSUE TITLE
Dashboard Datasource doesn't work if the panel is hidden inside a row

### ISSUE THREAD

**Issue by Theoooooo** [grafana/grafana#32709]
**What happened**:
I created a simple dashboard to display data from my Elasticsearch cluster.
As i wanted to simplify the work load and the amount of request that will be done inside this dashboard, i used the **-- Dashboard --** datasource to only make one query and reused the result on multiple panels.

As i was working with it (and i've already worked with this feature before), it was working properly. But i wanted to simplify the view and i added a row to split my 2 panels inside designated rows.

When i reduced and reopen the 2 rows, my second panel with the datasource set to my first panel display an error which was saying the first panel in question cannot be found.

I suppose the pannels hidden inside a row are getting "unloaded" or something like that, which i can understand to reduce the load from the dashboard and limit the amount of query that can be done inside a single dashboard.

But as you're using the "-- Dashboard --" datasource and the rows features, the panels can't get the data expected from the first panel and through an error, which is totally normal i suppose.

Here is a gif to give you a better explaination of the issue i'm encountering :

![github_issue_row_panel](https://user-images.githubusercontent.com/33425208/113696221-ffddf680-96d1-11eb-976b-f8634cc916a1.gif)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two panel, both in separated rows
2. Create a query from the first panel inside the first row
3. Edit your second panel and select from the datasource option the "-- Dashboard --" and choose your first panel
4. Reduce the first row where the first panel is present
5. Reduce the second row
6. Reopen the second row, you should get the same issue as describe in the .gif above

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: Elasticsearch 7.12.0
- OS Grafana is installed on: CentOS7 1804
- User OS & Browser: Edge 89.0.774.68

**Comment by baur** [comment]
Hi, sorry for offtop, but how to create captions with cruved edges?

**Comment by Theoooooo** [comment]
> Hi, sorry for offtop, but how to create captions with cruved edges?

Hello,

With html inside the **Text** panel

```html
<style>
  .main-title-favories {
    font-size: 20px;
  }

  .content-test{
    width: auto;
    margin-top: 10px;
    border: double 5px transparent;
    border-radius: 21px;
    text-align: center;
    background-image: linear-gradient(#0b0c0e, #0b0c0e),linear-gradient(to right, #BA9D08, #BA3708);
    background-origin: border-box;
    background-clip: content-box, border-box;
  }
</style>

<div class="dashboard-header">
  <div class="content-test main-title-favories">
    My test
  </div>
</div>
```

**Comment by pkolyvas** [comment]
Confirmed that this is still an issue in `main`:
![Screen Shot 2021-12-02 at 9 16 53 AM](https://user-images.githubusercontent.com/43178667/144429395-f9c21300-84c2-4584-8e18-306711b3f1ce.png)

**Comment by natellium** [comment]
Thanks for raising this. We'll look into this as part of a bigger initiative #52484
