### ISSUE TITLE
Browsing to same dashboard using dashboard overview does not select a template variable

### ISSUE THREAD

**Issue by pjfiers** [grafana/grafana#32711]
**What happened**:
No variable from dropdown is selected or injected.

**What you expected to happen**:
First variable or current variable to be selected.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a dashboard with a template variable with multiple values
- Browse to dashboard,
![grafana_bug_0](https://user-images.githubusercontent.com/1277821/113697872-18e7a700-96d4-11eb-99f7-93378c04d9e2.PNG)
![grafana_bug_1](https://user-images.githubusercontent.com/1277821/113697885-1edd8800-96d4-11eb-8e55-e4b04b5fec82.PNG)
- Change selected value from template variable
![grafana_bug_2](https://user-images.githubusercontent.com/1277821/113697952-374da280-96d4-11eb-9118-4052e7ee882e.PNG)
- Click on dashboard-name in top left
![grafana_bug_3](https://user-images.githubusercontent.com/1277821/113697972-3e74b080-96d4-11eb-82ad-a64114e614d0.PNG)
- Select same dashboard
![grafana_bug_4](https://user-images.githubusercontent.com/1277821/113697979-416fa100-96d4-11eb-81bd-3aa07f632c5d.PNG)

**Anything else we need to know?**:
This glitch only occurs if you either:
- Change the template variable via dropdown to anything other than dashboard default
- Arrive on dashboard by direct link (from external site or other dashboard) with template variables in url other than dashboard default

**Environment**:
- Grafana version: 7.3.10, 7.5.2
- Data source type & version: Any
- OS Grafana is installed on: Debian 
- User OS & Browser: Any
- Grafana plugins: N/A
- Others:
  - Dashboard JSON:
  `{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 159,
  "iteration": 1617705482544,
  "links": [],
  "panels": [
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "content": "# Selected var1:\n${var1:text}\n\n\n## Query example:\nSELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter AND afield =~ /(${${var1:text}_var:pipe})/ GROUP BY time($__interval) fill(null)",
        "mode": "markdown"
      },
      "pluginVersion": "7.3.10",
      "targets": [
        {
          "groupBy": [
            {
              "params": [
                "$__interval"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "orderByTime": "ASC",
          "policy": "default",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "text"
    },
    {
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "custom": {
            "align": null,
            "filterable": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 7,
        "w": 12,
        "x": 0,
        "y": 7
      },
      "id": 4,
      "options": {
        "showHeader": true
      },
      "pluginVersion": "7.3.10",
      "targets": [
        {
          "groupBy": [
            {
              "params": [
                "$__interval"
              ],
              "type": "time"
            },
            {
              "params": [
                "null"
              ],
              "type": "fill"
            }
          ],
          "orderByTime": "ASC",
          "policy": "default",
          "query": "SELECT mean(\"value\") FROM \"measurement\" WHERE $timeFilter AND afield =~ /(${${var1:text}_var:pipe})/ GROUP BY time($__interval) fill(null)",
          "rawQuery": true,
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              },
              {
                "params": [],
                "type": "mean"
              }
            ]
          ],
          "tags": []
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "foo",
          "value": "1"
        },
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "var1",
        "options": [
          {
            "selected": true,
            "text": "foo",
            "value": "1"
          },
          {
            "selected": false,
            "text": "bar",
            "value": "2"
          }
        ],
        "query": "foo : 1, bar : 2",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "row foo 1",
          "value": "row foo 1"
        },
        "error": null,
        "hide": 2,
        "includeAll": true,
        "label": null,
        "multi": false,
        "name": "foo_var",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "row foo 1",
            "value": "row foo 1"
          },
          {
            "selected": false,
            "text": "row foo 2",
            "value": "row foo 2"
          },
          {
            "selected": false,
            "text": "row foo 3",
            "value": "row foo 3"
          }
        ],
        "query": "row foo 1, row foo 2, row foo 3",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "row bar 1",
          "value": "row bar 1"
        },
        "error": null,
        "hide": 2,
        "includeAll": true,
        "label": null,
        "multi": false,
        "name": "bar_var",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "row bar 1",
            "value": "row bar 1"
          },
          {
            "selected": false,
            "text": "row far 2",
            "value": "row far 2"
          },
          {
            "selected": false,
            "text": "row bar 3",
            "value": "row bar 3"
          }
        ],
        "query": "row bar 1, row far 2, row bar 3",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Grafana Bug report",
  "uid": "OrhXgPlMz",
  "version": 19
}`

**Comment by zoltanbedi** [comment]
I couldn't reproduce this with the dashboard.json you provided. Can you please try to upgrade?
