### ISSUE TITLE
Grafana support for Opentsdb v2.2.0 and above

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3271]
There are big differences between Opentsdb 2.1 and 2.2.

1. Opentsdb deprecated tags in v2.2.0 and introduced filters. This is one of the major change which we need to make in Grafana query control. 

2. /api/query takes a new parameter "showQuery" to identify request queries, which throws 400 with any version lower than Opentsdb v2.2.0.

So, how should we support these two different kinds of Opentsdb version? There are two options I can think of:

1. Stop supporting Opentsdb 2.1.1 for Grafana 2.6 and above. If Grafana 2.6 and above is used, people need to upgrade Opentsdb to 2.2.0. This is the **easy** option to implement :smile: 

2. Have two datasources for Opentsdb which are 
a.) 2.1.1 and lower 
b.) 2.2.0 and above
like we have for InfluxDB. This is the **harder** option to implement and won't affect users even if they upgrade Grafana.

My vote is option 2.

**Comment by utkarshcmu** [comment]
@torkelo Do we care about backward compatibility of Grafana and Opentsdb? Upgrading to Opentsdb 2.2.0 will break a few things and will introduce new parameters as mentioned above. Which option do you think is better in the above mentioned comment?

**Comment by torkelo** [comment]
in what way did it depricate tags? Is OpenTSDB 2.2 query api backward compatible or does it not work at all with Grafana 2.5?

**Comment by utkarshcmu** [comment]
1. In Opentsdb 2.2.x introduced filters (which are much more useful than tags). They are similar to tags but have richer features than tags like wildcard support, etc.

2. To fix #1876 , "showQuery" parameter needs to be added in the HTTP request to Opentsdb, which does not work with Opentsdb 2.1.x. So, if Grafana's alias feature needs to work with Opentsdb, users need to upgrade to Opentsdb 2.2.x.

**Comment by torkelo** [comment]
yes, but is OpenTSDB 2.2 backward compatible with 2.1? or is the api changes totally non backward compatible? 

If someone installs OpenTSDB 2.2 today, does it work at all in Grafana? Does tags work, you said depricated, does that equal that tags are removed , the tag filter api removed?

**Comment by utkarshcmu** [comment]
Opentsdb 2.2.x is completely backward compatible. Grafana will work with Opentsdb 2.2.x if someone installs it today. Tags will work, everything will be fine.

**Comment by torkelo** [comment]
ok, so it is only if Grafana would take advantage of filters that things would start to break (or we would need to split/duplicate the OpenTSDB data source)

**Comment by utkarshcmu** [comment]
Consider the following scenario when Grafana 2.5 is being used with Opentsdb 2.1.x:

1. Now, We go ahead and make changes in grafana master branch and add "showQuery" parameter(available in opentsdb 2.2.x) in the HTTP request.which Grafana makes to opentsdb, to fix #1876.

2. Users upgrade Grafana to master branch or next version and do not upgrade opentsdb 2.1.x datasource, then HTTP requests to Opentsdb 2.1.x will fail hence showing errors on their dashboards and won't work until the user upgrade to Opnetsdb 2.2.x or downgrade grafana back to 2.5.

**Comment by utkarshcmu** [comment]
Second issue is for taking advantage of filters. Current query editor uses tags and we cannot take advantage of filters until we change the query editor. And if we change the query editor to take advantage of filters, it will break tags.

So, IMO the best way to solve these two issues is to split/duplicate the opentsdb datasource as you said.

**Comment by digrich** [comment]
FillPolicy is also being introduced to calculate the missing data points in 2.2. I think Grafana query editor needs to make some changes to pass FillPolicy parameter also.

**Comment by utkarshcmu** [comment]
@torkelo How about tracking the version of Opentsdb similar to https://github.com/grafana/grafana/pull/3321 and then changing the query according to that?

**Comment by johann8384** [comment]
It sounds like this feature would involve a redesign of the query editor for OpenTSDB. I would strongly encourage support for OpenTSDB 2.3 (https://github.com/opentsdb/opentsdb/tree/put) and the expressions. I made a feature request #3805  for this. I realize that 2.3 is still a while out. With the filters and expressions, the OpenTSDB query editor is going to look much more like InfluxDB or Graphite than the current OpenTSDB editor.

**Comment by bergquist** [comment]
solved by #4138
