### ISSUE TITLE
TypeError: Cannot read property 'emit' of undefined

### ISSUE THREAD

**Issue by tomwilkie** [grafana/grafana#32717]
I was playing with a dashboard's variables trying to select a different datasource I think

Version: Grafana v7.5.0-16578pre (317909f0c9)

<img width="1552" alt="Screenshot 2021-04-06 at 14 01 23" src="https://user-images.githubusercontent.com/444037/113714972-df696880-96e0-11eb-9172-04cb824b31c5.png">

**Comment by torkelo** [comment]
@tomwilkie can you link to the dashboard? Trying to replicate on a few dashboards that have a data source variable but unable to
