### ISSUE TITLE
Feature Request: Add "Total Datasources" to Server Admin Stats.

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#32728]
**What would you like to be added**:

Please add "Total Datasources" to Server Admin Stats.

**Why is this needed**:
 I'd like to know how many data sources we have without resorting to API calls or DB queries.

**Comment by conorevans** [comment]
Hey @zoltanbedi I happened to be interested in this too and I know where/how to add this, but I figure it might be in backlog to triage and so help might not be wanted? If my contribution would be welcomed at this time, lmk, otherwise no sweat.

**Comment by zoltanbedi** [comment]
@grafana/grafana-frontend-platform can @conorevans work on this?
