### ISSUE TITLE
prometheus proxy denies POST to /query_exemplars

### ISSUE THREAD

**Issue by tcolgate** [grafana/grafana#32720]
Exemplars can't currently be queried via a proxied prometheus datasource using POST, as the  query_exemplars is denied by the proxy.

https://github.com/grafana/grafana/blob/823f0bc4601dfdbf613d59d872b6c6f282166001/pkg/api/pluginproxy/ds_proxy.go#L256

**Comment by ivanahuckova** [comment]
We should check if `proxy.ctx.Req.Request.Method == "POST" && !(proxy.proxyPath == "api/v1/query" || proxy.proxyPath == "api/v1/query_range" || proxy.proxyPath == "api/v1/series" || proxy.proxyPath == "api/v1/labels")` is needed and why are we checking it for Prometheus. If it is not needed, we can completely remove it. If it is needed, we should add `|| proxy.proxyPath == "api/v1/series"`.

**Comment by tcolgate** [comment]
Prometheus has a bunch of admin endpoints, so the check is valid. I think to fix the specific error, `api/v1/query_exemplars` needs to be added to the check (that's the call that is currently being denied).
