### ISSUE TITLE
Sessioner panics on a connection error

### ISSUE THREAD

**Issue by austinhyde** [grafana/grafana#3272]
https://github.com/grafana/grafana/blob/master/pkg/middleware/session.go#L64:

```go
	sessionManager, err = session.NewManager(options.Provider, *options)
	if err != nil {
		panic(err)
	}
```

This could definitely stand to be handled better. It currently manifests without being logged, which makes it a real pain to track down when it's ran detached.

Here's the current output when run in the foreground:

```
2015/11/17 21:56:13 [I] Login: Ldap enabled, reading config file: /usr/local/grafana/conf/ldap.toml
panic: ERR invalid password

goroutine 1 [running]:
github.com/grafana/grafana/pkg/middleware.Sessioner(0x1325880, 0x0, 0x0)
	/home/vagrant/grafana-build/src/github.com/grafana/grafana/pkg/middleware/session.go:60 +0x161
github.com/grafana/grafana/pkg/cmd.newMacaron(0xc82041a930)
	/home/vagrant/grafana-build/src/github.com/grafana/grafana/pkg/cmd/web.go:49 +0x4c1
github.com/grafana/grafana/pkg/cmd.StartServer()
	/home/vagrant/grafana-build/src/github.com/grafana/grafana/pkg/cmd/web.go:78 +0x45
main.main()
	/home/vagrant/grafana-build/src/github.com/grafana/grafana/main.go:71 +0x1f8
....
```

In my case, this happened because my Redis password was wrong, but this will obviously happen on any error when connecting to a session provider.

**Comment by utkarshcmu** [comment]
#2776 ?

**Comment by austinhyde** [comment]
Heh, yeah, I suppose that's related, I didn't see it on my initial search. I was looking for the more general "session panic" issues.

**Comment by woodsaj** [comment]
I think Grafana should just catch all calls to panic() and log the error and stack trace.
This can be done easily enough by adding a recover() call inside a deferred call in main()

eg in main.go
```
func main() {
	// capture panics.
	defer func() {
		if r := recover(); r != nil {
			stack := make([]byte, 20480)
			runtime.Stack(stack, false)
			log.Fatal(4, "panic: %s\n%s", r, string(stack))
		}
	}()
```

**Comment by austinhyde** [comment]
That might be a good catch-all case, but wouldn't the better solution be to simply not panic for a simple error?

**Comment by torkelo** [comment]
A failure to init session manager should probably panic (exit the app), but maybe not, will investigate.
