### ISSUE TITLE
Influx top function 

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#3273]
Hi,

Was looking at https://github.com/grafana/grafana/issues/2757 but cant find the top function in the drop down? Did it not get implemented ?
Trying to do it by raw qurey mode but im failing that aswell

Was interested in tryin it in conjunction with the new table panel in 2.6pre

**Comment by torkelo** [comment]
I agree, this function needs to be added now that the table panel exists, https://github.com/grafana/grafana/issues/2721
