### ISSUE TITLE
Table panel filter for value (cell) not working on ElasticSearch DataSource

### ISSUE THREAD

**Issue by fjlour** [grafana/grafana#32746]
**What happened**: 
When using a Table Panel (new) with ElasticSearch data source, and Raw Data or Logs metric type, the little magnifying glass displays when hovering a cell value and labels "Filter for Value", which in the older Table panel it would filter in or out the value as an ad-hoc filter, however, in this new table panel it does nothing.

**What you expected to happen**:
To have the click action filter the table values by adding an ad-hoc filter in the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
ElasticSearch Datasource, add a table panel and select Raw Data.

**Anything else we need to know?**:
Tested in 7.4.0 and 7.5.2

**Environment**:
- Grafana version: 7.4.0 and 7.5.2
- Data source type & version: ElasticSearch 7.10
- OS Grafana is installed on: Ubuntu 18.04 (Docker)
- User OS & Browser: Windows 10 and Chrome or Firefox
- Grafana plugins: none
- Others:

![2021-04-07_11h41_20](https://user-images.githubusercontent.com/42777078/113854868-447f9580-9797-11eb-8a70-027106923d44.gif)

![2021-04-07_11h43_36](https://user-images.githubusercontent.com/42777078/113854945-5d884680-9797-11eb-969e-9357ff24d161.png)

**Comment by kaydelaney** [comment]
Briefly looked into this and it seems like an issue with the Table panel in general rather than being specific to Elasticsearch

**Comment by hugohaggmark** [comment]
Closing this issue as I can't repro it on https://play.grafana.org/d/7stpV9XGk/table-panel-filter-for-value-cell-not-working-on-elasticsearch-datasource-32746?orgId=1 and we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
