### ISSUE TITLE
Relative loading of font and style files

### ISSUE THREAD

**Issue by ZuperZee** [grafana/grafana#32750]
**What would you like to be added**:

Being able to load font and style files relative.

Currently grafana toolkit build font and style files with a leading / which causes the files to be absolute.

**Why is this needed**:

For use with reverse proxies.

More info on why this is needed <https://github.com/gapitio/gapit-htmlgraphics-panel/discussions/19#discussioncomment-579053>

**Comment by ZuperZee** [comment]
Removing the leading slash from <https://github.com/grafana/grafana/blob/82bae892eb030ea80428d0e4c271afaf59ad4539/packages/grafana-toolkit/src/config/webpack/loaders.ts#L163>
seemed to make the font files load relatively.

**Comment by jackw** [comment]
Closing as this should be fixed in #35416 and released in v8.0.1
