### ISSUE TITLE
Frontend Dashboard Alerting Cannot Find Query

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#32751]
**What happened**:
UX errors that query is missing even though it is there.

![image](https://user-images.githubusercontent.com/1692624/113874148-7b4bb080-9783-11eb-9e27-46ccdb583301.png)

**What you expected to happen**:
Test should not throw this error since query A exists

**How to reproduce it (as minimally and precisely as possible)**:

1. Go Dashboard, or create new saved dashboard
2. Click add panel (in my instance, default random walk query is there)
3. Go to alerting tab, select A, and set threshold

**Anything else we need to know?**:
Can be worked around by adding a second query to the list of queries.

@peterholmberg also reproduced this.

**Environment**:
- Grafana version: 82bae892eb
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
This is legacy alerting.
