### ISSUE TITLE
Grafana 2.5 non-negative-derivative only works on zoom out

### ISSUE THREAD

**Issue by tclass** [grafana/grafana#3275]
Hi,
I only updated to Grafana 2.5, I use Graphite and use the non-negative-derivative, but it only shows up if I zoom out very far, if I zoom in to the correct time, nothing shows up anymore. Is there any known issue?

**Comment by torkelo** [comment]
no, maybe an issue with your graphite install? There has been no reported issues relating to this.

Seems to work fine:
http://play.grafana.org/dashboard/db/issue-3275?panelId=1&fullscreen&edit

Maybe your graphite wisper files are a problem or storage schema
