### ISSUE TITLE
Building grafana source on ARM

### ISSUE THREAD

**Issue by vmanju123** [grafana/grafana#32768]
I am trying to build grafana source on ARM64 and having some tough issues. I see that grafana direct binary is available for ARM64, but i would like the source code based binary to make some customizations. Is there a separate code branch for ARM ?  If so can can you point me to the code base, If it is generic code base, are there instructions on how to build on ARM64

I followed below steps
using Grafana 7.2.1 Branch
installed python2, node js, yarn, build essentials and golang for ARM and set the path

ran
yarn --ignore-engines install --pure-lockfile
Build went fine

ran go run build.go build
for making a package
getting below error

root@ip-172-31-81-196:/home/ubuntu/td_grafana# go run build.go build package
Version: 7.2.1, Linux Version: 7.2.1, Package Iteration: 1617816208
rm -r ./bin/linux-arm64/grafana-server
rm -r ./bin/linux-arm64/grafana-server.md5
go version
go version go1.16.3 linux/arm64
Targeting linux/arm64
go build -ldflags -w -X main.version=7.2.1 -X main.commit=64e46a747b -X main.buildstamp=1613638203 -X main.buildBranch=td_dev/1.0 -o ./bin/linux-arm64/grafana-server ./pkg/cmd/grafana-server
go build github.com/aws/aws-sdk-go/service/ec2: /usr/local/go/pkg/tool/linux_arm64/compile: signal: killed
go build github.com/influxdata/line-protocol: /usr/local/go/pkg/tool/linux_arm64/compile: signal: killed
exit status 1
exit status 1

**Comment by aknuds1** [comment]
Hi - it's better if you ask support questions in our [forum](https://community.grafana.com/) or [Slack](https://slack.grafana.com/) since we use GitHub issues for bugs and feature requests only.

As for whether there's a specific branch for ARM, no. Everything builds off the same branch.

**Comment by vmanju123** [comment]
Thanks

I actually made some progress and installed them manually using 
go get github.com 
command
there were several other errors similarly and had to install each of them manually

not below is the latest error
go version go1.16.3 linux/arm64
Targeting linux/arm64
go build -ldflags -w -X main.version=7.2.1 -X main.commit=64e46a747b -X main.buildstamp=1613638203 -X main.buildBranch=td_dev/1.0 -o ./bin/linux-arm64/grafana-cli ./pkg/cmd/grafana-cli
./node_modules/.bin/grunt build --pkgVer=7.2.1-1617817436 --arch=arm64 --platform=linux
Version 7.2.1-1617817436
/home/ubuntu/td_grafana
Running "clean:release" (clean) task
>> 0 paths cleaned.

Running "clean:build" (clean) task
>> 0 paths cleaned.

Running "exec:webpack" (exec) task
/home/ubuntu/td_grafana
>> Killed
>> Exited with code: 137.
>> Error executing child process: Error: Process exited with code 137.
Warning: Task "exec:webpack" failed. Use --force to continue.

Aborted due to warnings.
exit status 3
exit status 1
