### ISSUE TITLE
Set the default for max_open_conn on sqlite3 to 1 instead of unlimited

### ISSUE THREAD

**Issue by benjojo** [grafana/grafana#32769]
**What would you like to be added**:
Grafana does not appear to handle the SQLITE_BUSY state (aka `database is locked`) very well.

Efforts in the past appear to have been made to fix it: https://github.com/grafana/grafana/pull/17274 and https://github.com/grafana/grafana/pull/17276 however have not fully fixed it.

Instead of adding retry logic to every path where sqlite3 could hit a lock, I suggest it's more logical to set `SetMaxOpenConns` on the database engine itself to be 1, this prevents the entire case from happening.

Right now the [go-sqlite3 README.md suggests this](https://github.com/mattn/go-sqlite3/blob/ab91e9342b029f7b8d6097257c9a7874153a5b3f/README.md) to prevent this condition.

My suggested patch would be:

```diff
diff --git a/pkg/services/sqlstore/sqlstore.go b/pkg/services/sqlstore/sqlstore.go
index f1a8f8a745..fa954bfe61 100644
--- a/pkg/services/sqlstore/sqlstore.go
+++ b/pkg/services/sqlstore/sqlstore.go
@@ -321,7 +321,11 @@ func (ss *SQLStore) initEngine() error {
                return err
        }
 
-       engine.SetMaxOpenConns(ss.dbCfg.MaxOpenConn)
+       if ss.dbCfg.Type == migrator.SQLite && ss.dbCfg.MaxOpenConn == 0 {
+               engine.SetMaxOpenConns(1)
+       } else {
+               engine.SetMaxOpenConns(ss.dbCfg.MaxOpenConn)
+       }
        engine.SetMaxIdleConns(ss.dbCfg.MaxIdleConn)
        engine.SetConnMaxLifetime(time.Second * time.Duration(ss.dbCfg.ConnMaxLifetime))
 ```

Other ways I guess to fix this is to make the default config have the correct value:

```ini
#################################### Database ############################
[database]
# You can configure the database connection by specifying type, host, name, user and password
# as separate properties or as on string using the url property.

# Either "mysql", "postgres" or "sqlite3", it's your choice
type = sqlite3
# [...] Snipped [...]
max_idle_conn = 1
max_open_conn = 1
```

**Why is this needed**:

Users will (objectively) randomly get logged out since the sqlite3 database is locked:

```
Apr 07 16:45:06 monitoring grafana-server[5570]: t=2021-04-07T16:45:06+0000 lvl=eror msg="Failed to look up user based on cookie" logger=context error="database is locked"
Apr 07 16:45:06 monitoring grafana-server[5570]: t=2021-04-07T16:45:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/datasources/proxy/1/api/v1/query_range status=401 remote_addr=xxx time_ms=5004 size=26 referer="https://yyy/d/zzz?orgId=1&refresh=30s"
Apr 07 16:45:06 monitoring grafana-server[5570]: t=2021-04-07T16:45:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/api/login/ping status=401 remote_addr=xxx time_ms=0 size=26 referer="https://yyy/d/zzz?orgId=1&refresh=30s"
Apr 07 16:45:06 monitoring grafana-server[5570]: t=2021-04-07T16:45:06+0000 lvl=eror msg="Could not load alerts" logger=alerting.ruleReader error="database is locked"
Apr 07 16:45:09 monitoring grafana-server[5570]: t=2021-04-07T16:45:09+0000 lvl=info msg="Successful Logout" logger=http.server User=
```

Other hard to debug issues appear to come up from database locking. and since this is the default grafana setup, I suggest making this not be possible, since the defaults are likely (?) to be smaller installs that do not need many open threads on the sqlite3 engine.

This issue has been happening on and off for me for a couple of months and 30 mins ago it finally pushed me over the edge to debug why Grafana randomly logs me out.

**Comment by eeeeeta** [comment]
You might also want to consider installing a [busy timeout](https://www.sqlite.org/c3ref/busy_handler.html) (there's a C function for it, and also a PRAGMA if your Go API doesn't expose that) -- which will get SQLite to just retry the transaction if it conflicted with another connection up to a certain timeout period instead of just insta-failing.

**Comment by aknuds1** [comment]
Since we already have a parameter, database.max_open_conn, to control the max number of open connections, all you're suggesting is to modify the default, right? Why not just set database.max_open_conn? It should have the effect you're asking for. I can also suggest that you try enabling write ahead log for SQLite, as discussed in [this](https://github.com/grafana/grafana/issues/17912) issue. Ideally we should have a configuration parameter to enable WAL, I think.

Closing the issue as it isn't a bug.

**Comment by benjojo** [comment]
It's a bug because on the "fresh out of box" defaults that Grafana ships with it will randomly log you out. That's a bug in my eyes, sure you can go and search for this issue and learn that you need to set `max_open_conn` to 1, but surely this goes against software working well out of the box?

**Comment by aknuds1** [comment]
Maybe the better solution is to, as I alluded to, add a configuration parameter to enable WAL and make that default at some point. It's difficult to foresee which problems might arise from changing the default to 1.
