### ISSUE TITLE
Icons: Some icons are missing

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#32776]
**What happened**:
On our hosted admin-ops-tools instance that runs on master, some icons are missing. Might be related to https://github.com/grafana/grafana/pull/32387
![image](https://user-images.githubusercontent.com/30407135/113993024-49564f00-9854-11eb-806e-809784788bba.png)
![image](https://user-images.githubusercontent.com/30407135/113993062-53784d80-9854-11eb-8952-17f32b04287f.png)

**Environment**:
- Grafana version: master Grafana v7.5.0-16732pre (c1061d038c)

**Comment by leeoniya** [comment]
i'll go through the codebase and add all remaining icons we actually use to the in-bundle static cache. that will fix this specific issue but it won't fix the underlying problem, that `admin-ops-tools` has a different http root directory structure compared to this repo. someone else will have to look into adjusting our icon loading strategy for that.
