### ISSUE TITLE
Support for specifying an account id when querying for CloudWatch metrics from Grafana

### ISSUE THREAD

**Issue by kevingerard72** [grafana/grafana#32778]
AWS allows for sharing of metrics from one account to another.
When querying for metrics in CloudWatch, the UI allows for selecting a source account id.
![image](https://user-images.githubusercontent.com/81374351/113993927-3a23d100-9855-11eb-9c75-7a8ab4e7cd00.png)

Unfortunately, this functionality appears not to be available in Grafana.

When specifying a specific account ID, here is what the request from CloudWatch looks like:
_{
    "view": "timeSeries",
    "stacked": false,
    "metrics": [
        [ { "expression": "SEARCH('{AWS/RDS} MetricName=\"ActiveTransactions\"', 'Average', 300)", "id": "e1", "period": 300, "accountId": "############" } ]
    ],
    "region": "eu-west-1"
}_

Notice the "accountId" entry in the metrics portion of the request.

I have found no way of including the account ID when querying from Grafana.
Am I missing something?
If indeed this is not available, can it be added?

Many thanks

**Comment by sunker** [comment]
Thanks for reporting this @kevingerard72! Didn't know that features existed in the CloudWatch console, but I think it sounds great. The questions is how to solve this though. I might be possible to do using data links. I'll do some investigating on my side and report back here.

**Comment by kevingerard72** [comment]
Hi Eric,
Thanks for your feedback.
Feel free to reach out to me if you need more info or screenshots.
Cheers,
Kevin

**Comment by gigawatts** [comment]
I was just about to open a new issue asking if exactly this was possible. I'll be eagerly awaiting this feature!

**Comment by kevingerard72** [comment]
Hi Erik,
Do you have an update for us related to this issue?
Many thanks,
Kevin

**Comment by sunker** [comment]
Hi @kevingerard72! I'm talking to AWS engineers about this. I'm afraid it might take some more time to investigate this.
