### ISSUE TITLE
Panels are able to draw outside their bounds

### ISSUE THREAD

**Issue by heliodor** [grafana/grafana#32771]
**What happened**:
When viewing a dashboard, a panel is drawing outside its bounds, over another panel.

**What you expected to happen**:
Each panel's canvas should be clipped to the box that visually represents the panel.

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana v7.5.2 with the `larona-epict-panel` plugin.
Create a dashboard with two rows and two columns of empty panels.
Edit the bottom-right panel and set it to use the `ePict` plugin as the visualization type.
Click the "Add a box button". In the box definition settings:
X: -100
Y: -100
Font-size: 30
Hover your cursor right under the word "Color" and you should be able to click to choose a color. The default is white, so it looks like there's nothing there. Choose a color, such as red.
Exit the panel's edit mode to go back to viewing the entire dashboard.
You should see `N/A` drawn in red floating over one of the other panels.
See attached screenshot.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.2
- Data source type & version:
- OS Grafana is installed on: Ubuntu in docker
- User OS & Browser: Mac OSX, Chrome
- Grafana plugins: larona-epict-panel
- Others:

<img width="1432" alt="Screen Shot 2021-04-07 at 9 25 19 PM" src="https://user-images.githubusercontent.com/395678/113954666-49b90080-97e8-11eb-8a25-8c4b610a98a2.png">

**Comment by torkelo** [comment]
Yes, it's up to panels respect their dimensions, having overflow hidden makes dropdowns and other overflowing elements not possible from within the panel
