### ISSUE TITLE
Switching from RAW query mode to Graphical mode discard any query initially done from RAW mode

### ISSUE THREAD

**Issue by patrickatomic** [grafana/grafana#3277]
So I just realize that when I have a RAW query that works on grafana from influx 0.9 datasource, if I switch it (by mistake or intentionally) to Graphical mode, of course the graphical query won't include the specific changes I made in RAW (that are not supported using the Graphical query mode...) but when I revert back to RAW mode, the original RAW query I had is lost....

Here's an example:

=RAW QUERY=
SELECT derivative(mean(value),1s)*-8 FROM "snmp_tx" WHERE "host" = 'untangle-af_mtl' AND "type" = 'if_octets' AND "type_instance" = 'eth0' AND $timeFilter GROUP BY time($interval) fill(none)

=Switch it to graphical mode=

=Switch it back to RAW mode=
SELECT count("mean(value),1s") AS "mean(value),1s" FROM "snmp_rx" WHERE "host" =~ /$untangle/ AND "type" = 'if_octets' AND "type_instance" = 'eth0' AND $timeFilter GROUP BY time($interval) fill(null)

See? My original RAW query is changed... :(
The new RAW query match the one from from the query listed in Graphical mode...

I'm using Grafana 2.5.0 with Influxdb 0.9.4

Thanks

**Comment by torkelo** [comment]
yes, this is by design, there is no query parse in Grafana that can translate between the different modes. I can understand that if you accidentally switch mode it can cause problems.
