### ISSUE TITLE
@grafana/ui:  InlineFieldRow and InlineField cause Minified React error #130 in grafana 7.0.3

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#32780]
**What happened**:
@grafana/ui:  InlineFieldRow and InlineField cause Minified React error #130 in grafana 7.0.3

**What you expected to happen**:
when using @grafana/ui developing custon plugins, if we return InlineFieldRow in render function, it will cause Minified React error #130 in grafana 7.0.3

Grafana Version: 7.0.3
Grafana UI Version:  7.5.2

https://user-images.githubusercontent.com/12808432/113996875-2b0b4600-988a-11eb-8e78-c2eee667c209.mov

**How to reproduce it (as minimally and precisely as possible)**:
```tsx
render() {
    return (
      <InlineFieldRow>
        <InlineField label="Query" labelWidth={12} grow>
          <Input />
        </InlineField>
      </InlineFieldRow>
    )
}
```

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: custom
- OS Grafana is installed on: macos 11.2
- User OS & Browser: macos11.2
- Grafana plugins: QueryEditor Component

**Comment by MeetzhDing** [comment]
it should be related to this [@emotion/css issues 2114](https://github.com/emotion-js/emotion/issues/2114).
when i use the @emotion/css, React#130 problem will be reproduced.

maybe we should upgrade @grafana/toolkit config?

**Comment by MeetzhDing** [comment]
OR maybe we should upgrade emotion in the @grafana/ui dependencies ?

**Comment by torkelo** [comment]
I think this component did not exist in 7.0.3, so a plugin built with Grafana/UI 7.5 is only guaranteed to work in Grafana 7.5

**Comment by MeetzhDing** [comment]
> I think this component did not exist in 7.0.3, so a plugin built with Grafana/UI 7.5 is only guaranteed to work in Grafana 7.5

In grafana7.0.3, InlineFieldRow and InlineField was existed. 
And when using grafana-toolkit, the @grafana/ui package has been added to webpack config `externals`,  So people who using grafana under 7.2.2(tested by our testing engineer ) will get this problem.

i think this @emotion/css problem should be deal with AND it won`t cost too much time.
