### ISSUE TITLE
Improve error handling in toDataQueryError function

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#32783]
**What would you like to be added**:

I'd like to propose an enhancement request for the https://github.com/grafana/grafana/blob/master/packages/grafana-runtime/src/utils/queryResponse.ts#L136 function.

Because some data sources can return errors as objects #27618 I think it would make sense to check the error message to be type `string`.

**Why is this needed**:

This is needed to make sure that the error message returned from here is always a string.

**Comment by imskr** [comment]
Can I work on this @zoltanbedi? I'm new to the project and trying to get started contributing to the project :)

**Comment by zoltanbedi** [comment]
Go ahead @imskr. We welcome every contribution.

**Comment by xrisaD** [comment]
Hi @zoltanbedi, is this still open?

**Comment by zoltanbedi** [comment]
Hi @xrisaD yes this still not fixed.

**Comment by jjromary** [comment]
Hi, @xrisaD. How can I manage to reproduce the error? I tried to do it in the same way as shown in issue [#27618](https://github.com/grafana/grafana/issues/27618) but I'm not getting it.

**Comment by zoltanbedi** [comment]
Sorry @jjromary I think this issue doesn't make sense as a whole lot changed to the codebase since this issue.
