### ISSUE TITLE
Explore: Blank page when datasource in localStorage is missing

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#32782]
**What happened**:
When opening Explore, the pre-default datasource is set to the last one used. It might happen that a datasource gets removed or renamed, in that case Explore only shows a blank page.

In this example I'm manually editing localstorage, but the result it's equivalent to deleting/renaming a datasource. 

https://user-images.githubusercontent.com/1170767/114010040-9ee22a00-985b-11eb-8cba-c231db8ed721.mov

**What you expected to happen**:
In such condition I'd expect the default datasource to be selected instead and the explore page to be usable.

**How to reproduce it (as minimally and precisely as possible)**:

- Open Explore
- Manually edit `grafana.explore.datasource.1` entry in localstorage to something non-existent (this imitates deleting a datasource, or renaming one)
- Navigate somewhere else and then back to `/explore`

**NOTE**: Only refreshing the explore page doesn't trigger the problem, as the datasource specified in the URL takes precedence over the one in localstorage

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.3

**Comment by dbluxo** [comment]
I just did a fresh Grafana installation (7.5.3) in which two datasources (Prometheus, Loki) are provisioned via a sidecar. When I open Explore, the page also remains blank. With Grafana 7.4.3 there is no problem.
