### ISSUE TITLE
Docs feedback: /administration/image_rendering.md

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#32799]
In the **Grafana image renderer plugin and remote rendering service** section, there is a list of dependencies to install on a CentOS system. This was up to date on CentOS 7.

On CentOS 8, the following two dependencies are also required: `alsa-lib` and `libX11-xcb`. The `libX11-xcb` package doesn't seem to exist in CentOS 7 repositories so it looks like we need 2 lists now.

**Comment by achatterjee-grafana** [comment]
@AgnesToulet, do you want to take this up? Otherwise, I can update the topic and add you as a reviewer. LMK, thanks!

**Comment by AgnesToulet** [comment]
@achatterjee-grafana Sorry for the delay and thanks for the heads-up! You can take this and put me and Alexandre as reviewers. I like to be informed but I don't have any way to test this so I trust @adeverteuil on this.
