### ISSUE TITLE
Grafana should have pagination or scroll loading for LogQL queries

### ISSUE THREAD

**Issue by Morriz** [grafana/grafana#32791]
**What would you like to be added?**:

Pagination or scroll loading for LogQL queries.

**What would you like to be removed??**:

Please remove the "line limit" input which is confusing ("auto" should just work, right?), is unnecessary (why was it ever introduced in the UI?) and interfering with good UX. 

**Why is this needed**:

When a user selects a time window for a query, the user should not need to be asked additional information to perform that query, and grafana should load & render the results either through pagination or by scrolling the time range into view. Just like with any other good working data query solution. 

The grafana + loki combo has been around long enough now to have been able to hide implementation details from the UX I would say.

**Comment by zoltanbedi** [comment]
Duplicate of #19354

**Comment by Morriz** [comment]
Why is this seen as a duplicate when I clearly state the problematic use of line limit here? Should I file a separate issue for that?

**Comment by Morriz** [comment]
Point is that the query range should dictate the log retrieval. That pagination is a solution to line limit is a bonus.

**Comment by atlee19** [comment]
Commenting in Dec. 2021, I agree with @Morriz that pagination for logs would be better than the using a line limit.

**Comment by jo-krk** [comment]
Any news on this? Afaik, pagination still works only in Explore view

**Comment by david-guenault** [comment]
No one will use log panel without pagination or log scrolling. Is it that hard to implement what already exist in explore panel ?

**Comment by artem-zherdiev-ingio** [comment]
One year later. There are still not on logs panel. Any ETA of this?

**Comment by zoltanbedi** [comment]
Hello 👋 
This is being worked on see https://github.com/grafana/grafana/issues/71728
