### ISSUE TITLE
Improve handling of SNMP metric names with Prometheus

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#32792]
**What would you like to be added**:

As discussed on the snmp-exporter repo (https://github.com/prometheus/snmp_exporter/issues/104#issuecomment-576022769), Grafana currently handles metric names that do not follow the Prometheus conventions of `component_subcomponent_measurement` relatively poorly in some areas. This applies specifically to the SNMP `componentSubcomponentMeasurement` convention in these areas:

 - Autocompletion: SNMP metrics appear far at the bottom of autocompletion, if at all.
 - Metric browsing: SNMP metrics spill into the root of the metric insertion dialogue, making it very hard to use.
![picture showing the metrics spilling into the dialogue](https://user-images.githubusercontent.com/5447747/72684428-a09dc180-3ae0-11ea-9b50-f64e018cd744.png)

**Why is this needed**:
This behaviour makes Grafana less pleasant to use than it could be for NMS applications, which make heavy use of SNMP.

**Comment by davkal** [comment]
@NotAFile is the latest fuzzy search helping? See #32207
