### ISSUE TITLE
Annotation queries in Explore

### ISSUE THREAD

**Issue by fredr** [grafana/grafana#32798]
**What would you like to be added**:
I would like to be able to write annotation queries in the Explore view

**Why is this needed**:
I use the Explore view a lot when investigation ongoing and past problems, and it would be very useful if it was possible to write annotation queries (from both metrics and logs) to show in the graphs. This would make it easier to find correlations between events and and increases and decreases in graphs.

I'm thinking something like this:
![explore-annotations](https://user-images.githubusercontent.com/762956/114051287-3b70f000-988d-11eb-9013-c4a2fd4b2133.png)

**Comment by bohandley** [comment]
@grafana/observability-logs Would you like to take a look at this as it relates to Explore?

**Comment by ivanahuckova** [comment]
This is probably for @grafana/observability-experience-squad. Passing to their project.

**Comment by ifrost** [comment]
Thanks @fredr! This is something that is definitely on our radar. I'll add it to our backlog

**Comment by Elfo404** [comment]
We are closing this request, as there are other pressing priorities. If this request comes up in the future or it starts getting more traction, we will research and prioritize as needed.
