### ISSUE TITLE
URL parameter change doesn't reload a scripted dashboard

### ISSUE THREAD

**Issue by datamuc** [grafana/grafana#32800]
**What happened**:

Parameter change in URL of a scripted dashboard does not reload the page. Clicking the links on this dashboard [test.js.txt](https://github.com/grafana/grafana/files/6279535/test.js.txt) changes the url in the browser, but doesn't reload the page/dashboard.

![grafana-7 5 3](https://user-images.githubusercontent.com/51400/114052471-5ee86a80-988e-11eb-930d-e7986b659dd2.gif)

**What you expected to happen**:
Panel title and content should change when clicking on the dashboard links.

![grafana-7 3 1](https://user-images.githubusercontent.com/51400/114052436-5859f300-988e-11eb-8b64-12eae96628dd.gif)

**How to reproduce it (as minimally and precisely as possible)**:
- put the dashboard above into public/dashboards
- access http://grafana-url/dashboard/script/test.js
- click on the dashboard links

**Anything else we need to know?**:

It was working on 7.3.1. I've testet an upgrade to 7.5.3 which resulted in the behavior above.

**Environment**:
- Grafana version: 7.5.3
- Data source type & version: n/a
- OS Grafana is installed on: linux
- User OS & Browser: chrome on windows
- Grafana plugins: none
- Others:

**Comment by zoltanbedi** [comment]
@dprokop is it possible that the routing refactor caused this problem?

**Comment by dprokop** [comment]
@zoltanbedi nope, routing work is only available on master and this reports issue in 7.5.3

**Comment by datamuc** [comment]
I manually bisected through all the docker-tags: 7.4.2 is the first faulty release. 7.4.1 works fine.

**Comment by datamuc** [comment]
According to the release notes this may be the cause: #31178

**Comment by datamuc** [comment]
😞
