### ISSUE TITLE
Total Sum vary when we increase the time frame 

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#3280]
Hello @torkelo,

I have one confusion in getting Total count of single metrics.
I am collecting data in every 15 minutes, retention according to that in graphite.

But when i see the data of different timestamp in grafana, Total value is not correct, Total count is decreasing when i increase the time frame window.

Below are the 3 snapshot, 
one is for 2Nov to 10Nov: total count is 137943
Second is for 10Nov to 19Nov: total count is 158599
Third is for 2 Nov to 19 Nov: Total count is 197695.

The third one should be total of first and second, but the output is different. 

![image](https://cloud.githubusercontent.com/assets/15123322/11264039/7f0e256c-8eb6-11e5-958a-dc401ad2327c.png)

![image](https://cloud.githubusercontent.com/assets/15123322/11264086/f1b81d5c-8eb6-11e5-8ab3-837a32e2e09a.png)

![image](https://cloud.githubusercontent.com/assets/15123322/11264103/019ddb4e-8eb7-11e5-9404-1868514b5d59.png)

**Comment by torkelo** [comment]
for total to be correct you need to add this graphite function, consolidateBy(sum) to your query. By default graphite will consolidate points using avg

**Comment by Himanshu-pupneja** [comment]
Thanks @torkelo , that works.

Best Regards,
Himanshu
