### ISSUE TITLE
Interval description at Query Options with wrong formula

### ISSUE THREAD

**Issue by KevinAsher** [grafana/grafana#32819]
**What happened**:

At my quest of understanding the grafana interface, i've found an issue on the explanation of the automatic interval variable as shown in the image below:
![image](https://user-images.githubusercontent.com/20466664/114107228-f48ff400-98a6-11eb-803b-6f468bed8d2a.png)
**What you expected to happen**:
The UI shows the formula for the `$__interval` variable is `Max data points / time range`, but shouldn't it be `time range / Max data points` instead? The relevant code seems to support this:
https://github.com/grafana/grafana/blob/ba6da3d6144927d7f3bf3d28527e367b21d2eea7/packages/grafana-data/src/datetime/rangeutil.ts#L272

**How to reproduce it (as minimally and precisely as possible)**:
Just edit or create an existing panel and click on `Query options` to see the relevant UI.

**Environment**:
- Grafana version: Grafana v7.4.3

**Comment by torkelo** [comment]
Good catch!

**Comment by ivanahuckova** [comment]
To fix this, we just need to update label in `public/app/features/query/components/QueryGroupOptions.tsx` to **Time range / Max data points**

**Comment by conorevans** [comment]
Oh man, I've had to explain this (interval) so many times and was always confused by this label, but kind of brushed it off - great catch 😅
