### ISSUE TITLE
Button to delete a data source not shown if there's an error

### ISSUE THREAD

**Issue by heliodor** [grafana/grafana#32814]
**What happened**:
I am not shown the button to delete a data source because Grafana encountered an error trying to render the config for the data source. The data source is a custom one and the plugin for it was not available because I started Grafana without it.

**What you expected to happen**:
The user should be given the option to delete a data source regardless of any errors in rendering the configuration screen for that data source.

**How to reproduce it (as minimally and precisely as possible)**:
Pick any custom data source plugin that does not ship with Grafana v7. Run Grafana with it.
Add a data source for this custom plugin.
Restart Grafana without the plugin.
Go to the list of data sources and click on the one you configured.
You will get the error shown in the attached screenshot.
The standard buttons at the bottom of the screen are not available: `Save + Test`, `Delete`, `Back`

**Anything else we need to know?**:
This goes to show that the user should be able to delete a data source from the list of data sources, not just from within the config screen for a data source.
That aside, the config screen should have two logical units: the config section and the buttons section. The buttons do not depend on the content in the config section. You should always see them. `Delete` can always delete. No reason why it can't. `Back` can always take you back to the list of data sources. `Save + Test` can be available and error out when clicked.

**Environment**:
- Grafana version: `7.5.2`
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

<img width="1430" alt="Screen Shot 2021-04-08 at 3 43 03 PM" src="https://user-images.githubusercontent.com/395678/114088102-aa951700-9882-11eb-829e-4d6af46f3133.png">

**Comment by ivanahuckova** [comment]
This can be reproduced on grafana.play as well with [New Relic data source](https://play.grafana.org/datasources/edit/117). We have removed all enterprise data source plugins from grafana.play, but forgot to delete this instance. An now, there is no way from UI to delete it.

**Comment by heliodor** [comment]
@dprokop, I see you labeled this as "awaiting more evidence". Is there anything missing or unconvincing in the discussion above?

**Comment by ivanahuckova** [comment]
Btw @dprokop we have this issue in play where we are not able to delete New Relic data source trough UI. 
https://play.grafana.org/datasources/edit/000000117

![image](https://user-images.githubusercontent.com/30407135/120448023-6d816880-c38b-11eb-8171-2edcc1889880.png)

**Comment by natellium** [comment]
This should have been closed by https://github.com/grafana/grafana/pull/40095
