### ISSUE TITLE
Improving documentation by adding embedded panel parameters list.

### ISSUE THREAD

**Issue by glemiere** [grafana/grafana#32811]
**What would you like to be added**: Documentation regarding parameters available for embedded panels.

**Why is this needed**: It is very hard to find them, for instance, I found out about "refresh" somewhere on the forum, but searching for it within the documentation yields no result. At this point I don't know what else is available or missing. It prevents both improvements to grafana and custom software development based on these embeds.

Thank you!

**Comment by ivanahuckova** [comment]
@grafana/docs-squad fyi

**Comment by achatterjee-grafana** [comment]
@ivanahuckova. I have spoken with @dprokop and we will work on this.

**Comment by glemiere** [comment]
That's awesome! Thanks a ton!

**Comment by glemiere** [comment]
Hey there! Any news on this?

**Comment by oddlittlebird** [comment]
Sorry, we are all kind of swamped with Grafana 8 development right now.
