### ISSUE TITLE
Table Panel: Handle long words and large cell content

### ISSUE THREAD

**Issue by zhangsx123** [grafana/grafana#3281]
Table panel can't align column name with value when the value is long string using time_series_to_columns. I think we can do ellipsis for long string instead of show them out completely.

**Comment by torkelo** [comment]
can you show a screenshot?

**Comment by zhangsx123** [comment]
Sorry, I tried to upload screenshot many times but always failed. In my use case, table panel contains many columns (one column has long string value) and horizontal scroll bar appear, this case will cause unalignment and lose some column name.

**Comment by godfreyhe** [comment]
like this:
![Image](https://github.com/godfreyhe/t/blob/master/pics/2.jpg)
![Image](https://github.com/godfreyhe/t/blob/master/pics/3.jpg)

**Comment by zhangsx123** [comment]
Nice! @godfreyhe

**Comment by torkelo** [comment]
Fixed in v7 table
