### ISSUE TITLE
new API to retrieve panel type json schema from cue definition

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#32826]
After the cue schema defined for all panel types: https://github.com/grafana/grafana/pull/32527, we want to add a new feature to ease panel editing on the frontend (propose possible keys for existing panel type when editing). In order to make it possible, we need to provide an API in which takes panel type as a parameter and returns JSON schema accordingly.

**Comment by aknuds1** [comment]
Edited the description a bit for clarity.

**Comment by ying-jeanne** [comment]
this feature could be used by https://github.com/grafana/grafana/pull/33453, to enable the autocompletion

**Comment by sdboyer** [comment]
Closing this out as part of cleanup - we do want JSON schema, but probably not quite like this
