### ISSUE TITLE
rename GraphNG -> TimeChart, uPlot -> GraphNG

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#32846]
what is currently GraphNG should become something like TimeChart, as it deals with Time on X, has timezone support, accepts time range, etc. it has a tiny bit of code that tries to use it as an X/Y chart by having non-time X, but this is a kludge that should be removed once we have a proper X/Y component built for this purpose, which requires a lot more changes and a significantly different set of prerequisites and panel controls.

our uPlot wrapper is actually the thing that _should_ be called GraphNG. confusingly, it currently has 3 different names, depending on where you look:

- folder (uPlot)
- filename (Plot.tsx)
- class (UPlotChart)

**Comment by dprokop** [comment]
Yes!
