### ISSUE TITLE
influxdb: flux: better support for multiple-value records

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#32842]
when grafana receives a response from influxdb in flux mode where there is a `_value` column and a `_value2` column, the `_value2` column is ignored. this should not happen.

explanation:
currently when the flux-data is received by grafana, we make a decision: is this time-series or not
( https://github.com/grafana/grafana/blob/master/pkg/tsdb/influxdb/flux/builder.go#L102 )
if it is not time-series, we send basically the"raw" flux result into the browser.
if it is time-series, we find the timestamp-column and the value-column, and the potential label-columns, and build a browser-data from those. we ignore the rest. so if there were additional value-columns, those get ignored.

the usual workaround is to in flux, rename "_value" to something else, so grafana does not classify the flux-data as time-series, and the browser receives the whole raw data.

this is not optimal. we plan to do this improvement:
when we detect it is in time-series mode, we will add every "value-column" to the data sent to the browser. we can decide based on the is-part-of-the-group-key functionality. we may improve the is-time-series heuristic too.
we need to be careful so that the label-handling remains correct.

**Comment by quentinmit** [comment]
Can you add explicit controls to override this, instead of trying to make an even smarter (and complicated) heuristic?

**Comment by gabor** [comment]
@quentinmit we thought about adding such controls, but first we want to implement this (not dropping additional value-columns). we can always add it later, if it becomes necessary.

**Comment by gabor** [comment]
this was implemented in https://github.com/grafana/grafana/pull/33823https://github.com/grafana/grafana/pull/33823 , closing the issue.
