### ISSUE TITLE
Bug with the border between table columns

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#32845]
**What happened**:
If there is a data link in the cell, then the border between the columns disappears

![Screenshot_4](https://user-images.githubusercontent.com/43705385/114186513-a08d1a00-994f-11eb-8613-e182a97e6bdf.png)

**How to reproduce it (as minimally and precisely as possible)**:
Just set data link to cell

**Environment**:
- Grafana version: 7.5.3
- User OS & Browser: Chrome 89 + windows 10

**Comment by ivanahuckova** [comment]
I was able to reproduce this as well:
https://user-images.githubusercontent.com/30407135/114189566-9e748c80-994a-11eb-99d8-f030099f7b1a.mov
