### ISSUE TITLE
[FeatureRequest] Link and Info panel Icons in Dark mode hard to see

### ISSUE THREAD

**Issue by mykllterry** [grafana/grafana#32852]
This has been around for a while 
Currently I'm using
Grafana v7.4.2
Safaria 14.0.3
Chrome 89.0.4389

This is similar to issue [#22813](https://github.com/grafana/grafana/issues/22813) Maybe the same work can address these also.

The panel icon for link and info do not show well in dark mode. 
![image](https://user-images.githubusercontent.com/17049593/114212262-7a975380-9916-11eb-8ef8-0143705101f1.png)

In light mode the icon shows okay.
![image](https://user-images.githubusercontent.com/17049593/114212416-ac101f00-9916-11eb-957a-ec6fbe75a715.png)

**Comment by sidverma32** [comment]
@hugohaggmark   I would like to take this up. As this will be my first contribution to this repo. if you can guide me it will be very helpful.
