### ISSUE TITLE
Bad CSS perfomance of <inputs>'s

### ISSUE THREAD

**Issue by jkmnt** [grafana/grafana#32858]
**What happened**:

I was prototyping a panel plugin with a lot of inputs fields for configuration (spreadsheet-like).
The number of inputs is ~400 (40*10 grid). The inputs are simple `<input>`'s, no magic.
To my surprise there was a noticeable lag when switching (focus/blur) between inputs.

**What you expected to happen**:

I've expected it would be fast and flying.

**How to reproduce it (as minimally and precisely as possible)**:

Generate a form/table with a lot if `<input>`'s, try to switch between them.

**Anything else we need to know?**:

Chrome devtools revealed the lag is due to massive Recalculate Style triggered by outline.js
outline.js is dirty hacking the global style on _every_ keypress and mousedown.
So each keypress/mousedown is triggering the Recalculate Style !
IMHO it's a bad thing perfomance-wise, especially for a limited platforms like RPi.

AFAIK outline.js is some accessibility workaround for keyboard navigation.
Is it really needed for Grafana, since it not a site but app ?

**Environment**:
- Grafana version:
v7.4.1 (07649d1313)
- User OS & Browser:
Chrome on windows

**Comment by jkmnt** [comment]
Tried to delete the DOM node the outline.js is injecting it's magic into (using the chrome dev tools).
Now my inputs are flying !

**Comment by leeoniya** [comment]
thanks for testing!

this thing looks to be 10,000 web-years old: (Jan 2018): https://github.com/lindsayevans/outline.js/commits/master

a lot has changed since then. i'll bet this can all be done with plain css now. if not, we should investigate a more performant codepath.

cc @Ijin08, @torkelo

**Comment by torkelo** [comment]
@leeoniya think we can remove it, we will add custom outline styling in the theming work

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/33066
