### ISSUE TITLE
Feature Request: Exclude a tag from a dashboard list panel

### ISSUE THREAD

**Issue by addshore** [grafana/grafana#3286]
Usecase:

A grafana installation has a 'draft' tag.
I want to be able to generate a list of all dashboards that are tagged as X but not as 'draft'

**Comment by daniellee** [comment]
Thank you for submitting this feature request. However, due to inactivity and/or lack of upvotes, we’re going to close this for now. This does not mean that we are closing it forever. Feel free to comment on this issue to clarify why this is needed and upvote it.
