### ISSUE TITLE
Main menu on Grafana 7.5.3 does not work on the latest chromium-ungoogled

### ISSUE THREAD

**Issue by sanel** [grafana/grafana#32865]
**What happened**:

After Grafana update to 7.5.3, main menu (on the left side) doesn't work any more on the latest chromium-ungoogled (89.0.4389.114). It does work on dev firefox. However, it worked in Grafana 7.4.2.

**What you expected to happen**:

When I click on any item in the menu (`Data Sources`, `Alerting Rules`, ...) it should open the page.

**How to reproduce it (as minimally and precisely as possible)**:
 - Install chromium-ungoogled
 - Install Grafana 7.5.3
 - Click on any item in the left menu (e.g. `Configuration > Data Sources`)
 - Nothing happens. Nothing in console log.
 - Tested also with incognito mode, so no extensions involved.

**Environment**:
- Grafana version: 7.5.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: chromium-ungoogled 89.0.4389.114
- Grafana plugins: none

**Comment by sanel** [comment]
However, when Grafana window is resized or opened with mobile device (simulated through chromium dev tools), clicking on menu items works.

**Comment by sanel** [comment]
After further investigation, this seems to be related with chromium hardware acceleration. Some popups even on GitHub stopped working; I'm attaching a screenshot, where usually clicking a profile link will work, but not in this case.

![image](https://user-images.githubusercontent.com/213914/114534388-3de99600-9c4f-11eb-9a02-560da2ff6a84.png)

After running chromium with the flags down below, Grafana menu clicking started to work:

```
chromium-browser \
    --enable-pinch  \
    --flag-switches-begin \
    --enable-accelerated-video-decode \
    --enable-experimental-web-platform-features \
    --enable-gpu-rasterization \
    --enable-zero-copy \
    --ignore-gpu-blocklist \
    --enable-features=DecodeJpeg420ImagesToYUV,DecodeLossyWebPImagesToYUV,V8VmFuture,Vulkan \
    --flag-switches-end \
    --use-gl=desktop
```

**Comment by hugohaggmark** [comment]
Closing this issue because it's related to the browser.
