### ISSUE TITLE
Data Links based on values don't change with table sorting

### ISSUE THREAD

**Issue by jlyons6100** [grafana/grafana#32864]
**What happened**:
I've had an issue with data links that depend on table values. They don't respond to sorting.
**What you expected to happen**:
I expected data links to be updated as table was sorted.
**How to reproduce it (as minimally and precisely as possible)**:
Add a __value to a data link and change the sorting of the data. Data links do not change when the table is sorted.

**Anything else we need to know?**:
Images of issue:
I created data links for the first column like this: `http://test_url/${__value.text}`
If I hover over the first value, you can see in the lower left hand corner that the correct data link is present. 

<img width="1401" alt="Screen Shot 2021-04-10 at 12 35 31 AM" src="https://user-images.githubusercontent.com/2278962/114262610-d1903d80-9995-11eb-8374-0d235fb69bad.png">

However, in the second image, the same data link is used even after changing the table sorting.
<img width="1398" alt="Screen Shot 2021-04-10 at 12 35 48 AM" src="https://user-images.githubusercontent.com/2278962/114262611-d523c480-9995-11eb-8ad2-cce1394d70cb.png">

**Environment**:
- Grafana version:  v7.5.2
- Data source type & version: --Grafana--, 
- OS Grafana is installed on: Ubuntu - 18.04.5 LTS (Bionic Beaver)
- User OS & Browser: MacOS Big Sur, Chrome browser
- Grafana plugins: Built in "--Grafana--" data source
- Others:

**Comment by rrickardt** [comment]
+1 7.5.3 affected as well, i solved it downgrading to 7.5.1, data links on sorted values works well there.

**Comment by hugohaggmark** [comment]
This issue was fixed by https://github.com/grafana/grafana/pull/32571 and will be release in 7.5.4 patch release.
