### ISSUE TITLE
Failed to render and upload alert panel image by use Grafana Image Renderer

### ISSUE THREAD

**Issue by ccyaml** [grafana/grafana#32866]
**What happened**:
we want to upgrade grafana from 6.2.5 to 7.0.3，and our datebase don't change
we find when we use 7.0.3 grafana， the image render plugin can't work， the logs is 
```
lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=2667 error="Timeout error. You can set timeout in seconds with &timeout url parameter"
```
and when i use 7.0.3 grafana with new datebase(empty database)，the image render plugin is OK

so i check the code of grafana, i find timeout parems is from ```setting.AlertingNotificationTimeout```， so i add notification_timeout_seconds=60 in config file， but the  image render plugin can't work too

when we set addnotification_timeout_seconds = 100 , the logs is 
```
lvl=eror msg="Failed to render and upload alert panel image." logger=alerting.notifier ruleId=2667 error="Rendering failed: TimeoutError: Navigation timeout of 30000 ms exceeded"
```

i use  image render plugin by download plugin file and put the plugin in date/plugin

the cpu of pod is 4U, and memory is 20G

Grafana Image Renderer version is 2.0.0

thanks

**What you expected to happen**:
i want to upgrade grafana from 6.2.5 to 7.0.3，and our datebase don't change, and the image render plugin can work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: ES7.0+
- OS Grafana is installed on:  euleros
- User OS & Browser: euleros
- Grafana plugins: 
- Others:

**Comment by ccyaml** [comment]
sorry for this issue, i find the image plugin don't work because of my mistake

**Comment by taner91xp** [comment]
Hi, how did you solve your issue?
