### ISSUE TITLE
Time series: x-axis crosshair gets stuck when scrolling

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#32862]
**What happened**:

The x-axis crosshair gets misaligned when viewing a time series panel whilst scrolling.

**What you expected to happen**:

The x-axis should be aligned correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Whilst moving your mouse and scrolling, stop over a time series graph. The x-axis crosshair will be incorrect.

**Anything else we need to know?**:

https://user-images.githubusercontent.com/9749173/114253923-6ac65080-99a4-11eb-818a-4673f8ee3e7a.mp4

**Environment**:
- Grafana version: 7.5.2@sha256:b071787d69cf1e8ece704838475ffd24ccbd46fad6f0b141e5922ee8dd39c30d (Docker)
- Data source type & version: Time series 7.4.3
- OS Grafana is installed on: Kubernetes 1.20.5
- User OS & Browser: Windows 10 Pro, Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by leeoniya** [comment]
heh, i just noticed this earlier today and landed a fix 3hrs ago :D

https://github.com/grafana/grafana/pull/32859

**Comment by leeoniya** [comment]
btw, if you move the cursor out of the plot and back in it should re-sync.
