### ISSUE TITLE
Error in logs when viewing dashboard

### ISSUE THREAD

**Issue by junior466** [grafana/grafana#32874]
**What happened**:
Errors in logs when viewing dashboard.

**What you expected to happen**:
No errors.
**How to reproduce it (as minimally and precisely as possible)**:
Browse the dashboard
**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.5.0
- Data source type & version: Influx & latest
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome OSX & latest
- Grafana plugins:
- Others:
- 
When I browse a certain dashboard I receive the following errors in the logs. Everything is working properly. 
 
    Message: t=2021-04-11T19:23:08-0400 lvl=eror msg="Request error" logger=context userId=1 orgId=1 uname=admin error="net/http: abort Handler"

    Message: t=2021-04-11T18:55:53-0400 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=1 orgId=1 uname=admin path=/api/datasources/proxy/2/_msearch remote_addr=192.168.143.50 referer="http://192.168.139.20:3000/d/FHB0jngMk/network?orgId=1&refresh=30s" error="http: proxy error: context canceled"

192.168.143.50 is the computer I am browsing from. 

The [dashboard](https://pastebin.com/raw/KjLV6xUF).

**Comment by hugohaggmark** [comment]
Hi @junior466 does any of the queries take longer than 30s? My thinking is that you have a refres rate set to 30s on the dashboard and if some of the queries take longer than that they will be cancelled. Can you try to change the refresh rate to 120s instead and see if that helps?

**Comment by junior466** [comment]
> Hi @junior466 does any of the queries take longer than 30s? My thinking is that you have a refres rate set to 30s on the dashboard and if some of the queries take longer than that they will be cancelled. Can you try to change the refresh rate to 120s instead and see if that helps?

Right on @hugohaggmark. One of my queries are set to run every 60s so changing it from 30s to 60s makes the error go away.

**Comment by hugohaggmark** [comment]
Great to hear @junior466, I'm going to close this issue now but we can always reopen it when needed.
