### ISSUE TITLE
Prometheus DataSource fails when no exemplars are accessible / disable exemplars button is stuck

### ISSUE THREAD

**Issue by bwplotka** [grafana/grafana#32873]
👋🏽 My goal is to set up Prometheus + Tempo with exemplar support.

**What happened**:

Using dashboard Panel with Prometheus data source stopped working when I added Tempo DataSource:

![image](https://user-images.githubusercontent.com/6950331/114300272-53c45300-9ab7-11eb-91c3-4701a0ab0425.png)

Dashboards now error with `Cannot use 'in' operator to search for 'exemplars' in undefined`

![image](https://user-images.githubusercontent.com/6950331/114300049-54a8b500-9ab6-11eb-9d3a-bb67172bb401.png)

**Extra finding 1**

Now when I remove Tempo data source and get back to my dashboards, things still have the same error, but when I click some mix of don't show / show query and disable/enable exemplars (although it feels like that button does not work): 

![image](https://user-images.githubusercontent.com/6950331/114300320-aa319180-9ab7-11eb-9437-52faa2de31da.png)

Querying suddenly works... but well, without exemplars I won't.

![image](https://user-images.githubusercontent.com/6950331/114300351-ce8d6e00-9ab7-11eb-89c4-cd9474390d1c.png)

**Extra finding 2**

Exemplars call is successful but does not have any data:

![image](https://user-images.githubusercontent.com/6950331/114300621-1eb90000-9ab9-11eb-935b-988e81841ace.png)

**What you expected to happen**:

At least the metrics graph should work as it used to before adding Tempo data source. 

**How to reproduce it (as minimally and precisely as possible)**:

Deploy https://github.com/bwplotka/observe-argo-rollout/tree/c2a07c2f82920ade1bbde674fe07d4d683b2b6f7/manifests/generated/monitoring

Go to Grafana and the only dashboard there (Demo), see that no query works. It used to work before adding Tempo tracing DataSource 

**Environment**:

Everything is here: https://github.com/bwplotka/observe-argo-rollout/tree/c2a07c2f82920ade1bbde674fe07d4d683b2b6f7/manifests/generated/monitoring

Grafana: grafana/grafana:7.5.2
Prometheus: prom/prometheus:v2.26.0
Tempo: v0.6.0

**Comment by hugohaggmark** [comment]
Adding this to @grafana/observability-squad for initial investigation.

**Comment by bobrik** [comment]
I think #32513 fixes the issue.

**Comment by bobrik** [comment]
I backported this into our internal instance and it works well with prometheus v2.26.0.

**Comment by aocenas** [comment]
@bwplotka should be fixed in 7.5.3. Please reopen if you are still seeing this.
