### ISSUE TITLE
Logs: Make "Show context" button more accessible

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#32870]
**What would you like to be added**:

I'd like to ask for the "Show context" button to be moved to the left side, or otherwise made more accessible.
If log messages are long, the button is not visible and users have to use the horizontal scrollbar to get to the far right side.

Maybe it can always "hover" on the right side, overlapping the log-message, when the mouse is over log lines, without the need to scroll?

![grafik](https://user-images.githubusercontent.com/33002073/114285920-28ac1600-9a5b-11eb-8688-fb6c7a024273.png)

**Why is this needed**:

If log messages are long (e.g. exception callstacks, ...), the show context button becomes useless because you are constantly scrolling.

I even forgot about the feature / thought it had been removed because I never saw the button...

Demo:
![yZz7Hkqkbl](https://user-images.githubusercontent.com/33002073/114285861-a02d7580-9a5a-11eb-82b1-78a288fc5116.gif)

**Infos**

Since this was changed to "bug":
- `Windows 10 2020H2, Firefox 87.0`
- `Grafana v7.5.2 (ca413c612f)`

**Comment by hugohaggmark** [comment]
Added this to your project @grafana/observability-squad

**Comment by ivanahuckova** [comment]
I would say this is bug. I remember that in the past, we have intentionally moved "Show context" button below the log line so it is visible. Not sure when this changed.

**Comment by ivanahuckova** [comment]
Fixed by https://github.com/grafana/grafana/pull/36324
