### ISSUE TITLE
grafana/toolkit panel plugin gives 404

### ISSUE THREAD

**Issue by JorundMartinsen** [grafana/grafana#32886]
**What happened**:
In plugins folder, ran
- ```npx @grafana/toolkit plugin:create test-plugin```
- selected ```panel```
- ```sudo yarn install```
- ```sudo yarn build```
- ```sudo systemctl restart grafana```

Open plugins page, with console output.
Get 404 on test-plugin (exact output below)

**What you expected to happen**:

Plugin should work "out of the box"

**How to reproduce it (as minimally and precisely as possible)**:
Run the above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.5.1 (4dffb875cf)
- Data source type & version:
- OS Grafana is installed on: EndeavourOS, Kernel: Linux 5.11.6-arch1-1
- User OS & Browser: Win10 19041.867, Chrome  89.0.4389.114

**Error message in chrome**

GET http://{server}/public/app/plugins/panel/dist/img/logo.svg 404 (Not Found)

**```tail -f /var/log/grafana/grafana.log | grep test-plugin``` output**:

t=2021-04-12T11:15:21+0200 lvl=dbug msg="Loading plugin" logger=plugins path=/usr/share/grafana/public/app/plugins/panel/test-plugin/dist/plugin.json
t=2021-04-12T11:15:21+0200 lvl=dbug msg="Getting signature state of plugin" logger=plugins plugin=company-test-plugin isBackend=false
t=2021-04-12T11:15:21+0200 lvl=dbug msg="Plugin is unsigned" logger=plugins id=company-test-plugin
t=2021-04-12T11:15:21+0200 lvl=dbug msg="Found plugin" logger=plugins id=company-test-plugin signature=unsigned hasRoot=false
t=2021-04-12T11:15:21+0200 lvl=dbug msg="Non-valid plugin Signature" logger=plugins pluginID=company-test-plugin pluginDir=/usr/share/grafana/public/app/plugins/panel/test-plugin/dist state=unsigned
t=2021-04-12T11:15:21+0200 lvl=dbug msg="Attempting to add plugin" logger=plugins id=company-test-plugin
t=2021-04-12T11:15:21+0200 lvl=dbug msg="Successfully added plugin" logger=plugins id=company-test-plugin

**Comment by hugohaggmark** [comment]
Hi @JorundMartinsen, we can see that you're using `sudo` before each command, which could mean that Grafana doesn't have access to the plugin folders.  Can you try to rerun it without `sudo` or run the Grafana service as `root`.

**Comment by JorundMartinsen** [comment]
I've also found that renaming 'module.ts' to 'module' works.

I'll test with root permission level.

**Comment by tolzhabayev** [comment]
@JorundMartinsen could you try adding the plugin into this config? https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

**Comment by JorundMartinsen** [comment]
I've tested this with Mr. Olssons setup. 
I also ran the scripts without sudo, so:
``` console
JorundMartinsen@dev-no:~/repos$ npx @grafana/toolkit plugin:create test-plugin
// select panel plugin.
// set org name to 'myorg'
// all other options are default

JorundMartinsen@dev-no:~/repos$ cd ./test-plugin
JorundMartinsen@dev-no:~/repos/test-plugin$ yarn install
JorundMartinsen@dev-no:~/repos/test-plugin$ yarn build
JorundMartinsen@dev-no:~/repos/test-plugin$ docker run --rm \
    -e GF_DEFAULT_APP_MODE=development \
    -p 3000:3000 \
    -v ~/repos/test-plugin:/var/lib/grafana/plugins \
    grafana/grafana:8.3.3
```

Can confirm this is not a problem on this setup. Both with v8.3.3 and v7.5.1
