### ISSUE TITLE
Docs feedback: /administration/security.md

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#32890]
Can we add a section here on the security implications of enabling Anonymous access to dashboards. ?

**Comment by hugohaggmark** [comment]
Assigning @achatterjee-grafana to this, feel free to reassign this issue.

**Comment by simonc6372** [comment]
I can provide the first pass input to this. 
* anyone on the internet will be able access any dashboard they know the URL for. 
* anyone on the internet can make view calls to the API, so can list all folders, dashboards and datasources. 
* anyone on the internet with a little bit of knowledge can make arbitrary queries to any datasource that Grafana instance is configured with

This page https://grafana.com/docs/grafana/latest/auth/overview/#anonymous-authentication should probably reference the entry in the security page.

**Comment by achatterjee-grafana** [comment]
Fixed.
