### ISSUE TITLE
Importing Dashboard JSON should prompt to fix missing data sources

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#32891]
When I import dashboard JSON, the configured data sources may be named differently than where it was exported from, so the panels would not load any data until I go into each panel and adjust the datasource.

**What would you like to be added**:

If the data sources in a JSON import are not in the grafana instance, the import UI should prompt me to fix up any missing dashboards, or leave them as is.

Preferably it could do a "replace all" to fix all missing data sources of the same name in one swoop, then perhaps with individual overrides? (or just leave that to going back and editing each panel)

**Why is this needed**:

To make importing dashboards easier :)

**Comment by joshhunt** [comment]
@marefr I'm not sure how they were exported to be honest - I imported the dashboard "manually" from the provisioning repo.

**Comment by marefr** [comment]
If the dashboard is not exported for sharing externally Grafana cannot prompt for missing data sources since Grafana doesn't no what data source type is expected. 

Not sure if anything can be made to improve that short-term. I'll ask @grafana/grafana-frontend-platform for input

**Comment by joshhunt** [comment]
I think it still can, no? I think Grafana should know at least that the data source specified in the dashboard is missing in the user's Grafana, and it should be able to prompt to "fix" the data sources.

Even if there's no type specified, i think prompting to fix from all available data sources is an improvement on "successfully" importing a dashboard, but having every panel immediately error out and needing to fix manually panel-by-panel.
