### ISSUE TITLE
QueryOperationRow: headerElement overflows the row and hides title

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#32893]
**What happened**:
When **headerElement** is passed to **QueryOperationRow**, if it is longer than available space, it:
1. Hides the title of QueryOperationRow(see that Data option is not visible):
![image](https://user-images.githubusercontent.com/30407135/114389676-96f4f380-9b95-11eb-9cd5-3bff5de5b71f.png)

2. Overflows the row (see the text behind Download button): 
![image](https://user-images.githubusercontent.com/30407135/114389840-cdcb0980-9b95-11eb-8470-c5b4a2a286e6.png)

**What you expected to happen**:
I would expect that **title** is always visible as it seems more important. For the headerElement, I would expect for overflow to be hidden or ended with ellipses or it would be wrapped or had horizontal scrollbar. 

**How to reproduce it (as minimally and precisely as possible)**:
Run prometheus query (or other query that returns multiple dataFrames)  `alertmanager_alerts` -> open the Panel inspect -> Data tab.

**Comment by dprokop** [comment]
Fixed by https://github.com/grafana/grafana/pull/33400
