### ISSUE TITLE
Support full Graphite queries to populate template variables

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3290]
Consider the following data structure from statsv in Graphite:

* navtiming.by_browser_version.Chrome.46.firstPaint.median
* navtiming.by_browser_version.Chrome.46.firstPaint.count
* navtiming.by_browser.Chrome.firstPaint.median
* navtiming.by_browser.Chrome.firstPaint.count

I'd like to draw a graph that shows the median first paint of the 10 most used browsers (as there are many).

Basically it would query a metric `navtiming.by_browser.*.firstPaint.median`, and `exclude()` the ones not in the top 10.

It would probably use `highestAverage()` or `highestTotal()` of the associated `.count` from a certain timespan (e.g. summarize per week). Since `exclude()` doesn't provide this feature natively, I figured I'd try populating a template variable with the first 10 and then use that in place of the browser_family wildcard.

However currently dynamic variables can only be populated from a metric path, not a metric query. E.g. it can find `navtiming.by_browser.*` but not `highestAverage(navtiming.by_browser.*.firstPaint.count,10)`.

Is there a way around this, or perhaps some other way to achieve what I'm after in Grafana?

**Comment by torkelo** [comment]
The limitation for what types of queries you can use in template variables is in graphite, graphite does not allow full metric queries in its "metric find" API

**Comment by toni-moreno** [comment]
Hi @torkelo @Krinkle , indeed there is a way to find "nodes" from any metric with wildcards , you can patch your graphite-web with this PR  ( https://github.com/graphite-project/graphite-web/pull/718 ) , I'm using this API from a self made dashboard and is working ok.

This PR has not been accepted by the graphite collaborators yet , but you can vote +1 if  you think could be useful to future releases of grafana.
