### ISSUE TITLE
Table Column Filters reset on auto-refresh

### ISSUE THREAD

**Issue by HeinDTP** [grafana/grafana#32913]
**What happened**:
We collect netstat data every minute and write it into a PostgreSQL database, we then display the data of the last minute in a Table in Grafana. The dashboard has auto-refresh set to one minute so we always see the most recent information. We have enablee the "Column filter" option for the table and use it to filter for a certain IP or Port we are interested in. On auto-refresh the column filter is reset.

**What you expected to happen**:
We would expect the column filter not to reset on auto-refresh.

**How to reproduce it (as minimally and precisely as possible)**:
Set a filter on a column and then wait for auto-refresh.

**Anything else we need to know?**:
If this intended behavior, it would be nice to be able to opt-out of it in some way. 

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: PostgreSQL
- OS Grafana is installed on: s390x Docker Container
- User OS & Browser: Windows 10 + Firefox/Edge
- Grafana plugins: -
- Others: -

**Comment by hugohaggmark** [comment]
This is indeed intended, you can solve this by:
- Adding a [Filter Data by Values Transform](https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#filter-data-by-value) 
- Use [Ad Hoc Filters](https://grafana.com/docs/grafana/latest/variables/variable-types/add-ad-hoc-filters/#create-ad-hoc-filters) (this will filter all data in dashboard)
