### ISSUE TITLE
Datalink variable not getting updated in table plugin when sorting/filtering

### ISSUE THREAD

**Issue by mak1986** [grafana/grafana#32911]
**What happened**:
Datalink property with variable not getting updated when sorting/filtering rows. 
For example if we add a datalink property to id field.
`https://example.com/items/${__data.fields.id}`

And we have a simple table like this one:

| id | name |
|----|--------|
| 1 | Peter |
| 2 | John |

If sort by name we'll get

|id | name|
|----|--------|
|2 | John|
|1 | Peter|

Now id 2 would link to `https://example.com/items/1` while id 1 would link to `https://example.com/items/2`

**What you expected to happen**:
The datalink should get updated after sorting/filtering. It should belong to the correct row.

**Environment**:
- Grafana version: 7.5.3
- Data source type & version:  grafana/grafana:7.5.3-ubuntu
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: All OS, All browsers
- Grafana plugins: Table Plugin

**Comment by hugohaggmark** [comment]
Thank you for reporting this @mak1986, this issue is fixed by #32571 and will be released in Grafana 7.5.4.

**Comment by mak1986** [comment]
@huanggze Thank you!. I did a search on existing issues but couldn't find any related to the bug.
