### ISSUE TITLE
Remove Service based Migrations

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#32912]
The order of migrations is important. We currently have two problems:
 - Migrations change order over time, they a per_table (see https://github.com/grafana/grafana/issues/11090). This means any relational migrations are problematic.
 - **This issue is about this one:** With NG/Unified Alerting (edit: now moved), and Library Panels, the order of migrations will get more confused, as the migration order depends on the registry and its order.

For example:

```
// AddMigration defines database migrations.
// If Alerting NG is not enabled does nothing.
func (ng *AlertNG) AddMigration(mg *migrator.Migrator) {
	if ng.IsDisabled() {
		return
	}
	store.AddAlertDefinitionMigrations(mg, defaultIntervalSeconds)
	store.AddAlertDefinitionVersionMigrations(mg)
	// Create alert_instance table
	store.AlertInstanceMigration(mg)

	// Create alert_rule
	store.AddAlertRuleMigrations(mg, defaultIntervalSeconds)
	store.AddAlertRuleVersionMigrations(mg)
}
```

Since both of these are still under a feature flag, I think we should remove service based migrations (for anything but `sqlstore`) before 8.

More generally, if we do ordered based migrations like the reference suggests then service based migrations might be okay.

Side note: For the alerting migration, I expect that migration code is going to look worse. Because I have to modify tables like `dashboard` and `dashboard_acl`, so the current migrations on those tables is going to get a lot "Do Not Touch This" comments, else future upgrade could break.

**Comment by hugohaggmark** [comment]
@kylebrandt if I remember correctly, library-panels have been moved as suggested. Is there anything else to be done or can we close this?

**Comment by kylebrandt** [comment]
@hugohaggmark Can be closed I think, so closing. Thanks for the ping :-)
