### ISSUE TITLE
Table link bug on Influx if column sorting

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#32922]
**What happened**: The value of the dynamic link placed on the cell is incorrect if I sort it by one of the columns in the table.

**What you expected to happen**: The error occurs in the new table format. In the old case, this did not happen. As soon as I perform a snapshot, the error clears.

**How to reproduce it (as minimally and precisely as possible)**: Influx database required. This is an example Influx query:

`SELECT last("mon_valt_mai_vart"), last("mon_percent_vart")
FROM "ctmon" 
WHERE ("mon_valt_mai_vart" > 400) AND ("mon_percent_vart" > 50) AND $timeFilter 
GROUP BY time(10m), "id"`

Add a link to the 1st column:

![image](https://user-images.githubusercontent.com/2911588/114502474-20ef9b80-9c2c-11eb-8d7e-7ec2257fdd40.png)

The dinamic link is **ready**:

![image](https://user-images.githubusercontent.com/2911588/114502563-454b7800-9c2c-11eb-95c9-0ce470eae8a5.png)

Change the ordering of the 2nd column:

![image](https://user-images.githubusercontent.com/2911588/114502606-58f6de80-9c2c-11eb-9c38-bfe2213a97f4.png)

You can see that the value of the variable is **wrong**:

![image](https://user-images.githubusercontent.com/2911588/114502692-7b88f780-9c2c-11eb-9196-b17f53d69e2c.png)

**Environment**:
- Grafana version: v7.5.2 (ca413c612f)
- Data source type & version: InfluxDB v1.8.0 
- OS Grafana is installed on: CentOS
- User OS & Browser: Chrome 89.0.4389.114
- Grafana plugins: Table

**Comment by hugohaggmark** [comment]
Thank you for reporting this @sanchomuzax, this issue is fixed by #32571 and will be released in Grafana 7.5.4.
