### ISSUE TITLE
Dashboard tab is missing when configure Google Cloud Monitoring datasource

### ISSUE THREAD

**Issue by barrowkwan** [grafana/grafana#32920]
**What happened**:
Add Google Cloud Monitoring but dashboard tab is missing in datasource configuration

**What you expected to happen**:
Expected to see dashboard tab in Google Cloud Monitoring datasource configuration

**How to reproduce it (as minimally and precisely as possible)**:
Enable Goolge Cloud Monitoring datasource, go to configuration,  dashboard is missing

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.1.5 (9893b8c53d)
- Data source type & version: Google Cloud Monitoring 
- OS Grafana is installed on: Kubernetes
- User OS & Browser: OSX & Chrome
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
@barrowkwan out of the box dashboards was added to the Cloud Monitoring datasource in [7.3](https://grafana.com/docs/grafana/latest/release-notes/release-notes-7-3-0/). You need to upgrade grafana to get this feature.
