### ISSUE TITLE
Prometheus Template Queries against /api/v1/series do not respect HTTP Method setting

### ISSUE THREAD

**Issue by kfdm** [grafana/grafana#32921]
**What happened**:

When using Prometheus with template variables, the queries against the `/api/v1/series endpoint`, still put parameters into the URL query string hitting a query length limit regardless of [http method](https://grafana.com/docs/grafana/latest/datasources/prometheus/#prometheus-settings) setting

**What you expected to happen**:

When configuring POST, it should POST all values in only the post body

**How to reproduce it (as minimally and precisely as possible)**:

1. Create datasource with Prometheus and set method to POST
2. Create a series [template](https://grafana.com/docs/grafana/latest/datasources/prometheus/#templating). Example
    `label_values(up, instance)`
3. When grafana queries the endpoint, the query will look something like this

`http post https://prometheus.example.com/api/v1/series?match[]=up`

`match[]`, `start`, `end` will all be part of the query parameters instead of being part of a POST body.

POST support for the series endpoint was added in prometheus [2.9.0](https://github.com/prometheus/prometheus/releases/tag/v2.9.0)

> [ENHANCEMENT] Add support for POSTing to /series endpoint. #5422

It looks like part of this was attempted in https://github.com/grafana/grafana/pull/31401

though it seems like the series query is still not constructed correctly

https://github.com/grafana/grafana/blob/183a89b576e5960996152cf494694038bb8197f7/public/app/plugins/datasource/prometheus/metric_find_query.ts#L92

https://github.com/grafana/grafana/blob/183a89b576e5960996152cf494694038bb8197f7/public/app/plugins/datasource/prometheus/metric_find_query.ts#L170

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.5.2 (ca413c612f)
- Data source type & version: Prometheus 2.25.2 
- OS Grafana is installed on: Linux-3.10.0-514.21.2.el7.x86_64-x86_64-with-centos-7.3.1611-Core
- User OS & Browser: Chrome

**Comment by hugohaggmark** [comment]
Passing this to @grafana/observability-squad

**Comment by GustavJaner** [comment]
Having a similar issue with dashboards using prom template queries after upgrading from v7.4.2 to v7.5.3. The same prom query used directly from a panel or explore works fine, but when used from a template query variable (to the same prom data source) it gives the following error:
```
Templating [instance]
Error updating options: When Content-Type:application/x-www-form-urlencoded, URL cannot include query-string parameters (after '?'): '/default/api/v1/series?end=1619006523&match%5B%5D=prometheus_build_info&start=1619002923'
```
