### ISSUE TITLE
Docs feedback: /http_api/snapshot.md

### ISSUE THREAD

**Issue by StephanRhode** [grafana/grafana#32939]
Hi there, I am new to Grafana and wanted to use the snapshot api to generate a snapshot as in UI. Basically, click a button and store all data and figures in a snapshot. After some failure I found that the user has actually to provide the entire dashboard model (includung the data) to the snapshot api, which was at least to me not intuitive.

Could you add some hint that snapshot api does not all in once? I guess many users would expect that.

**Comment by mckn** [comment]
Thank you for giving this feedback. @oddlittlebird what do you think about this suggestion?

**Comment by oddlittlebird** [comment]
@achatterjee-grafana is the main owner of the Grafana OSS docs, so I'll pass it to her.

**Comment by achatterjee-grafana** [comment]
Hello @StephanRhode, thank you for the feedback. I am looking at our snapshot API doc for creating a snapshot https://grafana.com/docs/grafana/latest/http_api/snapshot/#create-new-snapshot. We do mention in the JSON Body schema section that dashboard is a required property: "dashboard – Required. The complete dashboard model."

Can you specify what additional information will be helpful. 

Also, adding @marefr, who is our SME.

**Comment by StephanRhode** [comment]
I just started to use Grafana. The sentence "The complete dashboard model" does make sense if you are familiar with the term dashboard model. If you are new it, it does not resolve to: complete dashboard model := all dashboard settings and all metric data. So you would need to know in detail what a dashboard model is.

At beginning I expected to schedule a snapshot via API and get a complete snapshot like in UI. But now it seems, I would need to write some script to first scrape the data from metrics, write a dashboard model..., and then I can use the snapshot API to store it. So the snapshot API does "just" a small part of what expected.

If you could give a hint that the snapshot API endpoint is designed for the UI and does not create a complete snapshot with data, it would be helpful for people looking to somehow store a snapshot of an interactive dashboard via some API command.

**Comment by marefr** [comment]
Updating https://github.com/grafana/grafana/blob/master/docs/sources/http_api/snapshot.md as author suggest is probably a good idea. Something along these lines?

```md
# Snapshot API

## Create new snapshot

`POST /api/snapshots`

Creates a new snapshot. 

> Note: When creating a snapshot using the API you have to provide the full dashboard payload including snapshot data. This endpoint is essentially designed for the Grafana UI.

**Example Request**:
```

**Comment by achatterjee-grafana** [comment]
Fixed.
