### ISSUE TITLE
Build: when docs generation is failing the build is still marked as green.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#32931]
**What happened**:
When the `api-extractor` failed to extract docs from a package the build still continues to run and is being marked as green. This will cause subsequent builds to fail further down the pipeline.

**What you expected to happen**:
If the docs could not be exported we need to fail the build to prevent potential issues being merged to master.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a `export * as util from './utils` line in any of the `@grafana/*`-packages.
2. Run `yarn packages:build`
3. Run `yarn packages:docsExtract`
4. Look in the logs and you will see that the package containing the export have failed the api-extractor docs export.

**Anything else we need to know?**:
I think we probably should move the commands being run in the `yarn packages:*` to the gbpl.

**Environment**:
- Grafana version: n/a
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by leventebalogh** [comment]
Closing this, as we probably need to re-think how we would like to document plugin-related APIs in the future.
