### ISSUE TITLE
Stacked line graph changes colour when time series is removed

### ISSUE THREAD

**Issue by AdmiralGT** [grafana/grafana#32940]
**What happened**:

Dashboard line incorrectly changes colour. The line labelled `apply-si-fakeops-esc05` is yellow and is consistent at value 1 throughout. The line labelled `delete-si-fakeops-esc02` has value 1 at 12:05, disappears at 12:29. The line from 12:29 onwards is only the value of `apply-si-fakeops-esc05` but is shown blue, rather than yellow.

![image](https://user-images.githubusercontent.com/3476614/114551441-51026300-9c5b-11eb-9908-363c81d086e3.png)

**What you expected to happen**:

The line should be displayed with the correct colour.

**How to reproduce it (as minimally and precisely as possible)**:

Stacked line graph with 1 consistent time series.  Briefly add and remove other time series.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 6.7.0
- Data source type & version: Prometheus (actually Thanos Ruler, running Thanos v0.17.0)
- OS Grafana is installed on: Docker image
- User OS & Browser: Windows 10, Chrome Version 89.0.4389.114
- Grafana plugins: https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource
- Others:

**Comment by dprokop** [comment]
@AdmiralGT can you share the data from the panel and the panel JSON? You will find panel inspect helpfult to get it: https://grafana.com/docs/grafana/latest/panels/inspect-panel/

**Comment by torkelo** [comment]
this is expected when line series are drawn on top, the one drawn last will render top of the other

**Comment by torkelo** [comment]
disable stacking should fix this, think in later versions (7.4+) we changed the stacking logic to not interpolate so this should work with stacking in v7.4+
