### ISSUE TITLE
Grafana (7.5.3) Loki alert self-signed certificate

### ISSUE THREAD

**Issue by arnouthoebreckx** [grafana/grafana#32942]
**What happened**:
When using the newest feature alerting for Loki using the Loki datasource the alert cannot resolve the query because of an _x509: certificate signed by unknown authority” changing state to=alerting_ error. These same alerts worked before with the workaround of creating a Prometheus datasource pointed towards Loki.

**What you expected to happen**:
I expected the alert to properly be able to query.

**How to reproduce it (as minimally and precisely as possible)**:
This is a docker image with no explicitly extra certificates in /etc/ssl/certs but CACerts are added to the datasource config for each datasource.

1. Setup Loki datasource in Graph panel and create a query
2. Setup an alert for this query
3. Test alert and notice the X509 error

**Anything else we need to know?**:
The query for Loki does work properly in the graph view and even when done through Grafana Explore. In the Logs I notice that when the alert is triggered that Graphana uses the full URL to connect to the Loki datasource instead of the **/api/datasources/proxy/1/loki/api/v1/query_range?...** route.

In the snippet below you can see the query that is executed for the graph and the one by the alert.

> t=2021-04-13T07:57:55+0000 lvl=info msg="Proxying incoming request" logger=data-proxy-log userid=13 orgid=1 username=[user] datasource=loki **uri="/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1470&query=count_over_time(%7Bapp%3D%22app-test%22%7D%7C~%22(INFO%7CERROR)%22%5B5m%5D)&start=1618279075000000000&end=1618300676000000000&step=15" method=GET body=**

> 2021/04/13 07:01:01 https://[url]/loki/api/v1/query_range?direction=BACKWARD&end=1618297261129128621&interval=1&limit=1000&query=count_over_time%28%7Bapp%3D%22app-test%22%7D%7C~%22%28INFO%7CERROR%29%22%5B5m%5D%29&start=1618296961129128621&step=1
t=2021-04-13T07:00:01+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=6 name="Loki alert" error="tsdb.HandleRequest() error **Get \"https://[url]/loki/api/v1/query_range?direction=BACKWARD&end=1618297201154147598&interval=1&limit=1000&query=count_over_time%28%7Bapp%3D%22app-test%22%7D%7C~%22%28INFO%7CERROR%29%22%5B5m%5D%29&start=1618296901154147598&step=1\"**:  x509: certificate signed by unknown authority" changing state to=alerting

If the alert was also going through the /api/datasources endpoint it would use the CACert configured there and would function properly. 

**Environment**:
- Grafana version: 7.5.3
- Data source type & version: Loki
- OS Grafana is installed on: Openshift Cluster
- User OS & Browser: Windows & Google Chrome
- Grafana plugins:
- Others:

**Comment by steverweber** [comment]
https://github.com/grafana/grafana/issues/32856
https://github.com/grafana/grafana/issues/32533

Perhaps the developers will notice this is something users are looking for.
