### ISSUE TITLE
InfluxDB/Flux: Labels to fields transformation doesn't work properly with string fields

### ISSUE THREAD

**Issue by ModestTG** [grafana/grafana#32965]
**What happened**:
I have the following query
```
from(bucket: "telegraf_host")
  |> range(start: -1m)
  |> filter(fn: (r) => r["_measurement"] == "Tautulli: get_activity")
  |> filter(fn: (r) => r["_field"] == "f_hash")
  |> group(columns: [], mode:"by")
  |> drop(columns: ["host", "t_measurement", "t_location", "t_stream_count", "t_stream_count_direct_play", "t_stream_count_direct_stream", "t_stream_count_transcode", "_measurement", "_start", "_stop", "_field", "t_lan_bandwidth", "t_total_bandwidth", "t_wan_bandwidth"])  
  |> yield(name: "mean")
```
The `_value` value is a string. When I apply the "Labels to fields" transformation to this query, the field value disappears from my query and I get an incorrect visualization.

Before transform (all tags in header)
![pre_transform](https://user-images.githubusercontent.com/12620790/114647389-a44bd400-9ca2-11eb-8c9a-0c6faa3cb104.png)

After transform (value field missing)
![post_transform](https://user-images.githubusercontent.com/12620790/114647528-deb57100-9ca2-11eb-8f0a-03c39a293f27.png)

**What you expected to happen**:
Where `_value` is a string, the "Labels to fields" transformation should render string fields when transforming. Currently, it appears that this field is getting dropped when being transformed

InfluxDB screenshot of query
![influxquery](https://user-images.githubusercontent.com/12620790/114647816-56839b80-9ca3-11eb-9f55-f7511be02fe4.png)

**How to reproduce it (as minimally and precisely as possible)**:
Use a query that has a string for the `_value`. Include other tags in the query. Use the table panel for this query. Apply the "Labels to fields" transformation

**Anything else we need to know?**:
This does not appear to be an issue when `_value` is a number format (either `int` for `float`)

Number `_value` pre transformation
![int_pre](https://user-images.githubusercontent.com/12620790/114648171-00632800-9ca4-11eb-9b43-43eebab0dd76.png)

Number `_value` post transformation
![intpost](https://user-images.githubusercontent.com/12620790/114648195-0953f980-9ca4-11eb-9eec-f6db605d9e6f.png)

Query CSV from problematic query (redacted sensitive info, not important for this issue)
```
#group,false,false,false,false,false,false,false,false,false,false,false,false,false,false,false
#datatype,string,long,dateTime:RFC3339,string,string,string,string,string,string,string,string,string,string,string,string
#default,mean,,,,,,,,,,,,,,
,result,table,_time,_value,t_friendly_name,t_full_title,t_grandparent_title,t_media_type,t_parent_title,t_platform,t_quality_profile,t_stream_video_full_resolution,t_title,t_username,t_video_decision
,,0,2021-04-14T02:47:01Z,a7614f1180f61e1765b4aff8b10ba689,<REDACTED>,The Equalizer,,movie,,Chrome,3 Mbps 720p,1080p,The Equalizer,<REDACTED>,copy
,,0,2021-04-14T02:47:01Z,1729655bb531a1fc71925cd3d4b0cfd6,<REDACTED>,Castle (2009) - A Chill Goes Through Her Veins,Castle (2009),episode,Season 1,Roku,4 Mbps 720p,720p,A Chill Goes Through Her Veins,<REDACTED>,transcode
```

Thank you very much for taking a look at this. Let me know if you need more information.

**Environment**:
- Grafana version: Grafana v7.5.3 (3e3cf4dc60) (Docker: grafana/grafana:latest)
- Data source type & version: InfluxDB 2.0.4 (git: 4e7a59bb9a) build_date: 2021-02-08T17:47:02Z
- OS Grafana is installed on: Linux 4.15.0-135-generic #139-Ubuntu SMP Mon Jan 18 17:38:24 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- User OS & Browser: User OS: Microsoft Windows 10 Pro v10.0.19041 N/A Build 19041. Browser: Firefox 87.0 (64 bit)
- Grafana plugins: grafana-worldmap-panel, grafana-clock-panel, simpod-json-datasource, grafana-piechart-panel
- Others:

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/observability-squad

**Comment by aocenas** [comment]
This seems to be specific to the data and that the column only contains labels but does not have any name itself. If there is a name it work the same way whether the values are strings or numbers. Not sure though why there is no name for the column in the first query.

**Comment by ModestTG** [comment]
Now that you point that out I am curious as to why no field name is listed there. I am archiving this information using the Telegraf `exec` input plugin. Utilizing JSON data.

Here is the snippet from Telegraf that is archiving this data. Note that I had to explicitly specify the `json_string_field` for the `fs_hash` field:
```
[[inputs.exec]]
  interval = "1m"
  timeout = "45s"
  data_format = "json"
  commands = [
    "/home/docker/code/scripts/python/tautulli/tautulli-get-activity.py"
  ]
  json_name_key = "t_measurement"
  json_string_fields = ["fs_*"]
  tag_keys = ["t_*"]
```

Here is a snippet of the code thaat the `tautulli-get-activity.py` script returns when run (redacted sensitive information):
```
[
  {
    "f_stream_count": 1,
    "f_stream_count_direct_play": 1,
    "f_stream_count_direct_stream": 0,
    "f_stream_count_transcode": 0,
    "f_total_bandwidth": 7804,
    "f_lan_bandwidth": 7804,
    "f_wan_bandwidth": 0,
    "t_username": "<REDACTED>",
    "t_full_title": "RWBY - The Stray",
    "t_friendly_name": "<REDACTED>",
    "t_title": "The Stray",
    "t_media_type": "episode",
    "t_parent_title": "Season 1",
    "t_grandparent_title": "RWBY",
    "t_stream_video_full_resolution": "720p",
    "t_video_decision": "direct play",
    "t_quality_profile": "Original",
    "t_platform": "Windows",
    "t_location": "lan",
    "t_measurement": "Tautulli: get_activity",
    "fs_hash": "9d31200e8894f0379031a0b60a5c0944"
  }
]
```

The `fs_hash` field is the field giving me trouble, and the one not showing up with the query in Grafana. Hope this additional information helps!

**Comment by aocenas** [comment]
@ModestTG can you check with the latest v8 beta version https://grafana.com/grafana/download/beta? We changed a bit logic in how the influx plugin transforms data which should be a bit more robust an maybe that will fix the naming issue.

**Comment by ModestTG** [comment]
It would appear that the issue was fixed in the version recommended! The rows appear to be showing properly now that the value is properly being showed. Thank you so much for the fix!

![test](https://user-images.githubusercontent.com/12620790/118891988-d4038280-b8c5-11eb-9539-937a49f91f8a.png)

**Comment by gabor** [comment]
@ModestTG i'm glad it helped! closing the issue.

**Comment by pgmillon** [comment]
Hi,
I'm experiencing the same issue when trying to show logs collected by telegraf stored into influxDB2:
```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "tail")
```
![image](https://user-images.githubusercontent.com/715479/123281296-ddf25400-d509-11eb-842c-e1cda7271bee.png)

**Comment by pgmillon** [comment]
I also tried to update the flux query with a group. The table view is "fine" but the regular view only shows the _value field even with an "Organize fields" transformation:
```

from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "tail")
  |> group(columns: ["message"])
```
![image](https://user-images.githubusercontent.com/715479/123285650-85bd5100-d50d-11eb-9eed-32cf5f7dcb69.png)
![image](https://user-images.githubusercontent.com/715479/123285700-91107c80-d50d-11eb-9b70-b5da7b4bab71.png)

**Comment by gabor** [comment]
hi @pgmillon , thank you for the detailed report, but, could you please create this as a new github issue? the original report was for an older version of grafana, where things worked differently, and this issue might have a different cause. so creating a new issue and describing the what-is-happening, what-i-wanted-to-happen again will help us not to mix things up. thank you.

also, please add this info:
- your version of grafana (i think you are running on the newest, but to avoid any misunderstandings, please write down your grafana version)
- the raw csv output from influxdb server for your flux queries. this is how you get that: go to the influxdb-ui (chronogfraf), explore-mode, enter your query, run it, and below the visualization there is a download-csv button. press it, download the csv, then please make sure you remove every secret/confidential info from it, and then upload it to the github issue (or just paste it into a comment in the github issue). this will help us find the problem faster.

thanks!

**Comment by pgmillon** [comment]
Sure, I created https://github.com/grafana/grafana/issues/36157 accordingly
