### ISSUE TITLE
HTTP dataproxy timeout - "http: proxy error: context canceled"

### ISSUE THREAD

**Issue by rejeevd** [grafana/grafana#32960]
**What happened**:
When the datasource query takes more than 15 seconds it times out. I have observed this in different datasources including InfluxDB as well as SIMPOD-JSON-DATASOURCE. I could see the below error in the grafana logs.
`t=2021-04-13T16:16:42+0100 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=2 orgId=2 uname=xxxxx@xxxxx path=/api/datasources/proxy/7/query remote_addr=127.0.0.1 referer=http://localhost:8087/cw/web/monitor/datasources/edit/7/ error="http: proxy error: context canceled"`
I have specified [dataproxy]/timeout = 600. Still the timeout happens at about 10-15 seconds.
Note: This was working in Grafana version 6.7.3

**What you expected to happen**:
As the query takes only about 22 seconds in the server side, I expected the queries to pass.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure how to reproduce.

**Anything else we need to know?**:
None

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: SIMPOD-JSON-DATASOURCE, INFLUXDB
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Mac OS Firefox
- Grafana plugins: INFLUXDB
- Others:

**Comment by aknuds1** [comment]
How did you arrive at the conclusion that this error is due to a timeout? Is it possible that the network request was simply dropped? It's impossible to conclude from the error message that the request is canceled due to a timeout.

**Comment by rejeevd** [comment]
This error happens consistently whenever the response takes more than 15 seconds. And, it never occurs before 10 seconds.
The API if I request from outside of Grafana it works without any issues.
Also, we never had this issue when we were using Grafana 6.7.3

**Comment by rejeevd** [comment]
Looks like the issue was on the client side. our calls to Grafana were going through a proxy and it was timing out.
Please consider this issue resolved for now. If it turns out otherwise I will reopen.
Sorry for the inconvenience.
