### ISSUE TITLE
Alert notification templating not working with Graphite tags

### ISSUE THREAD

**Issue by annelaurefroment** [grafana/grafana#32977]
**What happened**:
I created an alert on a graphite metric with a host tag 
![image](https://user-images.githubusercontent.com/49911675/114687944-d0209580-9d46-11eb-97e3-dc2d434d4a98.png)

and I'm getting this notification:
![image](https://user-images.githubusercontent.com/49911675/114688131-02ca8e00-9d47-11eb-816a-2c4911360b99.png)

**What you expected to happen**:
The ${host] is replaced by the tag value, as explained in the documentation:
https://grafana.com/docs/grafana/latest/alerting/add-notification-template/ 

**Environment**:
- Grafana version: 7.5.3
- Data source type & version: Graphite

**Comment by kylebrandt** [comment]
@wbrowne I would be curious if this gets converted to data frames, and tags become labels:
 - For Graphite to work properly will SSE (Server Side Expressions) it will need to be label based. I my current thinking is that this what will eventually allow alerts per series with the Graphite data source. If the data source doesn't do this, will need some sort of (extract labels/tags from series name) in expressions, which would get awkward.
 - Graphite didn't always support labels/tags I don't think - and I don't know enough about graphite myself to know what the right actions are.

**Comment by wbrowne** [comment]
Thanks for the info @kylebrandt  - was just thinking about this based on your comments regarding the SQL datasources. From what I have seen, Graphite supports tags/labels from version 1.1.x. Prior to that version, maybe we just don't support it or at least attempt some naive approach. Going to data frames makes sense to support this and hopefully we can prioritize that soon!
