### ISSUE TITLE
Table data links don't update when row order is changed

### ISSUE THREAD

**Issue by ProteusCortex** [grafana/grafana#32981]
**What happened**: I have a table, where each row has a data link that uses the _ID_ column. When changing the initial order of the rows, either by filtering or just sorting them using another column, the data links do not follow the new order. The result is that the data link points to the wrong _ID_.

![image](https://user-images.githubusercontent.com/1230251/114695086-e10bdf80-9d23-11eb-91de-67d01a8307b4.png)

As you can see in the above image, the data link of the 1st row points to the job order with _ID_ that was in the 1st row before sorting using the _ID_ column.

**What you expected to happen**: The data links should follow the new order of the rows, when sorted or filtered, just like the following image, showing the initial order of the rows and the data link pointing to the correct _ID_.

![image](https://user-images.githubusercontent.com/1230251/114695334-2b8d5c00-9d24-11eb-8df4-5f827f4c4538.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a table with some unique numbers.
2. Add data links to in the _Field_ tab that include a variable like `${__data.fields.ID}`, to include the column with the unique numbers.
3. Re-arrange the columns, either by filtering, or sorting using another column.
4. Check where the data links point to.

**Environment**:
- Grafana version: v7.5.3 (3e3cf4dc60)
- Data source type & version: MySQL 8.0.23-0ubuntu0.20.04.1
- OS Grafana is installed on: Ubuntu Server 20.04.2 LTS
- User OS & Browser: Chrome, Edge & Firefox (all at their latest versions) on Windows 10
- Grafana plugins: Only built-in plugins
- Others: -

**Comment by TimoL** [comment]
We see exactly the same issue with Grafana 7.5.3. We recently upgraded from Grafana 7.3.x, so I can't pin it down to a specific version update.

**Comment by TimoL** [comment]
Fix seems to be included in Grafana 7.5.4 release: https://github.com/grafana/grafana/commit/5e1d0a8851dc18893b663b44be14875f60c4e69b

**Comment by Yeins12** [comment]
I have exactly the same problem with data links of a table, the data links don´t follow follow the change of the new order,  is there some solution?

**Comment by Yeins12** [comment]
> Fix seems to be included in Grafana 7.5.4 release: [5e1d0a8](https://github.com/grafana/grafana/commit/5e1d0a8851dc18893b663b44be14875f60c4e69b)

It is right

**Comment by Basanon** [comment]
I have this issue right now
It also happen if field filter been applied

**Comment by Basanon** [comment]
Just installed 7.5.4 update on Windows
Issue fixed
