### ISSUE TITLE
How to make JSON dashboards aware of organizations?

### ISSUE THREAD

**Issue by rucek** [grafana/grafana#3298]
When I put a JSON file with a dashboard in the directory specified under `[dashboards.json]` in `grafana.ini`, the dashboard becomes visible in all organizations. Is there a way to make a given dashboard available only to a given organization?

I though it might work by creating subdirectories named after organizations in the dashboard directory, but unfortunately it didn't.

**Comment by torkelo** [comment]
file based dashboards are global (only meant to be used in a single org setup). If you have multiple orgs you can use the HTTP api to import dashboards.
