### ISSUE TITLE
SSL/HTTPS -- Grafana 2.5

### ISSUE THREAD

**Issue by rainmanh** [grafana/grafana#3299]
Guys

This is an ubuntu 1.404 box and Kibana 2.5 .. Installed the base debian package

I managed to have the SSL certificate working and everything seems all right "apparently" but it seems 
when I enable SSL  (https) grafana is NOT able of extracting data from the remote graphite sources.

When connecting to any of the remote graphite boxes it just says : the WEB UI just reports " Unknown error" and there is nothing else I can see in the log files.

I had the impression the https connection was for the WEB UI only but it seems it got a bit further than that..

Any idea?

Many thanks

**Comment by torkelo** [comment]
do you use proxy or direct data source access? If you use direct access (ie graphite is accessed directly from the browser), then HTTPs poses stricter CORS rules (you need to modify graphite to allow the grafana domain to access it)

**Comment by rainmanh** [comment]
@torkelo 
Going further on debugging this:
* hot a SelfCert -- SSL
Anf the request from grafana gets stuck but running this in debuging mode (chrome) I get the following:

``````
Mixed Content: The page at 'https://grafana.server:3000/datasources/edit/4' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://graphite.server/metrics/find/?query=*'. This request has been blocked; the content must be served over HTTPS.
``````

**Comment by torkelo** [comment]
as I said if you use HTTPS and have configured data sources for direct access your data sources also need to be under HTTPS (and special CORS options needs to be configured). You can switch to "proxy" access mode to work around these issues.

**Comment by rainmanh** [comment]
I realised about it immediately after but I wanted to keep all those lines as anybody else looking for information HTTPS related could find these traces and it could help a bit.
Your help is very much appreciated.
