### ISSUE TITLE
Add Hidden Series to the awesome Time series panel

### ISSUE THREAD

**Issue by oscni** [grafana/grafana#33013]
**What would you like to be added**:
The panel Graph has a Hidden Series override feature, the new Time series panel does not seem to have that. Would be great if that could be added.

**Why is this needed**:
When having lots of different data it is very nice to have a regexp and match so that only certain important values show up from the start.

**Comment by mckn** [comment]
Great feedback! This is possible if you do it manually (by clicking the series in the legend) and then save the panel. What this does is that it will generate a system override that does this and that one is persisted when you save the dashboard.

However it sounds like a good idea to make this override available in the UI as well so you can use it together with a regex.

**Comment by oscni** [comment]
Actually that's why I included the word regexp in the request :) It does only work to save when you always have the same name of the metrics. If the metrics names changes depending on time and filter then you would want to do regexp to define what should be shown from the beginning.

**Comment by dprokop** [comment]
This should be new fixed by https://github.com/grafana/grafana/pull/34783
