### ISSUE TITLE
Snapshot: Snapshot link causes an unauthorized error when we use dashboard links

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#33017]
**What happened**: When we open a local snapshot link that had dashboard links (which search for a dashboard tag and add a link in the dashboard) causes an unauthorized error as it is making a search call to Grafana.

<img width="355" alt="error" src="https://user-images.githubusercontent.com/65600879/114838512-65c52f00-9df2-11eb-9a17-ead66b67eafa.png">

<img width="960" alt="SnapshotError" src="https://user-images.githubusercontent.com/65600879/114841264-44b20d80-9df5-11eb-8710-88cf11f0ad8b.png">

**What you expected to happen**: It should not make search call and cause error.

**How to reproduce it (as minimally and precisely as possible)**: 

- Create a dashboard with a dashboard link that will search with a tag. 
- Now generate a local snapshot on it and try opening it then we will face an unauthorized issue.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.2 
- Data source type & version: Any
- OS Grafana is installed on: Any
- User OS & Browser: Windows, Chrome
- Grafana plugins: Any
- Others:

**Comment by torkelo** [comment]
The solution here is to remove dashboard links in snapshots, Dashboard links require the use of the search API which is not always available in snapshots as they are supposed to only contain captured data and to support anonymous viewing. But only remove dashboard links, static links can remain. 

https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/ShareModal/ShareSnapshot.tsx#L112

**Comment by torkelo** [comment]
So to fix this filter out type === 'dashboards' of the dashboard.links array as art of the scrub snapshot 
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/ShareModal/ShareSnapshot.tsx#L112
