### ISSUE TITLE
doc reference http_api -> Change Password not work

### ISSUE THREAD

**Issue by JerryXia** [grafana/grafana#3301]
I look the http_api doc(http://docs.grafana.org/reference/http_api/#change-password), when i'm trying to change user pasword, the server return unauthorized httpstatuscode.

I found the success request parameters

    PUT /api/user/password HTTP/1.1
    Accept: application/json
    Content-Type: application/json
    Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

    {
        "oldPassword": "old_password",
        "newPassword": "new_password",
        "confirmNew": "confirm_new_password"
    }

and it return is not  `{"message":"User password updated"}`, it should be `{"message":"User password changed"}`

Sorry, my english is not good !

**Comment by torkelo** [comment]
thanks for informing me! fixed!
