### ISSUE TITLE
interval variable name is used as a Step in Explore

### ISSUE THREAD

**Issue by adivinho** [grafana/grafana#33018]
**What happened**:
Interval variable is passed to Explore as a variable name but not as a value

**What you expected to happen**:
It should be passed a value of used interval or Step shouldn't be set at all.

**How to reproduce it (as minimally and precisely as possible)**:
Use an interval variable ($interval) as a Min step parameter
![Screenshot_20210415_114237](https://user-images.githubusercontent.com/25184101/114841751-dcf1c780-9de0-11eb-811a-355d34b4fef3.png)

Jump to Explore by element drop-down link.
![Screenshot_20210415_120331](https://user-images.githubusercontent.com/25184101/114843568-9f8e3980-9de2-11eb-875b-3b51c402a0c7.png)

Explore Step parameter gets the variable name as a value and can't perform a query. 
![Screenshot_20210415_114303](https://user-images.githubusercontent.com/25184101/114841760-dfecb800-9de0-11eb-8987-57b8211562f4.png)

**Environment**:
- Grafana version: 7.5.4-1

**Comment by zoltanbedi** [comment]
Related to https://github.com/grafana/grafana/issues/31293. We need to make sure that the variable interpolation is consistent in explore.

**Comment by davkal** [comment]
Note that `$interval` is a template variable, and not a built-in variable.
