### ISSUE TITLE
Links wrong in sorted tables

### ISSUE THREAD

**Issue by iridos** [grafana/grafana#33021]
Starting from 7.5.3, links in a table use the text from the wrong table element in the link, depending on sorting of the table.
It looks like the link texts are not updated when the table is re-sorted to reflect the new values in the field:

E.g. there is a column "user" with users A,B,C,D. In the "overrides" menu, a link is defined for the field "user" like this:
https://localhost/grafana/d/CgRW/usage-by-user?orgId=1&var-user=${__data.fields.user}

In one sorting, links are correct and the 2nd entry "B" leads to a link for user "B". 
But clicking on the column to re-sort the table so that the second entry now is "C", the link still from that field  contains the username "B".

**Comment by TimoL** [comment]
Hi @iridos, see #32981, issue should be fixed in Grafana 7.5.4.

**Comment by iridos** [comment]
Hi, 
oh nice!
Didn't find #32981 for some reason :(

And I could have sworn that I started out writing the bug report from 7.5.4, but I just tested again and it is gone. Seems the automatic updates don't automatically restart the server and I was still on 7.5.3 then. Too late to check for that now, though.

Thank you.
