### ISSUE TITLE
Grafana Alert does not send all affected series

### ISSUE THREAD

**Issue by robert8103** [grafana/grafana#33030]
**What happened**:
I’m facing currently a bug with the alert messages (in slack).
I have got a dashboard with multiple series.
If the alert rule meets less or equal to 6 series everything is fine.
If there are more than 6 I only get the first 6 series are shown in the message (slack).
**What you expected to happen**:
![dashboard](https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/7/7d6f3b82efacd0540e32e02f25fa7d539a04eafd.png)
In that case I would expect to get all series that are below 7.7 (should be 10 series) not only the first 6 (1, 3, 4, 5, 6, 7)
**How to reproduce it (as minimally and precisely as possible)**:
Create a chart with multiple series at least 7 and set an alert on it use a slack channel to get notified.
Set the alert rule to be triggered to at least 7 series.
You would find all affected series in the alert history but only the first 6 will be sent via slack.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: Postgres (SQL query)
- OS Grafana is installed on:  Grafana Docker Image
- User OS & Browser: OSX, Firefox
- Grafana plugins: grafana-piechart-panel,briangann-datatable-panel,mtanda-histogram-panel,doitintl-bigquery-datasource
- Others:

**Comment by dsotirakis** [comment]
@robert8103 thanks for spotting this, please let us know if you have any other problems with this!
