### ISSUE TITLE
Loki: create Derived Field from a Loki Label

### ISSUE THREAD

**Issue by raphaelquati** [grafana/grafana#33056]
**Environment**:
- Grafana version: v7.5.2
- Data source type & version: Loki 
- OS Grafana is installed on: Docker
- User OS & Browser: Edge (Windows 10)
- Grafana plugins: Cortex, Loki
- Others:

I'm trying to create a derived field, but it's not working.

The log is sent to Loki from a C# code. It uses OpenTelemetry, Serilog plus https://github.com/RehanSaeed/Serilog.Enrichers.Span and https://github.com/mishamyte/serilog-sinks-grafana-loki (configured to send log in json format)

So, TraceId field is sent to Loki as label, but Loki datasource [doesn't parse labels](https://github.com/grafana/grafana/blob/615c153b3a2e4d80cff263e67424af6edb992211/public/app/plugins/datasource/loki/result_transformer.ts#L407)

![LokiDerived](https://user-images.githubusercontent.com/815086/114937310-024bf900-9e14-11eb-9a41-a9d89c4622a3.gif)

**Comment by christoph-buente** [comment]
I think this is still the same with version 9.0.4., isn't it?

**Comment by christoph-buente** [comment]
@mckn @davkal We found a way to massage the original JSON log line to make the message field contain the trace id, so it would be detected. But this is really backward. I'm wondering how other people log the trace_id and have Grafana make it a clickable link.

**Comment by mckn** [comment]
@grafana/observability-logs do you know ☝🏻

**Comment by gabor** [comment]
hi @christoph-buente , @raphaelquati , yes, currently it's not possible to create derived fields from Loki labels.
the thing is, it's not recommended to put the `traceId` in Loki labels, because the set of label-values can become very large (see https://grafana.com/docs/loki/latest/best-practices/#use-dynamic-labels-sparingly )

conceptually the feature request (allow Loki to make derived fields from labels) makes sense 👍 , it's just the use-case of traceIds in labels is not recommended, sorry.

**Comment by christoph-buente** [comment]
@gabor thanks for the links. And similar to Prometheus, I understand the necessity to keep the cardinality of label-value combinations low.

When JSON logs are configured, does it mean I need to put anything that is not supposed to be a loki label inside the `message` string? That will cause additional string parsing to extract the information, which could have already been a separate value.

**Comment by gabor** [comment]
@christoph-buente , let me loop in the @grafana/loki-squad (they work on the loki database), they might have some tips about how best approach this problem.

**Comment by raphaelquati** [comment]
Hi @gabor,

I agree with you: high cardinality is bad. So we reconfigured our application to work correctly.
The nuget component we use supports to send TraceId (and others labels) as a field.

To me, this issue can be closed.

**Comment by MichelHollands** [comment]
> When JSON logs are configured, does it mean I need to put anything that is not supposed to be a loki label inside the `message` string? That will cause additional string parsing to extract the information, which could have already been a separate value.

@christoph-buente Additional string parsing is a very common way of working in Loki and is nothing to be afraid of. You might want to put a line filter expression so this processing is only done for lines that have a TraceId field.

**Comment by gabor** [comment]
considering the original issue has been resolved, i'll close this github-issue. if there are more questions about how to handle high-cardinality data in Loki, i recommend asking in the loki community at https://community.grafana.com/c/grafana-loki/41 . thanks all!
