### ISSUE TITLE
Generic HTTP CSV / TSV datasource plugin

### ISSUE THREAD

**Issue by addshore** [grafana/grafana#3305]
Timesires data is often stored in TSV or CSV files that slowly get appended to in cases where databases are not setup.

It would be great to be able to pull data such as this into grafana.

I started working on a datasource plugin for such a case https://github.com/addshore/grafana-tsv-datasource

This currently allows you to specify a TSV file over HTTP and load it into grafana.
It supports different column layouts so long as there is a date that can be parsed by JavaScript and a value in the mix.
It also supports files with and without data headings.

I open this for general tracking and to let people know there is some code that can kind of do this now!

**Comment by utkarshcmu** [comment]
+1

**Comment by mattttt** [comment]
:+1:

**Comment by tral** [comment]
+1

**Comment by mash0304** [comment]
+1. Must have feature.

**Comment by timani** [comment]
+1

**Comment by MacXatu** [comment]
+1

**Comment by paraita** [comment]
+1

**Comment by cherweg** [comment]
+1

**Comment by StanislavBG** [comment]
+1 

How is it possible to have so many cool plug-in as source and not have "drop a CSV" file as source ...

**Comment by LarsLarsLars** [comment]
+1

**Comment by tammytankian** [comment]
+1

**Comment by mjbayer** [comment]
+1

**Comment by granttr** [comment]
+1

**Comment by shivkumarr** [comment]
+1

**Comment by DavidWeber1990** [comment]
+1

**Comment by designerferro** [comment]
This would be nice. +1

**Comment by yanbin7** [comment]
+1, any update now?

**Comment by cariag** [comment]
This would be very useful, +1

**Comment by kikoncuo** [comment]
This was started in 2015 and still no updates. This would be a useful feature!

**Comment by josearodrigueze** [comment]
+1

**Comment by infa-kparida** [comment]
+1

**Comment by vatechie** [comment]
+1

**Comment by sundararajan93** [comment]
+1

**Comment by jmlmoreno** [comment]
+1

**Comment by gelicia** [comment]
There is a plugin like this available. https://grafana.com/grafana/plugins/marcusolsson-csv-datasource/ 

Does this help with what everyone was looking for?
