### ISSUE TITLE
Cards/Alerts: Alerts cards with long URL are overflowing

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#33053]
**What happened**:
![image](https://user-images.githubusercontent.com/30407135/114934819-b496b700-9e3a-11eb-979b-88c4b42aa567.png)

**What you expected to happen**:
I would expect URL to be wrapped and inside Card component.

**How to reproduce it (as minimally and precisely as possible)**:
Create any alert (loki/prometheus/influx) using devenv data source and then stop it. The unreachable URL is overflowing in the card. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.4

**Comment by axelavargas** [comment]
Hey @ivanahuckova 😄  I was trying to replicate this error but I was not able to do it, after some research with @thisisobate we discovered that was already fixed on this commit [here](https://github.com/grafana/grafana/commit/495345c0c24e42a065b02605817e29fe8f6ce1de#diff-46d3884376b6414bb67f5244264993844cd93f0e239ed5baff43e9abc805961e)
