### ISSUE TITLE
Invalid calculation of the X axis max for histogram with buckets

### ISSUE THREAD

**Issue by lnicot01** [grafana/grafana#33073]
**What happened**:
![bug](https://user-images.githubusercontent.com/54575435/115014024-1c3c1900-9eb2-11eb-9138-7e0cf5f50185.gif)
In this example, the 120 values are between 747.59 and 750.17 but the X axis goes up to 757  
It is a histogram with 5 buckets

**What you expected to happen**:  
Fix the calculation of the max value of the x axis

**How to reproduce it (as minimally and precisely as possible)**:  
Make a histogram with buckets with large values compared to the size of the range [min value - max value]

**Anything else we need to know?**:  
In the fie */public/app/plugins/panel/graph/graph.ts* - function *addXHistogramAxis* - line *724*  
Grafana adjusts the max value of the XAxis to ensure it has enough space for last bar (adding 1% to max and round with tick step):

`max = Math.ceil((max * 1.01) / tickStep) * tickStep`

But if 
- max value is large  
`max value = 750`
- and tickStep is small  
`tickStep = (max value - min value) / nb buckets = (750.17-747.59) / 5 = 0.5`

the 1% added represents `750 * 0.01 = 7.5`  
i.e. 15 bars `(7.5 / 0.5 = 15)`  
These are the 15 ticks that we see in the image after the bars!

We can changed the calculation to add 1% of **max-min** instead of 1% of **max**:

Old code:
```js
// Expand ticks for pretty view
min = Math.floor(min / tickStep) * tickStep;
// 1.01 is 101% - ensure we have enough space for last bar
max = Math.ceil((max * 1.01) / tickStep) * tickStep;
```

Fixed code:
```js
// Expand ticks for pretty view
max = Math.ceil((max + (max - min) * 0.01) / tickStep) * tickStep;
min = Math.floor(min / tickStep) * tickStep;
```

(the max value must be calculated before the min value because it uses it in its calculation)

I think this is the same problem as issue 32006.

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: Clickhouse
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10 / Chrome
- Grafana plugins:
- Others:

**Comment by leeoniya** [comment]
yes, this looks like a duplicate of #32006.

your proposed fix sounds reasonable, and was likely the original intent of that code.

as i mentioned in #32006, the histogram functionality is being completely rewritten into a new panel. the way it does bucket control and tick determination is entirely different and should achieve exact bar/tick alignment and x axis padding.

you can try out the new core logic in the last demo here: https://leeoniya.github.io/uPlot/demos/latency-heatmap.html

would you like to submit a PR for your proposed change?

**Comment by leeoniya** [comment]
new histogram panel does this correctly.
