### ISSUE TITLE
Sparklines or horizon graphs in table views?

### ISSUE THREAD

**Issue by victorhooi** [grafana/grafana#3308]
It would be awesome to have sparklines in Grafana's table view:

<img width="1069" alt="sparklines table" src="https://cloud.githubusercontent.com/assets/242632/11311267/dd69161c-8fb5-11e5-9a45-dc58b32f7b70.png">
Originally from https://github.com/grafana/grafana/issues/3219#issuecomment-158511101, https://github.com/grafana/grafana/issues/3219#issuecomment-158517982 and https://github.com/grafana/grafana/issues/3219#issuecomment-158518877

Or perhaps even better than sparklines - horizon graphs:

https://square.github.io/cubism/
https://square.github.io/cubism/demo/

This lets you use colour combined with height, to get much better vertical resolution.

<img width="1069" alt="screenshot 2015-11-22 08 49 16" src="https://cloud.githubusercontent.com/assets/243499/11320684/f31de94c-90f5-11e5-8209-978b8261cb65.png">

**Comment by vlaadbrain** [comment]
Yes, having the ability to have a column as a sparkline for the timerange of the dash, in addition to the timeseries aggregations like so...

![Edward Tufte - Sparklines](http://www.edwardtufte.com/bboard/images/0001OS-15656.gif)

note the dots on the line indicate where the aggregations are, like max, min, and current :) 

![Edward Tufte - Sparklines w/ normal ranges](http://edwardtufte.com.s3.amazonaws.com/Pysch_glucose_compare.png)

Above right is an example of a sparkline with a "normal range"  shaded bar .  possibly the normal range derived from annotations?

**Comment by ptitou** [comment]
+1

**Comment by voiprodrigo** [comment]
+1

**Comment by jtyr** [comment]
There is a simple plugin for horizon graph here:
https://github.com/creative-area/grafana-panel-plugin-horizon

You can test it with Docker like this:

```shell
docker run \
  -d \
  -p 3000:3000 \
  --name=grafana \
  -e "GF_INSTALL_PLUGINS=https://github.com/creative-area/grafana-panel-plugin-horizon/archive/master.zip;creative-area-horizon-panel" \
  grafana/grafana
```

Then access `localhost:3000` and create a new Dashboard with the Horizon Panel.

**Comment by robianson** [comment]
+1

**Comment by abctaylor** [comment]
The repo mentioned above doesn't look like it's receiving updates. Is there any likelihood this will be officially supported in new-style Grafana tables, in the same way overrides for gauges are possible? This would be immensely valuable.

**Comment by abctaylor** [comment]
@torkelo in a [blog post dated 2020](https://grafana.com/blog/2020/04/28/grafana-7.0-sneak-peek-new-table-panel-for-dashboards/) you mention sparklines could easily feature inside table cells. Is this likely going to happen? It would be awesome to have this functionality and much appreciated by the community.

**Comment by abctaylor** [comment]
This would still be really cool to have.

**Comment by abctaylor** [comment]
Looks like this can be done as follows:
![image](https://github.com/grafana/grafana/assets/30197206/8b4b8eb6-65dc-4aa5-848b-89c3a39f2a46)
![image](https://github.com/grafana/grafana/assets/30197206/8ce43eb2-1645-40f5-a46c-7d9a8ee0a015)

**Comment by codeincarnate** [comment]
Yes, this has been added already quite some time ago now but sadly the documentation is pretty sparse (and is not coming up at all in a google searches for me). That's something that we can look at adding

**Comment by abctaylor** [comment]
It would be awsome if thresholds could be used in sparklines too, to get a result like this:

![image](https://github.com/grafana/grafana/assets/30197206/f5584929-47e4-4969-819b-bfae59c2f6b3)

At present I don't see any thresholding options, just a single color choice.
