### ISSUE TITLE
[FeatureRequest]: [Time series panel] Rename mean to average in legend

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#33094]
**What would you like to be added**:
Old graph panel has "avg" label in the legend. It has been renamed to "Mean" in the new time series panel.
![image](https://user-images.githubusercontent.com/19311511/115121863-40cce980-9fb5-11eb-864c-1f7e56c124a6.png)

**Why is this needed**:
I think "average" or "avg" is more common word and it is easier to understand it, especially for people whose English is not native language. Those people may not understand the mean word meaning.

**Comment by tfylling** [comment]
In mathematical terms average and mean are close, but not synonymous. Mean without a qualifier is usually taken to mean arithmetic mean, which is synonymous to average. However there are also geometric mean and harmonic mean, which aren't. That said, I don't really mind this change as I think it presents slightly better. As for non-english speakers, I guess the understandability depends on what the terms are in their native language. Maybe it could just be second choice in the Legend values drop down as a simple fix?
