### ISSUE TITLE
[Time series panel] Shared tooltip does not work

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#33093]
**What happened**:
Shared tooltip and shared crosshair does not work with time series panel.
I have tested it with two time series panels and with time series & graph panel.
![image](https://user-images.githubusercontent.com/19311511/115120004-69e87c80-9fab-11eb-835e-86d60d184167.png)

**What you expected to happen**:
It should work the same way as with two graph panels.
![image](https://user-images.githubusercontent.com/19311511/115119923-170ec500-9fab-11eb-8579-19c349a6e8ba.png)

**Environment**:
- Grafana version: 7.5.4

**Comment by dprokop** [comment]
Shared tooltip support added in v8.0.0-beta1
