### ISSUE TITLE
[Time series panel] Tooltip shows only current value

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#33091]
**What happened**:
When there are 2 queries on time series panel which are sent with different frequency, the tooltip shows only the "current value".
![image](https://user-images.githubusercontent.com/19311511/115119537-24c34b00-9fa9-11eb-8944-9d23e40d2239.png)

**What you expected to happen**:
Old "Graph" panel showed both values
![image](https://user-images.githubusercontent.com/19311511/115119596-8388c480-9fa9-11eb-8319-f984dfd41030.png)

There should be an option like "Show last not null" for the tooltip.

**Anything else we need to know?**:
I had a Tooltip mode set to All

**Environment**:
- Grafana version: 7.5.4

**Comment by torkelo** [comment]
This is a bug fixed in time series panel, the old Graph showed values very far from where you where hover

**Comment by szerwi** [comment]
@torkelo What do you think about adding option to display last value, even though the time is different?
I have a graph on which one value is sent every 10 seconds and the other is sent every 10 minutes. In this situation it is hard to hover  the mouse on the point to display the second value.

**Comment by torkelo** [comment]
No, so many options already.

Why is it hard to move mouse to the datapoint you want to inspect?

**Comment by szerwi** [comment]
@torkelo I normally use this panel with 24h timerange. In this situation the interval is 1m, so each point is really close to each other. 
The second value on my panel is being sent every 10min (for example at 12:00, 12:10, 12:20).
When I move the mouse about 1mm to left or right, the graph switches to 12:01 and I cannot see the second value (only the first one which is sent every 10 seconds).

**Comment by leeoniya** [comment]
i wonder if we should make a transform that can be used to align data to predefined intervals, like 1s, 5s, 10s, 15s...1m, 5m, 10m.

this would trade timestamp accuracy for better aligment.

**Comment by szerwi** [comment]
So, do you plan to add an option like show last not null for the tooltip or something similar?

**Comment by retrodaredevil** [comment]
@szerwi I'm having this problem after making the jump from Grafana 7 to Grafana 10. Did you end up finding a good solution?

Additionally, I'm also having trouble getting data points to correctly stack when their frequencies are different. Might be related, but could be unrelated.
