### ISSUE TITLE
[Time series panel] Time labels are cut

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#33092]
**What happened**:
In specific conditions, time lables on time series panel are cut.
![image](https://user-images.githubusercontent.com/19311511/115119724-28a39d00-9faa-11eb-8194-3e5587103601.png)
In this example, last time label is "17.04 18:00", but last two zeros are not visible.

**Anything else we need to know?**:
I have changed date&time formats in Grafana config, but I am pretty sure the problem also occurs on default date formats.

**Environment**:
- Grafana version: 7.5.4

**Comment by leeoniya** [comment]
yes, we still have to implement padding auto-sizing. i've added it to the todo list.

**Comment by szerwi** [comment]
I believe it had been fixed, as I haven't noticed that issue for some time now ;)
