### ISSUE TITLE
Grafana plots wrong values

### ISSUE THREAD

**Issue by nazco** [grafana/grafana#3311]
I've the problem that grafana plots a huge peak where no such peak is. The graphite-web interface also doesn't print it. I have three host with interfaces with arround 60Mbit/s without a peak but if I sum them up I get a huge peak of 450Gbit/s.

first host
![screenshot2015-11-22_17-24-10](https://cloud.githubusercontent.com/assets/1292551/11324837/f98b5074-913d-11e5-9f14-c0d90e0f86ae.png)

second host
![screenshot2015-11-22_17-24-23](https://cloud.githubusercontent.com/assets/1292551/11324838/f98efd78-913d-11e5-97c6-f49bc6311700.png)

third host
![screenshot2015-11-22_17-24-35](https://cloud.githubusercontent.com/assets/1292551/11324840/f98fdf18-913d-11e5-93e2-65bf84e95150.png)

the hosts together
![screenshot2015-11-22_17-24-46](https://cloud.githubusercontent.com/assets/1292551/11324839/f98f6af6-913d-11e5-88f3-2214118a71e5.png)

The Query to the graphite backend
> alias(scaleToSeconds(scale(nonNegativeDerivative(sumSeriesWithWildcards(ffrn.$gateways.freifunk-rhein-neckar.de.eth0.*.bytes, 1, 5)), 8), 1), 'rx+tx')

**Comment by nazco** [comment]
Well in between I found out that this doesn't happen if I first do the stuff to get bits per second and than sum them up.

**Comment by torkelo** [comment]
Grafana just plots the values received from graphite, so you will have to consult the graphite project. You can verify that the problems is in graphite or Grafana by either switching to Graphite png mode (in display options) and check the json returned by graphite in chrome dev tools (f12) network tab
