### ISSUE TITLE
PostgreSQL+TimescaleDB: no data retrieved for intervals below 1s when using $__timeGroup macro in Grafana 7.4.2+

### ISSUE THREAD

**Issue by paniterka** [grafana/grafana#33124]
**What happened**:
I use Grafana with PostgreSQL data source with TimescaleDB installed. 
In a query using $__timeGroup macro, when the interval determined by the UI is less than 1s (e.g. 200ms), the macro no longer gets translated to the correct time_bucket function. Instead, the interval passed to time_bucket function in these cases is "0s", which causes an error: "pq: period must be greater then 0". As a result, no data is returned from the database. See screenshot from the Query Inspector below.
This behavior is observed for all Grafana releases from 7.4.2 to 7.5.4. 
![incorrect_blur](https://user-images.githubusercontent.com/35473115/115239715-52320500-a11f-11eb-82ca-fc87aea48533.png)

**What you expected to happen**:
The interval is translated correctly between $__timeGroup and time_bucket, for example $__timeGroup(time, '200ms', 0) should be time_bucket('0.2s', time). The behavior was correct in previous Grafana releases. 
See attached screenshot from Grafana 7.4.1 for the exact same query: 
![correct_blur](https://user-images.githubusercontent.com/35473115/115239749-5c540380-a11f-11eb-8327-716085d53c0d.png)

**How to reproduce it (as minimally and precisely as possible)**:
Zoom in close enough on a time trace pulled in from TimescaleDB. 

**Environment**:
- Grafana version: 7.4.2+ 
- Data source type & version: PostgreSQL 12.5 + TimescaleDB 12 
- OS Grafana is installed on: Windows 
- User OS & Browser: Chrome 
- Grafana plugins: PostgreSQL

**Comment by hugohaggmark** [comment]
Passing this to @grafana/backend-platform

**Comment by ying-jeanne** [comment]
seems the bug is introduced by this pr: https://github.com/grafana/grafana/commit/d56c5285e213152c1a4b325da2e9fea6fca5881c, we need to keep the decimals to make sure ms works.

**Comment by marefr** [comment]
I opened a PR to resolve this

**Comment by paniterka** [comment]
Hello, thank you for tackling this @marefr ! I tested the feature today and it seems that there is still a rounding to 100ms going on - in Grafana 7.5.5 
`$__timeGroup(begin, '50ms',0) `
is translated to 
`time_bucket('0.1s',begin) ` 
and for intervals below 50ms, which seem to get rounded down to '0.0s', I get again the same error "pq: period must be greater then 0" as before.  Which makes the macro unusable for these timescales. Would it be possible to enable rounding to the millisecond, so the third digit after comma?

**Comment by marefr** [comment]
@paniterka care to open a PR? Or perhaps open a new bug issue targeting your specific problem. I was a bit unsure when fixing this the last time what kind of formats/rounding timescaledb supports. Tried to look in timescale repo, but couldn't really find any specification.

**Comment by paniterka** [comment]
@marefr So in Grafana 7.4.1 the macro is working just fine using arbitrary floats. I just checked and for example 
`$__timeGroup(begin, '0.1ms',0) as time` -> `  time_bucket('0.0001s',begin) as time`  
gives me a correct array of time points. 

I would argue that this is still the original bug :) from the outside it seems that starting from Grafana 7.4.2 all the interval values are arbitrarily rounded somewhere on the backend. Until 7.5.4 they were rounded up to the nearest second, and now in 7.5.5 they are rounded to 0.1 second, which doesn't solve the overall issue that there is some silent rounding with an arbitrary grain involved which eventually makes part of the drilldown in time unusable.

**Comment by marefr** [comment]
@paniterka the code is here https://github.com/grafana/grafana/blob/b2d4730ca1c0ed7919f2ca8cab5a4ffb2283c2b2/pkg/tsdb/postgres/macros.go#L112

Where the `1` in `%.1fs` denotes the number of decimals.
