### ISSUE TITLE
[FeatureRequest] Show source field for multi query LogQL

### ISSUE THREAD

**Issue by Morriz** [grafana/grafana#33121]
**What would you like to be added**:

In case of a multi logql query an extra column "Source" should be shown that is automatically populated with the query source.

**Why is this needed**:

To discern which query fetched which logs.

**Comment by Morriz** [comment]
I also added the following separate "accessibility" issue to address the lack of colors for this problem, but this issue here could be seen as the precursor story to that.

**Comment by hugohaggmark** [comment]
Passing this to @grafana/observability-squad

**Comment by ivanahuckova** [comment]
Actually, for each log line, we actually use refId (id of query row) to crate unique id. So this should be very easy to implement. I couldn't find any other issue/discussion regarding this, so keeping this open.

**Comment by ivanahuckova** [comment]
@Morriz Isn't this same as https://github.com/grafana/grafana/issues/33120, just different solution - color vs column?

**Comment by ivanahuckova** [comment]
I'll close this in favour of https://github.com/grafana/grafana/issues/33121. Feel free to reopen if I am wrong.
