### ISSUE TITLE
Docs feedback: /getting-started/getting-started.md

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#33131]
Under 'Step 3 Create a Dashboard' for item #1:
   "Click the + icon on the left panel, select Create Dashboard, and then click Add new panel."

the "Add new panel." ending should be updated to "Add an empty panel"

![image](https://user-images.githubusercontent.com/9828569/115265804-6dcfe800-a0ec-11eb-9229-2ebd872645c7.png)

**Comment by achatterjee-grafana** [comment]
Fixed with PR https://github.com/grafana/grafana/pull/33285.

**Comment by achatterjee-grafana** [comment]
Fixed with PR https://github.com/grafana/grafana/pull/33285.
