### ISSUE TITLE
Docs feedback: /installation/docker.md "User ID changes"

### ISSUE THREAD

**Issue by SebastianThorn** [grafana/grafana#33144]
Hello not sure if I'm missunderstanding the docs, but the gid of root is not 1 in my container.
Running: grafana/grafana:7.5.2

>= 7.3 | grafana | 472 | root | 1

```
# docker exec -it grafana bash
bash-5.0$ id -g root
0
bash-5.0$
```

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/docs-squad

**Comment by oddlittlebird** [comment]
@xlson, does this look right to you?

**Comment by achatterjee-grafana** [comment]
Assigning to @oddlittlebird. She has started investigation.

**Comment by SebastianThorn** [comment]
well, seems like this got fixed some time ago.
https://github.com/grafana/grafana/pull/32323

**Comment by xlson** [comment]
@SebastianThorn thanks for calling this out, you are correct.

I will close this issue.
