### ISSUE TITLE
invalid: compilation failed: error at :@xx:xx-xx:xx expected comma in property list, got LPAREN

### ISSUE THREAD

**Issue by Udayendu** [grafana/grafana#33143]
**What happened**: Grafana is unable to load data from InfluxDB. But data are visible in InfluxDB GUI and CLI.

**What you expected to happen**: Grafana should be able to read the data correctly from InfluxDB as its already there.

**How to reproduce it (as minimally and precisely as possible)**:
- Make sure to have a vCenter of 6.5 or 6.7 or 7.0 version with some hosts, vms, datastores, clusters in it.
- Deploy the InfluxDB first
- Get the token and update the telegraf.conf file and start the telegraf container
- Check the data in the InfluxDB ui for the specific bucket. It should be visible and your query should work.
- Then deploy the grafana from its latest docker image and configure the data source as mentioned in the below image
![image](https://user-images.githubusercontent.com/1809177/115349529-967ddd80-a1d1-11eb-8fc0-7b2ae0058136.png)
- You will see that data are not visible in the grafana dashboard and will show the error as mentioned in the issue subject line
![image](https://user-images.githubusercontent.com/1809177/115349636-b8776000-a1d1-11eb-9c8f-af0d7020021a.png)

**Dashboard Plugin**:
- I am using https://grafana.com/grafana/dashboards/8159 dashboard plugin
- But also tried with https://grafana.com/grafana/dashboards/12786 and the same result

**Anything else we need to know?**: The deployment is done on top of a CentOS 7 vm using docker images.

**Environment**:
- Grafana version: v7.5.4
- Telegraf: 1.18.1
- Data source type & version: InfluxDB: 2.0.4
- OS Grafana is installed on: Docker Image
- User OS & Browser: Windows & Linux (Chrome, Firefox, Edge)

**Docker Images**:
![image](https://user-images.githubusercontent.com/1809177/115350291-8f0b0400-a1d2-11eb-8b81-38e54219a99a.png)

**Comment by Udayendu** [comment]
[grafana_error_logs.txt](https://github.com/grafana/grafana/files/6341256/grafana_error_logs.txt)

Please find the attached error logs from grafana docker container.

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/observability-squad

**Comment by Udayendu** [comment]
A discussion is going on in the community about the same issue and they are expecting some query language issue: https://community.grafana.com/t/invalid-compilation-failed-error-at-xxxx-expected-comma-in-property-list-got-lparen/46315/3

**Comment by Udayendu** [comment]
This is a compatibility issue. I fixed it after downgrading the InfluxDB to 1.8.5
So closing this.
