### ISSUE TITLE
All Series in tooltip does not respect Hide Empty option

### ISSUE THREAD

**Issue by toote** [grafana/grafana#3314]
If you have a query that returns a lot of series that have no data, it is normal to activate the "Hide Empty" option. But if you also activate the "All Series" option for the Tooltip, the tooltip shows all series that have no values in the current graph. So you end up with a graph that looks as if it had a few series but can not check their values using the tooltip.

**Comment by torkelo** [comment]
this is not true, hide empty option is applied to the all series tooltip. At least in Grafana 2.x. 

Keep in mind that All is empty => all data points must be null

**Comment by toote** [comment]
I just realized I had an older version installed (1.9.1), my bad. Thanks for the quick response!
