### ISSUE TITLE
[FeatureRequest] Allow to create transform plugins

### ISSUE THREAD

**Issue by ralequi** [grafana/grafana#33154]
**What would you like to be added**: The ability to create plugins that adds a custom type of transform

**Why is this needed**: Some kind of data requieres some ad-hoc preprocess that may be too complex for the underlying DB.

Now a days this can be done by very complex queries repeated across many panels (which makes it hard to maintain) or by re-doing panel/datasource plugins to inject such kind of ad-hoc preprocesses. Probably a worse solution that the other one but sometimes, in fact, actually is the only possible way to do it.

**Comment by wbrowne** [comment]
@ralequi Is there any particular transformation operations that you're considering? It would be great if people would share their use case because it might be something we can contribute directly to Grafana's built-in transforms in the meantime. The idea of pluggable transforms is certainly interesting and one we will keep in mind for the future. 

Aside: Will also link a comment [here](https://github.com/grafana/grafana/issues/36228#issuecomment-897077347) made on the plugins platform roadmap issue that relates to this as well

**Comment by dosgood1968** [comment]
I would use this to find the ratio of a list of data series to another single or list of data series, without knowing in advance how many series are in each list.

For example, Query A can return N series of data, depending on template variables. Query B can return a single series.

My desired output is Query-A[0..N] / Query-B. 

I would extend this so Query B can also return more than one series. Every series in Query-A would be divided by one series in Query-B, matched by naming conventions.

The current math transform doesn't work if the number of series is unknown.

It would be great if someone could implement a more flexible math transform and plug it in. It would also be interesting to see a Transform that is scriptable via Javascript (for example), for arbitrary transformations. 

FWIW I have implemented this use case using a Plotly panel plugin. This solved my problem but required that I code the visualization as well as the transform. I would have preferred to use a built-in visualization and only code the transform.

**Comment by sympatheticmoose** [comment]
To provide an update, this isn't something we're looking at implementing as the complexity of introducing additional plugin types outweighs the benefits.

**Comment by adminy** [comment]
I believe the original request was custom javascript for field transform. Not sure why this became a plugin requirement.
