### ISSUE TITLE
Problems visualizing booleans in graph

### ISSUE THREAD

**Issue by Knocks83** [grafana/grafana#33151]
![image](https://user-images.githubusercontent.com/22529815/115365050-4e0bf300-a1c4-11eb-9e65-f08863102d32.png)

**What happened**:
The boolean value (the bubble popup below) doesn't show the value, while the numbers (bubble popup up) is shown correctly

**What you expected to happen**:
I expected the boolean value to be shown correctly (true/false or even 0/1 like the axis)

**How to reproduce it (as minimally and precisely as possible)**:
Add a query to a boolean to your graph

**Anything else we need to know?**:
Both Grafana and InfluxDB have been installed via apt

**Environment**:
- Grafana version: OSS v7.5.0-beta2 (a9077812d8)
- Data source type & version: InfluxDB 1.8.4
- OS Grafana is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: Windows 10 - Firefox
- Grafana plugins: None

**Comment by torkelo** [comment]
The new timeline panel coming in v8 will solve that https://github.com/grafana/grafana/pull/31973
