### ISSUE TITLE
Option to enable tooltips ordering display

### ISSUE THREAD

**Issue by Gueust** [grafana/grafana#3316]
When we have **many** (e.g. > 50) metrics displayed in the same graph (such as memory usage of processes, or CPU usage of machines), it can be very difficult to find for instance which curve is the highest or the smallest at a given time.

It then could be useful to have an option to order (in ascending or in descending order) the legend items when hoovering over a graph.

In my example, this can allow operators to find what process is consumming all the memory, or what machine is under heavy load.

I'm not sure I am clear enough in my description, do not hesitate to ask for more details.

**Comment by torkelo** [comment]
good idea, 

will close as this already proposed in , https://github.com/grafana/grafana/issues/1189
