### ISSUE TITLE
Grafana Alert Rules Error "tsdb.HandleRequest() error Error response from server: no org id (<nil>)"

### ISSUE THREAD

**Issue by Airray** [grafana/grafana#33197]
**What happened**:
alert rules error: "Execution Error: tsdb.HandleRequest() error Error response from server: no org id (<nil>)"
![alert rule error](https://user-images.githubusercontent.com/8575461/115487539-790d4a00-a28b-11eb-9f72-e06f2a5d5157.png)

data sources use Loki, and set up Custom HTTP Headers, Loki is work, but alert rules happened error message.
![X-Scope-OrgID](https://user-images.githubusercontent.com/8575461/115487950-40ba3b80-a28c-11eb-9f08-c81eb6766a92.png)

**What you expected to happen**:
The grafana alert rules have no error messages.

**How to reproduce it (as minimally and precisely as possible)**:
1. use Promtail send log to Loki (set up tenant-id=TEST)
2. Grafana Datasource add Loki and set up  Custom HTTP Headers (X-Scope-OrgID=TEST)
3. Create Loki alert, use alert rule test, you can see error  "Execution Error: tsdb.HandleRequest() error Error response from server: no org id (<nil>)"

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: grafana/loki:1.6.1 and loki 2.2.0 (chart 3.5.0)

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/observability-squad for initial investigation

**Comment by torkelo** [comment]
looks like the loki backend is not using the custom headers

**Comment by ivanahuckova** [comment]
Related to https://github.com/grafana/loki/issues/3608

**Comment by ivanahuckova** [comment]
I am wondering, if until grafana/loki#3608 is implemented, it wouldn't make sense to refactor to Prometheus client as  it allows to override and supports range query. @aocenas thoughts?

**Comment by ivanahuckova** [comment]
Waiting for https://github.com/grafana/loki/pull/3654

**Comment by owen-d** [comment]
Upstream is merged :) @ivanahuckova

**Comment by owen-d** [comment]
Revendoring PR is here: https://github.com/grafana/grafana/pull/33534
