### ISSUE TITLE
Docs feedback: /clients/promtail/installation.md

### ISSUE THREAD

**Issue by eduardoroliveira** [grafana/grafana#33192]
the configmap name in volume does not match the configmap name:
- name: promtail-config
        configMap:
          name: promtail-configmap
vs

apiVersion: v1
kind: ConfigMap
metadata:
  name: promtail-config
  namespace: loki

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/docs-squad

**Comment by oddlittlebird** [comment]
It seems like this is a Loki issue. Can you transfer it to the Loki repo?

I made this issue in the website repo to hopefully get this problem addressed. https://github.com/grafana/website/issues/4092

**Comment by achatterjee-grafana** [comment]
Closing, as the problem was addressed as per the comment above.
