### ISSUE TITLE
Customize dashboard persistent per user

### ISSUE THREAD

**Issue by ymora042** [grafana/grafana#332]
Hi,

We have grafana running in our environment, I would like to know if grafana provide the functionality to create dashboard persistent per AD user?

**Comment by unkn0wn404** [comment]
Will be very useful save dashboard's variables per user. I means each user want monitor different graphs (for example if you have graphs by each system customers). If you have graphs by metric 1,2,3,4,5, user1 always see only metric 1 and 2, but user2 want to check 3,4,5
