### ISSUE TITLE
Adding a new flow unit m3/h

### ISSUE THREAD

**Issue by vitorli** [grafana/grafana#33200]
Maybe I'm wrong, but I searched for this flow unit, I would like to see it in the m3 / h update or tell me if it is possible to make a custom unit
**What would you like to be added**:
Adding a new flow unit m3/h

**Why is this needed**:

for flow measurement

**Comment by hugohaggmark** [comment]
@vitorli we do have custom units https://grafana.com/docs/grafana/latest/panels/field-options/standard-field-options/#custom-units
