### ISSUE TITLE
Support data units with decimal prefixes

### ISSUE THREAD

**Issue by orivej** [grafana/grafana#3320]
Currently byte values can only be displayed with binary prefixes (e.g. 1000000 bytes is 976 KiB).
It would be great to have an option to select decimal data prefixes for byte values (e.g. 1000 KB).

Something like this in `public/app/core/utils/kbn.js`, but I am not sure about the names:
```js
  kbn.valueFormats.dbytes  = kbn.formatBuilders.decimalSIPrefix('B');
  kbn.valueFormats.dkbytes = kbn.formatBuilders.decimalSIPrefix('B', 1);
        text: 'data',
          {text: 'bytes (binary)',      value: 'bytes' },
          {text: 'kilobytes (binary)',  value: 'kbytes'},
          {text: 'bytes (decimal)',     value: 'dbytes'},
          {text: 'kilobytes (decimal)', value: 'dkbytes'},
```

@rroethof previously suggested this in #463.

**Comment by hubby2004** [comment]
@torkelo, @orivej 
I also think this will be a good feature. The KiB is more accurate but few people use it now. The KB, MB, GB, TB, etc. are what people are used to nowadays.
By the way @torkelo, great software!!

**Comment by efattibene** [comment]
This will be a good feature also for me.
Is it possible to have this feature implemented in a feature release?

**Comment by herver** [comment]
I think this can be closed, I submitted a PR that has been merged :smile: 
But it seems like we'll have to wait for Grafana 4.0 to see this released :cry:
