### ISSUE TITLE
Render and share link contains only one item of a multiselect variable

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#33216]
Hi everyone,

we have the issue, that not all selected variable items are in the share and render link. Only one item seems to be added.

**How to reproduce it (as minimally and precisely as possible)**:
- create a variable with multiselect
- create a graph with a query that contains this variable
- select 2 or more items in the variable
- click share on that graph
Then we only have one variable item is in this links

Link to dashboard is:
https://grafana.domain.de/d/cLUhzjXGz/1043046?orgId=22&var-query0=it-es-data07&var-query0=it-es-data09
Render Link on the graph is:
https://grafana.domain.de/render/d-solo/cLUhzjXGz/1043046?orgId=22&var-query0=it-es-data09&from=1618990114371&to=1619011714371&panelId=2&width=1000&height=500&tz=Europe%2FBerlin

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: Influx and Graphite
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04 & Firefox 85
- Grafana plugins: -

Best regards,
Patrick

**Comment by hugohaggmark** [comment]
Hi @Foxeronie and thank you for creating this issue, I can repro this but it needs a bit of more details. If you have 2 items selected and save that as the default for the dashboard everything works ok as shown in the working example below:

**Working example:**
https://play.grafana.org/d/qg1nUqXMk/render-and-share-link-contains-only-one-item-of-a-multiselect-variable-33216?orgId=1

But if you change the variable or navigate to an url containing a multi-select variable like below then the `Direct link rendered image` will only include the first variable value.
**Not working example:**
https://play.grafana.org/d/qg1nUqXMk/render-and-share-link-contains-only-one-item-of-a-multiselect-variable-33216?orgId=1&var-devices=eth0&var-devices=lo

**Comment by Foxeronie** [comment]
Hey hugohaggmark,
yes, we have the same behavior. If I select multiple items and save the dashboard including current values, the rendered image contains all of the data.
As soon as I select more, the link only seems to have the last selected value.
When I select less, the last item in list seems to be used.
This also happens to any other variable, if you change the value of another one.

**Comment by shanson7** [comment]
We have the same issue. Manually adding the extra `&var-VarName=Value` to the image render link seems to work as expected. So this seems to just be an issue when creating the link text.
