### ISSUE TITLE
Docker build fails with missing git binary using the Dockerfile.ubuntu version

### ISSUE THREAD

**Issue by szatmari** [grafana/grafana#33223]
Failed to execute ```docker build -f Dockerfile.ubuntu .``` because of missing git binary.

Git tag: 7.5.4

```
Step 5/35 : RUN yarn install --pure-lockfile
 ---> Running in 27040ab8b9c5
yarn install v1.22.5
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Couldn't find the binary git
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

https://github.com/grafana/grafana/commit/f917c2ab0fdce4af5c63cf9f19475045d654894e misses addig git installation to the Dockerfile.ubuntu.

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/backend-platform

**Comment by dsotirakis** [comment]
Thanks a lot @szatmari for spotting this, actually related to https://github.com/grafana/grafana/pull/31802, but will do the same for `Dockerfile.ubuntu` also now :)
