### ISSUE TITLE
[Feat Req?] Send notification over existing channel API

### ISSUE THREAD

**Issue by LuKePicci** [grafana/grafana#33231]
**What would you like to be added**: I was looking for an API to create and send a notification via an existing notification channel. It should be the opposite of [alerting_notification_channels/#delete-alert-notification-by-id](https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/#delete-alert-notification-by-id) and somehow similar to [alerting_notification_channels/#test-notification-channel](https://grafana.com/docs/grafana/latest/http_api/alerting_notification_channels/#test-notification-channel) but with meaningful notification contents. Does it exist already outside of the docu?

**Why is this needed**: I have a custom table panel with buttons on each row to manually notify someone about that entry in case alerting didn't get triggered because of exceptional unpredictable data (let's say false negatives from a supervised ML model). This is not a privileged action, so it doesn't make sense to me letting a dashboard user to create a temporary alert rule for that log entry to be notified.

The only dirty workaround I can think to is to send my manual notification intention to a different index and tell grafana to alert whatever entry happens to be inserted in that index, but this wouldn't be realtime as that notification will be sent out on the next alerts rules evaluation. I'm open to any advice about that, but I really think there should be an API to manually send a notification (maybe using an existing "alert notification template" which I'd rather call "notification template" instead).

Cheers,
-LuKe

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/backend-platform

**Comment by marefr** [comment]
Thanks for your request. This is out of scope for the alerting feature and alert notifications are not really built for usage outside of alerting why I'm eager to close this. Sounds more like you're interested in a general purpose notification solution. If you rewrite your issue title/description explaining what you need and what problem that would solve without relating to alerting or alert notifications I'll reopen this.

**Comment by LuKePicci** [comment]
It's not related to alerting, it's all about notifications. I only mentioned alerts as a dirty workaround to get some notification pushed by abusing the alerting backend. I didn't even applied the alerting tag, this issue was moved here with this tag by @hugohaggmark

Of course the existing notifications backend appears to be somehow tight coupled to alerting so maybe you're still involved.

**Comment by marefr** [comment]
> It's not related to alerting, it's all about notifications. I only mentioned alerts as a dirty workaround to get some notifications pushed by abusing the alerting backend.

Rather than providing a dirty workaround please try explaining your problem without providing a solution. Thanks

**Comment by LuKePicci** [comment]
> Why is this needed: I have a custom table panel with buttons on each row to manually notify someone about that entry in case alerting didn't get triggered because of exceptional unpredictable data (let's say false negatives from a supervised ML model). 

I'm sorry if this was not clear enough.
