### ISSUE TITLE
Right Y-Axis issue on Graph and GraphWithLegend UI components

### ISSUE THREAD

**Issue by wburgos** [grafana/grafana#33242]
**What happened**:
On Graph and GraphWithLegend UI components, applying a right y-axis to a series doesn't make the values of this series use that axis.

**What you expected to happen**:
The Y-Axis on the right should match the values of the series it's attached to.

**How to reproduce it (as minimally and precisely as possible)**:
Go to https://developers.grafana.com/ui/latest/index.html?path=/story/visualizations-graph-graphwithlegend--graph-with-legend. On `Knobs`, write `B` in the `Right y-axis series` field. The right y-axis gets created and the legend for the B-series goes under this axis, but it is basically irrelevant to the B-series values, which still uses the left y-axis.

**Environment**:
- Grafana version: The one on developers.grafana.com

**Comment by ryantxu** [comment]
note that the graph component will be replaced with one based on uPlot -- the config options/structure is all a work in progress, but one of the key features in the new timeseries panel is MUCH better multi-axis support

In what context are you using this component?

**Comment by wburgos** [comment]
> In what context are you using this component?

I developed a custom panel to be able to use the Graph component with a JSON file as provisioning instead of a classic data source. I wanted to graph multiple series with one being a different unit, so I tried the right Y-Axis for this one.

**Comment by torkelo** [comment]
this component will be deprecated in v8 and will likely be removed in a future release.
