### ISSUE TITLE
New datasource

### ISSUE THREAD

**Issue by krocher5** [grafana/grafana#3324]
Hi,

I am thinking about writing a new datasource for Grafana. I looked through the existing datasource plugins, but I don't totally understand the concept behind them. Can anybody make a brief description as in what would be the steps in creating a datasource?

Cheers.

**Comment by addshore** [comment]
You may find this useful https://github.com/addshore/grafana-example-datasource

There are also a bunch at https://github.com/grafana/grafana-plugins

And I can also point you to https://github.com/addshore/grafana-tsv-datasource and https://github.com/addshore/grafana-wmfpageviews-datasource

**Comment by krocher5** [comment]
Thank you!
