### ISSUE TITLE
THE problem of Time series and monitoring function

### ISSUE THREAD

**Issue by LeeZChuan** [grafana/grafana#33252]
HI,

I have a question about the Time series and monitoring function of grafana, **that is, how does the time series and monitoring function of grafana work?** 

Read the latest data according to the refresh time granularity set by the user in advance?If not?Or other option？

Will grafana‘s real-time data reading burden our temporal database? I'm worried that reading in seconds by grafana will cause a lot of access burden to the time series database. If multiple users observe real-time data charts at the same time, the database will crash.

Can someone can tell me the reason behind it?

Thanks!

**Comment by torkelo** [comment]
The refresh rate of dashboards and the frequency of evaluation of alert rules is up to you you can set these to high values so they do not overload your database. For dashboard refresh there is a min refresh interval option you can set for the whole system
