### ISSUE TITLE
Docs feedback: /alerting/create-alerts.md

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#33250]
Images are a bit out of date. Might be worth a glance over the steps as well, to make sure they are still accurate.

**Comment by hugohaggmark** [comment]
@mjseaman this is a friendly reminder to add appropiate labels as `type/docs` to make the issue triage smoother for people on issue triage. Thank you.

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/docs-squad

**Comment by achatterjee-grafana** [comment]
We will be re-writing alerts for v8.0.

**Comment by hugohaggmark** [comment]
Should we close this issue then @achatterjee-grafana ?

**Comment by achatterjee-grafana** [comment]
Alerting will be an opt-in feature it seems like. Let me check with Daniel and Diana.

**Comment by oddlittlebird** [comment]
We will be writing new documentation for the new alerting feature, but the existing content will still exist. @achatterjee-grafana, perhaps we can update images as part of that rewrite, since we'll be touching both doc sets a lot during that time to compare/contrast/single source content.

**Comment by achatterjee-grafana** [comment]
Hi @mjseaman, considering we will deprecate legacy alerting in Grafana 9, can we close this issue?
