### ISSUE TITLE
Grafana -> OpenNMS: Finds nodes, but no resources?

### ISSUE THREAD

**Issue by mpursley** [grafana/grafana#3326]
Hey All, 

I'm running Grafana 2.5.0 and OpenNMS Web Console Version 1.12.3.

I've added the OpenNMS datasource plugin, from here...
https://github.com/OpenNMS/grafana/tree/features/opennms/public/app/plugins/datasource/opennms

I was able to add one of our OpenNMS machines as a Datasource.  I can see and search the nodes, but it doesn't show any #, lables, foreign IDs.  I can put a node name (fqdn) into the node field and hit query, but that just spins for ever.  See screenshots here... https://goo.gl/Rg0CzA

I don't see any obvious errors in the logs that I've found.  

Can anyone offer any suggestions of other things to try or look into?

Thanks!
Matt

**Comment by j-white** [comment]
You'll need OpenNMS 16.0.0 or higher for the integration to work.

As a note, the OpenNMS datasource plugin is in a fork of the Grafana project, so this doesn't really belong here. I've opened up the Issue tracking on the fork, let's use that for any follow ups.

**Comment by mpursley** [comment]
Yes, thanks.  I didn't see any issue tracking on the fork so figured I would post here... 

@torkelo Thanks for closing this one.  I will open a new ticket on the fork if I have more issues after the update.  

Thanks Guys,
Matt
