### ISSUE TITLE
Explore doesn't display errors in SQL queries

### ISSUE THREAD

**Issue by zsiciarz** [grafana/grafana#33273]
**What happened**:
In Explore, when executing an incorrect query against a Postgres datasource, database errors are not shown. There's no feedback in the UI what went wrong. When the query is correct, everything works fine and the results are displayed correctly.

**What you expected to happen**:
IIRC there used to be a red error bar which displayed the error message as returned from the database, when the query failed due to syntax/schema errors. 

**How to reproduce it (as minimally and precisely as possible)**:
Go to Explore, select a PostgreSQL datasource, switch from query builder to raw SQL and select Format as: Table. Then run the following query (note the missing `n` in function name): 
```
select versio();
```
There is no change in the UI, no error message, no results. On the other hand `select version();` should work fine and display Postgres version string. See the screen recording below:

![grafana](https://user-images.githubusercontent.com/182194/115719305-4131ff80-a37c-11eb-8856-19be3fb9e5e9.gif)

**Anything else we need to know?**:

The database error is coming back from the backend, there's a HTTP 400 response like this:

```
{"results":{"A":{"error":"pq: function versio() does not exist","refId":"A","meta":{"executedQueryString":"select versio();"},"series":null,"tables":null,"dataframes":null}},"message":"pq: function versio() does not exist"}
```

**Environment**:
- Grafana version: 7.4.3 and 7.5.4 running from Docker containers
- Data source type & version: PostgreSQL 9.6
- OS Grafana is installed on: Debian Linux
- User OS & Browser: Firefox 87 on Linux desktop, uBlock Origin disabled; also happens on Chromium 90.0.4430.72 
- Grafana plugins: no extra plugins beyond default
- Others:

**Comment by zsiciarz** [comment]
The error bar is there for Prometheus data sources, for example:
![image](https://user-images.githubusercontent.com/182194/115720374-4e032300-a37d-11eb-90a5-db442ea29cbd.png)

**Comment by martinemplo** [comment]
I have the same problem
Browser Google Chrome Version 88.0.4324.96

**Comment by hugohaggmark** [comment]
This seems to be fixed on master, maybe @grafana/observability-squad can add which PR fixed this?
