### ISSUE TITLE
Annotations: Input changes don't work properly

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#33277]
**What happened**:
I noticed that Loki query editor doesn't render in Annotations. I have found this PR https://github.com/grafana/grafana/pull/32903 that fixes issues with loading angular annotation query editors. I used the same fix for Loki and editor appeared. However, I noticed that I wasn't able to update line limit and type of query. I have tried it with different editor (Cloudwatch) and experienced the same problem.

**How to reproduce**:
Cloudwatch:
https://user-images.githubusercontent.com/30407135/115736862-eb655380-a38b-11eb-8396-12c5d59205f1.mov

Loki:
https://user-images.githubusercontent.com/30407135/115736841-e6a09f80-a38b-11eb-8858-b13a24c08ccb.mov

**Environment**:
- Grafana version: master b90ef261fd

**Comment by ivanahuckova** [comment]
fyi @jackw, @torkelo

**Comment by torkelo** [comment]
@ivanahuckova looking into this now
