### ISSUE TITLE
Plotting a counter on Singlestat panel

### ISSUE THREAD

**Issue by Akshaykapoor** [grafana/grafana#3327]
Hi,

I'm writing data to a influxDB in the format, 

**test_dev5 val=24 1448419500** which return a success after that

When trying to setup the value in Single stat panel, the value does not pop up on the panel, this is what the panel shows currently, 

![screen shot 2015-11-24 at 6 50 24 pm](https://cloud.githubusercontent.com/assets/2920022/11387096/46c3a54a-92dc-11e5-8ab7-ad7a73745f0f.png)

Is there something that i'm missing ?

**Comment by torkelo** [comment]
you can check what influxdb is returning using chrome dev tools (f12) / network tab. 

Maybe influxdb is not returning data?

**Comment by Akshaykapoor** [comment]
@torkelo thanks for that. The issue was not related to the data, rather time-stamp of the data (it was not correct in the place and hence not populating the correct value ).

But i have to appreciate you for the promptness of any queries asked, be it github/google-groups etc etc. I just love this tool, you're doing an amazing job man!

**Comment by torkelo** [comment]
@Akshaykapoor thank you!
