### ISSUE TITLE
Homepage dashboards broken after upgrade from 2.0.2 - 2.5

### ISSUE THREAD

**Issue by sacasumo** [grafana/grafana#3329]
After upgrading from 2.0.2 to 2.5 it seems that the homepage is broken and I couldn't find anything obvious on what's wrong. All the previous dashboards were retained and are fine, eveeyrthing works but the homepag dashboards, which hasn't been modified from the default show dashboard / starred lists.

![image](https://cloud.githubusercontent.com/assets/6401588/11389521/ceff59bc-9341-11e5-8c01-b6ef12bdf974.png)

**Comment by torkelo** [comment]
that is strange, no one has reported any upgrade issues. Did you restart grafana-server?

**Comment by sacasumo** [comment]
yes a couple of times .. more of a cosmetic thing than anything else .. 

not sure whether these have any impact / effect on it:

```
[root@mtgraph02 grafana]# tail -f grafana.log
2015/11/25 07:26:56 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'Main Org.': Organization not found
2015/11/25 07:26:56 [I] Completed / 302 Found in 717.329µs
2015/11/25 07:27:56 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'Main Org.': Organization not found
2015/11/25 07:27:56 [I] Completed / 302 Found in 15.171181ms
2015/11/25 07:28:56 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'Main Org.': Organization not found
2015/11/25 07:28:56 [I] Completed / 302 Found in 674.951µs
2015/11/25 07:29:56 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'Main Org.': Organization not found
2015/11/25 07:29:56 [I] Completed / 302 Found in 687.485µs
2015/11/25 07:30:56 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'Main Org.': Organization not found
2015/11/25 07:30:56 [I] Completed / 302 Found in 646.332µs
^C
[root@mtgraph02 grafana]#
```

they're pretty much spamming the log folder continuously ..

**Comment by torkelo** [comment]
ok, did you enable anonymous in grafana.ini? org_name must match an organization that exists.

http://docs.grafana.org/installation/configuration/#org_name
