### ISSUE TITLE
[FeatureRequest] Elasticsearch: allow to remove ".keyword" suffix for grouping fields

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#33299]
**What would you like to be added**:
A setting that allows change a names of fields in alerts
Unfortunately, transformations are not available for panels with alerts:
![image](https://user-images.githubusercontent.com/50422107/115836980-c838b380-a420-11eb-8d7e-c269f9313a31.png)

**Why is this needed**:
By default, Elasticsearch allows index a field twice - for searching and for grouping.
A field indexed for grouping gets `.keyword` suffix:
![image](https://user-images.githubusercontent.com/50422107/115836582-506a8900-a420-11eb-90df-a9c03e7a5f49.png)

This is how a field is displayed in alert:
![image](https://user-images.githubusercontent.com/50422107/115836740-8576db80-a420-11eb-89c9-31b9f330f4c2.png)

This is very inconvenient when you need to match events by the same fields from different databases:
![image](https://user-images.githubusercontent.com/50422107/115837221-ffa76000-a420-11eb-8f92-ab7717a6a72a.png)

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/observability-squad

**Comment by ivanahuckova** [comment]
In Grafana 8+ we are moving away from having alerting tied to graph panel. Alerting queries are created in separate UI and therefore transformations that are used in the panel won't affect them.

@Elfo404 @nathanrodman @peterholmberg Do you think that this feature request should be solved on data source level (we would implement this only in ElasticSearch) or if other data sources would benefit from this as well and this should be a new alerting feature request.

**Comment by Elfo404** [comment]
@ivanahuckova while I don't see this being difficult to implement on a DS level, I'd say it would be better suited for a generic alerting "renaming" feature.

looping in @grafana/alerting-squad

**Comment by ifrost** [comment]
@grafana/alerting-squad what do you think about it?
