### ISSUE TITLE
Panel resize fills the whole row

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3331]
Steps to reproduce:
1. Make 4 panels:

<img width="1394" alt="screen shot 2015-11-24 at 11 54 10 pm" src="https://cloud.githubusercontent.com/assets/1019609/11391395/08597a7a-9307-11e5-9d5a-5f3cd8e02c79.png">

2. Resize the 3rd panel then the 4th one will automatically extend

<img width="1410" alt="screen shot 2015-11-24 at 11 54 16 pm" src="https://cloud.githubusercontent.com/assets/1019609/11391399/0e6f4444-9307-11e5-9e4d-ce411eedc7eb.png">

4th panel automatically fills the whole row which we do not want.

**Comment by torkelo** [comment]
this is by design, when you resize a panel that is not the last panel, all panels will try fill the full row width
