### ISSUE TITLE
Explore: clicking on RunQuery doesn't work the first time you click but the second it does

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#33319]
When you click on `RunQuery` immediately without invoking any onBlur then the query isn't executed. But the next time it is.

![bug1](https://user-images.githubusercontent.com/562238/115876059-29bf4900-a446-11eb-89c7-d711e47e85b5.gif)

**Comment by zoltanbedi** [comment]
We should wrap the onRunQuery with a setTimeout function to make sure it runs after the onBlur.

**Comment by gabor** [comment]
hi @hugohaggmark can you still reproduce this on the current version of grafana? i'm unable to reproduce it well. i tried it in multiple browsers and it happened maybe once in 30 cases (or never, i'm not 100% sure about that 1 case).

**Comment by aocenas** [comment]
@hugohaggmark just a ping again whether you are still seeing this.

**Comment by hugohaggmark** [comment]
@aocenas @gabor I can't repro this in Grafana 8.0.2. Closing this now, skilled work 🎉
