### ISSUE TITLE
Elasticsearch: For log queries, add limit info to meta object

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#33318]
**What happened**:
To utilize https://github.com/grafana/grafana/pull/33069, we need to add `meta.limit` to logs dataFrames. Also, we need to change in `adjustMetaInfo`  code ` const limit = limitIndex && logsModelMeta[limitIndex]?.value;` to `const limit = limitIndex >= 0 && logsModelMeta[limitIndex]?.value;`.

**Comment by ivanahuckova** [comment]
@Elfo404 fyi

**Comment by Elfo404** [comment]
Thanks!
