### ISSUE TITLE
Table panel and datetime null values

### ISSUE THREAD

**Issue by diogopalma** [grafana/grafana#33316]
Reopening issue #32816 

**What happened**:
I'm unable to override the null value of a datetime field returned by a MySQL select statement on a table panel.
Basically, this bug only happens if you have a datetime column that is null for all rows.

**What you expected to happen**:
I believe that, if the datetime field value is null, the "No value" property override should work regardless of the data source column having or not non-null values.

**How to reproduce it (as minimally and precisely as possible)**:
My data source is a MySQL table that contains a col full of null values. 

I have added a table panel, built the query and overrided the following properties:
- Unit: Datetime local;
- No value: "-".

Steps:
- Create a table containing two datetime cols: A and B;
- Add a few entries for that table, but only set the datetime value for col A;
- Column B - containing only null values - will appear at Grafana as "null" and you won't be able to override that;
- Now, set a datetime value for any row at col B;
- Column B will correctly show empty values at Grafana instead of the "null" word.

**Anything else we need to know?**
I'm not sure if this bug only affects datetime fields and MySQL data sources, further investigation is required.

**Environment**:
- Grafana version: v7.5.3
- Data source type & version: MySQL v5.7.32
- OS Grafana is installed on: CentOS

**Comment by dprokop** [comment]
@diogopalma  do you mind sharing your Panel JSON and data returned by the query? You can find those in https://grafana.com/docs/grafana/latest/panels/inspect-panel/

**Comment by diogopalma** [comment]
@dprokop sure

Panel JSON
`{
  "type": "table",
  "title": "Panel Title",
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 8
  },
  "id": 6,
  "targets": [
    {
      "refId": "table_null_test",
      "format": "table",
      "timeColumn": "time",
      "metricColumn": "none",
      "group": [],
      "where": [
        {
          "type": "macro",
          "name": "$__timeFilter",
          "params": []
        }
      ],
      "select": [
        [
          {
            "type": "column",
            "params": [
              "value"
            ]
          }
        ]
      ],
      "rawQuery": true,
      "rawSql": "SELECT \n  dt_a AS 'A',\n  dt_b AS 'B'\nFROM col_test\nORDER BY id DESC"
    }
  ],
  "options": {
    "showHeader": true
  },
  "datasource": "mysql-test-datasource",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": null,
        "filterable": false
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "A"
        },
        "properties": [
          {
            "id": "unit",
            "value": "dateTimeAsLocal"
          },
          {
            "id": "noValue",
            "value": "-"
          }
        ]
      },
      {
        "matcher": {
          "id": "byName",
          "options": "B"
        },
        "properties": [
          {
            "id": "unit",
            "value": "dateTimeAsLocal"
          },
          {
            "id": "noValue",
            "value": "-"
          }
        ]
      }
    ]
  },
  "pluginVersion": "7.5.5"
}`

Data returned
`{
  "state": "Done",
  "series": [
    {
      "fields": [
        {
          "name": "A",
          "config": {
            "custom": {
              "filterable": false
            },
            "color": {
              "mode": "thresholds"
            },
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "value": null,
                  "color": "green"
                },
                {
                  "value": 80,
                  "color": "red"
                }
              ]
            },
            "mappings": [],
            "unit": "dateTimeAsLocal",
            "noValue": "-"
          },
          "values": [
            "2021-04-01T19:01:38Z",
            "2021-04-01T19:01:37Z",
            "2021-04-01T19:01:36Z",
            "2021-04-01T19:01:35Z",
            "2021-04-01T19:01:34Z"
          ],
          "type": "string",
          "state": {
            "displayName": "A",
            "scopedVars": {
              "__series": {
                "text": "Series",
                "value": {
                  "name": "Series (table_null_test)"
                }
              },
              "__field": {
                "text": "Field",
                "value": {}
              }
            },
            "seriesIndex": 1
          }
        },
        {
          "name": "B",
          "config": {
            "custom": {
              "filterable": false
            },
            "color": {
              "mode": "thresholds"
            },
            "thresholds": {
              "mode": "absolute",
              "steps": [
                {
                  "value": null,
                  "color": "green"
                },
                {
                  "value": 80,
                  "color": "red"
                }
              ]
            },
            "mappings": [],
            "unit": "dateTimeAsLocal",
            "noValue": "-"
          },
          "values": [
            null,
            null,
            null,
            null,
            null
          ],
          "type": "other",
          "state": {
            "displayName": "B",
            "scopedVars": {
              "__series": {
                "text": "Series",
                "value": {
                  "name": "Series (table_null_test)"
                }
              },
              "__field": {
                "text": "Field",
                "value": {}
              }
            },
            "seriesIndex": 2
          }
        }
      ],
      "refId": "table_null_test",
      "meta": {
        "executedQueryString": "SELECT \n  dt_a AS 'A',\n  dt_b AS 'B'\nFROM col_test\nORDER BY id DESC",
        "rowCount": 5
      },
      "length": 5
    }
  ],
  "annotations": [],
  "request": {
    "app": "dashboard",
    "requestId": "Q130",
    "timezone": "browser",
    "panelId": 6,
    "dashboardId": 15,
    "range": {
      "from": "2021-05-01T19:14:12.334Z",
      "to": "2021-05-02T01:14:12.334Z",
      "raw": {
        "from": "now-6h",
        "to": "now"
      }
    },
    "timeInfo": "",
    "interval": "1m",
    "intervalMs": 60000,
    "targets": [
      {
        "refId": "table_null_test",
        "format": "table",
        "timeColumn": "time",
        "metricColumn": "none",
        "group": [],
        "where": [
          {
            "type": "macro",
            "name": "$__timeFilter",
            "params": []
          }
        ],
        "select": [
          [
            {
              "type": "column",
              "params": [
                "value"
              ]
            }
          ]
        ],
        "rawQuery": true,
        "rawSql": "SELECT \n  dt_a AS 'A',\n  dt_b AS 'B'\nFROM col_test\nORDER BY id DESC",
        "datasource": "mysql-test-datasource"
      }
    ],
    "maxDataPoints": 910,
    "scopedVars": {
      "__interval": {
        "text": "1m",
        "value": "1m"
      },
      "__interval_ms": {
        "text": "60000",
        "value": 60000
      }
    },
    "startTime": 1619918052334,
    "rangeRaw": {
      "from": "now-6h",
      "to": "now"
    },
    "endTime": 1619918052564
  },
  "timeRange": {
    "from": "2021-05-01T19:14:12.334Z",
    "to": "2021-05-02T01:14:12.334Z",
    "raw": {
      "from": "now-6h",
      "to": "now"
    }
  },
  "timings": {
    "dataProcessingTime": 0.0700000673532486
  }
}`

**Comment by diogopalma** [comment]
Hello @dprokop , 

Were you able to reproduce this issue?

Thanks a lot.

**Comment by oscarkilhed** [comment]
I was able to reproduce this in 7.5.5 but it's fixed in 8.0.0-beta1. It does not seem to be critical enough to warrant a backport to 7.5, so I'm closing this.

Thank you for reporting the issue.
