### ISSUE TITLE
Wrong query for resolve variable with tag_value

### ISSUE THREAD

**Issue by msaf1980** [grafana/grafana#33317]
**What happened**:
Grafana produce incorrect query for resolve variable with tag_values when depend on multi-value variable with several selected items

**How to reproduce it**:
1) Add 2 variables
route="test1,test2" (Custom type)
gateway="tag_values(route, route = ${route})" (Query on Graphite Datasource with refresh on Time Range Change)

2) On dashboard for variable route try to select test1 and test2

For resolve variable route incorrect query was formed

`/api/datasources/proxy/2/tags/autoComplete/values?expr=route = {test1&expr=test2}&tag=route&limit=10000&from=1619180806&until=1619181708`

Correct query parameter for `expr=route` is

`expr=route={test,test2}`

**Environment**:
- Grafana version: 7.5.4-1 (or earlear)
- Data source type & version: Graphite 1.1.x
- OS Grafana is installed on: Linux
- User OS & Browser: All (tested on Firefox, Chrome)

**Comment by mckn** [comment]
Thanks for reporting this however we will remove the tags feature from Grafana 8 so I will close this issue.

https://github.com/grafana/grafana/issues/29602
