### ISSUE TITLE
How to get top 10 utilization servers and forecasting/trending

### ISSUE THREAD

**Issue by gopalvd** [grafana/grafana#3332]
Hi,
I am using influxdb as my database. And grafana to display the data from influx. Is there a way I can get top 10 util servers, based on cpu or memory among all the servers?

Also, can i get the capacity capabilites as well using grafana, like if I have a history of data, based on the same, can i get a trending, or forecasting capabilities. Are there any examples available in the grafana live demo page?

**Comment by torkelo** [comment]
you can do this in Graphite, and in Elasticsearch, and in Prometheus. InfluxDB does not support these kinds of queries. you will have to change time series database or request a feature in InfluxDB
