### ISSUE TITLE
Frontend: Webpack injected scripts don't include CSP nonce

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#33323]
**What happened**:
When enabling [CSP](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP), Safari won't load Grafana since some dynamically loaded JS bundles don't have the "nonce" attribute. The JS loading errors can look as follows:

```
[Error] Refused to load http://localhost:3000/public/build/default~DashboardPage~SoloPanelPage.7bb0ed519991a573201e.js because it does not appear in the script-src directive of the Content Security Policy.
```

AFAICT this is happening because Webpack injects scripts without the nonce attribute, which is necessary for JavaScript to be loadable when CSP is enabled (provided that `$NONCE` is in the `script-src` setting).

**What you expected to happen**:
For all JS bundles to have the nonce attribute set.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable CSP
2. Launch Grafana
3. Log into Grafana in Safari

This should break visibly.

**Anything else we need to know?**:

*When this is fixed, `script-src` changes in #34363 should be reverted, since it's a workaround that should presumably no longer be required*.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: OSX / Safari
- Grafana plugins:
- Others:

**Comment by ryantxu** [comment]
https://webpack.js.org/guides/csp/  :man_shrugging:

**Comment by kaydelaney** [comment]
Not 100% sure that what's happening here actually involves webpack not adding the nonce to dynamic chunks. If the nonce attribute is empty in devtools that could just be [nonce hiding](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/nonce#accessing_nonces_and_nonce_hiding).
In any case, I changed my CSP to the following and it works now in Safari, Chrome, and Firefox. Will make a PR soon.

```
content_security_policy_template = """script-src $NONCE 'strict-dynamic' 'unsafe-eval' 'self';object-src 'none';font-src 'self' fonts.gstatic.com;style-src 'self' 'unsafe-inline';img-src * data:;base-uri 'self';connect-src 'self' grafana.com ws://$DOMAIN:$PORT wss://$DOMAIN:$PORT;manifest-src 'self';media-src 'none';form-action 'self';"""
```
(Where `$DOMAIN` and `$PORT` are replaced with the appropriate values. Will be done automatically in the PR).

**Comment by aknuds1** [comment]
@kaydelaney did you test against #34339 also?

**Comment by kaydelaney** [comment]
> @kaydelaney did you test against #34339 also?

Thought I had and it worked, but trying again I got the same error mentioned in the issue.
I'm still not sure this is a webpack issue though, as inspecting the nonce attribute in the devtools console reveals that it's set for the vendor chunk.
I did some reading of the CSP spec, and I think the key passage is [here](https://www.w3.org/TR/CSP3/#strict-dynamic-usage):
> If script.js contains the following code:
>```js
>var s = document.createElement('script');
>s.src = 'https://othercdn.not-example.net/dependency.js';
>document.head.appendChild(s);
>
>document.write('<scr' + 'ipt src="/sadness.js"></scr' + 'ipt>');
>```
>
>dependency.js will load, as the script element created by createElement() is not "parser-inserted".
>
>sadness.js will not load, however, as document.write() produces script elements which are "parser-inserted".

Looking at the error reported in the console:
`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). jquery.js:6347`
```js
// ...
if ( elem.nodeType === 1 ) {
	jQuery.cleanData( getAll( elem, false ) );
	elem.innerHTML = value;
}
// ...
```

`Content Security Policy: The page’s settings blocked the loading of a resource at inline (“script-src”). angular.js:3332`
```js
function jqLiteClone(element) {
  return element.cloneNode(true);
}
```

I suspect in both instances, these elements are "parser-inserted" as mentioned in the spec, and throw an error as a result.
That makes this a difficult problem to solve though, as it means we either go with `unsafe-hashes` / `unsafe-inline`, or patch jquery/angular to not use a parser-inserted API.

**Comment by jackw** [comment]
I just gave this another look. It seems setting `__webpack_nonce__` doesn't work when running `yarn dev`. If I enable CSP in the config and run `yarn build` I can see the nonce being logged out by webpack when dynamically loading chunks.

**Comment by kaydelaney** [comment]
Think I've finally figured out what's up with the firefox errors.
When an angular graph panel is loaded, as part of the process angular/jquery sets the `innerHTML` of an element to the following:
```html
<div class="graph-panel" ng-class="{'graph-panel--legend-right': ctrl.panel.legend.rightSide}">
  <div class="graph-panel__chart" grafana-graph ng-dblclick="ctrl.zoomOut()">
  </div>

  <div class="graph-legend">
    <div class="graph-legend-content" graph-legend></div>
  </div>
  <div ng-if="ctrl.contextMenuCtrl.isVisible">
    <graph-context-menu
      itemsGroup="ctrl.contextMenuCtrl.menuItemsSupplier()"
      onClose="ctrl.onContextMenuClose"
      getContextMenuSource="ctrl.contextMenuCtrl.getSource"
      timeZone="ctrl.getTimeZone()"
      x="ctrl.contextMenuCtrl.position.x"
      y="ctrl.contextMenuCtrl.position.y"
    ></graph-context-menu>
  </div>
</div>
```

My best guess is that firefox interprets `onClose="ctrl.onContextMenuClose"` as an inline event handler ([this](https://developer.mozilla.org/en-US/docs/Web/API/GlobalEventHandlers/onclose) maybe?), and so complains about it being inserted via `innerHTML`. The errors go away if we just rename the prop from `onClose` to `onMenuClose` or something else that isn't a global event handler.

**Comment by kaydelaney** [comment]
Did some testing and the same issue above affects `color-picker` and `unit-picker` as well.
Could also rename the props for those components, but would break the interface which isn't ideal since they're part of grafana-ui. Maybe we could change `react2AngularDirective` to allow supplying aliases for prop names? Thoughts, @torkelo ?
