### ISSUE TITLE
Panels with timeshift after snapshot does not show the data correctly

### ISSUE THREAD

**Issue by johnatannvmd** [grafana/grafana#33335]
**What happened**:
I have a dashboard with a side-by-side comparison of the same metrics but shifted in the past for a certain amount of time via the variable. For future comparison, I made a snapshot of this dashboard. Panels with timeshift do not show the data and show me the "Data outside time range" message. If I click the button "Zoom to data" metrics from the non-timeshifted panels.

Normal dashboard:
![image](https://user-images.githubusercontent.com/4918448/115898313-158b4400-a466-11eb-958c-cd7bc9d81d0f.png)

Snapshot:
![image](https://user-images.githubusercontent.com/4918448/115898517-51bea480-a466-11eb-8334-681e75357d3a.png)

Snapshot after "Zoom to data"
![image](https://user-images.githubusercontent.com/4918448/115898736-8e8a9b80-a466-11eb-805a-2df928ad4d1a.png)

**What you expected to happen**:
Timeshift variable is applied to the panels correctly

**How to reproduce it (as minimally and precisely as possible)**:
Two panels, one of them is timeshifted. Make a local snapshot.

**Anything else we need to know?**:
I open the snapshot from the DB and the variables `$timeshift` are on the panel. Moreover, timeshift is present in the templating section of the dashboard:
```json
{
        "current": {
          "selected": false,
          "text": "680m",
          "value": "680m"
        },
        "hide": 2,
        "label": null,
        "name": "timeshift",
        "options": {
          "selected": false,
          "text": "680m",
          "value": "680m"
        },
        "query": "",
        "refresh": false,
        "skipUrlSync": false,
        "type": "constant"
      }
```

**Environment**:
- Grafana version: Grafana v7.5.4 (615c153b3a)
- Data source type & version: Influx
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome/Firefox
- Grafana plugins: Standard panel

**Comment by johnatannvmd** [comment]
Moreover, if I export this snapshot there are no current values, but these values present in the DB.

![image](https://user-images.githubusercontent.com/4918448/116073683-6767e000-a699-11eb-8103-967d3754f903.png)

**Comment by hugohaggmark** [comment]
Hi @johnatannvmd and thanks for reporting this, we currently do not support templating values in snapshots as documented here: https://grafana.com/docs/grafana/latest/sharing/share-dashboard/#publish-a-snapshot. Closing this issue for now but we can always reopen it in the future if more evidence points to an actual issue in Grafana.

**Comment by johnatannvmd** [comment]
If you create a custom variable with a certain value it will work with a snapshot. That value is used by the panel(time-shift works) but the time-shift indication does not appear in the panel.

![index](https://user-images.githubusercontent.com/4918448/116997640-bc34d780-ace5-11eb-8999-e1fb7686922a.png)

**Comment by johnatannvmd** [comment]
Looks like there is inconsistent behavior for Snapshots. On the one hand, hidden variables do not work, on the other hand, it does work if it is visible on the dashboard.

> Grafana strips sensitive data like queries (metric, template and annotation) and panel links, leaving only the visible metric data and series names embedded into your dashboard

Okay, variables were stripped, but as far I can see variables still in the body of the snapshot(stored in the DB) it just does not apply to the panel(timeshift property).

**Comment by johnatannvmd** [comment]
@hugohaggmark Can you please me with that? That kind of snapshots works perfectly in the 6.7 Grafana.
