### ISSUE TITLE
Improved mechanism for allowing app plugins to inject menus and and actions via `grafanaPanelInspectActionSupplier`

### ISSUE THREAD

**Issue by clord** [grafana/grafana#33334]
**What would you like to be added**:

A general way for plugins to register functionality to show on the "Actions" tab on inspector of panel and explore view. 

The mechanism is currently an unsupported extension. This item tracks improving it, fully supporting multiple plugins, supported in panel inspector and explore inspector, and finally adding a sub-menu for actions. 

**Why is this needed**:

UX for users, who currently have to copy-paste the query, remember the right datasource and time-range, and recreate these in the plugin UI. Often for our plugin, user is looking at an existing query in a panel and would like to bring it into the plugin for further processing.

**Sub-goals**:

- [ ] Does not show an action if plugin is not installed.
- [ ] Explore inspectors action panel.
- [ ] Panel inspector action panel.
- [ ] Menu option on panel menu to show available actions.
- [ ] support multiple plugins via `grafanaPanelInspectActionSupplier`

**Comment by sympatheticmoose** [comment]
@clord [UI Extensions](https://grafana.com/developers/plugin-tools/ui-extensions/) covers this as a general capability now. Extension points within the inspectors panels should be possible to add if there is a requiremet
