### ISSUE TITLE
There's an unidentified bouncy line in my graph

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#33341]
**What happened**:

Sorry, I don't know.

**What you expected to happen**:

* For the lines to correlate to the data, and the data to be explained in the tooltip.
* For stacked lines not to cross through each other.

**How to reproduce it (as minimally and precisely as possible)**:

<https://grafana.wikimedia.org/d/000000330/varnish-machine-stats?viewPanel=3&editPanel=3&orgId=1&from=1619210663680&to=1619211333476&var-datasource=esams%20prometheus%2Fops&var-cluster=All>

Haven't yet narrowed it down.

| Figure 1: Stacked lines | Figure 2: Stacked lines (fully filled, hide series with zeros only) |
|--|--
| <img width="1329" alt="Screenshot 2021-04-23 at 22 15 22" src="https://user-images.githubusercontent.com/156867/115930684-d0750b00-a481-11eb-85ef-e392fe51e791.png"> | <img width="1336" alt="Screenshot 2021-04-23 at 22 14 39" src="https://user-images.githubusercontent.com/156867/115930726-e08cea80-a481-11eb-9997-81fa5abcdbf5.png">

And when I click in the legend to show one series, and then with optoin to show the others, the line is not there, suggesting that it is coming from a series that is hidden from the legend:

| Figure 3
|--
| <img width="400" alt="Screenshot 2021-04-23 at 22 14 34" src="https://user-images.githubusercontent.com/156867/115930844-0f0ac580-a482-11eb-8b2e-bc7d584de9a1.png">

Based on Figure 1, I assume it must be `guest_user` metric, but as seen in that image, it has value 0 in the tooltip. And here is that series shown alone:

<img width="300" alt="Screenshot 2021-04-23 at 22 21 40" src="https://user-images.githubusercontent.com/156867/115931009-5abd6f00-a482-11eb-9d62-634f84e56a96.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian
- User OS & Browser: Firefox 87 on macOS, and in Safari 14 on macOS, possibly elsewhere too.

**Comment by dprokop** [comment]
@Krinkle can you be more precise what line are you talking about? Not sure I fully understand what you are experiencing here :)

**Comment by Krinkle** [comment]
@dprokop Can you reproduce the issue at the provided Wikimedia link? The spiky lines have started to show on various other dashboards and data sources as well. It makes no sense to me since:

* The series in question only has zeroes, so there's no reason for the line to be moving at all. The tooltip also confirms the line in question has a zero at all the points where it seems to be alternating to the highest value in the graph at 30%.
* It is in a stacked graph with no overrides of any kind, so how is it even possible for the visualisation library to be drawing a line that is **crossing** **through** other lines. As far as I know, that is also something not meant to be possible in a stacked graph.

Figure 2: When I configure the graph to hide series containing ony nulls/zeroes, the series goes away from the legend, but it remains in the graph just the same.

Figure 3: This is the expected rendering for Figure 2. I made it by using option-click on each of the series in the legend, so the weird spiky green line goes way.

**Comment by torkelo** [comment]
The issue is the data is being stacked, but the data points do not align so every other data point the stacking is not able to stack as the other series are all null for that data point, try to group the data into wider time buckets (adjust step) so all time have data points, or disable stacking 


![Screenshot from 2021-04-28 08-58-12](https://user-images.githubusercontent.com/10999/116360190-f55ddb00-a7ff-11eb-9ff2-0dacfe3ffdd4.png)

**Comment by Krinkle** [comment]
Ah! This helped me realize that one of the three Prometheus queries had resolution set to 1/1, but the others used resolution 1/3. Setting them all to 1/3 made the problem go away.

Thank you!
