### ISSUE TITLE
NodeGraph: context menu doesn't show details if there is no link

### ISSUE THREAD

**Issue by hectorj** [grafana/grafana#33358]
Hi!

I'm experimenting with the beta Node Graph Panel, and I just spent some time figuring out an issue : there is no context menu displayed when clicking on nodes/edges if they don't have at least a link, even though they have `details__`.

Now I see that it was intentionally done in this commit https://github.com/grafana/grafana/pull/29706/commits/1a6bec8033e75c24000262192715dbdbd7084768 but I wonder if it is possible to revert this decision? (ping @aocenas)

I think it should be possible to display details without any links.

If I missed something and it is not possible, it should probably be documented.

I'm happy to contribute a fix either to the code or to the docs, just let me know what you think is the best solution 🙂

**Comment by aocenas** [comment]
Yes this is true and as you say probably does not make sense if there are some details to be shown. We will probably change this at some point but if you want to contribute this it would be great.

**Comment by joe-w** [comment]
I too seem to be facing this issue, and see no detail__ fields in graph mode.  However, I'm actually TRYING to include a link in a context menu, and I see no documentation on how to do this.

Specifically, I'd like a link from a node in the graph, with a URL that can include fields from the selected node - effectively a Data Link from Node Graph.  This appears to be what's happening in the Demo video on the Node Graph plugin page (https://grafana.com/docs/grafana/latest/visualizations/node-graph/) but I see no documentation on how this is accomplished.  Any pointers would be greatly appreciated.

**Comment by lmangani** [comment]
@aocenas a year later is there any documentation on how to properly include node links and trigger context visibility in graph mode, just like grafana does internally for tempo and service graph views?

**Comment by aocenas** [comment]
Hey sorry I know this is a bit long to solve, unfortunately, we did not have enough time to spend on this. Hopefully, this will improve near future. In the meantime I can just point to this part of the Tempo code https://github.com/grafana/grafana/blob/c8f2148f7504b393b8f9b32fe19e7f519fa66793/public/app/plugins/datasource/tempo/datasource.ts#L456 where we create a field config with required data links. You can use the similar code to create data links from a 3rd party datasource.

**Comment by aocenas** [comment]
This is actually fixed now
