### ISSUE TITLE
Unable to use Influxdb2 as datasource

### ISSUE THREAD

**Issue by ludz-lim** [grafana/grafana#33351]
**What happened**:

I'm unable to configure Influxdb2 as a datasource

**How to reproduce it (as minimally and precisely as possible)**:

Create a Influx DB data source, Click "Save and Test",  It returns  "Error reading Influxdb"

![image](https://user-images.githubusercontent.com/21330830/115953088-11b9f900-a51c-11eb-9cdb-c2f1a38e7227.png)

![image](https://user-images.githubusercontent.com/21330830/115953289-23e86700-a51d-11eb-87a3-79060f88ffff.png)

The grafana logs says:
```bash
"Flux query failed" logger=tsdb.influx_flux err="not found: no buckets found in organization d8fee9b87bad9775" query=buckets()
```

Seems that it was able to query the correct org ID for org `rdit`, but fails to list its buckets

However, I was able to list the buckets for organization ID d8fee9b87bad9775 on the influx DB server itself

```bash
[root@ip-172-20-237-53 influxdb]# influx bucket list  -o rdit
ID                      Name            Retention       Organization ID
163975ccaf75a18e        _monitoring     168h0m0s        d8fee9b87bad9775
7eafcaf657ef0e85        _tasks          72h0m0s         d8fee9b87bad9775
efbca247574dff99        harbor          0s              d8fee9b87bad9775
```

**Anything else we need to know?**:

I tried updating the plugins and restart grafana, but it still didn't work

```bash
 grafana-cli plugins update-all
```

**Environment**:
- Grafana version:  `grafana-7.5.4-1.x86_64`
- Data source type & version: `Influxdb2 (2.0.4)`
- OS Grafana is installed on: `Amazon Linux2`
- User OS & Browser: `Windows 10 / Chrome`
- Grafana plugins: `InfluxDB`
- Others:

**Comment by jayaddison** [comment]
@ludz-lim While you should be careful not to paste any tokens into this thread, my guess is that the token you have configured on your datasource does not have permissions to read the associated buckets.  Could you check the permissions assigned to the token?

(the token does appear to belong to the correct organization, otherwise I might have guessed at a token-organization mismatch between configuration and data source; thanks for ruling that out by providing the `influx` CLI output)

**Comment by ludz-lim** [comment]
@jayaddison  After googling for some time, it seems that token need to have admin permission (Sorry, I can't recall the page where I read it). I made it work by using the admin token.  I'll double check the permissions of the token. 

It would be nice if the error message can be changed to "Permission not allowed" instead of "No bucket found in organization". I appreciate the fast reply :)
