### ISSUE TITLE
CI: Move nightly Docker image scan job from CircleCI to Drone

### ISSUE THREAD

**Issue by aknuds1** [grafana/grafana#33369]
**What happened**:
We should move the nightly Docker image scan job from CircleCI to Drone, and make sure that security issues are communicated in an easily detected manner, f.ex. by sending messages to a dedicated Slack channel.

**Comment by miyasasa** [comment]
Hi @aknuds1,
I'm new to the project and want to get started contributing by this issue :) Can I do this one?

**Comment by aknuds1** [comment]
> Hi @aknuds1,
> I'm new to the project and want to get started contributing by this issue :) Can I do this one?

@idafurjes were you supposed to try to tackle this one?

**Comment by idafurjes** [comment]
yes, exactly this one

**Comment by aknuds1** [comment]
@miyasasa sorry, someone is already assigned to this one. But thanks!
