### ISSUE TITLE
[yarn] [webpack] [build] Module parse failed: Unterminated comment

### ISSUE THREAD

**Issue by jayaddison** [grafana/grafana#33360]
**What happened**:
When running `yarn start` (strictly speaking, `yarnpkg start`) for version `1.22.10` of `yarn` to build and run the `grafana` assets and resources, an `angular.js`-related error appears in the output of the `webpack` build, after SASS compilation has taken place.

```
ERROR in ./node_modules/angular/angular.js 2712:0
Module parse failed: Unterminated comment (2712:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
```

![grafana-webpack-build-error](https://user-images.githubusercontent.com/55152140/116004842-895f5500-a5fc-11eb-9c33-71bb2e2914ae.png)

The comment referenced appears like so - this snippet begins at the comment opener, and ends at the EOF:

```
/* global angularModule: true,
  version: true,

  $CompileProvider,

  htmlAnchorDirective,
  inputDirective,
  hiddenInputBrowserCacheDirective,
  formDirective,
  scriptDirective,
  selectDirective,
  optionDirective,
  ngBindDirective,
  ngBindHtmlDirective,
  ngBindTemplateDirective,
  ng
```

**What you expected to happen**:
No `angular`-related error message should appear.

**How to reproduce it (as minimally and precisely as possible)**:
Using `yarn` version `1.22.10`, run `yarn start` from a fresh local directory checkout of 47e68580a645db4fc30674c2fc3f0dd09596e15f.

**Anything else we need to know?**:
I attempted a screen recording using [`peek`](https://github.com/phw/peek) - the resulting animation had a black background, and did not include the relevant console output for this issue.

This _might_ be an upstream issue in either [`webpack`](https://github.com/webpack/webpack/) or [`angular`](https://github.com/angular/angular).  Happy to redirect my issue report to either of those projects if and when we determine the cause exists there.

I'm not sure I'm likely to enter into your CLA yet before further consideration, so I'm unlikely to offer a pull request related to this issue if it does exist within the `grafana.git` repository.

**Environment**:
- Grafana version: Approximately v7.5.4 (specifically, 47e68580a645db4fc30674c2fc3f0dd09596e15f)
- Data source type & version: N/A
- OS Grafana is installed on: Manjaro Linux
- User OS & Browser: Manjaro Linux, Firefox 88.0
- Grafana plugins: None

**Comment by dprokop** [comment]
What happens when you remove node_modules, run `yarn install --pure-lockfile` and then `yarn start`?

**Comment by jayaddison** [comment]
Thanks for checking @dprokop - the same problem appears after running `yarn install --pure-lockfile` followed by `yarn start`.

**Comment by jayaddison** [comment]
Thanks @jackw - yes, this was still reproducible, and it turns out to have been a `yarn` caching issue.  Clearing that cache sorted things out; thanks for the suggestion :)
