### ISSUE TITLE
Proposal: abandon the Discord notifier logic in favor of Slack webhooks

### ISSUE THREAD

**Issue by ChipWolf** [grafana/grafana#33377]
**What would you like to be changed**: Currently, there are two notifiers for Slack and Discord. As Discord [supports Slack-compatible webhooks](https://discord.com/developers/docs/resources/webhook#execute-slackcompatible-webhook), you're able to append `/slack` to a Discord webhook & specify it as a webhook URL in the Slack notifier for an equal outcome. This obsoletes the need to maintain an additional notifier for Discord.

I propose this should be implemented by allowing Discord to remain as an available notification type, merely modifying the backend logic for the Discord notifier to call on the Slack notifier, simply appending `/slack` to the provided webhook URL.
I'll leave any more specific implementation details up to the code owners, such as how to surface the optional notification settings from the Slack notifier if Discord is chosen.

**Why is this needed**: This reduces some complexity and mitigates the need to implement any additional optional configuration options in the Discord notifier logic to reach feature parity with the Slack notifier.

The upper message shows a test notification from the Discord notifier.
The lower message shows a test notification from the Slack notifier.

![32BE045E-07CF-4888-BAF0-7257C2BF8C5B_1_105_c](https://user-images.githubusercontent.com/3164166/116073600-8a3dc880-a688-11eb-8312-97b3344c1d49.jpeg)

**Comment by ChipWolf** [comment]
Thoughts on this @dsotirakis?

**Comment by dsotirakis** [comment]
Hello @ChipWolf, let me have a look and I'll get back to you :)

**Comment by ChipWolf** [comment]
For reference, this is how Ghost handles this:
![](https://i.cwlf.uk/YZmEK)

**Comment by marefr** [comment]
Slack incoming webhooks are marked as legacy/deprecated and potentially to be removed in the future: https://api.slack.com/legacy/custom-integrations/messaging/webhooks

So not sure if this makes this issue obsolete/not needed and/or there's a new non-legacy way for Discord and others to make make use of the Slack API?

**Comment by ChipWolf** [comment]
> 
> 
> Slack incoming webhooks are marked as legacy/deprecated and potentially to be removed in the future: https://api.slack.com/legacy/custom-integrations/messaging/webhooks
> 
> So not sure if this makes this issue obsolete/not needed and/or there's a new non-legacy way for Discord and others to make make use of the Slack API?

Legacy incoming webhooks for Slack are deprecated, however incoming webhooks (using the Slack app) are not

**Comment by marefr** [comment]
Thanks. I think the request makes sense then. Question is just how to migrate things.

**Comment by bramceulemans** [comment]
I think it's valuble to make sure that the embed images still work. Personally we use the Discord notifications and love them.

**Comment by ChipWolf** [comment]
> 
> 
> I think it's valuble to make sure that the embed images still work. Personally we use the Discord notifications and love them.

They work, the Discord endpoint for Slack webhooks behaves exactly as Slack does natively

**Comment by armandgrillet** [comment]
"This reduces some complexity": going further in this direction, we could only allow webhook as contact points to reduce complexity in the codebase. Having a separate contact point for Discord gives more clarity to users, we will keep it.
