### ISSUE TITLE
Encrypt datasource password in defaults.ini file

### ISSUE THREAD

**Issue by briskjj** [grafana/grafana#33371]
**What would you like to be added**:

Now the database password is saved in plaintext in the defaults.ini file. 
Whether it can be encrypted for storage in the defaults.ini file. Could only be reset by starting grafan-cli?
**Why is this needed**:
Security

**Comment by wbrowne** [comment]
Hi @briskjj.

>Now the database password is saved in plaintext in the defaults.ini file.

As per the [docs](https://grafana.com/docs/grafana/latest/administration/configuration/#config-file-locations), we don't encourage the modification of the defaults.ini. 

Perhaps the [Variable Expansion](https://grafana.com/docs/grafana/latest/administration/configuration/#variable-expansion) feature is something that will suit your needs. There is a [specific example ](https://grafana.com/docs/grafana/latest/administration/configuration/#file-provider)of how to use this feature using the database password.

P.S. If you’re running Grafana Enterprise, you can also use [our Hashicorp Vault integration.](https://grafana.com/docs/grafana/latest/enterprise/vault/)
