### ISSUE TITLE
InfluxDB: graph query no datapoints

### ISSUE THREAD

**Issue by jmls** [grafana/grafana#3338]
I have been trying all day to get this right - and failing ;) I can't even draw a miserable graph ...

if I curl a request from the cli, I get this

```bash
curl -G 'http://myurl/query?db=mydb&pretty=true' --data-urlencode "q=SELECT HR FROM dashboard ORDER BY time DESC LIMIT  1"
```
I get some results

```json
{
    "results": [
        {
            "series": [
                {
                    "name": "dashboard",
                    "columns": [
                        "time",
                        "HR"
                    ],
                    "values": [
                        [
                            "2015-11-25T18:31:42.196276119Z",
                            99.38
                        ]
                    ]
                }
            ]
        }
    ]
}
```

however, if I use this query in the influxdb I get no data points

![image](https://cloud.githubusercontent.com/assets/929523/11407203/362e4078-93a9-11e5-876a-6504022b76e4.png)

what exactly am I doing wrong here ? I know that it must be something so bleeding obvious ...

thanks

**Comment by jmls** [comment]
this is from the influx admin ui : so I definitely have data , just can't get it through to grafana :(

![image](https://cloud.githubusercontent.com/assets/929523/11409595/ffac0cfa-93b8-11e5-898b-255ac1bd2d1b.png)

**Comment by torkelo** [comment]
Try using the query editor, and don't limit by one
