### ISSUE TITLE
Update Macaron path

### ISSUE THREAD

**Issue by onlyjob** [grafana/grafana#3340]
Old macaron path [github.com/Unknwon/macaron](https://github.com/Unknwon/macaron) is deprecated.
Please consider updating to [github.com/go-macaron/macaron](https://github.com/go-macaron/macaron) or to [gopkg.in/macaron.v1](http://gopkg.in/macaron.v1).
Thanks.

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/commit/4fe72ebf69f560849d8f128de18901d872c6e3f9

**Comment by onlyjob** [comment]
Thanks! :-)
