### ISSUE TITLE
Series override: Hide / Show Only in Tooltip

### ISSUE THREAD

**Issue by ecables** [grafana/grafana#3341]
Just upgraded to 2.5, and discovered "legend: false" -- this is great! It would be nice if there was also "tooltip: false" so that items could be excluded from the tooltip, as well as the legend.

There are cases where the query returns values that are necessary for computation, but distract from the graph. In these cases it is useful to have both "legend: false" and "tooltip: false," so that the computation can be performed, but not distract from the visual representation.

**Comment by torkelo** [comment]
If they query is only used for computation can't you hide the query using the eye in the metrics tab?

**Comment by Griesbacher** [comment]
That would be great, I need the same. The reason is, I want to draw the line but the name is just distracting if shown.

**Comment by ilgizar** [comment]
I also needed it. This patch will add option "tooltip: true|false" and hide tooltip according invisibility of series on legend.
[patch](http://paste.ofcode.org/QF4Tr7HKzCyb77f7ueX67Q)
PS: sorry my English.

**Comment by rjain11** [comment]
Is there any ETA on this feature?
