### ISSUE TITLE
How to delete dashboard

### ISSUE THREAD

**Issue by joyhope** [grafana/grafana#3342]
I try to delete one problem dashboard, but I could not find where to delete it.  The dashboard is configured none editable.

I could not find X according https://github.com/grafana/grafana/wiki/FAQ.

**Comment by torkelo** [comment]
You will have to make it editable again, use Save As and specify the same name

**Comment by asarkar** [comment]
I've a dashboard that has a syntax error and doesn't load. Thus, I can't use the delete link. How else can I get rid of it?
