### ISSUE TITLE
Data Sources configuration page is broken after upgrade to 7.5.4 

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#33437]
**What happened**: Data Sources configuration page is not accessible,

**What you expected to happen**: use the configuration page to setup my datasources.

**How to reproduce it (as minimally and precisely as possible)**:
* install Grafana v7.0.0 (aee1438ff2)
  * click the Configuration gear -> Data Sources; make sure the data source page is working. 
* upgrade to Grafana v7.5.4 (615c153b3a)
  * click the Configuration gear -> Data Sources; see that data source page is broken.
  *
![image](https://user-images.githubusercontent.com/6409857/116272789-dd4b7480-a789-11eb-959c-cf2de33c3a63.png)
 

**Anything else we need to know?**:
The grafana.log
```
t=2021-04-27T15:50:25+0000 lvl=info msg="Successful Login" logger=http.server User=admin@localhost
t=2021-04-27T15:50:29+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/build/default~DataSourceDashboards~DataSourceSettingsPage~DataSourcesListPage~NewDataSourcePage.7d3798b26be143575eb4.js status=404 remote_addr=10.29.206.120 time_ms=3 size=40593 referer=http://XXXX:3000/datasources
```

**Environment**:
- Grafana version: Grafana v7.5.4 (615c153b3a)
- Data source type & version: Prometheus, Influx
- OS Grafana is installed on: Redhat enterprise 7
- User OS & Browser: Win10, Chrome, MS edge.
- Grafana plugins: grafana-clock-panel,grafana-polystat-panel,jdbranham-diagram-panel,yesoreyeram-yesoreyeram-boomtable-panel
- Others: after downgrading back to 7.0.0 the data sources page is working again.

**Comment by torkelo** [comment]
@yarix what happens if you refresh the browser page? This error is common after an upgrade, you need to refresh the browser

**Comment by yarix** [comment]
@torkelo , i have refreshed the page, deleted caches and cookies. i've also switched browsers. in all cases the problem is the same.
when accessing the page, Grafana tries to fetch a JS that does not exist (http 404).
![image](https://user-images.githubusercontent.com/6409857/116362650-f34d4980-a80a-11eb-9a9f-48d8154db0bf.png)

**Comment by torkelo** [comment]
@yarix can you try to re-install Grafana? verify that that file exists on disk at /usr/share/grafana/public/build  ? 

We have not other report like this, something must have happened during install/upgrade where the new frontend assets where updated but not all files got copied.

**Comment by yarix** [comment]
so that was the problem.
we use the tar.gz installation and probably it had issue with unpacking the file, this is the file on my end : `default~DataSourceDashboards~DataSourceSettingsPage~DataSourcesListPage~N`
 
Closing since it looks like a problem on my end.
 Thanks
