### ISSUE TITLE
fill below to not working properly

### ISSUE THREAD

**Issue by leahoswald** [grafana/grafana#33435]
![Screenshot2021-04-27_16-50-44](https://user-images.githubusercontent.com/1292551/116263662-d61c6a80-a779-11eb-9b2c-2a18abd92896.png)

**What happened**:
I tried to use the fill below to override but it doesn't work properly. The lines mentioned in the override (best/worst) are not display and not filled too. But if I hove over the graph I can see the datapoints in the tooltip (see screenshot).

**What you expected to happen**:
That the area between best/worst would be filled.

**How to reproduce it (as minimally and precisely as possible)**:
See screenshot above.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.5.4
- Data source type & version: prometheus 2.23.0
- OS Grafana is installed on: debian buster 10.9
- User OS & Browser: archlinux, firefox 88 and chromium 90
- Grafana plugins: -
- Others:

**Comment by torkelo** [comment]
can you show what the data looks like? very hard to see the best & worst data points, any nulls there?

**Comment by leahoswald** [comment]
Damit, thanks for being my rubber duck^^. I was sure I tried it in both directions fill below to best and fill below to worst. But in this case, we see ICMP RTTs here, so worst is the bigger value of the two and I need to select fill below to worst. Now it works.
![Screenshot2021-04-28_10-53-36](https://user-images.githubusercontent.com/1292551/116375906-06aee380-a810-11eb-8f2e-f7ff151908ea.png)
