### ISSUE TITLE
Grafana webhooks only working from the CLI

### ISSUE THREAD

**Issue by eljimbo** [grafana/grafana#33448]
I am hoping that someone can help with a weird issue with the webhook alerting notification channels. We are using Zoom for our company messaging platform and I want to be able to send alerts from various panels etc to a monitoring channel. The incoming webhook has been setup and added as an app to zoom and when I test using a curl from the CLI of the grafana VM (Ubuntu 19.10), I get the 'Hello World' test message successfully. 

However, when I try and setup a notification channel, I only get a 'Failed to send alert notifications' message.

I have attempted from various locations, i.e. my laptop, other servers on the same range but I get the same outcome. When tailing the syslogs, I can see that for some reason, instead of it trying to send to inbots.zoom.us it only tries to send it to the server where I am attempting the test from (i.e. my browser or whichever server I am on) so receive a 500 response.

_"Apr 27 20:38:49 *servername* grafana-server[878]: t=2021-04-27T20:38:49+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname="My Username" method=POST path=/api/alert-notifications/test status=500 remote_addr=<whatever the IP of the server is>  time_ms=685 size=48 referer=https://<grafana-URL>:3000/alerting/notification/4/edit"_

I am using v7.5.4 of grafana, but this was also occurring in the previous version before I updated recently. I have also got our network team to see if there is anything going on on the firewall, but when sending via the Browser test they cannot see anything.

**Comment by mckn** [comment]
@eljimbo thanks for reporting this! Do you get any more errors in the logs? The error you attached seems to only showing the request log and not the underlying error.

Also, next time you report an issue please use our template it helps us to triage the issues easier and quicker.

**Comment by eljimbo** [comment]
Apologies, this is the first time logging via here, could you point me to the template and I will re-do my query.

That is the only log i can find referencing the attempt via the browser

These are the only other details in the syslogs (after firing the test from the broswer)

Apr 30 11:38:30 vm1grf001 systemd-resolved[859]: Server returned error NXDOMAIN, mitigating potential DNS violation DVE-2018-0001, retrying transaction with reduced feature level UDP.
Apr 30 11:39:46 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:46+0000 lvl=info msg="Request Completed" logger=context userId=3 orgId=1 uname="<MY Username>" method=GET path=/login status=302 remote_addr=10.3.106.29 time_ms=12 size=24 referer=
Apr 30 11:39:55 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:55+0000 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
Apr 30 11:39:55 vm1grf001 rsyslogd: omfwd: TCPSendBuf error -2027, destruct TCP Connection to 127.0.0.1:6514 [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Apr 30 11:39:55 vm1grf001 rsyslogd: action 'action-8-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.1901.0 try https://www.rsyslog.com/e/2007 ]
Apr 30 11:39:55 vm1grf001 rsyslogd: action 'action-8-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.1901.0 try https://www.rsyslog.com/e/2359 ]
Apr 30 11:39:55 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:55+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.webhook error="Webhook response status 500 Internal Server Error" webhook="Zoom Webhook"
Apr 30 11:39:55 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:55+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error="Webhook response status 500 Internal Server Error"
Apr 30 11:39:55 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:55+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error="Webhook response status 500 Internal Server Error"
Apr 30 11:39:55 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:55+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=3 orgId=1 uname="<MY Username>" error="Webhook response status 500 Internal Server Error" remote_addr=10.3.106.29
Apr 30 11:39:55 vm1grf001 grafana-server[910]: t=2021-04-30T11:39:55+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname="<MY Username>" method=POST path=/api/alert-notifications/test status=500 remote_addr=10.3.106.29 time_ms=379 size=48 referer=https://<Grafana-URL>:3000/alerting/notification/6/edit
Apr 30 11:41:28 vm1grf001 grafana-server[910]: t=2021-04-30T11:41:28+0000 lvl=info msg="Sending webhook" logger=alerting.notifier.webhook
Apr 30 11:41:28 vm1grf001 grafana-server[910]: t=2021-04-30T11:41:28+0000 lvl=eror msg="Failed to send webhook" logger=alerting.notifier.webhook error="Webhook response status 500 Internal Server Error" webhook="Zoom Webhook"
Apr 30 11:41:28 vm1grf001 grafana-server[910]: t=2021-04-30T11:41:28+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error="Webhook response status 500 Internal Server Error"
Apr 30 11:41:28 vm1grf001 rsyslogd: omfwd: TCPSendBuf error -2027, destruct TCP Connection to 127.0.0.1:6514 [v8.1901.0 try https://www.rsyslog.com/e/2027 ]
Apr 30 11:41:28 vm1grf001 rsyslogd: action 'action-8-builtin:omfwd' suspended (module 'builtin:omfwd'), retry 0. There should be messages before this one giving the reason for suspension. [v8.1901.0 try https://www.rsyslog.com/e/2007 ]
Apr 30 11:41:28 vm1grf001 rsyslogd: action 'action-8-builtin:omfwd' resumed (module 'builtin:omfwd') [v8.1901.0 try https://www.rsyslog.com/e/2359 ]
Apr 30 11:41:28 vm1grf001 grafana-server[910]: t=2021-04-30T11:41:28+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error="Webhook response status 500 Internal Server Error"
Apr 30 11:41:28 vm1grf001 grafana-server[910]: t=2021-04-30T11:41:28+0000 lvl=eror msg="Failed to send alert notifications" logger=context userId=3 orgId=1 uname="<MY Username>" error="Webhook response status 500 Internal Server Error" remote_addr=10.3.106.29
Apr 30 11:41:28 vm1grf001 grafana-server[910]: t=2021-04-30T11:41:28+0000 lvl=eror msg="Request Completed" logger=context userId=3 orgId=1 uname="<MY Username>" method=POST path=/api/alert-notifications/test status=500 remote_addr=10.3.106.29 time_ms=127 size=48 referer=https://<Grafana-URL>:3000/alerting/notification/6/edit


For some reason, instead of sending the webhook  https://inbots.zoom.us/incoming/hook/blah> it tries to send it to the local IP of the server when using the broswer. We have no GPOs set for proxy etc and there is nothing in the hosts files on the machines.

**Comment by marefr** [comment]
@eljimbo you sure that Grafana server properly can lookup inbots.zoom.us via DNS? You should be able to see more details by enabling [debug log level](https://grafana.com/docs/grafana/latest/administration/configuration/#level). Especially this message https://github.com/grafana/grafana/blob/a40aef0822c27fa9d145e8410f3b7979feb8446b/pkg/services/notifications/webhook.go#L99

**Comment by eljimbo** [comment]
sorry for the delay in response, yes the Curl from the CLI works when sending 

curl '<inbots url>' -X POST -H 'Authorization: <token>' -H 'Content-Type: application/json' -d 'Hello World'

also, yes the grafana server can nslookup the inbots -

nslookup inbots.zoom.us
Server:		127.0.0.53
Address:	127.0.0.53#53

Non-authoritative answer:
inbots.zoom.us	canonical name = d-3ifaru7qrg.execute-api.us-east-1.amazonaws.com.
Name:	d-3ifaru7qrg.execute-api.us-east-1.amazonaws.com
Address: 52.20.207.176
Name:	d-3ifaru7qrg.execute-api.us-east-1.amazonaws.com
Address: 3.230.96.168
Name:	d-3ifaru7qrg.execute-api.us-east-1.amazonaws.com
Address: 35.172.241.185

I have opened a ticket with Zoom, who have managed to replicate the issue and they have said, basically cos within the alert channel notification for zoom there is nowhere to put the authorisation token, this is why it is unable to send via the test or via the automated alerts in the grafana panels.

they have said the following in their latest email -

"So in this case the curl command push through because the command contains the verification token, which in Grafana, using the HTTP POST there is no field where in we can put the verification token.  

I have informed our back end on this, but our back end informed me that it is really required on the third party app to have the verification token included on their part to authenticate on Zoom incoming webhook channel. 

If possible can you also try to send an inquiry to Grafana for that field required in order to authenticate on Zoom incoming webhook"

**Comment by marefr** [comment]
I believe the proper solution for your problem is to setup a new service receiving the Grafana webhooks and forwards them to Zoom with all your required data set. This is the recommended approach for anyone using the webhook notifier because the payload is Grafana specific and target systems normally requires specific payloads. 

Reference https://grafana.com/docs/grafana/latest/alerting/notifications/#webhook

I'll close this since there's nothing more to discuss.

**Comment by eljimbo** [comment]
Yep thanks, it's just a bit of a pain having to have this part in the middle when most other alert channels like Slack etc work without this much hassle.
