### ISSUE TITLE
Grafana alert giving false alarm

### ISSUE THREAD

**Issue by dharamaraob** [grafana/grafana#33449]
**What happened**:
```
When we are using the grafana alert to send the notification for nonrunning pods
sum by (pod) (kube_pod_status_ready{condition="false"} == 1) > 0

I faced the following issue
one pod went to not running state, then an alarm went to pending state,  in next 2 mins  another pod changed state to not running, for 1 minute both pods are in not  running state. First pod status now in running state, the second pod is not running state for 8m, the grafana is alerted with two pods, even though the other pod status changed to running. 
I expected, that the pod is not in a running state for 10m. Only then it has to trigger.
The same query, with 10m wait time is working fine with prom alert manager.

- alert: pod_not_running
        expr: sum by (pod) (kube_pod_status_ready{condition="false"} == 1) > 0
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Pod - {{ $labels.pod }} not running"


```
<img width="899" alt="Screen Shot 2021-04-19 at 4 14 21 PM" src="https://user-images.githubusercontent.com/29635138/116316674-24743e00-a767-11eb-9265-57707ea14509.png">

**What you expected to happen**:
```
It has to fire the alarm when pod is not running for 10m.
grafana alert(giving another which is in not running state for 2 minutes and running state for 8m) 
<img width="404" alt="Screen Shot 2021-04-27 at 2 46 23 PM" src="https://user-images.githubusercontent.com/29635138/116317113-c4ca6280-a767-11eb-9add-64dd2177758a.png">

[Alerting] Pods Not In Running State alert
[Alerting] Pods Not In Running State alert
Pods Not In Running State
{pod="dummy-pod"}
1
{pod="test-pod"}
1
prom alert(triggering correctly)
Alert details:
  Alert: Pod - test-pod not running - warning
    Description:
```
<img width="404" alt="Screen Shot 2021-04-27 at 2 46 23 PM" src="https://user-images.githubusercontent.com/29635138/116317806-b3358a80-a768-11eb-830e-962504c11d43.png">

<img width="908" alt="Screen Shot 2021-04-27 at 2 52 51 PM" src="https://user-images.githubusercontent.com/29635138/116317579-5cc84c00-a768-11eb-82e2-fa5309f05fe1.png">
<img width="664" alt="Screen Shot 2021-04-27 at 3 01 33 PM" src="https://user-images.githubusercontent.com/29635138/116318522-c137db00-a769-11eb-9ecf-72426d9ce8b3.png">

**How to reproduce it (as minimally and precisely as possible)**:
create a pod make it fail, wait for 2 minutes, create another pod that should be in not running state, now make the first pod
to running state, second pod is not running state. But you see an alarm with two pods (first and second pod) and alarm counts from when first pod status changed to not running state.

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana/grafana:7.4.3 (hem chart version 6.6.3)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by timurista** [comment]
I observed this also, we were running this on a Kubernetes cluster that was downscaling from 4 pods to 1. During this event, 3 pods were terminating at different times. One was terminated after 1 minute, then another pod was terminated in 2 minutes, then another was terminated in 3 minutes.

I was expecting by the end of 10 minutes that there would not be any alerts sent because we would have successfully downscaled all 3 pods and have been left with just 1. However, the alert triggered anyways.
