### ISSUE TITLE
Templating Grafana / InfluxDB 

### ISSUE THREAD

**Issue by NicolasOstinelli** [grafana/grafana#3344]
Hi,
I'm using Grafana v2.5.0 and try to implement the use of templating to show our measurements on our monitoring installation.
I have some problem with this and I try to explain it.
As you can see in the image below, I want to select a device and see is power consumption, but the selected device doesent change.
![img_ 047](https://cloud.githubusercontent.com/assets/14232929/11419593/c7e06c1a-9428-11e5-88eb-3cbd9e0f9108.PNG)

The jason of the query is showed below (only a part):
 "measurement": "gridsense_HH01_techroom",
      "query": "SELECT mean(\"value\") AS \"value\" FROM \"gridsense_HH01_techroom\" WHERE \"item\" = 'HeatPump' AND \"signal\" = 'kW_tot' AND $timeFilter GROUP BY time($interval), \"item\", \"signal\"",
      "rawQuery": false,
      "refId": "B",
      "tags": [
        {
          "key": "item",
          "operator": "=",
          "value": "HeatPump"
        },
        {
          "condition": "AND",
          "key": "signal",
          "operator": "=",
          "value": "kW_tot"

I don't know if the problem is the templating that I create or if it's a bug on grafana. 
Thank's for helping me.

**Comment by torkelo** [comment]
you need to use the template variables in your query. 

Example here:
http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&edit

**Comment by NicolasOstinelli** [comment]
I use templates:
![img_ 049](https://cloud.githubusercontent.com/assets/14232929/11421084/a15130e8-9432-11e5-949e-5d43df3e2317.PNG)
![img_ 050](https://cloud.githubusercontent.com/assets/14232929/11421082/a14fba56-9432-11e5-9caf-8f5852994ca9.PNG)
![img_ 051](https://cloud.githubusercontent.com/assets/14232929/11421083/a150039e-9432-11e5-9949-dbd7a849deb0.PNG)

But I don't know what I do wrong. Could you please help me understand?
Thanks

**Comment by discoduck2x** [comment]
If youre using Influxdb then check your query, it should be something like
SELECT mean("value") AS "value" FROM /$Measurements$/ WHERE "Item" =~ /$Item$/

**Comment by discoduck2x** [comment]
...and if you use the built in query editor - does it give you the proper templating variables?

**Comment by NicolasOstinelli** [comment]
@discoduck2x:Thanks for your answer.
My query look like this now:
 "query": "SELECT mean(\"value\") AS \"value\" FROM /$Measurements$/ WHERE \"item\" =~ /$Item$/ AND \"signal\" =~ /$Signal$/ AND $timeFilter GROUP BY time($interval), \"item\", \"signal\", \"Measurements\"",
The result is better than befor. But I don't have the Boiler in the leaving room.
When I select the Measurements he don't change (look at the image below):
![img_ 053](https://cloud.githubusercontent.com/assets/14232929/11423190/9cf71476-9442-11e5-8c3f-ab4df7c6b1dc.PNG)

Maybe the error is in the Template?
@torkelo do you have some suggestions?
Thanks

**Comment by discoduck2x** [comment]
I´ve never tried templating variables on measurement names,, i would try stick everything into the same measurement e.g, and then adding tag room=gridsens_"room" along with all other tags etc.
