### ISSUE TITLE
uncorrect links from DataFrame

### ISSUE THREAD

**Issue by VladislavYak** [grafana/grafana#33443]
**What happened**:
I got table which considers links to specific microservices (column named services).
Here's how i provided links from _Dasboard settings --> Overrides_
![image](https://user-images.githubusercontent.com/69644103/116295511-d7618d80-a7a1-11eb-8369-0f0e6e539a6a.png)

It works well when i do not sort my dataframe by any column, but  when i do that it navigates me to the wrong service. Watch the gif:
![Animation](https://user-images.githubusercontent.com/69644103/116294196-5eae0180-a7a0-11eb-8b2a-e137e75be52c.gif)

**What you expected to happen**:
Wanted to be linked to the right service
**How to reproduce it (as minimally and precisely as possible)**:
Make 3 dashboards. First one should be named for example as "poo", second as "foo". Third dashbord should consider DataFrame with at least 2 columns of string (with names "poo" and "foo") and numeric types. Sort this DataFrame by numeric column, and provided that rows changed its positions, try to navigate to dashboards named "foo" and "foo"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: vertica db
- OS Grafana is installed on: 
- User OS & Browser: Windows with Google Chrome
- Grafana plugins:
- Others:

**Comment by mckn** [comment]
Thanks for reporting this! It should already be fixed in the `7.5.4` version.

See for more information:
https://github.com/grafana/grafana/issues/32981
