### ISSUE TITLE
Not all tables have primary keys, blocking initial Grafana startup with sql_require_primary_key=ON

### ISSUE THREAD

**Issue by dansimone** [grafana/grafana#33450]
**What happened**:
This issue is a follow up to https://github.com/grafana/grafana/issues/12971.  As described in that bug, if you are using for your Grafana data store MySQL > 8.0.13 with sql_require_primary_key=ON, then Grafana fails to start due to a couple of tables not having primary keys:

```
msg="Executing migration failed" logger=migrator id="Create alert_rule_tag table v1" error="Error 3750: Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set. Add a primary key to the table or unset this variable to avoid this message. Note that tables without a primary key can cause performance problems in row-based replication, so please consult your DBA before changing this setting."
```

**What you expected to happen**:

That Grafana would be able to start initially, pointing to a fresh MySQL DB with sql_require_primary_key=ON.

**How to reproduce it (as minimally and precisely as possible)**:

- Configure a MySQL 8 DB with sql_require_primary_key=ON (typical to set this for an HA-enabled MySQL instance).
- Configure Grafana to use the above MySQL as its data store.
- Start Grafana.

**Anything else we need to know?**:

Issue https://github.com/grafana/grafana/issues/12971 was closed as of https://github.com/grafana/grafana/pull/22255, but one thing not addressed by that PR is creating all tables _initially_ with primary keys.  What Grafana does now is:
- Create alert_rule_tag and annotation_tag tables initially without primary keys.
- Migrate them to new schemas that contain primary keys.

However, if you are running using MySQL with sql_require_primary_key=ON, then step 1) fails out of the gate.

Is there any reason to not change things so that the initial schema created (for a fresh Grafana instance) for alert_rule_tag and annotation_tag contain primary keys?

There are several workaround posted for how to get around this problem, but they seem like unnecessary hoops to have to jump through.

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: MySQL 8.0
- OS Grafana is installed on: OEL 8.3
- User OS & Browser: N/A
- Grafana plugins: N/A

**Comment by wbrowne** [comment]
Hi @dansimone. Thanks for the report.

>Is there any reason to not change things so that the initial schema created (for a fresh Grafana instance) for alert_rule_tag and annotation_tag contain primary keys?

We have generally avoided this in the past as it "re-writes history". However, we'll keep this issue open and keep an eye so we can prioritize it as necessary.

Thanks again!

**Comment by vin-c** [comment]
Same here with a fresh 8.3.3 docker image running on debian

Creating a new instance with a mysql-cluster backend is impossible now :/

* container does not start and throw almost the same error as described.

```
...
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="Create alert_rule_tag table v1"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="Add unique index alert_rule_tag.alert_id_tag_id"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="drop index UQE_alert_rule_tag_alert_id_tag_id - v1"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="Rename table alert_rule_tag to alert_rule_tag_v1 - v1"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="Create alert_rule_tag table v2"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="create index UQE_alert_rule_tag_alert_id_tag_id - Add unique index alert_rule_tag.alert_id_tag_id V2"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=info msg="Executing migration" logger=migrator id="copy alert_rule_tag v1 to v2"
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=eror msg="Executing migration failed" logger=migrator id="copy alert_rule_tag v1 to v2" error="Error 3098: The table does not comply with the requirements by an external plugin."
grafana_1          | t=2022-01-18T15:49:54+0000 lvl=eror msg="Exec failed" logger=migrator error="Error 3098: The table does not comply with the requirements by an external plugin." sql="INSERT INTO `alert_rule_tag` (`alert_id`\n, `tag_id`) SELECT `alert_id`\n, `tag_id` FROM `alert_rule_tag_v1`"

**Comment by wbrowne** [comment]
You can try follow the steps mentioned here @vin-c https://github.com/grafana/grafana/issues/42177#issuecomment-977723083

**Comment by vin-c** [comment]
Thanks it was here indeed https://github.com/grafana/grafana/issues/12971#issuecomment-773793513

(But what a pain to setup :shrug: )

**Comment by vin-c** [comment]
This is just a workaround, if a clean install requires these steps to work, it may still be an issue ?

**Comment by yasharne** [comment]
The same problem with grafana 8.4.1 and MySQL with group replication enabled

**Comment by SunSparc** [comment]
Confirmed to still be a problem in version `8.5.0-beta1`.

Why is an initial install of Grafana doing migrations? Is it first installing legacy data and then migrating that data? Why not just install modern data? I suppose this is to continue support for users who want legacy features. I am not sure what the best solution would be, but we should not punish new users.

Could this be added to the install/migration script?
```
SET SESSION sql_require_primary_key=0
```

**Comment by SunSparc** [comment]
Perhaps something like this:
```
func (b *BaseDialect) CreateTableSQL(table *Table) string {
    sql := "SET SESSION sql_require_primary_key=0;\n"
    sql += "CREATE TABLE IF NOT EXISTS "
    sql += b.dialect.Quote(table.Name) + " (\n"
    ...
```
In [`pkg/services/sqlstore/migrator/dialect.go`](https://github.com/grafana/grafana/blob/23956557d8c6a119b7de5be5c42024e29634d002/pkg/services/sqlstore/migrator/dialect.go#L128)

**Comment by SunSparc** [comment]
Still a problem.

**Comment by iXingo** [comment]
Still a problem.

**Comment by heytrav** [comment]
I'm running into this problem now as well. 

I thought I had found a workaround by manually creating the tables with a primary key. This seemed to work for several of them.

Now I'm running into the problem that there is a migration to add an `id int primary key` to the `seed_assignment` table and the migrations fail because the table would have two primary keys.

I can't drop the column or the constraint because our database cluster says
```
ERROR 3750 (HY000): Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.
```

The table has to be created with a primary key but the current migrations fail to create it. I don't know how to bypass that particular migration.

Any workarounds for this?

This is on a cluster with other apps so I'm reluctant to remove the constraint.

**Comment by SunSparc** [comment]
@heytrav, this is the note I have for myself. It is specific to a database I have hosted at DigitalOcean, but the concept is that you reconfigure the server to turn off the primary key requirement, do the update, then turn the requirement back on (if needed, it is a good idea).

> when upgrading Grafana databases, if this error is encountered:
> - Error 3750 (HY000): Unable to create or change a table without a primary key, when the system variable 'sql_require_primary_key' is set.
> 
> disable requiring primary key
> `$ doctl databases configuration update <database-id> --engine mysql --config-json '{"sql_require_primary_key": false}'`
> 
> do Grafana database update
> 
> re-enable requiring primary key
> `$ doctl databases configuration update <database-id> --engine mysql --config-json '{"sql_require_primary_key": true}'`
