### ISSUE TITLE
Broken grafana dashboard link can cause a DoS attack to influxdb

### ISSUE THREAD

**Issue by maklaut** [grafana/grafana#3345]
Hipchat broke the dashboard link like this:
```
http://example.com//dashboard/db/mydashboard?from=20151126T00010%3C%2Fp%3E%3Cspan%20class&to=20151126T030149
```

`from` parameter was interpreted as 1970-01-01 and requests become very slow.
The situation became seriously because this dashboard has many graphs.
So only one click on link cause that influxdb stops responding (high load average and swapping).

**Comment by toxatoor** [comment]
+1
The same problem.

**Comment by burthen** [comment]
+1
The same here. 
Really serious issue!

**Comment by torkelo** [comment]
sounds like a big problem with influxdb :)
