### ISSUE TITLE
Explore: Make importing from other data sources consistent across different data sources

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#33458]
**What would you like to be added**:

Follow up on:  https://github.com/grafana/grafana/pull/33405#discussion_r621144346 

**Why is this needed**:

With #33405 we will have the following implementations to map queries between data sources:

* Prometheus -> Loki (https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/loki/language_provider.ts#L334)
* Prometheus, Loki -> Elasticsearch (https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/language_provider.ts#L113)
* Graphite -> Loki #33405 

The conversion is done at the destination data source object, but as we add more it may make data source implementations more complex. One way of approaching this could be to extract conversion logic to separate functions or a separate component (like in #33405). All tests for importing could be also extracted to a separate file. We can also keep it at `languageProvider` until more mappings is needed.

Looping in: @ivanahuckova and @Elfo404

**Comment by ivanahuckova** [comment]
I like this! I am wondering if we couldn't create API for this so it would be easy to import queries without much customisation. Cause mapping from any data source to other data source should be easy. You basically need key-value pairs from one data source and format these key-value pairs in the other data source. 

Then any data source that has function to create key-value pairs with other data source that supports changing key-value pairs to query would support mapping.

**Comment by ifrost** [comment]
That could work! On top of key-value pairs we may also need some generic way to describe how they're connected (e.g. whether it's exact match, regexp, negation, etc.) - operators might be different between data sources.

**Comment by ivanahuckova** [comment]
Yes good point! Plus if we want to support mapping, we should also don't forget about that - to give possibility to rename keys as you do in Graphite PR.
