### ISSUE TITLE
Dashboard import failing with: Templating [$myvar] Error updating options: Cannot read property 'text' of null

### ISSUE THREAD

**Issue by kmoppel** [grafana/grafana#33463]
**What happened**:
With all latest versions after v7.3.10 one of my dashboards fails to be imported via JSON

**What you expected to happen**:
Dashboard should load as with 7.3.10 and before I assume

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a PostgreSQL datasource
2. Import the template from [here](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/postgres/v6/tables-top/dashboard.json), replacing the "dbname" variable query with a dummy one ("SELECT 'dummy' AS dbname") though, to avoid  bootstrapping a pgwatch2 metrics storage schema.

**Anything else we need to know?**:
Checked all the latest release notes also but there was only talk of deprecating some "tag group" features but not yet removing.

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: Postgres v12
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04, all browsers
- Grafana plugins: none
- Others: Detailed error message show below

![Screenshot from 2021-04-28 10-56-31](https://user-images.githubusercontent.com/346788/116367864-6e652e80-a810-11eb-8bc3-5da2172a37c2.png)

```
TypeError: Cannot read property 'tags' of null

    at t (http://0.0.0.0:3000/public/build/app.7d3798b26be143575eb4.js:2:611919)
    at O (http://0.0.0.0:3000/public/build/vendors~app.7d3798b26be143575eb4.js:2:90047)
    at div
    at s (http://0.0.0.0:3000/public/build/DashboardPage.7d3798b26be143575eb4.js:2:110997)
    at div
    at p (http://0.0.0.0:3000/public/build/DashboardPage.7d3798b26be143575eb4.js:2:112331)
    at div
    at t (http://0.0.0.0:3000/public/build/DashboardPage.7d3798b26be143575eb4.js:2:8993)
    at O (http://0.0.0.0:3000/public/build/vendors~app.7d3798b26be143575eb4.js:2:90047)
    at div
    at div
    at div
    at t (http://0.0.0.0:3000/public/build/vendors~app.7d3798b26be143575eb4.js:2:1037092)
    at m (http://0.0.0.0:3000/public/build/app.7d3798b26be143575eb4.js:2:3052342)
    at div
    at div
    at t (http://0.0.0.0:3000/public/build/DashboardPage.7d3798b26be143575eb4.js:2:268722)
    at O (http://0.0.0.0:3000/public/build/vendors~app.7d3798b26be143575eb4.js:2:90047)
    at n (http://0.0.0.0:3000/public/build/vendors~app.7d3798b26be143575eb4.js:2:663493)
    at t (http://0.0.0.0:3000/public/build/app.7d3798b26be143575eb4.js:2:1800871)
    at h (http://0.0.0.0:3000/public/build/app.7d3798b26be143575eb4.js:2:2976033)
    at t (http://0.0.0.0:3000/public/build/app.7d3798b26be143575eb4.js:2:1962642)
    at t (http://0.0.0.0:3000/public/build/app.7d3798b26be143575eb4.js:2:1963172)
    at l (http://0.0.0.0:3000/public/build/vendors~app.7d3798b26be143575eb4.js:2:87654)
```

**Comment by kmoppel** [comment]
The created PostgreSQL datasource should also be marked as default datasource

**Comment by kmoppel** [comment]
FYI - after some trial and error I manged to work around the error by specifying a dummy "selected" value for the "dbname" dropdown. Diff here: https://github.com/cybertec-postgresql/pgwatch2/commit/bf10a96e6ed3eb61652f3dd137ac7ffcb0e0fd60.
So feel free to close if the issue seems irrelevant. Thanks!

**Comment by kmoppel** [comment]
And sorry, one more general question about this bunch of v6 dashboards (most carried over from v5 even)  - does Grafana plan to generally be still backwards-compatible or should one basically re-implement all dashboards whenever a new major version appears, i.e. v8 as next ?

**Comment by dprokop** [comment]
@kmoppel we do plan to be backwards-compatible of course :)

**Comment by hugohaggmark** [comment]
Hi @kmoppel, looking at your template you're missing the datasource prop
![image](https://user-images.githubusercontent.com/562238/116663071-e5c4ca80-a996-11eb-9297-9c6b3821b0fe.png)

**Comment by kmoppel** [comment]
@hugohaggmark Thanks for the feedback! This cannot be the root cause though I think in case you want to still get to to the bottom of this...as datasource is null also for the [other 30](https://github.com/cybertec-postgresql/pgwatch2/tree/master/grafana_dashboards/postgres/v6) dashboards but they got loaded normally.

**Comment by hugohaggmark** [comment]
> @hugohaggmark Thanks for the feedback! This cannot be the root cause though I think in case you want to still get to to the bottom of this...as datasource is null also for the [other 30](https://github.com/cybertec-postgresql/pgwatch2/tree/master/grafana_dashboards/postgres/v6) dashboards but they got loaded normally.

@kmoppel thanks for quick feedback can you point me to one of those where a query variable has a datasource set to null and works, shouldn't work.

**Comment by kmoppel** [comment]
@kmoppel Ok for example [this one](https://github.com/cybertec-postgresql/pgwatch2/blob/master/grafana_dashboards/postgres/v6/db-overview/dashboard.json).
I think "null" just uses the default data source which is perfectly logical.

My original problem got fixed when the "current" attribute values of a template variable were set to empty strings or when removing the "current" attribute altogether, seems it doesn't like "null" anymore.

**Comment by hugohaggmark** [comment]
Gotcha, thank you @kmoppel. One last question are you importing this via provisioning or via the import functionality in Grafana?
![image](https://user-images.githubusercontent.com/562238/116842231-22cdce80-abdc-11eb-88f6-93d4b137f503.png)
