### ISSUE TITLE
TablePanel: Sort seems to be broken after updating to Grafana v7.5.4 (615c153b3a)

### ISSUE THREAD

**Issue by Robsta86** [grafana/grafana#33466]
After updating to Grafana v7.5.4 (615c153b3a) with the fix for the sorting issue reported in #32435 sorting broke for us in a TablePanel.

We get unexpected behavior when we're sorting on a column, see the screenshots below:

![Screenshot 2021-04-28 102921](https://user-images.githubusercontent.com/36365843/116372460-b5512500-a80c-11eb-9933-5c0dc9d89113.png)
![Screenshot 2021-04-28 102947](https://user-images.githubusercontent.com/36365843/116372466-b5e9bb80-a80c-11eb-9a0b-0d93ae4dfd7d.png)

**Comment by torkelo** [comment]
Can you use inspect / data and show the raw data? (also show the data types, you find in inspect / json / DataFrame structure)

**Comment by Robsta86** [comment]
![Screenshot 2021-04-28 104158](https://user-images.githubusercontent.com/36365843/116374609-b84d1500-a80e-11eb-8c24-47f4c086d124.png)

`[
  {
    "meta": {
      "preferredVisualisationType": "table",
      "transformations": [
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize"
      ]
    },
    "refId": "E",
    "length": 29,
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {}
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "Value #E",
        "type": "number",
        "config": {}
      }
    ]
  },
  {
    "meta": {
      "preferredVisualisationType": "table",
      "transformations": [
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize"
      ]
    },
    "refId": "A",
    "length": 29,
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {}
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "Value #A",
        "type": "number",
        "config": {}
      }
    ]
  },
  {
    "meta": {
      "preferredVisualisationType": "table",
      "transformations": [
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize"
      ]
    },
    "refId": "D",
    "length": 16,
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {}
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "Value #D",
        "type": "number",
        "config": {}
      }
    ]
  },
  {
    "meta": {
      "preferredVisualisationType": "table"
    },
    "refId": "F",
    "length": 0,
    "fields": []
  },
  {
    "meta": {
      "preferredVisualisationType": "table",
      "transformations": [
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize",
        "organize"
      ]
    },
    "refId": "G",
    "length": 8,
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {}
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "masked",
        "config": {
          "filterable": true
        },
        "type": "string"
      },
      {
        "name": "Value #G",
        "type": "number",
        "config": {}
      }
    ]
  },
  {
    "meta": {
      "preferredVisualisationType": "table"
    },
    "refId": "B",
    "length": 0,
    "fields": []
  }
]`

**Comment by Robsta86** [comment]
@torkelo any update on this matter? :-)

**Comment by torkelo** [comment]
What data source are you using? I am unable to replicate this, has be something strange going on with the raw data types, maybe mixing string and numbers in the data frame?

**Comment by svet-b** [comment]
@torkelo this is reproducible for us quite reliably, regardless of datasource, when the following conditions are met:
1. An Outer Join transformation is applied
2. At least one of the data series has rows with index values (on which the join is performed) that are not present in the other column.

We first noticed this when doing joins between GraphQL and InfluxDB data. It's obviously quite difficult to share a "reproducer" based on this, given that the datasource endpoints are private. Though it seems easy to recreate the same behavior synthetically using the "CSV Metric Values" scenario of the TestData datasource:

1. Create two series. One of them has 6 values, and the other one has 4.
<img width="641" alt="Screen Shot 2021-05-07 at 3 43 43 PM" src="https://user-images.githubusercontent.com/12831860/117501039-8729be80-af4b-11eb-9cf9-e14ed02b0139.png">
2. The series are generated in a way that there will be partial overlap between the timestamps. Join on these timestamps (though I can confirm that joining on other types of index values produces the same result)
<img width="314" alt="Screen Shot 2021-05-07 at 3 43 52 PM" src="https://user-images.githubusercontent.com/12831860/117501056-8d1f9f80-af4b-11eb-810b-0062e0ceecd3.png">
3. Sorting of the B-series, which has fewer values, is incorrect:
<img width="507" alt="Screen Shot 2021-05-07 at 3 44 19 PM" src="https://user-images.githubusercontent.com/12831860/117501062-8f81f980-af4b-11eb-8bc3-4bde70cc36b0.png">

**Comment by svet-b** [comment]
Just wanted to check in on this, as I see it's still in "needs more info" state. Happy to provide more info if helpful. Though I assume everyone's simply busy trying to get v8.0 out the door, so this just hasn't had much airtime.
