### ISSUE TITLE
Adding a option for hiding a Dashboard to viewer role

### ISSUE THREAD

**Issue by calkoe** [grafana/grafana#33474]
Hello,

i am providing Dashboards to my customers via a public organisation and the Anonymous login feature.
It would be good if a customer is not able to see the public dashboards of other customers.
A public Dashboard should only be accessible by the direct link.

That would be awesome!
Thanks!

(I've tried to remove the folder permissions for the "viewer" role and add the permissions again to the Dashboard itself,
but this don't hide the Dashboards from all Places in the Grafana UI.)

**Comment by torkelo** [comment]
this is currently not possible, and not secure if it would as a viewer role can still issue any possible query to all data sources added to the anonymous org
