### ISSUE TITLE
[docs] Docs feedback: /permissions/dashboard-folder-permissions.md

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#33470]
There are two dashboard-folder-permissions pages, one with dashes and one with underscores. They are different from each other. 

https://grafana.com/docs/grafana/latest/permissions/dashboard_folder_permissions/
https://grafana.com/docs/grafana/latest/permissions/dashboard-folder-permissions/

Suggestion:
- They should be merged or one should be deleted
- We should check for references to the deleted page, or perhaps set up a redirect to make sure links don't break elsewhere in the docs

For example I found this issue when trying to link to dashboard/folder permissions from https://grafana.com/docs/grafana/latest/enterprise/license/license-restrictions/. The current link from that page is `< relref "../../permissions/dashboard-folder-permissions.md" >`

**Comment by achatterjee-grafana** [comment]
Looking at the source code, we do not have any "dashboard_folder_permissions.md" file. I am not sure how to remove it.

**Comment by robbymilo** [comment]
The source for the file is on this branch: https://github.com/grafana/grafana/tree/v7.5.x/docs/sources/permissions which syncs to `latest`. Looks like this was fixed in `master` for `next`: https://github.com/grafana/grafana/tree/master/docs/sources/permissions

**Comment by achatterjee-grafana** [comment]
Seems like the change made to `next` did not make it to `latest`. I have made the change manually via PR https://github.com/grafana/grafana/pull/33497.
