### ISSUE TITLE
$tag_name in alias for opentsdb metric doesn't work

### ISSUE THREAD

**Issue by bizhao** [grafana/grafana#3347]
Version 2.5
Using $tag_tagname as suggested but it doesn't work.
The tag name is host, but the legend still shows $tag_host.

Same metric works fine in opentsdb.
![opentsdb](https://cloud.githubusercontent.com/assets/1912361/11421113/89e6f43e-946d-11e5-84bc-543012c5728f.png)
![tag_name](https://cloud.githubusercontent.com/assets/1912361/11421112/89e63bc0-946d-11e5-97cf-cb43bcbeba70.png)

**Comment by torkelo** [comment]
You need to group by tag for openTSB to return tag information (and split Series based on tag)
