### ISSUE TITLE
Prometheus: Try to use labels API instead of series API as it newly supports match

### ISSUE THREAD

**Issue by luhhujbb** [grafana/grafana#33487]
**What happened**:
On metric with high cardinality (a lots of prometheus series) we can't get label values.
This is because label_values use /api/v1/series instead of /api/1v/label when there is a metric defined.

It comes from here :
https://github.com/grafana/grafana/blob/b5190ee547340aa8f9e4d9e32d4ff05e3687d449/public/app/plugins/datasource/prometheus/metric_find_query.ts#L73-L109

It uses /api/v1/series endpoint when there is a serie selector (metric) to match

**What you expected to happen**:

The documentation of prometheus HTTP API indicates that it supports "match" field on label value endpoint
https://prometheus.io/docs/prometheus/latest/querying/api/#querying-label-values

This endpoint is well optimized to retrieve label values.

**How to reproduce it (as minimally and precisely as possible)**:

Fill a prometheus/victoria metrics server with a high cardinality metrics (3 tag/label with 500 different values), getting values from one label/tag will return 250000 of series using series endpoint, but only 500 label values using label endpoint.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: prometheus 2.26/victoriametrics 1.58.0
- OS Grafana is installed on: dockerofficial image
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by luhhujbb** [comment]
It seems that this new feature exists only since v2.24 of prometheus.

**Comment by ivanahuckova** [comment]
Yes, as you have mentioned, support of `match` param in `/labels` API is quite a new thing. It was added in [january 2021](https://github.com/prometheus/prometheus/releases/tag/v2.24.0). So if we would implement this, we would need to handle the fact that some of our users are not on the newest versions of prometheus.

**Comment by bboreham** [comment]
As we approach a year since support for this was added in Prometheus, can I re-raise this request for Grafana Prometheus datasource to use the better API.

**Comment by colega** [comment]
This change coming to Prometheus should also improve the `/label/<name>/values` performance so it's another reason to switch: https://github.com/prometheus/prometheus/pull/9907

**Comment by gabor** [comment]
we will have to decide how to handle users with Prometheus older than v2.24.0 (where this feature was added).
i did a quick check, and it seems we will not be able to feature-detect this (Prometheus older than v2.24.0 does not reject a query to label-values-with-matches), so the try-it-and-if-it-fails-use-old-api approach will not work here.

**Comment by chenlujjj** [comment]
Can we maintain the prometheus version in datasource metadata?

**Comment by bboreham** [comment]
I'm not sure if there is a clean way to get the version from the backend: Cortex/GEM will not answer `/status/buildinfo` (and doesn't map to a released Prometheus version), and there are other non-Prometheus stores using the same API like Chronosphere.
Perhaps we could add an "API version" to the Prometheus API, but that pushes out the fix by some months.

Could you probe something else that would error in the older versions, for instance `/query_exemplars`, added in 2.26?

**Comment by nachopv** [comment]
Hi

As long as the Feature Request solution will only apply for upcoming versions, that means that grafana will need to deal with this issue for a while 
Is not only demanding excesive ammounts of data prometheus backends but also consuming tons of memory on the browser side
I think it makes sense to consider to have the chance to set up a flag on the datasource definition in order to control this behaviour

**Comment by dimitarvdimitrov** [comment]
prometheus has the `/api/v1/status/buildinfo` endpoint as of `v2.14` which exposes a version string ([docs](https://prometheus.io/docs/prometheus/latest/querying/api/#build-information))

**Comment by colega** [comment]
Can we use the [same piece of code](https://github.com/grafana/grafana/blob/509e34cfe7b702e2e5ad2a1d66c989b695ae3c45/public/app/types/unified-alerting-dto.ts#L74-L79) that is used for ruler api support?
It already checks the buildinfo endpoint and reads the application name, we'd just need to check the version too.

**Comment by alanprot** [comment]
Hi...

Based on https://github.com/grafana/grafana/pull/54263#issuecomment-1228938668,  is there any documentation on how this "prometheus version detection" will work? I imagine that projects like thanos or cortex will need to expose  this info somehow to grafana can take decision on, for instance, what endpoint to call.

**Comment by gtk-grafana** [comment]
@alanprot Not yet, we're still figuring out the details! Is there anything you would like to see?

**Comment by alanprot** [comment]
I was looking at grafana code it is already implementing what @bboreham suggested on https://github.com/prometheus/prometheus/issues/10022

https://github.com/grafana/grafana/blob/f3085b1cacef1a7cda5963320f116555b4389fa9/public/app/types/unified-alerting-dto.ts#L59-L70

I wonder if we should go ahead with the idea and make those "features" list documented so all other projects can comply and hint what features it supports.

in order to do so i think grafana would need to keep a documentation somehow of this feature list and the intended behavior.

**Comment by gtk-grafana** [comment]
Yeah @alanprot those features appear to be returned from the Mimir API right now, but we don't seem to have feature detection for the other flavors (yet). I'm currently trying to find out if the Mimir api has always supported this change as well or if we'll need to support the old usage for certain versions for Mimir as well.

And agreed, we're going to want to make sure this is well documented.

**Comment by gtk-grafana** [comment]
Actually it looks like Mimir has always supported this API since launch (2.0.0), so we should be good to make this change for all Mimir datasources, but I'll make sure to test that.

**Comment by gtk-grafana** [comment]
@alanprot So as I'm getting into Cortex I'm realizing that we're assuming that Cortex will always support the latest prometheus API changes (like the labels api change requested here), as we don't currently have any solution for checking the cortex version.

It looks like the grafana code currently checks to see if the `/api/v1/status/buildinfo` endpoint returns a 404, and then we label that datasource as cortex, which doesn't seem like an ideal long term solution.

I have a few questions:
* Is the labels API with match always supported in all versions of Cortex? (i.e. can we release this particular change for all cortex clients?)
* Is there a better way to check the cortex flavor? Is there an API we could be using?
* How do we want this to work long term? Mimir gives us an array of feature flags in the buildinfo api endpoint which is the best solution (for us) I've seen, but I'm curious to hear your thoughts on this.

I've yet to dive into Thanos yet, I'll be looking into that next.

**Comment by alanprot** [comment]
* Is the labels API with match always supported in all versions of Cortex? (i.e. can we release this particular change for all cortex clients?)
    > Seems only cortex v1.8.0 introduced the `match[]` parameter on the `labelValues` api
* Is there a better way to check the cortex flavor? Is there an API we could be using?
  > Not that am aware of :(
* How do we want this to work long term? Mimir gives us an array of feature flags in the buildinfo api endpoint which is the best solution (for us) I've seen, but I'm curious to hear your thoughts on this.
 > Maybe we should get someone from thanos to chime in as well?

**Comment by gtk-grafana** [comment]
* Seems only cortex v1.8.0 introduced the `match[]` parameter on the `labelValues` api
> Hmm, v1.8.0 is only from march 2021. Since we don't have a way to detect the cortex version we'd currently have to assume support  for all or none cortex clients.

I'm now thinking it would be better to ignore the version/flavor detection for this issue and just fall back to the old API after trying the new one, and then worry about defining the buildinfo api requirements for feature flags as a long-term goal to get better support between Grafana and Cortex/Mimir/Thanos.

**Comment by gtk-grafana** [comment]
Ugh, no I forgot 
> (Prometheus older than v2.24.0 does not reject a query to label-values-with-matches), so the try-it-and-if-it-fails-use-old-api approach will not work here.
