### ISSUE TITLE
Non default logging directory causes grafana to fail to start

### ISSUE THREAD

**Issue by jamesblackburn** [grafana/grafana#3349]
I've untar'd grafana 2.5 and made the installation read-only. I'm configuring as per:
http://docs.grafana.org/installation/configuration/

I create a configuration with only a change to the datadir and logdir:

```
[paths]
data = /users/is/jblackburn/grafana/var

#
# Directory where grafana can store logs
#
;logs = /var/log/grafana
logs = /users/is/jblackburn/grafana/logs
```

And I ran grafana, and it fails (trying to write to a read-only logs dir):

```
$ grafana-server -homepath /apps/research/tools/grafana/current/ -config git/monit/conf/logs.dev.man.com/etc/grafana.ini 
2015/11/26 11:15:39 [log.go:290 Error()] [E] Fail to set logger(file): open /apps/research/tools/grafana/current/data/log/grafana.log: no such file or directory
```

Issue #2508 mentions a workaround, which works:

```
$ grafana-server -homepath /apps/research/tools/grafana/current/ -config git/monit/conf/logs.dev.man.com/etc/grafana.ini "cfg:default.paths.logs=/users/is/jblackburn/grafana/logs"
2015/11/26 11:16:45 [I] Starting Grafana
2015/11/26 11:16:45 [I] Version: 2.5.0, Commit: v2.5.0+1-g287d8ca, Build date: 2015-10-28 08:43:28 +0000 GMT
2015/11/26 11:16:45 [I] Configuration Info
Config files:
  [0]: /apps/research/tools/grafana/current/conf/defaults.ini
  [1]: git/monit/conf/logs.dev.man.com/etc/grafana.ini
Command lines overrides:
  [0]: default.paths.logs=/users/is/jblackburn/grafana/logs
Paths:
  home: /apps/research/tools/grafana/current/
  data: /users/is/jblackburn/grafana/var
  logs: /users/is/jblackburn/grafana/logs

2015/11/26 11:16:45 [I] Database: sqlite3
2015/11/26 11:16:45 [I] Migrator: Starting DB migration
2015/11/26 11:16:45 [I] Migrator: exec migration id: create migration_log table
2015/11/26 11:16:45 [I] Migrator: exec migration id: create user table
2015/11/26 11:16:45 [I] Migrator: exec migration id: add unique index user.login
2015/11/26 11:16:45 [I] Migrator: exec migration id: add unique index user.email
2015/11/26 11:16:45 [I] Migrator: exec migration id: drop index UQE_user_login - v1
...
```

It seems wrong that grafana 2.5 doesn't respect the log dir from the config, and the workaround is documented...

**Comment by jamesblackburn** [comment]
And as with @iwinux on #2508 and the issue #2175 disabling the file logger in my `grafana.ini` doesn't help.

It looks like, grafana is *respecting* the log file path from the config file. However on startup it `touch`es the file referenced in the default log path or specified on the command line.

If I do this:
```
logs = .../logs
$ grafana-server  -config .../grafana.ini "cfg:default.paths.logs=.../logs2"
```
Grafana attempts to create a file under `.../logs2/grafana.log` but logs to under `.../logs/grafana.log`

**Comment by torkelo** [comment]
yes, it is best to use the "cfg:default.paths.logs" override. As logging is temporarily initialized before reading config in order to log error while reading config :)

**Comment by jamesblackburn** [comment]
Hi @torkelo - this is a bug though, right? In that the documentation implies otherwise, and the workaround is only documented in closed tickets...

Can this issue stay open until this is documented / fixed?

**Comment by torkelo** [comment]
ah, sorry, your right!

**Comment by oddlittlebird** [comment]
@marefr, what needs to change in the docs to address this?

**Comment by marefr** [comment]
@oddlittlebird this [section](https://grafana.com/docs/grafana/latest/installation/configuration/#logs) needs update. I haven't a definite answer of exactly what or how to write it. But something like this:

Path to where Grafana will store logs. This path is usually specified via command line in the init.d script or the systemd service file. It can be overridden in the configuration file or in the default environment variable file. However, please note that by overriding this the default log path will be used temporarily until Grafana have fully initialized/started.

Override log path using the command line argument `cfg:default.paths.log`:
```bash
./grafana-server --config /custom/config.ini --homepath /custom/homepath cfg:default.paths.logs=/custom/path
```
