### ISSUE TITLE
Feature Request: Toggle Hide/Show Navigation Bar

### ISSUE THREAD

**Issue by BabuBhatt** [grafana/grafana#3350]
It'll be great to have a keyboard shortcut or dashboard toggle to hide/show the navigation bar. Would be especially useful in kiosk environments where Grafana is not interacted with.

**Comment by bergquist** [comment]
Are there any standard short cuts for that behaviour?
CTRL + K + B in sublime text does something similar.

**Comment by ygbr** [comment]
+1

**Comment by bergquist** [comment]
Kiosk mode was added in Grafana 4
