### ISSUE TITLE
Collapsing a row with panels below that row moves those panels into the row

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#33505]
Grafana 7.5.4
Windows 10, Chrome 90.0.4430.93

If I start with:
![image](https://user-images.githubusercontent.com/7028403/116470668-f824f400-a830-11eb-854f-de43f3046fa7.png)

And then expand and then collapse the row, I then have:
![image](https://user-images.githubusercontent.com/7028403/116470742-0e32b480-a831-11eb-8d2e-88ee09216a27.png)

Which is obviously not desirable. This issue has been present since at least some 7.4.x version.

**Comment by torkelo** [comment]
This has always been how row works , when collapsed they take all panels below up to the next row, to mark where a row ends you need to add an additional row

**Comment by nabelekt** [comment]
Hmm, ok. I think better functionality would be to have the user explicitly add panels to a particular row.
