### ISSUE TITLE
Sort switch port

### ISSUE THREAD

**Issue by PatHoo** [grafana/grafana#33509]
**What would you like to be added**:
With snmp_exporter, in Grafana Dashboard ID(10523) -> Settings -> Variables
Query: `query_result(ifHCInOctets{job="snmp",instance="$Device"})`
Regex: `.*ifName="(Fo.*?|Te.*?)",.*`
Sort: `Numerical(asc)`
```
Preview of values
All
Fo1/0/25
Fo1/0/26
Te1/0/1
Te1/0/10
Te1/0/11
Te1/0/12
Te1/0/13
Te1/0/14
Te1/0/15
Te1/0/16
Te1/0/17
Te1/0/18
Te1/0/19
Te1/0/2
Te1/0/20
Te1/0/21
Te1/0/22
Te1/0/23
Te1/0/24
```
**Why is this needed**:
I want this:
```
Preview of values
All
Fo1/0/25
Fo1/0/26
Te1/0/1
Te1/0/2
Te1/0/3
...
Te1/0/10
Te1/0/11
...
```

**Comment by torkelo** [comment]
the values are not numerical
