### ISSUE TITLE
Derivative option in influxDB 9.x and KairosDB

### ISSUE THREAD

**Issue by EstebanSantana** [grafana/grafana#3351]
Hello,
I don't find the 'derivative' function in InfluDB 9.x and 'diff' function in KairosDB.
Theses features they are planned in one future version?

Many thanks for your work.
Esteban

**Comment by torkelo** [comment]
For InfluxDB it will be solved by the new editor that will soon be merged to master, 
https://github.com/grafana/grafana/issues/2802#issuecomment-159611025

For KairosDB not sure, someone can submit a PR :)

**Comment by EstebanSantana** [comment]
Thanks i wait this and i chose InfluxDB rather than KairosDB.
