### ISSUE TITLE
ClickHouse plugin alert get 401 Unauthorized error

### ISSUE THREAD

**Issue by tmanh17** [grafana/grafana#33519]
**What happened**:

ClickHouse Datasource alert is always in pending/alerting status with error ```Error: tsdb.HandleRequest() error rpc error: code = Unknown desc = invalid status code. status: 401 Unauthorized```

**What you expected to happen**:

Just notify an alert when it exists actually

**How to reproduce it (as minimally and precisely as possible)**:

1. Install vertamedia-clickhouse-datasource plugin
2. create a dashboard and panel that use ClickHouse Datasource then create an alert for this.
3. wait a few seconds then check the panel created
![image](https://user-images.githubusercontent.com/29015535/116531999-f713c580-a909-11eb-93a3-c74149482d75.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.4.2
- Data source type & version: 
- OS Grafana is installed on: Debian 8.5
- User OS & Browser: Ubuntu 20.04 & Chrome
- Grafana plugins: vertamedia-clickhouse-datasource
- Others:

**Comment by mckn** [comment]
Thanks for reporting this, however this isn't a grafana managed plugin so I would recommend you to open an issue in the following repository instead: https://github.com/Vertamedia/clickhouse-grafana
