### ISSUE TITLE
pid file is only readable by grafana

### ISSUE THREAD

**Issue by andsens** [grafana/grafana#3352]
After upgrading to 2.5 my `process_running` check in my monitoring framework fails because `/var/run/grafana-server.pid` is no longer readable by others. If readability by others is a security issues, may I suggest `chgrp`'ing the file to something like `adm` on debian?

**Comment by bergquist** [comment]
Thanks for reporting.

Seems to be fixed by now :)
https://github.com/grafana/grafana/blob/master/pkg/cmd/grafana-server/main.go#L100
