### ISSUE TITLE
Direct link rendered image unable to deal with Chinese

### ISSUE THREAD

**Issue by dccrazyboy** [grafana/grafana#3353]
hi,

when i try to render a image from api like this:
`http://192.168.2.169:5000/render/dashboard-solo/db/new-dashboard?panelId=1&fullscreen&from=1448592401916&to=1448614001916&width=1000&height=500`

the title has some unicode like chinese '中文'，but the image title looks wrong:

![image](https://cloud.githubusercontent.com/assets/2993912/11437337/f86a01e8-9527-11e5-99c6-86624a1c3a3f.png)

i try'd the lastest version(2.5), but there still have this problem.

**Comment by torkelo** [comment]
you probably need to install chinese or unicode fonts on the server so phantomjs can use it
