### ISSUE TITLE
Can't set up the default_home_dashboard_path 

### ISSUE THREAD

**Issue by avlitman** [grafana/grafana#33537]
**What happened**:
I'm trying to set a custom default home dashboard (with json file) with default_home_dashboard_path variable, But nothing has changed.
 
**What you expected to happen**:
see in Grafana web the custom home dashboard I added in the grafana.ini file under 'dashboards'

**How to reproduce it (as minimally and precisely as possible)**:
1. login to my grafana server
2. add my custom home dashboard json under: /usr/share/ovirt-engine-dwh/conf/grafana-dashboards/home/home.json
3. add a yml file under: /etc/grafana/conf/provisioning/dashboards/grafana-dwh-dashboards-home.yaml (tried also without the yml file)
4. Edit /etc/grafana/grafana.ini **or** /usr/share/ovirt-engine-dwh/conf/grafana.ini.in
5. add under: [dashboards]
default_home_dashboard_path = /usr/share/ovirt-engine-dwh/conf/grafana-dashboards/home/home.json
6. systemctl restart grafana-server

**Anything else we need to know?**:

1.**grafana-dwh-dashboards-home.yaml:**
---
apiVersion: 1

providers:
- name: Home Dashboard
  orgId: 1
  folder: null
  folderUid: null
  type: file
  disableDeletion: false
  editable: true
  updateIntervalSeconds: 10
  allowUiUpdates: true
  options:
    path: /usr/share/ovirt-engine-dwh/conf/grafana-dashboards/home/

2.**home.json:**

{
  "__inputs": [
    {
      "name": null,
      "label": null,
      "description": "",
      "type": "datasource",
      "pluginId": "postgres",
      "pluginName": "PostgreSQL"
    }
  ],
  "__requires": [
    {
      "type": "panel",
      "id": "dashlist",
      "name": "Dashboard list",
      "version": ""
    },
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "6.7.4"
    },
    {
      "type": "panel",
      "id": "homelinks",
      "name": "Home Links",
      "version": ""
    },
    {
      "type": "panel",
      "id": "news",
      "name": "News Panel",
      "version": ""
    },
    {
      "type": "datasource",
      "id": "postgres",
      "name": "PostgreSQL",
      "version": "1.0.0"
    },
    {
      "type": "panel",
      "id": "text",
      "name": "Text",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "panels": [
    {
      "content": "<div class=\"dashboard-header\">\n  <span>Monitoring Portal</span>\n</div>",
      "datasource": null,
      "editable": true,
      "gridPos": {
        "h": 2,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "links": [],
      "mode": "html",
      "style": {},
      "title": "",
      "transparent": true,
      "type": "text"
    },
    {
      "datasource": null,
      "folderId": 29,
      "gridPos": {
        "h": 8,
        "w": 10,
        "x": 0,
        "y": 2
      },
      "headings": false,
      "id": 3,
      "limit": 30,
      "links": [],
      "query": "",
      "recent": false,
      "search": true,
      "starred": false,
      "tags": [],
      "title": "oVirt Executive Dashboards",
      "type": "dashlist"
    },
    {
      "cacheTimeout": null,
      "datasource": null,
      "gridPos": {
        "h": 31,
        "w": 9,
        "x": 10,
        "y": 2
      },
      "id": 4,
      "links": [
        {
          "targetBlank": true,
          "title": "",
          "url": ""
        }
      ],
      "options": {
        "feedUrl": "https://grafana.com/blog/news.xml"
      },
      "pluginVersion": "6.7.4",
      "targets": [
        {
          "format": "table",
          "group": [],
          "metricColumn": "none",
          "rawQuery": true,
          "rawSql": "\n\n",
          "refId": "A",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "column"
              }
            ]
          ],
          "timeColumn": "time",
          "where": [
            {
              "name": "$__timeFilter",
              "params": [],
              "type": "macro"
            }
          ]
        }
      ],
      "title": "Latest from the blog",
      "type": "news"
    },
    {
      "datasource": null,
      "gridPos": {
        "h": 31,
        "w": 5,
        "x": 19,
        "y": 2
      },
      "id": 123124,
      "links": [],
      "title": "Useful links",
      "type": "homelinks"
    },
    {
      "datasource": null,
      "folderId": 30,
      "gridPos": {
        "h": 7,
        "w": 10,
        "x": 0,
        "y": 10
      },
      "headings": false,
      "id": 123125,
      "limit": 30,
      "links": [],
      "query": "",
      "recent": false,
      "search": true,
      "starred": false,
      "tags": [],
      "title": "oVirt Inventory Dashboards",
      "type": "dashlist"
    },
    {
      "datasource": null,
      "folderId": 35,
      "gridPos": {
        "h": 8,
        "w": 10,
        "x": 0,
        "y": 17
      },
      "headings": false,
      "id": 123126,
      "limit": 30,
      "links": [],
      "query": "",
      "recent": false,
      "search": true,
      "starred": false,
      "tags": [],
      "title": "oVirt Service Level Dashboards",
      "type": "dashlist"
    },
    {
      "datasource": null,
      "folderId": 37,
      "gridPos": {
        "h": 8,
        "w": 10,
        "x": 0,
        "y": 25
      },
      "headings": false,
      "id": 123127,
      "limit": 30,
      "links": [],
      "query": "",
      "recent": false,
      "search": true,
      "starred": false,
      "tags": [],
      "title": "oVirt Trend Dashboards",
      "type": "dashlist"
    }
  ],
  "schemaVersion": 22,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "hidden": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ],
    "type": "timepicker"
  },
  "timezone": "browser",
  "title": "Home",
  "uid": "Home",
  "variables": {
    "list": []
  },
  "version": 1
}

**Environment**:
- Grafana version: 6.7.4 and 7.3.6
- Data source type & version: PostgreSQL
- OS Grafana is installed on: CentOS Linux 8 
- User OS & Browser: 
- Grafana plugins:
- Others: 
Any help would be appreciated, thank you very much.

**Comment by avlitman** [comment]
Hi I was able to fix it! 
Thank you so much.
Noe I got this error https://github.com/grafana/grafana/issues/26447 : can see it's fixed in 7.4 version

Thanks again,
Aviv

**Comment by marefr** [comment]
@avlitman #28750 was included in 7.4.0-beta1. If you believe it still doesn't work please open a new bug report. Thanks
