### ISSUE TITLE
Docs feedback: Widths between 970px and 982px rendor poorly 

### ISSUE THREAD

**Issue by mrjones-plip** [grafana/grafana#33546]
Hi there! The docs on grafana (eg [this page](https://grafana.com/docs/grafana/latest/auth/)), are intended to have 3 states, but actually have 4.  The 4th looks bad and is found  starting at  970px wide and up to 982px wide.  This happened to be the browser width of my window at the time, hence how I noticed it.

### Full 

![grafana docs1](https://user-images.githubusercontent.com/8253488/116608106-a8edca80-a8e7-11eb-9871-17244235a349.png)

### Semi-full

![grafana docs2](https://user-images.githubusercontent.com/8253488/116608130-af7c4200-a8e7-11eb-85a1-b580f3f741fc.png)

### Mobile

![grafana docs3](https://user-images.githubusercontent.com/8253488/116608148-b7d47d00-a8e7-11eb-9863-45f3f5f42556.png)

### 970px wide and up to 982px wide

![grafana docs4-bad](https://user-images.githubusercontent.com/8253488/116608229-d0449780-a8e7-11eb-94ff-9f6983d9aa9e.png)

**Comment by mckn** [comment]
Thanks for reporting this! I'm closing this one and opening a new one In the proper repository with a reference to this one.
