### ISSUE TITLE
grafana can not create influxdb nested variables

### ISSUE THREAD

**Issue by meng2014** [grafana/grafana#3355]
I use influxDB 0.9.3。Grafana2.1.3.
I already have a variable named "ip" for influxDB and I want to create a nested variable(not a variable) named "port" for influxDB in Grafana console,but when I try to write:
SHOW TAG VALUES WITH KEY = "port"  WHERE ip=~ /$ip/
none values can be hit.So who can help me ? 
Here is docs:
http://docs.grafana.org/datasources/influxdb/

**Comment by torkelo** [comment]
can you open chrome dev tools (f12), network tab and check if that the correct influxdb query is issued and influxdb response?

**Comment by meng2014** [comment]
The port variable is set like this:"SHOW TAG VALUES FROM "10.77.128.101:8080-bolt" WITH KEY = "port" WHERE ip=~ /$ip/" . AND the URL like this:"http://localhost:3000/api/datasources/proxy/1/query?epoch=ms&q=SHOW+TAG+VALUES+FROM+%2210.77.128.101:8080-bolt%22+WITH+KEY+%3D+%22port%22+WHERE+ip%3D~+%2F(10%5C.77%5C.128%5C.101)%2F" . The result likes this : {"results":[{}]} . Does it mean the url is right and none values can be hit?
By the way,both ip and port are  TAG in influxdb not  field.Then what should I do next?Thank you !
