### ISSUE TITLE
Logs panel not displaying full logs

### ISSUE THREAD

**Issue by giom-l** [grafana/grafana#33559]
**What happened**:
We are migrating from a grafana 6.5.2 to a grafana 7.5.2
In one of our dashboard, we used the logs panel to display some logs from Elasticseach and it went well.
However, it does not work anymore in grafana  7.5.2 where we only have timestamp displayed (because I toggled "time")
Otherwise, I only have "1" displayed
The datasource is the same (elasticsearch index)

What we had in grafana 6.5.2
![image](https://user-images.githubusercontent.com/29728596/116682691-dcdff300-a9ae-11eb-8fd6-e3edca9cd1dd.png)

What we have now 
![image](https://user-images.githubusercontent.com/29728596/116682766-f6813a80-a9ae-11eb-9443-1658ea9c826a.png)

**What you expected to happen**:
Logs to be displayed

**How to reproduce it (as minimally and precisely as possible)**:
Here is my panel configuration
![image](https://user-images.githubusercontent.com/29728596/116699317-b9747280-a9c5-11eb-96db-5c30e856124a.png)

I tried to change toggle various options but that remained unsuccessful.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Amazon linux 2
- User OS & Browser: Firefox, Chrome, Brave (all latest versions)
- Grafana plugins: /
- Others: /

**Comment by mckn** [comment]
Thanks for reporting this. Would it be possible to get your panel json to be able to reproduce this easier?

**Comment by giom-l** [comment]
Sure, here it is 

`   {
      "datasource": "Elasticsearch - IODS - Spark rt logs ",
      "fieldConfig": {
        "defaults": {},
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 0
      },
      "id": 3,
      "options": {
        "dedupStrategy": "none",
        "showLabels": false,
        "showTime": true,
        "sortOrder": "Descending",
        "wrapLogMessage": false
      },
      "targets": [
        {
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "auto",
                "min_doc_count": 0,
                "trimEdges": 0
              },
              "type": "date_histogram"
            }
          ],
          "metrics": [
            {
              "field": "select field",
              "id": "1",
              "meta": {},
              "settings": {},
              "type": "logs"
            }
          ],
          "query": "message:\"error\"",
          "refId": "B",
          "timeField": "@timestamp"
        }
      ],
      "timeFrom": null,
      "timeShift": null,
      "title": "Logs details",
      "type": "logs"
    }`

**Comment by Elfo404** [comment]
Hi @giom-l, have you configured your datasource settings with valid `Message field name` and `Level field name` settings?

![Screenshot 2021-05-14 at 09 22 04](https://user-images.githubusercontent.com/1170767/118243003-dd3fba00-b495-11eb-9fa3-70a354228327.png)

**Comment by giom-l** [comment]
Damn, you're right @Elfo404 
Those settings were not set in the previous versions and we just migrated the grafana intance (not the DB) so it was not in the current version.

Setting them properly make the panel work fine :)
I guess it was somewhat inferred previously ?

**Comment by Elfo404** [comment]
Glad you solved it.

they are indeed somewhat inferred when those settings are not set, right now for example the log message field is taken from the first string value in the response, but it's just an implementation detail, so those fields should always be set to have a predictable result.
