### ISSUE TITLE
Azure Monitor datasource: extend supported metrics for Microsoft.Sql/servers/databases

### ISSUE THREAD

**Issue by marcoboffi** [grafana/grafana#33566]
**What would you like to be added**:
Azure Monitor datasource does not support all metrics available in Microsoft.Sql/servers/databases Namespace.   
For example are not available:

-  diff_backup_size_bytes
-  full_backup_size_bytes

and several other metrics 

**Why is this needed**:

These metrics are very useful to build a complete dashboard on SQL Server instance.

**Comment by andresmgot** [comment]
I think this is either a documentation error or missing fields in the Azure API. It's true that the documentation list many [metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/metrics-supported#microsoftsqlserversdatabases) but those are not listed when requesting metrics definitions:

```
curl 'http://localhost:3000/api/datasources/proxy/42/azuremonitor/subscriptions/<sub-id>/resourceGroups/cloud-datasources/providers/Microsoft.Sql/servers/andres-test/databases/andres-test/providers/microsoft.insights/metricdefinitions?api-version=2018-01-01&metricnamespace=Microsoft.Sql%2Fservers%2Fdatabases' | jq -r '.value[].name.value'
cpu_percent
physical_data_read_percent
log_write_percent
dtu_consumption_percent
storage
connection_successful
connection_failed
blocked_by_firewall
deadlock
storage_percent
xtp_storage_percent
workers_percent
sessions_percent
dtu_limit
dtu_used
sqlserver_process_core_percent
sqlserver_process_memory_percent
tempdb_data_size
tempdb_log_size
tempdb_log_used_percent
allocated_data_storage
```

Which are actually the same list that you get when using Azure Monitoring:

![Screenshot from 2021-07-15 16-56-35](https://user-images.githubusercontent.com/4025665/125810223-93f9bf78-588b-4a16-ab79-34628cc47cc2.png)

Thoughts? cc/ @joshhunt @kostrse

**Comment by andresmgot** [comment]
Hi @marcoboffi,

I am going to close this issue since there is not anything that we can do from our side at the moment since it's the Azure API the one that doesn't expose those metrics. Maybe you can contact the Azure Monitor support team to understand why those metrics are not available on the Azure Portal? Once those are there you should be able to see them as well in Grafana.

Please, reopen this issue if you think there is still something that we should look at.
