### ISSUE TITLE
The series is displayed incorrectly in the tooltip of timeseries panel.

### ISSUE THREAD

**Issue by xAnder1402** [grafana/grafana#33574]
Grafana 7.5.5
Chrome 90.0.4430.85 x64
Windows 10 20H2
![image](https://user-images.githubusercontent.com/12598781/116708203-23961300-a9d8-11eb-8e04-72054b8bee5b.png)
![image](https://user-images.githubusercontent.com/12598781/116708220-298bf400-a9d8-11eb-8b16-e72eb06f6103.png)

**Comment by dprokop** [comment]
@xAnder1402 do you mind sharing data that the panel displays the tooltip wrong for? You can do this by using [panel inspect](https://grafana.com/docs/grafana/latest/panels/inspect-panel/)

**Comment by xAnder1402** [comment]
![image](https://user-images.githubusercontent.com/12598781/118595217-53ecf800-b7b3-11eb-84b4-00b946b8e2d3.png)


[Количество и стоимость кодов по заказам и отгрузкам-data-as-seriestocolumns-2021-05-18 08_28_29.zip](https://github.com/grafana/grafana/files/6498612/-data-as-seriestocolumns-2021-05-18.08_28_29.zip)

**Comment by xAnder1402** [comment]
8.0.2 Fixed
![image](https://user-images.githubusercontent.com/12598781/121881802-673ea500-cd18-11eb-9757-cb50b3056c35.png)
