### ISSUE TITLE
Start frontend dev

### ISSUE THREAD

**Issue by yousef-soliman** [grafana/grafana#33582]
**What happened**:
When i try to start frontend dev using `yarn start` i got these errors 
```
ERROR in ./packages/grafana-ui/src/components/Icon/iconBundle.ts
Module not found: Error: Can't resolve '../../../../../public/img/icons/unicons/wrap-text.svg' in '/home/yousef/Projects/Go/grafana/packages/grafana-ui/src/components/Icon'
 @ ./packages/grafana-ui/src/components/Icon/iconBundle.ts 126:0-87 280:12-17
 @ ./packages/grafana-ui/src/components/Icon/Icon.tsx
 @ ./packages/grafana-ui/src/components/index.ts
 @ ./packages/grafana-ui/src/index.ts
 @ ./public/app/app.ts
 @ ./public/app/index.ts
```
**What you expected to happen**:
start localhost env
**How to reproduce it (as minimally and precisely as possible)**:
```
git clone https://github.com/grafana/grafana.git
yarn install --pure-lockfile
yarn start
```
**Anything else we need to know?**:

**Environment**:
- Grafana version: latest version
- OS Grafana is installed on: fedora

**Comment by torkelo** [comment]
unable to replicate this, can you try removing node_modules and try again?
