### ISSUE TITLE
Visual bug with the ">" character in the tab title

### ISSUE THREAD

**Issue by MrBlood01** [grafana/grafana#33594]
Hi everyone, I've been trying to figure out how to solve this problem for days:

![bug](https://user-images.githubusercontent.com/76105951/116756214-067b3780-aa0c-11eb-9492-86fbd6be01fe.jpg)

As you can already guess from the title I'm trying to insert the ">" symbol inside the title of a tab. 
But it is automatically converted to "& gt;".

Can anyone help me out? Thanks so much everyone in advance!

- Grafana version: 7.5.5
- Data source type & version: Sql Server 
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10 & Chrome / Edge / Firefox

**Comment by MrBlood01** [comment]
Can anyone help me out?

Thanks.

**Comment by MrBlood01** [comment]
@torkelo So is it a global bug? I have to do something?

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/33617
