### ISSUE TITLE
Hide "No Data" text

### ISSUE THREAD

**Issue by bakman2** [grafana/grafana#33599]
**What would you like to be added**:
I want my panel to be empty if there is no data. 
So I put a space in the `No Value: What to show when there is no value` field.
This space is being ignored, any other character will work. 

**Why is this needed**:
By default this field is empty and yet `No Data` is displayed.
The field and the output should match. ie: the field should also say: `No Data`, then it would actually match.

This may be a non-issue for others, but please provide a solution on how to make this `No Data` disappear.

![Screenshot 2021-05-02 at 07 11 20](https://user-images.githubusercontent.com/333960/116803244-acb36400-ab16-11eb-9aea-11ec63cd5558.jpg)

**Comment by PraveenJP** [comment]
Can I try to fix this bug @bakman2? I am new to this project so I like to contribute?

**Comment by rmhowe425** [comment]
@PraveenJP Are you still working this issue or can I grab it?

**Comment by PraveenJP** [comment]
No, please grap it..

**Comment by jupiter566** [comment]
@rmhowe425 may I ask if you made any advancement in solving this functional grey area ?

**Comment by rmhowe425** [comment]
@jupiter566 No I have not, if you want to work on this go for it!
