### ISSUE TITLE
Using interval variables in min step causes "Unexpected error"

### ISSUE THREAD

**Issue by weeco** [grafana/grafana#33592]
**What happened**: I created a normal Graph chart, used bars as display method (but that's not necessary for reproducing) and I wanted to find an appropriate value for minStep that scales with my time range so that the width of my bars remains decent - regardless of the selected time range. Therefore I wanted to use the `$__interval` variable and divide that by some number. That immediately caused an error in the frontend:

![image](https://user-images.githubusercontent.com/23424570/116746054-489c7d00-a9fc-11eb-81b5-d7b850d29acd.png)

![image](https://user-images.githubusercontent.com/23424570/116746212-6bc72c80-a9fc-11eb-86eb-eea2f1b99fed.png)

**What you expected to happen**:

I expected that `$__interval` equals to my currently selected time range for the dashboard (e.g. 6h). If I divide that by 6 I expect a min step of 1h. The variable is also suggested to be used in the tooltip next to the `minStep` field.

**How to reproduce it (as minimally and precisely as possible)**:

Rebuild a graph query and try to use the interval variable in the minStep

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.5.4
- Data source type & version: Prometheus/Cortex
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: Instana
- Others:

**Comment by zoltanbedi** [comment]
Hi @weeco Prometheus does not support math in the step field.

**Comment by weeco** [comment]
@zoltanbedi Ok got you, how about showing such a hint / validating the input before sending it to Prometheus then. I think the error handling is not very user friendly in that specific case.

**Comment by zoltanbedi** [comment]
Validate input for arithmetic and return with proper error or document properly that we don't support arithmetic in Prometheus or add some info to the tooltip.

**Comment by zoltanbedi** [comment]
I'm going to close this issue. We are going to add support for variables in step field and we have issues already open for arithmetic #14011 and #5125
