### ISSUE TITLE
Error on "go run build.go build package"

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#3363]
I'm following Grafana [instructions](http://docs.grafana.org/project/building_from_source/) in order to build it from source.

But, when I get to the part of creating optimized release packages, after installing FPM (v.1.4.0), I keep getting the same error:

    $ fpm
    /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require': no such file to load -- ffi (LoadError)
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/util.rb:3
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package.rb:2
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm.rb:3
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `gem_original_require'
    from /usr/lib/ruby/site_ruby/1.8/rubygems/custom_require.rb:31:in `require'
    from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/bin/fpm:5
    from /usr/bin/fpm:19:in `load'
    from /usr/bin/fpm:19

Any idea on what it may be? I'm on a RedHat EL6 64 bit machine.

**Comment by torkelo** [comment]
either update your ruby version or install backports, which is required I think for FPM to work when using ruby 1.8

FPM depends on the 'backports' gem, which you don't seem to have installed: 

https://github.com/jordansissel/fpm/blob/master/fpm.gemspec#L27 

https://github.com/marcandre/backports 

It looks like you're running Ruby 1.8.5; according to the Backports README, it's 'compatible with Ruby 1.8.6, 1.8.7, 1.9.1, 1.9.2, 1.9.3, JRuby and Rubinius.'

**Comment by antjori** [comment]
Appreciate the help @torkelo !

I'll check my versions and act in accordance. 

Thank you!

**Comment by antjori** [comment]
So, I've checked my versions and I think they meet the requirements:

    [root@test grafana]# ruby -v
    ruby 1.8.7 (2013-06-27 patchlevel 374) [x86_64-linux]

    [root@test grafana]# gem list
    
    *** LOCAL GEMS ***
    
    arr-pm (0.0.10)
    backports (3.6.7)
    cabin (0.7.2)
    childprocess (0.5.8)
    clamp (0.6.5)
    ffi (1.9.10 java)
    fpm (1.4.0)
    json (1.8.3)
    rubygems-update (2.5.0)

@torkelo , any other idea?

**Comment by antjori** [comment]
Hey,

I manage to solve this problem by installing RVM and reinstalling both Ruby and FPM.

Probably was in fact a versions' problem.

Thanks for all your help.
