### ISSUE TITLE
Series combination based on elasticsearch datasource

### ISSUE THREAD

**Issue by 1tft** [grafana/grafana#3364]
Hello,

tried to summarize seriesA and seriesB based on elasticsearch datasources. 
So I chose mixed datasource and added a graphite seriesC where I tried the sumSeries function:
 ![sumseries](https://cloud.githubusercontent.com/assets/8899007/11451849/1b702d32-95d4-11e5-8b28-08d4cd1c5bc6.png)

This is not working. There is no seriesC in the chart.
Is there any other way to summarize two elasticsearch series?

**Comment by torkelo** [comment]
not elasticsearch does not support this. sumSeries is a graphite function
