### ISSUE TITLE
Docker build errors with 'build constraints exclude all Go files in /go/src/github.com/grafana/grafana'

### ISSUE THREAD

**Issue by robotastronaut** [grafana/grafana#33652]
**What happened**:

Trying to build a docker image locally using either of the Dockerfiles would fail with the following error:

```
package github.com/grafana/grafana/pkg/cmd/grafana-server
        imports github.com/grafana/grafana/pkg/server
        imports github.com/grafana/grafana/pkg/api
        imports github.com/grafana/grafana/pkg/services/schemaloader
        imports github.com/grafana/grafana: build constraints exclude all Go files in /go/src/github.com/grafana/grafana
exit status 1
```

Running `go run build.go build` would properly compile the binaries.

**What you expected to happen**:

I expected running `make build-docker-full` to properly build a docker image.

**How to reproduce it (as minimally and precisely as possible)**:

Check out any commit after [748778f](https://github.com/grafana/grafana/commit/748778fff063568971d9235c117974193a559d32) and run `make build-docker-full`

**Anything else we need to know?**:

This was introduced by the `schemaloader` service package importing `grafana/grafana`, found in the top-level `embed.go`. This file and associated directories (`cue/` and `public/app/plugins`) are not currently being copied to the go builderbefore running `go run build.go build`.

**Comment by aknuds1** [comment]
Dup of #33636.
