### ISSUE TITLE
ElasticSearch-IndexMissingException[[.kibpmnpm] missing]

### ISSUE THREAD

**Issue by safiresh** [grafana/grafana#3365]
HiTeam, 

I am new user for Grafana and i try to add elasticsearch as datasource but i am getting error index missing. kindly look at my screen shot and i traced that issue  grafana  send prerequest for elasticsearch with wrong index name. its change the index name if we give index name "a" means  its automatically char changed "pm" like that. we can't specy correct index name :( 
![screen shot 2015-11-28 at 8 30 37 pm](https://cloud.githubusercontent.com/assets/2355624/11452514/1f588160-9610-11e5-894d-2b7f466aec5a.png)

**Comment by torkelo** [comment]
remove the setting Pattern: Hourly, change this to None
