### ISSUE TITLE
Grafana not sending client_secret in GitHub OAuth flow

### ISSUE THREAD

**Issue by kabachook** [grafana/grafana#33655]
**What happened**:
`login.OAuthLogin(NewTransportWithCode)` when singing in using GitHub

**What you expected to happen**:
Successful login 

**How to reproduce it (as minimally and precisely as possible)**:
 
- Follow the steps in https://grafana.com/docs/grafana/latest/auth/github/
- Try to login using GitHub
- See the error page 

**Anything else we need to know?**:
I intercepted the request to `https://github.com/login/oauth/access_token`, and it seems that it does not conform with the flow written in GItHub docs [link](https://docs.github.com/en/developers/apps/authorizing-oauth-apps#2-users-are-redirected-back-to-your-site-by-github)

The request:
```
POST /login/oauth/access_token HTTP/1.1
Host: github.com
Content-Type: application/x-www-form-urlencoded

client_id=[redacted]&code=[redacted]&grant_type=authorization_code&redirect_uri=https%3A%2F%2Fgrafana.local%2Flogin%2Fgithub
```
So, there is no `client_secret` in the request, and GItHub responses with error: `error=incorrect_client_credentials&error_description=The+client_id+and%2For+client_secret+passed+are+incorrect.&error_uri=https%3A%2F%2Fdocs.github.com%2Fapps%2Fmanaging-oauth-apps%2Ftroubleshooting-oauth-app-access-token-request-errors%2F%23incorrect-client-credentials`

Grafana logs: `lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="oauth2: server response missing access_token"`

**Environment**:
- Grafana version: `v7.5.5 (b5190ee547)`

**Comment by kabachook** [comment]
`oauth2` library does not send `client_secret` [by default](https://github.com/golang/oauth2/blob/master/oauth2.go#L213), however it supports setting additional params.
For example we can pass this to [`connect.Exhange`](https://github.com/grafana/grafana/blob/master/pkg/api/login_oauth.go#L129):
```go
SetAuthURLParam("client_secret", config.ClientSecret)
```

**Comment by kabachook** [comment]
Okay, I looked up `oauth2` sources and it automatically [discovers](https://github.com/golang/oauth2/blob/5e61552d6c78/internal/token.go#L203) auth style, but it does not seem to work...
Probably needs debugging

**Comment by kabachook** [comment]
Omg, I misspelled `GITHUB` in envs, so that `client_secret` is empty🤦‍♂️
![image](https://user-images.githubusercontent.com/9118683/116930078-f8295780-ac67-11eb-8246-d0069b7e2a5a.png)

**Comment by prologic** [comment]
FWIW I did something even more stupid. I passed the "client_id" as the "client_secret" and didn't notice. Basd copy/paste of env vars in the config file I was modifying 😅 (it doesn't help that I'm legally blind and only get to see about 2 lines of text and 20-30 characters at a time 🤣
