### ISSUE TITLE
request failed issue when we are integrating Azure sentinel to Grafana

### ISSUE THREAD

**Issue by bhadvit** [grafana/grafana#33653]
Below is the error:

1) we are trying to integrate Azure sentinel incidents view in Grafana dashboard, when trying to execute query below is the 
    error.

request failed, status: 401 Unauthorized, body: {"error":{"message":"Valid authentication was not provided","code":"AuthorizationRequiredError","correlationId":"357bfd7b-1032-4135-a6c5-a755526038de"}}

2) Please help me How to monitor Azure sentinel incidents in Granfana dashboard.

**Environment**:
- Grafana version: v 7.5.5
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser:  Windows, Chrome
- Grafana plugins: None
- Others:

**Comment by alyssabull** [comment]
Closing as it's out of date. If it's still an issue please reopen.
