### ISSUE TITLE
Grafana Unable to send notification email via Gmail SMTP

### ISSUE THREAD

**Issue by iamejboy** [grafana/grafana#33668]
**What happened**:
Grafana was unable to send notif via gmail smtp

**What you expected to happen**:
Successful sending of notif via gmail smtp

**How to reproduce it (as minimally and precisely as possible)**:
Setup smtp w/ the following:

[smtp]
enabled = true
host = smtp.gmail.com:587
user = User_here
password = """Password_here"""
;cert_file =
;key_file =
skip_verify = true
from_address = Email_here
from_name = Grafana Alert
;ehlo_identity =
;startTLS_policy =

Note:
- Google Mail 2FA enabled and password was generated
- Tested Gmail smtp creds with ssmtp and works fine

Grafana logs throws generic log
`t=2021-05-04T01:14:12+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid= error="Failed to send notification to email addresses: my-test-email@gmail.com: 535 5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials ge4sm941467pjb.49 - gsmtp"`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.5.5
- OS Grafana is installed on: Ubuntu 18
- User OS & Browser: Any

**Comment by marefr** [comment]
Works for me using this configuration with 2FA enabled so I'll close this.

```
[smtp]
enabled = true
host = smtp.gmail.com:587
user = <email>@gmail.com
password = <2FA password>
cert_file =
key_file =
skip_verify = false
from_address = <email>@gmail.com
from_name = Grafana
ehlo_identity =
```

If it still doesn't work you'll need to provide more information highlighting that this is a Grafana problem and not for example a network/firewall problem.
