### ISSUE TITLE
CSP blocks plugin details images

### ISSUE THREAD

**Issue by robbierolin** [grafana/grafana#33662]
**What happened**:
Enabling CSP through the .ini prevent images in plugin details pages from loading. Screenshot attached for the Timestream plugin but the same issue occurs on many plugins. Chrome show the error `Refused to load the image '<URL>' because it violates the following Content Security Policy directive: "img-src 'self' data:".`

**What you expected to happen**:
Enabling CSP would not degrade plugin details pages.

**How to reproduce it (as minimally and precisely as possible)**:
Set `content_security_policy = true`

**Anything else we need to know?**:
This also prevents users from loading images (e.g. logos) through a text panel with a <img> tag. Is this the intention of the default CSP?

**Environment**:
- Grafana version: AMG on Grafana v7.5.2
- User OS & Browser: Chrome

![Screen Shot 2021-05-03 at 11 49 29 AM](https://user-images.githubusercontent.com/8867000/116919839-bc11da80-ac06-11eb-971b-444a741fd063.png)

**Comment by torkelo** [comment]
csp is still pretty new and we have not yet solved all issues with it (in safari for example), 

You can customize the csp content policy using content_security_policy_template setting 

default: 
https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L246

**Comment by torkelo** [comment]
@marefr what do you think? update the default csp policy (that is disabled by default) to allow external images?

**Comment by aknuds1** [comment]
@torkelo I think it might be OK to relax the default CSP template wrt. `img-src`. Should we change the default to `*`, which allows any image source?

**Comment by marefr** [comment]
> update the default csp policy (that is disabled by default) to allow external images?

I guess that should work. Otherwise, could we proxy the image request through the grafanacom proxy in the backend or just proxy them through the backend?

**Comment by aknuds1** [comment]
I'll make a PR to change the default to allow all image sources.
