### ISSUE TITLE
Log Panel: Both Ascending & Descending order auto scrolling towards top

### ISSUE THREAD

**Issue by abhisheknegi** [grafana/grafana#33661]
**What would you like to be added**:

On selecting 'Ascending' order for log panel, scroll pointer should be at the bottom which will show new log lines on panel (mimicking live view).

**Why is this needed**:

On log panel user needs to scroll down on every refresh to see new data lines even if order or data is ascending. Default scrolling seems to be top which is ok for descending but it should be bottom for ascending.

![image](https://user-images.githubusercontent.com/13733548/116917399-769fde00-ac03-11eb-859d-51ae5cee2ae5.png)

**Comment by jareware** [comment]
@zoltanbedi would you be able to comment as to the validity of the approach detailed in #36629? Would such a PR be accepted?

**Comment by ivanahuckova** [comment]
Hello @jareware! I am wondering, if you think that this should be a new setting of if we should automatically scroll to bottom when the order is Ascending? Is there a use case when this wouldn't be useful for Ascending order and would be useful for Descending?

**Comment by jareware** [comment]
@ivanahuckova hmm, good point, it could just be the default for when the sort order is Ascending! Suppose I was just trying to make sure it'd be opt-in, so if someone _was_ relying on the current behaviour (for whatever strange reason), this change wouldn't break their dashboards/processes. 😇

**Comment by ivanahuckova** [comment]
I think that we could just implement it base on Ascending/Descending order and always scroll to the newest log lines. I was thinking about the use case where this wouldn't be wanted, but couldn't find one. And we can always, in the future, just add this as separate setting, if there is a use case for that. It is easier to add setting than to remove setting. 🙂

So @jareware if you would be up for this, I can assign this issue to you. It would be awesome! 🚀 🙏
