### ISSUE TITLE
API does not use key or deleteKey when external is true

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/grafana#33665]
**What happened**:
When creating a snapshot using the API and setting the "key", "deleteKey" and "external": true, the response generated returns with randomised strings rather than the specified key and deleteKey as per the API doc: https://grafana.com/docs/grafana/latest/http_api/snapshot/

This is similar to issue #16742, however I don't think all the code was added in that fix, explanation below. 

If I used the following command: 
curl \
  -H "Authorization: MY_TOKEN \
  -H "Content-Type: application/json" \
  -d '{ "dashboard": { "editable":false, "hideControls":true, "nav":[ { "enable":false, "type":"timepicker" } ], "rows": [ { } ], "style":"dark", "tags":[], "templating":{ "list":[ ] }, "time":{ }, "timezone":"browser", "title":"Home", "version":5 }, "expires": 86400, "name": "Generated Daily Snapshot", "external": true, "deleteKey": "dailySnapshotDelete", "key": "dailySnapshot" }' \
  http://grafana-home-0.home.local:3000/api/snapshots

(Note that "external": true, is set)
The output:
{"deleteKey":"gWIMNqzKFcHrcaL0kq3xt5H7UyoRs7rq","deleteUrl":"http://grafana-home-0.home.local:3000/api/snapshots-delete/gWIMNqzKFcHrcaL0kq3xt5H7UyoRs7rq","id":32,"key":"5c0cSuQuPNEo8K8txNiS1jqjc86Tj2Cy","url":"http://grafana-home-1.home.local:3000/dashboard/snapshot/5c0cSuQuPNEo8K8txNiS1jqjc86Tj2Cy"}

The "key" and "deleteKey" is not honored, and instead random generated strings are returned. 

**What you expected to happen**:

When setting "external": true, then "key" and "deleteKey" should be honoured and the returned URL's should use these. 

**How to reproduce it (as minimally and precisely as possible)**:

As per the curl above, you need to set: 
"external":true,
"key": "my-key",
"deleteKey": "my-delete-key"

**Anything else we need to know?**:
I think I found the issue. In this file: 
https://github.com/grafana/grafana/blob/master/pkg/api/dashboard_snapshot.go

On line 86 it checks for the external flag, which is true, and will then execute createExternalDashboardSnapshot on line 92. 
If you jump to this function on line 41, then you'll see that the function does not extract the "key" and "deleteKey" fields, only name, expires and dashboard (line 43-47). This is where the values are ignored and missing code should be added to use the key and deleteKey fields as well. The API doc indicates that these fields can be set as optional, and it seems like these optional fields are ignored in this function. 

**Environment**:
- Grafana version: 7.5.5 OSS
- Data source type & version: NA
- OS Grafana is installed on: Centos 7.9
- User OS & Browser: Chrome 89
- Grafana plugins: NA
- Others:

**Comment by marefr** [comment]
Fixed by #33686
