### ISSUE TITLE
FR: Finding fields in elasticsearch for templating filtering by name

### ISSUE THREAD

**Issue by rjromay** [grafana/grafana#3366]
I tried to find (and filter) fields in elasticsearch as I would do using graphite metric names.

My fields in elasticsearch look like: event.dta.1_1_1, event.dta.1_1_2, event.dta.2_11_3, etc. For graphite I would use event.dta.\* to get all those values for templating.

It would also be nice if they could be fitered by type at the same time (which is AFAIK only way of filtering elasticsearch fields as of today). Something like:

{"find": "field", "regex": "event.dta.*", "type":"number"}

Another way to solve the issue: if {"find": "terms"} was able to find all the "leaf" fields (currently is not able to find nested parameters, only single types on root), I could use Regex text field to filter them. Maybe this second way is more correct.

**Comment by 1tft** [comment]
Good morning @rjromay,
you should not use dots in field names any longer: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_mapping_changes.html#_field_names_may_not_contain_dots
Elastic 2.0 doesn't support this.

**Comment by rjromay** [comment]
Thx @1tft but my fields don't contain dots, they are nested:
"event": {
          "properties": {
            "dta": { 
                   "properties": {
                        "dta": {  "type":"string"}
                    }
           }
 }
             
Probably my issue was not clear enough.

**Comment by 1tft** [comment]
Thank you for this clarification. I also noticed that grafana (v.2.5) ist not able to find nested fields.
So you can't use a structure like it is described here: http://metrics20.org/
Maybe in future it is also possible to work in grafana with "metrics 2.0" but you have to consider that Elastic as datasource is a very new feature in grafana.

**Comment by rjromay** [comment]
I was not aware of metrics 2.0, which seem nice by the way. It simply that I'm ingesting json objects with logstash in elasticsearch, inheriting the hierarchy.

I tagged issue subject as a Feature Request instead of Bug because I do realize it's a new functionality and, having a look to the code, following nested object definition is simply not implemented.

**Comment by torkelo** [comment]
closing this for lack of demand and also we have a regex filter (done client side)
