### ISSUE TITLE
InfluxDB: flow query graph problem

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#33675]
(this issue has been split out from https://github.com/grafana/grafana/issues/28078 so that we do not mix separate potentially separate issues together). the issue is reported by @pheetr 

i reproduce some of the discussion from that issue here:

written by @pheetr:
"
 I have one _value column per query, but I have multiple of these queries to display in a Graph. As there are no other descriptive column names in an individual query result, Grafana calls the results "Value" for all the queries in the graph. As they have the exact same name, I can't use overrides or transform rename functionality to give these different names, which is the reason why I tried renaming the _value column in the queries themselves, but then when I do that the results don't get visualized, even though the values show up in the legend or the hover tooltip (screenshot).
I'm on v7.5.4.

Thx.

![](https://user-images.githubusercontent.com/44616229/116685324-0d715e00-a9aa-11eb-96b6-2a925ce8d91c.png)
![](https://user-images.githubusercontent.com/44616229/116687358-ed8f6980-a9ac-11eb-875f-0bd05bf5e0a8.png)
"

**Comment by gabor** [comment]
by @pheetr: the query:
```
from(bucket: "test")
|> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "win_process")
  |> filter(fn: (r) => r["_field"] == "Private_Bytes")
  |> filter(fn: (r) => r["instance"] =~ /firefox.*/)
  |> group() // resets group key putting all tables in one group
  |> aggregateWindow(every: 30s, fn: sum)
  |> drop(columns: ["host"])
  |> rename(columns: {_value: "FF"})```

**Comment by gabor** [comment]
@pheetr i'm not sure yet if i completely understand your problem, for now i will tell you how to fix the query just posted 😸 , we can continue from there then.

(also, note, flux-query-handling is still in beta, this will change in later versions of grafana)

- when you are configuring your dashboard-panel, and try to figure out why things are not shown like they should, try to switch the visualization to `Table` temporarily. it will show you all the data that is received by the browser, so should help with troubleshooting
- in general, if the data contains one time-ish column and one number-ish column, the graph-visualization will figure it out, but in your case, you have 3 time-ish columns (`_start`, `_end`, `_time`) so things get confused
- to fix this, we will "remove" the `_start` and `_end` columns
- add a Transformation, choose OrganizeFields, and hide `_start` and `_end`
- now if you switch to the graph visualization, you should see the graph

this should fix your problem with not seeing the graph. does fix your whole problem too? if not, just write back with additional info.

**Comment by pheetr** [comment]
@gabor, thanks. It's curious that Grafana would get confused by the presence of _start and _stop, given that afaik Flux pretty much adds these columns in every query as they represent the range() function arguments, out of which I believe at least "start" is mandatory to have in any query.
You were right though, removing these resolves the issue, though I tested it by removing them in the flux query itself, by adding them to the drop() function I already had in there. This is the approach I'll run with for now.
Maybe it would be safe to have Grafana ignore these two columns for the purpose of graph-visualization by default? 

Interestingly, I had identified another workaround shortly before you shared your suggestion that didn't require removing the two columns.
By adding a new static value column where every value is the name I wanted the series to have ("FF" in the example), Grafana ended up displaying the series correctly and with the "FF" name, without the need to remove _start and _stop or to rename the _value column.

Query:
```
from(bucket: "test")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "win_process")
  |> filter(fn: (r) => r["_field"] == "Private_Bytes")
  |> filter(fn: (r) => r["instance"] =~ /firefox.*/)
  |> group() // resets group key putting all tables in one group
  |> aggregateWindow(every: 30s, fn: sum)
  |> drop(columns: ["host"])
  |> set(key: "instance", value: "FF")
```
This, I believe raises the question why Grafana seems to get confused by _start and _stop when we rename the _value column, but it's not confused by them when we don't use rename() and instead introduce a new static column.

Please let me know if you need additional details, whether it's the use case or something else.
