### ISSUE TITLE
🚨 Potential Server-Side Request Forgery (SSRF) (CWE-918)

### ISSUE THREAD

**Issue by huntr-helper** [grafana/grafana#33683]
👋 Hello, @torkelo, @bergquist, @marefr - a potential high severity Server-Side Request Forgery (SSRF) (CWE-918) vulnerability in your repository has been disclosed to us.

#### Next Steps

1️⃣  Visit **https://huntr.dev/bounties/1-other-grafana/grafana** for more advisory information.

2️⃣  **[Sign-up](https://huntr.dev/)** to validate or speak to the researcher for more assistance.

3️⃣ Propose a patch or outsource it to our community - whoever fixes it gets paid.

✏️ **NOTE**: If we don't hear from you in *14 days*, we will proactively source a fix for this vulnerability (and open a PR) to ensure community safety.

---

#### Confused or need more help?

- Join us on our **[Discord](https://huntr.dev/discord)** and a member of our team will be happy to help! 🤗

- Speak to a member of our team: @JamieSlome

---

*This issue was automatically generated by [huntr.dev](https://huntr.dev) - a bug bounty board for securing open source code.*

**Comment by adam-nygate** [comment]
Hi! 👋

Adam here from https://huntr.dev. I can see that this has already been addressed in #26623, so apologies for the alarm. I've invalidated this vulnerability on our side.

Please let me know if I'm mistaken - thanks! 😊
