### ISSUE TITLE
Add ability to hide "Forward OAuth Identity" option in the data source config

### ISSUE THREAD

**Issue by kminehart** [grafana/grafana#33698]
**What would you like to be added**:

I think a setting in plugin.json needs to be added, like "allow-forward-oauth-identity" to enable the "forward OAuth Identity" option in the datasource settings.

**Why is this needed**:

The Grafana Enterprise Plugins teams are getting a lot of support requests about this feature "not working" when really it's just not implemented and should be hidden.

Thanks! :)

**Comment by marefr** [comment]
@kminehart I think the solution is rather to 
- add a new prop for hiding the Forward OAuth Identity option in
https://github.com/grafana/grafana/blob/a40aef0822c27fa9d145e8410f3b7979feb8446b/packages/grafana-ui/src/components/DataSourceSettings/types.ts#L10 
- add a new scoped variable for hiding the Forward OAuth Identity option in https://github.com/grafana/grafana/blob/a40aef0822c27fa9d145e8410f3b7979feb8446b/public/app/features/datasources/settings/HttpSettingsCtrl.ts#L6-L8

And hide the Forward OAuth Identity option in UI if above setting is true. WDYT?

**Comment by kminehart** [comment]
That makes sense to me!

**Comment by marefr** [comment]
@wbrowne something to prioritize soon?
