### ISSUE TITLE
Elasticsearch: Date histogram for alerts should default to datasource

### ISSUE THREAD

**Issue by simianhacker** [grafana/grafana#33701]
**What happened**:

On the front end when you create a new visualization, the date histogram field is blank but the data still returns. This is because when the `date_histogram` is being built it falls back to the default from the datasource; it just works. But if the user never sets the value and creates an alert, the alert will never trigger because the backend code doesn't fallback to the datasource time field for the date_histogram.

**What you expected to happen**:

The alert code should fallback to the datasource time field for the `date_histogram`

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new visualization (the default count will do)
2. Go to the Alert tab
3. Add a threshold value that should trigger
4. Click the test button.

You will see that even though the chart is showing data, the values are all zeros.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Master
- Data source type & version: Any
- OS Grafana is installed on: Source
- User OS & Browser: Any
- Grafana plugins: None
- Others:

**Comment by zoltanbedi** [comment]
This might be fixed by the backend migration.

**Comment by ivanahuckova** [comment]
I wasn't able to reproduce this anymore. When I have interval set to 'auto', the alerting query works as expected. 
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/30407135/181288257-9c3accbc-d5e4-417d-aad3-80b9f595cfa4.png">

I am going to close this issue, but feel free to reopen if you are still experiencing this.
