### ISSUE TITLE
AzureMonitor: Refresh Documentation

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#33713]
- Update screenshot with new UI
 - Logs:
   - Update to reference the new resource picker
 - App Insights / Insights Analytics:
   - Remove query documentation (can go back to prev version of docs to view)
   - Include migration instructions for App Insights -> Metrics, Insights Analytics -> Logs 
 - [Template variables issue](https://github.com/grafana/grafana/issues/33834)

**Comment by kostrse** [comment]
Provisioning template also needs to be updated:
https://grafana.com/docs/grafana/latest/datasources/azuremonitor/#configure-the-data-source-with-provisioning

**Comment by joshhunt** [comment]
See also #29783
