### ISSUE TITLE
Prometheus row template values are incorrectly escaped (twice)

### ISSUE THREAD

**Issue by NotAFile** [grafana/grafana#33712]
**What happened**:
When defining a repeating row, the values are escaped twice. For example, if `$instance` is defined as a dashboard variable and `$interface` is defined as a row variable and the following query is used:

```
my_metric{instance="$instance", interface="$interface"}
```

In the query inspector, I can see that the resulting query is (url-decoded):

```
my_metric{instance="my.domain.example.com", interface="fe\\.1\\.1"}
```

**What you expected to happen**:

The `interface` variable is not escaped, giving the expected result:

```
my_metric{instance="my.domain.example.com", interface="fe.1.1"}
```

**How to reproduce it (as minimally and precisely as possible)**:

1. define a single value custom variable `dashboard` as `a.a,a.b,a.c`
2. define a multi-value custom variable `row` as `a.a,a.b,a.c`
3. set up a row to repeat for `row`.
4. add a Prometheus query of the form: `a{b="$dashboard", c="$row"}`
5. observe double backslashes in query inspector

**Anything else we need to know?**:

I speculate what is happening here is that Grafana is not correctly handling the fact that repeating rows turn a multi-value variable into a single value variable. In that case, it would try to apply the regex formatting and escaping used for multi-values which matches what we're seeing.

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: Prometheus 2.
- OS Grafana is installed on: Debian
- User OS & Browser: Fedora 34, Firefox 88
- Grafana plugins: n/a
- Others:

**Comment by ivanahuckova** [comment]
This is `work-as-intended` behavior. You can learn more in #16275 (comment) and #6888.
