### ISSUE TITLE
 Value groups/tags (Experimental feature) selections not working as expected.

### ISSUE THREAD

**Issue by anthonydba** [grafana/grafana#33725]
Note: based on sample dashboard https://play.grafana-zabbix.org/d/000000071/templating-guide-advanced

group/tags will be referred to as just groups.

**What happened**:  The selection of Groups and Values does not work as expected.

Issue 1, Group selection,  then removing one group clears out all selected values. 

![Group Selection Issue](https://user-images.githubusercontent.com/48160339/117084266-a16d5d80-acfb-11eb-9e5f-a22686a95b61.gif)

Issue 2, Selecting Groups then Values, does not reflect in the group selection.
![Group Value Selection](https://user-images.githubusercontent.com/48160339/117084500-383a1a00-acfc-11eb-974b-0ff949a482cb.gif)

Issue 3, Selection box does not work as expected. When selecting 1 value.
![Value Selection Issue](https://user-images.githubusercontent.com/48160339/117084586-6c153f80-acfc-11eb-988b-2b7bb1621756.gif)

**What you expected to happen**:
Issue 1, Values of the other selected group to still be selected.
Issue 2, When values are selected or deselected after group selection, what is expected that it would reflect in the groups.
Issue 3, If only one value selected I expect the "Selected (1)" have blue dash - 

**How to reproduce it (as minimally and precisely as possible)**:
Please see attached gifs.

**Anything else we need to know?**:

**Environment**: https://play.grafana-zabbix.org/d/000000071/templating-guide-advanced

**Comment by torkelo** [comment]
This experimental feature is deprecated and will be removed in v8, so any issues will not be fixed

**Comment by asr21** [comment]
@torkelo any idea on what the alternative for this feature is

**Comment by anthonydba** [comment]
@asr21 @torkelo 
Well this is quite disappointing to say the least.    We use this on many of our dashboards in a similar setup to the following dashboard.   Could please let us know the alternative. 

https://play.grafana-zabbix.org/d/000000071/templating-guide-advanced

**Comment by torkelo** [comment]
You should be able to accomplish the same thing with two linked variables, one for the groups and then use that in the main variable query

**Comment by anthonydba** [comment]
@torkelo 
I am having issue with linking the two variables.  
The way we get the Groups/tags is from one table, that has the proper tags associated to the values.   
Then we have multiple tables with the associated values but not the tags. 
I'm not sure we can use this work around. 

Why is this feature being deprecated?  From our stand point its a very useful feature.

**Comment by torkelo** [comment]
not sure why you can't? can you show your queries?

**Comment by anthonydba** [comment]
Variable Name: Landscape
Original Variable, with Value groups/tags (Experimental feature) enabled
Query:
SHOW TAG VALUES from system_data WITH KEY = "name"

Tags Queary:
SHOW TAG VALUES from system_data WITH KEY = "type"

Tag Values Query:
SHOW TAG VALUES from system_data WITH KEY = "name" WHERE type=~ /$tag/


select "lastValue" from (SELECT  last("status_value") as "lastValue"  FROM "job_status" WHERE "landscape" =~ /^$Landscape$/ ) WHERE $timeFilter AND (lastValue = 2 or lastValue = 3) GROUP BY landscape

Selecting the specific value is no problem, but I am not clear how to link another variable and table since the tags are not in the job_status table.  We only get those values from system_data.

**Comment by torkelo** [comment]
but that looks like you can spit into two variables easily. 

Query variable named "type":
SHOW TAG VALUES from system_data WITH KEY = "type"

Query variable; Landscape
SHOW TAG VALUES from system_data WITH KEY = "name" WHERE type=~ /$type/

**Comment by anthonydba** [comment]
Hi @torkelo I got it working, but I have to mention this is even more cumbersome than using the "
Value groups/tags" feature.  Is there someway to get this feature put back in?

**Comment by torkelo** [comment]
In what way is it more cumbersome? Less concepts, just the normal chaining of variables that most are already used to
