### ISSUE TITLE
API requests authorization brocken when auth proxy enabled

### ISSUE THREAD

**Issue by shoonoise** [grafana/grafana#3372]
Hi, I expected that grafana must ignore auth proxy header when API calls processing, because grafana already has ability to check API KEYs (which add by org's admins). 
So I want to use embedded auth mechanism when API calls (disable `/api/` path in my auth proxy).

Overall, I guess that API Key should be checked for any API call, even if the request from an authorized user.

**Comment by torkelo** [comment]
api key is checked for first, so it should work even when auth proxy is enabled

**Comment by shoonoise** [comment]
> api key is checked for first, so it should work even when auth proxy is enabled

If auth proxy enabled and `X-WEBAUTH-USER` header is present - doesn't matter if there is no api key in header. The request will be authorized.
For example, I can put any *username* in  `X-WEBAUTH-USER` header and perform api requests from the *username*.

**Comment by torkelo** [comment]
yes, but if you issue an HTTP request with an Authorization header with a Valid API Key, the API key  should take precedence and be used over the auth header. Maybe the Authorization header is filtered out by your auth proxy?

**Comment by shoonoise** [comment]
> Maybe the Authorization header is filtered out by your auth proxy?

No, I've exclude `/api/` path from auth proxy handling. And the problem is that I still can authorize by `X-WEBAUTH-USER` header, but should not (as API Key not present).

**Comment by torkelo** [comment]
you cannot exclude paths from auth proxy handling in Grafana. If auth proxy is enabled Grafana will look for the auth proxy header for all requests, this is required as the frontend uses the API.

**Comment by woodsaj** [comment]
@shoonoise the `/api/*` routes are used by the frontend. Blocking these routes in your authProxy will prevent your users from being able to use Grafana.

When using AuthProxy, you should never expose Grafana directly to the network. Only the server(s) handling authentication and proxying requests should be able to authenticate users.

If you want your users to be able to use their Grafana API_Keys instead of authenticating using your AuthProxy, then you will need to create a second Proxy that does not do any auth, but strips out any "X-WEBAUTH_USER` headers.  

eg in apache, you could just create a second VHOST.

```
<VirtualHost *:80>
    ServerAdmin webmaster@authproxy
    ServerName api-key-only
    ErrorLog "logs/api-key-only-error_log"
    CustomLog "logs/api-key-only-access_log" common

    RequestHeader unset X-WEBAUTH-USER

    ProxyRequests Off
    ProxyPass / http://localhost:3000/
    ProxyPassReverse / http://localhost:3000/
</VirtualHost>
```

**Comment by shoonoise** [comment]
>  the /api/* routes are used by the frontend.

That's what I missed. Now I see.

> If you want your users to be able to use their Grafana API_Keys instead of authenticating using your AuthProxy, then you will need to create a second Proxy that does not do any auth, but strips out any "X-WEBAUTH_USER` headers.

Thanks for advise! That was my plan B.
