### ISSUE TITLE
Generic Oauth role_attribute_strict don't seems to work

### ISSUE THREAD

**Issue by xenofree** [grafana/grafana#33735]
Hi,

**What happened**: When no roles is applied, user is authorized as Viewer

**What you expected to happen**: User should be unauthorized

**How to reproduce it (as minimally and precisely as possible)**:

[auth.generic_oauth]
enabled = true
role_attribute_path = contains(realm_access.roles[*], 'grafana_admin') && 'Admin' || contains(realm_access.roles[*], 'grafana_editor') && 'Editor' || contains(realm_access.roles[*], 'grafana_viewer') && 'Viewer'
role_attribute_strict = true

lvl=eror msg="Failed to extract role" logger=oauth.generic_oauth error="failed to search user info JSON response with provided path: \"contains(realm_access.roles[*], 'grafana_admin')
&& 'Admin' || contains(realm_access.roles[*], 'grafana_editor') && 'Editor' || contains(realm_access.roles[*], 'grafana_viewer') && 'Viewer'\": Invalid type for: <nil>, expected: []jmespath.jpType{\"array\", \"string\"}"

I tried with 
role_attribute_path = contains(realm_access.roles[*], 'grafana_admin') && 'Admin' || contains(realm_access.roles[*], 'grafana_editor') && 'Editor' || contains(realm_access.roles[*], 'grafana_viewer') && 'Viewer' || 'Denied'
but i'm mapped as Viewer too

t=2021-05-05T10:05:37+0200 lvl=dbug msg="OAuthLogin got user info" logger=oauth userInfo="&{Id: Name:*** Email:*** Login:*** Company: Role:Denied Groups:[]}"
t=2021-05-05T10:05:37+0200 lvl=dbug msg="Building external user info from OAuth user info" logger=oauth
t=2021-05-05T10:05:37+0200 lvl=dbug msg="Syncing Grafana user with corresponding OAuth profile" logger=oauth
t=2021-05-05T10:05:37+0200 lvl=info msg="Successful Login" logger=http.server User=***

**Environment**:
- Grafana version: 7.5.5
- OS Grafana is installed on: Docker
- User OS & Browser: Windows, Chrome

**Comment by PavelGloba** [comment]
Same issue.

Turns out it only appears in the docs for some reason. The actual feature is planned only for 8.0.0 https://github.com/grafana/grafana/pull/28021#issuecomment-735380101

**Comment by marefr** [comment]
We've updated the latest (7.5) documentation to not include this feature, https://grafana.com/docs/grafana/latest/auth/generic-oauth/
