### ISSUE TITLE
Problem with character encoding when exporting image using /render/dashboard-solo

### ISSUE THREAD

**Issue by ZhukovAlexey** [grafana/grafana#3373]
Hello. I have the Grafana 2.1.3 version running on Ubuntu and use /render/dashboard-solo API to export .png images.

![good_albo_live](https://cloud.githubusercontent.com/assets/1679467/11476620/d3ef5f42-9794-11e5-84cc-5b99233f5c33.png)

Then I did a migration to the new server on Red Hat and the latest Grafana 2.5 version. But all the text on picture can't be readable. There's a problem with character encoding.

![bad_factor_live](https://cloud.githubusercontent.com/assets/1679467/11476619/d3eea890-9794-11e5-9755-f3c0165fb662.png)

Could you please tell me what kind of font setting is used and where I can fix it.

Thanks in advance.

**Comment by torkelo** [comment]
try installing font packages  . 

For example try
```
yum install fontconfig
yum install freetype*
```

**Comment by ZhukovAlexey** [comment]
torkelo, thanks fot the reply, but:

1. Package fontconfig-2.10.95-7.el7.x86_64 already installed and latest version
2. Package freetype-2.4.11-10.el7_1.1.x86_64 already installed and latest version

Also installed:
* freetype-devel-2.4.11-10.el7_1.1.x86_64.rpm
* freetype-demos-2.4.11-10.el7_1.1.x86_64.rpm 

Still have the same issue.

**Comment by torkelo** [comment]
what version of redhat / centos?

**Comment by torkelo** [comment]
Not sure what could be wront, try updating phantomjs under /usr/local/grafana/vendor/phantomjs,  or follow some phantomjs install guide

**Comment by ZhukovAlexey** [comment]
[uisadm@vuis ~]$ cat /etc/redhat-release
Red Hat Enterprise Linux Server release 7.1 (Maipo) 

[uisadm@vuis ~]$ /usr/share/grafana/vendor/phantomjs/phantomjs --version
1.9.8

I'll try to update it to the new version this week and write you about results. Thanks.

**Comment by ZhukovAlexey** [comment]
I've upgraded up to 2.0.0 version (and also tried the previous 1.9.7).

 [uisadm@vuisn ~]$ /usr/share/grafana/vendor/phantomjs/phantomjs --version
2.0.0

And there's no text at all.

![factor_live_phantom_js_2 0 0](https://cloud.githubusercontent.com/assets/1679467/11526450/a3b8e82c-98eb-11e5-88cf-62b1dc034ead.png)

I got how the render process works.

It seems that if on the /dashboard-solo page there's no problem with encoding in browser that the problem with image lies on how PhantomJS saves webpage to .png.

And I should dig for PhantomJS on RedHat issues.

If I find anything I'll tell you.

Thanks.

**Comment by ZhukovAlexey** [comment]
My bad. Having nothing in "fc-list". Installed some fonts and it works!

**Comment by upgradeksh** [comment]
I had the same problem and sorted it out after installing urw-fonts package on CentOS 6

**Comment by Sandwichzhao** [comment]
hello, I similar problem , when I export data.
![image](https://user-images.githubusercontent.com/13583249/49426653-21660500-f7dc-11e8-8036-c65935345db4.png)
I have many kind of font where  in "fc-list". Grafana is 5.4.1pre1. Could you help me, thanks

**Comment by Sandwichzhao** [comment]
![image](https://user-images.githubusercontent.com/13583249/49426787-8ae61380-f7dc-11e8-9cfb-1048e44005c6.png)
