### ISSUE TITLE
Security issue - OS Command Injection in ejs

### ISSUE THREAD

**Issue by jongyllen** [grafana/grafana#33747]
# OS Command Injection in grafana/grafana (master)

## Issue Details

- **Vulnerability**: OS Command Injection
- **Severity**: High
- **Project**: grafana/grafana
- **Branch**: master

## Issue Description
ejs is vulnerable to OS command injection. An attacker is able to inject and execute arbitrary OS commands via the `render` and `renderFile` functions if external input is passed into the `options` parameter.

This issue was fixed in version 3.1.6 of ejs. That version is currently considered safe, we suggest that you upgrade to the fixed version.

**Comment by dprokop** [comment]
![image](https://user-images.githubusercontent.com/2376619/117302622-20899f80-ae7c-11eb-9710-7255eb8ad810.png)

`ejs` is a dev dependency of webpack-bundle-analyzer, meaning it's not bundled with Grafana. It's not creating runtime vulnerability.

**Comment by jongyllen** [comment]
Thank you for investigateing
