### ISSUE TITLE
Timeseries chart goes blank with error if there are no data

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [grafana/grafana#33745]
**What happened**:
A query that does not return data brakes the "timeseries" chart with this rendering ![timeseries](https://user-images.githubusercontent.com/34926125/117144161-e784f880-adb1-11eb-9809-9c53daf21d87.png)

**What you expected to happen**:
An empty chart with "no data" written in the middle
**How to reproduce it (as minimally and precisely as possible)**:
Create a timeseries chart and fed it with a query that does not return data
**Anything else we need to know?**:
I'm using influxdb v2 as datasource
**Environment**:
- Grafana version: v7.5.5 (b5190ee547)
- Data source type & version: InfluxDB v2
- OS Grafana is installed on: ubuntu 20.04 desktop
- User OS & Browser: Windows 10, Chrome (latest)
- Grafana plugins: N/A
- Others: N/A

**Comment by dprokop** [comment]
This one should be fixed in v8-beta1
