### ISSUE TITLE
Security issue - Prototype Pollution in grafana/grafana handlebars

### ISSUE THREAD

**Issue by jongyllen** [grafana/grafana#33748]
# Prototype Pollution in grafana/grafana (master)

## Issue Details

- **Vulnerability**: Prototype Pollution
- **Severity**: High
- **Project**: grafana/grafana
- **Branch**: master

## Issue Description
handlebars is vulnerable to prototype pollution. An attacker is able to inject arbitrary properties into prototype constructs when selecting certain compiling options to compile templates which can lead to arbitrary code execution.

This issue was fixed in version 4.7.7 of handlebars. That version is currently considered safe, we suggest that you upgrade to the fixed version.

**Comment by dprokop** [comment]
![image](https://user-images.githubusercontent.com/2376619/117302825-5a5aa600-ae7c-11eb-8604-65cdfe0c01be.png)

`handlebars` is a dev dependency of lerna, meaning it's not bundled with Grafana. It's not creating runtime vulnerability.

**Comment by jongyllen** [comment]
Thank you for investigateing
