### ISSUE TITLE
Log Browser label selection box too small

### ISSUE THREAD

**Issue by olds463** [grafana/grafana#33749]
**What would you like to be added**:
Dynamically resize log browser label selector element. If your label name is long, in this case we are importing from AWS cloudwatch, so the names are a bit long. This is for step 2 in the log browser.

**Why is this needed**:
Makes browsing labels hard. UI should allow resizing the label box, or dynamically resize to available space based on the number of labels selected in step 1.

**Comment by zoltanbedi** [comment]
Can you show us a screenshot please? Also which version of Grafana are you seeing this?

**Comment by olds463** [comment]
![Screenshot from 2021-05-05 10-53-54](https://user-images.githubusercontent.com/18619567/117162258-9e707c80-ad90-11eb-84fb-6000182a8bd4.png)

Seeing this in 7.5.4 & 7.5.5. While the horizontal nav bar appears, I feel it would be better presented to have dynamic width based on number of label selectors chosen.
