### ISSUE TITLE
Security issue - Prototype Pollution in merge

### ISSUE THREAD

**Issue by jongyllen** [grafana/grafana#33746]
# Prototype Pollution in grafana/grafana (master)

## Issue Details

- **Vulnerability**: Prototype Pollution
- **Severity**: High
- **Project**: grafana/grafana
- **Branch**: master

## Issue Description
merge is vulnerable to prototype pollution. The function `_recursiveMerge` allows for an injection of arbitrary properties into existing construct prototypes and modification of attributes such as `__proto__`, `constructor` and `prototype`.

This issue was fixed in version 2.1.1 of merge. That version is currently considered safe, we suggest that you upgrade to the fixed version.

**Comment by dprokop** [comment]
![image](https://user-images.githubusercontent.com/2376619/117302440-eae4b680-ae7b-11eb-8f91-500e5f026138.png)

`merge` is a dev dependency fo sass-linter, meaning it's not bundled with Grafana. Longer term we are getting rid of all SASS styles so this will not be part of our deps tree.

**Comment by jongyllen** [comment]
Thanks for investigating this
