### ISSUE TITLE
Old CLA site page is blank

### ISSUE THREAD

**Issue by hartfordfive** [grafana/grafana#3376]
The old CLA page, http://grafana.org/docs/contributing/cla.html, is just a blank page.  A 301 redirect should be done to the proper location http://docs.grafana.org/project/cla/.  When searching for "grafana cla" on Google, this appears to be the first result.

**Comment by utkarshcmu** [comment]
#3377

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana.org/commit/3649b2cfb0b634cb112b3b99afa6944ccf8b1314
