### ISSUE TITLE
Make it possible to validate dashboard JSON with datasource queries

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#33761]
The current panel JSON does not include enough information to know validate if the query options are OK.  We currently save the name of the datasource, not its id or type:
```
{
    "type": "my-panel-type",
    "datasource": "-- Mixed --",
    "targets": [
      {
        "datasource": "name 1",
        "refId": "A",
        "query": "SELECT * FROM ..."
      },
      {
        "datasource": "name 2",
        "refId": "B",
        "query": "http_requests_total{}"
      }
    ]
  }
  ```

To support validation and not silently breaking dashboards after renaming a datasource, we should replace the datasource identifier with an object.  Perhaps:

```
{
    "type": "my-panel-type",
    "datasource": { "type":"-- Mixed ---" },
    "targets": [
      {
        "datasource": { "type":"loki", "uid": "123" },
         ...
      },
      {
        "datasource": { "type":"mysql", "uid": "456" },
        ...
      }
    ]
  }
```

BONUS:  In addition to the identifiers, query objects have the added complexity that they attach properties to the same level as their parent object.  This makes it difficult to reliably validate and has conflicts when we define new 'global' properties -- Like "queryType".  A better solution would be to move the type dependent properties to its own object.  IE:

```
{
    "type": "my-panel-type",
    "datasource": { "type":"-- Mixed ---" },
    "targets": [
      {
        "datasource": { "type":"loki", "uid": "123" },
         "options": {
              "query": "..."
          }
      },
      {
        "datasource": { "type":"mysql", "uid": "456" },
         "options": {
              "query": "SELECT ..."
          }
      }
    ]
  }
```

The id/type migration seems reasonably self contained -- moving options is much harder :)

**Comment by sdboyer** [comment]
This is now feasible, thanks to #33817
