### ISSUE TITLE
editors_can_invite configuration

### ISSUE THREAD

**Issue by pbaumard** [grafana/grafana#33771]
**What would you like to be added**:

[editors_can_admin](https://grafana.com/docs/grafana/latest/administration/configuration/#editors_can_admin) configuration allows editors to administrate dashboards, folders and teams they create.

We would like an additional editors_can_invite setting to allow editors to invite users as Viewer or Editor (not as Admin).

The design would be similar to the existing org/users/invite, except that the Admin role is removed:

![image](https://user-images.githubusercontent.com/6176006/117280565-055e6600-ae63-11eb-8c80-a8dec2946908.png)

**Why is this needed**:

I can see no other way to enable editors to invite users for now.

**Comment by sakjur** [comment]
Hello @pbaumard,

Thank you for the feature request.

We're working on introducing a system to address this need in Grafana Enterprise as part of our scope for Grafana 8.
We don't want to control access through the configuration file, we've needed a cohesive system built in to Grafana that can allow a user to customize Grafana similar to this to avoid an inflation of unmaintainable options.

We'll share more information about that system during [GrafanaCon](https://grafana.com/about/events/grafanacon/2021/), but long story short this is a level of control we're working on extending to all Grafana components for Grafana Enterprise users, not just to inviting users.
