### ISSUE TITLE
Grafana is using "refresh" JSON field instead "refresh_on_load" on templating

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3378]
Hi, playing with Grafana I realize that by default when a templating param is created, it generates the "refresh_on_load" field:
`  "templating": {
    "list": [
      {
        "type": "query",
        "datasource": null,
        "refresh_on_load": false,
        "name": "test",
        "options": [ ... ]`

But when you enable or disbale that "Refresh on Load" feature, by the first time, the field "refresh" is created and its that field that is changed instead of "refresh_on_load":
  `"templating": {
    "list": [
      {
        "type": "query",
        "datasource": null,
        "refresh_on_load": false,
        "name": "test",
        "options": [
         ...
        ],
         ...
        },
        "regex": "",
        "refresh": true
      },`

Tested on: http://play.grafana.org/dashboard/db/issue-3275

Thanks for all

**Comment by torkelo** [comment]
thanks for info, :heart:  fixed!
