### ISSUE TITLE
Grafana dont include image in notification

### ISSUE THREAD

**Issue by shdubna** [grafana/grafana#33790]
**What happened**:
Grafana dont send image in alert notification. Include image options is enabled in notification channel. Grafana running in kubernetes and use remote image renderer running in same pod. Grafana configured to use image renderer by environment variables GF_RENDERING_SERVER_URL=http://127.0.0.1:8081/render and GF_RENDERING_CALLBACK_URL=http://127.0.0.1:3000/.

When I try to render image manually (by clicking share in panel menu) evrything work fine. But in notification I received only "No image renderer available/installed".

I try to enable debug mode for rendering log in grafana. I found logs with render request if try to create image manualy (from share), but there is not logs with rendering request when alert execution.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.0.6
- Data source type & version:
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
You're using quite an old version of Grafana, please try a newer version such as 7.5.5. We haven't had similar reports so closing this for now. Let me know if you still experience problems on newer version and I'll consider reopen this. Thanks
