### ISSUE TITLE
App dashboard links are dead

### ISSUE THREAD

**Issue by JorundMartinsen** [grafana/grafana#33808]
**What happened**: 
Cloned grafana-starter-app and modified plugin.json. Added `"addToNav": true` on a dashboard.
Built and added app to Grafana v7.5.5
Open sidebar link and click dashboard link
Redirected to `http://localhost:3000/dashboard/db/lots-of-stats`

**What you expected to happen**:
Redirected to `http://localhost:3000/d/YeBxHjzWz/starter-app-stats`

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:
Probably related to `pkg/api/index.go:113`

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: -
- OS Grafana is installed on: Win10
- User OS & Browser: Win10 Chrome
- Grafana plugins: -
- Others:

**Comment by marefr** [comment]
Fixed by #36899

**Comment by andreasgerstmayr** [comment]
I can reproduce this issue on the latest main branch, with the same steps as outlined above.

Clone grafana-starter-app, add `"addToNav": true` to a dashboard, `yarn install && yarn build`, and run `podman run -v $(pwd):/var/lib/grafana/plugins/grafana-starter-app:z -p 3001:3000 -e GF_DEFAULT_APP_MODE=development docker.io/grafana/grafana:main` from the grafana-starter-app directory.

The link to the dashboard in the navigation bar is broken. Can you please re-open this issue?
