### ISSUE TITLE
PromQL Query Editor: scrolling through queries with mouse is not usable

### ISSUE THREAD

**Issue by hawran** [grafana/grafana#33815]
**What happened**:
1. Open a PromQL Query Editor (data from prometheus) with more than one query.
2. Try to scroll up / down through queries with the mouse over the editor panel.
3. Queries are just "shaking" without any significant movement.

**What you expected to happen**:
Queries moving up / down according to the mouse.

**How to reproduce it (as minimally and precisely as possible)**:
See **What happened** above.
 
**Anything else we need to know?**:
Regarding the issues I've been experiencing with the editor so far I would really beg for a possibility to switch off all those editor's "[smart functionalities](https://github.com/grafana/grafana/issues/30997)"... 

**Environment**:
- Grafana version: Grafana v7.5.5
- Data source type & version: prometheus v2.26.0
- OS Grafana is installed on: Linux / Ubuntu 20.04.2 LTS
- User OS & Browser: Firefox 88.0 (64-bit)
- Grafana plugins: ...
- Others:

**Comment by hawran** [comment]
UPDATE: The same problem with `firefox --safe-mode`.

**Comment by hawran** [comment]
https://user-images.githubusercontent.com/25924718/118649688-13f23900-b7e4-11eb-9d61-b7209cf28c56.mp4

I've created 3 (empty) "queries", at 11 sec tried to scroll down, then used the scroll bar, at 20 sec tried to scroll up, then via the scroll bar.
I hope it'll help somehow.

**Comment by ifrost** [comment]
> I've created 3 (empty) "queries", at 11 sec tried to scroll down, then used the scroll bar, at 20 sec tried to scroll up, then via the scroll bar.
> I hope it'll help somehow.

Thanks a lot @hawran. It should be fixed by https://github.com/grafana/grafana/pull/34263
