### ISSUE TITLE
define default datasource with config file is not working

### ISSUE THREAD

**Issue by duthifree** [grafana/grafana#33814]
**What happened**:
define default datasource with config file is not working

**What you expected to happen**:
i want to be able to define default datasource with config file

**How to reproduce it (as minimally and precisely as possible)**:

```bash
/usr/share/grafana $ cat /etc/grafana/provisioning/datasources/datasource_thanos.yaml 
datasources:
- name: "Thanos"
  type: "prometheus"
  access: proxy
  orgId: 1
  url: "..."
  isDefault: true
  editable: true
  ```

**Anything else we need to know?**:
it works with UI (Admin user)

**Environment**:
- Grafana version: 7.5.5

**Comment by marefr** [comment]
Please make sure to include `apiVersion: 1` top of the yaml file as explained in docs here https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file.
