### ISSUE TITLE
Feature request : Add operations between queries for Opentsdb

### ISSUE THREAD

**Issue by Othyus** [grafana/grafana#3381]
Hi, 
I'm looking for make addition/subtraction operations between metrics, I view this feature : 
https://github.com/grafana/grafana/issues/177
but it's only for Graphite. 
Is it possible to make the same for opentsdb please?
Thank you in advance

**Comment by torkelo** [comment]
since that is a graphite feature, you should open a feature request with OpenTSDB project asking for more rich query features :)

**Comment by pbustosl** [comment]
@torkelo Have you thought about querying the DataSource for the series and do the math on Grafana? (btw, I'm using KairosDB)
