### ISSUE TITLE
Documentation: High Availability

### ISSUE THREAD

**Issue by datamuc** [grafana/grafana#33822]
https://github.com/grafana/grafana/blob/main/docs/sources/administration/set-up-for-high-availability.md#stateless-sessions mentions and links to a [sessions] section in the configuration file, but there is no such section in https://github.com/grafana/grafana/blob/main/docs/sources/administration/configuration.md documented.

**Comment by achatterjee-grafana** [comment]
Thank you @danieldspx for your contribution via PR https://github.com/grafana/grafana/pull/33827.

**Comment by marefr** [comment]
@achatterjee-grafana sorry didn't have time to review the PR until now. The changes suggested in the PR is not really correct in regards to user sessions/remote cache. 

```md
Grafana uses auth token strategy with database by default. This means that a load balancer can send a user to any Grafana server without having to log in on each server. If you want to offload the login session data from the database, then you can configure [remote_cache]({{< relref "../administration/configuration.md" >}}#remote-cache).
```

Either the full User sessions paragraph/section should be removed or the last part "If you want to offload the login session data from the database, then you can configure remote_cache." should be removed.

**Comment by achatterjee-grafana** [comment]
@marefr, thank you for the review. I have removed the line "f you want to offload the login session data from the database, then you can configure remote_cache." via PR https://github.com/grafana/grafana/pull/33870.
