### ISSUE TITLE
Transformations: Add a flip transformation (rows to fields)

### ISSUE THREAD

**Issue by Totalus** [grafana/grafana#33824]
### What would you like to be added

A transformation that would "flip" the data: the row values of a specified column would become the fields and the original fields would become the values of a new column.

Say we got the following data.

| City | Population (thousands) | Temperature |
|--|--|--
| London | 9304 | 16°C
| New York | 8462 | 19°C
| Montreal | 2070 | 25°C

Flipping the table by the *City* field would result in the following.

| Fields  | London  | New York  | Montreal 
|---|---|---|---
| Population (thousands) | 9304 | 8462 | 2070
| Temperature | 16°C | 19°C | 25°C

### Why is this needed

Multiple visualizations (Pie chart, Bar gauge, ...) use field names (or series names if multiple series) as label for the data. I am often able to get the first table from my data, but I haven't figure out a way to display the result in one of those visualizations. This transformation would allow to make the data compatible with those views.

I can probably work on a PR for this, but would like comments before. Is there already a way to do that I'm not aware of ?

**Comment by ryantxu** [comment]
The biggest issue with this approach is what type the field becomes -- in the case above do they all become string fields?

For table view -- we should absolutely do this at the visualization level, others also.

**Comment by Totalus** [comment]
> The biggest issue with this approach is what type the field becomes -- in the case above do they all become string fields?

Oh good point. Yeah I guess they would have to become string fields, which then becomes an issue for visualization as it uses numbers. The use case I thought about actually had only two columns (i.e. City and Population), but still, the field type consideration makes this approach much less appealing.

> For table view -- we should absolutely do this at the visualization level, others also.

Yes, I also thought about this possibility. I made a new issue (#33825) about it.
