### ISSUE TITLE
"If no data or all values are null" add "do_nothing" option

### ISSUE THREAD

**Issue by jgournet** [grafana/grafana#33828]
**What would you like to be added**:
As the title says ;)

**Why is this needed**:
None of the current options actually do what I need:
- if I set "If no data or all values are null" to "OK": if the state is currently erroring and grafana/prometheus fails to get the data, we will receive an OK message (which is wrong, as the real state is currently erroring).
- if I set "If no data or all values are null" to "keep_last_state": 
1) some series never have any state for that alert, so we receive  a "no data" alert whenever we restart grafana (3h after restarting it, which is our reminder time)
2) also: "null" values are an OK state for us, so we miss recovery events.

What I'd like grafana to do is: nothing ! 
ie: don't fire an OK state, or fire a no_data: just do nothing.

Thanks a lot for that

**Comment by JohnnyQQQQ** [comment]
We are working on this as it's related to https://github.com/grafana/grafana/issues/40392 and https://github.com/grafana/grafana/pull/43583
