### ISSUE TITLE
How to update Grafana properly from 2.1.3 to 2.5

### ISSUE THREAD

**Issue by willemdh** [grafana/grafana#3382]
I tried updating my Grafana server from 2.1.3 to 2.5 with this command:

    sudo yum install https://grafanarel.s3.amazonaws.com/builds/grafana-2.5.0-1.x86_64.rpm

After the installation the only thing I see in the webGUI is this:

{{alert.title}}

Please advise how to upgrade my Grafana server without breaking it. Thanks!

**Comment by willemdh** [comment]
Ok, the solution was to follow the docs... Closing..

```
  261  sudo yum install https://grafanarel.s3.amazonaws.com/builds/grafana-2.5.0-1.x86_64.rpm
  262  sudo service grafana-server start
  263  sudo /sbin/chkconfig --add grafana-server
  264  systemctl daemon-reload
  265  systemctl start grafana-server
  266  systemctl status grafana-server
```

**Comment by torkelo** [comment]
the first issue is due to you not restarting grafana-server after downloading the new version. 

The second issue about dashboards not loading sounds strange. There has been no reported upgrade issues between 2.1.3 and 2.5

**Comment by willemdh** [comment]
Hey, I manage to fix it by re-entering the InfluxDB backend info.

**Comment by LANRRI** [comment]
hi  , i want to upgrade grafana from 2.0.2 to 3.1.1 , should i backup the grafana.db, and just install new package?

**Comment by torkelo** [comment]
Yes, you can update with any issues.  You can read changelog for info on
minor changes that could effect but otherwise dashboards are 100% backward
compatible

**Comment by LANRRI** [comment]
now i have two versions of grafana , 2.0.2 running on port 3000 ,  3.1.1 running on port 3001, how can i migrate the old dashboads to 3.1.1 ?

**Comment by torkelo** [comment]
copy the database is the easiest way.

**Comment by LANRRI** [comment]
thanks, i have successfully upgrade to 3.1.1~~
