### ISSUE TITLE
Allow url to override the override in fullscreen view

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3383]
Our dashboard has a panel for historic context pinned to "Last 4 months". The rest of the dashboard tends to focus on the last 6 hours instead.

It would be nice to be able to link to one of those panels with a different `from` value, but I'm not sure it's possible.

E.g. a link like https://grafana.wikimedia.org/dashboard/db/navigation-timing?panelId=15&fullscreen&from=now-8M shows the last 4 months (from the override), not the last 8 months. Is there a way to do this?

**Comment by mtanda** [comment]
Now, from can be controlled by template variable.
https://github.com/grafana/grafana/pull/4063

**Comment by mtanda** [comment]
@torkelo I think this is possible with time range templating.

**Comment by Krinkle** [comment]
It currently doesn't work (updated last week), but maybe the below is what you are after? That would be okay for my use case. Ideally the `from` parameter would just work, but template vars can be set by url as well so that's fine.

<img width="922" alt="screen shot 2016-03-03 at 15 56 56" src="https://cloud.githubusercontent.com/assets/156867/13500021/9569204c-e158-11e5-8882-09ab3414eb8b.png">

**Comment by mtanda** [comment]
Sorry, the PR is merged in this week.
It might be not usable in last week build.
You can set template variable in URL like "?var-history=3m".

**Comment by torkelo** [comment]
closing in favor of https://github.com/grafana/grafana/issues/5872 (same issue)
