### ISSUE TITLE
Button to skip to previous timeframe of same size

### ISSUE THREAD

**Issue by BitProcessor** [grafana/grafana#33838]
When inspecting metrics, a 7d view of metrics can sometimes "filter out" some spikes that would have been seen in a 1d view. Currently, there is no easy way in Grafana to quickly skip between subsequent timeframes of 1d (unless I'm missing something?).

A button to quickly skip forward/backward would therefore be a nice addition. 
I included some screenshots of the way Datadog handles this: a simple << and >> button which takes the initial setting (past 1d in the example) and allows for quickly skipping backward (and forward again).

![Screenshot 2021-05-10 at 11 30 30](https://user-images.githubusercontent.com/50638541/117638664-5e8c0980-b183-11eb-9ed4-60c56c6cd8ad.png)
![Screenshot 2021-05-10 at 11 30 36](https://user-images.githubusercontent.com/50638541/117638661-5e8c0980-b183-11eb-9bc8-ca0af2c645ba.png)
![Screenshot 2021-05-10 at 11 30 42](https://user-images.githubusercontent.com/50638541/117638658-5d5adc80-b183-11eb-8893-cf6ce8571133.png)

**Comment by marefr** [comment]
You have to click on the zoom out icon to enable this, see https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file.

**Comment by BitProcessor** [comment]
@marefr 🤦🏻 
Thanks a lot - how could I miss that 👍🏻
