### ISSUE TITLE
Unit Testing  for Grafana Changes

### ISSUE THREAD

**Issue by shanky05** [grafana/grafana#3386]
@torkelo I have made some changes in Grafana Graph visualizations. I need to add unit test cases for the same. I see that there is command called "grunt test" which will run all the unit tests.

Could you please point me to some documentation on how to write test cases, what framework we are using for the same etc etc. I am unable to find any documentation on unit testing the Angular JS part of grafana.

**Comment by torkelo** [comment]
you can look at existing tests here, https://github.com/grafana/grafana/tree/master/public/test

**Comment by shanky05** [comment]
Hello @torkelo Please dont close it. I have gone though them. I am not able to see the results. These are lots of js errors so i dont whether it is executing my test case or not. If yes then  if that is successful or not. 

I commented all the files in test-main under specs folder expect one where i have made the changes. But i am not able to find whether that is running or not...
 Please guide me little so that i can procee, as i am stuck right now with this error.

**Comment by torkelo** [comment]
just add a new file named _specs or add a new test case to an existing _specs file. To only execute your new test you can add `.only` after the `describe` or `it` methods, like `it.only(...` you should not modify test-main

**Comment by torkelo** [comment]
to verify that you test executes, add a fail case or console.log

**Comment by shanky05** [comment]
I tried what ever you asked me to do. But now also when i run "grunt test" only JS warnings are running. Like this

Expected indentation of 2 characters at public/app/panels/embkeynote/dashboardHome.js :
    38 | $(document).ready(function() {
What ever console i added that is not at all coming. I tried adding console in the existing test case files as well. Not luck...

**Comment by torkelo** [comment]
you need to fix your jshint / jscs style errors , that check is done before unit tests are executed

**Comment by shanky05** [comment]
thanx @torkelo  for your guidance. I am able to run my test cases now. 

I have one more question, do we have any Unit Test cases for the backend code( go code).??

**Comment by torkelo** [comment]
@shanky05 yes, search for files ending with _test.go
