### ISSUE TITLE
Security Enhancement : having only 1 session per user

### ISSUE THREAD

**Issue by arnaudlemaignen** [grafana/grafana#33864]
Grafana is not preventing a particular user from logging in multiple times simultaneously. Permitting a user to login multiple times may create concurrency faults, created when a particular set of data is updated simultaneously or at least almost synchronously by separate requests from alternative sessions. This could generate inconsistencies or exceptions, depending upon the nature of the data being modified and give cause to user confusion. In addition, failure to prevent concurrent logins may allow an attacker who gained access to a users credentials to go unnoticed.

**What would you like to be added**:
a new ENV variable like
global_session_by_user
with a default value = -1 (in order not to disturb grafana user community)

if global_session_by_user = 1 then only 1 session by user account is permitted

**Why is this needed**:
The possible use of the same login account on more than one session simultaneously in grafana is considered as a vulnerability for security penetrating software (like Rootshell Security)

**Comment by marefr** [comment]
This is currently an Enterprise feature, see https://grafana.com/docs/grafana/latest/enterprise/license/license-restrictions/#concurrent-sessions-limit.
