### ISSUE TITLE
Live: Disconnect banner shown on login page

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#33860]
**What happened**:
Logout from Grafana and saw the disconnected banner. 
![image](https://user-images.githubusercontent.com/1668778/117682112-0967ec00-b1b3-11eb-8279-6660eb932d3f.png)
 
**What you expected to happen**:
To not see the disconnected banner. 

**How to reproduce it (as minimally and precisely as possible)**:
Visit the login page unauthenticated.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main (1b36656455ee3c79cb5f219479197ac508eddbb8)
- User OS & Browser: Chrome and Firefox

**Comment by ryantxu** [comment]
interesting!  ya we should remove that -- note it is only shown in dev mode
