### ISSUE TITLE
Tag values query for Elasticsearch not working?!

### ISSUE THREAD

**Issue by 1tft** [grafana/grafana#3387]
Hello,

I tried to use the cool Multi select feature (http://docs.grafana.org/reference/templating/#multi-select) for graphs based on Elasticsearch as datasource.
I could not find any working "Tag values query", so that I can select a tag (e.g. "backend") and grafana automatically selects particular template variable values (e.g. server3, server4 ...).

![tags_query_elastic](https://cloud.githubusercontent.com/assets/8899007/11525329/7b7625fa-98d2-11e5-9bb7-9b087598f4f4.png)

Anybody knows a valid tag values query for elastic?

**Comment by novegit** [comment]
this works for me in the "Tag values query" field: 
{"find":"terms", "field": "@hostname", "query": "$tag"}

**Comment by anhlqn** [comment]
Could someone give an example of Value groups/tags for Elasticsearch backend? Are the tag values retrieved from a field in ES?

**Comment by ctkien** [comment]
![image](https://cloud.githubusercontent.com/assets/8022447/22783053/9d7e39b8-eefc-11e6-9359-258902684a0f.png)
Here is my config. It worked.

**Comment by 1tft** [comment]
Issue can be closed, query from comment "novegit commented on 5 May 2016 " and query from screenshot by @ctkien is working. Thx

**Comment by LeThuyVN** [comment]
hello, working with elasticsearch Data source how to make make report auto like: {"find": "$v1", "field": "$v2", "query": "$v3: $v4"}
