### ISSUE TITLE
TextPanel: After creating a new text panel and going back to dashboard it is blank

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#33888]
- Create a new dashboard
- Add panel
- Change to text panel
- Hit back button 

Blank panel

**Comment by torkelo** [comment]
Also unable to update content, the content does not update after coming back to dashboard (old content remains)

**Comment by sslupsky** [comment]
More specifically, if you erase the content (for instance, to create a blank panel), the old content remains.  However, if you change the content to something other than null, it changes.

**Comment by torkelo** [comment]
This one is fixed in v8 stable
