### ISSUE TITLE
Option to enable withCredentials without requiring basicAuth

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#3388]
Grafana past version support it.
https://github.com/grafana/grafana/issues/1204

But, Grafana seems to not support this, now.

https://github.com/grafana/grafana/blob/24324939e14af64dc4d7eb51308d7ec197c85a01/pkg/models/datasource.go#L33-L44
datasource model doesn't have withCredentials.

I want to use it in Prometheus datasource.

**Comment by torkelo** [comment]
what purpose does withCredentials have when basic auth is not used?

**Comment by mtanda** [comment]
I don't use basic auth.
I use oauth2_proxy (with nginx), to auth Prometheus host access.
https://github.com/bitly/oauth2_proxy

By using oauth2_proxy, I can restrict the member who can access (by Google OpenID Connect).
(I don't want to share basic auth password, because it is uncontrollable who can access...)

There are several Prometheus host and one Grafana host.
The request from Grafana to Prometheus is cross origin, 
Without "withCredentials", auth cookie doesn't sent to oauth2_proxy, the request failed.

**Comment by mtanda** [comment]
PR is merged.
