### ISSUE TITLE
Add getContextSrv to allow react apps to access context

### ISSUE THREAD

**Issue by JorundMartinsen** [grafana/grafana#33897]
**What would you like to be added**:
getContextSrv in @grafana/runtime
**Why is this needed**:
This would allow app creators to filter on user access level. 
Ex: 
- Additional information for admins. 
- Limited page access for Viewers
- Refresh intervals for pages conform to allowed interval.

**Comment by tolzhabayev** [comment]
We are not planning to expose the whole context at the moment, we will explore exposing some functionality of it as needed.
