### ISSUE TITLE
Timeseries: Unit not displayed correctly

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#33895]
When a new unit is specified in the FieldConfig, it's not displayed in the Y-axis of the panel. If I manually trigger a re-render on the panel, for example clicking on the legend, the new unit is picked up. Seems like we have the same problem with the old graph panel. 

![timeseriespanelunit](https://user-images.githubusercontent.com/2388950/117773160-488c5080-b238-11eb-812a-687a3715d7a0.gif)

**Comment by torkelo** [comment]
@sunker can you test this again, think this might be fixed in main/v8 stable

**Comment by sunker** [comment]
Yes, verified that it's working as expected in 8.0.x.
