### ISSUE TITLE
Failed metric query warning does not disappaer again

### ISSUE THREAD

**Issue by bangert** [grafana/grafana#3389]
Hi,

grafana is awesome. Thanks for sharing it!

Concerning the elasticsearch datasource I noticed today, that there is a
 nice little warning, when there is an error with the current query. 

![snapshot2](https://cloud.githubusercontent.com/assets/73190/11526570/9c73caa6-98db-11e5-9066-9fe9be94bb36.png)

However, the icon does not disappear again, when everything is ok again. A reload of the current page, will make the icon dissappear.

Thanks

**Comment by torkelo** [comment]
I can't replicate this, are you sure you are using elasticsearch datasource?

**Comment by bangert** [comment]
Hi Torkel,

yes - i am on the elasticsearch datasouce.
if you remove the groupby statement before fixing it, the notice will stay indefinitly.
The following is what i should have added in the original report.

 - click '+' to add another groupby statement.
 - click 'select field' without filling anthing in
 - the notice will correctly appear
 - click '-' to remove the groupby statement
 - the notice is still there, even though there is no error.

I am on 2.5 btw, and have not tried the prereleases.
Thanks.

**Comment by torkelo** [comment]
seems to be fixed in master, cannot replicate
