### ISSUE TITLE
Ghost queries in editor

### ISSUE THREAD

**Issue by volter** [grafana/grafana#3390]
* Create a new graph -- "-- Grafana --" is set as the data source
* Click "+ Query" 3 times -- Nothing happens
* Change the data source to Elasticsearch (other sources may show the same effect)
* Find 4 query sections in the form, instead of the expected single one

**Comment by utkarshcmu** [comment]
Able to reproduce....... its a bug.. :(

**Comment by torkelo** [comment]
what do you mean expected single one? you clicked "+ Query" 3 times (and it has by default one), so that equals 4 queries. The Grafana data source is just a test data source so does not show a query editor. But the add query button still works.

**Comment by torkelo** [comment]
I can see that is a strange behavior, but it's not like its a bug that needs fixing as the impact to users should be close to zero :)
