### ISSUE TITLE
Annotation list reference to other dashbaord fails - different root url

### ISSUE THREAD

**Issue by CWollinger** [grafana/grafana#33917]
**What happened**:
Grafana is running behind nginx reverse proxy with different root_url. 
Using an (alpha) annotation list panel.
Click on an annotation in the list which is referencing to another dashboard.
Receive HTTP404 because URL change to /grafana/grafana/

Dashboard link: `https://example.com/grafana/d/oe6eH0CGk/dashboard-1`
![grafana_annotation](https://user-images.githubusercontent.com/11299733/117804632-45a15800-b258-11eb-8ff2-9d75e768a049.PNG)

Dashboard link: `https://example.com/grafana/d/Wl9ZD0CGz/dashboard-1`
![grafana_annotation_list](https://user-images.githubusercontent.com/11299733/117805249-08899580-b259-11eb-9ec8-25756fcfd441.PNG)

If you click on the annotation you will be redirect to `https://example.com/grafana/grafana/d/oe6eH0CGk/dashboard-1` which results in 404.

**What you expected to happen**:
Dashboard opens correctly.  

**How to reproduce it (as minimally and precisely as possible)**:
1. Create annotation in dashboard 1
2. Add (alpha) annotation list panel in dashboard 2
3. Click on the annotation in the annotation list.
4. Link is broken 

**Anything else we need to know?**:
grafana.ini
````
root_url = https://example.com/grafana/

[plugins]
enable_alpha = true
````

nginx.conf
````
location /grafana/ {
    proxy_pass http://grafana:3000/;
}
````

**Environment**:
- Grafana version: v7.5.4
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10 & Firefox 84
- Grafana plugins: (alpha) annotation list panel

**Comment by jackw** [comment]
@CWollinger thanks so much for taking the time to report this bug. Can confirm it's an issue with the alpha annotations panel.
