### ISSUE TITLE
Data source doesn't display HTML changes

### ISSUE THREAD

**Issue by krocher5** [grafana/grafana#3391]
I'm trying to slightly modify the InfluxDB datasource. I'm editing to query.options.html by adding a few random characters to "Switch to editor mode" (eg: "Switch to editor mode ==="), I build everything with grunt and when I start Grafana I can't see the changes.

Additional details:
- I am pointing Grafana to the public_gen directory
- I checked the query.options.html in the public_gen directory and it has the changes
- I tried to add an < h1 >Hello world< / h1 > and I can't see the changes either
- I tried the same with other datasources, I still can't see any change
- I loaded the page with different browsers, having the cache disabled

Did anybody else run into this? Any idea on how I can fix this?

**Comment by torkelo** [comment]
make your changes in the public/ dir then run grunt, or run grunt watch, then make your changes.
