### ISSUE TITLE
Failed to render and upload alert panel imag

### ISSUE THREAD

**Issue by ylmcr7** [grafana/grafana#33926]
this is my grafan-image-render log
![image](https://user-images.githubusercontent.com/63889450/117812154-042e9e00-b294-11eb-91a3-dcb0eba11ed8.png)

this is grafana log
![image](https://user-images.githubusercontent.com/63889450/117811661-676c0080-b293-11eb-890a-6202a88e21a6.png)

this is my email message
![image](https://user-images.githubusercontent.com/63889450/117811730-7d79c100-b293-11eb-9575-e53af5276aba.png)

no image 
 i want this email is 
![image](https://user-images.githubusercontent.com/63889450/117811787-94b8ae80-b293-11eb-80a1-848a0bc1409c.png)

please help me 

this is my docker command
docker run -itd --user 0 -p 3000:3000 --name=grafana -v /etc/localtime:/etc/localtime -v /data/grafana:/var/lib/grafana -v /data/grafana/log:/var/log/grafana -v /data/grafana/etc/grafana.ini:/etc/grafana/grafana.ini --env GF_RENDERING_SERVER_URL=http://121.1**.**.***:8081/render --env GF_RENDERING_CALLBACK_URL=http://121.1**.**.***:3000grafana/ grafana/grafana:7.0.3

docker run -d --name=grafana-image-renderer -p 8081:8081 -v /data/grafana-image-renderer/config.json:/usr/src/app/config.json grafana/grafana-image-renderer:latest

**Comment by marefr** [comment]
Please configure https://grafana.com/docs/grafana/latest/administration/configuration/#notification_timeout_seconds

**Comment by ylmcr7** [comment]
curl http://121.19*.**. **:8081/render
{"statusCode":400,"error":"Bad Request","message":"Missing url parameter"}

this is my grafana log 

![image](https://user-images.githubusercontent.com/63889450/117914892-bf981680-b316-11eb-9860-ab7d232007b4.png)

that 's error

nitifition is not image
![image](https://user-images.githubusercontent.com/63889450/117914949-d76f9a80-b316-11eb-9cc3-7fb71d5d317b.png)

this is my docker command 
docker run -itd --user 0 -p 3000:3000 --name=grafana -v /etc/localtime:/etc/localtime -v /data/grafana:/var/lib/grafana -v /data/grafana/log:/var/log/grafana -v /data/grafana/etc/grafana.ini:/etc/grafana/grafana.ini --env GF_RENDERING_SERVER_URL=http://121.19**.**.**:8081/render --env GF_RENDERING_CALLBACK_URL=http://121.***.***.**5:3000/ grafana/grafana:7.0.3

what's happen i dont konw please help me.

**Comment by ylmcr7** [comment]
this is my 
`;#################################### Alerting ############################
[alerting]
;# Disable alerting engine & UI features
enabled = true
;# Makes it possible to turn off alert rule execution but alerting UI is visible
execute_alerts = true
;
;# Default setting for new alert rules. Defaults to categorize error and timeouts as alerting. (alerting, keep_state)
error_or_timeout = alerting
;
;# Default setting for how Grafana handles nodata or null values in alerting. (alerting, no_data, keep_state, ok)
nodata_or_nullvalues = no_data
;
;# Alert notifications can include images, but rendering many images at the same time can overload the server
;# This limit will protect the server from render overloading and make sure notifications are sent out quickly
concurrent_render_limit = 5
;
;
;# Default setting for alert calculation timeout. Default value is 30
evaluation_timeout_seconds = 30
;
;# Default setting for alert notification timeout. Default value is 30
;;notification_timeout_seconds = 30
;
;# Default setting for max attempts to sending alert notifications. Default value is 3
max_attempts = 3
;
;# Makes it possible to enforce a minimal interval between evaluations, to reduce load on the backend
min_interval_seconds = 1`

**Comment by ylmcr7** [comment]
;#################################### Alerting ############################
[alerting]
;# Disable alerting engine & UI features
enabled = true
;# Makes it possible to turn off alert rule execution but alerting UI is visible
execute_alerts = true
;
;# Default setting for new alert rules. Defaults to categorize error and timeouts as alerting. (alerting, keep_state)
error_or_timeout = alerting
;
;# Default setting for how Grafana handles nodata or null values in alerting. (alerting, no_data, keep_state, ok)
nodata_or_nullvalues = no_data
;
;# Alert notifications can include images, but rendering many images at the same time can overload the server
;# This limit will protect the server from render overloading and make sure notifications are sent out quickly
concurrent_render_limit = 5
;
;
;# Default setting for alert calculation timeout. Default value is 30
evaluation_timeout_seconds = 30
;
;# Default setting for alert notification timeout. Default value is 30
;;notification_timeout_seconds = 30
;
;# Default setting for max attempts to sending alert notifications. Default value is 3
max_attempts = 3
;
;# Makes it possible to enforce a minimal interval between evaluations, to reduce load on the backend
min_interval_seconds = 1

**Comment by marefr** [comment]
`;;notification_timeout_seconds = 30` the `;` means comment. Please try changing to `notification_timeout_seconds = 60`

**Comment by ylmcr7** [comment]
no.

**Comment by marefr** [comment]
Does it work if you browse the panel where the alert is defined, click panel context menu -> share and _Direct link rendered image_ link on the _Link_ tab?  If not, that's where I would start investigating things. 

You seem to use a quite old Grafana version as well and would suggest testing a newer version. For us to help you further would expect using the [bug report issue template ](https://github.com/grafana/grafana/issues/new?assignees=&labels=type%3A+bug&template=1-bug_report.md) with as much detailed as possible or ask for help on the [community site](https://community.grafana.com/).

**Comment by ylmcr7** [comment]
this is grafana:atest. so that's
 EROR[05-12|19:31:32] Remote rendering request failed          logger=rendering renderer=http error="500 Internal Server Error"
EROR[05-12|19:31:32] Rendering failed.                        logger=context userId=1 orgId=1 uname=admin error="remote rendering request failed, status code: 500, status: 500 Internal Server Error"
EROR[05-12|19:31:32] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=GET path=/render/d-solo/jXpuGAjGz/test status=500 remote_addr=36.110.17.10 time_ms=60549 size=1731 referer=


![image](https://user-images.githubusercontent.com/63889450/117968578-eb3bf080-b358-11eb-88ff-c443e4cbd253.png)

**Comment by marefr** [comment]
Then you need to inspect the log of the grafana-image-renderer service/container

**Comment by ylmcr7** [comment]
Internal Server Error
![image](https://user-images.githubusercontent.com/63889450/117971642-bf226e80-b35c-11eb-8038-908521ef40e7.png)

**Comment by ylmcr7** [comment]
since i click  share---> Direct link rendered image


is end is 
![image](https://user-images.githubusercontent.com/63889450/117972030-3526d580-b35d-11eb-917e-bedb23049df3.png)


this is my grafana-image-renderer log

{"url":"/render?deviceScaleFactor=1.000000&domain=121.199.30.165&encoding=&height=500&renderKey=TiFdjziYt5hC091S4bDs3wh6bibLnaGn&timeout=60&timezone=Asia%2FShanghai&url=http%3A%2F%2F121.199.30.165%3A3000%2Fgrafana%2Fd-solo%2FjdipwxCMz%2Ftest-1%3ForgId%3D1%26from%3D1620820622819%26to%3D1620820922819%26panelId%3D2%26width%3D1000%26height%3D500%26tz%3DAsia%252FShanghai%26render%3D1&width=1000","stack":"TimeoutError: Navigation timeout of 60000 ms exceeded\n    at /usr/src/app/node_modules/puppeteer/lib/LifecycleWatcher.js:142:21\n  -- ASYNC --\n    at Frame.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:111:15)\n    at Page.goto (/usr/src/app/node_modules/puppeteer/lib/Page.js:675:49)\n    at Page.<anonymous> (/usr/src/app/node_modules/puppeteer/lib/helper.js:112:23)\n    at Browser.<anonymous> (/usr/src/app/build/browser/browser.js:170:24)\n    at Generator.next (<anonymous>)\n    at fulfilled (/usr/src/app/build/browser/browser.js:5:58)\n    at processTicksAndRejections (internal/process/task_queues.js:97:5)","level":"error","message":"Request failed"}
{"message":"172.17.0.1 - - [12/May/2021:12:03:05 +0000] \"GET /render?deviceScaleFactor=1.000000&domain=121.199.30.165&encoding=&height=500&renderKey=TiFdjziYt5hC091S4bDs3wh6bibLnaGn&timeout=60&timezone=Asia%2FShanghai&url=http%3A%2F%2F121.199.30.165%3A3000%2Fgrafana%2Fd-solo%2FjdipwxCMz%2Ftest-1%3ForgId%3D1%26from%3D1620820622819%26to%3D1620820922819%26panelId%3D2%26width%3D1000%26height%3D500%26tz%3DAsia%252FShanghai%26render%3D1&width=1000 HTTP/1.1\" 500 96 \"-\" \"Grafana/7.5.4\"\n","level":"error"}

**Comment by Sweetie60** [comment]
I am currently facing the same issue. Could you please share how you ultimately resolved it?
