### ISSUE TITLE
Drilldown dashboard link gets changed if dashboard has a special charecter

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#3392]
I have a dashboard, with a drilldown link, the detail dashboard has a `-` in the name
![image](https://cloud.githubusercontent.com/assets/8618235/11530833/f47415ac-991d-11e5-8022-85a1f171b593.png)

Now when I click on the launcher, the browser gets the dashboard name without `-`, leading to dashboard not found error
![image](https://cloud.githubusercontent.com/assets/8618235/11530874/32cd1af6-991e-11e5-97a6-ce7628d677ac.png)

Note that this is an issue if I manually type the dashboard name `transaction-metrics`, If I wait for the small popup, and select an autocomplete entry, the generated link works.

**Comment by utkarshcmu** [comment]
@mvadu Not able to reproduce this error. Included a hyphen in the dashboard name but, drilldown link just works perfectly.

**Comment by utkarshcmu** [comment]
@torkelo Not able to reproduce this bug, even after typing the dashboard name above manually instead of selecting from the dropdown. May be this was a bug in an earlier version but not in master branch.

**Comment by torkelo** [comment]
Seems to be fixed

**Comment by gnewcomb** [comment]
I'm getting this same behavior in  v4.3.2 (commit: ed4d170).

Dashboard with dashes in the name, dashes are removed when used in a drilldown link, and the link doesn't work.

**Comment by suda** [comment]
Confirmed in v4.4.3 (commit: 54c79c5) as well. In the meantime using `absolute` type with full dashboard URL works.

**Comment by bergquist** [comment]
Fixed in 4.5.2 http://play.grafana.org/dashboard/db/dashboard-with-panel-link?orgId=1&panelId=1&fullscreen&edit&tab=general
