### ISSUE TITLE
Cannot read property 'v1' of undefined (theme.v1) in grafana/grafana:master

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#33958]
**What happened**:

I understand it's still a work in progress, but I want to make sure that Redis plugins will support the upcoming version.
Introduced `theme.v1` is breaking custom Table panels.

![Screen Shot 2021-05-11 at 1 32 50 PM](https://user-images.githubusercontent.com/47795110/117860869-c95e4300-b25e-11eb-8823-1908e4f51f06.png)

**What you expected to happen**:

Plugins should works as expected.

**How to reproduce it (as minimally and precisely as possible)**:

Any custom table component should have the same issue.

In my case:

1. Start Redis-app docker based on the master

```
docker run -p 3000:3000 --name=redis-app ghcr.io/redisgrafana/redis-app:master
```

2. Start Redis

```
docker run -p 6379:6379 redis/redis
```

3. Add Redis Data Source and add Redis Latency panel.
 
**Anything else we need to know?**:

**Environment**:
- Grafana version: Docker grafana/grafana:master
- Data source type & version: master
- OS Grafana is installed on: Docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Something for @grafana/grafana-frontend-platform to look into

**Comment by torkelo** [comment]
not sure what is going, I tried running 
> docker run -p 3000:3000 --name=redis-app ghcr.io/redisgrafana/redis-app:master 

and the table panel is working fine. 

The error makes no sense. The display processor using the new theme which has v1

**Comment by torkelo** [comment]
ah, your have a custom panel that is creating it's own display processors, any reason for this? the data passed to the panel should already have display processor set on the fields. 

This line where you call getDisplayProcessor, the theme is not optional, this was a mistake in the typing corrected in v8. In v8 we will require the theme object passed to this   
https://github.com/RedisGrafana/grafana-redis-app/blob/master/src/redis-latency-panel/components/redis-latency-panel-table/redis-latency-panel-table.tsx#L92 

plugins developed for v8 will not work for v7.x

**Comment by mikhailredis** [comment]
@torkelo As I remember, tables are empty without adding display processors. Someone from community had the same errors and was able to see his data in the table after adding display processor.

Can I just add theme and it should work for v7 and v8? What is the right solution?

**Comment by torkelo** [comment]
> Can I just add theme and it should work for v7 and v8? What is the right solution?

Yes, that should work

**Comment by mikhailredis** [comment]
@torkelo thank you, it's working in both v7 and v8.
