### ISSUE TITLE
Error installing custom Grafana from RPM

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#3395]
I've downloaded Grafana, modified some of it's images and generated a RPM package.

Although, when I'm trying to install it, the following error occurs:

```
[root@test grafana]# rpm -ivh ./dist/grafana-2.6.0-pre1.x86_64.rpm
Preparing...                ########################################### [100%]
   1:grafana                ########################################### [100%]
: command not foundNEsj: line 2:
: invalid option.mvNEsj: line 3: set: -
set: usage: set [--abefhkmnptuvxBCHP] [-o option-name] [arg ...]
warning: %post(grafana-2.6.0-pre1.x86_64) scriptlet failed, exit status 2
```

Specs:
```
Red Hat Enterprise Linux Server release 6.4 (Santiago)
Linux test 2.6.32-358.el6.x86_64
```

**Comment by torkelo** [comment]
Can you install the offical packages?

**Comment by antjori** [comment]
I do! That what's bugging me...

**Comment by torkelo** [comment]
ok, then maybe your doing something strange

**Comment by antjori** [comment]
@torkelo you were absolutely right!

The file ./packaging/rpm/control/postinst had its EOL in Windows format.

This occurred because I copied the sources from Windows to my RedHat installation.

Well, it is solved now!

Thanks for all your time and help :smile:
