### ISSUE TITLE
Customize title and logo

### ISSUE THREAD

**Issue by krzd7** [grafana/grafana#33964]
**What would you like to be added**:
Customize the logo and website title via interface.

**Why is this needed**:
I'm aware a lot of people edit this directly via code, but I think that officially supporting this would be nice. It is not about hiding the Grafana brand, because it will still appear at the very bottom of the page. It would allow people to make the dashboard page look a little bit more like as an extension of their sites/products.

**Comment by marefr** [comment]
This is supported in Grafana Enterprise: https://grafana.com/docs/grafana/latest/enterprise/white-labeling/
