### ISSUE TITLE
Sorting Table Panel Does Not Sort Data Links

### ISSUE THREAD

**Issue by Lord-Bacon** [grafana/grafana#33963]
**What happened**:
A user reported that when they clicked on a data link on a table panel that the data passed to the next panel was incorrect. They had sorted the panel using a column header and clicked on the link to view the data for user A, but instead saw the data for user B. The panel is configured to pass the name clicked on to a variable on the same dashboard using the data link.

**What you expected to happen**:
The user should see the data for the name they have clicked on.

**How to reproduce it (as minimally and precisely as possible)**:
Create a table panel with data links.
Change the sort from the default sort using a column header.
Test the data links and they will still all trigger in the order from the original sort.

https://i.imgur.com/ch1Zu2y.gif

**Anything else we need to know?**:

**Environment**:
- Grafana version: OSS 7.5.3
- Data source type & version: MySQL 5.6.4, MSSQL 2014
- OS Grafana is installed on: Amazon Linux 
- User OS & Browser: all
- Grafana plugins: n/a
- Others:

**Comment by torkelo** [comment]
Fixed in 7.5.4
