### ISSUE TITLE
elasticsearch not working

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#3396]
I have added elasticsearch as data source, tested the datasource and returned as success.

Once I attempted to use the data source to create chart, I keep getting this error:

"Cannot read property 'length' of undefined"

This is chrome log showing:

TypeError: Cannot read property 'length' of undefined {stack: "TypeError: Cannot read property 'length' of undefi…apply (http://localhost:3000/app/app.js:13:11839)", message: "Cannot read property 'length' of undefined"}message: "Cannot read property 'length' of undefined"

**Comment by torkelo** [comment]
Can you show the request and response from Elasticsearch? Did you specify the time field correctly?

**Comment by gsaray101** [comment]
![elastic_error](https://cloud.githubusercontent.com/assets/3009225/11538153/96d29880-98ee-11e5-8e40-a9507d1ea7e2.PNG)

**Comment by torkelo** [comment]
what version are you using? no one has reported anything similar with 2.5 or 2.6 but if it is 2.6 maybe a new issue. 

Try removing the query and adding a new query

**Comment by gsaray101** [comment]
I've tried it with different indexes. This is what the _mapping shows about the timestamp:

"timestamp" : {
            "type" : "date",
            "format" : "dateOptionalTime"
          }

**Comment by torkelo** [comment]
and you specifed `timestamp` in the time field in the data source edit view?  (do *not* add a `@` as your time field does not have that).

**Comment by gsaray101** [comment]
I took out @, still the same error.

**Comment by torkelo** [comment]
after you did the timefield change, try removing the query and adding a new blank query. Also try reloading grafana. What version are you using?

**Comment by gsaray101** [comment]
the same issue after removing query, reloading grafana. I am using version 2.5.0

**Comment by gsaray101** [comment]
any ideas?

**Comment by gsaray101** [comment]
Hi Torkel, can you provide a same lucene query for document like this:

{
  "took" : 4,
  "timed_out" : false,
  "_shards" : {
    "total" : 5,
    "successful" : 5,
    "failed" : 0
  },
  "hits" : {
    "total" : 18,
    "max_score" : 1.0,
    "hits" : [ {
      "_index" : "web_app",
      "_type" : "data",
      "_id" : "11111",
      "_score" : 1.0,
      "_source":{"oerrs":"0","load_avg_1min":"0.00","thresholdValue":"8931.0","cpu_idle":"100","host":"server101","server_uptime":"117","runQ_threads":"1","iostat":{"iostat_vdc":"6.60","iostat_vda3":"3.00","iostat_vdd":"1.04","iostat_vda2":"2.90","iostat_dm-0":"3.26","iostat_vda1":"3.44","iostat_vdb":"0.45","iostat_vda":"2.90"},"ierrs":"0","appcode":"cds","load_avg_10min":"0.00","page_scanrate":"NA","memory_free":"10572","cpu_user":"0","alertCount":"6","timestamp":"2015-12-01T18:32:00.0051","thresholdLimit":"5.0","memory_used":"8398","collisions":"0","load_avg_15min":"0.00","cpu_system":"0"}
    },

**Comment by gsaray101** [comment]
Torkel, when I attempted to create a new dashboard it worked but when I try to add a graph via panel, it gives me that error.

**Comment by torkelo** [comment]
same query? yes `*`  is a valid lucene query. 

Do you do anthing with the query to get the error or do you get this error with the default blank query?

**Comment by gsaray101** [comment]
I received the error when I add graph from the panel and pick elasticsearch as the data source. The error pops up. But if I chose to create a new dashboard I dont see the error. The problem is that in one dashboard, I'd need to have multiple charts from elasticsearch datasource, currently not able to do this.

**Comment by torkelo** [comment]
not sure I understand, you can have one elasticsearch graph but not multiple? 

It seems to work here: http://play.grafana.org/dashboard/db/elasticsearch-metrics

**Comment by gsaray101** [comment]
try to add a new chart with elasticsearch data source, you'll see the error top left corner of the panel. The same error on your site.

**Comment by torkelo** [comment]
yes, but when I click refresh or update the query everything works fine. it is just the initial request after switching data source it seems.
