### ISSUE TITLE
http API to manage dashboard variables

### ISSUE THREAD

**Issue by yasharne** [grafana/grafana#33979]
**What would you like to be added**:
endpoint like `/api/dashboards/uid/:uid/:variable` to get or create/update information about the variable 

**Why is this needed**:
Right now I didn't find any docs on updating a variable using APIs, I tried updating the variable by updating the dashboard but I get `{"message":"Not found"}` error

**Comment by hugohaggmark** [comment]
We're working on a way to create variables you can share between dashboards instead of opening up the ability to change variables from the api within a specific dashboard.
