### ISSUE TITLE
Feature Request: Limit number of metrics shown in Tooltip.

### ISSUE THREAD

**Issue by andreaspe** [grafana/grafana#3397]
In Grafana the hover legend shows all metrics if "All series" has been selected. 

![image](https://cloud.githubusercontent.com/assets/1135967/11542609/7488b4c2-9938-11e5-8121-3294df8a88b6.png)

This can be very hard to read if one has a lot of metrics on a graph.

![image](https://cloud.githubusercontent.com/assets/1135967/11542670/af317924-9938-11e5-93c4-34e9218e1d66.png)

It would be a nice feature to limit "All series" to a fixed number, like top 5 but still show all the metrics in the graph.

**Comment by b13n1u** [comment]
+1

**Comment by bergquist** [comment]
Finding a good number for that limit would be hard. I suggest you just uncheck "All series"
