### ISSUE TITLE
How can I change grafana units of measurement?

### ISSUE THREAD

**Issue by ladshada** [grafana/grafana#3398]
I am gathering data from servers by collectd and store it in the graphite. I am trying to create visualisation for collectd memory plugin with grafana dashboard. In graphite I am seeing data in Mb, Gb, etc, but in grafana graph I see strange "Mib" or "Bil" or "Tib" on the Y-axis. When I am changing data rendering from flot to graphite png everything is ok, but I want to have interactive graph.
How can I change grafana units of measurement?

**Comment by toni-moreno** [comment]
You can not change it.

The Mib TiB are the Aproved International Prefixes for 1024 based units.

You can yourself review the code.

````

// Extension of the scaledUnits builder which uses SI binary prefixes. If
  // offset is given, it starts the units at the given prefix; otherwise, the
  // offset defaults to zero and the initial unit is not prefixed.
  kbn.formatBuilders.binarySIPrefix = function(unit, offset) {
    var prefixes = ['', 'Ki', 'Mi', 'Gi', 'Ti', 'Pi', 'Ei', 'Zi', 'Yi'].slice(offset);
    var units = prefixes.map(function(p) { return ' ' + p + unit; });
    return kbn.formatBuilders.scaledUnits(1024, units);
  };
````
