### ISSUE TITLE
Grafana Markdown - Code Snippet Improvement

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#3399]
Currently, the markdown for the code snippets either blend into the panel background or are barely visible on the background in dark mode. 

We should update the `<code>` CSS to look much nicer in light and dark themes. 

@bulletfactory and I will take care of this small tweak and submit a PR. 

Ref:
![screenshot_2015-12-02_16_54_09](https://cloud.githubusercontent.com/assets/2886187/11545568/e9f52c4a-9915-11e5-93d3-65fc26ab8ad7.png)

**Comment by torkelo** [comment]
great, you can take a look at this dashboard for reference of one that is using it a lot 
http://play.grafana.org/dashboard/db/ultimate-graphite-query-guide

**Comment by bulletfactory** [comment]
Was this closed because it's fixed? or is it a duplicate?

**Comment by torkelo** [comment]
think I accidentally clicked "Close and comment" :) Habit of mine :)
