### ISSUE TITLE
Move accesscontrol metrics into accesscontrol package

### ISSUE THREAD

**Issue by donomii** [grafana/grafana#33998]
**What would you like to be added**:

counters live inside of the pkg/services/accesscontrol domain somewhere (say pkg/services/accesscontrol/metrics or even in the root) since we're moving more into package by service rather than package by layer.

**Why is this needed**:

Consistent organisation makes teamwork easier

**Comment by marefr** [comment]
@donomii removed this from the backend platform backlog project. Should perhaps be in some project related to enterprise?
