### ISSUE TITLE
Loki: Bring back processed bytes as meta info

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#33994]
**What would you like to be added**:
Total bytes processed was removed in https://github.com/grafana/grafana/commit/1c838f58723e113f3fd546f859b20a33461cd4cb as this was considered temporary solution before we implement Inspector. However, based on feedback, this is valuable information for every query and therefore we should bring it back.

**Comment by ivanahuckova** [comment]
Basically all that is needed is to bring back this code (1c838f5)
![image](https://user-images.githubusercontent.com/30407135/117972556-96ce4c00-b32b-11eb-80cc-db76433619a3.png)

**Comment by mmenbawy** [comment]
I will try making the necessary changes and submit a PR.
