### ISSUE TITLE
Docs feedback: /administration/provisioning.md

### ISSUE THREAD

**Issue by tigattack** [grafana/grafana#34000]
It seems that supported settings for Discord are missing from the alerting supported settings section.

Could this be added please?

**Comment by marefr** [comment]
Here's the file that needs changes: https://github.com/grafana/grafana/blob/main/docs/sources/administration/provisioning.md

We're not planning to work on this short-term so would need help from the community/contributors for this one.

**Comment by tigattack** [comment]
Thanks @marefr. Where can I find the source for the supported settings for Discord notification channel?  
I had a look just now but without understanding the code I didn't have much luck 😀

**Comment by marefr** [comment]
PropertyName here:
https://github.com/grafana/grafana/blob/7bcb938b80c2d1fdc6f297fbf91f4286936874db/pkg/services/alerting/notifiers/discord.go#L27-L45

**Comment by achatterjee-grafana** [comment]
@tigattack and @marefr , can we close this issue?

**Comment by tigattack** [comment]
Yes, thank you.
