### ISSUE TITLE
Azure Monitor datasource: ResourceGroups() not supported with "Multi-value" mode

### ISSUE THREAD

**Issue by jackalakalaka** [grafana/grafana#34004]
[A copied issue](https://github.com/grafana/azure-monitor-datasource/issues/92) from an archived Azure Monitor datasource repo:

Azure Monitor doesn’t support ResourceGroups() in a dashboard variable with “Multi-value” or "All" mode selected, and implementation of the API being able to expect more than one resource group name would be extremely useful.
```
# Example from the current query inspector:
{
  "xhrStatus": "complete",
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/2/azuremonitor/subscriptions/<guid>/resourceGroups/{rgA,rgB}/resources?api-version=2018-01-01"
  },
  "response": {
    "error": {
      "code": "InvalidResourceGroup",
      "message": "The provided resource group name '{rgA,rgB}' has these invalid characters: '{,}'. The name can only be a letter, digit, '-', '.', '(', ')' or '_'."
    }
  }
}
```

Adding this would allow for dynamic population of a dashboard with multiple resource groups' data, avoiding the need for a user to manually select a dropdown variable value to see info about more than one group. This adaptability is already possible with variables that support Multi-value mode if a user selects "Repeat by variable" under "Repeat options" whereby extended panels are automatically created.

**Comment by sunker** [comment]
Yes I agree this would be a nice feature. Think it should also be possible to do using the Azure Resource Graph api, but it's gonna require a lot of refactoring. I'll label this a feature request, and hopefully we can do this in the near future.

**Comment by Purneau** [comment]
Is it correct that using this 'multi-value' mode is currently also not possible within a resource group?
E.g. I'm trying to display the CPU usage of two machines in a single graph, but if I select more than one machine in the `VM` variable (multi-value) it fails with a 404.
