### ISSUE TITLE
Template variables current value lost on dashboard refresh through navbar

### ISSUE THREAD

**Issue by lsoica** [grafana/grafana#34034]
**What happened / How to reproduce it**:
Steps:
* Load a dashboard with template variables
* Select a custom value for one of the variables
* From the navbar, click the navbar page button
* Select the same dashboard under "Recent"
* The variable for which I selected a custom value is now empty

![grafana-template-variables](https://user-images.githubusercontent.com/1623282/118094041-e6b61d00-b3d6-11eb-89d9-760880ffee8e.gif)

**What you expected to happen**:
The template variable value to be the first value in the list.

**Environment**:
- Grafana version: v7.3.7
- Data source type & version: Prometheus
- OS Grafana is installed on: Kubernetes
- User OS:Ubuntu 20.04
- Browser: Brave Version 1.23.75  Chromium: 90.0.4430.93 (Official Build)  (64-bit)

**Comment by torkelo** [comment]
this is expected your opening the same dashboard you are on, which will clear your current URL variable state. 

Why do you want to select the dashboard you are on in search?

**Comment by lsoica** [comment]
Hi, thanks for your response. I don't think the "why" really matters here. If you leave the option to do it, someone will do it at some point, right ? 

The issue (as far as I see it) is not that the query string is cleared. The issue is that there's no value selected out of the available values for that template variable. Hence, all the panels relying on the template variable are broken.

Another issue I see is that the behavior is not consistent. If I reload the page, the template variable is provisioned with the first value in the list. If I navigate to the dashboard trough the side menu, again, the template variable is provisioned with the first value in the list.

One difference is that the page is not re-fetched when selected through the navbar/search.

**Comment by LeeZChuan** [comment]
Hi,

Maybe, i have the same problem with you. 

When i choose the same variables in different pages. The same variables can not be store it.

I think the grafana could support it in the future? 

![OUvj4qGuHb](https://user-images.githubusercontent.com/48050314/118344055-de88e980-b55e-11eb-9ede-14d6101c9a11.gif)
