### ISSUE TITLE
Observability: Cross team testing kitchen sink issue

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#34038]
Please add any found issues here:

**Comment by zoltanbedi** [comment]
Explore - legend toggling not working in graph


https://user-images.githubusercontent.com/13729989/119814676-f8291a00-beea-11eb-8016-d31a57a2fb80.mp4

**Comment by oscarkilhed** [comment]
In explore -> inspector -> data tab -> data options
clicking the `Download for Excel` generates a JS error and does not flip the switch.

![image](https://user-images.githubusercontent.com/468940/119951706-8ad5c180-bf9c-11eb-8183-4369d4966790.png)

**Comment by oscarkilhed** [comment]
![image](https://user-images.githubusercontent.com/468940/119952111-f15adf80-bf9c-11eb-8353-b24671938b0f.png)

The last log row is hard to expand if there is a horizontal scroll bar. The clickable area is partially hidden behind the scrollbar.

**Comment by zoltanbedi** [comment]
The Download for Excel issue should be fixed https://github.com/grafana/grafana/pull/34685

**Comment by ifrost** [comment]
> Explore - legend toggling not working in graph
> 
>  Kapture.2021-05-27.at.12.56.24.mp4

Can be fixed by #34531 https://github.com/grafana/grafana/pull/34531#issuecomment-848675049

**Comment by ifrost** [comment]
Logs panel in a dashboard is laggy when dragging. Also - context menu takes about 2 seconds to open.

https://user-images.githubusercontent.com/745532/120298501-6e05fa80-c2ca-11eb-8b76-88654e567410.mov

**Comment by oscarkilhed** [comment]
When creating a query in influx chronograf and pasting those queries into grafana, if I add a group weird stuff happens.
Graph in both grafana and chronograf:
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)
  |> yield(name: "last")
```

Graph displayed in chronograph but not in grafana: 
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> group(columns: ["cpu"])
  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: true)
  |> yield(name: "last")
```

This query has no visible datapoints in the grafana graph, but the graph looks ok in chronograph.
```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_system")
  |> filter(fn: (r) => r["cpu"] == "cpu0")
  |> group(columns: ["host"])
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")
```

**Comment by gabor** [comment]
@oscarkilhed thanks a lot for the tests! from the two problematic queries, the first i think is ok, how it should be, and the second i will fix with a PR.
