### ISSUE TITLE
Bug: cannot use non-latin characters inside Data Links

### ISSUE THREAD

**Issue by vsile** [grafana/grafana#34043]
**What happened**:
I added a [link](https://вверх.рф) to my Panel (Edit Panel -> Field -> Data links -> Add link) with non-latin characters.
![Screenshot_20210513_122514](https://user-images.githubusercontent.com/9244347/118109900-6e595700-b3ea-11eb-864a-7351feec38b3.png)

But created link doesn't contain any non-latin characters.
![Screenshot_20210513_122635](https://user-images.githubusercontent.com/9244347/118111059-da888a80-b3eb-11eb-8977-0eeef93f6b28.png)

**How to reproduce**:
Create Graph or Stat Panel -> Field -> Data links -> Add link 
Add some link with non-latin characters - https://вверх.рф

**Environment**:
- Grafana version: 7.5.6
- Data source type & version: Prometheus v2.27.0
- OS Grafana is installed on: Linux 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2+deb10u2 (2019-11-11) x86_64 GNU/Linux
- User OS & Browser: OpenSuse Leap 15.3, Firefox 78.9.0esr (64-bit)
- Grafana plugins: Graph, Stat and other

**Comment by dsotirakis** [comment]
Hello @vsile , this PR probably fixed the issue -->

Has a `8.0.0` milestone on it, so it will be available at the next version :) 

For reference:

![image](https://user-images.githubusercontent.com/15115078/118142909-7ed1f780-b413-11eb-81b8-246c45401964.png)
