### ISSUE TITLE
Long series names on heatmap panel pushes visualization off the screen. 

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#34048]
**What happened**:
There is a  problem with the heat-map panel. This is reproducable on play.

If there is a really long series name, (and when using "data-format: time series buckets) then the series name is not truncated, but pushes the visualization way over to the right. (or even off the page)
there is no option to truncate the series names in the axis labels.
Let me know if you want me to log this as a bug directly into github.

**What you expected to happen**:
Series name to truncate, or wrap. 
Or an option to define a maximum length. 

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/8004654/118120912-8f20ad00-b3e8-11eb-9ecb-c17134e1c7a1.png)

**Environment**:
- Grafana version: 7.5.5 
- Data source type & version: Grafana Cloud
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser:  windows/Firefox 
- Grafana plugins:  n/a
- Others:

**Comment by Elfo404** [comment]
passing this to @grafana/grafana-frontend-platform
