### ISSUE TITLE
Elasticsearch interval template variable

### ISSUE THREAD

**Issue by jveldboom** [grafana/grafana#3404]
Love the ability to use ES! Thanks for all your hard work!

Within the "Metrics" section when using Elasticsearch as the data source templating the interval only seems to work if you use the "Switch editor mode". But the template variable cannot be "interval".

Below is a quick example of trying to use the template variable `$time` and then switching to the editor mode and trying both `$time` and `$interval` as variables.

![graphana](https://cloud.githubusercontent.com/assets/303202/11550592/48e55576-993f-11e5-8f1b-5442dabd40e9.gif)

**Comment by torkelo** [comment]
yes, use something other than $interval,  that is already used by the query editor for the "auto" variable. I cannot change that without breaking existing queries.
