### ISSUE TITLE
Alerting: UI fixes

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#34051]
_Tested on Dev env. Latest tested on May 13_

### Alert rules listing - - - - - - - - - - - - -   

**Functionality**
- Missing option to add a new group 
- Missing expand all button

**UI**

- :heavy_check_mark: Search input missing placeholder
- :heavy_check_mark: State filter is missing label
- :heavy_check_mark: View as should be a radio button group - same as state. It should also be on he same line
- Title of two areas (treshold and system) is missing the word “alerts” at the end
- :heavy_check_mark: Update table rows content to match Figma - remove status, add summary, add timing
    Domas: partially-  I kept status, but renamed to `health`. It seems that both health and state are important to see
- :heavy_check_mark: update sections from Treshold and System or application to the new names
-  NoData as a state should be displayed with an orange label not a blue one

### Alert rule creation  - - - - - - - - - - - - -   

**Functionality**

- I want to save a newly created alert (prometheus one), and I get an errro message saying “There are errors in the form below. Please fix them and try saving again” but there is no indicator of where those errors are  

**UI**
- :heavy_check_mark: Title of each section is too big, should be H4 - 16px
- :heavy_check_mark: update text for alert types to Grafana managed alerts and Cortex/Loki managed alerts - see Figma
- :heavy_check_mark: Namespace and group selects should be on the same line
- :heavy_check_mark: make sure all those inputs and selects from 1st step have equal width
- :heavy_check_mark: spacing between inputs/selects on the same row should be 24px
- :heavy_check_mark: add more vertical spacing between each section - that spacing should be 56px
- :heavy_check_mark: as agreed, in section 4, we should show from start summary, description and runbook URL
- missing section 5, where we tell the user about notifications policies 
- use lighter gray for steps count background (1…5)

### Silences - - - - - - - - - - - - -   

**Functionality**
- :heavy_check_mark:I get 2 messages every time I save a silence “Silence created” and. “Silence updated” - feels redundant 

**UI** 
- :heavy_check_mark: missing duration input field as we have today - it’s useful as it’s faster to read by a human, than a date range is
-  :heavy_check_mark: Update “matchers” to Matching labels - as matcher is not a real word
-  :heavy_check_mark: Update label of first input from matchers to say “Label” instead of “Name”
- All inputs should have placeholders

### Contact points - - - - - - - - - - - - -   

**Functionality**
- as soon as I saved my first contact point, in the table I see now one called default, that doesn’t have a type. this seems like a bug
  Domas: canot repro :/ 

**UI**
- create message template add spacing between title and form
- inputs should have placeholders
- indicate with * required fields (both for template form and contact point form - really important for slack for example, super long list of inputs)
- for contact points that have long list of optional fields we should show that under an expandable element, like we have today in Grafana OSS
- Contact points - icons on the buttons (duplicate and delete) should be 16x16px 

### Routes- - - - - - - - - - - - -   

**UI** 
- :heavy_check_mark: update tab name to Notification policies 
- Remove border bottom from root policy box
- Root policy edit - create a contact point link should have underline 
- timing options 
    - remove box surrounding this area -please see Figma. 
    - also caret icon should point to the right when timings are collapsed, and down when they are expanded
    - timing options should have defaults values
- Specific policies edit/create
    -   :heavy_check_mark: Please update text from “Matchers” to “Matching labels” as matchers is not a real word. Same for the button - see Figma, is updated
    - :heavy_check_mark: we should add a delete icon for each row (as we have in silences), my bad, I forgot to add it in Figma
    - Fix input validations - the tooltip appears inline instead of being positioned absolute. if only one input per row has a validation error everything gets shifted down (see screenshot)
    - On/Off switches should have the label on the same line as the switch 
Table listing of specific policies - don’t show nested policies table if there is no value in there. Most of these policies will be on one level only

### General issue - - - - - - - - - - - - - 

* Hard to silence an alert - no way to do it from alert listing, and no way to see affected alerts by a silence, so basically has to try it in blind, or to remember all the labels
* Try to standardize parts of the UI - indicate required fields (we indicate them only on some forms), Empty states for tables - they should all look the same (like the empty state from specific policies under notification policies)

<img width="1708" alt="Screenshot 2021-05-13 at 13 10 25" src="https://user-images.githubusercontent.com/5183519/118126526-23970980-b401-11eb-951c-a315c1f3fa0c.png">
<img width="397" alt="Screenshot 2021-05-13 at 15 22 09" src="https://user-images.githubusercontent.com/5183519/118126537-25f96380-b401-11eb-982c-cae2239a1ae3.png">
<img width="1458" alt="Screenshot 2021-05-13 at 15 25 01" src="https://user-images.githubusercontent.com/5183519/118126540-25f96380-b401-11eb-9f84-ca47cc5d4ccf.png">

**Comment by domasx2** [comment]
Great work! I got comments for some of these:


> ### Alert rules listing - - - - - - - - - - - - -
> **Functionality**
> 
> * Missing option to add a new group

I'm not sure what this button should do. For grafana, we don't show folders unless they have alerts in them and for cloud it's not possible to to create group without adding a rule. So it kinda follows it should just take you to rule creation, same as the "create rule" button right next to it?

> 
> **UI**
> * View as should be a radio button group - same as state. It should also be on he same line
Component does not support links. Lots of effort to make a nav-enabled one, left it for later :/

> * Title of two areas (treshold and system) is missing the word “alerts” at the end

Should be "rules" perhaps?

> 
> ### Alert rule creation - - - - - - - - - - - - -
> **Functionality**
> 
> * I want to save a newly created alert (prometheus one), and I get an errro message saying “There are errors in the form below. Please fix them and try saving again” but there is no indicator of where those errors are

No validation popups on any fields? Odd, I got "Authorization to datasource failed". Seems this datasource is set up as read-only...

> 
> **UI**
> 
> * missing section 5, where we tell the user about notifications policies

I think we need to discuss it. We can't really know in advance where an alert instance of a rule would be routed. No good way to ensure either option, despite what user selects.

> 
> ### Contact points - - - - - - - - - - - - -
> **Functionality**
> 

> * for contact points that have long list of optional fields we should show that under an expandable element, like we have today in Grafana OSS

Does work this way, except for Slack where all fields are technically "optional", but did not feel right to have everything collapsed

**Comment by oanamangiurea** [comment]
Thanks for having a look so fast Domas. 

>I'm not sure what this button should do. For grafana, we don't show folders unless they have alerts in them and for cloud it's not possible to to create group without adding a rule. So it kinda follows it should just take you to rule creation, same as the "create rule" button right next to it?
 Yes, will take you to rule creation where we have an info box saying that groups can't be empty - [this screen here](https://www.figma.com/file/2s7EGevGeI4GuiArOmUECK/Unified-Alerting?node-id=248%3A382). This is for the user to not get frustrated not knowing how to create a new group if they need one, hence the button.
 
 >Should be "rules" perhaps?
Right, it should be rules. I updated Figma as well
 
 >No validation popups on any fields? Odd, I got "Authorization to datasource failed". Seems this datasource is set up as read-only...
 No validation for me :( and I looked in console, but noting to indicate something coming from one of the form fields
 
 >Maybe we should point out some documentation instead, and link to routes without prescribing options?
 Ok, in that case I'll need to update that area in Figma. I'll post here when it's done
 
 >Does work this way, except for Slack where all fields are technically "optional", but did not feel right to have everything collapsed 
 It's fine if they are collapsed, except from Slack incoming webhook URL. This is how it's shown today in OSS. see screenshot 
<img width="648" alt="Screenshot 2021-05-14 at 12 40 12" src="https://user-images.githubusercontent.com/5183519/118253483-a5933b00-b4b2-11eb-8073-0b1e2c734af8.png">

**Comment by domasx2** [comment]
Slack is complicated :( in the new version you have to provide **either** url or token, but we got no way to express in the options system currently. Maybe we shold not base collapse state on "required" but rather add a separate indicator for "collapsed"..
Will think about it
