### ISSUE TITLE
InfluxDB: Table requests

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3409]
New feature for influxdb that allows you to query and return table data, can be used with the new table panel.

Example 1: field & tag wildcard queries without group by time:
![image](https://cloud.githubusercontent.com/assets/10999/11562568/03313e4c-99cf-11e5-91b1-e1502ec0465d.png)

Example 2: group by tag
![image](https://cloud.githubusercontent.com/assets/10999/11562661/a6bff044-99cf-11e5-9532-4d36dbbb5285.png)

**Comment by fsauer65** [comment]
that's awesome! Thanks!!!
