### ISSUE TITLE
8.0.0-beta1 release notes do not mention licensing change

### ISSUE THREAD

**Issue by adg** [grafana/grafana#34091]
The [8.0.0-beta1 release](https://github.com/grafana/grafana/releases/tag/v8.0.0-beta1) was issued recently, but nowhere in the list of changes is the change of license from Apache 2.0 to AGPL.

This may significantly affect some Grafana users, so it should be called out prominently in the release notes.

**Comment by zoltanbedi** [comment]
@grafana/docs-squad fyi

**Comment by achatterjee-grafana** [comment]
Good idea, @oddlittlebird will be able to take care of this.

**Comment by oddlittlebird** [comment]
@mjseaman, do we want this in the What's new? If so, please add an entry to the draft Google doc.

**Comment by adg** [comment]
IMO it should be prominently displayed in the release notes. There has been another 8.x release and still no mention of this important change.

**Comment by achatterjee-grafana** [comment]
Hello, we are on top of this and the information will be "prominently" displayed. Thanks for the reminder! Tagging @daniellee as well.

**Comment by adg** [comment]
8.0.0 is out. No mention of the license change in the release notes nor the [what's new page](https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v8-0/0).

**Comment by osg-grafana** [comment]
@daniellee *nudge*

**Comment by achatterjee-grafana** [comment]
Can we close this issue @mjseaman? TY

**Comment by tcolgate** [comment]
We're at 8.0.5, and this isn't mentioned on the release page, CHANGELOG, or the blog as far as I can tell.
