### ISSUE TITLE
Failed to build docker image with error `Unknown command "pkg-archive"`

### ISSUE THREAD

**Issue by jiangpengcheng** [grafana/grafana#34108]
**What happened**:

Failed to run `make build-docker-dev`, and error is `Unknown command "pkg-archive"`

**What you expected to happen**:

Succeed to build docker image

**How to reproduce it (as minimally and precisely as possible)**:

just run `make build-docker-dev`

**Anything else we need to know?**:

**Environment**:
- Grafana version: master branch, commit hash 2fc9c6ca58cb6df332976d1414614abb9f8a2f9e
- Data source type & version: No
- OS Grafana is installed on: CentOS Linux release 7.9.2009 (Core)
- User OS & Browser: CentOS Linux release 7.9.2009 (Core)
- Grafana plugins: No
- Others:

**Comment by dsotirakis** [comment]
Hello @jiangpengcheng, can you please provide more information on what environment you run on?

Maybe related to https://github.com/grafana/grafana/issues/13727

Any reason you want to run `build-docker-dev`
You can run `make build-docker-full` instead.

**Comment by jiangpengcheng** [comment]
I checked that the `build.go` has removed command `pkg-archive` in this PR: https://github.com/grafana/grafana/pull/29461, so this error happended

I used `make build-docker-dev` because I think it looks more light than `make build-docker-full`, does community use `make build-docker-full` to build offcial docker image now?

**Comment by ivanahuckova** [comment]
@dsotirakis I have removed `needs more info` label and replaced it with `needs investigation`. If we have more questions, we can always ask and add it again. 🙂 Also, I have moved this to backend platform backlog.

**Comment by dsotirakis** [comment]
@jiangpengcheng Hello!
Is this still the case? Please have a look [here](https://github.com/grafana/grafana/issues/13727#issuecomment-430894272) and [here](https://github.com/grafana/grafana/issues/13727#issuecomment-430894272) for some comments. I'd suggest you use `make build-docker-full` instead, at least if you're running on MacOS.
However, I'll delete `pkg-archive` since its not the case anymore. Thanks!
