### ISSUE TITLE
Value mapping for hexadecimal strings match all values

### ISSUE THREAD

**Issue by Totalus** [grafana/grafana#34131]
### What happened

When trying to set value mapping for hexadecimal strings (`0x123`), the mapping matches (replaces) all values.

Without value mapping:
![image](https://user-images.githubusercontent.com/34516402/118289183-13376b00-b4a3-11eb-9490-aad1f5329a9f.png)

With value mapping for `0x10`:
![image](https://user-images.githubusercontent.com/34516402/118289433-585b9d00-b4a3-11eb-90c9-c6b1e5a5f35d.png)

### What you expected to happen

The value replacement only applied to the values that actually match.

### Anything else we need to know ?

#30893 was a fix for this issue, but does not properly fix the case of hexadecimal strings because `parseFloat` is still used with hex strings and always returns 0. `parseInt` should be used instead as it properly parses hex strings.

### Environment
- Grafana version: `Grafana v7.5.6 (5fdad5bfe4)`

**Comment by Totalus** [comment]
It seems like #33820 partially solves this issue since it uses the string value for comparison for `MappingType.ValueToText` mapping type. However I think it will still be an issue with the `MappingType.RangeToText` type as it still uses `parseFloat`.

**Comment by hugohaggmark** [comment]
Seems this is not working in Grafana Beta3 at all https://play.grafana.org/d/wTQj4Y6Mk/value-mapping-for-hexadecimal-strings-match-all-values-34131?orgId=1
