### ISSUE TITLE
Library panels: missing column leads to "error while loading library panels" error in frontend

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#34145]
**What happened**:
Updated a dev environment grafana from 7.5.5 to 8.0.0-beta1. On visiting any existing dashboard, the frontend pops an error toast "error while loading library panels" and the inspector indicates a 500 err. No panels in the dashboard load. Grafana log shows an error for "pq: column u1.id does not exist". Seems like a database migration might be missing?

**What you expected to happen**: Any DB migrations required should run and existing dashboards should load

**How to reproduce it (as minimally and precisely as possible)**: Grafana 7.5.5 with postgres backend, dashboards configured for some existing sources. Remove 7.5.5 and replace with 8.0.0 beta1, should see error loading dashboards.

**Anything else we need to know?**:

**Environment**: AWS/Fargate
- Grafana version: 8.0.0 beta 1
- Data source type & version: prometheus 
- OS Grafana is installed on: Docker/AWS-Fargate
- User OS & Browser: MacOS, Chrome
- Grafana plugins:
- Others:

**Comment by hdecarne** [comment]
Same after 7.5.6 -> 8.0.0-beta1 upgrade. Log messages are:

> 2021-05-14T22:28:35+02:00 <server> /usr/bin/grafana-server[2694]: t=2021-05-14T22:28:35+0200 lvl=eror msg="Error while loading library panels" logger=context userId=2 orgId=1 uname=<user> error="pq: column u1.id does not exist" remote_addr=10.1.1.100
> 2021-05-14T22:28:35+02:00 <server> /usr/bin/grafana-server[2694]: t=2021-05-14T22:28:35+0200 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname=<user> method=GET path=/api/dashboards/uid/2o5dPnsMz status=500 remote_addr=10.1.1.100 time_ms=47 size=73 referer=<base server url>/d/2o5dPnsMz/system-access
>

**Comment by jpdstan** [comment]
We're experiencing this too.

**Comment by hugohaggmark** [comment]
Hi everyone, because Library Panels where behind a feature toggle we didn't bother on doing proper migrations. To fix this you need to run this:
```
DELETE from migration_log where sql like '%library_panel%';
DELETE from migration_log where sql like '%library_element%';
DROP TABLE library_panel;
DROP TABLE library_panel_dashboard;
DROP TABLE library_element;
DROP TABLE library_element_connection; 
```

Sorry about any inconvenience this might cause.

**Comment by schirgitom** [comment]
Dear all,

i installed V8.0.0 from scratch and I experienced this issue. 
It remains the same after running the SQL commands...

Any ideas?

Thanks,
Thomas

**Comment by hugohaggmark** [comment]
> Dear all,
> 
> i installed V8.0.0 from scratch and I experienced this issue.
> It remains the same after running the SQL commands...
> 
> Any ideas?
> 
> Thanks,
> Thomas

Thanks for reporting this @schirgitom can you please share OS and version, Database & version and the exact log output from grafana server. Could you also share the results from 
SELECT * from migration_log where sql like '%library_panel%';
SELECT * from migration_log where sql like '%library_element%';

Thank you

**Comment by schirgitom** [comment]
Dear Hugo,

Thanks for fast reply.
> > Dear all,
> > i installed V8.0.0 from scratch and I experienced this issue.
> > It remains the same after running the SQL commands...
> > Any ideas?
> > Thanks,
> > Thomas
> 
> Thanks for reporting this @schirgitom can you please share OS and version, Database & version and the exact log output from grafana server. Could you also share the results from
> SELECT * from migration_log where sql like '%library_panel%';
> SELECT * from migration_log where sql like '%library_element%';
> 
> Thank you

My OS is Windows 10 Pro - Version 20H2
Database: PostgreSQL 13

The Logs are attached - unfortunately it is partly in german...
[grafana.log](https://github.com/grafana/grafana/files/6499973/grafana.log)


The results of the queries are: 
![image](https://user-images.githubusercontent.com/83354971/118624232-42164f80-b7c9-11eb-91b9-06a00e3f4d02.png)

![image](https://user-images.githubusercontent.com/83354971/118624348-5eb28780-b7c9-11eb-8e99-87ac952e080e.png)


Thanks,
Thomas

**Comment by hugohaggmark** [comment]
Thank you @schirgitom and what does the grafana logs from the server say and any output from the browsers console or network tab that you might have. Thank you again!

**Comment by schirgitom** [comment]
> Thank you @schirgitom and what does the grafana logs from the server say and any output from the browsers console or network tab that you might have. Thank you again!

The response from network tap is the following: {"error":"pq: Spalte u1.id existiert nicht","message":"Error while loading library panels"}

It means that the column u1.id does not exist. 
The grafana logs from server are attached to the post before - but i will copy the last lines into here:

`t=2021-05-18T10:16:39+0200 lvl=info msg="New token" logger=context userId=0 orgId=0 uname= unhashed token=a11b05270ab707f2ef6787156d9f5985
t=2021-05-18T10:16:44+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[::1] time_ms=3 size=0 referer=
t=2021-05-18T10:16:50+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[::1] time_ms=2 size=0 referer=
t=2021-05-18T10:17:01+0200 lvl=eror msg="Error while loading library panels" logger=context userId=1 orgId=1 uname=admin error="pq: Spalte u1.id existiert nicht" remote_addr=[::1]
t=2021-05-18T10:17:01+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/uid/Q3Qxek3Gz status=500 remote_addr=[::1] time_ms=19 size=91 referer=http://localhost:3000/d/Q3Qxek3Gz/new-dashboard-copy
t=2021-05-18T10:48:23+0200 lvl=info msg="New token" logger=context userId=1 orgId=1 uname=admin unhashed token=c5047364a1a5696053b0ae5246c55564
t=2021-05-18T10:48:26+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[::1] time_ms=11 size=0 referer=
t=2021-05-18T10:49:04+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[::1] time_ms=3 size=0 referer=
t=2021-05-18T11:31:28+0200 lvl=info msg="New token" logger=context userId=1 orgId=1 uname=admin unhashed token=70508f98e9390c50462f9861b786b6cc
t=2021-05-18T12:18:23+0200 lvl=info msg="New token" logger=context userId=1 orgId=1 uname=admin unhashed token=a667c9d47e6c10ce4265118e18268225
t=2021-05-18T12:18:23+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/build/grafana.light.2e9481ec206e268d9cf4.css status=404 remote_addr=[::1] time_ms=211 size=28243 referer="http://localhost:3000/d/1wV2Ri3Mk/new-dashboard-copy-2?orgId=1"
t=2021-05-18T12:18:25+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/editor/editor.main.js.map status=404 remote_addr=[::1] time_ms=14 size=28243 referer=
t=2021-05-18T12:18:25+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/loader.js.map status=404 remote_addr=[::1] time_ms=15 size=28243 referer=
t=2021-05-18T12:18:35+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/live/ws status=0 remote_addr=[::1] time_ms=6 size=0 referer=
t=2021-05-18T12:18:35+0200 lvl=eror msg="Dashboard not found" logger=context userId=1 orgId=1 uname=admin error="Dashboard not found" remote_addr=[::1]
t=2021-05-18T12:18:35+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/uid/1wV2Ri3Mk status=404 remote_addr=[::1] time_ms=1 size=63 referer="http://localhost:3000/d/1wV2Ri3Mk/new-dashboard-copy-2?orgId=1"
t=2021-05-18T12:18:44+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/loader.js.map status=404 remote_addr=[::1] time_ms=9 size=28243 referer=
t=2021-05-18T12:18:45+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/editor/editor.main.js.map status=404 remote_addr=[::1] time_ms=9 size=28243 referer=
t=2021-05-18T12:18:45+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/editor/editor.main.nls.js.map status=404 remote_addr=[::1] time_ms=7 size=28243 referer=
t=2021-05-18T12:18:45+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/base/worker/workerMain.js.map status=404 remote_addr=[::1] time_ms=11 size=28243 referer=
t=2021-05-18T12:18:52+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/lib/monaco/min-maps/vs/base/worker/workerMain.js.map status=404 remote_addr=[::1] time_ms=9 size=28243 referer=
t=2021-05-18T12:18:56+0200 lvl=eror msg="Error while loading library panels" logger=context userId=1 orgId=1 uname=admin error="pq: Spalte u1.id existiert nicht" remote_addr=[::1]
t=2021-05-18T12:18:56+0200 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/dashboards/uid/at3gNm3Gz status=500 remote_addr=[::1] time_ms=4 size=91 referer=http://localhost:3000/d/at3gNm3Gz/new-dashboard-copy
`

**Comment by hugohaggmark** [comment]
Thank you @schirgitom, I'll look into this

**Comment by hugohaggmark** [comment]
I can repro this on a clean postgres installation

**Comment by hugohaggmark** [comment]
My apologies, seems like this is a bug on fresh Grafana 8.0.0-beta1 installation for users using Postgres as the DB for Grafana. Working on a fix that is released on Thursday in Beta2. Thank you for your patience.
