### ISSUE TITLE
Tempalting: Multi Value and All selection for KairosDB

### ISSUE THREAD

**Issue by dchicurel** [grafana/grafana#3414]
Hi, I have found that is not possible to do Multiple Value and All selection for KairosDB. The issue should be that none of the 'multi format' options (glob, lucene, pipe..etc) matches with KairosDB query format. I think that should work if we add an option like 'json' or something. 
For example, the format for a KairosDB query should be like:
```
"tags":{"server":["server1","server2"]}
```
But, when I try with glob (the most similar approach) I'm getting:
```
"tags":{"server":["{server1,server2}"]}
```
do you think this could be accomplished adding the option and the logic here?
https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateSrv.js
It should be something like:
```
 case "json": {
            return value.join('","'); // I'm not sure if double quotes have to be quoted here.
          }
```
Or should be this accomplished in the datasource side?

Thank you!

**Comment by mbessler** [comment]
+1
I tried a few things based on @dchicurel's suggestions but the double quotes get escaped before the query is sent to KairosDB. Probably to sanitize form input, so that makes sense. Not being familiar with the grafana code-base nor really javascript, I ran out of things to try. 
Any suggestions would be appreciated.

**Comment by dchicurel** [comment]
I thought the format could be build with text, but I realized that what is needed is a json object (array). What I ended up doing is to use the pipe format, and then split the string in kairosdb datasource.
It is working with that. It is not finished, but the main change I did is this:
```
--- a/public/app/plugins/datasource/kairosdb/datasource.js
+++ b/public/app/plugins/datasource/kairosdb/datasource.js
@@ -329,11 +329,11 @@ function (angular, _, dateMath, kbn) {
       if (_.isEmpty(query.aggregators)) {
         delete query.aggregators;
       }
-
       if (target.tags) {
         query.tags = angular.copy(target.tags);
         _.forOwn(query.tags, function(value, key) {
-          query.tags[key] = _.map(value, function(tag) { return templateSrv.replace(tag); });
+          query.tags[key] = _.map(value, function(tag) { return templateSrv.replace(tag, options.scopedVars).split('|'); });
+          query.tags[key] = _.flatten(query.tags[key]);
         });
       }
```

**Comment by ptgreg** [comment]
@dchicurel any news on this feature? I also need it. Could you do a PR of you changes?

**Comment by mkeagar** [comment]
+1

**Comment by vguhesan** [comment]
+1

**Comment by torkelo** [comment]
closing this as kairosdb is in it's own repo now
