### ISSUE TITLE
Dashboard settings styling issues

### ISSUE THREAD

**Issue by Knocks83** [grafana/grafana#34164]
**What happened**:
![image](https://user-images.githubusercontent.com/22529815/118405677-374ca500-b679-11eb-89cc-1e334fa769c6.png)

**What you expected to happen**:
The panel options should be in the box and the "Delete dashboard" button should be a little higher that the border of the page

**How to reproduce it (as minimally and precisely as possible)**:
Take a dashboard, go to its settings and scroll down

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0 beta 1
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 - Firefox

**Comment by ivanahuckova** [comment]
I was able to observe/reproduce this on https://play.grafana.org/d/000000010/annotations?orgId=1&editview=settings

**Comment by torkelo** [comment]
is this only on windows+firefox? cannot replicate on linux with chrome or firefox . What version of firefox?

**Comment by Knocks83** [comment]
> 
> 
> is this only on windows+firefox? cannot replicate on linux with chrome or firefox . What version of firefox?

In my case it happens on Google Chrome too (just downloaded). The Firefox version is 88.0.1 (64-bit).

**Comment by thisisobate** [comment]
I just confirmed...same behaviour occurs in chrome.
<img width="1148" alt="Screenshot 2021-05-18 at 14 21 21" src="https://user-images.githubusercontent.com/29557702/118658839-ad214f80-b7e4-11eb-911c-6ee3bd7a0be5.png">
Would open a PR for this soon
