### ISSUE TITLE
Datasources: Dataproxy timeout in configuration is not working properly when requests go through proxy

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#34177]
**What happened**:

Noticed that [dataproxy.timeout](https://github.com/grafana/grafana/blob/main/conf/defaults.ini#L144) is not working when requests go through proxy and **not** as backend datasources (works well in this case). Even if someone sets a small timeout, the server is not timing out.

**What you expected to happen**:

Timeout after certain amount of seconds is set.

**How to reproduce it (as minimally and precisely as possible)**:

Can set up a Prometheus panel, send requests with a delay (will go through proxy) and see that it won't timeout.

In more depth, you can use [mitmproxy](https://mitmproxy.org/) like:

>  mitmproxy --mode=reverse:http://127.0.0.1:9090 --listen-host=127.0.0.1 --listen-port=9999 --set console_mouse=false using prometheus, and then configure a Prometheus data-source in grafana for port-9999.
Inside the mitmproxy window:
press “i” to setup intercepting, enter ‘~q’ to intercept requests.
Using this, every request coming to mitmproxy has to be approved with `a`. or approve all requests with `A`.

**Anything else we need to know?**:

Related issue: https://github.com/golang/go/issues/28876

Potential (?) workaround, is to use `ResponseHeaderTimeout`, tested and works. (https://stackoverflow.com/a/65963311)

**Comment by hqm** [comment]
Is there a release of Grafana that has this issue fixed?
