### ISSUE TITLE
Feature Request : Alias for pannels

### ISSUE THREAD

**Issue by thasos** [grafana/grafana#3418]
Hello,

I have a templated dashboard with some pannels (QoS, ResponseTime, RequestNumber, ...) by client, and I want a direct link to a couple of pannel/client, for integration with another tool.

Example (grafana 2.5.0) with a shared link :
- http://grafanahost/render/dashboard-solo/db/my_templated_dash_perclient?panelId=**2**&var-client=**someclient**&width=1000&height=500
- http://grafanahost/render/dashboard-solo/db/my_templated_dash_perclient?panelId=**3**&var-client=**otherclient**&width=1000&height=500

But the id can change if I add a pannel (for example).
So an alias system would be great, like :
- http://grafanahost/render/dashboard-solo/db/my_templated_dash_perclient?panelId=**qos**&var-client=**someclient**&width=1000&height=500
- http://grafanahost/render/dashboard-solo/db/my_templated_dash_perclient?panelId=**nb_requests**&var-client=**otherclient**&width=1000&height=500

*(I've searched in old issues and found nothing, sorry if I used wrong keywords !)*

Thanks in advance, and nice work :)
Regards.

**Comment by torkelo** [comment]
if you have a scripted dashboard you can just assign a unique panelId that you do not change. It needs to be a number though.
