### ISSUE TITLE
Can't save notification channel

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#34200]
**What happened**:
When creating a notification channel and clicking on the Save button nothing happens and the new notification channel is not being saved.

https://user-images.githubusercontent.com/1170767/118482002-11241500-b70c-11eb-822c-eea8acf88f70.mov

**What you expected to happen**:
The notification channel should be saved correctly

**How to reproduce it (as minimally and precisely as possible)**:
Try to create a new notification channel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8 (beta1)
- Data source type & version: N/A
- OS Grafana is installed on: Mac OS
- User OS & Browser: Mac OS / Firefox 89
- Grafana plugins:
- Others:

**Comment by Clarity-89** [comment]
Seems to be an issue with `react-hook-form`, the `addresses` field from the email option doesn't get unregistered when the type is changed, causing a validation error. Seems like updating `react-hook-form` to version 7.5.3 solves this issue.
