### ISSUE TITLE
annotation lines drawn below graphs

### ISSUE THREAD

**Issue by arussellsaw** [grafana/grafana#3420]
We use a lot of 100% fill graphs on our grafana dashboards, and have found that the annotations are drawn below the data, rendering them invisible but for the bottom icon.

this is on grafana 2.1 using influxdb 0.9 datasource and google auth (probably unrelated)

**Comment by torkelo** [comment]
will require an update to flot graphing library, the markings are rendered before series.

**Comment by torkelo** [comment]
we updated the way annotation are drawn in 4.6, should fix this
