### ISSUE TITLE
annotations visible after changing dashboards

### ISSUE THREAD

**Issue by arussellsaw** [grafana/grafana#3421]
I've found that when changing dashboards between our production and staging environment i can see the annotations for the previous dashboard for a while until a new annotation query is finished.

this is using two different datasources, both influxdb 0.9
this is on grafana 2.1.1 using google auth (probably unrelated)

**Comment by torkelo** [comment]
fixed in master and 2.5 & 2.6 builds

**Comment by torkelo** [comment]
or after closer inspection it is only fixed in 2.6.x
