### ISSUE TITLE
Datalinks wrong after Auto-Refresh or change of time range

### ISSUE THREAD

**Issue by ulrichSchreiner** [grafana/grafana#34212]
hi,

i'm using 8.0.0-beta1, so perhaps this is a beta-bug.

anyway: i create datalinks with my data from loki to jump to a seprate webapp and show the data. When doing a browser-refresh (F5, CTRL-R) all data is ok and all links are rendered correctly.

but when i change the time selector now to a different value (for example from 1h -> 3h) all reloads and most of the time **some** of the datalinks are wrong now. they use the variables from the wrong row. this also happens, when grafana does its own data reload (when i have an auto-refresh of 30s or 1min or so).

i use 
~~~
https://>my.webapp.url>/${__data.fields.TraceID}
~~~
as link and
~~~
Open ${__data.fields.TraceID}
~~~
as tooltip. 

The log-data from loki is rendered in a table and in the table shows correct log-data. so it is very confusing seeing one `TraceID` in the table panel but the link jumps to the one of the row below. 

and btw: sometimes the field is rendered empty (not in the link, not in the tooltip) although it is shown in the table.

**Comment by ivanahuckova** [comment]
Hello @ulrichSchreiner and thank you for reporting the issue. I was also able to reproduce this on [grafana.play with gdev-testdata data source](https://play.grafana.org/d/tNlWezqGk/datalinks_autorefresh?orgId=1).

https://user-images.githubusercontent.com/30407135/118612309-eeeacf80-b7bd-11eb-921c-d0387861f6b3.mov
