### ISSUE TITLE
Error during WebSocket handshake: Unexpected response code: 404

### ISSUE THREAD

**Issue by gittygoo** [grafana/grafana#34224]
**What happened**:

On console we can see the following error
`WebSocket connection to 'wss://XXXX.YYYY//OURSUBPATHapi/live/ws' failed: Error during WebSocket handshake: Unexpected response code: 404`

Somehow it seems its is missing a "/" between "OURSUBPATH" and "api"

**What you expected to happen**:
no errors

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to Grafana v8.0.0-beta1 (84203aaff8)

**Anything else we need to know?**:

We use the following docker ENV Variables:

GF_SERVER_SERVE_FROM_SUB_PATH = true
GF_SERVER_ROOT_URL = https://XXXX.YYYY/OURSUBPATH/

**Environment**:
- Grafana v8.0.0-beta1 (84203aaff8)
- Running on kubernetes/docker

**Comment by ivanahuckova** [comment]
This seems to be already fixed in https://github.com/grafana/grafana/pull/34134.  This PR is going to be part of the next beta-2 release.
