### ISSUE TITLE
Unable to save multiple active values as template 

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#3422]
The Template variables feature allow the user to select multiple values, but when saving a dashboard and refreshing the page, it always has the first value in the list selected.

For some reason it won't save multiple values.

However when selecting multiple ones at runtime it works fine. And providing multiple via a permalink (e.g. `?var-foo=x&var-foo=y`) also works fine.

<img width="841" alt="screen shot 2015-12-04 at 16 00 29" src="https://cloud.githubusercontent.com/assets/156867/11594154/4fc3cd34-9aa0-11e5-95c3-571fd6489179.png">
<img width="217" alt="screen shot 2015-12-04 at 16 00 39" src="https://cloud.githubusercontent.com/assets/156867/11594155/5172664a-9aa0-11e5-93ce-baa24143e04b.png">

Read-only demo: <https://grafana.wikimedia.org/dashboard/db/redis?var-cluster=mc1*&var-cluster=rdb1*>

When viewing the JSON before saving, it contains:
```json

        "current": {
          "text": "rdb1* + mc1*",
          "value": [
            "rdb1*",
            "mc1*"
          ],
          "tags": []
        },
```

Once saved, and reloaded, it has become:
```json
        "current": {
          "text": "rdb1*",
          "value": "rdb1*"
        },
```

**Comment by torkelo** [comment]
it works for me:
http://play.grafana.org/dashboard/db/issue-3422

**Comment by torkelo** [comment]
When I look at the dashboard json you have for that dashboard it does not look like you saved it while you had many selected.

**Comment by Krinkle** [comment]
Using the "View JSON" feature before saving, I can see it contains:
```json
        "current": {
          "text": "rdb1* + mc1*",
          "value": [
            "rdb1*",
            "mc1*"
          ],
          "tags": []
        },
```

Once saved, and reloading the page, it becomes:
```json
        "current": {
          "text": "rdb1*",
          "value": "rdb1*"
        },
```

**Comment by Krinkle** [comment]
> When I look at the dashboard json you have for that dashboard it does not look like you saved it while you had many selected.

... and when you view it in the browser, you also saw that it processed it wrongly and presented only one option selected?

**Comment by torkelo** [comment]
strange, have you done something with the backend storage? I mean it should save the current state of the json. No one has reported any save problems so its very strange. And it seems to work on all instances I have. 

Can you inspect the json pushed in the save (using chrome dev tools),  Does other changes persist?

**Comment by torkelo** [comment]
sorry, Missed the comment that you said it does save it and you see the correct json when you load it. Maybe its problem with the loading / dashboard init phase. It seems to be fixed in master. Try 2.6 beta that was released today.

**Comment by Krinkle** [comment]
@torkelo We've upgraded to `v2.6.0-beta1`, but the issue was not resolved. I've re-selected the options and re-saved the dashboard, but the bug remains.

The format did change a little bit.

Newly saved Dashboard JSON at <https://grafana.wikimedia.org/api/dashboards/db/redis>:
```json

        "options": [
          {
            "text": "rdb1*",
            "value": "rdb1*",
            "selected": true
          },
          {
            "text": "rdb2*",
            "value": "rdb2*",
            "selected": false
          },
          {
            "text": "mc1*",
            "value": "mc1*",
            "selected": true
          },
          {
            "text": "mc2*",
            "value": "mc2*",
            "selected": false
          }
        ],
```

Which looks good. But at run time it becomes:
```json
        "options": [
          {
            "text": "rdb1*",
            "value": "rdb1*",
            "selected": true
          },
          {
            "text": "rdb2*",
            "value": "rdb2*",
            "selected": false
          },
          {
            "text": "mc1*",
            "value": "mc1*",
            "selected": false
          },
          {
            "text": "mc2*",
            "value": "mc2*",
            "selected": false
          }
        ],
```

**Comment by torkelo** [comment]
Very strange, do not understand why I cant replicate it here:
http://play.grafana.org/dashboard/db/issue-3422
