### ISSUE TITLE
User name is not updated right away after updating "X-WEBAUTH-NAME" value

### ISSUE THREAD

**Issue by GaryZengTurbo** [grafana/grafana#34225]
**What happened**:
Same user with updated "X-WEBAUTH-NAME" value, the name is not updated right away.

**What you expected to happen**:
The name should always matches the "X-WEBAUTH-NAME" value. 
On the third time, the returned name is `user2`, but the "X-WEBAUTH-NAME" value is `user1`. 

**How to reproduce it (as minimally and precisely as possible)**:
1. curl -H "X-WEBAUTH-USER: user" -H "X-WEBAUTH-NAME: `user1`" http://localhost:3000/api/user
{"id":4,"email":"user","name":"`user1"`,"login":"user","theme":"","orgId":1,"isGrafanaAdmin":false,"isDisabled":false,"isExternal":true,"authLabels":["OAuth"],"updatedAt":"2021-05-17T14:56:53Z","createdAt":"2021-05-17T14:56:53Z","avatarUrl":"/reports/avatar/ee11cbb19052e40b07aac0ca060c23ee"}%
2. curl -H "X-WEBAUTH-USER: user" -H "X-WEBAUTH-NAME: `user2`" http://localhost:3000/api/user
{"id":4,"email":"user","name":"`user2`","login":"user","theme":"","orgId":1,"isGrafanaAdmin":false,"isDisabled":false,"isExternal":true,"authLabels":["OAuth"],"updatedAt":"2021-05-17T14:57:02Z","createdAt":"2021-05-17T14:56:53Z","avatarUrl":"/reports/avatar/ee11cbb19052e40b07aac0ca060c23ee"}%
3. curl -H "X-WEBAUTH-USER: user" -H "X-WEBAUTH-NAME: `user1`" http://localhost:3000/api/user
{"id":4,"email":"user","name":"`user2`","login":"user","theme":"","orgId":1,"isGrafanaAdmin":false,"isDisabled":false,"isExternal":true,"authLabels":["OAuth"],"updatedAt":"2021-05-17T14:57:02Z","createdAt":"2021-05-17T14:56:53Z","avatarUrl":"/reports/avatar/ee11cbb19052e40b07aac0ca060c23ee"}%

**Anything else we need to know?**:
After waiting a while, the name will be updated eventually.

**Environment**:
Grafana version: v7.3.8 (1e261642f4)

**Comment by marefr** [comment]
This code 
https://github.com/grafana/grafana/blob/355be158b7fb27b71ac37a3821916346536125c0/pkg/services/contexthandler/authproxy/authproxy.go#L317

is calling this code which caches the signed in user data for 5 seconds 
https://github.com/grafana/grafana/blob/355be158b7fb27b71ac37a3821916346536125c0/pkg/services/sqlstore/user.go#L506

**Comment by ying-jeanne** [comment]
seems when we fallback the name change as user2 -> user1, it doesn't take the change, but when we update user2 -> user3, it takes the change immediately, probably somewhere when we cache, we "ignore" the fallback behavior since we think it is an "outdated" data

**Comment by ying-jeanne** [comment]
hey @GaryZengTurbo, thanks for reporting issue. As described before, the expected behavior is a bit confusing since we need to modify the user info in a get action, would you mind to share with us the use case when you would need to do above transactions? could you use user API to do the user info modification instead?

**Comment by GaryZengTurbo** [comment]
Hi @ying-jeanne ,

Thanks for following up.
>could you use user API to do the user info modification instead?

We are using `auth-proxy`, and trying to avoid directly modifying user. 
 
Here are the details our Grafana integration use case:
1. we use  Grafana’s auth-proxy to feature.
2. In some case, we have same X-WEBAUTH-USER user with different X-WEBAUTH-NAME name. 
```
 proxy_set_header   X-WEBAUTH-USER $webauth_user;
 proxy_set_header   X-WEBAUTH-NAME $webauth_name;
```
3.  when the name is not updated, we will have wrong user name on the UI. For example, in the screenshot, the X-WEBAUTH-NAME value was `test2`, but the UI show `test1`.
![screenshot_user](https://user-images.githubusercontent.com/78286537/121370434-bb0d5080-c90a-11eb-8bc5-49ea573a4261.png)

**Comment by Rohxn16** [comment]
Hey, is this issue still open? If it is I will take a look into this.
