### ISSUE TITLE
Coloring doesn't seem to work for JSON Data on Elaasticsearch

### ISSUE THREAD

**Issue by skundrik** [grafana/grafana#3425]
Regardless of what I do, can't get any colours. The status column is mapped as "long" in ES.

![image](https://cloud.githubusercontent.com/assets/14072681/11596553/96061268-9aad-11e5-98c0-c9f572e08a49.png)

**Comment by torkelo** [comment]
make sure your status field is a number in the json document and not a string

**Comment by skundrik** [comment]
The mapping is set to long in ES but I'll double check.

**Comment by torkelo** [comment]
checkt the response from ES using chrome dev tools (network tab)

**Comment by skundrik** [comment]
Thanks, you are correct seems my data was coming down as strings for some reason.
