### ISSUE TITLE
new Time series panel is missing the threshold functionality

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#34268]
Not sure if it's by design, the default threshold does not work, and the threshold that used to work in the graph panel is missing.

**Comment by oscarkilhed** [comment]
Have you tried changing the show threshold setting?

![image](https://user-images.githubusercontent.com/468940/118631428-c66bd100-b7cf-11eb-88d7-5059f75743bf.png)

**Comment by amnonh** [comment]
I'm using Grafana 7.5.5 and it's missing:
![image](https://user-images.githubusercontent.com/2118079/118632766-6a0daf00-b7d9-11eb-9fd0-7c9f48ab8a14.png)

**Comment by oscarkilhed** [comment]
Ah, this is fixed in the next version, thanks for reporting the issue.
