### ISSUE TITLE
Elasticsearch table queries limited to 500 entries

### ISSUE THREAD

**Issue by NickG123** [grafana/grafana#3426]
Hi there,
I have been using the new Table panel in the 2.6.0 beta1.
First of all, this is an awesome new feature, great work!
One thing I noticed is that queries from ElasticSearch seem to have a hard-coded max size of 500, so (for example) when I make a query for log entries from the past 30 days, I only get 500 of them back.
It would be nice if this was a customizable option.

**Comment by torkelo** [comment]
500 seems like a reasonably number, you can always narrow the time range?

**Comment by 1tft** [comment]
Only for information, the 500 limit does not affect the normal time series histogramm, correct? Also for you information elastic 2.1 has placed a soft limit on the maximum number of results (default 10,000) that can be requested in any single search request (https://github.com/elastic/elasticsearch/pull/13188). But I think grafana does not make a normal "search" when creating the histogramm?!

**Comment by torkelo** [comment]
no it only affects raw log queries

**Comment by NickG123** [comment]
500 does seem like a reasonable amount (I can't imagine wanting to scroll through more than that) I just thought it might be desirable to make it configurable.  If you disagree, feel free to close the ticket.

**Comment by Chris7** [comment]
Sorry to resurrect this, but I've been using grafana to aggregate logs across multiple docker services, so 500 is actually a small number when aggregating multiple docker containers/services. I noticed this is still non-configurable, would it be possible to have this option definable in the data source or in the query panel itself?

**Comment by daniellee** [comment]
@Chris7 is this in the table panel?

**Comment by Chris7** [comment]
It isn't, I created my own logstreamer panel, though it does draw from the table panel for column setup:

![ginkgo_logstream](https://cloud.githubusercontent.com/assets/963909/25871205/b79d406e-34d4-11e7-8730-db1c446b530c.png)

**Comment by daniellee** [comment]
@Chris7 That sounds :sparkles:. Any chance you could send submit that as a plugin to https://github.com/grafana/grafana-plugin-repository? And with this use case, we would definitely consider adding a variable for the max limit.

**Comment by Chris7** [comment]
Certainly @daniellee. I'll spend some time cleaning it up this week so it's not that horrific.

**Comment by cr42** [comment]
+1 to make the 500 limit configurable for elasticsearch raw documents. I often use grafana as a GUI for ES  queries that often exceed this limit and then export the data as csv.

**Comment by jaune-rouge** [comment]
+1 to that.

Additionally I believe this is the same issue for elastic search template queries. I'm trying to get everything and then use the regex feature to extract file extensions. However, since the query limits itself to 500 I'm not getting all of the file extensions as they don't all appear in the 500 documents returned by the query.

**Comment by cr42** [comment]
I think this is now covered by #8527

**Comment by aurimasplu** [comment]
+1

**Comment by Daphneitec** [comment]
+1

**Comment by junneyang** [comment]
+1 for return size configurable

**Comment by beingyash** [comment]
I believe this has not yet been considered till Grafana 7. Do we have any update @torkelo ?
