### ISSUE TITLE
FR: Refresh Template Variable on time range change

### ISSUE THREAD

**Issue by NickG123** [grafana/grafana#3427]
The "Refresh on load" option for template values seems to work well.
However, it would be nice if it was also possible to refresh when the timespan changes.
For example, if I have metric A, for which the most recent data is from 5 seconds ago, and metric B, for which the most recent data is from 1 day ago, I run into the following issue:
I set up the template while my time span is set to "last 5 minutes".  The results of the query at this point only contains metric A.  If I later change my time span to "last 7 days", it still only displays metric A in the template, even though the result of the query at this point would be both metric A and metric B

**Comment by torkelo** [comment]
template variables are designed to be invariant on time. So only refreshed on dashboard load.

**Comment by NickG123** [comment]
That seems odd to me.  That means that if I have a dashboard where the time span is set to "last 5 minutes", and I have had it open for an hour, I will have template variables for metrics that have not had any data in the last 5 minutes.  If someone else were to then open the same dashboard with the same time span setting ("last 5 minutes") they would only see a subset of the template options that I see (those that have data for the last 5 minutes).

Let me explain my specific use case.

I am using logstash in order to ship application logs into elasticsearch.  I am using the new Table panel in order to visualize the log data.  This is great because I can set up template variables for the source application of the log if I want to see logs for that specific application.  Having the application list dynamically loaded from an elasticsearch query is perfect, because it means I don't have to update the template every time I add a new application.

This means that if I set my timespan to "last 5 minutes" then I only see applications which have logged in the last 5 minutes.  This is fine, except that if I then want to see the logs of an application that has not logged in a while, I can't simply switch it to "last 24 hours" (or something similar), because the application list is not updated.

As a result, I have to change the timespan, save the dashboard and refresh in order to view logs from these applications.  This would especially a problem for users who only have read access to the page - they won't be able to save the dashboard, and thus there is no way for them to view the logs for those applications.

**Comment by torkelo** [comment]
Grafana and the templating feature was designed for time series databases. Metric key inspection queries are usually not time related (they can be, but usually not). This requirement might change with the advent of Elasticsearch which does not have a separate metric meta database

**Comment by henridf** [comment]
I just ran into this problem. I'm storing time series in ElasticSearch, and using a template with a query like `{"find": "terms", "field": "my_field_name"}`. It took me a while to figure out that the time filter was the reason for some keys not showing up.... I had no idea that a time filter was even being used until I looked at the ES query that was being made.

**Comment by henridf** [comment]
What about just dropping the range filter when doing the ES query to get a list of terms? That seems like it would fix the above problem, and if my understanding of @torkelo's comment above is correct, it would also be in line with what is done for time-series datasources.

**Comment by henridf** [comment]
Another approach might be to expose the time range boundaries as variables (e.g. `$from` and `$to`) so that they can be used as filters in the template query.

**Comment by mtanda** [comment]
It might be https://github.com/grafana/grafana/issues/1909.

**Comment by NickG123** [comment]
Dropping the range filter would work if you didn't want it to be dynamic.  You could make one expensive query once to get all contents and then never refresh the template.  However it does not solve my issue, as I would like newly added data to automatically get added to template.

To me the best solution is to make the template refresh within the time range any time the data is refreshed, as I have done in my pull request.

**Comment by robison** [comment]
+1, this would be amazing to be able to use Grafana as a single pane of glass for pulling in Elasticsearch table data with time ranges.

**Comment by sslupsky** [comment]
I have this problem as well.  I am filling a template variable with an ES query and I would like that variable to be independent of the time.

+1 to have the option to specify:

bound the query by the time range specified in the upper right corner
bound the query by an absolute time range specified in the template settings
specify how the values are refreshed (page load, time change, etc)

**Comment by NickG123** [comment]
Fixed by #4281
