### ISSUE TITLE
Panel settings search bar not behaving correctly

### ISSUE THREAD

**Issue by Knocks83** [grafana/grafana#34282]
**What happened**:
When writing something in the search bar of the panel (in my case a Time series) settings, after the first letter it loses focus on the search bar and starts typing somewhere else.

https://user-images.githubusercontent.com/22529815/118652833-43567500-b7e7-11eb-92be-9af84e3e6243.mp4

**What you expected to happen**:
I expected it to keep writing in the search bar

**How to reproduce it (as minimally and precisely as possible)**:
Go to a panel settings, start searching.

**Environment**:
- Grafana version: Grafana 8.0.0 beta 1
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 - Firefox

**Comment by torkelo** [comment]
This autoFocus={true} needs to be changed: https://github.com/grafana/grafana/blob/8cfbee1e11122bfe4991dcbbbc391470006963fa/public/app/plugins/panel/timeseries/SpanNullsEditor.tsx#L53
