### ISSUE TITLE
Cannot process annotations when meta.dataTopic is set to `annotations`

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#34284]
**What happened**:

I followed this guide to setup annotations https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/

It is not very detailed so I inspected a grafana source code to see what data are supported.

Seems like when datasource issues a query for annotations, it runs through `runRequest::processResponsePacket()`.

There it pushes data from packet to `annotations` array 

```ts
    if (packet.data && packet.data.length) {
      for (const dataItem of packet.data) {
        if (dataItem.meta?.dataTopic === DataTopic.Annotations) {
          annotations.push(dataItem);
          continue;
        }
```

However, it does not get parsed further and Annotations editor says there are no events:

![image](https://user-images.githubusercontent.com/327717/118655062-7994f400-b7e9-11eb-9b4a-03dbfc4f7b7c.png)

`annotations_srv` pipes `runRequest` result and expects `panelData.series` to be present (`if (!panelData.series) {`)

So when I tried to satisfy the condition above `if (dataItem.meta?.dataTopic === DataTopic.Annotations) {`, `standardAnnotationSupport::getAnnotationsFromData()` is called with empty array.

**What you expected to happen**:

What is the `meta.dataTopic` good for then?

**How to reproduce it (as minimally and precisely as possible)**:

This is datasource response

```json
[
   {
      "meta":{
         "dataTopic":"annotations"
      },
      "fields":[
         {
            "name":"Start",
            "type":"time",
            "values":[
               1621287170000,
               1621289567000,
               1621289588000,
               1621291694000,
               1621293947000,
               1621297642000,
               1621300700000,
               1621300708000,
               1621304060000
            ]
         },
         {
            "name":"End",
            "type":"time",
            "values":[
               1621289560000,
               1621291690000,
               1621289592000,
               1621293940000,
               1621297550000,
               1621300694000,
               1621301219000,
               1621304052000,
               1621307666000
            ]
         }
      ]
   }
]
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4
- OS Grafana is installed on: macos
- User OS & Browser: chrome latest

**Comment by torkelo** [comment]
The dataTopic DataTopic.Annotations is only for data sources that want to return annotation/exemplars along with metric data (so same metric query can return both metrics and annotations/exemplars).  

For an annotation query defined in the annotations list of dashboard settings, those queries should return data using the normal data topic.

**Comment by simPod** [comment]
Thank you for explaining.
