### ISSUE TITLE
Cloudwatch plugin results seem to be capped

### ISSUE THREAD

**Issue by DanHoerst** [grafana/grafana#3429]
We have a fairly large infrastructure in AWS. When I attempt to search for a dimensions value I seem to be receiving a set number of results. Is there a cap to the amount of dimension values that Grafana will return? Even attempting to filter (either by search or regex) the values only filter through the returned values.

For example, we have about 300 AutoScaling groups with the term "Admin" in them. When I attempt to create a variable from the following, only two admin groups return:

    query: dimension_values(us-east-1, AWS/EC2, CPUUtilization)
    regex: .*Admin.*

I am seeing the same behavior when I attempt to manually type "Admin" into the dimensions (autopopulate) of the query.

**Comment by torkelo** [comment]
@mtanda do you have any knowledge of a cap/limit ?

**Comment by mtanda** [comment]
@torkelo @DanHoerst 
Sorry, I don't consider such a large infrastructure.

The ListMetrics API cap result, it is reason why all dimensions returned.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_ListMetrics.html
> Up to 500 results are returned for any one call. To retrieve further results, use returned NextToken values with subsequent ListMetrics operations.

I already PR for this, upgrade to aws-sdk-go version 1.0, using "Paginators" will solve this.
https://github.com/grafana/grafana/pull/3294

**Comment by DanHoerst** [comment]
Thanks @mtanda @torkelo. How long do you think we should expect until this is in a release? Looking forward to it!

**Comment by mtanda** [comment]
Thanks for merging PR.

@DanHoerst torkelo will create beta release package.
When package is ready, please test it in your environment :-)

**Comment by DanHoerst** [comment]
Hey @mtanda @torkelo . I pulled the nightly build from here https://grafanarel.s3.amazonaws.com/builds/grafana-2.6.0-beta2.linux-x64.tar.gz, installed and tested it. 

In the query section of the dashboard I now see all of the values. It takes a bit of time to load but I think that's expected given the size of our infrastructure.

However, when I attempt to set up a template variable for any AWS related value, it now only shows None. Previously it would show the matches capping at the number of results. I've tried deleting the variable and recreating it as well, and it only shows None.

Please let me know if you need any more info and thanks for your help.

**Comment by torkelo** [comment]
@DanHoerst whats your template variable query?

**Comment by DanHoerst** [comment]
`dimension_values(us-east-1, AWS/EC2, CPUUtilization)`

**Comment by mtanda** [comment]
Sorry, I changed the query interface by torkelo request.
https://github.com/grafana/grafana/pull/3205#discussion_r44522654
https://github.com/grafana/grafana/commit/eb5822bc7c766a746246770930167bd2284f7249

Please specify dimension_key parameter.

**Comment by DanHoerst** [comment]
Hey @mtanda. Thanks. Adding that dimension key works. It also reinforced the need for #3477 as it seems to load even slower via template variables than it does via normal search. To be clear, it's definitely manageable - it's just "slow".

Thanks again for your help. This is great.

**Comment by mtanda** [comment]
@DanHoerst I’m glad to help you!! :smile:
