### ISSUE TITLE
Handle boolean values

### ISSUE THREAD

**Issue by mirkocomparetti-synesis** [grafana/grafana#34296]
**What would you like to be added**:
At the moment, boolean support is lacking
![image](https://user-images.githubusercontent.com/34926125/118664840-18255300-b7f2-11eb-94a5-dd433b36a2d6.png)
which means that a query that returns a bool value cannot be displayed as long as the datatype is converted to integer, for instance.
Boolean values should be handled as those are a valid usecase in the data world
**Why is this needed**:
Storing values that represent a state like "error yes/no", "door open/close", ... which can be represented easily and more human friendly with a boolean value, now cannot be used as is in grafana, while this should be handled as those are a viable option.

**Comment by torkelo** [comment]
what data source are you using? 

Seems like the panel can handle it:

![Screenshot from 2021-05-18 16-23-20](https://user-images.githubusercontent.com/10999/118668735-6c7e0200-b7f5-11eb-95a2-d7d39e2a4684.png)

**Comment by mirkocomparetti-synesis** [comment]
I'm using influxdb v2 now, and this returns the column as "boolean" not a string with value true, which is similar to what you showed.
What happens if you write "true,false,some"?

**Comment by mirkocomparetti-synesis** [comment]
@torkelo I tried to reproduce your findings, but I have a different result and a different UI (I'm using the latest OSS)
![image](https://user-images.githubusercontent.com/34926125/118682083-693c4380-b800-11eb-8186-c21b57f3371c.png)
Where am I wrong?
Thanks!

**Comment by torkelo** [comment]
supporting boolean data in csv metric values scenario was recently added (v8)

**Comment by ryantxu** [comment]
@mirkocomparetti-synesis  it looks like you are on a 7x build -- the boolean support is in 8x -- you can try the beta, or run from main

**Comment by mirkocomparetti-synesis** [comment]
Ok, very well then! I'm using the stable 7.X, that is the reason why!
Thanks!

**Comment by mirkocomparetti-synesis** [comment]
Hello @torkelo @ryantxu,
I'm trying now with the beta OSS and this is what I get
![image](https://user-images.githubusercontent.com/34926125/118768805-b9a6b600-b87f-11eb-8b13-4cbe8c8360a1.png)
I cannot make it work even with 8; also I tested your example and it does not work as well.

**Comment by mirkocomparetti-synesis** [comment]
Hello @torkelo
You closed the ticket before I managed to add the comment about my test with 8 beta.
Let me know what I'm missing in my tests.

Thanks!

**Comment by aengusrooneygrafana** [comment]
@gabor  as discussed - as we have replicated this, can you please review this ticket for a fix?  Thanks @mirkocomparetti-synesis for raising with us again.

**Comment by gabor** [comment]
hi @mirkocomparetti-synesis i was able to reproduce your problem and i'm working on a fix.

**Comment by gabor** [comment]
for reference, the bug is in the influxdb code that parses boolean-responses from the server.

**Comment by mirkocomparetti-synesis** [comment]
Thanks a lot @aengusrooneygrafana, @gabor!
