### ISSUE TITLE
Help use case: programmatically change query

### ISSUE THREAD

**Issue by hmilkovi** [grafana/grafana#3430]
Greetings,
I need to programmatically change query of graph. Is it possible if so how?

Use case:
Custom html table with buttons that change graph query on click event.

Thanks :)

**Comment by torkelo** [comment]
yes, you can access the queries from the dashboard model. 

There is no docs for this though. 

first query first row first panel
$scope.dashboard.rows[0].panels[0].targets[0]

**Comment by hmilkovi** [comment]
Can I do it from panel or must I implement my own method in template html?
Graph will automatic refresh or?

**Comment by torkelo** [comment]
you will have to implement a custom panel and call the correct grafana services to refresh the other panel
