### ISSUE TITLE
LDAP authentication doesn't work with userPrincipalName as username

### ISSUE THREAD

**Issue by kennethmac2000** [grafana/grafana#3431]
LDAP authentication doesn't seem to work properly in my environment when using userPrincipalName as the value of username. That is, with the following values set in ldap.toml:

search_filter = "(userPrincipalName=%s)"

[servers.attributes]
...
username = "userPrincipalName"
email =  "mail"
...

It works the first time a particular user tries to log in, but then on a subsequent login attempts you see an error like this in grafana.log:
[login.go:101 LoginPost()] [E] Error while trying to authenticate user: UNIQUE constraint failed: user.email

It seems Grafana is trying to create a new user every time, instead of realising that the user trying to login already exists. Thus, the unique constraint on the email field is failing.

When, eg, sAMAccountName is used as the value of username, everything works fine - both on login attempt 1, and on subsequent login attempts.

The values of these two attributes for me are:

userPrincipalName: Kenneth.MacArthur@company.com
sAMAccountName: Kenneth.MacArthur

Could the issue be the at sign in userPrincipalName?

It is slightly unclear exactly how the matching of existing users takes place - it seems like a little bit of black magic. ;) Otherwise, I would be happy to help debug this further.

I'm running Grafana v2.5.0.

**Comment by torkelo** [comment]
matching is done on email and username

**Comment by torkelo** [comment]
you can enable logging and see what ldap attributes are fetched. I guess the email property is not being matched correctly. Check that your ldap email property is correct or set it to userPrincipalName

**Comment by kennethmac2000** [comment]
When you say matching is done on email and username, do you mean that the values of *both* have to match for an LDAP user to be considered an existing user (ie, it's an AND condition)?

If so, why have a unique constraint on email by itself?

**Comment by kennethmac2000** [comment]
I have verbose LDAP logging enabled. I am setting Grafana's "email" property to the value of the "mail" attribute from our LDAP server, and the value of this attribute looks fine. As mentioned, everything works fine in any case when the "username" property is set to "sAMAccountName" from LDAP (without changing anything relating to the "email" property), so this doesn't actually look like it has anything to do with "email".

**Comment by torkelo** [comment]
whats ldap logging output? (showing the ldap attributes fetched during login)

**Comment by JulienChampseix** [comment]
Got the same issue:

using this config:
bind_dn = "cn=%s,cn=Users,dc=foo,dc=com" 
search_filter = "(cn=%s)"
search_base_dns = ["cn=Users,dc=foo,dc=com"] 
=> it's works but it's not the real username ldap represented by sAMAccountName

if using sAMAccountName
bind_dn = "sAMAccountName=%s,cn=Users,dc=foo,dc=com" 
search_filter = "(sAMAccountName=%s)"
search_base_dns = ["cn=Users,dc=foo,dc=com"] 

=> dont work and got error : 
[I] LDAP initial bind failed, LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903CF, comment: AcceptSecurityContext error, data 52e, v2580
[login.go:98 LoginPost()] [E] Invalid username or password: Invalid Username or Password

**Comment by JulienChampseix** [comment]
any idea @torkelo ?

**Comment by torkelo** [comment]
no :( your ldap server does not like binding on sAMAccountName

**Comment by torkelo** [comment]
if you have ldap admin/anonymous user can set bind_password or bind_dn to blank. Then the search (user lookup) will take place and the user authentication bind will be done on the search hit

**Comment by JulienChampseix** [comment]
@torkelo you're right sAMAccountName not supported for direct bind_dn so i was trying an other way over userPrincipalName.

This command ldapsearch works using julien@foo.com (which is the userPrincipalName of course i entered manually the pwd) : 
ldapsearch -x -h ldap.foo.com -D "julien@foo.com" -W -b "cn=users,dc=foo,dc=com" -s sub "(cn=*)" cn mail sn
Enter LDAP Password:

Meaning userPrincipalName is supported by our ldap (active directory).

How can i setup ldap.toml for use userPrincipalName for the bind_dn ? 

i tried:
bind_dn = "userPrincipalName=%s,cn=Users,dc=pws,dc=com"
search_filter = "(userPrincipalName=%s)"
search_base_dns = ["cn=Users,dc=pws,dc=com"]

still having : 
[I] LDAP initial bind failed, LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903CF, comment: AcceptSecurityContext error, data 52e, v2580
[login.go:98 LoginPost()] [E] Invalid username or password: Invalid Username or Password

if it's working over ldapserach grafana should be able to connect over it also.

Hope you could provide me your help on it.

**Comment by JulienChampseix** [comment]
@kennethmac2000 which config you had in your ldap.toml, can you paste it here ?

**Comment by torkelo** [comment]
set bind_dn= and bind_password= to blank (empty) to make grafana search for the user and bind on the dn after search (the dn will be full dn for the found user)

**Comment by JulienChampseix** [comment]
@torkelo i have tried setup like you mentionned : 

bind_dn = ''
bind_password = ''
search_filter = "(userPrincipalName=%s)"
search_base_dns = ["cn=Users,dc=foo,dc=com"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "userPrincipalName"
member_of = "memberOf"
email =  "mail"

or 
#bind_dn = ''
#bind_password = ''
search_filter = "(userPrincipalName=%s)"
search_base_dns = ["cn=Users,dc=foo,dc=com"]
[servers.attributes]
name = "givenName"
surname = "sn"
username = "userPrincipalName"
member_of = "memberOf"
email =  "mail"

Both dont work and getting this error : 
[E] Error while trying to authenticate user: LDAP Result Code 1 "Operations Error": 000004DC: LdapErr: DSID-0C090748, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580

**Comment by torkelo** [comment]
if you cannot leave them blank (meaning anonymous access is not allowed), specify a bind_dn for user and bind_dn password to use for search

**Comment by torkelo** [comment]
that is do not use "%s" in the bind_dn,  specify a user that can be used for the initial bind,

**Comment by JulienChampseix** [comment]
i would avoid to put a user/password in clear text in a config which really not secure. I would have a dynamic bind_dn using the login/password entered by user. 
Could be a bug inside the ldap.go connector ?

**Comment by torkelo** [comment]
no, you need to specify a user in order to search ldap (since you do not have anonymous access to search), there is no bug, as your ldap does support binding on sAMAccountName you need to search for the user first (using sAMAccountName, then do the bind)

**Comment by JulienChampseix** [comment]
i can't do based on userPrincipalName ? instead of sAMAccountName.
With userPrincipalName, my ldap support as exposed to you over ldapsearch

**Comment by torkelo** [comment]
@JulienChampseix I am not sure I understand what your saying. 

I though you tried but your ldap does not allow you to bind on the property you want to bind on? I am confused. Anyway you should be able to search on any property, then grafana will bind on the ldap dn entry for the found user.

**Comment by JulienChampseix** [comment]
In fact originally i tried to use sAMAccountName (instead of cn which is the default) using this config:
  bind_dn = "sAMAccountName=%s,cn=Users,dc=foo,dc=com"
  search_filter = "(sAMAccountName=%s)"
  search_base_dns = ["cn=Users,dc=foo,dc=com"]
  [servers.attributes]
  name = "givenName"
  surname = "sn"
  username = "sAMAccountName"
  member_of = "memberOf"
  email = "mail"

 but my ldap dont support it (confirmed using ldapsearch).

So second step i wanted try to use userPrincipalName:

  bind_dn = "userPrincipalName=%s,cn=Users,dc=pws,dc=com"
  search_filter = "(userPrincipalName=%s)"
  search_base_dns = ["cn=Users,dc=pws,dc=com"]
  [servers.attributes]
  name = "givenName"
  surname = "sn"
  username = "userPrincipalName"
  member_of = "memberOf"
  email = "mail"

 but here i got the grafana error : 
  [E] Error while trying to authenticate user: LDAP Result Code 1 "Operations Error": 000004DC: LdapErr: DSID-0C090748, comment: In order to perform this operation a successful bind must be completed on the connection., data 0, v2580

 Note for this second step the command line ldapsearch works meaning the ldap support base_dn using userPrincipalName but not over grafana.
 Command ldapsearch used/working: ldapsearch -x -h ldap.foo.com -D "julien@foo.com" -W -b "cn=users,dc=foo,dc=com" -s sub "(cn=*)" cn mail sn

So i would be able to configure grafana (ldap.toml) using userPrincipalName with bind_dn but dont success for the moment. That's why i would your help for fix it or detect if it's hidden bug.

**Comment by JulienChampseix** [comment]
@torkelo 
any waiting your feedback on my previous comment, i had an other one question. When enabling verbose in ldap, is it possible to expose also the bindPath used ? which is used there https://github.com/grafana/grafana/blob/master/pkg/login/ldap.go#L256

**Comment by JulienChampseix** [comment]
@torkelo how to reopen this issue ? as atm we can't use LDAP authentication with userPrincipalName

**Comment by torkelo** [comment]
where do you specify userPrincipalName here? 

```
ldapsearch -x -h ldap.foo.com -D "julien@foo.com" -W -b "cn=users,dc=foo,dc=com" -s sub "(cn=*)" cn mail sn
```

Did you try to specify search user, and search on userPrincipalName?   (static search user used for search only)

**Comment by JulienChampseix** [comment]
-D "julien@foo.com" here is the bind DN which is userPrincipalName field
-b "cn=users,dc=foo,dc=com" is the base dn for search which the ldap tree

As it's working from command line, it should work over grafana(ldap.toml) also with the right config. But config posted previously i tested dont works.

**Comment by JulienChampseix** [comment]
@torkelo possible to add more information into the verbose mode of the ldap (like bind_dn used during connection, search used, ..) That will be very usefull and could easily for you to add those additionnal log in the 2.6 version which is in beta.

**Comment by torkelo** [comment]
how can "julien@foo.com" be a bind dn, does not look like a dn path. 

if now bind password or bind_dn is specified a second bind is done on the DN of the search hit. OR if bind_dn does not contain `%s`, meaning its a static dn for a user used only to be able search ldap. 

The DN used for the second bind (it it needed), is the canonical dn path for the search hit, meaning the dn path the ldap server returns as the full path for search hit. 

you can add more logging here if you need more:
https://github.com/grafana/grafana/blob/3b67a6a222cbcff6e7b9d85dfbeec13d9a74dab0/pkg/login/ldap.go

**Comment by kennethmac2000** [comment]
I'm not sure if this conversation is still about the original issue any more, but to clarify the setup in my environment:

- There is a bind DN (and password) for the search user, which is a service account that we created specifically for this purpose
- The search filter used in the first bind is "(userPrincipalName=%s)"
- userPrincipalName is mapped to the username attribute in [servers.attributes]

To emphasise again, if I was happy to use sAMAccountName as the search filter/username value, this would already be working. But for some reason, things don't work when I use userPrincipalName.

In my environment, sAMAccountName is kenneth.macarthur whereas userPrincipalName is kenneth.macarthur@company.com. It couldn't be something as simple as the at sign in userPrincipalName could it?

**Comment by torkelo** [comment]
what do you mean by "It couldn't be something as simple as the at sign in userPrincipalName could it?" 

The `%s` in the search filter will be replaced with the username you specify on the login page. 

When your search filter is using userPrincipalName is there a search hit? If you have verbose logging enabled it should report ldap attributes for the search hit. It just the second bind that is failing?

**Comment by kennethmac2000** [comment]
I took quite some time to write the original issue, and I don't think I can explain things again any better.

Logging in with userPrincipalName set to be the username works *the first time* (ie, before the user exists in Grafana's database), but not on subsequent login attempts.

Logging in with sAMAccountName set to be the username works both the first time and on subsequent login attempts.

Logging in with an incorrect userPrincipalName or sAMAccountName value (or an incorrect password) does not work, at any time.

To be absolutely clear, it's not the second bind that's failing, it's the second *login attempt* - but only when the username is set to userPrincipalName.

There is nothing output to the log, even with verbose LDAP logging on, which tells you specifically what is going on on that second login attempt.

The log does tell you that you're trying to create a user with the same e-mail address as an existing user - which would makes sense if we were indeed trying to create a new user here. But we're not.

A user record was already created on the first login attempt, and on login attempt 2, with the same login credentials, I would assume Grafana should be determining that the user logging in already has a record in the Grafana user database and not be trying to create another user record.

And indeed it does this correctly when we use sAMAccountName as the username.

The only two key differences between sAMAccountName and userPrincipalName in my environment is that userPrincipalName is longer, and it contains an at sign.

Grafana obviously has to do some matching to determine whether the user logging in is a new user or an existing user. Could the reason this matching logic appears to not be working correctly with userPrincipalName values be that the value is either too long or that it contains an at sign?

**Comment by torkelo** [comment]
@kennethmac2000 I have yet to see your output after turning on verbose logging. That way I can see what ldap attributes is fetched (email, username etc)

**Comment by kennethmac2000** [comment]
Hi, I'm not sure this will be of much use, but here goes... (I've replaced any company references with made-up strings of the same length)

With username = sAMAccountName

 DN: (string) (len=63) "CN=Kenneth MacArthur,OU=Users,OU=abcdef,DC=abcdefghijk,DC=local",
 FirstName: (string) (len=7) "Kenneth",
 LastName: (string) (len=9) "MacArthur",
 Username: (string) (len=17) "Kenneth.MacArthur",
 Email: (string) (len=26) "kenneth.macarthur@abcd.com",
 MemberOf: ([]string) (len=41 cap=64) {
 ...
 }

With username = userPrincipalName

 DN: (string) (len=63) "CN=Kenneth MacArthur,OU=Users,OU=abcdef,DC=abcdefghijk,DC=local",
 FirstName: (string) (len=7) "Kenneth",
 LastName: (string) (len=9) "MacArthur",
 Username: (string) (len=26) "Kenneth.MacArthur@abcd.com",
 Email: (string) (len=26) "kenneth.macarthur@abcd.com",
 MemberOf: ([]string) (len=41 cap=64) {
 ...
 }

**Comment by kennethmac2000** [comment]
For clarity, to restate the key point from my message above:

"It's not the second bind that's failing, it's the second login attempt - but only when the username is set to userPrincipalName."

The first login attempt for a particular user works with both sAMAccountName and userPrincipalName.

**Comment by torkelo** [comment]
Yes, I have understood that. But have asked for ldap log output 10 times now :( it's the key to understanding it. The error makes me believe the mail attribute is returning an empty string or something that is causing issues

**Comment by kennethmac2000** [comment]
Isn't what I pasted in the message above LDAP log output? It's from /var/log/grafana/grafana.log with LDAP verbose logging turned on. Otherwise, I'm not sure what to provide?

**Comment by kennethmac2000** [comment]
Is the output from /var/log/grafana/grafana.log pasted above sufficient @torkelo, or should I add something more?

**Comment by l0ckt1ght** [comment]
I know this is an old issue, but I was having the same problem trying to use samaccountname as the username. When using anything other than "cn" for "username in my ldap.toml, the username is blank in grafana under the users tab. when using "cn" the value of "cn" gets used as the username and shows up under the users tab in the web interface. I'd be more than willing to share my whole log if it helps, but since this is a closed issue I figured I wouldn't post it unless requested. 

Note: This does not actually affect the users ability to login with samaccountname, just what's displayed for username in the users tab in the web interface

**Comment by pckls** [comment]
We have a situation where our sAMAccountName is a different username than what is included in userPrincipalName. I was trying to allow people to login with either, and using a dynamic bind_dn, but I could not get this to work. I can however get this to work for either case.

Login works using sAMAccountName (eg. pckls/password):

```
grafana::ldap_cfg:
  servers:
    - host: 'ad.example.org'
      bind_dn: 'DOMAIN\%s'
      search_filter: "(sAMAccountName=%s)"
      search_base_dns: ["dc=example,dc=org"]
  'servers.attributes':
    name: 'givenName'
    surname: 'sn'
    username: 'sAMAccountName'
    member_of: 'memberOf'
    email: 'mail'
```

Login works using userPrincipalName (eg. tom.pickles@example.org/password):

```
grafana::ldap_cfg:
  servers:
    - host: 'ad.example.org'
      bind_dn: '%s'
      search_filter: "(userPrincipalName=%s)"
      search_base_dns: ["dc=example,dc=org"]
  'servers.attributes':
    name: 'givenName'
    surname: 'sn'
    username: 'sAMAccountName'
    member_of: 'memberOf'
    email: 'mail'
```

The config isn't direct from the TOML file it's from Hiera but you get the point.

Anyway just thought I would mention it as I did get userPrincipalName working, just not as well as sAMAccountName.
