### ISSUE TITLE
Light theme does not show values on top of the bart in the (beta) bar chart (Grafana v8.0.0-beta1)

### ISSUE THREAD

**Issue by Grrrolf** [grafana/grafana#34335]
This concerns the new [bar chart](https://github.com/grafana/grafana/issues/30741) (#30741)

**What happened**:
When using the new (beta) bar chart plugin in Grafana v8.0.0-beta1 (84203aaff8), it will not show the values on the top of the bars when the light theme is in use. However, when using the dark theme, it shows the values on top of the bars.

With the dark theme:
![image](https://user-images.githubusercontent.com/10052794/118713768-9d286080-b822-11eb-9a01-2b28866eba1d.png)

With the light theme: 
![image](https://user-images.githubusercontent.com/10052794/118713851-bdf0b600-b822-11eb-9ba7-f80e359013b9.png)

I have set the "Show values" to "Always":
![image](https://user-images.githubusercontent.com/10052794/118714683-f6908f80-b822-11eb-86da-2ba03661c6e1.png)

**What you expected to happen**:
I expected the values shown in a colour which can actually be seen when using the light theme.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a bar chart 
2. set "Show values" to "Always"
3. switch to the light theme, if you haven't already.

**Anything else we need to know?**:
No.

**Environment**:
- Grafana version: Grafana v8.0.0-beta1 (84203aaff8)
- Data source type & version: PostgreSQL data source plugin supplied with Grafana v8.0.0-beta1 (84203aaff8)
- OS Grafana is installed on: Mac OS Big Sur
- User OS & Browser: Mac OS + Google Chrome
- Grafana plugins: Only default plugins.
- Others:

**Comment by leeoniya** [comment]
think https://github.com/grafana/grafana/pull/34229 addresses this, along with sizing improvements.
