### ISSUE TITLE
Do not wrap plugin's metric editor with class="tight-form-container"

### ISSUE THREAD

**Issue by olfway** [grafana/grafana#3433]
Right now plugin's provided metric editor loaded with:
```
<div class="tight-form-container">
<query-editor-loader ng-repeat="target in panel.targets" ng-class="{'tight-form-disabled': target.hide}" >
</query-editor-loader>
</div>
```
this "tight-form-container" causes visual artifacts if you want to display anything but the table.

and if you want to display a table you can add this class youself

**Comment by torkelo** [comment]
Each editor must stack in a similar way so you can mix different data sources, that class wraps all queries so it cannot be in each query
