### ISSUE TITLE
aliasbynode doesn't support spaces

### ISSUE THREAD

**Issue by vpaul** [grafana/grafana#3434]
Hi there,

I'm using grafana to visualize a custom metrics. Metrics are being renamed sourced from an external. The external may contain mostly all characters including spaces and special symbols. On a graph I'm able to observe full metric name perfectly like:

source.name with spaces.metric.type.

But when I do aliasbynode(1) it shows only "name" but not full "name with spaces" as expected. Obviously, workaround is to use aliassub but it would be probably better aliasbynode support spaces and special symbols.

Thank you,

Pavel

**Comment by torkelo** [comment]
AliasByNode is a graphite function, the logic is handled in the graphite backend. Please redirect this question to the graphite project.
