### ISSUE TITLE
display chart for different time range.

### ISSUE THREAD

**Issue by joyhope** [grafana/grafana#3435]
I use influxdb.  
It is easy to show one item in the time range.  e.g CPU in time 1 ~ time 2. 
Is it possible to display the same metric but with different time range in the same chart?
cpu  time1   ~ time 1 + 1 hour
cpu  time2   ~ time 2 + 1 hour 
cpu  time3   ~ time 3 + 1 hour

**Comment by torkelo** [comment]
Graphite has a timeShift function, InfluxDB does not have this feature. I think there is an open feature request in the InfluxDB project to support this.
