### ISSUE TITLE
get environment metainfo in backend plugin

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#34356]
**What would you like to be added**:
When the backend plug-in starts, please inject some meta information into the execution environment of the plug-in, such as grafana version, edition etc.

**Why is this needed**:
When our backend plugin working, it reporting some meta info while getting data from business services.
We need to decide whether to maintain a specific version based on this basic information.

Metadata can be obtained through  [grafanaBootData](https://grafana.com/docs/grafana/latest/packages_api/runtime/grafanabootconfig/) in the web page，but this information will be lost when the user uses the alarm function. 

Can you add this feature？Or is there any other way to solve this problem ?

**Comment by MeetzhDing** [comment]
And when datasource.ts query function is called, request param can only be transferred to the backend through the [targets array field](https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L123). 

It's hard to transferr common info to backend sdk.

**Comment by marefr** [comment]
It's already supported via environment variables, see code https://github.com/grafana/grafana/blob/7b17801047ae79e1725639e502bd06fd9171f141/pkg/plugins/backendplugin/manager/manager.go#L65
