### ISSUE TITLE
AzureMonitor: Improve Azure Resource Graph docs

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#34361]
[This](https://github.com/grafana/grafana/pull/33293) PR had to be merged to main before the Azure Resource Graph docs were approved by the @grafana/docs-squad. This issue can be closed when a new PR that addresses the [problems](https://github.com/grafana/grafana/pull/33293) described here is merged to main. 

Also, I'd like the docs to describe what macros are available.

**Comment by achatterjee-grafana** [comment]
@joshhunt is working on rewriting the AzureMonitor docs.
