### ISSUE TITLE
Members of a team granted Admin rights cannot create template variables

### ISSUE THREAD

**Issue by NikolayTsvetkov** [grafana/grafana#34407]
**What happened**:
Members of a team that is granted with Admin rights on a dashboard are not able to create template variables, even though they can create plots and save the dashboard. If the team is set with Editor privileges the problem is not present.
I consider this as a bug because the Admin rights should provide more privileges than Editor and also because editing plots and dashboard works without problem.

**What you expected to happen**:
Admins should be able to create/edit template variables.

**How to reproduce it (as minimally and precisely as possible)**:
The problem is easily reproducible following the next steps:
1. Create User with Viewer privileges
2. Create Team and add the user to the team
3. Set the team with Admin privileges on a particular dashboard
4. Login with the newly created User and try to create template variable in the dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: 
- OS Grafana is installed on: CentOS 8
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you show a screenshot or video of this? We have no other reports like this, and not seeing any permissions checks on this the Variables section in dashboards settings

**Comment by NikolayTsvetkov** [comment]
![Screenshot 2021-05-20 at 13 19 28](https://user-images.githubusercontent.com/24571856/118975248-1a171f80-b974-11eb-8931-eef2b8896240.png)
Hi @torkelo and thank you for the immediate reply !
Please find the screenshot of the exception when I try to save some dummy custom variable using this user. Meanwhile creating/modifying plots is not a problem. As I mentioned, if the Team permissions are changed from Admin to Editor, it works without problem. The User itself is defined with Viewer privileges in the organisation.

**Comment by ashharrison90** [comment]
hey @NikolayTsvetkov 👋 

thanks for raising this. it looks like this has been fixed at some point as i can't reproduce it in the latest version of Grafana 8. if you're able to upgrade (or have upgraded already) and can let me know if the problem is resolved that would be great. 

if there's any issues, let me know and we can reopen this issue.

thanks! 😄
