### ISSUE TITLE
Influx ability to hide serie when fetched from one query

### ISSUE THREAD

**Issue by eMerzh** [grafana/grafana#3443]
whith influx you have the ability to select more than 1 column in a query...
and it goes as individual series in grafana, which is great.

The issue is that you can't click on 1 of the series to hide it,like if it was 2 separate query...
please add this possibility :)

Thanks and keep up the good work!

**Comment by torkelo** [comment]
if you want to hide it, then separate it into two queries. The eye feature is for disabling queries.

**Comment by eMerzh** [comment]
i don't want to hide it permanently (otherwise i wouldn't added it) but "hide" like described here:

![Hide doc](http://docs.grafana.org/img/v1/graph_overview.png ) at upper_95

**Comment by torkelo** [comment]
but you can do what is described in the image, just shift-click

**Comment by eMerzh** [comment]
yeah but that disable them both at the same time.... unfortunately.... (not sure it's a bug or a feature request)
