### ISSUE TITLE
"Logs for this span" link broken for Zipkin datasource

### ISSUE THREAD

**Issue by alanmcg** [grafana/grafana#34440]
Just added a Zipkin datasource and expected to be able to open the matching log in a split view as per the docs but the log explorer view is opened with the query set to just {} and therefore fails with error:

`parse error at line 1, col 2: syntax error: unexpected }, expecting IDENTIFIER `

![image](https://user-images.githubusercontent.com/43033315/118856652-7a0bb880-b8d7-11eb-9b29-fd230a0d2419.png)

- Grafana version: 7.5.5
- Data source type & version: loki 2.2.1

**Comment by zoltanbedi** [comment]
This might be due to misconfiguration. You have to provide tags https://grafana.com/docs/grafana/latest/datasources/zipkin/#trace-to-logs that are on your spans so a loki query can be created from that.
