### ISSUE TITLE
TimeSeries: legend toggle weirdness (google sheets?)

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#34449]
ran into this while trying to repro https://github.com/grafana/grafana/issues/34166

attempting to toggle one series, turns off both:

https://user-images.githubusercontent.com/43234/118894101-390ca780-b8c9-11eb-98a3-002e644da919.mp4

this does not seem to affect other gdev dashboards, but gonna set `beta2` milestone to get an extra pair of eyes on it. feel free to push to beta3 or later if non-blocker.

dashboard:

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 197,
  "links": [],
  "panels": [
    {
      "datasource": "Google Sheets",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "graph": false,
              "legend": false,
              "tooltip": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "cacheDurationSeconds": 0,
          "refId": "A",
          "spreadsheet": "1A1CmxbwIOSFU53Q8BZuKh6HzR8IFJbBxeWmuSXFkvyI"
        },
        {
          "cacheDurationSeconds": 0,
          "hide": false,
          "refId": "B",
          "spreadsheet": "1iJmWxwto_-fyKmZsNpWFNT62VjmhEyA26xboDAf87Yg"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": false,
  "schemaVersion": 30,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2021-05-17T04:59:30.000Z",
    "to": "2021-05-17T05:00:30.000Z"
  },
  "timepicker": {},
  "timezone": "utc",
  "title": "spanNulls-thresh-bug",
  "uid": "6wYTFnqMz",
  "version": 3
}
```

**Comment by dominicpoeschko** [comment]
![issue](https://user-images.githubusercontent.com/45942148/119523436-0bb67280-bd7d-11eb-9692-63d93571a74c.gif)

Hi having the same Issue.
Has to do with the new Time Series Plugin.
Happens only when there is a override on the Display name.

Hope this is helpful.

Greeting
Dominic

**Comment by dprokop** [comment]
@dominicpoeschko the issue you are reporting is the one already reported here: https://github.com/grafana/grafana/issues/31364

@leeoniya can you create a repro dashboard on play.grafana.com for an investigation? Does it happen to any spreadsheets you use or just a this particular one?

**Comment by dprokop** [comment]
@leeoniya I'm still investigating this but my current findings are that the display name in the legend is different from the one that's actually returned from the getDisplayName. There is some very weird thing going on. The display name for the legend gets calculated twice. First time it's calculated correctly: A Time, B Rh but with the second pass the names/query ref are revrsed: Time A, RH B. When the matcher kicks in it tries to match on names the names from the first calculation, however the options passed to the matcher use the later calculated names. Here's some recording of the debug session for the legend rendering: 

https://user-images.githubusercontent.com/2376619/119977913-41e03600-bfb9-11eb-8d78-4807ce712b39.mp4

Looking some more into this now.
