### ISSUE TITLE
Convenient exploring of logs from Loki, if I want to see not the last logs' lines

### ISSUE THREAD

**Issue by shootkin** [grafana/grafana#34468]
**What would you like to be added**:

When I explore Loki through grafana, If I set limit, say, "5000" for log lines,  then I see latest 5000 log lines perfectly well.
But what if I want to see previous 5000 log lines? If limit is set to more than 5000 lines it slows down the browser and grafana. 

Now I have to manually set appropriate time range in order to see previous 5000 lines of logs. 
So I think it would be great if I could just did single click to some button in order to see previous 5000 log lines.

**Why is this needed**:
Because now the grafana doesn't have convenient method to explore previous (not last) lines of logs.

**Comment by zoltanbedi** [comment]
Have you tried the new logs navigation? https://grafana.com/docs/grafana/next/explore/logs-integration/#logs-navigation I think it should solve your problem.

**Comment by zoltanbedi** [comment]
This is a new feature that is coming in Grafana 8, you can try it out by upgrading to Grafana 8.0.0-beta1.

**Comment by shootkin** [comment]
Thanks a lot for the information!
