### ISSUE TITLE
Getting  mean instead of last value in single stat panel

### ISSUE THREAD

**Issue by SadE54** [grafana/grafana#3447]
I have a measurement in Influxdb that's in fact an incremental counter ( so an integer value).
I just want to get the last value, so in Grafana I have this query  : 
FROM pump_on
WHERE
SELECT last  counter
math expr
AS 
as expr
GROUP BY time auto no fill

The problem it's the value displayed in the panel seems to be the mean of the series , with a decimal.
Maybe I made a mistake in my query , but 'last' seems self explanatory Oo

**Comment by pakozm** [comment]
I suffered the same problem and I solved it removing the GROUP BY clause, just like this:

```
SELECT last("value") FROM "seriesname" WHERE $timeFilter
```

But I think this behavior is not weird and unexpected.

**Comment by torkelo** [comment]
what value have you selected in the singlestat options tab, have you selected Current there?

![Uploading image.png…]()

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/11625774/c3eb0b7a-9cdd-11e5-94f7-cfda2e894d7d.png)

**Comment by SadE54** [comment]
Ok i got it , I thought it was related to the query, so I missed this particular field in top panl options . 
Thx !

**Comment by pakozm** [comment]
Nice, it was really helpful :-) for me also
