### ISSUE TITLE
Allow selecting Azure subscription as scope instead of workspaces only

### ISSUE THREAD

**Issue by Dammi87** [grafana/grafana#34482]
Hi all

I've been trying out the Azure Monitor datasource which is quite nice, but often limiting. Case in point the fact we are limited to use workspaces as the query scope for Logs.

In the portal, I'm able to choose subscription level scope
![image](https://user-images.githubusercontent.com/23643258/118962319-c6e1a480-b954-11eb-9246-3b1cd6e8ff53.png)

While in Grafana 7.x you are limited to use workspaces. 

I had a look at grafana/grafana-dev:8.1.0-23054pre and tried my datasource there and I see a lot of improvements! However, it still looks like I'm unable to query on a subscription level.
![image](https://user-images.githubusercontent.com/23643258/118962764-3eafcf00-b955-11eb-902c-274d06f304f5.png)

Is this a limitation in Grafana or something else?

**Comment by joshhunt** [comment]
Hi @Dammi87 - thanks for raising this feature request!

For 8.0 our goal with the resource picker was to expand Logs to query any single (supported) resource - basically maintain parity with existing feature set while updating the UI.

"Multi-select" - being able to select Subscriptions and Resource Groups, as well as multiple supported resources, like the Azure Portal - is something we want to do very soon. It unlocks some really cool capabilities with Azure Monitor :) 

If you don't mind sharing, what use cases would you like this for? Do you have some sample queries you would like to visualise?

**Comment by Dammi87** [comment]
Hi @joshhunt - Thanks for your reply 

So we use Azure cloud services extensively in my company and we've been wanting to create a dashboard to monitor the health of all the dashboards. We are already using Grafana for an another use-case to great success so it made sense to try to do the same with the monitoring solution.

I haven't dug to much into it, but we are using a version of this dashboard [here](https://grafana.com/grafana/dashboards/10538) but that is of course only a single event hub. We want to create a tabular overview of resources (i.e use the Grafana repeat function). When I ran into the issue that I couldn't select the service across the subscription instead of workspace, I kinda shelved the work to be honest.

But to give an example of what we wanted to do was, for example, copying the "Dead Letter" KPI for all event hubs horizontally across the screen. Query for all event hubs available on the portal (that are already sending logs) like the top query is showing. This would allow us to add a variable to the dashboard for easier filtering of event hubs etc.

Generally speaking, we kinda like the freedom of raw queries as opposed to UI based functionality :)

**Comment by joshhunt** [comment]
Good news - turns out this was incredibly easy to implement (the work was just on optimising the UI) and it will be going out in 8.0-beta3 next week :) 

Thanks for raising the request and prompting us to look into how to support this!
