### ISSUE TITLE
Panel Resize: Changes doesn't reflect after changing panel sizes in inspect JSON and click on apply

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#34483]
**What happened**: To edit the size of the panel with particular dimensions, I have to select the Inspect > Panel JSON and then adjust the width and height in JSON.  But the changes are not reflected even after clicking on apply. I have to save & reload the page to see the changes.

**What you expected to happen**: After applying size in  Inspect > Panel JSON the changes should reflect without dashboard save and reload.

**How to reproduce it (as minimally and precisely as possible)**: Go to panel JSON and edit the **h** and **w** in the following property of panel JSON:

 `"gridPos": {
   "h": 4,
   "w": 24,
   "x": 0,
   "y": 3
 },`

**Anything else we need to know?**: Able to reproduce in Play Grafana.

**Environment**: Any
- Grafana version:  7.2 and above
- Data source type & version: Any
- OS Grafana is installed on: Any
- User OS & Browser: Any
- Grafana plugins: ANy
- Others:

**Comment by oscarkilhed** [comment]
I agree, the expected behavior is for the panel to update on apply.

**Comment by hugohaggmark** [comment]
Maybe we should remove the Apply button in inspect JSON tab and point users to the Dashboard JSON instead that does a full page reload when applied?

**Comment by axelavargas** [comment]
> Maybe we should remove the Apply button in inspect JSON tab and point users to the Dashboard JSON instead that does a full page reload when applied?

Thank you @hugohaggmark :), at the end we decided to use the fix made on the PR. It means for now we only support changing `gridPos` using Panel Inspect JSON, and in the future we will make a bigger refactor to fix changing plugin type. I have already created another issue #35479

**Comment by satyatechy** [comment]
Hi @axelavargas, 
we have ported the changes and found the following regression:
When we duplicate the panel we can't see the panel, we have to save and refresh the dashboard to see the duplicated panel. 
Please check and provide the fix.

**Comment by torkelo** [comment]
@satyatechy fixed by https://github.com/grafana/grafana/pull/35906

**Comment by satyatechy** [comment]
@torkelo the actual issue is reproducing again. Unable to update the size of the panel. I think something broke after this #35906 fix.

**Comment by torkelo** [comment]
strange, I can updated gridPos and have it take effect

**Comment by satyatechy** [comment]
We are using 7.5.5 now. Will that make difference?

**Comment by torkelo** [comment]
@satyatechy well yes, the fix is only part of 8.0.3

**Comment by satyatechy** [comment]
@torkelo We are getting the following error when we replace the panel JSON in edit mode(We do this to copy the panel from another session where the copy panel from UI doesn't work)
<img width="372" alt="error1" src="https://user-images.githubusercontent.com/65600879/122925947-f7b65e80-d384-11eb-8fcb-64526f2bc3e4.png">

**Comment by torkelo** [comment]
@satyatechy what did you update?

**Comment by satyatechy** [comment]
> @satyatechy what did you update?

we ported #35906 changes. Panel resizing and panel duplicating both works fine but when we replace panel JSON with other panel's JSON in edit mode this error occurs "An unexpected error happened"

**Comment by torkelo** [comment]
@satyatechy yea, if you want to replace a full panel you need to use Dashboard settings / JSON, the panel json only supports small json edits (where panel type & id is preserved)
