### ISSUE TITLE
Unified Alerting: "Run Queries" does not show full error

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#34506]
**What happened**:
Do not see full error returned when using "Run Queries"

![image](https://user-images.githubusercontent.com/1692624/118992056-4b7ef380-b952-11eb-8408-ce6077b13e77.png)

**What you expected to happen**:
See the full Error message

**How to reproduce it (as minimally and precisely as possible)**:

Do something to cause an error (for example, see image).

**Comment by kylebrandt** [comment]
The `rpc error: code = InvalidArgument desc = ` part of the string will be cleaned up (removed) with https://github.com/grafana/grafana/pull/34738

**Comment by mckn** [comment]
> The `rpc error: code = InvalidArgument desc = ` part of the string will be cleaned up (removed) with #34738

So we can close this issue?

**Comment by kylebrandt** [comment]
@mckn Nope we will need to show both the error and message properties, I just cleaned up what was in the error property some.
