### ISSUE TITLE
Beta 2.6 Query editor not "selecting" data from drop down list

### ISSUE THREAD

**Issue by jhhayden** [grafana/grafana#3450]
Using influxdb, can manually type data into select box bot mouse action fails to do anything.

![screen shot 2015-12-07 at 5 00 56 pm](https://cloud.githubusercontent.com/assets/1423588/11641094/4f8c0a46-9d04-11e5-8a83-b42273d49bc9.png)

**Comment by discoduck2x** [comment]
+1

**Comment by torkelo** [comment]
this is fixed in master :) https://github.com/grafana/grafana/issues/3428
