### ISSUE TITLE
Time and string fields get unique background color in v8 

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#34519]
**What happened**: Table panel option Cell display mode more specific options Color text or Color backgroud (solid) do not work as expected. Expected one color across all columns but colors are different. Same dashboard on 7.5.7 does not have this issue.

8.0.0-beta2:
![image](https://user-images.githubusercontent.com/66313770/119004078-899a0880-b98e-11eb-9287-4ea4f3634fcf.png)

7.5.7
![image](https://user-images.githubusercontent.com/66313770/119004441-e0074700-b98e-11eb-80bd-aa8cb525f79d.png)

**What you expected to happen**: One color across all columns if option Color background (solid) is selected.

**How to reproduce it (as minimally and precisely as possible)**: Table panel with Color background (solid) turned on.

**Anything else we need to know?**: /

**Environment**:
- Grafana version: 8.0.0-beta2 (2021-05-20)
- Data source type & version: TimescaleDB
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: /
- Others: /

**Comment by ivanahuckova** [comment]
@edin008 That is not how the cell display mode works. It changes the colors of each field based on its values and values across the whole table/your tresholds. This is example from Grafana 7.5.7. As you can see, the fields have different colors based on its value. 
![image](https://user-images.githubusercontent.com/30407135/119316025-bdb74700-bc76-11eb-94cc-06a2dd6af908.png)

You can check out this feature requests that might be related to what you are expecting:
https://github.com/grafana/grafana/issues/27542
https://github.com/grafana/grafana/issues/26383

**Comment by edin008** [comment]
> @edin008 That is not how the cell display mode works. It changes the colors of each field based on its values and values across the whole table/your tresholds. This is example from Grafana 7.5.7. As you can see, the fields have different colors based on its value.
> ![image](https://user-images.githubusercontent.com/30407135/119316025-bdb74700-bc76-11eb-94cc-06a2dd6af908.png)
> 
> You can check out this feature requests that might be related to what you are expecting:
> #27542
> #26383

Hi,

Thank you for your answer. It was a bit strange that there is a difference between 7.5.7 and 8.0.0-beta2 even tho I am using the same dashboard with same settings. Below is a bit more explanation about this in case it is a bug.

The problem is not in version 7.5.7, it works here as expected. I have one color and I expect whole table / all cells in that color.
![image](https://user-images.githubusercontent.com/66313770/119370858-14904100-bcb6-11eb-912b-591ddb819c63.png)
![image](https://user-images.githubusercontent.com/66313770/119371454-bc0d7380-bcb6-11eb-872c-456a42d28a72.png)

The problem is in 8.0.0-beta2, with using same dashboard and same settings I get different cell colors.
![image](https://user-images.githubusercontent.com/66313770/119371298-91bbb600-bcb6-11eb-9a3a-16f33b06a90b.png)
![image](https://user-images.githubusercontent.com/66313770/119371499-c9c2f900-bcb6-11eb-846b-7ce9d0419834.png)

**Comment by ivanahuckova** [comment]
Can you please share your Panel JSON

**Comment by edin008** [comment]
> Can you please share your Panel JSON

Here is Grafana dashboard with included sample data. Selected datasource can be any MySQL database formatted as table.
[Table Cell Color-1622206152193.zip](https://github.com/grafana/grafana/files/6560921/Table.Cell.Color-1622206152193.zip)

Here is Panel JSON as well: 
[Panel JSON.zip](https://github.com/grafana/grafana/files/6560984/Panel.JSON.zip)

Grafana 7.5.7:
![image](https://user-images.githubusercontent.com/66313770/119986897-b2d91b00-bfc4-11eb-8e77-3d47942b270f.png)

Grafana 8.0.0-beta2:
![image](https://user-images.githubusercontent.com/66313770/119986989-cedcbc80-bfc4-11eb-8364-de0122ee78a8.png)

**Comment by torkelo** [comment]
this is a side effect of the default color logic @ryantxu added in v8 , https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/field/displayProcessor.ts#L141
