### ISSUE TITLE
Beta 2.6 Incorrect loading of query with derivative function 

### ISSUE THREAD

**Issue by mpergament** [grafana/grafana#3452]
"query": "SELECT derivative(mean(\"value\"), 5s) FROM \"jnpr.analyticsd\" WHERE \"device\" = 'qfx5100-01-48s' AND \"interface\" = 'xe-0_0_10' AND \"type\" = 'traffic-stats.rxucpkt' AND $timeFilter GROUP BY time(10s), \"type\"",

after importing config 
[Juniper Network Agent Interface Dashboard for qfx5100-01-48s-1449563188056.zip](https://github.com/grafana/grafana/files/55172/Juniper.Network.Agent.Interface.Dashboard.for.qfx5100-01-48s-1449563188056.zip)

is shown in Grafana as :
"query": "SELECT mean(\"value\") FROM \"jnpr.analyticsd\" WHERE \"device\" = 'qfx5100-01-48s' AND \"interface\" = 'xe-0_0_10' AND \"type\" = 'traffic-stats.rxucpkt' AND $timeFilter GROUP BY time($interval), \"type\"",

**Comment by torkelo** [comment]
what do you mean shown? The dashboard you pasted has raw queries. (ie using text box), you cannot do changes in text box and have that carry over to the ui query editor.

**Comment by mpergament** [comment]
If you export dashboard that is what I get. If I use ui query editor and
export dashboard, it always has raw queries in it.

Am Dienstag, 8. Dezember 2015 schrieb Torkel Ödegaard :

**Comment by torkelo** [comment]
I am not I understand. If build a dashboard with graphs using the InfluxDB query editor, then save or export it, then load / import the dashboard, open any graph in the editor I can still see the queries in the editor mode (not in raw text box mode). So I cant replicate the scenario where all queries turn from UI editor mode to raw text editor mode after export.

**Comment by mpergament** [comment]
I will make a video

Am Dienstag, 8. Dezember 2015 schrieb Torkel Ödegaard :

**Comment by mpergament** [comment]
I close this one as it is a problem in my script (did not consider new changes in 2.6)
