### ISSUE TITLE
Malformed Data Link - version 8b1 and 8b2

### ISSUE THREAD

**Issue by lux4rd0** [grafana/grafana#34528]
**What happened**:

Created a datalink using variables from a table view (with transformations) that results in broken URLs

**What you expected to happen**:

Proper link URL formations

**How to reproduce it (as minimally and precisely as possible)**:

Create data link:

Title:
`Show Hourly Forecast for ${__data.fields.day_start_local}`

URL:
`/d/${__dashboard.uid}﻿﻿/?var-forecast_day_num=﻿${__data.fields["day_num"]}﻿&var-display_date=${__data.fields.day_start_local}`

Results in the following URLs:

version 8b1 and 8b2 - `https://grafana.lux4rd0.com/d/lux4rd0labs_weatherflow_14%EF%BB%BF%EF%BB%BF/?var-forecast_day_num=%EF%BB%BF22%EF%BB%BF&var-display_date=Saturday,%20May%2022nd`

version 7.5.6 - `http://grafana.tylephony.com/d/lux4rd0labs_weatherflow_14/?var-forecast_day_num=22&var-display_date=Saturday,%20May%2022nd`

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.0-beta2 (9d4c719205)
- Data source type & version:
- OS Grafana is installed on: CentOS / Docker
- User OS & Browser: MacOS Chrome - Version 90.0.4430.212 (Official Build) (x86_64)
- Grafana plugins:
- Others:

**Comment by jackw** [comment]
The strings posted above in the reproduction steps contain `zero width no break space` characters.

<img width="1043" alt="Screenshot 2021-06-01 at 16 16 55" src="https://user-images.githubusercontent.com/73201/120338811-db2e8580-c2f4-11eb-946e-b4d1c96dffbc.png">

Them appearing in URLs in `v8.0.0-beta1` appears to be a side-effect of updating the [braintree/sanitize-url](https://github.com/braintree/sanitize-url/pull/32#discussion_r617637466) package in #33551 as downgrading the package back to 4.0.0 strips the `zero width no break space` characters.

I'm not entirely sure how we should handle this (the character is generally used for line-wrapping long words) so probably shouldn't make it's way into a URL.
