### ISSUE TITLE
Beta 2.6 Group By is only available on first Query 

### ISSUE THREAD

**Issue by mpergament** [grafana/grafana#3453]
All subsequent queries do not have Group By row:
![grafanagroupbyerror](https://cloud.githubusercontent.com/assets/13856387/11651858/47617bcc-9d94-11e5-90df-be0e838d478c.jpg)

**Comment by torkelo** [comment]
is this an old dashboard that you opened? or is it when trying to create a new dashboard?

**Comment by mpergament** [comment]
I see this problem if I try to create one from scratch.

**Comment by torkelo** [comment]
so if you click the "+ Query" button you get a query without a group by?

**Comment by torkelo** [comment]
ah, I see the issue, the "Group By" label text is only visible on first query. Will fix

**Comment by mpergament** [comment]
Exactly

Am Dienstag, 8. Dezember 2015 schrieb Torkel Ödegaard :

**Comment by mpergament** [comment]
Thanks!
