### ISSUE TITLE
Graph/Timeseries > Axes > Decimals "Auto": does not recognize decimal places

### ISSUE THREAD

**Issue by Herr-Sepp** [grafana/grafana#34546]
**What happened**:
Influx 2.0 Datasource
Query with data that has 4 decimal places

The axe and the tooltip is rounded to full numbers
![image](https://user-images.githubusercontent.com/10489458/119160704-d21df880-ba58-11eb-8df5-13d625f65050.png)

**What you expected to happen**:
auto recognizes the decimal places
![image](https://user-images.githubusercontent.com/10489458/119160804-e95ce600-ba58-11eb-88e0-a3863c21b0ab.png)

**Environment**:
- Grafana version: 7.5.7
- Data source type & version: Influx 2.0
- OS Grafana is installed on: Docker Linux
- User OS & Browser: Windows 10 Vivaldi/Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you show the raw data in inspector and the json DataFrame structure

**Comment by Herr-Sepp** [comment]
![image](https://user-images.githubusercontent.com/10489458/119181901-85dfb200-ba72-11eb-9236-6ce13aa68162.png)

With Field > standard option > Unit : "local format"
![image](https://user-images.githubusercontent.com/10489458/119181970-a0199000-ba72-11eb-8fc5-10c638f4726c.png)

With Field > standard option > Unit :"none"
![image](https://user-images.githubusercontent.com/10489458/119182164-dd7e1d80-ba72-11eb-8ef6-c048f30dbc03.png)

But with both (none and local format) the auto-option for decimals does not work for me

DataFrame Structure:

`[
  {
    "length": 13,
    "refId": "A",
    "name": "metrics",
    "meta": {
      "executedQueryString": "from(bucket: \"performance-monitor\")\r\n  |> range(start: 2021-05-06T18:23:53Z, stop: 2021-05-21T18:23:53Z)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"metrics\")\r\n  |> filter(fn: (r) => r[\"systemdatasource\"] =~ /DBGP/)\r\n  |> filter(fn: (r) => r[\"branch\"] =~ /(Trunk|Trunk_pallet_changer|6\\.3)/)\r\n  |> filter(fn: (r) => r[\"scenario\"] =~ /Fahrwerk/)\r\n  |> filter(fn: (r) => r[\"_field\"] == \"value_throughput_time\")\r\n  |> drop(columns: [\"_field\"])\r\n  |> rename(columns: {scenario: \"_field\"})"
    },
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {
          "unit": "none"
        }
      },
      {
        "name": "Fahrwerk",
        "type": "number",
        "config": {
          "unit": "none"
        },
        "labels": {
          "branch": "6.3",
          "systemdatasource": "DBGP"
        }
      }
    ]
  },
  {
    "length": 4,
    "refId": "A",
    "name": "metrics",
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {
          "unit": "none"
        }
      },
      {
        "name": "Fahrwerk",
        "type": "number",
        "config": {
          "unit": "none"
        },
        "labels": {
          "branch": "Trunk",
          "systemdatasource": "DBGP"
        }
      }
    ]
  },
  {
    "length": 2,
    "refId": "A",
    "name": "metrics",
    "fields": [
      {
        "name": "Time",
        "type": "time",
        "config": {
          "unit": "none"
        }
      },
      {
        "name": "Fahrwerk",
        "type": "number",
        "config": {
          "unit": "none"
        },
        "labels": {
          "branch": "Trunk_pallet_changer",
          "systemdatasource": "DBGP"
        }
      }
    ]
  }
]`

**Comment by torkelo** [comment]
the auto decimals logic does not handle this specific scenario, where you have a high number with very small (or no) differences. You will need to specify the decimals manually for a case like this
