### ISSUE TITLE
Displaying specific columns of table

### ISSUE THREAD

**Issue by VladislavYak** [grafana/grafana#34545]
**What would you like to be added**:
Hey :)
I have a table considering a lot of columns in it.
My issue that most of time i don't want to dispay all columns. It would be great if i can just pick some columns to show.
I would name it as "Selector": a panel where i can click on specific columns and they would be displayed (also having button "show all" would be great)

If this feature already exists, please refer me to it

**Why is this needed**:
It's not convinient to scroll the whole table to see just 2 or 3 columns
![too_sparse](https://user-images.githubusercontent.com/69644103/119144079-fd044e80-ba50-11eb-9801-059caed1d0db.gif)

**Comment by torkelo** [comment]
Add a filter transform in the transform tab (in panel edit), or add the organize fields transform. With this transform you can reorder and hide columns

**Comment by csanc47** [comment]
thanks bro!
