### ISSUE TITLE
Sumseries function

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#3454]
Hello @torkelo,

I have some data that i need to sum up. I am using sumseries() function and that is working fine.
But when i extend the time frame then data only come up for first 24hours.
Is there any default value sat to this function or do i need to change something?

Thanks in advance,

Himanshu

**Comment by torkelo** [comment]
Check your graphite storage schema configuration

**Comment by Himanshu-pupneja** [comment]
Thanks for your response @torkelo .
Data is displayed for all the time without sumseries function. And when i used the sumseries() data comes up for only first 24 hours..
Retention is also set to 100days.

I am not sure it is related to storage schema or not.

Thanks & Regards,
Himanshu
