### ISSUE TITLE
Prometheus data source - Custom HTTP headers are cached and changes to the same header are not effective

### ISSUE THREAD

**Issue by vishiy** [grafana/grafana#34554]
In prometheus data source, when custom HTTP headers were modified, queries are still made with the older header values.
ex;-
1) In the prometheus data source add a custom http header with a value. say myheader, and its value as myheadervalue.
2) Save and test and use it on dashboard(s)
3) Go back to the datasource and change the myheadervalue to myheadervalueupdated. Save & test.
4) Observe queries using the data source still using the old her value (myheadervalue).

Looks this is cached some where in the proxy ?
Grafana v7.5.4

**Comment by torkelo** [comment]
Strange, are you seeing the old value being cached for a long time?

**Comment by torkelo** [comment]
Because the current ds proxy cache is only 5 seconds, so must be something wrong either with the cache timeout or this being cached in some other way

**Comment by vishiy** [comment]
I have tried up to 30 mins.

**Comment by ivanahuckova** [comment]
Hello @vishiy! We did some bug fixes for custom headers that were part of Grafana 8.0 release. I tried to reproduce this issue with Grafana 8.0, but I wasn't able to reproduce it. Therefore it seems to be fixed. Could you please upgrade to Grafana 8 and try again? I will close this issue, but feel free to reopen if you encounter this issue again.
