### ISSUE TITLE
Panels missing occasionally when embeded via iframe

### ISSUE THREAD

**Issue by SeanTse** [grafana/grafana#34569]
**What happened**:
When embeding dashboards via iframe, some panels are missing (those on the bottom of a dashboard whose height exceeds the size of my screen). These panels will come back when changing time range or refreshing a few times.

**What you expected to happen**:
Dashboards can be displayed normally when embeded.
**How to reproduce it (as minimally and precisely as possible)**:
A long enough dashboard being embeded in an iframe
**Anything else we need to know?**:
Grafana is proxyed behind an nginx (version: 1.19.5)
**Environment**:
- Grafana version: 7.5.7
- Data source type & version: Prometheus v2.26.0
- OS Grafana is installed on: Installed with Docker (grafana/grafana:7.5.7)
- User OS & Browser: Windows 10 & Chrome 90.0.4430.212
- Grafana plugins: Statusmap 0.4.1 & Pie Chart 1.6.1
- Others:

**Comment by Elfo404** [comment]
Hi @SeanTse,

Do you get any error in the browser console?

**Comment by SeanTse** [comment]
Hi @Elfo404 
It turns out that the initial height of our iframes was not enough to fit the panels, so we simply set it higher to solve this problem. I think we can close it. Thanks for your help anyway.

**Comment by Elfo404** [comment]
Awesome! 

Closing this them, but please feel free to comment again if you experience any issue and we can reopen it
