### ISSUE TITLE
Incorrect alias/tag replacement with 2.6 beta1

### ISSUE THREAD

**Issue by commarla** [grafana/grafana#3456]
Hi,

Only the first alias is used when I have a multiplie queries graph. 
I have 3 hosts selected and want to display paging IN & OUT so I made 2 queries with 2 aliases but all metrics took the first alias : 

![image](https://cloud.githubusercontent.com/assets/4509360/11655831/1ea6848a-9db1-11e5-9b84-4e01e9e6f672.png)

I should have : 
SLMUPP1WAS05 IN
SLMUPP1WAS12 IN
SLMUPP1WAS23 IN
SLMUPP1WAS05 OUT
SLMUPP1WAS12 OUT
SLMUPP1WAS23 OUT

Instead of : 
SLMUPP1WAS05 IN
SLMUPP1WAS12 IN
SLMUPP1WAS23 IN
SLMUPP1WAS05 IN
SLMUPP1WAS12 IN
SLMUPP1WAS23 IN

I have tried to change the first alias and all have been updated : 
![image](https://cloud.githubusercontent.com/assets/4509360/11655903/a4109db8-9db1-11e5-9fce-30d6ae8cff1d.png)

I am using OpenTSDB and Grafana version: 2.6.0-beta1, commit: v2.6.0-beta1, build date: 2015-12-04 15:45:06.

Thanks,

Laurent

**Comment by torkelo** [comment]
This is a problem with OpenTSDB, not always possible to match query to returned series.  Has been reported many times, I think there is a fix in OpenTSDB master (will come in next OpenTSDB release)

**Comment by commarla** [comment]
You right, my bad, I didn't search deep enough.

Thanks,
