### ISSUE TITLE
Conditional Coloring of Table Cells

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana#34579]
Hi everyone!

**What would you like to be added**:
I would like to use thresholds with tables to colorize cells by conditions based on their relative values

**Why is this needed**:
For example: i have two cells - A and B. And I want B-cell  background color to be changed when its value greater then A-cell value ( B > A condition, or B == 0.8 * A, or B==0 when A!=0, or whatever).
Something like conditions in Excel spreadsheets. I need it for statistics.

Now I cannot find a way to do something like this.

**Comment by torkelo** [comment]
duplicate of https://github.com/grafana/grafana/issues/11418
