### ISSUE TITLE
need a health check entry path to Grafana that won't generate session

### ISSUE THREAD

**Issue by Dieken** [grafana/grafana#3457]
I'm using HAProxy as load balancer for my Grafana cluster,   and Grafana cluster use MySQL as session storage. HAProxy does http check against Grafana every 2 seconds,  the problem is I can't find an entry path that Grafana doesn't generate session,  I wouldn't like the health check force Grafana to create tons of garbage session in MySQL.

Could you provide a /status entry path without session, or do I miss some magic entry path?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3302  will add that aspect to this issue :)
