### ISSUE TITLE
BarChart: Support for data links 

### ISSUE THREAD

**Issue by andreee94** [grafana/grafana#34608]
Datalinks in the BarChart panel are not shown even if configured both in the general option and in the override one.

![image](https://user-images.githubusercontent.com/5384246/119380639-465ad500-bcc1-11eb-995e-77fb901a1e20.png)

PROTIP: record your screen and attach it as a gif to showcase the issue.

**What happened**:
Datalink is not working in the BarChart panel

**What you expected to happen**:
I expect to be able to drilldown through the datalink option in the BarChart panel

**How to reproduce it (as minimally and precisely as possible)**:
- Create a BarChart panel
- Set the datalink option
- No link appears in the panel while clicking on an item

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta2
- Data source type & version: Loki
- OS Grafana is installed on: k3s on linux 
- User OS & Browser: linux & firefox
- Grafana plugins: 
![image](https://user-images.githubusercontent.com/5384246/119382540-722a8a80-bcc2-11eb-89b1-2510730f0150.png)

- Others: -

**Comment by dprokop** [comment]
Closing in favor of https://github.com/grafana/grafana/issues/36709
