### ISSUE TITLE
Problem upgradegrafana v.6.5.3 to v.75.3

### ISSUE THREAD

**Issue by jvs87** [grafana/grafana#34601]
**What happened**:
Im stuck with the upgrade of grafana from version 6.5.3 to 7.5.3. I've done a copy from grafana.db, default.ini and plugins before do the upgrade.

I use .tar archive ( I've no conectivity out ) to decompress files on actual grafana path ( 6.5.3 ) following https://grafana.com/docs/grafana/v7.4/installation/debian/ instructions.

When try to start grafana-server it stucks in migration :

`t=2021-05-24T17:25:28+0200 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2021-05-24T17:25:28+0200 lvl=info msg="Starting DB migrations" logger=migrator
t=2021-05-24T17:25:28+0200 lvl=info msg="Executing migration" logger=migrator id="Add unique index datasource_org_id_uid"
t=2021-05-24T17:25:28+0200 lvl=eror msg="Executing migration failed" logger=migrator id="Add unique index datasource_org_id_uid" error="UNIQUE constraint failed: data_source.org_id, data_source.uid"
t=2021-05-24T17:25:28+0200 lvl=eror msg="Exec failed" logger=migrator error="UNIQUE constraint failed: data_source.org_id, data_source.uid" sql="CREATE UNIQUE INDEX `UQE_data_source_org_id_uid` ON `data_source` (`org_id`,`uid`);"
`
Ive been following https://github.com/grafana/grafana/issues/27837 but not result.

**What you expected to happen**:
Upgrading version works.
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?*

**Environment**:
- Grafana version: 6.5.3 to 7.5.3
- OS Grafana is installed on: centos 7
- Others:

**Comment by torkelo** [comment]
Try upgrading to v7 or v7.1 before going to v7.5

**Comment by jvs87** [comment]
I have tried to v7.1 and stucks in the same error :

` Migration failed err: Failed to roll back transaction due to error: %!s(<nil>): UNIQUE constraint failed: data_source.org_id, data_source.uid`

**Comment by jvs87** [comment]
Finally i could do the upgrade !
It was a problem from grafana.db, some values were "0" at column uid in table data_source . Changing the uid in base org_id columns solved the problem.

Thanks
