### ISSUE TITLE
Can the Mysql session table be added empty to the database on the default install?

### ISSUE THREAD

**Issue by pythianali** [grafana/grafana#3461]
Hi,

I'm having an issue with Grafana 2.5.  We are deploying via puppet (bfraser/grafana) and it is being back ended by a RDS Mysql instance.  The deployment is ok but we would like to automatically add the missing session table to the RDS instance.

It can be added manually, but we are deploying with CF/ASG/Puppet.    The problem we have is that we are trying to ensure this table exists prior to the Grafana install.  We tried the puppetlabs/mysql with the mysql::db directive but that invokes mysql::server which isn't installed locally in our case.  Additionally the puppetlabs/aws can manage RDS but we are unable to load the table data easily on deploy.

The main issue isn't really a Grafana one but it can be solved easily here if the session table was added by default when Grafana is installed.   Otherwise we will need to take this up with the other mysql and aws module developers.  Is there any reason why that table isn't included by default?  I didn't see any mention of this in the roadmap.

Thoughts?

**Comment by torkelo** [comment]
yes, this should be very easy to do.
