### ISSUE TITLE
Alerting: Cross team testing

### ISSUE THREAD

**Issue by papagian** [grafana/grafana#34628]
Please add any found issues here:

**Comment by zoltanbedi** [comment]
Can't delete alert label - see the video attached

https://user-images.githubusercontent.com/13729989/119819324-8b188300-bef0-11eb-9d7f-f848206ba3fa.mp4

**Comment by aocenas** [comment]
Silencing:
In general seems to work fine but there are some UX nitpicks:
![Screenshot from 2021-05-31 13-14-24](https://user-images.githubusercontent.com/1014802/120186040-4142dc00-c213-11eb-9dbf-fb1def991fda.png)

This state with what it is actually silencing is shown for only small amount of time around when the notification would be sent and after maybe a minute it goes back to 
![Screenshot from 2021-05-31 13-15-42](https://user-images.githubusercontent.com/1014802/120186113-5cade700-c213-11eb-9ebd-54bff402c2fc.png)
Seems like the state is reset at that moment. I would expect this to cumulatively count number of notifications it silenced or just number of alerts that it targets and that info to be persistent.

![Screenshot from 2021-05-31 13-14-39](https://user-images.githubusercontent.com/1014802/120186227-836c1d80-c213-11eb-82d5-d118630ec0c9.png)
In the silence tab when there is info what it silenced there is this button but it does not do anything when clicked.

**Comment by aocenas** [comment]
Migration: Works
just a small nitpick. The migrated contact points have totally generated name so even though before I had a point named `me` it migrated to `autogen-panel-recv-ijVuzMeGz` would be nice to keep at least partially of the original name.

**Comment by aocenas** [comment]
There is an `Alert list` panel type that should show all alerts in the system (or filtered ones) but id does not seem to work with new alerting. The `test alert` shown is actually deleted so I assume it shows the data from old alerting:
![Screenshot from 2021-05-31 15-26-47](https://user-images.githubusercontent.com/1014802/120200736-ef0ab680-c224-11eb-8d32-fb851ebcc711.png)
