### ISSUE TITLE
Suggestions to Grafana 8.1

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#34623]
**What would you like to be added**:
Plugin Table:
- adding a row coloring (by value or text from column)
- possibilty freeze some columns like in Excel
- column name height (text in two rows in column name)
- adding text size (title and value)
- adding row width

Plugin Bar Chart:
- adding stack columns option
- adding option (values on the bar, above bar, on the bottom bar)

**Why is this needed**:
I think this is very important changes and will help many people who using Grafana on daily basis :)

**Comment by oscarkilhed** [comment]
Maybe you could split this request up into multiple issues? 

Happy to report that both your requests on the Bar Chart is already being worked on.

**Comment by kale1d0code** [comment]
one feature which would be extremely useful in the table plugin
which used to be supported in version 6 of Grafana
would be the ability to hide a column but still use the data from it
to enable using a hidden ID column to use in data links

**Comment by torkelo** [comment]
Many of these exist as separate feature requests, also moving feature requests to https://github.com/grafana/grafana/discussions
