### ISSUE TITLE
Transfrom: FilterByValue transform crashes panel edit when field is not found 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#34626]
To replicate 

* Open this dashboard & panel in panel edit: http://localhost:3000/d/WFlOM-jM1/barchart-value-text-sizing?orgId=1&editPanel=13&tab=transform 

here we try to lookup a field by name: 
https://github.com/grafana/grafana/blob/main/public/app/core/components/TransformersUI/FilterByValueTransformer/FilterByValueFilterEditor.tsx#L24 

That can be undefined if it's not found but it is passed to a function that expects it.

**Comment by daniellee** [comment]
A dashboard that recreates the error: https://g80-beta.grafana.net/d/u2BcGyqMz/transformcrash?orgId=1&editPanel=2&tab=query

Click on the transformations tab to crash.
