### ISSUE TITLE
Grafana image direct render get 404

### ISSUE THREAD

**Issue by ldkingvivi** [grafana/grafana#3463]
Hi Guys,

We are using version 2.5, and looks like the image direct render link has 404 page not found error, but if we remove the "/render" part, it works fine as general sharing

this is broken for direct image:
http://10.12.17.16:8080/render/dashboard-solo/db/some_status?panelId=23&fullscreen&from=now-1h&to=now&width=1000&height=500

This is working as general url sharing:
http://10.12.17.16:8080/dashboard-solo/db/some_status?panelId=23&fullscreen&from=now-1h&to=now&width=1000&height=500

**Comment by torkelo** [comment]
what platform are you running? have you installed the required font libs that are required for phantomjs? check the grafana error log.

**Comment by ldkingvivi** [comment]
Here's the log

2015/12/08 11:55:28 [I] PhantomRenderer::renderToPng url http://localhost:8080/dashboard-solo/db/vip_developer_443_status?panelId=23&fullscreen&from=1449599988676&to=1449603588676&width=1000&height=500
2015/12/08 11:55:28 [I] Completed /render/dashboard-solo/db/vip_developer_443_status 404 Not Found in 6.014569ms

**Comment by ldkingvivi** [comment]
forget to mention that's  oracle linux enterprise 6

**Comment by torkelo** [comment]
make sure root_url is the same url you see in the browser, also make sure phantomjs works on the server
