### ISSUE TITLE
Snapshot sharing fails silently if querying the datasources takes too long

### ISSUE THREAD

**Issue by arodland** [grafana/grafana#3464]
Sharing a snapshot forces all of the datasources to be re-queried, and there's a non-configurable 5-second timeout for this process. If the timeout is exceeded, which can happen for a long timerange or a large number of series, the spinner stops and nothing at all happens. I think there are two bugs here:

1. That there's no way to wait longer for the data, and
2. That there's no reporting of what went wrong.

**Comment by torkelo** [comment]
yes, this needs to be improved, https://github.com/grafana/grafana/issues/2537
