### ISSUE TITLE
datetime picker inconsistencies

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#3465]
![picker-inconsistent](https://cloud.githubusercontent.com/assets/20774/11666677/916ea0f0-9e52-11e5-8c2f-fdb1c2d7f7ec.png)
Can we call "week to date" "week so far"? To be more consistent with "The day so far"
actually can we make it "This week so far", because everything else either has a "this" or a "the" in front.
(with the exception of "today" which is the proper form of "this day" so that's ok)
and probably "The day so far" -> "This day so far" for extra consistency but it's also a bit clearer.

**Comment by Dieterbe** [comment]
@mattttt

**Comment by bulletfactory** [comment]
Looking at the entire time-range panel to see how the other ranges are treated:
<img width="543" alt="screenshot 2015-12-08 15 43 39" src="https://cloud.githubusercontent.com/assets/1950595/11668008/ea0783ca-9dc2-11e5-8ee8-132e6f8f57bd.png">

"This week so far" makes sense, and feels consistent.
Maybe "The day so far" should be "Today so far" 
<img width="563" alt="screenshot 2015-12-08 16 01 48" src="https://cloud.githubusercontent.com/assets/1950595/11668402/028d257e-9dc5-11e5-943e-acb7e2aa008e.png">

This now feels consistent to me

**Comment by mattttt** [comment]
I also prefer "[The period] so far", mostly because it feels clearer as to what it does. Nice suggestion @Dieterbe.

**Comment by Dieterbe** [comment]
+1 for "Today so far"

![ocd](https://cloud.githubusercontent.com/assets/20774/11668671/5c6fbd98-9e5d-11e5-95d6-70f70c9e68fe.jpg)

**Comment by torkelo** [comment]
:+1:

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/11681618/5e080b08-9e60-11e5-81fe-1151f14dc441.png)

**Comment by Dieterbe** [comment]
No "this week so far" ?

**Comment by torkelo** [comment]
ah, missed that one

**Comment by Dieterbe** [comment]
thanks T
