### ISSUE TITLE
Re-sizing of flux query editor 

### ISSUE THREAD

**Issue by eriktar** [grafana/grafana#34657]
**What would you like to be added**:
In grafana 7.5.5 it is not possible to re-size the flux query editor.  Meaning I'm stuck with 11 visible lines at the time.  The influxql text editor has a re-size possibility, so it seems that the framework should be able to support this.

**Why is this needed**:
Flux seems to be more verbose and at least for me the queries often span more than 11 lines.  For my workflow it would be very useful to see a larger portion of the query at the time.

**Comment by gabor** [comment]
the Flux editor uses the `@grafana/ui/CodeEditor` component. i tried to make it resizeable, but i am not able to do it without modifying `@grafana/ui/CodeEditor`.  if i do the following, it works:
1. delete this wrapper div https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Monaco/CodeEditor.tsx#L152
2. at the place where it is used ( in my case https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/influxdb/components/FluxQueryEditor.tsx#L176 ):
    - set CodeEditor's height prop to `100%`
    - wrap CodeEditor in a div with `{{ resize: 'vertical', overflow: 'auto', minHeight: '200px',}}`


and then it works. but if i keep the wrapper-div in @grafana/ui/CodeEditor, it does not.

any ideas @grafana/grafana-frontend-platform how to move forward with this?

**Comment by srclosson** [comment]
We should double check to see if the new component behaves differently. There is a new `MonacoCodeEditor` that could also be a possibility? Setting `Needs Investgation`

**Comment by bohandley** [comment]
The Flux query editor is using Monaco and we agree this should be resize-able. We will look into this as we have the capacity.
