### ISSUE TITLE
Beta 6.2 Data periodically disappears from graph if derivative is used in query (InfluxDB)

### ISSUE THREAD

**Issue by mpergament** [grafana/grafana#3467]
Video attached shows the problem. Data disappears from graph periodically. Dashboard config is attached.
[Juniper Network Agent Interface Dashboard for qfx5100-01-48s-1449609801036.zip](https://github.com/grafana/grafana/files/56068/Juniper.Network.Agent.Interface.Dashboard.for.qfx5100-01-48s-1449609801036.zip)
![grafanadatadisappear](https://cloud.githubusercontent.com/assets/13856387/11668905/f3638f18-9df9-11e5-9354-24100db4b936.jpg)
[GrafanaDataDisappear.mov.zip](https://github.com/grafana/grafana/files/56066/GrafanaDataDisappear.mov.zip)

**Comment by torkelo** [comment]
make sure the Group by time option (below the queries) has a lower limit that is above the rate at which you send metrics. Like if you send every 10s specify `>11s` in the group by time limit. 

But it could be that you are encountering an InfluxDB bug. You can check InfluxDB response using chrome dev tools network tab.

**Comment by mpergament** [comment]
InfluxDB update to 9.5 solved this issue.
