### ISSUE TITLE
Snapshot URL not using Proxy address in Snapshot generation tab.   (7.4.2 ENT) 

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#34687]
**What happened**:
When creating a dashboard local snapshot in a Grafana Enterprise 7.4.2 on-prem installation **behind a proxy**, you will see two different URLs for the snapshot depending on where you are looking: snapshot creation tab versus Dashboards > Snapshots tab.  One URL works, the other does not since it does not take into account the proxy.

**What you expected to happen**:
The URL presented in both locations should be the same and be for the proxy version.

**How to reproduce it (as minimally and precisely as possible)**:

The URL presented at the time of creation [go to any dashboard > Share > Snapshot > Local Snapshot] will show the actual server name and a port which fails for users coming in via a proxy:

`https://graf123.DOMAIN1.com:3000/dashboard/snapshot/mlx506MXldE1. . .`

The other URL presented for the same snapshot in menu [Dashboards > Snapshots] works correctly - it uses the configured Proxy address which the users expect:
`https://grafana.DOMAN2.com/dashboard/snapshot/mlx506MXldE. . .`

**Anything else we need to know?**:

**Environment**:
- Grafana version: Enterprise 7.4.2
- Data source type & version: InfluxDB FOSS
- OS Grafana is installed on: Redhat 7.9
- User OS & Browser: Chrome
- Grafana plugins: n/a

- Other: **Full details with actual examples and config file screenshots in ZD-Ticket 24593**

**Comment by evictorero** [comment]
I confirm this issue is still happening in grafana 10. The snapshot list is building the URL using the `window.location.href` while the snapshot tab is using the server URL config.
