### ISSUE TITLE
how to save the panel json  on dashboards

### ISSUE THREAD

**Issue by venkatdba64** [grafana/grafana#3468]
i updated the panel json under dashboards to limit 1000 . after update it showed me once i logout and login its not showing all. how to save it. And how to made it to visible to users.

**Comment by torkelo** [comment]
Are you talking about dashboard list? 

I think you are talking about the home dashboard. You cannot change the home dashboard currently (there is an issue for that already so will close this)

**Comment by venkatdba64** [comment]
I created the some 80 dashboards in grafana .In grafana home page under the logo of grafana  we are seeing starred dashboards as well as dashboards  i want to display all the 80 dashboards under dashboards .how to do that ..if it is not possible give me the issue number .or if it possible let me know how to do. Thanks so much

**Comment by torkelo** [comment]
this is the issue for being able to change the home dashboard, https://github.com/grafana/grafana/issues/1678
