### ISSUE TITLE
time_series beta 2 (missing Alerting and thresholds not displaying)

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#34681]
**What would you like to be added**: Alerting tab is not visible/operational in time_series beta2.
**What would you like to be added**: Thresholding configuration does not show up in time_series beta2 chart
**Why is this needed**: Alerting is needed to configure alerts for chart metrics.  Thresholding is available already, but configuration changes are not being displayed on chart

**Comment by hugohaggmark** [comment]
Hi @underdog if you're you trying to report an issue can you please use our template? And when you do, can you separate it into 2 issues and give more details about each one because it's hard to figure out what you mean with this issue. Thank you!
