### ISSUE TITLE
signed plugins show up as unsigned

### ISSUE THREAD

**Issue by KhoiDinh** [grafana/grafana#34690]
**What happened**:
Some signed plugins are showing up as unsigned.
**What you expected to happen**:
For the signed plugins to show up as signed.
**How to reproduce it (as minimally and precisely as possible)**:
install the specified plugins and grafana versions

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.2 or 8.0.0beta
- Data source type & version:
- OS Grafana is installed on: linux
- User OS & Browser: linux/google chrome
- Grafana plugins:
1.	Agenty-flowcharting-panel: https://grafana.com/grafana/plugins/agenty-flowcharting-panel/ (Community signed) version 0.9.0 
2.	aidanmountford-html-panel: https://grafana.com/grafana/plugins/aidanmountford-html-panel/ (Community signed) version 0.0.1
3.	Grafana-piechart-panel: https://grafana.com/grafana/plugins/grafana-piechart-panel/ (Grafana signed) version 1.6.1
- Others:

**Comment by wbrowne** [comment]
@KhoiDinh Unfortunately I'm unable to reproduce. Of the 3 plugins you listed, 2 of those are unsigned (have no signature whatsoever)
![image](https://user-images.githubusercontent.com/1173299/119665300-8abab200-be34-11eb-861c-800981e2ea9a.png)

The Grafana Piechart Panel is signed and therefore should work.

Are you able to confirm that neither of these plugins (`agenty-flowcharting-panel` and `aidanmountford-html-panel`) contain a `MANIFEST.txt` in the extracted plugins root directory?

**Comment by carlosleoliveira** [comment]
@KhoiDinh I'm using Grafana 7.5.7 and to Flowcharting was needed the beta version 1.0b. The html plugin maybe is too old.
