### ISSUE TITLE
Data change along with time frame?

### ISSUE THREAD

**Issue by mrvvV** [grafana/grafana#3469]
Hey,

On grafana, is it possible to make my data respond to the time frame?
For example, If I zoom into a specific day, or time frame, could all my single stat values change according to that time frame?

Furthermore, I would like to calculate the percentage from the query with the single stat panel. For example, A/B to get a percent stat. 
I read something about how I can use rows to achieve this, but I'm not quite sure how to get the data from the rows. Also, for some reason the count function does not generate the data in the time frame. It gives me values that I do not expect to get. Could someone please give me some insight? 

Thanks!
Vincent

**Comment by torkelo** [comment]
All panels will update when you can time range or zoom in. 

Some data sources (like Graphite) allow you do to complex analytics like divide one query with another query.

**Comment by mrvvV** [comment]
@torkelo one last question. How do I get the time interval variable into my queries.
For some reason when I am changing my time interval my data is not changing accordingly. I want to do something like:

Select totalTime from builds where "status" = 'success' and time > <lower bound of time interval> and time < <higher bound of time interval>

Thanks,
Vincent

**Comment by torkelo** [comment]
if you use InfluxDB you need `WHERE $timeFilter` , for all other data sources this is handled automatically

**Comment by mrvvV** [comment]
Thanks it works!
