### ISSUE TITLE
[Auth proxy]header property not support non-ascii code

### ISSUE THREAD

**Issue by msober** [grafana/grafana#34692]
**What happened**:
When use auth proxy,  add header property like
X-WEBAUTH-NAME: 张三
then grafana username shows "??"

**What you expected to happen**:
grafana username also show "张三"

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: 
- OS Grafana is installed on: mac
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Passing this over to @grafana/backend-platform

**Comment by zserge** [comment]
Historically, HTTP has allowed field content with text in the ISO-8859-1 charset only. Additional charsets have been supported via RFC2047 (so-called MIME encoding): https://datatracker.ietf.org/doc/html/rfc2047

In that RFC the header value might be of the form `=?charset?encoding?encoded text?=`, which not only looks weird, but is also barely supported by clients/servers in the wild.

Please, check if utf-8 in MIME encoding is working for you.

**Comment by msober** [comment]
> Historically, HTTP has allowed field content with text in the ISO-8859-1 charset only. Additional charsets have been supported via RFC2047 (so-called MIME encoding): https://datatracker.ietf.org/doc/html/rfc2047
> 
> In that RFC the header value might be of the form `=?charset?encoding?encoded text?=`, which not only looks weird, but is also barely supported by clients/servers in the wild.
> 
> Please, check if utf-8 in MIME encoding is working for you.

This way is so weird and our reverse proxy use apache http client(java) that not support MIME header
