### ISSUE TITLE
Tree like explorer of graphite metrics keys  

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#347]
In the current state of Grafana I often found myself going back and forth between a Grafana graph metrics query and the built in Graphite web interface. The main reason is I got used to be able to browse for metrics (using the "explorer like tree"  UI) and still see the complete tree independently of the query itself, something I can not do in Grafana since I can only see metrics on a per node basis and only by clicking on the node while in editing the query mode. Maybe I've spent too much time building graphs with the stock UI and maybe I should forget about being able to see all metrics in a persistent dedicated area but I think there is some value in it. I understand searching for metrics leveraging ElasticSearch is on the roadmap so that's why I'm creating this.

**Comment by IzakMarais** [comment]
Opentsdb has added support to build trees (and query them via HTTP). That query endpoint might also be useful when implementing this feature for OpenTSDB.

http://opentsdb.net/docs/build/html/user_guide/trees.html

**Comment by simonvanderveldt** [comment]
@torkelo Is it expected behaviour that if I have hierarchical data that i have namespaced using tags like `house1` and `house1.bedroom1` and I query for `house1` using Grafana that I get the results from `house1.bedroom1`as well?

I'm using Templating in Grafana and noticed this `location =~ /$location/` in the `WHERE` row of the Metrics properties. The `=~` might have something to do with it?

**Comment by ytti** [comment]
Wouldn't it be possible to make this source agnostic? When you configure source, you could optionally configure field-separator character, when configured it would build tree-like presentation from the counter names.

When when using labels sensibly in influxdb some structure would be helpful when there are large number of counters available.

**Comment by simonvanderveldt** [comment]
This stalebot thing is so annoying :gun:

**Comment by torkelo** [comment]
Sorry, it was wrongly configured (should only have acted on PRs)

**Comment by fifeclub** [comment]
Still relevant - so much so we're considering building a panel like this - would be better as a standard panel though.

**Comment by itsmylife** [comment]
@grafana/observability-metrics does not currently have the bandwidth to prioritize development on this issue. If members of the community want to take this issue we will help review any submitted PRs. Please upvote or comment to help us re-prioritize this issue in the future!
