### ISSUE TITLE
Printing / Saving a Dashboard Table & Data

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#34703]
We are using version 7.5.1

I notice that when we have a table which for example is pre-sized to only display 10 rows, but the data source returns 100 rows, when using the browser (ex. Chrome) to save the page as a PDF, it will only show the current 10 rows that are displayed in the view, but not the entire table contents.

![image](https://user-images.githubusercontent.com/1325158/119623107-867c9d80-be10-11eb-9089-d53d4668b27d.png)

I would have assumed that even when I click on the View option for the panel, I should be able to view all of the rows and save the entire page (manually) as a pdf and/or print the contents. I know that I can manually export the data to CSV but then it is without the column widths, css, etc.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by reuvygroovy** [comment]
Now I see, that I can't print/save any page as a PDF, unrelated to tables. The pictures/graphs, etc. - none come out. Is this by design?

**Comment by torkelo** [comment]
Not by design, just requires some work to get this print view to behave and render a very different view and it has not been requested. Grafana Enterprise has a Reporting feature that can build PDF from dashboard using different layouts. But it is rendering each panel and placing them into a PDF that the report service builds

**Comment by torkelo** [comment]
For table, use inspect menu > Data, there you can export the data to excel and print it from there
