### ISSUE TITLE
Unified Alerting: Add time picker for rule run/test buttons

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#34734]
**What would you like to be added**:
A time picker that sets the "now" time for "Run Queries" and the "Preview your Alert".

Based on the current layout, I would recommend putting it next to "Run Queries" and displaying the same time above the table returned from "Preview your Alert".

Not ideal, but seems to me to be the best placement and you can generally see "Run Queries" when viewing the preview.

**Why is this needed**:
So alert rules can be tested to see what happens at a specific time.

Example user story: Get alert from rule, didn't want it. Set rule to that time, test to confirm it triggers. Adjust alert, run again and make sure it doesn't trigger.

cc @mckn

**Comment by mckn** [comment]
@oanamangiurea do you have any input on how we could fit this into the UI?

**Comment by oanamangiurea** [comment]
@kylebrandt @mckn I wonder if we could use the picker tied to the run query button, similar to the one in explore, having the values of the dropdown adjusted for what we need. See screenshot 
<img width="164" alt="Screenshot 2021-05-27 at 10 26 33" src="https://user-images.githubusercontent.com/5183519/119783585-04ef4300-bed6-11eb-92b7-34dfbcd7de15.png">

For preview your alert - will this be readonly or can it be selected independently from the one next to run query?

**Comment by kylebrandt** [comment]
I like the picker tied to the button idea. In this case it will be a Calendar Date Time, and not relative time. This way users can set the time to run the alert to match some event they know happened. Also, when editing the rule and testing it, if the time is changing that can lead to confusion (as the data is changing while editing), so it is useful to be fix the time for visualization and testing.

For Preview Alert, I think it should be tied to this time. I think we want the results of the visualization to be consistent with the results in the preview (we don't have a backend endpoint that does both of these at once yet, but I imagine that for the future).

**Comment by armandgrillet** [comment]
Superseded by https://github.com/grafana/grafana/issues/53443
