### ISSUE TITLE
Alerting function missing in Time Series Beta 2

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#34735]
**What happened**: Alerting configuration missing

**What you expected to happen**: To be able to configure alerts within the Time Series Beta 2 similar to the legacy Chart panel

**How to reproduce it (as minimally and precisely as possible)**: Create new Time Series Beta 2 chart. Alerting is missing

**Anything else we need to know?**: screenshot attached shows area where alerting should be, if it were configured the same as the legacy Chart panel

**Environment**:
- Grafana version: Grafana version: Grafana v7.5.7 (91de517)
- Data source type & version: Data source type & version: influxdb 1.8.6-1 armhf
- OS Grafana is installed on: OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+ #1414 SMP armv7l GNU/Linux
- User OS & Browser: User OS & Browser: Windows 10, Brave or Chrome
- Grafana plugins: Time Series Beta 2
- Others:
![time_series_beta2](https://user-images.githubusercontent.com/510960/119656070-e1ea6380-bdef-11eb-8ca0-4b409564ec6f.png)

**Comment by torkelo** [comment]
it's added in v8-beta
