### ISSUE TITLE
Time_Series Beta 2 Threshold Values Not Displaying

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#34732]
**What happened**: Threshold values should show up on chart when added/modified in time_series beta 2 configuration

**What you expected to happen**: I would expect the values or percentages used in the threshold configuration to show up within the chart, similar to the legacy Chart panel

**How to reproduce it (as minimally and precisely as possible)**: Create Time Series Beta 2 chart, configure thresholds for your chart based on what thresholds you would like to set, based on the data in your chart

**Anything else we need to know?**:

**Environment**:  
- Grafana version: Grafana v7.5.7 (91de51771c)
- Data source type & version: influxdb 1.8.6-1 armhf
- OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+ #1414 SMP armv7l GNU/Linux
- User OS & Browser: Windows 10, Brave or Chrome
- Grafana plugins: Time Series Beta 2
- Others:
![time_series_beta2](https://user-images.githubusercontent.com/510960/119654392-080f0400-bdee-11eb-9f99-bf8736be79d9.png)

**Comment by torkelo** [comment]
Fixed in v8
