### ISSUE TITLE
[ldap] - multi ldap tree & servers

### ISSUE THREAD

**Issue by JulienChampseix** [grafana/grafana#3474]
Hi Team,

Ldap auth is working well when you have 1 ldap tree for 1 company having 1 ldap endpoint, in case of you have several company so several different ldap tree having (so meaning one separated ldap endpoint per company), do you support it ?
By this way, can we have sereval ldap.toml in grafana ? or duplicate section [[servers]] ? or other method? which will be loaded at the grafana start and when someone is trying to connect, grafana will try every toml / section [[servers] for connect this users.

Hope it's a bit clear as explanation :)

(cc @torkelo )

Thanks.
Julien.

**Comment by torkelo** [comment]
I think it will try every server specified, and use the first that works.

**Comment by JulienChampseix** [comment]
How can i config several company in grafana ?

detailled example for my requirement bellow :

company 1: 
host = "10.10.10.1"
bind_dn = "cn=%s,cn=Users,dc=company1,dc=com"

company 2: 
host = "192.168.1.1"
bind_dn = "cn=%s,cn=Users,dc=company2,dc=com"

company 3: 
host = "176.16.2.10"
bind_dn = "cn=%s,cn=Users,dc=company3,dc=com"

I would be able to provide the same grafana for all company but having several ldap tree behind for authenticated users from those 3 company.

**Comment by torkelo** [comment]
you should be able to specify multiple `[[servers]]` sections. 

Like this 
```toml
[[servers]]
  host = 
  bind_dn = 
  [servers.attributes]
  # stuff
  [[servers.group_mappings]]
  # mappings
[[servers]]
  host = 
  bind_dn = 
  [servers.attributes]
  # stuff
  [[servers.group_mappings]]
  # mappings
```
