### ISSUE TITLE
Support for CloudWatch custom metrics

### ISSUE THREAD

**Issue by matschaffer** [grafana/grafana#3475]
(extracted from [this comment](https://github.com/grafana/grafana/commit/0912cec0e5d882cbbdba2f7d174a5940a0c6e01b#commitcomment-14674633))

I've been using the original CloudWatch data source (ea7c6edc) plus a cronjob that calls aws cloudwatch list-metrics and it's been pretty effective.

Downside is that configuring the location of the json file is a little strange from the web UI, plus you also need the aws-cli installed.

Another thought would be to just do it in memory via time.NewTicker. You're making more calls as you scale up grafana instances, but at once per hour I doubt it'd incur much cost.

**Comment by mtanda** [comment]
This is past implementation.
https://github.com/mtanda/grafana/blob/be6cb24e10f3b6bc3228d67a1dfa2cb5474ef566/public/app/plugins/datasource/cloudwatch/datasource.js#L176-L219

**Comment by torkelo** [comment]
needs to be implemented in the backend

**Comment by mtanda** [comment]
Yes, of course!
I don't consider implement it in frontend :-)

**Comment by marco-hoyer** [comment]
This would be great. +1

**Comment by benjdlambert** [comment]
:+1:

**Comment by joebaldwin95** [comment]
This would be amazing! Any progress?

**Comment by matschaffer** [comment]
Incase it helps anyone we're running ea7c6edc which still had custom metric support.

**Comment by joebaldwin95** [comment]
Thanks, I have built that version but no custom metrics are showing for me :/

**Comment by matschaffer** [comment]
@joebaldwin95 you'll need to enable the plugin by doing:

```console
> cp public/app/plugins/datasource/cloudwatch/{_,}plugin.json
```

Then add a cronjob that populates a metrics JSON file via this command (I put mine in a `reload_metrics.sh` script):

```console
aws cloudwatch list-metrics --region "${AWS_REGION}" > public/cloudwatch_metrics.json
```

Then you should be able to point the plugin at your file via the UI using this dialog:

<img width="833" alt="grafana_-_home" src="https://cloud.githubusercontent.com/assets/690/12223946/6222e2c6-b828-11e5-8693-8718f46efa31.png">

**Comment by joebaldwin95** [comment]
Thanks for the help! I have tried building from the source using https://github.com/grafana/grafana/tree/ea7c6edcd0468cc6145967596364507d24c9805d as the source url but when I go to the cloudwatch datasource UI, I dont see the custom metric attribute field. Could you tell me which folder I need to be in to run "cp public/app/plugins/datasource/cloudwatch/{_,}plugin.json"?

**Comment by matschaffer** [comment]
Ah, sorry about that I think that command may have be used on another rev. I just gave a test on ea7c6edc and I can see the field on my mac. The process was:

```
go get github.com/grafana/grafana
cd "${GOPATH}/src/github.com/grafana/grafana"
git checkout ea7c6edcd 2>/dev/null || true
go run build.go setup
godep restore
npm install -g grunt-cli
npm install
go run build.go build
grunt release
cd dist
tar -zxf grafana-2.2.0-pre1.darwin-x64.tar.gz
cd grafana-2.2.0-pre1
./bin/grafana-server
```
