### ISSUE TITLE
Cannot deselect alert state filter

### ISSUE THREAD

**Issue by owen-d** [grafana/grafana#34752]
It would be really nice to remove all existing filters

![image](https://user-images.githubusercontent.com/8173478/119685325-423ecc80-be13-11eb-9ffa-bc36c5696957.png)

**Comment by armandgrillet** [comment]
Fixed in August 2021, this is in Grafana 8 and 9:
<img width="600" alt="PS 2022-08-28 à 08 39 31" src="https://user-images.githubusercontent.com/2117580/187061167-11abcd6b-8c7f-491a-8687-f6eb38226236.png">
