### ISSUE TITLE
Dashboard init failed in 8.0.0Beta2

### ISSUE THREAD

**Issue by jtorkkel** [grafana/grafana#34788]
**What happened**:

Loading dashboard created initially using Grafana 5 and 6 fails immediately resulting Dashboards init failure.  If Dashboard created using Grafana 7 then loading succeed.

**What you expected to happen**:
Dashboard should load

**How to reproduce it (as minimally and precisely as possible)**:
Load old dashboard created using old Grafana. Dashboard include old tables and old SingleStat panel.
I manage to reduce failing Dashboard to few repeating SingleStat panels. When panels were changed to new Stat the panel the dashboard worked.
I was not able to find what exactly fails. The error I see when using Chrome debugger is.
Migrating dashboard manually to to new Stat is quite challenging for large dashboards as must be done in advance.
 
initDashboard.ts:161 TypeError: e.changePlugin is not a function
    at DashboardMigrator.ts:896
    at v.<anonymous> (DashboardMigrator.ts:580)
    at v.updateSchema (DashboardMigrator.ts:633)
    at D.updateSchema (DashboardModel.ts:993)
    at new D (DashboardModel.ts:156)
    at initDashboard.ts:158

fails here:

    // create model
    let dashboard: DashboardModel;
    try {
      dashboard = new DashboardModel(dashDTO.dashboard, dashDTO.meta);
    } catch (err) {
      dispatch(dashboardInitFailed({ message: 'Failed create dashboard model', error: err }));
      console.error(err);
      return;
    }

    if (oldVersion < 28) {
      panelUpgrades.push((panel: PanelModel) => {
        if (panel.type === 'singlestat') {    # line 580
          migrateSinglestat(panel);
        }
      });

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0 Bta
- Data source type & version:
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by jtorkkel** [comment]
Manyally migrating all SingleStat to Stat using Grafana v7 fix the issue, but single repeating SingleStat might break the migration. Dashboards cannot be modified after migated to v8 as load fails immediately.

**Comment by Elfo404** [comment]
hi @jtorkkel, just to make sure I understood correctly, you are trying to upgrade from v7 to v8, having some dashboards create in v5/6, right?

**Comment by jtorkkel** [comment]
Hi, I tested multiple dashboard. 
One created initially v5/v6 and latest Grafana was 6.4.3 
Another v4/v6/v7 latest grafana 7.5.7.
I never migrated to new Stat but kept using Singlestat. 
Most Singlestat works but some with ~100 repeating panel trigger the failure. 

Deleting the failing one helped.

Also when I migrated Singlestat to Stat the dashboard worked, but that is painfull for all dashboards, forgettkng to migrate one might trigger the failure snd you need to restore old.

**Comment by torkelo** [comment]
@jtorkkel can you share a dashboard json (before migration) that fails?

**Comment by torkelo** [comment]
@jtorkkel can you share a dashboard json (before migration) that fails?

**Comment by jtorkkel** [comment]
Hi,

I managed to reduce the dashboard to few repeating panel and manually obfuscate the dashboard by removing repeating panels with leaking names.

In my testing it still "fails to init" in 8.0.0Beta3 when imported. Failed dashboard is still imported and will become visible.

[Failing dashboard.zip](https://github.com/grafana/grafana/files/6614205/Failing.dashboard.zip)

**Comment by wargamez** [comment]
Seeing the same thing in 8.0.0, had to downgrade to 7.5.7...

**Comment by jackw** [comment]
From the time I've invested debugging this I believe it's related to Panel Rows being collapsed when the migration is attempted. Expanding all rows and saving the dashboard prior to exporting / migrating appears to work from my initial testing.

**Comment by davidgiga1993** [comment]
[dashboard.zip](https://github.com/grafana/grafana/files/6622463/dashboard.zip)
Don't know if it helps but here is my dashboard which fails migration

**Comment by eurodrew555** [comment]
I ran into this same "dashboard init failed" issue after upgrading to grafana-8.0.0-1 on CentOS 8.
My dashboard with the issue had many panel rows collapsed before the upgrade.

Following @jackw above I downgraded to 7.5.7-1, expanded all rows and saved the dashboard.
After upgrading to 8.0.0-1 again the dashboard now displays OK without error.

**Comment by dan-m-joh** [comment]
I can confirm that downgrading to 7.5.7, expanding all rows, save the dashboard and then update to 8.0.0 works as described by @jackw
