### ISSUE TITLE
Unified Alerting:  Alert rule creation - update save buttons style

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#34785]
The current implementation uses 3 different button styles for alert rule creation, in the top bar, and because we have changed themes the "Save" one looks disabled. Please change the style on "Save" button from secondary to primary (blue), as we have in Figma.

<img width="313" alt="Screenshot 2021-05-27 at 10 28 55" src="https://user-images.githubusercontent.com/5183519/119785720-23eed480-bed8-11eb-82f5-66dd7cac4ff4.png">

**Comment by torkelo** [comment]
@oanamangiurea @Clarity-89  should they not use toolbar button styles? as these are in the toolbar 
![Screenshot from 2021-11-02 10-41-20](https://user-images.githubusercontent.com/10999/139822898-69ce6849-71cb-465f-bf5d-639db46bb294.png)

**Comment by Clarity-89** [comment]
Hmm, I think both cases work here, from the user point of view I don't see why `Save & Exit` should have primary style, while `Save` should not. I guess this is more of a question to the UX team.

**Comment by oanamangiurea** [comment]
Both "Save" and "Save and exit" are positive actions, and both are primary in this case as it depends on what the user is planning to do, only having one as a primary might mislead the user for example to exit the alert creation flow.
cc @jessover9000 as she's in charge of the alerting project
