### ISSUE TITLE
Feature Request: Generic key/value mapping

### ISSUE THREAD

**Issue by joeshaw** [grafana/grafana#3478]
First, some background: I have a template variable that lets you select the environment you want to look at: prod, stage, dev.  These map onto our Graphite data source, so we do queries like `$env.counts.etc`.  We also recently started using the CloudWatch data source.  We have ELB instances with names roughly of the form "foo-develb-abcdef."  I would like to be able to take `$env` and map it onto an ELB instance, so that I can keep a single template variable.

So, it'd be nice if I could set up a generic key-value mapping that's something like:

env-to-ELB-name:
dev -> foo-develb-abcdef
stage -> foo-stagee-123456
prod -> foo-prodel-xyz123

and then I could key into that somehow in queries, like `kv_map(env-to-ELB-name, $env)`, and get the proper ELB name.

We would then do the same thing for RDS, SQS, and other AWS services.  Unfortunately while we set AWS tags for env on all the services that support it, CloudWatch doesn't support them as a dimension that can be queried.

For my purposes, I don't need the mapping to be dynamically generated in any way.  I could just set the ELB names by hand, but I could somehow see populating it automatically from elsewhere.

**Comment by mtanda** [comment]
I have similar problem in AWS environment.
And I want to generate mapping automatically.

I think if Grafana has feature "external templating query source" (https://github.com/grafana/grafana/issues/2188), we can handle this well.
Generate mapping in EC2 instance which has enough IAM, and put the mapping result somewhere accessible, then set templating to the mapping.

**Comment by eheydrick** [comment]
This would be useful for mapping instance name -> instanceId.

**Comment by spinus** [comment]
+1
I think this could be implemented as another regexp field, right?
There is one regexp field to extract value from query, probably can be another regexp to extract name.

Than, would be nice if grafana exports those two values to templates, let's say "$var" and "$var.name" (or "$var_name")

**Comment by mtanda** [comment]
I create datasource plugin for this.
https://github.com/mtanda/datasource-plugin-templating_json

It can loading external json file, and query by jmespath.

**Comment by joeshaw** [comment]
@mtanda could you add a README to explain how to install and use it?

**Comment by mtanda** [comment]
@joeshaw The plugin is seems to be broken due to recent Grafana change. I fixed it.
And add README. To use the plugin, you will need to install latest Grafana build (3.0 pre1).

**Comment by hugohaggmark** [comment]
If I understand the description correctly, this is already implemented in #28896 and in #28625 so I'm going to close this issue. If I've interpreted this issue wrongly, we can reopen it.

Thank You to you for taking the time to create this issue!
