### ISSUE TITLE
BarChart: Tooltip is persistent when you go to editmode

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#34790]
For some reason the fix applied to time series panel by @oscarkilhed in https://github.com/grafana/grafana/pull/34001 does not work in BarChart panel:

https://user-images.githubusercontent.com/2376619/119794489-db371b80-bed7-11eb-849e-2a49e1d7ea7b.mp4

The problem appears when you hover over the bar and press `e` to go to the edit panel.

**Comment by oscarkilhed** [comment]
This actually worked in #34001
Gonna have a look at what changed

**Comment by leeoniya** [comment]
this was regressed by https://github.com/grafana/grafana/pull/34229

after that PR, pressing `e` to pull up edit mode fires `removeEventListener()`
