### ISSUE TITLE
es-hadoop question

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#3479]
Hi Torkel,

I have a different question. Have you used es-hadoop with elasticsearch? If longer data is in hadoop, would grafana using elasticsearch as datasource be able to connec to hadoop via es-hadoop plugin?

Or any ideas around how grafana would be able to read data from hadoop?

**Comment by torkelo** [comment]
I have not tested es-hadoop, if it has an HTTP api that is compatible with elasticsearch 1.7 - 2.0 then it should work
