### ISSUE TITLE
Toolkit: npx commands fail with NPM 7.x.x

### ISSUE THREAD

**Issue by mjekrami** [grafana/grafana#34807]
npx @grafana/toolkit plugin:create Cloudflare-map --verbosenpx @grafana/toolkit plugin:create Cloudflare-map --verbose
Result:{{
npm WARN ERESOLVE overriding peer dependency    
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@">=15.0.0 <17.0.0" from @iconscout/react-unicons@1.1.4
npm WARN node_modules/@iconscout/react-unicons
npm WARN   @iconscout/react-unicons@"1.1.4" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from @torkelo/react-select@3.0.8
npm WARN node_modules/@torkelo/react-select
npm WARN   @torkelo/react-select@"3.0.8" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   react-dom@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   1 more (@grafana/slate-react)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0" from @torkelo/react-select@3.0.8
npm WARN node_modules/@torkelo/react-select
npm WARN   @torkelo/react-select@"3.0.8" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.0.0-0 || ^16.0.0-0" from @visx/gradient@1.0.0
npm WARN node_modules/@visx/gradient
npm WARN   @visx/gradient@"1.0.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.3.0-0" from @visx/shape@1.4.0
npm WARN node_modules/@visx/shape
npm WARN   @visx/shape@"1.4.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0-0" from @visx/tooltip@1.3.0
npm WARN node_modules/@visx/tooltip
npm WARN   @visx/tooltip@"1.3.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   react-dom@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   1 more (@grafana/slate-react)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.0-0" from @visx/tooltip@1.3.0
npm WARN node_modules/@visx/tooltip
npm WARN   @visx/tooltip@"1.3.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.0.0 || ^16.0.0" from rc-cascader@1.0.1
npm WARN node_modules/rc-cascader
npm WARN   rc-cascader@"1.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   react-dom@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   1 more (@grafana/slate-react)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^15.0.0 || ^16.0.0" from rc-cascader@1.0.1
npm WARN node_modules/rc-cascader
npm WARN   rc-cascader@"1.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.5" from react-beautiful-dnd@13.0.0
npm WARN node_modules/react-beautiful-dnd
npm WARN   react-beautiful-dnd@"13.0.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   react-dom@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   1 more (@grafana/slate-react)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^16.8.5" from react-beautiful-dnd@13.0.0
npm WARN node_modules/react-beautiful-dnd
npm WARN   react-beautiful-dnd@"13.0.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-custom-scrollbars@4.2.1
npm WARN node_modules/react-custom-scrollbars
npm WARN   react-custom-scrollbars@"4.2.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react-dom@17.0.1
npm WARN node_modules/react-dom
npm WARN   react-dom@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   1 more (@grafana/slate-react)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react-dom@"^0.14.0 || ^15.0.0 || ^16.0.0" from react-custom-scrollbars@4.2.1
npm WARN node_modules/react-custom-scrollbars
npm WARN   react-custom-scrollbars@"4.2.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^0.14.0 || ^15.0.0 || ^16.0.0-0" from react-highlight-words@0.16.0
npm WARN node_modules/react-highlight-words
npm WARN   react-highlight-words@"0.16.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.0" from react-hook-form@5.1.3
npm WARN node_modules/react-hook-form
npm WARN   react-hook-form@"5.1.3" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.x" from react-monaco-editor@0.36.0
npm WARN node_modules/react-monaco-editor
npm WARN   react-monaco-editor@"0.36.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^15.x || ^16.x" from react-storybook-addon-props-combinations@1.1.0
npm WARN node_modules/react-storybook-addon-props-combinations
npm WARN   react-storybook-addon-props-combinations@"1.1.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN ERESOLVE overriding peer dependency
npm WARN Found: react@17.0.1
npm WARN node_modules/react
npm WARN   react@"17.0.1" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
npm WARN     @grafana/ui@"7.5.7" from @grafana/toolkit@7.5.7
npm WARN     node_modules/@grafana/toolkit
npm WARN   3 more (@emotion/core, @grafana/slate-react, react-dom)
npm WARN
npm WARN Could not resolve dependency:
npm WARN peer react@"^16.8.3" from react-table@7.0.0
npm WARN node_modules/react-table
npm WARN   react-table@"7.0.0" from @grafana/ui@7.5.7
npm WARN   node_modules/@grafana/ui
[    ..............] / idealTree:tiny-warning: sill fetch manifest tiny-warning@^1.0.3

**Comment by Elfo404** [comment]
Hi @mjekrami thanks for reporting this.

could you please tell us which version of `npm` are you using? (`npm -v` should do the job)

I'm also not able to create a plugin, seems like npm is failing resolving some dependencies (in my case `npm -v` output is `7.8.0`)

**Comment by tokuleo** [comment]
Hi @Elfo404 and @mjekrami 

I also had this problem with plugin:create and tiny-warning using npm 7.x.x. However, it works after I downgraded npm to 6.14.12. This could be a potential workaround.

**Comment by Elfo404** [comment]
Just tried it out with npm 6 and it works correctly. thanks @tokuleo

**Comment by dprokop** [comment]
@tokuleo one more question - what version of Node are you at?

**Comment by jackw** [comment]
Looks like a similar issue to #31396 

Due to the way module resolution changed in NPM 7 I believe the `--legacy-peer-deps` argument needs to be passed when running the create command:

```shell
npx @grafana/toolkit plugin:create Cloudflare-map --legacy-peer-deps
```

@tokuleo could you try the above command and confirm if it solves the issue with NPM 7 please?

**Comment by tokuleo** [comment]
@dprokop I'm using node v12.22.1

@jackw After re-upgrading to npm 7.15.0, the following works

```
npx --legacy-peer-deps @grafana/toolkit plugin:create my-plugin
```

Note that it looks like if I pass `--legacy-peer-deps` immediately after `npx`, it gets passed to `npm`.

**Comment by mjekrami** [comment]
I'm using npm version 7.11.2

**Comment by RileyMShea** [comment]
The problem persists on 7.19.x.  Appears the issue comes from lacking explicit `resolutions` in a package.json.

See https://github.com/yarnpkg/rfcs/blob/master/implemented/0000-selective-versions-resolutions.md for more info.

yarn 2 is stricter which helps prevent situations like this.  Could be used w/out plug'n'play but maybe not worth considering the delicate nature of monorepos.

**Comment by rkuhn** [comment]
> We should probably consider adding some info to docs and tutorials that include the workaround for the time being.

I strongly agree — such a nice and obvious and documented command not working (and I first suspected Apple Silicon and tried it on a cloud box) deserves prominent documentation in the tutorials.

**Comment by tolzhabayev** [comment]
We are closing this issue as stale
