### ISSUE TITLE
[Question] Can Templating pull from multiple data sources?

### ISSUE THREAD

**Issue by druchoo** [grafana/grafana#3480]
If so, how? If not, please make feature request.

-Thanks

**Comment by torkelo** [comment]
You can select data source for each template variable, but one variable cannot pull form multiple.

**Comment by druchoo** [comment]
As always, thanks for the super fast response. Can you make this feature request?

**Comment by torkelo** [comment]
no, as there is no description at all for what your requesting or why, how it should, whats the use case etc

**Comment by druchoo** [comment]
Request: Allow templating query type templating variables to pull from multiple data sources
How: make 'Data source' drop down multi select
Use case: Have multiple graphite data sources and would like to view in one dashboard that uses templating

**Comment by mhite** [comment]
I'd also love this feature!

**Comment by JeromeVi** [comment]
I would love this too !
