### ISSUE TITLE
Switch to yarn to compile yields yarn-related concurrency issue

### ISSUE THREAD

**Issue by Berbe** [grafana/grafana#34803]
**What happened**:
Since the [switch from `grunt` to `yarn`](https://github.com/grafana/grafana/commit/2d49d3f5b23a3f4c35d7b96c2d1451dc5012ebb0#diff-b4c6189f9184e61338a887d10410ec33e466f2fdba640cb632fab869dcb8b289) in the compilation phase of the Docker image, image building often (as opposed to _systematically_) fails with an `Extracting tar content of undefined failed` error, [as reported upstream](https://github.com/yarnpkg/yarn/issues/7212).

**What you expected to happen**:
Consistently successful building process

**How to reproduce it (as minimally and precisely as possible)**:
Cook several times the Docker image recipe from a release done after the aforementioned change. Any `7.5` will do.

**Anything else we need to know?**:
Despite the issue having been reported and quoted often since April, 2019 (that is, precisely more than 2 years), and at least one attempt (tied to the issue) of fixing it via a [PR](https://github.com/yarnpkg/yarn/pull/8182) (opened for roughly a year), this issue is still not fixed in trunk `yarn`.

Since this problem was never encountered with `grunt`, would it be possible to temporarily revert the building toolchain again? Or in any case change it?
I must point out I have *no* expertise in this toolchain whatsoever.

**Environment**:
- Grafana version: v7.5.7 (All 7.5 qualify?)

**Comment by marefr** [comment]
Change introduced via #29538

**Comment by dsotirakis** [comment]
@Berbe hello and thanks for raising this - haven't been able to reproduce it on v8+, is it something that still persists?

**Comment by merceyz** [comment]
> this issue is still not fixed in trunk yarn.

The issue has been fixed in `yarn@>=2` https://yarnpkg.com/getting-started/migration

**Comment by Elfo404** [comment]
given this has gone stale for a while and there's no progress I'm going to close this.

Also, at the same time, I don't think switching back to grunt would be a viable approach. We are also working on improving and updating our tooling (see https://github.com/grafana/grafana/pull/39082) which will hopefully solve the issue.
