### ISSUE TITLE
Table view when editing causes the panel data to not update

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#34820]
**What happened**:

Setting visualisation to "Table view" when editing causes the panel data to not update.

**What you expected to happen**:

Updating a query when in the new "Table view" mode should still show new data as it's updated. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new panel using gdev-testdata data source, configured as:
   - Scenario: CSV Metric Values
   - String Input: hello_world
2. Configure the panel to use the Table visualisation
3. Change the 'String Input' in query editor
   - _Observe that the value updates correctly in the visualisation_ 😄 
4. Turn on the "Table view" mode
5. Change the 'String Input' in query editor
   - _Observe that the value does not update in the "table view" visualisation_ 😢 
6. Turn "Table view" mode back off
   - _Observe that the value still has not updated in the visualisation_ 😐
3. Change the 'String Input' in query editor
   - _Observe that the value updates correctly in the visualisation_ 😄 
  
I also replicated this issue using similar steps with the Azure Monitor data source, so the issue seems to be independent to the data source.

_Originally posted by @joshhunt in https://github.com/grafana/grafana/issues/34624#issuecomment-847703102_

**Comment by torkelo** [comment]
@axelavargas this one is tricky, think we will have to wait with this one. Will require a bigger refactoring

**Comment by torkelo** [comment]
the problem is that when enabling table view we are not rendering the DashboardPanel (& PanelChrome), and the thing that actually listens to refresh events and issues another query is being done in PanelChrome, so without rendering the real panel there is nothing that issues the new query

**Comment by axelavargas** [comment]
@torkelo yes, I figure out the logic behind this issue on Friday 😅, I noticed  the `PanelRenderer` component is not subscribing to the `RefreshEvent` that is triggered in the `QueryEditor`, my plan was to add these subscription events into `PanelRerendered` but I wanted to confirm if you have another approach in mind.
