### ISSUE TITLE
html special characters in aliases/queries

### ISSUE THREAD

**Issue by Griesbacher** [grafana/grafana#3482]
When a html special char is within a alias or query, it will be replaced in the GUI with the special char. In the title the char is not replaced. It would be nice if there is a flag which flips this behaviour globally, ether it is shown as plain text(what I prefer) or is replaced with the corresponding special char.

The title contains the same text as the alias:
![grafana](https://cloud.githubusercontent.com/assets/12564488/11710804/2aa59614-9f22-11e5-9f45-d1efecfe8530.PNG)
I'm not sure if this is a bug or a feature :wink:

**Comment by torkelo** [comment]
you can use the special chars directly, no need to escape them

**Comment by Griesbacher** [comment]
I don't want them displayed as special chars, that's my problem. The name of the datasource is per accident the same as the escape sequence.
