### ISSUE TITLE
Adding the possibility of custom ordering of legends in stacked series

### ISSUE THREAD

**Issue by AnesBendimerad** [grafana/grafana#34845]
First of all, I would like to thank the Grafana community for the significant effort devoted to develop such a powerful and wonderful tool.

I have a question related to stacked series. 

When we use the "graph" visualization to show stacked series (in my case, retrieved from InfluxDB with flux), the order in which series are stacked is alphabetical. For example: 
![image](https://user-images.githubusercontent.com/12132263/119864694-30485100-bf1b-11eb-8c8f-6e122444018c.png)

It starts by ADMINISTRATIVE, then APPLICATION, then COMMIT, etc.
I would like to enforce a custom order (e.g., start by CPU, then Scheduler, then USER I/O, then SYSTEM I/O, etc.). Is this currently possible? if not, is it something that can be added in future versions ? For example, it can be a text field in which we specify the order:
![image](https://user-images.githubusercontent.com/12132263/119865390-e875f980-bf1b-11eb-9d3b-d60e3657413c.png)

Many thanks.

**Comment by torkelo** [comment]
you can add a join transform to join the data into one table/frame. then use the "Organize fields" transform to change order

**Comment by AnesBendimerad** [comment]
The solution that you proposed have perfectly worked for me. Thank you for your help!
![image](https://user-images.githubusercontent.com/12132263/119946775-498ee300-bf97-11eb-88cd-90046e655444.png)
