### ISSUE TITLE
POST request redirected to GET

### ISSUE THREAD

**Issue by pawanrawal** [grafana/grafana#3485]
Grafana makes a POST request to `https://host_name/api/datasources/proxy/5//_msearch?search_type=count` which returns a 301 redirect to a GET request to the same url which returns `{"error":"ElasticsearchParseException[Failed to derive xcontent]","status":400}`
Any reason why might this be happening ? 

Also the first POST request is not logged in `/var/log/grafana/grafana.log` but the second request is . What am I missing here ?
![screen shot 2015-12-10 at 5 50 56 pm 2](https://cloud.githubusercontent.com/assets/7247941/11715468/2d1cd074-9f68-11e5-89cc-4917d88aa023.png)
![screen shot 2015-12-10 at 5 51 04 pm 2](https://cloud.githubusercontent.com/assets/7247941/11715469/2ee12c98-9f68-11e5-9c07-9b85bdeda43d.png)

**Comment by torkelo** [comment]
maybe wrong version of elasticsearch? What version are you using?

**Comment by pawanrawal** [comment]
have a look at the screenshots please. They might help. I don't think there is any problem with elastic search.

**Comment by torkelo** [comment]
what screenshot? Why do you think there is no problem? Your elasticsearch server is returning an error ElasticsearchParseException , what version are you using? what is the query?

**Comment by pawanrawal** [comment]
Why is the POST request being redirected to a GET request ? Also why is the POST request not logged and the GET is. I am not saying there is a problem with grafana but if you can answer these questions, it might help me debug this issue ?

Thanks

**Comment by torkelo** [comment]
why the post is redirected to GET? I don't know ask your Elasticsearch server :)

**Comment by torkelo** [comment]
I am trying to help you by asking you questions to understand your setup more. For example whats your Elasticsearch version, did you specify timefield and index correctly, whats your query, etc

**Comment by pawanrawal** [comment]
Elastic search version - 1.7
Yes the timefield and index are correct 

`curl 'http://host/api/datasources/proxy/1//_msearch?search_type=count' -H 'Origin: http://host' -H 'Accept-Encoding: gzip, deflate' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.73 Safari/537.36' -H 'Content-Type: application/json;charset=UTF-8' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://host/dashboard/db/gross-numbers-total' -H 'Cookie: grafana_sess=c13817ef955f2ada' -H 'Connection: keep-alive' -H 'X-FirePHP-Version: 0.0.6' --data-binary $'{"search_type":"count","ignore_unavailable":true,"index":"logstash-aggregated-nthday"}\n{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"*"}},"filter":{"bool":{"must":[{"range":{"time":{"gte":"1418211122721","lte":"1449747122721"}}}]}}}},"aggs":{"2":{"date_histogram":{"interval":"1d","field":"time","min_doc_count":1,"extended_bounds":{"min":"1418211122721","max":"1449747122721"}},"aggs":{"1":{"sum":{"field":"events.collection_create"}}}}}}\n' --compressed`

This POST request is redirected to a GET which returns this error.

**Comment by pawanrawal** [comment]
The above is the request made by Grafana . I have picked this up from the Network tab in Chrome dev tools.

**Comment by torkelo** [comment]
ok, and what is the redirect address? can you show the raw result?

**Comment by torkelo** [comment]
I am not sure why your Elasticsearch server is redirecting, do you have some proxy infront of elasticsearch or using some Elasticsearch auth or hosting service?

**Comment by pawanrawal** [comment]
I got the issue now. Since grafana web makes a request to `curl 'http://host/api/datasources/proxy/1//_msearch?search_type=count'` , my oauth2 proxy in front of grafana web server redirects this because of the `//` in the url before `msearch`. Any reason why you have this non standard path ?

**Comment by torkelo** [comment]
No reason, that was a bug, fixed in  master and 2.6 builds

**Comment by pawanrawal** [comment]
Thanks that solved my issue.
