### ISSUE TITLE
Improve Tracing Explore History Panel

### ISSUE THREAD

**Issue by joe-elliott** [grafana/grafana#34855]
**What would you like to be added**:
More detail in the trace query history panel.  The most obvious thing to add is the root span name and service name. This is already displayed in the trace view so hopefully it's not too hard to extract. Technically this could be extended to include other process tags of the root span as well.

**Why is this needed**:
Currently the only contents of the panel is the trace id searched for. This is not particularly useful when reviewing search history because it's difficult to distinguish between a bunch of opaque trace ids.

![image](https://user-images.githubusercontent.com/2272392/119892498-354fd500-bf08-11eb-905f-91b11f980657.png)

**Comment by ifrost** [comment]
This can be done as part of #26192

**Comment by ifrost** [comment]
Query history uses only the query itself to create query description, not the results of the query. We'll take this scenario into account when working on improvements for query history in https://github.com/grafana/grafana/issues/26192. I'm closing this issue for now but feel free to continue the discussion in https://github.com/grafana/grafana/issues/26192.
