### ISSUE TITLE
Regex matching for the new Value Mapping

### ISSUE THREAD

**Issue by Kohen-lab** [grafana/grafana#34878]
**What would you like to be added**:

A way to use regex in value mapping so we could match part of a value, as an example : 
![image](https://user-images.githubusercontent.com/80967120/119953051-e2286180-bf9d-11eb-8f3d-08756216cf24.png)

Here it would be nice to have the field be red when the word Failure is matched in the name.

**Why is this needed**:

Helps for better visibility in table graphs adding color more dynamically

**Comment by torkelo** [comment]
closing this as as we had an older issue for this https://github.com/grafana/grafana/issues/15877
