### ISSUE TITLE
Font problem with image rendering

### ISSUE THREAD

**Issue by commarla** [grafana/grafana#3487]
Hi,

Grafana beta1 or beta2 install on new server has this issue : 
![image](https://cloud.githubusercontent.com/assets/4509360/11717954/d0f6a6a8-9f53-11e5-9fe4-cf70751a3f42.png)

I think there are some font missing somewhere on my server?
I am using en_US.UTF-8 encode on the server.

Regards,

**Comment by torkelo** [comment]
try installing font packages on the server, required by the phantomjs server side rendering
