### ISSUE TITLE
Help colour blind users by using different symbols when drawing graphs

### ISSUE THREAD

**Issue by daenney** [grafana/grafana#34882]
**What would you like to be added**:

When drawing graphs with multiple time series, all series are drawn in the same way aside from their colour. However, for colour blind people this is often not enough to be able to distinguish between two lines.

Consider drawing each series in the panel with a different symbol, instead of everything being a solid line. For example, make each point in the graph that you're connecting distinct, and use dots, dashes, triangles, squares etc. to make each series visually distinct without relying solely on colour.

**Why is this needed**:

Improve accessibility for colour blind people.

Relates to: #21120, #18041

**Comment by leeoniya** [comment]
it"s being tracked as a todo item here: https://github.com/grafana/grafana/issues/30564

**Comment by daenney** [comment]
Brilliant, hadn't seen that one. I'll close this one then!

**Comment by daenney** [comment]
It does seem like https://github.com/grafana/grafana/pull/30192 which would solve this went stale and got closed by the bot. That's unfortunate.
