### ISSUE TITLE
Typo in grafana.ini - secret_kiey 

### ISSUE THREAD

**Issue by linuxbutler** [grafana/grafana#3489]
Hi 

Just installed 2.6.0-beta1, and comparing the old grafana.ini with the new one. 
I noticed that in 2.6.0-beta1, under the security section, there appears to be a typo: 

 # used for signing
;secret_kiey = SW2YcwTIb9zpOOhoPsMm

In the previous config file, this was 
 # used for signing
;secret_key = SW2YcwTIb9zpOOhoPsMm

I think that extra "i" is erroneous ? 

Thanks!

**Comment by bergquist** [comment]
Yea its an error.
The config seems correct in git.

https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L115

did you use any provisioner to install it?
Seems like an vim error :)

**Comment by linuxbutler** [comment]
Yeah I thought so too, a vim error.  Happens a lot to me too. 

I just downloaded the grafana-2.6.0-beta1.x86_64.rpm package manually from the internet, and used yum localinstall for the installation. 

Thanks again.

**Comment by bergquist** [comment]
Happens to all of us :)

I'm closing this issue.
