### ISSUE TITLE
LibraryPanels: Go back button triggers save modal even when no changes have been made

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#34891]
**What happened**: Save modal is triggered every time I leave panel edit for a library panel

**What you expected to happen**: Save modal shouldn't appear if I haven't made any changes

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard and a panel. Convert the panel into a library panel.
2. Go into Panel edit and click Save library panel
3. Click on `Go back` or press Esc
4. Should trigger Save modal even though I just saved

![image](https://user-images.githubusercontent.com/434655/119974623-2ecb6700-bfb5-11eb-8197-72a51d52312c.png)

Test dashboards: 
- https://g80-beta.grafana.net/d/-zopi9qGk/librarypanel-issue?orgId=1
- https://g80-beta.grafana.net/d/JuWZgrqMz/azure-monitor-cross-squad-testing?orgId=1&editPanel=2

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta2
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu and Chrome

**Comment by hugohaggmark** [comment]
I had a look, and it seems our configRevision solution in PanelModel isn't completely solid (yet) 

What happens is that some data sources like Azure Monitor and DataDog call `updateQueries` as part of their initialization. Any call to `updateQueries` will increment the configRevision.
https://github.com/grafana/grafana/blob/886f6fc55b32d271177587c2da4a5f93e98cb91d/public/app/features/dashboard/state/PanelModel.ts#L417

Other data sources like Postgres don't call `updateQueries` and then it works https://g80-beta.grafana.net/d/S8apI93Gz/azure-monitor-cross-squad-testing-copy?orgId=1&editPanel=6.

The consequence for all this is that we can't trust `panelModel.hasChanged` property and need to find another solution. Not sure what that is. 
Maybe we should only increment the config revsion when the queries differ between calls? Not sure that is possible though.

Any other suggestions @dprokop @torkelo

**Comment by hugohaggmark** [comment]
To make things even worse, seems (at least Azure Monitor) mutates `this.targets` on the PanelModel directly so there's no way for us to know `before` and `after` states unless we introduce Proxies.

**Comment by sunker** [comment]
Yes unfortunately, the Azure Monitor query ctrl is still in angular. All sub datasources are migrated to react though, so the mutating of `this.target` would have been fairly easy to solve if it wasn't for the fact the so many [migrations](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/query_ctrl.ts#L142-L153) are being done in the queryCtrl. Testing all those after a react migration would be painful and something that almost certainly introduces bugs. For this reason, I'd like to wait with this change in the Azure Monitor datasource until 8.1 when we have more time.

**Comment by natellium** [comment]
Closing this as we can't fix it at the moment. Creating a better change tracker will take care of this in the future.
