### ISSUE TITLE
FLUX time range not reflected in Grafana 

### ISSUE THREAD

**Issue by stefanbie** [grafana/grafana#34903]
Hi!
When I set a time range in a FLUX query it is ignored by Grafana. 
Compare the times for query and request below:

Form query instpector:
```
from(bucket:"performance")
  |> range(start: 2021-05-10T14:00:00Z, stop: 2021-05-20T14:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "processed")
  |> filter(fn: (r) => r["_field"] == "average_us" or r["_field"] == "percentile_us" or r["_field"] == "max_us")

Object
request:Object
url:"api/ds/query"
method:"POST"
data:Object
queries:Array[1]
range:Object
from:"1622210308689"
to:"1622210608689"
hideFromInspector:false
response:Object
results:Object
A:Object
```
The time frame for the request is the Grafana time frame.

have tested on Ubuntu 20.08 with Grafana 7.2 and 8.00 beta2

**Comment by gabor** [comment]
hi @stefanbie , based on the data you provided, the influxdb server will receive the time-range "start: 2021-05-10T14:00:00Z, stop: 2021-05-20T14:00:00Z" as it is in the query.

the "from" and "to" numeric timestamps describe the time-range you specified in the grafana-ui. but, because the time-range is hardcoded in the flux-query, they will be ignored.

is there anything wrong with the situation?

**Comment by stefanbie** [comment]
Hi @gabor , yes, it is the grafana time range that is dispalyed, not the hardcoded FLUX time frame.

**Comment by gabor** [comment]
@stefanbie the way grafana works is that you choose the time-range at the top of the screen, and then the visualizations show that time-range.

in case of Flux queries, you can use the the `v.timeRangeStart` and `v.timeRangeEnd` variables to use the chosen time-range in your flux query, for example like this:

```
from(bucket: "mybucket")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
```

of course, you can also put fixed date timestamps in your query, like this
```
from(bucket: "mybucket")
  |> range(start: 2021-05-10T14:00:00Z, stop: 2021-05-20T14:00:00Z)
  |> filter(fn: (r) => r["_measurement"] == "cpu")
  |> filter(fn: (r) => r["_field"] == "usage_idle")
```

but the visualizations (graphs) shown in grafana will still be set to the time-range that you chose in grafana (at the top of the screen).

i hope this explains the situation. if i misunderstood the situation and this is a different issue feel free to reply and we can reopen the issue.
