### ISSUE TITLE
Can I use Elasticsearch as dashboard storage?

### ISSUE THREAD

**Issue by zdenekpizl** [grafana/grafana#3491]
Hallo,

 we're using v1.9 and going to upgrade v2.5. Is there still option to keep dashboards in Elasticsearch? Reason is simple - ES has pretty nice HA + failover features hardly achievable by sqlite/mysql/postgresql.

So it would be nice to have this option - store dashboards's definitions still in Elasticsearch.

Thank you, regards Zdenek Pizl.

**Comment by bergquist** [comment]
No, Sorry.

They have to be imported into the database. 

Setting up HA for postgres and mysql might be tricky but on the other hand very easy to backup.

/CB

**Comment by zdenekpizl** [comment]
It is a pity indeed. We have HA Graphite with multiple Graphite-API nodes providing also grafana-1.9 UI. Users can access any of those nodes and create dashboards which are then populated among ES nodes and are (de facto) accessible immediatelly on every grafana's UI nodes.

This is not possible using advanced version 2.x. Well ...
