### ISSUE TITLE
Tempo: test data source using new echo endpoint

### ISSUE THREAD

**Issue by kvrhdn** [grafana/grafana#34919]
_This is kind of a follow up to #32677 and the PR #34762._

In #34762 we improved the test data source implementation by checking the body of the response from Tempo. The Tempo team is not comfortable making the body of a 404 response part of our stable API, so instead we are currently adding a separate endpoint specifically for testing: `/api/echo` (https://github.com/grafana/tempo/pull/714).

This endpoint is added to the query frontend and exists next to the regular query endpoint (`/api/traces/{traceID}`).

So we should change this to use the echo endpoint instead: https://github.com/grafana/grafana/blob/d6037a49b69a1293e2390749cc6e1622dfe1b2bc/public/app/plugins/datasource/tempo/datasource.ts#L93-L107

I don't mind picking this up, but with the Grafana backend in between the frontend and Tempo this is a bit more involved. So I could use some guidance on the best way to expose this echo endpoint to the frontend 🙂

**Comment by zoltanbedi** [comment]
I can see two ways to solve this you can define the CheckHealth function in the backend https://github.com/grafana/grafana/blob/main/pkg/api/plugins.go#L318

or use getBackendSrv from the frontend to make a request like here https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/influxdb/datasource.ts#L475

**Comment by kvrhdn** [comment]
Okay, I've been digging through the code and I think I'm stuck again...

So I'm trying to implement a `CheckHealth` function in the backend, this seems to be the cleanest solution.

The check health request from the frontend enters the backend here: https://github.com/grafana/grafana/blob/1c49986b2f2e36179159258517696353a5ea01c8/pkg/api/datasources.go#L429-L431

But this function fails when it tries to get the `DataSourcePlugin` from the `PluginManager`: https://github.com/grafana/grafana/blob/1c49986b2f2e36179159258517696353a5ea01c8/pkg/api/datasources.go#L442-L445

I'm don't think the Tempo datasource implements `DataSourcePlugin`, it seems to still use the deprecated `plugins.DataPlugin`. Maybe we should add an implementation of `DataSourcePlugin` and register that somewhere?

**Comment by zoltanbedi** [comment]
I'm not sure what's up with that. Maybe @wbrowne can help?
