### ISSUE TITLE
Add PDF file export function

### ISSUE THREAD

**Issue by T3fan** [grafana/grafana#34929]
What?
Add PDF file export function （like Tableau）

Why?
Very nice Dashboards tool, but it can't generate PDF report.
Advise to add a function to export Dashboard and Dashboard folder to PDF report

![图片](https://user-images.githubusercontent.com/5149108/120020154-f0b55e00-c01b-11eb-9755-222341732883.png)

**Comment by torkelo** [comment]
This is an Grafana Enterprise feature so closing this
