### ISSUE TITLE
time range

### ISSUE THREAD

**Issue by caotic112** [grafana/grafana#3492]
On influxdb 0.9 the now() - xM doesn't work.The accepted parameters are:
u microseconds
s seconds
m minutes
h hours
d days
w weeks

**Comment by torkelo** [comment]
What version are using? Think this is fixed in master and 2.6

**Comment by caotic112** [comment]
2.5.0 , i'll try the 2.6, still a question, with big range time my influxdb crash with nothing in the log, what could be the problem?

**Comment by torkelo** [comment]
The problem is that your using InfluxDB, it crashes all the time
