### ISSUE TITLE
When a single result is displayed using Bar Gauge, Legend is no longer viewable. 

### ISSUE THREAD

**Issue by Phara0h** [grafana/grafana#34926]
**What happened**: When a single result is displayed using Bar Gauge, Legend is no longer viewable. 

**What you expected to happen**: The Legend to be viewable as it is for anything with more than 1 result.

**How to reproduce it (as minimally and precisely as possible)**: Create a Bar Guage and have it only have 1 field. 

**Environment**:  Production
- Grafana version: 8.0.0-beta2
- Data source type & version: Prometheus (latest)
- OS Grafana is installed on: AWS Linux
- User OS & Browser: Mac Google Chrome

 Here are some screenshots showing the behavior. 

![Screen Shot 2021-05-28 at 12 30 04 PM](https://user-images.githubusercontent.com/1054802/120015163-05104100-bfb1-11eb-8649-4e5bb2ec3327.png)
![Screen Shot 2021-05-28 at 12 29 55 PM](https://user-images.githubusercontent.com/1054802/120015172-06da0480-bfb1-11eb-8054-b047e7c293f2.png)

If this is not a bug please change the type to enhancement, please.

**Comment by torkelo** [comment]
this is by design, you can set the Display name property under `Standard options` to get the legend to show even when there is only one series

**Comment by Phara0h** [comment]
> this is by design, you can set the Display name property under `Standard options` to get the legend to show even when there is only one series


Display Name does not allow things like this `{{method}} {{route}}` so should I make a ticket for an "enhancement that Display Names support templating since it seems you are 100% against legend showing (or even having an option of the showing) when there is only 1 result?
