### ISSUE TITLE
Data links and sorting/filtering in tables

### ISSUE THREAD

**Issue by KBac** [grafana/grafana#34927]
**What happened**:
In a table panel I created a data link for a field. And in the data link I used the macro "${__data.fields[fieldName]}". If the table is not sorted and not filtered then the data link uses the "fieldName" value from the same row. If I click on any column header to sort the table or filter values then the data link uses the "fieldName" value from another row.

**What you expected to happen**:
Correct data links regardless of sorting/filtering mode for the table.

**How to reproduce it (as minimally and precisely as possible)**:
Create table panel with several columns. Add data link "${__data.fields[fieldName]}". Sort the table by different columns. Filter values. Check if the data link uses correct value.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
update to latest 7.5 and it is fixed
