### ISSUE TITLE
Add a Sharing privilege management function

### ISSUE THREAD

**Issue by T3fan** [grafana/grafana#34928]
the link only share  to viewer.
![图片](https://user-images.githubusercontent.com/5149108/120018154-57854800-c019-11eb-826c-0db469570af3.png)

some times, many Dashboards need to show to anonymous users, so they can view anonymous privilege Dashboards and not need to login.

so advise to add a Sharing privilege management function as follow:

![图片](https://user-images.githubusercontent.com/5149108/120018460-c5317400-c019-11eb-9039-3469c934d261.png)

**Comment by torkelo** [comment]
This is not possible given Grafana's current query permission logic, If you want to share to an anonymous user you can use the Snapshot feature that can be found within the share modal. It captures and store the data currently being visualized and can be shared without a user needing query access to the data source

**Comment by T3fan** [comment]
> 
> 
> This is not possible given Grafana's current query permission logic, If you want to share to an anonymous user you can use the Snapshot feature that can be found within the share modal. It captures and store the data currently being visualized and can be shared without a user needing query access to the data source

the way only show a page to anonymous user every time，

if you  show many Dash Folders to anonymous user,  the way is low efficiency.
