### ISSUE TITLE
disable viewers to inspect or download data

### ISSUE THREAD

**Issue by T3fan** [grafana/grafana#34931]
What:
disable viewers to inspect or download CSV

why?
read-only mode, protect data, reduce server pressure.
so advise to add a disable switch

![图片](https://user-images.githubusercontent.com/5149108/120021960-51de3100-c01e-11eb-89eb-52088a1374c7.png)
![图片](https://user-images.githubusercontent.com/5149108/120022017-66bac480-c01e-11eb-94e5-ebf9a1dd09f4.png)

![图片](https://user-images.githubusercontent.com/5149108/120021754-0fb4ef80-c01e-11eb-96ee-98499bb27fe2.png)

**Comment by torkelo** [comment]
This does not make that much sense, the data is already sent to the browser so it can be visualized, so hiding the inspect drawer adds no security. Any user can download the data via the query API if they wanted to

**Comment by T3fan** [comment]
> Any user can download the data via the query API if they wanted to

this is programmer‘s mind, not designed by User's mind, not all customers have this ability
