### ISSUE TITLE
Improve chart zoom function

### ISSUE THREAD

**Issue by T3fan** [grafana/grafana#34933]
what?
Improve chart zoom function

why？
1.Not everyone needs zoom chart by mouse.
2. Chart renew to default time range is too troublesome if it zoomed by mouse

advice：
add a button on settings，enable or disable zoomed chart by mouse.
add a zoom button on chart, replace mouse.
add a default button on chart, quickly switch chart to default time range if click it.

![图片](https://user-images.githubusercontent.com/5149108/120025356-227df300-c023-11eb-9953-a84e557095a0.png)

![图片](https://user-images.githubusercontent.com/5149108/120025754-bea7fa00-c023-11eb-98c3-dcd8b5c66261.png)

![图片](https://user-images.githubusercontent.com/5149108/120025644-95876980-c023-11eb-86f3-fa723d6a01ee.png)

**Comment by torkelo** [comment]
not sure this option makes that much sense, but we can add an easy way to reset/go back to the default time range. 
https://github.com/grafana/grafana/issues/4973 

You can use the back button on your browser to undo a time range change
