### ISSUE TITLE
Clock Transparency Not Working

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#34942]
**What happened**: Transparency slider has no effect on panel

**What you expected to happen**: Panel should be transparent

**How to reproduce it (as minimally and precisely as possible)**: Create clock panel, enable transparency via slider

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.0-beta2
- Data source type & version: influx 1.8.6-1
- OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+
- User OS & Browser: Brave, Chrome
- Grafana plugins: Clock
- Others:
![image](https://user-images.githubusercontent.com/510960/120046480-dd809f00-bfd7-11eb-8a98-20f5224f800b.png)
![image](https://user-images.githubusercontent.com/510960/120046513-effad880-bfd7-11eb-86c7-87b4673b6c0c.png)

**Comment by underdog** [comment]
![image](https://user-images.githubusercontent.com/510960/120046553-086af300-bfd8-11eb-96ed-dee23dc33186.png)
forgot the pic of the slider on

**Comment by torkelo** [comment]
this looks like the same issue as https://github.com/grafana/grafana/issues/34943 (same root cause)
