### ISSUE TITLE
Clock Background Not Working

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#34943]
What happened: Color picker has no effect on panel

What you expected to happen: Panel background should be modified

How to reproduce it (as minimally and precisely as possible): Create clock panel, select background color

Anything else we need to know?:

Environment:

Grafana version: Grafana v8.0.0-beta2
Data source type & version: influx 1.8.6-1
OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+
User OS & Browser: Brave, Chrome
Grafana plugins: Clock

![image](https://user-images.githubusercontent.com/510960/120046688-541d9c80-bfd8-11eb-8027-951e93d33725.png)
![image](https://user-images.githubusercontent.com/510960/120046715-6697d600-bfd8-11eb-9350-8a326d0af1f2.png)

**Comment by torkelo** [comment]
unable to replicate in main with a dev build, but can replicate on 8.0-beta2, we will investigate

**Comment by hugohaggmark** [comment]
Issue already reported in plugin repo https://github.com/grafana/clock-panel/issues/92

**Comment by torkelo** [comment]
think we need to investigate this, I could not replicate in a dev build with latest built clock panel but many are seeing this

**Comment by jackw** [comment]
There's an open PR grafana/clock-panel/pull/94 in the clock panel that solves this issue. I'll be publishing the fix later today.

**Comment by jackw** [comment]
Have published clock panel v.1.1.3 which fixed this issue: https://github.com/grafana/clock-panel/releases/tag/v1.1.3
