### ISSUE TITLE
Local admin not allow with LDAP enable

### ISSUE THREAD

**Issue by Isma399** [grafana/grafana#3495]
Since I enabled LDAP authentification, I have no more access with the login admin to grafana.
I tried to disable LDAP, reset admin password to default in grafana.ini but  grafana admin access is still forbidden.
I have no right to  create a ldap group in my organization.

Here's my grafana.ini :

    admin_user = admin
    admin_password = admin

Here' s my working ldap.toml:

    bind_dn = "uid=xxx,ou=people,dc=organization,dc=dom"
    bind_password = 'password'
    search_filter = "(&(departmentNumber=SI*)(uid=%s))"
    search_base_dns = ["ou=people,dc=organization,dc=dom"]
     [servers.attributes]
    name = "givenName"
    surname = "sn"
    username = "cn"
    member_of = "memberOf"
    email =  "mail"      

*deparmentNumber=SI, because we work in SI1 & SI2*
With this config, no admin access.

Logs seems fine : 
    
>  2015/12/11 12:59:42 [I] Login: Ldap enabled, reading config file: /etc/grafana/ldap.toml
> 2015/12/11 12:59:53 [I] Ldap User Info: (*login.ldapUserInfo)(0xc2080c90a0)({
>DN: (string) (len=41) "uid=imyname,ou=people,dc=organization,dc=dom",
> FirstName: (string) (len=6) "myname",
> LastName: (string) (len=6) "lastname",
> Username: (string) (len=13) "Tlastname myname",
 >Email: (string) (len=27) "mail@organization.dom",
 >MemberOf: ([]string) {
> }
>})

    

Adding  

    [[servers.group_mappings]]
    #group_dn = "*"
    #org_role = "Admin"

  
gives obiousvly admin right to everyone, but  that's not what I want.

I've tried this but don't work too 

    [[servers.group_mappings]]
    #group_dn = "uid=myname,ou=people,dc=organization,dc=dom"
    #org_role = "Admin"

I only need one admin access for a local user or one LDAP user but I don't how to manage it. Could you help me?
Thanks

**Comment by torkelo** [comment]
it looks like you have commented out the role mapping with the `#` char

**Comment by Isma399** [comment]
Oups, no.
I tried that 
    
    [[servers.group_mappings]]
    group_dn = "uid=myname,ou=people,dc=univ-brest,dc=fr"
    org_role = "Admin"

**Comment by torkelo** [comment]
it does not look like your use is member of any groups, 
This is empty. 
```
MemberOf: ([]string) {
}
```

So for this 
```
[[servers.group_mappings]]
group_dn = "uid=myname,ou=people,dc=univ-brest,dc=fr"
org_role = "Admin"
```

to work you need , `uid=myname,ou=people,dc=univ-brest,dc=fr` as a group dn in member_of

**Comment by Isma399** [comment]
In [servers.attributes] ? 
This doesn't work : 
    
    [servers.attributes]
    name = "givenName"
    surname = "sn"
    username = "cn"
    member_of = "uid=myname,ou=people,dc=univ-brest,dc=fr"
    email =  "mail"

**Comment by torkelo** [comment]
member_of needs your ldap attribute where you have ldap groups memberships

**Comment by torkelo** [comment]
if you do not have ldap groups you can use this:
[[servers.group_mappings]]
group_dn = "*"
org_role = "Admin"

**Comment by Isma399** [comment]
OK, but how can I restrict admin org_role to one user?
Thanks for you help.

**Comment by zstyblik** [comment]
@Isma399, have you figured it out? Of course, except manually assigning admin to specific user via web ui.

Thanks

**Comment by Isma399** [comment]
No sorry, I disabled admin access except when it's needed.
