### ISSUE TITLE
There is any  easy  and clean way to add piwik tracking client to grafana?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#3496]
I would like to add piwik analytic to grafana to track usage but I would prefer avoid the direct html/javascript editing.

There is any good way to do that?

**Comment by torkelo** [comment]
no, only google analytics

**Comment by toni-moreno** [comment]
Could be interesting if we can add a plugable way to add different analytic clients in grafana. Are you agree?
We can help in this new feature if you want.

**Comment by torkelo** [comment]
you can do that, via google tag manager

**Comment by torkelo** [comment]
which is also supported

**Comment by toni-moreno** [comment]
Sorry for my ignorance @torkelo on how these analytics clients works.

Could the google analytics client built in grafana be integrated with a  piwik server ?

The matter is we are working inside a corporation and its security policy   prohibit sending data outside and force the use of the piwik client in all their web based tools.

how can I do that?

**Comment by torkelo** [comment]
you can use google tag manager to inject the piwik script tag
