### ISSUE TITLE
Elasticsearch: Support inline scripts for metrics 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3500]
Enhancement to Elasticsearch query editor, All non pipeline metric aggregations now support inline script and missing options:

![image](https://cloud.githubusercontent.com/assets/10999/11750431/9f4a45fc-a033-11e5-8101-5fce3f785b3b.png)

**Comment by wbedard** [comment]
My apologies in advance as I am relatively new to Grafana+ElasticSearch.  In trying out this feature, I keep getting a "Parse Failure" error from ES.  After reviewing the ES scripting specs (for both 1.7, which I am using, but also for 2.x), I see no mention of the "inline" keyword, which you hardcode after "script", into every query containing an inline script.  The ES specs state that the "script" keyword implies an inline script and that index or file-based scripts use slight variations to differentiate them.

When I fall back to Grafana 2.5.0, which provides the ES query editor, I don't get the Parse Error.  The only real difference is the omission of the "inline" keyword.  For example:

From Grafana 2.6.0:
...
"avg":{
  "field":"metric_value",
  "script":{"inline":"_value * 1"}
  }

From Grafana 2.5.0:
....
  "avg":{
    "field":"metric_value",
   "script": "_value * 1"
  }

Thanks in advance for your time and effort in reviewing this issue!

**Comment by faxm0dem** [comment]
[it seems](https://www.elastic.co/guide/en/elasticsearch/reference/2.1/modules-scripting.html) the recommended way is to disable inline scripts, and to use files instead. Would it be possible to allow for that? basically the inline script is copied to a file, which is executed by ES (much more secure)
