### ISSUE TITLE
Search: Do not update query in URL for every keystroke 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#35010]
Search feels a bit sluggish when typing, my suspicion is that it's because we update the url onChange and this triggers a full route re-render (incl sidemenu). Think we should change this to onBlur instead (ie update URL). This might improve performance.

**Comment by Clarity-89** [comment]
I'm not sure using onBlur here will work, especially in the case when user types an input and refreshes the page. Plus URL setting is tied to onChange logic of the search query.

 What could be done instead is to debounce the setting of the URL inside the functions in [useSearchQuery](https://github.com/grafana/grafana/blob/main/public/app/features/search/hooks/useSearchQuery.ts#L24) hook but I also feel like there should be sone kind of middleware or smth that would handle this URL setting side effect search query changes.

**Comment by torkelo** [comment]
@Clarity-89 yea a high debounce time might be best
