### ISSUE TITLE
Grafana InfluxDB 5m range only part of the graph appears

### ISSUE THREAD

**Issue by akiskourtis** [grafana/grafana#3501]
I have setup a grafana, influxdb system and want to fetch every second from Influxdb and display the last 5 minutes in grafana.

However this happens
![grafana-bug](https://cloud.githubusercontent.com/assets/1667681/11750928/d84344b6-a03e-11e5-96b5-b896d0dce059.png)

There seems to be a threshold where from this moment and before the graph stops to appear,
If I zoom to previous periods data and graphs reappear. If I increase the range the threshold will go a bit back but never spread to the whole graph.

![grafana-bug2](https://cloud.githubusercontent.com/assets/1667681/11751017/7e3d0a78-a03f-11e5-9658-12418779b7a0.png)

I use group time 1s, and for each metric also 1s.

Do you have any clue, what might be the cause?

The requests from influxdb seem to be returning just fine

Thank you!

**Comment by torkelo** [comment]
maybe there the time is off between your local machine or your influxdb server? Or an influxdb bug.

**Comment by akiskourtis** [comment]
i see.. thank you for your response! I will look further into that, and post back if I find any solution/workaround.
