### ISSUE TITLE
AzureMonitor: Remove possibility of having different credentials for Logs and Metrics

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#35028]
**What would you like to be added**:
Remove possibility of having different credentials for Logs and Metrics. This was partly removed in 8.0 - since then, new users are not able to have different credentials for Logs and Metrics. 

**Why is this needed**:
This will simplify the code for handling routes, clouds and credentials.

**Comment by andresmgot** [comment]
Desired UX:

Users still using different Logs credentials will get an error message alerting that this feature is no longer supported. To help with a possible migration, the credentials fields can be made read-only:

![Screenshot from 2021-06-01 11-46-50](https://user-images.githubusercontent.com/4025665/120303626-4ebd9c00-c2cf-11eb-90a3-2967d90fef0a.png)

This is the (provisional) TODO list:
 - [ ] Remove code related to Log Analytics credentials
 - [ ] Remove/merge plugin.json routes using Log Analytics credentials
 - [ ] Adapt the datasource config to make Log Analytics credentials read-only

**Comment by kostrse** [comment]
What is the timing of the complete removal of different credentials?
Are you anticipating to start showing error in 8.1?

**Comment by andresmgot** [comment]
> What is the timing of the complete removal of different credentials?
> Are you anticipating to start showing error in 8.1?

Yes, the plan is to remove it for 8.1 (letting people to copy-paste things like the tenant ID in case they need to look for it). WDYT?
