### ISSUE TITLE
Auto add new queries for graphs over elastic search

### ISSUE THREAD

**Issue by jasw** [grafana/grafana#3504]
Hi all,

My use-case is for a SaaS solution, customers could create their own app servers. Each app server upon start up will post metrics continuously to a central elastic-search backend (shared). 

Metrics would be prefixed by the customer name and docker instance name. For example, customerA just created a web app with 2 instances, we can expect elastic search would have new records like this:

```
name:frontier.customerA.8faad85c2b73.jvm.memory.total.used @timestamp:December 11th 2015, 17:45:06.000 value:514,126,672 _id:AVGPW1bH7Iyo-sQmE48e _type:gauge _index:metrics-2015-12 _11
```

and

```
name:frontier.customerA.1b4b3019c488.jvm.memory.total.used @timestamp:December 11th 2015, 17:45:06.000 value:514,126,672 _id:AVGPW1bH7Iyo-sQmE48e _type:gauge _index:metrics-2015-12 _11
```

Now I could create a Grafana graph with queries against those two records by hard coding the customer name and instance name. 

The end memory usage graph looks like this:
![Per instance memory usage](http://i.imgur.com/HyFDkkf.png)

One of my many questions is, is there a way to automatically add a new query (via API calls from outside or internal polling on templated queries) to this graph?  I would also like to create alias matching the customer and instance names as shown in the graph (bottom left corner, red circled ). 

I guess that means I want a way to back reference a server term like `name:frontier.(.*).(.*).jvm.memory.total.used` and the alias field can set to `$1 - $2` to achieve what I manually created in the screenshot above. 

PS, I have been through the REST APIs Grafana provides but could not find anything operates on graph level.

Many thanks,

Jason

**Comment by torkelo** [comment]
you can update whole dashboards through the HTTP API

**Comment by jasw** [comment]
Thanks @torkelo . I think you meant to use the json dashboard and create new ones by templating the json and call the creating new dashboard?  Will give it a go. Is there a plan to have more granular APIs to support modifying dashboards based on graph, row etc?
