### ISSUE TITLE
Table Cell display mode Color background won't work with Thresholds in percent

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#35059]
Since Grafana Beta 2, the background color is no longer displayed in the table when you select percent.

![grafik](https://user-images.githubusercontent.com/79257887/120353616-16838100-c302-11eb-9039-2f9c80f5f63d.png)

![grafik](https://user-images.githubusercontent.com/79257887/120352889-87766900-c301-11eb-8211-4485b6758b7d.png)

**Comment by torkelo** [comment]
was unable to replicate this, works in beta3 at least https://play.grafana.org/d/Ehu5LNeGz/table-percent-thresholds?orgId=1

**Comment by UlrichThiess** [comment]
I'm sorry to waste your time, but there is realy a problem. Please look here:

https://www.zoomsoft.de/kap.mp4

Mybe it's because i installed grafane on Windows Server 2019?

**Comment by torkelo** [comment]
Ah I think it's the datalinks that might cause it

**Comment by UlrichThiess** [comment]
Can i support somehow?

**Comment by torkelo** [comment]
can you show your panel data and json? still unable to replicate

**Comment by UlrichThiess** [comment]
I have sent you an invitation to my installation. So you can work directly on my system and find the error.

As soon as you have registered, I will give you the necessary rights.

**Comment by UlrichThiess** [comment]
With Beta 1 it works, with Beta 2 it don't works.
See: https://www.zoomsoft.de/kap2.mp4

**Comment by UlrichThiess** [comment]
I found out the reason why this is happening.

Percent is specified as the unit, but with 0.0-1.0. Now 1-100% is displayed correctly, but the thresholds relate to the actual value and not, as up to 8.0.0 Beta1, to the displayed value.

Percent is one part per hundred. So - in my opinion - a threshold as a percentage should be given as 50%, but a threshold as a value as 0.5.

I removed the films.

Worked:

<img width="623" alt="grafik" src="https://user-images.githubusercontent.com/79257887/122717743-56d48000-d26c-11eb-9e96-00128ed1a892.png">

Not working:

<img width="615" alt="grafik" src="https://user-images.githubusercontent.com/79257887/122717896-871c1e80-d26c-11eb-954f-611f4460cee4.png">

**Comment by torkelo** [comment]
Percent is working as it should (with 50% or 80%), even with the unit 0-1 percent. The thing you are missing is setting a min & max, under standard options set min; 0, and max: 1 

![Screenshot from 2021-06-21 08-45-37](https://user-images.githubusercontent.com/10999/122718313-145f7300-d26d-11eb-91cd-53a848b45340.png)
![Screenshot from 2021-06-21 08-45-29](https://user-images.githubusercontent.com/10999/122718329-188b9080-d26d-11eb-908b-651316cb3777.png)

**Comment by UlrichThiess** [comment]
Many thanks for the help. That was different in Version 7 and 8.0.0 Beta 1. Should max and min not be set correctly with "Auto"?

**Comment by torkelo** [comment]
The auto behavior is not great, it's based on all columns 

https://github.com/grafana/grafana/issues/26383
