### ISSUE TITLE
Remove automatically increasing step value in Grafana dashboard for Gauge on more than 12 Hrs duration

### ISSUE THREAD

**Issue by sksingh20** [grafana/grafana#35065]
**What happened**: This is observed that crucial gauage data points lost when dashboard duration increased for more than 12 Hours. 

Objective of dashboard is not only to show beautiful graphs but to show clear data pointers for status of servers and applications.
Grafana team decision to alter and drop substantial data points will make Grafana useless when key business objectives are not met and even become misleading. There is no reason for Grafana team to modify step value which becomes adverse to business use case. 

**What you expected to happen**: Step value should not change on increasing duration. Substantial Data loss and wrong reporting is not acceptable just to show graphs. This needs to be given in documentation on max data points which can be handled by grafana. 

**How to reproduce it (as minimally and precisely as possible)**: Increase time duration of graph.
for six hour duration query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622040435&end=1622062035&step=15"

For 12Hour duration Grafa query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1622018980&end=1622062180&step=20"

for 7 days duration Grafana query is as follows:
url:"api/datasources/proxy/2/api/v1/query_range?query=IOT_Wstation%7Bparam%3D%22Power-Calc%22%2Cexported_instance%3D%2212%22%7D&start=1621457100&end=1622061900&step=300"

**Anything else we need to know?**: There was one input given by grafana team to use max_data_point with query. This is of no solution as duration itself is unknown when review status for last a week or longer or so. Again another input given as only 11K records is returned by Prometheus on query, which is also wrong as returnable records are much higher in number 5e7.

**Environment**: 
- Grafana version: Grafana 7.5.7
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

max_over_time(range-vector): the maximum value of all points in the specified interval.

**Comment by torkelo** [comment]
Please raise this with the prometheus project: https://github.com/prometheus/prometheus/blob/39d79c3cfb86c47d6bc06a9e9317af582f1833bb/web/api/v1/api.go#L424 

Making queries work or return expected results independent of time range requires understanding how the database query language and mechanics work (like query aggregations and sampling). Please read up on range vectors and prometheus functions: https://prometheus.io/docs/prometheus/latest/querying/basics/  

The step parameter is essential for how to turn instant queries into time series, Prometheus samples data every step, you then have to write in your query for the range of data that should be included in each step query.

**Comment by sksingh20** [comment]
@torkelo Issue raised with Prometheus for 11K records. However, with limitation of 11K records we should able to draw a graph for 40 Hours for scraps @15sec. Why graph is limited to only 1100 points?

**Comment by torkelo** [comment]
To not have more data points than pixels. Sorry just try to learn about range vectors and how Prometheus range queries work. 

You are the first in 5 years who think auto step is wrong and unable to understand or interested to learn you can write queries that read data between steps. Just add an aggregation function and range to your query

**Comment by sksingh20** [comment]
@torkelo Please find default dashboard of zabbix. This dashboard shows what business need to see. If I am missing a query you can help me how we can see 3 months view of data.

![image](https://user-images.githubusercontent.com/35199465/120594764-09c86f80-c45f-11eb-8fb6-84cd029b001b.png)

**Comment by sksingh20** [comment]
> To not have more data points than pixels. Sorry just try to learn about range vectors and how Prometheus range queries work.
> 
> You are the first in 5 years who think auto step is wrong and unable to understand or interested to learn you can write queries that read data between steps. Just add an aggregation function and range to your query

Objective is to solve business use case. Even if someone comes back after summer holidays, people will try to see status of server and application for last 3 months to have comparative view.

Data handling and data presentation are two different perspective.

**Comment by torkelo** [comment]
You need to learn how to write Prometheus queries, Grafana cannot know what data you are looking for. Have you tried adding max_over_time function and a range vector with  $__interval as the range? 

This is the same for every data source and query language, you have to add a group by time & aggregation function for the query to work consistently on different time ranges.

**Comment by sksingh20** [comment]
@torkelo I tried, but this is not giving expected result. You can try max_over_time for 3months duration on any gauge value graph. Max over time is purely maximum over time.
max_over_time(range-vector): the maximum value of all points in the specified interval.

**Comment by sksingh20** [comment]
@torkelo One of the remarks by Grafana team is as below:

https://github.com/prometheus/prometheus/issues/8887
**As far as I see, zabbix returns less than 900 points i your examples. The 11000 samples limit is not your issue I guess, as it is 10 times more than what you have provided as an example.

_Originally posted by @roidelapluie in https://github.com/prometheus/prometheus/issues/8887#issuecomment-853634295_**

**Comment by torkelo** [comment]
> max_over_time(range-vector): the maximum value of all points in the specified interval.

Yes, are you looking for something else besides max?

**Comment by sksingh20** [comment]
> > max_over_time(range-vector): the maximum value of all points in the specified interval.
> 
> Yes, are you looking for something else besides max?

Max is of no relevance. Max is just can be one of tiny requirement. 
Gauge values are instant state of application/parameter which is expected to be visualize.

**Comment by torkelo** [comment]
if your visualizing gauge / instant state, you should use an instant query, then no step is involved at all. 

But you had a graph? if the graph is visualizing a prometheus gauge then using an average as an aggregation function is usually the correct function (so avg_over_time)

**Comment by sksingh20** [comment]
@torkelo Since beginning of this issue, it is mentioned that this is for gauge. We still have some way to manage counter type.

Thank you sharing your view which clearly lacks enterprise experience. We now see Grafana as tool for lower environments. 
We noted limitation of Grafana and we will need to look into alternative solution who understand business use cases.

avg_over_time(range-vector): the average value of all points in the specified interval.

This limitation will be reported in CXO community to let CXO be aware of limitation of Grafana.

**Comment by torkelo** [comment]
Well if you're not interested in learning Prometheus or basic query mechanics like aggregation then I suggest you try something else.

**Comment by sksingh20** [comment]
Yes @torkelo  We need to try something else and reason for other CEO as well. 
Grafana want years of data to be accepted by company in 900 points. Such dashboard will only give junk values.

I must say that Grafana team is lacking actual enterprise requirements.

**Comment by torkelo** [comment]
Happily no one else agrees, of the million of users this is the first time someone fails to understand the need for query aggression.

But agree Prometheus is not easy to learn at first so you might be best with something else

**Comment by sksingh20** [comment]
@torkelo I am sure Grafana team have no view of criticality with gauge data.

Only God can help a patient if doctor/medical device start using Grafana!!!!

**Comment by torkelo** [comment]
Yes, maybe they will have to learn the database query language.

I am struggling understanding your lack of interest in learning how Prometheus works.

Prometheus has a very unique take on database and query mechanics which are very different.

**Comment by sksingh20** [comment]
@torkelo While you are referring again and again with Prometheus. Prometheus team confirmed that they are returning 11K records. Whereas you are only taking 1000 records to draw graph.

Prometheus team is feeling 11K records are good to draw graph.
Grafana team is thinking only 1000 records are enough to draw graph.

If this is not lack of experience and visibility on what Grafana team is drawing on dashboard?

**Comment by torkelo** [comment]
Getting more data points than pixels is not useful, and using dynamic step is what every Prometheus UI does to get graphs that work no matter if your using small or short time ranges.  

In 6 years working with Prometheus community, no one has complained about this :) they all learn how to write queries that use range vectors to get the desired data. 

If you showed your query and explained you data (how it is collected, the scrape interval) and what you want to visualize I might be able to help you.

**Comment by sksingh20** [comment]
@torkelo I see challenge in your default approach where you drop data upfront for all type of data by changing step value by its own. You need to understand every use case is different. You are treating every data as some number and you are not feeling that Guage data is instantaneous value of real life parameter. This can be Temperature, Blood reports, ECG reports etc..

This is always important and utmost important to have data visible on its raw form, the way it is captured. This is why I see Prometheus gives option to see data in raw form, average, max etc...

There can always be a requirement to see average, Max of points where different view of data can be observed with different way. As this needed observer/operator can switch mode. By switching mode observer/operator will be knowing that now he is getting approximation data and not real/raw data.
 
Gauge is purely instantaneous value of parameter, In my decades of years of experience we should not manipulate data. If you do then Grafana is no more tool of accuracy but remains a tool of high level approximation.

Your default approach is to put data with approximation like avg of data, increasing step value!! This can be dangerous and life threatening.

In my one of use case, there is graph showing how long servers where on Mains, Power backup and battery. There is instantaneous value. Requirement is to know how many times power switched modes and for how long. No avg graph needed, No Max graph needed only actual raw value needed.

Like If a patient in admitted in hospital for 3 months and doctor trying to visualize health... Doctor want to see actual value. No avg needed at all and so plenty of use cases.

Grafana failing in its approach when accuracy and precision is needed, where Grafana dropping data points.

Visualization and pixels challenge always there since decades. What you are trying to do is to dictate and force user than giving option to user to switch modes.

Its all about data handling when putting on graph. If more than one data point competing for single pixel, you can always gives a configuration option where competing data points will have avg/max/min. This have its own overheads. Optimum always a matter of debate.
In either case dropping data by its own for gauge value leaves graph with wrong/junk data based on usecase and accuracy needed.

**Comment by torkelo** [comment]
Sorry was really trying to help you understand how Prometheus works and how to write queries for prometheus. But my patience has run its course, hope you find a tool that solves your use case.

**Comment by torkelo** [comment]
> Requirement is to know how many times power switched modes and for how long.

This does not sound like a gauge. If you want to count things changing you need a counter in prometheus.

**Comment by torkelo** [comment]
> A requirement is to know how many times power switched modes and for how long

In Prometheus, you would do this with a counter, and a timer, one metric that counter that increments on state changes, and another that measures the duration of states.

**Comment by sksingh20** [comment]
@torkelo you switched gears instantly. 

You rely on prometheus but you drop 90% of data returnable from prometheus upfront.
Then you say you can't display 11K records and then you again say to check prometheus working!!! 

I said earlier base designer of Grafana have only thoughts of counter and lacks understanding of Gauge metrics.
If you think everything can be converted into counter metrics then just try to change your hemoglobin count of blood report in counters !!!

**Comment by torkelo** [comment]
I give up, trying to help you learn how time series and Prometheus works but you are clearly not interested to learn and just rude :disappointed: 

Prometheus is not a SQL database :)

**Comment by sksingh20** [comment]
@torkelo Prometheus returns raw data and you are again and again forcing to take approximation data because Grafana not able to handle raw data. You are not ready to accept things.

**Comment by torkelo** [comment]
well if you learned how to write a query so Prometheus scans the raw data it does not have to return all of it to Grafana. This is how Prometheus query language is designed, it's not designed so that it does not have to return all data (which would hang browsers when they zoom out / increase time range)

**Comment by sksingh20** [comment]
> well if you learned how to write a query so Prometheus scans the raw data it does not have to return all of it to Grafana. This is how Prometheus query language is designed, it's not designed to return all data (which would hang browsers when they zoom out / increase time range)

@torkelo This is what I wrote earlier. Grafana limitation to to present about 1000 points and so data to be manipulated/transform to fit in 1000 points. If data points can't reduce to 1000 points for given duration and need higher precision, other tools to be selected having such capability.

**Comment by roidelapluie** [comment]
There is a misunderstanding.

Prometheus can render up to 11000 steps. Which is not the raw data.

You can query the raw data, unlimited, by using `gauge[${__interval_s}s]` and instant query. However, this might lead to bad experience, since grafana might get data it did not expect. And your own screen does not have enough space to display it.

**Comment by sksingh20** [comment]
Thank you @roidelapluie for confirming that Prometheus is not putting any restriction/limitation on count of returnable raw data. Obviously there is no reason for doing so at Prometheus level.

This is purely up to Visualization tool on how to manage and show such data. Grafana limitation is of dashboard only approx 1000 points.

**Comment by torkelo** [comment]
@sksingh20 for graphs Grafana defaults max data points to the width of the graph in pixels, max data points are then used to calculate the min interval & step.

you can override and set max data points to whatever you want:

![Screenshot from 2021-06-04 13-06-47](https://user-images.githubusercontent.com/10999/120792507-eae8dc80-c535-11eb-97df-4e3b3ec61ccb.png)

**Comment by sksingh20** [comment]
@torkelo Thank you for giving override option which improved resolution. Now step value is improved and new step value is based on Max 11K records or Interval value, Whichever is Higher.

I tried to see graph of gauge[${__interval_s}s], but Grafana do not show any result on graph whereas Prometheus returning all raw data without limitation.

Do you have some suggestion?
