### ISSUE TITLE
Why Does the Table Plug-in Remove the Paging Function in Version 7.0.0 and Later?

### ISSUE THREAD

**Issue by caoqiang-github** [grafana/grafana#35077]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
We replaced it with virtualized scrolling, 

But hope to add pagination as a new option 
https://github.com/grafana/grafana/issues/26022
