### ISSUE TITLE
Explore: Migrate from `GrafanaTheme` to `GrafanaTheme2`

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#35097]
Multiple Explore-related components still make use of `GrafanaTheme`. 
Since Grafana 8.0 introduces `GrafanaTheme2` and deprecates `GrafanaTheme` we should migrate to the new theme.

This should probably be done in multiple small PRs that target a small amount of components to make review easy.

Also the following data sources have components that need to be migrated:
- [ ] Elasticsearch
- [ ] Loki
- [ ] Graphite
- [ ] Prometheus

**Comment by Betula-L** [comment]
Can i take this up?

**Comment by torkelo** [comment]
I have not updated the theme guide nor created a migration guide (on my todo after v8). In the meantime this is a good guide how we translate the new theme to v1 theme:
https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/themes/createV1Theme.ts
