### ISSUE TITLE
Failed : "Direct link rendered image" (ReverseProxy under /grafana)

### ISSUE THREAD

**Issue by handfreezer** [grafana/grafana#3509]
**Hello**,
I create a lab in a virtualbox, and to simplify access, I put a reverseproxy (nginx) to give access to grafana, influxdb and icingaweb2 on same DNS and port. Grafana access is available under /grafana and I set root_url accordingly. Everything is working well except direct rendered image. I succeded to get a rendered image by breaking the configuration (if I got a rendered image, everything else is dead almost).
Below, you will find two screenshots, and my configuration which fails, and the change needed to get rendering image working (but ONLY image rendering... :-( )

I guess the rendered image is created on the server side, and the root_url is partially used to set PhantomRenderer instead of full use or set to local use.

Any idea? (I'm available for more test or info if needed)

**=> Failed**
**grafana.ini:**
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

**nginx.conf:**
proxy_redirect          off;
proxy_set_header        Host            $http_host;
proxy_set_header        X-Real-IP       $remote_addr;
proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
client_max_body_size    10m;
client_body_buffer_size 128k;
client_header_buffer_size 64k;
proxy_connect_timeout   90;
proxy_send_timeout      90;
proxy_read_timeout      90;
proxy_buffer_size   16k;
proxy_buffers       32   16k;
proxy_busy_buffers_size 64k;
server {
        listen 80;
        server_name _;

        location / {
                return 404;
        }
        location /grafana {
                proxy_pass  http://localhost:3000;
                rewrite  ^/grafana/?(.*)  /$1 break;
        }
}

**Here is the URL used:**
http://localhost:50080/grafana/dashboard/db/s3k

**Direct rendered image:**
http://localhost:50080/grafana/render/dashboard-solo/db/s3k?panelId=3&fullscreen&from=1449832848735&to=1449853991848&var-Hostname=MyServer&var-Interval=10s&width=1000&height=500

**Log of Grafana:**
2015/12/12 18:31:27 [I] PhantomRenderer::renderToPng url http://localhost:3000/grafana/dashboard-solo/db/s3k?panelId=3&fullscreen&from=1449832848735&to=1449853991848&var-Hostname=GC7H1&var-Interval=10s&width=1000&height=500
2015/12/12 18:31:28 [I] Completed /grafana/dashboard-solo/db/s3k 404 Not Found in 1.445947ms
2015/12/12 18:31:28 [I] Completed /grafana/css/grafana.dark.min.2f192efd.css 404 Not Found in 1.714132ms
2015/12/12 18:31:28 [I] Completed /grafana/app/app.b4b243aa.js 404 Not Found in 1.397244ms
2015/12/12 18:31:41 [I] PhantomRenderer::renderToPng url http://localhost:3000/grafana/dashboard-solo/db/s3k?panelId=3&fullscreen&from=1449832848735&to=1449853991848&var-Hostname=GC7H1&var-Interval=10s&width=1000&height=500
2015/12/12 18:31:41 [I] Completed /grafana/dashboard-solo/db/s3k 404 Not Found in 2.041059ms
2015/12/12 18:31:41 [I] Completed /grafana/css/grafana.dark.min.2f192efd.css 404 Not Found in 1.221249ms
2015/12/12 18:31:41 [I] Completed /grafana/app/app.b4b243aa.js 404 Not Found in 2.159047ms

**=> Success **
*Same as above except for:
**grafana.ini:**
root_url = http://localhost:3000/

**=>Failed rendered**
![grafana_render_direct_failed](https://cloud.githubusercontent.com/assets/2912752/11763263/c9c0a2f6-a103-11e5-9b3d-015b47425f0f.png)

**=> Succeed render**
![grafana_render_direct_success](https://cloud.githubusercontent.com/assets/2912752/11763262/c9bd704a-a103-11e5-8e0d-365dcd418e7d.jpg)

**Comment by torkelo** [comment]
your nginx config should not rewrite urls, 

```
location /grafana/ {
    proxy_pass http://localhost:3000/;
}
```

and grafana.ini 
```
root_url = http://localhost:3000/grafana
```

**Comment by handfreezer** [comment]
I'm sorry, but I think it was closed too quick..

*From what I understood about diffrence between in 'proxy_pass http://localhost:3000' and 'proxy_pass http://localhost:3000/' , the second one is an implicit rewriting rule to remove the matching part of location... but nevermind, I applied your request (note my rewriting rule allow someone using http://localhost:50080/grafana to access the server, and this is not the case with the second solution)

*I did the change in grafana.ini

=> nothing better, in fact, it was bad as grafana is answering urls with TCP/3000 in encoded urls whereas it should be 50080. 

**the fact is I found the 'root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana' on internet, it's not mine.

Now I made an other test: on my client side, I added in hosts file the line '127.0.0.1 localgrafana' and tried the same job. I got the same failure with exactly the same log in grafana about phantom instead of giving localgrafana:50080.

 What I guess is that invocation of phantom renderer is done with the local resolution of binding port of grafana server instead of the use of root_url, isn't it?

**Comment by torkelo** [comment]
well the correct way would be to use 

```
location /grafana/ {
    proxy_pass http://localhost:3000/;
}
```

and grafana.ini 
```
root_url = http://localhost:50080/grafana
```
(do not use localhost, use the domain name / ip you use i the browser). This url is used to set session cookies, and the sub url is used to render correct urls and the frontend, also it used to in call to phantomjs to render panels, so the url must be accessable server side.

**Comment by handfreezer** [comment]
OK, I understood what you want me to do, but as I said, you can not rely on only one NS  used to access grafana instance. 

That's why I think it should be possible to reference the Host header field of the http request when generating html/javascript code on client side, and use localhost when needed to render on server side, don't you?
