### ISSUE TITLE
Explore: Refactor typings for redux-connected components

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#35099]
We should refactor the way the props for components are defined so that they can be automatically inferred from `mapStateToProps` s functions.

Example: https://github.com/grafana/grafana/blob/a55a2722764fdae5b7091b432bfc6e0cd1d61f1b/public/app/features/explore/ExplorePaneContainer.tsx#L125

See: https://github.com/grafana/grafana/blob/main/contribute/style-guides/redux.md#typing-of-connected-props

Here's a list of components that need refactoring. Check them off when they've been refactored

**Components**
inside `public/app/features/explore`
- [x] NodeGraphContainer.tsx
- [x] ReturnToDashboardButton.tsx
- [x] TableContainer.tsx

**Comment by olbo98** [comment]
Added the remaining components that needs to be refactored to the issue

**Comment by olbo98** [comment]
@Elfo404 could you take a look and see if there are any more components that need to be refactored?

**Comment by olbo98** [comment]
Closing this issue since all components have bee refactored
