### ISSUE TITLE
Timeseries Panel expects the first dataframe to be "time"

### ISSUE THREAD

**Issue by srclosson** [grafana/grafana#35098]
**What happened**: A query returned by the NewRelic datasource came back with data that looks like this:
![image](https://user-images.githubusercontent.com/7053010/120472452-4a9b8800-c37c-11eb-89ca-b672f0a2fddd.png)

**What you expected to happen**: I expected the graph to render properly, finding the time in the data.Frame with the field type of "Time"

**How to reproduce it (as minimally and precisely as possible)**: The insights query is 
```
SELECT average(loadAverageOneMinute) as '1 minute', average(loadAverageFiveMinute) AS '5 minutes', average(loadAverageFifteenMinute) AS '15 minutes' FROM SystemSample WHERE `entityGuid` = 'MTYzMjc1NXxJTkZSQXxOQXw4OTE5NzAzNTE2MjMwMTQ3Njgy' $__timeFilter TIMESERIES
```

**Anything else we need to know?**: If I perform a transformation, everything works fine 
![image](https://user-images.githubusercontent.com/7053010/120472933-df05ea80-c37c-11eb-961d-f002774bcde6.png)

**Environment**:
- Grafana version: 8.0-beta 2
- Data source type & version: New Relic 2.1.1
- OS Grafana is installed on: Darwin
- User OS & Browser: Opera (latest)
- Grafana plugins: Too many
- Others:

**Comment by ryantxu** [comment]
![image](https://user-images.githubusercontent.com/705951/120717504-8453b800-c47c-11eb-9faf-1423b82eb6c6.png)

added a transformer so time was last:
![image](https://user-images.githubusercontent.com/705951/120717544-95042e00-c47c-11eb-9027-8c022e7fcb14.png)


dooh
