### ISSUE TITLE
Maintain colors and order for metrics

### ISSUE THREAD

**Issue by s4z** [grafana/grafana#351]
I've noticed with grafana dashboards viewing influxdb metrics the graph colours change on nearly every refresh - would it be possible to maintain graph colours across refreshes? I believe this happens as each refresh contains a different set of metrics (mostly the same set however a few may be added, a few may be removed).

**Comment by Shoen** [comment]
i guess that for backends like graphite even if the order is not deterministic one could apply a default behavior on the web frontend to sort by received metrics by key name

**Comment by bobrik** [comment]
Found my comment from almost 2 years ago here :)

Is it a right place to ask for sorted metric names? It is kind of hard to correlate without order:

![image](https://cloud.githubusercontent.com/assets/89186/12673499/0e1f0820-c675-11e5-9c07-ef977e12332d.png)

I think two checkboxes make sense on graph leve:

- [x] sort metrics
- [x] natural sort (appears if the first one is ticked)

**Comment by torkelo** [comment]
Closing this as it seems to have been an influxdb sorting issue,
