### ISSUE TITLE
Shared tooltip X position is incorrect when scrolled.

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#35106]
**What happened**:
Shared tooltip X position is incorrect when scrolled.

**How to reproduce it (as minimally and precisely as possible)**:
Reproducable on https://g80-beta.grafana.net/d/Y29yZf3Mz/joshs-azure-monitor?orgId=1 with the two "GithubTestDataVM" panels after you scroll down a few 100px.

<img width="1648" alt="Screen Shot 2021-05-28 at 2 42 05 pm" src="https://user-images.githubusercontent.com/46142/119995131-309d2680-bfc5-11eb-966d-7f5e529614c6.png">

_Originally posted by @joshhunt in https://github.com/grafana/grafana/issues/34624#issuecomment-850441282_

**Comment by dprokop** [comment]
Fixed with https://github.com/grafana/grafana/pull/34782
