### ISSUE TITLE
[enhancement] allow table panel "query" to be modified on the dashboard page dynamically

### ISSUE THREAD

**Issue by blysik** [grafana/grafana#3511]
I'm thinking about an option to table panel which exposes the query to a editable field on the dashboard page.

This would allow you to tweak the query parameter without having to edit the table panel.

What do you think?

**Comment by torkelo** [comment]
you can use a template variable to do that now. Just use a template variable of type custom. Could be made easier to use though.

**Comment by blysik** [comment]
That would allow pre-set queries via the template variable dropdown.  That's pretty cool, and definitely close to this enhancement idea.  Not quite "on the fly" queries.  

Also having trouble using a template variable in the Query field in the table panel.  Maybe user error.

**Comment by blysik** [comment]
Never mind, was user error.  I got the template variable to work.

**Comment by blysik** [comment]
This usage makes me want to be able to re-locate the template variables "row".  So I could place it near the table panel.

**Comment by daniellee** [comment]
There are now ad hoc filters that allow on the fly queries so closing this.

http://docs.grafana.org/guides/whats-new-in-v4/#ad-hoc-filter-variable
