### ISSUE TITLE
Remove footer from grafana login page

### ISSUE THREAD

**Issue by VinayDanda** [grafana/grafana#35111]
**What would you like to be added**: Need the footer to be removed from the Grafana login page. Footer => links -> Documentation, Support, Community, Open Source, build version.

**Why is this needed**: We don't need to have this enabled on the login page. So would need to disable it completely.
![Grafana-footer](https://user-images.githubusercontent.com/33858700/120495300-325a5600-c3da-11eb-87e9-71552d498538.png)

**Comment by VinayDanda** [comment]
Please help assist how to disable the above footer links from the login page.
Grafana version: 7.3.5

**Comment by zoltanbedi** [comment]
Hi @VinayDanda you can only do that in Grafana Enterprise. See this document how to do that https://grafana.com/docs/grafana/latest/enterprise/white-labeling/
