### ISSUE TITLE
Tooltip is cut off

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#35139]
**What happened**: I hovered my cursor over the Data format options in the Heatmap panel editor and the tooltip went off the side.

![image](https://user-images.githubusercontent.com/52059945/120551450-e47a2980-c3aa-11eb-90ab-8c774a88b954.png)

**What you expected to happen**: It to be readable and not run off the edge of the page.

**How to reproduce it (as minimally and precisely as possible)**: Hover your cursor over the data format options for the Heatmap panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 8 beta3
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser: Windows and Chrome
- Grafana plugins:
- Others:

**Comment by ryantxu** [comment]
This is really an issue with the angular panels -- and we don't have a clear path to fix that :cry: 

The specific issue will be fixed with: https://github.com/grafana/grafana/issues/45495 and angular is now on the deprecation path
