### ISSUE TITLE
Annotations: After adding a new annotation to old graph all annotations are cleared 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#35131]
To reproduce:
* Create new dashboard add an old graph panel
* Save dashboard
* CTRL/MOD click graph and add a new annotation 
* After clicking save on the annotation popover there is no annotation added to the graph but you will see it refresh (new query)
* Click refresh on time picker, see newly annotation appear
* Try create a new annotation event, this time after hitting save the all annotations are cleared again 

Another way to reproduce
* Have a graph that shows annotations
* Go into panel edit
* Change something within the query editor to tigger a new query (like alias for test data datasource). A new panel local refresh event fires (but no dashboard refresh) so no annotation query and all annotations are lost. 

The reason is that only a panel level refresh event is fired so a new annotation query is never issued, so the graph is rendered without annotations. 

I tried switching the results Subject to a ReplaySubject https://github.com/grafana/grafana/blob/main/public/app/features/query/state/DashboardQueryRunner/DashboardQueryRunner.ts#L22  

This had the effect of showing the old annotations (but created lots of other bugs), but it does not show the annotation you just added as **no** new query for annotations is fired. Think we somehow need to fire the dashboard queries for these local refresh events.

**Comment by torkelo** [comment]
@hugohaggmark if you can take a look at this tomorrow that be great.

**Comment by hugohaggmark** [comment]
@torkelo I'm on it!
