### ISSUE TITLE
Logs panel button cut off

### ISSUE THREAD

**Issue by oddlittlebird** [grafana/grafana#35140]
**What happened**: One of the buttons in the Logs panel is cut off on the edge of the screen.
![image](https://user-images.githubusercontent.com/52059945/120551855-5d798100-c3ab-11eb-837d-480c2a76a9af.png)

**What you expected to happen**: It should stack or something.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 8 beta 3
- Data source type & version: 
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, Chrome
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
we will have to decide if we switch it to `select`, or we fix the panel-width.
