### ISSUE TITLE
Refresh interval per panel

### ISSUE THREAD

**Issue by lacion** [grafana/grafana#3514]
it would be useful specially now that there is elastic search and cloud watch backends to be able to set a per graph refresh i would like to have dashboards that will show a general overview some times over a week running pretty hard queries over in elastic search, but also showing some graph from other sources (like graphite or others db's) where i would like near realtime updates.

having real time updates on ES and cloud watch is really heavy on ES resources and cost's on aws but being able to override the refresh rate per graph would be really helpful.

**Comment by gbrian** [comment]
+1
What's the way for helping on this ?

**Comment by utkarshcmu** [comment]
How about per row refresh rate instead of per graph?

**Comment by gbrian** [comment]
First version done:
Now refresh is by panel and you can set the value on each panel, at row level or dashboard level.
Basically what it does, at dashboard refresh, is to assign a refresh rate to each panel. 

Main interval is calculated to be the greatest common divisor and that's all.

Pending last testing and create the pull request.

![image](https://cloud.githubusercontent.com/assets/767180/12228302/96b1f93a-b839-11e5-8214-ab0c4f64b65b.png)
![image](https://cloud.githubusercontent.com/assets/767180/12228309/a6e50da6-b839-11e5-99d7-835f68018065.png)
 
![image](https://cloud.githubusercontent.com/assets/767180/12228255/ed948e12-b838-11e5-8e7d-08f5d3a2a882.png)

**Comment by mtanda** [comment]
This is useful for CloudWatch to reduce cost.

**Comment by gbrian** [comment]
I've had to close pull request as there are many changes on master to keep it updated (test were failing as well). I'll try to implement again over latest version unless @torkelo you already have started this implementation.

**Comment by jsdt** [comment]
+1

**Comment by Codelica** [comment]
I think this would be very useful for mixed content dashboards.  I'd love to be able to mix some realtime-ish charts in with longer term trends.  Any chance this could be revived ?

**Comment by arianitu** [comment]
+1, I really assumed Grafana would support something like this.

**Comment by leafonsword** [comment]
Hope support row level, panel level refreshing!

**Comment by hatzlhoffer** [comment]
+1 this would be very helpful!

**Comment by kccheung** [comment]
+1

**Comment by dooe** [comment]
+1

**Comment by colmobrien84** [comment]
+1 this would greatly add to my Grafana <3

**Comment by scaarup** [comment]
+1

**Comment by camelstrike** [comment]
+1

**Comment by unixfox** [comment]
Is it possible to stop posting the useless `+1` and just upvote the first comment on this issue if you are interested into this feature?

**Comment by arnolde** [comment]
I'm surprised this was implemented 3 years ago but not released yet... Please upvote more :-)

**Comment by arnolde** [comment]
@Edu-GM Please don't write +1, that is no help. Click the thumbs-up on the very first message in this issue, that will effectively upvote this issue.

**Comment by Knot3n** [comment]
Please release this feature .. we need it to have a bit less load on the server.

**Comment by gbrian** [comment]
Hi everyone,
Did new attempt to implement this feature. The PR is just a preview for sharing the approach and grab some comments.
Please if you have the time check it and share your thoughts
https://github.com/grafana/grafana/pull/16384

**Comment by gbrian** [comment]
Ok, done tested and working fine!
hope they'll like the implementation 😅 @daniellee @torkelo 
![grafana_panel_refresh](https://user-images.githubusercontent.com/767180/55616207-9862d880-5791-11e9-8952-14e3298ba195.gif)

![image](https://user-images.githubusercontent.com/767180/55616309-d3650c00-5791-11e9-89e2-7206027d8514.png)

**Comment by gbrian** [comment]
Ok, guess I have it done for the React panels 😓 
![grafana_panel2](https://user-images.githubusercontent.com/767180/55622680-2c886c00-57a1-11e9-9b1d-de66995118fe.gif)

**Comment by MissMusic** [comment]
I need this so much!

**Comment by em0il** [comment]
can someone tell me how I can achieve different refresh intervals (by own coding or where can I find the panel from above)

**Comment by mario-donnarumma** [comment]
I think this feature would be great. Definitely need this.

**Comment by davide-acanfora** [comment]
This would be a great feature for dashboards with multiple datasources :+1:

**Comment by dbu748** [comment]
I would love to have this feature ! :+1:

**Comment by pknad505** [comment]
This would be an amazing feature and its the only reason why I'm hesitant to start using this platform +1

**Comment by szerwi** [comment]
Is there any update about this future? I'd like to see it in Grafana.

**Comment by Zangoran** [comment]
@torkelo Any update?

**Comment by beingyash** [comment]
@torkelo Is this feature request anywhere on the current roadmap?

**Comment by torkelo** [comment]
no

**Comment by dnfm** [comment]
Why would it be?  It's not like a tonne of people haven't wanted it for nearly 5 years now!

... oh wait..

**Comment by beingyash** [comment]
> no

Do you have some defined criteria to consider feature requests, so as to get this one qualified?

**Comment by szerwi** [comment]
@torkelo so maybe at least some protection that if previous refresh is not finished, it won't start another one. I have a few panels which took long to load and when I set refresh rate to 10s it is impossible for them to load, I need to manually change refresh rate to 1 minute so they load properly.

**Comment by gbrian** [comment]
Hi @torkelo ,
First things first, thanks for taking the time to answer commenats in this thread as I can perfectly understand the reason for Grafana- and many other open source projects- to keep focus.
So this is a comment for all people here willing to have this an probably other features in Grafana:

What if there's a fork adding this functionalities and offering the pull request to the main repository? Do you know if something like this exists?

 * New features/bug fixes will be deployed following Grafana's guideline
 * New features will be discussed/agreed with repository owners to ensure its adoption by main repository in the future.
 * All developments will have each own branch
 * There will be a main branch with all developments or option to build your own set
 * Pull requests will be updated with new changes coming from main repository
 * Fork will use platform like https://opencollective.com/ to sustain developments

Comments @torkelo ?, on your time.

**Comment by torkelo** [comment]
We accept pull requests for popular feature request if the implementation is sound and the added complexity is low enough compared to the added value

**Comment by hanahas** [comment]
👍

**Comment by kj187** [comment]
👍

**Comment by Julhh** [comment]
👍
