### ISSUE TITLE
Grafana is showing the ANSI reset code 'ESC[m' in logs view

### ISSUE THREAD

**Issue by cdeharo** [grafana/grafana#35166]
**What happened**: Grafana is showing the ANSI reset code 'ESC[m' in logs view.

**What you expected to happen**: The 'ESC[m' is hidden and interpreted as reset code.

**How to reproduce it (as minimally and precisely as possible)**: View a log like the following in Grafana:
```
[1;30m[2021-05-31 19:12:27.976][m[32m[ INFO][m[35m[10][m[34;1m[][m[32;1m[][m[33;1m[][m[30m[blablabla runner][m[36m[blablabla=>blabla$blabla$1][m[Starting service for blabla... ],815416643a099f0150f01c4c120f139c_A,NaN
```

Note that the `ESC` char is represented with `` in the above log.

![Colored log with ANSI reset code shown](https://user-images.githubusercontent.com/12809819/120632636-78aac600-c469-11eb-8dc2-b92b456eab54.png)

We can see that only the reset coloring codes (`ESC[m`) are those that are not well printed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.3
- Data source type & version: Loki and Promtail 2.2.0
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 10 & Chrome Latest
- Grafana plugins: default plugins
- Others:

**Comment by zuchka** [comment]
related: 
https://github.com/grafana/grafana/issues/29039

which was closed in favor of another related issue, but in the Loki repo:
https://github.com/grafana/loki/issues/2861

**Comment by zoltanbedi** [comment]
@ivanahuckova is this fixed?

**Comment by ifrost** [comment]
This is still broken. It seems that [ansicolor](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/utils/ansicolor.ts) parser doesn't handle reset code properly. It handles `\u001b[0m` but in the example above `0` is omitted and `\u001b[m` is used instead (which is valid reset code). 

`\u001b[0m` seems to be handled fine beacuse after changing reset code in the example from `\u001b[m` to `\u001b[0m` it renders just fine:

<img width="1368" alt="Screenshot 2021-06-18 at 13 48 39" src="https://user-images.githubusercontent.com/745532/122557806-8cdfed00-d03d-11eb-80c9-db0a02d285c1.png">

**Comment by ifrost** [comment]
https://github.com/xpl/ansicolor/pull/15

**Comment by xpl** [comment]
@ifrost I've merged your PR, thank you!
