### ISSUE TITLE
playlist is broken

### ISSUE THREAD

**Issue by Betula-L** [grafana/grafana#35164]
**What happened**:
We can not open or create playlist in recent version.

![图片](https://user-images.githubusercontent.com/6059935/120633863-356a4a80-c49d-11eb-9189-e83b1e74f834.png)

**What you expected to happen**:

Component `Playlists` act as normal.

**How to reproduce it (as minimally and precisely as possible)**:
Just open https://play.grafana.org/playlists

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9d4c71920555f3ee76b1d8ed6f1b1a5d2885af
- User OS & Browser: Edge && Firefox

**Comment by jackw** [comment]
Can reproduce locally when logged in as a viewer. Looks like an issue with how the `Card.Actions` component is cloning children.

**Comment by Betula-L** [comment]
@jackw  Yes, i can reproduce this bug locally rather as a viewer or admin.
