### ISSUE TITLE
Probability Distributions: EDF/CDF, PDF  [feature-request]

### ISSUE THREAD

**Issue by samhatchett** [grafana/grafana#3516]
When viewing large amounts of data for diagnostic purposes, it is often useful to look at derived statistics. These include most notably the [Empirical Distribution Function](https://en.wikipedia.org/wiki/Empirical_distribution_function) and the [Probably Density Function](https://en.wikipedia.org/wiki/Probability_density_function) (similar to Histogram). These plots require a little math to generate, but it is all well-documented and available in various third-party libraries: see https://www.npmjs.com/package/distributions

These plots use the viewing time-range as a parameter separate from the 2 dimensions of the display, but provide valuable information about the character of the timeseries data. This feature request is related to #600 #516 #949

**Comment by torkelo** [comment]
graphite has a bunch of analytics functions, if your time series store is missing a metric transform function when please open a PR for that time series store :) 

Grafana leave's the processing of metric queries and metric transformation functions to the time series backends. Processing metric queries and doing transformation is much better done there.
