### ISSUE TITLE
Azure Monitor Datasource fails to connect in 8.0.0beta3

### ISSUE THREAD

**Issue by sethjones** [grafana/grafana#35177]
**What happened**:
When adding a new, or using an existing, Azure Monitor datasource the test phase AND/OR using the data source results in a "Bad Request" error. 

Error Message: "1. Azure Monitor: Bad Request: Bad Request 2. Azure Log Analytics requires access to Azure Monitor but had the following error: Bad Request: Bad Request "

**What you expected to happen**:
Test and usage is successful and data is queryable.

**How to reproduce it (as minimally and precisely as possible)**:
1. Using version 8.0.0beta1-beta3 attempt to add an Azure Monitor data source with valid credentials.
2. Attempt "Save & test"

**Anything else we need to know?**:
This datasource configuration is confirmed working in the latest stable build (7.5.7) and when using the latest nightly/master build.

**Environment**:
- Grafana version: 8.0.0 beta3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac/Firefox
- Grafana plugins: n/a
- Others:

**Comment by kostrse** [comment]
@sethjones Was it migration of existing deployment of Grafana from  **7.5.7** or fresh deployment of **8.0.0-beta3**?

Did you upgrade existing deployment of Grafana with existing database from **7.5.7** to **8.0.0-beta3** and existing, previously working, datasource just stopped working in **8.0.0-beta3**?

Or did you create a new datasource in a fresh deployment of Grafana 8.0.0-beta3 and same credentials, which you used before in  **7.5.7* stopped working in **8.0.0-beta3**?

Do you host your Grafana in Azure (App Service, VM, AKS etc.) or somewhere else?

**Comment by sethjones** [comment]
I did some more testing today.

I verified working on new instance locally and on my kibe cluster. 

I need to test another server upgrade and migration still.

**Comment by sethjones** [comment]
Just to add some more information, and actually answer your questions...

@kostrse 

We are running in an Openshift Kubernetes Cluster.  I was testing in a newly installed instance of grafana, that was then restored from api backups.  Originally, the Azure data sources were bugged and not working. Myself and another engineer on my team tried adjusting the configs, trying to readd the data sources and kept having the same issue.  We tried this process with beta1,2,3. And the results were the same.  We then updated to master/nightly and they magically worked again.

However, testing today on the same cluster, it worked.  We were rather confused. So i spun up a fresh local instance and tried it there too.  I am going to try the full new instance in the cluster, and restore process again to see if that causes an issue.  If that works as well... I will be at a loss for what was causing our issue for the last few versions.

Thanks,
Seth

**Comment by sethjones** [comment]
So I'm having a heck of a time tracking this down. This morning our preprod cluster exhibited this same behavior again. The saved credentials that were put in on friday, and worked fine, stopped working.  I re-entered the same creds into a new data source and it worked again.  My local test version did not exhibit any incorrect behavior. 

I believe I am going to close this for now. I have no evidence of what is happening, and could be something unrelated. If i experience this issue again, and can track something worth while down I'll reopen an issue.

Thanks,
Seth
