### ISSUE TITLE
Cannot safe preferences with Firefox

### ISSUE THREAD

**Issue by ulrichSchreiner** [grafana/grafana#35186]
Hi,

i'm using 8.0.0beta3

when i try to save a new theme or set the default (home) dashboard i cannot do this with firefox. it always jumps back to the values which were selected before i changed. when i do the same which chrome, the change of preferences work.

in the network panel of the dev tools of FF i see a PUT request to the URL `/api/org/preferences` but in the column where the number of bytes is shown, FF shows the text "NS_BINDING_ABORTED".

![image](https://user-images.githubusercontent.com/1642951/120652456-18734e80-c480-11eb-9c38-0ad9d68510f3.png)

as written before: chrome works without a problem

**Comment by zoltanbedi** [comment]
Should be fixed by https://github.com/grafana/grafana/pull/34836
