### ISSUE TITLE
Save confirmation for dashboards

### ISSUE THREAD

**Issue by abraithwaite** [grafana/grafana#3518]
Maybe this has already been mentioned in another ticket, but I couldn't find it.

It would be _very_ nice to have a save confirmation dialog for dashboards given that the settings button is right next to it.

I ought to get in the habit of copying a dashboard before playing with it, but that's a lot of overhead for what could be solved with a confirmation dialog.

Using grafana 2.5

<img width="502" alt="screen shot 2015-12-14 at 5 38 31 pm" src="https://cloud.githubusercontent.com/assets/3791413/11799506/90a8d222-a289-11e5-828a-7f4e9859e3bc.png">

**Comment by torkelo** [comment]
not sure about this
