### ISSUE TITLE
Alerting: Send a default template with error message when there is templating error in ngalert notification channels

### ISSUE THREAD

**Issue by codesome** [grafana/grafana#35207]
**What would you like to be added**:

When there is some error in expanding a template for notification channels in ngalert, we are simply ignoring it with a log message and the rendering will likely turn into empty string. It would be nice to send some default template in that case with the template rendering error message in it.

**Why is this needed**:

Easier to to fix the template this way. The logging for this error is a debug log, otherwise since it can flood the logs.

**Comment by bobemoe** [comment]
Is this dupe of #43733 ?
