### ISSUE TITLE
Unable to build for linux platform on OSX

### ISSUE THREAD

**Issue by schen59** [grafana/grafana#3520]
I am trying to build grafana backend on mac OSX with the following command:
go run build.go -goos "linux" build

However, I always get the error:
runtime/cgo
ld: unknown option: --build-id=none
clang: error: linker command failed with exit code 1 (use -v to see invocation)
exit status 2
exit status 1

I also try disable CGO_ENABLED, but doesn't work.
I've compiled a linux version of go in my mac.

**Comment by torkelo** [comment]
not sure sqlite3 can be cross compiled

**Comment by schen59** [comment]
Ok. Thanks for the response. I guess I need to build it in linux env then.
