### ISSUE TITLE
[multiselect TAG][influxDB] UI does not refresh when a tag is clicked

### ISSUE THREAD

**Issue by fredericbarrau** [grafana/grafana#3521]
I am trying to use the great multiselect & tagging feature in grafana 2.6.0 with influxDB 0.9.
I have set up a multiselect variable, which works great. Now I want to attach a tag for grouping these variables. I have set up everything like so :

![grafana-template](https://cloud.githubusercontent.com/assets/98490/11806437/70138d88-a313-11e5-8b7a-4498e3c47861.jpg)

Now, Grafana shows the variables & the tag. When I click on a tag, an XHR request is spawned by the UI, and the backend returns the values associated with the tag I've clicked on : 

![xhr1](https://cloud.githubusercontent.com/assets/98490/11806491/c5e96f84-a313-11e5-943f-e7bab989c0f5.jpg)

![xhr2](https://cloud.githubusercontent.com/assets/98490/11806495/cff4ce6a-a313-11e5-8e20-9b7d72f15448.jpg)

So far, so good.
Unfortunately, the UI does not refresh the value list according to the selected tag. The select input does not even select itself when clicked. (It just triggers the XHR request above).

![grafana-click](https://cloud.githubusercontent.com/assets/98490/11806525/03616308-a314-11e5-883f-f741e0eeac40.gif)

It's so close to work it's frustrating :)

**Comment by krise3k** [comment]
+1

**Comment by daniellee** [comment]
This seems to work now in v4.2.0.
