### ISSUE TITLE
AzureMonitor: metrics query editor should reset when datasource changed

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#35222]
**What happened**:

Query editor for Azure Monitor Metrics:

When user switches to another Azure Monitor data source (which has different credentials), the input in the query editor stay the same. Since new data source doesn't have access to the same data, it cannot fetch data for the existing input but shows error message.

![image](https://user-images.githubusercontent.com/1131253/120735110-dc9bb180-c49e-11eb-8110-0c07e5a58bcf.png)

**What you expected to happen**:

Change of datasource should trigger cascade update of input controls:
* If the currently entered subscription isn't fond among subscriptions received from the new datasource, then reset the subscription.
* Reset of subscription should trigger reset of resource group and so on.

In this case, if both datasources have effectively same permissions, then switching between datasources won't change input.
If two datasources have different permissions and point to different subscriptions/resources, then switching between datasources would reset input instead of showing error.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two Azure Monitor datasources A and B with different credentials and access to different subscriptions (datasource A doesn't see subscription B and datasource B doesn't see subscription A).
2. Add new panel, select datasource A
3. Select all input fields
4. Switch to datasource B
5. See error message and unresolved subscription ID

**Anything else we need to know?**:

The bug doesn't block functionality, user can choose proper subscription to fix the issue, just overall user experience..

**Environment**:
- Grafana version: **8.0.0-beta3** and **main**
- Data source type & version: **Azure Monitor**

**Comment by joshhunt** [comment]
Hmmm... this is an interesting one. I'm thinking this issue would want to be looked at at a higher level than just this one particular data source.

Other data sources (prometheus) do not reset their properties when switching between instances, but i understand the user experience concerns here.

**Comment by joshhunt** [comment]
I'm actually not even sure how, inside AzureMonitor, we can even detect this easily. The QueryEditor is being completely unmounted (especially because our QueryEditor is still a react component mounted in an angular controller mounted in react...), so its not a case of react state persisting when it shouldn't...

**Comment by joshhunt** [comment]
Thinking about this - when we get dropdown results back from Azure (e.g., list of subscriptions) we should check to see if the dropdown value is a valid in the options. If it's not, we should clear it out.

Overall though, I think that we should mitigate errors that show in the UI when this happens rather than completely clear all values.

**Comment by kostrse** [comment]
Yes, if current dropdown's value is among the returned results, then keep the value.
If dropdown's value not in the results, then the existing value should be cleared, and it also should trigger chain reaction among dependent dropdowns.

Each dropdown depends on the value of its parent dropdown (e.g. resource name on resource group, resource group on subscription etc.). If parent dropdown changes its value then child dropdown should be reevaluated:
* if parent is empty, then child cannot have any values should should clear too (and trigger reevaluation of own childs)
* if parent is not empty, then child should fetch new data using based on the new value of parent, and if new results do not contain current value, then clear it (and trigger reevaluation of childs)
