### ISSUE TITLE
Feature request: support multiple AWS Accounts

### ISSUE THREAD

**Issue by marco-hoyer** [grafana/grafana#3522]
The existing solution for multiple credentials implies usage of static credentials. For grafana instances running in AWS it would be much nicer to be able to configure a role to assume per datasource. This way  one could grant the instance permission to assume roles in different accounts which are only allowed to read CloudWatch metrics. To use this, there could be a configuration option for the datasource to assume a specific role. This way, a centralized grafana instance could be used to view metrics across accounts without handling static credentials.

**Comment by torkelo** [comment]
not sure you can assign roles like that. but maybe

**Comment by marco-hoyer** [comment]
You will need to do the following:
1. Create IAM role for your EC2 instance like grafana-role
2. Create an IAM role per AWS account allowing read-only access to CloudWatch with a trust relationship policy like
```JSON
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Sid": "",
      "Effect": "Allow",
      "Principal": {
        "AWS": [
          "arn:aws:iam::<grafana-account>:role/grafana-role"
        ]
      },
      "Action": "sts:AssumeRole"
    }
  ]
}
```
3. Create an EC2 instance with InstanceProfile linking the grafana-role created in 1. to the instance
4. On the EC2 instance call STS.assumeRole(<ARN of a role created in 2.>)
5. Use credentials returned in 4. to read CloudWatch metrics from corresponding account

Would be really awesome to have something like this since this is the most secure and easy solution for cross account metric dashboarding.

**Comment by tmonk42** [comment]
+1 on this. STS AssumeRole is exactly what I was thinking when I noodled on this functionality before I saw this issue :)

Work around for us would look like having multiple instances of Grafana (one per AWS account).

**Comment by moritzheiber** [comment]
Relevant part of the documentation: http://docs.aws.amazon.com/sdk-for-go/api/aws/credentials/stscreds/AssumeRoleProvider.html

**Comment by tmonk42** [comment]
@mtanda I think I'm seeing a bug on this. I'm running nightly build grafana-3.1.0-1463649023.x86_64 on Amazon Linux AMI release 2016.03

I've added three CloudWatch Datasources for our three big accounts, and when creating a dashboard to show a certain metric for each account, it looks like requests are occasionally getting the wrong credentials. I'm seeing this on at least two different metrics I've made graphs for thus far. Examples of the same graphs (each is set to a specific cloudwatch datasource) refreshed three times:

![screen shot 2016-05-20 at 11 59 38 am](https://cloud.githubusercontent.com/assets/4541/15438748/7f544f0e-1e82-11e6-82a2-34e05bbd331b.png)
![screen shot 2016-05-20 at 11 59 52 am](https://cloud.githubusercontent.com/assets/4541/15438754/849d6d56-1e82-11e6-9489-fe4f0df71138.png)
![screen shot 2016-05-20 at 12 00 03 pm](https://cloud.githubusercontent.com/assets/4541/15438755/875104ea-1e82-11e6-81f6-ec836450e509.png)

**Comment by mtanda** [comment]
@tmonk42 Sorry, it is bug.
https://github.com/grafana/grafana/pull/5124 might fix. (not test locally, sorry)

**Comment by tmonk42** [comment]
This fixed it. Thank you!

**Comment by mtanda** [comment]
Thanks for testing!

**Comment by mtanda** [comment]
can close this issue.

**Comment by mtanda** [comment]
@bergquist please close this too :-)

**Comment by marco-hoyer** [comment]
Thx a lot for implementing this
