### ISSUE TITLE
Azure Monitor: user-friendly error mesages for query errors in Azure Resource Graph

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#35225]
Currently in Azure Resource Graph tab, in case of a query error (either syntax or other error like non-existing table), raw HTTP response being displayed as error message:

![image](https://user-images.githubusercontent.com/1131253/120748889-5f7d3600-c4b8-11eb-9a80-b7f7cff202d4.png)

The HTTP response is structured JSON and could be parsed to display a more user friendly error message:

```json
{
    "error":
    {
        "code": "BadRequest",
        "message": "Please provide below info when asking for support: timestamp = 2021-06-04T05:09:13.1870573Z, correlationId = f1c5d97f-26db-4bdc-b023-1f0a862004db.",
        "details":
        [
            {
                "code": "InvalidQuery",
                "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
            },
            {
                "code": "ParserFailure",
                "message": "ParserFailure",
                "line": 2,
                "token": "<"
            },
            {
                "code": "ParserFailure",
                "message": "ParserFailure",
                "line": 4,
                "characterPositionInLine": 23,
                "token": "<"
            }
        ]
    }
}
```

**Comment by chandan00761** [comment]
Can I work on this issue?

**Comment by fridgepoet** [comment]
Hi @chandan00761, @yaelleC and I have already started working on it a bit together, sorry about that!

**Comment by chandan00761** [comment]
Oh no problem. If you can link the pull request while closing the issue, I will learn something from it.

**Comment by ulaszek-james** [comment]
^ same

**Comment by yaelleC** [comment]
@kostrse : do you have an example of a more user friendly message for the error in this issue?

We are a bit worried about parsing the json as error messages tend to vary quite a bit (some have line / col numbers, other don't). Without the assurance of an error message structure guaranteed for all query errors it would not be wise to hard code any custom parsing.

The best option we could think of at the moment would be to display some messaging specifying that we got an error back from Azure Resource Graph and then show a prettified version of the json. 
Do you think that would be more user friendly?

**Comment by kostrse** [comment]
@iwysiu I think Azure Monitor uses schema form the [Microsoft REST API Guidelines](https://github.com/microsoft/api-guidelines/blob/vNext/Guidelines.md#7102-error-condition-responses)

If user would be able to see both: a human-readable summary message + full prettified JSON in case if user needs it
That would be the perfect scenario.

The summary message could be obtained by iterating over the hierarchy of `details` and concatenating the `code` and `message`. If they present.

For this example:
```json
{
    "error":
    {
        "code": "BadRequest",
        "message": "Please provide below info when asking for support: timestamp = 2021-06-04T05:09:13.1870573Z, correlationId = f1c5d97f-26db-4bdc-b023-1f0a862004db.",
        "details":
        [
            {
                "code": "InvalidQuery",
                "message": "Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying."
            },
            {
                "code": "ParserFailure",
                "message": "ParserFailure",
                "line": 2,
                "token": "<"
            },
            {
                "code": "ParserFailure",
                "message": "ParserFailure",
                "line": 4,
                "characterPositionInLine": 23,
                "token": "<"
            }
        ]
    }
}
```

The summary message would be:

> BadRequest: Please provide below info when asking for support: timestamp = 2021-06-04T05:09:13.1870573Z, correlationId = f1c5d97f-26db-4bdc-b023-1f0a862004db. InvalidQuery: Query is invalid. Please refer to the documentation for the Azure Resource Graph service and fix the error before retrying. (Details)

**Comment by yaelleC** [comment]
Thanks for the API guidelines @kostrse , that's exactly what I was looking for!
