### ISSUE TITLE
AzureMonitor: unhandled error in JavaScript console when opening query editor

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#35223]
**What happened**:

When adding new or editing existing panel with Azure Monitor datasource, JavaScript console shows unhandled error:

```
react_devtools_backend.js:2560 PanelQueryRunner Error TypeError: Cannot read property 'dimensionFilters' of undefined
    at migrateMetricsDimensionFilters (query_ctrl.ts:547)
    at migrateQuery (datasource.ts:292)
    at Datasource.query (datasource.ts:74)
    at callQueryMethod (runRequest.ts:183)
    at runRequest (runRequest.ts:134)
    at PanelQueryRunner.run (PanelQueryRunner.ts:243)
```

Referenced files:
* [query_ctrl.ts:547](https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/public/app/plugins/datasource/grafana-azure-monitor-datasource/query_ctrl.ts#L547)
* [datasource.ts:292](https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts#L292)
* [datasource.ts:74](https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts#L74)
* [runRequest.ts:183](https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/public/app/features/query/state/runRequest.ts#L183)
* [runRequest.ts:134](https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/public/app/features/query/state/runRequest.ts#L134)
* [PanelQueryRunner.ts:243](https://github.com/grafana/grafana/blob/43d3d9756285caec2621707471f7e08a86f6771e/public/app/features/query/state/PanelQueryRunner.ts#L243)

**What you expected to happen**:

No error in JavaScript console

**How to reproduce it (as minimally and precisely as possible)**:

1. Make Azure Monitor datasource as default
2. Open Developer Tools
3. Create/open dashboard and click Add Panel
4. See error in the JavaScript console

**Anything else we need to know?**:

While it doesn't visibly affect UI but needs to be checked if it has any implications.

**Environment**:
- Grafana version: **8.0.0-beta3** and **main**
- Data source type & version: **Azure Monitor**
- User OS & Browser: **Google Chrome**

**Comment by sarahzinger** [comment]
@kostrse I spent a bit of time trying to recreate this and don't see it anymore, I'm guessing this may have been fixed in another pr, have you seen this recently? Going to close it for now, but if you're still seeing this let me know and we can reopen it.
