### ISSUE TITLE
AzureMonitor: use latest API version for Azure Resource Graph queries

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#35232]
**What would you like to be added**:

Currently, Azure Resource Graph queries use outdated preview version of API: 2018-09-01-preview
To eliminate risk of having it deprecated, we should update ARG queries to latest API version: 2021-03-01 or newer.

[azure-resource-graph-datasource.go](https://github.com/grafana/grafana/blob/1f16fac8d76bb584595d4692f639bbdc275f9347/pkg/tsdb/azuremonitor/azure-resource-graph-datasource.go#L45)

Newer API has different response schema.

**Why is this needed**:

To use recent, non-preview API to eliminate compatibility risks with national clouds.

**Comment by friendyou1** [comment]
Time of the movement starting hits
