### ISSUE TITLE
HTTP Client: Implement `go-conntrack` to track client connections

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#35257]
**What would you like to be added**:

Ideally, we'd like to be able to track client connection based on certain labels. Currently this happens for Enterprise and we need to implement it in the OSS repo as well.

We think of using [go-conntrack](https://github.com/mwitkow/go-conntrack) for this.

Needs to be implemented into https://github.com/grafana/grafana-plugin-sdk-go repo.

**Special notes**:

The implementation is needed both for `v7.5.x` and `v8.0.x` onwards.

**Comment by marefr** [comment]
> Needs to be implemented into https://github.com/grafana/grafana-plugin-sdk-go repo.

Not exactly sure about that. Definitely not for v7.5.x at least. 

For v8.0.x we can add options for [ConfigureClientFunc](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go@v0.103.0/backend/httpclient#ConfigureClientFunc) and [ConfigureTransportFunc](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go@v0.103.0/backend/httpclient#ConfigureTransportFunc) when creating the HTTP client provider as an example:
https://github.com/grafana/grafana/blob/3331506660c527bd998886dcc29f82fdbd0b8354/pkg/infra/httpclient/httpclientprovider/http_client_provider.go#L15
