### ISSUE TITLE
Regex on templating doesn't exclude results v2.6

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3525]
Hi, I just upgraded from 2.5 to Grafana 2.6 and realized that all my DB with templating feature didn't load correctly.

On templating variables, the first allows the user to select the system to view.
In my case, we have a Graphite tree wich it also has the "carbon" directory. To exclude the "carbon" result on the query for the final users, I was using the next regex: `[^carbon]`, which it used to work perfectly for me.

Grafana 2.6 doesn't recognize the regex and show me no results.

Thanks for all

**Comment by torkelo** [comment]
there has been no change in the templating feature, can you describe more your template variable config? Maybe show a screenshot of your template variable options?

**Comment by sbengo** [comment]
Hi, thanks and sorry, I couldn't answer yesterday.
Actually I can't prove you on 2.5 (upgraded to 2.6), but on another platform, we have Grafana v 2.1.0-pre1, so the __following screenshots corresponds to 2.1-pre version__. 

Without using any regex, the full template query is:
![image](https://cloud.githubusercontent.com/assets/13196237/11835515/6d6ba27a-a3d4-11e5-8685-978b75d910cb.png)


 Wich using the next regex: `[^carbon]`, the results excludes the system `carbon`.

![image](https://cloud.githubusercontent.com/assets/13196237/11835481/2baf0f34-a3d4-11e5-8947-f38d8a90c581.png)

On the __2.6__, using the same dashboard, so the same templating query, datasource, etc. with the same regex filter: `[^carbon]`, it returns `None`:

![image](https://cloud.githubusercontent.com/assets/13196237/11835560/d78802e8-a3d4-11e5-8c2e-de7cbc04f301.png)


Thanks for all

**Comment by Kuermel** [comment]
I have the same problem if I have special characters in the regex query. 
For example "-" '$ "" ^ ".

My guess is that this problem is caused by this commit. https://github.com/grafana/grafana/commit/77c510c

**Comment by torkelo** [comment]
Regex feature in templating requires you have a a capture group, otherwise you will not get anything. This has always been the case. `[^carbon]` does not have a capture group so no value will match.

**Comment by toni-moreno** [comment]
Hi @torkelo , I'm working with @sbengo and we have been working with [^carbon] as filter for some months at least since 2.1 version.

Anyway this other regex seems to work well, 

^(?!carbon$).*

thanks to help us to fix this regex mistake.
