### ISSUE TITLE
Time series: Changing tooltip mode has no effect

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#35266]
**What happened**:
Switching the tooltip-mode has no effect immediately. If i save the dashboard and reload the page in the browser, it gets applied correctly.

**What you expected to happen**:
Switching mode automatically applies to the panel

**How to reproduce it (as minimally and precisely as possible)**:
* Go into edit mode in a time series panel (e.g https://g80-beta.grafana.net/d/NiwIClqGz/simple?orgId=1&editPanel=2) 
* Change the tooltip mode
* Hover over the graph
* To see the changes apply: save the dashboard and refresh the page

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta3

**Comment by leeoniya** [comment]
@dprokop is aware (it affects several panel types that use the tooltip plugin). he mentioned this in https://github.com/grafana/grafana/pull/35005#issue-658441008.

i think once you exit edit mode it is applied (no saving or refresh necessary)

i don't think there's another ticket tracking this so let this be it.

**Comment by oscarkilhed** [comment]
Did some additional testing, it seems like the first time you change the mode it's reflected. Any subsequent change is not reflected. Will look into what's going on.
