### ISSUE TITLE
Self-updating Template Variables

### ISSUE THREAD

**Issue by pcable3d** [grafana/grafana#3526]
For now templated variables are constant unless the user updates/renews the template manually.

Self-updating template variables which pull in new nodes or tags on a user-defined frequency would be very useful for dynamic networks where nodes come and go on the fly.

what are your thoughts on this?

M

**Comment by torkelo** [comment]
if you check the refresh checkbox they will update on dashboard load.

**Comment by pcable3d** [comment]
Well... yes.

Thanks for the quick eye-opener
