### ISSUE TITLE
[tempo datasource] Add ability to filter by trace/span ids

### ISSUE THREAD

**Issue by sergeyshaykhullin** [grafana/grafana#35268]
**What would you like to be added**:

The initial discussion is here: https://github.com/grafana/tempo/issues/735

Add to tempo datasource `tracesToLogs` ability to filter by span or trace ids, not only by time range

Now: `{ app="my-app" }`
Desired: `{ app="my-app" } |~ "span id"` or `{ app="my-app" } |~ "trace id"`

**Why is this needed**:

It is useful to filter exact logs

**Comment by akaimirror** [comment]
This feature is crucial for us to adopt Tempo + Loki.

Our application consists of many services and can send sub-requests to third-party systems. These sub-requests may take minutes to complete. As processing is asynchronous, our services switch to requests while waiting for replies.

So, as request processing can take a long time to complete, and is heavily interleaved with other requests, we have a problem of finding relevant lines in log files.

Current idea is to add span IDs to logs and use Tempo + Loki in Grafana to read them, but this won't work without the feature requested here.
