### ISSUE TITLE
Timerange: Date range picker does not handle timezone correctly

### ISSUE THREAD

**Issue by MichaelKim0407** [grafana/grafana#35290]
**What happened**:
My browser timezone is PST (-7) and my dashboard timezone is set to UTC. When I select a date range with the calendar picker, the start date flips back for one day.

Here I clicked on 2 -> 3, and the display on the right displays my selected range correctly, but the calendar itself jumps to 1 -> 3.
![Screenshot from 2021-06-04 12-05-53](https://user-images.githubusercontent.com/2630527/120851292-77db6800-c52d-11eb-97f8-3208556fc4f9.png)

The (same?) bug was reported and closed at https://github.com/grafana/grafana/issues/19091. Because react-calendar component does not handle timezones (https://github.com/wojtekmaj/react-calendar/issues/135), a timezone-aware wrapper was added to grafana in this PR https://github.com/grafana/grafana/pull/23586. I haven't done enough digging to see if the PR didn't correctly address the issue, or a later commit broke it.

As I'm using Grafana 7.5.4, I checked out the source code and added a few `console.log` lines in [TimePickerCalendar.tsx](https://github.com/grafana/grafana/blob/v7.5.4/packages/grafana-ui/src/components/TimePicker/TimeRangePicker/TimePickerCalendar.tsx).

```typescript
function useOnCalendarChange(onChange: (from: DateTime, to: DateTime) => void, timeZone?: TimeZone) {
  return useCallback(
    (value: Date | Date[]) => {
      if (!Array.isArray(value)) {
        return console.error('onCalendarChange: should be run in selectRange={true}');
      }

      const from = dateTimeParse(dateInfo(value[0]), { timeZone });
      const to = dateTimeParse(dateInfo(value[1]), { timeZone });

      onChange(from, to);
      console.log(value, timeZone, from, to); // <-----
    },
    [onChange, timeZone]
  );
}
```

When I click on a range on the calendar, the `onChange` method for the `Calendar` component is called, and `value` passed in says `Wed Jun 02 2021 00:00:00 GMT-0700 (Pacific Daylight Time)` and `Thu Jun 03 2021 23:59:59 GMT-0700 (Pacific Daylight Time)` (since react-calendar does not support timezones and always assumes browser time, I guess?). The `timeZone` variable is `"utc"`. The return values of `dateTimeParse`, `from` and `to`, change to `06-02 00:00:00 UTC` and `06-03 23:59:59 UTC` and fed to the parent component's callback. This is what I expect.

The problem, however, seems to happen when the calendar is rendered again.

```typescript
const Body = memo<Props>(({ onChange, from, to, timeZone }) => {
  const value = inputToValue(from, to);
  const theme = useTheme();
  const onCalendarChange = useOnCalendarChange(onChange, timeZone);
  const styles = getBodyStyles(theme);
  console.log(from, to, timeZone, value); // <-----
```

Here, `from` and `to` are the same as they were sent to the parent, i.e. `06-02 00:00:00 UTC` and `06-03 23:59:59 UTC`. `timeZone` is still `"utc"`. The problem is that `inputToValue` returns `Tue Jun 01 2021 17:00:00 GMT-0700 (Pacific Daylight Time)` and `Thu Jun 03 2021 16:59:59 GMT-0700 (Pacific Daylight Time)`, which are then sent to the `Calendar` component. The calendar would then render Jun 1 -> 3.

**What you expected to happen**:
The date range picker should use the dashboard timezone and ignore the browser timezone. When I set the dashboard timezone to UTC, I expect the picker to both pick UTC time, and display UTC time.

I also read from the PR mentioned above,

> There are multiple reasons why this is a handy feature but the following scenario explains the need pretty well. If you are monitoring a platform that operates in multiple time zones it would make everything easier to display the date/time values in the local timezone instead of your local or UTC.

I have to admit I don't fully understand the scenario described here, which may provide some justification for respecting browser time?? But in any case, what the date range picker definitely should **NOT** do, is picking UTC time and then displaying browser time in the same widget.

**Environment**:
- Grafana version: 7.5.4
- Data source type & version:
- OS Grafana is installed on: Docker
- User OS & Browser: Ubuntu Linux/ Chrome
- Grafana plugins:
- Others:

**Comment by MichaelKim0407** [comment]
Hi @mckn , sorry for pinging you for your work from more than a year ago. Can you please take a look and provide some insights? Thanks!

**Comment by mckn** [comment]
> Hi @mckn , sorry for pinging you for your work from more than a year ago. Can you please take a look and provide some insights? Thanks!

No worries, I will have a look at this later this week 🙏🏻

**Comment by zuchka** [comment]
I can confirm this UI behavior on play.grafana.com using several different UTS settings:

https://cln.sh/XsGo9W

![CleanShot 2021-06-07 at 09 02 41](https://user-images.githubusercontent.com/37156449/121074303-62558080-c76f-11eb-8e62-6541c04eef53.gif)
