### ISSUE TITLE
Saving panels does not save table view toggle

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#35296]
**What happened**:
After saving panel in Table view, click on Apply, the panel is still in Time series mode.
![Screenshot 2021-06-03 164650](https://user-images.githubusercontent.com/63325084/120875126-0caa8980-c55f-11eb-855c-d38afe7d8fbf.png)
![Screenshot 2021-06-03 164704](https://user-images.githubusercontent.com/63325084/120875127-103e1080-c55f-11eb-970c-a9fb0f844341.png)

**Comment by torkelo** [comment]
This is by design, table view is just a quick toggle to view data in table form.

If you want to switch to table visualization use the visualization picker and select table

**Comment by torkelo** [comment]
> If the user use to toggle to see the table and saves it, and the dashboard still shows the panel with "no time field", is that confusing to the user?

Not necessarily, it would be very confusing if this was persisted as it's separate from the visualization selection

**Comment by torkelo** [comment]
Try new v8 alerting (behind feature toggle)

**Comment by kale1d0code** [comment]
I am having this issue with a table
when picking the Table Visualisation and formatting as table,
the table view toggle switches off when exiting edit view and disables the custom sort functionality
