### ISSUE TITLE
ARG queries should default to Table view

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#35295]
**What happened**:

ARG queries only has `table` format. But the table view toggle is always default to false, which can cause confusion for some users when they first see the query result.
![Screenshot 2021-06-04 175937](https://user-images.githubusercontent.com/63325084/120875091-e258cc00-c55e-11eb-86e8-bd87b49dadb7.png)
![Screenshot 2021-06-04 175948](https://user-images.githubusercontent.com/63325084/120875092-e389f900-c55e-11eb-8a80-46674bb3a06d.png)

**Comment by torkelo** [comment]
ARG ?

**Comment by torkelo** [comment]
Switch to table visualization if you want to show data as table, the table view toggle is just for temporary quick table view without having to switch visualization back and forth

**Comment by torkelo** [comment]
Created issue for improving the UX here so the default visualization can suggest that you change to another type: https://github.com/grafana/grafana/issues/35325

**Comment by shuotli** [comment]
> ARG ?

Azure Resource Graph

**Comment by shuotli** [comment]
> Switch to table visualization if you want to show data as table, the table view toggle is just for temporary quick table view without having to switch visualization back and forth

It's not a good experience. We used to have a "switch to table view" reminder button. Can we bring it back?

**Comment by torkelo** [comment]
yes
