### ISSUE TITLE
Hi, any one knows if/how i can read file from grafana datasource plugin ?

### ISSUE THREAD

**Issue by akruman** [grafana/grafana#3530]

**Comment by torkelo** [comment]
???

**Comment by torkelo** [comment]
have no idea about what your asking :) please explain :)

**Comment by akruman** [comment]
I mean here : C:\Users\kruman\Desktop\grafana-2.5.0\public\app\plugins\datasource  
there are data source plugins. 

i want to be able to require('fs') from the file datasource.js
and then in XYDatasource.prototype.query = function(options) {
i want to be able to read file directly.

**Comment by akruman** [comment]
ok i get it, the code runs in browser
