### ISSUE TITLE
Alerting (Beta3): Failed to evaluate queries and expressions

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#35305]
While testing a newly created alert rule I receive an warning when changing a classic condition from `IS ABOVE` to `IS BELOW` and clicking on `Run Queries`.

https://user-images.githubusercontent.com/562238/120976021-38ea2400-c772-11eb-9ddb-71d8a8190c94.mp4

Alertrule found here: https://g80-beta.grafana.net/alerting/-cSStY6Gk/edit?returnTo=%2Falerting%2Flist

**Comment by kylebrandt** [comment]
I think this is frontend, as the value is missing when I bring up inspect:

![image](https://user-images.githubusercontent.com/1692624/121202029-f93f3d00-c842-11eb-887e-3389a166d8bd.png)

If you change the number using up/down from 10 to say 11, it works.
