### ISSUE TITLE
Feature Request: Create custom Macros for MySQL datasource

### ISSUE THREAD

**Issue by zhangjiang-china** [grafana/grafana#35304]
Hi Grafana developer,

I am using the macros of MYSQL in grafana, it is a good feature to simplify syntax of SQL, but its logic can not meet our requirement. I wonder is there any way to create custom macros for MySQL by myself.

For example:
1.We want the $__timeGroup( ) supports QUARTER.

2.We hope the $__timeGroup( ) group the time by a whole natural week,month,quarter,year.

If so, the time of X axis will display the end of the natrual week,month,quarter,year.
The last data point will display the current date.

We write complex SQL to implement this kind of requirement, include grouping by time and filling missing value.

Below is the panel we created which group the time by Quarter:
![image](https://user-images.githubusercontent.com/54022777/120970189-b68d4000-c730-11eb-8458-3167cacccfe0.png)
![image](https://user-images.githubusercontent.com/54022777/120970205-bbea8a80-c730-11eb-8141-9d2e71044bbd.png)

Now we want to simplify the SQL.I am not sure if any other needs this kind of requirement, and maybe we will have more and more customization demand，so I wonder if there is any way for us to create macros or library for Grafana by ourselves. :grinning:

**Comment by marefr** [comment]
Somewhat related to #11431

**Comment by phemmer** [comment]
Not sure if it should be a separate issue, but custom macro functionality for postgres would also be appreciated.
It's very common to want to get the rate/derivative of a value, which in postgres looks something like:

    ((mycol - lag(mycol, 1) OVER w)::double precision / extract(epoch FROM (time - lag(time, 1) OVER w)) AS "rate"

As you can see, this is a very lengthy statement, and is easy to typo. Thus it would highly benefit from a macro. There are other similar macros as well, and so it would be nice to be able to define them.
