### ISSUE TITLE
The first label on alert is not saved

### ISSUE THREAD

**Issue by hota911** [grafana/grafana#35303]
**What happened**:

1. Add labels to an alert
2. Click "Save" button

**What you expected to happen**:

All labels are saved.

**How to reproduce it (as minimally and precisely as possible)**:

The first label is not saved.

**Anything else we need to know?**:

The REST body does not contain the first label.

![スクリーンショット 2021-06-07 15 17 25](https://user-images.githubusercontent.com/38419042/120968602-09540f80-c7a4-11eb-954d-1b57a68240c5.png)

**Environment**:
- Grafana version: Grafana v7.3.5 (11f305f88a)
- Data source type & version: Prometheus, CloudWatch
- OS Grafana is installed on: LInudx
- User OS & Browser: MacOS Chrome 91
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
Can you try to upgrade to 7.5? v8 is releasing tomorrow with a new alerting engine & UI so this old alerting system that is part of the dashboard panel is deprecated and wont see much updates/bugfixes unless critical

**Comment by skirino** [comment]
(I'm a coworker of @hota911 )
We've tried 7.5.8 and 8.0.3 and confirmed that this bug is still present in both versions.
@torkelo Could you reopen this issue?
