### ISSUE TITLE
Grafana data source issue

### ISSUE THREAD

**Issue by FloraJeeva** [grafana/grafana#35319]
Hi ,
   
       I can't able to add data source. Every time while adding it shows Failed to add data source error message.

Grafana Version : 5.3.
Workaround tried: org_datasource = 100

Can you please help us to add

**Comment by torkelo** [comment]
Please describe your issue more, what data source, show what fields you have filled in, any errors in server logs? any error in chrome browser log? 

Try upgrading to latest stable.  version 5.3 is 3 years old
