### ISSUE TITLE
Home button for Home dashboard

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3532]
Can we have the home button back to go to the Home dashboard?

**Comment by utkarshcmu** [comment]
Closing. Do not need it anymore. First link in the dropdown is Home.

**Comment by tangyouze** [comment]
In my idea, upper left space is quite empty, and home button is clicked quite often in my common usage scenario. When I want to change to another board, I always click the "home bookmark" on the most left of my bookmark bar, and click another board.

**Comment by bergquist** [comment]
@tangyouze I suggest you use the new keyboard shortcuts http://docs.grafana.org/reference/keyboard_shortcuts/
