### ISSUE TITLE
Feature Request: Configurable DeviceScaleFactor, Width, Height option for alerting service

### ISSUE THREAD

**Issue by wei840222** [grafana/grafana#35320]
**What would you like to be added**:
For these two files
https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifier.go#L200
https://github.com/grafana/grafana/blob/main/pkg/services/rendering/rendering.go#L185

It seems the deviceScaleFactor, width, height in query string of request sending to image render always be "1".
Is any config like GF_IMAGE_RENDER_DEVICE_SCALE_FACTOR to change this behavior?

**Why is this needed**:
The image from render set larger deviceScaleFactor will more readable.

**Comment by wei840222** [comment]
I tested, width and height also needs to be configurable. here is example
origin image 
![image](https://user-images.githubusercontent.com/17737823/121115640-f430bc80-c847-11eb-8c4d-df750eb71711.png)
width 300 height 400
![image](https://user-images.githubusercontent.com/17737823/121115684-00b51500-c848-11eb-82cd-d95b66e185c1.png)

**Comment by zuchka** [comment]
Hi @wei840222,

Thanks so much for starting to investigate this enhancement. Do you think you'd like to make a Pull Request?
