### ISSUE TITLE
Save Dialog Not Prompting (v8.0.0-beta3)

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#35329]
**What happened**: If you add a panel and exit the dashboard without manually saving, you are not prompted if you wish to save the changes.  you can either modify the panel with a query or not, the results are the same

**What you expected to happen**: There should be a prompt to save the dashboard since changes were made

**How to reproduce it (as minimally and precisely as possible)**: Add a panel, select another menu option on the left bar to exit that dashboard

**Anything else we need to know?**: The prompt works if you add a row and attempt to exit the dashboard

**Environment**:
- Grafana version: Grafana v8.0.0-beta3
- Data source type & version: influxdb
- OS Grafana is installed on: Linux raspberrypi 5.10.17-v7l+
- User OS & Browser: Brave, Chrome
- Grafana plugins: tested with time series
- Others:

**Comment by torkelo** [comment]
fixed by #34989  (fixed after beta3)

**Comment by underdog** [comment]
could it be possible to tag the beta3 actions in the each issue associated?  I searched for this issue, but it seems it was buried inside that fix issue. I feel like I'm wasting your time by adding issues and having them closed out because they are duplicates.
