### ISSUE TITLE
PanelEdit: Suggest panel type change or transform if data is not suitable for current visualization 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#35325]
Currently the default time series panel shows a text "Data does not have a time field".  

I think we should add a way for visualization plugins to notify Grafana that data cannot be visualized and suggest other visualizations (Similar too switch to table button we have in old Graph) but more generic and something other panel types can hook into. Would also be nice if panels could suggest a transform or option?

**Comment by joshhunt** [comment]
Supposedly DataFrames can already specify `PreferredVisualization`, which Explore uses (but not dashboard panels)?  https://github.com/grafana/grafana-plugin-sdk-go/blob/v0.103.0/data/frame_meta.go#L32-L33

Still, I think it would be handy if Grafana would automatically default non-timeseries frames to the table visualisation, or provide some kind of suggestion without requiring data sources to add new things.

**Comment by torkelo** [comment]
yea, this would not require data source to add anything, only time series panel to add something, so panel edit can suggest switching to table
