### ISSUE TITLE
Can't change GROUP BY condition in UI - v2.6.0

### ISSUE THREAD

**Issue by deric** [grafana/grafana#3533]
After upgrade to v2.6.0 (in fact first I've tried beta1, then the final release) all group by conditions on all dashboards are broken `fill(null)`. I can remove this GROUP BY condition but Grafana is refusing to change it to any meaningful value. In manual editor it works fine. 

Same issue happens on Graphite and InfluxDB v0.9 backends. There are no errors in console.

**Comment by torkelo** [comment]
can you show a screenshot of the query editor, and the panel json?

**Comment by deric** [comment]
Sure. 
![grafana-editor](https://cloud.githubusercontent.com/assets/138573/11838228/e24b7a28-a3e5-11e5-84cd-ded9bf930e8d.png)
![grafana-manual](https://cloud.githubusercontent.com/assets/138573/11838235/e81d1a24-a3e5-11e5-9cd4-dec645d6a336.png)

A workaround that sometimes helps:

1. Switch to manual editor
2. Delete `fill(null)`
3. Duplicate query
4. Delete original query
5. Switch editor for duplicated query
6. Change group by condition

Although, it's quite annoying.

**Comment by torkelo** [comment]
not sure what the issue was here, no one else has reported anything similar so will close this.
