### ISSUE TITLE
State timeline strings does not change on zoom

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#35344]
**What happened**:
I played with grafana v8-beta3 on play.grafana.org and tried to zoom on State timeline strings dashboard. It zoomed the time, but the table didn't change

**What you expected to happen**:
I am not sure if it works as intended, but I would expect that the values are represented for a time period

**How to reproduce it (as minimally and precisely as possible)**:
1. Open https://play.grafana.org/d/YI95GyqMz/1-new-features-in-v8-0?orgId=1&from=now-24h&to=now
It looks something like this:

![image](https://user-images.githubusercontent.com/8693064/121056606-6a450d00-c7cf-11eb-95a2-6cf891608ae0.png)

2. Change from last 24h to last 6h
3. Observe that "State timeline strings" has not changed the state/boxes based on the time, however "State timeline with time series + thresholds" has changed

![image](https://user-images.githubusercontent.com/8693064/121056706-88ab0880-c7cf-11eb-920f-edfeae14f45e.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.0-beta3
- User OS & Browser: macOS 11.4 (20F71) / Chrome Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by leeoniya** [comment]
this demo uses our fake datasource with hardcoded strings (see in panel edit), if you connect it to a real datasource it will work fine.
