### ISSUE TITLE
Inconsistent annotation query display

### ISSUE THREAD

**Issue by srclosson** [grafana/grafana#35346]
**What happened**: I have two dashboards. The two dashboards are using two datasources:
1. Oracle
2. TestDataDB

Each dashboard has two annotation queries configured. One for Oracle, the other for TestDataDB 

**What you expected to happen**:

I'm expecting that both dashboards on refresh will display the annotations requested.

**How to reproduce it (as minimally and precisely as possible)**:

https://g80-beta.grafana.net/d/-j3BJD6Mk/test?orgId=1
https://g80-beta.grafana.net/d/NicHC2KGz/oracle-annotations?orgId=1

The "test" dashboard works fine. The only difference I know is that I started annotations with the TestDataDB Query.
The "oracle-annotations" dashboard does not work. If you disable the annotations and re-enable them, the annotations show up, but if they are enabled, and you refresh the dashboard, they do not. 

**Anything else we need to know?**:

Nope

**Environment**:
- Grafana version: 8.0.0-beta3
- Data source type & version: Oracle plugin (whatever is installed)
- OS Grafana is installed on: Probably a container with Linux?
- User OS & Browser: Opera (latest)
- Grafana plugins: grafana-oracle-datasource.
- Others:

**Comment by zuchka** [comment]
can also confirm this behavior on v8-beta3.

Playing with these dashboards, it looks like the variables impact behavior, too. Removing them corrects the issue:

https://g80-beta.grafana.net/d/Toh1iseMk/oracle-annotations-copy-test?orgId=1

**Comment by hugohaggmark** [comment]
@srclosson can you still repro this in 8.0.4?

**Comment by isaacag** [comment]
Looks like is the same issue as #35896, and yes still reproducible on 8.0.6.
