### ISSUE TITLE
2.6.0 Angular JS Error

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3534]
I am seeing this error in v2.6.0 

When you load "settings" URL for any dashboard:
**http://localhost:3000/dashboard/db/new-2?editview=settings**

You will see the following error in Developer Tools Console in any browser:
```Error: JSON.parse: expected double-quoted property name at line 3 column 1 of the JSON data```

**Comment by bergquist** [comment]
I cannot reproduce it.

**Comment by utkarshcmu** [comment]
Looks like my setup had some error. Even I am not able to reproduce it now. 😞
