### ISSUE TITLE
Time series: Annotations are all grey

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#35347]
http://localhost:3000/d/TkZXxlNG3/panel-tests-graph-ng?orgId=1

![image](https://user-images.githubusercontent.com/43234/121070994-0140a380-c795-11eb-92a5-dfc6137ab30b.png)

![image](https://user-images.githubusercontent.com/43234/121071105-27feda00-c795-11eb-9849-81f440696eb2.png)

**Comment by torkelo** [comment]
those are a special form of annotations returned directly by the data source, they have no color on them: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/testdata/datasource.ts#L109 

Annotations returned by dashboard annotation queries have the correct color
