### ISSUE TITLE
Bar Charts mysql count() requests

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana#35357]
Hi all !

I just setup the 8 version of Grafana, and want to test the Bar Charts visualisation.
I have some mysql request with count() wich works on Bar Gauge visualisation, but this visualisation is quite ugly (in my opinion ^^)

But when I try to use Bar Charts I have this msg: Bar charts requires a string field.
I suppose xthat is because of the count() in the request: 

```
Select count(*) as "Column 1" from table 
Where ....
```
Is there a way to use Bar Charts with count() ?

Thx !

**Comment by dprokop** [comment]
@eglyn thanks for the quick feedback. As of the information displayed to you within the Bar Chart viz, your result needs to have a string field. Think about it as a category that you want to group the bars with on your bar chart. I think using GROUP BY in your query should help you get the visualization you want.
