### ISSUE TITLE
Bar Gauge panel wrong gauge names

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#35360]
add a bar gauge panel in a dashboard, use the `gdev-testdata` data source, choose `CSV content`, add this data:
```
name,value
"A",42
"B",55
"C",55
```

set the bar gauge panel to `show=all_values` and `fields=numeric_fields`.

you will see three gauges, names "A", "C", "C". they should be named "A", "B", "C". the second gauge has the wrong name.
this only happens when the values of the gauges are the same.

it seems to be a cache issues, for both "B" and "C" the same cache-value is used and this causes the problem.
if you go to https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/field/fieldOverrides.ts#L218 and change that line to `let v =undefined;` then it will work correctly. (of course this is not the right fix 😄 )

**Comment by torkelo** [comment]
@gabor Good catch! we added the display processor cache a few weeks ago, 

Fix PR https://github.com/grafana/grafana/pull/35368
