### ISSUE TITLE
MissingRegion error for Cloudwatch alerts since upgrade to 8.0.0

### ISSUE THREAD

**Issue by guillaumesmo** [grafana/grafana#35369]
**What happened**:
I have upgraded Grafana to 8.0.0
Although the dashboards work as expected (including data coming from Cloudwatch) the alerts fired immediately with the following error:

```
Execution Error: request handler response error {MissingRegion: could not find region configuration A <nil> [] [] 0xc000b620f0}
```

**What you expected to happen**:
No errors from alerts

**How to reproduce it (as minimally and precisely as possible)**:
Create a Cloudwatch data source in v7 with a default region selected, create an alert but use the "default" region. Upgrade to v8, the alert fails.

**Anything else we need to know?**:
In the panel config, when changing the "default" region to a specific version, the alert works again, so it must be something with the default region from the data source config not taken into account.

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Docker (grafana/grafana image)
- User OS & Browser: N/A
- Grafana plugins: Core only
- Others: -

**Comment by zoltanbedi** [comment]
@sunker, @wbrowne can https://github.com/grafana/grafana/pull/31149 caused this issue?

**Comment by andresmgot** [comment]
I am able to reproduce the issue. Getting the error:

```
ERROR[06-09|13:14:10] Alert Rule Result Error                  logger=alerting.evalContext ruleId=7 name="Panel Title alert" error="request handler response error {MissingRegion: could not find region configuration  A <nil> [] [] 0xc001bd5200}" changing state to=alerting
```

I will keep investigating this and update this thread. Thanks for reporting!

**Comment by sunker** [comment]
Looks like there's a typo [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/cloudwatch.go#L105). I guess that's the problem?

**Comment by sunker** [comment]
> Looks like there's a typo [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/cloudwatch.go#L105). I guess that's the problem?

Saw your PR now. Nice!
