### ISSUE TITLE
Unique Count on string fields in ElasticSearch

### ISSUE THREAD

**Issue by patjlm** [grafana/grafana#3536]
It seems the ElasticSearch query editor only allows to 'unique count' on number fields.

I'd like for example to unique count user names, sessionid, url, ...

**Comment by xiaoping378** [comment]
i met the same question.

**Comment by Elufimov** [comment]
+1

**Comment by evil2bart** [comment]
+1 need this function too

**Comment by vveloso** [comment]
+1

**Comment by nitram4** [comment]
it is about the precission ? could it be added through JSON panel editor?

**Comment by nitram4** [comment]
+1 not possible through JSON panel :-(

**Comment by tonyC2016** [comment]
@evil2bart @patjlm  does grafana2.6 unique cout support for string now ,or do you have other way to get the distinct value ,maybe lucene query?if you do ,plz tell me  thanks

**Comment by tonyC2016** [comment]
i just use grafana 2.6 for unique count  a String ID,and get a wrong result back ,how i can get a dictinct result back  wish anyone tell me a way to fix it

**Comment by hitthefrei** [comment]
+1

**Comment by ankushtehale** [comment]
+1

**Comment by royir** [comment]
+1

**Comment by CodingPythonMan** [comment]
+1
