### ISSUE TITLE
CloudWatch: issue #28301 is back after updating to grafana 8.0.0

### ISSUE THREAD

**Issue by salavessa** [grafana/grafana#35388]
Issue #28301 is back after updating to grafana 8.0.0

**Comment by andresmgot** [comment]
hi @salavessa, I am able to reproduce the bug. It seems there is something weird with the visualization:

![Peek 2021-06-08 18-40](https://user-images.githubusercontent.com/4025665/121224762-2ca4ba80-c889-11eb-842c-577bc9d282df.gif)

I had to refresh the table several times until both time series are properly displayed. Not sure what can be the source yet.

**Comment by sunker** [comment]
The problem appears to be similar to #28301, but I think this is a consequence of [this](https://github.com/grafana/grafana/pull/31149) migration to SDK contracts. I'll see if a can come up with a fix asap.
