### ISSUE TITLE
DashboardQueryRunner: Rxjs errors when leaving or opening dashboard

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#35386]
Seeing this error: 
* When opening http://localhost:3000/d/iRY1K9VZk2/lazy-loading?orgId=1 
* Sometimes when leaving it as well (going to data sources), then go back. 

![Screenshot from 2021-06-08 16-55-50](https://user-images.githubusercontent.com/10999/121208880-b13c0c80-c87a-11eb-922b-0db70280bea9.png)

**Comment by torkelo** [comment]
@hugohaggmark any ideas what this could be? have not figured this out.

**Comment by hugohaggmark** [comment]
@torkelo I'll have a look and see what I can find
