### ISSUE TITLE
Annotations are missing field 'index' in grafana 2.6

### ISSUE THREAD

**Issue by ojware** [grafana/grafana#3539]
If you're creating a new dashboard or saving an old one (pre 2.6) under new name, the annotations datastructure is missing the 'index' field. It's not in the exported JSON, nor is it being displayed in the settings any more. Adding it manually to the JSON and importing it, thus makes it available and usable again, also in the UI.

**Comment by torkelo** [comment]
this is by design to support old dashboards, new dashboards should use the index defined on the Elasticsearch data source (where you can use index time pattern names)

**Comment by ojware** [comment]
thx for the immediate clarification, i'm gonna read the release notes now ;)

**Comment by waqark3389** [comment]
@torkelo That makes sense but does this mean we have to have a data source for every index in elasticsearch?

**Comment by torkelo** [comment]
yes, for every index pattern
