### ISSUE TITLE
Grafana 8.0 incorrectly adding prefix label to grouped data

### ISSUE THREAD

**Issue by risoms** [grafana/grafana#35390]
**What happened**:
Updated to Grafana 8.0. I'm noticing all of my plots are adding as a prefix the variable name used. If a function is used (i.e. `COUNT()`, the function would be prefixed

**What you expected to happen**:
- Plot legend to display as expected

**How to reproduce it (as minimally and precisely as possible)**:
- Upgrade to Grafana 8.0
- Create a timeseries or  plot using psql

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.0 (41f0542c1e)
- Data source type & version: PSQL 10
- OS Grafana is installed on: Linux
- User OS & Browser: OSX, Chrome
- Grafana plugins: None
- Others:
![image](https://user-images.githubusercontent.com/10383917/121221547-4b845c00-c84b-11eb-8ada-16974923d22e.png)

**Comment by torkelo** [comment]
Are you using the built in Postgres data source? can you show you query?

**Comment by torkelo** [comment]
I can replicate this. thanks for reporting this!

**Comment by risoms** [comment]
@torkelo Just in case it's still needed. Here is an example query
```sql
SELECT
    $__timeGroupAlias(time, 30m, NULL),
    name AS metric,
    count(iv) AS value
FROM source
GROUP BY 1, 2
ORDER BY 1
```

**Comment by torkelo** [comment]
@risoms the value column in that query is `value` but grafana shows it as `count`, can you show the query inspector / JSON / DataFrame structure?`

**Comment by risoms** [comment]
Since the data is coming from work. I can't unfortunately.

**Comment by deathchurch** [comment]
This also happens with the MSSQL datasource, to reproduce it you can use the example on the MSSQL datasource documentation page, any graph will have the legend of value {then the metric name}.

**Comment by Vizzyy** [comment]
+1 

All my metrics are now prefixed by "value" 

example query:

```sql
SELECT
  UNIX_TIMESTAMP(timestamp) AS "time",
  hostname AS metric,
  value
FROM server_metrics
WHERE
  $__timeFilter(timestamp) AND
  metric = 'cpu_util' AND             
  hostname in (${host.csv})
ORDER BY timestamp
```

**Comment by torkelo** [comment]
Temporary fix is to update SQL and return value AS Value (capital V)

**Comment by risoms** [comment]
@torkelo Upgrade to which version of postgres?
