### ISSUE TITLE
Grafana 8 variables broken with Postgresql SELECT query on INTEGER field

### ISSUE THREAD

**Issue by Papyruse** [grafana/grafana#35391]
**What happened**:

With Grafana 8, when building a variable with a Postgresql as datasource backend, cannot return integer values with the SELECT query.

![bug1](https://user-images.githubusercontent.com/14894681/121223814-324dd080-c888-11eb-9f64-31f6c3a93979.png)

**What you expected to happen**:

Get values with the SELECT statment on INTEGER field.

![bug2](https://user-images.githubusercontent.com/14894681/121223844-3bd73880-c888-11eb-9484-94f5f3c3c20b.png)

**How to reproduce it (as minimally and precisely as possible)**:

Just make a simple SELECT on an integer field (like id)

**Anything else we need to know?**:

Broken since upgrading Grafana instance from 7 to 8.

**Environment**:
- Grafana version: 8.0
- Data source type & version: Postgresql 12 with Timescaledb 2.0
- OS Grafana is installed on: Linux Debian 10
- User OS & Browser: MacOS & Firefox
- Grafana plugins: none
- Others:

**Comment by zuchka** [comment]
possibly related:
https://github.com/grafana/grafana/issues/35376

**Comment by zuchka** [comment]
I can confirm that this behavior has changed between 7.5.7 (91de51771c) and 8.0 (78d53c5e3d). Tested on macOS + chrome + dummy devenv Postgres.

On 7.5.7:

![CleanShot 2021-06-08 at 17 35 21@2x](https://user-images.githubusercontent.com/37156449/121292147-31676f80-c885-11eb-9611-96618b7afb4b.png)

And here it is on 8.0. Interestingly, it looks like the query gets a successful response, but the data doesn't render:

![CleanShot 2021-06-08 at 18 07 50@2x](https://user-images.githubusercontent.com/37156449/121292242-565be280-c885-11eb-8afc-a6ae599d3310.png)

**Comment by hugohaggmark** [comment]
Introduced by #32257 that filters out integers. Might be worth looking into if we're reused this for other SQL data source. 
https://github.com/grafana/grafana/blob/6d78f92816ce7453a9b446a4ab469a6649d649c2/public/app/plugins/datasource/postgres/response_parser.ts#L25

**Comment by hugohaggmark** [comment]
Passing this over to @grafana/backend-platform
