### ISSUE TITLE
StatPanel 8.0: Legend names no longer show

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#35401]
**What happened**:
Assigned legend names no longer show up. Instead the word "Value" appears.

**What you expected to happen**:
Previous releases showed the legend name in place of "Value"

**How to reproduce it (as minimally and precisely as possible)**:
Assign names in the legend box.

**Anything else we need to know?**:
Previous versions would use legend values, ex: "CPU Count"
<img width="1786" alt="Screen Shot 2021-06-09 at 15 22 18" src="https://user-images.githubusercontent.com/4478053/121304020-c24a5380-c936-11eb-909d-5c14dd8d78db.png">

**Environment**:
- Grafana version: 8.0

**Comment by torkelo** [comment]
@maemigh I am unable to replicate this, can you show your panel json, and using the query inspector / JSON / Dataframe structure,  those two info points could help

**Comment by maemigh** [comment]
Hi @torkelo I've attached the requested info
 
[panel.dataframe.txt](https://github.com/grafana/grafana/files/6628853/panel.dataframe.txt)
[panel.data.txt](https://github.com/grafana/grafana/files/6628854/panel.data.txt)

[panel.json.txt](https://github.com/grafana/grafana/files/6628867/panel.json.txt)

**Comment by torkelo** [comment]
I am unable to replicate this  https://play.grafana.org/d/rympNognz/prometheus-stat-display-name?orgId=1&editPanel=2

![Screenshot from 2021-06-17 10-06-12](https://user-images.githubusercontent.com/10999/122357243-d94efe00-cf53-11eb-8317-12ba9ffa23cf.png)

**Comment by maemigh** [comment]
@torkelo I am able to duplicate using your  https://play.grafana.org/d/rympNognz/prometheus-stat-display-name?orgId=1&editPanel=2

If you change from "Calculate" to "All Values", all the legend values then change to "Value" just like in my original screenshot.

**Comment by maemigh** [comment]
Conversely, in my original dashboard, if I change to "Calculate" then the legend works again. 

I've tested multiple times on the playground and I had a few instances where the panel didn't update until I changed the legend name. ie: it still looked good, but then changing "Query1" to "Query1 2" made the Panel trigger an update and all legend names then turn to "Value".

**Comment by torkelo** [comment]
The all values option does not make that much sense for this type of data, you really just want one result per frame and field. So you can fix it by switching to Calculate 

But still something funky going on

**Comment by torkelo** [comment]
Fixes #35863
