### ISSUE TITLE
Ability to add annotations on the new time series panel

### ISSUE THREAD

**Issue by pkolyvas** [grafana/grafana#35424]
## Use case

As a Grafana user, when I'm reviewing data on a dashbord, the ability to add annotations to a panel vizualization is helpful to highlight specific events or provide some additional context to changes or current states of data. I am unable to click on a on the new time series panel vizualization and add annotations like the old (legacy) time series panel.

## What would you like to be added
Ability to click and add annotations to data on the new Time Series Panel.

Ex. from the legacy time series panel:
![Screen Shot 2021-06-09 at 9 25 40 AM](https://user-images.githubusercontent.com/43178667/121353879-b80f6180-c904-11eb-8736-50134ff4a88b.png)

Related: #30564

**Comment by dprokop** [comment]
@pkolyvas the work around annotations editor is pretty much ready for testing in https://github.com/grafana/grafana/pull/36220 :)
