### ISSUE TITLE
LibraryPanels: Remove library panel icon from title 

### ISSUE THREAD

**Issue by RyuunosukeDS3** [grafana/grafana#35422]
**What would you like to be added**:
The ability to hide the library panel icon from the title, just like you do with query options

**Why is this needed**:
It makes the panel a little bit ugly, and it is not really useful for the final client, only the developer.

**Comment by pkolyvas** [comment]
@RyuunosukeDS3 Thanks for the feedback!

Do your "final clients" have read-only access to the dashboard or are your clients picking from lists of library panels to build their dashboards?

**Comment by torkelo** [comment]
We are considering removing this icon, not sure having it in the first place was a good idea

**Comment by RyuunosukeDS3** [comment]
I'm sorry for the delay, for some reason GutHub didn't ping me...


> @RyuunosukeDS3 Thanks for the feedback!
> 
> Do your "final clients" have read-only access to the dashboard or are your clients picking from lists of library panels to build their dashboards?

Well they have "read only" but i guess giving them the ability tobuild their own dashboard with the library is not a bad idea! LMAO



> We are considering removing this icon, not sure having it in the first place was a good idea

I mean it COULD be great so people who knows grafana know they're linked, but the general user would just keep asking me what that means and if it is possible to hide it (they're quite picky). LMAO

Thanks for the replies!

**Comment by torkelo** [comment]
I think we should just remove it.
