### ISSUE TITLE
Grafana rpm upgrade doesn't restart Grafana server

### ISSUE THREAD

**Issue by xyntrix** [grafana/grafana#3543]
We automatically update Grafana across our fleet. The package update doesn't automatically restart Grafana, and because it doesn't this corrupts the dashboard display.  This requires us to go out and manually restart all of our Grafana servers.

**Comment by torkelo** [comment]
if you want automatic restart you can set this env flag, 
https://github.com/grafana/grafana/blob/master/packaging/deb/default/grafana-server#L17
