### ISSUE TITLE
Explicit list of what API is used behind Prometheus template variable functions

### ISSUE THREAD

**Issue by bwplotka** [grafana/grafana#35437]
Hi, It would be amazing to add exactly the APIs used behind https://grafana.com/docs/grafana/latest/datasources/prometheus/#query-variable

Currently, as Grafana Prometheus compatible backend, it's very implicit - we are guessing. ):

For example, recently Grafana changed (I am guessing) implementation from api/v1/series to api/v1/labels `labels` which broke some backends (it requires Prometheus or other API implementations with matchers).

If not in documentation can we learn here, What API are used behind?  (: Thanks!

**Comment by aocenas** [comment]
@ivanahuckova also maybe we could add Thanos to our devenv blocks to be able to test this kind of changes.

**Comment by ivanahuckova** [comment]
Do you think we should also do Corte then? @aocenas
