### ISSUE TITLE
Support Prometheus /graph api

### ISSUE THREAD

**Issue by roidelapluie** [grafana/grafana#35431]
**What would you like to be added**:

I would be interesting to see if Grafana can expose a Prometheus /graph-compatible endpoint. The endpoint would redirect to Grafana explore.

**Why is this needed**:

Prometheus can send a graph URL to alertmanager. It would be great if in the alertmanager notifications, we could apply a replaceAll template that switches from Prometheus /graph to grafana /prometheus/graph with e.g. a `replaceAll`. The user would then be redirected to /explore, with the correct query.

**Comment by seb-koch** [comment]
Loving the idea! I currently hacked it together right in the receiver configuration by using a set of `reReplaceAll` calls. Here is a working example. The base URL has to be encoded as otherwise the link breaks when viewed in the browser (i.e. in Opsgenie).

```
note: '{{ range .Alerts }}{{ reReplaceAll ".*expr\\=" "https%3A%2F%2Fdomain.tld%2Fgrafana%2Fexplore%3ForgId%3D1%26left%3D%5B%5C%22now-15m%5C%22%2C%5C%22now%5C%22%2C%5C%22Prometheus%5C%22%2C%7B%5C%22exemplar%5C%22%3Atrue%2C%5C%22expr%5C%22%3A%5C%22" .GeneratorURL | reReplaceAll "&g0.tab=1" "%5C%22%7D%5D" }}{{end}}'
```
