### ISSUE TITLE
Dashboards: Dashboards in Application's `plugin.json` stopped working after upgrading to v8

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#35447]
**What happened**:

As per the discussion on the public Grafana Slack ([link](https://grafana.slack.com/archives/C3HJV5PNE/p1623251539076500)), app plugins stopped working in Grafana 8.0.0.

This is a consequence of https://github.com/grafana/grafana/pull/35104 which removed support of endpoints that contained slug, but a leftover remained:

https://github.com/grafana/grafana/blob/e3afb63e62d5fb7ec577c33efaa7473de37aff45/pkg/plugins/app_plugin.go#L119
and

https://github.com/grafana/grafana/blob/e3afb63e62d5fb7ec577c33efaa7473de37aff45/pkg/api/index.go#L111

**What you expected to happen**:
Application dashboards to work properly in Grafana v8.0.0.

**How to reproduce it (as minimally and precisely as possible)**:
Comment on the public Slack says:

> the dashboard is loaded and works, but they are not accessible using the menu - something was changed or should be updated

which is expected since it can't find the correct slug.

**Environment**:
- Grafana version: v8.0.0

**Comment by marefr** [comment]
If it would be super tricky to solve this in a rather fast and future proof way without any breaking changes, we might want to re-introduce some internal support for these slug-API endpoints as the short-term solution and think about how to solve this longer term.

**Comment by marefr** [comment]
Suggested solution:

Introduce a new route `/p/<plugin-id>/slug` that would get the dashboard and redirect to proper dashboard URL, i.e. `/d/<uid>/<slug>`. 

Introduce a new api route specific for looking up plugin dashboard by plugin id and slug, e.g. `/api/plugins/<plugin id>/dashboards/slug/<slug>`. There's already an endpoint for fetching all plugin dashboards `/api/plugins/<plugin id>/dashboards.

Files/lines changed in #35507 need to use the `/p/<plugin-id>/slug` URL instead.

**Comment by rozetko** [comment]
Hey @idafurjes!
Seems like the issue is closed but not fixed yet. Are there plans to fix this? Or is there any workaround to make the left panel links work for Application plugins in Grafana 8+ maybe?

**Comment by idafurjes** [comment]
@rozetko we closed the issue because we deprecate using slugs, we will rely on UID instead

**Comment by rozetko** [comment]
@idafurjes 
so there is no way to make the left panel links work for Application plugins in Grafana 8+ until the fix?
