### ISSUE TITLE
No Tooltip / edit Menue (Popup) from Tablet

### ISSUE THREAD

**Issue by thechris1992** [grafana/grafana#35445]
**What happened**:
V 7.5.x - the tooltip and Hoover menu comes up when touching the i or the menu arrow from the Panels.

**What you expected to happen**:
touch = click or mousehover

**How to reproduce it (as minimally and precisely as possible)**:
use Grafana over a Tablet and Try to change a Panel
On IPhone it works. Strange… After clearing the Cache on my Tablett it still dont work 

 i got it.
horizontally = no popup 
upright = popup 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: influxDB
- OS Grafana is installed on: Linux Scretch (Rasperian OS)
- User OS & Browser: IPad OS 14.6, Safari, Google Crome
- Grafana plugins: /
- Others:

**Comment by zuchka** [comment]
> i got it.
horizontally = no popup
upright = popup

nicely done! Glad you figured this out.
