### ISSUE TITLE
Value to text on table panel V2.6

### ISSUE THREAD

**Issue by Samuel1989** [grafana/grafana#3544]
Hey Guys,

I was wonder if value to text transformation is already available for tables or potentially planned into a future release?

Part of what I am using Grafana for is to keep track of active services, so I merely have a active state of 1 or a down state of 0, I then transform these into "Active" or "Inactive" via the single stat value to text functionality. As more and more services become available it would actually be really nice to just have a table of Active/Inactive with cell colours of green or red.

Sam

**Comment by KSGBridgeman** [comment]
I have been trying to do the same.  My work around is to build a dashboard that combines Text and SingleStat boxes in a row, then have it repeat using variables: 

Create Variable: processName  Check ALL
Row Editor: Row Height: 100px   Repeat Row: select <processName>
Add Panel: Text Panel   Title: $processName
Add Panel: SingleStat    Query:  processName:$processName  Metric: State
        Options: Value to Text Mapping:  1 -> UP   0 -> DOWN

then you can use the selector to choose a specific service, some, or all services to get a service panel.

**Comment by henry-spanka** [comment]
+1

**Comment by vitorboschi** [comment]
+1

**Comment by evandro-portugal** [comment]
+1

**Comment by mattttt** [comment]
This would be quite valuable for worldPing events table as well.

**Comment by slsims03** [comment]
+1 Would definitely be a very useful feature

**Comment by kirang20** [comment]
+1

**Comment by ocervell** [comment]
+1

**Comment by GLutzBR** [comment]
+1

**Comment by trojanc** [comment]
+1

**Comment by slsims03** [comment]
Any traction that on this?

**Comment by Kaauw** [comment]
+1

**Comment by gabosvk** [comment]
+1

**Comment by lelando** [comment]
+1

**Comment by delgod** [comment]
+1

**Comment by jazzerjazzer** [comment]
+1

**Comment by mtehonica** [comment]
+1

**Comment by sharedansi** [comment]
+1

**Comment by westofariver** [comment]
+1

**Comment by szymic1** [comment]
+1

**Comment by TomasMFranco** [comment]
+1. 
Would be really useful to us as well.
I'd prefer to give the user a simple string rather than a code to look up.

**Comment by mjtrangoni** [comment]
+1

**Comment by ngrangeia** [comment]
+1

**Comment by cloudbehl** [comment]
+1

**Comment by defenestration** [comment]
This seems doable if you set the Cell Type to a 'String'. The 'Value Mappings' options then become available. I'm using Grafana 5.3.2.

**Comment by Willis0826** [comment]
@defenestration Thanks, I found it. However, I was wonder is that possible to change the color of the text which been converted?

**Comment by defenestration** [comment]
If you use the range/threshold setting it should be able to color the text.

**Comment by Willis0826** [comment]
Thanks again! I got it : )
It seems like if we want to show the `value to text` and change the `color of text` we will need to use `Range to text` and `Thresholds` both.

**Comment by torkelo** [comment]
7.0 table panel supports value to text mappings
