### ISSUE TITLE
Add filters to legend formatter with Prometheus datasource

### ISSUE THREAD

**Issue by dontrebootme** [grafana/grafana#3545]
Similar to: http://prometheus.io/docs/visualization/promdash/#filters
Is this already supported today?

**Comment by mtanda** [comment]
Not yet.
In Grafana, underscore.js template function is used to generate legend string.
http://underscorejs.org/#template

So you can use the underscore.js feature.

**Comment by roman-vynar** [comment]
You can just use a normal JS.

Say your metric name is `mysql_global_status_blabla` and you want to get its part `blabla` on the legend:
```
{{ __name__.replace("mysql_global_status_", "") }}
```
Similar with the labels.

**Comment by juliusv** [comment]
Ah. That's why `{{ location }}` once put the browser's URL into the legend instead of the `location` label value (don't have a Grafana lying around to try at the moment, but a friend had this problem). That sounds like a problem when random JS vars collide with Prometheus label names.

**Comment by mtanda** [comment]
> By default, template places the values from your data in the local scope via the with statement. However, you can specify a single variable name with the variable setting. This can significantly improve the speed at which a template is able to render.

http://underscorejs.org/#template

Avoid using "with statement" will fix ```{{ location }}``` problem, but it need to specify variable name like ```{{ labels.job }}```.

I'm not sure which is better...

**Comment by grobie** [comment]
Would it be possible to have both in order to not break backwards compatibility? Like adding a `labels` variable in order to allow calls like `labels.location` and other overloaded names (ironically now `labels.labels`).

**Comment by mtanda** [comment]
@grobie When setting "options.variable" in lodash, need to change "legend format string" itself.
https://lodash.com/docs#template
All variable name reference should have "options.variable" prefix.

I try to fix this by https://github.com/grafana/grafana/pull/5096 .

**Comment by FauxFaux** [comment]
It appears that this pull request, and the 3.1 release, has crippled the ability to run arbitrary JS, meaning that there's a regression in functionality here. That is, `.replace()` no-longer works, and this feature remains unimplemented, with no work around.

**Comment by torkelo** [comment]
Sorry for taking time to merge this, looks like a hotly requested feature. Just want to extract some of the logic to core grafana so other data sources can take advantage of this feature. Hope to be able to do this soon.

**Comment by sandersaares** [comment]
Oh no, legends without `.replace()`? Say it aint so!

**Comment by mbjelac** [comment]
Thanks @pvalsecc , `label_replace` works like a charm!

**Comment by Redsandro** [comment]
@pvalsecc @mbjelac I can't figure this out. What would you write to simulate a _Legend Format_ `.replace('some_long_name', 'short')` using `label_replace`?

**Comment by mbjelac** [comment]
@Redsandro I used it for removing part of a label text, but I think you can use it for replacement too.
In the meantime I fixed my template regex, so I don't need this anymore, but I checked [the docs](https://prometheus.io/docs/prometheus/latest/querying/functions/#label_replace()) again, and here's how I think it would work:

If `my_metric` has a label `my_label`, then

`label_replace(my_metric, "other_label", "$1short$2", "my_label", "(.*)(some_long_name)(.*)")`

should create a label `other_label` with `some_long_name` replaced with `short`.

But check the regex capture group syntax... I just wrote it from my head. It might have errors.

**Comment by pwm** [comment]
@mbjelac amazing, thanks a lot for this, I've completely missed it in prometheus' doc!

**Comment by mdlayher** [comment]
Also ran into this today, and Prometheus' label_replace seems to work.  I was able to use this to retrieve the first segment of a host's FQDN for an instance label:

```
label_replace(x_keys{job="myjob",instance=~"$region.*"} > 0, "instance", "$1", "instance", "(.*).internal.*")
```

It would be super nice if something could be done in the Legend format though, such as `{{instance.trim_right(.)}}`, but I have no clue how feasible that is. :) Thanks for Grafana.

**Comment by candlerb** [comment]
I have a similar problem here.  I want the legend to show prometheus tags ifDescr and ifAlias, but ifAlias is sometimes empty:

```
ifType_info{ifAlias="",ifDescr="vlan254",ifIndex="10",ifName="vlan254",ifType="l2vlan"} 1
ifType_info{ifAlias="",ifDescr="vlan255",ifIndex="9",ifName="vlan255",ifType="l2vlan"} 1
ifType_info{ifAlias="Hurricane Electric IPv6 Tunnel Broker",ifDescr="sit1",ifIndex="15",ifName="sit1",ifType="other"} 1
```

If I use the legend format of `{{ifDescr}} {{ifAlias}}`, then for any timeseries where ifAlias is empty, the literal string "ifAlias" appears in the legend.  (I am guessing the value is undefined, and treated as an error?)

I've been unable to find *any* documentation of the syntax of legend formats, and what is allowed or not allowed within them.

But it certainly doesn't seem to be Javascript: e.g. `{{ifAlias ? ifAlias : ifDescr}}` just gives the whole thing as a literal string, whether or not ifAlias is defined.

**Comment by anupamdivesh** [comment]
In which Version this fix has being done. Currently i am using grafana-4.6.3-1.x86_64 and .replace() is not working on that

Thanks in advance

**Comment by anupamdivesh** [comment]
> It appears that this pull request, and the 3.1 release, has crippled the ability to run arbitrary JS, meaning that there's a regression in functionality here. That is, `.replace()` no-longer works, and this feature remains unimplemented, with no work around.

Is this issue going to fix in later release

**Comment by aocenas** [comment]
I think custom legend formatting should be supported now. Please reopen if still relevant

**Comment by candlerb** [comment]
Can you point to the documentation of what syntax is allowed in legend expressions?  And in what version did it change? Googling for "grafana custom legend formatting" isn't turning up anything useful.

With Grafana 6.7.4, I still get the issues mentioned earlier.  Configuring this query with custom legend:

![image](https://user-images.githubusercontent.com/44789/85539556-e1f54880-b60d-11ea-944e-4a054871a2d6.png)

gives this result:

![image](https://user-images.githubusercontent.com/44789/85539480-c5f1a700-b60d-11ea-917e-77c285a27179.png)

The problems are:
1. This availability and syntax of this limited templating language in legends is not documented AFAICS
2. If you expand a field like `{{ifAlias}}` and that value doesn't exist, you get the literal string `ifAlias`, and I want a way to replace this with a (possibly blank) default value

**Comment by ishangupta-ds** [comment]
> Can you point to the documentation of what syntax is allowed in legend expressions? And in what version did it change? Googling for "grafana custom legend formatting" isn't turning up anything useful.
> 
> With Grafana 6.7.4, I still get the issues mentioned earlier. Configuring this query with custom legend:
> 
> ![image](https://user-images.githubusercontent.com/44789/85539556-e1f54880-b60d-11ea-944e-4a054871a2d6.png)
> 
> gives this result:
> 
> ![image](https://user-images.githubusercontent.com/44789/85539480-c5f1a700-b60d-11ea-917e-77c285a27179.png)
> 
> The problems are:
> 
> 1. This availability and syntax of this limited templating language in legends is not documented AFAICS
> 2. If you expand a field like `{{ifAlias}}` and that value doesn't exist, you get the literal string `ifAlias`, and I want a way to replace this with a (possibly blank) default value

we also have a similar requirement mentioned here, https://github.com/grafana/grafana/pull/6627#issuecomment-843973143
