### ISSUE TITLE
Docs: apt-key is deprecated and should not be used

### ISSUE THREAD

**Issue by 532910** [grafana/grafana#35467]
https://github.com/grafana/grafana/blob/main/docs/sources/installation/debian.md#to-install-the-latest-enterprise-edition
> wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

https://manpages.debian.org/buster/apt/apt-key.8.en.html#COMMANDS

> Note: Instead of using this command a keyring should be placed directly in the /etc/apt/trusted.gpg.d/ directory with a descriptive name and either "gpg" or "asc" as file extension.

Moreover, instead of `/etc/apt/trusted.gpg.d/` it should be placed in `/usr/share/keyrings/` with `signed-by` in sources.list.
https://wiki.debian.org/DebianRepository/UseThirdParty#Sources.list_entry. For example:
```
deb [signed-by=/usr/share/keyrings/deriv-archive-keyring.gpg] https://deriv.example.net/debian/ stable main
```

**Comment by zuchka** [comment]
possibly related to recent apt issues:

https://github.com/grafana/grafana/issues/35273

**Comment by 532910** [comment]
I'd not say so.

**Comment by zuchka** [comment]
@grafana/backend-platform do you have input here? `apt-key` is deprecated, which means the docs will eventually need updating, correct? If you agree and this sounds like a basic chore I could try starting a PR for it 👍

**Comment by malcolmholmes** [comment]
Please feel free to make a PR. All help appreciated.

**Comment by idafurjes** [comment]
@zuchka I removed this issue from backend issue triage board, since you are opening a PR
