### ISSUE TITLE
Does query support LIMIT on number of rows?

### ISSUE THREAD

**Issue by Srungaram** [grafana/grafana#3546]
Example :SELECT last("value") AS "value" FROM "measure1" WHERE $timeFilter GROUP BY "name"
LIMIT 10

**Comment by torkelo** [comment]
Its not supported in query editor. I think InfluxDB has a limit query word, but you can easily check the influxdb docs :)

**Comment by Srungaram** [comment]
Yes InfluxDB has it but I am getting blank screen when using it in Grafana

**Comment by torkelo** [comment]
@Srungaram 
It works fine for me here:
http://play.grafana.org/dashboard/db/influxdb-table?panelId=3&fullscreen&edit
