### ISSUE TITLE
dashboard init failed after upgrading to 8.0.0-beta3

### ISSUE THREAD

**Issue by baurine** [grafana/grafana#35478]
**What happened**:

Some dashboards init failed after upgrading grafana 8.0.0-beta3.

![image](https://user-images.githubusercontent.com/1284531/121488419-a5308600-ca05-11eb-9bb4-6a765ab232c7.png)

![image](https://user-images.githubusercontent.com/1284531/121488478-afeb1b00-ca05-11eb-8cef-a01d9c30d7d5.png)

![image](https://user-images.githubusercontent.com/1284531/121489624-d9f10d00-ca06-11eb-945c-73fd6535ad3b.png)

**What you expected to happen**:

The dashboards can be loaded normally.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade the grafana from 7.5.4 to 8.0.0-beta3.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0-beta3
- Data source type & version: Prometheus
- OS Grafana is installed on: macOS and Linux
- User OS & Browser: Chrome 91
- Grafana plugins:
- Others:

**Comment by baurine** [comment]
The issue still exists in the 8.0.0 version.

**Comment by JohnnyQQQQ** [comment]
I had the same problem, the issue is already fixed and was tracked here https://github.com/grafana/grafana/issues/34788 It will be part of the 8.0.1 release

**Comment by baurine** [comment]
thanks @JohnnyQQQQ , glad to hear it's has a fix, I will close this issue.
