### ISSUE TITLE
Regex handling in datasource variables vs. default datasource

### ISSUE THREAD

**Issue by rsommer** [grafana/grafana#35476]
**What happened**:
When defining a datasource-variable with regex filtering like `/^fancyname/`, the name `default` appears while not matching the filter.

**What you expected to happen**:
No `default` in the datasource list if not matching the regex filter.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an empty dashboard
2. Add a new variable fpr Type Data source
3. Under options, select a type containing your default data source
4. Add regex filter not matching `default`

**Anything else we need to know?**:
What seems to be merged on #32625 is not to be found in the git checkout and seems more correct. Instead, the code from #31208 unconditionally adds `default` to the result list, ignoring any regex-filter.

The referenced commit da76d2a74a284156325eb0b3e5a23e097677010a is found on github, but if I check out the code:

```
$ git remote -v
origin	https://github.com/grafana/grafana.git (fetch)
origin	https://github.com/grafana/grafana.git (push)

$ git show HEAD
commit e3afb63e62d5fb7ec577c33efaa7473de37aff45 (HEAD -> main, origin/main, origin/HEAD)

$ git show da76d2a74a284156325eb0b3e5a23e097677010a
fatal: bad object da76d2a74a284156325eb0b3e5a23e097677010a
```

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: various
- OS Grafana is installed on: Linux/Debian buster
- User OS & Browser: Linux/Ubuntu, google chrome
- Grafana plugins: default

**Comment by hugohaggmark** [comment]
Hi @rsommer, thank you for taking the time to write this issue. The commit I think you're looking for is https://github.com/grafana/grafana/commit/c5241aa6108551b70dd40e7e34d5da82643e621b and not da76d2a74a284156325eb0b3e5a23e097677010a. 

I'm working on a fix for this, should be released in 8.0.2. Thank you!
