### ISSUE TITLE
Import template with data source the template does not work. 

### ISSUE THREAD

**Issue by athingisathing** [grafana/grafana#3547]
When importing a dashboard with a template that has a data source the datasource is there (some times *1) but not active until you select settings>templating>edit>update for all variables. The data is then working and the templates then provide dynamic graphs. 

The data source is already in the system.
The graph in the dashboard works once you follow the steps above...

1* {
The data srouce does not always show up in the template edit form even though it was there on import and in the the datasources... also any custom datasource name does not have a value in the options html... This is secondary due to the lack of reproducibility but may be root or linked cause.    option value="object:null" 

```shell
<li ng-show="current.type === 'query'">
								<select class="input input-medium tight-form-input last ng-pristine ng-valid ng-touched" ng-model="current.datasource" ng-options="f.value as f.name for f in datasources"><option value="string:grafana" label="grafana">grafana</option><option value="string:graphite.staging" label="graphite.staging" selected="selected">graphite.staging</option><option value="object:null" label="testdata">testdata</option></select>
							</li>
>
shell
}

**Comment by torkelo** [comment]
the data source marked as default will have the `null` value. 

If you want to update template variable values on dashboard load/import please check the Refresh checkbox.
