### ISSUE TITLE
Panel Inspect JSON: Changing property 'type' doesn't update in dashboard after changing it via inspect JSON and clicking on apply

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#35479]
**What happened:** 

Changing `type` on Panel -> InspectJson does not update the visualization in the dashboard

**What you expected to happen:** 

Visualization is updated if the type is changed.

**How to reproduce it (as minimally and precisely as possible):** 

Go to any timeseries panel in dashboard -> Inspect -> Panel JSON and edit the following property:

"type": "gauge"

![changing-type-json](https://user-images.githubusercontent.com/239999/121500829-f2e5c800-c9de-11eb-853e-ef881918f40f.gif)

Anything else we need to know?: Able to reproduce in Play Grafana.

Environment: Any

Grafana version: 7.2 and above
Data source type & version: Any
OS Grafana is installed on: Any
User OS & Browser: Any
Grafana plugins: ANy
Others:

**Comment by ryantxu** [comment]
This should probably just emit an error -- the current logic locks the type+id since changing them manually can leave things in a pretty odd state.
