### ISSUE TITLE
allow user to make api calls using their LDAP credential

### ISSUE THREAD

**Issue by schen59** [grafana/grafana#3548]
Looks like right now if we use LDAP integration we can log in successfully in the web console. However, it seems that a user can not make API calls directly using his/her LDAP credential. It always throw "invalid username or password" error. I was thinking is it possible to add some support like 'initContextWithLdap" to allow api calls with LDAP?

**Comment by torkelo** [comment]
you can make api calls using api key, you can only login with ldap. But if you want to do api call you could login and do api calls with the session cookie.

**Comment by schen59** [comment]
Ok. Thanks for the explanation. Is there any reason why we can only login with ldap but can not make api calls with ldap?
