### ISSUE TITLE
Double click on graph to zoom out

### ISSUE THREAD

**Issue by padcom** [grafana/grafana#3549]
Currently when a panel is embedded there is a way to zoom in (by selecting portion of the graph) but no way to zoom out. Other charting solution (i.e. Dygraph) solved that problem by using double click (see demo on their web site: http://dygraphs.com/). Do you think that something like it could also be available in Grafana's charts?

**Comment by torkelo** [comment]
+1

**Comment by toni-moreno** [comment]
+1

**Comment by bergquist** [comment]
That was the intention for this PR #1541 
But it's way to old to be merged.

Perhaps that PR can give some guidance for solving this problem.

**Comment by jahed** [comment]
Worth noting this feature request is already covered in #614 from a while back.

**Comment by padcom** [comment]
Cool! Thank you!
