### ISSUE TITLE
Annotations with predefined colors don't show anchor

### ISSUE THREAD

**Issue by marcbachmann** [grafana/grafana#35495]
**What happened**:
Annotations don't show any anchor when using a preconfigured color of the small color bubbles.

The main colors are working properly.
Effect on Dashboard             |  Configured color of Annotation
:-------------------------:|:-------------------------:
<img width="501" alt="Screenshot 2021-06-10 at 12 41 36" src="https://user-images.githubusercontent.com/431376/121511978-845a3780-c9e9-11eb-8a32-1b0f0e1fae1e.png">  | <img width="360" alt="Screenshot 2021-06-10 at 12 42 30" src="https://user-images.githubusercontent.com/431376/121512014-8fad6300-c9e9-11eb-877a-05d53767cd2e.png">

The line has the wrong color and the anchor is missing, so it also won't show any info on hover.
<img width="300" alt="Screenshot 2021-06-10 at 17 12 09" src="https://user-images.githubusercontent.com/431376/121550597-293b3b80-ca0f-11eb-846e-b301a7459565.png">

**What you expected to happen**:
The primary colors (big color bubble) are working properly. Both should behave the same.

Effect on Dashboard             |  Configured color of Annotation
:-------------------------:|:-------------------------:
<img width="506" alt="Screenshot 2021-06-10 at 12 42 01" src="https://user-images.githubusercontent.com/431376/121511936-786e7580-c9e9-11eb-821d-1a035d9ccb04.png">  | <img width="361" alt="Screenshot 2021-06-10 at 12 42 18" src="https://user-images.githubusercontent.com/431376/121511904-6d1b4a00-c9e9-11eb-8582-342433fc54e8.png">

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Dashboard with a panel
- Add an annotation to the panel (using built in possible or any source)
- Go to the annotations setting and choose a secondary color to display (in a small color bubble)
- Go to the dashboard and observe that the anchor is not present

**Environment**:
- Grafana version: 8.0.0 (maybe older)
- Data source type & version: Loki v2.2.1
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: Chrome (latest)

**Comment by torkelo** [comment]
thanks for reporting this! If you switch to new Time series panel it should be fixed but old Graph is showing this. We will fix in next patch release!

**Comment by marcbachmann** [comment]
Thanks for the info. Btw. If I switch to the new panel, the alert get dropped.

**Comment by torkelo** [comment]
The alert?

**Comment by marcbachmann** [comment]
that one 
![image](https://user-images.githubusercontent.com/431376/121562409-b4b9ca00-ca19-11eb-94aa-88864d0ab8a5.png)
