### ISSUE TITLE
Alerting: Standardize UI

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#35496]
- **Notification policy page** even if similar to Contact points, on a closer look elements are not standardized. Please fix the following under notification policy:
    - Expand collapse caret icon should have the same size on all tables. The one in the notification policy is smaller. 
    - Edit/ delete icons should look the same as actions on table rows. We decided a while ago to just show icons, without the label
    - heading sizes -  Headings should be `<4h>` followed by a `<p>` description, which is grey. Also, keep the same spacing between elements \
    - table headers should be bold
- **Tables** - half of them are using `<table>` element, half of them are made using `<div>`. We want to use` <div>` so they are responsive

**Comment by peterholmberg** [comment]
closed via https://github.com/grafana/grafana/pull/38770
