### ISSUE TITLE
Alerting: rule creation - query result display

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#35497]
On Alert Rule creation - Don’t display a stat/time series/table area under expressions if they can only have 1 or 0 value (true or false), it’s a waste of space and looks like things are not working

**Comment by kylebrandt** [comment]
I think it can be important in certain cases that it still can be seen. For example imagine a chunk of logic in the math expression like `($A || $B) && ! $C` - the output can help confirm expected results ( logic can be confusing :-) ).

If the visualizations could be collapsed on their own independent of the queries, than we could choose not to expand things by default that we think are usually not helpful, without removing the ability to inspect it more.

**Comment by gillesdemey** [comment]
We should keep it for now because as @kylebrandt pointed out that it would be useful for debugging math and other expressions, we'll keep this in mind when we do another UX review later this month.
