### ISSUE TITLE
Metric alias leaks to other metrics when tags are subset of tags

### ISSUE THREAD

**Issue by timurb** [grafana/grafana#3550]
I see the following in Grafana 2.5.0 with OpenTSDB backend. I'm using OpenTSDB 2.1.3 now.

Scenario:
* add 2 metrics with the same name to the metrics list
* first metric has attached `tag1=$tag1` and set Alias to `foobar`
* second metric has attached `tag1=$tag1, tag2=*` and don't set Alias

I see Alias attached to all of the metrics but not only to the first one as I'd expect.

**Comment by utkarshcmu** [comment]
dupe #1876

**Comment by torkelo** [comment]
problem is with OpenTSDB and query  -> result matching , see #1876
