### ISSUE TITLE
CloudWatch Stat for Entire Dashboard Time Range

### ISSUE THREAD

**Issue by HarryEMartland** [grafana/grafana#35506]
**What would you like to be added**:

The ability to create a stat for a CloudWatch query for the entire time range of a dashboard.

I can do this with AWS dashboards by selecting the "Time range value shows the value from the entire time range." option seen below.

<img width="985" alt="Screenshot 2021-06-10 at 13 02 10" src="https://user-images.githubusercontent.com/2979931/121521635-3692fe80-c9ec-11eb-97a5-c01735d92673.png">

**Why is this needed**:

We are building dashboards to show services SLOs. I want be able to show the current value of the SLI for a given window chosen using the dashboard range dropdown.

**Comment by torkelo** [comment]
All queries use the dashboard time range.

Not sure I understand what you mean

**Comment by HarryEMartland** [comment]
Sorry, I want to show <error requests> / <total requests>. Lets say the dashboards time range is 5 minutes and I have the following data.

errorRequests = [10,11,10,9,11]
totalRequests = [100,110,99,105,104]

I believe currently if I create a stat panel the value would show 0.105 (11/104) where I want it to show  0.0810 ((10+11+1+9+11)/(100+110+99+105+104)) which is the value over the whole time range. 

When using prometheus we have the instant option. I would like the same when using CloudWatch metrics :).

<img width="725" alt="Screenshot 2021-06-10 at 14 12 16" src="https://user-images.githubusercontent.com/2979931/121530973-e3be4480-c9f5-11eb-9ee1-c7ed316eab37.png">

**Comment by torkelo** [comment]
or in the stat panel you can choose to show the sum of all values (under calculate)
