### ISSUE TITLE
DashboardSettings: TimeZone dropdown doesn't change the timezone

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#35504]
**Doesn't work from dashboard settings:**
1. Open this dashboard https://play.grafana.org/d/l4CyfC6Mz/dashboardsettings-timezone-dropdown-doesnt-change-the-timezone-35504?orgId=1
2. Goto dashboard settings
3. Change the time zone, time zone changes [Ok]
3. Go back to dashboard
4. The time zone change is not reflected in panel or in the time picker [NOT OK]

**Works from time picker:**
1. Open this dashboard https://play.grafana.org/d/l4CyfC6Mz/dashboardsettings-timezone-dropdown-doesnt-change-the-timezone-35504?orgId=1
2. Change the time zone in the time picker, time zone changes [Ok]
3. The time zone changes are reflected in time picker [OK]
4. Goto dashboard settings
5. The time zone changes are reflected in time zone picker [OK]

**Comment by mckn** [comment]
Some background information to consider. You can configure the timeZone on multiple levels so this is one of the reasons why it isn't in redux (for everything). 

You can configure it on the following levels:

- organizational level
- user level
- dashboard level

I am happy to help out explaining this a bit more if needed 🙏🏻 🙌🏻
