### ISSUE TITLE
Grafana 8.0.0: Preferences not saved when using Firefox

### ISSUE THREAD

**Issue by trueuto** [grafana/grafana#35503]
**What happened**: Changed Organisation's preferences (Theme, Timezone or Home Dashboard), clicked "Save" button. Preferences were not saved, preference page reloads showing old values. An "Unexpected error" message is briefly visible before page reloads. It happens only when using Firefox browser.

**What you expected to happen**: Preferences are saved.

**How to reproduce it (as minimally and precisely as possible)**: Use Firefox, login to Grafana, open Organisation's Preferences, modify Theme, click Save.

**Anything else we need to know?**: It seems that the PUT request is not send in Grafana 8.0.0 when the "Save" button is clicked. I have checked it with 7.5.0 and when clicked, "Save" button sends PUT request with JSON payload. Subsequent "Save" clicks in 8.0.0 finally cause the PUT request to be sent but with no payload. Resending the request (e.g. via WebDeveloper tools) results in 403 response. Tried with most recent Firefox and with some previous versions on both Windows and Linux. Checked on locally installed version (from .deb file) as well as a Docker container (Ubuntu based).

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: n/a
- OS Grafana is installed on: Debian (.deb installation), Ubuntu (Docker image)
- User OS & Browser: Windows 10/FF 89.0, Linux/FF 78.x ESR
- Grafana plugins: n/a
- Others: n/a

**Comment by zuchka** [comment]
I can confirm this. Reproduced using play.grafana.org + macOS + FF 89.0. **Chrome 91.0.4472.77 worked as expected.** Seems specific to the button in the `preferences` component that is reused on /profile and /users.

Here is a vid of FF 89 vs Chrome 91 on play.grafana.org (v8.0.0 (41f0542c1e)):

![CleanShot 2021-06-10 at 12 41 47](https://user-images.githubusercontent.com/37156449/121606934-c8017100-c9ea-11eb-9050-4e3f867370ec.gif)
