### ISSUE TITLE
Time Series Panel can not load 

### ISSUE THREAD

**Issue by Betula-L** [grafana/grafana#35500]
**What happened**:

We can not load time series panel in recent commit `e3afb63e62d5fb7ec577c33efaa7473de37aff45`, i.e. branch `main`.

![图片](https://user-images.githubusercontent.com/6059935/121514239-5e9b5580-ca1e-11eb-96f9-37cc08f5f96a.png)

**What you expected to happen**:

Show panel as expected.

**Anything else we need to know?**:

It works well in v8.0.0, but not in branch `main`.

**Comment by dprokop** [comment]
@Betula-L can you please share your Dashboard JSON if possible and the stack trace from the console? I've just lookied if it's broken on main, and it seems to work OK.

**Comment by Betula-L** [comment]
Sorry,  i can not reproduce it now. Closed.
