### ISSUE TITLE
Table panel: Allow custom column headings or hiding it

### ISSUE THREAD

**Issue by volter** [grafana/grafana#3551]
I'm making this request with JSON Data mode and ES data in mind. The field names may not be what you want in the heading and I suppose there are cases where you would like to hide the headings too -- maybe just to save space.

**Comment by JoBrad** [comment]
I would love this feature! I am using the table panel to show Top n Items by Count/Amount, and the heading of "Metric" is not ideal.

**Comment by volter** [comment]
How do you manage to do that? I didn't get that working.

**Comment by JoBrad** [comment]
I used the highestCurrent function, which takes an integer for how many values you want.

**Comment by noizex** [comment]
Would be great to have this feature, right now a lot of column names that come from Elasticsearch look like garbage - data.testResults.totalCount, makes it really hard to fit all columns properly into the table. Could be even added as a feature of column styling, so we could type our own column to override the original one.

**Comment by sunnos9** [comment]
:+1:

**Comment by henriquemaciel** [comment]
+1

**Comment by lucadistefano** [comment]
+1

**Comment by Abhishekpan** [comment]
@torkelo  can you please tell us in which version fix of #5466 will be incorporate?

**Comment by torkelo** [comment]
@Abhishekpan none? that PR was not merged

**Comment by gunererd** [comment]
+1

**Comment by inselbuch** [comment]
+1

**Comment by Petyas** [comment]
+1

**Comment by foxos42** [comment]
+1

**Comment by h0wser** [comment]
+1

**Comment by nvh-gel** [comment]
+1

**Comment by lipoteFR** [comment]
+1

**Comment by jonesn** [comment]
+1

**Comment by mmccollum2** [comment]
+1

**Comment by Mick66** [comment]
+1

**Comment by Exocomp** [comment]
+1

**Comment by mariusionescu** [comment]
+1

**Comment by ajaybhatnagar** [comment]
+10

**Comment by valerioPengue** [comment]
+1

**Comment by lesterwang** [comment]
+1

**Comment by lakal-malimage** [comment]
We can edit column headers by editing panel json

**Comment by marcolino7** [comment]
Hi,
but is it possible to HIDE column?

Thanks
Marco

**Comment by torkelo** [comment]
yes, in 4.3.2 there is a column style rule option to hide column

**Comment by costimuraru** [comment]
Nice!
For reference, you need to set the Column Type to `Hidden`.
<img width="982" alt="screen shot 2018-11-21 at 14 07 33" src="https://user-images.githubusercontent.com/952836/48840268-d210e500-ed96-11e8-8066-5e6ffea22ba8.png">
