### ISSUE TITLE
Grafana 8.0.0: template variable don't show numeric values anymore

### ISSUE THREAD

**Issue by 321freddy** [grafana/grafana#35516]
**What happened**:
Updated Grafana to 8.0.  I noticed that some template variables with queries to PostgreSQL didn't return any values. Here is one example (sensor_id is a number):
`SELECT sensor_id
FROM sensors
WHERE virtual_sensor_id = 1`
![grafana1](https://user-images.githubusercontent.com/28625949/121532464-a5c61e00-c9ff-11eb-97c2-2e76abc1aa22.PNG)

Casting the value to text on the DB side fixed this for now:
`SELECT sensor_id::text
FROM sensors
WHERE virtual_sensor_id = 1`
![grafana2](https://user-images.githubusercontent.com/28625949/121532505-b080b300-c9ff-11eb-9e4c-00eaf8fa794d.PNG)

**What you expected to happen**:
Grafana should accept numeric values for template variables (as in previous versions)

**How to reproduce it (as minimally and precisely as possible)**:
- Update to Grafana 8.0.0
- Create a template variable with the above queries

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: PostgreSQL 13 with TimescaleDB plugin v2.3.0
- OS Grafana is installed on: Docker
- User OS & Browser: Firefox 78.10.0esr, Windows10
- Grafana plugins: None
- Others:

**Comment by lux4rd0** [comment]
Is this similar to https://github.com/grafana/grafana/issues/35391

**Comment by torkelo** [comment]
fixed in 8.0.1 https://github.com/grafana/grafana/pull/35411
