### ISSUE TITLE
Table panel doesn't handle variables

### ISSUE THREAD

**Issue by KSGBridgeman** [grafana/grafana#3552]
Attempting to filter table using variable.  Datasource is ElasticSearch.

Display of 'RAW Document' seem to me should allow a variable in one of the fields to limit the displayed records.

Say I add a variable for FieldX consisting of values A, B, and C.  The overall table may have 100 rows.

I add a Lucene query:  fieldX:$FieldX

I select 'A' in the drop down, should only see the 20 'A' rows.
I select 'All', should see all 100 rows.
etc.

If it doesn't work, or is not intended to work, then Variables should be blocked on Table

**Comment by torkelo** [comment]
Seems to work fine, http://play.grafana.org/dashboard/db/elasticsearch-templated-table
