### ISSUE TITLE
Panels/visualizations/table/ change background by text information

### ISSUE THREAD

**Issue by syswombat** [grafana/grafana#35526]
**What would you like to be added**:
https://grafana.com/docs/grafana/next/panels/visualizations/table/

i would like to change the background

where Info’s are
if down should turn red the background
if up green the background
if other another color the background

thanks for a feedback how to do this

have a nice day
vinc

**Why is this needed**:

i got some information which are confirmed or with error or not clear
so the Error should get a orange Background or a Bold Red text

**Comment by torkelo** [comment]
This is already possible in v8, you can use value mappings to assign colors to strings. For table you then need to assing cell display mode to color background
Example 
https://play.grafana.org/d/OhR1ID6Mk/3-table?orgId=1&editPanel=16

**Comment by syswombat** [comment]
hmm so the problem is my v7.5x Grafana ;-(

**Comment by torkelo** [comment]
We do not add big new features to old versions

**Comment by syswombat** [comment]
ok, i have done the update and works fine to me. Merci!
