### ISSUE TITLE
Feature Request: Loading UI - Tracing Menus

### ISSUE THREAD

**Issue by sethjones** [grafana/grafana#35523]
**What would you like to be added**:
When using the Tracing Explorer panel and opening the service or operation dropdown, a loading indicator to let users know that something is happening and they should wait.

**Why is this needed**:
The current implementation can result in users believing that there are not values available for selection, when there is an active query processing to build the values.  Users may close the menu before the response has been received and processed to fill in the values.

**Comment by aocenas** [comment]
Just to clarify, are you talking about jaeger data source search UI?
![Screenshot from 2021-06-14 13-43-17](https://user-images.githubusercontent.com/1014802/121887042-84727400-cd16-11eb-8756-37a90ac6b5b7.png)

**Comment by sethjones** [comment]
That is the panel yes.

**Comment by nicolastakashi** [comment]
I guess this already exists in the newer versions.

**Comment by aocenas** [comment]
This should be already implemented.
