### ISSUE TITLE
Failed to save rule: GetRuleGroup unsupported in rule local store

### ISSUE THREAD

**Issue by MTRNord** [grafana/grafana#35536]
**What happened**:
When adding a alert rule with Loki using the ngalert feature I am unable to save the alert rule using the default configs.

**What you expected to happen**:
Saving an alert rule should work with default configs.

**How to reproduce it (as minimally and precisely as possible)**:
Use the default local config for loki and try to make an alert in the new alert system using loki managed alerts.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.0 (41f0542c1e)
- Data source type & version: Loki & 2.2.1
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 10 & Firefox 89.0 (64-bit)
- Grafana plugins: Stock + Grafana Image Renderer

**Comment by MTRNord** [comment]
Hi itis the GET request on `[server]/api/ruler/5/api/v1/rules/[namespace]/[group]` failing with 400 Bad Request and the error in the title.

Default configs means following https://grafana.com/docs/loki/latest/installation/local/#install-and-run and also adding systemd logs to promtail in my case. So it is https://raw.githubusercontent.com/grafana/loki/master/cmd/loki/loki-local-config.yaml 

In terms of logs I dont see anything special. I guess there is a flag I can set to get debug logs? And if so which one would that be?


Current logs (be ware that stuff in [] is just redacted due to privacy reasons.):
```
Jun 11 10:45:37 [server] grafana-server[13101]: t=2021-06-11T10:45:37+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:45:37+0200
Jun 11 10:45:52 [server] grafana-server[13101]: t=2021-06-11T10:45:52+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:45:52+0200
Jun 11 10:46:07 [server] grafana-server[13101]: t=2021-06-11T10:46:07+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:46:07+0200
Jun 11 10:46:22 [server] grafana-server[13101]: t=2021-06-11T10:46:22+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:46:22+0200
Jun 11 10:46:37 [server] grafana-server[13101]: t=2021-06-11T10:46:37+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:46:37+0200
Jun 11 10:46:52 [server] grafana-server[13101]: t=2021-06-11T10:46:52+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:46:52+0200
Jun 11 10:47:07 [server] grafana-server[13101]: t=2021-06-11T10:47:07+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:47:07+0200
Jun 11 10:47:22 [server] grafana-server[13101]: t=2021-06-11T10:47:22+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:47:22+0200
Jun 11 10:47:37 [server] grafana-server[13101]: t=2021-06-11T10:47:37+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:47:37+0200
Jun 11 10:47:52 [server] grafana-server[13101]: t=2021-06-11T10:47:52+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:47:52+0200
Jun 11 10:48:07 [server] grafana-server[13101]: t=2021-06-11T10:48:07+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:48:07+0200
Jun 11 10:48:22 [server] grafana-server[13101]: t=2021-06-11T10:48:22+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:48:22+0200
Jun 11 10:48:30 [server] grafana-server[13101]: t=2021-06-11T10:48:30+0200 lvl=info msg="Request Completed" logger=context userId=1 orgId=2 uname=MTRNord method=GET path=/api/ruler/5/api/v1/rules/[namespace]/[group] status=400 remote_addr=2a02:8108:1200:6790:6d53:3fa6:8e1d:1c51 time_ms=19 size=85 referer=https://grafana.[server]/alerting/new
Jun 11 10:48:37 [server] grafana-server[13101]: t=2021-06-11T10:48:37+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:48:37+0200
Jun 11 10:48:52 [server] grafana-server[13101]: t=2021-06-11T10:48:52+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:48:52+0200
Jun 11 10:49:07 [server] grafana-server[13101]: t=2021-06-11T10:49:07+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:49:07+0200
Jun 11 10:49:22 [server] grafana-server[13101]: t=2021-06-11T10:49:22+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:49:22+0200
Jun 11 10:49:37 [server] grafana-server[13101]: t=2021-06-11T10:49:37+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:49:37+0200
Jun 11 10:49:52 [server] grafana-server[13101]: t=2021-06-11T10:49:52+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:49:52+0200
Jun 11 10:50:07 [server] grafana-server[13101]: t=2021-06-11T10:50:07+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:50:07+0200
Jun 11 10:50:22 [server] grafana-server[13101]: t=2021-06-11T10:50:22+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:50:22+0200
Jun 11 10:50:37 [server] grafana-server[13101]: t=2021-06-11T10:50:37+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:50:37+0200
Jun 11 10:50:52 [server] grafana-server[13101]: t=2021-06-11T10:50:52+0200 lvl=info msg="recording state cache metrics" logger=ngalert now=2021-06-11T10:50:52+0200
```

**Comment by justBjoern** [comment]
Hey,
I got the same problem. 

Shouldn't the GET request look like:
`GET /loki/api/v1/rules/{namespace}/{groupName}`
But mine also looks like the one from MTRNord:
`GET /api/ruler/3/api/v1/rules/{namespace}/{groupName}`



Reference:
https://grafana.com/docs/loki/latest/api/#get-rule-group

**Comment by brodyck** [comment]
I am having this issue as well.

On a quick search before I had to stop looking yesterday, the only context I can find for 'namespaces' is with grafana cloud.

Something probably important to note is that my Loki + promtail is on a remote machine.

**Comment by domasx2** [comment]
I think local rule store does not support the ruler API, so rules can't be edited via UI. Will test this and handle it better

**Comment by papagian** [comment]
> I think local rule store does not support the ruler API, so rules can't be edited via UI. Will test this and handle it better

Yes, this error is actually [returned](https://github.com/cortexproject/cortex/blob/b3c87d71b8ac45a87308657309ce666ee1ee4028/pkg/ruler/rules/local/local.go#L107) from the cortex API

**Comment by MTRNord** [comment]
> 
> 
> I think local rule store does not support the ruler API, so rules can't be edited via UI. Will test this and handle it better

Which brings me as a user to 2 follow up questions:

- Why is this the case?
- And how do I solve this without requiring to use [cloud provider]? Aka how to selfhost this efficiently without missing out on the feature?

**Comment by owen-d** [comment]
The short answer is that the local ruler backend which Loki inherits from Cortex was initially modeled on Prometheus’s file-based configuration and it seemed reasonable to disallow these files from being edited via API. However, I doubt this should necessarily be the case as the idea of where rules are stored and whether they're immutable are independent concepts. I think it would be reasonable to PR into Cortex allowing the local rule store to implement the ruler API.

**Comment by domasx2** [comment]
Similar issue, but for cortex https://github.com/grafana/grafana/issues/35977

**Comment by domasx2** [comment]
Hey!

Both Loki & Cortex do not support ruler api with local rule store. Added a note to docs and added better error messages for when this problem occurs. Don't think there's much else we can do about it on Grafana side. An easy workaround for using local fs is to run https://min.io/ , which provides S3-compatible api for locally stored files, and then configure cortex/loki to use S3 sorage pointing at it.

Closing this issue

**Comment by JasonYangX** [comment]
What are the reasons for not supporting it?
