### ISSUE TITLE
[Grafana v8.0.0] The panel loses data when changing their options

### ISSUE THREAD

**Issue by sergejmueller** [grafana/grafana#35532]
**What happened**:
The panel data goes invisible as soon as the panel options are changed.

**What you expected to happen**:
The panel data is still visible.

**How to reproduce it (as minimally and precisely as possible)**:
- Install a streaming data source plugin (e.g. [Streamr Data Source](https://github.com/grafana/grafana-plugin-repository/pull/935))
- Choose the plugin as panel data source
- Wait for panel data
- Change a panel setting

**Anything else we need to know?**:
- On my local machine I use Grafana v7.3.6 with the same Streamr Data Source version without problems.
- The developer console shows no javascript errors during the changing process.

**Environment**:
- Grafana version: Grafana v8.0.0 (41f0542c1e)
- Data source type & version: [Streamr Data Source](https://github.com/grafana/grafana-plugin-repository/pull/935) 1.5.0
- OS Grafana is installed on: Cloud
- User OS & Browser: Mac Chrome
- Grafana plugins: [Streamr Data Source](https://github.com/grafana/grafana-plugin-repository/pull/935)
- Others: None

**Attachment:**
![Bildschirmaufnahme-2021-06-10-um-20 09 24](https://user-images.githubusercontent.com/108992/121577690-12eea900-ca2a-11eb-92e2-571a153a105f.gif)

**Comment by zuchka** [comment]
@sergejmueller it looks like your Streamr datasource was both authored by you and is now archived. Have you encountered this using any other plugins? Ideally using only core features / official plugins inside grafana?

Going to close this for now but more than happy to reopen if you have more insights to share 👍
