### ISSUE TITLE
MySQL "order by DESC" Not Working in 

### ISSUE THREAD

**Issue by CrankyDataGuy** [grafana/grafana#35534]
**What happened**:
Values which were supposed to be displayed in the bar gauge in descending order are not in order.
**What you expected to happen**:
Values to be sorted from highest bandwidth usage at the top, in descending order
**How to reproduce it (as minimally and precisely as possible)**:
Create a MySQL table with several rows, with datetime in first column, names in 2nd column, and values in the 3rd column, and use "ORDER BY <value col> DESC". A copy of the query I am using is in the attached screenshot.
**Anything else we need to know?**:
This query and panel display worked fine in previous versions before 8.0
**Environment**:
- Grafana version: 8.0.1
- Data source type & version: MySQL ver 14.14, distrib 5.7.34
- OS Grafana is installed on: Ubuntu 
- User OS & Browser: Ubuntu 18.04.5 LTS
- Grafana plugins: Bar Gauge
- Others:
![Bar Panel Screenshot](https://user-images.githubusercontent.com/28568427/121584519-26cce780-c9f7-11eb-8062-61e03ea82e68.png)

**Comment by danielpereira-gub** [comment]
I have the same problem

**Comment by marefr** [comment]
@CrankyDataGuy can you please copy request/response via inspect -> query tab and include here. Thanks

**Comment by danielpereira-gub** [comment]
Hy, the problem also occurs with piechart




SELECT 1623724682 AS time,
UPPER(D.neighborhood) AS 'TIPO DE SOLICITAÇÃO', 
COUNT(A.id) AS 'QUANTIDADE DE SOLICITAÇÕES'

FROM assignments as A
INNER JOIN assignment_incidents AS B
ON A.id = B.assignment_id
INNER JOIN incident_types AS C 
ON B.incident_type_id = C.id
INNER JOIN people AS D 
ON B.client_id = D.id

WHERE DATE_FORMAT(A.created, "%d/%M/%Y") = '14/JUNE/2021' AND B.team_id = 3 AND B.incident_status_id <> 8

GROUP BY 2

ORDER BY COUNT(*) DESC

**Comment by CrankyDataGuy** [comment]
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "refId": "A",
          "datasourceId": 1,
          "rawSql": "SELECT\n  dt AS \"time\",\n  switchName,\n  lagCurrentBW AS \"lagCurrentBW\"\nFROM Grafana_5160_Statistics\nWHERE\n  $__timeFilter(dt)\nGROUP BY switchName\nORDER BY lagCurrentBW DESC\nLIMIT 10",
          "format": "time_series",
          "intervalMs": 60000,
          "maxDataPoints": 910
        }
      ],
      "range": {
        "from": "2021-06-15T12:57:00.499Z",
        "to": "2021-06-15T13:02:00.499Z",
        "raw": {
          "from": "now-5m",
          "to": "now"
        }
      },
      "from": "1623761820499",
      "to": "1623762120499"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "name": "results",
              "meta": {
                "executedQueryString": "SELECT\n  dt AS \"time\",\n  switchName,\n  lagCurrentBW AS \"lagCurrentBW\"\nFROM Grafana_5160_Statistics\nWHERE\n  dt BETWEEN FROM_UNIXTIME(1623761820) AND FROM_UNIXTIME(1623762120)\nGROUP BY switchName\nORDER BY lagCurrentBW DESC\nLIMIT 10"
              },
              "fields": [
                {
                  "name": "time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-ARDMOKXA_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-ATKAOKXA_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-BGPTOKXA_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-CES-POTEAU-5160-1"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-CES-RACK59-5160-1"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-CHCKOKXA_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-CLNTOK04_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-DRNTOKXA_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-DUCNOKXA_S21"
                  }
                },
                {
                  "name": "lagCurrentBW",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "switchName": "INNI-SLSWOKXA_S21"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1623744001000
                ],
                [
                  635475487
                ],
                [
                  379457130
                ],
                [
                  1050448275
                ],
                [
                  843500068
                ],
                [
                  2632692018
                ],
                [
                  303132761
                ],
                [
                  1491654923
                ],
                [
                  1622440991
                ],
                [
                  551493376
                ],
                [
                  955852970
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}

**Comment by marefr** [comment]
Thanks. Given the changes in the SQL data sources for Grafana v8.0 the format returned from Grafana backend is data frames and unfortunately requires some manual work from you to migrate these specific use cases.

I will make sure to add some [upgrade notes](https://grafana.com/docs/grafana/latest/installation/upgrading/#upgrading-to-v80) about this.

**The recommended way:**
Using a _Table_ query instead makes sense when you only need the time to filter on and it doesn't require any transformations. Example query and screenshot of results below:
```sql
SELECT
  avg(value) as value,
  hostname as metric
FROM 
  grafana_metric
WHERE
  $__timeFilter(createdAt)
GROUP BY 2
ORDER BY 1 desc
```

![Selection_999(354)](https://user-images.githubusercontent.com/1668778/122064422-72b1cf00-cdf1-11eb-8513-699c0aece9cc.png)
![Selection_999(353)](https://user-images.githubusercontent.com/1668778/122064426-734a6580-cdf1-11eb-8c5d-f5df478680dd.png)

**The somewhat more complicated way:**
Since you're using _Time series_ as format from Grafana v8.0.0 you'll need to use transformations to transform it into a ordered data set. Example using my _Time series_ query and screenshots below for transformations:
```sql
SELECT
  createdAt as time_sec,
  avg(value) as value,
  hostname as metric
FROM 
  grafana_metric
WHERE
  $__timeFilter(createdAt)
GROUP BY 3
ORDER BY 2 desc
```

![Selection_999(352)](https://user-images.githubusercontent.com/1668778/122064430-73e2fc00-cdf1-11eb-973c-40a59f2309ec.png)
![Selection_999(351)](https://user-images.githubusercontent.com/1668778/122064432-73e2fc00-cdf1-11eb-97ee-1ef94ff88741.png)

**Comment by torkelo** [comment]
since your only showing the last value I would change this to table query that return the LAST value in the SQL instead, and then configure the bar gauge show "All values" (instead of calculating and picking the latest)

**Comment by torkelo** [comment]
that way the order should be preserverd
