### ISSUE TITLE
Build: seems like branches started with `v` will be treated as a release branch by drone.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#35547]
**What happened**:
Comparing these tow PR:s I get different build pipelines in drone. Feels like we need to make sure that the release branches matches the version tag rather than just start with an `v`.

https://github.com/grafana/grafana/pull/35248 <-- running release pipeline (branch named: view-alert-rule-page)
https://github.com/grafana/grafana/pull/35546 <-- running test pipline (branch named:  mkcn/view-alert-rule-page)

**What you expected to happen**:
I was expecting the test-pr pipeline to run for my PR.

**How to reproduce it (as minimally and precisely as possible)**:
Open a PR based off a branch starting with `v`.

**Comment by mckn** [comment]
@aknuds1 do you know how I should label/triage this issue?

**Comment by aknuds1** [comment]
@mckn the issue is known and I made a PR to fix it, but my solution was rejected by the cloud platform team, so I have to find the time to think up a better approach.
