### ISSUE TITLE
Grafana 8 regression: Absolute links to own domain fail if behind reverse proxy

### ISSUE THREAD

**Issue by skladd** [grafana/grafana#35566]
**What happened**:
After updating to Grafana 8.0.0, absolute links to resources on same domain, but not under /grafana sub url, are leading to 404 errors:
On a Grafana installation under `https://example.org/grafana` a link to `https://example.org/other` is transformed to `https://example.org/grafana/other` or `https://example.org/grafana/https://example.org/other` leading to a 404 error.
Interestingly, the preview before clicking the link is still correct (`https://example.org/other`).

**What you expected to happen**:
Clicking the link should open the configured URL.

**How to reproduce it (as minimally and precisely as possible)**:
docker environment variables set:
```
GF_SERVER_ROOT_URL=/grafana/
GF_SERVER_SERVE_FROM_SUB_PATH=true
```
Add a dashboard link (type "Link") to same domain, but not under /grafana/.

**Anything else we need to know?**:
Opening in a new tab works correctly.

Seems to be similar to #33118, but now happens even with absolute URLs. 

**Environment**:
- Grafana version: 8.0.0, 8.0.1
- Behind apache reverse proxy, setting root_url

**Comment by torkelo** [comment]
GF_SERVER_ROOT_URL=/grafana/ 

does not look correct, GF_SERVER_ROOT_URL should be the full public url (you see in the browser, ie to your reverse proxy)

**Comment by torkelo** [comment]
Failed to replicate this, set:

GF_SERVER_ROOT_URL=http://localhost:3000/grafana
GF_SERVER_SERVE_FROM_SUB_PATH=true

then added a dashboard link to http://localhost:3000/other   and it stays http://localhost:3000/other

**Comment by skladd** [comment]
Right, it should be and is `GF_SERVER_ROOT_URL="https://example.org/grafana"`.
Nevertheless, the problem persists for me. It stopped working after upgrading to 8.0.0 in the Docker based setup as well as on "native" Debian installation without Docker.

**Comment by skladd** [comment]
Maybe introduced by #31463 (Routing: Replace Angular routing with react-router)?

**Comment by skladd** [comment]
@torkelo Could you reproduce the problem using the given example? Do you need more information?

**Comment by SuperAvarice** [comment]
I am also experiencing this issue. Went from v7.5.9 to v8.0.3 with docker containers.
I also use a nginx reverse proxy.

I only use GF_SERVER_ROOT_URL: "{{ grafana_root_url }}/grafana"
GF_SERVER_SERVE_FROM_SUB_PATH is NOT used, so defaults to "false".

Noticed this on the default home dashboards. I am using Markdown text.
The links that point to other domains work fine, the ones that point to the base url get the SERVER_ROOT_URL prepended.
The deploy is completely automated, only versions changed.

**Comment by SuperAvarice** [comment]
Still broken as of v8.0.4

**Comment by torkelo** [comment]
@skladd yes, was able to replicate it now. Fix PR is up
