### ISSUE TITLE
bug: shared crosshair does not scale the y axis correctly

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#35571]
**What happened**:

The shared crosshair does not scale the y axis correctly.

**What you expected to happen**:

The shared crosshair should be in-line with other graphs.

**How to reproduce it (as minimally and precisely as possible)**:

Create some time series graphs with different data and varying degrees of data. The crosshairs will not match up.

https://user-images.githubusercontent.com/9749173/121703173-76301800-caca-11eb-9883-1d73f3a16c20.mp4

**Anything else we need to know?**:

N/A

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: Time series (new)
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Windows 10 Pro (Chrome)
- Grafana plugins: N/A
- Others: N/A

**Comment by uhthomas** [comment]
Either they should be in-line with the source cross-hair in proportion to its position on the graph, or it should remain at the tip of the line. I don't remember what the previous behavior was.

**Comment by uhthomas** [comment]
Okay I just checked and the behavior of the old graph is my first suggestion; position relative to the original.

**Comment by leeoniya** [comment]
they are positioned by value along matching y scales, which looks correct to me in the screen rec above. i'm not sure it would make much sense to syn them by raw position %.

**Comment by uhthomas** [comment]
@leeoniya I would consider this as a regression as the old Graph visualization did it in a way that made sense, whereas the new behavior is not what I would have intuitively expected.

**Comment by uhthomas** [comment]
For brevity, here's a clip of the same data with the old Graph visualization.

https://user-images.githubusercontent.com/9749173/121704386-a2986400-cacb-11eb-8648-2ecc3d0d78f1.mp4

**Comment by uhthomas** [comment]
Worse yet, the shared tooltip disappears on the "Odomoter" the new Time Series visualization because it's so far out.

**Comment by leeoniya** [comment]
you're showing an interaction where you want to explicitly move the cursor on a non-hovered chart. the whole point of a shared cursor is that you can synchronize the same scale values along x and y, not so that you can reduce the effort to mousing over to the other chart. you still see the values at the synchronized x position in the tooltip (except i guess when it's in single mode and relies on y hover proximity), it's just that the y crosshair is now synchronized by scale, which was impossible before.

yes, it's a change in behavior, but as with everything a regression for one person is an enhancement for another person.

let's leave this issue open for a while to collect feedback, but the behavior you're seeing is by design, and not a bug.

**Comment by uhthomas** [comment]
I see your viewpoint and it makes sense, although it doesn't work in lots of situations. Imagine a graph showing the percentage (0-1) and a graph showing the actual amount. The crosshair doesn't lineup as the value is either way out of bounds (280 in a 0-1 graph), or anchored to 0. See:

https://user-images.githubusercontent.com/9749173/121716525-0a54ac00-cad8-11eb-90f7-bb2f1f173310.mp4

Additionally, not all visualizations on a dashboard will be visualizing the same thing.

Maybe it should be configurable? I'm not sure.

**Comment by leeoniya** [comment]
> I see your viewpoint and it makes sense, although it doesn't work in lots of situations.

agreed, there are certainly issues on both sides of this, choosing is hard :(

> Additionally, not all visualizations on a dashboard will be visualizing the same thing.
> Maybe it should be configurable? I'm not sure.

that's a general problem with a single, dashboard-level toggle. unless we provide very customizable config for groups of panels you want synchronized and how. it's unlikely there will be much appetite for offering an intricate config for this feature.

**Comment by leeoniya** [comment]
we will be removing y sync functionality entirely in our upcoming tooltip rewrite. both the previous and current behavior are unhelpful and 🤯 

the new tooltip in the synced panels will simply switch to "multi/all" mode and will be vertically centered within the panel.
