### ISSUE TITLE
Migration to ngalert fails on Grafana 8.0.1 (with MySQL backend database)

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#35583]
**What happened**:
- exported the environment variable to enable next generation alerts (export GF_FEATURE_TOGGLES_ENABLE=ngalert)
- Restarted the Grafana service (systemctl restart grafana-server)
- Service failed to restart and threw errors (see below)

**What you expected to happen**:
- Grafana to do alert migration and restart

**How to reproduce it (as minimally and precisely as possible)**:
- Grafana v8 instance with traditional alerts; mysql backend database
- enable ngalert and restart grafana service

**Anything else we need to know?**:
Relevant logs from journalctl:
```
Jun 11 09:49:42  grafana-server[2941322]: t=2021-06-11T09:49:42-0500 lvl=info msg="Starting DB migrations" logger=migrator
Jun 11 09:49:42  grafana-server[2941322]: t=2021-06-11T09:49:42-0500 lvl=info msg="Executing migration" logger=migrator id="move dashboard alerts to unified alerting"
Jun 11 09:49:45  grafana-server[2941322]: t=2021-06-11T09:49:45-0500 lvl=eror msg="Executing migration failed" logger=migrator id="move dashboard alerts to unified alerting" error="Error 1406: Data too long for>
Jun 11 09:49:45  grafana-server[2941322]: t=2021-06-11T09:49:45-0500 lvl=eror msg="Exec failed" logger=migrator error="Error 1406: Data too long for column 'alertmanager_configuration' at row 1" sql="code migra>
Jun 11 09:49:45  grafana-server[2941322]: service init failed: migration failed (id = move dashboard alerts to unified alerting): Error 1406: Data too long for column 'alertmanager_configuration' at row 1
Jun 11 09:49:45  systemd[1]: grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Jun 11 09:49:45  systemd[1]: grafana-server.service: Failed with result 'exit-code'.
```

This may have something in common with issue #22853 but I am not sure

**Environment**:
- Grafana version: 8.0.1
- Data source type & version: InfluxDB for metrics; MySQL backend for Grafana
- OS Grafana is installed on: CentOS 8 Stream
- User OS & Browser: All OS/Browsers
- Grafana plugins: None
- Others:

**Comment by zuchka** [comment]
Hi @jdmaloney,

Yes, looks very similar to https://github.com/grafana/grafana/issues/22853.

**Comment by kylebrandt** [comment]
I am thinking perhaps that the database type needs to be bigger. Currently we are using type `TEXT`, and I think we might want `MEDIUMTEXT` https://stackoverflow.com/a/6766854/107156 .

**Comment by jdmaloney** [comment]
@kylebrandt I can confirm.  I went ahead and modified that column type in the database manually and that allowed the migration to proceed as expected.
