### ISSUE TITLE
Feature Request: Time Series Legend - "Last (not null)" - hide or rename bc is too long (too many characters as heading)

### ISSUE THREAD

**Issue by bob454522** [grafana/grafana#35589]
**What would you like to be added**:  Ability to rename or shorten the column header "Last (not null)" as it appears in a legend-> table - Ideally we could simply remove the "(not null)" part such that it shows just "Last"  (see below please) -  another idea, is that it could be changed to "Last*"  with the * meaning = (not null) **

**Why is this needed**: its too long when its rendered in the actual graph , and thus takes up more space than is necessary:
ie:
![image](https://user-images.githubusercontent.com/60830628/121726472-3a885480-cab0-11eb-918f-3186fb8d53ce.png)

We almost always use "Last (not null)" as opposed to "Last" in our graphs' legend.   
_(btw- LOVE this new "Last (not null)" legend option added to the AWESOME new "time series" viz - grafana just never stops getting better)._

however as a column header,  the 15x characters in "Last (not null)"  is really too long to be a column header (especially when its part of a legend to a graph, which should be taking up as little space as possible, so that the graph itself can be the main focus).

**Ideally we could simply remove the "(not null)" part such that it shows just "Last"   (i realize there might be confusion with the standard "Last" which does include nulls,  however the confusion is < the utility of a more clean/clear legend , which takes up less space).**

thanks,
LOVE GRAFANA !!

-------

EDIT:  here is a pretty good example i came across just now,  i feel that having "(not null)" is not worth the extra width/pixels being used up by the legend.  (and frequently in our cases using the standard "Last"  does not give the output we are looking for):
(i duplicated this graph to test and upgrade to Time-Series visualization vs the "Graph (old)" viz - so below is the same graph/data

![image](https://user-images.githubusercontent.com/60830628/121727964-3e1cdb00-cab2-11eb-9c7a-b9ed92b17ff0.png)

**Comment by hugohaggmark** [comment]
@dprokop @leeoniya this seems like a reasonable feature request?

**Comment by erkexzcx** [comment]
I think option to rename it or customize title would be great.

E.g. I want to save space and have very short titles. Like instead of `Last` I would like to use `Cur`. Instead of `Mean` I would like to use `Avg` and so on.

**Comment by GregoryOrciuch** [comment]
Hi, I came across this issue while transforming from Graph(old) to new Timeseries.
It looks like Last (not null) is too long indeed, but I'm missing the option to rename it to whatever value and this seem not possible.
Please consider making an option to rename those  in the 'Override fields' menu.

Thanks for your hard work!

**Comment by torkelo** [comment]
have PR up https://github.com/grafana/grafana/pull/35633

**Comment by GregoryOrciuch** [comment]
cool but that PR looks like a just name change, right? not a possibility to edit it

**Comment by torkelo** [comment]
@GregoryOrciuch no that won't be possible, will complicate the UI too much, but if there is big demand for that and we find a good way to do it in the UI that does not just add another option then it could work

**Comment by Numex106** [comment]
Looking for this also. I use the legend at the bottom and not to the right as OP does. The old graph used "current" which was nice and short "Last (not null)" takes up a lot of space when using the legend at the bottom. I suspect more people will use last(not null) as opposed to last. A way to edit the names would be nice, but switching it around might be easy. Last and Last (incl. null) something like that?
