### ISSUE TITLE
Feature Request - Setting Max values on template selection with Mutiple Selection enabled

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3558]
Hi,

Today someone used our huge dashboard which SO metrics are shown with multiple selection enabled on each templating params (there are 5 templating fields). On the logs, some panels made more than 3000 matches and it crashed whole graphite.

There would be awesome if you could set a maximum number on templating selection, which it wouldn't allow the user select more than it at once.

I.E: Setting max to 2:

![mockup2](https://cloud.githubusercontent.com/assets/13196237/11893169/a927ac32-a56e-11e5-881b-559b9805f41a.png)

Thanks for all.

**Comment by torkelo** [comment]
you can disable the ALL option, seems good enough, it would be a pain to manually select 3000 values
