### ISSUE TITLE
Feature Request: Support "True Color" escape sequences in loki logs

### ISSUE THREAD

**Issue by nevans** [grafana/grafana#35588]
**24-bit "direct" RGB colors in logfiles**

Sometimes logfiles use 24bit RGB color escape sequences to distinguish between e.g. different email addresses using a checksum or for other reasons. Supporting the entire RGB color space would be useful.

The escape sequences used by almost all terminals with 24-bit RGB support are:

`ESC[ 38;2;⟨r⟩;⟨g⟩;⟨b⟩ m` => Select RGB foreground color
`ESC[ 48;2;⟨r⟩;⟨g⟩;⟨b⟩ m` => Select RGB background color

Perhaps I should also open an issue on the `ansicolors` npm package? At a very quick glance, I wasn't certain if adding 24bit RGB color support there would be API compatible or would require an update to grafana.

**Comment by zuchka** [comment]
somewhat related to [this ANSI logs issue](https://github.com/grafana/grafana/issues/22853)

**Comment by davkal** [comment]
@nevans we could use some help on this, could you verify if ansicolor supports this?

**Comment by nevans** [comment]
Sorry I lost track of this.  No, it doesn't look like it does.  I posted an issue here: https://github.com/xpl/ansicolor/issues/17

**Comment by joey-grafana** [comment]
Closing this as it's an issue in an external repo - and we have posted to that repo.
