### ISSUE TITLE
Rendered templated graphs with query based template variables shows wrong data

### ISSUE THREAD

**Issue by doganyazar** [grafana/grafana#3559]
Channel is a template variable and it has several values: ch1, ch2, ch3
Dashboard shows the graphs perfectly fine when I change channels on dropbox but when I get a share link such as the one below (including query based template variables),
it renders graphs for other channels sometimes (i.e. bring the graph for ch1 instead of ch2). It looks like a caching issue on the server side since refreshing the link brings different results.

"/dashboard/db/mydasboard?panelId=1&fullscreen&from=1450440522857&to=1450444122858&var-server=dc1&var-channel=ch2"

**Comment by torkelo** [comment]
what version of grafana do you have? Do you have any other variables in the dashboard?

**Comment by doganyazar** [comment]
Version 2.5.0
Yes I have 3 template variables in total in the same dashboard.

**Comment by torkelo** [comment]
try upgrading to 2.6, think something like this has been fixed.

**Comment by doganyazar** [comment]
Will try! Thanks for the response.

**Comment by doganyazar** [comment]
This looks like fixed! I want to try it a bit more and if it is all fine we can close this next week. 
Thanks again.
