### ISSUE TITLE
$__timeGroupAlias(timestamp, $__interval) resolving to month instead of minute in case of 'interval=1m'

### ISSUE THREAD

**Issue by simon-verzijl** [grafana/grafana#35593]
**What happened**:

When using $__timeGroupAlias(timestamp, $__interval) in a Bigquery query, whenever the interval is '1m', it gets translated to 1 month instead of 1 minute in the generated Bigquery : 
SELECT
  TIMESTAMP(  (PARSE_DATE( "%Y-%m-%d",CONCAT( CAST((EXTRACT(YEAR FROM `timestamp`)) AS STRING),'-',CAST((EXTRACT(MONTH FROM `timestamp`)) AS STRING),'-','01')))) AS time, 

When using $__timeGroupAlias(timestamp, 1min) it is translated to the expected query : 
SELECT
  TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`timestamp`), 60) * 60) AS time, 

**What you expected to happen**:
When $__interval=1m I expect the generated query to be:
SELECT
  TIMESTAMP_SECONDS(DIV(UNIX_SECONDS(`timestamp`), 60) * 60) AS time, 

**How to reproduce it (as minimally and precisely as possible)**:
Freshly installed Grafana 8.0.1 with only Google BigQuery plugin. Connect to a BQ dataset and enter below query : 

SELECT
  $__timeGroupAlias(timestamp, $__interval),  
FROM `project.bqdataset.table`
WHERE
  $__timeFilter(timestamp)

**Anything else we need to know?**:
I'm not sure if this issue is on Grafana side or at the plugin side. Was not able to test same with other plugins yet.

**Environment**:
- Grafana version: 8.0.1 (but same happening in 7.5.5)
- Data source type & version: Google BigQuery (https://github.com/doitintl/bigquery-grafana) 2.0.2
- OS Grafana is installed on: Google GKE
- User OS & Browser: MacOS 11.2.3 / Chrome 91.0.4472.77
- Grafana plugins: Google BigQuery 2.0.2
- Others: -

**Comment by torkelo** [comment]
Please report this to the https://github.com/doitintl/bigquery-grafana repo as this looks like a plugin issue
