### ISSUE TITLE
State timeline does not respect transparency

### ISSUE THREAD

**Issue by pkoenig10** [grafana/grafana#35606]
**What happened**:
I changed the color on a state timeline panel to one with some amount of transparency. The alpha component of the color was ignored and the color was displayed without any transparency (100% alpha).

**What you expected to happen**:
The alpha component of the color to be respected and the color to appear transparent.

This does seems to work correctly on all other panels I tested, so I think the issue is limited to the state timeline panel.

See the following screen recording for a demonstration: [screen_recording.zip](https://github.com/grafana/grafana/files/6645820/screen_recording.zip)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a state timeline panel.
2. Change the color to one with some amount of transparency (using any one of the multiple methods to select a color) .

**Environment**:
- Grafana version: v8.0.1
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on: The official Docker image (https://hub.docker.com/r/grafana/grafana) in Docker version 20.10.6 build 370c289 on Ubuntu 20.04.2 LTS
- User OS & Browser: MacOS 10.15.7 & Chrome
- Grafana plugins: None

**Comment by torkelo** [comment]
It's best to set opacity with the state timeline opacity slider, that way you can get consistent opacity for all colors. 

But we should detect if there is an opacity in the color and use that instead

**Comment by pkoenig10** [comment]
I specifically wanted opacity for some colors but not all colors. To effectively not show any "normal" values an only show "abnormal" values.

For example, I wanted the green sections of the timeline to be transparent and the red part to be opaque.
