### ISSUE TITLE
Template to render a single alert

### ISSUE THREAD

**Issue by Anzic23** [grafana/grafana#35604]
**What happened**:
I'm trying to create a rule for sending alarms to Telegram. I took the template from the documentation:
```
{{ define "message" }}
  {{ if gt (len .Alerts.Firing) 0 }}
    {{ len .Alerts.Firing }} firing:
    {{ range .Alerts.Firing }} {{ template "alert" .}} {{ end }}
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}
    {{ len .Alerts.Resolved }} resolved:
    {{ range .Alerts.Resolved }} {{ template "alert" .}} {{ end }}
  {{ end }}
{{ end }}
```
The template name is the same as define "message".  If I understand correctly, the message is generated from a example of a template to render a single alert:
```
{{ define "alert" }}
  [{{.Status}}] {{ .Labels.alertname }}
  
  Labels:
  {{ range .Labels.SortedPairs }}
    {{ .Name }}: {{ .Value }}
  {{ end }}
  
  {{ if gt (len .Annotations) 0 }}
  Annotations:
  {{ range .Annotations.SortedPairs }}
    {{ .Name }}: {{ .Value }}
  {{ end }}
  {{ end }}

  {{ if gt (len .SilenceURL ) 0 }}
    Silence alert: {{ .SilenceURL }}
  {{ end }}
  {{ if gt (len .DashboardURL ) 0 }}
    Go to dashboard: {{ .Dashboard URL }}
  {{ end }}
{{ end }}
```
By the way, it looks like the template has an error in the line "Go to dashboard: {{ .**Dashboard URL** }}", I think it should be like this "Go to dashboard: {{ .**DashboardURL** }}"
But no matter how I substitute the values, the "standard" message always comes.
**What you expected to happen**:
ability to edit the default template.
my temple:
```
{{ define "alert" }}
  [{{.Status}}] {{ .Labels.alertname }}
  
  лейбл:
  {{ range .Labels.SortedPairs }}
    {{ .Name }}: {{ .Value }}
  {{ end }}
  
  {{ if gt (len .Annotations) 0 }}
  Annotations:
  {{ range .Annotations.SortedPairs }}
    {{ .Name }}: {{ .Value }}
  {{ end }}
  {{ end }}

  {{ if gt (len .SilenceURL ) 0 }}
    Silence alert: {{ .SilenceURL }}
  {{ end }}
  {{ if gt (len .DashboardURL ) 0 }}
    Go to dashboard: {{ .DashboardURL }}
  {{ end }}
{{ end }}
{{ define "message" }}
  {{ if gt (len .Alerts.Firing) 0 }}
    {{ len .Alerts.Firing }} firing:
    {{ range .Alerts.Firing }} {{ template "alert" .}} {{ end }}
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}
    {{ len .Alerts.Resolved }} resolved:
    {{ range .Alerts.Resolved }} {{ template "alert" .}} {{ end }}
  {{ end }}
{{ end }}
```
**How to reproduce it (as minimally and precisely as possible)**:
Create alert rule, create a template.

**Environment**:
- Grafana version: v8.0.1 (8849243d27)
- Data source type & version: Prometheus
- OS Grafana is installed on: docker
![image](https://user-images.githubusercontent.com/37106885/121822955-c4037680-ccaa-11eb-871e-cb00f10fa50a.png)

**Comment by codesome** [comment]
@Anzic23 could you give few more details on how you tried to override the message?

I was able to override the message with these 2 steps
1. Create 2 templates with name "alert" and "message" with the content in this issue description (and yes, it should be `DashboardURL` and not `Dashboard URL`)
2. In the optional telegram settings, under message field, put `{{ template "message" . }}`

**Comment by Anzic23** [comment]
Now I understand, I need to create TWO DIFFERENT templates. This is closer to what I need. But still, it still doesn't work as I need it. For some reason, this message is returned:
```
1 resolved:
     
  [resolved] Мониторинг объектов
  
    Временно выключить оповещения: https://grafana.xxxxxxx.ru/alerting/silence/new?alertmanager=grafana&matchers=alertname%3D%D0%9C%D0%BE%D0%BD%D0%B8%D1%82%D0%BE%D1%80%D0%B8%D0%BD%D0%B3+%D0%BE%D0%B1%D1%8A%D0%B5%D0%BA%D1%82%D0%BE%D0%B2
```
And the link to the dashboard does not come
My TWO templates are:
1- alert
```
{{ define "alert" }}
  [{{.Status}}] {{ .Labels.alertname }}
  {{ if gt (len .SilenceURL ) 0 }}
    Временно выключить оповещения: {{ .SilenceURL }}
  {{ end }}
  {{ if gt (len .DashboardURL ) 0 }}
    Go to dashboard: {{ .DashboardURL }}
  {{ end }}
{{ end }}
```
2 - message
```
{{ define "message" }}
  {{ if gt (len .Alerts.Firing) 0 }}
    {{ len .Alerts.Firing }} firing:
    {{ range .Alerts.Firing }} {{ template "alert" .}} {{ end }}
  {{ end }}
  {{ if gt (len .Alerts.Resolved) 0 }}
    {{ len .Alerts.Resolved }} resolved:
    {{ range .Alerts.Resolved }} {{ template "alert" .}} {{ end }}
  {{ end }}
{{ end }}
```

**Comment by Anzic23** [comment]
My rule was created in alert rules. There is no alerts tab in the dashboard. Can you tell me what the template should look like if I need to get the name of the service that triggered the trigger and the link to the panel?
![image](https://user-images.githubusercontent.com/37106885/121907753-05406880-cd35-11eb-9dc9-563e5a58bbbd.png)
![image](https://user-images.githubusercontent.com/37106885/121908002-40429c00-cd35-11eb-8f69-4c90eebab502.png)

**Comment by codesome** [comment]
Alert rules created on the alerts page is not linked to any dashboard because you manually add a query there.

You have alert tab while editing a *panel* inside a dashboard. Rules created via this will have the dashboard URL in the alerts.

As for name of service, you can template the labels and annotations in the rules to extract info from the query results (see about `$labels.xyz` [here](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/), can also access rule labels via this), but for Grafana managed alerts, multi dimensional query results are not supported like in Prometheus, so you will have the query results in the annotations.

I am closing this issue now since I don't think there is any bug here.
