### ISSUE TITLE
Add non negative option to Elasticsearch derivative aggregation 

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#3561]
Because some counters reset when rebooting, a derivative graph can look quite odd. Graphite has a non negative derivative option which Elasticsearch unfortunately does not (yet) have.

Is it possible to filter out negative values on the client side? When Elasticsearch supports the non negative derivative option natively, Grafana could use that option instead of the client side filtering. I have also created an issue for Elasticsearch: https://github.com/elastic/elasticsearch/issues/15542

**Comment by torkelo** [comment]
would prefer to no add work arounds in Grafana for limitations in the time series stores. For this to implemented properly Grafana will need some generic metric transformation functions (applicable to all data sources), this will likely be added some time this year.

**Comment by felixbarny** [comment]
Sounds like a good idea. Is there an issue for that which I can watch?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3677
