### ISSUE TITLE
New "Time Series panel" wastes more space than the old one

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#35629]
**What would you like to be added**:

New "Time Series Panel' wastes more space and therefore not fully compatible with the old one. When I migrated old one to the new one, I had to increase their size as they become almost unreadable..

See this picture - red color points out where space is wasted:
![image](https://user-images.githubusercontent.com/5955795/121881955-9523e980-cd18-11eb-8cf9-ae8c7d9529a3.png)

**Why is this needed**:

In order to make new panel fully compatible with the old one and in order to save space.

**Comment by torkelo** [comment]
thanks for reporting this, opened a PR that reduces the ticks a bit
