### ISSUE TITLE
Timeseries : Auto Min Max for y-scale does not work when NaN are present

### ISSUE THREAD

**Issue by wweijtje** [grafana/grafana#35634]
In timeseries panel the y-axis doesn't scale (Min and Max both in Auto) properly when there are NaN in the query. As a result the entire plot disappears along with the y-axis.  The timeseries only becomes visible when the yscale is set to fixed limits (Note in the legend the mean value is NaN as well) . 

![image](https://user-images.githubusercontent.com/85878088/121886375-9869a600-cd15-11eb-9595-40214aa31f79.png)

When changing the period, to have no NaN values it works just fine : 
![image](https://user-images.githubusercontent.com/85878088/121886478-b8996500-cd15-11eb-89b8-9e69f283e1c3.png)

I would expect to scaling to ignore NaN values and scale accordingly. 

- Grafana version: Grafana v8.0.1 (8849243d27)
- Data source type & version: Postgresql 
- OS Grafana is installed on: Windows
- User OS & Browser: Windows, Chrome
- Grafana plugins: timeseries panel

**Comment by torkelo** [comment]
could it be caused by https://github.com/grafana/grafana/issues/35634 ?

**Comment by torkelo** [comment]
Sorry wrong issue
