### ISSUE TITLE
Prevent unlimited user acess to data source where not necessary

### ISSUE THREAD

**Issue by PhilippWendler** [grafana/grafana#3563]
Currently, every user (including role `Viewer`) seems to be able to access the full content of the data source via the `/api/datasources/proxy/` URL. There is no way to restrict which data a user can see.

We have some users that should only be allowed to view the data that is shown in a few predefined dash boards. These should not have access to any other data that is present in the same graphite instance.

I think this could be implemented by delivering an access token together with the dash board that specifies which data the user is allowed to request via the `render` API. Then the latter would not even have to check the permissions of the user, just that the supplied token matches the requested data.

**Comment by torkelo** [comment]
This would involve parsing all the dashboards that the user has access to and validate all the queries exist in any of those dashboards. This is impossible giving wildcard queries and templated dashboards. 

Graphite has no per metric access permission / feature. What you are talking about requires a feature in Graphite.

**Comment by PhilippWendler** [comment]
I do not think this involves parsing all dashboards on every request, and it could be done purely in Grafana.

What I propose is the following: when the user loads the dashboard, there is a list of queries contained. Now, for each query a token gets added to the dashboard that allows this user access to this query. When the query is made, the client has to present this query-specific token, and Grafana can validate the token before forwarding the query to graphite. Validating the query token could even be done without storing all such tokens on the server if the token is something like a cryptographically signed form of (timestamp, user, query).

**Comment by toni-moreno** [comment]
Hi  we are currently working on adding metric filtering per user/group to graphite.

(https://github.com/graphite-project/graphite-web/pull/1435)

After this work done grafana admins will be able  to define datasources with metric restrictions by only add user/autentication (and previously configured in graphite of course).

Any suggestion will be welcomed

**Comment by PhilippWendler** [comment]
Thanks for the link @toni-moreno that looks interesting and would probably also suit our usecase.
