### ISSUE TITLE
iframe reloading

### ISSUE THREAD

**Issue by erdemcer** [grafana/grafana#35631]
I have a simple vue js application which has iframe contains Grafana panel or dashboard. When url changed of panel or dashboard all iframe is reloaded again . I have tested this issue with Kibana , it has worked as expected not loading all iframe . 
is there any way update only panel data without reloading all iframe ?

[https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/f/f611168eeea8a800f67adf4bfdb3ed3f05165d16.gif](url)

Thanks

**Comment by torkelo** [comment]
How are you changing iframe url?

**Comment by erdemcer** [comment]
Hi,
Every time button or link is called , new  url of dashboard or panel is passed to iframe src. 
Thanks

**Comment by torkelo** [comment]
how passed? change url of the iframe?

**Comment by erdemcer** [comment]
I have added code . And you can find gif showing that the issue .

Gif shows that , “Refresh iframe” button changes src attribute of iframe with updated URL of grafana panel. 

```
<body>
  <input v-model="unitSelectedValue">
  <button v-on:click="getLink">Refresh Iframe</button>
  <div id="frame2div"><iframe id="frame2" ref="iframeRef" width="800" height="300" :src=linkgrafana sandbox="allow-same-origin allow-scripts allow-forms"></iframe></div>
</body>


new Vue({
    el:"#app",
    data:{
        unitSelectedValue:'0000',
        linkgrafana:'',
    },
    methods: {           
        getLink(){
            linkgrafana = 'http://localhost:3004/d-solo/0DorbSg7k/testdash2-copy?orgId=1&var-unitid='+this.unitSelectedValue+'&from=1623663179722&to=1623666779722'
            this.linkgrafana = linkgrafana
        }
    },
})
```

![](https://aws1.discourse-cdn.com/standard14/uploads/grafana/original/2X/f/f611168eeea8a800f67adf4bfdb3ed3f05165d16.gif)

**Comment by erdemcer** [comment]
Hi,
is there any update ?
Thanks

**Comment by joshhunt** [comment]
Finally dig a bit of digging into this. It's standard browser behaviour to do a full page load when changing the `src` attribute on an iFrame. I'm not sure what Kibana is doing to work around this (if anything at all), and there are some hack we could do to try and detect this, but it would be unreliable and only work in certain situations.

If your iFrame is on the same origin as Grafana, you may be able to access [`iframeEl.contentWindow`](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/contentWindow) and use `history.push`/`replaceState` to hook into Grafana's router, but I have not tested it and cannot vouch for its reliability.
