### ISSUE TITLE
New "Time series panel" legend isn't as good as the old one

### ISSUE THREAD

**Issue by erkexzcx** [grafana/grafana#35630]
**What would you like to be added**:

New "Time series panel" contains titles of the functions rather than human-readable titles. It either needs option to rename them, or it should be renamed from the Grafana side for good.

See this picture for comparison - how much space it wastes and how not-human-friendly it looks:
![image](https://user-images.githubusercontent.com/5955795/121882585-6b1ef700-cd19-11eb-8afe-10cc67a0301e.png)

**Why is this needed**:

In order to save space and make more human-friendly titles.

**Comment by torkelo** [comment]
in what way are they not human-friendly?

**Comment by torkelo** [comment]
We can reduce font size of table headings, so they match old legend. (will open PR shortly) 

The Last (not null) is more clear and understandable but is a bit too long. We have an issue for that one: https://github.com/grafana/grafana/issues/35589
