### ISSUE TITLE
AzureMonitor: Add error handling to ResourcePicker

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#35643]
**What would you like to be added**:

Catch HTTP errors in the resource picker when:
 - fetching initial data
 - fetching resources in resource groups

and display the error in the UI consistent with the rest of the data source.

**Comment by vickyyyyyyy** [comment]
we will check if this is already done or not

**Comment by sunker** [comment]
> we will check if this is already done or not

It was not :(
