### ISSUE TITLE
Feature Request - Tooltip content customization

### ISSUE THREAD

**Issue by mojchal** [grafana/grafana#3564]
Hello,

in series tooltip, in addition to point value, I would like to display also value of tag(s).

Thanks!

**Comment by torkelo** [comment]
you can do this, but you have to include the tag value in the series name.

**Comment by mojchal** [comment]
Sorry, I meant I need to display additional **fields** values in the tooltip.

**Comment by torkelo** [comment]
For that to work you need to select the field in your metric query (and add it to the series name)
