### ISSUE TITLE
Annotation string sanitization

### ISSUE THREAD

**Issue by volter** [grafana/grafana#3565]
Version 2.6

Sanitization fails for annotation messages with angled brackets. The newline is interpreted in a message like "hello\n\n<new line>", but "Could not sanitize annotation string, html escaping instead" is spit out on the console. This is in contrast to using annotations in the table panel, where the new-lines are not interpreted and the angled brackets are removed.

I'd love to have new-lines supported somehow.

**Comment by torkelo** [comment]
annotation text with html is not supported, `\n` in the annotation text is working as it should. Seems like the table panel is not sanitizing content correctly.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3673
