### ISSUE TITLE
AzureMonitor: Resource picker recently used 

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#35655]
**What would you like to be added**:

Resource picker should show a tab(?) with recently selected resources (and resource groups) that have been queried with.

It should share "recently used" across multiple panels (it should not just be recently used in that one panel, that wouldnt have that much value.)

Unsure where to store the list of recently used - probably just local storage?

**Comment by vickyyyyyyy** [comment]
This is a feature request that we can't see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
