### ISSUE TITLE
2.6.0/Elasticsearch ds/version not exported in json

### ISSUE THREAD

**Issue by SLoeuillet** [grafana/grafana#3566]
I tried to populate datasources via JSON+http API.
Exporting existing DS created via web ui, there is no 'version' exported in JSON output.

I tried to add version, esVersion, es-version with 2/"2.x" but no luck for now

**Comment by torkelo** [comment]
It is for me, when I request http://play.grafana.org/api/datasources/25

![image](https://cloud.githubusercontent.com/assets/10999/11912444/f1413780-a63c-11e5-81e5-5e9eb2221ead.png)
