### ISSUE TITLE
Docs: Document Grafana Managed data source feature support 

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#35666]
**What would you like to be added**:
A documentation page with Alerting that lists data sources that should work with Grafana managed alerting. 

In particular, if the data source supports:
 - Numeric Responses (a.k.a Single Stat / Vector / Non-Timeseries)
 - Multi-dimensional alerting based on Labels

So I imagine it will be a table in alerting docs.

**Why is this needed**:
Clear up confusion about what data sources can do what things with Grafana Managed Alerts in unified alerting.

**Comment by kylebrandt** [comment]
Note: Technically this is SSE (Server Side Expressions). As that is what takes in data and shapes the data frames into what alerting evaluation expects.

**Comment by achatterjee-grafana** [comment]
Hi @kylebrandt, can we close the issue?

**Comment by armandgrillet** [comment]
I don't think this has been documented yet. A new datasources page in https://grafana.com/docs/grafana/next/alerting/unified-alerting/ would be necessary.

**Comment by brendamuir** [comment]
Created here: https://grafana.com/docs/grafana/latest/alerting/fundamentals/data-source-alerting/
