### ISSUE TITLE
Docs feedback: /sharing/_index.md  - anonymous access no longer allowed in HG

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#35678]
Doc to modiy: 
https://grafana.com/docs/grafana/latest/sharing/

"To enable anonymous access on a Grafana Cloud instance, contact your Customer Support."

Anonymous access to HOSTED Grafana is no longer allowed

Ref Slack thread:
https://raintank-corp.slack.com/archives/CVD7EPRAN/p1621323211000100?thread_ts=1620736246.109900&cid=CVD7EPRAN

Pls change as customers are getting confused. 
Ref  https://grafana.zendesk.com/agent/tickets/28530

Thanks!

**Comment by pkolyvas** [comment]
@mlewald PR'ed. Feel free to suggest additional changes.

**Comment by achatterjee-grafana** [comment]
Fixed.
