### ISSUE TITLE
add kerberos support for postgresql

### ISSUE THREAD

**Issue by ktdreyer** [grafana/grafana#35677]
**What would you like to be added**:
My organization has a PostgreSQL database that I want to query with Grafana. This PostgreSQL database uses Kerberos authentication instead of the usual username/password authentication mechanism.

**Why is this needed**:
Some enterprise databases use Kerberos for authentication, and it would be great to support Kerberos instead of a simple username/password authentication.

**Comment by codeincarnate** [comment]
This has been open for a couple of years but doesn't seem to be a highly requested feature at this point. That being the case I'm going to close it for now. If there's any others that have the need for this please comment here and we can revisit if that's the case! 😄
