### ISSUE TITLE
Cannot use unsigned plugins even if Grafana is configured to do so

### ISSUE THREAD

**Issue by Watermeloune** [grafana/grafana#35670]
**What happened**:

I'm currently testing grafana 8's features but unsigned plugins are unusable. I went into the configuration file and set "allow_loading_unsigned_plugins" to true but it doesn't seem to work even though I can see in the admin tab that the configuration is there.

https://i.ibb.co/R71PhDN/allow-unsigned.png

**What you expected to happen**:
I expect that Grafana let me use unsigned plugins If I configure it to do so.

**Environment**:
- Grafana version: 8.0.2
- OS Grafana is installed on: Linux Gentoo 5.4.72
- User OS & Browser: Linux Gentoo 5.4.72 - Firefox

Thanks!

**Comment by serramatutu** [comment]
I can work on this issue if it's approved

**Comment by serramatutu** [comment]
@Watermeloune just so you know, the docs were updated and now you're required to add a list of trusted plugins.

![image](https://user-images.githubusercontent.com/18057473/121928176-48d7aa00-cd16-11eb-8d64-434874f175b0.png)

https://grafana.com/docs/grafana/latest/administration/configuration/#allow_loading_unsigned_plugins

**Comment by marefr** [comment]
Have always been and should be a comma-separated list of plugin identifiers. 

Regarding environment variables you forgot the [plugins] section. Please use `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS`. Please read the [documentation](https://grafana.com/docs/grafana/latest/administration/configuration/#configure-with-environment-variables) for reference.

**Comment by serramatutu** [comment]
This still doesn't work and there was definitely a behavior change. The configuration above used to work on 7.x.

I'm using the env var `GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=<my-plugin>` as you suggested. Grafana even logs that there was a configuration override:

![image](https://user-images.githubusercontent.com/18057473/121931511-1760dd80-cd1a-11eb-8e12-0e8d36cf9535.png)

But it still raises an error

![image](https://user-images.githubusercontent.com/18057473/121931542-26e02680-cd1a-11eb-84be-72e5459e2899.png)

I'm following all steps in the documentation for configuring it with env vars: capitalize letters and prepend `GF_PLUGINS_`.

**Comment by marefr** [comment]
Given, "has a modified signature" it sounds to me like you have a MANIFEST.txt for your plugin that doesn't correlate with the latest changes/state of your plugin. More information here, https://grafana.com/docs/grafana/latest/plugins/plugin-signatures/#plugin-signatures, the setting in question is only applicable if the loaded plugin signature is `Unsigned`.

**Comment by serramatutu** [comment]
Thanks! That solved the problem. I think the documentation can be improved though:

![image](https://user-images.githubusercontent.com/18057473/121933338-5728c480-cd1c-11eb-8908-162363a5c99e.png)

"even if they lack a valid signature" led me to believe it would allow modified signatures as well.

**Comment by Watermeloune** [comment]
Well sorry for this useless issue, I was so tired yesterday I didn't even think about reading the comment.

It's just a detail but wouldn't it be better to rename this parameter "allowed_unsigned_plugins" or something like that? Because the current name may lead to think it is a boolean

**Comment by marefr** [comment]
> It's just a detail but wouldn't it be better to rename this parameter "allowed_unsigned_plugins" or something like that? Because the current name may lead to think it is a boolean

Yes maybe, but need to handle that change to be backward compatible. So far we haven't got a lot of feedback on this why we currently not are planning to change this, but might change in the future.
