### ISSUE TITLE
ngalert migration error.

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#35686]
grafana 8.0.2
attempted to enable ngalert but migration failed.

```
Jun 14 18:41:31 grafana-p01.math grafana-server[19489]: t=2021-06-14T18:41:31-0400 lvl=eror msg="Executing migration failed" logger=migrator id="move dashboard alerts to unified alerting" error="failed to migrate alert 44: dashboard with UID  under organisation 3 not found: %!w(<nil>)"
Jun 14 18:41:31 grafana-p01.math grafana-server[19489]: t=2021-06-14T18:41:31-0400 lvl=eror msg="Exec failed" logger=migrator error="failed to migrate alert 44: dashboard with UID  under organisation 3 not found: %!w(<nil>)" sql="code migration"
Jun 14 18:41:31 grafana-p01.math grafana-server[19489]: service init failed: migration failed (id = move dashboard alerts to unified alerting): failed to migrate alert 44: dashboard with UID  under organisation 3 not found: %!w(<nil>)
```

I'm likely going to jump into the database and do some manual hacky things to get through this failed step.

**Comment by steverweber** [comment]
I assume since I was an early adopter of grafana my database has some odd artifacts

after a few deletes and retries to restart the grafana service
```
postgresql..
delete from alert where id=44 and org_id=3;
delete from alert where id=43 and org_id=3;
delete from alert where id=25 and org_id=6;
delete from alert where id=42 and org_id=3;
```

now grafana service gives error:
```
t=2021-06-14T19:31:47-0400 lvl=info msg="Executing migration" logger=migrator id="move dashboard alerts to unified alerting"
t=2021-06-14T19:31:47-0400 lvl=eror msg="Executing migration failed" logger=migrator id="move dashboard alerts to unified alerting" error="pq: current transaction is aborted, commands ignored until end of transaction block"
t=2021-06-14T19:31:47-0400 lvl=eror msg="Exec failed" logger=migrator error="pq: current transaction is aborted, commands ignored until end of transaction block" sql="code migration"
```

not much hint what the sql error is that is failing in the transaction.

At this point I like to note that my org table only has one org so perhaps the alert migration script can be set to only migrate alerts that have an org in the org table.

```
found a few extra records to delete
delete from alert where not org_id=1;
```

still no good. So used the err string in the log to find the code.
```
pkg/services/sqlstore/migrations/ualert/ualert.go
```
.. not in the mood anymore.
so, shrug I give up,

Perhaps my struggle will help beef up the logging in the migration code.

**Comment by kylebrandt** [comment]
Thank you for taking the time to share the issues you ran into.

Regarding the specific part with the aborted transaction from postgres, I think that could be this issue https://github.com/grafana/grafana/issues/35529 , which has fix https://github.com/grafana/grafana/pull/35556 that will be in 8.0.3 .

**Comment by steverweber** [comment]
I'll give >=8.0.3 a try after it's release.
