### ISSUE TITLE
No longer able to show non-time series data in a table

### ISSUE THREAD

**Issue by PrestonTaylor** [grafana/grafana#35685]
**What happened**: table holding data with no relevant time dimension no longer displays correctly.
![image](https://user-images.githubusercontent.com/11053557/121966868-5bb1a500-cd3d-11eb-84d0-41f541f4ba96.png)

**What you expected to happen**: hostnames along the left hand column, time information removed. This is how it used to display.
![image](https://user-images.githubusercontent.com/11053557/121966875-60765900-cd3d-11eb-9d78-c5eee66ee182.png)

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/11053557/121966882-64a27680-cd3d-11eb-8c23-69036d6d2f74.png)
Unfortunately I don't have an older version of grafana immediately available to double check but I believe this happened with the new table overhaul that came in 7.x, I'm in a shared environment for which I'm not the admin so I don't know exactly what was upgrade from or when. However; I'm 99% sure there used to be an option for pulling the data accross as a table rather than a time series. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.4
- Data source type & version: zabbix 4.1.5
- OS Grafana is installed on: Centos
- User OS & Browser: chrome
- Grafana plugins: zabbix 4.1.5
- Others:

**Comment by torkelo** [comment]
Think zabbix has updated to our new data format, I would recommend updating to v7.5 or v8 and use the new table panel (also available in v7.3), then use transformations to shape the data (reduce for example to only show one value for each series).

**Comment by PrestonTaylor** [comment]
Thanks, I guess I just needed to actively re-select "table" plugin, I assumed it was already selected, once I re-selected it things started to work normally again.
