### ISSUE TITLE
Playlist randomly logs user off

### ISSUE THREAD

**Issue by cong-trinh** [grafana/grafana#3568]
We have a playlist that run on a big screen near our team to monitor the health of our systems and everything works and looks great. But it seems like Grafana logs the current user off after ~10-15 mins. I thought that this is due to browser inactivity so I downloaded Session Keep Alive plugin for firefox that should ping the login page every 2 mins but this didnt help. I am wondering if anyone has any idea on how to keep the user login and the playlist running 24x7.

**Comment by torkelo** [comment]
this sounds very strange, the default session timeout is 24 hours, and it will be renewed every request, and even after that it can be renewed with the keep me logged in cookie. 

No one else has reported anything like this. What are you using for session storage? Do you have multiple grafana-servers infront of load balancer? Has others also found that they get logged out after short amount of time?

**Comment by cong-trinh** [comment]
The session storage is default and should be File. There is only one Grafana server and no load balancer between the browser and server. I am not sure if changing to use memory session storage will help but I will try once I get a chance as the Grafana user might not have permission to create the necessary session files. I have noticed this on my laptop too and others within my org experiences the same issue.

If it help at all I dont have to sign back in (sn/pw) but simply clicking the sign-in button on the left hand side will automatically log me back in where I can receate the playlist. I am running 2.5, it seems like 2.6 recently just released so I might give that a go and see if it helps.

Thanks for commenting back and good job with Grafana.

**Comment by cong-trinh** [comment]
Just an update I switch to use 2.6 and changed the session storage to memory and it hasnt logged me off in the last 5 hours. Closing.
