### ISSUE TITLE
Sidebar menu dropdown items unclickable on Safari

### ISSUE THREAD

**Issue by natellium** [grafana/grafana#35695]
**What happened**:
The dropdown on the sidebar closes before the user can click on an item

**What you expected to happen**:
The dropdown menu stays open while the user is hovering it

**How to reproduce it (as minimally and precisely as possible)**:
* Hover on a sidebar menu item. The dropdown will open
* Try to click on an item within the dropdown

See video:
https://user-images.githubusercontent.com/74534993/122010354-55620e00-cdbb-11eb-8b8c-f9f18043627f.mov

**Environment**:
- Grafana version: 8.0.1
- User OS & Browser: Safari 14.1.1

**Comment by peterholmberg** [comment]
Was just about to report the same! Same issue on chrome in windows10
