### ISSUE TITLE
Alerting: ability to delete cortex/loki groups

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35709]
**What would you like to be added**:
Should be possible to delete cortex or loki rule groups from the rule list page. Currently can only delete rules one by one.

**Why is this needed**:
Deleting a group by deleting rules one by one is time consuming and not obvious

**Comment by gillesdemey** [comment]
If we want to be able to delete alerts for a particular folder in Grafana Managed alerts, we should also add a new tab to the folder view.
