### ISSUE TITLE
Disable capability to create new Orgs for non admin users

### ISSUE THREAD

**Issue by W4lken** [grafana/grafana#3570]
Hello,

It appears that a grafana non admin user is able to create new organisations. Is it a bug or a normal behaviour ? Because I think a lot of administrators want to give access to users but only in read-only mode.

Best Regards

**Comment by cong-trinh** [comment]
The config gives you control on who can create orgs.

allow_org_create
Set to false to prohibit users from creating new organizations. Defaults to true.

http://docs.grafana.org/installation/configuration/
