### ISSUE TITLE
Alerting: threshold value is cleared when operator is changed in rule editor

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35717]
**What happened**:

When editing a condition in the UI, if you have an expression and change the operator (from < to > for example) and have previously set a numerical threshold (10) the value is not cleared in the UI but the post to the API no longer contains the number, so the condition fails to evaluate.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by peterholmberg** [comment]
@davidmparrott this issue is a copy of one you created. Can you still repro this?

**Comment by peterholmberg** [comment]
Closing this, can not reproduce
