### ISSUE TITLE
Alerting: autosuggest labels for matchers in notification policies and silences forms

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35716]
**What would you like to be added**:
When editing matching labels in silence or notification policy form, it would be helpful if labels from existing alerts could be autosuggested. 

**Why is this needed**:

**Comment by wardbekker** [comment]
+1 got a prospect asking for this today (not a blocker).

**Comment by konrad147** [comment]
We can try to use `api/v2/alerts/groups` endpoint from Alertmanager to get the list of firing alerts and their labels
