### ISSUE TITLE
Alerting: Add autocomplete to template editor to visualize available variables

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35726]
**What would you like to be added**:
Add a reference of available variables, or at leasta a link to docs in the templat editor

**Why is this needed**:

**Comment by gillesdemey** [comment]
We already have the link to the template documentation, but we will also add the default template to the message value so users have a good starting point.

**Comment by gillesdemey** [comment]
Since we're using the Monaco editor now we can add an auto complete provider
