### ISSUE TITLE
Session Timeout

### ISSUE THREAD

**Issue by blusterman** [grafana/grafana#3573]
I'm using Grafana on an info display and have to be logged in to see the dashboards (security reason). After about 20 minutes I'm logged out and Grafana is not able to show the graphs.

An option to stay logged in would be nice.

**Comment by torkelo** [comment]
what version of Grafana are you using? What session storage? Out of disk space? Default session store is using files on disk and 24 hour session timeout.

**Comment by blusterman** [comment]
I'm using the newest version (v2.6). Sorry for the double post, there is already an issue with this problem #3568
