### ISSUE TITLE
Alerting: support vanilla alertmanager

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35736]
**What would you like to be added**:
Currently the alertmanager supports only cortex alertmanager implementation. Could also support the vanilla prometheus alertmanager, though you'd only be able to manage silences and view notifications.

**Why is this needed**:

**Comment by heyoheyo** [comment]
Hello, we would absolutely love to have this feature! Do you know when approximately this would be available? And would it be possible to also manage notification policies via that (even if at later stage)? Thank you so much!

**Comment by domasx2** [comment]
Hey!

- It would work as a Alertmanager datasource, yes
- No idea yet about when, sorry :/
- It would only be possible to view alerts and manage silences. Prom alertamnager does not have API for editing configuration. You'd have to run cortex alertmanager if you need this

**Comment by matejzero** [comment]
For us, this would be good enough. Alerts management is run through git anyway, to review changes and run sanity checks CI jobs.

**Comment by weyert** [comment]
@domasx2 Yes, I second what @matejzero said. 

Would you be able to give any tips or trucks regarding making this happen? What would be needed to add support for vanilla alertmanager? Would a new datasource be added? Are there any UI changes needed?

**Comment by domasx2** [comment]
> What would be needed to add support for vanilla alertmanager? Would a new datasource be added?

Good question, we haven't thought it through yet :thinking:  I *think* it might be best to use the same existing datasource. Maybe add a toggle to datasource configuration to specify if it's cortex or prometheus implementation?

> Are there any UI changes needed?

When using the prometheus alertmanager, contact points & notification policies should be made read-only as it does not have an endpoint to update configuration.

**Comment by clyang82** [comment]
@domasx2 Do we support getting alert rules from the external alertmanager? I saw there is alert section in datasource configuration page 
<img width="531" alt="image" src="https://user-images.githubusercontent.com/7711311/138229204-4aade146-c4fd-47b6-a2b7-a774d03eaf25.png">

But I cannot get any alerts from the configured alertmanager in the alert rules page. 
<img width="1142" alt="image" src="https://user-images.githubusercontent.com/7711311/138229328-70d0f267-490e-40b7-b55f-0aec41234698.png">

Am I missing something? Thanks.
