### ISSUE TITLE
Alerting: opt out prometheus or loki datasources from alerting

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#35735]
**What would you like to be added**:
Should be possible to opt out prometheus or loki datasources from alerting via config editor. 

**Why is this needed**:

**Comment by simonswine** [comment]
I think that would be super useful feature. As part of GEM we have certain data sources (e.g. that query multiple tenants), which don't support the ruler. I think it would be great if it also could work without any additional data source config flag.  Maybe a 404 on the ruler API endpoint just means that there is no ruler support in the data source.
