### ISSUE TITLE
docker tag: latest

### ISSUE THREAD

**Issue by setiseta** [grafana/grafana#35743]
**What happened**:
Updated docker image grafana/grafana (without tag, so it uses latest) to update from 8.0.1 to 8.0.2 but got 7.5.8

**What you expected to happen**:
get version 8.0.2 with the latest tag

**How to reproduce it (as minimally and precisely as possible)**:
```
docker pull grafana/grafana
docker run --rm grafana/grafana | grep "server version"
```

**Comment by p-schneider** [comment]
`:latest` (and `:latest-ubuntu`) are now pointing at the 8.0.2 Versions.
[(see recent tags on dockerhub)](https://hub.docker.com/r/grafana/grafana/tags?page=1&ordering=last_updated)

**Comment by setiseta** [comment]
this seems to reappear. got an 7.5.12 instead of 8.3.2.
it seems the docker tags latest is still set on 7.5. releases.
