### ISSUE TITLE
Specifying a range of hosts

### ISSUE THREAD

**Issue by martbhell** [grafana/grafana#3574]
Hi,

Is it already possible to specify a range of hosts in grafana (I've only tested with 2.5) with graphite backend, like:

<pre>
nodes.c[10-578].collectd.aggregation-cpu-average.cpu-user
</pre>

It works right now if one keeps the number under 10, like this:

<pre>
nodes.c[1-9].collectd.aggregation-cpu-average.cpu-user
</pre>

But if one puts like anything over 10 or so it becomes a bit unpredictable. The below adds c1, c2 and c3:
<pre>
nodes.c[10-30].collectd.aggregation-cpu-average.cpu-user
</pre>

**Comment by torkelo** [comment]
Graphite supports glob syntax for selecting metric keys, not sure glob patterns support numeric ranges, but take a look at the wiki for glob expressions, https://en.wikipedia.org/wiki/Glob_(programming) 

and also checkout the graphite docs.
