### ISSUE TITLE
Alerting UI: Update matcher component for different operators

### ISSUE THREAD

**Issue by oanamangiurea** [grafana/grafana#35745]
Right now we allow the user to use For silences and notification policies we need to update the matching labels component. 

- Right now we use a checkbox to indicate the operator type (equal or not equal) between label and value. That should be replaced by a toolbar style button that features a dropdown selection of options (equal, not equal, and I think we should support "~" as well)
- For Regex we should add a tooltip saying in which field can the user use regex and make that into a switch not a checkbox, as it's an on/off type of thing 

Updated designs in [Figma](https://www.figma.com/file/2s7EGevGeI4GuiArOmUECK/Unified-Alerting?node-id=382%3A2)

![Screenshot 2021-06-15 at 15 23 59](https://user-images.githubusercontent.com/5183519/122051849-b6a2d500-cded-11eb-99d0-a2ac9c559163.png)

**Comment by kylebrandt** [comment]
This is what I see in the figma:

![image](https://user-images.githubusercontent.com/1692624/126338517-614a17c6-e46a-432e-9e04-47bea308bf03.png)

Which I think is nice. The other option might be a 4 options select, something like "Equal", "Not Equal", "Regex Match", "Not Regex Match"

**Comment by oanamangiurea** [comment]
@kylebrandt I like that idea with 4 options select, It will be much easier to understand where you are supposed to write the regex expression

**Comment by kylebrandt** [comment]
Dropping this sketch that Armand made in one of the linked issues for additional naming options (and its pretty / hand-drawn, seems a shame not to include in the main issue :-) )

https://user-images.githubusercontent.com/2117580/127180389-0418f368-8bf7-4ad3-854d-4260af8e0d10.jpeg

**Comment by oanamangiurea** [comment]
@kylebrandt I wonder if we could use icons as well as text in these dropdowns. Like:
```
= Equals
!= Does not equal
.* = Regex matches
.* != Regex does not match 
```

Or is it too confusing for the regex part?
