### ISSUE TITLE
Prometheus 2.0 Stats dashboard should use `TimeSeries` instead of `Graph (old)`

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#35757]
when adding a Prometheus data source, there's a dashboards tab with some prebuilt dashboards ready to be imported:

![image](https://user-images.githubusercontent.com/20999846/122065167-a25cd900-cde9-11eb-99bd-7296ff8c4c7e.png)

but when importing the Prometheus 2.0 Stats dashboard, the graphs use the old graph visualisation:

![image](https://user-images.githubusercontent.com/20999846/122065350-c7e9e280-cde9-11eb-869e-48ca7c2283e6.png)

feels like these should be upgraded to use `TimeSeries` to encourage users to use the new panel

**Comment by davkal** [comment]
Let's ask the #prometheus folks what they would like to see here. Also worth checking out our prometheus integration in Grafana Cloud.
