### ISSUE TITLE
Docs: dead link on https://grafana.com/docs/grafana/latest/alerting/create-alerts/ 

### ISSUE THREAD

**Issue by scoren-gl** [grafana/grafana#35783]
https://grafana.com/docs/grafana/latest/alerting/create-alerts/  is 404'ing - might have to do with a url change/re-org

Could potentially be redirected to https://grafana.com/docs/grafana/latest/alerting/

**Comment by achatterjee-grafana** [comment]
I am not sure where you found the missing link @scoren-gl, it should get re-directed to: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/

We have added new alerting documentation and the old URL will not work.

**Comment by achatterjee-grafana** [comment]
Closing the issue as the problem was resolved.
