### ISSUE TITLE
how to use time unit day

### ISSUE THREAD

**Issue by ThierryHenry1994** [grafana/grafana#35785]
**What happened**:
I want the data I retrieve from MySQL to be measured in days, which is what I set up but the final unit is weeks
**What you expected to happen**:
Display in days unit
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/32047768/122142307-c66bf900-ce81-11eb-973b-ed9b112a7fe4.png)

**Environment**:
- Grafana version:7.57
- Data source type & version:mysql
- OS Grafana is installed on:windows
- User OS & Browser:chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Many of the time units automatically scale as the values get longer.

If you just want a static days suffix you can specify a custom unit 'suffix: days'
