### ISSUE TITLE
Table hosts / metrics

### ISSUE THREAD

**Issue by janick02** [grafana/grafana#3578]
Hi,

I'd like to know if it's possible (or will be) to generate a table like this:

```
          +-----------+-----------+-----------+-----------+
          | Metric #1 | Metric #2 | Metric #3 | Metric #4 | 
+---------+-----------+-----------+-----------+-----------+
| host-01 |   Value   |   Value   |   Value   |   Value   |
+---------+-----------+-----------+-----------+-----------+
| host-02 |   Value   |   Value   |   Value   |   Value   |
+---------+-----------+-----------+-----------+-----------+
| host-03 |   Value   |   Value   |   Value   |   Value   |
+---------+-----------+-----------+-----------+-----------+
```

With values based on the last timestamp stored.

I know it's not a time series query, but it could be usefull in a dashboard.

**Comment by torkelo** [comment]
what time series store are you using?

**Comment by janick02** [comment]
Elasticsearch (2.1.0)

**Comment by Elufimov** [comment]
I have same question with same data source.

**Comment by torkelo** [comment]
This is almost what you want, but there is some limitations to column naming. 
http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=5&fullscreen&edit

**Comment by torkelo** [comment]
http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=6&fullscreen&edit
