### ISSUE TITLE
Multi value variable doesn't work with prometheus data source when variable contains dot

### ISSUE THREAD

**Issue by Davasny** [grafana/grafana#35792]
**What happened**:
Grafana escapes dots in prometheus query only when using variables, in result prometheus returns empty data set.

**What you expected to happen**:
When using variable with checked "multi value" I expect to pass same query to prometheus as without checked "mutli value"

**How to reproduce it (as minimally and precisely as possible)**:
1. Create new variable (I needed list of hosts) like this:
```
name: host
datasource: prometheus
query: query_result(up)
regex: /.*instance="([^"]+).*/
multi value: false
```
2. Create new panel (old graph or new time series)
3. Create query (I needed load avg)
```
system_load15{instance="$host"}
```
4. Save and select host
5. Great! Works fine
6. Change variable settings to `multi value: true`
7. Select one host
8. Doesn't work

**Anything else we need to know?**:
Query inspector returns:

1. For `multi value: false`
```
{
  "request": {
    "url": "api/datasources/proxy/9/api/v1/query_range",
    "method": "POST",
    "data": {
      "query": "system_load15{instance=\"dbX.X.X.X:1081\"}",
      "start": 1623805515,
      "end": 1623827115,
      "step": 15
    },
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "__name__": "system_load15",
            "host": "dbX.X.X.X",
            "instance": "dbX.X.X.X:1081",
            "job": "database-mongod"
          },
          "values": [
            [
              1623805515,
              "0.19"
            ],
            [
              1623805530,
              "0.18"
            ],
            [
              1623805545,
              "0.18"
            ]
          ]
        }
      ]
    }
  }
}
```

2. For `multi value: true`
```
{
  "request": {
    "url": "api/datasources/proxy/9/api/v1/query_range",
    "method": "POST",
    "data": {
      "query": "system_load15{instance=\"dbX\\\\.X\\\\.X\\\\.X:1081\"}",
      "start": 1623805695,
      "end": 1623827295,
      "step": 15
    },
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": []
    }
  }
}
```

As you can see, grafana escapes dots in query when using mutli value feature.

**Environment**:
- Grafana version: v8.0.2 (5c5d45e19f)
- Data source type & version: Prometheus
- OS Grafana is installed on: Centos 7
- User OS & Browser: Windows 10, Opera 76.0.4017.177
- Grafana plugins: -
- Others: -

**Comment by Davasny** [comment]
I think the problem is in `prometheusSpecialRegexEscape()`

https://github.com/grafana/grafana/blob/dcd4bf1615ac4d36574669b37c99e54172604d6a/public/app/plugins/datasource/prometheus/datasource.ts#L866

I think we should remove dot sign from this regex: `/[$^*{}\[\]\'+?.()|]/g`

**Comment by aocenas** [comment]
Don't think this is a but. Problem is that with prometheus to do a multivalue variable you have to use regext operator so it would be `system_load15{instance=~\"dbX\\\\.X\\\\.X\\\\.X:1081\"}` Then you can select multiple values a we will do a regext to match multiple hosts. Without the regex that won't work and as it is regext it needs different escaping for special characters witch then makes the query different than if it wasn't a regext.

So for single value you can use `{label="$variable"}` for multivalue variables you have to use `{label=~"$variable"}`.
