### ISSUE TITLE
Support NG-Alert Labels in Alert-List Panel

### ISSUE THREAD

**Issue by siegenthalerroger** [grafana/grafana#35797]
**What would you like to be added**:
The new alerts in grafana 8 allow us to have labels for each alert (e.g. for different services). This information is exposed to notifications but is not usable with the alert list panel. 

**Why is this needed**:
Currently I cannot only show alerts pertaining to a specific label (e.g. a specific service or severity).

**Comment by domasx2** [comment]
Related https://github.com/grafana/grafana/issues/35720

**Comment by peterholmberg** [comment]
Closing this as it is covered in #35720
