### ISSUE TITLE
InfluxDB flux, API add datasource Windows

### ISSUE THREAD

**Issue by LGKI** [grafana/grafana#35806]
**What happened**:
By creating a new data source using Grafana API. All was setup just token and httpHeaderValue was missing.

**What you expected to happen**:
I expect my configuration too be fully operational

**How to reproduce it (as minimally and precisely as possible)**:
Install Influx and launch it.
Generate a new API key in Grafana:
Give this configuration:

```Python
server = "http://localhost:3000/"
url = server + "api/datasources/"
headers = {"Authorization":"Bearer  <myAPIkey>",
    "Content-Type":"application/json",
    "Accept":"application/json"
}

my_json = {
    "access": "proxy",
    "basicAuth": False,
    "isDefault": False,
    "jsonData": {
        "defaultBucket": "test_bucket",
        "httpHeaderName1": "Authorization",
        "httpMode": "POST",
        "organization": "<orgName>",
        "version": "Flux"
    },
    "defaultBucket": "test_bucket",
    "httpHeaderName1": "Authorization",
    "httpMode": "POST",
    "organization": "<orgName>",
    "version": "Flux",
    "name": "InfluxDB",
    "type": "influxdb",
    "url": "http://localhost:8086/",
    "secureJsonFields":{
        "httpHeaderValue1": "Token <myAdminToken>",
        "token": "<myAdminToken>"
    },
    "withCredentials": False
}


r = requests.post(url = url, headers = headers, data = json.dumps(my_json), verify=False)
```

it return me

```
{'datasource': 
{'id': 18, 'uid': '****', 'orgId': 1, 'name': 'InfluxDB', 'type': 'influxdb', 'typeLogoUrl': '', 'access': 'proxy', 'url': 'http://localhost:8086/', 'password': '', 'user': '', 'database': '', 'basicAuth': False, 'basicAuthUser': '', 'basicAuthPassword': '', 'withCredentials': False, 'isDefault': False, 'jsonData': {'defaultBucket': 'test_bucket', 'httpHeaderName1': 'Authorization', 'httpMode': 'POST', 'organization': '***', 'version': 'Flux'}, 'secureJsonFields': {}, 'version': 1, 'readOnly': False}, 'id': 18, 'message': 'Datasource added', 'name': 'InfluxDB'}
```

**Anything else we need to know?**:
To send the request I use a Python script. But it can't come from there because the request is correctly send.

**Environment**:
- Grafana version:
v7.5.7 and v8.0.2 (i tried both)
- Data source type & version:
InfluxDB flux v2.0.5
- OS Grafana is installed on:
local machine
- User OS & Browser:
OS windows 10 pro & Google Chrome
- Grafana plugins:
None
- Others:
I already configure a data source like this one using the GUI. It is with the result of it that I tried to make this one. The one made with GUI work perfecttly.

![Capture](https://user-images.githubusercontent.com/44500201/122201739-a39b0e00-ce9c-11eb-89f7-f444ebe580cb.PNG)

**Comment by marefr** [comment]
No other similar reports so expect this to be an error from your side. When you create the data source through the UI, please have developer tools of browser open and the network tab. After posting/creating the data source inspect the POST request payload. 

Based on the code it looks weird that you provide both Authorization header and token when configuring the data source - are you sure this is really needed? In my head only token should be enough. 

I'm closing this since it doesn't seem to be a bug in Grafana, rather user error. If you could provide information/proof this is actually a Grafana bug we'll reopen the issue. For further help would suggest  our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by LGKI** [comment]
> No other similar reports so expect this to be an error from your side. When you create the data source through the UI, please have developer tools of browser open and the network tab. After posting/creating the data source inspect the POST request payload.
> 
> Based on the code it looks weird that you provide both Authorization header and token when configuring the data source - are you sure this is really needed? In my head only token should be enough.
> 
> I'm closing this since it doesn't seem to be a bug in Grafana, rather user error. If you could provide information/proof this is actually a Grafana bug we'll reopen the issue. For further help would suggest our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

I actually did it. All my post request are based on my observation comming from dev tools :/.  And you are right with the header, I removed it and it works (with GUI).  Here is my  new JSON, just in case:
```JSON
my_json = {
    "orgId":1,
    "name":"InfluxDB",
    "type":"influxdb",
    "typeLogoUrl":"",
    "access":"proxy",
    "url":"http://localhost:8086",
    "password":"",
    "user":"",
    "database":"",
    "basicAuth":False,
    "basicAuthUser":"",
    "basicAuthPassword":"",
    "withCredentials":False,
    "isDefault":False,
    "jsonData":{
        "defaultBucket":"test_bucket",
        "httpMode":"POST",
        "organization":"<org_name>",
        "version":"Flux"
    },
    "secureJsonFields":{
        "token":  <my_token>
    },
    "version":2,
    "readOnly":False
}
```
I remove `id` and `uid` it is the only difference with the observation and the request.

I also asked about this issue on Grafana Community but it seems that no one is trying to create a datasource influxDB with grafana API.

I'm sorry for the issue if you don't think it is one. I would be glad to search proof. Could you maybe indicated me witch repertory concern the datasource adding using API? I couldn't find that part.

Thank you for the fast answer!

**Comment by LGKI** [comment]
You are right, thank you! I'm sorry.
Header isn't needed but that is not the problem. The problem is `secureJsonField` has to be `secureJsonData`, when I look the data in dev tools I get `secureJsonField` but to POST a new data source you have to said **Data**

Again I'm extremely sorry for this mistake, my bad.
