### ISSUE TITLE
Annotation line too fine

### ISSUE THREAD

**Issue by volter** [grafana/grafana#3580]
The annotation line is so thin, it can even become invisible, due to sub-pixel precision positioning. I would suggest to allow for a wider line stroke in the annotation configuration.

**Comment by volter** [comment]
I took a brief look and setting a different line width and adding the form elements should be something I can manage. However, there seems to be a certain centering problem with the icon I would have to investigate further.

**Comment by robison** [comment]
Was about to open a feature request, but found this one already open. I'd love to see some additional options above & beyond what were available in 2.6 & previous versions, instead of removing the ability to change the arrow/marker size.

**Comment by devilldog** [comment]
what about not using an icon at all and going for something like data dog uses which is a wider stroke with like 70% opacity and stacking events that occur at the same time.
![datadog](https://cloud.githubusercontent.com/assets/8161862/15514552/920e1098-21b7-11e6-9fcd-d93ce06943cb.png)

**Comment by devilldog** [comment]
What about no icon with a wider line, reduced opacity and stack multiple annotations like data dog does ?
![datadog](https://cloud.githubusercontent.com/assets/8161862/15514575/aeedf3cc-21b7-11e6-827f-237d063b0c0f.png)

**Comment by robison** [comment]
I'd prefer to simply have some options around it; I can't say that I'm a fan of that UI element, personally - but I feel that quite a few things would be improvements over the current annotation presentation.

**Comment by envintus** [comment]
Having options around customizing the visualizing of an annotation would be great. Google's Stackdriver uses dots at the top of a graph to indicate an annotation. Having options like that in addition to the current implementation would be good.

![](https://codelabs.developers.google.com/codelabs/cloud-stackdriver-getting-started/img/bd40ff0f3bdf99e7.png)

**Comment by torkelo** [comment]
we changed changed how annotations are rendered since this issue was created, think they are more visible now
