### ISSUE TITLE
Show graph group by year

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#35800]
Hi, I'm encountering a lot's of problem in trying to correctly show values grouped by year. Are several weeks I'm trying and I think the problem is the incorrect of timing conversion within $__timeGroup macro. I tryed to ask for more helps in grafana forum but no answer.
Here you can find all the details (last message) https://community.grafana.com/t/same-dashboard-with-more-relative-time-panel/39266/11?u=donatod

**Comment by dsotirakis** [comment]
Hello @DonatoD , thanks for raising this. Please try to follow our template about raising issues next time you raise one!

Looping in @grafana/grafana-frontend-platform , since the changes mentioned in the community forum are mostly frontend related.

**Comment by DonatoD** [comment]
Sorry. Could you please explain better on how do it?

**Comment by dsotirakis** [comment]
@DonatoD no problem! When you first open a new issue, you can see some existing comments and headings there, inside the description box. These are guidelines - header templates on how a good issue should be filed in order for the team to know what needs to be done or what this issue is for really.

For example when you try to open a bug report, you'll see in the description box:

```
<!--
Please use this template to create your bug report. By providing as much info as possible you help us understand the issue, reproduce it and resolve it for you quicker. Therefor take a couple of extra minutes to make sure you have provided all info needed.

PROTIP: record your screen and attach it as a gif to showcase the issue.

- Questions should be posted to: https://community.grafana.com
- Use query inspector to troubleshoot issues: https://bit.ly/2XNF6YS
- How to record and attach gif: https://bit.ly/2Mi8T6K
-->

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
```

this is for use, and not for deletion!

**Comment by DonatoD** [comment]
Sorry! Here more details:
- Grafana version 8.0.1
- Data source Mysql (phpMyAdmin 5.1.0)
- Windows 10
- Google Chrome
I've tried to visualize the graph with other programs other than Grafana, and it is shown correctly.
Thanks

**Comment by mckn** [comment]
Hello, sorry for the late response. It sounds like you should be able to do this with a bar chart. Did a quick example here:

<img width="1655" alt="Skärmavbild 2021-07-12 kl  21 40 05" src="https://user-images.githubusercontent.com/172951/125346322-e2b46600-e359-11eb-9472-05269e65cbe6.png">

I hope this helps 🙏🏻

**Comment by DonatoD** [comment]
Thanks Marcus. In this way I'm able to see data correctly, but I need to show one value as bar and onother one as line.
For what I know the only way I can do it is with time series graph. With bar chart I didn't find how to do it, even looking for some overrides :-(  :-(  :-(

**Comment by DonatoD** [comment]
Why it's closed? data are still shown incorrectly even with last release
