### ISSUE TITLE
Deleting curated dashboards fail with 404 error

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#35811]
**What happened**:

Attempting to delete a dashboard I imported from a data source (curated dashboards) results in a 404 error.

![image](https://user-images.githubusercontent.com/46142/122205620-5e74dd00-ce98-11eb-8bc2-c589dbece606.png)

It's trying to make a `DELETE /api/dashboards/db/amazon-ec2` request, which 404s

**What you expected to happen**:

It deletes the dashboard without an error 😅

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure data source `gdev-cloudwatch`  (or any other data source with curated dashboards)
2. Add a dashboard from the "Dashboards" tab of the data source
3. Attempt to delete the dashboard. It'll error

**Anything else we need to know?**:

**Environment**:

Failing on latest main (16850630bf)

**Comment by leandro-deveikis** [comment]
This should be fixed with #46636
