### ISSUE TITLE
How do I sign a plugin？

### ISSUE THREAD

**Issue by zqw961025** [grafana/grafana#35816]
Hi, I'm using the Grafana ClickHouse plugin but I find it's unsigned,  I know the following ways I can use it：
[plugins]
allow_loading_unsigned_plugins=vertamedia-clickhouse-datasource

But it is still unsigned and I would like to sign for it. How should I do it or is there any other better solution?

**Comment by wbrowne** [comment]
@zqw961025 It is the responsibility of plugin authors to sign their plugins. Are you the author of the `vertamedia-clickhouse-datasource` plugin?

The `allow_loading_unsigned_plugins` will allow the plugin to load but it will still show it as unsigned, for security purposes. What version of the plugin are you trying to run? I can see that the [latest version](https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource) is signed

**Comment by zqw961025** [comment]
My ClickHouse plugin is version 2.1.0 and Grafana is version 7.5.7, I would like to ask if only the plugin author can signthe plugin, can I only sign the ClickHouse plugin in my own local.

**Comment by wbrowne** [comment]
Yes it looks like version `2.1.0` wasn't yet signed. If you can upgrade the plugin to its latest version (`2.3.1`), then it will be marked as signed. Let me know if this works for you.

>can I only sign the ClickHouse plugin in my own local
No it doesn't work like that. Only versions that are officially signed by the plugin author will work. This is to ensure that the package is signed by a trusted authority who have gone through the plugin submission flow, where it gets directly reviewed and approved by Grafana.

**Comment by zqw961025** [comment]
I have changed version clickhouse  to 2.3.1, thank you very much.

**Comment by zqw961025** [comment]
I have another question that I would like to ask, I deployed Grafana via Dockerfile, it looked fine at first, but when I tried to view the log file, there was no file in the /var/log/grafana directory. I found that the default log file configuration is:
[log]
logs = /var/log/grafana
I made sure that my users had read and write access to the directory，What's going on here？

**Comment by wbrowne** [comment]
@zqw961025 Please open another issue if you're experiencing a different problem
