### ISSUE TITLE
Docs: The correct "Global variables" page doesn't show up on Google

### ISSUE THREAD

**Issue by theneva** [grafana/grafana#35818]
Hi! :wave:

I've twice been led to believe I have a false memory of the "Global variables" docs page now, so I figured I'd give you a heads-up.

**What happened**:

Using Google, DuckDuckGo, or Bing to search for "grafana global variables" doesn't list the latest "Global variables" docs page with content, but instead lists the Grafana 6.7 version of the page.

The page I expected to show up in search results (note that the `<title>`, URL path, and heading are all "Global variables):

![image](https://user-images.githubusercontent.com/1404650/122219291-96d3e580-ceaf-11eb-9c35-0c0a28949219.png)

A Google search from an incognito Chrome window:

![image](https://user-images.githubusercontent.com/1404650/122216641-e8c73c00-ceac-11eb-8ec0-10c1a261096e.png)

Note that Google _does_ list the correct (/latest/…) "URL variables" page (https://grafana.com/docs/grafana/latest/linking/data-link-variables/) whose link to the "Global variables" page is _in Google's content preview_.

**What you expected to happen**:

I expected the latest version of the "Global variables" page to show up with a normal content preview in the Google search results in response to a pretty unambiguous query.

**How to reproduce it (as minimally and precisely as possible)**:

Search Google for "grafana global variables" or any other query that should obviously be good enough.

**Anything else we need to know?**:

I think the issue is that Google has already indexed the page under the Grafana 6.7 docs URL path, and the page hasn't changed significantly enough for Google to bother indexing the one under the /latest/… path.

I'm by no means an SEO expert, but I did check a couple of things.

I checked for any response headers on https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/ that could cause Google to not crawl or index the page, but didn't find anything with Chrome or (in case the header is omitted from responses to common browsers) cURL:

![image](https://user-images.githubusercontent.com/1404650/122218147-6b9cc680-ceae-11eb-859b-361617c87ea1.png)

I also checked if there were any robots.txt files under any of the subpaths leading up to https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/ (there weren't), and the root robots.txt at https://grafana.com/robots.txt looks like this:

![image](https://user-images.githubusercontent.com/1404650/122218249-88d19500-ceae-11eb-90b5-21073297ba3b.png)

I don't believe the robots.txt file to be at fault, since other pages under `/docs/grafana/latest/` (such as https://grafana.com/docs/grafana/latest/linking/data-link-variables/) are listed.

That said, there is some other weirdness, because the "URL variables" page listed in Google only has its `<title>` set to "URL variables", while both the path and page heading have been changed to "Data link variables":

![image](https://user-images.githubusercontent.com/1404650/122219028-52e0e080-ceaf-11eb-9440-0e220203c413.png)

I guess that might just be an oversight and thus unrelated to the indexing issue.

**Environment**:

Most of these are N(ot)/A(pplicable) because this seems to be an issue with the docs website.

- Grafana version: N/A
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Google Chrome Version 91.0.4472.101 (Official Build) (x86_64) running under macOS Big Sur Version 11.3 on a 2018 15-inch MacBook Pro
- Grafana plugins: N/A
- Others: N/A

**Comment by theneva** [comment]
(I made some edits to the original post because I realised the preview-less search result near the top of the search results is, in fact, the page I'm looking for – but under the docs path for Grafana 6.7.)

**Comment by torkelo** [comment]
thanks for reporting this, was problem with our regex for no index on versioned (old) docs, it also matched doc pages starting with a v

**Comment by theneva** [comment]
oh, awesome, thanks for the quick fix!
