### ISSUE TITLE
Loki data source - Max data points vs. step

### ISSUE THREAD

**Issue by JNevrly** [grafana/grafana#35828]
**What happened**:
Using Loki data source, I set `Max data points` to 1, in query, I use range vector with variable 
`sum(count_over_timer(.... [$__interval])) by (...)`
Dashboard time range is set to `Last 24 hours`. 

In query inspector, I see the `$__interval` substituted as `1d` which I think is correct, and the `step=86400`, which I also think is correct.
However, in the query response, I get grouped series, each with **two** data points - one for `now()`, one for `now()-24h`. 

This creates a problem even if I'm using the "Last" transformation, because of the grouping - let's say a log line that was present in the aggregate for `now()-24h` is not present in the aggregate for `now()`, then I get series whose last value is zero (there is no transform that allows to rid of such series).

**What you expected to happen**:
I expect to get query response with grouped series, each having **exactly one data point**, that is a range-vector-based aggregate of the last 24 hours. Therfore, if the matching log line is not in the aggregate from last 24 hours, it would be not present in the query result.

In current implementation, because of this bug, I also get series that should not been there (last value 0), because a matching log line was present in the previous point `now()-24h` aggregate.

**How to reproduce it (as minimally and precisely as possible)**:
Any query with Loki data source with `Max data points` limited to 1.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.3.5
- Data source type & version: Loki (default)
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: Loki data source (default)
- Others:

**Comment by torkelo** [comment]
max data points is only a Grafana option that for many data sources is only used to calculate the interval (step in Loki's case). I pinged the loki team to see if they can answer why your getting two data points back in this case and if there is any way to do what you want

**Comment by torkelo** [comment]
@JNevrly can you try an instant query?

**Comment by JNevrly** [comment]
Thanks a lot for a quick support!

I've read about the instant query in the documentation and I think this could be the way to achieve what I want, but I don't know how to do it. I don't see any UI option for that in the panel's query editor...

**Comment by wardbekker** [comment]
Hi @JNevrly 

The Query type setting is below the query editor when editing a panel. It was introduced in a 7.x Grafana (don't know the exact version, but I would guess 7.4.x) 

Example:

![image](https://user-images.githubusercontent.com/35603/122355523-3ea1ef80-cf52-11eb-92c9-97db7453cc69.png)

range queries will indeed not guarantee a single result

**Comment by JNevrly** [comment]
Thanks! Actually, I've managed to solve it even using the 7.3.5 (which doesn't offer the UI on your screenshot), using the Prometheus datasource plugin pointed on my Loki instance. Then I get the UI offering the instant query and that does exactly what I needed. 

Thanks a lot for pointing me in the right direction! However, I still think that the original Loki datasource behaviour I've described is kind-of unexpected.

**Comment by wardbekker** [comment]
I think I see a tiny difference between the step size and the timerange from Grafana.

1623918712 − 1623917811 = 901, while the step is 900, this probably adds the extra result. WDYT @cyriltovena 

![image](https://user-images.githubusercontent.com/35603/122361779-dc4bed80-cf57-11eb-8465-b6ec6470de76.png)

**Comment by ivanahuckova** [comment]
I reopened and will investigate to find the reason/see if there is something that could be improved/fixed.

**Comment by ivanahuckova** [comment]
> I think I see a tiny difference between the step size and the timerange from Grafana.

I have tried to set max data points to 1, set the step that it matches the seconds difference between to-from (301 seconds) and I still got 2 results. So I don't think it is because of a larger time range than the step. 
+cc @cyriltovena
