### ISSUE TITLE
Add option to change data source when importing dashboard

### ISSUE THREAD

**Issue by KEVISONG** [grafana/grafana#35832]
**What would you like to be added**: Add option to change data source when importing dashboard.

**Why is this needed**: A dashboard is exported with data source hardcoded in the exported JSON file, which is hard to import again if the data source name is different (even if the underlying data source is the same, while the data source name is different, the imported dashboard is not gonna work).

The current workaround is to manually replace all data source name in the JSON file before importing.

**Comment by torkelo** [comment]
this should be easier to do properly after https://github.com/grafana/grafana/pull/33817 is completed

**Comment by torkelo** [comment]
If you export a dashboard for sharing (toggle int the share/export modal), then use the import dashboard page you will get to select data source during import
