### ISSUE TITLE
Access ngalert alert info returns empty string

### ISSUE THREAD

**Issue by LMBoehm** [grafana/grafana#35833]
I set up an alert rule in Grafana v8.0.1 using the new grafana 8 alerts. When I click `preview your alert` in the `Create alert rule` UI I get the following table:

| State | Info |
| ----- | ---- |
| Alerting | [ metric='hostxzy' labels={instance=hostxyz:1234, job=name} value=100 ] |

According to this: [Link](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/#details) I should be able to access the information of the above table like so: `{{ $labels.instance }}`. However, when I do that in the `Add details for your alert`-summary section it only returns an empty string instead of `hostxyz:1234`. It would be very helpful to be able to access all values from the table to provide more information in the alert message.

**Comment by kylebrandt** [comment]
I think this means you are using the classic condition expression for the alert. This operation is special in that it doesn't track alerts per labels.

If you use reduce and math, then alert instances will be per label, and then labels that come from the data will be available.

Presently, regardless that info string is not structured yet and is just a string (looking to change in the future). But when you do "preview alert" and see additional columns that have string values, those are labels that should be accessible presently.

**Comment by LMBoehm** [comment]
thank you, using reduce and math works!

**Comment by julienlr** [comment]
Is there a way to get the value that triggered the alert ? {{ value }} and {{ labels.value }} doesn’t work for me

**Comment by istar2metal** [comment]
> Is there a way to get the value that triggered the alert ? {{ value }} and {{ labels.value }} doesn’t work for me

Same question

**Comment by Selaron** [comment]
@julienlr @istar2metal  try {{ $value }}, this results in a String like "[ metric='hostxzy' labels={instance=hostxyz:1234, job=name} value=100 ]", but I don't know how to access or loop through the elements in there in order to generate a better text output.
