### ISSUE TITLE
Alerting: State history missing in new alerting

### ISSUE THREAD

**Issue by bsper2** [grafana/grafana#35841]
**What would you like to be added**:
Hoping that the 'State History' feature that is in Grafana v7 makes its way to v8. We have a v8.0.2 install with the new alerting turned on and this feature is missed.

**Why is this needed**:
Very helpful to have a method from within Grafana itself to view the state history of your alerts.

**Comment by gotjosh** [comment]
Part of https://github.com/grafana/grafana/issues/41164
