### ISSUE TITLE
v8.0.x multi data source queries with innflux and mysql results in mysql fields prefix as "results x"

### ISSUE THREAD

**Issue by xfatzleex** [grafana/grafana#35840]
**What happened**: in v8.0.x  multi data source queries with influx and mysql results in mysql fields fields appended as results_x. this has caused outer join transformations to not work between influx and mysql queries where panels have influx and mysql as datasource

**What you expected to happen**: in v7, when we show data frame, mysql fields will show as their defined column names. i.e. id, name, 

**How to reproduce it (as minimally and precisely as possible)**: in a panel, query A use influx db as source, query B, use mysql as source, both should have a common field , try to do outer join transforation.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.2, v8.0.1
- Data source type & version: influxdb 1.7, mariadb10.4, mysql
- OS Grafana is installed on: ubuntu 18.04
- User OS & Browser: chrome  91.0.4472.106
[v7 v8 comparison.pdf](https://github.com/grafana/grafana/files/6665964/v7.v8.comparison.pdf)

**Comment by xfatzleex** [comment]
just to add, this was not seen in a multi datasouce query with mysql + mysql
only seen in influx + mysql

**Comment by torkelo** [comment]
duplicate https://github.com/grafana/grafana/issues/35390 we have a fix in the works https://github.com/grafana/grafana/pull/35839
