### ISSUE TITLE
Dashboard: issue re-selecting default time zone in settings.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#35849]
**What happened**:
![timezonr](https://user-images.githubusercontent.com/172951/122045112-9c60fb00-cddd-11eb-885f-82eae65285dd.gif)

**What you expected to happen**:
The default timezone (in this case, CEST) should be selected and used in the dasboard.

**How to reproduce it (as minimally and precisely as possible)**:
Please follow the steps in the gif image above.

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 8.1.0-pre (https://github.com/grafana/grafana/commit/eb7dd8e377c19524788e3532214f10c4cd354267)
- Data source type & version: N/A
- OS Grafana is installed on: macOS Big Sur (11.4)
- User OS & Browser: macOS Big Sur (11.4) / Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by axelavargas** [comment]
@mckn Hey Marcus :D thank you for reporting the issue 🙌🏾 . I was trying to reproduce this locally (using the main branch), but I couldn't, it seems is fixed, or maybe is there a configuration that I am missing? 

My default user timezone is: Browser time


![TimezonDefault-working-as-expected](https://user-images.githubusercontent.com/239999/123074442-95f30480-d417-11eb-91de-54e1fb4a4373.gif)

**Comment by mckn** [comment]
I also had a look at this again and I can not longer reproduce this in main. I will close this issue, thanks for having a look at it @axelavargas
