### ISSUE TITLE
StatPanel: DataLink hint text is not visible

### ISSUE THREAD

**Issue by baur** [grafana/grafana#35846]
**What happened**:
Dashboard Links not visible in Kiosk mode

![image](https://user-images.githubusercontent.com/2898361/122328335-490fb980-cf51-11eb-9952-82f0dce4ba3b.png)

Link Title

![image](https://user-images.githubusercontent.com/2898361/122328449-7bb9b200-cf51-11eb-8d6b-4112ec590834.png)

**What you expected to happen**:

Actually i wanted Dashboard Links was visible in Kiosk mode #15776 , 
but is this case Link title on Hint text

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.2 (5c5d45e19f)
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows 10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you show your panel json? What is the data? is the panel showing multiple stats or one?

**Comment by baur** [comment]
@torkelo 
> Can you show your panel json? What is the data? is the panel showing multiple stats or one?

{
  "id": 811,
  "gridPos": {
    "h": 3,
    "w": 24,
    "x": 0,
    "y": 3
  },
  "type": "stat",
  "title": "Навигация",
  "pluginVersion": "8.0.2",
  "fieldConfig": {
    "defaults": {
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      },
      "links": [
        {
          "title": "Переход",
          "url": "${__data.fields.link}"
        }
      ]
    },
    "overrides": []
  },
  "options": {
    "reduceOptions": {
      "values": true,
      "calcs": [
        "lastNotNull"
      ],
      "fields": "/^linkName$/"
    },
    "orientation": "auto",
    "text": {
      "valueSize": 23
    },
    "textMode": "value",
    "colorMode": "background",
    "graphMode": "area",
    "justifyMode": "auto"
  },
  "targets": [
    {
      "alias": "",
      "format": "table",
      "rawSql": "select 'd/F4yKhe6Gq/dobycha?orgId=1&kiosk' as link, 'LinkName1' as linkName\r\nunion all select 'd/F4yKhe6Gr/priem-rudy?orgId=1', 'LinkName2'\r\nunion all select '', 'LinkName3'",
      "refId": "A"
    }
  ],
  "datasource": null
}

**Comment by torkelo** [comment]
So it sort of depends on what the text mode option is set to, if the text mode set to value & name (or auto), then the tooltip can show the data link name. But otherwise the visualization tooltip will take precedence (and show name or value)
You can play around with text mode here: 
https://play.grafana.org/d/9DPT9MDGk/stat-data-links-from-data?orgId=1&editPanel=2 

Since your returning LinkName1  in your query you can just set this to whatever you want to show in the tooltip. and then pick this field in the Fields select

**Comment by baur** [comment]
Please show me case when Title is working from Edit Link from

![image](https://user-images.githubusercontent.com/2898361/122328335-490fb980-cf51-11eb-9952-82f0dce4ba3b.png)

**Comment by torkelo** [comment]
Set text mode to name and value (under stat options)

**Comment by baur** [comment]
@torkelo 

**So sad, I can't hide link any way (((**

![image](https://user-images.githubusercontent.com/2898361/122388723-f9051700-cf91-11eb-9372-01a91a3ed6cc.png)
