### ISSUE TITLE
Search: Input does not show what I type until I stop typing 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#35847]
With https://github.com/grafana/grafana/pull/35033 we tried to improve the sluggish feeling of typing when using seach. The debounce on the locationUpdate is great limits re-renders but the search input itself never updates to I never see what I type until I stop so the feeling a very sluggish UI remain.

**Comment by torkelo** [comment]
@Clarity-89 any alternative solutions? can we de-couple the search input box from the URL in a way that still allow URL-> search input updates?

**Comment by Clarity-89** [comment]
I'm not sure it has anything to do with updating location, I've tested it without location update and the behaviour is the same. Also it seems like the input debouncing starts only after the results for the first query have been loaded, i.e. it doesn't happen when first opening search and typing a query. I'll look into this.
