### ISSUE TITLE
AzureMonitor: Show a warning in Log Analytics panel if different credentials are set

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#35858]
**What would you like to be added**:

After https://github.com/grafana/grafana/pull/35121, Log Analytics credentials are no longer used. If the user visits the data source config page, they will see the error banner but if they don't, a panel which were using those credentials can be silently failing. We should show a warning in that scenario so the user gets notified about the change.

We should also provide an upgrade path for the data source so user can remove the banner/error once they have migrated (if necessary) their credentials.

cc/ @kostrse

**Comment by joshhunt** [comment]
It would be great if we could show warnings in an easy way on the dashboard, but I'm not sure how much effort to spend on this. I think with messaging in both the change log/whats new and in the config editor, we've covered the bases well.

I think we can make panels show a warning (??) if they have separate credentials configured (but are no longer being used), but we would need an easy way for users to dismiss these (could just be a "clear credentials" button in config editor)

**Comment by andresmgot** [comment]
> I think we can make panels show a warning (??) if they have separate credentials configured (but are no longer being used), but we would need an easy way for users to dismiss these (could just be a "clear credentials" button in config editor)

Yes, I don't know if a plugin can define these kind of warnings but I was thinking on something like: 
![Screenshot from 2021-06-22 09-18-39](https://user-images.githubusercontent.com/4025665/122881020-f6f8da80-d33a-11eb-81da-58ebe8c47974.png)

And then the "clear credentials" button to remove the warnings and set the value `sameAs: true`.
