### ISSUE TITLE
Cannot enable auto-refresh when zooming to a custom time range

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#3585]
When zooming in or specifying a custom time range, the auto-refresh get disabled and cannot be enabled again unless selecting a relative time range (selecting a refresh interval and applying does nothing).
This is a problem when viewing future data (e.g. forecasts) and then zooming in to a smaller range

**Comment by torkelo** [comment]
this is already fixed in master and in latest stable version 2.6
