### ISSUE TITLE
The performance of Elasticsearch queries generated by grafana are not optimal 

### ISSUE THREAD

**Issue by shankerwangmiao** [grafana/grafana#35866]
**What happened**:

When using elasticsearch panels, queries with empty "lucene query" takes too long to complete. 

In the query inspector, I can see the queries generated is not optimal: 

``` json
{
  "search_type": "query_then_fetch",
  "ignore_unavailable": true,
  "index": "<index_name>"
}
{
  "size": 0,
  "query": {
    "bool": {
      "filter": [
        {
          "range": {
            "@timestamp": {
              "gte": <start_time>,
              "lte": <end_time>,
              "format": "epoch_millis"
            }
          }
        },
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*"
          }
        }
      ]
    }
  },
  "aggs": {
 // omitted
```

By running the same query in the Kibana console and profiling it, I can figure out that it is the following filter item that leads to the problem, especially there are large amount of fields in the documents in the index:

``` json
        {
          "query_string": {
            "analyze_wildcard": true,
            "query": "*"
          }
        }
```

By removing the `query_string` filter, the speed of the query can be improved significantly. Furthermore, The following patch, by removing `query_string` filters with `*` in its `query` field, can significantly increase the loading speed of the entire dashboard.

``` patch
diff --git a/public/app/plugins/datasource/elasticsearch/query_builder.ts b/public/app/plugins/datasource/elasticsearch/query_builder.ts
index 5f5eb9f842..9a2205cb2c 100644
--- a/public/app/plugins/datasource/elasticsearch/query_builder.ts
+++ b/public/app/plugins/datasource/elasticsearch/query_builder.ts
@@ -228,6 +228,10 @@ export class ElasticQueryBuilder {
       },
     };
 
+    if (queryString === '*') {
+      query.query.bool.filter.pop();
+    }
+
     this.addAdhocFilters(query, adhocFilters);
 
     // If target doesn't have bucketAggs and type is not raw_document, it is invalid query.
```

**What you expected to happen**:

There should be no `query_string` filters with `*` in its `query` field in the generated elasticsearch query.

**How to reproduce it (as minimally and precisely as possible)**:

In any elasticsearch panel, with a query whose ``Lucene Query" is empty, such pattern of generated elasticsearch query can be spotted.

**Anything else we need to know?**:

The patch above is a proof of the cause of this issue, but I guess this patch may not be adequate to get applied.

**Environment**:
- Grafana version: Grafana v8.0.0 (41f0542c1e)
- Data source type & version: Elasticsearch 7.13.2
- OS Grafana is installed on: Debian Buster
- User OS & Browser: Safari 14.1.1 on macOS Catalina 
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Actually, we might want to hold back from fixing it in the front-end as we plan to remove the front-end implementation of the query builder and always go through Grafana BE.

**Comment by shankerwangmiao** [comment]
> Hi @shankerwangmiao , thanks for reporting this!
> 
> I would actually consider this a bug that slipped through somehow, in the BE (when doing alerting) we actually omit it:
> 
> https://github.com/grafana/grafana/blob/7a304223e69f6a9c06405ed7ec6ff817ebb4787d/pkg/tsdb/elasticsearch/time_series_query.go#L79
> 
> I'll take a look at it.

Maybe it is because an the front-end, '*' is auto added when the query is empty?
