### ISSUE TITLE
New Alerting (ngalert) : Configure no data an error handling could not set

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#35865]
Grafana 8.1.0-26372pre on Windows Server 2019
Published via Sophos XG Firewall Webproxy to https://www.zoomsoft.de/grafana

If i enable _Configure no data and error handling_ and save the rule it won't be saved.

<img width="524" alt="grafik" src="https://user-images.githubusercontent.com/79257887/122365138-b70cae80-cf5a-11eb-8c75-41e6aa14208d.png">

**Comment by kylebrandt** [comment]
@UlrichThiess Can you describe the behavior a bit more? For me it always seems to save. I do notice that when I save it,  the slider-checkbox goes back to "hidden", but the fields under it are not set, then when it refreshes that section is not expanded, but it still saves.

Note that slider itself doesn't have any effect on the alert rule, only the selection of the two drop downs that appear when it is selected (Although I can see how that might be confusing from a UX perspective).

But perhaps you are experiencing something else?

**Comment by UlrichThiess** [comment]
Please, please, please excuse me.

Of course it works, I mistook the switch for the on / off switch.

But maybe that's really where the decision should be made to remove the switch and always show the options. It is the only use of such a switch and it can be seen that it leads to confusion.
