### ISSUE TITLE
Cloudwatch: Dimensions

### ISSUE THREAD

**Issue by vasiliyb** [grafana/grafana#3586]
Folks,
  I do not see a way (documented) to graph for a sample metrics across my entire fleet.  Lets say we wanted CPU Credit Utilization graphed across all of our t2.* instances... What should the Dimension be?  Specifying `InstanceType=t2*` does not yield any data.

Thanks!

**Comment by torkelo** [comment]
not sure the Cloudwatch api supports wildscards for dimension filters. Check the docs:
http://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/CW_Support_For_AWS.html
