### ISSUE TITLE
"convert value to float failed: metricIndex 1 type can't be converted to float" after upgrade to 8.0.2

### ISSUE THREAD

**Issue by sh4d0v1** [grafana/grafana#35876]
**What happened**:
After upgrade to Grafana 8.0.2 some simple graphs broke, which were showing integer data.
Error message: "convert value to float failed: metricIndex 1 type can't be converted to float"
The data types triggering the bug are smallint and tinyint unsigned from a MySQL database.

**What you expected to happen**:
Successful conversion to float values.

**How to reproduce it (as minimally and precisely as possible)**:
Plot a graph with smallint or tinyint column data from a MySQL database.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: 10.3.27-MariaDB-0+deb10u1
- OS Grafana is installed on: Debian Stable
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Please include the query you're using. Thanks

**Comment by sh4d0v1** [comment]
Yeah, sorry, it is so basic I didn't include it:

`SELECT
  timestamp AS "time",
  PR
FROM sensordata
WHERE
  timestamp BETWEEN FROM_UNIXTIME(1623757180) AND FROM_UNIXTIME(1623929980) AND
  device_id = 5
ORDER BY timestamp`

PR is a smallint here.

**Comment by kylebrandt** [comment]
As a temporary workaround, it might work to cast the tinyint column (`PR` I assume) to a something else - something like `, CAST(PR as signed) FROM`
