### ISSUE TITLE
Grafana 8.0.2 + InfluxDB (Flux) issue: "Data does not have a time field"

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#35874]
**What happened**:
We are trying to use our 'usual' Flux queries to load timeseries from InfluxDB Cloud 2.0 via Flux for visualization in Grafana. This is done via a query similar to the one recommended in the [Grafana Docs](https://grafana.com/docs/grafana/latest/datasources/influxdb/influxdb-flux/):

```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> filter(fn: (r) => r["_measurement"] == "958D2219")
  |> filter(fn: (r) => r["_field"] == "EngineSpeed")
  |> yield(name: "mean")
```

**What you expected to happen**:
The above query would usually let us load the time series from InfluxDB without issues - this has worked in 7.X versions of Grafana. However, as of 8.X, the data is not loaded and instead we get a message stating `Data does not have a time field`. We have verified that the same InfluxDB data source + Flux query works without issues in older versions of Grafana:

![image](https://user-images.githubusercontent.com/26184427/122384898-6d2cc400-cf6c-11eb-9bdc-d0be35641f20.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an InfluxDB Cloud 2.0 free user account
2. Link it with Grafana Cloud 8.0.2 free user account
3. Attempt to use the standard default query as outlined above to show a time series

**Comment by MatinF** [comment]
I've attached below the JSON request information as well. If anyone else has found a way to handle this short-term, your inputs would be appreciated - currently, it seems to us that Grafana 8.0.2 and 8.0.3 + InfluxDB Flux is broken.

```
{
  "id": 23763571993,
  "gridPos": {
    "h": 9,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "type": "timeseries",
  "title": "Panel Title",
  "datasource": "InfluxDB",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "options": {
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "hide": false,
      "query": "from(bucket: v.defaultBucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> aggregateWindow(every: v.windowPeriod, fn: mean)\r\n  |> filter(fn: (r) => r[\"_measurement\"] == \"958D2219\")\r\n  |> filter(fn: (r) => r[\"_field\"] == \"EngineSpeed\")\r\n  |> yield(name: \"mean\")",
      "refId": "A"
    }
  ]
}
```

**Comment by gabor** [comment]
hi @MatinF , yes, that flux query should indeed work (i've just verified it on some test data and it worked). though i do recommend moving the `aggregateWindow` line to be second-to-last, like this:

```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "958D2219")
  |> filter(fn: (r) => r["_field"] == "EngineSpeed")
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> yield(name: "mean")
```

could you try it in this order? (i don't think this is the problem, but just to be sure).

if it does not work, we will need to see the raw csv result coming from influxdb.

if you login to influxdb-cloud:
- go to `Explore`
- enter the query
- please verify that you can run it and you see the visualization you expect there
- below the visualization there is a button to download CSV. this allows you to download the raw csv result from the query
- please download the csv

then please make sure you remove any confidential/private/secret info from the csv result, and then upload the csv here so we can take a look. thanks!

**Comment by MatinF** [comment]
Thank you for your support. I am not sure what happened, but when I test the setup now it works as it should. I apologize for the inconvenience regarding this and I'll be closing it now.

**Comment by gabor** [comment]
@MatinF no worries, i'm glad it works now!

**Comment by KanchiSaiHemanth123** [comment]
Time Series panel not working in Grafana 8.1.2 version without time field in data query.Please help me.

**Comment by gabor** [comment]
hi @KanchiSaiHemanth123 , please create a new separate github issue for your problem, and please describe there the problem in more detail (what influxdb version did you use, what flux query did you use, in general, how to reproduce the problem).
