### ISSUE TITLE
Multiple series error in single stat

### ISSUE THREAD

**Issue by gsaray101** [grafana/grafana#3587]
trying to add single stat with multi series. For example, I am trying use single stat panel with multiple server cpu usage and receiving "multiple series error". This is not allowed?

I am trying to look at multiple servers cpu usage, if any of them breaches 80%, I need that single stat panel to turn red, is this possible or this would only work with one server cpu usage?

**Comment by torkelo** [comment]
Singlestat only works with single series. But you can always query for the highest series  (if your time series database supports that)

**Comment by gsaray101** [comment]
using elasticsearch as the data repository, would it work on ES?

**Comment by gsaray101** [comment]
I think I got it, thank you
