### ISSUE TITLE
Color the bolt symbol for annotations

### ISSUE THREAD

**Issue by volter** [grafana/grafana#3590]
There is no visual feedback in the annotation list or the actual annotation picker on the dashboard which color matches which annotation.

I simply added a style="color:{{annotation.iconColor}}" in public/app/partials/submenu.html and public/app/features/annotations/partials/editor.html. If you are fine with this approach, I can make a pull request! Whether the icon or the line color is used, is a topic for debate, I guess.

![annotation_color](https://cloud.githubusercontent.com/assets/1042313/11976732/aa9e691e-a97b-11e5-8ee1-6514c967ecaf.png)

**Comment by torkelo** [comment]
good idea!

**Comment by torkelo** [comment]
@mattttt

**Comment by mattttt** [comment]
I like this idea a lot, nice work @volter ! I believe we should use icon color, not line color.

Excited to see this PR, I think it'll help a lot.

**Comment by bergquist** [comment]
Nice! 

Perhaps we should assign different default colours for annotations? like the graphs panel time serie. With this PR people have to change the icon colours by them self before having multiple colours. I think few people will discover that. 

@volter @mattttt @torkelo

**Comment by volter** [comment]
I guess random defaults are an interesting idea. I think people will discover it though, once they color their annotations differently.

**Comment by mattttt** [comment]
I support the automatic selection of default colors, primarily because it extends the behavior on the graph series. :+1:

**Comment by volter** [comment]
I see a bit of a regression with 4.x releases here, because there no longer is a bolt symbol on the dashboard. Hence you again don't know which checkbox belongs to which colour.

**Comment by thewolf** [comment]
+1

**Comment by volter** [comment]
Can we maybe re-open this or do you want a separate ticket?
