### ISSUE TITLE
Getting data from all indexes

### ISSUE THREAD

**Issue by AndroidHitchhiking** [grafana/grafana#35901]
I am using grafana v8.X and successfully added the elastic search indexes in data source. Now whenever I am displaying table from json response even though I have a specific index selected in dropdown but in query index is always blank and getting the data from all the indexes

![image](https://user-images.githubusercontent.com/16745242/122449780-3d81ba00-cf74-11eb-937f-0986b001bb0c.png)

![image](https://user-images.githubusercontent.com/16745242/122449704-2b078080-cf74-11eb-85bf-ef4883e1c98e.png)

**Comment by torkelo** [comment]
can you show your data source settings?

**Comment by AndroidHitchhiking** [comment]
Below is datasource setting for one index 
![image](https://user-images.githubusercontent.com/16745242/122475639-f5be5b00-cf92-11eb-90f1-58643e00be1c.png)
![image](https://user-images.githubusercontent.com/16745242/122475692-08d12b00-cf93-11eb-8569-3f58bca33801.png)

**Comment by AndroidHitchhiking** [comment]
Below are the settings for one index
![image](https://user-images.githubusercontent.com/16745242/122477616-07553200-cf96-11eb-991b-16f54e12cad1.png)
![image](https://user-images.githubusercontent.com/16745242/122477642-13d98a80-cf96-11eb-8f67-d563fc03cb99.png)

**Comment by Elfo404** [comment]
Hello @AndroidHitchhiking, 
you need to specify the index you want to query in the `Index name` field, in your case I assume `specs-summary-temp-test`.

Also, maybe this can help: https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#index-settings
