### ISSUE TITLE
Status History, Status TimeLine: Enhancement requests

### ISSUE THREAD

**Issue by baur** [grafana/grafana#35900]
First of all, thank you for the long-awaited  Status History, Status TimeLine panels, they are very cool!!!

**What would you like to be added**:

In my case

Query1
`select time, value as Device1 from table order by time`

Query2
`select time, value as Device2 from table order by time`

![image](https://user-images.githubusercontent.com/2898361/122446210-37b3c500-cfc4-11eb-91fa-2e5329132387.png)

1. Hide word suffix 'result' from alias name (see picture)
2. Add a column to group by instead of adding new query series for each Device
3. Alias name from DB table (in MSSQL DS alias name is column name)
4. Auto sort by time

**Why is this needed**:
- suffix 'result' is too long
- It's too hard to add queries to each device, I see in InfuxDB is only one query (play.grafana.com)
- I cant select the Device name from a table, instead I have to specify this as the column name, I see that's no problem for InfuxDB like DS

**Environment**:
- Grafana version: v8.0.2 (5c5d45e19f)
- Data source type & version: MSSQL
- OS Grafana is installed on: Windwos 10
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
Can you expand your queries? Have you specified the results alias? can you not remove that? 

> Add a column to group by instead of adding new query series for each Device

Why not combine all into one query that returns multiple columns? (all devices?) the panel can handle it. 

> Alias name from DB table (in MSSQL DS alias name is column name)

but in your query there is `as Device1` where is results coming from? 

> Auto sort by time

This is better done in the query and in the SQL query engine 

> I cant select the Device name from a table, instead I have to specify this as the column name, I see that's no problem for InfuxDB like DS

I do not understand this, select from table???

**Comment by baur** [comment]
Sorry, I understand it, Will try pivot query.
In my case all data in one  column

**Comment by baur** [comment]
Panel cant manage one query 

`
{
  "id": 735,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 24,
    "h": 8
  },
  "type": "status-history",
  "title": "Panel Title",
  "targets": [
    {
      "refId": "A",
      "format": "table",
      "alias": "",
      "rawSql": "with t as (\r\nselect DATEADD(hour,0, cast(cast(getdate() as date) as datetime)) as time \r\nunion all select DATEADD(hour,3, cast(cast(getdate() as date) as datetime)) as time \r\nunion all select DATEADD(hour,4, cast(cast(getdate() as date) as datetime)) as time \r\nunion all select DATEADD(hour,5, cast(cast(getdate() as date) as datetime)) as time \r\nunion all select DATEADD(hour,6, cast(cast(getdate() as date) as datetime)) as time )\r\nselect time, 'device1' deviceName, 10 as value from t\r\nunion all select time, 'device2', 11 from t\r\norder by time"
    }
  ],
  "options": {
    "showValue": "auto",
    "rowHeight": 0.9,
    "colWidth": 0.9,
    "legend": {
      "displayMode": "list",
      "placement": "bottom"
    },
    "tooltip": {
      "mode": "single"
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 1,
        "fillOpacity": 70
      },
      "color": {
        "mode": "thresholds"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "mappings": []
    },
    "overrides": []
  },
  "datasource": null
}
`

**Comment by torkelo** [comment]
you can do that with one query, you might need some join  / sub query so that all the different devices get's their own column

**Comment by torkelo** [comment]
With SQL this stuff is a bit harder but you cannot compare SQL to say influx, influx is specifically built for these types of queries. SQL is soo much more generic so it requires a bit more from you to shape the data

**Comment by torkelo** [comment]
can you open panel inspector / JSON tab / DataFrame structure?

**Comment by baur** [comment]
> you can do that with one query, you might need some join / sub query so that all the different devices get's their own column

Thank you, StatusHistory done!

![image](https://user-images.githubusercontent.com/2898361/122540428-742a0400-d04a-11eb-9204-3ee2de658cf1.png)

result

![image](https://user-images.githubusercontent.com/2898361/122540579-9a4fa400-d04a-11eb-85ab-f49ddd2f26c1.png)

**But with State TimeLine problems!**
Because after pivot query certainly appears null rows 

![image](https://user-images.githubusercontent.com/2898361/122549483-595c8d00-d054-11eb-9a9e-cdc8f361f3af.png)

and they affect the result

![image](https://user-images.githubusercontent.com/2898361/122549678-96288400-d054-11eb-9f7e-a9f5a482782a.png)

**Comment by baur** [comment]
State TimeLine JSON

```
{
  "id": 739,
  "gridPos": {
    "h": 8,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "state-timeline",
  "title": "Panel Title",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "lineWidth": 0,
        "fillOpacity": 70
      },
      "color": {
        "mode": "thresholds"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          }
        ]
      },
      "mappings": [
        {
          "options": {
            "Device1": {
              "color": "red",
              "index": 0
            },
            "Device2": {
              "color": "green",
              "index": 1
            }
          },
          "type": "value"
        }
      ]
    },
    "overrides": []
  },
  "options": {
    "mergeValues": true,
    "showValue": "auto",
    "alignValue": "left",
    "rowHeight": 0.9,
    "legend": {
      "displayMode": "list",
      "placement": "bottom"
    },
    "tooltip": {
      "mode": "single"
    }
  },
  "targets": [
    {
      "alias": "",
      "format": "table",
      "rawSql": "with t as (\r\nselect           DATEADD(hour,0, cast(cast(getdate() as date) as datetime)) as time,'Device1' as  Line1 ,'Device1' Line2\r\nunion all select DATEADD(hour,1, cast(cast(getdate() as date) as datetime)) as time ,'Device2' as  Line1 ,null as Line2\r\nunion all select DATEADD(hour,2, cast(cast(getdate() as date) as datetime)) as time ,'Device1' as  Line1 ,'Device2' Line2\r\nunion all select DATEADD(hour,3, cast(cast(getdate() as date) as datetime)) as time ,null as  Line1 ,'Device1' Line2\r\nunion all select DATEADD(hour,4, cast(cast(getdate() as date) as datetime)) as time ,'Device1' as  Line1 ,'Device2' Line2\r\nunion all select DATEADD(hour,5, cast(cast(getdate() as date) as datetime)) as time , null     as  Line1, 'Device1' Line2\r\nunion all select DATEADD(hour,6, cast(cast(getdate() as date) as datetime)) as time ,'Device2' as  Line1 ,null Line2\r\nunion all select DATEADD(hour,7, cast(cast(getdate() as date) as datetime)) as time ,'Device1' as  Line1 ,'Device2' Line2\r\n)\r\nselect [Util].[fConvertLocalDateTimeToUTC](time) as t1, Line1 as L1, Line2  as L2 from t\r\n\r\n\r\n",
      "refId": "A"
    }
  ],
  "datasource": null
}
```

**Comment by baur** [comment]
It would be great if panels can manage data without any pivot query, just with group by field (with alias names)

Because any data writes with rows
