### ISSUE TITLE
Documentation Update Request: Timestream docs missing IAM policy

### ISSUE THREAD

**Issue by davidnewhall** [grafana/grafana#35904]
## **What would you like to be added**:

Please update the [Timestream plugin documentation](https://grafana.com/grafana/plugins/grafana-timestream-datasource/) to include the plugin's required IAM permissions.

This statement is on the Timestream plugin docs page:
> The Timestream plugin authentication system matches the standard Cloudwatch plugin system. See [the grafana documentation](https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#authentication) for authentication options and setup.

However, the standard CloudWatch plugin docs make no mention of Timestream, and using the example IAM policy on _that_ page leads to this error when adding a new Timestream data source:

> AccessDeniedException: User: `arn:aws:sts::11111:assumed-role/grafana-cloudwatch-read-only/1623954287185711362` is not authorized to perform: `timestream:DescribeEndpoints`

## **Why is this needed**:

There's no way to know which granular permissions Timestream uses.  As an example, the correct IAM policy was added to X-Ray recently: https://grafana.com/grafana/plugins/grafana-x-ray-datasource/

**Comment by achatterjee-grafana** [comment]
@sunker, can you help with this issue? Thanks!

**Comment by sunker** [comment]
The policies needed to access the timestream api:s are different from the ones that cloudwatch needs. @ryantxu can you chime in on this one?

**Comment by davidnewhall** [comment]
Ridiculous.
