### ISSUE TITLE
Alert contact points are shared across organizations

### ISSUE THREAD

**Issue by lafrech** [grafana/grafana#35925]
**What happened**:

I migrated to 8.0 and activated `ngalerts`.

All contact points (even newly created) are shared across organizations.

**What you expected to happen**:

I expected contacts to be isolated in their own organization.

**How to reproduce it (as minimally and precisely as possible)**:

Use 8.x + `ngalerts`. Create two orgs. Create a contact in org 1. Switch to org 2. Contact is there.

**Anything else we need to know?**:

IIUC, organizations are meant to use a single install to isolate independent groups (multi-tenancy). Those shouldn't see each other. Sharing contact info is a leak.

**Environment**:
- Grafana version: v8.0.2 (5c5d45e19f)
- OS Grafana is installed on: Linux Debian

**Comment by lafrech** [comment]
Worse. Notifications are also shared. I didn't try but it looks like a contact from an organization could be notified for an alert on data from another organization if the label matches.

This is also the case due to the contact being default contact.

To sum things up, AFAIU, alerts are isolated (can only be created on data in the org) but notification contacts and policies are not.

Either I'm totally misunderstanding something, either this is a serious leak in the organization isolation feature.

**Comment by gotjosh** [comment]
Fixed by https://github.com/grafana/grafana/pull/37320
