### ISSUE TITLE
References links to external span doesn't work

### ISSUE THREAD

**Issue by krikz** [grafana/grafana#35939]
**What happened**:
I've added linked traces to span (in dotnet)

`
            using var activity = activitySource.StartActivity($"Orders loader process", ActivityKind.Internal, Activity.Current.Context,
                links: unionOrders.Select(_ => _.Traceparent).Distinct()
                                  .Select(_ => new ActivityLink(_.GetActivityContextFromTraceparent())).ToArray());
`

this links appeared in References block, but links to external traces pointed to current page

![image](https://user-images.githubusercontent.com/5272634/122548188-b0a13400-d039-11eb-8ecd-724aff39901c.png)

**How to reproduce it (as minimally and precisely as possible)**:

Add link to span from other trace

**What you expected to happen**:

link will open trace in new tab

**Anything else we need to know?**:

In grafana sources I found createLinkToExternalSpan, it look like function hasn't implementation
`  render() {
    const {
      setSpanNameColumnWidth,
      updateNextViewRangeTime,
      updateViewRangeTime,
      viewRange,
      createLinkToExternalSpan,
      traceTimeline,
      theme,
      ...rest
    } = this.props;
    const { trace } = rest;
    const styles = getStyles(theme);
    return (
      <ExternalLinkContext.Provider value={createLinkToExternalSpan}>`

#23047

**Environment**:
- Grafana version: Grafana v7.5.7 (91de51771c)
- Data source type & version: Tempo grafana/tempo:007c31d5
- OS Grafana is installed on: docker image
- User OS & Browser: windows 10 chrome 91.0.4472.101

#

**Comment by connorlindsey** [comment]
This bug will be fixed in 9.1.0 by this PR: https://github.com/grafana/grafana/pull/50113
