### ISSUE TITLE
Dynamic variable assign

### ISSUE THREAD

**Issue by entrop92** [grafana/grafana#3593]
Hi!

I'm building a huge grafana 2.6.0 + influxdb 0.9 setup. 

I'm stuck with a variable problem:
I define two variables:
![service](https://cloud.githubusercontent.com/assets/16414622/11977459/26dc300c-a994-11e5-9df3-8051a023db80.png)

and (please note - i have 4 values for "service" and 4 values for "ifAlias". Each "ifAlias" is assigned to it's "service" by the =~ /$service/
![alias](https://cloud.githubusercontent.com/assets/16414622/11977456/22dcbe36-a994-11e5-855f-8df2dcf805c8.png)

They "iAlias" variable is tied to the "service" variable. Some regular expressions are applied to match the right values for "ifAlias".

This is how it should be: (I have selected a specific value for "service")
![single](https://cloud.githubusercontent.com/assets/16414622/11977519/a30f3f16-a994-11e5-94a7-bdc6df2c768c.png)
The "ifAlias" is mentioned in the "Title" and shows some info according to the selected "service".

But if a select for "service" ALL (as you can see, the "Repeat Panel" uses the "service" variable), a get something strange:
![error](https://cloud.githubusercontent.com/assets/16414622/11977566/fc7ebf90-a994-11e5-9999-48282d01455c.png)
It would be great, if it would select the right value, referring to the variable value selected for the graph. Right now i can set just any value for "ifAlias" and it will apper next to "service" variable value in the "Title". it's a bug or I'm missing something?

Best regards, Petr

**Comment by torkelo** [comment]
I am not sure I understand it looks correct from the screenshot. the first title says check-port23 and the second panel contains "check-port25" , you repeated the panel based on service variable so the panel repeated twice for each of those values.
