### ISSUE TITLE
State timeline colors are not correctly mapped 

### ISSUE THREAD

**Issue by colega** [grafana/grafana#35934]
**What happened**: I created a State Timeline visualization on a metric that reports timestamps the applications deployed somewhere. Then I choose the `Red-Yellow-Green (by value)` color scheme.

**What you expected to happen**: I'd expect to have different colors for different version, but I got red for the first version and green for the next ones.

![image](https://user-images.githubusercontent.com/1511481/122539502-f7862e00-d027-11eb-9fee-138113a62699.png)

**How to reproduce it (as minimally and precisely as possible)**: 
 - Query a metric that reports unix timestamps in milliseconds
 - Select `State timeline` visualization
 - Select `Red-Yellow-Green (by value)` color scheme

**Anything else we need to know?**:

**Environment**:
- Grafana version: `8.1.0-pre`, `8.0.2`
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux, Mac 
- User OS & Browser: Chrome 91 on Mac
- Grafana plugins: None

----

I tried to debug this, and I saw that in `scale.ts` the function [`getMinMaxAndDelta`](http://github.com/grafana/grafana/blob/7f882eea05d7054407cf2c1fa05cbfe38414aa05/packages/grafana-data/src/field/scale.ts#L67-L70) returns default 0-100 values, because `Field.type` is `time` 

```ts
function getMinMaxAndDelta(field: Field): NumericRange {
  if (field.type !== FieldType.number) {
    return { min: 0, max: 100, delta: 100 };
  }
```

That makes `FieldValueColorCalculator` [receive](http://github.com/grafana/grafana/blob/7f882eea05d7054407cf2c1fa05cbfe38414aa05/packages/grafana-data/src/field/fieldColor.ts#L181-L181) unexpected values, in the case of the screenshot above, it receives `0`, `0.9901647133354451`, `1`, `16240021650`, `16240027500` and `16240027950` values as `percent` (console log, I guess those correspond to different fields, but you get the idea that it's not right)

**Comment by torkelo** [comment]
Not sure I understand your data, are you visualizing time values on a time axis? (double time?)

**Comment by colega** [comment]
Yes, I was visualizing time values (timestamps which are _versions_ for us) on a time axis (when each version was deployed on each env)

 I decided to prepare an example dataset to present this clearer, where data looks like this:

![image](https://user-images.githubusercontent.com/1511481/122554212-fc9fa900-d038-11eb-8726-72f110190b5f.png)

And I realized that it's actually rendered correctly:

![image](https://user-images.githubusercontent.com/1511481/122554307-1a6d0e00-d039-11eb-9c63-fefc859110c3.png)

Then (and thanks to the internal conversation) I saw that in my previous example the intermediate value is just too close to the max value, which makes it almost identical color when interpolated.

As discussed in parallel, this colorscheme doesn't seem to be very useful for this kind of data, so I'm going to propose a new unique-value-based colorscheme in a different issue, and will close this issue since there isn't actually any kind of bug.
