### ISSUE TITLE
CloudWatch datasource with multiple queries reorders randomly on every data refresh 

### ISSUE THREAD

**Issue by JesperCph** [grafana/grafana#35944]
When using the Cloudwatch datasource with multiple queries, it randomly reorders the dataset with every data refresh.

**What you expected to happen**:
The order of the output dataset is in the same order every time data is refreshed, based on query name or the order that the queries are defined.

**How to reproduce**:
Make a CloudWatch datasource that has at least to queries. save it and refresh the data. There more queries the easier it is to reproduce.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: CloudWatch 
- User OS & Browser: Windows 10, Google Chrome 91.0.4472.106

In the recorded video, i have set it to refresh data every 5s.
![ezgif com-gif-maker](https://user-images.githubusercontent.com/86109175/122557156-b3e9ef00-d03c-11eb-833b-33166fe15b6f.gif)

**Comment by sunker** [comment]
I'm afraid this is not something we can solve in the CloudWatch data source. It needs to be solved in the data source plugin SDK. See this issue: https://github.com/grafana/grafana-plugin-sdk-go/issues/366

**Comment by sunker** [comment]
Will close this issue since it can't be solved in this data source. Feel free to re-open if you feel like @JesperCph
