### ISSUE TITLE
State timeline: Color same dynamic string state with same color

### ISSUE THREAD

**Issue by Legion2** [grafana/grafana#35945]
**What would you like to be added**: Color option to color dynamic string based state. For example, the state represents a version name of deployed software component. Each timeseries represent a different device. Every time a new version is released the state space increases. I want to color the state based on the version. So that it is easy to see which devices have the same version over time and when the version changed.

**Why is this needed**: The Color Schema classic palette produces random colors for each series, but all states for a series have the same color. Color by value currently does not work for string states such as version strings. Value mapping can not be used, because the set of possible states constantly increases.

How it currently looks like with the classic palette:
![image](https://user-images.githubusercontent.com/12752323/122556862-505fc180-d03c-11eb-8b10-d56034a8f3b2.png)

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/35947

**Comment by torkelo** [comment]
closing it in favor of #35947
