### ISSUE TITLE
Dashboard variable shows as blank value after navigation

### ISSUE THREAD

**Issue by Noah-Sutton** [grafana/grafana#35957]
**What happened**: When using either the built in dashboard toolbar navigation or the navigation provided by the dashboard list plugin. My dashboard variable (query) populates as empty. Once I click on it the default value it is applied and the data loads as expected.

**What you expected to happen**: Navigation would not cause variable to populate as empty

**How to reproduce it (as minimally and precisely as possible)**: Go to dashboard, then navigate away using dashboard toolbar. Then navigate back to it by clicking dashboard in list. The first dashboard variable now shows as blank.

**Environment**:
- Grafana version: grafana-enterprise:7.5.6
- Data source type & version:  Microsoft SQL Server
- User OS & Browser: Windows 10 and Google Chrome

**Comment by lux4rd0** [comment]
Looks similar to my issue... https://github.com/grafana/grafana/issues/35471 - will watch for updates. :)

**Comment by torkelo** [comment]
indeed
