### ISSUE TITLE
Docs feedback: /sharing/share-panel.md

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#35956]
https://grafana.com/docs/grafana/latest/sharing/share-panel/#embed-panel

Since the decision was made to no longer allow/enable anonymous access for HOSTED Grafana, this page should have a note to that effect in the 'Embed Panel' section:

![image](https://user-images.githubusercontent.com/9828569/122604538-f4d90800-d02a-11eb-8c3b-21abab22870a.png)

Something like "Note: Anonymous access is only configurable in on-prem installations. The hosted service does not allow..."

**Comment by zuchka** [comment]
@oddlittlebird

**Comment by oddlittlebird** [comment]
@pkolyvas and @richardqlam, can you confirm this?

@achatterjee-grafana, FYI

**Comment by pkolyvas** [comment]
@oddlittlebird @zuchka @achatterjee-grafana @mlewald 

Indeed, Anonymous Access is not available for Grafana Cloud, we recently removed outdated language about contacting support here: https://github.com/grafana/grafana/pull/35687

This is likely related.

**Comment by achatterjee-grafana** [comment]
Fixed.
