### ISSUE TITLE
Time Series: Cannot read property 'type' of undefined

### ISSUE THREAD

**Issue by lux4rd0** [grafana/grafana#35953]
**What happened**: Zooming in or out, or changing time ranges, causes the Time Series panel to error with:

```
TypeError: Cannot read property 'type' of undefined
    at Fc (TooltipPlugin.tsx:164)
    at na (react-dom.production.min.js:157)
    at Ba (react-dom.production.min.js:180)
    at Uu (react-dom.production.min.js:269)
    at Os (react-dom.production.min.js:250)
    at _s (react-dom.production.min.js:250)
    at ws (react-dom.production.min.js:250)
    at ds (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

In react-dom.production.min.js:216 

The graph does not render until a reload of the page happens.

**What you expected to happen**: No error. Graph displayed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.2 (5c5d45e19f)
- Data source type & version: Loki
- OS Grafana is installed on: Docker alpine
- User OS & Browser: MacOS - Chrome Version 91.0.4472.106 (Official Build) (x86_64)
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
thanks for reporting this!

**Comment by pkolyvas** [comment]
I think an issue I just filed with the Satus History panel might be related. Same/similar error: https://github.com/grafana/grafana/issues/35994

**Comment by ashharrison90** [comment]
had a look at recreating. some hopefully useful info:
- seems to only affect loki data sources
- seems to only occur when zooming **and the tooltip is visible**. so either hover a data point at your end zoom if tooltip mode is `single`, or switch tooltip mode to `all`
- i can't reproduce when just changing time ranges via the dropdown

**Comment by lux4rd0** [comment]
Yep - when I see this - it's almost always a Loki data source. However - just now, I picked up my first "Cannot read property 'type' of undefined" with an InfluxDB data source. I was clicking/dragging for a zoom functioning (with tooltips) and it popped up. Running Grafana Enterprise v8.0.3 (cae5c5e46b).

**Comment by AlexLast** [comment]
Also seeing this for the Loki datasource 👍

**Comment by Tristan971** [comment]
Just had it against a prometheus datasource.

Changed a timeseries panel from 3h to 90d, then selected a smaller range with the cursor. Breaks every single time with:
```
react-dom.production.min.js:216 TypeError: Cannot read property 'type' of undefined
    at Fc (TooltipPlugin.tsx:164)
    at na (react-dom.production.min.js:157)
    at Ba (react-dom.production.min.js:180)
    at Uu (react-dom.production.min.js:269)
    at Os (react-dom.production.min.js:250)
    at _s (react-dom.production.min.js:250)
    at ws (react-dom.production.min.js:250)
    at ds (react-dom.production.min.js:243)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:18)
```

happens on both 8.0.2 and 8.0.3

**Comment by ashharrison90** [comment]
k i've had another look

the problem occurs when you're viewing a graph with multiple series, and you zoom into a region of the graph where some of the series don't occur. in that case, there's a possibility that the `focusedSeriesIdx` is could be out of range of the `data.fields` array.

that means it could occur for any data source, not just Loki. 

i'll put a PR in with a sort of band aid fix, basically just not to render the tooltip if that occurs. 
we _could_ also try to detect when the data changes, and adjust the `focusedSeriesIdx` to the new value. but i'm not sure how we'd do that as there doesn't seem to be a unique identifier for each series, and it would require keeping the old data around i think.
