### ISSUE TITLE
AmazonMQ metrics are not imported properly

### ISSUE THREAD

**Issue by gabriellisboa** [grafana/grafana#35955]
**What happened**:
AmazonMQ RabbitMQ metrics that are found under **Node Metrics by Broker** on Cloudwatch are missing in Grafana

**What you expected to happen**:
Have all available metrics from Cloudwatch on Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
- ```docker run -d -p 3000:3000 grafana/grafana```;
- Configure Cloudwatch integration with valid credentials;
- Try to create a dashboard to visualize **SystemCpuUtilization**;

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Cloudwatch (built in)
- OS Grafana is installed on: Grafana docker image
- User OS & Browser: macOS Catalina
- Grafana plugins: Cloudwatch data source
- Others:

Prints that shows that some metrics are being shown and others are not:

<img width="1439" alt="Screen Shot 2021-06-18 at 15 04 14" src="https://user-images.githubusercontent.com/8193904/122600904-de40aa00-d046-11eb-9167-c6102e6ed835.png">
<img width="1439" alt="Screen Shot 2021-06-18 at 15 02 30" src="https://user-images.githubusercontent.com/8193904/122600915-e1d43100-d046-11eb-99a1-74497b30e24a.png">

**Comment by henderjm** [comment]
Also seeing this yesterday on version 7.5.*

In my case also the dimension values were not auto populated either.

**Comment by andresmgot** [comment]
from https://docs.aws.amazon.com/amazon-mq/latest/developer-guide/security-logging-monitoring-cloudwatch.html seems that we are missing a couple of dimensions: `Node` and `Virtual host`. Will add that in a PR.

Also, not sure if it's the issue you are hitting @henderjm but depending on the metric, some dimensions will be available and some others don't (as listed in the docs above).
