### ISSUE TITLE
Thresholds don't work by 'Ad field by calculation'

### ISSUE THREAD

**Issue by NvBgm** [grafana/grafana#35958]
The tresholds was always working in version V8.01
Not in V8.02 and v8.03
See video for more explanation..

**Environment**:
- Grafana version: v8.03
- Data source type & version: MSQL
- OS Grafana is installed on: Rasberry

https://user-images.githubusercontent.com/8125819/122616129-19b09800-d08a-11eb-85cf-f299535fe38d.mp4

**Comment by torkelo** [comment]
you are just missing specifying min and max for the BTS row, by default the auto min and max is table wide (for all columns)

We know this is not great (auto is for all columns), have an issue for that https://github.com/grafana/grafana/issues/29881
