### ISSUE TITLE
Data sources getting created in Main org even after giving org_id in API

### ISSUE THREAD

**Issue by sanjaynambiar** [grafana/grafana#3595]
Hi,
Whats the best way to create data sources automatically. Using Grafana 2.5 Version. We have tried web API using admin username and password. But its creating datasources in Main Org even if we provide the correct org id.  Because of this tried using the API keys(have to rely on UI for creating the API keys) and seems its working correctly. Is there a way to create the API keys automatically.

Commands used:
curl 'http://admin:xxxxx@127.0.0.1:3000/api/datasources/' -X POST -H 'Content-Type: application/json;charset=UTF-8' --data-binary '{"org_id":5,"name":"name","type":"graphite","url":"<url>","access":"proxy"}’'
 
even if we give org id as 5 data source is getting created in org 1.

**Comment by torkelo** [comment]
you need to switch to an org before creating the data source, a data source is created for the authenticated users active organization. 
http://docs.grafana.org/reference/http_api/#switch-user-context
