### ISSUE TITLE
Clock panel background color no longer applied -- always "gray"

### ISSUE THREAD

**Issue by Codelica** [grafana/grafana#35954]
**What happened**:

Clock panel no longer honors its "Background Color" setting.  It's always set to `background-color: gray` regardless of settings.

**What you expected to happen**:

Background color setting should be applied. 

**How to reproduce it (as minimally and precisely as possible)**:

Just make a Clock panel in Grafana 8.0.3 and try to apply a background color or make it transparent. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Not relavant
- OS Grafana is installed on: Ubuntu 20
- User OS & Browser:  Chrome, Safari, Brave, etc...
- Grafana plugins: Not relavant

**Comment by torkelo** [comment]
Update clock panel to latest version
