### ISSUE TITLE
TimeSeries: Support threshold and other by value color schemes to color line by value 

### ISSUE THREAD

**Issue by TheGreyDiamond** [grafana/grafana#35968]
**What would you like to be added**:
Allow the "From thresholds" colour palette for Timeseriers Graphs.

**Why is this needed**:
To make things like this possible (which is currently impossible)
![An image of a graph](https://cdn.thegreydiamond.de/img/2021/06/20/2021-06-20_20-08-42-bbdf0778-3c38-4fbf-8513-a3e314d56cd6.png )

**Comment by leeoniya** [comment]
like this ;) ?

https://github.com/grafana/grafana/pull/35910

**Comment by TheGreyDiamond** [comment]
Oh damm. Yes. I hoped I looked enough but I didn't. Wooops
