### ISSUE TITLE
Grafana 8 InfluxDB retention selection problem

### ISSUE THREAD

**Issue by cicciopizza** [grafana/grafana#35966]
**What happened**:
Problem with InfluxDB retention selection when multiple retention is present on db.
I have a db "test" with 2 retention: autogen and RP1
the combobox concatenates the 2 retention: autogenRP1

**What you expected to happen**:
combobox with retention list:
autogen
RP1

**How to reproduce it (as minimally and precisely as possible)**:
1. create database test (influxdb 1.7.8) 
2. CREATE RETENTION POLICY "RP1"  ON test DURATION 365d REPLICATION 1
> show retention policies on test
```
name    duration  shardGroupDuration replicaN default
----    --------  ------------------ -------- -------
autogen 0s        168h0m0s           1        true
RP1     8760h0m0s 168h0m0s           1        false
```

When I select the retention in the combobox I see a single string with the 2 concatenated retention autogenRP1 (see image)

![image](https://user-images.githubusercontent.com/26459829/122669754-1c60d980-d1bf-11eb-8551-154fd389d0ed.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: influxdb 1.7.8
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Ubuntu 20.04.2 LTS - Chrome 
- Grafana plugins: ACE.SVG, D3 Gauge and standard plugin
- Others:

**Comment by gabor** [comment]
hi @cicciopizza we will fix this, as a workaround for now you can write the retention-policy name into the field to select it.
