### ISSUE TITLE
TimeSeries: data cleaning introduced streaming performance regression

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#35962]
after disabling source maps and compression (terser) in webpack production builds i'm able to get line-level profile feedback.

it looks like the data cleaning pass introduced in https://github.com/grafana/grafana/pull/35638 had a large impact on streaming performance.

we should detect when we're in "append" mode and only clean the new data rather than doing it for the entire dataset on every render (related: https://github.com/grafana/grafana/pull/35465).

![image](https://user-images.githubusercontent.com/43234/122649771-25857400-d0f5-11eb-9241-ea63e81009c3.png)
![image](https://user-images.githubusercontent.com/43234/122649717-c6bffa80-d0f4-11eb-8200-b604facf46d4.png)

**Comment by torkelo** [comment]
@leeoniya can we close this or move milestone?
