### ISSUE TITLE
TimeSeries show wrong values #35689

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#35975]
**What happened**:
I updated Grafana to 8.0.2 and Grafana shows wrong values

**What you expected to happen**:
Fix this issue
**How to reproduce it (as minimally and precisely as possible)**:
Please add empty panel
Add code MS SQL
```
SELECT convert(date,'2021-06-12 06:00',102) time,3 'Ilość dostaw LK'
union ALL
SELECT convert(date,'2021-06-13 06:00',102) time,2 'Ilość dostaw LK'
union ALL
SELECT convert(date,'2021-06-14 06:00',102) time,1 'Ilość dostaw LK'
union ALL
SELECT convert(date,'2021-06-10 06:00',102) time,2 'Ilość dostaw LK'
```
Select visualization Time Series
Set Graph style: Bar, Tooltip mode: All
If you hover mouse on the 14 June then will show you value 3 and if you hover mouse on the 10 June you see the same tooltip and the same value
![122178774-2dd87780-ce87-11eb-9831-7a6aa8b974c9](https://user-images.githubusercontent.com/73607094/122709607-e8d58c00-d25e-11eb-92d1-aef3a85a5b72.png)
and If I hover mouse after 15 June then shows me value from 10 June
![122178930-53fe1780-ce87-11eb-8bbc-d83f248257e3](https://user-images.githubusercontent.com/73607094/122709620-ee32d680-d25e-11eb-880b-dacb857a4806.png)

**Comment by torkelo** [comment]
What if you order the data by time asc?

**Comment by deejayluk** [comment]
If I adding order by time asc, it's okay
The data should be sorted before or we must adding order by to work properly :)

**Comment by dprokop** [comment]
@deejayluk - @torkelo is right here. Time series panel expects the data coming back from the query to be sorted by time.

Looking at the data you are trying to plot it seems like you have a non-observability use case that you are trying to address. Can you elaborate a little bit more on your use case? I'm happy to talk with you on our slack if that's fine with you.

**Comment by deejayluk** [comment]
> @deejayluk - @torkelo is right here. Time series panel expects the data coming back from the query to be sorted by time.
> 
> Looking at the data you are trying to plot it seems like you have a non-observability use case that you are trying to address. Can you elaborate a little bit more on your use case? I'm happy to talk with you on our slack if that's fine with you.

dziękuje Dominik, in the previous version of Grafana I didn't use sorting and data was correctly.
It's not a problem for me to using sorting :)
