### ISSUE TITLE
[Grafana V8.0.2 to V8.0.3] - Log spam when grafana is open

### ISSUE THREAD

**Issue by S0ulHunt3r** [grafana/grafana#35988]
**What happened**:
Have log spam with info, example:
![GrafanaLog](https://user-images.githubusercontent.com/916396/122756795-cbb8b180-d28e-11eb-9d0a-5a77e4bb4fba.png)

On chrome i have the errors:
![GrafanaConsoleErrors](https://user-images.githubusercontent.com/916396/122756916-eb4fda00-d28e-11eb-8eeb-6e7966a2efac.png)

**What you expected to happen**:
I expect not having this logs or errors.

**How to reproduce it (as minimally and precisely as possible)**:
I have this configuration behind nginx as proxy, i just upgraded from version 7.5.7 to 8.0.2.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- OS Grafana is installed on: Redhat 7.6
- User OS & Browser: Windows 10 > Chrome
- Grafana plugins: Native Plugins
- Others:

**Comment by torkelo** [comment]
Are you using some http proxy? It looks like Grafana's websocket connection cannot be opened

**Comment by S0ulHunt3r** [comment]
I use nginx in front of grafana. Grafana has that configuration in place with context t-grafana.
Need to change something on nginx?

**Comment by S0ulHunt3r** [comment]
Hi, what more information is needed? I think i gave all.

**Comment by FZambia** [comment]
@S0ulHunt3r hello, Nginx can not proxy WebSockets by default, so you need to add some additional Nginx configuration. Like:

```
# this is required to proxy Grafana Live WebSocket connections.
map $http_upgrade $connection_upgrade {
  default upgrade;
  '' close;
}

server {
  # ... your config here

  location /t-grafana/ {
   # ... your config here
  }

  # Additionally proxy Grafana Live WebSocket connections.
  location /t-grafana/api/live {
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "Upgrade";
    proxy_set_header Host $http_host;
    proxy_pass http://t-grafana-server/;
  }
}
```

Also take a look at related [tutorial](https://grafana.com/tutorials/run-grafana-behind-a-proxy/)

**Comment by S0ulHunt3r** [comment]
Hi, i will disabled it because i dont use it. 
Tryed that config but still get the same error.

**Comment by S0ulHunt3r** [comment]
Thanks for the help.
