### ISSUE TITLE
How can I  disable new relative time in tooltip ?

### ISSUE THREAD

**Issue by toni-moreno** [grafana/grafana#3599]
From some days to now a relative time appeared 

![image](https://cloud.githubusercontent.com/assets/5883405/11985387/9825737e-a9c4-11e5-9241-90a717e2fe24.png)

and it seems no way to disable it.

![image](https://cloud.githubusercontent.com/assets/5883405/11985475/68eec8fc-a9c5-11e5-9d1a-e95b0a17ffd7.png)

IMHO all new features should be transparent to old dashboards and backwards compatible ( if posible).

There is any way to disable this new feature?

**Comment by utkarshcmu** [comment]
That is how relative_time was implemented initially but then we decided to make it compulsion.

See #2444

**Comment by bergquist** [comment]
Right now there is no way to disable it. And I dont think we should add one either. 

It wont be possible to add options for all new features or changes that appear. That's how software is bloated :)

I don't understand what you mean by "all new features should be transparent to old dashboards and backwards compatible" This change should not effect the dashboard json at all.
