### ISSUE TITLE
Timeseries panel only shows tooltip when mousing over the exact datapoint

### ISSUE THREAD

**Issue by gcbirzan** [grafana/grafana#35990]
**What happened**: When the datasource has null values, even with connected null values always, you need to mouse over the exact point (or, rather, half way between it and the null value, probably) in order for the tooltip to show. Even more hilariously, at some zoom levels some points are, probably, between exact pixels so you cannot get the value no matter what.

**What you expected to happen**: Just like the old graph panel, the tooltip should be shown when being between two data points with values. 

**How to reproduce it (as minimally and precisely as possible)**: Any influxdb query will show this problem as $__interval gets smaller. The recording is with datapoints every 30s and group by time(100ms)

**Anything else we need to know?**: [Screencap](https://birzan.org/~gcbirzan/grafana.gif)

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: InfluxDB, but the problem is not specific to it.
- OS Grafana is installed on: Linux
- User OS & Browser: Linux Firefox and Chrome, but it's not specific to any of these.
- Grafana plugins:
- Others:

**Comment by gcbirzan** [comment]
I think #35990 might be related to this.

**Comment by leeoniya** [comment]
probably will be fixed by https://github.com/grafana/grafana/pull/34552

**Comment by pprkut** [comment]
I'm still seeing this with 8.3.4, so #34552 did not fix it. The pull request mentions a 15px scanning limit, which is probably what's causing it for me (if I look at a larger window, points move closer to each other and I don't experience the issue)

![Screenshot_20220120_114645](https://user-images.githubusercontent.com/56635/150324349-c693baf7-f698-4af3-97d4-a657bb3f07ba.png)

**Comment by leeoniya** [comment]
we're working on adding control over hover proximity in https://github.com/grafana/grafana/pull/81421

we will likely change the default 15px non-null-value scanning behavior to Infinity, unless that proximity option is explicitly configured.
