### ISSUE TITLE
Explore Elasticsearch：every subsequent addition or deletion of characters will automatically trigger the search

### ISSUE THREAD

**Issue by tensorchen** [grafana/grafana#35993]
**What happened**:

**_When the last query result is empty_**, every subsequent addition or deletion of characters will automatically trigger the search

**What you expected to happen**:

Click to trigger search after input

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: Elasticsearch 
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome

**Comment by zuchka** [comment]
reproduced this on our play.grafana sandbox.

Seems similar in nature to [this recent Influx PR](https://github.com/grafana/grafana/issues/33464)

**Comment by Elfo404** [comment]
I'm assuming you are referring to the Lucene filter input, in that not having to press the run query button is the intended behavior.

I just tried it and the search is not executed on every keystroke, the change event is debounced correctly and the query is run only after ~500ms the last keystroke.
