### ISSUE TITLE
Pie Chart cuts off after 25 entries without possibility for configuration

### ISSUE THREAD

**Issue by schamock** [grafana/grafana#36003]
**What happened**:
When using the Pie Chart (not the old one) the visualization cuts off after 25 entries. This is true for the Pie Chart itself as well as for the legend. The percent value is also only calculated based on the first 25 entries.

**What you expected to happen**:
While the cut off seams to be reasonable for the chart, it isn't appreciated for the legend. The limit should be configurable and/or there should be an option the introduce an "other" entry, if there are too many.
This should also fix the problem, that the percentage value is not based on all entries but only on the first 25 which leads to wrong assumptions for datasets with >> 25 entries.

**How to reproduce it (as minimally and precisely as possible)**:
Just create a Pie Chart with > 25 categories.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3 cae5c5e46b
- Data source type & version: Flux (InfluxDB 2.0.7)
- OS Grafana is installed on: Raspberry Pi OS
- User OS & Browser: not really relevant (MacOS / Safari)
- Grafana plugins: none that are related to this
- Others: n/a

**Comment by ashharrison90** [comment]
hey @schamock 👋 

i've tried reproducing this on both the latest code in main and the 8.0.3 release but can't unfortunately.
here's what i see using the test data set:

![image](https://user-images.githubusercontent.com/20999846/122952658-0f3a1b00-d376-11eb-92a1-f3c9d0415503.png)

both the legend and pie chart seem to functioning fine. i've also tried with an influxdb source and that seems ok as well.

are there any other special steps needed to see this behaviour?

**Comment by schamock** [comment]
Hi @ashharrison90 meanwhile I assume that the root cause seems to be the same as in #30290 . It's a "special" behavior of the Flux handling. I tried different statements (inspired by the help in #30290), each of them had restrictions.

**First try:**
```
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "unbound_queries")
  |> group(columns: ["destination"], mode: "by")
  |> count()
  |> drop(columns: ["_start", "_stop"])
```
The results are not limited to 25, but there was no way to order the results by the result of "count" in the legend. That should be caused by the `group` statement which outputs the results unordered. The Flux command sort has no effect (see second try) and the sort transformation in Grafana also doesn't work in that case.

**Second try:**
```
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "unbound_queries")
  |> group(columns: ["destination"], mode: "by")
  |> count()
  |> group()
  |> drop(columns: ["_start", "_stop"])
  |> sort(columns: ["_value"], desc: true)
```
I introduced another `group()` to join the results within a single table. Therefore the `sort` command works again. But now the Pie Chart only consists of one portion. Therefore I changed "Value options" -> "Show" from "Calculate" to "All values". After that I can see the results ordered, but only the first 25. The rest is ignored.

**Third try:**
```
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "unbound_queries")
  |> group(columns: ["destination"], mode: "by")
  |> count()
  |> rename(columns: {_start: "_time"})
  |> drop(columns: ["_stop"])
  |> group(columns: ["destination"])
  |> sort(columns: ["_value"], desc: true)
```
That basically the workaround from #30290, but it results in the same behavior as the first try: Results are not limited, but no way to order them.

When switching to InfluxQL instead of Flux I had a similar problem as in try 1&3: I can see all results, but not ordered.

Conclusion:
* I found no way to see all results AND have them ordered in the legend at the same time
* The handling of Flux became somehow more complicated in Grafana 8.x (at least that's my subjective impression)
* I really miss the option to introduce the configurable "others" option that was present in the old pie chart (but that's only a side note)

Do I perhaps miss something obvious? Any help is highly appreciated! Thanks!

**Comment by torkelo** [comment]
So influx is not returning data in the right order or limiting the data?

Can you show the result in table view? 

Could be an influx issue?

**Comment by schamock** [comment]
Form what I can tell, InfluxDB works just fine (as intended and described in their documentation).
But I found another indicator, that something might be wrong within the new Pie Chart.
See the attached screenshot. The Pie Chart itself is sorted (biggest piece first followed by the second biggest ...) while the legend itself is completely unordered.
I used the variant one in my above comment to generate this chart.

![image](https://user-images.githubusercontent.com/75547446/123040877-c5dce080-d3f4-11eb-9ca8-1fda73a2e2ae.png)

**Comment by ashharrison90** [comment]
@schamock so there's a few different things to unpick here.

as far as i can tell, the pie chart will always be ordered from biggest to smallest piece, whereas the legend is presented as is. there's an argument that if the pie chart is always sorted, then the legend probably should be as well. i think that's probably a reasonable feature request.

the other thing is the limit of 25 you're seeing. i can confirm with option 2 (`All values`), that there is a default limit of 25. this applies to both pie charts and stat panels. i can't seem to find exactly where that default 25 limit is set, but a question for @torkelo: does it make more sense to show the default limit (25) as the placeholder instead of the max (5000)? e.g. change https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/stat/types.ts#L52?

so i think your option 2 works. the only thing you're missing is to override the hidden default max limit set in the panel options:

![image](https://user-images.githubusercontent.com/20999846/123074009-da2dd700-d40e-11eb-8df2-cf635c0d3829.png)

hope that helps!

**Comment by schamock** [comment]
@ashharrison90 Oh great, i didn't touch the limit because the shown default of 5000 seamed to be large enough ;) But this definitely did the trick!
