### ISSUE TITLE
Cannot use Loki-based Tempo search with long log lines

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#36004]
**What happened**:
Grafana 8.0.0 - Using Explore with the Tempo data source and set to use Loki log lines for discovery, long log lines aren't readable. They extend past the edge of the browser and there is no line wrap or horizontal scroll bar available. This makes it difficult to get the log context when looking for traces.

**What you expected to happen**:
Long lines are either wrapped or the frame allows horizontal scroll

**How to reproduce it (as minimally and precisely as possible)**:
While this happens with long lines, its just as easy to make it happen by resizing the browser window. You'll find that the log lines are cut off and there's no way to view the part off screen.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: Tempo/Loki - both at 1.0.0o
- OS Grafana is installed on: Docker (AWS Fargate)
- User OS & Browser: MacOS, Chrome Version 91.0.4472.106 
- Grafana plugins:
- Others:

**Comment by connorlindsey** [comment]
As a temporary workaround, you should be able to resize the table columns. By resizing the message column to the right, you should then be able to horizontally scroll the table. Repeat that a few times until you can see the entire message.
