### ISSUE TITLE
Dashboard JSON model unclear

### ISSUE THREAD

**Issue by hjet** [grafana/grafana#36008]
The [Dashboard JSON model](https://github.com/grafana/grafana/blob/main/docs/sources/dashboards/json-model.md) docs page (specifically `templating`) does not capture [this](https://gist.github.com/ingvarch/51ef3022738d3b9011b2ce802a605aaf#file-gistfile1-txt-L997) `query` object type.

Perhaps we should consider adding more detail to this page to avoid issues like [this](https://github.com/grafana-tools/sdk/pull/151), as it can be easy to mistakenly interpret `query`'s type as a `string`, when in reality its type varies depending on the template variable type.

**Comment by achatterjee-grafana** [comment]
@hjet, do you want to update the topic?
