### ISSUE TITLE
Lines not stacked with data from influxdb2

### ISSUE THREAD

**Issue by fredrikagr** [grafana/grafana#36015]
**What happened**: Lines are not stacked when selecting "Stack series": "Normal"

**What you expected to happen**: The lines to be stacked

**How to reproduce it (as minimally and precisely as possible)**: Create a new time series graph, with the following query:

    from(bucket: "monitor")
      |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
      |> filter(fn: (r) => r["_measurement"] == "test")
      |> filter(fn: (r) => r["_field"] == "count")
      |> group(columns: ["uuid"])

**Anything else we need to know?**: The data from InfluxDB2's data explorer is pasted below (csv), for some reason I couldn't attach it as a file.

With "Stack series" set to "Off" it looks like this:
![1](https://user-images.githubusercontent.com/62143568/122883273-52c46300-d33d-11eb-993c-0d8831555e82.png)

And with "Stack series" set to "Normal" it looks like this:
![2](https://user-images.githubusercontent.com/62143568/122883276-535cf980-d33d-11eb-88ae-bbe6a5f32682.png)

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: InfluxDB, version 2.0.5
- OS Grafana is installed on: RedHat Enterprise Linux 8.4
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: None that should apply to this issue (world panel is installed).
- Others:

Here is the CSV-formatted data mentioned above:

#group,false,false,true,true,false,false,false,false,false,false,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,long,string,string,string,string,string
#default,_result,,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,id,type,uuid
,,0,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T09:57:56Z,2,count,test,96448411029,end,KErBdyo2SNOYjNbqntDvNA==
,,0,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T09:28:53Z,2,count,test,96448411029,start,KErBdyo2SNOYjNbqntDvNA==
,,1,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T07:48:12Z,2,count,test,91554258680,end,KZwlT7i6Te6LYZ0dzG2LKg==
,,1,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T07:32:49Z,2,count,test,91554258680,start,KZwlT7i6Te6LYZ0dzG2LKg==
,,2,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T07:52:33Z,2,count,test,95425888921,end,lcaFojzZQGa7K8b6TDuC+Q==
,,2,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T06:28:09Z,2,count,test,95425888921,start,lcaFojzZQGa7K8b6TDuC+Q==
,,3,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T09:14:42Z,3,count,test,95705853317,end,qN63X5jnQGuGMY2SDFxrhQ==
,,3,2021-06-17T06:00:00Z,2021-06-17T11:00:00Z,2021-06-17T08:04:00Z,3,count,test,95705853317,start,qN63X5jnQGuGMY2SDFxrhQ==

**Comment by gabor** [comment]
hmm.. this seems to not be related to influxdb at the end (i was able to reproduce it with the test-data-source too).
@grafana/grafana-frontend-platform any ideas about this problem?

(just look at the 2 screenshots, stacked-off and stacked-on). there are 4 time-series in the visualization, all have 2 points. when you enable stacked-mode it becomes weird.)

**Comment by ploquets** [comment]
With zabbix as source, this weird stacking is occurring as well.
In version 7.4.0 was working fine.

Since then:
![image](https://user-images.githubusercontent.com/5149178/124683337-30852600-dea3-11eb-8a7f-59bc999a17fd.png)

**Comment by ploquets** [comment]
I posted this in https://github.com/grafana/grafana/issues/34912

**Comment by leeoniya** [comment]
looks like same situation as this: https://github.com/grafana/grafana/issues/35554#issuecomment-873671806

**Comment by torkelo** [comment]
stacking null values is not supported, in your flux query is there a way to inject 0 values for missing data points? so there is a consistent data point & value for every interval
