### ISSUE TITLE
BarChart: No room given to value even when show values is set to always 

### ISSUE THREAD

**Issue by baur** [grafana/grafana#36012]
**What happened**:

**What you expected to happen**:

Bar Chart value is not visible

![image](https://user-images.githubusercontent.com/2898361/122868149-61664680-d34c-11eb-8844-86b7f85ea584.png)

![image](https://user-images.githubusercontent.com/2898361/122868233-835fc900-d34c-11eb-8ff6-37fa163d20ea.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Open Sourcev8.0.2 (5c5d45e19f)
- Data source type & version: SQL
- OS Grafana is installed on: Windows10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you include you panel json? (min and max settings?)

**Comment by torkelo** [comment]
was able to replicate this, https://play.grafana.org/d/1o-mceRnk/bar-chart-no-room-for-value?orgId=1

Seem like there is no room for value when all bars are close to max

**Comment by RyuunosukeDS3** [comment]
Same happened to me on vertical bars.

![barchart](https://user-images.githubusercontent.com/31015675/124758207-b8e7e300-df04-11eb-9b3b-2f27b3bc507b.png)

Max as set to 1.5 and text size to 12.

**Comment by RyuunosukeDS3** [comment]
Any progress on this?

**Comment by ajinkya-mulay** [comment]
Same problem I am also facing 
![image](https://user-images.githubusercontent.com/95682162/235629622-00a2a0f3-5aca-4f68-8035-072f9ca26023.png)
