### ISSUE TITLE
TimeSeries: Tooltip should show milliseconds time when zoomed in far enough

### ISSUE THREAD

**Issue by zegerhoogeboom** [grafana/grafana#36017]
**What would you like to be added**:

In the old time series panel when zoomed in far enough the tooltip would show the milliseconds:
![image](https://user-images.githubusercontent.com/5371096/122901301-b6ef2300-d34d-11eb-9713-1dfb755ed778.png)

When using the new time series panel it doesn't show the milliseconds time in the tooltip:

![image](https://user-images.githubusercontent.com/5371096/122901519-e9008500-d34d-11eb-80fc-87ba90cc80e2.png)

**Why is this needed**:

Having the milliseconds in the tooltip is very useful to me as I'm analyzing data on a small time windows where milliseconds matter.

**Comment by torkelo** [comment]
When you say legend you mean tooltip?

**Comment by zegerhoogeboom** [comment]
Sorry about that, indeed I meant tooltip.

**Comment by cebilon123** [comment]
I can take it as my first contribution 😄
