### ISSUE TITLE
[Feature Request] Stat Panel: Support emoji

### ISSUE THREAD

**Issue by baur** [grafana/grafana#36010]
**What would you like to be added**:

Please, add emoji supporting on Stat Panel

![image](https://user-images.githubusercontent.com/2898361/122856669-ffe8ac80-d338-11eb-9205-ec2ed71b337e.png)

**Comment by zuchka** [comment]
related to #35154. (emoji in markdown in text panel)

**Comment by torkelo** [comment]
Grafana frontend supports emoji , could be the SQL driver does not ?

**Comment by baur** [comment]
> Grafana frontend supports emoji , could be the SQL driver does not ?
@torkelo

Thank you, it's my fault, 
required N' prefix

![image](https://user-images.githubusercontent.com/2898361/122867720-c40b1280-d34b-11eb-9bc1-f0ef5607e8b5.png)
