### ISSUE TITLE
Alerting: replace switch with collapse cheveron for "configure no data and error handling" toggle

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#36016]
**What would you like to be added**:

 "configure no data and error handling" switch in the alert editor page only toggles UI elements to appear, but it gives the impression that it modifies data somehow. Let's replace it with usual cheveron `>` for clarity.

![image (2)](https://user-images.githubusercontent.com/847684/122898687-c07b8980-d353-11eb-95ec-4d182177c301.png)

**Why is this needed**:

**Comment by dsiperek-vendavo** [comment]
I was just going to report this as a bug as it seems like the values are not staying set.
