### ISSUE TITLE
ngAlerting templating: possibility to show values on which the alert was triggered

### ISSUE THREAD

**Issue by malejpavouk** [grafana/grafana#36020]
**What would you like to be added**: It seems that it is not possible to anyhow template the values that were used to evaluate the alerting rule. In alert rule definition there are named A, B, C... and relate to the value of the reading itself (not to label pairs)

**Why is this needed**: It would be very useful to see in notification that disk space alert is firing, because there is less than < 5GB (1234MB) of space on the disk, where 5GB is the threshold and 1234MB is the value ($B) of the current reading that caused the alert to be triggered.
Currently, it's only possible to visualize label pairs (key, value), not the actual reading value.

**Comment by kylebrandt** [comment]
Previous internal issue: https://github.com/grafana/alerting-squad/issues/79

Which had:

From @gotjosh 

> In Prometheus, an alert can produce multiple series each of them with a value. Given each alert would have its own set of values the series -> value it's 1:1.
> 
> In the Grafana world, this is not true. An SSE alert that uses $A > $B now produces 1 alert that needs to include two values for it to produce a meaningful annotation. We need to find a solution for handling that. 
> 
> After chatting with @gerobinson, we discussed a few points:
> 
> - We think using private labels (or maybe annotations?) to communicate the values between scheduler <> alertmanager is feasible. The thing to keep in mind here is that alerts with different values but the same set of original labels should not be a _different_ alert in the alertmanager. 
> - These private labels would be parsed and removed from the final set of labels that compose the alert group key
> - These values would be available in templates under a certain nomenclature (there is a change we need to copy / modify upstream Alertmanager code) e.g. $values.A or $values.B assuming their RefID is A or B

from @codesome 

> I have another question/concern: Do we support templated labels for SSE? Like `"namespace": "$labels.namespace"` or similar? Because in that case, the multiple values generated would have to be routed to different places if necessary, and we no longer can have it in a single alert with the new way of routing.
> 
> One solution for this one could be not allowing templated labels for SSE.


> Now coming to the problem mentioned in the description, one possible solution could be we introduce a new template variable which is an array of (labels, value) tuple. And we have a default annotation field using this template variable while users can modify as they want.
> 
> The above is only for SSE which produces 1 alert always. For multidimensional alerts, we will already support template variables like Prometheus, right?

**Comment by kylebrandt** [comment]
@malejpavouk 

Note that currently we do put these values (when the labels would "join" with the alert instance labels) ... as a big ugly string into the `__value__` label :-/ ... 

I believe this is available in notifications via the `__value__` label (but currently isn't available in annotation expansion, such as template with the `summary` annotation, yet).

This is not ideal and was a quick fix so at least the information would be available in some form for notifications in the initial feature preview. So making this better (available in annotations, and available as template variables in a more fine grained way) is a goal I believe for 8.1 or 8.2.

**Comment by dsiperek-vendavo** [comment]
Do you have an example?  I tried __value__ labels in notification template with no luck.

**Comment by malejpavouk** [comment]
@kylebrandt  yeah, I tried exactly the same code. Originally I thought that its caused by the reduce condition I use (since we are on top of Prometheus/Thanos), but I got the same disappointing result even with classic condition.

**Comment by kylebrandt** [comment]
> @kylebrandt ... but I got the same disappointing result even with classic condition.

Note the classic condition also puts values in `__value__`, but a bit differently (format, values it includes) since it is meant to behave like pre-8 dashboard alerting, but it should still be populated - so maybe something a bit later in my spot in the code in the template processing - an area I know less about...

**Comment by codesome** [comment]
> Oh maybe this fella in template_data.go:

Yes that is the one. Not skipping `_value__` sounds good.

**Comment by gerobinson** [comment]
Hi @malejpavouk, I have just merged PR #36611 which should fix this issue!
