### ISSUE TITLE
display style / fill below to doesnt seems to work well

### ISSUE THREAD

**Issue by nemenemsrouge** [grafana/grafana#3602]
Hello,

I have 2 metrics in graphana from graphite:

1 for the exec time of a big processing call
1 for the exec time of the same processing but for yesteday

I want to compare the performances in execution time between now and 1 day ago.

So I use in display style the fill below option... but it randomly doesnt work ...
The filling doesnt display from time to time (I set autorefresh to 5 sec)

I joined 2 pictures, 

the first one when it works:
![grafana 1](https://cloud.githubusercontent.com/assets/6534850/11992936/e7cae08c-aa2b-11e5-8b1a-a4d418d09232.png)

the second one when it doesnt work:
![grafana 2](https://cloud.githubusercontent.com/assets/6534850/11992938/efc70e28-aa2b-11e5-9498-2b7fb4066059.png)

Any idea?

Regards 
nemenemsrouge

**Comment by torkelo** [comment]
The second one does not appear to have many data points for yesterday? Can you enable points so we can see what datapoints actually exist?

**Comment by nemenemsrouge** [comment]
Sure,

here it is: 

![grafana 4](https://cloud.githubusercontent.com/assets/6534850/11994896/4e11d718-aa47-11e5-9dc9-62838033bda4.png)

Seems that there is enough points!

(merry christmas Torkelo ^^)

**Comment by torkelo** [comment]
Try changing null point mode to null as zero , maybe some missing points. Hut your points look wrong, fill bellow to only works for series that are always above a nether series (like max and min)

**Comment by nemenemsrouge** [comment]
Interesting, this seems to work better now !

Thank you very much and I wish you a lot of happiness for christmas and for the end of year

Regards
Nemenemsrouge

De : Torkel Ödegaard [mailto:notifications@github.com]
Envoyé : jeudi 24 décembre 2015 14:37
À : grafana/grafana <grafana@noreply.github.com>
Cc : Jeremy Cohen-Solal <Jeremy.Cohen-Solal@dalenys.com>
Objet : Re: [grafana] display style / fill below to doesnt seems to work well (#3602)


Try changing null point mode to null as zero , maybe some missing points. Hut your points look wrong, fill bellow to only works for series that are always above a nether series (like max and min)

**Comment by bergquist** [comment]
Closing this since it seems to be solved. :)
