### ISSUE TITLE
Grafana 8 alerting does not propagate to Alertmanager consistently

### ISSUE THREAD

**Issue by abhimanyupatel** [grafana/grafana#36037]
Running grafana 8.0.2 with the ngalert feature toggle enabled and alertmanager in a local docker environment it seems that the alerts are being triggered but not propagated to the alertmanager. There are some non-deterministic alerts that do show up but it's very rare and no patterns seems to be present.

When running a docker image with grafana version 7.X it has no issues propagating the alerts right away after they trigger.

Does anyone else have this issue as well? Is this a known side effect of upgrading?

**Comment by davidmparrott** [comment]
@abhimanyupatel can you tell me a little more about your configuration? Have you configured the external Alertmanager as a contact point or are you expecting Grafana 8 alerts to send everything to the external Alertmanager by default? Grafana 8 alerting uses an embedded alertmanager for Grafana managed alerts but can also send alerts to an external alertmanager when configured as a contact point.

**Comment by abhimanyupatel** [comment]
@davidmparrott Sure, I have configured the external Alertmanager as a contact point and also set up all the necessary tags which I include in the alert rules. Just to be safe, I also set the external Alertmanager as the default channel. This didn't make a difference though.

As for the general setup, I'm running it all in a local docker environment as not to touch anything in our other environments with the alpha feature. So Grafana and Alertmanager are connected (Alertmanager being defined as a contact point) locally through the IPs provided in the docker configs. The IP I point to is also correct, since I can test it with Grafana 7.x in the same setup. 

I've also tested it with 8.0.3 with the same result. Another interesting thing I saw yesterday is that one alert showed up quite some time after being triggered and when another one got triggered, it showed up but the first one disappeared despite still being in an alerting state and then after some time the second alert also disappeared despite still alerting. It's all a bit non-deterministic and I can't tell how to reproduce it unfortunately - thus the issue.

Do let me know if you need any other information from my side. Thanks for looking into this!

**Comment by davidmparrott** [comment]
@abhimanyupatel just checking whether it's possible you're running afoul of the issue reported here https://github.com/grafana/grafana/issues/36094

**Comment by gotjosh** [comment]
@abhimanyupatel can you please share with us your alertmanager configuration and an example of what kind of rule you're using it with? 

There's basically three steps here that could be the problem: rule evaluation, alert rule -> alertmanager, or alertmanager -> contact point. On any of these cases, there _should_ be a message on the logs that indicate where it failed.

Sharing your configuration with us should be able to let us try to replicate the setup and find the problem - in the rare occasion where we're failing to log the error/output.

**Comment by abhimanyupatel** [comment]
> @abhimanyupatel just checking whether it's possible you're running afoul of the issue reported here #36094

Thanks for checking. It's not the same issue. I replaced my label values to single words and it still happens. I also don't have Prometheus as the data source but Azure Data Explorer.

@gotjosh absolutely, I'm using the vanilla alertmanager docker image and connect it via the appropriate IP address on grafana.
I've added the config I found below. The curious part is that it's not stable in sending alerts. E.g. I can see some alerts being shown sometimes - but then they stay until after they're resolved. Some don't even show up at time but do some other times. Without changing anything on the alert.

My grafana config is also the standard config, with the exception of the ngalert feature toggle being enabled of course.

The only config I could find on the alertmanager is the following:
/etc/alertmanager $ cat alertmanager.yml
route:
  group_by: ['alertname']
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'web.hook'
receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://127.0.0.1:5001/'
inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'dev', 'instance']
 

Also here is how the alertmanager is defined in the contact points menu:
![image](https://user-images.githubusercontent.com/4376076/125352614-592f7480-e316-11eb-8441-0307ea39cd55.png)

And the corresponding notification policy:
![image](https://user-images.githubusercontent.com/4376076/125352676-6ba9ae00-e316-11eb-8dd9-7f93bb8d78aa.png)

This setup works sometimes, so I feel it can't be due to the setup but maybe you'll see something I missed.

Thank you for having a look!

**Comment by gotjosh** [comment]
Can you also please sure the alert rule definition from the grafana side?

**Comment by abhimanyupatel** [comment]
Sure, here you go. I can't include the exact query but it's basically a graph showing the CPU usage of various instances.

![image](https://user-images.githubusercontent.com/4376076/125358398-b0851300-e31d-11eb-803f-02d74dcce99c.png)
![image](https://user-images.githubusercontent.com/4376076/125358458-c4c91000-e31d-11eb-869d-9db53e1296df.png)
![image](https://user-images.githubusercontent.com/4376076/125358503-d3172c00-e31d-11eb-8399-5ff23748db24.png)

**Comment by davidmparrott** [comment]
@abhimanyupatel is it possible that the issue is there's already an alert firing for this condition? The classic condition does not create multi-dimensional alerts, so there will only ever be one alert instance generated by the condition.

**Comment by abhimanyupatel** [comment]
@davidmparrott No, this is unfortunately the only alert I have on this condition. I've also reduced it to 2 alerts overall (different queries and conditions) in order to test the behavior more easily.

**Comment by gotjosh** [comment]
@abhimanyupatel we've made some changes wrt timings on how alerts are sent out to the Alertmanager - are you able to test the main branch directly to see if it is consistent now?

**Comment by gotjosh** [comment]
We believe this should now be fixed after the changes of sending resolved signals. Please feel free to open a new issue if it is not.
