### ISSUE TITLE
divideSeries on mixed datasource panels

### ISSUE THREAD

**Issue by bradleyphipps** [grafana/grafana#3603]
I'm getting estimated billing charges from Cloudwatch and wanting to divide this number by some numbers from Graphite. I have divideSeries(#A,#B) working with two numbers from graphite, but when I try using Cloudwatch as one of the sources, a result is not shown. Both A and B show the correct numbers when not hidden.

Is this feature implemented? Maybe I'm missing something obvious...

Currently using Grafana 2.5.

Screenshot: ![screen shot 2015-12-24 at 10 55 40](https://cloud.githubusercontent.com/assets/1391599/11993788/02245c8c-aa2d-11e5-8f27-d692ada200a1.png)

**Comment by torkelo** [comment]
divideSeries is a graphite function, so it can only operate on graphite queries :(

**Comment by bradleyphipps** [comment]
Thanks for the swift update :sob:

I guess I'll have to get the billing numbers and post them into graphite myself.

Keep up the great work :+1:
