### ISSUE TITLE
Enabling e-mail verification on sign up makes the sign up button return 404.

### ISSUE THREAD

**Issue by RyuunosukeDS3** [grafana/grafana#36038]
**What happened**:
When I enbaled the option to verify the e-mail on sign up, clicking on the "sign up" button redirected me to the "/verify" which returned 404

**What you expected to happen**:
Normal sign up page and then e-mail verification

**How to reproduce it (as minimally and precisely as possible)**:
just enable e-mail verification

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- OS Grafana is installed on: Alpine on docker
- Host OS: Ubuntu Server 20.04.2
- User OS & Browser: Chrome on Windows

**Comment by zuchka** [comment]
Hi @RyuunosukeDS3 

Thanks for creating this issue. I was able to reproduce the error running this container:

`docker run -p 3000:3000 -e "GF_USERS_VERIFY_EMAIL_ENABLED=true" -e "GF_USERS_ALLOW_SIGN_UP=true" grafana/grafana:main`

confirmed on `grafana/grafana:8.0.0 - 8.0.3` as well, on macOS + firefox or chrome.  not much in dev tools

**Comment by RyuunosukeDS3** [comment]
Thanks for the response! Hope it doesn't take too long to fix since this kind of a must have in our work environment. Always amazed by the Grafana's team work.

**Comment by tskarhed** [comment]
The issue is cause by this line
https://github.com/grafana/grafana/blob/98893c04202bbf3f0a3ab13e41fa77adc563eaa7/public/app/core/components/Login/UserSignup.tsx#L7

It was changed in #26263. I'm investigating the expected behaviour and the reason behind the change

**Comment by tskarhed** [comment]
To prevent this from happening again, we probably need some e2e tests that tests all the available routes.
