### ISSUE TITLE
Expression stops working when input queries contain variables

### ISSUE THREAD

**Issue by maththedude** [grafana/grafana#36039]
**What happened**:
I had a panel working correctly with two queries and an expression. I wanted to replace two dates in each query with the global variables $__from and $__to. Doing that broke the panel, giving "expression request error". Inspecting the two queries shows they are identical whether they are hardcoded or using variables. The panel will not show data from either query, or the expression (probably expected behavior from an error).

**What you expected to happen**:
I expected the panel not to break.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query using hardcoded dates
Create an expression with the query as an input
Edit the query, changing the hardcoded dates to $__from and $__to, formatted correctly

**Anything else we need to know?**: 
Expression takes in non-timeseries table data (queries) and produces non-timeseries table data. Display element is a bar gauge.

Queries with hardcoded dates and the expression (working):
![withoutVariables](https://user-images.githubusercontent.com/62571760/122988713-a64ba680-d367-11eb-9bee-a419d018879e.PNG)

Queries with $__from and $__to and no expression (working):
![WithVariablesWithoutExpression](https://user-images.githubusercontent.com/62571760/122988840-c5e2cf00-d367-11eb-9b7f-4d51ecd944bb.PNG)

Queries with $__from and $__to and and expression (broken, giving "expression request error", and not displaying data):
Note: I know this expression is different than the working one. I wanted to make this on as simple as possible for the bug report.
![withVariablesWithExpressionBROKEN](https://user-images.githubusercontent.com/62571760/122989016-f591d700-d367-11eb-9ebd-45ae7a3d7906.PNG)

**Environment**:
- Grafana version: 8.0.1
- Data source type & version: postgresql latest
- OS Grafana is installed on: whatever is on the latest grafana/grafana docker container
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: None
- Others:

**Comment by zuchka** [comment]
Hi @maththedude 

thanks for reporting this. [According to our docs](https://grafana.com/docs/grafana/latest/panels/expressions/#using-expressions), Expressions are both a beta feature that are liable to break in new versions, and _will not work with dashboard variables_:

> Note: Expressions do not work with dashboard variables.

> Note: When possible, you should do data processing inside the data source. Copying data from storage to the Grafana server for processing is inefficient, so expressions are targeted at lightweight data processing.
