### ISSUE TITLE
Feature request: Standalone plot library

### ISSUE THREAD

**Issue by breezewish** [grafana/grafana#36033]
**Why is this component needed**:

Now that there is a `GraphNG` component for plotting. However it is only useful and easy to be used inside the Grafana project, but not outside the Grafana. Maybe it can be refined to be something like https://www.npmjs.com/package/@elastic/charts so that the community can have powerful time series graphs just like the Grafana without much efforts! Currently people must manually encapsulate the uplot by themselves, which is pretty hard to use (due to the low level interface uplot provides).

___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

Outside the grafana: Bring the powerful feature of Grafana to the open source world!

___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by streamthing** [comment]
@breeswish  how to read uplot config generated by Grafana?
