### ISSUE TITLE
JSON export dashboard does not include default datasource, hence import fail

### ISSUE THREAD

**Issue by yarix** [grafana/grafana#36040]
**What happened**:
importing dashboards to Grafana Cloud does not work properly when exported dashboards contains default data-source.
The imported dashboard uses a wrongly DS and "Random Walk" query.
![image](https://user-images.githubusercontent.com/6409857/122987428-437aff00-d3a9-11eb-8d5d-f5fe6b680fd8.png)

**What you expected to happen**:
import & export of dashboards from one system to the other should work.

**How to reproduce it (as minimally and precisely as possible)**:
1. create a default data source (e.g. prometheus) and **mark it as default** ![image](https://user-images.githubusercontent.com/6409857/122987788-a9678680-d3a9-11eb-91c9-aeb8af81f7bc.png)

2. create a dashboard with some panels that query the default DS. 
![image](https://user-images.githubusercontent.com/6409857/122988459-7245a500-d3aa-11eb-9c43-78b114548048.png)

3. export the dashboard as JOSN, and click the `export for sharing externally` 
![image](https://user-images.githubusercontent.com/6409857/122988797-c81a4d00-d3aa-11eb-8127-890281d93c61.png)

4. import the dashboard into another system (e.g. Grafana Cloud), select the relevant DS. 
![image](https://user-images.githubusercontent.com/6409857/122989261-4840b280-d3ab-11eb-99d5-86806000627c.png)

5. check that the imported dashbord is not working as expected.
 
**Anything else we need to know?**:
* the exported JSON file contains `"datasource": null` on all the panels.
* a workaround is to manually edit the exported JSON file, replacing `"datasource": null` with `"datasource": "${DS_PROMETHEUS-MAIN}"` (as in the __inputs section)

**Environment**:
- Grafana version: on-prem, OSS, 7.5.4 and cloud 8.0.3
- Data source type & version: promethus
- OS Grafana is installed on: RHEL 7
- User OS & Browser: chrome
- Grafana plugins: none
- Others:

**Comment by R2DToo** [comment]
I am constantly running into this issue on a daily basis as well. Not much to add from my side as I feel everything has been explained pretty well. It would be immensely helpful if this issue could get tackled 🙂

**Comment by yarix** [comment]
👏
