### ISSUE TITLE
[Feature Request] [NG-Alerting] Filter alert instances based on their state in Alerts view and Alert List panel

### ISSUE THREAD

**Issue by diveflo** [grafana/grafana#36048]
**What would you like to be added**:
Ability to filter ng-alert **instances** based on their state, rather than only per alert.
This would be great for both the Alert view as Alert List panel.

**Why is this needed**:
We have a few alerts which thanks to the new alerting in Grafana 8 are multidimensional and create hundrets of alert instances each.
Going through them to find the one that's firing can be quite cumbersome.

![image](https://user-images.githubusercontent.com/11045082/123008331-ff90f580-d3ba-11eb-91b2-ec5ab9292819.png)

Version: 8.0.3

**Comment by dsiperek-vendavo** [comment]
This is VERY MUCH needed as trying to find critical alerts in 500 plus instances is a nightmare making this product almost not useable!
Thanks

**Comment by dsiperek-vendavo** [comment]
Any update on this? UI is not usual when you have 600 normal and 1 critical and we are waiting on this to move forward.

**Comment by tlifschitz** [comment]
This new multidimensional alert feature is great in some cases!! But here we are facing the same issue, the Firing alert is lost in all the Normal state instances.

**Comment by blauter** [comment]
Same issue here. Real bummer as the alert list panel was the finishing touch on a couple dozen alerts I just created but its completely un-usable as there 100's of OK state in the list with just a few bad state.

**Comment by JacobsonMT** [comment]
Agreed, this would be very useful for me as well. 

I'll take a crack at a PR if no one minds. I was thinking something along the lines of:

- New set of state filters for the alert instances:
  - Alerting
  - Error
  - Pending
  - No Data
  - Normal
- An alert instance label filter for filtering by labels (custom priority-level labels come to mind as a use-case here)
- (optional) It would be nice IMO to be able to layout the alert instance horizontally for some flexibility in dashboard design, but I can leave it out of this PR if people think that's best.

Let me know if anyone has recommendations on alternate filters/methods, for now I'll start with this though.
