### ISSUE TITLE
Unable to use 'sni-pnp-datasource' plug-in

### ISSUE THREAD

**Issue by FRvanderVeen** [grafana/grafana#36043]
**What happened**:
After upgrading Grafana docker image to 8.0.3 my dashboard (containing a PNP datasource) no longer opens

`t=2021-06-22T20:44:04+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/plugins/sni-pnp-datasource/src/img/logo.svg status=404 remote_addr=172.17.0.1 time_ms=1 size=1727 referer=http://host:port/datasources/new`

**What you expected to happen**:
Being able to open the dashboard / plugin configuration page

**How to reproduce it (as minimally and precisely as possible)**:
Deploy the latest docker image, with environment var GF_INSTALL_PLUGINS=sni-pnp-datasource, and a local folder for volume /var/lib/grafana
Login to admin
Go to plugins
Open pnp

**Anything else we need to know?**:
After testing it with a specific volume I tested it without the volume. In that setup the plugin configuration page opens without issue. Which makes me think issue is on Grafana side and not in the plugin

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: sni-pnp-datasource 1.0.8
- OS Grafana is installed on: Synology DS218+ running DSM 6.2.4-25556
- User OS & Browser: Windows / Firefox 89.0.1
- Grafana plugins sni-pnp-datasource 1.0.8
- Others:

Screenshot when opening dashboard
![image](https://user-images.githubusercontent.com/86024496/123001404-fac74400-d3b0-11eb-9d00-8f29ca0c6e37.png)

Screenshot when opening plugin configuration page
![image](https://user-images.githubusercontent.com/86024496/123001544-221e1100-d3b1-11eb-9202-4e8509be4910.png)

**Comment by torkelo** [comment]
it could be permission issue with your local folder?

**Comment by FRvanderVeen** [comment]
I don't think that's the issue. I was able to reproduce it with a newly created docker image. That image was able to install the plugin, so I would expect all permissions on the local folder to be correct.

**Comment by zuchka** [comment]
@FRvanderVeen 

to verify: this throws an error for you?

`docker volume create pnptest`

`docker run -p 3000:3000 -e "GF_INSTALL_PLUGINS=sni-pnp-datasource" -v "pnptest:/var/lib/grafana" grafana/grafana:8.0.3`

And if not, have you tried adding the the plugin by using the new plugin catalog?

` -e "GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true"`

**Comment by FRvanderVeen** [comment]
Thanx for all the help, but it turned out to be a rights issue after all. Not totally sure what fixed it, but after giving 'chmod -R 777' on the local folder which was mounted as /var/lib/grafana things started working again. So probably the rights on that specific folder where wrong.
Closing this issue, since it looks like it's fixed

**Comment by nhart12** [comment]
I'm having this same issue on 8.0.3, although I'm running in azure and mounting /var/lib/grafana to an Azure file share. Any ideas here on what could be the issue?

**Comment by yggdrasil-tynor** [comment]
@nhart12  same issue for me on Azure File Shares

**Comment by nhart12** [comment]
@yggdrasil-tynor I posted over here a workaround for now, seems to be related to permissions in v8 
https://github.com/grafana/grafana/issues/34718#issuecomment-870934478
