### ISSUE TITLE
Deleting alert gives error (ngalert) 

### ISSUE THREAD

**Issue by N3v3R3nD** [grafana/grafana#36042]
**What happened**:
Error 404
**What you expected to happen**:
Alert to be deleted

**How to reproduce it (as minimally and precisely as possible)**:
It was a random alert in my list after enabling ngalert, then added a second to test again and the same happened on that panel. 
 I have the issue with 2 of the same alerts on the same panel. 
I tested to delete, the panel, and dashboard, still gives the same error, but of course unable to find the panel anymore. 

Is there any other way to delete these alerts?

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Influx 1.8
- OS Grafana is installed on: Debian 10
- User OS & Browser: Chrome
-
 
![ss1](https://user-images.githubusercontent.com/3173205/122997184-06fcd280-d3ac-11eb-993c-b6ec784bee7a.PNG)

![error](https://user-images.githubusercontent.com/3173205/122997153-ffd5c480-d3ab-11eb-8217-a2cb7a7c5119.PNG)

**Comment by papagian** [comment]
@N3v3R3nD do you get the above error when you click on the Delete button next to the rule in the Alerting listing page or from somewhere else?
The dashboard is under a folder or under the General one? The rules are saved under this folder?
Can you share the failing request/response in your browser's developer tools (network tab)? Can you check for any errors in the server logs?

**Comment by N3v3R3nD** [comment]
After the upgrade to 8.0.5, I was able to delete the alerts again so the issue is solved.
