### ISSUE TITLE
Threshold coloring based on time interval

### ISSUE THREAD

**Issue by patjlm** [grafana/grafana#3604]
Would it be possible to have a threshold list of values using templates and especially $interval ?

Values in the graph are highly based on the time interval used: we do not have the same number of errors during 1second or during 1 hour. It would be nice to be able to use $interval in the threshold values list for coloring tables or single stats.

Threshold: 0,100*$interval,500*$interval

That would mean always providing the interval in the same unit. So maybe $interval_ms (as I saw in some other issues) might be more relevant.

**Comment by torkelo** [comment]
would you not need to do multiplication or division for to work properly? 

If you threshold values depend interval, maybe change the query to average / calculate rate instead. Do not think thresholds should change when you change time range, will be very confusion / complex.

**Comment by patjlm** [comment]
Indeed, I did not see the multiplication sign did not go through in my text. Sorry about that.
Thresholds don't depend on the interval for metrics likes Max, Min or Average. However for things like Count or Sum, they're useless with auto or templated interval.
The only workaround for now, as you mentioned, is to not display Sum/Counts but rates.

**Comment by neoliv** [comment]
I have a similar use case.
What I would like to have is a $interval (in seconds) without the unit symbol.
That way I could do a:
SELECT sum(error) / $interval_nounit FROM ...GROUP BY time($interval)
And get an error rate in error/s whatever the interval is set to.
Cheers.

**Comment by torkelo** [comment]
in Grafana 4.2 you have a built-in variable name $__interval_ms    (interval in milliseconds)

**Comment by neoliv** [comment]
Thank you.
Exactly what I was looking for.
Works like a charm.
