### ISSUE TITLE
Grafana 8x the point to change the y-axis to left and right is missing

### ISSUE THREAD

**Issue by syswombat** [grafana/grafana#36041]
hello
on Grafana 8x the point to change the y-axis to left and right is missing.
the description like on Grafana 7 is not working
https://grafana.com/blog/2020/03/10/learn-grafana-how-to-use-dual-axis-graphs/
have a nice day
vinc

**Comment by zuchka** [comment]
Hi @syswombat 

thanks for reporting this. In Grafana 8, we actually _extended this feature_. Now you can add multiple axes (more than two):
https://play.grafana.org/d/YI95GyqMz/1-new-features-in-v8-0?orgId=1&editPanel=54

You can then use overrides to set the placement for each series:

![CleanShot 2021-06-24 at 14 04 46@2x](https://user-images.githubusercontent.com/37156449/123349538-4125bb80-d4f5-11eb-9fc6-2b9fc03b4994.png)

@marcusolsson do you think we should make a note on the blog that things have changed a bit in 8.x.x?

**Comment by marcusolsson** [comment]
Might be a good idea!

**Comment by dhs9004** [comment]
Hi,

I'm having a similar issue, using two queries

![image](https://user-images.githubusercontent.com/38137546/142783282-64cb2f12-55a3-457a-a37e-50de6312af14.png)

The override feature doesn't work for the axis placement.

this the response from query B

![image](https://user-images.githubusercontent.com/38137546/142783369-d191e3de-1fb5-42e9-ad90-7e71fde32d11.png)

using grafana v8.2.3
Thanks,
