### ISSUE TITLE
Currently, only graph alarms can be configured. What can I modify to enable other plug-ins to support alarm configuration?

### ISSUE THREAD

**Issue by caoqiang-github** [grafana/grafana#36052]
Currently, only graph alarms can be configured. What can I modify to enable other plug-ins to support alarm configuration?

**Comment by torkelo** [comment]
you can try the new alerting system : 
https://grafana.com/docs/grafana/latest/alerting/unified-alerting/

With this system you can link to any panel but the alert rule is defined separatly

**Comment by caoqiang-github** [comment]
If we don't want to use another alarm system, can't we modify something to satisfy? For example, if I want to add alarm configurations to the stat plug-in, can I simply modify some code to meet the requirements?

**Comment by caoqiang-github** [comment]
> you can try the new alerting system :
> https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
> 
> With this system you can link to any panel but the alert rule is defined separatly

If we don't want to use another alarm system, can't we modify something to satisfy? For example, if I want to add alarm configurations to the stat plug-in, can I simply modify some code to meet the requirements?
