### ISSUE TITLE
topk(<INT>, <QUERY>) supported in Explorer but does not get applied on dashboards

### ISSUE THREAD

**Issue by proffalken** [grafana/grafana#36053]
**What happened**:

When running a LogQL query against the latest loki data source in the explorer, the `topk(5, <QUERY>)` limits the results returned to the top five items.

When running exactly the same query as part of a graph creation for a dashboard, the `topk` limit is ignored and multiple rows are returned without any kind of filtering:

The query in the Explorer Window:
![GraphQLExplorer](https://user-images.githubusercontent.com/262545/123038121-ba36ed00-d3e7-11eb-857a-abb9a9349497.png)

The same query in Dashboard editor:
![GrafanaChart](https://user-images.githubusercontent.com/262545/123038117-b99e5680-d3e7-11eb-8af2-2844ef770ce1.png)

**What you expected to happen**:

If a query runs correctly in Explorer, it should also run correctly in Dashboard mode

**How to reproduce it (as minimally and precisely as possible)**:

Create a Loki query that uses the `topk()` function

**Environment**:
- Grafana version: 8.0.2
- Data source type & version: Loki (Built In)
- OS Grafana is installed on: Official Docker Container
- User OS & Browser: Arch Linux, Brave Browser
- Grafana plugins:
- Others:

**Comment by Mario-Hofstaetter** [comment]
You are using `Instant` query mode in explore, but `Range` query mode in dashboard from what the screenshots tell.

As far as my experience goes, using `topk` in range queries often returns more than the set `n` series because of how it works (which may be unexpected if the users is familiar with e.g. SQL `TOP` statement.

**Comment by proffalken** [comment]
@Mario-Hofstaetter thanks for the prompt reply.

I've tried both `Range` and `Instant` in both windows, and still the correct result (top five rows) is only returned in explore mode.

I'll read up more on `topk` because it sounds like I've misread something somewhere from what you're saying.

**Comment by proffalken** [comment]
Is there more documentation about topk other than https://grafana.com/docs/loki/latest/logql/#aggregation-operators ?

I ask because according to that my query should only return the top five results from Loki, but as you can see it returns many more than that in Grafana.

What am I missing here? Have I misunderstood what topk does, and if so is someone able to explain it to me better than the documentation does so I can go an update the docs?

**Comment by ivanahuckova** [comment]
I have found the same discussion in Prometheus developers group that explains the issue and why there are diifferent results for range and instant queries: https://groups.google.com/g/prometheus-developers/c/Ksthw4SvN9M/m/FBfKsOI7AgAJ. There is also this github issue that explains it as well: https://github.com/prometheus/prometheus/issues/586. 

```
The topk applies to each individual step in the query, not the entire query as a whole, so at any given moment on that graph there will be 10 items, but across the entire graph there may be more, since each step may result in a different set of items.
```

**Comment by Mario-Hofstaetter** [comment]
@proffalken Maybe also take a look at this:
https://prometheus.io/blog/2021/02/18/introducing-the-@-modifier/

While writing this, I realized your query was LogQL not PromQL, but maybe the `@-modifier` could be implemented into loki too in the feature.

> Currently, the topk() query only makes sense as an instant query where you get exactly k results, but when you run it as a range query, you can get much more than k results since every step is evaluated independently.
>[...]
>Coming back to the topk() fix, the following query plots the 1m rate of http_requests_total of those series whose last 1h rate was among the top 5. Hence now you can make sense of the topk() even as a range query where it plots exactly k results.

**Comment by lddlww** [comment]
> While writing this, I realized your query was LogQL not PromQL, but maybe the `@-modifier` could be implemented into loki too in the feature.

@Mario-Hofstaetter the mean you are that loki does not support exactly topK so far?
