### ISSUE TITLE
SQL: Name of time field changed in v8 

### ISSUE THREAD

**Issue by thesteg** [grafana/grafana#36059]
**What happened**:

After upgrade to 8.0.3 from 7.5.5 graph panel no longer could display data from query.

**What you expected to happen**:

Graph panel should work as before.

**How to reproduce it (as minimally and precisely as possible)**:

Upgrade from 7.5.5, use transform: filter by name

**Anything else we need to know?**:

There is a transform on my panel that filters by name, in 7.5.5 it picks out 'Time' from the $__timeGroupAlias but on upgrade to 8.0.3 'Time' is no longer available because there is a capitailsation of the 'time' field in version 7.5.5 which does not appear to happen in 8.0.3.

Both versions 7.5.5 and 8.0.3 expand the $__timeGroupAlias to time_bucket('10.0s',logtime) AS "time"

A fix is to go back through and change the name filters from 'Time' to 'time' but is quite tedious!

**Environment**:
- Grafana version:

7.5.5, 8.0.3

- Data source type & version:

timescaledb pg12

- OS Grafana is installed on:

archlinux, docker

- User OS & Browser:

Opera, win10

- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@marefr this looks like another SQL breaking change, can we capitalize time like before?

**Comment by torkelo** [comment]
Or maybe its due to the macro having lowercase but before the column name was ignored?

**Comment by marefr** [comment]
I think the reason for returning time lowercased in frame in v8 was because client side didn't support time fields named `Time`, but not sure.

**Comment by marefr** [comment]
@ying-jeanne do you remember if we had any discussion around naming of the time field in frame?

**Comment by torkelo** [comment]
Looks like the new ToWide frame transform preserves the original time column name

**Comment by marefr** [comment]
> Looks like the new ToWide frame transform preserves the original time column name

I think before Grafana 8 the frontend/UI picked out `Time` as field name. On v7.5.x we used the old data model (no data frames) and cannot change the name of the returned time-column/field, see https://github.com/grafana/grafana/blob/c5cf127aa6217ae8babdd6fb9315114e8badd488/pkg/tsdb/sqleng/sql_engine.go#L510

Similarly, when parsing the response in v7.5.x we don't do anything special in regards to the naming of the time-field/column:
https://github.com/grafana/grafana/blob/c5cf127aa6217ae8babdd6fb9315114e8badd488/public/app/plugins/datasource/mysql/response_parser.ts#L21-L54

I wonder if SQL data sources should change to return `Time` if the column name is `time`? Unsure, but feels more like the conversion from/to series/frames is not compatible with returned frames and eager to handover this to frontend to have a look at or document this as a breaking change in the upgrade notes and close this issue.

@torkelo @grafana/grafana-frontend-platform WDYT?

**Comment by torkelo** [comment]
@marefr this is not a frontend issue , it's a breaking change in the format returned be SQL time series queries. Before these returned a data frame with a Time field and a Value field. 

But in v8 this was changed breaking lots of old dashboards and use of old/external plugins.

Can we add a new wide time series format option to sql query editors so this becomes opt in?

**Comment by torkelo** [comment]
>  wonder if SQL data sources should change to return Time if the column name is time?

yes, the time field should be named `Time` if it's a time series.

**Comment by marefr** [comment]
Linking to this code could have helped earlier I guess to show how responses with series are converted to dataframes in v7.5.x:
https://github.com/grafana/grafana/blob/b37c59c1b2fcbbe9cc050b49d40c80a299f362fe/packages/grafana-data/src/dataframe/processDataFrame.ts#L69-L109
https://github.com/grafana/grafana/blob/b37c59c1b2fcbbe9cc050b49d40c80a299f362fe/packages/grafana-data/src/types/dataFrame.ts#L217

> Can we add a new wide time series format option to sql query editors so this becomes opt in?

Not sure we want to go this route, but definitely possible. But feels like adding more legacy code that complicate things. 

I opened a [PR](https://github.com/grafana/grafana/pull/36720) that changes the name of the time field to "Time" for time series queries to be compatible with pre-v8 behavior.
