### ISSUE TITLE
Explore logs displaying RAW ANSI color codes [Grafana v8.0.3]

### ISSUE THREAD

**Issue by waterdrop01** [grafana/grafana#36051]
Here is what I see when querying my k8s app logs on Grafana:
![Screenshot from 2021-06-23 00-58-08](https://user-images.githubusercontent.com/47316824/123010379-c9557500-d3be-11eb-840e-d68cbb9b8211.png)

But, here is what "kubectl logs <pod_id>" shows:
![Screenshot from 2021-06-23 00-58-38](https://user-images.githubusercontent.com/47316824/123010449-ed18bb00-d3be-11eb-8fad-34ca53b2fa37.png)

You can see that Grafana displays ANSI color codes, while it should display purple color text...

Do you have the same problem?

Thanks for your help!

**Environment**:
- Grafana version: v8.0.3
- Data source type & version: Loki latest
- OS Grafana is installed on: Kubernetes

**App**
- That's the logs of a Nodejs app running in Kubernetes, and started using this env:
```
- name: DEBUG_COLORS
              value: 'true'
```

**Comment by zuchka** [comment]
@ifrost is this maybe related to #35166 ?

**Comment by ifrost** [comment]
> @ifrost is this maybe related to #35166 ?

Seems like something different 🤔 we need to try to reproduce it. cc @ivanahuckova

**Comment by waterdrop01** [comment]
@ifrost @ivanahuckova I seem to encounter the same issue not only with my nodejs pods logs, but also with:

drone.io pod logs:
![Screenshot from 2021-06-24 12-18-14](https://user-images.githubusercontent.com/47316824/123246967-aaea9900-d4e6-11eb-8a3e-104cd91a573f.png)

Traefik pod logs:
![Screenshot from 2021-06-24 12-18-36](https://user-images.githubusercontent.com/47316824/123247003-b342d400-d4e6-11eb-8bfa-c952fd077597.png)

Loki pod logs:
![Screenshot from 2021-06-24 12-19-20](https://user-images.githubusercontent.com/47316824/123247023-b8078800-d4e6-11eb-8ca3-12933c8d6125.png)

Are all these back slask \\\ normal?

**Comment by olbo98** [comment]
Could it be that there's some process which is adding extra back slashes which will escape the back slash in the ANSI code?

**Comment by olbo98** [comment]
Did some digging and something that produces this behaviour is using `JSON.stringify()` on string that hasn't been parsed as a JSON object. If we just pass a string into `JSON.stringify()` it will just add back slashes to everything like this
Writing out the log as a string without doing anything with it:
<img width="466" alt="Screenshot 2021-07-02 at 11 42 30" src="https://user-images.githubusercontent.com/16028771/124256685-de9f7180-db2b-11eb-8282-9e3a326df267.png">
Passing the message to `JSON.stringify()` without first parsing it with `JSON.parse()`
<img width="582" alt="Screenshot 2021-07-02 at 11 42 39" src="https://user-images.githubusercontent.com/16028771/124256821-02fb4e00-db2c-11eb-8e4b-5435e6a5d716.png">

Or maybe an even clearer example:
Writitng out the log as a string without doing anything with it:
<img width="516" alt="Screenshot 2021-07-02 at 11 51 04" src="https://user-images.githubusercontent.com/16028771/124256904-19a1a500-db2c-11eb-91c8-02ba536d1f61.png">
Passing the message to `JSON.stringify()` without first parsing it with `JSON.parse()`
<img width="588" alt="Screenshot 2021-07-02 at 11 51 12" src="https://user-images.githubusercontent.com/16028771/124256976-2cb47500-db2c-11eb-87a3-63ee97896243.png">

As you can see it seems like it's adding extra back slashes. @grafana/observability-squad do you think this could be the cause for the problem?

**Comment by ivanahuckova** [comment]
>As you can see it seems like it's adding extra back slashes. @grafana/observability-squad do you think this could be the cause for the problem?

Escaped quotes in nested jsons are normal, but if the escaping is incorrect, it can be in some cases problematic. I am not sure if it can affect the ANSI coloring. First of all, we need an example of the received log line (ideally directly from the network tab) and see if it ANSI coloring works on that log line. If yes, then the problem is within Grafana and we need to find where and fix it. If not, then received log is probably incorrect and we + user can investigate where exactly is the problem in that log line.)

>You can see that Grafana displays ANSI color codes, while it should display purple color text...
@waterdrop01 Could you please provide us with the log line (in text format, ideally directly from the network tab) that you expect to have ANSI coloring, but it doesn't work in Grafana. 

>@ifrost @ivanahuckova I seem to encounter the same issue not only with my nodejs pods logs, but also with...

@waterdrop01 I don' see any ANSI codes in the provided logs, so there is no reason for them to have colors so I am not sure how is this related to the described issue.

**Comment by waterdrop01** [comment]
Thanks a lot @olbo98 and @ivanahuckova for investigating my issue. Really appreciated!

Just to clarify, I have a node.js program using the [debug](https://github.com/visionmedia/debug) module to log to the console. [Here is a repo](https://github.com/waterdrop01/grafana-node-log) for you to reproduce, but basically this is enough to reproduce:
```js
const debug = require("debug")("index.js");

setInterval(() => debug("Hello"), 1000);
```
Then just run it using `DEBUG=* DEBUG_COLORS=true DEBUG_DEPTH=10 node src/index.js` and it will output something like this:

![Screenshot from 2021-07-04 13-33-42](https://user-images.githubusercontent.com/47316824/124383396-7f2c9780-dccc-11eb-90d7-2ebf9ba05302.png)

Now after I dockerize it, and deploy it to my kubernetes cluster, the logs in grafana/explore look like this:

![Screenshot from 2021-07-04 13-37-22](https://user-images.githubusercontent.com/47316824/124383486-01b55700-dccd-11eb-926a-52cc95883290.png)

I remember that before, I used to **get colors in grafana, and no backslash**.

What changed in between:

- Maybe upgrading to Grafana v8?
- Maybe upgrading Loki? 
- Maybe upgrading Promtail?

I'm not sure....I did a lot of upgrades and only recently ran LOGQL queries in grafana/explore.

Here are the helm charts installed in the k8s cluster:
```
NAME      	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART            	APP VERSION
grafana   	monitoring	22      	2021-06-27 00:02:37.761239033 +0200 CEST	deployed	grafana-6.13.5   	8.0.3      
loki      	monitoring	10      	2021-06-23 12:24:59.859478666 +0200 CEST	deployed	loki-2.5.1       	v2.2.0     
prometheus	monitoring	7       	2021-06-08 14:37:43.33486582 +0200 CEST 	deployed	prometheus-14.1.1	2.26.0     
promtail  	monitoring	3       	2021-06-22 19:19:24.235193304 +0200 CEST	deployed	promtail-3.6.0   	2.2.1
```
Thanks again!

**Comment by waterdrop01** [comment]
I just ran the logql query using `logcli`:

- `logcli query '{job="default/qu4nt-js-test-log"}'` 

and the result is exactly the same as what's being displayed on grafana/explore:

```
2021-07-04T13:55:57+02:00 {} {"log":"  \u001b[31;1mindex.js \u001b[0mHello \u001b[31m+1s\u001b[0m\n","stream":"stderr","time":"2021-07-04T11:55:57.078010021Z"}
2021-07-04T13:55:56+02:00 {} {"log":"  \u001b[31;1mindex.js \u001b[0mHello \u001b[31m+1s\u001b[0m\n","stream":"stderr","time":"2021-07-04T11:55:56.076258142Z"}
2021-07-04T13:55:55+02:00 {} {"log":"  \u001b[31;1mindex.js \u001b[0mHello \u001b[31m+1s\u001b[0m\n","stream":"stderr","time":"2021-07-04T11:55:55.074842851Z"}
2021-07-04T13:55:54+02:00 {} {"log":"  \u001b[31;1mindex.js \u001b[0mHello \u001b[31m+1s\u001b[0m\n","stream":"stderr","time":"2021-07-04T11:55:54.073289516Z"}

```

**Comment by ifrost** [comment]
Thanks @waterdrop01. We'll try to have a look at this 👍

**Comment by ant1m** [comment]
Hi,
I don't know if it's related, but there seem to be an issue with escaping special characters, they are replaced by their unicode java/C representation. They are fine in the detailed view, though. (Seen on grafana 8.0.3 and loki 2.1)
![apersand_not_escaped](https://user-images.githubusercontent.com/963299/124926369-bd43f700-dffd-11eb-95be-213c1deacccc.png)
If it is beyond the scope of this issue, please tell me if i should file a other one for this.

**Comment by waterdrop01** [comment]
Hi @ifrost, did you have a chance to look into this issue? I'll provide any additional info you need to reproduce this bug :) Thanks!

**Comment by ifrost** [comment]
@waterdrop01, sorry not yet. We're having an investigation session tomorrow and I'll use it to check it :)

**Comment by ifrost** [comment]
I was able to reproduce it locally using the sample node.js app mentioned above on minikube with promtail/loki helm charts. The sample app produces errors to stderr which are colorized nicely when running `kubectl logs`. These logs are saved to a file `/var/log/pod` by Docker logging driver (?), which I think by default is [`json-file`](https://docs.docker.com/config/containers/logging/json-file/). When stderr is saved, ANSI escape characters are encoded to `\u001b` to get a valid JSON:

```
{"log":"  \u001b[31;1mindex.js \u001b[0mHello \u001b[31m+1s\u001b[0m\n","stream":"stderr","time":"2021-07-16T09:24:23.5631887Z"}
```

When such log is sent to Loki the encoded escape character is not decoded back. @ivanahuckova / @cyriltovena - do you think that could be the cause of the problem? Do you know if there's a way to adjust promtail or Loki configuration?

I tried manually changing `\u001b` to actual escape codes:

[logs-test-mixed.log](https://github.com/grafana/grafana/files/6831870/logs-test-mixed.log)

and converted logs are displayed correctly: (note - the file contains a mix of escaped/non-escaped and json/plain variants)

<img width="1142" alt="Screen Shot 2021-07-16 at 17 47 36" src="https://user-images.githubusercontent.com/745532/125974802-ad2655a3-8dd0-47a3-86a7-3b64ec77e98d.png">

@waterdrop01 Did it work before with some other versions of promtail/Loki? I guess one way to make it work could be if your app was writing logs to a file, not stderr. If that's not an option then maybe changing Docker logging driver could help (though I didn't manage to get this working). Or maybe @cyriltovena can advise how to configure promtail/Loki to make it work?

**Comment by waterdrop01** [comment]
Thanks a lot @ifrost for your time, really appreciated.

I know for sure that all my docker image running in Kubernetes used to produce logs that were readable in Grafana.

Probably after upgrading one of those (Grafana, Loki or Promtail), **NONE** of my logs (be it a custom node.js or a standard traefik container) are properly displayed in `explore` tab of Grafana.

I actually can't really believe I'm the only affected by this regression?

Here is for instance the logs for `{app="traefik"}`:
![Screenshot from 2021-07-16 22-23-09](https://user-images.githubusercontent.com/47316824/126004551-d4238183-31e1-422a-8776-ad6ca31fe836.png)

I'm 100% sure there weren't that many backslash few months ago.

Note: Everything has been installed using the Grafana helm charts:

```
NAME      	NAMESPACE 	REVISION	UPDATED                                 	STATUS  	CHART            	APP VERSION
grafana   	monitoring	24      	2021-07-15 16:33:22.348583298 +0200 CEST	deployed	grafana-6.13.9   	8.0.5      
loki      	monitoring	11      	2021-07-04 13:50:36.803709367 +0200 CEST	deployed	loki-2.5.2       	v2.2.1     
prometheus	monitoring	8       	2021-07-04 13:49:59.7254792 +0200 CEST  	deployed	prometheus-14.3.0	2.26.0     
promtail  	monitoring	3       	2021-06-22 19:19:24.235193304 +0200 CEST	deployed	promtail-3.6.0   	2.2.1      
```

**Comment by cyriltovena** [comment]
I think the problem is that we're sending JSON to Loki which has to escape those characters.

You'll need to configure promtail to send the log line instead by unwrapping the json payload.


Change this line https://github.com/grafana/helm-charts/blob/main/charts/promtail/values.yaml#L242 in your config and replace `cri` with `docker`.

**Comment by waterdrop01** [comment]
Thanks @cyriltovena for your help.

Here is my full `promtail-custom-values.yml`:
```
config:
  serverPort: 3100
  lokiAddress: http://loki:3100/loki/api/v1/push

snippets:
  pipelineStages:
    - docker: {}
```
Then ran `helm upgrade promtail grafana/promtail --namespace=monitoring --values promtail-custom-values.ymll` but problem is still there (queried the logs in the last seconds on Grafana).

Surprisingly, adding 
```
snippets:
  pipelineStages:
    - docker: {}
```
to my `promtail-custom-values.yml` and running `helm diff` didn't output any change. So this may be that the actual helm upgrade didn't reallly take into account the `cri` to `docker` key name change...?

**Comment by cyriltovena** [comment]
Not sure about helm, can you `kubectl edit` and restart promtail instead.

**Comment by waterdrop01** [comment]
`snippets` key should actually be located under the `config` key, it now works perfectly!

Thanks a lot @cyriltovena for the hint!

For whoever stumble upon this issue, it's actually discussed in more details here: https://github.com/grafana/helm-charts/issues/212

And promtail default config moving from `docker` to `cri` is related to kubernetes deprecating dockershim.

This means that everyon using kubernetes should [migrate from dockershim to either containerd or cri-o](https://kruyt.org/migrate-docker-containerd-kubernetes/)
