### ISSUE TITLE
Time Series Panel: Option to invert series order in legend and tool tip

### ISSUE THREAD

**Issue by tfylling** [grafana/grafana#36054]
**What would you like to be added**:
An option to invert the listing order of the series in the legend and tooltip.

**Why is this needed**:
For stacked graphs it would make it much quicker to jump from plot to value list if the items on said lists appear in the same vertical order as in the graph. Currently it's the exact opposite, which of course can be argued for as well in some cases, so just a toggle would be perfect.
![image](https://user-images.githubusercontent.com/20243684/123043497-a5af2080-d3f8-11eb-9b80-41195ab2038c.png)

**Comment by torkelo** [comment]
duplicate / extension of https://github.com/grafana/grafana/issues/35429

**Comment by Groxx** [comment]
since this seems to be happening again (v9.3.16, tooltip order is always the reverse of the display with "none" sorting): should this be re-opened or should I file a new issue?
