### ISSUE TITLE
AccessControl: Scope evaluated as a string

### ISSUE THREAD

**Issue by gamab** [grafana/grafana#36055]
<details>

<summary>Expand.</summary>

During a pull request review https://github.com/grafana/grafana/pull/35996, I added this test for fun to see if we correctly assessed scopes:

```go
		{
			desc:     "should fail when scope is too narrow",
			expected: false,
			eval:     Permission("reports:read", Combine("reports", ScopeWildcard)),
			params:   nil,
			permissions: map[string]map[string]struct{}{
				"reports:read": {
					"reports:*": struct{}{},
				},
			},
		},
```

This test fails, because we don't actually assess the scope wildcard as a wildcard but as the actual '*' character.

_Originally posted by @gamab in https://github.com/grafana/grafana/pull/35996#r656162202_

</details>

**Description:**

We might have a little security flaw regarding the assessment of access control scopes. When we protect an endpoint with a permission, for instance: `action:"settings:read", scope:"settings:*"` (wildcard => all settings) we assume only users with the permission `action:"settings:read", scope:"settings:*"` will be able to target the endpoint. Same goes for the scope `settings:**` (super-wildcard => all settings sections and all subsections), we assume only users with the super wildcard scope would be able to target the endpoint.
Currently however, we assess this scope as a string and not as the glob(regex) concept it represents. In other word, if a user has permission: `action:"settings:read", scope:"settings:?"` (this scope means, have access to one letter settings) the user will be granted access to the endpoint, same for `action:"settings:read", scope:"settings:[*]"` (this scope means, have access to settings identified by '*'). A more likely example is, if we want to protect an resource with: `action:"settings:read", scope:"settings:**"` but the user has `action:"settings:read", scope:"settings:*"` we would grant him access as well.

We could leverage the pull request's work to have another type of evaluator, let's call it the ExactPermission evaluator. This evaluator would perform an exact match on the scope and not a glob match. We would use it for endpoints we want to protect with specific glob(regex) patterns such as the ones using wildcards or super-wildcards.

**Comment by alexanderzobnin** [comment]
Yes, that definitely makes sense. I think we don't need yet another evaluator, but change existing one.

**Comment by gamab** [comment]
@donomii can we close this one?
