### ISSUE TITLE
CodeEditor: Rich, custom intellisense experience for SQL dialects

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#36061]
**What would you like to be added**:

A lot of data source plugins that use SQL (or a dialect of it) use the [CodeEditor](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Monaco/CodeEditor.tsx) component for building raw sql queries. By specifying any of the [supported monaco languages](https://github.com/microsoft/monaco-languages/tree/main/src), syntax highlighting is added to the editor. Some data sources also use getSuggestions prop to inject suggestions for template variables, macros etc. 

Syntax highlighting and basic suggestions is nice, but without intellisense / autocomplete the user experience is still pretty poor. Using the completion item provider [api](https://microsoft.github.io/monaco-editor/api/interfaces/monaco.languages.completionitemprovider.html) for Monaco, we should be able to create a rich, custom intellisense experience that gives smart suggestions based upon the current position inside the query etc. 

The schema is basically the same for all SQL languages. They have tables, columns, functions, keywords and so on. Therefore, it should be possible to build a generic completion item provider for any sql data source. All the user of the provider would do is to pass tables, columns etc based upon the selected schema. Potentially, it can also provide autocomplete for values that are loaded on demand. 

Currently there's a need for this in the redshift plugin, the athena plugin, the cloudwatch metrics plugin, but I think many more data sources could benefit from this too. 

[This](https://mono.software/2017/04/11/custom-intellisense-with-monaco-editor/) is an example of how custom intellisense is implemented for an xml schema. Think we should be able to do something similar. 

These are some early findings. The end goal here would be to not have to re-implement custom intellisense every time we build a new sql-like data source. Creating this issue to collect some more feedback. 

cc @kminehart @ryantxu

**Comment by joshhunt** [comment]
Alternate reading could be how other similar projects achieve this also. e.g. from InfluxDB https://github.com/influxdata/ui/blob/master/src/shared/components/FluxMonacoEditor.tsx

**Comment by sunker** [comment]
Fixed in https://github.com/grafana/grafana-experimental/pull/8
