### ISSUE TITLE
Permission denied to access property "parentElement" when clicking on "line limit" form field in Firefox

### ISSUE THREAD

**Issue by dror1212** [grafana/grafana#36069]
**What happened**:
JS vm is crashing with Permission denied to access property "parentElement" message when clicking on "line limit" form field.
[crushed like in here](https://github.com/grafana/grafana/issues/23225)

**What you expected to happen**:
Change the limit

**How to reproduce it (as minimally and precisely as possible)**:
I personally used grafana 7.5.8 and loki 2.2.1, happend to me also on 7.2.1 when clicking on the limit to change it on grafana.

**Anything else we need to know?**:
I am working on an isolated environment with no internet access to the outside, used the default grafana configurations.
It's vm based.

**Environment**:
- Grafana version: 7.5.8, 7.2.1
- Data source type & version: Loki 2.2.1
- OS Grafana is installed on: rhel7
- User OS & Browser: Firefox

**Comment by torkelo** [comment]
you might have to do some investigation, what version of firefox? can you update, disable extensions? we have been unable to replicate this

**Comment by dror1212** [comment]
It was indeed the firefox version, thanks, it was a mistake on my side.
