### ISSUE TITLE
Grafana 8.0.x: Stat panel broken

### ISSUE THREAD

**Issue by elcomtik** [grafana/grafana#36075]
**What happened**:
After upgrade to Grafana 8.0.0 (same applies for latest 8.0.3) stat panel broke. 

I mentioned that in https://github.com/grafana/grafana/issues/35475#issuecomment-858377048
![121479584-7812b200-c9ca-11eb-891c-dbcd713a5743](https://user-images.githubusercontent.com/6266956/123099850-dad86480-d432-11eb-8405-d2eddcf7d3b2.png)

I recently tested it at the latest 8.0.3 version but issue still persists. IT shows weird values
![Screenshot 2021-06-23 at 14 52 48](https://user-images.githubusercontent.com/6266956/123100096-15420180-d433-11eb-97bd-8b5f51e92527.png)
or 
![Screenshot 2021-06-23 at 14 58 45](https://user-images.githubusercontent.com/6266956/123100565-8681b480-d433-11eb-8748-324149348e54.png)

**What you expected to happen**:
Show values like before
![Screenshot 2021-06-23 at 14 50 06](https://user-images.githubusercontent.com/6266956/123100066-0fe4b700-d433-11eb-84e4-e9fb84e1541f.png)

**How to reproduce it (as minimally and precisely as possible)**:
Use stat panel and Prometheus data source. Enable "Instant" switch on at least one stat panel.
![Screenshot 2021-06-23 at 14 59 42](https://user-images.githubusercontent.com/6266956/123100727-a618dd00-d433-11eb-967b-33a53cf1ebe7.png)

**Anything else we need to know?**:
This issue was mitigated when I disabled "Instant" on all stat panel instances used on the dashboard.

I would not like to reconfigure all dashboards, anyway I'm not using sparklines so no need for more data than latest value

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: MacOS X Big Sur, Chrome 91.0.4472.106
- Grafana plugins: Stat panel
- Others:

**Comment by torkelo** [comment]
Strange, we have no other reports like this. Can you show what Prometheus returns for the panes that say N/A ? or 2.74? What does prometheus return in those cases? and what are your panel settings?

**Comment by elcomtik** [comment]
I just made a query inspection and here is the output from the Prometheus server. (value is not 2.74, because in this time it changed from the previous one). In my opinion, the Prometheus server works OK. 
![Screenshot 2021-06-23 at 18 35 25](https://user-images.githubusercontent.com/6266956/123135580-41b94600-d452-11eb-9397-9c8fd0f92ce0.png)
![Screenshot 2021-06-23 at 18 34 43](https://user-images.githubusercontent.com/6266956/123135585-43830980-d452-11eb-9e6b-ce1bf9451f9b.png)

**Comment by torkelo** [comment]
* And what did the panel show for that 8.25 result? 
* what happens if you open a N/A panel in edit mode, still show N/A? what does the query return / check table view? 
* Does it only happen when you refresgh all panels, open chrome dev tools network tab, hit refresh see all queries to prometheus. Any thing wrong with the results? 
* On N/A panel if you open inspect / DATA tab what does it show? 
* on a panel that shows the same as another panel (2.74), inspect / data , what does this show?

**Comment by elcomtik** [comment]
I just found what caused the issue. I forgot that I don't use Prometheus directly, but use timeseries caching by [trickster](https://github.com/trickstercache/trickster/). It came up when I looked into chrome dev tools and found out that there are literally the same values for each query. I used trickster version 1.0.3 when I updated it to the latest version 1.1.5, issue just disappeared.

Just for anyone else, I put answers to your question below.

> * And what did the panel show for that 8.25 result?

8.25 for all stat panels on the dashboard.

> * what happens if you open a N/A panel in edit mode, still show N/A? what does the query return / check table view?

Yes, it still shows N/A (N/A is mapped from null).

> * Does it only happen when you refresgh all panels, open chrome dev tools network tab, hit refresh see all queries to prometheus. Any thing wrong with the results?

I tested this, also. All responses were the same.

> * On N/A panel if you open inspect / DATA tab what does it show?

I didn't test this.

> * on a panel that shows the same as another panel (2.74), inspect / data , what does this show?

Inspect must be refreshed, so it will not be useful.

It seems that this issue can be closed.
