### ISSUE TITLE
Variables not updated using flux

### ISSUE THREAD

**Issue by stefanbie** [grafana/grafana#36070]
Hi Im running on Grafana 7.4 and have InfluxData Cloud as datasource. If have a variable for which a value is added to the datanbase, I have to manually update the variables to make it realize there are changes. Even if I run a query with the variable included it wont dynamically update. I have also tried to reload the page but it makes no difference. The only way is to go into variables and manually update.

Variable:
```
import "influxdata/influxdb/schema"

schema.tagValues(bucket: "results", tag: "id")
```
Query:
```
from(bucket: "results")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "test_result")
  |> filter(fn: (r) => contains(value: r["id"], set: ${id:json}))
```

**Comment by gabor** [comment]
hi @stefanbie , i am not able to reproduce the problem. i tried a simplified version of your situation:
- i created a variable with the query you had (i used a different bucketname and tagname)
- i saved the variable and went back to the dashboard
- there is now a select-box with the current values
- now i added a new measurement to influxdb that created a new tagvalue.
- i reloaded the grafana-dashboard-webpage, and now when i open the selectbox i see the new tagvalue


could you repeat this test using the newest grafana version (8.0.4 or later) and tell us if it worked?
if it worked, please also try the whole scenario you are using, if that one is working too, or not.

**Comment by stefanbie** [comment]
I was not able to reproduce this issue on 8.04. Seems to be related to 7.4.

**Comment by gabor** [comment]
@stefanbie i'm glad it works in the current version.
