### ISSUE TITLE
Unsaved changes when someone else saves a dashboard with grafana live on

### ISSUE THREAD

**Issue by gcbirzan** [grafana/grafana#36073]
**What happened**: If you modify a dashboard at the same time with someone else, your current changes get overwritten without any warning.

**What you expected to happen**: A confirmation window should pop asking me if I want the dashboard to reload.

**How to reproduce it (as minimally and precisely as possible)**: Have a dashboard open in two tabs, modify something in one but don't save, modify and save in the other.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: irrelevant
- OS Grafana is installed on: Linunx
- User OS & Browser: Firefox Linux
- Grafana plugins: irrelevant
- Others:

**Comment by torkelo** [comment]
I can confirm this, thanks for reporting it! thought we had a unsaved check here, we will investigate and fix!

**Comment by ryantxu** [comment]
hymmm -- well this explains it:
https://github.com/grafana/grafana/blob/main/public/app/features/live/dashboard/dashboardWatcher.ts#L119

but need to figure out where the change tracker went!
