### ISSUE TITLE
disable scrollbar when embed?

### ISSUE THREAD

**Issue by est** [grafana/grafana#3607]
is it possible to disable this in `grafana.light.min.css` ? 

    ::-webkit-scrollbar {
        width: 8px;
        height: 8px
    }

![1](https://cloud.githubusercontent.com/assets/23570/11999378/3020a0c6-aaf7-11e5-8cbc-275e4351afe4.png)

I knew there might be some reason for this scrollbar to exist that I am unaware of, but can we at least make the scrollbar optional? I want my embedded graphs to be very clean without clutters.

**Comment by torkelo** [comment]
your iframe embedding a graph I take it? What version of grafana and what browser and os are you using? 

Is this iframed panels showing a scrollbar? 
http://docs.grafana.org/guides/whats-new-in-v2/#panel-iframe-embedding

**Comment by est** [comment]
Hi @torkelo,

Yes, I am iframe embedding a graph

>  What version of grafana and what browser and os are you using?

I am using Chrome v41 64bit on win7 64bit, using grafana-2.5.0-1.x86_64.rpm

> Is this iframed panels showing a scrollbar? 

Yes. I took a screenshot

![1](https://cloud.githubusercontent.com/assets/23570/12012917/061d3b72-ad45-11e5-8bfa-ef6e60bd98da.png)

**Comment by jplatte** [comment]
If Grafana were to add the [border-box fix](https://css-tricks.com/box-sizing/), this would be fixed. I didn't check in detail what parts of the layout this affects, but I'd say it's a good idea in general to have this in your CSS.

**Comment by Azef1** [comment]
+1 to patch this scrollbar:
![capture3](https://cloud.githubusercontent.com/assets/15362041/13578637/7218e07a-e499-11e5-9c73-7c38adfc7efa.PNG)
I confim when i delete the border css in grafana.dark.min.css, the scrollbar disappear.
![capture4](https://cloud.githubusercontent.com/assets/15362041/13578753/27317eae-e49a-11e5-89cf-b80317b535da.PNG)

**Comment by torkelo** [comment]
this should be fixed in Grafana 3.0

**Comment by m4rten** [comment]
where is that grafana.dark.min.css stored ?
if i change it, will the next update work without problem if i do so ?

**Comment by yatahaze** [comment]
I'm having this issue on 5.1.2

**Comment by dastrix80** [comment]
I have this same issue, how do we disable the scrollbar?
