### ISSUE TITLE
Thresholds with more than 3 comma-separated values

### ISSUE THREAD

**Issue by adamotte** [grafana/grafana#3608]
According to grafana documentation on SingleStat Panel,

> Thresholds: Change the background and value colors dynamically within the panel, depending on the Singlestat value. The threshold field accepts **3 comma-separated values**, corresponding to the **three colors** directly to the right.

It will be better to allow more than 3 values/colors for example to follow temperature coloring

![temp-colors](https://cloud.githubusercontent.com/assets/1204733/12005953/ed9ee2a8-abbe-11e5-809c-04c347339f90.jpg)

**Comment by bergquist** [comment]
#3601

**Comment by RollingFred** [comment]
+1 
I have 7 log levels. 5 I'd like to colorize differently

**Comment by bmagistro** [comment]
+1
One use case would be a lower/upper "error/fault" zone, a lower/upper "warning" zone, and a nominal zone.
If looking at water levels in a pool (pretend these are in feet and pool is 4 feet max), 0 is probably bad, 1 might be warning, 3.5 might be warning and >4 is probably also bad.  Values between 1 and 3.5 would be what is considered normal so the gauge would show red, yellow, green, yellow, red based on where those values are.

**Comment by nagimov** [comment]
+1
In my case I have both upper and lower limit warnings (e.g. [0..1]: error, [1..2]: ok, [2..3]: error), so custom thresholds with custom colors would be great.

**Comment by daianmartinho** [comment]
+1

**Comment by lelando** [comment]
+1

**Comment by gwuillou** [comment]
Is this feature could be include as in the diagram plugin?(https://grafana.com/plugins/jdbranham-diagram-panel).
![diagram_display](https://user-images.githubusercontent.com/20662503/27961978-c3271920-6330-11e7-9a1d-6d143bf7f280.png)
The goal will be to choice by yourself the color you want for one threshold

**Comment by LastStupid** [comment]
+1
I have 5 state in my case, it would be nice like Diagram plugin

**Comment by mabnz** [comment]
+1

**Comment by bcbane** [comment]
Yes please make this. It would be so useful

**Comment by coussej** [comment]
This would be a great feature for opening up further use cases for the single stat panel. 
The way it is implemented in the diagram plugin looks like a very generic way to deal with this!

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.

**Comment by sunisa-j** [comment]
I suggest to edit Panel JSON.
<img width="671" alt="Screenshot 2019-10-16 02 48 02" src="https://user-images.githubusercontent.com/6669455/66864846-47ddfa80-efc0-11e9-9e39-9750ac6d3b37.png">

You can add a lot of colors as you want according to thresholds setting in options tab.
<img width="878" alt="Screenshot 2019-10-16 02 48 35" src="https://user-images.githubusercontent.com/6669455/66864890-5f1ce800-efc0-11e9-8495-efda7b6bed34.png">

<img width="1370" alt="Screenshot 2019-10-16 02 47 40" src="https://user-images.githubusercontent.com/6669455/66864976-84115b00-efc0-11e9-8734-4b19616b4d30.png">

I hope this can help you :)

**Comment by ryantxu** [comment]
Or just use the gauge panel!
