### ISSUE TITLE
Time series: Laggy tooltips

### ISSUE THREAD

**Issue by uhthomas** [grafana/grafana#36086]
**What happened**:

On Firefox, the tooltips for the new time series visualisation are really jumpy and laggy.

https://user-images.githubusercontent.com/9749173/123133046-4298aa80-d447-11eb-88d1-86dc18795e3a.mp4

**What you expected to happen**:

The tooltips should be nice, like on WebKit browsers.

**How to reproduce it (as minimally and precisely as possible)**:

Use any dashboard with the new time series visualisation.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Time Series
- OS Grafana is installed on: Kubernetes (Docker)
- User OS & Browser: Windows 10, Firefox 89.0.1
- Grafana plugins: N/A
- Others: N/A

**Comment by Mario-Hofstaetter** [comment]
Looks different for me, using Firefox 89.0.1 on Windows 20H2,
on https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1 , `Grafana v8.0.3 (cae5c5e46b)`

¯\\_(ツ)_/¯

https://user-images.githubusercontent.com/33002073/123174358-47c61b80-d480-11eb-8a77-6964345a5e1c.mp4

**Comment by uhthomas** [comment]
For good measure I also just tried using the dashboard from the link you've provided. I see the same behaviour, albeit on a different graph further down.

https://user-images.githubusercontent.com/9749173/123177887-0896cb00-d47e-11eb-8099-7104ce8d019b.mp4

Here's what it looks like in the latest version of Chrome and Edge:

https://user-images.githubusercontent.com/9749173/123177987-39770000-d47e-11eb-9e35-e73f1afee3d0.mp4

**Comment by torkelo** [comment]
And if you try it in chrome is it the same? (Firefox + windows issue?)

**Comment by uhthomas** [comment]
> 
> 
> And if you try it in chrome is it the same? (Firefox + windows issue?)

Edge and Chrome both behave normally per the second video in https://github.com/grafana/grafana/issues/36086#issuecomment-867210691

**Comment by leeoniya** [comment]
we're going to roll out a full rewrite of tooltips soon (`newVizTooltips`). gonna close this since old tooltips code will be removed soon afterwards.
