### ISSUE TITLE
Converting Graph (old) to Time series does not handle series overrides using regex

### ISSUE THREAD

**Issue by Darth-Bobo** [grafana/grafana#36085]
**What happened**: Changing a graph of type "Graph (old)" to the new "Time series" converts a "series override" using a regex into a field "field with name" override instead of a "field with name matching regex" override.

**What you expected to happen**: The series override should convert to a field with name matching regex override where appropriate.

**How to reproduce it (as minimally and precisely as possible)**:
Take any panel of type "Graph (old)", add a series override using a regex in the "Alias or regex" box.
Change the visualisation to "Time series".  The override is converted to the wrong type with an error saying "(not found)".

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.0.1
- Data source type & version: AWS Timestream
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: macOS Big Sur, Firefox 89.0.1
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Hi @Darth-Bobo, 

Thanks for reporting this. I reproduced [your error on our public sandbox](https://play.grafana.org/d/eQQpvRk7z/old-graph-series-override-regex-wont-update-to-new-panel?orgId=1). Let me know if I missed anything 👍 

Confirming the "not found" text in the new override settings, inside the Time Series panel, as well:

![CleanShot 2021-06-23 at 12 55 17@2x](https://user-images.githubusercontent.com/37156449/123178139-4bc35080-d422-11eb-9626-a54ec294137d.png)

**Comment by torkelo** [comment]
We need to detect if alias here contains a regex and use a regex matcher instead: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/timeseries/migrations.ts#L115
