### ISSUE TITLE
[grafana v8 - ngalert] Failed to fetch

### ISSUE THREAD

**Issue by waterdrop01** [grafana/grafana#36092]
I upgraded to Grafana V8 and enabled ngalert feature.

When navigating to `alerting/notifications/receivers/new?alertmanager=grafana` and clicking on:
![Screenshot from 2021-06-23 19-34-09](https://user-images.githubusercontent.com/47316824/123142714-0589e380-d45a-11eb-8f96-bcc5353a6f51.png)

Setting an email contact point and then clicking on: 
![Screenshot from 2021-06-23 19-34-14](https://user-images.githubusercontent.com/47316824/123142751-0de21e80-d45a-11eb-9eeb-7a04f92b192c.png)

It hangs like this for 1 minutes:
![Screenshot from 2021-06-23 19-34-00](https://user-images.githubusercontent.com/47316824/123142815-24887580-d45a-11eb-81e4-5cf0d0c7954c.png)

And finally displays this error:
![Screenshot from 2021-06-23 19-32-49](https://user-images.githubusercontent.com/47316824/123142845-2d794700-d45a-11eb-9e67-6e7bfdcf988a.png)

It seems like the POST request never reach the server.

Any help would be welcome.

**Comment by dsiperek-vendavo** [comment]
You should have a page like this:
![image](https://user-images.githubusercontent.com/70541548/123148340-f92f6780-d414-11eb-89cf-0f8017304aed.png)
I have no issues getting something to save.

**Comment by waterdrop01** [comment]
Thanks @dsiperek-vendavo for your help. I have the exact same page as you, but impossible to save anything.

This might be related to this issue https://github.com/grafana/grafana/issues/36079 as well as this issue https://github.com/grafana/grafana/issues/36079?

The contact points interface is acting weirdly (like it's disconnected from the backend somehow) request doesn't make it through...

**Comment by papagian** [comment]
@waterdrop01 thanks for reporting this. Could you check in your browser's developer tools network tab if there are any failing requests to `/api/alertmanager/grafana/config/api/v1/alerts`?
Also do you see any errors on the server logs? Can you share them? thank you!

**Comment by xens** [comment]
@waterdrop01 I had more or less the same issue; I've had a bunch of Slack / Teams alerts defined on some dashboards -> upgraded from 7.x to 8.0 -> activated `ngalert` -> was unable to edit / create / delete anything in the new Alerting panels (Alert rules, Silences, Contact points, Notification Policies).

I've obtained `504` from my CDN saying that the backend was unreachable

![image](https://user-images.githubusercontent.com/1699826/124079468-78422280-da49-11eb-981b-98322d9f97bb.png)

On the Grafana-side I couldn't find stack-traces or anything (I was in logging=trace).

So I believe something went wrong during the old->new alert conversion.

What I did to fix it (I'm on K8s + external mysql DB):

1. Launched a tooling container (alpine), installed the mysql-client tools
2. Connected to the DB
3. Truncated the alert_configuration table `TRUNCATE alert_configuration;`
4. Restarted the Grafana deployment

After that I could create new Alert rules, Silences, Contact points, Notification Policies.

Hope this helps.

**Comment by waterdrop01** [comment]
@xens you nailed it! It worked for me as well (late reply as I didn't receive any email notification from Github following your message).

The only difference is that my grafana is using local sqlite3 db `/var/lib/grafana/grafana.db`.

I deployed the below ubuntu pod and attached it to grafana pvc:
```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu
spec:
  volumes:
    - name: ubuntu-pv-claim
      persistentVolumeClaim:
        claimName: grafana
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
        - mountPath: "/var/lib/grafana"
          name: ubuntu-pv-claim
```
and then, as sqlite3 doesn't support `TRUNCATE`, I ran `DELETE FROM alert_configuration;`

Finally, my alerts are back!!!
