### ISSUE TITLE
Minified React error #185 when reaching Grafana home page

### ISSUE THREAD

**Issue by Shadorc** [grafana/grafana#36096]
**What happened**: Since 8.0.X, loading the Grafana page displays this error beforer showing anything else. The page is also constently reloading.
```
An unexpected error happened
DétailsError: Minified React error #185; visit https://reactjs.org/docs/error-decoder.html?invariant=185 for the 
full message or use the non-minified dev environment for full errors and additional helpful warnings.
```

![Animation](https://user-images.githubusercontent.com/6506416/123176997-bf964500-d484-11eb-8854-4a6f406d8103.gif)

**What you expected to happen**: The authentication page is shown.

**How to reproduce it (as minimally and precisely as possible)**: I just tried to reach my Grafana page with `http://<my_ip>:3000`, like I always did.

**Anything else we need to know?**: The full error message according to React website is
```
Maximum update depth exceeded. This can happen when a component repeatedly calls setState inside 
componentWillUpdate or componentDidUpdate. React limits the number of nested updates to prevent infinite loops.
```

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 20.02.2
- User OS & Browser: Windows 10 & Vivaldi
- Grafana plugins: None

**Comment by torkelo** [comment]
maybe an issue with Vivaldi? can you try another browser? do you have a custom home dashboard?

**Comment by Shadorc** [comment]
Indeed, it's an issue with Vivaldi, it works fine on Firefox. 
I don't have a custom home dashboard.

I don't know if it's a Grafana issue on Vivaldi or a Vivaldi issue so feel free to close this issue if needed 
Thanks !

**Comment by ivanahuckova** [comment]
@Shadorc Thank you very much for verifying that Grafana works on [supported browser](https://grafana.com/docs/grafana/latest/installation/requirements/#supported-web-browsers). 🙏 I am going to close the issue as Vivaldi is not on our list of supported browser.

**Comment by lspaula** [comment]
Is it possible to reopen this? It started to happen in many other browsers, including Chrome (103.0.5060.134), Samsung Internet (17.0.7.34) and Edge (103.0.1264.77 ). It happens when there is a large number of items. I've tried with only a few items and it works fine. Is this a limitation or configuration of the browser. It stopped working a few days ago and was working ok prior to that.

**Comment by ivanahuckova** [comment]
@lspaula feel free to open new issue with more details on the issue.

**Comment by wenbya** [comment]
Is there anyone face the same problem in "deploy grafana in azure kubernetes service" ? it just a simple yaml file with grafana latest image.
