### ISSUE TITLE
Labels to Fields Transformation No Options Found

### ISSUE THREAD

**Issue by kdorsel** [grafana/grafana#36095]
**What happened**: The labels to fields transformation does not show a list of labels.

![image](https://user-images.githubusercontent.com/2569415/123168937-a8d0fd80-d446-11eb-9db6-27b14118c11f.png)

**What you expected to happen**: Shows the list of labels from which one can be selected

**How to reproduce it (as minimally and precisely as possible)**:

The following query will reproduce the results. Query format is table.

```
select '2021-06-06'::date as time, 'c' as cluster, 'machine1' as machine, 234 as val
union
select '2021-06-06'::date as time, 'c' as cluster, 'machine2' as machine, 23 as val
union
select '2021-06-06'::date as time, 'c' as cluster, 'machine3' as machine, 543 as val
union
select '2021-06-06'::date as time, 'c' as cluster, 'machine4' as machine, 432 as val
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Postgres 12.3
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10 Edge 91
- Grafana plugins: N/A
- Others: N/A

**Comment by torkelo** [comment]
your query already returns fields (columns), there are no labels there (mainly used by time series databases)

**Comment by kdorsel** [comment]
My expectation is that the result is similar to the docs https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#labels-to-fields.

This is the query result:
| Time | Cluster | Machine | Value |
| ----- | -------- | --------- | ------ |
| 2021-06-06 | C | Machine1 | 250 |
| 2021-06-06 | C | Machine2 | 550 |
| 2021-06-06 | C | Machine3 | 750 |
| 2021-06-06 | C | Machine4 | 350 |

This is the after transformation result desired:
| Time | Cluster | Machine1 | Machine2 | Machine3 | Machine4 |
| ----- | -------- | ----------- | ---------- | ----------- | ----------- |
| 2021-06-06 | C | 250 | 550 | 750 | 350 |

Based on my understanding of the Labels to fields this is the intended purposes. So in this case the machine column is the one that should be chosen from the dropdown.

**Comment by bn1** [comment]
I'm having same issue using Postgres database for the very same use case. What's the solution?

**Comment by kdorsel** [comment]
Currently none. You would need to use a pivot table in postgres to achieve this. There's lots of info on stackoverflow about this topic, but unless you have a fixed # of items it's not pretty.

I currently just skipped this Grouped Bar Chart. My use case for this was displaying aggregated downtime as a grouped bar chart for every day entry.

Might be worth a ping or a new Issue as once closed it's very unlikely to get another comment.

**Comment by ryantxu** [comment]
If you are using postgres at v8+ -- can you try selecting the "timeseries" type?  This will do a "Long to Wide" conversion that *I think* will give you:

| Time | {cluster=C, machine=Machine1} |  {cluster=C, machine=Machine2}  |  {cluster=C, machine=Machine3}  |  {cluster=C, machine=Machine4}  |
| ----- | -------- | ----------- | ---------- | ----------- |
| 2021-06-06 | 250 | 550 | 750 | 350 |

**Comment by kdorsel** [comment]
Actually, yes. That does produce the desired results based on testing.

However there is a catch 22. The goal of doing this was to use the Bar Chart visualization with weeks as the X axis. However Bar Chart requires that the X axis be a string. For this Long to Wide conversion with the Timeseries type it requires the datetime column which the Bar Chart does not support for the X axis.

**Comment by bn1** [comment]
@ryantxu can you provide me simple example of that query? Finally I ended up with `crosstab()` query using hard-coded columns in the query.

**Comment by kdorsel** [comment]
@bn1 Create a new panel and use this as a query

```
select '2021-06-06'::date as time, 'machine1' as machine, 234 as val
union
select '2021-06-06'::date as time, 'machine2' as machine, 23 as val
union
select '2021-06-06'::date as time, 'machine3' as machine, 543 as val
union
select '2021-06-06'::date as time, 'machine4' as machine, 432 as val
```

And make sure to set Format As: Timeseries. It wil convert it over for you. From my testing it only works with a single metric hence this dropping the cluster column.

**Comment by ffisc** [comment]
Also having a similar issue (with InfluxDB data source). Table looks broadly like Time | Category | Value.
But in my case **the value is not a number**, it's a text, so I cannot format the table as a timeseries.
Any thoughts on what to do?

**Comment by bilykigor** [comment]
Same issue

**Comment by Noobgam** [comment]
Apparently grafana is very picky when deciding to transform.

In my case, I have a mysql that emits the following:
```
SELECT UNIX_TIMESTAMP(FROM_UNIXTIME(date / 1000)) as time_sec, `count` as value, srs_level
      FROM noobgam_personal.language_learning
```
![image](https://github.com/grafana/grafana/assets/10178515/badcbd78-2dd5-4ca8-a109-d793f2b41fa9)


And grafana does not seem to want to convert it with that transformation.

Although when prompted with a bit of a different query, that is indistinguishable in Grafana UI it succeeds and does what you expect it to do

```
SELECT ROUND(UNIX_TIMESTAMP(FROM_UNIXTIME(date / 1000)), 0) as time_sec, `count` as value, CONVERT(srs_level, NCHAR) as srs_level
      FROM noobgam_personal.language_learning;
```

However sad this is, probably the best solution is to make the pivot table on the SQL side whenever possible and not rely on the frontend to do this
![image](https://github.com/grafana/grafana/assets/10178515/aefa2f09-9cd9-4699-bde5-9cb1cafbe557)
