### ISSUE TITLE
[NG-Alerting] Silences are lost after restart

### ISSUE THREAD

**Issue by weiwu-sre** [grafana/grafana#36099]
**What happened**:
Silence is not persisted to database, when restart pod on Kubernetes.

I also tried to run multiple Grafana pods. But silence info disappears during browser refresh. That makes me think that silence data is stored on local disk instead of persisting to backend database.

**What you expected to happen**:
Silence should load from database after restart or re-deploy

**How to reproduce it (as minimally and precisely as possible)**:
- Deploy Grafana to Kubernetes with Mysql backend and ngalert feature flag enabled
- Create a silence on Grafana
- Delete Grafana Pod
- Load alerting/silences page

**Anything else we need to know?**:

Looking at the log from the pod. I saw a panic may related to this issue.
```
t=2021-06-23T23:52:10+0000 lvl=eror msg="Request error" logger=context userId=63 orgId=1 uname=wei.wu error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:212 (0x4369fa)\n/usr/local/go/src/runtime/signal_unix.go:734 (0x450412)\n/root/go/pkg/mod/github.com/prometheus/alertmanager@v0.22.2/dispatch/route.go:146 (0x16619b7)\n/drone/src/pkg/services/ngalert/notifier/alerts.go:54 (0x1b46b5d)\n/drone/src/pkg/services/ngalert/api/api_alertmanager.go:138 (0x231bece)\n/drone/src/pkg/services/ngalert/api/forked_am.go:93 (0x2324f58)\n/usr/local/go/src/reflect/value.go:476 (0x4a67a6)\n/usr/local/go/src/reflect/value.go:337 (0x4a5c78)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1047816)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1047191)\n/drone/src/pkg/services/ngalert/metrics/metrics.go:140 (0x1ad81dc)\n/usr/local/go/src/reflect/value.go:476 (0x4a67a6)\n/usr/local/go/src/reflect/value.go:337 (0x4a5c78)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1047816)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1047191)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x1049b7c)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1bce505)\n/drone/src/pkg/middleware/request_metrics.go:55 (0x1bce4f0)\n/usr/local/go/src/reflect/value.go:476 (0x4a67a6)\n/usr/local/go/src/reflect/value.go:337 (0x4a5c78)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1047816)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1047191)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x1049b7c)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1bce384)\n/drone/src/pkg/middleware/recovery.go:166 (0x1bce377)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:81 (0x10499f2)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0x1047511)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0x1047284)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x1049b7c)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1bcc431)\n/drone/src/pkg/middleware/logger.go:35 (0x1bcc405)\n/usr/local/go/src/reflect/value.go:476 (0x4a67a6)\n/usr/local/go/src/reflect/value.go:337 (0x4a5c78)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1047816)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1047191)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x1049b7c)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:115 (0x1bcf617)\n/drone/src/pkg/middleware/request_tracing.go:56 (0x1bcf60a)\n/usr/local/go/src/reflect/value.go:476 (0x4a67a6)\n/usr/local/go/src/reflect/value.go:337 (0x4a5c78)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0x1047816)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0x1047191)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/context.go:125 (0x1049b7c)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/router.go:187 (0x105b5d0)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/router.go:303 (0x1055d25)\n/root/go/pkg/mod/gopkg.in/macaron.v1@v1.4.0/macaron.go:220 (0x104ee4c)\n/usr/local/go/src/net/http/server.go:2887 (0x71b562)\n/usr/local/go/src/net/http/server.go:1952 (0x716a8c)\n/usr/local/go/src/runtime/asm_amd64.s:1371 (0x473020)\n"
```

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Grafana
- OS Grafana is installed on: Kubernetes v1.20.7 Amazon Linux2
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by codesome** [comment]
The panic seems unrelated to the persistence of silences, I will check that. 
And yes, silences are stored on disk (and even notification log) at the moment and requires same disk to be attached after a restart.

**Comment by codesome** [comment]
I have adjusted the title based on the issue description and opened https://github.com/grafana/grafana/issues/36114 for the panic

**Comment by codesome** [comment]
After some offline chat, the conclusion is that to use the new alerting, running Grafana as a statefulset and attaching a PVC to the workload is a requirement. There are no plans to support storing silences and notification log in the database. (If this info was not present in the docs, it will be added soon)

**Comment by weiwu-sre** [comment]
Thanks for looking into this.

Does this mean this new alerting feature does not support HA mode ? 

What will happen if I have two statefulset pods with PVC enabled ? When I create a new silence. is this new silence going to be populated on both pods ?

**Comment by codesome** [comment]
> When I create a new silence. is this new silence going to be populated on both pods ?

Not yet. And HA is not supported _yet_ for the new alerting, we are actively looking into it.

**Comment by dsiperek-vendavo** [comment]
I have PVC and still lost the silences...   Not sure how they got lost but all of my silences are gone and I can still see the alerts i created.

**Comment by codesome** [comment]
@dsiperek-vendavo Is Grafana running as statefulset? Or is it getting attached to same PVC after restart? Additionally, was it a graceful restart?

**Comment by torkelo** [comment]
@codesome where are silences stored on disk? Some where under the data path?  (/var/lib/grafana for a normal linux install)

**Comment by codesome** [comment]
@torkelo they are stored in this file inside the data path: `$datapath/alerting/silences`

**Comment by torkelo** [comment]
Great, then as long as this mounted to a persisted volume it should work

**Comment by dsiperek-vendavo** [comment]
> @dsiperek-vendavo Is Grafana running as statefulset? Or is it getting attached to same PVC after restart? Additionally, was it a graceful restart?

It attaching to same PVC after restart and restart was graceful.

**Comment by dsiperek-vendavo** [comment]
I just lost all silences with manually deleted the container just now.  kubectl delete pod/prometheus-ha-grafana-67c7c57b7b-ps75j

**Comment by codesome** [comment]
@dsiperek-vendavo I highly suspect the data directory goes missing/deleted between restart in your case. With an intact directory, I am able to get the silences back on restart.

**Comment by codesome** [comment]
@weiwu-sre I am investigating the panic that you have posted in the issue description. Did the panic happen right after you restarted Grafana or after some time it was all up and running? The only case that I see the panic can happen is trying to get the alerts in browser as soon as Grafana is up before the Alertmanager component in the new alerting is initialised.

The panic needs to be fixed either way, but making sure that there is no other way that the panic can happen.

**Comment by weiwu-sre** [comment]
> @weiwu-sre I am investigating the panic that you have posted in the issue description. Did the panic happen right after you restarted Grafana or after some time it was all up and running? The only case that I see the panic can happen is trying to get the alerts in browser as soon as Grafana is up before the Alertmanager component in the new alerting is initialised.
> 
> The panic needs to be fixed either way, but making sure that there is no other way that the panic can happen.

Yup. Panic happened right after Grafana pod restart.

**Comment by achatterjee-grafana** [comment]
@codesome, can we close this issue based on PR https://github.com/grafana/grafana/pull/36808?
