### ISSUE TITLE
[bug] Grafana 8 missing feedback / error-handling from Cloudwatch

### ISSUE THREAD

**Issue by bgardner-noggin** [grafana/grafana#36097]
**What would you like to be added**:
Previously in Grafana 7, if a widget utilising a cloudwatch data source returned a warning, this warning would be displayed in the top left of the widget with the details.

An example is if the user queries a metric over a large time span, and Cloudwatch truncates the data, the user received a message that the data is truncated and they need to lower their timestamp

In Grafana 8, this no longer appears. I can't even see it anywhere in the Query inspector output
![Cloudwatch-error](https://user-images.githubusercontent.com/3347206/123178747-35250400-d4cb-11eb-9c2f-6ac5bad90f14.png)

**Why is this needed**:
Show feedback to the user if there is a problem with the query / timestamp

**Comment by zuchka** [comment]
Hi @bgardner-noggin 

Thank you for reporting this issue. I see that you've made a very similar bug report in May. I've closed that one in favor of this one.

In the future, please try your best to fill out our issue template in its entirety. The more information the squads have, the better and faster they can assist you.

**Comment by sunker** [comment]
@bgardner-noggin I believe these type warnings (it's not an error - just a warning that indicates that you're not seeing all data points in grafana) are now displayed as a warning icon at the top, in the middle of the panel. If you hoover that icon, you should see the same message. 
![Screenshot from 2021-06-29 23-16-53](https://user-images.githubusercontent.com/2388950/123869082-d7604400-d930-11eb-884d-3ebccbf9a962.png)

**Comment by bgardner-noggin** [comment]
Ahh yes, there it is.

Might I suggest that it should be in a different colour. I had no idea it was there.

**Comment by sunker** [comment]
Would you mind creating a feature request for that? 

I'll go ahead a close this issue now. Thanks for reporting this @bgardner-noggin
