### ISSUE TITLE
[Docs] feedback: /datasources/elasticsearch.md

### ISSUE THREAD

**Issue by haelekuin** [grafana/grafana#36103]
The example URL https://play.grafana.org/dashboard/db/elasticsearch-templated under https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#using-variables-in-queries is an invalid URL.

https://play.grafana.org/d/CknOEXDMk/elasticsearch-templated is the correct one

**Comment by zuchka** [comment]
Hi @haelekuin thanks a bunch for this issue. Just submitted a docs patch that should close this
