### ISSUE TITLE
Show tag name suggestions for OpenTSDB

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#3610]
![image](https://cloud.githubusercontent.com/assets/89186/12012283/96d59ca0-ace5-11e5-9b1d-f8d1c20e0791.png)

At this point of adding a metric on the graph you already have something plotted, which means you have query response:

![image](https://cloud.githubusercontent.com/assets/89186/12012284/c375f0b6-ace5-11e5-8881-e7fd6a07badf.png)

There is a value in suggesting these tag values in the tag key box.

**Comment by utkarshcmu** [comment]
Tag key/value suggestion works using opentsdb's suggestion api. Isn't it working in 2.6?

**Comment by bobrik** [comment]
@utkarshcmu are you talking about the one that requires 2x load on HBase?

I just upgraded 2.5.0 -> 2.6.0 and see irrelevant tag name suggestions:

![image](https://cloud.githubusercontent.com/assets/89186/12020885/f164b9ba-ad78-11e5-9987-744e0600ebf4.png)

**Comment by utkarshcmu** [comment]
So, there are two apis which provide tag keys and tag values. 

1. Lookup api which is more heavy on opentsdb but provide relevant suggestions based on the metric name.

2. Suggest api which is lightweight and keeps the load on opentsdb low for getting metadata. But it just provide tag names and values according to the typeahead suggestions and not relevant to the metric name.

In 2.6 , Grafana uses suggest api which keeps the load on Opentsdb low. 

Sometimes I feel that lookup api was better but mostly suggest api works way better.

**Comment by bobrik** [comment]
My point is: you have relevant tag names after initial query execution. You don't need any other APIs to make it work. Zero extra API calls required.

Tag values are different, though. I'd argue that you can fetch tags and values from different storage (elasticsearch) instead of relying on OpenTSDB, but that's for another issue.

**Comment by utkarshcmu** [comment]
So, you mean to say that, we should use lookup api instead of suggest api for querying tag names which will make more sense? Is that what we need to resolve the issue?

**Comment by bobrik** [comment]
> My point is: you have relevant tag names after initial query execution. You don't need any other APIs to make it work. Zero extra API calls required.

No mention of lookup api here, because it is irrelevant.

Query that gets executed when you enter metric name:

```
# curl -s 'http://opentsdb/api/query' -d '{"start":"5s-ago","queries":[{"metric":"tsd.hbase.rpcs","aggregator":"sum","rate":true,"rateOptions":{"counter":false},"downsample":"5s-avg","tags":{}}]}' | jq .
[
  {
    "metric": "tsd.hbase.rpcs",
    "tags": {},
    "aggregateTags": [ <-- THESE TAGS ARE RELEVANT TO THE QUERY
      "type",
      "host"
    ],
    "dps": {
      "1451377285": 45734.299999999996
    }
  }
]
```

You have tag names here, they are relevant, use them.

**Comment by torkelo** [comment]
Grafana is using OpenTSDBs metric inspection api for this, if they are irrelevant complain to the OpenTSDB project :)

**Comment by torkelo** [comment]
I already tries switching to the "relevant api" and that caused an uproar (due to high load)

**Comment by bobrik** [comment]
Funnily enough, OpenTSDB UI uses query results to suggests relevant tag values. Let me try to make a point again: you need to use 0 (zero) APIs to make it work. How much load can you introduce by 0 extra API calls exactly?

**Comment by torkelo** [comment]
@bobrik  well grafana supports many data sources and uses a data source plugin api that is used for many things, like the metric names and tags api is used for template variables and for typeahead completion in the editor (through the same plugin api abstraction). But it's looks like this could be improved by some clever caching of tags, and knowing if a tag inspection query came from the query editor. But then if you have multiple queries then what tags to show? OpentTSDB results are impossible to match to the originating query (with 100% accuracy), but that problem might be minor  (some tag suggestions would be wrong coming from another query). 

Anyway, I agree with you that there is possibility to improve the editor suggestions, PR please? :)

**Comment by bobrik** [comment]
Sorry, I don't follow. Are you telling me that you can't tell what response came for `myquery2` to show tag name suggestions relevant to it? I'm not asking for anything else.

1. User enters metric name
2. User changes focus / picks a metric from dropdown / triggers query by any other action
3. Grafana asks OpenTSDB to give back results
4. Tags from query are used as suggestions in tag name dropdown for that query

I don't see how this requires some black magic to work. What caching are you talking about? What tag inspection query? Why multiple queries make it harder?

![image](https://cloud.githubusercontent.com/assets/89186/12180327/d4889052-b573-11e5-89bb-4174eeaf9dfd.png)

**Comment by torkelo** [comment]
as I said your welcome to submit a PR, I am sure it's going to be easy, I might have misunderstood you and thought it more complicated than needed. I though you wanted to reuse the metric request result used used for rendering graph in the typeahead completion :)

**Comment by bobrik** [comment]
If it makes sense, please reopen the issue.

**Comment by utkarshcmu** [comment]
@bobrik Your suggestion will perfectly for suggesting Tag Keys. But we still need to use lookup/suggest API to make a call to get Tag values. Right?

**Comment by bobrik** [comment]
Yes, that's right. That's how OpenTSDB UI works.

**Comment by digrich** [comment]
I completely agree with @bobrik's  point here. In 2.6, irrelevant tag key/value suggestions are creating lot of confusions. I can't really upgrade to 2.6 because of this issue. It would be really hard for many people to know exactly what tags are relevant for the metric key. 

Can we please re-open this issue?

**Comment by utkarshcmu** [comment]
+1 for Reopening this issue ... will try to fix this ASAP...

**Comment by utkarshcmu** [comment]
I think switch to suggest_api was not as useful as we thought (#2840). Also, as specified by @bobrik in this issue, we can cut down tag_keys query and get the tag_keys from the metric query call.

Any thoughts?

**Comment by torkelo** [comment]
Sounds good!
