### ISSUE TITLE
Grafana managed alert with Loki datasource: unsupported result format: "streams"

### ISSUE THREAD

**Issue by sbellan** [grafana/grafana#36108]
**What happened**:
While creating alert rule with Loki data source, received the error, `Failed to evaluate queries and expressions: failed to execute conditions: unsupported result format: "streams"`. Selecting "Preview" or "Run queries" in the page shows this error. 

**What you expected to happen**:
Not to run into this error while creating alert rule.

**How to reproduce it (as minimally and precisely as possible)**:

- Create alert rule - type "Grafana managed alert"
- Query - "Loki" datasource
- "A" Enter query
- Leave the default for "B" condition (last() of A "IS ABOVE" 3)
- Hit "Run queries". you will receive the error

**Anything else we need to know?**:
Saving alert works fine and even the alert gets triggered. But the "health" of the alert show "error"
![image (2)](https://user-images.githubusercontent.com/428882/123227981-f458cb00-d489-11eb-8208-b26d73aba211.png)

**Environment**:
- Grafana version: Grafana v8.0.3 (cae5c5e46b)
- Data source type & version: Loki 2.2.0
- OS Grafana is installed on: Linux (k8s Pod)
- User OS & Browser: MacOS, Chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Alerting should work only on metrics queries, not on logs. As it is mentioned in [documentation here](https://grafana.com/docs/loki/latest/api/#matrix-vector-and-streams) _Stream: a Stream is a set of all values (logs) for a given label set over the queried time range. Streams are the only type that will result in log lines being returned._ So even if we processed streams on backend, the alerting wouldn't work cause the returned data is in form of log lines, not metrics.

**Comment by ivanahuckova** [comment]
@sbellan Could you please confirm that the query that you run was Loki logs query and that there is no problem with Loki metrics query?

**Comment by sbellan** [comment]
Thank you @ivanahuckova for the clarification. Though i would say that even with the warning the alerting works some times on Loki logs query. What is the correct way to create an alert based on some text on log (eg. if a specific text showed up in the logs more than 3 times in the last minute..etc) or is that use case not valid?

**Comment by ivanahuckova** [comment]
I recommend checking out https://grafana.com/docs/loki/latest/logql/#range-vector-aggregation

So for what you are asking, the query could be `count_over_time({job="my_app"} |= "text I am searching for" [1m])` as `count_over_time`  counts the entries for each log stream within the given range.

**Comment by sbellan** [comment]
Perfect. Thank you, so much.

**Comment by ivanahuckova** [comment]
I am going to close the issue as we support alerting only on metrics queries, not on log queries.
