### ISSUE TITLE
[Grafana 8] Explore doesn't toggle datasource instances correctly

### ISSUE THREAD

**Issue by spech66** [grafana/grafana#36104]
**What happened**:

Have multiple Datasources of the same type (MySQL Prod, Dev, Test, ...).
Go to Explore and enter some SQL to create a table view.
Switch to another Datasource of same type. The old datasource is still used.

**What you expected to happen**:

The new Datasource is used.

**How to reproduce it (as minimally and precisely as possible)**:

See steps above.

**Anything else we need to know?**:

The query URL is not changing correctly:
Initial: `.../explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22ProdDB%22,%7B%22datasource%22:%22ProdDB`
After change: `.../explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22DevDB%22,%7B%22datasource%22:%22ProdDB`

In Grafana 7 or on entering the Explore view again the datasource in the URL is changed correctly.

**Environment**:
- Grafana version: 8.0.0 and 8.0.2
- Data source type & version: MySQL - core version
- OS Grafana is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: Ubuntu 20.04.2 LTS and Chrome 91.0.4472.114
- Grafana plugins: -
- Others: -

**Comment by zsiciarz** [comment]
Same here on Grafana 8.0.3 and Postgres datasources.

**Comment by dsotirakis** [comment]
Looping in @grafana/observability-squad

**Comment by ivanahuckova** [comment]
Thanks for creating the issue! I was able to reproduce as well.
