### ISSUE TITLE
EPIC: HA/MT support for the Plugin Catalog

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#36111]
**Why?**:
The ability for the Plugin Catalog to be synced across multiple Grafana instances

Having a separate plugin service would enable:
- Plugin installs without restarts in Grafana Cloud, possible to install directly without going over the grafana.com portal
- Plugin CDN configuration centralized and easier to manage
- Less burden on plugin administration via HG API
- Remote Plugins provisioning

**Who is the first target group?**
- Hosted Grafana / Grafana Cloud only

**Comment by mckn** [comment]
What do you think about changing this feature so we store the configuration of what plugins that should be installed in the database? then we can change the grafana instance to just mirror that state. If we add or remove anything to the central configuration in the database each instance will try to remove/add the plugins to be in sync with the central configuration.

**Comment by wbrowne** [comment]
Yep that's one of the options covered in the original design doc. There's some work to do to figure out with other teams how we want to handle these types of HA use cases in general, but that is certainly an option.

**Comment by tolzhabayev** [comment]
Closing this one until we have more clarity on how we want to approach this.
