### ISSUE TITLE
$__timeFilter handles DATEADD function incorrectly

### ISSUE THREAD

**Issue by jtommi** [grafana/grafana#36127]
**What happened**:
Here is the part of the query from the panel editor:
```
WHERE
$__timeFilter(DATEADD(hour, 15, CASE
		WHEN logs.id IS NULL THEN comp.creation_date
		ELSE logs.creation_date
	END))
```
and here is the executed query:
```
WHERE
DATEADD(hour BETWEEN '2021-05-25T13:45:25Z' AND '2021-06-24T13:45:25Z')
```

**What you expected to happen**:
The executed query should be
```
WHERE
DATEADD(hour, 15, CASE
		WHEN logs.id IS NULL THEN comp.creation_date
		ELSE logs.creation_date
	END)  BETWEEN '2021-05-25T13:45:25Z' AND '2021-06-24T13:45:25Z'
```

**How to reproduce it (as minimally and precisely as possible)**:
Use my above example in a WHERE and observe the syntax error.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.0
- Data source type & version: SQL Server
- OS Grafana is installed on: don't know
- User OS & Browser: Win10, tried on Firefox and Brave

**Comment by jtommi** [comment]
If someone stumbles accross this same issue, here is a simple workaround
```
WHERE
	'${__from:date:iso}' <= DATEADD(hour, 15, CASE
		WHEN logs.id IS NULL THEN comp.creation_date
		ELSE logs.creation_date
	END)
	AND
	'${__to:date:iso}' >= DATEADD(hour, 15, CASE
		WHEN logs.id IS NULL THEN comp.creation_date
		ELSE logs.creation_date
	END)
```

**Comment by marefr** [comment]
Thanks. For these advanced use cases would recommend using `WHERE <date> >= $__timeFrom() AND <date> <= $__timeTo()` rather than `$__timeFilter(<column>)`

**Comment by marefr** [comment]
Duplicate of #18765
