### ISSUE TITLE
Make hyperlinks blue in info tooltips

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#36122]
When I hover over an (i) info tooltip containing a hyperlink, I want the hyperlink to render and blue and underlined, so that I know I can click on it. In light mode, I'd like to be able to see it.

An example of a tooltip with a hyperlink is the Grafana 7.4 Variables config screen, on the Regex field.

Current state:
Light mode:
![Screen_Shot_2021-02-16_at_1_23_29_PM.png](https://images.zenhubusercontent.com/5f4cdf05aae72098bcd13cbb/0cae4284-ac28-4a4c-af63-a696fc5febb2)

Dark mode:
![Screen_Shot_2021-02-16_at_1_24_25_PM.png](https://images.zenhubusercontent.com/5f4cdf05aae72098bcd13cbb/0e4db834-d819-4de0-82f2-7a5ccd0c8d77)

**Comment by tharun208** [comment]
@mjseaman I like to work on this issue
