### ISSUE TITLE
Grafana 8 - Alert on Cloudwatch Logs Not Working

### ISSUE THREAD

**Issue by EthanMcL** [grafana/grafana#36139]
Trying to create an alert based on a cloudwatch log insight.  Running v8.0.3.

I've tried many different queries, and they work in a dashboard panel to return time series data, to be able to create alerts from if need be.  However I can not get any queries to work from the new Alerts page.

Sample query: stats count(*) by bin(30s)

`Error
Failed to evaluate queries and expressions: failed to execute conditions: failed to query data: ValidationError: Error in expression 'queryA': Invalid syntax status code: 400, request id: <omit>`

**Working from Dashboard Panel:**
![grafana2](https://user-images.githubusercontent.com/18131775/123296572-218a9500-d4ed-11eb-8287-5644bc0d244a.png)

**Not Working from Alert Creation Screen:**
![grafana](https://user-images.githubusercontent.com/18131775/123296163-ca84c000-d4ec-11eb-8b40-375c5e2caa7d.png)

**Comment by zuchka** [comment]
Hi @EthanMcL 

thanks for creating this issue. Anything interesting in your browser's dev tools when you throw this error?

**Comment by zuchka** [comment]
I was able to reproduce on an [internal instance running 8.0.0-beta3](https://g80-beta.grafana.net/alerting/new?returnTo=%2Falerting%2Flist).

I was also able to throw the error running a 8.0.3 container and adding an empty, unconfigured Cloudwatch DS:
`docker run -p 3000:3000 -e "GF_INSTALL_PLUGINS=grafana-singlestat-panel, marcusolsson-json-datasource" -e "GF_FEATURE_TOGGLES_ENABLE=ngalert" -e "GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true" -e "GF_PANELS_DISABLE_SANITIZE_HTML=true" grafana/grafana:8.0.3`

* add and save cloudwatch DS
* add alert using that DS
* choose Cloudwatch Logs instead of metrics
* minified Js error gets thrown

I also think [this issue from support](https://github.com/grafana/support-escalations/issues/462) might be related. Cloudwatch Logs in explore throws immediate react.js error

possibly involves error handling and the `fetchLogGroupOptions` function [here](https://github.com/grafana/grafana/blob/8fe58fc2e3b62b06af87b0c4b2252b32d7008f3f/public/app/plugins/datasource/cloudwatch/components/LogsQueryField.tsx#L109)

**Comment by EthanMcL** [comment]
Tried it this morning to test the console logs.  I got a new error (not sure if I'm just doing something slightly different), but none the less, here is the error:
`Failed to evaluate queries and expressions: failed to execute conditions: failed to query data: error parsing query "A", type assertion to string failed`

And the console log error:
![grafana-console-1](https://user-images.githubusercontent.com/18131775/123424483-43405680-d597-11eb-9049-807f93dbb138.png)
![grafana-console-2](https://user-images.githubusercontent.com/18131775/123424490-45a2b080-d597-11eb-923d-9370b90cef95.png)
![grafana-console-3](https://user-images.githubusercontent.com/18131775/123424498-48050a80-d597-11eb-9e53-dabb570fd27c.png)

**Comment by opub** [comment]
I have gotten both of the errors above also using v8.0.3. No amount of simplifying the query gets it to work.

There does appear to be a JS error when I attempt to run the query and before the 400 response.
![Screen Shot 2021-06-25 at 2 49 17 PM](https://user-images.githubusercontent.com/3865761/123472022-9c72af00-d5c4-11eb-8018-18f3b082918d.png)

**CloudWatch Alert Rule**
![Screen Shot 2021-06-25 at 2 47 05 PM](https://user-images.githubusercontent.com/3865761/123471837-61707b80-d5c4-11eb-95a1-8bb335bd6af9.png)

**Request Payload**
```{
  "data": [
    {
      "refId": "A",
      "queryType": "",
      "relativeTimeRange": { "from": 172800, "to": 0 },
      "datasourceUid": "Ndub1jg7z",
      "model": {
        "refId": "A",
        "hide": false,
        "namespace": "",
        "metricName": "",
        "expression": "filter @message like /deadlock/",
        "dimensions": {},
        "region": "default",
        "id": "",
        "alias": "",
        "statistics": ["Average"],
        "period": "",
        "queryType": "randomWalk",
        "matchExact": true,
        "queryMode": "Logs",
        "logGroupNames": ["/aws/rds/instance/qa-testing-database/error"],
        "statsGroups": []
      }
    },
    {
      "refId": "B",
      "queryType": "",
      "relativeTimeRange": { "from": 0, "to": 0 },
      "datasourceUid": "-100",
      "model": {
        "conditions": [
          {
            "evaluator": { "params": [0], "type": "gt" },
            "operator": { "type": "and" },
            "query": { "params": ["A"] },
            "reducer": { "params": [], "type": "count" },
            "type": "query"
          }
        ],
        "datasource": "__expr__",
        "hide": false,
        "intervalMs": 1000,
        "maxDataPoints": 43200,
        "refId": "B",
        "type": "classic_conditions"
      }
    }
  ]
}
```

**Comment by diogosilvaiupp** [comment]
Dear, I had the same problem creating alerts based on CloudWatch Logs. Grafana needs a value for this rule.

After query A, just add "Expression" and in the "Operation" field check Reduce and in the function you can use Last to set the last value.

Then you will have to indicate a new C field with the value of target, which can be "Classic Condition" or "Math" if you want some data transformation.

**Comment by brunooliveiramelo** [comment]
> Dear, I had the same problem creating alerts based on CloudWatch Logs. Grafana needs a value for this rule.
> 
> 
> 
> After query A, just add "Expression" and in the "Operation" field check Reduce and in the function you can use Last to set the last value.
> 
> 
> 
> Then you will have to indicate a new C field with the value of target, which can be "Classic Condition" or "Math" if you want some data transformation.

Hi, could you explain how did you get it? I tried but got this error `“Error
Failed to build evaluator for queries and expressions: only data source queries may be inputs to a classic condition, D is a Expression”`
