### ISSUE TITLE
PieChart: Make pie slice gradient more subtle to match other visualizations feel

### ISSUE THREAD

**Issue by FlyveHest** [grafana/grafana#36141]
**What happened**:
I updated from 7 series to 8.0.3, and changed an existing pie chart to the new piechart graph, and noticed that the colors, even though I selected the same across graphs, are different in the pie chart.

![example](https://user-images.githubusercontent.com/55623/123314120-7c8ead00-d52a-11eb-8b4c-76642f8546a7.png)

Both reds are the default red color swatch, but the pie chart is #d20f29 and the bar graph is #e8475a.

**What you expected to happen**:
Colors should be the same across graphs

**How to reproduce it (as minimally and precisely as possible)**:
Create a time series graph and a pie chart graph, set an element to use the default red color, the colors are not the same.

**Environment**:
- Grafana version: 8.0.3

**Comment by zuchka** [comment]
Hi @FlyveHest 

Thanks for reporting this. Yes, I see what you mean, but I think this is more about the gradient effect on the pie chart. I made[ two panels on our public sandbox running 8.0.3](https://play.grafana.org/d/f56Zwmk7z/pie-chart-color-issue?orgId=1) and I can recreate your issue. 

However, when I hover over a "pie slice" you can see the the CSS references #f2495c, which looks to be the standard red used by the bar chart and other. The red in the legend also seems to match.

![CleanShot 2021-06-24 at 12 37 40@2x](https://user-images.githubusercontent.com/37156449/123341329-7e844c00-d4e9-11eb-9bab-9f12bf536676.png)

So I'm wondering if this has to do with the gradient effect, radiating from the center of the pie...

**Comment by zuchka** [comment]
also @FlyveHest,

please add some more information about your Grafana instance, OS, browser, etc. Anything to help the squads. TY! 👍

**Comment by mckn** [comment]
I created a dashboard with two different types of panels. One pie and one bar gauge and they seems to get different variants of red.

**Comment by dprokop** [comment]
> I created a dashboard with two different types of panels. One pie and one bar gauge and they seems to get different variants of red.

Are you sure @mckn ? I've tested it agains time seres and pie chart next to each other and the base color is exactly the same- the difference in the PieChart is that it has fairly "bold" gradient, hence the issue.

**Comment by mckn** [comment]
> > I created a dashboard with two different types of panels. One pie and one bar gauge and they seems to get different variants of red.
> 
> Are you sure @mckn ? I've tested it agains time seres and pie chart next to each other and the base color is exactly the same- the difference in the PieChart is that it has fairly "bold" gradient, hence the issue.

You are correct but I guess that is the "issue" the author is highlighting. Sorry for the sparse comment :)
