### ISSUE TITLE
Time Series - using field overwrite to change the displayed name in legend disables series toggle

### ISSUE THREAD

**Issue by notrixatenza** [grafana/grafana#36147]
I'm not sure if this is a bug or intended.
Currently connected an elasticsearch datasource to a time series panel in grafana 8.0.2, while displaying 5 different metrics. Everything works as intended. On the dashboard you can go along and enable / disable the series (toggle) that you want to see.
As described here: https://grafana.com/docs/grafana/latest/panels/legend-options/

Then I used overrides to change the name of the fields in the legend by using "Fields with name" -> "Standard Option Display Name". That also works as expected but you loose the option to toggle the series on or off. If you toggle a series with a changed name, all series get untoggled / or toggled at the same time. All overwritten fields have a different name, so this shouldn't be the issue.

Here is a short gif showing the problem: https://media.giphy.com/media/LqRX08eCsXbbjV6kkY/giphy.gif

**Comment by alexandrseverinov** [comment]
Well, I can "+1" the problem. Also it isn't datasource specific — I was able to obtain described behaviour with ClickHouse and PostgreSQL as datasource.

**Comment by ivanahuckova** [comment]
@grafana/grafana-frontend-platform fyi

**Comment by torkelo** [comment]
fixed in v8.1 https://github.com/grafana/grafana/pull/35893
