### ISSUE TITLE
Reduce transform causes loss of precision in 64 bit series names

### ISSUE THREAD

**Issue by nathanpegram** [grafana/grafana#36149]
**What happened**: When using a reduce transform on a time series with series names made of decimal representation of unsigned 64bit numbers (e.g. the string '2882377905688543293'), the resulting field column will truncate the precision of the represented number(2882377905688543000). I am assuming something is needlessly parsing to a numeric representation that is insufficient for the uint64.

**What you expected to happen**: The series name string should be duplicated verbatim in the reduced output.

**How to reproduce it (as minimally and precisely as possible)**:
 - Create an influx query on a measurement with one of the tags holding 64bit unsigned integers. Group by time and tag.
 - Alias the series name by tag name "$tag_My64BitTag"
 - Add a reduce transformation that calculates stats on each series.
 - The series name will be transformed in the reduced output. e.g. '2882377905688543293' becomes 2882377905688543000
 - Adding some non numeric characters to the series alias, "$tag_My64BitTag foo" cures the loss of precision, but isn't acceptable for my use case. Presumably that is causing the attempt to parse to fail.

**Environment**:
- Grafana version: 7.4.3

**Comment by axelavargas** [comment]
@nathanpegram thank you for reporting this issue 🙌🏾. 

Information for the assignees: It might be good to take a look at a similar issue that was resolved before in the reduce transformation: [Reduce Transform seems to skip decimal strings]( https://github.com/grafana/grafana/issues/31580 )

**Comment by kaydelaney** [comment]
@nathanpegram Could you give a bit more info about what visualization you're using after reducing the output?

**Comment by zuchka** [comment]
@nathanpegram @kaydelaney perhaps I'm off here, but I've seen similar things when the table panel tries to handle very large numbers.
`Number.isSafeInteger(2882377905688543293) = false` in JS, so I'm guessing this is why the integers are only preserved when you force the series name to be recognized as a string by adding `"2882377905688543293 foo"`. When treated as numbers, they get truncated...

so perhaps this technically `works-as-intended`?

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isSafeInteger
- https://stackoverflow.com/questions/9643626/does-javascript-support-64-bit-integers

**Comment by joshhunt** [comment]
The error here happens not with the transform, but in the way values are rendered (in the table).

I don't think it's intuitive that a field of type string is truncated, especially given some data sources may intentionally return Very Large Numbers as strings to prevent javascript from truncating them.

A workaround is to explicitly set the Unit to String, which will prevent Grafana from trying to parse it as a number for display.

![1017_2022-03-01-15-06_chrome](https://user-images.githubusercontent.com/46142/156193840-2df670d8-d8d9-4a0f-9d35-9c1758f34c29.png)

**Comment by iambingoNJU** [comment]
Same issue on v10.4.2. It seems kibana handles it well but grafana will truc big numbers. Only 15~16 digits in the prefix is correct. So what is the workaround to this issue?
