### ISSUE TITLE
Endpoint for managing plugin status

### ISSUE THREAD

**Issue by mmahacek** [grafana/grafana#36146]
**What would you like to be added**:
Either a `grafana-cli` command or a HTTP API endpoint for enabling/disabling plugins that have been installed.

**Why is this needed**:
Assists in the remote management and automation of server configuration. It is possible to add/remove via the CLI command, but if we wanted to just disable certain plugins without completly removing it, there isn't an option to automate that.

**Comment by zuchka** [comment]
Hi @mmahacek 

thanks for creating this feature request! Sounds like a v useful thing to add 👍
