### ISSUE TITLE
Logs panel is broken when reading from InfluxDB 2

### ISSUE THREAD

**Issue by pgmillon** [grafana/grafana#36157]
**What happened**:

When using the following query for a logs panel, only the message field is visible.
```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "tail")
```
[2021-06-25-09-53_influxdb_data-1.csv](https://github.com/grafana/grafana/files/6714502/2021-06-25-09-53_influxdb_data-1.csv)

The logs are collected with telegraf.tail plugin and shipped to an influxdb2 instance.
Adding the labels to fields transformation to show additional columns breaks the panel even more. It's like only the first column is shown.

![image](https://user-images.githubusercontent.com/715479/123281296-ddf25400-d509-11eb-842c-e1cda7271bee.png)

I also tried to update the flux query with a group. The table view is "fine" but the regular view only shows the _value field even with an "Organize fields" transformation.

```
from(bucket: v.defaultBucket)
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "tail")
  |> group(columns: ["message"])
```

![image](https://user-images.githubusercontent.com/715479/123285650-85bd5100-d50d-11eb-9eed-32cf5f7dcb69.png)
![image](https://user-images.githubusercontent.com/715479/123285700-91107c80-d50d-11eb-9b70-b5da7b4bab71.png)

**What you expected to happen**:

The message field + labels as field should be visible in the panel

**How to reproduce it (as minimally and precisely as possible)**:
Use a query that has a string for the _value. Include other tags in the query. Use the table panel for this query. Apply the "Labels to fields" transformation

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-26886pre (aae3b76d84) - Docker grafana/grafana:main
- Data source type & version: influxdb 2.0.7
- OS Grafana is installed on: Alpine 3.13.5 (Docker)
- User OS & Browser: Manjaro 21.0.7 & Firefox 89.0.1
- Grafana plugins: None
- Others:

**Comment by gabor** [comment]
hi @pgmillon ... the logs panel only shows a single field, it cannot show multiple fields at the same time. you can choose which one is shown by for example using the `organize fields` transformation, and hiding the not-wanted fields, or just reorganizing them, it seems logs-panel picks the first string-field.

if you want to show multiple fields at the same time, i recommend the table-panel.

i tried the csv-data you uploaded (the first one), and using a table panel and a "labels to fields" transformation i was able to show all the fields.

does this solve your problem?

**Comment by pgmillon** [comment]
Hi,
using a table-panel works fine indeed. 
But why only showing a single field in the logs-panel ? I mean, logs are not a single field : considering at least time, level, source, text if not a complete JSON object.

**Comment by gabor** [comment]
hi, i'm glad it worked with the table-panel.

regarding why logs-panel cannot show multiple columns.. i guess it's a different perspective on the data. you see, when you use the logs-panel, you will see only a single string. but, you can click open any line, and we show you all the related data to that log-line.
so i think for the multi-column use-case the table-panel serves better currently.

if you do think the multi-column layout is something that should be included in the logs-panel, i recommend that you create a feature-request github-issue where you focus on this, and describe why it would be useful to have. (no promises if and when it gets implemented, but at least it will be tracked and you might even get some additional responses or recommendation from other users)
