### ISSUE TITLE
Grafana 8 : Title background color for stat

### ISSUE THREAD

**Issue by jbarotin** [grafana/grafana#36156]
**Steps to reproduce**:
Since update to Grafana 8, for the widget "stat", the title background can only stay in white or transparent. 
**Actual Result**:
In a dashboard that contains a lot of this widget, we got the following display : 
![2021-06-25_09-24](https://user-images.githubusercontent.com/4245508/123386626-260b8800-d597-11eb-9d1f-5ce7020202db.png)
There is too much white in the dashboard it's less understandable for us.

**Expected Result**
In the setting of stat widget, in the title part, in order of a checkbox "Transparent background", we need a combo box with the option "white", "transparent" and "same as value". 

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: influxdb
- User OS & Browser: Linux Ubuntu Firefox & Chrome
- Others:

**Comment by yurividal** [comment]
You can leave the title blank, give an ALIAS to the query, and Select Text Mode "Value and Name"

![image](https://user-images.githubusercontent.com/8555749/123431796-95966d00-d5c1-11eb-894d-5be216d4c8e2.png)

![image](https://user-images.githubusercontent.com/8555749/123431859-a5ae4c80-d5c1-11eb-9674-2ea7f85dfc2a.png)

**Comment by jbarotin** [comment]
Thanks a lot, it works very well.
