### ISSUE TITLE
Alerting: Make alert list more compact like in previous version (g7)

### ISSUE THREAD

**Issue by jbarotin** [grafana/grafana#36152]
**Steps to reproduce**:
I'm using the alert list in Grafana in my main dashboard (displayed on a TV in the office) to check if there some alerts that are still up.

**Actual Result**:
This widget is able to display only one and a half alert :
![2021-06-25_08-23](https://user-images.githubusercontent.com/4245508/123380203-74b52400-d58f-11eb-9312-82159ade9449.png)

**Expected Result**
In the previous version, I can display 3 alerts (maybe 4), sorry I haven't got a screenshot.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: InfluxDB
- User OS & Browser: Linux Ubuntu Firefox & Chrome
- Others:

**Comment by zuchka** [comment]
Hi @jbarotin 

Thanks for making this issue. Curious: are you using the new opt-in unified alerting, or the legacy dashboard alerting system? Here is the alert-list behind showing the new system:

https://play.grafana.org/d/Mpq3Enknk/alert-list-panel-unified-alerting?orgId=1

Also, is resizing the panel not an option?

**Comment by jbarotin** [comment]
Hi @zuchka,

I wasn't aware of the redesign of the alerting system, I haven't enabled "ngalert" feature, so I'm using the legacy alerting system. If you told me that it is almost done, I can enable it next week (and fill an issue to share feedback, if I've got are any). 

From what I understand in the new version, I will get a metric with the number of alerts enabled, so this kind of indicator will be more compact than the alert list widget :) 

About the widget alert list, I can change my view and resize my dashboard, I want just that share with you the feedback about something I could do previously and found that it not possible with the new version.

**Comment by zuchka** [comment]
Hi @jbarotin 

Awesome--we really appreciate the feedback!

the next-gen alerting is not quite ready for production, which is why it is still behind a feature toggle. It is a big step forward, however, so we'd always be interested in feedback from power users and early adopters like yourself 👍 

`docker run -p 3000:3000 -e "GF_FEATURE_TOGGLES_ENABLE=ngalert" -e "GF_PLUGINS_PLUGIN_ADMIN_ENABLED=true" grafana/grafana:8.0.3

**Comment by jbarotin** [comment]
I prefer to test it directly on my "production" installation. Is it possible to step back to the old system, if it is not working properly ?

**Comment by ivanahuckova** [comment]
Yes! In that case, you just need to disable the ngalert feature toggle - https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/#disabling-grafana-8-alerting-after-migration

**Comment by konrad147** [comment]
We no longer develop legacy alerting

**Comment by konrad147** [comment]
We no longer develop legacy alerting
