### ISSUE TITLE
Please use a different favicon for offical website/docs/etc and Grafana instances

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3615]
Having a dozen tabs open, it's rather hard to see at a glance what is docs and what is running instances.

See https://github.com/prometheus/prometheus/issues/643 for some related thoughts.

**Comment by bergquist** [comment]
I feel your pain. 
Perhaps we can have a mono version for the docs? what do you think @bulletfactory @mattttt ?

**Comment by RichiH** [comment]
If we can agree on mono, inverted, or other simple conversions, I can send
a PR.

Richard

Sent by mobile; excuse my brevity.

**Comment by torkelo** [comment]
please submit PR or new feature request for the website project 
https://github.com/grafana/grafana.org

**Comment by RichiH** [comment]
Are you happy with https://github.com/grafana/grafana.org/pull/19 or do you need more changes?
