### ISSUE TITLE
Having trouble converting octets to interface percentage utalized

### ISSUE THREAD

**Issue by malichite** [grafana/grafana#3616]
I am currently dumping data into graphite with collectd.  I am gathering ifmib::ifInOctets and ifmib::ifOutOctets.  I can graph this data into graphana, however I want to display the data as port utilization percentage.  Not sure how to go about this.

**Comment by bergquist** [comment]
I have no idea what ifmib::ifInOctets or ifmib::ifOutOctets means. But I think your looking for the graphite function asPercent http://graphite.readthedocs.org/en/1.0/functions.html#graphite.render.functions.asPercent

**Comment by malichite** [comment]
Not sure why this was closed, this is not really an answer to the question.  IFMIB::ifInOctets is an snnmp mibs.  The value is just total number of octets but I need to be able to derive speed and do the matht o get percentage.
