### ISSUE TITLE
Search: Add ability for exact title matching in /api/search/ 

### ISSUE THREAD

**Issue by eddawley** [grafana/grafana#3617]
At work, we have a python dashboard sync tool that manages a bunch of Grafana dashboards based on Mako templates.  For efficiency, we pull any existing dashboards and diff their content against the new content and only submit writes if the content has changed/doesn't exist.  This is especially helpful in Grafana 2.x since the sqlstore code blindly updates dashboard and then deletes and reinserts tags.  The problem is that the API requires a slug for exact searching but the slug logic is based on the gosimple/slug which is not exactly portable to other languages.  It would be nice to add the following:
1.  new /api/search param to indicate exact title matching
2.  sql index on (org_id, title) to facilitate exact title matching

and/or
1.  new /api/slugify so we can use a regular GET /api/dashboards/db/:slug

I wouldn't mind submitting a PR for this if you tell me which one you prefer.

**Comment by bergquist** [comment]
Closing this since dashboards now have `uid`
