### ISSUE TITLE
[Docs] feedback: /panels/visualizations/state-timeline.md

### ISSUE THREAD

**Issue by dmarks8427** [grafana/grafana#36177]
[The state timeline paragraphs ](https://grafana.com/docs/grafana/latest/panels/visualizations/state-timeline/#value-mappings) references a [Value Mapping](https://grafana.com/docs/grafana/latest/panels/visualizations/state-timeline/%20%7b%7b%20refref%20%22../value-mappings.md%22%7d%7d%20) link that returns a 404 when I try to follow it. I have found an article on [Value Mapping](https://grafana.com/docs/grafana/latest/panels/value-mappings/) within the `Panels` section that I believe is where it should land.

**Comment by zuchka** [comment]
Thanks for noting this @dmarks8427!

I'll talk to the docs squad to get it fixed. I'd submit a quick patch but that link is using a Hugo relref, so it's a tad more involved. 👍

**Comment by zuchka** [comment]
Hi @achatterjee-grafana,

Look like a broken relref on line 44?
