### ISSUE TITLE
[Time Series Panel] Missing padding for labels 

### ISSUE THREAD

**Issue by Shadow505** [grafana/grafana#36178]
**Info**:

This issue is not present when using the old Grafana graph.

**Steps to reproduce**:
Create a Time-Series Panel and assign labels to the Axis

**Actual Result**:

No padding between the label and the actual data on the Y axis. See:

![grafanaPadding](https://user-images.githubusercontent.com/9123343/123453680-12d0da80-d5e0-11eb-9b43-1cf6703a6b2f.PNG)

**Expected Result**

Padding between the label and the actual data on the Y axis

The most optimal solution would be, if you could manually specify the desired padding (and maybe even the font size) in pixels for each label. But at there bare minimum there should be a default padding present. At the moment is it unreadable and looks quite bad.

**Environment**:
- Grafana version: Grafana v8.0.3 (cae5c5e46b) 
- User OS & Browser: Windows 10, Chrome & Firefox

Thanks!

**Comment by leeoniya** [comment]
good catch.

i missed adjusting this when making the tick label size assesment more exact in https://github.com/grafana/grafana/pull/35842

the previous strategy likely added the extra space to the tick labels for this purpose, but it should be part of `axis.labelSize`
