### ISSUE TITLE
[feature request] Allow viewer to access add dashboard page if viewer can edit enabled

### ISSUE THREAD

**Issue by TommyCpp** [grafana/grafana#36186]
**What would you like to be added**:
If viewer can edit is enabled, we'd like to allow users to access the add dashboard pages. 

Currently user can access the page with url but there is no add dashboard button in the menu.

**Why is this needed**:

In organization we adopt a GitOps model where users store dashboard json in a git repo and manage those from there. When users need to change something they usually just edit online and then copy paste the changed dashboard json file to the git repo to make the change permanent. 

It would be helpful if they can do the same when adding dashboard. Please let me know if you have any questions around this.

**Comment by zuchka** [comment]
Hi @TommyCpp 

Thanks for submitting this feature request!
