### ISSUE TITLE
Can not create Alerts if Dashboard has variables.

### ISSUE THREAD

**Issue by NikolaBorisov** [grafana/grafana#36191]
**What happened**:

It looks like you can not define alerts properly for metrics that use the variables. For example I have graph panel with $interval variable that I have se to 1d. I try to define an alert over this metric. It looks like when the query is evaluated the variable $interval is not set to 1d. 

```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "3.694ms",
  "error": "request handler error: request failed, status: 400 Bad Request",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1624491137989,
        "queries": [
          {
            "refId": "A",
            "model": {
              "aggregator": "zimsum",
              "alias": "main feed posts",
              "downsampleAggregator": "zimsum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$interval",
              "metric": "XA.feed.post",
              "refId": "A"
            },
            "datasource": {
              "id": 3,
              "name": "OpenTSDB"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1624663937989
      }
    }
  ]
}
```

OpenTSDB showed this: 
```
23:32:17.992 WARN  [HttpQuery.logWarn] - [id: 0x7197ab30, /172.31.13.175:38820 => /172.31.36.39:4242] Bad Request on /api/query: Invalid duration (number): $interval
```

**What you expected to happen**:
I was expecting to just create the alert with the current value of the variable. Or have an option to specify which value of the variable the alert should execute with.

**How to reproduce it (as minimally and precisely as possible)**:
Make a dashboard with graph panel and OpenTSDB (might be true for other sources). 
Make sure your dashboard has a variable set to something and use this variable in the opentsdb downsample option.
You can not really make an alert over this metric.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Hi @NikolaBorisov 
Thanks for making this issue. 

One quick question: I see you are running 8.0.3. Are you using the legacy dashboard alert system, or are you using the new, opt-in Unified Alerting, which requires the `ngalert` feature toggle?

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/

**Comment by NikolaBorisov** [comment]
@zuchka Thanks for pointing me at the right direction. I didn't know I have to enable ngalert. I did it now. I ran into another issue. I'm using OpenTSDB as a source and the Create Alert rule -> 2. Create a query to be alerted on I get my datapoints in 1970. Opentsdb is doing timestamps in milliseconds and I think this alerts code does not understand this.

Should I file a different issue?

**Comment by zuchka** [comment]
glad you've made progress on this! If you're saying that the query in the alert panel returns different results than the query editor in a dashboard, or explore, then I'd definitely create a new issue. I'm guessing [based on this old pr](https://github.com/grafana/grafana/pull/4227) that opentsdb and grafana are handling ms in your dashboards?

**Comment by NikolaBorisov** [comment]
Ok, I'm closing this one since the issues is now different https://github.com/grafana/grafana/issues/36245
