### ISSUE TITLE
Separate stacks for positive and negative Y

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3619]
Currently, enabling both stacking and negative Y axis will subtract the negative values from the positive ones instead of having two distinct stacks: one up, one down.

Without looking at the code, this should be relatively easy to do by always doing positive additions for both positive and negative Y, but doing so in two different buckets. At the end, simply flip the axis of the negative one.

As I don't see any use in the current behaviour, I don't think an option to retain the old style would be needed.

The approach above would also solve https://github.com/grafana/grafana/issues/2747

**Comment by RichiH** [comment]
As a follow-up, http://dashboard.congress.ccc.de/ solves this with two graphs: One cummulated on its own and one overlay for IPv6. That only works for exactly two graphs, though. For an arbitrary number like "all interfaces on device", this does not work.

**Comment by torkelo** [comment]
This is already possible with series style override (style tab) you can set stack groups based on series name regex

**Comment by RichiH** [comment]
I didn't see that... Thanks!

**Comment by douglasg14b** [comment]
@torkelo  @RichiH 

Can you explain the process to achieve this with the series overrides?

**Comment by RichiH** [comment]
You just have to group one to positive and one to negative and enable stacking.

Grouping can be done by pattern matching and regex on the time series' description.
