### ISSUE TITLE
[cloudwatch] Nested template variables stopped working after upgrade to 8.x 

### ISSUE THREAD

**Issue by awsiv** [grafana/grafana#36197]
**What happened**:

I have cloudwatch dashboards that uses nested query variables. 
eg. 

```
        "datasource": "${datasource}",
        "definition": "resource_arns($region,ecs:service,{\"Name\":[\"test\"]})",
```
This worked fine in 7.x, but stopped working after upgrade to 8.x (currently at 8.0.3)

For 8.0.3, grafana always seems to use the datasource and region that was selected when saving the dashboard:

```
eg. 

{"results":{"metricFindQuery":{"frames":[{"schema":{"refId":"metricFindQuery","meta":{"custom":{"rowCount":1}},"fields":[{"name":"text","type":"string","typeInfo":{"frame":"string"}},{"name":"value","type":"string","typeInfo":{"frame":"string"}}]},"data":{"values":[["arn:aws:ecs:ap-southeast-1...
```

**What you expected to happen**:
A variable with `query`  type should  use the dynamically selected variable to fetch the variable value.

**How to reproduce it (as minimally and precisely as possible)**:

Create 2 dashboard variables, with the 2nd using the first one
```
        "datasource": "${datasource}",
        "definition": "resource_arns($region,ecs:service,{\"Name\":[\"test\"]})",

```

**Anything else we need to know?**:
I am only using Cloudwatch datasource so haven't tested this for other datasources

**Environment**:
- Grafana version: 8.0.3 (docker hub)
- Data source type & version: cloudwatch
- OS Grafana is installed on: docker ubuntu
- User OS & Browser: chromium
- Grafana plugins:
- Others: installed on fargate behind loadbalancer

**Comment by jveldboom** [comment]
We're seeing the same thing but the whole `resource_arns` function seems to be no longer returning any data. We've tried it with and without variables. We're on v8.0.3 (cae5c5e46b) in Grafana Cloud

For example, this basic query returns no results:
```
resource_arns(us-east-1,lambda:function, {"application":["my-app-name"], "environment":["production"]})
```

**Comment by rhowe** [comment]
I am seeing similar. I'm still trying to pin down exactly what's going on, but we have several Cloudwatch datasources configured, each configured with an assume role arn to allow viewing metrics from different accounts.
resource_arns() works for me, but uses the wrong datasource!
This means I end up retrieving ARNs from the wrong account which breaks a ton of dashboards.
The datasource it uses appears to jump around somewhat at random as well.

**Comment by awsiv** [comment]
my issue is the same as @rhowe

**Comment by rhowe** [comment]
I have cherry-picked 30dc4025c2eda715ce595f868cc553db0586418d onto the v8.0.2 tag and built a new `grafana-server` binary. It does seem to resolve this issue, thanks! Looking forward to v8.0.5
