### ISSUE TITLE
[Google Cloud Monitoring] Query builder trims service/metric list over 10000

### ISSUE THREAD

**Issue by jcortejoso** [grafana/grafana#36206]
**What happened**: When trying to build a query using the Google Cloud Monitoring Plugin, I can't  find or select some of the GCP Metric services to show the metrics:
![image](https://user-images.githubusercontent.com/5635989/123614243-70457100-d804-11eb-8c75-fdcd6b00e0ea.png)

Last service shown is `Kubernetes` and in this service the last metric I can select is `grpc_server_handling_seconds`:
![image](https://user-images.githubusercontent.com/5635989/123614410-98cd6b00-d804-11eb-8fa9-3dc3f10e0dbb.png)

Looking to the requests seems to me that the request to `/api/datasources/proxy/9/cloudmonitoring/v3/projects/{project}/metricDescriptors` is being trimmed. Checking how many metrics are returned by this endpoints turns out that they are 10000:
```
# curl -s 'https://org.grafana.net/api/datasources/proxy/9/cloudmonitoring/v3/projects/{project}/metricDescriptors' -H <HEADERS> --compressed | jq . | grep '"name": "projects/{project}/metricDescriptors' | wc -l
 10000
 ```

So I cannot use the query builder to build queries from the services that are trimmed out form the `metricDescriptors` endpoint.

**What you expected to happen**: The building allows me to select all the GCP services/metrics available in the project.

**How to reproduce it (as minimally and precisely as possible)**: Try to build a query from a GCP project with more than 10000 metric descriptors.

**Anything else we need to know?**: Using grafana cloud.

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b) (grafana cloud)
- Data source type & version: 1.0.0
- OS Grafana is installed on: Grafana cloud
- User OS & Browser: Tested with Linux/MacOS and Firefox/Chrome.
- Grafana plugins: Google Cloud Monitoring
- Others:

**Comment by sunker** [comment]
Thanks for reporting this @jcortejoso! 

@iwysiu seems like the list metric descriptors api returns a next page token. Do you think we'll be able to iterate over these pages in the resource handler for metric descriptors?

**Comment by iwysiu** [comment]
We might have to restructure a bit, but we should be able to.
