### ISSUE TITLE
Graph: Support log scaling for values smaller 1

### ISSUE THREAD

**Issue by norges** [grafana/grafana#3620]
If log scaling is activate,d in my case log(base10), the lowest intervals is between 0 and 1. I have a measurement with values in the range 10^-4 until 10^3, I would like to have over intervals like 10^-4, 10^-3 and so on.

**Comment by cederigo** [comment]
Hi, I'm using Grafana for a thermal vacuum chamber where this is a requirement too.
Using the "master" branch I could achieve it :-) thanks to:
 - #7781 (Added scientific notation as a unit)
 - Improvements made in graph ticks when using a log scale

Just a matter of time till version "4.3.0" will be released.

Cheers, Cédric

<img width="1416" alt="screen shot 2017-03-28 at 09 16 20" src="https://cloud.githubusercontent.com/assets/415316/24393282/d28e4f5c-1397-11e7-8ee5-a72f191f8ac8.png">

**Comment by daniellee** [comment]
Thanks @cederigo had missed this. This issue is closed by #5278.
