### ISSUE TITLE
It's not possible to add variable datasources queries to mixed panels in Grafana 8.x

### ISSUE THREAD

**Issue by jbermejo-veridas** [grafana/grafana#36204]
**What happened**: Since we updated to Grafana 8.0.x we are not able to add more variable queries to our mixed panels. Previously we had the option of adding datasources like ${cloudwatch}, but now we are restricted to add directly the datasource. I attach 2 images to see the differences 

Previously we had the option to add these variables datasources to our panels
![image (2)](https://user-images.githubusercontent.com/86592832/123605075-c235c900-d7fb-11eb-9211-e6439a906b3a.png)

Since the upgrade to grafana 8.0.x these options have dissapeared
![Nuevo proyecto](https://user-images.githubusercontent.com/86592832/123605087-c530b980-d7fb-11eb-8b75-bbaf6b3bf1b9.png)
 
**What you expected to happen**: To continue being able to select the variable datasource in each panel

**How to reproduce it (as minimally and precisely as possible)**: Create a variable datasource, create a mixed panel and try to add that variable datasource in a query

**Anything else we need to know?**: This works correctly in grafana 7.5.7, but not in grafana 8.0.x

**Environment**:
- Grafana version: 7.5.7 / 8.0.x
- Data source type & version: Cloudwatch + ElasticSearch
- OS Grafana is installed on: docker ubuntu 
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by jbermejo-veridas** [comment]
Any news on this bug?

**Comment by m1cah** [comment]
I noticed this too. Also, I tried edited the json query in the query inspector to use variables and got a 500 Internal Server Error "Metric request error". In my case, I am using mixed data source but with multiple Cloudwatch datasources.

**Comment by bjhartin** [comment]
This is also a problem for us

**Comment by Doron-Bargo** [comment]
Same here

**Comment by bijwaard** [comment]
This also occurs with mixed Datasources, e.g. I use datasource variables SelectedCT and SelectedVT. 
![image](https://user-images.githubusercontent.com/6523124/154914319-109c9e2f-b96b-4ba6-8606-733bf1eae7e9.png)

- When re-using an older dashboard both variables work fine, 
- When trying to use a second datasource variable in a query it is not part of the selection. 
- You can start with a single datasource selection e.g. Datasource $SelectedCT, but when you then set the datasource to mixed, the other variable $SelectedVT is not available for selection.
- when you add a new query, both $SelectedVT and $SelectedCT are not available as Datasource selection
- you can of course edit the Panel/Dashboard source and make the change yourself in the targets, this appears to work, e.g. change $SelectedCT to $SelectedVT:
```
  "targets": [
    {
      "alias": "$SelectedCT:$tag_line",
      "datasource": {
        "uid": "$SelectedCT"
      },
```
Kind regards,
Dennis

**Comment by bijwaard** [comment]
This still happens in grafana 9, with mixed as well as direct template datasource selection.
![image](https://github.com/grafana/grafana/assets/6523124/3a63b2c1-db6b-481d-aee9-71ae883aadf9)

Old dashboard has template datasource ${sensors} selected, which is multi-select and works perfectly with repeated panel.
![image](https://github.com/grafana/grafana/assets/6523124/5858c367-5648-4b4c-966d-31839878cfb1)
When I try to change I can only select template datasource ${reference}
![image](https://github.com/grafana/grafana/assets/6523124/1cd2f750-3bc1-4a09-9d4f-ef62688bd354)
When I try to change ${reference} back to ${sensors} it is no longer in the list and is no longer accepted by typed it in.

Kind regards,
Dennis

**Comment by natellium** [comment]
Hey there, I believe this is related to https://github.com/grafana/grafana/issues/16543 and a known limitation described in [this comment](https://github.com/grafana/grafana/issues/16543#issuecomment-1181633895). We're working on adding some warnings to make this limitations more clear https://github.com/grafana/grafana/issues/74849#issue-1894721386.

I was able to reproduce this issue in 8.x but from 9.1.0 onwards it seems to "work" (when there's only one value selected in the variable). @bijwaard do you have multiple values selected for either your variables? That'd explain why they're not visible in the dropdown.
