### ISSUE TITLE
Prometheus Link does not fill in current template variables

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#3622]
In the query editor for Prometheus there is a link to open graph in Prometheus which is quite helpful for debugging

![image](https://cloud.githubusercontent.com/assets/3651746/12052714/b23addb0-aedf-11e5-8d7e-cecddb67859c.png)

The issue though this link does not changes variable names ($host in this case) with their current values as selected for currently visible chart giving link going to the page like this:

![image](https://cloud.githubusercontent.com/assets/3651746/12052771/33add294-aee0-11e5-8f5c-15348593038b.png)

As you see $host has not been replaced with proper constant value

**Comment by mtanda** [comment]
Thanks for reporting the issue!
I fixed this issue in https://github.com/grafana/grafana/issues/3624.
