### ISSUE TITLE
Elasticsearch Count not scaled in Bar gauge (as expected)

### ISSUE THREAD

**Issue by wols** [grafana/grafana#36221]
**What happened**:

When using a term filter query with a bar gauge panel the grouped `Count` metric bars are not scaled - all values are `100%` (see screenshot A).

**What you expected to happen**:

Scaled bars (see screenshot B).

**How to reproduce it (as minimally and precisely as possible)**:

Select a Elasticsearch index, select metric `Count` and group by a `value.keyword`.

**Anything else we need to know?**:

If a `max value` (standard options) given, the scales are different (Screenshot B).
But this is not a workarounf for `values > max value`.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Elasticsearch 7.10
- OS Grafana is installed on: Oracle Linux 8
- User OS & Browser: Gentoo Linux & Firefox 89.0.1
- Grafana plugins:
  * grafana-clock-panel @ 1.1.3
  * grafana-worldmap-panel @ 0.3.3
  * jdbranham-diagram-panel @ 1.7.3
  * natel-plotly-panel @ 0.0.7

**Screenshots**

`A`

![Screenshot A](https://user-images.githubusercontent.com/764167/123638651-b3f9a400-d81f-11eb-9d50-2437c565c628.png)

`B`

![Screenshot B](https://user-images.githubusercontent.com/764167/123638755-cffd4580-d81f-11eb-946c-6b8e4711cefa.png)

**Comment by wols** [comment]
I found a way (or a hack?) for correct representation:

1. Add a `Transform`
2. Add `Reduce` and select Mode `Series to rows`
3. Use Calculation `Total`

Yes **`Total`** and _not_ `Count`!
`Count` does not show the correct number for the grouped terms.
The numbers `156` and `180` are created by adding as many doc_counters with a reading of `1`. 

4. Change under `Value options` from `Calculate` to `All values`. 
5. Under `Standard option` set the value `Min` to ``0 .

`C`

![grafana_3](https://user-images.githubusercontent.com/764167/124519283-20107500-dde9-11eb-9ab0-c573c10867ea.png)

`D`

![grafana_4](https://user-images.githubusercontent.com/764167/124519294-27378300-dde9-11eb-9d66-269b48d60b4e.png)

**Comment by torkelo** [comment]
The auto min and max are defined by the values returned, but since you are setting up the stat panel to show the number of values (Count reducer), then the auto min max will not be a good option and you will have to specify a good min max value yourself

**Comment by torkelo** [comment]
Yes a workaround is to use a transform to reduce and get the count of values as the transform happens before auto min / max is calculated.
