### ISSUE TITLE
Prometheus: Add custom query parameters when creating PromLink url

### ISSUE THREAD

**Issue by mgronst** [grafana/grafana#36239]
Running Grafana version v7.5.5 (b5190ee547)

In the Data Source settings, Im adding the following Custom query parameter: `g0.max_source_resolution=auto`
However this parameter is not included in the PromQL query that is performed towards Prometheus/Thanos.

I can verify this by creating a new graph, and in the edit mode under query selecting the link to Prometheus, the
custom query parameter is not shown in the actual PromQL query.

**Comment by ivanahuckova** [comment]
Hello @mgronst, custom query parameters are part of all prometheus queries. However, they are not used when creating url to Prometheus in PromLink button. I'll add the `feature-request` label and rephrase the title a little.

**Comment by Ian-Yy** [comment]
Hi @ivanahuckova, I've created a PR. Please review and let me know if there's anything wrong with it. Thanks

**Comment by ivanahuckova** [comment]
@Ian-Yy thank you! Looking at it now. :)
