### ISSUE TITLE
Search does not handle LIMIT properly or TAG filtering

### ISSUE THREAD

**Issue by eddawley** [grafana/grafana#3623]
There are several issues here that all stem from the fact that https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/dashboard.go#L123 always joins with dashboard_tag (cross product) even though it never includes a term clause in the SQL.  

Specifically:
1.  LIMIT is hardcoded to 1000 in the sqlstore code even though it can be specified by the user 
2. TAG search is done later on in https://github.com/grafana/grafana/blob/master/pkg/services/search/handlers.go#L67.  This means that a TAG-only API search causes the database to select every dashboard in the organization limit 1000 which may never have the tag you are looking for.  The fact that the join results in a cross product further lowers the probability of the target dashes being included.

To reproduce, create > 1000 dashboards all with tags foo and bar.  Perform a /api/search/?tags=foo and it'll return < 1000 results.  Adding &limit=SOME_LARGE_INT will not change the count.

To fix:
1.  Tag names should be pulled in separate queries only after all filtering and paging has been done.  These selects could be batched into dashboard_id ranges for efficiency.
2.  In filtering code,  only join on dashboard_tag if searching by tags.  It would look like  "INNER JOIN dashboard_tag ON dashboard.id = dashboard_tag.dashboard_id WHERE ... AND dashboard_tag.term IN (...)".  I assume you don't need to support inverse tag filters.  If you do, then the negated form would be "LEFT JOIN dashboard_tag on dashboard.id = dashboard_tag.dashboard_id AND dashboard_tag.term IN (...) WHERE ... AND dashboard_tag.id IS NULL"
3.  Add an index on (dashboard_tag.dashboard_id).  I was actually surprised there is not a UNIQUE KEY (dashboard_id, term) which would be better if the rest of the code handles that constraint.  The migration code looks like it is trying to add one so this might be a bug by itself.
4.  Change filtering code to use user supplied limit.

I should be able to add a PR for this in the next week or two if I can find the time.  Please let me know if I got something wrong.

**Comment by torkelo** [comment]
yea, looks like this was not implemented correctly. 

But the dashboard_tag.dashboard_id_term unique index is there for me and works, what data base are you using?

**Comment by josephmc5** [comment]
MySQL

**Comment by johnmca** [comment]
I previously opened issue #4824 that was closed, but wondering if this open issue is related to what I am seeing. I have over 1000 dashboards in one environment that has issues with tags. When searching based on tags the chooser shows the tag and proper number of dashboards associated, but when selecting the tag to filter out the dashboards, there are missing dashboards in the search results.

**Comment by iksaif** [comment]
I cross-referenced linked issues and PR. #5292 had a partial solution (it allowed the caller to override the limit) but it got reverted .

**Comment by qrtalaci** [comment]
+1

**Comment by InformatiQ** [comment]
stupid question. why not just remove the limit of 1000 in services/sqlstore/dashboard.go:func SearchDashboards ?

**Comment by torkelo** [comment]
because api's with out limits are really really bad idea. I

**Comment by iksaif** [comment]
https://github.com/grafana/grafana/pull/8021 is an attempt at solving this.

**Comment by cdickmann** [comment]
Was hit by this when using sqlite. Really annoying as we create dashboards programmatically, each with 2 tags, and so we very quickly hit this limit, even though each tag will only be attached to 20-40 dashboards.

**Comment by bergquist** [comment]
@torkelo I think we should consider increasing the limit to... 5000? Just to push the problem down the road until development is merged to master. Its gonna be a while until people run 5.0 as primary Grafana.

**Comment by torkelo** [comment]
Maybe, this is fixed in develop branch thou6:)

**Comment by pkarmaka** [comment]
@torkelo  To confirm, is this already fixed and released?

**Comment by torkelo** [comment]
No, it's only in the develop branch

**Comment by iksaif** [comment]
> @torkelo I think we should consider increasing the limit to... 5000? Just to push the problem down the road until development is merged to master. Its gonna be a while until people run 5.0 as primary Grafana.

Yes please.

**Comment by torkelo** [comment]
I think this was fixed in v5
