### ISSUE TITLE
Grafana 8.0.3 - Override 

### ISSUE THREAD

**Issue by RobRGitHub** [grafana/grafana#36244]
**What happened**:

When using the "Organize Fields" Transform or the Overrides from the plugins to do the same function, all overrides are removed upon panel refresh. Whether there is a variable that drives the dashboards for specific systems, manual refresh of the panel or timed refresh, whatever overrides are added get removed.

**What you expected to happen**:

Expect that if I hide a field(s) from view or rename the column(s) header that the settings remain after apply the changes or saving the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

 This is GIF recording when the Transform "Organize Fields" is used.

![override](https://user-images.githubusercontent.com/65612454/123712696-d4862600-d840-11eb-8fc9-8f57762821a2.gif)

This is GIF recording when Overrides are used to do the same thing, after they are set and saved the settings revert on refresh but the overrides still are listed just no longer functioning.

![override2](https://user-images.githubusercontent.com/65612454/123713119-ba991300-d841-11eb-9ae6-2ff5e9705fd2.gif)

**Anything else we need to know?**:

This happened to some degree on version 7.5.x as well but I was only using tables at the time. In this case some column renames would remain but others would be reverted to no change. Currently on 8.0.3 it's happening on Tables, Time Series Graph and State Time Line plugins but I suspect affects any plugins where field name overrides can be used.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: InfluxDB v2
- OS Grafana is installed on: Linux CentOS 7
- User OS & Browser: WIndows 10 \ Edge Chromium, Google Chrome
- Grafana plugins: Tables, Time Series Graph, State Time Line
- Others:

**Comment by torkelo** [comment]
Looks lile your column names change for every refresh, you need stable column names

**Comment by RobRGitHub** [comment]
Sorry about that...I didn't even notice those time stamps in the columns were changing.
