### ISSUE TITLE
AzureMonitor: Resource picker misses part of directory

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#36243]
**What happened**:

"azure-devops" is missing in the resource picker directory
![Screenshot 2021-06-24 153116](https://user-images.githubusercontent.com/63325084/123711750-d42c6180-d825-11eb-8ba6-2581f8ac411d.png)
![Screenshot 2021-06-24 153057](https://user-images.githubusercontent.com/63325084/123711757-d5f62500-d825-11eb-88c4-e834ca4ed743.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
Thanks for the report! Do you have a sample resource URI I could use (at least in the UI, i know I probably won't be able to access it) to try and reproduce this? Happy for you to send it privately if need be.
