### ISSUE TITLE
Docs feedback: /alerting/old-alerting/add-notification-template.md

### ISSUE THREAD

**Issue by sregger** [grafana/grafana#36258]
It would be helpful to see the `Query` tab in this example. I'm trying to figure out what the query should look like as it defines the `handler` and `instance` labels.

**Comment by dsotirakis** [comment]
Looping in @grafana/docs-squad

**Comment by brendamuir** [comment]
notification templating has been updated- see here: https://grafana.com/docs/grafana-cloud/alerting-and-irm/alerting/manage-notifications/template-notifications/
