### ISSUE TITLE
Percentage thresholds do not apply

### ISSUE THREAD

**Issue by simPod** [grafana/grafana#36252]
**What happened**:

Set up percentage threshold but it is mostly ignored, only one color is somehow applied.

**What you expected to happen**:

To see all 4 colors in column the Override is applied to

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/327717/123757805-9f201d80-d8be-11eb-90c8-8b4a4917ea13.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: master

**Comment by torkelo** [comment]
@simPod you need to set min & max as well
