### ISSUE TITLE
Numerical view of traceId and spanId in Trace View

### ISSUE THREAD

**Issue by krikz** [grafana/grafana#36262]
**What happened**:
After update Grafana to 8.0 spans Ids and trace Id has presented as number which is inconvenient, because them writes in hex in logs.

![image](https://user-images.githubusercontent.com/5272634/123784434-1a45fb80-d8e0-11eb-8211-6946d4b53c2a.png)

**What you expected to happen**:
As in previous version spanId and TraceId in hex
**How to reproduce it (as minimally and precisely as possible)**:
Open trace in trace view
**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b)
- Data source type & version: tempo, loki
- OS Grafana is installed on: docker
- User OS & Browser: Windows 10 & chrome

**Comment by davkal** [comment]
@annanay25 did something change in the backend?

**Comment by annanay25** [comment]
Hmm, a few changes were made between Grafana 7.4.x and Grafana 7.5, but nothing that was specific to the way traceIDs/spansIDs were encoded - https://grafana.com/docs/tempo/latest/configuration/querying/

@krikz Could you please provide Grafana & Tempo versions from before & after the upgrade?

cc @zoltanbedi

**Comment by krikz** [comment]
> Hmm, a few changes were made between Grafana 7.4.x and Grafana 7.5, but nothing that was specific to the way traceIDs/spansIDs were encoded - https://grafana.com/docs/tempo/latest/configuration/querying/
> 
> @krikz Could you please provide Grafana & Tempo versions from before & after the upgrade?
> 
> cc @zoltanbedi

before
Grafana v7.5.7 (91de517)
tempo version lost
after
Grafana version: v8.0.3 (cae5c5e)
Tempo (version=007c31d5, branch=main, revision=007c31d5)
