### ISSUE TITLE
Cloudwatch: missing dimension in AWS/KinesisVideo namespace

### ISSUE THREAD

**Issue by carmit246** [grafana/grafana#36266]
**What happened**:
StreamName dimension for AWS/KinesisVideo namespace is missing.

**What you expected to happen**:
CloudWatch KinesisVideo metrics contains StreamName dimension.
The dimension is missing in Grafana after setting CloudWatch plugin.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: CloudWatch
- OS Grafana is installed on: Amazon Linux 2
- Grafana plugins: CloudWatch

**Comment by joshhunt** [comment]
Sounds like AWS/KinesisVideo namespaces and dimensions needs to be added to the supported list in [metric_find_query.go](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/metric_find_query.go#L45)
