### ISSUE TITLE
Loki: Log browser doesn't respect new time range when fetching labels

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#36278]
**What would you like to be added**:
Loki log browser fetches the labels with initial time range and doesn't update labels when time range changes. It is using selected time range to show values of the labels. 

https://user-images.githubusercontent.com/30407135/123834521-ca7b2a80-d907-11eb-97d0-93b210de4279.mov

This can be problematic/confusing in many ways as at other places, we usually pass the the selected time range to queries.

**Why is this needed**:
To always show all available labels.

**Comment by tharun208** [comment]
@ivanahuckova I like to work on this

**Comment by ivanahuckova** [comment]
Awesome! I'll assign issue to you. :)

**Comment by tharun208** [comment]
@ivanahuckova, I see this behaviour is common across other `data sources also. Basically, It is not triggering a call to the backend if the query field is empty.

**Comment by ivanahuckova** [comment]
Maybe, but before introducing the log/metrics browser, we updated the labels in dropdown when the time ranges changed. So we could reintroduced this behaviour again for browser.

**Comment by tharun208** [comment]
okay, is this change needs to be discussed?

**Comment by ivanahuckova** [comment]
> okay, is this change needs to be discussed?

Not really. This used to work for cascader button. The query editor receives the changes when time picker changes, so we can just check if the time range changed and fetch new labels. Maybe we could add a condition to fetch the labels only if time range change is bigger than 1 minute.

**Comment by ivanahuckova** [comment]
@tharun208 Have you been working ono this? Is there anything I can help with?
