### ISSUE TITLE
Grafana 2.6.0  - Colors on the graph and table mismatch

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#3627]
Hi,

I found out in some conditions  I see colors on the graph and table to be different

![image](https://cloud.githubusercontent.com/assets/3651746/12074995/44dd4cfa-b13f-11e5-8838-d976c8fe64eb.png)

Note also tooltip shows colors from the table - there is no "blue" which is seen on the graph

If I disable hiding graph with zeroes I can see the graph like this:

![image](https://cloud.githubusercontent.com/assets/3651746/12075001/867a3ef2-b13f-11e5-8a24-5fea4d7e324e.png)

Which is also not correct - the blue time series actually should be red as this is what table shows avg of about 13

**Comment by torkelo** [comment]
Lolks very strange, Could you create a gist with the raw promethods response? And the panel json?

**Comment by torkelo** [comment]
@PeterZaitsev have you been able to replicate this? Can I close?

**Comment by torkelo** [comment]
will close due to lack of more info
