### ISSUE TITLE
Improve visibility of widget warnings

### ISSUE THREAD

**Issue by bgardner-noggin** [grafana/grafana#36285]
See https://github.com/grafana/grafana/issues/36097 for screenshots

**What would you like to be added**:
Improve visibility of the widget warnings

**Why is this needed**:
In grafana 7, when a widget had a warning, then there was a bright red indicator in the top left corner of the widget. Now a very subtly grey warning icon is placed next to the title of the widget. So subtle that I raised the bug mentioned above as I thought it had been removed entirely.

I suggest that the placement of the icon next to the title makes it non obvious. If it was moved back to the top left of the widget it would be more visible. A colour change to red or orange would be an improvement but for the colour blind amongst us I think it really needs to be moved away from the title as well.

**Comment by torkelo** [comment]
We are planing to redesign the panel chrome soon and hope to make panel info & warning state icons more visible , https://github.com/grafana/grafana/issues/31080
