### ISSUE TITLE
Graph not displayed when Data is Available

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#3628]
Hi,

This is Grafana 2.6.0 + Prometheus

I have built the graph to show the avg io size:

irate(node_disk_sectors_read{alias="$host",device!~"dm-*"}[5m])*512/irate(node_disk_reads_completed{alias="$host",device!~"dm-*"}[5m]) 

As you can note it can and probably does contains some "nulls" when there was no IO completed and we have division by zero.   

What happens in Grafana thought I see no graph displayed at all, but as I move tooltip I see there is data actually available

![image](https://cloud.githubusercontent.com/assets/3651746/12075024/4145e128-b140-11e5-9019-3998c67395c7.png)

This does not look like it is issue with Prometheus as follow the link to see time series in Prometheus it shows graph correctly:

![image](https://cloud.githubusercontent.com/assets/3651746/12075030/6ecc66d0-b140-11e5-8fdd-2de9182a3e32.png)

**Comment by torkelo** [comment]
Is stack enabled?

**Comment by PeterZaitsev** [comment]
Yes,  Stack was enable which it was not.  Disabling stack makes graph show correctly

Thanks!

**Comment by zstyblik** [comment]
Hello,

I have query like `nginx_connections_current{exported_instance=~".*some\\.hostname.*", state=~".*(waiting|writing|reading).*"}` and seeing this issue as well? Yes, if I turn off stacked then data do show up. And yes, there are some null values, resp. data missing. However, I thought this would only affect `irate()` and not everything. Is this expected?

Thank you.

**Comment by torkelo** [comment]
set null point mode to "null as zero" if you want to use stacked and have null values

**Comment by zstyblik** [comment]
Thanks @torkelo.
