### ISSUE TITLE
Alerting: Overwrites another user's change without warning 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#36294]
If two users are editing the same alert rule Grafana will overwrite the other user's changes without warning. 

* Open same alert rule in two tabs
* Make a change in both, save 
* Make another change in the other tab (or to fully simulate a different browser and user). Save. 
* Grafana saves and overwrites the other users change without any warning 

For some entities in Grafana (dashboards, data sources et) we have a version column that provides optimistic concurrency to prevent or warn users before overwriting someone else's changes.

**Comment by papagian** [comment]
We keep versioning of Grafana 8 Alerts so it won't be hard to support this. This optimistic concurrency for the other entities occurs in the frontend or in the backend?

**Comment by torkelo** [comment]
@papagian backend, the SQL orm framework handles it (using a WHERE version= ) clause
