### ISSUE TITLE
Legend colors missing in Safari browser when using dark theme

### ISSUE THREAD

**Issue by daviskirk** [grafana/grafana#3629]
When using the dark theme and using the safari browser, the legend colors are not displayed next to the legend names.  
This is ONLY an issue with the dark theme/safari combination, the light theme displays the colors correctly.
I tried tried firefox, chrome and safari for comparison of dark and light themes. 

I'm running the stock Grafana version 2.6

**Comment by calebcall** [comment]
Interesting, I noticed this same thing the other day and thought my panel was just messed up and haven't had time to go back and look at it.

**Comment by calebcall** [comment]
I just went and looked and mine is now working.  Odd

**Comment by daviskirk** [comment]
Hmm... I've tried at least a few different safari versions (9.02, 9.0) on osx and ipad.  Could it have something to do with the grafana version?  The javascript console does not show any errors either

**Comment by torkelo** [comment]
anyone else who can replicate this on play.grafana.org? 

I know safari has some issues showing icons when using accessing websites with low ports numbers like 3000
