### ISSUE TITLE
Feature Request: Diff view on unsaved changes

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3630]
Sometimes, Grafana warns me about unsaved changes when I am not aware of what save-worthey changes I made. Instead of simply asking me to cancel, discard, or save, I would like to be offered a diff of the two versions. Two options come to mind:
- Graphical: show me what the two pages would look like
- Unified diff: show me the unified diff of the underlying JSON

Personally, I would prefer the latter.

**Comment by bergquist** [comment]
I kinda like it. If someone decide to make a PR based on this. Make sure the code is isolated.

**Comment by torkelo** [comment]
Added in v9
