### ISSUE TITLE
Apps: Plugin page return 404 status code 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#36304]
Even though we have a route for /a/:pluginId  (https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L82) 

this route returns 404 (That is the request for the main document page).  Tested the example app: 

http://localhost:3000/grafana/a/myorgid-simple-app

**Comment by tharun208** [comment]
Both the frontend and backend route matches the pattern like `/a/:pluginId` and not as `:id/a/:pluginId`. I like to raise a PR for this

**Comment by torkelo** [comment]
The pattern in the code looks correct

**Comment by tharun208** [comment]
@torkelo, It is not returning any 404 error if I append `/grafana` to the `root_url` in the config.

**Comment by marefr** [comment]
Maybe need to define one additional route without star/slash as such `r.Get("/a/:id", reqSignedIn, hs.Index) // App Root Page` ? You can see here for example we're doing just that:
https://github.com/grafana/grafana/blob/b255f3db3f84d897f33deedb063e6ea5fd86eada/pkg/api/api.go#L61-L62

**Comment by torkelo** [comment]
A that could be it

**Comment by tharun208** [comment]
@torkelo can I raise a pr for this?

**Comment by torkelo** [comment]
That be awesome
