### ISSUE TITLE
ValueMappings: Missing scrollbar in value mappings editor modal 

### ISSUE THREAD

**Issue by lux4rd0** [grafana/grafana#36317]
**What happened**:

If there are more than ~23 value mappings, the edit window doesn't scroll in order to edit them all. (Based on the verticle height of the window.) In prior to version 8, the value mappings didn't have a separate pop-up modal window to edit - so this wasn't an issue. Now if there are a lot of value mappings to edit from prior versions, not all of them can be edited. I can not also access the bottom of the page to save the edits. :)

**What you expected to happen**:

Allow the Value mappings pop-up window the ability to scroll to the full amount of mappings available.

**How to reproduce it (as minimally and precisely as possible)**:

Add lots of mappings. :) (I have some that are over 100+ mappings, etc. But you only need to add a couple of dozen based on your vertical screen size)

**Anything else we need to know?**:

Value mappings in the panel editor:

![value_mappings1](https://user-images.githubusercontent.com/30187533/124023514-a37a3280-d9b3-11eb-890b-112abca92cd3.png)

Value mappings in the pop-up window (without scroll bars):

![value_mappings2](https://user-images.githubusercontent.com/30187533/124023582-b1c84e80-d9b3-11eb-9926-6bde53632295.png)

**Environment**:
- Grafana version: Grafana v8.0.3 Enterprise (cae5c5e46b)
- Data source type & version: Any
- OS Grafana is installed on: Docker container
- User OS & Browser: MacOS / Chrome Version 91.0.4472.114 (Official Build) (x86_64) 
- Grafana plugins:
- Others:

**Comment by tskarhed** [comment]
Related to #32833
