### ISSUE TITLE
Can grafana do not display deleted kubernetes pods(Kubernetes+Prometheus+Grafana)

### ISSUE THREAD

**Issue by opskumu** [grafana/grafana#3631]
The kubenetes pod is short-lived, if frequent create and delete pod, the grafana dashboard will be have many deleted no datapoints pods.(use grafana Templating)

So, Can grafana do not display deleted kubernetes pods?

![deleted pods](https://raw.githubusercontent.com/opskumu/Day/master/tmp/deleted-pods.png)

Thank you.

**Comment by opskumu** [comment]
@jimmidyson

**Comment by torkelo** [comment]
you should probably make your queries more dynamic. Grafana shows the result of your queries, if they return no data the panels show no data :)
