### ISSUE TITLE
HistoryWrapper constructor history param not work

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#36322]
**What happened**:
In file [LocationService.ts](https://github.com/grafana/grafana/blob/b8010ba9f59732b18ff4570e95a9337cc71241bc/packages/grafana-runtime/src/services/LocationService.ts#L34),  HistoryWrapper constructor history param is useless.

```ts
    // If no history passed create an in memory one if being called from test
    this.history =
      history || process.env.NODE_ENV === 'test'
        ? H.createMemoryHistory({ initialEntries: ['/'] })
        : H.createBrowserHistory({ basename: config.appSubUrl ?? '/' });
```

**What you expected to happen**:
add a bracket

```ts
    this.history =
      history || (process.env.NODE_ENV === 'test'
        ? H.createMemoryHistory({ initialEntries: ['/'] })
        : H.createBrowserHistory({ basename: config.appSubUrl ?? '/' }));
```

**Comment by torkelo** [comment]
@MeetzhDing can you open a PR?

**Comment by MeetzhDing** [comment]
@torkelo  https://github.com/grafana/grafana/pull/36367
