### ISSUE TITLE
apply time range not work

### ISSUE THREAD

**Issue by ThierryHenry1994** [grafana/grafana#36323]
**What happened**:
I want to count all the bugs and the number of bugs solved so far this year.I click "This year so far" and "Apply time range" ico.
Now the dashboard is as I expected. But  when I switched to the other Dashboard and switched back, the chart was distributed in seven days, and the previous configuration didn't work at all.I have clicked "save","apply" and "save dashboard" icon.
![image](https://user-images.githubusercontent.com/32047768/124072698-afc5c480-da73-11eb-88c7-63505046e627.png)
![image](https://user-images.githubusercontent.com/32047768/124072740-c23ffe00-da73-11eb-9e0d-a4c40738df2a.png)

**What you expected to happen**:
When I switched back to the dashboard, it was still in this year's order, not this week's
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:grafana 7.5.7
- Data source type & version:mysql
- OS Grafana is installed on:windows
- User OS & Browser:firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you describe what your doing in more detail? 

* Are you changing time range while in panel edit? 
* Is it when coming back from panel edit that the time range is not preserved 
* What do you mean by "But when I switched to the other Dashboard and switched back"

**Comment by ThierryHenry1994** [comment]
> Can you describe what your doing in more detail?
> 
> * Are you changing time range while in panel edit?
> * Is it when coming back from panel edit that the time range is not preserved
> * What do you mean by "But when I switched to the other Dashboard and switched back"

sry. My description is not clear enough. 
My operation is :
change the time range of this dashboard(A) to "this year so far" --> click "Save dashboard" icon --> Switch to another dashboard(B) --> Switch to dashboard(A) --> time range is "Last 7 day" not "this year so far"

**Comment by torkelo** [comment]
When yiou save the dashboard be sure to save the new time range as the new default time range 

![Screenshot from 2021-07-01 14-50-50](https://user-images.githubusercontent.com/10999/124127262-ccfe9100-da7b-11eb-87ff-ee80b02dd079.png)
