### ISSUE TITLE
Remove login form validations

### ISSUE THREAD

**Issue by fds13** [grafana/grafana#3633]
Hello, good afternoon!

Question:
How can I remove the login form validations? 

Explanation:
- I need to make login without interactions with the login form.

Why:
- I'm making a poor integration with another system, where I send credentials in URL. In Grafana, I get these credentials and place in the fields (username and password), all with jQuery. But doing that way, I can't submit the login form, because it's not valid.
It is understandable?

Note: I'm a noob with Angular :/

Thank you very much!

**Comment by torkelo** [comment]
you can use any of grafana's supported auth mechanisms (oauth, auth proxy, basic auth etc).

What your doing is not supported :(
