### ISSUE TITLE
Add query options per QueryRow

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#36336]
Add options for 

- Interval
- Max data points

**Comment by kylebrandt** [comment]
Needed for https://github.com/grafana/grafana/issues/36336

**Comment by gillesdemey** [comment]
Discussed and deemed low priority – current workarounds are to update queries to use a larger aggregation window than the scraping interval.

**Comment by soniaAguilarPeiron** [comment]
Min interval is already editable in the alert rule form (min step). 

<img width="1341" alt="Screenshot 2023-01-23 at 09 07 34" src="https://user-images.githubusercontent.com/33540275/213993722-bbba5b76-1a2b-4f3a-a47c-07136e06efff.png">

**Comment by gabor** [comment]
@soniaAguilarPeiron , just to clarify, that min-step setting is specific to the Prometheus data source. other data sources do not always provide it.

**Comment by soniaAguilarPeiron** [comment]
thank you @gabor , and then the min interval defaults to 1s right?, do you think we should let users to edit this min interval?

**Comment by gabor** [comment]
(sorry, i don't remember what it defaults to)

honestly i don't know what's the best approach here. my personal opinion is that we should have min-interval there too. perhaps a shared widget that could be used in every part of grafana for min-interval/max-data-points?

i remember a similar discussion for the `explore` section, about adding them there (currently they are only in dashboards),
but i don't remember the end-result of that discussion. pinging @grafana/explore-squad 😄 , what's the current situation/plans with adding the dashboard-query-options to explore-mode?
