### ISSUE TITLE
Unified Alerting: Thanos rule states are shown, but no alert is send

### ISSUE THREAD

**Issue by farodin91** [grafana/grafana#36330]
I really like to new UI of alerting system.

**What happened**:

I set up Thanos as Prometheus datasource. Now, i can see the state of rules collected by the Thanos RuleApi. Alerts are not send through the grafana alertmanger.

**What you expected to happen**:

* Alerts send

**How to reproduce it (as minimally and precisely as possible)**:

* Setup Prometheus and connect it to the Thanos query with both APIs store and rule.
* Connect Thanos to Grafana
* Now a PrometheusRule should trigger inside of Prometheus
* You can see the alert state

**Anything else we need to know?**:

UI based creation of rules is only possible inside of Grafana by Loki and Cortex. 
I think it would be okay if just alerting works and rules have to be created outside.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus & Thanos 0.21.1
- OS Grafana is installed on: docker image
- User OS & Browser: firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
The build-in alert manager only works for Grafana managed alert rules. But you can enable alpha plugins and try out the alert manager data source, it allows you to use the UI in Grafana to manage an external alert manager (that Thanos can use)

**Comment by torkelo** [comment]
https://grafana.com/docs/grafana/latest/datasources/alertmanager/

**Comment by farodin91** [comment]
I will checkout datasource Alertmanager. 

I think would be great to mark entries than are not managed by Grafana with a hint to show what implication is.

**Comment by torkelo** [comment]
The Grafana manged rules are grouped at the top 

![Screenshot from 2021-07-01 12-11-49](https://user-images.githubusercontent.com/10999/124107519-97e74400-da65-11eb-85e8-937d3c523a2d.png)
