### ISSUE TITLE
OAuth login return 500 instead of access denied when using `role_attribute_strict=true`

### ISSUE THREAD

**Issue by TheoBrigitte** [grafana/grafana#36339]
**What happened**:

I tried to log in via OAuth and I got greated with a Server Error page.

<img width="791" alt="image" src="https://user-images.githubusercontent.com/6536819/123804773-ca6e3100-d8ed-11eb-9852-f9cf628e9b83.png">

logs
```
t=2021-07-01T08:49:34+0000 lvl=info msg="state check" logger=oauth queryState=***** cookieState=*****
t=2021-07-01T08:49:34+0000 lvl=dbug msg="OAuthLogin Got token" logger=oauth token="&{AccessToken:***** TokenType:Bearer RefreshToken: Expiry:2021-07-01 09:19:33.856505878 +0000 UTC m=+1878.202401326 raw:map[access_token:***** expires_in:1799 id_token:***** token_type:bearer]}"
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Getting user info" logger=oauth.generic_oauth
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Extracting user info from OAuth token" logger=oauth.generic_oauth
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Received id_token" logger=oauth.generic_oauth raw_json="{\"iss\":\"https://dex.*****\",\"sub\":\"*****\",\"aud\":\"*****+\",\"exp\":1625131174,\"iat\":1625129374,\"at_hash\":\"*****\",\"c_hash\":\"*****\",\"email\":\"myEmail\",\"email_verified\":true,\"groups\":[\"someOtherGroup\"],\"name\":\"User name\",\"preferred_username\":\"username\"}" data="Name: User name, Displayname: , Login: , Username: , Email: myEmail, Upn: , Attributes: map[]"
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Getting user info from API" logger=oauth.generic_oauth
t=2021-07-01T08:49:34+0000 lvl=dbug msg="HTTP GET https://dex.*****/userinfo: 200 OK {\"iss\":\"https://dex.*****\",\"sub\":\"*****\",\"aud\":\"*****+\",\"exp\":1625131174,\"iat\":1625129374,\"at_hash\":\"*****\",\"email\":\"myEmail\",\"email_verified\":true,\"groups\":[\"someOtherGroup\"],\"name\":\"User name\",\"preferred_username\":\"username\"}"
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Received user info response from API" logger=oauth.generic_oauth raw_json="{\"iss\":\"https://dex.*****\",\"sub\":\"*****\",\"aud\":\"*****+\",\"exp\":1625131174,\"iat\":1625129374,\"at_hash\":\"*****\",\"email\":\"myEmail\",\"email_verified\":true,\"groups\":[\"someOtherGroup\"],\"name\":\"User name\",\"preferred_username\":\"username\"}" data="Name: User name, Displayname: , Login: , Username: , Email: myEmail, Upn: , Attributes: map[]"
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Processing external user info" logger=oauth.generic_oauth source=token data="Name: User name, Displayname: , Login: , Username: , Email: myEmail, Upn: , Attributes: map[]"
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Setting user info name from name field" logger=oauth.generic_oauth
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Set user info email from extracted email" logger=oauth.generic_oauth email=myEmail
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Processing external user info" logger=oauth.generic_oauth source=API data="Name: User name, Displayname: , Login: , Username: , Email: myEmail, Upn: , Attributes: map[]"
t=2021-07-01T08:49:34+0000 lvl=dbug msg="Defaulting to using email for user info login" logger=oauth.generic_oauth email=myEmail
t=2021-07-01T08:49:34+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="invalid role"
t=2021-07-01T08:49:34+0000 lvl=eror msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/login/generic_oauth status=500 remote_addr=185.102.95.187 time_ms=43 size=1751 referer=https://dex.g8s.ginger.eu-west-1.aws.gigantic.io/
```

Especially pointing at `t=2021-07-01T08:49:34+0000 lvl=eror msg="login.OAuthLogin(get info from generic_oauth)" logger=context userId=0 orgId=0 uname= error="invalid role"` which is expected. I expect the role to be invalid/empty and the user to be denied access.

**What you expected to happen**:

I would have expected to see an Access denied page.

According to the documentation when `role_attribute_strict = true` and `role_attribute_path` does not return a role, Grafana should denies user access.

> Role mapping
> 
> If  the `role_attribute_path` property does not return a role, then the user is assigned the `Viewer` role by default. You can disable the role assignment by setting `role_attribute_strict = true`. It denies user access if no role or an invalid role is returned.

https://grafana.com/docs/grafana/latest/auth/generic-oauth/#role-mapping

**How to reproduce it (as minimally and precisely as possible)**:

Running Grafana 8.0.3 with a generic oauth provider configured and following directives `role_attribute_strict=true` `role_attribute_path="false || ''"`, should be enough.

But here is the configuration I used:

```
GF_PATHS_CONFIG=/grafana-config/grafana.ini
GF_PATHS_PROVISIONING=/provisioning
GF_ALERTING_ENABLED="false"
GF_ANALYTICS_REPORTING_ENABLED="false"
GF_AUTH_GENERIC_OAUTH_ENABLED="true"
GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP="true"
GF_AUTH_GENERIC_OAUTH_TEAM_IDS=""
GF_AUTH_GENERIC_OAUTH_ALLOWED_ORGANIZATIONS=""
GF_AUTH_GENERIC_OAUTH_NAME=grafana-dex
GF_AUTH_GENERIC_OAUTH_CLIENT_ID=*****
GF_AUTH_GENERIC_OAUTH_SCOPES=openid profile email groups
GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://dex/auth
GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://dex/token
GF_AUTH_GENERIC_OAUTH_API_URL=https://dex/userinfo
GF_AUTH_OAUTH_AUTO_LOGIN="true"
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_PATH="contains(groups, 'AdminTest')  && 'Admin' || contains(groups, 'ViewerTest') && 'Viewer'"
GF_AUTH_GENERIC_OAUTH_ROLE_ATTRIBUTE_STRICT="true"
GF_AUTH_DISABLE_LOGIN_FORM="true"
GF_AUTH_BASIC_ENABLED="true"
GF_SECURITY_ADMIN_PASSWORD="*****"
GF_SECURITY_DISABLE_GRAVATAR="true"
GF_SERVER_PROTOCOL=http
GF_SERVER_ROOT_URL=https://*****
GF_SESSION_COOKIE_SECURE="true"
GF_USERS_ALLOW_SIGN_UP="false"
GF_USERS_ALLOW_ORG_CREATE="false"
GF_LOG_LEVEL=debug
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: `8.0.3`
- Data source type & version: n/a
- OS Grafana is installed on: docker: `grafana/grafana:8.0.3`
- User OS & Browser: `macOS 11.4` && `Firefox 89.0.2`
- Grafana plugins: n/a
- Others: n/a

**Comment by wbrowne** [comment]
Thanks for flagging this @TheoBrigitte and apologies for the delay on this. There's also a discussion about this [here](https://github.com/grafana/grafana/discussions/37281).

So it looks like we're not specifically handling that use case and are defaulting to serving a `HTTP 500`.

More details:

Check is made [here](https://github.com/grafana/grafana/blob/main/pkg/login/social/generic_oauth.go#L184-L186):
 
```golang
if s.roleAttributeStrict && !models.RoleType(userInfo.Role).IsValid() {
	return nil, errors.New("invalid role")
}
```

with the [caller](https://github.com/grafana/grafana/blob/main/pkg/api/login_oauth.go#L207-L221):

```golang
userInfo, err := connect.UserInfo(client, token)
if err != nil {
	var sErr *social.Error
	if errors.As(err, &sErr) {
		hs.handleOAuthLoginErrorWithRedirect(ctx, loginInfo, sErr)
	} else {
		hs.handleOAuthLoginError(ctx, loginInfo, LoginError{
			HttpStatus:    http.StatusInternalServerError,
			PublicMessage: fmt.Sprintf("login.OAuthLogin(get info from %s)", name),
			Err:           err,
		})
	}
	return nil
}
```

I think this could be improved for sure.

**Comment by wbrowne** [comment]
Have looped in @grafana/backend-platform to help this find the right home

**Comment by david-woelfle** [comment]
Same problem here.

And I disagree with @wbrowne, IMHO this IS a bug. The Grafana docs state [here](https://grafana.com/docs/grafana/latest/auth/generic-oauth/#role-mapping) that:
> If  the `role_attribute_path` property does not return a role, then the user is assigned the Viewer role by default. You can disable the role assignment by setting `role_attribute_strict = true`. It denies user access if no role or an invalid role is returned.

That is quite clear that if `role_attribute_strict = true` Grafana should deny access to any user without a valid role assigned to. Hence Grafana should return a 403 and display some access denied page instead of a 500 that makes users believe that there was a internal problem with the Grafana instance.

Beyond that, I would appreciate a fix and would like to thank you in advance for working on this :)
