### ISSUE TITLE
shift-enter shortcut in Explorer logs search doesn't work when 'zoomed' on a time range

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#36349]
**What happened**:
When using Explorer for logs search with Loki (or other sources) the keyboard shortcut shift-enter completes the query and tells grafana to run it. In 8.0.0 and 8.0.3 if you make a search using the default time picker ranges, this works fine. However if you are doing exploratory searching the key shortcut stops functioning. For example, initiate a very wide search like `{app="myapp"}` for a 1 hour range, with lots of results. Then you might decide that a particular window of time has the results you want to look at more closely - if you click and drag the histogram to a range it will 'zoom' to that start/end time range. At this point if you do _any_ modification to the query, for example adding `|= "error"` and use shift-enter keyboard shortcut, grafana does not process they key combination and does not execute the query.

**What you expected to happen**:
Shift-enter keyboard shortcut should work in all query views and time ranges of the Explorer, and it should trigger the query to run.

**How to reproduce it (as minimally and precisely as possible)**:
1. In explorer write a query for logs, something that returns results over several minutes probably
2. Use the 'shift-enter' keyboard shortcut, the query should execute
3. Use the histogram to select a small portion of the results - verify that the time picker shows a specific time range now
4. Edit the logql query; either to a different set of label selectors, or adding a filter expression of any kind that matches some of the log lines in view.
5. Use 'shift-enter' keyboard shortcut, the query will **not** execute 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Tested on 8.0.0 and 8.0.3
- Data source type & version: Loki 2.2.0
- OS Grafana is installed on: Docker/AWS Fargate
- User OS & Browser: MacOS Chrome 
- Grafana plugins:
- Others:

**Comment by jackw** [comment]
Can reproduce this. Looks like the second attempt to use `shift + enter` (after selecting a time range via histogram) to run the query causes the query string to update but no request is made. Looping in @grafana/observability-squad since this appears to be explore related.

**Comment by ivanahuckova** [comment]
I was able to reproduce this with both - Loki and Elastic, but only using **logs histogram**. When I ran metrics queries, `shift + enter` after selecting a time range trough time series panel wworked.
