### ISSUE TITLE
Tooltip in Time series vs. Graph (old)

### ISSUE THREAD

**Issue by schmimat** [grafana/grafana#36346]
Hello,

on Grafana v8.03 I try to create a timeshift diagramm with flux with is working perect, but the tooltip is different between the new Time series vs. Graph (old).

In the Graph (old) panel I can see the value of the “last” point even if the mouse is between the points, in the Time series the value only shows when the mouse is direct on an point.

I also report this to [community.grafana.com](https://community.grafana.com/t/tooltip-in-time-series-vs-graph-old/49798).
Don't know where is the right place for this.

Best Regards

 Matthias
![2021-07-01 12_10_02-Window](https://user-images.githubusercontent.com/14329731/124113829-2bbc0e80-da6c-11eb-94ee-71ff1e49bb95.png)

![2021-07-01 12_07_00-Window](https://user-images.githubusercontent.com/14329731/124113794-21017980-da6c-11eb-9b30-ea1b11904357.png)

**Comment by torkelo** [comment]
yes, this old behavior in the old graph many considered a bug, so we fixed it for time series panel Now it only shows data close to the time your hovering over

**Comment by schmimat** [comment]
Hi,

thank you for the quick response. 
I also see the issue / request from schollsi [Time Series: Only show selected series in tooltip #36290](https://github.com/grafana/grafana/issues/36290#issue-933443606)

But in my oppinion it is not a bug, it is a feature.
When you see all values in the tooltip in a timeshift diagramm you can compare it by the 
numbers, not only by the visiual impression.

To make the tooltip work, when you are hoovering the diagramm, it is also necessary to name each Querry via the `|> set(key: "_field", value: "BS (Brenner Starts)")` command in flux (or alias in SQL)

![2021-07-01 14_42_23-Window](https://user-images.githubusercontent.com/14329731/124127516-1818a400-da7c-11eb-9a0d-f47ef46aff2e.png)

Best regard
 Matthias

**Comment by torkelo** [comment]
We might add a proximity limit to know how far to look for values

**Comment by schmimat** [comment]
Thanks.

I also have found this 

[TimeSeries: make cursor points hover the nearest non-null/undefined datapoint #34552](https://github.com/grafana/grafana/pull/34552#issuecomment-858162775)

and the  flot-multi-hover.mp4 is showing what I think it's also a good feature.

Best regards Matthias

**Comment by leeoniya** [comment]
> and the flot-multi-hover.mp4 is showing what I think it's also a good feature.

that implementation is very obviously flawed because it hovers a green datapoint at ~12:00 when the cursor is over ~15:15, and the tooltip shows ~15:15 in the header making it look like those are all values at that time, which is completely wrong.

**Comment by schmimat** [comment]
Yes and no. 

It's ok to say that the data point is at a different time and thats "completely" wrong.

On the other side I'm adding values (starts of an light) over the day and compare it via time shift with other days (-1d -2d -1w)

So at ~15:22:02 I have 8 starts yesterday but also 14 starts today and 22 starts 2 days before.

![2021-07-01 16_36_43-Window](https://user-images.githubusercontent.com/14329731/124142846-e529dc80-da8a-11eb-9f86-cfc694ea446e.png)

**Comment by leeoniya** [comment]
sure, some _limited_ level of proximity is okay (which is what that PR does [1]), as opposed to the old graph behavior which has no hover distance restriction.

the $1M question is how much proximity is okay if we're commited to showing only a single shared time value in the header. and/or should it be made configurable? per panel? globally?

https://user-images.githubusercontent.com/43234/121441048-ab176000-c94e-11eb-913b-09501cef0e31.mp4

**Comment by schmimat** [comment]
The question of proximity (interpolation?) is defined by the users choice of the Graph style.
![2021-07-01 18_43_29-Window](https://user-images.githubusercontent.com/14329731/124160544-a6048700-da9c-11eb-9d51-cd313d8d60f1.png)

In my oppinion interpolation for the tooltip only make sence when the graph style is one of the green marked styles.
(step befor and step after)

For any other styles no interpolation is helpfull

mfG Matthias

**Comment by leeoniya** [comment]
> In my oppinion interpolation for the tooltip only make sence when the graph style is one of the green marked styles.

when you have many slightly mis-aligned series, you need _some_ level of hover by proximity, otherwise you will only be able to focus a single point on a single series that is directly under the pixel you are hovering, which is exactly the issue that PR solves. (look through the linked issues and discussions).

> Maybe it can help to "show" not only a single line at the mouse position but a bar represending e.g a ± 1m time slot
(wich now can be set per panel) to see the time slot in wich the values of the points are selected?

this was discussed here: https://github.com/grafana/grafana/issues/6946#issuecomment-859723394

**Comment by bredmich** [comment]
Why was this issue just closed without further discussion?
I´m currently trying to get my old Graph panels into the new time series.
Sometimes the hover doesn´t work at all and i need to hover around a point multiple times before Grafana finally accepts that i want to see this value.
Some kind of proximity is badly needed.
The tooltip is kind of useless when i need to point at the exact pixel of a chart to see it.

**Comment by leeoniya** [comment]
> Sometimes the hover doesn´t work at all and i need to hover around a point multiple times before Grafana finally accepts that i want to see this value.
> Some kind of proximity is badly needed.
The tooltip is kind of useless when i need to point at the exact pixel of a chart to see it.

the issue is closed because hover proximity was added in the PR linked above. please update to 8.1.2 and if the problem persists, open a new github issue with your dataset and a screen recording showing it. thanks!

**Comment by bredmich** [comment]
The issue was closed before the PR was mentioned and torkelo said that "We might add a proximity limit".
After the PR was mentioned you said it´s still flawed so i didn´t read through thr PR.
Anyway, i was on 8.1.1, upgraded to 8.1.2 and the tooltips are working again.
