### ISSUE TITLE
Pie chart skips topmost (random) values from MySQL Data Source

### ISSUE THREAD

**Issue by JCN-9000** [grafana/grafana#36359]
Just updated grafana to v8.0.4 to see how pie chart fixes worked and still something is off:
 
**What happened**:
topmost values are not accounted in pie or legend: random set is displayed.

**What you expected to happen**:
biggest value returned showed first in legend and pie

**How to reproduce it (as minimally and precisely as possible)**:
return some amount of values ( mine is over 400 ) from MySQL query, if not limited to same amount of panel ( 25 or whatever is defined ) random ( usually top ) values are omitted.

Example:`
SELECT
  UNIX_TIMESTAMP(curdate()) as time_sec,
  sum(size) as value,
  uid as metric
FROM ACCT_STAT where size > 0 group by uid order by value desc limit 50;
is displayed correctly if also Limit (Max number of rows to display) is set to 50; if left to the default of 25 pie is not filled correctly.
Even if query asks for sorted results, using Query Inspector I see data is not there in decreasing order, so maybe the plugin only gathers first 25 entries received, which do not contain topmost values as expected.

**Anything else we need to know?**:
same problem showed on V8.0.3 too

**Environment**:
Red Hat Enterprise Linux Server release 7.6 (Maipo)
mariadb-5.5.60-1.el7_5.x86_64
Pie chart by Grafana Labs - ( New one )

- Grafana version:
OpenSource v8.0.4

- Data source type & version:
MySQL default
 
- OS Grafana is installed on:
Red Hat Enterprise Linux Server release 7.6 (Maipo)
- User OS & Browser:
Debian 10, 
Google Chrome Version 91.0.4472.114 (Official Build) (64-bit)
Firefox 89.0.2 (64-bit)
- Grafana plugins:
grafana-piechart-panel @ 1.6.2  (unused)

- Others:

**Comment by torkelo** [comment]
Yes, the limit set in value options is not done after any sort, you would need to sort them in a query or transform first

**Comment by torkelo** [comment]
Can you set the limit higher or if not sort the results in the query? (last resort use sort by transform) 

we have some open related issues: https://github.com/grafana/grafana/issues/35960
and sort via legend

**Comment by JCN-9000** [comment]
Well I **am** sorting the data in the query, but it does not reach the panel in a sorted way, looking at the Query Inspector data reported. So maybe it's the MySQL Data Source that needs to follow the rules and sort them as directed ? 

I will try to sort via transform and see what happens

With the default value of 25 , if it is a little less than the returned number of rows it is hard to see if the returned data is correctly displayed or not, unless you already know the result  or double check with the underlying database. This because the last bit of data returned is discarded, but it may not be the less significant part of it.

I can put a higher limit, but at least this behavior should be better documented,
It took me a while to understand it was not my query to be faulty, but that it was partially rendered.
How bad a big limit will impact on the renderer ? Memory used, performance, other drawbacks ?

A little digression in favor of issue: #35960 , if you put a high value to row limit in order to catch all the returned data, then the panel tries to fit all the received values resulting in a mostly black big ending slice of the pie. So explicitly discarding values under a threshold will help a lot when results are more than a handful of values.
