### ISSUE TITLE
Visual Bug by Annotations in Grafana 8

### ISSUE THREAD

**Issue by rgrullon** [grafana/grafana#36351]
What happened?
If you enable an Axis on the right side of the Time Series panel (see attached screenshot) and set some Annotations in the dashboard settings, you will see an visual bug or small offset between the Annotation line and arrow.

What was expected to happen?
The Annotation line and arrow should be exactly above each other.

Steps to reproduce the problem:
1. Set an Annotation to a dashboard
2. Create a new Panel with Time Series and Random walk data
3. Set axis to left only

Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):
Grafana v8.0.2 (5c5d45e19f)

**Comment by dprokop** [comment]
@rgrullon can you provide a screenshot so that we know what is going on?

**Comment by rgrullon** [comment]
![Screen Shot 2021-06-30 at 10 57 14](https://user-images.githubusercontent.com/5454355/124131246-9ad63a80-da4d-11eb-839a-ca49505418e1.png)

**Comment by rgrullon** [comment]
![Screenshot 2021-06-16 163432](https://user-images.githubusercontent.com/5454355/124131432-cb1dd900-da4d-11eb-80cc-63ee0da11910.png)

**Comment by torkelo** [comment]
What OS and browser are you on?

**Comment by rgrullon** [comment]
Support comment - think we can close this as the customer doesnt seem to be able to reproduce. I'm thinking it might of been a race condition that hasnt happened again.

Customer comment - am working on Windows and tested this behaviour with Chrome (Version 91), Firefox (Version 78) and Edge.
Today with Grafana v8.0.3 (cae5c5e46b) I cannot recreate this behaviour - was this bug fixed with the minor release?
