### ISSUE TITLE
Grafana 8 ngalert does not add visual annotations to panels.

### ISSUE THREAD

**Issue by Selaron** [grafana/grafana#36369]
Grafana legacy alerting keept adding visual annotations to panels like seen in this example:

[https://grafana.com/static/img/docs/v4/slack_notification.png](https://grafana.com/static/img/docs/v4/slack_notification.png)

Grafana 8 ngalert does not seem to do so, even though the migrated alerts are still referencing the panels.

In my opinion this is a very useful feature that allows direct visual feedback on graph trend and alert occurrences so I'd hesitate to upgrade and migrate our live grafana server at this cost.

**Comment by davidmparrott** [comment]
@Selaron I am working on getting these annotations for Grafana 8 alerts back!

**Comment by Selaron** [comment]
@tuhnu9089  alerting annotations are back in 8.1.1 (or even 8.1.0?), but there are still issues regarding coloring (#37304) and annotations appearing on multiple panels (#37612).
I guess them to be fixed in 8.1.2 coming soon.

**Comment by tuhnu9089** [comment]
@Selaron, did you mean option "include image"? 
Because it's currently unavailable into 8.1.1 + ngalert
![image](https://user-images.githubusercontent.com/58990524/129859441-a4edd68a-2f64-45c8-b6b6-33722f14a741.png)

**Comment by Selaron** [comment]
> @Selaron, did you mean "include image" option?

@tuhnu9089  no this issue is about the red and green annotation lines displayed in graphs.
Speaking of which, I'm also missing the include image option but this is a very different issue, does it already have a number?

**Comment by tuhnu9089** [comment]
>  does it already have a number?

@Selaron, not yet
