### ISSUE TITLE
Possibility of tying panels vertically when auto resizing

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#36361]
**Why is this component needed**:
Hi, at the moment panels are kept in order from left to right, then from top to bottom. So they are accordingly adjusted depending on the page size.
Some times should be very useful to have the possibility to tie two or more panels vertically (I mean one underneath the other) so that they can be treated as one single panel during the resize action.
A common example is when you have a panel with a table and underneath it the same metric shown as graph. And this for for more metrics.
When you look at the dashboard on a computer it’s ok. For each metric you have above the table and below the graph. But when you look at it on a mobile (or when you resize the page) you will firstly find all the tables, and then all the graphs
This is the monitor view
![image](https://user-images.githubusercontent.com/51508670/124187959-e07f1b80-dabe-11eb-8a2e-a51d76f31438.png)
And thees on a small size screen
![image](https://user-images.githubusercontent.com/51508670/124188060-09071580-dabf-11eb-9847-45ea2b150451.png)
![image](https://user-images.githubusercontent.com/51508670/124188148-276d1100-dabf-11eb-8e7f-55f64dc6dddf.png)

**Comment by leeoniya** [comment]
probably quite difficult to do without https://github.com/grafana/grafana/issues/10916

**Comment by torkelo** [comment]
Yes, closing in favor of panel groups
