### ISSUE TITLE
Datasource API query - backendSrv fetch not catching errors for cancelled request (catchError)

### ISSUE THREAD

**Issue by DislayPS** [grafana/grafana#36364]
**What happened**:
Datasource API query - backendSrv fetch Observable is not catching cancelled request error

**What you expected to happen**:
catchError should work on the fetch Observable with a cancelled request

**How to reproduce it (as minimally and precisely as possible)**:
**Scenario 1: Default fetch with a .pipe on the observable and a catchError - 
Does not catch the error -> does not log "ERROR RETURN"
Does catch the response (map) -> logs "MAP RETURN"
Screenshot: https://ibb.co/L9qXwtF**

> query(queryData: DataQueryRequest<any>): Observable<DataQueryResponse> {
    const queryOptions: BackendSrvRequest = {
      url: `${this.url}/query`,
      method: 'POST',
      data: queryData,
      requestId: `sameRequestId`,
    };

    return this.backendSrv.fetch(queryOptions).pipe(
      map((r) => {
        console.log('MAP RETURN');
        return r as DataQueryResponse;
      }),
      catchError((err) => {
        console.log('ERROR RETURN');
        return throwError(err);
      })
    );
  }

**Scenario 2: Fetch with a subscribe (Adding an additional subscribe on the fetch observable)
Now number of queries is 4 /query instead of 2.
Does log all cancelled requests (3 times "ERROR RETURN")
Does log the completed response (1 time "MAP RETURN")
Screenshot: https://ibb.co/xzT4V3C**

> query(queryData: DataQueryRequest<any>): Observable<DataQueryResponse> {
    const queryOptions: BackendSrvRequest = {
      url: `${this.url}/query`,
      method: 'POST',
      data: queryData,
      requestId: `sameRequestId`,
    };

    const response$ = this.backendSrv.fetch(queryOptions).pipe(
      map((r) => {
        console.log('MAP RETURN');
        subscription.unsubscribe();
        return r as DataQueryResponse;
      }),
      catchError((err) => {
        console.log('ERROR RETURN');
        subscription.unsubscribe();
        return throwError(err);
      })
    );
    const subscription = response$.subscribe();
    return response$;
  }

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3

- Data source type & version: 
Datasource React plugin  with all latest packages:
"@grafana/data": "^8.0.4",
 "@grafana/runtime": "^8.0.4",
"@grafana/toolkit": "^8.0.4",
"@grafana/ui": "^8.0.4",

- OS Grafana is installed on: 
MacOS

- User OS & Browser:
MacOS & Chrome

- Grafana plugins: Custom

**Comment by torkelo** [comment]
cancellation will just complete the observable, it is not an observable error: 
https://github.com/ReactiveX/rxjs/blob/6fa819beb91ba99dadd6262d6c13f7ddfd9470c5/src/internal/observable/dom/fetch.ts#L124
