### ISSUE TITLE
Grafana 8.0.3 can load plugins that need to be installed manually.

### ISSUE THREAD

**Issue by kongchujun** [grafana/grafana#36368]
**What happened**:
Grafana 8.0.3 can not load plugins which need to be grafana-cli installed or downloaded.
**What you expected to happen**:
Grafana can load plugins which need to be grafana-cli installed or downloaded.
**How to reproduce it (as minimally and precisely as possible)**:
version: '3.5'
services:
  grafana2:
      image: grafana/grafana:8.0.3
      container_name: grafana2
      ports:
        - "3001:3000"
      environment: 
        GF_SERVER_ROOT_URL: "http://${HOST_IP:-192.168.33.11}"
        GF_SECURITY_ADMIN_PASSWORD: "secret" 
      volumes: 
        - "./grafana2:/var/lib/grafana:rw"     
 then use command to run this container:  docker-compose up -d grafana2
then get into this container with command:  docker-compose exec grafana2 bash
run this order to download the plugins:  grafana-cli plugins install grafana-worldmap-panel
Get out of container and, restart it:  docker-compose restart grafana2.
Open the url with you browser, then login in with username and password:  admin secret
Create a dashboard, then create a panel, select the panel type of grafana-worldmap-panel.
And you will see a error tip in the center of panel: Error loading: grafana-worldmap-panel

**Anything else we need to know?**:
The error wont happen in less than 8.0.0 version. It means for example in Grafana7.5.7 this kind of low version wont have this
error.

**Environment**:
- Grafana version: 8.0.3 
- Data source type & version: postgres 9.2.0 or any kind of it
- OS Grafana is installed on:  docker images  grafana/grafana:8.0.3
- User OS & Browser: Chrome
- Grafana plugins: any plugins that need to installed manaully.
![snipaste_20210702_140351](https://user-images.githubusercontent.com/21653870/124228178-60989600-db3e-11eb-8dc3-95a9f3a3c65d.jpg)

- Others:

**Comment by torkelo** [comment]
any errors in the server log or browser log? 

Did you try following the recommended way to install plugins in docker? https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-in-the-docker-container

**Comment by kongchujun** [comment]
> any errors in the server log or browser log?
> 
> Did you try following the recommended way to install plugins in docker? https://grafana.com/docs/grafana/latest/installation/docker/#install-plugins-in-the-docker-container

Here is the log in browser:
Error loading panel plugin: grafana-worldmap-panel Error: Fetch error: 404 Not Found
    at system.js:4
    at async actions.ts:41
    at async actions.ts:131

I have checked the url that you send me. It recommended me to install the plugin when build the image.
But in my project, we need to add the plugins after the images build. And it work in version less than 8.0.0.
Besides, thanks for relpy.

**Comment by kongchujun** [comment]
Here is the logs in the server:
 2021-07-02T06:57:45.278064146Z t=2021-07-02T06:57:45+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/public/plugins/grafana-worldmap-panel/module.js status=404 remote_addr=192.168.33.1 time_ms=8 size=1727 referer="http://192.168.33.10:3001/d/CG34ELznk/new-dashboard-copyxccc?orgId=1"

**Comment by kongchujun** [comment]
Hi, I think I find out the problem.
If I get rid of the
 volumes:  
  - "./grafana2:/var/lib/grafana:rw"
this config in the docker-compose.yml file.
It can run the plugins which install by "grafana-cli plugins install grafana-worldmap-panel"

**Comment by kongchujun** [comment]
After discussed with colleagues, when it is up, you need to change the role of plugins fold. chown 472:0 -R plugins.
Then move the plugins.zip into plugins folds and unzip it. Then restart the container. Then it works.
Besides, you can not realize it Vagrant.
