### ISSUE TITLE
Alert templating per dox does not work

### ISSUE THREAD

**Issue by PrestonTaylor** [grafana/grafana#36365]
**What happened**: 
Using documentation here https://grafana.com/docs/grafana/v7.5/alerting/add-notification-template/ I configured an alert
![image](https://user-images.githubusercontent.com/11053557/124198664-1f9d7480-da9f-11eb-8f14-f2db0135e187.png)
output alert text as seen in slack:
[Alerting] Failed ESAs alert
${instance} has problems
{instance="blahblahblah"}
1
**What you expected to happen**:
Alert output with variables replaced
output alert text:
[Alerting] Failed ESAs alert
blahblahblah has problems
{instance="blahblahblah"}
1

**How to reproduce it (as minimally and precisely as possible)**: See screenshot, any simple query and alert seems to produce same results

**Anything else we need to know?**:

**Environment**:
- Grafana version: v7.3.4
- Data source type & version: Prometheus Native plugin
- OS Grafana is installed on: Centos
- User OS & Browser: Chrome
- Grafana plugins: Prometheus
- Others:

**Comment by torkelo** [comment]
you are on a too old a version, the alert notification templating was added in 7.4
