### ISSUE TITLE
Can I get detail infomation from click event on the chart?

### ISSUE THREAD

**Issue by aspoman** [grafana/grafana#3637]
I'd like to show detail infomation about current point that people clicked.Is there any function like this?
Or give some advice about finishing this task .
Thanks very much

**Comment by torkelo** [comment]
what detailed information?

**Comment by aspoman** [comment]
The situation is I store the detail data into hbase,I want the grafana call the server when people click  chart point with current point's information.
For example, people click some point on chart -> code call server -> open another page -> show detail infomation about current piont people clicked.
I want to know how to modify the code and achieve this function or where can I modify 
Because of my poor English,I' not sure you can understand me,mayby some picture can be helpful

Appreciate your reply

**Comment by torkelo** [comment]
Sounds like a very special feature for your case, you can fork grafana and try to implement it.
