### ISSUE TITLE
Month over Month time shift issue

### ISSUE THREAD

**Issue by svishniakov** [grafana/grafana#36383]
Hello,

I am trying to build Month over Month report on one page.

The idea is to select one full month, and as well as selected month get the previous month data on the same page as well, for comparison reasons.

I built two TimeSeries panels:
 1. Panel from the right - reflects the data related to the selected period
 2. Panel from the left - built with timeshift - 1M

<img width="467" alt="Screenshot 2021-07-01 at 18 24 46" src="https://user-images.githubusercontent.com/642970/124268088-bcb0e980-db41-11eb-8bed-21e0d36ac587.png">

When I select time range for the full month of 31 days everything works perfecly and I see the whole previous month on the left panel. Please check March-February example below.

<img width="1242" alt="Screenshot 2021-07-01 at 18 22 06" src="https://user-images.githubusercontent.com/642970/124268212-e5d17a00-db41-11eb-8261-207a2905bfa3.png">

**What happened**:
But I am experiencing the issue when I select full month which is less then 31 days (30, 29 or 28). In this case panel from the left reflects only range which is equal to selected range number of days. For example if I select an April, only 30 days will be selected in March, instead of 31 days. Please check screenshot below.

<img width="1241" alt="Screenshot 2021-07-01 at 18 19 40" src="https://user-images.githubusercontent.com/642970/124268275-f97ce080-db41-11eb-840b-c05e3f2d56a5.png">

**What you expected to happen**: 
Complete previous month reflected on the graph.

**How to reproduce it (as minimally and precisely as possible)**:
Built to simple graphs': one of them using `Time shift: 1M`. Compare selection between graphs.

**Environment**:
- Grafana version: 8.0.1
- Data source type & version: PostgreSQL
- User OS & Browser: Mac OS & Chrome

Yours sincerely,
Sergejs

**Comment by svishniakov** [comment]
@natellium why it looks for you like feature request? Just curious :)

From the user perspective looks like a bug - when I choose 1M timeshift it must be shifting by one month, but not for the number of days of the selected month.

**Comment by natellium** [comment]
Hey @svishniakov  sorry, I forgot to drop a comment clarifying this :)

We currently don't support natural months in our filtering, it takes the amount of days instead. I totally understand this feels like a bug from a user standpoint, but it's actually something we need (and want:)) to add support to, hence the feature request.

**Comment by svishniakov** [comment]
Hey @natellium thanks a lot for clarification. Looking forward for implementation and ready to help with testing :)

Cheers,
Sergey

**Comment by svishniakov** [comment]
Hi @natellium can I affect prioritisation of developement in this case? Are the paid users requests has more priority?

**Comment by oscarkilhed** [comment]
How do we want this to work? Should 2021-03-01 line up with 2021-02-01 and then the time shift end up with no values for 2021-02-29 30 31? It's going to be ok for ranges that start at the first of a month and go for exactly one month, but it might be confusing for ranges spanning multiple months, with the series alternating between missing values at the end of months. I think we need to add this as a separate time shift and retain the old functionality with the 30 day time shift.

**Comment by svishniakov** [comment]
@oscarkilhed it will be confusing, I think. But, you can set timeshift to 30d, not 1M.
