### ISSUE TITLE
Docs feedback: /alerting/unified-alerting/_index.md

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#36387]
There are 3 phantom entries in the Grafana 8 alerting menu.

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/

Screenshot:
![Screenshot 2021-07-02 08-55-37](https://user-images.githubusercontent.com/3270755/124277696-57de9a80-db13-11eb-9a2d-6f8e89518036.png)

**Comment by achatterjee-grafana** [comment]
Fixed via another PR.
