### ISSUE TITLE
TimeSeries: Tooltip color not matching graph and legend ones

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#36385]
**What happened**:

<img width="1051" alt="Fullscreen_02_07_2021_13_52" src="https://user-images.githubusercontent.com/153052/124270955-22e73d80-db3d-11eb-92a6-eacc8021c347.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS Firefox 89.0.2

- Grafana plugins:
- Others:

**Comment by rmmh** [comment]
Simple repro on grafana v8.0.4 (81fef5b4b4)

Create any graph with multiple series:
![image](https://user-images.githubusercontent.com/211868/124301088-8f9e1000-db1c-11eb-91fb-0751adf4c63a.png)

Observe that the series have the expected color:
![image](https://user-images.githubusercontent.com/211868/124301205-b78d7380-db1c-11eb-9887-68a8b404e543.png)

Click "Refresh Dashboard" and observe that the legend colors no longer match the lines:
![image](https://user-images.githubusercontent.com/211868/124301310-e1469a80-db1c-11eb-8091-78863a495708.png)

**Comment by RichiH** [comment]
Also found in Grafana Cloud 8.0.4. In my case, it's triggered when I change the time range and goes back to normal when I reload: https://drive.google.com/file/d/1th_xTDDgEk_SLXPZfumrEIBNOhHTYSoN/view

**Comment by torkelo** [comment]
@RichiH @rmmh been trying to replicate but cannot replicate, tried both real queries, refreshing, changing time range, etc using the same prometheus queries you had @rmmh 

Here is a test dashboard with prometheus 
https://play.grafana.org/d/hMxEQgi7k/legend-and-tooltip-series-color-match?orgId=1  

What OS and browser are you using?

**Comment by benrubson** [comment]
Same issue here with time-series panels.
Grafana 8.0.4.
InfluxDB as source.
MacOS Safari / Firefox as browser.
@torkelo strangely enough I can't make your test dashboard to fail.

![image](https://user-images.githubusercontent.com/6764151/124633854-feb19680-de85-11eb-871e-8750d26d89a4.png)

**Comment by rmmh** [comment]
I can't repro this on 8.0.3. It appears to be a regression in 8.0.4. @sylr can you double check your Grafana version?

**Comment by sylr** [comment]
I confirm I'm affected on `Grafana v8.0.3 (cae5c5e46b)`.

To reproduct I've to change variables values back and forth, the time range while doing it is `now-3h` & `now-1m`.

**Comment by sylr** [comment]
https://user-images.githubusercontent.com/153052/124721430-6826b900-df09-11eb-9a47-ed714c5f77be.mov

**Comment by RichiH** [comment]
* Debian testing
* Chromium 90.0.4430.212-1
* Grafana Cloud Free
* Prometheus data source
* I can reproduce with https://play.grafana.org/d/hMxEQgi7k/legend-and-tooltip-series-color-match?orgId=1&from=now-30m&to=now as well. Same behavior like in https://github.com/grafana/grafana/issues/36385#issuecomment-874731071

**Comment by hhromic** [comment]
I can also confirm this on Grafana 8.0.4 :(

**Comment by benrubson** [comment]
Still in `8.0.5`.

**Comment by wrightsonm** [comment]
I see this problem with Grafana 8.0.4 and Influxdb datasource.
To me it looks like the tooltip colors are off by 1 index when compared to the main table.

![image](https://user-images.githubusercontent.com/6232774/126042328-6d9033ed-e2dd-4d81-8b26-482adb606652.png)

**Comment by wrightsonm** [comment]
the colors in the tooltip also change around depending on the active series that is being hovered over:
![image](https://user-images.githubusercontent.com/6232774/126042397-e682e0c0-de32-43fc-ac0d-bf99f5b90275.png)
and the hover over green line:
![image](https://user-images.githubusercontent.com/6232774/126042419-da0ecc7e-6221-40cb-9ad1-bf7585d6b6ca.png)

**Comment by jossera** [comment]
Hi All,
I have the same problem with version 8.0.6. But I have a workaround.

Edit the Panel and klick on each color wich is koresponding to the value an chose a color for it. It can be se same color. Than save the panel and it works.

Greeting

Jo

**Comment by MarcoPignati** [comment]
confim the issue in 8.0.6

**Comment by MrutyunjayD** [comment]
Could someone confirm whether the color mismatch between the chart and legend in Grafana 9.2.0 is a bug or if it is due to an error on my part?
<img width="1370" alt="Screenshot 2023-03-15 at 11 12 01 AM" src="https://user-images.githubusercontent.com/28100045/225217929-60a18b46-ceaf-4e10-b601-f5865efc1777.png">
