### ISSUE TITLE
Numerical sorting instead of alpabetical sorting in templates

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3638]
When I create a template which generates `{1..30}`, Grafana sorts alphabetically like so:

    1
    10
    11
    12
    13
    14
    15
    16
    17
    18
    19
    2
    20
    21
    22
    23
    24
    25
    26
    27
    28
    29
    3
    30
    4
    5
    6
    7
    8
    9

which sucks for obvious reasons. 

While allowing different sorting algorithms (natural, i.e. taking k, M, etc into account, comes to mind) would also be nice, I do feel the default should be numeric like so:

    1
    2
    3
    4
    5
    6
    7
    8
    9
    10
    11
    12
    13
    14
    15
    16
    17
    18
    19
    20
    21
    22
    23
    24
    25
    26
    27
    28
    29
    30

**Comment by mtanda** [comment]
Dupe of https://github.com/grafana/grafana/issues/2839

**Comment by RichiH** [comment]
Sorry, I did search, but missed that.

Thanks!
