### ISSUE TITLE
Feature Request: All-only templates

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3639]
Some templates I simply want to pass into my https://github.com/prometheus/prometheus queries without giving the user the option to modify them. Specifically, my templates for interface matching should never be of any value other than "All". Forcing that template to always-all would help my avoid user errors.

**Comment by torkelo** [comment]
then why do you need a template variable at all just a wildcard  in the query would do?

**Comment by RichiH** [comment]
Several reasons:

* to re-use the same queries across several Dashboards
* to make the queries shorter, simpler to read, and to apply changes across several queries at once and in an consistent manner
* to use regex on the results on label_values easily

@torkelo I realize that this is unlikely, but I would like to ask you to re-open this issue.

**Comment by torkelo** [comment]
could you describe more in detail how your All only queries enable this?

**Comment by RichiH** [comment]
In my current, specific example, I need to jump through a few hoops to get exactly the correct interface types of various routers and then do aggregated graphs over a few hundred or thousand interfaces.

I have one or two graphs per type of traffic, directions of traffic, etc.

In all of those, I use the same template to make the queries shorter and to make _certain_ that I don't have a subtly different query in one of the graphs skewing my results.

In this case, I don't want my users to change anything as these graphs are not meaningful without showing exactly what I want them to show.


(as an aside, allowing me to resize the query input field when using the prometheus source would also be appreciated as my queries regularly run over that length, even when using templates)

**Comment by torkelo** [comment]
why can you not use a custom template variable with a single fixed value in this case then?

**Comment by RichiH** [comment]
Mainly to split up retrieval of values and application of regex.

I can try to migrate over to custom templates and if I run into too many hassles.
