### ISSUE TITLE
Templating: Support time field values in unix epochs  

### ISSUE THREAD

**Issue by nenad** [grafana/grafana#36404]
**What happened**:

When creating a variable from a SQL source (I tested with MySQL and PostgreSQL datasources) with TIMESTAMP(TZ) column type, the variable is the timestamp as integer unlike before where it was an RFC3339 representation.

**What you expected to happen**:

The variable to be formatted in RFC3339 so that it's easy to use it in other queries.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have a PostgreSQL/MySQL datasource with a table which has a column of type 'TIMESTAMP' or 'TIMESTAMPTZ'
2. Create a variable that uses this column (i.e. `SELECT ts FROM data WHERE id=1 LIMIT 1`)
3. Observe that the displayed variable is a Unix timestamp instead of formatted one (i.e. 1625250397000 vs 2021-07-02T22:27:25Z)

Here are some pictures that show the issue (Observe the "Preview of values" section):

## Grafana 7

![Screenshot2021-06-29-14-22-25](https://user-images.githubusercontent.com/2515325/124315294-09adb380-db74-11eb-9d63-888f11a98cd9.png)

## Grafana 8

![Screenshot2021-06-29-14-18-09](https://user-images.githubusercontent.com/2515325/124315298-0a464a00-db74-11eb-9ce2-2c21bd9fcdc1.png)

**Anything else we need to know?**:

[I've created a PR that demonstrates a potential fix for the issue](https://github.com/grafana/grafana/pull/36405), but I'm not sure if the Grafana team wants to handle this from the backend, or the frontend side. I've noticed significant changes on how the data is provided from the backend to the frontend which made me doubt if this needs to be fixed on the backend as frontend now has information about the type of the variable:

<details>
<summary>Grafana 7 response structure example</summary>

```json
{

    "results":{
        "new_now":{
            "refId":"new_now",
            "meta":{
                "executedQueryString":"SELECT end_datetime FROM times limit 1;",
                "rowCount":1
            },
            "series":null,
            "tables":[
                {
                    "columns":[
                        {
                            "text":"end_datetime"
                        }
                    ],
                    "rows":[
                        [
                            "2021-07-02T18:35:07.288777Z"
                        ]
                    ]
                }
            ],
            "dataframes":null
        }
    }

}
```

</details>

<details>
<summary>Grafana 8 response structure example</summary>

```json
{
    "results":{
        "query0":{
            "frames":[
                {
                    "schema":{
                        "name":"results",
                        "meta":{
                            "executedQueryString":"select ts from data limit 1;"
                        },
                        "fields":[
                            {
                                "name":"ts",
                                "type":"time",
                                "typeInfo":{
                                    "frame":"time.Time",
                                    "nullable":true
                                }
                            }
                        ]
                    },
                    "data":{
                        "values":[
                            [
                                1625168710920
                            ]
                        ]
                    }
                }
            ]
        }
    }

}
```

</details>

Additionally, I believe these issues are relevant:
- Broken variables from SQL sources: https://github.com/grafana/grafana/issues/35391
- PR that brings the "frame" concept: https://github.com/grafana/grafana/pull/32257

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: PostgreSQL 13
- OS Grafana is installed on: Linux
- User OS & Browser: Arch Linux, Firefox 87
- Grafana plugins: x
- Others: x

**Comment by nenad** [comment]
I've made another observation. The query executed in a normal panel will be properly formatted, even though the data is returned in an Unix timestamp format:

![Screenshot2021-07-03-11-23-59](https://user-images.githubusercontent.com/2515325/124349797-5d121700-dbf1-11eb-95b8-1386cf43c212.png)

This makes me think that the formatting is done on the frontend, and the implementation for it is missing for dashboard variables.

**Comment by torkelo** [comment]
The problem here is going to be how should the value be interpolated? what date format should be used?

**Comment by nenad** [comment]
Grafana 7 returned the formatting in RFC3339 based on my tests (i.e. `2021-07-02T18:35:07.288777Z`). I'd suggest using that as a starting point.

**Comment by marefr** [comment]
@nenad I think I see what might be wrong/changed here between v7 and v8. Don't think your suggested PR is the correct solution to this, but I might be wrong. I present an alternative solution below.

On v7 we checked if there was a time-series or table query, ref:
https://github.com/grafana/grafana/blob/c5cf127aa6217ae8babdd6fb9315114e8badd488/pkg/tsdb/sqleng/sql_engine.go#L182-L197

On v8, I think the following code
https://github.com/grafana/grafana/blob/ca2223f7058284d9a70b0c753d05331f5b3acd19/pkg/tsdb/sqleng/sql_engine.go#L273-L278

Should be moved inside this if-statement to only apply for time-series queries:
https://github.com/grafana/grafana/blob/ca2223f7058284d9a70b0c753d05331f5b3acd19/pkg/tsdb/sqleng/sql_engine.go#L280

**Comment by nenad** [comment]
@marefr I gave a shot to your suggestion, but variable templating still renders unix epoch seconds unfortunately. Seeing how the tables are receiving unix epoch seconds but render it in RFC3339, I wonder if this is also how variables should behave.

**Comment by marefr** [comment]
@nenad weird. Think you can update your PR with those changes and I'll review/test it out?

**Comment by marefr** [comment]
Tested on v7.5.5:
- A template variable using query `SELECT NOW();` returns the column as text/string (`"2021-07-18T05:14:19.522794Z"`) from the Grafana backend and renders as `2021-07-18T05:14:19.522794Z` in the UI.
- A template variable using query `SELECT NOW() as time;` returns the column as float/epoch (`1626585468413.561`) from the Grafana backend and renders as `1626585468413.561` in the UI.

I tried my suggested solution and correctly as you said it doesn't work. Seems like any time field is converted to JSON as epoch ms and that is potentially happening here:
https://github.com/grafana/grafana-plugin-sdk-go/blob/843e160c3b78b11a1db78e3a477f3fc3ec20e9c9/data/frame_json.go#L768-L770

Based on this I think the proper solution is to handle this client side.

The following functions needs an update where checking if any frame field is a time field and convert it to a JavaScript date:
https://github.com/grafana/grafana/blob/37caebc9348cf0074f9531ccf86ac9992039639f/public/app/plugins/datasource/postgres/response_parser.ts#L5-L36
https://github.com/grafana/grafana/blob/37caebc9348cf0074f9531ccf86ac9992039639f/public/app/plugins/datasource/mysql/response_parser.ts#L5-L36
https://github.com/grafana/grafana/blob/37caebc9348cf0074f9531ccf86ac9992039639f/public/app/plugins/datasource/mssql/response_parser.ts#L5-L36

The suggested short-term workaround would be for you to convert your time column into a string using something like `SELECT to_char(<time column>, 'YYYY-MM-DD"T"HH24:MI:SS.US"Z"');`

**Comment by marefr** [comment]
@ryantxu do you have any input on above given you added the data frame JSON conversion to the SDK?

**Comment by marefr** [comment]
@ryantxu any input on above?

**Comment by lingfish** [comment]
I've just hit this issue too; an update would be appreciated.

**Comment by societymartingale** [comment]
Solution for me was to use @marefr 's suggestion above to do a to_char() conversion in the sql statements. I also had to change some sql to order by time. (This is to prepare for upgrading from Grafana 7 to 8.)

**Comment by jfagoagas** [comment]
Is there any update on the issue? @marefr 

Thanks!

**Comment by Neurobion** [comment]
Is there any update on the issue?

**Comment by codeincarnate** [comment]
Grabbing this from another channel, forgot to copy it over here:

From Grafana 8 on time fields will generally return as a timestamp without transformation. As it stands today it would be very disruptive to change this behavior as the front-end now currently expects timestamps to be sent from the back-end. To avoid this, the solution would be to convert the time field to a string. For MSSQL this would be done using the `format` function as follows `SELECT format(date_field, 'YYYY-MM-DD')` where `YYYY-MM-DD` would be the desired date formatting string.

Other database systems as mentioned here would have slightly different functions/syntax. For instance in Postgres it's `to_char` and in MySql it's `DATE_FORMAT`.
