### ISSUE TITLE
Filter template variable `instance_id` of MemoryStore for Redis doesn't work

### ISSUE THREAD

**Issue by itkq** [grafana/grafana#36409]
**What happened**:

When querying to MemoryStore for Redis metrics (Google Cloud Monitoring) with filter and template variable instance_id, slashes (`/`) are escaped to (`\\/`), resulting in an invalid query error.

**What you expected to happen**:

Templating instance_id should work.

**How to reproduce it (as minimally and precisely as possible)**:

1. Define a dashboard variable `instance_id` as below (project_id is not necessary to define here).
![image](https://user-images.githubusercontent.com/8341422/124344646-855c3e80-dc0e-11eb-9f48-55676633a579.png)
2. Create some panels using `instance_id` as a filter like below.
![image](https://user-images.githubusercontent.com/8341422/124344687-c05e7200-dc0e-11eb-823c-7579fcc4e22d.png)
3. You will get a query failed error.

I understand what's happening here; Template variables including slashes are escaped.  In this case, '.queries[0].metricQuery.filters' (jq path) in request body

- should be
```
 [
  "resource.label.instance_id",
  "=",
  "projects/PROJECT_ID/locations/LOCATION/instances/INSTANCE"
]
```
- but actually
```
[
  "resource.label.instance_id",
  "=",
  "projects\\/PROJECT_ID\\/locations\\/LOCATION\\/instances\\/INSTANCE"
]
```

**Anything else we need to know?**:

When choosing the instance ID that Grafana suggests (instead of template variable), it does work. 

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b)
- Data source type & version: Google Cloud Monitoring
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome 93.0.4548.0
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
To support variables with multiple values the interpolation engine will assume regex filter matching so will escape the value to regex. You can override this using `${instance_id:raw}`  or change the filter matcher to use regex operator  (in the your data query)

**Comment by itkq** [comment]
@torkelo Sorry for taking up your time. Thank you!
