### ISSUE TITLE
Cell display mode 'Color Text' won't work if you set a Data link

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#36416]
Can be reproduced in https://play.grafana.org/d/OhR1ID6Mk/3-table?orgId=1&viewPanel=4

If you insert a data link, the column Last loses the value colors.

<img width="709" alt="grafik" src="https://user-images.githubusercontent.com/79257887/124381924-32918e00-dcc5-11eb-80f1-1c05d1f5e3ef.png">

**Comment by torkelo** [comment]
I see the link color in the columns with background is also wrong (changes to gray when you add the datalink, it should remain white )

**Comment by tharun208** [comment]
@torkelo, I like to work on this

**Comment by torkelo** [comment]
@tharun208 great, think this function https://github.com/grafana/grafana/blob/f62bc59688c5bb73c60b2464797c946b68fb8750/packages/grafana-ui/src/components/Table/styles.ts#L17 needs to override any anchor (a tag) color under it

```ts
  const buildCellContainerStyle = (color?: string, background?: string) => {
    return css`
      padding: ${cellPadding}px;
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      border-right: 1px solid ${borderColor};
      ${color ? `color: ${color};` : ''};
      ${background ? `background: ${background};` : ''};
      background-clip: padding-box;
      &:last-child:not(:only-child) {
        border-right: none;
        padding-right: ${lastChildExtraPadding}px;
      }
      &:hover {
        overflow: visible;
        width: auto !important;
        box-shadow: 0 0 2px ${theme.colors.primary.main};
        background: ${background ?? rowHoverBg};
        z-index: 1;
        .cell-filter-actions  {
          display: inline-flex;
        }
      }
     // something like this 
      a {
         ${color ? `color: ${color};` : ''};
      }

    `;
  }
```

**Comment by blueForestIcarus** [comment]
This is still a problem
