### ISSUE TITLE
Datasource proxy returning 5xx for DataSource not found

### ISSUE THREAD

**Issue by ericayosh** [grafana/grafana#36418]
**What happened**:
Grafana workspace throwing 500 with the error code "data source not found", message "Unable to load datasource meta data" when calling /api/datasources/proxy/4/api/v1/query_range

When [datasources/cache](https://github.com/aws-observability/aws-grafana/blob/fbcc464c7d5197dd6cd134184d990f0bda2893bb/pkg/services/datasources/cache.go#L35) calls the [sqlstore.getDatasrouce](https://github.com/aws-observability/aws-grafana/blob/fbcc464c7d5197dd6cd134184d990f0bda2893bb/pkg/services/datasources/cache.go#L52) the sqlstore is returning a DataSource not found error [link](https://github.com/aws-observability/aws-grafana/blob/fbcc464c7d5197dd6cd134184d990f0bda2893bb/pkg/services/sqlstore/datasource.go#L62), this is being translated by the dataproxy as an Internal Server Error.

**What you expected to happen**:
Grafana returns 4xx status code when a datasource is not found 

**How to reproduce it (as minimally and precisely as possible)**:
* In a Grafana workspace add a Prometheus data source
* Go to Explore, select the Prometheus data source
* Configure simple query (example: `http_requests_total`)
* Open new tab, delete Prometheus datasource
* Go back to Explore tab and run query 

**Anything else we need to know?**:
AWS Managed Grafana reporting issue. 

**Environment**:
- Grafana version: 7.5
- Data source type & version: any datasource relying on datasources/proxy
- OS Grafana is installed on: n/a
- User OS & Browser: n/a

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/b13101fd00d55e0acef8a14af994a15f96af757f/pkg/services/datasourceproxy/datasourceproxy.go#L49

**Comment by tharun208** [comment]
@torkelo, I will raise a PR for this
