### ISSUE TITLE
Grafana behind Reverse Proxy and Telegram URL

### ISSUE THREAD

**Issue by maxdd** [grafana/grafana#36414]
Hi,
I'm using NGINX as reverse proxy and i've noticed that when there is a telegram notification the provided URL in the text message starts with http://......... (i guess because grafana is effectively running as http).
In my case given i'm using https on my domain (thanks to nginx) it would be great to have the possibility to change it (force it) to https.
In my configuration i'm using:

      - GF_SERVER_DOMAIN=**************
      - GF_SERVER_ROOT_URL=%(protocol)s://%(domain)s:%(http_port)s/**********/
      - GF_SERVER_SERVE_FROM_SUB_PATH=true

Could there be already such feature?

Regards,

**Comment by torkelo** [comment]
set GF_SERVER_ROOT_URL to your public facing URL (use use in browser, ie to your reverse proxy + any sub path)
