### ISSUE TITLE
Influx: Add easier way to name a query result like alias in the old query editor

### ISSUE THREAD

**Issue by Kallb123** [grafana/grafana#36413]
As far as I'm aware, since I can't find an easy guide for this, just being able to change the display name of a series in the graph legend requires what feels like a hack workaround. It seems you have to edit your query to include an extra column and then make sure it's classed as a group:

```
  |> set(key: "series_name", value: "My Measurement")
  |> group(columns: ["_start", "_stop", "_field", "_measurement", "domain", "entity_id", "friendly_name", "series_name"])
```

Then you also have to go to the graph properties and set the display name option to be a variable that selects the `series_name`. 

Surely there could be an easier way of doing it?
In the picture below, you'll see Grafana already has some kind of label per query (Server and PiHole here):

![image](https://user-images.githubusercontent.com/1054734/123163730-f27f0f80-d469-11eb-9bf1-1df355f2968f.png)

Could an assumption be made that one query = one series, therefore that label could be used as the display name? Then if you're displaying multiple series within a query, you might have to use the more complicated bit of logic.

**Comment by torkelo** [comment]
you should be able to just reference the label directly in the `Display name` field, example `${__field.labels.mode}`  if you want Grafana to use an influxdb label in the name. 

It looks like you want to name the query manually and use that name, but you have multiple queries so cannot just specify the value in Display name. You could use an override and target the data by query name and set Display name in the override. But a bit cumbersome.

**Comment by gabor** [comment]
hi @Kallb123:
- as a workaround, you can try set-in the `_field` property to the needed value, like `|> set(key: "_field", value:"NEW_NAME")`, it should modify the name. (we try to construct the name in a way that is similar to how influxdb's own UI does it, and it uses the `_field` attribute in the name, so if it changes, the name changes too. it should not be necessary to `group()` after this.
- if we consider a change to how things work, could you describe how you would like this to behave? i mean, what would be optimal for your use-case? (of course, no guarantees that we can implement it 😄 , but i think it is a good starting point to discuss it)

**Comment by ifrost** [comment]
We've closed this issue since it needs more information and hasn't had any activity recently. We can re-open it after you you add more information. To avoid having your issue closed in the future, please read our [CONTRIBUTING](https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md) guidelines.

Happy graphing!
