### ISSUE TITLE
 Template variables with Redis on Grafana 8 not working anymore

### ISSUE THREAD

**Issue by uebenes** [grafana/grafana#36410]
Hello together, 

**What happened**:
since the Grafana 8 update - the variable templating over the Redis data source it not working

![image](https://user-images.githubusercontent.com/59523839/124346114-a3766e80-dc0f-11eb-939b-189b842000da.png)

**What you expected to happen**:
In version 7.XX it always was possible to add variables from a Redis data source

**How to reproduce it (as minimally and precisely as possible)**:
Just try to add a redis variable to as template variable - it is **not working** with any Redis command

**Anything else we need to know?**:
The Redis Data Source is working and also works together with all the standard panels. So it's not a problem with the data source or the plugin itself. 

![image](https://user-images.githubusercontent.com/59523839/124346072-5abeb580-dc0f-11eb-899b-828e7feec3ad.png)

**Environment**:
- Grafana version: 8.04
- Data source type & version: Redis
- OS Grafana is installed on: 5.4.0-58-generic 64-Ubuntu SMP GNU/Linux
- User OS & Browser: Chrome
- Grafana plugins: Redis Plugin 1.4
- Others: I tried it out with direct installation of Grafana and also in a Docker image - same problem!

**Comment by torkelo** [comment]
Strange, any errors in browser console?

**Comment by uebenes** [comment]
I got some warnings:

![image](https://user-images.githubusercontent.com/59523839/124541477-12440980-de54-11eb-9803-aab7b306e2a5.png)

**Comment by torkelo** [comment]
@uebenes no I do not have this data source setup. We have no other similar reports. not sure what could be the cause

**Comment by uebenes** [comment]
Really? I have tested it in different environments with all common browsers. Its always worked with Grafana 7.X, but not with 8.X - so it must be a new bug, Could not be possible, that I am the only guy in the world, who uses Redis as template variable source.

**Comment by uebenes** [comment]
It seems the issue has been solved: I have tested it with Grafana 8.1 and the plugin redis-datasource version 1.5. Its working like before now! 

So, this issue can be closed!
