### ISSUE TITLE
Alerting fails on Prometheus +Inf values

### ISSUE THREAD

**Issue by dmitriishaburov** [grafana/grafana#36424]
**What happened**:

Alert rules fail when they encounter `+Inf` in a Prometheus time series.

**What you expected to happen**:

Alerts working:
- Test rule passes
- Alert firing because `+Inf > 1`
- Alert annotation saved and slack notification sent

**How to reproduce it (as minimally and precisely as possible)**:

- Create a panel with query `1 / 0`.
- Create alert `when avg() of query is above 1`
- Observe following errors:

When pressing Test Rule button: `body json marshal`

In grafana-server logs:

```
t=2021-07-05T08:06:55+0000 lvl=eror msg="body json marshal" logger=context error="json: error calling MarshalJSON for type null.Float: invalid character '+' looking for beginning of value"
t=2021-07-05T08:07:30+0000 lvl=eror msg="Failed to save annotation for new alert state" logger=alerting.resultHandler error="json: error calling MarshalJSON for type *simplejson.Json: json: error calling MarshalJSON for type null.Float: invalid character '+' looking for beginning of value"
```

Also Slack notifications fail:
```
t=2021-07-05T06:50:27+0000 lvl=eror msg="failed to send notification" logger=alerting.notifier uid=Kjr04IbWk error="json: error calling MarshalJSON for type null.Float: invalid character '+' looking for beginning of value"
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: Prometheus 2.26.0 / Thanos 0.20.1
- OS Grafana is installed on: Docker container in K8s

**Comment by ivanahuckova** [comment]
We should check if this is regression from 7.4 and if it could be related to migration to dataframes on backend.

**Comment by ivanahuckova** [comment]
This was an issue in Grafana 7.4 as well, so it is not related to migration to dataframes on backend.

I have investigates on the issue and found out, that the problem happens in `response.go`. The error is following:

```
EROR[07-16|11:03:16] Error writing to response                logger=context userId=1 orgId=1 uname=admin err="data.FrameMeta.Custom: []classic.EvalMatch: classic.EvalMatch.Labels: Metric: Value: unsupported value: +Inf"
```

and it happens specifically in `if err := enc.Encode(r.body); err != nil { ctx.Logger.Error("Error writing to response", "err", err) }` in `func (r StreamingResponse) WriteTo(ctx *models.ReqContext) {`. 

I am not very familiar with this part of the codebase and why do we use `WriteTo` for `StreamingResponse` and not `NormalResponse` and if encoding is necessary for this. Probably @grafana/backend-platform will have more context. 🙂

**Comment by marefr** [comment]
@ivanahuckova have you tried reproduce this after the Prometheus conversion to data frames? I thought problems like this won't happen with data frames. #13055 seems related. 

@kylebrandt might have some input on JSON and float/nan/infinity as well?

**Comment by ivanahuckova** [comment]
I have tried this today on current master. Now, we don't get error in the UI, just ini Grafana logs, but we also don't receive any data on frontend.

**Comment by kylebrandt** [comment]
For @ivanahuckova 's error:
When the "classic condition" operation is used in SSE is used in NG alerting adds Eval Matches (`EvalMatch`) to frame metadata, which capture series that matched a condition.

The EvalMatch has a "*float64", and JSON can't encode info/nan by the JSON specification - this fails. I think we can probably make the .Value property of EvalMatch a string, will look next week.

---

First post (7.4) (old alerting), I'm guessing the move to dataframes may have caused this, as they changed it so `Inf` values could make its way to evaluation, but less sure on this one at the moment.
