### ISSUE TITLE
8.0: Datasource influxDB: Grafana not filtering tags

### ISSUE THREAD

**Issue by Kilvador** [grafana/grafana#36436]
Hello!

I have this influxdb structure: 
Measurement=metrics
Tags: hostname, service
Field: value

1-st screenshot, Grafana 7.5.9: 

When building query i've selected **tag_hostname** and wanted to select **tag_service**. Service Names are shown _Only for selected_ **tag_hostname**.

It is as it is expetcted.

![Screenshot_1_759](https://user-images.githubusercontent.com/32729875/124477931-4a444180-ddad-11eb-8ca8-b61a7627efac.png)

2-d screenshot, Grafana 8.0.0 (tested till 8.0.4, bug is there):

Same query build, but shown **ALL Service Names in DB, no tag_hostname filter**! And it is about **any other queries and tags**.

![Screenshot_2_800](https://user-images.githubusercontent.com/32729875/124477938-4c0e0500-ddad-11eb-8057-93df274fae0c.png)

**How to reproduce it (as minimally and precisely as possible)**:

Do any influxdb query in grafana 7.5.9, upgrade to 8.0.4, try to recreate query.

**Environment**:
- Grafana version: 8.0.0-8.0.4
- Data source type & version: InfluxDB2
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Win 10 Chrome 91
- Grafana plugins: standard

**Comment by gabor** [comment]
@Kilvador thanks for the report, you are correct, we will fix this.

**Comment by Kilvador** [comment]
Thanks a lot! Will test soon!
