### ISSUE TITLE
Merge Transform not merging anymore since #36407

### ISSUE THREAD

**Issue by Blaimi** [grafana/grafana#36435]
**What happened**:
Merge transform is not merging anymore since #36407.

**What you expected to happen**:
Merge still works.

**How to reproduce it (as minimally and precisely as possible)**:
Create a datasource with duplicates, organize and merge fields.

**Anything else we need to know?**:
before the "fix":

![Bildschirmfoto von 2021-07-05 14-58-22](https://user-images.githubusercontent.com/1222379/124476056-b53c4b00-dda2-11eb-93d7-da110e442110.png)

after the "fix":

![Bildschirmfoto von 2021-07-05 15-01-30](https://user-images.githubusercontent.com/1222379/124476130-c71dee00-dda2-11eb-94a8-df18793f29dd.png)

Note also the difference between the column header and the key in the adhoc-filter – #36396 is indeed "fixed", but #36407 made it much worse!

**Environment**:
- Grafana version: 1.8.0-pre with at least 0cd2b566ad36bfe7ffcf45c660f284dec706f23a

**Comment by torkelo** [comment]
it works as it should, merge is only for merging two or more tables (results). Nothing to do when there is just a single table 

Not sure what your trying to do. Remove duplicates?

**Comment by Blaimi** [comment]
Yes, but after hiding some values with "organize fields". It was working before the commit and was my expected behaviour. The bug described in #36396 is the loss of meta-information, not that merge should behave different if it "merges" a single source.

**Comment by edgarpoce** [comment]
Hi @Blaimi, have you tried using "Group By"? I think you can group the duplicated items by the expected unique key field and then select the function to calculate the other fields, e.g. Last. I tried this approach against the url you shared and it seems to work correctly, even with a previous transformation to rename a field. https://play.grafana.org/d/OhR1ID6Mk/3-table?orgId=1.

**Comment by Blaimi** [comment]
The behaviour to delete the rename before #36407 was intentional, it is implemented in https://github.com/grafana/grafana/blob/f62bc59688c5bb73c60b2464797c946b68fb8750/packages/grafana-data/src/transformations/transformers/merge.ts#L121 since 17d87071e6850827528e109e6fe5701ce057b649 in #26042 (more specific https://github.com/grafana/grafana/pull/26042/commits/fda8e38af9c3844d4c66164f635b1502ec3eeb45#diff-d5fc984051bd84d30d6f094dc7ff96732b9c07a41bf00b90fdbce8f78d3ea8e4R180).

I.e. the report in #36396 was invalid and should have been wontfix. Before #36407 one could workaround the rename-deletion by adding another organize transform after the merge without loosing the side-effect of merging on a single frame. The behaviour of the merge is now different if you "merge" a single dataset or if you merge the same dataset with an empty one or even the same dataset twice, so I made #36469 to clarify this for the user.



> Hi @Blaimi, have you tried using "Group By"?

Not yet, but we will find a way to do this. I thought the duplicate removal was one of the intentions of the merge-transform because “mergeable values will be combined into the same row”. Since we based on an undocumented “feature” which was in fact a side effect of an unspecified situation, we are fine to have this problem now instead of somewhere in the future with an update. BTW: Best will be to not get duplicates at all from the query.
