### ISSUE TITLE
Syslog filling up with warnings

### ISSUE THREAD

**Issue by RoyKas** [grafana/grafana#36443]
After recent upgrade of Grafana to 8.0.4. on Debian, my syslog is filling up with the following warning message:

_lvl=warn msg="Request Origin is not authorized" logger=live origin=http://nas001.local:3000 appUrl=http://localhost:3000/ allowedOrigins=_

**Comment by torkelo** [comment]
You can set your grafana root_url  (ini setting) to `http://nas001.local:3000`   to make this warning go away 

or set 
```ini
[live]
allowed_origins = "https://*.example.com"
``` 

to what you use in the browser to access Grafana
