### ISSUE TITLE
Query variable with MySQL data source results in error 400

### ISSUE THREAD

**Issue by flaix** [grafana/grafana#36445]
**What happened**:

When creating a template query variable for a dashboard with a MySQL data source, the query fails with an query error 400.

<img width="1233" alt="Screenshot 2021-07-05 at 19 33 21" src="https://user-images.githubusercontent.com/2362065/124506083-38719700-ddcb-11eb-9413-dfd6677adf2d.png">

Clicking on the "Update" button at the bottom of the dialog has no effect. But the variable is created nonetheless. It has no values, though.

**What you expected to happen**:

I would expect a template variable to be created with the values that the query yields when run against the data base in the data source:

```
mysql> SELECT DISTINCT package FROM downloads;
+-----------+
| package   |
+-----------+
| api       |
| fedclient |
| manager   |
| tgz       |
| war       |
| zip       |
+-----------+
6 rows in set (0.01 sec)
```

**How to reproduce it (as minimally and precisely as possible)**:

With a MySQL data source create a query variable with whatever query returns a single column with multiple string values.

**Anything else we need to know?**:

```
mysql> describe downloads;
+-----------------+------------------+------+-----+---------+----------------+
| Field           | Type             | Null | Key | Default | Extra          |
+-----------------+------------------+------+-----+---------+----------------+
| id              | int(10) unsigned | NO   | PRI | NULL    | auto_increment |
| date            | date             | NO   |     | NULL    |                |
| package         | char(12)         | NO   | MUL |         |                |
| version         | char(12)         | NO   | MUL |         |                |
| downloads_total | mediumint(9)     | YES  |     | NULL    |                |
| downloads_day   | int(11)          | YES  |     | NULL    |                |
+-----------------+------------------+------+-----+---------+----------------+
6 rows in set (0.01 sec)
```

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: MySQL 5.7
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: macOS with Firefox 89.0.2 as well as Safari 14.1.1.
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Hello @flaix, thanks for opening this issue!

unfortunately, I'm not able to reproduce this, I'm assuming your datasource is configured properly, so can you please open the browser devtools and inspect the response of the XHR request being sent by Grafana when you get the error? there you should get more information on why the query failed

**Comment by flaix** [comment]
Sure thing. This the response:
```json
{
    "results": {
        "query0": {
            "error": "interpolation failed: time: unknown unit \"d\" in duration \"1d\"",
            "frames": [
                {
                    "schema": {
                        "meta": {},
                        "fields": []
                    },
                    "data": {
                        "values": []
                    }
                }
            ]
        }
    }
}
```

**Comment by flaix** [comment]
The MySQL data source is configured with a "min time interval" of "1d". In case that plays a role. It is the only place that I can imagine that the "1d" comes from.

**Comment by Elfo404** [comment]
Thanks for the follow up, looping in @grafana/backend-platform

**Comment by marefr** [comment]
Able to reproduce on Grafana v8.0.3 and main (dev) using MySQL 5.6 with a min interval of `1d`.

**Comment by marefr** [comment]
Seems like #32257 changed to properly returning an error in case getting the min-interval returns an error:
https://github.com/grafana/grafana/blob/67b977fd6352bba00e1f2cc60c6800a9cf6e04ae/pkg/tsdb/sqleng/sql_engine.go#L349

To me seems like using a unit bigger than hour, i.e. days/`1d`, as min interval on data source level has never worked as expected,  but rather the error has been swallowed.

I can see two different solutions here, first thing would be to fix this error happening on every query for any SQL data source that has min interval configured to something like `1d` or higher. Short term solution for this would be to log the error and don't return the error.

The actual solution for supporting min intervals of `1d` and higher would be to replace the following with `gtime.ParseInterval(interval)`
https://github.com/grafana/grafana/blob/67b977fd6352bba00e1f2cc60c6800a9cf6e04ae/pkg/tsdb/calculator.go#L93
https://github.com/grafana/grafana/blob/67b977fd6352bba00e1f2cc60c6800a9cf6e04ae/pkg/tsdb/interval/interval.go#L100

**Comment by marefr** [comment]
@flaix Workaround for now is to use `24h` as min interval instead of `1d`.

**Comment by flaix** [comment]
I can confirm, that the workaround works. Thank you!
