### ISSUE TITLE
The y-axis digital display of the time series panel is wrong

### ISSUE THREAD

**Issue by liner-lin** [grafana/grafana#36448]
**What happened**:
![image](https://user-images.githubusercontent.com/25217954/124535316-7c56b180-de48-11eb-9a23-4dd85442c31c.png)
configs:
![image](https://user-images.githubusercontent.com/25217954/124535426-a9a35f80-de48-11eb-8f83-f409bc6c5ecf.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Grafana v8.0.3 (cae5c5e46b)
- Data source type & version:
- prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Mac & chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Looks correct to me, can you describe what is wrong? you specified 0 decimals and that is what you got

**Comment by liner-lin** [comment]
> Looks correct to me, can you describe what is wrong? you specified 0 decimals and that is what you got

oh，I'm sorry! I am referring to the Y axis, not the X axis.It should be "0 1 2"  not "0 0 0 1 1 1 1 2 2 2", just like the old  Graph panel.
![image](https://user-images.githubusercontent.com/25217954/124546063-a6b26a00-de5c-11eb-8484-a4faeb765f3c.png)

**Comment by leeoniya** [comment]
this is related to https://github.com/grafana/grafana/issues/35838 (or maybe some of the linked issues in there, too).

it looks like the old graph filtered tick labels in a way that, once formatted to the number of indicated decimal places, removed any duplicates that did not exactly match the tick value.

**Comment by torkelo** [comment]
but your old graph has a different max value (6), and you specified 0 decimals

**Comment by torkelo** [comment]
This is the new times series panel, with the same data you have. Set soft max of 6, reset default 
![Screenshot from 2021-07-06 09-30-50](https://user-images.githubusercontent.com/10999/124560234-dea9b500-de3c-11eb-9d13-4a9365b34870.png)
