### ISSUE TITLE
$__interval_60s and $__interval_s variables

### ISSUE THREAD

**Issue by bgardner-noggin** [grafana/grafana#36447]
**What would you like to be added**:
Dynamically calculate two new variables for the interval

$__interval_s - The $__interval variable converted to seconds, eg 1m -> 60, 1h -> 3600
$__interval_60s - The $_interval variable converted to seconds but rounded to the nearest multiple of 60 seconds

**Why is this needed**:

I have the following cloudwatch metrics search query. 

_SEARCH('AWS/DynamoDB TableName=$Cluster MetricName="ConsumedReadCapacityUnits"', 'Average', 60)_

When I'm viewing data for more than 2 days, I get a "too many datapoints" warning from Cloudwatch.

I would like to use the dynamic interval calculations already supported by grafana which populate the $__interval and $__interval_ms variables. However I cannot use these as they are because cloudwatch requires the period in seconds and in multiples of 60

If these variables existed, I could configure min interval, max data points and then change the query to

_SEARCH('AWS/DynamoDB TableName=$Cluster MetricName="ConsumedReadCapacityUnits"', 'Average', **$__interval_60s**)_

**Comment by bgardner-noggin** [comment]
One slight tweak, the $__interval_60s should have a minimum of 60, ie if less than 60, round up. Although this could be worked around with the existing minimum interval setting

**Comment by torkelo** [comment]
duplicate (or extension) of  https://github.com/grafana/grafana/issues/20262
