### ISSUE TITLE
Forecast does not forecast.

### ISSUE THREAD

**Issue by fuqqer** [grafana/grafana#3644]
The holtWinters forecast function does not show predictive values.  It only shows "would have forecast values" for already existing time periods. It should display the predicted value (X seconds into the future) based on the size of the sample selected.

Bug #1576  was erroneously closed.

**Comment by tmonk42** [comment]
The function doesn't exist in Grafana, it's a Graphite function and would need to be fixed there. On the Grafana end, there's just a list of what Graphite functions can be called.

**Comment by fuqqer** [comment]
Sorry, wrong project. I'll go back to asking graphite maintainers.
