### ISSUE TITLE
iframe share panel "Grafana has failed to load its application files" error

### ISSUE THREAD

**Issue by felixmondelo** [grafana/grafana#36456]
**What happened**:

When I share a panel in an iframe, the message "If you're seeing this Grafana has failed to load its application files" appears.

The problem is in Chrome, with Microsoft Edge for example it's working.

**What you expected to happen**:

It's supposed that I can see my panel with the data.

**How to reproduce it (as minimally and precisely as possible)**:

Export a panel within an iframe and include the iframe in a HTML page.

**Environment**:
- Grafana version: 7.3.7
- Data source type & version: Azure Data Explorer 
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: Gantt and Azure Data Explorer
- Others:

**Comment by torkelo** [comment]
you might have to enable embedding, https://grafana.com/docs/grafana/latest/administration/configuration/#allow_embedding 

there are browser security features that disable this by default
