### ISSUE TITLE
Variables with dashes don't interpolate with OpenTSDB

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#3645]
Imagine timeseries like `mymetric {node=myserver,node-type=db}`. I want to plot `mymetric` per node type. This doesn't work, since `$tag_node-type` interpolates to `myserver-type`.

I'm on 2.6.

**Comment by torkelo** [comment]
you can use ``[[tag_node-type]]`` syntax for these cases

**Comment by bobrik** [comment]
I think docs should mention that.

![image](https://cloud.githubusercontent.com/assets/89186/12126960/3468bf44-b3ec-11e5-9575-517fb569e6bb.png)


Also, it is not mentioned here and image is broken: http://docs.grafana.org/datasources/opentsdb/
