### ISSUE TITLE
Alerting: Dashboard links on Alerts panel (ngalert)

### ISSUE THREAD

**Issue by haelekuin** [grafana/grafana#36451]
**What would you like to be added**:
On the Alerts panel when using ngalerts, add the ability to link dashboards / panels and open them in a new tab.

**Why is this needed**:
This feature was present with legacy alerts.

**Comment by alexweav** [comment]
This could be stored as an annotation which could be picked up in the UI.

**Comment by konrad147** [comment]
This has been fixed by https://github.com/grafana/grafana/pull/63648
