### ISSUE TITLE
Postgres/MySQL: Allow more than 100 where-values when using the graphical query builder

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#36467]
**What would you like to be added**:
Allow more than 100 where-values in the graphical query builder.

![image](https://user-images.githubusercontent.com/1668778/124581678-96e15880-de51-11eb-9189-43cbd5011302.png)

**Why is this needed**:
To allow users that uses the graphical query builder to filter queries in an exploratory fashion when there's more than 100 values and not knowing every single stored value.

**Additional information**:
Making the limit of 100 configurable is not really a solution to this because it doesn't scale. One idea might be to allow user to search for values in the database when input of characters in the drop down happens. Another idea would be to implement support for pagination and/or in combination with searching for values.

**Comment by zoltanbedi** [comment]
This is not limited in the new query builder.
