### ISSUE TITLE
building from source on debian 6 x86

### ISSUE THREAD

**Issue by sharon77242** [grafana/grafana#3646]
hi i tried to build from source according to instructions it seems all installed correct.
i started grafana and then it shows blank white page i entered chrome console and it shows errors on:
* es6-shim.js:30Uncaught TypeError: Object function call() { [native code] } has no method 'bind'
(anonymous function)es6-shim.js:30
(anonymous function)es6-shim.js:25
(anonymous function)es6-shim.js:27
in this rows:
 (this, function () {
  'use strict';

row 30:  var _apply = Function.call.bind(Function.apply);
  var _call = Function.call.bind(Function.call);
  var isArray = Array.isArray;

* boot.js:6Uncaught SyntaxError: Unexpected token catch
and here:
(function bootGrafana() {
  'use strict';

  System.import('app/app').then(function(app) {
    app.init();
  }).catch(function(err) {
    console.log('Loading app module failed: ', err);
  });

})();

thank you.

**Comment by torkelo** [comment]
what browser and os are you using? Did you run the default grunt task?

**Comment by sharon77242** [comment]
as i mentioned on the title the os is debian 6 32 bit with chrominum browser tried with epiphany also,
with default grunt task you mean grunt command without arguments? if so yes.
thank a lot for your response

**Comment by sharon77242** [comment]
what am i doing wrong can someone build it for me?
