### ISSUE TITLE
Annonations plugin for grafana

### ISSUE THREAD

**Issue by pedrooct** [grafana/grafana#36470]
**Annotations list plugin grafana improvements**:

**Why is this needed**: The panel for annotations is in alpha and has a lot of bugs, but it provides a good way to present annotations since in grafana 8, at least for my knowledge, it doesn't provide support for annotations to be present other than on graphs.

**Comment by torkelo** [comment]
ok, thanks for the feedback, will try to prioritize this panel

**Comment by pedrooct** [comment]
Thank you for the response! 👍
