### ISSUE TITLE
ngalert: Support 'serve_from_subpath = true'

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#36479]
Grafana v8.1.0-27591pre
on Windows Server 2019
via Web Proxy

custom.ini
```
[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_subpath = true
```

<img width="562" alt="grafik" src="https://user-images.githubusercontent.com/79257887/124624833-8d6de580-de7d-11eb-936e-5b3a07b44fe0.png">

In the url `\grafana` is missing if i click on `View in Explore`.

**Comment by UlrichThiess** [comment]
Found another one:
<img width="1641" alt="grafik" src="https://user-images.githubusercontent.com/79257887/124625720-56e49a80-de7e-11eb-99d8-5ec0d9828308.png">

**Comment by peterholmberg** [comment]
@UlrichThiess Hi!

for me the buttons redirect to the correctly. Can you confirm that you still have this issue?

**Comment by UlrichThiess** [comment]
If i hover the View-Button:

![grafik](https://user-images.githubusercontent.com/79257887/130045425-5903e3ed-6294-48b2-aaa9-74aeafef16ef.png)

The root-URL is not correct .... But it works!

If i hover the See graph-Button:

![grafik](https://user-images.githubusercontent.com/79257887/130045631-54f689b8-e176-4ed7-80ef-878655f35a5c.png)

**Comment by UlrichThiess** [comment]
![grafik](https://user-images.githubusercontent.com/79257887/130046319-15a33198-f432-49c8-aaef-3951e8d75e9a.png)

I hover `View`. Wrong URL (missing `/grafana/`), but on click it loads the correct site in the **same** browser tab with `/grafana/`.

![grafik](https://user-images.githubusercontent.com/79257887/130046473-9fd6c675-d9b8-4b45-a64e-dd6c705a5b20.png)

Now i hover `View in Explore`, wrong URL (missing `/grafana/`), on click it opens a new browser tab with wrong url. `/grafana/` is still missing.

Sometimes you open in the same browser tab and sometime you open in a new browser tab. I can't see rules on this....

**Comment by peterholmberg** [comment]
Gotcha, I see the same thing.
