### ISSUE TITLE
today() for specific panels

### ISSUE THREAD

**Issue by stephanstapel** [grafana/grafana#3647]
I found https://github.com/grafana/grafana/issues/1186 where having "today" and "the day so far" was discussed, implemented and introduced on dashboard level.

Unforfortunately I didn't find this possibility on panel level (using InfluxDB here). It'd be great to have this feature to show things like 'orders so far today'.

If this is already possible, posting a hint would be great!

**Comment by jakubholynet** [comment]
Hi, why was this closed? I would also like to know if it is / will be possible to use "today()" for a particular panel. Thanks!

**Comment by gcrevell** [comment]
I know this is old, but for other people who stumble upon this issue like I did, the solution is to use `now/d` in the relative time field in a panel.

**Comment by Appelg** [comment]
A bit late to the party, but writing **0d/d** in Time shift gets "TODAY" for the panel. I did not find documentation for this, https://grafana.com/docs/grafana/latest/panels/queries/#query-options those tables need a bit of more examples.
