### ISSUE TITLE
grafana-image-renderer cannot find chrome in custom docker image with pre-installed image renderer

### ISSUE THREAD

**Issue by derekjc** [grafana/grafana#36476]
**What happened**: I followed the instructions shown in [custom-image-with-grafana-image-renderer-plugin-pre-installed](https://grafana.com/docs/grafana/latest/installation/docker/#custom-image-with-grafana-image-renderer-plugin-pre-installed) to add the image-renderer plugin to a custom docker image. Rendering of images fails "Rendering failed.".

Docker logs:
```
logger=context userId=1 orgId=1 uname=admin method=POST path=/api/user/password/reset status=400 remote_addr=103.97.93.184 time_ms=10 size=52 referer=http://172.105.48.21:3000/login
INFO[07-06|13:26:09] Rendering                                logger=rendering renderer=plugin path="d-solo/cOLjyRm7z/test?orgId=1&from=1625556067692&to=1625577667692&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta"
EROR[07-06|13:26:09] Render request failed                    logger=plugins.backend pluginId=grafana-image-renderer error="Error: Failed to launch the browser process! spawn /var/lib/grafana-plugins/grafana-image-renderer/chrome-linux/chrome ENOENT\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n" url="http://localhost:3000/d-solo/cOLjyRm7z/test?orgId=1&from=1625556067692&to=1625577667692&panelId=2&width=1000&height=500&tz=Asia%2FCalcutta&render=1"
EROR[07-06|13:26:09] Rendering failed.                        logger=context userId=1 orgId=1 uname=admin error="rendering failed: Error: Failed to launch the browser process! spawn /var/lib/grafana-plugins/grafana-image-renderer/chrome-linux/chrome ENOENT\n\n\nTROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/master/docs/troubleshooting.md\n"
```
It looks like grafana or the plugin is trying to execute "/var/lib/grafana-plugins/grafana-image-renderer/chrome-linux/chrome" even though it does not exist. It doesn't seem to be looking at environment variable `GF_RENDERER_PLUGIN_CHROME_BIN=/usr/bin/chromium-browser`

**What you expected to happen**: Image rendering should work as documented

**How to reproduce it (as minimally and precisely as possible)**:
* Build docker using instructions in [docs](https://grafana.com/docs/grafana/latest/installation/docker/#custom-image-with-grafana-image-renderer-plugin-pre-installed).
* Run it, create a panel, try to share it with "Direct link rendered image" option.

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.0.4
- Data source type & version:N/A
- OS Grafana is installed on:Debian 10 amd64
- User OS & Browser:Fedora/Firefox
- Grafana plugins:grafana-image-renderer
- Others:

**Comment by torkelo** [comment]
Was able to replicate this.

**Comment by marefr** [comment]
Seems to accidentally have been removed in https://github.com/grafana/grafana-image-renderer/pull/233. But think the more appropriate is to change the custom Docker file to use the environment variable `GF_PLUGIN_RENDERING_CHROME_BIN`, [ref](https://github.com/grafana/grafana-image-renderer/blob/7a34f24eac6c731f0da40a3f1f5798547cc7556d/src/plugin/v2/grpc_plugin.ts#L186-L188).

As a workaround, when building your custom image can you set the `GF_PLUGIN_RENDERING_CHROME_BIN` environment variable?

**Comment by derekjc** [comment]
@marefr I added GF_PLUGIN_RENDERING_CHROME_BIN as a runtime docker environment variable and it works. Thanks for the workaround!
