### ISSUE TITLE
Postgres/MySQL: Existing where-expressions should be taken into account when auto-completing where-values using the graphical query builder

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#36473]
**What would you like to be added**:
Existing where-expressions should be taken into account when auto-completing where-values using the graphical query builder.

**Why is this needed**:
To allow users that uses the graphical query builder to filter queries in an exploratory fashion and get suggestions of where-values part of the data already filtered out.

**Comment by mdvictor** [comment]
We will look more into this as we continue improving the SQL editors after their migration to react. Will return with further answers when we start working on improving the MySQL editor
