### ISSUE TITLE
Document process for including dashboards in plugin.json 

### ISSUE THREAD

**Issue by wbrowne** [grafana/grafana#36475]
**What would you like to be added**:

**Why is this needed**:
Addresses the confusion in #12509

**Related issue(s):**
https://github.com/grafana/integrations-team/issues/239

**Related PR(s):** https://github.com/grafana/grafana/pull/40410

**Comment by achatterjee-grafana** [comment]
Hello @wbrowne, should we close this issue? TY

**Comment by wbrowne** [comment]
I'm not sure that this is complete yet @achatterjee-grafana. We're planning to refactor some of this soon so we will likely include documentation changes there too so I'll keep this open for that reason

**Comment by wbrowne** [comment]
Can close in that case 😄
