### ISSUE TITLE
Sorting is not honored by exporting the table CSV

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#36472]
**What happened**: Sorting is not honored by exporting the table. By default, the below table is sorted in descending order by time. However, in the CSV exported file, it is in ascending order.

**What you expected to happen**: The CSV export should honor the sorting we set in the dashboard table.

**How to reproduce it (as minimally and precisely as possible)**: 

- Create a table and save the dashboard with some sorted order on any column.
- Now clieck on inspect data and switch on Apply panel transformations, Formated data and dowload for excel.
- From the preview apply sorting and click on download CSV
- The downloaded CSV will not honer either the sorting that we applied on dashboard or on the previw.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 7.5.5 and above
- Data source type & version: Any
- OS Grafana is installed on: Any
- User OS & Browser: Any
- Grafana plugins: Tabe
- Others:

**Comment by torkelo** [comment]
The export to CSV is there for the raw data, any visualization specific options won't carry over. If you want to sort data and have it be preserved in csv export you will have to use the sort by transform.

**Comment by satyatechy** [comment]
> The export to CSV is there for the raw data, any visualization specific options won't carry over. If you want to sort data and have it be preserved in csv export you will have to use the sort by transform.

Thank you @torkelo sort by transform works for our use case.
