### ISSUE TITLE
Render as png doesn't seem to work

### ISSUE THREAD

**Issue by paulbakker** [grafana/grafana#3648]
Rendering panels as png doesn't seem to work. I do get an image with a graph, but it's always empty:

<img width="502" alt="screen shot 2016-01-05 at 21 41 01" src="https://cloud.githubusercontent.com/assets/109484/12127016/0c4566da-b3f5-11e5-972a-61abb7748cc7.png">

The logs don't show errors.
```
2016/01/05 20:39:12 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/new-dashboard?panelId=1&fullscreen&edit&var-host=todo-release-208-kahl8&width=1000&height=500
Loading a web page: http://localhost:3000/dashboard-solo/db/new-dashboard?panelId=1&fullscreen&edit&var-host=todo-release-208-kahl8&width=1000&height=500
```

I'm running the official Docker image. Other types of sharing (link, iframe etc.) work correctly.

**Comment by torkelo** [comment]
it does work on every instance I have access to, must  be something strange going on in your case.

it tries to open http://localhost:3000/dashboard-solo/db/new-dashboard?panelId=1&fullscreen&edit&var-host=todo-release-208-kahl8&width=1000&height=500  url in phantomjs on the grafana server, is your time series store accessable from there?

**Comment by paulbakker** [comment]
The url was indeed the problem. Forgot that Docker (on osx) doesn't run on localhost... Thanks for the hint!

**Comment by torkelo** [comment]
No problem! Glad you got it to work:)
