### ISSUE TITLE
State Timeline missing alerts tab

### ISSUE THREAD

**Issue by gmariani** [grafana/grafana#36480]
The Alerts tab is missing from the State Timeline widget. Is this on purpose or coming soon?

**Comment by torkelo** [comment]
yes, it is on purpose. The new alert engine is standalone and separate from dashboards and panels. 
https://grafana.com/docs/grafana/latest/alerting/unified-alerting/ 

you can link an alert rule to a dashboard and panel but it's just an additional info to the standalone alert rule.

**Comment by gmariani** [comment]
@torkelo 
That's what I suspected and I did look....and I don't see any other way to create an alert. So is this a separate bug then? Please see the screenshots from my installation of Grafana v8.0.3. There is no option to create an Alert Rule except from the dashboard widgets which you now say are no longer being used....

![Screenshot 2021-07-06 14 02 04](https://user-images.githubusercontent.com/5058619/124646760-0f044a00-de63-11eb-90d1-d55d89a02a0c.png)
![Capture](https://user-images.githubusercontent.com/5058619/124646762-0f9ce080-de63-11eb-8d7c-de1593de4e27.PNG)

**Comment by torkelo** [comment]
With the current alert system (the new system is opt-in via feature toggle) you create a new alert rule via a the Alert tab (if timeseries or old graph visualization selected)
