### ISSUE TITLE
Some users are unable to switch organizations somewhere since 8.0 upgrade.

### ISSUE THREAD

**Issue by yoshi314** [grafana/grafana#36499]
**What happened**:

SOME  users lost access to organizations in grafana. The picker only lists "All users" as their choice. Users are authenticated via ldap in apache first.

From the admin panel, they are assigned to various orgs but they cannot pick anything in the org switcher except for 'all users'.

**What you expected to happen**:

No changes.

**How to reproduce it (as minimally and precisely as possible)**:

No clue. Have an affected user, or a new user.  Assign him to few organizations.  He cannot pick any to switch to. It looks ok in sqlite as well.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: graphite, prometheus
- OS Grafana is installed on: debian 9
- User OS & Browser: firefox, chrome
- Grafana plugins:
```
alexanderzobnin-zabbix-app
btplc-status-dot-panel
ddurieux-glpi-app
flant-statusmap-panel
fzakaria-simple-annotations-datasource
grafana-image-renderer
grafana-kubernetes-app
grafana-piechart-panel
grafana-simple-json-datasource
raintank-worldping-app
vonage-status-panel
yesoreyeram-boomtable-panel
```

**Comment by yoshi314** [comment]
I'll try to reproducing that on separate instance with copy of the sqlite db.

**Comment by Elfo404** [comment]
Hello @yoshi314 , thanks for reporting this.

looping in @grafana/backend-platform.

**Comment by yoshi314** [comment]
If there is anytning i can do to narrow this down, i'll be happy to try.

**Comment by marefr** [comment]
@yoshi314 do you see any errors logged in console tab while using for example Chrome developer tools or similar when trying to switch organization? Do you see any interesting errors/messages logged in the Grafana server log?

To me ldap sounds like the potential problem here. If a user having this problems being logged into Grafana, what is the result of opening `http://<grafana host>/api/user/orgs` in the browser?

**Comment by yoshi314** [comment]
it's not the problem with login, since apache does it and grafana is provided the username.

The user appears in admin panel, i assign orgs to them. And they cannot pick any org to switch to.

Nothing interesting in server log, but i'll see in the browser.

**Comment by yoshi314** [comment]
interesting detail i noticed is - users who have issues have email and username set to (nulll), whiile users that have correct interaction with grafana have those fields filled out.

**Comment by yoshi314** [comment]
Switching to private mode seems to fix things temporarily. Deleting cookies also sometimes helps.

It might be something within our Kerberos communication, since that is disabled in private mode.

**Comment by yoshi314** [comment]
Ok, i had an exception for /api in apache config. It used to be ok in 7.x but broke 8.x somehow. 

For now, this is fixed.
