### ISSUE TITLE
No library panels found

### ISSUE THREAD

**Issue by victorclaessen** [grafana/grafana#36491]
**What happened**:

After upgrading to grafana 8 on debian, I wanted to create a new dashboard. However, no library panels are available.
![image](https://user-images.githubusercontent.com/11179036/124670327-1d2e8680-deb4-11eb-8451-90d10f49e555.png)

**What you expected to happen**:

I expected there to be some panels which I could add.

**How to reproduce it (as minimally and precisely as possible)**:

I guess upgrade grafana 7 to 8 on Debian, and try to add a new dashboard with a panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.04
- Data source type & version: MySQL
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 10 Firefox 89.0.2
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
you need to add some panels to the library first. The panel library is composed of panels you have stored and added to it.

**Comment by torkelo** [comment]
you can add panels to the library from the panel menu, or from edit panel / open visualization picker, change to library panels

**Comment by rgordill** [comment]
8.1.1 on Fedora:

GET http://localhost:3000/library-panels 404 (Not Found)
