### ISSUE TITLE
Time macros not working in Variable query against Azure Monitor datasource

### ISSUE THREAD

**Issue by Blackbaud-ChrisBlythe** [grafana/grafana#36490]
**What happened**:
I'm trying to leverage the various time macros (e.g. $__timeFilter, $__timeTo, etc.) in a LogAnalytics query to populate a dashboard variable against an Azure Monitor datasource. I've tried several variations, but nothing seems to work. Hopefully, it's something simple that I'm missing?
 
![image](https://user-images.githubusercontent.com/14931768/124667347-e6854b80-de74-11eb-9edf-ec8899ee871b.png)

**What you expected to happen**:
Since these macros work in queries that populate dashboards, I would expect them to work in Variable queries as well.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Variable against an Azure Monitor datasource that leverages a LogAnaltyics query to populate the data
- Add one of the time macros in a where clause to filter the data by time (e.g. _| where $__timeFilter(TimeGenerated)_)

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: Azure Monitor 0.3.0
- OS Grafana is installed on: Linux

**Comment by ehuggz** [comment]
@Blackbaud-ChrisBlythe 
I use Grafana exclusively to create Azure Dashboards from LogAnalytics and ApplicationInsights Kusto Queries. 
It is great to see another Azure SRE using Grafana - there aren't a lot of us yet.

A couple of things:
1. Your Data Source setup looks odd. Grafana 8 switches to using Logs as the source for Application Insights and Log Analytics.
2. Entries are case sensitive and there are two underscores ("_") after the $
3. I see you are not ordering your series by TimeGenerated asc - that can also cause issues in Grafana.

I am running Grafana 8 Pro (Grafana Hosted), but have also run Grafana 7 from K8 on AKS without issues so I don't think that is your problem either. You could try setting up a free Grafana Hosted  account and connecting to your Azure Data Sources if that is possible in your configuration. Hosted Grafana works well. That would help validate to your internal config. 

![image](https://user-images.githubusercontent.com/544939/125457390-63388b0e-e1ba-43b0-b9dd-030e7d4dd9a1.png)

**Comment by andresmgot** [comment]
I can verify that macros are not working in the latest version for template variables.

Thanks for your comment @ehuggz. Indeed the macro works fine for panel queries but the issue @Blackbaud-ChrisBlythe is seeing is when creating [template variables](https://grafana.com/docs/grafana/latest/datasources/azuremonitor/template-variables/).

**Comment by Blackbaud-ChrisBlythe** [comment]
Thanks for the confirmation @andresmgot and comments @ehuggz!
