### ISSUE TITLE
Allow to specify maximum length for alert tags

### ISSUE THREAD

**Issue by olexandrger** [grafana/grafana#36500]
**What would you like to be added**:
Please allow redefining via properties maximum allowed length for alert tag.

**Why is this needed**:
Currently, maximum length is hardcoded to 100 characters [here](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/tag_mig.go#L11)

But there are cases when this is not enough. For example, some URLs can exceed this limit. Also, usage of VARCHAR(255) is very common in databases and such fields can not be added to the tag.

Thanks

**Comment by ying-jeanne** [comment]
this is a duplicate issue of https://github.com/grafana/grafana/issues/22853, something keep in mind:
1.  To make it configurable would be a bad idea, knowing that it would be over killed to run migration every-time when settings changes. And it might cause no backward compatible changes when we decrease the length, not sure we want to support that.
2. MySQL has a limit on index size that would be 767 bytes : https://github.com/grafana/grafana/issues/10779, if we modify the length to 255, we end-up around 710 bytes for the index, that means in the future no more column could be added to the index anymore.

It would be unlikely that we would increase the length of alert tags in db, except there are really a strong needs.
