### ISSUE TITLE
cannot generate query_Ctrl.ts

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36509]
Why don't I use this command “npx @grafana/toolkit plugin:create my-plugin” to generate a file without query_Ctrl.ts

**Comment by torkelo** [comment]
Just ran this, there is no query_ctrl in the starter template. We do not want new angular plugins, only react :) 

![Screenshot from 2021-07-07 15-56-04](https://user-images.githubusercontent.com/10999/124772026-ec922f80-df3b-11eb-93e1-b7e7ba784e40.png)
