### ISSUE TITLE
Grafana sends datasource name as undefined with mixed plugin made as default datasource 

### ISSUE THREAD

**Issue by ShilpaSivanesan** [grafana/grafana#36508]
**What happened**: mixed plugin when made as a default data source returns data source name as undefined

**What you expected to happen**: the mixed plugin should send the data source name

**How to reproduce it (as minimally and precisely as possible)**: make mixed type plugin as default, add a query for the data source, which will not return anything

check for the dsName value in the console 

```
options.target

datasource: undefined
expression: "A['ct']+10"
hide: false
outputMetricName: "ct1"
periods: 7
queryType: "Arithmetic"
refId: "B"
timeshiftUnit: "days
```

**Anything else we need to know?**: It happens only with mixed type plugin

**Environment**:
- Grafana version: V8.4.0
- Data source type & version: Mixed plugin
- OS Grafana is installed on: linux
- User OS & Browser: chrome
- Grafana plugins: MetaQueries [PM]
- Others:

**Comment by zoltanbedi** [comment]
I tried to reproduce this but couldn't. I saw datasource filled in the console. Can you please provide more detailed steps to reproduce?

**Comment by samfadrigalan** [comment]
I ran into a similar issue. Here's some screenshots with how to reproduce the issue.

#### Grafana 7 Query Editor Row props -- `datasource` is defined for new queries
<img width="1340" alt="Screen Shot 2021-07-14 at 11 16 34 AM" src="https://user-images.githubusercontent.com/6889258/125654806-69d43dd5-9495-4d58-a178-2626c335d3d9.png">

#### Grafana 8 Query Editor Row props -- undefined `datasource` for new queries
<img width="1347" alt="Screen Shot 2021-07-14 at 11 19 59 AM" src="https://user-images.githubusercontent.com/6889258/125655187-8dd911bd-ee46-4b0a-b65e-cd202f7c55b5.png">

#### Grafana 8 Query Editor Row props -- `datasource` is defined after some steps
<img width="1346" alt="Screen Shot 2021-07-14 at 11 24 44 AM" src="https://user-images.githubusercontent.com/6889258/125655642-b61ffc9d-880b-429a-bd7b-05532d2fbead.png">

**Comment by zoltanbedi** [comment]
I think this is an issue in the plugin. I'm going to close this now but we can reopen if you think there is something that we should do.
