### ISSUE TITLE
[time-series] Bars with line-width = 0 do not show depending on time-range

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#36519]
Hi,

**What happened**:

With time-series panel, when bars are configured with `line-width = 0`, depending on the time-range, they are not visible at all (see screenrecord below).
I set `line-width = 0` and `fill-opacity = 100` for bars so that they are not visible at all on the x-axis when data value is 0 (with `line-width = 1` we have a line all over the x-axis).
It used to properly work with the (now deprecated) graph-panel, but then this configuration leads to a display bug with the time-series panel.

**What you expected to happen**:

Bars properly show with `line-width = 0`, whatever the time-range is.

**How to reproduce it (as minimally and precisely as possible)**:

Use time-series panel, set bars with with `line-width = 0` and `fill-opacity = 100`, play with the time-range.

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: InfluxDB
- OS Grafana is installed on: Linux
- User OS & Browser: MacOS, Safari & Firefox
- Grafana plugins: -
- Others: -

![bars](https://user-images.githubusercontent.com/6764151/124770605-c28c3d80-df3a-11eb-9ac2-73fe1108bffa.gif)

**Comment by torkelo** [comment]
@leeoniya any thoughts? is this reasonable to support?

**Comment by leeoniya** [comment]
yes, i'm pretty sure what happens here is that the bar width is being computed from the closest adjacent points and when the time range is 2 days and the datapoints are 1min apart, the bar width becomes < 0.5px and is likely rounded to 0. i'll add either a configurable or hard-coded 1px minimum in the next uPlot update that should solve this.

**Comment by benrubson** [comment]
Really good news, many thanks guys 👍

**Comment by leeoniya** [comment]
added a minWidth param here: https://github.com/leeoniya/uPlot/commit/64fce0bde510411fa94617c005956aaac423a3cc

**Comment by benrubson** [comment]
Closing this, fixed in 8.1.0.
Thank you again :+1:
