### ISSUE TITLE
display metric bytes as bits

### ISSUE THREAD

**Issue by pdxmaverick** [grafana/grafana#3651]
Using Zenoss 5, data is stored in OpenTSDB.

I need to be able to display ifHCOutOctets as bps, the data is stored in Bps.

How can I modify the data, i.e. *8?

**Comment by torkelo** [comment]
most Time series stores support many metric transformation functions and scaling math etc, OpenTSDB however does not :(

**Comment by torkelo** [comment]
but I suggest you open a feature request with the OpenTSDB project :)
