### ISSUE TITLE
Yarn Install Produces error, unable to build plugin from starter pack

### ISSUE THREAD

**Issue by shashwata27** [grafana/grafana#36518]
**What happened**:
After getting toolkit using `npx --legacy-peer-deps ... .` , I excuted yarn install and this gave the following error.
`C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin>yarn install
yarn install v1.22.10
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.13: The platform "win32" is incompatible with this module.
info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
info fsevents@2.3.1: The platform "win32" is incompatible with this module.
info "fsevents@2.3.1" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning "@grafana/toolkit > ts-jest@26.3.0" has incorrect peer dependency "jest@>=26 <27".
warning "@grafana/toolkit > @grafana/ui > @grafana/slate-react > slate-react-placeholder@0.2.9" has unmet peer dependency "slate-react@>=0.22.0".
warning "@grafana/toolkit > @grafana/ui > @torkelo/react-select > react-input-autosize@2.2.2" has incorrect peer dependency "react@^0.14.9 || ^15.3.0 || ^16.0.0-rc || ^16.0".
warning "@grafana/toolkit > @grafana/ui > rc-cascader > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react@^16.0.0".
warning "@grafana/toolkit > @grafana/ui > rc-cascader > rc-trigger > rc-motion@1.1.2" has incorrect peer dependency "react-dom@^16.0.0".
[5/5] Building fresh packages...
[-/4] ⠄ waiting...
[-/4] ⠄ waiting...
[3/4] ⠄ node-sass
error C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\node-sass: Command failed.Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\node-sass
Output:
Building: C:\Program Files\nodejs\node.exe C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\node-gyp\bin\node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [
gyp verb cli   'C:\\Program Files\\nodejs\\node.exe',
gyp verb cli   'C:\\Program Files\\GrafanaLabs\\grafana\\plugins-bundled\\internal\\basic-plugin\\node_modules\\node-gyp\\bin\\node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library='
gyp verb cli ]
gyp info using node-gyp@3.8.0
gyp info using node@15.7.0 | win32 | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` failed Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21)
gyp verb `which` failed  python2 Error: not found: python2
gyp verb `which` failed     at getNotFoundError (C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:13:12)
gyp verb `which` failed     at F (C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:68:19)
gyp verb `which` failed     at E (C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:80:29)
gyp verb `which` failed     at C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\which\which.js:89:16
gyp verb `which` failed     at C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\isexe\index.js:42:5
gyp verb `which` failed     at C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\isexe\windows.js:36:5
gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:194:21) {
gyp verb `which` failed   code: 'ENOENT'
gyp verb `which` failed }
gyp verb check python checking for Python executable "python" in the PATH
gyp verb `which` succeeded python C:\Users\sahas\AppData\Local\Programs\Python\Python39\python.EXE
gyp ERR! configure error
gyp ERR! stack Error: Command failed: C:\Users\sahas\AppData\Local\Programs\Python\Python39\python.EXE -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (node:child_process:333:12)
gyp ERR! stack     at ChildProcess.emit (node:events:379:20)
gyp ERR! stack     at maybeClose (node:internal/child_process:1069:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:300:5)
gyp ERR! System Windows_NT 10.0.19042
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\GrafanaLabs\\grafana\\plugins-bundled\\internal\\basic-plugin\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd C:\Program Files\GrafanaLabs\grafana\plugins-bundled\internal\basic-plugin\node_modules\node-sass
gyp ERR! node -v v15.7.0
gyp ERR! node-gyp -v v3.8.0
`

**What you expected to happen**:
I expected to have a plugin to be built.

**How to reproduce it (as minimally and precisely as possible)**:
use the latest version of npm and node, I have python3 installed in system

**Anything else we need to know?**:

**Environment**:
- Grafana version:7.5.6
- Data source type & version: panel plugin
- OS Grafana is installed on:Windows
- User OS & Browser: Windows
- Grafana plugins: started toolkit plugin
- Others:

**Comment by zuchka** [comment]
https://github.com/grafana/grafana/pull/36598 might fix this

**Comment by realsushi-official** [comment]
The error here is "no python2 found"
More details at https://www.reddit.com/r/node/comments/ey82ov/its_2020_why_is_nodegyp_still_breaking_builds/
and https://stackoverflow.com/questions/63943756/replace-node-sass-with-dart-sass-in-create-react-app-v3-x

**Issue:** when you use `yarn install` with `@grafana/grafana-toolkit: "next"` it installs the V7xx which depends on node-sass (and node-gyp, thus python2)

**Definitive fix** modify package.json with `"@grafana/toolkit": "8.1.6",` (this is the current latest version)
Why it works? just because node-sass seems to be replaced by sass which depends on dart for a cross-compilation purpose (the purpose of node-gyp according to stack-overflow)

((Btw a wrong fix would be to remove yarn.lock, as such it may switch to a fully fledged React project but without the correct eslint config))

**impacted os** Any fresh OS: Arch-linux, manjaro or even W10 if python2 has not been installed for the purpose with according path variable.

**Comment by zuchka** [comment]
@realsushi-official @shashwata27 I believe this is resolved. Building a plugin today using `npx @grafana/toolkit  plugin:create my-plugin` creates a `package.json` using `    "@grafana/toolkit": "latest"`

closing this for now but can reopen if I am wrong
