### ISSUE TITLE
[Cloud Support] Enhance configuration of feature toggles

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#36511]
**What would you like to be added**:
The current feature toggle framework only allows to enable features by passing the feature name in an array/comma-separated string. It would be much easier to manage if toggles were configured using a map. Ex

```ini
[feature_toggles]
AlertingNG = true
feature_b = false
feature_c = false
```

In addition, it would be nice if we could expose what toggles are enabled in the instance as metrics so we can see how many instances and what instance have certain features enabled quickly. 

**Why is this needed**:
It makes it hard to merge multiple sources of configuration into one, for example where you would like to keep a global configuration and override it per cluster or instance.

**Comment by bergquist** [comment]
:+1: The only thing I would like to add is to always keep an list of available feature toggles so they are always included in the metrics regardless if they are available or not :)
