### ISSUE TITLE
Please answer my question

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36524]
![image](https://user-images.githubusercontent.com/76942485/124788636-1e2aeb00-df7c-11eb-8816-f107de11fccf.png)
I'm building a plug-in for granfan 7. How can I add these two buttons? I see that other plug-ins are AngularJS not react. Do you have any documents or demos to refer to?

**Comment by torkelo** [comment]
for the help icon use `.setQueryEditorHelp(LogsCheatSheet)`  in module file (where you call new DataSourcePlugin)

**Comment by CloudWise-Lukemiao** [comment]
i not found .setQueryEditorHelp() in module.ts,i only have setQueryCtrl and setQueryEditor

**Comment by torkelo** [comment]
you will need to use v8 of grafana/ui and grafana/data npm libs, and use Grafana v8  

Of for the pen icon we do not have that feature added to react query editors yet
