### ISSUE TITLE
Can grafana aggregation metrics by some method and display on the main page

### ISSUE THREAD

**Issue by Huangsir** [grafana/grafana#3652]
offer a subpage that display detail metrics of the main page

for example，the main page display metrics by sum with all host，and the subpage display every host's metrics

**Comment by torkelo** [comment]
yes, you can use the table panel and depending your time series data store and it's query feature you could get a sort of overview stats data, it could be very expensive query though. 

You can not easily modify the home dashboard at this point (open issue for that, will be possible in future version)
