### ISSUE TITLE
hi torkelo can you give me a detail code ? 

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36529]
i not found .setQueryEditorHelp() in module.ts,i only have setQueryCtrl and setQueryEditor. or please tell me this  demo url?

![image](https://user-images.githubusercontent.com/76942485/124797006-5df5d080-df84-11eb-801f-9359546d6f3e.png)

**Comment by CloudWise-Lukemiao** [comment]
I don't know how to use it

**Comment by CloudWise-Lukemiao** [comment]
my module.ts code :
import { DataSourcePlugin } from '@grafana/data';
import { DataSource } from './DataSource';
import { ConfigEditor } from './ConfigEditor';
import { QueryEditor } from './QueryEditor';
import { MyQuery, MyDataSourceOptions } from './types';

export const plugin = new DataSourcePlugin<DataSource, MyQuery, MyDataSourceOptions>(DataSource)
  .setConfigEditor(ConfigEditor)
  .setQueryEditor(QueryEditor);

**Comment by CloudWise-Lukemiao** [comment]
thank you

**Comment by torkelo** [comment]
please use community site for questions

**Comment by torkelo** [comment]
you will need to use v8 of grafana/ui and grafana/data npm libs, and use Grafana v8

Of for the pen icon we do not have that feature added to react query editors yet

**Comment by CloudWise-Lukemiao** [comment]
pen icon is not support on grafana 7 or 8?

**Comment by torkelo** [comment]
no
