### ISSUE TITLE
Table panel data links do not redirect to correct dashboard URL

### ISSUE THREAD

**Issue by eamonryan** [grafana/grafana#36532]
**What happened**: When clicking a data link specifically in a table panel that goes to a URL like so:
`./d/6581e46e4e5c7ba40a07646395ef7b23/k8s-resources-pod?var-datasource=$datasource&var-cluster=$cluster&var-namespace=$namespace&var-pod=$__cell`

I am sent to a 404 page despite there being a dashboard under that id.

The reason, turns out to be because the dashboard is actually located at `/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-mixin-compute-resources-pod` and not `/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-resources-pod`.

However, our docs say that the uid should account for the dashboard name being different.

If you refresh on the 404 page with the same URL in the browser address bar, the proper redirect occurs and the page loads, so it seems the redirect path is not occurring when coming from a table panel data link.

This works fine with a regular panel link, it only seems to occur specifically in a data link within a table panel.

Side note: Removing the part of the URL in the data link that contains the "bad" name also allows the link to work e.g. `./d/6581e46e4e5c7ba40a07646395ef7b23/?var-datasource=$datasource&var-cluster=$cluster&var-namespace=$namespace&var-pod=$__cell`

**What you expected to happen**: I expect that `/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-resources-pod` gets redirected to whatever the true URL under that dashboard ID is e.g. `/d/6581e46e4e5c7ba40a07646395ef7b23/k8s-mixin-compute-resources-pod`.

**How to reproduce it (as minimally and precisely as possible)**:

- Have a dashboard with a table panel
- Add a data link that goes to another dashboard ID but with an incorrect name after the ID
- Try to follow the link, see a 404 page
- Refresh the 404 page, see that the URL is redirected to the correct page

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: Prometheus, but it probably doesn't matter which source.
- OS Grafana is installed on: Linux
- User OS & Browser: Ubuntu 18.04, Firefox 89.0.2 (64-bit)
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
was unable to replicate, did you really have a dot (`./`) at the start of your url? Can you try a relative? or fully qualified url?

**Comment by eamonryan** [comment]
> did you really have a dot (./) at the start of your url?

I did but did not write this myself, this is a deployment of the [kubernetes-mixin ](https://github.com/kubernetes-monitoring/kubernetes-mixin) so all the dashboards etc. were pre-defined.

Removing the dot does seem to help, I think, but it's unclear why, since even with the dot, the actual clickable link visible when hovering/copying does not display any dot at all.

**Comment by torkelo** [comment]
> Removing the dot does seem to help, I think, but it's unclear why, since even with the dot, the actual clickable link visible when hovering/copying does not display any dot at all.

Could be because chrome removes it? But anyway a link starting wth `./` is valid path for relative URLs, the dot is usually only used in local files system to mean current directory and that does not make sense in this case
