### ISSUE TITLE
Postgres query returning null values works in v7 but fails in v8

### ISSUE THREAD

**Issue by nabelekt** [grafana/grafana#36538]
A Postgres query that returns null in some columns for some rows fails in both the Graph and Time Series panels on Grafana v 8.0.4.:

<img width="1506" alt="Screen Shot 2021-07-07 at 6 02 13 PM" src="https://user-images.githubusercontent.com/7028403/124844324-35a0ae80-df51-11eb-88a9-f250f7d79e32.png">

pgAdmin showing that the same query works fine there:
<img width="1396" alt="Screen Shot 2021-07-07 at 6 03 38 PM" src="https://user-images.githubusercontent.com/7028403/124844340-3e918000-df51-11eb-8933-f0bab3fd8f30.png">

Null values in some columns for some rows:
<img width="1279" alt="Screen Shot 2021-07-07 at 6 04 03 PM" src="https://user-images.githubusercontent.com/7028403/124844375-579a3100-df51-11eb-8a0d-acc96c4d96e4.png">

<img width="192" alt="Screen Shot 2021-07-07 at 6 04 50 PM" src="https://user-images.githubusercontent.com/7028403/124844374-57019a80-df51-11eb-858f-30b73a896c96.png">

- Grafana 8.0.4 installed on macOS 11.3 via Homebrew running in Safari
- Postgres 13.3 (but set as v12 in the data source options since there is no option for v13)

The same query and panel works in fine in v 7.5.7.

**Comment by torkelo** [comment]
@kylebrandt any ideas to why this happens?

**Comment by marefr** [comment]
There's a temporary workaround for this, cast your int16 columns to integer
