### ISSUE TITLE
Bug: templating variable with data source name equal to default data source shows blank

### ISSUE THREAD

**Issue by liyichao** [grafana/grafana#3653]
Say my default data source is A1, Using API, I change templating.list.datasource to A1. After refreshing, the grafana frontend shows null in the data source field. But using API to get the dashboard, data source filed is correctly updated to A1, so why the frontend shows the null instead of A1?

**Comment by torkelo** [comment]
if its the default data source, panels will refer to it as "null" (so you can change default data source without updating panels), the same is not true for templating, template variables target a specific datasource name, if you change the name, you need to update the template variable

**Comment by liyichao** [comment]
Yes, template variables are updated. But the frontend displays as an empty variable if I have updated the variable via API. Like this:

<img width="887" alt="2016-01-08 08 23 44" src="https://cloud.githubusercontent.com/assets/2576762/12186816/3dfad9f6-b5e1-11e5-940a-04fb1b314520.png">

**Comment by liyichao** [comment]
The variable returned is correct.

<img width="448" alt="2016-01-08 08 26 11" src="https://cloud.githubusercontent.com/assets/2576762/12186868/9a41b4aa-b5e1-11e5-9b93-9e5eb687ab82.png">

**Comment by torkelo** [comment]
the reason is that you do not have a datasource named "influxdb"

**Comment by liyichao** [comment]
No, I have, and it is the default data source.

**Comment by torkelo** [comment]
your right, this is a bug, thanks for reporting this!

**Comment by torkelo** [comment]
Closing this as I think this is fixed
