### ISSUE TITLE
Tempo view short url produces an endless loading trace panel when the url includes logs and traces

### ISSUE THREAD

**Issue by zswanson** [grafana/grafana#36531]
**What happened**:
Using the tempo Explore feature I had a search from logs open and selected a trace. This gives me a side by side view of logs on the left and a trace on the right. Having found an odd trace, I selected the 'copy shortened link' button at the top of grafana. When I paste that url into a new browser tab the logs panel loads but the trace panel is stuck trying to load. The 'refresh' icon in the corner is red and swirling. It will not complete if I leave it alone. However I can hit the 'refresh' button to stop the fetch and then press refresh again and it will load fine. This only seems to happen when the shortened-link is used with the dual-panel-view.
![image](https://user-images.githubusercontent.com/1272954/124808886-80a8ca80-df2d-11eb-95ea-0fc65497158b.png)
 
No console errors but the network trace in my browser shows a 'canceled' transaction for `https://grafana.<mydomain>/api/ds/query` 

**What you expected to happen**:
The trace panel should load immediately

**How to reproduce it (as minimally and precisely as possible)**:
Assuming a grafana stack with loki + tempo and logs to traces configured
1. Visit Explore, select Tempo data source.
2. set query type to 'search' and then enter a logql selector
3. select a trace that appears - it should open to the right. 
4. Click the copy shortened link icon at the top of the page (I tend to click the one thats on the temp panel side)
5. Open a new browser tab or window, paste the url and load the page

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: Tempo/Loki
- OS Grafana is installed on: Docker/AWS-Fargate
- User OS & Browser: Mac OS 11, Chrome

**Comment by zoltanbedi** [comment]
I was not able to reproduce this in latest Grafana. Can you try to upgrade to 8.0.4?

**Comment by ivanahuckova** [comment]
I have experienced similar thing with the test data source where query on the left side hasn't finished. This happened not only when I used short url, but also when I just copy-pasted the url. So I don't think this is related to short url.
