### ISSUE TITLE
"Direct link rendered image" problem

### ISSUE THREAD

**Issue by starchou** [grafana/grafana#3654]
I click the "Direct link rendered image"  ,the result is :
![image](http://7xpuc9.com1.z0.glb.clouddn.com/grafana.png)

i already have install fontconfig 
`yum install -y fontconfig freetype freetype-devel fontconfig-devel`

grafana version : 2.1.6 and 2.6

**Comment by torkelo** [comment]
some versions of centos does not include any fonts at all, maybe need to install a font 
https://github.com/grafana/grafana/issues/3373#issuecomment-161331537
