### ISSUE TITLE
alerting: datasource-min-interval ignored

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#36551]
datasources can specify a "min-interval" value, (called 'scrape interval' in prometheus, 'min time interval' in influxdb etc.), and when running queries from a dashboard or from explore-mode, that value is used (meaning, if the calculated `interval` is smaller than this value, then this value is used)
when using alerting (tested with the new alerting mode), this value is not used.

how to reproduce (influxdb or prometheus):
- influxdb
  - setup an influxdb flux data source, set min-time-interval to "37s"
  - create an alert, observe the query sent to the database, it will have an interval-value of "64ms".
- prometheus
  - setup a prometheus data source, set scrape-interval to "37s"
  - create an alert, observe the query sent to the database, it will have "step" set to "1".

**Comment by gabor** [comment]
as discussed with @marefr and @kylebrandt yesterday, this relates to https://github.com/grafana/grafana/issues/27469#issuecomment-878451517 and probably will have to be solved together with the rest of the "interval problem"

**Comment by marefr** [comment]
Maybe we should close this and keep the relevant discussions in #27469?

**Comment by gabor** [comment]
you're right, closing this one.
