### ISSUE TITLE
No time range for annotations on Time Series panel

### ISSUE THREAD

**Issue by anemyte** [grafana/grafana#36564]
Hi,
I've noticed that Time Series panel does not show time ranges for annotations. On the image below I made two panels (old Graph and new Time Series) using Grafana sample data. They both show the same annotation but... you can see the difference.

**What happened**:
![image](https://user-images.githubusercontent.com/44520858/124937572-2df40f00-e010-11eb-8294-2fdd15ccae47.png)

**What you expected to happen**:
I expected to see the annotation as a region on the new panel as well.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a dashboard with a Time Series and a Graph panels.
2. Create an annotation with both `time` and `timeEnd` as in the [docs](https://grafana.com/docs/grafana/latest/http_api/annotations/#create-annotation)

**Environment**:
- Grafana version: v8.0.3 (cae5c5e46b)
- Data source type & version: Grafana
- OS Grafana is installed on: Debian 10
- User OS & Browser: Debian 10, Chrome 90.0.4430.212
- Grafana plugins: Many but I guess it's irrelevant

I did a bit of Googling but I was unable to find anything relevant. Close it and take my apologies if it is intended behaviour/has been reported already.

**Comment by Elfo404** [comment]
Hi @anemyte, thans for reporting this!

Looping in @grafana/grafana-frontend-platform. Also, I think it's worth mentioning (might be related) that according to https://grafana.com/docs/grafana/latest/dashboards/annotations/#adding-annotations, one should be able to add annotation manually by cmd+click on a panel, but also this doesn't seem to be working.

**Comment by Herr-Sepp** [comment]
Isn´t this fixed with https://github.com/grafana/grafana/pull/3622?
But we have to wait for 8.1

**Comment by anemyte** [comment]
> Isn´t this fixed with #36220?
> But we have to wait for 8.1

Judging by the images there - it has been. I guess I'll wait for 8.1 and see for myself. Thanks!
