### ISSUE TITLE
Allow users to use icons in dashboards

### ISSUE THREAD

**Issue by joernhees** [grafana/grafana#36574]
**What would you like to be added**:
When editing dashboard elements, instead of just text, it would sometimes be nice to also be able to insert common icons (e.g., a CPU icon). It would be awesome if you could expose whatever icons grafana uses itself to the users (don't really care if its font-awesome or unicons).

**Why is this needed**:
Cause it allows us to make nicer dashboards? Also you use icons all over the whole interface of grafana yourself, so why not allow users to also use them?

**Comment by torkelo** [comment]
you can use emojis (just copy them from somewhere and paste them) 

> Cause it allows us to make nicer dashboards? Also you use icons all over the whole interface of grafana yourself, so why not allow users to also use them? 

Any idea how that would work? In text fields? where?

**Comment by joernhees** [comment]
> you can use emojis (just copy them from somewhere and paste them)

yes, we use emojis where possible already, but the standard ones are surprisingly relatively sparse wrt. tech... like CPU, Memory, ...

> Any idea how that would work? In text fields? where?

yupp, in text fields... if the font is loaded maybe this already would work via copying the unicode char
- `` (from https://iconscout.com/unicons/explore/line "processor") or
- `︁` (from https://fontawesome.com/v6.0/icons?d=gallery&p=1&q=processo&s=solid)

Alternative via their common html code
- `<i class="uil uil-processor"></i>`
- `<i class="fa-solid fa-microchip"></i>`

**Comment by jfolz** [comment]
We're pretty constrained on horizontal space in most of our tables and there are no fitting Unicode emoji, so I've resorted to use 🚌 = GPU, 🚗 = CPU, 🚚 = memory. It saves enough space in the table, but it has confused some people and the emoji render different on different platforms.
Rather worryingly even fontawesome and unicons lack most of the icons that I'd want to use, so custom icons are a bit of necessity.

**Comment by torkelo** [comment]
not sure we can support this in any good way, we might add an image option to value mappings / threshold steps in the future. this could potentially also support icons

**Comment by joernhees** [comment]
😢
