### ISSUE TITLE
GoogleCloudMonitoring: GCE Default Service Acct auth is available but displays empty error when not on GCE

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#36578]
**What happened**:
When I am running Grafana _not_ on a GCE VM and I create a GCM data source, I see the option to authenticate using a GCE Default Service Account. 
When I select that option, I see a blank error message

**What you expected to happen**:
The ideal: if I am not running on GCE, then I don't see that auth option at all
Another approach: I am made aware that with with GCE Default Service Account only works on GCE, and I see a descriptive error message if I still try to use it.

**How to reproduce it (as minimally and precisely as possible)**:
![gce-error](https://user-images.githubusercontent.com/3848559/124972438-97135c80-dfe7-11eb-9981-bd8a3d900b54.gif)

**Anything else we need to know?**:
Note: this is noted in the docs, but there is an opportunity to make it clearer in the UI.

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: Google Cloud Monitoring, Grafana 8.0.4 edition
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OS Chrome
- Grafana plugins:
- Others:

**Comment by mjseaman** [comment]
CC @mnako1

**Comment by joshhunt** [comment]
@sunker Does this happen from misconfiguration of Grafana? Or is there an opportunity for better error messaging here?

**Comment by sunker** [comment]
> Or is there an opportunity for better error messaging here?

Definitely an opportunity for better error messages here.

**Comment by edith007** [comment]
Hi @mjseaman! 👋🏻 
is this something I can get to work on? If so I'd like to get to work on it. 🙇🏻

**Comment by mjseaman** [comment]
Sure thing!

**Comment by sunker** [comment]
Hi @edith007! Thanks for reaching out.  

Currently we're working on a major refactoring of the CloudMonitoring data source. Please see [this](https://github.com/grafana/grafana/pull/38650) PR. It's possible that this will solve the problem, but if not I'll ping you in about two weeks.

**Comment by iwysiu** [comment]
Moving to the backlog, as it still returns a generic error.
