### ISSUE TITLE
Render to png not working on windows due to phantomjs missing .exe extension

### ISSUE THREAD

**Issue by sischnei** [grafana/grafana#3657]
With grafana 2.6.0 windows x64 builds (official) I'm unable to use the render to png feature. Grafana logs:

```
2016/01/06 16:18:00 [render.go:40 RenderToPng()] [E] Failed to render to png: exec: "D:\\Tools\\grafana-2.6.0\\vendor\\phantomjs\\phantomjs": file does not exist
2016/01/06 16:18:00 [I] Completed [::1] admin "GET /render/dashboard-solo/db/demo-dashboard HTTP/1.1" 500 Internal Server Error 671 bytes in 4000us
```

If I rename the file 'vendor/phantomjs/phantomjs' to 'vendor/phantomjs/phantomjs.exe' the rendering works flawlessly. I think this is a minor packaging error?

**Comment by smur89** [comment]
This is still an issue for me on the latest master
