### ISSUE TITLE
Alerting: UI filter for Firing should exclude Normal alert instances

### ISSUE THREAD

**Issue by davidmparrott** [grafana/grafana#36581]
The alerting UI filter by state only filters alerting rules. This can be hard to navigate for users with multi-dimensional rules with a large number of matches but only a few that are alerting. The UI filter should exclude `Normal` alert instances when applied

**Comment by davidmparrott** [comment]
First reported here https://github.com/grafana/grafana/issues/36179

**Comment by papagian** [comment]
@davidmparrott Is this duplicate of #36048?

**Comment by davidmparrott** [comment]
Yup! Closing in favor of existing feature request
