### ISSUE TITLE
AzureMonitor: New Logs resource picker displays only first 1000 resources - v8.0.x

### ISSUE THREAD

**Issue by itsjusth** [grafana/grafana#36586]
My non-prod subscriptions (38) contain a few dozen Log Analytics workspaces.  In 7.x, the workspace selector was adequate.  I was able to see all subscriptions and all workspaces.  It was not necessary to see any other (non-Log Analytics) resources.

![image](https://user-images.githubusercontent.com/53532085/125010925-7d990180-e035-11eb-96a0-4ee6e5ef5dd2.png)

In the latest 8.x versions, the resource picker displays ALL resources that the identity has access to.  In non-prod, this is 1953 items.  In the new resource picker, only the first 1000 items are displayed.  This leaves out about half of the resources and makes them unselectable.  The situation is worse in Production where my total resource count is over 7500.  I am rolling back to 7.5.8 until this bug is resolved.

![image](https://user-images.githubusercontent.com/53532085/125011416-69a1cf80-e036-11eb-87b1-ad6946841a21.png)

**Comment by andresmgot** [comment]
I think this will be solved by #35646

Is there a workaround for this to work before Grafana 8.2 @joshhunt ?
