### ISSUE TITLE
Plugin Invalid signature

### ISSUE THREAD

**Issue by dessen-xu** [grafana/grafana#36587]
**What happened**:

All my plugins have been changed to Invalid signature, but I did not do any change.
![image](https://user-images.githubusercontent.com/41524013/125012417-bcae6d80-e09c-11eb-98fd-7f2008376bfe.png)
![image](https://user-images.githubusercontent.com/41524013/125012460-d51e8800-e09c-11eb-9886-9006b33a4edf.png)

**What you expected to happen**:

what I need to do to fix the problem.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.1
- Data source type & version: oepnTSDB
- OS Grafana is installed on: linux
- User OS & Browser: mac chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Can you try updating them?

**Comment by dessen-xu** [comment]
Update Grafana to V8.0 ?

**Comment by dessen-xu** [comment]
You mean that update plugins ?

**Comment by dessen-xu** [comment]
I had tried, not work.

**Comment by dessen-xu** [comment]
Any else way, please

**Comment by Elfo404** [comment]
That's very strange. How did you install your plugins? any server log we can look at?

i tried setting up a 7.5.1 instance with some plugins and could not reproduce the issue.

**Comment by dessen-xu** [comment]
I move /dist that after build folder to grafana /data/plugins

**Comment by dessen-xu** [comment]
Excuse me, How do I run backend test. I want to test my manifest.txt fold.  Fold "manifest_test.go"
