### ISSUE TITLE
Stream metrics fails with 500 HTTP Status error

### ISSUE THREAD

**Issue by edsiper** [grafana/grafana#36583]
**What happened**:

At [Fluent Bit](https://fluentbit.io), since v1.8 we are handling native metrics. Sending the metrics through our InfluxDB connector works with Influx Cloud, we can see the metrics. Now when sending the same metrics to Grafana to try out the Stream Metrics (like Telegraf) but we receive an HTTP 500 Status error.

After digging, we found a minimal influxdb line protocol payload that doesn't work and helps to reproduce the issue:

[failed_payload.txt](https://github.com/grafana/grafana/files/6787653/failed_payload.txt)

**What you expected to happen**:

Get metrics ingested.

**How to reproduce it (as minimally and precisely as possible)**:

Yes, file is attached above. You can reproduce with curl by doing:

```
curl -H "Authorization: Bearer redacted.." -k \
       https://something.grafana.net/api/live/push/custom_stream_id \
       --data-binary @failed_payload.txt -vvv
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: Fluent bIt Node Exporter + InfluxDB output 
- OS Grafana is installed on: cloud and local linux
- User OS & Browser: chrome
- Grafana plugins: default
- Others:

**Comment by FZambia** [comment]
@edsiper hello! Thanks for opening an issue.

Is this data comes from Telegraf? If yes - can you also provide a Telegraf configuration that exposes data in this format?

I am asking because at the moment we assume that the same metric has identical field set. This assumption does not work for this input that's why after conversion we are getting a data frame with not-aligned column length and an error (will add more detailed logging since at the moment actual error not visible in logs).

**Comment by edsiper** [comment]
@FZambia 

Hi, the data is coming from Fluent Bit in Influx format over HTTP to Grafana. 

As a bit of context, in Fluent Bit, we are replicating a subset of metrics that exists today on Prometheus Node Exporter, so now Fluent Bit has a plugin that collects the exact same metrics and we have the ability to convert them to Prometheus Exporter or Influx format. As a reference I am attaching the full Prometheus and Influx payloads:

- [influx.txt](https://github.com/grafana/grafana/files/6792217/influx.txt)
- [prometheus.txt](https://github.com/grafana/grafana/files/6792219/prometheus.txt)

Ideally, we want to be a first-class citizen-supported Metrics collector for Grafana streaming. Besides allowing our users to ingest into Influx Cloud, they would also be able to choose Grafana.

**Comment by FZambia** [comment]
@edsiper thanks, now clear. As I mentioned we were not prepared for input like this. Will try adapting converter code to handle that. So the frame sent to a client will look like this for a `failed_payload.txt`:

```
+------------------+-----------------------------------------+---------------------+---------------------------+
| Name: labels     | Name: time                              | Name: seconds_total | Name: guest_seconds_total |
| Labels:          | Labels:                                 | Labels:             | Labels:                   |
| Type: []string   | Type: []time.Time                       | Type: []*float64    | Type: []*float64          |
+------------------+-----------------------------------------+---------------------+---------------------------+
| cpu=7, mode=user | 2021-07-09 01:25:51.607273176 +0300 MSK | 6410.48             | null                      |
| cpu=0, mode=user | 2021-07-09 01:25:51.607273176 +0300 MSK | null                | 0                         |
| cpu=0, mode=nice | 2021-07-09 01:25:51.607273176 +0300 MSK | null                | 0                         |
| cpu=1, mode=user | 2021-07-09 01:25:51.607273176 +0300 MSK | null                | 0                         |
+------------------+-----------------------------------------+---------------------+---------------------------+
```

Need to re-check how frontend will behave in this case.

We also discussed internally a possible approach for the future to avoid having lot of nulls in resulting frames for Prometheus-based input.

**Comment by FZambia** [comment]
The fix should be a part of v8.0.6 soon

**Comment by FZambia** [comment]
@edsiper hello, v8.0.6 has been released, please check it out.

**Comment by edsiper** [comment]
everything is working now!

![fixed](https://user-images.githubusercontent.com/369718/125980821-ba1d65a2-86fb-44b8-a4ca-02f022855c82.png)

**Comment by edsiper** [comment]
thank you!!
