### ISSUE TITLE
natel-influx-admin-panel ：plugins error

### ISSUE THREAD

**Issue by EnergeticWong** [grafana/grafana#36592]
**What happened**:插件异常无法使用

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.0.4
- Data source type & version:influxdb
- OS Grafana is installed on:rhel7
- User OS & Browser:RHEL7 chrome
- Grafana plugins:natel-influx-admin-panel @ 0.0.6
- Others:

**Comment by torkelo** [comment]
Please raise issues related to external plugins on the community site or the respective plugin's github repository

**Comment by EnergeticWong** [comment]
> Please raise issues related to external plugins on the community site or the respective plugin's github repository

ok , thanks.
