### ISSUE TITLE
Alert via MS Teams Webhook does not attach image

### ISSUE THREAD

**Issue by voigtste** [grafana/grafana#36593]
**What happened**:

Configured teams webhook and set up alert. Alert comes through but not with Panel image.
Deployment has activated image renderer (k8s deployment via helm chart) and image renderer works (e.g. share panel and download png).
Side note: when clicking on "test" in the channel setup, a sample image is attached to the message. But for some reason, the real alert messages do not have it.

Is there some "trick" or some undocumented template variable which we should name in the alert message?

**What you expected to happen**:

Image of alert triggering panel is attached (or at leas linked) to alert message.

**How to reproduce it (as minimally and precisely as possible)**:

1. Set up MS Teams webhook
2. Set up notificication channel
3. set up alert
4. "Provoke" alert

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Promehteus
- OS Grafana is installed on: GKE / K8S
- User OS & Browser: Chrome
- Grafana plugins:-
- Others:

**Comment by papagian** [comment]
Thanks for reporting this.
Are you using the legacy alerting or Grafana 8 Alerts opt-in feature? In the latter there is no yet image support.
In the legacy MS Teams notification channel you need to have configured [an external image storage provider](https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/#external-image-store).
Have you defined such [an external storage](https://grafana.com/docs/grafana/latest/administration/configuration/#external_image_storage)?

**Comment by voigtste** [comment]
Hi Sofia, thanks for clarification.
No, I did not configure external image storage provider. Will take a look at this.
