### ISSUE TITLE
Auth: Setting to have withCredentials enabled by default for ALL XHR

### ISSUE THREAD

**Issue by sgarg7** [grafana/grafana#3659]
We set cookies to authenticate users to Grafana. The issue is after the cookie expires and the page is idle, making an XHR request fails with 401. Grafana does not set withCredentials for XHR by default.
Please allow configuring $httpProvider.defaults.withCredentials or set it to true by default.

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/12172870/d39b599c-b553-11e5-8319-5dc7c20aeeba.png)

new option in 2.6

**Comment by sgarg7** [comment]
I meant for requests to Grafana itself, not datasources.

**Comment by torkelo** [comment]
Not sure what your talking about them, set cookies? where? where do you set cookies? you must be using some unsupported auth scheme? 

Use Auth proxy feature if you need custom auth before grafana

**Comment by sgarg7** [comment]
Forget the cookie part. We do use Auth proxy and custom auth . The issue is that XHR requests(to say, fetch a partial template on click) don't work with our custom auth (on a different sub-domain) since the requests don't have "withCredentials" set to true.

**Comment by torkelo** [comment]
what requests are sent to a different domain by grafana? should this not be handled by your auth proxy?

**Comment by sgarg7** [comment]
Valid question. The reverse proxy that Grafana sits behind does not perform the actual authentication (kerberos). It reads a cookie that is set by the authentication proxy on another host which can do Kerberos after requesting the browser for credentials(and get the username). The reverse proxy redirects to this auth proxy if the cookie isn't set. That should answer your first question.

We didn't keep the two parts together since there wasn't a good kerberos library with the reverse proxy we are using.

This cookie expires every 10 minutes, and then the reverse proxy redirects to the auth proxy but it doesn't work for XHR since withCredentials isn't set.

The change I'm looking for is lines 10,11,12 in https://gist.github.com/sgarg7/5c17b7ae2a8763c075fd

**Comment by torkelo** [comment]
that change has some security implications

**Comment by sgarg7** [comment]
Could you make it opt-in based on a configuration setting? I'm not familiar enough with the code to make that change.

**Comment by torkelo** [comment]
possibly, if it is a very common problem.

**Comment by sgarg7** [comment]
Can we keep this issue open?

**Comment by torkelo** [comment]
please try to fix this issue in your auth proxy setup. As a new config option in grafana to only solve your issue is not likely.

**Comment by sgarg7** [comment]
Did you mean to reopen the issue too? It would get better discussion that way.

**Comment by torkelo** [comment]
yes, I meant to do that :)  

So far everyone who has used the auth proxy feature has been fine without it. This different different subhost auth sounds strange.

**Comment by sgarg7** [comment]
I don't need this change anymore, it can be closed.
