### ISSUE TITLE
Explore: make it more clear which label corresponds to which switch

### ISSUE THREAD

**Issue by olbo98** [grafana/grafana#36608]
**What would you like to be added**:
In the logs options panel it would be nice if the space between the labels and the switches was smaller to clearly indicate which label belongs to the corresponding switch. Or maybe add a divider to split them into individual groups.
<img width="1342" alt="Screenshot 2021-07-09 at 14 32 14" src="https://user-images.githubusercontent.com/16028771/125078750-25a8dc00-e0c3-11eb-8f16-b1c2769cda0b.png">

**Why is this needed**:
Sometimes it's quite difficult to know which switch to click in order to set a certain option and adding some change to the panel ui to make this more clear would remove some of the confusion

**Comment by zoltanbedi** [comment]
We should check whether it makes sense to make the gap between select and label or between the switches smaller.
