### ISSUE TITLE
Bug: Variable Dropdown in snapshots gets stuck

### ISSUE THREAD

**Issue by henridf** [grafana/grafana#3660]
When I load a snapshot of a dashboard that contained a variable dropdown, it renders like this:

![image](https://cloud.githubusercontent.com/assets/1022041/12158786/22638ab2-b492-11e5-8232-4892e8984af2.png)

However if I now click on the down arrow in one either of the dropdowns, I get an empty dropdown box:

![image](https://cloud.githubusercontent.com/assets/1022041/12158811/52606956-b492-11e5-852e-9227840611c4.png)

The only way that I found to make the box go away is to enter some value in the input field.

It seems like the dropdown should be disabled altogether when viewed in a snapshot.

**Comment by torkelo** [comment]
variables values are not included in snapshots, only visible data

**Comment by henridf** [comment]
> variables values are not included in snapshots, only visible data

Understood. But are you saying that the present behavior (dropdown with no values that doesn't go away) is as intended ?

**Comment by torkelo** [comment]
a sorry, missed the fact that the dropdown does not go away

**Comment by utkarshcmu** [comment]
@torkelo  The desired feature details were not clear in this PR, so I hided the variables menu. So, the desired functionality is to have the variable's menu with the variables selected when snapshot was taken?

**Comment by torkelo** [comment]
only the current value, the bug that it does not go away (the dropdown)
