### ISSUE TITLE
change unit to km it over 1000km change to 1Mm

### ISSUE THREAD

**Issue by syswombat** [grafana/grafana#36626]
Hello

Changed the Distanz Unit to Km
if it is below 1000 it write 960Km
if it is above it write 1.123Mm (like MegaMeter ;-) )

![grafan-7KmProblem](https://user-images.githubusercontent.com/3279451/125187424-e2b84700-e22f-11eb-8dcc-c87b8c0badb4.PNG)

i use Grafana 8.0.5
have a nice day
vinc

**Comment by torkelo** [comment]
well it is correct, 1230 kilo meters is 1.123 million meters.  (1.123 SI miles). 

If you do not want it to scale like this and just want the suffix, use `suffix: km`  in the unit

**Comment by syswombat** [comment]
@torkelo 
sorry but as i know it is not a Standart to use Mm (Megameter) so if it is selected to be Km in the Unit it should stay like that!
if the Unit is Km and i have 900meter so it should show 0.9Km. if is above 1000Km so it still Km i would like to show - thats the reason i select it. (thats i belive it is a bug)

**Comment by kvalev** [comment]
Actually I think its a bug, it just does not make sense to revert back to using "meters" as unit when the value exceeds 1000km. You can see in the screenshot below that the chart label jumps from meters, to kilometers and back to meters, which I dont think looks good and most likely its not intended.
<img width="75" alt="Screenshot 2022-10-25 at 10 26 56" src="https://user-images.githubusercontent.com/270592/197711089-f18bdce7-e363-4a9b-b971-e0236d96bfb7.png">
