### ISSUE TITLE
[State timeline] - State value not changing overtime

### ISSUE THREAD

**Issue by Leletir** [grafana/grafana#36633]
Hi,

First of all, I'm not sure if it's an issue or me who just misunderstood how to use the State timeline visualization.

**What I'm trying to achieve:**

I'm trying to monitor the status of one of my systemd units.
I'm using Metricbeat and Elasticsearch for the logs collection and storage.
I use the state timeline visualization.

**What happened**:
When I try to create a state timeline which should show when the service is up/down (for simplification), it only show the value of the first document.

<img width="1254" alt="Screenshot 2021-07-11 at 20 47 38" src="https://user-images.githubusercontent.com/16922595/125206782-3e62ee80-e289-11eb-8bb9-270f800e87ca.png">

<img width="1253" alt="Screenshot 2021-07-11 at 20 48 04" src="https://user-images.githubusercontent.com/16922595/125206793-4d49a100-e289-11eb-85a4-7abda5e2eece.png">

As you can see, the visualization should show that the state as changed  from 'active' to 'failed', and from 'running' to 'failed'.

It's maybe due to the request have done:

- I'm using a "Raw data" query:

<img width="1248" alt="Screenshot 2021-07-11 at 20 50 41" src="https://user-images.githubusercontent.com/16922595/125206876-aadded80-e289-11eb-98f4-a4f5a957c4f7.png">

- And I'm adding a transformation on the results (just to reduce the number of fields available):

<img width="1245" alt="Screenshot 2021-07-11 at 20 51 48" src="https://user-images.githubusercontent.com/16922595/125206908-d19c2400-e289-11eb-950b-39cd2ad78fb9.png">

I've seen that the "size" of documents I'm using to query elasticsearch has an influence of the results, but I failed to figure out how grafana used this number to display the graph.

I've maybe missed a part of the documentation, if so don't hesitate to send me the links (RTFM is more than welcome ;) )

So if you have an idea of what is going on, do not hesitate to answer. I'm a beginner with Grafana, I could have missed something obvious for others.

Have a good day.

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: Elasticsearch
- OS Grafana is installed on: RHEL 8.4
- User OS & Browser: Firefox
- Grafana plugins: Redis/JSON

**Comment by leeoniya** [comment]
if your states are string values, you should add value mappings for the colors you want, though we probably should assign random colors somehow if this is missing.

![image](https://user-images.githubusercontent.com/43234/125207829-50766a00-e254-11eb-8bdb-b045a51c77d7.png)

**Comment by Leletir** [comment]
Hi,

Sorry i completed forgot to add the value mappings, here they are:
<img width="956" alt="Screenshot 2021-07-11 at 23 40 55" src="https://user-images.githubusercontent.com/16922595/125210666-93aafa00-e2a1-11eb-8015-d783008b5ea1.png">

**Comment by leeoniya** [comment]
and did that fix anything?

**Comment by Leletir** [comment]
Hello @leeoniya,

No I applied these value mappings before opening the issue.

**Comment by baur** [comment]
Hello @Leletir 
Try order by time ...

**Comment by Leletir** [comment]
Hello @baur,

Thank you for your answer, in sort it by time thanks to transformation.

<img width="1239" alt="Screenshot 2021-07-13 at 10 38 15" src="https://user-images.githubusercontent.com/16922595/125420043-8c771acf-ecb1-4d5f-ad5d-edee48b15676.png">

And now I have this result:

<img width="1208" alt="Screenshot 2021-07-13 at 10 39 29" src="https://user-images.githubusercontent.com/16922595/125420195-faeb2e4f-f3c5-488c-b47f-f743e9fb17a5.png">

Thank you @leeoniya and @baur for your help.

Have a good day.
