### ISSUE TITLE
Error message not displayed

### ISSUE THREAD

**Issue by camsellem** [grafana/grafana#36636]
**What happened**:

Creating a new Microsft SQL Server data source. If credentials are wrong the UI only displays the "400" generic error code. There is also no error message in the Grafana server log (DEBUG level activated). The only way to find a comprehensive error message is to open the browser dev panel (see screenshot)

**What you expected to happen**:

See a comprehensive error message

**How to reproduce it (as minimally and precisely as possible)**:

- Create a MSSQL data source
- Generate an error (wrong credentials)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: MSSQL
- OS Grafana is installed on: officiel docker image
- User OS & Browser: MacOS / Brave
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/3879044/125222073-a9a1d480-e30c-11eb-816f-b218a3e84cd2.png)

**Comment by Elfo404** [comment]
@ifrost is this fixed by https://github.com/grafana/grafana/pull/35120?

**Comment by ifrost** [comment]
> @ifrost is this fixed by #35120?

@Elfo404 - Yes 👍

**Comment by Elfo404** [comment]
Cool! closing this then, the fix will be available in 8.1 🚀
