### ISSUE TITLE
NG Alert: Recurring Silences Feature Request

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#36637]
**What would you like to be added**:
The ability to have silences repeat at a scheduled interval. 

Eg. the ability to have a silence scheduled for every Monday from midnight to 1am.  

**Why is this needed**:
We have machines and infrastructure that go through an automated reboot and/or patch/reboot cycle and we'd like to silence alerts about these systems when they reboot.  They preform a reboot and or update/reboot once a week for example and we'd like to not have to manually configure a silence for each time; instead having a silence that allows for a recurring frequency.  

Edit: I stumbled across this being discussed a bit in issue #5856 not sure if this is redundant enough for a close due to that issue being pretty broad and also ~ 5 years old.

**Comment by kylebrandt** [comment]
(@gotjosh assigned this to you since I think this is "Muting Timing" which I believe you are looking into)

**Comment by gotjosh** [comment]
Thanks @kylebrandt is this exactly it.

**Comment by gotjosh** [comment]
Hey everyone!

Apologies it took us this long to get a response on such issues, for a while now Grafan has had a dedicated Alerting team to expedite such features. 

Silencing is now a core feature of Unified Alerting and pausing all the alerts of a rule is possible via https://grafana.com/docs/grafana/latest/alerting/unified-alerting/silences/

Also, silencing for a period of time is possible via https://grafana.com/docs/grafana/next/alerting/unified-alerting/notifications/mute-timings/

Let us know if there's anything else we're missing as part of a feature request for Alerting within Grafana's Discussions system.
