### ISSUE TITLE
Building Server from source and running fails due to missing data/plugin directory

### ISSUE THREAD

**Issue by seizadi** [grafana/grafana#3663]
I am running Grafana from GitHub on Mac got error for data/plugins not being present. I manually created the directory and this fixed the problem, not sure if this is known issue with building from source.
-Soheil

```bash
sc-l-seizadi:grafana seizadi$ ./bin/grafana-server 
2016/01/06 20:53:55 [I] Starting Grafana
....
2016/01/06 20:53:55 [W] Failed to scan dir "data/plugins" error: lstat data/plugins: no such file or directory

sc-l-seizadi:grafana seizadi$ pwd
/Users/seizadi/grafana/src/github.com/grafana/grafana

sc-l-seizadi:grafana seizadi$ mkdir data/plugins

sc-l-seizadi:grafana seizadi$ ./bin/grafana-server 
2016/01/06 21:26:58 [I] Starting Grafana
2016/01/06 21:26:58 [I] Version: 3.0.0-pre1, Commit: v2.6.0+188-g9343b03, Build date: 2016-01-06
.....
  plugins: data/plugins

2016/01/06 21:26:58 [I] Database: sqlite3
2016/01/06 21:26:58 [I] Migrator: Starting DB migration
2016/01/06 21:26:58 [I] Listen: http://0.0.0.0:3000
```

**Comment by bergquist** [comment]
That's just a warning. Did grafana not start at all or did you abort once you saw the message? I will improve the logging so it cause less confusion :)

**Comment by seizadi** [comment]
No problem, this is my first time running Grafana, so when I saw the
warning I was not sure if I had done something wrong or it was expected
behavior. Thanks for fixing the warning.
-Soheil
