### ISSUE TITLE
Expressions to select a series, from queries returning multiple series [Server Side Expressions]

### ISSUE THREAD

**Issue by MikeLin2018** [grafana/grafana#36640]
**What would you like to be added**:
Background: If a query returns multiple series, the threshold check (from expressions for alerts) will be evaluated for each series. There is no mechanism to only select a subset of series for expression evaluation.

Want: Expressions be able to select a subset of series from queries returning multiple series. Because only wide format is supported for alerting query graphs, name and label matcher is preferred. 

Example: Classic condition
![image](https://user-images.githubusercontent.com/39137700/125236981-c3ee9a80-e299-11eb-804a-8ba64c9a7c6b.png)

Example: Math
![image](https://user-images.githubusercontent.com/39137700/125237139-0f08ad80-e29a-11eb-8fbf-73778d848c29.png)

Goal: Currently merging two queries (2 individual series) into a single series is achievable through expressions like `$A+$B`. The goal is to support the reverse direction - split a single query returning multiple series into individual series.

**Why is this needed**:
My need: Different alerting threshold for different series of a single Query through Grafana 8.0.x alerting expression.
General need: Enable "SQL-like query returning multiple series" to split into individual series, and then process each series through its own math expression pipeline. 

**Alternatives?**:
There could be alternatives to support this use case, but with shortcoming: 

Alternative 1: Use multiple queries and one expression for each query.
Why not alternative 1: Not DRY nor efficient. Same query conditions will be repeated multiple times. Query update will be expensive. For BigData applications, multiple complex queries against data warehouse (e.g. Google BigQuery Plugin for Grafana) could be inefficient.

**Comment by kylebrandt** [comment]
I can think of two general approaches to this:
 - Selectors: Add selectors for series (and maybe labels) to operations (as implied in the screenshot, something like `$A[selector Expression]`) and similar via UX for tings like reduce
 - New Operation(s): Add a new SSE operation(s) like select / filter that produces new variables (RefIDs) with the filtered content.

I am not sure which one would generally make for a better UX. Selectors would make for a more compact UI, but might add usage complication to cases where they are not used. Also due to the design of what gets returned from SSE, the filtering / data from the return wouldn't be visualized as an independent step.

In terms of technical implementation, the new operation(s) would be easier to implement with SSE as it currently is. However, since filtering stages will produce data copies in this form this will also result in more resource usage.

**Comment by MikeLin2018** [comment]
Considering UX complexity, state visualization (after filtering), and resource usage, another potential approach is to **add filtering to Math Operation as a math operator**. The result would be similar to the second approach (New Operation).
- UX complexity: For other operations that don't have a textarea (e.g. Classic condition, Reduce, Resample), they don't need to support series filtering. At the beginning, other operations could potentially use series filtering via a chain of expressions through Math Operation. If we do see adoption, we might add this in the future.  
- State visualization vs. resource usage: If state visualization is needed, user could make this operation a standalone RefID in math operation (similar to a new operation). If resource usage is needed, user could still combine "series filtering" with other math operation. 

Noted this approach might blur the boundary of Math Operation to become less "Math".

**Comment by kylebrandt** [comment]
> add filtering to Math Operation as a math operator

That would be possible, but is actually the more difficult to design / implement correctly. By doing it with the math expressions it becomes part of the text lexer and parser. I do get your point though, that adding this to Math would allow math operation to be to be Math and/or Filter.

The tricky part with math syntax is that it is very difficult to change in the future. For example if we get something wrong with the syntax, I migration that reads text and rewrites it is very tricky to pull off.

With an operation, the fields are all delimited, so migrations are more feasible. There is also always the option to create a new operation and make it available and deprecate the old one, which is more difficult with syntax.

Making it an operation also doesn't preclude implementing the selector option in the future (with the exception of ending up with two ways to do the same thing).

Lastly, if the filtering (or whatever it is called) operation doesn't actually modify the contents of data fields, but what fields appear, this operation could not copy frame data and instead the new frame can reference the fields of the hold frame to avoid the memory overhead.
