### ISSUE TITLE
The datasource does not support alerting queries

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36641]
I am writing my own database plug-in. When I click alert, I will be prompted the datasource does not support alerting queries. How to add alert。
![image](https://user-images.githubusercontent.com/76942485/125242057-d5c65100-e31e-11eb-8c94-161dc2b27f7a.png)

**Comment by torkelo** [comment]
It needs to have a backend implementation, and needs to have alerts: true in plugin.json

**Comment by CloudWise-Lukemiao** [comment]
backend implementation is grafana server beckend ?
