### ISSUE TITLE
Legend is not showing anymore when printing dashboard to PDF

### ISSUE THREAD

**Issue by mpetitjean** [grafana/grafana#36656]
**What happened**:

When using the "Print to PDF" option of any browser, legend is not rendered properly when upgrading from Grafana **v7.3.7** to **v8.0.4**. The legend is not showing the colored lines, as shown below.

![image](https://user-images.githubusercontent.com/15037388/125265064-bfab9700-e304-11eb-9fd3-42a456de4387.png)

**What you expected to happen**:

Expecting the legend to be rendered in PDF similarly as in the web dashboard (it was the case in v7.3.7)

**How to reproduce it (as minimally and precisely as possible)**:

Create a dashboard with a Time Series panel. Use any browser to print the page to PDF.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.4
- Data source type & version: MariaDB
- OS Grafana is installed on: CentOS
- User OS & Browser: Windows 10, tried with Brave, Chromium and Firefox
- Grafana plugins: /
- Others: /

**Comment by natellium** [comment]
I was able to reproduce it here https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 . After checking previous versions seems this might have been introduced in 7.4.0

**Comment by mpetitjean** [comment]
I can confirm the issue was introduced in 7.4.0 - rendering fine until 7.3.10

**Comment by mpetitjean** [comment]
I personally have been stuck on 7.3.10 because of this, I have not been able to find a workaround

**Comment by mpetitjean** [comment]
This issue seems to be categorized in a deprecated project sheet. Is there any plan to work on it ? Thanks.

**Comment by joshhunt** [comment]
Does checking "Background Graphics" resolve the issue appropriately?

![1579_2022-04-08-10-33_chrome](https://user-images.githubusercontent.com/46142/162408850-736bfb1b-39cb-43c1-89a4-f493bebd18bb.png)

I'm not sure printing to PDF is something that we explicitly support, especially when we have the [Image Renderer plugin](https://grafana.com/grafana/plugins/grafana-image-renderer/), and [Reporting in Grafana Enterprise](https://grafana.com/docs/grafana/latest/enterprise/reporting/). If there's quick fixes we can make to PDF printing we're happy to do it.

**Comment by mpetitjean** [comment]
If anyone stumbles upon this issue, I ended up working around it by performing a lossless screenshot via a headless browser using Puppeteer, then converting it to PDF. It does the trick.

**Comment by n-benchoubane** [comment]
> 

I've the same issue running a headless browser using Puppeteer. Can you elaborate?

**Comment by mpetitjean** [comment]
I threw my solution on a little [blogpost](https://mpetitjean.github.io/grafana/2022/05/30/grafana-to-pdf.html) which will hopefully help anyone with the same issue.

**Comment by n-benchoubane** [comment]
> Thank you for the reply. I ended up using [this](https://github.com/sindresorhus/capture-website). It works well execpt for the dark mode which can't be overriden from generating snapshots :/

**Comment by henjoe** [comment]
> I threw my solution on a little [blogpost](https://mpetitjean.github.io/grafana/2022/05/30/grafana-to-pdf.html) which will hopefully help anyone with the same issue.

Link is broken. 
It's 2024 and I use V9.0.+ and still the issue is there. Anyone solve it? Thanks.

**Comment by odoucet** [comment]
Link can be visible on archive here : https://web.archive.org/web/20230219205134/https://petitjean.cc/grafana/2022/05/30/grafana-to-pdf.html
You can also take a look at project https://github.com/wiremind/grafana-pdf-exporter
