### ISSUE TITLE
hi torkelo ，Can you give me some advice。

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36658]
I am writing my own database plug-in. When I click alert, I will be prompted the datasource does not support alerting queries. How to add alert。
![image](https://user-images.githubusercontent.com/76942485/125278450-58620700-e345-11eb-9917-42f58987253a.png)

I want to know This backend implementation is grafana server or database side。

**Comment by torkelo** [comment]
https://grafana.com/tutorials/build-a-data-source-backend-plugin/

**Comment by axelavargas** [comment]
Hey @CloudWise-Lukemiao 😄, a friendly reminder on how to report issues in the Grafana GitHub project, we have a set of templates to create issues, and we encourage our community members to follow them, these templates help the community and the team to keep a clear overview of the current bugs and feature requests.

If you have questions related to how to use Grafana, you can always post them in the community forum https://community.grafana.com/ , as well you can take a look at the documentation https://grafana.com/docs/


![Screenshot from 2021-07-12 13-55-58](https://user-images.githubusercontent.com/239999/125285188-b0374880-e31a-11eb-9a20-5f5c3f00e342.png)
