### ISSUE TITLE
building from source fpm error

### ISSUE THREAD

**Issue by sharon77242** [grafana/grafana#3666]
hello i try to build from package on version 2.6 on debian 6 32 os and when im trying to run optimized build:
go run build.go build package

i get this error: /usr/lib/ruby/1.8/find.rb:39:in `find': no block given (LocalJumpError)
	from /usr/lib/ruby/1.8/find.rb:38:in `catch'
	from /usr/lib/ruby/1.8/find.rb:38:in `find'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:671:in `add_path'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:679:in `write_conffiles'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:677:in `each'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:677:in `write_conffiles'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:590:in `write_control_tarball'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/package/deb.rb:389:in `output'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:475:in `execute'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:67:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/lib/fpm/command.rb:535:in `run'
	from /usr/lib/ruby/gems/1.8/gems/clamp-0.6.5/lib/clamp/command.rb:132:in `run'
	from /usr/lib/ruby/gems/1.8/gems/fpm-1.4.0/bin/fpm:8
	from /usr/bin/fpm:23:in `load'
	from /usr/bin/fpm:23

what am i doing wrong?

**Comment by torkelo** [comment]
https://github.com/jordansissel/fpm/issues/923

please use google more :)

**Comment by sharon77242** [comment]
Thank you very much for your help and great work, sorry for bad questions i
succesfully managed to make a package and install it 😀😄

**Comment by torkelo** [comment]
that's great!
