### ISSUE TITLE
Mapping value to text does't work in singlestat panel

### ISSUE THREAD

**Issue by romanponomarev** [grafana/grafana#3667]
Hello.
Mapping value to text does't work in singlestat panel.

Installed APP:
zabbix - 2.4.7
grafana - 2.6
grafana-zabbix - 2.5.1

I created singlestat panel, added query "IT Service" and chose IT service and IT service property - Status...
![pic1](https://cloud.githubusercontent.com/assets/15785694/12149929/b9ce3e4a-b4d0-11e5-802f-cc04c0fb2a34.PNG)

The current status value is 2.
Request:
{
"jsonrpc":"2.0",
"method":"service.getsla",
"params":{
"serviceids":"1",
"intervals":[{"from":1452087912,"to":1452087912}]},
"auth":"172c262a4f9fbdacf5ea8acf7747ccb6",
"id":1
}
Responce:
{"jsonrpc":"2.0","result":{"1":{"status":"2","problems":[],"sla":[{"from":1352452201,"to":1353057001,"sla":100,"okTime":604800,"problemTime":0,"downtimeTime":0}]}},"id":1}

![pic2](https://cloud.githubusercontent.com/assets/15785694/12149950/d4a0d8a4-b4d0-11e5-9e42-96f474407030.PNG)

but while mapping of value to text,  the current status value is 0, for some reason.
![pic3](https://cloud.githubusercontent.com/assets/15785694/12149956/db70faf6-b4d0-11e5-9a94-a817e6cf26b0.PNG)

Could you help me with this problem ?

**Comment by torkelo** [comment]
maybe because zabbix returns zero for the last value?
