### ISSUE TITLE
Missing syntax highlighting and typeahead for several promql functions

### ISSUE THREAD

**Issue by ekpdt** [grafana/grafana#36677]
**What happened**:

Query editor should provide typeahead and syntax highlighting for some PromQL functions but it doesn't

**How to reproduce it (as minimally and precisely as possible)**:

Write some query using sgn/clamp/absent_over_time/group/etc. and observe that there's no typeahead or syntax highlighting
https://play.grafana.org/goto/ducPY0m7k?orgId=1

**Environment**:
- Grafana version: HEAD (`main@36cb3965`)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Mac/Chrome
- Grafana plugins: N/A
- Others:

I'm fairly certain this is just a change to https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/promql.ts and I am happy to submit a patch

**Comment by zoltanbedi** [comment]
Please create a pr if you can fix this. We will appreciate it.
