### ISSUE TITLE
Docs feedback: /alerting/unified-alerting/contact-points.md

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#36681]
In the list of notifiers: "List of notifiers supported by Grafana"
https://grafana.com/docs/grafana/latest/alerting/unified-alerting/contact-points/#list-of-notifiers-supported-by-grafana
the list appears to have items with links but clicking the item goes nowhere.  

Under the old notification documentation: "New notification channel fields"
https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/#new-notification-channel-fields
the list shows items with working links that go to useful guides for each notification channel.

Can we assume the old guide for setting up the channels is exactly the same for the new 8.0 guide?

A customer is asking how to setup a Slack channel and send an image of the graphic causing the alert.  The old section for Slack details how to do this https://grafana.com/docs/grafana/latest/alerting/old-alerting/notifications/#slack
but I'm unsure if this works for the new alerting system. 

If the links from the old doc are still functionally identical, please fix/migrate the new 8.x guide to include the same info.

**Comment by zoltanbedi** [comment]
@grafana/docs-squad

**Comment by yuri-tceretian** [comment]
@armandgrillet I think we should improve that as the adoption of Grafana 8 alerting is growing.

**Comment by GrafanaWriter** [comment]
Thanks for this feedback.

@achatterjee-grafana is working on improving the alerting docs.

**Comment by achatterjee-grafana** [comment]
@yuri-tceretian, can we use the links from legacy dashboard links? Or do you think that each of the notifiers should be tested and we need updated documentation for them? If we do need tp update the docs, who is the SME I can reach out for help? Thank you for any clarification.

**Comment by davidmparrott** [comment]
@achatterjee-grafana the docs for each notifier should be compared to existing behavior. If the old one is still up to date, then no need to change. Basically walk through creating and testing each notifier to document whatever is missing.

**Comment by achatterjee-grafana** [comment]
Hi @armandgrillet, I will need to pair up with a developer. As @davidmparrott suggested, the work involved comparing new behavior to existing. Happy to work with someone, or if someone has the setup to test and would like to open a PR, happy to collaborate. 

Also, removing myself as the assignee.

**Comment by armandgrillet** [comment]
The priority of this is increasing, let's use https://github.com/grafana/grafana/issues/42173 (which I have updated with the info from this issue) to track the work. This should get done before Grafana 9.0 is out, we could use the old links as a quick fix but we should verify that the doc is still accurate and move it to new alerting instead.
