### ISSUE TITLE
could not see redis, adx, static plugin with v8.0.5

### ISSUE THREAD

**Issue by nkol2307** [grafana/grafana#36689]
**What happened**:
after installing new helm chart for Grafana with v8.0.5 we are not able to see adx, statis and redis plugin
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: Azure data explorer 
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: adx, redis, static
- Others:

**Comment by zoltanbedi** [comment]
Can you check your grafana logs if the plugins are listed there? I've just checked the static plugin 1.4.2 with grafana 8.0.5 and I can see it in the plugins list.

**Comment by zoltanbedi** [comment]
This is probably fixed by https://github.com/grafana/grafana/pull/36721
