### ISSUE TITLE
Dashboard JSON differences between export and API import

### ISSUE THREAD

**Issue by betandr** [grafana/grafana#3668]
The exported dashboard JSON from the web app looks like:

```
{
  "id": 1,
  "title": "Dashboard Title",
  ...
```

...however I can't POST this to /api/dashboards/db API endpoint as the format required is:

```
{
  "dashboard": {
    "id": null,
    "title": "Dashboard Title",
    ...
```

Is this intentional? When provisioning a new Grafana instance I have a script which curls JSON dashboard files which I've edited in the web app and then exported the JSON to Grafana to set up the dashboards. However the JSON I export doesn't have the `"dashboard": {...` part.

**Comment by torkelo** [comment]
yes, the write api is different from the read, it needs info on how to handle version diffs (should grafana overwrite newer version etc), this is described in the api docs :)
