### ISSUE TITLE
Make Trace ID query work from the keyboard only

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#36694]
**Steps to reproduce**:
Bring up Explore window; select trace data source; select Query Type: TraceID.
Enter something in Trace ID text field.
Try to initiate search using keyboard.
![image](https://user-images.githubusercontent.com/8125524/125419822-da90ddfc-1ae0-4b59-8951-53a7b7a0331e.png)

**Actual Result**:
Nothing happened on <kbd>Shift</kbd>+<kbd>Enter</kbd>

**Expected Result**
Shift-Enter should trigger a search for consistency with other queries I've used.
![image](https://user-images.githubusercontent.com/8125524/125419869-ba0a81fc-68f3-4c5b-b332-94e4527a8976.png)
(Note <kbd>Ctrl</kbd>+<kbd>Enter</kbd> works there too, and seems more natural for me)

**Relevant WCAG Criteria:**
[2.1.1](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0#keyboard)

**Environment**:
- Grafana version: Grafana v8.1.0-28167pre (b1d576c5da)
- Data source type & version: Tempo; not obvious how to get the version
- User OS & Browser: Windows 10; Chrome
- Others:

**Comment by zoltanbedi** [comment]
We should add a global handler to <kbd>Shift</kbd>+<kbd>Enter</kbd> to run query in explore. Check if it makes sense to have it in dashboard as well.
