### ISSUE TITLE
Href images no longer fully clickable

### ISSUE THREAD

**Issue by BPeters-gits** [grafana/grafana#36695]
Images are no longer fully clickable when using a href in a text visual.

See thread below for details:
https://community.grafana.com/t/href-images-no-longer-fully-clickable/47201

**Comment by zoltanbedi** [comment]
Can you try to upgrade to the latest Grafana? I couldn't reproduce this in 8.0.5.

**Comment by BPeters-gits** [comment]
I've reproduced this on my local grafana server running 8.0.5. This has been occurring for me since 7.5.

When creating a text visual and using the HTML editor to create a href image, only a small bar in the center of the image is actually clickable. When clicking on the top or bottom side of the image, it does not link to anything.

This was not present in 7.3 and earlier for me.

Example:

html:
`<a href="https://google.com"><img src=https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Random_House_Tower_bluesky_jeh.JPG/800px-Random_House_Tower_bluesky_jeh.JPG></a>`

Only the marked part is clickable

![image](https://user-images.githubusercontent.com/87363271/125449954-4634d062-fdaa-4e6a-b7bf-926f05eae5ec.png)

**Comment by zoltanbedi** [comment]
Got it now,  I was able to reproduce it. It works in edit mode but on the dashboard the link is the same that you reported.

**Comment by ashharrison90** [comment]
hi @BPeters-gits 👋 

i think this is correct behaviour. `<a>` elements have `display: inline;` by default. i think the real bug is that it works somehow by magic in edit mode 😂 

to make your use case work, you can override the style in your html. if you set 

```html
<a href="https://google.com" style="display: block;"><img src=https://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Random_House_Tower_bluesky_jeh.JPG/800px-Random_House_Tower_bluesky_jeh.JPG></a>
```

does that solve your use case? if so, i think we can close this as working as intended. 

thanks! 😄

**Comment by BPeters-gits** [comment]
Well that's something. 🤔 

I've just tested this and that's exactly correct. Switching the display to block seems to work as intended. 
I don't ever recall changing the display to block pre-7.5 so that's what got me thinking this was a bug.

Thank you all very much!
