### ISSUE TITLE
Data proxy times out regardless of timeout setting

### ISSUE THREAD

**Issue by wchan-ea** [grafana/grafana#36704]
**What happened**:
When running a query against a Graphite data source that is expected to take long, Grafana times out the request even though the data proxy timeout is set high (360 secs).  Have tried this in both 7.4.5 and 8.0.5 (in 8.0.5, additionally set the timeout in the Graphite data source to have a timeout of 360 secs).  It seems to time out at 30 seconds regardless.

**What you expected to happen**:
Grafana would respect the timeout value configured.

**How to reproduce it (as minimally and precisely as possible)**:
Have a query in a Graphite data source that runs for more then 30 secs
Run that query via Grafana
Notice it times out after 30 secs
Adjust timeout values using GF_DATAPROXY_TIMEOUT to 360 and restart Grafana (using Grafana in a docker).  Notice that in the settings screen it is correctly set to 360.
Run the query above again
Notice it still times out after 30 secs

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.4.5 (also tried in 8.0.5)
- Data source type & version: Graphite 1.1.x
- OS Grafana is installed on: Alpine docker on Google container OS
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: Only the standard one from the official docker image
- Others:

**Comment by zoltanbedi** [comment]
There was a problem around this that got fixed in https://github.com/grafana/grafana/pull/34597

**Comment by ifrost** [comment]
I wasn't able to reproduce it in latest v8.0.6. Timeout setting work as expected, but bear in mind that in case of Graphite timeout can be set up in 4 different places:

1. Grafana frontend datasource settings (see point 1 below)
2. Grafana backend settings (GF_DATAPROXY_TIMEOUT flag) 
3. Graphite: Web server, e.g. ngxinx (see point 2 below)
4. Graphite: WSGI server, e.g. with gunicorn (see point 3 below).

@wchan-ea, could you please ensure that:

1. Timeout is not overridden in data source HTTP settings:

<img width="573" alt="Screen Shot 2021-07-30 at 13 25 25" src="https://user-images.githubusercontent.com/745532/127646449-8eccfb88-1bcd-4542-8164-7309a00b6d39.png">

2. Web server that you're using to server graphite-web has correct timeout settings, for example if you're using nginx make sure you heave these in http/server settings:

```
proxy_read_timeout 120;
proxy_send_timeout 120;
proxy_connect_timeout 120;
send_timeout 120;
```

3. Your WSGI server has correct timeout settings. For example if you're using gunicorn 

`sudo gunicorn wsgi --pythonpath=/opt/graphite/webapp/graphite --bind 127.0.0.1:8989 --graceful-timeout=120 --timeout=120`
