### ISSUE TITLE
Anchor links redirecting to a panel inside the same dashboard

### ISSUE THREAD

**Issue by DamGameHero** [grafana/grafana#36708]
**What would you like to be added**:
The possibility of making anchor links inside a dashboard. These links could redirect us to a panel of the dashboard without having to scroll.
These links were possible in Grafana v7. + because there was an HTML ID attribute for each panel.
Since Grafana v8. +, These IDs have disappeared.

**Why is this needed**:
This improves user experience and it saves time for the user because it is guided by these anchor links.

Example:
A Panel A displays the average/percentile of a metric (Memory utilization for instance). A clickable link on the panel A (panel link) directs to Panel B where more information are available (Memory utilization by process for instance).

**Comment by severicus** [comment]
Hello, is this issue still open ... I'd like to be assigned to it.
