### ISSUE TITLE
BarChart: Add support for stacking series

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#36705]
Current bar char implementation does not allow series stacking, which is a popular and important feature of bar charts. You can read more about bar chart stacking [here](https://chartio.com/learn/charts/stacked-bar-chart-complete-guide/)

Current implementation of bar chart makes it impossible to re-use time series stacking implementation, yet there is an ongoing work in uPlot that will make it possible: https://github.com/leeoniya/uPlot/commit/0f3cbd4ae1442214946d47212a2be02f5e0355d2

The above demo shows a direction of the bar chart code refactor that we need to do in order to get stacking in place. Before starting the actual work on stacking we need to get https://github.com/grafana/grafana/pull/36725 in place as it adjusts BarChart code with the latest changes in uPlot)

Stacking should work in value and percent mode.

**Comment by leeoniya** [comment]
we implemented stacking in https://github.com/grafana/grafana/pull/36725.

this now shares the same stacking code as timeseries, so percent mode will presumably land together with the implementation there.

we still have some tweaks to do in barchart, such as label positioning & contrast.

should we close this issue and open a new one?
