### ISSUE TITLE
about alert give me suggest？

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36706]
![image](https://user-images.githubusercontent.com/76942485/125445410-0e6dd61c-13f6-4ce1-99c4-5e5ba361021a.png)

Is there any version that can add alert to my plugin? At present, I use grafana 8.0.4 enable grafana alerting to click on the above prompt in the test rule times

**Comment by pkolyvas** [comment]
Hi @CloudWise-Lukemiao,

Thanks for reaching out to us, the place to ask questions like this is in our [community forum](https://community.grafana.com/), specifically the [Grafana Development forum](https://community.grafana.com/c/development/30). It's the best place to get support and also help support other developers looking to extend Grafana. 

If you're not sure where you should be asking a question, we recommend starting there first. If you have any other concerns or questions about getting help with Grafana development - please reach out to me directly.
