### ISSUE TITLE
BarChart: Support Prometheus Instant Queries (Labeled Data)

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#36712]
**What would you like to be added**:
Support for Barchart display of "instant" Prometheus queries - in which the identifier of each item in the bar graph is the set of labels and not string columns.

Currently Get:
![image](https://user-images.githubusercontent.com/1692624/125455413-4d90c1d6-1eb0-42f2-bbba-e6ab454f044c.png)

**Why is this needed**:
Popular data source and response format (note SSE shares similar response format for number data - except no time field), so having to use the Labels to Fields transform is cumbersome.

Note: This also relates to finding a numeric data format to support Grafana Managed alerts with SSE https://github.com/grafana/grafana/issues/35663 to enable https://grafana.com/docs/grafana/latest/alerting/unified-alerting/grafana-managed-numeric-rule/ with non-SQL datasources, and more generally this [internal design doc](https://docs.google.com/document/d/1pR9g_LQfjl5nCCIZzjV3pJGVCKfB9MtqNehp6ZJVEMI/edit) on data types

**Comment by torkelo** [comment]
@dprokop  @ryantxu @leeoniya  this one is interesting, something that has hit me a couple of times, the question is should BarChart automatically detect this and support this format or should this require a manual adding of a "fields to rows" Transform  (that we do not have) 

So for clarity the data frame looks like this

Time | SomeFieldNameWithLabels |  SomeFieldNameWithLabels2 | SomeFieldNameWithLabels3
--------| -------------------------------------| ----------------------------------------| -----------------------------------------
21432121 | 10 | 20 | 30

**Comment by ryantxu** [comment]
@torkelo -- what are the actual labels?  Do they exist, or are they already munged into the name?  

@kylebrandt -- is there a way to produce output that looks the same using the testdata source?

**Comment by kylebrandt** [comment]
Was asked about naming, so for this item to give some context, if we were to name with the schema:

<DataType><FrameFormat>

Time Series: 

- TimeSeriesWide ("TimeSeries - WideFrame" "Time Series in Wide Frame format")
- TimeSeriesMany
- TimeSeriesLong

Numeric (Good for bar charts):

- NumericWide (one frame, many numeric fields, labels are key)
- NumericMany (like Wide, but one field per frame, labels again matter)
- NumericLong (labels / dimensions are in string columns, what the bar chart current supports)

**Comment by kylebrandt** [comment]
@ryantxu The structure is many frames, labels is there, looks like:


```
{
    "meta": {
      "preferredVisualisationType": "table"
    },
    "refId": "A",
    "length": 1,
    "name": "up{instance=\"host.docker.internal:3000\", job=\"grafana\"}",
    "fields": [
      {
        "name": "Time",
        "type": "time",
      },
      {
        "name": "Value",
        "type": "number",
        "config": {
          "displayNameFromDS": "up{instance=\"host.docker.internal:3000\", job=\"grafana\"}",
        },
        "labels": {
          "instance": "host.docker.internal:3000",
          "job": "grafana"
        }
      }
    ]
  },
  {
    "meta": {
      "preferredVisualisationType": "table"
    },
    "refId": "A",
    "length": 1,
    "name": "up{instance=\"localhost:9090\", job=\"prometheus\"}",
    "fields": [
      {
        "name": "Time",
        "type": "time",
      },
      {
        "name": "Value",
        "type": "number",
        "config": {
          "displayNameFromDS": "up{instance=\"localhost:9090\", job=\"prometheus\"}",
        },
        "labels": {
          "instance": "localhost:9090",
          "job": "prometheus"
        }
      }
    ]
  },
```
</details>

**Comment by torkelo** [comment]
> @torkelo -- what are the actual labels? Do they exist, or are they already munged into the name?

Does it matter?  it's just a frame with a time field, and a number of number fields. (on string field)

For example just starting with data like this, it would be nice if this form was supported. It is in stat, bar gauge etc 

Stockholm | New York | London
--------| -------------------------------------| ----------------------------------------
1000 | 2000 | 3000

**Comment by kylebrandt** [comment]
> is there a way to produce output that looks the same using the testdata source?

Note quite from what I can tell, this would be close, the output for "B", and is what I would call NumericMany. Except it doesn't have a time field like the prom response does:

![image](https://user-images.githubusercontent.com/1692624/125495672-bdb0bd37-484b-47ca-95ce-ba766e494743.png)

**Comment by mahadi** [comment]
Sorry for sliding in here, but isnt it something similar what would be needed here also:
https://community.grafana.com/t/grafana-8-bar-chart-not-working-with-time-base-labels/50062
Ma datasource is not prometheus but is there any chance that additional types of values (timestamps and numeric values) on for x-axis will be available for the bar chart plugin in the future?

**Comment by gtk-grafana** [comment]
@ryantxu we see you're working on this with https://github.com/grafana/grafana/pull/63901, let us know if there's anything we can do to support you!

**Comment by leeoniya** [comment]
we plan to add this soon, it's needed for migrating from Graph (old) which supported it.

tracking in https://github.com/grafana/grafana/issues/80931
