### ISSUE TITLE
Table panel: row for each matched metric?

### ISSUE THREAD

**Issue by galonsky** [grafana/grafana#3671]
I tried messing around with this, but I'm not sure if it's possible.

If I have a metric like `metric.blah.*.count`, a graph will show all metrics that fit that pattern, and `aliasByNode` will cleanly display those. Is there a way to have a similar thing in the table view, like this?

```
metric.blah.abc.count | 123
metric.blah.xyz.count | 456
```

If it isn't possible, consider this a feature request. Thanks!

**Comment by torkelo** [comment]
yes, http://play.grafana.org/dashboard/db/new-features-in-v2-6?panelId=1&fullscreen&edit

**Comment by galonsky** [comment]
thank you!
