### ISSUE TITLE
can't import dashboard when datasource use influxdb v9

### ISSUE THREAD

**Issue by jcmartins** [grafana/grafana#3672]
![screenshot_20160107_160006](https://cloud.githubusercontent.com/assets/326909/12178309/ef456dc8-b557-11e5-995e-58ff3f2b777e.png)

** I can't see influxdb-v9 **

![screenshot_20160107_155945](https://cloud.githubusercontent.com/assets/326909/12178307/eaff6e4e-b557-11e5-96fb-3d5c2c27260c.png)

**Comment by torkelo** [comment]
since the migration is for dashboards stored in influxdb it only works for influxdb 0.8 as it is the only version that ever supported storing dashboards.
