### ISSUE TITLE
Grafana v8.0.5 does not connect to Influxdb2.0 with Flux or fluxQL

### ISSUE THREAD

**Issue by ralph1966** [grafana/grafana#36728]
FluxQL login attempt results in "bad gateway"
Flux login results in "cant read database"

My Fluxdb works perfectly fine and I am able to write data from a Java App I created using exactly the same details that are failing with the above. Also, many complaints about grafana log in issues online. 

![Flux_fail](https://user-images.githubusercontent.com/15122572/125513712-9adaf687-df76-4eb7-9961-7267f17fcc2c.PNG)
![fluxQL_fail](https://user-images.githubusercontent.com/15122572/125513722-5e2c09f4-6b5c-49de-ab08-985937786b86.PNG)

**Environment**:
- Grafana version: v8.0.5
- Data source type & version: IInfluxDB 2.0.7
- OS Grafana is installed on: Docker/Win10
- User OS & Browser: Win10 & Chrome
- Grafana plugins:
- Others:

**Comment by davidnewhall** [comment]
Do you have the same issue in 8.0.4?

**Comment by ralph1966** [comment]
I haven't tried yet.  I have just checked the Docker network and they are in the same one.

**Comment by davidnewhall** [comment]
I'm having some plugin problems in 8.0.5 that do not exist in 8.0.4. (None of them work at all.) Was hopeful to find someone else with a possibly-similar issue. Thanks for replying!

**Comment by ralph1966** [comment]
Hi.  I just tried v8.0.4 and the same, very frustrating ! I have been trying all day

**Comment by ralph1966** [comment]
From grafana Gui to influx I get this error

Post "http://**test1**:7777/api/v2/query?org=scottbart": dial tcp **172.18.0.2**:7777: connect: connection refused

I have checked Docker Network and both containers are in it and the Host name test1 is converted to IP (above)

        "Containers": {
            "bea30cf5029cf87a7d8ec45d939b321be12b50a7b5fdf0603e2743d9caf41904": {
                "Name": "test1",
                "EndpointID": "f73cdf61d15bbeda40db1e0fb24dcd4089c0d8c61163aac1559fdd42e0cd8dfb",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "d137cb465cf707b27809ac7d75e67ab8edb285f4b15be50650cc0762b7e6c734": {
                "Name": "grafana",
                "EndpointID": "ef995e6c019907e831aac871c77529c7b3fd15b120763c3de34899eec511281f",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            }
        },

**Comment by ralph1966** [comment]
HI.  Finally got it working.  I tried the default port of 8086 and it worked right away for Flux.   I set it up for port 7777, my Java App writes perfectly ok to port 7777.  Moral of the story is maybe just install InfluxDB with default ports !


![working](https://user-images.githubusercontent.com/15122572/125594226-25068217-2e65-4dab-bf7e-ef46f851a78d.PNG)

**Comment by zoltanbedi** [comment]
Awesome! thanks for letting us know. I'm going to close this issue then.
