### ISSUE TITLE
Table: HTML Sanitize table content 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3673]

**Comment by torkelo** [comment]
I might be that the table panel will render table content contains html, this should be html escaped. Maybe sanitized instead to support some html tags, not sure. wonder if kibana table panel supports some html tags.

**Comment by bergquist** [comment]
Ive added a new unescaped content field to logs in ES and the html is indeed rendered. 
I somehow guess that people might be using this for all kind of customization. So just escaping all html might be harsh. This might be a time when I would consider introducing a setting and have it escape html as default.

**Comment by fillest** [comment]
How to disable escaping? I'm using tables to display top-processes-list so I need line breaks but "<br/>" gets escaped now

**Comment by fillest** [comment]
Oops, github has rendered `<br/>`

**Comment by torkelo** [comment]
@fillest currently you can't, see
https://github.com/grafana/grafana/issues/4596

**Comment by badhabitustc** [comment]
+1

**Comment by dlopes7** [comment]
@torkelo Is there anyway we can change that on the source code? Change a style so it is not sanitized? We really need to use this here.
