### ISSUE TITLE
How can I make alert work

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#36739]
![image](https://user-images.githubusercontent.com/76942485/125558781-51bcf771-22d2-45f3-ab29-f86530c4e6bb.png)
I use alert to return image content in my own plugin. How can I make alert work。I sent several messages on the community, but no one answered me，
the community url ：https://community.grafana.com/t/how-can-i-make-alert-work/50429

**Comment by zoltanbedi** [comment]
Thanks, we will answer it in the forum.
