### ISSUE TITLE
{"message":"Unauthorized"} When trying to login using the command line

### ISSUE THREAD

**Issue by maximus2situation** [grafana/grafana#3674]
Hi,

I'm trying to login into Grafana using the command line and the response is: {"message":"Unauthorized"}. I'm using this command: curl http://admin:admin@localhost:3000/api/login/ping . Can someone help me to fix this? I'm using grafana v2.6. Thanks!!!

**Comment by torkelo** [comment]
not sure what your trying to do, you do not login with basic auth you authenticate with it like this:
```
curl http://admin:admin@localhost:3000/api/org
```

**Comment by maximus2situation** [comment]
First thanks for the reply. My goal is to login using the command line. After do it I'm expecting to go through the browser and be automatically log as admin. I Don't want to see the login page when I'm doing http://localhost:3000. Is it possible?
