### ISSUE TITLE
Implement UI for deleting data on supported data sources

### ISSUE THREAD

**Issue by MurzNN** [grafana/grafana#36740]
**What would you like to be added**:
Implement UI for deleting data on supported data sources. And glad to have hiding/filtering on unsupported data sources.

**Why is this needed**:

Very often people make mistakes and adds wrong data to databases, for testing purposes (eg test labels or unusual label values for test Alerting) or by mistakes (typos, wrong configuration). But there is no way now to delete or hide this test data, so they will kept forever, until not cleaned by retention.

So will be very useful to provide some way for delete, or somehow hide (if deletion is not possible) those data from Grafana UI.

**Comment by zoltanbedi** [comment]
You can use https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#filter-data-by-name to remove those data.
