### ISSUE TITLE
Save dashboards, users, settings to ElasticSearch until MS SQL is an option

### ISSUE THREAD

**Issue by galactickaz** [grafana/grafana#3675]
I am installing a multi-server ElasticSearch cluster with Grafana installed on each server using ElasticSearch as a datasource. I do not want to stand up mysql or postgres just so Grafana has the supported backend for storing dashboards, users, settings, etc. since I already have the infrastructure in place for MS SQL. Is it possible to temporarily use ElasticSearch as the backend store for these settings just until MS SQL becomes available as an option?

Thanks!

**Comment by torkelo** [comment]
no :( 

MS SQL support might be worth investing, a PR would be welcomed but it would not be trivial.

**Comment by torkelo** [comment]
reason is simple, there is a TONE of data access code that would have to be written to make it use elasticsearch instead of a SQL based data store.

**Comment by galactickaz** [comment]
Understandable. I appreciate the response. :)
