### ISSUE TITLE
Docs feedback: /permissions/dashboard-folder-permissions.md

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#36755]
This document page for folder-permissions does not explain exactly how Grafana processes the permissions that have been granted. 

I have had one user interpret that when adding something like "TeamX can edit", to the existing "Editors can Edit" and "Views can view" that the user must be a member of "TeamX && Viewer" will only be able to view, and that for them to edit, they must be "TeamX && Edit" When in fact this is not the case. 

It's an uncommon reading of this page, but not one that is explicitly called out. We could either add an example, or add "Each of these permissions is processed independently" or similar help ?

**Comment by zoltanbedi** [comment]
@grafana/docs-squad
