### ISSUE TITLE
Grafana shares links, hides left side, header navigation, especially how to display query criteria

### ISSUE THREAD

**Issue by changzhichen** [grafana/grafana#36779]
**What happened**:
When I embedded links to the Grafana Share Dashboard in other projects, I used the parameter &kiosk to hide the left, header navigation and also the query criteria.

**What you expected to happen**:
After hiding the left and head navigation, the query condition should be displayed, what should I do?

now:
![image](https://user-images.githubusercontent.com/27051861/125755333-8a06a88e-dfe6-4d27-9a21-cb7a9c3896aa.png)

expected:
![image](https://user-images.githubusercontent.com/27051861/125755492-0a590229-3f6e-4f75-b16d-1045c34d5ca2.png)

**Environment**:
- Grafana version: Grafana v8.0.3 
- Data source type & version: prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Linux & Chrome

**Comment by zoltanbedi** [comment]
You should ask this in https://github.com/grafana/grafana-kiosk
