### ISSUE TITLE
Missing colour schemes in Grafana v8.0.2 (5c5d45e19f)

### ISSUE THREAD

**Issue by wyqydsyq** [grafana/grafana#36773]
**What happened**:
Running Grafana as a docker container with standard configuration as per [the docs](https://grafana.com/docs/grafana/latest/installation/docker/), there are only two color schemes available; classic and single:
![image](https://user-images.githubusercontent.com/621277/125717407-390a781b-c93b-4c96-9af0-6d219c8f58a1.png)

**What you expected to happen**:
There are various other schemes available, particularly the "by value" ones, as shown in the docs:
![image](https://user-images.githubusercontent.com/621277/125717449-82ff0eec-5384-4470-aab8-389f90bcebd0.png)

**How to reproduce it (as minimally and precisely as possible)**:
1) Run Grafana via Docker as per https://grafana.com/docs/grafana/latest/installation/docker/
2) Add a panel using data from any datasource
3) Try to use a "by value" color scheme

**Anything else we need to know?**:

- Environment: Docker
- Grafana version: Grafana v8.0.2 (5c5d45e19f)
- Data source type & version: Postgres
- OS Grafana is installed on:  Alpine

**Comment by zoltanbedi** [comment]
Can you please tell us what panel are you using? The TimeSeries panel only supports these two color modes but going to support more in 8.1 see https://github.com/grafana/grafana/pull/35910

**Comment by torkelo** [comment]
Yes, only some panels support color by value schemes in v7.3 - 8.0 

In v8.1 we introduce support for color by value modes in Time series (graph) panel 
https://grafana.com/docs/grafana/next/panels/visualizations/time-series/graph-color-scheme/
