### ISSUE TITLE
unable to see datasource in the explore tab

### ISSUE THREAD

**Issue by navneet1075** [grafana/grafana#36785]
**What happened**:

i added loki as datasource in the grafana datasources and the connection to the datasource was ok . in save and test on ui it shows success. however when i click on explore tab , nothing happens . it does not open up ui to add datasource. 

**What you expected to happen**:

explore tab should open the loki datasource added and we should be able to see results. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.0
- Data source type & version: loki , 2.2.1
- OS Grafana is installed on: linux 
- User OS & Browser: macos and chrome
- Grafana plugins: NA
- Others: NA

**Comment by navneet1075** [comment]
attaching screenshots:
datasource added : 
<img width="925" alt="Screenshot 2021-07-15 at 11 24 48" src="https://user-images.githubusercontent.com/6396611/125764624-1a397f5a-1d3e-45d0-8b00-b0f2cde1e667.png">

datasource connected and tested : 
<img width="1087" alt="Screenshot 2021-07-15 at 11 24 56" src="https://user-images.githubusercontent.com/6396611/125764627-4c31a441-5ea2-42f3-9ff2-4a40d1e357ca.png">

click on explore: 
<img width="371" alt="Screenshot 2021-07-15 at 11 25 08" src="https://user-images.githubusercontent.com/6396611/125764630-48d220fb-1c92-4f82-a03f-80e51297b28f.png">

no result are visible . its blank : 
<img width="883" alt="Screenshot 2021-07-15 at 11 25 16" src="https://user-images.githubusercontent.com/6396611/125764633-fcb1069d-ed51-40ca-93a6-2e3a525694c4.png">

**Comment by zoltanbedi** [comment]
can you please try to hard refresh your browser or try it in another one? It seems like that something stuck in explore that prevent it from opening.

**Comment by navneet1075** [comment]
ok browser issue . closing  . thanks a lot @zoltanbedi saves a lot of time

**Comment by navneet1075** [comment]
<img width="1461" alt="Screenshot 2021-07-15 at 11 31 36" src="https://user-images.githubusercontent.com/6396611/125765414-667c1c06-fd41-47ec-aedc-073d1a4ba760.png">
