### ISSUE TITLE
Panel Inspect: join-by-time not working properly

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#36782]
**What happened**:
I have multiple testdata metrics, and they are not joining in time any more (tested in grafana 7.5.9 and 8.0.5)  as can be seen when inspecting the data:
![image](https://user-images.githubusercontent.com/6523124/125743551-dace309c-9fdd-4ac4-98fb-134898630075.png)
![image](https://user-images.githubusercontent.com/6523124/125743640-126ceafd-9cfa-4e4d-bf1b-ec34281261b2.png)
![image](https://user-images.githubusercontent.com/6523124/125743729-a9e9c157-ccfc-4664-8304-a2937eed7d24.png)
The query looks like this:
![image](https://user-images.githubusercontent.com/6523124/125755281-a90760d6-0706-4564-ac55-0c6743314fec.png)

**What you expected to happen**:
I expect the two testdata metrics to be joinable in time.
The data used to join fine in grafana 7.3.7 and earlier and was successfully used as input for the alexandra-trackmap.
![image](https://user-images.githubusercontent.com/6523124/125755424-cee5f98e-2d94-4241-ab41-3cfd3ca3dcd0.png)
E.g. in grafana 7.1.1, I can show the data joined in time:
![image](https://user-images.githubusercontent.com/6523124/125757971-25e49907-5a4d-4e4b-b4d9-79336912dc80.png)

**How to reproduce it (as minimally and precisely as possible)**:
Here is the JSON for the dashboard with simple graph instead of the trackmap. It only needs the testdata to be added as datasource for it to work.
[TestdataDB_join_test.json.zip](https://github.com/grafana/grafana/files/6821836/TestdataDB_join_test.json.zip)

As can be seen in the grafana 8.0.5 screenshot below, the graph shows data for all 3 metrics, but inspect doesn't join them in time.
![image](https://user-images.githubusercontent.com/6523124/125761795-71595f4d-4a74-4058-8e84-5b071d116b78.png)

**Anything else we need to know?**:
We bumped into this issue with the alexandra trackmap, see [issue 62](https://github.com/alexandrainst/alexandra-trackmap-panel/issues/62). Issue also seems to happen with other datasource types.

**Environment**: ubuntu 20.04.2
- Grafana version: 8.0.5
- Data source type & version: testdataDB datasource is bundled with grafana
- OS Grafana is installed on: Ubuntu 20.04.2
- User OS & Browser: mozilla firefox 89.02
- Grafana plugins: alexandra trackmap (used for most pictures above), graph (for reproducing step)
- Others:

**Comment by ryantxu** [comment]
You should be able to use:
![image](https://user-images.githubusercontent.com/705951/125847821-6a713337-f179-477e-8563-f6f8f2cf81f7.png)

or (in 8.1):
![image](https://user-images.githubusercontent.com/705951/125847893-4e8e9f05-cd68-4783-8533-a642a7755fd6.png)


And with the new (8.1) geomap panel :tada: 
![image](https://user-images.githubusercontent.com/705951/125848041-49d81e09-2a3f-4f71-8b57-b4e76e8b8664.png)

**Comment by ryantxu** [comment]
Nevermind... yes I can replicate:
![image](https://user-images.githubusercontent.com/705951/125848318-19602541-d0f0-46ad-9a9b-e0ae0c90c8a6.png)

**Comment by bijwaard** [comment]
Thanks Ryan, 

The outer-join indeed works, also as a work-around for the mentioned alexandra-trackmap issue. It may however not be so intuitive for most users.

Kind regards,
Dennis
