### ISSUE TITLE
Feature request: unit "timestamp" and "millisecond timestamp"

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3678]
I have a few timestamps in my TSDB and would like to show those in single-stats. Currently, I simply show them as an integer without units, but that's not very helpful. If I set the unit to seconds, it tells me 46y, which is as technically correct as it's useless.

Having timestamp as a unit would allow me to show a meaningful, human-readable value of last success, last failure, etc. And yes, that probably means that this unit would need to deal with timezones. Offering UTC and browser-timezone would be a reasonably 80/20 imo.

**Comment by Azef1** [comment]
Me too, I have on Y-axis a timestamp unit and it's not understandable. I would like to show this with human readable (ex: D-M-Y, M/D/Y, Y-M-D, hour/min/second ...).
Currently, I set the unit to seconds: 
![time](https://cloud.githubusercontent.com/assets/15362041/14241198/8835d680-fa4a-11e5-872d-facbb1502b4e.png)
I would like show 10h27min8s

**Comment by galindro** [comment]
+1

**Comment by jackric** [comment]
+1

**Comment by bartekj** [comment]
+1

**Comment by martinm82** [comment]
+1

**Comment by warden** [comment]
+1

**Comment by romanwozniak** [comment]
+1

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/9298 

adds 3 new date formats, (no custom date formats)
