### ISSUE TITLE
Elasticsearch datasource: paging query with offset and limit

### ISSUE THREAD

**Issue by tbmxp** [grafana/grafana#36781]
**What would you like to be added**:
How about add a new query parameter such as offset, using elasticsearch datasource to query logs?

**Why is this needed**:
Too much log records recalled by normal query, but grafana panel limit 500 records by default. Paging query with given offset and limited page size seems better.

**Comment by zoltanbedi** [comment]
Duplicate of https://github.com/grafana/grafana/issues/24236
