### ISSUE TITLE
Add REST API for Library Panels

### ISSUE THREAD

**Issue by saeltz** [grafana/grafana#36799]
**What would you like to be added**:

Library Panels are a cool new feature!
We want to utilize them but our Grafana runs without persistence, with all dashboards saved in an internal GitHub repository.
To use the library panels, we couldn't find a way to export the panel as JSON and also no API documentation (assuming the API exists).

**Why is this needed**:

To support Grafana users that don't have persistence to save the library panels.

**Comment by zoltanbedi** [comment]
Thanks for opening this issue @saeltz I think https://github.com/grafana/grafana/issues/34652 is the same what you just asked so I'm going to close this now.
