### ISSUE TITLE
AlertNG: GManaged Alert Annotations Errors when Map Keys Missing

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#36803]
**What happened**:
When a key is missing from `$labels` or `.Values` with a templated annotation, the whole template fails.

![image](https://user-images.githubusercontent.com/1692624/125794879-efeeb221-4dce-439f-96b6-6007b78dc92d.png)

Errors in the log look like:

```
EROR[07-15|09:47:15] error in expanding template
=ngalert name=summary value="Host \"{{ $labels.server }}\" in \"{{ $labels.location }}\" error rate of {{ .Values.errorRate }}% above {{ .Values.threshold }}%" err="error executing template __alert_SQL-Like Metric Selection (Direct Variant): 
template: __alert_SQL-Like Metric Selection (Direct Variant):1:132: executing \"__alert_SQL-Like Metric Selection (Direct Variant)\" at <.Values.errorRate>: 
map has no entry for key \"errorRate\""
```

**How to reproduce it (as minimally and precisely as possible)**:
Make an alert with annotation that tries to template a a label that doesn't exist.

cc @gerobinson

**Comment by kylebrandt** [comment]
I think I may also be seeing these sort of errors in the log when it happens:

```EROR[07-15|09:47:15] error in expanding template              logger=ngalert name=summary value="Host \"{{ $labels.server }}\" in \"{{ $labels.location }}\" error rate of {{ .Values.errorRate }}% above {{ .Values.threshold }}%" err="error executing template __alert_SQL-Like Metric Selection (Direct Variant): template: __alert_SQL-Like Metric Selection (Direct Variant):1:132: executing \"__alert_SQL-Like Metric Selection (Direct Variant)\" at <.Values.errorRate>: map has no entry for key \"errorRate\""
```

So if those are connected, maybe two things:
1. If something is missing, maybe better to expand into a missing string instead of erroring the whole template? (although maybe will be an issue with pipelines in templates?)
2. The main thing, why are these missing?

**Comment by davidmparrott** [comment]
Could change this so that we log the error and continue attempting to expand the template for possibly present values. This change was a result of https://github.com/grafana/grafana/pull/36535
