### ISSUE TITLE
Multi-enabled template var with single selection in ES query

### ISSUE THREAD

**Issue by henridf** [grafana/grafana#3680]
I have a template var `$my_var` (using an ElasticSearch query `{"find": "terms", "field": "my_field_name"}`) with multi-value enabled and multi-format set to Lucene.

I'm using that template in a graph where the query is defined as `my_field_name:$my_var`. 

When more than one value is selected, everything works fine. The query sent out by the client looks like:
```
  "query":"my_field_name:(\"bla\" OR \"bladeeblaa\")"
```
But with only one value selected, the query looks 
```
  "query":"my_field_name:bla"
```
and this fails (leading to the red triangle in ULH corner of graph) with an ElasticSearch parsing exception. 

The problem is of course that the field "bla" is not quoted. 

From the comments in #2828 it sounds like formatting single values isn't about to happen, but does anyone have a workaround? I'm hoping that I'm missing something straightforward. Thanks!

**Comment by torkelo** [comment]
why does unquoted `bla` result in ES exception? Or are the real value something that cantains non  word characters (that need to be quoted). 

To fix this a big change how the templating feature works needs to happen, there is an issue for it:
https://github.com/grafana/grafana/issues/2918

**Comment by henridf** [comment]
Thanks for quick response. Yes, the real values contain non `\w` characters.
