### ISSUE TITLE
explore UI messed up with Safari 

### ISSUE THREAD

**Issue by mxlxm** [grafana/grafana#36827]
**What happened**:
<img width="523" alt="image" src="https://user-images.githubusercontent.com/1845326/125891988-41dd74cf-ddf3-4faf-a9a9-d011641422e0.png">

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1、add three query, and run query.

**Anything else we need to know?**:
use TestDataDB with Logs/NodeGraph also messed up.

**Environment**:
- Grafana version: v8.0.6
- Data source type & version: any
- OS Grafana is installed on: Centos7
- User OS & Browser: MacOS 11.1 & Safari 14.0.2
- Grafana plugins: none
- Others:

**Comment by zoltanbedi** [comment]
I was not able reproduce this in safari 14.1.1. Can you please try to upgrade your browser or see if you can reproduce this in google chrome or firefox?

**Comment by mxlxm** [comment]
@zoltanbedi everything works fine with Chrome and Firefox. tested with Safari 14.0.3  also works fine.
But Safari version older than 14.0.3 all messed up. Coworkers tested.
