### ISSUE TITLE
Live: refresh graph at a minimum frame rate

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#36820]
Currently live feeds will refresh at the rate data changes... but that is not great when your data is not constantly refreshing or goes out of sync.  For live data, we often want the graphs moving left at a predictable speed regardless of the stream update rate

There are a few ways we can solve this:

1. Easy, but inconsistent:  each streaming query can include an update interval as a query parameter and have the and send duplicate values at that interval

2. Add a dashboard level refresh rate.  This will have a single ticker at the dashboard level that updates all panels with x=time

option 2 seems better but more involved :thinking:

**Comment by ypnos** [comment]
Looking forward to this feature. Here is an example of the current live refresh in a State Timeline panel. Would be great to have a smooth animation.

![state panel](https://user-images.githubusercontent.com/8481470/135925958-e5fd9e5b-a344-480e-8bdd-97ee4b1a6642.gif)

**Comment by ryantxu** [comment]
This is supported by the `liveNow` setting in dashboards (has been for a while)
<img width="461" alt="image" src="https://user-images.githubusercontent.com/705951/222227661-ebfaafa6-7293-442b-bea8-2f0b227743bb.png">
