### ISSUE TITLE
State Timeline: Hide short periods of time

### ISSUE THREAD

**Issue by baur** [grafana/grafana#36828]
**What would you like to be added**:

Hide short periods of time 

![image](https://user-images.githubusercontent.com/2898361/125894573-ed4aded7-a093-4a3f-a60f-e6525a2124eb.png)

**Why is this needed**:

I know for sure that these are communication problems or other non-system problems. It distorts reality.

**Comment by baur** [comment]
Like this:

![image](https://user-images.githubusercontent.com/2898361/125894805-a0a04fcf-91a0-45da-9414-c5b99fd405e8.png)

**Comment by baur** [comment]
@dprokop 

The screenshot shows that several equipments go offline at the same time, but this is impossible, this is clearly a communication problem. In addition, this physical equipment cannot turn off and turn on in a minute, these equipment are huge. Therefore, we would like to add minimum segments, if less to show (ignore) them.

**Comment by leeoniya** [comment]
@baur we are going to address the null threshold spanning in https://github.com/grafana/grafana/issues/36616

hopefully it is possible for these communications problems to be recorded as null values.

**Comment by baur** [comment]
> @baur we are going to address the null threshold spanning in #36616
> 
> hopefully it is possible for these communications problems to be recorded as null values instead of momentary "off" states.

Ok, 
Thank you!
