### ISSUE TITLE
Attach metadata (custom text) to each point on Time series Graph

### ISSUE THREAD

**Issue by MurzNN** [grafana/grafana#36833]
**What would you like to be added**:
Will be good to have ability to attach additional metadata to each point on Time series graph, something like this:
![image](https://user-images.githubusercontent.com/336662/125921257-4da824ed-9518-4b79-9363-564972a099f3.png)
That information can be attached, for example, from the same log record in Loki data source.

**Why is this needed**:
Very often, when we see something unusual on charts, we need to find source of that problem. Now we have only timestamp for this. But attaching metadata will greatly improve the usability of Grafana Charts!

**Comment by zoltanbedi** [comment]
You can do this by using exemplars see https://grafana.com/blog/2021/03/31/intro-to-exemplars-which-enable-grafana-tempos-distributed-tracing-at-massive-scale/

**Comment by MurzNN** [comment]
Thanks you for information, but I still can't find the right manual with description how to do this for Loki data source? In provided link there is example only for Prometeus. Can you please point me to right article about Exemplars and Loki, with displaying metadata on Grafana Chart?
