### ISSUE TITLE
Scoped Graphite data source

### ISSUE THREAD

**Issue by ecneladis** [grafana/grafana#3684]
It would be very helpful to have data sources with scoped Graphite paths, so you can expose only subset of metrics to specific organisations or users.

It'd impossible with direct data sources, but in proxy mode there could be some kind of path scoping/validation.

Today, even in viewer mode someone could call directly *api/datasources/proxy/(...)* and receives all the data from specificied data source.

**Comment by lsiudut** [comment]
+1 for that. We hit that problem not so long time ago. Good catch!

**Comment by szibis** [comment]
+1

**Comment by nagas** [comment]
+1

**Comment by zytek** [comment]
yeah, would like that

**Comment by torkelo** [comment]
this requires a feature in graphite-web as well (due wildcard queries it's next to impossible to handle in solely in Grafana)

**Comment by dhirajforyou** [comment]
Would like to mention my hack for same requirement.
As mentioned by Torkel, i modified graphite api to accept the metric
access- corresponding to org name.

I stored this metric access string in a new column in org sqlite table.

Ex. Org "world" have metric access to "one.data" only.

Add "one.data" as metric access in table org.
At time of proxy'ing query, add this to request.

At graphite level we filter out results with respect to metric access field.

Cons: one org needs entire access, where we can see all data.

Regards
