### ISSUE TITLE
CSS issue in span timing

### ISSUE THREAD

**Issue by jaketlarson** [grafana/grafana#36845]
**What happened**:
In Tempo, the larger spans at the top of the trace UI have their timings cut-off, which is confusing until you realize that it's just cut off.

**How to reproduce it (as minimally and precisely as possible)**:
Seems like every root span I check has its timing cut off or hidden. If you right click and inspect the span in the UI you can see that it's there, just out of view. In some instances it does show just an "ms" or "s".
![Screen Shot 2021-07-16 at 12 14 05 PM](https://user-images.githubusercontent.com/8398488/125939340-a0e8db85-923c-4be9-bbe8-a2de708923f5.png)

**Environment**:
- Grafana version: Grafana Cloud
- Data source type & version: Tempo
- OS Grafana is installed on: N/A
- User OS & Browser: macOS Chrome
- Grafana plugins: N/A

**Comment by connorlindsey** [comment]
We're currently investigating this issue and potential ways we can consistently display the span duration in the UI. I've prototyped a few solutions but am waiting for additional input from our UX team to make sure what solution we land on works well. 

In the meantime, span duration can be see by clicking on a span to expand the span details:
![image](https://user-images.githubusercontent.com/12838032/127171168-a1ce41c6-5d32-4488-9d68-4d2c0e54e94f.png)
