### ISSUE TITLE
Mentioning Slack users in alert notification messages no longer works

### ISSUE THREAD

**Issue by bigunyak** [grafana/grafana#36840]
**What happened**:
We use Slack integration to get alert notifications from Grafana. We have alerts configured for many different services and it's usually different people who are responsible for different services. This is why we need to mention different Slack users in the alert notification Message field. Mentioning people by their @slack_username used to work fine but since recently it's no longer working, and user mentions come as plain text, not recognised by Slack.

**What you expected to happen**:
Mentioning Slack users in alert notification Message field by their @slack_username should be recognised by Slack and trigger Slack notification for mentioned user.

**How to reproduce it (as minimally and precisely as possible)**:
Set up an alert with Slack integration and try mentioning Slack users in the alert notification Message field.

**Anything else we need to know?**:
I'm aware about possibility to use the Mention Users field under Optional Slack Setting. But as I explained, we have many different alerts and notifications should be assigned to different people.

**Environment**:
- Grafana version: v8.0.4 (81fef5b4b4)
- Data source type & version: NA
- OS Grafana is installed on: NA
- User OS & Browser: NA
- Grafana plugins: NA
- Others: NA

**Comment by santihernandezc** [comment]
Hi @bigunyak ! All mentions to Slack users must be done in the form of `<user ID>` as detailed [here](https://api.slack.com/changelog/2017-09-the-one-about-usernames).

Example alert text:
![Screen Shot 2021-09-02 at 14 33 52](https://user-images.githubusercontent.com/41638679/131890603-6492cad6-43fe-48f1-9f87-64f1102ba9d8.png)

Result:
<img width="504" alt="Screen Shot 2021-09-02 at 13 49 05" src="https://user-images.githubusercontent.com/41638679/131890644-d4f6f954-b95b-4d10-9e70-6a8682588d75.png">

This applies to new alerting but should apply to legacy alerting as well.
