### ISSUE TITLE
Cannot link Dashboard to Organization via API

### ISSUE THREAD

**Issue by mkolarek** [grafana/grafana#3685]
I have a use case where I have one data source for multiple organizations and when a dashboard is created via API I see no way to specify which organization it belongs to, only which data sources its panels use. Am I mistaken here or is this really not possible at the moment?

**Comment by torkelo** [comment]
it is, the user your authenticating as is using an organization (one can be active at any time). You can change which org that is , http://docs.grafana.org/reference/http_api/#switch-user-context
