### ISSUE TITLE
Tracing: show number of child span in UI

### ISSUE THREAD

**Issue by kvrhdn** [grafana/grafana#36862]
**What would you like to be added**:
Show (at a glance) the amount of child spans a span has. This is useful information to understand how many operations a span created.

**Why is this needed**:
For instance, in Tempo we have an operation scanning our backend and this creates one span per request. Since we are scanning a lot of data it creates a ton of spans, multiple pages to scroll through.
It would help me to see at a glance how many requests this list contains.

![Screenshot 2021-07-16 at 19 09 04](https://user-images.githubusercontent.com/7748404/125984214-a827810b-ba08-432b-8dc6-8fefd828dc63.png)

![Screenshot 2021-07-16 at 19 10 18](https://user-images.githubusercontent.com/7748404/125984343-debd7cb5-e4a6-4872-9401-f55f05fc40ff.png)

I'm honestly not sure what the best place to show this is, maybe next to the ❗ sign in the collapsed view?

**Comment by tharun208** [comment]
@ivanahuckova, I like to work on this. Before starting up, can you tell me where to add this count in the UI?

**Comment by ivanahuckova** [comment]
@zoltanbedi  @connorlindsey @aocenas Can you help with this?

**Comment by zoltanbedi** [comment]
I think we need to get help from @Ijin08 to figure out where to put it.

**Comment by connorlindsey** [comment]
The plan is to display the span count here in the left side pane as well as in the expanded span row view next to the service, duration, and start time. The span names should still be vertically aligned so the implementation should adjust the number of digits shown accordingly. 

![image](https://user-images.githubusercontent.com/12838032/130490977-1d029f56-6950-4a8b-adfb-af94d6310117.png)

![image](https://user-images.githubusercontent.com/12838032/130491201-ac8363df-f0d3-41be-9b4e-c1c0fdb4755e.png)
