### ISSUE TITLE
Full page refresh no longer warns user of unsaved changes

### ISSUE THREAD

**Issue by Ultraseamus** [grafana/grafana#36871]
**What happened**:

Made changes in a dashboard, then went to refresh the page without saving, and observed that there was no "Unsaved changes" prompt.

**What you expected to happen**:

I expected the same functionality as previous Grafana versions. Which was a prompt asking if I was sure that I wanted to refresh.

**Environment**:
- Grafana version: 8.0.6
- User OS & Browser: Chrome

**Comment by andresmgot** [comment]
Also happens when clicking on a link, my +1  :pray:
