### ISSUE TITLE
Safari 14 with Grafana 8.0.6 results in "Grafana has failed to load its application files"

### ISSUE THREAD

**Issue by nkukard** [grafana/grafana#36875]
**What happened**:
Upgraded from 7.5.7 to 8.0.4 and noticed error only on Safari 14 stating "Grafana has failed to load its application files".

Reviewed bug #34897 and bug #35594 which appeared to be resolved in #36274, commit appeared to be in release 8.0.5.

Upgraded to 8.0.5 and had the same result only on Safari 14.

Upgraded to 8.0.6 and had the same result only on Safari 14.

Browsers tested: Firefox, Google Chrome, Chromium, Microsoft Edge, Vivaldi  - All working

**What you expected to happen**:
No error to be displayed and Grafana to load.

**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana 8.0.6 and attempt opening in Safari 14.

**Anything else we need to know?**:
Screenshots below...
![Screenshot_20210717_064655](https://user-images.githubusercontent.com/2354782/126028645-d0f55a9c-1fde-46a8-a699-ae1f3e0ec2c7.png)
![Screenshot_20210717_064714](https://user-images.githubusercontent.com/2354782/126028646-49709e95-da97-4cb4-86fd-4edd38226ea7.png)
<img width="1680" alt="image001" src="https://user-images.githubusercontent.com/2354782/126028647-e84950ce-6535-4124-8063-75c6512bb1d7.png">

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Tested Prometheus
- OS Grafana is installed on: Tested Ubuntu 20.04
- User OS & Browser: Version 14.1.1 (16611.2.7.1.4)
- Grafana plugins: Standard ones
- Others:

**Comment by williamsp** [comment]
I also have the same issue since updating to Grafana 8, but on Firefox for Android (and some older versions of desktop Firefox).
This happens also in Private Browsing mode, with plugins disabled. The only error in the console is "invalid regexp group".

Here's the screenshot:
![Screenshot from 2021-07-19 12-31-51](https://user-images.githubusercontent.com/3760416/126126096-4f714a58-4c55-4adf-8a45-53bbb9c52cf6.png)

**Comment by kaydelaney** [comment]
Unable to reproduce with the 8.0.6 docker image. Will test the upgrade path later.

**Comment by TobiKr** [comment]
Having the same issue with Samsung Digital Signage displays running on Tizen OS (which worked before upgrading to 8.0).

**Comment by tskarhed** [comment]
@nkukard From what source did you install Grafana?

**Comment by nkukard** [comment]
@tskarhed I tested on Ubuntu 20.4 using https://grafana.com/docs/grafana/latest/installation/debian/

I'm now using ArchLinux with the same issue...
ref https://archlinux.org/packages/community/x86_64/grafana/
ref https://github.com/archlinux/svntogit-community/blob/packages/grafana/trunk/PKGBUILD

**Comment by dg-nvm** [comment]
we also see that after the update from 7.3.7 to 7.5.9 Safari users complain about the "Grafana has likely been updated". Safari 13 and the latest 14, does not matter.

We use docker containers to ship Grafana

**Comment by marceloudi** [comment]
Same error here on Firefox 74:

`SyntaxError: invalid regexp group app.843e85298b12060ea650.js:1:18`


 **Environment:**

    Grafana version: v8.1.1 (90c87a52f7)
    Browser User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:74.0) Gecko/20100101 Firefox/74.0 
    Grafana plugins: Standard ones
    Others:

**Comment by tskarhed** [comment]
We installed the Grafana Docker image 7.5.7 with a persistent volume and upgraded to the latest (8.1.1), and we still didn't manage to replicate the Safari (14.1.1) issue.

For the Firefox, I would highly recommend upgrading the version. We couldn't reproduce in the latest one.

**Comment by Rafiki-o7** [comment]
I have found that the issue occurs after logging in.
- Goes to grafana url
  -- no problems
- logs in
  -- no problems
- home dashboard loads upon login in
  -- problem occurs
- changes URL to grafana url/dashboards
  -- no problems
- opens any dashboard
  -- problem occurs

I hope this helps give more clarity to the specific problem

**Comment by ashharrison90** [comment]
we still have no way of reproducing this internally so it's difficult to make any progress on working on a fix. 🤔 

it would be extremely helpful if anyone who can reproduce can make sure they're on the latest version of grafana/safari and provide as much info as possible. thanks! 🙏

**Comment by williamsp** [comment]
I don't know about Safari, but for Firefox:

On Android, it's reproducible on Firefox Fennec, but not in Firefox Daylight.
Download link: https://download.mozilla.org/?product=fennec-latest&os=android&lang=multi

On Desktop, I think it's reproducible on early Firefox Quantum.
I tried 68 and it has the issue, @marceloudi tried 74 and has the issue too.
So, maybe only after the latest ESR (version 78), the issue is gone.

Download link: 
https://ftp.mozilla.org/pub/firefox/releases/68.9.0esr/
https://www.mozilla.org/en-US/firefox/all/#product-desktop-esr

**Comment by jackw** [comment]
@nkukard @williamsp @Rafiki-o7 Do you have CSP enabled in the `grafana.ini` settings or do you have a proxy setup with CSP?

**Comment by nkukard** [comment]
@jackw Yep, here is my CSP and reverse proxy settings... I'm using Apache. I just want to re-iterate that this works with all browsers except Safari until I updated as mentioned above. Perhaps something more is required.
```
<VirtualHost *:443>
        ServerName redacted.redacted
        Header set Content-Security-Policy "default-src 'self'; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
        Header set Strict-Transport-Security "max-age=31536000"
        Header set X-Content-Type-Options "nosniff"
        Header set X-Frame-Options "SAMEORIGIN"
        Header set X-XSS-Protection "1; mode=block"
        ProxyPassReverse / http://localhost:3000/
        SSLCertificateFile /etc/letsencrypt/live/redacted.redacted/fullchain.pem
        SSLCertificateKeyFile /etc/letsencrypt/live/redacted.redacted/privkey.pem
        Include /etc/letsencrypt/options-ssl-apache.conf
        <Location "/">
                ProxyPreserveHost On
                RequestHeader set X-Forwarded-Proto "https"
                RequestHeader set X-Forwarded-Ssl "on"
                ProxyPass http://localhost:3000/
        </Location>
</VirtualHost>
```

**Comment by jackw** [comment]
@nkukard I believe your issue might be related to your Apache CSP template. In the following image you'll see an error `this operation is insecure` prior to the `panelsRendered` error. Do you see the same?

![image](https://user-images.githubusercontent.com/73201/135588333-366c50ac-f129-4f63-ace5-1b4c7a2ed3c5.png)

A possible idea would be to add `Content-Security-Policy-Report-Only` which should give report warnings in the browser console allowing you to understand what is causing some scripts to fail to load. More info can be found [here](https://cheatsheetseries.owasp.org/cheatsheets/Content_Security_Policy_Cheat_Sheet.html#2-content-security-policy-report-only-header).

For reference Grafana ships with a content security policy that looks similar to this:

```
Header set Content-Security-Policy "script-src 'self' 'unsafe-eval' 'unsafe-inline' 'strict-dynamic';object-src 'none';font-src 'self';style-src 'self' 'unsafe-inline' blob:;img-src * data:;base-uri 'self';connect-src 'self' grafana.com;manifest-src 'self';media-src 'none';form-action 'self'"
```

**Comment by nkukard** [comment]
@jackw good catch!! sadly I don't have Safari myself, so didn't immediately see that.

I had to remove "strict-dynamic" from the CSP, this works for me ...
```
script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'none'; font-src 'self'; style-src 'self' 'unsafe-inline' blob:; img-src * data:; base-uri 'self'; connect-src 'self' grafana.com; manifest-src 'self'; media-src 'none'; form-action 'self'
```

**Comment by jackw** [comment]
@nkukard excellent news! I'm going to go ahead and close this issue. I'll add something to our documentation explaining that using CSP with a reverse proxy will require particular settings.

Regarding the `SyntaxError: invalid regexp group` error some are experiencing here with older versions of firefox I'd suggest following @ashharrison90 [instructions further up](https://github.com/grafana/grafana/issues/36875#issuecomment-923935703) and update to the latest version.

**Comment by TobiKr** [comment]
Hi,

we still see the issue here with Tizen OS TVs. Error message is "Grafana has failed to load its application files". I have no option to debug the browser, but see these entries in the access log:
```
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk HTTP/1.1" 200 41402 "-" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/fonts/roboto/RxZJdnzeo3R5zSexge8UUVtXRa8TVwTICgirnJhmVJw.woff2 HTTP/1.1" 200 14748 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/build/runtime.4bfd7b0ee99616560b7a.js HTTP/1.1" 200 4349 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/build/grafana.dark.4bfd7b0ee99616560b7a.css HTTP/1.1" 200 231496 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/build/angular~app.4bfd7b0ee99616560b7a.js HTTP/1.1" 200 185386 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/build/moment~app.4bfd7b0ee99616560b7a.js HTTP/1.1" 200 292676 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/img/grafana_icon.svg HTTP/1.1" 200 5690 "https://dashboard.sec.dogado.net/" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/fonts/roboto/CWB0XYA8bzo0kSThX0UTuA.woff2 HTTP/1.1" 200 14600 "https://dashboard.sec.dogado.net/public/build/grafana.dark.4bfd7b0ee99616560b7a.css" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/build/app.4bfd7b0ee99616560b7a.js HTTP/1.1" 200 2664522 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
172.22.55.37 - - [04/Oct/2021:14:50:46 +0200] "GET /public/build/vendors~app.4bfd7b0ee99616560b7a.js HTTP/1.1" 200 2883457 "https://dashboard.sec.dogado.net/d/VZF2cISGz/internal-it-overview?orgId=1&refresh=10s&kiosk" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"
```

I added the following header to the nginx config:
`add_header Content-Security-Policy "script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'none'; font-src 'self'; style-src 'self' 'unsafe-inline' blob:; img-src * data:; base-uri 'self'; connect-src 'self' grafana.com; manifest-src 'self'; media-src 'none'; form-action 'self'";`

Do you have any idea how to debug this further?

Thanks
Tobias

**Comment by nkukard** [comment]
@TobiKr , @jackw , I must apologize I received a message "All is working" but it was referring to everything except Safari.

I'm busy trying to acquire a Safari browser to test this out on and will debug further.

@TobiKr , can I ask if you had any CSP headers before?

**Comment by TobiKr** [comment]
@nkukard thanks for your quick reply! I did not have any CSP headers or reverse proxy before. I just installed nginx as reverse proxy to check if this would solve the issue.

**Comment by leeoniya** [comment]
> we still see the issue here with Tizen OS TVs.
> `200 41402 "-" "Mozilla/5.0 (SMART-TV; Linux; Tizen 4.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.0 Safari/537.36" "-"`

Chrome 56 was released almost 5 years ago (2017-01-25). I'm not sure there are concrete plans to continue supporting browsers that are never upgraded. Is it possible to upgrade the TV's OS & browser version to something more recent?

**Comment by nkukard** [comment]
@TobiKr Thanks, was just curious. As @leeoniya said, its probably due to the age of the browser. The Tizen site has some info about what the browsers support, but I think thats what your particular problem is.

FWIW I threw a PI onto each of our TV's and fed them HDMI.

I'll revert back with my findings into Safari hopefully tomorrow.

**Comment by nkukard** [comment]
I have looked into the Safari issue deeper now as I got my hands on a MacOS system.

The issue with Safari is it does not allow WS/WSS connections when `connect-src` or `default-src` has `'self'` listed. Despite every other browser out there allowing it.

To get Safari to work if you are using a CSP, then you need to add `wss:` for TLS (and if you still not using TLS, which you should be), then `ws:`.

My original CSP now works...
```
Content-Security-Policy: "default-src 'self'; connect-src 'self' wss:; font-src 'self' data:; img-src 'self' data:; script-src 'self' 'unsafe-eval' 'unsafe-inline'; style-src 'self' 'unsafe-inline';"
```

As does the one posted by @jackw ...

```
Content-Security-Policy: "script-src 'self' 'unsafe-eval' 'unsafe-inline'; object-src 'none'; font-src 'self'; style-src 'self' 'unsafe-inline' blob:; img-src * data:; base-uri 'self'; connect-src 'self' grafana.com; manifest-src 'self'; media-src 'none'; form-action 'self'"
```

**Comment by TobiKr** [comment]
@leeoniya @nkukard Yes, it's always a pain with these integrated browsers, but a good compromise if you have >50 displays to manage :-) There is no newer firmware version, but I am going to open a case with Samsung. I just wonder why it worked with Grafana < 8.0

**Comment by leeoniya** [comment]
> I just wonder why it worked with Grafana < 8.0

if you want to know specifically, you can try opening Grafana 8.0+ in Chrome 56 on a Windows, Linux or macOS desktop and see what the errors say in DevTools console.

it could be missing / old specced IntersectionObserver, ResizeObserver, MatchMedia, or any other web platform features that we have started using to optimize performance in modern browsers.

**Comment by TobiKr** [comment]
> if you want to know specifically, you can try opening Grafana 8.0+ in Chrome 56 on a Windows, Linux or macOS desktop and see what the errors say in DevTools console.
> 
> it could be missing / old specced IntersectionObserver, ResizeObserver, MatchMedia, or any other web platform features that we have started using to optimize performance in modern browsers.

Thanks for the hint, I made some screenshots of the errors. I am not a JS developer and cannot assess if those errors are related to the outdated browser version or "real errors". Do you have an idea?

![2021-10-05_13h17_32](https://user-images.githubusercontent.com/9446386/136013344-46639a45-8549-4af6-842e-58e888cc87dc.png)
![2021-10-05_13h16_54](https://user-images.githubusercontent.com/9446386/136013345-527574c5-b254-4a8f-93c0-143525505de1.png)
![2021-10-05_13h17_41](https://user-images.githubusercontent.com/9446386/136013348-ac089957-aa83-42d4-85a9-41fe29c504e5.png)

**Comment by leeoniya** [comment]
both of these are syntax errors that can probably be fixed by configuring Babel for older browser support..BUT, once these are fixed, you'll likely run into more errors that are not syntax related but feature related, and require more involved work-arounds. it would be an endless goose chase now and in the future to keep working around these deficiencies in old browsers.

the best advice is not to rely on built-in browsers in the TVs and simply use them as dumb displays. throw a Pi (or similar) with Chrome on each of them and call it a day.

**Comment by tablatronix** [comment]
Same issue on ipad safari, proxy or not no difference
