### ISSUE TITLE
Firefox 90 can not connect to Grafana

### ISSUE THREAD

**Issue by gquintana** [grafana/grafana#36887]
**What happened**:

I run Grafana Server on Windows (either directly or with Docker) and then open http://localhost:3000 with Firefox 90.0.
Firefox can not open the default login page, the HTTP request seems to be stuck. I can not see any log on the server side telling me something bad occured. I can not see the HTTP request in Firefox debugger, it looks like Firefox can not open a TCP connection to local Grafana.

**What you expected to happen**:

The Grafana login page should appear on Firefox.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run Grafana server on Windows
2. Open http://localhost:3000 with Firefox 90 on Windows

**Anything else we need to know?**:

* Tried different Grafana Version (7.3 and 8.0.6) deployed differently (Windows exec or Docker image on Docker Desktop with WSL2) -> none works 
* Tried different browsers both Edge and Chrome, both of them can open the login page. It proves my Grafana server is in good shape and it's a Firefox related issue
* Tried older Firefox 78.12.0esr, it doesn't have the problem either. It seems to be related to recent Firefox releases.
* Firefox 90 is properly setup: I am creating this issue with it, I can use Kibana with it. I removed all plugins.
* Tried http://127.0.0.1:3000 doesn't help
* Tried running another Web server locally (Node http-server), Firefox 90.0 can connect to it
* Tried using  "Private browser" mode (navigation privée) but doesn't help

**Environment**:
- Grafana version: 6.7.5, 7.3.0, 8.0.3 to 8.0.6
- Data source type & version: doesn't matter at this point
- OS Grafana is installed on: Windows 10 or Docker Desktop for Windows with WSL2
- User OS & Browser: Firefox 90.0 for Windows
- Grafana plugins: none
- Others:
![grafana-firefox](https://user-images.githubusercontent.com/755587/126072930-57b02776-1e75-4ed6-89a7-76054597a969.png)

** Additionnal info **

Immediately after Windows startup there is already something listening on port 3000:
```
$ netstat -aon

Connexions actives

  Proto  Adresse locale         Adresse distante       État
  ...
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       4292
  TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING       4292
  ...

$ Get-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    426      27     3592      11580              4292   0 svchost
```
I ignore what svchost is, but it doesn't prevent Grafana from starting
```
INFO[07-20|18:26:03] HTTP Server Listen                       logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```
The funny part is that there are now several things listening on port 3000:
```
$ netstat -aon

Connexions actives

  Proto  Adresse locale         Adresse distante       État
...
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       1296
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       4292
...
 TCP    [::]:3000              [::]:0                 LISTENING       1296

$ Get-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    296      18    39968      54820       0,58   1296   1 grafana-server
    393      27     3116      10660              4292   0 svchost
```
I seems that svchost is listening on IPv4:3000 while Grafana  is listening on IPv4+IPv6:3000

Now if I set `http_addr = 120.0.0.1` to bind only localhost and to IPv4
```
EROR[07-20|18:27:29] Stopped HTTPServer                       logger=server reason="failed to open listener on address 120.0.0.1:3000: listen tcp 120.0.0.1:3000: bind: L’adresse demandée n’est pas valide dans son contexte."
EROR[07-20|18:27:29] Server shutdown                          logger=server error="HTTPServer run error: failed to open listener on address 120.0.0.1:3000: listen tcp 120.0.0.1:3000: bind: L’adresse demandée n’est pas valide dans son contexte."
HTTPServer run error: failed to open listener on address 120.0.0.1:3000: listen tcp 120.0.0.1:3000: bind: L’adresse demandée n’est pas valide dans son contexte.
```

Finally changing the listening port `http_port = 8888` (8888 is unsed) and now I can open Grafana with Firefox 90.0!

It seems to me that Grafana shouldn't start while port 3000 is already used.

**Comment by kaydelaney** [comment]
My first thought is it might be a Content-Security Policy issue. Does your server config have CSP enabled?

**Comment by gquintana** [comment]
@kaydelaney I am using Grafana defaults settings, i didn't tune anything to debug this issue and `content_security_policy = false` by default

**Comment by gquintana** [comment]
Additionnal info:

Immediately after Windows start there is something listening on port 3000:
```
$ netstat -aon

Connexions actives

  Proto  Adresse locale         Adresse distante       État
  ...
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       4292
  TCP    0.0.0.0:3001           0.0.0.0:0              LISTENING       4292
  ...

$ Get-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    426      27     3592      11580              4292   0 svchost
```

But it doesn't prevent Grafana from starting
```
INFO[07-20|18:26:03] HTTP Server Listen                       logger=http.server address=[::]:3000 protocol=http subUrl= socket=
```
The funny part is that there are now several things listening on port 3000:
```
$ netstat -aon

Connexions actives

  Proto  Adresse locale         Adresse distante       État
...
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       1296
  TCP    0.0.0.0:3000           0.0.0.0:0              LISTENING       4292
...
 TCP    [::]:3000              [::]:0                 LISTENING       1296

$ Get-Process -Id (Get-NetTCPConnection -LocalPort 3000).OwningProcess

Handles  NPM(K)    PM(K)      WS(K)     CPU(s)     Id  SI ProcessName
-------  ------    -----      -----     ------     --  -- -----------
    296      18    39968      54820       0,58   1296   1 grafana-server
    393      27     3116      10660              4292   0 svchost
```
I seems that svchost is listening on IPv4:3000 while Grafana  is listening on IPv6:3000

Now if I set `http_addr = 120.0.0.1` to bind only localhost and to IPv4
```
EROR[07-20|18:27:29] Stopped HTTPServer                       logger=server reason="failed to open listener on address 120.0.0.1:3000: listen tcp 120.0.0.1:3000: bind: L’adresse demandée n’est pas valide dans son contexte."
EROR[07-20|18:27:29] Server shutdown                          logger=server error="HTTPServer run error: failed to open listener on address 120.0.0.1:3000: listen tcp 120.0.0.1:3000: bind: L’adresse demandée n’est pas valide dans son contexte."
HTTPServer run error: failed to open listener on address 120.0.0.1:3000: listen tcp 120.0.0.1:3000: bind: L’adresse demandée n’est pas valide dans son contexte.
```

Finally changing the listening port `http_port = 8888` (8888 is unsed) and now I can open Grafana with Firefox 90.0!

**Comment by tskarhed** [comment]
@gquintana Hi! Could you update the initial post with that information?

**Comment by mckn** [comment]
Closing this issue since it seems to be resolved, please let me know if I need to reopen it.
