### ISSUE TITLE
ngalert constantly repeating alert notification.

### ISSUE THREAD

**Issue by Selaron** [grafana/grafana#36888]
**What happened**:
I get constantly repeating alerts (e.g. every 5min) after migration to ngalert grafana 8.

**What you expected to happen**:
I'd expect to get one alert notification and one resolved notification as soon the state is ok again.

**How to reproduce it (as minimally and precisely as possible)**:
Configure an alert that  fires if your 16 core CPU has less than 1000 cores for 5min. You'll get wired mail notification telling this alert is firing plus resolved (e.g. 2 alerts firing, 5 alerts resolved).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Debian bullseye

**Comment by Darth-Bobo** [comment]
I've noticed a similar problem with an AWS Timestream source, I've attached an example section from a graph that's produced by a service tester.

The tester spits out connections failures over a two minute period (we've deliberately broken it for testing here).  The alert is set to fire if the sum of the failures is greater than 0 over a five minute period - which it does - but then it clears the alert after around four minutes even though the alert condition should still be satisfied.  It does not then appear to re-evaluate the condition for another few minutes when it correctly goes into the pending->alert cycle again before clearing the alert once more.

I can't quite put my finger on the issue as after leaving this overnight it did behave as expected for periods of 2-3 hours before going into this cycle again for a while.

Grafana version: 8.0.5
Data source: AWS Timestream

<img width="762" alt="Screenshot 2021-07-21 at 10 47 51" src="https://user-images.githubusercontent.com/50400845/126469263-e5a03b08-6f1b-45cd-ac1d-d60b785e007a.png">

**Comment by kylebrandt** [comment]
@Selaron is this with the new "ngalert" feature flag or is this the dashboard alerting (without that flag?)

**Comment by kylebrandt** [comment]
@Selaron Can you share some information on an alert rule that this is happening with?

1. The queries and the "classic condition"
2. The rule settings for the "Evaluate every" and "For", and the settings under "Configure no data and error handling"

**Comment by Selaron** [comment]
@kylebrandt I added a screenshot of a rule related to prometheus node exporter firing if a particular device has less than 100GB free space left.

In legacy alerting I got a single [Alert] notification as soon this condition was true and another [OK] notification after cleaning up the disk.

After migration to ngalert, I get frequent [firing] notifications until the disc is cleaned.
Each of the notification mails may contain one or multiple [firing] and [resolved] sections for this particular alert configuration.

![GrafanaAlert](https://user-images.githubusercontent.com/234048/127140131-65ad64ae-09a4-4c5a-ba03-66ace1c0a536.png)

**Comment by kylebrandt** [comment]
@Selaron Sounds like it could be https://github.com/grafana/grafana/issues/36644 - are you able try this on the `main` branch of Grafana, or try when the next 8.1.0 beta/final comes out?

**Comment by Selaron** [comment]
@kylebrandt  Fixed with solution mentioned in #36644: Just upgraded to Grafana 8.1.1 - thank you :)

**Comment by Selaron** [comment]
@kylebrandt  Just wanted to add that I now get [FIRING]-Notifications as expected, but I do not get [RESOLVED]-Notifications anymore. Would this be a new issue?

**Comment by kylebrandt** [comment]
@Selaron Yes going to close this one, so please make a new issue for not getting resolved, as we will need to figure out how that is coming about.
