### ISSUE TITLE
Datasource mixed: MySQL and InFluxDB showing "results" as metric label

### ISSUE THREAD

**Issue by biohazardxxx** [grafana/grafana#36896]
What Grafana version and what operating system are you using?
v8.0.6 & Win server 2019

What are you trying to achieve?
After upgrade from v7 panels with a datasource mixed (one from MySQL and anohter from InfluxDB) suddenly the metric labels of the MySQL query are prefixed with “results”.
![image](https://user-images.githubusercontent.com/1370362/126120421-844c2737-c339-4ac3-9984-9fd4335267a0.png)

Disabling/removing the influxDB query makes "results " disapear. 

How are you trying to achieve it?
The querys using do not have an affect on this. But anyhow here examples:
MySQL:
SELECT
  $__timeGroupAlias(runAt,$__interval),
  env AS metric,
  count(id) AS value
FROM captures
WHERE
  $__timeFilter(runAt)
GROUP BY 1,2
ORDER BY $__timeGroup(runAt,$__interval)

Influx query
SELECT mean("PercentProcessingUnitUsed") FROM "systemStatus" WHERE ("host" = 'MyServer') AND $timeFilter GROUP BY time($__interval) fill(linear)

What did you expect to happen?
Not showing results as part of metric names.

Did you receive any errors in the Grafana UI or in related logs?
Nope

**Environment**:
- Grafana version: v8.0.6
- Data source type & version: MySQL & InfluxDB
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: WIn 10 , Chrome
- Grafana plugins: not related

**Comment by ivanahuckova** [comment]
I was able to reproduce the issue. The extra "result" word appear, when we use mysql data source in combination with ANY other data source (not just influxDB).
![image](https://user-images.githubusercontent.com/30407135/126152410-184d1f0e-0bf6-4a34-84c7-1730572ee211.png)
![image](https://user-images.githubusercontent.com/30407135/126152462-5e4fa7c9-18f7-490a-90c9-c6a58e454d84.png)

**Comment by ivanahuckova** [comment]
I am not sure if this is bug, or if there is a reason for this. Passing to @grafana/backend-platform to evaluate.
