### ISSUE TITLE
Error when import dash with panel library

### ISSUE THREAD

**Issue by SN4K3D** [grafana/grafana#36897]
I put the link of the problem already reported on your platform so that it can be referenced here too and have an answer ;)

Continue your work, Grafana is a great Opensource tool!

https://community.grafana.com/t/error-when-import-dash-with-panel-library/49884

**Comment by SN4K3D** [comment]
thank you very much @hugohaggmark  for this new feature  !

**Comment by hugohaggmark** [comment]
> thank you very much @hugohaggmark for this new feature !

Please let me know if you find any issues with it. Thank you!
