### ISSUE TITLE
Feature Request: Support for influxdb '=~' operator in WHERE conditions

### ISSUE THREAD

**Issue by sysadmin1139** [grafana/grafana#3689]
There is WHERE operator grafana doesn't support, but influx does, `=~`. Unlike a lot of influx stuff, this shouldn't require a complete reengineering of the UI. Here is an example query that uses it:

    SELECT sum(value) 
    FROM hit_counters 
    WHERE
        webapp =~ /api_[a-z]/ AND
        time > now() - 2d 
    GROUP BY
        time(5m), webapp

This will produce multiple time-series, and grafana is smart enough to chart them. When used with an alias like `$tag_webapp`, new API services willl automatically appear on the charts without having to edit the chart.
![hitsbyapp](https://cloud.githubusercontent.com/assets/812860/12206615/89152204-b607-11e5-82f9-a3b69acbe83e.png)
It's pretty cool, and it would be great if it were in the query editor.

**Comment by torkelo** [comment]
In what way does it not support it????
http://play.grafana.org/dashboard/db/influxdb?panelId=1&fullscreen&edit

**Comment by torkelo** [comment]
I mean it was support from the first version :) 
so not sure what you mean

**Comment by sysadmin1139** [comment]
For whatever reason, the equality operators I have in the 2.6.0 build I'm running only has 

    =
    <>
    <
    >

The `=~` operator is not present. There is no UI hint that this feature is supported.

And yet... there is your example of it doing so. When I put in `/api_[a-z]/` in the second field, this stealth operator pops in as if by magic.
