### ISSUE TITLE
A11y - Fix  double focus when global focus styles are applied

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#36908]
While testing this PR https://github.com/grafana/grafana/pull/36533 report double focus issues here, we can address them in another PR.

It is usually solvable with `display: inline-block`.

- [ ] Cards: Double focus stops / focusable thing in Cards (first one with rounded border, then one with square borders) (Dashboard -> Alerting, Configuration -> DataSources)

**Comment by tharun208** [comment]
@axelavargas I like to work on this

**Comment by axelavargas** [comment]
> @axelavargas I like to work on this

@tharun208 That's Amazing👏, thank you! feel free to open a PR

**Comment by axelavargas** [comment]
Issue was fixed 🚀 on [PR](https://github.com/grafana/grafana/pull/37783)
