### ISSUE TITLE
[Time series] Selecting graphs in legend is not working if a different display name is set

### ISSUE THREAD

**Issue by Ram-Sys** [grafana/grafana#36904]
![grafanaTimeSeries](https://user-images.githubusercontent.com/15229932/126137065-4484ab51-52b6-40dc-a7cd-4c065b322dba.gif)

**What happened**: When selecting a graph in the legend, all graphs get hidden or shown.

**What you expected to happen**: Just the one selected should be hidden or shown.

**How to reproduce it (as minimally and precisely as possible)**: Create a Time Series Panel with at least two graphs and set an alternate 'display name' via series override

**Anything else we need to know?**: 

**Environment**:
- Grafana version: tested with v8.0.3 and v8.0.6
- Data source type & version: simpod JSON Datasource
- OS Grafana is installed on: runs in Container (official Docker image)
- User OS & Browser: Linux + Firefox
- Grafana plugins: simpod-json-datasource,linksmart-sensorthings-datasource,grafana-worldmap-panel,marcusolsson-static-datasource,agenty-flowcharting-panel,snuids-trafficlights-panel,marcuscalidus-svg-panel,dalvany-image-panel,grafana-worldmap-panel,marcusolsson-csv-datasource,marcusolsson-json-datasource
- Others:

**Comment by kaydelaney** [comment]
Should be fixed for 8.1: https://github.com/grafana/grafana/pull/35893
