### ISSUE TITLE
Official release '8.0.6' sha256 not in synch across CDN

### ISSUE THREAD

**Issue by Esysc** [grafana/grafana#36906]
I'm building a custom Grafana ami on AWS that will replace our running `prod` instance. I'm using `packer` + `salt` to build and everything is done on AWS. `salt` template is update to point to `8.0.6` and use `sha256` from the [download page](https://grafana.com/grafana/download): `7aa819d28f15c7c602258990ed0be68e9fcf4217ced60be2052c8b37746826b7`

**What happened**:
The build process fails systematically  due to sha256 inconsistency, the file differs. I've downloaded the `.deb` file on my laptop and computed `sha256` was exactly as published. I then did the same on an EC2 instance and got different results. 

| laptop                      |  ec2                         |
| -------------------------- | ------------------------- |
| wget https://dl.grafana.com/oss/release/grafana_8.0.6_amd64.deb | wget https://dl.grafana.com/oss/release/grafana_8.0.6_amd64.deb |
| ... | ... |
| Connecting to dl.grafana.com (dl.grafana.com) 151.101.14.217 | Connecting to dl.grafana.com (dl.grafana.com) 199.232.26.217 |
| `sha256sum`: 7aa819d28f15c7c602258990ed0be68e9fcf4217ced60be2052c8b37746826b7 | `sha256sum`: 36a21b33974f3c68ccb6bab98b720fce6566013fbd03662b368268f3890cb5e9 |
| `ls -l`: `55808124 juil. 15 13:05 grafana_8.0.6_amd64.deb` | `ls -l`: `55803436 Jul 14 15:22 grafana_8.0.6_amd64.deb` |

As you can easily check, the timestamp and file weight is not the same.

**What you expected to happen**:
The file should be coherent across CDN.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 20.04 x86_64
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by Esysc** [comment]
Hi checked again manually and the issue seems to be solved somehow. Should I close this one?

**Comment by wbrowne** [comment]
@Esysc Great to hear. Yep I'll go ahead and close it
