### ISSUE TITLE
Docs feedback: /panels/visualizations/table/table-field-options.md

### ISSUE THREAD

**Issue by JohannesFluegel** [grafana/grafana#36907]
If you click on https://grafana.com/docs/grafana/latest/panels/visualizations/table/table-field-options/ on the links _Configure all fields_ or _Configure specific fields_, nothing happens.

**Comment by achatterjee-grafana** [comment]
Hello @JohannesFluegel ! which version of Grafana docs are you looking at?

Looking at the latest Table visualization information, this section "https://grafana.com/docs/grafana/latest/visualizations/table/#table-options" corresponds to https://grafana.com/docs/grafana/v7.5/panels/visualizations/table/table-field-options/.

Also, for field overrides documentation, refer to https://grafana.com/docs/grafana/latest/panels/field-overrides/. For versions 7.5 and older, refer to https://grafana.com/docs/grafana/v7.5/panels/field-options/.

Hope this helps.

**Comment by achatterjee-grafana** [comment]
Closing this issue as the link  https://grafana.com/docs/grafana/latest/panels/visualizations/table/table-field-options/ no longer exists. 

I have provided the updated links in the previous comment.
