### ISSUE TITLE
Bug: Graph not displaying all lines

### ISSUE THREAD

**Issue by danodemano** [grafana/grafana#3692]
So this is an odd one.  Bear with me as I'm still fairly new to both Grafana and InfluxDB.  Yesterday I setup a Smokeping-like metric.  I have a script doing pings every ~30 seconds and writing them to the InfluxDB.  Yesterday it was working great, everything displayed as expected.  Today however most of the lines are missing from the graph but ONLY when using a time-frame less than 12 hours.  What's even more strange is that when you hover-over the graph the data for the line IS THERE.  It's hard to even fully describe so let me just show some pictures:

3-hour view:
![3-hours](https://cloud.githubusercontent.com/assets/1128744/12222789/6e45588e-b794-11e5-8eff-f0cf058fe7b6.PNG)

Hover-over on 3-hour view:
![hover](https://cloud.githubusercontent.com/assets/1128744/12222791/6e4a9498-b794-11e5-8e52-8a55959aa602.PNG)

12-hour view:
![12-hours](https://cloud.githubusercontent.com/assets/1128744/12222790/6e48820c-b794-11e5-8d41-675a343034d8.PNG)

OS: CentOS 7 x64
Grafana Version: 2.6.0
InfluxDB Version: 0.9.6.1

Please let me know what additional information I can provide.  Any assistance or insights would be appreciated.  Thanks!

EDIT: I actually took a screenshot yesterday to send around to some of my coworkers.  Here's what it looked like on the 3-hour view when it was working:

![dashboard_1](https://cloud.githubusercontent.com/assets/1128744/12222898/b790ce18-b796-11e5-8fb9-9b5a652d9225.PNG)

EDIT 2: Now I'm really confused...I just flipped over to the tab to check temps and it's working again.  NOTHING has changed on the server or my local machine:

![new](https://cloud.githubusercontent.com/assets/1128744/12223153/c4809c28-b79d-11e5-93c1-13ec0a6ab1c5.PNG)

**Comment by torkelo** [comment]
have you stack enabled without fill(0) in your query perhaps?

**Comment by torkelo** [comment]
stacking requires there to be values for all data series, if one below is null it wont stack anything

**Comment by danodemano** [comment]
@torkelo Thanks for the quick reply!  I had it set to "fill(null)" the default, just changed it to "fill(0)".  Yes I am using stacking so I suspect that was the issue.  I'll keep an eye and it and let you know if the problem re-surfaces.  Thanks again!

**Comment by gobibooma** [comment]
In latest grafana, select group by option as fill(0).
![image](https://user-images.githubusercontent.com/29653473/28237502-b51a931e-695e-11e7-9347-e19c346cc6bb.png)

**Comment by torkelo** [comment]
Check your InfluxDB max-row-limit option :)

**Comment by bergerx** [comment]
I'm not sure if this is the same problem, but metrics gone missing when zoom out, playing with different fill values does not change the result.

You can see here that more metrics appear as I zoom in:
![influxdb-missing-metrics-when-zoomed-out](https://user-images.githubusercontent.com/45531/28310428-237e8dda-6bb5-11e7-8da6-cde8eb6d230c.gif)

**Comment by torkelo** [comment]
probably an issue with your infludb query or your influxdb settings, to low max-row-limit can cause the above behaviour

**Comment by mabnz** [comment]
Guys,

I’m seeing something similar in 4.6.2 with series not showing. I’ve recorded a video here (https://vimeo.com/244248457). Is this likely to be related or has this been determined not to be a bug?

**Comment by mabnz** [comment]
This is still occurring for me on the latest build? If I duplicate the panel it doesn't happen, suggesting it's not any influxdb configuration I've not made.

**Comment by daniellee** [comment]
@mabnz at the end of your video, it looks like the dashboard refreshes and then the panels are identical. (The left panel gets the same series as the right panel) Or am I missing something?

**Comment by mabnz** [comment]
@daniellee Yes that's correct, but only after modifying the panel to change the span length. If no changes were made the panel would only show a max of 7 series, repeated refreshes not withstanding.
