### ISSUE TITLE
WebSocket connection failed. Error in browser console, since Grafana version 8.0.4.

### ISSUE THREAD

**Issue by itejera** [grafana/grafana#36929]
Starting from version 8.0.4, a lot of this messages: _WebSocket connection to 'ws://ip_host:port/api/live/ws' failed:_         _centrifuge.js:544_ , started to show in the Chrome console.

![grafana](https://user-images.githubusercontent.com/87670746/126221005-9a31a44c-0cd4-4aad-a9e5-e180400e8af9.gif)

And Firefox console

![firefox](https://user-images.githubusercontent.com/87670746/126222155-c7674fce-61ee-45df-bfe2-d00b971eda99.gif)

No change was done to the existing dashboards, all was working great before. The messages just start appearing after upgrading from 8.0.3.   

**Environment**: 
- Grafana version: 8.0.6
- Data source type: InfluxDB
- OS Grafana is installed on: Debian 10
- User OS & Browser:  Windows/MacOS : Chrome/Firefox

**Comment by asciifaceman** [comment]
Digging around I can't find a fix. I no longer understand how one is supposed to configure grafana to use an https-offloading reverse proxy

**Comment by FZambia** [comment]
This is caused by a change made in v8.0.4 to solve #34537

By default, Grafana now checks request Origin to match `root_url` option in `[server]` section. It's also possible to set a list of allowed origin patterns using `allowed_origins` option in `[live]` section. See [docs](https://grafana.com/docs/grafana/latest/live/configure-grafana-live/#request-origin-check), also an ongoing pr to v8 upgrading section - #36661 

There is also a known bug #36822 – I am not sure whether it's related to your specific setup though. I need a server warning line to understand, could you guys post warning from server logs which contains `Request Origin is not authorized` message? 

But while this bug exists it's still possible to use `[live] allowed_origins` option to avoid problems with WebSocket connection.

**Comment by asciifaceman** [comment]
I had fixed it and it was working using the new `[live]` config however today it quit on me again. Nondescript 400 errors, it's not complaining about authorization tho. Just a bare `Request Completed` with a 400 without further context.

**Comment by Rohlik** [comment]
I receiving also this msg with Grafana 8.1.1, but in my case I have `400` not `403` errors in Grafana log:  
```
t=2021-08-19T11:55:03+0200 lvl=info msg="Request Completed" logger=context userId=4 orgId=1 uname=tomas.rohlik@EXAMPLE.COM method=GET path=/api/live/ws status=400 remote_addr=50.55.50.50 time_ms=0 size=12 referer=
```
In Chrome console is error visible as:
```
WebSocket connection to 'wss://grafana-dev.na.example.com:8443/api/live/ws' failed: centrifuge.js:544
```

I have this in my `grafana.ini`:
```
[live]
allowed_origins = "https://grafana-dev.na.example.com:8443"
```

Can you tell me why this error occuring or can I ignore it? 🤔

**Comment by FZambia** [comment]
@Rohlik hello, 400 in most cases caused by reverse proxy. Are you using Nginx? In this case you need to enable WebSocket proxy support since Nginx can't proxy WebSocket by default [as shown here](https://grafana.com/docs/grafana/latest/live/configure-grafana-live/#websocket-and-proxies).

**Comment by Rohlik** [comment]
@FZambia Thank you for that. Yes, we are using Apache as reverse proxy. Now, because of you I know what I need to fix. Thanks once more time 👍🏽 .

**Comment by eardkdw** [comment]
I'm also using Apache, but @Rohlik 's solution above didn't work for me, possibly because we have Grafana in sub path. This worked, however:

```apache
<Location /grafana>
      # destination directory
      ProxyPreserveHost On
      ProxyPass http://127.0.0.1:3000
      ProxyPassReverse http://127.0.0.1:3000
      RequestHeader set X-Forwarded-Proto 'https'
      Header set X-Frame-Options SAMEORIGIN

      Order deny,allow
      Allow From all
   </Location>
   <Location /grafana/api/live/ws>
      #Deal with websocket for live updates
      ProxyPreserveHost On
      ProxyPass ws://127.0.0.1:3000/grafana/api/live/ws
      ProxyPassReverse ws://127.0.0.1:3000/grafana/api/live/ws

   </Location>
```

**Comment by nazar2343** [comment]
WebSocketClient.js:16 WebSocket connection to 'wss://3000-nazar2343-testproject-94kvcv2mnk8.ws-eu38.gitpod.io:3000/ws' failed:  Як вирішити проблему поможіть пліз

**Comment by miq28** [comment]
I'm on Grafana 8.4.5, Ubuntu 18.04, Apache 2.x 
For Apache and grafana on subpath, I solved this by first installing the necessary apache modules, including websocket

- proxy
- proxy_http
- proxy_wstunnel

I got inspired from this [website](https://www.serverlab.ca/tutorials/linux/web-servers-linux/how-to-reverse-proxy-websockets-with-apache-2-4/)  and @eardkdw [answer](https://github.com/grafana/grafana/issues/36929#issuecomment-1036381333) above.

Then this apache conf works from me -  please note my grafana is on subpath` http://domain.com/gf` path:

```apache
<VirtualHost *:80>
	ServerName domain.com
	ServerAlias domain.com
        DocumentRoot /var/www/domain.com

  # handle subpath
  <Location /gf>        
        ProxyPreserveHost On
        ProxyPass http://localhost:3000
        ProxyPassReverse http://localhost:3000
  </Location>

  # handle ws
  <Location /gf/api/live/ws>
        ProxyPreserveHost On
        ProxyPass ws://localhost:3000/gf/api/live/ws
        ProxyPassReverse ws://localhost:3000/gf/api/live/ws
  </Location>
</VirtualHost>
```
In `grafana.ini` I also enabled
```go
serve_from_sub_path = true
```

No more ws console error 😁

**Comment by SincerelyUnique** [comment]
Same issue for Grafana 8.4.4

**Comment by FZambia** [comment]
@nazar2343 @SincerelyUnique hello, WebSocket error usually happens due to 2 possible reasons:

1. [Origin check](https://grafana.com/docs/grafana/latest/live/configure-grafana-live/#request-origin-check) - this is usually 403 status code and server logs have detailed origin failure description
2. Reverse proxy server/load balancer not configured to proxy WebSocket connections. For example, Nginx configuration described [here](https://grafana.com/tutorials/run-grafana-behind-a-proxy/). This is usually 400 status code.

**Comment by mimihmaponya** [comment]
> This is caused by a change made in v8.0.4 to solve #34537
> 
> By default, Grafana now checks request Origin of WebSocket Upgrade request to match `root_url` option in `[server]` section. It's also possible to set a list of allowed origin patterns using `allowed_origins` option in `[live]` section. See [docs](https://grafana.com/docs/grafana/latest/live/configure-grafana-live/#request-origin-check), also an ongoing pr to v8 upgrading section - #36661 (UPD. [available on doc site](https://grafana.com/docs/grafana/latest/installation/upgrading/#grafana-live))
> 
> There is also a known bug #36822 – I am not sure whether it's related to your specific setup though. I need a server warning line to understand, could you guys post warning from server logs which contains `Request Origin is not authorized` message?
> 
> But while this bug exists it's still possible to use `[live] allowed_origins` option to avoid problems with WebSocket connection.

**Comment by mimihmaponya** [comment]
Hi. 

I know this is closed, I have trying to establish connection to wss using apache httpd on Oracle Linux 8 and i keep getting the wss failed warning when I inspect and my application is running using wildfly and it is accessible securely using https but I am unable to access web socket securely with https.

**Comment by hasnainnaseem2** [comment]
If you are using nginx proxy to serve grafana then you can use below configuration to solve web socket issue.


http {
    map $http_upgrade $connection_upgrade {
        default upgrade;
        '' close;
    }

    upstream grafana {
        server 127.0.0.1:3000;
    }

    server {
        listen 8000;

        location / {
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection $connection_upgrade;
            proxy_set_header Host $http_host;
            proxy_pass http://grafana;
        }
    }
}

**Comment by mxsxs2** [comment]
I am posting my solution for a Kubernetes deployed Grafana where I got 400 for the socket connections.

I have HAProxy terminate SSL before the request gets into the Kubernetes NGINX Inc ingress controller.

I added this annotation to my ingress:
```
nginx.org/server-snippets: |
      location /api {
        rewrite  ^/(.*)  /$1 break;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "Upgrade";
        proxy_set_header Host $http_host;
        proxy_pass http://loki-grafana.monitoring.svc.cluster.local;
      }
```

_loki-grafana.monitoring.svc.cluster.local_ is the internal DNS for the service.

Now I get 101.

**Comment by yucob** [comment]
I got same errors.

**Comment by gifforeign4** [comment]
I tackled that challenge and identified a resolution https://lnkr.fun/a84abbf

**Comment by hoetz** [comment]
@sorcer1122 definitely try this: https://github.com/grafana/grafana/issues/36929#issuecomment-954500731

This finally fixed the WSS error spam for me.

**Comment by xuyenvuong** [comment]
For Caddy on OPNSense, to support WS, make sure to add these `header_up` headers

Add headers: `OPNSense -> Services -> Caddy -> Reverse Proxy -> Headers -> +`

e.g. for `header_up Connection "Upgrade"`, do
```
Header: header_up
Header Type: Connection
Header Value: Upgrade
```

```
header_up Connection "Upgrade"
header_up Upgrade "websocket"
header_up Host {host}
header_up X-Forwarded-For {remote_host}
header_up X-Forwarded-Host {host}
header_up X-Forwarded-Proto {scheme}
header_up X-Real-IP {remote_host}
```
Next, `-> Handlers` -> Select and Edit the proxy domain you want to support WS
Open `Transport`, from `HTTP Headers` select all of the above `header_up` headers -> `Apply`

Next, verify it by going to `Diagnostics -> Caddyfile`, you shoud see something like this:

```
yourdomain.com {
    handle {
        reverse_proxy 192.168.1.13:11000 {
            header_up Connection "Upgrade"
            header_up Upgrade "websocket"
            header_up Host {host}
            header_up X-Forwarded-For {remote_host}
            header_up X-Forwarded-Host {host}
            header_up X-Forwarded-Proto {scheme}
            header_up X-Real-IP {remote_host}
        }
    }
}
```
Now, restart Caddy. Everything should work.
