### ISSUE TITLE
Alert Labels Are Not Overwritten for pagerduty in Grafana8 Alerts

### ISSUE THREAD

**Issue by salamanderrex** [grafana/grafana#36931]
**What happened**:
I am trying to use grafana8 alerts with labels like summary and severity. 
contact points

![image](https://user-images.githubusercontent.com/6581499/126251371-5bad5b07-9c2f-4231-bfc4-5827cf076d7c.png)
the alert
![image](https://user-images.githubusercontent.com/6581499/126251288-7d0cc463-2e9a-4c19-995f-35aec4a4ef97.png)

**What you expected to happen**:
severity on pagerduty side is warning and msg should be the alert msg.
**How to reproduce it (as minimally and precisely as possible)**:
Just link with pagerduty with grafana8.

**Anything else we need to know?**:

This is the msg on pagerduty side. it should have a field called `payload`?  [doc](https://developer.pagerduty.com/docs/events-api-v2/trigger-events/)

```
{
  "client": "Grafana",
  "client_url": "http://localhost:3000/",
  "contexts": [
    {
      "href": "http://localhost:3000/",
      "text": "External URL",
      "type": "link"
    }
  ],
  "description": "this is from dev-monitoring portal",
  "event_type": "trigger",
  "incident_key": "some_key",
  "service_key": "another_key",
  "details": {
    "firing": "
Labels:
 - alertname = new rancher1 just slack
 - service = rancher
 - severity = warning
Annotations:
 - description = yes
 - summary = summary over
Source: http://localhost:3000/alerting/xxxxxxx/edit
Silence: http://localhost:3000/alerting/silence/new?alertmanager=grafana&matchers=alertname%3Dnew+rancher1+just+slack%2Cservice%3Drancher%2Cseverity%3Dwarning
",
    "num_firing": "1",
    "num_resolved": "0",
    "resolved": ""
  }
}
```

pagerduty GUI
![image](https://user-images.githubusercontent.com/6581499/126251871-e454930f-c2e9-4172-8618-0c48e0e90b41.png)

**Environment**:
- Grafana version: 8.0.6
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
Hello @grafana/backend-platform! I am not sure if this is a bug or miss-configuration/question. Passing to your backlog to evaluate.

**Comment by codesome** [comment]
@salamanderrex the severity is set in the _contact point config_, and the labels on the rule _do not_ override it. I see in your screenshot that the config for the contact point is indeed "Critical", which is what you see in Pagerduty. If you want to use Warning, you have to create another contact point with Warning severity and have routing policies to route to appropriate contact points based on labels.

Regarding the `payload` field in the JSON, I am not sure if the JSON that you posted is possible to be produced by Grafana, we do set only the `payload` field and not the `details`. I will double check. Do you happen to have any proxy in between that might be doing some translation?

**Comment by codesome** [comment]
@salamanderrex I had another close look at the JSON that you posted. That is a valid JSON for Pagerduty's v1 API (incident_key is also for v1, while for v2 its dedup_key). So I am wondering if you are using Prometheus Alertmanager with a v1 API.

I checked Grafana's JSON for Pagerduty and it has the payload field and everything that you would expect for v2 API.

Example payload from Grafana
```json
{
   "routing_key":"someintegrationkey",
   "dedup_key":"cc9772a1ec901d26ef71dae861793e4d08979fa5030a3f0a5f3ba549f1f2d0b6",
   "description":"[FIRING:1]  (AlwaysFiring lvalue1 lvalue2)",
   "event_action":"trigger",
   "payload":{
      "summary":"This is a custom summary",
      "source":"ganesh",
      "severity":"critical",
      "class":"test class",
      "component":"Grafana",
      "group":"default",
      "custom_details":{
         "firing":"\nLabels:\n - alertname = AlwaysFiring\n - lname1 = lvalue1\n - lname2 = lvalue2\nAnnotations:\n - description = my description\n - summary = my summary\nSource: http://localhost:3000/alerting/7J1LXaZ7k/edit\nSilence: http://localhost:3000/alerting/silence/new?alertmanager=grafana\u0026matchers=alertname%3DAlwaysFiring%2Clname1%3Dlvalue1%2Clname2%3Dlvalue2\n",
         "num_firing":"1",
         "num_resolved":"0",
         "resolved":""
      }
   },
   "client":"Grafana",
   "client_url":"http://localhost:3000/",
   "links":[
      {
         "href":"http://localhost:3000/",
         "text":"External URL"
      }
   ]
}
```

**Comment by salamanderrex** [comment]
Thanks for the update.  I do not use Prometheus Alertmanager.

I checked the pagerduty side. That is a new service i created for testing and the API key is v2.

Another thing i missed to tell is my deployment, it was a Grafana `v7.4.3 ` via helm chart and i changed the version to `Grafana 8`. Maybe something in existing db, sqlite, makes it pagerduty v1? ( but Grafana uses pagerduty v2 API since 6.1.6, idk. I had one more migration before my 7.4.3. but i cannot recall that version)

**Comment by codesome** [comment]
v2 is hardcoded in Grafana 8 alerting, including using the `payload` and not the `details`, and `dedup_key`/`routing_key` instead of `incident_key`/`service_key`. So there is no way the JSON payload that you posted is possible to be generated from Grafana 8 alerting.

Could you share the pagerduty config present in the DB before you migrated?

**Comment by gotjosh** [comment]
@salamanderrex If I understand this issue correctly it relates to the usage of the PD v1 API in the old Grafana alerting given that after 8 we hardcode v2 directly.

If this is the case I'm going to close down this issue since we're only dealing with critical bugs in the old alerting. Feel free to re-open if I'm mistaken.
