### ISSUE TITLE
Are there any WebSocket DataSource plugins?

### ISSUE THREAD

**Issue by xmlking** [grafana/grafana#3693]
I have `socket.io` server running, that can feed real-time data to dashboard.
are there any grafana plugins to feed real-time data via  WebSocket ?

it would be nice to have real-time dashboard support in Grafana like [freeboard](https://github.com/Freeboard/freeboard)

**Comment by torkelo** [comment]
no not currently, the current data source api (javascript abstraction that all datasources implement) does not have support for that. 

You can set refresh rate as low as 1s which gives you very real time graphs.
