### ISSUE TITLE
Table panel is active behind panel editor

### ISSUE THREAD

**Issue by JorundMartinsen** [grafana/grafana#36934]
**What happened**:
Table panel is 'interactable' when editing another panel

**What you expected to happen**:
Table panel should not be interactable

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a text panel.
2. Create a table panel.
3. Inflate text panel so the table is placed approx. center bottom.
4. Open text panel editor
5. Hover where table headers were. They are be interactable, with mouse response

https://user-images.githubusercontent.com/11029081/126271504-1022dccf-c713-40d4-9dfe-253391d99589.mp4

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.4 (81fef5b4b4)
- OS Grafana is installed on: Cloud version
- User OS & Browser: Win10 1909 (18363.1556) | Chrome 91.0.4472.124

**Comment by glintik** [comment]
Hey,

Thank you @JorundMartinsen for good catch!
I removed z-index for table column resize div. It's not needed actually.
