### ISSUE TITLE
Grafana World Map plugin no longer supports data from Loki now that the "query as prometheus" function has been deprecated

### ISSUE THREAD

**Issue by proffalken** [grafana/grafana#36936]
**What happened**:

Since support for querying Loki via the Prometheus data source was removed, it is not possible to query the data in Loki to return in the format required by the Worldmap plugin.

When you could configure a Prometheus data source to point to Loki, then the following query would return the latitude, longitude, city, country, and sum total as a table that could be used to populate datapoints on the map

```
sum(rate({job="fluentbit"}|= "pppoe0" | json | latitude != "" and latitude != 0 and longitude != "" and longitude != 0 [$__interval])) by (country, city, latitude, longitude)
```
Now that you cannot use the prom data source for Loki, the explorer view returns this:

![2021-07-20_07-41](https://user-images.githubusercontent.com/262545/126274144-b9f1a973-bf12-4b82-b3ec-43b5ca92a60b.png)

and the world map in table view returns this:

![2021-07-20_07-44](https://user-images.githubusercontent.com/262545/126274218-0fb80fdb-a790-4e5e-95d9-983bb7eb7c80.png)

**What you expected to happen**:

I expect to see the data from Loki used to plot points on the map.  The below was from when you could use the Prom data source with Loki:

![SIEM Dashboard](https://www.budgetsmarthome.co.uk/img/monitoring_dashboard.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create a new dashboard with a World-Map panel on it and query a loki data source that contains lat/long/city/country data.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.6 (68fe9e3431)
- Data source type & version: Built in to the above version
- OS Grafana is installed on: Linux (official docker container)
- User OS & Browser: Arch Linux, Brave.com Browser
- Grafana plugins: grafana-github-datasource,grafana-worldmap-panel,grafana-clock-panel,grafana-piechart-panel,natel-discrete-panel,mtanda-histogram-panel,larona-epict-panel,grafana-googlesheets-datasource,agenty-flowcharting-panel,gowee-traceroutemap-panel
- Others:

**Comment by ivanahuckova** [comment]
Hello @proffalken! Does it work if you use **Labels to fields** transformation? https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#labels-to-fields

**Comment by proffalken** [comment]
@ivanahuckova thanks, that's got me a lot closer and has the labels as columns in the table, it's certainly a good workaround for now, however I'm seeing quite a delay in updates with relatively small data sets (< 1000 rows), so it doesn't feel quite like the complete solution.

![2021-07-20_12-34](https://user-images.githubusercontent.com/262545/126319151-2fa59800-8f9c-462d-b436-3bc9effcf01d.png)

Now I'm trying to get the count of the access attempts into the Value field for the map.

I'm using https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#add-field-from-calculation with the "Count" operator, however this just results in everything being set to `1` rather than being the total number of times each city appears in the data set.

![2021-07-20_12-52](https://user-images.githubusercontent.com/262545/126319235-32ab0976-ee86-40e3-b3e3-600421fc6614.png)

I'd expect to see one row per city, with the "count" representing the number of times that city appears in the range.

I'll keep working my way through the various filters, but if you know of a way to do this easily I'd love to hear it!

**Comment by ivanahuckova** [comment]
> however I'm seeing quite a delay in updates with relatively small data sets (< 1000 rows), so it doesn't feel quite like the complete solution.

Not sure what do you mean by delay? Can you please share video of it, because I wasn't able to reproduce. 

>Now I'm trying to get the count of the access attempts into the Value field for the map.

Is that something you could do in Prometheus? You should be able to do that in the same way.

**Comment by proffalken** [comment]
> > however I'm seeing quite a delay in updates with relatively small data sets (< 1000 rows), so it doesn't feel quite like the complete solution.
> 
> Not sure what do you mean by delay? Can you please share video of it, because I wasn't able to reproduce.

Delay as in it takes a while to process all of these results, and it *feels* like it takes longer now than it did before.  This could be anecdotal, I'll see if I can confirm with some proper data.

> 
> > Now I'm trying to get the count of the access attempts into the Value field for the map.
> 
> Is that something you could do in Prometheus? You should be able to do that in the same way.

I'll try, it used to "just happen" when using the Prom data source with Loki, it doesn't appear to be the case now.

**Comment by proffalken** [comment]
OK, closing this, the following settings give me what I want:


### Query:
```
sum by (country, city, latitude, longitude) (count_over_time({job="fluentbit"}|= "pppoe0" | json | latitude != "" and latitude != 0 and longitude != "" and longitude != 0 [$__interval]))
```

### Transformations:

![2021-07-26_13-11](https://user-images.githubusercontent.com/262545/126986616-3401c90e-a4b6-4717-ad2e-c07e89514c1d.png)

**Comment by ivanahuckova** [comment]
@proffalken thanks for sharing how you resolved this! 🙏
