### ISSUE TITLE
invalid influxdb query in annotations documentation

### ISSUE THREAD

**Issue by f0s0** [grafana/grafana#3694]
Documentation at http://docs.grafana.org/reference/annotations/ shows a non valid influxdb query:
`select text from events where $timeFilter`
Influxdb complains when value is not selected. For me works:
`select text,value from events where $timeFilter`

**Comment by torkelo** [comment]
what version of influxdb are you iusing

with 0.9.5 I can query things like "select message from logs where $timeFilter"  fine
