### ISSUE TITLE
Anonymous viewing on organization while logged in can return 404's

### ISSUE THREAD

**Issue by madarivi** [grafana/grafana#36949]
**What happened**:

Grafana returns a 404's while requesting to an organization with anonymous viewing right for a logged in user that is not part of that organization. 

**What you expected to happen**:

I expect requests for the organization with anonymous viewing that only require viewing permission to an organization configured with anonymous viewing to always succeed.    

**How to reproduce it (as minimally and precisely as possible)**:

1. Create two organizations (org1, org2)
2. Configure org2 for anonymous viewing
```
[auth.anonymous]
enabled = true
org_name = Cockpit
org_role = Viewer
hide_version = true
```
3. Create a user, user1, in org1
4. Observe a call to view something in org2 to succeed (e.g. `curl 'https://grafana.monitoring.tiled.media/api/dashboards/home?orgId=2'`
5. Login with user1 and extract the grafana session cookie
6. Observe the same call to view something in org2 to fail with a 404 (e.g. `curl 'https://grafana.monitoring.tiled.media/api/dashboards/home?orgId=2' -H 'Cookie: grafana_session=***'`

**Anything else we need to know?**:
The setup we are trying to support is Iframe embed, with anonymous viewing. The issue we are running is the following. We have a webapp with embedded grafana panels using the anonymous viewing setup. This works fine until these users also log into the grafana UI because it sets the grafana_session cookie on all the iframe embed requests.

**Environment**:
- Grafana version: v8.0.2 (5c5d45e19f)
- Data source type & version: not relevant
- OS Grafana is installed on: grafana/grafana:8.0.2 docker image
- User OS & Browser: any
- Grafana plugins: https://github.com/doitintl/bigquery-grafana/archive/1.0.8.zip;doitintl-bigquery-datasource,grafana-worldmap-panel
- Others:

**Comment by wbrowne** [comment]
Am able to reproduce. Thanks for creating this issue @madarivi 😄

**Comment by alexanderzobnin** [comment]
Hi! I'm looking into the issue and it seems it's how it should work. Anonymous auth intended to work only with unauthenticated users. Once the user is logged in, anonymous auth is not applied anymore. So the user should be a member of organization which configured for anonymous access. It feels strange since user can log out and then have access to the org, so maybe we can improve it.
