### ISSUE TITLE
Grafana smtp not working

### ISSUE THREAD

**Issue by kisienya** [grafana/grafana#3695]
I am trying to configure grafana with smtp in order to allow invites to grafana organisations via email.

I can send mail on linux prompt via mutt on the server that has grafana and postfix installed. However I cannot send mail via grafana web interface when inviting users.

I have configured grafana.ini smtp values appropriately i.e.
enabled =	true
from_address =	from@address.com
host	= name.of-server.com:25

The log files are quiet.

Is there a configuration I am missing?

Cheers

**Comment by torkelo** [comment]
strange that the  log file is quiet. Set log level to Trace, should see that grafana tries to send email. 

did you restart grafana-server after config change?

**Comment by kisienya** [comment]
Thanks Torkelo,

I restarted the server, revoked and recreated the users and now its working.

Cheers

**Comment by swdream** [comment]
@kisienya @torkelo  how can I check that grafana sent email to make sure my smtp config is right?

**Comment by torkelo** [comment]
Check grafana log for errors?
