### ISSUE TITLE
sumSeries function is not working in Grafana for more than two different metrics.

### ISSUE THREAD

**Issue by prashant-koshatwar** [grafana/grafana#3696]
I am trying to sum following three different metrics:
- vlg.infrastructure.aws.ec2.Ec2RunningCosts.*
- vlg.infrastructure.aws.ebs.EbsRunningCost.*
- vlg.cost.aws.datatransfer.*.*.*

Individually all three show correct values. And single value for each day.Which is expected.

But when I apply sumSeries on these metric it shows multiple values for some days (but not all).
Which is not expected.

Please help me on this ASAP.

**Comment by torkelo** [comment]
Sum series is a graphite function, executed in graphite

**Comment by prashant-koshatwar** [comment]
![image](https://cloud.githubusercontent.com/assets/16647913/12235262/a610a7aa-b898-11e5-9630-e99f4f4092ee.png)

This is how I am using in grafana but some how for above metrics it is not working

**Comment by torkelo** [comment]
You can use query reference instead of using the text editor for bested queries. See info help in query editor help section. Not sure I can help with troubleshooting graphite query problems,maybe  ask in graphite project?

**Comment by prashant-koshatwar** [comment]
Thanks for quick replay.

By using Query reference we can select only one metrics if we want to use complex function then Query is not useful.
 
Please reopen the issue, may be another one can help to resolve that problem.

**Comment by torkelo** [comment]
what do you mean ,"only select one metric" ?

This works great:
![image](https://cloud.githubusercontent.com/assets/10999/12237375/a7247f14-b87e-11e5-8292-a1547a443014.png)

Not sure why a graphite issue should be open here in the grafana project? What do you mean btw by "multiple values for some days" ?

**Comment by adslwy** [comment]
Hey Torkelo,
Your answer is very useful, actually many of us don't familar with Graphite, how to select multpile metrics to do sum up also bother me for a while
