### ISSUE TITLE
Geomap: unexpected error

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#36971]
Grafana 8.1.0-29019pre
on Windows 2019 Server

custom.ini
```
[server]
protocol = https
http_port = 443
domain = www.zoomsoft.de
enforce_domain = true
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

add panel
add empty panel
switch to Geomap

![grafik](https://user-images.githubusercontent.com/79257887/126386163-90c35b77-6c03-4a73-8a6c-b408a15b30ed.png)

**Comment by ryantxu** [comment]
@UlrichThiess -- can you try again?  This should be fixed now, but please let us know if you still see issues!

**Comment by UlrichThiess** [comment]
Thank you, it works. However, it is not yet a replacement for TrackMap.

Offtopic: Is there a way to always get the latest build with WGET? Then I could create a task that installs the current Buil once an hour.
