### ISSUE TITLE
Format Single Stats Values with Commas

### ISSUE THREAD

**Issue by itzmesanjib** [grafana/grafana#3699]
Okay, everything work great for me - until i found out that a few of the stats are so big that its virtually not possible to decipher by the human eye. I am using a single stat panel and the value it returns is something like xxxxxxxxxx. I would like that to be shown in the screen in the following manner: x,xxx,xxx,xxx
Is it possible? I have tried a few ways but did not find anything till now. I need this urgently done so any help in this regard will be high appreciated!!
PS: Sorry if this issue has been raised earlier and already fixed.

**Comment by torkelo** [comment]
try the different unit formats, there is no one that has a bunch of commas, but you can use short, then you will get `1.23 Mil` for milion range, (or Bil , etc)

**Comment by itzmesanjib** [comment]
Thanks @torkelo !!
