### ISSUE TITLE
Empty Table Panel's Options

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#3702]
On Grafana v3.0.0-pre1, the Table Panel's **Options** tab is empty, without presenting the options for the columns' data type manipulation as seen on v2.6 and older versions.

![image](https://cloud.githubusercontent.com/assets/8490141/12259166/b520e1ba-b90b-11e5-8c8e-27ab319a00fc.png)

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master, will push out new build soon.

**Comment by antjori** [comment]
Thanks! :+1:
