### ISSUE TITLE
Stopping when the metric flow stops

### ISSUE THREAD

**Issue by krishnakanthpps** [grafana/grafana#3704]
Hi.

Is it possible to stop the refresh of the graph from command line as soon as the data inflow stops. 

I want my jmeter test graph to stop refreshing as soon as the test ends, so that if I forget for some reason to see the graphs, it should not keep updating/refreshing the graph.

**Comment by torkelo** [comment]
no there is no way to remotely stop an auto refresh setting on a dasbhoard
