### ISSUE TITLE
Problem rendering PNGs

### ISSUE THREAD

**Issue by hasso** [grafana/grafana#3705]
I had a problem rendering PNG files and tracked it down to SSL/TLS issue with phantomjs. The problem is that with '--ssl-protocol=any' phantomjs is starting from SSLv2, but with SSLv2 support removed from servers at all, the initial SSLv2 hello is rejected immediately without any chance to upgrade a version.

I think that b2a0ae0f83e1c3d98a8f7822fabefac86b0230ab should be just reverted as original issue doesn't exist any more either - TLSv1 is now default in phantomjs.

**Comment by torkelo** [comment]
since when did they change default TLS version in phantomjs?

**Comment by hasso** [comment]
No idea, but it is:

$ /usr/share/grafana/vendor/phantomjs/phantomjs --help | grep TLS
  --ssl-protocol=<val>                 Sets the SSL protocol (supported protocols: 'SSLv3', 'SSLv2', 'TLSv1' (default), 'any')

**Comment by torkelo** [comment]
but if TLSv1 is default why is `any` causing a change in that?

**Comment by hasso** [comment]
Because 'any' doesn't mean that it attempts to connect with all known protocol versions until it succeeds, but probably "let's start with lowest one and try to upgrade it". What I see here is that phantomjs attempts to connect with SSLv2, server sends back a TLSv1 fatal alert (which means that connection is terminated) and phantomjs doesn't attempt a new connection.

**Comment by torkelo** [comment]
what happens when you connect to server that does not suppot TLSv1 and only SSLv2 ?

**Comment by torkelo** [comment]
fixed with https://github.com/grafana/grafana/commit/49fdf8427a02b200588ecc07d7094e80550ecedc

hope it does not break it for others
