### ISSUE TITLE
Alerting: variables not interpolated when auto creating grafana 8 alert from a panel

### ISSUE THREAD

**Issue by domasx2** [grafana/grafana#37061]
**What happened**:

With `ng_alert` flag set, if you go to alerts tab in a panel and click "create alert from this panel", variables are not interpolated. 

**What you expected to happen**:

Variables should be interpolated to their current values.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by domasx2** [comment]
needs some discussion on how to handle `$__interval` and friends.
Some options:
1. Frontend interpolates. This is a problem if user then changes the interval, could result gaps in data being queried
2. Backend interpolates it. Seems reasonable, but not all alerting datasources currently can do it, notably prom/loki
3.  Do not allow saving rules that include variables. Easy, but least satisfying

**Comment by kylebrandt** [comment]
> needs some discussion on how to handle `$__interval` and friends.
> 1. Frontend interpolates. This is a problem if user then changes the interval, could result gaps in data being queried

I think 1 is a fair option. This still allows users to bootstrap their alert. And in the case of alerting where you end up with:
 1. Specific time windows for a query that are not changing once saved (unlike a dashboard where one zooms in and out)
 2. Additional options for the alerts run interval and FOR

So I think for users to have a better understanding of how the alert rule to behaves, it is generally better if these are set to numeric values instead of variable value.

I'm not sure if there are some data sources though that don't take this input anywhere in the query editor, and it has to come from the query options?  Even with @gabor breaking it down in https://github.com/grafana/grafana/issues/27469#issuecomment-878891684 I still find my self a bit confused (I think I would need to go through some data sources to get a hands on feeling for this to get it).

**Comment by domasx2** [comment]
Here's the potential problem I see: 

1. User has dashboard query `sum(foo [$__interval]) by (bar)` , and in the dashboard interval resolves to `1s`
2. User creates a alert rule out of it, query is interpolated by frontend and fixed to `sum(foo [1s]) by (bar)`
3. On the alert rule page, user doubles the time range without modifying max data points, effectively doubling the interval to 2 seconds. But for each step the query still only sums 1 second worth of data,  thus losing half of available data

Am I munsderstanding soemthing, or is this plausible?

**Comment by gabor** [comment]
@kylebrandt  wrote:
> I'm not sure if there are some data sources though that don't take this input anywhere in the query editor, and it has to come from the query options? Even with @gabor breaking it down in [#27469 (comment)](https://github.com/grafana/grafana/issues/27469#issuecomment-878891684) I still find my self a bit confused (I think I would need to go through some data sources to get a hands on feeling for this to get it).

the complicating factor is this:
most of our datasources (prometheus, etc.), only run "go" code when alerting happens. for from-dashboard queries they handle everything in the browser, and only proxy the request through the grafana-backend.
so their go-code assumes it is always called for alerting (old alerting), where the interval-value never arrives (only the value optionally chosen in the gui in `query_options/min_interval` arrives confusingly under the attribute-name "interval" in the query-json ). so these datasources always do the dance of:
- take the thing named "interval" from the query-JSON
- if not there, then try to take "interval" from the datasource-settings-JSON
- if any of these two exists, that is the minimium-interval-limit
- then based on the time-range calculate the final interval value
- if the final interval value is lower than the minimum-interval-limit, use minimum-interval-limit instead

so, if we want to do the from-frontend-interval solution:
- new-interval (and also old-interval) needs to send the real-final-from-frontend-interval into https://github.com/grafana/grafana-plugin-sdk-go/blob/main/backend/data.go#L58 for the datasource
- we will have to modify the datasource-plugins to modify their dance to be:
  1. read out this value from `DataQuery.Interval` and use it
  2. there is no step 2 😄 


btw. an alternative to the frontend-calculates solution is to make it alerting-system-on-backend-calculates. from the perspective of the datasource-plugins it looks the same as frontend-calculates.

(NOTE: i do not know what is better for the alerting-use-case, all i wrote is from the perspective of the datasource plugin)

phew, sorry for the long text. if anything is unclear, feel free to ask.

**Comment by domasx2** [comment]
Thanks for the explanation Gabor! 
We talked about this during the alerting weekly and decided that for now frontend should interpolate these at the point where alert rule is being created (from a panel), so alert rule queries will not contain any variables in the end. Will modify PR accordingly soon and add you as reviewer

**Comment by peterholmberg** [comment]
closed via #37201
