### ISSUE TITLE
Grafana 2.1.3-1 bug with `Null point mode`

### ISSUE THREAD

**Issue by dstranatic** [grafana/grafana#3707]
We're experiencing a bug in Grafana 2.1.3-1.
Whether one metric is empty, it doesn't draw graph for other metrics after it.
ie because currently `one server` has NULL topic leaders (as it's not finished starting yet) it will not draw lines for rest of servers in the graph.
Actually this only happens if `Null point mode` is set to "connected" or "null", setting it to "null as zero" will draw the missing lines.
A problem is that then we cannot distinguish between NULL (ie server is down) and zero.

**Comment by torkelo** [comment]
this is a requirement for stack rendering, it requires there be data points (non null) for the stacking to work.
