### ISSUE TITLE
Explore UI - updated PromQL / LogQL statement not being resolved correctly when 'Run Query' clicked 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#37099]
**What happened**:

(Step 1)  In Grafana Explore, run a PromQL or LogQL query, e.g. 

Query1 - PromQL example 
sum(count_over_time(container_network_transmit_errors_total{namespace="production"}[10m]))

Query2 - LogQL example 
sum(count_over_time({error_level="ERROR"}[10m])) 

Click 'Run Query' - the expected result is displayed.  

(Step 2)  Modify the query to remove the sum funciton `sum(` and `)` 

Query1 modified - 
count_over_time(container_network_transmit_errors_total{namespace="production"}[10m])

Query2 modified -
count_over_time({error_level="ERROR"}[10m]) 

Click 'Run Query' immediately after deleting the closing bracket `)`  - an error is returned.  

Error Query 1 - 
![image](https://user-images.githubusercontent.com/54800912/126634624-d632d0e8-414f-44eb-8cde-ba2cdee51804.png)

Error Query 2 - 
![Screenshot 2021-07-22 at 13 30 25](https://user-images.githubusercontent.com/54800912/126634653-62a73f1c-d2ad-47cd-bcbd-ae2c8761b740.png)

Json Query 1 - note the 'expression' still contains the closing bracket `)` 
```
{
  "state": "Error",
  "series": [],
  "annotations": [],
  "error": {
    "message": "\"invalid parameter \\\"query\\\": 1:87: parse error: unexpected right parenthesis ')'\"",
    "refId": "A",
    "status": 400,
    "statusText": ""
  },
  "request": {
    "app": "explore",
    "dashboardId": 0,
    "timezone": "browser",
    "startTime": 1626953875815,
    "interval": "2s",
    "intervalMs": 2000,
    "panelId": "Q-5831a900-a26c-4e9b-8383-1e4ed1d05c37-0",
    "targets": [
      {
        "refId": "A",
        "key": "Q-5831a900-a26c-4e9b-8383-1e4ed1d05c37-0",
        "exemplar": true,
        "expr": "count_over_time(container_network_transmit_errors_total{namespace=\"production\"}[10m]))"
      }
```

Json Query 2 - note the 'expression' still contains the closing bracket `)` 

```
{
  "state": "Error",
  "series": [],
  "request": {
    "app": "explore",
    "dashboardId": 0,
    "timezone": "browser",
    "startTime": 1626953406049,
    "interval": "2s",
    "intervalMs": 2000,
    "panelId": "Q-f912cbf1-f83e-4741-be69-c0ba1427eadf-0",
    "targets": [
      {
        "refId": "A",
        "key": "Q-f912cbf1-f83e-4741-be69-c0ba1427eadf-0",
        "expr": "count_over_time({error_level=\"ERROR\"}[10m]))"
      }
```

**What you expected to happen**:

No error returned after clicking on 'Run Query' 

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps above 

**Anything else we need to know?**: 

n/a 

**Environment**:
- Grafana version:  Grafana Cloud Hosted Grafana 8.0.6
- Data source type & version:  Grafana Cloud Hosted Prometheus and Hosted Loki  
- OS Grafana is installed on:  Grafana Cloud 
- User OS & Browser:  MacOS & Chrome 
- Grafana plugins:  n/a 
- Others: n/a

**Comment by aengusrooneygrafana** [comment]
Additional note:  

"Click 'Run Query' immediately after deleting the closing bracket ) - an error is returned" 

You need to hit 'Run Query' very quickly after deleting the closing bracket to reproduce this, in under a second.

**Comment by ifrost** [comment]
Could be related to the way we debounce running the query. One solution could be to cancel debouncing onBlur(). I had similar issues reported in the past.

**Comment by ifrost** [comment]
Possibly related to https://github.com/grafana/x-ray-datasource/issues/24

**Comment by gabor** [comment]
@ifrost yes it does sound like an issue with the `debounce` (though i did not debug the code to verify it). i think in general what we want is:
- the data-model is updated immediately without debounce (technically this means on every keypress)
  - (this might be technically challenging/impossible in some cases though) 
- (in panel, not explore) trigger query re-evaluation in a debounced way

your idea with not-debouncing onblur sounds reasonable, though i wonder if it could cause problems in some corner cases

@ivanahuckova  any ideas?

**Comment by ivanahuckova** [comment]
Since the last message, we have significantly change the code and switched query editor library. Moreover, I was not able to reproduce this anymore. So closing the issue.
