### ISSUE TITLE
Annotations don't work against Azure Monitor

### ISSUE THREAD

**Issue by mitulmk** [grafana/grafana#37121]
**What happened**:
I attempted to create Annotation off of Azure Monitor. The Service drop down doesn't populate.
![image](https://user-images.githubusercontent.com/22421034/126701437-1594c393-cccf-415f-83da-e1e298686d63.png)

**What you expected to happen**:
I expect the Service dropdown to show the various services (Azure Logs, etc.)

**How to reproduce it (as minimally and precisely as possible)**:
Dashboard Settings | Annotations | Choose Azure Monitor as data source

**Anything else we need to know?**:

**Environment**:
- Grafana version:
Enterprise (Free & unlicensed)v8.0.6 (68fe9e3431)

- Data source type & version:
- Azure Monitor

- OS Grafana is installed on:
- User OS & Browser: Windows, Edge
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
Investigating this - but I'm not too sure what's happening. It looks like the annotations controller is no longer receiving its datasource instance.

**Comment by joshhunt** [comment]
Torkel spotted this fix for this to get the editor to load again, but there are still some rough spots due to the UI being a bit older and not keeping up with our refactors and deprecations in 8.1.

Will continue work on this, mainly in the way of switching the annotations editor to be our react query editor.

**Comment by mitulmk** [comment]
Thanks @joshhunt. Can you log an issue for the continued work so we can follow it?

**Comment by mitulk** [comment]
Great, I see them working now: 
![image](https://user-images.githubusercontent.com/14897058/129625975-1feda5f6-2fec-41a4-885a-31f16aab0d4e.png)

**Comment by mitulk** [comment]
Created https://github.com/grafana/grafana/issues/38522 to track this work.
