### ISSUE TITLE
SigV4 Auth Details section appears even though `GF_AUTH_SIGV4_AUTH_ENABLED=false`

### ISSUE THREAD

**Issue by rohang98** [grafana/grafana#37120]
**What happened**:
The SigV4 Auth Details section appears for existing Prometheus data sources even though `GF_AUTH_SIGV4_AUTH_ENABLED=false`. However, the toggle for SigV4 auth does not appear, as shown in the image below, which is confusing for users.

![image](https://user-images.githubusercontent.com/24855547/126702323-247fcd2b-f1d1-45d1-b320-3243ad5cb909.png)

**What you expected to happen**:
When `GF_AUTH_SIGV4_AUTH_ENABLED=false` is set, the toggle for SigV4 auth should not appear **and** the SigV4 Auth Details section should not appear.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install any Grafana version (tested with 7.5.5 and 8.0.6).
2. Set `GF_AUTH_SIGV4_AUTH_ENABLED=true`.
3. Setup a Prometheus data source using SigV4 Auth.
4. Set `GF_AUTH_SIGV4_AUTH_ENABLED=false`.
5. Edit the existing Prometheus data source you created in step 3. The SigV4 toggle should be gone but the SigV4 Auth Details section still exists.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: MacOS & Chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
@grafana/backend-platform I think this is not Prometheus related issue, but generic error for all data sources supporting SigV4.
