### ISSUE TITLE
Public Snapshot Possible via API?

### ISSUE THREAD

**Issue by benyoungnz** [grafana/grafana#3713]
I am trying to via the API create a snapshot and use the url returned to then embed into another system.

I can create the snapshots ok, everything renders and displays fine but only when authenticated, otherwise the dashboard loads but a big orange "Unauthorized" toastr panel comes up when trying to push data into the graphs

Am i missing something here? 

In short: I am trying to replicate the "Share Dashboard > Snapshot Sharing > Local Snapshot" via the actual interface (which works perfectly anonymously)

Ideas?/Thanks in advance

FYI when creating the snapshot i am just passing the rows as queries  and any variable data with it, no embedded data, i note that when i create the snapshot via the interface it passes all of the data in the request to the snapshots interface, but if i request the dashboard via the api i simply get the structure back with queries and no data to replicate this

**Comment by torkelo** [comment]
if you create a snapshot via api you need to make sure all panels have snapshotData (that is metric data), this happens in the frontend when you make a snapshot, all panels save their visible data into the panel json. 

So it's if you need to automate the creation of a snapshot you need ways to capture the metric data and inject it into the panel json,

**Comment by benyoungnz** [comment]
FYI for those that are interested I managed to automate/get around this by doing the following

call /api/dashboards/db/{DashboardName} to get my base schema for the dashboard

foreach dashboard>rows  get each of the panels

with each panel

inject the snapshotData base array required for when we get the data

now get each "target" and fire a query to /api/datasources/proxy/2/query?epoch=ms&q={Query}
 
Note with the query you need to replace out any variables you have, in my case it was the servername but could be one or more - also replace the $interval and $timefilter based on your requirements

Once this is returned iterate the results>series and use the values to create an array as follows [value,timestamp] and put these into your Snapshot data array - at this point i also replaced the alias so the values had a nice name in the graph such as "server1 memory consumption"

Then pose this JSON off to the /api/snapshots endpoint where you will have your graphs snapshot URL returned

**Comment by stapelberg** [comment]
Thanks @benyoungnz for the description.

In case anyone is interested in reading a programmatic instead of a prose version of the algorithm, feel free to take a look at https://github.com/robustirc/benchmark/blob/093285fda4fa788830d3aa6f300635d2d7db628e/internal/grafana/snapshot.go

**Comment by AlexRudd** [comment]
Started making a stand-alone tool + Go lib for taking Grafana snapshots. Used a lot of @stapelberg 's code (thanks!!), will try and polish it a bit in the coming weeks but please feel free to contribute:

https://github.com/AlexRudd/snapshot_grafana

**Comment by utkarshcmu** [comment]
I have also create a CLI tool for Grafana which has a lot of features - https://github.com/utkarshcmu/wizzy 
https://utkarshcmu.github.io/wizzy-site/home/
May be I can add one more feature to add snapshots via CLI, should be quick!

**Comment by utkarshcmu** [comment]
It can create GIFs for you dashboards as well, if you want multiple dashboards using a single command.

**Comment by brismuth** [comment]
@torkelo any chance of this becoming a feature in the API in the future? How would you feel about a pull request adding it in? To clarify, I'm suggesting a single API endpoint to generate a public snapshot of a dashboard, similar to how the UI works.
