### ISSUE TITLE
Add annotation on timeseries is not work.

### ISSUE THREAD

**Issue by macropan** [grafana/grafana#37136]
**What happened**: cannot add annotation on timeseries, but graph(old) is ok.

**What you expected to happen**: want add annotation on new visualization like timeseries.

**How to reproduce it (as minimally and precisely as possible)**: just add annotation on timeseries.

**Anything else we need to know?**: tried to use CMD + Click, but not work.

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: sql, Azure China Log Analytics
- OS Grafana is installed on: docker on Centos7
- User OS & Browser: Mac, Edge & Chrome
- Grafana plugins: Nothing special
- Others: N/A

**Comment by pkolyvas** [comment]
Hi @macropan!

Grafana 8.0.x's time series panel doesn't include the ability to add annotations yet, we're shipping Time Series panel annotations in 8.1, which is in beta right now and should be generally available in early August.
