### ISSUE TITLE
Problem with more one datasources add in grafana with ansible

### ISSUE THREAD

**Issue by robbyq92** [grafana/grafana#37142]
Hi i try to create ansible playbook for deploy datasources grafana´s.

I follow
https://docs.ansible.com/ansible/latest/collections/community/general/influxdb_database_module.html 
and
https://docs.ansible.com/ansible/2.6/modules/list_of_database_modules.html?highlight=influxdb

I create the datasources:

i try this:
#grafana_datasources:
community.grafana.grafana_datasource:
  - name: "xxxxxxxxxx"
    type: "influxdb"
    access: "direct"
    url: "xxxxxxxx"
    basicAuth: true
    basicAuthUser: "xxxxxx"
    basicAuthPassword: "xxxxx"
    database: "xxxxxxx"
    user: "xxxxxxxx"
    password: xxxxxxxxxx
    access: server
    isDefault: false
    readOnly: false
    editable: true
    tls_skip_verify: false
    jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
     httpMode: POST

#grafana_datasources:
grafana_datasource:
  - name: "xxxxxxxxxx"
    type: "influxdb"
    access: "direct"
    url: "xxxxxxxx"
    basicAuth: true
    basicAuthUser: "xxxxxx"
    basicAuthPassword: "xxxxx"
    database: "xxxxxxx"
    user: "xxxxxxxx"
    password: xxxxxxxxxx
    access: server
    isDefault: false
    readOnly: false
    editable: true
    tls_skip_verify: false
    jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
     httpMode: POST

i have 5 databases in influx and i need to add all my databases to datasources grafana, if i add manual it work perfect.
maybe need add othe config for detect another databases? grafana_datasoruces 1, grafana_datasourcers 2?

#grafana_datasources 1
grafana_datasource:
  - name: "xxxxxxxxxx"
    type: "influxdb"
    access: "direct"
    url: "xxxxxxxx"
    basicAuth: true
    basicAuthUser: "xxxxxx"
    basicAuthPassword: "xxxxx"
    database: "xxxxxxx"
    user: "xxxxxxxx"
    password: xxxxxxxxxx
    access: server
    isDefault: false
    readOnly: false
    editable: true
    tls_skip_verify: false
    jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
     httpMode: POST

#grafana_datasources 2
grafana_datasource:
  - name: "xxxxxxxxxx"
    type: "influxdb"
    access: "direct"
    url: "xxxxxxxx"
    basicAuth: true
    basicAuthUser: "xxxxxx"
    basicAuthPassword: "xxxxx"
    database: "xxxxxxx"
    user: "xxxxxxxx"
    password: xxxxxxxxxx
    access: server
    isDefault: false
    readOnly: false
    editable: true
    tls_skip_verify: false
    jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false
     tlsSkipVerify: true
     httpMode: POST

Ansible playbook with -vvv it all ok

PLAY RECAP ***************************************************************************************************************************************************************************************************************************
xxxxxx               : ok=29   changed=0    unreachable=0    failed=0    skipped=25   rescued=0    ignored=0

**What happened**:
i deploy the grafana datasources, and i havent problem in ansible, but i have 5 db in influx and i need add all databases in datasourcers to grafana, but only add one
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.6 the last version
- Data source type & version: Influxdb 1.8.2
- OS Grafana is installed on: Redhat 8
- User OS & Browser: firefox, Red Hat 8
- Grafana plugins: nothing it only install last version 8.0.6
- Others:

ansible --version
ansible 2.9.22
  config file = /etc/ansible/ansible.cfg
  configured module search path = ['/home/ma00_m360/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python3.6/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 3.6.8 (default, Mar 18 2021, 08:58:41) [GCC 8.4.1 20200928 (Red Hat 8.4.1-1)]

**Comment by ivanahuckova** [comment]
Hello @robbyq92. Have you tried adding data source `uid`?   
```# <string> custom UID which can be used to reference this datasource in other parts of the configuration, if not specified will be generated automatically
    uid: my_unique_uid
```

Here is a documentation on provisioning: https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file

**Comment by robbyq92** [comment]
> 
> 
> Hello @robbyq92. Have you tried adding data source `uid`?
> 
> ```
>     uid: my_unique_uid
> ```
> 
> Here is a documentation on provisioning: https://grafana.com/docs/grafana/latest/administration/provisioning/#example-data-source-config-file

Thx for ansver Ivana.

I used this:
https://github.com/cloudalchemy/ansible-grafana/blob/master/tasks/datasources.yml

my config in datasources is:
- name: Ensure datasources exist (via API)
  grafana_datasource:
    grafana_url: "{{ grafana_api_url }}"
    grafana_user: "{{ grafana_security.admin_user }}"
    grafana_password: "{{ grafana_security.admin_password }}"
    name: "{{ item.name }}"
    url: "{{ item.url }}"
    ds_type: "{{ item.type }}"
    access: "{{ item.access | default(omit) }}"
    is_default: "{{ item.isDefault | default(omit) }}"
    basic_auth_user: "{{ item.basicAuthUser | default(omit) }}"
    basic_auth_password: "{{ item.basicAuthPassword | default(omit) }}"
  with_items: "{{ grafana_datasources }}"
  when: not grafana_use_provisioning

- name: Create/Update datasources file (provisioning)
  become: true
  copy:
    dest: "xxxxxx/datasources/ansible.yml"
    content: |
      apiVersion: 1
      deleteDatasources: []
      datasources:
      {{ grafana_datasources | to_nice_yaml }}
    backup: false
    owner: root
    group: grafana
    mode: 0640
  notify: restart grafana
  when: grafana_use_provisioning


maybe i have one parameter bad, and always used the last...

**Comment by robbyq92** [comment]
it finish:

in defaults/main.yml i put:

grafana_datasources:

    name: fist datasource
    name: second datasources

not:
grafana_datasources:

    name: first datasource
    grafana_datasources:
    name: second datasource

thx all :)
