### ISSUE TITLE
How can i download or get all the dashboard exist in DB

### ISSUE THREAD

**Issue by cchiremath** [grafana/grafana#3714]
Hi All,
 i tried getting dashboard from Grafana .it works fine for a single dashboard if we give name of a dashboard like below.

curl http://localhost:3000/api/dashboards/db/xyz-dashboard

however i would like to list all dashboard and get all of them in a loop as dashboard list will be huge hence i would be thankful to the forum to provide some support for the getting all the dashboard exists in DB.

regards,
Chandrashekhar

**Comment by torkelo** [comment]
http://docs.grafana.org/reference/http_api/#search-dashboards
