### ISSUE TITLE
Geomap panel can't zoom out completely in certain cases

### ISSUE THREAD

**Issue by pkolyvas** [grafana/grafana#37155]
### **What happened**
The new Geomap's maximum "zoomed out" level isn't adequate for certain panel sizes. I couldn't zoom out far enough to see the entire map. There may be no data in the hidden areas, but I'd like to set the view to the entire world.

![image (1)](https://user-images.githubusercontent.com/43178667/126781421-2849182f-0970-4297-a5c2-0973c7e59fa4.png)
  
### **What you expected to happen**:
That I could set the zoom level in the same way as the old WorldMap panel.

### **How to reproduce it (as minimally and precisely as possible)**:
Try to zoom out as far as possible on the Geomap panel. In many cases a bit of the world will still be obscured. 

- Grafana version: 8.1.0-beta2 
- User OS & Browser: MacOS/Chrome

**Comment by ryantxu** [comment]
I removed the "bug" label :)  someone worked very hard to make sure the map coords can not be duplicated.

Regardless we changed the default setting so it can zoom more in https://github.com/grafana/grafana/pull/37174 and will get merged into 8.1
