### ISSUE TITLE
Include current template variable values

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#37158]
Setting the "Include current template variable values" option, from what I read in this documentation https://grafana.com/docs/grafana/latest/linking/dashboard-links/, any matching templates in the linked dashboard are set to the values from the link

**What happened**:
I can see that all the variables are passed, even the ones that do not exist in the new dashboard, and so that do not match any variables. And again these variable are again passed to next linked dashboard and so on.

**What you expected to happen**:
That only the matching templates variables in the linked dashboard are passed and set to the values from the link

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Mysql
- OS Grafana is installed on: Windows 10
- User OS & Browser: windows 10 - Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
This works as intended, including all variables from the current dashboard

**Comment by torkelo** [comment]
If you want to include specific variables (for example only ones that exist in the target dashboard), then you can add those manually in the link URL

**Comment by DonatoD** [comment]
Ok. Thanks for the clarification.
But in this way, If I'm understanding correctly, you need to have a link for each dashboard (which is not the problem) moreover you cannot put together the links in a menu as for the dashboard link. Having several dashboard this could became a problem. Isn't it?
