### ISSUE TITLE
Geomap: ZOOM-Control + cannot be used if no title is given

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#37153]
Grafana 8.1.0-29318pre
on Windows Server 2019

ZOOM-Control + cannot be used if no title is given
without a title, it should be moved down by the height of the title

**Comment by ryantxu** [comment]
:thinking: Better than moving it, we need some way to get the events to the control....   currently all mouse events are captured by the header (transparent)
![image](https://user-images.githubusercontent.com/705951/126812410-c38a8ffe-a2be-4b3e-b292-a6b6d966fe3d.png)

**Comment by leeoniya** [comment]
`pointer-events: none` css can be useful for situations like this when you need click-through-ability. though here it would need to be applied to the header on-demand when moving to the zoom control bounding box location, jquery-style.

probably not a great general solution.

**Comment by UlrichThiess** [comment]
Look here: https://www.zoomsoft.de/grafana

As you could see, TrackMaps Panel has found a solution.

**Comment by leeoniya** [comment]
have they?

https://user-images.githubusercontent.com/43234/126818152-4dbdba72-d17f-4d84-9cca-917251d89a73.mp4

**Comment by ryantxu** [comment]
Looks like TrackMaps moves the zindex for eveything above the panel header -- that is fine if you keep the border, so there are still a couple pixels, but in geomap, we removed the small padding around everything.  I think the approach in:
https://github.com/grafana/grafana/pull/37169  will likely be good enough

**Comment by UlrichThiess** [comment]
Yes, I agree. # 37169 looks very nice.

Then can this be closed?
