### ISSUE TITLE
Issues related to the measurement units

### ISSUE THREAD

**Issue by sunil-jhamnani** [grafana/grafana#3715]
Hi,
I am using Grafana in docker. There is an option in Grafana to select the Unit for Left Y and Right Y. 
Now for example if I create a graph with data source using as graphite and selecting median of firstPaint metrics then it gives me the graph. Now the issue is if I change the Unit to minutes, days, or the worst case kilometres then also the graph shows me the values with that unit but the correct unit for firstPaint metrics is ms.

Is this correct?

**Comment by bergquist** [comment]
Yes.

Grafana does not know the actual unit in the datasource. So its up to the creator of dashboard to use what ever unit fits the data. It's just a label.
