### ISSUE TITLE
Login form displays password instead of logging in

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#37162]
**Steps to reproduce**:

Go on the login page (generally `http://localhost:3000/login`). Three ways to see the accessibility issue:

- Enter your email or username, enter your password, press enter expecting for the login to happen.
- Enter your email or username, enter your password, press tab expecting the focus to move to the "Log in" button, press enter expecting for the login to happen.
- Enter your email or username, enter your password, go back to the first input (e.g. by clicking on it), press enter expecting for the login to happen.

**Actual Result**:

The password gets revealed, the login does not happen.

**Expected Result**

The login should happen.

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

Maybe [3.2.2](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=322#on-focus).

**Environment**:
- Grafana version: v8.1.0-pre (2601a4dd6e)
- Data source type & version: macOS
- User OS & Browser: Google Chrome 92
- Others:

**Comment by tskarhed** [comment]
This has been fixed in #37444
