### ISSUE TITLE
Wrong annotations show on a given dashboard. Correct annotations show on page refresh.

### ISSUE THREAD

**Issue by pkolyvas** [grafana/grafana#37160]
### **What happened**:

- I created an annotations panel on my main (homepage) dashboard. 
- I clicked on an annotation which exists on another dashboard.
- Grafana loads that dashboard, but with the wrong annotations.
- When I refresh the page, the right annotation appears.

I load a dashboard with Annotations. It shows annotations on panels that were not created on that dashboard or those panels:
<img width="1205" alt="Screen Shot 2021-07-22 at 7 55 14 PM" src="https://user-images.githubusercontent.com/43178667/126791661-859dbd6d-829f-4ee6-88ff-86e1dd117d30.png">

When I refresh the page, the right annotation(s) load:
<img width="1213" alt="Screen Shot 2021-07-22 at 7 55 30 PM" src="https://user-images.githubusercontent.com/43178667/126791703-2dd7e3e4-ff9a-400b-95ae-0eecfde7900d.png">

### **What you expected to happen**:
- I select a dashboard, it should load the correct annotations.

**How to reproduce it (as minimally and precisely as possible)**:
- Create an annotation on a panel in a dashboard
- Leave and come back to that dashboard. Wrong annotations show.
- Refresh dashboard. Right annotations shown.

### **Anything else we need to know?**:

- Grafana version: 8.1.0-beta2
- Data source type & version: CloudWatch
- OS Grafana is installed on: Used docker (grafana/grafana:8.1.0-beta2)
- User OS & Browser: MacOS/Firefox

**Comment by ryantxu** [comment]
Be sure to test alerting support in both old and new alerting systems.  The icons and states are behaving odd also -- in the current state, I think it is a blocker for 8.1 release.  In particular the alert states are shown intermittently and without indication of state.

**Comment by mueslo** [comment]
This also happened to me now in Grafana 11.4... I tried for almost an hour to debug it until I found this and Ctrl+F4 refreshed the page.
