### ISSUE TITLE
undefined length for json object from elasticsearch datasource

### ISSUE THREAD

**Issue by dbental** [grafana/grafana#3716]
Hi,

im using grafana 2.6 and elastic 2.0,
when im trying to add the datasource to the graph panel i get this error "Cannot read property 'length' of undefined" and i cannot select any field, even after the error goes away i still cannot select any metric field.

i added an example below of the JSON object im using.

im new to grafana so im trying to understand is there any limitation on the object itself since i don't have this problem with kibana.

thanks !

{
  "_index": "baselineperfmon",
  "_type": "perfmon",
  "_id": "635882728851571667",
  "_score": null,
  "_ttl": 1209599640,
  "_source": {
    "PerfData": {
      "Memory#Available MBytes#": 832,
      "Memory Usage (MB)": 3263.48828125,
      "Memory#Pages/Sec#": 0,
      "Memory#Committed Bytes#": 1750122496,
      "Memory#Page Faults/Sec#": 2213.38330078125,
      "Paging File#% Usage#_Total": 26.009559631347656,
      "PhysicalDisk#% Disk Time#_Total": 1.2784587144851685,
      "PhysicalDisk#Avg Disk Bytes/Transfer#_Total": 7106.6826171875,
      "PhysicalDisk#Avg Disk Queue Length#_Total": 0.02557169832289219,
      "PhysicalDisk#Avg Disk Sec/Transfer#_Total": 0.00154491001740098,
      "PhysicalDisk#Avg Disk Sec/Read#_Total": 0.0006875001126900315,
      "PhysicalDisk#Avg Disk Sec/Write#_Total": 0.001588050159625709,
      "PhysicalDisk#Disk Transfers/Sec#_Total": 16.553512573242188,
      "Processor#% Processor Time#_Total": 9.460739135742188,
      "Processor#% Privileged Time#_Total": 4.793707847595215,
      "Processor#% User Time#_Total": 4.716390609741211,
      "Processor#interrupts/Sec#_Total": 6243.939453125
    },
    "Timestamp": "2016-01-13T09:08:05.1571667Z",
    "ServerName": "grg-pcp-15.mgt.888prod.local"
  },
  "fields": {
    "Timestamp": [
      1452676085157
    ]
  },
  "sort": [
    1452676085157
  ]
}

**Comment by torkelo** [comment]
graph panel only works with time series data right now, you will have to use the table panel for data like this right now.

**Comment by dbental** [comment]
Thanks for the response, but i fail to understand how is this related to how i visualize the data.

if i take the same object and save it without the PerfData like in the example below i can select the metrics, if i put the metrics inside PerfData i cannot select it, is there any depth limit on how you parse the data ?

{
"_index": "baselineperfmon",
"_type": "perfmon",
"_id": "635882728851571667",
"_score": null,
"_ttl": 1209599640,
"_source": {
"Memory#Available MBytes#": 832,
"Memory Usage (MB)": 3263.48828125,
"Memory#Pages/Sec#": 0,
"Memory#Committed Bytes#": 1750122496,
"Memory#Page Faults/Sec#": 2213.38330078125,
"Paging File#% Usage#_Total": 26.009559631347656,
"PhysicalDisk#% Disk Time#_Total": 1.2784587144851685,
"PhysicalDisk#Avg Disk Bytes/Transfer#_Total": 7106.6826171875,
"PhysicalDisk#Avg Disk Queue Length#_Total": 0.02557169832289219,
"PhysicalDisk#Avg Disk Sec/Transfer#_Total": 0.00154491001740098,
"PhysicalDisk#Avg Disk Sec/Read#_Total": 0.0006875001126900315,
"PhysicalDisk#Avg Disk Sec/Write#_Total": 0.001588050159625709,
"PhysicalDisk#Disk Transfers/Sec#_Total": 16.553512573242188,
"Processor#% Processor Time#_Total": 9.460739135742188,
"Processor#% Privileged Time#_Total": 4.793707847595215,
"Processor#% User Time#_Total": 4.716390609741211,
"Processor#interrupts/Sec#_Total": 6243.939453125
"Timestamp": "2016-01-13T09:08:05.1571667Z",
},
"fields": {
"Timestamp": [
1452676085157
]
},
"sort": [
1452676085157
]
}
