### ISSUE TITLE
Cannot import dashboard from ElasticSearch

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#3717]
Using 2.6.0. Importing kibana dashboards fail:

![image](https://cloud.githubusercontent.com/assets/1611494/12294680/2ee3a99a-b9f4-11e5-96af-198beb1f3e8f.png)

Connection test is fine.

I cannot import a manually exported json file either.

**Comment by torkelo** [comment]
there is no (have never been) any support for importing kibana dashboards, only dashboards from Grafana 1.x
