### ISSUE TITLE
Alias template variables

### ISSUE THREAD

**Issue by linar-jether** [grafana/grafana#3718]
The option to alias template variables would be a very nice to have feature, 
e.g. a template variable to allow to switch between different queries, but instead of writing it as #A or #H (the query id) we could alias it to {'Aggregated': '#A', 'Separated': '#H'} and allow the user to toggle between different queries without the need to edit the panel

**Comment by torkelo** [comment]
not sure about this :(

**Comment by linar-jether** [comment]
Sure? seems there is a need for something like that https://github.com/grafana/grafana/issues/3478

**Comment by torkelo** [comment]
I do not see the connection between key/value lookup and friendly alias names for query letters?

**Comment by linar-jether** [comment]
The query names was just an example, this issue is about friendly variable names to display 
![image](https://cloud.githubusercontent.com/assets/11908736/12296346/c0481414-ba0f-11e5-9fb6-7fa95b9c02ce.png)

**Comment by SatyaYuga** [comment]
+1

**Comment by gmdimitriz** [comment]
+1

**Comment by YeisonMelo** [comment]
+1
