### ISSUE TITLE
Changing default datasource breaks all dashboards with datasource:null

### ISSUE THREAD

**Issue by Thoro** [grafana/grafana#37193]
**What happened**:

When creating a panel with the default datasource, the datasource property is left at null and will not change.

Changing the default datasource in Grafana, breaks all existing panels that were created with the default datasource before the change.

**What you expected to happen**:

Save the datasource - even if it's the default datasouce.

**How to reproduce it (as minimally and precisely as possible)**:

- Have 2 datasource in Grafana
- Create a new dashboard and a new panel with the default datasource, check the JSON Model (Datasource is null).
- Edit the panel and change it to the secondary datasource, check the JSON Model (Datasource is filled).
- Edit the panel and change it back to the default datasource, check the JSON Model (Datasource is null)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: Prometheus & Graphite included with Grafana
- OS Grafana is installed on: Centos 7
- User OS & Browser: macOS 10.15.7 and Chrome 91.0.4472.114
- Grafana plugins: only Core
- Others:

There's an existing issue about this: https://github.com/grafana/grafana/issues/1919

**Comment by torkelo** [comment]
this is correct and by design, null indicates that the current default data source should be used. It enables you to change the default and have take effect on all panels using the default data source. 

But it's not ideal, we are working on improving parts of this https://github.com/grafana/grafana/issues/1664
