### ISSUE TITLE
Display zero line slightly thicker

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3721]
When having positive and negative Y axis, it would be a nice visual clue if the zero line would be slightly thicker.

For fully filled graphs, it might make sense to draw the 0 line _slightly_ too much to the left and/or right outside the actual graph. That way, one would have the same visual clue.

**Comment by torkelo** [comment]
you can use grid threshold (in line mode) to have a more prominent zero line 

![image](https://cloud.githubusercontent.com/assets/10999/12297152/146f0164-ba0c-11e5-86ec-efb2f75c37b6.png)

**Comment by RichiH** [comment]
Thanks!

**Comment by G-Pereira** [comment]
How can I do this on the current version?
