### ISSUE TITLE
Query exporter for Prometheus data source

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3722]
For debugging and creation of new graphs, it would be extremely helpful to be able to export the currently active query with all the template values filled in.

Optionally, having a link to go into the Prometheus Expression Browser with that PromQL query filled in would also be _very_ nice.

**Comment by torkelo** [comment]
export to what? 

In the prometheus query editor there a link to promdash

**Comment by RichiH** [comment]
While that's what I was looking for (sorry for that...) it does not fill in the template values.

I.e. it will send me to `irate(ifHCInOctets{fqdn=~"$ciscos",ifDescr=~"$cisco_interfaces"}[2m])*8` instead of filling in `$ciscos` and `$cisco_interfaces`.

**Comment by mtanda** [comment]
I fixed it at this PR, https://github.com/grafana/grafana/pull/3624.
It might be included latest build.

**Comment by RichiH** [comment]
Neat. Thanks :)
