### ISSUE TITLE
Docker container fails to build in main

### ISSUE THREAD

**Issue by dejapong** [grafana/grafana#37225]
**What happened**:

Building grafana using the Dockerfile.ubuntu fails with the following message: 

```
go: gopkg.in/macaron.v1@v1.4.0 (replaced by ./pkg/macaron): reading pkg/macaron/go.mod: open /src/grafana/pkg/macaron/go.mod: no such file or directory
```

**What you expected to happen**:
The container to build successfully

**How to reproduce it (as minimally and precisely as possible)**:
Clone grafana, and run this in the root directory, on the `main` branch:

`docker build -t grafana/grafana:dev --pull -f Dockerfile.ubuntu .`

**Anything else we need to know?**:

**Environment**:
- Grafana version: > 8.1.0-beta2 
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Hi @dejapong 

Thanks for reporting this. I was able to reproduce this on Ubuntu 20.04 and macOS 11.4:
* Docker version 20.10.7, build f0df350
* > 8.1.0-beta2 3ab9249f16
* `docker build -t grafana/grafana:dev --pull -f Dockerfile.ubuntu .`
results in:

```
------
 > [go-builder 4/9] RUN go mod verify:
#18 21.57 go: gopkg.in/macaron.v1@v1.4.0 (replaced by ./pkg/macaron): reading pkg/macaron/go.mod: open /src/grafana/pkg/macaron/go.mod: no such file or directory
------
executor failed running [/bin/sh -c go mod verify]: exit code: 1
```
