### ISSUE TITLE
Loki query error

### ISSUE THREAD

**Issue by QBH-insist** [grafana/grafana#37244]
**What happened**:
It was occoured error very frequently when choose range time manually

**What you expected to happen**:
I hope query normally when choose range time manually

**How to reproduce it (as minimally and precisely as possible)**:

1. **choose time “last 1 hour”, query result is  normally**
![image](https://user-images.githubusercontent.com/39401478/127119033-8305d7a0-b033-459c-b424-408637f37b8e.png)

2.**choose the same range time manually, query result is  wrong**
![image](https://user-images.githubusercontent.com/39401478/127120832-3c2b95b0-8d29-4094-81e3-f61b70bb26ee.png)
![image](https://user-images.githubusercontent.com/39401478/127120988-36546f9c-d04c-4ed6-88d0-fb56b76400d4.png)

**Anything else we need to know?**:
1. Tow same request
![image](https://user-images.githubusercontent.com/39401478/127121332-452d8e8c-33e1-4ac6-94c1-68e86b225e52.png)
normally
`http://ip:port/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22servicename%22%7D&start=1627369468000000000&end=1627373069000000000&step=2`
wrong
`http://ip:port//api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22servicename%22%7D&start=1627369468000000000&end=1627373069000000000&step=2`

2. grafana config
docker-compose.yml
` grafana:
    image: grafana/grafana
    container_name: lpg-grafana
    ports:
      - 5000:5000`

**Environment**:
- Grafana version: v8.0.6
- Data source type & version: Loki v2.2.1
- OS Grafana is installed on:  centos 7.9

**Comment by QBH-insist** [comment]
### Add Log Info
I check lgos where wrong occoured.
command: "docker logs --since 1m container id" 
**request**
![image](https://user-images.githubusercontent.com/39401478/127250569-de8476ba-4faf-468f-aca4-d99973e5b9ee.png)
`http://ip:port/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22test-service%22%7D&start=1627431986000000000&end=1627435587000000000&step=2`

**Granfana Log**
![image](https://user-images.githubusercontent.com/39401478/127250513-717b3219-0543-4c33-a386-d760e644223a.png)


**Loki Log**
![image](https://user-images.githubusercontent.com/39401478/127250338-a0c28b43-f9e2-4998-b395-ed795262ec4b.png)

**Comment by QBH-insist** [comment]
My problem has been solved
I set it 20s by mistake

> chunk_store_config:
max_look_back_period: 20s change to 0s

**Comment by olbo98** [comment]
Hi @QBH-insist! Nice to see that you were able to solve the issue! I'm closing this.
