### ISSUE TITLE
env var not overwriting configuration variable

### ISSUE THREAD

**Issue by bwilder** [grafana/grafana#3724]
Hi,
I'm attempting to use an environment variable to overwrite the database.password in grafana.ini, but I don't seem to be able to get things configured correctly to make this work. 

Grafana version: 2.0.2
OS: Ubuntu 14.04

Grafana.ini:
[database]
type = postgres
host = test.server:5432
name = grafana
user = grafana
password = secret

/etc/environment:
...
GR_DATABASE_PASSWORD=n3wpassw0rd

/etc/default/grafana-server:
...
GR_DATABASE_PASSWORD=n3wpassw0rd

I've tried restarting grafana-server and even restarting the box w/no joy.

Any thoughts? 
Thanks!

**Comment by torkelo** [comment]
try with GF instead of GR prefix

**Comment by bwilder** [comment]
wow, thanks for taking the time.

**Comment by torkelo** [comment]
try a newer version of grafana, your using a very oold one

**Comment by bwilder** [comment]
I figured, thanks.
