### ISSUE TITLE
Built for Raspian throws Excepton

### ISSUE THREAD

**Issue by dilgerma** [grafana/grafana#3725]
I´ve build grafana 2.6.0 for Raspian. 
When starting grafana-server I get 

template: index:55:20: executing "index" at <.PluginJs>: PluginJs is not a field of struct type *dtos.IndexViewData

I know you don´t support Raspbian but I have no idea what´s the problem. Any hints?

**Comment by oriste** [comment]
You can find a working package of Grafana 2.6.0 for Raspbian here: http://padcom13.blogspot.de/2015/12/influxdb-telegraf-and-grafana-on.html

**Comment by torkelo** [comment]
@dilgerma are you sure you tried to build 2.6 ? looks like you tried to build master
