### ISSUE TITLE
Specific routing for ngalerts is confusing

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#37267]
**What happened**:

This is the UI when editing notification policies using ngalerts and creating a specific routing:

![PS 2021-07-27 à 16 30 01](https://user-images.githubusercontent.com/2117580/127177185-2075fa5f-a6be-49d9-9d92-4d7a3444f502.png)

Having checkboxes for "Regex" and "Equal" on the right is confusing, what does checking them mean?

**What you expected to happen**:

A dropdown between the label and the value with clear options:

![43D43F37-B5A4-4167-B8EE-0C4FB12D3DCE_1_102_a](https://user-images.githubusercontent.com/2117580/127180389-0418f368-8bf7-4ad3-854d-4260af8e0d10.jpeg)

**How to reproduce it (as minimally and precisely as possible)**:

Have a running Grafana server with `GF_FEATURE_TOGGLES_ENABLE=ngalert` set, go to `/alerting/routes`, create a specific policy.

**Anything else we need to know?**:

**Environment**:
- Grafana version: `main.version=8.1.0-pre -X main.commit=c189851339`
- Data source type & version: Prometheus
- OS Grafana is installed on: macOS
- User OS & Browser: macOS, Chrome 92
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
I think we have this in in this issue https://github.com/grafana/grafana/issues/35745 ?
