### ISSUE TITLE
Assign tags to all graphs in a dashboard

### ISSUE THREAD

**Issue by hijklmno** [grafana/grafana#3726]
Hi guys, I am currently using only OpenTSDB as a datasource. Is it possible to have a dashboard-level tag filter which will apply to all my graphs? For example, each graph has a tag specifying the object's unique identifying number. I want to apply a tag filter on all graphs (objID=1234) without going to each graph and updating the tags.

Currently I have two dashboards, one of which that shows the average (as I have hundreds of these objects), and another which has the tags already put in place, and I just do a ctrl-f on the JSON, replace the objID and import new dashboard.

Thanks!

**Comment by utkarshcmu** [comment]
You can use templates for now for the whole dashboard. That is what I am using for Opentsdb dashboards. http://docs.grafana.org/datasources/opentsdb/

**Comment by torkelo** [comment]
you can use templating for something like this
