### ISSUE TITLE
In a table, formatting a timestamp field (pulled from Prometheus metric label value) as any form of "Date" unit yields NaN

### ISSUE THREAD

**Issue by lucas181** [grafana/grafana#37276]
**What happened**:
In a query to Prometheus that returns only a straight metric, I have two labels that include timestamps.  When I attempt to display these timestamps in a table, I am unable to set the unit to any type of date format. All six options cause the values to be displayed as "NaN".

**What you expected to happen**:
The timestamps should be correctly displayed as a date, as they would if the returned metric value was a timestamp.

**How to reproduce it (as minimally and precisely as possible)**:
The following is an example of the metric being scraped by Prometheus:
`my_uptime_metric{expires_at="1607137229000",launched_at="1607086829683",node_label="Launch_179"} 20322007.078515`

Create a table panel querying `my_uptime_metric` only. Create a unit override for either the `expires_at` or `launched_at` field ("Fields with Name") and select any of the "Date & Time" types.

**Anything else we need to know?**:
I have a suspicion that the NaN result may be due to the timestamp values being expressed as a string instead of a numeric type.  This data is being exposed to Prometheus through the node_exporter utility's textfile collector feature, and while the file node_exporter is reading from has the timestamps as a numeric format, it is applying the quotes to the timestamps.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Promtheus 2.4.3
- OS Grafana is installed on: Docker Alpine Image
- User OS & Browser: Windows 10, Chrome 92
- Grafana plugins:  grafana-clock-panel, flant-statusmap-panel
- Others:
![Grafana-table-timestamp-nan](https://user-images.githubusercontent.com/28738538/127207208-bc186f8d-ae97-4529-9227-b80be016a744.png)

**Comment by zuchka** [comment]
Hi @lucas181 

Thanks for making this issue. Follow up question: Can you share more details about prometheus.yaml and the textfile that you are scraping? I just tested this and I was able to scrape a file on disk with timestamps as values via node_exporter and then to convert in a table override:

![CleanShot 2021-07-27 at 13 35 56@2x](https://user-images.githubusercontent.com/37156449/127242755-aa9c4259-ddb2-492e-8b7c-e8475c199fb8.png)

![CleanShot 2021-07-27 at 13 36 15@2x](https://user-images.githubusercontent.com/37156449/127242780-642220bb-a236-4249-a815-c3d9088716d5.png)

Here were the steps I took: made a new directory and added a file called `myscript.prom`. added the following contents:

```
myscript_duration_seconds 10
myscript_last_run_seconds 1627425918000
```

I started node_exporter with the `--collector.textfile.directory=/path/to/scrape/directory` flag.

Queried prometheus for `myscript_last_run_seconds{}`. The timestamps in the table are then convertible.

Maybe this is a config issue?

**Comment by lucas181** [comment]
@zuchka - The issue itself isn't with the metric value, but timestamps contained within _label_ values.  The metrics you populated in the `myscript.prom` file don't contain such data.  Here's the example I posted in the initial report:

`my_uptime_metric{expires_at="1607137229000",launched_at="1607086829683",node_label="Launch_179"} 20322007.078515`

Can you try reproducing using this metric?

**Comment by zuchka** [comment]
Yep. You're right--was moving too fast and missed that the timestamps were labels. If I'm understanding [this response from Brian Brazil correctly](https://stackoverflow.com/questions/57723162/prometheus-label-comparison-with-vector-timestamp), then Prometheus itself always handles labels as "opaque strings". He suggests an interesting workaround...maybe that's of some help?

**Comment by zuchka** [comment]
A better approach now is to use the `convert field type` transformation inside the query editor, and not the unit overrides in the panel editor. I suspect this will convert a Prometheus label like `"1607137229000"` from a string type to a time type 👍 

https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#convert-field-type
