### ISSUE TITLE
Annotations - Href links in text not rendering a clickable link

### ISSUE THREAD

**Issue by stv-io** [grafana/grafana#37286]
**What happened**:
Href links in annotations text does not render a link anymore in grafana 8. This used to work in grafana 7. This is extremely useful when linking a Change log or information link as part of the annotation, used during deployments, for example.

Sending an annotation with the following payload:

```
{
  "tags":[ "release_name", "service_name", "deploy"],
  "text": "<a href=\"https://github.com\">release_name: deployed by Name Surname <name@exampleo></a>"
}
```

to the `/api/annotations` endpoint, gives a 200 OK, the annotation is received and stored, but does not display the blue text as a link, but just the raw text.

**What you expected to happen**:
Same as grafana 7, the annotation text is a clickable link as defined by the href

**How to reproduce it (as minimally and precisely as possible)**:

Testing this locally, on docker spin up 2 instances of grafana side by side:

`docker run -d -p 3008:3000 grafana/grafana:8.0.6`

`docker run -d -p 3007:3000 grafana/grafana:7.5.10`

For each instance login, generate an API key and a dashboard for each. For each dashboard create an annotation, from grafana datasource, query tags, filtering for tags `deploy`, save.

Then post the annotation using a simple `curl`

towards grafana 7
`
curl -sX POST -w '%{http_code}' -o post-annotation.json http://localhost:3007/api/annotations --data-binary '{ "tags":[ "release_name", "service_name", "deploy"], "text": "<a href=\"https://github.com\">release_name: deployed by Name Surname <name@example.com></a>" }' -H Content-Type:application/json -H 'Accept: application/json' -H 'Authorization: Bearer <API TOKEN>' && cat post-annotation.json
`

results in the correct link, and the text

![image](https://user-images.githubusercontent.com/6401588/127262019-31e83314-6a56-4a26-bc28-e888844d211d.png)

towards grafana 8
`
curl -sX POST -w '%{http_code}' -o post-annotation.json http://localhost:3008/api/annotations --data-binary '{ "tags":[ "release_name", "service_name", "deploy"], "text": "<a href=\"https://github.com\">release_name: deployed by Name Surname <name@exampleo></a>" }' -H Content-Type:application/json -H 'Accept: application/json' -H 'Authorization: Bearer <API TOKEN>' && cat post-annotation.json
`

results in just the text and no link

![image](https://user-images.githubusercontent.com/6401588/127261936-cd4416ab-8cfd-46af-b858-e031a8da1eb0.png)

**Anything else we need to know?**:

Idea originally taken from https://community.grafana.com/t/url-in-annotations/2051/5

**Environment**:

* Grafana version: v8.0.6 (68fe9e3431)
* OS Grafana is installed on: official docker image
* User OS & Browser: Mac Os Big Sur, Chrome
* Grafana plugins:
* Others:

**Comment by zuchka** [comment]
Hi @stv-io 
Thanks for making this issue. I did a quick test and you are right--href links are broken in annotations. However, this appears to be specific to the `time series` panel and not the grafana version. I was able to add an href link to the `Graph (old)` panel on Grafana 8 without error. That might be a possible workaround for the moment...

Adding complete parity between the old and new graph panels is currently [tracked in this issue](https://github.com/grafana/grafana/issues/30564). You will note that annotations are on that list, and that the issue has an 8.2.0 milestone. In other words, I expect this issue to get fixed very soon.

**Comment by stv-io** [comment]
Hey @zuchka thanks for the update, fair comments, will follow that issue and wait for the upcoming release. Given that in our case, clickable links are still being rolled out, we can probably wait for 8.2 and test with the "Graph (old)" panel as you suggested.

Keep up the amazing work ❤️
