### ISSUE TITLE
Bug: Format is missing on ElasticSearch datasource annotations queries

### ISSUE THREAD

**Issue by descrepes** [grafana/grafana#3728]
Hi,

I'm using ES 2.1.1 and grafana 2.6.0.

The ES request from annotations is generated like this :
```
{
  "fields":["time","_source"],
  "query":{
    "filtered":{
      "query":{
        "bool":{
          "should":[{
            "query_string":{
              "query":"service_description:(COMMIT)"
            }
          }]
        }
      },
      "filter":{
        "bool":{
          "must":[{
            "range":{
              "time":{
               "from":1452630675845,
               "to":1452717075845
              }
            }
          }]
        }
      }
    }
  },
  "size":10000
}
```

This request give the following error:
```
{
  "error" : {
    "root_cause" : [ {
      "type" : "parse_exception",
      "reason" : "failed to parse date field [1452630675845] with format [strict_date_optional_time||epoch_second]"
    } ],
    "type" : "search_phase_execution_exception",
    "reason" : "all shards failed",
    "phase" : "query",
    "grouped" : true,
    "failed_shards" : [ {
      "shard" : 0,
      "index" : "shinken-2016.01.13",
      "node" : "FsZ-WECiTAuOoJqM4c_MVg",
      "reason" : {
        "type" : "parse_exception",
        "reason" : "failed to parse date field [1452630675845] with format [strict_date_optional_time||epoch_second]",
        "caused_by" : {
          "type" : "illegal_argument_exception",
          "reason" : "Invalid format: \"1452630675845\" is malformed at \"630675845\""
        }
      }
    } ]
  },
  "status" : 400
}
```

When we specify the "format" of the date field in the request:
```
{
  "fields":["time","_source"],
  "query":{
    "filtered":{
      "query":{
        "bool":{
          "should":[{
            "query_string":{
              "query":"service_description:(COMMIT)"
            }
          }]
        }
      },
      "filter":{
        "bool":{
          "must":[{
            "range":{
              "time":{
               "from":1452630675845,
               "to":1452717075845,
               "format":"epoch_millis"
              }
            }
          }]
        }
      }
    }
  },
  "size":10000
}
```

We got the expected result.

Thx !

**Comment by torkelo** [comment]
make sure you have specified Elasticsearch version in datasource settings
![image](https://cloud.githubusercontent.com/assets/10999/12318157/6b72ba64-ba98-11e5-8199-c5674a3883e1.png)

**Comment by descrepes** [comment]
Hi,

It's already set to 2.x and it's working fine with tables but not with annotations.

Regards.

**Comment by spijet** [comment]
I tested this with tables, graph panels and annotations. As for graphs, Grafana sends this request in my case:
`{"search_type":"count","ignore_unavailable":true,"index":["logstash-2016.02.28","logstash-2016.02.29"]}
{"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"host:192.168.115.206"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1456695748924","lte":"1456717288924","format":"epoch_millis"}}}]}}}},"aggs":{"2":{"date_histogram":{"interval":"30s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":"1456695748924","max":"1456717288924"},"format":"epoch_millis"},"aggs":{}}}}`

And for annotations, it does:

`{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["logstash-2016.02.28","logstash-2016.02.29"]}
{"fields":["@timestamp","_source"],"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"host:192.168.115.206"}}]}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1456695782720,"to":1456717322720}}}]}}}},"size":10000}`
Which gives me this error in ElasticSearch:
`RemoteTransportException[[BMS01][192.168.115.165:9300][indices:data/read/search[phase/query]]]; nested: ElasticsearchParseException[failed to parse date field [1456696116509] with format [dateOptionalTime]]; nested: IllegalArgumentException[Invalid format: "1456696116509" is malformed at "6509"];`

If I change the annotation query to something like:
`{"search_type":"query_then_fetch","ignore_unavailable":true,"index":["logstash-2016.02.28","logstash-2016.02.29"]}
{"fields":["@timestamp","_source"],"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"host:192.168.115.206"}}]}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":1456584782720,"lte":1456696116509,"format":"epoch_millis"}}}]}}}},"size":10000}`
It works, at least with curl.

Using Grafana 2.6.0 and ElasticSearch 2.2.

**Comment by volter** [comment]
I guess that's missing around line 73 in datasource.js.

**Comment by volter** [comment]
https://github.com/grafana/grafana/pull/4472
