### ISSUE TITLE
[docs] broken links

### ISSUE THREAD

**Issue by matthewhelmke** [grafana/grafana#37280]
I found these while doing a local build of the cloud docs using Hugo. Here are the warnings. You should be able to find/fix them quickly and easily.

`WARN 2021/07/27 15:04:53 [en] REF_NOT_FOUND: Ref "../../field-options/configure-all-fields.md": "/home/matthew/GitRepos/website/content/docs/grafana/latest/panels/visualizations/table/table-field-options.md:15:26": page not found
WARN 2021/07/27 15:04:53 [en] REF_NOT_FOUND: Ref "../../field-options/configure-specific-fields.md": "/home/matthew/GitRepos/website/content/docs/grafana/latest/panels/visualizations/table/table-field-options.md:16:31": page not found
WARN 2021/07/27 15:04:54 [en] REF_NOT_FOUND: Ref "./standard-options.md": "/home/matthew/GitRepos/website/content/docs/grafana/next/panels/transformations/config-from-query.md:10:87": page not found
`

**Comment by zuchka** [comment]
@achatterjee-grafana FYI

**Comment by achatterjee-grafana** [comment]
@matthewhelmke - did you build complete?

**Comment by matthewhelmke** [comment]
@achatterjee-grafana I do a complete local build of grafana/website every time I prepare a PR larger than a trivial change.

**Comment by achatterjee-grafana** [comment]
I do too - and I saw them today as well. But the doc build is successful as these are warning.

I will check on them tomorrow.
