### ISSUE TITLE
How to remove the playlist?

### ISSUE THREAD

**Issue by grtfou** [grafana/grafana#37284]
**What happened**:
I don't know how to remove an exist playlist. [Doc](https://grafana.com/docs/grafana/latest/dashboards/playlist/#delete-a-playlist)
<img src="https://user-images.githubusercontent.com/1241272/127258383-2e6dcda2-a589-4653-909f-12da442a2318.png" width=50% height=50%>
<img src="https://user-images.githubusercontent.com/1241272/127258749-96c43c18-c02b-44b9-95a3-c863a2440f23.png" width=50% height=50%>

**What you expected to happen**:
Have a remove button.

**How to reproduce it (as minimally and precisely as possible)**:
Run a Grafana container on Docker.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6 (68fe9e3431)
- User OS & Browser: MacOS 11.2.1 & Chrome 92.0.4515.107
- Docker: Docker Engine - Community v20.10.7

**Comment by zuchka** [comment]
Hi @grtfou, thanks for making this issue. I could not find a remove option either. Escalating this to the frontend team 👍

**Comment by Mario-Hofstaetter** [comment]
For reference, Grafana 7 UI of Playlists:
![grafik](https://user-images.githubusercontent.com/33002073/127501196-de9cb491-2f82-418e-a650-7928d75e24a6.png)
