### ISSUE TITLE
Dashboard Edited/Saved notifications leak into other views

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#37306]
**What happened**:
When I:

In Tab A:
 - Open up a dashboard
 - Navigated to another page (in my case, `/alerting/routes` with ng alerting enabled)

In Tab B
 - Edit the dashboard I was viewing in Tab A and save

I see "Dashboard Saved" (or in another case "someone modified the dashboard" modal) in Tab A even though I am no longer on the dashboard that was edited.

**What you expected to happen**:
Only to get these notifications while actively in a dashboard.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: ddf5b65c51
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
I wonder if https://github.com/grafana/grafana/issues/36934 is related
