### ISSUE TITLE
[8.1.0-beta2] Login form toggles password visibility instead of submitting

### ISSUE THREAD

**Issue by sakjur** [grafana/grafana#37302]
**What happened**:

I try to log in to Grafana 8.1-beta2 and have the password field in focus (Safari + Chrome), pressing the enter key toggles the password visibility (*****<->admin) instead of submitting the form.

**What you expected to happen**:

The form should be submitted and the user logged in if the password is correct.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to the login page.
1. Fill out username, tab to fill out the password, press enter to submit.
1. Instead of submitting, the plaintext of the password is now visible on the screen.

**Anything else we need to know?**:

Tried to search for issues mentioning password and toggle to see if this was already fixed but didn't find anything, I haven't tried it on the main or 8.1.x branch.

**Environment**:
- Grafana version: 8.1.0-beta2
- Data source type & version: -
- OS Grafana is installed on: macOS
- User OS & Browser: macOS Big Sur, Safari and Chrome.
- Grafana plugins: -
- Others: -

**Comment by wbrowne** [comment]
Fixed in 8.1.0 stable with https://github.com/grafana/grafana/pull/37444
