### ISSUE TITLE
Access Time Range from javascript

### ISSUE THREAD

**Issue by h4wkmoon** [grafana/grafana#3731]
Hi, 
And first of all, thanks fr the beatutiful tool that is Grafana.
Sorry to ask that on Github. This is not a feature request, nor as issue. But, I don't to send a email 

I've discovered that in the text panel, when set to HTML, we can add javascript there. That's a wonderfull feature. With it, I can change the page background, and many many other cool stuff.
Now, I'd like to get some context information, such a the time range of the current page.
Do you know how to accomplish that, plz ?

EDIT : forgot to add "plz" and minor typos ;)

**Comment by The-Nik** [comment]
That's a very cool question. I also want to add some buttons zu choose a new time range. The timepicker handels with the variable temptime:

temptime.from.date = 2015-12-01
temptime.from.hour = 14
temptime.from.minute = 36
temptime.from.second = 49
temptime.from.millisecond = 655

temptime.to.date = 2015-12-01
temptime.to.hour = 14
temptime.to.minute = 36
temptime.to.second = 49
temptime.to.millisecond = 655

The function of the Apply-Button is: setAbsoluteTimeFilter(validate(temptime));dismiss();

So far I don't found a way, to manage this. Any other ideas?

- Niklas

**Comment by torkelo** [comment]
if you want access to time range you need to develop a custom panel plugin
