### ISSUE TITLE
Axis Right override not work in mysql datasource 

### ISSUE THREAD

**Issue by 1270514689** [grafana/grafana#37323]
Axis Right override not work in mysql datasource 

![捕获](https://user-images.githubusercontent.com/5121903/127424603-565c257b-394b-456c-abc8-9a80dcec52a8.JPG)

**Environment**:
- Grafana version: v8.1.0-beta2
- Data source type & version: mysql8.0
- Grafana plugins: time series

**Comment by zuchka** [comment]
Hi @1270514689,

I believe that you must first associate each y axes with a unit, and then you can map its location. This should be the case regardless of datasource:

![CleanShot 2021-07-29 at 09 31 11@2x](https://user-images.githubusercontent.com/37156449/127554583-843f59ed-4fd9-4ab0-8dc6-ecfe94a6178c.png)

If you have any more questions about using the new overrides, I would ask in https://community.grafana.com/. We can reopen this issue once there is more evidence that this is a bug 👍
