### ISSUE TITLE
v2.6 breaks regex in templating variable

### ISSUE THREAD

**Issue by hrchu** [grafana/grafana#3732]
I have the following variable setting in grafana v2.5 (with influxdb v0.8):

![image](https://cloud.githubusercontent.com/assets/3183314/12320903/31a98526-bae6-11e5-9850-b7a3824a963a.png)

where metric name is in form of  `servers.admin01.cpu.total.guest`.

After upgrade grafana to v2.6, the variable cannot have any value.

**Comment by torkelo** [comment]
works as before, there has been no change in this in v2.6 . 

you need to wrap the regex within forward slashes  `/servers\.(\S+)\./`

**Comment by hrchu** [comment]
Hi, I confirm that v2.5 can work without wrapping regex, and v2.6 only works with wrapping regex.

**Comment by torkelo** [comment]
ok, the reason it worked without slashes was due to a bug that was fixed in 2.6, as the placeholder text says it needs to be a regex string enclosed in `/`
