### ISSUE TITLE
epoch_millis problem when querying with elasticsearch version 2.x datasource

### ISSUE THREAD

**Issue by alexpsi** [grafana/grafana#3733]
I have elasticsearch-2.1.1 and grafana-2.6.0 installed, when using the version 2.x elasticsearch datasource I get an aggregation error at the graphs query. The problem is the inclusion of the format: epoch_millis parameter. 

When tried as a curl request with the format parameter removed it succeeds and the datasource works if I change the datasource to version 1.x

Thanks.

**Comment by torkelo** [comment]
it depends on when the index/mapping was created i think, if the index is old (before 2.x) it could be the reason. All I know is that for 2.x the epoch_millis should be used as format, it is what kibana uses.

**Comment by alexpsi** [comment]
I am running all this on vagrant so the index is brand new. Could you share a sample elasticsearch index template that will also contain the proper timestamp field?
