### ISSUE TITLE
[Google Cloud Monitoring Datasource] window 1d gives wrong window

### ISSUE THREAD

**Issue by AAverin** [grafana/grafana#37335]
**What happened**:
Using `window 1d` in Google Cloud MQL results in window starting at the time the page was refreshed instead of 00.00 as in Google Cloud Metrics Explorer

**What you expected to happen**:
`| window 1d` used in MQL query should result in window starting at the beginning of the day

**How to reproduce it (as minimally and precisely as possible)**:
Connect to Google Cloud data source, have some log-based metric to play with and try to build a query of "daily metric" where data should be displayed in a window from the beginning to end of the day.

**Anything else we need to know?**:
Using aforementioned window query directly in Google Cloud Metrics Explorer results in correct window that starts at the beginning of the day

**Environment**:
- Grafana version: v7.4.1 (07649d1313)
- Data source type & version: `Google Cloud Monitoring`
- OS Grafana is installed on: `Ubuntu`
- User OS & Browser: `Chrome`
- Grafana plugins:
- Others:

**Comment by andresmgot** [comment]
Hi,

This can be controlled in the time picker, for example, if you want to start the query at 00:00 you can get that simply selecting a day from the date picker:

![Screenshot from 2021-11-24 13-29-04](https://user-images.githubusercontent.com/4025665/143238824-a7745220-54df-4936-bda5-81a09c07dd2d.png)

About automatically select the query period, this is a feature request that we can’t see prioritising any time in the near future. If this is a feature that the community still wants, please re-open this in discussions and we may consider it further if it gets more traction. Thanks!
