### ISSUE TITLE
"General" listed as destination folder sometimes while saving dashboards if the environment has 2000+ folders

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#37348]
**What happened**:
We have large Grafana installation with nearly 12,000 dashboards, since our Grafana v8 upgraded, "General" folder became invisible. This caused a major issue to us: since we have a dozen users are admin, so they have edit permission to "General" folder, a pre-existing issue that when admin review user dashboard and save the dashboard, sometimes it will be saved under "General" even without changing dashboard folder destination(this probably warrant another issue if not existed already) and often admins wouldn't even realize. When this happens, since we can't see General folder anymore, we don't even know what's in the General folder.

**What you expected to happen**:
1. General Folder should still be viewable/editable by admin
2. Saving an existing dashboard from regular folder by admin should not cause the dashboard be saved under General folder.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6
- Data source type & version: Metrictank
- OS Grafana is installed on:
- User OS & Browser: RHEL 7.6 / Chrome
- Grafana plugins:
- Others:

**Comment by shalstea** [comment]
When we open a dashboard, in the Settings the folder is automatically set to General overriding the original setting.  It doesn't seem to happen every singe time.  But if it does and we save it, then the dashboard is moved.

**Comment by fyang13** [comment]
I think I find out why the dashboard get saved into General folder sometimes. When admin go to a dashboard setting, a request to query of dashboard folders that the user has admin access will be sent to Grafana, but each request are limit to 1000 entries, and it only go through 2 iteration:

https://grafana.prod.bloomberg.com/api/search?query=&type=dash-folder&permission=Edit

So if the dashboard are currently in the folder not in the first 2000 folder list, it will be saved under General folder. That's why we don't see this all the time, if the dashboard are under folder starting with letter A-N in our case, it won't have problem, but for any others, it will be saved under General since it never show up in the list.

**Comment by dsotirakis** [comment]
Hello @fyang13, still trying to reproduce that. Is it only happening with >2000 folders?

**Comment by marefr** [comment]
@dsotirakis temporarily changing the limit to something small (code) I think should allow you to reproduce it without creating > 2000 folders. Have you tried this?

**Comment by dsotirakis** [comment]
Will try changing [this](https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/dashboard.go#L326) and try again.

**Comment by dsotirakis** [comment]
@fyang13, could you please set `limit=xxxx` as a query parameter in `/search` to check if that solves the issue for now? Meanwhile we'll try to solve it for the next minor version.

**Comment by fyang13** [comment]
Yes, increasing limit will make General folder show up(btw, max limit is 5000). However, the source of the problem still exist, and more importantly this won't help the major issue it's causing dashboard in the folders above 2000th by alphabetical will be saved under "General" whenever it's being updated by an admin.
I think the code will have to be updated either make each page to be higher than 1000, or iterate all the pages rather than just iterate the page twice.

**Comment by dsotirakis** [comment]
@fyang13 the page follows the limit, so if we set the limit to be higher than 1000, then the page will be too. I think the actual problem lies in the pages. Iterating the pages is an issue as I can see. I think we shouldn't have a limit there and we shouldn't have a limit at all when trying to save a dashboard, so even if you cannot see a folder due to the limit, you would be able to save in that folder anyway. Working on it, we can always jump on a call if you feel like it.
