### ISSUE TITLE
Time series left Y-axis values cut

### ISSUE THREAD

**Issue by terokinnunen** [grafana/grafana#37347]
**What happened**:
Some left Y axis values are cut when using auto for Axis - Width setting.

**What you expected to happen**:
Auto width adjusts the width so that all Y-axis values are fully displayed.

**How to reproduce it (as minimally and precisely as possible)**:
- Add panel - Add an empty panel
- Select/keep "Time series" panel
- Data source "-- Grafana -- " / Random Walk
- Set Standard options: Min to -1, Max to 1
- Adjust panel height if needed to include intermediate Y-axis values (like 0.500) that get cut

![image](https://user-images.githubusercontent.com/579368/127482102-99150b32-74c7-4bda-baaf-56f361c69dc6.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6 (68fe9e3431) (Online Grafana sandbox). Also with master Docker image v8.1.0-29852pre (08a73a5291)
- Data source type & version: Any
- OS Grafana is installed on: Online sandbox, Alpine Docker image
- User OS & Browser: Windows 10/Edge. Also Linux/Firefox
- Grafana plugins: -
- Others:

**Comment by zuchka** [comment]
Hi @terokinnunen 

Thanks for making this issue. I was also able to reproduce this [on our online sandbox](https://play.grafana.org/d/qwYVy9Znz/axis-cutoff?orgId=1) 👍

**Comment by leeoniya** [comment]
let's see what's going on here...
