### ISSUE TITLE
Is this a bug? alias doesn't appear

### ISSUE THREAD

**Issue by pizzacpe23** [grafana/grafana#3735]
![2016-01-14_175115](https://cloud.githubusercontent.com/assets/16382483/12322657/0c5f6a7c-bae8-11e5-8779-16d96dedc40e.png)

Matric #A is green
Matric #B is yellow

I made this graph to show a problem of using alias function when I use aliasByNode with Matric #B. It does not appear alias name like Matric #A. It doesn't have any problem with other alias functions. Hope this help you.

**Comment by torkelo** [comment]
this might be a graphite issue, whats the response from graphite? (open chrome dev tools / network tab, look at the response from the /render call)
