### ISSUE TITLE
Error "plugin failed" with latest build 3.0.0-pre1

### ISSUE THREAD

**Issue by commarla** [grafana/grafana#3737]
Hi,

I am trying the last build and got this error just after the login : 
![2016-01-14 12_39_31-grafana - home](https://cloud.githubusercontent.com/assets/4509360/12323529/3b3952da-babc-11e5-94fe-66a6d8bbdb6c.png)

Grafana version: 3.0.0-pre1, commit: v2.6.0+334-g8ff48c1, build date: 2016-01-13 15:51:47

Regards,

**Comment by torkelo** [comment]
sorry, will fix soon

**Comment by torkelo** [comment]
should be fixed in latest build,
