### ISSUE TITLE
switch appInsights to logs, the data links does not work

### ISSUE THREAD

**Issue by macropan** [grafana/grafana#37384]
**What happened**: due to the appinsights read only, I switch it to logs, but data links does not work, they go to the Azure Portal by default. and ${__data.fields}﻿ still not work too.
![WX20210730-111232](https://user-images.githubusercontent.com/6326663/127594516-6f00e60e-e4b9-4b54-9278-52ee68c06e95.png)
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 

- Grafana version: 8.0.6
- Data source type & version: Azure China
- OS Grafana is installed on: Docker
- User OS & Browser: Edge
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
See https://github.com/grafana/grafana/issues/32007#issuecomment-814336439 - this is a platform limitation of Grafana where links supplied by the data source will override what's specified in the panel config.

Fortunately there's a work around, to specify the links in Overrides. See the issue thread for more details ^^
