### ISSUE TITLE
Docs feedback: /datasources/cloudwatch.md

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#37381]
Under https://grafana.com/docs/grafana/latest/datasources/cloudwatch/#iam-roles

> Providing you have chosen the AWS SDK Default authentication method, and your Grafana server is running on AWS, you can use IAM Roles to handle authentication **automically**.

fix "automically" to automatically?

**Comment by achatterjee-grafana** [comment]
Fixed in https://github.com/grafana/grafana/pull/37697
