### ISSUE TITLE
UX: Fix light theme button color

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#3738]
Standard UX behaviour (no source to cite other than instinct!) would be for the Apply button in the Time range picker to start grey, as it does, but if the user overtypes the values (i.e. they are changed from what they were when the Time range dialog opened) the Apply button should change colour to indicate that it is now clickable by the user in order to activate the change made. 

![image](https://cloud.githubusercontent.com/assets/3671582/12326654/1487389c-baca-11e5-986f-3cd8d05853ae.png)

After changing the value(s), the button would change apperance (but not look lame like this photoshop-hack job): 
![image](https://cloud.githubusercontent.com/assets/3671582/12326709/55a6ea2a-baca-11e5-8292-2cf6cf89c717.png)

**Comment by torkelo** [comment]
hm... agree that the default state of that button looks disabled in the white theme (looks ok in dark theme)

thoughts @mattttt?

**Comment by torkelo** [comment]
@mattttt & @bulletfactory Is just me but does the btn-inverse button look a bit like a disabled button on the light theme?
