### ISSUE TITLE
Cloudwatch Cross account Permission Error in Grafana 8.x

### ISSUE THREAD

**Issue by mitchellharvey97** [grafana/grafana#37383]
When Using Cloudwatch log explorer, if Grafana doesn't have permission to assume the role, the user is displayed an "An unexpected error happened" error rather than something meaningful.

![image](https://user-images.githubusercontent.com/7417605/127578127-4be5b69f-eead-4ac9-9cbe-8fa3f6f7dd1a.png)

Previous versions of Grafana would provide permission denied error or similar.

Reproduction Steps:

Run a new install in docker

`docker run -d -p 3000:3000 --env AWS_ACCESS_KEY_ID="ACCESS_KEY_ID_HERE" --env AWS_SECRET_ACCESS_KEY="ACCESS_KEY_HERE --env AWS_SESSION_TOKEN="SESION_TOKEN_HERE" grafana/grafana:8.0.6`

Navigate to `http://localhost:3000/datasources/new` and add a new Datasource of "Cloudwatch"
Use AWS SDK Default and an Assume Role ARN to a role that your local user currently does not have access to, and create a new data source

![image](https://user-images.githubusercontent.com/7417605/127578490-81c1b6b8-2c66-434f-8150-3107365c168e.png)

Navigate to http://localhost:3000/explore and select the new Datasource, and select Cloudwatch Logs
![image](https://user-images.githubusercontent.com/7417605/127578549-b5698c1a-cd64-4508-a419-29503ec1b4f2.png)

The Error shown at the top of this ticket will then be thrown. "An unexpected error happened"

To prove this is a permission denied error, Log into your AWS account and edit the trust relationship on the IAM policy to allow access. I.e 
`{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Principal": {
        "AWS": "arn:aws:iam::LOCAL_GRFANA_USER_ACCOUNT_ID:root"
      },
      "Action": "sts:AssumeRole"
    }
  ]
} `

and then navigate to the explore Cloudwatch logs which should successfully work.

This behavior was first noticed on our proper deployment via AWS Fargate and I was able to successfully replicate it locally in a brand new environment, so I can't see a way that it is any specific config that I have causing the issues. 

This is replicated in Chrome & Safari on MacOsx as well as a few Windows-based browsers as well (Not sure specifics on browsers etc)

**Comment by zuchka** [comment]
Hi @mitchellharvey97 

Thanks so much for creating this issue. Question, would you say your issue is related to https://github.com/grafana/grafana/issues/36139?

**Comment by mitchellharvey97** [comment]
Hey @zuchka , I am not convinced it is the exact same, but the comment you made https://github.com/grafana/grafana/issues/36139#issuecomment-867935719 does indicate that you had come across the react.js error. I can't see the issue from support linked (dead link or no permissions) to be able to confirm if it is the same though.

**Comment by zuchka** [comment]
thanks, @mitchellharvey97 -- the more info the better 😎

**Comment by zuchka** [comment]
@mitchellharvey97 are you still experiencing this on versions newer than `8.0.6`

thx 👍

**Comment by mitchellharvey97** [comment]
Hey @zuchka I no longer actively use grafana daily so not sure if newer versions address this issue better - but a quick test looks like it now provides an error popup rather than a website crash so I would say that is better.
