### ISSUE TITLE
Panel Plugin - Cesium Globe

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#3739]
This is a stub to begin a Cesium plugin by gilgamezh

https://twitter.com/gilgamezh/status/687643063267758082

![download](https://cloud.githubusercontent.com/assets/2886187/12327170/e66352a6-baa2-11e5-9ba8-e97b20ceb703.png)
![download-1](https://cloud.githubusercontent.com/assets/2886187/12327171/e664212c-baa2-11e5-8240-a7ec1a00ab6a.png)

There isnt any official documentation yet, but we're happy to help it along.

**Comment by gilgamezh** [comment]
s/gilgamezh/@luciotorre  ;)

https://github.com/luciotorre/grafana/tree/add_cesium

**Comment by gilgamezh** [comment]
thanks!! 

First question: Whats its the way to include .css and .js files ? currently we are doing it:

```
+++ b/public/views/index.html
@@ -17,6 +17,12 @@
     <link rel="icon" type="image/png" href="[[.AppSubUrl]]/public/img/fav32.png">
                <base href="[[.AppSubUrl]]/" />
 
+    <style>
+      @import url(http://cesiumjs.org/Cesium/Build/Cesium/Widgets/widgets.css);
+    </style>
+    <script src="http://cesiumjs.org/Cesium/Build/Cesium/Cesium.js"></script>
+
+
```

**Comment by bergquist** [comment]
They both have to be loaded as modules in https://github.com/luciotorre/grafana/blob/add_cesium/public/app/panels/globe/module.js Unfortunately we don’t support loading custom CSS files at the moment. But I guess we can enable that. let me get back to you :)

**Comment by gilgamezh** [comment]
@bergquist ok. thanks! :rocket:

**Comment by gilgamezh** [comment]
related to #3185

**Comment by bergquist** [comment]
@gilgamezh Sorry for not responding quickly to this issue. But we are soon about to get beta 3.0 out and then it should be much easier to integrated this plugins. Cesium is such a large library that it would be much better of with some build steps which we will make easier in the beta. 

Ill get back to this!

**Comment by gilgamezh** [comment]
@bergquist no problem! I'm following the new release ;) thanks!

**Comment by bergquist** [comment]
@gilgamezh @peregrinogris awesome!
