### ISSUE TITLE
Expand relative time options to include until, example from=1h  until=10m

### ISSUE THREAD

**Issue by jpbarron** [grafana/grafana#374]
It would be super awesome if there was a way to enable relative time picker options for Show the Past (which works currently) and Until (not an option I can find).

![image](https://cloud.githubusercontent.com/assets/7452753/2845930/fc607ee6-d09b-11e3-8ceb-42935f22f9f7.png)

Other than using the exact time frame, 'now' is the only other option available.

I'd like to set graphs up to pull the last 12 hours until 10 minutes ago for example.  this would remove some graph artifacts from metrics on 5 minute intervals and due to memcache settings that can add a few more minutes to the lag.  

If some but not all metrics have come in for a wildcard or sumSeries function the end of the graph has a fall off artifact.

![image](https://cloud.githubusercontent.com/assets/7452753/2845843/1c1b8e66-d09b-11e3-8abd-44cc1d149a9f.png)

Graphite's built in dashboard time picker for Relative Time Range has the option to put in both From and Until as relative values.

![image](https://cloud.githubusercontent.com/assets/7452753/2845906/bfe64a40-d09b-11e3-8d7c-afbb2c9e332a.png)

Thanks!

**Comment by torkelo** [comment]
Implemented in now in master, https://github.com/grafana/grafana/commit/b940f4a97d7a849371bfb5345c1e8617140f26c7

![image](https://cloud.githubusercontent.com/assets/10999/5891598/b1ac1378-a49f-11e4-9d5a-a13ed8b8c7f2.png)

**Comment by txaj** [comment]
you da real mvp @torkelo thanks !
