### ISSUE TITLE
Annotation "Enabled" button disappear after Grafana v8.0.6 upgrade

### ISSUE THREAD

**Issue by fyang13** [grafana/grafana#37422]
**What happened**:
After Grafana upgraded from v7.5.3 to v8.0.6, the “Enabled” button in annotation disappear, and the user dashboard with annotation enabled does not enable automatically upon load, user have to toggle the “Enabled” switch on top of the dashboard to make the annotation show up. The state of annotation upon dashboard load seems now get saved when dashboard is saved, based on whether the annotation is enabled or not at the time.
Is this an intended change? 

**What you expected to happen**:
Behavior change like this should be documented in release notes if it's intended.

**How to reproduce it (as minimally and precisely as possible)**:
Go to Dashboard setting -> Annotation setting, "Enabled" switch is gone, it used to be in front of "Hidden" switch, as shown [here]([https://grafana.com/static/img/docs/v53/annotation_tag_filter_variable.png])

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6
- Data source type & version:
- OS Grafana is installed on: RHEL 7.6
- User OS & Browser: Chrome, Safari
- Grafana plugins:
- Others:

**Comment by KBac** [comment]
Actually it seems that the state of annotation is not saved with the dashboard. When I enable annotations, save dashboard and reload it, I see that annotations are “enabled” (switch is on) but there are no annotations on charts. When I toggle the switch off/on again, annotations appear on charts.
