### ISSUE TITLE
Cloudwatch not showing list of items for dimensions

### ISSUE THREAD

**Issue by rtkmhart** [grafana/grafana#3742]
Just installed Grafana 2.6, setup the cloudwatch data source. Awesome work, very excited to see this. 

Most of the metrics work fine, however there is one that I can't get working. Specifically if I select the metric "AWS/AutoScaling" and pick any metric, then in Dimension pick AutoScaleGroupName, the dropdown shows nothing (see screenshot). I can however pull CPU utilization for an autoscale group using AWS/EC2 CPUUtlization.
![screen shot 2016-01-14 at 10 13 01](https://cloud.githubusercontent.com/assets/2601414/12328036/9955ae28-baa7-11e5-8cda-0cb1a5f75ae8.png)

Adding in the ASG name manually for one that I know exists doesn't provide any data. There's nothing in the grafana log to indicate why. 

Thoughts?

**Comment by torkelo** [comment]
not sure, what is CloudWatch returning? If it's blank its probably because cloudwatch is not returning anything

**Comment by rtkmhart** [comment]
AFAIK it's returning nothing at all, there's nothing in the drop down. How can I debug this in Grafana or on the server?

**Comment by mtanda** [comment]
Please check using awscli.
```
aws cloudwatch list-metrics --region us-west-2 --output json
```

If the output includes AWS/AutoScaling, it should be appeared in Grafana.

**Comment by rtkmhart** [comment]
Thank you, that is it, I did not have metrics enabled on the ASG. 

I expected that if the Metric showed in Grafana it would have data, but it appears the metric must be prepopulated? 

Thanks.

**Comment by mtanda** [comment]
If the CloudWatch doesn't have metric data, the "list-metrics" doesn't return all metrics.
There is some case, it doesn't have metric data (due to no metric data report).

https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/as-metricscollected.html
> If you disable group metrics, Auto Scaling does not send any group metrics data to CloudWatch.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/elb-metricscollected.html
>  If there are no requests flowing through the load balancer or no data for a metric, the metric is not reported.
