### ISSUE TITLE
Grafana does not reload its TLS server certificate data 

### ISSUE THREAD

**Issue by richardjudgeman** [grafana/grafana#37433]
**What happened**:
After the start, the Grafana pod reads the PKI information from the file(s) configured in grafana.ini. The running Grafana pod does not seem to monitor the update of these files and so the browser accessing the Grafana UI reports an expired certificate even when the information in the files (e.g. /etc/grafana/pki/tls.crt) contains a refreshed and valid certificate data.

**What you expected to happen**:
Grafana should regularly check the files storing the TLS cert and key for updates and utilize the updated data on the fly, i.e. without the need to restart the Grafana pod. 

**How to reproduce it (as minimally and precisely as possible)**:
Configure Grafana with a certificate that has a short validity of e.g. 2h. Start the Grafana pod and update the file storing the TLS cert (e.g. /etc/grafana/pki/tls.crt) with a refreshed certificate data (validity e.g. 10h) while keeping the Grafana pod running. Observe the PKI files in the Grafana pod's namespace being updated with the new certificate data (and the new validity) while the browser connecting to the Grafana UI will report an expired certificate 2h after the pod start, i.e. when the cert loaded at the start of the Grafana pod has expired.

**Anything else we need to know?**:
Jetstack cert-manager and K8S Secret are useful in automating the test case

**Environment**:
- Grafana version: 7.4.1-ubuntu
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Microsoft Edge
- Others: TLS certificate and key supplied from cert-manager 1.4.0

**Comment by ying-jeanne** [comment]
The current design is we load config.ini just one time at the server start time, It is a good idea to make it updatable on the fly without restart the server, The ticket should be a feature request.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). 

What does moving the issue mean? 

Firstly, it means we're keeping it open as a feature request. In moving this issue to our [GitHub Discussions](https://github.com/grafana/grafana/discussions) board, it will retain all the comments and labelling already part of the issue. 

Secondly, it signals we have no immediate plans to implement it, but would like to continue to engage with the idea or request. We hope to use the discussion thread to continue building use cases and evidence that can help us prioritize it later on down the road. It can also help everyone, as part of the Grafana community, have an opportunity to pick up issues for contribution which are clearly defined. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!
