### ISSUE TITLE
Panel menu not closes 

### ISSUE THREAD

**Issue by baur** [grafana/grafana#37436]
**What happened**:

Panel menu not closes. I can open them all at same time

![image](https://user-images.githubusercontent.com/2898361/127819482-dd73d3c6-a5c6-4ef4-adef-10ffea5c8eab.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-beta2 (147704deb9) (same 8.0.x)
- Data source type & version: 
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: 
- Others:

**Comment by tskarhed** [comment]
Can replicate. This only happens when you click the panel titles in sequence. Clicking outside of any of them causes them all to close.
