### ISSUE TITLE
ngalert notification is flapping between Firing and Resolved

### ISSUE THREAD

**Issue by tetsuya28** [grafana/grafana#37461]
**What happened**:
ngalert is flapping

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Setting alert for kubernetes cluster network usage with `Reduce`, `Math` expressions.
<img width="500" alt="screen_shot 2021-08-03 10 19 05" src="https://user-images.githubusercontent.com/11973270/127943170-1e81b70b-ccb7-4a77-9adc-3e19c03cff1b.png">

- Then, the alert is fired.
<img width="190" alt="screen_shot 2021-08-03 10 10 03" src="https://user-images.githubusercontent.com/11973270/127942904-37e969e0-5ae8-4f60-91e8-7a5d6ae7f6c0.png">

- But, slack notification is flapping with `Firing` and `Resolved` every 70s for the same alert
  - Every notification shows this alert starts `8/3 01:03:49`, and Resolved in 70s.
  - In Grafana console, it seems to be continued this alert from `8/3 01:03:49`, but never resolved it.
<img width="561" alt="screen_shot 2021-08-03 10 09 07" src="https://user-images.githubusercontent.com/11973270/127942705-49cc4db4-b338-4062-842e-1e227daf2154.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-beta3
- Data source type & version: VictoriaMetrics Storage
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ying-jeanne** [comment]
It seems alert is resolved automatically in 70s, @grafana/alerting-squad could you take a look of the issue to see whether it is a misconfiguration or a bug? Thanks.

**Comment by tetsuya28** [comment]
it happens especially when I set short Evaluate period like `Evaluate every 10s for 20s`

**Comment by kylebrandt** [comment]
There is a fix for how normal/ok states are communication with the embedded notification system (alert manager) that should be in the next release https://github.com/grafana/grafana/pull/37363 , this may fix this issue (there have also been others that fixes might impact this).

Aside from that all the timings are important to be able to figure out the behavior (I am also currently working on making list of need debug information more generically as a separate thing ).

But for timings:
Rule:
 - Run interval
 - For setting
 - Nodata/error settings
 - (Also maybe queries and return data if possible)

Notification Policy (the one that will apply to the alert)
 - Group wait, Group interval, repeat interval

**Comment by tetsuya28** [comment]
thanks!! I hope it would be solved in next release.

**Comment by jake-bierman** [comment]
Hi, I have been following these Resolve/Firing bug topics for a while now, I tried the latest release for windows 8.1.1 and using InfluxDB as my database, It does not appear to be fixed in this release and seems to be resolving/firing at a rate related to the group interval set in the notification policy.

**Comment by bigdaveman** [comment]
I'm still getting this issue on 8.1.1

Running the latest docker image, using Prometheus as a datasource

**Comment by kylebrandt** [comment]
@jake-bierman / @bigdaveman Are either of you able to provide the information in https://github.com/grafana/grafana/issues/37461#issuecomment-891931268

**Comment by jake-bierman** [comment]
This is what i have for my test alert at the moment
Run interval: 10s 
For setting : 10s
also tested both at 30s, with no difference 
Nodata/error settings: will alert for no data and errors

Notification Policy:
I think this have the info required
        {
          "receiver": "Test Alert Contact Point",
          "group_by": [
            "sensorID",
            "alertname"
          ],
          "matchers": [
            "alerttype=\"fault\""
          ]
        }
      ],
      "group_wait": "1s",
      "group_interval": "1s",
      "repeat_interval": "52w"
    }

I should get some time later to experiment with group_interval at higher values and see if the alerts will still trigger or if they will get delayed as i have not done this yet.

**Comment by tetsuya28** [comment]
I'm still facing this issue on v8.1.2.
```
Run interval: 10s
For setting : 30s
```

```
"group_wait": "1s",
"group_interval": "1s"
```
