### ISSUE TITLE
Wrong values on left Y axis when using short unit

### ISSUE THREAD

**Issue by Foxeronie** [grafana/grafana#37470]
Hi!

**What happened**:
The left Y axis shows a sum above 2 million when using short unit while the sum is around 1.7 million (the correct sum) when using the none unit

**What you expected to happen**:
Don't show a sum of over 2 million if there are only 1.7 million

**How to reproduce it (as minimally and precisely as possible)**:
Please see the screenshots. The values are stacked.

![Screenshot from 2021-08-03 11-06-31](https://user-images.githubusercontent.com/10115997/127990649-05a301f2-ad21-45b4-a81e-2956ce15e4f0.png)
![Screenshot from 2021-08-03 11-06-47](https://user-images.githubusercontent.com/10115997/127990652-99cf25c6-1f55-4cf7-9b59-e173181c5722.png)

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Graphite 1.0.2
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04 with Firefox
- Grafana plugins: Time series used

Best regards,
Patrick

**Comment by ying-jeanne** [comment]
Hi team @grafana/grafana-frontend-platform, seems user is asking to use round down instead rounding for showing the short unit on the frontend, could you take a look to confirm whether it is a bug? Thanks

**Comment by tskarhed** [comment]
Issue reproduced [here](https://play.grafana.org/d/kmsIYHG7k/wrong-values-on-left-y-axis-when-using-short-unit-37470?orgId=1). I don't think it is a bug though. Removing the `0` from decimals solves the problem.
<img width="1311" alt="Screenshot 2021-08-03 at 13 50 29" src="https://user-images.githubusercontent.com/1438972/128010630-3ff07406-b5e5-46c5-8dc3-a673013dfcb4.png">
I'm closing this issue. If the solution was insufficient, please tell us and we'll reopen it again!
