### ISSUE TITLE
Keep and re-send cookies when doing direct request

### ISSUE THREAD

**Issue by pfischermx** [grafana/grafana#3748]
We use SSO for protecting lot of our internal sites. I was configuring grafana to play with one of our OpenTSDB environments and I was not getting any further, all I was getting was a 302 sending me to our login site. After looking at the HTTP cookies we send to grafana VS the ones it sends I noted it was not copying the original ones.

Is there a way that  that if Grafana gets cookie-foo, that it will re-transmit it? At least in direct (non-proxy) mode. In proxy mode I'd understand it since then it could end up using/sending cookies that you don't want but with a direct XHR, it *should* keep them.

**Comment by torkelo** [comment]
in direct mode Grafana will not remove any cookies for other domains.

**Comment by pfischermx** [comment]
That is not quiet what I'm seeing, this is the setup I've:

 - Grafana (either behind nginx or accessed directly): dashboard.corp.domain.com
 - My OpenTSDB: tsdb.corp.domain.yahoo.com:9999

On chrome developer tools I can see that browser is sending the cookie to grafana (Cookie:) but when grafana makes a direct request to my opentsdb no cookies are sent.

**Comment by torkelo** [comment]
@pfischermx did you enable withCredentials in the datasource options view? Think that is needed, otherwise browsers will automatically strip cookies from XHR requests

**Comment by pfischermx** [comment]
So we are using grafana 2.6, I can't remember if ti supports with credentials on the datasource options view or not (again, this is for opentsdb). However to get this to work we also needed to add the following to the POST request of /api/query:

      options.headers = { 'Content-Type': 'application/x-www-form-urlencoded' };

This is something that other plugins are already doing so possibly it is just not set for opentsdb (I'll file a PR for this), but when you don't maintain your opentsdb instance (which happens very often in a medium/big company) it can get tricky to get the OPTIONS sorted out. Sending the content as x-www-form-urlencoded will make the request a POST rather than an OPTIONS followed by a POST.

Usually if you are protected by a SSO it happens that OPTIONS is usually ignored and if you send one you are redirected/denied  since SSO usually does not expect OPTIONS.
