### ISSUE TITLE
Adding Influxdb doens't adjust Setting Frontend

### ISSUE THREAD

**Issue by moweigel** [grafana/grafana#37488]
**What happened**:

There'r no customized settings when switchting query language to "Flux" (as shown in documentation

**What you expected to happen**:

Input for eg. bucket name or token

**How to reproduce it (as minimally and precisely as possible)**:

add new database in grafana, select influxdb, change query language

**Anything else we need to know?**:

Send help pls <:^) 

**Environment**:
- Grafana version: latest
- Data source type & version: Influxdb 2.0
- OS Grafana is installed on: Linux (docker)
- User OS & Browser: windows & chrome
- Grafana plugins: none (Redis-app, redis-datasource but i guess its not that important for my issue)
- Others:
expected:
![image](https://user-images.githubusercontent.com/88386643/128027615-5ffa9a14-4d75-46c3-80f2-a9f322c2250a.png)
received: 
![image](https://user-images.githubusercontent.com/88386643/128027769-ffdd089c-946c-4b93-8c1c-73e761550c49.png)

**Comment by ying-jeanne** [comment]
Hi, @moweigel 

I am using the latest Grafana version v8.1.0-beta3, here is what i see on the UI:
<img width="871" alt="Screenshot 2021-08-03 at 17 49 54" src="https://user-images.githubusercontent.com/74549700/128046417-b6303991-cc78-41ae-bfc5-57775bd50e90.png">

Could you try it out and see whether the issue persist?

Thanks

**Comment by moweigel** [comment]
It was indeed just at the lower end of the page... Feeling kinda dumb since I wasted a good hour searching for a possible issue. Thanks anyway 👯
