### ISSUE TITLE
Render link doesn't pass "Current" theme on URL and light theme is not working

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#3749]
Hi, I'm using Light theme when I'm logged on my admin account.
Grafana version: 2.6.0

EDIT: Sorry, don't know why, my session was closed... Actually it's working fine on shared links, it is taking the current theme, only it is failing on render link.

When you use the render link, it doesn't get the current theme on the user, so in my case, the result is the render png with black theme instead of light theme.

**Comment by bergquist** [comment]
This have been fixed.
