### ISSUE TITLE
Receiving false positive "Database is Locked" alert in Grafana 8 ngalert

### ISSUE THREAD

**Issue by tgritter** [grafana/grafana#37508]
**What happened**:
We are receiving this error message in Grafana 8 ngalert, even though we are receiving data and the alerts are working as expected.
<img width="371" alt="Screen Shot 2021-07-30 at 2 09 16 PM" src="https://user-images.githubusercontent.com/16708600/128066147-aa682130-5722-49fb-8011-df3fa2eb641e.png">

**What you expected to happen**:
Everything is working as expected, so the error message looks like a false positive. 

**How to reproduce it (as minimally and precisely as possible)**:
It is occurring when there is no data in a query, such as times when we are not receiving any requests to our servers. So maybe try building a query with null values. Here is our query that is giving us the most trouble:
<img width="667" alt="Screen Shot 2021-07-30 at 2 11 30 PM" src="https://user-images.githubusercontent.com/16708600/128069627-8240cf45-d86c-445c-8240-0ee9a12fee26.png">
<img width="638" alt="Screen Shot 2021-07-30 at 2 11 37 PM" src="https://user-images.githubusercontent.com/16708600/128069632-4c120b4d-d42c-41af-b7a7-6eb2d0878b62.png">
<img width="673" alt="Screen Shot 2021-07-30 at 2 11 47 PM" src="https://user-images.githubusercontent.com/16708600/128069644-62250777-90dc-42b0-9ffb-fe8e10cda2be.png">
<img width="688" alt="Screen Shot 2021-07-30 at 2 11 52 PM" src="https://user-images.githubusercontent.com/16708600/128069652-c41f9cc4-1357-43c1-a00c-161d2f440467.png">
<img width="513" alt="Screen Shot 2021-07-30 at 2 11 58 PM" src="https://user-images.githubusercontent.com/16708600/128069662-51ca6036-1a1e-497f-a5b0-a04d0e17928c.png">

**Anything else we need to know?**:
As I mentioned, we are getting the false positive when there is no data in a query, so I suspect the problem may be something like that it interprets a null value as the database being locked. 

**Environment**:
- Grafana version: 8.0.6 ngalert
- Data source type & version: InfluxDB 1.8.1
- OS Grafana is installed on: Linux
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

**Comment by tgritter** [comment]
I've also configured no data and error handling all to okay will no avail:
<img width="372" alt="Screen Shot 2021-08-03 at 11 58 01 AM" src="https://user-images.githubusercontent.com/16708600/128070959-670966ae-9d25-42ed-a647-1a12f03b2f77.png">

**Comment by kylebrandt** [comment]
@tgritter (What database is being used in your setup (e.g. postgres, sqlite)?

**Comment by tgritter** [comment]
@kylebrandt We are using InfluxDB 1.8.1

**Comment by tgritter** [comment]
@kylebrandt I've just updated another one of our service, and getting same error when there is no data. 
<img width="372" alt="Screen Shot 2021-08-19 at 12 49 26 PM" src="https://user-images.githubusercontent.com/16708600/130134717-39f2b729-eae9-413d-985d-909013683afa.png">

Since there are times when we expect no data, I believe the bug is that the above errors should be ignored when we set `No Data` to ok.
<img width="365" alt="Screen Shot 2021-08-19 at 12 51 59 PM" src="https://user-images.githubusercontent.com/16708600/130135036-b5ce4b98-bd63-4eae-9567-e7e1060c065f.png">

**Comment by kylebrandt** [comment]
@tgritter I'm thinking this might not be specific to alerting, but rather it is just showing itself in alerting.

We have this general issue open already for Database is locked with sqlite https://github.com/grafana/grafana/issues/16638 , maybe https://github.com/grafana/grafana/issues/16638#issuecomment-830417878 ?

**Comment by a-mazed** [comment]
I have the same problem on my Grafana 8.1.2.
Set pragma as advised in the comment above
`sqlite3 grafana.db 'pragma journal_mode=wal;'`
Seems that it can help. Will check

**Comment by tgritter** [comment]
@kylebrandt Thanks Kyle! Our issue is with influxDB, not sqlite3. But thanks for redirecting me to the issue, I left a comment there. Feel free to close the issue!
