### ISSUE TITLE
Loki: Graph - > line and legend are not displayed when query return no results

### ISSUE THREAD

**Issue by ItaySasson** [grafana/grafana#37526]
Loki graph line is not displayed when there is no return value or query result is empty.

**What happened**:
When using Loki with Graph visualization queries that return no results (empty or null) are not displayed in graph and are not displayed in legend. 

When there is return value:
![image](https://user-images.githubusercontent.com/88428517/128151960-4f1cec16-2790-4952-931f-15fdcc81aa74.png)

When there is no return value:
![image](https://user-images.githubusercontent.com/88428517/128152113-d06269b3-8fac-495b-8ac9-53077c243be0.png)

**What you expected to happen**:
Even when return result is empty/null the graph line should be set to 0 and should be displayed in the legend

**How to reproduce it (as minimally and precisely as possible)**:
1. Under graph displayed: set "null as zero".
2.  Send query of (count over time) that returns results
3. Send query  of (count over time) that returns no results.
**Anything else we need to know?**:

- Grafana version:  7.5.5
- Data source type & version: Loki v2.2.1
- OS Grafana is installed on: Windows
- User OS & Browser: Windows 2012 R2

**Comment by ashharrison90** [comment]
hi @ItaySasson 👋 

thanks for raising. unfortunately, i don't think there's any way we can "fix" this - this is Grafana working as designed.

`null as zero` only applies to that series if there is at least 1 data point in the time range specified. if there are no data points in the time range, grafana doesn't know anything about that series. hope that makes sense!

i'll close the issue as working as designed, but if you think i've made a mistake or would like to add some more information please feel free and we can reevaluate. 

thanks! ❤️
