### ISSUE TITLE
Grafana 8 breaks Data Link variable to be “results”

### ISSUE THREAD

**Issue by mossuchida** [grafana/grafana#37553]
I was using Graph Visualization. When I upgraded to grafana 8.0.6, it no longer passes the column variable correctly. Following is my data link:

/d/mongodb_dynamic/mongodb-detail?var-column=${__series.name}&from=${__from}&to=${__to}
Expected URL picks up the series name:
```
http://.../d/mongodb_dynamic/mongodb-detail?var-column=limit
```
Actual URL (Broken) The value is changed to “results” for some reason :
```
http://.../d/mongodb_dynamic/mongodb-detail?var-column=results
```

This might be related to this issue :  https://github.com/grafana/grafana/issues/37528

**Comment by wolfs** [comment]
I see the same behavior in our Grafana Cloud instance in data links and alerts: all the series are called `results`. We are as well on Grafana 8.0.6.

**Comment by ying-jeanne** [comment]
Hi @mossuchida,

Thanks for reporting issue, it is a great help form your side. This "results" is introduced from grafana v8.0 and we recently removed from v8.1, could you try to update to Grafana 8.1.x, the problem should be resolved there.

Thanks,

**Comment by mossuchida** [comment]
I have updated to 8.2.1, but still it does not work.
