### ISSUE TITLE
grafana 8 alert

### ISSUE THREAD

**Issue by caoqiang-github** [grafana/grafana#37576]
Hello, we do not want to upgrade the Grafana version but want to use the alarm function of Grafana8 and move the alarm of Grafana8 to Grafana7.4.2. Is this solution feasible?

**Comment by underdog** [comment]
i'm not a dev, but I suspect the answer will be, upgrade to G8, but it's in beta, so you'll have to wait till it's GA release.  I've been running beta for a while, it's not ready for production areas, yet.  I do not think the devs will backport ngalert into G7

**Comment by torkelo** [comment]
we will not backport it to 7.x , only security fixes are backported. 

new alerting will be GA in Q4
