### ISSUE TITLE
Templated variables do not get reloaded

### ISSUE THREAD

**Issue by jifwin** [grafana/grafana#3758]
Hi

I have an issue with scripted dashboards and templating. I have a scripted dashboard that defines some templated variables. Variables have „Refresh on load” set. But when these variables are specified in URL by „var-NAME” parameter, then they do NOT get reloaded and that causes my graphs not to work. Is it an expected behaviour?

The problem showed up after upgrading Grafana 2.1.3 to 2.6.

**Comment by torkelo** [comment]
could could describe your variables and their relation? 

It is true that a variable that is defined from url uses that value, but variables that depend on that variable should update (if they have refresh defined).

**Comment by jifwin** [comment]
Ok. Let's say my metricFindQuery function is:
    MyDatasource.prototype.metricFindQuery = function () {
      return $q.when([{text: 1, value: 1},{text: 2, value: 2},{text: 3, value: 3},{text: 4, value: 4},{text: 5, value: 5}]);
}

And my scripted dashboard is query.js.
Now, when I go to http://localhost:3000/dashboard/script/query.js, all values are available and all graphs are fine.
![image](https://cloud.githubusercontent.com/assets/5750402/12374210/d498c666-bc94-11e5-8436-8302ee237925.png)

But then, I go to http://localhost:3000/dashboard/script/query.js?var-row=All&var-label=All and values are not loaded.
![image](https://cloud.githubusercontent.com/assets/5750402/12374230/40666862-bc95-11e5-9940-95ede4a18187.png)

Just to make things clear, in my example row and label are independent of each other. The same problem occurs when var-row/var-label equals any value, not only "All".

**Comment by jifwin** [comment]
Is utkarshcmu's fix ok?

**Comment by utkarshcmu** [comment]
No, my fix was not ideal. Was just a workaround. Will try to fix it properly asap.

**Comment by bergquist** [comment]
Are you using a custom datasource? Perhaps that is causing problems. I cannot reproduce your problem in master.

The setup Ive tried is 
this dashboard https://gist.github.com/bergquist/af6b0233b42b2539e48b
and this url http://localhost:3000/dashboard/script/scripted.js?var-Hostname=server1&var-summarize=1s

Perhaps the issues was introduced in 2.6.0 and is gone is master. Would you please try reproducing this in the nightly build?
