### ISSUE TITLE
Dynamically generate rows+panel+graphs?

### ISSUE THREAD

**Issue by dnbert** [grafana/grafana#376]
Hello,

Is it possible to dynamically generate rows/panels/graphs when a new data point is added to Graphite? 

The use case that I have right now, is that I ship a lot of data from a lot of machines into Graphite from Collectd, and I'd like to setup a new dashboard (with rows/panels/graphs) for CPU utilization and another dashboard for Memory utilization.

**Comment by nopzor1200** [comment]
There's a feature in development that @torkelo describes in #1888  that allow for dynamically generated rows + panels. 

I think it addresses all the use cases, and might eliminate the need to use a scripted dashboard to get this functionality (although that's always an option of course).

We'd love your feedback on it. Please check it out and leave a comment there. Thanks!

**Comment by torkelo** [comment]
implemented in this issue, https://github.com/grafana/grafana/issues/1888
