### ISSUE TITLE
Password authentication vulnerable to timing attack

### ISSUE THREAD

**Issue by ecneladis** [grafana/grafana#3760]
[grafana/pkg/login/auth.go#L59](https://github.com/grafana/grafana/blob/bddcc6491a8e80124ab88eb1973bb9aabc0b36be/pkg/login/auth.go#L59)
```Go
	passwordHashed := util.EncodePassword(query.Password, user.Salt)
	if passwordHashed != user.Password {
		return ErrInvalidCredentials
	}
```

Please use constant time compare function.

**Comment by bergquist** [comment]
Thank you for reporting this issue :)
