### ISSUE TITLE
New alerts are not recognized in Opsgenie if there's alert already firing

### ISSUE THREAD

**Issue by Freak12Techno** [grafana/grafana#37618]
**What happened**:
So we have a bunch of alerts set in Grafana (with new alerts opt-in) and the integration with OpsGenie set up.
Once there are no alerts and the one is firing, there's a new alert pushed to OpsGenie and we are notified:
![image](https://user-images.githubusercontent.com/83376337/128427430-fc22c86b-498c-4fee-8b78-f6e1fe304dd2.png)

But when the other alert is triggered, there's a notification with different name sent to OpsGenie, but it considers it a duplicate and won't alert us on that:

![image](https://user-images.githubusercontent.com/83376337/128427619-da7f131d-cfef-4f0b-883c-9758db9ef29a.png)

I assume that's because they have the same alias: https://support.atlassian.com/opsgenie/docs/what-is-alert-de-duplication/, and if you see OpsGenie logs, they have the same `alias` for both of these alerts.

I also think this may be not OpsGenie-specific, but something bigger affecting the alerts in general.

**What you expected to happen**:

2 different alerts created by OpsGenie.

**How to reproduce it (as minimally and precisely as possible)**:

- Set up Grafana + OpsGenie with default notification policy
- Create 2 multi-dimensional alerts
- Have 1st of them firing
- Get a notification from OpsGenie
- Have 2nd of them firing
- No notification

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 20.04.2
- User OS & Browser: Firefox/Brave
- Grafana plugins: Only the default ones
- Others:

**Comment by Vimao** [comment]
You could change the grafana integration in opsgenie to include for example tags in the alias field. This helped me in the old alerting when i had such issues

**Comment by Freak12Techno** [comment]
@Vimao how can I set it? I don't see such an option in the contract point settings
![image](https://user-images.githubusercontent.com/83376337/128514410-2f83d729-580b-4fb9-99b6-ccac1601a1f1.png)

**Comment by Freak12Techno** [comment]
I may know why. The integration (if I'm interpreting `pkg/services/ngalert/notifier/channels/opsgenie.go` correctly) seems to treat the whole alerts set as a single alert with the same `alias` field and sends all of them as 1 requests instead of multiple ones. Not sure if that's intended, as I see the same behaviour in telegram and slack integrations as well. Can someone clarify?

As I see, the OpsGenie integration (not sure if others as well, but this one at least) should work in the different way: it should iterate over the alerts, then send 1 request per each alert. This way it'll trigger a new alert for each Grafana alert.

I can do a PR on that, but before that, can somebody from the development team clarify if that'd be okay or the current behaviour is expected and correct?

**Comment by kylebrandt** [comment]
@Freak12Techno Before changing the notifier, I'm wonder if you set the Notification policy that points to opsgenie is change so the Group by setting has the entry `...` (a literal 3 dots):

e.g:

![image](https://user-images.githubusercontent.com/1692624/131347220-87bd434d-3fb8-4e1e-bad0-44f5eeb7c439.png)

From the alert manager documentation (which is embedded in grafana for new alerts and what notifications go through:

```
# To aggregate by all possible labels use the special value '...' as the sole label name, for example:
# group_by: ['...']
# This effectively disables aggregation entirely, passing through all
# alerts as-is. This is unlikely to be what you want, unless you have
# a very low alert volume or your upstream notification system performs
# its own grouping.
```

https://www.prometheus.io/docs/alerting/latest/configuration/#route

**Comment by serge1peshcoff** [comment]
@kylebrandt I haven't tried this yet, will try to reproduce it later tonight.

**Comment by Freak12Techno** [comment]
@kylebrandt Actually yes, I've verified it and it indeed works as expected, so this solved it for me, thanks!
I wonder if it should be more highlighted or set as default though, as I had no idea on that and I think that may mislead people. What do you think?

**Comment by kylebrandt** [comment]
I've made a separate issue to follow up UX on the group by settings (and the secret settings :-/ ) in https://github.com/grafana/grafana/issues/38760

So closing this.
