### ISSUE TITLE
Annotations/Alerts appearing on multiple panels

### ISSUE THREAD

**Issue by underdog** [grafana/grafana#37612]
**What happened**:
annotations/alerts are being mirrored/displayed across all the panels within a dashboard and not just contained to the panel with the associated alert

**What you expected to happen**:
Alerts should display only on the panel with the alert configured and triggered

**How to reproduce it (as minimally and precisely as possible)**:
Create multi-panel dashboard
Create alert
Trigger alert
Alert will display on all panels

**Anything else we need to know?**:
I saw this occurring with legacy alert and now with ngalert

**Environment**:
- Grafana version: Grafana v8.1.0-beta3 (f778fdbbe8)
- Data source type & version: influxdb 1.8.7-1 armhf 
- OS Grafana is installed on: raspberry pi
- User OS & Browser: Windows 10, brave, chrome, windowsedge
- Grafana plugins: N/A
- Others: N/A
![image](https://user-images.githubusercontent.com/510960/128406115-73d46820-1ec2-4644-9f3a-c99b4a7108b1.png)

**Comment by torkelo** [comment]
likely fiixed by https://github.com/grafana/grafana/pull/37496

**Comment by cmckeen** [comment]
I am seeing this behavior as well, running v8.1.0 which #37496 was a part of.

![Screen Shot 2021-08-09 at 10 25 42 AM](https://user-images.githubusercontent.com/866968/128722704-cca437b4-9a72-4958-b384-f744b7deeaaf.png)

**Comment by cmckeen** [comment]
Also, worth mentioning is  https://github.com/grafana/grafana/issues/37640#issuecomment-895241922, in which Kyle thinks this may be resolved with the fix in https://github.com/grafana/grafana/issues/37304.

**Comment by ryantxu** [comment]
This is not fixed and really should be for 8.1.2

**Comment by Trysupe** [comment]
I also had this issue with my grafana instance on `v. 8.1.0`. After downgrading back to `v. 7.5.10` the annotations showed up normally even those created on `v. 8.1.0`. This means there is no issue with saving the annotations only with displaying them.
