### ISSUE TITLE
Mysql - still issue grouping by year

### ISSUE THREAD

**Issue by DonatoD** [grafana/grafana#37611]
**What happened**:
Grouping data by YEAR the "date starting from" and "data itself" are incorrect.
The correct data, as you can see directly from DB as well as from Grafana as table, are:

From database
![image](https://user-images.githubusercontent.com/51508670/128395581-c356b095-d3b0-4660-aeef-c557b87bba20.png)

From Grafana
![image](https://user-images.githubusercontent.com/51508670/128395707-7d1d0b07-0851-4a2a-a311-d3d52a56c60c.png)

But since I need to show them as time series, in this way data and date are completely wrong
![image](https://user-images.githubusercontent.com/51508670/128396428-f392f69f-4370-4f55-9130-596386e984d9.png)

The problem is only grouping data by year. Below, from the grafana query inspector, you can see the data grouped by day just to have more info on the database (data from the beginning till now).
The first data, infact, is on "2020-12-04 01:00:00", and not on "2019-12-20 01:00:00"
![image](https://user-images.githubusercontent.com/51508670/128398053-173ae91c-538c-4fd8-935e-06f34d84c738.png)
![image](https://user-images.githubusercontent.com/51508670/128397773-d99795b1-f009-42b7-a857-f732c61e0040.png)
![image](https://user-images.githubusercontent.com/51508670/128397105-3a5537e8-483f-4912-ac2f-1b9aff42e932.png)

**How to reproduce it (as minimally and precisely as possible)**:
making a query as in the attached imagine
I started using grafana from 8.0 and just update to 8.1 but the problem still remain

**Environment**:
- Grafana version: 8.1
- Data source type & version: phpMyAdmin 5.1.0
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10 - Chrome

**Comment by DonatoD** [comment]
Any news about it? Unfortunately this problem it's creating a lot of noise as we are unable to analyze the correct data. Still. it's embarrassing for me not be able o provide a reasonable explanation. Please help!
Thanks a lot

**Comment by DonatoD** [comment]
I unfortunately even with the last version 8.3.3 the problem still remain.
This is how it groups the value. Right now it's already consider 2022. Please fix it!!!!!!
Thank
![Immagine 2021-12-27 095323](https://user-images.githubusercontent.com/51508670/147454267-9c79816a-d263-4a51-afbc-2b75dd62d92a.jpg)
s

**Comment by zoltanbedi** [comment]
@DonatoD can you please give me steps to reproduce, I can hardly understand what is not working here?

**Comment by DonatoD** [comment]
Hi, it's an old post and at the and I was forced to write a dedicate code as a workaround.
Any way, to reproduce it;
1) create a table as it is shown (you can see the first part of the table, the end/start of the year, the final part of the table)
2) you can check that grafana received the correct records selecting the table format
![image](https://user-images.githubusercontent.com/51508670/232335129-1ec6827e-ad82-4777-94e8-765f1b95690d.png)

3) but when you select time series as format, then the values are incorrect
![image](https://user-images.githubusercontent.com/51508670/232335359-a9087ff6-bfd2-4c8f-9ce1-b62b23a84cf9.png)

**Comment by zoltanbedi** [comment]
I'm unable to replicate this. I can't even create a query like this `SELECT dateColumn, valueColumn FROM table GROUP BY YEAR(dateColumn)` as mysql throws an error on it.

**Comment by DonatoD** [comment]
It's strange. It works to me. I have phpMyAdmin,
Probably. you find something different on the last Grafana release. So you should adjust it consequently, or just write it as code instead of using prepared GUI

**Comment by zoltanbedi** [comment]
So I changed my MySQL instance and disabled ONLY_FULL_GROUP_BY. Now the query runs but I can't see any difference when I change from timeseries to table mode. Can you try it out with the latest Grafana if you could still reproduce this? @DonatoD

**Comment by zoltanbedi** [comment]
Glad to hear that, thank you for confirming @DonatoD. I'm going to close this issue then.
