### ISSUE TITLE
Broken panel layout in 8.1

### ISSUE THREAD

**Issue by alexanderzobnin** [grafana/grafana#37624]
**What happened**:
When the window is quite narrow (in my case it's 860 pixels), panels are overlapping each other and it's not possible to drag panels. It also looks like panel with is incorrect and panel gets the full dashboard with, but instead of switching to the vertical layout, it's still placed horizontally. Starting from approximately 770 pixels of panel with, dashboard is switching to the vertical layout.

<img width="818" alt="Screenshot 2021-08-06 at 10 22 28" src="https://user-images.githubusercontent.com/4932851/128473329-31f84351-742c-4f6e-80b5-288a7a9a323d.png">

**What you expected to happen**:
Panels should be placed on the dashboard properly.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard with 2 panels in the same row. Resize browser window to ~800 pixels (width).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0 (62e720c06b)
- Data source type & version: N/A
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS/Chrome
- Grafana plugins:
- Others:

**Comment by frepke** [comment]
+1

**Comment by torkelo** [comment]
strange unable to replicate this. For me when the viewport get's smaller than 768px it switches to mobile layout, and before that it looks ok

**Comment by jjriggs** [comment]
Experienced the same issue on my small-screen grafana-kiosk client. Confirmed that the problem disappears after downgrading to grafana-server v8.0.6

**Comment by frepke** [comment]
Unfortunately v8.1.2 doesn't solve the problem on my iPhone.
It starts working when I zoom out to 50% (here the graphics appear again) and zoom back in to 85% or 100%.
