### ISSUE TITLE
Divide result of one query by result of another query in SingleStat pane (InfluxDB 0.9)

### ISSUE THREAD

**Issue by gvohra** [grafana/grafana#3762]
Hi there

I realise this is probably trivial to do, but I've searched the docs / GitHub issues and could not find a solution.

I would like to divide the result of the top query by the result of the second query, to transform these absolute numbers into a %:

<img width="1021" alt="screen shot 2016-01-16 at 1 41 56 pm" src="https://cloud.githubusercontent.com/assets/11955301/12374676/dbacca84-bc57-11e5-97a6-31691a83b95f.png">

I feel like this should be possible but I'm not sure how. Please could someone point me in the right direction :)? That'd be much appreciated!

Thanks,
Gaurav

**Comment by torkelo** [comment]
This is possible with Graphite as Graphite supports nested sub queries and many transformations and analytics functions. 

InfluxDB however does not support nested functions or transformations on query results, suggest you submit a feature request to InfluxDB project if this is something you are missing.

**Comment by gvohra** [comment]
@torkelo thanks for the quick reply. Will follow up with InfluxDB. Do you happen to know if there is any functionality similar to T-SQL's CASE WHEN / IIF() function? Something like the following?

`SELECT sum(CASE WHEN value < 25 THEN 1 ELSE 0 END) / count(value) from "ui.switch_thread" where $timeFilter`

**Comment by torkelo** [comment]
No InfluxDB does not support that

**Comment by gvohra** [comment]
For posterity, I got around this by defining another field `under_target` in InfluxDB which is essentially `CASE WHEN value < 25 THEN 1 ELSE 0 END`, then writing the above query as `SELECT sum(under_target) / count(value) FROM "ui.switch_thread" WHERE $timeFilter"
