### ISSUE TITLE
Expression" (math) not working when variable is used

### ISSUE THREAD

**Issue by tamil777selvan** [grafana/grafana#37636]
**What happened**: When using "expression" math `$A + 1` on Stat panel, the data of the expression only works only when Query "A" is not having variable in Where clause.

**What you expected to happen**: Expect to see the stats as per the expression given.

**How to reproduce it (as minimally and precisely as possible)**: 

- Filter data with variables in "A" query

- In Expression try to use math expression and check the data rendered in panel.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: InfluxDb
- OS Grafana is installed on: Linux
- User OS & Browser: Mac & Chrome
- Grafana plugins: Stat

Attachments: 

When Used Variable: 
![Screenshot 2021-08-06 at 5 12 28 PM](https://user-images.githubusercontent.com/49207189/128505542-55be21b1-5c7d-494c-b4d3-7e1cf3ed4c86.png)

When Variable is not Used:
![Screenshot 2021-08-06 at 5 12 43 PM](https://user-images.githubusercontent.com/49207189/128505613-5611e6c6-608c-4f9f-8f65-d29edcbce4bb.png)

**Comment by connorlindsey** [comment]
@kylebrandt this seems like a generic expressions problem. Who should we assign this to?

**Comment by kylebrandt** [comment]
> @connorlindsey This would be on the frontend side of SSE (server side expressions) and how queries work there I think. Currently there is nobody on the frontend side of SSE, so it would just be if someone on frontend platform was interested in picking it up I think.

**Comment by jfagoagas** [comment]
Hi! 

What is the status of this issue? As far as I can see https://github.com/grafana/grafana/pull/41778 solves it.

When will it be released?

**Comment by MiguelAHentoux** [comment]
I'm having the same trouble, is there already a solution?
