### ISSUE TITLE
Azure Monitor plugin does not list the namespace “Microsoft.DBforPostgreSQL/flexibleServers”

### ISSUE THREAD

**Issue by rehbergtr** [grafana/grafana#37637]
**What happened**:
Unable to query against Azure Database for PostGreSQL flexibleServer

**What you expected to happen**:
I want to see metric namespace “Microsoft.DBforPostgreSQL/flexibleServers” in Azure monitor plugin in Grafana

**How to reproduce it (as minimally and precisely as possible)**:

* Create yourself a Azure Database for PostGreSQL flexible server
* Try to query against the namespace in Grafana 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.6
- Data source type & version: Azure Monitor 0.3.0
- OS Grafana is installed on: Unix
- User OS & Browser: Mac OS / Chrome
- Grafana plugins: Azure Monitor 0.3.0
- Others:

Same problem from a different user:

https://community.grafana.com/t/azure-monitor-plugin-does-not-list-the-namespace-microsoft-dbforpostgresql-flexibleservers/48224

Thanks in advance!

**Comment by sarahzinger** [comment]
I believe this should be an easy fix, we just need to add this namespace to our supported namespaces list https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/supported_namespaces.ts#L26

will move it to our sprint

**Comment by rehbergtr** [comment]
Awesome, thank you!

**Comment by rehbergtr** [comment]
Holy moly, that was a serious misclick 😱
