### ISSUE TITLE
Alertng fail to send alert when a multi dimensional rule has label names in kebab case (ex. InfluxDB tag) 

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#37651]
**What happened**:

I tried to create a multi dimensional alerting rule from an InfluxDB database. This database uses kebab case to name tag. When alert fires, Grafana notifier complains that alert label has an invalid name as '-' are not allowed in label names. 

**What you expected to happen**:

Grafana should allow '-' in label names, convert '-' to '_' automatically or provides a convenient way to do so.

**How to reproduce it (as minimally and precisely as possible)**:

Let's define a silly multi dimensional alerting rule. Key point is `group by tag(customer-environment)` (note the - in tag name)

![image](https://user-images.githubusercontent.com/1764725/128529920-d638c102-798a-48bc-aee2-0691c61b0510.png)

Rule can be saved, is evaluated and will eventually fire. However, alert is never sent. Checking the logs, we can observe that notifier is complaining about invalid label name.

```
t=2021-08-06T14:53:07+0000 lvl=eror msg="failed to put alerts in the notifier" logger=ngalert count=16 err="invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\";invalid label set: invalid name \"customer-environment\""
``` 

**Anything else we need to know?**:

* I'm not aware of any easy way to rename the tag at query time.

**Environment**:
- Grafana version: 8.0.6 (cannot test 8.1.0 because of #37626)
- Data source type & version: InfxluDB 1.8
- OS Grafana is installed on: Official docker image running in k8s

**Comment by hashi825** [comment]
Seeing the same issue when using an Elasticsearch datasource due to dotted fields.

**Comment by gabor** [comment]
note: influxdb tag-names can contain anything. i was able to use "⛄" (that is the SNOWMAN WITHOUT SNOW unicode character) as tag-name.
