### ISSUE TITLE
Embed panel iframe URL broken when sharing from home dashboard (set via config)

### ISSUE THREAD

**Issue by Jamie-** [grafana/grafana#37655]
**What happened**:
I want to embed a panel from one of my dashboards in another site. The panel in question exists on a dashboard which is also my home dashboard, specified via config. I opened Grafana and it shows my home dashboard, I go into the panel sharing options and go to the embed tab. The iframe it gives me however does not embed that panel but the entire dashboard.

**What you expected to happen**:
To be given an iframe that embeds just the panel (and not the whole dashboard page).
Took me a while to work out but if you instead go to the dashboard directly via the manage dashboards page and then try to share the panel in the same way, it works.

Example URL generated from home (bad): http://localhost:3000/?orgId=1&refresh=5s&panelId=9

Example URL generated from dashboard's page (good): http://localhost:3000/d-solo/HbGzEKGnk/dashboard-name?orgId=1&refresh=5s&panelId=9

**How to reproduce it (as minimally and precisely as possible)**:
Interestingly this is not reproducible when setting up a test manually - i.e. creating a dashboard by hand and setting it as default. It seems to exercise this bug you need set your home dashboard using config (or in my case config via docker env vars)

I created a new dashboard, added a panel with random generated data, exported it to JSON (`test.json`). I then use that as my test dashboard for the below docker command.

```
docker run --rm -it -p3000:3000 -e GF_SECURITY_ADMIN_PASSWORD=password -v "/path/to/example/dashboards:/var/lib/grafana/dashboards" -e GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/test.json grafana/grafana
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.0.6 (68fe9e3431)
- Data source type & version: n/a
- OS Grafana is installed on: Official Docker container (grafana/grafana)
- User OS & Browser: Ubuntu & Chrome 92
- Grafana plugins: None
- Others: n/a

**Comment by wbrowne** [comment]
Good catch @Jamie-, thanks for flagging it. Looks like a bug to me too

**Comment by marefr** [comment]
Not sure why this one was added to backend. Moved to @grafana/user-essentials 

Noticed that if sharing the link of the panel and copy that and visits it then it works as expected. Link: http://localhost:3000/?orgId=1&refresh=5s&panelId=9&from=1642507653613&to=1642529253613&viewPanel=3

When sharing for embed, visiting the link generated doesn't work. Link: http://localhost:3000/?orgId=1&refresh=5s&panelId=3&from=1642507722902&to=1642529322902

The difference seem to be addition of `viewPanelId=3`.
