### ISSUE TITLE
Stat Panel is showing „no data“ since 8.1.0

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#37659]
**What happened**: 
Upgraded from 8.0.6 to 8.1.0
Stat Panel is showing "No Data". 
If I explore the data source I can access the database correctly.

Query:
`SELECT "Status" FROM "AquacontrolData" WHERE $timeFilter`

**How to reproduce it (as minimally and precisely as possible)**: 
Upgrade to 8.1.0

**Anything else we need to know?**: 
Downgrading to 8.0.6 is fixing the issue immediately. 

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on: Ubuntu 18.06
- User OS & Browser: macOS / Safari
- Grafana plugins: Stat Panel

**Comment by torkelo** [comment]
Could be a Datasource issue, can you show result from query inspector?

**Comment by jostrasser** [comment]
Hi @torkelo 

sure... I have compared the output of 8.0.6 and 8.1.0 and it is identical:

`{
  "request": {
    "method": "GET",
    "url": "api/datasources/proxy/22/query",
    "params": {
      "db": "pooldb",
      "q": "SELECT \"Status\" FROM \"AquacontrolData\" WHERE time >= now() - 15m and time <= now()",
      "epoch": "ms"
    },
    "data": null,
    "precision": "ms",
    "hideFromInspector": false
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "AquacontrolData",
            "columns": [
              "time",
              "Status"
            ],
            "values": [
              [
                1628364265245,
                "working"
              ],
              [
                1628364565245,
                "working"
              ],
              [
                1628364865246,
                "working"
              ]
            ]
          }
        ]
      }
    ],
    "executedQueryString": "SELECT \"Status\" FROM \"AquacontrolData\" WHERE time >= now() - 15m and time <= now()"
  }
  }`

**Comment by torkelo** [comment]
@jostrasser what are your panel options? 

Under value options make your field selection is not "Numerical Fields" 
![Screenshot from 2021-08-10 12-05-06](https://user-images.githubusercontent.com/10999/128848546-9aea0411-91d4-4938-8972-6580fae6c1fa.png)
