### ISSUE TITLE
"Color scheme from thresholds" is changing the color below the threshold value

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#37658]
**What happened**: When I set the series color scheme to `From thresholds` using the new 8.1.0 feature, the color of the line is adjusted just below the intended value.

**What you expected to happen**: I expected the line color to change at exactly the threshold value.

**How to reproduce it (as minimally and precisely as possible)**:
Create a series
Set the color scheme to `From thresholds (by value)`
See this video demonstrating the behavior: https://youtu.be/J4BDTJvCDhA

**Anything else we need to know?**:
I was also testing out the new transformation Config from Query in this panel (though the query was disabled), so I wonder if there was some interaction between the two?

**Environment**:
- Grafana version: 8.1.0-beta3
- Data source type & version: TestData DB
- OS Grafana is installed on: Docker
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

**Comment by trueuto** [comment]
#37629 is somewhat related; it additionally addresses the Firefox behaviour which is even worse.
