### ISSUE TITLE
Quick snapshot Keyboard Shortcut

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3766]
@torkelo / @bergquist Any suggestions on this?

<img width="448" alt="screen shot 2016-01-17 at 1 17 16 pm" src="https://cloud.githubusercontent.com/assets/1019609/12380029/dd3b4162-bd1c-11e5-9d3c-78c2961d55b0.png">

**Comment by bergquist** [comment]
I don't think it deserves a new button. 

But perhaps the snapshoot process can be made quicker. 
Perhaps a keyboard short cut? that would be easy to promote within the snapshoot dialog so power users would find it and hidden enough for normal users.

**Comment by utkarshcmu** [comment]
Keyboard shortcut works. Agreed. Dashboard space is precious. :)

**Comment by utkarshcmu** [comment]
How about a keyboard shortcut on the main dashboard instead of snapshot dialog. Will save a lot of clicks. :)

**Comment by bergquist** [comment]
Sounds good.
