### ISSUE TITLE
Grafana 8 alert rules "no data" notification behavior needs documentation

### ISSUE THREAD

**Issue by GyunCho** [grafana/grafana#37665]
**What happened**: I was told that with the release of 8.1.0, the UI bug with the no data and error handling will be fixed, 
and after upgrading Grafana to 8.10 today, I verified that it got fixed. (FYI, the issue is this: https://github.com/grafana/grafana/issues/36016, values in no data and error handling do not stay set)

After configuring no data and error handling like this screenshot:
![image](https://user-images.githubusercontent.com/25306520/128582431-4f40ee70-02ea-45d1-a974-4dccf68f2ebd.png)
I expected to get an alert when state is "NoData" for 5 minutes, but I didn't get any alerts for "NoData" state.

**What you expected to happen**:
Getting an alert email that starts with [No Data] when there's no data for the alert for certain period of time.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Grafana 8.1.0 version (but all 8 versions also I believe)
2. Create an alert, and set up the contact point and notification policy to make it send an email alert when it meets conditions
3. Make the alert to have no data (I used promql)
4. See if the alert starts sending emails

**Anything else we need to know?**:
Alerts had no problems sending emails before I upgraded to Grafana 8
Any other alerts that meet the condition has no problem sending emails.
Example alert query and its result:
<histogram_quantile(0.95, sum by (le) (rate(kong_latency_bucket{type="request",cluster="wrong-cortex"}[5m])))>
![image](https://user-images.githubusercontent.com/25306520/128582958-4f19f244-e094-4834-9352-b797195d0f5d.png)

**Environment**:
- Grafana version: Grafana 8.1.0
- Data source type & version: Cortex (Enterprise-metrics) 1.3.3
- OS Grafana is installed on: Docker
- User OS & Browser: Mac, Chrome
- Grafana plugins:
- Others:

**Comment by kylebrandt** [comment]
To get a notification with the new alerting system, the No Data setting needs to be change to "Alerting".

TODO: Documentation at https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/#conditions should be updated to clarify this.

**Comment by GyunCho** [comment]
That did work!
But the one thing that changed in a bad way for a fired email is that the email doesn't start with [No Data] anymore, or it's specified in email content.
There's no way for us to know if the alert got fired because of the No Data. I hope this also gets improved.
That's all for this issue.
Thanks alot @kylebrandt !

**Comment by kylebrandt** [comment]
@GyunCho That is a good point, do you mind making another issue for that?

**Comment by GyunCho** [comment]
Created a feature request: https://github.com/grafana/grafana/discussions/37762

Thanks!
