### ISSUE TITLE
Use correct and consistent default scaling prefixes/units

### ISSUE THREAD

**Issue by taam** [grafana/grafana#37668]
(This topic was already mentioned in other places, but I've not seen it anywhere with the explicit wish to change the defaults. If I missed that or you think this is too redundant, then I'm sorry, and you can just close it.)

**What happened**:
When creating a new panel, by default Y values are shown with unit "short", where large values are shown with "wrong" and inconsistent scaling prefixes/units, e.g. K, Mil, Bil. "K" is wrong in terms of SI units, because it would be "Kelvin" then (https://en.wikipedia.org/wiki/Kelvin). "Mil" and "Bil" (as abbreviations for "million" and "billion" I assume) is - besides the inconsistency - also problematic, because it has different meanings in different countries (https://en.wikipedia.org/wiki/Long_and_short_scale).

**What you expected to happen**:
As I'm hoping, that most people watching these graphs understand (and expect) SI units, "short" should use SI prefixes (https://en.wikipedia.org/wiki/Metric_prefix), I think that would solve the problems mentioned above, and it would actually be shorter. (Using "si:" as a custom unit seems to be a hack to get this, but I think the default should be just more sane.)

**Environment**:
- Grafana version: primarily tested with 7.x, but seems to be the case with 8.x, too

**Comment by dsotirakis** [comment]
Hey @taam, could you please post the places you've seen this so we can have a look? Thanks!

**Comment by taam** [comment]
Sure, e.g. if you go to https://play.grafana.org/ -> "Feature showcases" -> "5 - Bar charts and pie charts", the first panel "Popular JS Frameworks" shows the "K" "unit". If you scale it up you get "Mil", "Bil", "Tri", "Quadr", "Quint", and so on. Interestingly, if you scale it down, you're getting long numbers, then scientific notation starting below 1e-6. Using scientific notation could also be an option for large numbers, but there should be some consistency. Thanks!

**Comment by taam** [comment]
Still applies.
