### ISSUE TITLE
Alert "engine" does not honor "Skip TLS Verify" for Elasticsearch data source

### ISSUE THREAD

**Issue by pachico** [grafana/grafana#37687]
**Alert "engine" does not honor "Skip TLS Verify" for Elasticsearch data source**:

While  "Skip TLS Verify" **DOES work** as expected for drawing data, but it **DOES NOT** when alert rule is manually or automatically evaluated.

**What you expected to happen**:
Alert works as expected, as in versions previous to 8.1.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1
- Data source type & version: Elasticsearch 6.4.2
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Any

![image](https://user-images.githubusercontent.com/2184438/128693734-b725a28e-769e-4590-a4b5-95c896a965b3.png)
![image](https://user-images.githubusercontent.com/2184438/128693835-7832632e-6b09-4b8b-8ed9-ff628cf4952a.png)

**Comment by gabor** [comment]
this might be the same as to https://github.com/grafana/grafana/issues/37683

**Comment by dsotirakis** [comment]
Hello @pachico, thanks for filing this - could you please add the steps to reproduce?
Thanks!

**Comment by pachico** [comment]
Sure:

1. Given an ElasticSearch (v6.4.*) node behind an SSL that cannot be verified, add it as data source (screenshot) (By ticking the "Skip TLS Verify" you will be able to use it.)
3. Create any time series graph (this can be in both Graph (marked as old) and Time Series panel)
4. Create an alert of any sort
5. Press "Test rule" -> This will fail since the alert does not seem to allow to skip the TLS verification.

Does this help?

![image](https://user-images.githubusercontent.com/2184438/129000029-03ac045e-6167-42d5-96fb-2b0118ee4efa.png)
