### ISSUE TITLE
Alerts cannot connect to graphite database since 8.1.0

### ISSUE THREAD

**Issue by yakob-aleksandrovich** [grafana/grafana#37686]
#### Environment:
- Grafana 8.1.0 on docker
- Graphite 1.1.7+ on docker
- Amazon Linux 2

#### Initial Condition:
- Graphite and Grafana are installed on the same server.
- Graphite uses basic authentication with username and password

#### How to reproduce:
- Create a dashboard
- Create a graph panel.
- Input any query related to your data into the query panel (eg "aliasByMetric(stats.gauges.server1_api.*)")
- In Alerting tab of the graph, input a threshold,
- Save dashboard
- Click on test rule in alert tab

#### Observed behavior:
- when testing rule, we have this response:

```
firing:true
state:"alerting"
conditionEvals:" = true"
timeMs:"168.163ms"
error:"Execution Error: request handler error: failed to query data: request failed, status: 401 Unauthorized"
logs:Array[1]
0:Object
message:"Condition[0]: Query"
data:Object
from:1628236340096
queries:Array[1]
0:Object
to:1628236640096
```

#### Expected behavior:
- no error should be displayed when testing. Alert should be fired if data requires it.

Misc
- We use the old style of alerting (NO ngalert)

Please note:
- all our alerts have suffered this issue when updating from 8.0.6 to 8.1.0
- no configuration has changed on graphite, especially authentication
- grafana still display data. Only alerting seems broken.
- reverting back to 8.0.6 fixes our issue

**Comment by ifrost** [comment]
Fixed by #37797
