### ISSUE TITLE
Percentage thresholds do not apply

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#37681]
**What happened**:

Percentage thresholds works same as Absolute thresholds. The value I input is treated as an absolute value.

**What you expected to happen**:
Percentage thresholds based on percentage.

**How to reproduce it (as minimally and precisely as possible)**:
![bug](https://user-images.githubusercontent.com/4949937/128689104-7e660a36-39e2-4a87-8a77-d8bf97ab8cd9.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0-30560pre (b78a67cec7)
- Data source type & version:
- User OS & Browser: Edge  Beta 93.0.961.11

**Comment by oscarkilhed** [comment]
I don't think it's treating the value as an absolute value. It seems that the threshold is set to the percentage of the auto min max even if min max are set.

![image](https://user-images.githubusercontent.com/468940/130019772-c6009db4-486e-49d2-9010-65c7006923eb.png)

Here the values for the series are 10 and 5. Threshold set to 50% ends up at 7.5, right between the two series. It should end up at 5, which is at 50% of the min max set to 0 and 10.

**Comment by imReker** [comment]
Grafana v8.1.0-30560pre (b78a67cec7)

My test:
![bug](https://user-images.githubusercontent.com/4949937/130032627-55017f5a-4e49-4183-b82e-bcfe0864b527.png)

And import your demo:
![bug2](https://user-images.githubusercontent.com/4949937/130037885-2c3a9d4f-1222-4ebd-8a52-d7c6abb1dd56.png)

**Comment by oscarkilhed** [comment]
Hmm, yeah, verified your behavior on Grafana v8.1.0-30560pre (b78a67c). I was testing on main.

**Comment by leeoniya** [comment]
@imReker we've merged the fix for this. please try the nightly build tomorrow.
