### ISSUE TITLE
Dashboard-Solo Requires Login for Snapshot

### ISSUE THREAD

**Issue by benyoungnz** [grafana/grafana#3769]
Edit: Sorry. Just read the actual text on that page and realised it specifically says if anon is not enabled etc etc - however is there a possibility of adding this as a feature request for the future?

I am trying to embed a single panel from a snapshot without any of the surrounding grafana interface like when you generate a dashboard-solo url from the sharing interface on a panel.

When i use the following it works unauthenticated

Entire Dashboard
http://grafana/dashboard/snapshot/XXXX

Single Panel view, i.e panel 1
http://grafana/dashboard/snapshot/XXXX?panelid=1&fullscreen

Now if i try use the following for logged in users in terms of it just showing the graph and nothing else it works but for unauthenticated users they are redirected to the login page

http://grafana/dashboard-solo/snapshot/XXXX?panelid=1&fullscreen

Is there a way to achieve this?

**Comment by utkarshcmu** [comment]
As per the message in UI:
<img width="877" alt="screen shot 2016-02-14 at 11 34 01 pm" src="https://cloud.githubusercontent.com/assets/1019609/13042258/b25fced2-d373-11e5-843b-87acfb1f19df.png">
if anonymous access is enabled the dashboard-solo URL will work. 

But if anonymous access is disabled, the dashboard-solo URL will redirect you to login. If we want users to embed/access dashboard-solo urls without enabling anonymous access, then #4033 is the fix.
