### ISSUE TITLE
Tag Playlists

### ISSUE THREAD

**Issue by markolson** [grafana/grafana#377]
Issue #36 proposed dashboard playlists, which were merged in with 7b036cb - I think it would be useful build off of that and have the option to start a playlist using a tag, rather than favorites, as the basis for the list of dashboards. I'm happy to try to implement this myself, if it's a thing that would stand a fair chance of getting in.

**Comment by christrotter** [comment]
+1

We have multiple teams now using Grafana (with multiple TVs displaying data), so just using the Favourites doesn't quite work.  Being able to have a selectable playlist based on the team's tag would be most excellent.

**Comment by torkelo** [comment]
closed in favor of https://github.com/grafana/grafana/issues/3790
