### ISSUE TITLE
The graph avg is NaN.000000000year

### ISSUE THREAD

**Issue by sucan163** [grafana/grafana#3770]
I use data source is InfluxDB v0.9.6 ,Granfan is v2.6.0
Why min max current are ok,but avg is error.
Please help me.Thankyou!
![image](https://cloud.githubusercontent.com/assets/13954813/12382701/ec32e880-bdd7-11e5-8f53-67f23c497668.png)

**Comment by bergquist** [comment]
What does it say if you show avg as short?

**Comment by torkelo** [comment]
can you open chrome dev tools network tab and look at the raw response from your time series store? Please past it here or make a gist with the metrics query response json

**Comment by sucan163** [comment]
@torkelo The response json is too big. 1223 lines. What's your E-mail I can send you.Thankyou for your help.

**Comment by sucan163** [comment]
@bergquist  I don't understand how show avg as short?  Is the timestamp out of range?

**Comment by torkelo** [comment]
@sucan163 you can create a gist ?

**Comment by torkelo** [comment]
@sucan163 the values are strings. You need to send numeric values to influxdb

**Comment by sucan163** [comment]
@torkelo I'm very grateful to remind me! Thankyou!
