### ISSUE TITLE
Why can't it be packaged

### ISSUE THREAD

**Issue by freemankevin** [grafana/grafana#37724]
$ go run build.go build package
Version: 8.1.0-pre, Linux Version: 8.1.0, Package Iteration: 1628581762pre
rm -r ./bin/windows-amd64/grafana-server.exe    
rm -r ./bin/windows-amd64/grafana-server.exe.md5
go version
go version go1.16.7 windows/amd64
Targeting windows/amd64
go build -ldflags -w -X main.version=8.1.0-pre -X main.commit=7d503d4331 -X main.buildstamp=1628535698 -X main.buildBranch=main -buildmode=exe -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server
rm -r ./bin/windows-amd64/grafana-cli.exe
rm -r ./bin/windows-amd64/grafana-cli.exe.md5
go version
go version go1.16.7 windows/amd64
Targeting windows/amd64
go build -ldflags -w -X main.version=8.1.0-pre -X main.commit=7d503d4331 -X main.buildstamp=1628535698 -X main.buildBranch=main -buildmode=exe -o ./bin/windows-amd64/grafana-cli.exe ./pkg/cmd/grafana-cli
Unknown command "package"
exit status 1

Centos /windows environment is the same result

**Comment by dsotirakis** [comment]
Hello @mvalletta. Could you please align with the template we have prior to opening an issue? And also provide a bit more info if possible?
Thanks!

```
<!--
Please use this template to create your bug report. By providing as much info as possible you help us understand the issue, reproduce it and resolve it for you quicker. Therefor take a couple of extra minutes to make sure you have provided all info needed.

PROTIP: record your screen and attach it as a gif to showcase the issue.

- Questions should be posted to: https://community.grafana.com
- Use query inspector to troubleshoot issues: https://bit.ly/2XNF6YS
- How to record and attach gif: https://bit.ly/2Mi8T6K
-->

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:
```

**Comment by freemankevin** [comment]
How to migrate the source code package to other platforms for deployment, such as; rpm/tar.gz。I can’t find it in the official documentation，thanks for the reply。Refer to some posts, the execution result of "go run build.go build package" is unsuccessful

**Comment by freemankevin** [comment]
The grafana source code is packaged into an rpm package

Expect to get   “dist/grafana-latest-1.x86_64.rpm”

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: prometheus  2.28.1
- OS Grafana is installed on: Centos
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by limabing** [comment]
hello,can you tell me how to solve this problem finally?thank you!
