### ISSUE TITLE
Bug: Value mapping not working in all case (string)

### ISSUE THREAD

**Issue by nicolargo** [grafana/grafana#37728]
In some cases, value mapping from a string did not work:

Example:

- "Procedure execution started." ==> Mapping OK :)
- "Procedure execution completed. Confirmation status: CONFIRMED" ==> Mapping KO :(

Is there any limit concerning string mapping (number of characters, special characters ?).

Thanks !

<img width="1627" alt="bug-grafana" src="https://user-images.githubusercontent.com/776747/128837110-a452daee-c523-41d1-9932-7c4650e5717b.PNG">

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: ElasticSearch
- OS Grafana is installed on: CentOS 7.6
- User OS & Browser: Firefox 79

**Comment by ashharrison90** [comment]
hi @nicolargo 👋 

with a simple example i can't reproduce:
![image](https://user-images.githubusercontent.com/20999846/128844007-db9240e5-e716-4ef3-9e18-30c06c093903.png)

would you be able to share your panel json and some sample data? my initial guess is that there's some special character in your data that's preventing the value mapping from matching correctly.

**Comment by nicolargo** [comment]
My bad !

After exporting data to a CSV there is an empty space at the end of the string !

Thanks, you save my day :)
