### ISSUE TITLE
Elasticsearch: Interval value cannot be used within metric script field

### ISSUE THREAD

**Issue by RobertLukan** [grafana/grafana#3773]
I am creating a dashboard for Netflow collector, which is based on Logstash and Elasticsearch. End device is reporting active flows based on 60 sec interval in bytes format. In order to get bandwidth used, conversion from bytes to bits per second can be easily done with script field (multiply with 8 and divide by 60)

Issue appears when auto interval is used and interval is longer then 60 sec. In that case displayed values are not correct. I am trying to use $interval field inside of script field, to correct this behavior, but I am getting following error:

![screen shot 2016-01-18 at 11 02 41 am](https://cloud.githubusercontent.com/assets/15019985/12388418/088eb680-bdd3-11e5-8ae6-b9d4ab2a5e88.png)

Which somehow make sense, string cannot be used for calculation. Is there any way to convert $interval from string to integer ?

For example, I am not facing those kind of a behavior under kibana, there is no need to adjust the value when interval is longer > 60 sec.

Example of correct graph (interval = 60 sec):

![screen shot 2016-01-18 at 11 13 42 am](https://cloud.githubusercontent.com/assets/15019985/12388696/b9de737a-bdd4-11e5-9650-4ea48a436008.png)

Example of incorrect graph (Interval = 600sec);

![screen shot 2016-01-18 at 11 13 25 am](https://cloud.githubusercontent.com/assets/15019985/12388710/d13cb8ec-bdd4-11e5-9fac-13f3fd10302d.png)

Any ideas, maybe I am doing something wrong ? Thanks

**Comment by mekalz** [comment]
I'v added a variable $intervalSeconds in the template. I will make a pull request later.

**Comment by stefan-baranoff** [comment]
Same/similar to #6582 - did you happen to get that pull request in?

**Comment by mekalz** [comment]
I have submitted my code, please see PR #7170 and review.

**Comment by torkelo** [comment]
you can now use `$__interval_ms`
