### ISSUE TITLE
On the Export tab, enable to share externally and click Save to file does not work in 8.1

### ISSUE THREAD

**Issue by NvBgm** [grafana/grafana#37743]
In the dashboard menu, click Share dashboard to export the dashboard to your computer. On the Export tab, enable to share externally and click Save to file.

Afther update Grafana to v8.1 it does not activate the 'Save to file' button in Share dashboard Export tab.
Enable to externally is set also

![Export save to file](https://user-images.githubusercontent.com/8125819/128885260-58ac474f-3daa-46dc-a27f-fa3af7320c62.png)

**Environment**:
- Grafana version: 8.1
- Data source type & version: SQL
- OS Grafana is installed on: Raspberry
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment]
hi @NvBgm 👋 

thanks for raising! struggling to recreate this, works fine for me on mac with chrome.
few questions to hopefully get a bit more information:
- when you say it does not activate the 'Save to file' button, do you mean you click the button and nothing happens?
- are there any errors in the browser console?
- would you be able to share your dashboard json? (i realise the irony of this question... 😂 but i'm assuming you can still view the json?)

thanks again! 😄

**Comment by NvBgm** [comment]
Hi, Thanks for your reaction.

Indeed, when I click the button nothing happens.
There are no errors in the browser console.
And yes i can view the json en copy it to the clipboard.

**Comment by NvBgm** [comment]
Hi all,

I found the problem. It turns out to be an extension in chrome that blocks the save to file popup window.
Sorry for the error reported too early.
