### ISSUE TITLE
Axis width is not calculated correctly in 8.1

### ISSUE THREAD

**Issue by krocans** [grafana/grafana#37740]
Since Grafana 8.1.0 axis width is not calculated correctly when set to auto and beginning of longer axis labels is being cut.
Examples:
![image](https://user-images.githubusercontent.com/42302779/128873742-f27b1187-4893-4981-9be0-3b8b77bcdd3e.png)
![image](https://user-images.githubusercontent.com/42302779/128873855-13273bb3-debd-4dd4-9e77-ac22c770c017.png)
Setting axis width manually to some bigger value shows full label but this is not very handy workaround.

**Comment by leeoniya** [comment]
regressed by https://github.com/grafana/grafana/pull/37464.

here it fails cause the for `50%` we measure `000`, but `%` is wider than `0`.

it's a game of whack-a-mole if we want to  avoid measuring every single label (fine for 5s / normal refreshes, but kills performance for 50ms streaming updates).

looks like we need so actually measure everything and implement a measurement cache/memoization in a `Map()`.

**Comment by leeoniya** [comment]
also visible in v8.1.2 on play.grafana.org home:

![image](https://user-images.githubusercontent.com/43234/130471934-cae5810d-1ad0-4e23-a939-5fd115406908.png)
