### ISSUE TITLE
Legend popover doesn't load

### ISSUE THREAD

**Issue by sunbit** [grafana/grafana#3774]
When clicking on the coloured line left to a legend item, fails to load the popup legend with a not found when trying to load file:

`app/plugins/panels/graph/legend.popover.html`

seems like is `panel` instead of  `panels`.
I had a previously setup from ~ a week ago (commit `a9aaa5ad73578b58ff4df0eaade41bbe421d6359`) that was working, latests code pulled today fails.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master, will push out new 3.0-pre1 builds
