### ISSUE TITLE
Unable to apply alerts on graphs using transformations

### ISSUE THREAD

**Issue by jdevilla20** [grafana/grafana#37751]
Hi

I am using grafana v8.05.  I am trying to apply alerts on a graph using transformations.  I am getting an error.

"Transformations are not supported in alert queries"

![image](https://user-images.githubusercontent.com/45016974/128984524-f22b6301-c111-4858-84c1-17be082ac115.png)

Is there a workaround for this?

**Comment by dsotirakis** [comment]
Hello @jdevilla20, could you please re-upload the pictures since they are corrupted for me?
Thanks!

**Comment by jdevilla20** [comment]
@dsotirakis 

Here are the screenshots:

![image](https://user-images.githubusercontent.com/45016974/128984703-80c86419-734e-40a8-8dea-28ca364d4324.png)

![image](https://user-images.githubusercontent.com/45016974/128984734-13b03ef5-2a06-4fb1-bc59-d7fdf98fc4e1.png)

![image](https://user-images.githubusercontent.com/45016974/128984766-d82805ab-b9f5-473a-8d9b-333a86c45059.png)
