### ISSUE TITLE
Question: Can grafana support server-less visualization?

### ISSUE THREAD

**Issue by gopalakrishnan-subramani** [grafana/grafana#3775]
We have small Industrial IoT device with web server (limited capabilities, memory, CPU, storage). Recently I have explored Grafana for time series data visualization with InfluxDB, found it very impressive,  wish to use Grafana dashboard embedded inside our IoT Web client application.

I know Grafana support multiple API backends which are external DB servers, my question here is do we have any Javascript written DB back-end, that can run within browser context, supplying data to Grafana? Our data is stored as CSV files in IoT device, we can pull CSV file on need basis, load the file content in to  In Memory Browser based Javascript DB engine, then Grafana can pull data with in browser itself.

Any suggestion or pointer would help us. Thank you.

**Comment by torkelo** [comment]
you can check the datasource api used by the existing plugins:https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource

Would be easy to write a datasource that used an in memory javascript data, but Grafana itself needs a backend and cannot be embedded inside other applications beside via iframe.
