### ISSUE TITLE
grafana 8.1.x alerts failing for influxdb

### ISSUE THREAD

**Issue by steverweber** [grafana/grafana#37770]
alerts are failing with error: tested 8.1.0 and 8.1.1
```
InfluxDB returned error status: 401 Unauthorized 
```

After reverting to to version 8.0.6 alerts work with data source influxdb 1.8.9,
My influxdb server is running with auth and ssl enabled. perhaps related to the bug.

Sorry lacking in details. Just thought I would pass along quickly.

**Comment by steverweber** [comment]
likely related https://github.com/grafana/grafana/issues/37686

**Comment by gabor** [comment]
@steverweber this is probably the same problem as https://github.com/grafana/grafana/issues/37626 , there is a workaround described in https://github.com/grafana/grafana/issues/37626#issuecomment-895226853

(closing this issue, feel free to comment in that issue if the workaround does not help)
