### ISSUE TITLE
Grafana 3.0 issue - Can't modify an existing singlestat that has a drilldown link 

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#3777]
Steps to replicate:
1) Create a singlestat with drilldown link.
2) In the dashboard, try to click on the singlestat title in order to display the View/Edit/Duplicate/Share menu (see attached).
What happens:
The menu does not appear, instead we're being redirected to the drilldown link.
What should happen:
The menu should appear and we should not be redirected anywhere if we click on the singlestat title.

This is a bit frustrating. 

<img width="983" alt="screen shot 2016-01-18 at 15 16 15" src="https://cloud.githubusercontent.com/assets/952836/12392351/0a9f830e-bdf7-11e5-8663-ad88fd87bbfa.png">

<img width="239" alt="screen shot 2016-01-18 at 15 18 10" src="https://cloud.githubusercontent.com/assets/952836/12392363/14708c7a-bdf7-11e5-920b-1aafc3cb943a.png">

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master, will push out new pre release build

**Comment by costimuraru** [comment]
Cool, thanks @torkelo!
