### ISSUE TITLE
Explore view: Query error: Cannot read property resultType of undefined 

### ISSUE THREAD

**Issue by jgehrcke** [grafana/grafana#37787]
**Bug description**:

This error should not appear:

![Screenshot from 2021-08-11 10-53-05](https://user-images.githubusercontent.com/265630/129004986-7abb65e4-213a-48c9-a358-3a49c1d6334b.png)

**What you expected to happen**:

When no HTTP response arrived (in its entirety) the response-representing object in code seems to be `undefined` (makes sense). This can happen as of transient issues or as of a timeout hitting in. A perfectly expected scenario. In those cases the _actual_ underlying error should be shown (e.g.: "timeout while ..." or so).

**How to reproduce it (as minimally and precisely as possible)**:

In this case I think a timeout error was hitting in, i.e. the response didn't fully arrive within a minute or so. However, this kind of scenario (no HTTP response having arrived _completely_) is totally expected as of a whole spectrum of transport level issues or service outages.

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Loki

**Comment by gabor** [comment]
hi @jgehrcke , unfortunately i cannot reproduce the problem. when the Loki query takes too long, the request is stopped and i get a "Bad Gateway" error.

is there any more info you could provide about how to reproduce it?
could you check the network-tab during such a request, and see what is received by the browser? is it a http200 request? also, what kind of JSON is in the response?

**Comment by jgehrcke** [comment]
> is it a http200 request?

Let's carefully distinguish request and response! :) 

I am talking about the case 

> When no HTTP response arrived ...

So. That's the scenario! One reason for ending up in this state is when the HTTP client used in the Grafana UI gives up waiting for the response to arrive in its entirety (it might have seen the response headers, but it might not have seen the _end_ of the response body within a given time frame).

>  when the Loki query takes too long, the request is stopped and i get a "Bad Gateway" error.

That just means that a proxy between your browser and Loki is friendly enough to implement a timeout criterion. It then sends an HTTP response to the HTTP client, and from the HTTP client's point of view this is then a very different scenario from the one this ticket is about.

**Comment by gabor** [comment]
hi @jgehrcke thanks for the response.
unfortunately, if we cannot reproduce the issue, we cannot fix it, so i'd like to know:
- can you reproduce the problem?
- if yes:
  - please describe how
  - open the browser-network-tab and check what happens with the loki ajax-request when the problem is happening. does it end with a http200 response? if yes, what does the response-data contain? (please remove any private/secret info it might contain)

thank you.

**Comment by jgehrcke** [comment]
> can you reproduce the problem?

Yes. As in "I am able to". For hopefully obvious reasons this is however difficult to put into a minimally working example. Requires a distributed system where the query endpoint shows special behavior.

They critical ingredient I think is to make the query response hit the HTTP client's timeout while it is currently receiving response data.

There are (at least) two ways to get there:

1) In a real-world production scenario find a query response that behaves like that. This is what I did, but I cannot give you this reproduction environment. Downside with this approach is of course that this may or may not be reproducible.

2) For making this reliably reproducible, the best approach is to use query endpoint that is artificially made a 'slow responder' to actually hit the timeout criterion in the client (one that actually streams the response body!).

So, while I know of one way to reliably reproduce the problem, this is a little bit of work and the developer who's going to try to fix this might want to create this in their preferred way.

> open the browser-network-tab and check what happens with the loki ajax-request when the problem is happening. does it end with a http200 response? 

Probably yes. When an HTTP response is sent over a TCP connection then the first few bytes already contain the status code. This may even be '200 OK'. After that, there is still a lot that can go wrong before the last byte of the HTTP response is received. This is the scenario we talk about here.

Let me try to reproduce this with my reproduction environment, and then show more screenshots.

**Comment by jgehrcke** [comment]
Reproduced.

### what the UI shows:

![Screenshot from 2021-08-13 14-51-23](https://user-images.githubusercontent.com/265630/129359969-c3f58f53-de49-4b50-b5ea-f9e2f39d2a00.png)

### what the console shows:

![Screenshot from 2021-08-13 14-58-12](https://user-images.githubusercontent.com/265630/129361021-a9a983f0-f725-4dc6-bf2b-2b6f38aea1c6.png)

so that's in the loki plugin

### what the network tab shows

![Screenshot from 2021-08-13 14-57-37](https://user-images.githubusercontent.com/265630/129360620-ac5e13e2-3025-41d3-ba25-7f6b8abd9eea.png)

Critical detail here is: 200 GET response headers were received _but_ the response never arrived completely. Bottom left in this screenshot (above) shows that about ~30 MB of response data were already received in the moment the client decided to not wait longer.

In the following high-level overview the request is shown with `200` in the Status column:

![Screenshot from 2021-08-13 15-01-23](https://user-images.githubusercontent.com/265630/129360966-e6422e48-2bf0-4e89-8e7e-4078c003ef2e.png)

The `Response` tab can't show anything meaningful, makes sense:
![Screenshot from 2021-08-13 15-00-19](https://user-images.githubusercontent.com/265630/129361162-c9b35928-80d9-4747-b418-7b9ea953ad69.png)

The `Timing` tab is interesting as it shows that 'content download' really took most of the time here -- it does not show that it did not complete, but that's what happened:
![Screenshot from 2021-08-13 14-57-52](https://user-images.githubusercontent.com/265630/129361237-f20180af-5bd4-4d08-84dc-7387f12bb614.png)

### Further analysis

Of course, an interesting question is which entity actually decided to stop the response streaming:

1. Did the client actively decide to not receive any further response byte? 
2. Did the server decide to close the transport?

4. I suppose if it were (2) then the fetch() API call in the browser would not show as successful. Based on the data at hand, it is highly likely that the HTTP client that sits on top of fetch() has decided to stop consuming any further response byte.

**Comment by gabor** [comment]
@jgehrcke thanks for the info! we will look more into this.

**Comment by gabor** [comment]
NOTES for further investigation:
- may be related: if you make it so that the loki-response to the browser is a http404 (by pointing the datasource to a wrong place for example), we get the same error-message, from https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/loki/result_transformer.ts#L508 . this should not happen, at that place we assume everything is ok.
- may be interesting: the data-download stopped at `29.7mb`. maybe we are cutting the processing based on a file-size-limit?
