### ISSUE TITLE
Repeating row shown even when variable empty

### ISSUE THREAD

**Issue by didfet** [grafana/grafana#3778]
I have a dashboard with two variables :
- one to select a host for the whole dashboard
- one to display a repeating row for each jvm on the selected host

If the jvm list is not empty for the selected host, everything is ok, I have a row for every jvm
If the jvm list is empty, the dashboard still displays one row with graphs showing : no datapoints

Have I missed something or is it a bug ?

**Comment by torkelo** [comment]
no, this is not a bug, the repeat panel/row feature needs to have at least one value (the first panel/row acts as the template), if it is removed there is no way to edit the row/panel to repeat

**Comment by didfet** [comment]
OK I get it. But I still have 2 remarks :
- there should be a default value for the variable when the list is empty. What I see here is the last value of the first row when the list wasn't empty
- I think there is an elegant way of dealing with this : just collapse the row by default when the variable is empty. If you want to edit one of the panels, you just need to click on the button to expand the row
