### ISSUE TITLE
Tooltip not displaying properly on Time Series graph with SQL Datasource

### ISSUE THREAD

**Issue by deathchurch** [grafana/grafana#37798]
**What happened**:
When mousing over a Time Series graph the Tooltip is not showing the series value when the setting is Single mode Tool Tip, if you change to All mode the Tooltip shows the correct values.

**What you expected to happen**:
Expected the Tool Tip to be shown correctly in all modes

**How to reproduce it (as minimally and precisely as possible)**:
Single
![image](https://user-images.githubusercontent.com/37252590/129041706-547a78a3-1f13-453a-b435-ebf617e98135.png)

All
![image](https://user-images.githubusercontent.com/37252590/129041780-ff1a7b0a-9595-43c1-be96-037cd393c598.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: SQL Data source
- OS Grafana is installed on: Windows
- User OS & Browser: Edge Chromium
- Grafana plugins: Default
- Others: N/A

**Comment by leeoniya** [comment]
pretty sure this was an unfortunate regression that slipped into 8.1.0 and was then fixed in 8.1.1 by https://github.com/grafana/grafana/pull/37615

please try with v8.1.1: https://grafana.com/grafana/download

**Comment by deathchurch** [comment]
Yes 8.1.1 has indeed fixed this issue, thanks.
