### ISSUE TITLE
Unified Alarms grouping problem and missing information

### ISSUE THREAD

**Issue by gorkem2020** [grafana/grafana#37802]
> {
    "receiver": "AWS-API",
    "status": "firing",
    "alerts": [
        {
            "status": "resolved",
            "labels": {
                "alertname": "room52 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:10:09.4695512Z",
            "endsAt": "2021-08-08T09:39:09.4695512Z",
            "generatorURL": "......",
            "fingerprint": "01fae9f107e8bd51",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room52} value=2.365125572430543 ]"
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room12 alarm"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:28:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "a098028d1b41e9d3",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room12} value=1.0623855049899877 ]"
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room34 alarm"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:14:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "4b0d66b2b6892db2",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room34} value=-2.150685102297814 ], 
							[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room34} value=-1.4462688306315763 ]"
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room27 alarm"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:34:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "743396bd962fb20e",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room27} value=-1.0793742662029506 ]"
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room11 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:15:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "20a09a687697d95d",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room11} value=-1.1582701187584759 ]"
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room44 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:39:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "b05d3969851e0d8b",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": ""
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room05 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:36:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "58da6e7b8acf20db",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room05} value=1.5318855962592126 ], 
							[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room05} value=1.144295316738316 ]"
        }
    ],
    "groupLabels": {},
    "commonLabels": {},
    "commonAnnotations": {},
    "externalURL": "https://example.com:3000/",
    "version": "1",
    "groupKey": "{}:{}",
    "truncatedAlerts": 0,
    "title": "[FIRING:6]  ",
    "state": "alerting",
    "message": "some message"
}

**What happened**:
1-) even though no grouping has been set for alarms, it is still grouping notifications.
2-) 'firing' and 'resolved' notifications are grouped under 'firing'. (example above, 6 firing and 1 resolved)
3-) 'valueString' information is empty for 'firing' notification. and non-empty for 'resolved'

**What you expected to happen**:
1-) if no grouping has been set, then there shouldn't be any grouping
2-) 'firing' notifications should be grouped under 'firing' and 'resolved' notifications should be grouped under 'resolved'
3-) 'valueString' should not be empty for 'firing' notifications. and should be empty for 'resolved' notifications.

**Anything else we need to know?**:

**Environment**: docker image grafana/grafana:8.1.0
- Grafana version: 8.1.0
- Data source type & version: influxdb 2.0.7
- OS Grafana is installed on: docker. alpine.
- User OS & Browser: Mozilla, chrome
- Grafana plugins: none
- Others:

**Comment by kylebrandt** [comment]
Hi @gorkem2020 

 1. Even if the notification policy does not have "group by" set, the group timings still of the notification policy still apply - can you share those settings?
 2. the value string issue sounds like it could be a bug and perhaps separate, doing mind creating another separate issue for that one?

**Comment by gorkem2020** [comment]
> 
> 
> Hi @gorkem2020
> 
>     1. Even if the notification policy does not have "group by" set, the group timings still of the notification policy still apply - can you share those settings?
> 
>     2. the value string issue sounds like it could be a bug and perhaps separate, doing mind creating another separate issue for that one?

Hey! Thanks for reply. Here are some screenshots.


![1](https://user-images.githubusercontent.com/29964484/129712038-169d7e81-b860-4362-aa49-1ef00c42d34b.png)
![2](https://user-images.githubusercontent.com/29964484/129712043-07ce4b34-cc24-4e8c-a923-47950b6e11cf.png)
![3](https://user-images.githubusercontent.com/29964484/129712046-cacba64c-a74a-41e4-8b62-46b312ae01ee.png)

**Comment by gorkem2020** [comment]
> 
> 
> Hi @gorkem2020
> 
>     1. Even if the notification policy does not have "group by" set, the group timings still of the notification policy still apply - can you share those settings?
> 
>     2. the value string issue sounds like it could be a bug and perhaps separate, doing mind creating another separate issue for that one?

I can understand grouping by timings, but 'firing' and 'resolved' should be in different batch groups, no? Or should I make some changes in options to separate these? I assumed it would separate them by default.

**Comment by danielelisi** [comment]
We're experiencing the same issues on Grafana 8.1:
 - alerts being grouped even though we didn't set group by parameters.
 - slack messages containing firing and resolved alerts in the same message.

**Comment by kylebrandt** [comment]
I think the issue may be that group_by needs to be set to `...` as per https://www.prometheus.io/docs/alerting/latest/configuration/#route , looking into this more ... will follow up

**Comment by kylebrandt** [comment]
I'm wondering if you edit the policy to be like:

![Selection_004](https://user-images.githubusercontent.com/1692624/130233543-71151cf7-531c-410d-9ee5-2cd1641617be.png)

With 1 for both group wait and group interval, and manually enter `...` into group by, if things work like what you are after?

**Comment by kylebrandt** [comment]
> * slack messages containing firing and resolved alerts in the same message.

@danielelisi Is this an issue because you don't want them grouped, or because you feel the notification should not have been sent if alerting and then resolved?

If you don't want them grouped, to better understand the use case, what is the issue with having them grouped?

**Comment by gorkem2020** [comment]
> 
> 
> I'm wondering if you edit the policy to be like:
> 
> ![Selection_004](https://user-images.githubusercontent.com/1692624/130233543-71151cf7-531c-410d-9ee5-2cd1641617be.png)
> 
> With 1 for both group wait and group interval, and manually enter `...` into group by, if things work like what you are after?

Hello,

what do you mean with '...' 3 dots? I just edited it as you recommended and now will be waiting.

**Comment by kylebrandt** [comment]
Literal 3 dots. This is from the alertmanager syntax
https://www.prometheus.io/docs/alerting/latest/configuration/#route , we
may make it the default. But it can be manually entered into the field.

**Comment by sgpinkus** [comment]
> Even if the notification policy does not have "group by" set, the group timings still of the notification policy still apply - can you share those settings?

@kylebrandt  How can timings apply if there is no grouping? Timing apply to groups. Does it mean:

 - `group_by=unset: everything is grouped.
 -  `group_by="...": nothing is grouped.

?

Also why is it necessary to set the timing parameters to `1s` *and* the grouping to `...`? Given `...` the timing parameters would apply to each individual alert.
