### ISSUE TITLE
Please give me some help。how to move the template variables into row

### ISSUE THREAD

**Issue by crazy-pizza** [grafana/grafana#37815]
In the dashboard，we use row to distinguish the different metrics，and we use some template variables in the dashboard.
However, template variables are not useful in all rows，we want to be able to make our template variables belong to row.

**Comment by dsotirakis** [comment]
Hello @crazy-pizza, thanks for opening an issue.
Could you please describe in a bit more detail what do you want to do and what's wrong?
You can use the issue template that appears when you create a new issue!
Thanks!

**Comment by crazy-pizza** [comment]
@dsotirakis OK，I‘m sorry, I will use the issue template in the future。

For example, I have three row and one template variable  in my dashboard.
the template variable is Http request uri.  I want to move this template variable into row as name of  ’Web‘.  But I didn't know how to do this.
![image](https://user-images.githubusercontent.com/35158271/129175529-60881667-ce58-4782-b469-7bbedd9a1f0b.png)

**Comment by dsotirakis** [comment]
Will close the issue as this is a question for the community. Please ask for some help in https://community.grafana.com/
Thanks!
