### ISSUE TITLE
PanelEdit: actual size is busted

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#37812]
When working on a panel with a specific aspect ratio, it is nice to see it in the shape it will be in the dashboard.  We have the "Fill" and "Actual" for this reason... but it is currently not behaving properly.

![image](https://user-images.githubusercontent.com/705951/129112499-32094ddd-662a-48be-802d-c01f03b7b221.png)

Edit mode:
![image](https://user-images.githubusercontent.com/705951/129112534-4e2f2c4f-1102-4b5e-b2e9-a9b73389aea0.png)

I would expect to see something similar to what we had in 7x and 8.0

**Comment by torkelo** [comment]
ah, was on my todo to fix this yesterday. but good that there is an issue for it
