### ISSUE TITLE
Unified Alerting: Template variables not being expanded in alert messages.

### ISSUE THREAD

**Issue by dmit2k** [grafana/grafana#37836]
I'm using Grafana 8.1.0 with ngalert option enabled and with two Contact points created (Webhook type and Alertmanager type), the datasource is Prometheus.

According to https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/ it ishould be possible to use query labels and values in alert messages for Summary and Description. 

I have tried all possible combinations of {{ $labels.domain }}, {{ $values.A.Value }} etc, but actually it is not being rendered into real values (both in Alerting UI and actual messages sent).

Alerting UI shows the following Value for a fired alert:

`[ metric='mydomain.com' labels={__name__=domain_expiry_days, domain=mydomain.com, instance=domain_exporter:9222, job=domain-exporter, monitor=vm-main, origin_prometheus=vm-main} value=29 ]`

But resulting Summary is still

`Domain {{ $labels.domain }} expires in {{ $values.A.Value }} day(s)`

**Comment by kylebrandt** [comment]
I'm thinking maybe https://github.com/grafana/grafana/pull/36611 didn't make it into the release because it was missing the backport tag ... looking.

**Comment by kylebrandt** [comment]
@dmit2k Can you provide more info about the alert rule?
 - Data source?
 - If possible can you share the expresisons and/or queries?
 - When running "test rule" when editing the rule, what does the table show?

**Comment by dmit2k** [comment]
>     * Data source?

1) Prometheus (Victoriametrics)
 
>     * If possible can you share the expresisons and/or queries?

Tested with another alert (just in case), same problem:

![query](https://user-images.githubusercontent.com/1772195/129676925-ff7cf7cd-61b1-4a41-845e-1a65c4761f08.jpg)

![alert_template](https://user-images.githubusercontent.com/1772195/129677057-4650ed98-0c93-4de9-864f-c968990d1925.jpg)

 
>     * When running "test rule" when editing the rule, what does the table show?

![test_rule](https://user-images.githubusercontent.com/1772195/129676945-f2258165-a4e6-4e16-b1a3-b07753046185.jpg)

And I finally get the following alert message to my notification channel both via Alertmanager and Webhook contactpoints:

![alert_message](https://user-images.githubusercontent.com/1772195/129677426-8abf0f2f-c291-41f8-a5e6-456d811084e9.jpg)

**Comment by kylebrandt** [comment]
Ah, labels and values are not supported when using the "classic condition" operation. What should be available when using classic condition I believe is `{{ .ValueString }}` , or `{{ $value }}` either of those work?

Looks like that needs documentation.

**Comment by dmit2k** [comment]
> Ah, labels and values are not supported when using the "classic condition" operation. 

[facepalm] Guys, that **definitely** needs to be documented. I've spent a week finding what I'm doing wrong....
Thank you @kylebrandt Now it worked by using the Reduce & Math functions. 

What prevented me from using those myself was the warning badge on the button that "Beta features could stop working". So now I'm a bit frustrated - is it a new recommended way of managing much promoted Unified Alerting of Grafana 8 or is it still beta?

> What should be available when using classic condition I believe is `{{ .ValueString }}` , or `{{ $value }}` either of those work?

As I remember I have tried this "old school" notation but couldn't make it work either.

> Looks like that needs documentation.

For sure! :-D

Thanx once again!

**Comment by kylebrandt** [comment]
@dmit2k Sorry for the frustration and the short reply, was getting towards the end of my day and wanted to get the info out.

Will make a PR to update the documentation shortly.

Grafana 8 / Unified alerting is still beta / feature preview, on upgrades, unified alert rules may also be cleared before we make it the default alerting system, but we are working as fast as we can to get it there. Your feedback helps us get there so thank you!

**Comment by dmit2k** [comment]
It looks like I've caught another but similar bug: values and labels not being expanded in alert messages when using ELK datasource, even when using Math and Reduce expressions:

`Website {{ $labels.vhost.keyword }} has {{ $values.C.Value }} {{ $labels.http_status }} responses for last 3 hours`

Previewing alert displays a valid table of labels and values similar to what I get when using Prometheus datasource.

And one more thing... :) No alerts being sent out to Alertmanager contactpoint (or any other) while I can see them firing in Grafana UI.

@kylebrandt thank you for clarification, though a bit strange: Unified Alerting was so much advertised upon release of Grafana 8, and actual Grafana documentation points on its features, so I've got an impression it's now "official" production-ready way and not just a Beta preview.

**Comment by hoangmnsd** [comment]
I'm facing the same problem. My question is: when I using the "classic condition" operation, what should I use in alert message body?   
I've tried {{ .ValueString }} , and {{ $value }}  but it doesn't help.
