### ISSUE TITLE
Possibility to hide table header

### ISSUE THREAD

**Issue by costimuraru** [grafana/grafana#3783]
In order to gain some space on the main dashboard, it would be helpful to have an option in the table panel to hide the table header (the one containing "Metric"/"Max"/"Avg"/etc.).

**Comment by bergquist** [comment]
If you just remove the Panel title it will be smaller. 

![image](https://cloud.githubusercontent.com/assets/618863/12412794/f6d597a8-be89-11e5-8679-fcf2e55a21c6.png)

**Comment by costimuraru** [comment]
@bergquist, thanks for the quick response. I am actually referring to this:

![ss](https://cloud.githubusercontent.com/assets/952836/12439373/7e509bd4-bf38-11e5-8d50-12d1271473a0.png)

There's currently no way of hiding the header when dealing with a table panel.

**Comment by mattiaswolff** [comment]
+1

**Comment by michakrause** [comment]
+1

**Comment by bergquist** [comment]
@costimuraru sorry. I missed your reply :/ What's the reason to using table and hiding the header?

**Comment by michakrause** [comment]
The header takes a lot of space, especially on very small tables (2 rows for example).
As seen in the example from @costimuraru it also often contains no valuable information at all, because you can probably guess what column displays the metric, and which shows the value.

**Comment by RollingFred** [comment]
+1
I'm using a table to display log entries coming from ES. The content is self descriptive (timestamp, severity, text)
The header is unnecessary in our case (and the column headers are displaying field raw name, which is pretty ugly)

**Comment by majkinetor** [comment]
+1

If many tables have time/value format it doesn't convey any new information either.

**Comment by mckdev** [comment]
+1

**Comment by claudiutraistaru** [comment]
+1
I use this as a workaround to display a text value and no need for header

**Comment by chrisjacksonsw** [comment]
I too have used the table panel to display text from the grafana database as a workaround. In my case it's an html link to a query that allows the user to see where the metrics are coming from and dig a bit deeper into the information. If the single stat panel had an option to refer to an external link (generated dynamically from the database) this would be better.

**Comment by infa-kparida** [comment]
+1

**Comment by torkelo** [comment]
Implemented in new table panel in 7.0
