### ISSUE TITLE
Value mappings limited by gui / No scollbars

### ISSUE THREAD

**Issue by Beowolve** [grafana/grafana#37833]
**What happened**:
Value mapping dialog does not show a scrollbar if dialog does not fit on browser viewport.
The Cancel/Update buttons get inaccessible by the mouse cursor on a full HD Screen after 13-14 values. 

**What you expected to happen**:
If the list becomes too long, a scrollbar should be visible for the items and the cancel / update buttons should be visible at all times. Also the "Add a new mapping" button get pushed of the screen.

**How to reproduce it (as minimally and precisely as possible)**:
Go to value mappings and start adding new mappings, you will reach a point where you can't add any items limited by the gui.

**Anything else we need to know?**:
The view could be a little more compact, so that more values fit easy on a normal screen. Scrollbars should be added, but its better if you don't need them.

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: InfluxDB - doesn't matter...
- OS Grafana is installed on: Docker / Linux
- User OS & Browser: Windows / Chrome
- Grafana plugins: -

**Comment by torkelo** [comment]
this should be fixed in v8.1
