### ISSUE TITLE
Elasticsearch: Bucket script in term order by is not showing any results in grafana 8.0.6

### ISSUE THREAD

**Issue by BhoomikaAnghan** [grafana/grafana#37849]
**What happened**:  Bucket script in term order by is not showing any results in grafana 8.0.6 with elasticsearch data source

**What you expected to happen**: Order by Bucket script should show the results based on bucket script in the stats panel

**How to reproduce it (as minimally and precisely as possible)**:

1.Prepare Bucket script based on fields calculations in the series description
2.Use group by {field_name} and order by {Bucket Script}
3.Check query inspector error and error message on the stats panel
 
For more details check on community: https://community.grafana.com/t/elasticsearch-should-not-be-possible-to-use-bucket-script-in-term-order-by-in-grafana-8-0-6/51588?u=anghanbhoomika

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: Elasticsearch and 7.10.0
- OS Grafana is installed on: Red Hat Enterprise Linux 8.2 (Ootpa)
- User OS & Browser: Windows 10 and google chrome

**Comment by Elfo404** [comment]
as per https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-bucket-terms-aggregation.html pipeline aggregations (like Bucket Script) can't be used for ordering. 

The error here is that we are showing the bucket script in the order by select, which shouldn't happen.
Thanks for reporting this, I'll follow up with a PR to remove pipeline aggregations from the order by select.

**Comment by BhoomikaAnghan** [comment]
Hi,

Can you please provide me a solution for this as I am new to grafana? As per my requirement, I need to use bucket script in term order by if you are removing that option then could you please provide an alternate solution for this?

**Comment by Elfo404** [comment]
we are only removing that option from the UI because it's not supported by elasticsearch itself: https://discuss.elastic.co/t/ordering-terms-aggregation-based-on-pipeline-metric/31839

Grafana has no power there. apparently, you might have some luck using a bucket_sort aggregation (see: https://github.com/elastic/elasticsearch/issues/8486#issuecomment-768323340), but this is currently not possible in Grafana and I'm not completely sure it fits your use case, and it would be a separate feature request.

**Comment by BhoomikaAnghan** [comment]
> we are only removing that option from the UI because it's not supported by elasticsearch itself: https://discuss.elastic.co/t/ordering-terms-aggregation-based-on-pipeline-metric/31839
> 
> Grafana has no power there. apparently, you might have some luck using a bucket_sort aggregation (see: [elastic/elasticsearch#8486 (comment)](https://github.com/elastic/elasticsearch/issues/8486#issuecomment-768323340)), but this is currently not possible in Grafana and I'm not completely sure it fits your use case, and it would be a separate feature request.

Hi @Elfo404 ,

Thank you so much for your answer!. It would be a great feature of grafana if possible.
