### ISSUE TITLE
NewsPanel: CORS proxy deprecated and need to find an alternative

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/grafana#37841]
**What happened**:

Using the News Feed Visualisation (the rss reader), you can load a rss file to be displayed inside Grafana. If you load any rss file you will receive a CORS issue which is to be expected as the browser won't load content from a domain that is different from Grafana's root_url. It is possible to use the CORS proxy option, however this proxy has been deprecated since January 31 2021, and now no longer works.  This is explained here: https://github.com/Rob--W/cors-anywhere/issues/301

![image](https://user-images.githubusercontent.com/83230950/129200956-d2733eb5-aa41-4b38-b717-f4a0dbfa465e.png)

This means that no RSS feed will load from any valid RSS URL, unless the domain supports CORS or comes from the same root_url as Grafana. 

I have tried with a number of valid RSS feeds, and none I found so far support CORS:
https://www.nasa.gov/rss/dyn/breaking_news.rss
http://feeds.bbci.co.uk/news/uk/rss.xml
https://www.wired.co.uk/feed/rss

**What you expected to happen**:

Any valid RSS feed to load inside Grafana, either directly or through a CORS proxy

Grafana should remove the current CORS proxy as it has been deprecated, and one of the following solutions should be considered:
 - Switch to a different public CORS proxy. This has the downside that it too could be closed at any moment rendering the News feed plugin broken again
 - Host our own CORS proxy, accessible only by Grafana 
 - Grafana server itself downloads the raw XML file, and renders the output. This has the downside that Grafana server would need outbound access to an external resource, making it possible that in locked down environments this won't work
 - Another solution ?

**How to reproduce it (as minimally and precisely as possible)**:

Use any valid RSS feed, enable CORS proxy and observe the error message in the browser console: 
https://www.nasa.gov/rss/dyn/breaking_news.rss
http://feeds.bbci.co.uk/news/uk/rss.xml
https://www.wired.co.uk/feed/rss

You'll see an error like this: 
![image](https://user-images.githubusercontent.com/83230950/129201617-faa0f191-8ede-4f27-8ca9-c2d4d3b99f35.png)

**Anything else we need to know?**:

**Environment**: Centos 7
- Grafana version: Any Grafana with the News panel and CORS proxy. In this case Grafana 8.1.1
- Data source type & version: - 
- OS Grafana is installed on:
- User OS & Browser: Latest Chrome (Version 92.0.4515.131 (Official Build) (64-bit))
- Grafana plugins: News Feed Visualisation
- Others:

**Comment by 1tft** [comment]
You should make cors proxy feature configurable, so that everyone can configure his own proxy url.
For enterprise customers there should be offered a Grafana hosted Cors proxy.
I think over 90% of rss feed producers does not set cors header, so they are not usable with Grafana.

**Comment by dwyer125** [comment]
Would appreciate if this could be looked at sooner rather than later as all our rss feed panels have stopped working since Feb 1st
