### ISSUE TITLE
Elasticsearch: All metric names are Count for alert queries

### ISSUE THREAD

**Issue by urusha** [grafana/grafana#37846]
**What happened**:
Created ES alert for  `Count` with `Group by`
![image](https://user-images.githubusercontent.com/1746504/129207330-486cc38f-6907-42fa-a9e1-61aaa4429ddd.png)
Got multiple metrics in the graph (graph-old or new time series - no matter) with correct names, but all metrics names in the alert are `Count `
![image](https://user-images.githubusercontent.com/1746504/129210253-0c63d295-3c08-415b-8862-973e53808096.png)
No matter if aliasing is used or not.

**What you expected to happen**:
Correct metrics names in the alert

**How to reproduce it (as minimally and precisely as possible)**:
See what happen

**Anything else we need to know?**:
8.0.6 was OK

**Environment**:
- Grafana version: Version 8.1.0 (commit: 62e720c06b, branch: HEAD)
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Debian
- User OS & Browser: Linux, Firefox
- Grafana plugins:
- Others:

**Comment by tkukushkin** [comment]
Same problem after upgrading to 8.1.1

**Comment by torkelo** [comment]
@Elfo404 any ideas what this could be? Have we changed the backend metric naming scheme/alias interpolation? 

looks like https://github.com/grafana/grafana/pull/36132 is big one that changed between 8.0 and 8.1

**Comment by dsotirakis** [comment]
Should be fixed in `8.1.2`! Thanks for raising the issue @urusha!
