### ISSUE TITLE
Decimal precision does not apply to y axis

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#3784]
Grafana 2.6.0:

![image](https://cloud.githubusercontent.com/assets/89186/12404438/7fb32f1a-be33-11e5-87bf-35c06f25210c.png)

Reusing the same setting / introducing another one might be useful. Setting Y max is not an option for me since values can go in tens of thousands of %.

**Comment by torkelo** [comment]
The y axis decimals are automatically calculated based all series min/max  (or if fixed grid min/max is specified), there are some edge cases when the min/max range is very small where the auto decimal count can become to high, think there already are issues for that. 

The decimals options for the legend does not apply for the graph y axis.

**Comment by bobrik** [comment]
Can I have a link to existing issue to subscribe to updates? I tried searching before creating this issue.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/2759

**Comment by bobrik** [comment]
Thanks!

**Comment by waqark3389** [comment]
+1
