### ISSUE TITLE
Error reading InfluxDB

### ISSUE THREAD

**Issue by Jcbarraza** [grafana/grafana#37843]
Error reading InfluxDB
I've tried to set it up in every way possible. But I can't come up with the setup. I need help.

I use Windows  10
Grafana 8.1
![Sin título](https://user-images.githubusercontent.com/64224172/129203600-27d3108d-2eb0-4c37-b6ac-925b9efe0cca.png)

**Comment by dsotirakis** [comment]
Hello @Jcbarraza can you please provide more information on how/what you did and didn't get any luck?

**Comment by Jcbarraza** [comment]
I have made multiple configurations of different threads with the same problem but the result is the same 

https://community.grafana.com/t/unable-to-connect-influxdb2-0-to-grafana/48268

https://community.grafana.com/t/trouble-adding-influxdb-2-0-as-datasource/36490/29

**Comment by connorlindsey** [comment]
@Jcbarraza I'll close this issue for the moment because it seems like this is an issue with configuring your data source and should be followed up with on the community forum. If you see a specific bug report, please feel free to reopen the issue.
