### ISSUE TITLE
Prometheus Data Source Tooltip has misleading data

### ISSUE THREAD

**Issue by PeterZaitsev** [grafana/grafana#3785]
Hi,

I noticed the following in many Prometheus Based Dashboards.   It looks like  when the series disappears because it is zero/null and hiding zero/null is enabled tooltip will still show old value 

![image](https://cloud.githubusercontent.com/assets/3651746/12407306/2970abbe-be24-11e5-9c7c-5c049ff96d18.png)

As you can see in this case pessimistic_lock_index shown as it is 21 but you can see on the graph there are no metrics reaching that value

**Comment by torkelo** [comment]
This is related to this issue, a limitation/bug in how all series tooltip looks for values, it currently does handle non continous series very well. This is not a big issue for Graphite and InfluxDB that insert null values for missing values, but there is an issue for other time series stores and for queries that return metrics with different intervals, https://github.com/grafana/grafana/issues/3063

**Comment by mtanda** [comment]
This PR change datasource default behavior, fill null for missing data points.
https://github.com/grafana/grafana/pull/3661

The issue might be fixed by this.
