### ISSUE TITLE
Allow Grafana to tolerate small windows where backend DB is inaccessible

### ISSUE THREAD

**Issue by sandeepbangera** [grafana/grafana#37854]
### Discussed in https://github.com/grafana/grafana/discussions/37316

<div type='discussions-op-text'>

<sup>Originally posted by **dansimone** July 28, 2021</sup>
Currently, when Grafana's backend Mysql DB is unavailable, Grafana crashes almost immediately, even when not being actively used.  To make Grafana more fault tolerant, some improvements to this behavior might be to:
- Have Grafana remain alive, but respond with an error message indicating a backend issue.
- Have Grafana run on cached data for some period of time before either crashing or showing an error message indicating a backend issue.</div>

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). 

What does moving the issue mean? 

Firstly, it means we're keeping it open as a feature request. In moving this issue to our [GitHub Discussions](https://github.com/grafana/grafana/discussions) board, it will retain all the comments and labelling already part of the issue. 

Secondly, it signals we have no immediate plans to implement it, but would like to continue to engage with the idea or request. We hope to use the discussion thread to continue building use cases and evidence that can help us prioritize it later on down the road. It can also help everyone, as part of the Grafana community, have an opportunity to pick up issues for contribution which are clearly defined. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!

**Comment by pkolyvas** [comment]
@sandeepbangera - Discussions was the right place to create the feature request. I'm going to close this so we can discuss it there.
