### ISSUE TITLE
Elasticsearch table view Percentiles metric 

### ISSUE THREAD

**Issue by Elufimov** [grafana/grafana#3786]
Hi!
I try to use table view as describe here https://github.com/grafana/grafana/issues/3578 and bring Percentiles. And table show a empty cell. Here an example 
![](https://i.gyazo.com/a473673dd8597d63686940c6010282df.png)
![](https://i.gyazo.com/6363a2e6ed8c58e726d30349fd753bdf.png)

**Comment by a-lustin-parc** [comment]
+1

**Comment by s-titov-parc** [comment]
+1

**Comment by v-karbovnichiy-parc** [comment]
+1

**Comment by rdpanek** [comment]
Hi, any news? Elasticsearch and Percentiles is very usefull :-)

**Comment by qgemine** [comment]
+1

**Comment by MaximizedAction** [comment]
+1

**Comment by frostynova** [comment]
+1

**Comment by dylanBehetre** [comment]
+1 (il n'y a rien d'afficher car le JSON retourné par la requête ne contient pas la réponse)
![image](https://user-images.githubusercontent.com/10670549/27629906-1b5ab80c-5bf4-11e7-89fe-84309d8f9eb3.png)

![image](https://user-images.githubusercontent.com/10670549/27629920-258c09fc-5bf4-11e7-8c3c-cce5ae20a60b.png)

**Comment by bengoodwyn** [comment]
+1

**Comment by shafferjohn** [comment]
how to make it like this...

request time (seconds) from nginx log
 
|api_url|tp25|tp50|tp75|tp90|tp99|
|----|----|----|----|----|----|
|/api/login|0.5|1.2|1.4|1.7|2.0|
|/api/search|1.0|2.0|2.2|2.7|3.7|
|/api/logout|0.1|0.1|0.2|0.4|1.0|

**Comment by SumantaSarathiChakraborty** [comment]
+1 Any update on this ?? Any workaround will also be helpful

**Comment by brunofitas** [comment]
+1

**Comment by ddoice** [comment]
+1
IMHO the table is quite useless without percentiles.

**Comment by marefr** [comment]
Had a look at this and fix is quite simple, but will need some more work. Will open a PR soon. 

Someone wrote it doesn't work when group by date histogram, but I can confirm it does on Grafana 6.0-pre (master) at least so could be a temporary workaround:
![image](https://user-images.githubusercontent.com/1668778/52948526-e9ea0c00-3379-11e9-88bc-9193dcf3240d.png)
