### ISSUE TITLE
Geomap with influxDB 2.0.7

### ISSUE THREAD

**Issue by tatsutaigu** [grafana/grafana#37861]
**What happened**:
Regarding geohash, marker shows geohash when mouse over.
I hope to show marker value.
![image](https://user-images.githubusercontent.com/44219065/129305230-371a8557-05f2-433d-ae7b-1a73b5819e3a.png)

Regarding coords, it does not shows marker.
![image](https://user-images.githubusercontent.com/44219065/129304650-f9d11f43-46a4-47d9-8990-e9879a270506.png)

When latitude and longitude are set same value, marker is shown.
but position is wrong because latitude and longitude are set same value.
And, it shows latitude (or longitude) value. I hope to show marker value.
![image](https://user-images.githubusercontent.com/44219065/129305077-9fac3edc-4921-4ff8-860b-6c6a084660be.png)

**Environment**:
- Grafana version:8.1.1
- Data source type & version: InfluxDB 2.0.7
- OS Grafana is installed on: ubuntu(20.04) on docker
- User OS & Browser: windows10 / Firefox 91
- Grafana plugins: geomap
- Others: influxDB line protocol =
 `test,Location=test1 A=60,geohash=\"u10hbp00rc\",latitude=51.4984620052715,longitude=0.000`
![image](https://user-images.githubusercontent.com/44219065/129305736-f49735cd-c37c-497a-95fa-b34ce518d841.png)

**Comment by gabor** [comment]
hi @tatsutaigu thanks for the detailed investigation. i looked into this, and what i found is that all 3 modes (lookup, coordinates, geohash) require the same data-format. basically, if you enable [table view] at the top of the panel, what you want to see is a table like this:

|time|country|value|
|-----|----|----|
|.......|GB|72|
|.......|AU|51|

or

|time|geohash|value|
|-----|----|----|
|.......|hash1|72|
|.......|hash2|51|

or

|time|coord_lat|coord_lng|value|
|-----|----|-----|----|
|.......|lat1|lng1|72|
|.......|lat2|lng2|51|


to reach this, there are many ways, i will describe some:

### country names as tags

you inserted them as:
```
test_lookup_tag,country=GB val=42
test_lookup_tag,country=AU val=22
```
you are running a flux-query like this:
```
from(bucket: "mybucket")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "test_lookup_tag" and r._field == "val")
```
add a "Transform" named "labels to fields" (do not select anything inside the transform), and you should get the table-display as described.
now choose the "lookup" option in the geomap-panel, pick "country" as the lookup-field, pick "val" as the marker-size.
this way you get markers sized based on the value-field, the mouse-hover-popup will show everything from the "table row", meaning timestamp+country_code+value

### coordinates in fields

you inserted them as:
```
test_coords_field lat=number1,lng=number2,val=42
test_coords_field lat=number3,lng=number4,val=22
```

(where `number*` are numbers, not strings)

you are running a flux query like this:
```
from(bucket: "mybucket")
    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
    |> filter(fn: (r) => r._measurement == "test_coords_field")
    |> filter(fn: (r) => r._field == "lat" or r._field == "lng" or r._field == "val")
````
add a "Transform" named "Outer join" (you can pick "Time" inside the transform), and you should get the table-display as described.
now choose the "coords" option in the geomap-panel, pick "lat (base field name)" for latitude-field, and pick "lng (base field name)" for longtitude-field, and "val (base field name)" for marker-size. this way you get markers sized based on the value-field, the mouse-hover-popup will show everything from the "table row", meaning timestamp+country_code+value

you can probably achieve this result also by modifying the flux-query to do the join inside flux but using the transform was simpler for my tests.

does this explain the situation, or is there something you'd like to change?

**Comment by tatsutaigu** [comment]
Hi,@gabor

It is strange.

Line Protocol is
`test,Location=test1 lat=51.4984620052715,lng=0.000,val=60`

table view is different from your example.
I can see 3 test = [measurement].
And, lat, lng and val are independence.
![image](https://user-images.githubusercontent.com/44219065/129362669-c9741102-1e19-4f24-98bb-76b6eedb8412.png)

![image](https://user-images.githubusercontent.com/44219065/129363034-a9552891-b4eb-4709-be10-89c8ed58cad2.png)

![image](https://user-images.githubusercontent.com/44219065/129363135-83494b1e-b4b2-4ecb-a72e-605f08243795.png)

![image](https://user-images.githubusercontent.com/44219065/129363273-d6875ebf-87b6-415d-853f-a2a268bdad91.png)

**Comment by gabor** [comment]
@tatsutaigu did you add the "Transform" "outer join"?

**Comment by tatsutaigu** [comment]
@gabor , @N3v3R3nD 

Thank you for your advice.
it could show data on correct position.
`Outer json` or ` Merge` on `Transform` effectived.
