### ISSUE TITLE
Annotations using datasource-type variable as data source throws an exception interrupting initial display

### ISSUE THREAD

**Issue by w4rgrum** [grafana/grafana#37867]
**What happened**:

Since upgrade from Grafana v7.x to Grafana v8.x one of our dashboard does not display anything at first load (empty panels), then clicking on refresh displays the data properly.

At first load console is showing the below error:
`Uncaught Object { message: "Datasource named ${datasource} was not found" }`

After some investigations it seems the issue is that our Annotations for this dashboard are using a datasource-type variable called "datasource" as datasource. Setting-up a hard value for the datasource instead of using a variable fixes the issue (but is not what we want for those Annotations). It seems variables are not resolved when Annotations queries are triggered at first load.

**What you expected to happen**:

Dashboard displays data at first load as usual.

**How to reproduce it (as minimally and precisely as possible)**:

1) Go to a dashboard that works fine
2) Add a datasource-type variable
3) Create an Annotation using this datasouce-type variable as data source
4) Save dashboard
5) Reload page in browser or load a new page with your dashboard, you should see the error in your console and no data displayed in the panels (clicking on the refresh button of the dashboard then displays the panels data)

**Anything else we need to know?**:

no

**Environment**:
- Grafana version: v8.1.1 (90c87a52f7)

**Comment by ashharrison90** [comment]
hi @w4rgrum 👋 

i believe we've just fixed this with https://github.com/grafana/grafana/pull/37883, which will be released in 8.1.2
if you're still seeing the issue in 8.1.2 please add a comment and we'll reopen

thanks! 😄
