### ISSUE TITLE
New Table panel - Text color is ignored when using override option for "value mapping" 

### ISSUE THREAD

**Issue by camsellem** [grafana/grafana#37869]
**What happened**:

Trying to change the color of the text for a specific column in my table panel. Using the override option -> value mapping -> set color

Using Google Sheet Data Source

**What you expected to happen**:

Text color to change depending on the value (High - Red / Normal - green / Low - blue)

**How to reproduce it (as minimally and precisely as possible)**:

Panel is available here -> https://ops.grafana.net/d/gqDkmsG7k/activity-dashboard?orgId=1&var-fiscal_period=THIS_FISCAL_QUARTER&editPanel=21

![image](https://user-images.githubusercontent.com/3879044/129336767-76133039-80fc-415b-93af-46ff9e757c19.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Brave
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
you need to set a cell display mode for the column as well that uses the color (Color background, or color text)
