### ISSUE TITLE
No alert for influx db text query

### ISSUE THREAD

**Issue by basva923** [grafana/grafana#37872]
**What happened**:
The alert "Template variables are not supported in alert queries" was received for a influxdb query without variables:
SELECT hrStorageUsed / hrStorageSize FROM "...." WHERE ("storageDescription" = '....') GROUP BY "source"

The alert itself does work however.

**What you expected to happen**:
The alert message should not be there.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new graph
2. Select an influxdb data source
3. Build the following TEXT query (needed since the gui doesn't support my query?):  SELECT hrStorageUsed / hrStorageSize FROM "...." WHERE ("storageDescription" = '....') GROUP BY "source"
4. Create an alert => Error message

**Environment**:
- Grafana version: 5.4.5
- Data source type & version: influx db (1.7.6-alpine docker)
- OS Grafana is installed on: Linux (docker)
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
I am sorry but we are not really supporting such an old Grafana version (unless the 5.4.5 is a typo). Please try updating if you can.
