### ISSUE TITLE
TimeSeries: render order for bars, lines, and points vs. query order

### ISSUE THREAD

**Issue by nikki-kiga** [grafana/grafana#37904]
**What happened**:

Discovered and discussed through #36882

Currently, a series that is set to display points will render before a bars series depending on the query order.

**What you expected to happen**:

Render bars, lines, and then points regardless of query order

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/42276368/129417703-30efad3b-a267-4dee-8d50-7160ddfdb3b8.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: gdev-testdata+
- OS Grafana is installed on: OSX
- User OS & Browser: OSX & Chrome, Firefox, and potentially others
- Grafana plugins: none
- Others:

**Comment by codeincarnate** [comment]
Going to close this one in favor of #36882 as it has far more detail.
