### ISSUE TITLE
[Playlist] Add searches for dashboards as playlist items.

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#3790]
Instead of just adding one specific dashboard it should also be possible to add a search for ex "backend" and when the playlist starts playing, all the dashboards in the search result for "backend" should be played. This way new dashboard can be added and automatically played.

**Comment by utkarshcmu** [comment]
Instead of search results, playlist of the dashboards for a single/multiple tag(s) has more requirement by the users as they tag the dashboards. Also, whenever a new dashboard is assigned a tag, it should automatically join the playlist. How about this? :)

**Comment by bergquist** [comment]
I think tags and searches should be supported. 

Right now https://github.com/grafana/grafana/blob/master/pkg/api/playlist.go#L104 only gather dashboards based on id. But it should also be able to gather dashboards based on searches and tags.

**Comment by mattttt** [comment]
@bergquist Thanks for reminding me of that, I have to think about how to include that in this view.

![editplaylist](https://cloud.githubusercontent.com/assets/2886187/12536888/1181a35e-c280-11e5-88f8-903f3324798b.png)
