### ISSUE TITLE
Geomap:  "Cannot read property 'length' of undefined" when query returns empty

### ISSUE THREAD

**Issue by HenrikRolandHansen** [grafana/grafana#37911]
**What happened**:
Geomap displays "Cannot read property 'length' of undefined" when query returns empty. Even after the time period is selected again to contain data the Geomap displays the error.

Entering edit mode shows the data again, but after hitting apply it still shows the error message.

**How to reproduce it (as minimally and precisely as possible)**:
scroll time range until no data is returned and then scroll or reset time range to periode with data.

https://user-images.githubusercontent.com/8969659/129487178-0df5105e-8bec-4e23-ba5f-8cf7c274b5e6.mp4

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: Influxdb
- OS Grafana is installed on: Raspberry pi
- User OS & Browser: Google Chrome and Edge

**Comment by HenrikRolandHansen** [comment]
any update on this

**Comment by dprokop** [comment]
@HenrikRolandHansen sorry for late response. Could you please:
- provide us with a stack trace from the console
- share your dashboard JSON if possible
- Share panel's rawe data from the Panel Inspect (in CSV format)

The above will help us reproduce the issue.

I've tried reproducing this issue agains main and 8.1.0 and didn't manage to.

**Comment by HenrikRolandHansen** [comment]
@dprokop attached the requested information.

Attached panel Json and csv data I use with the map. Note the issue is happening if there is no data returned from the query.  So it should be fairly easy to simulate via Influxdb. Not sure where to find the stack trace 

[panel Json.txt](https://github.com/grafana/grafana/files/7129008/panel.Json.txt)
[DMI lyndata-data-2021-09-08 15_03_49.csv](https://github.com/grafana/grafana/files/7129019/DMI.lyndata-data-2021-09-08.15_03_49.csv)

Console:

vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2 TypeError: Cannot read properties of undefined (reading 'fields')
    at zt (utils.ts:8)
    at Bt (scale.ts:11)
    at Object.update (heatMap.tsx:85)
    at hi.dataChanged (GeomapPanel.tsx:134)
    at hi.shouldComponentUpdate (GeomapPanel.tsx:90)
    at hi (vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2)
    at za (vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2)
    at qu (vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2)
    at Os (vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2)
    at _s (vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2)
iu @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
i.componentDidCatch.n.callback @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
li @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
du @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Ss @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.unstable_runWithPriority @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Uo @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
ks @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
ds @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.unstable_runWithPriority @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Uo @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Wo @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Vo @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
us @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
enqueueSetState @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
m.setState @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
onDataUpdate @ PanelChrome.tsx:229
next @ PanelChrome.tsx:135
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.notifyNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e._trySubscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
c @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._innerSub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._tryNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.nextInfiniteTimeWindow @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
next @ PanelQueryRunner.ts:268
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.notifyNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.notifyNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.notifyNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Promise.then (async)
t @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
c @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._innerSub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._tryNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Promise.then (async)
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e._trySubscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.connect @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
c @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._innerSub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._tryNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e._trySubscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ backend_srv.ts:87
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ ResponseQueue.ts:30
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ ResponseQueue.ts:35
(anonymous) @ FetchQueueWorker.ts:54
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.notifyNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
c @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._innerSub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._tryNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ FetchQueue.ts:76
(anonymous) @ FetchQueue.ts:55
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ FetchQueue.ts:59
(anonymous) @ backend_srv.ts:92
e._trySubscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.connect @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
c @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
c @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._innerSub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._tryNext @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e._trySubscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.call @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
e.subscribe @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
pipeToSubject @ PanelQueryRunner.ts:264
run @ PanelQueryRunner.ts:244
async function (async)
run @ PanelQueryRunner.ts:221
runAllPanelQueries @ PanelModel.ts:298
(anonymous) @ PanelChrome.tsx:251
t.__tryOrUnsub @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t._next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.next @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
n @ EventBus.ts:36
FnK4.c.emit @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
publish @ EventBus.ts:26
refresh @ PanelModel.ts:316
startRefresh @ DashboardModel.ts:335
(anonymous) @ actions.ts:557
async function (async)
(anonymous) @ actions.ts:554
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
o @ store.ts:27
timeRangeUpdated @ DashboardModel.ts:322
refreshDashboard @ TimeSrv.ts:241
setTime @ TimeSrv.ts:297
(anonymous) @ DashNavTimeControls.tsx:64
onChange @ TimePickerWithHistory.tsx:20
(anonymous) @ TimeRangePicker.tsx:56
M @ TimePickerContent.tsx:175
onChange @ TimeRangeOption.tsx:62
Ue @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
$e @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Or @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Er @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Ne @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
(anonymous) @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
jr @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Zt @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Xt @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
t.unstable_runWithPriority @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Uo @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Re @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Kt @ vendors~app.d7cfb4e56c8be9229275.js:sourcemap:2
Show 160 more frames
PerformanceBackend.ts:39 performance (3) [{…}, {…}, {…}]

**Comment by dprokop** [comment]
@ryantxu do you mind having a look at this issue?
