### ISSUE TITLE
fix nightly scan on docker image https://drone.grafana.net/grafana/grafana/31223/1/3

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#37918]
Nightly scan keeps failing even after our previous fix. Need to update dependencies.

**Comment by orgads** [comment]
When do you plan to push the new images?

**Comment by dsotirakis** [comment]
@orgads, hello!
Next release, 8.1.3, happening this week :)

**Comment by orgads** [comment]
Thank you.
