### ISSUE TITLE
More control over the number of datapoints 

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#3791]
As far as I can remember, Grafana by default requests one datapoint per pixel from the TSDBs. When you have selected a large timespan like 60 days, that can lead to a lot of datapoints, especially if the graph is full screen. I know that you can set the group by time interval but that does not scale as you select larger timespans.

So a slider would be cool that influences after how many pixels a datapoint should be generated. The max setting would be the same as today's behavior and the min setting would for example generate a datapoint each 500th pixel or so. So no matter how big the timespan and how wide the graph gets, the space between the points would be the same.

In the screenshot below, you can see how the response size and time significantly drops when you enlarge the  'Group by time interval'. But even with the largest setting, there are more than enough datapoints for this timespan.

<img width="593" alt="" src="https://cloud.githubusercontent.com/assets/2163464/12418469/cbbb4c36-beaf-11e5-890f-5183f9c19774.png">

This example uses elasticsearch whose response format is quite chatty...

**Comment by mtanda** [comment]
+1

**Comment by benrubson** [comment]
#3982 will help you !

You will be able to define an interval variable with bigger steps (so with less data points).
You will also be able to tune it with a minimum auto interval value. Useful when for example you have new points every X seconds, and you do no want to add interpolated points between them, you can define X as the minimum value (or of course to the value you want).

Then you set this variable as the down sample value in your source, and you're done !

I had the same issue as yours, too many data points, now it's OK.

![one](https://cloud.githubusercontent.com/assets/6764151/13553169/03482224-e380-11e5-9797-0a6996f79040.png)

![two](https://cloud.githubusercontent.com/assets/6764151/13553172/0ae436da-e380-11e5-99d2-bb4100503e23.png)
