### ISSUE TITLE
Add setting configuration to datasource

### ISSUE THREAD

**Issue by JackyWoo** [grafana/grafana#37923]
### Discussed in https://github.com/grafana/grafana/discussions/37922

<div type='discussions-op-text'>

<sup>Originally posted by **JackyWoo** August 16, 2021</sup>
#### Motivation
I use grafna with MySQL DataSource and I use 'group_concat' function which has a result longer than default value 1024. So I want to change the setting 'group_concat_max_len'. But I can not find out the configuration. 

I think maybe there are other cases like that. So add setting configuration to datasource maybe useful.</div>

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). 

What does moving the issue mean? 

Firstly, it means we're keeping it open as a feature request. In moving this issue to our [GitHub Discussions](https://github.com/grafana/grafana/discussions) board, it will retain all the comments and labelling already part of the issue. 

Secondly, it signals we have no immediate plans to implement it, but would like to continue to engage with the idea or request. We hope to use the discussion thread to continue building use cases and evidence that can help us prioritize it later on down the road. It can also help everyone, as part of the Grafana community, have an opportunity to pick up issues for contribution which are clearly defined. 

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Looking forward to the discussion!

**Comment by pkolyvas** [comment]
Hey @JackyWoo - Discussions was the right place to create the feature request. I'm going to close this so we can discuss it there.

**Comment by JackyWoo** [comment]
@pkolyvas Thank you.
