### ISSUE TITLE
Feature request: dashboard edited by "xyz"

### ISSUE THREAD

**Issue by joakimberglund** [grafana/grafana#3793]
If possible it would be nice I could see who last edited a dashboard or graph displayed on each page.

"Edited by john, 2016-01-15 11:27:33"

**Comment by bergquist** [comment]
You can see that in
Dashboard settings -> Metadata

**Comment by torkelo** [comment]
only in master (and pre release builds)

**Comment by bergquist** [comment]
Oh yea! Sorry :)
