### ISSUE TITLE
Annotation Query Failed Cannot read property 'to' of undefined - Azure dashboards

### ISSUE THREAD

**Issue by DanielA2119** [grafana/grafana#37940]
Upgrading Grafana opensource from 8.0.2 to 8.1.0 or 8.1.1 causes an error to appear during refresh of previously created dashboards we use to monitor Azure applications.

Annotation Query Failed
Cannot read property 'to' of undefined

![image](https://user-images.githubusercontent.com/69923076/129625426-1ddbc137-3e9c-4833-87b0-23d61be3b388.png)

The annotations section of the dashboards are empty. 
I've also unchecked the box for "When enabled the annotation query is issued every dashboard refresh" and issue persists.

![image](https://user-images.githubusercontent.com/69923076/129625757-f7c9f5fa-4116-466a-b290-e1074e5daec3.png)

Here's the JSON for annotations in the dashboards.

{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },

It's a very frustrating alert especially if you're refresh is at a fast rate.

Reverting back to 8.0.2 resolves the issue.  

Very similar issue to https://github.com/grafana/grafana/issues/37819. 

Any ideas?

Thanks.

**Comment by nechry** [comment]
I also have this issue, in the log someting interesting is added:
```
t=2021-08-19T07:56:12+0000 lvl=eror msg="Browser console error" logger=plugins.backend pluginId=grafana-image-renderer msg="AnnotationSrv.query error JSHandle@error" url=https://localhost/public/build/app.843e85298b12060ea650.js line=4716.000 column=9599.000
t=2021-08-19T07:56:13+0000 lvl=eror msg="Browser console error" logger=plugins.backend pluginId=grafana-image-renderer msg="WebSocket connection to 'wss://localhost/api/live/ws' failed: Error during WebSocket handshake: Unexpected response code: 403" url=https://localhost/public/build/vendors~app.843e85298b12060ea650.js line=1.000
```

**Comment by zuchka** [comment]
Thanks @nechry and @DanielA2119,

I think we should close this as a duplicate in favor of https://github.com/grafana/grafana/issues/37819.%C2%A0

Can reopen if the issues diverge, however 👍
