### ISSUE TITLE
Dashboard UIDs are not preserved when importing/creating dashboards thru importing .json file

### ISSUE THREAD

**Issue by vishiy** [grafana/grafana#37944]
**What happened**:
When i import an existing .json dashboard file, i see the UID for the imported dashboard is getting changed, when import is completed.
[Kubernetes_Compute Resources_Namespace(Pods).txt](https://github.com/grafana/grafana/files/6996122/Kubernetes_Compute.Resources_Namespace.Pods.txt)

**What you expected to happen**:
Dashboard UIDs preserved when importing dashboards as .json (unless there is a colllsion between UIDs between whats imported v whats already in the grafana instance)

**How to reproduce it (as minimally and precisely as possible)**:
    
See an attached sample dashboard. UID in there is '85a562078cdf77779eaa1add43ccec1e'. But in my case after import i see a shorter/modern UID 'Wx8Ori77z'.  Grafana version i am trying to import it in to is 'Grafana v8.0.6 (68fe9e3431)' .

**Anything else we need to know?**:

- Grafana version:
 v8.0.6 (68fe9e3431)

**Comment by mitulk** [comment]
Looks like the UID is preserved only if the user chooses to click the "Change uid" button, which seems backward.

**Comment by joshhunt** [comment]
Looks like the provided dashboard has an old style of UID which is migrated to a new style once imported, and the "Change UID" button skips this migration and takes the input verbatim (allowing you to change it in the process).

If I export a new dashboard, and reimport it, i notice that the UID is preserved.

**Comment by axelavargas** [comment]
Maybe @ying-jeanne can help us here :), as @joshhunt mentioned it seems we have a new style for our UID in v8.x compared with older versions like 7.5.x, is this the expected behaviour Ying?

**Comment by ying-jeanne** [comment]
Hi I am not aware of this, I think it should relate to a history when we introduce the new UID format before I join the team, I reckon @marefr would have more context about it.

**Comment by marefr** [comment]
I can reproduce on [play](https://play.grafana.org/) (v8.1.2) and main (856cb1d80f81ed683b7990aaf8ab0e89433df0f1). This definitely seems like a bug to me and it seems like frontend not are passing the uid when not clicking on the `Change uid` button and importing the dashboard.

Request payload when importing the attached dashboard:
![Selection_1034](https://user-images.githubusercontent.com/1668778/130760741-cf0d98b0-2459-4f7f-bbb0-a3d72059f162.png)

**Comment by marefr** [comment]
Passing this back to @grafana/grafana-frontend-platform

**Comment by hugohaggmark** [comment]
Thanks @ying-jeanne and @marefr, @axelavargas can you have a look at this one, I mean as you've already started some initial investigation? Thank you

**Comment by joshhunt** [comment]
nice stuff @axelavargas and @marefr !!!
