### ISSUE TITLE
Plugins: Catalog should not display links for enterprise plugins

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#37951]
When viewing details of an enterprise plugin we shouldn't show the links in the header to repo, license etc as users cannot access the github links.

**Comment by yesoreyeram** [comment]
@jackw - Enterprise plugins will be removing those internal URLs in their next releases and replace them with publicly accessible URLs. So I think this should be okay to keep those URLs.

CC @josiahg

**Comment by ryantxu** [comment]
Great -- will close this and track it in https://github.com/grafana/integrations-team/issues/209
