### ISSUE TITLE
Grafana Annotations are not working fine

### ISSUE THREAD

**Issue by hemanthog** [grafana/grafana#3796]
Grafana Annotations are not working fine

Grafana version: 2.6
Influxdb version: 0.9

Getting this error after saving the annotation on grafana UI: Annotations error
InfluxDB Error: Cannot read property 'message' of null

I am successfully creating events from CLI of influxdb

Not sure why the annotations are not working 

Please help me

**Comment by hemanthog** [comment]
![grafana annotation](https://cloud.githubusercontent.com/assets/16670526/12438315/32c9ee92-beeb-11e5-8e68-fc935a67acf0.png)

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/12445234/72ea70f0-bf63-11e5-9119-db01c2cafaab.png)

Works fine here, can you open chrome dev tools & network tab and look at the response from InfluxDB? Also might be some error in the js console

**Comment by hemanthog** [comment]
Hello torkelo,

Thank you for the response.

It might be working good for you, i got that error for annotations and all of my dashboard's are working fine.

I am able get the results when i query in the CLI

curl -i -XPOST 'http://common1.psolv.local:8086/write?db=events' --data-binary 'event,host="hemanth_desktop",type="end" text="TestRun End"    1453251635000000000'

Results:

> select text, type, host from event
name: event
-----------
time			text		type	host
1453249810000000000	TestRun Start	"start"	"hemanth_desktop"
1453251635000000000	TestRun End	"end"	"hemanth_desktop"


But when i do the same thing in grafana, i got that error and annotations are not getting created.

js console looks good.

**Comment by torkelo** [comment]
Check chrome dev tools network tab for the request and response , try specifying column mapping
