### ISSUE TITLE
BarChart: Long x-axis values are not readable

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#37966]
In case when the x-axis value labels are wider than the bars themselves it's very easy to produce a bar chart that's hardly readable:

![image](https://user-images.githubusercontent.com/2376619/129735739-3b52d0b9-a4c7-479c-b785-b170b0722a7d.png)

Two alternative solutions to mitigate this issues are:

1. Google Data Studio alternates the y position of label to produce readable x-axis value labels(when theres enugh space) or rotates them:

 | Enough space | Limited space  |
|---|---|
|![image](https://user-images.githubusercontent.com/2376619/129736491-1c4f3b4c-1fde-4688-b098-0b7330729b45.png)|![image](https://user-images.githubusercontent.com/2376619/129736654-188bd186-449f-4c5c-9207-19a102a06480.png)|
  
2. Google Sheets renders the x-axis value labels either rotated (when there's enough space) or vertically:

| Enough space | Limited space  |
|---|---|
|![image](https://user-images.githubusercontent.com/2376619/129736221-373781a6-1e81-437e-9013-34929e7a40a9.png)|![image](https://user-images.githubusercontent.com/2376619/129736277-846b5fd9-569a-4545-b77f-259bb801720e.png)
  

uPlot already allows us to rotate the labels with the axis config- this can be seen in the [Box & Whiskers demo](https://leeoniya.github.io/uPlot/demos/box-whisker.html). What we need to do is to detect the bar/bars group width vs value label width and apply the rotation accordingly.

Test data for the charts above:
```csv
"author","commits"
conda-forge-coordinator,62
Curt Clifton,54
armaneshaghi,22
Matthew Weier O'Phinney,17
nobody,13
Wassim Chegham,13
grothoff,11
Jenkins,9
CI Pool Trigger Resource,9
spectre360,6
(no author),6
hellcatv,6
Maks,5
Maks3w,5
Marco Pivetta,5
Greg Burek,5
sdavis,5
dustymc,5
themedropbox,5
Syed Jafri,5
Jim Regan,5
BillSkiCO,5
Nerd Guide,4
Mario Cho,4
nguyennam9696,4


```

**Comment by leeoniya** [comment]
the other part of this if figuring out the proper x axis height (or bottom padding) to prevent label clipping once rotated. uPlot's rotation does not handle this for you. i'd probably start with doing a text ellipsis past a fixed max length, measuring longest label, then trig-ing the bbox at the desired rotation angle and grabbing the new height from that.

**Comment by dprokop** [comment]
Related feature request: https://github.com/grafana/grafana/issues/3591
