### ISSUE TITLE
Obfuscate external_image_storage.azure_blob Account Key in admin UI

### ISSUE THREAD

**Issue by billabongrob** [grafana/grafana#37970]
**What happened**: Used Azure Blob as external_image_storage.  Account Key is presented in the admin settings hostname/admin/settings

**What you expected to happen**: Account Key is obfuscated with asterisks similar to auth.azuread.client_secret

**How to reproduce it (as minimally and precisely as possible)**:  Configure external_image_storage.azure_blob

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.10
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: Mac / Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
can confirm that `account_key` is visible in Server Admin settings view:

<img width="636" alt="CleanShot 2021-08-17 at 13 33 01@2x" src="https://user-images.githubusercontent.com/37156449/129813979-2b2698e3-1172-49e2-8a39-7ffb922c65cc.png">
