### ISSUE TITLE
Prometheus Data source with SSE Errors: "failed to query data: no http method provided"

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#37976]
**What happened**:

Works: 
![image](https://user-images.githubusercontent.com/1692624/129776324-28d0087a-4909-4148-bea8-a036c968a942.png)

Does not work (Error):

![image](https://user-images.githubusercontent.com/1692624/129776557-d4e236c3-6b16-4dd6-96ee-c3d3ce1a53b3.png)

**What you expected to happen**:
Used to work for me, so guess something changed and needs to be updated, not sure what I missed yet though.

**Anything else we need to know?**:
Once an SSE operation is added, the query is routed through the backend.

**Environment**:
- Grafana version: d93d989a5a (origin/main)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
We have different paths right now for backend and front end so there can be differences and bugs we did not see. We are working on refactoring so we will only use the backend path: https://github.com/grafana/grafana/issues/37784. @kylebrandt is this something that needs to be prioritized or can it wait for that refactor (it is already in progress)

**Comment by kylebrandt** [comment]
> @kylebrandt is this something that needs to be prioritized or can it wait for that refactor (it is already in progress)

I'm not quite sure as I haven't heard of other repros yet - so maybe this is just me? If it isn't just me, then it is an issue I think because all Grafana managed alerts in the new alerting system using prometheus will not work.

**Comment by kylebrandt** [comment]
Seems to have been introduced in https://github.com/grafana/grafana/pull/37358

**Comment by marefr** [comment]
Seems like fallback to the default is missing here https://github.com/grafana/grafana/blob/9a71cec1f05a1021ec9e57e9fe1acb376a1fe9f3/pkg/tsdb/prometheus/prometheus.go#L83-L86
