### ISSUE TITLE
Grafana alerts(old) random evaluation time

### ISSUE THREAD

**Issue by bad3bs** [grafana/grafana#37989]
Grafana version: 8.x (docker)

Alerts(old) with evaluate 24h or 1440min occur at random time.
Evaluate 1m, 5m, 10m  works as expected.

**Comment by zuchka** [comment]
Hi @bad3bs 

Thank you very much for reporting this issue. Can you please provide more details on how to reproduce this issue? Anything that can help the team move faster and help get you unblocked 👍

**Comment by bad3bs** [comment]
Here one of test alert rules:

I made alert rule at 2021-08-16 22:05:39 evaluated interval 1440m
Alerting happend at 2021-08-17 08:00:03

![test_alert](https://user-images.githubusercontent.com/52122817/130156443-59432902-0655-4d26-8386-b048d0eac791.png)

query:

![test_query](https://user-images.githubusercontent.com/52122817/130156479-32d64732-a3e2-4496-913a-766416333887.png)

**Comment by peterholmberg** [comment]
@zuchka moving this to the backend board since evaluation does not happen in the frontend

**Comment by JohnnyQQQQ** [comment]
@bad3bs how does your setup look like? Do you use something like Kubernetes to orchestrate your docker containers? We suspect that this could be caused by restarting the docker container as this would result in the scheduler resetting.

**Comment by bad3bs** [comment]
> @bad3bs how does your setup look like? Do you use something like Kubernetes to orchestrate your docker containers? We suspect that this could be caused by restarting the docker container as this would result in the scheduler resetting.

Yes deploy in k8s, but pods don't restart, i checked it several times.
