### ISSUE TITLE
valueString issue in Unified Alarms

### ISSUE THREAD

**Issue by gorkem2020** [grafana/grafana#37995]
> {
    "receiver": "AWS-API",
    "status": "firing",
    "alerts": [
        {
            "status": "resolved",
            "labels": {
                "alertname": "room52 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:10:09.4695512Z",
            "endsAt": "2021-08-08T09:39:09.4695512Z",
            "generatorURL": "......",
            "fingerprint": "01fae9f107e8bd51",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room52} value=2.365125572430543 ]"
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room44 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:39:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "b05d3969851e0d8b",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": ""
        },
        {
            "status": "firing",
            "labels": {
                "alertname": "room05 alert"
            },
            "annotations": {},
            "startsAt": "2021-08-08T09:36:09.4695512Z",
            "endsAt": "0001-01-01T00:00:00Z",
            "generatorURL": "......",
            "fingerprint": "58da6e7b8acf20db",
            "silenceURL": "......",
            "dashboardURL": "",
            "panelURL": "",
            "valueString": "[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room05} value=1.5318855962592126 ], 
							[ metric='toxic_gas_level' labels={id=0451, city=paris, location=room05} value=1.144295316738316 ]"
        }
    ],
    "groupLabels": {},
    "commonLabels": {},
    "commonAnnotations": {},
    "externalURL": "https://example.com:3000/",
    "version": "1",
    "groupKey": "{}:{}",
    "truncatedAlerts": 0,
    "title": "[FIRING:6]  ",
    "state": "alerting",
    "message": "some message"
}

**What happened**:
1-) 'valueString' information is **empty** for '_firing_' notification. and **non-empty** for '_resolved_'

**What you expected to happen**:
1-) 'valueString' should **not be empty** for '_firing_' notifications. and should be **empty** for '_resolved_' notifications.

**Anything else we need to know?**:

**Environment**: docker image grafana/grafana:8.1.0
- Grafana version: 8.1.0
- Data source type & version: influxdb 2.0.7
- OS Grafana is installed on: docker. alpine.
- User OS & Browser: Mozilla, chrome
- Grafana plugins: none
- Others:

**Comment by zuchka** [comment]
Hi @gorkem2020 

Thank you very much for reporting this issue. Can you please provide more details on how to reproduce this issue? Anything that can help the team move faster and help get you unblocked 👍

**Comment by gorkem2020** [comment]
> 
> 
> Hi @gorkem2020
> 
> Thank you very much for reporting this issue. Can you please provide more details on how to reproduce this issue? Anything that can help the team move faster and help get you unblocked 👍

I have 2 simple queries which evaluate some values for the last 1 hour. and a simple condition. I took some screenshots. 


![1](https://user-images.githubusercontent.com/29964484/130199377-2dda0e4e-b980-4a7c-9b8a-546530dcc227.png)
![2](https://user-images.githubusercontent.com/29964484/130199381-a97022d6-7a95-4ca6-8805-b1b02ead62bf.png)
![3](https://user-images.githubusercontent.com/29964484/130199641-8f7b4074-f429-410d-a042-285ae5a69afd.png)

**Comment by kylebrandt** [comment]
@gorkem2020 What is the contact point type(s) for AWS-API?

**Comment by gorkem2020** [comment]
> 
> 
> @gorkem2020 What is the contact point type(s) for AWS-API?

Sorry for the late response, I completely missed notification.

type is webhook (POST)

**Comment by gorkem2020** [comment]
Hello,

I've updated to 8.2.2 thinking this issue must have been surely solved. Unfortunately, I'm still getting empty valueString under 'firing' alerts. and non-empty valueStrings under 'resolved' alerts.

I'm really not sure how people are using alerts without alertStrings? Am I doing something wrong here?

I really want to use this new alerting system but it is impossible to use it without valueStrings. Is there anything I can do to solve this issue on my end?

**Comment by peterholmberg** [comment]
Should be solved in 8.3 https://github.com/grafana/grafana/pull/41951

**Comment by haku** [comment]
i am seeing a similar issue with using ngalert  (v8.3.2) - for the same alert sometimes the valueString field will be an empty string and sometimes it will be filled in correctly.  there does not seem to be any pattern to it.  i wonder if there is some sort of race condition or inconsistent iteration order somewhere?

**Comment by zuchka** [comment]
> using ngalert (v8.3.2)

I think ngalert was deprecated in the Grafana config. I'd check that you are using the newest Unified Alerting settings 👍

**Comment by haku** [comment]
by "ngalert" i mean https://github.com/grafana/grafana/tree/main/pkg/services/ngalert
which seems to be the code for the new alerting system?

**Comment by GdHuni** [comment]
> Should be solved in 8.3 #41951

could you reopen the issue, please? My version is 8.3.7  but I still run into the same problem, only when valuestring is not empty after the second time

{
	"receiver": "xy_alert",
	"status": "firing",
	"alerts": [{
		"status": "firing",
		"labels": {
			"alertname": "link_cs_mysql_to_doris"
		},
		"annotations": {
			"content": "flink_cs_mysql_to_doris_guoan fail",
			"key": "rule_engine",
			"notify_type": "8",
			"who": "guoan"
		},
		"startsAt": "2023-12-21T06:24:07.345890993Z",
		"endsAt": "0001-01-01T00:00:00Z",
		"generatorURL": "http://grafana.win.oa.com/alerting/pk1RjRdSz/edit",
		"fingerprint": "e7d6c0f199532b5a",
		"silenceURL": "http://grafana.win.oa.com/alerting/silence/new?alertmanager=grafanamatchers=alertname%3D%E5%82%AC%E6%94%B6-%E5%AE%9E%E6%97%B6%E5%90%8C%E6%AD%A5%E8%A1%A8flink_cs_mysql_to_doris_guoan",
		"dashboardURL": "http://grafana.win.oa.com/d/4ZJRuaF4k1",
		"panelURL": "http://grafana.win.oa.com/d/4ZJRuaF4k1?viewPanel=54",
		"valueString": ""
	}],
	"groupLabels": {
		"alertname": "flink_cs_mysql_to_doris_guoan"
	},
	"commonLabels": {
		"alertname": "flink_cs_mysql_to_doris_guoan"
	},
	"commonAnnotations": {
		"content": "flink_cs_mysql_to_doris_guoan ",
		"key": "rule_engine",
		"notify_type": "8",
		"who": "guoan"
	},
	"externalURL": "http://bigdata_grafana.win.oa.com/",
	"version": "1",
	"groupKey": "{}:{alertname=\"flink_cs_mysql_to_doris_guoan\"}",
	"truncatedAlerts": 0,
	"orgId": 1,
	"title": "[FIRING:1] flink_cs_mysql_to_doris_guoan ",
	"state": "alerting",
	"message": "**Firing**\n\nValue: [no value]\nLabels:\n - alertname = flink_cs_mysql_to_doris_guoan\nAnnotations:\n - content = link_cs_mysql_to_doris_guoan \n - key = rule_engine\n - notify_type = 8\n - who = guoan\nSource: http://bigdata_grafana.win.oa.com/alerting/pk1RjRdSz/edit\nSilence: http://grafana.win.oa.com/alerting/silence/new?alertmanager=grafana\u0026matchers=alertname%3D%E5%82%AC%E6%94%B6-%E5%AE%9E%E6%97%B6%E5%90%8C%E6%AD%A5%E8%A1%A8flink_cs_mysql_to_doris_guoan\nDashboard: http://grafana.win.oa.com/d/4ZJRuaF4k1\nPanel: http://grafana.win.oa.com/d/4ZJRuaF4k1?viewPanel=54\n"
}
