### ISSUE TITLE
Data link doesn't work with Cell Display Mode

### ISSUE THREAD

**Issue by mertbakir** [grafana/grafana#37992]
**What happened**:

Data links on tables doesn't work when using a cell display mode other than "auto" or "color text"

JSON mode: (can't click on it)
![image](https://user-images.githubusercontent.com/43188411/129854459-e8a177b5-0685-47e3-8ff3-ef4805ecf3d7.png)

Color Text: (works as expected)
![image](https://user-images.githubusercontent.com/43188411/129854505-98eb9f19-ad58-479b-834e-a263b9854325.png)

**What you expected to happen**:

I expect it to work with other views too, espcially json mode.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a table,
- Use override method for a column.
- Add data links
- Display as JSON view
- Data link won't work anymore.

**Anything else we need to know?**:

This was working fine in v7

**Environment**:
- Grafana version: 8.1.1

**Comment by dprokop** [comment]
Doesn't work for the following cell types:
- [ ] LCD Gauge
- [ ] Gradient gauge
- [ ] Basic gauge
- [ ] JSON View

**Comment by oscarkilhed** [comment]
Took a quick look at this. Looks like we don't handle multiple links, only the first one gets displayed. Other visualizations open a menu where you can pick the link you want to follow.
