### ISSUE TITLE
[BUG] InfluxDB data source problem

### ISSUE THREAD

**Issue by mdzidic** [grafana/grafana#38002]
Hello,

We have InfluxDB as a data source, the button "Save and test" says that the data source is working fine.

We can create panels with InfluxDB selected as a data source without any problems, but when we are trying to create an Alert for our panel we get this error message after clicking on the "Test rule" button:

```
{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "73.189ms",
  "error": "request handler error: failed to query data: InfluxDB returned error status: 401 Unauthorized",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1629277850767,
        "queries": [
          {
            "refId": "A",
            "model": {
              "alias": "Download",
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$__interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "interval": "60s",
              "measurement": "snmp_rx",
              "orderByTime": "ASC",
              "policy": "default",
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  },
                  {
                    "params": [
                      "10s"
                    ],
                    "type": "non_negative_derivative"
                  }
                ]
              ],
              "tags": [
                {
                  "key": "host",
                  "operator": "=",
                  "value": "192.168.0.1"
                },
                {
                  "condition": "AND",
                  "key": "type",
                  "operator": "=",
                  "value": "if_octets"
                },
                {
                  "condition": "AND",
                  "key": "type_instance",
                  "operator": "=",
                  "value": "ether1"
                }
              ],
              "target": ""
            },
            "datasource": {
              "id": 14,
              "name": "InfluxDB-collectd"
            },
            "maxDataPoints": 0,
            "intervalMs": 0
          }
        ],
        "to": 1629278150767
      }
    }
  ]
}
```

**What happened**:
`"error": "request handler error: failed to query data: InfluxDB returned error status: 401 Unauthorized",`

**What you expected to happen**:
Successful Alert test.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add InfluxDB as data source
2. Add a panel with InfluxDB data source
3. Create an Alert for the panel
4. Test rule

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: v8.1.1 (90c87a52f7)
- Data source type & version: InfluxDB official plugin
- OS Grafana is installed on: Official Docker image
- User OS & Browser: Linux - Chrome
- Grafana plugins:
- Others: InfluxDB v1.8

**Comment by zuchka** [comment]
Hi @mdzidic 

Thanks for making this issue. I was not able to reproduce this issue when building Grafana from `main` (v8.1.0-pre (646d95b8fb)). I added influx, made a panel, and added and tested an alert. Can you provide any more details about this issue? Are you using the legacy alerting system of the new [Unified Alerting](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/), which is still behind a feature-toggle?

**Comment by blamarvt** [comment]
Is this a duplicate of #37770 ?

**Comment by zuchka** [comment]
Thanks @blamarvt, sounds very possible.

@mdzidic how have you configured your influx datasource? Are you connecting with TLS?

As suggested above, [this might be related (see comment for workaround)](https://github.com/grafana/grafana/issues/37626#issuecomment-895226853)

**Comment by mdzidic** [comment]
Hello,

It looks like the same problem.

I run InfluxDB and Grafana on the same host inside Docker containers.
Also, I don't have TSL enabled on my InfluxDB, only Basic Auth.

Just tried retyping the password on the InfluxDB data source panel and it seems that fixes the issue.

Thank you for your time!
