### ISSUE TITLE
Stacked values miss dataseries

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#3801]
Grafana 2.6.0, OpenTSDB datasource, two metrics with tags.

I open a dashboard and everything works as expected:

![image](https://cloud.githubusercontent.com/assets/89186/12449369/b2d114a6-bf74-11e5-9745-2c94efb40027.png)

Then I pick another application (change templating variable):

![image](https://cloud.githubusercontent.com/assets/89186/12449379/c62fb48a-bf74-11e5-8549-1d2c8878b357.png)

Then I uncheck stacked graphs:

![image](https://cloud.githubusercontent.com/assets/89186/12449391/deac6e68-bf74-11e5-9816-c6d57c3917b3.png)

It doesn't happen with all apps, but it happens with a lot of apps.

**Comment by torkelo** [comment]
Stacking requires non null values for all series, it wont stack null values or non continues series.

**Comment by torkelo** [comment]
I know this can be painful for some databases that do not return nulls for missing data, not sure what OpenTSDB returns, if it returns null for missing data you can use the "null as zero" option in display tabs to solve the problem.

**Comment by bobrik** [comment]
@torkelo OpenTSDB 2.2 supports fill policies in downsampling: http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html#fill-policies

I cannot use these in grafana yet, though. Should I file another issue?
