### ISSUE TITLE
Dashboard submenu disappears when in kiosk tv mode

### ISSUE THREAD

**Issue by alirezamansoori** [grafana/grafana#38037]
**What happened**:

When using the tv profile mode the content of Dashboard submenu is also disappearing. (template variables, dashboard links, etc.)

**What you expected to happen**:

I expect the kiosk=tv (tv profile) display mode to only hide the sideMenu.

**How to reproduce it (as minimally and precisely as possible)**:

Issue presents itself regardless of platform its running on. I can reproduce it by using the the kiosk=tv parameter.

https://play.grafana.org/d/rUpVRdamz/dashboard-links-with-variables?orgId=1
vs
https://play.grafana.org/d/rUpVRdamz/dashboard-links-with-variables?orgId=1&kiosk=tv

notice the template variables and the dashboard links (Dashboard submenu section) disappear.

**Anything else we need to know?**:

I wasn't sure if this is more of a grafana frontend bug or related to grafana-kiosk repository, so I also openned a similar issue on grafana-kiosk repository. https://github.com/grafana/grafana-kiosk/issues/61

**Environment**:
- Grafana version: latest
- Data source type & version: NA
- OS Grafana is installed on: NA
- User OS & Browser: regardless
- Grafana plugins: NA
- Others:

**Comment by zuchka** [comment]
closing this (for now) in favor of the ongoing discussion here: https://github.com/grafana/grafana-kiosk/issues/61
