### ISSUE TITLE
TimeSeries Panel: Could not create annotations over time

### ISSUE THREAD

**Issue by Willena** [grafana/grafana#38032]
**What happened**:

When holding the controlKey, WindowsKey, AltKey, and selecting a range of time (like we would have done if we were zooming), the Annotation Editor does not open, instead, the zoom action is executed, and it is not what we want. 

**What you expected to happen**:

The Annotation editor should have opened to allow the annotation creation. 

**How to reproduce it (as minimally and precisely as possible)**:

1. Create an empty dashboard
2. Create a single time series panel, with the Grafana datasource
3. Hold shift, ctrl, alt or windows key while selecting a zone on the graph
4. Release everything
5. The zoom action is executed and the Annotation panel is not shown.

**Anything else we need to know?**:

In the `public/app/plugins/panel/timeseries/plugins/AnnotationEditorPlugin.tsx` source file I can see that the key that triggers the annotation editor is the `metaKey` also sometimes known as `windows key` or `command key`. 
Based on this article https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey I think it would be better to use another key like the control or alt key instead. 

**Environment**:
- Grafana version: 8.1.1
- Data source type & version: Grafana Internal
- OS Grafana is installed on: Centos 7
- User OS & Browser: Firefox 90, Windows
- Grafana plugins: None
- Others: N.A

**Comment by leeoniya** [comment]
initially i was also surprised that Ctrl did not work, but now i see that it's a regression from the prior behavior:

https://github.com/grafana/grafana/blob/c5f8d987094913b9b84e80e916d5274848e8d9a9/public/app/plugins/panel/graph/graph.ts#L186-L187

would you like to PR the fixes in `AnnotationEditorPlugin.tsx`?
