### ISSUE TITLE
Move scuemata base system into a separate repository

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#38038]
The [scuemata system](https://docs.google.com/document/d/1qp3flLb6q1dPqTmHQ6MV-o6lOmlctfMNpzTx2MdzucY/edit#heading=h.ps08c938afna) for defining evolvable schema was always intended to be generic, independent of Grafana. We did the first iteration of it inside this repo, because it made rapid iteration easier, and because it enabled a couple handy hacks for dealing with the complexities of dashboard composition. However, with Grafana's overall schema system progressing steadily towards maturity, it's time to make the shift.

This could be in the Grafana org, or not. Not sure what our pattern here really is. ([cuetsy](https://github.com/sdboyer/cuetsy) is in my personal namespace, but that's not necessarily a precedent we have to follow)

Some refactoring will be necessary here, but not a ton, i don't think. Main bits that need to move:

* `pkg/schema`
* parts of `pkg/schema/load`, mostly in [`generic.go`](https://github.com/grafana/grafana/blob/main/pkg/schema/load/generic.go)
* `cue/scuemata/scuemata.cue`

The scuemata system is also due for a serious second pass, having found some major friction points over the past few months. That'll come after we re-home the code.

**Comment by sdboyer** [comment]
Closing this out, this has been done for a while - https://github.com/grafana/thema

**Comment by NoOnEtHeMaStA** [comment]
Collaborate
