### ISSUE TITLE
Regression in nightly: Direct link rendered image not working

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#3804]
In latest nightly, it's not possible to generate images anymore. I can reproduce this in any panel by clicking at the panel title -> share ->  Direct link rendered image

The browser keeps waiting for an answer but no image show up

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master, will push out new nighly

**Comment by vitorboschi** [comment]
I've tried the build from 21/01/2016 07:18:54, which seem to have your commit but it still didn't work here

**Comment by torkelo** [comment]
@vitorboschi sorry, did not test the fix properly, did another fix, new nightlies are on their way

**Comment by vitorboschi** [comment]
It's working fine now. Thank you for your efforts
