### ISSUE TITLE
Data link to Explore Loki logs fails with multi-value variables (LogQL regex filter)

### ISSUE THREAD

**Issue by fgmpe** [grafana/grafana#38053]
Hi,

**What happened**:
I create datalink from Grafana panel (with metrics from Loki log lines) to Explore of Loki datasource. URL of link is:
```
/explore?orgId=1&left=%5B%22$__from%22,%22$__to%22,%22Loki%22,%7B%22expr%22:%22%7Bhost%3D%5C%22${host}%5C%22,process%3D%5C%22haproxy%5C%22%7D%7Cunpack%7Cbackend%3D~%5C%22${be}%5C%22%20and%20http_status_class%3D%5C%22${__field.labels.http_status_class}%5C%22%22%7D%5D
```
Variable ${be} is dashboard variable of Query type with "multi-value" and "include All" checked. When i click the data link, I get to Explore page with correct datasource (Loki), timeinterval and LogQL query.
```
{host="some.host.net",process="haproxy"}|unpack|backend=~"{be-01,be-02}" and http_status_class="2xx"
```
Rendered value of ${be} variable is wrong for LogQL regex filter: `{be-01,be-02}`
Query in Loki Explore does not work, nothing is found.

**What you expected to happen**:
I expect rendered value of ${be} variable to be: `be-01|be-02`
It would display expected Loki log lines in Explore, which would be great for our Developers.

**Suggestion**
Please provide new datalink variable / expression to render multi-value dashboard variables in regex-friendly way:
- ${be} ... `{be-01,be-02}`
- ${__regex_friendly.be} ... `be-01|be-02`

**How to reproduce it (as minimally and precisely as possible)**:
- create dashboard with multi-value variable
- create datalink using value of this variable as argument of LogQL regex filter
- follow the datalink
- rendered multi-value variable value is wrong for regex filter

**Environment**:
- Grafana version: Grafana v8.0.6 (68fe9e3431) (official Docker image)
- Data source type & version: Loki, built-in

**Comment by hugohaggmark** [comment]
Hi @fgmpe can you try and replace `$be` with `${be:pipe}` and see if that works? Thank you. 
You can read more about the formatting options here
https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#pipe

**Comment by fgmpe** [comment]
Hi, that is exactly what i needed. Thank you for the documentation link.
