### ISSUE TITLE
Feature Request: Support for OpenTSDB 2.3 Expressions

### ISSUE THREAD

**Issue by johann8384** [grafana/grafana#3805]
The company I worked for submitted the expression code and has an internal Datasource that works with the expressions, although, it's simplistic at best. It is simply a text box where you write your expression to be returned.

I'm planning to submit a PR to add that datasource, but if @utkarshcmu has something better in the works, like improvements to the OpenTSDB datasource to support them the way the Graphite or Bosun datasources do, that would be great.

An example of the new expression usage:

``` bash
curl 'http://localhost:4244/api/query/gexp/?start=10m-ago&exp=alias(scale(sum:rate:1m-avg:tsd.rpc.received\{domain=atl1\},0.10),TSDBRPCSCALED)' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://localhost/grafana/' -H 'Origin: http://localhost' -H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/46.0.2490.86 Safari/537.36' --compressed
```

A picture of our Datasource in Use:

<img width="400" alt="grafana-opentsdb-expression" src="https://cloud.githubusercontent.com/assets/154673/12455365/017cc104-bf61-11e5-9fdc-266c1da88674.png">

Originally I posted this in #3077 but I realized that was for the filters not the new expressions.

**Comment by utkarshcmu** [comment]
@johann8384 Feel free to submit a PR, I am not working on Opentsdb expressions support currently. :) 

But looks like Opentsdb 2.3 is too far to be released. They have not even released 2.2. :(
I am not sure will @torkelo accept a PR right now or later for expressions support as Opentsdb 2.3 official release will be sometime in the future.

**Comment by utkarshcmu** [comment]
Asked for a release candidate for Opentsdb 2.3 https://github.com/OpenTSDB/opentsdb/issues/680

**Comment by johann8384** [comment]
Thanks, you are correct, 2.3 is a fair bit away. It's essentially the development branch, I think 2.2 is still RC3.

**Comment by utkarshcmu** [comment]
@johann8384 Have already submitted a PR for supporting Filters #3981 in Grafana for Opentsdb 2.2.0.

Once 2.3.x RC1 is cut out from Opentsdb repo, we can work on Expressions support as well. :)

**Comment by johann8384** [comment]
Here is what we are using internally, I think it could be done better. 
https://github.com/turn/grafana/tree/v2.0.x_OpenTSDBM/public/app/plugins/datasource/opentsdbM

**Comment by eswdd** [comment]
@johann8384 @utkarshcmu if adding support for "exp" queries, it would be good to have support for "gexp" queries as well, if possible. even if it's just a text box.

**Comment by johann8384** [comment]
What we have is a textbook where you type in your query. ex: alias (sum (metric1,metric2),"bothmetrics")

**Comment by WangFenjin** [comment]
Hi team,

As OpenTSDB2.3 RC1 had been released, do we have any update on this issue? I tried @johann8384 's implementation, but seems not work in grafana 3.0 beta 7.

Thanks for your great work on this project.

**Comment by utkarshcmu** [comment]
There is no work done yet to support Expressions in Grafana, but supporting Expressions should be the next major thing for Grafana-Opentsdb support.

**Comment by digrich** [comment]
+1

**Comment by utkarshcmu** [comment]
I will try to work on this feature ASAP, but if anyone else wants to start working on it please go ahead. Just give me heads up, so that I know someone else is working on it. Thanks :)

**Comment by sihara** [comment]
any updates here? anything we can test opentsdb's exp and gexp with grafana?

**Comment by utkarshcmu** [comment]
@sihara No progress from my side though. Too busy these days. :(

**Comment by JimHagan** [comment]
My organization is doing a serious evaluation of OpenTSDB / Grafana stack to replace a legacy Graphite setup.  This feature would be tremendously useful, as it would make the cutover from graphite more feasible.  Is there even an estimate of effort for this particular request?

**Comment by utkarshcmu** [comment]
@JimHagan I will try to add support for expressions asap, as time permits.

**Comment by cffyh** [comment]
@utkarshcmu  how long it would be finished this feature?

**Comment by utkarshcmu** [comment]
@cffyh I will try to start some work this week and finish it before Grafana 4.0 release. It would be great to have expressions supported in Grafana 4.0. :)

**Comment by ocarino** [comment]
Hi,

> and finish it before Grafana 4.0 release

any updates on this? I would really appreciate opentsdb expressions in grafana.

Cheers...

**Comment by soeren-lubitz** [comment]
I would really help to have at least rudimentary support for expressions.

**Comment by johann8384** [comment]
Support gexp at least would be really nice, and probably easier than exp. http://opentsdb.net/docs/build/html/api_http/query/gexp.html

**Comment by utkarshcmu** [comment]
Progress so far:

Query A shows collapsed version of a OpenTSDB **metric** query.
Query B shows non-collapsed version of a OpenTSDB **metric** query.
Query C shows collapsed version of a OpenTSDB **expression** query.
Query D shows non-collapsed version of a OpenTSDB **expression** query.

<img width="1420" alt="screen shot 2017-01-03 at 2 42 47 am" src="https://cloud.githubusercontent.com/assets/1019609/21605481/5f05e994-d15e-11e6-8890-2a4ff8bff06c.png">

**Comment by soeren-lubitz** [comment]
this looks promising... any idea in terms of when the feature will be available for testing?

**Comment by digrich** [comment]
@utkarshcmu This looks great. Will it support gexp also?

**Comment by utkarshcmu** [comment]
I'll try to get all 3 API end points (/api/query , /api/query/exp,  /api/query/gexp) working but my current goal is any 2 right now and get it out for the people to use it.

**Comment by utkarshcmu** [comment]
Hopefully we should have this feature by the end of this week if all is good with the code quality :)

**Comment by johann8384** [comment]
it might be possible to copy off the graphite datasource for the gexp since it would work in a similar way and the string passed to the database is very similar

**Comment by utkarshcmu** [comment]
Currently, only 1 request is sent from 1 panel to OpenTSDB. To support expressions, we will have to send multiple requests, reason being all 3 endpoints(/api/query, exp, gexp) support different HTTP methods and have different endpoints. So, we have to make multiple requests per panel to support all 3 endpoints.

**Comment by utkarshcmu** [comment]
@johann8384 Can you suggest any better way to call OpenTSDB in 1 request and get response back for all 3 different types of queries?

**Comment by utkarshcmu** [comment]
gexp supported completed in PR #7118 

Updated screenshots:

![screen shot 2017-01-08 at 7 46 01 am](https://cloud.githubusercontent.com/assets/1019609/21751132/bbcb252e-d576-11e6-8d9f-287393ab89d0.png)

Can someone test PR #7118 ?

**Comment by utkarshcmu** [comment]
Can anyone test the PR #7118 ? Lets get this feature merged into 4.2.0!

**Comment by virtual81** [comment]
I tested the patch and found two issues:
1. After upgrading and reloading the page, all graphs were showing "no datapoints". After clicking visible/invisible for a metric in a graph, everything was visible again. Did this for all graphs, so cannot reproduce this one anymore.
2. Grouping by tag is not working. Added "{host=*}" to a query which results in an error:
TypeError: Unable to get property 'gexpAlias' of undefined or null reference
   at transformGexpData (eval code:394:7)
The metrics are arriving correctly at the client, as tested by the network trace of the browser.

**Comment by virtual81** [comment]
Did some research and testing on grouping by tags:
"show_query=true" is actually supported by gexp API via HTTP GET, so it would in principle be possible to connect the metric queries to the responses, but the response always contains 0 as the query index.
The problem lies in the opentsdb expression classes, which use the wrapper class EDPtoDP, which always returns 0 from the getQueryIndex() function. don't know what would be the cleanest solution here, but i hacked my way around it, adding a setQueryIndex() function and numbering the DataPoints of the expression_results in QueryRpc.java QueriesCB::call() by expression-index, as they are the only queries.

**Comment by utkarshcmu** [comment]
@virtual81 Thanks for the feedback, will improve the PR asap!

**Comment by skygragon** [comment]
just wanna to know how is this feature going?

**Comment by utkarshcmu** [comment]
@skygragon i was working on that in one of the PRs but was not able to complete it. So, i left it in the middle due to lack of time on my end. Feel free to use that PR and finish the feature implementation.

**Comment by smalik03** [comment]
Is someone working towards adding expressions to the datasource?

**Comment by torkelo** [comment]
not that we know of

**Comment by smalik03** [comment]
Thanks for replying @torkelo. I guess I might take a stab at it then. Will update once I have something concrete.

**Comment by shashilpikrishan** [comment]
@smalik03 did you get a chance for closure on this. We have been extensively using Grafana & TSDB and desperately in need of this feature.  

We would be really thankful for having this feature soon.

**Comment by smalik03** [comment]
@shashilpikrishan I had made some progress on adding expressions but got sidetracked with some other work. Will try to find some time and submit a PR for basic expression querying soon.

**Comment by smalik03** [comment]
Added basic expression query to OpenTSDB datasource. I have not played around a lot with expressions so not sure if this covers most of the options. It would be great if someone can test these changes and provide some feedback to work on.

@shashilpikrishan @digrich

Thanks, @utkarshcmu the expressions PR helped a lot.

**Comment by dprime** [comment]
How's this going? Ready for a merge into an RC/beta ?

**Comment by smalik03** [comment]
There are still some global options left to be added for expressions. I haven't used expressions a lot so I am waiting for someone to test this PR and provide some feedback before I add more options and finalize this. @dprime it would be great if you could test this PR.

**Comment by sbryan77** [comment]
@smalik03 what commit should I pull to get this feature so I can try to test it?

**Comment by smalik03** [comment]
@sbryan77 you can pull from this branch [smalik:opentsdb-expressions](https://github.com/smalik03/grafana/tree/opentsdb-expressions)

**Comment by kevingu1983** [comment]
@smalik03 any plans for this request?

**Comment by smalik03** [comment]
@kevingu1983 I have not had enough time to work on this after the initial changes I made. Feel free to pull from the branch in the above comment to test and add enhancements to it.

**Comment by dehotot** [comment]
Hi all, I have ported utkarshcmu's "gexp" code forwards to the current Grafana version and have submitted a pull-request.

It is not yet heavily-tested.

**Comment by dehotot** [comment]
I've fixed the bug in my latest commit to https://github.com/dehotot/grafana/tree/opentsdb-gexp

I want to add one feature - I want to add the ability to do `$tag_foo` aliases for wildcard tags in gExp (like you can already do in classic "metric" queries)

I'll put that feature in tomorrow, then I think the PR is good to be opened.

**Comment by dehotot** [comment]
OK, I've got `$tag_foo` aliases working for wildcard tags in gExp. (I worked out a way to assign a unique ID to gexp queries)

![screen shot 2018-05-11 at 22 25 36](https://user-images.githubusercontent.com/34746075/39947657-9e3721e6-556a-11e8-84d7-6790111b231e.png)

I've updated my clone. Feel free to pull your own copies and test for yourselves . I'll reopen that PR after a few days' testing in production next week.

**Comment by dprime** [comment]
That's wonderful and the tag feature is sweet. I'll do some testing of this
at work on Monday and see what the office denizens think/find. I'll report
any feedback. Thank you!

**Comment by mjb512** [comment]
@dehotot I submitted a PR for the case where you want multiple tag substitutions in the alias - e.g. "traffic from $tag_src to $tag_dst"

I have also realised that older dashboards no longer work. It appears to be due to the lack of `queryType` in the existing panels. Just updated the PR with a fix to assume 'metric' type

**Comment by dehotot** [comment]
@mjb512 can you sign the CLA? See: https://github.com/grafana/grafana/pull/11974#issuecomment-389897823

**Comment by mjb512** [comment]
Signed.

**Comment by dehotot** [comment]
It seems stuck, can you go over to https://github.com/grafana/grafana/pull/11974 and see if you can convince it to accept your signature? You might need to click something like the "Let us recheck it" link.

Ta so much 😀

**Comment by raunz** [comment]
I tried out this and there are a few important features missing, which would make gexp query usable.
1) Current patch doesn't support variables e.g. $host or [[interface]]
url:"api/datasources/proxy/1/api/query/gexp?start=1527920693806&exp=scale(sum:interface.octets.out.[[host]]{interface=[[interface]]},8)&gexpIndex=1"
message:"No such name for 'metrics': 'interface.octets.out.[[host]]'"
url:"api/datasources/proxy/1/api/query/gexp?start=1527920800020&exp=scale(sum:interface.octets.out.$host{interface=$interface},8)&gexpIndex=1"
message:"No such name for 'metrics': 'interface.octets.out.$host'"
2) Rate. Expecting to see Mbits on the graph, not TeraBits since last counter rollover.

![grafana_-_ethernet_-_2018-06-04_09 55 22](https://user-images.githubusercontent.com/15248710/40902661-6d6ffe4a-67dd-11e8-922f-c6ac3564263a.png)

We are stuck with Grafana 1.9.1 as the values on TSDB metrics are in bytes and in that version we can use simply "scale=8" to multiply the bytes values to bits.
I expected to solve the problem with gexp, but not yet.

**Comment by jcmorrow89** [comment]
Is this still getting traction? Or has this been completed?

**Comment by gnydick** [comment]
I haven't had time to finish it.

**Comment by eangelou** [comment]
Hello, is there any hope to get support for /api/query/exp after 3 years?
