### ISSUE TITLE
Legend items order does not remain with PostgreSQL data source

### ISSUE THREAD

**Issue by igor-ryabchikov** [grafana/grafana#38082]
**What happened**: Legend items order was set by PostgreSQL query in Grafana v7. After upgrading to Grafana v8.1.1 items are always sorted by name.

**What you expected to happen**: Order of items set by PostgreSQL should remain as it used to be in Grafana v7.

**How to reproduce it (as minimally and precisely as possible)**: Write any PostgreSQL query with multiple metrics and custom order.

**Environment**:
- Grafana version: 8.1.1
- Data source type & version: PostgreSQL
- OS Grafana is installed on: ubuntu 18.04

![image_2021-08-19_19-14-05](https://user-images.githubusercontent.com/8830663/130104646-cb03fd95-511d-4776-8f31-cffef91ff934.png)

**Comment by zuchka** [comment]
@igor-ryabchikov this will be resolved with this PR, to be released in 8.3

https://github.com/grafana/grafana/pull/40226
