### ISSUE TITLE
Library panels in collapsed dashboard rows are not updated

### ISSUE THREAD

**Issue by fgmpe** [grafana/grafana#38110]
**How to reproduce it (as minimally and precisely as possible)**:
- create dashboard D1
  - create Time series panel LP, save it as library panel
  - save dashboard
- create dashboard D2
  - add Row R
  - add library panel LP into row R
  - collapse row R
  - save dashboard
- go to dashboard D1
  - make some change in library panel LP
  - save library panel LP (note that dashboard D2 is not in list of updated dashboards)
- go to dashboard D2
  - expand Row R
  - note that library panel LP is not updated

**What you expected to happen**:
I'd expect that library panels are updated also on dashboards where they are in collapsed rows.

**Environment**:
- Grafana version: docker image - grafana/grafana:8.1.2
- Data source type & version: Prometheus (built-in)
- OS Grafana is installed on: Ubuntu 20.04 
- User OS & Browser: Ubuntu 18.04, Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Grafana plugins: none

**Comment by zuchka** [comment]
Hi @fgmpe 

Thanks so much for creating this issue, and for providing such great steps for reproduction. I can confirm the behavior described using our [official sandbox](play.grafana.org), which was running Grafana v8.1.0 (62e720c06b) at the time. Both the lack of updating when a library panel is inside a collapsed row, and that "dashboard D2 is not in list of updated dashboards"

[D1 on play.grafana
](https://play.grafana.org/d/yMCrcL7nz/library-panel-in-row?orgId=1)

[D2 on play.grafana
](https://play.grafana.org/d/35mztL77z/library-panel-in-row-test-2?orgId=1)

**Comment by hugohaggmark** [comment]
I'm not super familiar with the underlying design of rows on dashboards but I think this is aligned with how saving collapsed rows work in Grafana. 

Do you think we should make an exception for library panels @kaydelaney @torkelo?

**Comment by hugohaggmark** [comment]
Nevermind my last comment I think I know what is going on.
