### ISSUE TITLE
Prometheus: Regex escape cause error

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#3811]
I use label_values() query for templating.
![label_value_query](https://cloud.githubusercontent.com/assets/224552/12474282/574a8786-c05d-11e5-9543-5f6eb2be9fdf.png)

I specify query like this.
![query](https://cloud.githubusercontent.com/assets/224552/12474325/ae954512-c05d-11e5-8467-7de267131980.png)

The templating escape label values if it has "-", and "foo-label" becomes "foo\\-label".
https://github.com/grafana/grafana/blob/f2ce8f266b9351ec7377d33d2b81e82e402e2024/public/app/features/templating/templateValuesSrv.js#L243-L245

The query is failed with following error response.
```
{"status":"error","errorType":"bad_data","error":"parse error at char 17: unknown escape sequence U+002D '-'"}
```

**Comment by mtanda** [comment]
There are same report.
https://github.com/grafana/grafana/issues/2918#issuecomment-147887093

Sorry, this is dupe.

**Comment by torkelo** [comment]
yea, this is a requires a big rethink to fix. I think the only way to work around the problem right now is to remove the All option and multi select, I think then there wont be any escaping

**Comment by mtanda** [comment]
Thanks for response.
I want to use both, so I wait "fundamental fix" :-)
