### ISSUE TITLE
FR: Grafana stats view for Admins

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3812]
Single place to know about Grafana stats for admins:

<img width="1064" alt="screen shot 2016-01-21 at 1 17 46 am" src="https://cloud.githubusercontent.com/assets/1019609/12476258/ea1efd5c-bfdc-11e5-809e-b196e0a02226.png">
<img width="1176" alt="screen shot 2016-01-21 at 1 17 50 am" src="https://cloud.githubusercontent.com/assets/1019609/12476260/eb7a95a8-bfdc-11e5-9bf7-1722d38f7417.png">

Thoughts?

**Comment by torkelo** [comment]
good idea

**Comment by utkarshcmu** [comment]
PR?

**Comment by torkelo** [comment]
That would be great

**Comment by utkarshcmu** [comment]
Closed via #3840
