### ISSUE TITLE
the position of the points on the lines is error sometimes

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#3813]
I use grafana-3.0.0-pre1, and find the position of the points on the lines is error sometimes.

(upload pictures failed, I use the urls below instead)

![click me: normal case1 ](https://github.com/godfreyhe/t/blob/master/pics/4.jpg)

![click me: bad case ](https://github.com/godfreyhe/t/blob/master/pics/5.jpg)

![click me: normal case2 ](https://github.com/godfreyhe/t/blob/master/pics/6.jpg)

**Comment by torkelo** [comment]
the all series tooltip requires that all series have the same number of datapoints, it behaves strangely when one serie is non continous or has different point resolution than another series. You might be able to fix it by fill(0) or some way to inject nulls for missing data points. Most time series databases has a way to inject nulls for missing data and very rarely return non continous series or series with different resolutions so this has not been a big issue before. You can also disable the all series tooltip and turn on the single value tooltip. 

There already is an issue for this restriction with the all series tooltip, so will close this.
