### ISSUE TITLE
Unable to export dashboard

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#3816]
On Grafana's version 3.0.0-pre1, when the _Export_ button, on the tab _Manage dashboard_, is pressed, nothing happens.

**Comment by torkelo** [comment]
how old is the build your using? Think this was fixed yesterday

**Comment by antjori** [comment]
I've updated it yesterday morning. Going to make a new build and redeploy it.

I'll get back at you as soon as I validate it.

Thanks for the feedback @torkelo

**Comment by antjori** [comment]
@torkelo, I've just built and deployed a new version and the issue reported was indeed already fixed.

Thank you!
