### ISSUE TITLE
FR: Enhance ES query editor

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#3817]
Enhance the Elasticsearch query editor with the same possibilities as the ones available for InfluxDB:
- aggregations
- selectors
- transformations
- math
- aliasing
- fields

**Comment by torkelo** [comment]
This is already implemented for the Elasticsearch query editor

**Comment by torkelo** [comment]
if there is a specific metric  aggregation or bucket aggregation that is missing please open a specific issue for that. Remember that Elasticsearch is very different so exact parity is not possible :)

**Comment by antjori** [comment]
Ok, my bad!

Since one already has the _stddev_ available is it possible that the derivative transformation may be added?

What do you think?

**Comment by torkelo** [comment]
derivative was added in Grafana 2.6 if you specify elasticsearch version 2.x in your grafana datasource settings

**Comment by antjori** [comment]
Duly noted!

I was using 1.7.x version.

Thanks once again for the feedback!
