### ISSUE TITLE
Forward Slash "/" not searchable for Elastiscsearch query

### ISSUE THREAD

**Issue by stephenshubin** [grafana/grafana#3818]
Using version 2.6, I have been running into issues building Lucene queries using the "/" character. 
According to the recent changes the forward slash is now considered a special character and needs to be backslash escaped.
For example:
```
filename:\/location1\/subdir2\/SOMEDATA\/*
```
returns nothing (even though that same query works via curl)

Looking into the raw JSON for the query I noticed this:
```
 "query": "filename:\\/location1\\/subdir2\\/SOMEDATA\\/*",
```
It appears as though you are automatically escaping special characters (or just "\"). While this is nice it happens automatically, it prevents me from using  "/" as a search parameter since it is impossible to backslash escape "/" in the search parameter.

**Comment by torkelo** [comment]
strange, could not replicate this, both 
`@metric:logins.count AND @hostname:server\/4`
and `@metric:logins.count AND @hostname:"server/4"`
works
![image](https://cloud.githubusercontent.com/assets/10999/12809636/e7615e80-cb20-11e5-9e4c-4b52e0d65cfc.png)
