### ISSUE TITLE
Can I use oauth token for authentication web requests ? 

### ISSUE THREAD

**Issue by biswanaths** [grafana/grafana#3823]
Hi,
 
   I would like to get some clarification regarding oauth implementation in grafana. As I understand, the grafana server does the oauth flow gets the token and then gets the userinfo and stores this in session tied with cookie. All the subsequent requests it works with the cookie.

   I have requirement, where I would like to render grafana as web view in a mobile application. And the mobile app would get the access token and would like to use this access token to pass to the grafana, rather than making user do the oauth authentication again in webview.

   What would be the right way to go about it ? Please do let me if I was unclear or missing any information.

Thanks. 
Biswanath

**Comment by torkelo** [comment]
oauth does not work like that :(  grafana must get the token via redirect from the oauth provdier

**Comment by biswanaths** [comment]
Sorry for the bother. If I understand correctly grafana is kind of using google oauth provider to get the identity of the user, in a way openID connect. https://en.wikipedia.org/wiki/OpenID_Connect

I don't see the access token being used further after getting the token anywhere. 

Am I missing something ?

**Comment by torkelo** [comment]
No your not missing anything , it is only a one time token used during login  (not stored anywhere)
