### ISSUE TITLE
FR: Hide some row menu actions to users with Viewer role

### ISSUE THREAD

**Issue by evandro-portugal** [grafana/grafana#3827]
Hello, since an update in master branch, the role viewer can see now the controls for adding panels and rows, which they shouldn't. The same way, they shouldn't be able to use the key binding 'control + h' to toggle between hide controls or not.

I'm not sure when which commit it started to act like this, but right now I'm working around hiding controls with an account that can edit the dashboard and saving it, and had to disable 'control+h' key binding on the code.

**Comment by torkelo** [comment]
The main point of the Viewer role is not being able to save dashboards. They will always have the capability to view the dashboard json and if they know some http issue any metric query. But to help users that have Viewer role from accidentally adding rows I can certainly see the case for hiding some items in the row menu (the row menu has the collapse action which should be accessible to viewers)

**Comment by evandro-portugal** [comment]
Right, thanks @torkelo , I understand that, the thing is that the feature to add panels and rows got broken too, if a viewer manages to add a row or a panel, the dashboard got broken all apart.

**Comment by torkelo** [comment]
how does it break the dashboard?

**Comment by evandro-portugal** [comment]
When as a viewer, if I add a panel, the hole dashboard get wiped out and I could see just the new panel that was added. At least it was like this when I posted here, so to prevent that I saved my dashboards with hidden controls and disabled the key bidding to show the controls again. Need to look for it with the actual master branch code.

**Comment by torkelo** [comment]
think this is fixed in v5
