### ISSUE TITLE
Docs: Split http_api doc into multiple files

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3828]
We should split the http_api.md doc into multiple files in a dedicated http_api directory. The single doc is too long to find stuff and with more docs we can have stuff elaborated. 

Would have helped #3826 and many other tickets.

**Comment by bergquist** [comment]
Good idea.

**Comment by utkarshcmu** [comment]
Please review/merge #3923

**Comment by utkarshcmu** [comment]
@bergquist Let me know if any changes are needed in the above mentioned PR. :)

**Comment by utkarshcmu** [comment]
@bergquist - Any updates on this issue?
