### ISSUE TITLE
Templating with multi select stop working after Panel repeat select then unselect

### ISSUE THREAD

**Issue by zsxking** [grafana/grafana#3831]
Step to reproduce:
1. Go to http://play.grafana.org/dashboard/db/new-features-in-v2-1
2. Edit the panel on 4th row, "Color by regex rule"
3. In "General" tab, select "Repeat Panel" to "Servers"
4. Click "Back to Dashboard"
5. Change the selection of Servers variable, e.g. from backend_02 + backend_03 to backend_02 + backend_03 + backend_04
6. Edit the same panel, "Color by regex rule" again.
7. Select the empty option in "Repeat Panel" 
8. "Back to Dashboard"
9. Change the selection of Server variable, e.g. to backend_02 + backend_03
expect: 
The "Color by regex rule" show stacked graph of backend_02 and backend_03
actual:
The "Color by regex rule" show only backend_02
Changing Server variable doesn't change what item to display for "Color by regex rule" afterward. 

* Reselect  "Repeat Panel" for that panel will make the repeat work again, but once unselected, it return back to bug state. 
* Same bug doesn't happen for row repeat. 

My guess: when unset panel.repeat, it didn't unset panel.scopedVars, and left it as it was.

**Comment by torkelo** [comment]
what version of grafana are you using?

**Comment by torkelo** [comment]
ah, sorry, your example was from play.grafana.org so I know the version :)
