### ISSUE TITLE
Plugin catalog?

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#3833]
Idea: Add a plugin catalog to the Grafana web site and/or documentation so users can find unofficial plugins easily.

I'm willing to submit a PR so long as someone tells me what the best location for it would be.

**Comment by torkelo** [comment]
We are working on this! :)

**Comment by mattttt** [comment]
Grafana.net is live! Currently, all plugins need to be added manually (email plugins@grafana.net) but self-service submission will be available soon.
