### ISSUE TITLE
Non-Dashboard Pages Design

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#3834]
Moved from Issue: https://github.com/grafana/grafana/issues/3687

Evolution on the existing design, and I'm liking this a lot. We still have to address the duplication of the nav bar, but Im anxious to hear some feedback before spinning wheels for even longer on this.

The colors reuse nearly all existing Grafana variable, which I like:
Background: 1F1F1F, Form Field Label: 262626, Form Field Input: 333, etc...

![editplaylist](https://cloud.githubusercontent.com/assets/2886187/12532412/728195be-c1e1-11e5-8824-77d4c81c33f5.png)
![grafanadatasource - 2](https://cloud.githubusercontent.com/assets/2886187/12532413/72845222-c1e1-11e5-8ebb-965b522f0a8b.png)
![orgprofile](https://cloud.githubusercontent.com/assets/2886187/12532414/7285515e-c1e1-11e5-8e7c-62ed298f6a94.png)
![userprofile](https://cloud.githubusercontent.com/assets/2886187/12532415/728580ca-c1e1-11e5-9c40-6b6b928410b7.png)
![users](https://cloud.githubusercontent.com/assets/2886187/12532416/7289213a-c1e1-11e5-8f9d-eb6afe730afb.png)

Notice Grafana Admin, moved into a single page with tabs (instead of a separate nav bar)

![grafana admin](https://cloud.githubusercontent.com/assets/2886187/12532411/727fce50-c1e1-11e5-90ef-3323788e4977.png)

**Comment by torkelo** [comment]
I am liking this, great job! Is the whole page background of the panel background color? looks that way

1) The smaller size cancel button looks a bit strange

**Comment by mattttt** [comment]
Correct, it is the entire background. At this point, we'll keep the dark background for dashboards, which looks sharp and brings focus to the panels. I was originally concerned it might somewhat jarring to switch between the different backgrounds, but conversely, it actually feels a lot nicer than switching to the full dark background (which I believe was your concern as well)

(1) Cancel button - yea, i want to keep playing with it. If we dont hit on something much better, same side fo' sho'

**Comment by bergquist** [comment]
Great! 

@mattttt do you have any idea about how we should handle searches as playlist items? It would work just like tags but get dashboards based on matching title. Perhaps that could be discussed in https://github.com/grafana/grafana/issues/3790

**Comment by mattttt** [comment]
Not fleshed out yet, but here is a quick and dirty compilation of the new elements:

![grafanastyleguide](https://cloud.githubusercontent.com/assets/2886187/12687934/e7cb7c7c-c6a0-11e5-853d-4ecb75e05ff6.png)

**Comment by torkelo** [comment]
Will close this, progress for all css work can should be done on this issue, https://github.com/grafana/grafana/issues/4036
