### ISSUE TITLE
HTTP Head requests produce 404 response

### ISSUE THREAD

**Issue by ryanmac8** [grafana/grafana#3835]
Backend server does not allow for head requests. Produces a 404 response when running a 
````
curl -I <grafana server address>
````
Yet, if I just want to preform a get request it will accept the request and not produce a 404. Would be nice to have a config spot to allow or deny HTTP head requests.

**Comment by torkelo** [comment]
yes, Grafana HTTP api does not support HEAD requests

**Comment by ben-xo** [comment]
We're also experiencing this issue. However, it seems it used to work, as our old service checks weren't failing, and they used HEAD. Did this change at some point?
