### ISSUE TITLE
New user link does not display properly on Android

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#3839]
Current Chrome on current Marshmallow on Nexus 6P and Nexus 5X can not display the link sent to new users in a way that allows the user to register.

If you need a screenshot let me know.

Using Grafana 2.6.0 from .deb on this host.

**Comment by bergquist** [comment]
Mobile support is not something that we are aiming for at the moment. 
Discussions regarding that should be held in https://github.com/grafana/grafana/issues/512

**Comment by RichiH** [comment]
Thanks; and sorry for the dup!

**Comment by bergquist** [comment]
@RichiH no worries :) I think @daniellee just fixed it anyway :)

**Comment by RichiH** [comment]
@daniellee thanks!

Jftr, I am fully OK with degraded functionality and agree with it not being
a focus yet, as long as absolute baseline works.

Richard

Sent by mobile; excuse my brevity.
