### ISSUE TITLE
Tempo: TraceID field is missing on initial page load

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#38407]
**What happened**:
Trace id field doesn't appear when first loading Tempo

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: Tempo
- OS Grafana is installed on:
- User OS & Browser: Chrome, Mac OS
- Grafana plugins:
- Others:

**Comment by diegocejasprieto** [comment]
you found any solution?¿
