### ISSUE TITLE
FR: Adding total_rows, total_panels, total_queries, created_by to dashboard Metadata tab

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3841]
We should also add total number of panels and queries on a dashboard in metadata. This will be helpful in knowing how heave a single dashboard is.

<img width="552" alt="screen shot 2016-01-24 at 11 35 46 pm" src="https://cloud.githubusercontent.com/assets/1019609/12545017/776cb1e0-c2f3-11e5-9cf7-5e897e88f3ad.png">

Any thoughts?

**Comment by torkelo** [comment]
Good idea!

**Comment by utkarshcmu** [comment]
All required metadata fields from this issue are shown in #3873.

**Comment by utkarshcmu** [comment]
Closing this.... as the other metadata information is not that important....
