### ISSUE TITLE
Annotation Panel: Annotation end time not displayed for time range annotations

### ISSUE THREAD

**Issue by Willena** [grafana/grafana#38424]
**What happened**:

When displaying the time of annotation in the annotation panel, only the start time get displayed. 
For time range annotation the end time should also be displayed.

![image](https://user-images.githubusercontent.com/1786065/130367250-69f12267-49a6-465c-9da7-342755e2beae.png)

**What you expected to happen**:

The end time when available should be also displayed.
<img width="588" alt="image" src="https://user-images.githubusercontent.com/1786065/130367304-426d915a-f09c-4df7-8f1c-055735c18bf7.png">

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a dashboard with a timeseries panel and tha annotation panel
2. Create a time range annotation over 1 hour
3. Look the annotation list: the end time is not displayed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: None
- OS Grafana is installed on: Mac OSx
- User OS & Browser: Firefox 90, MacOsx
- Grafana plugins: None
- Others: N.A

**Comment by axelavargas** [comment]
Thank you @Willena for reporting this issue and opening the PR 🙌🏾 , I was able to reproduce the issue here on Grafana play https://play.grafana.org/goto/F8K63X7nz?orgId=1 , we are going to review the PR 👀
