### ISSUE TITLE
Threshold by value not displaying correct colors

### ISSUE THREAD

**Issue by rennomarcus** [grafana/grafana#38428]
**What happened**: when selecting the following:

* gradient mode = "scheme"
* color scheme = "from thresholds (by value)
* threshold -> giving three thresholds (base -> green, 120 -> yellow, 150 -> red)
* show thresholds = "as filled regions"

The colors from the regions work fine and when hovering the data points, I can see the value with the right color. The problem here is that the plot itself is incorrect. The colors are almost random and are gradient. 

![grafana_threshold](https://user-images.githubusercontent.com/1592068/130376596-5beefa8c-13ff-402b-b213-e4c38c3adb3c.png)
![config_threshold](https://user-images.githubusercontent.com/1592068/130376599-3df3d9fa-fffb-4a34-a132-5f21aa97e14c.png)

**What you expected to happen**: The colors from the plot/line in my chart to match the color's value.  (If I select green-yellow-red I almost get the result, but the thresholds are inferred from the values)

**How to reproduce it (as minimally and precisely as possible)**: create a time series panel, select gradient mode to "scheme", select color scheme "from thresholds (by value), and add a threshold.

**Anything else we need to know?**: No.

**Environment**:
- Grafana version: 8.1.1
- Data source type & version: InfluxDB 2.0.8
- OS Grafana is installed on: docker image `grafana/grafana`
- User OS & Browser: Ubuntu 20.04.2 LTS / Firefox 91.0.1 (64-bit)
- Grafana plugins: None
- Others: N/A

**Comment by leeoniya** [comment]
plz try v8.1.2.

i did a pretty big refactor of this feature in https://github.com/grafana/grafana/pull/37670

**Comment by leeoniya** [comment]
@rennomarcus i'm gonna close this for now, since i'm quite confident the linked PR solves this issue. we can re-open if it's still a problem for you after updating to 8.1.2.

**Comment by rennomarcus** [comment]
@leeoniya , just want to tell you that I tested with the v8.1.2 and it's working great. Thank you!

**Comment by leeoniya** [comment]
👍
