### ISSUE TITLE
[2.5.0] Proxied responses include Set-Cookie headers

### ISSUE THREAD

**Issue by j-white** [grafana/grafana#3845]
When accessing a datasource via the 'proxy' method, the responses from the proxy include any 'Set-Cookie' headers that have been set by the datasource's HTTP server.

This causes the data source session information to be "leaked" to the browser, removing the benefit of using the proxy to shield the credentials.

**Comment by torkelo** [comment]
data source api's should not set cookies, that would could mean hundreds of sessions are created.

Grafana will not save the cookie and send it back. But your right it should be filtered out from the response.
