### ISSUE TITLE
Some panels show white background in dark mode when printing to PDF in Google Chrome

### ISSUE THREAD

**Issue by pcsegal** [grafana/grafana#38460]
**What happened**:

When printing a Grafana dashboard to PDF in Google Chrome, with Grafana in dark mode, some panels show a partially or completely white background.

I have seen it happen with the following panels:
* Time series
* Stat

Example screenshot of "Time series" panels:

![Screenshot from 2021-08-23 12-18-05](https://user-images.githubusercontent.com/7880893/130474593-76d40aa2-2001-4f7b-9be3-9cbc04c7a3bc.png)

Example screenshot of a "Stat" panel:

![Screenshot from 2021-08-23 12-34-29](https://user-images.githubusercontent.com/7880893/130475850-ba6897ce-15cf-4fac-8fc0-7d6074b46464.png)

Note: there is another open issue, #36656, which might be related.

**What you expected to happen**:

The panels should show a dark background, matching the dark theme.

**How to reproduce it (as minimally and precisely as possible)**:

One quick way to see it is to navigate to https://play.grafana.org/d/000000012/grafana-play-home?orgId=1 and print the page to PDF in Chrome. The result should look similar to the first screenshot above.

To reproduce it in a local Grafana 8.1.2 installation: set the theme option to dark mode, create a new dashboard, add a "Time series" or "Stat" panel with the "--Grafana--" datasource (setting the query type to Random Walk), and use Google Chrome to navigate to this dashboard and print it to PDF.

**Anything else we need to know?**:

There is another open issue, #36656, which might be related.

**Environment**:
- Grafana version: 8.1.2.
- Data source type & version: This seems to happen regardless of datasource; tried it with MySQL and the built-in --Grafana-- datasource.
- OS Grafana is installed on: I used Grafana installed in Ubuntu 20.04 for reproducing it locally.
- User OS & Browser: Ubuntu 20.04; Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
I think I'm passing this over to the BI squad.

**Comment by dprokop** [comment]
Will be fixed with next uPlot release. More details in https://github.com/grafana/grafana/pull/38762

**Comment by davkal** [comment]
Seems to be a Chrome issue. Closing this for Grafana.
