### ISSUE TITLE
[Azure monitor] todouble/toreal does not work on Azure Resource Graph explorer.

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#38472]
**What happened**:

Consider this KQL:
```
securityresources
| where type == 'microsoft.security/securescores'
| project percentageScore=todouble(properties.score.percentage)
| take 1
```
This works on Azure portal ARG explorer but not on Grafana ARG. It returns the error message:
`unsupported analytics column type number`
However it works if you remove `todouble()`

![image](https://user-images.githubusercontent.com/63325084/130672198-3c24673c-1fa5-42cc-a689-cfe6d5758c0b.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:  v8.0.5 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by andresmgot** [comment]
it would be just adding that as a new line:

```patch
var converterMap = map[string]data.FieldConverter{
	"string":   stringConverter,
	"guid":     stringConverter,
	"timespan": stringConverter,
	"dynamic":  stringConverter,
	"object":   objectToStringConverter,
	"datetime": timeConverter,
	"int":      intConverter,
	"long":     longConverter,
	"real":     realConverter,
	"bool":     boolConverter,
	"decimal":  decimalConverter,
	"integer":  intConverter,
+	"number":  decimalConverter,
}
```

and check if that works as expected

**Comment by shuotli** [comment]
> it would be just adding that as a new line:
> 
> ```diff
> var converterMap = map[string]data.FieldConverter{
> 	"string":   stringConverter,
> 	"guid":     stringConverter,
> 	"timespan": stringConverter,
> 	"dynamic":  stringConverter,
> 	"object":   objectToStringConverter,
> 	"datetime": timeConverter,
> 	"int":      intConverter,
> 	"long":     longConverter,
> 	"real":     realConverter,
> 	"bool":     boolConverter,
> 	"decimal":  decimalConverter,
> 	"integer":  intConverter,
> +	"number":  decimalConverter,
> }
> ```
> 
> and check if that works as expected

I created a PR for this fix.
