### ISSUE TITLE
Slash is appended to data source url

### ISSUE THREAD

**Issue by Sutrannu** [grafana/grafana#3847]
Grafana 2.[5-6].0 with nginx reverse proxy
Grafana-Zabbix 2.5.1
Data source Zabbix 2.2.x (https). nginx

Grafana is configured with 2 nearly identical zabbix instances as data sources. One on the same host, one remote. Both are configured with fqdns, e.g., `https://fqdn/api_jsonrpc.php`. The api request made to the local zabbix instance is `https://fqdn/api_jsonrpc.php`. The request to the remote instance is `https://fqdn/api_jsonrpc.php/`. note the invalid trailing slash.
From the successful nginx logs:
`"POST /api_jsonrpc.php HTTP/1.1" 200`
From the failed nginx logs:
`"POST /api_jsonrpc.php/ HTTP/1.1" 403`
From the Grafana 2.5 log:
`2016/01/20 15:09:39 [I] Completed /api_jsonrpc.php/ 403 Forbidden in 2.61934ms`
From the Grafana 2.6 log:
`2016/01/25 10:51:09 [I] Completed 127.0.0.1 - "POST /api_jsonrpc.php/ HTTP/1.0" 403 Forbidden 564 bytes in 20941us`

Bug reported to [grafana-zabbix](https://github.com/alexanderzobnin/grafana-zabbix/issues/146) first, then here when identified as (most likely) a Grafana bug.

**Comment by torkelo** [comment]
are you using the direct or proxy mode for the data source?

**Comment by Sutrannu** [comment]
proxy

**Comment by woodsaj** [comment]
https://github.com/grafana/grafana/blob/master/pkg/api/dataproxy.go#L51
if proxyPath is an empty string, then joinUrlFragments will append a "/"

A PR was submitted for the zabbix datasource to resolve this.
https://github.com/alexanderzobnin/grafana-zabbix/pull/117

So i think this could be fixed by updating the JoinUrlFragments function to handle empty strings.
https://github.com/grafana/grafana/blob/master/pkg/util/url.go#L27

eg.
```
func JoinUrlFragments(a, b string) string {
	aslash := strings.HasSuffix(a, "/")
	bslash := strings.HasPrefix(b, "/")
	switch {
        case a == "" || b == "":
                 return a + b
	case aslash && bslash:
		return a + b[1:]
	case !aslash && !bslash:
		return a + "/" + b
	}
	return a + b
}
```

**Comment by daniellee** [comment]
@Sutrannu just a quick question, what does the data source url look like in Grafana (in the url field)? Does it have a trailing slash or not?

We can fix the JoinUrlFragments function to handle empty strings anyway.

**Comment by Sutrannu** [comment]
The urls in the original post are accurate. `https://fqdn/api_jsonrpc.php` There is no training slash configured in the web interface.
