### ISSUE TITLE
Toolkit: Align starter templates with versions of grafana-toolkit

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#38483]

**Comment by hugohaggmark** [comment]
Friendly reminder to add labels to issues so we don't add more work for people on Issue Triage.

**Comment by jackw** [comment]
Following discussions around this issue rather than come at the problem from the starter templates it would be better for developers to have transparent configs so they can resolve the issues with misaligned templates rather than us maintaining syncing git tags with grafana toolkit versions.
