### ISSUE TITLE
Open two browser tab to view different "organization" with same login user throw exception.

### ISSUE THREAD

**Issue by jocundmo** [grafana/grafana#3850]
Hi, not sure whether I did it wrong, I created two organizations under the same user account, and try to monitor the metrics at the same time, seems only one of the tab could work - I use Opera34, open two normal tabs, while another one always throw exception saying "Unable to load datasoruce meta data".

I tried to trace the Request Headers, noticed this might be related to cookie, but I cannot dig into it. We would be very appreciated be advised what we should do to be able to  monitor two organizations at same time without deploying the Grafana twice.

**Comment by torkelo** [comment]
You can have one active organization at any time

**Comment by jocundmo** [comment]
thanks for replying, do you mean open two tabs to monitor two different organizations are not supported?

**Comment by torkelo** [comment]
Precisely
