### ISSUE TITLE
elasticsearch query on grafana

### ISSUE THREAD

**Issue by sharon77242** [grafana/grafana#3851]
Hi there,
I use elastic search as datasource on new grafana version, there ia a way to view top multiple values ?
For example if i have 50 processes and im getting all the data from elasticsearch is there a way to display 5 top process value on same graph? (The processes are dynamic so it might change).

Thanks

**Comment by torkelo** [comment]
http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=1&fullscreen&edit
