### ISSUE TITLE
Pull #33533 causes excessive load to InfluxDB and possibly other data sources

### ISSUE THREAD

**Issue by sawo1337** [grafana/grafana#38514]
**What happened**:
With Grafana 8.0 query variables can no longer be never refreshed, which causes long-running queries to bog down InfluxDB and possibly other data sources. With concurrent users refreshing dashboards, InfluxDB can easily be locked out, where in the past this issue was possible to be worked around by selecting "Refresh: Never" in the dashboard settings for specific variables. This is no longer possible and renders Grafana essentially unusable for certain scenarios. 
For example, we monitor web server access logs and we support filtering by a website so we have a dropdown that is filled by doing select distinct on all sites in that log. The log is obviously huge so scanning that column each time is not feasible. The same would apply to any large data set, especially when this information does not need to be refreshed every time.

**What you expected to happen**:
It was expected to at least explain why that pull was needed and it was not explained at all. Also, there is no workaround provided for such scenarios where large datasets need to be queried, the main use case for this functionality. One example workaround would be to allow this functionality to be used by specifying an option in the config or similar approach, but I see no reason for this to be removed completely all of a sudden.

**How to reproduce it (as minimally and precisely as possible)**:
Create a query that takes a minute to complete and assign to query variable, save the dashboard, and refresh.

**Environment**: Ubuntu
- Grafana version: 8-0-0 and above
- Data source type & version: Influx DB 1.8
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox/Chrome
- Grafana plugins: 
- Others:#

**Comment by hugohaggmark** [comment]
@torkelo @pkolyvas should we move this to Github Discussions and continue there?

**Comment by torkelo** [comment]
@sawo1337 the problem with Refresh: Never was that the data ended up stored in the dashboard.json , making the dashboard schema model huge in many cases. Sounds like we need a proper caching solution for the problem you are experiencing. Grafana Enterprise has query caching, maybe that could help. Does InfluxDB have some query caching mechanism or rollup/aggregation of slow queries?

**Comment by sawo1337** [comment]
Getting Grafana enterprise just for this specific feature doesn't really seem feasible at this point, I think this would be the case for a lot of other people as well.
I've checked the InfulxDB documentation, but can't seem to find anything that would resemble query caching, there are some third-party solutions, but this introduces more overhead on top of the existing functionality as it requires a separate webserver with a proxy. If big JSON is such an issue, I think this feature can be left included, just hidden by default, whoever needs it would have to live with the downsides of big JSON models. The best case would be to have some sort of caching, but for the time being, I don't see why it can't be used as it is.

**Comment by kakila** [comment]
This issue is quite problematic. I am self-hosting grafana and since this update exploring data in long queries is impossible.
I also agree this is a bug or a regression, not a feature request.

`the problem with Refresh: Never was that the data ended up stored in the dashboard.json , making the dashboard schema model huge in many cases.`
@torkelo this seems to be an odd solution to an unrelated problem. Better solutions would have bee:
- add a configuration variable to limit the size of the schema
- alert when the schema is getting to  big, and give the option to cancel the query
- cache only a fixed size of the query and update the rest.

Refresh: never should mean exactly that. Never refresh unless the users decides to do so

**Comment by sawo1337** [comment]
Same here, we haven't updated our Grafana instances since that issue was identified and I still don't see why hiding the feature by default was not an option as compared to completely remove it.
