### ISSUE TITLE
Tag/measurement suggestion not working if an inequality sign used in the where statement.

### ISSUE THREAD

**Issue by markgoffin** [grafana/grafana#3853]
Using Grafana 2.6.0-1

For a 0.9 InfluxDB source. The plus symbol for the WHERE statement or the GROUP BY statement usually brings up a list of suggestions. If an inequality sign of any type (<, > or <>) is used then the plus symbol no longer suggests any of the possible choices.

**Comment by torkelo** [comment]
seems to work fine for me:
http://play.grafana.org/dashboard/db/influxdb?panelId=3&fullscreen&edit
