### ISSUE TITLE
Support HEAD response for most views/GET operations

### ISSUE THREAD

**Issue by vpetersson** [grafana/grafana#3854]
There appears to be an incorrect implementation of the HEAD response in Grafana (or at least for the demos site). I'm not sure if this is intentional or not, but I find it somewhat strange. 

For instance, If i try to get the HEAD for the demo site, I get a 404 status code:

```
$ curl -I http://play.grafana.org
HTTP/1.1 404 Not Found
Server: nginx
Date: Tue, 26 Jan 2016 16:38:12 GMT
Content-Type: text/html; charset=UTF-8
Connection: keep-alive
Vary: Accept-Encoding
Set-Cookie: grafana_sess=5665fd2493d7a41d; Path=/; HttpOnly
```

Yet, if I request the whole site, it works just fine and I get a 200 status code:

```
$ curl http://play.grafana.org
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <meta name="viewport" content="width=device-width">
    <meta name="theme-color" content="#000">

    <title>Grafana</title>
[...]
```

Is this by design or is it a bug?

**Comment by torkelo** [comment]
it's by design

**Comment by vpetersson** [comment]
I'm sorry, but that doesn't seem to make a whole lot of sense to me (and it does violate [RFC 2616](https://www.w3.org/Protocols/rfc2616/rfc2616-sec9.html)). Could you shed some light on the reasoning for this? Also, is that only for the demo site, or for Grafana at large?

**Comment by torkelo** [comment]
It's just that we have not added handlers for HEAD operations to the api routes.
https://github.com/grafana/grafana/blob/master/pkg/api/api.go

Why is this important?

**Comment by vpetersson** [comment]
Understood. Well, we've had a number of customers who wants to use Granana with [Screenly](https://github.com/wireload/screenly-ose/) to display their dashboards on a big screen. Before putting up anything on the screen, Screenly will check the HEAD to make sure that the assets is accessible. This works well across all sites that we have tested, with the one exception of Grafana.

**Comment by torkelo** [comment]
I see, well I think we can get HEAD working easily.

**Comment by vpetersson** [comment]
Thanks, @torkelo.

**Comment by ryantm** [comment]
> Why is this important?

I ran into this issue too. I was trying to monitor grafana with monit. monit uses HEAD by default to detect that an HTTP server is functioning:
https://bitbucket.org/tildeslash/monit/src/54ea2cefe4dfcc47566501b4741ae80e8ddbadc0/src/protocols/http.c?at=master&fileviewer=file-view-default#http.c-244

**Comment by cmartin0077** [comment]
Sorry about the multiple commits. 

I added the SetAutoHead call which should give a HEAD response by default for every GET. It seems to work and no longer returns 404.
