### ISSUE TITLE
Grafana with Unexpected InfluxDB Query Returns Occasionally

### ISSUE THREAD

**Issue by TJChong92** [grafana/grafana#38559]
**What happened**: Sometime influxdb query return unexpected result as below
{
  "status": 200,
  "statusText": "OK",
  "ok": true,
  "data": "",
  "url": "http://<myserver>:3000/api/datasources/proxy/12/query?db=simulation&epoch=ms",
  "type": "basic",
  "redirected": false,
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/12/query",
    "params": {
      "db": "simulation",
      "epoch": "ms"
    },
    "data": "q=SELECT%20mean(%22target%22)%20AS%20%22target%22%20FROM%20%22production%22%20WHERE%20(%22machine%22%20%3D%20'MILO_Packaging')%20AND%20time%20%3E%3D%20now()%20-%201h%20and%20time%20%3C%3D%20now()%20GROUP%20BY%20time(30s)%20fill(previous)%3BSELECT%20mean(%22totalizer%22)%20AS%20%22totalizer%22%20FROM%20%22production%22%20WHERE%20(%22machine%22%20%3D%20'MILO_Packaging')%20AND%20time%20%3E%3D%20now()%20-%201h%20and%20time%20%3C%3D%20now()%20GROUP%20BY%20time(30s)%20fill(previous)",
    "precision": "ms",
    "hideFromInspector": false
  }
}

**What you expected to happen**:Should always return with request and response object instead
{
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/12/query",
    "params": {
      "db": "simulation",
      "epoch": "ms"
    },
    "data": "q=SELECT%20mean(%22target%22)%20AS%20%22target%22%20FROM%20%22production%22%20WHERE%20(%22machine%22%20%3D%20'MILO_Packaging')%20AND%20time%20%3E%3D%20now()%20-%201h%20and%20time%20%3C%3D%20now()%20GROUP%20BY%20time(30s)%20fill(previous)%3BSELECT%20mean(%22totalizer%22)%20AS%20%22totalizer%22%20FROM%20%22production%22%20WHERE%20(%22machine%22%20%3D%20'MILO_Packaging')%20AND%20time%20%3E%3D%20now()%20-%201h%20and%20time%20%3C%3D%20now()%20GROUP%20BY%20time(30s)%20fill(previous)",
    "precision": "ms",
    "hideFromInspector": false
  },
  "response": {
    "results": [
      {
        "statement_id": 0,
        "series": [
          {
            "name": "production",
            "columns": [
              "time",
              "target"
            ],
            "values": [
              [
                1629898410000,
                100000
              ],
              [
                1629898440000,
                100000
              ],
              [
                1629898470000,
                100000
              ],
              [
                1629898500000,
                100000
              ],
              [
                1629898530000,
                100000
              ],
              [
                1629898560000,
                100000
              ],
              [
                1629898590000,
                100000
              ],
              [
                1629898620000,
                100000
              ],
              [
                1629898650000,
                100000
              ],
              [
                1629898680000,
                100000
              ],
              [
                1629898710000,
                100000
              ],
              [
                1629898740000,
                100000
              ],
              [
                1629898770000,
                100000
              ],
              [
                1629898800000,
                100000
              ],
              [
                1629898830000,
                100000
              ],
              [
                1629898860000,
                100000
              ],
              [
                1629898890000,
                100000
              ],
              [
                1629898920000,
                100000
              ],
              [
                1629898950000,
                100000
              ],
              [
                1629898980000,
                100000
              ],
              [
                1629899010000,
                100000
              ],
              [
                1629899040000,
                100000
              ],
              [
                1629899070000,
                100000
              ],
              [
                1629899100000,
                100000
              ],
              [
                1629899130000,
                100000
              ],
              [
                1629899160000,
                100000
              ],
              [
                1629899190000,
                100000
              ],
              [
                1629899220000,
                100000
              ],
              [
                1629899250000,
                100000
              ],
              [
                1629899280000,
                100000
              ],
              [
                1629899310000,
                100000
              ],
              [
                1629899340000,
                100000
              ],
              [
                1629899370000,
                100000
              ],
              [
                1629899400000,
                100000
              ],
              [
                1629899430000,
                100000
              ],
              [
                1629899460000,
                100000
              ],
              [
                1629899490000,
                100000
              ],
              [
                1629899520000,
                100000
              ],
              [
                1629899550000,
                100000
              ],
              [
                1629899580000,
                100000
              ],
              [
                1629899610000,
                100000
              ],
              [
                1629899640000,
                100000
              ],
              [
                1629899670000,
                100000
              ],
              [
                1629899700000,
                100000
              ],
              [
                1629899730000,
                100000
              ],
              [
                1629899760000,
                100000
              ],
              [
                1629899790000,
                100000
              ],
              [
                1629899820000,
                100000
              ],
              [
                1629899850000,
                100000
              ],
              [
                1629899880000,
                100000
              ],
              [
                1629899910000,
                100000
              ],
              [
                1629899940000,
                100000
              ],
              [
                1629899970000,
                100000
              ],
              [
                1629900000000,
                100000
              ],
              [
                1629900030000,
                100000
              ],
              [
                1629900060000,
                100000
              ],
              [
                1629900090000,
                100000
              ],
              [
                1629900120000,
                100000
              ],
              [
                1629900150000,
                100000
              ],
              [
                1629900180000,
                100000
              ],
              [
                1629900210000,
                100000
              ],
              [
                1629900240000,
                100000
              ],
              [
                1629900270000,
                100000
              ],
              [
                1629900300000,
                100000
              ],
              [
                1629900330000,
                100000
              ],
              [
                1629900360000,
                100000
              ],
              [
                1629900390000,
                100000
              ],
              [
                1629900420000,
                100000
              ],
              [
                1629900450000,
                100000
              ],
              [
                1629900480000,
                100000
              ],
              [
                1629900510000,
                100000
              ],
              [
                1629900540000,
                100000
              ],
              [
                1629900570000,
                100000
              ],
              [
                1629900600000,
                100000
              ],
              [
                1629900630000,
                100000
              ],
              [
                1629900660000,
                100000
              ],
              [
                1629900690000,
                100000
              ],
              [
                1629900720000,
                100000
              ],
              [
                1629900750000,
                100000
              ],
              [
                1629900780000,
                100000
              ],
              [
                1629900810000,
                100000
              ],
              [
                1629900840000,
                100000
              ],
              [
                1629900870000,
                100000
              ],
              [
                1629900900000,
                100000
              ],
              [
                1629900930000,
                100000
              ],
              [
                1629900960000,
                100000
              ],
              [
                1629900990000,
                100000
              ],
              [
                1629901020000,
                100000
              ],
              [
                1629901050000,
                100000
              ],
              [
                1629901080000,
                100000
              ],
              [
                1629901110000,
                100000
              ],
              [
                1629901140000,
                100000
              ],
              [
                1629901170000,
                100000
              ],
              [
                1629901200000,
                100000
              ],
              [
                1629901230000,
                100000
              ],
              [
                1629901260000,
                100000
              ],
              [
                1629901290000,
                100000
              ],
              [
                1629901320000,
                100000
              ],
              [
                1629901350000,
                100000
              ],
              [
                1629901380000,
                100000
              ],
              [
                1629901410000,
                100000
              ],
              [
                1629901440000,
                100000
              ],
              [
                1629901470000,
                100000
              ],
              [
                1629901500000,
                100000
              ],
              [
                1629901530000,
                100000
              ],
              [
                1629901560000,
                100000
              ],
              [
                1629901590000,
                100000
              ],
              [
                1629901620000,
                100000
              ],
              [
                1629901650000,
                100000
              ],
              [
                1629901680000,
                100000
              ],
              [
                1629901710000,
                100000
              ],
              [
                1629901740000,
                100000
              ],
              [
                1629901770000,
                100000
              ],
              [
                1629901800000,
                100000
              ],
              [
                1629901830000,
                100000
              ],
              [
                1629901860000,
                100000
              ],
              [
                1629901890000,
                100000
              ],
              [
                1629901920000,
                100000
              ],
              [
                1629901950000,
                100000
              ],
              [
                1629901980000,
                100000
              ],
              [
                1629902010000,
                100000
              ]
            ]
          }
        ]
      },
      {
        "statement_id": 1,
        "series": [
          {
            "name": "production",
            "columns": [
              "time",
              "totalizer"
            ],
            "values": [
              [
                1629898410000,
                3
              ],
              [
                1629898440000,
                3
              ],
              [
                1629898470000,
                3
              ],
              [
                1629898500000,
                3
              ],
              [
                1629898530000,
                3
              ],
              [
                1629898560000,
                3
              ],
              [
                1629898590000,
                3
              ],
              [
                1629898620000,
                3
              ],
              [
                1629898650000,
                3
              ],
              [
                1629898680000,
                3
              ],
              [
                1629898710000,
                3
              ],
              [
                1629898740000,
                3
              ],
              [
                1629898770000,
                3
              ],
              [
                1629898800000,
                3
              ],
              [
                1629898830000,
                3
              ],
              [
                1629898860000,
                3
              ],
              [
                1629898890000,
                3
              ],
              [
                1629898920000,
                3
              ],
              [
                1629898950000,
                3
              ],
              [
                1629898980000,
                3
              ],
              [
                1629899010000,
                3
              ],
              [
                1629899040000,
                3
              ],
              [
                1629899070000,
                3
              ],
              [
                1629899100000,
                3
              ],
              [
                1629899130000,
                3
              ],
              [
                1629899160000,
                3
              ],
              [
                1629899190000,
                3
              ],
              [
                1629899220000,
                3
              ],
              [
                1629899250000,
                3
              ],
              [
                1629899280000,
                3
              ],
              [
                1629899310000,
                3
              ],
              [
                1629899340000,
                3
              ],
              [
                1629899370000,
                3
              ],
              [
                1629899400000,
                3
              ],
              [
                1629899430000,
                3
              ],
              [
                1629899460000,
                3
              ],
              [
                1629899490000,
                3
              ],
              [
                1629899520000,
                3
              ],
              [
                1629899550000,
                3
              ],
              [
                1629899580000,
                3
              ],
              [
                1629899610000,
                3
              ],
              [
                1629899640000,
                3
              ],
              [
                1629899670000,
                3
              ],
              [
                1629899700000,
                3
              ],
              [
                1629899730000,
                3
              ],
              [
                1629899760000,
                3
              ],
              [
                1629899790000,
                3
              ],
              [
                1629899820000,
                3
              ],
              [
                1629899850000,
                3
              ],
              [
                1629899880000,
                3
              ],
              [
                1629899910000,
                3
              ],
              [
                1629899940000,
                3
              ],
              [
                1629899970000,
                3
              ],
              [
                1629900000000,
                3
              ],
              [
                1629900030000,
                3
              ],
              [
                1629900060000,
                3
              ],
              [
                1629900090000,
                3
              ],
              [
                1629900120000,
                3
              ],
              [
                1629900150000,
                3
              ],
              [
                1629900180000,
                3
              ],
              [
                1629900210000,
                3
              ],
              [
                1629900240000,
                3
              ],
              [
                1629900270000,
                3
              ],
              [
                1629900300000,
                3
              ],
              [
                1629900330000,
                3
              ],
              [
                1629900360000,
                3
              ],
              [
                1629900390000,
                3
              ],
              [
                1629900420000,
                3
              ],
              [
                1629900450000,
                3
              ],
              [
                1629900480000,
                3
              ],
              [
                1629900510000,
                3
              ],
              [
                1629900540000,
                3
              ],
              [
                1629900570000,
                3
              ],
              [
                1629900600000,
                3
              ],
              [
                1629900630000,
                3
              ],
              [
                1629900660000,
                3
              ],
              [
                1629900690000,
                3
              ],
              [
                1629900720000,
                3
              ],
              [
                1629900750000,
                3
              ],
              [
                1629900780000,
                3
              ],
              [
                1629900810000,
                3
              ],
              [
                1629900840000,
                3
              ],
              [
                1629900870000,
                3
              ],
              [
                1629900900000,
                3
              ],
              [
                1629900930000,
                3
              ],
              [
                1629900960000,
                3
              ],
              [
                1629900990000,
                3
              ],
              [
                1629901020000,
                3
              ],
              [
                1629901050000,
                3
              ],
              [
                1629901080000,
                3
              ],
              [
                1629901110000,
                3
              ],
              [
                1629901140000,
                3
              ],
              [
                1629901170000,
                3
              ],
              [
                1629901200000,
                3
              ],
              [
                1629901230000,
                3
              ],
              [
                1629901260000,
                3
              ],
              [
                1629901290000,
                3
              ],
              [
                1629901320000,
                3
              ],
              [
                1629901350000,
                3
              ],
              [
                1629901380000,
                3
              ],
              [
                1629901410000,
                3
              ],
              [
                1629901440000,
                3
              ],
              [
                1629901470000,
                3
              ],
              [
                1629901500000,
                3
              ],
              [
                1629901530000,
                3
              ],
              [
                1629901560000,
                3
              ],
              [
                1629901590000,
                3
              ],
              [
                1629901620000,
                3
              ],
              [
                1629901650000,
                3
              ],
              [
                1629901680000,
                3
              ],
              [
                1629901710000,
                3
              ],
              [
                1629901740000,
                3
              ],
              [
                1629901770000,
                3
              ],
              [
                1629901800000,
                3
              ],
              [
                1629901830000,
                3
              ],
              [
                1629901860000,
                3
              ],
              [
                1629901890000,
                3
              ],
              [
                1629901920000,
                3
              ],
              [
                1629901950000,
                3
              ],
              [
                1629901980000,
                3
              ],
              [
                1629902010000,
                3
              ]
            ]
          }
        ]
      }
    ],
    "executedQueryString": "SELECT mean(\"target\") AS \"target\" FROM \"production\" WHERE (\"machine\" = 'MILO_Packaging') AND time >= now() - 1h and time <= now() GROUP BY time(30s) fill(previous);SELECT mean(\"totalizer\") AS \"totalizer\" FROM \"production\" WHERE (\"machine\" = 'MILO_Packaging') AND time >= now() - 1h and time <= now() GROUP BY time(30s) fill(previous)"
  }
}

**How to reproduce it (as minimally and precisely as possible)**: it happen occasionally for approximate every minutes.

**Anything else we need to know?**:
My influxdb raw data get input every seconds. Min interval set to 30s in dashboard query. Dashboard refresh rate at 5s. Query data for last hour. 
Tried set min interval as default which is 5s in my case, issue persist. 

**Environment**:
- Grafana version:v8.1.2
- Data source type & version: InfluxDB 1.6.4
- OS Grafana is installed on: Raspbian
- User OS & Browser: Windows10 , Google Chrome
- Grafana plugins: Time-series
- Others:

**Comment by zuchka** [comment]
Hi @TJChong92, since this issue has been stale for a few weeks now, I'm going to close it. If your issue persists, please trying following the above advice about running one SELECT query and report back with findings. 👍

**Comment by TJChong92** [comment]
Hi, I will try to running on single query. However, my application still prefer multiple query to produce useful information in single panel.

**Comment by TJChong92** [comment]
I had tried on single query. Sometime, its respond for the panel return similar output as I mentioned in the post, like as below:
{
  "status": 200,
  "statusText": "OK",
  "ok": true,
  "data": "",
  "url": "http://<removed- my server url >:3000/api/datasources/proxy/12/query?db=simulation&epoch=ms",
  "type": "basic",
  "redirected": false,
  "request": {
    "method": "POST",
    "url": "api/datasources/proxy/12/query",
    "params": {
      "db": "simulation",
      "epoch": "ms"
    },
    "data": "q=SELECT%20round(mean(%22speed%22))%20AS%20%22speed%22%20FROM%20%22production%22%20WHERE%20(%22machine%22%20%3D%20'MILO_Packaging')%20AND%20time%20%3E%3D%20now()%20-%201h%20and%20time%20%3C%3D%20now()%20GROUP%20BY%20time(10s)%20fill(previous)",
    "precision": "ms",
    "hideFromInspector": false
  }
}

![Capture](https://user-images.githubusercontent.com/76833412/134474964-0af4b6c5-d1ad-40f7-a087-e3d64e187ddd.JPG)

It seems to have received an response for the query, but return wrongly. It shall return response with data but instead, it return response like above and hence my panel showing me no data.
