### ISSUE TITLE
Grafana Bar Gauge Ignores Order By Sort

### ISSUE THREAD

**Issue by spxie85** [grafana/grafana#38567]
Suppose datasource for sample Bar Gauge here: https://play.grafana.org/d/vmie2cmWz/bar-gauge?orgId=1 is an SQL backend, and you apply ORDER BY on the values, the Bar Gauge continues to sort the results in alphabetical order based on the series name and ignores the sorting rules given by the underlying SQL.

The "Sort By" option under the Transform tab doesn't allow me to sort by values either.

**Comment by mckn** [comment]
Hmm, so the `renameByRegex` transformation does not sort the data. It will keep the same order as it had when it entered the transformation pipeline.

**Comment by mckn** [comment]
Can you please provide the panel data to assist with further investigation. You can extract the panel data by doing the following steps:

1. Inspect the panel to bring up the panel inspector.
<img width="804" alt="Skärmavbild 2021-08-30 kl  13 58 42" src="https://user-images.githubusercontent.com/172951/131335935-c4e1e8cc-4bd1-4388-9690-7c912f01beae.png">

2. Copy the data from the query-tab to get the raw backend response.
<img width="832" alt="Skärmavbild 2021-08-30 kl  13 59 42" src="https://user-images.githubusercontent.com/172951/131335791-e7968421-c947-4752-b90f-bd4080bbe3d3.png">

3. Download the CSV data from the  data-tab to get the data passed to the panel.
<img width="833" alt="Skärmavbild 2021-08-30 kl  13 59 55" src="https://user-images.githubusercontent.com/172951/131335839-c9c2b771-33b3-4453-b74d-eeb4f3de0829.png">

4. Attach the data to a comment in this issue. Thank you for helping us helping you 🙏🏻

**Comment by spxie85** [comment]
> Here's the raw data extracted from the SQL query used:
> 
> ```
> time,symbol,max
> 2021-08-26T09:00:24.781767Z,YESBANK,252916364 
> 2021-08-26T09:00:24.781767Z,ZOMATO,249723854 
> 2021-08-26T09:00:24.781767Z,IDEA,219484526 
> 2021-08-26T09:00:24.781767Z,RCOM,71727864 
> 2021-08-26T09:00:24.781767Z,VISESHINFO,71645482 
> 2021-08-26T09:00:24.781767Z,JPPOWER,67332142 
> 2021-08-26T09:00:24.781767Z,SAIL,62471280 
> 2021-08-26T09:00:24.781767Z,ITC,47263771 
> 2021-08-26T09:00:24.781767Z,IBULHSGFIN,39988986 
> 2021-08-26T09:00:24.781767Z,PNB,39507185 
> ```
> 
> Raw result from inspect / data
> 
> ```
> Time,IBULHSGFIN,IDEA,ITC,JPPOWER,PNB,RCOM,SAIL,VISESHINFO,YESBANK,ZOMATO
> 26-08-21 16:52,40.0 Mil,219 Mil,47.3 Mil,67.3 Mil,39.5 Mil,71.7 Mil,62.5 Mil,71.6 Mil,253 Mil,250 Mil
> ```
> 
> Bar Gauge Shown
> ![Untitled](https://user-images.githubusercontent.com/26221112/130935534-92b2bf8b-e9be-4ad7-b46c-8e0b36b0eeb6.png)

Hi,
I've actually provided this already above under "Raw result from inspect / data". Here's a screenshot to show:

![image](https://user-images.githubusercontent.com/26221112/131356674-594b57fd-13f6-41cb-9c4a-0ba62ece4025.png)

Here's another one when I format as Table
![image](https://user-images.githubusercontent.com/26221112/131356827-c8badecc-7416-4c12-88fd-43597b33f9f3.png)

Let me know if you need more info

**Comment by spxie85** [comment]
Here's a sample query statement
```
select now() as time, symbol, max(totalTradedQuantity)
from parser_machine
where symbol != null and totalTradedQuantity != null
and ReceiveTime BETWEEN '2021-07-26T02:00:00Z' AND '2021-07-26T14:59:59Z'
group by symbol
order by 2 desc
limit 10
```

**Comment by mckn** [comment]
> Here's a sample query statement
> 
> ```
> select now() as time, symbol, max(totalTradedQuantity)
> from parser_machine
> where symbol != null and totalTradedQuantity != null
> and ReceiveTime BETWEEN '2021-07-26T02:00:00Z' AND '2021-07-26T14:59:59Z'
> group by symbol
> order by 2 desc
> limit 10
> ```

Ah, sorry for being unclear. I meant the data from the `inspect -> query` tab @spxie85.

**Comment by spxie85** [comment]
ok, I suppose you're referring to the JSON request/response on the Query tab.

```
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "refId": "A",
          "datasourceId": 2,
          "rawSql": "select now() as time, symbol, max(totalTradedQuantity)\nfrom nsec_nyfe1227\nwhere symbol != null and totalTradedQuantity != null\nand $__timeFilter(ReceiveTime)\ngroup by symbol\norder by 2 desc\nlimit 10\n\n\n",
          "format": "time_series",
          "intervalMs": 60000,
          "maxDataPoints": 921
        }
      ],
      "range": {
        "from": "2021-07-26T02:00:00.000Z",
        "to": "2021-07-26T14:59:59.000Z",
        "raw": {
          "from": "2021-07-26T02:00:00.000Z",
          "to": "2021-07-26T14:59:59.000Z"
        }
      },
      "from": "1627264800000",
      "to": "1627311599000"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "meta": {
                "executedQueryString": "select now() as time, symbol, max(totalTradedQuantity)\nfrom nsec_nyfe1227\nwhere symbol != null and totalTradedQuantity != null\nand ReceiveTime BETWEEN '2021-07-26T02:00:00Z' AND '2021-07-26T14:59:59Z'\ngroup by symbol\norder by 2 desc\nlimit 10\n\n\n",
                "transformations": [
                  "renameByRegex"
                ]
              },
              "fields": [
                {
                  "name": "Time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "IBULHSGFIN"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "IDEA"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "ITC"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "JPPOWER"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "PNB"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "RCOM"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "SAIL"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "VISESHINFO"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "YESBANK"
                  }
                },
                {
                  "name": "max",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "symbol": "ZOMATO"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1630416452438
                ],
                [
                  39988986
                ],
                [
                  219484526
                ],
                [
                  47263771
                ],
                [
                  67332142
                ],
                [
                  39507185
                ],
                [
                  71727864
                ],
                [
                  62471280
                ],
                [
                  71645482
                ],
                [
                  252916364
                ],
                [
                  249723854
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}
```

**Comment by torkelo** [comment]
> This is what I see after doing the switch

After the switch format from time series to table you need to change the bar guage value options to "all values"

**Comment by mckn** [comment]
@spxie85 if you have a look at the request/response data you can see that it sorted in alphabetical order and not in the order of the values. So either we have an issue in your query or in the datasource.

**Comment by mckn** [comment]
@spxie85 as a work around you can try to do as @torkelo suggested. 

1. Switch the query result format (Select dropdown) to Table.
2. Change the bar guage value options to "all values".

And I will forward this issue to our backend squad since this is a bug when we are converting the data from the datasource into our wide data frame format.

**Comment by spxie85** [comment]
fantastic, I'm getting sorted result now! This combination of selection appears a little cryptic, and I certainly hope the bug gets fixed.

![image](https://user-images.githubusercontent.com/26221112/131514316-4f178690-9b8d-407c-9b2d-1b43033f90db.png)

**Comment by mckn** [comment]
After some more investigation I think the issue here is more about the UX and helping the user define a proper query and format. Because the data you are querying isn't really time series data. 

Let me know if you want me to re-open this issue.
