### ISSUE TITLE
Docs feedback: /administration/image_rendering.md

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#38560]
https://grafana.com/docs/grafana/latest/administration/image_rendering/#certificate-signed-by-internal-certificate-authorities

The troubleshooting section includes only steps for Linux.   Please add the steps needed to fix a Windows installation of Grafana for "Certificate signed by internal certificate authorities" issue.

**Comment by AgnesToulet** [comment]
Hello! I'm closing this issue because it was already done, see https://grafana.com/docs/grafana/latest/setup-grafana/image-rendering/troubleshooting/#:~:text=grafana/.pki/nssdb-,Windows%3A,-Copy 

Please, reach out if this was not enough to solve your issue.
