### ISSUE TITLE
Object selected in draw.io panel not replicate into dashboard when saved

### ISSUE THREAD

**Issue by MuhdMurad** [grafana/grafana#38570]
Object selected in draw.io panel not replicate into dashboard when saved:

Aug 25th 2021:

everytime select different ogjects in draw.io and save it, the object not reflected into dashboard and just coming as normal square object.*:

**Anything else we need to know?**:

Found that these files not being part of permitted  files extension list as per https://github.com/grafana/grafana/blob/v8.1.2/pkg/api/plugins.go#L24-L30. Please assist to make this compatible

GET https://<grafana>/public/plugins/agenty-flowcharting-panel/libs/drawio//stencils//cisco/routers.xml 403
GET https://<grafana>/public/plugins/agenty-flowcharting-panel/libs/drawio//stencils//cisco/switches.xml 403
GET https://<grafana>/public/plugins/agenty-flowcharting-panel/libs/drawio//stencils//cisco/servers.xml 403
GET https://<grafana>/public/plugins/agenty-flowcharting-panel/libs/drawio//stencils//cisco/buildings.xml 403

GET https://<grafana>/public/plugins/agenty-flowcharting-panel/static/defaultGraph.drawio 403
GET https://<grafana>/public/plugins/agenty-flowcharting-panel/static/defaultGraph.drawio 403
GET https://<grafana>/public/plugins/agenty-flowcharting-panel/static/defaultGraph.csv 403

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: InfluxDB. 1.2
- OS Grafana is installed on: Cloud
- User OS & Browser: CHrome
- Grafana plugins: FLowcharting 
- Others:

**Comment by bijwaard** [comment]
Dear all,
Guess this may also be the curprit with existing flowcharting drawings, see https://github.com/algenty/grafana-flowcharting/issues/314.
Kind regards,
Dennis
