### ISSUE TITLE
incorrect legends with influxdb 2.0

### ISSUE THREAD

**Issue by tatsutaigu** [grafana/grafana#38575]
**What happened**:
Hi,

I would like to show data on every Friday.
I hope legends to show "test1 val".
I tried, but legends are too long.
And, `weekday` is shown. I do not want to show it.
Column titles on table are not correct. 

How do I do it?

![image](https://user-images.githubusercontent.com/44219065/130925874-563c0877-e235-43f3-b41d-ea974b8ae634.png)
![image](https://user-images.githubusercontent.com/44219065/130927818-d0d2e680-1144-44a2-a28d-ff73769c4a58.png)

**How to reproduce it (as minimally and precisely as possible)**:
>     import “date”
> 
>     from(bucket: “my_bucket”)
>     |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
>     |> filter(fn: (r) => r["_measurement"] == “test”)
>     |> filter(fn: (r) => r["_field"] == “val”)
>     |> filter(fn: (r) => r[“Location”] == “test1”)
>     |> timeShift(duration: 9h)
>     |> map(fn: (r) => ({r with weekday: date.weekDay(t: r._time)}))
>     |> filter(fn: (r) => r.weekday == date.Friday)
>     |> aggregateWindow(every: 1d, fn: last, createEmpty: false)
>     |> yield(name: “last”)

**Environment**:
- Grafana version: 8.1.1
- Data source type & version: influxDB 2.0.7

**Comment by tatsutaigu** [comment]
@gabor,

Thank you for your advice!
I could set "Merge" and "Organize fields" on "Transform" and resolved it.

When I remove `|> filter(fn: (r) => r[“Location”] == “test1”)` from query, "Outer join" is better than "Merge".

**Comment by tatsutaigu** [comment]
Hi,
I set "Outer join" and "Organize fields" on "Transform".
When time range is changed, `_value` on "Organize fields" change to blank. 
for example
I set time rage "2021-07-02 00:00:00" to "2021-07-31 23:59:59" and `_value` on "Organize fields" are set.
time range is set to "2021-07-01 00:00:00" to "2021-07-30 23:59:59", then `_value` on "Organize fields" are cleared.
back to "2021-07-02 00:00:00" to "2021-07-31 23:59:59", `_value` on "Organize fields" that I set are shown.

**Comment by mckn** [comment]
> Hi,
> I set "Outer join" and "Organize fields" on "Transform".
> When time range is changed, `_value` on "Organize fields" change to blank.
> for example
> I set time rage "2021-07-02 00:00:00" to "2021-07-31 23:59:59" and `_value` on "Organize fields" are set.
> time range is set to "2021-07-01 00:00:00" to "2021-07-30 23:59:59", then `_value` on "Organize fields" are cleared.
> back to "2021-07-02 00:00:00" to "2021-07-31 23:59:59", `_value` on "Organize fields" that I set are shown.

hmm, can you share the raw data? Sounds like the `_value` field is missing for that time range. You can do inspect on the panel and have a look at the `Query` tab to see the raw data.

<img width="512" alt="Skärmavbild 2021-08-30 kl  10 30 40" src="https://user-images.githubusercontent.com/172951/131310604-d785803e-ae1b-4fd6-a817-2376a0f5e63c.png">

<img width="477" alt="Skärmavbild 2021-08-30 kl  10 31 11" src="https://user-images.githubusercontent.com/172951/131310616-73c1e2f5-079d-4860-8241-2e5bfaf7e4f1.png">

**Comment by tatsutaigu** [comment]
Hi, @mckn,

Query is here.
![image](https://user-images.githubusercontent.com/44219065/131585493-55042172-4bcc-4a92-a2f9-d2b4a4d55983.png)

Legends includes `_start` and `_stop` value.
Therefore, renamed `_value` on `organize fields` were cleared when time range changed.
I think it is root cause.
![image](https://user-images.githubusercontent.com/44219065/131585159-dff58c4d-2c3c-484d-b99e-243bd05be9e5.png)

**Comment by mckn** [comment]
@tatsutaigu to me it sounds like the `_value` is missing from the returned data when changing the time range. Can you please provide the data being returned from the two different scenarios?

Also, can you please verify that you are using the macro to specify time range in your query?

You can extract the panel data by doing the following steps:

1. Inspect the panel to bring up the panel inspector.
<img width="804" alt="Skärmavbild 2021-08-30 kl  13 58 42" src="https://user-images.githubusercontent.com/172951/131335935-c4e1e8cc-4bd1-4388-9690-7c912f01beae.png">

2. Copy the data from the query-tab to get the raw backend response.
<img width="832" alt="Skärmavbild 2021-08-30 kl  13 59 42" src="https://user-images.githubusercontent.com/172951/131335791-e7968421-c947-4752-b90f-bd4080bbe3d3.png">

3. Download the CSV data from the  data-tab to get the data passed to the panel.
<img width="833" alt="Skärmavbild 2021-08-30 kl  13 59 55" src="https://user-images.githubusercontent.com/172951/131335839-c9c2b771-33b3-4453-b74d-eeb4f3de0829.png">

4. Attach the data to a comment in this issue. Thank you for helping us helping you 🙏🏻

**Comment by tatsutaigu** [comment]
Hi, @mckn,

data is here.
if you need more information, please let me know.

> "_time","_value {Location=""target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-30 23:59:59 +0000 UTC""}","weekday {Location=""target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-30 23:59:59 +0000 UTC""}"
> 2021-07-03 09:00:00,4163,5
> 2021-07-10 09:00:00,3661,5
> 2021-07-17 09:00:00,4288,5
> 2021-07-24 09:00:00,4967,5
> 2021-07-31 08:59:59,4124,5
>

**Comment by mckn** [comment]
> Hi, @mckn,
> 
> data is here.
> if you need more information, please let me know.
> 
> > "_time","_value {Location=""target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-30 23:59:59 +0000 UTC""}","weekday {Location=""target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-30 23:59:59 +0000 UTC""}"
> > 2021-07-03 09:00:00,4163,5
> > 2021-07-10 09:00:00,3661,5
> > 2021-07-17 09:00:00,4288,5
> > 2021-07-24 09:00:00,4967,5
> > 2021-07-31 08:59:59,4124,5
> > 
> 

Hello, thanks but you did not reply to my questions. Please try again.

**Comment by tatsutaigu** [comment]
I'm sorry, I could not understand your question.

I think macro of time range is working.

start = 2021-07-02 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-30 23:59:59 ( at local time: UTC + 9h )
![image](https://user-images.githubusercontent.com/44219065/132291900-61323f50-ffa8-4f92-964c-00a80041029a.png)

start = 2021-07-09 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-31 23:59:59 ( at local time: UTC + 9h )
![image](https://user-images.githubusercontent.com/44219065/132292352-7c64110d-f849-4079-97fc-4b252e176c79.png)

step 2:
Query are below.

start = 2021-07-02 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-30 23:59:59 ( at local time: UTC + 9h )
![image](https://user-images.githubusercontent.com/44219065/132292625-14b72429-2001-49f5-970e-c317297f8715.png)

start = 2021-07-09 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-31 23:59:59 ( at local time: UTC + 9h )
![image](https://user-images.githubusercontent.com/44219065/132292748-fd8f1db2-518f-44bc-8e2d-aa6cc3d25aa6.png)

Step3 :
CSV files of data are below.

start = 2021-07-02 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-30 23:59:59 ( at local time: UTC + 9h )
> "_time","_value {Location=""A_target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-30 23:59:59 +0000 UTC""}","weekday {Location=""A_target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-30 23:59:59 +0000 UTC""}"
> 2021-07-03 09:00:00,4163,5
> 2021-07-10 09:00:00,3661,5
> 2021-07-17 09:00:00,4288,5
> 2021-07-24 09:00:00,4967,5
> 2021-07-31 08:59:59,4124,5

start = 2021-07-09 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-31 23:59:59 ( at local time: UTC + 9h )
> "_time","_value {Location=""A_target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-31 23:59:59 +0000 UTC""}","weekday {Location=""A_target"", _field=""test"", _start=""2021-07-02 00:00:00 +0000 UTC"", _stop=""2021-07-31 23:59:59 +0000 UTC""}"
> 2021-07-03 09:00:00,4163,5
> 2021-07-10 09:00:00,3661,5
> 2021-07-17 09:00:00,4288,5
> 2021-07-24 09:00:00,4967,5
> 2021-07-31 09:00:00,4124,5

**Comment by mckn** [comment]
No worries, super thanks! Can you also share what transformations you are applying?

**Comment by tatsutaigu** [comment]
I use `Outer join` and `Organize fields` as below.

![image](https://user-images.githubusercontent.com/44219065/132306370-a8bd8b65-aa80-4de2-9676-b237da40c5fa.png)

**Comment by gabor** [comment]
@tatsutaigu thank you for all the information!

i have some more questions:
1. when you say "When time range is changed, _value on "Organize fields" change to blank." ... could you post a screenshot of _value being blank? 
2. can you try changing "Outer join" Transform to "Merge" Transform? does that help?

**Comment by tatsutaigu** [comment]
Hi, @gabor ,

1.
`_value` has `_start` and `_stop`.
when `_start` or `_stop` value were changed by time range, `_value` on `Outer join` are mismatch.
so, set strings are blank.

start = 2021-07-02 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-30 23:59:59 ( at local time: UTC + 9h )
![image](https://user-images.githubusercontent.com/44219065/132310010-9a51d221-c091-4302-9e62-4cc828af8a39.png)

start = 2021-07-09 00:00:00 ( at local time: UTC + 9h )
stop = 2021-07-31 23:59:59 ( at local time: UTC + 9h )
![image](https://user-images.githubusercontent.com/44219065/132312641-af82254e-b345-48d1-86d2-d853c29054fb.png)


2.
my data is 22 legends.
but, legends is only one when I use `Merge`.
![image](https://user-images.githubusercontent.com/44219065/132314291-6a422259-ef6a-48b7-9a04-6dc8715ca3c2.png)

**Comment by gabor** [comment]
hi @tatsutaigu , thanks for the information. it seems i will need to see the data that is returned from the influxdb database to grafana. this is how you can get it:

1. set the time-range to the one that works
2. run the query, open the query-inspector, where you can see the flux query. COPY the flux-query from the query-inspector.
3. open the influxdb web-user-interface, it is at the same URL where influxdb runs, for example at `http://localhost:8086` . go to `explore` in it, click on the [script editor] button, and PASTE the query there. and then run it.
4. there is a button to download CSV [ v CSV]. press it. it will allow you to download the raw CSV output of the query.
5. edit the CSV and make sure there is no private/secret info in it. 
6. upload the CSV here.
7. now go back to grafana, set the time-range to the one that does not work, repeat the process and upload the CSV file here

with those two CSV files it should be easier to find out what went wrong. thanks!

**Comment by tatsutaigu** [comment]
Hi, @gabe-kent ,
I would like to explain this phenomenon again.

Please refer to below image.
![image](https://user-images.githubusercontent.com/44219065/133222477-df3b30ec-4838-4018-905c-b83f61d5e9f1.png)

title `every: 1d` is correct legends at all time range.
however, title `every: friday` is incorrect legends.
legends of `every: friday` has 2 items; _value{...} and weekday{...}.

query of title `every: 1d`  is here.
> import "date"
> 
> from(bucket: "my_bucket2")
>   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
>   |> filter(fn: (r) => r["_measurement"] == "test")
>   |> filter(fn: (r) => r["_field"] == "target")
>   |> aggregateWindow(every: 1h, fn: last, createEmpty: false)
>   |> timeShift(duration: 9h)
>   |> aggregateWindow(every: 1d, fn: last, createEmpty: false)
>   |> timeShift(duration: -9h1s)
>   |> yield(name: "last")
 
query of title `every: friday`  is here
> import "date"
> 
> from(bucket: "my_bucket2")
>   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
>   |> filter(fn: (r) => r["_measurement"] == "test")
>   |> filter(fn: (r) => r["_field"] == "target")
>   |> aggregateWindow(every: 1h, fn: last, createEmpty: false)
>   |> timeShift(duration: 9h)
>   |> map(fn: (r) => ({r with weekday: date.weekDay(t: r._time)}))
>   |> filter(fn: (r) => r.weekday == date.Friday)
>   |> aggregateWindow(every: 1d, fn: max, createEmpty: false)
>   |> timeShift(duration: -9h1s)
>   |> yield(name: "max")

`map(fn: (r) => ({r with weekday: date.weekDay(t: r._time)}))` and `filter(fn: (r) => r.weekday == date.Friday)` are added to query of title `every: 1d`.

I guess Grafana cannot process map() function.

**Comment by gabor** [comment]
hi @tatsutaigu , the problem seems to be that your second flux query adds one more column to the data ( "weekday" ), and this changes the layout of the data. two possible solutions:

A.
remove the column after the filter:
```
|> map(fn: (r) => ({r with weekday: date.weekDay(t: r._time)}))
|> filter(fn: (r) => r.weekday == date.Friday)
|> drop(columns: ["Friday"])
```

B.
do not add the new column, just filter. remove the `map` line, and change the filter like this:
```
|> filter(fn: (r) =>  date.weekDay(t: r._time) == date.Friday)
```

does this fix your problem?

**Comment by tatsutaigu** [comment]
hi @gabor ,
Thank you for your advice!
this problem solved by your solution B.
