### ISSUE TITLE
How do I create/determine the "slug" paramater for the API?

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#3858]
Right now the get/delete functions of the API require a slug parameter to identify the dashboard in question but the search for example only returns id and title but not the slug. There seems to be no function to calculate the slug from an id or title and I think it would be useful to be able to get/delete a dashboard using its id.

Right now when I perform a search using the API how can I delete one of the returned dashboards using only the data that was returned in that search?

**Comment by torkelo** [comment]
the search api returns the slug (in the uri property which also contains the dashboard type)

**Comment by dennisjac** [comment]
But that also contains a prefix "db/". Can I transmit the string including the "db/" and the server knows what to do or do I need to somehow extract the slug itself from the uri. If so how can I do this in a way that won't break in the future? Is there any particular reason why the id isn't used for this?

**Comment by torkelo** [comment]
well it is included in the read api as well. 

GET /api/dashboards/db/new-dashboard

**Comment by dennisjac** [comment]
if "/api/dashboards" is the API endpoint and "db/new-dashboard" the identifier that would make sense I guess but in that case it would be better to update the documentation accordingly and describe the command as "GET/DELETE /api/dashboards/:dashboard-uri" to make this more obvious.
Right now its not really clear what the actual identifier for the dashboard is only the slug as the documentation suggests or the uri which your comments suggest.

**Comment by torkelo** [comment]
You right the docs could be more clear on this. The reason for this is that there are different types of dashboards and the slug is the identifier and the url segment before is the type of dashboard (db, file, script)
