### ISSUE TITLE
Graph(old): It no longer renders thresholds in 8.1+

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#38596]
Noticed on play site that the old graph is no longer showing any thresholds. 

* Example https://play.grafana.org/d/000000074/alerting?orgId=1&editPanel=4

**Comment by hugohaggmark** [comment]
Is this related to what you're working on @dprokop, I mean with thresholds?

**Comment by dprokop** [comment]
> Is this related to what you're working on @dprokop, I mean with thresholds?

Nope - my work is related to enabling threshold controls in the graph ng based visualizations, and in the alerting views to start with. We have not decided yet whether or not we want to bring this functionality to the time series panel.

**Comment by axelavargas** [comment]
@torkelo I noticed there is a message that says: Visual thresholds options disabled, it seems intentional 

![AlertingThresholds](https://user-images.githubusercontent.com/239999/132221482-0d257a8b-9caa-42b3-a35b-7c16b275c1f0.png)

**Comment by axelavargas** [comment]
Nevermind, I tested in another dashboard and indeed there are no thresholds, I will take a look :)

**Comment by axelavargas** [comment]
Update:

I noticed in the graph plugin we have this [line](https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/graph/graph.ts#L79) that is checking if ng-alert feature toggle is enabled or not, based on that it will draw the thresholds. On play.grafana.org we have that feature toggle enabled, and this is the reason we can't see thresholds.

```
// unified alerting does not support threshold for graphs, at least for now
if (!config.featureToggles.ngalert) {
      this.thresholdManager = new ThresholdManager(this.ctrl);
 }

```
Locally I tested removing the feature toggle and the thresholds were shown correctly, I asked the alerting team about this topic, to gather more context.

**Comment by torkelo** [comment]
@axelavargas ah! please remove that if statement, we should always add the threshold manager

**Comment by axelavargas** [comment]
@torkelo I got some feedback from @domasx2, this was added to avoid showing dashboard alerts thresholds when `ngalert` is enabled, but the implementation is missing other threshold use cases like this, he will take over this issue tomorrow.

**Comment by torkelo** [comment]
@domasx2 not sure I understand the logic for now showing graph thresholds, this display option should be available to users always.

**Comment by domasx2** [comment]
The intention was to only disable dashboard alert thresholds if `ngalert` is enabled. Disabling thresholds entirely was a mistake. Not enough research / PR reviews I guess :)

**Comment by torkelo** [comment]
@domasx2 but even with ngalert enabled, do not understand the reasons to disable a graph visualization feature

**Comment by domasx2** [comment]
Did not intend to disable graph visualizatiom feature entirely, this was a mistake. Just to not render old existing dashboard alert threshold if ngalert is emabled

**Comment by domasx2** [comment]
I think didnt realize at the time that threshold manager was not for alerts only, my bad

**Comment by domasx2** [comment]
@hugohaggmark @torkelo need some input on how to best proceed with fixing this, problem descirbed in draft PR: https://github.com/grafana/grafana/pull/38918
