### ISSUE TITLE
grafana dashboards can not be saved,getting 415 error.

### ISSUE THREAD

**Issue by cchiremath** [grafana/grafana#3859]
Hi ,
i could save few dashboards earlier on grafana but now i am getting 415 error while saving any old dashboard or new dashboard.

we are not using any separate DB. and we are using grafana 2.5

can u plz assist with the solution.

regards,
Chandrashekhar

**Comment by torkelo** [comment]
Can you show any output from the grafana.log and any response from grafana beside the status code?

**Comment by cchiremath** [comment]
2016/01/26 14:57:04 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 621.383µs
2016/01/26 14:59:23 [I] Completed /api/dashboards/db/undefined 404 Not Found in 6.648919ms
2016/01/26 15:02:21 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 672.964µs
2016/01/26 15:03:10 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 1.181539ms
2016/01/26 15:03:11 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 847.71µs
2016/01/26 15:03:41 [I] Completed /dashboard-import/haeventpipelinecopper 404 Not Found in 1.079312ms
2016/01/26 15:04:11 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 617.534µs
2016/01/26 15:06:51 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 665.692µs
2016/01/26 15:07:24 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 622.051µs
2016/01/26 15:07:32 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 563.334µs
2016/01/26 15:07:43 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 826.686µs
2016/01/26 15:07:44 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 638.034µs
2016/01/26 15:07:44 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 512.228µs
2016/01/26 15:26:44 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 562.008µs
2016/01/26 15:26:48 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 665.591µs
2016/01/26 15:26:52 [I] Completed /api/dashboards/db/ 415 Unsupported Media Type in 761.048µs

POST https://revproxy.sc-tx3.huron-dev.com:8002/grafana/api/dashboards/db/ 415 (Unsupported Media Type)(anonymous function) @ app.b4b243aa.js:12q @ app.b4b243aa.js:12j @ app.b4b243aa.js:12i @ app.b4b243aa.js:13(anonymous function) @ app.b4b243aa.js:13n.$eval @ app.b4b243aa.js:13n.$digest @ app.b4b243aa.js:13n.$apply @ app.b4b243aa.js:13(anonymous function) @ app.b4b243aa.js:15_.event.dispatch @ app.b4b243aa.js:7q.handle @ app.b4b243aa.js:6
app.b4b243aa.js:12 Object {data: Array[1], status: 415, config: Object, statusText: "Unsupported Media Type"}config: Objectdata: Array[1]headers: (c)status: 415statusText: "Unsupported Media Type"__proto__: Object(anonymous function) @ app.b4b243aa.js:12(anonymous function) @ app.b4b243aa.js:12i @ app.b4b243aa.js:13(anonymous function) @ app.b4b243aa.js:13n.$eval @ app.b4b243aa.js:13n.$digest @ app.b4b243aa.js:13n.$apply @ app.b4b243aa.js:13f @ app.b4b243aa.js:12r @ app.b4b243aa.js:12v.onload @ app.b4b243aa.js:12
app.b4b243aa.js:12 [Object, severity: "warning"]0: Objectlength: 1severity: "warning"__proto__: Array[0](anonymous function) @ app.b4b243aa.js:12(anonymous function) @ app.b4b243aa.js:12(anonymous function) @ app.b4b243aa.js:13e @ app.b4b243aa.js:10(anonymous function) @ app.b4b243aa.js:10

**Comment by torkelo** [comment]
Must be your reverse proxy that is causing problem :(

**Comment by cvvs** [comment]
Would setting the `X-Content-Type-Options: nosniff` header break grafana?

**Comment by torkelo** [comment]
nope

**Comment by cvvs** [comment]
Unsetting all the headers will being passed to grafana will, however. Thanks, @torkelo. This was self-inflicted.
