### ISSUE TITLE
Missing "Access" config in datasource UI

### ISSUE THREAD

**Issue by Rohlik** [grafana/grafana#38601]
**What happened**:
There is no setting/toggle in Grafana UI while editing/creating a new datasource. For example Graphite.

**What you expected to happen**:
I expect some toggle setting in UI.

**How to reproduce it (as minimally and precisely as possible)**:
Edit or create Graphite datasource.

**Anything else we need to know?**:
According to official [Docs](https://grafana.com/docs/grafana/latest/datasources/graphite/). `Access` is valid and even required parameter (with _server_ as default) so it should be visible in UI datasource setting.

**Environment**:
- Grafana version: 7.2.2 and 8.1.0
- Data source type & version: Graphite 1.1.x
- OS Grafana is installed on: Linux CentOS 8 via DEB package
- User OS & Browser: Debian with latest Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by achatterjee-grafana** [comment]
I do not see the access option either. Looking at https://play.grafana.org/datasources/edit/000000001

![2021-08-30_16-03-43](https://user-images.githubusercontent.com/70489351/131398296-79623f50-4d41-44de-add6-2895e4602ba6.png)

**Comment by ifrost** [comment]
I think docs are incorrect and "Access" could be removed from there. Graphite datasource always uses "Server" mode. @Rohlik do you need "Browser" mode for Graphite? If yes, could you explain a bit more why and what's your use case?

**Comment by Rohlik** [comment]
@ifrost I don't know if docs are outdated but "Browser/Direct" access mode definitely works.

Our use case:
We are using several Graphite datasources and each of them are behind Apache web proxy with Kerberos auth (GSSAPI module), so user needs to be authenticated to access metrics from Graphite.
That's why we are using "Browser" mode with option "With Credentials" enabled.

**Comment by achatterjee-grafana** [comment]
Thanks, @ifrost for resolving the issue.

**Comment by ifrost** [comment]
Using browser access mode is deprecated. Docs will updated in the next release.
