### ISSUE TITLE
Docs feedback: /panels/panel-library.md

### ISSUE THREAD

**Issue by henryw374** [grafana/grafana#38605]
hi, I would like some info on how to manage version history of library panels. 

Thanks

**Comment by achatterjee-grafana** [comment]
@pkolyvas and @kaydelaney, do we have the capability? If so, can you let me know so that I can update the docs? TY

**Comment by pkolyvas** [comment]
Library panels don't currently have a version history. I'm going to retile this issue and move it to discussions in order to start tracking a feature request.
