### ISSUE TITLE
Dashboard Links add backslashes to variable values with (at least) influxdb

### ISSUE THREAD

**Issue by wamdam** [grafana/grafana#3861]
We're using the dashboard link feature as in https://github.com/grafana/grafana/issues/1944 to link from one dashboard to another including the selected variables.

![bildschirmfoto von 2016-01-27 09-24-05](https://cloud.githubusercontent.com/assets/147094/12607770/bfbe4d1a-c4d7-11e5-81fb-107209c254b0.png)

We're querying the list of variables from the database similar to this:

![bildschirmfoto von 2016-01-27 09-32-30](https://cloud.githubusercontent.com/assets/147094/12607938/efd2c93a-c4d8-11e5-9f16-b3fba4a5c37d.png)

This works well until a selected variable has a character in it which influxdb would backslash (like -, ., and more). So a selection of `server-123` would become `server\-123` when the link to the other dashboard is created.

I _guess_ that this behavour is because influxdb wants to search with regexp for the selected tags. The generated dashboard link looks like this:

`...?from=now-1h&to=now&var-var_server=server\-123&var-var_othervar=some\.value&var-test=All`

The dashboard which opens from this link can't find the values in its own variable lists and shows them as selected variable including the backslashes. This results in an empty dashboard.

I have followed the code path down to `linkSrv.js:30 addParamsToUrl` where the _value_ is added to the url. However, I was unable to follow the path down to some influxdb integration code.
I have not tested this with other databases however.

**Comment by mtanda** [comment]
this issue maybe related, https://github.com/grafana/grafana/issues/2918

**Comment by torkelo** [comment]
this should be fixed in Grafana 3.x
