### ISSUE TITLE
Allow embedding of entire dashboards

### ISSUE THREAD

**Issue by macgregor** [grafana/grafana#3863]
I love the individual embeddable graphs. I use them in a small scrolling marque that displays metrics for our product in the office (grafana playlists wasnt to my liking, too simple and leaves too much screen real estate wasted). Works perfectly. I was disappointed that I couldn't embed an entire dashboard in an iframe though.  

Any way dashboard-solo could be upgraded to allow embedding of dashboards, or perhaps rows of graphs?

**Comment by torkelo** [comment]
the dashboard solo route is also used for panel PNG rendering.

**Comment by torkelo** [comment]
If you want to embed a dashboard you will have to iframe whole grafana. This could be improved in the future if we have a kiosk mode (something that can hide the header)
