### ISSUE TITLE
Support JSON encoding/decoding of large integer values in data frames

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#38634]
**What happened**:
Ran a table query selecting column of data type bigint and when visualized in table panel the values are wrong.

Query:
```sql
select cast(12345678901234801 as bigint) as alert union all 
select cast(12345678901234902 as bigint) as alert union all
select cast(12345678901235003 as bigint) as alert union all
select cast(12345678901235104 as bigint) as alert union all
select cast(12345678901235205 as bigint) as alert union all
select cast(12345678901235306 as bigint) as alert
```

Result:
![Selection_1039](https://user-images.githubusercontent.com/1668778/131125555-45cf1d37-e784-47e5-afdd-7299743e3333.png)

Query inspector:
```json
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "refId": "A",
          "datasourceId": 60,
          "rawSql": "SELECT cast(12345678901234801 as bigint) as alert union all \nselect cast(12345678901234902 as bigint) as alert union all\nselect cast(12345678901235003 as bigint) as alert union all\nselect cast(12345678901235104 as bigint) as alert union all\nselect cast(12345678901235205 as bigint) as alert union all\nselect cast(12345678901235306 as bigint) as alert",
          "format": "table",
          "intervalMs": 60000,
          "maxDataPoints": 930
        }
      ],
      "range": {
        "from": "2021-08-27T06:12:35.449Z",
        "to": "2021-08-27T12:12:35.449Z",
        "raw": {
          "from": "now-6h",
          "to": "now"
        }
      },
      "from": "1630044755449",
      "to": "1630066355449"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "meta": {
                "executedQueryString": "SELECT cast(12345678901234801 as bigint) as alert union all \nselect cast(12345678901234902 as bigint) as alert union all\nselect cast(12345678901235003 as bigint) as alert union all\nselect cast(12345678901235104 as bigint) as alert union all\nselect cast(12345678901235205 as bigint) as alert union all\nselect cast(12345678901235306 as bigint) as alert"
              },
              "fields": [
                {
                  "name": "alert",
                  "type": "number",
                  "typeInfo": {
                    "frame": "int64",
                    "nullable": true
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  12345678901234800,
                  12345678901234902,
                  12345678901235004,
                  12345678901235104,
                  12345678901235204,
                  12345678901235306
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}
```

**What you expected to happen**:
The values to represent what I selected from the database:
```
12345678901234801
12345678901234902
12345678901235003
12345678901235104
12345678901235205
12345678901235306
```

**How to reproduce it (as minimally and precisely as possible)**:
See _What happened_.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0 and main branch (e872032a2b5edd4be5c6a5b42efa7c93d7e9f23a)
- Data source type & version: Microsoft SQL Server

**Comment by kminehart** [comment]
I'm assigned to this one but I'm really unsure about what to do about it.

From @sakjur :

> I get the same result from running this in the browser’s console:

```
console.log(12345678901234801,
12345678901234902,
12345678901235003,
12345678901235104,
12345678901235205,
12345678901235306)
```

:thinking: do we need to stringify it before displaying it in the table?

**Comment by sakjur** [comment]
> 🤔 do we need to stringify it before displaying it in the table?

If we'd do that, that'd possibly break some transformations 🤔

**Comment by kminehart** [comment]
What about using the BigInt type for these in the frontend? 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by sakjur** [comment]
That looks really interesting, and afaict our the browsers we say we support supports it https://caniuse.com/bigint

**Comment by kminehart** [comment]
I'm thinking this may be a larger task then where we add support for `big.Int` in the data frame (cc @ryantxu ) which should be represented by the BigInt type on the frontend, then.

**Comment by marefr** [comment]
@kminehart yes I changed it :+1:

**Comment by leeoniya** [comment]
i dont think this is feasible.

1. JSON cannot encode BigInt except as stings, which means every value would need to be converted to BigInt.
2. BigInt does not work with normal math operators, so all functions that do anything with numbers (like transformers) would need to be have an additional, slower BigInt code path.
3. there is little reason why numbers this large need to exist in the frontend. e.g. the use case of needing exact bytes in an exabyte-magnitude number is an outlier among outliers.
