### ISSUE TITLE
Support tags in rows and columns at the same time

### ISSUE THREAD

**Issue by AlexeyDmitriev** [grafana/grafana#3865]
Suppose such case:

I have different type of events which are stored in influxdb in measurement "events" and each have two tags: type of event(user_registration, error, warning...) and server on which it happened.

I want a table which has servers as rows and type of events which shows number of events in last 1 hour for example

query may be smth like

`SELECT sum("count") FROM "log_rate" WHERE $rimeInterval GROUP BY "server", "event_type"`

I didn't find a way to do this now

**Comment by torkelo** [comment]
Made an example for you :)
http://play.grafana.org/dashboard/db/influxdb?panelId=3&fullscreen&edit

**Comment by AlexeyDmitriev** [comment]
@torkelo it's not exactly what I want, here column is for value

What I mean is something like

server\datacenter | America | Europe
------------ | -------------
server1 | 23 | 23
server3 | 46 | 17
server5 | 99 | 77

**Comment by hugodlg** [comment]
@torkelo the example is no longer accessible
Can we have it again?
