### ISSUE TITLE
Tag values are not respecting $timeFilter. could be a time zone issue.

### ISSUE THREAD

**Issue by sunildabburi** [grafana/grafana#38657]
**What happened**:
Tag values are not respecting $timeFilter. could be a time zone issue.

**What you expected to happen**:
Tag values should get filtered based on $timeFilter provided

**How to reproduce it (as minimally and precisely as possible)**:
Capture a metric with a hostname tag for few hours and then change the hostname and try capturing the metric again for the next 4 hours. See if the tag values for that filter still show the old hostname even when the time range is set to last 15 minutes.

We are capturing pod names (aka hostnames) using our health metric by getting the get tag values for a given $timeFilter.
Even though the pod is not available currently, it is still being shown in tag values. However, the health metric by itself does not show that pod name. This makes me think if tag values are not properly considering the $timeFilter. could be some time zone issue here.

**Anything else we need to know?**:
Attaching screenshots for clarification

last 6-hour window showing both hostname tags in health metric

<img width="1381" alt="Screen Shot 2021-08-27 at 3 33 49 PM" src="https://user-images.githubusercontent.com/6094289/131182429-2fa12fa5-5a17-40ca-b470-8b39dd6f75a2.png">

last 5-minute window showing only 1 hostname tag in the health metric

<img width="1381" alt="Screen Shot 2021-08-27 at 3 35 13 PM" src="https://user-images.githubusercontent.com/6094289/131182485-949a3cb0-01ec-4973-8d18-a4889fe26aee.png">

last 6-hour window showing both hostname tag values

<img width="1381" alt="Screen Shot 2021-08-27 at 3 34 48 PM" src="https://user-images.githubusercontent.com/6094289/131182519-95ecff3b-51ef-4933-9949-3c9e502d92aa.png">

last 5-minute window showing both hostname tag values

<img width="1381" alt="Screen Shot 2021-08-27 at 3 34 59 PM" src="https://user-images.githubusercontent.com/6094289/131182554-43250368-c217-4143-8953-ec54c502da31.png">

tag values reflecting both hostnames under variables

<img width="1080" alt="Screen Shot 2021-08-27 at 4 03 17 PM" src="https://user-images.githubusercontent.com/6094289/131182722-be6d222b-d15c-44b9-bf4a-4281bf38df2f.png">

We have the default time zone set to Canada EDT. Tried with UTC as well. No luck.

**Environment**:
- Grafana version: v7.3.7 (1e261642f4)
- Data source type & version: Influx DB. Not sure of the version.
- OS Grafana is installed on: Linux
- User OS & Browser: Mac, Chrome
- Grafana plugins: None
- Others:

**Comment by gabor** [comment]
hi @sunildabburi , unfortunately InfluxDB does not support limiting the `SHOW TAG VALUES` by a time-range.

there is an open github-issue about this here: https://github.com/influxdata/influxdb/issues/5668

there are some workarounds described in the github-issue, they might help with your problem.

i am closing the issue for now, if i misunderstood something, just reply and we can reopen it. thanks!

**Comment by sunildabburi** [comment]
Thank you @gabor appreciate it
