### ISSUE TITLE
Grafana 504 timeout for Loki DataProxy

### ISSUE THREAD

**Issue by borisyukd** [grafana/grafana#38665]
**What happened**:
This is an extension of the https://github.com/grafana/grafana/issues/31638
It looks that I hits one more timeout in Grafana DataProxy. When I create a request that executes during more than 60 seconds it fails with ```error="http: proxy error: context canceled"``` and ```time_ms=59998 size=0```.

Full log:
```
t=2021-08-28T11:09:38+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=2 orgId=1 uname="***" path=/api/datasources/proxy/1/loki/api/v1/query_range remote_addr=*** referer="https://***/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Benvironment%3D%5C%22production%5C%22%7D%20%7C%3D%20%5C%2212312312345%5C%22%22%7D%5D" error="http: proxy error: context canceled"
t=2021-08-28T11:09:38+0000 lvl=eror msg="Request Completed" logger=context userId=2 orgId=1 uname="***" method=GET path=/api/datasources/proxy/1/loki/api/v1/query_range status=502 remote_addr=*** time_ms=59992 size=0 referer="https://***/explore?orgId=1&left=%5B%22now-6h%22,%22now%22,%22Loki%22,%7B%22expr%22:%22%7Benvironment%3D%5C%22production%5C%22%7D%20%7C%3D%20%5C%2212312312345%5C%22%22%7D%5D"
```

![Screenshot (7)](https://user-images.githubusercontent.com/5219872/131215835-6a39f662-d9fe-4825-97ac-becfd464d505.png)
If I copy request URL from Grafan Query Inspector and execute it to the Loki directly (without dataproxy) using curl it returns data successfully.
```
# time curl -k -H 'X-Scope-OrgID: ***' 'http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Benvironment%3D%22production%22%7D%20%7C%3D%20%225432112345%22&start=1630126882112000000&end=1630148482115000000&step=10' 
{"status":"success","data":{"resultType":"streams","result":[],"stats":{"summary":{"bytesProcessedPerSecond":372969034,"linesProcessedPerSecond":658056,"totalBytesProcessed":25001545809,"totalLinesProcessed":44112074,"execTime":67.033837865},"store":{"totalChunksRef":2192,"totalChunksDownloaded":2192,"chunksDownloadTime":2.085474973,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":18766196510,"decompressedLines":33199790,"compressedBytes":1795650388,"totalDuplicates":0},"ingester":{"totalReached":1,"totalChunksMatched":16,"totalBatches":0,"totalLinesSent":0,"headChunkBytes":36793,"headChunkLines":99,"decompressedBytes":6235312506,"decompressedLines":10912185,"compressedBytes":609880203,"totalDuplicates":0}}}}

real	1m7.046s
user	0m0.000s
sys	0m0.010s
```

**What you expected to happen**:
Data should be rendered in Grafana without HTTP 504 error
 
**How to reproduce it (as minimally and precisely as possible)**:
In the same way as in https://github.com/grafana/grafana/issues/31638. Just setup Loki for Grafana and execute long enough request (with duration > 60s) 

**Anything else we need to know?**:
Configuration is almost the same, there are two differences:
- Grafana was updated to 8.1.2
- Loki dataproxy has been configured with timeout 600   

**Environment**:
- Grafana version: ```Version 8.1.2 (commit: 103f8fa094)```
- Data source type & version:
```
# loki version 2.3.0
```
- OS Grafana is installed on:
```
Amazon Linux release 2 (Karoo)
Linux %HOSTNAME% 4.14.232-176.381.amzn2.aarch64 #1 SMP Wed May 19 00:32:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
- User OS & Browser:
```
Brave
Version 1.28.105 Chromium: 92.0.4515.131 (Official Build) (64-bit)

Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.3 LTS
Release:	20.04
Codename:	focal
```
- Grafana plugins: No additional plugins installed

**Comment by philippebn** [comment]
Same bug here with loki.yaml configuration
`querier:
      engine:
        timeout: 5m
      query_timeout: 5m`

**Comment by borisyukd** [comment]
Hi, 
in my case I get 504 even if there is no other proxy between grafana and loki.
I`ve just tested 8.2.0 and got the same result.
On my opinion in order to reproduce you just need grafana (from rpm), loki (from github releases), loki dataset, for instance, 10-20 Gb and common configs with common timeouts. I this case you should get 504 for request with time > 60 sec.

**Comment by adamdecaf** [comment]
I'm seeing this occur on my cluster. Grafana appears to attempt a request, but doesn't retry on a typical `connection refused` error. Looking at [the code for datasource proxying](https://github.com/grafana/grafana/blob/v8.2.5/pkg/api/pluginproxy/ds_proxy.go) there doesn't appear to be an attempt to retry. 

![Screen Shot 2021-11-22 at 9 40 49 AM](https://user-images.githubusercontent.com/120951/142909317-d9f3aa40-2964-421d-b747-24cd3b9c708c.png)

**Comment by aocenas** [comment]
@jessabe I am going to move it to your squad as this may be something in the backend code.

**Comment by papagian** [comment]
@borisyukd  I wonder if you hit a timeout when you try to authenticate to the datasource? can you provide the datasource configuration as well as your [dataproxy settings](https://grafana.com/docs/grafana/latest/administration/configuration/#dataproxy)

@adamdecaf I'm not sure if your case is the same as the above since the error in your case is `connection refused` but I wonder what use cases retrying would resolve? occasional datasource failures?

**Comment by borisyukd** [comment]
Please image and find settings attached.
I tested Grafana 8.4.2 with Loki 2.4.2 and still got timeout after 60 seconds.

### Loki Datasource
![Loki-Settings-Grafana](https://user-images.githubusercontent.com/5219872/156160786-bb3f1624-ee55-471c-b7d3-866636623265.png)

### Grafana Dataproxy
```
#################################### Data proxy ###########################
[dataproxy]

# This enables data proxy logging, default is false
;logging = false

# How long the data proxy waits before timing out, default is 30 seconds.
# This setting also applies to core backend HTTP data sources where query requests use an HTTP client with timeout set.
timeout = 240

# How many seconds the data proxy waits before sending a keepalive probe request.
keep_alive_seconds = 240

# How many seconds the data proxy waits for a successful TLS Handshake before timing out.
;tls_handshake_timeout_seconds = 10

# How many seconds the data proxy will wait for a server's first response headers after
# fully writing the request headers if the request has an "Expect: 100-continue"
# header. A value of 0 will result in the body being sent immediately, without
# waiting for the server to approve.
;expect_continue_timeout_seconds = 1

# The maximum number of idle connections that Grafana will keep alive.
;max_idle_connections = 100

# How many seconds the data proxy keeps an idle connection open before timing out.
idle_conn_timeout_seconds = 300

# If enabled and user is not anonymous, data proxy will add X-Grafana-User header with username into the request, default is false.
;send_user_header = false
```

**Comment by kylebrandt** [comment]
> in my case I get 504 even if there is no other proxy between grafana and loki

To verify, is there any proxy (e.g. nginx, haproxy) between your client and Grafana?

**Comment by borisyukd** [comment]
I tested both cases:
- Direct connection from Grafana to Loki without any proxy
- Connection with Nginx as proxy between Grafana and Loki

Result is that there is no difference for the issue and I got 60s timeout and 504 response from Grafana Data proxy for both cases.

**Comment by borisyukd** [comment]
Loki config has these parameters in `server` block:
```
server:
  http_listen_port: 3100
  http_server_read_timeout: 300s
  http_server_write_timeout: 180s
  http_server_idle_timeout: 300s
```
You may also find [here](https://github.com/grafana/grafana/issues/38665#issue-981809312) that direct request to Loki has no 60s timeout and returns data with HTTP 200. I will copy the same here to make it easier to find:
```
# time curl -k -H 'X-Scope-OrgID: ***' 'http://localhost:3100/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Benvironment%3D%22production%22%7D%20%7C%3D%20%225432112345%22&start=1630126882112000000&end=1630148482115000000&step=10' 
{"status":"success","data":{"resultType":"streams","result":[],"stats":{"summary":{"bytesProcessedPerSecond":372969034,"linesProcessedPerSecond":658056,"totalBytesProcessed":25001545809,"totalLinesProcessed":44112074,"execTime":67.033837865},"store":{"totalChunksRef":2192,"totalChunksDownloaded":2192,"chunksDownloadTime":2.085474973,"headChunkBytes":0,"headChunkLines":0,"decompressedBytes":18766196510,"decompressedLines":33199790,"compressedBytes":1795650388,"totalDuplicates":0},"ingester":{"totalReached":1,"totalChunksMatched":16,"totalBatches":0,"totalLinesSent":0,"headChunkBytes":36793,"headChunkLines":99,"decompressedBytes":6235312506,"decompressedLines":10912185,"compressedBytes":609880203,"totalDuplicates":0}}}}

real	1m7.046s
user	0m0.000s
sys	0m0.010s
```

**Comment by kylebrandt** [comment]
It seems context cancelled means the client side has cancelled the requests and the logs are echoing that, and locally dumping I'm not seeing a deadline on the context.

Few things to try that might help us narrow this down if you can:
 - If you are able to replicate the request to Grafana's dataproxy with curl and get the timeout (e.g. from network tab of chrome inspector, copy as curl). Does it still time out?
 - Also able to show any info from the network tab of chrome inspector?
 - Same behavior in Firefox?

**Comment by borisyukd** [comment]
It looks like behavior is almost the same for each case.
Please find details below.

### Loki direct request using curl
```
$ time curl -kv -H 'X-Scope-OrgID: ***' 'https://username:password@loki.domain/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22api%22%7D%20%7C~%20%22123123123123123%22&start=1646041192635000000&end=1646213992635000000&step=120'
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>

real	3m0,802s
user	0m0,036s
sys	0m0,028s
```

### Grafana Dataproxy direct request using curl
```
time curl  -H 'Cookie: grafana_session=***' 'https://grafana-domain/api/datasources/proxy/1/loki/api/v1/query_range?direction=BACKWARD&limit=1000&query=%7Bservice%3D%22api%22%7D%20%7C~%20%22123123123123123%22&start=1646041192635000000&end=1646213992635000000&step=120'
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
</body>
</html>

real	1m0,368s
user	0m0,040s
sys	0m0,019s
```
### Chrome-based browser (Brave) response
```
Query error
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> </body> </html> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page --> <!-- a padding to disable MSIE and Chrome friendly error page -->
```
![Screenshot Chrome-based](https://user-images.githubusercontent.com/5219872/156350313-4f9dc8e8-a94b-45d7-99cc-ce9d66e95dae.png)


### Firefox response
```
Query error
<html> <head><title>504 Gateway Time-out</title></head> <body> <center><h1>504 Gateway Time-out</h1></center> </body> </html> 
```
![Screenshot Firefox](https://user-images.githubusercontent.com/5219872/156350339-96a16ed3-1b5d-4911-a827-bdd67cd87595.png)

**Comment by kylebrandt** [comment]
I see awselb (AWS elastic load balancer?) Not something I have used (or at least, not in some time), but seems there are timeouts there - e.g. https://aws.amazon.com/premiumsupport/knowledge-center/504-error-classic/ (not sure if classic is the one, or other ones are similar, but that says classic is 60s).

Could that be it?

**Comment by borisyukd** [comment]
It looks like it was my fault.. I thought that ALB `idle timeout` was set to 300s but after you comment I retested curl request to data proxy from local console and from remote one and saw that there is a difference between execution times. After that I changed timeout from 60 to 300 and I see that everything works as it should to.
@kylebrandt Thank you so much. I think the case could be closed for now.

**Comment by kylebrandt** [comment]
Glad we got it solved!

**Comment by LinTechSo** [comment]
Hi same issue here
Loki version 2.6.1
any updates and/or suggestions? 

i increased  timeout settings in loki nginx gateway and loki itself but nothing chaged.

**Comment by rmn-lux** [comment]
maybe helpful: https://community.grafana.com/t/loki-queries-within-grafana-dashboards/71361

**Comment by dtotopus** [comment]
For people still having issues - please check the logs of grafana-loki-querier component. In my case I had ````level=error ts=2023-10-10T19:08:05.095541131Z caller=batch.go:720 org_id=fake msg="error fetching chunks" err="Get \"https://VERYPERSONALBLOB/grafana-loki/fake/sample?timeout=30\": context canceled"````
As we're using azure blob storage - timeout=30 was the default that was ruining all the fun even all other timeouts were increased.
Check the docs under relevant section - in our case https://grafana.com/docs/loki/latest/configure/#azure_storage_config and make sure that you've increased storage backend value as well
