### ISSUE TITLE
Add field from calculation transform bug

### ISSUE THREAD

**Issue by MrMittensTheCat** [grafana/grafana#38673]
**What happened**:
Whenever I have 2 query's in grafana I cannot do any binary operation transform without getting NaN as a result even though in calculation I have selected last non null value. 

As you can see by the attached screenshots, the 2 query's work seperately but when I have both of them I cannot do a calculation using both of them and only a calculation with the 2nd query gives me a result. Using the first query results in Nan even though when I only have the first query it just calculates as it should

**What you expected to happen**:
Just have the 2 numbers add up to: 
5.764.421.259.264

**How to reproduce it (as minimally and precisely as possible)**:
This is pretty difficult as I am using the PRTG plugin for my query's . This however shouldn't be the issue as I have explained above. The numbers **do** work when I don't have both query's.

**Anything else we need to know?**:

I also had this same problem when using InfluxDB getting data from a VCenter server but I have since given up on that because of the NaN issue.

**Environment**:
- Grafana version: Grafana v8.1.0-32440pre (72d296843d)
- Data source type & version: 
Data Sources / PRTG 4.0.4
https://grafana.com/grafana/plugins/jasonlashua-prtg-datasource/
- OS Grafana is installed on:
Docker Container running on Ubuntu 20.04
- User OS & Browser:
Windows 10 & Edge Browser
- Grafana plugins:
PRTG
Worldmap Panel
- Others: /

Calculating between the 2 not working:
![Screenshot_1](https://user-images.githubusercontent.com/25552351/131247661-73d13fad-547d-4420-89b1-eb02c703bc24.png)

Calculating with only the first one:
![Screenshot_2](https://user-images.githubusercontent.com/25552351/131247663-fce68ee7-6f7f-4ceb-be27-b8b64d4c03d3.png)

Calculating with only the second one:
![Screenshot_3](https://user-images.githubusercontent.com/25552351/131247664-be150300-2851-4b8b-9ee0-1ff4b9716668.png)

Calculating the first one with both query's 
![Screenshot_4](https://user-images.githubusercontent.com/25552351/131247665-79829f14-0c7f-4be4-a6dd-884599a6f76f.png)

Calculating the second one with both query's
![Screenshot_5](https://user-images.githubusercontent.com/25552351/131247667-e3635485-80eb-40f4-bdd0-d63f6a5be50a.png)

**Comment by MrMittensTheCat** [comment]
UPDATE: 

After experimenting some more I've found that for some reason the first queried number becomes undefined whenever I load up another one.


(Result is the same if I switch the query's around, the first one becomes undefined)
![Screenshot_6](https://user-images.githubusercontent.com/25552351/131250013-37456c03-e4c9-41b0-8fe7-f65228fdc836.png)

**Comment by hugohaggmark** [comment]
@MrMittensTheCat I've tried with prometheus and the test data source and I can't repro this issue. The PRTG data source you've mentioned is not a built-in Grafana data source so there might be something not working with it. Can you create an issue in their repo instead? Thank you!
