### ISSUE TITLE
Cannot authenticate with LDAP 

### ISSUE THREAD

**Issue by sksegha** [grafana/grafana#3867]
I cannot seem to authenticate with LDAP; i have tried a few steps already but my error logs does not even indicate an attempt by Grafana

My ldap.toml is below 

# Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# Ldap server host
host="159.202.9.218 "
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if ldap server supports TLS
use_ssl = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false

# Search user bind dn
bind_dn = "cn=oolasu1,dc=i,dc=ameriprise,dc=com"
# Search user bind password
bind_password = 'Gladys1985'

# Search filter, for example "(cn=%s)" or "(sAMAccountName=%s)"
search_filter = "(oolasu1=%s)"
# An array of base dns to search through
search_base_dns = ["dc=ameriprise,dc=com,dc=i"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "cn"
surname = "givenName"
username = "oolasu1"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=AP-Storage-NetApp-admins,ou=groups,dc=i,dc=ameriprise,dc=com"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"

but my logs continues to show this when I try to log in, looks like its not even using LDAP at all

# Set to true to log user information returned from LDAP
verbose_logging = true

[[servers]]
# Ldap server host
host="ldapserverhost "
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if ldap server supports TLS
use_ssl = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false

# Search user bind dn
bind_dn = "cn=use,dc=i,dc=mycompany,dc=com"
# Search user bind password
bind_password = 'password'

# Search filter, for example "(cn=%s)" or "(sAMAccountName=%s)"
search_filter = "(userID=%s)"
# An array of base dns to search through
search_base_dns = ["dc=mycompany,dc=com,dc=i"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "cn"
surname = "givenName"
username = "userID"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=AP-Storage-NetApp-admins,ou=groups,dc=i,dc=ameriprise,dc=com"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"

and here is my setting for LDAP 
auth.ldap	
config_file	/etc/grafana/ldap.toml
enabled	true

i cannot seem to find out what the problem is.

**Comment by torkelo** [comment]
I can't either, it should print ldap info in the grafana.log if you have enabled verbose (and any connection error should also be printed no matter if verbose is enabled or not)
