### ISSUE TITLE
Logs navigation: Show more log results clears page

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#38679]
**What happened**:

Trying to get more log entries results in empty page (same as when no results are found).

**What you expected to happen**:

Handle somehow the empty time interval.
At least allow user to go back... showing an empty page forces the user to re-run the search with a new time interval.

**How to reproduce it (as minimally and precisely as possible)**:

1. Search log entries that return more than 500 limit
2. Go to bottom of page and click `Older logs`
3. This page doesn't exceed the 500 limit (important!)
4. Click again `Older logs`
5. Notice empty page, no graph, no results table

**Anything else we need to know?**:

Related to PR #33259 and feature #19354

**Environment**:
- Grafana version:  Grafana v8.1.0 (62e720c)
- Data source type & version: Elasticsearch 7.10.1
- OS Grafana is installed on: docker
- User OS & Browser: Win10 & Firefox
- Grafana plugins: default
- Others:

**Comment by ivanahuckova** [comment]
@cdalexndr I have tried to reproduce the issue, but wasn't able to. Is there a chance that there are no more logs? Could you please send us the network tab request & response from when you click on Older logs.

https://user-images.githubusercontent.com/30407135/133236066-b4577e75-4d4c-4250-b6bd-cbfc895f8f71.mov

**Comment by cdalexndr** [comment]
Sorry, I miss specifying the datasource type. Updated first post. 
Have you tried with elasticsearch datasource? Maybe it's specific to ES.
