### ISSUE TITLE
Geomap + Flux: Marker Color based on thresholds not working

### ISSUE THREAD

**Issue by schamock** [grafana/grafana#38676]
**What happened**:
I'm trying to use Geomap as replacement for the World map plugin (as suggested in #30290).
The Geomap works fine when I'm setting the Marker Color to "Fixed Color", but I get the following error when I'm setting it to the "Hits" value: "undefined is not an object (evaluating 'n.value')"
My result table consists of two columns: "Country" with a two letter country code and "Hits" with the number of matching hits. (see Flux code below)

**What you expected to happen**:
Assumption was, that changing the Marker Color to "Hits" would lead to a Marker Color based on the configured Thresholds.

**How to reproduce it (as minimally and precisely as possible)**:
Fluxcode:

```
from(bucket: "pfsense")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => (r._measurement == "ip_block_log" and r._field == "action"))
  |> filter(fn: (r) => (r.Dir == "out"), onEmpty: "keep")
  |> group(columns: ["GeoIP"], mode: "by")
  |> count()
  |> map(fn: (r) => ({ Country: r.GeoIP, Hits: r._value }))
```
Data Layer Settings: Markers
├ Location: Lookup
├ Lookup Field = Country
├ Gazetteer = Countries
├ Marker Color = Hits (causes the described error)
└ Marker Size = Hits

**Anything else we need to know?**:
Not sure, what else could be helpful. Please ask, if information is missing.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: InfluxDB v2
- OS Grafana is installed on: Debian Bullseye
- User OS & Browser: not relevant
- Grafana plugins: none
- Others:

**Comment by ryantxu** [comment]
What does your data look like in the table view?  

From your description, the size is using hits OK, but fails with color?

Are you able to paste the JSON response you see in the network tab?

**Comment by schamock** [comment]
Exactly, "Hits" works for the size but not for the color.
I'm not exactly sure, which JSON you mean. I attached the three I found in the Query inspector. I also attached the CSV I get directly from InfluxDB for the very same request.
Is that the information you were asking for?

[2021-08-30-20-57_influxdb_data.csv](https://github.com/grafana/grafana/files/7078953/2021-08-30-20-57_influxdb_data.csv)
[jsons.zip](https://github.com/grafana/grafana/files/7078958/jsons.zip)

**Comment by ryantxu** [comment]
I see -- the issue is triggered when there is only one threshold value.

This works:
![image](https://user-images.githubusercontent.com/705951/131418337-e7f7ce90-3f95-4e56-8ce5-a7490544b725.png)

But when the additional theshold is removed, it fails:
![image](https://user-images.githubusercontent.com/705951/131418392-0eadc5ef-d82f-4536-a79f-3b096d827e95.png)

Error here:
![image](https://user-images.githubusercontent.com/705951/131418482-de468a66-3408-4247-8366-ed2f4146d585.png)

**Comment by schamock** [comment]
@ryantxu Thanks for the analysis! I was absolutely sure, that I had multiple threshold values and just removed them while trying to find the problem... But great to see that a fix for stupid people like me is on the way ;)
Thank you for your great work!
