### ISSUE TITLE
Invalid logs table date tooltip

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#38682]
**What happened**:

Hovering over a bar in the logs table shows invalid date:
![image](https://user-images.githubusercontent.com/22418250/131268394-e6fe9aa2-1155-4013-8c5a-dccc1aca77a8.png)
![image](https://user-images.githubusercontent.com/22418250/131268404-66c52dab-a26b-436d-984f-36e32ff7b7bf.png)

The dates are inverted, but the count is good.

**What you expected to happen**:

Correct tooltip date.

**How to reproduce it (as minimally and precisely as possible)**:

Search some data that aggregates into two table points.
Notice invalid tooltip data.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Grafana v8.1.0 (62e720c)
- Data source type & version: 7.10.1
- OS Grafana is installed on: docker
- User OS & Browser: Win10 & Firefox 90.0
- Grafana plugins: default
- Others:

**Comment by ivanahuckova** [comment]
This should be resolved by https://github.com/grafana/grafana/pull/37615 which is part of 8.1.1 release
