### ISSUE TITLE
E2E addDashboard flow should support query variables with custom code editors

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#38683]
**What happened**:
I was writing e2e tests for an external component with uses the same code editor for query template variables as it does for a regular query and I wanted to confirm that adding a template variable worked, but the e2e tests flow for template variables is currently written in such a way that it only checks for the default code editor and not any code editor. 

**What you expected to happen**:
I expect to be able to test my datasource plugin's ability to add and use template variables

**How to reproduce it (as minimally and precisely as possible)**:
To use the same code editor for your template variables extend DataSourceVariableSupport

**Environment**:
- Grafana version: 8.1.2

**Comment by hugohaggmark** [comment]
Friendly reminder to add `labels` to new issues so people on issue triage have less work. Thank you!
