### ISSUE TITLE
Logs navigation: Pagination skips entries

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#38681]
**What happened**:

Trying to get `Older logs` skips entries.
The initial page contains entries from `21:52:58` newest entry to  `21:20:30` oldest entry (position 500), but the page time is incorrectly computed to `21:19:22` oldest entry. 
(Don't know if it's relevant, but I have duplicate entries on `21:20:30`)

Thus, when retrieving an older page, the page starts from `21:19:22` skipping results. I have multiple entries on `21:20:13` that are skipped.
![image](https://user-images.githubusercontent.com/22418250/131267647-e99e40b1-c5f3-40af-a428-a85c9a35901d.png)
![image](https://user-images.githubusercontent.com/22418250/131267702-07b151d2-5d83-4924-aff7-08bd0b64a0f5.png)

Also notice that in the second page, the first entry has time `21:19:06` but the page is displayed incorrectly to be from `21:19:22`.

**What you expected to happen**:

Normal pagination.

**How to reproduce it (as minimally and precisely as possible)**:

1. Search log entries returining more than the 500 limit
2. Bottom of page, click `Older logs` and notice results are skipped

**Anything else we need to know?**:

Related to PR #33259 and feature #19354

**Environment**:
- Grafana version:  Grafana v8.1.0 (62e720c)
- Data source type & version: Elasticsearch 7.10.1
- OS Grafana is installed on: docker
- User OS & Browser: Win10 & Firefox
- Grafana plugins: default
- Others:

**Comment by cdalexndr** [comment]
Here are some `_msearch` request data for debugging:

First page `02.04:44 - 21:17:11`:
Request:
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"log-*"}
{"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1630256684072,"lte":1630278284072,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"level:ERROR"}}]}},"sort":[{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},{"_doc":{"order":"desc"}}],"script_fields":{},"aggs":{"1":{"date_histogram":{"interval":"20s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":1630256684072,"max":1630278284072},"format":"epoch_millis"},"aggs":{}}},"highlight":{"fields":{"*":{}},"pre_tags":["@HIGHLIGHT@"],"post_tags":["@/HIGHLIGHT@"],"fragment_size":2147483647}}
```
Response:
[Response1.txt](https://github.com/grafana/grafana/files/7073356/Response1.txt)

Second page `21:17:11 - 17:41:03`:
Request:
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"log-*"}
{"size":500,"query":{"bool":{"filter":[{"range":{"@timestamp":{"gte":1630239431940,"lte":1630261031940,"format":"epoch_millis"}}},{"query_string":{"analyze_wildcard":true,"query":"level:ERROR"}}]}},"sort":[{"@timestamp":{"order":"desc","unmapped_type":"boolean"}},{"_doc":{"order":"desc"}}],"script_fields":{},"aggs":{"1":{"date_histogram":{"interval":"20s","field":"@timestamp","min_doc_count":0,"extended_bounds":{"min":1630239431940,"max":1630261031940},"format":"epoch_millis"},"aggs":{}}},"highlight":{"fields":{"*":{}},"pre_tags":["@HIGHLIGHT@"],"post_tags":["@/HIGHLIGHT@"],"fragment_size":2147483647}}
```
Response:
[Response2.txt](https://github.com/grafana/grafana/files/7073358/Response2.txt)

**Comment by ifrost** [comment]
I was able to reproduce it locally. I think the problem stems from using `visibleRange.from` [here](https://github.com/grafana/grafana/blob/main/public/app/features/explore/LogsNavigation.tsx#L115) (calculated by [getSeriesProperties](https://github.com/grafana/grafana/blob/main/public/app/core/logs_model.ts#L271)), not the timestamp of the oldest log entry in the page.
