### ISSUE TITLE
Logs navigation: Older logs not working when flipped results order

### ISSUE THREAD

**Issue by cdalexndr** [grafana/grafana#38680]
**What happened**:

Pressing `Older logs` button cycles between two datasets instead of retrieving actual older logs.

**What you expected to happen**:

Show older logs

**How to reproduce it (as minimally and precisely as possible)**:

1. Search some log entries that exceed the 500 limit
2. Press `Flip results order`
3. Press `Older logs` to load another page
4. Again press `Older logs` and notice the newer page is displayed instead of loading the older ones
5. More clicking `Older logs` cycles between the two pages

**Anything else we need to know?**:

Related to PR #33259 and feature #19354

**Environment**:
- Grafana version:  Grafana v8.1.0 (62e720c)
- Data source type & version: Elasticsearch 7.10.1
- OS Grafana is installed on: docker
- User OS & Browser: Win10 & Firefox
- Grafana plugins: default
- Others:

**Comment by ivanahuckova** [comment]
@cdalexndr thank you for creating issue. I was able to reproduce the bug.
