### ISSUE TITLE
Chore: remove classnames package from the repo

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#38698]
**What happened**:

The [classnames](https://github.com/JedWatson/classnames) library is not necessary as emotion/css has a similar function called [cx](https://github.com/emotion-js/emotion/tree/main/packages/css#cx). For consistency we should refactor our codebase to only use emotion's classname implementation.

Tasks:
- [ ] Check performance when using the classNames library vs using the cx function from emotion
- [ ] Remove classnames dependencies (types/classnames, classnames)
- [ ] Use cx from emotion instead of classnames where needed

**Comment by MukulKolpe** [comment]
Hey @zoltanbedi, can I work on this issue??

**Comment by zoltanbedi** [comment]
> Hey @zoltanbedi, can I work on this issue??

Sure, go ahead.

**Comment by VedanthB** [comment]
I would like to do this, could you guide me on hoe i should proceed ? it would be my first open source contribution!

**Comment by zoltanbedi** [comment]
Hi all,
Before we start doing anything we should measure performance impact by using the classnames library and then using the emotion js cx function. If it is not that big we should move forward with this.

**Comment by glintik** [comment]
@zoltanbedi Added test for classnames and cx:
```
>npx jest --verbose public/app/classnamesToCxMigration.test.tsx
 PASS  public/app/classnamesToCxMigration.test.tsx (9.614 s)
  Performance of classnames
    ✓ 2 strings (173 ms)
    ✓ object (356 ms)
    ✓ string + object (395 ms)
    ✓ string + object + string (433 ms)
    ✓ 5 strings (277 ms)
  Performance of cx
    ✓ 2 strings (825 ms)
    ✓ object (1114 ms)
    ✓ string + object (1331 ms)
    ✓ string + object + string (1525 ms)
    ✓ 5 strings (1347 ms)
```

Looks like cx has some performance issues.
Tested on macOs Mojave 10.14.6 (18G6042), 2,3 GHz Intel Core i7, nodejs v14.17.6.

**Comment by zoltanbedi** [comment]
This is awesome! Thank you so much @glintik. 🎉

**Comment by glintik** [comment]
Cool :).
What did you decide - proceed to the next step "Remove classnames dependencies" or cancel classnames removal?

**Comment by zoltanbedi** [comment]
So we decided to not to do anything about this. Thanks for helping us with checking this out.
