### ISSUE TITLE
Links in annotations are not clickable

### ISSUE THREAD

**Issue by Andrei-Rudenka** [grafana/grafana#38695]
In time series graphs links in annotations are not clickable.
![image](https://user-images.githubusercontent.com/89780743/131331211-e273e0f4-9932-468c-bdeb-65962dcc7504.png)

If we switch to graph(old) links in annotation becomes clickable
![image](https://user-images.githubusercontent.com/89780743/131331269-70159420-d040-4fa0-be7e-72d0ce469235.png)

**Comment by mckn** [comment]
@Andrei-Rudenka I did try this locally and for me the link is clickable but missing the proper styling. Are you experiencing it the same way?

**Comment by Andrei-Rudenka** [comment]
> @Andrei-Rudenka I did try this locally and for me the link is clickable but missing the proper styling. Are you experiencing it the same way? So basically the issue is that the link is missing the link styling, in that case.

I look at console. Link exists, but without styling. The main problem is that annotation frame hides on hover and I cannot click =)

**Comment by Andrei-Rudenka** [comment]
If it is useful 
Grafana v8.0.6 (68fe9e3431)
InfluxDB

**Comment by mckn** [comment]
Super, thanks for confirming. But regardless, something that needs to be fixed.
