### ISSUE TITLE
access is forbidden to plugin file

### ISSUE THREAD

**Issue by jaqb76** [grafana/grafana#38690]
**Environment**:
- Grafana version:8.1.2
- Plugin: agenty-flowcharting-panel

Empty panel with plugin flow-chart.

In log:
lvl=eror msg="Plugin file access forbidden" logger=context userId=1 orgId=2 uname=admin error="access is forbidden to plugin file /var/lib/grafana/plugins/agenty-flowcharting-panel/static/defaultGraph.csv"

In change #37688 I think missing csv extension.

**Comment by wbrowne** [comment]
Thanks for flagging @jaqb76 - we have a duplicate issue here https://github.com/grafana/grafana/issues/38570. I'll close this in order to consolidate
