### ISSUE TITLE
CodeEditor using javascript/typescript causes an error in the console

### ISSUE THREAD

**Issue by ZuperZee** [grafana/grafana#38700]
Currently the monaco editor integrated into Grafana has removed typescript types.<https://github.com/grafana/grafana/blob/bafe16368ae945f4627e445280a63f53e2cfcf7a/scripts/webpack/webpack.common.js#L85-L88> Which makes it hard to use types.
![image](https://user-images.githubusercontent.com/39485579/130408305-ed349ead-2cca-4f7e-835f-0afd06a64f2b.png)

_Originally posted by @ZuperZee in https://github.com/grafana/grafana/discussions/38430_

**Comment by ZuperZee** [comment]
This also makes script tags in the text panel show types like window and such.
Currently the same error comes in the text panel when using <script></script>.

**Comment by mckn** [comment]
@joshhunt do you know what the thoughts where regarding the changes made to the editor?

**Comment by dprokop** [comment]
@ZuperZee why do you need explicit ts syntax support in Grafana?

**Comment by ZuperZee** [comment]
The main reason why I need it is because I've developed a plugin and wanted to move to the integrated CodeEditor instead of my own implementation of Monaco.

When there were two Monaco loader configurations the last config would be loaded and because Grafana's implementation uses kusto it would be hard to implement it so both config would work together.

Without the ts syntax the browser console gets an error when the language is set to javascript which can be confusing to users. The types are handy since it gives autocompletion and such.

**Comment by ZuperZee** [comment]
![image](https://user-images.githubusercontent.com/39485579/131465616-136791be-6e7f-4edc-8968-8b3e6a484b72.png)

**Comment by ZuperZee** [comment]
> @joshhunt do you know what the thoughts where regarding the changes made to the editor?

The TS part is a little big (~4MB) and was most likely removed to save some space.
![image](https://user-images.githubusercontent.com/39485579/131466517-c4ff74ed-2fad-4cb9-9296-580bd937dd78.png)
Link to the conversation where this was added <https://github.com/grafana/grafana/pull/33204/files#r619058827> (The link will probably not jump to the conversation. Try pressing the link below instead.)
The line where this was added <https://github.com/grafana/grafana/pull/33204/files#diff-80463b1c065d6048b7ea4efcfd4e2ff8f79ef503f461348e57f497496c751f1eR86>
