### ISSUE TITLE
Alerting with OpenTSDB, graph data not sorted by time

### ISSUE THREAD

**Issue by NikolaBorisov** [grafana/grafana#38729]
**What happened**:
Data from query on the Create Alert Rule page is not displayed properly. It looks like the data is not sorted and the graph looks terrible.

**What you expected to happen**:
I expected the graph displayed on the Create alert rule page to look exactly like the panel for which I'm trying to create the alert.

**How to reproduce it (as minimally and precisely as possible)**:
Try to create an alert on a OpenTSDB graph panel. Click "Run queries" and look at the data in Time series format and also table format.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: OpenTSDB 2.4
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu / Firefox
- Grafana plugins:
- Others:

![not_sorted](https://user-images.githubusercontent.com/184322/131395122-94a12cd7-9f1c-45da-bdee-a810f6bd9dfb.png)
![not_sorted2](https://user-images.githubusercontent.com/184322/131395123-5167d8ea-4db9-439d-bc92-63137092bea8.png)

**Comment by wbrowne** [comment]
I believe I'm seeing something similar

![Screenshot 2021-08-31 at 19 21 45](https://user-images.githubusercontent.com/1173299/131547919-b3f0f965-b546-4829-98a7-d8c5d648c057.png)
![Screenshot 2021-08-31 at 19 21 55](https://user-images.githubusercontent.com/1173299/131547926-d5e71381-1aff-4458-a85c-84986b6ad053.png)

**Comment by kylebrandt** [comment]
It looks like on the backend for OpenTSDB, it looks like the response object is a map. Since server side expressions go through the backend, we do not get sorted data.

IIRC, opentsdb has an option that is (asArray) or something like this, so the request should specify that, and then we would get ordered data back.

**Comment by peterholmberg** [comment]
@kylebrandt this sounds like a change to the opentsdb plugin then? Would it change anything for paneledit/explore if we enabled arrays?

**Comment by kylebrandt** [comment]
@peterholmberg No, this change would entirely be on the backend side and within the OpenTSDB datasource.

**Comment by wbrowne** [comment]
Then this is most likely related to changes here I imagine https://github.com/grafana/grafana/pull/35815

**Comment by kylebrandt** [comment]
@wbrowne The following needs to change to not be a map for Datapoints:

https://github.com/grafana/grafana/blob/7e6cf14c84fd3bbd1ba709ecb772ff7e3afd4d6a/pkg/tsdb/opentsdb/types.go#L9-L12

And then however you specify that serializer option in my link above would also need to be set so the response marshals into it.

**Comment by NikolaBorisov** [comment]
Hello All, 

Is there any chance to fix this? Basically the new alerting does not work for people using OpenTSDB...

**Comment by wbrowne** [comment]
CC @grafana/observability-squad just in case this one is lost

**Comment by NikolaBorisov** [comment]
Any change someone can look at this one.

Because of this we can not use grafana alerts with OpenTSDB

**Comment by ivanahuckova** [comment]
+cc @grafana/observability-metrics

**Comment by joey-grafana** [comment]
Hey OpenTSDB is owned by the metrics squad, not the traces and profiling squad :) I'm re-assigning someone from the metrics squad!

**Comment by aangelisc** [comment]
This should be fixed by #90991
