### ISSUE TITLE
 Feature request: Multiple Marker Shapes in one Geomap

### ISSUE THREAD

**Issue by asayeedi** [grafana/grafana#38739]
I'd love the possibility to have the multiple markers like Circle and Square in same Geomap.
Suppose I have a Device Type A and Type B and I want to show Device Type A in Geomap with Circle and Device Type B with Square. It becomes very convenient to Identify the types without hovering over each markers.

**Comment by mckn** [comment]
Closing this one since the following discussion already exists: https://github.com/grafana/grafana/discussions/38740
