### ISSUE TITLE
logs panel throws error with cloudwatch datasource after upgrading from v7.4.3 to v8.1.2

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#38743]
**What happened**:
logs panel throws "Cannot read property 'meta' of undefined" after upgrading grafana from v7.4.3 to v8.1.2 while using cloudwatch logs query
**What you expected to happen**:
the panel should work as expected
**How to reproduce it (as minimally and precisely as possible)**:
create logs panel in grafana  v7.4.3  with cloudwatch logs query, upgrade grafana to  v8.1.2
**Anything else we need to know?**:

stack trace of the error in chrome console:
runRequest.catchError TypeError: Cannot read property 'meta' of undefined
    at t.project (datasource.ts:192)
    at t._tryNext (mergeMap.js:59)
    at t._next (mergeMap.js:49)
    at t.next (Subscriber.js:53)
    at t._next (map.js:41)
    at t.next (Subscriber.js:53)
    at t._next (throwIfEmpty.js:32)
    at t.next (Subscriber.js:53)
    at t._next (Subscriber.js:76)
    at t.next (Subscriber.js:53)

**Environment**:
- Grafana version: v8.1.2
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Debian 9
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

Please let me know if any other details required

**Comment by aocenas** [comment]
Was looking into this but cannot reproduce it. Looking at the code where it originated some data seems to be missing but I am not seeing how that could happen as that data is generated inside Grafana.

Can you tell me if this is some transient issue? For example is it happening only for panels which were created in previous version and new panels work fine?
Can you send what the query looks like (removing anything sensitive data)?

**Comment by vbichov** [comment]
could reproduce both in the new pannel and upgraded one.

dug a little deeper - it seems that the issue is somehow related to the query name
<img width="281" alt="Screen Shot 2021-09-22 at 12 25 18" src="https://user-images.githubusercontent.com/4352719/134318487-3a132fa4-387a-43ed-a95c-40aee7aea334.png">


Anything other than `A` triggers an error

but changing to `A` still doesn't solve the issue - now I get a spinning wheel with no data :(

**Comment by vbichov** [comment]
ok - issue seems to be solved in 8.1.5 - closing
