### ISSUE TITLE
Anyone Can Edit Panel JSON.

### ISSUE THREAD

**Issue by deckw** [grafana/grafana#3874]
It appears that non-admin users can edit and update the JSON panel.  

Steps to Recreate:
1. Create a panel
2. login as non-admin user
3. Try to edit panel through JSON
4. ???
5. Profit

**Comment by torkelo** [comment]
Thanks for reporting this, should be hidden for viewers. 

Just a side not that the Viewer role is not for metric security, anyone with viewer access can view panel json and if the user is knowledgeable in http query for any metric.

**Comment by utkarshcmu** [comment]
So, whats the required functionality? The small panel menu containing "Panel JSON, Export CSV, Toggle Legend" should completely be hidden from the viewer? OR just the "Update" button on "Panel JSON" should be disabled/hidden?

**Comment by deckw** [comment]
I think the "Update" button should be disabled/hidden

**Comment by Payden-Pringle** [comment]
I have found that this issue is still occurring in version 5.4.3 (commit: 6539180).

I created a Dashboard and a Panel within it then a dummy user who only has the Viewer role within the organization and for the Dashboard.

The user can see the Panel JSON button and edit the JSON then click Update.

This causes the edited Query to be ran. @torkelo

**Comment by alchuk** [comment]
Dear Torkel,
Can you please explain why is the viewer allowed to view panel JSON code? In my practice I'm forced to give access to external users and as a part of security considerations I won't give them r/w rights. The viewer can discover my backend database structure as well as internal device and interface names which are used in queries. I can't imagine why would viewer need to know the JSON structure of a panel.

**Comment by marefr** [comment]
@alchuk https://grafana.com/docs/grafana/latest/installation/security/#viewer-query-permissions
