### ISSUE TITLE
Consider supporting multple series sanely in singlestat panel

### ISSUE THREAD

**Issue by t-pascal** [grafana/grafana#3875]
This problem results from a multiple series reply from OpentTSDB. It is possible that it is OpenTSDB specific, but solving it more generally might be a better approach. The use case is allowing a dashboard using templates that supports the "all" variable (which causes OpenTSDB to respond with multiple series).

In my case, I want to use a singlestat panel with templates. This works great as long as I don't include the "all" variable. With OpenTSDB, the "all" template is translated to *. Using * results in multiple series being returned.

For example:

```
metric = proc.cpu
tags: environment = prod
```
Returns a series:

`proc.cpu = [1, 2, 3, 4,...]`

But with 'all' specified in the template

```
metric = proc.cpu
tags: environment = *
```
Returns multiple series:

```
proc.cpu = [
  [1,2,3,4,...], (prod)
  [5,6,7,8,...], (dev)
  [9,10,11,12,...] (qa)
]
```
I propose that certain operations are realistically reasonable for multiple series. Obviously average() is meaningless. But surely max(), min(), count(), sum() would work.

So I think that it would be great to add a checkbox in the singlestat panel (perhaps in the Options tab) to allow "multiple series" and if this box is checked to allow certain operations in a drop down that allows sound "multiseries safe" operations. Possibly this alters the already existing dropdown box for the "Big Value" operator (max, min, sum...):

```
min([series1],[series2],...) = min(min([series1]),min([series2,])...)
max([series1],[series2],...) = max(max([series1]),max([series2,])...)
sum([series1],[series2],...) = sum(sum([series1]),sum([series2,])...)
count([series1],[series2],...) = sum(count([series1]),count([series2,])...)
```
(and others, mimmax, mimmin, zimsum)

Assuming this is a good solution, we would also need to document the changes in http://docs.grafana.org/reference/singlestat/

Another option that is OpenTSDB specific is to alter any queries that have tags with "all" or * so that OpenTSDB returns (hopefully) a single specific series. This option might be good for any other data sources with a similar metric result using globs like '*' or "all". That is:

```
metric = proc.cpu
tags: environment = *, type = system
```
is mutated to:

```
metric = proc.cpu
tags: type = system
```

This seems like a worse solution to "magically" fix the problem rather than surface it to the user and allow them to choose how the multi-series data are handled expl

**Comment by torkelo** [comment]
most other time series databases support merging time series so this is a feature that has be be implemented in OpenTSDB. 

It will be implemented in a generic way in the future, https://github.com/grafana/grafana/issues/3677
