### ISSUE TITLE
Timeshift is buggy

### ISSUE THREAD

**Issue by go-online** [grafana/grafana#3876]
Since the migration to Grafana 2.x it seems the timeshift isn't working properly.
When trying anything up to '7d' (exclude) - it works, but when apply timeshift(7d) - the graph is disappearing.
The strange thing, is that I DO have these metrics up to 30 days.

**How do I know?**
Because when looking at a time frame of 30 days, with metrics set to timeshift(6d) - it works and show graphs to ~30 days back. But when just move it to '7d' - it makes it disappear completely.

**My storage-schema file is:**

```
[statsd]
priority = 110
pattern = ^stats.*
retentions = 10s:1d,60s:30d,300s:30d
```

**Any idea??**

Thanks!

**Comment by torkelo** [comment]
are you stacking multiple series? Enable points drawing (in display styles tab) to check if there are any points. Also you can open chrome dev tools and check the response from graphite (check network tab and graphites response from the render call), is graphite returning data? If not it's an issue in graphite.

**Comment by go-online** [comment]
Thank @torkelo 
Well I DO have datapoints for at least 30 days back. See image below.

![image](https://cloud.githubusercontent.com/assets/6809159/12977060/0c987d5e-d0d1-11e5-99b8-c846951c4c6f.png)

For some reason tough when I choose only 7 days back - all datapoints "disappear" - and the server response includes aonly NULLs... Here's an example of 7 days timeframe request:

[{"target": "wups 7d", "datapoints": [[null, 1454593020], [null, 1454594760], [null, 1454596500], [null, 1454598240], [null, 1454599980], [null, 1454601720], [null, 1454603460], [null, 1454605200], [null, 1454606940], [null, 1454608680], [null, 1454610420], [null, 1454612160], [null, 1454613900], [null, 1454615640], [null, 1454617380], [null, 1454619120], [null, 1454620860], [null, 1454622600], [null, 1454624340], [null, 1454626080], [null, 1454627820], [null, 1454629560], [null, 1454631300], [null, 1454633040], [null, 1454634780], [null, 1454636520], [null, 1454638260], [null, 1454640000], [null, 1454641740], [null, 1454643480], [null, 1454645220], [null, 1454646960], [null, 1454648700], [null, 1454650440], [null, 1454652180], [null, 1454653920], [null, 1454655660], [null, 1454657400], [null, 1454659140], [null, 1454660880], [null, 1454662620], [null, 1454664360], [null, 1454666100], [null, 1454667840], [null, 1454669580], [null, 1454671320], [null, 1454673060], [null, 1454674800], [null, 1454676540], [null, 1454678280], [null, 1454680020], [null, 1454681760], [null, 1454683500], [null, 1454685240], [null, 1454686980], [null, 1454688720], [null, 1454690460], [null, 1454692200], [null, 1454693940], [null, 1454695680], [null, 1454697420], [null, 1454699160], [null, 1454700900], [null, 1454702640], [null, 1454704380], [null, 1454706120], [null, 1454707860], [null, 1454709600], [null, 1454711340], [null, 1454713080], [null, 1454714820], [null, 1454716560], [null, 1454718300], [null, 1454720040], [null, 1454721780], [null, 1454723520], [null, 1454725260], [null, 1454727000], [null, 1454728740], [null, 1454730480], [null, 1454732220], [null, 1454733960], [null, 1454735700], [null, 1454737440], [null, 1454739180], [null, 1454740920], [null, 1454742660], [null, 1454744400], [null, 1454746140], [null, 1454747880], [null, 1454749620], [null, 1454751360], [null, 1454753100], [null, 1454754840], [null, 1454756580], [null, 1454758320], [null, 1454760060], [null, 1454761800], [null, 1454763540], [null, 1454765280], [null, 1454767020], [null, 1454768760], [null, 1454770500], [null, 1454772240], [null, 1454773980], [null, 1454775720], [null, 1454777460], [null, 1454779200], [null, 1454780940], [null, 1454782680], [null, 1454784420], [null, 1454786160], [null, 1454787900], [null, 1454789640], [null, 1454791380], [null, 1454793120], [null, 1454794860], [null, 1454796600], [null, 1454798340], [null, 1454800080], [null, 1454801820], [null, 1454803560], [null, 1454805300], [null, 1454807040], [null, 1454808780], [null, 1454810520], [null, 1454812260], [null, 1454814000], [null, 1454815740], [null, 1454817480], [null, 1454819220], [null, 1454820960], [null, 1454822700], [null, 1454824440], [null, 1454826180], [null, 1454827920], [107.56761904761905, 1454829660], [null, 1454831400], [null, 1454833140], [null, 1454834880], [null, 1454836620], [null, 1454838360], [null, 1454840100], [null, 1454841840], [null, 1454843580], [null, 1454845320], [null, 1454847060], [null, 1454848800], [null, 1454850540], [null, 1454852280], [null, 1454854020], [null, 1454855760], [null, 1454857500], [null, 1454859240], [null, 1454860980], [null, 1454862720], [null, 1454864460], [null, 1454866200], [null, 1454867940], [null, 1454869680], [null, 1454871420], [null, 1454873160], [null, 1454874900], [null, 1454876640], [null, 1454878380], [null, 1454880120], [null, 1454881860], [null, 1454883600], [null, 1454885340], [null, 1454887080], [null, 1454888820], [null, 1454890560], [null, 1454892300], [null, 1454894040], [null, 1454895780], [null, 1454897520], [null, 1454899260], [null, 1454901000], [null, 1454902740], [null, 1454904480], [null, 1454906220], [null, 1454907960], [null, 1454909700], [null, 1454911440], [null, 1454913180], [null, 1454914920], [null, 1454916660], [null, 1454918400], [null, 1454920140], [null, 1454921880], [null, 1454923620], [null, 1454925360], [null, 1454927100], [null, 1454928840], [null, 1454930580], [null, 1454932320], [null, 1454934060], [null, 1454935800], [null, 1454937540], [null, 1454939280], [null, 1454941020], [null, 1454942760], [null, 1454944500], [null, 1454946240], [null, 1454947980], [null, 1454949720], [null, 1454951460], [null, 1454953200], [null, 1454954940], [null, 1454956680], [null, 1454958420], [null, 1454960160], [null, 1454961900], [null, 1454963640], [null, 1454965380], [null, 1454967120], [null, 1454968860], [null, 1454970600], [null, 1454972340], [null, 1454974080], [null, 1454975820], [null, 1454977560], [null, 1454979300], [null, 1454981040], [null, 1454982780], [null, 1454984520], [null, 1454986260], [null, 1454988000], [null, 1454989740], [null, 1454991480], [null, 1454993220], [null, 1454994960], [null, 1454996700], [null, 1454998440], [null, 1455000180], [null, 1455001920], [null, 1455003660], [null, 1455005400], [null, 1455007140], [null, 1455008880], [null, 1455010620], [null, 1455012360], [null, 1455014100], [null, 1455015840], [null, 1455017580], [null, 1455019320], [null, 1455021060], [null, 1455022800], [null, 1455024540], [null, 1455026280], [null, 1455028020], [null, 1455029760], [null, 1455031500], [null, 1455033240], [null, 1455034980], [null, 1455036720], [null, 1455038460], [null, 1455040200], [null, 1455041940], [null, 1455043680], [null, 1455045420], [null, 1455047160], [null, 1455048900], [null, 1455050640], [null, 1455052380], [null, 1455054120], [null, 1455055860], [null, 1455057600], [null, 1455059340], [null, 1455061080], [null, 1455062820], [null, 1455064560], [null, 1455066300], [null, 1455068040], [null, 1455069780], [null, 1455071520], [null, 1455073260], [null, 1455075000], [null, 1455076740], [null, 1455078480], [null, 1455080220], [null, 1455081960], [null, 1455083700], [null, 1455085440], [null, 1455087180], [null, 1455088920], [null, 1455090660], [null, 1455092400], [null, 1455094140], [null, 1455095880], [null, 1455097620], [null, 1455099360], [null, 1455101100], [null, 1455102840], [null, 1455104580], [null, 1455106320], [null, 1455108060], [null, 1455109800], [null, 1455111540], [null, 1455113280], [null, 1455115020], [null, 1455116760], [null, 1455118500], [null, 1455120240], [null, 1455121980], [null, 1455123720], [null, 1455125460], [null, 1455127200], [null, 1455128940], [null, 1455130680], [null, 1455132420], [null, 1455134160], [null, 1455135900], [null, 1455137640], [null, 1455139380], [null, 1455141120], [null, 1455142860], [null, 1455144600], [null, 1455146340], [null, 1455148080], [null, 1455149820], [null, 1455151560], [null, 1455153300], [null, 1455155040], [null, 1455156780], [null, 1455158520], [null, 1455160260], [null, 1455162000], [null, 1455163740], [null, 1455165480], [null, 1455167220], [null, 1455168960], [null, 1455170700], [null, 1455172440], [null, 1455174180], [null, 1455175920], [null, 1455177660], [null, 1455179400], [null, 1455181140], [null, 1455182880], [null, 1455184620], [null, 1455186360], [null, 1455188100], [null, 1455189840], [null, 1455191580], [null, 1455193320], [478.7013333333333, 1455195060]]}]

**How can it be??**

Thanks

**Comment by torkelo** [comment]
not sure, maybe a graphite bug?
