### ISSUE TITLE
Unified Alerting: Notification Policy group by settings are confusing

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#38760]
**What happened**:
The Group by options seems to have created confusion for several users:

![image](https://user-images.githubusercontent.com/1692624/131526552-617929fa-91da-44b9-bb2b-c70f0fb519b8.png)

(e.g. issue https://github.com/grafana/grafana/issues/37618)

As I understand it:
 - When this has an entry of three periods, `...` then there is no grouping of alert instances by labels (although I believe alerting/resolved can still group) (see https://www.prometheus.io/docs/alerting/latest/configuration/#route)
 - When it is empty, I am not sure, but I think it means to group everything together (the come within the time window, regardless of labels) (@gotjosh you know this one?)
 - When labels are present, they are grouped on them (this one is clear enough)

**What you expected to happen**:

I think the empty value there is confusing to users, and the `...` is basically a special secret value when looking at the UI. So I think those two things need to be clarified the UI somehow. 

We should probably also note in the docs which contact points (e.g. opsgenie or ones that do there own grouping) that should have the `...` as there notification policy to work correctly.

**Anything else we need to know?**:

We could also consider changing the default on group by for default policy to be non-grouping. But regardless of the default I think it will help if we expose and clarify the non literal label name options for that field and what they mean.

cc @oanamangiurea

**Comment by yuri-tceretian** [comment]
https://github.com/grafana/grafana/issues/39143 is related to this. I think we can close it. wdyt @kylebrandt?
