### ISSUE TITLE
Alerting: Support storing silences and notification log on the database

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#38794]
Because of the embedded alertmanager, Grafana has moved from being completely stateless to requiring a persisting disk for storing silences and notification log.

I believe there's a path to support writing and reading these in the database that does not require heavy modification to the current operational state.

- [x] Add support in Prometheus/alertmanager for custom functions as part of the maintenance in [silences](https://github.com/prometheus/alertmanager/blob/main/silence/silence.go#L356-L380) and [nflog](https://github.com/prometheus/alertmanager/blob/main/nflog/nflog.go#L193). https://github.com/prometheus/alertmanager/pull/2689
- [x] Add support for writing and reading `[]bytes` to and from the database. These data structures are a protobuf. https://github.com/grafana/grafana/pull/39005
- [x] Implement the custom functions that write and read the state to/from the database https://github.com/grafana/grafana/pull/39005
- [x] ~~Add a flag to Grafana for enabling the usage of this new operational mode~~ went for fallback mode https://github.com/grafana/grafana/pull/39005
- [x] Update documentation to indicate that there's an option that does not require Grafana to be run as a stateful workload. https://github.com/grafana/grafana/pull/39005

**Comment by mckn** [comment]
Hehe, no worries :) I do the same thing.
