### ISSUE TITLE
Alerting: alerts deduplication not working when ngalert enabled

### ISSUE THREAD

**Issue by newstead** [grafana/grafana#38795]
Hello!

I'm running 2 separate Grafana instances with single PostgreSQL database and receiving duplicate alerts in Slack
So there is an issue in internal alertmanager near alerts deduplication
AFAIK this is known issue, but there is no public report for this (cc: @davidmparrott )

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Prometheus/v2

**Comment by malejpavouk** [comment]
https://github.com/grafana/grafana/issues/35083#event-5201704498
^^ It was already reported in this thread, there is even some work on the HA setup using gossip between the nodes (but not finished).

The root cause is that the alerts are currently stored on local disk and not in the database.
