### ISSUE TITLE
Singlestat panels are gone in existing dashboards

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#3879]
Singlestat panels are not appearing on existing dashboards, and also leave an empty space I cannot get rid of.  Using nightly from 2016/01/28

**Comment by daniellee** [comment]
Could you post the dashboard json?

**Comment by vitorboschi** [comment]
{
  "id": 7,
  "title": "Status SLT",
  "originalTitle": "Status SLT",
  "tags": [
    "Item 3"
  ],
  "style": "dark",
  "timezone": "browser",
  "editable": true,
  "hideControls": false,
  "sharedCrosshair": true,
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "200px",
      "panels": [
        {
          "aliasColors": {
            "Fila de envio": "#BF1B00",
            "Transações": "#DEDAF7"
          },
          "bars": true,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 3,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": false,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Fila de envio",
              "bars": false,
              "lines": true,
              "linewidth": 2,
              "yaxis": 2
            }
          ],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "Transações",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "sum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.tag_transactions",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina"
              }
            },
            {
              "aggregator": "avg",
              "alias": "Fila de envio",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.queueSize",
              "refId": "B",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Transações / $timespan",
          "tooltip": {
            "shared": false,
            "value_type": "cumulative"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "short",
            "short"
          ]
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "rgba(50, 172, 45, 0.97)",
            "rgba(255, 0, 0, 0.89)",
            "rgba(245, 54, 54, 0.9)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 10,
          "interval": null,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "span": 1,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "aggregator": "max",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "max",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "ping.timeout",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "dst_host": "ocr.$maquina",
                "host": "$maquina"
              }
            }
          ],
          "thresholds": "0,1",
          "title": "OCR ($timespan)",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "Offline",
              "value": "1"
            },
            {
              "op": "=",
              "text": "Online",
              "value": "0"
            }
          ],
          "valueName": "current"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "rgba(50, 172, 45, 0.97)",
            "rgba(255, 0, 0, 0.89)",
            "rgba(245, 54, 54, 0.9)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 11,
          "interval": null,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "span": 1,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "aggregator": "max",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "max",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "ping.timeout",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "dst_host": "contexto.$maquina",
                "host": "$maquina"
              }
            }
          ],
          "thresholds": "0,1",
          "title": "Contexto ($timespan)",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "Offline",
              "value": "1"
            },
            {
              "op": "=",
              "text": "Online",
              "value": "0"
            }
          ],
          "valueName": "current"
        }
      ],
      "showTitle": true,
      "title": "SLT"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": 1,
            "leftMin": 0,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 12,
          "leftYAxisLabel": "",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "$tag_dst_host",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {},
              "metric": "ping.timeout",
              "refId": "A",
              "tags": {
                "dst_host": "*",
                "host": "$maquina"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Downtime estimado",
          "tooltip": {
            "shared": true,
            "value_type": "cumulative"
          },
          "transparent": false,
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "none",
            "short"
          ]
        },
        {
          "aliasColors": {},
          "bars": true,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 13,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": false,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "OCR",
              "currentTagKey": "",
              "currentTagValue": "",
              "disableDownsampling": false,
              "downsampleAggregator": "sum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "1d",
              "errors": {},
              "metric": "slt.passage.count",
              "refId": "A",
              "tags": {
                "host": "$maquina",
                "type": "ocr"
              }
            },
            {
              "aggregator": "sum",
              "alias": "Tag",
              "currentTagKey": "",
              "currentTagValue": "",
              "disableDownsampling": false,
              "downsampleAggregator": "sum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "1d",
              "errors": {},
              "metric": "slt.passage.count",
              "refId": "B",
              "tags": {
                "host": "$maquina",
                "type": "tag"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Passagens / Dia",
          "tooltip": {
            "shared": true,
            "value_type": "individual"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "short",
            "short"
          ]
        }
      ],
      "title": "New row"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {},
          "bars": true,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 3,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 8,
          "leftYAxisLabel": "Placas",
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": false,
            "hideEmpty": true,
            "max": true,
            "min": true,
            "rightSide": true,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": false,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": true,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "Faixa 1",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "sum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.ocr.recognizedPlates",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "lane": "1"
              }
            },
            {
              "aggregator": "sum",
              "alias": "Faixa 2",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "sum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.ocr.recognizedPlates",
              "refId": "B",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "lane": "2"
              }
            },
            {
              "aggregator": "sum",
              "alias": "Faixa 3",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "sum",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.ocr.recognizedPlates",
              "refId": "C",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "lane": "3"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Placas Reconhecidas / $timespan",
          "tooltip": {
            "shared": false,
            "value_type": "cumulative"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "short",
            "short"
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 9,
          "leftYAxisLabel": "Reconhecimentos/Total",
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": false,
            "hideEmpty": false,
            "max": true,
            "min": true,
            "rightSide": true,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "avg",
              "alias": "Faixa 1",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.ocr.performance",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "lane": "1"
              }
            },
            {
              "aggregator": "avg",
              "alias": "Faixa 2",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.ocr.performance",
              "refId": "B",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "lane": "2"
              }
            },
            {
              "aggregator": "avg",
              "alias": "Faixa 3",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "slt.ocr.performance",
              "refId": "C",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "lane": "3"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Performance OCR",
          "tooltip": {
            "shared": false,
            "value_type": "cumulative"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "none",
            "short"
          ]
        }
      ],
      "title": "New row"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "150px",
      "panels": [
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "decimals": 1,
          "editable": true,
          "error": false,
          "format": "s",
          "id": 2,
          "interval": null,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "span": 2,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "aggregator": "avg",
              "alias": "Uptime",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "errors": {},
              "hide": false,
              "isCounter": false,
              "metric": "os.system.uptime",
              "refId": "A",
              "shouldComputeRate": false,
              "shouldDownsample": false,
              "tags": {
                "host": "$maquina"
              }
            }
          ],
          "thresholds": "86400,604800",
          "title": "Uptime",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "current"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": true,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 4,
          "interval": null,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "Mbps",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "span": 2,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "aggregator": "avg",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "errors": {},
              "metric": "os.net.ifspeed",
              "refId": "A",
              "shouldDownsample": false,
              "tags": {
                "host": "$maquina",
                "iface": "eth0"
              }
            }
          ],
          "thresholds": "50,100",
          "title": "Network Link Speed",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "current"
        },
        {
          "aliasColors": {
            "Total": "#890F02",
            "Total (/home)": "#890F02",
            "Utilizado": "#508642",
            "Utilizado (/home)": "#508642"
          },
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 5,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "null as zero",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Utilizado",
              "fill": 2
            }
          ],
          "span": 4,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "Total",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "hide": false,
              "metric": "linux.disk.fs.space_total",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "mount": "/home"
              }
            },
            {
              "aggregator": "sum",
              "alias": "Utilizado",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "linux.disk.fs.space_used",
              "refId": "B",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "mount": "/home"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Uso de Disco (/home)",
          "tooltip": {
            "shared": false,
            "value_type": "individual"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "bytes",
            "bytes"
          ]
        },
        {
          "aliasColors": {
            "Total": "#890F02",
            "Total (/home)": "#890F02",
            "Utilizado": "#508642",
            "Utilizado (/home)": "#508642"
          },
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 6,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "null as zero",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "Utilizado",
              "fill": 2
            }
          ],
          "span": 4,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "Total",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "hide": false,
              "metric": "linux.disk.fs.space_total",
              "refId": "A",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "mount": "/"
              }
            },
            {
              "aggregator": "sum",
              "alias": "Utilizado",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "linux.disk.fs.space_used",
              "refId": "B",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina",
                "mount": "/"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Uso de Disco (/)",
          "tooltip": {
            "shared": false,
            "value_type": "individual"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "bytes",
            "bytes"
          ]
        }
      ],
      "showTitle": true,
      "title": "Recursos de sistema"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "200px",
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": 100,
            "leftMin": 0,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(255, 0, 0, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(244, 255, 0, 0.22)",
            "thresholdLine": false
          },
          "id": 1,
          "leftYAxisLabel": "% CPU",
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "avg",
              "alias": "CPU",
              "counterMax": "",
              "counterResetValue": "200",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "isCounter": true,
              "metric": "os.cpu",
              "refId": "A",
              "shouldComputeRate": true,
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina"
              }
            },
            {
              "aggregator": "avg",
              "alias": "Memória Livre",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "metric": "os.mem.percent_free",
              "refId": "B",
              "shouldDownsample": true,
              "tags": {
                "host": "$maquina"
              },
              "target": ""
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "CPU + Memória",
          "tooltip": {
            "shared": false,
            "value_type": "cumulative"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "percent",
            "short"
          ]
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 0,
          "grid": {
            "leftLogBase": 1,
            "leftMax": null,
            "leftMin": null,
            "rightLogBase": 1,
            "rightMax": null,
            "rightMin": null,
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 7,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "aggregator": "sum",
              "alias": "In",
              "counterMax": "4294967295",
              "counterResetValue": "0",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "isCounter": true,
              "metric": "os.net.bytes",
              "refId": "A",
              "shouldComputeRate": true,
              "shouldDownsample": true,
              "tags": {
                "direction": "in",
                "host": "$maquina"
              }
            },
            {
              "aggregator": "sum",
              "alias": "Out",
              "counterMax": "4294967295",
              "counterResetValue": "0",
              "currentTagKey": "",
              "currentTagValue": "",
              "downsampleAggregator": "avg",
              "downsampleFillPolicy": "none",
              "downsampleInterval": "$timespan",
              "errors": {
                "downsampleInterval": "Invalid interval string, expexcting a number followed by one of \"Mwdhmsy\""
              },
              "isCounter": true,
              "metric": "os.net.bytes",
              "refId": "B",
              "shouldComputeRate": true,
              "shouldDownsample": true,
              "tags": {
                "direction": "out",
                "host": "$maquina"
              }
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Transferência de rede",
          "tooltip": {
            "shared": false,
            "value_type": "cumulative"
          },
          "type": "graph",
          "x-axis": true,
          "y-axis": true,
          "y_formats": [
            "bps",
            "bps"
          ]
        }
      ],
      "title": "New row"
    }
  ],
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {
    "collapse": false,
    "enable": true,
    "notice": false,
    "now": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "status": "Stable",
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d"
    ],
    "type": "timepicker"
  },
  "templating": {
    "enable": true,
    "list": [
      {
        "allFormat": "glob",
        "current": {
          "tags": [],
          "text": "pc-km66-n",
          "value": "pc-km66-n"
        },
        "datasource": null,
        "includeAll": false,
        "name": "maquina",
        "options": [
          {
            "selected": false,
            "text": "pc-km70-n",
            "value": "pc-km70-n"
          },
          {
            "selected": false,
            "text": "pc-km70-s",
            "value": "pc-km70-s"
          },
          {
            "selected": true,
            "text": "pc-km66-n",
            "value": "pc-km66-n"
          },
          {
            "selected": false,
            "text": "pc-km66-s",
            "value": "pc-km66-s"
          },
          {
            "selected": false,
            "text": "pc-km43-n",
            "value": "pc-km43-n"
          },
          {
            "selected": false,
            "text": "pc-km44-s",
            "value": "pc-km44-s"
          },
          {
            "selected": false,
            "text": "pc-km32-n",
            "value": "pc-km32-n"
          },
          {
            "selected": false,
            "text": "pc-km33-s",
            "value": "pc-km33-s"
          },
          {
            "selected": false,
            "text": "pc-km25-n",
            "value": "pc-km25-n"
          },
          {
            "selected": false,
            "text": "pc-km25-s",
            "value": "pc-km25-s"
          }
        ],
        "query": "pc-km70-n,pc-km70-s,pc-km66-n,pc-km66-s,pc-km43-n,pc-km44-s,pc-km32-n,pc-km33-s,pc-km25-n,pc-km25-s",
        "refresh": false,
        "refresh_on_load": false,
        "type": "custom"
      },
      {
        "allFormat": "glob",
        "auto": true,
        "auto_count": 200,
        "current": {
          "text": "auto",
          "value": "$__auto_interval"
        },
        "datasource": null,
        "includeAll": false,
        "name": "timespan",
        "options": [
          {
            "text": "auto",
            "value": "$__auto_interval"
          },
          {
            "text": "1m",
            "value": "1m"
          },
          {
            "text": "10m",
            "value": "10m"
          },
          {
            "text": "30m",
            "value": "30m"
          },
          {
            "text": "1h",
            "value": "1h"
          },
          {
            "text": "6h",
            "value": "6h"
          },
          {
            "text": "12h",
            "value": "12h"
          },
          {
            "text": "1d",
            "value": "1d"
          },
          {
            "text": "7d",
            "value": "7d"
          }
        ],
        "query": "1m,10m,30m,1h,6h,12h,1d,7d",
        "refresh_on_load": false,
        "type": "interval"
      }
    ]
  },
  "annotations": {
    "list": []
  },
  "refresh": "15m",
  "schemaVersion": 9,
  "version": 17,
  "links": []
}

**Comment by bergquist** [comment]
Thanks for reporting this. It should be fixed now. Builds should be done within 20 min

**Comment by vitorboschi** [comment]
It's working now. Thanks for the fix!
