### ISSUE TITLE
Wrong date in timeseries panel tooltip

### ISSUE THREAD

**Issue by urbanze** [grafana/grafana#38799]
**What Grafana version and what operating system are you using?**
8.1.0

**What are you trying to achieve?**
Correct tooltip date in timeseries panel.

**What happened?**
When I use mouse to view info about points in timeseries panel, the tooltip box show wrong date. Eg:

Point X = 12:15h
Point Y = 12:16h

When mouse is close to X, show Y date.
When mouse is close to Y, show X date.

**Did you follow any online instructions? If so, what is the URL?**
I recorded .GIF to show this error/bug and uploaded to my drive (https://drive.google.com/file/d/1LrQ7JCNPscycKuQrDIx4QaclzXfPVI16/view?usp=sharing)

I already open this in grafana forum (https://community.grafana.com/t/wrong-date-in-timeseries-tooltip/52662)

**Comment by leeoniya** [comment]
pretty sure this got fixed in https://github.com/grafana/grafana/pull/37615

can you try the latest release (8.1.2)?

**Comment by mckn** [comment]
Yes, just verified it is not reproduced in 8.1.2 so #37615 will resolve this.
