### ISSUE TITLE
'Classic palette' Color scheme has no effect in State Timeline

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#38806]
**What happened**:
![state](https://user-images.githubusercontent.com/4949937/131792146-e29234da-0396-4f26-ac5f-e30cca3c684b.png)

**What you expected to happen**:
![state2](https://user-images.githubusercontent.com/4949937/131793059-46d5b083-c39f-4cfc-b004-d180ed787fba.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a State Timeline with different values
2. Check `Merge equal consecutive values`
3. Set `Color scheme` to `Classic palette`

**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)

**Comment by mckn** [comment]
Seems to work as expected if you try to visualize table formatted data but not with time series.

**Comment by imReker** [comment]
I tried switch format to table, and get same issue.

**Comment by ryantxu** [comment]
I am not really sure what the classic pallet *should* do.  In fact, perhaps it should be hidden/removed :man_shrugging: 

The classic pallet will color each *series* in a consistent way, but the required behavior is to get a new color based on the value.

**Comment by leeoniya** [comment]
i guess if each series just has "on" states (e.g. "on",null,"on") we can still use the classic palette.

basically just treat all states in a series as the next classic palette color?

**Comment by andness** [comment]
We have a timeline that shows what network operator our IoT device was connected to at any given time. So I expected the classic palette to color each value in each series differently, as this makes it much easier to see when the value changes. I guess this is what @leeoniya is suggesting, but I just wanted to give an example of a real world use case for it.

Note that the set of possible values is very large (https://www.mcc-mnc.com/) so creating a custom color mapping is difficult.

Our workaround is use the "Discrete" plugin (https://grafana.com/grafana/plugins/natel-discrete-panel/) but there's always the concern that this plugin will stop working.

**Comment by codeincarnate** [comment]
This is a tricky one unfortunately because the state timeline works on the basis of thresholds and there's not an easy data agnostic way to map palettes to those thresholds. We may want to consider hiding/removing these options for state timeline to make it less confusing. 

Otherwise, if there is a strong desire for this from someone please feel free to reopen.

**Comment by justinsmalley** [comment]
I am interested in this. There are times when I am reading a string metric, and don't know all possible values beforehand. There could be 10 or 20 different possible values with more being added daily. Some of my "favourite" or most common values I may hard code to a constant color using value mappings, but for the rest I would like to see automatically assigned different colors.

**Comment by ralismark** [comment]
fwiw this seem like the same thing as https://github.com/grafana/grafana/issues/35947
