### ISSUE TITLE
GraphNG: Allow axis placement control that's independent from unit config

### ISSUE THREAD

**Issue by SebastianThorn** [grafana/grafana#38810]
**What happened**:
Override setting not beeing honerd

**What you expected to happen**:
Field/Query to be moved to the right side

**How to reproduce it (as minimally and precisely as possible)**:
Add override in the panel-settings.

**Anything else we need to know?**:
JSON of panel:
```json
{
  "id": 4,
  "gridPos": {
    "h": 8,
    "w": 16,
    "x": 0,
    "y": 0
  },
  "type": "timeseries",
  "title": "InfluxDB",
  "datasource": "TF influx_1-8-5_prd_primary_v1",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 2,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 1,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "left",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": []
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Series"
        },
        "properties": [
          {
            "id": "custom.axisPlacement",
            "value": "right"
          }
        ]
      }
    ]
  },
  "options": {
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "table",
      "placement": "right",
      "calcs": [
        "last"
      ]
    }
  },
  "targets": [
    {
      "alias": "Measurements",
      "groupBy": [
        {
          "params": [
            "1m"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "influxdb_database",
      "orderByTime": "ASC",
      "policy": "default",
      "queryType": "randomWalk",
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "numMeasurements"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Series",
      "groupBy": [
        {
          "params": [
            "1m"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "influxdb_database",
      "orderByTime": "ASC",
      "policy": "default",
      "queryType": "randomWalk",
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "numSeries"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "Shards",
      "groupBy": [
        {
          "params": [
            "1m"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "influxdb",
      "orderByTime": "ASC",
      "policy": "default",
      "queryType": "randomWalk",
      "refId": "C",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "n_shards"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ]
}

```

**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)
- Data source type & version: InfluxDB 1.8.5
- OS Grafana is installed on: Ubuntu, Docker
- User OS & Browser: Win10, Windows Edge
- Grafana plugins: -
- Others: -

**Comment by SebastianThorn** [comment]
![image](https://user-images.githubusercontent.com/409816/131810150-6d4233f3-68e3-4c22-86a1-1e2572351233.png)

**Comment by mckn** [comment]
Try selecting one of the following fields:

- Value (base field name)
- Measurements

Since you have multiple value fields in your time series data you need to either select the first one represented in the data or the Value (base field name) to get the override to be applied properly.

<img width="1015" alt="Skärmavbild 2021-09-02 kl  16 27 38" src="https://user-images.githubusercontent.com/172951/131862139-25ae6c0a-f5cc-4e32-ba8e-460670ba1f09.png">

**Comment by mckn** [comment]
If you select any other field for the override it won't be applied. Not sure if this is by design or a bug but I will send it to the people with the answer on that question.

**Comment by SebastianThorn** [comment]
I want only one on the right side, "series".
This was possible in earlier versions of Grafana,

**Comment by mckn** [comment]
> I want only one on the right side, "series".
> This was possible in earlier versions of Grafana,

Ah, got it! So you basically want that field to be in a table on its own on the right side of the graph. Go it!

**Comment by dprokop** [comment]
@SebastianThorn thanks for opening the issue. This is one of the limitations of the Time series panel. I will consider this a feature request to allow axis side control that's independent from the Unit settings.

Currently the axes are created based on units configured for each series. Standard options unit will be displayed on the left hand side, wile units from overrides will by default create right hand side axes. Until we implement the unit-independent axis side control I suggest that you create a unit override for the series you want to be displayed on the right side.

**Comment by SebastianThorn** [comment]
It used to work in older versions of Grafana but is removed in version 8,
did I understand correctly?

**Comment by dprokop** [comment]
@SebastianThorn yes, indeed. It doesn't work in the Time series panel (axis are dependent on unit config), but it works still in Graph (old) panel
