### ISSUE TITLE
TablePanel Row Styles for "time series aggregations"

### ISSUE THREAD

**Issue by vlaadbrain** [grafana/grafana#3881]
When using time series aggregations Table Transform, it seems that Column Styles are less useful than row styles, since the metrics are layed out as rows.  Alternatively if it was possible to Transpose the data in the time series aggregations table the Column Styles would be more appropriate.  since the style formats data points that are derived from the same data type.

**Comment by torkelo** [comment]
Good point, but think column styles are good enough for now
