### ISSUE TITLE
Can't set color to threshold when added more than 55 thresholds

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#38822]
**What happened**:
Can't set color to threshold when last threshold is a special color, the color control of new threshold disappeared.

![color](https://user-images.githubusercontent.com/4949937/131824965-a3697c29-3154-46e9-83c5-b4e857fbed84.png)

**How to reproduce it (as minimally and precisely as possible)**:
1. Click Add threshold button 55 times, you'll see threshold 0, 10, 20, 30....540
2. The color of threshold `540` would be rgb(222, 218, 247)
3. Click Add threshold button again.
4. Color control of threshold `550` disappeared.
5. Remove threshold `550`.
6. Click color control of threshold `540`, click `Custom`, click textbox(`rgb(222, 218, 247)`), press Enter key.
7. Click Add threshold button.
8. Color control of threshold `550` appeared normally.
9. Click Add threshold button.
10. Color control of threshold `560` disappeared.

**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)
- User OS & Browser: Edge Chromium 93.0.961.33 beta

**Comment by torkelo** [comment]
think value mappings might be a better fit for you

**Comment by imReker** [comment]
No, the issue maybe related to color generating, not related to amount of thresholds.
Please note step 6-10, if I set same color manually to the last normal threshold, I can add new threshold again, but soon the issue occur again.

**Comment by glintik** [comment]
Hello guys,

Let me introduce my fix for this bug. Fix does:
1) Shows default color(#CCCCCC) in color picker when all colors are used in "Thresholds" section.
2) For any undefined color value shows color picker with default black color.

If you want another default color - fixed or from pallette, let me know, I'll adjust the code accordingly.
