### ISSUE TITLE
Time series panel: The values on the axes are repeated

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#38849]
**What happened**:
The similar values on the axes are repeated 
![bug](https://user-images.githubusercontent.com/43705385/131996169-145e849d-b596-44fa-9160-1d2a9b2d86f1.png)

**How to reproduce it (as minimally and precisely as possible)**:
Panel JSON:
```json
{
  "id": 73,
  "gridPos": {
    "h": 15,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "type": "timeseries",
  "title": "Color bars by discrete thresholds",
  "datasource": "gdev-testdata",
  "maxDataPoints": 42,
  "interval": "80s",
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "bars",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 0,
        "fillOpacity": 84,
        "gradientMode": "scheme",
        "spanNulls": false,
        "showPoints": "never",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "thresholds"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "orange",
            "value": 20
          },
          {
            "color": "red",
            "value": 30
          }
        ]
      },
      "mappings": [],
      "min": 0,
      "unit": "degree",
      "decimals": 0
    },
    "overrides": []
  },
  "options": {
    "tooltip": {
      "mode": "single"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "targets": [
    {
      "scenarioId": "random_walk",
      "refId": "A",
      "hide": false,
      "min": 1,
      "max": 2,
      "spread": 1
    }
  ]
}
```

**Environment**:
- Grafana version: 8.1.2-31763 (current play.grafana)

**Comment by dprokop** [comment]
@DmitrySidorow looking at your panel json I see that you have decimals config set to 0: `"decimals": 0`. Please set it to the number of decimals you want to show, or remove the decimals config completely to apply automatic decimals.

You can modify it by hand by setting Standard options -> Decimals in the panel options editor.

**Comment by DmitrySidorow** [comment]
> @DmitrySidorow looking at your panel json I see that you have decimals config set to 0: `"decimals": 0`. Please set it to the number of decimals you want to show, or remove the decimals config completely to apply automatic decimals.
> 
> You can modify it by hand by setting Standard options -> Decimals in the panel options editor.

I only have integer values. In the old graph, the values on the axis are not duplicated

Time series graph:
![image](https://user-images.githubusercontent.com/43705385/132207789-b49be394-9afb-49cc-aa4b-238a59170857.png)

Old graph:
![image](https://user-images.githubusercontent.com/43705385/132207921-52ee749c-3d39-4521-9c85-7d2ca8e2aecf.png)

**Comment by nonsavant** [comment]
Why did this get closed @dprokop? I have the same problem, for a graph with integer results the automatic labelling of the y-axis is whack.
