### ISSUE TITLE
Grafana 8 pagerduty alert use the same incident_key (dedup_key) for the same group alerts

### ISSUE THREAD

**Issue by vijkishan** [grafana/grafana#38845]
**What happened**:
We enabled new Grafana alerts feature by mentioning  ngalert in Grafana.ini file. However, PagerDuty receiving all alerts in single page load with same dedup_key. due to which all alerts that are fired in that group are tagged under one incident. 
**What you expected to happen**:

Each alert should have its own dedup_key such that  PagerDuty will create individual incident for each alert. 

**How to reproduce it (as minimally and precisely as possible)**:

Create multiple alert rules under single group folder. and adjust the threshold such that all alerts rules fire an alert. 
check in PagerDuty how that payload is. 
we should expect single payload with unique dedup_key for each alert or all alerts mentioned in the single payload but with unique dedup_key for each alert. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.0.6 (68fe9e3431)
- Data source type & version: Azure data explorer 
- OS Grafana is installed on: 
- User OS & Browser: Windows 11 and Edge 
- Grafana plugins:
- Others:

**Comment by davidmparrott** [comment]
@vijkishan can you post your alertmanager config here? I think you might be running into an issue with grouping that could be solved with configuration changes but would like to be sure.
