### ISSUE TITLE
Dashboard Variables Query regex not matching

### ISSUE THREAD

**Issue by cgthayer** [grafana/grafana#38857]
If one goes to dashboard settings > variables > edit, and specifies a query, with a regex, that regex isn't matching regex-parenthesis (for grouping).  For example, if I search for `/.*stress.*/` I see results but not for `/.*(stress).*/` or `/.*(stress|echo).*/`

**Environment**:
- Grafana version: 7.5.7
- Data source type & version: Prometheus

Picture showing that "stress" is matched (although it doesn't exist) for regex `/.*(stress).*/`, but "stress-grpc" and "stress-go-grpc" are not.

<img width="953" alt="Screen Shot 2021-09-03 at 4 34 08 PM" src="https://user-images.githubusercontent.com/265677/132075671-ee635017-cacf-4978-bc17-497ee8bbd239.png">

Here are all the matches one would expect, based on `/.*stress.*/`

<img width="956" alt="Screen Shot 2021-09-03 at 4 33 30 PM" src="https://user-images.githubusercontent.com/265677/132075753-794b2174-5b7b-4dec-94be-cf90274e8a88.png">

**Comment by dprokop** [comment]
@cgthayer thank you for reporting the issue. It seems to indeed be an issue with a code that extracts variables from query results. I managed to get a test case when it breaks: https://github.com/grafana/grafana/blob/1dd5ac1c68e7ca118199e79a8316ed3fe4364961/public/app/features/variables/query/reducer.test.ts#L364

For some reason mulitple regex matches are not taken into account. Maybe @hugohaggmark knows the reasoning for that?

**Comment by hugohaggmark** [comment]
@dprokop I guess this is still an issue in Grafana 8+?

**Comment by dprokop** [comment]
> @dprokop I guess this is still an issue in Grafana 8+?

Yes, it is. The breaking test case is agains main.

**Comment by natellium** [comment]
Closing this one as it is working as expected as described in the comment above.
