### ISSUE TITLE
Variables: Invalid size of the field for entering a variable

### ISSUE THREAD

**Issue by DmitrySidorow** [grafana/grafana#38850]
**What happened**:
Small size of the field for entering a variable
![image](https://user-images.githubusercontent.com/43705385/132001610-d2c7a25b-f059-4ad2-8632-a4a05aa3cb46.png)

**What you expected to happen**:
The field size must at least match the length of the hint 🤔

**Environment**:
- Grafana version: 8.1.2-31763
- User OS & Browser: Windows 10 + latest chrome

**Comment by glintik** [comment]
Hi guys,

I've added a fix for this small UI bug, please take a look.
