### ISSUE TITLE
Variables not updating inside a Panel when the preceding Row uses "Repeat For"

### ISSUE THREAD

**Issue by dllivipuma** [grafana/grafana#38853]
**What happened**: Variables are not updating inside a Panel when the preceding Row uses "Repeat For"

**What you expected to happen**: The panel content should update when changing their value.

**How to reproduce it (as minimally and precisely as possible)**: Changing the variable "host" a couple of times should bring up the issue.

**Anything else we need to know?**: The variables are not updating inside the panel, but the title updates as expected. I've attached the .json and hopefully it´s self-explained.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: None. The variables are custom.
- OS Grafana is installed on: Centos 8.4.2105
- User OS & Browser: Windows 10, Google Chrome and Firefox
- Grafana plugins: Happens with several type of panels: Text, Graph, Table, etc
![dashboard_variable_bug](https://user-images.githubusercontent.com/75102583/132017381-8a46008e-c349-4683-b1f8-10bfbac9e43d.gif)
[dashboard_variable_bug.txt](https://github.com/grafana/grafana/files/7106383/dashboard_variable_bug.txt)

- Others:

**Comment by dprokop** [comment]
Tried to reproduce it with the dashboard provided and indeed, it fails. After few changes of the variable the bottom panel no longer calls [`componentDidUpdate`](https://github.com/grafana/grafana/blob/e5ce7591677976768fa3877eac240a4a3f94d9be/public/app/plugins/panel/text2/TextPanel.tsx#L43). Cannot trace any dependencies on the actual variables as these are referenced only via `replaceVariables` closure.
