### ISSUE TITLE
Failed to send webhook-Client.Timeout exceeded while awaiting headers

### ISSUE THREAD

**Issue by letran3691** [grafana/grafana#38858]
**What happened**:

Recent I’ve issue. Sometime missing notification grafana send to telegram.
I Checked log and seen err “Failed to send webhook”.

Error specific:
```
t=2021-09-04T00:17:17+0700 lvl=info msg=“Sending telegram notification” logger=alerting.notifier.telegram chat_id=-337 bot_token=85-yBvgiE2TYpUkA-Jfjgttnu-9I apiAction=sendPhoto
t=2021-09-04T00:17:47+0700 lvl=eror msg=“Failed to send webhook” logger=alerting.notifier.telegram error=“Post https://api.telegram.org/bot851E2TYpUkA-Jfjgttnu-9I/sendPhoto: net/http: request canceled (Client.Timeout exceeded while awaiting headers)” webhook=infra_bot
t=2021-09-04T00:17:47+0700 lvl=eror msg=“failed to send notification” logger=alerting.notifier uid=bYDZk error=“Post https://api.telegram.org/bot85TYpUkA-Jfjgttnu-9I/sendPhoto: net/http: request canceled (Client.Timeout exceeded while awaiting headers)”
```

**Environment**:
My system don’t use proxy and grafana install manual
grafana v6.2.5
Data source type & version: Prometheus
OS centos 7

**Comment by dprokop** [comment]
@letran3691 thanks for creating this issue. I see that you are on an old version of Grafana. Have you tried updating to the latest?

**Comment by zuchka** [comment]
@letran3691 closing this issue due to staleness. If the issue persists, please let us know and we can reopen.
