### ISSUE TITLE
Refactor Explore's graph to use PanelRenderer instead of custom ExploreGraphNG

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#38866]
Explore currently uses [custom graph panel implementation](https://github.com/grafana/grafana/blob/main/public/app/features/explore/ExploreGraphNGPanel.tsx)which is pretty much the same implementation as TimeSeries panel. 

Let's rewrite it to use PanelRenderer with TimeSeriesPanel rather than having this additional wrapper. PanelRenderer with TimeSeriesPanel is already used successfully with Alerting NG, i..e https://github.com/grafana/grafana/blob/main/public/app/features/alerting/unified/components/rule-viewer/RuleViewerVisualization.tsx#L110

**Comment by aocenas** [comment]
Tbh I have no idea what that wrapper does in addition to normal panel. We have some `Container` wrappers that usually that do some work but usually it's a bit clearer what they do. So no objections but mostly from not really knowing if there is going to be any issue.

**Comment by dprokop** [comment]
> Tbh I have no idea what that wrapper does in addition to normal panel. We have some `Container` wrappers that usually that do some work but usually it's a bit clearer what they do. So no objections but mostly from not really knowing if there is going to be any issue.

@aocenas primary reason for us to use PanelRenderer is to reduce the repeated code between Explore and dashboards. @zoltanbedi is already on this task.
