### ISSUE TITLE
getOrCreateOrg in pkg/services/sqlstore/org.go doesn't actually get the org before create - initial grafana start fails

### ISSUE THREAD

**Issue by Millnert** [grafana/grafana#38862]
**What happened**: Due to LDAP integration I configured e.g.:
```
allow_sign_up = false
allow_org_create = false
auto_assign_org = false
```

Grafana does not start, and both Grafana and PostgreSQL query logs very clearly indicate getOrCreateOrg in https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/org.go tries to insert the default org even though it exists.

**What you expected to happen**: That Grafana starts and getOrCreateOrg in https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/org.go does not attempt to insert the default org when it exists.

**How to reproduce it (as minimally and precisely as possible)**: Presumably, configure e.g.:
```
allow_sign_up = false
allow_org_create = false
auto_assign_org = false
```

with a PostgreSQL DB backend.

It seems fairly clear just by following the getOrCreateOrg in https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/org.go how given those settings, we end up with an insert attempt.

Setting `auto_assign_org = true` and making sure the "Main Org." in the database has id = 1, causes a successful start of grafana.

**Anything else we need to know?**:  Repeating: Grafana doesn't start its very initial start so every aspect such as User OS/browser, data source etc are moot.

**Environment**:
- Grafana version: RPM grafana.x86_64 version 8.1.2-1
- Data source type & version: N/A
- OS Grafana is installed on: CentOS 8
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by dprokop** [comment]
@Millnert can you please share Grafana logs?

**Comment by zuchka** [comment]
@Millnert closing this issue due to staleness. If the problem persists, please upload your grafana logs and we can reopen 👍
