### ISSUE TITLE
Add "include image" option into Notification settings. ngalert 

### ISSUE THREAD

**Issue by tuhnu9089** [grafana/grafana#38867]
**Why is this component needed**:
ngalert is a good continuation of the alerting in grafana, but getting alerts without images is inconvenient.
In my opinion "include image" is a very useful function.
___
 - [x] Is/could it be used in more than one place in Grafana?
_This feature is already available for simple alerts (without ngalert)_

**Where is/could it be used?**:
The **include image** should be shown in the "contact point" -> "Notification settings" configuration. 
/alerting/notifications/receivers/[NAME]/edit?alertmanager=[NAME]
![129883661-a7d34bd3-09f7-4ebe-a74c-3c9ee739799f](https://user-images.githubusercontent.com/58990524/132179436-8ad0beaa-9616-4e54-b22c-84801c7faeb0.png)
___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [x] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [x] It is extendable (rest props are spread, styles with className work, and so on).
- [x] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [x] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by gotjosh** [comment]
I'm turning this into a discussion as it is a feature request. **For context, we've completely deprecated the support for images in Alerting.** 

With enough support, I'm happy to start digging up more context on why we removed it and what kind of solutions we can propose moving forward.

But I don't think this is needed anymore. We've included a way to customise your notifications via templating and you get a direct link to the queries (including graphs) that generated this alert. With those two, the alert itself should have enough context to help you dig what you need.
