### ISSUE TITLE
Grafana8 Dashboard Image Render

### ISSUE THREAD

**Issue by tetsuya28** [grafana/grafana#38871]
**What happened**:
In grafana 8, I cannot get image for a dashboard page, even with grafana-image-renderer plugins and image render sidecar.
In grafana 7, I get these images from following url.
```
https://sample-host.com/render/dashboard/db/sample-dashboard-name?from=now-1d%2Fd&to=now-1d%2Fd&width=1280
```
Is there a way to get dashboard image in grafana 8?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: grafana-image-renderer
- Others:

**Comment by marefr** [comment]
Please see [v8.0.0 breaking changes](https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-0-0/#breaking-changes).

Please use the `/render/d/<dashboard uid>/<optional dashboard slug>?...` format instead.
