### ISSUE TITLE
prometheus: monaco-based query editor, remaining issues

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#38877]
all necessary features are done now, there are two developmenent/maintenance issues remaining:
     - (after the feature-flag is removed). write an e2e-test that makes sure the editor works (either trigger an autocomplete and verify we get options, or at least verify that console.error is empty)
     - find a place for the tree-visualization-debug-tool

**Comment by itsmylife** [comment]
I should link this comment here https://github.com/grafana/support-escalations/issues/3580#issuecomment-1217513907

**Comment by itsmylife** [comment]
- "loading different versions of monaco editor at the same time" is a problem. We should come up with a best-practices document to inform people to use bundled version of monaco to prevent race conditions.

**Comment by itsmylife** [comment]
I've created the guideline here https://github.com/grafana/grafana/pull/54585
