### ISSUE TITLE
Change "whitelisted" label setting in data source configuration

### ISSUE THREAD

**Issue by myrle-krantz** [grafana/grafana#38888]
(originally reported by Eve Meelan)
![Screen Shot 2021-08-25 at 2 06 31 PM](https://user-images.githubusercontent.com/16136960/132229882-f92c8da6-8f51-4023-9b9c-a7be902ab5cb.png)

**What happened**:
In the DataSource/Prometheus configuration page, one of the settings is labeled "Whitelisted Cookies"

**What you expected to happen**:
The label should be "Accepted Cookies"

**Anything else we need to know?**:
Documentation may need to be updated.
The affected file can be found here https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/DataSourceSettings/DataSourceHttpSettings.tsx (thanks to Gio for finding it for me).

**Comment by osg-grafana** [comment]
Sorry for catching this late. Instead of "accepted", it is "allowed" per the style guide at https://github.com/grafana/grafana/blob/main/contribute/style-guides/documentation-style-guide.md#allowing-and-blocking.
