### ISSUE TITLE
Barchart: X axis does not update when data changes

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#38905]
To replicate

* Add 2 queries random walk 
* Add a reduce transform 
* Select bar chart 
* Change alias of one of the queries 
* See no change in x-axis (it should change to reflect the new category value) 

Or replicate here: https://play.grafana.org/d/JUpQTq7nk/1-new-features-in-v8-1?orgId=1 

Change any of the month names in the query CSV content, no change in graph until you also change the field name.

**Comment by zoltanbedi** [comment]
I've confirmed that when changing the x axis the panel doesn't update in edit view. Also observed that the unit didn't work as well.

https://user-images.githubusercontent.com/13729989/132685136-fb7bc505-297d-4703-9bbb-d80d70e411b7.mp4
