### ISSUE TITLE
Explore: Query inspector in split view is not split

### ISSUE THREAD

**Issue by dannykopping** [grafana/grafana#38917]
**What happened**:
Inspected two Loki queries, in a split view in Explore.
The Query Inspector's _Query_ tab's contents is updated in both splits when refreshing.

**What you expected to happen**:
The Query Inspector's _Query_ tab should only update for the split view which is being refreshed.

**How to reproduce it (as minimally and precisely as possible)**:
- inspect two Loki queries side-by-side in Explore
- click _Inspector_ on both views
- hit _Refresh_ from the _Query_ tab
- see both split views updating

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.2 (103f8fa094)
- Data source type & version: Loki
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Chrome
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
this seems to work in some cases and not in others, so we should investigate this.

**Comment by Elfo404** [comment]
We are still unsure how to move forward with this. In its current state it's obviously a bug but the fix may not be worth the time if this feature depending on actual usage. We should check how users are really using the inspector  and/or if it makes sense to have a single inspector for the whole Explore instead.

**Comment by gelicia** [comment]
After discussing with UX, this is a bug and actual usage is irrelevant - we will want to fix it.
