### ISSUE TITLE
auth.proxy creates users with their own org even when auto_assign_org = false

### ISSUE THREAD

**Issue by candlerb** [grafana/grafana#38922]
I have configured Grafana with:

```
[users]
allow_sign_up = false
allow_org_create = false
auto_assign_org = false
#auto_assign_org_id = -1
#auto_assign_org_role = Viewer

[auth]
disable_login_form = true
disable_signout_menu = true

[auth.basic]
enabled = false

[auth.proxy]
enabled = true
header_name = OIDC_CLAIM_email
header_property = email
auto_sign_up = true
sync_ttl = 60
whitelist = <proxy-IP>
headers = Name:OIDC_CLAIM_name
```

**What you expected to happen**:

New users to be created but not assigned to any organization.

**What happened**:

Sometimes this works; I've seen cases where new users get sent to `mygrafana/?orgId=-1` and then they have to wait until I manually assign their user to an organization.  This is what I want.  It prevents random "drive-by" users with Google accounts from doing anything important, whilst allowing me to see new users in a sort of holding area.

But more often than not, a new organization is created, just containing that one user with them as admin.  I don't want this, and I thought that `auto_assign_org = false` would prevent it.  It means I need to move them to the correct organization, and then delete the one which was dynamically created.

I can't explicitly set `auto_assign_org_id = -1`; this results in log `error="could not create user: organization ID -1 does not exist"`

**How to reproduce it (as minimally and precisely as possible)**:

Grafana is sitting behind an Apache2 proxy.

```
        OIDCProviderMetadataURL https://accounts.google.com/.well-known/openid-configuration
        OIDCClientID XXXX
        OIDCClientSecret XXXX

        OIDCRedirectURI /oauth2callback
        OIDCCryptoPassphrase XXXX
        OIDCScope "openid email"
        OIDCSessionInactivityTimeout 43200

        <Location />
                AuthType openid-connect
                Require valid-user
        </Location>

        ProxyPreserveHost On
        RequestHeader set X-Forwarded-Proto "https"
        ProxyPassMatch "^/(api/datasources/proxy/\d+/loki/api/v1/tail)" "ws://x.x.x.x:3000/$1"
        ProxyPass / http://x.x.x.x:3000/
        ProxyPassReverse / http://x.x.x.x:3000/
```

Connect using any random Gmail account.

(Note: I'm not using Grafana integrated authentication for Google accounts because the same proxy also fronts various other applications)

**Anything else we need to know?**:

Possible workaround will be to create a special organization called "Anonymous" or somesuch, and auto-create new users here.  Since I say the orgId=-1 work at least once, I was hoping this wouldn't be necessary.

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: N/A
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: macOS, Chrome
- Grafana plugins: None
- Others: Apache2 proxy with mod_auth_openidc in front of Grafana

**Comment by papagian** [comment]
> 

> I can't explicitly set `auto_assign_org_id = -1`; this results in log `error="could not create user: organization ID -1 does not exist"`

According to [the docs](https://grafana.com/docs/grafana/latest/administration/configuration/#auto_assign_org_id) the organisation should already exist. Can you try create such an organisation and set `auto_assign_org=true` and `auto_assign_org_id=<org_id>`?

**Comment by candlerb** [comment]
Yes I did that, and it works.  So I've now created an organization called "Holding Pen" that all unknown users get dumped into - and it's an OK solution.

Ideally, what I'd prefer to happen is that users which haven't been seen before get *no* organization.  And I did see that happen at least once: as mentioned before, when they went to the dashboard they had `orgId=-1`.  So I thought that was sorted.

But when I tried to repeat this, I found new users were getting added to their own dynamically-created organizations.

**Comment by papagian** [comment]
> Ideally, what I'd prefer to happen is that users which haven't been seen before get no organization. And I did see that happen at least once: as mentioned before, when they went to the dashboard they had orgId=-1. So I thought that was sorted.

Having `orgId=-1` can happen [if the user has used an authentication method other than the Grafana Authentication and there have been discovered more than one organisations](https://github.com/grafana/grafana/blob/78596a6756b58676837731b3297488c34b71c626/pkg/services/login/loginservice/loginservice.go#L143) or [if the user is invited](https://github.com/grafana/grafana/blob/063160aae2949dc1c13d043099198e7ca31b90a2/pkg/api/org_invite.go#L187).

I'll close this issue now but feel free to re-open it if you encounter a similar behaviour that does not belong to the above 2 cases.

**Comment by papagian** [comment]
my mistake; I meant that if the user has used an authentication method other than the Grafana Authentication and at least one organisation has been discovered. The organisation differs on each authentication provider and the `SkipOrgSetup` is not meaningful in all of them.
