### ISSUE TITLE
FR: Saved Reports

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3895]
Use case:

For example: some hacking attack OR any incident happens on New Year's eve and Ops wants to provide a report to the higher management for that time frame with different panels from different dashboards. So, currently they have to submit 3-4 dashboard snapshots for different dashboards.

But it would be great if Ops has the ability to add panel to this report which they are preparing through UI, which generated a URL at the end for people to access this Incident Report.

**Comment by bergquist** [comment]
This makes me think about #1920

**Comment by utkarshcmu** [comment]
Yeah #1920 can be a part of this feature. :)

**Comment by mtanda** [comment]
might be related https://github.com/grafana/grafana/issues/1803

**Comment by mtanda** [comment]
Just note.
Datadog has such feature.
https://www.datadoghq.com/blog/data-driven-notebooks/

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
