### ISSUE TITLE
Dashboard List Panel and support for "Last viewed dashboards"

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3896]
Store last viewed dashboards in local storage and show in dashboard list panel.

**Comment by utkarshcmu** [comment]
+1

**Comment by utkarshcmu** [comment]
I am about to start the work on:
1. 10 Most starred dashboards
2. 10 Recently updated dashboards

Where should these lists be displayed? Any suggestions? Home Page? Or a new link in the main nav as "Quick Look" or something.

**Comment by torkelo** [comment]
@utkarshcmu maybe an option in the dashboard list panel to show those?

**Comment by utkarshcmu** [comment]
Yeah, agreed. That would be a good start.
