### ISSUE TITLE
Query error when the value of the variable contains a forward slash AND you have multi-value selected for that variable

### ISSUE THREAD

**Issue by allomorphy** [grafana/grafana#38973]
Firstly, thank you to the Grafana gods for generously giving us such a powerhouse 🤗  

I seem to have detected an issue with template variables where multi-value is on and one of the values contains a forward slash. This occurred while trying (and failing 😅) to implement a repeat of the panel that you see in the link below with using a template variable to calculate the from and the to and then calling `angular.element('grafana-app').injector().get('timeSrv').setTime({from: kraft_from_grafana, to: kraft_to_grafana})`.
The report below is with _no_ custom js in the dashboard, it is not a problem for our use case right now but it might be useful for us later or for others, so we report here.

**What happened**:
Using influxdb, grafana reports an error on the QUERY as shown when the value of the variable contains a forward slash AND you have multi-value selected for that variable.
`message:"error parsing query: found \/, expected identifier, string, number, bool at line 1, char 228"` 

**What you expected to happen**:
The QUERY should work as it does when you select the template variable value that does not contain a forward slash or when you do not have multi-value selected.

**How to reproduce it (as minimally and precisely as possible)**:
Define a variable that contains a forward slash as part of its value and select multi-value for that variable.
Select the variable with the forward slash.

**Anything else we need to know?**:

QUERY works, when you do either of the following:
1. deselect multi-value 
2. encode the forward slash as `%2F`  in the definition of the  variable

This may be seen on the screen recording below or by using this dashboard where 1. and 2. above are set to reproduce the bug [forward slash error](https://humanalyse.com/d/6okmeGSnz/grafana_issues?orgId=3&from=2021-08-02%2010:51:10&to=2021-08-02%2015:21:10&var-glucose_units=mg%2Fdl&var-insulin_units=pMol&var-kraft_curves=1627896070071975400)
![Grafana_Issue_forward_slash_Kapture 2021-09-08](https://user-images.githubusercontent.com/50141922/132483013-2843ef36-1e51-4491-9f9c-63248accb9c6.gif)
**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)
- Data source type & version: Influxdb 1.7.0-1
- OS Grafana is installed on: aws container
- User OS & Browser: Mac (FWIW) All browsers
- Grafana plugins: e "GF_INSTALL_PLUGINS=marcuscalidus-svg-panel,blackmirror1-singlestat-math-panel,briangann-gauge-panel,jdbranham-diagram-panel,natel-plotly-panel and a prototype d3 plugin
- Others: N/A

**Comment by hugohaggmark** [comment]
Hi @allomorphy and thank you for creating such an informative issue. I think your Influx queries need to be adjusted according to the guidelines here: https://grafana.com/docs/grafana/latest/datasources/influxdb/influxdb-templates/

Specifically the WHERE clause should be changed to something like `WHERE ("cpu" =~ /^$cpu$/)` using regex pattern instead.

Let me know if that helps so we can close this issue.

**Comment by allomorphy** [comment]
Thank you @hugohaggmark No bug!
Indeed the regex invocation slays this beast. 

Grafana rocks! (But sometimes you need a generous guide 😉 )
I suck at reading docs, missed this one and did not think of it in my trial & error cycle 😓 

PS. I am wondering whether we could have more informative error messages in Grafana.
This might be a nice example and I would be happy to make PR's for such.
(PS I hack rather than program in js, too busy with orchestrating our health revolution.)

**Comment by hugohaggmark** [comment]
No worries, you're free to open a PR anytime, but I'm going to close this issue now because we're trying to limit open GitHub issues in order to better track planned work and features. Thank you for taking the time to create the issue.
