### ISSUE TITLE
Dashboard jiggles around when exemplar view drops down at right of window

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#38976]
**What happened**:
As I mouse over exemplars, the whole window "jiggles".

https://user-images.githubusercontent.com/8125524/132492100-a341a5df-ee52-4952-94a6-2d2d700b005b.mp4

**What you expected to happen**:
Steady display.

**How to reproduce it (as minimally and precisely as possible)**:
Make a Timeseries panel with exemplars, and have it set against the right-hand-side of the window.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.0-33294pre (17f9bc138e)
- Data source type & version: Prometheus 
- OS Grafana is installed on: Linux
- User OS & Browser: Windows 10; Chrome Version 92.0.4515.159 (Official Build) (64-bit)
- Grafana plugins: 
Alert Manager By Prometheus alertmanager, 
Alert groups By Grafana Labs, 
Alert list By Grafana Labs, 
Annotations list By Grafana Labs,
Azure Monitor By Grafana Labs,
Bar chart By Grafana Labs,
Bar gauge By Grafana Labs,
Canvas By Grafana Labs,
CloudWatch By Grafana Labs,
Dashboard list By Grafana Labs,
Debug By Grafana Labs,
Direct Input By Grafana Labs,
Elasticsearch By Grafana Labs,
Gauge By Grafana Labs,
Geomap By Grafana Labs,
Getting Started By Grafana Labs,
Google Cloud Monitoring By Grafana Labs,
Graph (old) By Grafana Labs,
Graphite By Grafana Labs,
Heatmap By Grafana Labs,
Histogram By Grafana Labs,
InfluxDB By Grafana Labs,
Jaeger By Grafana Labs,
Live By Grafana Labs,
Logs By Grafana Labs,
Loki By Grafana Labs,
Microsoft SQL Server By Grafana Labs,
MySQL By Grafana Labs,
News By Grafana Labs,
Node Graph By Grafana Labs,
OpenTSDB By Grafana Labs,
Pie chart By Grafana Labs,
Plugin list By Grafana Labs,
PostgreSQL By Grafana Labs,
Prometheus By Grafana Labs,
Stat By Grafana Labs,
State timeline By Grafana Labs,
Status history By Grafana Labs,
Table By Grafana Labs,
Table (old) By Grafana Labs,
Tempo By Grafana Labs,
TestData DB By Grafana Labs,
Text By Grafana Labs,
Time series By Grafana Labs,
Welcome By Grafana Labs,
XY Chart By Grafana Labs,
Zipkin By Grafana Labs

- Others:

**Comment by glintik** [comment]
I'd propose to add "overflow-y: scroll" to dashboard. It will fix this and many other similar UI issues.

**Comment by srclosson** [comment]
@bboreham could I get the JSON for your dashboard? I'm going to take a look at this.

**Comment by evandandrea** [comment]
It's the Metrics squad's understanding that this belongs with User Essentials. Please let me know if wrong.

**Comment by JoaoSilvaGrafana** [comment]
I am struggling to reproduce this on Windows, @srclosson what dashboard did you use to reproduce it?

**Comment by JoaoSilvaGrafana** [comment]
I managed to reproduce it on Windows as well, this does not happen on Heatmap exemplars, only seems to happen for Timeseries as it is using the `ExemplarsPlugin`, heatmap is using a more custom thing so it is fine.

For anyone using Mac, you can still see this broken if you open an Exemplar that goes out of bounds of the screen and then just scroll down, you can see that the page kind of becomes broken (look at navigation):
<img width="1475" alt="Screenshot 2022-09-16 at 15 26 53" src="https://user-images.githubusercontent.com/100691367/190664133-cd66f9e5-e1c7-47c4-8639-11ed3e51457d.png">

@grafana/grafana-bi-squad Any ideas of why this happens on the `ExemplarsPlugin`?

**Comment by codeincarnate** [comment]
This is tricky because there isn't really a limit to exemplars and so it's always potential that they might extend beyond the viewport. This is also OS specific. We may need to re-think a way to display exemplars if we're running into a lot of situations where they would need to be scrolled.

**Comment by leeoniya** [comment]
actually the plan is to render exemplars on canvas, same as heatmap does, and to unify the tooltip strategy. that second part is tricky because of how differently the tooltips are structured and work.

**Comment by gtk-grafana** [comment]
Can we adjust the priority on this? This essentially breaks the ability to use exemplars for all devices except apple silicone that appear to have native scrollbar styles that aren't rendered in the content.

**Comment by bboreham** [comment]
Interesting - I haven't noticed this happening on my Windows machine recently.

**Comment by gtk-grafana** [comment]
I can repro it on both my windows 10 devices, also it looks like `overflow: overlay` on the body fixes this issue
