### ISSUE TITLE
Loads ressources from Amazon AWS

### ISSUE THREAD

**Issue by tokudan** [grafana/grafana#3897]
Grafana unnecessarily includes a resource from https://grafanarel.s3.amazonaws.com/ when a webbrowser accesses a graph, no matter if the user is logged in.
That's a privacy issue, as it leaks information about the graphs and dashboards I use, maybe even about the template variables.

The only link I could find on a quick glance is https://grafanarel.s3.amazonaws.com/latest.json, which only contains informations about a beta version. I do not understand why grafana let's a client load that information.

**Comment by torkelo** [comment]
In Grafana 1.x , only when opening dashboard settings, grafana will request https://grafanarel.s3.amazonaws.com/latest.json to check if there is a newer version of grafana available. 

This feature is not present in 2.x (The feature might still be there in 2.0 beta and 2.1 not sure exactly when it was removed)
