### ISSUE TITLE
log package is expensive, especially in loglevels that aren't even used.

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#3898]
i have an application that uses `github.com/grafana/grafana/pkg/log` and I noticed a lot of cpu time is spent in the `Debug` level even though my level is set to > debug.

the culprit is obvious.
all functions look like so:
```
func (l *Logger) Trace(format string, v ...interface{}) {
	msg := fmt.Sprintf("[T] "+format, v...)
	l.writerMsg(0, TRACE, msg)
}

func (l *Logger) Debug(format string, v ...interface{}) {
	msg := fmt.Sprintf("[D] "+format, v...)
	l.writerMsg(0, DEBUG, msg)
}

func (l *Logger) Info(format string, v ...interface{}) {
	msg := fmt.Sprintf("[I] "+format, v...)
	l.writerMsg(0, INFO, msg)
}

...
```

it's only within `l.writerMsg` that we check
```
	if l.level > level {
		return nil
	}
```

therefore, every call to any such function (`.Debug`, `.Info()`, etc) causes calls to Sprintf (which are quite expensive) and needless allocations, only to be discarded because the level check happens *after* this.

Now, I could fix this (by moving the level checks before the Sprintf's) and file a PR, but I have to ask: why does grafana need its own log package in the first place?  We're probably better off relying on a solid 3rd party logging library thas is actively maintained.

**Comment by Dieterbe** [comment]
FWIW in the past i've quite happily used https://github.com/op/go-logging/
in fact, i even brought up the same issue there and a while ago and now all levels are optimized https://github.com/op/go-logging/issues/50

**Comment by torkelo** [comment]
One reason for using this embedded log package was that it was used by gogs (Go Git Service), which was a project that I took some of inspiration from (macaron, ini config system, xorm, etc), Another reason was that I feelt the built in logging lib to basic and the other big logging libs to complex. But go-logging looks great, So if we can migrate to go-logging without any breaking config (grafana.ini) changes that would be great. 

If it looks tricky to migrate to go-logging than adding the changes you suggest would be great as well. 

Just a quick question regarding logging best practice, I think it is usually best practice in performance critical loops/functions to do a level check outside the lib (as well) before calling the logging function.

**Comment by Dieterbe** [comment]
> Just a quick question regarding logging best practice, I think it is usually best practice in performance critical loops/functions to do a level check outside the lib (as well) before calling the logging function.

in go this doesn't help much. if the logging functions are relatively short (~5 lines) then the compiler will just inline them. even if they aren't inlined, the overhead is not much more then a stack allocation and a jmp call, which should be negligible. so i would only ever do this if it becomes apparent through a cpu profile that it's needed, otherwise it's not worth making the client code uglier.

**Comment by Dieterbe** [comment]
for the record, i have to correct myself re the above. as it turns out calling the log.Debug function a lot when not needed will cause quite some time spent in runtime.convT2E to convert the args to `interface{]`, and also the variadic interface arg is a slice and is heap allocated, so causes time spent in malloc and GC later.
this is probably true whether the function is inlined as well.
