### ISSUE TITLE
Plugins Catalog: display a 404 view when requested plugin does not exist

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#38997]
If a user navigates to the Plugin details page in the catalog with an unknown plugin id they are greeted with a blank page. We should provide some feedback so the user knows what's happened and what next steps to take.

**Comment by jackw** [comment]
In #38876 I added a simple alert as below:

<img width="1680" alt="Screenshot 2021-09-08 at 16 25 06" src="https://user-images.githubusercontent.com/73201/132669616-659bf729-9669-4640-92d0-5af92d650fd2.png">

If we feel that's enough shall we close this @grafana/plugins-platform?

**Comment by leventebalogh** [comment]
I think it should be absolutely enough for now (at least until we have a specific design for this scenario).

Closing, reopen if you have objections.
