### ISSUE TITLE
404 {"message":"Dashboard not found"} when getting dashboard using /api/dashboards/{{URI}}

### ISSUE THREAD

**Issue by vsonone** [grafana/grafana#3899]
We have a use case where we are iterating over all the dashboards available in grafana to get their details.

We are using basic authentication for this. for eg.
http://admin:admin@grafana_server/api/dashboards/{{dashboardURI}}
to get the dashboard details.

The use case is the following.
Our thread wakes up every 90 seconds, and then iterate over all the dashboards. it follows the following flow:
               - get all organizations for the user (GET /api/orgs)
              - for each organization
                       - switch to the organization (POST /api/user/using/:organisationId)
                       - get all dashboards for the organization (GET /api/search/)
                       - for each dashboard
                                 - get the dashboard details (GET /api/dashboards/db/:slug)

We are getting 404 Not found for some dashboards, although the dashboard exists. It is random which dashboard will return 404 Not found in an iteration. Sometimes, none of the dashboard return any errors. I am attaching a screenshot from a simple jmeter test, in which I am just trying to iterate over 6 dashboards for a given organization. And I get this error for random dashboards.
![grafanaerror](https://cloud.githubusercontent.com/assets/7455594/12699820/e7042844-c78f-11e5-82cd-8a3ddeb64a8c.PNG)

Following are the logs in grafana.log file.

Can you suggest some pointers on how to resolve this issue ? 
is this a performance issue with grafana ?
Can we somehow make sure that we always get the dashboard details if the dashboard exists and never get 404 not found for an existing dashboard ?

2016/01/30 17:53:22 [I] Completed /api/dashboards/db/sslv3-merchants 404 Not Found in 113.28364ms
2016/01/30 17:53:22 [I] Completed /api/dashboards/db/scholastic-inc-secure-acceptance-dashboard 404 Not Found in 105.882216ms
2016/01/30 17:53:22 [I] Completed /api/dashboards/db/scott-dashboard 404 Not Found in 104.503894ms
2016/01/30 17:53:23 [I] Completed /api/dashboards/db/secure-acceptance-merchant-dashboard 404 Not Found in 197.811082ms
2016/01/30 17:53:23 [I] Completed /api/dashboards/db/service-access-log 404 Not Found in 109.318901ms
2016/01/30 17:53:23 [I] Completed /api/dashboards/db/shauns-merchants-new 404 Not Found in 108.316792ms
2016/01/30 17:53:23 [I] Completed /api/dashboards/db/stdaniel-dash 404 Not Found in 106.712731ms

**Comment by vsonone** [comment]
I tried using API key instead of basic auth, and the results are promising. No errors in my limited test run. 

Do you think API Key is a better way to use http api over basic authentication to avoid such errors ?

**Comment by torkelo** [comment]
the only reason for getting this error is if your trying to get a dashboard that belongs to another organization, the api/dashboards/{{dashboardURI}} route is will only check currnet active organization.

**Comment by vsonone** [comment]
Those dashboards are part of the current active organizations....still
getting the error

**Comment by torkelo** [comment]
Can you share the script that does the search and fetch loop? Will try to replicate

**Comment by vsonone** [comment]
Here is my JMeter script. You will have to update the organizationId and
the dashboard URL ( See comments in the script).

Let me know your thoughts on the same, the API key seems to perform better.

See TODO: in the list, you will have to change the following:
- Grafana server name
- Grafana username password, auth basic header, I have admin/admin
- Dashboard URLS
- OrganizationId

On Sun, Jan 31, 2016 at 9:32 AM, Torkel Ödegaard <notifications@github.com>
wrote:

> Can you share the script that does the search and fetch loop? Will try to
> replicate
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/grafana/grafana/issues/3899#issuecomment-177526497>.
>



-- 
Thanks & Regards
Vikrant

The trouble with a rat race is, even if you win you are still a rat.

You take a decision, good or bad, rest is fate.
