### ISSUE TITLE
Adhoc filter generate incorrectly query in Prometheus

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#38996]
**What happened**:
Create Prometheus Query as below and set Filter to `nodeId=abc`
`last_over_time(sum by(nodeId)(port_traffic_total{port="9500"}) [1m:]) [$__range:]`

The generated query is incorrect:
`last_over_time{nodeId="abc"}(sum by(nodeId)(port_traffic_total{nodeId="abc",port="9500"}) [15m:]) [86400s{nodeId="abc"}:]`

Error 1: `nodeId="abc"` appended incorrectly to function `last_over_time`
Error 2: `nodeId="abc"` appended incorrectly to variable `$__range`

**What you expected to happen**:
`last_over_time(sum by(nodeId)(port_traffic_total{nodeId="abc",port="9500"}) [1m:]) [86400s:]`

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.2 (103f8fa094)

**Comment by ivanahuckova** [comment]
There are still multiple issues with ad hoc filter. Here is the list of other ones: https://github.com/grafana/grafana/pull/30931. Probably makes sense to fix this properly using parser rather than tweaking regex.

**Comment by ngc104** [comment]
broken in v8.1.6 too.

**Comment by afirth** [comment]
possibly related, #51743

**Comment by itsmylife** [comment]
This is fixed in this https://github.com/grafana/grafana/pull/75250
And the PR was backported to `v10.0.x` and `v10.1.x`
We are sorry that this fell into the cracks. 
Please let us know if there are further issues.
