### ISSUE TITLE
Collision in properties on DataFrameView

### ISSUE THREAD

**Issue by oscarkilhed** [grafana/grafana#38993]
**What happened**:
JS error "Cannot redefine property 2"

**How to reproduce it (as minimally and precisely as possible)**:
Create a stat, gauge or piechart panel.
Use this data as with the testdata csv content datasource:

foo,bar, 2
1,2,3

**Anything else we need to know?**:

The error occurs [here](https://github.com/grafana/grafana/blob/058ac6becfd00687dcddece4fc8b49a8a4547ea3/packages/grafana-data/src/dataframe/DataFrameView.ts#L35) because we're defining properties on the DataFrameView by name and by index. If there is a field name that is also a number, that number can collide with the property name set by index.

**Environment**:
- Grafana version: 8.1

**Comment by torkelo** [comment]
This was fixed by https://github.com/grafana/grafana/pull/40580
