### ISSUE TITLE
InfluxDB: InfluxQL query editor: tag-values with `'` or `\` break tag-name-selector

### ISSUE THREAD

**Issue by phil-or** [grafana/grafana#39003]
When I choose a metric from the dropdown menu the query editor mode is bugy:
![image](https://user-images.githubusercontent.com/36534023/132546298-c43991db-2e0c-4f8b-a2ea-a44840604de6.png)

Can't remove the metric tag because there is only "No options found". Tag hostname and measurement name also can't be removed and no more "GROUP BY" and "FROM" clausel can be added. 
![image](https://user-images.githubusercontent.com/36534023/132544396-962fee74-7ce8-4e8c-ad5f-5b3285c8211a.png)

When I choose /CallsIn/ as metric everything works fine:
![image](https://user-images.githubusercontent.com/36534023/132547558-7714b2d0-4768-477a-98ad-4ae286842553.png)

**Environment**:
- Grafana version: 8.1.1
- Datasource: InfluxDB 1.8.6
- User OS & Browser: Firefox 78.14.0esr (64-Bit) and Version 93.0.961.38 (64-Bit)

**Comment by dprokop** [comment]
@phil-or Is there any error in the developers console? If so - could you please share it with us?

**Comment by phil-or** [comment]
There is no error in the developer console.

But I have found out the cause of the problem. It's a problem with special characters. If in the tag_value the character ' or \ is used, you get "No options found" otherwise it works correct.
