### ISSUE TITLE
Plugins: Data Sources API (read-only endpoints) not Accessible to Viewers/Editors

### ISSUE THREAD

**Issue by bradenhs** [grafana/grafana#39011]
### First off - thank you for making such a wonderful tool! I've used Grafana in my day to day work at multiple companies and it's always been a pleasure to work with :heart:

---

**What happened**:

When I attempt to make a `GET` request to the `/api/datasources` endpoint as a viewer or editor I get a `403 Forbidden` response which feels inconsistent given that this data is accessible to viewers and editors through other means. It's exposed to both viewers and editors via the `grafanaBootData` global variable on the window object. Additionally it's accessible in the UI to editors via the data source selector component.

![Data Sources](https://user-images.githubusercontent.com/22484684/132592025-d7370721-1870-4fb1-946d-f7760b5d19a3.gif)

**What you expected to happen**:

I expect viewers and editors to have access to read-only data source API endpoints given they can already access this data via other means.

**How to reproduce it (as minimally and precisely as possible)**:

- Start Grafana locally
- Create a viewer or editor API key
- Put API key in a new file called `api_key`
- Run `curl http://localhost:3000/api/datasources -H "Authorization: Bearer $(cat api_key)"`
- Observe that a `403 Forbidden` response is returned
- Navigate in a browser to `http://localhost:3000`
- Login as a viewer or editor
- Open the dev tools and execute this `console.log(window.grafanaBootData.settings.datasources)`
- Observe that you're able to access all data source data despite not having the admin role

**Anything else we need to know?**:

I filed this as a bug but it could easily be regarded as a feature request too. I'd be happy to move this to a GitHub discussion with the data sources label if that's deemed the more appropriate route.

Additionally, if it is decided that these API endpoints should be made accessible to viewers/editors then I would be very happy to make a PR with the fix provided that would expedite the change 😄 

**Environment**:
- Grafana version: main branch latest commit (https://github.com/grafana/grafana/tree/258e2cd91eadeab8f37df10ce24138997122c1af)
- Data source type & version: n/a
- OS Grafana is installed on: Windows (WSL)
- User OS & Browser: Windows - Chrome
- Grafana plugins: None
- Others: Not sure what this item is asking about

**Comment by dprokop** [comment]
@marefr I'm gonna pass this one to Backend squad as you are probably the best to explain this behavior of the endpoint.

**Comment by kminehart** [comment]
Hmmm. It looks like this endpoint is intended to reflect the permissions required for accessing the data source settings list, which is restricted to admin-only..

The code for this restriction is here: 

https://github.com/grafana/grafana/blob/main/pkg/api/api.go#L269

I think it makes sense for this endpoint to reqOrgViewer, as it's a read-only endpoint and does not expose any interesting or potentially malicious data.

It looks like the response of this request is slightly different than the data stored in the boot settings. If we didn't find that changing the permission on this endpoint is palatable, I suggest we create a new one that returns the same data as what's in the boot settings.

**Comment by wbrowne** [comment]
@grafana/plugins-platform have chatted about this a bit recently and IIRC we think it makes sense to update the permissions. This will likely be something we tackle soon as the Plugin Catalog comes out of beta

**Comment by bradenhs** [comment]
Great! @wbrowne would you accept a PR on this (I'd be happy to make one) or would it be easier for Grafana to tackle this change internally? Also, just curious, when do you anticipate the Plugin Catalog to come out of beta?

**Comment by jessabe** [comment]
@bradenhs Plugin Catalog is meant to come out of beta in 8.3. I'll have a sync with the team on if an external PR makes sense or not as @wbrowne is currently on holiday.

**Comment by bradenhs** [comment]
Thanks @jessabe!

**Comment by jessabe** [comment]
@bradenhs no problem! So we did a quick go through and it looks like this might be a bit difficult to do externally as it will require some changes in Grafana Enterprise to work. I've looped in our PM's and the Engineers involved are already thinking about this, so hopefully should be resolved soon. I'll update with an ETA when we have one. :)

**Comment by wbrowne** [comment]
Now that the plugins platform is out of beta and 8.3.0 is coming soon, @grafana/plugins-platform will take a look at this.

**Comment by mitulk** [comment]
@wbrowne Any update on this? 
(I see the milestone tagging activity, but I'm not sure I'm interpreting it correctly.)

**Comment by kalleep** [comment]
@mitulk We just started working on this issue

**Comment by marefr** [comment]
@bradenhs I just realized that by calling [/api/frontend/settings](https://grafana.com/docs/grafana/latest/http_api/other/#get-settings) you would receive the same data as in `grafanaBootData`. Sorry for the confusion.

**Comment by marefr** [comment]
Given my earlier comment and lack of response I'm going to close this. We'll consider reopen if we have misunderstood something.
