### ISSUE TITLE
Grafana doesn't show graph if time is set to more than "last 6h"

### ISSUE THREAD

**Issue by drptbl** [grafana/grafana#3902]
Hello,

I'm really struggling with this issue and I have completely no idea what's going on.
I've set up graphite server which gets the data, later Grafana prints it out. When I'm right in Grafana and I have set "last 6h", graph is normally shown and everything works perfect, but if I select something more than "last 6h", for example "last 7h" or "last 12h" - graph is empty - no idea why. It should at least show my last 6h, even if there is no data (but data is here anyway) for the rest of time, am I clear? But no, graph is empty. The funny part is that If I set time to "last 7h" there is no graph, if I set it to "last 6h" - graph is here.

It looks that responses are totally fine for "last 6h" and "last 7h", but still, "last 7h" shows empty graph.
Any suggestions? Would be great!

- "Last 6h":
<img width="1221" alt="screen shot 2016-01-31 at 18 43 43" src="https://cloud.githubusercontent.com/assets/8177587/12703741/cf8376d2-c84a-11e5-8be8-0cb1aa13c872.png">
<img width="1436" alt="screen shot 2016-01-31 at 18 44 07" src="https://cloud.githubusercontent.com/assets/8177587/12703742/cf851cda-c84a-11e5-95fb-662703ef8a6b.png">
<img width="1437" alt="screen shot 2016-01-31 at 18 44 53" src="https://cloud.githubusercontent.com/assets/8177587/12703743/cf855dc6-c84a-11e5-8650-532711bab636.png">
<img width="1439" alt="screen shot 2016-01-31 at 18 45 03" src="https://cloud.githubusercontent.com/assets/8177587/12703744/cf882a9c-c84a-11e5-8574-47dbb24d09a4.png">

- "Last 7h":
<img width="1227" alt="screen shot 2016-01-31 at 18 46 09" src="https://cloud.githubusercontent.com/assets/8177587/12703751/08e37f1c-c84b-11e5-8a1c-ed51f6979c58.png">
<img width="1436" alt="screen shot 2016-01-31 at 18 46 23" src="https://cloud.githubusercontent.com/assets/8177587/12703750/08e2ed22-c84b-11e5-9138-e4b785881397.png">
<img width="1435" alt="screen shot 2016-01-31 at 18 46 41" src="https://cloud.githubusercontent.com/assets/8177587/12703752/08e5b6d8-c84b-11e5-9414-b06971cfaca4.png">
<img width="1435" alt="screen shot 2016-01-31 at 18 46 51" src="https://cloud.githubusercontent.com/assets/8177587/12703749/08e1d2c0-c84b-11e5-93fd-ba70f2cfaf37.png">

Thanks in advance! If need more details, just say :).

**Comment by woodsaj** [comment]
This is an issue with your graphite server/configuration.  Grafana is querying graphite correctly, but graphite is returning all null points.  This suggests that your graphite server is having problems with aggregated data.  When you request 6h of data, graphite returns raw data, but for ranges greater then 6hours it is trying to use aggregated data that it cant find. 

My guess is that you have the retentions in your storage-schemas.conf incorrectly set. ie, if you set the retention to `1m:21d,30m:5y`  but only send data every 15minutes then your aggregated data will be all nulls, assuming the default xFileFactor of 0.1 in you storage-aggregation.conf

**Comment by drptbl** [comment]
@woodsaj I know that's not proper place to ask, but this is how my `storage-schemas.conf` looks like:
```
[carbon]
pattern = ^carbon\.
retentions = 10s:6h,1min:90d

[default_1min_for_1day]
pattern = .*
retentions = 10s:6h,1min:6d,10min:1800d
```
and `storage-aggregation.conf`:
```
[min]
pattern = \.lower$
xFilesFactor = 0.1
aggregationMethod = min

[max]
pattern = \.upper(_\d+)?$
xFilesFactor = 0.1
aggregationMethod = max

[sum]
pattern = \.sum$
xFilesFactor = 0
aggregationMethod = sum

[count]
pattern = \.count$
xFilesFactor = 0
aggregationMethod = sum

[count_legacy]
pattern = ^stats_counts.*
xFilesFactor = 0
aggregationMethod = sum

[default_average]
pattern = .*
xFilesFactor = 0.3
aggregationMethod = average
```

Could you please help me and tell where is the problem? I'm not quite sure. Sorry about that.

**Comment by torkelo** [comment]
if you have recently changed your storage schema file you need to rebuild your whipser files (or remove them and have then recreated)

**Comment by drptbl** [comment]
@torkelo Thanks for answer!
I've removed whole `whisper` folder from `/opt/graphite/storage/`. Will update tommorow after I check if that helped. Thank you!

**Comment by drptbl** [comment]
@torkelo @woodsaj 
Removal didn't help, sadly. I still have no idea what's going on. My `storage-schemas.conf` and `storage-aggregation.conf` files look fine.

![screen shot 2016-02-01 at 13 54 58](https://cloud.githubusercontent.com/assets/8177587/12717945/89193d2a-c8eb-11e5-9bb7-80d900b6fb46.png)
![screen shot 2016-02-01 at 13 55 25](https://cloud.githubusercontent.com/assets/8177587/12717944/8917bc48-c8eb-11e5-8fe6-5abd9aafeb98.png)

There are still `nulls` for "Last 6h" and "Last 12h", but "Last 6h" works and "Last 12h" doesn't.

**Comment by woodsaj** [comment]
your carbon config states that your datapoints are being sent every 10seconds and every 1minute the last 6points are averaged.
`retentions = 10s:6h,1min:6d,10min:1800d`

In your aggregation rules you state that when performing the 1minute rollups, at least 30% of points need to be non-null else the resultant value will be null.
`xFilesFactor = 0.3`

This means that you need to have at least 2 points every minute.

but your graph suggests that you are not sending data at regular intervals with each point being spaced 30minutes ore more.  

If you are not sending data at a regular interval, then it is not a good fit for timeseries data. 

So you can either use a more suitable database that handles event data, like elasticsearch. or you can change your xFilesFactor  to be 0

**Comment by drptbl** [comment]
@woodsaj 
Just wanted to let you know, that setting `xFilesFactor` to `0` fixed my issue.

I'm very thankful for your help, I was struggling with this issue for a long time. I owe you a big cup of beer :).

**Comment by rosarch** [comment]
I had the same issue and came across this site, followed the advise and now working for me as well - Thanks!

**Comment by Aakansha-Talati** [comment]
I am facing the same issue , I can view the data for last 24 hours but not beyond that! I changed the xFilesFactor to 0 but do I need to restart any service or something to incorporate these changes?

**Comment by JessMarSoriano** [comment]
I am facing the same issue. With our current setup, I can view data for 7days. Beyond that, there's no data for some servers (while we're sure that there's data) and others have data in the graphs. I'm about to change the value of xFilesFactor to 0 as well. Do I have to recreate the whisper files or is there a certain period that I have to wait before the changes to take effect? Thank you very much in advance!

storage-schemas.conf
[icinga2]
pattern = ^icinga2\.
retentions = 5m:31d, 1h:2y

storage-aggregation.conf 
[icinga2]
pattern = ^icinga2\.
xFilesFactor = 0.1

**Comment by generalbytes** [comment]
I had to set xFilesFactor to 0 and delete old whisper files.
