### ISSUE TITLE
Metric name suggestions are cut-off

### ISSUE THREAD

**Issue by pstibrany** [grafana/grafana#39025]
**What happened**: I was typing metric name into the expression field, and since I couldn't remember the name, I was hoping to see possible suggestions. Window with suggestions did appear, but since it only shows first part of very long metric name, it was not very helpful.

**What you expected to happen**: I hoped to be able to pick single metric name from the list.

**How to reproduce it (as minimally and precisely as possible)**: Type part of the metric name to expression field. Problem occurs with very long metric names.

<img width="1154" alt="Screenshot 2021-09-09 at 11 26 53" src="https://user-images.githubusercontent.com/895919/132660496-ee295021-fd79-4ccf-96f9-a6df3b81df9c.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.2.0-33417pre (cf83d55db9)
- Data source type & version: Cortex 1.10+
- OS Grafana is installed on: some linux I guess
- User OS & Browser: mac OS, Safari 14.1.2
- Grafana plugins: don't know
- Others:

**Comment by gabor** [comment]
hi @pstibrany , thanks for the report, i did some improvements there, please try them if they solve your problem:
- you can make the suggestion-window wider now by grabbing the lower-right corner with the mouse and resizing that window
- if you press <CONTROL>+<SPACE> while navigating the suggestion-window, it will open an extra "help" window, with the help-text for the given thing, and it will also show the full name of the thing. (there is also a ">" sign at the right end of the currently-selected suggestion, clicking on it is the same as pressing <CONTROL>+<SPACE>

**Comment by gabor** [comment]
i'll close this, if there is any other problem, just comment here, thanks!

**Comment by pstibrany** [comment]
Thank you. I confirm that I can now resize the suggestions window. But I'm not sure what you mean by pressing +... when I press `+` on the keyboard, it is added to the editor field. And I don't see any `+` button on the screen.

<img width="1948" alt="Screenshot 2021-09-14 at 08 56 14" src="https://user-images.githubusercontent.com/895919/133210060-772ed645-6b39-4ef7-8f28-4480c5c0d870.png">

**Comment by gabor** [comment]
@pstibrany i am sorry, i wrote `<CONTROL>+<SPACE>`, but i wrote it the wrong way so github did not display it correctly. i updated my previous comment to show it correctly.

for the ">" thing, see this screenshot:
<img width="457" alt="arrow" src="https://user-images.githubusercontent.com/51989/133217698-e2e7e5e8-eb77-41fe-9663-90d7633c2fe3.png">


the ">" symbol will only appear when you move the mouse to that place. clicking on it does the same as pressing `<CONTROL>+<SPACE>`.

**Comment by pstibrany** [comment]
Oh, I see. Ctrl+Space works, as well as hovering in that place. I think users will have hard time discovering either of these, and would suggest to always keep "help" window visible instead, as it is super useful.

<img width="1948" alt="Screenshot 2021-09-14 at 10 00 14" src="https://user-images.githubusercontent.com/895919/133219292-fc6e2f35-920d-409f-ac6b-50e310202db4.png">

**Comment by gabor** [comment]
thanks for the recommendation, i will look into it :+1:
