### ISSUE TITLE
Grafana with Active Directory / LDAP

### ISSUE THREAD

**Issue by JannickH91** [grafana/grafana#3904]
Hi. I'm setting up Grafana to work with Active Directory, using it's built in support. I have limited experience with them both, so i'm asking for a little help putting the configuration together. I have verified that i can connect to my AD server from the machine grafana is running on.

This is the current configuration that i am working on. http://pastebin.com/AJzrnMPQ

There is not too much documentation to go from (at least with my level of knowledge). But here is their configuration guide for ldap http://docs.grafana.org/installation/ldap/#single-bind-example.

If there is anyone out there with grafana/AD experience it would be greatly appreciated.

**Comment by JannickH91** [comment]
I figured out the problem. It was because i forgot to remove the ";" infront of "enabled = true" in the grafana.ini. Rookie mistake :)

**Comment by torkelo** [comment]
glad you solved it :)
