### ISSUE TITLE
Shorten silence URL

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana#39044]
### Discussed in https://github.com/grafana/grafana/discussions/39043

<div type='discussions-op-text'>

<sup>Originally posted by **a-mazed** September  9, 2021</sup>
Please add an option to shorten silence URL.

Right now, my silence URL in Slack alert message can be 560 characters long, and that's not the biggest value. It's not good at all.

Grafana v8.1.3 using NGAlert</div>

**Comment by dprokop** [comment]
@a-mazed I'm closing this now as you have already opened a discussion.
