### ISSUE TITLE
Time Picker — Months & Quarters Time Ranges

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#39052]
As a user I'd like to be able to visualize data around calendar-based time periods.  Currently, I need to do a significant amount of shifting and legwork to get close to being able to visualize something that's common in other analytical tools. Ex. View fiscal year to date, or compare last quarter to this quarter. 

<p></p>

<https://www.figma.com/file/gXypOQEb8yU21RzlxXy2QW/?node-id=1446%3A10772>

<p></p>

To accomplish this, the design adds the following to the existing time picker:

- Type-ahead search box to allow users to quickly filter down the long list of relative time ranges

- Info tooltip that appears any time a fiscally-based time period is selected. Tooltip displays the fiscal year start and end months and days.

- `Change time zone` button becomes `Change time settings`

- New button group to allow users to select whether to change the time zone or set the fiscal year start month.

- Time settings area closes automatically upon user setting any dropdown options. Or users can click `Change time settings` to close the panel.

- Users can also set time ranges with the following notations:

  - fy = fiscal year

  - fq = fiscal quarter

- Upon selecting an absolute time range, the forward/back arrows should continue to work as they do today - advancing or reversing the time by 1/2 of the set period. In other words, if user selects 01-Dec to 31-Dec, the back arrow sets the time picker to be 30 days in length, beginning 15 days before the original start date: 15-Nov to 15-Dec.

<p></p>

Note three items are inconsistent in the Figma file:

- The design system's tags are brighter and bolder than what is currently being used in production. Please use the existing production styles for the time zone indicator (UTC+03:00)

- The relative time range pick list has borders and rounded corners in the design system. Please use the existing production styles with no borders or corners.

- Also the clear search tag should mimic the right panel in production.

<p></p>

Lastly, a number of ideas were suggested, attempted, and eventually descoped. A larger revisit of the overall time picker design will be spun off into a separate effort. [This design document ](https://docs.google.com/document/d/1LlRk_dQEfJfMiAhPc6L7uwmgD_Dum5JcKDc3HGKR5YE/edit#heading=h.ve4du26wqsib)captures many of the ideas that were suggested. 

<p></p>

<p></p>

**Comment by torkelo** [comment]
Link to feature: https://grafana.productboard.com/feature-board/planning/features/8647676

**Comment by amy-super** [comment]
The new times for the list include:
Previous fiscal quarter
Previous fiscal year
This fiscal quarter
This fiscal quarter so far
This fiscal year
This fiscal year so far
