### ISSUE TITLE
Min Interval Query Option not working as expected with Graphite datasource

### ISSUE THREAD

**Issue by Styx13** [grafana/grafana#39055]
**What happened**:
When setting the "Min Interval" Query Option for a Graphite datasource, it does not seem to have any influence.
Looking at the query sent to the backend, it is the same whatever value you select for Min Interval.

**What you expected to happen**:
I would expect that the choice of Min Interval would calculate and override the number of datapoints requested to graphite in order to respect that Min interval.
i.e: I am currently looking at 1 week worth of data. Data on my datasource is collected at a 10 seconds resolution.
By default, Grafana will use the width of the screen to calculate the maximum number of datapoints and that will set the Interval.
In my case, this default calculation ends up with 2110 datapoints, which over a period of 1 week (1 week = 604800 seconds) means and interval of 286 seconds (rounded up to 300 for 5 minutes).
![image](https://user-images.githubusercontent.com/16089886/132752067-1b61a793-c171-4061-9d73-e42920725f3f.png)

Now I would like to change that min interval to be at 10 minutes. I would then set Min Interval to 10m and expect Grafana to calculate the max number of datapoints from that (which should be  604800  / 600 = 1008 datapoints). However when I do so, nothing happens and the max datapoints stays at 2110 = width of panel and if I look at the query sent to graphite I still see in it (&maxdatapoints=2110), even though as you can see in the screenshot, interval get set to 10 min.
![image](https://user-images.githubusercontent.com/16089886/132752006-e6cbdd6d-a16f-47f9-9605-ae65774e5923.png)

The only way I found to get the data at the interval I really want is to go and calculate myself the max number of datapoints:
![image](https://user-images.githubusercontent.com/16089886/132752337-ebcc5962-5e41-481c-a33c-eea67a696779.png)

**How to reproduce it (as minimally and precisely as possible)**:
See example described above.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.1.5
- Data source type & version: Graphite 0.9
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Firefox 91.0.2
- Grafana plugins: only the core ones
- Others:

**Comment by dprokop** [comment]
Min interval settings is not used by Graphite datasource, ref https://github.com/grafana/grafana/issues/21413#issuecomment-578487468
