### ISSUE TITLE
Add one click to select all with column filter

### ISSUE THREAD

**Issue by hanyuancheung** [grafana/grafana#39068]
Here is a feature issue.

### The Problem

- When we select some values or fields with column filter in a table, sometimes we'd like to select all of the filter results or something like that. 

### Proposed solution

- So, I prefer there should be a feature to add one click to select all with column filter.

**Comment by Rocksnake** [comment]
I think I can solve it, could you assign it to me?

**Comment by imReker** [comment]
> I think I can solve it, could you assign it to me?

Off topic but related issue: 
Set input focus to `filter values` textbox when column filter popup.

**Comment by AntoniusFirst** [comment]
Hi guys,

It will be great if you will add one checkbox to check all filtered values in the column filter. Could you clarify, can we expect this improvement?
