### ISSUE TITLE
Can't delete disabled query

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana#39075]
**What happened**:
After upgrading Grafana from 7.5.7 to 8.1.2 I can't delete disabled queries, previously used for alerting.
Getting an error when saving dashboard:
```
Validation failed
alert validation error: Alert on PanelId: 189 refers to query(B) that cannot be found
```
![image](https://user-images.githubusercontent.com/25726917/132826613-092cfc4a-77b4-45db-afe5-77ce7bb2a69a.png)

Console log

```
fetch.js:45 POST http://hostname:3000/api/dashboards/db/ 422 (Unprocessable Entity)
(anonymous) @ fetch.js:45
e._trySubscribe @ Observable.js:43
e.subscribe @ Observable.js:29
e.call @ mergeMap.js:27
e.subscribe @ Observable.js:24
t.connect @ ConnectableObservable.js:34
e.call @ refCount.js:19
e.subscribe @ Observable.js:24
e.call @ filter.js:15
e.subscribe @ Observable.js:24
e.call @ tap.js:18
e.subscribe @ Observable.js:24
c @ innerSubscribe.js:89
t._innerSub @ mergeMap.js:72
t._tryNext @ mergeMap.js:66
t._next @ mergeMap.js:49
t.next @ Subscriber.js:53
(anonymous) @ subscribeToArray.js:5
e._trySubscribe @ Observable.js:43
e.subscribe @ Observable.js:29
e.call @ mergeMap.js:27
e.subscribe @ Observable.js:24
e.call @ catchError.js:16
e.subscribe @ Observable.js:24
e.call @ takeUntil.js:16
e.subscribe @ Observable.js:24
e.call @ throwIfEmpty.js:18
e.subscribe @ Observable.js:24
(anonymous) @ backend_srv.ts:87
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ ResponseQueue.ts:30
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ ResponseQueue.ts:35
(anonymous) @ FetchQueueWorker.ts:54
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.notifyNext @ mergeMap.js:85
t._next @ innerSubscribe.js:14
t.next @ Subscriber.js:53
(anonymous) @ subscribeToArray.js:5
c @ innerSubscribe.js:91
t._innerSub @ mergeMap.js:72
t._tryNext @ mergeMap.js:66
t._next @ mergeMap.js:49
t.next @ Subscriber.js:53
t._next @ filter.js:38
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ FetchQueue.ts:76
(anonymous) @ FetchQueue.ts:55
t.__tryOrUnsub @ Subscriber.js:192
t.next @ Subscriber.js:130
t._next @ Subscriber.js:76
t.next @ Subscriber.js:53
t.next @ Subject.js:47
(anonymous) @ FetchQueue.ts:59
(anonymous) @ backend_srv.ts:92
e._trySubscribe @ Observable.js:43
e.subscribe @ Observable.js:29
e.call @ map.js:18
e.subscribe @ Observable.js:24
(anonymous) @ Observable.js:98
e.toPromise @ Observable.js:96
request @ backend_srv.ts:67
post @ backend_srv.ts:385
O @ actions.ts:205
(anonymous) @ useDashboardSave.tsx:17
(anonymous) @ useDashboardSave.tsx:23
(anonymous) @ useAsyncFn.js:20
onSubmit @ SaveDashboardModal.tsx:44
onSubmit @ SaveDashboardForm.tsx:25
(anonymous) @ useForm.ts:1059
async function (async)
(anonymous) @ useForm.ts:1046
Ue @ react-dom.production.min.js:52
$e @ react-dom.production.min.js:52
(anonymous) @ react-dom.production.min.js:53
Or @ react-dom.production.min.js:100
Er @ react-dom.production.min.js:101
(anonymous) @ react-dom.production.min.js:113
Ne @ react-dom.production.min.js:292
(anonymous) @ react-dom.production.min.js:50
jr @ react-dom.production.min.js:105
Zt @ react-dom.production.min.js:75
Xt @ react-dom.production.min.js:74
t.unstable_runWithPriority @ scheduler.production.min.js:18
Uo @ react-dom.production.min.js:122
Re @ react-dom.production.min.js:292
Kt @ react-dom.production.min.js:73
```

**What you expected to happen**:
Saved dashboard without unused queries

**How to reproduce it (as minimally and precisely as possible)**:

1. Create query at Grafana 7.5.7, disable it and use for alert
2. Upgrade Grafana up to 8.1.2
3. Enable option ngalert
4. Edit panel and remove disabled query
5. Press Save button and get error

**Comment by papagian** [comment]
This error is returned when legacy alerts are extracted by the [dashboard](https://github.com/grafana/grafana/blob/477d4197fba9c1a18e2cbacdfb5cc6487e4880dd/pkg/services/alerting/extractor.go) during dashboard updates.

I think that we shouldn't fail if the Grafana 8 alerts are enabled, given that the user cannot remove the legacy alert from the UI (it's invisible). However, this will allow to delete a disabled query referenced by the legacy alert which will be problematic if the legacy alerting will be re-enabled (the rule will error).
Another option would be not to extract at all the legacy alerts when the Grafana 8 alerts are enabled but this also suffers from the above problem.

**Comment by davidmparrott** [comment]
@a-mazed just wanted to let you know I've been able to reproduce this error locally and will be working on what we should do in this situation.

**Comment by davidmparrott** [comment]
@a-mazed Testing out this failure scenario, I see that this happens even if I do not enable NG alerting, and the problem is still present on main. I'll have to look into what's going on a little deeper.

**Comment by davidmparrott** [comment]
The error in question is present in v7.5.7 and guards against deleting queries that are used for alerting. The presence of the error, after you have upgraded, is to allow backwards compatibility. If we change this to allow you to delete this query, despite there being a legacy alerting condition using it, then as mentioned by @papagian , we break the ability to rollback. I would like to check with @grafana/alerting-squad before proposing a change that can break the rollback option.

**Comment by gotjosh** [comment]
@davidmparrott thanks for taking a look!

I think we should be a bit more aggressive at making the user understand what's going on and letting them proceed with the action (with caveats). 

Think about the use-case where rolling back is not an option or something you care about - you're happy with the new system and would like to continue using it forever. It's pretty cumbersome (and "not possible" in cloud) to roll back, delete that alert and then proceed to delete the query/panel without support intervention.

Because of that, I think we should simply remove the condition from the alert as we save and then let the user know what happen (e.g. we removed condition X from Y because we couldn't find query Z for each alert). Looking at:
https://github.com/grafana/grafana/blob/e904f423e4f8caf495c285e4fc28fbcc44638048/pkg/services/alerting/extractor.go#L165-L175

I believe we could just remove that alerting condition if we hit the branch on L172 and unified alerting is enabled. What do you think?

**Comment by davidmparrott** [comment]
@gotjosh I think we should do this as part of the deprecation of legacy alerting. Weighing the potential downsides against each other we have the case where a user is unable to rollback to their prior version and Grafana may be completely unusable for them vs having to leave an unused query hanging around until the legacy alerting is removed entirely. I think the former is a much bigger risk than the latter.

**Comment by armandgrillet** [comment]
> we should be a bit more aggressive at making the user understand what's going
Until deprecation of legacy alerting, could we do this? The current error does not provide reasons to let the user understand why the deletion is not possible.

**Comment by davidmparrott** [comment]
In the code path where we have found that a user is trying to remove a query referenced by a legacy alert, we could check if grafana 8 alerts are enabled and, if so, preserve the original error message but also append something like `legacy alerting queries are not able to be removed at this time in order to preserve the ability to rollback to previous versions of Grafana` perhaps?
