### ISSUE TITLE
Row groups / collapsable panels

### ISSUE THREAD

**Issue by bobrik** [grafana/grafana#3908]
I have a dashboard which shows statistics per server, roughly 20 graphs per machine. Rows are repeated per server in this dashboard. While it is very nice to use to look at a single server, it gets messy when you have several of them enabled. In the end, I want to enable some graphs in the row and only look at them.

Simple dashboard with 2 servers and 3 graphs for each:

![image](https://cloud.githubusercontent.com/assets/89186/12724587/7445369a-c906-11e5-829b-3cb1bd7fff5f.png)

Imagine now much fun I have with 20 graphs per server.

I see two options:
1. Implement rows in rows, so I can collapse them.
2. Allow panel collapsing.

**Comment by mtanda** [comment]
+1

**Comment by torkelo** [comment]
closing this, think that this is better solved by using template variables instead of collapsing rows/panels.  (so select the server you want using template variables instead of expanding/collapsing rows)
