### ISSUE TITLE
Create org unexpected behavior with admin API token

### ISSUE THREAD

**Issue by adamlwgriffiths** [grafana/grafana#3909]
I've made an admin API token and am attempting to use the API to programmatically create organisations, users and dashboards. I'm stuck at the first step.

I have the following settings:
```
allow_org_create	false
user_org	1
```

The following call results in access denied
```
POST /api/orgs HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer <api key>
Cache-Control: no-cache

{ "name":"Test" }
```

Results in:
```
{
    "message": "Access denied"
}
```

Changing:
```
user_org -1
```

Same response
```
{
    "message": "Access denied"
}
```

Changing
```
allow_org_create true
```

Suddenly response is success.

```
{
    "message": "Organization created",
    "orgId": 3
}
```

Changing
```
user_org 1
```

Has no effect and still permits organisations to be created - although I saw a `Failed to create organization` response at one point but I cannot recreate it anymore.

This indicates that the `user_org` limitations are not being applied due to the API token being for an admin, does it not? Unless the limitations are not being checked for.

The access denied response should be coming from this check https://github.com/grafana/grafana/blob/e38e8c740f90c41e01017875414b05c5ecf89375/pkg/api/org.go#L79
```
	if !c.IsSignedIn || (!setting.AllowUserOrgCreate && !c.IsGrafanaAdmin) {
		return ApiError(403, "Access denied", nil)
	}
```

But I would expect the Admin API token to not fall in here due to the `c.IsGrafanaAdmin`.
The only possible explanation I have, is that the Admin role is not correctly set for API keys?
Unless `IsSignedIn` is false for API keys?

**Comment by adamlwgriffiths** [comment]
Can confirm that using basic auth (`https://<admin>:<password>@site/api/orgs`) instead, allows creation of organisations with `allow_org_create false`

**Comment by woodsaj** [comment]
"GrafanaAdmin" is an attribute of a user. It is different to the "admin" role within an organisation.  A user can be a grafanaAdmin while still only having a "viewer" role on all orgs they are a member of.

There is currently no way to grant grafanaAdmin privileges to an apiKey.

**Comment by adamlwgriffiths** [comment]
Ok, so the role of Admin is actually within the context of an 'organisation', rather than a system level admin. I understand.

So the only way to perform administration tasks via the API is to use basic auth (http://user:pass@server) using the admin credentials?
