### ISSUE TITLE
Grafana v7.4.0 mangles times in x-axis for graphs for ad-hoc queries

### ISSUE THREAD

**Issue by dandua98** [grafana/grafana#39107]
**What happened**:

- Updated Grafana from v6.2.4 to v7.4.0, noticed that times (x-axis) for graphs for ad-hoc queries/explore tab were sometimes mangled together in full screen. This did not happen for v6.2.4.
- Was reproducible on the latest v7 release as of Sep 10, 2021 (*v7.5.10*)

![image](https://user-images.githubusercontent.com/24802378/132918171-d31e2048-df3b-4c53-bf46-863d7a198250.png)

**What you expected to happen**:
- Resizing the windows (and the reloading) until the axis appears as it should works (see the fixed graph below), but the axis should be properly scaled for all resolutions.
![image](https://user-images.githubusercontent.com/24802378/132918208-d360e56f-25d0-46e1-8e25-f3da32c0874e.png)

**How to reproduce it (as minimally and precisely as possible)**: -

**Anything else we need to know?**: Was reproducible on another browser (Firefox) without any extensions too.

**Environment**:
- Grafana version: 7.4.0, 7.5.10
- Data source type & version: Prometheus
- OS Grafana is installed on: -
- User OS & Browser: Chrome 93.0.4577.63 (Official Build) (x86_64), macOS Big Sur 11.4
- Grafana plugins: None
- Others: -

**Comment by torkelo** [comment]
This should be fixed in later versions of Grafana (8.0)
