### ISSUE TITLE
data source limit

### ISSUE THREAD

**Issue by m0nikasingh** [grafana/grafana#3910]
Hi,

Grafana doesn't allow to add more than 100 data sources.

Monika

**Comment by bergquist** [comment]
Just curious. How come you use more then 100 datasources?

**Comment by m0nikasingh** [comment]
Hi @bergquist ,

We have about 13 datasources per server and about 8 servers behind the VIP. So that makes it 104.
Figured out solution, can increase limit in file pkg/services/sqlstore/datasource.go

Thanks,
Monika

**Comment by bergquist** [comment]
What kind of datasource are you using? Im still curious about this setup :)

**Comment by m0nikasingh** [comment]
:)
We are running 13 (graphite) containers to isolation services.
Datasource here is web end point.
Example : "datasource_name --> graphite_webapp_url:port_number"
These services are running in 4 datacenter's.

So we have 2 servers behind each VIP (13) in all 4 datacenter's. That makes it 13*4*2 :)

**Comment by utkarshcmu** [comment]
Wow!!!

**Comment by sikadiamond** [comment]
I'm also running @ the limit of the available datasources....

**Comment by afelle1** [comment]
It appears this is already a configuration option in [grafana/conf/defaults.ini](https://github.com/grafana/grafana/blob/c6c07599c73ef1c5ca4e722f078b82e85ffc3c54/conf/defaults.ini).  Ran into this myself and going to check the following in my installation but worth checking yourself:
<pre>
 #################################### Usage Quotas ##########################
 [quota]
 enabled = false
 
 # limit number of dashboards per Org.
 org_dashboard = 100
</pre>

**Comment by sikadiamond** [comment]
I see, however, I need more datasources, not dashboards

**Comment by afelle1** [comment]
Yeah sorry about that I realized too late.  It looks like there is an [undocumented global_data_source setting](https://github.com/grafana/grafana/blob/56622ee2c6d030efb7b39433b1b1fc6f0e7250a4/pkg/setting/setting_quota.go) that looks like it should allow infinite data sources but still digging.

**Comment by afelle1** [comment]
So one thing I noticed is that you can create more than 100 data sources via the API, however the UI and API will only show 100.  After I started to delete some of the data sources, the others that weren't visible appeared, so unclear

**Comment by arnmishra** [comment]
Is there any goal of increasing the number of data sources to more than 100?

**Comment by rubycut** [comment]
+1

**Comment by rubycut** [comment]
@m0nikasingh , pull request is merged, can we close this issue?

**Comment by m0nikasingh** [comment]
Yes, Thank you :)
