### ISSUE TITLE
#39018 breaks Dockerfile in v8.1.x

### ISSUE THREAD

**Issue by jkreileder** [grafana/grafana#39108]
https://github.com/grafana/grafana/pull/39018 adds
```
COPY packages/grafana-schema packages/grafana-schema
```
to `Dockerfile` and `Dockerfile.ubuntu` but there is no `packages/grafana-schema` in v8.1.x.

**Comment by ivanahuckova** [comment]
+fyi @dsotirakis

**Comment by dsotirakis** [comment]
Hey @jkreileder, thanks for spotting that, this was auto-generated at some point, and I misplaced that. I'll remove it as not need it for now!
