### ISSUE TITLE
The client/user clock is used to resolve "now" and not the server/Grafana clock

### ISSUE THREAD

**Issue by hcbraun** [grafana/grafana#39110]
**What happened:**
When using "now" / relative time ranges the clock of the client is used. If the clock of the local client is skewed the panels will show an incorrect time range.

**What you expected to happen:**
The server clock should be used to resolve "now"

**How to reproduce it (as minimally and precisely as possible): -**
Set the clock of a client to 5 minutes in the past. Open a dashboard with time range "last 15 minutes". Instead of the panel showing the last 15 minutes, the panel shows from the last 20 minutes to last 5 minutes.

**Environment:**
Grafana version: 8.0.3
User OS & Browser: Google Chrome 93.0.3577.63 (arm64), macOS 11.5.2 
Grafana plugins: None
Data source: Prometheus

**Comment by torkelo** [comment]
We have always used the users time, that has been what most expect. Users should see the time that their computer is set to, it's their computer who is visualizing and requesting the data

> . If the clock of the local client is skewed the panels will show an incorrect time range. 

Same will be true if server time is off

**Comment by hcbraun** [comment]
I would disagree. As an admin I can control and ensure the correctness of the server clock Grafana is running on. I can't do the same for every client.

This is not what a user expects when selecting timerange "now": 
> Users should see the time that their computer is set to, it's their computer who is visualizing and requesting the data
