### ISSUE TITLE
Link on dashboard to itself with different from parameter is not working

### ISSUE THREAD

**Issue by tillsteinbach** [grafana/grafana#39122]
**What happened**:
On a dashboard I created several links to itself with changing from/to parameters. The purpose is to allow the user to select predefined intervals such as "last year", "last month", "last week".
When I click on those the URL changes, but the selected interval does not recognize the new parameters in the URL. When I open the link in a new window everything is fine.

**What you expected to happen**:
Link will reload the same dashboard but with new time interval

**How to reproduce it (as minimally and precisely as possible)**:
Create empty dashboard, add link to self (/dashboardid?from=now-1w), klick on link and check timeinterval

**Anything else we need to know?**:
no

**Environment**:
- Grafana version: 8.1.3
- Data source type & version: irrelevant
- OS Grafana is installed on: Official grafana docker image
- User OS & Browser: checked on OS X with Safari and Firefox and on iOS

**Comment by Elfo404** [comment]
Hello @tillsteinbach thanks for reporting this.

I'm able to reproduce it when I do not set a `to` param as well. i think this should be still considered a bug, but if you try to set your link to `/{dashboardid}?from=now-1w&to=now` it should work as expected. can you confirm?

**Comment by tillsteinbach** [comment]
Thanks, your workaround is working flawlessly. From my perspective this makes it a low priority bug!
Unfortunately I found another one: https://github.com/grafana/grafana/issues/39199

**Comment by torkelo** [comment]
yes, both from & to are needed to update time range
