### ISSUE TITLE
Grafana using "1y" as auto time interval - not working with influxDB

### ISSUE THREAD

**Issue by groblus** [grafana/grafana#3912]
When groupby time(auto) is used, grafana creates a query with "1y" which is not understood by influxdb corretly.
Query is:
`SELECT mean("usage_idle") FROM "cpu" WHERE "cpu" = 'cpu-total' AND "machinetype" =~ /node$/ AND time > now() - 12h GROUP BY time(1y), "host" fill(none)`

And response is:
`
{
  "error": "error parsing query: found y, expected ) at line 1, char 131",
  "message": "error parsing query: found y, expected ) at line 1, char 131"
}
`
It happend while using "auto" as time interval.

**Comment by torkelo** [comment]
you must be using panel repeat, make sure you have specified a min span (next to panel repeat option in general panel tab)

**Comment by adrianlzt** [comment]
I have found the same issue zomming out enough.

InfluxDB don't accept 'y': https://docs.influxdata.com/influxdb/v0.10/query_language/spec/#durations

**Comment by adrianlzt** [comment]
This is the _culprit_: https://github.com/grafana/grafana/blob/master/public/app/core/utils/kbn.js#L98
