### ISSUE TITLE
(Shorten) URL broken when changing timerange while having a variable with spaces in the value

### ISSUE THREAD

**Issue by rlueckl** [grafana/grafana#39131]
**What happened**: having variables with values with space in the URL, then changing the time range replaces the `space` with `+` in the URL. Copy-pasting this URL seems to work, but creating a short URL and using that breaks the variable.

**What you expected to happen**: the spaces in the URL should not be replaced with `+`.

**How to reproduce it (as minimally and precisely as possible)**:
 * create a new dashboard
 * create a variable where the values have spaces in them (for example if your datasources are called "Graphite QA" and "Graphite Live" or create a simple custom variable with values like "test 1", "foo bar", etc.)
 * switch between the variable values a few times, so they appear in the URL bar of the browser (`&var-query0=test 1`)
 * change the time range with the timepicker
 * the URL changes from `&var-query0=test 1` to `&var-query0=test+1`
 * try sharing the dashboard with the "Shorten URL" function
 * the shortened URL takes the `+` sign literally and tries to use `test+1` as value instead of `test 1`

Copy-pasting the long URL with the plus signs works, the browser seems to recognize that it should be a space, but when redirecting from a short URL it breaks.

See screenshots:

Step 3: after switching the variable back & forth, the value appears in the URL:
![grafana_2](https://user-images.githubusercontent.com/10848041/133080498-0978ddb7-b8a6-4f17-a77d-ecd188985509.png)

Step 4-5: changing the time range changes the value in the URL:
![grafana_copy_pasted](https://user-images.githubusercontent.com/10848041/133079451-705afa2b-b4b0-4b66-9b59-e824a057977c.png)

Step 7: the resolved short URL puts the plus sign in the value:
![grafana_shorturl_resolved](https://user-images.githubusercontent.com/10848041/133079020-eb9720fc-b23e-4b99-9621-92b11a2d2687.png)

Depending on the dashboard I sometimes get the following error (the data source variable is used on panels):
![grafana_error](https://user-images.githubusercontent.com/10848041/133079975-3ec6b0a6-e30c-4b46-a46c-2197ef4ef8a3.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2, but I've seen it happen on 8.0.6
- Data source type & version: n/a
- OS Grafana is installed on: official Grafana Docker image running in Kubernetes
- User OS & Browser: Linux Mint, tested with Firefox 91.0.2, 92.0 and Chromium 93.0.4577.63
- Grafana plugins: n/a
- Others: n/a

**Comment by hugohaggmark** [comment]
Hi @rlueckl and thanks for reporting this issue!
Confirmed at: 
https://play.grafana.org/d/OvIEl4H7z/shorten-url-broken-when-changing-timerange-while-having-a-variable-with-spaces-in-the-value-39131?orgId=1&var-custom=a+value+with+spaces&from=now-5m&to=now

Failing short url:
https://play.grafana.org/goto/Tt9__4H7z?orgId=1

**Comment by rlueckl** [comment]
Thank you for quickly resolving the issue!
Can we expect the fix in a bugfix-release (8.1.6 maybe?) or 8.2?

**Comment by hugohaggmark** [comment]
Forgot to back port this to 8.2. Thanks for the reminder @rlueckl 👍

**Comment by hugohaggmark** [comment]
This is the issue 🙈 , the PR was backported to 8.2. Ooh Mondays
