### ISSUE TITLE
Authorization getting failed with the current version

### ISSUE THREAD

**Issue by sunil-jhamnani** [grafana/grafana#3914]
Hi @torkelo 

I am using the latest version of Grafana and it seems like its giving error of Unauthorized user every time. I am running this docker command:
_docker run -d -p 3000:3000 -v /home/sitespeed/data/grafana:/var/lib/grafana -e "GF_SECURITY_ADMIN_USER=superuser" -e "GF_SECURITY_ADMIN_PASSWORD=strongpassword" --name grafana --restart="always" grafana/grafana_

But the authorization is working fine with the development version _grafana/grafana:develop_

Please let me know if there are any extra parameters to be added while running this version.

Some extra information I collected:

- In /var/logs/grafana.log it shows the environment variables are changed successfully.
- If I run the command without the admin cred. then also the default cred. are not working. As far as I know the default cred. are admin-admin(let me know it they are changed).

Thanks in advance

**Comment by torkelo** [comment]
it works for me when I test that command. 

I think you must have an existing grafana database in /home/sitespeed/data/grafana , the admin user password is only set if the admin user does not exist, so if you have an existing grafana database with a admin user already the config option has no effect
