### ISSUE TITLE
Alerting: Improve UI in alerting notification policies

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#39143]
For users new to alerting (grafana hosted alerting in particular) some details in UI could be confusing or at least not informative. 
There are few really small things that could improve the user experience I find useful to do.
Here is a screenshot of a fairly common configuration of notification policies

![image](https://user-images.githubusercontent.com/25988953/133105234-9378cda2-b2e1-466b-b363-fd35f5387189.png)

As you can see, there are dummy `-` for all timings settings. However, according to the documentation as well as the description of each field, there is a concrete value behind that dash. It would be great if we can display a concrete value rather than meaningless hyphen. 
- In the case of root notification policy I would suggest to specify the default values
- In the case of routing config, I think it makes sense to mention that the value we display comes from the default policy.

The same is applicable to the "group by" values. The default grouping rule is to [put all a alerts in a single group](https://github.com/grafana/grafana/blob/d8d014042fcd7fb241bf7a3d5c86a2bf150dd9c4/docs/sources/alerting/unified-alerting/notification-policies.md#root-policy-fields), which may be not obvious for the users. I think it is worth mentioning that explicitly.

Also, there is a tiny layout issue (I tested in Firefox 92, Windows).
<details><summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/25988953/133107409-daf098ae-31ba-478c-b451-dc30ffae584a.png)

</details>

**Comment by peterholmberg** [comment]
@oanamangiurea can you have a look at this?

**Comment by oanamangiurea** [comment]
@yuri-tceretian @peterholmberg Thanks, these are good suggestions.

**Comment by gotjosh** [comment]
There's one more thing to address here:

There's a very special meaning for `...` within the `group_by` field. It means, "every set of unique labels is its own group" or one group per alert.

I'd love if we could find a way to make this a bit more obvious within the UI and whether it makes sense to highlight this within the UI somehow - it seems to be a deep source of confusion for users where they expect no grouping to be each alert in its group as oppose to one single group.

**Comment by oanamangiurea** [comment]
Pinging @jessover9000 to have a look at the issue

**Comment by gillesdemey** [comment]
Fixed in https://github.com/grafana/grafana/pull/61952
