### ISSUE TITLE
Alerting: embedded Alertmanager logs are not respecting log level

### ISSUE THREAD

**Issue by dafydd-t** [grafana/grafana#39146]
**What happened**:

Running grafana with UA enabled and log.level set to `info`. We are seeing lots of debug level logs in stdout. Looking at an example log line, it seems that some mistake in log formatting means a debug level log is desired.

[Link to some example logs](https://admin-ops-us-east-0.grafana.net/grafana/explore?orgId=1&left=%5B%221631542512858%22,%221631549712858%22,%22loki-ops%22,%7B%22expr%22:%22%7Bcluster%3D%5C%22prod-us-central-0%5C%22,%20slug%3D%5C%22alertingops%5C%22,%20level!%3D%5C%22debug%5C%22%7D%22%7D%5D)

example snippet":
```
lvl=info msg="level=debug component=dispatcher aggrGroup=\"{}/{rule_uid=\\\"<uid>\\\"}:{}\" msg=flushing alerts=\"[CDN Synthetics checks alert[<uid>][resolved]]\""
```

**What you expected to happen**:

no logs with `level=debug` to appear in logs when `log.level=info`.

**How to reproduce it (as minimally and precisely as possible)**:

- create Grafana instance
- enable ngalert feature toggle

**Anything else we need to know?**:

**Environment**:
- Grafana version: grafana-enterprise:8.2.0-33761pre (grafana cloud)
- Data source type & version: NA
- OS Grafana is installed on: linux
- User OS & Browser: NA
- Grafana plugins: NA
- Others: NA

**Comment by gotjosh** [comment]
This is a known problem 😭  -- The problem here is that the Alertmanager components use go-kit logger but we use a different logger. I wrote a shim that translates gokit fmt to the Grafana logger but is not able to differentiate levels.

**Comment by dafydd-t** [comment]
Oh, that's a shame. These logs add a significant volume to our HG instance log output, so I think it's important that we reduce them to an appropriate level.

I don't think this blocks the rollout, but I think it's important the longer term.
