### ISSUE TITLE
Filter for value with extracted labels

### ISSUE THREAD

**Issue by sandstrom** [grafana/grafana#39168]
**What happened**:

Clicking "Filter for value" on extracted labels doesn't work. The modified query assume it's a regular label (which it isn't).

**What you expected to happen**:

Expected query to be modified appropriately (i.e. by inserting a filter after the `json` pipeline step).

**How to reproduce it**:

See these two images on how to reproduce.

#### Before

*Click 'filter for value' (plus sign) next to "Company ID" field.*

![before](https://user-images.githubusercontent.com/122287/133228160-b8582387-3315-4521-8844-c976ec22af49.png)

#### After
![after](https://user-images.githubusercontent.com/122287/133228181-a838e9d9-0139-4e16-b8e2-71c8b69aa6eb.png)

**Anything else we need to know?**:

Being able to filter on extracted values is very useful to grab e.g. all log lines with a particular trace-id / request-id. See also https://github.com/grafana/grafana/issues/20166#issuecomment-844913096

**Environment**:
- Grafana version: Grafana v7.5.3 (3e3cf4dc60)
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Chrome

**Comment by ifrost** [comment]
Should be fixed by #38542. Please use the latest version.

**Comment by sandstrom** [comment]
thanks @ifrost 🎉
