### ISSUE TITLE
CloudMonitoring: Duplicate time series when querying Redis using MQL

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#39162]
**What happened**:
Client reporting duplicate time series for Cloud Monitoring/Stackdriver query in Grafana. Grafana shows three time series for the metric, which means they get three separate stats

**What you expected to happen**:
Not to see duplicates

**How to reproduce it (as minimally and precisely as possible)**:
Use this MQL query: 
```
fetch redis_instance
| metric 'redis.googleapis.com/stats/memory/usage'
| filter (metric. role == 'primary')
| every 1m
```

**Anything else we need to know?**:
Client not sure if there is something they can do in the query to fix this, as the exact same query in the Cloud Console seems to work fine, but in Grafana, this happens. Client aren't seeing this problem with Cloud SQL metrics, so far they've only seen it on a new Memorystore dashboard they built.

Issue was reported over email by our contact person at Google.

**Comment by sunker** [comment]
Asked to customer to provide: 
**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

Also asked if the same issue appears when querying memory usage for redis using the visual query builder.

**Comment by Rylon** [comment]
I'm the customer that raised this originally with Google, and they have asked me to provide the information above.

I can confirm that I'm seeing this via the Cloud Monitoring / Stackdriver data source for both Cloud SQL and Memorystore. I've attached a screenshot of what we see. If the time period is set to "1 hour" then the data appears correct, but setting it to "Last 24 hours" or more tends to add multiple time series to the panel where there should only be one?

![CleanShot 2021-07-23 at 8 10 23](https://user-images.githubusercontent.com/438452/134540813-a1a7a357-71af-46d6-aabd-3e8fab13362e.png)

Grafana version: Grafana v8.1.2 (103f8fa094)
Data source type & version: Google Cloud Monitoring (version is whatever shipped with Grafana 8.1.2?)
OS Grafana is installed on: Ubuntu 18.04 LTS
User OS & Browser: macOS 11.6 using Safari 15.0 (a colleague also tested from macOS 11.6 using Firefox 92.0)

**Comment by sunker** [comment]
Thanks @Rylon. Could you please also paste in the result that was passed from the backend to the frontend? To do so, click `Query Inspector` > `Refresh` > `+ Expand all` > `Copy to clipboard` and then paste as a new comment in this issue.

**Comment by Rylon** [comment]
@sunker Please find attached.
[query_inspector_json.txt](https://github.com/grafana/grafana/files/7244577/query_inspector_json.txt)

**Comment by sunker** [comment]
Thanks @Rylon. Using the json you attached, I'm not able to reproduce this. I'm only seeing one time series in the UI. 

Are you sure you're on Grafana v8.1.2? Judging by the [image](https://user-images.githubusercontent.com/438452/134540813-a1a7a357-71af-46d6-aabd-3e8fab13362e.png) that you've posted, it looks like an older version of CloudMonitoring that was prior to Grafana 8.0.

**Comment by Rylon** [comment]
Hi @sunker yeah definitely on that version
![CleanShot 2021-09-30 at 3 03 42](https://user-images.githubusercontent.com/438452/135470314-c8de76bd-2fca-48fb-a063-4c1c0776290d.png)
:

**Comment by sunker** [comment]
![Screenshot from 2021-10-04 11-26-31](https://user-images.githubusercontent.com/2388950/135827309-47e70114-08c9-42e9-8e0d-b0efee10ad5f.png)

This is what the cloud monitoring query editor looks like in 8.1.x. Any chance you can also share your dashboard?

**Comment by Rylon** [comment]
Hi @sunker does it do it if you change the dashboard time period to 24 hours or more? I'll get a JSOn dump of the dashboard itself later today.

**Comment by Rylon** [comment]
Hi again @sunker please find attached the dashboard:

[dashboard.json.txt](https://github.com/grafana/grafana/files/7279625/dashboard.json.txt)

I've also included a screenshot showing normally behaviour when set to the last 3 hours:

![3-hours](https://user-images.githubusercontent.com/438452/135886767-35426b9b-7e22-449c-93ac-d83216f9e5a8.png)

Setting it to a higher value such as last 2 days shows duplicate time series:

![2-days](https://user-images.githubusercontent.com/438452/135886771-50622f2c-b6e4-4abd-9dc9-4e804ac7cc0d.png)

And finally, here's a screen recording of the issue:

https://user-images.githubusercontent.com/438452/135886779-b8ff900a-44c6-4ac0-88d0-dc8ea9829587.mp4

Thanks!

**Comment by sunker** [comment]
Thanks for detailed description! 

I've now setup an instance in redis. Unfortunately, I'm still not able to reproduce the problem. I'm only seeing one timeseries in the graph/stat no matter what time range I use. 

I'm gonna ask you to do one more check if possible. If in the time series panel, you should be able to right click on the line in the graph and see a context menu. One of the options should be View in metrics explorer. Click on that option. If you're in the stat panel you should be able to click on the stat itself and it should open the metrics explorer in GCP in another tab. Please do this for the 3 hour time range that displays the expected behavior **and** for the 2 days time range that shows the unexpected behavior. Just want to make sure we're not seeing the same behavior in GCP.   
![Screenshot from 2021-11-02 08-35-56](https://user-images.githubusercontent.com/2388950/139805156-58db4b3e-4097-4933-9a92-3adaf45b2738.png)

Thanks!

**Comment by Rylon** [comment]
Hi @sunker glad to hear you can reproduce it! Sounds like a tricky one to replicate, but happy you've got a theory.

Does this mean further work is needed in Grafana to handle this properly? In the meantime, how should I modify the original MQL query to "play nicely" with this?

Thanks again!

**Comment by sunker** [comment]
>In the meantime, how should I modify the original MQL query to "play nicely" with this?

You should be able to get rid of the duplicated series by increasing the duration in the query. I can't say which exact duration to use because it depends on what time range you're using, but try to increase it to `every 5m`. 

[This](https://github.com/grafana/grafana/pull/41302) fix will be merged today and it will also go into our next patch release some time next week. 

Thanks for finding this and help to repro @Rylon!

**Comment by Rylon** [comment]
Thanks for sticking with it @sunker :) I'll keep an eye on that patch and update our Grafana as soon as it's available 👍

**Comment by sunker** [comment]
>This fix will be merged today and it will also go into our next patch release some time next week.

@Rylon I messed up. Added to 8.4.2 patch milestone to the PR, but forgot to add the `backport` label so the fix never made it into the patch release. I will be released in 8.3.0 though. The beta is being released Monday next week. Terribly sorry for this!

**Comment by Rylon** [comment]
No worries @sunker thanks for the efforts so far! Is it possible to edit the changeling to reflect that the patch didn't make it yet? Thanks :)

**Comment by Rylon** [comment]
I deployed v8.3.1 today and I can confirm that the problem has been solved 🥳

Thanks again for your efforts @sunker !
