### ISSUE TITLE
1 of 1+ datasources down => can't draw a graph

### ISSUE THREAD

**Issue by iangelov** [grafana/grafana#3916]
Hi guys - sorry for the terse subject, I'll explain the issue in more detail here.

First of all - thanks for your great work, Grafana's really allowing us to have a different perspective of the setups that we're running.

Now, on to the problem - we're using multiple Prometheus servers and our data is spanning across them. Our dashboards are using templates and we've added the same queries (with one or more variables from the template) against the different data sources. If all of the Prometheus servers are up, we're receiving the expected result - the data is taken from the relevant server (only one of the servers actually returns data) and drawn. During a short maintenance we noticed that this is not really the case if a single Prometheus data source is down, even though our query was able to return data from one of the servers.

Why do I think that this is an issue - my belief is that such issues are going to occur more and more often as people are starting to use Prometheus more - since Prometheus is designed to be decentralised. Now, federation is an obvious way to work around this - but in our case the amount of data is such that we can't really scale vertically anymore.

How can this be solved - potentially by having the ability to group data sources (this prevents repetition), and definitely by being able to handle a situation in which one or more of the data sources is unavailable.

What are your thoughts on this?

**Comment by torkelo** [comment]
not sure I understand, do you have a single graph that queries many Prometheus instances? Or a template variable that is filled with values from many instances (not supported in grafana, so not sure I understand how you do that).

**Comment by iangelov** [comment]
Sorry about that being unclear - we have a single graph that queries multiple datasources.

**Comment by torkelo** [comment]
closing as it's similar to this https://github.com/grafana/grafana/issues/4453
