### ISSUE TITLE
Dashboard app information architecture clarity improvements

### ISSUE THREAD

**Issue by lukasztyrala** [grafana/grafana#39169]
### Background

Currently, it is not clear what is the interplay of home, dashboards and plus icons:
- People consider Dashboards as one of the apps and a space to which they navigate, expecting the space to hold features related to browsing and managing dashboards.
- We have more resources than just dashboards, and folders that can be added, but the add icon serves only the dashboards' features.
- It is confusing to navigate to the homepage via the Dashboards app icon, and the home dashboard is presented as one of the dashboards in the General folder, but it is not rendered in the folder view.
- In addition, the search view is the browsing feature for dashboards, but with the future introduction of unified search, we cannot rely on search to be the browsing list for dashboards.
- All the above impact the new navigation project, and the information architecture needs to be fixed.

### Information architecture improvements relate to few changes:

- [ ] **Change home dashboard title (icon + name) to improve the clarity of information architecture**

<img width="1668" alt="home-title-icon" src="https://user-images.githubusercontent.com/141744/133234706-e0547469-88ce-47f0-98ed-fd7439f46081.png">

- [ ] **Rename Dashboard app home tab from Manage to Browse**

<img width="1249" alt="manage-to-browse" src="https://user-images.githubusercontent.com/141744/133234886-12299e7a-1693-42e5-9b1d-99b33e880375.png">

- [ ] **Remove Home dashboard link from Dashboard icon in the navbar (flyout menu on hover)**

<img width="598" alt="no-home-in-dashboard-menu" src="https://user-images.githubusercontent.com/141744/133235030-ec80bf23-377c-462e-bb5e-8771595ed3ff.png">

- [ ] **Remove Add icon from the navbar**

<img width="486" alt="add-icon-removed" src="https://user-images.githubusercontent.com/141744/133235128-443822dc-2115-4989-adb6-c74c803b9b3e.png">

Removing add icon from the navbar is related to the flyout menu redesign by @VesnaDean as we can consider adding the most important action to the flyout menu.

An alternative is to treat add an icon as a holder of a general resource add a shortcut (if we do, it should have an add data source, add a plugin, add a report, add alert, etc.).

### Design files

[**Figma file**](https://www.figma.com/file/esk6QuF0SSt8jY2UsggXJp/?node-id=923%3A11515) with proposed changes.

**Comment by torkelo** [comment]
I am missing a way to navigate the home dashboard (that can be user configured or the default)

> Change home dashboard title (icon + name) to improve the clarity of information architecture

Change it to what? in the designs, I cannot see any way to navigate to the home dashboard. 

We need an easy way for users to navigate their home dashboard, this can be different from Grafana home, or dashboards section home. The only option I can think of is for the dashboards section to have a "Home dashboard" sub-menu option.
