### ISSUE TITLE
ngAlert: When I delete a folder, my alerts are deleted without warning

### ISSUE THREAD

**Issue by pkolyvas** [grafana/grafana#39175]
## What happened
When testing Grafana 8 alerts out for production readiness we discovered that when you delete a folder of dashboards you are not warned that the alerts contained in that folder will also be deleted. 

## What you expected to happen
When I try to delete a folder which contains library panels I'm unable to delete the folder if it contains library panels which are in use. 

![Screen Shot 2021-09-14 at 8 46 38 AM](https://user-images.githubusercontent.com/43178667/133252068-52826a68-a975-4401-a485-e86515b43817.png)

## How to reproduce it (as minimally and precisely as possible)
1. Create an alert in any folder
2. Attach it to a panel in another folder
3. Delete the folder which contains the alert

## Anything else we need to know?

The crux of this issue is that, from the user perspective, the alerts exist in a folder, and yet there's no way when browsing folders to understand how many alerts might be present.

**Environment**:
- Grafana version: 8.2.x (docker main branch build - current)
- Data source type & version: N/A
- User OS & Browser: Max OS 11.7 & Safari Tech Preview (same on all browsers)
- Grafana plugins: N/A

**Comment by papagian** [comment]
The respective endpoint [accepts](https://github.com/grafana/grafana/pull/36427) an optional query parameter `forceDeleteRules`. If it's `false` and the folder has Grafana 8 Alerts the request will fail with 400 Bad Request folder contains alert rules. Therefore  the frontend should be updated ([here](https://github.com/grafana/grafana/blob/92b5baba55e42c9898a1cbf38bd083b36063d221/public/app/features/folders/state/actions.ts#L34) and [here](https://github.com/grafana/grafana/blob/92b5baba55e42c9898a1cbf38bd083b36063d221/public/app/features/manage-dashboards/state/actions.ts#L216)) to set this flag to `false`.
