### ISSUE TITLE
Graph panel: When no samples exist for the right hand side, interpolate one.

### ISSUE THREAD

**Issue by rburchell** [grafana/grafana#3917]
I have metrics in InfluxDB for a set of fairly static metrics. Think about things like disk space used percentage - it doesn't change very often. I added an optimization to my reporter to not report metrics unless they changed, thinking that this would help reduce the needed storage load. However, instead, I got empty gaps in the graph on the rightmost side until a new sample appeared, which is absolutely not what I wanted -- so now I'm back to shoving metrics in on a regular basis even if they haven't changed.

I think this is inconsistent: the graph (when two samples appear in the middle of the graphed range) appear interpolates the missing data between those positions. I'd think it would make sense to anticipate this for a future time sample too in many cases. Admittedly, this may not make sense for all types of graphs. Perhaps it also makes sense to display that sample differently, somehow, too.

**Comment by torkelo** [comment]
you can control how missing data should be handled using InfluxDB's fill() function , for example fill(0) or fill(null),   you can also control how Grafana should display null values via the Null point mode option in graph options (display styles tab), set this option to `connected` to ignore null values (this will remove the gaps in the graph and connect points)

**Comment by rburchell** [comment]
Oh, thanks for the hint. I'll have a look into that.

Can I suggest that it might be a good idea to talk about this problem somewhere in the documentation, mentioning that there's typically ways to solve it in the data source? Because I did go looking before filing this, but clearly didn't know where to go looking :)
