### ISSUE TITLE
Alerts create invalid Annotations

### ISSUE THREAD

**Issue by fsperling** [grafana/grafana#39184]
**What happened**:
I exported Annotations via the Grafana API.
I tried to create the same Annotations again on a different Grafana instance using the Grafana API.
It fails with: 400    { "message": "Failed to save annotation" }

**What you expected to happen**:
I can export and import Annotations with the API.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard panel. Create an alert. When the alert condition is reached it creates an annotation and another one when the alert is resolved.
Those annotations have an empty text field.

For the Grafana API the text field is mandatory.
Annotations created by an Alert can not be exported and then re-imported via the API because of an empty mandatory field.

Example of such an Annotation:
`{
  "id": 678829,
  "alertId": 986,
  "alertName": "VictoriaMetrics Ingress Success Rate",
  "dashboardId": 804,
  "panelId": 10,
  "userId": 0,
  "newState": "ok",
  "prevState": "pending",
  "created": 1631608940293,
  "updated": 1631608940293,
  "time": 1631608940284,
  "timeEnd": 1631608940284,
  "text": "",
  "tags": [],
  "login": "",
  "email": "",
  "avatarUrl": "",
  "data": {}
}`

**Environment**:
- Grafana version: 8.x.x
- OS Grafana is installed on: container running in k8s

**Comment by torkelo** [comment]
Alert annotations can only be created by the alerting engine and cannot be imported/exported via the http api

**Comment by fsperling** [comment]
It would be good to document that there are basically two kinds of annotations.
I wasted quite a bit of time figuring out that I get normal and alert annotations from the API (and can't create alert annotations via the API).

https://grafana.com/docs/grafana/latest/http_api/annotations/
