### ISSUE TITLE
CloudWatch Metric Plugin supports graphing Contributor Insight Metrics with INSIGHT_RULE_METRIC() math function

### ISSUE THREAD

**Issue by mnako1** [grafana/grafana#39191]
### Discussed in https://github.com/grafana/grafana/discussions/39190

<div type='discussions-op-text'>

<sup>Originally posted by **mnako1** September 14, 2021</sup>
CloudWatch Contributor Insights is a feature of CloudWatch which provides streaming TopN analysis of high cardinality time series dimensions.  Customers use CloudWatch Contributor Insights as a cost effective tool for TopN, "Top Talker" and "Most Impact" streaming time series analysis.   

Customer are generally able to graph metrics that describe their Contributor Insight "Rules" using the Math function "INSIGHT_RULE_METRIC(ruleName, metricName)" in an expression.   

This INSIGHT_RULE_METRIC() function is not working in the CloudWatch Grafana datasource plugin however because the "Period" parameter is not being set in the GetMetricData MetricDataQuery object for this expressions.  For most math functions, setting the "Period" parameter on each MetricDataQuery object is not required, however it is required for the "INSIGHT_RULE_METRIC" math function.  

Suggested solution:
  Set the "MetricDataQuery" "Period" Parameter to the Query Period.  

The INSIGHT_RULE_METRIC() Function also requires an additional IAM permissions.  The following documentation should be udpated to add access permissions for  "cloudwatch:GetInsightRuleReport".   

Grafana Docs to update: https://grafana.com/docs/grafana/next/datasources/aws-cloudwatch/ 

AWS Documentation:  
https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/ContributorInsights-GraphReportData.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html
https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_MetricDataQuery.html

</div>

**Comment by sunker** [comment]
Thanks for creating this issue @mnako1. 

> Suggested solution:
> Set the "MetricDataQuery" "Period" Parameter to the Query Period.

Will this work for any math expression? What if a period is already specified in the expression, e.g `SEARCH('{"AWS/EC2","InstanceId"} MetricName="CPUUtilization"', 'Average', 300)`. Which period would be used then - the one that is specified in the math expression or the one that is set on the MetricDataQuery object?

**Comment by mnako1** [comment]
> Thanks for creating this issue @mnako1.
> 
> > Suggested solution:
> > Set the "MetricDataQuery" "Period" Parameter to the Query Period.
> 
> Will this work for any math expression? What if a period is already specified in the expression, e.g `SEARCH('{"AWS/EC2","InstanceId"} MetricName="CPUUtilization"', 'Average', 300)`. Which period would be used then - the one that is specified in the math expression or the one that is set on the MetricDataQuery object?

Yes. the "MetricDataQuery" "Period" can be set for any Expression.  The SEARCH() math function is unique in that it always uses the period from the function itself, but it is still safe to set the "MetricDataQuery" "Period".
