### ISSUE TITLE
Link to same page with different query parameters does not work

### ISSUE THREAD

**Issue by tillsteinbach** [grafana/grafana#39199]
**What happened**:
"?from=now-1w&to=now" is valid URL used in a link to open the same dashboard with different time interval. Same applies e.g. if you want to link to the currently open dashboard with different variables. Unfortunately grafana adds "http://baseurl/" in front of the link and makes this very simple method to link to the same page impossible

**What you expected to happen**:
Link with "?from=now-1w&to=now" in the html

**How to reproduce it (as minimally and precisely as possible)**:
create dashboard and add a link only containing "?from=now-1w&to=now". Expectation would be a link to the dashboard itself with different time interval. What will happen is an invalid link to "http://baseurl/?from=now-1w&to=now"

**Anything else we need to know?**:
There is a workaround with linking to "/dashboarduuid/?from=now-1w&to=now" wish works finde, thus this is not a high priority issue. Still the ability to e.g. "?from=now-1w&to=now" is nice because it is free of the dashboards uuid and thus still works after the uuid changes (e.g. due to copying the dashboard)

I did not really get why this happens as it looks good in the html.

**Environment**:
- Grafana version: 8.1.3
- Data source type & version: irrelevant
- OS Grafana is installed on: official docker image
- User OS & Browser: happens on any browser
- Grafana plugins: irrelevant
- Others:

**Comment by torkelo** [comment]
it's not Grafana that is adding the baseurl it's the default browser behavior (when using base href) 

you can use `/d/${__dashboard.uid}/?from=now-1h&to=now}` to refer to the current dashboard
