### ISSUE TITLE
how can I add a http_proxy for alerts

### ISSUE THREAD

**Issue by ImmoWetzel** [grafana/grafana#39194]
I have to use a proxy to reachout the teams webhook.
How can I specify this proxy address for the alert/notification contact point

**Comment by torkelo** [comment]
environment variable `http_proxy` or `https_proxy`

**Comment by HBLiB** [comment]
Grafana 8 and ubuntu does not work, verified with version 7.5.9, and there it works.

**Comment by ImmoWetzel** [comment]
I use Grafana as docker container and started the container with --env https_proxy=192.168.1.2:8118 

and it works...
THX a lot

**Comment by HBLiB** [comment]
> Grafana 8 and ubuntu does not work, verified with version 7.5.9, and there it works.

Correction, Grafana 8 Enterprise edition it works.

**Comment by shawnlu-nj** [comment]
Grafana 9.5.17 running on docker does not work,  with “--env https_proxy=192.168.1.50:8888”. Email notifications do not go through the Linux global proxy at all. Only when selecting Slack and DINGDING Talk as notification methods, the Linux global proxy is used.
