### ISSUE TITLE
flux-datasource: Enhance precision of time-range to support milli-/nanoseconds.

### ISSUE THREAD

**Issue by alaendle** [grafana/grafana#39195]
Grafana in conjunction with the flux query language doesn't allow sub-second precision (while this isn't a problem for InfluxQL). My guess is that this should be changed to format for milliseconds or nanoseconds (`RFC3339Nano`) - but I'm not sure if additional changes are needed.

https://github.com/grafana/grafana/blob/df6b6e7a9886b091cbe5ff72ab413eb913d93eb7/pkg/tsdb/influxdb/flux/macros.go#L19-L20

I know I kept very short; so please let me know if I was unclear or if you need additional information. Thanks in advance!

**Comment by alaendle** [comment]
![2021-09-17_16h41_40](https://user-images.githubusercontent.com/969523/133803003-d37f9cf4-e078-42ef-8c20-ed2099e8d12b.gif)

**Comment by gabor** [comment]
hi @alechenninger , thanks for the detailed info! we will fix this.

**Comment by gabor** [comment]
@alaendle the change was merged, it should be available in 8.2.0 when it releases.
