### ISSUE TITLE
Table Panel: Add quick search over table values

### ISSUE THREAD

**Issue by gansvv** [grafana/grafana#3919]
It would be great to have a quick search over the contents of the table. This would be especially useful to drill-down to a specific item when tables have a large number of metric values.
I'm looking for something similar to http://datatables.net/

**Comment by mohanraj1939** [comment]
+1

**Comment by samuel-lebert-sb** [comment]
+1

**Comment by torkelo** [comment]
We are trying limit open GitHub issues in order to better track planned work or features we eventually hope to implement rather then enumerate all possible features. 

I will close this issue since it's been open for very long time without much interest in the feature or anyone showing interest in implementing it. 

This does not mean that we will never ever implement it or that we will never accept a PR for it. A closed issue can still attract up votes and act as a ticket to track feature demand/interest.

**Comment by sekomarek** [comment]
+1

**Comment by JohnBolander** [comment]
+1

**Comment by edum18** [comment]
you have the datatable panel plugin which has a search bar. https://grafana.com/plugins/briangann-datatable-panel

**Comment by saurabh3896** [comment]
+1

**Comment by edum18** [comment]
> +1
> 
> I am looking for this feature, I am planning to load table and want quick search feature to find values, even basic search would be fine.. currently i have to go back and forth between grafana and ELK to get my result correct. Please add this feature 👍

@satishdotpatel have you seen this plugin? https://grafana.com/plugins/briangann-datatable-panel

**Comment by saurabh3896** [comment]
I have already modified the core plugin folder and added the functionality for quick-search. But I can't figure out how to export it as a plugin so that I can install it any grafana instance. Any help would be appreciated.
This is the repository link : https://github.com/saurabh3896/grafana-table-filter-search

**Comment by amjad** [comment]
Would love to see this feature built into Table Panel. Quick search. @torkelo

**Comment by chrispatin** [comment]
This would be a good feature as well.

**Comment by abhishekmangudkar** [comment]
+1

**Comment by dbapower** [comment]
+1

**Comment by dwebsco** [comment]
+1

**Comment by Atem18** [comment]
Hi, grafana-datatable-panel seems not updated. Can we see to have it in standard table panel ?

**Comment by dbapower** [comment]
grafana-datatable-panel is not compatibility for 5.2.1,already use the 0.0.6 version.

**Comment by dbapower** [comment]
> I have already modified the core plugin folder and added the functionality for quick-search. But I can't figure out how to export it as a plugin so that I can install it any grafana instance. Any help would be appreciated.
> This is the repository link : https://github.com/saurabh3896/grafana-table-filter-search @torkelo

it's works fine~ But the search bar's  position is not beautiful,make the title looks so small~thanks ,and  would love to see this feature built into Table Panel.

**Comment by dbapower** [comment]
> I have already modified the core plugin folder and added the functionality for quick-search. But I can't figure out how to export it as a plugin so that I can install it any grafana instance. Any help would be appreciated.
> This is the repository link : https://github.com/saurabh3896/grafana-table-filter-search @torkelo

it's works fine~Need to restart grafana server。 And the search bar's  position is not beautiful,it makes the title looks so small~thanks ,and  would love to see this feature built into Table Panel.

**Comment by dbapower** [comment]
> I have already modified the core plugin folder and added the functionality for quick-search. But I can't figure out how to export it as a plugin so that I can install it any grafana instance. Any help would be appreciated.
> This is the repository link : https://github.com/saurabh3896/grafana-table-filter-search @torkelo

Need to restart Grafana server,and works fine。And the search bar's position looks not good,it makes the title looks so small,Would love to see this feature built into Table Panel. Quick search. @torkelo

**Comment by dbapower** [comment]
I have already modified the core plugin folder and added the functionality for quick-search. But I can't figure out how to export it as a plugin so that I can install it any grafana instance. Any help would be appreciated.
This is the repository link : https://github.com/saurabh3896/grafana-table-filter-search @torkelo

Need to restart Grafana server,and works not very good.the search bar's position looks not good,it makes the title looks so small.And if muti panel on the same DashBoard,Views obstruct each other.Would love to see this feature built into Table Panel. Quick search. @torkelo

**Comment by dbapower** [comment]
> I have already modified the core plugin folder and added the functionality for quick-search. But I can't figure out how to export it as a plugin so that I can install it any grafana instance. Any help would be appreciated.
> This is the repository link : https://github.com/saurabh3896/grafana-table-filter-search @torkelo

Need to restart Grafana server,and works not very good.the search bar's position looks not good,it makes the title looks so small.And if muti panel on the same DashBoard,Views obstruct each other.Would love to see this feature built into Table Panel. Quick search. @torkelo

**Comment by dbapower** [comment]
grafana-datatable-panel is work fine with grafana v5.2.1。need to restart grafana server，Thanks!

**Comment by Atem18** [comment]
@saurabh3896 Do you think you could modify : https://github.com/grafana/grafana/tree/master/public/app/plugins/panel/table and make a pull request ?

**Comment by dbapower** [comment]
grafana-datatable-panel search bar  are still some minor problems with it.As shown in the picture, it will show incomplete when there is more content.And the high version of grafana does not support。Hope grafana table panel Native support filter。@torkelo
![1](https://user-images.githubusercontent.com/47973709/60146089-cab52c80-97fa-11e9-800e-038f7ffcbe68.PNG)

**Comment by amjad** [comment]
Need this feature. Thanks.

**Comment by JFergIT** [comment]
+1 - Absolute must have.

**Comment by satishdotpatel** [comment]
> > +1
> > I am looking for this feature, I am planning to load table and want quick search feature to find values, even basic search would be fine.. currently i have to go back and forth between grafana and ELK to get my result correct. Please add this feature 👍
> 
> @satishdotpatel have you seen this plugin? https://grafana.com/plugins/briangann-datatable-panel

Thank you so much! that is what i was looking for, it works for me great, my datasource is mysql and now i can search record very easily.

**Comment by ch-hristov** [comment]
I'm surprised this doesn't exist by default in the data table. I'm using Grafana 6.7 and it seems like both the https://grafana.com/plugins/briangann-datatable-panel and the https://github.com/saurabh3896/grafana-table-filter-search are not very well made solutions. For the first one i get 

> Value column must have numeric datatype, column: jobstatus_id type: string value: -20200211-115601_222-v004-22E6-85JY8HEF

For the second one, it looks weird, makes strange movements and gives the same error as above. Overall, it seems like this issue should not be closed but open and I find it strange you closed it.

**Comment by fdbatista** [comment]
+1

**Comment by orena1** [comment]
Hi @ch-hristov  I also tried both options with 6.7 and both did not work.

**Comment by elrok123** [comment]
+1

**Comment by Nelluru-Hemasree** [comment]
+1-need this feature

**Comment by jazerda** [comment]
+1 would be good to know if the search feature is in the backlog

**Comment by FBorowiec** [comment]
+1

**Comment by anselmobattisti** [comment]
+1

**Comment by jasperjonker** [comment]
+1

**Comment by chavya** [comment]
Any updates on when do we plan to have this feature added ?

**Comment by NicoChang96** [comment]
+1 didn't see any update for this :(
really need this

**Comment by mbayat82** [comment]
+1

**Comment by chandan-denvr** [comment]
+1

**Comment by araujobsd** [comment]
++1

**Comment by k0rmo0** [comment]
Does grafana have this ?

**Comment by mehrdad-khojastefar** [comment]
+1

**Comment by meethatkar** [comment]
++1
