### ISSUE TITLE
Grafana  8.1.2 display issue

### ISSUE THREAD

**Issue by salamanderrex** [grafana/grafana#39200]
**What happened**:
that 600 line is above the 3.5k line. In prometheus, it has no issue. 
![image](https://user-images.githubusercontent.com/6581499/133328120-3b7a79fd-0497-48bb-9084-c0a6490ffa48.png)

![image](https://user-images.githubusercontent.com/6581499/133328209-77916298-9e74-4d66-a50f-922e4163ffde.png)

**What you expected to happen**:
it should look like in prometheus. 
**How to reproduce it (as minimally and precisely as possible)**:
the query is in the screenshoot.

**Anything else we need to know?**:
it errors in grafana 8.1.2 not in my grafana 7.
![image](https://user-images.githubusercontent.com/6581499/133328751-e57c4951-0fa4-48e0-a1c7-ffc8312a4dea.png)

**Environment**:
- Grafana version:
-  8.1.2
- Data source type & version:
- prometheus 2.29.2
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
can you include your panel json? Have you enabled stacking? can you show the raw query data?

**Comment by salamanderrex** [comment]
Oh, i found it is stack. after i disabled the stack, it works as expected. thanks!
