### ISSUE TITLE
Does Grafana support smoothing

### ISSUE THREAD

**Issue by arsibaba** [grafana/grafana#3920]
We are looking to deploy Grafana as one of our systems however I've been reading over the documentation and see no mention of there being a capability to smooth a line graph. However, looking through Google images appears to provide examples (I'm not sure if this is through the use of plugins or a functionality I'm unaware of).

I was hoping some one can help answer this question for me.
Thank you

Arsi

**Comment by torkelo** [comment]
It does not support spline curves (where spiked series is smoothed out by applying spline math, https://en.wikipedia.org/wiki/Spline_(mathematics)

You can smooth a series using transformation functions fi your time series store support them. graphite has a movingAverage function, Elasticsearch also has moving average transformation.
