### ISSUE TITLE
Bar graph does not re-calibrate percentages for new time range when stacked to 100%

### ISSUE THREAD

**Issue by Darth-Bobo** [grafana/grafana#39217]
**What happened**:
I created a bar graph to display data split into two values (successful commands vs failed in this case) and display the data as a 100% stacked graph against each command - so I can see percentage of failures vs successes.

The graph renders correctly when first loaded, but if the time range is changed the graph does not update the percentages correctly.

Example:
The first picture is when the graph initially loads with a time range of "Last 30 days".  It shows three commands and the percentages of success/fails correctly.
<img width="1189" alt="Last 30 days" src="https://user-images.githubusercontent.com/50400845/133399157-3dbc9f52-fa8c-4c89-93ba-97979dfbd88a.png">

The second picture is how the graph looks if the time range is changed to "Last 90 days"
<img width="1184" alt="Last 90 days" src="https://user-images.githubusercontent.com/50400845/133399185-8b134d5c-a3fe-4932-aa5d-5c8bb0afb36d.png">

As you can see, two additional commands are captured in the query, but there are no percentages next to the values and the percentages for the data captured by the 30 day range no longer total 100% - although the bars appear to all be rendered correctly.

Using the refresh dashboard control does not resolve the problem, but refreshing the browser window does.  This occurs in vertical and horizontal orientation.

**What you expected to happen**:
I expected the percentages displayed to refresh/recalibrate when the time range changed.

**How to reproduce it (as minimally and precisely as possible)**:
Create a bar graph stacked to 100% and change the time range.

**Environment**:
- Grafana version: 8.1.3 and 8.1.2
- Data source type & version: AWS Timestream
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: macOS Big Sur 11.6/Firefox 92.0

**Comment by dprokop** [comment]
@Darth-Bobo could you please check out latest version of Grafana? I think we have fixed this issue in 8.1.5 (https://github.com/grafana/grafana/pull/39188)

**Comment by Darth-Bobo** [comment]
Hi, sorry for the delay in replying I was away.  I've just updated to 8.2.0 and the issue definitely appears fixed in that, thanks!
