### ISSUE TITLE
Bar Gauge not refreshing when data is reloaded

### ISSUE THREAD

**Issue by laurielounge** [grafana/grafana#39210]
Bar gauge  does not refresh when values change to zero

I expected the graph to refresh

Create a bar gauge and attach some (say) date sensitive data to it. Save and view the chart. Then change the date range to a point where no data exists. The chart will not reflect the zero values.

Pressing F5 refreshes the value successfully

Environment:

    Grafana version: Community Version 8.1.3 (commit: a61f382, branch: HEAD)
    Data source type & version: MySQL Core
    OS Grafana is installed on: Rocky 8.4
    User OS & Browser:Firefox and Chrome, latest both, on Ubuntu and Windows 10
    Grafana plugins: Only

**Comment by torkelo** [comment]
Unable to replicate here: https://play.grafana.org/d/VfvV9PI7z/bar-gauge-zero?orgId=1&editPanel=2 
With that data source you can enter the values you want to show (similar to refresh), and when I change the last value to zero the gauge will re-render with the new value. 

Can you show what the panel inspect / data show when you change time range? (or query inspector), does it show zeros while the bar gauge show the old value? We have not other similar reports so it's very strange.

**Comment by laurielounge** [comment]
Appreciate the fast response Torkel.

Here's a before screenshot. Note the heights of the bars.
![bargauge1](https://user-images.githubusercontent.com/32884649/133388494-9eeeade9-1802-4d54-8558-854af0f08b3d.png)

And now, after adjusting a filter:
![bargauge2](https://user-images.githubusercontent.com/32884649/133388535-3d9a5d22-9dfb-4ac0-b7cd-49fb0dc79334.png)

You'll see that, despite the bars now showing values of zero, the bars didn't change heights.

**Comment by torkelo** [comment]
@laurielounge I need the inspect / data & query response for that last image as well

**Comment by laurielounge** [comment]
Here's the dashboard json-ed.
[Sales Analysis-1631690574515.zip](https://github.com/grafana/grafana/files/7167741/Sales.Analysis-1631690574515.zip)

**Comment by laurielounge** [comment]
For the top left dashboard,

Here's the before and after
[before.csv](https://github.com/grafana/grafana/files/7168035/before.csv)
After
[after.csv](https://github.com/grafana/grafana/files/7168038/after.csv)
The query response? You mean the sql that generates it? Or the stats?

Here's the specific panel json
[panel.zip](https://github.com/grafana/grafana/files/7168062/panel.zip)

**Comment by torkelo** [comment]
That is not the raw unformatted data, the data you showed have $ sign in them (so is not a number but a string).

Can you show the panel inspect / JSON /  DataFrame stucture (when the bug shows) 
and also the query inspector when the bug shows

**Comment by laurielounge** [comment]
No, correct, I've exported as CSV.

You mean.. panel -> inspect -> Panel JSON -> Dataframe strusture. Got it. Never seen that before.

Here you are.
[dataframe.zip](https://github.com/grafana/grafana/files/7168129/dataframe.zip)

**Comment by laurielounge** [comment]
[rawdata.zip](https://github.com/grafana/grafana/files/7168143/rawdata.zip)
And found the raw data as well.

**Comment by mckn** [comment]
@torkelo are you still investigating this or should we assign it to the user essentials squad?

**Comment by torkelo** [comment]
@mckn no
