### ISSUE TITLE
8.1.3 "request handler error: failed to query data: type assertion to string failed"

### ISSUE THREAD

**Issue by YouZhengChuan** [grafana/grafana#39216]
**What happened**:
![image](https://user-images.githubusercontent.com/3882312/133396298-38cb15cd-2d09-44e0-989d-0904b2249b0b.png)

As shown in the figure above, I created a chart using the influx data source, which contains 2 queries, where Ref "A" is the SQL statement manually entered, and Ref "B" is the SQL statement generated using the UI interface.

![image](https://user-images.githubusercontent.com/3882312/133396959-6be5b648-cb46-47f1-8013-8adeae4439e0.png)

```log
t=2021-09-15T16:18:03+0800 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=0 name="provider tx zone alert" error="request handler error: failed to query data: type assertion to string failed" changing state to=alerting
```

As shown in the figure above, the Alert created with Ref "A" will fail to test and run!

But the Alert created with Ref "B" is normal when running and testing.

**What you expected to happen**:

The queries created in these two methods should all run the Alert jobs normally.

**How to reproduce it (as minimally and precisely as possible)**:

 just need to manually enter a SQL query and create an Alert for it to reproduce.

**Anything else we need to know?**:

https://github.com/grafana/grafana/blob/fdc681788bb59acbe6229312d6dec7638bb539c2/pkg/tsdb/influxdb/model_parser.go#L28

Through the tracking code, I know that the error is generated from here, it seems that it is because the "resultFormat" parameter is missing in the query that manually enters the SQL statement.

```json
{
"model": {
              "hide": false,
              "query": "SELECT sum(\"tx_<500K_sum\") AS \"<500K\" FROM \"rp\".\"measurement\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
              "rawQuery": true,
              "refId": "A"
            }
}
```

**Environment**: MacOS and centos
- Grafana version: 8.1.3
- Data source type & version: influxdb 1.6.2
- OS Grafana is installed on: 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
fixed in https://github.com/grafana/grafana/pull/39330 , should be available in grafana 8.2.0, when it is released
