### ISSUE TITLE
Wrong color for error log selector

### ISSUE THREAD

**Issue by BitProcessor** [grafana/grafana#39213]
**What happened**:
The error log filter showed a blue or green line instead of a red one.

**What you expected to happen**:
The example "line" should be red

**How to reproduce it (as minimally and precisely as possible)**:
Good question.
See screenshots for 2 examples.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Loki  (installed with the Loki-distributed helm chart, 0.37.3)
- OS Grafana is installed on: official docker image
- User OS & Browser: Safari 14.1.2
![Screenshot 2021-09-15 at 08 35 17](https://user-images.githubusercontent.com/50638541/133383470-eb4fa1c4-8a64-46ec-bf0d-ca4072c3b506.png)
![Screenshot 2021-09-15 at 08 31 39](https://user-images.githubusercontent.com/50638541/133383475-83834d82-e722-4e21-8000-d4844d719b80.png)

**Comment by BitProcessor** [comment]
Seems to be happening for other levels as well:

![Screenshot 2021-09-15 at 09 29 17](https://user-images.githubusercontent.com/50638541/133390033-3fa8f020-68b2-4e81-874a-0215565176c4.png)

**Comment by Elfo404** [comment]
hi @BitProcessor thanks for reporting this!

closing it as duplicated of https://github.com/grafana/grafana/issues/37916
