### ISSUE TITLE
Legend color different from cursor shown color when hovering

### ISSUE THREAD

**Issue by fisdev6** [grafana/grafana#39215]
**What happened**:
when hovering over a chart, the color being shown is different from the legend color, in the attached file the hover color should be yellow, and it's blue.
**What you expected to happen**:
just hovering over the line's color should show the same color as the one shown in the legend
**How to reproduce it (as minimally and precisely as possible)**:
have a lot of different data shown over one chart, hover over one of the lines, the color should be the same as the one in the legend
![grafana-bug](https://user-images.githubusercontent.com/88373321/133397304-9b434440-3d58-42f0-a2e6-399e32741895.JPG)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Prometheus
- OS Grafana is installed on: docker container image
- User OS & Browser: Windows 10 & chrome
- Grafana plugins: none
- Others:

**Comment by torkelo** [comment]
this is fixed in v8.1
