### ISSUE TITLE
[DOCS] `PUT /api/admin/users/:id/permissions` arguments not specified

### ISSUE THREAD

**Issue by adamlwgriffiths** [grafana/grafana#3921]
The arguments for this API call are not specified in the documentation. The example request has no content.
http://docs.grafana.org/reference/http_api/#permissions

**Comment by adamlwgriffiths** [comment]
I assume it's a JSON blow of the following format?

```
{
  "role":"Viewer"
}
```

**Comment by torkelo** [comment]
No, that operation is only setting global permissions on the user, 

It currently expects a json body like this:
```json
{"isGrafanaAdmin": true}
```
