### ISSUE TITLE
[REST API] POST /api/admin/users - access denied and new orgs appearing

### ISSUE THREAD

**Issue by adamlwgriffiths** [grafana/grafana#3922]
Using the `POST /api/admin/users` end point to create a user, also creates a new organisation with the user's name.

```
# list existing orgs
GET https://<credentials>@<system>/api/orgs

[
    {
        "id": 1,
        "name": "Admin"
    }
]

# create a new org
POST https://<credentials>@<system>/api/orgs
{
  "name":"New Org"
}

{
    "message": "Organization created",
    "orgId": 12
}

# verify orgs on system
GET https://<credentials>@<system>/api/orgs

[
    {
        "id": 1,
        "name": "Admin"
    },
    {
        "id": 12,
        "name": "New Org"
    }
]

# set the active organisation (whatever that means) to be the new one
POST https://<credentials>@<system>/api/user/using/12

{"message":"Active organization changed"}


# make a new user
POST https://<credentials>@<system>/api/admin/users
{
  "name":"New User",
  "email":"newuser@example.com",
  "login":"NewUser",
  "password":"newuserspassword"
}

{
    "id": 7,
    "message": "User created"
}


# a new organisation appears with the name of the user's email address
GET https://<credentials>@<system>/api/orgs

[
    {
        "id": 1,
        "name": "Admin"
    },
    {
        "id": 12,
        "name": "New Org"
    },
    {
        "id": 13,
        "name": "newuser@example.com"
    }
]

# user is only in the new organisation
GET https://<credentials>@<system>/api/users/7/orgs

[
    {
        "orgId": 13,
        "name": "newuser@example.com",
        "role": "Admin"
    }
]
```

I cannot explain this behaviour, not a use case where this makes sense.

During testing I also found that if I didn't call `POST /api/user/using/:organisationId` with an organisation I created, the call would fail with a permission denied message.
After the first call to this, calls to `POST /api/admin/users` started succeeding.

**Comment by adamlwgriffiths** [comment]
Looking at the code (https://github.com/grafana/grafana/blob/56e208220530b5f79ed6e9a155338dc3e7bb625a/pkg/services/sqlstore/user.go#L74), it seems this is intentional.
Again, I cannot see a case where this makes sense. The API provides abilities to create organsiations and add users to them. It also provides the ability to change context/state between organisations which I can only conclude is for users already in multiple organisations and points to further deficiencies in the API itself.

Creating an organisation automatically should not be the default behaviour.
I can delete the organisation after the user is created, so it's clear that users can exist without being in an organisation.

The documentation makes no mention of this side-effect.

Tracing the logic, it seems 'SkipOrgSetup' must be set to true, which it seems to be by default. I've tried passing this in with the JSON (both lower and camel-case) and also passing in 'orgname', but the behaviour is still the same.
I'm have trouble figuring out the specifics of Go code, so I cannot be sure any of these are even relevant.

**Comment by torkelo** [comment]
With default config https://github.com/grafana/grafana/blob/master/conf/defaults.ini#L157 grafana should not create an organization for new users. However when this setting is set to false each new user also get's an organization of their own. 

What is your config setting for auto_assign_org ?

**Comment by adamlwgriffiths** [comment]
`GF_USERS_AUTO_ASSIGN_ORG=false`

**Comment by adamlwgriffiths** [comment]
Ok, that setting is counter intuitive.

The configuration docs state `# Set to true to automatically assign new users to the default organization (id 1)` which insinuates that setting it to `false` will do nothing.

Personally I don't want new users assigned to an organisation until I've allocated them one. It's technically a race condition as new users will either be: added to my root organisation - or have a new organisation created for them.

**Comment by torkelo** [comment]
A user can't exist without being connected to at least one organization. But I agree the docs can be better here, also I think there might be room to improve the admin api to allow the creation of a user without any org (would not be able login). 

The preferred way is to create the organization you want for your users and then switch to that org and then head to org users view and invite them. 

![image](https://cloud.githubusercontent.com/assets/10999/12808615/79bf73c4-cb18-11e5-8190-71caa72dae1e.png)

Might not be ideal for your case though.

**Comment by adamlwgriffiths** [comment]
No, this case doesn't fit with programmatic administration.
