### ISSUE TITLE
[2.6] Influxdb Templating

### ISSUE THREAD

**Issue by Griesbacher** [grafana/grafana#3924]
Hi,

I'm trying to create a Template with InfluxDB as backend. The data I have is like your example data: server1, server2, server3... 
![temp influxdb](https://cloud.githubusercontent.com/assets/12564488/12777094/ea140e6e-ca5a-11e5-88c7-aea00369cd40.PNG)

Now I want to use the template variable as part of the query:
![temp influxdb 2](https://cloud.githubusercontent.com/assets/12564488/12777389/d3b3374c-ca5c-11e5-824b-e984697fe11d.PNG)

The aim is to concatenate the variable and a hardcoded string. This doesn't  work in Influxdb, because the influxdb query which will be created contains this: "hostname" =~ /1$server/
Due to the dollar the regex won't match :disappointed: 
I know the example above will never work with your example data.

It is just working if the Variable is the last part of the query, like this:
![temp influxdb 3](https://cloud.githubusercontent.com/assets/12564488/12777301/61803a76-ca5c-11e5-9924-6bdcfd67862c.PNG)

This would be a example which should work with your test data, even if it is stupid:
![temp influxdb 4](https://cloud.githubusercontent.com/assets/12564488/12777506/cde16dc4-ca5d-11e5-8f12-8a2a0cfa7aa2.PNG)

So, is there a possibility to make this dollar sign optional, which will be added to the InfluxDB? Or has this a certain meaning?

Greets,
Philip

**Comment by torkelo** [comment]
try  `/[[Hostname]]server/`

**Comment by Griesbacher** [comment]
That's it! Thanks for the fast reply!

**Comment by vsreelasya** [comment]
Did this work?

**Comment by vsreelasya** [comment]
I am trying to Concatenate one Variable and a String, but this does not seem working to me.
