### ISSUE TITLE
Cosmetic but important update to grafana.ini

### ISSUE THREAD

**Issue by vorugantivishwanath** [grafana/grafana#39255]
Hi,

I respect grafana documentation and I understand that an end user should go through grafana documentation for making any changes, but from end user perspective please consider below 2 points

a) Comments are usually represented with lines that start with #
b) Below are the lines from grafana.ini in 7.x version
##################### Grafana Configuration Example #####################
#
# Everything has defaults so you only need to uncomment things you want to
# change

# possible values : production, development
;app_mode = production

# instance name, defaults to HOSTNAME environment variable value or hostname if HOSTNAME var is empty
;instance_name = ${HOSTNAME}
[root@dexpvpomp001 etc]# 

So, for a user who might be new and wants to quickly change the configuration he will usually go to grafana.ini and will start changing the configuration ( It is recommend to go through documentation, I agree! )
So , in the comments section of grafana.ini if there is an explict statement which states ";" has to be removed for configuration to come in to picture is added it will help a lot to end user and it is cosmetic but I feel it is worth to add.
Also, if possible documentation URL is added as comments, it is worthy too.

Decision can be taken by Grafana experts but it is an opinion from my end.

Thanks a lot.

**Comment by Elfo404** [comment]
Hello @vorugantivishwanath 

i'm not sure i understood what your suggestion is. would you like a line saying `to uncomment, remove ";" at the beginning of the line`?

**Comment by zuchka** [comment]
I have seen other community users not realize that they must remove the `;` to uncomment and activate the setting.

@achatterjee-grafana thoughts?

**Comment by achatterjee-grafana** [comment]
I will add the note.

**Comment by achatterjee-grafana** [comment]
Interestingly, the information is already there: https://grafana.com/docs/grafana/latest/administration/configuration/#comments-in-ini-files. I will try to make it more visible.

**Comment by achatterjee-grafana** [comment]
Updated Configuration topic: https://grafana.com/docs/grafana/latest/administration/configuration/ with a note.
