### ISSUE TITLE
Elasticsearch: query indices in batches

### ISSUE THREAD

**Issue by Cajga** [grafana/grafana#3925]
Hi,

We are using Grafana to visualize service availability data from Elasticsearch back-end. We are using daily based indices ([service_availability-]YYYY.MM.DD) to be able to drop an index and re-parse/calculate a day easily.

We created a dashboard which had 2 graphs and 9 single value panels. When we extended the visualization to more then 1 months of data, our ES started to drop requests with the following messages in the logs and we started to had missing data points on the graphs:
`[2016-02-02 15:35:12,453][DEBUG][action.search.type       ] [Meanstreak] [service_availability-2015.12.16][4], node[ArrKolU0R7qC4jBRvHjH8w], [P], v[4], s[STARTED], a[id=btd1jCQ5TUmZcpyzrquG_A]: Failed to execute [org.elasticsearch.action.search.SearchRequest@13e2ff77] lastShard [true]
RemoteTransportException[[Meanstreak][127.0.0.1:9300][indices:data/read/search[phase/query]]]; nested: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@ea25894 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@2e0d7a74[Running, pool size = 2, active threads = 2, queued tasks = 1000, completed tasks = 1364287]]];
Caused by: EsRejectedExecutionException[rejected execution of org.elasticsearch.transport.TransportService$4@ea25894 on EsThreadPoolExecutor[search, queue capacity = 1000, org.elasticsearch.common.util.concurrent.EsThreadPoolExecutor@2e0d7a74[Running, pool size = 2, active threads = 2, queued tasks = 1000, completed tasks = 1364287]]]`

We could also see that the counter of the rejected search thread pool requests increased significantly during our tries:
`$ curl 'localhost:9200/_cat/thread_pool?v&h=id,host,search.rejected'

id   host      search.rejected 
ArrK 127.0.0.1          509813 `

Using the browsers debugger (and direct access on the ES data source), we saw that Grafana did 11 http requests parallel and each search was using about 155 shards (31 indices multiplied by 5 shards each, which is the default value in ES when one creates an index). These get queued and as the queue size is only 1000, many requests gets dropped.

As we normally use kibana to search through the entries, we had a look how does kibana handles the daily based indexing. Kibana splits up the queries into smaller chunks and those requests are serialized as well. Doing a search in kibana which touches 1 month of indices will only use maximal of 15 shards (3 indices) at a time (on the same data set, where grafana used ~1700 shards with our dashboard with 11 panels).

A workaround was to switching to monthly based indices which works fine until we do not want to show more then 2 years of data on the same dashboard.

**Comment by Cajga** [comment]
Just for the logs: another change that we introduced and helped a bit is to decrease the shard size to 2 from the default 5 for our indices (re-indexed  the documents).

**Comment by Cajga** [comment]
Hi torkelo,

Have you had any chance to look into this?

**Comment by seuf** [comment]
Elasticsearch 5.6 introduced the `max_concurrent_shards_request` to reduce the number of shards per requests :

> The search’s max_concurrent_shard_requests request parameter can be used to control the maximum number of concurrent shard requests the search API will execute for this request. This parameter should be used to protect a singe request from overloading a cluster ie. a default request will hit all indices in a cluster which could cause shard request rejections if the number of shards per node is high. This default is based on the number of data nodes in the cluster but at most 256.

I've patched the elasticsearch datasource to add this parameter in queries where es version is >= 5.6 (PR is comming)

**Comment by marefr** [comment]
Fixed by #9950 so closing this
