### ISSUE TITLE
Transformations: Variables should work in 'Filter data by values' condition

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#39266]
**What happened**:
Variables not work in 'Filter data by values' condition.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a 'Filter data by values' transform.
2. Input variable in condition value.

**Environment**:
- Grafana version:Grafana v8.1.2 (103f8fa094)

**Comment by ivanahuckova** [comment]
@imReker this seems like a feature request. Would you mind creating new discussion item https://github.com/grafana/grafana/discussions/new.

**Comment by imReker** [comment]
I'm not sure if variables designed to work in transformations, my personal opinion that variables 'should' work everywhere in panel. Maybe this is a feature request.
