### ISSUE TITLE
Graph with ES datasource and derivative metric doesn't load

### ISSUE THREAD

**Issue by TimVG** [grafana/grafana#3926]
Strange behaviour: the graph doesn't load on page load or when refreshing, but if you open chrome dev tools to inspect it does load.
![ikwcnrphv4](https://cloud.githubusercontent.com/assets/2239999/12778829/450f1b9c-ca65-11e5-8cac-3ddf2c2d6e71.gif)

**Comment by torkelo** [comment]
Try too specity a date histogram interval that is higher or equal to the rate of writes to elastic. You have it set to auto so could be that it is lower than the rate of writes

**Comment by TimVG** [comment]
That seems to do the trick. I have set it to 1m and now it works. Thx.
