### ISSUE TITLE
Y-axis not working

### ISSUE THREAD

**Issue by flopp999** [grafana/grafana#39269]
**What happened**:
Cannot set one of the series to right Y-axis

**What you expected to happen**:
Selected series to be on right Y-axis

**How to reproduce it (as minimally and precisely as possible)**:
have more than two series, set one of them to be right Y-axis

**Environment**:
- Grafana version: 8.1.3
- Data source type & version: InfluxDB & 1.8.9
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows 10 & Chrome

This is possible in 8.1.2
I do also miss the quick-select right Y-axis when you click on color-change button in the legend

![Animation](https://user-images.githubusercontent.com/21694965/133557032-29d251c7-2456-420e-9b84-98fcfbd384f9.gif)

**Comment by torkelo** [comment]
you need to set a different unit (then it will automatically use a right y axis).

We have an issue to add support for setting y axis independent of unit:
https://github.com/grafana/grafana/issues/38810
