### ISSUE TITLE
Plugins: make it easy for plugins to publish and subscribe to Grafana app events.

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#39276]
To make it easier for plugins developer to publish and subscribe Grafana app events we should introduce a proper API where a plugin can hook into the event pipeline and get notified when different events occur.

Ways of doing this currently:

https://github.com/grafana/clock-panel/blob/546f1f7cd5588d31a5a9c0d61b199953b886232b/src/ClockPanel.tsx#L28
https://github.com/grafana/grafana-ml-app/blob/main/src/hooks/useEvents.ts#L6

### Additional notes
Probably it would make sense to restrict what events plugins can publish on this central "bus", e.g. no built-in core events.

**Comment by tolzhabayev** [comment]
@mckn so is it closed or anything more needs to be done here?

https://github.com/grafana/grafana/issues/39276#issuecomment-948328786

**Comment by mckn** [comment]
> @mckn so is it closed or anything more needs to be done here?
> 
> [#39276 (comment)](https://github.com/grafana/grafana/issues/39276#issuecomment-948328786)

I think we should refactor this a bit to make it more fool proof.
