### ISSUE TITLE
InfluxDB, Format as Table in a  table Panel is not mapping column names properly

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#3928]
I am using InfluxDB as data source, and using a table panel. I have marked the `Format As` as `Table`.
Grafana 2.6 is not able to properly map the columns properly. Reproduce: Refer to http://play.grafana.org/dashboard/db/influxdb?panelId=3&fullscreen&edit

The response is below:
`{"results":[{"series":[{"name":"logins.count","tags":{"datacenter":"America","hostname":"10.1.100.1"},"columns":["time","median"],"values":[[1454500800000,null],[1454504400000,132.04913204768673]]},{"name":"logins.count","tags":{"datacenter":"America","hostname":"10.1.100.10"},"columns":["time","median"],"values":[[1454500800000,null],[1454504400000,131.87755069183186]]},{"name":"logins.count","tags":{"datacenter":"America","hostname":"server1"},"columns":["time","median"],"values":[[1454500800000,null],[1454504400000,131.90910775377415]]}]}]}`

![image](https://cloud.githubusercontent.com/assets/8618235/12783297/9d635362-caa6-11e5-8821-b8738174c860.png)

Look at how `"datacenter":"America","hostname":"10.1.100.1"` from response ti rendered in table panel.

**Comment by torkelo** [comment]
does indeed look like a bug, thanks for reporting this!

**Comment by mvadu** [comment]
@torkelo my pleasure!

**Comment by torkelo** [comment]
fixed in https://github.com/grafana/grafana/commit/37ff432f9db716930f9247c0c71286eac053c002
