### ISSUE TITLE
Mixed up display of colors in the loki log graph

### ISSUE THREAD

**Issue by aksenk** [grafana/grafana#39297]
**What happened**:

When I view logs from loki, I see mixed colors of the log level when hovering the cursor.

**What you expected to happen**:

See the same colors on the legend and when hovering the cursor

**How to reproduce it (as minimally and precisely as possible)**:

Install 2.3.0 loki and promtail, grafana 8.0.5 and do any request from logs with different log levels.

**Anything else we need to know?**:

The behavior can be seen in the screenshots below:

![2](https://user-images.githubusercontent.com/9846543/133630509-bffcee2b-54a2-449f-9a3a-12e809fd8038.jpg)

![3](https://user-images.githubusercontent.com/9846543/133630535-e5879669-ac8f-40b1-b990-235ebd5c693f.jpg)

**This is displayed correctly on grafana version 7+**

**Environment**:
- Grafana version: 8.0.5
- Data source type & version: Loki
- Loki version: 2.3.0
- Promtail version: 2.3.0

**Comment by leeoniya** [comment]
was this fixed by https://github.com/grafana/grafana/pull/39072 :thinking:

**Comment by Elfo404** [comment]
@leeoniya yep! but in 8.1.4.

Closing this as already fixed in #39072, can you please try upgrading to 8.1.4? @aksenk

**Comment by aksenk** [comment]
Thank you!
