### ISSUE TITLE
Feature request to allow adjustments to yaxis scale

### ISSUE THREAD

**Issue by t-pascal** [grafana/grafana#3930]
This might be hard to describe and I don't think I can attach screenshots. So you'll have to imagine it.

The first use case is the following: We have a large spike of activity and then it goes away in the graphs. The metrics we're watching go on the Y-axis from several thousand to several million and then back down. We can't see "what's happening now" because it's washed out. Switching to fixed axes is difficult and cumbersome. Using log axes washes out the normal activity. It is currently possible to zoom(box outline)/pan(adjust date range) the X-axis via the usual view controls. Think of it as yaw control. This allows us to work around the spike. But what I'd love to do is be able to zoom(plus/minus)/pan(slider) the Y-axis. You might call it pitch control. I could filter out the large spike and go back to a normal view until it drops off the graph to the left.

This first use case is about average importance to me. That is, I could see a lot of other features being more important and a lot of other features being less important.

There is another use case: since we often have auto-scaling Y-axes (It's way too difficult to manage fixed Y-axes for each metric), sometimes we want to have two panels next to each go to the same scale for comparison. So the right panel might be scaled to 10e3 and the panel next to it might be 10e4. This can cause some strange reactions to a viewer without careful analysis. A nice solution might be to fix several panels in a row to the same scale. And if we used the above feature of being able to pan/zoom the Y-axis, that the related panels would be panned/zoomed at the same scale as the one we're manipulating.

This second use case is probably more difficult to manage and is less important than the feature above. And, if the first use case is added, then manipulating two panels to the same zoom without automatic mirroring would be a suitable workaround.

These two features show that the X-axis currently gets a lot of features and attention but the poor Y-axis is lagging behind. :)

**Comment by torkelo** [comment]
Interesting (and tricky problems), at least the second one. 
The first issue of filtering out spikes, you might be able to use graphite's function removeAboveValue , not sure what time series store you use though. 

There is already an issue for locking the y-axis for two graphs, so will close this issue.
