### ISSUE TITLE
Influx grafana still fails when keys include "/" 

### ISSUE THREAD

**Issue by sagetrey** [grafana/grafana#3931]
Grafana Version used 2.6 
Influxdb 0.9

Reference 

https://github.com/grafana/grafana/issues/2373

Issue still persists.

**Comment by torkelo** [comment]
what your query variable config?

**Comment by torkelo** [comment]
It works here, with this variable config:
![image](https://cloud.githubusercontent.com/assets/10999/12808439/449ab0ba-cb17-11e5-80bc-ac7fe211360e.png)
