### ISSUE TITLE
Grafana 8.1.4 -> Enter no reaction

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#39321]
**What happened**:
Enter doesn't work
**What you expected to happen**:
Fix it
**How to reproduce it (as minimally and precisely as possible)**:
Click on panel -> remove -> enter on keyboard -> no reaction

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: MS SQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- Grafana plugins: n/a
- Others: n./a

**Comment by torkelo** [comment]
thanks for reporting this, it had autoFocus but it was not working for some reason
