### ISSUE TITLE
OAuth login doesn't work with GF_SERVER_SERVE_FROM_SUB_PATH

### ISSUE THREAD

**Issue by davidgiga1993** [grafana/grafana#39326]
**What happened**:
When trying to use oauth login with grafana using `GF_SERVER_SERVE_FROM_SUB_PATH=true` the 1st redirect after clicking on the "OAuth Login" button is pointing to `domain.com/` instead of `domain.com/grafana` as configured in `GF_SERVER_ROOT_URL`

**What you expected to happen**:
The redirect should use the correct sub path

**How to reproduce it (as minimally and precisely as possible)**:
1) Enable oauth login ( can be a dummy since the issue appears before even redirecting to the provider)
2) Set `GF_SERVER_ROOT_URL=https://mydomain.com/grafana`
3) Set `GF_SERVER_SERVE_FROM_SUB_PATH=true`
4) Try to login

**Anything else we need to know?**:
When using a reverse proxy and removing the `GF_SERVER_SERVE_FROM_SUB_PATH` environment variable the login works as expected.

### Wrong
`GF_SERVER_SERVE_FROM_SUB_PATH=true`
```
Browser --> Grafana  /grafana/login/generic_oauth
Browser <-- Grafana Replies with location header: `location: /login/?access_type=online&client_id=`
```

### Correct
`GF_SERVER_SERVE_FROM_SUB_PATH=false` using reverse proxy
```
Browser --> Grafana  /grafana/login/generic_oauth
Browser <-- Grafana Replies with location header: `location: /grafana/login/?access_type=online&client_id=`
```

Interestingly the redirect_uri parameter for the oauth provider inside the url is correct in both cases

**Environment**:
- Grafana version: v8.1.4 (6855cdff7c)
- Data source type & version: N/A
- OS Grafana is installed on: K8
- User OS & Browser: Windows 11 / Chrome
- Grafana plugins: None
- Others:

**Comment by papagian** [comment]
I'm unable to reproduce it either in main using:
```
GF_SERVER_SERVE_FROM_SUB_PATH=true \
GF_SERVER_ROOT_URL=http://localhost:3000/grafana \
GF_AUTH_GOOGLE_ENABLED=true \
GF_AUTH_GOOGLE_CLIENT_ID=$CLIENT_ID \
GF_AUTH_GOOGLE_CLIENT_SECRET=$CLIENT_SECRET \
GF_LOG_LEVEL=debug make run
```

or in `8.1.4` using:
```
docker run --rm \
-e GF_SERVER_SERVE_FROM_SUB_PATH=true \
-e GF_SERVER_ROOT_URL=http://localhost:3000/grafana \
-e GF_AUTH_GOOGLE_ENABLED=true \
-e GF_AUTH_GOOGLE_CLIENT_ID=$CLIENT_ID \
-e GF_AUTH_GOOGLE_CLIENT_SECRET=$CLIENT_SECRET \
-e GF_LOG_LEVEL=debug \
grafana/grafana:8.1.4
```

In both cases I was able to login successfully.

**Comment by davidgiga1993** [comment]
Can you try using the generic oauth for reproducing? I can reproduce this with an out of the box configuration:
```
GF_LOG_MODE: "console"
GF_SERVER_SERVE_FROM_SUB_PATH: "true"
GF_SERVER_ROOT_URL: "https://mydomain.com/grafana"
GF_SMTP_ENABLED: "true"
GF_LOG_LEVEL: "debug"
# OAuth
#GF_AUTH_DISABLE_LOGIN_FORM: "true"
GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "98536c12-544c-4848-8c01-df77c8244f06"
GF_AUTH_GENERIC_OAUTH_SCOPES: "oauth email"
GF_AUTH_GENERIC_AUTH_URL: "https://myauth.com/as/authorization.oauth2"
GF_AUTH_GENERIC_TOKEN_URL: "https://myauth.com/as/token.oauth2"
GF_AUTH_GENERIC_API_URL: "https://myauth.com/idp/userinfo.openid"
GF_AUTH_GENERIC_EMAIL_ATTRIBUTE_NAME: "email"
```

**Comment by papagian** [comment]
I have tried with generic_oath but still I cannot reproduce it:
```
docker run \
-e GF_SERVER_SERVE_FROM_SUB_PATH=true \
-e GF_SERVER_ROOT_URL=http://localhost:3000/grafana \
-e GF_AUTH_GENERIC_OAUTH_ENABLED=true \
-e GF_AUTH_GENERIC_OAUTH_NAME=okta \
-e GF_AUTH_GENERIC_OAUTH_CLIENT_ID=$OKTA_CLIENT_ID \
-e GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET=$OKTA_CLIENT_SECRET \
-e GF_AUTH_GENERIC_OAUTH_SCOPES="openid profile email" \
-e GF_AUTH_GENERIC_OAUTH_AUTH_URL=https://$OKTA_DOMAIN/oauth2/v1/authorize \
-e GF_AUTH_GENERIC_OAUTH_TOKEN_URL=https://$OKTA_DOMAIN/oauth2/v1/token \
-e GF_AUTH_GENERIC_OAUTH_API_URL=https://$OKTA_DOMAIN/oauth2/v1/userinfo  \
--rm -p 3000:3000 grafana/grafana:8.1.4
```
Can you share your server logs and how you have configured your OAuth application?

**Comment by davidgiga1993** [comment]
Thanks again for getting back to me! 
I found the root cause: `GF_AUTH_GENERIC_AUTH_URL` instead of `GF_AUTH_GENERIC_OAUTH_AUTH_URL` (and similar with the other parameters). So 100% an configuration issue on my side, sorry!
Would be nice though if grafana could log a warning/error if an oauth parameter is missing.
