### ISSUE TITLE
 Adding support for Heroic time series database

### ISSUE THREAD

**Issue by yingfeng** [grafana/grafana#3932]
https://github.com/spotify/heroic

Heroic is also a popular time series database like opentsdb, influxdb,...,etc

**Comment by bergquist** [comment]
interesting. I cannot find any documentation about how they visualize the data.

**Comment by commarla** [comment]
https://spotify.github.io/heroic/#!/docs/api

**Comment by bergquist** [comment]
I mean how they render the data. I'm guessing they have some kind of dashboard setup now. Maybe even a Grafana datasource plugin that they might be willing to share :)

**Comment by udoprog** [comment]
Hey, I'm the maintainer of Heroic.

I actually started working on Grafana support for Heroic about three months ago. Things got in the way, and it eventually bit-rotted.
I've restarted my efforts, and have some basic query support up and running.
If you want to help out you can find instructions for how to setup a dev environment here:
https://github.com/udoprog/grafana/blob/master/HEROIC.md

I'll be setting up a pull request when It's done:ish. I'm targeting 3.0 and that includes getting more acquainted with the TypeScript setup for me. So I'd appreciate any support I can get.

**Comment by bergquist** [comment]
@udoprog I suggest you create a data source plugin for heroic rather then adding it to grafana core (we wont accept new datasources to grafana core unless they become really popular) Examples of such plugins can be found in https://github.com/grafana/grafana/tree/master/examples There you can find build script and examples of es5 and es6. You can also use Typescript if you like. 

In upcoming grafana we will make it easier to install plugins and we will start hosting a repo with all plugins. Would be cool to see heroic among the first plugins :)

**Comment by udoprog** [comment]
Neat, doesn't look like there would be a lot of work splitting it out.

So a few questions:

When the plugin is external, how will we avoid bit-rot (e.g. something changes in Core)? As it stands, plugins seem to have quite extensive access to DI basically anything it desires, which is quite a large API surface to maintain. Versioning the plugin API would be a way, but then one would have to be defined to begin with.

How do I currently install a plugin (so I can start working on it).

How is [this part managed](https://github.com/udoprog/grafana/commit/bc700530b9a63aa9d6aa6aa5151a2c48ed9b7044#diff-02ef37910c47e33a383f2c3b2a617159L14) when it's external, will it no longer be necessary?

**Comment by bergquist** [comment]
@udoprog Good questions!

We have mad a bunch of changes of how grafana core interact with plugins to make the contracts more explicit (still lacks documentation but examples cover most usecases). So the surface area that needed it smaller even thou plugin authors could to anything with angular DI. We will start working on versioning once 3.0 beta is out.

The easiest to install plugins for development is to place the plugin in a folder under grafana/data/plugins.  If you have buildscript for your javascript make sure to build them into a folder named dist. To install plugins in production you should be able to use grafana-cli once the plugin is added to our static plugins.json file :) 

Its only used for sending back metrics to our backend so we can see which datasources people use.

**Comment by bergquist** [comment]
Closing this the plugin is published https://grafana.net/plugins/udoprog-heroic-datasource :)
