### ISSUE TITLE
Docker Build Fails since 8.1.3

### ISSUE THREAD

**Issue by wodnan** [grafana/grafana#39348]
**What happened**:

performing a clean docker build results in an error

```
Removing intermediate container 4a30126c1666
 ---> 405b6f7e2a57
Step 14/42 : FROM golang:1.16.1-alpine3.14 as go-builder
manifest for golang:1.16.1-alpine3.14 not found: manifest unknown: manifest unknown

```

**What you expected to happen**:

build should finish with success

**How to reproduce it (as minimally and precisely as possible)**:

docker build --no-cache -t <tag> .

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.3/8.1.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zserge** [comment]
I can confirm the build doesn't work, since Go 1.16.1 uses Alpine 3.13 - https://hub.docker.com/layers/golang/library/golang/1.16.1-alpine3.13/images/sha256-1e892d23f06a26184b8d3f2687961ea0e450e321e1d1a1959921ddc35d819963?context=explore

A fix would be to use Go 1.16.5 and Alpine 3.14, or switch to Go 1.17 like it has been done in v8.2.x.

**Comment by wodnan** [comment]
on v8.2.0 a clean docker-build still does not work:
pkg/cmd/grafana-server/commands/cli.go:163:12: undefined: server.Initialize

occurs on both Dockerfiles with the following commands:

docker build --no-cache -f Dockerfile -t grafana .
docker build --no-cache -f Dockerfile.ubuntu -t grafana-ubuntu .

**Comment by tecmatia-dp** [comment]
I get same error building for Windows, out of the box:

`C:\grafana\src\github.com\grafana\grafana>go run build.go build
Version: 8.2.1, Linux Version: 8.2.1, Package Iteration: 1634206387
building binaries build
building grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/windows-amd64/grafana-server.exe
rm -r ./bin/windows-amd64/grafana-server.exe.md5
go build -ldflags -w -X main.version=8.2.1 -X main.commit=unknown-dev -X main.buildstamp=1634206388 -X main.buildBranch=main -buildmode=exe -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server
# github.com/grafana/grafana/pkg/cmd/grafana-server/commands
pkg\cmd\grafana-server\commands\cli.go:163:12: undefined: server.Initialize
exit status 2
exit status 1`
