### ISSUE TITLE
Feature Request: variables in X/Y-Max/Min

### ISSUE THREAD

**Issue by hryamzik** [grafana/grafana#3935]
Let's say you have a set of network graphs for several servers. They all have different scale as Y-Max is set to auto. You can set it to 1073741824 ( 1 gigabit ) for all the graphs but it won't make much sense. Defining a max value with a template variable could be really helpful in this case.

**Comment by xelite** [comment]
+1
Also option to set equal values on left and right Y-Max on a same graph.

**Comment by etlweather** [comment]
Similar use case for me. I have ping response time. I have a dashboard which shows today, yesterday, last week, comparison graphs. For a certain host, I may want 0-100ms as the scale, another host, on LAN, I may want to see 0-15ms scale so I can see changes on the graph. Right now I defaulted the dashboard to a certain value and have to change 3 graphs if I want to use a different scale.

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/6051

**Comment by stockto2** [comment]
You're sure this was included in 6051? I still can't use template variables in Y Max, after building from most recent source code.

**Comment by torkelo** [comment]
They issue was reversed due to issues

**Comment by tricky42** [comment]
Any timeline on when it will be included again?

**Comment by Ulrar** [comment]
Hi,

Is there a way to do that ? For a memory graph for example, knowing 4 Gb are used is good but not having the max makes the graph a bit useless .. It'd be great if I was able to use a query as Y-Max (since the total is collected).

**Comment by LeDistordu** [comment]
Hi,

It would be great if you could use item as Y-max, like item memory total

**Comment by relishcolouredhat** [comment]
Also came here  looking for this feature. Very surprised everybody does not need this.

**Comment by omarmarquez** [comment]
+1

**Comment by Veance** [comment]
+1

**Comment by neonardo1** [comment]
+1

**Comment by douglasg14b** [comment]
This would very much be wanted, some graphs looks a bit ridiculous without it.

**Comment by LittleDimON** [comment]
+1

**Comment by yurganov** [comment]
+1

**Comment by tecmatia-dp** [comment]
This change is working for me, in file "graph.ts", from...
```
      function parseNumber(value: any) {
        if (value === null || typeof value === 'undefined') {
          return null;
        }

        return _.toNumber(value);
      }
```
to...
```
      function parseNumber(value: any) {
        if (value === null || typeof value === 'undefined') {
          return null;
        }

        return _.toNumber(ctrl.templateSrv.replace(value, ctrl.panel.scopedVars));
      }
```

**Comment by adriananeci** [comment]
+1

**Comment by hryamzik** [comment]
@tecmatia-dp can you make a PR for this, please?

**Comment by simPod** [comment]
@hryamzik see the PR, was closed tho :/

**Comment by TSzerypo** [comment]
I know a lot of people who would be happy with this change.

**Comment by ohrly** [comment]
I like to have this with a variable or a direct query option:
I have thresholds within the datasource and I like to scale the graph from Y-Min: 0 to Y-Max: $threshold+0,1 basically!
But flexible Y-Min/Y-Max values would be also good, like often requested: >720 <292 and so on!
Would be greatly appreciated!

**Comment by fincomus** [comment]
+1

**Comment by Izdatyi** [comment]
3 years later ...

**Comment by brandond** [comment]
I'd love to see this too. The (very minor) PR to add this feature was closed in favor of a complete rewrite that is "1 to 2 years" out!

**Comment by rox-wolf** [comment]
Oh boy, we still need that. Please make it happen..

**Comment by axipher** [comment]
Would also like to have this feature

**Comment by LennyPenny** [comment]
Would love to see this!

**Comment by hdlbq** [comment]
+1

**Comment by scheka** [comment]
+1

**Comment by douglasg14b** [comment]
Please just use the reaction and not spam +1 comments.....

**Comment by simPod** [comment]
My https://github.com/grafana/grafana/issues/6477 was not complete. It is needed to resolve variables in axis also before running `updateLegendValues()`.

**Comment by slimsag** [comment]
Would a PR that adds support for this be accepted? Or is there a reason this is tricky behavior to add and it needs further discussion about how it would be implemented?

**Comment by philbour** [comment]
I created a variable to use in the max field for the gauge visualization but was surprised to find I couldn't! This is really needed. I run load tests with different loads, I have to keep changing the max value for the dashboard to look presentable.

Surprised that after 4 years and all the requests, this has still not been worked on.

**Comment by rmarabini** [comment]
+1

**Comment by thijsdebont** [comment]
I was surprised to find this is not implemented in Grafana. Seems such an intuitive feature. So +1 for the feature request.

**Comment by hb0nes** [comment]
> This change is working for me, in file "graph.ts", from...
> 
> ```
>       function parseNumber(value: any) {
>         if (value === null || typeof value === 'undefined') {
>           return null;
>         }
> 
>         return _.toNumber(value);
>       }
> ```
> 
> to...
> 
> ```
>       function parseNumber(value: any) {
>         if (value === null || typeof value === 'undefined') {
>           return null;
>         }
> 
>         return _.toNumber(ctrl.templateSrv.replace(value, ctrl.panel.scopedVars));
>       }
> ```
> 
> With this, it accepts dashboard variables in Y-min/max.

How would I use a variable after changing this .ts file? I have applied the changes but don't know what to input in the 'max' field in my bar graph chart.

**Comment by tecmatia-dp** [comment]
> How would I use a variable after changing this .ts file? I have applied the changes but don't know what to input in the 'max' field in my bar graph.

Use $var_name like in other valid places.
This fix is tested with Grafana v5, I don't know if still works in v7.

**Comment by gaurishprabhakar** [comment]
+1

**Comment by wiku-PSNC** [comment]
> This fix is tested with Grafana v5, I don't know if still works in v7.

Hi @tecmatia-dp , could you please verify if it still works in v7? This fix could help me very much, but so far it doesn't work for me. :(

**Comment by wiku-PSNC** [comment]
> Hi @tecmatia-dp , could you please verify if it still works in v7? This fix could help me very much, but so far it doesn't work for me. :(
I've discovered, that after changing graph.ts file the app.7b506073f46893460c0d.js (from grafana_7.0.4_amd64.deb) webpack has to be rebuild but at this moment I've no idea how to do it.

**Comment by noharm** [comment]
@wiku-PSNC , I don't know if this is still helpfull, but will post anyway.

I've followed the "[developer instructions](https://github.com/grafana/grafana/blob/master/contribute/developer-guide.md)" to clone and build the grafana frontend from source.Then I've updated `public/app/plugins/panel/graph/graph.ts` in the source tree with a slightly modified fix and rebuild:
```
  parseNumber(value: any) {
    if (value === null || typeof value === 'undefined') {
      return null;
    }

    return _.toNumber(this.ctrl.templateSrv.replace(value, this.ctrl.panel.scopedVars));
  }
```
Finally I've replaced `/usr/share/grafana/public` from the binary package, with the one I build from source and restarted the grafana-server.

I don't know if there's a easier way. But for me, this works like a charm.

**Comment by tgtwm1github** [comment]
@noharm Is it possible to share your build? It will greatly help.

**Comment by noharm** [comment]
I've made a fresh build. You can find a tgz of the "public" directory [here](https://drive.google.com/file/d/19hOQWK-Gec7uBexqK28b2iiegM3jtQIw/view?usp=sharing)

**Comment by tgtwm1github** [comment]
The link draws a blank page.

Is there any way you can share it via github?

**Comment by namadori** [comment]
I am really surprised, this seems a very basic feature (my first use for a variable is to set the Y-Max value across many charts) that almost everyone will need, and 5 years after the first post it is still not implemented.
Is there any way to draw the attention of the developers to this issue? From @tecmatia-dp it also seems to be pretty easy to implement.

**Comment by HaydenBurrows** [comment]
@wiku-PSNC 

A small modification with your code gets y min/max variables working for me.  Removing _. from this line:
`return _.toNumber(this.ctrl.templateSrv.replace(value, this.ctrl.panel.scopedVars));`

For my purpose it allows a text variable/s which a user can populate with a number of their choice.

**Comment by torkelo** [comment]
So in v8.1 we are adding two new transforms that will allow you to extract config like min, max, unit and thresholds from a normal query:

[Config from query results](https://grafana.com/docs/grafana/next/panels/transformations/config-from-query/)
[Rows to fields](https://grafana.com/docs/grafana/next/panels/transformations/rows-to-fields/) 

We are soon switching to Github discussions for feature requests, will create an issue there next week to collect feedback on these new transforms

**Comment by 19wolf** [comment]
^Those two links are dead. What's the current status of this and how do I make it work?

**Comment by axsuul** [comment]
The updated links are:

[Config from query results](https://grafana.com/docs/grafana/next/panels/transform-data/transformation-functions/#config-from-query-results)
[Rows to fields](https://grafana.com/docs/grafana/next/panels/transform-data/transformation-functions/#rows-to-fields)

**Comment by ErikEngerd** [comment]
I am not sure that the above will cover my use case. As part of troubleshooting I am using grafana to display two panels for the same metric. One with the current time interval and one with a time shift (configured in a text box variable). The most common case is to use a time shift of 1 week because results between different days of the weeks can usually not be compared. In this troubleshooting scenario, it is essential that the time scales are the same. Preferably, I would also like to show the metric and time-shifted metric in the same graph to allow an even easier comparison. 

Now, I basically would like the option to configure the axis ranges for the two panels using a for instance a variable, or to tie the y ranges for the two panels together. It is essential that the two time ranges are the same. 

If I use the config from query result option than I can determine the min and max for the given  time interval, but the other panel with the time shift will then still return different values for min and max. 

In general, it would also be a good solution to show the metric together with the time shifted metric in the same graph.

**Comment by simPod** [comment]
@torkelo any idea how to use the config from query?

I configured it but it converts all my series' names to `Value`. I just want to set one series' Max. I'd at least expect it not to affect all my series when I constrain `Apply to options` to a single series.

![image](https://github.com/grafana/grafana/assets/327717/a1226187-7daf-48fe-9b77-3421ac78864f)
