### ISSUE TITLE
Snapshot created with API requires login

### ISSUE THREAD

**Issue by elinkev** [grafana/grafana#3936]
I noticed that if i create a snapshot with API request, i can only view it after i login, otherwise it would say "Problem! Dashboard snapshot not found".

When i go to my panel and make a snapshot from the interface, it would show it to anyone without login requirement.

**Comment by torkelo** [comment]
You must be using the api wrongly as the frontend uses the api to save the snapshot :)

**Comment by elinkev** [comment]
@torkelo Maybe i explained my problem poorly, ill try again:

1) I login to grafana admin panel and create a dashboard with graphs
2) I click on a graph and create a snapshot locally (it generates me a hashtag like this '_4IvOZA6wuoitXnLFMPWiL6Ndl39iSH3M_')
3) I then can view my graph with this link _example.com/dashboard-solo/snapshot/4IvOZA6wuoitXnLFMPWiL6Ndl39iSH3M_
4) Other users can view this link without the need to login to grafana admin panel

Now im trying to do the same without the interface with API:
1) I create my snapshot with '/api/snapshots' route, passing required parameters to create exact graph like from first method.
2) It generates me a hashtag (key) '_u8iKjeWAt9QCj7Yhi6PvxTwt1nba5xr1_'.
3) I can view this snapshot **while im logged in **with this link _example.com/dashboard-solo/snapshot/u8iKjeWAt9QCj7Yhi6PvxTwt1nba5xr1_
4) When other users open this link, they are redirected to login

**Comment by torkelo** [comment]
it is probably because the snapshotted panel does not contain snapshot data (neads to be embedded in the panel json), if that is not present the panel will request data from the datasource, which could trigger a login

**Comment by jerryxguo** [comment]
the issue is closed but not mention if grafana will improve it to make snapshot created by API accessible without login

**Comment by torkelo** [comment]
You can,  there is an api.  But you need to inset the snapshot data into the panels in the dashboard json you are pushing to the snapshot api. 

If this is not present the panels will try to request metrics, fail due to no login and redirect to login page

**Comment by jerryxguo** [comment]
@torkelo  is there an API to get snapshot data?   I don't find an API from document that can get datapoints for a particular dashboard.

**Comment by torkelo** [comment]
No,  as that is part of the frontend code.

**Comment by andrii-rymar** [comment]
Wow, really unexpected behavior. Would be nice it if was mentioned in the docs.

**Comment by torkelo** [comment]
What is unexpected?

**Comment by andrii-rymar** [comment]
The difference between API and UI workflows in this case. It is not obvious that user needs to mess with raw data instead of super convenient "query-only" mode they get using Grafana via UI. 
Can't vote for all but I think it would be really nice to have feature.

**Comment by torkelo** [comment]
@andrii-rymar not sure what you mean. You think UI and API should offer the same features? So we should implement a browser in the backend? sorry, not following you.

**Comment by andrii-rymar** [comment]
> You think UI and API should offer the same features?
They already do offer the same features. The only thing is that they work differently while being named the same.  
So reading the "Sharing features" first and the "Snaphot API" then makes user think it works totally the same. But it's not. That is my reasoning.

**Comment by torkelo** [comment]
Not sure I understand, they are very different, snapshot api does something. there is no sharing api. 

The api's are used by the frontend, and extends the features in the api by using UI. Some of the features are the UI (like fetching and visualising metrics). The snapshot feature is using both backend api features and UI features.

**Comment by aviadhahami** [comment]
Bumping this as I ran into the same thing - 
I think what @andrii-rymar means is that when one generates a snapshot via the API (not the client), we'd expect that Grafana BE will take care of querying the relevant data and saving the snapshot, rather than just saving it.

To conclude - we'd expect a full snapshotted dashboard upon API request.
`(Query & Save =/= Save)`
