### ISSUE TITLE
Alertmanager API not deleting silences

### ISSUE THREAD

**Issue by tom0010** [grafana/grafana#39370]
**What happened**:
Trying to remove a silenced alert via the API

**What you expected to happen**:
Alert to be unsilenced and for alerts to start being sent again.

**How to reproduce it (as minimally and precisely as possible)**:
Do a `get` request of your silences:
`/api/alertmanager/grafana/api/v2/silences/`
Select one ID from the output:
```
[
    {
        "id": "9ae17ed1-7086-4d87-8a5f-ffb8618ed6f1",
        "status": {
            "state": "active"
        },
        "updatedAt": "2021-09-17T18:20:10.526Z",
```
Do a `delete` request using that id in the URL:
`/api/alertmanager/grafana/api/v2/silences/9ae17ed1-7086-4d87-8a5f-ffb8618ed6f1`

returns:
404
```
{
    "message": "Not found"
}
```
**Anything else we need to know?**:
Doing:
`/api/alertmanager/grafana/api/v2/silences/9ae17ed1-7086-4d87-8a5f-ffb8618ed6f1` 
on a `get` request will also produce the same error.

As per the spec, this should be correct:
`https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json`

**Environment**: Docker 
- Grafana version: v8.1.3 (a61f38238c)
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker build
- User OS & Browser: macOS Catalina, Chrome (latest)
- Grafana plugins: boomtable
- Others:

**Comment by gotjosh** [comment]
The URL appears to be incorrect, it should be `/api/alertmanager/grafana/api/v2/silence/9ae17ed1-7086-4d87-8a5f-ffb8618ed6f1` Where `silence` is without the S.

You can see the route definition in https://github.com/grafana/grafana/blob/dfbd7bf64fd4d0af06627924c79bc7ed9464ece9/pkg/services/ngalert/api/generated_base_api_alertmanager.go#L59

**Comment by tom0010** [comment]
Thanks @gotjosh. Working as expected 👍
