### ISSUE TITLE
[docs] IIS TUTORIAL: Clarify possible Azure AD authentication issue when serving from subpath

### ISSUE THREAD

**Issue by BradleyDHobbs** [grafana/grafana#39373]
After following the steps in this article: https://grafana.com/docs/grafana/next/auth/azuread/

**What happened**:

After setting up Azure AD authentication, the "login with microsoft" button redirects to a page that returns a 404 which doesn't include the subpath. 

URL with the 404 (after clicking login): "https://grafana.example.com/TENANT_ID/oauth2/v2.0/authorize?access_type=online&client_id=CLIENT_ID&redirect_uri=http%3A%2F%2Fgrafana.example.com%2Flogs%2Flogin%2Fazuread&response_type=code&scope=openid+email+profile&state=HF_mH9IN2k4EnABPC4osw0smMkewCiD2LfTHifZVN8E%3D"

You can see it does not include my subpath of "/logs". However, even if I manually put in "logs" after the domain it just redirects me back to the main login page.

Example:

domain = grafana.example.com
root_url = https://grafana.example.com/logs
serve_from_sub_path = true

App Registration Reply URL: https://grafana.example.com/logs

[auth.azuread]
name = Azure AD
enabled = true
allow_sign_up = false
client_id = APPLICATION_ID
client_secret = CLIENT_SECRET
scopes = openid email profile
auth_url = https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/TENANT_ID/oauth2/v2.0/token
allowed_domains =
allowed_groups =

**What you expected to happen**:

I would expect the button to login with azure ad and redirect to the home page after successful login.

**How to reproduce it (as minimally and precisely as possible)**:

Setting up Azure AD on a Grafana instance which serves from a subpath (example above).

Other info:

There was one particular portion of the azuread docs that was confusing and possibly contradictory. In step 4 it says set the redirect url to "https://grafanadomain/login/azuread". However, later in the docs there is a note that says "Ensure that the root_url in Grafana is set in your Azure Application Reply URLs (App -> Settings -> Reply URLs)". If these two sections are talking about the same setting (I think they are) you would have two different URLs. In my case I tried both "https://grafana.example.com/logs" and " https://grafana.example.com/logs/login/azuread"

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: NA
- OS Grafana is installed on: Windows Server 2016
- User OS & Browser: Windows 10 and Google Chrome
- Grafana plugins: 
- Others:

**Comment by zuchka** [comment]
Hi @BradleyDHobbs thanks for making this issue, and for sharing your confusion with the docs.

Can you share any information about your infra setup? Are you using a reverse proxy? If so, can you share the configs?

Hoping one of the backend / Azure folks can get you unblocked. In the meantime, here is [a recent discussion in our community forum on using a subpath to serve grafana behind nginx](https://community.grafana.com/t/serve-grafana-through-reverse-proxy-nginx/45631/5).

**Comment by Viajaz** [comment]
I think we have the same issue. I'm using IIS with ARR/URLRewrite as a front-end:

custom.ini
```
[server]
domain = example.com
root_url = https://%(domain)s/grafana/
serve_from_sub_path = true
enable_gzip = true

[security]
disable_initial_admin_creation = true

[users]
allow_sign_up = false
allow_org_create = false

[auth.azuread]
name = Azure AD
enabled = true
allow_sign_up = true
client_id = ffffffff-ffff-ffff-ffff-ffffffffffff
client_secret = REDACTED
scopes = openid email profile
auth_url = https://login.microsoftonline.com/ffffffff-ffff-ffff-ffff-ffffffffffff/oauth2/v2.0/authorize
token_url = https://login.microsoftonline.com/ffffffff-ffff-ffff-ffff-ffffffffffff/oauth2/v2.0/token
allowed_domains = example.com
allowed_groups =
```


When clicking on "Sign in with Microsoft" from `https://example.com/grafana/login` it will make a request to `https://10.50.1.61/grafana/login/azuread`
and in response get HTTP 302 with Location header is:
`https://example.com/ffffffff-ffff-ffff-ffff-ffffffffffff/oauth2/v2.0/authorize?access_type=online&client_id=ffffffff-ffff-ffff-ffff-ffffffffffff&redirect_uri=https%3A%2F%2Fexample.com%2Fgrafana%2Flogin%2Fazuread&response_type=code&scope=openid+email+profile&state=FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF%3D`

It's not using `auth_url` evidently

**Comment by Viajaz** [comment]
I solved this problem in IIS with ARR by disabling _Reverse rewrite host in response headers_  in ARR with no ill effects thus far.

**Comment by zuchka** [comment]
@BradleyDHobbs, have you tried @Viajaz's solution?

+1 for docs improvement 👍

**Comment by BradleyDHobbs** [comment]
Thanks @Viajaz. 

I’m trying it now @zuchka. Will update shortly.

**Comment by BradleyDHobbs** [comment]
Still having issues with this. For some reason the redirect works with the "domain" option set to "localhost:3000" in the grafana config, but obviously localhost will not resolve from an external client. I tried it on the server with localhost and it seems like it wants to work but then says login failed, although it got past the "The reply url doesn't match" error.

**Comment by BradleyDHobbs** [comment]
Setting allow_signup to true got it to work. I'll let someone else close the ticket in case there is any doc improvement takeaways from this. 

Thanks @zuchka @Viajaz

**Comment by papagian** [comment]
I will close this since the tutorials live under the [grafana/tutorials](https://github.com/grafana/tutorials/blob/master/content/tutorials/iis.md) repository

**Comment by osg-grafana** [comment]
Some things come to mind, which is why I am reopening this issue:

1) It is not clear where this work is being tracked if this is closed as-is. How about using the "Transfer issue" feature at the lower-part of the right-hand menu?
2) Is the work being done behind the scenes informally or is it bound to fall through the cracks?
3) "Tutorials" are a content type, not a topic. @GrafanaWriter, this idea feeds nicely into our information architecture work, which in part separates documentation source and documentation display layers.

**Comment by osg-grafana** [comment]
cc @joshhunt, who likely has a better idea than I do about what repo this issue belongs in.

**Comment by achatterjee-grafana** [comment]
Adding @matthewhelmke as this is a suggestion to improve tutorials.
