### ISSUE TITLE
Grafana UI Storybook - Remove ToolbarButton and ToolbarButtonRow?

### ISSUE THREAD

**Issue by TheApeMachine** [grafana/grafana#39382]
**Why is this component needed**:
I am not sure if this is the right forum, but I didn't consider it a bug. I've discovered Grafana UI today and after some struggles (I didn't know React) it's going quite well now. However I was trying to use the ToolbarButton and ToolbarButtonRow and was told by the linter they are not experted.
Looking in the node_modules I can indeed not see them there, and it seems like most of the functionality is actually covered just by Button.
The only variant I don't see in Button which is in ToolbarButton is the orange outlined one.

I am using Grafana 8.1.4 and the node module I think I put on latest (I don't know the node eco-system very well) let me check. Seems like 8.1.4 as well, but that package-lock.json is a bit confusing.

![toolbarbutton1](https://user-images.githubusercontent.com/9572060/133911343-f8e87064-8d30-4b7f-b717-c17c54749d3c.png)

![toolbarbutton2](https://user-images.githubusercontent.com/9572060/133911344-90bdb0e2-e3ff-42d6-ac49-566ba0191a3b.png)

- [x] Component has a story in Storybook.

**Documentation**

- [x] Properties are documented.
- [x] Use cases are described.
- [x] Code examples for the different use cases.
- [x] Styling guidelines, specific color usage (if applicable).

Sorry if this was the wrong forum, I don't do this very often, also it is very possible I am just not getting it fully or something and the component is just hidden to me. In any case I am happy to use the other Button type.

**Comment by torkelo** [comment]
Make sure you @grafana/ui later than 7.4 and the ToolbarButton and ToolbarButtonRow are exported and there (in the Button folder), they some unique design properties and behaviors that the default button does not have and is only to be used inside PageToolbar

**Comment by TheApeMachine** [comment]
I checked the correct version of Grafana UI, it was 8.1.4

**Comment by TheApeMachine** [comment]
Would I not expect to see it here either?

![grafanauitoolbar](https://user-images.githubusercontent.com/9572060/133996215-86f2060a-eac9-4229-aa68-66ebf64cabaf.png)

**Comment by TheApeMachine** [comment]
I see now, in the Button folder, ok, thank you :)
