### ISSUE TITLE
Auto refresh hides backend error

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#3938]
When the backend (e.g. InfluxDB) responds with an error, there is a red triangle with an exclamation mark at the top left of the graph. Clicking it shows some information about the error.
If the time range has been set to automatically refresh, the refresh causes a new query and a new error, but the displayed error is hidden and only the dimmed dashboard shows.

It would be nice if either:
1. The error dialog would remain, regardless of new queries performed, or
2. The error dialog would be updated with a new error

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master (now error should not be cleared when inspector is open and refresh happens, the same error info should be there)
