### ISSUE TITLE
Azure Monitor: Log requests 

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#39393]
**What happened**:
Grafana for some reason closes the connection towards LA Query API. As for why, All we know is that: Net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Anything else we need to know?**:
Related to https://github.com/grafana/azure-data-explorer-datasource/issues/262. 

**Environment**:
- Grafana version: 7.5.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Feedback from Log analytics team:

>Our API supports Prefer:wait header (API Documentation (loganalytics.io)), which cancels long-running query automatically. Default is 3 min … which does not really matches 30 sec wait time of Grafana.
Once you are doing this change – is it possible to send the header, based on the timeout set for datasource? You can add additional 10-15seconds as a guard bend , to account for potential “race” conditions

**Comment by cheekp** [comment]
> Adding more detail to this - this error would occur if queries take longer to execute than the timeout specified. This timeout is taken from the config ini file (`timeout` under `[dataproxy]`) which defaults to 30 seconds.

I've not had much luck setting the timeout under dataproxy to extend the LA-API query to >3mins which I believe is needed to handle frequent poor execution times, throttling scenarios etc in the Log Analytics stack. Is the dataproxy timeout sent as the Prefer:wait header ?
