### ISSUE TITLE
Inconsistent use of cross in panel UI

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#3939]
Some panels/windows can be closed by clicking a cross icon at the top right. Examples are annotations settings, templating settings, error inspector dialogs etc.
![cross-is-close](https://cloud.githubusercontent.com/assets/3284111/12817356/e5419b16-cb51-11e5-95b1-d007ec5f8208.png)

However the popup that appears when you click on a panel has the same icon in the same place, with the meaning 'delete':
![cross-is-delete](https://cloud.githubusercontent.com/assets/3284111/12817355/e540eed2-cb51-11e5-8040-12c3abb4e2a7.png)

Perhaps the latter can be changed to something else, such as a trash can (as used in confirmation dialog), traffic sign etc. or at least given a different color and position to prevent confusion with the 'cross is close' interaction paradigm.

**Comment by mattttt** [comment]
I'd agree with this, and the trash can is a much better idea. Good catch @jessetan!

+1

**Comment by torkelo** [comment]
I agree, this is inconsistent, 

![image](https://cloud.githubusercontent.com/assets/10999/12817731/d3a2207c-cb53-11e5-8b73-f31649ae8233.png)

**Comment by torkelo** [comment]
change implemented!

**Comment by bulletfactory** [comment]
:+1:

**Comment by jessetan** [comment]
That was fast :) :+1:
