### ISSUE TITLE
Timepicker bug when using override relative time

### ISSUE THREAD

**Issue by evandro-portugal** [grafana/grafana#3941]
Hello,

I've found a strange behavior when using some of the quick intervals...
In my dashboard, I got some panels that have override time activated... the issue only happens when I select the options from the second column (Yesterday, Day before yesterday, and so on). When I pick any of them, all of my panels that have override activated just return nothing at all. The interisting part is, if I use the option, lets say, 'Last 30 days', and then use one of my graphs to drag just a time interval, all the panels with override time act normal..... So the issue only happen if I choose one of the options in the second column, AND if the override time dont get 'inside' of the selected option (panels with override of 24h works with the option 'Yesterday' for exemple.. because they get inside of the time range.. but for the others the option doesnt work).
If needed I can record this happening, but it is easily replayable... just create any panel with override time, and use any of the second column timepicker option

**Comment by torkelo** [comment]
thanks for reporting this, fixed in master
