### ISSUE TITLE
Stat-Panel: Sparkline/Graph is not updated when streaming

### ISSUE THREAD

**Issue by MrLight** [grafana/grafana#39425]
**What happened**: A Stat-Panel does not refresh the graph, when using a streaming datasource. The shown value is refreshed as expected. The sparkline isn't.

**What you expected to happen**: Refresh the sparkline in sync with the shown value

**How to reproduce it (as minimally and precisely as possible)**: Use a streaming datasource like the mqtt example.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.0
- Data source type & version: custom Datasource 
- OS Grafana is installed on: Windows
- User OS & Browser: Win + Chrome
- Grafana plugins: none (expect the custom Datasource)
- Others:

**Comment by torkelo** [comment]
@leeoniya having an issue with ^ , we never rebuild the UPlotChart config on data only updates in Sparkline.tsx , so when data (and data time range) change there is no change in the x range. 

Not sure how to fix this inside the Sparkline component without rebuilding UPlotChart config every update. The range function on the x scale is not being called on susequent renders with updated data. 

https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Sparkline/Sparkline.tsx#L118
