### ISSUE TITLE
Repeat Row creates new rows at bottom of dashboard instead of after row

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#3942]
I have a dashboard that has two rows, each of them has a "Repeat Row" functionality (for different template variables).  

When I select multiple values for the **first** row, it creates the repeated rows after the **second** row and not after the **first** row. This is disrupting the rational order of the dashboard.

**Comment by karolisc** [comment]
Hi,

I got same issue. Right now i have only one such "repeated row" so i moved
this row to the end of the dashboard.
This is temporary fix as in future i hope to introduce more "repeated row".

Karolis

**Comment by torkelo** [comment]
thanks for reporting this! 

fixed in https://github.com/grafana/grafana/commit/a167eb4fa1c21a03688ecc4f267ab2d914ead8f1
