### ISSUE TITLE
Docs feedback: /datasources/mssql.md

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#39428]
There is an inconsistency in the case of timeend on this page  (https://grafana.com/docs/grafana/latest/datasources/mssql/#annotations ) and 
timeEnd on this page (https://grafana.com/docs/grafana/latest/http_api/annotations/#create-annotation) 

This has caused at least one customer ticket.

**Comment by marefr** [comment]
That's two different things, Grafana builtin annotations (stored in its database) vs MSSQL based annotations. What change do you suggest, that MSSQL should support `timeEnd` and not only `timeend`?

**Comment by GrafanaWriter** [comment]
Please let us know if there's further clarification needed in the documentation based on @marefr comments.

**Comment by marefr** [comment]
Feels reasonable to me to close it.

**Comment by achatterjee-grafana** [comment]
Thank you @marefr
