### ISSUE TITLE
InfluxDB datasource with non-default retention policy

### ISSUE THREAD

**Issue by entone** [grafana/grafana#3943]
I'm unable to make queries against anything other than default retention policy, which for me is 24 hours for the real-time data. I then roll-up into 1 hour averages for the past month, and would like to query against that data. 

I'm using the InfluxDB 0.9.x datasource in proxy mode.

I'm also unable to find a raw query editor

**Comment by torkelo** [comment]
in 2.6 there is no support to change retention policy in the editor, you have to switch to text editor mode, you do this using the hamburger menu to the right of the query. 

In the upcoming version (3.0), you can select retention policy in the editor. You can find pre release builds for 3.0 here:
http://grafana.org/download/builds.html

![image](https://cloud.githubusercontent.com/assets/10999/12829417/36d56826-cb8a-11e5-8691-cde73617c62b.png)

**Comment by entone** [comment]
Ok, I'm only on Grafana v2.1.3, should probably update
