### ISSUE TITLE
Elastic: The "interval" variables are not displayed in the query interval 

### ISSUE THREAD

**Issue by tmpjg** [grafana/grafana#39445]
**What happened**: The "interval" variables are not displayed in the query interval 

**What you expected to happen**: Show "interval" variables are not displayed in the query interval like grafana 7.x

**How to reproduce it (as minimally and precisely as possible)**: Create an interval variable and try to select it as interval for your query. If you manually write the name of the variable in the field it can be used. 

**Environment**:
- Grafana version: Grafana v8.1.4
- Data source type & version: Elastic
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Firefox

**Comment by zuchka** [comment]
Hi @jerognlz 

Can you please provide more details? Are you using [the `$__interval` global variable](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__interval)? Do you think you could try describing, or uploading screenshots, that help us understand what: "'interval' variables are not displayed in the query interval like grafana 7.x" means?

If this is a problem with templating then your dashboard JSON might be useful 👍

**Comment by jerognlz** [comment]
Yes, no problem. I am using a custom variable to set the intervals for my queries. 

![variable](https://i.imgur.com/yLGEzog.png)

When I look for the variable in the interval of a query it is not listed. In previous versions this happened. 

![list](https://i.imgur.com/amD28wu.png)

My workarround is to manually write in that field the name of the variable and even though it says "create" it uses the one I created previously. 

![create](https://i.imgur.com/oXIAdCF.png)

**Comment by zuchka** [comment]
thanks, @jerognlz. can you please copy and paste your dashboard json as well? And put it inside a codeblock? ` ``` ` JSON here `  ``` `
