### ISSUE TITLE
Panel Sharing - Direct link rendered image shows (almost) empty page when the panel is of Text type, and it contains iFrames as contents (in HTML mode)

### ISSUE THREAD

**Issue by droidnxs** [grafana/grafana#3945]
I succeeded in getting Grafana's text panel (in HTML mode) to render an external embed URL (which is itself a chart from NewRelic). However, if I try to share this panel and convert it to an image it shows an empty page. This is the case regardless of the type of content the iFrame will render. 
![iframe-bug_1](https://cloud.githubusercontent.com/assets/12829882/12841346/2fe721ee-cc11-11e5-820a-a22418cafe7b.png)
![iframe-bug_2](https://cloud.githubusercontent.com/assets/12829882/12841348/2ff5f73c-cc11-11e5-8574-e707774b0418.png)

I'm using Grafana version 2.6. Let me know if you need any clarifications.

**Comment by torkelo** [comment]
The panel rendering is only supported for grafana panels, not iframes in text panel :(
