### ISSUE TITLE
TypeError: Unable to dynamically transpile ES module when using Material UI 5

### ISSUE THREAD

**Issue by Zemelia** [grafana/grafana#39461]
Hello!

I've got next error:
`TypeError: Unable to dynamically transpile ES module.
 A loader plugin needs to be configured via 'SystemJS.config({ transpiler: 'transpiler-module' })'`

When trying to use Material UI 5 (https://github.com/mui-org/material-ui)
Error on dev(watch) mode.
On plugin build(production) it works ok, is it possible to fix this somehow?
 
Best Regards!

**Comment by torkelo** [comment]
the dynamic plugin loaders (systemJS) does not support transpilation.  You need to bundle materiaul ui in your plugin webpack build

**Comment by torkelo** [comment]
no but bundle it with your plugins webpack build

**Comment by Zemelia** [comment]
> no but bundle it with your plugins webpack build

@torkelo what is the best way to do it acc. to the grafana plugins philosophy? Custom webpack.config.js in plugin root or something else?
Thanks!

**Comment by raakasf** [comment]
@torkelo @Zemelia I am running into the same issue, is there any way to do this?
