### ISSUE TITLE
[ feature-request ] Provisioning: Do not takeAwayWritePermissions when duplicate UID/Title 

### ISSUE THREAD

**Issue by commixon** [grafana/grafana#39467]
**What happened**:
This is not a bug per se, but rather a question on the intended functionality.

Recently a new and nice restructure on the duplicate Validator was added (https://github.com/grafana/grafana/pull/26742).

Besides adding some logging it also added the functionality to lock the whole database write permissions if duplicates are detected.

**What you expected to happen**:
By locking the whole write permissions, we have come to a situation where a duplicate dashboard will affect all dashboards provisions for everyone (sidecarProvider in our case).

Would it make sense to instead just skip this dashboard load, log this as an error and continue in the loop?

For more control, would it make sense to also expose those errors as prom metrics? (even if the database write permission lock is kept, would it make sense to introduce those metrics? at least get notified when grafana is in a "locked" state)

**Environment**:
- Grafana version: 8.1.2
- OS Grafana is installed on: kubernetes 1.21.0

**Comment by zuchka** [comment]
Hi @commixon thank for making this issue 👍 

Although you phrase your comments as questions, I think I'm going to tag this as a feature request and route it to the OSS backend folks. From there they will either take it on, or it will migrate into Github Discussions as a community feature request.

This is a fairly sophisticated question, but FYI for the future: generally we prefer that our community ask questions on community.grafana.com, request features on https://github.com/grafana/grafana/discussions, and report bugs here. This could lean into any of those categories so no worries 😎

**Comment by commixon** [comment]
Thank you very much for this @zuchka ! 

For anybody interested in this, let me give you an update of our situation. So, this is a great catch, the fact that we now handle duplicates in `validator.go`. And we found, because of this, some duplicate entries and were forced ("forced" is meant in a positive manner) to take care of them.

The problem we will potentially face in the future (having a lot of teams provisioning their dashboards) is that a potential duplicate will lock the provisioning for everybody. We have put some guidelines in place (like avoid hardcoding uids, make sure you have a unique title), but still someone at some point will copy paste a json file :) 

Besides querying logs, we have no way to know about this "locked" state, until someone comes and pings with something like: "Hey, my dashboards are not provisioned".

The idea we currently have is the following:
- Make the `takeAwayWritePermissions` functionality a config option
- Introduce maybe a prometheus metric, something like `grafana_provisioning_duplicates{type="uid|title"}`. Maybe this could be used for alerting or in general for dashboard provisioning observability. This could be implemented even if the above mentioned point is not accepted. WDYT?

Btw, we are willing to tackle this and create a PR if this is something you agree upon.

**Comment by an-mmx** [comment]
Thanks for the clarifications @commixon !

The idea of preventing creating dashboards with duplicated UIDs/titles is a great move. Meanwhile, I can't get why is OrgID ignored? With this new limitation, the dashboard provisioning feature becomes less effective and loses some cool features.

Let me clarify. 
We have many Provisioned Dashboards. Some of these dashboards have cross-links to other provisioned dashboards for better navigation and detailed metrics overview. And this is a very useful feature that comes from common dashboards. To build the cross-links in the provisioned dashboards, we should use predefined UIDs of the dashboards (there is no other way to form a link to a dashboard). On the other hand, we have multiple Grafana Organizations in our company. And now, with the new Validation, we are unable to combine cross-links with dashboard provisioning across multiple organizations.
However, this is not the only issue that comes with the new Validation feature. Another limitation is that it is not possible to provisioning a dashboard with the same title between multiple Organizations when the provisioned dashboard has no parent folder specified.

It would be correct if the provisioned dashboards Validation should be limited to OrgID. Thus it would be possible to provisioning the same dashboard with the same title/ UID between different Organizations.

**Comment by commixon** [comment]
Hey @zuchka ! Any update on this one?

**Comment by zuchka** [comment]
@commixon looks like the backend folks have labelled this as a feature request. I've routed it to the correct project board 👍

**Comment by dminca** [comment]
So basically there’s no way to provision such things automatically ;)

And Grafana folks don’t even want to make this simpler, thanks lads

**Comment by verejoel** [comment]
Not stale, this issue still affects us. A single UID clash leads to all dashboards not being loaded, effectively allowing a single hastily copy-pastad dashboard manifest to bring down our production dashboards without any warning 🙈
