### ISSUE TITLE
TypeError: Cannot read property 'grafana.sidemenu' of null in PLAYipp browser

### ISSUE THREAD

**Issue by joelabrahamsson** [grafana/grafana#3946]
We use a system from the vendor PLAYipp to control our TV-screens around the office. PLAYipp uses small Andriod media players from Rikomagic which are plugged into the TVs. These use Androids built in web view on KitKat 4.4.2. When using this system we can display most dashboards, such as Kibana and Klipfolio, without a problem. However, when we try to display Grafana using this system the screen is just black. 

After reporting this to the vendor they claim that it's the below JS error which is causing the issue.

![pasted image at 2016_02_05 09_23 am](https://cloud.githubusercontent.com/assets/218986/12841232/8e897d72-cbea-11e5-9646-190f9b63c1f6.png)

**Comment by bergquist** [comment]
For the sake of debuggabillity. Which url you using?

**Comment by joelabrahamsson** [comment]
On our own screens we use our internal Grafana but PLAYipp has tried it with http://play.grafana.org without getting it to work.

**Comment by daniellee** [comment]
This is going to be hard to recreate. I'm not seeing this error when emulating Androids in Chrome. I'll see if I can dig up an Android 4.4.2. As we don't really support mobile phones for Grafana, we don't have a testing lab for mobile support.

**Comment by playippniklas** [comment]
Hi Daniel, 
My name is Niklas Ljung, and I'm the Development Manager of PLAYipp AB. We would like to help troubleshoot this in any way we can. Would it help if we loan you one of our media players with a simple full-screen app with a web view on it, or can we give you access to any more information? 

Please send me an email at: niklas.ljung@playipp.com, and I can arrange this, or anything else you might need!

Have a nice weekend!

**Comment by daniellee** [comment]
Thanks @playippniklas! Email sent.

**Comment by daniellee** [comment]
Great news! @playippniklas says they have enabled local storage and fixed it on their side. They will be sending a patched version to @joelabrahamsson soon.
