### ISSUE TITLE
Grafana 8.1.4 Bar Chart issue: plot is not defined

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#39471]
**What happened**:
When I change some value on filter the panel Bar Chart have error or when I change options in settings (I mean to add label name or soft min)

![image](https://user-images.githubusercontent.com/73607094/134162066-4ea40a9d-3d10-48db-8cb4-5284c06c432e.png)
**What you expected to happen**:
Fix it

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: MS SQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Chrome
- Grafana plugins: Bar Chart
- Others:

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/pull/39304 in v8.1.5
