### ISSUE TITLE
viewers_can_edit config setting does not work in 8.1+

### ISSUE THREAD

**Issue by techgnosis** [grafana/grafana#39495]
**What happened**: 
When upgrading to Grafana 8.1+ the `viewers_can_edit`  setting in grafana.ini stops working. The specific symptom is that users with only the Viewer Org role are no longer able to use Explore.

**What you expected to happen**:
In 8.0* you can set `viewers_can_edit` in grafana.ini and users with only Viewer Org role can still use the Explore functionality. This allows you to assign Team permissions on datasources and let people in that team Explore on those datasources.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Grafana 8.0*
2. Set `viewers_can_edit` in grafana.ini to `true`
3. Login as a user with only Viewer Org role
4. You will see you are able to use Explore
5. Downgrade to 8.0*
6. Login with that same user with Viewer Org role
7. You can no longer use Explore

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1*
- Data source type & version:
- OS Grafana is installed on: Official Docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
https://play.grafana.org

is using viewers_can_edit set to true and the anonymous "Viewer" user can still access explore. And logging in  with a Viewer user I can also Explore.

Double check that your setting is set to true
