### ISSUE TITLE
Aggregated results in a Table from influxdb 0.9.x shows extra empty column

### ISSUE THREAD

**Issue by kiranprabhu** [grafana/grafana#3951]
If I have this query in Table Metrics
Select max("slot") as "TSlot", sum("count") as "Count" from "Slots" group by "slot"

It shows result in the Table with columns (Time,slot,TSlot,Count)
1. "TSlot" is shown as a separate column, in fact column "slot" header should be "TSlot"
2. Is there any way I can Hide Time Column?(I have intentionally kept Time column zero)
  
thanks

**Comment by torkelo** [comment]
the table mode will should tags you group by and fields you select, since you group by a slot tag, and select a slot field you will get two columns (slot and TSlot). 

You cannot currently hide the time column
