### ISSUE TITLE
LCD Bar Gauge shows as full when no data

### ISSUE THREAD

**Issue by MrBlood01** [grafana/grafana#39548]
Hello everyone,

I would like to know how to disable the "led" inside the "Bar Gauge" graph when it is not active, that is when there is **"No data"** as in this case:

![OEE AGOSTINO](https://user-images.githubusercontent.com/76105951/134463250-4ac0a0c4-837a-4199-9c62-587041cd658b.png)

**Versione di Grafana in uso: v7.5.7
Versione Bar Gauge: Versione integrata in Grafana 7.5.7 è viene mostrato il seguente messaggio: No plugin help or readme markdown file was found
Database utilizzato: Microsoft SQL Server 2012**

**Comment by torkelo** [comment]
was able to replicate this one here: https://play.grafana.org/d/ip6STFN7k/gauge-no-data2?orgId=1

**Comment by torkelo** [comment]
Thanks for reporting this!
