### ISSUE TITLE
Investigate and replace old url functions to use URLSearchParams instead

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#39551]
Investigate the need for functions like:
-  encodeURIComponentAsAngularJS (https://github.com/grafana/grafana/blob/b891af935a9c97c18ec477fa75d5923ddaafbd7d/packages/grafana-data/src/utils/url.ts#L28)
- toUrlParams (https://github.com/grafana/grafana/blob/b891af935a9c97c18ec477fa75d5923ddaafbd7d/packages/grafana-data/src/utils/url.ts#L38) 
- many more

Can they be replaced by `URLSearchParams` and other builtin functions?

**Comment by torkelo** [comment]
@hugohaggmark not sure URLSearchParams supports booleans as nicely (so `{ test: true }` just becomes `?test`,  it handles arrays a bit differently I think but not sure. 

 encodeURIComponentAsAngularJS should be something we can stop using

**Comment by ashharrison90** [comment]
hm, good point.
booleans we could probably deal with, but it handles arrays by specifying e.g. `['foo', 'bar']` as `?my-param=foo%2Cbar`, which i think would be impossible to distinguish from the string `'foo,bar'`.

although [stackoverflow reckons you can simply append the same query param multiple times to get the array behaviour we have](https://stackoverflow.com/a/38798000), so if we have an array we can loop through and `.append` i think. 🤔
