### ISSUE TITLE
LDAP not loading when set in config (defaults overriding conf file)

### ISSUE THREAD

**Issue by swartzd** [grafana/grafana#3957]
Have LDAP enabled in config (etc/grafana/grafana.ini) and ldap verbose enabled, I do not see LDAP start in the log:

2016/02/07 21:41:47 [I] Starting Grafana
2016/02/07 21:41:47 [I] Version: 3.0.0-pre1, Commit: v2.6.0+565-g6b7491e, Build date: 2016-02-01 05:02:14 -0500 EST
2016/02/07 21:41:47 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
  [2]: default.paths.plugins=/var/lib/grafana/plugins
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana
  plugins: /var/lib/grafana/plugins

2016/02/07 21:41:47 [I] Database: sqlite3
2016/02/07 21:41:47 [I] Migrator: Starting DB migration
2016/02/07 21:41:47 [I] Listen: http://0.0.0.0:3000

Changed it in /usr/share/grafana/conf/defaults.ini and it now starts:
2016/02/07 21:45:47 [I] Login: Ldap enabled, reading config file: /etc/grafana/ldap.toml

**Comment by torkelo** [comment]
The last line says it's enabled

**Comment by torkelo** [comment]
you should see more in the log when you attempt to login

**Comment by swartzd** [comment]
I agree; as I mentioned - it did not work until I changed the setting in the defaults file. It would not accept the setting from the regular config file
