### ISSUE TITLE
Prometheus metrics for HTTP 401 are not reported.

### ISSUE THREAD

**Issue by chaudyg** [grafana/grafana#39590]
**What happened**:
Prometheus metrics for HTTP 401 are not reported.

**How to reproduce it (as minimally and precisely as possible)**:
```
$ docker run -d -p 3000:3000 grafana/grafana
$ curl --user name:password http://localhost:3000 -I
HTTP/1.1 401 Unauthorized
$ curl -s http://localhost:3000/metrics | grep grafana_http_request_duration_seconds_count
# empty
# missing grafana_http_request_duration_seconds_count{handler="/",method="GET",status_code="401"} 1
...

```
**Environment**:
- Grafana version: v8.1.5 (c725a4259a)

**Comment by zuchka** [comment]
Hi @chaudyg thanks for making this issue. 

Did not work running an 8.1.5 binary on Debian 10, Ubuntu 20.04 or CentOS 8.  `200` and `302` codes but no `401`s. Also no `401`s when testing Cent8 + 7.5.9

* see below for outputs and version details

strangely Mac M1: 8.1.5 docker and binary return `401`s on the `api/live/ws` handler

```
curl --user name:password http://localhost:3000 -I

curl http://localhost:3000/metrics | grep grafana_http_request_duration_seconds_count
grafana_http_request_duration_seconds_count{handler="/api/live/ws",method="GET",status_code="401"} 1

...

FOO=$(curl -s http://localhost:3000/metrics | grep grafana_http_request_duration_seconds_count)
echo $FOO
grafana_http_request_duration_seconds_count{handler="/api/live/ws",method="GET",status_code="401"} 15

# grep (GNU grep) 3.7
# Packaged by Homebrew

# curl 7.64.1 (x86_64-apple-darwin20.0) libcurl/7.64.1 (SecureTransport) LibreSSL/2.8.3 zlib/1.2.11 nghttp2/1.41.0
# Release-Date: 2019-03-27
```

On debian 10 w/ 8.1.5 binary:
```
curl --user name:password http://localhost:3000 -I

HTTP/1.1 401 Unauthorized
Cache-Control: no-cache
Content-Type: application/json; charset=UTF-8
Expires: -1
Pragma: no-cache
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
Date: Thu, 23 Sep 2021 23:51:14 GMT

# returns a 302 but no 401
curl -s http://localhost:3000/metrics | grep grafana_http_request_duration_seconds_count
grafana_http_request_duration_seconds_count{handler="/",method="GET",status_code="302"} 1



# Virtualization: kvm
# Operating System: Debian GNU/Linux 10 (buster)
# Kernel: Linux 4.19.0-17-cloud-amd64
# Architecture: x86-64

# grep
grep (GNU grep) 3.3

# curl
curl 7.64.0 (x86_64-pc-linux-gnu) libcurl/7.64.0 OpenSSL/1.1.1d zlib/1.2.11 libidn2/2.0.5 libpsl/0.20.2 (+libidn2/2.0.5) libssh2/1.8.0 nghttp2/1.36.0 librtmp/2.3
Release-Date: 2019-02-06
```

**Comment by marefr** [comment]
It's currently not supported because the metrics middleware implementing executes at a later stage after authentication/authorization. 

We've resolved this for the [tracing middleware](https://github.com/grafana/grafana/blob/fe46a5afe706234919aa5cc13c1513cd3971e7f0/pkg/api/http_server.go#L410), but not yet the [metrics middleware](https://github.com/grafana/grafana/blob/main/pkg/middleware/request_metrics.go). Similar approach with metrics middleware as we've done with tracing middleware should resolve this I believe, but not currently something that's planned. So if anyone is interested working on this let us know and we're happy to help out.

**Comment by marefr** [comment]
I had a look at this one again and didn't seem like a lot of work so I opened a [PR](https://github.com/grafana/grafana/pull/44234) trying to resolve it.
