### ISSUE TITLE
Snapshots: Inspect data does not work for snapshot dashboards 

### ISSUE THREAD

**Issue by kmiroy** [grafana/grafana#39595]
**What happened**:  The inspect panel functionality is currently a bit broken for a snapshot, Data tab get's stuck at Loading....

**What you expected to happen**:  Expect to see the inspect data to work 

**How to reproduce it (as minimally and precisely as possible)**:  This behavior can be observed with any snapshot.

**Anything else we need to know?**:

**Environment**:  prod
- Grafana version: 8.1
- Data source type & version:  any
- OS Grafana is installed on:  kubernetes
- User OS & Browser: mac os & chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@kmiroy I updated the description and title to refer to panel inspect / Data tab, inspect query does not make sense for snapshots as there are no queries here, just captured data

**Comment by dclendenan** [comment]
@torkelo I rather disagree - snapshot dashboards are created as part of the development cycle for generated dashboards here at Salesforce, and not being able to inspect the queries as generated is severely limiting.   I'm not clear what you mean about it being only captured data, they are definitely live queries. 
  
FYI @kmiroy raised this based on a discussion we had yesterday.

**Comment by dclendenan** [comment]
For more context, the workflow is for dashboards created using jsonnet (grafonnet-lib) and uploaded via the API.  Our dashboards are relatively complicated, and have both chains of template variables and generated functions within panels which then take template variables as inputs.

**Comment by torkelo** [comment]
@dclendenan then you must be talking about something else, snapshot dashboards have no queries, when created (from the UI) they only contain the data that was shown at the time.

**Comment by torkelo** [comment]
you can see the process for creating snapshots here: 
https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/ShareModal/ShareSnapshot.tsx#L125 

All queries are removed, even from template variables, everything is frozen (snapshotted) as it's viewed in the browser. Snapshots are for capturing the visible dashboard at a moment in time to be able to share it and go back to it even when the data is lost or no longer available

**Comment by dclendenan** [comment]
@torkelo has that changed in Grafana 8.x?  We're on 7.1.5 and our API-generated snapshots seem to have all functionality except for the edit-panel and inspect-query options.  I can update all template variables and the choices made modify what's shown in other variables and the panels.
URL format is `http://grafana.internal.tld/dashboard/snapshot/UID?var-foo=something&var-bar=somethingelse`

**Comment by torkelo** [comment]
That feature is not supposed to be used from API , or rather it requires special frontend code to first capture the data and embed it into the dashboard json , and then removes all queries.

Try using it from the UI (share modal). If your using the API to store copies of full dashboards without embedded snapshot data then it's not really a snapshot, surprised it even loads and renders.
