### ISSUE TITLE
Dashboard solo with multiple panels

### ISSUE THREAD

**Issue by elinkev** [grafana/grafana#3959]
I have multiple graphs that i want to share on external website.

I create snapshot of the dashboard, and then put the source into an iframe. 
However i dont want users to use any of the functionalities such as - navigation, search, drag and drop graphs and so on. 
For that i use the dashboard-solo route (it only shows the graph, disabling other features).
It works fine for one graph, but if i want to share multiple graphs i have to create an iframe for each graph. 
Is it possible to define multiple graphs into dashboard-solo route? (something like ?panelId=1&panelId=2). Or maybe theres a way to share dashboard with disabled navigation?

**Comment by torkelo** [comment]
similar to https://github.com/grafana/grafana/issues/2420 so will close this
