### ISSUE TITLE
Clicking "Panel JSON" hides existing JSON display

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#3960]
1. Click hamburger icon for a panel
2. Click "Panel JSON"
3. JSON is displayed at top of page (do not close this)
4. Click hamburger icon for another panel
5. Click "Panel JSON"
6. JSON window is closed

Expected:
6. JSON window displays JSON of second panel

(Grafana 2.6.0)

**Comment by torkelo** [comment]
There can be only one edit window open at any time, this is by design.

**Comment by jessetan** [comment]
@torkelo I can understand that, but would it be possible to update the contents of the existing edit window?
