### ISSUE TITLE
Templating variable does up update

### ISSUE THREAD

**Issue by sslupsky** [grafana/grafana#3962]
I think I may have identified an issue where the templating variables do not appear to update.  In the first screen shot, I show the first of two variables "project".  The project variable is a custom variable containing five different values.   
 
<img width="963" alt="screen shot 2016-02-08 at 8 39 29 am" src="https://cloud.githubusercontent.com/assets/16888734/12890658/cbf3cede-ce41-11e5-9a48-747c3ad43a07.png">

In the second screen shot illustrates the definition of the "location" variable.  This variable queries Influx for a list of the measurements and filters them using a regular expression.  The regular expression uses the project variable so that we only return a subset of all the locations.

<img width="1130" alt="screen shot 2016-02-08 at 8 39 40 am" src="https://cloud.githubusercontent.com/assets/16888734/12890781/5a6c0334-ce42-11e5-9c65-086fb3526406.png">

In the third screen shot, when I select a project other than the first project in the list, the location does not update.

<img width="699" alt="screen shot 2016-02-08 at 8 40 16 am" src="https://cloud.githubusercontent.com/assets/16888734/12890816/826f485a-ce42-11e5-997b-3b071d86f806.png">

The only way to get the location to update is to select the project, save the dashboard and then reload the dashboard.  A refresh does not update the variable.

**Comment by torkelo** [comment]
you need to use your $project variable in your query, grafana will not check variable dependencies in the regex field, only the query field.

**Comment by sslupsky** [comment]
Referring to the second screenshot, where the query is "SHOW MEASUREMENTS", it is not clear how to structure a query to return a subset of the measurements?

**Comment by sslupsky** [comment]
Ok, I have figured this out.  I used the following query:

SHOW MEASUREMENTS WITH MEASUREMENT =~ /$Project.*/

Thank you @torkelo.
