### ISSUE TITLE
Panels oscillate between showing full data and "no data"

### ISSUE THREAD

**Issue by Southclaws** [grafana/grafana#39622]
**What happened**:

We were using Grafana 6 and I upgraded to see if this issue was fixed but it's not. It might be a prometheus or configuration problem but it's very difficult to search for.

It's best explained via a video:

https://user-images.githubusercontent.com/1636971/134770302-a77a12b3-d5f4-4567-a552-c3dd660d0f45.mov

This is on a 5s refresh, but it happens without auto refresh, you just have to be (un)lucky enough to load the page at the right time and most of the graphs will show "no data", but a couple of refreshes later and you see charts.

I opened the inspector and checked out some of the queries and a lot of them just return this:

```json
{"status":"success","data":{"resultType":"matrix","result":[]}}
```

Which is going through the grafana server side proxy to prometheus' API.

**What you expected to happen**:

If there's no data, it seems like there should be gaps in the data but when the graph renders normally, it shows all the data going back through the selected time range.

I would expect an error if there's actually no data available but I'm thinking this might be a prometheus issue rather than grafana - but figured I'd start here and see if anyone has any ideas.

**How to reproduce it (as minimally and precisely as possible)**:

Not entirely sure unfortunately, I have the exact same setup: https://github.com/picostack/core running on a few servers of mine and other people's and a couple of them do this, the rest don't. We can't figure out the exact differences between environments that may cause this. The configs are the same.

**Anything else we need to know?**:

**Environment**: Linux, Docker, This exact setup: https://github.com/picostack/core
- Grafana version: 8.1.5
- Data source type & version: Prometheus v2.18.1
- OS Grafana is installed on: Linux Ubuntu 20
- User OS & Browser: Mac, chrome latest stable
- Grafana plugins: None

**Comment by torkelo** [comment]
yea, looks like Prometheus returns an empty result (so not a grafana issue), maybe a load blancer that hits a different prometheus instance?

**Comment by Southclaws** [comment]
There's only a single prometheus instance in this setup and no load balancer, might be a bug then I guess. Thanks for the response, I'll head to the prometheus repo and open an issue there.
