### ISSUE TITLE
Stat panel does not have a relative min/max to the value anymore.

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#39629]
**What happened**:

When using grafana 7.5.7 and you create a stat panel including 3 different metrics, each metric would show the Graph mode: Area relative to itsef. That has changed with 8.x and now the min/max for all stat panels are related to the biggest min/max available in the stat panel
  
**What you expected to happen**:

I would like to have each Stat panel visualization to have a relative min/max for itself.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to https://play.grafana.org/d/cvDFGseGz/graphite-templated-nested?orgId=1&editPanel=1
2. Copy the series
3. Add `scale(1000)`
4. Observe the non-scaled series is now just a flat line on the bottom

![image](https://user-images.githubusercontent.com/8693064/134818528-c439ce10-81bb-4e8f-a1d4-a822efa44bca.png)

On this picture I would expect to be able to see the graph on the left (non-scaled) values.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.4 (6855cdff7c)

**Comment by torkelo** [comment]
This was actually a bug in v7.5 that we fixed in v8.0
https://github.com/grafana/grafana/issues/32765
