### ISSUE TITLE
Table panel value mappings not working

### ISSUE THREAD

**Issue by sylr** [grafana/grafana#39635]
**What happened**:

![Screenshot_2021-09-27_at_10-04-50_k8s-nodes-thanos_-_Grafana](https://user-images.githubusercontent.com/153052/134869137-0fb2b41f-0ac7-4647-be25-4cc9b8dab383.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

https://gist.github.com/sylr/878437d21b07a4f6c2188dc0d4220531

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser: MacOS / Firefox
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@sylr you also need to set Cell display mode to color background

**Comment by sylr** [comment]
Thanks!
