### ISSUE TITLE
Tempo: 404 when switching to datasource

### ISSUE THREAD

**Issue by BitProcessor** [grafana/grafana#39643]
**What happened**:
When in Explore and switching from any datasource to Tempo, the following happens:
![Screenshot 2021-09-27 at 12 05 39](https://user-images.githubusercontent.com/50638541/134888815-d3f5399c-c50a-4813-b11a-5356b2b42087.png)

**What you expected to happen**:
Grafana shouldn't try to query Tempo with an empty ID when simply switching from another datasource in the Explore window ?

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana 8.1.5
Go to the Explore window
Select a datasource (not Tempo)
Now switch to a Tempo datasource

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.5
- Data source type & version: Tempo
- OS Grafana is installed on: Kubernetes (Helm chart)
- User OS & Browser: Safari 15.0 ; Mac OS Big Sur 11.6

**Comment by BitProcessor** [comment]
Screen recording:
https://user-images.githubusercontent.com/50638541/134901742-67f18404-bcfe-4825-adb9-71fc376dc4a9.mov
Seems like the Tempo datasource, start the "run query" action when selecting it (see recording, top right "Run query" button).

**Comment by connorlindsey** [comment]
This has been fixed as of the 8.2.0-beta1 release and will soon be in 8.2.0 stable. Could you please update to the beta or wait for the stable version? I'm going to close this issue for now, but please re-open it if you experience the same issue on 8.2. Thanks!
