### ISSUE TITLE
FR: Link to Docs in Grafana

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#3965]
A lot of users, who are new to Grafana, need documentation links. It would be great if we can have link to 
```
http://docs.grafana.org/
```
as help/tutorial/docs.

**Comment by utkarshcmu** [comment]
May be in some submenu or a global "?" icon in some corner would be great.

**Comment by mattttt** [comment]
+1

We've talked about this before; I'll volunteer to get something proposed!

**Comment by utkarshcmu** [comment]
Thanks @mattttt :)

**Comment by utkarshcmu** [comment]
Also, may be for each individual feature there can be a link to its respective page. 

For example, 
1. On main datasource page , there can be a link to http://docs.grafana.org/datasources/overview/
2. On playlist page, there can be a link to http://docs.grafana.org/reference/playlist/
3. On panel editor, there can be a link to http://docs.grafana.org/reference/graph/

I think this would be better because when a user will try to play with any new feature which he is not aware of , he will get the exact link which should help him out on that page. 

Thoughts?

**Comment by bergquist** [comment]
@mattttt Would be great if we could get this in before 3.0 release :)

**Comment by utkarshcmu** [comment]
Looks like this is the only issue left to be resolved before 3.0.0 release. :)
I think this should not be blocker to 3.0.0. This can even make into 3.1.0.

**Comment by torkelo** [comment]
This is implemented in page footer  (on all pages except dashboard)
