### ISSUE TITLE
Dynamic Annotation for some panel within single dashboard

### ISSUE THREAD

**Issue by achmadns** [grafana/grafana#3966]
Annotation feature currently, AFAIK, is correlate static events into flowing data. Could you please add _dynamic annotation_ based on mouse over such like the one provided by [sematext](https://apps.sematext.com/spm-reports/mainPage.do?timeIntervalFilter_granularity=AUTO&timeIntervalFilter_startDate&timeIntervalFilter_startTime&timeIntervalFilter_endDate&timeIntervalFilter_endTime&timeIntervalFilter_dataRetentionHours&date-picker&timeIntervalFilter_compareToDate&startDate=1454936400000&endDate=1455022800000) so that we can correlate metrics besides static events?

Thank you.

**Comment by torkelo** [comment]
you can now add annotations directly from the graph panel, 
http://docs.grafana.org/reference/annotations/#annotations

**Comment by achmadns** [comment]
Awesome work Grafana team. Thank you very much.
