### ISSUE TITLE
Implement Prometheus graphLink and tableLink functions

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#39662]
Our implementation of Prometheus template functions `graphLink` and `tableLink` (described [here](https://prometheus.io/docs/prometheus/latest/configuration/template_reference/)) currently returns empty strings. We need to implement the Grafana equivalent of those functions, overriding the default implementation.

While Prometheus has separate links for graph and table representations of an expression, Grafana has both table and graph representations in the `/explore` page, so both `graphLink` and `tableLink` should output the same relative path.

Prometheus template functions already working on our side:
- [x] `humanize`
- [x] `humanize1024`
- [x] `humanizeDuration`
- [x] `humanizePercentage`
- [x] `humanizeTimestamp`
- [x] `title`
- [x] `toUpper`
- [x] `toLower`
- [x] `match`
- [x] `reReplaceAll`
- [x] `args`
- [x] `pathPrefix`
- [x] `externalURL`
- [ ] `strvalue`
- [ ] `graphLink`
- [ ] `tableLink`
- [ ] `query`
- [ ] `first`
- [ ] `label`
- [ ] `value`
- [ ] `sortByLabel`

Out of scope: `tmpl`, `safeHtml` (we don't have a use case for those).</div>

**Comment by armandgrillet** [comment]
On hold while @santihernandezc is working on external AM.
