### ISSUE TITLE
alerts not being created

### ISSUE THREAD

**Issue by dadamssg** [grafana/grafana#39688]
**What happened**:
I'm attempting to alert on a pm2 processes with a prometheus gauge with a value of either 1(up) or 0(down).

Here are my alert rules
![image](https://user-images.githubusercontent.com/881986/134985510-79502df6-dcba-44d9-a7db-08d447499dcf.png)
^ There's probably an easier way to do this

![image](https://user-images.githubusercontent.com/881986/134985579-0c795375-ae5e-428f-8c89-872cc55b8d38.png)

When I click the **Preview alerts** button, i can see one row in an alerting state.
![image](https://user-images.githubusercontent.com/881986/134985856-3e168277-9335-411b-b96e-c9ce2a590458.png)

If i save this and view the **Matching instances** the one that should be Alerting is still in a Normal state. 

![image](https://user-images.githubusercontent.com/881986/134986134-faddb661-b0d9-40c7-8c00-83795b4a1794.png)

Here is my notification policy
![image](https://user-images.githubusercontent.com/881986/134986521-7a739af6-95c6-46ad-bdcb-c1991bb2e9df.png)

**What you expected to happen**:
I expect an alert to be created and a notification to be sent. 

**How to reproduce it (as minimally and precisely as possible)**:
If you have a similar prometheus gauge, you should be able to set up a similar alert and test.

**Environment**:
- Grafana version: v8.1.3
- Data source type & version: prometheus v2.29.1
- OS Grafana is installed on: centos 7
- User OS & Browser: mac & brave
- Grafana plugins:
- Others:

**Comment by dadamssg** [comment]
there's definitely something i don't understand about the timing or there's a bug. on another alert i have set up, a server started alerting at 8:58pm last night
![image](https://user-images.githubusercontent.com/881986/135101836-69810719-5cb8-48dc-82e0-52937adc5c59.png)

I didn't get the notification until 10:04pm 
![image](https://user-images.githubusercontent.com/881986/135102014-bebd8142-79c7-4fd5-abbe-f690391a0449.png)

I resolved the issue around 12:15am today
![image](https://user-images.githubusercontent.com/881986/135102365-3f16f2aa-6992-49cc-8f30-459b56453909.png)

But didn't get the notification until 1:21am
![image](https://user-images.githubusercontent.com/881986/135102465-eebd91c8-93ce-4b44-a8cc-5cedd7d8dca5.png)

**Comment by gerobinson** [comment]
Hi, I'm going to close this issue but if it still occurs after upgrading to 8.1.7 please feel free to re-open it!
