### ISSUE TITLE
Stack option on Graph panel is showing invalid data

### ISSUE THREAD

**Issue by CptOrange16** [grafana/grafana#39683]
Hello everyone
I'm having some issues with the Graph Panel.

**What happened**:

I have data that sometimes has null values, which represent a gap in the execution of a certain algorithm.
When using a graph panel, instead of showing the gap, the graph shows data that does not exist, it seems to be trying to fill in the gap where the data is null.
When I view each series separately, the data shows the gap correctly.

**What you expected to happen**:
The graph to have an empty gap when i have null values.

**How to reproduce it (as minimally and precisely as possible)**:

**1. First create some dummy data with `TestDataDB`:**

* **Use the `Predictable CSV Wave` option to create the first 3 series:**
![image](https://user-images.githubusercontent.com/4366792/134952413-db5f8c33-2326-4497-9199-68518fef18e9.png)
* **Use the `Manual Entry` option to insert 4 values that make up the series with missing values:**
![image](https://user-images.githubusercontent.com/4366792/134952984-97e462a0-b2cc-4baa-b6e5-abce3c74bde7.png)
* **You should get something like this:**
![image](https://user-images.githubusercontent.com/4366792/134953123-8057ad0f-8717-4048-becc-3d778f620caf.png)

**2. Create a graph with  `Panel > Visualization> Graph`**
**3. Select a bar graph `Panel > Display `**
![image](https://user-images.githubusercontent.com/4366792/134953837-e7c367fc-d269-47a7-a34e-823995a8bd38.png)

**4. Activate the stack option in `Panel > Display > Stacking and null value`**
![image](https://user-images.githubusercontent.com/4366792/134953565-5e4bfea8-1905-4d71-8a01-7a7ebc3f1c62.png)

**5. The invalid data appears`**
![image](https://user-images.githubusercontent.com/4366792/134954045-f985ec76-05c8-4a59-8b41-31ba96ee5ad0.png)

**Environment**:
- Grafana version: Docker image grafana/grafana:7.3.4-ubuntu   
- Data source type & version: Dummy data from TestDataDB 
- OS Grafana is installed on:  My docker is running on a ubuntu 20.04 machine
- User OS & Browser: Windows 10 & Firefox
- Grafana plugins: TestDataDB

Thanks for reading
If you need any other info let me know

**Comment by zoltanbedi** [comment]
Hi @CptOrange16 thanks for the detailed bug report. Can you please try to use a newer version 8.1 and the new Time series panel. We deprecated the old graph panel and won't fix any bugs related to it. Let me know if this is an issue in the new panel and we can reopen this issue.

**Comment by CptOrange16** [comment]
@zoltanbedi updating to 8.1.2 and using the new panel fixed all these issues. Thank you

**Comment by zoltanbedi** [comment]
@CptOrange16 Thank you so much for confirming.
