### ISSUE TITLE
Grafana v8.1.5 添加zabbix5.0数据源 报错404

### ISSUE THREAD

**Issue by isslower** [grafana/grafana#39704]
**What happened**:
grafana添加zabbix源，报错zabbix 密码以及数据库密码核对过没有问题。报错404
![mysql-datasources](https://user-images.githubusercontent.com/45580748/135053105-7db7edd5-7734-427d-8e08-f1d040828b8f.png)
![zabbixi -datasources](https://user-images.githubusercontent.com/45580748/135053142-18495837-2bfd-48ff-abec-e0bf74cd1f94.png)

**Anything else we need to know?**:
grafana error log
`t=2021-09-28T16:37:55+0800 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/datasources/8/resources/zabbix-api status=500 remote_addr=10.15.3.209 time_ms=16 size=83 referer=http://10.15.3.42:3000/datasources/edit/jYLYA8H7z`

**Environment**:
- Grafana version:Grafana v8.1.5 (c725a4259a)
- Data source type & version:Zabbix 5.0.15
- OS Grafana is installed on: CentOS Linux release 7.2.1511 (Core) 
- User OS & Browser:Google Chrome  94.0.4606.54
- Grafana plugins: zabbix Version 4.2.4
- Others:

**Comment by torkelo** [comment]
looks like your zabbix server is returning 404 for that url

Please ask questions on the community site https://community.grafana.com
