### ISSUE TITLE
NO DATA alert notification should be sent, but error notifications are sent out.

### ISSUE THREAD

**Issue by Dhyanesh97** [grafana/grafana#39711]
**What happened**:
Error notification sent for an alert if there is no flow of data in the measurement.
Configured "Alert state if no data or all values are null" to NO DATA.

**What you expected to happen**:
Alert should be in Normal state and no alert (Error) notification should be sent.
Is there any way i can sent NO data alert when there is no flow of data in measurement instead of sending error alert notification ?
Even after configuring "Alert state if no data or all values are null" to Alerting, notifications are sent for Error. Instead NO DATA alert should be triggered.

**How to reproduce it (as minimally and precisely as possible)**:

Configure alert for bucket/measurement with no incoming data.

![image](https://user-images.githubusercontent.com/89400147/135066898-4c234f4b-ed9e-4b68-bc60-86bfcf9db784.png)

![image](https://user-images.githubusercontent.com/89400147/135066730-7452b962-0443-4d47-aeaa-07645e81b374.png)

![image](https://user-images.githubusercontent.com/89400147/135066941-70704bf5-cb82-4170-b9b4-c27f769bdff2.png)

![image](https://user-images.githubusercontent.com/89400147/135067832-71d0f7eb-057e-47ea-9250-441e58e6bb5d.png)

That error is "**input data must be a wide series but got type not (input refid)**"

![image](https://user-images.githubusercontent.com/89400147/135069227-f3be03ce-5cb1-4cc7-ba9d-5de6e0a2b143.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.0 - Docker
- Data source type & version: InfluxDb 2.0
- OS Grafana is installed on: "Ubuntu 18.04.5 LTS"
- User OS & Browser: Windows/Firefox
- Grafana plugins: 
- Others: 
[](url)

**Comment by ehuggz** [comment]
I experience the same behavior and was going to open an issue.

- Alert status is "Firing"
- Error is displayed
- Investigation reveals the alert is in error status, usually with no data returned from query
- Sometimes editing the alert, expanding the the no data and error handling and saving the alert will return status to 
"normal"

Grafana version: 8.1.7 - Graphana Pro Online
Data source type & version: Azure Logs
OS Grafana is installed on: Hosted by Grafana
User OS & Browser: Windows/Firefox
Grafana plugins:
Others:

**Comment by xCROv** [comment]
Getting the same problems here. When the alert has no data returned, the whole alert errors and triggers even with "Alert state if no data or all values are null" set to "OK" or "No Data". "Alert state if execution error or timeout" also set to "OK" still returns an alert being fired and the alert returning "Failed to evaluate queries and expressions: failed to execute conditions: input data must be a wide series but got type not (input refid)"

Environment: 
Grafana version: v8.2.3 (fb85ed6912)
Data source type & version: InfluxDb 2.0
OS Grafana is installed on: Ubuntu - Official Grafana Docker 
User OS & Browser: Firefox / Windows 10

**Comment by togarha** [comment]
I'm getting the same error, API error when no data is on the alert query:
```
input data must be a wide series but got type not (input refid)
```

**Environment:**
* Grafana version: grafana v8.3.4
* Data source type & version: Microsoft SQL 2019
* OS Grafana is installed on: Red Hat Enterprise Linux release 8.3
* User OS & Browser: Windows10 & google chrome
* Grafana plugins:
* Others:

**Comment by mahmutefe** [comment]
Also, I am receiving the same error still could not pass. I wrote many times everywhere. And no support. It seems we are on our own.

**Comment by yuri-tceretian** [comment]
Since PR https://github.com/grafana/grafana/pull/40540 went in 8.2 Grafana creates a special type of alert `DatasourceNoData` that can be either silenced or, preferably, routed to a different contact point than regular alert notifications.

**Comment by grobinson-grafana** [comment]
In the case of NoData Grafana is still expecting a valid time series frame, but it looks like when using InfluxDB we receive a frame that is considered invalid in Grafana (missing a time and value field). I think this is a bug in Grafana where it is assuming InfluxDB will work similar to Prometheus in this situation.

**Comment by Dhyanesh97** [comment]
@grobinson-grafana Can this issue be prioritized ?
It is too difficult to identify actual alerts and NO DATA (error) alerts. We are receiving bunch of error alerts when there is no data.
Expected - We should receive NO DATA alerts when there is no data so that we can take proper actions at the right time.

**Comment by armandgrillet** [comment]
The challenge is that we're waiting for the implementation of https://github.com/grafana/grafana-plugin-sdk-go/blob/main/data/contract_docs/contract.md#no-data-and-empty Grafana-wide or this contract should be implemented in https://github.com/grafana/grafana/tree/main/pkg/tsdb/influxdb. 

Alerting behaving like this is not due to a bug in Alerting but due to the way the datasource plugin returns data, which is why I have added the label `datasource/InfluxDB`.

**Comment by itsmylife** [comment]
We are aware of the issue. We have the fix when the backend migration is completed https://github.com/grafana/grafana/issues/65045

**Comment by bohandley** [comment]
Hi all and @grafana/alerting-squad Is this still an issue? InfluxDB Flux was returning a response that was causing errors in other situations, but with this fix we are now returning "No Data" as Frames are nil and this is consistent with the DataPlane project. 

I was not able to reproduce this bug locally but this fix should handle the no data response correctly without returning an error. Can you help us confirm this?

https://github.com/grafana/grafana/pull/65301
