### ISSUE TITLE
Multiple data sources for graph queries

### ISSUE THREAD

**Issue by stvnwrgs** [grafana/grafana#3972]
One graph is only capable of getting multiple queries from the same data source. What if you want to show multiple queries from different data sources? I think this could be a nice feature. You would be able to show data from different data sources in one graph.

I'm not into the code, but I think it should be quite easy to add the data source to each query instead of the complete graph?

**Comment by torkelo** [comment]
lucky you this is already implemented in Grafana v2.5 

Just switch to the built in "-- Mixed --" data source, then you can add queries of different types.

Example
http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=4&fullscreen&edit
