### ISSUE TITLE
Docs feedback: /http_api/admin.md - typo in "Reload provisioning configurations" API endpoint

### ISSUE THREAD

**Issue by ethirolle** [grafana/grafana#39734]
Under https://grafana.com/docs/grafana/latest/http_api/admin/#reload-provisioning-configurations:

```
POST /api/admin/provisioning/accesscontrol/reload
```

should read

```
POST /api/admin/provisioning/access-control/reload
```

I.e., there should be a hyphen in `access-control`.

I tested this, and confirmed that accesscontrol endpoint does not exist, while access-control does exist, and `POST /api/admin/provisioning/access-control/reload` works successfully to reload the the access control provisioning files.

**Comment by imrishabh18** [comment]
@zoltanbedi I would like to take tis up

**Comment by zoltanbedi** [comment]
Thanks @imrishabh18
