### ISSUE TITLE
Hitting 'e' on a row should open the Row Options modal, not the panel editor

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#39732]
**What happened**:

I opened the panel editor on a row using the keyword shortcut 'e'.

![Screenshot 2021-09-28 09-52-23](https://user-images.githubusercontent.com/3270755/135100945-5a7c3a3b-06c7-453d-8f5f-9243a67df8e8.png)

**What you expected to happen**:

I was expecting the Row Options modal to pop up.

**How to reproduce it (as minimally and precisely as possible)**:

1. Move the mouse cursor over a row.
2. Press 'e' on the keyboard.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.4
- Data source type & version:
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Firefox 92.0.1 on Fedora 34
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
To start with we can at least make this shortcut do anything  (ignore rows) 

https://github.com/grafana/grafana/blob/main/public/app/core/services/keybindingSrv.ts#L219

**Comment by ashharrison90** [comment]
hi @adeverteuil 👋 

i've raised a PR to prevent using `e` to edit the dashboard row, as that's definitely not the intended interaction.

i agree it would be nice if the row options modal appeared (as it does when you press the gear icon). that would be a bit more work. can i suggest you raise that as a separate feature request in github discussions and we can prioritise accordingly.

thanks again for raising this! 🙌
