### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by parthiuk** [grafana/grafana#39733]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by parthiuk** [comment]
Hi, 
1) I am using Influxdb2.0 stuff as my datasource and having Grafana 8 as my presentation layer
2) created a table at Grafana 8 using the above data source and would able to view the table with data
.3) At the table edit mode click "Transform" tab and tried to hide some of the columns.
4) pressed save button, came out of Edit panel, would able to view the table for few secs (until auto refresh takes place)
5) either i click refresh button or at auto refresh.  all the changes i did in above step 3) & step 4) goes away. And takes me back to Step 2)

Please help me to resolve this.

**Comment by parthiuk** [comment]
Hi,

I am using Influxdb2.0 stuff as my datasource and having Grafana 8 as my presentation layer
created a table at Grafana 8 using the above data source and would able to view the table with data
.3) At the table edit mode click "Transform" tab and tried to hide some of the columns.
pressed save button, came out of Edit panel, would able to view the table for few secs (until auto refresh takes place)
either i click refresh button or at auto refresh. all the changes i did in above step 3) & step 4) goes away. And takes me back to Step 2)
Please help me to resolve this.

**Comment by parthiuk** [comment]
I Used Google Chrome browser

**Comment by torkelo** [comment]
@parthiuk unable to replicate this

here I have a table result and table visualization, organize fields transform witch hides one column. 
https://play.grafana.org/d/Q3LQl_H7k/hide-fields?orgId=1&editPanel=2&tab=transform

We have no other reports like this, so it's very strange.

**Comment by parthiuk** [comment]
@torkelo, thanks for your reply.

I have removed all joins in the table query and tried with single flux script like following,  whatever the columns hidden at the transform tab. remain hidden, it is working as you shown, even after I click the refresh button.

from(bucket: "MyBucket")
  |> range(start: -15s, stop:now())
  |> filter(fn: (r) => r["_measurement"] == "app_health")
  |> filter(fn: (r) => r["_field"] == "Data.status")
  |> group()

However, if I introduce a simple one to one join like following, then the issue starts.  All the hidden column @ transform tab is exposed again when refresh button is clicked.

app_status = from(bucket: "MyBucket")
  |> range(start: -15s, stop:now())
  |> filter(fn: (r) => r["_measurement"] == "app_health")
  |> filter(fn: (r) => r["_field"] == "Data.status")
  |> group()

build_name = from(bucket: "MyBucket")
  |> range(start: -15s, stop:now())
  |> filter(fn: (r) => r["_measurement"] == "app_info")
  |> filter(fn: (r) => r["_field"] == "Data.build.name")
  |> group()

build_status = join(
  tables: {A:build_name, B:app_status},
  on: ["instance_address"]
) |> yield()

**Comment by torkelo** [comment]
can you show the data result of that join? without any transform? Does it change for each refresh? the only thing that could cause this is the data changes every refresh

**Comment by parthiuk** [comment]
Data in this join is dynamic time series data for example time, start, stop for table A and table B and application alive status, etc.

Since my range window is between 0 to 15 secs.  all my data are keep changing for every fetch.

to be more precise, only data changes every time, but not the table structure.  List of columns of both Table A & B will remain same all the time.

**Comment by parthiuk** [comment]
If this is a know issue in Grafana V8.0.6, is there any work around to resolve this? any patch ?
or which is the latest Grafana version, this scenario works fine?

**Comment by gabor** [comment]
hi @parthiuk , i think the problem can be that some of the flux data (tag-names-and-values) become part of the table-column-names and when that changes, your columns become unhidden.
please try this:

- set up everything as described
- add the "Organize fields" transform and hide some columns
- write down the names of the columns that you see inside the "Organize fields" tranform
- now press refresh, so that the problem happens
- again go to the "Organize fields" section, and check the names of the columns there. did it change?

if it changed, that is the problem. you might try to add a "rename by regex" transform before the "organize fields", to make the column name fixed, so that it does not change.

if it is not changed, please send us the names of the columns you see there, it might help us find the problem.
