### ISSUE TITLE
Time series: Stacked Null Values do not appear as connected, even if option is chosen

### ISSUE THREAD

**Issue by bnrubin** [grafana/grafana#39740]
**What happened**: 
Migrated from deprecated graph panel to new timeseries panel.  Graph sometimes has stacked null values, they are not connected even if **always** is chosen as the "connect null values" option. 

**New**:
![image](https://user-images.githubusercontent.com/1072440/135115414-71d01898-4875-4d39-9e31-791856af477e.png)
![image](https://user-images.githubusercontent.com/1072440/135115427-5a9f75e2-e754-4628-a88e-c403e848feb1.png)

**Old**:
![image](https://user-images.githubusercontent.com/1072440/135115480-d4b6ce12-a049-462e-a386-d69417e5dd28.png)
![image](https://user-images.githubusercontent.com/1072440/135115498-5686d7a7-50ed-49df-b804-a0951cf55652.png)

**What you expected to happen**:
Null values should be connected, always.

**How to reproduce it (as minimally and precisely as possible)**:
Have stacked null values on a timeseries panel, have always "connect null values chosen"

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.5 (c725a4259a)
- Data source type & version: Graphite
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Windows 10, Chrome 93
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
thanks for reporting this, can confirm that stacking does indeed ignore the connect null option (or that is at least the current effect)

Even with a single series, and stacking enabled: 
![Screenshot from 2021-09-29 14-51-40](https://user-images.githubusercontent.com/10999/135271970-ffb03ae5-d01a-4025-807c-926234f8317b.png)

**Comment by Dr4g0nM4st3r** [comment]
Some more Information to reproduce this Issue. -> 
https://community.grafana.com/t/null-as-zero-not-working-making-sense-of-graphs-with-gaps-missing-data-points-in-stacked-graphs/41530

**Comment by Dr4g0nM4st3r** [comment]
Thanks for your effort, I just tested the fix from #46069, unfortunately this seems to have no effect on this bug. The stacked null values are still incorrect. (Grafana 8.4.4 and Datasource MySQL)
