### ISSUE TITLE
grafana-3.0.0-pre1.x86_64.rpm plugins dir missing?

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#3974]
trying out grafana-3.0.0-pre1.x86_64.rpm	2/9/2016, 6:51:38 PM
getting the following:

![image](https://cloud.githubusercontent.com/assets/12600004/12927516/ef395eea-cf68-11e5-875d-44f35f242363.png)

log shows:
 Could not scan dir "/var/lib/grafana/plugins" error: lstat /var/lib/grafana/plugins: no such file or directory

**Comment by torkelo** [comment]
just tested latest build, seems to have been fixed, but improved logging and loading of plugins, and also added creation of plugins dir if (or at least grafana will try to create it)
