### ISSUE TITLE
Grafana Template Custom Variable value 'false' not getting populated on drill down detailed view of Panel

### ISSUE THREAD

**Issue by mavasaf** [grafana/grafana#39754]
**What happened**:
When I created a custom template variable. 
variable name - build_allow_failure 
values - true,false. 
I see the template variable with true and false selections for the user.

Create a table panel. 
List the records from Elasticsearch datasource in a table panel 
Apply the template variable filter in the lucene query for listing details based on the template variable selection. 
if true is selected, list the data for true values only. 
if false is selected, list the data for false values only. 

when the user selects the value - true or false, based on the selection the table panel reflects the changes. 

However, when the value 'true' or 'false' is selected and user clicks on the View on the Panel and goes into detailed view mode, the template variables are NOT passed on. 

https://URL/d/DashboardID/**DashboardName**?&var-build_allow_failure&viewPanel=37 

**What you expected to happen**:

expectation is the template variables values are passed on in the URL like below. 
when true selected
https://URL/d/DashboardID/**DashboardName**?&var-build_allow_failure=true&viewPanel=37 
when false selected
https://URL/d/DashboardID/**DashboardName**?&var-build_allow_failure=false&viewPanel=37 

**How to reproduce it (as minimally and precisely as possible)**:
Reproduce steps are given in details in the above section,. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.0.4
- Data source type & version: Elasticsearch 6+
- OS Grafana is installed on: Windows, Linux
- User OS & Browser:Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Try upgrading to v8.1.5, as this seems to work in v8.1
https://play.grafana.org/d/cvDFGseGz/graphite-templated-nested?orgId=1&var-app=backend&var-server=backend_01&var-interval=1h

**Comment by mavasaf** [comment]
I have tested in the play.grafana.org. I can replicate the same issue in there.

**Comment by mavasaf** [comment]
https://play.grafana.org/d/000000030/elasticsearch-custom-templated-query?orgId=1&var-host=server1&var-host=server2&var-isValid&viewPanel=1

I tried in the above dashboard, by adding a template variable as below
![image](https://user-images.githubusercontent.com/68710456/135545303-6f020785-0cb9-4672-9cd4-e57ddeee0164.png)

And then I go to the main dashboard page. select the filter values as true. 

then click the Panel Top 5 Servers, and go to detailed view
![image](https://user-images.githubusercontent.com/68710456/135545400-32a3aa3b-2c85-47c1-9256-2f8ec49effdf.png)

Once you are in the detailed view, the url turns out to be like below. Please note how that template variable **_isValid_** is not getting set. 

https://play.grafana.org/d/000000030/elasticsearch-custom-templated-query?orgId=1&var-host=server1&var-host=server2**&var-isValid&**viewPanel=1

the value true gets stripped off the url, any specific reason for this behavior ? 
same is the case, when you select **_false_** too.

**Comment by mavasaf** [comment]
@torkelo  - Can you please confirm ? and reopen this case ?

**Comment by mavasaf** [comment]
related MR - ? 
https://github.com/grafana/grafana/pull/35075
