### ISSUE TITLE
Y-Axis units(sec) rounding, tooltip using decimal fractions

### ISSUE THREAD

**Issue by dannygoulder** [grafana/grafana#3977]
Just set up a dashboard showing units in seconds on the y-axis.  The rounding on the y-axis looks confusing, and the tooltip shows a decimal fraction (expecting to see hh:mm instead).

Not sure which JS library is doing this - I did have a dig around but didn't figure it out.  Screenshot cannot upload due to content filter.  I will try and work around it

**Comment by dannygoulder** [comment]
![image](https://cloud.githubusercontent.com/assets/4175328/12939692/bbe1e95e-cfdb-11e5-83ba-467fc40a80bf.png)

**Comment by torkelo** [comment]
this should be fixed in v5
