### ISSUE TITLE
Grafana v8.1.2 (103f8fa094) new Alerting constantly pending

### ISSUE THREAD

**Issue by ThePeltonian** [grafana/grafana#39771]
**What happened**:
I created an alert using the new alerting system for memory watch on a windows server - the initial testing of a low threshold alert was successful - subsequent alerts stay in pending and show 2x of the same thing pending these just change each time the evaluate time completes

![grafana_Memory_pending_issue_1](https://user-images.githubusercontent.com/85627260/135259899-4708bd44-3398-436d-b897-8316c993d46d.PNG)
![grafana_Memory_pending_issue_2](https://user-images.githubusercontent.com/85627260/135259973-ab81932f-899b-4dfd-aea7-0cb4a301ee23.PNG)
![grafana_Memory_pending_issue_3](https://user-images.githubusercontent.com/85627260/135259997-f2facf26-3e0d-42ac-9685-bad23a25153d.PNG)
![grafana_Memory_pending_issue](https://user-images.githubusercontent.com/85627260/135260047-97625634-540d-4ef3-8d99-13abc55be4ce.PNG)

**What you expected to happen**:
Alert to fire

**How to reproduce it (as minimally and precisely as possible)**:
Create alert for memory
let it fire
change alert threshold

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.2 (103f8fa094)
- Data source type & version: Influxdb V2.0
- OS Grafana is installed on: Linux
- User OS & Browser: Win10 pro & Chrome
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
@grafana/alerting-squad fyi

**Comment by gerobinson** [comment]
Thanks for the issue! Can I ask if this alert has custom labels as from the last screenshot it looks like the value of `B` is used in a custom label called `Value`? If so then this will explain the pending alerts as Grafana uses labels to group alert instances, such that it will create a new alert instance each time the value of `B` changes.

**Comment by ThePeltonian** [comment]
Really? crikey I was not aware of this - I wondered why it worked on some that had that value set and not others

Probably could do with the documentation updating for the alerting to specify what can and cant be added to the custom tags

Will test this out first
