### ISSUE TITLE
Customised  logo (image) for the text  panel

### ISSUE THREAD

**Issue by areebahmushtaq** [grafana/grafana#3978]
is it possible to change the logo for the text panels in Grafana UI? I want to have my customized icon for it. What files needs to be changed?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/text/module.ts#L27 

why do want to do this?

**Comment by areebahmushtaq** [comment]
Company Requirement

**Comment by torkelo** [comment]
why the just the text panel icon?

**Comment by areebahmushtaq** [comment]
they gave me a customized layout, and required 4 buttons at the bottom of each dashboard. These buttons when clicked would take to a new dashboard(linked). So i basically used text panels for this. So i am now going to put this text panel like a button with the customized logo

**Comment by areebahmushtaq** [comment]
I dint explain you well. Here is what i want to do:
![image](https://cloud.githubusercontent.com/assets/17145427/12950190/c32ad7f0-d02d-11e5-8187-6579e8833707.png)


You see these 4 boxes they are actually text panels. I want to change them to pictorial form like given in the image. Is it possible? and where do i need to make changes?

**Comment by torkelo** [comment]
place html in the text panel :)

**Comment by areebahmushtaq** [comment]
oh thankyou so much :) 
I am just a beginner in web development
