### ISSUE TITLE
Links in the Grafana docs don't distinguish themselves

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39788]
**Steps to reproduce**:
Head to any page in the Grafana docs, [here](https://grafana.com/docs/grafana/latest/getting-started/) for example.

**Actual Result**:
The links are a different colour, but that is the only means of identifying them unless you are hovering over them with the mouse. This means that a user who struggles with colour identification might not be able to initially locate the links.

**Expected Result**:
The links should be identifiable without the need to hover over them. Examples for these include underlining or bold text.

**Relevant WCAG Criteria:** https://www.w3.org/TR/WCAG21/#use-of-color + https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=141#use-of-color

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by torkelo** [comment]
this is pretty common now days (GitHub itself does not underline links, only on hover)

**Comment by JoelHaslam** [comment]
It is common I agree, however you'll see that the WCAG website themselves do this (https://www.w3.org/) in any cases where links need to be distinguished from text. I am unsure whether this would be needed to match any success criteria, but just want to provide some useful feedback 😸
