### ISSUE TITLE
Only colour used to convey information

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39785]
It is important that information isn't displayed by using only colour. This means that someone who might find it difficult to identify certain colours find it hard to interpret the information provided and are left at a disadvantage.

**Steps to reproduce**:
There are examples at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1), or head to your nearest dashboard.

**Actual Result**:
Some examples that I pulled out:
![image](https://user-images.githubusercontent.com/63413067/135283016-87da8d63-00de-45d9-b76e-d308dc2eba90.png)
![image](https://user-images.githubusercontent.com/63413067/135283026-dcd74a7c-0e88-4f84-b4c9-9901ff9ed261.png)

Both of these graphs use colour to inform the user how the graph is linked to the entries in the legend.

**Expected Result:**
There are a few solutions to this problem, The most common example is to use both colours and patterns to help convey the information.

**Relevant WCAG Criteria:** [1.4.1 use-of-color](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=141#use-of-color) + [Success Criterion 1.4.1 Use of Color](https://www.w3.org/TR/WCAG21/#use-of-color)

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by torkelo** [comment]
thanks for the feedback, we are aware of this and hope to address at some point

**Comment by JoelHaslam** [comment]
Thank you! Will this be tracked anywhere, or should I just try to keep up to date with anything that has the `accessibility` label on it?

**Comment by JoelHaslam** [comment]
Hi @torkelo, do you know if there is a work item open that is tracking this work? I'd like to be able to check in to see if this has been progressed and that feels like the most sensible way?

**Comment by torkelo** [comment]
@JoelHaslam no progress or ETA, might be added to a the accessibility project at some future point ~6-12 months at most , or if community members comes with a contribution that is interesting
