### ISSUE TITLE
Do not plot more point than TSDB has

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#3979]
Hello,

Let's take an example, a cpu.idle metric, with a TSDB `avg` aggregator.
The server has 24 CPUs, so the `avg` aggregator is perfect to avoid values such as 2400%.

However, I would like Grafana to only plot samples TSDB really has.
`zimsum` aggregator allows this behavior, because it does not interpolate :
http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html
The drawback is that I'm now back with values such as 2400%...
Is there any way to ask Grafana to divide received values ?
An `avg` aggregator on TSDB side **without interpolation** would have been great !

Thank you very much for your help :+1: 

Best regards,

Ben

**Comment by torkelo** [comment]
This sounds like a feature OpenTSDB has to implement, might be solved in the future by https://github.com/grafana/grafana/issues/3677

**Comment by benrubson** [comment]
Perhaps fill policies is the answer ?
http://opentsdb.net/docs/build/html/user_guide/query/aggregators.html
