### ISSUE TITLE
Additional content has no escape key

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39795]
Where additional content appears on the screen due to the action of a user, we should be able to remove it if necessary.

**Steps to reproduce**:
Hover the mouse over anything that produces additional content, for example any of the icons located in the top right hand corner of the UI. Once the additional content (text underneath) appears, attempt to remove it without moving the mouse.

**Actual Result**:
Unable to remove content.

**Expected Result**:
By pressing on a key on the keyboard (instinctively the _Esc_ key) you are able to remove the additional text content.

**Relevant WCAG Criteria:** [1.4.13 - content-on-hover-or-focus](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus) - **Dismissable** section

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by torkelo** [comment]
Normally hover tooltips are not hidden using escape, only things that require click action (modals, popovers) and that should already work, but if you find a modal or popover that does not hide when hitting esc please re-open. But for tooltips the most popular component frameworks and apps are not hidden when you hit esc

**Comment by torkelo** [comment]
but on closer testing I did find that the time picker is not closing on esc which it should

**Comment by torkelo** [comment]
created bug for that https://github.com/grafana/grafana/issues/39806
