### ISSUE TITLE
Graphs don't have valid contrast ratio

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39794]
**Steps to reproduce**:
Head to [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) for example graphs.

You can use the _**Accessibility insights for Windows**_ app (or a similar tool) to compare the contrast ratios between two colours. Check the ratios of both a graph against the background, and two colours are next to each other on the same graph.

**Actual Result**:
The required contrast ratio for non-text content is 3:1

The two example graphs that I used were:
![image](https://user-images.githubusercontent.com/63413067/135291800-7ec4d280-5ec7-49f0-82a7-31b3b7c70114.png)

_**Graph against background**_
![image](https://user-images.githubusercontent.com/63413067/135292173-5192cc5e-660e-4593-9bca-450517c88df6.png)

Comparing the border of the top entry against the background produces a contrast ratio of 1.525:1.

_**Colours in the same graphs**_
![image](https://user-images.githubusercontent.com/63413067/135292620-23bd173f-2b12-4d1e-bce4-1d8156823c48.png)

Comparing the border of the orange against the red produced a ratio of 1.566:1

**Expected Result**:
All ratios to be 3:1 or higher.

There are a variety of solutions to fix this, examples that I could think of include bold, contrasting borders or perhaps some logic that calculates colours depending on which other ones are present.

I do understand that this might be difficult to achieve given the large amount of colours which get used for certain graphs.

**Relevant WCAG Criteria:** [1.4.11 non-text-contrast](https://www.w3.org/TR/WCAG21/#non-text-contrast)

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by torkelo** [comment]
Those are demo panels to showcase visualizations not real use cases and not the default colors Grafana picks by default, and all colors the user can override if they want higher contrasts. 

But we do hope to someday introduce a super high contrast default color palette to address both contrast and color blindness

**Comment by JoelHaslam** [comment]
Okay, thanks!

Are you able to provide me with any links to some documents that show you how to override these colours?

I appreciate that you’re working so hard to try and improve the accessibility of the UI!!

**Comment by torkelo** [comment]
Click on the colored line in the legend, opens the color picker
