### ISSUE TITLE
Unable to hover over certain additional content

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39801]
Taken from from https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus
```
Hoverable:
If pointer hover can trigger the additional content, then the pointer can be moved over the additional 
content without the additional content disappearing;
```

**Steps to reproduce**:
Using the example graphs at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1), hover your mouse over any graph that contains series of data. If you hover your mouse over the graph it will produce a text box containing information about the data at that point (time, date, value etc).

![image](https://user-images.githubusercontent.com/63413067/135299747-4c18ed77-5dee-4299-b7d2-0d670f41ca2d.png)

Attempt to get the additional content to persist while you hover your mouse over it.

**Actual Result**:
As you move your mouse, the box will move with it and change to represent the data wherever the mouse is currently at.

**Expected Result**:
There would be some mechanism possible to prevent the extra content to keep moving and allow you to hover your mouse over it instead.

However, I understand that being able to read the data wherever the mouse is is a useful feature so this might be tricky.

**Relevant WCAG Criteria:** [1.4.13 content-on-hover-or-focus](https://www.w3.org/TR/WCAG21/#content-on-hover-or-focus) - **Hoverable** section

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by torkelo** [comment]
It's a tooltip that moves with the mouse so hard to move on top of it, but you can click a data point and then it will stay in place and you can hover over the tooltip, but you need to click exactly on a data point for that to work

**Comment by JoelHaslam** [comment]
I thought I had tried clicking as I thought that would be a suitable alternative.

I will try again on my system to make sure that it works for me :)
