### ISSUE TITLE
Browser font size has no impact on text

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39804]
**Steps to reproduce**:
Example given is on Chrome, but for Edge it is a very similar process.

Go to your settings in Chrome.
![image](https://user-images.githubusercontent.com/63413067/135301289-729f52eb-81d6-4699-a154-42ea610aedce.png)

Click on the appearance tab on the left, and select customise fonts:
![image](https://user-images.githubusercontent.com/63413067/135302473-1d3b23d2-9a5a-4913-914a-38ce9e231ba1.png)

Use the font size slider to increase / decrease the size of the font. 
![image](https://user-images.githubusercontent.com/63413067/135302759-fa27744a-d09e-4d71-bd37-3ee196ce076f.png)

**Actual Result**:
I changed the font size from 16 -> 72, and the results are below:
![image](https://user-images.githubusercontent.com/63413067/135303163-ef4f3a5e-8e24-431a-9d0c-1014a55fcb88.png)

As you can see, there was no change to the size of the font. However you can get the font size to increase slightly by changing the `Minimum font size` slider up to max.

The behaviour is the same on both Google Chrome and Microsoft Edge. 

**Expected Result**:
I would expect the text in the UI to alter accordingly as the slider is altered.

An example of this working can be done using the [w3 website](https://www.w3.org/TR/WCAG21/#resize-text) (font size from 16 -> 22).
![image](https://user-images.githubusercontent.com/63413067/135304941-e7848228-d320-45a6-82f6-b87c047ab623.png)

**Relevant WCAG Criteria:** [1.4.4 resize-text](https://www.w3.org/TR/WCAG21/#resize-text)

**Environment**:
- Grafana version: 8.1.4
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by torkelo** [comment]
We do not support this option, to change font size use regular browser zoom (CTRL/CMD + `+`)
