### ISSUE TITLE
Alerting: Reduce number of requests to database in scheduler

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#39812]
When the scheduler service runs it executes a procedure that synchronizes rules as well as executes rule evaluation. As part of the procedure, it requests all alert rules 
https://github.com/grafana/grafana/blob/012d4f0905748ce4b54dd5fc141d10f62edfa6ce/pkg/services/ngalert/schedule/schedule.go#L334
Then it iterates through all results and creates a goroutine that evaluates a single rule. That go routine makes another request on its own to get the rule. 
https://github.com/grafana/grafana/blob/012d4f0905748ce4b54dd5fc141d10f62edfa6ce/pkg/services/ngalert/schedule/schedule.go#L447
Therefore, in the worst case, there are N+1 requests to the database. It is worth mentioning that the goroutine does not request the alert rule if its version is not changed.
This behavior can be improved because the first request made by the scheduler's synchronization loop already contains all rules and it can be provided to the evaluation loop when needed.

cc @gotjosh

**Comment by yuri-tceretian** [comment]
I think this is blocked due to peculiarities of how scheduler interacts with an evaluation loop of a single alert. The current approach has one feature (or a flaw, depends on the point of view): if the rule evaluation routine iteration is longer than the rule evaluation interval then scheduler will pile up commands, which then can be executed in random order. This needs to be addressed before we optimize calls to database.

**Comment by grobinson-grafana** [comment]
@yuri-tceretian I think I saw a PR to fix the order of evaluations right?

**Comment by grobinson-grafana** [comment]
@yuri-tceretian I think I've seen a PR to fix the order of evaluations right?
