### ISSUE TITLE
Fine tune down sampling

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#3982]
Hello,

To fine tune down sampling I created a dashboard template variable `interval`.

Could it be possible to have more tuning control over the auto interval ?
- adding some more auto interval steps (300,400,500) ;
- adding a minimum threshold for auto calculated interval (the calculated interval will not be allowed to be smaller than the specified threshold value, for example we have samples every 15 seconds, and we don't want Grafana to downsample below 15 seconds).

I also noted that when you specify an auto interval step, Grafana seems to round the result to pre-defined values. For example, a 60 minutes range with an auto interval step of `200` should give a sample every 18 seconds, however Grafana gives a sample every 30 seconds.
Why ?
Cant' it round to the nearest (or to the /5 nearest) second ?
I would have liked my auto interval settings to give me a sample every 15 seconds.

Thank you very much :+1:

Ben

**Comment by benrubson** [comment]
Hello,

Could we think about improving this behavior please ?

Thank you again,

Ben

**Comment by benrubson** [comment]
Pull requests #4103, #4105 and #4108 will close this issue.

Thank you :+1:

**Comment by benrubson** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/6764151/13214492/3fc33b4c-d950-11e5-9cfc-bc5658391bed.png)

**Comment by benrubson** [comment]
Thank you very much @torkelo !
Could we also think about merging pull requests #4103 and #4105, as they are also related to this bug report ? It would then be completely close :+1: 

Thank you again,

Ben

**Comment by felixbarny** [comment]
Nice!
Right now I'm configuring the minimum Interval in the metrics tab of the Graph panel:
<img width="368" alt="bildschirmfoto 2016-03-06 um 09 50 37" src="https://cloud.githubusercontent.com/assets/2163464/13553197/f13d98c4-e380-11e5-8049-9e37239c42ca.png">

Is this value also considered?

**Comment by benrubson** [comment]
I'm not sure it will give you the same behavior as the one described above, you should get more data points than you want for the biggest time ranges.
