### ISSUE TITLE
Varable values are not getting inside dashboard

### ISSUE THREAD

**Issue by mohan-nagandlla** [grafana/grafana#39821]
HI team i am using grafana 8.0.3. I was creating a dashboard inside and inside dashboard i was trying to create the variables.
The first variable is data source named as DS -> type Prometheus this is working fine.
Now second variable is trying to getting the namespace values dependent on the DS but it is not giving the values.
![image](https://user-images.githubusercontent.com/52690110/135388925-1e845f33-5e91-461d-a484-a652aae2d42c.png)
can you please help me to solve this

**Comment by odegraciajr** [comment]
How did you solve this issue?
