### ISSUE TITLE
"typescript:build" failed - Cannot find name 'Promise'

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#3983]
After updating grafana with the changes present on *master*, and running the _grunt_ command, the following error occurs:

> Running "typescript:build" (typescript) task
> >> public/app/app.ts(76,5): error TS2304: Cannot find name 'Promise'.
> >> public/app/core/directives/plugin_component.ts(66,28): error TS2304: Cannot find name 'Promise'.
> >> public/app/features/panel/panel_editor_tab.ts(20,14): error TS2304: Cannot find name 'Promise'.
> >> public/app/headers/common.d.ts(1,1): error TS6053: File 'public/vendor/npm/angular2/typings/tsd.d.ts' not found.
> >> public/app/headers/common.d.ts(2,1): error TS6053: File 'public/vendor/npm/angular2/manual_typings/globals.d.ts' not found.
> Warning: Task "typescript:build" failed. Use --force to continue.
> 
> Aborted due to warnings.

**Comment by torkelo** [comment]
run npm install :)

**Comment by antjori** [comment]
Thanks for the input!

In fact I did ran the `npm install` command before posting the error.

Don't know why but apparently I had to run it this way:

`npm install --unsafe-perm`

Now everything's okay.

BTW, I take this opportunity to ask you if you have any estimation on the release of grafana's v.3?

**Comment by torkelo** [comment]
@antjori grafana 3.0 beta release is 1-2 weeks away
