### ISSUE TITLE
Admin: overhaul admin page navigation 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#3984]

**Comment by mattttt** [comment]
Cool, is this what we're thinking - something like this?

![screenshot 2016-02-10 09 47 09](https://cloud.githubusercontent.com/assets/2886187/12950474/586dbe70-cfdb-11e5-9830-23372a92c255.png)

**Comment by torkelo** [comment]
yes :)

**Comment by torkelo** [comment]
fixed
