### ISSUE TITLE
No link between label and form

### ISSUE THREAD

**Issue by JoelHaslam** [grafana/grafana#39841]
In an ideal world, labels for form entries are directly linked and clicking on the label will place the cursor / focus into the form entry field. This helps out users who may struggle to consistently place the cursor within the sometimes small form entry fields.

**Steps to reproduce**:
Open up the [dashboard settings](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&editview=settings) UI and click on the label for the auto refresh form

**Actual Result**:
No change.

**Expected Result**:
The cursor to enter the text box underneath this label.

**Relevant WCAG Criteria:** [3.2.2 labels-or-instructions](https://www.w3.org/WAI/WCAG21/quickref/?showtechniques=332#labels-or-instructions)

**Environment**:
- Grafana version: 8.2.0-beta1
- Data source type & version: Default data used at [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1)
- User OS & Browser: Windows & Chrome
- Others:

**Comment by hugohaggmark** [comment]
Related to #35613

**Comment by natellium** [comment]
@thisisobate I was just trying to reproduce this in v8.3.0-41154pre and it seems to be working. Might have been fixed already?

**Comment by thisisobate** [comment]
@natellium the **auto refresh** label works but the **Now delay now** doesn't
