### ISSUE TITLE
Cannot connect to local postgres

### ISSUE THREAD

**Issue by mkolarek** [grafana/grafana#3985]
I am trying to connect to a local postgres db, this is in my grafana.ini

`[database]`
`type = postgres`
`host = localhost:5432`
`name = octophant_db`
`user = postgres`
`password = `

I get this error:
`[log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: dial tcp [::1]:5432: getsockopt: connection refused`

I can connect to the same postgres with pgadmin with the same settings. Should I handle the blank password differently? I need it to be blank unfortunately.

**Comment by torkelo** [comment]
Try this

```
[database]
type = postgres
host = localhost:5432
name = octophant_db
user = postgres
password = ''
```

Notice the empty password quotes

**Comment by torkelo** [comment]
but thanks for reporting this, I made a code change so that Grafana will add quotes if password or user field is empty. So your problem will not be encountered in future releases :)  But you do not need to upgrade the fix I stated in the comment above should work in the existing stable release.
