### ISSUE TITLE
MSSQL macros $__from, $__to, $__timeFrom(), $__timeTo(), not working properly

### ISSUE THREAD

**Issue by RyuunosukeDS3** [grafana/grafana#39850]
**What happened**: MSSQL won't get right Datetime from any macro
 
**What you expected to happen**: To be able to select the datetime from the grafana time picker

**How to reproduce it (as minimally and precisely as possible)**:

Run the code:

```SQL
SELECT DATEADD(ss, convert(float, $__from)/1000, '19700101') as 'from',  DATEADD(ss, convert(float, $__to)/1000, '19700101') as 'to',
convert(datetime, $__timeFrom()) as 'timeFrom', convert(datetime, $__timeTo()) as 'timeTo'
```

![image](https://user-images.githubusercontent.com/31015675/135451239-d3d0f5b3-fe84-444d-8e1d-bcd99df96f62.png)
![image](https://user-images.githubusercontent.com/31015675/135451271-99329e5b-0cb5-4a08-8604-3b0c9ac96869.png)
![image](https://user-images.githubusercontent.com/31015675/135451303-1e1eb174-3251-416d-8de1-d7871992d929.png)

**Anything else we need to know?**:

MSSQL while using Linked Server with iHistorian. Our servers save data on -03 GMT and when using the $__TimeFrom() and $__TimeTo() Macros they only return UTC. Same happens for 

Here is the SQLs
```SQL
declare @test as varchar(400)

set @test = CONCAT('SELECT TagName, TimeStamp as time, convert(float, "value") as Value FROM OPENQUERY
(iHist,''

SET
StartTime="',SUBSTRING($__timeFrom(), 1, 10), ' ', SUBSTRING($__timeFrom(), 12, 8),'",
EndTime="', SUBSTRING($__timeTo(), 1, 10), ' ', SUBSTRING($__timeTo(), 12, 8),'",
IntervalMilliseconds=1min,
SamplingMode=Calculated,
CalculationMode=average
SELECT * FROM ihRawData WHERE
TagName LIKE SERVER.FIT_42001_PV.F_CV'')')

execute(@TEST)
```

```SQL
declare @test as varchar(400)

set @test = CONCAT('SELECT TagName, TimeStamp as time, convert(float, "value") as Value FROM OPENQUERY
(iHist,''

SET
StartTime="', DATEADD(ss, convert(float, $__from)/1000, '19700101'), '",
EndTime="',  DATEADD(ss, convert(float, $__to)/1000, '19700101'),'",
IntervalMilliseconds=1min,
SamplingMode=Calculated,
CalculationMode=average
SELECT * FROM ihRawData WHERE
TagName LIKE SERVER.FIT_42001_PV.F_CV'')')

execute(@TEST)
```

The weird thing is that the generated SQL is as the following:

```SQL
declare @test as varchar(400)

set @test = CONCAT('SELECT TagName, TimeStamp as time, convert(float, "value") as Value FROM OPENQUERY
(iHist,''

SET
StartTime="',SUBSTRING('2021-09-29T12:14:54Z', 1, 10), ' ', SUBSTRING('2021-09-29T12:14:54Z', 12, 8),'",
EndTime="', SUBSTRING('2021-09-30T12:14:54Z', 1, 10), ' ', SUBSTRING('2021-09-30T12:14:54Z', 12, 8),'",
IntervalMilliseconds=1min,
SamplingMode=Calculated,
CalculationMode=average
SELECT * FROM ihRawData WHERE
TagName LIKE SERVER.FIT_42001_PV.F_CV'')')

execute(@TEST)
```

```SQL
declare @test as varchar(400)

set @test = CONCAT('SELECT TagName, TimeStamp as time, convert(float, "value") as Value FROM OPENQUERY
(iHist,''

SET
StartTime="', DATEADD(ss, convert(float, 1632917426238)/1000, '19700101'), '",
EndTime="',  DATEADD(ss, convert(float, 1633003826238)/1000, '19700101'),'",
IntervalMilliseconds=1min,
SamplingMode=Calculated,
CalculationMode=average
SELECT * FROM ihRawData WHERE
TagName LIKE SERVER.FIT_42001_PV.F_CV'')')

execute(@TEST)
```

![image](https://user-images.githubusercontent.com/31015675/135453435-1baca89a-e231-4b49-a857-8201ae728ff7.png)

The substrings are to remove the T and Z from the TimeStamp, since the iHistorian does not understand it that way.

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: MSSQL
- OS Grafana is installed on: Ubunutu Server (Docker)
- User OS & Browser: Windows, Chrome

**Comment by zoltanbedi** [comment]
Hi @RyuunosukeDS3,
Grafana expect the timezone of the SQL server to be UTC, if it is not UTC, that can cause a variety of unexpected results in the numbers retrieved from it.
Do you know if your MSSQL server:
is running on a server set for UTC timezone?
is storing timestamps in UTC timezone?

**Comment by RyuunosukeDS3** [comment]
Hello @zoltanbedi! It is not running in UTC nor storing data in UTC. The MSSQL is being used as a linked server with iHistorian which is the one who's actually storing the data. The iHistorian server, to my knowledge, is saving data on -03 time zone.

**Comment by dprokop** [comment]
@RyuunosukeDS3 Grafana requires the time to be stored in UTC. Here are some relevant threads on our community site that you may find helpful:

https://community.grafana.com/t/datasource-is-in-local-time-hilarity-ensues/7323
https://community.grafana.com/t/microsoft-sql-server-utc-to-localtimezone/6965
