### ISSUE TITLE
Crosshair not being shared between Time series and State timeline

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#39867]
**What happened**:
Corsshair is not shared between time series and state timeline panels.
![image](https://user-images.githubusercontent.com/19311511/135489475-c9d104cf-597f-4723-ac22-7356faab1dd2.png)

**What you expected to happen**:
The vertical line should be shared between panels.

**Environment**:
- Grafana version: 8.2.0-beta1

**Comment by zoltanbedi** [comment]
duplicate of #35908
