### ISSUE TITLE
Shared crosshair/tooltip should be scale-aware when showing the horizontal crosshair line

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#39868]
**What happened**:
When there are two graphs with different values in vertical axis, the horizontal line that is shared between graphs looks a bit strange.
![image](https://user-images.githubusercontent.com/19311511/135489991-68970e00-452f-478d-8cde-9475eed83167.png)

![image](https://user-images.githubusercontent.com/19311511/135490176-5133a18e-0670-47a2-8180-f3ce296ebd75.png)

**What you expected to happen**:
I think that only vertical line should be shared. It will also match the behaviour of old graph panels:
![image](https://user-images.githubusercontent.com/19311511/135490223-749a98f9-0118-47e2-b982-f37fa7f0f1aa.png)

**Environment**:
- Grafana version: 8.2.0-beta1

**Comment by dprokop** [comment]
@szerwi thanks for opening this issue. The sync currently works against a primary y scale ( first y scale encountered in the data set). Hence the crosshair ain't unit/scale aware. I'm marking this one a feature request.

**Comment by BennettGardiner** [comment]
@dprokop Are there any plans to implement this? It would hopefully be configurable to either have one of the lines or both, as having the horizontal line doesn't make a lot of sense for most use cases.
