### ISSUE TITLE
Time series time labels occasionally show date at 24h timerange

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#39869]
**What happened**:
I have last 24h timerange selected.
From time to time, individual panels show also date on the labels, instead of just the time:
![1](https://user-images.githubusercontent.com/19311511/135490649-489cd880-e6bc-4b08-abe3-8862efc5e520.png)

After a data refresh, time labels go back to normal:
![2](https://user-images.githubusercontent.com/19311511/135490870-3a7bcedd-f48b-4de6-85ad-dc5b39021a56.png)

Some time ago I have reported the same issue, but with old graph panels: #13650. However, that issue was fixed.

**What you expected to happen**:
Time labels should always be the same.

**Environment**:
- Grafana version: 8.2.0-beta1

**Comment by roe1974** [comment]
In which Grafana version will the fix flow in ?

**Comment by roe1974** [comment]
Any News about this bug ?
br Richard

**Comment by nmarrs** [comment]
@szerwi hi, just checking in to see that this is still an issue for you in the Time Series panel? If so, do you have a reproduction case for this? Thanks!
