### ISSUE TITLE
Datasource Plugin Documentation

### ISSUE THREAD

**Issue by makaveli0129** [grafana/grafana#3987]
We are trying to create a new datasource and were looking for any documentation relating to the development of the plugin for a new datasource. Any idea where this is?

**Comment by bergquist** [comment]
@makaveli0129 we are working on better documentation for plugins. We are currently reworking the plugin model for grafana 3.0. We are currently aiming on releasing a beta version end of February so I suggest you wait a few weeks or start looking at the graphite datasource in master.
