### ISSUE TITLE
[Bug] Generic Ouath2 flow generates incorrect redirect_uri when grafana is behind ingress proxy

### ISSUE THREAD

**Issue by mteodor** [grafana/grafana#39881]
**What happened**:

When trying to use `generic_oauth2` grafana generates incorrect `redirect_uri` causing Oauth2 provider to reject the request

**What you expected to happen**:
Successful oauth2 authorization flow executed

**How to reproduce it (as minimally and precisely as possible)**:

Grafana is deployed behind ingress nginx proxy which does TLS termination and forwards traffic to grafana

```apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-grafana
  annotations:
    nginx.ingress.kubernetes.io/proxy-buffering: "on"
    nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
    nginx.ingress.kubernetes.io/proxy-buffer-size: "256k"
spec:
  rules:
    - host: {{ .Values.ingress.tls.hostname }}
      http:
        paths:
        - path: /grafana/(.*)
          pathType: Prefix
          backend:
            service:
              name: {{ .Release.Name }}-grafana
              port:
                number: {{ .Values.grafana.port}}
  tls:
  - hosts:
    - {{ .Values.ingress.tls.hostname }}
    secretName: {{ .Values.ingress.tls.secret }}
```
Grafana is configured for oauth2 authentication

```
    [server]
      # Protocol (http, https, h2, socket)
      protocol = http
      # The ip address to bind to, empty will bind to all interfaces
      http_addr =
      http_port = {{ .Values.grafana.port }}

      # The public facing domain name used to access grafana from a browser
      domain = {{ .Values.ingress.tls.hostname }}
      root_url = %(protocol)s://%(domain)s/grafana/
      serve_from_sub_path = true
     ...
           #################################### Generic OAuth #######################
      [auth.generic_oauth]
      name = OAuth
      enabled = true
      allow_sign_up = true
      client_id = {{ .Values.oidc.client_id }}
      client_secret = {{ .Values.oidc.client_secret }}
      scopes = openid email profile
      email_attribute_name = email:primary
      email_attribute_path =
      login_attribute_path =
      name_attribute_path =
      role_attribute_path =
      id_token_attribute_name =
      auth_url = https://{{ .Values.oidc.host }}/auth/realms/{{ .Values.oidc.realm }}/protocol/openid-connect/auth
      token_url = value: https://{{ .Values.oidc.host }}/auth/realms/{{ .Values.oidc.realm }}/protocol/openid-connect/token
      api_url = https://{{ .Values.oidc.host }}/auth/realms/{{ .Values.oidc.realm }}/protocol/openid-connect/userinfo
      allowed_domains =
      team_ids =
      allowed_organizations =
      tls_skip_verify_insecure = false
      tls_client_cert =
      tls_client_key =
      tls_client_ca =
```

When accessing 
`https://{{ .Values.ingress.tls.hostname }}/grafana/` redirect to authorization service starts 
url generated:
`https://{{ .Values.ingress.tls.hostname }}/auth/realms/master/protocol/openid-connect/auth?access_type=online&client_id=CLIENT_ID&redirect_uri=http%3A%2F%2F{{ .Values.ingress.tls.hostname }}%2Fgrafana%2Flogin%2Fgeneric_oauth&response_type=code&scope=openid+email+profile&state=uTYrYd7-_SsXoZoS3A17ZNv0L1idnq9WOcsjxAMQmtE%3D`

redirect_uri must be https to match the settings in Oauth2 client settings

when `protocol` in grafana settings is set to `https` grafana requires certificate.
when I set `root_url` to `https://(domain)s/grafana/` , redirect_uri is proper but then I get the following error in grafana log
```
t=2021-09-30T19:58:52+0000 lvl=eror msg=login.OAuthLogin(NewTransportWithCode) logger=context userId=0 orgId=0 uname= error="Post \"value: https://iot-auth.mainflux.io/auth/realms/ashvin/protocol/openid-connect/token\": unsupported protocol scheme \"value\""
```
Looks to me that `X-Forwarded-Proto` header isnt respected when constructing the `redirect_uri`
**Anything else we need to know?**:

**Environment**:
- Grafana version: `image: grafana/grafana:7.5.2`
- Data source type & version:
- OS Grafana is installed on:  `image: grafana/grafana:7.5.2`
- Ubuntu  20.04, Chrome, Firefox

**Comment by kylebrandt** [comment]
Looking at the configuration:

`token_url = value: https://{{ .Values.oidc.host }}/auth/realms/{{ .Values.oidc.realm }}/protocol/openid-connect/token`

`value` should not be in there, which I believe lines up with the error. Closing this as I guess this is the problem (and apologies for such an old issue). But please reopen if that doesn't solve it.
