### ISSUE TITLE
Build: Postgres and MySQL integration tests fail with certifications error

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#39889]
**What happened**:

Currently we see Postgres and MySQL integration tests failing with the following error:

```
+ apt-get update
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [53.0 kB]
Ign:2 http://deb.debian.org/debian stretch InRelease
Hit:3 http://deb.debian.org/debian stretch-updates InRelease
Hit:4 http://deb.debian.org/debian stretch Release
Get:5 https://dl.yarnpkg.com/debian stable InRelease [17.1 kB]
Ign:6 https://deb.nodesource.com/node_14.x stretch InRelease
Get:7 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [719 kB]
Err:8 https://deb.nodesource.com/node_14.x stretch Release
  server certificate verification failed. CAfile: /etc/ssl/certs/ca-certificates.crt CRLfile: none
Get:10 https://dl.yarnpkg.com/debian stable/main amd64 Packages [10.4 kB]
Get:11 https://dl.yarnpkg.com/debian stable/main all Packages [10.4 kB]
Reading package lists...
E: The repository 'https://deb.nodesource.com/node_14.x stretch Release' does no longer have a Release file.
```

[Drone link](https://drone.grafana.net/grafana/grafana/35889/1/25)

**Anything else we need to know?**:

This has already been reported here --> https://github.com/nodesource/distributions/issues/1266

We need to add the workaround to our `build-container` and deploy a new version of it.

**Comment by dsotirakis** [comment]
This latest commit seems to be a temporary solution for the builds against `v8.2.x` to pass.

https://github.com/grafana/grafana/pull/39886/commits/87b3cd38e53ba9ae5ed6a2ab325c2b85f3e10b38

Keeping this open until we have a more viable solution.

**Comment by ifrost** [comment]
> This latest commit seems to be a temporary solution for the builds against `v8.2.x` to pass.
> 
> [87b3cd3](https://github.com/grafana/grafana/commit/87b3cd38e53ba9ae5ed6a2ab325c2b85f3e10b38)
> 
> Keeping this open until we have a more viable solution.

@dsotirakis Could this be added to v8.1.x as well? There's a few PRs waiting to be backported - https://github.com/grafana/grafana/pulls?q=is%3Apr+base%3Av8.1.x+is%3Aopen

**Comment by dsotirakis** [comment]
@ifrost, it can be done, but we figured out that just by bumping `build-container:1.4.1` to `build-container:1.4.3` works as it has more recent certs. So it's less painful :) 
I can help you bump the versions if you like.
