### ISSUE TITLE
Dashboard snapshots are having some graphs captured incorrectly

### ISSUE THREAD

**Issue by Rurouni** [grafana/grafana#3988]
Hi,

I am running into strange issue with dashboard snapshots, where after opening snapshot I see that some graphs are not captured correctly (they show one seemingly random data line with test-series-0 label). That behaviour affects random graphs , but I have noticed that it happens more often the slower underlying query is, like the timeout of query when making the snapshot is much smaller than normal...
I am using ElasticSearch data sources in dashboard and Grafana is version 2.6

Thank you

**Comment by torkelo** [comment]
this is due to snapshots requiring that all queries finish within 4 seconds, there is an open request to fix this situation, 
https://github.com/grafana/grafana/issues/2537

**Comment by bubulemaster** [comment]
Hi,

becarefull about datasource. I have same issue when I choose Mixed.

![grafana](https://cloud.githubusercontent.com/assets/11473190/17855150/54b77980-6877-11e6-96f4-c6fb62dc5463.png)

Regards
