### ISSUE TITLE
converting time columns failed: failed to convert time column: column type "[]*string" is not convertible to time.Time

### ISSUE THREAD

**Issue by JosuaJoker** [grafana/grafana#39892]
I have the following issue that the postgres request executed by Grafana does not work and gives some conversioning error. (See below the sgl_raw-request and the error-message in the response of the Grafana postgres request). I checked the raw request used by Grafana with the postgres client pgAdmin, where it is working fine and you can see the output in the picture.

![image](https://user-images.githubusercontent.com/76047547/135580916-6ada04b5-bc8a-4c22-a1db-3fb254907f36.png)

**What happened**:
Grafan throws the error message: converting time columns failed: failed to convert time column: column type "[]*string" is not convertible to time.Time

**What you expected to happen**:
I expect that grafana displays the data.

**How to reproduce it (as minimally and precisely as possible)**:
With two tables, both having a column time with timestamps in unixtime format with 10 digits,
one table has a value column and the other table a state column.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v 8.1.5
- Data source type & version: postgres 9.3
- OS Grafana is installed on:   Windows 10
- User OS & Browser: edge
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
Please check out https://github.com/grafana/grafana/issues/35484.

**Comment by JosuaJoker** [comment]
Hi zoltanbedi,
thanks for your reply and closing the issue. I also noticed few minutes ago, that in one table the time is saved as a string and converting it to an integer works for me.
