### ISSUE TITLE
Grafana Panel Plugin onClick handlers works in edit mode, but not on Dashboard

### ISSUE THREAD

**Issue by TheApeMachine** [grafana/grafana#39917]
**What happened**:
I implemented a Google Maps component as a grafana panel plugin, but lose the ability to attach onClick handlers.

**What you expected to happen**:
Click events would be picked up normally, which happens in edit mode, but not on the dashboard itself.

**How to reproduce it (as minimally and precisely as possible)**:
Add @react-google-maps/api react plugin to a bare-bones react panel plugin generated with the grafana toolkit add the example setup for the plugin and render a marker with an onClick prop defined.

**Anything else we need to know?**:
I have tried narrowing the issue down to maybe a zIndex issue or something, but nothing is really helping.

**Environment**:
- Grafana version: 8.1.4
- OS Grafana is installed on: Pop OS Linux and Flatcar Linux (but I use the official docker image)
- User OS & Browser: Firefox 92.0
- Grafana plugins: None

I have attached 3 images, the first two showing the behavior when in edit mode, where it renders "here" in the console when a marker is clicked, and the third where I am clicking but nothing is logged. Interestingly making a marker 'draggable' also does not work and it will drag the map itself vs the marker.

![grafana-click1](https://user-images.githubusercontent.com/9572060/135645327-dfb485cc-90f6-49c1-8ca6-2d6af7e942c8.png)
![grafana-click2](https://user-images.githubusercontent.com/9572060/135645332-790c3239-bc56-456d-ac78-961ce2bc9288.png)
![grafana-click3](https://user-images.githubusercontent.com/9572060/135645333-5527335e-3f02-4297-95a0-000516d6d027.png)

**Comment by TheApeMachine** [comment]
Well, I don't know... Rendering a custom marker, which I was planning to anyway, seems to make it work...
Happy to close this, unless you want to investigate the default situation.

![grafana-click4](https://user-images.githubusercontent.com/9572060/135647582-72926ae2-d68d-471d-8794-1b597af83a69.png)

**Comment by torkelo** [comment]
Not sure there is much Grafana can do, looks like an issue with the lib

**Comment by TheApeMachine** [comment]
I think it's an issue with the combination, otherwise it would also not function in panel edit mode. Anyway, after a long journey I have all my plugins done :) I am hoping the company will allow me to do some write ups on the implementation, because this was hard to figure out :) Have a good day.
