### ISSUE TITLE
Logs volume panel should hide when live-tailing logs

### ISSUE THREAD

**Issue by dannykopping** [grafana/grafana#39915]
**What happened**:
I selected the _Live_ option to tail my logs, and the *Logs volume* is still present.

**What you expected to happen**:
The **Logs volume** panel should disappear because it is irrelevant on this page.

**How to reproduce it (as minimally and precisely as possible)**:
Run Grafana with the new `fullRangeLogsVolume` feature toggle on.

**Anything else we need to know?**:
This panel should probably be minimizable when it is not needed or is not toggled.

**Environment**:
- Grafana version: v8.3.0-36009pre (4dadb8fc51)
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ifrost** [comment]
Fixed by #40327
