### ISSUE TITLE
Read a parameter from URL

### ISSUE THREAD

**Issue by parthiuk** [grafana/grafana#39910]
**What happened**:    Tried to use data link to pass value from a dashboard cell to another cell. from the source cell managed to update the dashboard url with parameter    var_instance = a.b.c.d:xxxx, But, not able to read this parameter value from destination cell, hit with error, please see the snapshot

**What you expected to happen**:  destination cell should read the value without error

**How to reproduce it (as minimally and precisely as possible)**:  Please follow the snapshot

**Anything else we need to know?**:

**Environment**:
- Grafana version:     Grafana 8.0.6
- Data source type & version:     InfluxDB2.0
- OS Grafana is installed on:     Linux
- User OS & Browser:    Google Chrome
- Grafana plugins:     Nil
- Others:   Please help to read parameter from url, or suggest me other way to transfer data between cells in dashboard

![image](https://user-images.githubusercontent.com/18166763/135622018-d2c1130a-a302-42f0-8823-17b57125dc61.png)

**Comment by torkelo** [comment]
you need to define this as a dashboard variable (you can define it using custom variable type), then you can set it in URL using `var-<varname>=value` syntax
