### ISSUE TITLE
CI: Make `validate-scuemata` not depend on `build-backend` step

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#39924]
In our CI pipeline, `validate-scuemata` currently depends on `build-backend`, which makes it also depend on `test-backend`. The checks in that command essentially amount to linting, and they should be able to be run early in testing pipelines. If it's possible to do without too much surgery, it'd be great to remove this dependency in order to get faster feedback from these steps. 

The difficulty, i imagine, is that the command being run depends on `grafana-cli`, which is (i imagine but have not verified) an actual build artifact output of `build-backend`. If that's the case, it's probably more work than we want to do right now to change this, as we'd have to refactor the code out into some standalone main.go. Even in that case, though, we can keep this issue open as a reminder of the goal.

(My actual concern is for the `ensure-cuetsify` step introduced in #39922, but it depends on `validate-scuemata`, so this all applies equally)

cc @dsotirakis

**Comment by dsotirakis** [comment]
Makes sense to have a different CI step to only build `grafana-cli` I think. I'll assign it to me.

**Comment by sdboyer** [comment]
this is long-since done
