### ISSUE TITLE
not able to connect grafana datasource to opennms 

### ISSUE THREAD

**Issue by masoudSeraj** [grafana/grafana#3992]
hi, I am trying a simple network project in network management using opennms and grafana on windows 7.
grafana and opennms servers are succefully up but when I add a new data source and test it, I face this error on grafana:  "Get /opennms/metrics/find HTTP 1.1" 404 not found...

here is grafana:
![1](https://cloud.githubusercontent.com/assets/17166435/12959506/828670d4-cfeb-11e5-89b0-5e1604afe70c.PNG)
and the error:
![2](https://cloud.githubusercontent.com/assets/17166435/12959621/210781bc-cfec-11e5-9324-df8e5d559525.PNG)

I want to know why this could happen, what can I do to solve this?
note that I use port 8085 for grafana.

**Comment by torkelo** [comment]
not sure, looks like opennms is not implementing the graphite api correctly. Please contact OpenNMS
