### ISSUE TITLE
Playlist remove button missing

### ISSUE THREAD

**Issue by Sebi94nbg** [grafana/grafana#39929]
**What happened**:

I've added a playlist for testing the feature and afterwards, I wanted to remove it, but there is no button to remove as stated in the docs: https://grafana.com/docs/grafana/latest/dashboards/playlist/#delete-a-playlist

**What you expected to happen**:

I want to be able to see a button, which allows me to remove a playlist from Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

1. Base installation of Grafana
2. Create a new dashboard or import an existing one
3. Go to (Manage >) Playlists
4. Add a new playlist
5. Try to remove the playlist

**Anything else we need to know?**:

This issue seems to exist since at least Grafana 8.1.2: https://stackoverflow.com/questions/69134277/grafana-playlist-remove-button-not-seen

**Environment**:
- Grafana version: 8.1.2 and 8.1.5. (verified; others and olders are maybe also affected)
- Data source type & version: Prometheus 2.30.2
- OS Grafana is installed on: Debian 10 (buster)
- User OS & Browser: Windows 10 64bit (all available Updates are installed), Google Chrome 94.0.4606.61
- Grafana plugins: None (default installation)
- Others: N/A

**Comment by ivanahuckova** [comment]
@Sebi94nbg this was fixed in https://github.com/grafana/grafana/pull/38120 and was part of 8.2.0-beta1 release.
