### ISSUE TITLE
Data link option is missing in Heatmap

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#39925]
**What happened**: There is no option to add data links for heatmap
![image](https://user-images.githubusercontent.com/63325084/135697072-4f5c31c6-4be8-4efa-9618-f15babcef1d0.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.5 
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Heatmap is the only remaining legacy panel, we will introduce a new heatmap panel in an upcoming release 

https://github.com/grafana/grafana/issues/39936
