### ISSUE TITLE
X Axis Values repeat themselves

### ISSUE THREAD

**Issue by reuvygroovy** [grafana/grafana#39935]
![image](https://user-images.githubusercontent.com/1325158/135807498-f6b0f834-81c6-4f74-8c45-1f1bfe864f82.png)

I see the values on the graph repeat themselves
19.00 over and over again

This is the data
![image](https://user-images.githubusercontent.com/1325158/135807549-ff2bbe83-2615-4b11-a57a-7af352352e96.png)

We are using Grafana v8.1.2 (103f8fa094).

We are using a SQL Server datasource

**Comment by torkelo** [comment]
you will have to manually increase the decimals (under standard options), with some data sets the auto decimal count is not optimal 

https://github.com/grafana/grafana/issues/35838
