### ISSUE TITLE
Changing date by time picker resets panel relative time

### ISSUE THREAD

**Issue by baur** [grafana/grafana#39933]
**What happened**:

Changing date by time picker resets panel relative time

**What you expected to happen**:
The relative time of the panel must be fixed on the panel and should not change by time picker

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/2898361/135794373-611e1dba-75db-4404-b46e-b6e5ec45615c.png)

With preset values OK!
![image](https://user-images.githubusercontent.com/2898361/135794434-943815f9-3138-4ab6-8bf0-4b7affe13908.png)

but custom value changes panel time

![image](https://user-images.githubusercontent.com/2898361/135794485-e4f86d2e-4f6a-472a-ac2b-c03490574907.png)

**Anything else we need to know?**:

**Environment**:  
- Grafana version: v8.0.2 (5c5d45e19f) - v8.2.0-beta2 (a2306d2765) 
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows10
- User OS & Browser: Chrome

**Comment by baur** [comment]
https://play.grafana.org/d/000000041/time-range-override?orgId=1&from=1633284000000&to=1633370399000

![image](https://user-images.githubusercontent.com/2898361/135817178-f72a2a0d-3cec-41ea-a775-4091c52d13b4.png)

**Comment by torkelo** [comment]
this is by design so you can zoom into panels with relative time override, 

Here is a feature request for absolute panel time overrides 
https://github.com/grafana/grafana/issues/11552
