### ISSUE TITLE
400(Bad request) when creating an org with name existed

### ISSUE THREAD

**Issue by schen59** [grafana/grafana#3993]
I am trying to use REST API to create a new org with same name as existing org. It throws error like "Organization name taken" with status code 400. However, I think is it more appropriate to send status code 409(status conflict)?

**Comment by torkelo** [comment]
thanks for reporting this, your right!  fixed in https://github.com/grafana/grafana/commit/53f5cb6553d9d2e1b01e7eda74d12714e4eaa41e

**Comment by schen59** [comment]
great. Thanks for the update.
