### ISSUE TITLE
Status History title css broken

### ISSUE THREAD

**Issue by baur** [grafana/grafana#39934]
**What happened**:

v8.2.0-beta2 (a2306d2)

![image](https://user-images.githubusercontent.com/2898361/135796689-0a0d4f88-c284-44b9-aaad-5e27a79ce0e7.png)

![image](https://user-images.githubusercontent.com/2898361/135796772-9a59d7fd-effe-4b32-9880-531607318a62.png)

**What you expected to happen**:

v8.0.2 (5c5d45e)

![image](https://user-images.githubusercontent.com/2898361/135796565-afc630c5-e5e5-4432-9067-2bbc301a1839.png)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.0-beta2 (a2306d2)
- Data source type & version: MSSQL
- OS Grafana is installed on: Windows10
- User OS & Browser: Chrome

**Comment by torkelo** [comment]
Can you switch to table view while in panel edit and show what that shows? 

And inspect / JSON / Data frame structure, can you paste that here?

**Comment by baur** [comment]
Now works fine. can't reproduce it,
Maybe problem with cache ...
