### ISSUE TITLE
Spark lines not working for single stat panel = Grafana GitHub Code + InfluxDB

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#3996]
Duration : I selected different time ranges (Today, Last 1 Week, 10 Days, 90 Days). Spark line never shows up.

<img width="1373" alt="screen shot 2016-02-10 at 6 05 08 pm" src="https://cloud.githubusercontent.com/assets/406777/12967996/f6f5e82a-d020-11e5-93b7-6cadd0b5c076.png">

**Comment by torkelo** [comment]
what does your query look like?

**Comment by deepujain** [comment]
SELECT sum("count") FROM "dataquality" WHERE "alertId" = '1' AND $timeFilter

Time: Today / Last 1 Week / Custom Dates.

**Comment by torkelo** [comment]
That query only returns one datapoint , so impossible for grafana to show sparkling :)

**Comment by deepujain** [comment]
How do i group By date ?

SELECT sum("count") FROM "dataquality" WHERE "alertId" = '1' AND $timeFilter GROUP BY $timeFilter

**Comment by deepujain** [comment]
> select sum(count) from dataquality where time>'1' group by time(1d)
name: dataquality
-----------------
time	sum
0	1800

>

**Comment by deepujain** [comment]
Resolved: SELECT sum("count") FROM "dataquality" WHERE "alertId" = '1' AND $timeFilter GROUP BY time(1d) fill(null)

**Comment by deepujain** [comment]
Value  (Current)
Spark Line  (History)

How can one single query return two different sets of data so that grafana can render data ?

I want to Value (Green/Red) to by show for today and i want spark lines to show value that is grouped by days (so that history line is shown).

**Comment by torkelo** [comment]
you query for 1 or more data points (more than 1 if you want sparkline) you select what the value should be in the options tab (average, current, min, max)
