### ISSUE TITLE
The link to the Table Panel Showcase in the Grafana Playground is broken 

### ISSUE THREAD

**Issue by JordanHilder9** [grafana/grafana#39967]
This link on the Grafana website is broken: https://play.grafana.org/dashboard/db/table-panel-showcase?orgId=1
I found it via this webpage: https://docs.huihoo.com/grafana/2.6/reference/table_panel/index.html
Having access to this demo would be very useful for documentation's sake.

**Comment by ivanahuckova** [comment]
Hello @JordanHilder9, Grafana 2.6 is very, very old. Since then, we have replaced table panel with new one. You can find demo here: https://play.grafana.org/d/OhR1ID6Mk/3-table?orgId=1
