### ISSUE TITLE
Plugins: Investigate using Federated Modules for loading plugins

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#39961]
Webpack 5 is now being used in Grafana and ships with the Federated Modules plugin which could be used as a way to load plugins instead of using SystemJS. The author of the Webpack plugin describes it like so:

> Module federation allows a JavaScript application to dynamically load code from another application — in the process, sharing dependencies, if an application consuming a federated module does not have a dependency needed by the federated code — Webpack will download the missing dependency from that federated build origin.

This would allow a plugin to declare what dependencies it requires rather than using externals and the Grafana application can use Webpack to expose what it wants for plugins, which will load the version Grafana ships with (if required) else it will load its own. This would remove the need for Systemjs in the long run and potentially reduce the friction of breaking changes.

- [x] Create a sample plugin that uses the federated modules Webpack plugin in its build scripts (There is a monoreop of plugins [here](https://github.com/jackw/grafana-federated-plugins))
- [x] Update Grafana Webpack config to use federated modules Webpack plugin ([Branch](https://github.com/grafana/grafana/compare/jackw/package-build-improvements...jackw/federated-module-plugins))
- [x] Introduce a flag in plugin.json that allows us to selectively use Webpack or SystemJS to load plugins in the FE ([Branch as above](https://github.com/grafana/grafana/compare/jackw/package-build-improvements...jackw/federated-module-plugins))
- [x] Introduce a loader in Grafana to dynamically load plugins via Webpack ([Branch as above](https://github.com/grafana/grafana/compare/jackw/package-build-improvements...jackw/federated-module-plugins))
- [x] Expose all dependencies listed in plugin_loader via federated modules Webpack plugin ([Branch as above](https://github.com/grafana/grafana/compare/jackw/package-build-improvements...jackw/federated-module-plugins))
- [x] Migrate some plugins to use federated modules Webpack plugin [Monorepo of plugins](https://github.com/jackw/grafana-federated-plugins)

Related to: #30026

**Comment by tolzhabayev** [comment]
I think the investigation part (this issue) can be moved into done

**Comment by jackw** [comment]
Agreed! Closing as investigation is complete.
