### ISSUE TITLE
Wrapped alert when sent to Microsoft Teams

### ISSUE THREAD

**Issue by vijay62723** [grafana/grafana#40000]
**Steps to reproduce**: I have created an alert to be sent to Microsoft Teams using a "Incoming Webhook Connector", its working as expected but its not showing the completed message. the message is getting wrapped like this

**Actual Result**: 
```
http endpoint is unavailable 
url : go...
```

**Expected Result**  :
```
http endpoint is unavailable 
url : google.com
error code : 502 
```

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**: Grafana sending alerts to Microsoft Teams
- Grafana version: Grafana 8.1
- Data source type & version: Prometheus (not sure about the exact version but I guess its the latest one)
- User OS & Browser: Windows 10 and Chrome
- Others:

**Comment by ying-jeanne** [comment]
hey @vijay62723 I am not sure I well understand the issue here, you would like to not format the message sent to teams?

**Comment by ying-jeanne** [comment]
@grafana/alerting-squad hey team, it appears for me the user don't want to format the message sent to teams, i am not sure whether the request seems reasonable for you guys. @vijay62723 could you provide us more context why this format message would be disturbing? what is your use case, to backup your request? 

Thanks,

**Comment by armandgrillet** [comment]
I'm surprised that we do not catch this issue in https://github.com/grafana/grafana/blob/9c0a2a19fd121fd322bcc0482edbd73bfec6e7b5/pkg/services/ngalert/notifier/channels/teams_test.go

**Comment by yuri-tceretian** [comment]
@vijay62723 we have improved that MS teams receiver since 9.3.1 (https://github.com/grafana/grafana/pull/53532 and follow ups) and migrated to adaptive cards. 

https://user-images.githubusercontent.com/8484471/183948000-5dd930e5-3e04-417b-b379-12b5c5fd7c6b.png

Can you confirm that this fixes your issue

**Comment by yuri-tceretian** [comment]
Closing this issue. Please reopen or create a new one if the problem persists
