### ISSUE TITLE
Stacked Tooltip Shows Cumulative Values

### ISSUE THREAD

**Issue by leesjensen** [grafana/grafana#4002]
The tooltip for a stacked chart shows the cumulative value instead of the individual value of the item. This is really confusing and not what you would expect. It would be much more helpful to be able to identify the individual items contribution to the stack rather than a position dependant value.

![image](https://cloud.githubusercontent.com/assets/10098820/12991479/b0657da6-d0cc-11e5-8f97-d47fa0439b41.png)

For example in the above image I want to see what the actual values of the items are, not what the cumulative value is as they get stacked. If the cumulative value is valuable to someone then it should at least show both the individual and cumulative values. Without this I am left doing the math in my head for each item.

**Comment by torkelo** [comment]
there is an option to switch between cumulative or individual values in the display style tab

**Comment by leesjensen** [comment]
Oh, how embarrassing! Thanks for taking the time to respond and for building such an awesome interface. I use it extensively everyday. But apparently not extensively enough to know about the cumulative option.
