### ISSUE TITLE
Elasticsearch date histogram stuck on @timestamp

### ISSUE THREAD

**Issue by claygorman** [grafana/grafana#4004]
Hello,

Using the latest graphana release to query elasticsearch and works great. Only issue is I cannot use any other date field other then ```@timestamp``` for the date histogram.

Can anyone else replicate this as well?

**Comment by torkelo** [comment]
it should work, you can specify any field name in the datasource edit options

**Comment by rtktgerhardt** [comment]
I'm also having this issue in 2.6.0. If I change the group by parameter, the JSON for the dashboard doesn't change. I tested this by changing other features like the alias and closing and opening the JSON panel; the alias was different but the field and timeField values were unchanged. Regardless of what I provide for the Date Histogram field, I get:

              "bucketAggs": [
                {
                  "type": "date_histogram",
                  "id": "2",
                  "settings": {
                    "interval": "auto",
                    "min_doc_count": 0
                  },
                  "field": "@timestamp"
                }
              ],
              "timeField": "@timestamp",

**Comment by torkelo** [comment]
the timestamp field is only controlled from the elasticsearch datasource options.

**Comment by rtktgerhardt** [comment]
Ah, that makes sense. I added a second elasticsearch source that used my other time field and that solved it. Thanks!

**Comment by Kotove** [comment]
> the JSON for the dashboard doesn't change. I tested this by changing other features like the alias and closing and opening the JSON panel; the alias was different but the field and timeField values were unchanged. Regardless of what I provide for the Date Histogram field, I get

reproduced on 4.2.0.
the value selected in the Date Histogram field doesn't appear in corresponding Target.
From my point of view - it is hardcoded here:
grafana/public/app/plugins/datasource/elasticsearch/query_builder.js:

**Comment by dxjsunday** [comment]
had this issue resoved in new version?
