### ISSUE TITLE
privacy breach (Google Tag Manager)

### ISSUE THREAD

**Issue by onlyjob** [grafana/grafana#4005]
[blob/master/public/views/index.html](../blob/master/public/views/index.html#L84) appears to have an issue with privacy:

`//www.googletagmanager.com/ns.html?id=gtm-k2mj65`

**Comment by onlyjob** [comment]
Also (at least) files

[public/emails/welcome_on_signup.html](../blob/master/public/emails/welcome_on_signup.html#L98) and [public/emails/reset_password.html](../blob/master/public/emails/reset_password.html#L98)

contain `<img src="http://docs.grafana.org/img/logo_transparent_200x75.png"`, perhaps better replaced with `<img src="/img/logo_transparent_200x75.png"`.

Please respect privacy. ;)

**Comment by torkelo** [comment]
thanks for informing me. Fixed the first one .

The image link in the emails need to be absolute.

**Comment by onlyjob** [comment]
Thank you.

> The image link in the emails need to be absolute. 

Unless image file is attached to email...
