### ISSUE TITLE
Plugins: add a way to watch changes for the backend plugin code and restart the Grafana server when the plugin code is updated

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#40051]
### The problem
While developing a backend plugin the Grafana server needed to be manually restarted every time the plugin code is updated.

**Comment by Tschuuuls** [comment]
> Example on how to do this in VSCode:
> 
> https://github.com/grafana/grafana-k6-app/blob/main/.vscode/launch.json
> 
> Under the hood this does something like:
> 
> ```shell
> mage build:backend
> mage reloadPlugin
> ```
> 
> Big thanks to @scottlepp for helping with this!

I'm trying to debug a datasource plugin in vs-code, but unfortunately your link is dead and older tutorials seem to be outdated.
Could you point me to a working launch.json?

Thanks!

**Comment by mckn** [comment]
@Tschuuuls I have moved it to a gist instead. Should be able to view it now.

**Comment by sympatheticmoose** [comment]
Closed in favour of new issue in plugin-tools
