### ISSUE TITLE
source-less pre-built files

### ISSUE THREAD

**Issue by onlyjob** [grafana/grafana#4006]
There are several files in Grafana source tree that have no source code:

 * [public/vendor/crypto.min.js](../blob/master/public/vendor/crypto.min.js)
 * [public/vendor/modernizr-2.6.1.js](../blob/master/public/vendor/modernizr-2.6.1.js)
 * [public/vendor/css/normalize.min.css](../blob/master/public/vendor/css/normalize.min.css)

Such minified files are the same as pre-compiled binaries -- un-readable, non-modifiable and non-distributable in [Debian](http://debian.org). Certainly is is a bad practice to commit pre-built binaries to source tree. Also [there are more concerns](https://wiki.debian.org/onlyjob/no-minification) including security ones not to mention that minification is completely unnecessary.

Please replace minified files with their original uncompressed sources.

**Comment by onlyjob** [comment]
Also [jquery.flot.js](../blob/master/public/vendor/flot/jquery.flot.js#L32) have portion of minified code which is weird considering that the file have local modifications...

**Comment by torkelo** [comment]
ok. thanks for informing us, will try to update them

**Comment by onlyjob** [comment]
Thanks but it would be great if you close this bug _after_ resolving the issue. Please reopen.
