### ISSUE TITLE
please update normalize.css

### ISSUE THREAD

**Issue by onlyjob** [grafana/grafana#4007]
[normalize.min.css](../blob/master/public/vendor/css/normalize.min.css) is old, as of August 2012. Please consider upgrading to newer [release](https://github.com/necolas/normalize.css/releases).

Also please remember to commit original uncompressed file, like [this one](https://github.com/necolas/normalize.css/blob/3.0.3/normalize.css) to avoid problems reported in #4006.

Thanks.

**Comment by onlyjob** [comment]
Seriously? Just close without resolution? Is it fixed or not?

**Comment by torkelo** [comment]
really sorry, missed commenting, it is resolved, 
https://github.com/grafana/grafana/blob/master/public/sass/base/_normalize.scss

**Comment by onlyjob** [comment]
No worries, thanks for letting me know and thanks for fixing. :)
