### ISSUE TITLE
Grafana does not rollback cleanly after turning off unified alerting feature flag

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#40080]
**What happened**:
A sequence of events:
- new db MySql 5.6, feature flag is off
- created some alert for a panel
- enabled the feature flag 
- played with new alerting 
- disabled the feature flag
- repeat 2 steps above several times
- stop Grafana. keep the flag disabled.
- restart MySql server
- enable feature flag
- start Grafana. 💥 

Grafana crashed with 
```
Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): failed to migrate alert 6: failed to get or create general folder under organisation 1: Error 1062: Duplicate entry '81-1' for key 'UQE_dashboard_version_dashboard_id_version'
migration failed (id = move dashboard alerts to unified alerting): failed to migrate alert 6: failed to get or create general folder under organisation 1: Error 1062: Duplicate entry '81-1' for key 'UQE_dashboard_version_dashboard_id_version'
```
After inspecting the database, I found that there was not any dashboard with such Id. Moreover, there were a few more records like the below

| id | dashboard\_id | parent\_version | restored\_from | version | created | created\_by | message | data |
| :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- | :--- |
| 98 | 81 | 0 | 0 | 1 | 2021-10-05 18:18:32 | -8 |  | {"title":"General Alerting","uid":"387XRcv7k","version":1} |

**What you expected to happen**:
Migration should work back and forth and when flag is disabled, the rollback should not leave any leftovers.

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2-main
- Data source type & version: MySql 5.6 (Docker image)
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, N\A
- Grafana plugins: N\A
- Others: N\A

**Comment by armandgrillet** [comment]
The fix would be to cleanup a few records in the table.

**Comment by grobinson-grafana** [comment]
Is this fixed or still an issue?

**Comment by grobinson-grafana** [comment]
Is this fixed or is it still an issue?

**Comment by yuri-tceretian** [comment]
Closing this issue as it is a very edge case.
