### ISSUE TITLE
SHA256 Sum mismatch for 7.5.11 (OSS) - Standalone Linux Binaries(64 Bit)

### ISSUE THREAD

**Issue by vipinvkmenon** [grafana/grafana#40116]
**What happened**:

From the grafana download page, when we download the grafana tar file and compare SHA 256 sum against the one on the site, they are different.

**What you expected to happen**:
SHA256 in the download page vs locally generated are the same.

**How to reproduce it (as minimally and precisely as possible)**:
- Download the tar file for 7.5.11
  `wget https://dl.grafana.com/oss/release/grafana-7.5.11.linux-amd64.tar.gz`
- check the sha256
   ```
   $ sha256sum grafana-7.5.11.linux-amd64.tar.gz 
   3244d0ced48d2de9726c9a3bd6d5f08c1b6a081d42665401e033fc4a31c57d5d  grafana-7.5.11.linux-amd64.tar.gz
   ```
 This value is different from the one on the site which is: `SHA256: e8a4d6307e9693e9077c310e76e2382811b524aeb7957379fcccc8c35ee234a3`

 Concern: Is the mismatch due to issues in the package itself?  

**Environment**:
- Grafana version: 7.5.11 (OSS)
- OS Grafana is installed on: Ubuntu 16.04.6 LTS
- User OS & Browser: Chrome, Ubuntu

**Comment by papagian** [comment]
fixed by grafana/support-escalations/issues/1068
