### ISSUE TITLE
Single stat displaying wrong value

### ISSUE THREAD

**Issue by hujosh** [grafana/grafana#4011]
A series is not receiving any data-points, as confirmed by the graph in the picture, but single stat displays 0.07. Why is single stat saying that the current value of series is 0.07 when it should be zero?

![grafan_issue](https://cloud.githubusercontent.com/assets/17036601/13012996/b555e5f4-d201-11e5-9bda-fe3cf5223ff8.png)

**Comment by torkelo** [comment]
because you have specified in the single stat options that the value to be displayed should be the average of all values for the time range, and there are some values that are > 0 in the beginning of the time range
