### ISSUE TITLE
CloudWatch metric alias dimension interpolation broken for custom expressions

### ISSUE THREAD

**Issue by shousper** [grafana/grafana#40114]
Setting an "Alias" with dimension variables when using a custom expression based query does not interpolate the dimension values, but using a non-expression based query does.

**What happened**:
You can see below, the 2 query expressions are ultimately identical, but the labels in the chart aren't working for 1 of them:
![image](https://user-images.githubusercontent.com/1144345/136309876-26804cc9-7d19-4061-a09d-c77ec0af431c.png)

From the query inspector they also look identical:
![image](https://user-images.githubusercontent.com/1144345/136310127-f00a330a-4bd4-45be-b007-e70905e35a52.png)

And just for clarity I've made the alias different so the outcome is clear:
![image](https://user-images.githubusercontent.com/1144345/136310230-87cfe131-1ed5-44cb-823d-8536dcdb9345.png)

**What you expected to happen**:
Interpolation should work in both cases.

**How to reproduce it (as minimally and precisely as possible)**:
I think the screenshots above should suffice? Let me know if not.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: AWS CloudWatch
- OS Grafana is installed on: Container on AL2.
- User OS & Browser: macOS/Firefox
- Grafana plugins: No custom plugins, just OOTB.
- Others:

**Comment by sunker** [comment]
Should be fixed in https://github.com/grafana/grafana/issues/43905

**Comment by yaelleC** [comment]
I am closing this issue as it was resolved by Dynamic label work.

I can confirm that it works in prod (with new way of labelling) for both `Code` and `Builder`



![Image](https://user-images.githubusercontent.com/42030685/175285805-420e892e-aa0b-4a95-aa95-059361fc5918.png)

**Comment by shousper** [comment]
Thanks team 🙏🏻
