### ISSUE TITLE
Trouble pulling string / text data

### ISSUE THREAD

**Issue by screentan** [grafana/grafana#4012]
We are using PCP with pmwebd feeding Grafana via the (old?) Graphite API which only passes numerical data.  There is text data data (like OS type, kernel version, etc) that we would like to include in dashboards.  I'm discussing the best way to do this with the pmwebd developers but need to better understand Grafana's capabilities.  Is there a supported approach with Grafana and the Graphite API to display the string / text data?

**Comment by torkelo** [comment]
Graphite does not support string data, Grafana can display string data if it stored in Elasticsearch or InfluxDB
