### ISSUE TITLE
Systemd: Upgrading from 8.0.6 to 8.2.0 broke grafana

### ISSUE THREAD

**Issue by vsenapathy** [grafana/grafana#40162]
> **Note from Grafana team:** We're on this and will release a patch release that addresses this. In the meantime, you can [add an override to remove the syscall filter from the grafana-server service](https://github.com/grafana/grafana/issues/40162#issuecomment-938060240).

---

**What happened**:
Upgraded my dev Grafana from 8.0.6 to 8.2.0 by running the following commands
1. Took a backup of the DB
2. sudo apt-get update
3. sudo apt-get upgrade
4. grafana-cli plugins update-all
5. sudo service grafana-server restart
6. systemctl status grafana-server.service
● grafana-server.service - Grafana instance
   Loaded: loaded (/usr/lib/systemd/system/grafana-server.service; enabled; vendor preset: enabled)
   Active: failed (Result: signal) since Thu 2021-10-07 16:51:50 UTC; 7s ago
     Docs: http://docs.grafana.org
  Process: 25507 ExecStart=/usr/sbin/grafana-server --config=${CONF_FILE} --pidfile=${PID_FILE_DIR}/grafana-server.pid --packaging=deb cfg:default.paths.logs=${LOG_DIR} c
 Main PID: 25507 (code=killed, signal=SYS)

Oct 07 16:51:50 ip-10-216-5-98 systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Oct 07 16:51:50 ip-10-216-5-98 systemd[1]: grafana-server.service: Scheduled restart job, restart counter is at 5.
Oct 07 16:51:50 ip-10-216-5-98 systemd[1]: Stopped Grafana instance.
Oct 07 16:51:50 ip-10-216-5-98 systemd[1]: grafana-server.service: Start request repeated too quickly.
Oct 07 16:51:50 ip-10-216-5-98 systemd[1]: grafana-server.service: Failed with result 'signal'.
Oct 07 16:51:50 ip-10-216-5-98 systemd[1]: Failed to start Grafana instance.

**What you expected to happen**:
On reboot, expected grafana to come up properly without issues
**How to reproduce it (as minimally and precisely as possible)**:
Upgrade from 8.0.6 to 8.2.0
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.0
- Data source type & version: Influx
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Mac and Google chrome
- Grafana plugins:
- Others:

**Comment by vsenapathy** [comment]
Ya for the time being I reverted back to 8.0.6 this blocks me from upgrading

**Comment by flyersa** [comment]
Same here.

**Comment by kminehart** [comment]
@hibo98 your error looks slightly different but should still be resolved by #40176.

Sorry for the inconvenience all. Let me know if anyone runs into any issues after adding the workaround above.

**Comment by ssmoss** [comment]
@roman-rs Oh man that totally sucks :-( Guessing no backups?

**Comment by geosphere** [comment]
@ssmoss I did the same, and it solved the problem. Thanks. A little weird what needs to be edited `/lib/systemd/system/grafana-server.service`. Resetting these options in the `/etc/systemd/system/grafana-server.service.d/override.conf` has no effect.

**Comment by ssmoss** [comment]
@geosphere I think that is because the override suggestion just cleared one of the options. It is possible that more than one needs to be cleared to fix the issue. My approach was super heavy handed. I also didn't want to upgrade and forget about the override which is why I opted to change the service. I figured it will be bulldozed when they fix it in the next version.

**Comment by geosphere** [comment]
@ssmoss No, I tried clearing all new options. 
```conf
[Service]
LockPersonality=
MemoryDenyWriteExecute=
NoNewPrivileges=
PrivateDevices=
PrivateTmp=
PrivateUsers=
ProcSubset=
ProtectClock=
ProtectControlGroups=
ProtectHome=
ProtectHostname=
ProtectKernelLogs=
ProtectKernelModules=
ProtectKernelTunables=
ProtectProc=
ProtectSystem=
RemoveIPC=
RestrictAddressFamilies=
RestrictNamespaces=
RestrictRealtime=
RestrictSUIDSGID=
SystemCallArchitectures=
SystemCallFilter=
```
I have not touched `CapabilityBoundingSet` and `DeviceAllow`. But they are not defined in the original file either.

**Comment by LiMuBei** [comment]
Also ran into this issue on a Debian 9 system. A simple downgrade to 8.1.7 helped, but it seems something is wrong with the service definition in 8.2.0.

**Comment by f45tb00t** [comment]
Hi,

I can also confirm the issue. 

OS: Debain 9 (Stretch)

But you can easily do a rollback on the old version. In my case it was v8.1.5
apt-get install grafana=8.1.5

cheers

fb

**Comment by Vimao** [comment]
New options basically break compatibility with anything not running systemd >=240, for example ubuntu 18.04. 

This is a change that should really be documented in release notes

**Comment by kminehart** [comment]
@roman-rs There's a separate issue related to the image renderer plugin that includes a similar workaround: https://github.com/grafana/grafana/issues/40187#issuecomment-938629123

@bherrsk Your issue does seem to be different than these. Were you able to resolve it?

**Comment by willowpet** [comment]
Which logs ? I have nothing more
yes grafana is running on https port (with setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server)

**Comment by matzl** [comment]
This is still an issue in Version 8.2.3 (commit: fb85ed6912, branch: HEAD).
Just had to update because I ran into another bug, but this time I was smart enough to make a backup of the
/usr/lib/systemd/system/grafana-server.service

So this one was installed by grafana when running

```
sudo apt-get update
sudo apt-get install grafana
```

The installer asked:

> Configuration file '/usr/lib/systemd/system/grafana-server.service'
>  ==> Modified (by you or by a script) since installation.
>  ==> Package distributor has shipped an updated version.
>    What would you like to do about it ?  Your options are:
>     Y or I  : install the package maintainer's version
>     N or O  : keep your currently-installed version
>       D     : show the differences between the versions
>       Z     : start a shell to examine the situation
>  The default action is to keep your current version.
> *** grafana-server.service (Y/I/N/O/D/Z) [default=N] ? 

and I used D to backup my working service file:

```
cd /usr/lib/systemd/system/
cp grafana-server.service grafana-server.service.bck_working
```

Then `exit` and continued the installer with 'Y'. Seeing that this didn't work, I replaced the service file with my working one again:

```
cd /usr/lib/systemd/system/
cp grafana-server.service grafana-server.service.bck_8-2-3_default
cp grafana-server.service.bck_working grafana-server.service
```


Then stop grafana server, reload deamon, restart again, check status, voilà - working!

```
sudo systemctl stop grafana-server
sudo systemctl daemon-reload
sudo systemctl start grafana-server
sudo systemctl status grafana-server
```

(should show "active (running)" in green and website should be up again.

Content of the 8.2.3 file (not working):

```
[Unit]
Description=Grafana instance
Documentation=http://docs.grafana.org
Wants=network-online.target
After=network-online.target
After=postgresql.service mariadb.service mysql.service

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/sbin/grafana-server                                                  \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}


LimitNOFILE=10000
TimeoutStopSec=20
CapabilityBoundingSet=
DeviceAllow=
LockPersonality=true
MemoryDenyWriteExecute=false
NoNewPrivileges=true
PrivateDevices=true
PrivateTmp=true
PrivateUsers=true
ProtectClock=true
ProtectControlGroups=true
ProtectHome=true
ProtectHostname=true
ProtectKernelLogs=true
ProtectKernelModules=true
ProtectKernelTunables=true
ProtectProc=invisible
ProtectSystem=full
RemoveIPC=true
RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
RestrictNamespaces=true
RestrictRealtime=true
RestrictSUIDSGID=true
SystemCallArchitectures=native
UMask=0027

[Install]
WantedBy=multi-user.target

```


Content of my working file:
```
[Unit]
Description=Grafana instance
Documentation=http://docs.grafana.org
Wants=network-online.target
After=network-online.target
After=postgresql.service mariadb.service mysql.service

[Service]
EnvironmentFile=/etc/default/grafana-server
User=grafana
Group=grafana
Type=simple
Restart=on-failure
WorkingDirectory=/usr/share/grafana
RuntimeDirectory=grafana
RuntimeDirectoryMode=0750
ExecStart=/usr/sbin/grafana-server                                                  \
                            --config=${CONF_FILE}                                   \
                            --pidfile=${PID_FILE_DIR}/grafana-server.pid            \
                            --packaging=deb                                         \
                            cfg:default.paths.logs=${LOG_DIR}                       \
                            cfg:default.paths.data=${DATA_DIR}                      \
                            cfg:default.paths.plugins=${PLUGINS_DIR}                \
                            cfg:default.paths.provisioning=${PROVISIONING_CFG_DIR}


LimitNOFILE=10000
TimeoutStopSec=20					  
UMask=0027

[Install]
WantedBy=multi-user.target

```

**Comment by kminehart** [comment]
@matzl I want to help you but going to have to be more detailed.

While I am glad using the old unit file got your grafana service started, we did change it for a reason, and you should be aware than any changes you make could be overwritten in future updates.

The current unit file works for default installs as far as I'm aware. I would encourage you find what option specifically out of the 10 or so that were removed is causing your issue.

Some likely culprits are:

* Your grafana config is trying to use files in your /home directory, which is intentionally protected with the ProtectHome option.
* your grafana instance is attempting to start on a port less than 1024. This is not a recommended practice and requires a certain capability to be enabled: https://grafana.com/docs/grafana/latest/installation/debian/#start-the-server-with-systemd

If you provide the complete error log, including lines detailing the program exiting, then that would help as well.

**Comment by couchand** [comment]
I'd like to add some additional detail that was not at all clear to me from @kminehart's comment.

***The steps needed for starting grafana on a low port have changed***.

If you were previously adding the capability with:

```
sudo setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server
```

That invocation is no longer sufficient.  Per the [linked docs](https://grafana.com/docs/grafana/latest/installation/debian/#2-start-the-server), you must now instead update the service definition to include:

```
[Service]
# Give the CAP_NET_BIND_SERVICE capability
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE

# A private user cannot have process capabilities on the host's user
# namespace and thus CAP_NET_BIND_SERVICE has no effect.
PrivateUsers=false
```

---

As an aside, it is a bit surprising to me that there would be breaking changes requiring operator intervention without an accompanying section on the [upgrade page](https://grafana.com/docs/grafana/latest/installation/upgrading/).

**Comment by matzl** [comment]
@kminehart Ok, so since I needed to update to a newer version anyway because of [this security breach for versions <=8.3.1](https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/), I tried to find out which line causes issues in a process of elimination. Turns out Grafana works on my server with the 8.3.2 version service file if I only comment out those two lines:
```
# RestrictAddressFamilies=AF_INET AF_INET6 AF_UNIX
# SystemCallArchitectures=native
```
Whenever I uncomment one or both of them again, Grafana fails starting.

When I uncomment "RestrictAddressFamilies", i.e. I only comment out/disable "SystemCallArchitectures", I receive this error message in /var/log/syslog after starting grafana with "sudo systemctl start grafana-server":

```
Dec 13 03:56:35 myserver systemd[1]: Stopped Grafana instance.
Dec 13 03:56:44 myserver systemd[1]: Started Grafana instance.
Dec 13 03:56:44 myserver systemd[21212]: grafana-server.service: Failed at step ADDRESS_FAMILIES spawning /usr/sbin/grafana-server: Operation canceled
Dec 13 03:56:44 myserver systemd[1]: grafana-server.service: Main process exited, code=exited, status=232/ADDRESS_FAMILIES
Dec 13 03:56:44 myserver systemd[1]: grafana-server.service: Unit entered failed state.
Dec 13 03:56:44 myserver systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Dec 13 03:56:44 myserver systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Dec 13 03:56:44 myserver systemd[1]: Stopped Grafana instance.
... (4x more the same messages from "Started Grafana instance." to "Stopped Grafana instance.")
Dec 13 03:56:45 myserver systemd[1]: grafana-server.service: Start request repeated too quickly.
Dec 13 03:56:45 myserver systemd[1]: Failed to start Grafana instance.
Dec 13 03:56:45 myserver systemd[1]: grafana-server.service: Unit entered failed state.
Dec 13 03:56:45 myserver systemd[1]: grafana-server.service: Failed with result 'start-limit-hit'.
```


When I uncomment "SystemCallArchitectures", i.e. I only comment out/disable "RestrictAddressFamilies", I receive this error message in /var/log/syslog after starting grafana with "sudo systemctl start grafana-server":
```
Dec 13 03:59:47 myserver systemd[1]: Stopped Grafana instance.
Dec 13 03:59:50 myserver systemd[1]: Reloading.
Dec 13 03:59:51 myserver systemd[1]: Failed to get udev device from devnum 0:87: No such device
Dec 13 03:59:51 myserver systemd[1]: message repeated 2 times: [ Failed to get udev device from devnum 0:87: No such device]
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:24] Unknown lvalue 'LockPersonality' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:25] Unknown lvalue 'MemoryDenyWriteExecute' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:29] Unknown lvalue 'ProtectClock' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:30] Unknown lvalue 'ProtectControlGroups' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:32] Unknown lvalue 'ProtectHostname' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:33] Unknown lvalue 'ProtectKernelLogs' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:34] Unknown lvalue 'ProtectKernelModules' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:35] Unknown lvalue 'ProtectKernelTunables' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:36] Unknown lvalue 'ProtectProc' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:38] Unknown lvalue 'RemoveIPC' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:40] Unknown lvalue 'RestrictNamespaces' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:41] Unknown lvalue 'RestrictRealtime' in section 'Service'
Dec 13 03:59:51 myserver systemd[1]: [/usr/lib/systemd/system/grafana-server.service:42] Unknown lvalue 'RestrictSUIDSGID' in section 'Service'
Dec 13 03:59:55 myserver systemd[1]: Started Grafana instance.
Dec 13 03:59:55 myserver systemd[21451]: grafana-server.service: Failed at step SECCOMP spawning /usr/sbin/grafana-server: Operation canceled
Dec 13 03:59:55 myserver systemd[1]: grafana-server.service: Main process exited, code=exited, status=228/SECCOMP
Dec 13 03:59:55 myserver systemd[1]: grafana-server.service: Unit entered failed state.
Dec 13 03:59:55 myserver systemd[1]: grafana-server.service: Failed with result 'exit-code'.
Dec 13 03:59:55 myserver systemd[1]: grafana-server.service: Service hold-off time over, scheduling restart.
Dec 13 03:59:55 myserver systemd[1]: Stopped Grafana instance.
... (4x more the same messages from "Started Grafana instance." to "Stopped Grafana instance.") ...
Dec 13 03:59:56 myserver systemd[1]: grafana-server.service: Start request repeated too quickly.
Dec 13 03:59:56 myserver systemd[1]: Failed to start Grafana instance.
Dec 13 03:59:56 myserver systemd[1]: grafana-server.service: Unit entered failed state.
Dec 13 03:59:56 myserver systemd[1]: grafana-server.service: Failed with result 'start-limit-hit'.
```

Hope this helps!
Ah and I run " Ubuntu 16.04.7 LTS" on a VPS.

Best regards,
Matthias

**Comment by desrod** [comment]
I wanted to jump in here to mention that with 8.3.3, _**none**_ of the above suggestions work. Using `setcap`, updating the service unit file, removing or adding `SystemCallArchitectures` or `PrivateUsers=false`, _**will fail**_ when upgrading to 8.3.3. Even attempting to run the service as 'root', or changing the permissions to setuid root on the binary, will fail. 

It appears that we can no longer run Grafana on a public SSL port, and are required to stick this behind a load-balancer or SSL termination proxy in front of Grafana, drastically complicating a deployment. 

I'm off to find other replacements for Grafana, it seems they've started to swerve left and may no longer be the right solution for us.

**Comment by Christoph-W** [comment]
@desrod
I stumbled upon the same problem with Grafana 8.3.3 not starting on SSL port 443. The following solution helped on CentOS 7:
`setcap 'cap_net_bind_service=+eip' /usr/sbin/grafana-server`
`systemctl edit grafana-server`
... with this file content:
```
[Service]
CapabilityBoundingSet=CAP_NET_BIND_SERVICE
AmbientCapabilities=CAP_NET_BIND_SERVICE
```
Then save, exit and restart service.

**Comment by Chris-Tophski** [comment]
I also had to revert back to 8.1.7, because none of the above mentioned measurements worked for any version after this one up to 8.3.3.

**Comment by f45tb00t** [comment]
Hello,

I've waited for some versions. For me at least now it seems to be fixed.

sudo dpkg -l grafana
ii  grafana                   8.3.3             amd64             Grafana
cat /etc/debian_version 
9.13

**Comment by KushRohra** [comment]
@Christoph-W 
My vm where grfana is deployed dows not support systemctl command, any other way to change the file mentioned

**Comment by Chris-Tophski** [comment]
@KushRohra 
Please google how to manage services/daemons on your specific operating system.

**Comment by Chris-Tophski** [comment]
@f45tb00t 
It works for me on a RaspberryPi 4, but not on a VM with Ubuntu 18.04.

**Comment by TryTryAgain** [comment]
This is happening to me going from a recent 8.4.x to the latest 8.4.5 on a CentOS box. Hmmm, trying to find a solution, none of these are working :(
