### ISSUE TITLE
Hide in Area Viz Hiding Not Working in 8.1.x and 8.2.0

### ISSUE THREAD

**Issue by dragonknight9111** [grafana/grafana#40171]
**What happened**: Viz - Hide in Area also hides Tooltip

**What you expected to happen**: only hide Viz, but not Tooltip

**How to reproduce it (as minimally and precisely as possible)**:
Grab 2 variables in a graph (Host-1 and Host-2) for example for CPU and say "add field from calculation" and hit total. 
after go to Overrides -> Fields with Name -> Total -> Series -> Hide IN Area and hide Viz. 

**Anything else we need to know?**:
Issue happens in grafana 8.1.x and 8.2.0, last confirmed working as expected in 8.0.6

**Environment**:
- Grafana version: 8.2.0 
- Data source type & version: InfluxDb and Amazon Timestream
- OS Grafana is installed on: Ubuntu 20.0.4
- User OS & Browser: Firefox/Chrome/Edge
- Grafana plugins: Time Series
- Others: see attached screenshot for the issue
![Hiding_Viz_not_Working](https://user-images.githubusercontent.com/83013789/136445497-d1abf54f-9e56-48ef-847d-c0b6fae63f2d.jpg)

**Comment by dprokop** [comment]
This is an intended behavior introduced in 8.0.5 (https://github.com/grafana/grafana/blob/main/CHANGELOG.md#805-2021-07-08).

If you want to keep the series in the tooltip yet hide it from the viz, please use Fill opacity & Line width options overrides.

**Comment by jdiogo-correia** [comment]
Using Fill opacity and Line width overrides to hide the series works. But the auto scaling of the y axis will keep considering the series for the scale. Any way to get around this?

**Comment by MKrabs** [comment]
> This is an intended behavior introduced in 8.0.5 (https://github.com/grafana/grafana/blob/main/CHANGELOG.md#805-2021-07-08).
> 
> If you want to keep the series in the tooltip yet hide it from the viz, please use Fill opacity & Line width options overrides.

May I ask why?  
[I know why obviously](https://github.com/grafana/grafana/pull/36353#issue-934844582), but it doesn't make sense to remove a working feature for the sake of it.  
We have the technology, let us please use it.  
In case someone wanted to hide **both** Viz and the Tooltip, they could toggle both and have the result they're looking for.

What you suggested is not a good option though:
![chartsGrafana_8_1_why](https://user-images.githubusercontent.com/71791731/179219671-2d88b941-197b-4626-8c32-90f2d7f8c47e.png)
 
Could you please discuss about reverting the change?
