### ISSUE TITLE
Changing panel span from editor shrinking option panel also

### ISSUE THREAD

**Issue by ashimloves** [grafana/grafana#4018]
Changing panel span from editor shrinking option panel also, but it should only shrink the panel preview only.
![resize_panel](https://cloud.githubusercontent.com/assets/3369047/13027726/5c422c0a-d280-11e5-97c3-548a00b4fad3.PNG)

**Comment by kylebrandt** [comment]
This is true of all panel types from what I can see - Graph, Singlestat, and Table verified.

**Comment by torkelo** [comment]
seems fixed in master
