### ISSUE TITLE
Setting GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT is not setting the corresponding setting.

### ISSUE THREAD

**Issue by kyschouv** [grafana/grafana#40186]
**What happened**:
I set the environment variable `GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT` to `true`, but the corresponding setting is appearing as unset in the admin UI (and is supposedly not applying, as I can log in with AzureAD with an account that has no role and get auto-assigned the Viewer role). This should work in 8.x according to https://github.com/grafana/grafana/issues/22741, which was consolidated into https://github.com/grafana/grafana/issues/23218 and resolved by https://github.com/grafana/grafana/pull/28021.

![image](https://user-images.githubusercontent.com/11529726/136486406-cb5fd125-d4ca-470c-8537-ccb25c68aad8.png)

**What you expected to happen**:
Login with an account that has no Grafana role in the AAD application is blocked if the environment variable `GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT` is set to `true`.

**How to reproduce it (as minimally and precisely as possible)**:
1. Follow the documentation to set up AzureAD authentication (ensuring that no users are assigned Grafana roles).
2. Set the environment variable `GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT` to `true` for Grafana.
3. Log in to Grafana with a user.
4. Note that the user is auto-assigned Viewer instead of being denied access.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.5
- OS Grafana is installed on: grafana docker image.
- User OS & Browser: Windows 10, Chrome

**Comment by kyschouv** [comment]
Could you please read the issues I linked? I know it was only implemented for those two in the referenced pull request, but it was promised for AzureAD as well in https://github.com/grafana/grafana/issues/22741, which was closed by @marefr to consolidate with https://github.com/grafana/grafana/issues/23218 so keep the conversation in one place:

> I know this issue was opened before #23218, but that issue has more activity and comments and we would like to group everything related to this there.

Without rehashing all of the conversation in that issue, this functionality is definitely needed in AzureAD as well, as its lack leaves either a security hole (allowing others in a large tenant to access a Grafana instance where group-based restrictions aren't appropriate) or a usability problem (have to grant users roles in the AAD application as well as manually add them to Grafana). Please either re-open this issue, or re-open https://github.com/grafana/grafana/issues/22741.

**Comment by papagian** [comment]
@kyschouv Have you tried configuring [allowed groups](https://grafana.com/docs/grafana/v7.1/auth/azuread/#configure-allowed-groups-and-domains) for restricting access only to specific groups and domains?

**Comment by kyschouv** [comment]
@sdboyer I realize that was a bunch of numbers linked in a bunch of text, but hopefully that clarifies the expectation? I'd be happy to contribute here, but can't get the repo building following the instructions, and imagine it'd take me significantly longer to implement due to the set-up than someone who's already familiar with the code.

**Comment by sivamu** [comment]
I made a PR to address this issue @kyschouv, hoping for a positive outcome there.

**Comment by kyschouv** [comment]
Thanks @sivamu. Looks like the build is failing on the PR though, anything I can help with?

**Comment by sivamu** [comment]
Of course, glad to pitch in. The build's failing on tests unrelated to the code changes I made, but I can try rebasing with main and seeing if that resolves the issue.

**Comment by kyschouv** [comment]
Did this make it into 8.4.5? Or if not, do we know when it'll make it into a release? It's still not working with 8.4.5 today (setting `GF_AUTH_AZUREAD_ROLE_ATTRIBUTE_STRICT` to `true` is still allowing other tenant users in as Viewers).

**Comment by marefr** [comment]
@kyschouv it will be included in v8.5.0 - you can tell via the milestone set on the pull request.

**Comment by kyschouv** [comment]
@marefr I've tried to use this in v8.5.0 today, and it doesn't appear to be working. I've removed everyone from the enterprise AAD application and removed all users from Grafana (using an admin account). `GF_AUTH_ROLE_ATTRIBUTE_STRICT` is set to `true`, but it still lets anyone in the tenant log in and assigns them the Viewer role.

![image](https://user-images.githubusercontent.com/11529726/164519551-1715f00b-7612-40f9-893b-917bb5d11a39.png)

Did this change not make it in? I didn't notice it in the release notes. Am I just using it wrong? If it's not in, is there a reason? We've been eagerly awaiting this change for a long time now.

**Comment by sivamu** [comment]
I see the change in the latest release's source code. It would be useful to log the roles that your token is returning, in this [function](https://github.com/grafana/grafana/blob/main/pkg/login/social/azuread_oauth.go#L135), and see if the "Viewer" is actually present in the claim right out of AAD or whether Grafana is adding it. This might involve tweaking the grafana code and building a localized grafana image, and perhaps deploying it to where you're using it.

**Comment by kyschouv** [comment]
> I see the change in the latest release's source code. It would be useful to log the roles that your token is returning, in this [function](https://github.com/grafana/grafana/blob/main/pkg/login/social/azuread_oauth.go#L135), and see if the "Viewer" is actually present in the claim right out of AAD or whether Grafana is adding it. This might involve tweaking the grafana code and building a localized grafana image, and perhaps deploying it to where you're using it.

There are no `roles` in the `id_token` from AAD. If I grant myself the Grafana Editor role in AAD, then my `id_token` has `"roles": ["Editor"]`.

**Comment by marefr** [comment]
@kyschouv if there are no roles in id token the auto assign role setting will be used as the role, https://github.com/grafana/grafana/blob/9f0b6a57547988ee8665785e3b3f0381534db2a4/pkg/login/social/azuread_oauth.go#L126

Guess the idea being if there are no admin, editor or viewer role but there are some other role in the token an error will he returned and not allow user to login. Not sure how @sivamu reasoned in this regard while implementing the fix?

**Comment by sivamu** [comment]
I didn't account for that 😞 . Though I can see a workaround; by assigning a dummy role to all the users so that it will fail the check == admin, editor or viewer.

**Comment by kyschouv** [comment]
If I set the auto assign role to '', it still lets people in. If I set it to `none` or `norole` or some other dummy string, it grants people Editor for some reason.

**Comment by sivamu** [comment]
Grants editor in AAD or in grafana? I'm assuming in AAD.

**Comment by kyschouv** [comment]
No in Grafana. I checked AAD and I'm not getting any roles back, but even a brand new AAD user (that's never logged into my Grafana) is getting assigned Editor.

**Comment by sivamu** [comment]
I'll do some more testing when I have some time and update here. There's probably a bug in the code change I made.

**Comment by kyschouv** [comment]
I think I found the reason for `Editor`:

https://github.com/grafana/grafana/blob/3e7db088acd1da32ea489b0756cdf4e15ec2da69/pkg/setting/setting.go#L1355

If the `auto_assign_org_role` setting is set to anything other than a valid role name, it'll default to `Editor`. So it looks like there's no workaround. I imagine an additional `strictMode` check is needed inside the initial `if len(claims.Roles) == 0` block. Either that, or just remove that early out block entirely and let the code run (it should fail to find any valid roles, then hit the `strictMode` test and return an empty role).

**Comment by marefr** [comment]
I think I'm still pretty sure the problem is here https://github.com/grafana/grafana/issues/40186#issuecomment-1105729476 and the fix is to return an error is strict enabled and no roles returned from AAD. I'll reopen this one.

**Comment by kyschouv** [comment]
> I think I'm still pretty sure the problem is here [#40186 (comment)](https://github.com/grafana/grafana/issues/40186#issuecomment-1105729476) and the fix is to return an error is strict enabled and no roles returned from AAD. I'll reopen this one.

Yah it uses the auto assign role if none are in the token, but auto assign role has to be `Viewer`, `Editor`, or `Admin`, or the settings code will force it to `Editor`:

https://github.com/grafana/grafana/blob/3e7db088acd1da32ea489b0756cdf4e15ec2da69/pkg/setting/setting.go#L1355

**Comment by marefr** [comment]
I don't think the code touching `cfg.AutoAssignOrgRole` will be executed.

Current implementation:
https://github.com/grafana/grafana/blob/9f0b6a57547988ee8665785e3b3f0381534db2a4/pkg/login/social/azuread_oauth.go#L126-L128

My suggestion is to change above code to:
```go
if len(claims.Roles) == 0 { 
	if strictMode {
		return models.RoleType("")
	}

	return models.RoleType(autoAssignRole) 
} 
```

This code will return an error if the `role` is empty:
https://github.com/grafana/grafana/blob/9f0b6a57547988ee8665785e3b3f0381534db2a4/pkg/login/social/azuread_oauth.go#L73-L76

Which in turn is called from here and writes the HTTP response error in case of an error returned and by that restrict the user from logging in to Grafana:
https://github.com/grafana/grafana/blob/9f0b6a57547988ee8665785e3b3f0381534db2a4/pkg/api/login_oauth.go#L208-L221

WDYT?

**Comment by kyschouv** [comment]
> My suggestion is to change above code to:
> 
> ```go
> if len(claims.Roles) == 0 { 
> 	if strictMode {
> 		return models.RoleType("")
> 	}
> 
> 	return models.RoleType(autoAssignRole) 
> } 
> ```

This will work (I just tested it locally on top of `v8.5.1`). I also tested moving the current block (`if len(claims.Roles) == 0`) below the current `if strictMode` block, and that also works. I don't know that a server error for an unauthorized user is the behavior I'd expect (I think I'd expect a 403), but it's consistent with all of the other social providers as far as I can tell. I tried out various scenarios (adding and removing my role in AAD, changing my role in AAD, adding a group with a role to AAD) and they all appear to work correctly!

I'd submit a PR, but I'm going to be unavailable after tomorrow for a few weeks. Do you think you'd be able to make the change? Or if I submit a PR and there are necessary changes/additions, would you or someone else be able to manage those while I'm OOF?

**Comment by kyschouv** [comment]
I made the changes and added a test in the above PR. Let me know if it needs any changes. I've tested it and it works, at least on top of `v8.5.1`.
