### ISSUE TITLE
InfluxDB: "WHERE value = number" coerces number to string

### ISSUE THREAD

**Issue by sbraz** [grafana/grafana#40181]
**What happened**:
I used the query editor to set `WHERE value = 0`. The resulting InfluxDB query contains `WHERE "value" = '0'`

**What you expected to happen**:
The InfluxDB query should be `WHERE "value" = 0`.

**How to reproduce it (as minimally and precisely as possible)**:
Create an InfluxDB query in the query editor with either `==` or `!=` and an integer value.

**Anything else we need to know?**:
This is very similar to https://github.com/grafana/grafana/issues/4163 which had to do with `>` and `<` operators.

**Environment**:
- Grafana version: 8.1.6
- Data source type & version: InfluxDB 1.8.3
- OS Grafana is installed on: Gentoo
- User OS & Browser: Arch Linux & Firefox
- Grafana plugins: N/A
- Others:

**Comment by ivanahuckova** [comment]
This https://github.com/grafana/grafana/issues/4163 was closed but it seems that the issue still persists.

**Comment by groot-bastiaan** [comment]
We are suffering from the same issue, having to revert back to the text editor is really a major pain (especially if you have to redo this after every query change)

Would it not make sense to make a flag/option in the datasource configurtion that sets a certain column to a fixed data data type? so you can force it one one time to be a certain type? That would be a minumal change for a major improvement.

Offcourse auto detect would be nicer, but the current situation is really unworkable

**Comment by gtk-grafana** [comment]
I can verify that this is working for me now in 9.2.
If you create a query with the builder that contains a numeric tag value:
<img width="231" alt="image" src="https://user-images.githubusercontent.com/109082771/192870282-77e1cab0-2f23-4557-945f-02a38ddb05f6.png">
We will always quote that value in the raw query, so when it is converted into a raw query, it's properly quoted:
e.g. `SELECT mean("value") FROM "measurement" WHERE ("host" = '0')`
