### ISSUE TITLE
Question - DB Portability

### ISSUE THREAD

**Issue by Rucknar** [grafana/grafana#4019]
Hello,

I'm looking at a use-case with grafana and prometheus where they auto-configure to their surrounding environment when deployed. I've got it all working but i've found that Grafana looks like is caching some of values for things like template results. 

For instance, if i load up the grafana dashboard (using a backup of the DB) on a new instance, i can still see templates populated with old values. I have to deselect the old values and give it a minute or so to work.

Any easy way to achieve what i'm looking for?

**Comment by torkelo** [comment]
When you define the template variables there is a checkbox "Refresh on Load" which will update template variables on dashboard load.

**Comment by Rucknar** [comment]
Thanks for the heads up, works a treat!
