### ISSUE TITLE
Grafana 8.2.0 can't resolve Elasticsearch fields from $labels when used in templating

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#40193]
**What happened**: Grafana cannot substitue Elasticsearch fields from $labels variable when used in NGAlert templating

**What you expected to happen**: After an Elasticsearch query with group by terms, Grafana generates labels based on the terms you grouped by. I wanted to access these labels to prepare a more cohesive message sent with an alert

**How to reproduce it (as minimally and precisely as possible)**: Create an Elasticsearch query alert with a group by terms options, and then try to use anything from $labels variable in the details or custom labels section. 

**Anything else we need to know?**: Error logs below:

`{
  "err": "error executing template <REDACTED: template: __alert_<REDACTED>:1:86: executing \"__alert_<REDACTED>\" at \u003c$labels.log.MessageTemplate.keyword\u003e: map has no entry for key \"log\"",
  "logger": "ngalert",
  "lvl": "eror",
  "msg": "error in expanding template",
  "name": "MessageTemplate",
  "t": "2021-10-08T07:43:20.365017858Z",
  "value": "{{ $labels.log.MessageTemplate.keyword }}"
}
`

**Environment**:
- Grafana version: 8.2.0
- Data source type & version: Elasticsearch 7.0+
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Edge
- Grafana plugins: None other than default
- Others: This does seem related to https://github.com/grafana/grafana/pull/38629

**Comment by Vimao** [comment]
Yeah, but using {{ $values.refID.Labels }} creates a map, and i wanted to create a URL to another application containing the IDs of the event that generated an error.

My current workaround is that i defined alias mappings for the fields i needed and placed them in "root" of the document without any special characters in the name. This allows grafana tu use them with the $labels syntax. Still, it would be nice for Grafana to support them natively.

**Comment by JohnnyQQQQ** [comment]
We are going to close this, the solution by @altuhovsu seems correct to us as it's the go-template way to do this.
