### ISSUE TITLE
InfluxBD data source based on Flux query language not working any more

### ISSUE THREAD

**Issue by dollarrama** [grafana/grafana#40204]
**What happened**
I installed Grafana enterprise v8.2.0
After that the previous configured Data Source (influxdb - Flux Query language) throws an error.
No measurements can de read anymore 
Deleting and configuring the data source again does not help - throws the same error

**Expected**
Data source should work as before

**How to reproduce it (as minimally and precisely as possible)**:
Just configure a Data Source (influxdb - Flux Query language) and click "Save & Test"

**Anything else we need to know?**:
See screenshot below or click "Details" to get more information 

**Environment**:
- Grafana version: 8.2.0
- Data source type & version: influxdb - Flux Query language
- OS Grafana is installed on: Ubuntu (ARM)
- User OS & Browser: -
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/92152667/136533480-cb67f022-bf5a-4b99-b79c-a3ea527a316e.png)

**Comment by gabor** [comment]
hi @dollarrama , i am unable to reproduce the issue.

is the error happening to you when you press [save & test] on the configure datasource page?
if yes, could you send a screenshot with the error from the configure datasource page?

**Comment by dollarrama** [comment]
Hello,
I'm not sure what exactly happend ... 

After filing the issue I did some more investigations by doing following steps:
- Going back to grafana-enterprise=8.1.7
- Same issue "unexpected error" with this data source 
- applied the token for influxdb read access in DataSource configuration once again
--> data source worked with v8.1.7 !!!
- updated grafana-enterprise a second time to 8.2.0
--> now DataSource works with v8.2.0 (even without adding the token once again)

Closed for now ...
