### ISSUE TITLE
Template Variables picks up time instead of actual metric (InfluxDB)

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4021]
Template Query : SELECT alertTypeId FROM mydb."default".dataquality

This query in influx DB returns two columns (time, alertTypeId), time is always selected in influx DB. Looks like Grafana picks up column #0 and hence time is selected as shown in below picture

<img width="1383" alt="screen shot 2016-02-13 at 6 01 35 pm" src="https://cloud.githubusercontent.com/assets/406777/13031256/da725ea6-d27b-11e5-924b-8d30e95573ed.png">

**Comment by deepujain** [comment]
Actual Query Ran by Grafana (logs) : SELECT alertTypeId FROM mydb."default".dataquality

**Comment by torkelo** [comment]
only metric exploration queries are supported for templating right now, 

For example:  `SHOW TAG VALUES WITH KEY = "hostname"`
