### ISSUE TITLE
$interval template value not picked groupBy time function - Influx DB backend

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4022]
interval variable does not change the graph.

interval = 1d
<img width="1371" alt="1d interval" src="https://cloud.githubusercontent.com/assets/406777/13031684/88dc2964-d28a-11e5-96da-deee5f8cee86.png">

interval = 2d
<img width="1364" alt="2d interval" src="https://cloud.githubusercontent.com/assets/406777/13031689/955b1114-d28a-11e5-8788-20e76609291e.png">

However if i use constant "1d" / "2d" within time, then the graph changes.
<img width="1380" alt="screen shot 2016-02-13 at 7 46 05 pm" src="https://cloud.githubusercontent.com/assets/406777/13031691/c3f17dc4-d28a-11e5-8903-675e6e6af452.png">
<img width="1371" alt="screen shot 2016-02-13 at 7 45 56 pm" src="https://cloud.githubusercontent.com/assets/406777/13031692/c3f36aa8-d28a-11e5-982b-482ba222fb1e.png">

**Comment by torkelo** [comment]
please name the variable something else, `$variable` and `$timeFilter` are variables used internally by the influxdb editor,
