### ISSUE TITLE
Annotation are not shown and not saved,

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4023]
Below is my annotation:

Edit: 
<img width="1385" alt="screen shot 2016-02-13 at 7 55 11 pm" src="https://cloud.githubusercontent.com/assets/406777/13031745/beced82c-d28b-11e5-839a-b3721e1692f8.png">

Save: 
<img width="1384" alt="screen shot 2016-02-13 at 7 55 19 pm" src="https://cloud.githubusercontent.com/assets/406777/13031743/becd9b38-d28b-11e5-80e5-1f01ec24b40d.png">

Annotation Lost on Edit:
<img width="1388" alt="screen shot 2016-02-13 at 7 55 24 pm" src="https://cloud.githubusercontent.com/assets/406777/13031744/bece7b5c-d28b-11e5-82b9-5740c54c5472.png">

Also the annotation has no effect on graphs.

InfluxDB: 

> select experimentId, metricValue from dataquality where alertId='5'
name: dataquality
-----------------
time			            experimentId	metricValue
1454400000000000000	13785		19.38
1454400000000000000	13524		1.3
1454400000000000000	13391		0.35
1454400000000000000	12753		0.24
1454400000000000000	13391		0.56

**Comment by deepujain** [comment]
<img width="1395" alt="screen shot 2016-02-13 at 11 11 05 pm" src="https://cloud.githubusercontent.com/assets/406777/13032428/1f5710a4-d2a7-11e5-971c-fc410f37733c.png">

**Comment by torkelo** [comment]
thanks for reporting this, was a bug in master (3.0 pre release build). 

But there is another problem with your query, you need to have `WHERE  $timeFilter` so grafana can filter the annotation query based on the dashboard time range

**Comment by mpergament** [comment]
I do not see it working even with 92f4442 change.

**Comment by torkelo** [comment]
Did you update your query? It is working here

**Comment by mpergament** [comment]
Yes the query is updated and correct.

Am Donnerstag, 18. Februar 2016 schrieb Torkel Ödegaard :

**Comment by mpergament** [comment]
![influxdb](https://cloud.githubusercontent.com/assets/13856387/13158650/bb20f72c-d642-11e5-9159-bd3f10ea7622.jpg)
![grafana](https://cloud.githubusercontent.com/assets/13856387/13158656/c0f3f21c-d642-11e5-96b0-987fef0f9e17.jpg)

**Comment by mpergament** [comment]
It is a different issue (time zones in influx DB). Sorry!

**Comment by deepujain** [comment]
How do i get this fix ? I have built grafana from source using http://docs.grafana.org/project/building_from_source/ .  

Please share the steps
