### ISSUE TITLE
Testing Alert Rule gives error

### ISSUE THREAD

**Issue by cprasad-1512** [grafana/grafana#40249]
**What happened**:
I've two grafana dashboards for one datasource is  "Azure SQL" and for other  it is "Azure log Analytics Workspace".
I've created the Alert Rules using grafana dashboard and while testing Alert Rule, I'm getting below error:

**request handler response error {request failed, status: 404 Not Found, body: {\"error\":{\"message\":\"The requested path does not exist\",\"code\":\"PathNotFoundError\",\"correlationId\":\"7b069314-2e3d-4ce2-8e71-499e1f20aff2\"}}}",**

Detailed error message is below:
```{
  "firing": true,
  "state": "pending",
  "conditionEvals": " = true",
  "timeMs": "-938.866ms",
  "error": "request handler response error {request failed, status: 404 Not Found, body: {\"error\":{\"message\":\"The requested path does not exist\",\"code\":\"PathNotFoundError\",\"correlationId\":\"7b069314-2e3d-4ce2-8e71-499e1f20aff2\"}}  A <nil> [] [] 0xc0015512f0}",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1633850920950,
        "queries": [
          {
            "refId": "A",
            "model": {
              "appInsights": {
                "dimension": [
                  "none"
                ],
                "metricName": "select",
                "rawQuery": false,
                "rawQueryString": "",
                "timeColumn": "timestamp",
                "timeGrain": "auto",
                "valueColumn": ""
              },
              "azureLogAnalytics": {
                "query": "KubePodInventory\n| where TimeGenerated > ago(2m)\n| where ClusterName == \"$AKS\"\n| summarize arg_max(TimeGenerated, *) by ContainerName\n| project Name, ContainerName, Namespace\n| join kind = inner (\n    Perf\n    | where $__timeFilter(TimeGenerated)\n    | where ObjectName == 'K8SContainer'\n    | where CounterName == 'cpuUsageNanoCores'\n    | where InstanceName contains '$AKS'\n    | extend ContainerNameParts = split(InstanceName, '/')\n    | extend ContainerNamePartCount = array_length(ContainerNameParts)            \n    | extend PodUIDIndex = ContainerNamePartCount - 2, ContainerNameIndex = ContainerNamePartCount - 1 \n    | extend ContainerName = strcat(ContainerNameParts[PodUIDIndex], '/', ContainerNameParts[ContainerNameIndex])\n    | extend Time = format_datetime(TimeGenerated, \"yyyy-MM-dd HH:mm\")\n    | project Time, ContainerName, CounterValue\n) on ContainerName\n| summarize CoresPerNamespace=sum(CounterValue) by Time, Namespace\n| order by Time asc\n| project make_datetime(Time), Namespace, CoresPerNamespace / 1000000",
                "resource": "$Workspace",
                "resultFormat": "time_series"
              },
              "azureMonitor": {
                "aggOptions": [],
                "dimensionFilter": "*",
                "metricDefinition": "select",
                "metricName": "select",
                "metricNamespace": "select",
                "resourceGroup": "select",
                "resourceName": "select",
                "timeGrain": "auto",
                "timeGrains": [],
                "top": "10"
              },
              "queryType": "Azure Log Analytics",
              "refId": "A",
              "subscription": "XXXXXXXXXX"
            },
            "datasource": {
              "id": 1,
              "name": "Azure Monitor"
            },
            "maxDataPoints": 1500,
            "intervalMs": 200
          }
        ],
        "to": 1633851220950
      }
    }
  ]
}
```

**What you expected to happen**: 
I'm expecting that it should not throm error while testing Alert rule.

**How to reproduce it (as minimally and precisely as possible)**:
Create any grafana dashboard and test alert rule.

**Anything else we need to know?**:
i've tried running grafana locally, in azure vm and azure app service. And, all three setups gives the same error while test the alert rule.

**Environment**:
- Grafana version: 8.2
- Data source type & version: Azure SQl DB  and Azure log analytics workspace
- OS Grafana is installed on: windows

**Comment by sunker** [comment]
Thanks for reporting this @cprasad-1512. I think this might be related to https://github.com/grafana/grafana/issues/39444. 

Just to confirm, do you know if this alerting rule used to work before in previous versions of Grafana? Can you please share your whole dashboard.json with us?

**Comment by sunker** [comment]
I just noticed that a template variable is being used in your query. Template variables are not supported in alerting queries. 

When a template variable is used in the query, the query editor should not allow you to create an alert, so that's a bug. I'll try to fix that asap.

**Comment by cprasad-1512** [comment]
Hi @sunker , 
I imported the avaliable "AKS Monitor Container" Dashboard and in that, the variable is used in the query editor.
FYI:
![image](https://user-images.githubusercontent.com/80390752/140325987-ebc1d8de-9736-4bd6-bdad-9fa0c5c7c4e7.png)

Is this the template variable are you mentioning?
If it is, they you are right, it is bug.
And if it's not, then let me know if you need some more information about this.
Thanks!

**Comment by sunker** [comment]
Hi! Yes - seems like a variables are being used in the _resource_ field and in the query.

So the bug is that you allowed to create the alert rule. This should be prevented. We'll try to come up with a fix for that asap.

**Comment by cprasad-1512** [comment]
Hi!
Ok, got it.
So, is there any other way to create rule?
If it is, then please suggest me.
Or,
If not, then please fix this bug asap as we need to use this in our project urgently.
Thanks for your help!

**Comment by sunker** [comment]
There's no way to use template variables in alerting rules. If you need the alert rules, you have to remove the variables from your query and replace them with real values. 

A fix, making it impossible to create this rule, will come soon.

**Comment by cprasad-1512** [comment]
Sure @sunker !
Will be waiting for the fix!!

**Comment by cprasad-1512** [comment]
Hi  @sunker ,
Can you please tell me that in which version of Grafana , this fix can be seen?
Also, How i can know reproduce this fix?

Thanks!

**Comment by sunker** [comment]
Grafana 8.3.0 which will be released in a few weeks.
