### ISSUE TITLE
Loki: Support $__interval in alerting queries

### ISSUE THREAD

**Issue by viraptor** [grafana/grafana#40241]
**What happened**:
After creating an alert based on a loki query and trying to test it, I get an error.
From the message it looks like it doesn't know how to handle the interval variable in alert context.

**What you expected to happen**:
A test notification and reasonable handling of `$__interval`

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel with query `count_over_time({unit=\"foo.service\"} |= \"ClientConnect\" [$__interval])`

**Anything else we need to know?**:

Error received:
```
{
  "firing": true,
  "state": "",
  "conditionEvals": " = true",
  "timeMs": "5.418ms",
  "error": "request handler error: failed to query data: Error response from server: parse error at line 0, col 59: not a valid duration string: \"$__interval\" (<nil>)",
  "logs": [
    {
      "message": "Condition[0]: Query",
      "data": {
        "from": 1633733024560,
        "queries": [
          {
            "refId": "A",
            "model": {
              "expr": "count_over_time({unit=\"foo.service\"} |= \"ClientConnect\" [$__interval])",
              "legendFormat": "connects",
              "refId": "A"
            },
            "datasource": {
              "id": 8,
              "name": "Loki"
            },
            "maxDataPoints": 1500,
            "intervalMs": 1000
          }
        ],
        "to": 1633734824560
      }
    }
  ]
}
```

The alert works correctly if I change to range to a static `[1m]` or similar..

**Environment**:
- Grafana version: 8.2 (d7f71e9eae)
- Data source type & version: Loki
- OS Grafana is installed on: Fedora 34
- User OS & Browser: -
- Grafana plugins: -
- Others:

**Comment by torkelo** [comment]
@ivanahuckova looks like the code that replaces the built-in variables like __interval are not part of the loki backend go, i
it is part of the prometheus backend code:
https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/prometheus.go#L288

**Comment by ivanahuckova** [comment]
This can be ideally tackled during backend migration of Loki data source.
