### ISSUE TITLE
Incorrect data reported on single stat value, grafana + influxDB

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4024]
There is only 7 days of data ingested and single stat reports correct current value for today, yesterday and zooming out continuously shows correct current value. However zooming out eventually shows incorrect current value.

Zoom #1:
<img width="1370" alt="screen shot 2016-02-13 at 8 22 47 pm" src="https://cloud.githubusercontent.com/assets/406777/13031844/e0f7f5d8-d28f-11e5-8c90-43a8b84c5ad6.png">

Zoom #2:
<img width="1385" alt="screen shot 2016-02-13 at 8 23 22 pm" src="https://cloud.githubusercontent.com/assets/406777/13031846/e0f93cea-d28f-11e5-9815-f164c591126d.png">

Zoom #3: (Error)
<img width="1383" alt="screen shot 2016-02-13 at 8 23 33 pm" src="https://cloud.githubusercontent.com/assets/406777/13031845/e0f8fa3c-d28f-11e5-83b2-6c7705d61e33.png">

**Comment by deepujain** [comment]
N/A
<img width="1386" alt="screen shot 2016-02-13 at 8 30 34 pm" src="https://cloud.githubusercontent.com/assets/406777/13031858/ad853408-d290-11e5-8dfd-6a613754964f.png">

**Comment by torkelo** [comment]
looks like a problem with your InfluxDB query? In the error state can you show the response from InfluxDB? (open chrome dev tools network tab)

**Comment by deepujain** [comment]
{
  "error": "error parsing query: found y, expected ) at line 1, char 113",
  "message": "error parsing query: found y, expected ) at line 1, char 113"
}

**Comment by torkelo** [comment]
Looks like influxdb does not like your query
