### ISSUE TITLE
Live: Live timer is always initialized 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#40252]
Not sure how much this matters but feels inefficient to always register this measure callback which is called 10 times a second always no matter what Grafana page or dashboard your on or no matter what live time settings are. 

https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/dashgrid/liveTimer.ts#L113

Can we figure out a way to have this interval timer only active when needed?

**Comment by leeoniya** [comment]
we were quite careful in implementing this to ensure it does not affect performance. a 30s profile shows that it takes just 0.7ms. the more expensive part inside the `if` does not actually run unless you have the live dashboard setting enabled.

![image](https://user-images.githubusercontent.com/43234/136710911-4fb153d7-cf5a-4b31-9165-bb66873b510e.png)

![image](https://user-images.githubusercontent.com/43234/136710803-563d0bf8-1008-479e-b051-fe608d29a7ef.png)
