### ISSUE TITLE
Drilldown from grafana to kibana

### ISSUE THREAD

**Issue by deanefrati** [grafana/grafana#4026]
Hi, 

Is there a way to pass the time span and potentially the lucene query from grafana to kibana using a direct URL drilldown?

My use case is that i have some dashboards in grafana visualizing data from multiple sources (primarily influxdb and elasticsearch). I would like to give users the option to view more detailed log information in kibana by drilling down on a grafana dashboard. I can create the drilldown to a particular kibana dashboard very easily but haven't figured out a way to also pass the filters and time period. 

Thanks,
Dean

**Comment by deepujain** [comment]
Are you setting drill down URL on single stat panel ? What panel are you using ?

**Comment by deanefrati** [comment]
Just a regular graph panel

**Comment by torkelo** [comment]
if your lucene query is in a template variable yes, and if Kibana supports time range format grafana sends (from / to in unix epochs)
