### ISSUE TITLE
X Axis time modified when graph panel is plotted.

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4027]
My data collection dates are all at 00:00:00 for a day. (right at beginning) . When i plot below graphs the points seem to have moved. Why is that ?

<img width="1372" alt="screen shot 2016-02-13 at 10 26 28 pm" src="https://cloud.githubusercontent.com/assets/406777/13032281/0fa59474-d2a1-11e5-9b21-df9f86005faa.png">
<img width="1382" alt="screen shot 2016-02-13 at 10 27 30 pm" src="https://cloud.githubusercontent.com/assets/406777/13032282/0fa62880-d2a1-11e5-93b2-46d8bae35a71.png">

Is it a bug ?

**Comment by deepujain** [comment]
Changing dashboard setting to UTC from Browser started to show correct time in X axis

<img width="1377" alt="screen shot 2016-02-13 at 10 30 36 pm" src="https://cloud.githubusercontent.com/assets/406777/13032297/6d090fd8-d2a1-11e5-881f-a4ba5acec5c3.png">

**Comment by deepujain** [comment]
IT moved again. Even with UTC. I did not change anything.

![Uploading Screen Shot 2016-02-13 at 10.34.45 PM.png…]()

**Comment by torkelo** [comment]
maybe a problem with your InfluxDB query, not sure InfluxDB has a way to align group by time windows (or maybe it does)
