### ISSUE TITLE
Dashboard Panel, tags is not saved.

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4028]
I attached a tag "boards" to each of my dashboards.

I then created a dashboard panel with Mode as query.

I gave "boards" in tags and left query empty. Click save and come back to see that tags filed and empty and the dashboard list is not filtered by tags.

<img width="1391" alt="screen shot 2016-02-14 at 12 16 48 am" src="https://cloud.githubusercontent.com/assets/406777/13032665/55b6c898-d2b0-11e5-901f-3d73b6f403ca.png">
<img width="1387" alt="screen shot 2016-02-14 at 12 17 15 am" src="https://cloud.githubusercontent.com/assets/406777/13032664/55b6729e-d2b0-11e5-980a-a727e9635333.png">

**Comment by torkelo** [comment]
seems to work fine here, http://play.grafana.org/dashboard/db/issue-4028-tags-search?panelId=1&fullscreen&edit 

when you add a tag to the tags search you need to press "enter" key to add the tag
