### ISSUE TITLE
Is it possible to generate non time based graphs ?

### ISSUE THREAD

**Issue by groblus** [grafana/grafana#4029]
Is it possible to genereate a graph not based on time ?
Imagine pulling two fields from influx - one as a domain and the other for values, and then plotting them. 
Can it be done somehow?

**Comment by torkelo** [comment]
not currently :(

**Comment by dardik** [comment]
It's been 2 years since this was asked.
Is it possible now?

**Comment by torkelo** [comment]
Sadly no :( would love this as well
