### ISSUE TITLE
Support listening on a UNIX socket

### ISSUE THREAD

**Issue by julianbrost** [grafana/grafana#4030]
I'd like to be able to make Grafana listen on a UNIX socket. This can be useful when running Grafana with external authentication performed by the webserver, as you can easily prevent other local users from directly connecting to the socket via filesystem permissions.

This Go code can be used to handle HTTP requests on a UNIX socket:

``` go
l, err := net.Listen("unix", "/run/grafana/http.socket")
if err != nil {
    panic(err)
}

err = http.Serve(l, nil)
if err != nil {
    panic(err)
}
```

For testing, nginx supports `proxy_pass http://unix:/run/grafana/http.sock:/;`

**Comment by gummiboll** [comment]
:+1: I'm always for running services through unix sockets.

However, _on a side-note and not really sure if this is still the case_, but go's implementation of fcgi looks like its a bit slow: https://gist.github.com/hgfischer/7965620

**Comment by julianbrost** [comment]
I wasn't talking about FastCGI, you can do normal HTTP over UNIX sockets.

In the benchmark you reference, FastCGI over UNIX socket is fast than over TCP, so you might even get a bit more performance when doing HTTP over UNIX sockets compared to TCP.

And implementing this should be pretty easy, I think it would need no more than about 10 to 20 lines of code.

**Comment by cactus** [comment]
Searching for info on Grafana and unix socket support brought me here.
I run grafana behind nginx, and currently have it listening on loopback.
It would be nice to move it over to a unix sock.
