### ISSUE TITLE
Readme part which helps to run grafana on 80 port under unpriviledged user

### ISSUE THREAD

**Issue by xytis** [grafana/grafana#4034]
I've successfully ran grafana under grafana user with permitions to bind 80 port.

This was done under Debian with systemd.

In order to achieve this I added this line to grafana-server.service:
ExecPreStart=/sbin/setcap 'cap_net_bind_service=+ep' /usr/sbin/grafana-server

I suppose a tiny mention in current readme file to systemd capabilities and several setting lines could help other users to achieve this too:

https://www.freedesktop.org/software/systemd/man/systemd.exec.html#Capabilities=
https://github.com/kabukky/journey/wiki/Creating-a-Journey-service-using-systemd#2-create-the-journeyservice-file

As I understood, systemd way of doing the same would be:
CapabilityBoundingSet=CAP_NET_BIND_SERVICE

Yet this did not work for my setup, and I did not bother to look further.

Should I create a PR to readme file with aggregated info regarding my experience, or you have plans making this option a default in existing systemd service file?

**Comment by torkelo** [comment]
the config docs already have instructions for how to give the grafana binary permission to use port 80
