### ISSUE TITLE
Missing index creating DB high cpu usage

### ISSUE THREAD

**Issue by deathwarrior60** [grafana/grafana#40388]
**Environment**:
- Grafana version: 8.1.5
- OS Grafana is installed on: centos 7
- Database : Mysql

We had an incident our grafana instance, the DB cpu usage was really high causing latency on the webapp.
We managed to fix it but I have a question about the SQL request issue by grafana so I will describe our incident.

For information on our grafana instance :
 users: ~27000
 org : ~5500

So latency on the webapp was noticed. It appeared that it was caused by our mysql DB having it's CPU to the max.
When doing a show full processlist we quickly realised that we had request from grafana taking ~20s, here's the request : 
`SELECT
u.id as user_id,
u.is_admin as is_grafana_admin,
u.email as email,
u.login as login,
u.name as name,
u.help_flags1 as help_flags1,
u.last_seen_at as last_seen_at,
(SELECT COUNT(*) FROM org_user where org_user.user_id = u.id) as org_count,
org.name as org_name,
org_user.role as org_role,
org.id as org_id
FROM `user` as u
LEFT OUTER JOIN org_user on org_user.org_id = u.org_id and org_user.user_id = u.id
LEFT OUTER JOIN org on org.id = org_user.org_id WHERE u.id=27010;`
(we had ~30 of those running a the same time)

When doing an explain : 
`mysql> explain SELECT
    ->                 u.id             as user_id,
    ->                 u.is_admin       as is_grafana_admin,
    ->                 u.email          as email,
    ->                 u.login          as login,
    ->                 u.name           as name,
    ->                 u.help_flags1    as help_flags1,
    ->                 u.last_seen_at   as last_seen_at,
    ->                 (SELECT COUNT(*) FROM org_user where org_user.user_id = u.id) as org_count,
    ->                 org.name         as org_name,
    ->                 org_user.role    as org_role,
    ->                 org.id           as org_id
    ->                 FROM `user` as u
    ->                 LEFT OUTER JOIN org_user on org_user.org_id = u.org_id and org_user.user_id = u.id
    ->                 LEFT OUTER JOIN org on org.id = org_user.org_id WHERE u.id=132;
+----+--------------------+----------+------------+-------+-------------------------------------------------+-----------------------------+---------+-------------+---------+----------+--------------------------+
| id | select_type        | table    | partitions | type  | possible_keys                                   | key                         | key_len | ref         | rows    | filtered | Extra
 |
+----+--------------------+----------+------------+-------+-------------------------------------------------+-----------------------------+---------+-------------+---------+----------+--------------------------+
|  1 | PRIMARY            | u        | NULL       | const | PRIMARY                                         | PRIMARY                     | 8       | const       |       1 |   100.00 | NULL
 |
|  1 | PRIMARY            | org_user | NULL       | const | UQE_org_user_org_id_user_id,IDX_org_user_org_id | UQE_org_user_org_id_user_id | 16      | const,const |       1 |   100.00 | NULL
 |
|  1 | PRIMARY            | org      | NULL       | const | PRIMARY                                         | PRIMARY                     | 8       | const       |       1 |   100.00 | NULL
 |
|  2 | DEPENDENT SUBQUERY | org_user | NULL       | index | NULL                                            | UQE_org_user_org_id_user_id | 16      | NULL        | 1395639 |    10.00 | Using where; Using index |
+----+--------------------+----------+------------+-------+-------------------------------------------------+-----------------------------+---------+-------------+---------+----------+--------------------------+`

It seemed that the subquery was the issue.

When trying to execute it alone, it was taking ~15s
`mysql> select count(*) from org_user;
+----------+
| count(*) |
+----------+
|  1402096 |
+----------+
1 row in set (16.04 sec)`

since in the original subrequest there is contraint on the user_id, we decide to look at the index of org_user : 
`mysql> show index from org_user;
+----------+------------+-----------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| Table    | Non_unique | Key_name                    | Seq_in_index | Column_name | Collation | Cardinality | Sub_part | Packed | Null | Index_type | Comment | Index_comment |
+----------+------------+-----------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+
| org_user |          0 | PRIMARY                     |            1 | id          | A         |     1394463 |     NULL | NULL   |      | BTREE      |         |               |
| org_user |          0 | UQE_org_user_org_id_user_id |            1 | org_id      | A         |        6149 |     NULL | NULL   |      | BTREE      |         |               |
| org_user |          0 | UQE_org_user_org_id_user_id |            2 | user_id     | A         |     1395639 |     NULL | NULL   |      | BTREE      |         |               |
| org_user |          1 | IDX_org_user_org_id         |            1 | org_id      | A         |        5451 |     NULL | NULL   |      | BTREE      |         |               |
+----------+------------+-----------------------------+--------------+-------------+-----------+-------------+----------+--------+------+------------+---------+---------------+`

There is multiple-column index with user_id, but none with only user_id, so we tried to add it : 
`create index IDX_org_user_id on org_user(user_id) ;`

And solved the issue, the request took now less a second.

My question being : why is this request used for and issue that often ? is it really necessary to re calculate the org_count of the user everytime ?

Thanks in advanced.
Regards

**Comment by papagian** [comment]
It seems that this was resolved by #39002.
Thank you for reporting it!
