### ISSUE TITLE
Specifying plugin directory

### ISSUE THREAD

**Issue by mkoree** [grafana/grafana#4038]
Hi,

Is there a way to override the path where Grafana takes its plugins from (e.g. like overriding settings in defaults.ini with env variables)? Or to have an additional directory specified which contains custom plugins? The reason why I'm asking is that in my company I can run grafana but don't have permissions to put anything inside its installation directory - and therefore cannot use my custom plugin unless I am able to tell grafana where to find it. 

Thanks,
Kornel

**Comment by torkelo** [comment]
yes, in master / upcoming 3.0 (and 3.0 pre release builds) you can specify an external plugin path '

https://github.com/grafana/grafana/blob/master/conf/sample.ini#L21

**Comment by mkoree** [comment]
Thanks for the info.
