### ISSUE TITLE
/api/ds/query sometimes seems to return incorrect JSON responses

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#40398]
**What happened**:
We've received some reports of calling /api/ds/query returns an incorrect JSON payload. Some incorrect examples
```
"env":"something"rames":[{"schema":{"name":"{env=\"something\"}"
"env":"something2"ema":{"name":"{env=\"something2\"}"
{"results":{"A":{}}}ames":[{"schema":{"name":"{env=\"something3\"}"
```

**What you expected to happen**:
Correct JSON payload returned, e.g.
```json
{"results":{"A":{"frames":[{"schema":{"name":"{env=\"something\"}"
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
There's no 100% proof this is a Grafana problem, but seems likely. This [code](https://github.com/grafana/grafana-plugin-sdk-go/blob/5169c0aeb8a09cd9eadcfeb1368129847d60a09d/backend/data.go#L76-L81) might be interesting, related to https://github.com/json-iterator/go/issues/258 perhaps. Idea being a concurrency issue when a lot of concurrent queries are happening.

**Environment**:
- Grafana version: 8.x something 
- Data source type & version: The problem has been spotted using Prometheus or Graphite

**Comment by lucas-pate** [comment]
I believe that I am experiencing this issue as well. I have attempted to upgrade from 7.5.x to 8.2.4 but noticed that some dashboards using CloudWatch metrics were reporting "No Data" periodically. I managed to record the response from /api/ds/query, and Firefox reported it as JSON parse error.

I compared a valid response to an invalid one, and it appears that a label is pre-pended to the JSON response, and the result object is missing.

Beginning of good response:
`{"results":{"A":{"frames":[{"schema"`

Beginning of bad response (name edited, but length kept the same):
`"ClusterName":"name1234567"{"schema":{"`

I don't know if it's just a coincidence, but the ``"ClusterName":"name1234567"` is exactly the same length as `{"results":{"A":{"frames":[`, so it is almost like it was just pasted on top of the beginning of the valid JSON. The rest of the JSON matches and is valid.

**Comment by marefr** [comment]
Should hopefully be fixed with https://github.com/grafana/grafana/pull/42167 and https://github.com/grafana/grafana-plugin-sdk-go/pull/429. Will be included in Grafana v8.3.0.

**Comment by lucas-pate** [comment]
I pulled grafana/grafana-enterprise:main in my test environment, and I'm no longer seeing this issue. Thanks!

**Comment by marefr** [comment]
Thanks! Closing this. Let us know if you still experience this and we'll reopen it.
