### ISSUE TITLE
ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found

### ISSUE THREAD

**Issue by rayprill** [grafana/grafana#4039]
This may be the same as closed issue #3323.

We get multiple logs on a loaded system with a complex dashboard.  Grafana is v 2.5.0-pre1, along with graphite database at release level 0.9.12. The symptom is the Timeseries data request error along with thousands of occurrences of the following in the grafana log:

2016/02/12 16:25:48 [dataproxy.go:72 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found
2016/02/12 16:25:48 [I] Completed /api/datasources/proxy/4/render 500 Internal Server Error in 14.84622ms

The grafana configuration for database takes the default.  We did not change it. We have two datasources defined via the UI: elasticsearch and graphite. We are storing dashboards in elasticsearch. Otherwise the metrics datasource is graphite to the localhost.

More info: in our case this only happens with complex dashboards that are refreshed at a high frequency (5 seconds), and we cannot always reproduce it. Additionally, graphite is being briskly updated with continuous incoming data.

My theory is that graphite is not playing well with grafana. I turned trace and debug on, but no more info was provided. A peek at dataproxy.go source code shows no more log output, so that makes sense, although more info would be helpful.

Graphite/carbon db is configured with "inf" cache size. Is this a factor? Is serving the query too expensive? Not sure, but it is one idea I'm tossing around.

Any further information or suggestions are welcome.

**Comment by torkelo** [comment]
what is your Grafana database? sqlite3 or mysql or postgres?

**Comment by rayprill** [comment]
it is sqlite3.  We didn't change the database section of "grafana.ini", so presume the "defaults.ini" defines the config as:

[database]
# Either "mysql", "postgres" or "sqlite3", it's your choice
type = sqlite3
host = 127.0.0.1:3306
name = grafana
user = root
password =
# For "postgres" only, either "disable", "require" or "verify-full"
ssl_mode = disable
# For "sqlite3" only, path relative to data_path setting
path = grafana.db

**Comment by torkelo** [comment]
try changing to mysql or postgres, could be an issue with sqlite3 under high load, not sure though

**Comment by rayprill** [comment]
OK I will try that.  It will take a bit for me to get that running, but I'll report back.

**Comment by rayprill** [comment]
Update: we tried mysql and saw no improvement.

**Comment by rayprill** [comment]
More information.  On rare occasions, when I hit the graphite database with a raw render request (something like https://<ip>/graphite/render?&<query>") I'll get a corrupt record.  I presume that under the covers Grafana is doing something similar.  If so, Grafana will get something it may not expect if it comes back garbage.  It seems to be able to handle quite a few of these before giving up.

If this correlates to the error message that is the topic of this thread, then you can close this torkelo, and I'll look into Graphite.  Your performance notes mention that 0.9.14 is better than 0.9.12.  We are at 12, so perhaps that is a place to start.

**Comment by torkelo** [comment]
Yes, 0.9.12 is hardly usable as it return way to many points, on the corruption side sounds like an old bug in graphite where the json api randomly returns a one image

**Comment by trompx** [comment]
Hello @torkelo,

I get this error too `[dataproxy.go:87 ProxyDataSourceRequest()] [E] Unable to load datasource met a data: Data source not found` but for a different reason.

I deploy grafana with ansible, and I generate my datasources dynamically with jinja2 so I can set the datasource url base on my infra.
Then I run grafana 2.6 in docker, and in my startup script, I automatically add the datasource.
I have another script that backup the grafana.db (sqlite3) which backup the datasource too. 

Now say I want to deploy grafana to another server and restore the backup, but the datasource changed. I first restore the data, then remove the datasource. During startup, grafana detects that the datasource is missing add the new datasource.

I hit the error at that point. I guess it is because the datasource id changed and the link between a datasource and a dashboard is made on that id.

Would it be possible to link a datasource and a dashboard by the datasource name as an option?

**Comment by torkelo** [comment]
dashboard panels only refer to datasource by name not id

**Comment by rlex** [comment]
happened to me as well. 
t=2016-11-29T21:26:55+0300 lvl=eror msg="Unable to load datasource meta data" logger=context userId=2 orgId=2 uname=lex error="Data source not found"
t=2016-11-29T21:26:55+0300 lvl=eror msg="Request Completed" logger=context userId=2 orgId=2 uname=lex method=GET path=/api/datasources/proxy/12/query status=500 remote_addr=127.0.0.1 time_ms=1ns size=49

Tried switching to postgres (no migration, brand new install) - same issue.
