### ISSUE TITLE
Improvement: Fetch filters list from /api/config/filters in PR #3981

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4040]
Currently, all 7 filters are hardcoded in #3981. Ideally, the list of filters should be fetched from Opentsdb API - /api/config/filters.

**Comment by utkarshcmu** [comment]
This can be done when we fix #4056 otherwise implementing this functionality will face the same bug as in #4056

**Comment by bergquist** [comment]
solved by #4138
