### ISSUE TITLE
[ templating ] [ `custom` type ] `key : value` pairs break with duplicate `value`

### ISSUE THREAD

**Issue by PaddyProdapt** [grafana/grafana#40414]
**What happened**:  
Key with same values are disabled in the drop down menu for custom template variable (key/Value)

**What you expected to happen**:  Key with same values should not be disabled in the drop down menu PFA snaps 

**How to reproduce it (as minimally and precisely as possible)**: Try to create custom variable (key : value) with different key names but same value 
![Animation](https://user-images.githubusercontent.com/54354722/137193517-4c52549c-ad17-4b23-b8dc-00bb3810f123.gif)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1 and 7.5.8
- Data source type & version: NA
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome and firefox
- Grafana plugins: NA
- Others: NA

**Comment by ashharrison90** [comment]
hey @PaddyProdapt 👋 

can you explain a bit more about your use case for having different variables with the same value?

thanks! 😄
