### ISSUE TITLE
Slow dropdown for tags in annotation settings

### ISSUE THREAD

**Issue by psalaberria002** [grafana/grafana#40489]
**What happened**:
After upgrading to 8.x, the Tags dropdown in the Annotations section of dashboard settings
has become very slow. It can take up to 15 seconds to load after entering some text.
Previously there was no search capability, so it was instant.

**What you expected to happen**:
Tag search should be much quicker.

**How to reproduce it (as minimally and precisely as possible)**:
Grafana instance with lots of different annotations and tags.
Create a dashboard, go to annotations, add a new one,
set Grafana as data source, Filter By Tags, and type some text.
In addition, in our case we use variables in the annotation tags (e.g. `$kubernetes_cluster`),
which will always fail the search.

**Anything else we need to know?**:
<img width="725" alt="Screenshot 2021-10-14 at 22 27 25" src="https://user-images.githubusercontent.com/2410564/137391029-bc1e0276-e3d5-494b-aa62-c3ef5fed4dfe.png">

**Environment**:
- Grafana version: 8.1.6
- Data source type & version: Grafana (Tags)
- OS Grafana is installed on: Official Docker image
- User OS & Browser: MacOS/Chrome

**Comment by ashharrison90** [comment]
hi @psalaberria002 👋 

thanks so much for raising this!
i've raised a PR to address the performance issue. it will still need to make a call to the backend, but it should only be making 1 or 2 calls now (depending on your typing speed 🏃 ) as opposed to 1 every keystroke. this should hopefully go out in the upcoming 8.2.2 release.

i'm sure you're aware already, but just wanted to mention for others that while custom variables will fail the search you can still use them. when the search fails to find a matching tag, it presents an option to use your search string as a custom value.

hope that helps!
