### ISSUE TITLE
[ feature request ] [ GeoMap ] dynamically zoom to location based on input

### ISSUE THREAD

**Issue by ukkathva** [grafana/grafana#40496]
automictic zoom to location based on data content will be great value add .

**Comment by achatterjee-grafana** [comment]
This is not a doc issue, but a feature request. Removing docs label, for further traiging.

**Comment by kitarp29** [comment]
@zuchka @achatterjee-grafana  This issue is not very clear.
I want to contribute to this repo.
And this looks like a simple task.
Please explain this issue and assign it to me

**Comment by zuchka** [comment]
@kitarp29,

I believe that @ukkathva is suggesting an enhancement to [the GeoMap Plugin](https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/geomap), and not to the plugin's docs. 

I've revised the title to clarify the issue 👍

**Comment by ukkathva** [comment]
Hi Mat ,This is an issue regarding the plugin, But this auto zoom function
was  available in its world map but somehow these functions are dropped in
the new release of the map

[image: not issue.JPG][image: issye.JPG]
