### ISSUE TITLE
UX graph glitches in all builds after 2nd of Feb 

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#4049]
Hi,

In my opinion all of the latest builds (after 2 of February) seem to have some glitches with graphs presentation. For some dashboards:
- it's impossible to change graph size neither via the mouse nor by +/- clicking
- graphs are strangely compressed and contain inactive, grayed scrollbars

Examples below:
![graf1](https://cloud.githubusercontent.com/assets/12551929/13074670/569e7146-d4a6-11e5-9dc6-e42f09be0288.jpg)
![graf2](https://cloud.githubusercontent.com/assets/12551929/13074671/56a10186-d4a6-11e5-8a6f-fdf4e82b866d.jpg)

Build from 1st of February (MD5 094d0feea4cdd47b263adeb80b055966) is the last which renders every graph properly on all my dashboards. Any ideas what might cause this?

**Comment by bergquist** [comment]
I guess it was introduced by my fix for https://github.com/grafana/grafana/issues/1277 in https://github.com/grafana/grafana/commit/73bed3880f3232f0eb9805e1ef91d7b3a2c97252 

What browser, OS are you using?

**Comment by pavleec** [comment]
Checked on WinXP - Firefox 40.0.3 and Win7 - FF 38.6.0 ESR. Look's exactly the same on both.

**Comment by bergquist** [comment]
Its indeed that fix that causes the problem. overflow-y: scroll should only be added if the height of the inner box is bigger then the panel itself.

**Comment by pavleec** [comment]
Has this been fixed in the latest builds then? Today's version (22.02) still has the same glitches on graphs...

**Comment by pavleec** [comment]
Here is how it look's like - completely messed General tab on graph Edit page: (build from 24 of Feb)
![grafana](https://cloud.githubusercontent.com/assets/12551929/13281877/85b7043e-dae6-11e5-86d1-17ec38923e76.JPG)

**Comment by bergquist** [comment]
Seems to be something else that causes all those problems. We have started using css flexbox in master which is supported in FF 43+. Any chance you could try upgrading FF?

http://caniuse.com/#search=flex

**Comment by pavleec** [comment]
I've checked it in all the latest browsers FF 44, FF 43 and Chrome 48 (all freshly installed). Only Chrome seems to be closest in rendering it properly - graphs are fine but table panel is displayed in half of it's size and is not resizable.
Here are the screenshots from:
**FF43**
![ff43](https://cloud.githubusercontent.com/assets/12551929/13291329/a1d1243e-db17-11e5-8769-476233bd78f7.png)
**FF44**
![ff44](https://cloud.githubusercontent.com/assets/12551929/13291332/a4e547a4-db17-11e5-8e28-5aedb4af2eb2.JPG)
**Chrome 48**
![chr48](https://cloud.githubusercontent.com/assets/12551929/13291339/aada34ee-db17-11e5-86b3-9a5222a67f1b.JPG)

**Comment by pavleec** [comment]
I've additionally found that the above issue appears always when I activate the "**Repeat Panel**" option with defined template variable. Just create any new dashbard, add template variable and used it on repeat panel for a new graph - General tab starts looking like total mess then.
![bez tytulu](https://cloud.githubusercontent.com/assets/12551929/13748515/6a9f3ca4-e9fd-11e5-9c35-cb91931da5a9.jpg)

**Comment by sbengo** [comment]
Hi, after updating Grafana on play.grafana.com, I see the same problem as @pavleec, just exactly the same problem as the first comments.

Using Win10, FF45.0.1

Thanks for all

**Comment by mattttt** [comment]
Trying to replicate on FF 44.0.2 on OSX but cannot. Will keep trying.

**Comment by freeseacher** [comment]
@mattttt, do not try to do that. 
OSX automatically hides scrollbars when it thinks is useless. 
Do it in linux/windows

**Comment by torkelo** [comment]
closing this, reopen if there are still issues with latest beta

**Comment by pavleec** [comment]
Latest build (16.04) and latest Firefox or Chrome - still the same. Please check the following:
1.Create new dashboard, add any template variable with multi-value option selected 
2.Add graph panel with Repeat Panel option set to above variable 
When I activate more then two objects the dashboard scales like below:
![1](https://cloud.githubusercontent.com/assets/12551929/14598377/2f3460de-0552-11e6-8118-99e97d1e1a45.jpg)
and here's how the graph edit page looks like when I click on graph title > Edit:
![2](https://cloud.githubusercontent.com/assets/12551929/14598382/3449a6e2-0552-11e6-9f04-57871c551181.jpg)

**Comment by torkelo** [comment]
Did you set a min-span for the template variable? (next to the repeat option). Also there is an issue with the edit mode when you change a repeated template variable.

**Comment by pavleec** [comment]
You're right - setting the min-span solves the above problem. Edit page also looks correct then.
