### ISSUE TITLE
Unable to build Grafana on Windows from 8.2.x

### ISSUE THREAD

**Issue by tecmatia-dp** [grafana/grafana#40509]
**What happened**:
Build last versions of Grafana is failing, out of the box...

```
C:\grafana\src\github.com\grafana\grafana>go run build.go build-server
Version: 8.3.0, Linux Version: 8.3.0, Package Iteration: 1634289511pre
rm -r dist
rm -r tmp
rm -r c:\grafana\pkg\windows_amd64\github.com\grafana
building grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/windows-amd64/grafana-server.exe
rm -r ./bin/windows-amd64/grafana-server.exe.md5
go build -ldflags -w -X main.version=8.3.0-pre -X main.commit=unknown-dev -X main.buildstamp=1634289511 -X main.buildBranch=main -buildmode=exe -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server
# github.com/grafana/grafana/pkg/cmd/grafana-server/commands
pkg\cmd\grafana-server\commands\cli.go:168:12: undefined: server.Initialize
exit status 2
exit status 1
```

**What you expected to happen**:
Build without errors, as with any previous version, including 8.1.7

**How to reproduce it (as minimally and precisely as possible)**:
Windows 10 Pro, 
Download any source ZIP from 8.2.0, including last main on Github.

**Anything else we need to know?**:

**Environment**:
- Grafana version: From 8.2.0
- Go 1.17.2
- Node.js LTS

**Comment by tecmatia-dp** [comment]
The problem I have found analyzing differences between the "makefile" in version 8.1.x and 8.2.x, is that it is necessary to run a previous command to dinamically generate go files:
`gen-go: $(WIRE)`
`@echo "generate go files"`
`$(WIRE) gen -tags $(WIRE_TAGS) ./pkg/server`

In Windows it is not easy to install Wire and run the "Make" natively. Finally I could solve with some workaround, and then built Grafana, but I think a solution is needed to be able to build on Windows "out of the box". I am not expert in Go programming or Linux environments, so I'm sorry I can not contribute a solution.
I wonder if those files are generated in the same way and do not depend on the platform, perhaps they could be included already generated in the source code.

**Comment by marefr** [comment]
@tecmatia-dp we've updated the instructions for building on Windows: https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#building-on-windows

Let us know if that helps

**Comment by tecmatia-dp** [comment]
Thank you @marefr. I will try new procedure ASAP, and give feedback.

**Comment by zuchka** [comment]
@tecmatia-dp how are you finding the new build process on Windows? less pain points now?

**Comment by tecmatia-dp** [comment]
Sorry for delay. Yes, tested and working the new procedure. (my previous workaround was a bit complicated).
Just as an additional clarification, cause the "gen" process is "silent" but takes a long time, it seems to hang... I have canceled a couple of times, but in the end it works, maybe it is a specific performance problem of my virtual machine (on Windows 11).

**Comment by zuchka** [comment]
I'm glad to hear that the new procedure is working better, even if it's still not perfect. I think we can close this issue for now, but if the problem returns or you have more info to add, by all means just add it to this thread and we can reopen the issue 👍

**Comment by tecmatia-dp** [comment]
Ok, Thank you @zuchka
