### ISSUE TITLE
Empty menu bar

### ISSUE THREAD

**Issue by abtpst** [grafana/grafana#4051]
I am pretty new to grafana. I am trying to follow the tutorial on the website but my screen does not look anything like the ones mentioned in the tutorials. I have

[![enter image description here][1]][1]

  [1]: http://i.stack.imgur.com/su4a3.png

so it is completely balnk! there is no option where i can navigate for creating a new dashboard or adding a data source. i want to link grafana to my elasticsearch indices. How do i do that? Am i missing some configuration?

Please help.

**Comment by torkelo** [comment]
http://docs.grafana.org/guides/gettingstarted/

**Comment by abtpst** [comment]
Top header
Let's start with creating a new Dashboard. You can find the new Dashboard link at the bottom of the Dashboard picker. You now have a blank Dashboard.

i do not see any such link!

**Comment by abtpst** [comment]
plus i do not see anything in the side menu. why is the side menu empty? please take a look at the updated image

**Comment by mattttt** [comment]
Hi @abtpst 

Betting there are a couple things going on here. 

1. The Data sources menu item is not appearing, which likely means your account is not an admin. You'll want to log in and the Grafana admin and make sure your user account permissions are set properly. 

2. Once you have proper permissions, the New Dashboard link will appear on the bottom left of the dashboard picker (accessed by Clicking the dashboard name in the top bar - `Home` in your screenshot)

**Comment by gastoneb** [comment]
Just FYI, if you haven't created an organization yet then you won't have admin privileges and you won't be able to set up a new dashboard.

**Comment by SKShah36** [comment]
I have the same problem except that I am able to add the datasource and my user role is admin. I am running the grafana server on an ec2 instance but I don't have a link to create a new dashboard.

I have setup a new organisation as well to check if it works but it doesn't.

**Comment by marefr** [comment]
@SKShah36 what Grafana version?

**Comment by SKShah36** [comment]
It was around version 2 before the update and now it says version:master. I am not sure what it means?

**Comment by marefr** [comment]
@SKShah36 master means you're running Grafana from development build/nightly build. There should be a SHA1 commit there as well - what does that say? If you include a full screen screenshot where version is displayed I can probably see what version you're running, Grafana 2, 3, 4, 5 etc.

Here's from [play.grafana.org](https://play.grafana.org/d/000000012/grafana-play-home?orgId=1) (our demo site) which runs the Grafana v5.3.0-beta3 version:

![image](https://user-images.githubusercontent.com/1668778/46596533-3d4f7200-cadd-11e8-9ebd-f35d3261a3e9.png)
