### ISSUE TITLE
Set default organization for new users

### ISSUE THREAD

**Issue by vilory** [grafana/grafana#4052]
Would be nice to set default organization (different to id 1) to newly created users

maybe changing _auto_assign_org_ property from boolean to the id number?

Thanks

**Comment by torkelo** [comment]
auto_assign_org is mainly there for single org installations.

**Comment by vilory** [comment]
The purpose of this request is avoiding an admin to asign view right to an organization different than id 1.

mentioning auto_assign_org was just a suggestion.
