### ISSUE TITLE
Using template variables with CloudWatch on grafana v2.6.0

### ISSUE THREAD

**Issue by rcjim** [grafana/grafana#4053]
I am using grafana v 2.6.0-1 on a centos 6 box.  I am attempting to use a template variable with a cloudwatch query, but the legend is showing the template variable instead of the template variable value.

The setup is as follows:
- Defined template variable rdsinstance with the query "dimension_values(us-west-2,AWS/RDS,CPUUtilization,DBInstanceIdentifier)"
- Graph metrics defined as
-- Metric set to us-west-2, AWS/RDS, CPUUtilization, Stats = Average
-- Dimensions set to "DBInstanceIdentifier = $rdsinstance"
-- Alias set to  "{{region}} {{DBInstanceIdentifier}}: CPU"

On the generated graph, the legend is shown as "us-west-2 $rdsinstance: CPU".  So, what did I miss in my setup in that $rdsinstance is shown instead of the value of $rdsinstance?

Thanks,
Jim

**Comment by mtanda** [comment]
Thanks for reporting :-)
It is bug of datasource plugin.
I open PR to fix the bug.

**Comment by bergquist** [comment]
I added wrong issue id in the commit :)

**Comment by crazygit** [comment]
@rcjim have you get a solution to fix this, I met the same issue
