### ISSUE TITLE
unsigned plugin cannot be used if Grafana is listening on port 80

### ISSUE THREAD

**Issue by itayB** [grafana/grafana#40546]
**What happened**: unsigned plugin cannot be run/tested if Grafana is configured to listen on port 80

**What you expected to happen**: should allow using port 80 with an unsigned plugin (it works with other ports)

**How to reproduce it (as minimally and precisely as possible)**:
Try to run your own private or unsigned plugin.
set the following environment variables:
```
GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=<plugin_id>
GF_SERVER_HTTP_PORT=80
```
try to sign your plugin by running the following command:
```
yarn sign --rootUrls http://localhost:3000,http://localhost:80
```
and you'll get the following log:
```
t=2021-10-15T09:09:28+0000 lvl=warn msg="Could not find root URL that matches running application URL" logger=plugins plugin=itay-s3-datasource appUrl=http://localhost:80/ rootUrls="[http://localhost:3000/ http://localhost/]"
```
and Grafana won't let you use the data source:
![image](https://user-images.githubusercontent.com/457191/137583466-ff03b2da-4af4-49a5-8ef6-353fa320042c.png)

note that the second `rootURL` was changed and someone omitted its port - `http://localhost:80` --> `http://localhost/`.
**Anything else we need to know?**:
same scenrio works if you'll change `GF_SERVER_HTTP_PORT=80` --> `GF_SERVER_HTTP_PORT=3000`

**Environment**:
- Grafana version: v8.1.3 
- Data source type & version: customized data-source, built with plugin-datasource: https://github.com/org-insights/aws-s-3
- OS Grafana is installed on: official docker image `grafana/grafana:8.1.3`
- User OS & Browser: MacOS Big Sur 11.6, Chrome 94.0.4606.81
- Grafana plugins: https://github.com/org-insights/aws-s-3
- Others:

**Comment by tolzhabayev** [comment]
I cannot really reproduce it locally. I can sign without any issues using both:
`GF_SERVER_HTTP_PORT=80` and `GF_SERVER_HTTP_PORT=3000`

Could you try:
`yarn sign --rootUrls http://localhost:3000,http://localhost:80,http://localhost` ?
