### ISSUE TITLE
Support for more aggregations in Table Panel transformer

### ISSUE THREAD

**Issue by droidnxs** [grafana/grafana#4059]
The table panel currently (Grafana 2.6) supports Avg,Min,Max,Total,Current,Count. It would be handy to have other transform options such as Standard deviation, and nthPercentile.

![table-transforms](https://cloud.githubusercontent.com/assets/12829882/13108027/a5b84aea-d596-11e5-9f78-26874d468920.png)

**Comment by torkelo** [comment]
Those are better done in the time series database, graphite already has functions that does standard dev and percentiles, influxdb I think as a stddev function and elasticsearch also has both

**Comment by droidnxs** [comment]
I'm not sure if I was clear. What I'm looking for is a way to summarize a metric in Grafana. If I were to apply timeseries aggregation at the database, I would still be unable to transform it into a column in the table like this:
![table-transforms2](https://cloud.githubusercontent.com/assets/12829882/13109203/ec193a56-d59d-11e5-8184-87cdd5aa07a5.png)

**Comment by torkelo** [comment]
Time series summaries are best done in the time series database  ,  the table above can be very inaccurate  (showing min and max and avg calculated by grafana after the time series database performs aggregation)

Much better to do a query that returns the max and the min , or the percentiles

**Comment by droidnxs** [comment]
That way the problem is that, if I apply an aggregated (graphite) query the table panel doesn't summarize it, rather displays it as timeseries rows :(. Is there any way around this?:
![table-transforms3](https://cloud.githubusercontent.com/assets/12829882/13110509/874d0e0a-d5a6-11e5-95ae-48a5b0e9ceff.png)

**Comment by torkelo** [comment]
graphite does not currently support doing "series summary" metrics (that return min/max/percentiles) for a time range, elastic search does though http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=6&fullscreen&edit

**Comment by torkelo** [comment]
@droidnxs the problem is that for a table like yours to be accurate it needs to be done in graphite (or multiple queries that all return single aggregated value)

**Comment by droidnxs** [comment]
As a matter of fact, I did a comparison of manual (spreadsheet) aggregation vs tabular aggregation in grafana (+graphite) towards a sample time series and they seemed to be on point. ES is a very good option but we're already up and running with our systems' metrics pointed towards a hosted graphite setup.
