### ISSUE TITLE
new install of grafana 8.2.1 cannot connect to influxdb 2.0

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#40602]
**What happened**: Installed grafana 8.2.1 and tried to connect it to influxdb 2.0. Failed.

**What you expected to happen**: for the procedure to connect to influxdb 2.0 to work

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps here to connect to influxdb2.0 do not work because the configuration page for influxdb has been changed:
https://docs.influxdata.com/influxdb/v2.0/tools/grafana/

The above URL for influxdb is pointed to by:
https://grafana.com/docs/grafana/latest/getting-started/getting-started-influxdb/

**Anything else we need to know?**:
The new configuration page for influxdb does not work - because, e.g., the token line is missing.

What version do I need to downgrade to for the installation procedure to match the documentation?

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: influxdb 2.0

**Comment by yellowpattern** [comment]
I wouldn't worry about using the flux langauge interface as there is no structured query builder like there is with influxql, rather you need to write the flux query yourself, from scratch.

**Comment by gabor** [comment]
> @vdejager How did you succeed then with flux. Did you add custom headers

hi @RobertWi , i assume you are using InfluxDB 2.x or Cloud. in that case there is no need for custom headers, simply fill out these fields:
- URL (it is at the top in the HTTP section)
- Organization (it is in the "InfluxDB details section")
- Token (it is in the "InfluxDB details section")

and it should work. basically, the documentation at https://docs.influxdata.com/influxdb/v2.0/tools/grafana/#configure-grafana-to-use-flux works, except the fields that need to be filled out are not "togehter" in the same section. 

(i know this is confusing, we should improve this)

**Comment by gabor** [comment]
@yellowpattern thanks for reporting the issue. i agree there is room for improvement with the influxdb configuration page, we should do that.

in general i recommend the documentation at https://docs.influxdata.com/influxdb/v2.0/tools/grafana/ , it does have all the info you need, except the screenshot does not match exactly what is there today (the URL field is not in the `InfluxDB details` section, but at the top of the page instead). but, except that part, the info there is correct, and should allow you to setup the connection.

**Comment by gabor** [comment]
as the author was able to setup the connection, i am closing this issue.

(i agree that the config-page needs improvements, but that's best handled separately).

if anyone here still has problems connecting to influxdb, please create a new github issue, so that things are not mixed together, and make sure to mention two things:
- the version of your influxdb database (1.x, 2.x, cloud)
- are you tying to create an InfluxQL or a Flux connection.
