### ISSUE TITLE
"Drop here" area only shows on first line of row

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#4060]
(Please forgive the ASCII art,  easier than taking screenshots of this)

Consider a row that has two panels that do not fill the entire width:
```
[ panel ][ panel ][empty space]
```
If we grab a panel, a "Drop here" area appears that allows insertion of the panel:
```
[ panel ][ panel ][ drop here ]
```

Now consider a row that spans multiple lines, but ends with two panels that do not fill the entire width:
```
[    panel    ][    panel     ]
[ panel ][ panel ][empty space]
```
If we grab a panel, no "Drop here" area appears in the empty space.

The use case of a row with multiple lines (a multi-row row?) is not so obvious, but I find myself sometimes creating Dashboards that have them. This can make reordering panels a pain.

**Comment by torkelo** [comment]
Row should not span multiple "rows" , a row should only include panels that fit on a single line  (row)

**Comment by torkelo** [comment]
But I agree that his can be a pain, want to improve the dashboard grid/panel layout system in a future version of Grafana
