### ISSUE TITLE
Using an AverageSeries() with Stacking will Display an invalid series

### ISSUE THREAD

**Issue by Herkum** [grafana/grafana#4061]
If you look at this Graph and look at **Check Latency** you will see the values for the metric are 2.5~ seconds or so, but according the Y-Axis grid the values are in the 11 second range.

https://snapshot.raintank.io/dashboard/snapshot/v9537akWkcETUZNAyBcJLt087c6r9sdb

The metric used to generate **Check Latency** is this,
alias(averageSeries(core.*.monitoring-nagios4.prd.{nagios101_sj2_vclk_net,nagios102_sj2_vclk_net,nagios101_dc6_vclk_net}.curl.nagios.active_*_check_latency.nagios), 'Check Latency')

The reason for the major offset is that "Stacking" is on by default for the graph. It appears that Grafana is stacking all the metrics and using that to configure the legend rather than the averageSeries() values.  If I go and disable stacking under display styles for the **Check Latency** then Y-Axis is calculated correctly.

**Comment by torkelo** [comment]
you have stacking enabled for all series, you need to disable stacking Check Latency  (or put it in another stack group), you can do this in the display styles tab using a series override

**Comment by Herkum** [comment]
Yes, I understand your workaround.
How about this, metrics using certain Graphite functions (like averageSeries, or sumSeries) should have stacking disabled automatically.
 

    On Wednesday, February 17, 2016 8:42 AM, Torkel Ödegaard <notifications@github.com> wrote:
 

 Closed #4061.—

**Comment by torkelo** [comment]
eh why????

**Comment by torkelo** [comment]
averageSeries has nothing to do about if you want to stack a series, it combines a set of series to one series, but you can have multiple queries that use averageSeries :)

**Comment by Herkum** [comment]
If you have multiple series that you are aggregating why would you ever display a that stacked?
For example, if I wanted the average of these values (1,2,3) would you display 6 (the sum) or 2 (the average)?
Steve K 

    On Wednesday, February 17, 2016 9:37 AM, Torkel Ödegaard <notifications@github.com> wrote:
 

 eh why????—
