### ISSUE TITLE
Possible error in implementation of inline script support for Elasticsearch

### ISSUE THREAD

**Issue by wbedard** [grafana/grafana#4062]
This issue is just a placeholder to ensure visibility.  I put the meat of the problem as a comment in the original implementation thread (see below):
https://github.com/grafana/grafana/issues/3500#issuecomment-185255398

**Comment by torkelo** [comment]
It is working here and is using the correct query json according to the docs
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

Are you running Elastic 2.2?  have you enabled scripting in elasticsearch.yml?

**Comment by XciD** [comment]
I reopen this thread.

I'm facing the same issue with ES 1.7.x

This request works : 
``` 
"avg": {
        "field": "value",
        "script": "(_value)*4"
      }
```

But the one generated by Grafana isn't.

```
"avg":
{
       "field":"value",
       "script":   {"inline":"_value*4"}
}
```

**Comment by torkelo** [comment]
Grafana's query looks correct according to the docs 
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-scripting.html

**Comment by warroyo** [comment]
I am seeing behavior in grafana 3.0.1 . I receive a parse error whenever I add a script. Also running ES 1.x

**Comment by jisaitua** [comment]
I was having the same problem using ES 2.4.0, but after reading  [https://github.com/grafana/grafana/issues/4062#issuecomment-190144460](https://github.com/grafana/grafana/issues/4062#issuecomment-190144460) I enabled scripting in ES and it worked as expected.
Maybe a question mark in "Scripts" with a little warning about enabling scripting in ES would be useful.
