### ISSUE TITLE
Cloudwatch error: query timed out after 5 attempts

### ISSUE THREAD

**Issue by roterstein** [grafana/grafana#40632]
**What happened**:
Datasource : Cloudwatch
error: query timed out after 5 attempts

Note: Research has shown that this issue should have been fixed in higher grafana releases.
Apparently this is not the case. Current workaround is to use the 8.1.5 release which implies security issues.

**What you expected to happen**:
Query timeout does not appear and correct results are shown in grafana.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana 8.2.1:
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Red Hat Enterprise Linux 7
- User OS & Browser: MS Windows 10 Google Chrome, Mozilla firefox
- Grafana plugins: N/A
- Others
For more detailed information please see screenshots.
Thanks in Advance.
![2021-10-19 15_16_34-Window](https://user-images.githubusercontent.com/55058719/137923019-5dc655fa-6aa6-40b8-b7ea-d9d3c56a7372.png)
![2021-10-19 14_59_29-](https://user-images.githubusercontent.com/55058719/137923039-ab41afc8-d9fb-4100-a987-31e15aa7f570.png)
:

**Comment by zuchka** [comment]
@roterstein Are you still encountering this error? I am going to close this issue for now. If you're still blocked, please provide the additional details requested above and we'll be happy to reopen 👍 🙏
