### ISSUE TITLE
UX Bug: Clicking Duplicate on Edit page of a panel

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4064]
When I click "Duplicate" button from the panel menu, I see my Edit page as follows:

![screen shot 2016-02-17 at 7 35 17 pm](https://cloud.githubusercontent.com/assets/1019609/13133170/db26c028-d5ad-11e5-8402-0dadf83d786f.png)

You can see there is an extra panel down there below the queryCtrl.

Ideally, if we are in Edit mode, we can remove the "duplicate" option from the menu if possible.

**Comment by bergquist** [comment]
Removed the duplicate option in fullscreen mode. Thanks for reporting! :)
