### ISSUE TITLE
Enable alerting UI and backend to be read-only

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#40647]
This might depend on https://github.com/grafana/grafana/issues/36153

**Comment by gburton1** [comment]
@armandgrillet Does this look like a committed direction that Unified Alerting will take in 9.0? We manage provisioning of alert rules in various AlertManagers using other automated mechanisms outside of Grafana, but we do like the readonly visualization of live rules across all data sources that the new Unified Alerting UI is providing. We just don't want to present our users a lot of edit/create functionality that will clash with our existing provisioning.

**Comment by armandgrillet** [comment]
@JohnnyQQQQ @gillesdemey Is this epic still accurate? We already block edits if the provenance indicates API / File / etc.

**Comment by gillesdemey** [comment]
This one is pretty outdated, as long as the provisioning API is used (either via HTTP or file soon) it will mark the resource with a provenance and block the user from making edits.

Closing this one.
