### ISSUE TITLE
State timeline value mapping no longer shows error state since 8.2.0

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#40661]
**What happened**:

The state timeline no longer shows my "error state" within the state timeline panel. It now shows a single contiguous "< -∞" state which is quite confusing???

![image](https://user-images.githubusercontent.com/46142/138000699-a5d1a702-9865-4a5f-8693-190e0e8b97e2.png)

I have it set up with the value mappings 0 = Red/Down, 1 = Green/"zero-width-string"

![image](https://user-images.githubusercontent.com/46142/137999957-004913c2-7d34-4a76-a634-02bca69ba781.png)

This regressed during the 8.2.0 release where it was showing "<80", and has recently started showing the infinity symbol instead.

**What you expected to happen**:

There was 1 minute of down from 23:29 - 23:30 which I would expect it to show up as a red "Down" block. This is what it looked like in Grafana 8.1.7

![image](https://user-images.githubusercontent.com/46142/138001150-0ed7d17c-7719-4696-8a62-064ff74b4776.png)

**How to reproduce it (as minimally and precisely as possible)**:

 - Prometheus `up` query for a single job
 - Use State timeline panel with value mappings:
    -  0 -> Down [Red]
    - 1 -> Up [Green]

**Anything else we need to know?**:

I've checked for some issues and it seems a little bit related to perhaps to https://github.com/grafana/grafana/issues/40115, but https://github.com/grafana/grafana/pull/40371 was merged in and the issue still happens.

**Environment**:
- Grafana version :v8.3.0-38205pre (6ec2c54c5)
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 11, Chrome

**Comment by joshhunt** [comment]
Here's the panel JSON if it's helpful :) https://gist.github.com/joshhunt/773330e6099c1f584e5116207f30116d

**Comment by ryantxu** [comment]
@joshhunt I see -- the color mode is set to thresholds:
![image](https://user-images.githubusercontent.com/705951/138002565-8fbe7a44-fd15-4462-9be5-050b200ddf67.png)


If you change that to anything else, it will use the value coloring.   hymmm -- not sure what the best path forward is

**Comment by esjay90** [comment]
I tried the work around from @Mario-Hofstaetter, but then the merge function is not working according my value mappings. I expect that I get merged block, which are following the value mappings.

**Comment by melroy89** [comment]
Still an issue after 3 years!
