### ISSUE TITLE
Toolkit: Wrong publicPath used for plugin files

### ISSUE THREAD

**Issue by ZuperZee** [grafana/grafana#40671]
**What happened**:

When using dynamic imports the code tries to retrieve the file from the base.
![image](https://user-images.githubusercontent.com/39485579/138051449-43b15744-9785-4648-b0b7-7fbeff3f662e.png)

**What you expected to happen**:

The code should retrieve the code from the plugin path.

**How to reproduce it (as minimally and precisely as possible)**:

Create a plugin.
Create a file to import

test.ts

```ts
export default "test"
```

import the file

panel.ts

```ts
...
      import('./test').then(({ default: test }) => {
        console.log(test);
      });
...
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.2.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ZuperZee** [comment]
https://github.com/grafana/grafana/blob/82bae892eb030ea80428d0e4c271afaf59ad4539/packages/grafana-toolkit/src/config/webpack.plugin.config.ts#L168

should be
```ts
publicPath: `public/plugins/${getPluginId()}`,
```

There could be some problems if some plugins based the code that it loads code from the base.

**Comment by ZuperZee** [comment]
A workaround is to create a webpack.config.js with the changes

webpack.config.js
```ts
module.exports.getWebpackConfig = (config, options) => ({
  ...config,
  output: {
    ...config.output,
    publicPath: 'public/plugins/plugin-id/',
  },
});
```

The plugin id is the id written in the plugin.json file.

**Comment by mckn** [comment]
You are correct! However we are a bit hesitant to introduce this into the `grafana-toolkit` since it might have a negative impact on older angular plugins that are using the "legacy imports".

I will add this to the documentation about how to dynamically import modules in your plugin.
