### ISSUE TITLE
How to make correct vertical scale? (using custom JSON datasource)

### ISSUE THREAD

**Issue by tral** [grafana/grafana#4067]
Hello, I got the following situation:
http://dn.imagy.me/201602/18/2af0c9a822df45baffd1ef44de8fb92e.png
As you can see, lines don't fill all available vertical space.
We want it to looks like that: http://dn.imagy.me/201602/18/211924e91775d28edbcd4d1741b9d471.png
How can I achieve this? 
We're using this custom datasource: https://github.com/grafana/datasource-plugin-genericdatasource

**Comment by deepujain** [comment]
Tangential question. How did you make grafana support "Non English" labels ? 

Does it support i18n (l10n), if so what languages and how can i test this feature ?

**Comment by tral** [comment]
deepujain, i did not do anything to make Russian (cyrillic) labels work. It was working out of the box. I just specify Russian metrics names in my datasources and it works

**Comment by tral** [comment]
Guys? Any ideas?

**Comment by torkelo** [comment]
no idea, the auto y axis scale works here, strange, maybe something with the data? Try enabling points to see if there are any stray single points disconnected from the main series, could be causing something  like this

**Comment by tral** [comment]
we noticed that with other datasources scaling is correct...

**Comment by tral** [comment]
can this plugin influence on scaling?

**Comment by tral** [comment]
as you can see: no discsonnected single points:
http://dn.imagy.me/201603/02/e6c457928e87d5a9eaa5049f9d2d05a2.png

**Comment by tral** [comment]
answer is here https://github.com/grafana/grafana/issues/4560
