### ISSUE TITLE
Prometheus: Exemplars break alerting

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#40683]
**What happened**:

Recently my alerts on Grafana Cloud have regressed and firing incorrectly due to "NoData". I think this is because of the recent addition of exemplars for Prometheus for existing queries which add an extra data frame to the results, which confuses alerting.

My queries seemed to have gotten exemplars at the same time my instance got Unified Alerting, so I'm not 100% sure of the issue, but I think it's due to exemplars being turned on for existing queries.

**What you expected to happen**:

My alerts don't break!

**How to reproduce it (as minimally and precisely as possible)**:

 - In Grafana 8.1 set up an alert with prometheus + time series panel.
    - query: `up{job="destiny_stats"}`
    - alert condition: when last() of A is below 1
  - Observe that the alert works and does not have "NoData"
  - Upgrade to latest main and enable AlertsNG
  - Observe that the alert now has an additional data frame, and the alert has the state of "NoData" and no longer fires when `up` reports < 1

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.0-38205pre (6ec2c54c5)
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Windows 11, Chrome

**Comment by ivanahuckova** [comment]
@joshhunt could you please test again if you are experiencing this issue? I tried to reproduce, but all worked as expected. Moreover, it is impossible to remove exemplars button from alerting as we are using the same query editor, and editor doesn't know if it is in `panel-edit` or in `alerting`. I checked with alerting squad and they confirmed that there is no way to know this.

**Comment by joshhunt** [comment]
Checking this again, and my grafana cloud instance seems to have been downgraded back to old alerting, so I cannot fully test, but it looks like the empty exemplars series is no longer being added, so I think this is all good now 👍🏻
