### ISSUE TITLE
Add feature flags for features

### ISSUE THREAD

**Issue by CVTJNII** [grafana/grafana#4069]
I'm currently running Grafana in a 3 node cluster.  For simplicity I'm not using a shared database backend as I do not want to have to run a DB cluster under the Grafana cluster as I only want dashboards, instead I have Chef to set up to make sure all the dashboards are present and in sync.

With a rebuild using commit: v2.6.0+825-gffc9a83 I see several new features were added: pins, playlists, and snapshots.  Due to how our environment is set up at least some of these features are broken.  As such I'd like to not show them in the Grafana menu to avoid confusing users.

It would be nice for new features like this to have a feature toggle to disable them.  That way users like myself can keep up to date with the latest Grafana code while disabling features which are unwanted or known broken.  Thanks.

**Comment by torkelo** [comment]
if you run multiple grafana servers you should use mysql or postgres as grafana's database

**Comment by CVTJNII** [comment]
It would still be nice to control which features are released into production for a given environment.  Not everyone agrees on whether a feature is useful or desirable.
