### ISSUE TITLE
Tempo: search API is changing, adapt Grafana to use tags query parameter

### ISSUE THREAD

**Issue by kvrhdn** [grafana/grafana#40708]
The Tempo search API is slightly changing. See https://github.com/grafana/tempo/pull/1055 and https://github.com/grafana/tempo/pull/1062.
The changes will be backwards-compatible, so the existing Grafana implementation will continue to work, but we want to gradually phase out support for the original API.

**Before**: the original API allows you to specify tags as separate query parameters. For example if you search for traces with the tags `service.name=foo` and `http.url=api/search` you would query Tempo like this:

```
/api/search?service.name=foo&http.url=api/search
```

Disadvantage of this is that you can't query tags that clash with reserved keywords (`minDuration`, `maxDuration` and `limit`).

**After**: the new API puts all tags inside a `tags` query parameter. They have to be specified as `key=value` pairs, separated by spaces.
So to query Tempo with the new API:

```
/api/search?tags=service.name%3Dfoo%20http.url%3Dapi%2Fsearch
```

In which `service.name%3Dfoo%20http.url%3Dapi%2Fsearch` is URL encoding for `service.name=foo http.url=api/search`.

If a tag value contains a space, it should be wrapped in double quotes, i.e. `service.name="my service"`

Example using curl: https://github.com/kvrhdn/tempo/blob/search-api-isolate-tags-docs/docs/tempo/website/api_docs/_index.md#example

---

While developing the new API I did some tests with Grafana. I pushed my hacky implementation here: https://github.com/kvrhdn/grafana/commit/e1d5d95cb9595cd6558c1bba28647fa27ee51b0b

We can simplify the implementation a little bit by not parsing the tags field anymore but simply passing it as a string to Tempo. The syntax of the tags field in Grafana now matches what Tempo accepts in the `tags` query parameter.
This will ensure error messages from Tempo are more sensical as we have an error message that indicates the position of a bad token. For example _invalid tags: unexpected '=' at pos 18_.

But I'm obviously not a Grafana developer so take this with a grain of salt 🤣

**Comment by joe-elliott** [comment]
As part of this work we should also have Grafana start passing `start=` and `end=` based on the selected time range. start and end are unix epoch seconds.

This needs to be merged on the Tempo side to ignore other params if `tags=` is passed: https://github.com/grafana/tempo/pull/1119

**Comment by aocenas** [comment]
Is there any deadline when we need to support this? I assume as native search is still behind feature flag we have some buffer around this right?

**Comment by joe-elliott** [comment]
The reason we need it sooner rather than later is because it allows us to make changes on the backend api. Once this change rolls out and hosted Grafana starts sending `tags=` then we can adjust the backend API to start accepting other parameters.

The way tags are encoded into the url now we can't add additional parameters to our API without this change.
