### ISSUE TITLE
Export dashboard function not working properly with Safari on OS X

### ISSUE THREAD

**Issue by Styx13** [grafana/grafana#4070]
Hi,

On Safari, the Export function which allows you to download a Dashboard definition, does not work properly. Instead of offering a file to download, it just open a new tab that's empty.

Tested with both OS X 10.10 (Yosemite) and OS X 10.11 (El Capitan) with Safari 9.0.3.

BTW, I noticed on OS X that Grafana runs a lot better (faster and stable) on Safari compared to firefox (especially when you start looking at graphs with a good amount of datapoints). Which is why I use Safari with Grafana most of the time.

**Comment by utkarshcmu** [comment]
+1 Easily reproducible bug.

**Comment by torkelo** [comment]
This is a safari bug that is existed for years and is still not solved
