### ISSUE TITLE
Unified Alerting: Slack notification validation for recipient is too restrictive

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#40709]
**What happened**:
Slack notifier configuration in legacy alerting accepts almost any string in the field recipient. The Slack notifier in unified alerting has much more strict requirements according to the 
https://github.com/grafana/grafana/blob/722c414fef32a02ebb7dbe2458a494eba2bedd2c/pkg/services/ngalert/notifier/channels/slack.go#L46
Therefore, after migration to the unified alerting the Alertmanager will fail to start if the recipient does not match the more restrictive regex. 
In Alertmanager's slack configuration the field recipient can be any string https://prometheus.io/docs/alerting/latest/configuration/#slack_config

**What you expected to happen**:
Slack configuration in unified alerting should accept any string in the field recipient. Ideally, we should find the documentation in Slack API for a valid recipient string and follow it.

**How to reproduce it (as minimally and precisely as possible)**:
- Start Grafana with ngalert flag disabled
- Configure an alert rule and a Slack notification. Specify a channel name without `#`. Test the config. It should deliver a test message.
- enable ngalert flag and restart Grafana
- check logs and see that Alertmanager fails to start 
```
msg="Could not create notifier" logger=alerting.notifier notifier=000000002 error="alert validation error: recipient on invalid format: \"...\""
```
**Environment**:
- Grafana version: 8.2.1

**Comment by gotjosh** [comment]
Great find @yuri-tceretian! I think we should def fix the regex to make sure we're compliant with whatever Slack accepts, there might be more cases that we need to support.
