### ISSUE TITLE
Query not resolved to UI like query in Metrics tab of Graph panel

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4071]
![screen shot 2016-02-18 at 4 06 50 pm](https://cloud.githubusercontent.com/assets/406777/13162433/c3333800-d659-11e5-8ff6-a103088e18dc.png)

The above SQL query did not resolve into its equivalent UI type as shown below.
![screen shot 2016-02-18 at 4 06 57 pm](https://cloud.githubusercontent.com/assets/406777/13162434/c346cdc0-d659-11e5-9a54-34375fb1e34e.png)

Quite a lot of fields are missing and that spoils the graph upon save,

**Comment by torkelo** [comment]
There is no InfluxDB query parser in Grafana that can translate the ext query into the UI editor model , the feature your missing has to be implemented :(
