### ISSUE TITLE
explore: rich history: invalid localStorage entry breaks the page

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#40713]
in explore, if the rich-history localstorage entry gets broken, it causes the page to crash with no way to fix it.

how to reproduce:

1. go to expore-mode
2. open the browser's devtools, go to edit localstorage entries:
      a. find the entry with key `grafana.explore.richHistory`
      b. set it's value to `{}`
3. modify the URL in the browser so that it only contains the `/explore` part, so no query-string with a previously used query.
3. reload the page by pressing [enter]

the page will crash with an error and refreshing the page does not fix the problem.

**Comment by ifrost** [comment]
We are moving to remote storage where this should not be a problem and hence it's very low priority we won't fix it before.
