### ISSUE TITLE
grafana-toolkit node-sass build error: ‘remove_cv_t’ is not a member of ‘std’;

### ISSUE THREAD

**Issue by akira-kurogane** [grafana/grafana#40764]
**What happened**:
"yarn install" build of a fresh plugin created with grafana-toolkit 7.3.7 fails during node-sass build.

**How to reproduce it (as minimally and precisely as possible)**:

Following per instructions at https://grafana.com/tutorials/build-a-panel-plugin/ :

```
npx @grafana/toolkit plugin:create my-plugin
cd my-plugin
yarn install
```
Fails during the build of node-sass with the error shown below regarding unknown C++ template "remove_cv_t":

```
  g++ '-DNODE_GYP_MODULE_NAME=binding' '-DUSING_UV_SHARED=1' '-DUSING_V8_SHARED=1' '-DV8_DEPRECATION_WARNINGS=1' '-DV8_DEPRECATION_WARNINGS' '-DV8_IMMINENT_DEPRECATION_WARNINGS' '-D_GLIBCXX_USE_CXX11_ABI=1' '-D_LARGEFILE_SOURCE' '-D_FILE_OFFSET_BITS=64' '-D__STDC_FORMAT_MACROS' '-DOPENSSL_NO_PINSHARED' '-DOPENSSL_THREADS' '-DBUILDING_NODE_EXTENSION' -I/home/akira/.node-gyp/16.12.0/include/node -I/home/akira/.node-gyp/16.12.0/src -I/home/akira/.node-gyp/16.12.0/deps/openssl/config -I/home/akira/.node-gyp/16.12.0/deps/openssl/openssl/include -I/home/akira/.node-gyp/16.12.0/deps/uv/include -I/home/akira/.node-gyp/16.12.0/deps/zlib -I/home/akira/.node-gyp/16.12.0/deps/v8/include -I../../nan -I../src/libsass/include  -fPIC -pthread -Wall -Wextra -Wno-unused-parameter -m64 -O3 -fno-omit-frame-pointer -fno-rtti -fno-exceptions -std=gnu++14 -std=c++0x -MMD -MF ./Release/.deps/Release/obj.target/binding/src/binding.o.d.raw   -c -o Release/obj.target/binding/src/binding.o ../src/binding.cpp
In file included from /home/akira/.node-gyp/16.12.0/include/node/v8.h:30,
                 from /home/akira/.node-gyp/16.12.0/include/node/node.h:63,
                 from ../../nan/nan.h:56,
                 from ../src/binding.cpp:1:
/home/akira/.node-gyp/16.12.0/include/node/v8-internal.h: In function ‘void v8::internal::PerformCastCheck(T*)’:
/home/akira/.node-gyp/16.12.0/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
/home/akira/.node-gyp/16.12.0/include/node/v8-internal.h:492:38: error: ‘remove_cv_t’ is not a member of ‘std’; did you mean ‘remove_cv’?
  492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                      ^~~~~~~~~~~
      |                                      remove_cv
/home/akira/.node-gyp/16.12.0/include/node/v8-internal.h:492:50: error: template argument 2 is invalid
  492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                                  ^
/home/akira/.node-gyp/16.12.0/include/node/v8-internal.h:492:63: error: ‘::Perform’ has not been declared
  492 |             !std::is_same<Data, std::remove_cv_t<T>>::value>::Perform(data);
      |                                                               ^~~~~~~
...
...
...
...
make: Leaving directory '/var/lib/grafana/plugins/sparkline-stack/node_modules/node-sass/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/var/lib/grafana/plugins/sparkline-stack/node_modules/node-gyp/lib/build.js:262:23)
{
  "author": "Grafana Labs",
  "license": "Apache-2.0",
  "name": "@grafana/toolkit",
  "version": "7.3.7",
  "description": "Grafana Toolkit",
  "keywords": [
    "grafana",
    "cli",
    "plugins",
    "typescript"
  ],
  "repository": {
    "type": "git",
    "url": "http://github.com/grafana/grafana.git",
    "directory": "packages/grafana-toolkit"
  },
  "bin": {
    "grafana-toolkit": "./bin/grafana-toolkit.js"
  },
  "scripts": {
    "build": "grafana-toolkit toolkit:build",
    "clean": "rimraf ./dist ./compiled",
    "precommit": "npm run lint & npm run typecheck",
    "typecheck": "tsc --noEmit"
  },
  "main": "src/index.ts",
  "dependencies": {
    "@babel/core": "7.9.0",
    "@babel/preset-env": "7.9.0",
gyp ERR! stack     at ChildProcess.emit (node:events:390:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:290:12)
gyp ERR! System Linux 5.11.0-37-generic
gyp ERR! command "/usr/bin/node" "/var/lib/grafana/plugins/sparkline-stack/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /var/lib/grafana/plugins/sparkline-stack/node_modules/node-sass
gyp ERR! node -v v16.12.0
gyp ERR! node-gyp -v v3.8.0
```

**Anything else we need to know?**:

**Environment**:
- Grafana-toolkit 7.3.7
- OS Grafana is installed on: Ubuntu 21.04
- npm version: 8.1.0
- yarn version: 1.22.17
- Grafana version: 8.2.1

**Comment by akira-kurogane** [comment]
Attachment of the entire "yarn install" output.
[yarn.install.log](https://github.com/grafana/grafana/files/7393385/yarn.install.log)

**Comment by akira-kurogane** [comment]
After deleting the plugin directory and running `npx @grafana/toolkit plugin:create sparkline-stack` a couple of times again I end up with the same result. This applies whether I've do it `sudo -u grafana` or as my normal shell user.

package.json specifies "latest" for the toolkit dependency. (There's no "dependencies" at this moment, only "devDependencies").
```
{
  .....,
  "license": "Apache-2.0",
  "devDependencies": {
    "@grafana/data": "latest",
    "@grafana/toolkit": "latest",
    "@grafana/ui": "latest",
    "emotion": "10.0.27"
  },
  "engines": {
    "node": ">=14"
  }
}
```

but the yarn.lock that is created at the same moment in the plugin directory has:
```
"@grafana/toolkit@latest":
  version "7.3.7"
  resolved "https://registry.yarnpkg.com/@grafana/toolkit/-/toolkit-7.3.7.tgz#71dd37e8c43d3dea8dfe1e0e929484b7aa3f67df"
  integrity sha512-lQgiR3iRg/d5AaY47GqYLQVUZM4f984+FDB4dVS3/fEeICtKZdpBL52IhZws812g+GBDuNovPs58Pp9tIEIDEw==
  ....
```

If I run `npm view '@grafana/toolkit'` or `yarn info '@grafana/toolkit'` (i.e. as my normal shell user) they both show version 8.2.2.

`sudo -u grafana npm view '@grafana/toolkit'` also shows v8.2.2. I can't run `sudo -u grafana yarn info '@grafana/toolkit'` due to error "Error: EACCES: permission denied, open '/home/<myshellluser>/.yarnrc'".

After running `yarn install` a v7.3.7 version of the package will be saved to the user cache directory (~/.cache/yarn/v6/). This is the only instance of v7.3.7 package I find, but I guess finding the downloaded package is beside the point.

Is it the registry that the npx plugin:create command finds that is the issue? I run out of ideas for debugging at now.

**Comment by andresmgot** [comment]
Hi, I am also hitting this. Since Grafana now requires node 16, the `@grafana/toolkit` does not work anymore, if you try to install it, you get this error. It's because its dependency with node-sass. We need a PR similar to [this](https://github.com/grafana/grafana/pull/28624) @jackw. Right now the `node-sass` dependcy gets resolved to `node-sass "^4.13.1"` and we need something > 6.0.1 (according to [this stackoverflow solution](https://stackoverflow.com/questions/67241196/error-no-template-named-remove-cv-t-in-namespace-std-did-you-mean-remove)).

cc/ @shirleyleu

**Comment by andresmgot** [comment]
wait no, the problem is that when you do `npx @grafana/toolkit plugin:create <plugin>` you end up with an old `yarn.lock` that has an old reference to the toolkit (which has the old reference to node-sass). If you run `yarn upgrade` or `yarn add @grafana/toolkit` it updates the lock file and works so I am not sure how to update that file?

**Comment by jackw** [comment]
@andresmgot what are the `@grafana` package versions  in the `yarn.lock` file you get when first running `npx @grafana/toolkit plugin:create <plugin>`?

I'm still thinking this is some sort of weird caching issue somewhere.

**Comment by jackw** [comment]
Ok, thanks for the pointers @andresmgot . The issue is the lock files in the starter templates. e.g. https://github.com/grafana/grafana-starter-panel/blob/master/yarn.lock

**Comment by andresmgot** [comment]
:+1:  that can be it
