### ISSUE TITLE
Sharing a dashboard with empty graphs results in Unauthorized message

### ISSUE THREAD

**Issue by wamdam** [grafana/grafana#4076]
Version: 2.6.0
When using the function "Snapshot sharing" for a dashboard with graphs with no data (i.e. empty graphs), the shared dashboards seems to try to get /test and /ping for each of these empty graphs.

For logged-in users this results in showing test-data in the shared dashboard:

![bildschirmfoto von 2016-02-19 11-22-00](https://cloud.githubusercontent.com/assets/147094/13172931/05234efc-d6fb-11e5-9500-c4b26578181c.png)

For non-logged in users this results in the Unauthorized message and, when the browser debugger is opened, a lot of status 401 requests.

![bildschirmfoto von 2016-02-19 11-18-37](https://cloud.githubusercontent.com/assets/147094/13172900/dc5de4e6-d6fa-11e5-94d2-7478c80eb1dc.png)

![bildschirmfoto von 2016-02-19 11-18-22](https://cloud.githubusercontent.com/assets/147094/13172903/e1d8530c-d6fa-11e5-989a-307e510de2bc.png)

Both situations are annoying. Logged in users see wrong (i.e. test) data, non-logged in users see the Unauthorized messages.

**Comment by markuspatrick** [comment]
Anny news about the issue? We face the same problem...

**Comment by torkelo** [comment]
this is due to snapshot was not taken properly (queries was too slow to complete)
