### ISSUE TITLE
Grafana vs Elasticsearch templating query for string type with special characters

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4077]
Hi in the templating setup for grafana, with elasticsearch as database, I have a string field and have set it to not_analyzed
I also have the multiple option enabled, and ALL option enabled. The ALL query type is Lucene
So, when querying everything works fine when multiple values are selected or all values are selected
however, the query fails when only one of them is selected
on checking the query, for multiple or all, the generated query is like
client:\"ABC\" OR "\cde\"
but when only one of them is selected, the query is
client:ABC and so without the quotes, the query fails as the client name has special characters like [, etc

**Comment by torkelo** [comment]
this is a known problem for Elasticsearch that requires a big change in the templating system, https://github.com/grafana/grafana/issues/2918
