### ISSUE TITLE
Row height autosizing

### ISSUE THREAD

**Issue by loopping** [grafana/grafana#4078]
Hello,
I'm using 1.9 and I plan to use latest version.
getLegendHeight has changed in order to get Row height autosizing here https://github.com/grafana/grafana/commit/dabdf1b7fd1453b6114b65bdb77fee3404c93eee
I have rows that have bottom legends as table.
![capture1](https://cloud.githubusercontent.com/assets/7744271/13177188/cbcf085e-d717-11e5-9d19-f29817551b50.jpg)

As you can see in this test row, graphs are not aligned
How can I align graphs ?

**Comment by torkelo** [comment]
increase the row height so that it is as high as the highest graph

**Comment by loopping** [comment]
I did set the row height to 700px and I ahve the same result,graphs are not aligned.

![capture1](https://cloud.githubusercontent.com/assets/7744271/13178755/e470b0fc-d720-11e5-8ba1-fa438e1dc2f6.jpg)

**Comment by torkelo** [comment]
Look aligned to me, the graph takes up the 700px space minus the space needed for the lrgend

**Comment by torkelo** [comment]
If you need the graph in the panel to align with other graph in other panels disable the legend or switch it to right side or keep it at one row in non table mode
