### ISSUE TITLE
Yarn: `yarn run check-strict` throws non-descriptive errors

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#40799]
**What happened**:

In build steps that fail on `lint-frontend` steps because of the `yarn run check-strict`, we get messages as:

```
+ yarn run check-strict
Collecting code stats (typescript errors & more)
Typescript strict errors 8 exceeded 6 so failing build
```

Would be nice if the error messages could be more descriptive so we can know which files have to be fixed.

**Comment by Elfo404** [comment]
I think this can probably be closed as we removed that command (no more strict errors 🎉 )
