### ISSUE TITLE
Monoco editor in settings hides suggestions

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#40792]
When using the monoco editor on the text panel, the variable completion is hidden:

`ctrl+space`

![Peek 2021-10-21 23-32](https://user-images.githubusercontent.com/705951/138404548-d8c82765-b267-462b-86c9-202f30734f6c.gif)

**Comment by mckn** [comment]
I spent some time trying to reproduce this one and it seems to be that the "scollable" area that is generated by the "react-split-pane" is causing this behavior.

So I will move this to the user essentials squad.
