### ISSUE TITLE
Inconsistent Request objects from Influx Datasource Panels in 8.0.3. 

### ISSUE THREAD

**Issue by KirannBhavaraju** [grafana/grafana#40798]
**What happened**:
Hey guys. A solid product first of all. We are an IOT company which uses Grafana with influx as the primary candidate for any data visualization..
1. We use a connector which grafana tries to connect to, before reaches influx.
2. We were trying to update from Grafana v7 to v8, because we wanted to use the new streaming capabilities.

**What you expected to happen/ What happens in Grafana v7.4.5**:

- I request a field value from a measurement in influx which has certain tag keys and values.
- Observe when i apply the last `filter`, where i add this `{'tag_key': 'tag_value'}` pair which is `'variable': 'some-value'` I would expect for Grafana/influx plugin to parse the query completely up-until that point with all previous filters included, which happens successfully.
- All the `filters` I applied are translated to an SQL query and the values are fetched.
- This is what is expected to happen.

![image](https://user-images.githubusercontent.com/28805843/138417119-770086b2-9c7e-458a-8aca-9e8e25a6ef1b.png)

**Environment**:
- Grafana version: 7.4.5
- Data source type & version: Influx Core bundled with v7.4.5
- OS Grafana is installed on: Windows 10 - Docker container
- User OS & Browser: Windows 10
- Grafana plugins: - 
- Others: - 

**What happens in Grafana v8.0.3**:
- I do the same thing
- I use the same datasource.
- I proceed to select the last filter value like above, but the query grafana sends to my our connector is skipping an already applied filter.. as shown in the screenshot below.

![image](https://user-images.githubusercontent.com/28805843/138417882-f310a8d8-de79-404e-9bbf-36af2251eb76.png)
 
**Environment**:
- Grafana version: 8.0.3
- Data source type & version: Influx Core bundled with v8.0.3
- OS Grafana is installed on: Ubuntu 20.04.2 LTS
- User OS & Browser: Windows 10
- Grafana plugins: - 
- Others: - 

**How to reproduce it (as minimally and precisely as possible)**:
- Can be reproduced if the version 8.0.3 is used to query any influx data-source with multiple filters.

**Anything else we need to know?**:
- This issue however seems to be fixed in v8.1.5 where the request objects are consistent.

I was not successful in finding any issue in the closed ones too, so any more explanation on this would be very helpful. 
Pardon me if this is documented somewhere, but i didnt find it unfortunately. 
Thanks.

**Comment by gabor** [comment]
hi @KirannBhavaraju @zuchka , this looks like the problem that was fixed by https://github.com/grafana/grafana/pull/36570 in grafana 8.0.6

**Comment by KirannBhavaraju** [comment]
@gabor Thanks for the update.
