### ISSUE TITLE
Cross-Origin Request Blocked

### ISSUE THREAD

**Issue by maximus2situation** [grafana/grafana#4080]
Hi,

I am developing a feature using Grafana to display metrics from several datasources. Because I want to have a single sign in/log in page in my platform, I need to skip the login page. So I use apache as a proxy. The 000-default.conf file in apache looks like

<VirtualHost *:80>
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header always set Access-Control-Max-Age "1000"
Header always set Access-Control-Allow-Headers "X-Requested-With, Content-Type, Origin, Authorization, Accept, Client-Security-Token, Accept-Encoding"

<Proxy *>
        AuthType Basic
        AuthName GrafanaAuthProxy
        AuthBasicProvider file
        AuthUserFile /etc/apache2/grafana_htpasswd
        RewriteEngine On
        RewriteRule .* - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
        RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"
 </Proxy>
</VirtualHost>

And the grafana.ini looks like

[auth.proxy]
enabled = true
header_name = X-WEBAUTH-USER
header_property = username
auto_sign_up = true

When executing a request using angular js to grafana login api I get a CORS :"issue Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://mydomain:3000/login. This can be fixed by moving the resource to the same domain or enabling CORS"

For information this request using the commad line is working:

curl -H "X-WEBAUTH-USER: admin" -X "POST" -d user=admin -d email=admin@localhost -d password="admin" http://mydomain:3000/login

And the user is logged in.

How did I miss ? Thanks in advance

**Comment by torkelo** [comment]
you must be missing some cors header setting in nginx
