### ISSUE TITLE
Playlist: The final ux improvements

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#4082]
![image](https://cloud.githubusercontent.com/assets/618863/13179080/8265b568-d722-11e5-9192-671500088e05.png)

**Comment by mattttt** [comment]
Let's make sure to include the body copy under the header. It's helpful to users to understand the concept.

**Comment by bergquist** [comment]
![image](https://cloud.githubusercontent.com/assets/618863/13215718/bc81793a-d957-11e5-84c3-48b59d206bb7.png)

**Comment by bergquist** [comment]
![image](https://cloud.githubusercontent.com/assets/618863/13215731/da3b4eec-d957-11e5-8914-4a1fb147d629.png)

**Comment by bergquist** [comment]
https://files.slack.com/files-tmb/T02S4RCS0-F0NER5XAR-dbfe778d23/pasted_image_at_2016_02_22_04_30_pm_720.png

**Comment by torkelo** [comment]
ís there anything left on this? Looks good now
