### ISSUE TITLE
Build: Docker build fails due to missing call to gen-go 

### ISSUE THREAD

**Issue by atifali** [grafana/grafana#40839]
**What happened**:
Using the following command to build the backend on Windows fails:
`go run build.go build`

**What you expected to happen**:
Would expect the go backend binary to build.

**How to reproduce it (as minimally and precisely as possible)**:
On windows just run the command by following the procedure here for building on windows: https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md

**Anything else we need to know?**:
This is what the log looks like:
```
$ go run build.go build
Version: 8.3.0, Linux Version: 8.3.0, Package Iteration: 1635031358pre  
building binaries build
building grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/windows-amd64/grafana-server.exe
rm -r ./bin/windows-amd64/grafana-server.exe.md5
go build -ldflags -w -X main.version=8.3.0-pre -X main.commit=f496c31018 -X main.buildstamp=1634921041 -X main.buildBranch=main -buildmode=exe -o ./bin/windows-amd64/grafana-server.exe ./pkg/cmd/grafana-server       
# github.com/grafana/grafana/pkg/cmd/grafana-server/commands
pkg\cmd\grafana-server\commands\cli.go:168:12: undefined: server.Initialize
exit status 2
exit status 1
```

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: Windows 10
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: go version go1.17.2 windows/amd64

**Comment by atifali** [comment]
looks like the `wire_gen.go` file is not being generated as expected by the assumption with the line producing that error

installing wire manually using: `go get -d github.com/google/wire/cmd/wire` and then manually generating using `wire gen ./pkg/server` gives the following error:

```
$ wire gen ./pkg/server/
wire: C:\Projects\grafana\repos\grafana\pkg\server\wire.go:175:13: undeclared name: wireExtsSet
wire: C:\Projects\grafana\repos\grafana\pkg\server\wire.go:180:13: undeclared name: wireExtsTestSet
wire: generate failed
```

seems to be a `gopls` issue since the vars are declared in the file `wireexts_oss.go` - a quick hacky solution was to remove the commented build tags in that file:
```
//go:build wireinject && oss
// +build wireinject,oss
```

and running the `wire gen ./pkg/server` cmd again which generated the expected

any better solutions for this though?

**Comment by edannenberg** [comment]
Same issue on Linux.

**Comment by ygutgutia** [comment]
Facing the same issue on Windows

**Comment by edannenberg** [comment]
Executing `make gen-go`  before building the Go source fixes the issue.

**Comment by ygutgutia** [comment]
> Executing `make gen-go` before building the Go source fixes the issue.

Is there a way to install make without WSL? Using Chocolatey?

**Comment by tejagsp** [comment]
The problem arises from `pkg\cmd\grafana-server\commands\cli.go` # `server.Initialize`.
The `Initialize` is not declared by package `sever`.

There is not func for `Initialize` in `pkg\server\server.go`

P.S.: I am new to Go, this is just my assumption

**Comment by marefr** [comment]
Opened a PR #42390. If anyone can test/verify the instructions works that would be helpful. Thanks
