### ISSUE TITLE
cant combine bars and line with different interval in one time series panel

### ISSUE THREAD

**Issue by IerwinDE** [grafana/grafana#40835]
I described this issue on the forums hoping I was doint something wrong, but i was suggested, this might be a bug.
Forum post is here:
https://community.grafana.com/t/queries-with-different-time-resolution-influencing-eachother/55184/2

I want to display a graph that is based on values for every minute in the same panel as Bars that are based on data that is aggregated in weeks. I was able to create this behavior in the  “Graph (old)” panel but not in timed series.

This is what im trying to get (Graph old);
![old](https://user-images.githubusercontent.com/52814003/138566500-7756b433-81d1-42e1-8dc9-32bdc56f7327.JPG)

This is how it looks in time series with just the bars query enabled:
![bars_only](https://user-images.githubusercontent.com/52814003/138566538-d30faffb-909f-446b-9787-c37d3302e7a8.JPG)

This is what happens when I enable the line query:
![both](https://user-images.githubusercontent.com/52814003/138566552-b23d9c1c-9ed0-441b-bb90-3e0e0f66590b.JPG)

Notice how the bars seem to be squished to the width of the resolution of the line.

**Environment**:
- Grafana version:    8.2.1
- Data source type & version: MySQL
- OS Grafana is installed on: don't know
- User OS & Browser: Windows/Firefox
- Grafana plugins: don't know

Best regards

Ier

**Comment by leeoniya** [comment]
uPlot was updated 3 days ago in https://github.com/grafana/grafana/pull/41663, so this should now work in nightly.

https://grafana.com/grafana/download/nightly?edition=oss

let me know if this is still an issue for you.
