### ISSUE TITLE
Behaivour of height on panel and rows

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#4084]
Hi,
I'm trying to underestand the behaivour of height property of panel and rows and I have seen a strange behaivour on them. Grafana version 2.1.0-pre1:

__PhantomJS rendering__
When you render a panel using render link the graph resizes itself into height passed var. The problem is if you have a height fixed set in the panel, the render image appears with cut legend/graph if the height passed by URL on the render is lower than panel height.
i.e: 
Panel `height = 300px`
Render `&height = 200px` -> The result will be an image with the legend cut

I can't underestand why phantom is taking height panel instead of resizing itself as it does normally. Seting height on the panels should affect only on the dashboards, not the rendering of the panels.

__Panel editing manually (with corners):__
Let me explain with an example: if we have 3 panels (`span=4`) on a row(`height=200px`). The height of the second panel is set as 100px.

When we try to modify its height manually, it will increase/decrease the others panels height. It happens because when we increase/decrease the size of a panel manually we are changing the height of the row, not the panel height itself. So the panels with unset height takes it's height property from row automatically. After playing incresing/decreasing manually the panel 2 it becomes buggy and it's unable to select panel3

![height_buggy](https://cloud.githubusercontent.com/assets/13196237/13185421/5745a55e-d741-11e5-894f-9f54801ea1d8.png)

I think that if some of the panels are set with a height, it wouldn't be able to modify row height incresing/decreasing panel size manually.
Furthermore, the feature of modifyng manually the height of a panel, should change its own height, not the whole row height.

Thanks for all

**Comment by torkelo** [comment]
Settling panel height is not recommended, please only set row height
