### ISSUE TITLE
Feature Request : shared crosshair only on a row panel

### ISSUE THREAD

**Issue by Dual-Boot** [grafana/grafana#4085]
Hello,

 First, nice work.
I think shared crosshair is a useful option into dashboard, but it would be great to have the same feature only for a row panel.

  Thank you.

**Comment by torkelo** [comment]
Why only for a row ?

**Comment by Dual-Boot** [comment]
Hello,

 On a dashboard, I can set different row panels . And I put into one row panel several graphics. To enhance navigation into multiple graphic and better performance, I think a share crosshair into row panel and not the whole dashboard is more efficient.

  It's just my point of view.
  Regards
