### ISSUE TITLE
FR: Grafana Blame

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4086]
It would be great if we can keep history of changes in dashboards. But a good start can be just keeping an history of who changed it and when.

**Comment by utkarshcmu** [comment]
Also, we can have a small optional setting for admin's to set for saving dashboards. An admin can enable on Grafana/Organization's level to write a change log or change summary. So, when a user clicks on save button for any dashboard and if the admin has enabled this setting of "change summary" , a small modal can appear to write couple of lines like the one which comes up when we click on "Save as..". And then the editor's comments can be stored with the other change details.

**Comment by utkarshcmu** [comment]
Use case: This feature is important for an organization like us: We have offices all over the globe, where Grafana is being used as the primary monitoring system with thousands of people using it 24x7.

**Comment by bergquist** [comment]
Since this issue is very similar to #1504 I think we should keep the discussion there. 
Feel free to reopen if you disagree :)
