### ISSUE TITLE
Expired snapshots not purged from db

### ISSUE THREAD

**Issue by gummiboll** [grafana/grafana#4087]
Hello!

I've noticed that expired local snapshots are still left in the database, not a huge deal but seems unnecessary to keep them. Especially if snapshots are used excessively.

Would be nice if they where removed from the database after the expiration date has passed.

**Comment by utkarshcmu** [comment]
IMO,
Ideal solution - Grafana backend daemon.
Quick solution - Grafana-cli + CRON.

**Comment by bergquist** [comment]
I think this should be solved by a background job in grafana. Same as https://github.com/grafana/grafana/issues/2172
