### ISSUE TITLE
Resource picker doesn't show correct data when identity has access to resources in multiple subscriptions

### ISSUE THREAD

**Issue by kayodeprinceMS** [grafana/grafana#40889]
**What happened**:
Using Azure Monitor data source.
Configured managed identity with Monitor Reader role to one subscription(1), and to a Log Analytics workspace in a second subscription (2).
When building a query with Data Source: Azure Monitor and Service: Logs, the Select a **resource scope incorrectly shows the resources for subscription (1) under subscription (2)** 

**What you expected to happen**:
Resources for a subscription should only be listed under the subscription to which they belong.
![image](https://user-images.githubusercontent.com/58087222/138727863-1d826537-4c2b-4ea8-9306-df60df1d7310.png)

**How to reproduce it (as minimally and precisely as possible)**:
Configure Azure Monitor Data source
Allow Monitor reader access to one subscription and to a single resource in another subscription.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.5
- Data source type & version:  Azure Monitor 0.30
- OS Grafana is installed on:
- User OS & Browser: Microsoft Edge
- Grafana plugins: Azure Monitor
- Others:

**Comment by iwysiu** [comment]
Hi @kayodeprinceMS , I'm currently taking a look at this. How was the managed identity created? Through Terraform or manually?

**Comment by kayodeprinceMS** [comment]
@iwysiu The managed identity was created during deployment using ARM template.

**Comment by iwysiu** [comment]
Hi @kayodeprinceMS ! As an update, I have reproduced it and I'm working on fixing it.
