### ISSUE TITLE
Add an option to display stddev as a % around the mean

### ISSUE THREAD

**Issue by kettch** [grafana/grafana#409]
It would be great to be able to display the standard deviation as a range around the mean (that is a bar, or band, around the curve of the mean), rather than an absolute value.
It is much more readable to be able to see the mean and the range as a whole, and the evolution in time, instead of two values without any relation.

**Comment by torkelo** [comment]
needs to implemented in time series store (in query), before aggregation

**Comment by fsaf11** [comment]
Please, how to do it?

**Comment by yanivmo** [comment]
It is possible to graph deviations around a metric using the "fill below" display option. See #940 for more details.
