### ISSUE TITLE
Influxdb: Aliasing of multiple fields with aggregations:

### ISSUE THREAD

**Issue by ashb** [grafana/grafana#4090]
I'm playing with Grafana 2.6.0 and Influxdb 0.10.0 and I've run into some problem aliasing fields properly when using aggregations.

I have something putting multiple field values into a series called `mem`:

```
> SHOW FIELD KEYS FROM mem;
name: mem
---------
fieldKey
active
free
inactive
percent
total
used
wired
```

My query is this: `SELECT "wired", max("active") FROM "mem" WHERE "hostname" = '$hostname' AND $timeFilter GROUP BY time($interval) fill(none)`

If I set the alias to `$m.$col` the two aliases I get out are:

- `mem.active` -- this one is fine and as i expect
- `mem.max` -- this one shows the name of the aggregation, not the name of the field itself.

For two this is manageable but if I wanted to add multiple fields, such as active,inactive,wired,free all with max() aggregations then having to alias them manual is not ideal.

Is this a bug? I'd expect `$col` to always show the actual column name.

**Comment by torkelo** [comment]
You need to addo alias to the field using aggregation function, otherwise influxdb only returns the aggregations name

**Comment by ashb** [comment]
What is the purpose of `$col` then? If you are using aggregations it seems to be always incorrect.

If I use `field(*)` + aggregation how am I meant to alias it?

**Comment by torkelo** [comment]
@ashb this is how InfluxDB has decided it thinks columns names should be returned so dont blame Grafana for InfluxDB behavior. 

InfluxDB returns `max` as the column name (field name), when you write  `max(my_cool_column)`

But you ca fix this by adding an AS expression, `max(my_cool_column) AS my_cool_column`, this is done in the Grafana query editor by using the alias function :)  (not a real influxdb function byt syntactic sugar to clean up the horribly bad InfluxDB query language)

<img width="682" alt="screen shot 2016-02-20 at 22 57 35" src="https://cloud.githubusercontent.com/assets/10999/13199447/c8a3c7aa-d825-11e5-95d3-b6ca48f9e0c3.png">

**Comment by ashb** [comment]
Ah right, thanks! (Just learning InfluxDB after many years of using Graphite).

**Comment by sLuvpreet33** [comment]
@ashb Can you post the query which you made to alias the 2 fields ?

I am also facing this problem and I have just started influxdb, and no experience.

`SELECT (("speed"),("longitude")) AS "metric", "latitude", "longitude", "vehicleno", "geohash" FROM "vehicleinfo" WHERE "vehicleno" = 'KA-03-AD-6910'`

I want both speed and longitude as metric . How can I do that ?
