### ISSUE TITLE
Alerting: unable to change contact point when Alertmanager is not ready

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#40901]
**What happened**:
When internal Alertmanager fails to start due to invalid configuration, Grafana does not let it change the configuration because Alertmanager is not ready. On UI side this affects pages "Contact Points", "Notification Policies", "Admin" as they use the same API and model. The user is not able to change anything on these pages.

**What you expected to happen**:
Grafana should let users change configuration no matter what's the state of Alertmanager is. 

**How to reproduce it (as minimally and precisely as possible)**:
- Disable feature flag `ngalert`
- Create a notification channel that will not be accepted by Alertmanager (for example Slack https://github.com/grafana/grafana/issues/40709)
- Change the feature flag and restart Grafana
- Go to "Contact Points", remove or fix the bad configuration. Click the Save button. The request will fail with the message "Alertmanager is not ready".
 

**Environment**:
- Grafana version: 8.3.0-e117b80
- Data source type & version: MySql 
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10
- Grafana plugins: N/A
- Others: N/A

**Comment by yuri-tceretian** [comment]
@gotjosh @armandgrillet should we prioritize that?

**Comment by armandgrillet** [comment]
Yes, will triage next week.
