### ISSUE TITLE
Influx series filter based on values

### ISSUE THREAD

**Issue by cxreg** [grafana/grafana#4091]
In graphite, there are a number of functions that eliminate candidate series based on qualities of the values returned.  As far as I can tell, no such functionality exists for Influxdb.  I have opened https://github.com/influxdata/influxdb/issues/5760 to request this.

However, it seems possible that this is best implemented in the client, as it would require a second pass over the data, and since Influx uses cursors and streaming to populate a result set, this could be difficult.

Do you think that Grafana could support these kinds of filters for the Influx backend, removing series that don't qualify?

Here are the graphite functions I was able to identify which fall into this category (which filter on, but do not modify, series values)

averageAbove
averageBelow
currentAbove
currentBelow
highestAverage
highestCurrent
highestMax
lowestAverage
lowestCurrent
maxSeries
maximumAbove
maximumBelow
minSeries
minimumAbove
minimumBelow

Doing this in the client is not as functional as what Graphite does, since you could run further functions on the reduced set of series there, but it would be better than not having it at all

**Comment by bergquist** [comment]
we have been considering meta queries which sounds something you describe (https://github.com/grafana/grafana/issues/3677) but have not had the time to start working on it yet.

**Comment by torkelo** [comment]
Filtering series is something that is mainly up to InfluxDB to handle, but it's going to be tricky with their horrible query language, but they might be able to do something.
