### ISSUE TITLE
Fix fastpass issues on Cloudwatch plugin

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#40915]
Download the chrome extension for testing pages here: https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en

Fix any problems! 😄

**Comment by vickyyyyyyy** [comment]
dupe of https://github.com/grafana/grafana/issues/42705 and https://github.com/grafana/grafana/issues/42706
