### ISSUE TITLE
heatmap shows patterns where the data is zero

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#40919]
The Grafana heatmap visualization shows a "wave pattern" even though all the data is zero.
See the gif below showing the heatmap while toggling zeroes on and off, which reveals the fake pattern, I think it also depends on the max datapoints value.

![heatmap-pattern](https://user-images.githubusercontent.com/20774/138849284-ad50f9ef-dc7d-4215-8a1b-36126231595a.gif)

**Comment by leeoniya** [comment]
i think this is much improved in the new heatmap panel but probably impossible to solve for all display resolution, data shape, and config combos.
