### ISSUE TITLE
Unified Alerting : one empty template variable stops any other variable to be associated with it's corresponding value in the generated alert

### ISSUE THREAD

**Issue by Irrational-NX** [grafana/grafana#40918]
No sure if this is a bug or if it should be a feature request...

**What happened**:
Triggered an alert (grafana managed alert/prometheus queries and reduce/math expressions) containing multiple template variables, but not a single variable is replaced with it's corresponding label/value because one template variable is empty/missing.

Corresponding log error :

> lvl=eror msg="error in expanding template" logger=ngalert name=summary value="Interface {{ $labels.ifName }} {{ $labels.ifAlias }} of switch {{ $labels.instance }} blablabla DOWN : {{ $values.C.Value }}% / UP : {{ $values.D.Value }}%" err="error executing template __alert_Network switches - [DEBUG] my alert name: template: __alert_Network switches - [DEBUG] my alert name:1:117: executing \"__alert_Network switches - [DEBUG] my alert name\" at <$labels.ifAlias>: map has no entry for key \"ifAlias\""

Generated alert when label exists :
_summary: Interface Gi2/0/47 6B12 of switch 10.0.0.1 blablabla : DOWN : 92% / UP : 11%_

Genrated alert when **ifAlias** label is empty :
_summary: Interface {{ $labels.ifName }} {{ $labels.ifAlias }} of switch {{ $labels.instance }} blablabla  : DOWN : {{ $values.C.Value }}% / UP : {{ $values.D.Value }}%_

**What you expected to happen**:
Every variable that has a label/value is replaced, and the variable that contains nothing is replaced by a blank or not replaced at all (and stay in the form {{ $labels.XXXXX }} in the generated alert).
Just like when using a legend on a graph, if the label contains nothing, then it's replaced with nothing.
Legend **{{instance}} - {{ifName}} ({{ifAlias}})** gives the following result :
![image](https://user-images.githubusercontent.com/32514952/138844859-982e28ce-ebd1-43c9-89b8-8fb1a8d2dc75.png)

**How to reproduce it (as minimally and precisely as possible)**:
Creating an alert and using template variables that sometimes contains nothing.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: Prometheus 
- OS Grafana is installed on: Docker container : 8.2.2-ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by santihernandezc** [comment]
Hi @Irrational-NX,
This is the expected behavior for cases where a key is missing when parsing a template. This was introduced to solve [issue 35943](https://github.com/grafana/grafana/issues/35943) as we didn't want to send alerts with missing labels.
That being said, your proposed alternative makes for a better user experience, so I'll label this as a feature request.
Thanks for opening this issue!

**Comment by santihernandezc** [comment]
Hey @Irrational-NX,
We've merged a [PR](https://github.com/grafana/grafana/pull/41617) that solves this issue you're having. This feature will be available in 8.4.0.
