### ISSUE TITLE
Table Gauge Charts - value from calculated field always plotted as 0

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#40926]
**What happened**:
In a table panel, when showing data as a gauge bar, if the field is the result of a calculation (made in the query itself, or using the transform "Add Field from Calculation") the chart is not rendered properly. apparently is always stuck at 0.

here the field value is 0.264
![image](https://user-images.githubusercontent.com/12230314/138855553-e10a538e-61f5-4913-aaae-8f14efdc3da7.png)

This is the override configuration
![image](https://user-images.githubusercontent.com/12230314/138855749-7e459569-e4b0-44ec-9359-c4eda25c26d4.png)
Notes:
- even without min and max values, the issue persists
- even if the value is multiplied by 100 (therefore obtaining 26.4) it is still plotted as 0

This is my query (the same can be calculated using transform)
![image](https://user-images.githubusercontent.com/12230314/138857956-d114e1b0-9bba-458c-8de1-8c53f69e5319.png)

**What you expected to happen**:
I expect the gauge to plot the correct value

**How to reproduce it (as minimally and precisely as possible)**:
- Create a table object
- one of the fields must be the result of a division (or maybe any other operation) between 2 fields
    - it can be computed by the query itself or by using transform > "Add Field from Calculation" > Binaty Operation
- show the calculated field as a gauge.
- it should be stuck at 0 regardless of the value
- 
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on: Windows Server
- User OS & Browser: Windows 10, Chrome
- Grafana plugins: None
- Others:

**Comment by dprokop** [comment]
@Trovalo indeed, it looks like the values are 0, yet under the hood they are correct (ranging 0-1.0)

The problem here is that the bar gauge range is calculated based on the actual field values. The unit option is a **value  formatting option** only, and bar gauge (and other cell modes) are not taking it into consideration - they always produce results based on the raw data provided.

What you can do to achieve the results you want is to add two more transformations:
1. Add field from calculation where the new field's value is  `pct * 100`
2. Organize fields where you hide the `pct` field.

Then the values will be actual percents (0-100) and you can just format those as a percent unit.

Hope this helps!

**Comment by Trovalo** [comment]
Just a note, it works as said by @dprokop in the latest version of Grafana (as of now v8.2.3), but it doesn't in the previous version (I'm using v8.2.1)
I can say that in v8.2.1 as soon as you hide the "base" value (not yet *100) the issue comes back, and the gauge is plotted as a 0 value. It makes no sense but that's it.

**Comment by Trovalo** [comment]
Hi... 
I'm back because I'm unable to solve the issue (even after updating Grafana) and also unable to replicate it in the Grafana playground.

Here is my situation, I've calculated two fields, _Free (range 0-1) and Free (range 0-100), the point is that as soon as I hide the "support" field _free, the gauge plots 0 as value.

All visible:
![image](https://user-images.githubusercontent.com/12230314/143270529-135cc22f-765b-479f-a9ac-cea2ff4c7765.png)

Hidden support field:
![image](https://user-images.githubusercontent.com/12230314/143270821-e851e9ef-c055-4dda-ab02-661c0b73c7ac.png)

I've tried to replicate it in the grafana playground, using the same Grafana version `Grafana v8.2.5 (b57a137acd)`  and the same data source, InfluxDB.
The playground behaves correctly and keeps rendering the gauge properly even after hiding the support field.

here are the panels Json

<details>
  <summary>My panel Json</summary>

```
{
  "id": 23763571993,
  "gridPos": {
    "x": 0,
    "y": 23,
    "w": 18,
    "h": 8
  },
  "type": "table",
  "title": "Panel Title",
  "transformations": [
    {
      "id": "calculateField",
      "options": {
        "mode": "binary",
        "reduce": {
          "reducer": "sum"
        },
        "binary": {
          "left": "Available Space",
          "operator": "/",
          "right": "Total Space",
          "reducer": "sum"
        },
        "alias": "_Free"
      }
    },
    {
      "id": "calculateField",
      "options": {
        "mode": "binary",
        "reduce": {
          "reducer": "sum"
        },
        "binary": {
          "left": "_Free",
          "operator": "*",
          "right": "100",
          "reducer": "sum"
        },
        "alias": "Free"
      }
    },
    {
      "id": "organize",
      "options": {
        "excludeByName": {
          "_Free": true,
          "Free": false
        },
        "indexByName": {},
        "renameByName": {}
      }
    }
  ],
  "pluginVersion": "8.2.5",
  "options": {
    "showHeader": true
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "displayMode": "auto"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      },
      "unit": "kbytes"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "Free"
        },
        "properties": [
          {
            "id": "custom.displayMode",
            "value": "gradient-gauge"
          },
          {
            "id": "unit",
            "value": "percent"
          },
          {
            "id": "max",
            "value": 100
          }
        ]
      }
    ]
  },
  "targets": [
    {
      "refId": "A",
      "query": "SELECT last(\"available_space_bytes\") AS \"Available Space\", last(\"used_space_bytes\") AS \"Used Space\", last(\"total_space_bytes\") AS \"Total Space\" FROM \"$InfluxDB_RetentionPolicy\".\"sqlserver_volume_space\" WHERE $timeFilter GROUP BY \"volume_mount_point\", \"sql_instance\" fill(none)",
      "rawQuery": true,
      "resultFormat": "table"
    }
  ],
  "datasource": null
}
```
</details>

I've also create the same in the Grafana playground, and there it works
<details>
  <summary>Grafan Playground panel Json</summary>
  {
  "id": 15,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 8
  },
  "type": "table",
  "title": "Panel Title",
  "targets": [
    {
      "scenarioId": "csv_content",
      "refId": "A",
      "csvContent": "disk,used,total\na,80,100\nb,33,100\nc,42,100"
    }
  ],
  "options": {
    "showHeader": true
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "displayMode": "auto"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "pct_100"
        },
        "properties": [
          {
            "id": "custom.displayMode",
            "value": "lcd-gauge"
          }
        ]
      }
    ]
  },
  "datasource": "TestData DB",
  "pluginVersion": "8.2.5",
  "transformations": [
    {
      "id": "calculateField",
      "options": {
        "mode": "binary",
        "reduce": {
          "reducer": "sum"
        },
        "alias": "pct",
        "binary": {
          "left": "used",
          "operator": "/",
          "right": "total",
          "reducer": "sum"
        }
      }
    },
    {
      "id": "calculateField",
      "options": {
        "mode": "binary",
        "reduce": {
          "reducer": "sum"
        },
        "binary": {
          "left": "pct",
          "operator": "*",
          "right": "100",
          "reducer": "sum"
        },
        "alias": "pct_100"
      }
    },
    {
      "id": "organize",
      "options": {
        "excludeByName": {
          "pct_100": false,
          "pct": false
        },
        "indexByName": {},
        "renameByName": {}
      }
    }
  ]
}
```
</details>

Do you see something that I'm missing or do you have any other idea about what could be wrong?
