### ISSUE TITLE
Explore URL doesn't preserve LogQL quotes properly - introduces syntax error

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#40936]
When I explore Loki logs and then share the URL, I'm seeing that some of the quotes are getting removed, which **break the query I've written**.
This query: `{namespace="hosted-grafana"} | logfmt | insight_logs="true"` returns results fine. If I copy the URL (see GrafanaLabs Internal [Slack message here for URL](https://raintank-corp.slack.com/archives/CPXKS6FB5/p1635249958044100)), then open it in a new tab, the query is now `{namespace="hosted-grafana"} | logfmt | insight_logs=true`, which apparently is a Syntax Error :angry:

**Comment by gabor** [comment]
this is probably fixed by https://github.com/grafana/grafana/pull/42288 , will be available in grafana8.3.0 . i will close the issue for now, if it is not fixed, we can reopen the issue.

**Comment by samjewell** [comment]
Thanks @gabor and team for fixing this ❤️
