### ISSUE TITLE
UX bug in master: Snapshot nav bar UI broken

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4094]
Here is an image of how a snapshot page looks currently in Grafana master:

<img width="1383" alt="screen shot 2016-02-20 at 7 29 23 pm" src="https://cloud.githubusercontent.com/assets/1019609/13200703/9b4efd96-d808-11e5-828e-bae61d11f790.png">

The nav bar where title is a bit messed up.

**Comment by torkelo** [comment]
thanks for reporting this, fixed now!
