### ISSUE TITLE
Multiselect Template UI is messed up

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4096]
<img width="511" alt="screen shot 2016-02-20 at 10 13 33 pm" src="https://cloud.githubusercontent.com/assets/406777/13201299/3db032e2-d81f-11e5-82d1-41ea704c37b6.png">

**Comment by torkelo** [comment]
thanks for reporting this, it's fixed now. Sorry for having a buggy master at the moment (not how it usually is / should be), we are doing some big UX and style changes

**Comment by deepujain** [comment]
How do i update the code ? Please share instructions. Last time i had to delete everything and install again.
