### ISSUE TITLE
Grafana 8 alerting framework - `failed to save rule` to a folder that includes slash in folder name 

### ISSUE THREAD

**Issue by aengusrooneygrafana** [grafana/grafana#40979]
**What happened**: 

I’m getting the following message when trying to save an alert on Hosted Grafana  (latest version) 

![image](https://user-images.githubusercontent.com/54800912/139047485-70756d36-9381-4d31-a04a-760656027d06.png)

https://ops.grafana.net/explore?left=%5B%22now-1h%22,%22now%22,%22Grafana%20Logging%[…]7D%20%7C%3D%20%5C%22rooney%5C%22%22,%22refId%22:%22A%22%7D%5D

```t=2021-10-26T11:43:56+0000 lvl=eror msg="Request Completed" logger=context userId=8 orgId=1 uname=aengusrooneygrafana method=GET path=/api/prometheus/18/api/v1/rules status=502 remote_addr="130.211.1.165, 127.0.0.1" time_ms=7 size=2 referer="https://xxxx.grafana.net/?orgId=1" traceID=0362a6081ba1a818```

```t=2021-10-26T11:43:56+0000 lvl=eror msg="Data proxy error" logger=data-proxy-log userId=8 orgId=1 uname=aengusrooneygrafana path=/api/v1/rules remote_addr= referer= error="http: proxy error: http: no Host in request URL"```

the alert query i’m running is against the provisioned prom datasource - 

`absent(container_start_time_seconds{name="master"})` 

using a ‘grafana managed alert’… 

 the log from the Grafana instance created when we try and save this alert  (I put it in the folder whose name inclusdes a slash e.g "xxxx/yyyy" ... 

```t=2021-10-27T08:51:47+0000 lvl=info msg="Request Completed" logger=context userId=10 orgId=1 uname=xxxx method=GET path=/api/ruler/grafana/api/v1/rules/xxxx/yyyy status=404 remote_addr="35.191.12.103, 127.0.0.1" time_ms=6 size=51 referer="https://xxxx.grafana.net/alerting/new?returnTo=%2Falerting%2Flist" traceID=3b01ed133e6c9db2```

If i put it in another folder e.g. "XXXX", it saves fine. Is there an issue here if there's a / in the folder name? it doesnt look like the folder name is escaped for the url. 

**What you expected to happen**:

New alert rule saves successfully in a folder that includes a slash in the folder name.  

**How to reproduce it (as minimally and precisely as possible)**: 

Save an alert to a folder that includes a slash in the folder name.  

**Anything else we need to know?**:

**Environment**:
- Grafana version:  Hosted Grafana latest 
- Data source type & version:  prometheus data source latest 
- OS Grafana is installed on:  hosted grafana 
- User OS & Browser:  Macos / Chrome 
- Grafana plugins:  prometheus data source  
- Others:  n/a

**Comment by aengusrooneygrafana** [comment]
In addition, we are getting a 404 when trying to delete an Grafana Managed alert that has a slash in the rule name….  (We are logged in as admin role, and we can create/delete rules without a slash in the rule name).    

```t=2021-11-01T14:55:08+0000 lvl=eror msg="UnhandledRejection: Non-Error promise rejection captured with keys: config, data, status, statusText" logger=frontend user_id=5 url="https://<redacted>.grafana.net/alerting/grafana/Wb5fCRFnz/view?returnTo=%2Falerting%2Flist" user_agent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/95.0.4638.54 Safari/537.36" event_id=af90bcfdc352453d89d7241bd71c4174 original_timestamp=2021-11-01T14:55:08+0000 stacktrace="UnhandledRejection: Non-Error promise rejection captured with keys: config, data, status, statusText" user_email=vojtech.zak@notino.com``` 

https://ops.grafana.net/explore?left=%5B%22now-1h%22,%22now%22,%22Grafana%20Logging%22,%7B%22expr%22:%22%7Bapp%3D%5C%22grafana%5C%22,org%3D%5C%22notino%5C%22%7D%20%22,%22refId%22:%22A%22,%22datasource%22:%22Grafana%20Logging%22%7D%5D&orgId=1 

Conversation in slack:  https://raintank-corp.slack.com/archives/C02CV25CQ3Y/p1635779156072300

**Comment by yuri-tceretian** [comment]
Currently, hosted Grafana is 8.1.7 (at least my personal instance), and I could reproduce it. However, I failed to reproduce on Grafana 8.3.0-e8a30f6. The same folder and alert rule names were handled successfully.

**Comment by davidmparrott** [comment]
I think this is specific to hosted grafana. I tested using 8.1.2 because I had it locally already and it also handled saving a rule to a folder named `some/test` successfully. Let's see if anyone from @grafana/hosted-grafana-team can chime in.

**Comment by filewalkwithme** [comment]
I tried to reproduce the issue on Hosted Grafana using versions 8.1.7, 8.2.5 and even 8.3.0-e8a30f6 without success.

Please, let me know if the issue is still happening.

**Comment by davidmparrott** [comment]
We have managed to reproduce this with @filewalkwithme and will update here when we are confident we understand the root cause.

**Comment by filewalkwithme** [comment]
Thanks @davidmparrott, I confirm this issue is tied to Hosted Grafana. Also, we were able to identify the root cause. I created a new issue on Hosted Grafana in order to fix this.

**Comment by davidmparrott** [comment]
So long as we make sure to update this public issue once we've fixed the HG issue, I have no problem with that. Thanks for the hard work, @filewalkwithme
