### ISSUE TITLE
Annotations error: "Cannot read property 'message' of null"

### ISSUE THREAD

**Issue by mlowicki** [grafana/grafana#4097]
Seems to happen while Grafana can't retrieve events from Graphite. I guess more descriptive message should be displayed in such case.

**Comment by fernandotid** [comment]
I have the same problem when i take one week of metrcis of CPUs for 15 Servers

**Comment by torkelo** [comment]
seem to be fixed master

**Comment by gourav-sg** [comment]
I think that the error messages are different depending on the browser you are using.

**Comment by Quentinvarquet** [comment]
Hello,

FYI, the problem is from google chrome. It works perfectly if you take internet explorer
