### ISSUE TITLE
Grafana 2.6 logout failed when use nginx as a proxy

### ISSUE THREAD

**Issue by majj** [grafana/grafana#4098]
nginx conf:

location /grafana {
     proxy_pass         http://localhost:3000;
     rewrite  ^/grafana/(.*)  /$1 break;
     proxy_set_header   Host $host;
}

grafana ini:

[server]
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana

**Comment by torkelo** [comment]
Your nginx config is not right, requires trailing slash I think.  Please search existing issues , been reported a number of times

**Comment by majj** [comment]
Working!  Thanks!

**Comment by mrehker** [comment]
@majj - what was the solution?
