### ISSUE TITLE
Templating: How do i use variable sensitive (context aware)  with InfluxDB

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4099]
I have five template variables.
show tag values with key="alertId"
show tag values with key="siteId"
show tag values with key="businessUnit"
and two more.

Each one of them work fine, but i want them to be aware of one another. With left most as broadest filter and right most as narrowest filter.

I want to do this
show tag values with key="siteId" and alertId=$AlertId
show tag values with key="businessUnit" and alertId=$AlertId and siteId=$siteId
show tag values with key="experimentId"and alertId=$AlertId and siteId=$siteId and businessUnit=$businessUnit.

such kind of queries are not supported in InfluxDB (its like a global query) and select * query is fine but then it always has time has first column and grafana does not have a capability to select columns (like it does for annotations).

How do i acheive this with Influx + Graph. Or is it not possible ?

**Comment by deepujain** [comment]
I mean drop down that shows the values should be that. My last filter has atleast 200 values and a user cannot know what experiments (id, 200 values) belongs for its business unit. If the query was smart and filtered and showed only those experimentIds (like 10 of them) then it becomes easy

**Comment by torkelo** [comment]
You can use two template variables and use the first one in the query for the second variable

**Comment by deepujain** [comment]
I can but influx db does not support where in show tags and grafana does
not support variable selection from select queries as time is always first
column in select query for influx
