### ISSUE TITLE
[ Azure Monitor ] [ alerting ] "failed to execute query A: no handler found for query type"

### ISSUE THREAD

**Issue by rajabalaji-mp** [grafana/grafana#41001]
**What happened**:

When configuring Grafana alert rules, with Azure Monitor Datasource we had an error: 

`Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: no handler found for query type`

**What you expected to happen**:

Alert rule to get created without errors.

**FIX**:

When investigating further we see the request payload is passing queryType as null, when we change it to Azure Monitor, it works fine. Screenshots with the default payload from Grafana Azure Monitor plugin and corrected payload follow. 

NOT WORKING:

![image](https://user-images.githubusercontent.com/7393278/139090402-d2d25410-9d77-4372-ba75-0407f30eb1df.png)

WORKING:

![image](https://user-images.githubusercontent.com/7393278/139090692-3178f29f-f063-4465-bdda-f52e2acd4356.png)

**How to reproduce it (as minimally and precisely as possible)**:

Create an Alert rule with Azure Monitor data source. Please fix the payload.

**Anything else we need to know?**:

**Environment**:
- Grafana version: helm.sh/chart=grafana-6.16.4
- Grafana version: 8.1.0
- Data source type & version: Azure Monitor 0.3.0
- OS Grafana is installed on: Kube-prometheus-stack
- User OS & Browser: All
- Grafana plugins: Azure Monitor datasource
- Others:

**Comment by zuchka** [comment]
thanks, @andresmgot! I added the `area/alerting/unified` tag. FYI @grafana/alerting-squad 👍 ⏰

**Comment by rajabalaji-mp** [comment]
@zuchka what does this mean to us interms of timeline to rollout fixes please?

**Comment by tonedefdev** [comment]
I also wanted to state that I'm having the same issue when using Azure Logs as a data source for next gen alerting, so it's not just Azure Monitor that's returning this error message. Essentially, all new alerts are broken as no queries work despite them working in the Explorer.

**Comment by mstavrev** [comment]
I am having the same issue. Any update?

**Comment by domasx2** [comment]
Hey, working on this, will have a fix soon
