### ISSUE TITLE
UI Bug: Single stat panel , post fix text

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4101]
The post fix tag as additional line between the actual value and itself.

See pic.

<img width="1151" alt="screen shot 2016-02-21 at 10 53 25 am" src="https://cloud.githubusercontent.com/assets/406777/13204634/7946ba5a-d889-11e5-865c-2fd20876f32b.png">

6%

experiments.

I was expecting to see
6%
experiments.

There is additional line break between 6% and experiments.

**Comment by bergquist** [comment]
Both element cannot fit within the panel. Try widen the panels or decrease value fontsize.
