### ISSUE TITLE
Docs feedback: /visualizations/table/_index.md

### ISSUE THREAD

**Issue by mlewald** [grafana/grafana#41016]
For "Minimum column width"

Suggesting to add a note for this field description indicating that small screen devices (such as mobile smart phones) may need the default 150 pixel value reduced to 50 in order for some table based panels to render correctly in dashboards.

This limit was being hit in a phone triggering an endless re-size attempt causing the dashboard to constantly re-render.

ZD: 36041

**Comment by achatterjee-grafana** [comment]
Fixed.
