### ISSUE TITLE
Table panel content changes when annotation is selected/deselected.

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4102]
Annotations and Table contents are two independent "things". I see that table contents (either actual content/sorting of rows) is changing . Why is that ?

<img width="1383" alt="screen shot 2016-02-21 at 11 18 26 am" src="https://cloud.githubusercontent.com/assets/406777/13204781/08276f5a-d88d-11e5-9729-3367a6ba8bd2.png">
<img width="1380" alt="screen shot 2016-02-21 at 11 18 33 am" src="https://cloud.githubusercontent.com/assets/406777/13204782/0827c8ba-d88d-11e5-88a4-b332e0642b56.png">

Experiment Version Id column contents are changing. 

Other panels (graph) did not change which are further down the page.

Annotations:
select * from dqannotation where $timeFilter AND alertId='1'

Table Panel:
SELECT "metricValue" AS "Delta","metricId","experimentId","exprtVersionId","treatmentId","treatmentVersion","businessUnit","channelId","siteId" FROM "dataquality" WHERE "alertId" = '1'  AND $timeFilter

Both are different queries and do not overlap in anyway.

**Comment by torkelo** [comment]
Maybe an influxdb bug? Enabling annotations triggers a refresh if all panels Can you check the table panels query and response from influxdb?

**Comment by deepujain** [comment]
Queries generated are exact match:

SELECT metricValue AS Delta, metricId, experimentId, exprtVersionId, treatmentId, treatmentVersion, businessUnit, channelId, siteId FROM mydb."default".dataquality WHERE alertId = '1' AND time > 1455082104s AND time < 1455740291s


SELECT metricValue AS Delta, metricId, experimentId, exprtVersionId, treatmentId, treatmentVersion, businessUnit, channelId, siteId FROM mydb."default".dataquality WHERE alertId = '1' AND time > 1455082104s AND time < 1455740291s

And hence results should also be good.

**Comment by torkelo** [comment]
did you check the order of results returned from influxdfb?

**Comment by torkelo** [comment]
since you are sorting the table by Delta, and it's the same, difference in how InfluxDB returns data could matter
