### ISSUE TITLE
Failing to build Grafana on a Raspberry Pi 2 Model B, running Raspbian Jessie

### ISSUE THREAD

**Issue by phrend** [grafana/grafana#4104]
I know that the Raspberry Pi is not really your target audience, but I use Grafana at work, and would like to start using it at home...

I'm following the instructions on [http://docs.grafana.org/v2.6/project/building_from_source/](url) to build 2.6.0, but I suspect that I'm really building whatever's checked in to the master branch, since there's no `git checkout` in the list of commands, but I'm certainly not an expert at this.

I was able to get through building the backend, though I have not tested it, since I'm having trouble building the front end...

After running `npm install` I see

```
> node-sass@3.4.2 install /home/pi/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass
> node scripts/install.js

Cannot download "https://github.com/sass/node-sass/releases/download/v3.4.2/linux-arm-46_binding.node":

HTTP error 404 Not Found

Hint: If github.com is not accessible in your location
      try setting a proxy via HTTP_PROXY, e.g.

      export HTTP_PROXY=http://example.com:1234

or configure npm proxy via

      npm config set proxy http://example.com:8080

> node-sass@3.4.2 postinstall /home/pi/grafana/src/github.com/grafana/grafana/node_modules/grunt-sass/node_modules/node-sass
> node scripts/build.js

```
...so, I may have to compile that myself.

Eventually, the process exits with
```
npm ERR! Linux 4.1.17-v7+
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v4.3.0
npm ERR! npm  v2.14.12
npm ERR! code ELIFECYCLE

npm ERR! phantomjs@1.9.19 install: `node install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the phantomjs@1.9.19 install script 'node install.js'.
npm ERR! This is most likely a problem with the phantomjs package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls phantomjs
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/grafana/src/github.com/grafana/grafana/npm-debug.log
```

I did compile phantomjs and put it in my path
```
pi@raspberrypi:~/grafana/src/github.com/grafana/grafana $ which phantomjs
/usr/local/bin/phantomjs
pi@raspberrypi:~/grafana/src/github.com/grafana/grafana $ phantomjs --version
2.1.1
```
...so, I'm wondering if Grafana specifically requires v1.9.19, or if there's some other issue?

I did find links to [someone else's pre-compiled packages](http://padcom13.blogspot.de/2015/12/influxdb-telegraf-and-grafana-on.html) in another post here, so I may give them a try, but have been working at this for days now, so was hoping to actually learn how to compile this myself.

Thanks!

**Comment by phrend** [comment]
Update

I just finished building node-sass and stuck the resulting files from ~/node-sass/node_modules/ in to ~/grafana/src/github.com/grafana/grafana/node_modules/ then went back to ~/grafana/src/github.com/grafana/grafana and tried `npm install` again, and it does seem to want 1.9.19, since I'm seeing this in the output
```
Found PhantomJS at /usr/local/bin/phantomjs ...verifying
PhantomJS detected, but wrong version 2.1.1 @ /usr/local/bin/phantomjs.
```

I guess I'll try building 1.9.19 and see if that does the trick! (prolly take all night to build it)

**Comment by bergquist** [comment]
Phantomjs is only used for exporting grahps in grafana to PNG. Unless that is something you need you could remove phantomjs from package.json
