### ISSUE TITLE
Click on color of legend - broken UI pops up

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4106]
<img width="288" alt="screen shot 2016-02-21 at 11 08 11 pm" src="https://cloud.githubusercontent.com/assets/406777/13211750/12eeb0ca-d8f0-11e5-8e54-17f4fbea9407.png">

**Comment by deepujain** [comment]
Gets worse.
Keep going up (one by one)
<img width="244" alt="screen shot 2016-02-21 at 11 09 27 pm" src="https://cloud.githubusercontent.com/assets/406777/13211763/303be67a-d8f0-11e5-884a-347725e92fc4.png">

**Comment by deepujain** [comment]
Refresh the page and behavior repeats 
<img width="183" alt="screen shot 2016-02-21 at 11 10 01 pm" src="https://cloud.githubusercontent.com/assets/406777/13211776/4b3bfc8a-d8f0-11e5-865d-6ba181a62272.png">

**Comment by torkelo** [comment]
@bergquist due to "overflow-y: scroll" on legend. 

I will fix this, can update the popover to use the new lib tether / tether drop as it will not be affected by this (the popover is then a child of body tag so it does not matter what the container style is)

**Comment by bergquist** [comment]
@torkelo sweet!

**Comment by torkelo** [comment]
fixed in latest master
