### ISSUE TITLE
grafana pie plugin, pie appearance is not stable.

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4107]
Once i create pie panel and put in a query and go back to dashboard it shows up. Save the dashboard and refresh the entire page it vanishes leaving legends behind.

<img width="247" alt="screen shot 2016-02-21 at 11 11 42 pm" src="https://cloud.githubusercontent.com/assets/406777/13211804/a165cc26-d8f0-11e5-861b-4876acd77ab7.png">

<img width="247" alt="screen shot 2016-02-21 at 11 11 31 pm" src="https://cloud.githubusercontent.com/assets/406777/13211805/a16607ae-d8f0-11e5-9e16-d898b33fc30e.png">

**Comment by torkelo** [comment]
please reopen in the pie plugin repo
