### ISSUE TITLE
Heatmaps using 'time series buckets' are effected by the 'time series' axis Y-Axis Scale option

### ISSUE THREAD

**Issue by bucko909** [grafana/grafana#41082]
**What happened**:

I made a bucketed histogram in Graphite, selected 'logarithmic scale', then switched to 'time series buckets'. The graph rendered in a really broken way. Specifically, the cells are rendered with more than one bucket's height, creating the illusion that lower buckets override upper buckets.

![image](https://user-images.githubusercontent.com/7436550/139418850-7a60d553-0d62-497c-9ebc-50809947869b.png)

**What you expected to happen**:

![image](https://user-images.githubusercontent.com/7436550/139418821-dcbe5a4e-448d-41ac-b9cb-967a165b8f12.png)

It should render a heatmap with equal-Y-spaced/sized cells.

**How to reproduce it (as minimally and precisely as possible)**:

Make a graphite (or probably any) datasource which returns a collection of series with floating point labels. Switch to the heatmap visualisation with format 'Time series'. Select Y-Axis scale 'logarithmic (base 10)' (or any nonlinear scale). Switch to 'Time series buckets' format.

![image](https://user-images.githubusercontent.com/7436550/139418879-3d056b24-c9ca-4635-b7c9-53947a033110.png)

**Anything else we need to know?**:

**Environment**:

- Grafana version: v7.5.2 (ca413c612f)
- Data source type & version: Graphite 1.1.x
- OS Grafana is installed on: Ubuntu?
- User OS & Browser: Firefox 78.15.0esr
- Grafana plugins: Status Panel, Pie Chart (doubtful that they are relevant).

**Comment by zuchka** [comment]
Thanks for creating this issue, @bucko909 

Any chance you can test this on 8.2.2? Just want to verify if you can reproduce across newer versions 👍

**Comment by bucko909** [comment]
@zucha not easily -- the only Grafana instance I have access to is our company-wide one. I can try to get it updated, though.

**Comment by bucko909** [comment]
@zucha (though, from memory, I found code in the current version which didn't check the data type before branching on the log/linear setting, which is what led me to try changing it.)
