### ISSUE TITLE
[ bug ] Provisioned dashboards can never be deleted, even with `disableDeletion: false`

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#41085]
**What happened**:
For a dashboard with `disableDeletion: false`:
- I hit an error which says "Provisioned dashboard cannot be deleted"
![Kapture 2021-10-29 at 11 24 09](https://user-images.githubusercontent.com/2903904/139419679-4251d66f-3f89-44d2-9d8f-7eaf77820824.gif)

**What you expected to happen**:
Dashboard with `disableDeletion: false` should be deletable

**How to reproduce it (as minimally and precisely as possible)**:
Provision a dashboard with `disableDeletion: false`, then try to delete it in the UI. The buttons and main UI elements seem to allow the flow, but there's an error at the end of the process and the dashboard cannot be deleted.

**Anything else we need to know?**:

**Environment**:
- Grafana version: OSS 8.2.2
- Data source type & version: none
- OS Grafana is installed on: macOS BigSur 11.5.2 (20G95) - Darwin Arm64
- User OS & Browser: macOS BigSur 11.5.2 (20G95) - Darwin Arm64, Chrome 95.0.4638.54 (Official Build) (arm64)
- Grafana plugins: none
- Others: none

Files I used:
Dashboard  provisioning file:
```yaml
apiVersion: 1

providers:
- name: 'disableDeletion: false'
  orgId: 1
  type: file
  disableDeletion: false
  allowUiUpdates: true
  options:
    path: /opt/homebrew/var/lib/grafana/plugins/disableDeletion-false.json
- name: 'disableDeletion: true'
  orgId: 1
  type: file
  disableDeletion: true
  allowUiUpdates: false
  options:
    path: /opt/homebrew/var/lib/grafana/plugins/disableDeletion-true.json
```

and `disableDeletion-false.json`

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "gnetId": null,
  "graphTooltip": 0,
  "id": null,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "collapsed": true,
      "datasource": null,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "panels": [],
      "title": "Provisioned Dashboard",
      "type": "row"
    }
  ],
  "schemaVersion": 31,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "disableDeletion: false",
  "uid": null,
  "version": 0
}
```

**Comment by zuchka** [comment]
Thanks for creating this issue, @samjewell 

yes, I confirm. Combining `disableDeletion: false` and `allowUiUpdates: true` does seem to dead-end in that error.

I bundled your example in a docker-compose to make reproducing easier:

```
git clone git@github.com:zuchka/grafana-41085.git
cd grafana-41085
docker-compose up -d
```

**Comment by sdboyer** [comment]
I certainly see the issue here, but i'm also not sure we actually want to fix it.

The basic problem here is a common one related to provisioning: we've added properties to objects themselves, like `disableDeletion`, that are more properly understood as object metadata relating to their lifecycle. These create a tension between the UI-as-writer, and provisioning-as-writer. The existence of that field implies control over writability (via the UI), but that would undermine the mapping that we seek to create via provisioning.

Case in point: if we were to allow deletion of that provisioned dashboard via the UI, then what happens the next time provisioning is run (at Grafana startup)? Should we reject the recreation of the dashboard? To do so would require the creation of some kind of [tombstone](https://en.wikipedia.org/wiki/Tombstone_(data_store)). But that raises new questions, e.g., how do we show the existence of such tombstones in the UI, so that the user can manage them?

This is a rabbit hole, and i'd prefer we not descend. Rather, unless there's some burning use case here i'm unaware of, i'd prefer that we accept this wart as it is and defer fixing it properly to our plans for a new API and object/metadata model.

If indeed such a use case exists (@pkolyvas?), we can reopen.

**Comment by samjewell** [comment]
@sdboyer thanks for your explanation here.

> This is a rabbit hole, and i'd prefer we not descend
I take your point here, but I wonder isn't there even a small improvement we could make here? Such as improving the docs to acknowledge that this doesn't work and we're not fixing it, or disallow the `disableDeletion` option (and either log a warning or an error that it will be ignored) when parsing a dashboard provisioning file?

I'm left wondering whether I should spend time logging bugs such as this in future: A few times recently I've come across some weird and unexpected behaviour with provisioning and creation/deletion of objects such as dashboards and datasources. I believe these to be bugs, but I'm not sure, and I'm also not sure if it's worth logging them even if they are bugs, given that it sounds like we have some improvements coming down the track soon:
> our plans for a new API and object/metadata model
Can you say any more on this topic, or link to any further docs around our plans?

**Comment by samjewell** [comment]
> what happens the next time provisioning is run (at Grafana startup)

Well we also have a flag `allowUiUpdates` which can be set to `true`. So I would follow the precedent that we set there, whatever it is, so that we are at least consistent. ie. Do UI updates get overwritten or not when provisioning next runs, and what are the implications?

**Comment by sdboyer** [comment]
> I wonder isn't there even a small improvement we could make here?

Certainly, yes, there are probably at least some basic steps we could take. Improving the docs around them seems a reasonable step, at least - cc @achatterjee-grafana. (Reopening for that)

> Well we also have a flag allowUiUpdates which can be set to true.

Unfortunately, another property that just wades into this multiple-writers-split-brain problem situation. That one will need to go the way of the dodo, too. (Perhaps leave that as-is to not break existing workflows people may have made, but yeah, it's ultimately not what we want)

> I believe these to be bugs, but I'm not sure, and I'm also not sure if it's worth logging them even if they are bugs,

I do feel bad, you did a great job with this bug report - which i very much appreciate! - and i'm just squashing it, here. My guess, though, is that we'd be best served by a running list of briefly-described problems.

> Can you say any more on this topic, or link to any further docs around our plans?
Yes - not public (though it'd be great if we could get them there), but [this one](https://docs.google.com/document/d/1Zjj2nSP5-XX8oxU3F67-cFcvXdbCg0-3mtYfvgC264k/edit) talks a lot about the multiple-writers problem, though it's better to start from [this one](https://docs.google.com/document/d/1EOF20CFgTsBZ5ijykgkrGyOdAaUvRBVcWJVk39eaAl8/edit#).

**Comment by marefr** [comment]
I think there might be confusion around the `disableDeletion` property. Based on [documentation](https://grafana.com/docs/grafana/latest/administration/provisioning/#reusable-dashboard-urls):
> By default, Grafana deletes dashboards in the database if the file is removed. You can disable this behavior using the disableDeletion setting.

The way to delete provisioned dashboards currently is to delete them from disk. I've tried to reproduce using the latest commit from the main branch and I always get below behavior:
![image](https://user-images.githubusercontent.com/1668778/143086008-e45fd8bb-79a4-42ab-ba8a-1611c713c89d.png)

@samjewell in addition I think you might have a configuration error in your yaml files:
We have no official support for provisioning a single file, see documentation which refers to directory (path): https://grafana.com/docs/grafana/latest/administration/provisioning/#dashboards

This might be the reason you're seeing the Delete Dashboard button for some provisioning dashboards and some not. 

Would suggest you to try something like this:
```yaml
apiVersion: 1

providers:
- name: 'disableDeletion: false'
  orgId: 1
  type: file
  disableDeletion: false
  allowUiUpdates: true
  options:
    path: /opt/homebrew/var/lib/grafana/plugins/disableDeletion-false
- name: 'disableDeletion: true'
  orgId: 1
  type: file
  disableDeletion: true
  allowUiUpdates: false
  options:
    path: /opt/homebrew/var/lib/grafana/plugins/disableDeletion-true
```

Then put your  `disableDeletion-false.json` in `disableDeletion-false` directory and `disableDeletion-true.json` in `disableDeletion-true` directory.

**Comment by sdboyer** [comment]
That makes considerably more sense, thank you @marefr!

**Comment by samjewell** [comment]
> I've tried to reproduce using the latest commit from the main branch and I always get below behavior:

Thanks @marefr for looking into this. I had been running 8.2.2, so I tried 8.2.5 and 8.3.0, but I can still reproduce. Note that to reproduce I found I needed **both of these lines together:**

```yaml
  disableDeletion: false
  allowUiUpdates: true
```

(If I remove `allowUiUpdates: true` then I can no longer reproduce)

I haven't tried with `main` yet - I was hoping that by downloading the nightly build of 8.3.0 today I would at least be running a more recent build than your last message 9 days ago.

Thanks for your other comments, that's helpful ❤️

**Comment by marefr** [comment]
> Note that to reproduce I found I needed **both of these lines together:**

I'm pretty sure I tried that, but someone would need to investigate that to verify. 

> We have no official support for provisioning a single file, see documentation which refers to directory (path):

I'm basing that on the documentation solely, but maybe @bergquist who built provisioning from the beginning can provide some context around this?

**Comment by wbrowne** [comment]
>Dashboard with disableDeletion: false should be deletable

As @marefr mentioned, this isn't the case unfortunately @samjewell. I think the main issue here is that the frontend should really reflect the rule by not showing/greying out the delete dashboard button as no matter what the setting - if the dashboard is provisioned, you can only delete it by removing the provisioning file currently.

**Comment by samjewell** [comment]
I know it's been ages, but just wanted to say thanks for your help on this issue ❤️
