### ISSUE TITLE
[Feature Request] Panel time affected by Value Mapping

### ISSUE THREAD

**Issue by imReker** [grafana/grafana#41099]
**What happened**:
Get wrong time when unix timestamp matches Value Mapping.

**What you expected to happen**:
Time is not affected by Value Mapping.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set a big Range Value Mapping, e.g., 1000-9635389520000 map to text 'HIGH'.
2. Time in the panel displayed as 'HIGH'.

**Environment**:
- Grafana version: Grafana v8.2.2-39068 (183fe28769)
- User OS & Browser: Windows 11 Edge

**Comment by zuchka** [comment]
Thanks for creating this issue, @imReker 

Yes, I see the behavior. Here is a dashboard where value mapping has overwritten a timestamp:

https://play.grafana.org/d/jDwXddKnz/value-mapping-a-range-overwrites-timestamps?orgId=1

![CleanShot 2021-10-29 at 17 11 55@2x](https://user-images.githubusercontent.com/37156449/139518318-06c9aa50-b7c3-42ee-8c82-15fa7f81b2da.png)

**Comment by hugohaggmark** [comment]
Thanks for reporting this @imReker and thanks for repro @zuchka. Would you both expect the time values to be excluded from all value mappings? I'm just trying to figure out what you expect from this issue?

**Comment by imReker** [comment]
> Would you both expect the time values to be excluded from all value mappings?
In my opinion, the default Value Mapping settings should exclude the Time, because:
1. It's 'value' mapping. Time(underlying unix timestamp),  intuitively is not a `value`.
2. It's rare to map a exact time stamp (value/range) to some other thing.

Can we default exclude Value Mapping to Time, and allow users manually add an Value Mapping override to Time values to keep the compatibility with the old behavior.

**Comment by hugohaggmark** [comment]
@imReker aha, you mean that this used to work before? Can you identify which Grafana version when this stopped working?

**Comment by imReker** [comment]
No, the 'old' I mean the current behavior, which is Value mapping applied to Time.

**Comment by hugohaggmark** [comment]
I see ok, I'm converting this issue to a discussion so we can better track it.
