### ISSUE TITLE
Move template variables to title bar to save some vertical space

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#4109]
Hello,

Could we think about moving template defined variables to the title bar in order to save some vertical space ?
As shown in the screenshot below :

![screenshot](https://cloud.githubusercontent.com/assets/6764151/13214662/4eb9b544-d951-11e5-8748-a810d7c8e9b1.png)

Thank you very much :+1: 

Ben

**Comment by torkelo** [comment]
<img width="1265" alt="screen shot 2016-02-22 at 11 13 32" src="https://cloud.githubusercontent.com/assets/10999/13215405/5f41f6ca-d955-11e5-9fb2-42d417e2080e.png">

There is no room for them there :(
