### ISSUE TITLE
Influxdb response_parser.go raising "index out of range" error

### ISSUE THREAD

**Issue by wsgomes** [grafana/grafana#41103]
I noted some errors on log after upgrading from 7.5.7 to 8.2.2 (with legacy alert system).

`t=2021-10-28T18:54:03+0000 lvl=eror msg="Alert Panic" logger=alerting.engine error="runtime error: index out of range [-3]" stack="[engine.go:181 panic.go:1038 panic.go:90 response_parser.go:117 regexp.go:699 regexp.go:634 regexp.go:698 response_parser.go:102 response_parser.go:81 response_parser.go:41 influxdb.go:146 core_plugin.go:81 manager.go:301 instrumentation.go:40 instrumentation.go:69 manager.go:300 data_plugin_adapter.go:63 tsdb.go:242 service.go:68 query.go:195 query.go:53 eval_handler.go:37 engine.go:192]"`

`t=2021-10-28T18:54:03+0000 lvl=eror msg="Alert Panic" logger=alerting.engine error="runtime error: index out of range [1] with length 1" stack="[engine.go:181 panic.go:1038 panic.go:90 response_parser.go:117 regexp.go:699 regexp.go:634 regexp.go:698 response_parser.go:102 response_parser.go:81 response_parser.go:41 influxdb.go:146 core_plugin.go:81 manager.go:301 instrumentation.go:40 instrumentation.go:69 manager.go:300 data_plugin_adapter.go:63 tsdb.go:242 service.go:68 query.go:195 query.go:53 eval_handler.go:37 engine.go:192]"`

I found the following code as source of errors:

https://github.com/grafana/grafana/blob/6232fe07c089b86b9485b3b08282a0237ddb367d/pkg/tsdb/influxdb/response_parser.go#L116-L118

Note `>=` should be `>` in order to avoid "index out of range" error.
Im not sure something else must be changed for properly fix.

**EDIT: Adding further information:**

The image below shows how to reproduce this error:
![image](https://user-images.githubusercontent.com/2425134/139600200-e1d838c1-1455-40df-bb3c-ae4e76c0a2f8.png)

Then test the alert rule:
![image](https://user-images.githubusercontent.com/2425134/139600450-cc79f67a-8d24-4007-896b-b9526702afcc.png)

Error on UI:
![image](https://user-images.githubusercontent.com/2425134/139600467-38a1deda-f0ac-4734-a640-09a24253bc5a.png)

Somehow, this ALIAS field may give the "pos" variable in the code above.
If the alias field is "Test -1", the pos variable will be -1 which will raise index out of range [-1].
I tested it using positive and negative numbers. I only get no errors for 0 and 1.

It seems like some problem with regex logic:

https://github.com/grafana/grafana/blob/6232fe07c089b86b9485b3b08282a0237ddb367d/pkg/tsdb/influxdb/response_parser.go#L18-L20

https://github.com/grafana/grafana/blob/6232fe07c089b86b9485b3b08282a0237ddb367d/pkg/tsdb/influxdb/response_parser.go#L100-L118

Also happens row.Name contains dot ("Test 1.5") which splitted the string on line 100.
Im not sure this is the intended behaviour.

Using InfluxQL (not Flux) to query data.

Hope this helps

**EDIT 2: Adding further information:**

It seems like this is the expected behaviour:
https://grafana.com/docs/grafana/latest/datasources/influxdb/#alias-patterns
So it seems like regex is getting everything, not only words with "[[", "]]" or "$".

**Comment by wsgomes** [comment]
Edited with further information.

**Comment by wsgomes** [comment]
Edited with further information.

@dsotirakis 
I noted you changed the regex rule in https://github.com/grafana/grafana/pull/39185
I think this may have introduced this bug. Could you please check?

**Comment by dsotirakis** [comment]
Hello @wsgomes, thanks for catching that!

I think the error lies here: 
> So it seems like regex is getting everything, not only words with "[[", "]]" or "$".

Text aliases without `[[`, `]]`, or `$` should work. The error seems to be on the regular expression. I'll raise a PR for it.

**Comment by wsgomes** [comment]
Hi @dsotirakis, thanks for prompt action.

At first glance, I though the `index out of range` error was caused by `>=` in code below.
When `len(nameSegment) == pos`, we have this error too.
https://github.com/grafana/grafana/blob/6232fe07c089b86b9485b3b08282a0237ddb367d/pkg/tsdb/influxdb/response_parser.go#L116-L118

Do you think it should also be changed?

**Comment by dsotirakis** [comment]
Can you post an example of when does this happen?

**Comment by wsgomes** [comment]
Sure!

We have a measurement named `ABAQ Frio -3.5C`.
If I give alias `Test [[2]]` or `Test $2`, I get `index out of range` error.

ALIAS > METRIC
`Test [[0]]` > `Test ABAQ Frio -3`
`Test [[1]]` > `Test 5C`
`Test [[2]]` > `index out of range` error
`Test [[3]]` > `Test [[3]]`

The above happens the same when using `$`

Note this measurement name has a dot (`.`) which leads to string split on line 100.
I'm not sure this is the intended behaviour but it impacts the `nameSegment` variable.

I could not find this rule in docs about `[[number]]` or `$number`.

**Comment by wsgomes** [comment]
@dsotirakis Do you think I should open a new issue for this?
I noted 8.2.3 was released without this fix even though it was added to 8.2.3 milestone (now deleted).

**Comment by dsotirakis** [comment]
@wsgomes, yeah `8.2.3` release was an one-change patch release, I'll try to make sure these changes will fly to `8.2.4`!
You can open a new issue yes!
