### ISSUE TITLE
Add a button in the title bar to show / hide template variables

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#4110]
Hello,

This issue is another idea to try to solve #4109.
What about a new button in the title bar, next to the settings button for example, which would show / hide template defined variables ?
This would allow to save some vertical space.

<img width="857" alt="screenshot" src="https://cloud.githubusercontent.com/assets/6764151/13215568/8f5897c8-d956-11e5-83a8-fa2b2a7f3603.png">

Thank you very much :+1: 

Ben

**Comment by bergquist** [comment]
ref https://github.com/grafana/grafana/issues/2420

**Comment by benrubson** [comment]
These are complementary requests yes :+1:

**Comment by torkelo** [comment]
closing in favor of #2420
