### ISSUE TITLE
Series specific override affect the wrong setting

### ISSUE THREAD

**Issue by ashb** [grafana/grafana#4111]
Rather than try to explain it I cpatured a screengif of it:

![grafana_0 10_series_specific_overrides](https://cloud.githubusercontent.com/assets/34150/13215814/0d23f01e-d950-11e5-95e7-2c1eb4115446.gif)

I'm not sure if this a bug or just counter to my expectations but it seems that many of the overrides end up setting "Legend: $n" instead of the setting I expect.

So far this behaviour I've seen with trying to set the following overrides:

- Stacked true/false
- Stack A..D most of the time. I managed to get it once, but I can't get it working now again.
- Point Radius 1..5

What i was trying to do was have this total value not be stacked with the rest.

Grafana 2.6 with Influx 0.10.0

**Comment by torkelo** [comment]
fixed in master / grafana 3.0 pre release builds

**Comment by ashb** [comment]
:+1:

**Comment by JeanFred** [comment]
(For reference, I believe this was #3554)
