### ISSUE TITLE
Unified Alerting - Alert continues to fire if no data returned.

### ISSUE THREAD

**Issue by ehuggz** [grafana/grafana#41128]
**What happened**:
Created a unified alert using Azure Log Data Source Kusto Query
Kusto Query (where "APIM API STACK" and "CallbackURL" obfuscated):

dependencies
| where $__timeFilter(timestamp)
//| timestamp > ago(3d)
| where operation_Name == "<APIM API STACK>;rev=1 - upload-cpp"
| parse data with * "POST - " _activity "<Callback URL?brand=" _brand "&region=" _region "&sub=" _subscription
| summarize AggregatedValue=count() by _brand, timestamp

With "Configure no data and error handling" options both set to OK 
![2021-10-30_16-03-36](https://user-images.githubusercontent.com/544939/139557186-86bd4ee2-e86e-4fb6-986e-775f81a5ac32.gif)
And Query B triggered when returned value is greater than 0
![2021-10-30_16-16-37](https://user-images.githubusercontent.com/544939/139557299-290bf728-0c72-41c9-bf1d-3de4747c53df.gif)
Alert fires when first response occurs and then continues to fire when no data rows are returned from the Kusto Query
![2021-10-30_15-55-21](https://user-images.githubusercontent.com/544939/139557187-f15a46df-7ae8-42aa-a54d-2703e4130369.gif)

**What you expected to happen**:
Alert to fire when count>0 and stop firing when no data returned at next eval time.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert based on an Azure LogAnalytics or Application Insights Kusto query which returns no rows when condition is not present.
**Anything else we need to know?**:
Setting Evaluate to:

- Every 5m for 10m
- Every 5m for 5m
- Every 5m for 1m
Exhibits the same behavior

Editing the Alert Rule and saving it will sometimes resolve the alert, only to have it reoccur later.

**Environment**:
- Grafana version: Graphana Online 8.2.2 with Unified Alerting Flag enabled.
- Data source type & version:
- Azure Log Analytics or Application Insights
- OS Grafana is installed on: Online
- User OS & Browser: MIcrosoft Edge Version 95.0.1020.30
- Grafana plugins:
- Others:

**Comment by davidmparrott** [comment]
@ehuggz is this still happening? We've made a lot of [changes](https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-3-0-beta2/) to how NoData and Error states are handled, starting with 8.3, and I'd like to see if you're still encountering this issue

**Comment by yuri-tceretian** [comment]
I could not reproduce this behavior in my instance. @ehuggz can you please try to reproduce it in 8.3+. Also, if you succeed, can you please check what annotations mention?

**Comment by grobinson-grafana** [comment]
I'm going to close this issue as we haven't heard back! However please feel free to re-open the issue if there are further updates.

**Comment by grobinson-grafana** [comment]
I'm going to close this issue as we haven't heard back in a while. However, please feel free to re-open the issue if there are further updates!
