### ISSUE TITLE
Add 'RPM' as a unit of measurement

### ISSUE THREAD

**Issue by cbbs70a** [grafana/grafana#4113]
It would be very helpful if there was a unit of measurement for 'RPM' for measurements of things like sensor data for fans. I know its equivalent to 'Hertz' but it is not as descriptive.

**Comment by sslupsky** [comment]
+1 

FYI, RPM is **not** equal to Hertz.  Also, Hertz should be categorized as velocity or angular velocity along with RPM.

Other suggested units and categories:

Force units:
1. Pounds-Force (lbs)
2. Kilograms-Force (Kg)
3. Newton (N)
4. Kip
5.  G-Force (G)


Pressure units:
1. Megapascal (MPa)
2. Ksi
3. Kilograms-force per square cm
4. Torr (Torr)
5.  Standard atmosphere (atm)
6.  Pascal (Pa)


Area units:
1. Square metre (m²)
2. Square millimetre (mm²)
3. Square kilometre (km²)
4. Square feet (ft²)
5. Square mile (mi²)


Energy units:
1. millivolt (mV)
2. microvolt (µV)
3. milliampere (mA)
4. microampere (µA)
5. nanoampere (nA)
6. picoampere (pA)


Electrical units:
1. farad (F)
2. millifarad (mF)
3. microfarad (µF)
4. nanofarad (nF)
5. picofarad (pF)
6. henry (H)
7. millihenry (mH)
8. microhenry (µH)
9. ohm (Ω)
10. milliohm (mΩ)
11. kiloohm (KΩ)
12. megaohm (MΩ)


Weight units:
1. microgram (µg)
2. milligram (mg)
3. gram (g)
4. kilogram (kg)
5. tonne (t)
6. ounce (oz)
7. pound (lbs)


Length units:
1. microstrain (µ𝜖)
2.  feet


Magnetism units:
1. Tesla (T)
2. Gauss (G)
3. Weber (Wb)
4. Maxwell (Mx)
5. Oerstead (Oe)

**Comment by evanbreznyik** [comment]
I would say why not make units configurable just like datasources (but with the defaults given plus the extra ones you specify perhaps)?

Great list of extra units, by the way.

**Comment by samhatchett** [comment]
Units are hard to do well and exhaustively. Existing libraries are probably a better bet than re-inventing this wheel - Math.js seems pretty extensive: http://mathjs.org/docs/datatypes/units.html

Functionally speaking, it would perhaps be better to allow the user to specify their own units string, and automatically use the k/M/P/T ... prefixes to ease readability. Grafana isn't really doing dimensional analysis, so full-fledged unit support seems overkill. A list of unit strings for convenience (what is now offered) is nice, but will probably never be complete - there are just too many units to cover. For example in my industry sometimes people measure flow rate in terms of "acre-ft per day", but listing that archaic unit string would be a distraction for someone setting up monitoring for db i/o.

// also for reference, the complete guide to units: http://www.nist.gov/pml/wmd/pubs/upload/AppC-12-hb44-final.pdf

**Comment by torkelo** [comment]
this was added some time ago

**Comment by nebula-it** [comment]
Do you know which version this was added, I was not able to find 'rpm' in  v5.1.3 (087143285). (The rpm exists for reads per minutes but nor for revolution per minute) 
Thanks

**Comment by shred** [comment]
Can someone with proper permission please re-open this issue?

**Comment by torkelo** [comment]
Grafana 6.6 has custom units so you can add any unit you want

**Comment by Hipska** [comment]
Okay, but You said "this was added", so I assumed that You were talking about "Rotations per minute (RPM)".

**Comment by shred** [comment]
There is a "read per minute" unit, which also abbreviates to RPM, and could be used as "rotation per minute" even though it's technically something different.

The latest Docker image is 6.5.2, so I am still missing the custom units feature. If it's coming with 6.6, it's okay for me then. :smile:
