### ISSUE TITLE
Is Elasticsearch still a valid backend for dashboard storage?

### ISSUE THREAD

**Issue by winbatch** [grafana/grafana#4114]
We are currently using the sqllite backend but would like to improve our resiliency.  In the documentation it's a little unclear of whether we can still use ES to store the dashboards: 
http://docs.grafana.org/installation/migrating_to2/

Also, this document indicates:

elasticsearch: {
    type: 'elasticsearch',
    url: "http://my.elastic.server.com:9200",
    index: 'grafana-dash',
    grafanaDB: true,
  }

Is there a way to configure that via the Grafana GUI?  I didn't see anything that equates to grafanaDB: true.

**Comment by winbatch** [comment]
Sorry, just saw this:
https://github.com/grafana/grafana/issues/3491

Unfortunately, the grafana documentation still lists it as a valid option, leading to confusion:
http://docs.grafana.org/install/

**Comment by bergquist** [comment]
That page seems to be broken..
Show grafana 1.9 as latest.

**Comment by torkelo** [comment]
Elasticsearch is not available as dashboard storage
