### ISSUE TITLE
SingleStats Color Thresholds not working

### ISSUE THREAD

**Issue by 9arriflex9** [grafana/grafana#4115]
Hello Guys,

We are using Grafana 2.5.0 with the Zabbix Plugins.
I'm having trouble using the Single State Color Thresholds
The Thresholds is set to 100,95,90 but it always stay Green

Here is a Screenshot of the Single Stats config
[http://i.imgur.com/qoWfxzI.png](url)

I tried in our DEV(2.6.0) environements too and I get the same result

**Comment by bergquist** [comment]
The singlestat panel is assuming the order small -> large. 

rearrange the thresholds to 90, 95, 100 and click the invert order text and it should work :)
