### ISSUE TITLE
Expired silences are NOT removed after 5 days

### ISSUE THREAD

**Issue by zoltan-fedor** [grafana/grafana#41156]
**What happened**:
Expired silences are not removed after 5 days, see screenshot.
The screenshot was taken on Nov 1st, 2021, which is well over 5 days past the expiration of some of these silences, so they should have been removed.

![2021-11-01_11-53](https://user-images.githubusercontent.com/3887295/139701038-1bc52c86-db9c-4e8f-8210-00e6c1dd7f0c.png)

**What you expected to happen**:
I expect the expired silences to be removed after 5 days - just like the message states.

**How to reproduce it (as minimally and precisely as possible)**:
Create any silences, let them expire and wait 5 days to see them NOT being removed.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Official Grafana Docker image 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by cbos** [comment]
In 8.3 we also have the same issue. Expired silences are NOT cleanup after 5 days (even not after 2 months).

**Comment by armandgrillet** [comment]
5 days is the retention set https://github.com/grafana/grafana/blob/4e3a72fc2aa0fb9749e7648e035b08b651ad0637/pkg/services/ngalert/notifier/alertmanager.go#L161 thus there is definitely a bug here or we do not understand how the expiration is computed leading to the bug. 

We should also make this retention personalizable for users.

**Comment by joeblubaugh** [comment]
@armandgrillet I've opened a separate issue for: 
> We should also make this retention personalizable for users.

Here: https://github.com/grafana/grafana/discussions/46676
