### ISSUE TITLE
grafana and elasticsearch 1.x vs 2.x in the datasource

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4116]
If i set the elasticsearch version to 1.x (even though I have 2.x installed), everything works fine
However, if i change the version to 2.x, I end up getting an error related to the time as shown in the attachment

![image](https://cloud.githubusercontent.com/assets/7545534/13226190/34557884-d95e-11e5-8d07-43a8fec932ca.png)

**Comment by torkelo** [comment]
If you have old indices created by Elasticsearch 1.x you need to keep the version at 1.x (or update the old indice mappings)

**Comment by eben23** [comment]
i have tried deleting the old indices completely every time, but the same issue
