### ISSUE TITLE
kubernetes plugins report not support for latest  version

### ISSUE THREAD

**Issue by Duanjax** [grafana/grafana#41173]
**What happened**:
I installed kubeneter plugins in my local server, and my grafana version is 8.2.2, but I still get this warning this plugin doesn't support your version of Grafana.

![image](https://user-images.githubusercontent.com/86959085/139784393-6f219aa0-1088-4035-9459-1dfadc8ce97d.png)

![image](https://user-images.githubusercontent.com/86959085/139784426-3d0199de-1dba-4f2f-a3c2-45cc901095ef.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- 
![image](https://user-images.githubusercontent.com/86959085/139784174-13a138a2-0047-43ce-8940-754545e05c0e.png)

- Data source type & version:
- OS Grafana is installed on:
- installed  on ubuntu
- User OS & Browser:
- Grafana plugins:
- kuberneters-grafana-app
- Others:

**Comment by mckn** [comment]
Thanks for reporting this issue. A couple of follow up questions.

- Have you installed this plugin via the grafana-cli?
- What is the "not found" 404 screen shot you have supplied in the issue?
- The warning is valid. We can not for sure know that the plugin works in Grafana 8 since it has not been updated since version 5.

**Comment by Duanjax** [comment]
Hi @mckn,  thanks for looking into this issue.

1. - Have you installed this plugin via the grafana-cli?
   Yes, I installed this plugin via grafana-cli. 

2. - What is the "not found" 404 screen shot you have supplied in the issue?

 I get this  404 page when I click  the   left side  kubenrnetes  app. 

![image](https://user-images.githubusercontent.com/86959085/140253662-9190f114-4aad-4276-b58a-d769031c917d.png)
3. - The warning is valid. We can not for sure know that the plugin works in Grafana 8 since it has not been updated since Grafana version 5.

Does it mean I can try Grafana having lower versions, but why this plugins hits "Dependances: Grafana >=5.0+".  It doesn't make sense it requires higher version but it not support higher version since is has not been update since Grafana version 5.

**Comment by mckn** [comment]
> Does it mean I can try Grafana having lower versions, but why this plugins hits "Dependances: Grafana >=5.0+". It doesn't make sense it requires higher version but it not support higher version since is has not been update since Grafana version 5.

No, you are correct. This is a bug with how we format the dependency. In this case it should be 5.0.x and nothing else.
There are other plugins that you can use to add Kubernetes support to Grafana.

https://grafana.com/grafana/plugins/grafana-kubernetes-app/

**Comment by Duanjax** [comment]
Yeah, The plugin I used is as you mentioned, https://grafana.com/grafana/plugins/grafana-kubernetes-app/

I use the conmand: grafana-cli plugins install grafana-kubernetes-app
You can see the plugins list I have installed
![image](https://user-images.githubusercontent.com/86959085/140452996-a58f1141-4943-4421-8b71-acb374df8433.png)

I think the question here is  why this plugin doesn't work. Whether my Grafana has some issues not this plugin?

**Comment by mckn** [comment]
So the reason is that this plugin is incompatible with Grafana versions newer then 5.0.x.

However we have this plugin that hopefully does what you want: https://grafana.com/grafana/plugins/devopsprodigy-kubegraf-app/
