### ISSUE TITLE
MySQL: Lacks documentation about SSL/TLS options

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#41182]
Lacks documentation about [SSL/TLS options](https://grafana.com/docs/grafana/latest/datasources/mysql/#data-source-options).

![image](https://user-images.githubusercontent.com/1668778/139818538-8b1f4457-a160-4873-bebe-bb9c2a2dbdb5.png)

Would also be good to include an [example of provisioning](https://grafana.com/docs/grafana/latest/datasources/mysql/#configure-the-data-source-with-provisioning) using SSL/TLS.

**Comment by codeincarnate** [comment]
Have a PR up that addresses this 😄, see #64122
