### ISSUE TITLE
Error while trying to authenticate user: LDAP Result Code 200 "": x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by dccsp92** [grafana/grafana#4118]
I am trying to get the ldaps authentication to work but with or without setting the root_ca_cert in the ldap.toml find I get the error "Error while trying to authenticate user: LDAP Result Code 200 "": x509: certificate signed by unknown authority"   It seems like it is not either seeing the root_ca_cert definition or not using it.  I have verified the file and path do exist on the local server, verified the certificate is not expired, verified it is a trusted root CA on the AD ldap server and verified the correct server certificate is on the ldap server itself.  What am I missing?

**Comment by torkelo** [comment]
is your root CA in the right locations on the server? Others have been able to use ldap and self signed / and CA signed SSL certs so it is likely that your root CA are not in the right place on the server (not sure exactly where that is, not a SSL linux expert)

**Comment by dccsp92** [comment]
You were on the right track.  I am running this on Ubuntu so in my case I had the file in the correct /etc/ssl/certs directory but just placing in there doesn't make it trusted.  I had to actually move the file to /usr/share/ca-certificates with a .crt extension, add the file to /etc/ca-certificates.conf, then run the 
update-ca-certificates command and then specify the /etc/ssl/certs/my_CA_certificate.pem file in the ldap_toml file.  When you run the update-ca-certificates it links the crt certificate file to a pem extension.
Thanks for the direction!
