### ISSUE TITLE
grafana-server sudden memory spike that leads to OOM event

### ISSUE THREAD

**Issue by Imoustak** [grafana/grafana#41192]
**What happened**:
We are running Grafana as a standalone VM(EC2) on AWS. Since some days ago we are experiencing a recurring issue with sudden memory spikes. While the normal memory usage is below 1G at certain times during the day(which don't appear to be following a pattern) we see a sudden huge spike in memory that consumes the whole memory of the server(16G) and brings the server down. Any pointers on how to debug or proceed to resolve this would be more than useful since it happens multiple times per day currently.

This is what we see in our monitoring tool when this happens:
![Screenshot 2021-10-29 at 08 50 15](https://user-images.githubusercontent.com/13902948/139843161-0f05d505-2e11-4362-9982-8af840d0232a.png)

`grafana-server` process memory when this happens:

![Screenshot 2021-10-29 at 15 22 12](https://user-images.githubusercontent.com/13902948/139843296-b54e1cde-106f-4dbd-a183-b9eb50546b64.png)

What we have tried so far:
* Double the server's memory from 8G to 16G and we still experience the same issue which points to something else.
* Upgrade Grafana version from 8.1.3 to 8.1.7
* Enable debug logging (but we didn't spot anything particular so far)

**What you expected to happen**:
grafana-server process doesn't run into this huge memory usage spike and brings down the server.

**How to reproduce it (as minimally and precisely as possible)**:
Since we haven't been able to figure out the root cause of this I don't have a way to reproduce it in another system at the moment.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.1.7
- Data source type & version: PostgreSQL 11, Timestream, CloudWatch, Google Sheets, InfluxDB, ClickHouse
- OS Grafana is installed on: 
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic

- Grafana plugins:
installed plugins:
ae3e-plotly-panel @ 0.3.3
grafana-googlesheets-datasource @ 1.0.1
grafana-image-renderer @ 2.0.0
grafana-timestream-datasource @ 1.1.0
ilgizar-candlestick-panel @ 0.0.1
natel-plotly-panel @ 0.0.7
vertamedia-clickhouse-datasource @ 2.3.1
- Others:

**Comment by dsotirakis** [comment]
Hello @Imoustak, thanks for raising the issue!
* Do you have any logs that we can have a look at? Are they descriptive?
* Which was the first Grafana version where you noticed this happened?
* Do you happen to run heavy queries? Can you post them as well?

**Comment by Imoustak** [comment]
Hello @dsotirakis,

Thanks for the quick response. We noticed it on  8.1.3 then we upgraded to 8.1.7 to see if this solves it but we still see this. I am attaching the logs from the minute we experienced the issue(although I can't spot anything wrong there):

[grafana_logs.txt](https://github.com/grafana/grafana/files/7463288/grafana_logs.txt)


In the meantime, we identified one problematic dashboard that we changed last week and we could reproduce the issue when we open it. Basically every time we open this dashboard the memory usage of `grafana-server` process skyrockets and crashes the server.

Since we removed the panels we don't observe the issue so far.

This is the json difference of the previous version of the dashboard with the panels that we removed:
[grafana_problematic_panels.txt](https://github.com/grafana/grafana/files/7463332/grafana_problematic_panels.txt)

Do you spot anything problematic there? It's still not clear to us why this is happening. Thanks again for your time and help

**Comment by dsotirakis** [comment]
👋 
Nothing obvious to me.
@marefr, something that comes up from the top of your head? 🤔

**Comment by marefr** [comment]
Based on a very quick look at the logs the following request stands out since it seems to return ~7mb of data:
t=2021-11-02T17:07:00+0000 lvl=info msg="Request Completed" logger=context userId=34 orgId=1 uname=jan@test method=POST path=/api/ds/query status=200 remote_addr=X.X.X.X time_ms=1061 size=8015178 referer="https://grafana.test.io/d/ldD-R-4nz/ddd_deep_dive?orgId=1"

> This is the json difference of the previous version of the dashboard with the panels that we removed:

I don't see them as problematic, however could depend on how many rows are being returned from each query so would suggest investigating that.

**Comment by Imoustak** [comment]
Yes, it was actually this dashboard that was causing this. When we removed the new panels we don't observe this anymore. Thanks for looking into it guys, I am closing this since our issue is solved
