### ISSUE TITLE
Aliasing broken with InfluxDB 0.10.x ?

### ISSUE THREAD

**Issue by jwmarshall** [grafana/grafana#4120]
Unable to use any aliasing (eg $tag_host or [[tag_host]]) with InfluxDB 0.10.x. Note that I am adding the data source into grafana as an influx 0.9 type.

Everything else seems to work as expected though.

**Comment by torkelo** [comment]
did you group by tag also?

**Comment by jwmarshall** [comment]
Ahh, yes that was the missing bit! Thank you!!
