### ISSUE TITLE
Accessibility: Fix fastpass issues for core datasource config pages and query editors

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#41206]
As part of the ongoing accessibility improvements, we've been going through Grafana's various pages and fixing and accessibility issues reported by [fastpass](https://chrome.google.com/webstore/detail/accessibility-insights-fo/pbjjkligggfmakdaogkfomddhfmpjeni?hl=en).
The following is a list of core datasources that have some accessibility issues with their query editor and/or datasource configuration page. When the issues are fixed for a particular editor or config page, update the list with a link to the corresponding PR. If you'd like to assign yourself to a particular datasource, insert your avatar next to the relevant heading.

### [Azure Monitor](https://github.com/grafana/grafana/issues/41902) ![avatar](https://github.com/sarahzinger.png?size=24) @grafana/cloud-datasources 
- [x] #41902 
### [Cloudwatch](https://github.com/grafana/grafana/issues/40915) ![avatar](https://github.com/fridgepoet.png?size=24) @grafana/cloud-datasources 
- [x] #42705
- [x] #42706
### Elasticsearch  ![avatar](https://github.com/elfo404.png?size=24)
- [x] #42707
- [x] #42708
### [Google Cloud Monitoring](https://github.com/grafana/grafana/issues/41907) ![avatar](https://github.com/andresmgot.png?size=24) @grafana/cloud-datasources
- [x] #42709
- [x] #42710
### Graphite
- [x] Query Editor (https://github.com/grafana/grafana/pull/42532) (https://github.com/grafana/grafana/pull/42556)
- [x] #42711 (#43333)
### Influx
- [x] #42712
- [x] #42713
### Jaeger ![avatar](https://github.com/connorlindsey.png?size=24)
- [x] #42714
- [x] #42715
### Loki ![avatar](https://github.com/ivanahuckova.png?size=24)
- [x] Query Editor https://github.com/grafana/grafana/pull/42664
- [x] Configuration *(no issues in Loki code, some issues in alerting + derived field section)*
### MSSQL
- [x] #42716 (https://github.com/grafana/grafana/pull/43981)
- [x] #42717 (https://github.com/grafana/grafana/pull/43982)
### MySQL
- [x] #42718 (https://github.com/grafana/grafana/pull/43981)
- [x] #42719 (https://github.com/grafana/grafana/pull/43982)
### OpenTSDB (https://github.com/grafana/grafana/pull/43714)
- [x] #42720
- [x] #42721
### Postgres
- [x] #42722 (https://github.com/grafana/grafana/pull/43981)
- [x] #42723(https://github.com/grafana/grafana/pull/43982)
### Prometheus ![avatar](https://github.com/ivanahuckova.png?size=24)
- [x] Query Editor https://github.com/grafana/grafana/pull/42671
- [x] Configuration https://github.com/grafana/grafana/pull/42671
### Tempo ![avatar](https://github.com/connorlindsey.png?size=24)
- [x] #42724
- [x] #42725
### Zipkin ![avatar](https://github.com/connorlindsey.png?size=24)
- [x] #42726
- [x] #42727

**Comment by natellium** [comment]
🕺🏻
