### ISSUE TITLE
Select influxdb database on query editor

### ISSUE THREAD

**Issue by wgrcunha** [grafana/grafana#4121]
Hello,

I have a infrastructure with many databases on influxdb to separate kinds of data, with this i need to create one datasource per database, its possible to add on query editor the database selection?

Thanks!

**Comment by torkelo** [comment]
security is per database in InfluxDB, so this will likely not be added to query editor. You can use policies instead (which you can select in query editor in Grafana 3.0 (master))

**Comment by wgrcunha** [comment]
Thanks!

Another question, when i select "Mixed" on the datasource i can mix different datasources queries on the same chart. But i cannot change the datasource of one query (i need to remove and add another query from the right datasource). My question is: Is possible to use grafana templating to select datasource?

![image](https://cloud.githubusercontent.com/assets/596745/13408432/8ca7a5ee-df0c-11e5-9738-024ecb225026.png)

tyvm!

**Comment by torkelo** [comment]
No that is not possible  :(
