### ISSUE TITLE
Cloudwatch Bug: Access and Secret Key input fields broken

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#41211]
**What happened**:
I'm on the main branch and tried to set up a new Cloudwatch datasource and couldn't type anything in the access or secret keys

**What you expected to happen**:
I would expect to be able to type in these fields

**How to reproduce it (as minimally and precisely as possible)**:
Add a new cloudwatch datasource and select access and secret key

**Comment by ryantxu** [comment]
ha!  was about to file the same bug!

**Comment by sarahzinger** [comment]
@ryantxu just made this fix if you want to take a look https://github.com/grafana/grafana/pull/41215
