### ISSUE TITLE
convert epoch second  to wrong timestamp

### ISSUE THREAD

**Issue by RobinChiu** [grafana/grafana#41231]
**What happened**:
add a table panel and use postgresql data source.
select -482302590 as number, -482302590 as time, to_timestamp(-482302590), 1 as value

**What you expected to happen**:
time and timestamp will be the same value.
But it will show 
number         time                            to_timestamp                value
-482302590  **1969-12-26 18:01:37  1954-09-19T19:03:30Z**  1

It looks like the epoch convert in the grafana has some bug. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.2
- Data source type & version: postgresql12
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Win10 & chrome
- Grafana plugins:
- Others:

**Comment by RobinChiu** [comment]
I found if the number is big enough, the time will be correct. If number is small, it will be "ms", but if number is big enough, it will be "second". It will cause the $__timeGroup(timestamp,"1s",0)) return the wrong time. If we set the fillvalue in the $__timeGroup, grafana will try to fill the value between correct and wrong time. It will cause the OOM.

**Comment by dprokop** [comment]
@RobinChiu before we investigate this, can you try out latest version of Grafana? I see you are on 7.5.2.

**Comment by RobinChiu** [comment]
> @RobinChiu before we investigate this, can you try out the latest version of Grafana? I see you are on 7.5.2.

I tried the latest version 8.2.3. The problem is still there. 
select 86400 as number , 86400 as time, to_timestamp(86400) as timestamp

![2021-11-08 151909](https://user-images.githubusercontent.com/7788730/140699755-a2f0a6d0-297c-4126-9d36-67cdcc4d0b98.png)

If I use the $__timeGroup, I will get the wrong time. "1970-01-01 08:01:26"

with data as (
select 86400 as number , 86400 as time, to_timestamp(86400) as timestamp
)
select $__timeGroup(timestamp, '1s', 0) as time from data

**Comment by oscarkilhed** [comment]
Using a mysql datasource:
`select -482302590 as number, -1000000000 as time, 1 as value`
returns the same as 
`select -482302590 as number, -1000000000000 as time, 1 as value`

So it's not only the PostgreSQL ds that has this weird behavior.

**Comment by kirederik** [comment]
Spent some time investigating this one. Here's what I found:

- the `number as time` portion is handled by the front-end
  - We use MomentJs’s `moment.utc()` to [format time](https://github.com/grafana/grafana/blob/b8852ef6a3cbd476dc990509107e2e701d189c3c/packages/grafana-data/src/datetime/formatter.ts#L93-L107)
    - This function expects an [epoch in milliseconds](https://momentjs.com/docs/#/parsing/unix-timestamp-milliseconds/)
  - the `to_timestamp(number)` is handled by the back-end
  -   Postgres `to_timestamp` expects number to be [epoch in seconds](https://www.postgresql.org/docs/10/functions-datetime.html#FUNCTIONS-DATETIME-TABLE)

We could use `moment.unix` on the front-end but this may cause problems for folks that currently expect time to be in milliseconds. A few other datasources handle the `as time` conversion in the back-end -- I'll look at that next.

**Comment by kirederik** [comment]
OK, after some further investigation, I'd say this one is working as intended, although the docs could be clearer.

If your column contains unix epoch in seconds, you can use `extract` function as follows:

```
SELECT  extract(epoch from to_timestamp(-482302590)) as time
> 1969-12-26 07:01:37

SELECT -482302590 as time
> 1969-12-26 07:01:37
```

You can also take a look at the `$__timeEpoch` and `$__time` macros.

**Comment by kirederik** [comment]
> Using a mysql datasource: `select -482302590 as number, -1000000000 as time, 1 as value` returns the same as `select -482302590 as number, -1000000000000 as time, 1 as value`
> 
> So it's not only the PostgreSQL ds that has this weird behavior.

This happens because our [sql engine](https://github.com/grafana/grafana/blob/main/pkg/tsdb/sqleng/sql_engine.go#L839)  makes a call when transforming number literals to time: if it fits in 32bits, it considers the time to be in seconds; therefore it needs to be transformed to milliseconds prior to the date conversion. If it requires a 64bits integer, it considers it to already be in milliseconds. I guess we'll have some problems in [2038](https://en.wikipedia.org/wiki/Year_2038_problem) 👀
