### ISSUE TITLE
Feature request: set different time zones per each graph

### ISSUE THREAD

**Issue by nucleusv** [grafana/grafana#4123]
Would be great to set different time zones per each graph. 
Zabbix stores data in UTC, but we are in Moscow, but servers are in US. It is better to debug by servers local time.

**Comment by smalik03** [comment]
+1

**Comment by torkelo** [comment]
you can set timezone in dashboard settings

**Comment by nucleusv** [comment]
Reopen please.

In dashboard settings there are only 2 options: browser and UTC tomezones.

My browser timezone is Europe/Moscow, zabbix stores data in database in UTC, but my servers are in US and I need to see graphs in US timezone  EST. 

So a datasource should return data in UTC, 

+ add to dashboard ability to set timezone http://www.timeanddate.com/time/zones/ for all graphs on dashboard, and Grafana should convert time from datasource according to the dashboard settings

+ add to graph settings ability to overwrite dashboard timezone setting

**Comment by pierluca** [comment]
+1

We have a use case where Grafana is used to display graphs for distributed systems (think internet-of-things) and the values are only meaningful with local (user) time, as opposed to UTC.

By forcing everything in UTC (or browser's time), we're effectively comparing apples and oranges, as at a given time, we'll be seeing some system adopt its "night" behaviour and another its "morning" behaviour with no time shift.

**Comment by santhosbaala** [comment]
+1

**Comment by yriahi** [comment]
+1

**Comment by Codelica** [comment]
As flexible and customizable as Grafana is, this is the only thing that's caught me by surprise.  I think this should be re-considered as well.  Being able to display information in its native time zone it key for our use as well.

**Comment by bergquist** [comment]
I'm reopening this. I can see how this can be useful but I'm not sure about how this should be implemented.

**Comment by torkelo** [comment]
There is an older issue for this already, #558, maybe  a bit different as this asks for option per panel

**Comment by bergquist** [comment]
I think per panel could be really helpful when visualizing application/business metrics. Makes it much easier to consume the information from different time zones in one dashboard.

Graphs of support calls last 2h/requests/sold items in each timezone would very easy to understand.

**Comment by grajeshwaran** [comment]
+1

**Comment by aop** [comment]
+1

**Comment by Punkoivan** [comment]
+1

**Comment by tammytankian** [comment]
+1

**Comment by flopp999** [comment]
I just had kind of same problem, I have data from a time zone that is +2 from my time.
I found a work around, where you set Time range, From To, you can use FROM:Now-2h TONOW+3h.
This will show you data for 5 hours. If you want to see last hour local time of the system(in my case +2 from me) I wrote From:now+1h To:now+2h

**Comment by Punkoivan** [comment]
@flopp999 the problem is when you use NOW-2h you will get what you ask - NOW-2h, but with different TimeZone it should be EXACTLY the same time (the same moment since Unix Epoch) but only in different TimeZone.

**Comment by aryabchenko** [comment]
+1

**Comment by alexkot** [comment]
+1

**Comment by vukomir** [comment]
+1

**Comment by DavidFlamini** [comment]
+1

**Comment by mssanchez** [comment]
+1

**Comment by asafl** [comment]
+1

**Comment by leo-combes** [comment]
+1
In our case, we have a server in the USA and customers in different time zones. Everyone gets a chart with the USA time, when they would like to see them in their own time zone.
Therefore, the ideal would be to have each graph with a configurable time deviation according to its destination time zone.

**Comment by Eraac** [comment]
Sad this is still not implemented, my use case is pretty the same, I've dashboard with multiple panel, one panel (request rate) per load balancer (which are in multiple timezone), that will be such more pleasant to read with the local time of the load balancer
