### ISSUE TITLE
Cell Display Gauge Renderer length wrong

### ISSUE THREAD

**Issue by comtel2000** [grafana/grafana#41239]
**What happened**:
The cell display renderer does not behave proportionally to the underlying values.

![image](https://user-images.githubusercontent.com/2266347/140030677-08fda8a9-7aff-4244-8367-85c8a59c9f49.png)

json view:
![image](https://user-images.githubusercontent.com/2266347/140030526-82c79fb7-abb7-4c83-8fb1-f3d8016c2efb.png)

**What you expected to happen**:
The length/relation of the rendered gauge for a value like 6 must be twice as long as for the value 3

**How to reproduce it (as minimally and precisely as possible)**:
use the values:
![image](https://user-images.githubusercontent.com/2266347/140030526-82c79fb7-abb7-4c83-8fb1-f3d8016c2efb.png)

with TABLE visualization and a Cell Display Mode:
Gradient, LCD or Basic Gauge

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian (Buster)
- User OS & Browser: Windows/Chrome
- Grafana plugins: - 
- Others: -

**Comment by joshhunt** [comment]
I can understand the source of confusion, but this is working as designed. The min/max of the bar charts are based on the values in the table. So for your data, a gauge width of 0 represents a value of 2.7 as that is the minimum value in data.

If you want 3 to be half the width 6, you'll need the min value in the panel options to 0

![image](https://user-images.githubusercontent.com/46142/140314425-961a1072-b20c-450d-98b8-be3047ceae55.png)

**Comment by joshhunt** [comment]
Check out this sample dashboard to see this in action https://play.grafana.org/d/sB4cRPFnz/41239-bar-gauge-length

**Comment by comtel2000** [comment]
thx, totally make sense now.
