### ISSUE TITLE
generic_oauth by wechat  Scan QR code error

### ISSUE THREAD

**Issue by marklinglon** [grafana/grafana#41242]
![image](https://user-images.githubusercontent.com/18097531/140038428-d2d4285d-0aeb-4b75-af62-c4c8c7295abe.png)
![image](https://user-images.githubusercontent.com/18097531/140038492-ebff4491-0a71-41c1-86f0-058449d36b5d.png)
![image](https://user-images.githubusercontent.com/18097531/140038578-f5234861-163d-4c70-a0ef-cdfa604965b8.png)
error:
1.Failed to look up user based on cookie
2.user token not found
3.login.OAuthLogin(NewTransportWithCode)
4."Post \"\": unsupported protocol scheme \"\"
Are these bugs?

**Comment by dsotirakis** [comment]
Hello @marklinglon, could you provide some more information please and fill the empty fields in the issue description?
Like which Grafana version you are using, OS and such?

Thanks!

**Comment by marklinglon** [comment]
grafana/grafana:8.2.2

**Comment by ashharrison90** [comment]
hi @marklinglon 👋 

it's hard to determine whether this is a valid bug or a configuration error without all the information. if you can fill in the bug template as clearly and completely as possible it will help us to route this to the correct team.

you can find the bug template under issues -> new issue -> bug report. copy the entire template and edit your original post [here](https://github.com/grafana/grafana/issues/41242#issue-1043307050), filling in as much of the template as possible. 

thanks!

**Comment by marklinglon** [comment]
I have resolved it by proxy wechat.

**Comment by ashharrison90** [comment]
glad to hear! thanks for letting us know. 👍 
in the future, feel free to close the issue and leave a comment explaining.

thanks! 😄

**Comment by NNNaix** [comment]
How to fix it? I hava same problem.
