### ISSUE TITLE
NewsPanel: Issue with layout in 8.2 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#41256]
Seeing buggy layout with news panel in 8.2 on play (date), not seeing it in main:
https://play.grafana.org/d/z3yVbLFnk/news-panel-layout?orgId=1
![Screenshot from 2021-11-03 12-46-31](https://user-images.githubusercontent.com/10999/140054560-ac4c4233-77fe-4b03-8a3e-501a7b342f4b.png)

**Comment by torkelo** [comment]
@ashharrison90 I think you fixed this in https://github.com/grafana/grafana/pull/40016 but did not backport it,

**Comment by ashharrison90** [comment]
fixed by https://github.com/grafana/grafana/pull/41260
