### ISSUE TITLE
Grafana showing No Metrics - Api errrors from chrome developer

### ISSUE THREAD

**Issue by GastroGee** [grafana/grafana#4125]
I have a RHEL 6 on which my grafana and graphite run and i use a netapp-harvest as data collector. My new CDOT netapp clusters have perf metrics showing up on my dashboard with no issues; over the weeken i added old 7mode controllers to graphite for performance monitoring.

Grafana dashboard shows no metrics at all for the 7mode controllers while the clustered netapp controllers are just fine.

Graphite webapp however recieves the metrics from the netapp harvest because i can see them when i expand the poller folder and choose the 7mode controllers. The problem looks to be some problem on the grafana dashboard.

When i try to view the request from a chrome developer, i get a api/ datasource/ render (unathorized) error.

Has anyone seen a similar issue

Thanks in advance

**Comment by bergquist** [comment]
What grafana version are you using? 
Are you using direct access or proxy access?

If you are using direct access. Have you setup the "Access-Control-Allow-Origin: *" in graphite?

**Comment by GastroGee** [comment]
grafana is 2.1.3

and i have all those rules in place in graphite

I should also mention that only the 7mode controllers have no metrics; the Clustered OnTap cluster are fine

**Comment by torkelo** [comment]
did you specify the correct http url to you graphite server? Is it accessable from the grafana server? Did you specify access method proxy or direct when you added the datasource to grafana?
