### ISSUE TITLE
Bug in Master: Dashboard Link UI Broken

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4126]
Preview:

In Firefox:

<img width="1096" alt="screen shot 2016-02-23 at 12 52 08 am" src="https://cloud.githubusercontent.com/assets/1019609/13246326/d254f5be-d9c7-11e5-94cb-2736a926453f.png">

In Chrome:

<img width="1104" alt="screen shot 2016-02-23 at 12 52 37 am" src="https://cloud.githubusercontent.com/assets/1019609/13246332/de4f5a62-d9c7-11e5-969c-1fd6d2281821.png">

**Comment by bergquist** [comment]
closed by c189c2016438d7077ca4bc6b4b371bc346d1f966
