### ISSUE TITLE
Value mappings: selected colors not set correctly when using regex rules

### ISSUE THREAD

**Issue by vdwpsmt** [grafana/grafana#41265]
**What happened**:
colors of all values after the first regex mapping rule are set to the color in this first regex rule 

**What you expected to happen**:
colors following the regex rules

**How to reproduce it (as minimally and precisely as possible)**:
I used a default state time line panel in the [play.grafana](https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?from=now-12h&to=now&var-app=backend&var-server=backend_01&var-server=backend_03&var-interval=1h&orgId=1) environment
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: gdev-testdata
- OS Grafana is installed on:?
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

![image](https://user-images.githubusercontent.com/41926598/140065554-027c0625-3fd2-4fd5-b4fc-b1f581e4a358.png)

**Comment by torkelo** [comment]
@vdwpsmt try changing color scheme option (under Standard options) to Classic palette (something other than "From thresholds" )

**Comment by vdwpsmt** [comment]
@torkelo no succes changing the color scheme.
Reduced the panel to basic functionality.  this is the json of the panel:
[panel regex value mappings.txt](https://github.com/grafana/grafana/files/7472886/panel.regex.value.mappings.txt)

**Comment by vdwpsmt** [comment]
@mcdee I'm using this [feature ](https://github.com/grafana/grafana/pull/38931)but having trouble with the color option.  
Any idea what I'm doing wrong?

**Comment by ppozorski** [comment]
i've also notice that every next regex doesn't work if we want to pass the matched group to the "Display text" field
![Zrzut ekranu 2021-11-9 o 20 53 59](https://user-images.githubusercontent.com/37401474/140995160-e79bb81e-291a-49a4-a24d-d1ee8b6796b1.png)
.

**Comment by mcdee** [comment]
For anyone with this problem of regex colors not showing up, it appears that under 'Table/Cell display mode' you need to set it to 'Color text':

![screenshot_2021-11-09-213638](https://user-images.githubusercontent.com/511384/141009326-299ecf7b-f7c6-4706-a4b2-78d88143bc8b.png)

**Comment by mcdee** [comment]
@ppozorski please could you show the input data, and explain the expected output?  Thank you.

**Comment by mcdee** [comment]
Regarding the original issue, it appears that the state timeline is not running the display rules for regex; this can be tested by changing the `$1` replacement to a static string.  I'm afraid that I'm unsure where to look to understand the issue, however, as the regex rules code is separate from the display code.

**Comment by ppozorski** [comment]
Example:
Input: 8 679.38String
Output: 8 679.38
![Zrzut ekranu 2021-11-9 o 23 09 22](https://user-images.githubusercontent.com/37401474/141012856-1578fecd-a48d-4a0a-bb7c-45359c0e5c46.png)

And this is ok but for the other input with "Foo" text  I get a value with uncut text and also with "String" background:
![Zrzut ekranu 2021-11-9 o 23 14 30](https://user-images.githubusercontent.com/37401474/141013421-571afff8-add5-434e-a03b-6678411eb0bd.png)

**Comment by mcdee** [comment]
@ppozorski thanks.  Looks like any regexes beyond the first are being ignored.  I will take another look to see if I can understand what is going on here.

**Comment by ppozorski** [comment]
> Regarding the original issue, it appears that the state timeline is not running the display rules for regex; this can be tested by changing the `$1` replacement to a static string. I'm afraid that I'm unsure where to look to understand the issue, however, as the regex rules code is separate from the display code.

Yes, you are correct and after the replacement to static string it shows that the regex rule works only for the first definition.

**Comment by mcdee** [comment]
Thank you for the additional information.  A pull request has been raised that should address this issue.
