### ISSUE TITLE
Alerting Elasticsearch datasource error

### ISSUE THREAD

**Issue by binschlag** [grafana/grafana#41266]
I have configured Alert rules in Grafana which check data on my Elasticsearch datasource. Since beginning of August, as an Update was made to our Elasticsearch and Grafana tools, all this Alert rules don't work any more.
Alerts with other datasources work without any issues.

When testing an alert rule with elasticsearch, I get the following error message:

error:"request handler error: failed to query data: invalid character '<' looking for beginning of value"

**Comment by Elfo404** [comment]
hello @binschlag thanks for reporting this.
the issue is missing some information from the issue template, could you please tell us which version of Grafana are you using?
Also, the error makes me think there's is some issue on how the connection to the datasource is set up, could you please provide the full response as shown in the browser dev tools when pressing "save & test" in datasource settings?

**Comment by binschlag** [comment]
Hello @Elfo404 
thanks for your answer.
Grafana Version: Grafana v8.2.2 (6232fe07c0)

Here the full response of datasource settings:
`{"datasource":{"id":8,"uid":"000000008","orgId":1,"name":"ELK","type":"elasticsearch","typeLogoUrl":"","access":"proxy","url":"http://192.168.10.10/ES/","password":"","user":"","database":"[logstash-*]YYYY.MM.DD","basicAuth":false,"basicAuthUser":"elk","basicAuthPassword":"","withCredentials":false,"isDefault":false,"jsonData":{"esVersion":"7.10.0","includeFrozen":false,"interval":"Daily","logLevelField":"","logMessageField":"","maxConcurrentShardRequests":5,"timeField":"@timestamp","timeInterval":"5m","xpack":true},"secureJsonFields":{"basicAuthPassword":true},"version":19,"readOnly":false},"id":8,"message":"Datasource updated","name":"ELK"}`

I can see the data in the graph, but just alerts on this data don't work.
Thanks

**Comment by binschlag** [comment]
Hello @Elfo404 

you were right, I did some tests with different datasource settings and was able to solve this issue.
Still don't know, why original datasource was showing data but alerts were not working.

So it was a configuration issue and no bug.

Thanks.

**Comment by Elfo404** [comment]
Glad you solved it.
What happened is indeed strange though, if you notice something similar please feel free to let us know

**Comment by sewi-cpan** [comment]
@binschlag I encountered the same issue. Would be great to know how you solved it.
