### ISSUE TITLE
Cannot use grafana dashboard variables on Jaeger search query

### ISSUE THREAD

**Issue by qdesbiniobeya** [grafana/grafana#41273]
**What happened**: Dashboard defined variables are not interpolated on jaeger search query tags

**What you expected to happen**: Be able to use variables like other datasource queries :
![image](https://user-images.githubusercontent.com/80096044/140073433-9661bb45-6b5c-456b-93cf-bb96569015e4.png)

Where $host is a grafana dashboard variable

**How to reproduce it (as minimally and precisely as possible)**:
- Add a jaeger datasource to your grafana instance
- Add a variable on your grafana dashboard
- Add a "time series" panel, select "mixed" as datasource
- On the first "A" serie, select your jaeger datasource
- Try to use your variable on the tags field

KO : if we look on the query inspector we can see that variable is not interpolated:
```json
"request": {
    "url":"api/datasources/proxy/2/api/traces?service=my-service&tags=%7B%22http.url%22%3A%22%24host%22%7D&start=1635944383718000&end=1635947983718000&lookback=custom"
}
```

**Anything else we need to know?**: N/A

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: Jaeger
- User OS & Browser: Windows & Chrome
- Grafana plugins: only core plugins
- Others:

**Comment by dsotirakis** [comment]
@grafana/observability-squad, looping you in, not really sure if you are responsible for it 🙏

**Comment by srclosson** [comment]
Made a very simple change and wrote a test. Awaiting review.

**Comment by srclosson** [comment]
Implemented, and merged

**Comment by msetbar** [comment]
I am having the same issue in grafana 11.3.

**Comment by robocanic** [comment]
> I am having the same issue in grafana 11.3.

me too, is there a solution?

**Comment by maximnik** [comment]
I am experiencing the same issue with Grafana 11.4.0. When I try to use a variable in the Tag search, it does not interpolate correctly.

**Comment by zoltanbedi** [comment]
Hey this is fixed in https://github.com/grafana/grafana/pull/103399 which you can find in version 12.1.0 behind a feature toggle `jaegerBackendMigration`.
