### ISSUE TITLE
Variables behind "?" in Data Source URL are not send to the Server

### ISSUE THREAD

**Issue by benks-io** [grafana/grafana#41276]
**What happened**:
The URL provided to the json Datasource Addon GrafanaJsonDatasource will be requested from the json server without the query string after `?`

**What you expected to happen**:
Request the whole URL that is provided by the Plugin.

**How to reproduce it (as minimally and precisely as possible)**:

- Install GrafanaJsonDatasource
- Add a datasource `https//foo.bar/data.php?format=json`
- Check the Server Logs on `foo.bar`. They only show the request of `https//foo.bar/data.php` and not the full url with the variable.

**Anything else we need to know?**:
This was already mentioned in the GrafanaJsonDatasource repo:
https://github.com/simPod/GrafanaJsonDatasource/issues/213

**Environment**:
- Grafana version: Grafana v8.2.3 (fb85ed6912)
- Data source type & version: 
- OS Grafana is installed on: debian
- User OS & Browser: firefox
- Grafana plugins: GrafanaJsonDatasource

**Comment by papagian** [comment]
Given that for most of the `simPod/GrafanaJsonDatasource` endpoints the url [is concatenated](https://github.com/simPod/GrafanaJsonDatasource/blob/54c8f8e66310adbb7a72380b63d239dc6341c931/src/DataSource.ts#L128) with a subpath without considering any query parameters, I believe that this is rather a datasource issue than a grafana one.
![Screenshot 2021-11-08 at 11 57 38 AM](https://user-images.githubusercontent.com/1632407/140721695-70b20352-0bb9-4029-bf44-bdca8554dae4.png)

Regarding [SON API data source for Grafana](https://github.com/marcusolsson/grafana-json-datasource), according to [this](https://github.com/marcusolsson/grafana-json-datasource/issues/8#issuecomment-733526928) query parameters in the URL would be possible.
