### ISSUE TITLE
Grafana is not able to pull all the records from elasticsearch

### ISSUE THREAD

**Issue by NavneetMathpal** [grafana/grafana#4128]
Hi,

When I am trying to pull the rawdocuments in table from elasticsearch , It does not show me the all the documents which are available there in elasticsearch index . no matter how many docs are there in my elasticsearch index , it shows <=1000 docs.

I guess when Grafana is firing the query for getting the docs . It is fixing the document size in query , and not using [scan and scroll ](https://www.elastic.co/guide/en/elasticsearch/guide/1.x/scan-scroll.html).
 
Is there some way possible, from where I can increase the size of documents which are getting retrieved from elasticsearch .

**Comment by torkelo** [comment]
do you want to scroll through more than 1000 docs? You can specify a search filter in the lucene box

**Comment by NavneetMathpal** [comment]
@torkelo  could you pls let me know what query needs to be specify in search filter ?
can you give some example ?

**Comment by NavneetMathpal** [comment]
@torkelo  I have tried , but how search filter will resolve the issue of getting all the records ?
In lucene box I can specify some queries like -  country:london , but query for scrolling all the records , I am not getting this .

**Comment by grantzhanghao** [comment]
Hello, I met the same problem as you, did you resolve it?  also, is there a method to get user by user name?
Thank you.

**Comment by ntsiam** [comment]
Why is this issue closed? Why doesn't it make sense to need more than 10000 docs?
