### ISSUE TITLE
Cannot set different min/max or scale for the same unit.

### ISSUE THREAD

**Issue by laundmo** [grafana/grafana#41282]
**What happened**:

When setting 2 axis to the same unit (in my case `ppm` as we measure different gases) only one min/max override has some effect, the other one gets ignored.
![grafik](https://user-images.githubusercontent.com/24855949/140087894-674a0bce-772a-41e8-9db9-53f4aed20a4d.png)
This image contains test data where the amounts happened to be close together since both devices were measuring the same gas at this time.

**What you expected to happen**:

I expected to get 2 axis with different min/max scales

**How to reproduce it (as minimally and precisely as possible)**:

1. make a line panel with 2 series
2. override both series units to `ppm`
3. override 1 series to a max of `100` and the other to a max of `5`

**Anything else we need to know?**:

This is currently the reason we cannot upgrade our main grafana instance, since we need panels with the same unit on a vastly different min/max.

Related: 
- https://github.com/grafana/grafana/discussions/38242
- https://github.com/grafana/grafana/discussions/39619

This is filed as a bug report due to the addition of min/max not working in this situation.

A workaround for this is simply having different units, though in our case we measure the exact same unit with different ranges.

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: MySQL
- OS Grafana is installed on: Docker on Raspi OS
- User OS & Browser: Windows 10 + Firefox
- Grafana plugins: None

**Comment by ashharrison90** [comment]
not sure if this is a bug or feature request tbh... 🤔 

i'm erring on the side of bug since it works if the units are different, so seems strange that it wouldn't work for the same units

**Comment by dprokop** [comment]
I would consider this a feature request @ashharrison90 . We have one feature request that's indirectly related but boils down to a similar thing on how we treat axis/scales for the same unit: https://github.com/grafana/grafana/issues/41282

**Comment by dprokop** [comment]
I'm gonna close this as a duplicate.

**Comment by laundmo** [comment]
> I would consider this a feature request @ashharrison90 . We have one feature request that's indirectly related but boils down to a similar thing on how we treat axis/scales for the same unit: #41282

you linked to this exact issue...

i would argue this is definite a bug, since there is a config option that by all means should work, and did work in Grafana 7, but just doesn't have any effect.

**Comment by dprokop** [comment]
> > I would consider this a feature request @ashharrison90 . We have one feature request that's indirectly related but boils down to a similar thing on how we treat axis/scales for the same unit: #41282
> 
> you linked to this exact issue...
> 
> i would argue this is definite a bug, since there is a config option that by all means should work, and did work in Grafana 7, but just doesn't have any effect, namely the min/max setting for an axis. What makes this even more confusing is that it works when you do it for just one axis, and its not consistent which setting it uses.

My bad, I meant https://github.com/grafana/grafana/issues/38810, sorry about that @laundmo!

I cannot promise when exactly this will be fixed, but we will make our best to address this in the near future.
