### ISSUE TITLE
dashboard sharing via local snapshot loses entire metrics

### ISSUE THREAD

**Issue by markuspatrick** [grafana/grafana#4129]
Hi,
using the option sharing dashboards via local snapshot leads to a lost of metrics.

The pictures below shows the full dashboard.

![full_dashboard](https://cloud.githubusercontent.com/assets/13067413/13248125/08f99e9e-da1d-11e5-94d7-4c8cde1e6937.jpg)

The next picture shows the result after sharing. The two metrics in right bottom corner are replaced by the grafana test metrics. All Dashboards use the same datasource (so its not a access problem for the datasource). The test metrics are only shown if the user has a account in our grafana. External users (without an account) only see an error message (same to #4076). The problem does not depend on the choice of expire date for the (local) snapshot - it happens in every case. 

![shared_dashboard](https://cloud.githubusercontent.com/assets/13067413/13248254/9d051820-da1d-11e5-9a86-3e86020afa69.jpg)

Is it a bug or a problem in our grafana instance?
We use grafana 2.6.0 on an ubuntu its 14.4 

Cheers, 
Markus

**Comment by markuspatrick** [comment]
I forgot something. Its pure coincidence, which metrics an how many metrics are getting lost in the local snapshot. It differs from snapshot to snapshot...

**Comment by torkelo** [comment]
related to this issue, https://github.com/grafana/grafana/issues/2537
