### ISSUE TITLE
Document overriding systemd option `ProtectHome=true` for installs that use directories in `/home`

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#41299]
**What happened**:
If data directory is located under `/home`, Grafana can't read `/home` directory, and cause launch error.

**What you expected to happen**:
Grafana can launch without error.

**How to reproduce it (as minimally and precisely as possible)**:
Set data path, and launch Grafana.
```
[paths]
data = /home/grafana
```

**Anything else we need to know?**:
The change is introduced in https://github.com/grafana/grafana/pull/38109 .
According to [doc](https://www.freedesktop.org/software/systemd/man/systemd.exec.html), systemd reject `/home` access if `ProtectHome=true`.
> If true, the directories /home/, /root, and /run/user are made inaccessible and empty for processes invoked by this unit.

When I overwrite the setting by [drop-in](https://www.freedesktop.org/software/systemd/man/systemd.unit.html), I can launch Grafana.

If Grafana still use `ProtectHome=true`, this issue should be noticed in the document.

**Environment**:
- Grafana version:
  - 8.2.3
- Data source type & version:
- OS Grafana is installed on:
  - Linux (Ubuntu bionic)
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kminehart** [comment]
Yes this is intended as this is a non-standard install. Typically data directories fall under `/usr` or `/var`.

In order to rectify this, you can add the option `ProtectHome=false` in the systemd config, however I'd recommend creating an override file:

```bash
systemctl edit grafana-server
```

This will open the override file in your configured `$EDITOR`.

Add this text into that box to disabled `ProtectHome`.

```
[Service]
ProtectHome=false
```

**Comment by askdba** [comment]
This works!

**Comment by chri2547** [comment]
Closing at the install docs have recently gone through a rewrite.
