### ISSUE TITLE
Alias Pattern, InfluxDB: response_parser.go raising "index out of range" error

### ISSUE THREAD

**Issue by wsgomes** [grafana/grafana#41290]
I found a bug in [alias pattern](https://grafana.com/docs/grafana/latest/datasources/influxdb/#alias-patterns) rules that raise `index out of range` error.
Although not in documents, alias patterns `[[number]]` and `$number` work like an index for measurement name splitted by dot.

![image](https://user-images.githubusercontent.com/2425134/140166217-509c7622-1d61-421a-a039-1d021fa2b325.png)

This bug happened to me when evaluating alerts (can be simulated by clicking `Test rule` in Alert tab)

![image](https://user-images.githubusercontent.com/2425134/140167061-bda83cc9-2e0b-48cf-b5a8-2a09bf4ead4c.png)

`Test $0` alias will produce `Test ABAQ Frio -3` metric as result.
`Test $1` alias will produce `Test 5C` metric as result.
`Test $2` alias will produce `index out of range` error.
`Test $3` alias will produce `Test $3` metric as result.

![image](https://user-images.githubusercontent.com/2425134/140168373-9b7aec72-15ba-4440-9486-acbe8b78dcd3.png)
`runtime error: index out of range [2] with length 2`

Note: If measurement name does not have a dot, the error happens for `Test $1`.

This is where this bug happens in code (note `>=` instead of `>`):

https://github.com/grafana/grafana/blob/6232fe07c089b86b9485b3b08282a0237ddb367d/pkg/tsdb/influxdb/response_parser.go#L116-L118

Splitting measurement name by dot seems weird to me.
Maybe it has another use case.

This issue is a complement for https://github.com/grafana/grafana/issues/41103 resolved by @dsotirakis

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: InfluxDB (default version from Grafana 8.2.2)
- OS Grafana is installed on: Linux (Grafana image from Docker Hub)
- User OS & Browser: Windows 11 & Chrome
- Grafana plugins: default only
- Others: using clean Grafana image from Docker Hub (grafana/grafana:8.2.2)

**Comment by wsgomes** [comment]
Just noted another impact... see below.

![image](https://user-images.githubusercontent.com/2425134/140324977-4d155d5d-ca57-4aab-b1b7-69f1c74a2393.png)

![image](https://user-images.githubusercontent.com/2425134/140325012-0666ad43-f447-43e0-9856-595ae46c1456.png)

**Comment by gabor** [comment]
hi @wsgomes , thank you for the detailed report, we will fix this. 

> Splitting measurement name by dot seems weird to me. Maybe it has another use case.

it was originally implemented in https://github.com/grafana/grafana/commit/ead451a97987e49b417ff57944f7d70ef4f6d5f2 , if you want to read more about the context of why this exists.

we will update the documentation too (it is available in the help-window that you get when you click on the question-mark next to the datasource-name in a dashboard, but it is not currently in the docs-on-the-website)

**Comment by wsgomes** [comment]
hi @gabor, good to know! thanks!
