### ISSUE TITLE
Docs feedback: /variables/advanced-variable-format-options.md

### ISSUE THREAD

**Issue by jameskirsop** [grafana/grafana#41297]
This page should include details on `:date:<FORMAT>` options, which are currently missing documentation elsewhere in the Grafana docs except for a passing reference on a small number of pages such as the one for [adding Global Variables](https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__from-and-__to).

**Comment by osg-grafana** [comment]
@jericvizmanos writes internally, ... for the [advanced variable format options page](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#text) ... [How does one use] the key when setting up `key : value` pairs in custom variables. We were able to make it work with `${variable:text}`.
