### ISSUE TITLE
8.2.3 release tag shows as 8.2.2

### ISSUE THREAD

**Issue by smijolovic** [grafana/grafana#41293]
looks like 8.2.3 release was cut before all of the changelogs and versions were merged - build and changelogs all show as 8.2.2.

**Comment by zoltanbedi** [comment]
This should be ok now.

**Comment by smijolovic** [comment]
Still reporting 8.2.2 within the last 10 minutes - the branch still shows all 8.2.2 changelogs and version numbering.

**Comment by zoltanbedi** [comment]
I've seen that the changelog changes were not backported, thanks for letting us know. Which version numbering is not changed? Can you give me a link?

**Comment by smijolovic** [comment]
Sure - in the tag tree for 8.2.3:
https://github.com/grafana/grafana/tree/v8.2.3

If you scroll through all of the comments for the last updates, you will see all are referencing 8.2.2. When comiled, packaged, and deployed, the frontend UI still shows the version as 8.2.2.
