### ISSUE TITLE
Elasticsearch: Add Cumulative Sum Aggregation (Pipeline Agg)

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4130]
i have a series that shows, say, the count of visitors over every 10 minutes
now i want to get the cumulative sum plotted
i understand i need to use pipelines for elasticsearch, but only see Derivative or Moving Average.

Any ideas on how to handle this?

**Comment by eben23** [comment]
anyone has any ideas pls?

**Comment by eben23** [comment]
mind adding a cumulative for elasticsearch datasource pls

**Comment by eben23** [comment]
will this be part of grafana 3.0?

**Comment by eben23** [comment]
the grafana 3.0 looks great 
thx for the effort in this

any idea when the cumulative feature will be available?

**Comment by greg-peterson** [comment]
+1

**Comment by kongfei605** [comment]
+1 
i try grafana 4.2.0-pre1, it  does not  support cumulative sum aggregation.

**Comment by daire-byrne** [comment]
+1
Being able to plot an integral of a time series is very useful.

**Comment by rucciva** [comment]
+1

**Comment by lpalm** [comment]
+1

**Comment by Jonathan-Rosenberg** [comment]
+1

**Comment by rodrigongarcia** [comment]
+1

**Comment by asamuta** [comment]
Any plans for implementing this?

**Comment by opsnull** [comment]
Any plans for implementing this?

**Comment by rakeshramakrishnan** [comment]
Any plans for implementing this? It will be very useful

**Comment by gustavomitt** [comment]
+1

**Comment by brjborja** [comment]
+1

**Comment by dnhodgson** [comment]
+1

**Comment by brjlpz** [comment]
+1

**Comment by wil-code** [comment]
I prepared some changes which solves this issue.

**Comment by marefr** [comment]
@wil-code interesting. Open a PR and we'll have a look at it. Thanks

**Comment by cristianprofile** [comment]
+1 It will be very usefull.

**Comment by brjlpz** [comment]
+1

**Comment by retzkek** [comment]
I have a (very simple) change ready with this, working to get approval from my employer to sign the CLA to open a PR
https://github.com/retzkek/grafana/commit/59d574eb9b92850b2a6041da2a6d121c05665327

![Screen Shot 2019-12-19 at 1 16 29 PM](https://user-images.githubusercontent.com/1627510/71203960-a34c9300-2264-11ea-96fe-2fd056f04c80.png)

**Comment by oraclecaicai** [comment]
+1

**Comment by pablok-parkling** [comment]
+1
