### ISSUE TITLE
Suffix "Copy" in dashboard name when saving even for the first time.

### ISSUE THREAD

**Issue by tecmatia-dp** [grafana/grafana#41312]
**What happened**:
Text " Copy" is always added to dashboard name, even when saving for the first time with a custom name.

**What you expected to happen**:
Add "Copy" only when saving a copy (Save as) of the dashboard, not the first time.

**How to reproduce it (as minimally and precisely as possible)**:
Create a dashboard.
Keep default name "New dashboard", or change it, result is the same.
Save dashboard. The name will appear with " Copy" suffix.

**Environment**:
- Grafana version: v8.2.3, but it happens also in previous versions.

**Comment by joshhunt** [comment]
Tested this out and confirmed the issue 👍🏻 

Thanks for the report @tecmatia-dp!
