### ISSUE TITLE
Error while docker building in 8.2.3

### ISSUE THREAD

**Issue by liketodev1** [grafana/grafana#41313]
![Screenshot_2](https://user-images.githubusercontent.com/54404116/140314547-467cdd95-7112-4a08-8eca-2b5f1ed18e89.png)

I'm getting this error   in docker build . -t grafana

**Comment by dsotirakis** [comment]
Hello @liketodev1, thanks for raising the issue.

Maybe https://github.com/grafana/grafana/pull/41281 fixes it? Let me follow on that.

**Comment by guicaulada** [comment]
I believe #41281 should fix this issue. 

From our investigation the issue only happens on linux/arm64 machines, like the M1.

Using the argument `--platform linux/amd64` will solve the issue, but it will also build the docker image for a different architecture.

If the issue persists let us know.
