### ISSUE TITLE
Cannot disable refresh from the URL

### ISSUE THREAD

**Issue by aramirezverbio** [grafana/grafana#41329]
**What happened**: Whenever I open a dashboard without the refresh parameter in the URL, it is automatically added with a value of '1m'. When I try something like `refresh=off`, the dashboard gets stuck loading (it shows a spinner and says "Services"). When I set the refresh rate to `Off` via the dropdown menu, the parameter is removed from the URL, but reloading this URL gets me back to the first case.

**What you expected to happen**: I expect `refresh=off` to load the dashboard with the refresh rate set to off.

**How to reproduce it (as minimally and precisely as possible)**:
Simply open a dashboard without the refresh parameter in the URL: https://mysite/d/rYdddlPWk/node-exporter-full?orgId=1
it will automatically be changed to
https://mysite/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=1m
and a URL like https://mysite/d/rYdddlPWk/node-exporter-full?orgId=1&refresh=off gets stuck loading.

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: Prometheus 2.30.3
- OS Grafana is installed on: Arch Linux on armv7l (Raspberry Pi 2B)
- User OS & Browser: Arch Linux on x86-64. Tried on Firefox 94.0 and Brave 1.31.88.
- Grafana plugins:None
- Others: This issue seems similar to https://github.com/grafana/grafana/issues/9016

**Comment by thisisobate** [comment]
Can confirm this bug on main

**Comment by thisisobate** [comment]
> When I set the refresh rate to **Off** via the dropdown menu, the parameter is removed from the URL, but reloading this URL gets me back to the first case.

@aramirezverbio Did you try saving your dashboard after setting the refresh rate via the dropdown?

**Comment by aramirezverbio** [comment]
I just tried and that seems to do the trick. After setting the refresh rate to Off via the dropdown menu and saving the dashboard the refresh rate remains disabled when it is not specified in the URL. This is a valid workaround for my particular use case, thank you.
However, the page still hangs when specifying "refresh=off" in the URL.

**Comment by hugohaggmark** [comment]
@aramirezverbio thanks for reporting this, we currently do not support the `refresh=off` in the url, in fact it breaks the dashboard loading because it's not a valid time range. I'm going to close this issue now because you have a valid workaround and we're trying to limit open GitHub issues in order to better track planned work and features.

![image](https://user-images.githubusercontent.com/562238/141243777-ddc88976-6db7-4e00-af20-807120802dcf.png)

Thank You to you for taking the time to create this issue!
