### ISSUE TITLE
3.0.0 Graph Y-axis doesnt honor decimals

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#4132]
Settings decimals doesnt get reflected on the Y axis (table and graph values are ok though)

![image](https://cloud.githubusercontent.com/assets/12600004/13256795/6d403a8c-da4c-11e5-9747-a6267a55e8a4.png)

**Comment by torkelo** [comment]
yes, y-axis decimals is calculated automatically, decimal option is for legend only. 

if you want to control the decimals in the graph in cases like yours set y  axis min or max
