### ISSUE TITLE
Alerting: special alert instance if evaluation results in state Error

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#41331]
Recently, we added a new feature to Grafana alerting: a special alert when evaluation results in NoData state and it is mapped to NoData. See #40540 for more details. Also, we changed the migration from legacy alerting for "no data" state mapping from "KeepLastState" -> "Alerting" to  "KeepLastState" -> "No Data".

However, the legacy alerting also provides the ability to map Error state to "Keep Last State" but the unified alerting does not have that option as well as option "Error", which makes it impossible to match the behavior we introduced for no data state.

I see two ways to solve it:
1. Add the option "Error" to the dropdown for mapping Error state, and implement the creation of the special instance the same way we did for NoData. 
Pros: we match the no data behavior. Simple. 
Cons: we give more options which can be confusing for users.

2. Remove the dropdown altogether and hardwire the Error state to the special alert. 
Pros: simplifies the implementation of alerting flow. Predictable behavior. 
Cons: unclear how bad it would be for migration from states like Ok and Alerting. 

cc @grafana/alerting-squad let's decide which way we should go.

**Comment by Jxlam-pdx** [comment]
@yuri-tceretian For the legacy system, do we know the percentage of time users map "error state" to "keep the last state"?

**Comment by gerobinson** [comment]
I think we should do the same as we did for `NoData`: create a special alert instance for this alert rule. It gives them more options but I don't think it will be more confusing because its behaviour will be consistent with what we did for `NoData`.
