### ISSUE TITLE
Panels don't update after changing time range

### ISSUE THREAD

**Issue by jonasbleyl** [grafana/grafana#41354]
**What happened**: Changing the time range for a dashboard has no effect on the panels after changing panel visualization.

**What you expected to happen**: All panels should update with the specified time range.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to https://play.grafana.org/d/000000012/grafana-play-home
2. Edit a panel and change visualization to Stat.
3. Click "Apply" and go back to main dashboard.
4. Change dashboard time range.

**Environment**:
- Grafana version: 8.2.3
- User OS & Browser: Chrome/Edge

**Comment by hugohaggmark** [comment]
I can reproduce this, but if you edit the same panel again and change the time range again and then click apply all panels seem to work again.

**Comment by ashharrison90** [comment]
issue is fixed on main, so will be released in the upcoming 8.3 release. 🥳
