### ISSUE TITLE
Embedding a Secured Grafana into Web Application

### ISSUE THREAD

**Issue by maximus2situation** [grafana/grafana#4136]
I want to embed Grafana into my web application using AngularJS. The goal is, when user is in my application, she should be able to click on a button and load the Grafana UI. In itself, this is an easy task. To do this, I have an apache proxying Grafana and returning any necessary CORS headers. The apache reverse proxy config is as follows:

`Header always set Access-Control-Allow-Origin "*"
Header always set Access-Control-Allow-Methods "POST, GET, OPTIONS, DELETE, PUT"
Header always set Access-Control-Max-Age "1000"
Header always set Access-Control-Allow-Headers "x-requested-with, Content-Type, origin, Authorization, accept, client-security-token"

RewriteEngine on
RewriteCond %{REQUEST_METHOD} OPTIONS
RewriteRule ^(.*)$ $1 [R=200,L]
RewriteCond %{REQUEST_METHOD} OPTIONS
ProxyPass / http://localhost:3000/`

All works perfectly fine wen no security is involved. The following code is a simple Javascript of what I am doing:

`
var app = angular.module(myApp', []);

app.controller('MainCtrl', function ($scope, $http, $sce) {

$scope.trustSrc = function(src) {
        console.log(src);
        return $sce.trustAsHtml(src);
}
$http({
        method : 'GET',
        url : 'http://grafana-host.com',

}).success(function(response) {
        $("#test").attr('src', 'http://grafana-host.com')
        $("#test").contents().find('html').html(response);

}).error(function(error) {
        console.log(error);
});

});
`

In the html part, I just call a simple iframe with Id='test' to have the expected result

The challenge now is that once logged in into my application, user should not have to log in into Grafana again.

To resolve this issue, I set up Grafana to use Basic Auth. My goal is for my web app to pass basic auth to Grafana via the browser. Basically, when the user clicks on the button to open Grafana, I would issue a request via AngularJS. This request would include the required Authorization header to load Grafana. To do this, I augment the above code segment with the http blog after the url field:

headers : { 'Authorization' : 'Basic YWRtaW46YWRtaW4=' }

Also, in the success callback function, I replace the first instruction with:

$("#test").attr('src',"data:text/html;charset=utf-8," + escape(response))

Unfortunately, I do not seem to be able to get this to work. I get a {{alert.title}}

I know this should work because I can simulate this behavior with ModHeader extension of Chrome browser. If I put the following header in ModHeader: Authorization: Basic YWRtaW46YWRtaW4=, it loads Grafana from without need to log in. And if I remove the Authorization header, I am prompted for login name and password again.

The grafana changes are pretty simple:

[auth.basic] enabled = true

What am I missing?

**Comment by bergquist** [comment]
Seems like the javascript for grafana is not loading. Grafana is also using angular and will replace and hide the {{alert.title}} text once the javascript is loaded. I hade no idea why they do not load.

If you can make it work it would be great but this is however not something that we aim to support. Im therefor closing this ticket since Grafana itself will not solve this problem.

**Comment by hemsush** [comment]
I am also facing similar issue. Ajax calls not loading
