### ISSUE TITLE
Grafana version 7.2.3 standalone Linux binary not available to download

### ISSUE THREAD

**Issue by tseplak** [grafana/grafana#41371]
*Note:* Technically not a bug in Grafana itself, please let me know if there's a better place to file this. 

**What happened**: 
I was running Ansible to install Grafana version 7.2.3 and received the following error:

```
{"changed": false, "msg": "Failure downloading https://dl.grafana.com/oss/release/grafana-7.2.3.linux-amd64.tar.gz, HTTP Error 404: Not Found"}
```

**What you expected to happen**:
A successful download of version 7.2.3. 

**How to reproduce it (as minimally and precisely as possible)**:
Run: `wget https://dl.grafana.com/oss/release/grafana-7.2.3.linux-amd64.tar.gz`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.2.3
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Amazon Linux 2 / N/A
- Grafana plugins: N/A
- Others:

**Comment by dsotirakis** [comment]
Hello @tseplak, thanks for raising the issue!

7.2.3 does only have a vulnerability fix for enterprise edition, and it wasn’t published since it’s exactly the same for OSS as 7.2.2. Please use that version!
