### ISSUE TITLE
Exemplars: Have way how to see all exemplars and not sample them

### ISSUE THREAD

**Issue by josephDunne** [grafana/grafana#41382]
**What happened**: plotting a histogram percentiles with exemplars only shows the first exemplar per time bucket

**What you expected to happen**: expected grafana to plot exemplars in the same way that prometheus does - with all exemplars visible

**How to reproduce it (as minimally and precisely as possible)**: create a latency histogram with multiple exemplars. exemplars have a single label trace_id.

**Anything else we need to know?**: Attached is the exemplar query response

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: Prometheus 
- OS Grafana is installed on: Linux
- User OS & Browser: Mac Os & Safari
- Grafana plugins:
- Others:

[query_exemplars.json.zip](https://github.com/grafana/grafana/files/7489006/query_exemplars.json.zip)

![prometheus](https://user-images.githubusercontent.com/1827457/140580286-5bab5951-6dbb-4332-8f16-f7e655d6fc87.png)
![grafana](https://user-images.githubusercontent.com/1827457/140580304-7b3c33ce-65f1-4b00-8047-582c3247a8cd.png)

**Comment by JokerQueue** [comment]
+1，I have the same problem,  is there any solution?

**Comment by JokerQueue** [comment]
while there are multi time series result, the exemplars are less and fixed and confuse, not binding to each time series. I think this is a bug.

**Comment by ivanahuckova** [comment]
Hello @josephDunne. Thank you for creating the issue. It is true that Grafana is not showing all exemplars and we are doing sampling on them. This way, the graph is not overflowing when you have thousands of exemplars. We do it here https://github.com/grafana/grafana/blob/main/pkg/tsdb/prometheus/time_series_query.go#L361-L422 and a lot of time this is very useful, but I can see your usecase and why you would like to see them all/not sample them. If it is okay with you, I'll change this to feature request/discussion and add open a discussion about if we should have option to not sample them, or sample them only if there is more than X number of exemplars.
