### ISSUE TITLE
Varible rendered not correctly for Loki expression

### ISSUE THREAD

**Issue by jeyrce** [grafana/grafana#41395]
**What happened**:

I  tried to create a dashboard for loki, found varibles takes no effect for LogQL expr.
![image](https://user-images.githubusercontent.com/33649388/140709698-a9e7f8b5-2c79-4c51-8efa-c545f5734c59.png)

then save the settings and open shared like in another page whit the varible `targetIP` value: 

```
http://10.10.168.77:60014/grafana/d/80chRic7z/new-dashboard-copy?orgId=1&from=1636358874853&to=1636359174853&var-targetIP=10.10.168.77
```

It seems that the vatible dident render to the real expr, I got the log infomation from loki:

```
Nov 08 16:20:34 qplus loki-linux-amd64[5852]: level=info ts=2021-11-08T08:20:34.410599376Z caller=metrics.go:92 org_id=fake traceID=081baa54ec036f31 latency=fast query="{targetIP=\"$targetIP\"}" query_type=limited range_type=range length=5m0s step=200ms duration=1.827341ms status=200 limit=1000 returned_lines=0 throughput=0B total_bytes=0B
```

So the varible `targetIP` dident render the value `10.10.168.77`?

And I am sure the real expr worked correctly:
![image](https://user-images.githubusercontent.com/33649388/140707865-dfd9b4e9-9246-494d-878b-545de135e887.png)

**What you expected to happen**:

To confirm whether it's bug and find the correct way. I used to build PromQL expr for prometheus, it worked correctly.

**How to reproduce it (as minimally and precisely as possible)**:

Develop a loki system and set the datasource, create a dashboard for it with any varible.

**Environment**:
- Grafana version: 8.1.0
- Data source type & version: Loki 2.3.0
- OS Grafana is installed on: redhat 7.5
- User OS & Browser: Chrome
- Grafana plugins: None
- Others: None

**Comment by ashharrison90** [comment]
hi @jeyrce 👋 

i can reproduce this, but only if i wrap the query in strings. if i remove the string wrapping e.g. use `{targetIP=$targetIP}` instead of `{targetIP="$targetIP"}` everything works as expected:
![image](https://user-images.githubusercontent.com/20999846/140731016-8c6f7da0-49e4-4f80-8c34-04cbcd0c46ea.png)

does that solve your issue? 🤔

**Comment by jeyrce** [comment]
@ashharrison90 Thank you, I solved it by set editor settings just now. it seems that we must set the match rules for every varible.
![image](https://user-images.githubusercontent.com/33649388/140742669-a2941e46-115c-4dd3-9f20-1609b616d0a6.png)

Thanks a lot, it's my fault, I will close the issue  in few minutes.

**Comment by ashharrison90** [comment]
no problem, glad it's working for you now 🥳
