### ISSUE TITLE
Disable login but allow only admins to modify dashboards from UI.

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4139]
I have disabled login and 

auth.anonymous
enabled true

and  have 
org_role Viewer

However if i want to be able to modify dashboard i should be allowed to login as admin and make changes.

http://healthmonitor:8080/login

admin/admin

Does not work: Problem Unquthorized.

Is there a option to disable login but allow modification of dashboards through admin/editor login without having to restart grafana with auth.anonymous.enabled = false

**Comment by deepujain** [comment]
![screen shot 2016-02-23 at 6 27 33 pm](https://cloud.githubusercontent.com/assets/406777/13273810/25eb0eb4-da5b-11e5-994d-9344855d6e51.png)

**Comment by deepujain** [comment]
This works. I was giving wrong password for admin

**Comment by uppalarakesh2** [comment]
Could you help me out with this setup

**Comment by MahadevG** [comment]
Setup is
 Configuration in default.ini file enable below one to true to hide the login page. 
```
[auth]
# Set to true to disable (hide) the login form, useful if you use OAuth
#disable_login_form = false
disable_login_form = true
```

Next
```
[auth.anonymous]
# enable anonymous access
enabled = true
```

Restart the grafana and  you should be able to see  the grafana (if you don't see just change your org role from Viewer to Editor 
```
# specify role for unauthenticated users
org_role = Editor
```
