### ISSUE TITLE
UI: Access to graphs menu is not intuitive

### ISSUE THREAD

**Issue by jaimegago** [grafana/grafana#414]
It is not intuitive to the grafana new user that graphs menu is accessible by clicking on the graph title because there is no visual nor text clue about the title being more than plain text. Since editing graphs is needed very fast, new users will find out about clicking on the title one way or another but I think a few extra minutes of research could be saved for many new comers by adding some kind of clue (an icon maybe?).

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/770
