### ISSUE TITLE
Custom logo and Title

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4140]
I love grafana logo and title "Grafana". However having decided to go with Grafana for our dashboard needs is there a way to change the logo and grafana title , still acknowledging the fact that its powered by Grafana ?

**Comment by torkelo** [comment]
no there is currently no way to do this without forking grafana making changes and doing your own optimized build.-

**Comment by danpalmer** [comment]
@torkelo would you accept a pull request that implemented this? Assuming it was backwards compatible with sane decisions, configuration, etc, or is this a feature that you would explicitly not allow?

**Comment by danielneri-accesso** [comment]
@torkelo would a PR be accepted for this?
