### ISSUE TITLE
Dashboard: Validate query name before changing it

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#41401]
When a user renames a panel query then some characters causes the panel to break.
```
"  " - Space
" - " - Hyphen/Dash
" [ " - Square Bracket
" ( " - Bracket
" ` " - Grave
" $ " - Dollar
```

We should validate the input before save and warn/alert the user about any illegal chars.

**Comment by joshhunt** [comment]
Should/can the backend also be validating this?

**Comment by hugohaggmark** [comment]
We've looked into this and it seems to be specific to CloudWatch.

**Comment by hugohaggmark** [comment]
![image](https://user-images.githubusercontent.com/562238/141093014-6b17c5b6-cc3c-47c4-90f9-d419716a5271.png)

**Comment by sunker** [comment]
Thanks for creating this issue @hugohaggmark. 

Adding some context: All queries in the CloudWatch GetMetricData api need a unique id. This id can be used to reference other queries in math expressions. The user can specify a value for this using the Id field (see image above), but if they don't we fall back to `query[refId]`, e.g `queryA`. See https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/request_parser.go#L138-L144. 

We should test the ref id against the pattern `/^$|^[a-z][a-zA-Z0-9_]*$/`. If not, we should generate a unique, valid id.

**Comment by rmarturano** [comment]
Hey! I'd like to start working at this issue. 
Since it seems it's still in the backlog, could I take it? :)

+ @hugohaggmark @sunker

**Comment by hugohaggmark** [comment]
@rmarturano go for it 👍
