### ISSUE TITLE
grafana web doest not show me data source tab

### ISSUE THREAD

**Issue by anoopskapoor** [grafana/grafana#4141]
I am new to grafana. I just installed influxdb and  grafana. I am not able to find data source tab as mention on document. 
On installation doc:http://docs.grafana.org/installation/installation/
Its mention adding data source with below example, i am not sure which file i should add this so that Grafana web interface display, influxdb datasource
InfluxDB example setup
datasources: {
  'eu-metrics': {
    type: 'influxdb',
    url: 'http://my_influxdb_server:8086/db/<db_name>',
    username: 'test',
    password: 'test',
  },
  'grafana': {
    type: 'influxdb',
    url: 'http://my_influxdb_server:8086/db/grafana',
    username: 'test',
    password: 'test',
    grafanaDB: true
  },
},

**Comment by bergquist** [comment]
We seem to have some kind of error in the docs.

The url you are using is a very old version (1.9) 
Please use documentation on this page http://docs.grafana.org/installation/ (make sure it says 2.6)

**Comment by Scrxtchy** [comment]
Thanks, just had this issue on grafana 4.3.1 windows
Just commited myself as admin in the sqlite directly

**Comment by daniellee** [comment]
@Scrxtchy you could not find the list of data sources in Grafana?

**Comment by Scrxtchy** [comment]
My account was made without administrative access, the installation instructions did not provide the password. 

Was basically view only access

**Comment by daniellee** [comment]
@Scrxtchy you have to be an admin to access the data sources. The default password for the admin account is `admin` or the set once on first-run value specified in the config:

http://docs.grafana.org/installation/configuration/#admin-password

If you have lost the admin password, then it can be reset from the server:

http://docs.grafana.org/administration/cli/#reset-admin-password

**Comment by daniellee** [comment]
@Scrxtchy I updated the installation docs with the default password so that you will not get stuck next time. Thanks for pointing that out.
