### ISSUE TITLE
Grafana dashboard for elasticsearch 

### ISSUE THREAD

**Issue by NavneetMathpal** [grafana/grafana#4142]
Hi ,

can we make visulizalike like below in grafana using elasticsearch as datasource ?

1)
![capture1](https://cloud.githubusercontent.com/assets/6646828/13277264/98eb212c-db02-11e5-8773-7dc66feb0139.PNG)

2) In second (below picture) we can select the server names and accordingly dashboard get changes [link](http://play.grafana.org/dashboard/db/templated-graphs-nested) . I have tried to use templating but grafana was not able to parse the queries
example:  host:* (if I want all the host should come in drop down and I can select one)

![capture2](https://cloud.githubusercontent.com/assets/6646828/13277353/4b9c7d66-db03-11e5-9690-eb5e6d578595.PNG)

**Comment by torkelo** [comment]
1) Yes, 
http://play.grafana.org/dashboard/db/elasticsearch-metrics

2) 
http://docs.grafana.org/datasources/elasticsearch/#templating
demo dashboad
http://play.grafana.org/dashboard/db/elasticsearch-templated
