### ISSUE TITLE
Flux 2.0 - displayname not finding tags

### ISSUE THREAD

**Issue by donfox007** [grafana/grafana#41437]
**What happened**:
when setting 
![image](https://user-images.githubusercontent.com/11636218/140815460-818b0d61-c0bd-45f7-95b2-e0a946ec505f.png)
following happends
![image](https://user-images.githubusercontent.com/11636218/140816499-59738b85-d281-499f-b446-47b7cd3634aa.png)

this is how full name looks like 
![image](https://user-images.githubusercontent.com/11636218/140816126-e4583165-e986-471b-a8a3-0947d8b97d57.png)

**What you expected to happen**:
that Grafana reads out the vm_name without all the jitter
**How to reproduce it (as minimally and precisely as possible)**:
using telegraf + influxdb 2 + proxmox api

querry  : 
from(bucket: "proxmox")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["vm_name"] == "newinfluxserver" or r["vm_name"] == "Grafana")
  |> filter(fn: (r) => r["_field"] == "uptime")
  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)
  |> yield(name: "mean")  

//

**Anything else we need to know?**:
using a branch of telegraf to import data into influxdb

**Environment**:
- Grafana version: Grafana v8.2.3 (fb85ed6912)
- Data source type & version: InfluxDB 2.0.9 - 
- OS Grafana is installed on: ubuntu 
- User OS & Browser: win11 - edge
- Grafana plugins: none
- Others: proxmox database / api

**Comment by gabor** [comment]
hi @donfox007, i recommend renaming those names using Transforms so that when the data is displayed in the Gauge panel, it already has the correct names. there are multiple ways to achive this:

- one approach that might work is to use the `Labels to fields` transform, and make sure only `vm_name` is checked in the "Labels" field, and set the "Value field name" field to `vm_name`. 

- another approach is to use a "Rename by regex" transform, and set it up roughly like this:
    ```
    Match: .*vm_name="(\w+)".*
    Replace: $1
    ```
    (this assumes the possible values for vm_name only contain english alphanumeric characters and the underscore)

one of these approaches should fix your problem. if they don't fix it, just reply here please, and we can reopen the issue.

**Comment by gabor** [comment]
hi @donfox007 , there is also a much simpler approach too:
just write this in the `Display Name` field in the gauge panel: `${__field.labels.vm_name}`

**Comment by donfox007** [comment]
> 

Thanks , already looked at documentation can you maybe explain to me what difference between label and tag ?

it solved issue with above solution much love and appreciation

**Comment by gabor** [comment]
> Thanks , already looked at documentation can you maybe explain to me what difference between label and tag ?

@donfox007 tags and labels are the same thing. different time-series databases use different names for the same thing, for example:
- prometheus calls them labels (https://prometheus.io/docs/concepts/data_model/#metric-names-and-labels)
- influxdb calls them tags (https://docs.influxdata.com/influxdb/v2.0/reference/glossary/#tag)
