### ISSUE TITLE
Create organisation using REST api

### ISSUE THREAD

**Issue by paulbakker** [grafana/grafana#4143]
It's currently not possible to create an organisation using the REST API. I can see how this is related to the fact that API keys are created per organisation.
Would it be possible to create a "global" API key which could be used to create organisations (and maybe even API keys)?

**Comment by torkelo** [comment]
Any user can create new orgs (if you have not disabled it in the grafana.ini config file)

POST http://localhost/grafana/api/orgs/
{name: "My other new org"}

**Comment by paulbakker** [comment]
Perfect! In that case it's missing from the docs :) Do you want me to create a PR for that?

**Comment by torkelo** [comment]
I think it is in master docs ( it pushed)

**Comment by torkelo** [comment]
That should read not pushed
