### ISSUE TITLE
Href images no longer fully clickable

### ISSUE THREAD

**Issue by mikhailredis** [grafana/grafana#41445]
**What happened**:

The images with href are not fully clickable on the dashboards, except small area in the center of the image. Image is fully clickable in the Edit mode. Old issue in the forum: https://community.grafana.com/t/href-images-no-longer-fully-clickable/47201 and it was confirmed by Matt Abrams.

I am working on updates for my images plugin and has this issue in 8.2.3.

**What you expected to happen**:

Images should be fully clickable.

**How to reproduce it (as minimally and precisely as possible)**:

This issue was reproduced and confirmed by @Matt Abrams.

Any `<img>` inside `<a href>` should reproduce the issue.
![Screen Shot 2021-11-08 at 6 10 32 PM](https://user-images.githubusercontent.com/47795110/140832731-193a7960-bd4d-487f-8464-d6ecf9e793d2.png)

Image inside Text plugin has the same issue:

```
<a href="123"><img src="https://demo.volkovlabs.io/static/bg.png"/></a>
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: any
- OS Grafana is installed on: any
- User OS & Browser: any
- Grafana plugins: any
- Others:

**Comment by ashharrison90** [comment]
hey @mikhailredis 👋 

i think the previous comment [here](https://github.com/grafana/grafana/issues/36695#issuecomment-879911148) still applies. `<a>` elements are `display: inline;` by default as the more common case is to have inline links.

for the less common case (e.g. image links), if you set the style to have `display: block;` does that solve your issue?

hope that helps! 😄

**Comment by mikhailredis** [comment]
@ashharrison90, feels like a workaround, then a solution, but it works for my plugin.
Thank you.
