### ISSUE TITLE
Missing "show context" overlay when log query for Loki data source has json pipeline as a part of logql query.

### ISSUE THREAD

**Issue by jbreiding** [grafana/grafana#41448]
**What happened**:
Missing "show context" overlay in logs query when using json formatter in the pipeline.
both queries are working, just context overlay is missing

`{cluster="cluster name"} | json | level="error"` - no show context overlay

`{cluster="cluster name"} |= "error"` - has show context overlay

**What you expected to happen**:
context overlay to be present in both query results

**How to reproduce it (as minimally and precisely as possible)**:
run query with json format in pipeline

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.3 (a61f38238c)
- Data source type & version: Loki (?)
- OS Grafana is installed on: amazon linux 2 (amd64)
- User OS & Browser:
Mac monterey, 
safari
Version 15.1 (17612.2.9.1.20)
- Grafana plugins: unsure, installed via kube-prometheus-stack no grafana changes besides configuration
- Others:
This is all running on eks 1.20

**Comment by ivanahuckova** [comment]
@jbreiding That is a correct behaviour. We are showing context only if you use [line filter expression](https://grafana.com/docs/loki/latest/logql/log_queries/#line-filter-expression). It doesn't appear for [label filter expression](https://grafana.com/docs/loki/latest/logql/log_queries/#label-filter-expression). If showing of log context for queries with label filter expression would be useful feature for you, could you please create a new feature request in the discussions and tell us about your use case and what would you like to see.

**Comment by tristan-tsl** [comment]
maybe it's really useful...

**Comment by jbreiding** [comment]
@ivanahuckova my understanding of the show context is that it shows the lines surrounding the lines that match the filter.
This lines also do not match the line filter expression.

I was really hoping the same functionality would be there no matter the expression type chosen.

Thank you for the reply.

I could open a feature request if you think it makes sense. The context feature is really powerful and label filters are even more helpful to reduce the lines returned from the query.

**Comment by ivanahuckova** [comment]
@jbreiding Yes, it would be awesome if you created a new feature request in discussions and described why it would be helpful for you. 

Also btw by this:

>That is a correct behaviour.

I meant that is correct current behavior because we haven't implemented it. Not because it wouldn't make sense to have it implemented.

**Comment by jbreiding** [comment]
Totally makes sense, I will create the discussion.

**Comment by jbreiding** [comment]
Done, hope the linkage helps carry forward this conversation and details.
