### ISSUE TITLE
[Prometheus data source] Set default format for "all" and "multi" to "pipe"

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#4144]
Prometheus only supports pipe format for templates so at the least the default should be changed; optionally, all other options can simply be discarded.

**Comment by torkelo** [comment]
thanks for reporting this, fixed in https://github.com/grafana/grafana/commit/30f3b55baf11ed2e1129216ed668f7103b82f318

**Comment by zeph** [comment]
same for graphite... would u mind if I push a similar patch?
