### ISSUE TITLE
Tooltip shows previous day's values

### ISSUE THREAD

**Issue by chs820** [grafana/grafana#41444]
**What happened**: Upon hovering over a data point in a time-series panel, the tool-tip displays the previous day's data.

**What you expected to happen**: I expected that hovering over the data point would show that day's data point values.

**How to reproduce it (as minimally and precisely as possible)**: Create a time-series panel with values for each day. Hover over a data-point.

**Anything else we need to know?**: n/a

![grafana_hover_bug](https://user-images.githubusercontent.com/14276197/140832468-576ffc07-328c-41e0-a2d0-3b6e30216aae.png)

**Environment**:
- Grafana version: Grafana v8.2.3-40566 (3b8be57b4f)
- Data source type & version: BigQuery datasource for Grafana
- OS Grafana is installed on: Grafana Cloud Pro
- User OS & Browser: Pop!_OS & Brave
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
But looking at the timestamp and placement it looks correct, it 8pm on the 31st
