### ISSUE TITLE
Unable to add datasource in grafana 6.2.0 version

### ISSUE THREAD

**Issue by VinayKumarDanda** [grafana/grafana#41453]
**What happened**: "Failed to add datasource" while trying to Add a new datasource.

**What you expected to happen**: Add new datasource successfully.

**How to reproduce it (as minimally and precisely as possible)**: Click on add datasource.

**Anything else we need to know?**:  Below is the error message seen in logs.
lvl=eror msg="Failed to add datasource" logger=context userId=1 orgId=1 uname=admin error="Error 1062: Duplicate entry '1-0' for key 'UQE_data_source_org_id_uid'"

**Environment**:
- Grafana version: 6.2.0
- Data source type & version: any datasource type. Not with one datasource type.
- OS Grafana is installed on: Debian GNU/Linux 9
- User OS & Browser: Windows 10, Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Strange, we have no other similar reports. You are using a very old version. Try upgrading to 8.x and if your problem persists re-open this issue

**Comment by fearless11** [comment]
you can refer here https://github.com/grafana/grafana/issues/27837
