### ISSUE TITLE
how do i get a scripted dashboard to show up in the list of dashboards, or on the home dashboard?

### ISSUE THREAD

**Issue by lawre** [grafana/grafana#4145]
What is the trick to getting a scripted dashboard to show up in grafana without having to remember the URL?  Thanks.

**Comment by torkelo** [comment]
Right now there is no way to do this, the only option is to create a text panel with links to your scripted dashboards

**Comment by lawre** [comment]
In Grafana 3.0, is it now possible to get a scripted dashboard to show up in the list of dashboards, or on the home dashboard?  Thanks.

**Comment by torkelo** [comment]
You can't :(

**Comment by quanganhtran** [comment]
How about as of Grafana 5.1?

**Comment by namannigam** [comment]
How about now? Any future plans to it or any reason not to introduce this?
