### ISSUE TITLE
Docs feedback: /installation/rpm.md Proxy Settings

### ISSUE THREAD

**Issue by josefzahner** [grafana/grafana#41459]
Please specify where and how we have to define proxy settings for Grafana. We have a corporate proxy and it took me hours to find the exact format. The key was to not include the "http://".
Reference: https://github.com/grafana/grafana/issues/11962

Solution for CentOS:
env file: /etc/sysconfig/grafana-server
env variable: HTTPS_PROXY=10.X.X.X:8080

**Comment by sdboyer** [comment]
@papagian assigning you, since you've kindly made a PR for this :)
