### ISSUE TITLE
Panel repeat does not work when params in url is not in options of variable

### ISSUE THREAD

**Issue by dessen-xu** [grafana/grafana#41461]
**What happened**:

I repeat the panel with a Multi-value variable. But when I use variable that does not exit in options, it not work.

demo:

please open: https://xuzm15336533347.grafana.net/d/h1Tc6G5nz/repeat-test?orgId=1

![image](https://user-images.githubusercontent.com/41524013/140916228-581bba44-39e6-44ea-b920-5b71a3a8840e.png)
Now, repeat is ok.

But open: https://xuzm15336533347.grafana.net/d/h1Tc6G5nz/repeat-test?orgId=1&var-test=ccc&var-test=ddd

now, ddd is not in options, repeat does not work

![image](https://user-images.githubusercontent.com/41524013/140916568-7e313002-b80a-4c85-a67a-bcf8a5674d2d.png)

**What you expected to happen**:
Repeat can render variable in url, even if it does not in options.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7 && 8
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: mac chrome
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment]
hi @dessen-xu 👋 

i think this is working as designed. we only ever want to repeat for the set of defined variables. if the variable doesn't exist in the list of defined variables, we ignore it in the query params. 

do you have a use case for wanting this behaviour? 

thanks!

**Comment by dessen-xu** [comment]
Yes, I do. Can you consider adding this feature.

**Comment by hugohaggmark** [comment]
Hi @dessen-xu all feature requests should be opened as a Github discussion so we can better assess the community feedback. If you do create an issue it's very valuable to us and the community that you describe and argue for your use case. Thank you but I'm going to close this issue for now.
