### ISSUE TITLE
New Docker install won't start, complains about both permissions and checking server process execution privilege

### ISSUE THREAD

**Issue by bertiebaggio** [grafana/grafana#41481]
**What happened**:

`$ docker-compose up grafana` exits with following error in log:

```
Creating grafana ... done                                                                                                      
Attaching to grafana                                                                                                           
grafana     | GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.                                                      
grafana     | GF_PATHS_DATA='/var/lib/grafana' is not writable.                                                                
grafana     | GF_PATHS_HOME='/usr/share/grafana' is not readable.                                                              
grafana     | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later                                                                                                          
grafana     | Error checking server process execution privilege. error: could not get current OS user to detect process privileges                                                                                                                            
grafana     | t=2021-11-09T14:02:51+0000 lvl=crit msg="failed to parse \"/etc/grafana/grafana.ini\": open /etc/grafana/grafana.ini: no such file or directory"                                                                                                
grafana exited with code 1
```

**What you expected to happen**:  Container starts, performs first set up

**How to reproduce it (as minimally and precisely as possible)**:

Follow [Run Grafana Docker image](https://grafana.com/docs/grafana/latest/installation/docker/) guide.

docker-compose.yml:

```yml
version: 3.0

services:
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
      - ./grafana-config:/etc/grafana
      - ./grafana-log:/var/log/grafana
    # set in .env -- UID=1000,GID=1000
    user: "$UID:$GID"
```

Directories specified as bind volumes are created and are user-readable on host

**Anything else we need to know?**: See also: #41217

**Environment**:
- Grafana version: (`:latest` ie 8.2.3)
- Data source type & version:  N/A
- OS Grafana is installed on: Docker on Arch Linux host
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

----

Related reading: [New Docker Install with persistent storage, Permission problem](https://community.grafana.com/t/new-docker-install-with-persistent-storage-permission-problem/10896) forum thread

I am running into a similar issue to #41217 on new install:  logs complain both about permissions and not being able to get OS user to detect privileges.

In the other thread kylebrant suggests specifying the graphana user in the compose file. However, can the `user:`  specification in docker-compose.yml not be used to run grafana under a different id to 472, so that permissions match host permissions?

From https://grafana.com/docs/grafana/latest/administration/configure-docker/#run-grafana-container-using-bind-mounts:

> You may want to run Grafana in Docker but use folders on your host for the database or configuration. When doing so, it becomes important to start the container with a user that is able to access and write to the folder you map into the container.

## Workaround?

By using the `grafana/grafana:7.5.7` image I am able to get a running container with the usual default admin/admin login page.

Is this a regression, or has something changed in the meantime that changes how permissions should be set up on install / how `user:` should be specified?

Cheers!

**PS**: I am happy for this discussion to be moved to #41217, but OP there hasn't come back yet and they get a working dashboard, whereas I could not get a working container.

**Comment by papagian** [comment]
> In the other thread kylebrant suggests specifying the graphana user in the compose file. However, can the user: specification in docker-compose.yml not be used to run grafana under a different id to 472, so that permissions match host permissions?

I don't think that is possible given that the grafana user under the image is created with the [specific](https://github.com/grafana/grafana/blob/b39859bdfec267f968be4b82c0b6c84bf06c85c7/Dockerfile#L47) `uid`.
@grafana/grafana-release-eng WDYT?

**Comment by marefr** [comment]
I tried to run your docker-compose.yml.
1. First try
```
❯ docker-compose up                                                                                                                                                                                                                            
ERROR: Version in "./docker-compose.yml" is invalid - it should be a string.
```
2. Changed `version: 3.0` -> `version: "3.0"`
3. Second try
```
❯ docker-compose up
WARNING: The UID variable is not set. Defaulting to a blank string.
WARNING: The GID variable is not set. Defaulting to a blank string.
Starting grafana ... done
Attaching to grafana
grafana    | GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.
grafana    | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
grafana    | Grafana server is running with elevated privileges. This is not recommended
grafana    | t=2021-11-23T16:45:21+0000 lvl=crit msg="failed to parse \"/etc/grafana/grafana.ini\": open /etc/grafana/grafana.ini: no such file or directory"
grafana exited with code 1
```
4. Still couldn't get `user: "$UID:$GID"` to work. Had to change to `user: "${UID}:${GID}"` together with adding an .env file with the following contents: 
```
UID=1000
GID=1000
```
5. Then it picks up the specified user and group id's, but still fails similar to your example above:
```
❯ docker-compose up          
Creating network "test_default" with the default driver
Creating grafana ... done
Attaching to grafana
grafana    | GF_PATHS_CONFIG='/etc/grafana/grafana.ini' is not readable.
grafana    | You may have issues with file permissions, more information here: http://docs.grafana.org/installation/docker/#migrate-to-v51-or-later
grafana    | Error checking server process execution privilege. error: could not get current OS user to detect process privileges
grafana    | t=2021-11-23T16:48:42+0000 lvl=crit msg="failed to parse \"/etc/grafana/grafana.ini\": open /etc/grafana/grafana.ini: no such file or directory"
grafana exited with code 1
```

```
❯ docker-compose version 
docker-compose version 1.27.4, build 40524192
docker-py version: 4.3.1
CPython version: 3.7.7
OpenSSL version: OpenSSL 1.1.0l  10 Sep 2019
```

**Conclusion:**
1. Make sure you're providing environment variables in correct format according to your docker-compose version.
2. Read the [docs](https://grafana.com/docs/grafana/latest/administration/configure-docker/#configure-a-grafana-docker-image) carefully
> If you are running Grafana in a Docker image, then you configure Grafana using environment variables rather than directly editing the configuration file.

You are directly editing the configuration file which is not officially supported by us. You can do this, but then you need put a grafana.ini file in your mounted /etc/grafana volume. There's also additional things you need to create to mimic the Grafana default behavior, currently [this](https://github.com/grafana/grafana/blob/934e4ad3afdf8348f673a7eeb8571c93b92b6453/packaging/docker/Dockerfile#L61-L65). But again not really officially supported and we don't recommend overriding the /etc/grafana directory. 

I'm going to close this since it works as expected if you're following the documentation. If I misunderstood something, let me know, and we'll consider reopen the issue.

**Comment by bertiebaggio** [comment]
Thank you for taking the time to look into this and reply.

re 1: In my own docker-compose.yml  version is indeed a string- sorry about that, must have been lost somehow in translation to MWE. re 4: These (UID/GID) ostensibly work in the version I am running but I will test with a newer version.

I am some versions behind on my 'production' (for self-hosting purposes) docker host:

```
$ docker-compose version
docker-compose version 1.25.5, build unknown
docker-py version: 4.2.0
CPython version: 3.8.2
OpenSSL version: OpenSSL 1.1.1g  21 Apr 2020
```

My apologies too for missing that sentence in the docs! I will test afresh in a VM.
