### ISSUE TITLE
Downgrading Grafana

### ISSUE THREAD

**Issue by tal-ayalon** [grafana/grafana#41518]
**What happened**:
I want to know if there is official downgrade procedure. I upgraded grafana to 8.2.2 using Helm, now I want to revert it back to 7.2.1. How can I do it?

**What you expected to happen**:
I want to know if there is official downgrade procedure. I upgraded grafana to 8.2.2 using Helm, now I want to revert it back to 7.2.1. How can I do it?

**How to reproduce it (as minimally and precisely as possible)**:
I want to know if there is official downgrade procedure. I upgraded grafana to 8.2.2 using Helm, now I want to revert it back to 7.2.1. How can I do it?

**Anything else we need to know?**:
I want to know if there is official downgrade procedure. I upgraded grafana to 8.2.2 using Helm, now I want to revert it back to 7.2.1. How can I do it?

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: Prometheus
- OS Grafana is installed on: GKE k8s
- User OS & Browser: Mac, chrome
- Grafana plugins: 
- Others:

**Comment by torkelo** [comment]
As long as you have a database backup it's safe to downgrade to any previous version, 
https://grafana.com/docs/grafana/latest/installation/upgrading/
