### ISSUE TITLE
Downsampling sometimes not showing graph for all chart options

### ISSUE THREAD

**Issue by usulkies** [grafana/grafana#4151]
We're using Grafana (v2.6) with TSDB.
In some cases, the graph shown nothing, although there is data.
In the following example it happens especially when using "*" for a tag value.
Downsampling: 1 hour.
Range: last 6 hours
Total values in series: 16
Aggregators: zimsum
![image](https://cloud.githubusercontent.com/assets/10584010/13312917/fa54ca9e-dba2-11e5-8092-eef34d1d99bd.png)

When Display Styles using "Bars" or "Lines" (like this:)
![image](https://cloud.githubusercontent.com/assets/10584010/13312942/208597f2-dba3-11e5-8046-4a11f5d1566e.png)
The graph is empty but tooltip shows values:
![image](https://cloud.githubusercontent.com/assets/10584010/13312967/44f059b0-dba3-11e5-954c-1dc3fd035665.png)

When using "Points":
![image](https://cloud.githubusercontent.com/assets/10584010/13312974/59b5b75a-dba3-11e5-9193-e5c837ff1c4d.png)
Then the graph shows values:
![image](https://cloud.githubusercontent.com/assets/10584010/13312985/69a03834-dba3-11e5-9568-43d2f4e3d4e8.png)

Also, when choosing larger range (12 hours) the graph is presented:
![image](https://cloud.githubusercontent.com/assets/10584010/13313194/bcac2000-dba4-11e5-8b51-2fd53633110f.png)

**Comment by torkelo** [comment]
Stack requires there be values for all series, if some serie is missing values then the stacking failes and you end up with missing sections. 

For some datasources you can solve this by inserting 0 values for missing values, not sure how OpenTSDB handles missing values, you can try changing the null point mode in display styles tab to "null as zero", this might solve it, but only if OpenTSDB returns nulls for the missing data points

**Comment by usulkies** [comment]
But then why is it solved when I'm using larger range, or when using points instead of bars and lines?
Points are also stacked, why the problem persists only for lines and bars?
