### ISSUE TITLE
Geomap: GeoJSON Support Point Rendering

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#41514]
We currently only support fill rendering for geojson data, and don't display anything for point based data.

Support point rendering (show something on map for each point). Add airport geojson file as one of default options to use / test with (public/gazetteer/airports.geojson)

<img width="1363" alt="Screen Shot 2021-11-09 at 3 19 01 PM" src="https://user-images.githubusercontent.com/22381771/141021195-4c0ba941-d339-4395-82ea-a70607f1c3f0.png">

**Comment by ryantxu** [comment]
See also https://github.com/grafana/grafana/pull/41622

**Comment by nmarrs** [comment]
Addressed in #41622
