### ISSUE TITLE
Time series plugin tooltip doesn't have the static class name, id, or attribute

### ISSUE THREAD

**Issue by callmehomer** [grafana/grafana#41523]
**What happened**:
Currently, the **Time series** tooltip doesn't have any readable (user-friendly) HTML selector, besides generated CSS class ("css-tfew28"). I want to access the tooltip's DOM element, but I can access it only via this CSS class and I assume that the class can change in the future.

**What you expected to happen**:
It will be good if the tooltip would have a selector of any sort - constant class name, id, attribute. Similar to the old Graph, which at least has a 'tooltip' class assigned.

**How to reproduce it**:
The issue can be viewed on the test website, by inspecting the DOM.
https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1

![image](https://user-images.githubusercontent.com/31961734/141093903-c3cbcb12-c0be-4218-8de8-031a81e87608.png)

**Environment**:
- Grafana version: 8.3.0
- Grafana plugins: Time series

**Comment by torkelo** [comment]
why do you need this?
