### ISSUE TITLE
UX - single stat panel resize bug

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#4153]
Hi,
Something has changed in single stat panel presentation in all buids since 2nd of February. It's impossible to set it's size lower then 150px. I think it might be related somehow with the issue described in #4049. Here is how the same dashboard looks like in today's build (25 of Feb):
![single_stat0225](https://cloud.githubusercontent.com/assets/12551929/13323725/fcf63e6c-dbda-11e5-82f4-ed40b2428904.jpg)
And from 2 of Feb:
![single_stat0202](https://cloud.githubusercontent.com/assets/12551929/13323734/07953634-dbdb-11e5-8ed5-9baa4b3dd123.jpg)

**Comment by torkelo** [comment]
I just tested this and cant find any issue, whats your panel config? (prefix setting) & font size?
