### ISSUE TITLE
Tempo: basic auth password disappears when adding trace-to-log tags

### ISSUE THREAD

**Issue by kvrhdn** [grafana/grafana#41543]
**What happened**:
In the configuration page for the Tempo datasource, when you add tags in the trace to logs section using enter, the basic auth password is cleared.

Video:

https://user-images.githubusercontent.com/7748404/141119399-260fff55-287b-4a1f-8b08-f8a78b25302d.mov

**What you expected to happen**:
The basic auth password should not be cleared.

**How to reproduce it (as minimally and precisely as possible)**:
- Configure a Tempo datasource with basic auth enabled
- In the trace to logs section, add tags
- If you add a tag using the enter key, the password is cleared

**Anything else we need to know?**:
N/A

**Environment**:
- Grafana version: v8.2.3 and v8.3.0-40896pre
- Data source type & version: Tempo
- OS Grafana is installed on:
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment]
can repro this on main 👍
