### ISSUE TITLE
Dashboard can be made editable by other users.

### ISSUE THREAD

**Issue by sgarg7** [grafana/grafana#4155]
I verified this is happening. I remove the "editable" option from a dashboard. 
![image](https://cloud.githubusercontent.com/assets/1569480/13329335/4999af8e-dbc1-11e5-85ab-beb6170902d1.png)

Other users(with editor privilege) in the same organization can make it editable again. They can then make changes to the graph panels, and then save over my dashboard!

Giving viewer privilege to these users is not a solution since I want them to be able to create their own dashboards.

Is this expected behavior? If so what's the purpose of the editable option?

How can I prevent other users from editing my dashboard that I set to not be editable?

**Comment by torkelo** [comment]
The point of making a dashboard non editable is to put a dashboard in non edit mode, any user with editor privileges can enable editing again. There is no private / per user dashboards yet.
