### ISSUE TITLE
Time series panel threshold line

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#41550]
**What happened**: Visual threshold on time series panel does not update automaticaly when changing alert threshold (this is automatic on old graph panel).

![image](https://user-images.githubusercontent.com/66313770/141125906-e55d547f-05ff-48bd-93b1-d8b60dd18eef.png)

**What you expected to happen**: Visual threshold to automaticaly update based on threshold set on alert (like on old graph panel).

**How to reproduce it (as minimally and precisely as possible)**:/

**Anything else we need to know?**:/

**Environment**:
- Grafana version: 8.2.3
- Data source type & version:/
- OS Grafana is installed on: Debian
- User OS & Browser: Chrome, Windows 10
- Grafana plugins:/
- Others:/

**Comment by torkelo** [comment]
for the new time series panel this is manual, not ideal but this is the legacy alerting engine that we are going to remove in the futute. The new alerting system has a standalone UI. 
And in that ui you have drag handles for thresholds: 

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
![Screenshot from 2021-11-10 15-17-37](https://user-images.githubusercontent.com/10999/141129562-ca66ab15-b334-4d2b-9dc2-3c33f4bd5798.png)
