### ISSUE TITLE
Error message in alert rules page because of invalid datasources being saved

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#41553]
**What happened**:

When a user creates a Prometheus or Loki datasource without specifying a URL and then goes to the alert list page, an error toast for these datasources shows up.

![](https://user-images.githubusercontent.com/79632099/137888520-1a4c9d62-7896-44ec-8d9c-24533f99466b.png)

Right now, data sources are being created and updated without validating required fields.

**What you expected to happen**:

Error messages should be de-duplicated and less intrusive.
Also, there should be some kind of validation in place (e.g. indicating which fields are required and returning a 400 error if necessary) when updating data sources in order to keep consistency and avoid saving invalid data.

**How to reproduce it (as minimally and precisely as possible)**:

1. Have Grafana 8 alerting enabled.
2. Create Prometheus datasource, do not fill in URL.
3. Go to alert list page, an error toast will show up.

**Environment**:
- Grafana version: 8.2.

**Next steps**:

- [x] Validate the URL when updating a data source.
- [x] Show only 1 error per data source. 
Fixed in https://github.com/grafana/grafana/pull/37734
- [x] Persist the dismissal of the error message to localstorage, but show a warning icon that the user can click to show the full error message again.
Fixed in https://github.com/grafana/grafana/pull/43406
- [x] Figure out why it's rendering `[Object object]` as an error message
Fixed in https://github.com/grafana/grafana/pull/64023

**Comment by santihernandezc** [comment]
Related issue: https://github.com/grafana/grafana/issues/42836

**Comment by alexweav** [comment]
The backend component of this is up for review. Moving under the `area/frontend` path for remaining work.
