### ISSUE TITLE
grafana-2...tar.gz.. no run grafana with daemon

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#4158]
Hi,

I downloaded grafana-2.6.0.linux-...tar.gz and After install..

I tried to start grafana..
```
$ ./bin/grafana-server
```

#### But grafana ran only foreground.. I want to run daemon!
I don't want to run service

```
$ sudo service grafana-server start
// No!
```

How to run grafana daemon without sudo service?

Thank you!

**Comment by torkelo** [comment]
There is no built in daemon mode in grafana-server .

But you can easily start it as a background process: 
nohup ./bin/grafana-server &

http://stackoverflow.com/questions/4797050/how-to-run-process-as-background-and-never-die

**Comment by tuyy** [comment]
Thank you!!

**Comment by raz0r3dge** [comment]
Hey there, sorry for opening this again but, there is no daemon mode for grafana-server builded from source?
