### ISSUE TITLE
@grafana/data getDisplayProcessor func, encountered an error when value is numeric string bigger then MAX_SAFE_INTEGER.

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#41589]
**What happened**:

Use csv content source, the number string will display as number, but it`s type is string.

![image](https://user-images.githubusercontent.com/12808432/141270558-77569fa9-2a79-4aab-b9aa-863333689bbe.png)

In this function, should we add aditional condition to check value type? 
https://github.com/grafana/grafana/blob/881dd9992cef1d197e6d5c32d4da4b6bb0ce33c5/packages/grafana-data/src/field/displayProcessor.ts#L103

**What you expected to happen**:

display as full string content  3701925924894146889

**How to reproduce it (as minimally and precisely as possible)**:

use gdev-testdata datasource, and input below content:

```csv
str
aa
3701925924894146889
```

**Environment**:
- Grafana version: play.grafana.com latest version
- User OS & Browser: macos chrome

**Comment by MeetzhDing** [comment]
Solution 1.

this can process big integer and high-precision floating-point number， and FieldType.number will work like before. 
```js
    if (!isNaN(numeric) && (toString(numeric) === toString(value))) { ... }
```

but this only fix high precision number, numeric string like `111.12222` will be cut off still
![image](https://user-images.githubusercontent.com/12808432/141428564-e00a2504-1df0-4d2e-aef6-faed4d12fb5f.png)



Solution 2.
```js
  if (!isNaN(numeric) && field.type !== FieldType.string) { ... }
```
this will use FieldType info first, because there is no reason to get unit suffix to string type.
but this may changed the original intention of using `anyToNumber`

**Comment by torkelo** [comment]
For legacy reasons (not ideal) , Grafana will always try to format values as number by default. Not ideal. 

There is a work around set Unit (under standard options), to `String`

**Comment by towolf** [comment]
@torkelo I think we have this problem too with String data, but setting unit to String does not help:

![image](https://user-images.githubusercontent.com/345210/157048119-c3a57d7c-2393-44ef-a05e-95cd2b0de6b9.png)

![image](https://user-images.githubusercontent.com/345210/157049648-01a025ce-b74f-47b4-a8a3-84bbc7869b55.png)

![image](https://user-images.githubusercontent.com/345210/157049759-e0d79a3c-b9fb-40e3-8084-9dc9ce327596.png)

Are you sure there is not an issue with implicit conversions?

**Comment by torkelo** [comment]
Unable to replicate with the Table panel.  the raw data  "Table view" is having this issue, it's displaying data without any overrides/default unit. But if you switch to table panel it string unit works 
![Screenshot from 2022-03-07 19-03-25](https://user-images.githubusercontent.com/10999/157091850-29601029-aa64-49a5-b9f3-17a8f187813a.png)

**Comment by towolf** [comment]
Hi @torkelo I've tried it again with TestdataDB and I can reproduce? I'm quite confused why you don't see that.

![image](https://user-images.githubusercontent.com/345210/157097112-f864c96e-ddc9-4a94-80f2-c65538c9b92a.png)

Here's my Panel JSON with Grafana 8.4.1:

```json
{
  "id": 2,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 9
  },
  "type": "table",
  "title": "Panel Title",
  "targets": [
    {
      "scenarioId": "csv_content",
      "refId": "A",
      "datasource": {
        "uid": "Hv5CbYY7z",
        "type": "testdata"
      },
      "csvContent": "playerID, value\n76561198920624597, 10"
    }
  ],
  "options": {
    "showHeader": true,
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "fields": ""
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "displayMode": "auto"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      },
      "unit": "string"
    },
    "overrides": [
      {
        "matcher": {
          "id": "byName",
          "options": "playerID"
        },
        "properties": [
          {
            "id": "unit",
            "value": "string"
          }
        ]
      }
    ]
  },
  "datasource": {
    "uid": "Hv5CbYY7z",
    "type": "testdata"
  },
  "pluginVersion": "8.4.1"
}
```

**Comment by torkelo** [comment]
The testdata datasource is csv content is a bit special, on the backend it will turn all values to numbers that can be. So it's not related to your issue

**Comment by torkelo** [comment]
What data source are you using? Could be a bug in that datasource

**Comment by towolf** [comment]
@torkelo We have the problem with [Vertamedia/clickhouse-grafana](https://grafana.com/grafana/plugins/vertamedia-clickhouse-datasource/) and we replicated it with MySQL, by using `SELECT '76561198920624597'`. And then with TestData DB. So after three datasources we got the impression that this is a general problem.

**Comment by torkelo** [comment]
@towolf the string unit works for me (when used in an override) 
![Screenshot from 2022-03-16 16-01-47](https://user-images.githubusercontent.com/10999/158620875-106aec01-6d07-4419-ab62-7c853bb2a3a4.png)

**Comment by torkelo** [comment]
actually it works when set from the standard options as well (default)

**Comment by towolf** [comment]
Wow, I thought I could repro using the latest version, but now that I checked, with the latest version you seem to be correct! 

I guess, nevermind then? /shrug
