### ISSUE TITLE
Different timestamp in whisper

### ISSUE THREAD

**Issue by mkurakov** [grafana/grafana#4159]
My script is executed every 30 seconds and sends approximately 250-300 values to Whisper in a single pass. Sometimes there is a problem - the data returned from the script written with different timestamps. Because of this breaks sumSeries function. In carbon.conf I found MAX_DATAPOINTS_PER_MESSAGE = 500 option, but found no description of this parameter. How can I solve the problem with the wrong timestamp?
I'm using grafana-server 2.6.0

**Comment by bergquist** [comment]
This seems to be an issue for graphite not grafana.
https://github.com/graphite-project/

Feel free to reopen if you disagree.
