### ISSUE TITLE
Support ESM modules

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#41595]
This is an initial placeholder issue for discussion of how we support ESM modules in Grafana/how we convert Grafana to be ESM.

Why? Many new packages have updated to be ESM only.

See the FAQ here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

This is currently blocked until TypeScript 4.5 is released (https://devblogs.microsoft.com/typescript/announcing-typescript-4-5-beta/), but that should be any day now. 😱

**Comment by ben-polinsky** [comment]
Hi there,

Is this still the case? I have had success importing ES modules. I see this PR #51517 which appears to have added the support. In addition, there's this old note in the Toolkit FAQ:

> I am getting this message when I run my plugin: Unable to dynamically transpile ES module A loader plugin needs to be configured via SystemJS.config({ transpiler: 'transpiler-module' }).
This error occurs when you bundle your plugin using the grafana-toolkit plugin:dev task and your code comments include ES2016 code.

> There are two issues at play:

> The grafana-toolkit plugin:dev task does not remove comments from your bundled package.
Grafana does not support [ES modules](https://hacks.mozilla.org/2018/03/es-modules-a-cartoon-deep-dive/).
If your comments include ES2016 code, then SystemJS v0.20.19, which Grafana uses internally to load plugins, interprets your code as an ESM and fails.

> To fix this error, remove the ES2016 code from your comments.

Which is a bit confusing - it's not clear what ES2016 code in comments entails - I'm pretty sure I do have comments with ES2016 code and it transpiled fine. 

Thanks

**Comment by zoltanbedi** [comment]
Hi @ben-polinsky,

This issue is more like changing our codebase to esm modules.
