### ISSUE TITLE
Unit of measurement #B in metric name interpreted as query reference

### ISSUE THREAD

**Issue by easterhanu** [grafana/grafana#4162]
Many Nagios plugins output performance data with the unit of measurement (UOM) appended to the value, such as 1000b for thousand bits or 1000B for a thousand bytes and so on. Since Graphite has no concept of metadata, we've appended the unit of measurement into the metric name in Graphite like this:

foobar.size#b.avg (bits)
foobar.size#B.avg (bytes)
foobar.size#MB.avg (megabytes)

Since the introduction of the query reference feature in Grafana, adding a metric with bytes unit like 'foobar.size#B' results in "no datapoints" in Grafana, because Grafana considers "#B" to be a reference while it actually is a valid part of the metric name.

The only partial work-around we have figured out is to use 'foobar.size*B', i.e. replace the hash with an asterisk, but since the wildcard may match more than is intended, this is not a proper solution. We would also very much like to use the Grafana query editor as-is, without a need to manually edit the metric paths to bypass query reference logic.

I realise this is an unfortunate coincidence, but I also think it's a bit risky approach for Grafana to have special meaning for fixed "magic strings" in metric paths. Would it be possible to have the query reference syntax configurable by user? So instead of hard coded #([A-Z]) logic one could choose to use !$#([A-Z]) or whatever that would be known to be safe(r) by the user.

**Comment by torkelo** [comment]
I think this can be solved by a better more precise regex

**Comment by daniellee** [comment]
Still a bug in version 7.3.2.

**Comment by ifrost** [comment]
Referencing series with `#` is the default behavior we probably don't want to change. As a workaround please reference to your series wrapping the hashtag with curly braces:

`foobar.size{#}b.avg` 
`foobar.size{#}B.avg`
`foobar.size{#}MB.avg`

This way Grafana will skip the interpolation and Graphite will run the same query as without the curly braces.

If you would like to change this behavior please raise a feature request in discussions: https://github.com/grafana/grafana/discussions.

You can read more about the new process of handling feature requests here: https://github.com/grafana/grafana/discussions/36963
