### ISSUE TITLE
Folder information in dashboard being imported should be respected

### ISSUE THREAD

**Issue by mitulk** [grafana/grafana#41620]
**What happened**:
Folder information specified in imported dashboard json is not being respected.

**What you expected to happen**:
Folder picker should default to correct folder.

**How to reproduce it (as minimally and precisely as possible)**:
Test.json:
{
  "annotations": {
    "list": []
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 3,
  "links": [],
  "liveNow": false,
  "panels": [],
  "refresh": "",
  "schemaVersion": 31,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "folderId": 1,
  "folderUid": "AzureMonitor",
  "timepicker": {},
  "timezone": "",
  "title": "Test Dashboard",
  "uid": "Test00003",
  "version": 4
}

![FolderIgnoredOnImport](https://user-images.githubusercontent.com/14897058/141356669-5d115adf-698d-4c22-a31c-5f7274a4b709.gif)
:

**Anything else we need to know?**

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mitulk** [comment]
Please LMK if I'm doing something wrong. 

Looks like the  dashboard API supports specifying the folder when updating - https://grafana.com/docs/grafana/latest/http_api/dashboard/#create--update-dashboard.

**Comment by ashharrison90** [comment]
can repro in main

**Comment by ashharrison90** [comment]
hi @mitulk 👋 

having had time to look at this properly, i don't believe there's a bug here after all.
whilst we do support specifying a `folderId` as part of the api (it's the same api call Grafana makes when you actually press the `Import` button), you'll notice it's outside of the `dashboard` property: https://grafana.com/docs/grafana/latest/http_api/dashboard/#create--update-dashboard

that `dashboard` property is the json you import, and the schema for that json [makes no mention of a folder id](https://grafana.com/docs/grafana/latest/dashboards/json-model/). so the `folderId`/`folderUid` props you've added to the json make the dashboard json invalid. at the moment we just ignore the invalid properties - in future we'll hopefully throw an error.

in terms of the UI, the behaviour is as expected. you import a dashboard, and it defaults to the general folder. 

hope that makes sense!
