### ISSUE TITLE
InfluxDB "WHERE value < number" forces string

### ISSUE THREAD

**Issue by ThomDietrich** [grafana/grafana#4163]
Hey there,
the query editor for InfluxDB will always convert "WHERE value < 500" to:
`WHERE "value" < '500'`
even though it should be the following in order to be evaluated as a number:
`WHERE "value" < 500`

In other words, only the second expression will produce a graph.
Bug or Feature? ;)

tested with InfluxDB 0.10 and Grafana 2.6.0

**Comment by torkelo** [comment]
Bug in InfluxDB horrible query language I would say, but I guess grafana needs to clean up and solve its mess

**Comment by aperdices** [comment]
Hello.

Seems that this issue is still present in  Grafana v3.1.0-beta1 (commit: v3.1.0-beta1) with InfluxDB 0.12.2 (running on Debian Jessie 64 bits).

Maybe a  regression bug?

![sshot01](https://cloud.githubusercontent.com/assets/17157223/16409471/fca24fa6-3d1d-11e6-8be9-70a8d8688247.png)
![sshot02](https://cloud.githubusercontent.com/assets/17157223/16409479/04aeadfc-3d1e-11e6-85a8-25fb93dd9d58.png)

**Comment by aperdices** [comment]
I'm wrong. It's not a regression bug!

Seems that now InfluxDB 0.13 needs the integer tag value to be quoted!!!

Grafana launch this query to get autocomplete data:
**SHOW TAG KEYS FROM "SensorInfo" WHERE "SensorId" = 208**

But backend responds:
**ERR: right side of '=' must be a tag value string**

Quoting the integer value works fine:
**> SHOW TAG KEYS FROM "SensorInfo" WHERE "SensorId" = '208';
name: SensorInfo
----------------
tagKey
DeviceId
DeviceName
OpcName
SensorId
SensorType
WaterMeterSerial**

Anyone can reproduce this behavior?

**Comment by randomname872634** [comment]
I've found this bug to be present as well.

Influxdb version: 1.3
Grafana version: 4.6.3

I think this screenshot might clear things up:

![screen shot 2018-01-01 at 20 57 59](https://user-images.githubusercontent.com/846783/34470654-875fb022-ef36-11e7-8075-b3a005c0a60e.png)

So when I execute the query `SELECT count("value") FROM "autogen"."BTScan_MK_Jeroen" WHERE ("value" = '0') AND time >= now() - 6h GROUP BY time(5m) fill(0)"`
 it returns no results. However when I execute the following query manually, it does return results:
`SELECT count("value") FROM "autogen"."BTScan_MK_Jeroen" WHERE ("value" = 0) AND time >= now() - 6h GROUP BY time(5m) fill(0)"`

Anyone know of a (temporary) workaround?

**Comment by meiXXI** [comment]
same problem here...

**Comment by nicolargo** [comment]
Same "issue" with Grafana 5.2.1

    SELECT mean("EngineeringValue") FROM /^$mnemo$/ WHERE ("System" = 'TEST' AND "ChannelId" = 2) AND $timeFilter GROUP BY time($__interval) fill(none)

works fine (graph is generated.

    SELECT mean("EngineeringValue") FROM /^$mnemo$/ WHERE ("System" = 'TEST' AND "ChannelId" = '2') AND $timeFilter GROUP BY time($__interval) fill(none)

did not work...

**Comment by sepo27** [comment]
Still exists 6.7.3.

**Comment by ThomDietrich** [comment]
@torkelo would it make sense to reopen the issue?

**Comment by vmartinv** [comment]
I'm using Grafana v8.0.6, the issue persists.
