### ISSUE TITLE
Formatting of Text panel (vertically) is not correct

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4164]
Formatting of Text panel (vertically) is not correct when there is a graph panel in a row and labels of the graph are placed in a table on Right side.

<img width="1377" alt="screen shot 2016-02-26 at 10 27 27 am" src="https://cloud.githubusercontent.com/assets/406777/13361452/8f9fc808-dc73-11e5-9846-d1ced711ebe4.png">

Even pulling the text panel down does not help.

<img width="1379" alt="screen shot 2016-02-26 at 10 27 13 am" src="https://cloud.githubusercontent.com/assets/406777/13361453/917b742e-dc73-11e5-951c-a3155f3ef1b5.png">

**Comment by torkelo** [comment]
Can't replicate this, http://play.grafana.org/dashboard/db/issue-4164

What version of Grafana are you using?

**Comment by deepujain** [comment]
grafana-3.0.0-pre1 .
Question, how do i upgrade grafana to future versions without having to recreate dashboards ?
