### ISSUE TITLE
Tempo trace view is empty

### ISSUE THREAD

**Issue by mdisibio** [grafana/grafana#41646]
**What happened**:
Viewed a trace in Grafana and it showed as empty Trace View.   See screenshot:
<img width="1279" alt="Screen Shot 2021-11-10 at 3 51 40 PM" src="https://user-images.githubusercontent.com/13524475/141473266-d695ad7e-6ffd-4e0c-8bc9-2715e33502f4.png">

Viewing json file also generates error "JSON is not valid OpenTelemetry format". See attached file:  
[3445f9d072022c34663a8d8df4ee7285.json.zip](https://github.com/grafana/grafana/files/7527819/3445f9d072022c34663a8d8df4ee7285.json.zip)

**What you expected to happen**:
The trace is not empty and contents should be shown.  

**How to reproduce it (as minimally and precisely as possible)**:
View the trace `3445f9d072022c34663a8d8df4ee7285` in internal environment, or view the attached json file.

**Anything else we need to know?**:
This trace is generated by [tempo-vulture](https://github.com/grafana/tempo/tree/main/cmd/tempo-vulture), so wondering if it is an issue with invalid trace data from tempo-vulture.

**Environment**:
- Grafana version: v8.3.0-41210pre (d5fc48028)
- Data source type & version: Tempo 1.2
- OS Grafana is installed on: Linux
- User OS & Browser: OSX, Safari & Chrome
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
The issue with upload should be fixed shortly by this https://github.com/grafana/grafana/pull/41455

**Comment by aocenas** [comment]
@mdisibio I am looking at the trace and the problem seems to be that the resource is empty: `"resource": {},`. Based on Otel types we use:
```
        interface Resource {
            attributes: opentelemetryProto.common.v1.KeyValue[];
            droppedAttributesCount: number;
        }
```
This seems to be non optional (otherwise it would be `attributes?: ...`) and based on this protobuff definition it also seems non optional if I read it right https://github.com/open-telemetry/opentelemetry-proto/blob/main/opentelemetry/proto/resource/v1/resource.proto.

**Comment by mdisibio** [comment]
> @mdisibio I am looking at the trace and the problem seems to be that the resource is empty

Can confirm that adding at least 1 resource attribute fixes the display.  I think it makes sense for tempo-vulture to populate the service name anyway, so created https://github.com/grafana/tempo/pull/1127.  Unless this is something you still want to address on the Grafana side, then ok to close this.  It's unlikely (impossible?) for a real workload to be missing resource attributes.

**Comment by mckn** [comment]
I'm closing this issue on request of the author.

**Comment by zalegrala** [comment]
Nice, thanks for the fix here @mdisibio.

**Comment by aocenas** [comment]
I will create separate issue for the error handling. Just silently not showing any data isn't what we should be doing in this case.
