### ISSUE TITLE
Panels not showing up when scrolling fast on mobile device

### ISSUE THREAD

**Issue by pkuehnel** [grafana/grafana#41658]
**What happened**:
When fast scrolling down a dashboard on a mobile device (tested only on Android + Chrome/Opera) not all panels get loaded. Even if I wait minutes, the panels do not appear, only a reload of the page + scrolling down slow enough let the panels appear.

First scrolldown slow, second scrolldown fast with bottom panels not showing up:
![GrafanaError](https://user-images.githubusercontent.com/35361981/141594371-f51237a0-d712-4abe-892b-6e466ba6b64a.gif)

**What you expected to happen**:
Panels should show up as soon as they are in visable area.

**How to reproduce it (as minimally and precisely as possible)**:
Open a dashboard with many panels on a Android phone, scroll down fast.

**Anything else we need to know?**:
In some constellations the panels appear when slowly scrolling back up again, but I am not sure how to reproduce this.

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: PostgreSQL 12.8 with TimescaleDb 2.5.0
- OS Grafana is installed on: Debian 10 (within docker container)
- User OS & Browser: Android & Chrome/Opera
- Grafana plugins: -
- Others: -

**Comment by mckn** [comment]
Feels like this is related to https://github.com/grafana/grafana/issues/40776

**Comment by pkuehnel** [comment]
is fixed in 8.2.4
