### ISSUE TITLE
Feature Request: time range for current day

### ISSUE THREAD

**Issue by ama4tf** [grafana/grafana#4165]
It would be great if there was an option in the time range for just the current day. I'm trying to run a metric that's integrating across the day to see if my two processes handle the same amount of data, however I don't want to do -24hr since that could cover data processed from yesterday's load

**Comment by torkelo** [comment]
The time picker already has relative time ranges like "Today", and "Today so far"

http://play.grafana.org/dashboard/db/today

**Comment by torkelo** [comment]
this was introduced in Grafana v2.5
