### ISSUE TITLE
Template variables for Elastic search not returning exact match

### ISSUE THREAD

**Issue by chaithrar** [grafana/grafana#4166]
Hi,

I am using grafan to show status of all disks present on  a node.
For this I have added templates which would list all Host IPs and its respective disks.

below are template queries used for retrieving hostip and diskman's

{"find": "terms", "field": "hostip", }  -- this would list all hostip in cluster
{"find": "terms", "field": "diskname",  "query": "hostip:$HostIp"} -- this should help list disknames for a given hostip

I am able to get all host IPs for the cluster.
But when I am trying to query Disknames for given Hostip

I am getting below response

**_dev, sda3, sda6 ,sda9_**

Instead of

**_/dev/sda3, /dev/sda6, /dev/sda9_**

How should I tune query so that I can get the exact match

**Comment by torkelo** [comment]
try putting single or normal quotes around $HostIp in the query
