### ISSUE TITLE
Regression: Template variables with asterisk '*' not handled via query params anymore?

### ISSUE THREAD

**Issue by cbrinker** [grafana/grafana#4167]
Just upgraded from v1.9 to v2.6.0 and noticed that urls with 

```
https://server/dashboard/db/my-dashboard?var-foo=something-*&var-bar=somethingelse
```

no longer work as they had in the previous version. If you specify "var-foo=something" it _does_ still work as intended, plus if  you type 'something-_' directly into the foo input box, it also works. So the scope of the bug is limited to the '_' character in a query param.

   I spent a lot of time in the javascript debugger, but could never identify where/when those values actually get interpolated into the panels. I did step through enough to verify that at the very least the selection mechanism does get the appropriate 'something-*' value+text string, but it must ignore or reset it at some later point.

Is there a quick work around that could be employed?

Thanks,
Chris

**Comment by torkelo** [comment]
it is handled but if you specify two variables in url, one can trigger an update in the other (if the second use the fist in it's definition), so the first one triggers an update of the second and their by overwriting the value set from the url.

**Comment by cbrinker** [comment]
Ok, I have seen the bug even when declaring a single variable like this:

```
https://server/dashboard/db/my-dashboard?var-foo=something*
```

**Comment by torkelo** [comment]
That is strange, that works here: http://play.grafana.org/dashboard/db/templated-graphs-nested?var-server=web_server*

**Comment by cbrinker** [comment]
I see. That is not what I am seeing... Going to attempt to cut this down to its core then and see what I uncover.

**Comment by cbrinker** [comment]
Ok, I was able to pare it down to the root cause. With the dashboard you have running at play.grafana.org. You should be able to exercise this bug by editing the dashboard like this Manage > Templating > Variables > $app > Edit > Check "Refresh on load"
Save dashboard, then again attempt to request
```
http://play.grafana.org/dashboard/db/templated-graphs-nested?var-server=web_server*
```
and I suspect you will see that the server select box will be set to "All". 

It looks like the root issue is that if a template variable is referred to in another template variable, the "Refresh on load" gets applied after the query params are set. 

For me I will go through and adjust all dashboards that have a template variable referencing another, and disable "Refresh on load". I'm not comfortable with angular.js to get a PR setup for this though.

**Comment by torkelo** [comment]
this seems to be fixed 
in 4.x
