### ISSUE TITLE
Grafana 8.1.7 Pie chart on mobile

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#41688]
in 7.3.X Grafana Pie Chart on mobile hide Graph and show only table with data. In 8.1.7 Pie Chart new is too big and users must slide to the rigth for see data. Some users didn`t understand where is data.

![image](https://user-images.githubusercontent.com/42611903/141788152-b0370d41-bb1a-4b03-bbc5-affabf352119.png)

Please check layout or give menu to set check bar if table didn`t insert all in window hide graph. 

**Environment**:
- Grafana version: 8.1.7
- Data source type & version: Zabbix 4.1.5
- OS Grafana is installed on: OEL7
- User OS & Browser: Mozilla/Safari/Chrome mobeli
- Grafana plugins:

**Comment by oscarkilhed** [comment]
Thinking we should set the max width of the legend to something like 99% when the legend is vertical.

**Comment by Tepew** [comment]
In the old version Pie Chart, it was that if the table did not fit, the graph was hidden.

**Comment by oscarkilhed** [comment]
Setting the max-width to 99% is essentially going to accomplish the same thing.

**Comment by Mihir-Bhasin** [comment]
Max width will do the job i guess.

**Comment by yessGlory17** [comment]
I want to work on this issue. Can you give me some information about the code? @oscarkilhed
