### ISSUE TITLE
UX: Bug: Master Branch: Dropdown elements not visible until hovered in Firefox

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4168]
Just an example to show the issue when editing datasource in Mozilla Firefox:

<img width="560" alt="screen shot 2016-02-26 at 7 04 25 pm" src="https://cloud.githubusercontent.com/assets/1019609/13370446/03d44922-dcbc-11e5-9a8b-cafc4f5c815b.png">

On Google Chrome, the dropdown values are visible.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
