### ISSUE TITLE
CloudWatch Logs: Non default regions does not seem to be sent for some queries

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#41689]
As seen here: https://github.com/grafana/grafana/pull/39290/files/e5e0ae1f9130208fdfc94b3d56021846386da153#diff-5195d59bff5abb37dceeb2ba37e2e0acb2f73f861fc83e320a72f6e7b2784f18R590 it seems like sometimes we don't send region from the query to the backend (like for autocomplete queries) which means we can get odd behavior if other then default region is used.

**Comment by aocenas** [comment]
This https://github.com/grafana/grafana/pull/42194 one fixed this for autocomplete requests but for log context there is a problem that we don't have direct access to it so the fix will be more complex probably.

**Comment by taleena** [comment]
Reviewed the priority with Cloudwatch team today, they agreed on the priority shift since the one piece has been done. The remaining piece is for log context as mentioned by @aocenas above.

**Comment by aocenas** [comment]
For context the [Log Context](https://grafana.com/docs/grafana/latest/datasources/loki/#log-context) is probably not widely used and not much documented apart form what I linked. Basically if you show logs from a query that does some filtering, there is a small `Show Context` on each log line and if clicked it should show sort of modal windows on top and bottom of the clicked log line and should show logs without the filtering right around the selected log line, hence giving you more context.

So for example when if you filter for errors and you have one that is relevant you can quickly see other logs that lead to that error.

Data source needs to implement this Interface to support it https://github.com/grafana/grafana/blob/4e1cf7dea7cf7481602b42828d1311db12b01644/packages/grafana-data/src/types/logs.ts#L150 and this is implementation for CW logs https://github.com/grafana/grafana/blob/590ea19c3f28bff4157c29105c3ead50a49a54ab/public/app/plugins/datasource/cloudwatch/datasource.ts#L436 and the query that gets the context logs does not get the correct region so probably always returns logs from the default region.

**Comment by iwysiu** [comment]
This is still an issue in Grafana 9 and can be reproduced in the explore tab with the `cloudwatch-plugin-logs` log group and a query of `fields @message | filter @message not like /Exception/`
