### ISSUE TITLE
Set Elastisearch as a datasource using grafana api

### ISSUE THREAD

**Issue by Dville007** [grafana/grafana#4170]
Hi guys,
I'm using Grafana 2.6 and elasticsearch 2.0 and I want to use grafana api (/api/datasources) in my java application to set elasticsearch as a datasource. To do that I started with a simple curl. 
i.e
curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" -d '{"name":"elasticsearchdatasource","type":"elasticsearch","url":"http://myelastisearchhost:9200","access":"proxy","password":"","user":"","basicAuth":true, "basicAuthUser":"basicuser","basicAuthPassword":"basicuser","Pattern":"Daily", "index": "*", "version": "2.x","isDefault":false}' http://admin:admin@localhost:3000/api/datasources 

  but using that curl I am not able to set properly the index name, pattern , and version.

Where am I going wrong?

Thanks for the concern.

**Comment by danievanzyl** [comment]
`{
  "name":"datasource_name",
  "type":"elasticsearch",
  "access":"proxy",
  "url":"http://127.0.0.1:9200",
  "password":"",
  "user":"",
  "database": "index_name",
  "basicAuth":false,
  "isDefault":false,
  "jsonData":{"timeField":"datetime", "esVersion": 2}
}`

Note the jsonData: When in doubt have chrome running in debug mode and see what the API calls are.

**Comment by Dville007** [comment]
Thanks @danievanzyl  ! it works now as expected.
