### ISSUE TITLE
Add support for Linux System namespace in Cloudwatch

### ISSUE THREAD

**Issue by davidjh** [grafana/grafana#4171]
This is the namespace used by Amazon CloudWatch command line tools.

Thanks!

**Comment by mtanda** [comment]
Not sure, what the "Linux System" namespace is.

http://docs.aws.amazon.com/AmazonCloudWatch/latest/cli/cli-mon-put-data.html
If it is the namespace specified by "--namespace" option, it can be set in datasource setting page in 3.0.0-pre1 build.
https://github.com/grafana/grafana/pull/3736

**Comment by mpareja** [comment]
If you're looking for the `Linux System` metrics they are actual under the namespace prefix `System/Linux`. As mentioned by @mtanda, you'll need to add this "Custom Metrics namespace" to your Cloudwatch data source settings in Grafana. 

See the blurb at the bottom of the the [Amazon documentation](http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/mon-scripts.html#script_viewmetrics).
