### ISSUE TITLE
Dashboard JSON model should contain repeated rows

### ISSUE THREAD

**Issue by mjsaarin** [grafana/grafana#41728]
**What happened**:

Repeated rows are missing from saved dashboard JSON model. I suppose this was introduced by https://github.com/grafana/grafana/pull/32436

**What you expected to happen**:

All rows should be present in the JSON model. This could be a selectable option.

**How to reproduce it (as minimally and precisely as possible)**:

Save dashboard with Grafana 7.x and 8.x and compare models.

**Anything else we need to know?**:

I have a separate web server that pulls the JSON model, parses the model, renders the images for different time ranges with Render API, and downloads the rendered images. The final images are again grouped by user group and when users visits the web site they see the graph for their groups' storage usage only. I would like to continue providing this service. Feel free to suggest alternate approaches, too.

**Environment**:
- Grafana version: 8.1.2 and 7.5.11
- Data source type & version: Prometheus
- OS Grafana is installed on: RHEL8
- User OS & Browser: FreeBSD 13 & Chromium 94
- Grafana plugins: Render
- Others:

**Comment by mckn** [comment]
@torkelo can you ship in here? I'm a bit confused on what to do here. Looks like this is removed by design.

**Comment by torkelo** [comment]
No, they should not, they have no reason to exist in the saved model, they would just take up unnecessary space and make dashboard diffs messy. 

They are a dynamic element depending on the current evaluation of the variable value they are based on
