### ISSUE TITLE
Embedded dashboard-solo url from scripted dashboard results in 404

### ISSUE THREAD

**Issue by sni** [grafana/grafana#41736]
**What happened**:
Using the embed url from a single panel share embed iframe results in 404 for scripted dashboards.
(It works ok for normal dashboards)

**How to reproduce it (as minimally and precisely as possible)**:
1. Start latest grafana docker: docker run --rm -ti -p 3000:3000 --name grafana grafana/grafana:8.2.4
2. Open example dashboard: http://localhost:3000/dashboard/script/scripted.js?rows=3&name=myName
as described in https://grafana.com/docs/grafana/latest/dashboards/scripted-dashboards/

![image](https://user-images.githubusercontent.com/150844/141966925-64953024-2b7d-44c8-ace4-3e9742709b33.png)

3. open share panel for first graph and select Embed tab.

![image](https://user-images.githubusercontent.com/150844/141967357-ba3bd4b7-5411-41d8-9502-3f074679d2f9.png)

4. Copy/paste the url from the iframe and open in a new tab, ex.: http://localhost:3000/dashboard-solo/script/scripted.js?rows=3&name=myName&orgId=1&from=1637036112265&to=1637057712265&panelId=1

![image](https://user-images.githubusercontent.com/150844/141967653-27e331dd-c426-446d-9498-1936c3858875.png)

![image](https://user-images.githubusercontent.com/150844/141967742-7a54e504-2e32-4a49-ab18-1cc8b598362a.png)

I noticed the none-scripted dashboards now use /d-solo/... embed url, so i tried that one as well but it results in a different not found page:

![image](https://user-images.githubusercontent.com/150844/141968076-66cd802a-6fe8-4b77-b4ab-b2f8d5544789.png)

**Anything else we need to know?**:
I was able to reproduce the issue starting with the latest release down till the 8.0.0. The last 7.x release 7.5.11 works fine.

**Environment**:
- Grafana version: 8.0.0 - 8.2.4
- Data source type & version: probably unrelated, issue occured with all datasources, ex.: example datasource
- OS Grafana is installed on: probably unrelated, tried docker and native installation
- User OS & Browser: probably unrelated (firefox and chrome)
- Grafana plugins: unrelated

**Comment by joshhunt** [comment]
Thanks for reporting the issue. 

Scripted Dashboards are deprecated and will be removed in a future release, and will not receive fixes for issues like this.

**Comment by sni** [comment]
According to https://github.com/grafana/grafana/issues/24059 there is still no replacement for scripted dashboards yet. Do you
have other information? Would be nice to see this working again until there is a way to replace it.
