### ISSUE TITLE
Forward OAuth Identity with elasticsearch datasource is not seding headers

### ISSUE THREAD

**Issue by Scotturbina** [grafana/grafana#41741]
When I turn on the Forward OAuth Identity and try to "Save and Test" it prompts a sign in pop-up, I fill this with my credentials but nothing happens.

I receive this error from chrome dev tools:` {"error":{"root_cause":[{"type":"security_exception","reason":"missing authentication credentials for REST request [/data_source/_mapping]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}}],"type":"security_exception","reason":"missing authentication credentials for REST request [/data_source/_mapping]","header":{"WWW-Authenticate":["Bearer realm=\"security\"","ApiKey","Basic realm=\"security\" charset=\"UTF-8\""]}},"status":401}`

What you expected to happen:

I expect the user credentials being forwarded without the pop-up

How to reproduce it (as minimally and precisely as possible):

I got Open Id as auth method for grafana.
My grafana config looks like this :

```
########################## Data Proxy #############################
    [dataproxy]
    logging = true
    send_user_header = true
```
I saw that this works according to the documentartion If my data source uses the same OAuth provider as Grafana itself, for example using Generic OAuth Authentication, my data source plugin can reuse the access token for the logged-in Grafana user. (https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/ )

Anything else we need to know?:

This is the configuration I am trying on grafana:

![141532333-4c35ca80-b983-4592-a282-b99a7ce6fb6d](https://user-images.githubusercontent.com/22263714/141993945-2b4b791f-6a59-4976-a8a1-8f3c6bdbff8a.png)

![image](https://user-images.githubusercontent.com/22263714/141994009-3e08a089-38b2-49d1-858f-971b412ab70d.png)

But Grafana keeps asking me for the credentials every time I want to test it as shown below

![image](https://user-images.githubusercontent.com/22263714/141994079-5578e5a3-af93-418f-b20e-a99ec574a4e3.png)

Also I am using Open ID with same client id and secret for Elastic(Kibana) and Grafana

Is there something am I doing wrong?

Environment:

Grafana version: 7.2.1
Data source type & version: Elasticsearch 7.9.1
OS Grafana is installed on: REHL
User OS & Browser: REHL 8.4 and google chrome
Grafana plugins:
Others:

**Comment by Elfo404** [comment]
moving this to @grafana/backend-platform

**Comment by wbrowne** [comment]
This should be fixed with https://github.com/grafana/grafana/pull/41352, which will roll out in Grafana v8.3.0
