### ISSUE TITLE
Feature request: Panel Tooltip/Help-Text

### ISSUE THREAD

**Issue by m-o-e** [grafana/grafana#4174]
Many charts need a bit more explanation
than can be fit into the title alone.

It would be great if each panel could be assigned a free-form
description, to be shown in a tooltip when either the panel-title,
or a small :information_source: icon is hovered.

**Comment by utkarshcmu** [comment]
Dupe of #4079

**Comment by m-o-e** [comment]
Indeed, thanks!

Closing this and following #4079
