### ISSUE TITLE
Loki: Incorrect syntax highlighting in query field when a string literal contains a number

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#41754]
**What happened**:

For a Loki query like: `{cluster="foo"} | logfmt | message=~"foo-0"` the part `-0` is highlighted. Example:

![image](https://user-images.githubusercontent.com/745532/142014254-690b10cd-6a3a-44d1-82f0-efd1b6b99c9f.png)

**What you expected to happen**:

There should be no extra highlight within the string literal.

**How to reproduce it (as minimally and precisely as possible)**:

Enter the query above to Loki query editor.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3
- Data source type & version: Loki
- OS Grafana is installed on: self managed
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: N/A

CC: @bboreham

**Comment by bay1877** [comment]
Hi, I have graphana started and am trying to figure this out. I have branch 8.3.3 checked out, and am able to reproduce the extra highlighting. Biggest struggle right now is finding where the highlighting is done, as I am rather unfamiliar with the codebase. Any tips or guidance? Thanks!

**Comment by ifrost** [comment]
Thanks @bay1877 for having a look at this 🤝 I wasn't able to reproduce it in `main`. I think it might have been fixed by https://github.com/grafana/grafana/pull/45962?

**Comment by bay1877** [comment]
Should we close this issue now that it is resolved on main and there is no intention of back porting it?

**Comment by ifrost** [comment]
@grafana/observability-logs-and-traces do you think we can close it now? also please check the comment added after merging https://github.com/grafana/grafana/pull/45962#issuecomment-1062977735

**Comment by gabor** [comment]
i think we can close this one. i understand there are other possible improvements to the colors, but we are planning to migrate to a monaco based query-field for Loki in the future, and we can continue improvements from there.
