### ISSUE TITLE
UI request: Use left panel for dashboard navigation

### ISSUE THREAD

**Issue by m-o-e** [grafana/grafana#4175]
### Observation:

The prominent _collapsible left panel_ currently
presents shortcuts to views that are almost never used:

- Data sources
- My Account
- My Organization
- Grafana Admin
- Logout

In contrast, the most common operation (switching dashboards)
is hidden behind a modal and requires two clicks.

### Problem:

This is backwards. Switching dashboards should be fast and take only one click.
Links to seldom needed views such as _Grafana Admin_ don't need to
be permanently visible in the sidebar.

### Solution:

1. Move all elements in the _collapsible left panel_ behind a ⚙-modal.

![](http://i.imgur.com/tu52r34.png)
2. Move the dashboard search/list view into the _collapsible left panel_.

![](http://i.imgur.com/4YdGKNq.png)

**Comment by torkelo** [comment]
Good suggestion, but opening the sidenav to navigate is as not faster than opening the dashboard picker. Most have the sidenav closed (as you want max space for the dashboard). 

But I like the idea of being able to pin certain favorite dashboards to the sidenav , but I dont think the sidenav is an appropriate place to quickly search through hundreds of dashbords.
