### ISSUE TITLE
Selecting time series in legend only partially greys out other time series

### ISSUE THREAD

**Issue by StephenKing** [grafana/grafana#41760]
**What happened**:

I clicked on one entry in the legend of [a graph](https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1). The names of other time series are greyed out, but their legend values (min/max/avg etc). stay normal.

![Screenshot 2021-11-16 at 17 03 00](https://user-images.githubusercontent.com/277561/142021757-43d926a6-40a5-46f4-a790-d1c2f29b691d.png)

**What you expected to happen**:
Legend values to be greyed out, as it is in the old graph panel (makes it also better readable)

**How to reproduce it (as minimally and precisely as possible)**:
Click the entry in the legend

**Environment**:
- Grafana version: 8.2.4
- Data source type & version: Time series
- OS Grafana is installed on: https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
If anyone wants to help / contribute, we need to pass the item disabled state here to the stats : https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/VizLegend/VizLegendListItem.tsx#L74

**Comment by StephenKing** [comment]
Awesome reaction time ❤️
