### ISSUE TITLE
UX Bug: Don't nag about unsaved changes when only Time Range was changed

### ISSUE THREAD

**Issue by m-o-e** [grafana/grafana#4176]
Grafana should not nag about unsaved changes when only the Time Range was changed.
It makes browsing the dashboards with an admin account rather tedious.

**Comment by utkarshcmu** [comment]
+1 but only after dashboard version history feature, then we can replace the changed version of the dashboard with an old version of it.

**Comment by m-o-e** [comment]
Hm. You mean so it can save a new revision whenever the time range is changed?

I don't think that would be desirable. I switch the time-range around all the time,
and really only want it to be saved when I click the save-button manually.

In fact, when tracking issues down across dashboards I often wish
there was a toggle to ignore the stored time-range altogether, and just
carry over the currently selected range.

**Comment by torkelo** [comment]
@m-o-e what version are you using? Time range has always been in ignored when checking for changes. This issue is not present in latest stable v2.6. 

I did found an issue in latest master where a time change can sometimes cause an unsaved changes warning (fixing now)

**Comment by m-o-e** [comment]
@torkelo I'm on 2.6.0. When I change the time range (using the selector on the top right), then try to switch to a different dashboard, I get the "Unsaved Changes" dialog.

**Comment by torkelo** [comment]
Try saving the dashboard after you open it. Does the issue still appear? It can't  replicated on 2.6 systems I have access to. One cause for the dialog is that the dashboard schema is old, so saving it could once could fix that  (Grafana automatically upgrades the dashboard schema on dashboard load )

**Comment by m-o-e** [comment]
Yes. It happens every time when the Time Range was modified since the last save.
`Load -> Save -> Change Time Range -> Switch` still gives the Popup.

Fwiw, Grafana was installed from the Ubuntu deb and shows 2.6.0 in the upper left. Browser is Chrome.
Anyway, it's not a showstopping issue. I'll just wait for the next version and report back if it still persists there (perhaps your fix from today resolves it).

**Comment by torkelo** [comment]
@m-o-e can you replicate the issue on this dashboard? 
http://play.grafana.org/dashboard/db/annotations

i have tested this in multiple v2.6 systems and dashboards (with chrome/firefox and ubuntu/windows), none show unsaved changes dialog warning

**Comment by m-o-e** [comment]
@torkelo Nope. This one works correctly for me (no popup after changing the Time Frame).

I can only guess perhaps the Ubuntu deb that I'm using was bundled from an older version?
However, seeing that `play.grafana.org` works correctly is re-assuring. Looking forward to the next release and will report back if the issue persists on there. :)

**Comment by kormat** [comment]
I can confirm i'm hitting this issue with grafana 2.6.0 from the official apt repo, on debian wheezy. Manually applying the change from https://github.com/grafana/grafana/commit/9cebcc45c197aee364e9a3d24bfa95a91da039cc doesn't seem to change anything.

**Comment by shamil** [comment]
Still experiencing the same issues on `3.1.1`
Each time I change time range, grafana nags about unsaved changes...

**Comment by torkelo** [comment]
Strange, can't replicate it here, have you opened the dashboard and saved it? That could remove the issue, as grafana tries to upgrade the dashboard scheme whe it loads the dashboard

**Comment by cweimann** [comment]
I'm a new user and am having this issue with 4.1.1.

**Comment by vacri** [comment]
I'm also a new user and am having this issue on 4.1.2, installed on debian stretch, using the official apt repo. Apart from prometheus also being installed. it's a fresh, virgin server.

The bug happens with the default 'admin' user, but not when logged in as a 'global user' with grafana admin and org admin privs.

**Comment by yosida95** [comment]
I'm experiencing this issue on Grafana v4.5.2 (commit: ec2b0fe) installed using the official apt repository. Also, this issue happens when I'm logging into Grafana with 'admin' user.

**Comment by rmandziarz** [comment]
Hi,
I have the same issue. I am getting "save changes" popup every time when I am changing time range. It's happening only for default admin account. My environment: Grafana 7.1.1 installed from official Helm chart. Is there any solution to fix it?
