### ISSUE TITLE
Alert groups panel filter does not work with dashboard variables

### ISSUE THREAD

**Issue by mrpaulmanley** [grafana/grafana#41767]
**What happened**:
Using dashboard variables to filter labels does not work as expected. I am using this with the alpha Alertmanager integration. In the Filter -> Labels section of the panel options, I cannot use **site=$site**. Using the literal name of a site does work (eg. **site=site1**)

**What you expected to happen**:
I expect the variable for  $site to be properly interpolated and for the list of alerts to be filtered

**How to reproduce it (as minimally and precisely as possible)**:
Add an alertmanager (native prometheus version) datasource that has active alerts.
Create a dashboard with an Alert groups panel using the alertmanager data source.
Add a dashboard constant variable
Attempt to use the variable in a filter

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.4
- Data source type & version: Alertmanager alpha
- OS Grafana is installed on: amazon linux
- User OS & Browser: Ubuntu chrome, edge, and chromium
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
We will delete the alert groups panel in the future, you can use the alert groups tab instead.
