### ISSUE TITLE
Docs: Explore + logs add information about type of parser we use to get level of logs

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#41774]
**What happened**:
Update documentation
Here: https://grafana.com/docs/grafana/latest/explore/logs-integration/#logs-visualization

From:
```For logs where a level label is specified, we use the value of the label to determine the log level and update color accordingly. If the log doesn't have a level label specified, we parse the log to find out if its content matches any of the supported expressions (see below for more information). The log level is always determined by the first match. In case Grafana is not able to determine a log level, it will be visualized with unknown log level.```

To: 
```For logs where a level label is specified, we use the value of the label to determine the log level and update color accordingly. If the log doesn't have a level label specified, we try to parse the log using logfmt and JSON parsers to find out if its content matches any of the supported expressions (see below for more information). The log level is always determined by the first match. In case Grafana is not able to determine a log level, it will be visualized with unknown log level.```

**Comment by achatterjee-grafana** [comment]
Done
