### ISSUE TITLE
Prometheus templating: label_values can not deal with multiple label selectors

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4177]
When using label helper functions in templating it's not possible to use multiple label selectors. The problem is that functions like `label_values` do not expect the metric to include any commas, which is valid though.

Examples:
* `label_values(my_metric{static="some value", dynamic="$dynamic"}, new_label)`
* `label_values(my_metric{label1="$label1", label2="$label2"}, label3)`

The regular expression `label_values_regex` needs to be changed to not split the expression on comma.

@mtanda

**Comment by mtanda** [comment]
Thanks for reporting.
https://github.com/grafana/grafana/pull/4178 should fix the issue.
Please test it :-)

**Comment by grobie** [comment]
Oh wow, thanks a lot for the speedy update! I'll try it out.

**Comment by Meghna-singh** [comment]
label_values((my_metric1{label1="$label1"}, label2),(my_metric2{label="$label"}, label3))
Is this not possible to get labels from two different metric ??
