### ISSUE TITLE
Inconsistency between graph (stack) visualisation

### ISSUE THREAD

**Issue by HashemTaheriSonos** [grafana/grafana#41773]
**What happened**:
In grafana 8.2.3 by having "graph (old)" (same happen even by changing it to "timeseries"), we have inconsistent visualisation of the values between each refresh while the stack mode is on. In the following gif you can observe that each time i'm pressing refresh, we have completely different visualisation. just in one case it's the one we expect, the rest are misleading.

The source of the values are CloudWatch metrics.

![grafana-issue](https://user-images.githubusercontent.com/80122300/142039249-15b3cbb5-c61d-461c-8f43-86da0d0f34f4.gif)

**What you expected to happen**:
This shot is what i expected to have persistently and seems correct:
<img width="844" alt="2" src="https://user-images.githubusercontent.com/80122300/142039574-4836f13c-cb20-48dc-a83c-d90a79684085.png">

**Anything else we need to know?**:
Thought be related to [this Description](https://github.com/grafana/grafana/issues/9705#issuecomment-349438920), but changing the interval time and period didn't improved the situation.

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: CloudWatch 5.0.0

**Comment by torkelo** [comment]
the stacking will look different depending on the order of the stacking, look like the order Cloudwatch returns series in is not deterministic. 

@sunker anyway to get the order to be the same? 

In the old graph, you can enable legend and a legend value in table mode you can enable sorting the the legend (series) by a legend value (click legend value header), this will sort series and impact the stacking order. This feature is not available in time series panel until 8.3

**Comment by sunker** [comment]
> @sunker anyway to get the order to be the same?

Yes definitely. This [issue](https://github.com/grafana/grafana/issues/41303) is a symptom of the same problem in the CloudWatch backend. We'll aim to have a fix ready for 8.3.0.

**Comment by HashemTaheriSonos** [comment]
@torkelo @sunker Thanks for your answers,
I would like to mention that each of the represented graph are coming from different query and are not from a single one, like below: 
![metric-query](https://user-images.githubusercontent.com/80122300/142244246-4f598a31-553c-4c7c-ba71-f147765900df.jpg)

And also I tried with the legends as table but have quite same behaviour and some times it went wrong as same as the previous case :
![query-issue](https://user-images.githubusercontent.com/80122300/142243576-2a557c3b-f941-4c06-b096-302d9d6cae25.gif)

**Comment by sunker** [comment]
Got it, thanks for the detailed description @HashemTaheriSonos. 

Seems like the issue here is that the grafana-plugin-sdk doesn't honor the order of queries. There's already an issue for this and I've added a comment [here](https://github.com/grafana/grafana-plugin-sdk-go/issues/366#issuecomment-972629938).
