### ISSUE TITLE
App plugins with no angular page are missing "enable" button

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#41772]
When loading an app plugin like:
https://github.com/grafana/grafana-k6-app

It never shows up and there is no way to enable it.

by the time you look, it may have "autoEnabled"=true in the plugin.json -- but that does not seem like a great solution!

**Comment by leventebalogh** [comment]
I will close this in favour of https://github.com/grafana/grafana/issues/41772.
(Reopen if you have objections)
