### ISSUE TITLE
Want to match aliasColors per panel resource even when using visualization "graph old" in v8.

### ISSUE THREAD

**Issue by SEIJIIWATA** [grafana/grafana#41782]
**Why is this component needed**:
In grafana v8, when "graph old" is used in visualization, when a panel is set for each graph component, the aliasColors change and become different even though they are the same resource.
The aliasColors will change when the data of the target resource is updated, but if the colors are different, it may be mistaken for other resources.
I know that it is possible to fix the aliasColors for each resource, but is there any way to unify the default colors for each resource?
___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:
I think it's in common use.
___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [x] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [x] Styling guidelines, specific color usage (if applicable).

**Comment by torkelo** [comment]
you would have to specify series overrides using a regex that will match all the possible names you want a resources to have

**Comment by SEIJIIWATA** [comment]
@torkelo -san
Is this problem expected to be resolved with grafana version up grade?
In which version was it fixed?
