### ISSUE TITLE
"Fill below to" does not work with Repeating panels

### ISSUE THREAD

**Issue by genedavis** [grafana/grafana#41784]
**What happened**:
I am trying to use "Fill below to" feature of the Time Series panel.  When I use it, I can select my "max" line, but the "Fill below to" is only to a "specific" Min_value - not a generic one.  As a result, I only see one of my repeated panels show the proper "Fill below to" behavior
![Screen Shot 2021-11-16 at 8 13 04 PM](https://user-images.githubusercontent.com/1200144/142133622-592bbd1c-cbf7-416a-89ca-22df789b6020.png)

You can see that the graph on the left demonstrates the proper fill-below-to, but the one on the right does not:

![Screen Shot 2021-11-16 at 8 13 22 PM](https://user-images.githubusercontent.com/1200144/142133683-94973cda-4cb4-4ca6-a701-609523a75646.png)

**What you expected to happen**:
I expect all panels in the repeated group to show the same "Fill below to" behavior (see picture)

**How to reproduce it (as minimally and precisely as possible)**:
Have enough simple data to graph two lines on a Timeline, call them min_val and max_val, each keyed off of a tag, for example:
Tag     Time             Min     Max
Tag1     TIme1             1          3
Tag1     Time2             2         4
Tag2     Time1             6        10
Tag2     Time2            7         11

Create a repeating  Timeline panel (repeat across tags)
Try to add Fill below to as a Custom Override - you have to select a specific series (Tag1) as the "below to" value.  When you look at the whole repeated graph, Fill Below To will work for Tag1 but not for Tag2

**Anything else we need to know?**:
There can be dozens or even hundreds of tags - you never know - so you can't enumerate them

**Environment**:
- Grafana version: 8.1.1, also tried on 8.2.3, 8.0.2, 7.5.11, 7.5.4
- Data source type & version: Postgres 13 with TimescaleDB 2.4
- OS Grafana is installed on: Ubuntu 18.04
- User OS & Browser: Mac Chrome, Safari
- Grafana plugins: none other than standard installed (this once worked for us when the Time series was a plugin back around 7.5.4?  If we can go back, we would consider
- Others:

**Comment by torkelo** [comment]
fill below to works by specifying what series to fill to, so in your repeated panels that series name will change, so you will have to change the override matcher to match by regex so they will match names for the repeated panels as well

**Comment by genedavis** [comment]
Thanks @torkelo but as you can see (in my example above) you are not even allowed to type in a regex in the fill below to field?

**Comment by genedavis** [comment]
Even when I try to manually edit the JSON to fill below to min_value.*, it just gets confused about filling below to "anything"

**Comment by genedavis** [comment]
Since this ticket is closed, I'm not sure I should hear back - if I don't I will file a new ticket thx

**Comment by genedavis** [comment]
@torkelo Since this ticket is closed, I will file a new ticket if I don't hear otherwise by Monday.  Thx

**Comment by genedavis** [comment]
Opening new ticket since this one is closed with no responses

**Comment by genedavis** [comment]
Note: this issue can stay closed - we were including tag_name as part of our query, which was not needed.  Once removed, it removed the specialized version of series names that might require regex to match.  I still think there may be a bug since "fill below to" does not support regex, but this is not a problem for us.
