### ISSUE TITLE
[prometheus] Link to graph should use current template variable values

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4179]
When using a query including template variables, the "Link to Graph in Prometheus" should replace the variables with the current values. This would match the behavior of promdash and be more useful. What do you think @mtanda?

**Comment by mtanda** [comment]
I agree with you :-)

What version are you using?
In current master, the variables should be replaced.
https://github.com/grafana/grafana/pull/3624

**Comment by grobie** [comment]
Ha! You're too fast. I think I wrote that issue when working from a plain 2.6.0 instance. It seems to work fine in master.
