### ISSUE TITLE
Move from Dashing to Grafana: Value widgets from External sources best practices

### ISSUE THREAD

**Issue by brpaz** [grafana/grafana#4180]
Hi.
I am new to Grafana and trying to compare it with [Dashing](http://dashing.io) to analyse the strengths and weakness of each solution. I know Grafana is much more powerful with graphs but Dashing is really simple to use for single value widgets and has a lot of plugins and integration's.
I would prefer to have a single dashboard solution, thats why I am opening this issue to try to understand if its possible to migrate some of the Dashing widgets to Grafana.

For example, Lets give the following use case: 
I want to display my website "up" status returned from a service Pingdom for example. I just want to display it like up/down and the latest check date. Something similar to this dashing widget (https://github.com/Edools/dashing-pingdom).

What would be the best way of doing it in Grafana? Should I build some kind of external script that fetches the status from Pingdom and then save the data into some Data Source supported by Grafana, like InfluxDb? Or it would be possible to create for example a custom Data source, which just fetch the required information from Pingdom and updates the widget accordingly?

Another simple use case would be to display some stats from Analytics tool like Google Analytics or MixPanel. In this case probably a custom Data Source would be the best approach?

Thank you.

**Comment by torkelo** [comment]
a custom panel or data source could work in your case, not sure what is best in your case
