### ISSUE TITLE
App: Change order of preloadings plugins and app rendering

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#41804]
**What happened**:
When starting the Grafana frontend app we will try to load all plugins with the `preload` attribute set to `true` prior to rendering the React app.

We should probably change this so it is done after the React app has been rendered. Before proceeding with this we need to verify that this won't break any plugins hence this issue.

```[tasklist]
### Tasks
- [x] Investigate impact of `preload` on load times
```

**Comment by sympatheticmoose** [comment]
@mckn is this still worth investigating?

**Comment by mckn** [comment]
> @mckn is this still worth investigating?

I'm not sure, we would need to look at the metrics and see how the `preload` feature affect the load times of Grafana. Lets get back to this one once we have looked at the metrics.

**Comment by mckn** [comment]
Closed by introducing the async loading.
