### ISSUE TITLE
grafana with lighttpd as proxy

### ISSUE THREAD

**Issue by miguelangel-percona** [grafana/grafana#4181]
The config is pretty simple, but still doesn't work:

`root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/`

Lighttpd:

```
$HTTP["url"] =~ "^/grafana/" {
        proxy.server = ( "" =>
        ( (
        "host" => "127.0.0.1",
        "port" => 3000,
        ) )
        )
        }
}
```

I keep getting 404:

`2016/02/28 15:33:11 [I] Completed 127.0.0.1 - "GET /grafana/ HTTP/1.0" 404 Not Found 2199 bytes in 2715us`

**Comment by miguelangel-percona** [comment]
Finally fixed. lighttpd was sending /grafana. To remove it it is needed to to a url rewrite, but url rewrite is doesn't work inside $HTTP["url"]. This is how it works:
```

$HTTP["url"] =~ "^/grafana(.*)" {
        proxy.server = ( "" =>
        ( (
        "host" => "127.0.0.1",
        "port" => 9001
        ) )
        )
        }
}

$SERVER["socket"] == ":9001" {
        url.rewrite-once = ( "^/grafana(.*)$" => "$1" )
         proxy.server  = ( "" =>
        ( (
        "host" => "127.0.0.1",
        "port" => 3000
        ) )
        )
}
```

**Comment by bergquist** [comment]
Thanks for reporting and solving this issue :) I hope people will find this issue if they run into the same problem.
