### ISSUE TITLE
Log Panel inconsistant cuts off row message

### ISSUE THREAD

**Issue by risoms** [grafana/grafana#41828]
**What happened**: Log panel inconsistently displays row content. Each row is left blank, aside the timestamp and index variables. 

**What you expected to happen**: All content available per row is expected to be displayed - especially content with short character length (5 letters or less)

**How to reproduce it (as minimally and precisely as possible)**: Create log panel with data source Infinity or Postgres.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.1.7 (34b8880d53)
- Data source type & version: Postgres and Infinity JSON
- OS Grafana is installed on: Linux4.4.0-210-generic #242-Ubuntu SMP Fri Apr 16 09:57:56 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- User OS & Browser: OS X 10.15.7 (19H1519), Chrome
- Grafana plugins: Log Panel
- Others:
![image](https://user-images.githubusercontent.com/10383917/142239623-6e5019c6-673b-4f60-8b8a-b9532d2ee02c.png)

**Comment by ivanahuckova** [comment]
@risoms logs panel shows only the first string field from your data. You can use organize fields transformation to choose the field you would like to select. If you would like to see multiple fields, I recommend to use table panel. 

https://user-images.githubusercontent.com/30407135/142622878-707ae8ed-51b2-4bf9-92e7-5f8ad2ff531e.mov

There is also this related feature request https://github.com/grafana/grafana/discussions/38290. So if this would be useful for you, please upvote and tell us why would it be useful. 🙂
