### ISSUE TITLE
sqlstore does not respect log.mode=console

### ISSUE THREAD

**Issue by nfnty** [grafana/grafana#4182]
```
[log.go:75 Fatal()] [E] fail to initialize orm engine: sqlstore.init(fail to create xorm.log): open /usr/share/grafana/data/log/xorm.log: no such file or directory
```

**Comment by torkelo** [comment]
please describe more what your talking about, what your config is etc

**Comment by nfnty** [comment]
Exactly what it says. sqlstore tries to write to `xorm.log` even though `log.mode` is set to `console`

Here's a patch I applied to quicky fix the problem:
https://github.com/nfnty/pkgbuilds/blob/master/grafana/sqlstore_console.patch

**Comment by nfnty** [comment]
@iwinux is having the same problem: #2508

**Comment by torkelo** [comment]
@nfnty ok, thanks for clarifying the issue a bit with an actual description. The xorm log should only be created in dev mode, fixed now, thanks for reporting this.
