### ISSUE TITLE
Diagnostic tool to log duplicate usernames AND/OR email addresses in use for admin review

### ISSUE THREAD

**Issue by pkolyvas** [grafana/grafana#41832]
As an administrator, I'd like to be able to review where I might have multiple versions of the same account as a result of Grafana's current case-sensitive usernames and email addresses.

Grafana should be able to provide a list of duplicate user accounts (based on username AND/OR email address) for administrators. Currently, we expect to do this via Grafana's standard logging interface, but the design of the solution is open-ended at the time of issue filing.

**Comment by eleijonmarck** [comment]
This issue https://github.com/grafana/grafana/issues/52345 replaces this one. Closing of this one
