### ISSUE TITLE
Selecting a dashboard / viewing - HTTPD processes 100%

### ISSUE THREAD

**Issue by Bonn93** [grafana/grafana#4184]
Weird discovery this morning, when opening a dashboard, there was no response with only the loading icon in the top right of each item. Similar issue observed when system CPU is very high or high disk IO ( such as backups or a scheduled task ). 

HTTPD Processes were chugging all the CPU. Diving in a little more, I've been able to replicate that when I restart both services, open a dashboard, the CPU shoots to 100%.

With debug logs enabled on both, I can see that HTTPD is a proxy for the grafana service?, however I can't seem to get anymore logging or details from this. Able to replicate each and everytime on any dashboard. 

CentOS7, Apache 2.4.6,  Grafana - Version: 2.6.0, Commit: v2.6.0,

**Comment by torkelo** [comment]
maybe an issue with your apache setup? httpd is usually the apace process and not related to grafana

**Comment by Bonn93** [comment]
Datasource was the cause... it seems it hits apache very, very hard. Was in the end a credential / url issue.

**Comment by hah2930** [comment]
I have the same issue. @Bonn93 would you mind explaining what did you do to fix this? Thanks!
