### ISSUE TITLE
3.0 Branch / Issue Tracking

### ISSUE THREAD

**Issue by dan-cytexone** [grafana/grafana#4186]
Hello

Where should we be putting 3.0 bugs and other items?  It's very hard to find 3.0.  I've only found it on this page - http://grafana.org/download/builds.html

It looks really awesome and I'm super excited about it. 

Dan

**Comment by bergquist** [comment]
Please post all the bugs here on Github. This is the only issue tracker we are using at the moment.
Regarding 3.0 visibility we are not promoting it very much yet since it not even beta.
