### ISSUE TITLE
Auto refresh is reset from linked dashboard even if "Keep current time range" is checked

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#4188]
1. In the settings of a dashboard, add a link to dashboards (I'm using a tag to show a dropdown). Check "Keep current time range"
2. Set the time range to something (e.g. last 15 minutes) and set auto refresh to something (e.g. every 5 seconds)
3. Click the link to one of the linked dashboards
4. Observe new dashboard opens with same time range (here: last 15 minutes), but auto refresh interval reset to "off"

Expected:
4. Observe new dashboard opens with same time range (here: last 15 minutes), and same auto refresh interval (here every 5 seconds)

Grafana v2.6.0

**Comment by torkelo** [comment]
auto refresh setting is not considered part of the "current time range"

**Comment by jessetan** [comment]
In that case, can there be a "Keep current auto refresh" option?
