### ISSUE TITLE
Revised Modal Designs

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#4191]
New designs to bring modals into the design styles of 3.0. 

Note: the gradient should continue around the active tab, as is already in Grafana. I was just not easily able to replicate with Omnigraffle. 

**No tabs**
For use on modals like "Invite New Users"
![modal-notabs](https://cloud.githubusercontent.com/assets/2886187/13394238/0fcd378a-df22-11e5-8411-5e863b7dea01.png)

**Short tabs**
Replicating the panel tab style
![modal-shorttabs](https://cloud.githubusercontent.com/assets/2886187/13394239/0fcf7e8c-df22-11e5-9f8c-8cd9828e708c.png)

**So many tabs**
When the tab options exceed the width of the modal + header, drop tabs to next line.
![modal-longtabs](https://cloud.githubusercontent.com/assets/2886187/13394237/0fcadb66-df22-11e5-8f1b-b2a2e337c16f.png)

**Comment by torkelo** [comment]
Implemented! 

![image](https://cloud.githubusercontent.com/assets/10999/13474055/97f9db2c-e0bc-11e5-974c-e1fceffad9fc.png)

![image](https://cloud.githubusercontent.com/assets/10999/13474154/07532938-e0bd-11e5-9143-447f10758736.png)

![image](https://cloud.githubusercontent.com/assets/10999/13474247/6b0356ce-e0bd-11e5-9ad4-af4a6c1c4954.png)

**Comment by daniellee** [comment]
very nice!
