### ISSUE TITLE
Value mapping not working correctly for 2nd secondary axis

### ISSUE THREAD

**Issue by RkcCorian** [grafana/grafana#41920]
**What happened**:
![image](https://user-images.githubusercontent.com/79741077/142486067-b819cb2f-13e7-46de-a557-641930a22610.png)

**What you expected to happen**:
I created 2 times (both second axis) the value mapping equaly, which means for the region between 0.1 … 0.9 I would like to see nothing. It is working for the left second axes but does not work for the right second axis. I heavily asume a bug in grafana.
![image](https://user-images.githubusercontent.com/79741077/142486182-b853bb14-cfeb-40dd-a2eb-896138cd9b6f.png)

**How to reproduce it (as minimally and precisely as possible)**:
Create a second secondary axis. For a range, e.g. between 0.1 to 0.9, assign "nothing" / empty value. This is working for a single second axis (compare second screenshot above) but not for a second (compare first screenshot above)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana version 8.2.3
- Data source type & version: influxDB2.0.8
- OS Grafana is installed on: Synology Docker
- User OS & Browser: Windows / Android / Edge / Fully Browser
- Grafana plugins: None
- Others: See also https://community.grafana.com/t/value-mapping-not-working-for-second-axis/55927

**Comment by torkelo** [comment]
Was not able to replicate this:
https://play.grafana.org/d/N3aJV357k/2-axis-and-value-mappings?orgId=1&editPanel=2

![Screenshot from 2021-11-19 07-31-10](https://user-images.githubusercontent.com/10999/142576167-5e1c0892-e878-48b8-af90-5cb077d7e961.png)

**Comment by torkelo** [comment]
Works with ranges as well, we do not support empty string value, this is seen as "not set" so is ignored 
![Screenshot from 2021-11-19 07-34-46](https://user-images.githubusercontent.com/10999/142576430-99f82e52-ab06-466a-bde1-8a4d4e293e6b.png)

**Comment by RkcCorian** [comment]
Hmmm... then it is a bug that it is working with me with the first seconday axis?!

What can I do then? In my opinion it is a valid use case for all data where a state is behind. I would heavily request this as a feature. Where can I do this? Many thanks!

Compare also some of my graphs, where I have several states on secondary axis. The look really ugly with "-" or some other sign.

Some of my graphs as examples...
![image](https://user-images.githubusercontent.com/79741077/142578916-5e39eeb2-c9b5-4e61-84e4-08e31a5d6f44.png)
![image](https://user-images.githubusercontent.com/79741077/142578866-25594d04-7a96-46e1-8c20-4c5e2c1a6e09.png)

**Comment by torkelo** [comment]
If you use the panel inspect / JSON you can edit the json model and add a `" "` white space string to the value mappings model manually and with this it works, just the value mappings editor that is trimming the empty string and removing it the text 

![Screenshot from 2021-11-19 08-44-54](https://user-images.githubusercontent.com/10999/142584866-235da790-3853-401b-a1fc-4d3e28ac067b.png)

**Comment by RkcCorian** [comment]
Ahh, I didn't know the possibility with the JSON Editor, thx!

Isn't this still a problem with the editor?! For this I would then request an enhancement / bugfix.

Till this time I can workound manually and it look now correct...
![image](https://user-images.githubusercontent.com/79741077/142596345-fa89491e-1189-47b8-9e3b-aef189de9448.png)
