### ISSUE TITLE
'Failed to close response body' error after upgrade golang net/http

### ISSUE THREAD

**Issue by drTr0jan** [grafana/grafana#41924]
**What happened**:
Various errors like `Failed to close response body` are appeared in log after build Grafana with Go 1.17.3.
```
root@beastie:/var/log/grafana# tail grafana.log
t=2021-11-18T18:50:54+0000 lvl=warn msg="Failed to close response body" logger=plugins err="context canceled"
t=2021-11-18T19:10:54+0000 lvl=warn msg="Failed to close response body" logger=plugins err="context canceled"
t=2021-11-18T19:10:54+0000 lvl=warn msg="Failed to close response body" err="context canceled"
t=2021-11-18T19:20:54+0000 lvl=warn msg="Failed to close response body" err="context canceled"
t=2021-11-18T19:30:54+0000 lvl=warn msg="Failed to close response body" logger=plugins err="context canceled"
t=2021-11-18T19:50:54+0000 lvl=warn msg="Failed to close response body" logger=plugins err="context canceled"
t=2021-11-18T20:00:54+0000 lvl=warn msg="Failed to close response body" err="context canceled"
t=2021-11-18T20:10:54+0000 lvl=warn msg="Failed to close response body" logger=plugins err="context canceled"
t=2021-11-18T20:10:54+0000 lvl=warn msg="Failed to close response body" err="context canceled"
t=2021-11-18T20:20:54+0000 lvl=warn msg="Failed to close response body" logger=plugins err="context canceled"
```
**What you expected to happen**:
There're no errors while build with Go 1.17.2

**How to reproduce it (as minimally and precisely as possible)**:
Build Grafana with Go 1.17.3

**Anything else we need to know?**:
It looks like the bug is appeared after https://github.com/golang/go/commit/f9cb33c7c9d48fd0c38d17a659d5e968de648d40

**Environment**:
- Grafana version: 8.2.3-8.2.5
- OS Grafana is installed on: FreeBSD 12/stable

**Comment by zserge** [comment]
Likely to be related with the HTTP/2 changes you've mentioned.
Just to confirm, can this issue be reproduced with `GODEBUG=http2server=0`?

**Comment by drTr0jan** [comment]
@zserge, yep, the issue is reproduced with `GODEBUG=http2server=0`.

**Comment by marefr** [comment]
@zserge can you provide some more information here. Not sure there's something we should do or if this happens when http2 is not supported?

**Comment by marefr** [comment]
Based on the amount of [open issues](https://github.com/golang/go/issues?q=is%3Aissue+milestone%3AGo1.17.4+is%3Aopen) related to HTTP2 targeted for Go 1.17.3 I would strongly advice using an older Go version until Go 1.17.4 is out

**Comment by marefr** [comment]
@drTr0jan are you running Grafana with HTTP2 ([h2](https://grafana.com/docs/grafana/latest/administration/configuration/#protocol)) enabled?

**Comment by drTr0jan** [comment]
@marefr, nope, I'm running Grafana with HTTPS (`protocol = https`) enabled.

**Comment by marefr** [comment]
Tested locally with Go 1.17.3 and I see similar issues:
```
t=2021-11-24T11:27:19+0100 lvl=warn msg="Failed to close response body" logger=update.checker err="context canceled"
t=2021-11-24T11:27:19+0100 lvl=warn msg="Failed to close response body" logger=plugin.manager err="context canceled"
t=2021-11-24T11:27:42+0100 lvl=warn msg="Failed to close response body" logger=avatar err="context canceled"
t=2021-11-24T11:37:19+0100 lvl=warn msg="Failed to close response body" logger=plugin.manager err="context canceled"
```

Seems like https://github.com/golang/go/issues/49366 is the same bug as we see. With that seems like there's an issue with setting a timeout on HTTP clients which is something we do a lot, especially for most of the data sources. We definitely need to wait for Go 1.17.4.

**Comment by marefr** [comment]
I'm closing this in favor of #42253. Please subscribe to that issue to get a notification when it's closed/fixed.

**Comment by drTr0jan** [comment]
There're no errors in log after building by Go 1.17.4.
Thx.
