### ISSUE TITLE
GF_APP_MODE env variable should be respected

### ISSUE THREAD

**Issue by altokarev** [grafana/grafana#41921]
**What happened**:
Grafana instance configured via env variables doesn't respect `GF_APP_MODE` variable

```
/usr/share/grafana $ ENV | grep GF_APP_MODE
GF_APP_MODE=development
```
<img width="719" alt="CleanShot 2021-11-18 at 23 12 04@2x" src="https://user-images.githubusercontent.com/28726429/142489929-5b6b2c04-1808-4f05-9418-154f09389477.png">

**What you expected to happen**:
`GF_APP_MODE` env variable should be respected and switch the app mode as it should

**How to reproduce it (as minimally and precisely as possible)**:
Plain Kubernetes installation of `grafana/grafana:8.2.5` configured with env vars

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: -
- OS Grafana is installed on: Docker image on Kubernetes v1.19
- User OS & Browser: macOS Monterey 12.0.1 (21A559), Google Chrome 96.0.4664.45 (Official Build) (x86_64)
- Grafana plugins: lots
- Others: -

**Comment by mckn** [comment]
Hello, thanks for opening this issue however I think you have provided the environment variable incorrect. The pattern is as following `GF_<SectionName>_<KeyName>` and the `app_mode` key is part of the `default` section.

Please try to specify the value accordingly: `GF_DEFAULT_APP_MODE`.

For more information: https://grafana.com/docs/grafana/latest/administration/configuration/#override-configuration-with-environment-variables

**Comment by altokarev** [comment]
Yep, using `GF_DEFAULT_APP_MODE` helped.

Thanks, Marcus! 🙌

**Comment by mckn** [comment]
> Yep, using `GF_DEFAULT_APP_MODE` helped.
> 
> Thanks, Marcus! 🙌

np, happy that it worked :)
