### ISSUE TITLE
UX Improvement in master: Inconsistency in showing dashlist

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4194]
Starred dashboards dashlist shows dashboard titles whereas last viewed dashlist shows dashboard slugs:

<img width="1428" alt="screen shot 2016-02-29 at 8 40 10 am" src="https://cloud.githubusercontent.com/assets/1019609/13401291/6786b29c-dec0-11e5-8271-0b0a38978077.png">

Expected Behavior: Last viewed dashlist should also show Titles instead of dashboard Slugs.

**Comment by torkelo** [comment]
Yes, I thought they would do that as well
