### ISSUE TITLE
Values shown on the bars does not get refreshed on updating time range 

### ISSUE THREAD

**Issue by vishynit** [grafana/grafana#41952]
**What happened**:
Whenever the time range is updated on dashboard, the bars on the bar chart gets resized based on the new data but the values shown on the bars does not get refreshed. Clicking on the legends updates the values.

**How to reproduce it (as minimally and precisely as possible)**:
Set **Bar Chart -> Show Values** option to "Always". Use bar chart to plot data, update time range and check the values appearing on top of Bar. Hover on the bar to show the tooltip which has correct values.

![RecordingApp_Monitor](https://user-images.githubusercontent.com/52401068/142609827-d063fb1f-8f0c-417a-a2f8-c17227647e91.gif)

**Anything else we need to know?**:
Data is being pulled from GraphQL API using Infinity Data source plugin. 

**Environment**:
- Grafana version: 8.1.2
- Data source type & version: Infinity 0.7.8
- OS Grafana is installed on: Ubuntu
- User OS & Browser: OS - Mac , Browser - Chrome
- Grafana plugins: Bar Graph
- Others:

**Comment by torkelo** [comment]
This seems fixed in 8.2, try upgrading

**Comment by torkelo** [comment]
If you still get this in 8.2 please ping with a comment here and I will re-open

**Comment by leeoniya** [comment]
was fixed by https://github.com/grafana/grafana/pull/39188

**Comment by vishynit** [comment]
Thanks @torkelo @leeoniya I will update to 8.2 and confirm.
