### ISSUE TITLE
Chore: make sure we don't bundle @testing-library/* in our production app bundle

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#41970]
**What happened**:
If you do a scan on our app bundle it looks like there are some dependencies related to `@testing-library` that should not be required during run time and hence not included in the bundle.

**How to reproduce it (as minimally and precisely as possible)**:
Go to this URL to inspect the bundle.

https://bundlescanner.com/bundle/grafana-assets.grafana.net%2Fgrafana-pro%2F8.2.3-40566%2Fpublic%2Fbuild%2F8529.6cba7c8cda85920f6f36.js?website=play.grafana.com

**Environment**:
- Grafana version: 8.2.3

**Comment by leeoniya** [comment]
also

- @welldone-software/why-did-you-render
- semver
- json-source-map
- debug
- sizzle (separately from jquery)

**Comment by tolzhabayev** [comment]
@mckn we seem to have decided to expose a helper test util via `@grafana/ui` package which leads to this @testing-library being bundled in.

Here is the original [PR](https://github.com/grafana/grafana/pull/36398)
Here is where it's exposed: https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/index.ts#L200
Here is an example of usage in a test: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/components/QueryEditor/QueryEditor.test.tsx#L80

@leeoniya Please create separate issues per package for these, I am pretty sure every one of them has it's own reason to be there which has to be clarified separately.
