### ISSUE TITLE
Dashboard: Data source picker doesn't show tracing data sources 

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#41976]
**What happened**:
Data source picker doesn't show tracing data sources in main selection:
![image](https://user-images.githubusercontent.com/30407135/142634614-8cfba5de-4227-41d9-859e-a735350cfe2a.png)

To use tracing data source, you have to choose `mixed` data sources and then pick tracing one.
![image](https://user-images.githubusercontent.com/30407135/142633171-93d2b377-0a63-4513-8aa0-311f546b5e1c.png)

We should show all available data sources, not just the metrics ones. We also have now different visualisations for non-metrics data - node graph, logs panel,... 

Here - the datasource picker has `metrics` check: https://github.com/grafana/grafana/blob/main/public/app/features/query/components/QueryGroup.tsx#L184-L190

**Comment by torkelo** [comment]
@ivanahuckova it's not added here:
https://github.com/grafana/grafana/blob/main/public/app/features/query/components/QueryGroup.tsx#L187

**Comment by torkelo** [comment]
@ivanahuckova maybe tempo data source is missing metrics: true property in plugin.json (this signals to Grafana that it implements the query function and is not just an annotation data source)

**Comment by ivanahuckova** [comment]
@torkelo I'll implement `metrics=true` for tracing data sources (tempo, jaeger, zipkin). Should I leave this open so at some point we'll refactor this, so all data source don't have to add `metrics=true`? Or there is no plan to do this and I should close the issue?

**Comment by torkelo** [comment]
@ivanahuckova there is no plan, as we still have data sources that does not implement metrics query function, but maybe it should default to true?

**Comment by ivanahuckova** [comment]
I am not sure, but it seems non-intuitive to add `"metrics": true` to tracing data sources so they appear in data source picker in dashboard. And also, if metrics is not true, you can still access it trough mixed data sources. 🤔  So thinking about it - I would vote yes - it should default to true and if you don't want to have it in dashboard data source list, then specify it in plugin.json.

**Comment by joshhunt** [comment]
@torkelo What's your thoughts on how to continue with this?

I agree with how `metrics: true` might not be immediately obvious for how to make a data source show up in the list, but I think it might just be a quirk from confusing naming?

Alternatively, should we add `tracing={true}` to `<DataSourcePicker />`?  Is there already a filter on the data sources to make sure that only those that implement `.setQueryEditor()` show up?

Otherwise, I think we just do nothing and continue with `metrics: true`. Thoughts?

**Comment by torkelo** [comment]
I don't have any strong thoughts, adding tracing={true}  looks like the best option judging from what @aocenas said

**Comment by aocenas** [comment]
Yeah I guess here are my thoughts on this: https://github.com/grafana/grafana/pull/41974#issuecomment-976529932

Basically thinking about these matadata on data source as "what capabilities does a data source have". So metric=true for me means it can query something that returns time series data. This may be important for things like linking trace data source to logging data source, where we want to offer only trace data sources. There is no specific contract or API that needs to be supported but this gives at least some hint for these kinds of usecases.

**Comment by ivanahuckova** [comment]
@joshhunt in this case, when you add `tracing=true` to the dashboard data source picker, could you as a part of the PR remove `metrics:true` from jaeger, zikpin and tempo's `plugin.json` that I've added in https://github.com/grafana/grafana/pull/41974

**Comment by ivanahuckova** [comment]
Fixed
