### ISSUE TITLE
Order of plugins on left-hand sidebar is changes on refresh 

### ISSUE THREAD

**Issue by dimitarvdimitrov** [grafana/grafana#41987]
**What happened**: After refreshing grafana the order of plugins on the left-hand sidebar keeps changing. This is uncomfortable because I usually know where to click due to muscle memory. Instead I need to look at all plugins we have installed and find the one that I need. This becomes worse with more plugins.

![DeepinScreenshot_select-area_20211119160841](https://user-images.githubusercontent.com/21020035/142646051-4b230eda-7674-42ce-9b80-dec25ccd66e8.png) | ![DeepinScreenshot_select-area_20211119160754](https://user-images.githubusercontent.com/21020035/142646053-548d00f7-41a8-45bf-8944-2830cd93be20.png)

**What you expected to happen**: Plugin order persists between browser refreshes.

**How to reproduce it (as minimally and precisely as possible)**:
1. Open grafana
2. Install at least 2 plugins
3. Refresh grafana

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.2.2 (6232fe07c0)
- Data source type & version: n/a
- OS Grafana is installed on: linux/docker
- User OS & Browser: linux & google chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by ashharrison90** [comment]
will be fixed in 8.3 by https://github.com/grafana/grafana/pull/40078
