### ISSUE TITLE
Text Panel: Add support for markdown tables

### ISSUE THREAD

**Issue by sslupsky** [grafana/grafana#4198]
The following table does not render in Grafana:

```

| Col 1 | Col 2 | Col 3 | Col 4 |
|-------|-------|-------|-------|
|       |       |       |       |
|       |       |       |       |
|       |       |       |       |
|       |       |       |       |
|       |       |       |       |
|       |       |       |       |
|       |       |       |       |

```

This is how it should look:

| Col 1 | Col 2 | Col 3 | Col 4 |
| --- | --- | --- | --- |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |
|  |  |  |  |

**Comment by mtanda** [comment]
The library [remarkable](https://github.com/jonschlinkert/remarkable) support table, I think it is only CSS styling issue.

**Comment by sebastian-azeti** [comment]
+1 for this feature. We use text boxes to explain to the customers meaning of graphs and tables are great to do so.

**Comment by mtanda** [comment]
![image](https://user-images.githubusercontent.com/224552/32239521-1d657638-beae-11e7-911d-6fec2d186e76.png)
Seems to work in latest Grafana.
