### ISSUE TITLE
docs: update documentation for Cloud Monitoring

### ISSUE THREAD

**Issue by vickyyyyyyy** [grafana/grafana#42007]
Update our screenshots and the names of some of the options may have also changed

**Comment by Lucifergene** [comment]
Hi
I want to work on this issue. I have checked and have noted the changes. 
Can you please assign this to me?

**Comment by vickyyyyyyy** [comment]
hi @Lucifergene we don't normally assign issues to external contributors (for more information please see https://github.com/grafana/grafana/blob/main/CONTRIBUTING.md)

Please feel free to submit a PR for this and we will review it as soon as we can. Thanks!
