### ISSUE TITLE
Connect null values setting not working on time-series with multiple lines

### ISSUE THREAD

**Issue by GamerBene19** [grafana/grafana#42008]
**What happened**: Null values are connected despite setting beeing set to `threshold <1m`

**What you expected to happen**: Null values not to be connected

**How to reproduce it (as minimally and precisely as possible)**:
1. Have data that consists of multiple "lines" (e.g. CPU Utilisation per host for multiple hosts)  
I can provide some if needed
2. Create time-series graph out of that data
3. Set `connect null values` threshold (`none` also has the same behaviour)
4. Observe how lines ares still connected (also see picture two below)

**Anything else we need to know?**: Setting does work for graph with one line only (see picture one below)

**Environment**:
- Grafana version: Happend on 8.1.6, still happening on 8.2.5
- Data source type & version: Telegraf logging to InfluxDB 2.0
- OS Grafana is installed on: Ubuntu 20.04, fully up to date
- User OS & Browser: Windows/Linux with Firefox (but issue is independent of browser)
- Grafana plugins: None iirc

![Picture one](https://user-images.githubusercontent.com/20821976/142683262-586cafb1-f733-4f0f-892e-7422c2262778.png)
![Picture two](https://user-images.githubusercontent.com/20821976/142683463-428d542d-0624-49db-84eb-b4f4f23a6725.png)

**Comment by leeoniya** [comment]
do you actually have `null` values in your data? or are you expecting this option to `null` values into adjacent points over this threshold?

**Comment by GamerBene19** [comment]
Sorry for the late reply, weekend was a bit busy...
As far as I can tell I _do_ have`null` values (see screenshot)
![grafik](https://user-images.githubusercontent.com/20821976/142779261-c5ce62e9-b92f-49be-ac63-66501efed7d1.png)

Also the first graph shows different behavior from the second with same data structuring.

**Comment by zuchka** [comment]
@GamerBene19 I'm wondering if it would help if you [shared the raw, unformatted data](https://cln.sh/PTgRFb) for that first graph 👍

**Comment by GamerBene19** [comment]
A little correction: Your initial assumption was right.
I think its a problem on my end after all. The above data actually is from the upper graph (where "it works"). The data for the graph(s) were it doesn't work looks like this:
![grafik](https://user-images.githubusercontent.com/20821976/142997027-c5c5aec2-4880-456d-adc6-b544bf0f748f.png)
So it appears that there is something in my query is causes the null values to be filtered out.

**Comment by GamerBene19** [comment]
And just a second later I figured out what is causing it...
My query looks like this
```
from(bucket: "${bucket}")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "system")
  |> filter(fn: (r) => r["_field"] == "cpu")
  |> filter(fn: (r) => r["object"] == "lxc")  
  |> aggregateWindow(every: v.windowPeriod, fn: mean)
  |> filter(fn: (r) => r["_value"] > 0 )
  |> keep(columns: ["_time","host","_value"])
  ```
  if I comment out ` |> filter(fn: (r) => r["_value"] > 0 )` (which I added to filter out inactive hosts) it works just as intended.

**Comment by zuchka** [comment]
@GamerBene19 super! Great to hear you're unblocked now 😎
