### ISSUE TITLE
Table: array to text formatting is hard to read

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#42024]
**What happened**:
In any of the "text" cell display modes of Table (e.g. "color text"), array items will be concatenated with the single `,` character, which is hard to read.

For example, a "group by" query transform with `Calculate` / `all values` will produce an array.  For `Auto` cell display mode it's shown as JSON:

```
["ApproachCautiously","JumpAndHoller","SitAndSpin"]
```

If the cell display mode is changed to `Color text`, it appears as follows:
```
ApproachCautiously,JumpAndHoller,SitAndSpin
```

**What you expected to happen**:
Since the context of "Cell display mode" is specifically displaying values to the user, considering concatenating with `, ` (comma and space) for readability.

```
ApproachCautiously, JumpAndHoller, SitAndSpin
```

**How to reproduce it (as minimally and precisely as possible)**:
  1. generate an array value via `Group by` transform with `All values`, etc.
  2. use table visualization and set cell display mode to `Color text`

**Environment**:
- Grafana version: v8.1.6

**Comment by zuchka** [comment]
Thanks for creating this issue, @belm0 

I can confirm this behavior, but not how to categorize it exactly (bug, nice-to-have enhancement, works-as-intended, or will-not-implement). More on that soon 👍 

https://user-images.githubusercontent.com/37156449/142953285-400305f1-f1ee-4f7c-ba7b-7e6b4f723b4a.mp4

**Comment by zuchka** [comment]
fwiw, if you really wanted to drill down into that field, I believe you could destructure each object in the array into its own row using [the JSON API plugin](https://grafana.com/grafana/plugins/marcusolsson-json-datasource/) and a query syntax like `$.foo[*]`

**Comment by belm0** [comment]
>  if you really wanted to drill down into a single array, I believe you could destructure each object in the array into its own row

For my case we really do want to display a list, just hoping to make it more readable.  (Currently I'm using a hack which involves prepending a space to the group by input.)

There is another issue open about wrapping text in cells-- that would be nice to have too.

**Comment by zuchka** [comment]
you could also try using a regex-based value mapping, set specifically for that field. Then you could use a capture group for each `,` and add a space?

**Comment by belm0** [comment]
I have a workaround.  I filed this bug because I think grafana should format lists legibly out of the box, without workarounds.  This is about cell display format, "display" implying for human readers.

The change may be as simple as changing the formatting concatenator from `,` to `, `.
