### ISSUE TITLE
Datasource config: Insufficient HTTP URL input santization test 

### ISSUE THREAD

**Issue by hawtkey** [grafana/grafana#42022]
**What happened**:

- In the HTTP URL input for a Prometheus data source, I used a string like: "192.168.0.2:9090"
- ✔ Data source is working
- An alert created with a metric from the data source expects the HTTP URL to contain `http://` in the request and fails with error: `first path segment in URL cannot contain colon`

**What you expected to happen**:

 - Automatically sanitize the input
or
 - Error, EX: `"Missing Prefix: Expected http://<IP><Port>"`

**How to reproduce it (as minimally and precisely as possible)**:

 - Make a Prometheus data source with just `<IP><Port>` 
 - Make and test an alert using a metric from the data source

**Anything else we need to know?**:

 - Based on [this issue](https://github.com/grafana/grafana/issues/24882)

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: Prometheus 2.3
- OS Grafana is installed on: Debian 11
- User OS & Browser: Firefox
- Grafana plugins: None
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @hawtkey 

I can confirm that removing `http://` from a Prometheus DS config can result in a misleading 'success' message. Tested on `main`. `localhost:9090` will return `success` but running any query then fails with

```
EROR[11-22|13:19:08] Range query failed                       
logger=tsdb.prometheus query=up{} err="Post \"localhost:9090\": unsupported protocol scheme \"localhost\""
```

adding `127.0.0.1:3000` instead of `http://127.0.0.1:3000` also produces a false success:

```
EROR[11-22|13:11:09] Metric request error                     
logger=context userId=1 orgId=1 uname=admin error="failed to query data: parse \"127.0.0.1:9090\": first path segment in URL cannot contain colon" remote_addr=[::1]
```

**Comment by ivanahuckova** [comment]
Ok, so I was partly right (or partly wrong? 🤷‍♀️), and I have created PR #42189 that is connected to this, but doesn't really solve the real issue. This seems like a generic Grafana  issue. When user is adding url, we can detect **invalid url** and we show red outline. But then we don't do anything about it (user can still save the data source). This can be very problematic for some data sources that run queries trough frontend (proxied queries - e.g. Influx, Elastic, Loki,...). Requests with url that is missing protocol (http/https/...) are successful when run trough frontend (Grafana proxy). So health check and querying is successful. But alerting is done trough backend queries, and they will be failing for incomplete url. 

To test this out, you can choose internal data source (e.g. Elastic/Loki/Graphite/...), add incomplete url, run successful health check, run successful queries in dashboard, add expression query which will fail. This means that also all alerting queries will fail.

https://user-images.githubusercontent.com/30407135/143221615-82eb01b1-f6fe-42bb-8ba4-5e30a4d06414.mov

**Comment by masterwishx** [comment]
is the problem solvet ? i still have it and cant use Grafana  -  Grafana v8.3.3 (30bb7a93ca) Docker for Unraid 

![image](https://user-images.githubusercontent.com/28630321/146070676-af2f431b-1cdd-40e1-87bd-7b59f05d1fbc.png)


![image](https://user-images.githubusercontent.com/28630321/146070869-39dfa414-8f87-4e6f-aa5e-455f61027151.png)

**Comment by masterwishx** [comment]
Fixed by adding http:// to ds prometheus
![image](https://user-images.githubusercontent.com/28630321/146075078-5b9fa274-88a5-44fa-b902-f4dfb41b2134.png)
