### ISSUE TITLE
grafana-google-sdk: Extract auth config components from BigQuery datasource plugin

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#42030]
In BigQuery plugin there is an updated version of authentication details config component for Google datasources: https://github.com/grafana/google-bigquery-datasource/blob/auth-sdk/src/ConfigEditor.tsx#L61

Those components need to be moved out to a shared package as of https://github.com/grafana/grafana/issues/41764

FYI @sunker

**Comment by zoltanbedi** [comment]
This is done.
