### ISSUE TITLE
InfluxDB: Aliasing multiple columns

### ISSUE THREAD

**Issue by ZhukovAlexey** [grafana/grafana#4204]
Hello. I have Grafana 2.6 and InfluxDB 0.9.6.

Also I have two metrics, currently it uses two separate queries.

`a) SELECT "free_ts_size_gb" AS , "total_ts_size_gb"  FROM "ALBO_ORCL_DB_TBS_UTL" WHERE "tablespace" = 'FILE_CONTENT_HASH1_2016' AND $timeFilter`

`b) SELECT "total_ts_size_gb" FROM "ALBO_ORCL_DB_TBS_UTL" WHERE "tablespace" = 'FILE_CONTENT_HASH1_2016' AND $timeFilter`

![grafana_1](https://cloud.githubusercontent.com/assets/1679467/13421867/1b8852be-dfa2-11e5-9f5c-39bbd072bc50.png)

For performance reason (and Grafana supports it) we can draw two metrics with a single query.

`SELECT "free_ts_size_gb" AS "1_2016, free", "total_ts_size_gb"  AS "1_2016, size" FROM "ALBO_ORCL_DB_TBS_UTL" WHERE "tablespace" = 'FILE_CONTENT_HASH1_2016' AND $timeFilter`

But legend adds measurement name to alias instead of `1_2016, free` and `1_2016, size` column name I have `ALBO_ORCL_DB_TBS_UTL.1_2016, free` and `ALBO_ORCL_DB_TBS_UTL.1_2016, size`. It makes graph's legend less readable and more bulky.

![grafana_2](https://cloud.githubusercontent.com/assets/1679467/13421868/1bb8ebea-dfa2-11e5-9603-77de69987cc8.png)

First of all I thought about that InfluxDB returns column name in that style, but here is the JSON which returns by query and there're pretty names.

`http://vuis:8086/query?q=SELECT+free_ts_size_gb+AS+%221_2016,%20free_gb%22+%2C+total_ts_size_gb+AS+%221_2016,%20size_gb%22+FROM+ALBO_ORCL_DB_TBS_UTL+WHERE+tablespace+%3D+%27FILE_CONTENT_HASH1_2016%27+LIMIT+1&db=ORACLE_DB_TABLESPACES_UTIL`

`
{
   "results":[
      {
         "series":[
            {
               "name":"ALBO_ORCL_DB_TBS_UTL",
               "columns":[
                  "time",
                  "1_2016, free_gb",
                  "1_2016, size_gb"
               ],
               "values":[
                  [
                     "2016-02-05T10:59:25.158245715Z",
                     19.61,
                     32
                  ]
               ]
            }
         ]
      }
   ]
}
`

Is there any way not to auto-add measurement name to alias?

**Comment by torkelo** [comment]
You can use the Grafana Alias feature, 

![image](https://cloud.githubusercontent.com/assets/10999/13423614/33fe8b0c-df9c-11e5-958c-255b06ac66b1.png)

Here is a dashboard example:
http://play.grafana.org/dashboard/db/influxdb-issue-4204

**Comment by ZhukovAlexey** [comment]
**torkelo**, thank you. I saw that feature but didn't guess to combine AS clause with $col alias.

The result is on the picture below.

Maybe someone will be interesting.

![grafana_3](https://cloud.githubusercontent.com/assets/1679467/13424796/fab0a41c-dfb3-11e5-9e4c-915c9c7c4d0a.png)
