### ISSUE TITLE
Tempo: Unable to display very large traces

### ISSUE THREAD

**Issue by mapno** [grafana/grafana#42041]
We're experiencing issues when displaying very large traces in Grafana (>100 spans). Display of traces gets cut midway through the trace, and some spans are not rendered.

This usually happens in split view. When displaying the same trace in full view, it gets rendered correctly.

cc/ @connorlindsey 

![image](https://user-images.githubusercontent.com/39532714/142843068-02af51b6-c1fe-4c9f-ae1e-78a33c2ebd47.png)
</div>

**Comment by connorlindsey** [comment]
This has been resolved by this PR: https://github.com/grafana/grafana/pull/42480

Let me know if you're still experiencing it.
