### ISSUE TITLE
Bug: Last 10 viewed dashboards from Org1 shows up in Org2.

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4206]
Steps to reproduce:

1. Have a list of "Last 10 viewed dashboards" in Org1.
2. Switch to "Org2" and then you will see the same list of "Last 10 viewed dashboards", which was in Org1. 

Bug: List "Last 10 viewed dashboards" from Org1 should not exist in Org2.

**Comment by torkelo** [comment]
@utkarshcmu thanks for reporting this!

**Comment by bergquist** [comment]
@utkarshcmu Thanks for reporting!

I was hoping that this could be solved only using frontend by you have proven me wrong :)

I will filter the last visited dashboards by the backend. That way I will be able to add stars aswell

**Comment by utkarshcmu** [comment]
Yeah lets fix this. :)

Also one more thing I have noticed, when I clear my browser's cache, "last 10 view dashboards" dashlist becomes empty. I am not sure whether thats and expected behavior for this feature or not. But IMO, there should be a tooltip/info saying "WARNING: This list will be cleared when clearing browser cache", otherwise user will think that this list will be persisted.

**Comment by bergquist** [comment]
@utkarshcmu thats expected behaviors. This information was only suppose to be saved in local storage. 

How about putting that warning in panel -> options if "recently viewed" is selected?

**Comment by utkarshcmu** [comment]
@bergquist that works too. :+1
