### ISSUE TITLE
"State Timeline" share crosshair incorrect working with `Graph (old)` charts

### ISSUE THREAD

**Issue by mrkeuz** [grafana/grafana#42102]
**What happened**:

From `State Timeline` charts crosshair work well but not vice-versa. Cursor appears sometime but hang in random places (see screencast)

Issue appear with `Graph (old)` + `State Timeline` charts. With `Time series` + `State Timeline` seems crosshair works well between charts in both directions.

**What you expected to happen**:

- Crosshair shared between charts and correct working
- Crosshair worked from `Graph (old)` and from `State Timeline`

**How to reproduce it (as minimally and precisely as possible)**:

1. Add `Graph (old)` charts with data
2. Add `State Timeline` with data
3. Enable Dashboard Settings ⇾ Shared crosshair
4. Hover `Graph (old)` charts

**Anything else we need to know?**:

Related to #41038

**Environment**:
- Grafana version: v8.3.0-beta1 (63cb359220) 
- Data source type & version: Prometheus
- OS Grafana is installed on: (docker version: grafana/grafana:8.3.0-beta1)
- User OS & Browser: Ubuntu 20.04.3 & Brave version 1.31.91 (Chromium: 95.0.4638.69)
- Grafana plugins: 
- Others

![StateTimeline_missing_cursor_sync](https://user-images.githubusercontent.com/6247921/142956112-aebd9e2d-f97e-4ff0-8c84-f5743a0b37ff.gif)
:

**Comment by DmitrySidorow** [comment]
also, the hover tooltip is not shown when there is more than one series

**Comment by zoltanbedi** [comment]
Hi @mrkeuz,
We are not going to add support for this as the old graph is going to be deprecated in 9.0.
