### ISSUE TITLE
8.1.7 Grap (Old)/Timeseries Repeat options

### ISSUE THREAD

**Issue by Tepew** [grafana/grafana#42107]
**What happened**:
On mobile browser regular didn`t show graph when using Graph (old) with repeat option. I emulate this in chrome with iPhone 5/SE zabbix:
![image](https://user-images.githubusercontent.com/42611903/142980322-cfbb2755-99e9-48f0-8a3b-a9372e90d890.png)
![image](https://user-images.githubusercontent.com/42611903/142981477-46b0ba46-4f16-48a7-a791-b449f6259ee9.png)
TestData db:
![image](https://user-images.githubusercontent.com/42611903/142982936-a416fc9e-ea5a-4eac-96c6-60afad8561c6.png)

How it must look
![image](https://user-images.githubusercontent.com/42611903/142981552-844559c2-1522-4b6f-8614-8c08d3e3c40a.png)
Difference in emulate and mobile - in emulate after some time graph is showed sometime. In mobile if graph didn`t show after time they didn`t show.
If you turn the phone horizontally, the charts stick together. In emulate I cant`t this repeat.

With timeseries it repeat
![image](https://user-images.githubusercontent.com/42611903/142983718-03cc54a3-8dba-4071-859a-7066f6f715d4.png)

**How to reproduce it (as minimally and precisely as possible)**:
Dashboard with TestData db:
[Test with test db-1637651176247.zip](https://github.com/grafana/grafana/files/7586255/Test.with.test.db-1637651176247.zip)

Environment:
- Grafana version: 8.1.7
- Data source type & version: Zabbix/TestData db
- OS Grafana is installed on: OEL 7
- User OS & Browser: Mobile Chrome/Safari/Mozilla
- Grafana plugins: Zabbix plugin 4.1.5

**Comment by Tepew** [comment]
For experiment - delete raw. It didn`t result.

**Comment by torkelo** [comment]
This is fixed in 8.2

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/41009

**Comment by Tepew** [comment]
8.2.5 in test with dashboard from first post
![image](https://user-images.githubusercontent.com/42611903/143021487-9cc723bd-b7bf-4001-81b9-b4c7b8c97272.png)
![image](https://user-images.githubusercontent.com/42611903/143021570-81a2c126-ed3e-4bed-920e-c5167cbb15d4.png)

**Comment by Tepew** [comment]
![image](https://user-images.githubusercontent.com/42611903/143021660-e3c6476b-18e0-4660-bfcb-52d7f84d2f65.png)

**Comment by Tepew** [comment]
After many hours tests - in 8.2.5 graph load but not immediately
