### ISSUE TITLE
Bug: Available snapshots should ignore expired snapshots

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4210]
On the "Snapshots" UI page, we see all the available snapshots. But this list of snapshots shows even the expired ones.

Bug: Expired snapshots should not be shown on Grafana snapshots page. 

Fix: Modify sql query which fetches snapshots OR Filter snapshots in frontend.

**Comment by torkelo** [comment]
there should be a background go routine that clean's up expired snapshots

**Comment by bergquist** [comment]
ref #2172

**Comment by torkelo** [comment]
@bergquist not sure it i related to temp data folder

**Comment by utkarshcmu** [comment]
@torkelo this is not related to the temp folder.

So the list of snapshots which shows up on the snapshot page in grafana, also shows expired snapshots.

I suggest two things: 

1. The query should be modified which fetches the list of snapshots. The query should only fetch non-expired snapshots so that even when the expired snapshots from db are not deleted, the users won't be able to see them on the UI.

2. Grafana-cli should have capability of deleting expired snapshots. Then admins can put a daily cron job to run the clean up to clean up the db.

**Comment by torkelo** [comment]
think the cleanup should not require a admin's having to setup cron jobs, it should be part of the Grafana server

**Comment by utkarshcmu** [comment]
Agreed :+1:

**Comment by torkelo** [comment]
will close this as the root cause is this issue https://github.com/grafana/grafana/issues/4087
