### ISSUE TITLE
Grafana 8.2.3 - Azure Monitor Logs -  Resource picker not showing resources

### ISSUE THREAD

**Issue by VRay27** [grafana/grafana#42104]
**What happened**:
With **Grafana 8.2.3** ->In the panel, when I select the data source as Azure Monitor -> Logs -> Subscription -> Resource Group -> The resource group is not expanding here, even it does give a wait icon but it comes up empty. I have checked manually in Azure also the resource group isn't empty.
With **Grafana 8.0.5,** I am able to select the resource with the same Subscription, Resource Group and Client ID/Secret which I am using with Grafana 8.2.3
Please note both Grafana are in the same network.

**What you expected to happen**:
I was expecting to select the resource from the Azure resource group post my Grafana upgrade to 8.2.3 which I wasn't able to. 

**How to reproduce it (as minimally and precisely as possible)**:
I believe upgrade Grafana from 8.0.5 to 8.2.3 and select the data source Azure monitor-> logs -> subscription-> resource group -> .....
This would take you where I am getting the error

**Anything else we need to know?**:
I am able to select the azure resource in Grafana 8.0.5 but when I try to do the same post Grafana upgrade to 8.2.3, the Azure resource group doesn't expand no matter how many times I click on it. The way I follow, expand Subscription , go to the required Resource group, expand resource group -> here it will show it is expanding but nothing comes up which led me to believe that my resource group is empty. But the same thing I have tried in 8.0.5 with the same subscription and same resource group it is letting me select the resource group.

Please note : I have manually checked the Resource group in Azure and it has many resources.

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: Azure Monitor (Logs)
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Google Chrome, Edge

**Error Screenshot**
Since Grafana 8.2.3 didn't let me select the resource under the Resource group, I have only selected till Resource group

![image](https://user-images.githubusercontent.com/69594987/142972697-2c110ba8-e174-4538-bd17-e2976cfcf4cf.png)

**Error Log**

lvl=eror msg="Request error" logger=context userId=1 orgId=2 uname=admin error="interface conversion: interface {} is string, not bool" stack="/usr/local/go/src/runtime/iface.go:261 (0x40af34)\n/drone/src/pkg/tsdb/azuremonitor/azure-log-analytics-datasource.go:145 (0x2124ee4)\n/drone/src/pkg/tsdb/azuremonitor/azure-log-analytics-datasource.go:58 (0x212260a)\n/drone/src/pkg/tsdb/azuremonitor/azuremonitor.go:199 (0x2131954)\n/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.114.0/backend/data.go:33 (0xaa7b4e)\n/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.114.0/backend/datasource/query_type_mux.go:85 (0x16b2c01)\n/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:81 (0x16b3550)\n/drone/src/pkg/plugins/backendplugin/manager/manager.go:301 (0x1e46116)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:40 (0x1e431f7)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:69 (0x1e45f34)\n/drone/src/pkg/plugins/backendplugin/manager/manager.go:300 (0x1e45e46)\n/drone/src/pkg/tsdb/data_plugin_adapter.go:63 (0x1e678e1)\n/drone/src/pkg/plugins/tsdb.go:242 (0x1e68365)\n/drone/src/pkg/tsdb/service.go:68 (0x1e682b2)\n/drone/src/pkg/api/metrics.go:85 (0x2096359)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/api/routing/routing.go:18 (0x1614899)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/context.go:62 (0x16107b3)\n/drone/src/pkg/middleware/request_metrics.go:55 (0x16107a2)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/context.go:62 (0xdb48fa)\n/drone/src/pkg/macaron/macaron.go:155 (0xdb48ec)\n/usr/local/go/src/net/http/server.go:2046 (0x6d06ce)\n/drone/src/pkg/middleware/csp.go:22 (0x160cfb2)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/context.go:62 (0xdb48fa)\n/drone/src/pkg/macaron/macaron.go:155 (0xdb48ec)\n/usr/local/go/src/net/http/server.go:2046 (0x6d06ce)\n/drone/src/pkg/macaron/render.go:44 (0xdaf6e6)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/context.go:62 (0x160fb0a)\n/drone/src/pkg/middleware/recovery.go:168 (0x160fb01)\n/drone/src/pkg/macaron/context.go:32 (0xdac7fb)\n/drone/src/pkg/macaron/inject.go:139 (0xdad794)\n/drone/src/pkg/macaron/inject.go:117 (0xdad6bc)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/context.go:62 (0x160d9c4)\n/drone/src/pkg/middleware/logger.go:33 (0x160d9ad)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/context.go:62 (0x1612379)\n/drone/src/pkg/middleware/request_tracing.go:57 (0x1612368)\n/usr/local/go/src/reflect/value.go:543 (0x4dd1b3)\n/usr/local/go/src/reflect/value.go:339 (0x4dc764)\n/drone/src/pkg/macaron/inject.go:159 (0xdada26)\n/drone/src/pkg/macaron/inject.go:119 (0xdad674)\n/drone/src/pkg/macaron/context.go:67 (0xdac90b)\n/drone/src/pkg/macaron/router.go:156 (0xdb0f1d)\n/drone/src/pkg/macaron/router.go:213 (0xdb1bd5)\n/drone/src/pkg/macaron/macaron.go:189 (0xdaf030)\n/usr/local/go/src/net/http/server.go:2878 (0x6d3c3a)\n/usr/local/go/src/net/http/server.go:1929 (0x6cf7a7)\n/usr/local/go/src/runtime/asm_amd64.s:1581 (0x469ae0)\n"

**Comment by VRay27** [comment]
@joshhunt FYI/A

**Comment by vickyyyyyyy** [comment]
@VRay27 thanks for reporting! I can't seem to replicate this

- Is this an error you see using the same dashboard created when upgrading from 8.0.5 to 8.2.3? 
- The screenshot you've provided looks like it's from the `Explore` view - is that correct?
- Do you get the same error if you create a new dashboard on 8.2.3?
- Do you get any errors in the browser console?

> The resource group is not expanding here, even it does give a wait icon but it comes up empty

> the Azure resource group doesn't expand no matter how many times I click on it

are you able to provide a screenshot/video of this?

**Comment by VRay27** [comment]
1. Yes the same dashboard.
2. Yes the screenshot is from the explore option. 
3. Yes, I get the same issue if I create a dashboard and select the Azure Monitor->Logs-> Subscription -> Resource Group -> No resource been showed
4. I get 500 internal error which says check Grafana Internal Server error - Check for Grafana logs. The same Log I have pasted above in the initial box.
![image](https://user-images.githubusercontent.com/69594987/143172493-327e3fe4-24b2-40ea-a471-83d11f05ea42.png)
5. I will have to take a video , need to figure out a way to hide data and show the issue. I will post the same.

Please note: I have multiple subscriptions with the same client id/secret and the same named resource group is present across different subscription. Is that helpful?

**Comment by vickyyyyyyy** [comment]
> I have multiple subscriptions with the same client id/secret and the same named resource group is present across different subscription

@iwysiu I know the same resource across multiple subscriptions issue you've been working on is pretty much the opposite problem of this, but do you have any idea what could be causing this?

**Comment by iwysiu** [comment]
@vickyyyyyyy Based on the error, it looks like `dsInfo.JSONData["azureLogAnalyticsSameAs"]` is a string when it's expected to be a bool, though I haven't figured out why it's getting a string.

**Comment by iwysiu** [comment]
Actually, this could be related to the multiple subscription issue: the way the bug works, the first subscription gets multiple copies of the resource group that expand to the different sets of resources, and the duplicated resource groups under the other subscriptions are empty. So this might be fixed by #42170

**Comment by VRay27** [comment]
I think @iwysiu said is the crux of the issue. 
I have multiple subscription under the same clientID/secret. In that, I have two subscriptions, non prod and prod which has a same name Resource group. Let's say "XYZ".  
When I check the non prod, and select XYZ - it is getting expanded.
But when I check the prod and select XYZ - it shows up empty

One more thing I have noticed. When I double click on the XYZ resource group of the Prod subscription which is coming up empty, it is taking me directly to the XYZ resource group of Non Prod subscription which is weird @vickyyyyyyy

**Comment by VRay27** [comment]
@vickyyyyyyy @iwysiu  This is for both of you, If my reported issue is the same as #42170 , could you please confirm when this would be fixed so that we can upgrade our Grafana to that version.

**Comment by iwysiu** [comment]
Hi @VRay27 ! That fix is going to go out in version 8.3.0, which is scheduled for December 1st.

**Comment by VRay27** [comment]
> I think @iwysiu said is the crux of the issue. I have multiple subscription under the same clientID/secret. In that, I have two subscriptions, non prod and prod which has a same name Resource group. Let's say "XYZ". When I check the non prod, and select XYZ - it is getting expanded. But when I check the prod and select XYZ - it shows up empty
> 
> One more thing I have noticed. When I double click on the XYZ resource group of the Prod subscription which is coming up empty, it is taking me directly to the XYZ resource group of Non Prod subscription which is weird @vickyyyyyyy

So would you be able to confirm if my issue is the same one as that of the bug you mentioned ? @iwysiu

**Comment by iwysiu** [comment]
@VRay27 yes, I believe so! I checked my bug repro and it also has the behavior you mentioned where it gets taken to the other subscription. As a final confirmation, does the same name resource group get listed twice under each subscription?

**Comment by VRay27** [comment]
@iwysiu  I believe I saw that behaviour(duplication of RG name under each subscription) but at that time I thought I could be wrong since we have a lot many resource group in each subscription. But I will re check it again tomorrow and confirm the same.  Thanks for getting back on this. Really appreciate your help.

**Comment by VRay27** [comment]
@iwysiu  I can confirm I see the RG twice in my non prod subscription where it is getting expanded but only one RG in the prod subscription

**Comment by iwysiu** [comment]
Thanks for confirming! I'm closing this as being fixed by #42170
