### ISSUE TITLE
Organization menu empty in case of a single Organization.

### ISSUE THREAD

**Issue by jmvitali** [grafana/grafana#4211]
Hi,
We are currently implemented the wonderful application Grafana as dashboarding tool of Graphite.
Only the main organization has configured on our context. 

We have recently identified on that case Grafana displays an empty Organization popup window menu.
So user thinks to have an option by clicking on the Organization name, but no action/link are available within the displayed empty popup window menu.

Do you have a configuration solution or a workaround to avoid displaying this empty Organization popup window menu?
Is this display issue fixed on an on-going Grafana release? 
If this is no the case, can you help to fix that one into a next Grafana release? 

Thanks in advance for your help,
Kind regards,
Jean-Marc

![empty_orga_popup_window_menu](https://cloud.githubusercontent.com/assets/15108758/13426014/25ed12d6-dfab-11e5-925e-c2c46425f4dc.jpg)

**Comment by Guillaumichaud** [comment]
+1

**Comment by torkelo** [comment]
this is solved in master (upcoming 3.0)

if you are a user with only Viewer Organization Role then you see a sidemenu like this (I am hover over the profile main sidemenu to show the on hover subnav)

![image](https://cloud.githubusercontent.com/assets/10999/13427163/75c9ad26-dfb2-11e5-8268-68abe272238a.png)

Of course if you have disabled the ability for users to create new orgs that option will also not show.

just for reference this how it looks if you are logged in with an Org. Admin:
![image](https://cloud.githubusercontent.com/assets/10999/13427204/c58370a4-dfb2-11e5-898f-acd458902424.png)

**Comment by jmvitali** [comment]
Thanks torkelo for the quick detailed answer.

Do you already have an estimated release date for the  upcoming release 3.0?

**Comment by torkelo** [comment]
Yes, beta release within 1 week, stable within 3-4

**Comment by Guillaumichaud** [comment]
Great news!

**Comment by jmvitali** [comment]
Thanks for the information.
