### ISSUE TITLE
Plugins: Navigating to a plugin custom page doesn't respect the role attribute

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#42121]
A plugin developer can make use of the `[includes.role]` property in `plugin.json` to limit access to custom pages however the frontend doesn't seem to respect which can result in broken pages:

![image](https://user-images.githubusercontent.com/73201/143008491-2ae3797a-ce56-45ac-826b-479be0335331.png)

This PR: https://github.com/grafana/grafana/pull/53520 is preventing access when a route is loaded directly, now we need to do the same on the frontend side. The reason is react router being used directly in the app plugins and so far are not defining any protected routes based on plugin.json config.

**Comment by tolzhabayev** [comment]
Relevant https://github.com/grafana/grafana/issues/33897
