### ISSUE TITLE
Value to text mapping doesn't work with more than one field

### ISSUE THREAD

**Issue by xpinkyx** [grafana/grafana#4213]
When I add more than one value to text mapping to a singlestat and try to change one value, all value-fields change their input. Same with the textfield. I'm using firefox and the latest grafana build (25.2.2016)

**Comment by torkelo** [comment]
seems to work in latest builds

**Comment by torkelo** [comment]
oh, and by the way thanks for reporting this, if the problem still exists after updating please reopen issue!
