### ISSUE TITLE
Tempo: Show some error message when we could not transform response

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#42131]
In this issue https://github.com/grafana/grafana/issues/41646 the Tempo datasource just silently failed to transform the trace data and didn't show any error or message to the user, just didn't display any data.

We should propagate the error to the user.

**Comment by kvrhdn** [comment]
fyi, someone in the Tempo community Slack stumbled upon this bug: https://grafana.slack.com/archives/C01D981PEE5/p1641570998020700
