### ISSUE TITLE
Create link with specific values in table as parameters

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4214]
If I have a Table as my view, is it possible to create a dynamic html link to another dashboard or url based on the value of a specific column.
So, if i have an order id column and a list of rows, I want to see if I can click on a particular row and then go to a dashboard about that specific order id

**Comment by mtanda** [comment]
similar https://github.com/grafana/grafana/issues/3754

**Comment by bergquist** [comment]
I really like this idea. Could potentially provide a lot of flexibility. 

But I think #3754 is similar enough to close this.

**Comment by teo96** [comment]
+1

**Comment by fransdw** [comment]
+1

**Comment by sofixa** [comment]
+1

**Comment by beeflix** [comment]
+100

**Comment by digrich** [comment]
+1

**Comment by comcomservices** [comment]
+1

**Comment by wanyinglong** [comment]
+1

**Comment by indranilr** [comment]
+1

**Comment by gtt116** [comment]
+1

**Comment by brutus333** [comment]
+1

**Comment by lis0x90** [comment]
+1

**Comment by mady4ever** [comment]
+1

**Comment by zepspaiva** [comment]
+1

**Comment by MadeInChina** [comment]
+1

**Comment by inselbuch** [comment]
OH GOD YES

**Comment by Kenith** [comment]
+1

**Comment by asriverwang** [comment]
+1. Really need this feature.

**Comment by virgile-thermo** [comment]
+1

**Comment by vbicer** [comment]
+2

**Comment by vkroz** [comment]
+1

**Comment by ggolin** [comment]
+1

**Comment by Aceman87** [comment]
+1

**Comment by graemeparker** [comment]
+1

**Comment by Rellek72** [comment]
+1

**Comment by vvvprabhakar** [comment]
+1
