### ISSUE TITLE
Invalid time selection in "Time Range" causes Dashboard time picker to not open

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#4216]
A bug I found while messing around in the "Time Range":

If you enter a invalid day selection (I entered "now/d-7" in the "From:" and "To:" fields) you will receive an error on every graph in the dashboard ("Cannot read property 'valueOf' of undefined") - which is expected. The unexpected result is you cannot open the "Dashboard Time Picker" anymore...

**Comment by torkelo** [comment]
this is fixed in master :)
