### ISSUE TITLE
ElasticSearch template splits on "-"

### ISSUE THREAD

**Issue by moserke** [grafana/grafana#4218]
When writing a query for templates for elasticsearch, response appear to be split on "-" and making the data wrong.

For example:
{"find": "terms", "field": "MetricsTags.pod_namespace"} should return "default, kube-system", however, the returned values end up being "default, kube, system".  Is there a way to change this behavior or am I doing something wrong?

**Comment by torkelo** [comment]
it depends on how your elasticsearch index is defined, by default Elasticsearch will analyze words and split them so you can search for each word. Search elasticsearch docs for index mapping definitions and how to stop elasticsearch from splitting words when doing term queries (hint disable analyze in mapping definition for the property)
