### ISSUE TITLE
ServiceAccounts: Upgrade API keys when service accounts enabled

### ISSUE THREAD

**Issue by donomii** [grafana/grafana#42203]
When service accounts are enabled, API keys continue to function in the old way, without an attached service account.

Instead, check every API on startup and create a service account for each API key that doesn't already have one.

**Comment by eleijonmarck** [comment]
@donomii could you note down what we are waiting for for this to be put in the roadmap?

Is it the decision of what kind of migration we should be doing?

**Comment by donomii** [comment]
Yes, the migration is currently holding this up.
