### ISSUE TITLE
Trace Viewer virtualized scrolling is broken in right explore pane

### ISSUE THREAD

**Issue by autoric** [grafana/grafana#42245]
**What happened**:

When loading large traces (ie many spans) into the trace viewer on the right-side explore pane, virtualized scrolling is broken. If I scroll down in the right-side explore pane, spans farther down in the trace are not visible. It seems that the virtualized scroll state is being driven by the scroll position of the left-side explore pane.

https://user-images.githubusercontent.com/918178/143279863-d6e18abe-afe3-4cdd-8e2f-3d2ee310f71c.mov

**What you expected to happen**:

I can view the entire trace as I scroll.

**How to reproduce it (as minimally and precisely as possible)**:

Open a long trace in the right-side explore pane. Scroll down to try and view the entire trace contents.

**Comment by autoric** [comment]
I've identified the issue here: https://github.com/grafana/grafana/blob/main/public/app/features/explore/TraceView/TraceView.tsx#L119

This is assuming only one scroll container on the page. I've got a mostly working PR that switches over to using refs & passing a reference from the `<CustomScrollbar />` down to the `< TraceView />`. I will clean it up and open a PR after the thanksgiving holiday.

**Comment by connorlindsey** [comment]
Was able to reproduce this on latest. Thanks for reporting and opening your PR, taking a look now
