### ISSUE TITLE
npx @grafana/toolkit plugin:create my-plugin 

### ISSUE THREAD

**Issue by CloudWise-Lukemiao** [grafana/grafana#42268]
When I execute the NPX @ grafana / Toolkit plugin: create my plugin command, it is the same as in the picture. The implementation has been unsuccessful. I've been waiting for hours. I tried it several times and it's still the same

![image](https://user-images.githubusercontent.com/76942485/143388120-1dd92d88-716c-4700-864d-f34454e9ac1d.png)

**Comment by zuchka** [comment]
@CloudWise-Lukemiao see this topic in the forum:

https://community.grafana.com/t/plugin-create-stuck/47476

downgrading npm should resolve this.

In the future please follow our template as closely as possible, including steps for reproduction and more details re versions, configs, etc 👍
