### ISSUE TITLE
Building packages: "systemjs:build" task TypeError

### ISSUE THREAD

**Issue by robochat** [grafana/grafana#4226]
Following the instructions at http://docs.grafana.org/v2.6/project/building_from_source/#creating-optimized-release-packages. I get a long way through the process before stopping at a Build error
```
Running "systemjs:build" task
Starting systemjs-builder
Build error
[TypeError: Error compiling amd module "moment" at vendor/moment.js
	Cannot read property 'parameters' of undefined]
Warning: Task "systemjs:build" failed. Use --force to continue.

Aborted due to warnings.
```
These are the commands that I did:
```
cd $GOPATH/src/github.com/grafana/grafana
go run build.go setup            (only needed once to install godep)
godep restore                    (will pull down all golang lib dependencies in your current GOPATH)
go run build.go build
npm install
sudo npm install -g grunt-cli
grunt test
go run build.go build package
```
I'm not sure what to do now.

**Comment by torkelo** [comment]
strange the CI build is passing, 
https://circleci.com/gh/grafana/grafana/3102

Try updating nodejs and running "npm install"

**Comment by robochat** [comment]
Do I need to be on at least Nodejs ver. 4? I'm only on 0.10.42-4.el6

**Comment by torkelo** [comment]
yes

**Comment by robochat** [comment]
Ok, I've installed node v4.3.1 and npm v3.7.5. I've redone `npm install` But I still get the same error. 
What's the difference between `grunt`  and `grunt release` ? because I can't find the systemjs:part part in the CI build. When I do `grunt` or `grunt test` everything passes.

**Comment by tuyy** [comment]
@robochat Hi, brother

Do you solve this problem?
Help me plz.

Thanks.

**Comment by robochat** [comment]
This issue has been fixed now and the `build package` command works fine again.
Thanks!
