### ISSUE TITLE
grafana/experimental: Initial setup

### ISSUE THREAD

**Issue by dprokop** [grafana/grafana#42277]
grafana/experimental repository: https://github.com/grafana/grafana-experimental

Working on the grafana/experimental with @zoltanbedi we have discover couple of constraints:
- ⚠️ package's `canary` versions are published to GH Packages repo only, making them not easily usable _without additional auth setup on CI and developers end_
- ⚠️ using different package repositories for the same scope is not possible with yarn without introducing an additional proxy 

Both constraints above are solvable but would require us to introduce unnecessary complexity to our packages setup as well as some setup overhead for developers. We consider this suboptimal.

The constraints are shown on [the diagrams here](https://drive.google.com/file/d/1wkFxEE6I9585tkNTVT1qE4YuVjBYcX_C/view?usp=sharing)

After talking with @zoltanbedi @mckn and @jackw we have decided to do the following:
- [ ] Bring back `canary` releases to npm so that all grafana packages can be consumed from the same packages repository (#42922)
- [ ] checksum the packages published from the `main` branch and bail out if the same version (checksum-wise) has already been published (keep versioning in sync across packages and publish all if one or more packages has changes.) (#42922) 
- [ ] Test out if not externalizing grafana/ui/data in grafana/experimental will allow it to work as expected
- [ ] Not directly related: fix `next` tag being incorrectly assigned to packages released during patch releases

**Comment by marefr** [comment]
Please label this issue thanks :pray:
