### ISSUE TITLE
Legends cause panels to overrun the row height

### ISSUE THREAD

**Issue by swissdave** [grafana/grafana#4229]
If I use a second Y axis, or have a large number of data series, it causes the panel to grow in height over and above the row's specified height, resulting in an uneven layout of charts.

e.g. the chart of the left has expanded the row height a little:

![row](https://cloud.githubusercontent.com/assets/7346928/13460122/c0e3c168-e078-11e5-99c9-2940db52f1e3.png)

Maybe the chart size should be the remaining area once the legend has been rendered, always respecting the row height?  That would leave the user to choose a row height appropriate for the size of their legends..

**Comment by torkelo** [comment]
does the legend fit on one row? It looks like you have to many series to fit on one row, if you want graphs to align in that mode you need to put legend in table, then it will work as you expect (the graph height is reduced to compensate for the legend height )

**Comment by swissdave** [comment]
Yes, it's where the legends don't all fit on one line.  I switched to table mode and it still doesn't respect the row height - although it does reduce the chart size.  I think it's good when the legends belonging to the left Y axis are arranged on the left and the legends for the right Y axis are on the right - easier to see which series are comparable then..

![graf3](https://cloud.githubusercontent.com/assets/7346928/13463253/af9a4aa4-e08b-11e5-8d2c-d97a07ec970d.png)

**Comment by torkelo** [comment]
it does respect row height up to a point, but has a lower limit for how small it will cause the graph to be (so that many series dont reduce the graph to zero height)

**Comment by swissdave** [comment]
If a row height is not a fixed number, and rather lower limit, maybe the other panels in the row could be grown to the same height as the tallest in the row?  To my mind having charts of differing heights in a row looks untidy.

**Comment by torkelo** [comment]
Yes, I agree, you can fix this by setting a row height to tell same as the highest panel
