### ISSUE TITLE
Grafana unique count through elasticsearch

### ISSUE THREAD

**Issue by NavneetMathpal** [grafana/grafana#4231]
Hi,

I am trying to get the unique count on a string field in Grafana through elasticsearch.
but it does not give me the accurate data. any idea on this ?
Will it work fine in a case of integer (unique count of integers ) ?

Thanks

**Comment by torkelo** [comment]
The Unique Count is the same as the Cardinality Metric aggregation, https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html

**Comment by NavneetMathpal** [comment]
@torkelo   Agree... But I am not able to get the right distinct count in Grafana... If i fire the Cardinality aggs in elasticsearch it gives me accurate data..

**Comment by torkelo** [comment]
you can open chrome dev tool and check the network tab, there you will see the elasticsearch query and elasticsearch's response

**Comment by lucasrodcosta** [comment]
Hi everyone.

The unique counts in ElasticSearch are approximate, because exact counts requires large memory usage.
Details in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate.

But ElasticSearch offers the option `precision_threshold` to trade memory for accuracy.
In Kibana, to set a custom `precision_threshold` you can use the advanced section and put a custom JSON Input to the aggregation:

![](http://i.stack.imgur.com/Q2Joo.png)

It would be nice to have this option in Grafana too.

**Comment by nitram4** [comment]
Could this customization be placed somewhere inside JSON panel inside Grafana?

**Comment by torkelo** [comment]
Not currently but would be easy to add.

**Comment by tonyC2016** [comment]
@NavneetMathpal ,hi i got the same problem，have fixed it ,if ,how?,plz!

**Comment by abcfy2** [comment]
Is there any way to do unique count across multiple fields ?

**Comment by drewboswell** [comment]
I have the same problem, in the case where we try to get a unique count in a stat panel for instance: we don't need the group by function. Yet the query returns multiple datapoints as opposed to just one. 

Any idea on how to configure a unique count for elasticsearch datasource? I can't figure it out without any hacks (like a massive group by timeperiod)

**Comment by JohhnyP** [comment]
We're having the same problem.
In Kibana you can simply count unique text fields like this

![Kibana](http://i.imgur.com/bjpRcbK.png)
**Kibana Request**
`{
  "size": 0,
  "query": {
    "bool": {
      "must": [
        {
          "query_string": {
            "query": "*",
            "analyze_wildcard": true
          }
        },
        {
          "range": {
            "timestamp": {
              "gte": 1484300616021,
              "lte": 1484301516021,
              "format": "epoch_millis"
            }
          }
        }
      ],
      "must_not": []
    }
  },
  "_source": {
    "excludes": []
  },
  "aggs": {
    "1": {
      "cardinality": {
        "field": "gameDsc.keyword"
      }
    }
  }
}`

**Kibana Response**
`{
  "took": 4,
  "timed_out": false,
  "_shards": {
    "total": 5,
    "successful": 5,
    "failed": 0
  },
  "hits": {
    "total": 15812,
    "max_score": 0,
    "hits": []
  },
  "aggregations": {
    "1": {
      "value": 12
    }
  },
  "status": 200
}`

I can't find a way to do the same in Grafana (4.1.1 + Elastic5)
The following returns 3 (i have no idea why)
I think the group is not needed in this case and there is no way to remove it.

![Grafana](http://i.imgur.com/0PPgH63.png)

**Comment by beingyash** [comment]
> @torkelo Agree... But I am not able to get the right distinct count in Grafana... If i fire the Cardinality aggs in elasticsearch it gives me accurate data..

@torkelo I'm facing the same challenge. When i query es  directly, i get the accurate unique counts, however not in grafana. I tried using the grafana query from chrome dev tools and the query itself gives an incorrect unique count. 
btw, i'm already using precision_threshold 40000 and @drewboswell  mentioned, to get that unique count, i also had to use a massive interval value of 5 years.
