### ISSUE TITLE
WebSocket connection failed. Error in browser console, not behind proxy and without domaine

### ISSUE THREAD

**Issue by Vital91** [grafana/grafana#42327]
Hi,

Streaming from MQTT Datasource is not updated in real time inside the time series panel and I'm getting constant websocket error in browser console log (WebSocket connection to 'ws://192.168.1.24:3000/api/live/ws' failed:centrifuge.js:544), similarly to case #36929 but in my context, I’m working from home, without proxy and without domain set (localhost).
![image](https://user-images.githubusercontent.com/60693980/143484104-c11f825b-614d-4c9c-8e80-cb72796fe16f.png)

I have stopped Windows Firewall but problem persist.

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: MQTT DataSource
- OS Grafana is installed on: Linux in container
- User OS & Browser: Windows 10/ Chrome 
- Grafana plugins:
- Others:

**Comment by FZambia** [comment]
Hello, @Vital91 

May be a problem with `[live] allowed_origins` configuration. Do you see any Grafana server logs with message `Request Origin is not authorized`?

**Comment by Vital91** [comment]
Hi @FZambia,

thanks a lot, that's the point ! got it working now, thanks :-)

Vital

**Comment by degenhardt** [comment]
Hi Vital91! I have the same problem. Can you share with us your solution?

**Comment by TiagoAntonio019** [comment]
Hey y'all
I'm using Apache as a reverse proxy
Internet > Apache (public IP) > Grafana / Zabbix (private IP)
I had the same issue with my Grafana and Uptime Kuma...lol
On Uptime Kuma documentation I found this recommendation for Apache
```
RewriteCond %{HTTP:Upgrade} =websocket
RewriteRule /(.*) ws://localhost:3001/$1 [P,L]
RewriteCond %{HTTP:Upgrade} !=websocket
RewriteRule /(.*) http://localhost:3001/$1 [P,L]
```

### How to do it:

1. Open your virtual host: sudo vi /etc/apache2/sites-available/domain.com
2. Insert the code above
3. Save the file
4. Run: sudo systemctl restart apache2.service
