### ISSUE TITLE
Service accounts: Instrument service accounts with prometheus metrics 

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#42328]
In scope of this issues want to introduce metrics for the service account endpoint. 

- [ ] usage statistics https://github.com/grafana/grafana/pull/42332

**Comment by IevaVasiljeva** [comment]
@eleijonmarck, @Jguer is this done by https://github.com/grafana/grafana/pull/46619?

**Comment by eleijonmarck** [comment]
@IevaVasiljeva si! well spotted

**Comment by Jguer** [comment]
:sweat_smile: we still need an issue for implementing prometheus metrics which are not the same as usage statistics @eleijonmarck

**Comment by eleijonmarck** [comment]
@Jguer i am not sure that this was the same

**Comment by Jguer** [comment]
we have usage stats, system stats and (prometheus) metrics. Usage stats and system stats are ready for SAs, so we're just missing prometheus metrics. 

We don't need to add high cardinality metrics for prometheus, for example, adding the same ones we have already added for usage stats would already be an improvement
