### ISSUE TITLE
Transformation "Convert field type" not applying specified time format

### ISSUE THREAD

**Issue by sebcaps** [grafana/grafana#42326]
**What happened**:
Use 'Convert field type' transformation on a time column from influxDb, applying format 'YYYY-MM-DD' the format is not applied
![image](https://user-images.githubusercontent.com/24374878/143483940-c076f528-4b0b-451d-8797-88e946e68b19.png)

**What you expected to happen**:
Got the date value with format YYYY-MM-DD on each line

**How to reproduce it (as minimally and precisely as possible)**:
Create a query on a influxdb and apply the transformation.
**Anything else we need to know?**:
Transformation debug output
`Array[1]
0:Object
fields:Array[2]
0:Object
name:"Time"
config:Object
values:
buffer:Array[36]
0:1637694793795
1:1637696263862
2:1637697313919
3:1637697343913
4:1637697373928
5:1637697403930
6:1637697463755
7:1637705594390
8:1637705984392
9:1637706194423
10:1637706284419
11:1637706314233
12:1637734636361
13:1637734666126
14:1637736496254
15:1637736526412
16:1637766497855
17:1637766708082
18:1637781138801
19:1637781828641
20:1637783958815
21:1637783989076
22:1637784018974
23:1637784139006
24:1637784349026
25:1637784439027
26:1637784469023
27:1637784529032
28:1637786029106
29:1637786059116
30:1637786149114
31:1637786239140
32:1637794129353
33:1637842313041
34:1637842433182
35:1637844023009
type:"time"
state:Object
displayName:"Time"
1:Object
refId:"B"
meta:Object
executedQueryString:"SELECT  elapsed("value") /10000000 as duree FROM "tvstat" WHERE ("device" = 'Tele') AND time >= now() - 2d and time <= now() "
transformations:Array[3]
name:undefined
length:36`

**Environment**:
- Grafana version: v8.2.5 (b57a137acd)
- Data source type & version: InfluxDB 1.8.6
- OS Grafana is installed on:  Raspbian; grafana on docker
- User OS & Browser: WIn10 + Chrome

**Comment by sebcaps** [comment]
JSON Panel from grafana playground, where result not as expected,as well
`{
  "annotations": {
    "enable": false,
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 553,
  "iteration": 1637862378681,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "aliasColors": {},
      "annotate": {
        "enable": false
      },
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": "InfluxDB",
      "description": "",
      "editable": true,
      "error": false,
      "fill": 2,
      "fillGradient": 0,
      "grid": {},
      "gridPos": {
        "h": 9,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 1,
      "interval": "$summarize",
      "legend": {
        "alignAsTable": true,
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "rightSide": true,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "links": [],
      "nullPointMode": "connected",
      "options": {
        "alertThreshold": true
      },
      "percentage": false,
      "pluginVersion": "8.2.5",
      "pointradius": 5,
      "points": false,
      "renderer": "flot",
      "resolution": 100,
      "scale": 1,
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": true,
      "steppedLine": false,
      "targets": [
        {
          "alias": "$tag_hostname",
          "dsType": "influxdb",
          "groupBy": [],
          "measurement": "logins.count",
          "orderByTime": "ASC",
          "policy": "default",
          "query": "SELECT mean(\"value\") FROM \"logins.count\" WHERE \"hostname\" =~ /$Hostname$/ AND $timeFilter GROUP BY time($interval), \"hostname\"",
          "refId": "A",
          "resultFormat": "time_series",
          "select": [
            [
              {
                "params": [
                  "value"
                ],
                "type": "field"
              }
            ]
          ],
          "tags": [
            {
              "key": "datacenter",
              "operator": "=~",
              "value": "/^$datacenter$/"
            },
            {
              "condition": "AND",
              "key": "hostname",
              "operator": "=~",
              "value": "/^$host$/"
            }
          ],
          "target": ""
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "Selected Servers",
      "tooltip": {
        "msResolution": false,
        "query_as_alias": true,
        "shared": false,
        "sort": 0,
        "value_type": "cumulative"
      },
      "transformations": [
        {
          "id": "convertFieldType",
          "options": {
            "conversions": [
              {
                "dateFormat": "DD-MM-YYYY",
                "destinationType": "time",
                "targetField": "Time"
              }
            ],
            "fields": {}
          }
        }
      ],
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      },
      "zerofill": true
    }
  ],
  "refresh": "",
  "schemaVersion": 32,
  "style": "dark",
  "tags": [
    "gdev",
    "presentation",
    "influxdb",
    "misc"
  ],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "America",
          "value": "America"
        },
        "datasource": "InfluxDB",
        "definition": "",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "datacenter",
        "options": [],
        "query": "SHOW TAG VALUES  WITH KEY = \"datacenter\" ",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": null,
        "tagsQuery": null,
        "type": "query",
        "useTags": false
      },
      {
        "allFormat": "regex values",
        "allValue": null,
        "current": {
          "selected": false,
          "text": "All",
          "value": "$__all"
        },
        "datasource": "InfluxDB",
        "definition": "",
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": true,
        "label": null,
        "multi": true,
        "multiFormat": "regex values",
        "name": "host",
        "options": [],
        "query": "SHOW TAG VALUES WITH KEY = \"hostname\" WHERE \"datacenter\" =~ /^$datacenter$/",
        "refresh": 1,
        "refresh_on_load": false,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": null,
        "tagsQuery": null,
        "type": "query",
        "useTags": false
      },
      {
        "allFormat": "glob",
        "auto": true,
        "auto_count": 5,
        "auto_min": "10s",
        "current": {
          "selected": false,
          "text": "1m",
          "value": "1m"
        },
        "datasource": null,
        "description": null,
        "error": null,
        "hide": 0,
        "includeAll": false,
        "label": "",
        "name": "summarize",
        "options": [
          {
            "selected": false,
            "text": "auto",
            "value": "$__auto_interval_summarize"
          },
          {
            "selected": true,
            "text": "1m",
            "value": "1m"
          },
          {
            "selected": false,
            "text": "10m",
            "value": "10m"
          },
          {
            "selected": false,
            "text": "30m",
            "value": "30m"
          },
          {
            "selected": false,
            "text": "1h",
            "value": "1h"
          },
          {
            "selected": false,
            "text": "6h",
            "value": "6h"
          },
          {
            "selected": false,
            "text": "12h",
            "value": "12h"
          },
          {
            "selected": false,
            "text": "1d",
            "value": "1d"
          },
          {
            "selected": false,
            "text": "7d",
            "value": "7d"
          },
          {
            "selected": false,
            "text": "14d",
            "value": "14d"
          },
          {
            "selected": false,
            "text": "30d",
            "value": "30d"
          }
        ],
        "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d",
        "queryValue": "",
        "refresh": 2,
        "refresh_on_load": false,
        "skipUrlSync": false,
        "type": "interval"
      },
      {
        "datasource": "InfluxDB",
        "description": null,
        "error": null,
        "filters": [],
        "hide": 0,
        "label": null,
        "name": "adhoc",
        "skipUrlSync": false,
        "type": "adhoc"
      }
    ]
  },
  "time": {
    "from": "now-1h",
    "to": "now"
  },
  "timepicker": {
    "collapse": false,
    "enable": true,
    "notice": false,
    "now": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "status": "Stable",
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ],
    "type": "timepicker"
  },
  "timezone": "browser",
  "title": "InfluxDB Templated",
  "uid": "000000002",
  "version": 5
}`

**Comment by zuchka** [comment]
@sebcaps I know that you cannot save panels on the playground site, but can you please link to the dashboard you modified and screenshot how you changed it?

Also, I see this issue continues a lengthy conversation you started in the forum:
https://community.grafana.com/t/transformation-group-by-date/56525/10

I would also [share your raw, unformatted data](https://cln.sh/PTgRFb). And please share that data inside triple backticks [ ``` ] for a code block

**Comment by sebcaps** [comment]
Hello,
Indeed I first ask the question in community forum, just to be sure.
Here is the requested info : 
I used this [dashboard ](https://play.grafana.org/d/000000002/influxdb-templated?orgId=1&editPanel=1&tab=transform) 
![image](https://user-images.githubusercontent.com/24374878/143677483-3da895c9-c232-4c75-9a90-8b9113ba5468.png)
About data here it is : 
```"Time","10.1.100.1"
1638005280000,
1638005340000,-682.234454353537
1638005400000,-673.9099952295427
1638005460000,-669.1847411909125
1638005520000,-671.0988683515071
1638005580000,-669.4562762399381
1638005640000,-662.0206772524051
1638005700000,-653.0851966772351
1638005760000,-650.6144883741057
1638005820000,-651.816077900333
1638005880000,-654.7956452806509
1638005940000,-657.348037652674
1638006000000,-658.5442347716071
1638006060000,-664.1684681942705
1638006120000,-663.8505839815979
1638006180000,-655.2819178548076
1638006240000,-660.1081927145045
1638006300000,-656.5319735279569
1638006360000,-658.6354890116793
1638006420000,-664.7530845386171
1638006480000,-665.4443105905101
1638006540000,-667.7162844780585
1638006600000,-671.6388245726272
1638006660000,-668.9398474246503
1638006720000,-665.5678623803207
1638006780000,-663.7153583805346
1638006840000,-661.3460329319906
1638006900000,-660.6707780503726
1638006960000,-657.2657779203946
1638007020000,-653.5588806644749
1638007080000,-655.7117460067332
1638007140000,-658.2949909320707
1638007200000,-656.8956978862897
1638007260000,-653.565678367576
1638007320000,-657.1324409867283
1638007380000,-668.5576183566856
1638007440000,-674.2678970830219
1638007500000,-675.6941005919361
1638007560000,-673.4703148290996
1638007620000,-672.8924022683808
1638007680000,-666.5581051868448
1638007740000,-670.8072385637564
1638007800000,-666.9179369619663
1638007860000,-664.3711404707826
1638007920000,-664.6454962192746
1638007980000,-665.7856521855251
1638008040000,-667.3055818009685
1638008100000,-670.1906176940237
1638008160000,-670.7107720308385
1638008220000,-666.3586489345582
1638008280000,-668.3093825792263
1638008340000,-668.0448798270426
1638008400000,-657.4201045801868
1638008460000,-654.6912451447406
1638008520000,-660.5079949124782
1638008580000,-662.8371433144686
1638008640000,-664.1350638019607
1638008700000,-663.8349034260917
1638008760000,-664.4348007236073
1638008820000,-667.7280153453851
1638008880000,-670.8742866288666

 ```

**Comment by zuchka** [comment]
thanks @sebcaps. Here is a panel on play.grafana with the behavior.
https://play.grafana.org/d/000000002-foo/42326?orgId=1&editPanel=1&tab=transform

I couldn't get the formatting suggestions [in the docs](https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#convert-field-type) to apply.

**Comment by ashharrison90** [comment]
hi @sebcaps 👋 

the 'Date format' field in the 'Convert field type' transformer doesn't alter the **output** in any way. the intended use is to tell our date parser the format of the **input**. 

e.g. when parsing a string like `01-02-2021`, is that 1st Feb 2021 (British format) or 2nd Jan 2021 (American format)? the only way for Grafana to know is if you tell us the format, e.g. `DD-MM-YYYY`, then our date parser can then convert this to the correct date object.

i'm going to add a tooltip here clarifying the behaviour as much as possible because you're not the only person who's found this confusing.

hope that helps!

**Comment by sebcaps** [comment]
Hi, @ashharrison90, ok I got your point, but:
- definitely [doc ](https://grafana.com/docs/grafana/latest/panels/transformations/types-options/#convert-field-type) is not so clear as it explicitely describe output transformation ( input 2017-07-01 with format YYYY is "transformed" to 2017-01-01 00:00:00, even if we could expect 2017, not so strange that it's transformed to the 1st day of the year)
-expected behavior has been [reported ](https://community.grafana.com/t/transformation-group-by-date/56525/10) as OK with other datasource

**Comment by ashharrison90** [comment]
@sebcaps completely agree about the docs being unclear, i'm putting together a PR to fix that now 👍 

for the other datasource, i can only guess that the date is being returned as a string. in your case the date is a unix timestamp (e.g. `1638005340000`), so this transformation doesn't even run as we already know the exact date. 

i'm not sure exactly what your use case is... are you trying to group by day? if so, i think the best bet is to modify the data returned by your query. i think influx allows something like `GROUP BY time(1d)` 🤔

**Comment by sebcaps** [comment]
In my use case I can not use ```GROUP BY``` since I'm using influx ELAPSED function and  this particular case it does not have make sense. I'll try to found another solution.
Thank you for your input and doc update.

**Comment by krolli53** [comment]
Hello, I am still suffering from this issue. The doc still states that you can transform the output (which would be very very helpful). And on top, the actual wanted behaviour (telling grafana the input format) doesn't work for me either. The only way to get grafana working with the correct date is to change the input format in the source (in my case a google spreadsheet). Is there a way to get this working correctly?
