### ISSUE TITLE
Values shown on mouse hover

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4233]
is it possible to show a different set when hovering the mouse over a particular point?
Currently, it shows values that are plotted already
But wondering if it is possible to show extra information like say a text or id that is not plotted
Different from annotations

**Comment by bergquist** [comment]
That's not possible at the moment. Whats the use case for this that annotations cannot solve?

**Comment by eben23** [comment]
when am looking at say trades vs quotes, and there are several 1000s of them, annotations draws lives all over the place and brings the browser to a standstill

**Comment by torkelo** [comment]
closing due to similar to https://github.com/grafana/grafana/issues/3341
