### ISSUE TITLE
Docs feedback: /installation/debian.md

### ISSUE THREAD

**Issue by jsigned** [grafana/grafana#42331]
This line of the installation instructions no longer works:
wget -q -O - https://packages.grafana.com/gpg.key | sudo apt-key add -

It produces this error:
Warning: apt-key is deprecated. Manage keyring files in trusted.gpg.d instead (see apt-key(8)).

**Comment by zuchka** [comment]
Thanks for creating this issue, @jsigned 

this is known and a duplicate of [this issue](https://github.com/grafana/grafana/issues/35467). I'm working on a PR rn for it.
