### ISSUE TITLE
Unable to update existing dashboard via api even after enabling overwrite

### ISSUE THREAD

**Issue by vijay62723** [grafana/grafana#42330]
**What happened**: I'm trying to update an existing dashboard using api but its throwing an error message: 'A dashboard with the same uid already exists'

**What you expected to happen**: it should update the existing dashboard as per Grafana : https://grafana.com/docs/grafana/latest/http_api/dashboard/

**How to reproduce it (as minimally and precisely as possible)**: 
So I added "overwrite": true on the top level of the JSON file as below 
{
  "meta": {...
},
  "dashboard": {...
 },
  "folderId": 0,
  "message": "made some changes",
  "overwrite": true
}
==========================
And I'm using axios to post json data to grafana as below 

const updated_data = await axios({
            method: "POST",
            url: `https://grafana.com/api/dashboards/db`,
            headers: {
              "Content-Type": "application/json",
              Authorization: "Bearer eyJrIjoiS=",
              
            },
            data: prod_dashboard_data,
            
            
          });
======================================

then the error message appears :  data: { message: 'A dashboard with the same uid already exists' }
 status: 400,
 statusText: 'Bad Request',

**Anything else we need to know?**: I have even tried moving "overwrite": true to meta object level and also in dashboard level but no luck

**Environment**:
- Grafana version: latest (not sure exact version )
- Data source type & version: Prometheus ( not sure about the version)
- OS Grafana is installed on: helm charts
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
> Grafana version: latest (not sure exact version )

Can I ask, @vijay62723, what is it about your Grafana setup that prevents you from knowing your version? You are using Helm + K8s? Grafana version is critical to understanding your problem. You should be able to hit the `/api/health` endpoint for some metadata about your instance.

I would also try turning up the verbosity of the Grafana server logs and seeing what error messages it produces.

**Comment by vijay62723** [comment]
Hi @zuchka ,
Grafana version is : v8.2.4 

And I cannot paste the complete error message here as it has some sensitive information.
I think all its saying is 400 bad request.
data: { message: 'A dashboard with the same uid already exists' }
status: 400,
statusText: 'Bad Request',
