### ISSUE TITLE
Graph display error

### ISSUE THREAD

**Issue by waveschou** [grafana/grafana#42343]
Hi guys I found a problem. 
When drawing with graph, there are color blocks outside the curve.
I can be sure that there is no problem with my data, there is no negative number, this error will disappear after refreshing, and the color blocks are random.
I think I need some help pls.

chrome : 95.0.4638.69
plugins: graph
datasource: clickhouse
grafana version: 7.5.3

This is my screenshot:
![20211126-161418](https://user-images.githubusercontent.com/79442700/143548575-beac06cc-fc2b-4787-a09b-5b4f5bb9d73b.png)
![20211126-161423](https://user-images.githubusercontent.com/79442700/143548590-c5cf9e28-b499-4b28-8cff-1e65fd0da56f.png)
![20211126-161426](https://user-images.githubusercontent.com/79442700/143548592-21896f09-30ae-44ea-a3a5-12e9237086c4.png)

**Comment by torkelo** [comment]
Strange, no other similar report. 

What graph panel are you using old or timeseries? Can you try upgrading to 8.2 ? 

Share panel json & query data

**Comment by waveschou** [comment]
> Strange, no other similar report.
> 
> What graph panel are you using old or timeseries? Can you try upgrading to 8.2 ?
> 
> Share panel json & query data

Ok，I also encountered this problem for the first time

**Comment by ashharrison90** [comment]
hi @waveschou 👋 

it sounds like switching to timeseries has resolved the problem, so i'm going to close this issue.

if i've made a mistake and there's still a problem, please leave a comment and we can reopen this. thanks! 😄
