### ISSUE TITLE
Clean up logs and warnings from frontend unit tests

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#42359]
When we run the frontend unit tests we get a whole bunch of console.log/warn/error messages logged to the console. 

Some of these point out genuine shortcomings and errors in our code and tests, deprecations we should fix, or other more benign warnings. Nonetheless, they're distracting and make it difficult to track down genuine errors in tests

 - https://github.com/grafana/grafana/issues/45023
 - https://github.com/grafana/grafana/issues/45024
 - https://github.com/grafana/grafana/issues/45025
 - https://github.com/grafana/grafana/issues/45026
 - https://github.com/grafana/grafana/issues/45028
 - https://github.com/grafana/grafana/issues/45029
 - https://github.com/grafana/grafana/issues/45030
 - https://github.com/grafana/grafana/issues/45031

**Comment by ashharrison90** [comment]
if we ever get to 0, we could implement https://www.npmjs.com/package/jest-fail-on-console ? 🤔

**Comment by joshhunt** [comment]
Placeholder for common warnings and how to fix
