### ISSUE TITLE
ClipboardButton to share Panel link does not work on Chrome

### ISSUE THREAD

**Issue by joanlopez** [grafana/grafana#42365]
**What happened**:

Once I click on the `<ClipboardButton>` present on the `Link` tab of the `Share Panel` (while trying to share the link to a specific panel present on a dashboard), it displays the success alert but the text (the link, shortened or not) is not actually copied.

**What you expected to happen**:

The text (the link, shortened or not) to be actually copied.

**How to reproduce it (as minimally and precisely as possible)**:

1. Click on the dropdown present along the name of any dashboard panel.
2. Click on "Share".
3. Click on the blue "Copy" button along the panel link.
(Then the link is not actually copied)

**Anything else we need to know?**:

- Did some debugging and looks like the text is being sent to the `clipboard.js` library.
- Tried to update latest patch release of `clipboard.js` library and still not working.
- Tested on Safari and it worked, so looks like something specific to Google Chrome and maybe other browsers.
- Haven't seen any clear issue or insight from `clipboard.js`'s repository, but may worth looking further.

**Environment**: 
- Grafana version: Tested on `main` and `v8.4.0-43362pre`
- Data source type & version: -
- OS Grafana is installed on: MacOS & GCloud
- User OS & Browser: Mac OS Monterrey - `Google Chrome v96.0.4664.55 (Build oficial) (x86_64)`
- Grafana plugins: -
- Others: -

**Comment by joanlopez** [comment]
Here's a screenshot to illustrate the definition above 👇🏻 

<img width="1387" alt="Captura de pantalla 2021-11-26 a las 11 57 58" src="https://user-images.githubusercontent.com/5459617/143580267-08818ba4-0f1f-4a38-8f82-01b25be582ec.png">

**Comment by joshhunt** [comment]
Will look into this further, but FWIW it works as expected for me on Chrome 96.0.4664.45 + Windows 11

**Comment by joanlopez** [comment]
> Will look into this further, but FWIW it works as expected for me on Chrome 96.0.4664.45 + Windows 11

Wow! That's even more weird! 🙄 

Well, at least, how more specific is the issue, less important is, so good in that sense.
Good look with the explorations 💪🏻  Let me know if there's something else I can help with.

**Comment by joshhunt** [comment]
I have not been able to replicate this on Windows 11 + Chrome 96.0.4664.45, macOS Big Sur + Chrome (version unknown), or macOS Monterey 12.0.1 + Chrome 96.0.4664.55.

Steps I tried:

1. Visit [play.grafana.org](https://play.grafana.org/)
2. Click the panel title menu on the "server requests" panel on the Play homepage
3. Click Share
4. Click Copy
5. Link was successfully copied to the clipboard.

It also works as expected when trying to share the Dashboard also.

@joanlopez @dprokop Does the issue happen for you on [play.grafana.org](https://play.grafana.org/) ?

**Comment by dprokop** [comment]
@joshhunt - works just fine for me on play... :)

**Comment by joshhunt** [comment]
I can reproduce this locally, but not on any deployed instance 🤔  
Weird, but at least it's somewhere to start :)

**Comment by joshhunt** [comment]
Regression was caused by https://github.com/grafana/grafana/pull/41449/files?diff=split&w=1#diff-1f412eb5da2a5dc5eb72c3c79fc90dc8aa3c5e3555435efa7dd9fee74fa66ef5 adding `<FocusScope />` to `<Modal />`.

**Comment by kaydelaney** [comment]
For what it's worth, ClipboardJS depends on [document.execCommand](https://developer.mozilla.org/en-US/docs/Web/API/Document/execCommand) which has been deprecated, so it might be time to move to the [Clipboard API](https://caniuse.com/mdn-api_clipboard_writetext)

**Comment by joanlopez** [comment]
> I have not been able to replicate this on Windows 11 + Chrome 96.0.4664.45, macOS Big Sur + Chrome (version unknown), or macOS Monterey 12.0.1 + Chrome 96.0.4664.55.
> 
> Steps I tried:
> 
> 1. Visit [play.grafana.org](https://play.grafana.org/)
> 2. Click the panel title menu on the "server requests" panel on the Play homepage
> 3. Click Share
> 4. Click Copy
> 5. Link was successfully copied to the clipboard.
> 
> It also works as expected when trying to share the Dashboard also.
> 
> @joanlopez @dprokop Does the issue happen for you on [play.grafana.org](https://play.grafana.org/) ?

Nope, it does not happen on [play.grafana.org](https://play.grafana.org/) neither for me. 
However, it does happen to me on a hosted instance (internal ops).
