### ISSUE TITLE
Attempting to delete a non-existent folder returns 500

### ISSUE THREAD

**Issue by cristiangreco** [grafana/grafana#42375]
**What happened**:
Using the [Delete Folder](https://grafana.com/docs/grafana/latest/http_api/folder/#delete-folder) API endpoint to attempt to remove a non-existent folder returns a `500` error.

Request: `DELETE /api/folders/something`
Response: `{"message":"Folder API error"}`

**What you expected to happen**:
This endpoint should return `404` if the folder doesn't exist.

**How to reproduce it (as minimally and precisely as possible)**:
```
curl -X DELETE -H "Authorization: Bearer [REDACTED]" https://grafana.example.com/api/folders/something
```

**Anything else we need to know?**:
Logs show:

```
lvl=eror msg="Folder API error" logger=context userId=0 orgId=1 uname= error="found 0 folders, while expecting at most one"
```

The message seems to originate [here](https://github.com/grafana/grafana/blob/v8.2.5/pkg/services/libraryelements/database.go#L694).

**Environment**:
- Grafana version: 8.2.5

**Comment by ying-jeanne** [comment]
i am able to reproduce the issue with error code 500.
```
Successful POST request | AssertionError: expected response to have status code 200 but got 500
```
