### ISSUE TITLE
TimeSeries: Data links are not shown in context menu when you click inside bar 

### ISSUE THREAD

**Issue by GrzegorzLyp** [grafana/grafana#42398]
**What happend**: Regretion of usability of data links in Time Series visualization with stack bars:

**What is expected**: Option to work data links same as in Grafana 7 for stack bars:

**How to repeat**: Create stack bar time series with many values and try to click or see data point to use data links.:

**Environment**:
- Grafana version: 8.1.7 (same on play.grafana.org)

This is Graph (old) - works great
![image](https://user-images.githubusercontent.com/29247982/143644816-e60fe9a4-63a5-4c85-9dfc-d1d4bf253fd2.png)

This is TimeSeries - nightmare
![image](https://user-images.githubusercontent.com/29247982/143645315-8429b115-7050-4a16-a5f4-dd82b01348d1.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @GrzegorzLyp 

would you say this issue describes your situation?
https://github.com/grafana/grafana/issues/42130

**Comment by GrzegorzLyp** [comment]
> Thanks for creating this issue, @GrzegorzLyp
> 
> looks similar to this issue, would you say? #42130

Seems similiar but Bar Chart is now in beta and data links does not work at all. It seems like Bar Chart is not to date histograms and Time Series seems better replacement.

**Comment by hugohaggmark** [comment]
Moving this to @grafana/grafana-bi-squad

**Comment by torkelo** [comment]
I can see the data links "Details" in the menu

**Comment by torkelo** [comment]
ok have a replication here: https://play.grafana.org/d/yFWXvUp7z/data-links?orgId=1&from=now-30m&to=now 

The issue is that to get the data context menu to show the data links you need to click the "data point" the top of the bar, clicking inside the bar does not count (and no data link is shown), only when you click the actual point is the data links shown.
https://play.grafana.org/d/yFWXvUp7z/data-links?orgId=1&from=now-30m&to=now

**Comment by GrzegorzLyp** [comment]
Grafana 9 still does not have the problem fixed. Data Links seems to be useless in this case.

**Comment by nmarrs** [comment]
This should now be easier to support given [recent refactor of datalink handling in Time series](https://github.com/grafana/grafana/pull/76492)

**Comment by GrzegorzLyp** [comment]
Tested on 10.2 and works fine. When You change "Point Size" to 0 it works even better (thos points are not necessary anymore). From my point of view this issue can be closed.
