### ISSUE TITLE
Address Geomap 8.3 backport

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#42393]
[Jack Westbrook]: Yesterday we began releasing 8.3.0.beta2 and discovered some Geomap PRs that were targeting the 8.3.0-beta2 milestone but hadn't been backported. We merged any open ones to main and added the backport label in an attempt to get them into the beta2 release but ran into conflicts. In the end we moved them to the 8.3.0 milestone. If you'd like the following PRs to make the 8.3.0 stable could someone that understands the changes take the time to backport them please? Many thanks. :pray:
https://github.com/grafana/grafana/pull/41992
https://github.com/grafana/grafana/pull/42252
https://github.com/grafana/grafana/pull/42254
https://github.com/grafana/grafana/pull/42266

**Comment by mckn** [comment]
Closed due to #42399
