### ISSUE TITLE
Serviceaccounts: UI tab component for service accounts

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#42403]
**Why is this component needed**:
We want to replace this tab with the serviceaccounts tab and include apikeys within the serviceaccounts tab. As we are implementing serviceaccounts that will include apikeys and eventually we will be able to only add apikeys within a service account.

___
 - [ ] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

___
- [ ] Post screenshots possible.
- [ ] It has a single use case.
- [ ] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by dprokop** [comment]
@eleijonmarck please add description and apply adequate labels

**Comment by mjseaman** [comment]
Closing - we can construct the Service Accounts views using existing components.
