### ISSUE TITLE
Dashboard does not iterate over multi-value datasource variable

### ISSUE THREAD

**Issue by Matthew-Beckett** [grafana/grafana#42408]
**What happened**:

When making a dashboard template variable of type "Datasource", Datasource type "Prometheus" and then enabling the property "Multi-value", Grafana does not iterate over multiple prometheus datasources only the first.

**What you expected to happen**:

I expect to be able to provide multiple Prometheus datasources and the dasboard iterate over the count of prometheus datasources combining metrics based on query.

For example:

My two prometheus instances contain identical metrics from different sources, I expected Grafana to iterate over `(${prometheus})` and group metrics by the provided arguments

```
sum(probe_icmp_duration_seconds{phase="rtt",target=~"$target", location!=""} * 1000) by (location, target)
```

**How to reproduce it (as minimally and precisely as possible)**:

1. Add two prometheus instances as datasources
2. Create a dashboard with a datasource variable called `$prometheus` of type `prometheus`, enable multi-value
3. Create chart, set datatsource as `$prometheus` and add query
4. Select multiple datasources in dashboard

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Official Docker Container
- User OS & Browser: Firefox on Pop_OS! 21.04 LTS
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
@dprokop you're absolutely right, we have this issue that I think explains it: https://github.com/grafana/grafana/issues/16543

**Comment by dprokop** [comment]
Thank you @hugohaggmark!
