### ISSUE TITLE
OAuth: there is no ability to logout if email is not in "allowed_domain".

### ISSUE THREAD

**Issue by alexsuraykin** [grafana/grafana#42407]
If you enter an invalid domain in the login, you will not be able to login/logout through the web interface.

**Steps To Reproduce:**
1. Configure your IDP, create user with email;
2. Deploy Grafana with OAuth and "allowed_domains" parameter, value mustn't be equal user's email domain;
3. Login with user email("Login Failed Required email domain not fulfilled");
4. Click again on the button "Sign in with OAuth", then there will be "Login Failed" error again, because the IDP login has already been completed.

**Actual Result**: There is no way to log out and enter a new login password(As a workaround - add "/logout" endpoint to the url).
**Expected Result**: button or other way(automatic redirect) to log out.

**Environment**:
- Grafana version: 7.1.0
- Data source type & version: Prometheus
- OS Grafana is installed on: K8s
- User OS & Browser: Windows 10, Chrome, Firefox

**Comment by dprokop** [comment]
Thanks @alexsuraykin for opening the issue. I'll pass it to @grafana/backend-platform who is probably the best to help you with the issue.

**Comment by papagian** [comment]
@alexsuraykin which providers do you use? I'm asking because investigating how to solve this can differ for each provider.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by alexsuraykin** [comment]
Hello everyone, sorry to keep you waiting. We are using Keycloak.

**Comment by ybizeul** [comment]
I'm getting similar behavious with Grafana 8.3.4 configured for LDAP authentication.
There is no profile menu on the lower left hand corner, hence no way to logout/signout

**Comment by Jamsek-m** [comment]
Same problem here. We run Keycloak on our `auth.example.com` domain, and grafana on `grafana.example.com`, with configured allowed domains option to `example.com`. A Keycloak user who has email set to `user@gmail.com` gets error on login saying it has invalid email. Changing that user's email to `user@example.com`, enables him to login.

**Comment by kminehart** [comment]
sorry if I'm not understanding correctly but that sounds like it's working as intended, no? @Jamsek-m

**Comment by Jamsek-m** [comment]
I guess so, but shouldn't user be able to have a different email, if he so chooses? 

Or is allowed domain used only for registration check, and has no effect on rest of OAuth config (so it can be safely disabled, if we want different emails)?

**Comment by mgyongyosi** [comment]
@mgyongyosi please check this whether it can be reproduced in 9.3.
