### ISSUE TITLE
Elasticsearch singlestat average aggregation is wrong

### ISSUE THREAD

**Issue by dax** [grafana/grafana#4240]
When using Elasticsearch query in a singlestat panel, average aggregation is giving the wrong result.

Indeed, Elasticsearch is queried for an average value for each interval and then the final average value is computed based on all these average values which is not the same as the average of all raw values.

As far as I understand, a singlestat panel should display the average of all raw values for a given time range and filter.
To get the actual average value of a field for a time range, this aggregation returns the expected average:
```
{"avg": {"field":"myfield"}}
```

**Comment by torkelo** [comment]
you can control how many values Elasticsearch returns by changing the date histogram interval, either on the query or below the queries you have an option to change this interval. 
If you change to to 1y  (1 year) Elasticsearch will average all values on only return one value for the time range (unless the time range is more than 1 year).

![Uploading image.png…]()

**Comment by dax** [comment]
This is unfortunate to have to use this trick to get a correct value.
Moreover, using this trick is incompatible with spark lines which use the result of `date_histogram` aggregation.

**Comment by torkelo** [comment]
Trick?????? 

The query returns many values due to date histogram, you can select what of the many values you want in the options tab. 

You can make the query return a single value by changing the date histogram parameter. 

Not sure where the trick / confusion is.

**Comment by dax** [comment]
OK, this is not a trick :)
but it is still incompatible with with spark lines.

**Comment by torkelo** [comment]
Anyway if you select avg in the Options tab as the value, this should be the average of all the values returned by elasticsearch, So that should be the same as the Average of all the values.

**Comment by dax** [comment]
No an average of average values is not the same as an average as all values.

For ex, with 2 intervals:
- if we have 2 values for the first interval: 1 and 3 (ES returns 2 as the average value for this interval)
- if we have 3 values for the second interval : 1, 3, 6 (ES returns 3 as the average value for this interval)
Then the average of the 2 averages (2 and 3) is 2.5.
This is what is currently done by the singlestat panel.

Whereas the real average is `(1+3+1+3+5)/5 = 2.8`

**Comment by torkelo** [comment]
well for uniform data (where the number of measurements per interval is the same) which is what Grafana was originally built for (time series),  the average of average should be the same if I remember my maths right

**Comment by dax** [comment]
Yes for uniform data, this is right.
This is also why I use elasticsearch for my use case instead of graphite where I cannot get good summary values (for the same reason date histogram is not good for computing a single average value).

At the end I will use your advice for now and fork singlestat panel for my use case.
