### ISSUE TITLE
Firing and Resolved alerts are in the one Slack message

### ISSUE THREAD

**Issue by a-mazed** [grafana/grafana#42415]
**What happened**:

Sometimes I have a list of firing and resolved alerts in one Slack message. But the title is only about firing alerts.
For example:

```
[FIRING: 4] Alert name
4 firing:
 *firing alerts list*

6 resolved:
 *resolved alerts list*
```
I don't know if it's a bug, but I'm sure it’s a very bad behavior because I have to read an entire message to find alert’s status changing.

**What you expected to happen**:
I need separate messages for firing and resolved alerts
OR
Proper message header with counters both for firing and resolved alerts. For example:
`[FIRING: 4, RESOLVED: 6] Alert name`

**How to reproduce it (as minimally and precisely as possible)**:
Just use NGAlerts with a couple of dozens alert rules 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Centos 8
- User OS & Browser: Windows 10
- Grafana plugins: -
- Others: -

**Comment by BrikerMan** [comment]
+1 for the separate messages for firing and resolved alerts

**Comment by JoV8** [comment]
Same is happening for MS Team, +1

**Comment by JacobsonMT** [comment]
Thanks for the reporting the issue @a-mazed!

From what I see, the message title could definitely use some improvement for group notifications with both firing and resolved statuses. I'll go ahead and make a PR for that.

For the other request of splitting the notifications into two (one firing, one resolved), I have a followup question for everyone here. Would the existing feature of notification policy route grouping (See https://grafana.com/docs/grafana/next/alerting/unified-alerting/notifications/#grouping) cover your needs here? 

By default routes group all matching alerts together into single notifications as you are seeing, however if you specificy a "Group by" they can be grouped into multiple separate notifications. Note the special value of "..." will effectively disable grouping entirely, thus giving you a separate notification for each alert matching the route.

**Comment by BrikerMan** [comment]
> Thanks for the reporting the issue @a-mazed!
> 
> From what I see, the message title could definitely use some improvement for group notifications with both firing and resolved statuses. I'll go ahead and make a PR for that.
> 
> For the other request of splitting the notifications into two (one firing, one resolved), I have a followup question for everyone here. Would the existing feature of notification policy route grouping (See https://grafana.com/docs/grafana/next/alerting/unified-alerting/notifications/#grouping) cover your needs here?
> 
> By default routes group all matching alerts together into single notifications as you are seeing, however if you specificy a "Group by" they can be grouped into multiple separate notifications. Note the special value of "..." will effectively disable grouping entirely, thus giving you a separate notification for each alert matching the route.

@JacobsonMT This looks good too. But I will more prefer a single message for each Firing / Resolved status. Since we can forward that specific message, convert it into a thread.

If I have [FIRING: 2, RESOLVED: 1]. I really hope I can receive 3 messages instead of a grouped message. Is this something we can do?

**Comment by matrog** [comment]
> If I have [FIRING: 2, RESOLVED: 1]. I really hope I can receive 3 messages instead of a grouped message. Is this something we can do?

+1

https://github.com/grafana/grafana/discussions/46515

**Comment by JacobsonMT** [comment]
> If I have [FIRING: 2, RESOLVED: 1]. I really hope I can receive 3 messages instead of a grouped message. Is this something we can do?

Yes, this is something you can do by setting the "group by" to the special value of "...". It should then disable grouping of alerts and start sending one notification per alert.

![image](https://user-images.githubusercontent.com/8484471/159458488-23319cfd-e4eb-4d91-bc9f-9db7f935a3ea.png)

**Comment by BrikerMan** [comment]
> > If I have [FIRING: 2, RESOLVED: 1]. I really hope I can receive 3 messages instead of a grouped message. Is this something we can do?
> 
> Yes, this is something you can do by setting the "group by" to the special value of "...". It should then disable grouping of alerts and start sending one notification per alert.
> 
> ![image](https://user-images.githubusercontent.com/8484471/159458488-23319cfd-e4eb-4d91-bc9f-9db7f935a3ea.png)

Thanks, it works. Hope we can see this kind of details on the docs.

**Comment by matrog** [comment]
Thanks it works fine but would be good to still have the chance (maybe another secret label) to have FIRING and RESOLVED separated as the original requests.

**Comment by a-mazed** [comment]
Sorry for writing in the closed issue, but I still don't understand how to get a message title like [FIRING: 2, RESOLVED: 1].
Can you explain it please?
Using "group by" → "..." isn't a solution at all, because it breaks grouping.

**Comment by a-mazed** [comment]
I'm using Grafana 8.5.4 and still see alert messages like

```
[FIRING: 4] alertname
4 firing:

13 resolved:
```

Is it something I have to change in options or in templates?

My template title

```
{{ define "template_title" }}
[{{ .Status | toUpper }}: {{ if eq .Status "firing" }}{{ .Alerts.Firing | len }}{{ else if eq .Status "resolved" }}{{.Alerts.Resolved | len }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }}
{{ end }}
```

**Comment by JacobsonMT** [comment]
Ah, this was a change to the default template title if you have defined your own you won't see the change. The new default looks like this:

`[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ if gt (.Alerts.Resolved | len) 0 }}, RESOLVED:{{ .Alerts.Resolved | len }}{{ end }}{{ end }}] {{ .GroupLabels.SortedPairs.Values | join " " }} {{ if gt (len .CommonLabels) (len .GroupLabels) }}({{ with .CommonLabels.Remove .GroupLabels.Names }}{{ .Values | join " " }}{{ end }}){{ end }}`

The change basically added the following:

`{{ if gt (.Alerts.Resolved | len) 0 }}, RESOLVED:{{ .Alerts.Resolved | len }}{{ end }}`

You can add this to your custom title or remove your custom title and use the default, either should work here.

**Comment by a-mazed** [comment]
Thank you very much. It was pretty obvious. I don't know why I didn't get it earlier

**Comment by a-mazed** [comment]
@JacobsonMT this template has a bug.
Those ifs will never return count of resolved alerts in case if there are no firing alerts. We can get only those combinations:
```
[FIRING: NUM, RESOLVED: NUM]
[FIRING: NUM]
[RESOLVED]
```
Checked on default template
![image](https://user-images.githubusercontent.com/25726917/177987425-46c68bb3-9104-401a-855d-1aaf828a6956.png)

![image](https://user-images.githubusercontent.com/25726917/177987048-d31879fc-37a5-4f5c-82cb-bb0783eecd89.png)

**Comment by a-mazed** [comment]
This is the working template
`[{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ if gt (.Alerts.Resolved | len) 0 }}, RESOLVED:{{ .Alerts.Resolved | len }}{{ end }}{{ else if eq .Status "resolved" }}:{{ .Alerts.Resolved | len }}{{ end }}] `

**Comment by JacobsonMT** [comment]
@a-mazed AFAIK, this is intentional. Resolved is a state that implies all referenced alerts in the group are no longer firing. That being said, your template looks good and there's nothing wrong with adding the number of resolved alerts as you've done.

**Comment by tfreycb** [comment]
Is there a way to group by firing and resolved status to ensure I get two separate alert notifications, one for the group of firing alerts and one for the group of resolved alerts. I don’t like that they’re being commingled.

**Comment by jgournet** [comment]
@JacobsonMT : quick follow up on the "group_by":
I actually **need** to use a "group_by" option (I currently use:
```
group_by: ['alertname','grafana_folder']
```
so disabling grouping altogether is not an option.
Is there a way to finetune the "group_by" to not group by status ?
I tried:
```
group_by: ['alertname','grafana_folder','status']
```
but that does not work 
=> is there a way to make this work ?

**Comment by Siddhesh-Shinde** [comment]
> @JacobsonMT : quick follow up on the "group_by": I actually **need** to use a "group_by" option (I currently use:
> 
> ```
> group_by: ['alertname','grafana_folder']
> ```
> 
> so disabling grouping altogether is not an option. Is there a way to finetune the "group_by" to not group by status ? I tried:
> 
> ```
> group_by: ['alertname','grafana_folder','status']    ( and different variations, like ".status", "Status", ".Status")
> ```
> 
> but that does not work => is there a way to make this work ?

@jgournet by default grafana doesn't group alerts on the basis of status.
So default settings group_by: ['alertname','grafana_folder'] should work

**Comment by jgournet** [comment]
> @jgournet by default grafana doesn't group alerts on the basis of status. So default settings group_by: ['alertname','grafana_folder'] should work
unless this has changed recently ( I put the whole thing on hold for a while because of that kind of issues ), I was receiving alerts with both OK and "Firing" in the same payload (this is for alerts with multiple metrics - each one can independently fire)
