### ISSUE TITLE
Grafana color change to graph dynamically

### ISSUE THREAD

**Issue by slbmadhuri** [grafana/grafana#4241]
Hi all, 

I recently started learning grafana, I have a questions and would want to know if its possible doing it and the way to do it.

I am monitoring some errors every 1 hour from my DB and there are some colors that automatically appear in grafana for those errors. If there is a new error/errors coming up in the ext 1 hour can I have a red color/some different color just to show up the change that a new error resulted from the DB. I cannot hard code the error as they keep changing for every 1 hour and it comes from the DB.

Any suggestions on this will be very helpful.

Thanks,
Lakshmi

**Comment by torkelo** [comment]
if the error series gets a new name it and the old error series is still returned grafana will use another color for the series
