### ISSUE TITLE
Consistent and specific way to set colors/alpha

### ISSUE THREAD

**Issue by evanbreznyik** [grafana/grafana#4242]
Right now, I have two problems related to editing of graphs that can be solved with one solution:

1.  In the "Axes & Grid" tab, when setting the threshold colors, it's nearly impossible to be consistent with the colors/transparency if I want to customize these colors between my graphs.  In other words, if I want to make it 50% transparent yellow for "level 1" on two separate graphs, it's down to guesswork, since the color picker doesn't let me _also_ specify _specific_ RGBA (colors + alpha) values:
![Threshold Color Picker](http://i.imgur.com/hOFfYdb.png)

2.  Conversely, in the "Display Styles" tab, there's really a shortage of colors for series specific options.  While I think it's great to have a preset list that is consistent, it also prevents me from using my own unique or specific colors and alpha/transparency values if I want to use values beyond this list.  What's more, using "Line Fill" here instead of just a simply alpha to go with the color makes this inconsistent with how you set colors elsewhere for graphs.
![Series Specific Color Picker](http://i.imgur.com/UODs7bF.png)

I guess I am asking that the color picker not only be **consistent** in Grafana, but also allow me to *specify* specific colors/alphas (HSL + alpha + rgba text input) OR pick (from presets).  (Why not just use a combination of the preset colors and an option of the color picker/alpha slider/RGBA values to cover all these scenarios?)

This picker is very close to being just about right (without having presets):
![RGBA Color Picker](http://i.imgur.com/UN6mQth.png)

This lets you enter values as (r,g,b,a) if you know what you want -- as well as using the HSLV sliders if you want to experiment.

**Comment by torkelo** [comment]
all good points, we really want to unify the color selection, not had time to do it yet.

Will close this issue as it is already suggested https://github.com/grafana/grafana/issues/2322
