### ISSUE TITLE
Render bug when using "fill below to"

### ISSUE THREAD

**Issue by evanbreznyik** [grafana/grafana#4243]
When I use "fill below to" on a graph for a series, I often get a render bug on the left axis of the graph where the metrics for the series using "fill below to" are rendered a few pixels wider than expected (circled in red):

![Render Bug](http://i.imgur.com/HZD3LGj.png)

This is Grafana 2.6.0.

**Comment by torkelo** [comment]
thanks for reporting this,

**Comment by jessetan** [comment]
Wanted to add that I also see this, but that lines, bars, points **and** line fill are always properly drawn (do not overlap the left Y axis), so it would seem limited to just the "fill below" area
![fill below rendering](https://cloud.githubusercontent.com/assets/3284111/14282749/18ee7196-fb40-11e5-9651-bdc9e69c2466.png)


(Grafana 2.6.0 and Grafana 3.0.0 beta)

**Comment by torkelo** [comment]
Looks like a problem with the fill below to flot plugin, will try to investigate

**Comment by mariusoe** [comment]
This is also happening, when the line that is used as target is below the chart (e.g. if the minimum has been set to a fixed value). In this case, the area outside the actual chart is highlighted.

See image:
![grafana_fillbelow_bug](https://cloud.githubusercontent.com/assets/1217782/16142486/07fe4ff0-3466-11e6-91d7-45c5408efa75.PNG)

**Comment by leeoniya** [comment]
this is fixed in the new timeseries panel
