### ISSUE TITLE
Docs feedback: Clarify anonymous access implications in setup-grafana/configure-security/#implications-of-enabling-anonymous-access-to-dashboards

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#42483]
The **Implications of enabling anonymous access to dashboards** section of this doc makes it seem like anonymous access is enabled at a dashboard level, but it is actually enabled at a Grafana level, and individual dashboards can only be _hidden_ from anonymous users. There are also some extra implications.

I think it could say something like:

When you enable anonymous access in Grafana, any visitor can use Grafana as a Viewer without signing in. This section lists the security implications of enabling Anonymous access.

- Anyone with the URL of a dashboard accessible by Viewers can access that dashboard.
- New dashboards are publicly available unless the dashboard creator hides them from all Viewers.
- Anyone can edit or delete dashboards that have granted Edit or Admin abilities to Viewers.
- Anyone can make `view` calls to the API and list all folders, dashboards, and data sources.
- Anyone can make arbitrary queries to any data source that the Grafana instance is configured with.

**Comment by Eve832** [comment]
I think this could conceivably be addressed by either @imatwawana (dashboards) or @lwandz13 (Auth), though it feels like a dashboard topic imo. Either of you want to update the topic with Mitch's suggestions?

**Comment by lwandz13** [comment]
@Eve832 I can update this.

**Comment by lwandz13** [comment]
updates completed!
