### ISSUE TITLE
Serviceaccounts: api endpoint usage per serviceaccounts

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#42481]
## why and what we need
we need to be able to see the api usage per serviceaccount

what we want to do:
- [ ] ability to count the usage of a api endpoint for one serviceaccount
- [ ] implement that across all potential endpoints
- [ ] send usage statistics for the usage of api endpoints per serviceaccount

**Comment by Jguer** [comment]
This might add too many keys to the usage stats, we need to find different measures for this unfortunately

**Comment by eleijonmarck** [comment]
oh okay, we want to see the overall usage of the service account feature. At least on the broad scale

**Comment by Jguer** [comment]
I think https://github.com/grafana/grafana/pull/46619 can answer that
