### ISSUE TITLE
API documentation is not clear

### ISSUE THREAD

**Issue by kitarp29** [grafana/grafana#42494]
**Not Clear about applying Grafana HTTP API**:

**Documentation should be descriptive enough to help beginners like me**:

**Try to apply users API without any prior knowledge of Grafana**:

**Environment**:
- Grafana version: Latest
- Data source type & version: No
- OS Grafana is installed on: MacOs
- User OS & Browser: MacOs & Google Chrome
- Grafana plugins: None
- Others: none

The documentation of Grafana is a little confusing.
While fetching the users via API, the documentation tells.
Basic "Some Token Key"
But it does not tell from where to get the API token key.
It has to declare somewhere, that the API key is user:password is base64 encrypted.
For a developer, it seems like the API key generated on the dashboard settings is the method to achieve the said test case.

It seemed like an issue to me.
And, I would like to work on it. Please assign me this @matschaffer

**Comment by matschaffer** [comment]
I don't have repo access so you'll need someone in the org to assign it to you. I'm sure @torkelo can point you in the right direction.

The guide on https://grafana.com/docs/grafana/latest/http_api/create-api-tokens-for-org/ seems to cover some of those points you mention, but I also found it a little surprising that it didn't show you where in the UI to make a token for yourself. So probably not a bad idea to make some nicer guides.

**Comment by dprokop** [comment]
@kitarp29 feel free to open a PR with the updated documentation. We welcome such contributions with open hands :)

**Comment by kitarp29** [comment]
Sorry, for the delay.
I will be working on this next weekend.
I have my college exams and internship for the week.

**Comment by kitarp29** [comment]
Hey @dprokop 
Which file do I need to make the changes?
the README.md is not the correct file

**Comment by kitarp29** [comment]
ping

**Comment by achatterjee-grafana** [comment]
HTTP API documentation is here: https://github.com/grafana/grafana/tree/main/docs/sources/http_api

**Comment by chri2547** [comment]
This issue is stale. Please feel free to open a new issue, if required.
