### ISSUE TITLE
Bug: Deleted dashboards still in recently viewed list

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4249]
Steps:
* Create a dashboard
* Rename it or delete it
* Go to "Home"

Expected:
* Only see currently existing dashboards

Observed:
* Old dashboard names still listed (even when a dashboard was only renamed)

Version: v2.6.0-1252-gae69244

**Comment by bergquist** [comment]
Thank you for reporting this

**Comment by astsiapanay** [comment]
Not sure it was fixed properly. Deleted dashaboard still appears on recently viewed list. Also deleted record has an empty name that may more confuses user.
![dashboard-list](https://cloud.githubusercontent.com/assets/12490850/14734472/44b8b328-0873-11e6-85f8-a3ee41f3a3b4.png)

**Comment by astsiapanay** [comment]
Looks like local storage "dashboard_impressions" is not updated when dashboard is deleted. It may cause why empty record is still displayed.

**Comment by astsiapanay** [comment]
The problem was here(public/app/plugins/panel/dashlist/module.ts ):
this.dashList = dashboardIds.map(e => {
+          return _.find(result, r => {
+            return r.id === e;
+          });
+        });
map function may return undefined values for those ids which don't exist any longer.
