### ISSUE TITLE
PluginSigning: Private signing doesn't work for serve_from_sub_path=true

### ISSUE THREAD

**Issue by mcr-ksh** [grafana/grafana#42507]
**What happened**:
cant sign plugin when using serve_from_sub_path=true.
Plugin wont be accepted as signed. 
<img width="1677" alt="Screenshot 2021-11-26 at 17 08 43" src="https://user-images.githubusercontent.com/710460/144025039-329ece1d-9e37-4fc9-8fcb-b3b326e268a7.png">
<img width="1635" alt="Screenshot 2021-11-26 at 17 08 15" src="https://user-images.githubusercontent.com/710460/144025047-c266e82a-39ef-4afb-8f32-999565f668e5.png">

**What you expected to happen**:
when rooturls match the plugin is accepted as private signed.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the problem:
1. grafana.ini
root_url = https://localhost/analytics/
serve_from_sub_path = true
2. yarn sign --rootUrls https://localhost/analytics/
3. run grafana and have problem thrown

**Anything else we need to know?**:
I tried without serve_from_sub_path and signing works.

**Environment**:
Version numbers (grafana, prometheus, graphite, plugins, operating system, etc.):
# grafana-server -v
Version 8.2.5 (commit: b57a137acd, branch: HEAD)
Ubuntu 20.04.03 LTS
plugin: mqtt

**Comment by wbrowne** [comment]
@mcr-ksh this is fixed in v8.3.0. The stable release is planned for later this week if you want to try it out.

Thanks!
