### ISSUE TITLE
Plugin "Includes" in plugin.json

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#4255]
When a plugin includes embedded plugins there is not currently any way to know what they are aside from walking the source tree.  Can we get them listed in plugin.json alongside dependencies?

**Comment by bergquist** [comment]
I'm not sure embedded plugins need separate plugin.json files.

If those plugins can be downloaded by them self I think they should be listed as dependencies. Or am I wrong? =)

**Comment by DanCech** [comment]
What I'm saying is that within the plugin.json for the "main" plugin where it has the list of dependencies, it should also include a list of "included" plugins so we can know what is included without having to go spelunking in the source tree.

**Comment by torkelo** [comment]
I agree, this could be added. 

Something like this?
```json
{
 "includes": [
    {"type": "panel", "name": "Nginx Panel"},
    {"type": "datasourcel", "name": "Nginx DS"},
  ]
}
```

The only problem with adding something like above is that is could out of sync with the real plugin.json info (name/id), grafana will scan for included plugins and use the info in the plugin.json and ignore the info in this possible includes property. The only reason for it would be as meta info for grafana.net

**Comment by DanCech** [comment]
Yeah, there is definitely a danger that it could get out of sync but the only problem that would cause would be inaccuracy in the plugin listing so I think it's worth all the effort it'll save us when trying to display plugin details.

**Comment by torkelo** [comment]
@DanCech yea, I agree

**Comment by DanCech** [comment]
@bergquist can you take a look at this?

**Comment by bergquist** [comment]
Yeas! I will update https://github.com/grafana/grafana/blob/master/examples/nginx-app/plugin.json and https://github.com/grafana/app-plugin-example/blob/master/plugin.json

**Comment by DanCech** [comment]
Awesome, thanks!

**Comment by bergquist** [comment]
Both have been updated. 

```json
"includes": {
    "dashboards": [],
    "plugins": [
      {"type": "panel", "name": "Nginx Panel"},
      {"type": "datasource", "name": "Nginx Datasource"}
    ]
  },
```

I've added an array for dashboards but since we dont know what properties they have yet I left it empty. I've only added type and name for plugins since less info will decrease the chance of data going out of sync.

**Comment by bergquist** [comment]
@torkelo what do you think about the dashboard array? Should we treat them as plugins or an separate entity?

**Comment by torkelo** [comment]
@bergquist currently it looks like this for dashboards:

```json
{
  "name": "Graphite",
  "type": "datasource",
  "id": "graphite",

  "dashboards": [
    {"name": "Carbon Stats", "path": "dashboards/carbon_stats.json"}
  ],

  "metrics": true,
  "annotations": true
}
```

**Comment by torkelo** [comment]
and it would be the same for apps

**Comment by bergquist** [comment]
So much development in this area that I'm not aware of. Then I'll remove dashboards and "include" will be an array as suggested earlier in this issue.

**Comment by torkelo** [comment]
@bergquist well I just started on dashboards, lets think about it, maybe it makes sense to have it under a includes section

**Comment by torkelo** [comment]
ok so I changed my mind, think I like that this is under includes, 

```
{
  "name": "Graphite",
  "type": "datasource",
  "id": "graphite",

  "dashboards": [
    {"name": "Carbon Stats", "path": "dashboards/carbon_stats.json"}
  ],

  "metrics": true,
  "annotations": true
}
```

**Comment by torkelo** [comment]
oh, wrong paste

```json
{
  "name": "Graphite",
  "type": "datasource",
  "id": "graphite",

  "includes": {
    "dashboards": [
      {"name": "Carbon Stats", "path": "dashboards/carbon_stats.json"}
    ]
  },

  "metrics": true,
  "annotations": true
}
```

**Comment by torkelo** [comment]
or maybe simplify it?

oh, wrong paste

{
  "name": "Graphite",
  "type": "datasource",
  "id": "graphite",

  "includes": {
      {"type": "dashboard",  "name": "Carbon Stats", "path": "dashboards/carbon_stats.json"} 
  },

  "metrics": true,
  "annotations": true
}

**Comment by torkelo** [comment]
ok, I am now going with this: 

```json
{
"name": "Graphite",
"type": "datasource",
"id": "graphite",

"includes": {
   {"type": "dashboard", "name": "Carbon Stats", "path": "dashboards/carbon_stats.json"},
   {"type": "panel", "name": "Panel name"}  
},

"metrics": true,
"annotations": true
}
```

makes it easier to handle the includes list more generically

**Comment by bergquist** [comment]
Yea. Should make it easier for plugin pages in grafana.net and grafana

**Comment by DanCech** [comment]
Looks good to me

**Comment by bergquist** [comment]
@DanCech Both plugin.json files have been updated. https://github.com/grafana/grafana/blob/master/examples/nginx-app/plugin.json also includes a dashboard that links to an empty file.

**Comment by bergquist** [comment]
Closing this
