### ISSUE TITLE
Date Range Apply Across Dashboards

### ISSUE THREAD

**Issue by fksimon** [grafana/grafana#4256]
We have a simple use case where we have a summary dashboard and several detail dashboards.   We use the summary dashboard for quick identification of systems issues.   We then need more detailed view of the same time frames we have zoomed into on other dashboards, but unfortunately we have to re-pick the date range on each dashboard as we go through them.  This would be sort of equivalent to a click though mechanism on a chart that would open another dashboard with more detail of the information being displayed.

In all cases where we do this we have a specific range selected and we just want to reuse the range.  We are not doing a last x type of view.  Just adding a check box to the date range to "lock" the range unless specifically changed would work.

Example:
Summary page has a view of memory and CPU across multiple machines.   We see a major memory drop on one machine and we then open a dashboard to view details about that machine to see what load was going on at that time frame.   This may lead us to another dashboard for view detail of its dependencies.  Same time frame is needed in all views.

**Comment by torkelo** [comment]
Same as https://github.com/grafana/grafana/issues/1097 

You can sort of solve this now by adding Dashboard Links (option available in dashboard settings), Dashboard links allows you add links to other dashbords bellow the menu to the right, these links can be configured to go to other dashboards and preserve the current time range. 

But would like to solve this in a more generic way, like in the dashboard search have a way to open a dashboard with the current time range
