### ISSUE TITLE
[logging] Adding new key value pairs into cloud logs to make sure the backward compatibility

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#42560]
During Arch Sync, and everyone agreed that:
JSON output must be compatible (i.e. key names must be the same as before).
logfmt (AKA "text"?) output must be compatible. It's the one used in Docker by default, colorless plain text.
syslog - not so important
console - nobody cares, so if it's not compatible - fine. However, Petros checks out with key customers about it right now and might let you know if anyone needs the compatibility. Although, it's almost an unbelievable case.
Order of keys in JSON and logfmt, as well as presence of additional keys is also irrelevant. I.e. level=debug logger=foo or logger=foo level=debug doesn't matter for our users.
PS: log level names in json and logfmt must be the same as before.

**Comment by dprokop** [comment]
@ying-jeanne can you add adequate labels, please?
