### ISSUE TITLE
Prometheus: could not query exemplars for non histogram metrics

### ISSUE THREAD

**Issue by JokerQueue** [grafana/grafana#42566]
**What happened**:
When querying metrics like "increase(provider_failure_count_total{}[1m])" , I can't query with exemplars.

**What you expected to happen**:
I can query with exemplars for any metric.

**How to reproduce it (as minimally and precisely as possible)**:
I found the limit code in "public/app/plugins/datasource/prometheus/datasource.ts" relate to PR #39531 ，but I don't understand the reason "exemplars are available only for histogram metrics", as I known prometheus doesn't has this limit and I'm storing and querying exemplars with this metric "provider_failure_count_total" in prometheus now.

**Environment**:
- Grafana version: 8.3.0-beta2
- Data source type & version: Prometheus 2.31.1

**Comment by aocenas** [comment]
@ivanahuckova  do you remember why the check for histogram was added https://github.com/grafana/grafana/pull/39531/files#diff-a4c7450a7fbfcf23283bf451fef14397c9b007c8fdba59ffe497fb55b2813e6bR289 ? Don't see it in the previous code but not sure if such check was there before the backend migration.

**Comment by ivanahuckova** [comment]
@JokerQueue I am creating fix for this: https://github.com/grafana/grafana/compare/ivana/exemplars-fix?expand=1. You are correct, there shouldn't be this check. We should only check if we've already created an exemplar query for the same metric. If so, in that case don't run duplicated exemplars queries. This is a logic that should be in `shouldRunExemplarQuery` : https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.ts#L252-L264
