### ISSUE TITLE
API to allow lookup of datasource id by name

### ISSUE THREAD

**Issue by phalenor** [grafana/grafana#4258]
Please consider adding an API call to allow looking up a datasource ID by name. This would allow scripted dashboards that perform proxied queries before returning the dashboard to only know the name of the datasource, and not have to program the numeric id, which may change.

Right now the only way to get it is to query /api/datasources, which requires the caller to be an org admin. This breaks those scripted dashboards when the user is only a Viewer, etc.

**Comment by utkarshcmu** [comment]
@phalenor Resolved this issue by #4279 and for docs you may check #4290, as both the PR are merged into master now.

**Comment by phalenor** [comment]
This isn't quite what I was thinking about. I just wanted an api call to get the ID, that way it can be scoped to reqSignedIn. That way it can be accessed via scripted dashboard by anyone that's signed in.

**Comment by bergquist** [comment]
Closed by #4258
