### ISSUE TITLE
Bug: wrong coloring of percentages

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4259]
Steps:
* Create single stat for a value 0.68
* Use unit `percent 0.0-1.0`
* Set coloring to `0.7,0.9` (expected `70,90`, but understandable choice)

Expected:
* `68.0%` in red

Observed:
* `68.0%` in orage

Analysis:
It seems first the value gets rounded to 0.7 (with auto decimals), then compared to the threshold, and then converted to the new unit.

Test dashboard:
https://gist.github.com/dfbc448ce43dfcfa4f02

![screenshot from 2016-03-04 18-46-24](https://cloud.githubusercontent.com/assets/3432/13543477/9256ab5e-e239-11e5-91c3-b4f91e4ae758.png)

**Comment by bergquist** [comment]
Seems like I introduced this behavior with https://github.com/grafana/grafana/commit/c30c12d36950fc9a21b0f5a8b5423454bab33721#diff-e593190b57ddfe3f482e43e7b8248993 Trying to remember why :)
