### ISSUE TITLE
PanelQueryRunner Error Error: invalid metric editor mode - on all CloudWatch dashboards in Grafana 8.3.0

### ISSUE THREAD

**Issue by SamuraiPrinciple** [grafana/grafana#42598]
**What happened**:

After upgrading to Grafana 8.3.0 none of the CloudWatch dashboards show anything. In dev tools console, the following JavaScript error appears:

PanelQueryRunner.ts:258 PanelQueryRunner Error Error: invalid metric editor mode
    at filterMetricQuery (datasource.ts:259)
    at Array.filter (<anonymous>)
    at Fe.handleMetricQueries (datasource.ts:266)
    at Fe.query (datasource.ts:137)
    at runRequest.ts:180
    at j (runRequest.ts:131)
    at v.run (PanelQueryRunner.ts:256)

**What you expected to happen**:

Dashboards to be rendered.

**How to reproduce it (as minimally and precisely as possible)**:

Attached is the dashboard JSON causing that JavaScript error/nothing to be rendered 

[1.json.zip](https://github.com/grafana/grafana/files/7635506/1.json.zip)

**Anything else we need to know?**:

We provision our dashboards from file system.

If we get into edit mode and "refresh" the dashboard it is then rendered correctly. Here is the JSON diff:

As a general question, is this behaviour expected - that filesystem-provisioned dashboards created with older grafana versions aren't compatible with newer Grafana versions? If that's by-design, than feel free to close this issue (but it'd be good to have that documented somewhere).

<img width="2672" alt="Screenshot 2021-12-01 at 16 16 59" src="https://user-images.githubusercontent.com/621249/144271418-c5ce09b9-3283-4151-906e-e36a38565ab2.png">

**Environment**:
- Grafana version: 8.3.0
- Data source type & version: CloudWatch
- OS Grafana is installed on: Centos 7
- User OS & Browser: MacOS, Chrome
- Grafana plugins: -
- Others: N/A

**Comment by sunker** [comment]
Thanks for reporting this @SamuraiPrinciple. From what version did you upgrade?

**Comment by SamuraiPrinciple** [comment]
Upgraded from 8.2.5

**Comment by sunker** [comment]
Okay, thanks. 

No definitely not expected. It looks like all necessary migrations are not being executed. This is only a problem for users upgrading from 8.2.4 or 8.2.5 to 8.3.0. 

I'll try to come up with a fix asap. In the meantime, if you don't wish to downgrade you can manually edit the dashboard json and set the schemaVersion prop to 31. Then migrations should be executed and it should work. 

Thanks again for reporting this so quickly @SamuraiPrinciple!

**Comment by SamuraiPrinciple** [comment]
Sweet, thank you for the quick update/confirmation and a workaround...

Take care,
damjan

**Comment by dindurthy** [comment]
We encountered this upgrading from 8.2.3 to 8.3.1 and the workaround to "edit the dashboard json and set the schemaVersion prop to 31" doesn't work. Any recommendations?

**Comment by sunker** [comment]
> We encountered this upgrading from 8.2.3 to 8.3.1 and the workaround to "edit the dashboard json and set the schemaVersion prop to 31" doesn't work. Any recommendations?

What happens when you change the schemaVersion to 31? Still same error in the js console? 

The fix for this will be released in a 8.3.3, which is due sometime early this week.

**Comment by arnauddrain** [comment]
Hello @sunker, we're experiencing the same issue in a Grafana Cloud instance using version v8.3.3.
When changing the `schemaVersion` to 31, it is immediately reverted to 34 and the issue remains. Do you have another suggestion? Thanks for the support!

**Comment by sunker** [comment]
@arnauddrain for the necessary migrations to take place, the CloudWatch query model needs to be in a valid state. For it to be considered valid, the query needs to have the following props in the dashboard json model. 
```json
 {
          "period": "",
          "dimensions": {},
          "metricName": "",
          "namespace": "",
          "region": "",
}
```

We have had another user report that they're still seeing this error after upgrading to 8.3.3, and it turned out to be because the _period_ field was missing in the dashboard json. Can you check if that's the case here too? See [this](https://grafana.com/docs/grafana/latest/dashboards/json-model/#dashboard-json-model) page for instructions on how to open dashboard json.

**Comment by arnauddrain** [comment]
Thank you @sunker, the missing `period` was the issue! And I realized that it was not specific to CloudWatch, we also had this with some other panels.

**Comment by sunker** [comment]
Okay - good to hear! I believe a workaround is to add it manually or just enter the panel edit mode for the broken panel. From the next release, 8.3.4, the period prop won't be mandatory for the migration to run anymore.
