### ISSUE TITLE
Github authentication unable to verify organization membership

### ISSUE THREAD

**Issue by nielsams** [grafana/grafana#42592]
**What happened**:
I enabled Github authentication, with the goal of allowing only users that are members of my organization to log in to Grafana. 
I used the following settings in the [auth.github] section:
```
[auth.github]
enabled = true
allow_sign_up = true
client_id = [gh clientid]
client_secret = [supersecret]
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
allowed_organizations = azure
```

When I comment out the last line and allow any Github user to authenticate, it works fine. When I specify the organization, login fails:
```
t=2021-12-01T13:33:45+0000 lvl=eror msg="login.OAuthLogin(get info from github)" logger=context userId=0 orgId=0 uname= error="user not a member of one of the required organizations"
```

Presumably this is because when Grafana queries Github for the user's orgs, an empty response is returned:
```
t=2021-12-01T13:33:45+0000 lvl=dbug msg="HTTP GET" logger=oauth.github url=https://api.github.com/user/orgs status="200 OK" response_body=[]
```

This empty response can be reproduced in postman when using the same access token. 

**What you expected to happen**:
I expect the user to login successfully when they are a member of the required organizatrion.

**How to reproduce it (as minimally and precisely as possible)**:
- Create Github application and copy down clientid and secret
- Set the above as config for your Github auth, including a value for allowed_organizations
- Attempt to log in.

**Anything else we need to know?**:
I suspect this is caused by calling a deprecated Github endpoint for the user's organizations. In this case the URL being called is _api.github.com/user/orgs_.

When looking up the initial user, the following is returned:
```
{\"login\":\"nielsams\",
\"id\":xxxxxxx,
\"node_id\":\"xxxxxx\",
\"avatar_url\":\"https://avatars.githubusercontent.com/u/18422663?v=4\",
\"gravatar_id\":\"\",
\"url\":\"https://api.github.com/users/nielsams\",
\"html_url\":\"https://github.com/nielsams\",
\"followers_url\":\"https://api.github.com/users/nielsams/followers\",
\"following_url\":\"https://api.github.com/users/nielsams/following{/other_user}\",
\"gists_url\":\"https://api.github.com/users/nielsams/gists{/gist_id}\",
\"starred_url\":\"https://api.github.com/users/nielsams/starred{/owner}{/repo}\",
\"subscriptions_url\":\"https://api.github.com/users/nielsams/subscriptions\",
**\"organizations_url\":\"https://api.github.com/users/nielsams/orgs\",**
\"repos_url\":\"https://api.github.com/users/nielsams/repos\",
\"events_url\":\"https://api.github.com/users/nielsams/events{/privacy}\",
\"received_events_url\":\"https://api.github.com/users/nielsams/received_events\",
\"type\":\"User\",
\"site_admin\":false,
\"name\":\"Niels Buit\",
\"company\":\"Microsoft\",
\"blog\":\"\",
\"location\":\"Amsterdam\",
\"email\":\"xxxxxx\",
\"hireable\":null,
\"bio\":\"xxxxx\",
\"twitter_username\":null,
\"public_repos\":7,
\"public_gists\":7,
\"followers\":12,
\"following\":19,
\"created_at\":\"2016-04-12T14:24:29Z\",
\"updated_at\":\"2021-11-08T14:09:10Z\"}"
```

Perhaps the endpoint named in _organizations_url_ should be called instead of the other one. 

**Environment**: Docker
- Grafana version: v8.3.0 (914fcedb72)
- Data source type & version: n/a
- OS Grafana is installed on: 
- User OS & Browser: Windows 11 / Edge
- Grafana plugins:
- Others:

**Comment by dprokop** [comment]
Interesting, just created a Github OAuth app and it seems to work when I specify our organization as the allowed one. I'm passing this one to @grafana/backend-platform for further ivestigation.

**Comment by wbrowne** [comment]
I also haven't been able to reproduce @nielsams unfortunately. Can you confirm you're definitely configuring an GitHub **OAuth** app?

Have double checked the API docs and confirmed that we're using the [appropriate API](https://docs.github.com/en/rest/reference/orgs#list-organizations-for-the-authenticated-user)

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.

**Comment by kimble** [comment]
I have the same problem, just with teams

    logger=oauth.github t=2022-05-22T13:23:16.6+0000 lvl=dbug msg="HTTP GET" url="https://api.github.com/user/teams?per_page=100" status="200 OK" response_body=[]

    logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-05-22T13:41:24.07+0000 lvl=eror msg="login.OAuthLogin(get info from github)" error="user not a member of one of the required teams"

**Comment by brlbil** [comment]
I had the exact same problem. Initially, I created the OAuth application under my personal account. This was failing. The issue was resolved when I created an OAuth application under the organization.

**Comment by Xat59** [comment]
I had the same issue and I solved it by creating a OAuth app in the organization instead of creating it in my own user.
The Grafana documentation does not specify to do so : https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/github/

Thanks @brlbil

**Comment by wzur-r3** [comment]
Hello,

I found this issue while searching for some explanation of this issue.

Initially I used a private Github App and it helped when I switched it to a public one.
