### ISSUE TITLE
Docs: broken Candlestick viz image

### ISSUE THREAD

**Issue by leeoniya** [grafana/grafana#42617]
https://grafana.com/docs/grafana/latest/visualizations/candlestick/

cc @pkolyvas

**Comment by pkolyvas** [comment]
Thanks for catching that @leeoniya; a merge conflict in a website PR meant the first fix wasn't auto-merged. 

https://github.com/grafana/website/pull/7020

Fixed. May require another browser/incognito session to confirm if you've already looked at the page.
