### ISSUE TITLE
E2E Tests: Store Cypress recordings to GCS buckets

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#42627]
**What happened**:

We have a persistent e2e test failure we cannot reproduce locally, and we also don't have access to the recording produced by Cypress. What we really need is a place to store all recordings so people can easily debug and reproduce the issue on CI (since Cypress run is a really heavy operation anyway.

**What you expected to happen**:

We should have a place to store our e2e test artifacts, possibly with a URL generated after each run, so it's easier for people to access.

**Comment by marefr** [comment]
Is this done? Open but in done status of the project

**Comment by tolzhabayev** [comment]
@marefr not yet, waiting for the PR approval to merge
