### ISSUE TITLE
Graphite: Subqueries are not fully interpolated

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#42623]
**What happened**:

Created a dashboard for `gdev-graphite` with following queries:
* `stats.response.500`
* `stats.response.200`
* `scale(divideSeriesLists(diffSeriesLists(#B, #A), #B), 100)`

<img width="1128" alt="Screen Shot 2021-12-02 at 09 58 49" src="https://user-images.githubusercontent.com/745532/144390337-455926f2-fd1e-41fb-ba65-ddd61399519a.png">

The query is rendered fine with all subqueries interpolated:

<img width="1321" alt="Screen Shot 2021-12-02 at 09 59 04" src="https://user-images.githubusercontent.com/745532/144390421-0a8da534-eb33-4f19-a6d4-47fec6c2f63d.png">

But after creating an alert:

<img width="894" alt="Screen Shot 2021-12-02 at 09 59 13" src="https://user-images.githubusercontent.com/745532/144390451-923c926b-951d-4179-a1f4-a9abe0f096ab.png">

The second reference to `#B` is not interpolated:

<img width="746" alt="Screen Shot 2021-12-02 at 09 59 27" src="https://user-images.githubusercontent.com/745532/144390512-8c0a9ce8-9811-458a-a824-527a9a59abf4.png">

**What you expected to happen**:

All subqueries should be interpolated.

**How to reproduce it (as minimally and precisely as possible)**:

Use `gdev-graphite` and create any 2 queries. Then create additional query where one the former is referenced twice.

**Anything else we need to know?**:

**Environment**:
- Grafana version: scale(divideSeriesLists(diffSeriesLists(#B, #A), #B), 100)
- Data source type & version: Graphite 1.1
- OS Grafana is installed on: MacOS
- User OS & Browser: Chrome
- Grafana plugins: N/A
- Others: Happening at least since 7.5.3 https://community.grafana.com/t/alert-with-graphite-query-using-two-metrics-scale-divideserieslists-diffserieslists/56685

**Comment by JohnnyQQQQ** [comment]
@ifrost which Version were you using when this happened? This was fixed as part of https://github.com/grafana/grafana/pull/42493

**Comment by yuri-tceretian** [comment]
I think this is a bug that is relatively fast to fix. Although in a new Grafana 8 Alerting we do not support such queries, the migrated alert would use the interpolated query and therefore will fail to evaluate. The fix needs to be done on UI side where the interpolation is done.
@gillesdemey can you check please?

**Comment by ifrost** [comment]
Thanks @yuri-tceretian. You're right, `targetFull` should be fully interpolated in the frontend when the query is saved. I'll move the issue out of Alerting backlog.

**Comment by gtk-grafana** [comment]
@grafana/observability-metrics Will do some additional research into this task and update priority after reproducing in currently supported versions of Grafana.

**Comment by obetomuniz** [comment]
The problem still is happening. It's not only related to Alerting, but also Expressions. 

I'm starting to work on a proposal to fix the problem.
