### ISSUE TITLE
Alert list plugin should use the folder uid instead of id as filter

### ISSUE THREAD

**Issue by fsperling** [grafana/grafana#42625]
**What happened**:
Exported and imported dashboards with alerts to a new instance.
We have a dashboard that is in a folder X which uses the alert list plugin to list alerts.
After the migration the panels are empty and the filter has the folder all selected instead of X.
In the json we can see the filter references the old folder ID. However after importing the folder has a different ID.

**What you expected to happen**:
The filter should make use of uids that stay the same when you move dashboards across Grafana instances.

**Environment**:
- Grafana version: 8.2.5

**Comment by konrad147** [comment]
Closing the issue, legacy alerting is no longer actively maintained
