### ISSUE TITLE
Docker: grafana/grafana:latest arm architecture is missing

### ISSUE THREAD

**Issue by amuttsch** [grafana/grafana#42632]
**What happened**:

The latest docker `grafana/grafana:latest` image was not published for arm architectures.

**What you expected to happen**:

The latest docker `grafana/grafana:latest` image should be published for arm architectures :-)

**How to reproduce it (as minimally and precisely as possible)**:

See https://hub.docker.com/r/grafana/grafana/tags?page=1&name=latest

**Anything else we need to know?**:

I use watchtower to automatically update my docker images once there is a new version. The missing arm architecture caused docker to pull the amd64 version which does not work on arm / raspberry pi.

**Environment**:
- Grafana version: latest
- OS Grafana is installed on: Raspberry Pi 4 Rasbian x64

**Comment by malcolmholmes** [comment]
@amuttsch thank you very much for reporting this. This should now be resolved. If not, please feel free to reopen this issue. Thanks again.

**Comment by amuttsch** [comment]
Looks good, thanks for the fast update @malcolmholmes :heart:

**Comment by S474N** [comment]
Why?

:main 8.4.0
:latest 8.3.0

**Comment by malcolmholmes** [comment]
> Why?
> 
> :main 8.4.0 
> :latest 8.3.0

Because once 8.3.0 was released, the main branch moves on to being where we develop the next version, i.e. 8.4.0, which, obviously, hasn't been released yet. However, we do make it available for those that want to closely track development.
