### ISSUE TITLE
Data links from panels in repeated rows don't populate the row variable correctly

### ISSUE THREAD

**Issue by jfoy** [grafana/grafana#42694]
**What you expected to happen**:

We have a fairly common drill-down use case: a summary dashboard has a multi-valued template variable `cluster` and a single row of panels, where that row repeats for each value of the variable. A separate details dashboard accepts a single value for `cluster` and has many detailed panels based on that template variable.

On the panels of the summary dashboard, we'd like to embed a link to the details dashboard:

```https://grafana/d/some_id/details_dash?${cluster:queryparam}```

That way, a user inspecting the summary dashboard for all clusters could click through a particular cluster's summary panel directly to the details dashboard for that cluster. For an instance of the repeated row where `cluster` has value `my-cluster-1`, we'd expect the panel link on that row to be populated like:

```https://grafana/d/some_id/details_dash?var-cluster=my-cluster-1```

**What happened**:

- When we select `cluster: All` on the summary dash, all values for `cluster` are selected and we get a row for each value, but the panel link is populated as `https://grafana/d/some_id/details_dash?var-cluster=All`.
- When we select multiple individual values for `cluster` on the summary dash, we get the correct behavior of a row for each value, but the panel link is populated as `https://grafana/d/some_id/details_dash?var-cluster=my-cluster-1&var-cluster=my-cluster-2&var-cluster=my-cluster-3&...`

**Anything else we need to know?**:

It looks like this may be a recurrence of a previous bug:

#22286 and #25881 fixed in #26147 and flagged for cherry-pick in #26238
#29942 fixed in #29757
#32904 incorrectly flagged as a help question
https://community.grafana.com/t/current-value-of-a-repeat-variable-in-a-repeating-panel/10080
https://community.grafana.com/t/getting-single-variable-from-repeated-row/12920
https://community.grafana.com/t/templated-panels-and-linking-to-dashboard/14197
https://community.grafana.com/t/link-on-table-plugin-within-repeatable-row/37343

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a "details" dashboard that takes a `cluster` template variable, only allowing one value to be selected. The details dash doesn't need any panels. Copy its URL.
2. Create a "summary" dashboard with a single multi-value variable also named `cluster` (e.g. different Prometheus data sources). Check "Multi-Value" and "Include All option" on the dashboard settings Variable screen.
3. Add a row with a single panel to the "summary" dash. Under the panel settings, add a panel link pointing to the "details" dash with `?${cluster:queryparam}` on the end.
4. Under row settings choose "Repeat for: `cluster`".
5. Select `cluster` All, click the panel link, and see that it passes `?var-cluster=All`.
6. Select two or more explicit values for `cluster`, click the panel link, and see that it passes all values.

**Environment**:
- Grafana version: v8.2.5 (b57a137acd)
- Data source type & version: Prometheus 2.28.1
- OS Grafana is installed on: Alpine Linux
- User OS & Browser: MacOS 11.6.1, Firefox 95.0b12
- Grafana plugins: n/a, core only

**Comment by dprokop** [comment]
Can confirm this behavior. The dashboard to reproduce:

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 631,
  "iteration": 1638530089068,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "displayName": "var value: ${query0}",
          "links": [
            {
              "title": "Link for ${query0}",
              "url": "http://localhost:3000?${query0:queryparam}"
            }
          ],
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 8,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "colorMode": "value",
        "graphMode": "area",
        "justifyMode": "auto",
        "orientation": "auto",
        "reduceOptions": {
          "calcs": [
            "lastNotNull"
          ],
          "fields": "",
          "values": false
        },
        "textMode": "auto"
      },
      "pluginVersion": "8.4.0-pre",
      "repeat": "query0",
      "repeatDirection": "h",
      "targets": [
        {
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1"
        }
      ],
      "title": "Panel Title",
      "type": "stat"
    }
  ],
  "refresh": "",
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": true,
          "text": [
            "a",
            "b"
          ],
          "value": [
            "a",
            "b"
          ]
        },
        "hide": 0,
        "includeAll": true,
        "multi": true,
        "name": "query0",
        "options": [
          {
            "selected": false,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": true,
            "text": "a",
            "value": "a"
          },
          {
            "selected": true,
            "text": "b",
            "value": "b"
          },
          {
            "selected": false,
            "text": "c",
            "value": "c"
          }
        ],
        "query": "a,b,c",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "Data links from panels in repeated rows don't populate the row variable correctly #42694",
  "uid": "XwCqsihnk",
  "version": 7,
  "weekStart": ""
}

**Comment by dprokop** [comment]
It seems like an issue with `:queryparam` formatting which does not take into account the repeating and the actual context of the variable in which it's being used.

When using the variable in the data link without formatting applied, the value is resolved correctly (both for multiple individual values selected ass well as for `All` selected)

**Comment by hugohaggmark** [comment]
> It seems like an issue with `:queryparam` formatting which does not take into account the repeating and the actual context of the variable in which it's being used.
> 
> When using the variable in the data link without formatting applied, the value is resolved correctly (both for multiple individual values selected ass well as for `All` selected)

Thanks @dprokop, what do you mean by `When using the variable in the data link without formatting applied`?

**Comment by dprokop** [comment]
> Thanks @dprokop, what do you mean by `When using the variable in the data link without formatting applied`?

@hugohaggmark I mean `${variable}` instead of `${variable:queryparam}`.

**Comment by hugohaggmark** [comment]
@dprokop thank you 👍

**Comment by jfoy** [comment]
> When using the variable in the data link without formatting applied, the value is resolved correctly (both for multiple individual values selected as well as for All selected)

Fantastic, this gives us a workaround for the immediate use case. Thank you!
