### ISSUE TITLE
Functions as templating variables?

### ISSUE THREAD

**Issue by strizhechenko** [grafana/grafana#4269]
I want to use template variable "$func" = min + max + last, with multiple value option / graph repeat, but can use it only with manual query editing. What if add variables section in function select menu? It will be very usable!

**Comment by torkelo** [comment]
you can use it in the query editor 
![image](https://cloud.githubusercontent.com/assets/10999/13562963/edd9016a-e43d-11e5-9ec5-22de00e00c17.png)
