### ISSUE TITLE
Accessibility: Fix Cloudwatch config page fastpass issues

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#42706]

**Comment by fridgepoet** [comment]
The aria-labels I intended to add were already present in the new frontend repo: 
https://github.com/grafana/grafana-aws-sdk-react/blob/main/src/ConnectionConfig.tsx#L75 https://github.com/grafana/grafana-aws-sdk-react/blob/main/src/ConnectionConfig.tsx#L194
