### ISSUE TITLE
Github styled heatmap

### ISSUE THREAD

**Issue by nanoz** [grafana/grafana#4271]
Hi !

One of our main goal in using Grafana is to get a quick overview of our platform's health, in real time but also for a given time window.

For Grafana to do an even better job at giving us this quick overview, It seems to me that a GitHub styled heatmap would be a nice addition on top of our dashboards. We would then easily see when and how much of a given value where heated, at a minutes, hours or days range.

The idea was inspired from this awesome new product : http://trackburnr.com/

**Comment by linkslice** [comment]
This would be awesome to use in conjunction with annotations/graphite events. For example puppet/chef deploys/outages push an event into graphite and then something like cal-heatmap to map those using grafana annotations

**Comment by mtanda** [comment]
@bergquist Before starting to implement this, please refer this comment.
https://github.com/grafana/grafana/issues/3164#issuecomment-217826957

Elasticsearch histogram aggregation could be datasource of heatmap panel.
I think Grafana should define common interface for histogram/heatmap data.

**Comment by woohoou** [comment]
any news from this feature?

**Comment by nanoz** [comment]
It looks like this PR convers it https://github.com/grafana/grafana/pull/7934
