### ISSUE TITLE
Question: Recently viewed dashboards

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4272]
I logged in as user1 and viewed any 2 dashboards and I can see them in user1's recently viewed dashboard list. I logged out and logged in as user2 and see the same 2 dashboards in user2's recently viewed dashboard list.

Is this ok or this issue needs to be addressed?

**Comment by bergquist** [comment]
Good catch! I don't think this is a big issue however. 
They will only see dashboard they both have access to.

In the future I would like to have this kind of usage history in the backend. But while it's kept in the browsers local storage its accessible to anyone who can access the browser anyway.

**Comment by utkarshcmu** [comment]
👍🏼
