### ISSUE TITLE
Grafana 8.3 shows loki fake file error

### ISSUE THREAD

**Issue by hakro** [grafana/grafana#42735]
After migrating from Grafana 8.2.5 to 8.3, and enabling unified alerting, this error showed up in the Alerts page : 

`Failed to load rules config from Loki Global: unable to read rule dir /loki/rules/fake: open /loki/rules/fake: no such file or directory`

It show up for every Loki datasource that we have on that org : 

![2021-12-03_13-56](https://user-images.githubusercontent.com/3624853/144607311-8295698f-0856-4205-93c1-84c438f07a99.png)

**How to reproduce it (as minimally and precisely as possible)**:
- Upgrade Grafana 8.2.5 with a loki datasource to 8.3 
- Enable Unified Alerting
- Visit the Alert Rules page

**Anything else we need to know?**:
Loki works fine on the dashboards and Explore

**Environment**:
- Grafana version: 8.3
- Data source type & version: Loki 2.4.1
- OS Grafana is installed on: Ubuntu / Docker
- User OS & Browser: Firefox
- Grafana plugins: None
- Others:

**Comment by ashharrison90** [comment]
not sure whether this should go to alerting or o11y... given it seems to be specific to the loki datasource, o11y can have the first look 😄

**Comment by kathy-lee** [comment]
I have similar problem here:

```
Errors loading rules
Failed to load rules config from Loki: unable to read rule dir /tmp/loki/rules/fake: open /tmp/loki/rules/fake: no such file or directory
```

I tried inside the loki container to create directory '/tmp/loki/rules/fake' and put rule yaml file there, it didn't pop out this error anymore and can load properly the rules in this file. I thought at first it should work when I set the "ruler.rule_path" to point to this file, but it didn't. Also feel confused about difference between "ruler.rule_path" and "directory" in below:

```
  ruler:
  storage:
    type: local
    local:
      directory: /tmp/rules
  rule_path: /tmp/scratch
  alertmanager_url: http://localhost
  ring:
    kvstore:
      store: inmemory
  enable_api: true
```

In loki config reference shows:

```
# File path to store temporary rule files.
# CLI flag: -ruler.rule-path
[rule_path: <filename> | default = "/rules"]
```

```
  storage:
  # Method to use for backend rule storage (azure, gcs, s3, swift, local).
  # CLI flag: -ruler.storage.type
  [type: <string> ]
  ...
  # Configures backend rule storage for a local filesystem directory.
  [local: <local_storage_config>]
```

Can someone help to explain a little bit on this,  is this a bug or I configured wrongly?

**Comment by CEMario** [comment]
I made the error go away by creating `/tmp/loki/rules/fake` which my particular instance was complaining about, which presumably enables the Loki ruler. That's the code I used to configure the Loki values file installed with Helm:
```
extraVolumes:
  - name: fake
    emptyDir: {}
extraVolumeMounts:
  - name: fake
    mountPath: /tmp/loki/rules/fake
```
I'll see where I place the actual rules directory - the two places you can define it doesn't make it clear - but it seems like the fake dir is just a toggle for enabling the feature... Would have been nice if this hacky behaviour was documented with the new release.

**Comment by hakro** [comment]
Thx. It might be a work around but I think the issue is rather on Grafana itself.
This did not show up for me before 8.3 and before enabling unified alerts.
My Loki installations have not been changed during the Grafana upgrade.

**Comment by gabor** [comment]
i think this is something @grafana/alerting-squad should look at.

**Comment by gillesdemey** [comment]
This seems related to https://github.com/grafana/loki/issues/3953

**Comment by blondviper** [comment]
Try this.
In docker compose for loki put this:
`volumes:
- ./config/loki-rules.yaml:/tmp/rules/fake/rules.yaml/`

Local-config.yaml for loki:
`ruler:
  alertmanager_url: http://localhost:9093
  enable_alertmanager_v2: true
  enable_api: true
  enable_sharding: true
  ring:
    kvstore:
      store: inmemory
  rule_path: /loki/rules
  storage:
    type: local
    local:
      directory: /tmp/rules/fake`
In directory, you are specifying path to rules.yaml

**Comment by pillaris** [comment]
I think the issue here is your instance of Grafana Loki is running in single tenant mode, is that correct? 

I am running Grafana Loki in single tenant mode and had no issues in Grafan-Loki v8.2 with the following configuration :

```
ruler:
   alertmanager_url: http://localhost:9093
   storage:
      type: local
      local:
         directory: /loki/data/ruler
```

In v8.3, Grafana is showing this error "unable to read rule dir /loki/data/ruler/fake: open /loki/data/ruler/fake: no such file or directory".

I noticed this "section" in documentation: https://grafana.com/docs/loki/latest/rules/#interacting-with-the-ruler

So, without changing my configuration and with my grafana loki running, I manually created folder "fake" in /loki/data/ruler and the error is no longer showing in Grafana. I assume in single tenent mode the ruler.storage.local.directory must point to the folder "fake", i.e. /path/to/rules/fake, and rules.yaml should be placed inside "fake".

**Comment by blondviper** [comment]
For me it's working now, and I substituted localhost with alertmanager. Alerts are firing and no more Grafana issues.

**Comment by hakro** [comment]
After upgrading to 8.3.4, it now shows errors related to our Promethii instances as well, not just Loki
No configuration changes has been made on either Prom nor Loki before or after the Grafana upgrade

![2022-01-19_18-52](https://user-images.githubusercontent.com/3624853/150186816-6854f43c-c7bb-4d37-abd2-7e2df2e5d203.png)

The datasources are working fine, and we're able to query them in the dashboards and in Explore.
The errors only show on the Alerts page.

**Comment by mstavrev** [comment]
We are getting the same error as @harko reported - exactly after upgrade of Grafana to 8.3.4. 

The browser's console show every 20 seconds these errors when requesting the relevant resources:

> /grafana/api/prometheus/2/api/v1/rules - HTTP 404
> /grafana/api/ruler/2/api/v1/rules - HTTP 404
> /grafana/api/ruler/1/api/v1/rules - HTTP 500

For every invocation of the above three, here is what Grafana is logging:

> t=2022-01-22T08:49:00+0000 lvl=eror msg="API error" logger=context userId=1 orgId=1 uname=admin error="404 page not found\n" remote_addr=XXX
> t=2022-01-22T08:49:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/prometheus/2/api/v1/rules status=404 remote_addr=XXX time_ms=4 size=23 referer=https://XXX/grafana/alerting/list
> t=2022-01-22T08:49:00+0000 lvl=eror msg="API error" logger=context userId=1 orgId=1 uname=admin error="404 page not found\n" remote_addr=XXX
> t=2022-01-22T08:49:00+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/ruler/2/api/v1/rules status=404 remote_addr=XXX time_ms=1 size=23 referer=https://XXX/grafana/alerting/list
> t=2022-01-22T08:49:00+0000 lvl=eror msg="API error" logger=context userId=1 orgId=1 uname=admin error="unexpected content type from upstream. expected YAML, got text/html; charset=utf-8" remote_addr=XXX
> t=2022-01-22T08:49:00+0000 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/ruler/1/api/v1/rules status=500 remote_addr=XXX time_ms=2 size=23 referer=https://XXX/grafana/alerting/list

Any work-around or fix?

**Comment by kathy-lee** [comment]
I met the same issue from loading alert rules from Prometheus, when migrated to 8.3.4.
<img width="589" alt="Screenshot 2022-01-24 at 08 23 12" src="https://user-images.githubusercontent.com/31970955/150739038-25001db5-6495-4fcd-9e21-f920ff311e4a.png">

**Comment by glouis** [comment]
I found an explanation for the `fake` work presence.

As [Ruler storage](https://grafana.com/docs/loki/latest/rules/#ruler-storage), the expected path contains a `tenant id`.

As the second note in [Interacting with the Ruler](https://grafana.com/docs/loki/latest/rules/#interacting-with-the-ruler), the `tenant id` for Loki instance running in single tenant mode is `fake`.

So with the following in your configuration:
```
  storage:
    type: local
    local:
      directory: /usr/local/loki/rules
```
The rule files have to be in the folder `/usr/local/loki/rules/fake`.

**Comment by hakro** [comment]
Still happening with the newest version : 
- Grafana 8.4.6
- Loki 2.5

**Comment by gjemp** [comment]
the error disappeared when I added fake named folder into rules   directory

**Comment by JohnnyQQQQ** [comment]
This is a loki configuration problem. Some users posted solutions to the problem in the issue.

**Comment by claclin** [comment]
Hi, I get the following error:

**Failed to load the data source configuration for Loki: Unable to fetch alert rules. Is the Loki data source properly configured?**

Any idea please?
