### ISSUE TITLE
[BUG] Improve error message for missing permissions to aws credentials on disk

### ISSUE THREAD

**Issue by OriolGasco** [grafana/grafana#4273]
Hello, I have a problem when I try to connect Grafana with CloudWatch.
The logs of Grafana in /var/log/grafana/grafana.log are this:
2016/03/07 12:45:03 [cloudwatch.go:133 handleListMetrics()] [E] Unable to call AWS API: NoCredentialProviders: no valid providers in chain
2016/03/07 12:45:03 [I] Completed 127.0.0.1 admin "POST /api/datasources/proxy/8 HTTP/1.1" 500 Internal Server Error 36 bytes in 12002199us

The credentials are OK, because I try #aws cloudwatch list-metrics and works good.
by other hand I try to solve it with AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY environment variables, but have the same problem.

Someone can help me.
Thanks in advance

**Comment by bergquist** [comment]
Grafana requires you to have the credentials in a file. By default its ~/.aws/credentials 
The format can be found at http://docs.aws.amazon.com/cli/latest/userguide/cli-chap-getting-started.html

**Comment by OriolGasco** [comment]
Yes, I already follow this tutorial, so I have the directory ~/.aws/credentials with the credentials.
The credentials are OK, because I test it with the AWS_CLI with the command:
#aws cloudwatch list-metrics
And it is good because if I move the credentials file the command is not work, so I have the credentials file done and working by the AWS_CLI, but when I try to connect Grafana with de CloudWatch Data source I get the same error.
![grafana_error](https://cloud.githubusercontent.com/assets/12253495/13571227/d1389922-e473-11e5-9d55-9df2719bf244.png)

**Comment by JeanFred** [comment]
I’m experiencing the same thing (I have yet to test the CLI to make sure)

**Comment by OriolGasco** [comment]
I have solved it, all that have to do is to copy the file credentials, in the home of the grafana user:
/usr/share/grafana/.aws/credentials and give all permisions to this file.

#cp -r ~/.aws /usr/share/grafana/
#chmod 777 /usr/share/grafana/.aws/credentials

It works for me

**Comment by JeanFred** [comment]
Good catch @OriolGasco −  the trick is indeed to put it in `/usr/share/grafana/`.
For me 0644 was enough permission.

**Comment by sreeram-boyapati** [comment]
The bug is reproducible. I am using grafana 3.0 Beta. Please reopen this issue. Do the above suggested has worked.

**Comment by OriolGasco** [comment]
Did you put the credentials file in the Grafana user home's directory?
Check the Grafana's home directory with the next command:
# cat /etc/passwd |grep grafana | cut -d':' -f6
And then copy the credentials file in this directoy

**Comment by iGaskin** [comment]
I'm still getting the above error despite the credentials file being in the appropriate dir with correct permissions.  Any suggestions?  Does the aws cli need to be installed?  I was under the impression that grafana used its own go-aws api.

`-rw-r--r-- 1 root root 116 May 10 20:24 /usr/share/grafana/.aws/credentials`

**Comment by hailthemelody** [comment]
@iGaskin , how did you resolve it while using internal IP? Did you bind it to a reserved external IP or maybe NAT? I'm having the same issue.

**Comment by andremccarv** [comment]
@OriolGasco Nice!!! Finally working for me as well!!

**Comment by tario-yang** [comment]
Met same issue at Grafana 3.1.0. The error information is,

> EROR[07-21|14:22:23] Unable to call AWS API                   logger=context userId=1 orgId=1 uname=admin error="NoCredentialProviders: no valid providers in chain"

I find the root cause of this in my VM is `.aws/credentials`. It needs to make sure its content like,

> [default]
aws_access_key_id = ABCDEFG
aws_secret_access_key = ABCDEFG
output = json
region = us-east-1

Not keep the last two lines in config file which is also in `~/.aws`.

Based on this, the CloudWatch data source works.
![image](https://cloud.githubusercontent.com/assets/3666914/17027989/a45bde92-4f98-11e6-8e42-f72e95aa3990.png)

**Comment by zevarito** [comment]
For me running Grafana as Docker container was needed to configure which Profile to use, like this... https://github.com/grafana/grafana-docker#configuring-aws-credentials-for-cloudwatch-support

**Comment by davidfox2** [comment]
Same issue, ended doing the following:
sudo mv ~/.aws /usr/share/grafana/
sudo chown -R grafana:grafana /usr/share/grafana/.aws
sudo chmod 700 -R /usr/share/grafana/.aws

it is rather odd as the rest of that directory belongs to root:root but the .aws creds need to be grafana:grafana 700 to work (600 did not work for me, nor did root:grafana)


I did try moving the directory elsewhere and then updating the path but that didn't work.
in fact it caused another problem. where the profile name wont let go of old profile names!

I tried changing the path to etc/
save and test
failure
removed profile name and tried putting file back in /usr/share/grafana
save and test
failure
press cancel
click back on datasource
etc/ shows up in path again even though the last save config deleted it from the path, and appeared as deleted!

I needed to remove the datasource sompletely, and add a new one before it would accept the default path again.


anyone else want to try and confirm this behaviour?
could it possibly be that grafana is keeping old paths even after naming a new one or removing one?

also could someone on the grafana team change the documentation on http://docs.grafana.org/datasources/cloudwatch/ that the correct path is /usr/share/grafana/ and that it needs to be owned by grafana:grafana with 700

**Comment by foobarnum** [comment]
Weirdly home was set differently on the latest Ubuntu vanilla install. Moving the .aws/ to /var/lib/grafana was what was needed. Home in the log vs. home on the sytem were different.

ubuntu@ip-10-1-0-154:~$ cat /etc/passwd |grep grafana | cut -d':' -f6
/var/lib/grafana

ubuntu@ip-10-1-0-154:~$ sudo cp -vR /usr/share/grafana/.aws/ /var/lib/grafana
'/usr/share/grafana/.aws/' -> '/var/lib/grafana/.aws'
'/usr/share/grafana/.aws/credentials' -> '/var/lib/grafana/.aws/credentials' 

Startup logging

Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]: Command lines overrides:
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]:   [0]: default.paths.data=/var/lib/grafana
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]:   [1]: default.paths.logs=/var/log/grafana
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]: Paths:
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]:   home: /usr/share/grafana
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]:   data: /var/lib/grafana
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]:   logs: /var/log/grafana
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]: 2016/11/19 19:28:58 [I] Database: sqlite3
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]: 2016/11/19 19:28:58 [I] Migrator: Starting
Nov 19 19:28:58 ip-10-1-0-154 grafana[18169]: 2016/11/19 19:28:58 [I] Listen: http://0.0.

**Comment by jmdacruz** [comment]
Do I still need a file in `${GRAFANA_HOME}/.aws` if I'm using IAM roles instead of credentials? I'm seeing this very same issue, but I'm using Grafana `4.1.0-1484127817` on Ubuntu 14.04, and I'm using `Auth Provider: ARN` with the proper value on the `Assume Role ARN` property. I'm seeing the following log entry when trying to "Save & Test" the data source:

```
t=2017-01-12T21:57:06+0000 lvl=eror msg="Unable to call AWS API" logger=context userId=1 orgId=1 uname=admin error="NoCredentialProviders: no valid providers in chain. Deprecated. \n\tFor verbose messaging see aws.Config.CredentialsChainVerboseErrors"
```

**Comment by kyanh-huynh** [comment]
I had a similar problem. After many hours trying I deleted the failed data source and created a new one with same settings (using ~/.aws/config and ~/.aws/credentials.)

**Comment by jonseymour** [comment]
I also observed the behaviour that @jlEtsnJSd6ze1uOO noted. If the credentials profile datasource is created fresh, then it doesn't work, but if it is created with keys first, then reconfigured to use credentials it does work.

I suspect, but have not yet confirmed, that the reason this is so is that the credentials are not completely cleared upon reconfiguration and the way the shared credentials provider works is that it re-uses the originally configured credentials in place of the shared profile.
