### ISSUE TITLE
Upgrading to Grafana 8.3 broke variable interpolations with Azure Monitor

### ISSUE THREAD

**Issue by hakro** [grafana/grafana#42746]
After upgrading from Grafana 8.2.5 to 8.3, dashboards using Azure Monitor lost their parameters that have variables in them.

Here is a basic exemple : 
When modifying a panel that uses variables, the fields are empty.

![2021-12-03_16-02](https://user-images.githubusercontent.com/3624853/144625295-6ef30844-5614-4e2d-8796-d27707464d8d.png)

**What you expected to happen**:
It was expected to have the same resource names that were there before, based on the variables that are set.
In our case, we expected to have those values filled in : 

![2021-12-03_16-02_1](https://user-images.githubusercontent.com/3624853/144625696-2c71a9ee-90cc-476d-a9a1-12091b8ec114.png)

**How to reproduce it (as minimally and precisely as possible)**:
- On Grafana 8.2.5, have a panel using Azure Monitor, with fields based on variables
- Upgrade to Grafana 8.3
- Edit the panel. The fields using variables are empty. They should be filled

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Official docker image
- User OS & Browser: Any
- Grafana plugins: None
- Others:

**Comment by cdalvaro** [comment]
I have same issue too with Prometheus

**Comment by hakro** [comment]
Anyone has any workaround for this issue.
It's actually preventing us from making any modifications to our dashboards, because we loose all parameters when we try to edit, and we have to do it all over again.

I tried exporting the dasboard in json format. The variables are correctly set in the file. I then tried to import the json template again, and edit the dashboard, but I had the same issue. The fields using variables are empty.

Thx

**Comment by sarahzinger** [comment]
Hi @hakro sorry to hear the upgrade didn't go smoothly. I'm trying to recreate this now and better understand the issue so we can debug and I have a couple of questions if you have the time:
- can you take a look at the variables settings page (click the gear on the top right hand side of a failing dashboard and then click on the variables tab on the left) and let me know what types of variables these are that you are creating that seem to be failing? For example are these of type constant or query? A few screenshots of how you set up the original variables would be very helpful if you can!
- am I correct in understanding that the issue seems specific to variables that are dependent on other variables? So for example a variable of metric namespace with the value of "Microsoft.Web/serverFarms" works but the challenge is with variables like resource group which has a variable $Environment being used. 

Thanks so much!

**Comment by hakro** [comment]
Hello @sarahzinger 
Thank you for looking into this. Here are the details : 

On of the dashboards that has this issue, only has some simple variables : constant, and custom (with simple text).

Those variables are not interdependent on each other, they are rather ... flat.
![2021-12-14_17-23](https://user-images.githubusercontent.com/3624853/146039314-03f4ad72-1d11-4bf5-93c2-9a311d8f1f79.png)

The correct dashboard looks like this : 
![2021-12-14_17-24](https://user-images.githubusercontent.com/3624853/146039514-242a9c12-102a-4cff-b2f2-11a976926daa.png)

And when editing one of the panels, it looks like this : 
![2021-12-14_17-27](https://user-images.githubusercontent.com/3624853/146039601-4d98375c-6c67-44da-a5ac-a9f23b9cf597.png)

Only the fields using variables are indeed missing.
At this point I can only discard everything, otherwise if I save, the dashboard is broken.

Hope this help, let me know if you need any more info, happy to help.
Cheers.

**Comment by sarahzinger** [comment]
@hakro that's very helpful thanks!

Here's what I can see
- create a constant template variable in azure monitor on 8.1.7 (
- directly editing the dashboard's json to use the variable `thing-${variablename}`
- I see it listed in the edit panel page in the dropdown and the query loads correctly. When I look at the dashboard on it's own it also loads correctly.

Then starting at about 8.2 or so:
- dashboards using that variable load normally
- but when I go to the edit panel page they do not load properly in the dropdowns, nor does it render the query properly on the edit page. And when I go back to the dashboard page the query is stops loading (until I refresh the page and then it loads properly again)

In doing this I noticed in general our template variables often break on edit pages (not just not rendering in dropdowns but also in general not loading which seems like a separate but potentially related issue). I'm going to take a bit to investigate further and see if we can put in a fix!

In the meantime, I hope that the queries themselves can load on the dashboard page at least? I suppose there's also the possibility of trying to run this on 8.1 for a bit. I'm sorry I know that's not a great work around. If I think of a better alternative I'll let you know! Hopefully we can get a fix released very early january at the very least.
