### ISSUE TITLE
Error when creating a alert using the new unified alerting after upgrade to 8.3

### ISSUE THREAD

**Issue by hakro** [grafana/grafana#42755]
**What happened**:
Some metrics that usually return 0 from Azure Monitor have broken the alerts.
For example we had an alert on the number of fails (alert if it goes above 0) for Azure data factory executions : 

![2021-12-03_18-03](https://user-images.githubusercontent.com/3624853/144642969-bd56d21d-7815-41ca-b51c-3a52bb146b3f.png)

After the migration to 8.3, and enabling the unified alerting, those kind of alerts stopped working, and a big error shows up.
Trying to create the same alert yields the same error message. I looks like this : 

![2021-12-03_17-54](https://user-images.githubusercontent.com/3624853/144643197-8b716982-f9d7-43fd-8a34-754425c22079.png)

Here is the complete error : 

`TypeError: Ce[t] is undefined

jt@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:5069:18
div
l@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:3485:862
div
div
i@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:1448:7845
g@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:560:1539
Op@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:3407:5738
TimeSeries
./public/app/features/plugins/plugin_loader.ts/It<@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:5069:2339
Sl@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2868:458
Tl@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2868:1006
g@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:4812:15494
div
div
t@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:1184200
div
Y@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:47:2727
div
div
div
./.yarn/__virtual__/react-beautiful-dnd-virtual-459d405f6d/3/opt/drone/yarncache/react-beautiful-dnd-npm-13.1.0-fcf5568b1c-12b7e9fbe8.zip/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js/qo<@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:584951
f@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:498533
Uo@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:586322
Ho@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:586431
c@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:4225:951
div
S@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:5795:544
div
te@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:53:219
div
./.yarn/__virtual__/react-beautiful-dnd-virtual-459d405f6d/3/opt/drone/yarncache/react-beautiful-dnd-npm-13.1.0-fcf5568b1c-12b7e9fbe8.zip/node_modules/react-beautiful-dnd/dist/react-beautiful-dnd.esm.js/Go<@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:588664
f@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:498533
f@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:496186
oo@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:571695
t@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:504956
io@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:575435
se@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:59:270
div
ge@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:59:4722
F@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:891161
div
div
p@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:394:178
fieldset
Hd@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:3188:992
div
div
p@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:1:2107
Se@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:70:244
div
div
div
t@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:657031
u@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:262:1027
div
form
A@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:889085
ht@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:99:32
./public/app/features/alerting/unified/RuleEditor.tsx/It<@https://grafana.pernriri.io/public/build/AlertingRuleForm.fab5d6bbd438adca1160.js:122:35
Sl@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2868:458
Tl@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2868:1006
WithErrorBoundary
n@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:942013
zi@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:6393:193
t@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:989568
t@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:991589
main
t@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:986186
div
Ws@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2156:1022
./public/app/core/utils/ConfigProvider.tsx/d<@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:4480:26183
Sl@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2868:458
Tl@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:2868:1006
l@https://grafana.pernriri.io/public/build/633.fab5d6bbd438adca1160.js:2:969086
Oo@https://grafana.pernriri.io/public/build/7095.fab5d6bbd438adca1160.js:6473:384`

On the alert, I can also see this error : 
`failed to execute query B: request failed, status: 400 Received invalid query parameter: [aggregation, ],[api-version, 2018-01-01],[interval, PT1M],[metricnames, RunsFailed],[metricnamespace, Microsoft.Logic%2Fworkflows],[timespan, 2021-12-03T16%3A09%3A08Z%2F2021-12-03T17%3A09%3A08Z], TraceId: {94627f90-8435-414e-a259-020e33fc4171} for request: subscriptions/xxxxxxxxxxx/resourceGroups/regprhocbprod/providers/Microsoft.Logic/workflows/lacprhocbdiagnosticsprod/providers/microsoft.insights/metrics`

![2021-12-03_18-11](https://user-images.githubusercontent.com/3624853/144644324-d2141fa9-2991-48b7-9e99-e1808b81ff2a.png)

The same query works fine on Explore.

**What you expected to happen**:
No error

**How to reproduce it (as minimally and precisely as possible)**:
Try to create an alert on a metric that returns 0 from Azure Monitor (Data factory fails for example)

**Anything else we need to know?**:
Nope

**Environment**:
- Grafana version: 8.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Grafana official docker images
- User OS & Browser: Any
- Grafana plugins: None
- Others:

**Comment by santihernandezc** [comment]
Hey @hakro, thanks for opening this issue.

I wasn't able to replicate it exactly, but I found a very similar error related to Azure Monitor alerts in the process. I made a [PR](https://github.com/grafana/grafana/pull/42989) to fix that bug, and I think that same PR could potentially fix the one you're describing too.

Could you provide some more details on how to reproduce this exact error so I can make sure my PR fixes that too? For example, could you show me the next step in the alert you created?

**Comment by hakro** [comment]
Hello @santihernandezc 

Happy to help.
Here is what I did : 

1 - Upgraded to 8.3 (even 8.3.2 today), and enabled unified alerting using the environment variables config on the official Docker image

2 - Checked that ma query works on explore, it did : 
![2021-12-10_22-01](https://user-images.githubusercontent.com/3624853/145640885-e952645c-9c9b-4685-b19e-34fa8d589a83.png)

3 - Tried creating an alert using the same query. The error shows up right away. I thought it was related to queries returning 0 values (like in my example), but it actually show up all the time, regardless of the query.

I just discovered however that this error only shows up on the "Time series" view : 

![2021-12-10_22-10](https://user-images.githubusercontent.com/3624853/145642068-8ff22b94-4187-4c20-b21b-90b886764eb0.png)

4 - Switching to "Stat" or "Table" view, the error disappears
![2021-12-10_22-11](https://user-images.githubusercontent.com/3624853/145642174-437ac169-34c2-466a-8371-8fa5174cad50.png)

5 - In any case, there is no issue with the rest of the configuration, and I'm able to save the alert correctly.

I hope this helps.
Let me know if I can provide more info.

Cheers.

**Comment by santihernandezc** [comment]
@hakro yes! I noticed that an error pops up for every alert you try to set up using Azure Monitor as the data source, and that it's a thing that only happens in the Time Series view. The PR I submitted solves that.

I wasn't able to get near that `failed to execute query B` error though. I created an alert that resulted in that `TypeError` bug and saved the alert, but it is healthy nevertheless. I'll try to break that today.

**Comment by hakro** [comment]
Thank you for the feedback @santihernandezc 

A bit more fresh info that I got this weekend, hopefully it will help you pin point the issue : 
- The `failed to execute query B` seems to have appeared after the migration to 8.3, and enabling unified alerting. We have around 50 alerts with the same structure (send an alert if any there is a logic app execution failure, the query is that simple, no expression, or anything else used in it). Only 4 of these got the error state. Not sure why.

- This weekend, I have recreated all 4 alerts from scratch, and I didn't get the error any more. But I still get an excessive number of alerts due to "No data" or "Error" state, even though I see all values correctly on Explore. No values are missing on the Azure Monitor console either.

I hope this helps.
Cheers.

**Comment by santihernandezc** [comment]
@hakro my PR got merged. It solves the error in the "graph view" tab when creating an Azure Monitor alert. Now the graph is rendered correctly.

![Screen Shot 2021-12-16 at 14 02 43](https://user-images.githubusercontent.com/41638679/146577028-f6d4572d-061c-41e9-a40a-b444db489dd5.png)

About the high number of No Data / Error alerts you're getting... have you got the logs available that cover this time period? I suspect that there may have been an intermittent connectivity issue with your data source causing these alerts and want to see if I am able to confirm that.

**Comment by hakro** [comment]
Thanks @santihernandezc 

Here are a couple of recent logs while the same kind of alert triggered this night (around 00:15 in the logs, matching 1:15am in the next screenshots because of TZ differences)
[grafana.log.zip](https://github.com/grafana/grafana/files/7755002/grafana.log.zip)

This happens quite frequently since the upgrade, the datasource is Azure monitror.

Don't know if this helps, but here is some additional info : 
Here is the annotations on the dashboard around the time one of the alerts triggered : 
![2021-12-21_12-47](https://user-images.githubusercontent.com/3624853/146925626-645310a0-4c37-4c4b-9aaf-08399c181312.png)

And here are the values returned by the same query in explore. All of the values are there at that time:
![2021-12-21_12-49](https://user-images.githubusercontent.com/3624853/146925717-6ae95d3c-7ec5-42f5-a88c-c4431f2e284b.png)

And I get a bunch of spams at that moment, the email look like this : 
![2021-12-21_12-42](https://user-images.githubusercontent.com/3624853/146925929-97befe2e-010a-4562-b5aa-72c3094bca75.png)

Hope this helps.
Cheers

**Comment by hakro** [comment]
Hello @santihernandezc 

Somehow, all those alerts get triggered everyday at the same time, at 1:15 for me.
Here is an overview of the alert configuration: 

![2021-12-22_11-44](https://user-images.githubusercontent.com/3624853/147080707-39a7fc22-6a72-423e-a920-17d79bf0256c.png)

Some of the alerts are send becasue of a NO DATA, and some because of Datasource error, pretty much at the same time.
We could switch those to OK in the alert config, but it would defeat the purpose of those 2 fields, since we do want to get alerts when the datasources are legitimately failing.

Hope this helps.
Cheers

**Comment by santihernandezc** [comment]
Hey @hakro, thanks for the detailed explanation.
Could you set the `GF_LOG_LEVEL=debug` in order to turn debugging on around the time this happens? This way we can have the results for the query. These results may contain the error wrapped in.
Also, if you're being spammed with alerts from this data source you can change the Alertmanager grouping for this type of error to wait longer before notifying.

**Comment by armandgrillet** [comment]
We believe https://github.com/grafana/grafana/issues/44077 has closed this issue, feel free to reopen this issue if that's not the case.
