### ISSUE TITLE
Serviceaccounts: Emit audit logs for all mutating actions for service accounts

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#42769]

**Comment by ashharrison90** [comment]
@eleijonmarck can you please add some labels to avoid this appearing in issue triage view? thanks! 😄

**Comment by vtorosyan** [comment]
@eleijonmarck is this something perhaps we need to do with 8.5 release? I think we need to ensure to have audit logs for every new feature or?

**Comment by eleijonmarck** [comment]
@vtorosyan not sure if this is part of some SLA or similar we have. asking around in the #grafana channel now

**Comment by eleijonmarck** [comment]
@vtorosyan this is alright to have for 9.0, it is not a requirement for any beta feature. But of course would be good to have.

https://raintank-corp.slack.com/archives/C036J5B39/p1647962788777939
