### ISSUE TITLE
Preview of slack notifications in the new alerting is not displayed

### ISSUE THREAD

**Issue by itays-chase** [grafana/grafana#42768]
**What happened**:
After upgrade to the new alerting system, When an alert is triggering a notification to slack, the preview of the message is "This content can't be displayed".

**What you expected to happen**:
When there is a notifications sent from grafana to slack, I expect to see a preview of the message, maybe the message title.
It's happend on all slack apps including mobile and desktop.

**Anything else we need to know?**:
I think it's maybe related to the blocks message feature of slack. If you use blocks and you don't put a global text field for the message, you are getting that "Content can't be displayed" message.
https://stackoverflow.com/questions/56317962/message-notifications-produce-this-content-cant-be-displayed/56327506

**Environment**:
- Data source type & version:
- ubuntu 18.04
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuri-tceretian** [comment]
Hi @itays-chase, thanks for reporting about the issue! What version of Grafana do you use?

**Comment by itays-chase** [comment]
Hey @yuri-tceretian 
I am using grafana 8.2.5
and using slack webhooks

**Comment by davidmparrott** [comment]
I will test and see if I can reproduce this. Thanks for letting us know more about your setup

**Comment by davidmparrott** [comment]
@itays-chase I have not been able to reproduce this so far. Can you share your slack channel config here, please? Either screenshots that have sensitive fields redacted or (preferably) the JSON from the admin panel. Thanks!

**Comment by itays-chase** [comment]
@davidmparrott here is the json from the admin panel
`{
  "template_files": {},
  "alertmanager_config": {
    "route": {
      "receiver": "alerts-slack-channel",
      "group_by": [
        "alertname",
        "alertinstance"
      ],
      "repeat_interval": "12h"
    },
    "templates": null,
    "receivers": [
      {
        "name": "autogen-contact-point-default"
      },
      {
        "name": "alerts-slack-channel",
        "grafana_managed_receiver_configs": [
          {
            "uid": "LTr9Zqtnkz",
            "name": "alerts-slack-channel",
            "type": "slack",
            "disableResolveMessage": false,
            "settings": {
              "autoResolve": true,
              "httpMethod": "POST",
              "icon_url": "https://ddo0fzhfvians.cloudfront.net/uploads/icons/png/8135670941548141941-512.png",
              "mentionChannel": "channel",
              "severity": "critical",
              "text": "{{ if gt (len .Alerts.Firing) 0 }}\n{{ range .Alerts.Firing }} \n{{  .Annotations.message }} \n{{  .Labels.alertinstance }} \n{{  .Annotations.value }} \n{{ end }}\n{{ end }}\n{{ if gt (len .Alerts.Resolved ) 0 }}\n{{ range .Alerts.Resolved }}  \n{{  .Labels.alertinstance }} \n{{ end }}    \n{{ end }}",
              "title": "[{{ .Status | toUpper }}] {{ .GroupLabels.alertname }}",
              "uploadImage": true,
              "username": "Grafana"
            },
            "secureFields": {
              "url": true
            }
          }
        ]
      }
    ]
  }
}`

**Comment by davidmparrott** [comment]
Great, thank you! This is helpful. I have a suspicion from looking at it but I'm going to stuff this into a test instance I have to verify if I'm correct. I think this might come down to the fact that grafana alerting, after 8.0, doesn't support image uploads.

**Comment by davidmparrott** [comment]
@itays-chase so far I have not been able to reproduce this behavior. Can you give me some screen shots of the alerting rule configuration? I have tried this on 8.2.5 as well as current head of main and I get the same behavior: a very uninformative message but not the behavior you're describing.
<img width="536" alt="Slack___testing___dp-test" src="https://user-images.githubusercontent.com/4461026/147130591-d19aaf5e-8774-4869-b66e-6258935e4e00.png">

**Comment by jgillick** [comment]
@davidmparrott This is in the slack notification on my device and on my computer. All other slack messages preview correctly. Part of the problem is if I see an alert notification hit my phone, it's good to know if it's a P0 issue immediately without unlocking my phone.

<img width="431" alt="Screen Shot 2022-01-05 at 10 49 12 AM" src="https://user-images.githubusercontent.com/35894/148272353-827a49ac-127e-4d51-abc0-6cb236cfe8d0.png">

My theory is that the message is sent as a pure slack attachment without a message body. If the title of the slack message is sent as plain text before the attachment, the notifications might work correctly.

Here's my slack configuration.

<img width="1220" alt="Screen Shot 2022-01-05 at 10 50 09 AM" src="https://user-images.githubusercontent.com/35894/148272790-a1bf60f9-9fa0-447f-b6d0-f33bb0377bb9.png">

**Comment by davidmparrott** [comment]
@jgillick is it only the push notification where you're seeing this? I'll have to see if the popup on my phone behaves this way, I didn't think to look at that. Thanks for the context.

**Comment by jgillick** [comment]
@davidmparrott Yes, I'm only seeing this on the push notifications on both my computer and phone. All other slack push notifications display correctly, so I assume it has something to do with the way the slack message is structured by grafana. I'm assuming that slack attachments cannot be turned into previews, so adding text before the attachment might work.

**Comment by itays-chase** [comment]
@davidmparrott any news?

**Comment by davidmparrott** [comment]
@itays-chase unassigning myself from this as I am no longer with grafana labs.

**Comment by jgillick** [comment]
I'm attempting to fix this with PR https://github.com/grafana/grafana/pull/45750. From what I can tell, this only happens when a user is added to the `Username` field. Can the rest of you confirm this?
