### ISSUE TITLE
excessive open ports on alertmanager server

### ISSUE THREAD

**Issue by aggholamyy** [grafana/grafana#42766]
**What happened**:
there are lots of established connections from grafana-server on prometheus-alertmanager
**What you expected to happen**:
usually connections on alertmanager closed after a while but grafana 8.2.3 never close connections, they just open every 13-14 sec
**How to reproduce it (as minimally and precisely as possible)**:
for reproducing this issue I don't have specific way, but every time I restart grafana-server or alertmanager all those connections vanished
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.3
- Data source type & version:
- OS Grafana is installed on: ubuntu 20.04
- User OS & Browser: chrome all main stream OSs
- Grafana plugins:
- Others:

**Comment by gotjosh** [comment]
Hi @aggholamyy - what connections are we talking about? How are you monitoring them? Can you please give us a bit more detail on how we can investigate this issue?

What is the relationship between grafana-server and prometheus-alertmanager here? Are you referring to the internal Alertmanager or..?

**Comment by aggholamyy** [comment]
> Hi @aggholamyy - what connections are we talking about? How are you monitoring them? Can you please give us a bit more detail on how we can investigate this issue?
> 
> What is the relationship between grafana-server and Prometheus-Alertmanager here? Are you referring to the internal Alertmanager or..?

when grafana wants to send alert notifications, send them to Prometheus Alertmanager and therefore grafana open a connection from a random port to port 9093 of Prometheus Alertmanage, for checking this out I used "lsof -i:<pid of Prometheus alertmanager>" and in the result the owner of all those connections was grafana-server and there was 3 connection for other services like Prometheus itself

**Comment by zuchka** [comment]
hi @aggholamyy 

are you still encountering this issue?

**Comment by aggholamyy** [comment]
Hi
Honestly I had to delete the user and make it from admin panel, that issue
saw when the user try to create account by sign up button.
  After that I don’t see the issue again.
