### ISSUE TITLE
Variable not updating when time range changes

### ISSUE THREAD

**Issue by genedavis** [grafana/grafana#42761]
**What happened**:  Believe this could be a duplicate of #27294 which has been closed but has recent comments that there could still be issues as of Grafana 8.1.0.  What we see:

We have a Dashboard variable, call it A, set to refresh "On time range change".  This variable controls the list of items for for the query for a repeated panel display (and this list is time-range-sensitive).  However, upon time range change, this variable is seemingly not re-evaluated since the variable A is not updated as expected.  We instead have to change some OTHER variable value - which seems to trigger A's re-evaluation and panel redisplay

**What you expected to happen**:

Upon time range change, the variable should be evaluated and the graph properly populated.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a variable that returns the "items" you wish to display based on whether that item contains an "anomaly" in the current time frame (note therefore that as time range changes, different items will quality)

Create a dashboard displaying those items.  An initial refresh of the chart will show the correct items.

Now scroll time - a different set of items will have anomalies, but the dashboard is still displaying the original list of items.  Only a change/refresh of ANOTHER variable (say, a parameter controlling the maximum NUMBER of items to display) triggers the recomputing of the "items with anomalies" to show.

**Anything else we need to know?**:

**Environment**:  
- Grafana version: Grafana 8.1.1 with TimescaleDB enabled
- Data source type & version:  Postgres 13
- OS Grafana is installed on:  Ubuntu 18
- User OS & Browser:  Mac OS/X Chrome
- Grafana plugins:  none
- Others:

**Comment by ashharrison90** [comment]
hey @genedavis 👋 

i can't repro this on our test dashboard for this scenario on latest Grafana - are you able to share your dashboard json?

thanks!

**Comment by genedavis** [comment]
I think we have something for you @ashharrison90 

We have a reproducible version AND we think we have a way around it (though still likely a bug?).  This basically boils down to the Refresh setting of one of the dependent variables.

Steps to reproduce:
```
create table foo_time (id int, val float, t timestamp, system varchar(255));

insert into foo_time values (1, 10, '2021-01-01', 'A'), (2, 20, '2021-01-02','A'), (3, 30, '2021-01-03','B'), (4, 40, '2021-01-04','B'), (5, 50, '2021-01-05','B');
insert into foo_time select id, val+10, t + interval '1 day', system from foo_time;
insert into foo_time select id, val+20, t + interval '2 day', system from foo_time;
insert into foo_time select id, val+40, t + interval '4 day', system from foo_time;
```

Load up the attached dashboard from JSON.

Click the right arrow for time once or twice, and you'll see that we continue to show all ID's we were showing (3,4,5) in our repeated chart, though we SHOULD only be showing those WITH VALUES because of the $foo_time_var variable (filtering on t).  But it will still show the 3 id's even though it should not.

Now edit the variable System, and change Refresh from "On time range change" to "On dashboard load".
Rerun the above experiment, and you will see the proper behavior - we only see the repeated charts when they qualify from the foo_time_var variable.

Once we made this change ourselves, the undesired behavior went away - though it still seems like a bug?

Thanks! - Gene

**Comment by genedavis** [comment]
[Time Update Bug Reproduce-1638836193239.json.zip](https://github.com/grafana/grafana/files/7664370/Time.Update.Bug.Reproduce-1638836193239.json.zip)

Zipped version of the dashboard json

**Comment by hugohaggmark** [comment]
Thanks for reporting this @genedavis and such great repro steps and dashboard json, it really made the investigation such a breeze.  The thing causing this is that we're not processing any repeats on time range changes. I've alway wondered why this was the case for the "normal" variable changed path but not the on "time range changed" path. Is there are reason why processRepeats are not called on "time range changed" path @torkelo?

**Comment by genedavis** [comment]
Cool PR submitted and merged - thanks @hugohaggmark !
