### ISSUE TITLE
ask a questionn about the "Home"

### ISSUE THREAD

**Issue by hugoren** [grafana/grafana#4276]
Hi great god.Why I is administrator, and have no legal power to save the configuration of the home page or how to set the home page

**Comment by torkelo** [comment]
simple answer because no one has implemented the ability to do that yet :(

But work on it has started, https://github.com/grafana/grafana/issues/1678

**Comment by hugoren** [comment]
Thank you for your answer, why you can put the "Grafana Play Home" as the homepage on "http://play.grafana.org"?
Can you teach me?

**Comment by torkelo** [comment]
on play.grafana.org I have updated the file `/usr/share/grafana/public/dashboards/home.json`
