### ISSUE TITLE
close format data not work

### ISSUE THREAD

**Issue by sshuair** [grafana/grafana#42772]
Close the `Query Inspector` -> `Formated Data` is not work, It still convert the hex(postgresql type is varchar(64)) to int.
1. the original data(this is what I want):
![image](https://user-images.githubusercontent.com/5787131/144832041-b0f82dc4-544a-4700-b42c-2a1b83bce0b6.png)

2. this is the grafan query and displayed
![image](https://user-images.githubusercontent.com/5787131/144831322-9d2ac2d6-941b-4693-b578-5d58282715f2.png)

3. the is on the chart display
![image](https://user-images.githubusercontent.com/5787131/144831709-1f498941-1658-4ac7-9d78-60fb7a3a5f96.png)

**Comment by ashharrison90** [comment]
hi @sshuair 👋 

i believe this is behaving as designed. as stated in the description for `Formatted data`, this formats the data according to any overrides you've specified. by default, it tries to format the hex to a number. if you want to keep it as hex, you can add a field override to set the unit:

![image](https://user-images.githubusercontent.com/20999846/144866839-bacb6cfb-21b5-4fa5-88ce-7ddd53910ae7.png)

this should give you the behaviour you want in the query inspector.

if you believe there's still a bug or i've missed something, please let me know and we can reopen this. thanks! 😄

**Comment by sshuair** [comment]
woo， thanks
