### ISSUE TITLE
Circle CI fix needed

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4280]
Please fix Go tests

Failing tests details:

File: pkg/plugins/plugins_test.go
Line: 37

Expected:
```So(Apps["app-example"].Info.Screenshots[1].Path, ShouldEqual, "public/plugins/app-example/img/screenshot2.png")```

Actual:
```So(Apps["app-example"].Info.Screenshots[1].Path, ShouldEqual, "app-example/img/screenshot2.png")```

**Comment by torkelo** [comment]
ah, must have missed an email from circle ci, thanks for informing me!
