### ISSUE TITLE
In table with outer join transformation by time - hiding time field shifts units formatting of other fileds

### ISSUE THREAD

**Issue by leonsery** [grafana/grafana#42817]
**What you expected to happen**:
I have 4 queries (for CPU, MEM, NET and FS) and want to show table with series as a columns. This is result from Grafana 6.7:
![image](https://user-images.githubusercontent.com/27145550/145001413-e2b9e397-3502-4776-a7ec-4f9c3b397e4a.png)

**What happened**:
When using outer transformation by time field and trying to hide this field - the formatting of next fields shifted left.
My queries:
![image](https://user-images.githubusercontent.com/27145550/145001945-8d8e9a07-c850-4fa7-b738-91d754c1b1e2.png)

Transformation:
![image](https://user-images.githubusercontent.com/27145550/145002078-b527140a-44cb-43de-8950-f72799bd2a02.png)

Overrides:
![image](https://user-images.githubusercontent.com/27145550/145002522-7a3c7a13-b201-4fa1-b4b8-e3f1ae4d21d3.png)

Result before hiding time field - all fileds have proper units formatting:
![image](https://user-images.githubusercontent.com/27145550/145002562-4ddef913-a1b5-46a3-9b61-e8fb17b2d095.png)

After hiding time filed - all formates shifted left (CPU becomes to be formatted as a timestamp, RAM - as just number (like CPU), NET as RAM and FS as NET):
![image](https://user-images.githubusercontent.com/27145550/145002643-d6d7ad3c-fdae-4f7d-bd8a-67e9b82485ae.png)

**Environment**:
- Grafana version: 8.3 (tried also in 7 - the same behavior)
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- User OS & Browser: Chrome
- Grafana plugins: new table

**Comment by leonsery** [comment]
Is there any other way to get what I need with new table?
![image](https://user-images.githubusercontent.com/27145550/145004517-a290a271-1ea5-4b9a-8403-ee9742e214c4.png)

**Comment by ashharrison90** [comment]
can repro this locally.

use something like:
```
time,a,b
1638873263121,1,2
1638873263123,3,4
1638873263125,5,6
```

in the gdev csv content datasource. add a `hide in table` field override for `time`. toggle to true, and observe how it tries to parse the `a` column as a time. any subsequent overrides also then apply to the wrong index (i'm overring a, but it's applying to b):

![image](https://user-images.githubusercontent.com/20999846/145015127-6911561f-af32-45f1-b84b-ccedfeff8233.png)

**Comment by codeincarnate** [comment]
This was fixed with https://github.com/grafana/grafana/pull/50940
