### ISSUE TITLE
Do you have a detailed description of these parameters

### ISSUE THREAD

**Issue by hugoren** [grafana/grafana#4285]
Do you have a detailed description of these parameters and each parameter?

LIke :
       Combine
       Transform
       Calculate
       Filter
       Special

**Comment by bergquist** [comment]
I don’t really know what parameters you are talking about. Are you referring to database parameters?

**Comment by torkelo** [comment]
@hugoren those are graphite function categories, https://graphite.readthedocs.org/en/latest/
