### ISSUE TITLE
Grafana 0day is out

### ISSUE THREAD

**Issue by debu99** [grafana/grafana#42859]
Unauthorised file read 

https://www.wangt.cc/2021/12/grafana-未授权任意文件读取漏洞/

**Comment by ashharrison90** [comment]
hi @debu99 👋 

we've released updated versions with a fix. please see https://grafana.com/blog/2021/12/07/grafana-8.3.1-8.2.7-8.1.8-and-8.0.7-released-with-high-severity-security-fix/?src=slack&mdm=social for more info.

thanks! 🙌

**Comment by hamelg** [comment]
8.2.7, 8.1.8 and 8.0.7 are missing on the releases page.
https://github.com/grafana/grafana/releases
