### ISSUE TITLE
Package @grafana/toolkit upgrade ,plugins sign fail

### ISSUE THREAD

**Issue by dessen-xu** [grafana/grafana#42860]
**What happened**:
![image](https://user-images.githubusercontent.com/41524013/145144499-08366344-4146-4020-94f4-37231af7a243.png)
I see the package @grafana/toolkit was upgrade to 8.3.0. The v8.3.0 would lead to plugin sign fail. 

Sign with v8.3.0,the rootUrls is wrong
![image](https://user-images.githubusercontent.com/41524013/145145114-29682dd1-e0bf-43f2-a3da-bd20d9307641.png)

Sign with previous version，it is correct:
![image](https://user-images.githubusercontent.com/41524013/145159583-0440152e-ec61-43a0-8598-8d0ea2e73e24.png)

Sign with V8.3.0,the rootUrls is wrong.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: opentsdb,prometheus,mysql and so on
- OS Grafana is installed on: linux
- User OS & Browser:macOs, chrome
- Grafana plugins:
- Others:

**Comment by mckn** [comment]
Fixed by #43014
