### ISSUE TITLE
[UnifiedAlerting] Webhook alerts is sending the values from previous alert evaluation

### ISSUE THREAD

**Issue by molsza** [grafana/grafana#42872]
**What happened**:

I had created an alert with 2 queries and one condition. Like on the screenshot. Basically I am trying to compare recent error rates to the ones from the previous 5 days and fire the alert if it increase by more than 20%.

![image](https://user-images.githubusercontent.com/41799777/145190973-74e4f3bc-675f-494c-af23-035144a723a9.png)
 
During the test/preview alerts everything looks fine. I have set evaluation of the alerts to be **30 min with pending 0**. To send the alert I am using the webhook. I've started receiving the alerts, but with values which doesn't match the condition ->  `current > last * 1.2`. I've compared the data with the time of the alerts and firing the alert was justified. Form comparison the real data with the values send in the alert it looks like the values in alerts are delayed.  

I have changed the alerts evaluation to be **5 min and 30 min in pending states**, and now they look accurate in firing events, but still they can come from previous 5 min ago evaluation, so values from resolve webhook usually look wrong (still meet alert condition).

**What you expected to happen**:

Values send in alert webhook should be current.

**How to reproduce it (as minimally and precisely as possible)**:

The presented use cases is above. Cannot say what is relevant. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.0, 8.3.4
- Data source type & version: MySQL

**Comment by molsza** [comment]
Turns out it is not so simple....

Even If I have a pending set it is still providing invalid values.
I've just received a set of incremental alerts:

Metric | Current Rate | Last 5 days
-- | -- | --
Metric1 | 0 | 0.099

Metric | Current Rate | Last 5 days
-- | -- | --
Metric1 | 0.125 | 0.099
Metric2 | 0 | 3.954

Metric | Current Rate | Last 5 days
-- | -- | --
Metric1 | 0.126 | 0.099
Metric2 | 6.667 | 3.949
Metric3 | 0 | 0

Every time when a new alert is reported it doesn't meet the condition, but next time when it is reported along with another new alert it does.

**Comment by davidmparrott** [comment]
@molsza can you post your alertmanager config here? I'm wondering if perhaps you're seeing something as a result of grouping and wait times.

**Comment by molsza** [comment]
There is no grouping or wait times configured, beyond the defaults. There is only an alert and mail contact point.

**Comment by molsza** [comment]
I have created the policy and set wait time to 1s but it didn't change much.

**Comment by davidmparrott** [comment]
@molsza I appreciate the extra context. Could you still post that for me, please?

**Comment by molsza** [comment]
It is something like this:
```
{
  "template_files": {},
  "alertmanager_config": {
    "route": {
      "receiver": "autogen-contact-point-default"
    },
    "templates": null,
    "receivers": [
      {
        "name": "autogen-contact-point-default",
        "grafana_managed_receiver_configs": [
          {
            "uid": "Fzf7MI1nk",
            "name": "autogen-contact-point-default",
            "type": "email",
            "disableResolveMessage": false,
            "settings": {
              "addresses": "michal...@....",
              "singleEmail": false
            },
            "secureFields": {}
          }
        ]
      }
    ]
  }
}
```

**Comment by molsza** [comment]
Another thing,  grafana know that the `test` value is 0, but it fires anyway:
![image](https://user-images.githubusercontent.com/41799777/148930009-d7bec34d-523a-4bd7-89f6-77bd36ddd50d.png)

**Comment by molsza** [comment]
I have created a simpler test:
With the query like:
`select RAND(), "a" as metric union all select RAND(), "b" as metric union all select RAND(), "c" as metric`
you don't need to care with table structures.
![image](https://user-images.githubusercontent.com/41799777/148933661-1b3c3c29-2d99-4e85-9e25-e390e7460c52.png)

The default emails result are:
![image](https://user-images.githubusercontent.com/41799777/148933417-a2fc58af-a69d-429f-bae7-a1e0cc067853.png)

**Comment by molsza** [comment]
@davidmparrott is there anything more you need?

**Comment by molsza** [comment]
Great, I've tested 8.4.2 and issue is gone.
