### ISSUE TITLE
path=/api/live/ws status=401 remote_addr=172.17.13.108 

### ISSUE THREAD

**Issue by cloudYuo** [grafana/grafana#42876]
**What happened**:
The background keeps reporting errors,i do nothing except start it with docker ,what caused it?
![图片](https://user-images.githubusercontent.com/37233582/145194948-9178e018-e87e-4cbe-a237-bc2095e0ff3f.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
start it with docker
**Anything else we need to know?**:

**Environment**:
- Grafana version:8.3.1
- Data source type & version:default
- OS Grafana is installed on:centos 7
- User OS & Browser:windows firefox
- Grafana plugins:default
- Others:

**Comment by bolshoytoster** [comment]
This could be related to #15316

**Comment by bolshoytoster** [comment]
It looks like `17217.13.108` tries to access `/api/live/ws` but their user token has expired so it returns [`401`](https://httpstatuses.com/401). It should bring the user to the login page but apparently doesn’t due to the repeated requests.

If you know what device `17217.13.108` is you could see if there are any errors in it’s browser

According to [this comment](https://github.com/grafana/grafana/issues/15316#issuecomment-833971558), it also can be caused by running multiple instances of grafana.

**Comment by cloudYuo** [comment]
> This could be related to #15316



> According to [this comment](https://github.com/grafana/grafana/issues/15316#issuecomment-833971558), it also can be caused by running multiple instances of grafana.

I think so,but i just start it ,didn't even open the browser and login.
it seems like a task with request /api/live/ws.
172.17.13.108 should be the ngnix.

**Comment by cloudYuo** [comment]
> It looks like `172.17.13.108` tries to access `/api/live/ws` but their user token has expired so it returns [`401`](https://httpstatuses.com/401). It should bring the user to the login page but apparently doesn’t due to the repeated requests.
> 
> If you know what device `172.17.13.108` is you could see if there are any errors in it’s browser
> 
> According to [this comment](https://github.com/grafana/grafana/issues/15316#issuecomment-833971558), it also can be caused by running multiple instances of grafana.
i login grafana,it is normal,but the error logs trouble me.
![图片](https://user-images.githubusercontent.com/37233582/145211064-328fe0a4-1be7-41b2-acb2-77572c8d391a.png)
![图片](https://user-images.githubusercontent.com/37233582/145211144-fefa87f1-1f84-49b1-bf68-a1b3ab460286.png)

**Comment by cloudYuo** [comment]
> It looks like `172.17.13.108` tries to access `/api/live/ws` but their user token has expired so it returns [`401`](https://httpstatuses.com/401). It should bring the user to the login page but apparently doesn’t due to the repeated requests.
> 
> If you know what device `172.17.13.108` is you could see if there are any errors in it’s browser
> 
> According to [this comment](https://github.com/grafana/grafana/issues/15316#issuecomment-833971558), it also can be caused by running multiple instances of grafana.

thanks.i get it, somewhere  tries to access /api/live/ws but their user token has expired
