### ISSUE TITLE
8.2.x ->8.3.1 Upgrade 

### ISSUE THREAD

**Issue by jlarmstrong** [grafana/grafana#42897]
**What happened**:
The normal DEB update release will no longer run under a grafana user/group without throwing errors related to both the log folder and /var/run/grafana. The recent release upgrade broke a system that i've upgraded without issue since 6.x and even uninstalling and reinstalling (checking all paths are removed) did not resolve the issue. The disk is NOT running in RO mode, I've manually confirmed this by touching another file in the same path.

Dec 08 13:11:19 host01 grafana-server[2560]: Failed to start grafana. error: failed to initialize file handler: open /usr/share/grafana/data/log/grafana.log: read-only file system
Dec 08 13:11:19 host01 grafana-server[2560]: failed to initialize file handler: open /usr/share/grafana/data/log/grafana.log: read-only file system

**What you expected to happen**:
The upgrade and related permission requirements would be applied or at least known to change.

**How to reproduce it (as minimally and precisely as possible)**:
Install 8.3.1 from apt deb package.

**Anything else we need to know?**:
I had this issue after the upgrade and after purging all grafana packages and manually confirming and removing the remaining folders it came back with a few install.

The grafana user/group has /bin/false set for the login shell.

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Postgres
- OS Grafana is installed on: Ubuntu 18.04LTS
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by bolshoytoster** [comment]
[This stackexchange answer](https://askubuntu.com/a/868792) suggests running `fsck -fn` and rebooting.

Have you tried this yet?

**Comment by jlarmstrong** [comment]
As mentioned above I can create files and folders without an issue.

**Comment by bolshoytoster** [comment]
If you run grafana something like `./grafana-server` you should be able to append `cfg:default.log.mode=console` to only log to stdout.

This is only meant to be a temporary solution.

**Comment by jlarmstrong** [comment]
I should have followed up with my current work around. After fully purging the systems of grafana and reinstalling (two identical systems running in an LB configuration). I had to enable bash login for the grafana user and I started the process manually using the same exact source of /etc/defaults/grafana-server and arguments within a detached shell so it kept running. That process has it running and writting as the grafana user/group to the log file.

**Comment by bolshoytoster** [comment]
I've opened a pull request that will allow grafana to continue running if it fails to initialise logs. It should resolve this issue.

**Comment by marefr** [comment]
@bolshoytoster I'm not sure that's a solution to the problem. If you fail to configure file based logs you probably want to be aware of it. Doesn't seem like there's other having this problem why it might be hard for us to accept the proposed solution.

**Comment by bolshoytoster** [comment]
@marefr We could keep running and print a message or we could leave it as it is but change the message to inform the user how to disable it (i.e. "failed to initialize file handler, you can disable it by running with the `cfg:default.log.mode=console` parameter").

**Comment by marefr** [comment]
@bolshoytoster sounds good :+1:
