### ISSUE TITLE
Error again.. Duplicates in a repeater are not allowed

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#4289]
hello brother.
i opend [#4282](https://github.com/grafana/grafana/issues/4282). 
and @torkelo told me that it was fixed in latest build.
i pulled the latest version of the code in here.
but i got same error again TT

when i click some buttons, especially, save&star buttons raise many errors. (check images plz)

<img width="539" alt="2016-03-08 7 07 42" src="https://cloud.githubusercontent.com/assets/13308314/13598561/cd2ebc1e-e561-11e5-81ce-5343ecb871f1.png">

then some errors occur in console tab(chrome developer tools).

<img width="812" alt="2016-03-08 7 06 56" src="https://cloud.githubusercontent.com/assets/13308314/13598549/b3a13c22-e561-11e5-9561-51abb134a21a.png">

there was no green alert message-box.

thanks a lot.

**Comment by bergquist** [comment]
@tuyy Sorry for this. 

Could you please open developer console and get the value from window.localStorage["dashboard_impressions"] and paste it here? 

Removing "dashboard_impressions" from localstorage should fix the problem for you (window.localStorage.removeItem("dashboard_impressions")) but it would be nice to see your current values so I can make sure this does not happen for other users.

Thanks!
/Carl

**Comment by tuyy** [comment]
@bergquist  This is window.localStorage["dashboard_impressions"] value

<img width="2560" alt="2016-03-09 9 59 00" src="https://cloud.githubusercontent.com/assets/13308314/13621802/99b23dc6-e5dd-11e5-8d67-1f018a8b281d.png">

Thanks!

**Comment by en90choi** [comment]
@bergquist Hi, i am a friend of @tuyy. 
![image](https://cloud.githubusercontent.com/assets/13308248/13622011/e702c8ce-e5de-11e5-8656-55b5d8c7d1ab.png)
i got window.localStorage["dashboard_impressions"] value.
check the screenshot please.
thanks.

**Comment by tuyy** [comment]
Hi , brother
I try re-latest version build..

and Success this problem!

Thanks.
