### ISSUE TITLE
Allow update of dashboard only to specific user/users

### ISSUE THREAD

**Issue by zdenekpizl** [grafana/grafana#429]
Hallo,

 I wonder if there is any way how to achieve following scenario:

- authenticated user has created a dashboard and save it
- this dashboard is available for all authenticated users but only defined group of users can save consequent changes of this dashboard back to system

Let's say there is small number of users or groups of users. Is it possible to shard dashboards according to user's membership to a group but still allow to search through all of them?

Thank you, regards .zp.

**Comment by elprofesor78** [comment]
Do you have a status of this feature ? Thank you.

**Comment by jedblack** [comment]
We could use this as well +1

**Comment by torkelo** [comment]
This is coming in Grafana 2.0 (that comes with an optional backend)

**Comment by jeromegit** [comment]
+1 on this one too.
is there an ETA for 2.0?

**Comment by torkelo** [comment]
@jeromegit yes, the code/alpha should be made public within a week or week and a half. Beta by end of February I hope.

**Comment by jeromegit** [comment]
Thanks Torkelo.
Look forward to it!

**Comment by jeromegit** [comment]
Thanks Torkelo!
I have been enjoying 2.0 but I have an issue/concern. I'll create a new issue ticket.
