### ISSUE TITLE
Bar chart overlaping numbers

### ISSUE THREAD

**Issue by zapi7557** [grafana/grafana#42905]
Hey guys,
![Screenshot_8](https://user-images.githubusercontent.com/26165632/145351199-ce1f0460-1c9a-4b40-af7a-d52a4c772b36.png)

How to fix overlaping numbers in bar chart, data source used Infinity, Grafana version 8.1.7. Is there a way to fit numbers inside bars?

**Comment by ashharrison90** [comment]
can repro pretty easily with csv test data of:
```
title,b,c,d
"wow",2,3,4
"foo",5,6,1000
```

orientation -> horizontal
stacking -> normal

tbh i'm not sure how we'd fix this and handle all scenarios nicely 🤔

**Comment by codeincarnate** [comment]
I've been taking a look at this. We're currently using a uPlot hook to draw these labels. This will occur it pretty much any situation in which there's a high variance in the given data. The test data from the comment above recreates this nicely:

<img width="634" alt="Screen Shot 2022-01-28 at 4 10 49 PM" src="https://user-images.githubusercontent.com/199847/151628604-3f04e683-972d-432d-9d01-61d139ddb162.png">

I'm working through potential solutions at the moment. Some potential options:

- We can not show values in conditions where they would overlap (seems like tooltip would make more sense)
- Position values within bar segments
- Use lines to indicate which segments the values are for
- Some mix of the above

Seeing what can work right now and may get some UX feedback here as well.
