### ISSUE TITLE
bug: Time Series Graph does not correctly visualise millisecond data

### ISSUE THREAD

**Issue by dsmanl** [grafana/grafana#42908]
**What happened**:

We are trying to visualise time series data with millisecond precision. It seems that the `Time Series` graph ignores/ cuts off the milliseconds. When we are using the old `Graph panel (old)` the data is visualised as expected. However, the labelling/ resolution of the time axis seems to be more appropriate on the `Time Series` graph.

![time_series_graph](https://user-images.githubusercontent.com/67360039/145362566-7d8d42b5-83d6-4bf5-8ea3-f98e85465a80.gif)

**What you expected to happen**:

We expect to be able to visualise time series data where milliseconds are resolved correctly (e.g. like in the old `Graph panel (old)`).

**How to reproduce it (as minimally and precisely as possible)**:

The following SQL statement can be used in the `PostgreSQL` datasource to create a minimum working example. In order to reproduce the problem, one has to select the `Time Series` graph.

```sql
SELECT
    time, value
FROM
    (
        SELECT '2021-12-09T08:00:01Z'::timestamp AS time, 10 AS value
        UNION
        SELECT '2021-12-09T08:00:01.250Z'::timestamp AS time, 15 AS value
        UNION
        SELECT '2021-12-09T08:00:01.500Z'::timestamp AS time, 5 AS value
        UNION
        SELECT '2021-12-09T08:00:01.750Z'::timestamp AS time, 7.5 AS value
        UNION
        SELECT '2021-12-09T08:00:02Z'::timestamp AS time, 15 AS value
    ) AS tmp
ORDER BY
    time
;
```

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: PostgreSQL
- OS Grafana is installed on: -, Grafana Docker Image
- User OS & Browser: macOS Big Sur 11.5.1, Chrome Version 96.0.4664.93 (Official Build) (x86_64)

Thanks a lot!

**Comment by ashharrison90** [comment]
hey @dsmanl 👋 

using your example query in 8.3.1 this seems to be fixed:
![image](https://user-images.githubusercontent.com/20999846/145378086-7b8bb217-65e5-4f5e-8a6c-490f482e6611.png)

can you try upgrading and see if that fixes your problem? if not, please leave a comment and we can reopen this.

thanks! 😄
