### ISSUE TITLE
Can not type tilde in Logql explorer

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#42910]
**What happened**:
When typing a logql query containing tilde, eg  `|~  "searchstring"`, after I've typed the tilde and press space, right before typing `searchstring`, the tilde disappears.
I've tried all kinds of tricks to work around it, nothing works.
* Pressing escape before pressing space, doesn't work.
* Type `searchstring` first and then insert the tilde in front of it.  Sortof works if you click "Run query" with your mouse after, but if you try to type anything else anywhere in the editor the tilde disappears again.
* Typing the full logql in a text editor and then pasting it into grafana. - This works but is an extra annoying step as you can imagine.

**What you expected to happen**:
Typing tilde has no special behavior in text editor, behaves like any normal text.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Keyboard layout is Swedish. So typing tilde requires some strange combination of Altgr+`~`, then space.

**Environment**:
- Grafana version: 8.3.1
- OS Grafana is installed on: Official grafana Docker image: grafana/grafana:8.3.1
- User OS & Browser: Ubuntu 21.04, Firefox 94.

**Comment by Elfo404** [comment]
closing this in favor of https://github.com/grafana/grafana/issues/43177 which has a few more details
