### ISSUE TITLE
String fields are converted to number even if they are not a number

### ISSUE THREAD

**Issue by Legion2** [grafana/grafana#42920]
**What happened**: I updated to Grafana 8.3.1 and now some table string values are converted to numbers and thereby change their value:
The value `0.58.0` is changed to `0.58`.
This only happens sometimes, I think if the first value in the series looks like a number (`1.0`).

**What you expected to happen**: Strings do not change their value, like in previous grafana versions.

**How to reproduce it (as minimally and precisely as possible)**: Have a series with a string field where the first value is `1.0` and the second is `1.2.3`

**Anything else we need to know?**: I think this is related to https://github.com/grafana/grafana/pull/41791, which guesses the field type based on the first non null value

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: influxdb 1.8
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Linux Chrome
- Grafana plugins:
- Others:

**Comment by rust84** [comment]
I think I am seeing the same issue with the Rook Ceph dashboards and others. 

![var](https://user-images.githubusercontent.com/23284108/145395573-e71cb917-fec3-4e17-bf89-e572ce7622c9.png)

![string](https://user-images.githubusercontent.com/23284108/145395659-919229fe-412e-487e-af89-ad70989598db.png)

**Comment by Legion2** [comment]
@rust84 I think your issue is this one https://github.com/grafana/grafana/issues/42605

**Comment by rust84** [comment]
That looks like it for me then thank you.

**Comment by ashharrison90** [comment]
hi @Legion2 👋 

just to clarify, are you talking about the actual table panel or the view shown when you enable `Table view` here?
![image](https://user-images.githubusercontent.com/20999846/145569759-5921e406-2cfd-4556-9e3b-c9cc6822131c.png)

**Comment by Legion2** [comment]
@ashharrison90 It happens in both views. Howerver, in the Table View number like strings are always converted to numbers. And the effects are combined in the Table View: `0.58.0` is converted to `0.58` in the Table panel and if I turn on the Table View it is converted to `0.580`. `21.11.2` is converted to `21.11` in Table panel and converted to `21.1` if I turn on Tabe View, but only if it was converted to `21.11` before. If I see `21.11.2` in the Table panel, it is also shown in the Table View as `21.11.2` .

**Comment by Legion2** [comment]
I think there are two independent transformations happening here, one is acting on the whole series if it thinks the series contains numbers, the second transformation is acting on the individual fields in the Table View and converts them to numbers if the output of the first transformation looks like a number.

**Comment by ashharrison90** [comment]
as an immediate workaround for the actual table, you should be able to force the unit to string in the config:

![image](https://user-images.githubusercontent.com/20999846/145573901-b1020dd4-5774-49b4-b702-7e748c3c4066.png)

**Comment by Legion2** [comment]
The workaround doesn't work, the strings are still converted to numbers even when the Unit is set to String.

**Comment by Legion2** [comment]
@ashharrison90 how can I create simple test data to create a repoducer, without an actual data source?

**Comment by ashharrison90** [comment]
@Legion2 sorry for the really slow reply. it was hackathon week here last week at Grafana so i was busy hacking code to pieces 🪓 

you can enable the test data source via the instructions here: https://grafana.com/docs/grafana/latest/datasources/testdata/

i've also created a repro dashboard here: https://play.grafana.org/d/0TAG1JTnz/42920-number-parsing?orgId=1
but as i mentioned, setting the unit to string fixes the table visualization. it **does not** fix the "table view" though. 

this is why i want to clarify where the bug actually is. i _think_ the table visualization is behaving correctly. it tries to parse things correctly. occasionally it gets stuff wrong, but you can always override that behaviour by specifying the unit. the "table view" behaviour looks like a bug though - i'm pretty sure that should always show the underlying data. 

what do you think?

**Comment by torkelo** [comment]
set unit to "string" to override the auto format as number behavior

**Comment by Legion2** [comment]
@ashharrison90 I can repoduce it on your test dashboard with an influxdb source, but I cannot save it, here is a screenshot with all the settings:
![image](https://user-images.githubusercontent.com/12752323/146968553-4e4f28fc-4315-453e-a3f1-fd8719a55c0c.png)
You can see that the values are converted to numberes (the string is converted to NaN) eventhough the type is set to string. I can only reprodce this in the influxdb source when using a selector(fist/last) and the first/last value of the series looks like a number.
