### ISSUE TITLE
Azure datasource: TypeError: i.default.interval_to_ms is not a function

### ISSUE THREAD

**Issue by jleloup** [grafana/grafana#42925]
**What happened**:

Since our update from Grafana 8.1.6 to 8.3.1 we can observe failures in dashboards using an Azure datasource: panels using such datasource with a `Time Grain` set to Auto crashes with this error: 

`i.default.interval_to_ms is not a function``

We can reproduce this in the Explore UI as shown in this screenshot: 

<img width="1354" alt="Screen Shot 2021-12-09 at 14 05 10" src="https://user-images.githubusercontent.com/20790125/145402781-81e02e4f-172c-49e9-88cd-d6c8ae141df9.png">

Switching to a fixed time interval prevents this issue from happening.

**What you expected to happen**:

* Explore UI and dashboards panels using Azure datasource with `Time Grain` set to Auto should work properly

**How to reproduce it (as minimally and precisely as possible)**:

* creating an Azure datasource
* use the Explore UI to create any sort of query while also using `Time Grain` as Auto

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Azure
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for creating this issue. 

@jleloup are you sure you're on the 8.3.1? Looking at the screenshot you've added, it looks like you're using an older version of the plugin that was only available prior to grafana 8.0.

**Comment by sunker** [comment]
@MrBeanzy what version are you on? For me this is working as expected using the latest main of Grafana.

![units](https://user-images.githubusercontent.com/2388950/146198464-8cea7325-1e4f-42d3-8f4a-a44d31847f3d.gif)

**Comment by jleloup** [comment]
> Thanks for creating this issue.
> 
> @jleloup are you sure you're on the 8.3.1? Looking at the screenshot you've added, it looks like you're using an older version of the plugin that was only available prior to grafana 8.0.
> 
> > We are seeing the same issue. Also appears that the units are no longer coming through for the metrics. So its defaulting everything to a percentage
> 
> Possibly there's been a change in the API. I'll investigate this.

I double checked, I confirm that I am using Grafana 8.3.1:

<img width="214" alt="Screen Shot 2021-12-15 at 18 20 41" src="https://user-images.githubusercontent.com/20790125/146234185-f445d430-9cc1-439d-8517-3ecec1136c54.png">

This instance is deployed using the Helm chart from https://github.com/grafana/helm-charts/tree/main/charts

**Comment by andresmgot** [comment]
@MrBeanzy @jleloup It turns out that the plugin that you can install from https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/?tab=installation is an older version of the Azure plugin that you get by default with Grafana as a core plugin. In Grafana 8.3, the external plugin is being used instead. To fix the issue, uninstall the external plugin. 

```
grafana-cli plugins remove grafana-azure-monitor-datasource
```

should do the trick (or remove it through the UI).

Please, reopen this issue if you still find this issue.

**Comment by MrBeanzy** [comment]
> @MrBeanzy @jleloup It turns out that the plugin that you can install from https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/?tab=installation is an older version of the Azure plugin that you get by default with Grafana as a core plugin. In Grafana 8.3, the external plugin is being used instead. To fix the issue, uninstall the external plugin.
> 
> ```
> grafana-cli plugins remove grafana-azure-monitor-datasource
> ```
> 
> should do the trick (or remove it through the UI).
> 
> Please, reopen this issue if you still find this problem after removing the plugin.

Awesome thank you! Saved me a load of hassle!

**Comment by frankvaneykelen-work** [comment]
> @MrBeanzy @jleloup It turns out that the plugin that you can install from https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/?tab=installation is an older version of the Azure plugin that you get by default with Grafana as a core plugin. In Grafana 8.3, the external plugin is being used instead. To fix the issue, uninstall the external plugin.
> 
> ```
> grafana-cli plugins remove grafana-azure-monitor-datasource
> ```
> 
> should do the trick (or remove it through the UI).
> 
> Please, reopen this issue if you still find this problem after removing the plugin.

That didn't work for us - after uninstalling the plugin the Azure Monitor is no longer available as a data source - the existing Azure Monitor data source complain about a missing plugin:
![image](https://user-images.githubusercontent.com/84066324/154682209-0514b2e5-e8bd-48d3-9221-e5ad2961176a.png)

And when adding a new data source Azure Monitor is not listed:
![image](https://user-images.githubusercontent.com/84066324/154682579-3aaa07da-ea6a-43be-8cb8-3c887195025b.png)

We're on Grafana v8.3.2 (8ad64b76ca) hosted by Aiven.

Does it maybe require a restart?

**Comment by frankvaneykelen-work** [comment]
> mmh, the Azure monitor datasource should be installed by default as a core plugin (and cannot be uninstalled). Maybe the solution by Aiven modifies the source code to remove core plugins?

That might indeed be the case - in the list of core data sources it is missing:
![image](https://user-images.githubusercontent.com/84066324/154688026-94ad77f4-d1a7-4764-88c0-c226da4f02ce.png)
Is Azure Monitor normally in that overview?

**Comment by frankvaneykelen-work** [comment]
Yes, it's missing all right:
![image](https://user-images.githubusercontent.com/84066324/154703119-b3494e54-f25b-466a-a906-2accbcad4d32.png)
I'm now waiting for Aiven support to help me with this. I'll post any resolution in this thread.

**Comment by frankvaneykelen-work** [comment]
FYI: the core Azure Monitor has been made available by Aiven on our Grafana via a temporary workaround:

> The long-term fix has not yet been ironed out but we have a temporary workaround we can apply to the running node, ie. simply remove the deprecated plugin and restart Grafana. This should make the core version appear again, but you may possibly need to recreate the data source.
> This kind of workaround is transient and does not persist over node redeployment, such as when maintenance updates are applied, but we hope to get the proper fix out soon too.
> If this is alright with you, we can perform the mitigation now.
