### ISSUE TITLE
MySQL Overview Dashboard - Metric request error - Grafana 8.3.1

### ISSUE THREAD

**Issue by mhollstein** [grafana/grafana#42936]
**What happened**: After Update to Grafana 8.3.1 the MySQL Overview Dashboard doesn't work.

**What you expected to happen**: The MySQL Overview Dashboard works as in Grafana 8.2.1 (it works till 8.2.7)

**How to reproduce it (as minimally and precisely as possible)**: Update to Grafana 8.3.0 as minimum and use the
MySQL Overview Dashboard  https://grafana.com/grafana/dashboards/9623
You see the error after the update once you reload the Dashbord in browser

**Anything else we need to know?**: it seeems that the query url is broken

**# 8.2.1**
Object
request:Object
url:"api/datasources/proxy/2/api/v1/query_range?query=rate(mysql_global_status_queries%7Binstance%3D%22localhost%3A9104%22%7D%5B5m%5D)%20or%20irate(mysql_global_status_queries%7Binstance%3D%22localhost%3A9104%22%7D%5B5m%5D)&start=1639014600&end=1639057800&step=300"
method:"GET"
...
result:Array[1]
0:Object
metric:Object
instance:"localhost:9104"
job:"mysqld_exporter"
values:Array[103]
0:Array[1639027200,0.4703522875665654]
1:Array[1639027500,0.8]
2:Array[1639027800,0.8035115912687415]
...

**# 8.3.1**
Object
request:Object
**url:"api/ds/query"**
method:"POST"
...
response:Object
message:"**Metric request error**"

**Environment**:
- Grafana version: 8.3.1
- Data source type & version:  Prometheus 2.31.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Ubuntu 16.04 Browser: Firefox 88.0 64 Bit
- Grafana plugins: 
grafana-clock-panel
grafana-image-renderer
grafana-piechart-panel
grafana-simple-json-datasource
grafana-singlestat-panel
jdbranham-diagram-panel
monitoringartist-monitoringart-datasource
natel-discrete-panel
natel-plotly-panel
novalabs-annotations-panel
radensolutions-netxms-datasource
ryantxu-ajax-panel
savantly-heatmap-panel
vonage-status-panel

- Others:

**Comment by zoltan-fedor** [comment]
Same here, also after upgrade from 8.2.1 to 8.3.1

**Comment by pgporada** [comment]
Same here.

**Comment by torkelo** [comment]
could maybe be fixed by https://github.com/grafana/grafana/pull/42927 , any errors in grafaa server log ?

**Comment by ivanahuckova** [comment]
Hello @mhollstein and thank you so much for bringing this up! I looked at the **MySQL Overview Dashboard** JSON ad I think that this is the same issue as the issue that was fixed in [Prometheus: Fix interpolation of template variables in interval](https://github.com/grafana/grafana/pull/42637). The fix was merged and will be part of the next patch release. 

Just to make sure, would you mind sharing the Query infor from Query Inspector. Something like this to see what is the format of query and what could have gone wrong: 
![image](https://user-images.githubusercontent.com/30407135/145574678-6cadadc5-6f72-4b45-ab30-6899b6958ed0.png)

**Comment by mhollstein** [comment]
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "calculatedInterval": "10m",
          "datasourceErrors": {},
          "errors": {},
          "expr": "rate(mysql_global_status_queries{instance=\"localhost:9104\"}[5m]) or irate(mysql_global_status_queries{instance=\"localhost:9104\"}[5m])",
          "format": "time_series",
          "interval": "$interval",
          "intervalFactor": 1,
          "legendFormat": "",
          "metric": "",
          "refId": "A",
          "step": 20,
          "datasource": {
            "uid": "000000002",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "exemplar": false,
          "requestId": "13A",
          "utcOffsetSec": 3600,
          "datasourceId": 2,
          "intervalMs": 300000,
          "maxDataPoints": 100
        }
      ],
      "range": {
        "from": "2021-12-10T01:00:28.953Z",
        "to": "2021-12-10T13:00:28.956Z",
        "raw": {
          "from": "now-12h",
          "to": "now"
        }
      },
      "from": "1639098028953",
      "to": "1639141228956"
    },
    "hideFromInspector": false
  },
  "response": {
    "message": "Metric request error"
  }
}`

**Comment by mhollstein** [comment]
Another Panel:
![image](https://user-images.githubusercontent.com/56024424/145578713-aca88ec9-0e1b-46d0-969d-10d939ddf58b.png)
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "calculatedInterval": "2m",
          "datasourceErrors": {},
          "errors": {},
          "expr": "max(max_over_time(mysql_global_status_threads_connected{instance=\"localhost:9104\"}[5m])  or mysql_global_status_threads_connected{instance=\"localhost:9104\"} )",
          "format": "time_series",
          "interval": "$interval",
          "intervalFactor": 1,
          "legendFormat": "Connections",
          "metric": "",
          "refId": "A",
          "step": 20,
          "datasource": {
            "uid": "000000002",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "exemplar": false,
          "requestId": "92A",
          "utcOffsetSec": 3600,
          "datasourceId": 2,
          "intervalMs": 20000,
          "maxDataPoints": 1869
        },
        {
          "calculatedInterval": "2m",
          "datasourceErrors": {},
          "errors": {},
          "expr": "mysql_global_status_max_used_connections{instance=\"localhost:9104\"}",
          "format": "time_series",
          "interval": "$interval",
          "intervalFactor": 1,
          "legendFormat": "Max Used Connections",
          "metric": "",
          "refId": "C",
          "step": 20,
          "target": "",
          "datasource": {
            "uid": "000000002",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "exemplar": false,
          "requestId": "92C",
          "utcOffsetSec": 3600,
          "datasourceId": 2,
          "intervalMs": 20000,
          "maxDataPoints": 1869
        },
        {
          "calculatedInterval": "2m",
          "datasourceErrors": {},
          "errors": {},
          "expr": "mysql_global_variables_max_connections{instance=\"localhost:9104\"}",
          "format": "time_series",
          "interval": "$interval",
          "intervalFactor": 1,
          "legendFormat": "Max Connections",
          "metric": "",
          "refId": "B",
          "step": 20,
          "target": "",
          "datasource": {
            "uid": "000000002",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "exemplar": false,
          "requestId": "92B",
          "utcOffsetSec": 3600,
          "datasourceId": 2,
          "intervalMs": 20000,
          "maxDataPoints": 1869
        }
      ],
      "range": {
        "from": "2021-12-10T01:06:16.507Z",
        "to": "2021-12-10T13:06:16.507Z",
        "raw": {
          "from": "now-12h",
          "to": "now"
        }
      },
      "from": "1639098376507",
      "to": "1639141576507"
    },
    "hideFromInspector": false
  },
  "response": {
    "message": "Metric request error"
  }
}`

**Comment by mhollstein** [comment]
This panel works
![image](https://user-images.githubusercontent.com/56024424/145579342-45c2fcae-61b4-4879-8f20-6aed138ef122.png)
`{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "calculatedInterval": "10m",
          "datasourceErrors": {},
          "errors": {},
          "expr": "mysql_global_status_uptime{instance=\"localhost:9104\"}",
          "format": "time_series",
          "interval": "5m",
          "intervalFactor": 1,
          "legendFormat": "",
          "metric": "",
          "refId": "A",
          "step": 300,
          "datasource": {
            "uid": "000000002",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "exemplar": false,
          "requestId": "12A",
          "utcOffsetSec": 3600,
          "datasourceId": 2,
          "intervalMs": 300000,
          "maxDataPoints": 100
        }
      ],
      "range": {
        "from": "2021-12-10T01:11:40.781Z",
        "to": "2021-12-10T13:11:40.781Z",
        "raw": {
          "from": "now-12h",
          "to": "now"
        }
      },
      "from": "1639098700781",
      "to": "1639141900781"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "name": "mysql_global_status_uptime{instance=\"localhost:9104\", job=\"mysqld_exporter\"}",
              "refId": "A",
              "meta": {
                "custom": {
                  "resultType": "matrix"
                }
              },
              "fields": [
                {
                  "name": "Time",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time"
                  }
                },
                {
                  "name": "Value",
                  "type": "number",
                  "typeInfo": {
                    "frame": "float64",
                    "nullable": true
                  },
                  "labels": {
                    "__name__": "mysql_global_status_uptime",
                    "instance": "localhost:9104",
                    "job": "mysqld_exporter"
                  },
                  "config": {
                    "displayNameFromDS": "mysql_global_status_uptime{instance=\"localhost:9104\", job=\"mysqld_exporter\"}"
                  }
                }
              ]
            },
            "data": {
              "values": [
                [
                  1639141200000,
                  1639141500000,
                  1639141800000
                ],
                [
                  233,
                  533,
                  833
                ]
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}`
Query: mysql_global_status_uptime{instance="$host"}

**Comment by mhollstein** [comment]
After a refresh in query inspector in panel "Current QPS" I get this message in the log:

t=2021-12-10T14:19:26+0100 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="failed to query data: time: **invalid duration \"$interval\"**" remote_addr=127.0.0.1
t=2021-12-10T14:19:26+0100 lvl=eror msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=500 remote_addr=127.0.0.1 time_ms=65 size=34 referer="http://127.0.0.1:3000/d/hlP72bh7z/mysql-overview-original?orgId=1&editPanel=13&inspect=13&inspectTab=query"

**Comment by mhollstein** [comment]
I found out: if I copy query A, create new query B and copy the same content in query B, disable query A, then it works.

![image](https://user-images.githubusercontent.com/56024424/145582033-cba5cfd6-593f-4b5f-a918-d8088d8302f4.png)

**Comment by pgporada** [comment]
@mhollstein You're not putting `$interval` into query B `Min step` field which is why query B is working. Hopefully the linked PR from @ivanahuckova  will be available in Grafana v8.3.3. I'm affected by this too.

**Comment by davidnewhall** [comment]
I'm also dealing with broken panels because the `Min step` input is no longer interpolating custom variables on Prometheus datasources.

**Comment by ivanahuckova** [comment]
Thank you for confirmation. 🧡 This has been fixed in https://github.com/grafana/grafana/pull/42637 and will be part of the next patch release.
