### ISSUE TITLE
Datasource Google Cloud Monitoring incorrectly deduplicates metrics names

### ISSUE THREAD

**Issue by tw1nk** [grafana/grafana#42931]
Google Cloud Monitoring have a lot of duplicated metric names under the same Service and the UI incorrectly deduplicates these which can make it impossible to choose the exact one you want. 

Example:
```json
{
      "valueType": "DOUBLE",
      "metricKind": "CUMULATIVE",
      "type": "kubernetes.io/anthos/container/cpu/core_usage_time",
      "unit": "s{CPU}",
      "service": "kubernetes.io",
      "serviceShortName": "kubernetes",
      "displayName": "CPU usage time",
      "description": "Cumulative CPU usage on all cores used by the container in seconds."
}, {
      "valueType": "DOUBLE",
      "metricKind": "CUMULATIVE",
      "type": "kubernetes.io/container/cpu/core_usage_time",
      "unit": "s{CPU}",
      "service": "kubernetes.io",
      "serviceShortName": "kubernetes",
      "displayName": "CPU usage time",
      "description": "Cumulative CPU usage on all cores used by the container in seconds."
},
```

These two metrics are completely different but one of them is randomly removed from the UI, which I think is caused by google cloud monitoring metrics descriptors api call doesn't return data sorted. This causes further confusion as you might have data on one of the metrics but not the others and when you use the explore data can just disappear.

I did a quick hack in https://github.com/grafana/grafana/blob/2655be61b6dbf548282f3370c74339152cec2e29/pkg/tsdb/cloudmonitoring/resource_handler.go#L94-L95

```go
		typeParts := strings.SplitN(resp.Descriptors[i].Type, "/", 3)
		resp.Descriptors[i].Service = typeParts[0] + "/" + typeParts[1]
		resp.Descriptors[i].ServiceShortName = strings.SplitN(resp.Descriptors[i].Service, ".", 2)[0] + " (" + typeParts[1] + ")"
```
to verify the issue and a possible fix

**Comment by sunker** [comment]
Thanks for creating this issue @tw1nk! 

Would you like to create a PR with your fix?

**Comment by sunker** [comment]
Would probably be more useful to show metric type name (e.g `kubernetes.io/container/cpu/core_usage_time`) in the select option description instead of showing the metric description. Select option description for the metric picker is set [here](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloud-monitoring/components/Metrics.tsx#L64). 

![Screenshot from 2021-12-14 13-41-46](https://user-images.githubusercontent.com/2388950/146000485-a638b9d5-5f98-47af-870c-41979e4276b1.png)

**Comment by tw1nk** [comment]
Sure. I could take a look at it. 

The current description is good to have as it describes what is measured, and I think it would be great to visualize the metric type name as you did here as well. 

But I also think splitting up into more services like 
![image](https://user-images.githubusercontent.com/67468/146147876-8c591e65-2024-43dc-81c8-9e0ba16bbf6b.png) would improve usability as there would be less options in the metric name drop down.

**Comment by sunker** [comment]
I think that looks great. Although currently undocumented, there's a template variable query for loading _Services_. 
![Screenshot from 2021-12-15 09-45-10](https://user-images.githubusercontent.com/2388950/146153323-f730754b-b16d-4df9-8106-c5755bc8d31f.png)

I think this variable is quite unusable, but if one has saved a variable with the value `Kubernetes`, the change that you're suggesting will be a breaking change, which is not ideal for a minor release. However, I'll try to come up with a migration for this. If that's not possible to do, I think it's fine to introduce a breaking change. 

Ping me once you need a review for the PR. Thanks!

**Comment by tw1nk** [comment]
Unfortunately it seems the grafana UI is built in some arcane framework / language and I can't figure out how to add new row to the description as changing it to this

```tsx  
const metricsByService = metricDescriptors
        .filter((m) => m.service === selectedMetricDescriptor.service)
        .map((m) => ({
          service: m.service,
          value: m.type,
          label: m.displayName,
          description: m.type + '\n' + m.description,
        }));```

or with `<br>` instead of `\n` didn't yield the expected result.

**Comment by sunker** [comment]
Think you should be able to set [white-space](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Select/getSelectStyles.ts#L43) to `pre` to allow lines to be broken on new line characters.

**Comment by sunker** [comment]
pre-wrap is probably better so that lines are wrapped and not overflown

**Comment by tw1nk** [comment]
![image](https://user-images.githubusercontent.com/67468/146383694-e6fb8734-b269-4d19-b6a9-bf16275ad5fa.png)

That was a lot more complex than I thought it would be. 
I'm going to clean it up a bit and open a PR
