### ISSUE TITLE
Feature Request: Time Paging

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#4293]
I find myself wanting to scroll backwards through time at a certain interval. So for example, lets say I'm viewing a week. I would find it very helpful to have shortcuts that let me page back and forwards in weeks without having to do a custom time.

This would allow me to "browse" graphs across time without downsampling or creating too much data for the DOM.

**Comment by digrich** [comment]
+1

**Comment by evanbreznyik** [comment]
:+1:

Would also be nice to automatically jump back by multiples of the epoch currently in use.  For example, if you use "last 3 hours" and you want to page forward/backward, the time should just shit in offsets/steps of 3 hours (much like OP says, but with weeks).

**Comment by grobie** [comment]
Duplicate of https://github.com/grafana/grafana/issues/119.

**Comment by bergquist** [comment]
closing this since its a dupe. 
Feel free to reopen if you disagree
