### ISSUE TITLE
All panels empty after update from 8.2.5 -> 8.3.1

### ISSUE THREAD

**Issue by nilsschuette1234** [grafana/grafana#42940]
**What happened**:
Updated Grafana 8.2.5 to 8.3.1.
Almost all panels from our via json-files provisioned dashboards are empty and don't show any data.
After one clicks on edit of a panel the data is shown again.

**What you expected to happen**:
Showing all provisioned dashboards as before the update

**How to reproduce it (as minimally and precisely as possible)**:
Provision a dashboard with plugin versions 8.2.5 with grafana 8.3.1

**Anything else we need to know?**:

**Environment**:
Docker bitnami/grafana on AWS/Fargate

- Grafana version: 
8.2.5 -> 8.3.1

- Data source type & version:
cloudwatch

- OS Grafana is installed on:
debian

- User OS & Browser:
Ubuntu + Chrome

First panel is empty:

![Screenshot from 2021-12-09 16-29-24](https://user-images.githubusercontent.com/71640855/145428693-df049abb-0b8b-48bb-bf0e-e711db6fd514.png)

After clicking "edit" the data is loaded again:

![Screenshot from 2021-12-09 16-29-56](https://user-images.githubusercontent.com/71640855/145428691-ace925e6-22f8-45cd-b3fe-c48c354e3cf8.png)

compairing the generated json from before and after hitting "edit", these are the major changes one can see:

![Screenshot from 2021-12-09 16-52-58](https://user-images.githubusercontent.com/71640855/145429854-a8b81ee7-2351-438e-8aed-7a9e7b12b21d.png)

**Comment by visit1985** [comment]
Can confirm. Affects all our provisioned dashboards as well

**Comment by visit1985** [comment]
Probably related to https://github.com/grafana/grafana/pull/33817

**Comment by torkelo** [comment]
Will be fixed in next patch release  https://github.com/grafana/grafana/pull/42611

**Comment by torkelo** [comment]
Apologize for this bug, need to be better at catching these issues! Sorry you had to downgrade
