### ISSUE TITLE
Docs feedback: /whatsnew/whats-new-in-v8-3.md images broken

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#42951]
Hi, the images for the Candlestick Panel and Grafana Alerting seem to be broken. They may need new links.

**Comment by GrafanaWriter** [comment]
Thanks @mjseaman, will take a look.

@achatterjee-grafana - Can you take a look at the image links and advise? 

The links are {{< figure src="/static/img/docs/alerting/alerting_8_0.png" max-width="1200px" caption="Grafana Alerting" >}} and {{< figure src="/static/img/docs/candlestick-panel/candlestick_panel_8_3.png" max-width="1200px" caption="Candlestick panel" >}}

Both images are there, but seem to be nested in another `static` directory? 

`/website/blob/master/static/static/img/docs/alerting/alerting_8_0.png` is where the alerting image is stored (same structure for the candlestick panel) and that second `static` directory is the only difference I can find.
