### ISSUE TITLE
can not complete `go run build.go setup`

### ISSUE THREAD

**Issue by GCwithH2O** [grafana/grafana#42961]
**What happened**:

can not complete `go run build.go setup`
```
pkg\cmd\grafana-server\commands\cli.go:170:12: undefined: server.Initialize
exit status 2
exit status 1
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.3.1
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by GCwithH2O** [comment]
https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md

**Comment by Chaklader** [comment]
I try to do it in the Ubuntu and ended up with the same error.
