### ISSUE TITLE
stack 100% in time series have to much bug

### ISSUE THREAD

**Issue by depfryer** [grafana/grafana#42962]
What happened:
i upgrade the old "graph" to "time serie" and obtain unusable graphic

![with grap](https://user-images.githubusercontent.com/17575141/145525932-e43c0747-e522-4bf4-bd9a-6195e6c47532.png)

![with time series](https://user-images.githubusercontent.com/17575141/145525928-802652a7-99a9-433a-8eb3-8665b5a11502.png)

also, the values ​​seem badly placed on the curve (we have the impression that the green curve is far from 50% while not at all)
old : ![old](https://user-images.githubusercontent.com/17575141/145526912-380a9659-d8ae-4835-a2b3-cd5e78cef392.png)
new : ![new](https://user-images.githubusercontent.com/17575141/145526970-1d1a0e7f-3029-46af-b41e-ca3f41314040.png)
blue line is a threesold for 50%

**What you expected to happen**:
return like the old, readable value (not in percent) with unit selected.

**How to reproduce it (as minimally and precisely as possible)**:
activate "100%" in "Stack series"

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: influxDB 1.8
- OS Grafana is installed on: docker
- User OS & Browser: windows, vivaldi
- Grafana plugins:

**Comment by ashharrison90** [comment]
hey @depfryer 👋 

thanks for raising this!

would it be possible for you to share your dashboard json? it really helps when trying to debug issues. thanks! 😄

**Comment by torkelo** [comment]
The blue thresholds looks to be at 70%

**Comment by depfryer** [comment]
I set it to 50

```json
{
  "id": 11,
  "gridPos": {
    "h": 10,
    "w": 15,
    "x": 9,
    "y": 7
  },
  "type": "graph",
  "title": "repartition HC/HP",
  "transformations": [],
  "thresholds": [
    {
      "$$hashKey": "object:83",
      "colorMode": "custom",
      "fill": false,
      "fillColor": "rgba(51, 162, 229, 0.2)",
      "line": true,
      "lineColor": "#1F60C4",
      "op": "lt",
      "value": 50,
      "yaxis": "left"
    }
  ],
  "pluginVersion": "8.3.1",
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "aliasColors": {},
  "bars": false,
  "dashLength": 10,
  "dashes": false,
  "description": "",
  "fieldConfig": {
    "defaults": {
      "unit": "watth"
    },
    "overrides": []
  },
  "fill": 1,
  "fillGradient": 0,
  "hiddenSeries": false,
  "lines": true,
  "linewidth": 1,
  "nullPointMode": "null",
  "options": {
    "alertThreshold": true
  },
  "percentage": true,
  "pointradius": 2,
  "points": false,
  "renderer": "flot",
  "seriesOverrides": [],
  "spaceLength": 10,
  "stack": true,
  "steppedLine": false,
  "targets": [
    {
      "alias": "heures creuses",
      "datasource": {
        "type": "influxdb",
        "uid": "DBhMZnVnk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "hide": false,
      "measurement": "consommationElectrique",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "select sum(used_wh ) as \"HC\" FROM \"consommationElectrique_global\" WHERE (\"HC\" = '1') AND $timeFilter \n\n group by time(1d) ",
      "rawQuery": true,
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "voltage_mv"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    },
    {
      "alias": "heures pleines",
      "datasource": {
        "type": "influxdb",
        "uid": "DBhMZnVnk"
      },
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
      "measurement": "consommationElectrique",
      "orderByTime": "ASC",
      "policy": "default",
      "query": "select sum(used_wh ) as \"HP\" FROM \"consommationElectrique_global\" WHERE (\"HC\" = '0') AND $timeFilter \n\n group by time(1d) ",
      "rawQuery": true,
      "refId": "B",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "voltage_mv"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "mean"
          }
        ]
      ],
      "tags": []
    }
  ],
  "timeRegions": [],
  "tooltip": {
    "shared": true,
    "sort": 0,
    "value_type": "individual"
  },
  "xaxis": {
    "mode": "time",
    "show": true,
    "values": [],
    "name": null,
    "buckets": null
  },
  "yaxes": [
    {
      "$$hashKey": "object:55",
      "format": "watth",
      "logBase": 1,
      "show": true
    },
    {
      "$$hashKey": "object:56",
      "format": "short",
      "logBase": 1,
      "show": true
    }
  ],
  "yaxis": {
    "align": false
  },
  "timeFrom": null,
  "timeShift": null,
  "datasource": null
}``

**Comment by depfryer** [comment]
any news ?

**Comment by dprokop** [comment]
@depfryer sorry for a late reply. Could you please share the data you are experiencing the issue with by sharing the [CSV from the Panel Inspect](https://grafana.com/docs/grafana/latest/panels/inspect-panel/)? 

Please make sure you share raw data - meanin the transformations and field configuration is not applied in the Data Options in Panel Inspect:
![image](https://user-images.githubusercontent.com/2376619/148228678-be5d7757-b597-4f27-b59e-6a1dd52fa817.png)


This would definitelly help us debug the threshold line, data accuracy issue you describe. Tho, I think the shreshold line is drawn correctly. It takes the lowest and the highest values and renders the threshold at 50% which in your data range scenario is somewhere around 70% (stacking percent).

See the graph below with two series of 1,1,1,... values and threshold at 50% - it renders the threshold line at 75% (stack value)

![image](https://user-images.githubusercontent.com/2376619/148230825-e811f569-a985-4188-9837-ec4406625f90.png)

The other issue about the values in the tooltip. This is definitely a bug caused by the fact that in % stacking mode the value is using percent unit rahter than the one configured by the user. We will try to fix this soon.

**Comment by depfryer** [comment]
[repartition HC_HP journaliere-data-as-seriestocolumns-2022-01-05 15_36_52.csv](https://github.com/grafana/grafana/files/7815598/repartition.HC_HP.journaliere-data-as-seriestocolumns-2022-01-05.15_36_52.csv)

![image](https://user-images.githubusercontent.com/17575141/148235223-61291b15-e6f3-4ca2-8892-f42d293a2773.png)


if i force the "min" here
![image](https://user-images.githubusercontent.com/17575141/148235735-e7c3601b-9424-436a-b4c7-a058a472d0fd.png)
the render is correct 
![image](https://user-images.githubusercontent.com/17575141/148235791-bffac8da-2f93-463e-af91-18809a511b85.png)

but... for me it's still incorrect, when i ask 50% i expect to have 50% no 70% because it's using a unknow min 

If i put an alert, the threshold would be 70% not 50% ?

**Comment by depfryer** [comment]
i just found this
![image](https://user-images.githubusercontent.com/17575141/148264821-f1ac9aba-ba4f-4b57-a9f4-275ec6f95cc2.png)
![image](https://user-images.githubusercontent.com/17575141/148265053-eed90aae-4724-4ea9-bbdf-1beacc8b0c7c.png)


VS  
![image](https://user-images.githubusercontent.com/17575141/148264924-f29a156b-bb92-4c24-a41f-c65212f627bf.png)
![image](https://user-images.githubusercontent.com/17575141/148265024-389f2dbc-bf1a-45fb-ab3c-5bef47f1078e.png)
