### ISSUE TITLE
Label is set on both Axis instead of only Y axis

### ISSUE THREAD

**Issue by gseroul** [grafana/grafana#42966]
**What happened**: I set "test" Label in a default time series => I can see this label for both Y and X axis

**What you expected to happen**: To see this label only on Y axis like in the doc

**How to reproduce it (as minimally and precisely as possible)**: just set a label on a time series

**Anything else we need to know?**: Maybe a 2nd Label field for X axis could be a good idea

**Environment**: using last grafana docker oss image
- Grafana version: v8.3.1 (b9eacd93e9)
- Data source type & version: PostgreSQL 12+
- OS Grafana is installed on: docker Alpine image
![grafana-screen](https://user-images.githubusercontent.com/1685233/145548217-6afc32a1-0e4a-4cc4-93fc-a1b3d99e7375.png)

- User OS & Browser: Windows and Firefox
- Grafana plugins: None (only default)
- Others:

**Comment by ashharrison90** [comment]
can repro in main

docs say [this should only set the label for the y axis](https://grafana.com/docs/grafana/next/visualizations/time-series/change-axis-display/#label)

**Comment by thomasbromkapsdata** [comment]
Same problem. Tried to mitigate it by using override but it is the same using override on the only query of the panel, even setting the axis to "left".
Environment: Grafana 8.3.4 , Datasource: InfluxDB, OS: Debian 11

**Comment by zoltanbedi** [comment]
Nice catch @gseroul. We need to update the doc for this. There was this feature that changed how the axis label behaves https://github.com/grafana/grafana/pull/41142
In order to only see the label under the x axis you need to create a field override for the time field with the Axis > Label option.

**Comment by buzzware** [comment]
This is crazy. Its still happening on the Bar Chart on 9.5.3.
I can't go to 10 without https://grafana.com/grafana/plugins/pgollangi-firestore-datasource supporting 10
