### ISSUE TITLE
The request header security configuration is incorrect.

### ISSUE THREAD

**Issue by sunfanwei** [grafana/grafana#42964]
Delete'unsafe-eval' from the content_security_policy_template. Visit Grafana The following error is reported:
core.js:4 Uncaught EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self' 'strict-dynamic' 'nonce-vJjwNVwr+5YntlS1C/o/nQ'".

    at eval (<anonymous>)
    at core.js:4
    at Object../node_modules/baron/src/core.js (core.js:5)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module../public/app/core/components/scroll/scroll.ts (scroll.ts:1)
    at __webpack_require__ (bootstrap:790)
    at fn (bootstrap:150)
    at Module../public/app/core/core.ts (core.ts:1)
    at __webpack_require__ (bootstrap:790)
(anonymous) @ core.js:4
./node_modules/baron/src/core.js @ core.js:5
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/core/components/scroll/scroll.ts @ scroll.ts:1
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/core/core.ts @ core.ts:1
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/features/panel/panel_ctrl.ts @ default~app.d1b16024567cb171e5be.js:116868
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/plugins/sdk.ts @ sdk.ts:1
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/features/plugins/plugin_loader.ts @ default~app.d1b16024567cb171e5be.js:120948
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/app.ts @ default~app.d1b16024567cb171e5be.js:70012
__webpack_require__ @ bootstrap:790
fn @ bootstrap:150
./public/app/index.ts @ index.ts:3
__webpack_require__ @ bootstrap:790
checkDeferredModules @ bootstrap:45
webpackJsonpCallback @ bootstrap:32
(anonymous) @ vendors~app.d1b16024567cb171e5be.js:1

Request header security issues exist when baron@3.0.3 is used.

**Comment by torkelo** [comment]
@sunfanwei what do you mean? Grafana currently requires unsafe eval, which is why it is in the default template

It's not only baron that requires is some other libs as well, we hope to have an option to disable support for old angular plugins in v9, then we could support no unsafe eval mode
