### ISSUE TITLE
Grafana 404s out trying to access rule data via Prometheus

### ISSUE THREAD

**Issue by korewaChino** [grafana/grafana#42963]
**What happened**:
I don't really know where I went wrong here, but it seems like Grafana still tries to use the ruler endpoint even with vanilla Prometheus, and thus errors out with a 404.

It tries to access `/api/ruler/<id>/api/v1/rules` and somehow fails with a 404.

![image](https://user-images.githubusercontent.com/38139192/145527296-1779f01a-06dc-479f-8faa-ef4a85f18f08.png)

**What you expected to happen**:
Grafana properly using `/api/v1/rules` to read the rule data
**How to reproduce it (as minimally and precisely as possible)**:
Set up a normal alertmanager and Prometheus configuration, then enable the Alerting UI option in the prometheus datasource.
![image](https://user-images.githubusercontent.com/38139192/145528512-d5e8ede7-3781-49b4-a2b1-35616278bbd3.png)

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: Prometheus 2.24.1 & Alertmanager 0.21.0
- OS Grafana is installed on: Fedora Linux 35 (Server)
- User OS & Browser: Fedora Linux 35 w/ Microsoft Edge
- Grafana plugins: Alertmanager

**Comment by gotjosh** [comment]
You can disable it via the "manage alerts via Alerting UI" radio button shown on the screenshot you posted. With that, we make it read-only.

**Comment by orlovmyk** [comment]
I fixed this by adding backend to my upstream in my nginx conf, now it looks like this. No need to disable it throw UI.

nginx.conf
```
error_log  /dev/stderr;
pid        /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events {
    worker_connections  4096;  ## Default: 1024
}

http {
  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
    '"$request" $body_bytes_sent "$http_referer" '
    '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   /dev/stderr  main;
  sendfile     on;
  tcp_nopush   on;

  upstream read {
    server loki-read:3100;
  }

  upstream write {
    server loki-write:3100;
  }

  upstream backend {
    server loki-backend:3100;
  }

  upstream cluster {
    server loki-read:3100;
    server loki-write:3100;
  }

  server {
    listen 80;
    listen 3100;

    location = /ring {
        proxy_pass       http://cluster$request_uri;
    }

    location = /memberlist {
        proxy_pass       http://cluster$request_uri;
    }

    location = /config {
        proxy_pass       http://cluster$request_uri;
    }

    location = /metrics {
        proxy_pass       http://cluster$request_uri;
    }

    location = /ready {
        proxy_pass       http://cluster$request_uri;
    }

    location = /loki/api/v1/push {
        proxy_pass       http://write$request_uri;
    }

    location = /loki/api/v1/delete {
        proxy_pass       http://write$request_uri;
    }

    location = /loki/api/v1/tail {
        proxy_pass       http://read$request_uri;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }

    location ~ /loki/api/.* {
        proxy_pass       http://read$request_uri;
    }

    location ~ /prometheus/api/.* {
        proxy_pass       http://backend$request_uri;
    }
  }
}

```
