### ISSUE TITLE
Alerting UI visible in panel configurations when Alerting has been disabled

### ISSUE THREAD

**Issue by ohmakai** [grafana/grafana#42998]
**What happened**:
Configurations for both classic alerting and new unified alerting have been disabled, but Alert tab persists on dashboard panel edit mode.
<img width="1264" alt="Screen Shot 2021-12-10 at 11 04 58 AM" src="https://user-images.githubusercontent.com/477793/145645541-ec533998-c42d-48ce-9dc2-e17b654d4db4.png">
<img width="1269" alt="Screen Shot 2021-12-10 at 11 04 20 AM" src="https://user-images.githubusercontent.com/477793/145645554-06b2a489-d756-48e7-8359-b529ad3f66e7.png">

Example configuration:
```
# Legacy Grafana alerting
export GF_ALERTING_ENABLED=false
# Grafana v8 unified alerting
export GF_UNIFIED_ALERTING_ENABLED=false
```

**What you expected to happen**:
Alert tab should not be visible when all alerting configurations are disabled.

**How to reproduce it (as minimally and precisely as possible)**:
- Disable alerting for both legacy and unified alerting. 
- Create/edit a dashboard panel
- An Alert tab will be present and actionable

**Anything else we need to know?**:
This looks to have been addressed previously in https://github.com/grafana/grafana/issues/25143, but I believe that was before v8 and possibly doesn't account for Unified alerts (just guessing).

**Environment**:
- Grafana version: Grafana v8.2.5
- Data source type & version: Graphite 1.1, Prometheus 5.0.0, CloudWatch 5.0.0, etc.
- OS Grafana is installed on: Alpine 3.14.3
- User OS & Browser: MacOS 11.6.1, Firefox Developer Edition 96.0b3
- Grafana plugins: N/A
- Others: N/A

**Comment by Elfo404** [comment]
I can also reproduce this on master with 

```
[unified_alerting]
enabled = false

[alerting]
enabled = false
```
