### ISSUE TITLE
Time series: Stack bar single tooltip showing zero values

### ISSUE THREAD

**Issue by luxuan0401** [grafana/grafana#42994]
**What happened**:
When hover over purple bar, the tooltip shows green legend with 0 value.
<img width="1218" alt="Screen Shot 2021-12-10 at 10 39 01 AM" src="https://user-images.githubusercontent.com/2644564/145625200-fae7f5e2-7b3c-4de6-b13e-85435c1d2c79.png">

And when I change the tooltip to `all`, you will see the purple legend has 1 as value.
<img width="1213" alt="Screen Shot 2021-12-10 at 10 39 19 AM" src="https://user-images.githubusercontent.com/2644564/145625442-a1e13498-db0b-40df-a5a5-411055e5dee1.png">

**What you expected to happen**:
When hover over purple bar, the tooltip shows purple legend with 1 value.

I expected similar behavior as the tooltip in the `Old graph` type shown as below:
<img width="1213" alt="Screen Shot 2021-12-10 at 10 45 26 AM" src="https://user-images.githubusercontent.com/2644564/145625705-2012c5d7-1a30-4544-9212-2f6508ec24fc.png">

**How to reproduce it (as minimally and precisely as possible)**:
Create a time series graph with graph style as `Bars`, tooltip mode as `Single` and stack series as `Normal`.
Graph configs:
<img width="264" alt="Screen Shot 2021-12-10 at 10 49 50 AM" src="https://user-images.githubusercontent.com/2644564/145626202-7ded5e1d-3be4-41fd-aef8-fbe40fb74281.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.1
- Data source type & version: Prometheus 
- OS Grafana is installed on: linux
- User OS & Browser: mac os and chrome
- Grafana plugins: none
- Others:

**Comment by Elfo404** [comment]
The issue here is that your last series (the dark green one) has a 0 value, which places the popover trigger on top of the previous series (in your case the purple one). this In turn makes it impossible to "hover" the "purple series" (which is now triggered based on proximity to the data point, not the bar itself).

looping in @grafana/grafana-bi-squad

**Comment by luxuan0401** [comment]
If we can support disabling the "hover triggered based on proximity to the data point" feature, that would be great. The old graph's hovering only on bar is sufficient for our use case.

**Comment by Darth-Bobo** [comment]
Any news on this?  The behaviour is an even bigger pain where data is sparse so the tip that pops up could even be for a value that wasn't recorded in the time slot.

I'm seeing this behaviour in 8.5.6 and 9.0.2.

**Comment by codeincarnate** [comment]
BI Squad was able to reproduce it. In this case it's possible to have multiple points in the same location and in that situation only a single data point will be shown when hovered. A possible solution would be to do a distance calculation between points and show multiple values in the tooltip if they're clustered closely enough. That being said it doesn't seem like this is a widespread issue, but if anyone is experiencing this please feel free to chime in here.

**Comment by amarant** [comment]
Same problem here, when we hover the blue serie it shows the red one, so it is not really usable, even worse when there is a serie with a very small value.

<details>
  <summary>Click me</summary>
  
  ### Heading
  1. Foo
  2. Bar
     * Baz
     * Qux

  ### Some Code
  ```json
{
  "annotations": {
    "list": []
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 44,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "Xh_IcBeGk"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisCenteredZero": false,
            "axisColorMode": "text",
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "bars",
            "fillOpacity": 100,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "normal"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom",
          "showLegend": true
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "Xh_IcBeGk"
          },
          "decimalSeparator": ".",
          "delimiter": ",",
          "header": true,
          "ignoreUnknown": false,
          "refId": "A",
          "scenarioId": "random_walk",
          "schema": [
            {
              "name": "",
              "type": "string"
            }
          ],
          "seriesCount": 10,
          "skipRows": 0
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "refresh": false,
  "schemaVersion": 37,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2022-11-09T21:26:42.893Z",
    "to": "2022-11-09T21:26:42.921Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "test",
  "uid": "775WWbDVk",
  "version": 1,
  "weekStart": ""
}
  ```
</details>


![image](https://user-images.githubusercontent.com/2281471/201388954-bbec68ee-2ba4-4701-b8b7-ed8d9f794efa.png)

**Comment by shmyer** [comment]
This is also the case when using Lines instead of Bars and "Stack series" set to normal. I'd expect the single tooltip to show the value for the line's area i'm hovering but it shows the value of the nearest point on the line.

**Comment by nmarrs** [comment]
Review http://localhost:3000/d/1KxMUdE7k/timeseries-and-barchart-stacking?orgId=1 to look into addressing this (Stack 100% / Mixed Styles)

**Comment by nmarrs** [comment]
Current behavior - this seems to be better than it used to be but we should change proximity to be infinity when in bar style



https://github.com/grafana/grafana/assets/22381771/1ba51f3b-ef87-4d54-9827-8df314e79bfb
