### ISSUE TITLE
Question: Help setting up Value groups/tags

### ISSUE THREAD

**Issue by rdzimmer** [grafana/grafana#4299]
I am new to Grafana but really like what I see so far.  I am using Grafana 2.6.0 with InfluxDB 0.9.3 to monitor my Kubernetes environment.  
I have setup some templates and graphs, but I'm having trouble with the 'Value groups/tags', specifically the 'Tag values query'.  All of the online references I see online have a slightly different UI format when building templates, for example http://docs.grafana.org/reference/templating/.  I've pasted a screenshot of what I'm trying below.  
I'm currently trying to get any group/tag combination to work, so I've simplified my queries to try to get any group tags to work.  I can see all of my pods in the group tags when I use the 'Tags query' 'SHOW TAG VALUES FROM "uptime" WITH KEY = "pod_name"'.  However, when I select the tags it does not show anything.  I am trying a 'Tag values query' of 'SHOW TAG VALUES FROM "uptime" WITH KEY = "pod_name" WHERE "pod_name" = $tag'.  I've also tried just '$tag' or hard coding in a pod name.  
Any suggestions would be greatly appreciated, thanks!

![templating](https://cloud.githubusercontent.com/assets/17729406/13611600/607aa5f4-e531-11e5-8527-3e674db1ff42.PNG)

**Comment by torkelo** [comment]
Tags query should be SHOW TAGS

**Comment by AlexMaksimkin** [comment]
Also have a problem with this two queries. My tags/tag_values queries are same as on picture above. Setup with InfluxDB v0.10, Grafana v2.6.0.

![grafana](https://cloud.githubusercontent.com/assets/3739584/14487806/642ce06a-016d-11e6-9af7-09765e857475.png)

Both queries worked in InfluxDB and returned expected results (first - list of tags, second - list of hosts for specific tag), but in Grafana reaction on checkbox/clicking on tag is silence.

Also I see in browser debugger that Grafana do query when I click on tags and receive valid response:
![grafana2](https://cloud.githubusercontent.com/assets/3739584/14488209/9d9cea28-016f-11e6-9f88-eb3eafd51f61.png)

Regarding @torkelo recommendation I tried to change "Tags query" to "SHOW TAGS", but then I see an error: 

"Template variables could not be initialized: error parsing query: found TAGS, expected CONTINUOUS, DATABASES, DIAGNOSTICS, FIELD, GRANTS, MEASUREMENTS, RETENTION, SERIES, SERVERS, SHARD, SHARDS, STATS, SUBSCRIPTIONS, TAG, USERS at line 1, char 6"

What I do wrong? :)
Thanks!

**Comment by torkelo** [comment]
the tag values query should return values that are a subset of the main values query? Are they? 

I mean if you have a main query like:
show tag values with key = hostname

tag query:
show tag values with key = datacenter

tag values query:
show tag values with key = hostname WHERE datacenter=$tag


something like the above meaning the tag values query should return a subset of the main query

**Comment by torkelo** [comment]
@AlexMaksimkin this strange, just tested this and it worked fine. 
http://play.grafana.org/dashboard/db/templating-value-groups

**Comment by hoalequang** [comment]
Hi @torkelo ,
I have same issue when use grafana 4.0 and influxdb v0.13.0. and I see it did not worked in http://play.grafana.org/dashboard/db/templating-value-groups

**Comment by miketwenty1** [comment]
+1 
I'm also using grafana 4.  Having issues.  I also see your link:
http://play.grafana.org/dashboard/db/templating-value-groups
Doesn't seem to have grouping tags working as expected.

**Comment by Bklyn** [comment]
@torkelo I believe @hoalequang is correct.  This feature seems to have regressed.  If I go to the templating-value-groups test dashboard, I see two tags available "America" and "Europe".  Each tag has a tooltip that indicates which hosts belong to the region, but if I click one of the tags, I simply get a popup menu for selecting individual hostnames / IPs.  The tags then disappear, never to return.

**Comment by Bklyn** [comment]
This seems to be a case of #6752

**Comment by tlintz** [comment]
The case/example above only worked for me after I used regex.
e.g: SHOW TAG VALUES FROM redis WITH KEY = "host" WHERE services =~ /.*$tag.*/

**Comment by alphacr** [comment]
Hi guys, i have a similar problem that I need help in, if anyone could help me on https://community.grafana.com/t/how-to-set-up-the-custom-tags-for-multi-value-in-grafana/15495 or
 https://github.com/influxdata/influxdb/issues/12809, it would be much appreciated
