### ISSUE TITLE
[Feature Request] Incremental data request

### ISSUE THREAD

**Issue by mihigh** [grafana/grafana#4300]
We have e very heavy graph, with a very expensive query witch is refreshing every X minutes. Does it make sense to request only the data from the previous reload? This way the load on the datasource would be much lower.

**Comment by bergquist** [comment]
That could make sense for simple queries. But more complex queries could suffer since the previous data might be affected by new data (moving averige, time based aggregations) and I don't think Grafana should try to decide what queries could be effected or not.

**Comment by mihigh** [comment]
@bergquist It can be decided by the client via a checkbox.
