### ISSUE TITLE
Prometheus: Variables are no longer being evaluated in Annotations.

### ISSUE THREAD

**Issue by darkl0rd** [grafana/grafana#43008]
**What happened**:

Using variables in Annotations broke in 8.3.x

When using expression{label="value"} the annotation still works. When using expression{label=~"$variable"} the annotation is no longer shown. Testing the same expression (which always worked) by adding it to a graph shows that it should indeed return a value.

**What you expected to happen**:

Annotations to evaluate defined variables

**How to reproduce it (as minimally and precisely as possible)**:

Create a annotation, in your expression refer to a defined variable from the variables section.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Official Docker image on Linux x86_64
- User OS & Browser: MacOS 12.0.1, Chrome 96.0.4664.93
- Grafana plugins: None
- Others: None

**Comment by mindw** [comment]
Same for 8.3.3 - this seems like a regression in 8.3.x.

**Comment by victorboissiere** [comment]
We have the same issue and we lost many features in our dashboards because of this

**Comment by SailingYYC** [comment]
This is a significant impacting issue for us as well.
