### ISSUE TITLE
Alerting - Renaming a query replaces existing query names in expressions

### ISSUE THREAD

**Issue by haelekuin** [grafana/grafana#43007]
**What happened**:
Changing the name of a query when creating an alert replaces all existing query names used in expressions with the new query name, even if the name was previously not referenced.
[Recording](https://gfycat.com/opulentdeadlygoat)

**What you expected to happen**:
Only the name of the query is changed, with expressions / variables not changing.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an alert
2. Add an expression
3. Rename any query not used as an input for the expression

Grafana version: 8.3.1

**Comment by Elfo404** [comment]
Hi @haelekuin , thanks for reporting this!

I was able to reproduce this as well on master using both "Reduce" and "Resample"
