### ISSUE TITLE
[Bug] Link timestamp/variable include can't be disabled

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4301]
Steps:
* click "Link to Dashboard"
* deselect current time range or template variables

Expected:
* timestamps/vars get removed from the generated link immediately

Observed: 
* Link still contains timestamps/vars

Version:
3.0.0-pre1 (commit: v2.6.0-1345-g7ecf057)

**Comment by torkelo** [comment]
thanks for reporting this, will fix asap
