### ISSUE TITLE
Aggregation/comparison of two series from different graphite sources

### ISSUE THREAD

**Issue by evanbreznyik** [grafana/grafana#4302]
In 2.6.0, I appreciate the ability to use multiple data sources across hosts.  However, I have noticed by ability to run functions between two series that exist in two different data sources (even if they're the same type of source) is severely limited.  After not seeing anything in the documentation about this, I'm hoping you can tell me what I'm doing wrong or how to accomplish this.

For example, assume I have two sources.  Both are Graphite.  Let's say one is "us-east-1a" and the other is "us-east-1b" (imagine I am collecting metrics for each AWS availability zone separately).  If I then add these metrics to a graph:

* A:  graphite.us-east-1a.app-server*.bytes_out
* B:  graphite.us-east-1b.app-server*.bytes_out

I cannot then add a third metric to C that does:

* C:  sumSeries(#A, #B)

...nor can I aggregrate or use any other functions (like diffSeries) to compare these two series to other without using the built in Graphite data source (which, while containing all the metrics, causes Grafana to send a HUGE amount of proxy queries that take dozens of times longer to execute).

Yes, I can _stack_ the two metrics and make them share the same color, but I cannot _literally_ sum them together and then treat them as one metric.  (In the above example, I might want to look at the outgoing bandwidth for all my app-server* hosts, regardless of which Graphite node collects them.)

Maybe there is something obvious I am missing, but again --- I cannot see a way to do this without relying on the slow, built-in Graphite data source that seems a proxy query per metric THEN has to aggregate.

**Comment by bergquist** [comment]
This is not supported in Grafana but something that we have been looking into for a while but never got started. https://github.com/grafana/grafana/issues/3677

Closing this since its a dupe.
