### ISSUE TITLE
[Feature Request] Spline interpolation

### ISSUE THREAD

**Issue by evanbreznyik** [grafana/grafana#4303]
Since Grafana is able to deal with raw data points in a linear, vector way, is there any possibility of transcending the abilities of Graphite and interpolating data using Akima or EAM (or, if you want to get fancy, pure B-splines, Gauss-Lanczos, or other tensor) functions?

Akima/EAM might be very logical first choices, since they honor the momentary spikes or values in raw data in a way that B-splines do not.

Examples below:
![Spline interpolation](http://i.imgur.com/lHtFvOp.png)
![Better look at Akima](http://cloud.originlab.com/www/products/images/imgSeqs/InterpolatedYFromXMethods/InterpolatedYFromXMethods_02.png)

Again, if these can be kept in vector form without the need to rasterize, a much more useful (not to mention beautiful) graph could be rendered.  Think useful and beautiful smoothing interpolation.

**Comment by sslupsky** [comment]
+1  Good idea!  Could be combined with #4435

**Comment by Arbel-arad** [comment]
has there been any progress on this?
