### ISSUE TITLE
Time regions from Graph (old) available for new Time regions?

### ISSUE THREAD

**Issue by Wandmalfarbe** [grafana/grafana#43042]
PR https://github.com/grafana/grafana/pull/12371 introduced *Time regions* for the old graph panel which were incredibly useful. One could highlight certain time periods like weekends or color each weekday with a background. Is such a feature available for the new *Time series*?

**What happened**:

The new *Time series* panel provides no way to display *Time regions* like in the old graph panel.

**What you expected to happen**:

Provide a way to highlight certain regions based on time, e.g. weekends (https://github.com/grafana/grafana/issues/5930).

**Environment**:
- Grafana version: v8.3.2

**Comment by Elfo404** [comment]
closing this as duplicate of #35486
