### ISSUE TITLE
User administration, I am still confused

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4304]
1. root (grafana) admin created two orgs and one editor, one viewer in each orgs.
2. root created a datasource. this datasource is not available in both the orgs ?

Do i need to now create a admin user in each org and let them create datasources ?

**Comment by deepujain** [comment]
Two orgs are created, each org has admin & viewer. Admin created few dashboards in each org.

Can grafana admin view all dashboards without switching to organizations ?

When anonymous login is  enabled (true) then can that anonymous user view all the dashboards ? Or does this user belong to a org of grafana admin . Today i dont see the dashboards for anonymous user.

I want a anonymous user to be able to see the dashboards.

**Comment by deepujain** [comment]
Can you comma separated orgs here ?

# specify organization name that should be used for unauthenticated users
org_name = Main Org.

**Comment by bergquist** [comment]
* Datasources belongs to the org. So you have to setup them it once per org. 
* Admins can only see the dashboards from the currently active org.
* Anonymous users can only see the dashboards from the org you assign them to in the conf. 
* Comma separated orgs is not supported.

Organization functionality in grafana is designed for hosting totally seperate companies or organisation not teams within the same org or dashboard permissions.
