### ISSUE TITLE
grafana data source not found through proxy

### ISSUE THREAD

**Issue by swaroopkundeti** [grafana/grafana#43050]
**What happened**:
When I run queries I do not see results and in logs i see 404 for data source. 

<pre>
t=2021-12-08T19:46:48+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/1/api/v1/metadata status=404 remote_addr=10.0.10.5 time_ms=278 size=43 referer="https://dev.monitoring.example.com/monitoring/d/wyTIFC57z/performance-node-health?orgId=1&editPanel=120&inspect=23763571993&inspectTab=query"
t=2021-12-08T19:46:49+0000 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=GET path=/api/datasources/proxy/4/api/v1/metadata status=404 remote_addr=10.0.10.5 time_ms=220 size=43 referer="https://dev.monitoring.example.com/monitoring/d/wyTIFC57z/performance-node-health?orgId=1&editPanel=120&inspect=23763571993&inspectTab=query"
</pre>
**What you expected to happen**:

Queries suppose to execute and fetch data

**How to reproduce it (as minimally and precisely as possible)**:

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Prometheus
- OS Grafana is installed on: grafana image provided by grafana.
- User OS & Browser: Mac and Chrome

**Configuration**
<pre>
   - name: Prometheus-us-south
      type: prometheus
      orgId: 1
      access: proxy
      url: http://trickster.monitoring.svc.cluster.local:8480/us-south
      isDefault: false
      version: 1
      editable: true
      jsonData:
        httpHeaderName1: 'Authorization'
      secureJsonData:
        httpHeaderValue1: 'Bearer abcd'
  - name: Prometheus-us-east
      type: prometheus
      orgId: 1
      access: proxy
      url: http://trickster.monitoring.svc.cluster.local:8480/us-south-staging
      isDefault: true
      version: 1
      editable: true
      jsonData:
        httpHeaderName1: 'Authorization'
      secureJsonData:
        httpHeaderValue1: 'Bearer abcd' 
</pre>

**grafana.ini**
<pre>
grafana.ini:
  paths:
    data: /var/lib/grafana/
    temp_data_lifetime: 24h
    logs: /var/log/grafana
    plugins: /var/lib/grafana/plugins
    provisioning: /etc/grafana/provisioning
  analytics:
    check_for_updates: true
  log:
    mode: console
    level: info
  server:
    protocol: http
    http_port: 3000
    enforce_domain: false
    domain: https://dev.monitoring.example.com/monitoring
    root_url: https://dev.monitoring.example.com/monitoring
    serve_from_sub_path: true
    router_logging: false
    static_root_path: public
    enable_gzip: false
  database:
    type: sqlite3
    host: 127.0.0.1:3306
    name: grafana
    user: root
    max_idle_conn: 2
    conn_max_lifetime: 14400
    ssl_mode: disable
    path: grafana.db
    cache_mode: private
  remote_cache:
    type: database
  dataproxy:
    timeout: 30
    logging: false
    send_user_header: false
  users:
    allow_sign_up: false
    allow_org_create: false
    auto_assign_org: true
    auto_assign_org_id: 1
    auto_assign_org_role: Viewer
    verify_email_enabled: false
    default_theme: dark
    viewers_can_edit: false
    editors_can_admin: true
  auth:
    login_cookie_name: grafana_session
    login_maximum_inactive_lifetime_days: 7
    login_maximum_lifetime_days: 30
    token_rotation_interval_minutes: 10
    disable_login_form: false
    disable_signout_menu: false
</pre>

**Comment by Elfo404** [comment]
Hi @swaroopkundeti thanks for reporting this.

This is weird, I can query that metadata endpoint without any issue here.
Is it the only HTTP request that fails? could it maybe be a network configuration error?

**Comment by swaroopkundeti** [comment]
@Elfo404 thank you for checking. I cross-checked with my Prometheus team and found out that it's deliberately disabled. I will be closing this issue as this is a problem on our side. 

Appreciate again for your help.
