### ISSUE TITLE
Opensearch, alert test return "Query Returned No Series" 

### ISSUE THREAD

**Issue by fsa1803** [grafana/grafana#43053]
**What happened**:
We use OpenSearch 1.1 configured with compatibility.override_main_response_version: true (https://opensearch.org/docs/latest/clients/agents-and-ingestion-tools/index/) for Beats compatibility.

Datasource is configured like:
![img04](https://user-images.githubusercontent.com/66841577/145856594-8baa5846-8ad3-49a8-975c-9c38e26936ed.PNG)

the problem occurs even though I configure as Elasticsearch 7.0+

query is:
![img01](https://user-images.githubusercontent.com/66841577/145856954-e5eee6f9-d07a-40fb-87c2-e32664d9e291.PNG)

and alert is:
![img02](https://user-images.githubusercontent.com/66841577/145857003-37a8783b-8973-42e5-9f9b-f096e522616b.PNG)

When I test the rule:
![img03](https://user-images.githubusercontent.com/66841577/145857059-db3e5f99-ec72-4a18-877f-a1ed0513cc53.PNG)
 

**Anything else we need to know?**:

If I use Elastsearch datasource al goes fine.

**Environment**:
- Grafana version: OSS 8.3.1
- Data source type & version:  OpenSearch
- OS Grafana is installed on: Red Hat 8.3
- User OS & Browser: Windows 10 Chrome
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Closing this in favor of https://github.com/grafana/opensearch-datasource/issues/11
