### ISSUE TITLE
How to change grafana app path?

### ISSUE THREAD

**Issue by Sartner** [grafana/grafana#4305]
How to change grafana app path?

I changed the root_url in '/etc/grafana/grafana.ini', but got 404.

root_url = %(protocol)s://%(domain)s:%(http_port)s/
to
root_url = %(protocol)s://%(domain)s:%(http_port)s/myAppPath

**Comment by torkelo** [comment]
you can only do that if you have a nginx/apache proxy in front of Grafana.

**Comment by Sartner** [comment]
I use a nginx server in front of it . And set the app path to  /grafana/. 
**nginx.conf:**
``` 
location /grafana/{
  proxy_pass http://grafana_host:grafana_port/;
}
```

but it still load resources from ROOT path
http://myNginxHost/public/app/app.ca0ab6f9.js

**Comment by torkelo** [comment]
looks correct, did you restart grafana-server after the config change?

**Comment by Sartner** [comment]
Oh! It's success...
Thank you very much~~~
