### ISSUE TITLE
Building packages: "systemjs:build" task TypeError Same result #4226

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#4306]
Hi, brother
I running latest-version grafana on centos6. very nice running...

but,,

when I try this command 
"go run build.go build package" for packaging

Below Error occurred ..

```
Running "systemjs:build" task
Starting systemjs-builder
Build error
[TypeError: Error compiling amd module "moment" at vendor/moment.js
        Cannot read property 'parameters' of undefined]
Warning: Task "systemjs:build" failed. Use --force to continue.

Aborted due to warnings.
exit status 3
exit status 1
```

npm version is 2.14.12, go version is 1.5 and nodejs version is 4.3.2

how to packaging latest grafana ? 

thanks.

**Comment by torkelo** [comment]
strange, it is passing on the build server (https://circleci.com/gh/grafana/grafana)

try removing node_modules dir and rerun "npm install"
