### ISSUE TITLE
Grafana Alert v2 API does not allow updating of existing rule group

### ISSUE THREAD

**Issue by Etherdaemon** [grafana/grafana#43066]
**What happened**:
POSTing to `/api/ruler/grafana/api/v1/rules/<namespace>` the first time results in rules being created. 
On the second time to POST with or without updates to the Payload the result was 
```
500 Internal Server Error
{"message": "failed to update rule group: a conflicting alert rule is found: rule title under the same organisation and folder should be unique" }
```
**What you expected to happen**:
As the Swagger docs mentions that this API endpoint should create and update I expect an update to succeed. Or a second endpoint should be made available to perform a PATCH

![image](https://user-images.githubusercontent.com/8214068/145908038-3cf192cd-8c4b-4089-8b06-47dd4cbd4e74.png)

**How to reproduce it (as minimally and precisely as possible)**:
* Perform a POST to `/api/ruler/grafana/api/v1/rules/<namespace>` with a simple rule group payload
* Re-POST the same payload to the same API endpoint

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.1 and v8.3.2
- Data source type & version: Grafana Alert
- OS Grafana is installed on: RHEL 7
- User OS & Browser: Windows and Ubuntu
- Grafana plugins: Polystat
- Others: Attempted via curl, Postman and VSCode REST Client

**Comment by lafrech** [comment]
I experienced the same. The API endpoint allows both creation and update. The thing is that when updating, a `uid` must be specified. You can check that by updating an alert from your browser and watching the payload using the "developer interface" (the name may differ depending on the browser).

My understanding is the following:

Upon creation, a uid is created automatically by Grafana server. When posting a second time, the server does not know which element is being updated unless that uid is added to the payload.

You can get the uid with a GET on the endpoint.

In any case, a 500 means server error, which is bad. The payload in invalid but the server fails to detect that properly. It could be that it tries to create a second rule but chokes on a unique name constraint, for instance. (Perhaps the name could have been be used as the ID but that's another story.) It would be better if the error was caught and a better error message returned.

-------------------------

My use case is creating many alerts using the API. After updating the alert template, I need to update all alerts. What I should do is fetch the alerts from the endpoint to get the uid then POST with the proper uid. In practice, a quick and dirty way is to delete and recreate.

**Comment by j0rzsh** [comment]
I am having the same issue. The thing is that if you do not provide an uid, it goes to create and if you provide an uid, it goes to update. This is not in the documentation, you should try it yourself for knowing it.

This means that I cannot create and update using the same body, and also menas that I cannot specify the uid the same I do with dashboards. It is very strange that those two systems (dashboards and alerting) work differently, I think it is not the expected behaviour.

Also a 500 error when the name is conflicting is not the best code error to use IMO.

Thanks :)

**Comment by amandeep-r** [comment]
Having same issue here. Worked around it as follows:

1. Fetch the alert models in a particular namespace using the `/api/ruler/grafana/api/v1/rules/<namespace>` endpoint
2. Wrote a snippet to to remove the `UID` field from the alert rule models prior to saving the file:
```
alert_namespaces = ["x", "y", "z"]

for folder in alert_namespaces:
    r_list_alerts = requests.get(
        url=f"{url_base}api/ruler/grafana/api/v1/rules/{folder}", headers=headers
    )
    r_list_alerts.raise_for_status()
    alert_models = r_list_alerts.json()[folder]
    for group in alert_models:
        for rule in group["rules"]:
            rule["grafana_alert"].pop("uid")
    with open(f"alert_backups/{folder}.json", "w") as f:
        json.dump(alert_models, f, indent=4)
    print(f"Backed up --- Alerts in folder: {folder}")
```

3. Prior to posting the saved alert models, delete all alert rules in the relevant namespace:

```
url = f"{url_base}api/ruler/grafana/api/v1/rules/{namespace}"
r_delete_alerts = requests.delete(url=url, headers=headers)
r_delete_alerts.raise_for_status()
r = requests.post(url=url, headers=headers, json=payload)
```

Echoing what @j0rzsh said in regards to how this system should mirror how dashboards handle `UID`

**Comment by JohnnyQQQQ** [comment]
This API is not for public use. Creating alert rules through API can be done with the supported provisioning API that you can find here https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/

**Comment by vispatel** [comment]
@JohnnyQQQQ even with the suggested API you would get a 500 error:

`{
    "message": "a conflicting alert rule is found: rule title under the same organisation and folder should be unique",
    "traceID": ""
}`
