### ISSUE TITLE
What grafana has the function of probability and statistics[/Question]

### ISSUE THREAD

**Issue by hugoren** [grafana/grafana#4307]
grafana_version 2.6
datasource  graphite0.9
os centos7.1

What grafana has the function of probability and statistics[/Question]
Data show the probability of 95% or 80% and so on 
Thank you for your answer

For example:
     50th Perc: 1417216                    50th Perc: 11200                    Max: 1              |
|    90th Perc: 1417216                    90th Perc: 11200                                        |
|    95th Perc: 1417216                    95th Perc: 11200                                        |
|    99th Perc: 1417216                    99th Perc: 11200                  Error Count: 0        |
|    99.9th Perc: 1417216                  99.9th Perc: 11200

**Comment by torkelo** [comment]
This is not a feature in Grafana, but how you query data, if you data store supports percentiles you can visualize it in Grafana.

**Comment by bergquist** [comment]
For percentiles with graphite you should use statsd https://github.com/etsy/statsd
