### ISSUE TITLE
Influx: Cannot remove tag from "WHERE" condition & autocomplete fails for second condition (in query builder when editing a panel)

### ISSUE THREAD

**Issue by matzl** [grafana/grafana#43073]
**What happened**:
When I add or edit a panel in the Grafana web interface and add or edit a new query, I can add a new WHERE condition by clicking on the field right to the blue "WHERE" field in the query builder and selecting a tag. However:
A) it is not possible to remove the tag, like it is for the SELECT or GROUP BY filter:
![Animation](https://user-images.githubusercontent.com/9556620/145968333-e7652b25-07f5-4ed5-82d2-354251a7ecd5.gif)

B) auto-complete fails for the second, third, ... tag, i.e. it only works when one tag is used in the WHERE condition:
![Animation2](https://user-images.githubusercontent.com/9556620/145969781-1aa751d9-3dcd-4cb8-aa21-424454d95e81.gif)

**What you expected to happen**:
A) I expected to have an option to remove the tag again (without deleting and re-adding the whole query), for example by clicking on the tag and selecting "remove" like it is for the SELECT or GROUP BY filter.

B) auto-complete works for all WHERE tags

**How to reproduce it (as minimally and precisely as possible)**:
(as shown in the screenshots)
In the environment mentioned below (or probably also other environments):
- add a new dashboard
- add a new panel
- in the query, add a new WHERE clause. A) Try to delete a WHERE condition, B) try to add a second tag in the WHERE condition

**Anything else we need to know?**:
Maybe this is part of the problem: I receive the following Javascript Errors/Warnings:
![screen 1](https://user-images.githubusercontent.com/9556620/145968337-4d1b9e7d-6f92-49b3-b366-b48095197cd1.png)

A) This one pops up twice when I click on the "WHERE" clause variable, in my case "slave_cell":
![screen 2](https://user-images.githubusercontent.com/9556620/145968339-731fcfb0-475f-4b62-8efc-58e25ae47d35.png)

B) no warning pops up when I try to ad a second or third tag in the WHERE condition.

**Environment**:
- Grafana version: 8.3.2 (afb9e8e5f3)
- Data source type & version: InfluxDB shell 0.10.0
- OS Grafana is installed on: Ubuntu 16.04.7 LTS
- User OS & Browser: Windows 10 Education 20H2, Vivaldi 4.1.2369.21 (Stable channel) (64-Bit)
- Grafana plugins: Core plugins + Plotly + Plotly panel + Scatter
- Others: -

**Comment by henriknoerr** [comment]
this is fixed in grafana 8.3.3
