### ISSUE TITLE
allow configurable scripted dashboard updation time in web interface [Feature Request]

### ISSUE THREAD

**Issue by arcolife** [grafana/grafana#4308]
When a json is thrown into the dashboards directory (when that feature is enabled), it takes sometimes upto 5-6 seconds or even more, for them to appear under regular dashboard search in grafana.  Questions:
- How is this currently happening? Which service is responsible for this? 
- Is this timing configurable?
- Could this be made configurable?

My application, which indexes data in ES, uses grafana as next redirection step in the web app, and requires for dashboards to be available immediately. I'm currently doing this by entering data into the sqlite3 database. Would prefer to use postgres for scaling up, if the (scripted dashboards + json files as db) doesn't work out well with scale. 

Thanks in advance!

--
* What grafana version are you using?
grafana-2.5.0-pre1.x86_64.rpm

* What datasource are you using?
Elasticsearch

* What OS are you running grafana on?
Fedora 23

**Comment by torkelo** [comment]
the json dashboards directory is scanned every minute, think this is low enough
