### ISSUE TITLE
Codeql: Code scanning errors

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#43080]
There are code scanning errors that are currently failing the main build.

- [ ] [Polynomial regular expression used on uncontrolled data in the Prometheus ds legend.ts](https://github.com/grafana/grafana/security/code-scanning/206?query=ref%3Arefs%2Fheads%2Fmain)
- [ ] [Replacement of a substring with itself in JSONFormatter/json_explorer/helpers.ts](https://github.com/grafana/grafana/security/code-scanning/23?query=ref%3Arefs%2Fheads%2Fmain) 
- [x] [Incomplete string escaping or encoding in alertmanager.ts](https://github.com/grafana/grafana/security/code-scanning/108?query=ref%3Arefs%2Fheads%2Fmain)
- [ ] [Polynomial regular expression used on uncontrolled data in template_srv.ts](https://github.com/grafana/grafana/security/code-scanning/98?query=ref%3Arefs%2Fheads%2Fmain)
- [ ] [Polynomial regular expression used on uncontrolled data in JSONFormatter/json_explorer/helpers.ts](https://github.com/grafana/grafana/security/code-scanning/97?query=ref%3Arefs%2Fheads%2Fmain)
- [ ] [Polynomial regular expression used on uncontrolled data in rangeutil.ts](https://github.com/grafana/grafana/security/code-scanning/95?query=ref%3Arefs%2Fheads%2Fmain)
- [ ] [Polynomial regular expression used on uncontrolled data in processDataFrame.ts](https://github.com/grafana/grafana/security/code-scanning/94?query=ref%3Arefs%2Fheads%2Fmain)
- [ ] [Incomplete string escaping or encoding in metricTree.ts](https://github.com/grafana/grafana/security/code-scanning/15?query=ref%3Arefs%2Fheads%2Fmain)
- [x] [Incomplete string escaping or encoding in JSONFormatter/json_explorer/helpers.ts](https://github.com/grafana/grafana/security/code-scanning/9?query=ref%3Arefs%2Fheads%2Fmain) https://github.com/grafana/grafana/pull/44096
- [x] [Uncontrolled data used in path expression - Plugin manager, dashboards.go](https://github.com/grafana/grafana/security/code-scanning/166?query=ref%3Arefs%2Fheads%2Fmain) 
- [x] [Uncontrolled data used in path expression - Plugin manager, installer.go](https://github.com/grafana/grafana/security/code-scanning/167?query=ref%3Arefs%2Fheads%2Fmain)
- [x] [Uncontrolled data used in path expression - Plugin manager, installer.go](https://github.com/grafana/grafana/security/code-scanning/168?query=ref%3Arefs%2Fheads%2Fmain)
- [x] [Uncontrolled data used in path expression - ngalert notifier](https://github.com/grafana/grafana/security/code-scanning/169?query=ref%3Arefs%2Fheads%2Fmain)
- [x] [Log entries created from user input - devenv](https://github.com/grafana/grafana/security/code-scanning/197?query=ref%3Arefs%2Fheads%2Fmain)
- [x] [Database query built from user-controlled sources - annotation.go](https://github.com/grafana/grafana/security/code-scanning/171?query=ref%3Arefs%2Fheads%2Fmain)
- [x] [Database query built from user-controlled sources - annotation.go](https://github.com/grafana/grafana/security/code-scanning/170?query=ref%3Arefs%2Fheads%2Fmain)

Fixes:
- #43623
- #43529
- https://github.com/grafana/grafana/pull/43462

**Comment by daniellee** [comment]
ref https://github.com/grafana/grafana/pull/43337 - potential fix for Polynomial regular expression used on uncontrolled data

**Comment by JohnnyQQQQ** [comment]
The one in ngalert seems to be a false positive, I created a PR to fix it. https://github.com/grafana/grafana/pull/43425

**Comment by marefr** [comment]
Dismissed below two as `won't fix` so they are now closed. We have a comment there explaining 
> If the user shouldn't be able to read the file, it should be handled through filesystem permissions

And the code is only used from the `grafana-cli`.

- [Uncontrolled data used in path expression - Plugin manager, installer.go](https://github.com/grafana/grafana/security/code-scanning/167?query=ref%3Arefs%2Fheads%2Fmain)
- [Uncontrolled data used in path expression - Plugin manager, installer.go](https://github.com/grafana/grafana/security/code-scanning/168?query=ref%3Arefs%2Fheads%2Fmain)

**Comment by gillesdemey** [comment]
PR for fixing `alertmanager.ts` is up in #43956
