### ISSUE TITLE
[Bug] OPENTSDB - $tag_tagname substitutions broken on nightly

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4311]
On today's nightly, tag substitution is not working anymore, ie. $tag_antenna appears as is, instead of outputing the tag value

**Comment by torkelo** [comment]
thanks for reporting this, will take a look tomorrow!

**Comment by utkarshcmu** [comment]
@vitorboschi Do you know when this issue appeared or did you just notice it today?

**Comment by vitorboschi** [comment]
I can't tell you exaclty when it appeared. I was using a nightly from 29/Jan, IIRC, and today I updated to the current nightly (from today), so it appeared somewhen in this timespan

**Comment by utkarshcmu** [comment]
Thanks for this info. I am able to reproduce the issue, will try to fix it asap. :)

**Comment by utkarshcmu** [comment]
So, according to my findings, something changed in this commit [https://github.com/grafana/grafana/commit/0da4168836a73a8a10bd8cf8b2e40d61b6179498#diff-ece81ff260bfcb9f65df22b3275da7ae] that broke $tag_tagname OR Alias feature for Opentsdb. 

Looking into this commit....

**Comment by utkarshcmu** [comment]
The responsible code for the above error:

**Comment by hasso** [comment]
I don't know what exact Prometheus issue with templates this fix should have fixed, but Prometheus template substitutions are certainly broken in the current nightly (3/13/2016, 9:35:35 PM) as well.

Using template with name "Hostname", which has a value "host.domain.com":

query{hostname="host.domain.com"} - works
query{hostname="$Hostname"} - doesn't work
query{hostname=~"$Hostname"} - works

**Comment by torkelo** [comment]
@hasso you say `query{hostname="$Hostname"}` does not work, what is your variable definition for Hostname? have you disabled All value and multi value?

**Comment by hasso** [comment]
Hostname is a query from Prometheus - label_values(load, instance) and works as expected. Multi-value isn't selected, but "All" is and disabling it fixes the problem indeed (though not a real solution for me as that's the one I'm using mostly).

**Comment by torkelo** [comment]
@hasso but if you have All value enabled how do you expect a query like `query{hostname="$Hostname"  t` to work? you cant match multiple values unless you use the regex operator

**Comment by hasso** [comment]
I have to admit I haven't thought about it ;). But the point is that it worked before (2.6 and nightlies up to middle of February probably). I have a lot of "template all possible hostnames and repeat single panel for every hostname" dashboards and they all worked before with hostname="$Hostname".

**Comment by torkelo** [comment]
@hasso but the All option could not have worked, right? Not understanding how that would be possible
