### ISSUE TITLE
Gradient should apply horizontally for horizontal bar charts

### ISSUE THREAD

**Issue by erozen** [grafana/grafana#43137]
**What happened**:
I had a bar chart in vertical mode, with gradient set to "Hue" - each bar tapered through the palette correctly.  When set to horizontal however, the gradient still applies vertically, so now the top of the top bar is red, fading to green at the bottom of the bottom bar.

**What you expected to happen**:
Gradient would be applied in the same direction as the bar

**How to reproduce it (as minimally and precisely as possible)**:
Create a bar chart, set direction to horizontal, and apply a gradient

**Anything else we need to know?**:
Screenshots below.
![1 grafana-good-gradient](https://user-images.githubusercontent.com/8446560/146167568-0a0e92a9-6e6b-4cc2-a9c2-c419a15d903d.png)
![2 grafana-bad-gradient](https://user-images.githubusercontent.com/8446560/146167677-6a93a9c5-6b68-4d38-9e4d-c867b6b8ba44.png)

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: Elasticsearch 7.15.2
- OS Grafana is installed on: Docker / linux
- User OS & Browser: Linux / Firefox
- Grafana plugins: None
- Others:

**Comment by leeoniya** [comment]
hmm, looks like we pass `GradientDirection.Up` in all places

https://github.com/grafana/grafana/blob/15695298082dee79ff37c4ff5ba64bb22b4ac355/packages/grafana-ui/src/components/uPlot/config/gradientFills.ts#L249

this function is also used for drawing threshold regions, so there are probably additional undiscovered bugs in ensuring that thresholds are draw in the correct orientation.
