### ISSUE TITLE
Prometheus Annotations that are based on a value between 0 and 1 do not show

### ISSUE THREAD

**Issue by amnonh** [grafana/grafana#43139]
**What happened**:
I created an annotation based on a Prometheus gauge metrics with values between 0 and 1.
![image](https://user-images.githubusercontent.com/2118079/146174816-3e475c9b-4e03-4d65-85d5-0ead2dc098c5.png)

The annotation didn't appear (I cross refrense it with a panel)
![image](https://user-images.githubusercontent.com/2118079/146175053-3514c980-b94e-4a8b-a09d-c063f312a2fc.png)

I then changed the annotation to be:
``10*min(scylla_node_ops_finished_percentage) by (ops, dc,instance) < 10``
And the annotation appear:
![image](https://user-images.githubusercontent.com/2118079/146175227-c25159d0-cc3a-4c50-9869-a444ae347fbd.png)

**What you expected to happen**:
``min(scylla_node_ops_finished_percentage) by (ops, dc,instance) < 1`` should have work
**How to reproduce it (as minimally and precisely as possible)**:
Create an annotation based on a prometheus value between 0 and 1.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.2 (but it didn't work in other 8.x versions that I tried)
- Data source type & version: prometheus
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jan-xyz** [comment]
We have a similar issue, I am not 100% sure if it is related or not. We have an annotation based on the `kube_replicaset_created` metric from Kubernetes which creates a new metric with the timestamp of the creation as the value in seconds. This stopped working recently for 99% of the cases, it does still seem to work for cases where we have two instances reported quickly after another. The full query is `kube_replicaset_created{namespace="my-ns"} * 1000`

Here a screenshot of the full configuration:
<img width="741" alt="Screenshot 2021-12-15 at 16 12 39" src="https://user-images.githubusercontent.com/5249233/146212550-a9a1f9f8-7f50-4dd3-80d3-d95e7542d997.png">

**Comment by guusvw** [comment]
Follow up on @jan-xyz 
We can at least confirm that the same Dashboard with the same setup for Annotations is working on Grafana v8.2.7

**Comment by SailingYYC** [comment]
I can confirm on 8.3.2 we have the exact same issue noted by @jan-xyz

**Comment by jan-xyz** [comment]
This bug blocks us from going past Grafana 8.2.7 for months now. Could we get some insides why this is prio low? It breaks at least a dozen of our dashboards.

**Comment by amnonh** [comment]
@jan-xyz as a work around I multiplied the expr in a 100 and change the condition accordingly, maybe it would work for you?

**Comment by gtk-grafana** [comment]
I am able to reproduce this locally on current main

**Comment by gtk-grafana** [comment]
A fix for this should be released in 9.2.0, thanks to everyone for taking the time to report and investigate this issue!
