### ISSUE TITLE
Add a newly created user to a given organisation

### ISSUE THREAD

**Issue by berrytchaks** [grafana/grafana#4314]
Hi all,

I created a user X, I created an organization for that user and I switch the X to the created organization. All that I did with the [grafana api](http://docs.grafana.org/reference/). Everything works well.
I then created a new user Y. Now I want to add the user Y to the organization created by the user X.
Well I thought of adding Y to the current organization but it does not works because the current organization is the main org.

Any help will be welcoming?
Thanks.

**Comment by torkelo** [comment]
you need to an api key for the new org you created for user X,  or use basic auth and a grafana server admin user, then you can use the admin apis
