### ISSUE TITLE
[Bug] More than two &var in QUERY STRING defaults to "All"

### ISSUE THREAD

**Issue by TryTryAgain** [grafana/grafana#4315]
I'm only able to pass two `&var` into a template.

I'm trying to get 
`http://somedomainname.com/grafana/dashboard/db/generic-check?var-device=SF-come_computername_com&var-check=Check_Memory_Load&var-datatype=perfdata&var-value=value`

...but it only works with up to two and defaults to All for anything over two. For example:
`http://somedomainname.com/grafana/dashboard/db/generic-check?var-device=SF-come_computername_com&var-check=Check_Memory_Load` works without issue..and `http://somedomainname.com/grafana/dashboard/db/generic-check?var-device=SF-come_computername_com&var-value=value` works without issue.

But as soon as I add more than two `&var-<varname>` it'll default anything more than two to All and not pass my QUERY STRING variable I'd like to go direct to using the template.

My templating is setup so each variable does allow the All value as well as multi-value selection, if that matters I'm not sure.

Any help is appreciated if this is not a bug and I'm overlooking something.

I'm on Grafana version 2.6.0
I'm using Graphite as my datasource
Grafana is installed on Ubuntu 14.04.4

**Comment by torkelo** [comment]
whats the definition for you template variables? Could be fixed recently. If you can please try the Grafana 3.0-pre1 pre release builds grafana.org/download/builds.html

**Comment by TryTryAgain** [comment]
Thanks for the response. 3.0-pre1 looks beautiful! Good news is the URI actually passes more than two var-<varname> but unfortunately, the graph is empty.
My definitions for the template variables are as follows

```
$device	        icinga2.*			
$check	        icinga2.$device.services.*				
$checkmetric	icinga2.$device.services.$check.*			
$datatype	        icinga2.$device.services.$check.$checkmetric.*			
$datametric	icinga2.$device.services.$check.$checkmetric.$datatype.*				
$value	        icinga2.$device.services.$check.$checkmetric.$datatype.$datametric.*			

```

I believe this is a new bug though, as I'm not able to get data to come up manually either, for some reason these variables aren't being populated from graphite even though the data exists. 

<img width="1374" alt="screen shot 2016-03-10 at 8 11 10 am" src="https://cloud.githubusercontent.com/assets/322503/13675865/615cec76-e698-11e5-8900-2c9c6c635238.png">
 ...shows what I'm brought to from the URI I specified, but if I manually enter each template variable for the device I realize the template variables are not pulling the available information (ie: datatype: metadata/perfdata don't even show up)...

Looks like I may need to revert and then wait. Let me know if I can help.
