### ISSUE TITLE
Entering kiosk mode in a different org locks UI

### ISSUE THREAD

**Issue by dessen-xu** [grafana/grafana#43150]
**What happened**:

The search params kiosk not work in url when the org to be accessed is not the current org.

example:

when the current org is 2, but I visit org 3 with kiosk in url:

https://xxx.com/?orgId=3&kiosk

The kiosk will be discarded:
https://xxx.com/?kiosk=&orgId=3

and no full screen

**What you expected to happen**:

kiosk can work

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.2
- Data source type & version: OpenTSDB,prome,Mysql and so on
- OS Grafana is installed on: Linux
- User OS & Browser: macOS, Chrome
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
I was able to reproduce this also on main.

It seems like when visiting a page having in the search params an `orgId` different from the active one and `kiosk`, the URL gets rewritten to `?kiosk=&oergId=x` (notice the extra `=` after `?kiosk`).

In my case though, Grafana enters kiosk mode, it just seems it cannot be exited anymore (ie. by pressing `ESC`)

**Comment by dessen-xu** [comment]
Grafana enters kiosk mode, but is incomplete. When '?kiosk=&orgId=x', it is:
![image](https://user-images.githubusercontent.com/41524013/146476145-aacceaa2-986d-4e91-8b8d-5f633fe324fb.png)

This is OK:
![image](https://user-images.githubusercontent.com/41524013/146476250-8064c14d-4162-434a-bf2c-3e3aef9c3f8a.png)
