### ISSUE TITLE
Monaco editor needs 6char-hexadecimal color codes

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#43158]
in https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/Monaco/theme.ts#L9-L10 we use colors from the grafana-theme to setup monaco.

we sometimes use short color names like `#fff` instead of `#FFFFFF`. this works in grafana, but it will fail in monaco. this happened in https://github.com/grafana/grafana/issues/43052 . we hotfixed this by adjusting the problematic colors manually, but we need a more robust fix, otherwise in the future a grafana-theme color change could bring the problem back.

**Comment by Elfo404** [comment]
a bit unsure where this falls in, @grafana/user-essentials because of theming? @grafana/observability-squad because of  monaco editor?

cc. @dprokop

**Comment by gabor** [comment]
just so we don't forget it: https://github.com/bgrins/TinyColor#tohexstring could be useful here

**Comment by JoaoSilvaGrafana** [comment]
I am not sure what is expected by this issue, is there something to be done on the theming side or what is the proposed solution?
@gabor do you want to clarify?

**Comment by gabor** [comment]
in the monaco-code, we read two values from the grafana theme, and use them to setup monaco. the values are:
- `theme.components.input.background,`
- `theme.colors.background.secondary`

this usually works fine, but the issue is, there are many ways to describe css colors, and monaco accepts less formats than "grafana". so, if you use three-letter-css-hexa-codes, they will work in grafana, but fail in monaco.

my idea was to use `https://github.com/bgrins/TinyColor#tohexstring` (we already use that npm package), to "normalize" the css-color-name for monaco, something like this:
```diff
-    return {
-      'editor.background': theme.components.input.background,
-      'minimap.background': theme.colors.background.secondary,
-    };
+    return {
+      'editor.background': tinycolor(theme.components.input.background).toHexString(),
+      'minimap.background': tinycolor(theme.colors.background.secondary).toHexString(),
+    };
```

**Comment by JoaoSilvaGrafana** [comment]
Ah ok! That should be changed in the Monaco editor, but according to the responsibilities spreadsheet no one owns it 😅  so who do we ask to make this change or at least to review it if we make it?
