### ISSUE TITLE
evaluate "now" for time range on grafana server

### ISSUE THREAD

**Issue by FlorianLudwig** [grafana/grafana#4316]
(grafana v2.6.0, influxdb datasource)

Settings the time range to `now - 5m` to `now` means that the grafana server evaluates `now` to a date as well as the influxdb backend.  So if the servers clocks are out of sync this leads to empty spaces in the graph.  If the clocks are out of sync by 5 miuntes it would mean completely empty graphs in this example.

Resolving `now` to a specific time once would mean consistent results and less strange-to-debug-empty-graphs.

**Comment by torkelo** [comment]
sorry, this will have to stay in the frontend
