### ISSUE TITLE
Incorrect "datasource" map for Expression targets when importing json on v8.3.3

### ISSUE THREAD

**Issue by romich** [grafana/grafana#43175]
**What happened**:
When importing json that used to work on v8.1, I now get error "expression request error" for panels that use Expressions.

**What you expected to happen**:
I expect such panels to continue working as they were before.

**How to reproduce it (as minimally and precisely as possible)**:
Source json (excerpt):
```
      "targets": [
        {...},
        {
          "datasource": "__expr__",
          "expression": "$A/$B",
          "hide": false,
          "refId": "C",
          "type": "math"
        }
      ]

```

json model right after import:
```
      "targets": [
        {...},
        {
          "datasource": {
            "type": "grafana-expression",
            "uid": "-100"
          },
          "expression": "$A/$B",
          "hide": false,
          "refId": "C",
          "type": "math"
        }
      ]

```

json model after deleting and re-adding Expression in WebUI:
```
      "targets": [
       {...},
       {
          "datasource": {
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$A/$B",
          "hide": false,
          "refId": "C",
          "type": "math"
        }
      ]

```

Result: `"datasource"` map is different.

**Anything else we need to know?**:
Happens on importing both via WebUI and HTTP API.

**Environment**:
- Grafana version: v8.3.3 (30bb7a93c)
- Data source type & version: n/a
- OS Grafana is installed on: Docker
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by ryantxu** [comment]
Trying to reproduce.... In 8.1, I export (for sharing externally) a dashboard with expressions, then try to import into 8.3... I get this notice: 
![image](https://user-images.githubusercontent.com/705951/147968421-d276faca-d644-49df-94a5-bb448c4c1a14.png)

Seems like for expression data sources we should avoid trying to map any special behavior.  I think this issue also points to another issue, but still digging
