### ISSUE TITLE
Azure Monitor: App crashes when using invalid template variable queries

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#43197]
This issue was originally reported as an HG escalation. 

**What happened**:
Frontend crashes when using an invalid variable query. 

![azurevariable](https://user-images.githubusercontent.com/2388950/146356895-8852c4b1-09c0-4282-8554-5253aab9ead7.gif)

**What you expected to happen**:

We should handle the exception (currently we don't in the Azure Monitor plugin) and return a human readable error message.

**How to reproduce it (as minimally and precisely as possible)**:
Use a  bad template variable query, e.g `ResourceGroups(abc)`

**Anything else we need to know?**:

Azure Monitor should indeed handle exceptions, but I also think the variable query runner should handle exceptions and prevent the app from crashing. Also it looks like the query is triggered on a really short debounce time. Has this been changed recently? I believe previously, variable queries were only triggered onblur. Thoughts @hugohaggmark? 

**Environment**: 
- Grafana version: main branch
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
@sunker I'm not aware of any debounce, should trigger onBlur only AFAIK. Regarding the  variable query runner, it should handle errors. I need to look into that part further.

**Comment by sunker** [comment]
> @sunker I'm not aware of any debounce, should trigger onBlur only AFAIK. Regarding the variable query runner, it should handle errors. I need to look into that part further.

Just saw that the debounce is coming from the azure monitor variable editor. So no need for you to dig deeper into this. Thanks @hugohaggmark!
