### ISSUE TITLE
Service accounts: Chore: Move roles to main package

### ISSUE THREAD

**Issue by donomii** [grafana/grafana#43209]
Consider moving roles into main package in pkg/services/serviceaccounts/manager/roles.go

from https://github.com/grafana/grafana/pull/42659/files/4cac308ad9e16f266fc58d00adb6059ccdd6d505#r769459699

**Comment by Jguer** [comment]
API keys roles have been moved in https://github.com/grafana/grafana/pull/46255.

This becomes a duplicate of https://github.com/grafana/grafana-enterprise/issues/2979
