### ISSUE TITLE
Grafana Node Graph only works in Explore mode when using Tempo data source

### ISSUE THREAD

**Issue by proffalken** [grafana/grafana#43201]
**What happened**:

Trying to use the Node Graph panel in a dashboard, the Tempo query for a specific stack trace does **not** return any data and errors with the message `id field is required for nodes data frame.`:

In `explore` mode:
![image](https://user-images.githubusercontent.com/262545/146362165-46f4b195-6ec0-4699-a159-8aa4ebc66b71.png)

In dashboard mode:
![image](https://user-images.githubusercontent.com/262545/146362382-3b8fc4a6-ab8a-4e80-b7ba-b77649948f64.png)

**What you expected to happen**:

I should be able to add a Node Graph widget on the dashboard based on a Tempo data source

**How to reproduce it (as minimally and precisely as possible)**:

Ensure that you have a valid trace in Tempo, confirm that the trace can be charted out in `Explore` mode.

Switch to `Dashboard` mode and add a new Node Graph panel with the same TraceID

**Anything else we need to know?**:

**Environment**:
- Grafana version:Grafana v8.3.1 (b9eacd93e9)
- Data source type & version: Core
- OS Grafana is installed on: Linux
- User OS & Browser: Linux/Brave (Chromium-based)
- Grafana plugins: grafana-github-datasource,grafana-worldmap-panel,grafana-clock-panel,grafana-piechart-panel,natel-discrete-panel,mtanda-histogram-panel,larona-epict-panel,grafana-googlesheets-datasource,agenty-flowcharting-panel,gowee-traceroutemap-panel,yesoreyeram-boomtheme-panel
- Others:

**Comment by proffalken** [comment]
I've just updated to Grafana v8.3.3 (30bb7a93ca) - the issue persists.

**Comment by tharun208** [comment]
@connorlindsey i like to work on this
