### ISSUE TITLE
Table panel w/ repeat option flickers when loading data (flickering, goes black)

### ISSUE THREAD

**Issue by philipklever** [grafana/grafana#43234]
**What happened**:
If a table panel is repeated with a dashboard variable, all instances but the first will flicker (go black) on loading/refreshing the data

**What you expected to happen**:
Prior (Grafana 8.2.0) the panel did not go black, when loading new data

**How to reproduce it (as minimally and precisely as possible)**:
- Install a fresh version Grafana 8.3.3 (Windows)

- Make a new dashboard
 - Add a variable to your dashboard: Type: Custom, Values: "1,2,3", Include All option: YES

![1](https://user-images.githubusercontent.com/54762464/146418177-49492811-bcd5-47dc-864c-855698370385.png)

- Add a new panel to the dashboard
 - Type: Table, Title: $query0, Data Source: "-- Grafana --" Random Walk
 - Repeat option: Repeat by variable: "query0", Max per row: "3"
 - Hit save

![2](https://user-images.githubusercontent.com/54762464/146418212-3519b3a6-4cb8-40cd-a8ef-f07bc6af4aa6.png)

- Refresh the dashboard manually and you will see the 2nd and 3rd panel go black during refresh
- Make sure, you really hit the "Reload"-Button hard several times in a row to see the flickering

![3](https://user-images.githubusercontent.com/54762464/146418228-c96e4bcf-d181-4639-bca0-4cc6287ce9cc.png)

**Anything else we need to know?**:

I tested the same setup with an old version 8.2.0 and saw no flickering.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Build-in Grafan source "-- Grafana --" Random Walk
- OS Grafana is installed on: Windows 10
- User OS & Browser: Windows 10, Chrome, Edge
- Grafana plugins: no
- Others: no

**Comment by Elfo404** [comment]
Hello @philipklever thanks for reporting this.

I'm able to reproduce this also on main, and for me, it happens every time I press the refresh button, and it's not limited to the table panel (I'm experiencing the same with the time series panel)

**Comment by ashharrison90** [comment]
looks like this is a side effect of https://github.com/grafana/grafana/pull/42828, but we need this to fix a different bug. 

looking deeper into the code to see if we can find a fix. 🚧 🔧

**Comment by CD-UNCC** [comment]
this issue if affecting all of our in house dashboards operating on grafana cloud. Is there a way to rollback what version we are using on grafana cloud?

**Comment by dgrr** [comment]
> this issue if affecting all of our in house dashboards operating on grafana cloud. Is there a way to rollback what version we are using on grafana cloud?

This issue is still present in grafana cloud
