### ISSUE TITLE
Configuration documentation is outdated

### ISSUE THREAD

**Issue by jazzzz** [grafana/grafana#4323]
There are some options in [`defaults.ini`][1] that are not documented in the [configuration documentation][2], like the Redis support for the sessions.

[1]: https://github.com/grafana/grafana/blob/v2.6.0/conf/defaults.ini
[2]: http://docs.grafana.org/installation/configuration/

**Comment by bergquist** [comment]
Thank you for noticing this. 
I'm adding it to master now but the site wont be updated before we release 3.0 beta.
