### ISSUE TITLE
Links in dropdown

### ISSUE THREAD

**Issue by Cheesman97** [grafana/grafana#4324]
Is there a posility to put links in a dropdown like the dashboards?
![image](https://cloud.githubusercontent.com/assets/16607523/13668667/81abbe46-e6be-11e5-9db9-d504d77e60ff.png)
So it would be possible to link to a scripted dashboard.

**Comment by bergquist** [comment]
No that's not possible at the moment. You have to add each link by them self. We will work on improving scripted dashboards in the future to treat them more like regular dashboards. Not sure when thou.
