### ISSUE TITLE
[Bug] Viewer can see "New" and "Import" in menu

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4326]
We allow everyone to view grafana inside of our internal network. We don't allow everyone to manage dashboards. Legitimate users are sometimes unaware that they are not logged in and start a new dashboard. They can't save and often lose their work when they realize the issue.

![screenshot from 2016-03-10 09-08-05](https://cloud.githubusercontent.com/assets/3432/13671792/07006ad4-e6a0-11e5-81ed-06416ad52f00.png)

**Comment by bergquist** [comment]
Thank you for reporting this!

**Comment by denis-soundcloud** [comment]
:heart:
