### ISSUE TITLE
[Bug] Table panel using Annotations does not get 'Text' and 'Tags' from Graphite events

### ISSUE THREAD

**Issue by mcallaway** [grafana/grafana#4327]
Grafana 2.6 on Linux with Graphite data source, trying out the new Table panel, making a table of Graphite events. I can see my table, which is non-empty. The columns are Time, Title, Text and Tags.

The bug is that Text and Tags are always empty. Title appears to come from the graphite target expression. In my example I'm doing:

    alias(events("mytag"),"The thing used as the title")

I believe "Text" should map to the "data" attribute of the graphite event, and the "Title" should map to the "what" attribute of the graphite event, and "Tags" should be the graphite event tags.

This can be seen also in the grafana.playground example:

http://play.grafana.org/dashboard/db/annotations

If I add a new row, add table panel, remove any metric query, select Annotations, remove any row formatting options, you can see what I'm talking about.

![screen shot 2016-03-10 at 9 44 05 am](https://cloud.githubusercontent.com/assets/517288/13675317/9cd1787c-e6a6-11e5-9a2b-9fb356491342.png)

I see that the query used aren't really graphite events, but really graphite metrics used in functions. Create a graphite event with something like:

    curl -k -X POST "https://graphite/events/" -d '{"what": "This is what", "tags": "thetag", "data": "This is text in the data field" }

I would want the Grafana Table entry to then be:

    Time               |     Title            |   Text      |     Tags
    <timestamp>  |   This is what  |  This is text in the data field    |   thetag

**Comment by torkelo** [comment]
you cannot you the graphite expression query field if you want graphite to return events data, you need to use the events field if you want grafana to query graphite using the events api. If you use the target expression input grafana will issue a metric query, your query `alias(events("mytag"),"The thing used as he title")` when issued to graphite does not return any text or tags data.  (the render graphite query api does not support that)
