### ISSUE TITLE
[bug - minor] when viewing plugin pages, log contains 404 for logo image link 

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#4328]
Version: grafana master as of 3/10/16 running on Mac OS X 10.11.3
When viewing the plugin page for the nginx-app plugin (http://127.0.0.1:3000/plugins/nginx-app/edit), the JavaScript console and the grafana-server's log both show a 404 for this URL: `/{{ctrl.model.info.logos.large}}`

The exact log entry is:
```
2016/03/10 17:10:53 [I] Completed 127.0.0.1 admin "GET /{{ctrl.model.info.logos.large}} HTTP/1.1" 404 Not Found 5563 bytes in 942us
```
The plugin's logo is still visible. (That is, the substitution in `public/app/features/plugins/partials/edit.html` for `ctrl.model.info.logos.large` appears to be made.)
A minor bug, but I thought I'd report it.

**Comment by torkelo** [comment]
the plugin list and plugin page are not really completed yet, but thanks for informing me about this issue, will fix soon :)

**Comment by torkelo** [comment]
this this is fixed now
