### ISSUE TITLE
CloudWatch: Handle new error codes for MetricInsights

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#43283]
<sup>Originally posted by **sunker** December 17, 2021</sup>
When support for [Metrics Insights](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/query_with_cloudwatch-metrics-insights.html) was added to the GetMetricData api, a few new error codes were introduced. These should be handled as an error or possibly as a warning. 

![Screenshot 2021-12-09 at 18 46 54](https://user-images.githubusercontent.com/2388950/146552415-c7ecf2fa-b5da-4150-8df7-b9017be609d6.png)

</div>

**Comment by amustaque97** [comment]
Hi @sunker, I would love to take this issue. Would you mind sharing some more details like relevant files and steps to validate my changes are working or not!

**Comment by sunker** [comment]
Sure! This code for this should be pretty straight forward, but you might need to have a data in your AWS account to be able to test it. 

The GetMetricData response looks like [this](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html#API_GetMetricData_Example_1_Response). On the top level response array, it includes messages with errors and/or warnings. We want to loop through these messages and look for error codes that matches the error codes above. If so, we can return a warning (not error) that indicates to the user that something happened that might affect the result. 

We already handle warnings in a similar way when the error code `MaxMetricsExceeded` is returned by the api. You can take a look at the code [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/response_parser.go#L53-L55). If this warning is returned in the cloudwatch response, we append a notice to the data frame (see [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/response_parser.go#L193-L198)). When the severity level is set to `data.NoticeSeverityWarning`, a warning icon will be displayed on the top of the panel. If you hover over the icon, you'll see the warning text. 

If you have more than 100 (could be 500) metrics in aws, you can reproduce this pretty easily by adding an empty search expression in the CloudWatch query editor. 
e.g `SEARCH('', 'Sum', 300)`

![Screenshot from 2022-01-05 09-56-51](https://user-images.githubusercontent.com/2388950/148191438-8cd70392-515e-4cba-9e7d-66aaa3948f86.png)

Some of the new error codes might be hard to reproduce, but MaxQueryTimeRangeExceeded should be simple - you just increase the time range in grafana until the warning is returned. 

Please let me know if you need any guidance!

**Comment by amustaque97** [comment]
Hi @sunker , appreciate for such a long and descriptive reply :clap: I connected my AWS account and tried different options as suggested by you. Looks like I'm not able to reproduce this behaviour. I printed the GetMetricData response on console and it looks like this if I try to follow description column in the above description image.

I checked online as well but couldn't find any docs/code/mention of all the 3 error codes.

![image](https://user-images.githubusercontent.com/21127788/149017371-4712080b-f2cd-4d79-8230-796e8db9cf40.png)

**Comment by Gabrielopesantos** [comment]
Hello, is this still being worked? If not, can I take this issue? Thanks in advance.

**Comment by amustaque97** [comment]
> Hello, is this still being worked? If not, can I take this issue? Thanks in advance.

Feel free to pick it up. Good luck 😃

**Comment by Gabrielopesantos** [comment]
I also did a few research and testing but could not find anything related to the error codes specified in this issue.  Is this still an issue?

I still made some changes that handle these new error messages and show them as warnings (with the text specified in the first message). Let me know if it is worth opening a pull request for this.

**Comment by sunker** [comment]
Hi @Gabrielopesantos! Some of these errors might be hard to repro, but I might be able to help out with that. Please open a draft PR and assign it to me and I'll take a look.
