### ISSUE TITLE
Unified Alerting: Grafana deletes all alerts after disabling unified alerting

### ISSUE THREAD

**Issue by filewalkwithme** [grafana/grafana#43303]
**What happened**:
After disabling unified alerting, Grafana deletes all alerts created under unified alerting, not being able to recover it, even after enabling UA again. 

**What you expected to happen**:
Grafana should preserve alerts created under unified alerting, even if the user downgrade to legacy alerting and then upgrade it again.

**How to reproduce it (as minimally and precisely as possible)**:
- Start Grafana with Unified Alerting enabled
  - [unified_alerting][enabled]=**true**
- Create new alerts
- Restart Grafana with Unified Alerting disabled
  - [unified_alerting][enabled]=**false**
- Alerts are not there anymore
- Restart Grafana with Unified Alerting enabled
  - [unified_alerting][enabled]=**true**
- Alerts **are not there anymore**

**Anything else we need to know?**:

**Environment**:
- Grafana version:
Seen with 8.3.3 and 8.2.7

- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by armandgrillet** [comment]
We could migrate once, the first time a user enables UA. The second time a user switch back we don't do anything. When they switch again we don't migrate and return a warning stating that we are now migrating as the table is not empty. We could provide a flag to forge the migration again.

**Comment by filewalkwithme** [comment]
> We could migrate once, the first time a user enables UA. The second time a user switch back we don't do anything. When they switch again we don't migrate and return a warning stating that we are now migrating as the table is not empty. We could provide a flag to forge the migration again.

I liked that approach. It would mitigate the risk of losing data when experimenting with Unified Alerting.

**Comment by santihernandezc** [comment]
@filewalkwithme just to let you know, I made a [design doc](https://docs.google.com/document/d/1waqgEb6fy7WEZk06oa8NdQi4G0Xlwca0nvOIzR8ORSE/edit) for this and we're currently discussing which proposal to move forward with.

**Comment by santihernandezc** [comment]
Closing this since we have a safeguard in place, and we decided that this safeguard is enough to prevent further incidents. Check the [design doc](https://docs.google.com/document/d/1waqgEb6fy7WEZk06oa8NdQi4G0Xlwca0nvOIzR8ORSE/edit) for more details.
