### ISSUE TITLE
Stat panel value wrong when range 6h or more

### ISSUE THREAD

**Issue by B3DTech** [grafana/grafana#43300]
**What happened**:
I have a stat panel that I’m using to display a metric pulled from Zabbix. The metric is a value taken every 1 minute. I’m using the stat panel value option calculate total so sum the individual values returned by the metic. When I’m editing the metic, it shows the correct value (e.g. 18).

When I go to the dashboard and refresh it, the value is roughly half what it should be, 9.17 for a 6 hour range.  For a 12 hour range, it becomes 3.71, and 1.88 for a 24 hour range.

It appears that it's using the range in the calculation, however it should be a total, so taking the values and summing them, regardless of the range. 

![Kapture](https://user-images.githubusercontent.com/32655512/146600447-682f1a7a-a608-4e0e-b5c2-b611700bf96d.gif)

**What you expected to happen**:

The correct sum of 18 should be consistent for any time range of 6 Horus or more.

**How to reproduce it (as minimally and precisely as possible)**:

Create a stat panel using a metric from zabbix.  Set the panel value option calculate total.

**Anything else we need to know?**:

**Environment**:
- Grafana version:  8.3.3
- Data source type & version:  Zabbix 4.2.4
- OS Grafana is installed on:  CentOS 7
- User OS & Browser:  OS X Safari
- Grafana plugins:  Zabbix

**Comment by B3DTech** [comment]
One more thing of note, the values that Zabbix gets and are stored in the Zabbix DB are whole numbers only. There's no way it should ever be a decimal.

**Comment by torkelo** [comment]
It's not an issue with the Stat panel, but must be something with the query, maybe you need to add a sum aggregation function to the query? Not sure how zabbix handles aggregation

**Comment by B3DTech** [comment]
Why do you say it's not an issue with stat panel? 
I have 300 points being returned by my Zabbix query, 16 of them with a value of 1, and 284 with a value of 0.  Why would stat panel return anything other than a whole number when using the Total function?

**Comment by B3DTech** [comment]
Again, when I view it in edit mode, it is always 100% correct.  It is only when I'm viewing it on the dashboard that it display wrong.  

When inspecting in edit mode:

12/20/21 8:40 | 0
12/20/21 8:41 | 0
12/20/21 8:42 | 1
12/20/21 8:43 | 1
12/20/21 8:44 | 0
12/20/21 8:45 | 0
12/20/21 8:46 | 0
12/20/21 8:47 | 0
12/20/21 8:48 | 0
12/20/21 8:49 | 0
12/20/21 8:50 | 0
12/20/21 8:51 | 0
12/20/21 8:52 | 0
12/20/21 8:53 | 0
12/20/21 8:54 | 0
12/20/21 8:55 | 0
12/20/21 8:56 | 0
12/20/21 8:57 | 0
12/20/21 8:58 | 0
12/20/21 8:59 | 0
12/20/21 9:00 | 0
12/20/21 9:01 | 0
12/20/21 9:02 | 0
12/20/21 9:03 | 0
12/20/21 9:04 | 1
12/20/21 9:05 | 0
12/20/21 9:06 | 0

When inspecting the panel on the dashboard the values are wrong, returning decimals. 
2021-12-19 23:05:00
0
2021-12-19 23:10:00
0
2021-12-19 23:15:00
0.200
2021-12-19 23:20:00
0

**Comment by B3DTech** [comment]
And this impacts only the stat panel.  The same exact query on a time series graph is perfectly fine, with the query returning whole numbers only.

**Comment by B3DTech** [comment]
@alexanderzobnin - does this sound like an issue with the Zabbix plugin or possibly with the Grafana Stat Panel?

**Comment by B3DTech** [comment]
Also interesting is if I drag to zoom in on a range, I get the following error several times, but only on this dashboard:
Error
json: cannot unmarshal number 1640103091.778 into Go struct field TimeSeriesData.series.TS of type int64

Other dashboards that use the Zabbix plugin don't have this issue.
