### ISSUE TITLE
Bar Gauge - Vertical view flips direction with data links

### ISSUE THREAD

**Issue by Rushmed** [grafana/grafana#43306]
**What happened**:  After update 8.3.2 --> 8.3.3 Bar gauge panel graphs with vertical views flip in opposite direction

**What you expected to happen**: As before the view of the panel should be independend of adding data links.

**How to reproduce it (as minimally and precisely as possible)**:
Panel without data link:
![image](https://user-images.githubusercontent.com/59259796/146612740-3a07de30-f98d-4137-a9a1-6390d24f0911.png)

Panel with data link (wrong):
![image](https://user-images.githubusercontent.com/59259796/146612802-67a0bb40-c68b-4739-bd43-f9cfe9fe20e8.png)

**Anything else we need to know?**:

**Environment**: Pi4
- Grafana version: 8.3.3
- Data source type & version: InfluxDB
- OS Grafana is installed on: RaspiOS Bullseye
- User OS & Browser: Chrome Windows, Samsung Internet Android
- Grafana plugins: Bar Gauge
- Others:

**Comment by restorepoint1** [comment]
Hello! Also there is wrong bar alignment and unfilled area height & alignment when data links are used
With data link
![image](https://user-images.githubusercontent.com/87772055/146874947-1b8951a2-ef22-4604-b3a7-08008c266e53.png)

Without data link
![image](https://user-images.githubusercontent.com/87772055/146874955-d451c007-f845-400b-a79c-42ee7980521f.png)

**Comment by curiousbaker** [comment]
I get this issue in version 9.1.0 and 9.1.3
