### ISSUE TITLE
Turn off Web Auth

### ISSUE THREAD

**Issue by Commander-Crash** [grafana/grafana#43318]
Look I'll get strait to it. I have nothing to hide with my graphs I would like it so i would not have to log in. It is very irritating that it logs me out almost every hour. I have no need to password protect something i could care less if it leaks. I'm more in danger of my password being leaked then my graph info. Please have a way to turn web login off thanks.

**Comment by zuchka** [comment]
Hi @Commander-Crash 

here are some config settings you can explore using:
- https://grafana.com/docs/grafana/latest/administration/configuration/#login_maximum_inactive_lifetime_duration
- https://grafana.com/docs/grafana/latest/administration/configuration/#login_maximum_lifetime_duration
- https://grafana.com/docs/grafana/latest/administration/configuration/#disable_login_form
