### ISSUE TITLE
Grafana override value mappings is not working for multiple regex options

### ISSUE THREAD

**Issue by eugenegoncharuk** [grafana/grafana#43332]
**What happened**: Tried to use Override value mappings feature for Table widget with multiple regex options.

**What you expected to happen**: Expected that all the regex mappings a processed one by one and all the data is replaced correctly.

**How to reproduce it (as minimally and precisely as possible)**: 
Have a timeseries data like:
"first row"
"second row"

Create a new Override value mappings with two regex, like 
.\*first.\* -> 1
.\*second.\* -> 2

**What I see**: Only first regex with mapping  .\*first.\* -> 1 is used and data is replaced.

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: Any
- User OS & Browser: Chrome
- Grafana plugins: No

**Comment by zuchka** [comment]
Thanks for creating this issue, @eugenegoncharuk 

multiple regex value mapping appears to work on Grafana 8.3.3. [Check out this dashboard](https://play.grafana.org/d/-7xxVYo7k/regex-value-map-test?orgId=1&editPanel=2&showCategory=Override%201):

![CleanShot 2021-12-22 at 15 26 11@2x](https://user-images.githubusercontent.com/37156449/147173715-01957019-62ce-437e-bc2b-e77bdab22b8f.png)
