### ISSUE TITLE
[Bug] Incorrect stacked values on legend and tooltip

### ISSUE THREAD

**Issue by ilgizar** [grafana/grafana#4333]
If you make multiple stacks, the values in the legend and in the tooltip are calculated incorrectly. This is due to the fact that you are using a scalar variable instead of an array to store the last value.
[stacked value patch](http://paste.ofcode.org/WZwJXFVYQNsNtaFMSkgPgm)

**Comment by cincodenada** [comment]
This should be closed, as this option is already available by choosing "individual" for "Stacked Value" in the "Display" tab of the graph options.
