### ISSUE TITLE
Cannot get context menu for first point in time series

### ISSUE THREAD

**Issue by Sahtair** [grafana/grafana#43342]
**What happened**:
When clicking on the first (or the only point if a time series only has one point) we do not get the context menu, which is an issue if we have data links. In the screenshots below we can see that clicking on the first point we do not get it and then if we click on the next one we do.
![Screenshot 2021-12-20 at 11 38 27](https://user-images.githubusercontent.com/11059126/146754972-623cc90d-6f6c-4a6a-a1b6-b34344b8ae40.png)
![Screenshot 2021-12-20 at 11 39 07](https://user-images.githubusercontent.com/11059126/146754982-f48620ce-ca93-4dff-9aaa-e0e6655dde35.png)

**What you expected to happen**:
We get the context menu when clicking on the first point in the series 
**How to reproduce it (as minimally and precisely as possible)**:
Here is a gist of the minimal reproducible example https://gist.github.com/Sahtair/250456a026086ccadab28a07c845dcff
**Anything else we need to know?**:
/
**Environment**:
- Grafana version: 8.4.0-pre (also observed on older versions)
- Data source type & version: TestData DB
- OS Grafana is installed on: macOS X Big Sur 11.4
- User OS & Browser: macOS X Big Sur 11.4 & Chrome Version 96.0.4664.110 
- Grafana plugins: /
- Others: /

**Comment by zuchka** [comment]
@Sahtair can you please visit this public dashboard and see if the tooltip appears on hover?

https://play.grafana.org/d/oumMKhonk/mja-test?orgId=1&from=1639981870098&to=1639981870150

It appears for me. I based this in your gist. Let us know what you see so we can drill down on the issue here 👍 

![CleanShot 2021-12-20 at 14 58 01@2x](https://user-images.githubusercontent.com/37156449/146853075-8da46a8b-6d9c-467e-9b9d-ed707f69ac44.png)

**Comment by Sahtair** [comment]
@zuchka I am sorry if I was not clear enough. The hover is not the problem the **clicking** on the point is. It is a problem if you have data links setup and you cannot click on the point and get the context menu with the links. Also I do not have access to this dashboard. Looking at another dashboard in the play I can see that I do not get the menu like I expected to.
https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&from=1640069390137&to=1640069498872
![image](https://user-images.githubusercontent.com/11059126/146891816-ada001d8-e710-4662-93c1-99f17dc57134.png)

**Comment by ivanahuckova** [comment]
I was able to reproduce this on grafana play as well:
https://user-images.githubusercontent.com/30407135/148068545-e5aa676d-efaa-43f4-aba3-83d56a8d4497.mov

**Comment by ivanahuckova** [comment]
@grafana/grafana-bi-squad @Sahtair also created a fix for this issue: https://github.com/grafana/grafana/pull/43344 🙏 🧡
