### ISSUE TITLE
Only one datasource used with multi-value datasource selection

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#43351]
**What happened**:
When more than two influxdb datasources are selected, only one of them is shown. The one shown seems to be the one that was first selected. Also in panel/inspect, only one datasource is active.

**What you expected to happen**:
I expected the values from all selected datasources to be shown.

**How to reproduce it (as minimally and precisely as possible)**:
* Create at least two influxdb datasources
* Create a datasource template variable
* Create a graph panel and using metrics from selected datasource:
![image](https://user-images.githubusercontent.com/6523124/146763527-d190a624-e091-40e0-8fa2-4e72f6911b53.png)
* enable multi-value on datasource template variable
![image](https://user-images.githubusercontent.com/6523124/146762126-0cb4af0c-bfac-43da-991b-254dd4ef4be6.png)
* Select more than one datasource, and only one is visualized:
![image](https://user-images.githubusercontent.com/6523124/146762305-d8cb6d7c-a582-4bae-907d-b05be7cdb099.png)
![image](https://user-images.githubusercontent.com/6523124/146762802-9733fa4f-1ccf-46d6-99f8-67c77a4a77cd.png)

Also when inspecting the data, only one datasource is shown:

**Anything else we need to know?**:
When I single-select a datasource, it shows up normally:
![image](https://user-images.githubusercontent.com/6523124/146762495-43804ea0-758d-42e9-8be2-c661cbf02e33.png)

**Environment**:
- Grafana version: 8.3.3 (also in 8.1.3)
- Data source type & version: influxdb 5.0.0 (core)
- OS Grafana is installed on: Ubuntu 20.04.3 LTS
- User OS & Browser: Ubuntu 20.04.3 LTS & firefox 95
- Grafana plugins: core
- Others:

**Comment by torkelo** [comment]
a multi-valued data source variable only works for repeated panels, so you need to go into panel options / repeating, and select the data source variable, Then the panel will be repeated for every data source you selected

**Comment by bijwaard** [comment]
Thanks Torkel,
It is a pity that I cannot show them in the same graph, that would make it easier to compare the them.
Kind regards,
Dennis
