### ISSUE TITLE
Azure AD OAuth: Grafana does not fetch user groups when #groups > 200 (Does not support distributed claims)

### ISSUE THREAD

**Issue by ThomasMarcelis** [grafana/grafana#43356]
**What happened**:
For users who are member of more than 200 azure AD groups, the groups are not being parsed and the Team Sync feature is broken

**What you expected to happen**:
The groups are correctly parsed upon login for all users.
Grafana should support distributed claims as per the official OIDC spec

**How to reproduce it (as minimally and precisely as possible)**:
1. Create an app registration in Azure, configure auth.azuread in grafana.ini to use this app registration (URLs, client secret).
2. Add a user to this app registration/enterprise application who is a member of 200+ groups
3. Attempt to login with this user
4. Note the following line in the logs:
t=2021-12-09T14:34:58+0000 lvl=dbug msg="AzureAD OAuth: extracted groups" logger=social email=xxx@yyy.com groups=[]

**Anything else we need to know?**:
In Azure, if a user is indirectly a member of more than 200 groups, Azure will send _claim_names and _claim_sources instead of the groups, per OIDC Core 1.0, section 5.6.2:
https://openid.net/specs/openid-connect-core-1_0.html#AggregatedDistributedClaims

Example:
```
{
  "_claim_names": {
    "groups": "src1"
  },
  "_claim_sources": {
    "src1": {
      "endpoint": "https://graph.windows.net/{orgId}/users/{userId}/getMemberObjects"
    }
  }
}
```
The groups then have to be fetched in a separate request

longform explanation in someones blog post: http://www.mattruma.com/adventures-with-azure-ad-group-overage-claim/

**Environment**:
- Grafana version: 8.3.3 enterprise
- Data source type & version:
- OS Grafana is installed on: Default official container (Alpine)
- User OS & Browser: Windows 10, chrome
- Grafana plugins: -
- Others:

**Comment by andresmgot** [comment]
This is already being handled by @kalleep @alexanderzobnin and @sakjur so removing this from cloud-datasources dashboard. Let us know if we can help!
