### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by zzphamvanthanhzz** [grafana/grafana#4336]
Hi everyone,

I'm using Grafana for monitor our service, Grafana is so good.
I'm building it from source following the instruction: _http://docs.grafana.org/project/building_from_source/_. Every thing works well except one problem: every time loading page, it request so many _js_ file, which takes lost of time (as attached image).
How can I build Grafana and concat all js files into one file?

Thanks alot.
![screenshot from 2016-03-11 16-31-37](https://cloud.githubusercontent.com/assets/12881155/13698818/0f5667b0-e7a9-11e5-8b97-7f72d0daa361.png)

**Comment by torkelo** [comment]
http://docs.grafana.org/project/building_from_source/#creating-optimized-release-packages 

"grunt build" will optimize frontend assets (concat and minify js) 

"grunt release" -> create standalone release tar/zip 

"go run build.go build package" -> creates deb & rpm packages   (requires fpm to be installed)
