### ISSUE TITLE
[Feature Request] Show error panel when it uses a missing/broken plugin

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4337]
As it is now, if you have a dashboard containing a missing plugin, there are some gaps where the plugin panels should be. This is confusing and there's no easy way for the user to remove/reorganize the panels.

I think a dummy panel stating that "Plugin X is missing/broken" would be a big improvement to Grafana

**Comment by torkelo** [comment]
this is already implemented in Grafana 3.0 (master), if dashboard is opened containing a panel type that has not been installed grafana will load a "UnkownPanel" instead, that is just an empty panel informing you what panel type was not found, you can then remove the panel if you want.

**Comment by vitorboschi** [comment]
Do you know when it was merged in master? I'm pretty sure I tested in a recent nightly (from this week) and this was still happening. In my case, the plugin was not missing, but it was broken (early version, not compatible with the current version)

**Comment by torkelo** [comment]
that case is much harder to solve, if there is a bug in a panel, then it is kind of too late to show another panel. But if it is missing then grafana can show another panel.

**Comment by vitorboschi** [comment]
Got it. Thanks for the info
