### ISSUE TITLE
Influxdb 2.x and Grafana's understanding of time is "different"

### ISSUE THREAD

**Issue by Sineos** [grafana/grafana#43378]
**What happened**:
I cannot get Graphs to be displayed with a local timezone and getting same results in simple queries 

**What you expected to happen**:
Set local timezone to have proper time values and return correct query results

**How to reproduce it (as minimally and precisely as possible)**:

### Case 1: Local timezone in Grafana and query range today
![grafik](https://user-images.githubusercontent.com/4459312/146812899-22d5523b-9ddb-42df-a333-650e82cb574e.png)

Left query:
```
from(bucket: "home")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "vzlogger")
  |> filter(fn: (r) => r["Source"] == "S0_EG")
  |> filter(fn: (r) => r["_field"] == "Energy")
  |> aggregateWindow(every: 10s, fn: distinct, createEmpty: false)
```

Right query:
```
from(bucket: "home")
  |> range(start: today())
  |> filter(fn: (r) => r["_measurement"] == "vzlogger")
  |> filter(fn: (r) => r["Source"] == "S0_EG")
  |> filter(fn: (r) => r["_field"] == "Energy")
  |> aggregateWindow(every: 30s, fn: distinct, createEmpty: false)
```
Right query is using the [today()](https://docs.influxdata.com/flux/v0.x/stdlib/universe/today/) function as I want to have a fixed range that does not modify when using Grafana' selector

![grafik](https://user-images.githubusercontent.com/4459312/146814063-a6784ca4-5a31-4692-9d0e-b46b9eaf3b01.png)

Result:
- Left query is the expected result
- Right query using `today()` function is 1h off
- My graphs display nicely with my current time

### Case 2: UTC timezone in Grafana and query range today

Same queries as above. Only Grafana timezone changed to UTC

![grafik](https://user-images.githubusercontent.com/4459312/146814657-44f6be69-39ee-4887-b2b0-af5b76ca0f21.png)

Result:
- Left query is the expected result
- Right query is the expected result
- My graphs are off for 1h

### Case 3: Timezone settings in Flux-Query

Left query:
```
from(bucket: "home")
  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)
  |> filter(fn: (r) => r["_measurement"] == "vzlogger")
  |> filter(fn: (r) => r["Source"] == "S0_EG")
  |> filter(fn: (r) => r["_field"] == "Energy")
  |> aggregateWindow(every: 10s, fn: distinct, createEmpty: false)
```

Right query:
```
import "timezone"
timezone.location(name: "Europe/Berlin")

from(bucket: "home")
  |> range(start: today())
  |> filter(fn: (r) => r["_measurement"] == "vzlogger")
  |> filter(fn: (r) => r["Source"] == "S0_EG")
  |> filter(fn: (r) => r["_field"] == "Energy")
  |> aggregateWindow(every: 30s, fn: distinct, createEmpty: false)
```

Right query is using the [timezone.location](https://docs.influxdata.com/flux/v0.x/stdlib/timezone/location/) function in an attempt to solve the problem. Results are the same as in Case 1 und Case 2, respectively.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.3 (30bb7a93c)
- Data source type & version: InfluxDB 2.1.1
- OS Grafana is installed on: Ubuntu 20.04.3 LTS
- User OS & Browser: Windows 10 / Firefox
- Grafana plugins: none
- Others: n/a

**Comment by zuchka** [comment]
@Sineos have you explored using Grafana's global variables, and specifically the time macros that work with InfluxDB?

- https://play.grafana.org/d/000000083/influxdb-raw-query-template-var?orgId=1&editPanel=1
- https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/

**Comment by Sineos** [comment]
@zuchka Thanks.
Sorry, I fail to see how this relates to this issue.
In my understanding this boils down to a different handling of influxDB built in function like `today()` and Grafana's handling of timestamps / timezones. `today()` does not Grafana's global variables.

Any explanation would be appreciated.

**Comment by zuchka** [comment]
@Sineos I'm not very proficient at Influx, so I can't speak too intelligently here. I was only suggesting that you try and use Grafana's time macros and see what happens.

I encourage you to ask this question on the forum. There are some influx wizards in there who will have more input 👍
