### ISSUE TITLE
When trying to edit a query in a panel and save the dashboard, a validation error is displayed: "tags is not a valid field"

### ISSUE THREAD

**Issue by effiban** [grafana/grafana#43377]
**What happened**:
After editing a query in the panel UI, and trying to save the dashboard - I get a validation error on the top right: "tags is not a valid field". 
- I tried to fix by editing the json directly and removing the "tags" field which was set to an empty array. When I saved it it succeeded (and the tags field was gone) - but then when I tried again to edit the query in the UI I got the same error.
- I also tried to edit the query in the json directly, but the same error appeared again...

**What you expected to happen**:
Dashboard saved successfully

**How to reproduce it (as minimally and precisely as possible)**:
We have a hosted graphite instance of our organization and I can only reproduce there:
1) Open the following dashboard (if permitted): https://ks.hostedgraphite.com/bc0087a2/grafana/d/b1G5KYYWz/eii-ecomm-insights-ingestor?orgId=2
2) Edit one of the queries , then press "Save".

**Environment**:
- Grafana version: ?
- Data source type & version: ?
- OS Grafana is installed on: ?
- User OS & Browser: Ubuntu 18, Chrome 96.0.4664.110
- Grafana plugins: ?
- Others:

**Comment by effiban** [comment]
@yinong @lior-gershony @navaco - this is preventing me from fixing one of the panels in the E2 dashboard after I refactored the metric name.
Have you possibly seen this happen before?

**Comment by zuchka** [comment]
@effiban sorry, your link didn't work. Wondering if it might be more effective to contact hostedgraphite about this issue? the squads can't do much without a Grafana version and a method to reproduce bugs that succeeds outside of a third-party service like hostedgraphite.com
