### ISSUE TITLE
[BUG] build in docker not enable InfluxDB

### ISSUE THREAD

**Issue by gavinzhou** [grafana/grafana#4338]
I build grafana in docker with alpine
add datasource influxdb

```
2016/03/11 15:31:51 [I] Completed 153.216----------- admin "POST /api/org/plugins/influxdb/settings HTTP/1.1" 404 Not Found 23 bytes in 658us
```

**Comment by bergquist** [comment]
@gavinzhou Thank you for reporting this! This was fixed by https://github.com/grafana/grafana/commit/85466c7ee1ce5299ed67943a42ee7c8f10fef3ae should be available on docker soon.
