### ISSUE TITLE
Grafana getting 404 response from Influxdb 8.9

### ISSUE THREAD

**Issue by alpsla** [grafana/grafana#4339]
Hi, 
I have a grafana 2.0.2
InfluxDB 0.8.9
InfluxDB has some data and reports https://gyazo.com/b571097f31922223bc44b5f5653d7d90
I set up a new dashboard which shows me an error InfluxDB Error without description https://gyazo.com/c2040b8d735d5144d4d2b5a99637fb04
Network tab from Dev tool shows me 404 https://gyazo.com/2c681a036959e4e37a4f700177f28ce6
Console's screen shows InfluxDB error https://gyazo.com/5900ca9c3d30b9bbeb17fb1398e5451d
Please advise.
Thanks,
alpsla

**Comment by torkelo** [comment]
dont know why your InfluxDB return 404, please ask in influxdb mailing list or project on github
