### ISSUE TITLE
CloudWatch: regression affecting some metrics not being pulled

### ISSUE THREAD

**Issue by gchamon** [grafana/grafana#43405]
**What happened**:
Using grafana cloud, we suddenly stopped receiving data from some AWS/ES namespace metrics, namely `Shards.active` and `Shards.unassigned`, which we use to monitor shard limits in our Elasticsearch cluster.

Importing the dashboard `11655` into grafana, we see that most of the panels are missing data:

![image](https://user-images.githubusercontent.com/9471861/146966987-eb6f0ea2-f1d2-49e0-b228-f393cb865bd4.png)

I first launched a docker container with the latest grafana version and reproduced the problem locally, just to make sure nothing was particularly off with our Grafana Cloud configuration. I then launched a docker container locally with version 8.1.8 and was able to view the dashboard metrics successfully:

![image](https://user-images.githubusercontent.com/9471861/146967068-eec56f70-385c-4c2f-bc81-7136ae0072b9.png)

The kibana status, specifically, shows an error message:

![image](https://user-images.githubusercontent.com/9471861/146922224-ef6c419c-174c-4936-9498-530d3e846db9.png)

Since this is still working in an earlier version of grafana, the problem seems to be a regression in the latest version.

**What you expected to happen**:

I expected to have the metrics from AWS/ES collected, just like in earlier versions of grafana.

**How to reproduce it (as minimally and precisely as possible)**:

- Create a Elasticsearch (now Opensearch) cluster in AWS
- Configure cloudwatch plugin
- Add the AWS Elasticsearch dashboard number `11655`
- Check that most metrics are missing
- Do the same with version 8.1.8 and see the metrics are there

**Anything else we need to know?**:

I believe this describes the entirety of the problem.

**Environment**:
- Grafana version: v8.3.3 (30bb7a93c)
- Data source type & version: CloudWatch 5.0.0
- OS Grafana is installed on: Cloud
- User OS & Browser: Arch Linux, Chromium
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Thanks for reporting this issue @gchamon! 

I think this issue was solved in [this](https://github.com/grafana/grafana/pull/43350) PR which will be released in January. But just to confirm, can you please share your dashboard?

**Comment by gchamon** [comment]
Hey @sunker , thanks for the response! Glad to see it getting an ack and fix.

The dashboard was imported from https://grafana.com/grafana/dashboards/11655 as is. I believe if you use this dashboard you will be able to reproduce the issue.

**Comment by sunker** [comment]
Thanks for quick reply!

Tested with the latest main and I can confirm it's working. So the fix will come out in 8.3.4 which is planned to be released in January I think. If you don't want to wait until then there's also a workaround. Just open the panel editor for the broken queries. I believe that should run the migration and put the query model in a valid state again. 

I'll close this issue now. Feel free to reopen it if you feel the need to.
