### ISSUE TITLE
[Azure] [query editor UI] monitor aggregation field not updating state

### ISSUE THREAD

**Issue by emnbdx** [grafana/grafana#43402]
**What happened**:
I use timeseries visualisation with azure monitor source to display sql usage (but probably same thing with other data)
When I set aggregation to value different from average (maximum for example) and I cme back to edit my dashboard, value is set to average again :/

**What you expected to happen**:
When I set maximum as aggregation, maximum is selected when I edit again

**How to reproduce it (as minimally and precisely as possible)**:
![Screen Recording 2021-12-21 at 11 21 44](https://user-images.githubusercontent.com/3239701/146917512-2002b65c-4514-46b1-ba07-5712c1eb3f1d.gif)

**Anything else we need to know?**:
I think this is due to data loading.
Average is set by default then data come from azure and don't update list

**Environment**:
- Grafana version: 8.2.7
- Data source type & version: azure monitor native
- OS Grafana is installed on: debian
- User OS & Browser: macos / brave but not seems to be usefull
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @emnbdx 

Can you please share that error message in the corner, as well as anything of interest in the network tab of your browser's dev tools when the panel breaks?

**Comment by emnbdx** [comment]
The error message is not really important, it's due to parameterized query when I take my video.
If I try now I don't have it ;)

I looked to my developer tools and I can see an error about websocket.
`centrifuge.js:544 WebSocket connection to 'wss://watch.helloasso.com/grafana/api/live/ws' failed: `

**Comment by zuchka** [comment]
ok so this issue is more about the query editor not properly maintaining state for the `Aggregatation` field, yes?

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/AggregationField.tsx#L9-L12

**Comment by emnbdx** [comment]
I think so ;)

**Comment by fridgepoet** [comment]
Thanks @emnbdx !
