### ISSUE TITLE
Prometheus: No authorization header to datasource with oauthPassThru enabled

### ISSUE THREAD

**Issue by kschu91** [grafana/grafana#43415]
Since Grafana 8.3 there is no authroization header passed throug to datasource anymore using `oauthPassThru`.

We have a Grafana set up with generic oauth authorization and are passing through OAuth identities to data sources via `oauthPassThru`. This worked well until upgrade to Grafana 8.3. Since 8.3 there is no authroization header passed through anymore, which results in unauthenticated requests against datasources.

I also validated that using pipedream (formerly requestbin) to check headers sent to the datasource:
![image](https://user-images.githubusercontent.com/5566756/146930514-af117f62-f0d2-422f-a746-ef474cfb0936.png)
![image](https://user-images.githubusercontent.com/5566756/146930551-e561f3fe-2e59-410b-816f-21813edc8390.png)

Also, I added some additional logging on a local setup:
https://github.com/grafana/grafana/blob/c1be17bec7bd88be6ab0d2d028c48d03af4105f1/pkg/services/query/query.go#L127
![image](https://user-images.githubusercontent.com/5566756/146931841-19aeb4d6-353e-435f-b3f8-9053e607f214.png)
to ensure that oauth token will be recognized correctly by grafana. Grafana adds the 
token correctly to the request headers. But somewhere on the way down, the headers seems to get lost.

```
DBUG[12-21|13:47:55] Updating last user_seen_at               logger=context userId=2 orgId=1 uname=****** user_id=2
DBUG[12-21|13:47:55] Received command to update data source   logger=datasources url=https://ens73diue5x00vm.m.pipedream.net
DBUG[12-21|13:47:55] Applying default URL parsing for this data source type logger=datasource type=prometheus url=https://ens73diue5x00vm.m.pipedream.net
DBUG[12-21|13:47:55] token needs rotation                     logger=auth tokenId=2 authTokenSeen=true rotatedAt=2021-12-21T13:23:46+0100
DBUG[12-21|13:47:56] auth token rotated                       logger=auth affected=1 auth_token_id=2 userId=2
INFO[12-21|13:47:56] New token                                logger=context userId=2 orgId=1 uname=****** unhashed token=58af2d5c2e462e557ae17165f832f5ac
INFO[12-21|13:47:56] Request Completed                        logger=context userId=2 orgId=1 uname=****** method=PUT path=/api/datasources/1 status=200 remote_addr=[::1] time_ms=282 size=475 referer=http
://localhost:3000/datasources/edit/hHKkqATnk
DBUG[12-21|13:47:56] seen token                               logger=auth tokenId=2 userId=2 clientIP=::1 userAgent="Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
" authToken=7565ee6505623eb1af45fb76c205df1df9b485c08cd3a9f67a6e66f4d2590305
DBUG[12-21|13:47:56] Updating last user_seen_at               logger=context userId=2 orgId=1 uname=****** user_id=2
INFO[12-21|13:47:56] Request Completed                        logger=context userId=2 orgId=1 uname=****** method=GET path=/api/frontend/settings status=200 remote_addr=[::1] time_ms=107 size=3622 referer
=http://localhost:3000/datasources/edit/hHKkqATnk
DBUG[12-21|13:47:56] Updating last user_seen_at               logger=context userId=2 orgId=1 uname=****** user_id=2
INFO[12-21|13:47:56] Request Completed                        logger=context userId=2 orgId=1 uname=****** method=GET path=/api/datasources/uid/hHKkqATnk status=200 remote_addr=[::1] time_ms=50 size=402 r
eferer=http://localhost:3000/datasources/edit/hHKkqATnk
DBUG[12-21|13:47:56] Updating last user_seen_at               logger=context userId=2 orgId=1 uname=****** user_id=2
DBUG[12-21|13:47:56] Querying for data source via SQL store   logger=datasources id=1 orgId=1
DBUG[12-21|13:47:56] Processing metrics query                 logger=query_data query="&{data:map[datasource:map[type:prometheus uid:hHKkqATnk] datasourceId:1 exemplar:false expr:1+1 instant:true interval: intervalMs:60000 legendFor
mat: maxDataPoints:1 queryType:timeSeriesQuery refId:test requestId:0test utcOffsetSec:3600]}"
DBUG[12-21|13:47:56] snowball: oauth pass thru is enabled     logger=query_data
DBUG[12-21|13:47:56] snowball: passing thru access token      logger=query_data access_token=eyJraWQiOiJ2VUFXTzk...
DBUG[12-21|13:47:56] snowball: passing thru id token          logger=query_data X-ID-Token=eyJraWQiOiJkSFkxUUI1aUk5d2tGMjlxMG1o...
DBUG[12-21|13:47:56] Sending query                            logger=tsdb.prometheus start=2021-12-21T12:47:55+0000 end=2021-12-21T12:47:56+0000 step=1m0s query=1+1
EROR[12-21|13:47:59] Instant query failed                     logger=tsdb.prometheus query=1+1 err="Skip: do not know how to skip: 0, error found in #0 byte of ...||..., bigger context ...||..."
INFO[12-21|13:47:59] Request Completed                        logger=context userId=2 orgId=1 uname=****** method=POST path=/api/ds/query status=400 remote_addr=[::1] time_ms=3276 size=126 referer=http://
localhost:3000/datasources/edit/hHKkqATnk
```

Unfortunetly I was not able to find the root cause for this. Maybe this is related to https://github.com/grafana/grafana/pull/42753 or https://github.com/grafana/grafana/issues/42672?

**Environment**:
- Grafana version: 8.3.3 and v8.4.0-pre (18fdb89554)
- Data source type & version: Prometheus (5.0.0)

**Comment by torkelo** [comment]
@ivanahuckova do you remember discussing how to handle OAuth pass through?

**Comment by torkelo** [comment]
similar issue for Elasticsearch, https://github.com/grafana/grafana/issues/43311

**Comment by toddtreece** [comment]
I believe what is happening here is that the headers are added to the `backend.QueryDataRequest`:

https://github.com/grafana/grafana/blob/c1be17bec7bd88be6ab0d2d028c48d03af4105f1/pkg/services/query/query.go#L127-L136

Since the client is instantiated by the instance factory here: 
https://github.com/grafana/grafana/blob/ffc72aa25541a8f3a1930f59f7007a8e8301fd84/pkg/tsdb/prometheus/prometheus.go#L108

It wouldn't have access to the `backend.QueryDataRequest` headers when creating the client here:
https://github.com/grafana/grafana/blob/ffc72aa25541a8f3a1930f59f7007a8e8301fd84/pkg/tsdb/prometheus/prometheus.go#L159-L162

Here's an example of setting headers in the prometheus go client:
https://pkg.go.dev/github.com/prometheus/client_golang/api/prometheus/v1#example-API-QueryRangeWithUserAgent

**Comment by ivanahuckova** [comment]
I am wondering if this could be regression of this PR https://github.com/grafana/grafana/pull/40349

**Comment by ivanahuckova** [comment]
@marefr @dsotirakis I am wondering if this could be regression of #40349 based on @toddtreece's investigation https://github.com/grafana/grafana/issues/43415#issuecomment-999098995? Also, could this be an issue in other data sources that don't create client for each request such as influx?

**Comment by marefr** [comment]
> @marefr @dsotirakis I am wondering if this could be regression of #40349 based on @toddtreece's investigation [#43415 (comment)](https://github.com/grafana/grafana/issues/43415#issuecomment-999098995)? Also, could this be an issue in other data sources that don't create client for each request such as influx?

I don't think so. Only custom headers will automatically be added to outgoing HTTP requests via [middleware](https://github.com/grafana/grafana-plugin-sdk-go/blob/main/backend/httpclient/custom_headers_middleware.go). These custom headers are the ones that the user can edit in the UI when configuring a HTTP data source. 

For making use of this `Authorization` header, it needs to be added manually for any backend data source (core or external). This header will only be populated if the request is coming from a user/UI. If request is coming from for example alerting this will never be populated (there's no OAuth token available).

**Comment by Scotturbina** [comment]
@ivanahuckova Same thing happening to me in https://github.com/grafana/grafana/issues/43311 , mine did not work in 7.2.1 (https://github.com/grafana/grafana/issues/41741) and when I update to 8.3.2 then the pop-up did not appear anymore (which is good) but auth headers are not being reflected in my proxy, anything you need, please let me know how I can help
