### ISSUE TITLE
Connect null values set to Never with topk queries does not work

### ISSUE THREAD

**Issue by michaelkebe** [grafana/grafana#43410]
**What happened**:
I am using a prometheus query in a panel which uses the `topk` [prometheus aggregation operator](https://prometheus.io/docs/prometheus/latest/querying/operators/#aggregation-operators). Because of `topk` just shows the top `n` values it can happen, that one metric is only in the first part of query result and in the last part of the query result, but in between it is not, because it is not in the `n` values. Grafana connects the first and last part even though Connect nulll values is set to never.

**What you expected to happen**:
The line should be not connected, because the query does not return values in the middle part of the query.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I think that this problem also applies to `bottomk` and maybe other aggregation operators.

**Environment**:
- Grafana version: 8.3.2
- Data source type & version: prometheus 2.26.0
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 Chrome
- Grafana plugins: -
- Others: -

**Comment by torkelo** [comment]
> The line should be not connected, because the query does not return values in the middle part of the query.

For Grafana to know this Prometheus would need to return null values for the missing values, which it does not. if prometheus did return null values you would see a gap there.

**Comment by krzysion** [comment]
This behaviour has only occurred since upgrading from Grafana 8.2.7 to 8.3.x.
8.2.7:
![2021-12-21 22_00_31-Window](https://user-images.githubusercontent.com/36912975/146997288-431cbace-79f9-4052-842d-e5fe1da62059.png)

8.3.3:
![2021-12-21 22_00_41-Window](https://user-images.githubusercontent.com/36912975/146997303-bdca2a2d-b49a-4572-8031-0463da6f114f.png)

Query:
`sum without(cpu) (rate(node_cpu_seconds_total{instance="node-exporter:9100",mode="system"}[$__rate_interval])) > 0.05`

**Comment by michaelkebe** [comment]
@krzysion Thanks for posting this. I can confirm this behavior in Version 8.3.2. I don't think someone will reopen this. Maybe we should open a new issue linking to this one?

**Comment by michaelkebe** [comment]
According to my research the problem is not limited to queries with `topk` (as @krzysion also said). It even occurs on very simple metrics with gaps.

The bug was introduced with version 8.3.0, because in version 8.2.7 the Connect null values configuration behaves as expected.

**Comment by michaelkebe** [comment]
Even the old graph visualization has this problem.
