### ISSUE TITLE
Prometheus: Annotation queries are not interpolating variables

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#43438]
The changes in v8.3 to annotationQuery function:
https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/datasource.ts#L663 

Breaks all annotation queries that use variables. The previous version called createQuery:
https://github.com/grafana/grafana/blob/v8.2.7/public/app/plugins/datasource/prometheus/datasource.ts#L639 

Which reuses all the logic for normal metric query (which annotation query is), inside createQuery the expr is interpolated. 

Think there might be more bugs introduced by this change (all the logic inside createQuery to align time range & step  etc, seems to be missing in new version)

**Comment by toddtreece** [comment]
> all the logic inside createQuery to align time range & step etc, seems to be missing in new version

I am still digging into the prometheus code, but I did notice that this piece have been moved to the backend:

https://github.com/grafana/grafana/blob/ffc72aa25541a8f3a1930f59f7007a8e8301fd84/pkg/tsdb/prometheus/time_series_query.go#L73-L78

**Comment by machinly** [comment]
Only the `TimeRange` is moved to the backend, and there are other variables that need interpolating.

**Comment by ivanahuckova** [comment]
Hello @machinly! 👋 First of all thank you for your PR! 🙏 I reviewed it and it worked. But then I thought about using `applyTemplateVariable` method that we already have in Prometheus that is going to interpolate variables in a way that backend expects it and I created PR for it https://github.com/grafana/grafana/pull/43459. I hope you don't mind. I raelly, really appreciate your help! 🚀

**Comment by machinly** [comment]
I'm glad to know that this is just an unfinished function, not an unexpected  issue😃.
