### ISSUE TITLE
Rendering image for polyStat panel is not honoring relative time option in query options

### ISSUE THREAD

**Issue by sunnygadumadeinvizag** [grafana/grafana#43437]
**What happened**: 
It has been observed that when poly stat panel is created by adding Relative time option in query options section and when the poly stat panel is empty and when we click on on render image, the image is shown with poly stat data.

**What you expected to happen**:
When relative time value is used in query options and the empty panel is present grafana panel, both grafana panel and rendered image should be in sync

**How to reproduce it (as minimally and precisely as possible)**:
1) Create a polystat panel with any data source
2) Go to Query options and Relative time value as 30m.
![rm](https://user-images.githubusercontent.com/47292531/146971238-d4c758c9-b78e-4626-bcd1-46253ba1142d.JPG)

3) Make sure that when the data is not plotted in polystat panel with 30m relative time,
4) Save the panel and right click on panel title-> Share -> Click on Direct Link Rendered Image
![ri](https://user-images.githubusercontent.com/47292531/146971314-defe0fe2-d85f-498e-b598-07634453368e.JPG)

5) Observe that image gets plotted with polystats, ideally it image also should have empty data but here rendering image is not honoring relative time in query options.

- Grafana version: 7.5.2
- User OS & Browser: Chrome
- Grafana plugins: Polystat

**Comment by zuchka** [comment]
> Make sure that when the data is not plotted in polystat panel with 30m relative time,

My apologies @sunnygadumadeinvizag but can you try and clarify this? 

Were you able to reproduce this on play, which I believe is now running 8.3.3?

**Comment by zuchka** [comment]
Also, the polystat is maintained by Grafana, but it is not a core plugin. If this issue is specific to the polystat panel, then I think we should close this and you should make a new issue in that repo:
https://github.com/grafana/grafana-polystat-panel/issues
