### ISSUE TITLE
[PG 12+] Grafana 8.3.3 - Numeric, boolean, and text columns not displaying in dropdown

### ISSUE THREAD

**Issue by nick-bowman** [grafana/grafana#43444]
### Discussed in https://github.com/grafana/grafana/discussions/37009

<div type='discussions-op-text'>

<sup>Originally posted by **mindfuucker** March 22, 2019</sup>

What happened:
I just installed grafana to connect to my postgresql database.
Installed the 6.0.0 beta3 version because I hoped postgreSQL 11 would be supported.

Created my first dashboard, added a graph and tried to select a Numeric(5,3) column. Only integer columns were displayed in the dropdown.

Manual adding of the column name displays the graph without any problems. Problem is just the dropdown.

What you expected to happen:
A dropdown containing all columns (numeric and integers).

How to reproduce it (as minimally and precisely as possible):
Install grafana 6.0.0 beta3
install postgresql 11.2
create table with numeric values.
Add dashboard, graph and select column.

Anything else we need to know?:
Table is partitioned using native postgresql 11 partitioning.

Environment:

Grafana version: 6.0.0 beta3
Data source type & version: PostgreSQL 11.2
OS Grafana is installed on: Ubuntu 18.04
User OS & Browser: Firefox
Grafana plugins: none
Others: none

</div>

This is created out of the issue that was originally reported in the above linked discussion and continues to be unresolved to this point in time. 

**What happened**:
We host a Grafana instance that connects to a PostgreSQL database, and attempt to create panels and dashboards that display the information stored in the database.

When creating a panel connected to a a PostgreSQL data source and selecting a table that has numeric, boolean, or textual columns that represent valid data, the names of these columns do not show up in the selectable panel dropdown UI as valid values for the "Column" subfield of the SELECT clause. The column names that do show up in the dropdown  are for integer and real columns. 

Manually adding the columns names successfully retrieves the data from the database and displays it in the panel. The problem is just in displaying all the appropriate/available options in the dropdown menu. 

**What you expected to happen**:
The dropdown menu for Column selection in the SELECT clause of the panel query creation UI to display ALL possible columns from the table that could contain data of interest for creating graphs, tables, and other panels. This includes columns of numeric type, as well as booleans and text fields as well (the data we deal with has enumeration types, which are stored in their converted textual format).

**How to reproduce it (as minimally and precisely as possible)**:
Install grafana 8.3.3
install postgresql 13.5
create table with numeric, boolean, and textual values.
Add dashboard, graph and select column. 

**Anything else we need to know?**:
PostgreSQL data source is using TimescaleDB plugin 

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: PostgreSQL 13.5
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome
- Grafana plugins: pierosavi-image-it

**Comment by zoltanbedi** [comment]
No need to create a separate issue for this we can use the original discussion to track this. https://github.com/grafana/grafana/discussions/37009
