### ISSUE TITLE
[Grafana] 8.3.X Copy a Dashboard to another environment by copying it from Json Model

### ISSUE THREAD

**Issue by jgarciadelanoceda** [grafana/grafana#43440]
**What happened**:
Since Grafana 8.3.X is not possible to copy a dashboard to other environment, because in the dashboard the database does not appear as a String so you have to change all the panels to be able to copy a dashboard to another environment.
I think that is since  #33817 

**What you expected to happen**:

To be able to copy a dashboard to another environment

**How to reproduce it (as minimally and precisely as possible)**:
If you have 2 enviroments(With the same database name and different uid in the database object) where Grafana is installed, build a dashboard in one and try to copy it to another. You will  copy the dashboard but all the queries are not being copied since the 2 environments have a different Uid for the database, so you have to build the query again in the second enviroment which is annoying.

To copy it to another enviroment I used the Json Model of the dashboard and Import it in the new enviroment.
I think that if you do it with the dashboard table (The data column) you will get it right

**Anything else we need to know?**:

**Environment**:
- Grafana version:8.3.3
- Data source type & version:Influx
- OS Grafana is installed on:Windows
- User OS & Browser:Windows &Chrome
- Grafana plugins:
- Others:

**Comment by kristjansb** [comment]
I recently ran into this issue trying to upgrade from 7.5.x to 8.3.x and came up with a few work arounds. Depending how many dashboards you are trying to move between environments, one is more manual & time consuming but seems the more flexible (at the time on 8.3.1).

Pull up the dashboard share menu -> export and enable the "Export for sharing externally" toggle, then save to file. When you import the dashboard into the other instance, there will be a drop down menu for each data source used in the dashboard that you can match up by name, and it will fill out the necessary datasource UIDs in the imported JSON. This also seems to be the only way I was able to migrate library panels between environments.

<img width="465" alt="image" src="https://user-images.githubusercontent.com/7348565/146992466-791033b6-8370-4530-aabe-c00414bac527.png">


The second option may take a bit more trial and error, but helps with larger migrations. Basically, you can use datasource provisioning to get your UIDs to match across environments, then the reference object/UIDs should match without the "export for external sharing" toggle enabled. Major caveat being, if you are using unified alerts and having existing Grafana managed alert rules defined, changing the datasource UID through provisioning will end up dropping any queries using that datasource in alerting.

**Comment by jgarciadelanoceda** [comment]
Thank you @kristjansb 
The first way you can copy without losing information.

**Comment by zuchka** [comment]
closing this for now-- 👍
