### ISSUE TITLE
[Bug] viewer can manipulate panel

### ISSUE THREAD

**Issue by leslie-wang** [grafana/grafana#4345]
As a viewer, I should only be able to see dashboard panels. However, current UI allows them to 

- add row
- delete row
- add panel

Not sure if it is bug, but it causes some confusion.

Ex
* My grafana version: 2.6.0
* My datasource: InfluxDB 0.9.2
* My OS: ubuntu/trusty64

**Comment by torkelo** [comment]
this is already reported: https://github.com/grafana/grafana/issues/3827

Viewer role was mainly created to stop some users from creating or saving changes to dashboards. Doing changes like deleting a row or adding a panel that they cant save is not (usually) doing any harm. I can understand that having these actions there is a little inconsistent and confusing and a PR that fixes this would be welcome :) 

Please be aware of that Viewers that know any HTTP will always be able to query for any data exposed by a data source.
