### ISSUE TITLE
Question: Display selected fields from elasticsearch document based on user input in Grafana

### ISSUE THREAD

**Issue by asitk** [grafana/grafana#4346]
Is it possible to create an input box that takes user input and display matched results from selected fields from elastic-search on similar lines to kibana ? 

![kb](https://cloud.githubusercontent.com/assets/8538597/13721937/5304fcda-e85b-11e5-87cf-ceb8daa5fc78.png)

Thanks !

**Comment by torkelo** [comment]
You can create a custom template variable that you can use in your elasticsearch queries. 

But there are no field selector.

**Comment by asitk** [comment]
Thanks!
