### ISSUE TITLE
Alerting: correctly log datasource errors when they occur

### ISSUE THREAD

**Issue by davidmparrott** [grafana/grafana#43465]
**What happened**:
We are swallowing datasource errors instead of logging them as errors when they happen

**How to reproduce it (as minimally and precisely as possible)**:
You can change pkg/tsdb/prometheus/prometheus.go to return an error intermittently by adding a code snippet to the QueryData function just before the return.

```
	if time.Now().Minute()%2 == 0 {
		return result, fmt.Errorf("and error David made")
	}
```

When we evaluate conditions in the scheduler, we call ConditionEval to do so. This can return an error but only ever returns results, nil. We should check the results from executeCondition to see if there is an error present in the results, and return that error if so in order for it to be properly logged.

**Comment by davidmparrott** [comment]
Observations from early poking:
If you take the naive approach and just return nil, error when you have an error, or if you also evaluate the  results (evaluateExecutionResults) and then do the check returning the results, you drop out of the ruleRoutine before states have been processed, which means you don't have the rule health set correctly, and you don't get the alert instances processed, saved, etc.

**Comment by yuri-tceretian** [comment]
I think this is pretty important for better observability. It does not seem to be a very big change.

**Comment by grobinson-grafana** [comment]
@yuri-tceretian I think you have fixed this in one of your latest PRs?
