### ISSUE TITLE
[Bug] Can't query default retention policy unless it's also DEFAULT in InfluxDB

### ISSUE THREAD

**Issue by coudy** [grafana/grafana#4347]
I have two retention policies 'default' and 'expire' (which is actually `DEFAULT` as in https://docs.influxdata.com/influxdb/v0.10/query_language/database_management/#create-retention-policies-with-create-retention-policy) in InfluxDB 0.10 as follows:

```
name    duration    replicaN    default
default 0           1           false
expire  24h0m0s     1           true
```

Both policies are shown in the dropdown inside the query builder but the one marked 'default' constructs the erroneous query `FROM "measurement"` when the correct query is `FROM db_name."default"."measurement"`. There's no way to select from this retention policy unless I edit the query directly.

Using current master @ d575a5ce on OS X.

**Comment by shanielh** [comment]
@torkelo Willing to help, Where should I start?

**Comment by shanielh** [comment]
Hi @coudy , I've created a pull request with the fix you wanted, It uses the full name of the measurement for query. 

Please test it with your scenario and tell if it works :+1:

**Comment by coudy** [comment]
Works great! :+1:

**Comment by shanielh** [comment]
@coudy I've changed the code to @torkelo's request. Can you please test it again?

**Comment by coudy** [comment]
@shanielh Yep, still works as expected.

**Comment by bergquist** [comment]
This would cause all existing panels who use a none default retention policy to break. Since they would start using the default retention policy instead of the default in influxdb.

We should add the possibility to set a default retention policy that should be used by grafana on the datasource config page.

**Comment by coudy** [comment]
@bergquist Is breaking compatibility a big deal given that this is targeting a new major version? @shanielh's solution feels like the right thing to do and is also simpler.

**Comment by bergquist** [comment]
@coudy yes. We take backwards comparability very seriously. Updating a lot of dashboards is painful. 

I think its a good thing to let influxDB decided whats the default retention policy. But it should be possible to make it easier to deal with this within grafana.

**Comment by coudy** [comment]
@bergquist OK, sounds fair. 👍

**Comment by geoffgarside** [comment]
This just caught me out, any idea when this might be changed to allow specification of the "default" retention policy? Perhaps a solution might be to define `DEFAULT` and `default` as separate retention policies in the queries. This assumes existing queries could be updated from `default` to `DEFAULT` transparently without disruption. I'm fairly new to using Grafana though so theres likely some implications I'm not currently aware of w.r.t this.

**Comment by davkal** [comment]
This is too niche, so closing this. If anyone from the community wants to work on this, please reach out to @gabor
