### ISSUE TITLE
Azure monitor data source can not find metrics for firewall

### ISSUE THREAD

**Issue by xiaopeng163** [grafana/grafana#43482]
**What happened**:

![image](https://user-images.githubusercontent.com/5743757/147142731-55a09f57-2e61-4dda-9ea3-88e7b35943b2.png)

![image](https://user-images.githubusercontent.com/5743757/147142903-0e965d78-a982-43cb-ab35-906ef0a1bdac.png)

the metric can be found in azure, but not in Grafana from azure monitor data source

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.3
- Data source type & version:   azure monitor, latest
- OS Grafana is installed on:  
- User OS & Browser:  latest docker image grafana/grafana-oss
- Grafana plugins:  azure monitor, latest
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @xiaopeng163 

Is there some quick way that the team can try and reproduce this? was the `Firewall` resource type dynamically populated, or did you input that name manually?

**Comment by xiaopeng163** [comment]
@zuchka  all fields are populated, like `subscription`, `resource group`, `resource type`, `resource name`.

but no `metric` can be found.

**Comment by xiaopeng163** [comment]
@zuchka  we found the issue, thanks,  new identity fixed the issue.
