### ISSUE TITLE
Move y-axis labels inside graphs

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#4349]
Hello,

I would really be interested into moving y-axis labels inside the graph, simply moving them horizontally to the right of the axis.
This would give us vertically aligned graphs, with the the same vertical starting point.
For the moment, they are not aligned because their starting point depends on the labels' width (example below).
Of course the problem is the same for the right y-axis (move labels to the left of the axis).

This modification would also maximize width space for plotting (we would save labels width).

With some transparency, or just printing 3 labels (min, max, middle), this should be achievable.

Thank you very much :+1: 

Ben

![29c9d2c8-e32e-11e5-98fa-9ebdb7d6ff5c](https://cloud.githubusercontent.com/assets/6764151/13728672/7b84855c-e920-11e5-990d-cd4189564a0b.png)

**Comment by torkelo** [comment]
it will make the label Unlegible in many scenarios (many series, series fill are fill etc)

**Comment by benrubson** [comment]
And something from :

![7b84855c-e920-11e5-990d-cd4189564a0b-2](https://cloud.githubusercontent.com/assets/6764151/13729197/014e74e0-e930-11e5-945d-fd2ad0d4ab32.png)

To :

![7b84855c-e920-11e5-990d-cd4189564a0b](https://cloud.githubusercontent.com/assets/6764151/13729236/8e979cb4-e930-11e5-9cb3-ed3b953663c6.png)

Of course this would be possible through an option, so that users can keep the current display or go with this new one.

This new view gives the min and max of the axis, which is enough in many cases (we then have the details with the tooltip), and which improves plotting space, alignements...

Many thx !

**Comment by benrubson** [comment]
@torkelo, and something from :

![7b84855c-e920-11e5-990d-cd4189564a0b-2](https://cloud.githubusercontent.com/assets/6764151/13729197/014e74e0-e930-11e5-945d-fd2ad0d4ab32.png)

To :

![7b84855c-e920-11e5-990d-cd4189564a0b](https://cloud.githubusercontent.com/assets/6764151/13729236/8e979cb4-e930-11e5-9cb3-ed3b953663c6.png)

?

Of course this would be possible through an option, so that users can keep the current display or go with this new one.

This new view gives the min and max of the axis, which is enough in many cases (we then have the details with the tooltip), and which improves plotting space, alignements...

Many thx !
