### ISSUE TITLE
Cannot select data-link variables from drop-down, such as "built-in: time-range"

### ISSUE THREAD

**Issue by samjewell** [grafana/grafana#43501]
We've found a bug with the selection of variables when editing data links. During data-link edit modal, when I type `$` a dropdown appears listing the available data-link variables. This dropdown is scrollable as the list is too long to show initially. As soon as I have scrolled the list, for example to pick any of the items at the bottom of the list, I'm then unable to actually pick any option: Instead at that point the mouse click returns me to the top of the scroll position within that dropdown.
This effectively makes it impossible for me to pick any of the 4 bottom options, such as `Built-in Time Range` which was the one I wanted in this case.

Video recording of the issue has been shared on GrafanaLabs internal Slack, here: https://raintank-corp.slack.com/archives/C036J5B39/p1640256294074400

**Environment**:
- Grafana version: v8.4.0-46267pre (b87c737a1)
- Data source type & version: Loki Datasource, Table Viz
- OS Grafana is installed on: GrafanaCloud
- User OS & Browser:
   - Chrome 96.0.4664.93 (Official Build) (arm64). MacOS BigSur 11.5.2.
   - Rutger saw the same issue on Linux 
- Grafana plugins: None
- Others:

**Comment by axelavargas** [comment]
Hey, @samjewell thank you for reporting this issue 😄 , I am able to reproduce the issue,  and I am moving it into being prioritized by the team to fix it.

ps, In the meantime, I have found a workaround using the arrow keys in the keyboard (up, down to navigate the select, and enter to select).

**Comment by samjewell** [comment]
@RutgerKe this got fixed 👏 🎉

**Comment by samjewell** [comment]
@JoaoSilvaGrafana and team, I know it's been ages, but just wanted to say thanks for fixing this ❤️
