### ISSUE TITLE
Unable to Select Resource from large resource group for Azure Log DataSource

### ISSUE THREAD

**Issue by ehuggz** [grafana/grafana#43503]
**What happened**:
Try to select an Azure Application Insights or Azure Log Analytics resource from Resource Group picker in the Logs option for Azure Data Source. After expanding a larger resource group and scrolling beyond the initially visible resources, all attempts to click a resource end by auto-scrolling back to resource group folder without selecting a resource group.

**What you expected to happen**:
1. Create new panel
2.  Select Azure DataSource
3.  Select Logs
4.  Open Resource Picker
5.  Navigate to Resource Group
6.  Scroll down to resource and click to select resource.

**How to reproduce it (as minimally and precisely as possible)**:
The specific issue is a little hard to show in a screenshot - but is quite repeatable.

1. Create a new Dashboard Panel, select Azure Data Source and set service to Logs (Screenshot 1)
![1-AzureResourcePickerBug](https://user-images.githubusercontent.com/544939/147252778-ea155deb-a015-452b-9f7a-99d9c0e1622b.jpg)

2. Click Open Resource and navigate to Subscription and Resource Group containing Kusto Query Data Sources (Screenshot 2)
![2-AzureResourcePickerBug](https://user-images.githubusercontent.com/544939/147252809-c6e86c21-3f03-40e4-b90e-2f25eb6432b3.jpg)

Note: Resource Group must contain more Resources than will fit on the screen. Replicating the issue will require a resource group containing 10 or more resources, with the resource to be selected toward the end of the list of resources within the Resource Group.

3. Scroll past existing resources and try selecting a resource - click will be taken back to the resource group with nothing selected.

**Observed Errors**
There are browser console errors when expanding the Resource Group.
In particular: handleError:: ResizeObserver loop limit exceeded
![handleErrorRsizeObserverlooplimitexceeded](https://user-images.githubusercontent.com/544939/147252886-353c35d6-5a25-41b9-906d-80b0d66fc888.jpg)
![ConsoleErrors](https://user-images.githubusercontent.com/544939/147252899-609906db-cc6a-4d5f-a06a-4681e2da6bd5.jpg)

While I've discovered a workaround, it is very time-consuming and tedious. Let me know if you have trouble replicating the issue and need more information as I will be glad to help.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3
- Data source type & version: Azure Data Source - logs for Kusto Queries
- OS Grafana is installed on: Grafana Pro (Online)
- User OS & Browser: Windows 11 Edge

**Comment by andresmgot** [comment]
Quoting myself from the other issue:

> Thanks for the details @ehuggz, I can reproduce the issue. Interestingly, only happens sometimes for me so if I scroll around, sometimes it allows me to click in the element and sometimes don't. If a resource is already selected and all the other items are disabled I am also able to reproduce the issue (clicking an element, causes the scroll bar to change).
