### ISSUE TITLE
[Question] Data source configuration

### ISSUE THREAD

**Issue by carioka88** [grafana/grafana#4350]
Hello,
I am using Grafana v2.6.0 and I am doing all the configuration/setup.
From the browser, I can access to the datasources configuration and add a new one, and it is working from there! (I am using elasticsearch)
What I would like to know is if there is any way of adding in a config file the data source (with the http settins and elastic search details).
Something like this:
```
datasources: {
  elasticsearch: {
    type: 'elasticsearch',
    url: "http://my.elastic.server.com:9200",
    index: 'grafana-dash',
    grafanaDB: true,
  }
},
```
Is it possible? 
I would like to do it from puppet in the future as well.

Thanks in advance!

**Comment by torkelo** [comment]
you have to use the http api, most config management recipies (chef, puppet, ansible, etc) have been able to use the http api to setup data sources from config
