### ISSUE TITLE
Azure Monitor: Missing resources for huge resource groups

### ISSUE THREAD

**Issue by huberttrz** [grafana/grafana#43514]
**What happened**:
When working with the Azure Monitor data source and selecting a resource group with more than 1000 resources in the query editor, you won't have all the resources available for selection. The reason appears to be a request behind the scenes made to `/api/datasources/2/resources/azuremonitor/subscriptions/#SUBSCRIPTION_ID#/resourceGroups/#RESOURCE_GROUP_NAME#/resources?api-version=2018-01-01` which returns a JSON with a values array of 1000 elements only and a nextLink which apparently isn't followed by Grafana. Even if I select a specific resource type in my query, Grafana still makes a request for all the resources in the resource group instead of using a resourceType filter.

**What you expected to happen**:
Whenever I'm working with resource groups with over 1000 elements I should be able to select any element which is present in that resource group. Grafana should either:
- follow the `nextLink` value and fetch another batch of resources
- use a resourcetype filter when requesting resources 

**How to reproduce it (as minimally and precisely as possible)**:
1. You will need a resource group with over 1000 resources.
2. Go into query editor and select your subscription, resource group with over 1000 elements and one of the resource types.
3. Look at the network tab of your browser, Grafana will make a request without filtering for the specific resource type. You will get only 1000 resources in the response and only those resource will be available for selection.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.3.3
- Data source type & version: Azure Monitor data source - native plugin | Grafana Labs | 0.3.0 | Core
- OS Grafana is installed on: Docker - grafana/grafana:8.3.3
- User OS & Browser: Manjaro Linux - Firefox 95.0
- Grafana plugins: No extra than what is shipped with grafana
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @huberttrz 

I know, generally speaking, that one of the dangers with fetching paginated JSON data is that you risk throttling the DS with a bunch of requests and then getting rate-limited.

That said, looks like the Cloudwatch plugin has a config setting that users can change to increase the number of paginated results to return:

> ...The API is paginated and returns up to 500 results per page. The CloudWatch data source also limits the number of pages to 500. However, you can change this limit using the `list_metrics_page_limit` variable in the [grafana configuration file](https://grafana.com/docs/grafana/latest/administration/configuration/#aws).

So is this a `bug`, a `works-as-intended`, or a `feature-request`? Not sure. The Azure squad will have more input here.

**Comment by huberttrz** [comment]
Thanks for picking this up.
Actually whenever I select (for example) a `SQL elastic pool` as Resource type:
![image](https://user-images.githubusercontent.com/5301199/147299073-3f6c95d5-2120-42f5-aa74-0b9fb2e0819d.png)
I would expect Grafana to make a call to azure api with this resource type as a filter/param thus limiting the number of resources returned. Currently, no matter what resource type I select, Grafana still tries to fetch all resources within the resource group, which is kind of waste of resources.

**Comment by andresmgot** [comment]
Thanks for the pointer @huberttrz, it really helps! I have opened a PR to filter resources when doing this list: https://github.com/grafana/grafana/pull/43522
