### ISSUE TITLE
TimeSeries: Tooltip sort order missing

### ISSUE THREAD

**Issue by kustodian** [grafana/grafana#43524]
**What happened**:
TimeSeries doesn't have an option for sorting the tooltip values as the old Graph panel does.

**What you expected to happen**:
I expected to have what the Graph panel had:
![image](https://user-images.githubusercontent.com/1949229/147360130-daeb9473-d257-4a30-bc8f-16b39eae9b80.png)

**Comment by zuchka** [comment]
There is already a discussion for this: #38861. It would be awesome if you upvoted it. Closing this duplicate issue. 👍
