### ISSUE TITLE
[ES] [data-links in ConfigEditor] adding multiple data links on same field in datasource settings doesn't work

### ISSUE THREAD

**Issue by okhowang** [grafana/grafana#43521]
**What happened**:
![image](https://user-images.githubusercontent.com/3352585/147345221-89a3be1e-8df0-43ab-a5cd-6e794da061f1.png)
![image](https://user-images.githubusercontent.com/3352585/147345250-7b2ea10c-d53d-4c08-bbf6-5ee20bdc2de3.png)
adding multiple data links on same field in datasource settings don't work
**What you expected to happen**:
there are multiple button after field which bind multple data links
**How to reproduce it (as minimally and precisely as possible)**:
add multiple data links on same field
**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.0
- Data source type & version: elasticsearch
- OS Grafana is installed on: linux
- User OS & Browser: windows chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
@okhowang please provide more exact details for reproduction. This does not look like the typical data links modal in the panel editor

**Comment by okhowang** [comment]
what details do you need?
there are just 2 steps for reproduction.
1. add two datalinks for same fields on data source settings.
2. explore the data source and expect there are two button after the field, but there is only first one

**Comment by zuchka** [comment]
> on data source settings.

thanks. That's what I needed. Not every DS has a data link component inside its ConfigEditor 👍
