### ISSUE TITLE
Move y-axis labels inside graphs

### ISSUE THREAD

**Issue by benrubson** [grafana/grafana#4352]
Hello,

This issue follows #4349 with a new idea.

I would really be interested into moving y-axis labels inside the graph, simply moving them horizontally to the right of the axis.
This would give us vertically aligned graphs, with the the same vertical starting point.
For the moment, they are not aligned because their starting point depends on the labels' width (example below).
Of course the problem is the same for the right y-axis (move labels to the left of the axis).

This modification would also maximize width space for plotting (we would save labels width).

What about the following modification ?

From :
![014e74e0-e930-11e5-945d-fd2ad0d4ab32](https://cloud.githubusercontent.com/assets/6764151/13737295/4c978c02-e9bc-11e5-8138-fd580dc9ed45.png)
To :
![8e979cb4-e930-11e5-9cb3-ed3b953663c6](https://cloud.githubusercontent.com/assets/6764151/13737300/57f06236-e9bc-11e5-9245-fdf8762025b4.png)

Of course this would be possible through an option / a checkbox, so that users can keep the current display or go with this new one.

This new view gives the min and max of the axis, which is enough in many cases (we then have the details with the tooltip), and which improves plotting space, alignements...

Thank you very much for considering this as a possible feature :+1: 

Ben

**Comment by torkelo** [comment]
having y-axis labels on the top x-axis ?

I think a better solution is to have an option to set a fixed width for the y-axis labels, that way all graphs will align

**Comment by benrubson** [comment]
One value on the top left of the graph to specify the maximum value.
One value on the bottom left of the graph to specify the minimum value.
