### ISSUE TITLE
After upgrading from 7.1 to 8.3.3, the values of variables are not displayed

### ISSUE THREAD

**Issue by guidao** [grafana/grafana#43535]
**What happened**:
After upgrading from 7.1 to 8.3.3, the values of variables are not displayed
<img width="1007" alt="企业微信截图_3b060a34-9fcd-44cb-b270-fd6a66033356" src="https://user-images.githubusercontent.com/3192136/147460726-652d4020-e570-4bdd-b97c-b42923e89cc6.png">

**What you expected to happen**:
<img width="1242" alt="企业微信截图_1820c49f-49d6-4d29-a57d-0296acef6b04" src="https://user-images.githubusercontent.com/3192136/147460826-52129baa-847d-4a67-b03c-392d7d604eb9.png">

**How to reproduce it (as minimally and precisely as possible)**:
Import old dashboard in grafana 8.3.3. For example: https://grafana.com/api/dashboards/10229/revisions/14/download

**Anything else we need to know?**:
I checked the json file and found the following difference,but I didn't find if there is a tool to do this migration
![image](https://user-images.githubusercontent.com/3192136/147461282-4582b1da-b43f-4bfc-b306-93861dd94b2a.png)

**Environment**:
- Grafana version: 7.1.3
- Data source type & version: prometheus && json

**Comment by zuchka** [comment]
Thanks for creating this issue, @guidao 

A couple of initial things:
- I see VictoriaMetrics mentioned in the screenshot. Are you using their hosted grafana service? or migrating away from it / something else? It also looks like you are importing the VictoriaMetrics dashboard, which has [some detailed notes about version incompatibilities](https://grafana.com/grafana/dashboards/10229).
- Even though Grafana's templating engine has undergone substantial improvements between 7.1.3 and 8.3.3, it looks like your cited dashboard on Grafana.com loaded correctly: 
![CleanShot 2021-12-27 at 13 43 51@2x](https://user-images.githubusercontent.com/37156449/147514117-ff21f0b4-3495-4b88-9ae0-de7ecc56a1d2.png)

- In your screenshot you list a `workload` variable, which was not included in the downloaded dashboard. I would try asking the [Grafana forum](https://community.grafana.com/) or the [Victoria Metrics forum](https://victoriametrics.com/community.html) for help here 👍

**Comment by guidao** [comment]
I'm sorry. I verified that the prometheus source is caused by the fact that there is no corresponding source in the new version (grafana 8.3.3). But the JSON source still has the problem. Can you help to verify?
```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "gnetId": null,
  "graphTooltip": 0,
  "id": 5178,
  "iteration": 1640660033631,
  "links": [],
  "panels": [
    {
      "aliasColors": {},
      "bars": false,
      "dashLength": 10,
      "dashes": false,
      "datasource": null,
      "fieldConfig": {
        "defaults": {
          "custom": {}
        },
        "overrides": []
      },
      "fill": 1,
      "fillGradient": 0,
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "hiddenSeries": false,
      "id": 2,
      "legend": {
        "avg": false,
        "current": false,
        "max": false,
        "min": false,
        "show": true,
        "total": false,
        "values": false
      },
      "lines": true,
      "linewidth": 1,
      "nullPointMode": "null",
      "percentage": false,
      "pluginVersion": "7.1.3",
      "pointradius": 2,
      "points": false,
      "renderer": "flot",
      "seriesOverrides": [],
      "spaceLength": 10,
      "stack": false,
      "steppedLine": false,
      "targets": [
        {
          "refId": "A",
          "target": ""
        }
      ],
      "thresholds": [],
      "timeFrom": null,
      "timeRegions": [],
      "timeShift": null,
      "title": "",
      "tooltip": {
        "shared": true,
        "sort": 0,
        "value_type": "individual"
      },
      "type": "graph",
      "xaxis": {
        "buckets": null,
        "mode": "time",
        "name": null,
        "show": true,
        "values": []
      },
      "yaxes": [
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        },
        {
          "format": "short",
          "label": null,
          "logBase": 1,
          "max": null,
          "min": null,
          "show": true
        }
      ],
      "yaxis": {
        "align": false,
        "alignLevel": null
      }
    }
  ],
  "schemaVersion": 26,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "allValue": null,
        "current": {
          "selected": false,
          "text": "*",
          "value": "*"
        },
        "datasource": "API",
        "definition": "/moc/app",
        "hide": 0,
        "includeAll": false,
        "label": null,
        "multi": false,
        "name": "apps",
        "options": [],
        "query": "/moc/app",
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "tagValuesQuery": "",
        "tags": [],
        "tagsQuery": "",
        "type": "query",
        "useTags": false
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ]
  },
  "timezone": "",
  "title": "New dashboard Copy",
  "uid": "Gtt64mA7z",
  "version": 2
}
```

**Comment by guidao** [comment]
I found the reason, because simple-json-datasource is no longer maintained, using grafana-simple-json-datasource instead, and everything works fine.

**Comment by zuchka** [comment]
@guidao I would also investigate this similar plugin:

https://github.com/marcusolsson/grafana-json-datasource

It's my personal preference when handling JSON APIs

**Comment by guidao** [comment]
Thanks, I will try it.
