### ISSUE TITLE
groupBy transformer changed the order of numeric keys

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#43545]
**What happened**:

https://github.com/grafana/grafana/blob/c3eb1ffe850be4f3ee4093987160fbb29e196e2f/packages/grafana-data/src/transformations/transformers/groupBy.ts#L66

In groupBy transform, the values with same key will be clac.
But when the key was numeric string, Object.keys will change the order of numeric keys.

Can see [the-order-of-js-object-keys](https://dev.to/frehner/the-order-of-js-object-keys-458d)

**What you expected to happen**:

Consider use Map to store key-value paris to keep order of values.

**How to reproduce it (as minimally and precisely as possible)**:

![image](https://user-images.githubusercontent.com/12808432/147525489-5e01d880-cff9-41d8-817b-967b7fea5f4c.png)

data 
```csv
key,value
500,1000
404,2000
200,5000
204,10000
```

![image](https://user-images.githubusercontent.com/12808432/147525528-f70bbf0d-d9a5-47f6-8ff8-3817c3bdb061.png)

transform config
```json
  "transformations": [
    {
      "id": "groupBy",
      "options": {
        "fields": {
          "key": {
            "aggregations": [],
            "operation": "groupby"
          },
          "value": {
            "aggregations": [
              "first"
            ],
            "operation": "aggregate"
          }
        }
      }
    }
  ],
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest 8.3
- Data source type & version: any
- OS Grafana is installed on: play.grafana.org
- User OS & Browser: macos chrome

**Comment by zuchka** [comment]
Thanks for creating this issue and for including the reproduction steps, @MeetzhDing 

Here is your reproduction saved to play, for further investigation:

https://play.grafana.org/d/3QEOC40nz/grafana-grafana-43535?orgId=1
