### ISSUE TITLE
Datasource: Live Websocket based data source

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#4355]
**UPDATE**: Published [design document](https://docs.google.com/document/d/15VgeOQSVJ8aBkVPlv6KodtwiPboW_XrbA-lKOft5Uk8/edit?usp=sharing) and requesting comments.

--

allow for live data to be pushed to graphs and panels via Grafana HTTP api. 

for example: 

```http
POST /api/streams/:<stream_name>/
{
"type": "time-series",
"delta": true,
"metric": "name",
"tags": {
"host": "server-1",
"data-center": "us-east-02",
},
"datapoints": [
]
}
```

**Comment by digrich** [comment]
@torkelo Do we have an documentation on this? What should be the data source API to support websocket streaming on grafana? In one of your video, you were mentioning that Intel's snap integration supports real time push of data, does that uses websocket?

**Comment by torkelo** [comment]
no, that one uses streaming features in snap http api.  But the snap data source is using a feature in Grafana that allows data sources to push data to panels (instead of panels only doing pull)

**Comment by mtanda** [comment]
I create a datasource plugin by using Grafana Live. (I'm not sure this is good example.)
https://github.com/mtanda/grafana-prometheus-pull-datasource

To create datasource plugin, you should learn about RxJS.
https://github.com/Reactive-Extensions/RxJS

**Comment by digrich** [comment]
Thanks. I will take a look.

**Comment by fti7** [comment]
@torkelo Do we have a new planned Milestone Version for this important Feature request? :-)

**Comment by torkelo** [comment]
no not yet

**Comment by davkal** [comment]
We're currently spec'ing this out. Here is a [design document](https://docs.google.com/document/d/15VgeOQSVJ8aBkVPlv6KodtwiPboW_XrbA-lKOft5Uk8/edit?usp=sharing). I request you all comment there.

**Comment by lssilva** [comment]
This would be a great feature to have.

**Comment by lssilva** [comment]
Has there been progress in this direction?

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by Scavallarin** [comment]
Hi! There has been any news into this? From what i saw there is only this so far:
https://github.com/mtanda/grafana-prometheus-pull-datasource
It would be such an amazing component really useful!
Thanks

**Comment by ryantxu** [comment]
This is now part of grafana-live:  https://grafana.com/docs/grafana/latest/live/
