### ISSUE TITLE
[Feature Request] Abbreviate long metric names in overlay legend so color coding and metric value can be seen

### ISSUE THREAD

**Issue by sslavic** [grafana/grafana#4356]
* What grafana version are you using?
Grafana version: 2.6.0 
* What datasource are you using?
Graphite

When hovering over graph, Grafana displays overlaying legend of metrics shown on graph. Metric names can be quite long. Typically metrics shown on same graph have a large portion of metric prefix common and it doesn't really add value to display the common prefix, especially not complete. Overlay legend has limited display area. When metric is so long, one can in overlay legend see common metric prefix but cannot see important bit, which specific metric is coded with which color and what was its recorded value.

Imagine having 10-20 nodes, measuring same metric on all of them, metric has long name, typical value is 0, but sometimes some have value higher than 0; with metrics from all nodes visualized in same graph, and legend under graph disabled - overlay legend shows all 10-20 time series, but one or few which have value different than 0 is hard and almost impossible to distinguish.

One idea how to improve this is maybe to display abbreviated metric name in overlay legend if name and value cannot fit available space - e.g. show

```
the...0.someCounter: 2
the...1.someCounter: 3
```

instead of:

```
the.quick.brown.fox.jumps.over.the.lazy.dog.0.someCounter: 2
the.quick.brown.fox.jumps.over.the.lazy.dog.1.someCounter: 3
```

**Comment by torkelo** [comment]
there are a multitude of graphite functions that allow you get get short readable series names

* alias
* aliasByNode
* groupByNode
* aliasSub
* etc

**Comment by sslavic** [comment]
Thanks for prompt response! aliasSub worked for me. Downside - it's not DRY, I had to repeat basically same aliasSub for multiple graphs on same dashboard. I wish this was automatic and one can turn it off/on on dashboard level.

**Comment by sslavic** [comment]
Was asked via email to provide example what worked for me, here's one:

`aliasSub(the.quick.brown.fox.jumps.over.the.lazy.dog.*.someCounter, "^.*\.dog\.(\d+)", "dog.\1")`

This would render:
```
dog.0.someCounter
dog.1.someCounter
...
```
