### ISSUE TITLE
Setting timing settings to 0 seconds repeat interval breaks Notification Policies view

### ISSUE THREAD

**Issue by m1keil** [grafana/grafana#43571]
**What happened**:
In my notification policies, I tried to disable repeat alerts by setting the timing of the repeat interval to 0 seconds.
I got an error after which I can no longer access the view:

<img width="1266" alt="CleanShot 2021-12-29 at 19 07 15@2x" src="https://user-images.githubusercontent.com/1589008/147640634-f74891b0-2d4c-4ade-b83f-d63ff4ab6173.png">

<img width="1270" alt="CleanShot 2021-12-29 at 19 07 34@2x" src="https://user-images.githubusercontent.com/1589008/147640661-4a1bcf2b-7262-4c24-8433-061c77fc04b3.png">

<img width="1285" alt="CleanShot 2021-12-29 at 19 07 48@2x" src="https://user-images.githubusercontent.com/1589008/147640673-ceee8c2c-22fc-46f8-a7cd-e0a5784499a2.png">

Log:

```
t=2021-12-29T08:09:31+0000 lvl=eror msg="failed to apply Alertmanager config for org" logger=ngalert.multiorg.alertmanager org=1 id=101 err="failed to parse Alertmanager config: unable to parse Alertmanager configuration: unmarshaling route for validations: repeat_interval cannot be zero"
```

**What you expected to happen**:
Repeated alerts to be disabled.

**Environment**:
- Grafana version: 8.3.3
- User OS & Browser: Chrome 96
- Grafana plugins: Default

**Comment by m1keil** [comment]
FYI if anyone hits this: 
to undo you will need to open the DB and go to `alert_configuration` table and remove the latest config version.

**Comment by zuchka** [comment]
Thanks for creating this issue, @m1keil 

I'd like to try and reproduce this but I'm having trouble. Are you able to reliably trigger this error?

**Comment by m1keil** [comment]
Yes. Here's a screenshot of the config:

<img width="1021" alt="CleanShot 2022-02-05 at 15 06 07@2x" src="https://user-images.githubusercontent.com/1589008/152628080-bd5d1d71-847c-4ed2-849a-bddea22f4c9d.png">


After clicking save, the issue returns

**Comment by penekk** [comment]
Hello,

I can confirm I'm having issues with this too, althought I'm simply unable to save the policy with repeat interval set to 0. When trying to save the policy I'm getting:
```Error: bad request data```. Is there any other way to disable the repeat alltogether?

Grafana v8.4.1 (53f5c6a44c)

**Comment by linjmeyer** [comment]
Same issue here, would like to disable repeat for alerts that are sending emails or webhooks but receive bad request when setting the value to 0.

**Comment by grobinson-grafana** [comment]
Hi! I don't think it is possible to disable the `repeat_interval` in either Grafana or Alertmanager. Grafana 8.5.6 has a fix for this issue where a `repeat_interval` of 0 cannot be set either via the Timing options in Notification policies or in the configuration in Admin.

@m1keil, were you able to fix your Alertmanager configuration?

**Comment by m1keil** [comment]
> @m1keil, were you able to fix your Alertmanager configuration?

Yes, I had to manually revert the change in the database.

**Note for everyone: This was an issue about the configuration "breaking" Grafana. This is NOT about the inability to disable repeat interval.**
