### ISSUE TITLE
[grafana dashboard] "Templating [Variable_Name]" Error happened with message 'Updating options: no elements in sequence'  when switch dashboards quickly

### ISSUE THREAD

**Issue by sulin-cogiot** [grafana/grafana#43585]
**What happened**:
Error "Teplating [Variable_Name] Error Updating options: no elements in sequence" happened
**What you expected to happen**:
No error happens
**How to reproduce it (as minimally and precisely as possible)**:
1. Login  Grafana
2. Star a dashboard which has 6 variables, and these variables are queried from Promethus
3. Set this dashboard as user default dashboard
4. Open this dashboard, and the dashbord in in loading status 
5. Click on Dashboard button, and then click on Home button or management button, and you can see below error (if you do not see this error, repeat step 4,5 quickly in. one second). This issue exists in 7.9.5, 8.0.6, as well as 8.3.3

<img width="794" alt="image" src="https://user-images.githubusercontent.com/78069091/147732448-a17299cb-7162-42fe-a3e1-1ec6157247b7.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.9, 8.0.6, as well as 8.3.3
- Data source type & version: Promethus, 2.14
- OS Grafana is installed on: K8S
- User OS & Browser:
- Grafana plugins: Do not installed additional plugin
- Others:
[grafana-yaml.txt](https://github.com/grafana/grafana/files/7791998/grafana-yaml.txt)

**Comment by zuchka** [comment]
Thanks for creating this issue, @sulin-cogiot 

May we please ask for a few additional bits of info?
1. It looks like you are provisioning Prometheus to K8s. Are you provisioning the dashboard in question as well?
2. Can you share the dashboard json that causes the bug?
3. When you trigger the bug, do you see anything of interest in your browser's dev-tools console, or the network tab?
4. Similarly, do any errors get logged in the Grafana Server log when this bug occurs?

Thanks for reporting this and for your help 👍

**Comment by sulin-cogiot** [comment]
Hi @zuchka 

Thanks for your quick response. Below are the answers:
1.  In my k8s env, I have promethus and grafana provisioned. I imported my own dashboards. And the dashboards has lots of variables.
2:  
[my-json-111.zip](https://github.com/grafana/grafana/files/7795286/my-json-111.zip)

3:
<img width="1495" alt="Screen Shot 2021-12-31 at 11 50 57 AM" src="https://user-images.githubusercontent.com/78069091/147802304-f8087aa0-07b2-4725-a4a5-4b0e239c0bae.png">
<img width="1501" alt="Screen Shot 2021-12-31 at 11 53 05 AM" src="https://user-images.githubusercontent.com/78069091/147802333-89b739ef-9c5a-48e2-81a5-a9c9978765a7.png">
4. 
[a.log](https://github.com/grafana/grafana/files/7795285/a.log)

**Comment by justinTM** [comment]
we updated Datasource through API and getting same/similar error when trying to load dashboards using the (preexisting) Dashboard. This was after re-deploying dashboards with Terraform.

`Error updating options: no elements in sequence`
`Templating init failed Couldn't find variable with id:cluster`

**Comment by sulin-cogiot** [comment]
Hi @zuchka

Several users have the same issue, would you pls take a look at this issue?

Thanks.

**Comment by justinTM** [comment]
@sulin-cogiot looks like @joshhunt might be able to comment?

**Comment by joshhunt** [comment]
Hi. We are investigating. When we have news to share, we will share :) 

In the meantime, you could avoid switching navigating away from a Dashboard while the template variables are loading ("Services..." loading message), or just dismiss the error messages.

If the error message appears without navigating away, please file a separate issue.

**Comment by sulin-cogiot** [comment]
Thanks @joshhunt 

This error message will go away in 10 seconds.
Pls help resolve this issue, thanks.
