### ISSUE TITLE
typo in grafana log level messages : lvl=eror instead of error

### ISSUE THREAD

**Issue by squalou** [grafana/grafana#43589]
**What happened**:

I was reading grafana logs, and stumbled upon these messages :

```
t=2021-12-30T09:33:04+0000 lvl=eror msg="Alert Rule Result Error" logger=alerting.evalContext ruleId=25 name=" ......
```
As you can see, `lvl=eror` is displayed instead of 'error'

**What you expected to happen**:

 `lvl=error` 

**How to reproduce it (as minimally and precisely as possible)**:

start grafana, probably adding a faulty configuration to force an error message to be displayed

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: mysql 8
- OS Grafana is installed on: linux
- User OS & Browser: linux / firefox
- Grafana plugins: none (docker image as is)
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @squalou 

This is intentional. See this duplicate issue for more info. Tl;dr is that `EROR` keeps all the log levels to four letters, which allows for better consistency and alignment.

https://github.com/grafana/grafana/issues/25052

**Comment by squalou** [comment]
that's fun :-D

thank you for the explanation.

Can't wait to see reducted-translation of other 'standard' levels such as 'debug', 'trace' or whatever.

(my 2 cents : adding space to 'info' would have done the job and stick to the standard ;-) )
