### ISSUE TITLE
[Feature Request] Allow plugins to "migrate" the database

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4358]
The piechart plugin recently changed its id to piechart-panel, but no dashboard was updated, and now there are missing panels.
Ideally they should be able to update all dashboards in order to prevent breakage whenever these changes happen.

**Comment by torkelo** [comment]
yes, sorry about that, piechart panel is a new plugin that is still under development, and we are working heavily on trying to improve the state of plugin support (and figuring out naming conventions). 

We will not change panel id like this after release
