### ISSUE TITLE
[Bug]  Table panel time range exceed dashboard time range

### ISSUE THREAD

**Issue by teo96** [grafana/grafana#4359]
I want to calculate average metrics in a table with a 'Time Series Aggregation' transformation.
To check my results, I compare what I got in grafana with direct queries to graphite.

Results are differents because time range used in the table panel is not the same as dashboard time range.
Looks like there is -1 minute at start and +1 minute at end if dashboard time range does not end with :00

You can test it on the play website : 
http://play.grafana.org/dashboard/db/new-features-in-v2-6?from=1457960400000&to=1457961000000&panelId=2&fullscreen
Dashboard time range : from 14:00:00 to14:10:00 => table is OK

http://play.grafana.org/dashboard/db/new-features-in-v2-6?from=1457965328436&to=1457967128437&panelId=2&fullscreen
Dashboard time range : from 14:00:05 to 14:10:05 => table time range : from  13:59:10 to 14:11:00

**Comment by torkelo** [comment]
this is due to how graphite handles time ranges, 

"from" value is exclusive, so in order to get data points for the whole time range Grafana subtracts one minute (if time range is low enough)

Same is true for "to" range
