### ISSUE TITLE
Can't update a Telegram notifier ("Could not find Bot Token in settings")

### ISSUE THREAD

**Issue by valentinmatter** [grafana/grafana#43591]
**What happened**:

I get an error saying "Could not find Bot Token in settings" when I try to update a Telegram notification channel (to add/remove reminders for instance). It's possible to update the channel by clicking on "Clear" and re-entering the bot token but it's far from ideal (and it fails again the next time).

https://user-images.githubusercontent.com/1763772/147744018-2243bf07-9c33-41e0-90f2-3d31ad3aaaa5.mov

**What you expected to happen**:

The notification channel should be updatable without re-entering the bot token every time.

**How to reproduce it (as minimally and precisely as possible)**:

Try to update a Telegram notification channel

**Anything else we need to know?**:

From a very quick look, I believe the error comes from [here](https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/telegram.go#L76). I assume that [the decryption of the secret](https://github.com/grafana/grafana/blob/main/pkg/services/alerting/notifiers/telegram.go#L71) fails and it falls back to `model.Settings.Get("bottoken").MustString()` which is an empty string, but I haven't had time to look deeper into how the decryption works.

**Environment**:
- Grafana version: Seen both on v8.3.3 (30bb7a93ca) and v8.4.0-pre (unknown-dev)
- Data source type & version: -
- OS Grafana is installed on: v8.3.3 is on AWS Linux, v8.4.0-pre is on Mac OS (installed with brew)
- User OS & Browser: MacOS
- Grafana plugins: -
- Others: -

**Comment by dataselfservice** [comment]
Same issue here. One additional note: `Test` notifications are sent successfully after updating the BOT token **and** before saving. After pushing the `Save` button notifications get broken.

**Comment by zuchka** [comment]
Thanks for creating this issue, @valentinmatter 

I was able to reproduce this. Steps:

1. run `docker run -p 3000:3000 -e GF_UNIFIED_ALERTING_ENABLED=FALSE -e GF_ALERTING_ENABLED=TRUE grafana/grafana:8.3.4`
2. log into grafana and create a telegram notification channel
3. add dummy info and token and save
4. click on the newly saved channel and then modify something (check a box under `Notification settings`)
5. error throws, as described above

https://user-images.githubusercontent.com/37156449/152627625-3634094a-32a7-4174-8bc1-9f21d7bf5389.mp4

**Comment by pschwippert** [comment]
I am able to reproduce this issue, and this applies to Slack alerts as well, the webhook is not saved correctly.

**Comment by alexweav** [comment]
Related, this seems to also be happening with Slack: https://github.com/grafana/grafana/issues/47404

There seems to be an issue with loading secure settings.

**Comment by peterholmberg** [comment]
The issues are separate for legacy and unified, we use another component for unified.

**Comment by grobinson-grafana** [comment]
Hi! This issue appears to affect legacy dashboard alerts which are deprecated. Would you consider upgrading to Grafana Alerting in Grafana 9?
