### ISSUE TITLE
Mix data sources of different types or instances on the same panel

### ISSUE THREAD

**Issue by pfischermx** [grafana/grafana#436]
Maybe there is a way and I can't figure it out. But I've two datasources, both of them are influxdb. 

My config is something like this:

    datasources: {
influx_a: {
         default: true,
         url: 'http://a.com',
         type: 'influxdb',
         username: 'test',
         password: 'test',
},
influx_b: {
         url: 'http://b.com',
         type: 'influxdb',
         username: 'test',
         password: 'test',
}
},

I can add the metrics (the graph shows some RPS, one for the one found in datasource a and another line for datasource b) but I'm having problem in seeing _both_ lines, I either need to click on the select box for influx_a or influx_b. Is there a way to show both? So that I can see the line of 'influx_a' and 'influx_b'.

Thanks :)

**Comment by jwestboston** [comment]
I'm definitely interested in this feature as well.

It would help as I spread my metrics collection across multiple datacenters and countries (and availability zones and regions in AWS speak), but there are some metrics that I'd like to view all on one graph/chart.  Of course, Grafana would therefore have the right to assume that the metrics displayed are all indeed of the same type.

**Comment by naegelin** [comment]
Def. could see value to this as well.

**Comment by djnym** [comment]
+1 on this feature as well, maybe now that 2.0 is out?

**Comment by fernando-cloudster** [comment]
I +1 this feature too. 
Since we cant lock some metrics out of a user on the database side (influx in my case), I've been separating each clients metrics in a separate database.
Awesome for them, but sad for me as I cant cross data from clients on the same graph.

**Comment by simple-snow** [comment]
+1

**Comment by matthew-kruse** [comment]
+1 on this feature

**Comment by Vanhoeyl** [comment]
+1

**Comment by torkelo** [comment]
Did some big changes to data source query editors which enabled this feature, looks like this will be coming to Grafana 2.2, will enabled single panel with different data source types, or for example a graph with series from the same data source type but different servers, so for example if you have graphite test, graphite prod, graphite staging you could query all of them and plot series on the same graph :)

![image](https://cloud.githubusercontent.com/assets/10999/9292484/079ce608-43fc-11e5-9d18-49a29901e00d.png)

**Comment by torkelo** [comment]
This feature is now available in master and in the latest builds of 2.2.0-pre1

A new built in data source named `-- Mixed --` is a available in the Metrics tab of the graph panel, using this data source you can now add queries of different data source types or instances to the same panel!
