### ISSUE TITLE
Login page background doesn't cover the entire viewport on mobile

### ISSUE THREAD

**Issue by winterqt** [grafana/grafana#43604]
**What happened**:

The login page background doesn't cover the entire viewport on mobile. 

**What you expected to happen**:

For it to cover the entire viewport.

**How to reproduce it (as minimally and precisely as possible)**:

1. Navigate to the login page

**Anything else we need to know?**:

Screenshot of the issue:
![IMG_1710](https://user-images.githubusercontent.com/78392041/147838882-d024d936-4fb2-4d85-bbb0-03d365781e36.jpg)

**Environment**:
- Grafana version: v8.3.3
- OS Grafana is installed on: NixOS
- User OS & Browser: iOS 15.2, Safari

**Comment by ashharrison90** [comment]
unfortunately, i don't think there's a nice way to solve this. we set the `html`/`body`/background to have `height: 100%;`. on mobile, this is the height when the address bar is present.

when you first load the page (on android) the address bar is visible so this works as expected:

however if you scroll the address bar out of view, we see similar behaviour to what you're describing:

on safari i believe there's a bottom navbar as well to further complicate things.

we could set it to `100vh`, but that would cause other issues as that is the height without the address bar. so some pages would end up overflowing a full page on mobile. 

there are some reported solutions out there, all of which look hacky and not worth the effort imo. will discuss with the team tomorrow and see if anyone else knows something i don't. 😄 

note: you can't repro this when emulating via dev tools, you have to use an actual mobile browser.

**Comment by thisisobate** [comment]
Tried reproducing on ios 15.2 using the safari browser.
Had similar experience as you did @ashharrison90 

Works fine on load but when you scroll, the issue appears.

**Comment by ashharrison90** [comment]
my inclination is to mark this as `wontfix`. as far as i can tell this is a quirk of mobile browsers, and although there are some solutions none of them look nice.

@winterqt can you confirm if you also only see this view after scrolling, or does it appear like that immediately? 🤔

**Comment by ashharrison90** [comment]
ok nm, found a cheeky `min-height: 100vh` buried in the code 😅

fix incoming!
