### ISSUE TITLE
Alert-Groups Panel does not allow templating of AlertManager Source

### ISSUE THREAD

**Issue by siegenthalerroger** [grafana/grafana#43611]
**What happened**: I tried using a variable in the name of the AlertManager in the new (alpha) Alert-Groups panel. This isn't even possible without directly editing the JSON.

**What you expected to happen**: As every other panel, the datasource should accept variables to allow a repeat-rows or panels to function.

**How to reproduce it (as minimally and precisely as possible)**: Add a new variable, add an alert-groups panel, try to use the variable to switch the AM used as datasource for the alert-groups panel (either with a repeat function or drop-down selector).

**Anything else we need to know?**: I understand that this is a alpha panel, as such this bug report is intended merely to make sure the issue isn't ignored before a full release. I hope this is the correct place to report this deviance of the panel from other grafana panels.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: AlertManager - built-in pre-release Datasource
- OS Grafana is installed on: Ubuntu, AKS Deployment
- User OS & Browser: MacOS & Chrome
- Grafana plugins: None except defaults

**Comment by peterholmberg** [comment]
Hello @siegenthalerroger, thanks for reporting this. Just a heads up, we are currently re evaluating the need for the alert groups panel and might merge it with the alert list panel

**Comment by siegenthalerroger** [comment]
Thanks for the update, yeah of course that makes sense. Having both is definitely redundant. Still something that should be ensured in a future merged version.

**Comment by konrad147** [comment]
We have `Custom grouping` option available in Alert list panel that can be used instead of the Alert Groups panel.
