### ISSUE TITLE
Failed to create external snapshot at raintank

### ISSUE THREAD

**Issue by tommyknows** [grafana/grafana#43617]
**What happened**:
When trying to publish a snapshot to the default external `snapshot.raintank.io` server, the request fails with "Failed to create external snapshot". 
In the logs, I can see the following message:
```
EROR[01-03|14:25:24] Failed to create external snapshot       logger=context userId=1 orgId=1 uname=admin error="create external snapshot response status code 500"
EROR[01-03|14:25:24] Request Completed                        logger=context userId=1 orgId=1 uname=admin method=POST path=/api/snapshots status=500 remote_addr=172.17.0.1 time_ms=527 size=54 referer="http://localhost:3000/d/hzTdjxAnk/test?orgId=1"
```

**What you expected to happen**: 
Snapshot publishing works with the default configuration. Or the documents explain why it does not work by default (I haven't found anything at least?).

**How to reproduce it (as minimally and precisely as possible)**:
`docker run --it --rm -p 3000:3000 grafana/grafana:latest`, logging in on the WebUI, creating a dashboard, clicking on the share button -> Snapshot -> Publish to snapshot.raintank.io.

Changing the timeout does not change anything.

**Anything else we need to know?**:
I've spun up a second Grafana instance with `public_mode = true`, and publishing to that instance works. 

The request that is being made looks sensible:
<details>
  <summary>Request Payload</summary>
<pre>
{"dashboard":{"annotations":{"list":[{"name":"Annotations & Alerts","enable":true,"iconColor":"rgba(0, 211, 255, 1)","snapshotData":[],"type":"dashboard","builtIn":1,"hide":true}]},"editable":true,"fiscalYearStartMonth":0,"graphTooltip":0,"id":1,"links":[],"liveNow":false,"panels":[{"fieldConfig":{"defaults":{"color":{"mode":"palette-classic"},"custom":{"axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"type":"linear"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]}},"overrides":[]},"gridPos":{"h":9,"w":12,"x":0,"y":0},"id":2,"options":{"legend":{"calcs":[],"displayMode":"list","placement":"bottom"},"tooltip":{"mode":"single"}},"snapshotData":[{"fields":[{"config":{"color":{"mode":"palette-classic"},"custom":{"axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"showPoints":"auto","thresholdsStyle":{"mode":"off"}},"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]}},"name":"time","type":"time","values":[1641198712319,1641198742319,1641198772319,1641198802319,1641198832319,1641198862319,1641198892319,1641198922319,1641198952319,1641198982319,1641199012319,1641199042319,1641199072319,1641199102319,1641199132319,1641199162319,1641199192319,1641199222319,1641199252319,1641199282319,1641199312319,1641199342319,1641199372319,1641199402319,1641199432319,1641199462319,1641199492319,1641199522319,1641199552319,1641199582319,1641199612319,1641199642319,1641199672319,1641199702319,1641199732319,1641199762319,1641199792319,1641199822319,1641199852319,1641199882319,1641199912319,1641199942319,1641199972319,1641200002319,1641200032319,1641200062319,1641200092319,1641200122319,1641200152319,1641200182319,1641200212319,1641200242319,1641200272319,1641200302319,1641200332319,1641200362319,1641200392319,1641200422319,1641200452319,1641200482319,1641200512319,1641200542319,1641200572319,1641200602319,1641200632319,1641200662319,1641200692319,1641200722319,1641200752319,1641200782319,1641200812319,1641200842319,1641200872319,1641200902319,1641200932319,1641200962319,1641200992319,1641201022319,1641201052319,1641201082319,1641201112319,1641201142319,1641201172319,1641201202319,1641201232319,1641201262319,1641201292319,1641201322319,1641201352319,1641201382319,1641201412319,1641201442319,1641201472319,1641201502319,1641201532319,1641201562319,1641201592319,1641201622319,1641201652319,1641201682319,1641201712319,1641201742319,1641201772319,1641201802319,1641201832319,1641201862319,1641201892319,1641201922319,1641201952319,1641201982319,1641202012319,1641202042319,1641202072319,1641202102319,1641202132319,1641202162319,1641202192319,1641202222319,1641202252319,1641202282319,1641202312319,1641202342319,1641202372319,1641202402319,1641202432319,1641202462319,1641202492319,1641202522319,1641202552319,1641202582319,1641202612319,1641202642319,1641202672319,1641202702319,1641202732319,1641202762319,1641202792319,1641202822319,1641202852319,1641202882319,1641202912319,1641202942319,1641202972319,1641203002319,1641203032319,1641203062319,1641203092319,1641203122319,1641203152319,1641203182319,1641203212319,1641203242319,1641203272319,1641203302319,1641203332319,1641203362319,1641203392319,1641203422319,1641203452319,1641203482319,1641203512319,1641203542319,1641203572319,1641203602319,1641203632319,1641203662319,1641203692319,1641203722319,1641203752319,1641203782319,1641203812319,1641203842319,1641203872319,1641203902319,1641203932319,1641203962319,1641203992319,1641204022319,1641204052319,1641204082319,1641204112319,1641204142319,1641204172319,1641204202319,1641204232319,1641204262319,1641204292319,1641204322319,1641204352319,1641204382319,1641204412319,1641204442319,1641204472319,1641204502319,1641204532319,1641204562319,1641204592319,1641204622319,1641204652319,1641204682319,1641204712319,1641204742319,1641204772319,1641204802319,1641204832319,1641204862319,1641204892319,1641204922319,1641204952319,1641204982319,1641205012319,1641205042319,1641205072319,1641205102319,1641205132319,1641205162319,1641205192319,1641205222319,1641205252319,1641205282319,1641205312319,1641205342319,1641205372319,1641205402319,1641205432319,1641205462319,1641205492319,1641205522319,1641205552319,1641205582319,1641205612319,1641205642319,1641205672319,1641205702319,1641205732319,1641205762319,1641205792319,1641205822319,1641205852319,1641205882319,1641205912319,1641205942319,1641205972319,1641206002319,1641206032319,1641206062319,1641206092319,1641206122319,1641206152319,1641206182319,1641206212319,1641206242319,1641206272319,1641206302319,1641206332319,1641206362319,1641206392319,1641206422319,1641206452319,1641206482319,1641206512319,1641206542319,1641206572319,1641206602319,1641206632319,1641206662319,1641206692319,1641206722319,1641206752319,1641206782319,1641206812319,1641206842319,1641206872319,1641206902319,1641206932319,1641206962319,1641206992319,1641207022319,1641207052319,1641207082319,1641207112319,1641207142319,1641207172319,1641207202319,1641207232319,1641207262319,1641207292319,1641207322319,1641207352319,1641207382319,1641207412319,1641207442319,1641207472319,1641207502319,1641207532319,1641207562319,1641207592319,1641207622319,1641207652319,1641207682319,1641207712319,1641207742319,1641207772319,1641207802319,1641207832319,1641207862319,1641207892319,1641207922319,1641207952319,1641207982319,1641208012319,1641208042319,1641208072319,1641208102319,1641208132319,1641208162319,1641208192319,1641208222319,1641208252319,1641208282319,1641208312319,1641208342319,1641208372319,1641208402319,1641208432319,1641208462319,1641208492319,1641208522319,1641208552319,1641208582319,1641208612319,1641208642319,1641208672319,1641208702319,1641208732319,1641208762319,1641208792319,1641208822319,1641208852319,1641208882319,1641208912319,1641208942319,1641208972319,1641209002319,1641209032319,1641209062319,1641209092319,1641209122319,1641209152319,1641209182319,1641209212319,1641209242319,1641209272319,1641209302319,1641209332319,1641209362319,1641209392319,1641209422319,1641209452319,1641209482319,1641209512319,1641209542319,1641209572319,1641209602319,1641209632319,1641209662319,1641209692319,1641209722319,1641209752319,1641209782319,1641209812319,1641209842319,1641209872319,1641209902319,1641209932319,1641209962319,1641209992319,1641210022319,1641210052319,1641210082319,1641210112319,1641210142319,1641210172319,1641210202319,1641210232319,1641210262319,1641210292319,1641210322319,1641210352319,1641210382319,1641210412319,1641210442319,1641210472319,1641210502319,1641210532319,1641210562319,1641210592319,1641210622319,1641210652319,1641210682319,1641210712319,1641210742319,1641210772319,1641210802319,1641210832319,1641210862319,1641210892319,1641210922319,1641210952319,1641210982319,1641211012319,1641211042319,1641211072319,1641211102319,1641211132319,1641211162319,1641211192319,1641211222319,1641211252319,1641211282319,1641211312319,1641211342319,1641211372319,1641211402319,1641211432319,1641211462319,1641211492319,1641211522319,1641211552319,1641211582319,1641211612319,1641211642319,1641211672319,1641211702319,1641211732319,1641211762319,1641211792319,1641211822319,1641211852319,1641211882319,1641211912319,1641211942319,1641211972319,1641212002319,1641212032319,1641212062319,1641212092319,1641212122319,1641212152319,1641212182319,1641212212319,1641212242319,1641212272319,1641212302319,1641212332319,1641212362319,1641212392319,1641212422319,1641212452319,1641212482319,1641212512319,1641212542319,1641212572319,1641212602319,1641212632319,1641212662319,1641212692319,1641212722319,1641212752319,1641212782319,1641212812319,1641212842319,1641212872319,1641212902319,1641212932319,1641212962319,1641212992319,1641213022319,1641213052319,1641213082319,1641213112319,1641213142319,1641213172319,1641213202319,1641213232319,1641213262319,1641213292319,1641213322319,1641213352319,1641213382319,1641213412319,1641213442319,1641213472319,1641213502319,1641213532319,1641213562319,1641213592319,1641213622319,1641213652319,1641213682319,1641213712319,1641213742319,1641213772319,1641213802319,1641213832319,1641213862319,1641213892319,1641213922319,1641213952319,1641213982319,1641214012319,1641214042319,1641214072319,1641214102319,1641214132319,1641214162319,1641214192319,1641214222319,1641214252319,1641214282319,1641214312319,1641214342319,1641214372319,1641214402319,1641214432319,1641214462319,1641214492319,1641214522319,1641214552319,1641214582319,1641214612319,1641214642319,1641214672319,1641214702319,1641214732319,1641214762319,1641214792319,1641214822319,1641214852319,1641214882319,1641214912319,1641214942319,1641214972319,1641215002319,1641215032319,1641215062319,1641215092319,1641215122319,1641215152319,1641215182319,1641215212319,1641215242319,1641215272319,1641215302319,1641215332319,1641215362319,1641215392319,1641215422319,1641215452319,1641215482319,1641215512319,1641215542319,1641215572319,1641215602319,1641215632319,1641215662319,1641215692319,1641215722319,1641215752319,1641215782319,1641215812319,1641215842319,1641215872319,1641215902319,1641215932319,1641215962319,1641215992319,1641216022319,1641216052319,1641216082319,1641216112319,1641216142319,1641216172319,1641216202319,1641216232319,1641216262319,1641216292319,1641216322319,1641216352319,1641216382319,1641216412319,1641216442319,1641216472319,1641216502319,1641216532319,1641216562319,1641216592319,1641216622319,1641216652319,1641216682319,1641216712319,1641216742319,1641216772319,1641216802319,1641216832319,1641216862319,1641216892319,1641216922319,1641216952319,1641216982319,1641217012319,1641217042319,1641217072319,1641217102319,1641217132319,1641217162319,1641217192319,1641217222319,1641217252319,1641217282319,1641217312319,1641217342319,1641217372319,1641217402319,1641217432319,1641217462319,1641217492319,1641217522319,1641217552319,1641217582319,1641217612319,1641217642319,1641217672319,1641217702319,1641217732319,1641217762319,1641217792319,1641217822319,1641217852319,1641217882319,1641217912319,1641217942319,1641217972319,1641218002319,1641218032319,1641218062319,1641218092319,1641218122319,1641218152319,1641218182319,1641218212319,1641218242319,1641218272319,1641218302319,1641218332319,1641218362319,1641218392319,1641218422319,1641218452319,1641218482319,1641218512319,1641218542319,1641218572319,1641218602319,1641218632319,1641218662319,1641218692319,1641218722319,1641218752319,1641218782319,1641218812319,1641218842319,1641218872319,1641218902319,1641218932319,1641218962319,1641218992319,1641219022319,1641219052319,1641219082319,1641219112319,1641219142319,1641219172319,1641219202319,1641219232319,1641219262319,1641219292319,1641219322319,1641219352319,1641219382319,1641219412319,1641219442319,1641219472319,1641219502319,1641219532319,1641219562319,1641219592319,1641219622319,1641219652319,1641219682319,1641219712319,1641219742319,1641219772319,1641219802319,1641219832319,1641219862319,1641219892319,1641219922319,1641219952319,1641219982319,1641220012319,1641220042319,1641220072319,1641220102319,1641220132319,1641220162319,1641220192319,1641220222319,1641220252319,1641220282319]},{"config":{"color":{"mode":"palette-classic"},"custom":{"axisLabel":"","axisPlacement":"auto","barAlignment":0,"drawStyle":"line","fillOpacity":0,"gradientMode":"none","hideFrom":{"legend":false,"tooltip":false,"viz":false},"lineInterpolation":"linear","lineWidth":1,"pointSize":5,"scaleDistribution":{"type":"linear"},"showPoints":"auto","spanNulls":false,"stacking":{"group":"A","mode":"none"},"thresholdsStyle":{"mode":"off"}},"mappings":[],"thresholds":{"mode":"absolute","steps":[{"color":"green","value":null},{"color":"red","value":80}]}},"labels":{},"name":"A-series","type":"number","values":[42.53058832926032,42.25488617692872,42.14195525145631,42.06696637568407,42.40903304226299,42.616903863155656,42.96772800878399,43.38355445963041,43.23247422809412,42.90142682711939,43.15565083764756,42.99012616743732,42.871296648010905,43.168040605160726,43.372321905999165,42.96000675862568,43.11573190000736,43.40145614103352,43.69304485945769,43.73767793620324,43.81191194910391,43.90271061437428,43.4122073947796,43.44855309772172,43.30956356901467,43.71412214190344,43.216661836490466,42.722084532939036,42.28444846469634,41.96914532049556,42.322861475245034,42.072232488475414,41.86650138643487,42.298824553163605,41.92827089517783,42.18715239417054,41.72024856213672,41.93124626835818,41.68025993445073,41.226650066885036,41.638621462450686,41.62612404289308,41.81313821251816,42.1578335247231,42.56661478478498,43.02124910702952,43.148417417469844,43.52036543157231,43.929432350358184,43.92947658152556,44.153848248815116,43.791893357741095,43.893276582402386,43.75826532216899,43.34350041230812,43.711720366717486,43.25637880680378,42.784141317362305,42.60957854457646,43.02379732116071,42.55674388891305,42.19790046923072,41.877498030841174,42.29104164396344,41.88499557870996,42.04956183985058,42.07362592259789,41.7318768936384,41.51495735105151,41.699067559823355,41.978380277833246,41.53280162811121,41.96538367609871,41.571996316846445,41.31925472116187,41.0271291702187,41.23113982716114,40.86493574594828,40.47343372969992,40.460643300935565,40.53398579785889,40.82262354092187,40.982662306217875,41.317471407061156,40.97744890170698,40.93822515346117,41.381636108835245,41.559652168427164,41.79829577921472,41.628849297268886,41.50559906041866,41.193362360086645,40.954771113555644,40.731471368250425,41.1497332125184,41.282377198519505,40.89712619893629,41.1920228534848,41.21151017566595,40.71676526549135,40.97710468052787,40.64603641386388,40.24209229343076,40.51526407046097,40.443799695981035,40.02082609076048,40.281971629326016,39.90745957323479,40.20434875920235,40.32223651259645,39.92808762935336,40.121770092280215,39.92763492080117,40.1780273774189,40.14324828471222,40.38172176946582,39.945100987481055,39.534087786916615,39.542479889235665,39.88805479457579,39.68077949172829,39.54579875037606,39.91580988452813,40.04573192351574,39.91844431119572,39.73721583031749,39.99521917358052,40.27705689104673,40.1682385859523,39.76527151630653,39.64625281569338,39.74526115616348,39.9413093285369,39.827738324815535,40.233320973621524,40.61194313731294,40.705445504622126,41.112403281643196,41.32359657112789,41.14337756242351,41.223522923372556,41.596016112403674,41.19651568400677,41.693236952769844,42.02207133278357,41.65369591482669,41.405887942460836,41.304493769392764,41.122534744478074,41.13228491604527,41.27888991362399,41.4584923303722,41.50323397718565,41.81715740614261,41.92351881005982,41.99832819860039,42.299192859118,42.47793115170847,41.990379418306176,42.20539530101777,42.12542613553749,41.636394663991666,41.932510550355204,42.223349657132964,42.42778809061613,42.658278589037884,42.53887153868158,42.578279707427775,42.49845121972292,42.18031592531277,41.86929446737516,41.68783777830237,41.62934668792665,41.155332154696346,41.16194085037525,41.27873910714735,41.02859095446722,41.49870593871744,41.56455242337475,41.151416133325796,41.64933594466305,41.75572325011467,42.072135378618945,41.929071766546,42.21039215078083,42.63789185223084,42.304824257529845,42.48474250997182,42.26387126641626,42.20077894099421,42.20980132788213,41.776136796617585,42.12899606227676,42.29591865876715,42.54281028447878,42.94609332856303,42.813275688972645,43.221913435617196,43.26827863055259,43.0404349593823,43.190497297894524,43.00408746137713,43.34248308792075,42.926350253334434,42.48874628296157,42.14564221230797,41.74110297928651,41.82057175296336,41.77928095430709,42.21347652434807,41.92262713546819,41.480959962533255,41.121081785826036,41.059797164530046,41.121743809925846,40.77870083383543,40.65306288266436,40.87657111690926,40.96812041628397,41.169491832585784,40.87309695049977,41.22552204273912,41.55994650038507,41.41136961127862,41.30423989546154,41.46303656868653,41.42429557969304,41.0544028849107,41.07750157196603,41.533380359727374,41.90279431641569,42.049942030670685,42.54226696058521,42.897200927049234,43.00775361574932,42.599570436701086,43.03261832979898,42.8171602687376,42.33446684979065,42.108944466054254,41.83843452938249,41.598392524223065,41.86846111252922,41.88030936381174,41.94409546589817,41.45347785204217,40.968854094391354,41.325369708570534,40.838788804036305,41.234758608276074,41.705430044071335,41.328774999273755,41.29387658529862,40.96356201442873,40.520513050688486,40.66070706056187,41.008339334985834,40.598971185577525,40.16745775972494,40.35650022267958,40.855558321158625,40.62018934460481,40.19330114389482,40.065300005843945,39.93222354763306,39.73972611402719,39.93541280770277,39.696913909707185,40.004993012133426,40.225954044671646,40.396575062126836,40.864703322151826,40.60138506298582,40.57165794382039,40.48982796301319,40.57851104000988,40.56149257528059,40.10746817274804,40.28821936949394,40.46346467809343,40.05687839976613,40.188942090598445,40.03512843183492,39.943536777606916,39.51227293922653,39.607977970862414,39.1688115531652,38.88951855239417,38.50108584590257,38.69360221154126,38.762026213700224,38.46224937315075,38.2223694681504,37.944215088142776,38.327991336503615,38.67492267417895,38.392838309752555,38.462176330358616,37.999999548996655,38.29934439188818,38.34542283447463,38.26221327161879,38.689249472709946,38.62617171428697,38.85414093734473,38.82280519467421,39.17381827923654,38.866965056772784,38.862505719187155,38.53890707760423,38.75410097244166,38.76361352923191,38.612345265153,38.41861331836934,38.436055061986025,38.05036245799229,37.79946641062684,37.92444715333076,37.760981916853304,37.37602168194266,37.33560200650793,36.95862088355167,36.563573043102785,36.76005624560074,36.898181529322606,36.801437898832035,37.150172180211094,36.923249129280954,37.225233443080256,37.369271519264174,37.25193227312037,36.817904919908,37.2184184321162,37.40150892313864,37.333102786559685,37.10123660692851,36.7557124335501,36.297995093221324,36.15135865588583,35.95821432592951,36.22276559420824,36.70360851519121,36.33116364941724,36.31375496256066,36.0435714063796,35.930197255761335,35.689398020186054,35.39608108143476,35.511916773777166,35.67346578514443,35.539538253622645,35.62948287455114,35.253403269265824,35.676896846767406,35.72380699742801,36.181469367323366,36.27039937395338,36.506691837095985,36.42113378875527,35.970559858633365,36.30210185544119,36.153759726839766,36.0960966815337,36.5455289785661,36.78988505148668,36.97624494127554,36.575717488937585,36.50423473685337,36.74816948623454,36.67843479738616,36.237056386669174,36.120651709672416,36.17277072783435,35.98619363187683,35.59451545800623,35.536385091349814,35.43966750117048,35.59004089865937,35.69815322604511,35.71892485862934,35.47681605449299,35.571596383247744,35.86702766274286,35.548601341874054,35.34907542160289,35.80026845248399,36.26542085704316,35.83432111679279,36.29502435826502,36.788675556836196,37.2312627446603,37.1979951930622,37.35794702848657,37.16187728804531,36.8064093271922,36.6013704445918,36.85723437312612,36.89216444682738,37.179862870156754,37.31579469423616,36.82243473258586,36.32627910710566,36.221554203395996,35.76097541296506,35.70029561212486,35.324807614935644,35.322242292224715,35.18610191606133,34.71152494340757,34.48628938313938,34.25600743693087,34.3573602914205,34.52312873215496,34.56931995326168,34.40338783343645,34.61840262392878,34.65856602013242,34.516294027266795,34.03010249171621,34.46500320397668,34.82819174987403,34.497797134760006,34.19037260682754,33.74052190814308,33.766674163017804,33.70497650078748,33.63752068838118,33.817625395735384,33.81363911369725,33.54161681251286,33.569585805039075,33.965807804178986,34.31460001694728,34.60079855647964,34.51346778936906,34.13161215521346,34.25030544927867,33.803723425831656,33.834582428338436,33.692392017453344,33.29249100347049,33.749852302550394,33.95152685313739,34.257883209761836,34.27796762606681,33.89211417926336,33.6326051585616,33.280753495860374,33.64775873469379,33.96686341975332,34.16647478626146,34.60953818301687,34.2653105005606,33.82678411307739,33.490784838071015,33.58046594943379,33.376233482728935,33.41429325566196,33.86606929840293,33.7508125356697,34.03095904206422,33.606166307675515,33.294642246774856,32.79513996331222,32.87119656431151,32.634545147227875,32.83145262521715,33.09913249085515,32.987266178394826,32.66413540859316,32.19754895725657,32.46574147811233,32.466170869543234,32.47934065784098,32.074073980417126,31.745502916864407,31.50784575119007,31.579597876704717,31.22205473771927,31.01408520123665,31.488321259267636,31.168064296980315,30.904750058542774,31.312549932705213,30.979250412939408,31.163702572264683,31.112005057886076,31.035397328651506,31.340889459533965,31.401179353873992,31.336748317719913,31.676847969251156,31.7015809893394,31.51820837712281,31.274118903794502,31.600750584728555,31.715801452119987,31.51666097164143,31.118738926953114,31.345733310310532,31.589599741701132,31.164549900161703,31.659096502138624,31.174784105267264,31.23530755432953,31.19963517534863,31.240857068233492,31.315320466212132,31.31454844478165,31.39831792717674,31.796969981323148,31.583446461735626,31.820590843590367,31.72114891075767,31.752457493110832,32.00262628109207,32.32288577420522,32.683006421694415,33.09349148353677,33.311940023284876,33.20290743196332,33.288734020958834,33.499191370022274,33.210587374316376,32.97832413595629,33.14986301591244,33.109984791258995,32.708807806618054,32.27884369183742,32.62053163019801,32.54312731907962,33.00906318156253,33.48787537855208,33.77709803582256,33.677703495851254,33.88848570628448,34.08642497030221,34.40951204293403,34.09306066684589,34.208814303535725,33.969802080484634,33.75214756324874,33.64828235430068,33.314967081706236,33.151088442607055,33.06662490823992,33.48211503783787,33.018133045418296,32.747874099593204,32.93149640500268,33.13443625633925,33.02034461991124,33.47577774146805,33.37739874834191,32.91913584369427,32.94901689402848,33.37886248322393,33.30317573811366,32.8602945987193,32.48483436164288,32.60969239541068,32.667739572945514,32.822483048710964,32.499780986670274,32.79936694617877,32.99013388777272,33.00853352595821,32.745951413826376,32.47632813183192,32.61735223142871,32.528732123741165,32.945224503306086,33.06112416495817,33.381546251223654,33.01317418668122,32.657438512807744,32.47261825737302,32.266248837877924,32.4851699779999,32.56697501069372,32.22807512729455,32.52711280935349,32.45867644241989,32.03066646130729,31.546146403242297,31.991756309673328,32.37641428039744,32.084342824133444,32.15359194298819,32.37816399134339,32.73508117280143,33.14886254983287,33.27783031677336,33.2179040238106,33.164239714810606,33.42371174335567,33.37285500559247,33.392605640231345,33.00414051921366,32.79632060363265,32.67412867352861,32.90854013902089,33.0299708243598,33.47683335725683,33.29617086691229,33.30854839198356,33.7811877984217,34.216903882627726,34.04967857525524,34.454952887584135,34.8002037556079,35.132720606705746,35.53046491689066,35.69781126433712,36.10769802752432,36.31776944375826,35.96901705056668,36.39328747341423,36.74608162190033,37.06018028680074,37.55944692787377,37.59233853195785,37.47439665296019,37.710067038674204,38.148376669098504,38.418885185137384,38.72087664998253,38.701857318427734,38.30857586648234,38.280818002673584,38.07150094253415,38.47962430295729,38.63932747704251,38.307254361418124,38.65811818068854,38.469385155308274,38.83787902895912,38.753226749918284,38.281688042808305,38.71974214608923,38.880707237758195,38.8812686561188,39.247206719350366,39.00665880742693,38.7260438959059,38.34096843885318,38.391703009287056,38.07093377833581,38.41772439480925,38.876412114336944,39.289782046271014,39.423341287848764,39.6789908892631,39.94148115297509,40.0321027866239,39.55051503272406,39.48085704068048,39.45271925618867,39.225055994745176,39.69433445656926,40.03543369191347,40.286222208003515,40.31694227627596,40.507034125973476,40.28726965329975,40.09025206238827,39.730919120544264,39.66861233787882,39.65092740970675,39.99814647537422,39.68544807557438,39.36139586216027,39.14654380720934,38.8871158612344,38.770316584194894,39.13230577980186,39.221932984338565,39.5096497793855,39.22319629458033,39.70216825238412,40.131620643624935,40.42421806496773,39.94699413036868,40.444419343667654,40.80714032111728,41.100171517891376,40.66432479493211,40.784766400388555,40.8152571248754,41.30739889485458,40.941278874422764,40.861754743922845,40.68763487998724,40.3336052395189,40.79512875651631,40.506735859118166,40.082703227335806,39.66686894654369,39.92990773227618,39.50194559924815,39.95686675825524,40.40040436737744,39.907249650774176,39.793965367615414,39.71893110488207,40.20221577261977,39.88504278932868,40.08105364126346,40.484287945296366,40.14095918400489,39.80879097249847,40.204442120575294,40.612641586137634,40.914431872389464,41.333621153763744,41.509551044311664,41.39975822487165,41.61764495286844,41.28697636248364,41.68382278750183]}],"refId":"A"}],"title":"Panel Title","type":"timeseries","targets":[],"links":[],"datasource":null}],"schemaVersion":34,"snapshot":{"timestamp":"2022-01-03T14:31:52.307Z"},"style":"dark","tags":[],"templating":{"list":[]},"time":{"from":"2022-01-03T08:31:56.329Z","to":"2022-01-03T14:31:56.329Z","raw":{"from":"now-6h","to":"now"}},"timepicker":{},"timezone":"","title":"test","uid":"eUrrjbA7z","version":1,"weekStart":""},"name":"test","expires":0,"external":true}
</pre>
</details>

If I understand the [code](https://github.com/grafana/grafana/blob/main/pkg/api/dashboard_snapshot.go#L79) correctly, this request is more or less being passed through to the upstream server, which is [by default](https://grafana.com/docs/grafana/latest/administration/configuration/#external_snapshot_url) `snapshots-origin.raintank.io`. 

**Environment**:
- Grafana version: v8.3.3
- Data source type & version: n/a
- OS Grafana is installed on: Docker container
- User OS & Browser: MacOS / Safari.
- Grafana plugins: none.
- Others: n/a

**Comment by AymanSalamn** [comment]
Same issue here!

**Comment by darbetti** [comment]
Ditto, same issue!

**Comment by kaydelaney** [comment]
Seems like there was an issue with the server. Seems to be fixed now on my end, but let me know if it's still causing problems

**Comment by darbetti** [comment]
@kaydelaney I've just tried again, but I keep getting "Failed to create external snapshot" error message :-(

**Comment by tommyknows** [comment]
Issue still exists for me too.

**Comment by k100956** [comment]
same issue..

**Comment by zer0kool** [comment]
Same issue here. Clean Grafana local instance and sharing the home dashboard. 

<img width="529" alt="Screenshot_3" src="https://user-images.githubusercontent.com/15951765/148350203-7c594d6e-ffb3-4dec-8b0a-68c843ce4676.png">

**Comment by joshhunt** [comment]
I am able to replicate this with the docker command `docker run --interactive --tty --rm -p 3000:3000 grafana/grafana:latest` and with play.grafana.com. I tried earlier from a Grafana Cloud dev instance and it worked, but just now it has failed.

When I ran Grafana locally (in Docker) it logged the error "Post \"https://snapshots-origin.raintank.io/api/snapshots\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)".

**Comment by kaydelaney** [comment]
Here's the current status of the issue:

> We are in the process of migrating the snapshot server to new infrastructure, which should give us greater stability. We hope to complete this within the next two weeks. In the meantime, we will keep an eye on the existing server.

Apologies for the inconvenience!

**Comment by rajaooxx** [comment]
Hello, this issue seems to have reappeared, what is the current status? Is it being fixed?

![image](https://user-images.githubusercontent.com/35056782/150622540-8773a5a0-b4e9-4faa-bdaa-3b04187e34ad.png)

**Comment by kristiankanchev** [comment]
> Here's the current status of the issue:
> 
> > We are in the process of migrating the snapshot server to new infrastructure, which should give us greater stability. We hope to complete this within the next two weeks. In the meantime, we will keep an eye on the existing server.
> 
> Apologies for the inconvenience!

@kaydelaney Is there an official statement about this? I am asking for audit purposes.

**Comment by malcolmholmes** [comment]
Thanks for the report. We acknowledge the issue, but we expect it to take a number of ours to resolve.

https://status.grafana.com/incidents/3f5mfxzbpgmp

**Comment by malcolmholmes** [comment]
Apologies for this long outage. We have completed the migration to new infrastructure. We expect this service to be more stable now.

**Comment by comnam90** [comment]
So if we're seeing this issues again @malcolmholmes ?
