### ISSUE TITLE
HTML table parameters border = 0 or border = none doesn't work in Grafana text panel.

### ISSUE THREAD

**Issue by Allan10000** [grafana/grafana#43627]
HTML table parameters border = 0 or border = none doesn't work in Grafana text panel. And when using HTML tables, the border defaults to display the borders. We want to be able to remove these borders from the dashboard panels.

Below are examples of the commands being used.  In both cases, the parameter is ignored and the border defaults as visible.
<table border="none"><td>test</td></table>
<table border="0"><td>test</td></table>

and the following command defaults to having visible borders as well.
<table><td>test</td></table>

I expect no borders, or the ability to make the borders disappear.

**Comment by torkelo** [comment]
you will have add custom styling to override the default markdown table styles,  style="border: none"

**Comment by Allan10000** [comment]
Hi Torkelo, thanks for the reply.  I have been unsuccessful in applying styles in the Grafana text panel.  It seems that Grafana doesn't understand the styles commands and just displays the stanzas as plain text.  Unlike with the border parameters in the table markup in HTML which is also ignored, but they are not displayed as plain text.  Can you please point me to a working example?

**Comment by torkelo** [comment]
@Allan10000 style="border:none" seems to work for me

**Comment by Allan10000** [comment]
I have attached a screen shot where you can see my attempt in using the style parameter in tables in the Content field to the right.  But after applying the changes the border of the table around Hotlinks, Menu 1, Menu 2, Menu 3 are still visible.  I'm not sure what is missing.

<table style="border:none" width="100%">

![style command](https://user-images.githubusercontent.com/97059697/148085079-86cd5536-6d63-4fcc-8d9e-cf4da69cd287.png)
.

**Comment by torkelo** [comment]
example: 
https://play.grafana.org/d/roFzEL0nz/html-table-border?orgId=1

If you disable html escaping (in server ini settings) you can use style tags in html panel to add new css classes as well

**Comment by Allan10000** [comment]
Hi Torkelo,  Thanks for sending the example.  With it I was able to figure out the issue.  Looks like it was a typo error on my part.  I was missing the tailing semi-colon before the closing double quotes in the parameter of the style command.   style="border:none;"  Once I put the semi-colon in and applied the change, the borders disappeared from that particular one. 
![style command v1](https://user-images.githubusercontent.com/97059697/148093229-08b7e017-b800-4341-bc7c-c9d6739b4570.png)
