### ISSUE TITLE
API support for query string CRUD

### ISSUE THREAD

**Issue by leslie-wang** [grafana/grafana#4362]
We have our own UI, and want to integrate Grafana in such a way:
  - high level statistics embed in our UI dashboard
  - high level statistics panel can be created/update through API
  - panel URL can be get and embed in our UI dashboard.
  - detail statistics uses native grafana UI

Seems like current APIs doesn't have such support. Thus, we hope Grafana can provide such APIs.

**Comment by torkelo** [comment]
you can embed a panel using iframe emedding,
http://docs.grafana.org/reference/sharing/#embed-panel

you can create/update dashboards using http api:
http://docs.grafana.org/reference/http_api/
