### ISSUE TITLE
Postgres Database Connection Always Successful

### ISSUE THREAD

**Issue by bbernays** [grafana/grafana#43638]
**What happened**:

When a user sets up a Postgres database as a source and clicks on `Save and Test` as long as the changes are saved successfully the UI will display a `Database Connection OK` message.

**What you expected to happen**:

If the call to `api/ds/query` returns an error I would expect the UI to show that error.

**How to reproduce it (as minimally and precisely as possible)**:

Create a Postgres datasource. Any hostname + port, Any password + user. Disable SSL/TLS. 
Press `Save and Test`

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- `v8.4.0-pre (unknown-dev)`
- Data source type & version:
   - Postgres 12+
- OS Grafana is installed on:
   - OSX M1 
- User OS & Browser:
- Chrome

**Comment by ivanahuckova** [comment]
I was able to reproduce this as well. The issue happens in [testDatasource() function](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/postgres/datasource.ts#L178 ). We use [metricFindQuery()](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/postgres/datasource.ts#L126) to test data source, but metricFindQuery never returns error. Instead it returns `catchError((err) => return of([]);)`.

**Comment by bbernays** [comment]
The error is returned within the response from the server, but the server always returns a 200 status. Here is an example of the failed response:

```
{"results":{"tempvar":{"error":"db query error: pq: password authentication failed for user \"postgres\"","frames":[{"schema":{"refId":"tempvar","meta":{"executedQueryString":"SELECT 1"},"fields":[]},"data":{"values":[]}}]}}}

```
