### ISSUE TITLE
Docs feedback: broken image link on /dashboards/time-range-controls.md

### ISSUE THREAD

**Issue by zuchka** [grafana/grafana#43639]
see the broken image link below the subheading https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/

`Common time range controls`

**Comment by ivanahuckova** [comment]
@grafana/docs-squad the content have been updated in https://github.com/grafana/grafana/pull/39847/files, but the new image wasn't added to https://github.com/grafana/website/tree/master/static/static/img/docs/time-range-controls.

**Comment by achatterjee-grafana** [comment]
I do not see any broken image link. Is it OK to close the bug @ivanahuckova? Perhaps the issue was fixed elsewhere?

**Comment by ivanahuckova** [comment]
Yes, closing the issue! :)
