### ISSUE TITLE
Count column for table size legend formated incorrectly when Unit defined

### ISSUE THREAD

**Issue by wfjm** [grafana/grafana#43654]
**What happened**:
I’m using an InfluxDB Flux data source.  
I’ve setup a panel with `Time series` visualization and a legend showing `Min`, `Max` and `Count`.  
So far all fine.  
![image](https://user-images.githubusercontent.com/11338668/148045938-b530d795-601e-4a26-894e-b070ff177d36.png)
Now I define a Unit, and use ‘Seconds’.
The Min and Max columns are now formatted in time units, as desired.
But the Count value is now interpreted as time, and given in 'minutes`.
![image](https://user-images.githubusercontent.com/11338668/148046100-467883c8-f5eb-4536-b5a7-a6df70656418.png)

**What you expected to happen**:
That’s of course wrong, the count is always a pure number.  
It should be formatted as an integer.  
The  `Unit` setting should apply only to columns like `min`,`max`, etc.

The `Decimals` setting should also be ignored.  
Having 2 decimals for `count`, as visible in the first screenshot, doesn't make sense too.

**How to reproduce it (as minimally and precisely as possible)**:
see above, all said.

**Anything else we need to know?**:

**Environment**:
- Grafana version: V8.2.3
- Data source type & version: from .deb provided by Grafana
- OS Grafana is installed on: Debian 11
- User OS & Browser: Ubuntu 20.04 & Firefox
- Grafana plugins: build-in Time Series visualization

**Comment by dprokop** [comment]
@wfjm - thanks for opening the issue, and indeed your observations are quite valid. We cannot promise if and when this will be fixed, but if you or anyone else want to open a PR with a fix, we will be happy to provide a review and guidance!

**Comment by wfjm** [comment]
@dprokop - thanks for acknowledging this issue.

**Comment by adela-almasan** [comment]
Fixed in https://github.com/grafana/grafana/pull/49004
