### ISSUE TITLE
Question: How to Custom dashboard?

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#4366]
HI, brother?

I 'm customizing 
(using centos6.5 and latest grafana version)

I want only the picture below.

<img width="1151" alt="2016-03-15 6 04 27" src="https://cloud.githubusercontent.com/assets/13308314/13772728/fb63c012-ead8-11e5-9289-fa442cddab44.png">

<img width="1156" alt="2016-03-15 6 04 11" src="https://cloud.githubusercontent.com/assets/13308314/13772729/fe3e6a08-ead8-11e5-8f35-b9a3594c9e4f.png">

...Um.. I wanna know html class name and angularjs module.. position..

help me plz ..

Thanks!

**Comment by torkelo** [comment]
> ...Um.. I wanna know html class name and angularjs module.. position..

please be more specific. 

Btw, if you to get more readable series names, use aliasByNode graphite function
