### ISSUE TITLE
Grafana 8.3.3 Text panel javascript bug or user error?

### ISSUE THREAD

**Issue by Jonk2** [grafana/grafana#43682]
I'm a new user of grafana and one of the thing I wanted to do was display an image from a local source (RPI on the network or another NAS location).

I am using 8.3.3 installed on a RPi4 today.

In the text panel, there's the option to write HTML to show an image,
Whilst this displays an image, it does not update the image when the dashboard updates. The image is updated every 5 seconds by other software running on the PI and a separate webpage will refresh as expected.

Others have used a small javascript script to add a timestamp to the end of the image src every xxxx milliseconds, thus a new image is displayed when the dashboard refreshes.

![image](https://user-images.githubusercontent.com/77614536/148099027-a0a00617-bd0b-4b6c-8c7d-c923f920279e.png)

This doesn't appear to work for me. If I add the javascript to the text panel, using html, this code is displayed as text under the image on the dashboard.

![image](https://user-images.githubusercontent.com/77614536/148098774-f3e80f08-f7a2-4d91-9b1c-bf5139832b52.png)

I've read previously you had to disable sanitize html, which I have done in the grafana.ini file, and rebooted etc but still no joy.

Not sure what I'm doing wrong or if this is a bug?

**Comment by torkelo** [comment]
you need to disable html sanitizing (ini setting) to allow javascript in text panel

**Comment by torkelo** [comment]
https://grafana.com/docs/grafana/latest/administration/configuration/#disable_sanitize_html

**Comment by Jonk2** [comment]
My last 2 sentences:

> I've read previously you had to disable sanitize html, which I have done in the grafana.ini file, and rebooted etc but still no joy.
> 
> Not sure what I'm doing wrong or if this is a bug?

What next?

**Comment by leonsery** [comment]
Hi,
The same in version 8.4.3!!! Please fix it!

**Comment by romainlaisne** [comment]
Does it work wirh just an alert? Perhaps a CORS issue as you images is on another server?
