### ISSUE TITLE
Refactor Visualization: Identity and add missing content. 

### ISSUE THREAD

**Issue by achatterjee-grafana** [grafana/grafana#43684]
While working on https://github.com/grafana/technical-documentation/issues/169, identified that we do not discuss which type of visualization works best for a particular data type. 

Initiated discussion: https://raintank-corp.slack.com/archives/C02HM1FGWQ4/p1638544847001600 and opening this issue to track the work in an upcoming quarter.

**Comment by chri2547** [comment]
Isabel is working on this. Closing.
