### ISSUE TITLE
[Bug] Seal the timeline at the legend on the right

### ISSUE THREAD

**Issue by ilgizar** [grafana/grafana#4369]
Steps of render graph with legend:
1. render diagram on full width
![render diagram on full width](http://pasteboard.co/images/2hA3ncNJ.jpg/download)
2. render legend over the diagram
![render legend](http://pasteboard.co/images/2hAaqZiB.jpg/download)
3. resize diagram
![resize diagram](http://pasteboard.co/images/2hAdNeeW.jpg/download)

After this patch time axis will be recalculated before redraw diagram.
![after patch](http://pasteboard.co/images/2hAmofjj.jpg/download)

Especially the bug manifests snapshot. Snapshot before patch 
![snapshot before](http://pasteboard.co/images/2hAz0HUx.png/download)
and after
![snapshot after](http://pasteboard.co/images/2hAArkIf.png/download)

[patch](http://paste.ofcode.org/sabgSHLGwYDDX8jGAYaJsH)

**Comment by torkelo** [comment]
please open Pull requests instead of pasting patches :)

**Comment by torkelo** [comment]
one of you images looked strange, 
2.) render legend over the diagram 

Could you describe the scenario for how you got that?

**Comment by ilgizar** [comment]
I described the steps of drawing the graph. In fact, everything happens in a some milliseconds and we only see the resulting image: ![step3](https://camo.githubusercontent.com/d5dec86ac1559a4b30e9bf77b146cc94327cad9b/687474703a2f2f7061737465626f6172642e636f2f696d616765732f326841644e6565572e6a70672f646f776e6c6f6164)

**Comment by kolobaev** [comment]
@torkelo hi, we have the same problem, when creating images with alerts:
https://camo.githubusercontent.com/f4929ab1e8a8903e59ce16df7cf59817fdd91e8a/687474703a2f2f7061737465626f6172642e636f2f696d616765732f3268417a304855782e706e672f646f776e6c6f6164
