### ISSUE TITLE
Cannot create "Value mappings" from Infinity (∞)

### ISSUE THREAD

**Issue by justaverylee** [grafana/grafana#43690]
**What happened**:
I first performed a transformation on a table of type "Add field from calculation" with Reduce row and "Difference Percent" options selected to create a new row. The new row sometimes results in infinity ∞ when the first field is 0. This is expected. I want to replace the infinity with a value mapping, but cannot seem to find a value mapping which matches the infinity value.
**What you expected to happen**:
I would expect an option under Value Mappings which will match Infinity. I would be satisified with a new option for Infinity being added, or having NaN include infinity.
**How to reproduce it (as minimally and precisely as possible)**:
1. I use a promql datasource, so set that up or something similar
2. Create a promql panel in a dashboard and turn on table view (or change it to a table format)
3. Create a "A" series with value '0'
4. Create a "B" series with value non-zero. I choose 10
5. Go to Transform query options. Click "Add field from calculation"
6. Choose Mode Reduce row, select the 0 and nonzero (10) fields and choose calculation "Difference percent"

***Now we've created an infinity in our table. We want to transform the infinities to something else. There may be another way to do the above. **My issue is that I can't find a way to do replace infinities.** ***

What I've tried:
1. In the right panel "Show options pane" -> Overrides -> Add field override. Select "Fields with name" and choose the "Difference percent" field.
2. Select "Add override property" and select "Value mappings > Value mappings"
3. Click "Add value mappings"
4. Select any option. I feel I've tried anything that seems remotely plausible but none match infinity.
**Anything else we need to know?**:

**Environment**:
- Grafana version: Newest published to docker today: 8.1.8
- Data source type & version: promql (although could be any)
- OS Grafana is installed on: macos
- User OS & Browser: chrome/macos
- Grafana plugins: default
- Others: blank instance created with `docker run grafana/grafana:latest` to reproduce. This might be a feature request. Feel free to let me know if that's where this should go.

**Comment by ivanahuckova** [comment]
@grafana/user-essentials for me this seems like a feature request that should be turned into discussion, but leaving up to you to decide. 🙂

**Comment by ashharrison90** [comment]
hi @justaverylee 👋 

you can achieve this today by using a normal value mapping against the value `Infinity` or `-Infinity`:
![image](https://user-images.githubusercontent.com/20999846/148238011-f098433b-17c3-4d50-a917-3209dd0b627a.png)

i've created a branch to add new special matchers - we'll discuss as a team whether we think this is worth adding because i do agree that it's a little hidden

hope that helps! 😄

**Comment by ashharrison90** [comment]
decided not to add a special matcher as we're trying to keep that list as small as possible.

have added some unit tests to ensure we don't regress the current behaviour of being able to map infinite values instead. 👍

**Comment by theldg** [comment]
Thanks
