### ISSUE TITLE
Color that depending on particular threshold 

### ISSUE THREAD

**Issue by mikhailov** [grafana/grafana#437]
I'm interested is that possible to change a color for the same metric? Sometime it can be very useful to take a brief look across ten-ish graphs on big screen to detect some kind of anomaly. Say, you have green-color CPU metric (comes through collectd) with 60% as a treshold. Once it goes beyoud it becomes red. What you think?

**Comment by savingschampion** [comment]
Are you guys working on this at all? it looks like the underlying graphing tool you use can already do this natively. http://www.flotcharts.org/flot/examples/threshold/index.html

**Comment by torkelo** [comment]
@savingschampion no we are not working on it. That plugin is solving the issue in a hacking way (splitting the series into multiple series with different colors, which will cause issues with other features in grafana, like hover), but it is possible I think. 

As get further along with our work on alerting we might look at this as well. Or if this gets many +1 votes  :)

**Comment by savingschampion** [comment]
That's a shame, graph colouring based upon value is a big thing we'd like for our business alerting.

**Comment by srhopkins** [comment]
+1 very useful feature for me.

**Comment by timgriffiths** [comment]
+1 we would like to see this too

**Comment by maberle** [comment]
+1 for me

**Comment by Lahorde** [comment]
+1

**Comment by gealtrag** [comment]
+1

**Comment by meenakshi-panda** [comment]
+1

**Comment by infradom** [comment]
+1 (background color based on threshold)

**Comment by nitlev** [comment]
+1

**Comment by cattt84** [comment]
+1

**Comment by pimeys** [comment]
+1

**Comment by Tittan31** [comment]
+1 iam trying to find exactly this feature. Changing the graph color based on actual value...any progress expected? Is there any way do this? Thank you man, i love grafana :-)

**Comment by mayt** [comment]
+1

**Comment by sata** [comment]
+1

**Comment by dm-balych** [comment]
+

**Comment by lexmag** [comment]
Rather than +1 in comments it's way better to react 👍 under initial comment.
There are many people who have subscribed to this issue to get a notification when it will be closed (hopefully implemented), and those +1 only create unnecessary noise for everyone.

**Comment by artemale** [comment]
+1

We need to highlight crossing of the threshold the same way as alerting is done, but without any notification. Monitoring person shall see red flashing background ideally to attract the attention. We find this feature as very-very valuable.

Any plans to add this to grafana? Does seem to be very huge effort.

**Comment by Aleksey-Maksimov** [comment]
+1

**Comment by thuck** [comment]
@daniellee is the #1365 a duplication of this one? Looks like they have similar objectives, or maybe I'm missing something.

**Comment by artemale** [comment]
1365 is about single stat probably, while this one is for graph, but you are right, objectives are the same.

**Comment by Xaelias** [comment]
I understand it's probably not obvious to make happen. But it's been 3 years and a half :-/

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by Melhorio** [comment]
+1  I work with equipment related issues utilizing Grafana for equipment variable trending (temperatures, pressures, current, power etc.) . I have to agree that this feature would help to pin point equipment issues. Also selecting the trend line color on normal area s grayish, warning area to dark yellow and on alarm area as bright red or orange (as an example) can make the trends pop out highlighting the problem areas fast in the case where there are tens of trends on the dashboards at any given time.

**Comment by arensp** [comment]
+1

**Comment by helinmik** [comment]
+1

**Comment by dprokop** [comment]
Think this should be now possible with https://github.com/grafana/grafana/pull/35910 in Grafana 8.1.
