### ISSUE TITLE
[Feature Request] Negative values of Y-axis speed (bps)

### ISSUE THREAD

**Issue by ilgizar** [grafana/grafana#4370]
I suggest a new feature: the display mode of the values on the Y axis (raw or absolute). It looks better for the network speed.

raw (default mode)
![raw](http://pasteboard.co/images/2hDwq3yb.jpg/download)
absolute
![abs](http://pasteboard.co/images/2hDzWvwO.jpg/download)

[patch](http://paste.ofcode.org/uypY9Vi4m7iUH23S6RiPkf)

**Comment by ilgizar** [comment]
open pull request #4408

**Comment by krobertson** [comment]
Should this be re-opened if the PR was closed? Was another feature request filed?
