### ISSUE TITLE
Question: How can I display strings

### ISSUE THREAD

**Issue by xpinkyx** [grafana/grafana#4372]
I read in the docs that it's possible to display strings in singlestat panel in version 2.1. I'm using the nightly build from 14th march right now, is it still possible in this version to display strings in single stat or any other panel and if yes, how? My datasource is elasticsearch and I don't get the possibility to choose my string-field in metrics menu.

**Comment by torkelo** [comment]
elasticsearch does not support string values in metric aggregations, so currently it is not possible. 

You can use Raw Document mode, but singlestat panel does not support that that mode

**Comment by Turing-Chu** [comment]
how can I show values with a string attribute in graph mode?
![image](https://user-images.githubusercontent.com/13805470/34463895-cf85154a-eea5-11e7-95a3-ebcd8e5896b8.png)
