### ISSUE TITLE
Alert List Panel to display flat list of alert instances

### ISSUE THREAD

**Issue by yuri-tceretian** [grafana/grafana#43732]
One of typical use-cases is when users create alert many rules that watch for different metrics of the same entity. For example, a truck that has oil, fuel, millage sensors. New Grafana alerting encourage users to group by metric rather than by monitored entity. 
Therefore, the alert instances can have the same set of labels that uniquely describe a single object.
In Alert List Panel those instances look like below
<img width="470" alt="firefox_sZVqmi9nw8" src="https://user-images.githubusercontent.com/25988953/148281541-3067e44a-0b08-45a6-8a7f-392a6183d6d5.png">

i.e. the panel displays nested list of alert rules with filtered instances. It would be great to have ability to flatten the list and just display alert instances.
<img width="470" alt="firefox_sZVqmi9nw8" src="https://user-images.githubusercontent.com/25988953/148283870-6000aa75-7e46-4cfe-a723-56bf989328af.png">

**Comment by gillesdemey** [comment]
Introduce a new view mode that only shows alert instances
