### ISSUE TITLE
[Bug] New luceneEscape method causing issues with ElasticSearch Query

### ISSUE THREAD

**Issue by smur89** [grafana/grafana#4373]
* What grafana version are you using?
Master branch
* What datasource are you using?
ElasticSearch
* What OS are you running grafana on?
Windows 10

In the latest version of master which I've just merged into my branch, my dashboard queries are no longer producing the correct results. Seems to be in escaping the lucene string characters in the templateSrv.js file.

The latest build has changed my lucene string from:

```
"query": "(publisher:vice.com OR publisher:eonline.com OR publisher:upworthy.com OR publisher:mic.com OR publisher:popsugar.com OR publisher:mashable.com OR publisher:ew.com OR publisher:vox.com OR publisher:complex.com OR publisher:uproxx.com OR publisher:vulture.com OR publisher:refinery29.com OR publisher:buzzfeed.com OR publisher:billboard.com OR publisher:cosmopolitan.com OR publisher:bustle.com OR publisher:fusion.net OR publisher:hellogiggles.com OR publisher:mtv.com) AND language:en AND _missing_:fbPostType AND _missing_:rdPostKind AND -_missing_​:sources"
```

To:
```
"query": "(publisher\\:vice.com\\ OR\\ publisher\\:eonline.com\\ OR\\ publisher\\:upworthy.com\\ OR\\ publisher\\:mic.com\\ OR\\ publisher\\:popsugar.com\\ OR\\ publisher\\:mashable.com\\ OR\\ publisher\\:ew.com\\ OR\\ publisher\\:vox.com\\ OR\\ publisher\\:complex.com\\ OR\\ publisher\\:uproxx.com\\ OR\\ publisher\\:vulture.com\\ OR\\ publisher\\:refinery29.com\\ OR\\ publisher\\:buzzfeed.com\\ OR\\ publisher\\:billboard.com\\ OR\\ publisher\\:cosmopolitan.com\\ OR\\ publisher\\:bustle.com\\ OR\\ publisher\\:fusion.net\\ OR\\ publisher\\:hellogiggles.com\\ OR\\ publisher\\:mtv.com) AND language\\:en\\ AND\\ _missing_\\:fbPostType\\ AND\\ _missing_\\:rdPostKind\\ AND\\ \\-_missing_​\\:sources"
```

Which returns the wrong value.

**Comment by torkelo** [comment]
can you show me your query variable definition and query editor settings?

Also you might be able to fix it by going into the template variable edit tab and hit update (the all value must update as it is stored differently in 3.0)

**Comment by smur89** [comment]
I have been working on a previous version of 3.0, cloned about a month ago. I tried your suggestion regardless however, and it didn't work.

Template variables:
![capture](https://cloud.githubusercontent.com/assets/2413634/13785904/577c2940-eacd-11e5-9f63-cbd22d9ed9c5.PNG)

![capture3](https://cloud.githubusercontent.com/assets/2413634/13785906/5a3ee474-eacd-11e5-9026-e548e5e424c2.PNG)

Query editor (I have some changes here over stock 3.0):
![capture2](https://cloud.githubusercontent.com/assets/2413634/13785919/6f84cfd8-eacd-11e5-9889-d0bbe4aa7514.PNG)

**Comment by smur89** [comment]
You can see I'm really just using the templating to store long variables to reuse in queries. When I switch the query to avoid templating, and just use the string equivalent, the correct value is returned.

![capture](https://cloud.githubusercontent.com/assets/2413634/13786429/6ee7caf6-eacf-11e5-88df-918f63eb210c.PNG)

**Comment by torkelo** [comment]
you could comma seperate your values and enable All value, 

but long term to fix your scenario where  you have lucene syntax in a variable, we need a way in grafana to disable lucene escaping

**Comment by smur89** [comment]
Thanks for the suggestion, for now I've just reverted to 

```JAVASCRIPT
return '(' + _.pluck(variable.options, 'text').join(' OR ') + ')';
```

and will revisit later.
