### ISSUE TITLE
No user feedback if a message/contact point template fails to evaluate

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#43733]
**What happened**:

When creating a message template (or a contact point with a templat-able field), it's easy for the user to to produce a template that fails to evaluate. If a bad template is entered, there is no user feedback. Messages (and test notifications) are successfully sent with no indicator, but the content ends up behaving strangely. There are a couple cases here:

1. Syntactically invalid template

If the provided template is not a valid Go template at all, the resulting message is completely empty.

Template:
```
I'm a custom message! Alerts firing: {{ len .Alerts.Firing }}
{{ .NoCloseBrackets
```

Sent message:
```
```

2. Valid template with invalid fields

If the provided template is parseable but references invalid fields, the resulting message gets truncated after the first failure.

Template:
```
I'm a custom message! Alerts firing: {{ len .Alerts.Firing }}
{{ .NotAField }} foo bar
```

Sent message:
```
I'm a custom message! Alerts firing: 1 
```

Currently, we log this event at Warn level.

**What you expected to happen**:

We should consider providing some form of user feedback, so that users have an easier time of writing templates. It's often very difficult to write and test complex templates, since it's not obvious _what_ exactly failed without log access. It's also often difficult to distinguish between a truncated template and an empty field.

In the event of a "real" notification, it's difficult to provide any sort of feedback aside from logs since notifications are synchronously issued as a result of alerts. However, the "Test Notification" button is specifically designed to troubleshoot message content, and is more synchronous. One solution would be to have the `POST /api/v1/receivers/test` include any templating errors in its response body, and displayed as a warning in the UI.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a contact point which supports a customizable message. (Email, googlechat, etc)
2. Enter one of the invalid templates above
3. Hit Test Notification. No error appears.
4. Observe the affected message.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: N/A
- OS Grafana is installed on: Linux
- User OS & Browser: Linux, Firefox 95.0.2
- Grafana plugins: N/A
- Others: ngalerting enabled

**Comment by gerobinson** [comment]
Now that Grafana supports contact point testing, including testing templates, I think we should start to think about returning an error (or even creating a separate alert) instead of sending blank messages for when a template fails to evaluate. Perhaps we can have a discussion about this later in the week or next week?

**Comment by devinrcheevers** [comment]
hi, new pm on alerts joining the party. It's captured in the thread above but I wanted to make sure it wasn't lost.

It seems like we have a couple different potential acceptance criteria's here:  

**User feedback**
 * Warn user when a template that fails to evaluate is entered. This feels like nice easy quick win that isn't debatable 
 * If template fail to evaluate what do we send as an alert?

**Comment by devinrcheevers** [comment]
I'll differ to y'all on implementation choice re: what we send as message due to template error. Just want to make sure we aren't coupling the two tasks. So I'd really like us to ship the user feedback asap and pick an incremental but reasonable approach for the message 'fallback' if the template fails to render.

If I'm missing something please let me know, excited to work with y'all on many more bugs.

**Comment by JacobsonMT** [comment]
The proposed solution should work well for basic text sections (message, title, ...). It should be noted though that if templating fails for a notifier option that is required to deliver the message, recovering will be unlikely. There aren't that many examples of this, but they do exist. 

For example, discord templates the webhook url and kafka templates the topic.

Letting the user know about these errors will need to be done external to the alert in question (a separate alert, logs, UI notifications, ...) and we should probably give thought to whether we should template these required fields at all unless absolutely necessary (e.g. in the case of future webhooks?).
