### ISSUE TITLE
Can't set the graphTooltip property through the POST dashboard API call

### ISSUE THREAD

**Issue by Zjaaspoer** [grafana/grafana#43730]
**What happened**
When I create a dashboard through the API, and set graphTooltip to 2, it defaults to value 0 after creation

**What you expected to happen**:
I expect the set value (2) to persist.

**How to reproduce it (as minimally and precisely as possible)**:
Do a POST to dashboards/db with a minimal Dasboard JSON:
```
{
  "dashboard": {
    "graphTooltip": 2,
    "panels": [],
    "title": "debug"
  }
}
```
If I do an immediate GET using the API I get
```
{
  "dashboard": {
    "graphTooltip": 2,
    "panels": [],
    "title": "debug"
  }
}
```
but when I go to the UI the tooltip functionality is set to default (so graphTooltip = 0) and if I inspect the JSON through the UI the graphTooltip is indeed set to 0 again.

**Anything else we need to know?**:
When I set the property through the UI and read the same dashboard via the API the property graphTooltip is set to 2

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: n/a
- OS Grafana is installed on: Docker
- User OS & Browser: n/a
- Grafana plugins: none
- Others:

**Comment by ivanahuckova** [comment]
@Zjaaspoer Thank you for creating this issue. I was able to reproduce this as well.

**Comment by torkelo** [comment]
your dashboard json is missing a schemaVersion, set this to something higher than 14 as before that graphTooltip was named sharedCrosshair

**Comment by Zjaaspoer** [comment]
That did the trick, thank you!
