### ISSUE TITLE
[Bug] There is no button to add new organization in the latest version

### ISSUE THREAD

**Issue by dengliu** [grafana/grafana#4375]
![screen shot 2016-03-15 at 12 51 53 pm](https://cloud.githubusercontent.com/assets/5108773/13792016/09e4c554-eaad-11e5-80ae-327c3938dbaf.png)
* What grafana version are you using?
commit 0b3ccaff27ac6b34b79d0cac7338c418b758b669
Merge: 82eb32a e905c2c
Author: Carl Bergquist <carl.bergquist@gmail.com>
Date:   Tue Mar 15 10:07:08 2016 +0100

    Merge pull request #4361 from bergquist/remove_staticRoot
    
    plugin.json: remove staticRoot field

* What datasource are you using?
InfluxDB
* What OS are you running grafana on?

Ubuntu 14

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/13805438/10b698d2-eb55-11e5-80dc-381cccf5136a.png)
