### ISSUE TITLE
[Bug] Nested templates causes multiple searches unnecessarily

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4376]
Grafana 2.6 with Graphite

If using templates where a node in the metric path is a $variable from a previous template item I observed that Grafana does 2 ?query http calls to Graphite.

In a dashboard with 1 template item you get 1 search.
In a dashboard with 2 template items that are dependent you get 3 searches.
In a dashboard with 3 template items that are dependent you get 5 searches.
etc.

To reproduce load the attached dashboard and then use Chrome inspect.

[template-bug.zip](https://github.com/grafana/grafana/files/174816/template-bug.zip)

**Comment by torkelo** [comment]
this is fixed in master (upcoming Grafana 3.0)
