### ISSUE TITLE
How to purge template list items for sharing dashboards

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4377]
Grafana 2.6 with Graphite

If using templates with a query, and you hit save, that list gets saved in the JSON dashboard options (dashboard -> templating -> list -> options).  If you export the dashboard those specific items are still in there.  I am looking for the best way to remove those items.  Initially I was just removing the entire options section of each template item which works fine on a fresh page load (if template items are set to always refresh).  But, in this same situation I discovered that if you load a URL with parameters (like &var-Group=PRD) then you just get a black page and no panels or template dropdowns to pick from.  I then tried populating it with the snippet with the code if your have no items in your datasource ({ "text" => "None", "value" => "", "isNone" => 'true', "selected" => 'true'}).  That works better, if you pass a URL with parameters it does populate and the panels load correctly, but if you click on the 1st of multiple template items you get an empty list, and it sort of hangs, you can't click it away.  Clicking the 2nd or greater and it works correctly. Checking with Chrome inspect I see that on  a query is done for the 2nd template item but not the 1st one.  All of this can be avoided if after importing the dashboard you save it once, so that some local items are found in the options list.  Problem is I can't mandate that people do that.
So my question is, what is the best way to remove the list of options from a query based template list?  Is there a bug here or have I just not figured out the correct way to do it?

I also opened https://github.com/grafana/grafana/issues/4376 a moment ago for something else I noticed while inspecting which could perhaps be related.

**Comment by torkelo** [comment]
There is no way to remove the options beside changing the template variables.

**Comment by torkelo** [comment]
there has been some fixes for initializing inter dependent template variables from URL in mater (upcoming grafana 3.0)
