### ISSUE TITLE
TLS certificates for PostgreSQL connection access denied

### ISSUE THREAD

**Issue by dontsovcmc** [grafana/grafana#43774]
**What happened**:
If I choose PostgreSQL Connection - TLS/SSL Method: File system path" I got error "Metric request error"

Grafana log sad, that permission denied, but "-rw-r--r-":
```
t=2022-01-06T21:33:34+0100 lvl=eror msg="Metric request error" logger=context userId=1 orgId=1 uname=admin error="failed to query data: stat /home/username/postgresql_certs_prod/root.crt: permission denied" remote_addr=127.0.0.1

username@ubuntu-2gb-hel1-5:~/postgresql_certs_prod$ ls -l
total 16
-rw-r--r-- 1 username username 639 Jan  6 20:42 postgresql.crt
-rw-r--r-- 1 username username 891 Jan  6 20:43 postgresql.key
-rw-r--r-- 1 username username 636 Jan  6 20:44 postgresql.key.der
-rw-r--r-- 1 username username 769 Jan  6 20:43 root.crt
```

**What you expected to happen**:
Success connection or some humanreadable error.
I check connection by DBeaver - it works.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create user "grafana"

create user grafana with encrypted password 'ххх';
GRANT SELECT ON ALL TABLES IN SCHEMA public TO grafana;

2. Generate server key. CN - server domain (not ip!).

openssl genrsa -des3 -out server.key 1024
openssl rsa -in server.key -out server.key
sudo chown postgres:postgres server.key
sudo chown 0600 server.key
sudo openssl req -new -key server.key -days 3650 -out server.crt -x509 -subj "/CN=your_domain.com" -addext "subjectAltName = DNS:your_domain.com"
sudo cp server.crt root.crt
sudo chown postgres:postgres server.crt
sudo chown 0600 server.crt
sudo chown postgres:postgres root.crt
sudo chown 0600 root.crt
sudo cp ./root.crt /var/lib/pgsql/data/root.crt
sudo cp ./server.crt /var/lib/pgsql/data/server.crt
sudo cp ./server.key /var/lib/pgsql/data/server.key

3. make changes in postgresql configuration:
sudo nano /etc/postgresql/10/main/postgresql.conf
ssl = on
ssl_ciphers = 'HIGH:MEDIUM:+3DES:!aNULL' # allowed SSL ciphers
ssl_prefer_server_ciphers = on
ssl_cert_file = '/var/lib/pgsql/data/server.crt'
ssl_key_file = '/var/lib/pgsql/data/server.key'
ssl_ca_file = '/var/lib/pgsql/data/root.crt'

4. change table access file:
sudo nano /etc/postgresql/10/main/pg_hba.conf

hostssl waterius        grafana         0.0.0.0/0               cert clientcert=1

5. restart server
sudo systemctl restart posgresql

check log:
sudo cat /var/log/postgresql/postgresql-10-main.log
sudo systemctl restart postgresql

6. Generate client keys:  CN - db username!

openssl genrsa -des3 -out postgresql.key 1024
openssl rsa -in postgresql.key -out postgresql.key
openssl req -new -key postgresql.key -out postgresql.csr -subj "/CN=grafana"
sudo openssl x509 -req -in postgresql.csr -CA root.crt -CAkey server.key -out postgresql.crt -CAcreateserial
openssl pkcs8 -topk8 -inform PEM -in postgresql.key -outform DER -nocrypt -out postgresql.key.der

7. Console checkup:
PGSSLMODE=verify-full PGSSLROOTCERT=root.crt PGSSLCERT=postgresql.crt PGSSLKEY=postgresql.key psql -h dev.waterius.ru -p 1432 -U grafana -d waterius

**Anything else we need to know?**:
There is pure manual about terrible SSL setup. There are a lot of formats, settings while generating keys. It will be good if you add some article about setup. Thanks a lot!

**Environment**:
- Grafana version: v8.3.3 (30bb7a93ca)
- Data source type & version: PostgreSQL 10
- OS Grafana is installed on: ubuntu
- User OS & Browser: chrome, macos

**Comment by dontsovcmc** [comment]
I change issue name, cause I solve Connection by using "Certificate content" and found solution for error: "db query error: x509: certificate relies on legacy Common Name field, use SANs instead"
Solution is using domain with subjectAltName not ip address here: 
`sudo openssl req -new -key server.key -days 3650 -out server.crt -x509 -subj "/CN=your_domain.com -addext "subjectAltName = DNS:your_domain.com""`

**Comment by ivanahuckova** [comment]
I am glad you were able to solve the issue! 🎉

**Comment by dontsovcmc** [comment]
> I am glad you were able to solve the issue and thank you for sharing the solution! 🎉 🧡

I solved another problem. Access denied for CA certificate not solved. If I choose PostgreSQL Connection - TLS/SSL Method: "File system path" I got error "Metric request error"
Grafana log sad, that permission denied, but file is "-rw-r--r-"

**Comment by dontsovcmc** [comment]
I upgrade ubuntu from 18.04 to 20.04 and got error postgresql start "FATAL:  could not load server certificate file "/var/lib/pgsql/data/server.crt": ee key too small"
Reason: The problem is that the latest versions of openssl now considers keys with a bit length of 1024 to be insecure.

Solve:  change 1024 to 2048 in genrsa command
