### ISSUE TITLE
The TestData DB lost

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#43771]
**What happened**: I can't found the `TestData DB` in datasource menu.

**Environment**:
- Grafana version: v8.3.2
- Data source type & version: `TestData DB`
- OS Grafana is installed on: CentOS

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/2911588/148431802-3c83e011-db06-4ac6-b209-e8f14986c6e5.png)

**Comment by torkelo** [comment]
Unable to replicate this with a 8.3.2 docker image 
![Screenshot from 2022-01-07 10-43-54](https://user-images.githubusercontent.com/10999/148525003-c80c9a13-b799-4ef5-ad8e-17e7c192f24c.png)

**Comment by ivanahuckova** [comment]
@sanchomuzax I am not able to reproduce this issue. Could you please open console and see if there are any errors. Also could you try to go to `http://your_grafana_instance/plugins/testdata` to see if you can see it there?

**Comment by sanchomuzax** [comment]
Thank you, working, sloved.
![image](https://user-images.githubusercontent.com/2911588/148550619-db59731d-e135-44f9-8c74-0ecad5199bd6.png)
