### ISSUE TITLE
Docs feedback: /developers/plugins/add-query-editor-help.md

### ISSUE THREAD

**Issue by ml054** [grafana/grafana#43790]
no longer available in grafana 8?

![image](https://user-images.githubusercontent.com/1250431/148524743-aea522d1-9b9a-454a-8d0f-9dd7ddd6f276.png)

**Comment by ivanahuckova** [comment]
@ml054 Can you please elaborate. `setQueryEditorHelp` is still available in Grafana 8 https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L80

**Comment by ml054** [comment]
@ivanahuckova you are absolutely right. `grafana/data` latest was resolved to 7.3.4.
