### ISSUE TITLE
Changing variable datasource away from Azure Monitor crashes the page

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#43803]
I think this issue is not specific to Azure Monitor, but it's where I noticed it and triggers it in a very reliable way.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new variable "Query" on a dashboard 
2. Select the Azure Monitor datasource. You do not need to fill out a query, just select Azure Monitor as the datasource.
3. Change the datasource to Prometheus
4. The page crashes with "An unexpected error happened" and a "TypeError: datasource.getVariables is not a function" exception.

**Anything else we need to know?**:

While the exception happens from within the Azure Monitor datasource, it appears the problem is higher up in the stack in core Grafana as it looks like the Azure Monitor datasource is being incorrectly passed the Prometheus datasource when switching. Eek!

**Environment**:
- Grafana version: latest main - 36e4a871f2

**Comment by hugohaggmark** [comment]
Great catch, I think this line https://github.com/grafana/grafana/blob/3ca3b7f4329c76a5fdb07af428fd741a26638b76/public/app/features/variables/query/actions.ts#L75 changes the data source before the editor has changed.

One way to solve this, will cause flicker though, would be to force an unload of the previous variable editor if the data source type is different.
```ts
if (previousDatasource && previousDatasource.type !== dataSource?.type) {
  dispatch(changeVariableEditorExtended({ propName: 'VariableQueryEditor', propValue: StandardVariableQueryEditor }));
  dispatch(changeVariableProp(toVariablePayload(identifier, { propName: 'query', propValue: '' })));
} 
```
