### ISSUE TITLE
FreeIPA and Grafana

### ISSUE THREAD

**Issue by MCMarcel90** [grafana/grafana#43833]
Hi,

i try to connect FreeIPA  with Grafana (v8.3.3 in a Docker).
I am fresh in FreeIPA and Access controlling.

By loggin in i get following event in the Log:

`t=2022-01-09T16:01:35+0100 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=302 remote_addr=162.158.90.88 time_ms=0 size=29 referer=https://myauthentification/`

I can get data if i am logged in in the Security/LDAP menu, i can search for a username which i created in FreeIPA, i can see names, Emails, if it is a Grafana Admin, Status is active and i have done some groups for Viewer, editor and Admin and all shows correctly.

my ldap.toml looks like this:
```
[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "ip.of.freeipserver"
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if LDAP server should use an encrypted TLS connection (either with STARTTLS or LDAPS)
use_ssl = false
# If set to true, use LDAP with STARTTLS instead of LDAPS
start_tls = false
# set to true if you want to skip SSL cert validation
ssl_skip_verify = true


# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
bind_dn = "uid=admin,cn=users,cn=accounts,dc=myipa,dc=server"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = 'averystrongpassword'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
# Allow login from email or username, example "(|(sAMAccountName=%s)(userPrincipalName=%s))"
search_filter = "(uid=%s)"

# An array of base dns to search through
search_base_dns = ["cn=accounts,dc=myipa,dc=server"]

# group_search_filter = "(cn=grafana_admin,cn=groups)"
# group_search_filter_user_attribute = "distinguishedName"
# group_search_base_dns = ["cn=groups,cn=accounts,dc=myipa,dc=server"]

# Specify names of the LDAP attributes your LDAP uses
[servers.attributes]
surname = "sn"
name = "givenName"
username = "mail"
member_of = "memberOf"
email =  "mail"

[[servers.group_mappings]]
group_dn = "cn=grafana_admin,cn=groups,cn=accounts,dc=myipa,dc=server"
org_role = "Admin"
grafana_admin = true

[[servers.group_mappings]]
group_dn = "cn=grafana_editor,cn=groups,cn=accounts,dc=myipa,dc=server"
org_role = "Editor"

[[servers.group_mappings]]
group_dn = "cn=grafana_viewer,cn=groups,cn=accounts,dc=myipa,dc=server"
org_role = "Viewer"
```

and my Grafana.ini looks like this:

```
[auth.ldap]
enabled = true
config_file = /etc/grafana/ldap.toml
allow_sign_up = true
```

if i go to my Grafana board, it redirects me to Authelia where i have to login, after loggin in it shows me the login of Grafana, which under my knowledge shouldn't be? If a user is logged in which is in the FreeIPA it should log in if the user is known, or if the user is unknown grafana should do a new user?

Maybe someone can help me get it work.. 

Thank you

Greetings

**Comment by marefr** [comment]
We do have this docker-compose setup for freeipa, but we haven't touched it since 2019 so cannot guarantee it still works. Please have a look/try it out/compare with your config. In general would suggest enable debug logging `GF_LOG_LEVEL=debug` to get more details logged and check the Grafana docker container logs.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
