### ISSUE TITLE
Timeout option in snapshot API?

### ISSUE THREAD

**Issue by radimkohout** [grafana/grafana#43830]
**What happened**:
Snapshot API doesn't have any timeout.
**What you expected to happen**:
It should have timeout.
**How to reproduce it (as minimally and precisely as possible)**:
Try create snapshot of dashboard, that takes longer to load.
**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.3
- Data source type & version: 10.5.12-MariaDB-1 
- OS Grafana is installed on: Debian 11
- User OS & Browser: None
- Grafana plugins: Doesn't matter
- Others:

**Comment by marefr** [comment]
Specifying a timeout is supported since long time ago, see https://grafana.com/docs/grafana/latest/sharing/share-dashboard/#publish-a-snapshot

**Comment by radimkohout** [comment]
@marefr No, it isn't. I don't mean specifying timeout in manually exported dashboards. I need to specify a timeout in the Snapshot API, so I don't get errors like this:
![image](https://user-images.githubusercontent.com/22203368/149932287-f195107c-467b-43cd-a818-1b0d41da9e14.png)

(Note when I am logged in, it loads the data afterwards, and the anonymous access is on)

**Comment by marefr** [comment]
Sorry, I don't understand what you mean. Is the screenshot of a "live"-rendered dashboard or is it a snapshot? Are you using the HTTP API to create a snapshot?

**Comment by radimkohout** [comment]
It is snapshot, created by HTTP API.

**Comment by marefr** [comment]
Please read the [Dashboard Snapshot HTTP API documentation](https://grafana.com/docs/grafana/latest/http_api/snapshot/#create-new-snapshot). 

> Note: When creating a snapshot using the API, you have to provide the full dashboard payload including the snapshot data. This endpoint is designed for the Grafana UI.

So would you go ahead with providing the full dashboard payload including the snapshot data it's up to you handling the timeout. Another way of automating this might be to use a headless browser.

**Comment by radimkohout** [comment]
How can I get that data dynamically?

**Comment by marefr** [comment]
The easiest way would be to use a headless browser using something like https://github.com/puppeteer/puppeteer and script it so that it visits a dashboard and creates a snapshot via the UI. Doing it solely thru the API is very tricky - for further help on the topic I suggest our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

**Comment by jtperez2** [comment]
@radimkohout how did you get it finally???

**Comment by kardoka** [comment]
> The easiest way would be to use a headless browser using something like https://github.com/puppeteer/puppeteer and script it so that it visits a dashboard and creates a snapshot via the UI. Doing it solely thru the API is very tricky - for further help on the topic I suggest our [community site](https://community.grafana.com/). Github are mainly for feature requests and bug reports.

The issue with such a approach is that snapshots created through the web UI will have different snapshots keys on each creation. Would it be possible to add either or both of these features?

1. Set a default snapshot timeout in the config file or somewhere in the settings
2. In the snapshot generation modal windows, optionally check to enter custom snapshot key (kind of how you can specify a key in the HTTP API when creating a snapshot).
