### ISSUE TITLE
regression in 8.3.3: re-draw of all repeated panels at every poll interval

### ISSUE THREAD

**Issue by bijwaard** [grafana/grafana#43843]
**What happened**:
After upgrading from grafana 8.3.2 to 8.3.3, the repeated panels are re-painted every poll interval in both firefox and chromium. This is illustrated with the repeated SVG panel below with two screenshots taken in succession. The SVG plugin seems to be completely reloaded and looses its internal state (e.g. zoom-level of phasor magnitude)

![image](https://user-images.githubusercontent.com/6523124/148739800-666a1634-2991-496e-900f-204cc6161c55.png)
![image](https://user-images.githubusercontent.com/6523124/148739815-daa24edf-06df-46d4-b743-e30b2c426117.png)

**What you expected to happen**:
I expected the same behavior as in 8.3.2 where the panels are not redrawn but just refreshed with updated metric values. This is illustrated with the same repeated SVG panel in grafana 8.3.2.
![image](https://user-images.githubusercontent.com/6523124/148739899-f9309618-0e4a-4101-8442-19e3bbb3a2f5.png)

**How to reproduce it (as minimally and precisely as possible)**:

* create at least two datasources
* create a template variable that can multi-select the datasources
* repeat a (SVG) panel for a multi-select datasource
* set auto-refresh to e.g. 5 seconds

**Anything else we need to know?**:
Might be related to #42828.
My SVG panel configuration:
![image](https://user-images.githubusercontent.com/6523124/148741862-fb92fa93-6c6b-4be0-8e6a-98a6346051ff.png)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: simpod-json-datasource @ 0.3.0
- OS Grafana is installed on: Ubuntu 20.04.3 LTS
- User OS & Browser: 
  - Ubuntu 20.04.3 LTS,  
  - firefox 95.0.1+build2-0ubuntu0.20.04.1, 
  - chromium-browser 1:85.0.4183.83-0ubuntu0.20.04.2
- Grafana plugins: 
  - alexandra-trackmap-panel @ 2.3.0, 
  - agenty-flowcharting-panel @ 1.0.0a,  
  - marcuscalidus-svg-panel @ 0.3.4, 
  - natel-plotly-panel @ 0.0.7
- Others:

**Comment by ashharrison90** [comment]
@bijwaard thanks for raising this! it does indeed sound very similar to #42828. the fix will be released in 8.3.4.

is there any chance you could test the latest docker build to see if that fixes the problem. you can get this with `docker pull grafana/grafana:main`

**Comment by bijwaard** [comment]
Hi Ashley,
Thanks for looking into this. I just managed to install docker with the main branch, and can confirm it is no longer repainting all repeated panels, thanks!
I compared to 8.3.3 using docker image grafana/grafana:latest where the issue is still there.

Kind regards,
Dennis

**Comment by ashharrison90** [comment]
perfect, thanks so much @bijwaard 👍 

i'll mark this as a duplicate and the fix will be released in 8.3.4 sometime soon™️ 😄
