### ISSUE TITLE
Remove Prometheus direct/browser access mode

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#43859]
Why?

- Very high maintenance burden to have multiple implementations in frontend and backend
- Very confusing for end user that graph panel render based on frontend implementation and alerting evaluates data based on backend implementation
- To be able to use alerting there's no support for direct/browser access mode
- Supporting both frontend and backend slows down the development of adding new features to datasource

Would appreciate feedback for those using direct/browser access mode and why they're needing that.

**Comment by acukan** [comment]
Hi we are using browser access mode for deploying all accessible one grafana and if user has access the data source use with it. 

for use it is fundamental future and it would be great for us if grafana continue to support it.

**Comment by kinghuang** [comment]
I'm noticing on Grafana Cloud that my Prometheus datasource with direct/browser access no longer makes queries through the browser, and thus failing to work. Has this removal already occurred?

We use direct access for some Prometheus backends that are not accessible through public routes. Users connect to VPN, and then can access the datasource with direct access.

**Comment by aocenas** [comment]
So it did not happen yet but will happen in near future with a high probability. Direct access is deprecated for quite a long time and as mentioned being able to support both direct access and backend access (which is required for alerting for example) has big maintenance costs for us.

**Comment by evandandrea** [comment]
- Beto could potentially pick this up, potentially in parallel to Prom, or provide support. During investigations of Influx variant of this task, sees some overlap with Prom.
- Agreement with the squad that Beto will pick this up. Do feel free to ask old team members for support as needed.
- Beto to add docs to the knowledge transfer doc.

**Comment by bpinske** [comment]
This change is quite bad for my org.

My org supports many 'airgapped' environments where due to compliance concerns we must not have direct connection between the environment networks. The browser proxy mode was great for us to have a single pane of glass monitoring where we would simply proxy traffic through our browser to the different datasources.

This is not possible with the server access model.
