### ISSUE TITLE
[Bug] OpenTSDB Annotations. Can't leave metric query field empty

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4387]
If one want's to show only global annotations, it's necessary to fill in a dummy metric there. Also, this requirement is not stated anywhere (not even in the error message you get if you leave the field empty)

**Comment by torkelo** [comment]
?

**Comment by vitorboschi** [comment]
In OpenTSDB there's the concept of global annotation, which are not attached to any particular metric. There's a checkbox in Grafana to select global annotations, as the screenshot below shows:

![image](https://cloud.githubusercontent.com/assets/71193/13813228/2cfa59fc-eb5f-11e5-891f-bda459897c6a.png)

If I just want the global annotations, I shouldn't need to fill the query

**Comment by torkelo** [comment]
aha, now I understand

**Comment by utkarshcmu** [comment]
@vitorboschi This looks like a annotations issue and not templating issue.
