### ISSUE TITLE
[Bug] withCredentials doesn't set when adding datasource

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#4389]
When I add new Prometheus datasource with "withCredentials = true", the setting doesn't store Grafana sqlite database.

- version: https://github.com/grafana/grafana/commit/fd531e84fc6175730ae67a8950fe2455d287e8cf
* datasource: Prometheus
* OS: Mac OS X 10.10.5

**Comment by torkelo** [comment]
works here. the access mode must use direct access though

**Comment by torkelo** [comment]
sorry, re-read the issue and now understand what you mean :)

**Comment by torkelo** [comment]
fixed!

**Comment by mtanda** [comment]
Thanks!
