### ISSUE TITLE
Cannot hide series when they have the same name

### ISSUE THREAD

**Issue by RutgerKe** [grafana/grafana#43909]
**What happened**:
I tried to hide a query while in explore, nothing happened.

Why I want this: while simplifying a complex query I wanted to get the exact same result for two queries. The two queries are shown with the same labelset, and when they are different I see both lines drawn seperately, but when they are the same I cannot hide one to check if the other is actually there (or I made a mistake and it returns only part of the data).

**What you expected to happen**:
Click in the legend, hide a series.

**How to reproduce it (as minimally and precisely as possible)**:
Use the prometheus datasource, fill in two times the value '1'.
![image](https://user-images.githubusercontent.com/6214906/148967303-c0bc106f-e6ee-497c-a3fb-4f5c4f2f044d.png)
I can click the number, but it will not hide.

[Another example on play.grafana.com](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:false,%22range%22:true,%22exemplar%22:true,%22expr%22:%221%22%7D,%7B%22refId%22:%22B%22,%22instant%22:false,%22range%22:true,%22exemplar%22:true,%22expr%22:%221%22%7D%5D)

**Anything else we need to know?**:
I check both grafana 8.3.3 and 7.3.0 and they both have the issue. Not sure if it ever worked. It does work for series with different names / labelsets.

**Environment**:
- Grafana version: 8.3.3 and 7.3.0
- Data source type & version: prometheus
- OS Grafana is installed on: ubuntu (and grafana cloud)
- User OS & Browser: Firefox
- Grafana plugins: None
- Others: None

**Comment by dprokop** [comment]
This does not feel like an issue with the time series itself, but rather how Prometheus data source handles naming the resulting series. Having two exact same queries will result in field names configured via `DisplayNameFromDS` with exact same values. 

I suggest using legend format for the other query to make the field naming unique. But @grafana/observability-squad  may have some other suggestions on how to solve that.

**Comment by aocenas** [comment]
Don't think there is much, I assume this can happen with any data source or combination of data sources so better to make the names non-ambiguous.

At the same time @dprokop does it make sense to use the series name as a unique identifier for things like how the legend works? Maybe something like query_id/ref_id + name would be better?

**Comment by ivanahuckova** [comment]
I don't think this is a Prometheus issue. Any data source can return results with the same name - e.g. when you run same query. Here we have both `lat` visible even though I clicked just on one. Also Explore doesn't have `legend` field for Prometheus. 
![image](https://user-images.githubusercontent.com/30407135/149749441-a2575710-e96f-4d94-ba06-87eabdc58f87.png)

So one way to change this would be add a legend field to Explore query editor. The other would be to change the way we hide/show series and instead of name use other key (some unique id?) to select specific series.

**Comment by RutgerKe** [comment]
I don't think this should be closed? The panel does happily draw two lines and gives them different colors, which match with the legend, so in some way it does already treat them like two separate timeseries, even if they have the same name. Just the legend hiding does not seem to work.

**Comment by dprokop** [comment]
> At the same time @dprokop does it make sense to use the series name as a unique identifier for things like how the legend works? Maybe something like query_id/ref_id + name would be better?

You are right @aocenas. There should be a distinction between what's displayed in the legend vs what's the underlying identifier is. Adding this to our backlog, hopefully we can address this soon. 

But to make sure @RutgerKe can continue without waiting for a fix - I assume the legend format in the Prometheus query should be a good solution, right?

**Comment by RutgerKe** [comment]
Glad to hear its on the backlog. Thanks! It is bothering me in the 'explore' view, I can currently work around it by using promql relabeling. The legend is indeed a good workaround for dashboards. So I am not blocked by this.
