### ISSUE TITLE
CloudWatch: Add support for dynamic labels

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#43905]
### Discussed in https://github.com/grafana/grafana/discussions/43894

<div type='discussions-op-text'>

<sup>Originally posted by **sunker** January 11, 2022</sup>
Currently, the cloudwatch data source supports [alias formatting](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#alias) that allows the user to substitute the returned metric label with region, period, metric dimension name etc. This substitution is performed in the plugin backend and the code for this is complicated. Now the GetMetricData api supports [dynamic labels](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/graph-dynamic-labels.html), so instead of doing the substitution in Grafana, we should let the api handle this for us. 

Even though it will be complicated, we should be able to migrate any existing alias patterns into the dynamic label pattern. 
| Current Pattern          | New patterns                                                   |
| ---------------------- | ------------------------------------------------------------- | 
| `{{region}}`           |  `${PROP('Region')}`                                            | 
| `Namespace: {{namespace}}, Instance: {{InstanceId}}`           | `Namespace: ${PROP('namespace')}, Instance: ${PROP('Dim.InstanceId')}`                                          | 

One problem though is that the [LabelOptions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_LabelOptions.html) which allows you to specify a time zone for the dynamic label calculations is set on request level and not on query level. Currently, there's no way for query editors to define panel level settings, but possibly the plugin api can be extended to support that. If not, even though it's not ideal we can make this a grafana configuration under the [aws section](https://grafana.com/docs/grafana/latest/administration/configuration/#aws). 
 </div>

**Comment by yaelleC** [comment]
This possibly fixes another open issue: https://github.com/grafana/grafana/issues/40114
(to link in PR for auto-closing)

**Comment by fridgepoet** [comment]
Closing in favor of #48434
