### ISSUE TITLE
Templating variable stop working

### ISSUE THREAD

**Issue by n3bojs4** [grafana/grafana#4391]
Version : grafana.x86_64  2.6.0-1
datasource: elasticsearch 2.1.1
OS: rhel 6.4

Hi,

I added a templating variable from a datasource (elasticsearch).
My dashboard worked like a charm with this var ($domain) but after a while all values in the dropdown list disappeared (None appears).
I took a look in the templating section and no values are returned anymore in the preview of values.
I verified the datasource used in my templating and it works great.

![grafana](https://cloud.githubusercontent.com/assets/5824519/13815799/48c4d072-eb8c-11e5-94e2-5398d2b34668.png)

Then i tried to create a new dashboard with the same templating var and it works.
But still doesn't return value on the first dashboard.

**Comment by torkelo** [comment]
maybe elasticsearch is not returning any values anymore? Whats the dashboard time range? Open chrome dev tools  (network tab), does the terms query get any hits? What is elasticsearch returning?

**Comment by n3bojs4** [comment]
Ok you are right, it seems to be an issue with the time range of the datasource used in the templating var.
I don't know if it's possible to force the time range in the templating query, it could be usefull.
