### ISSUE TITLE
InfluxDB: Update query editor to support InfluxDB 0.11 syntax changes

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#4392]
> The output of SHOW SERIES and SHOW TAG VALUES have changed a little bit. The relevant PRs are here where you can see the new outputs either in the diff or in the comments:

https://github.com/influxdata/influxdb/pull/5937
https://github.com/influxdata/influxdb/pull/5853

**Comment by bergquist** [comment]
Only show tags query was fixed by that commit.

**Comment by adrianlzt** [comment]
I'm having troubles with ``SHOW TAG VALUES`` and templating.

I have created a database and insert data in InfluxDB like this:
```
> create database grafana_templating
> use grafana_templating
Using database grafana_templating
> insert m1,host=hostA value=0
> insert m2,host=hostB value=0
> insert m2,host=hostC value=0
> SHOW TAG VALUES WITH KEY = "host"
name: m1
--------
key     value
host    hostA

name: m2
--------
key     value
host    hostB
host    hostC
```

Then, with grafana-3.0.0-beta21459801392.x86_64 I have created the new datasource and a new template with query:
``SHOW TAG VALUES WITH KEY = "host"``
But there is only one result:
![captura de pantalla de 2016-04-08 11-54-13](https://cloud.githubusercontent.com/assets/3237784/14380598/a65131b2-fd80-11e5-9581-b073a67f8ff4.png)
