### ISSUE TITLE
Elasticsearch: IP addresses don't survive terms aggregation (use key_as_string)

### ISSUE THREAD

**Issue by fluggo** [grafana/grafana#4393]
When using a terms aggregation on fields indexed as IP addresses, Grafana shows them as their raw key:

![image](https://cloud.githubusercontent.com/assets/2552507/13818130/bc28b2b0-eb62-11e5-9733-a215778f3cd3.png)

Elasticsearch returns the IP address in the key_as_string field.

**Comment by fluggo** [comment]
Forgot to mention: this is on Grafana 2.6.0, against Elasticsearch 2.2.

**Comment by xo4n** [comment]
I have seen the same behaviour with **Kibana 4.5** and Elasticsearch 2.2

**Comment by tomfun** [comment]
+1

**Comment by tomfun** [comment]
in 3.0.4 still the same trouble.

**Comment by lunetics** [comment]
+1

**Comment by lunetics** [comment]
I guess it's the antelope format, see:
https://beej.us/guide/bgnet/output/html/multipage/inet_ntoaman.html

so we basically just need a transformer  like inet_ntoa() funct

**Comment by fluggo** [comment]
No, no. It's much easier than that. Elasticsearch returns the decoded value
in the key_as_string field. It's literally already there.

**Comment by a-kitlin-parc** [comment]
+1

**Comment by YuriyIlyin** [comment]
+1

**Comment by shortdudey123** [comment]
+1

**Comment by fluggo** [comment]
Looking at this again. I *think* this could be as simple as changing [this line](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.js#L262):

```
      return this._post('_msearch?search_type=count', esQuery).then(function(res) {
        var buckets = res.responses[0].aggregations["1"].buckets;
        return _.map(buckets, function(bucket) {
          return {text: bucket.key, value: bucket.key};
        });
      });
```

to:

```
          return {text: bucket.key_as_string || bucket.key, value: bucket.key};
```

...but I don't have a build of Grafana going to test it out. Looks like I might have to do one, otherwise I don't think this issue is going anywhere.

**Comment by uros678** [comment]
@fluggo: I changed it in this [file](https://github.com/uros678/grafana/blob/master/public/app/plugins/datasource/elasticsearch/elastic_response.js#L169) like this:

` if (bucket.key) {
            props[aggDef.field] = bucket.key;
          } else {
            props["filter"] = nameIndex;
          }
          if (bucket.key_as_string) {
            props[aggDef.field] = bucket.key_as_string;
          }`

It is now displaying IP numbers correctly with my data. I don't know if it is the right way, since I don't understand much how all this is working and also I'm not a developer. 

I will also try your proposed method and will let you know if it works.

**Comment by fluggo** [comment]
@uros678: You know what, I bet I have completely the wrong place in the code. I bet yours is the right fix.

**Comment by uros678** [comment]
I don't know to be honest. Hopefully one of the developers would be so kind to give us some pointers or something.

Kind regards, 
Uros
