### ISSUE TITLE
Geomap: Cannot set anchor point for custom marker/icon/symbols

### ISSUE THREAD

**Issue by jeremiahrose** [grafana/grafana#43936]
Grafana 8.3.0 (open source, self hosted).

When I choose a custom .svg file to use as a map marker in the Geomap plugin, the icon is centered on the location point. However, for most marker icons, e.g like this one:
![text](https://static.thenounproject.com/png/5624-200.png) 
The location point should be at the bottom tip of the pin, not the center of the icon. 
This leads to inaccurate presentation of location data.

**Comment by mckn** [comment]
Sounds like adding an anchor point setting to the icon is a good plan.
