### ISSUE TITLE
Clarify folder select/multiselect check box behavior

### ISSUE THREAD

**Issue by amy-super** [grafana/grafana#43931]
Today, folder multiselect for `Move` and `Delete` work like this (for every folder except `General`):

- Select check box next to folder name with folder list **collapsed**
     - Move is disabled
     - Delete is enabled

- Select check box next to folder name with folder list **expanded**
     - Move is enabled
     - Delete is enabled

- Select global "select all" check box
     - Move is enabled
     - Delete is enabled

This behavior needs to be made consistent - `Move` and `Delete` should both be enabled upon selection of any check box. This issue may have a dependency on #43930. 

Additionally, when any of the folder-level check boxes are selected, the global check box should show a partial fill. Today it shows no fill some folders are selected (screenshot below) and it shows a full fill when all folders are selected.
<img width="1374" alt="Screen Shot 2022-01-11 at 5 25 37 PM" src="https://user-images.githubusercontent.com/87499219/149031229-118f492a-be1c-4753-8b1e-3b2e60d1ff89.png">

**Comment by natellium** [comment]
Wondering if https://github.com/grafana/grafana/issues/38102 can be tackled as part of this

**Comment by yusuf-multhan** [comment]
@amy-super
There is one more inconsistent behavior,
- When folder is expanded and selected, all dashboards under that folder also get selected (as expected). Then folder is collapsed and unselected, but that does not unselect the dashboards under that folder. 

Can you please include this as well?

**Comment by murtazaqa** [comment]
Hi @amy-super,

What @yusuf-multhan highlighted here is crucial as well. It causes ambiguity in behavior when -
1. Expand a folder
2. Select the folder
3. Collapse the folder
4. Unselect the folder

The dashboards inside this folder are still in selected state. Ideally it should unselect all the dashboards inside when I am unselecting the folder.

Also user can see Move and Delete buttons enabled where as there is no visible selection on the screen.
