### ISSUE TITLE
Support Icons For Value Mapping

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#43939]
Add support for icons for field value mapping

**Comment by torkelo** [comment]
You can use native emojis, what icons do you want to use?

**Comment by nmarrs** [comment]
Idea is to allow access to our current available icons in our `ResourcePicker.ts` modal which would provide more options for user than just text / emojis. Also, native emojis don't match color set by value map whereas with icons we can match that up. 

![Screen Shot 2022-01-11 at 4 14 10 PM](https://user-images.githubusercontent.com/22381771/149041386-3177fb09-34dd-467f-9120-6c799aeb55f8.png)

**Comment by torkelo** [comment]
ah, sounds good!
