### ISSUE TITLE
Feature request: Add independent time range in templating section 

### ISSUE THREAD

**Issue by n3bojs4** [grafana/grafana#4394]
Add a different time range in the templating section that can permit to return older value.

**Comment by mtanda** [comment]
The detail of issues is mentioned at https://github.com/grafana/grafana/issues/4391#issuecomment-197386826

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
