### ISSUE TITLE
[Feature Request] Allow hiding of Template Variables via URL param

### ISSUE THREAD

**Issue by toddwh50** [grafana/grafana#4395]
We have dashboards that we use on users' PCs that have Template Variables to filter the data in the graphs. But we also want to show these same dashboards on large wall displays, but don't want to show the Template Variable on the screen (since they are view only, no interactivity).

Currently, we have to copy the Template Variable version, then remove the Template Variable and edit every panel Query to remove the Template Variable terms from the Where clause. This takes a lot of time.

It would be much easier if we could pass a URL parameter such as "?template-variables=disabled" to hide the template variable area of the dashboard.

**Comment by torkelo** [comment]
this is already implemented, you can hide variables in Grafana 3.0 (soon to be released)
https://github.com/grafana/grafana/pull/4154

**Comment by toddwh50** [comment]
Great, thanks!

**Comment by matjazmav** [comment]
So what query parameter do I need to use to hide template variables? Where are docs about that?

**Comment by daniellee** [comment]
@matjazmav there is no query parameter for hiding template variables. There is a query parameter for going into kiosk mode (add `?kiosk` or `&kiosk` to the end of the url):

http://docs.grafana.org/reference/playlist/#tv-or-kiosk-mode

It is possible to hide a template variable through the template variable settings:

- https://github.com/grafana/grafana/issues/2420#issuecomment-270063730
- http://docs.grafana.org/reference/templating/#basic-variable-options

**Comment by matjazmav** [comment]
@daniellee But if i hide template variable I can not not use them in chart queries

**Comment by daniellee** [comment]
@matjazmav You set them through the querystring if you hide them:

```
http://localhost:3000/dashboard/db/templating-showcase?orgId=1&var-server=backend_01
http://localhost:3000/dashboard/db/templating-showcase?orgId=1&var-server=backend_02
```

Is that not what you are asking for? Maybe I don't understand your question?

**Comment by Codyooo** [comment]
It would be great if I can hide the templating variables by changing settings OR adding url parameters something like  &hide-temp-var=true. I think the latter way is more convenient. I hope you may consider adding this feature in the future~
