### ISSUE TITLE
[Question] No datapoints with influxdb 0.10.3

### ISSUE THREAD

**Issue by hmm2001** [grafana/grafana#4396]
Hello,

I am using Grafana 2.6.0 with influxdb 0.10.3 on CentOS 7. I have configured the data source and it is working. But when I started the query of the influxdb. It always shows "No datapoints".

Do you have any ideas?

Thank you very much for the help.

**Comment by torkelo** [comment]
whats your query? Maybe something wrong with your query that makes it return zero points?  Many are using 2.6 with InfluxDB 0.10 without issues

**Comment by hmm2001** [comment]
Very simple query as following

SELECT mean("value") FROM "load_longterm" WHERE "host" = 'localhost' AND $timeFilter GROUP BY time(10s) fill(null)

**Comment by torkelo** [comment]
And influxdb response ?

**Comment by hmm2001** [comment]
The query is working fine in influxdb. But when I tried it on the Grafana, it always gave me the "no datapoints" message.

**Comment by torkelo** [comment]
But what's the influxdb response? (And rendered query), check using Chrome dev tools network tab
