### ISSUE TITLE
Explore prometheus shows both instant and range values in the explore graph

### ISSUE THREAD

**Issue by RutgerKe** [grafana/grafana#43967]
**What happened**:

When running a query for prometheus in explore, the returned data is always shown in a graph.

![image](https://user-images.githubusercontent.com/6214906/149160242-c4a15fb0-36e8-4523-ae31-be1d64543fc0.png)

**What you expected to happen**:
The result of instant queries used to be in a table below the graph

**How to reproduce it (as minimally and precisely as possible)**:
A simple query of '1' will show it, [example on play.grafana.org](https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%221%22%7D%5D)

**Anything else we need to know?**:
When doing just an 'instant' query this happens as well, I think that is where the problem lies. If it was intentional: the table made more sense for instant queries, this graph visualization is kind of wasteful with space on the screen:
![image](https://user-images.githubusercontent.com/6214906/149161076-db3ddb7c-7f19-4868-a537-41436bbb7d8f.png)

Plus, when selecting 'stacking' this also messes up the visualization, the mix of instant and range in the same panel.

It works as I expected in Grafana version 7.3

**Environment**:
- Grafana version: 8.4, 8.3.3
- Data source type & version: prometheus
- OS Grafana is installed on: grafana cloud
- User OS & Browser: firefox
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
The issue is that scalar values should be shown in tables and not graph. To fix this,  we need to add `|| dataFrame.meta?.custom?.resultType) === 'scalar'` to https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/result_transformer.ts#L48.

**Comment by tharun208** [comment]
@ivanahuckova I like to work on this
