### ISSUE TITLE
Alerting: pause/unpause works incorrectly in some cases

### ISSUE THREAD

**Issue by nrukavkov** [grafana/grafana#43988]
**What happened**:
I use pause and unpause alerts in grafana while deploying the application. 
CI like this:
1. Pause alert in Grafana using API
2. Stop the application
3. Copy binary files 
4. Start application
5. Unpause alert in Grafana using API

While stopping my application generates a lot of dropping sessions and we monitor it. But Grafana ignores pause (I checked, Grafana in UI shows that alert is paused) and sends me a notification about the problem.

![image](https://user-images.githubusercontent.com/54890287/149292162-8c21c5a7-32df-4232-bfb2-33ccb08eea77.png)

**What you expected to happen**:
I expect to avoid getting notifications about problems.

**How to reproduce it (as minimally and precisely as possible)**:
Create some alert, pause alert, generate some data to make Grafana think that it is needed to send an alert, stop generating, and unpause alert.

**Environment**:
- Grafana version: v8.3.3 (30bb7a93ca)
- Data source type & version: influx
- OS Grafana is installed on: linux
- User OS & Browser: chrome

**Comment by ch1seL** [comment]
+

**Comment by ch1seL** [comment]
➕

**Comment by gerobinson** [comment]
Hi,

I'm afraid I'm not sure I quite understand the issue. I created an alert that evaluates once per 10 seconds for 30 seconds, received a notification, paused the alert, and then didn't receive further notifications until I unpaused the alert? Is the issue that Grafana is still sending notifications while the alert is paused?

**Comment by gerobinson** [comment]
A potential fix is to change `For` from `0m` to `5m` as the range is `(5m, now)`. This should mean that Grafana does not send notifications after the alert is unpaused as 5 minutes will have passed before the alert can change from pending to firing. However, a possible issue with this is that if the purpose of the alert is to send notifications if there is one or more errors in the last 5 minutes then I think its possible to miss alerts, so another option would be to unpause the alert 5 minutes after the service has been started.

I'm not sure that we would add such a feature to old alerting. Instead we would recommend upgrading to the new alerting (Unified Alerting) which is now the default in Grafana 8.3.

**Comment by gerobinson** [comment]
If upgrading to the new alerting (Unified Alerting) please check the [following page](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/). Unlike old alerting, Unified Alerting does not support pausing of alert rules. Instead, it's recommend to create a silence for the alert. For example, a 5 minute silence while updating the service.

**Comment by gerobinson** [comment]
Hi @nrukavkov, is this issue resolved?

**Comment by nrukavkov** [comment]
I suppose yes. Thank you
