### ISSUE TITLE
OpenTSDB Templating - Passing more than one tag condition within tag_values function

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#4398]
I am having a use case, where I want to get the filtered list of servers in the template dropdown for the selected environment. If I change the environment on first dropdown, it should update the second dropdown server list. Though 'OpenTSDB lookup' query supports to query that way but I am not sure, grafana allows in the UI to pass more than one tag parameter within tag_values function.

**Comment by gt-rocker** [comment]
As I see there is only one line to change:
`var tag_values_regex = /tag_values\((.*),\s?(.*)\)/;`
to non-greedy
`var tag_values_regex = /tag_values\((.*?),\s?(.*)\)/`

Then you can write template variable query in this way:
`tag_values(your.metric, yourTag1=$tempVar1,yourTag2)`
to get lookup query to opentsdb like
`?m=your.metric{yourTag1=XXX,yourTag2=*}`

Does anybody have time to test this and compose a pull request?

**Comment by digrich** [comment]
This support would also help in 'Value groups/tags' feature where we can pass the $tag parameter from first query to another tag value query as a second parameter. 

@utkarshcmu, @gt-rocker - Do you have any use case or example, where you have used 'Value groups/tags' in templating with OpenTSDB?

**Comment by gt-rocker** [comment]
Really I have no idea where to use this feature. I don't understand how it works (for user) because of very short description. Could you explain me the key benefits?

**Comment by utkarshcmu** [comment]
@digrich I also want this feature so that I can use $tag1 in 2nd template variable. Started some work last week but too busy at work these days. Hopefully will make some progress in next 1-2 weeks. :)

**Comment by digrich** [comment]
I think this feature would really help whenever we have large number of entries in the template dropdown and want to group them further by different dimension so end user can easily filter out the data on the dashboard.

for e.g. We have many report dashboards which uses table panel to show the system/app data of hundreds of servers. User can select either 'All' or some selected list of servers from the template dropdown but if he wants to select only some set of servers by some other dimensions, it's not easy. With this feature we can easily display different types of application as tags in the template dropdown and user can select any application which will display the data for only those servers where this application is running.

**Comment by gt-rocker** [comment]
I watched http://docs.grafana.org/img/v2/multi-select.gif. Looks nice.
But I have no need for this :)

I've spent some time investigating how it works.
And I have good news: it works! With my changes, described above.
For example, I have a template var with such query:
`tag_values(my.metric.name, opentsdb-tag-for-template-var-values)`

That's what I do for grouping by labels:
Tags query:
`tag_values(my.metric.name, opentsdb-tag-name-for-producing-labels)`
Tag values query:
`tag_values(my.metric.name, opentsdb-tag-name-for-producing-labels=$tag,opentsdb-tag-for-template-var-values)`

$tag is a keyword here - it equals the selected label's (group's) value.
So in a tag values query we request all values of our 'main' tag (for template var values list) with additional condition. I think that if we select multiple labels, grafana makes multiple queries (one for each label).

For example I grouped Spark applications by cluster names:
![screenshot from 2016-06-03](https://cloud.githubusercontent.com/assets/405550/15792210/7cba53d4-29e4-11e6-9c83-c03f32bb0936.png)

**Comment by digrich** [comment]
Thanks @gt-rocker for trying out this. I hope @utkarshcmu, whenever he gets time create a pull request for your changes.

**Comment by utkarshcmu** [comment]
Here is the required documentation for using nested template variables in Opentsdb. 

https://github.com/grafana/grafana/pull/5343/commits/f3003a97ef73b7eca2bd6cd2fdd97c40503c3824

**Comment by digrich** [comment]
Great. Thanks @utkarshcmu

**Comment by bergquist** [comment]
Close by https://github.com/grafana/grafana/pull/5343
