### ISSUE TITLE
Annotations: Variables don't work in Annotations queries

### ISSUE THREAD

**Issue by kustodian** [grafana/grafana#43994]
**What happened**:
We have a simple PromQL query that uses a variable `$team` in the Annotations query. Here is how it looks like:
![image](https://user-images.githubusercontent.com/1949229/149309196-8b699205-098b-4cbc-a154-47234d046e9d.png)

I'm pretty sure this worked in 7.X (not sure exactly when), but now variables don't work in Annotations queries. The same variable is used in other parts of the dashboard without a problem. Here is how this variable is defined:
![image](https://user-images.githubusercontent.com/1949229/149309853-c4562ddb-4b7a-4791-92c2-9f0ed001d29d.png)

From our testing no variable works. If we replace the variables with hard-coded strings, all works.

**What you expected to happen**:
That the query supported variables like they are supported in panels.

**How to reproduce it (as minimally and precisely as possible)**:
Create a variable and use it in the Annotations query.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Prometheus 5.0.0
- OS Grafana is installed on: CentOS 7
- User OS & Browser: ArchLinux/Firefox
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
This has been fixed and will be part of the next patch release https://github.com/grafana/grafana/pull/43459
