### ISSUE TITLE
Grafana v8.3.3 - Value Mappings - Time based fields do not apply Value mappings

### ISSUE THREAD

**Issue by hrandal** [grafana/grafana#44021]
**What happened**:   
Using Elastic search as a datasource, with Grafana version 8.3.3, noticed an issue with applying value mappings to any timeseries based data columns with Table Panels.
I have a table with a timestamp column (standards RFC date time). Despite modifying the Standard Options > Unit for the Time field, no value mapping transformations apply to the field. It seems that the underlying reason that the transformations do not apply is that despite applying unit changes, the original value for the timestamp field applies, and is not able to be converted through the Grafana value mappings transformations at this time. (Range, Regex, or Value).

**What you expected to happen**:  
  Value mappings to apply to the new field's value, which has been converted through Standard Options > Unit, instead of the field's original value.

**How to reproduce it (as minimally and precisely as possible)**:  
1. Create a table panel, and add a column with Date and Time -values. 
2. Apply field overrides to the field: Standard Options > Unit conversion : Date and Time -> Datetime ISO
2. Attempt to apply any value mappings to the field (Range, Regex, Value), I have been unsuccessful in getting any transformations to the field based on the new transformed field value. It seems that the value mapping does not apply after unit conversion.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Elastic Search 6.5+
- OS Grafana is installed on: MacOS
- User OS & Browser: Chrome
- Grafana plugins: none
- Others:
![image (2)](https://user-images.githubusercontent.com/97722295/149462273-e6a37250-b2ab-417e-87db-0b74ed9aa008.png)
![image (3)](https://user-images.githubusercontent.com/97722295/149462274-423f6b8d-909c-4bca-81c3-9da538a8316c.png)
![image](https://user-images.githubusercontent.com/97722295/149462275-489ac384-0323-4c0a-921e-d13d257e77e4.png)
![image (1)](https://user-images.githubusercontent.com/97722295/149462270-1155a848-9574-4d69-845d-994c969e1446.png)

**Comment by dprokop** [comment]
@hrandal as you have noticed, the value mappings apply to the raw data and this is how they are intended to work. Value mappings - as well as other field options - are means for providing display characteristics of your **raw** data. They are applied in a way they do not modify the underlying data as well as they are not aware of any other field options configured (i.e. unit and value mappings in your example).

We do not have plans to change that any time soon - but if you find this an important thing to support I highly encourage you to open a discussion around it: https://github.com/grafana/grafana/discussions. Then we can gauge whether or not this is something that we need to prioritize.
