### ISSUE TITLE
Alerting: Error in expanding template if NoData

### ISSUE THREAD

**Issue by gillg** [grafana/grafana#44038]
**What happened**:
Since I updated from 8.2.3 to 8.3.3 I have many errors `error in expanding template`
I detect them thanks to the metric `prometheus_rule_evaluation_failures_total` exposed on the grafana metrics endpoint.
It seems related to queries wich returns NoData, should not triggers alerting, but grafana seems try to evaluate the template even if nothing is sent...

**What you expected to happen**:
No errors if no alerting sent 

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/5639241/149516108-9369e186-487b-4816-9c26-962e60217ee2.png)

Alert state if no data or error : OK and OK

Some labels / annotations (like Summary) contains dynamic labels related to the query result (`{{$labels.cluster}}` for exemple)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux
- Grafana plugins: Alertmanager

**Comment by gerobinson** [comment]
Hi @mckn,

These errors are logged in Grafana but what happens is the variable (i.e. `{{$labels.cluster}}`) is expanded to `<no value>` for `DatasourceNoData` alerts. I will however raise this issue as it looks like we shouldn't be logging these errors for `DatasourceNoData` and `DatasourceError` alerts.

**Comment by mckn** [comment]
> Hi @mckn,
> 
> These errors are logged in Grafana but what happens is the variable (i.e. `{{$labels.cluster}}`) is expanded to `<no value>` for `DatasourceNoData` alerts. I will however raise this issue as it looks like we shouldn't be logging these errors for `DatasourceNoData` and `DatasourceError` alerts.

Ok ok, I'm not familiar with this feature but it sounds like @gerobinson understands the issue and will take this over.

**Comment by Sorvatus** [comment]
Hi @gillg 
i had the same problem. As a workaround i add "if guards" :)  for no data in my description
I figured out Summery / Description  based on the Go templating system like Message Templates.
```
{{if $values}}
    show {{$labels.cluster}}
{{end}}

```
![image](https://user-images.githubusercontent.com/87822992/151333560-aa8440e5-98d6-4558-9eff-1ee72c1d9cf0.png)

@gerobinson:
it will be nice to have a docs link to "Go templating system" 
[alert-annotation-label
](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/alert-annotation-label/
)
like it has been done at
[message-templating](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/message-templating/)

**Comment by grobinson-grafana** [comment]
Hi! We have made some small changes to the documentation for custom annotations and labels that should help :) https://grafana.com/docs/grafana/next/alerting/fundamentals/annotation-label/variables-label-annotation/

**Comment by grobinson-grafana** [comment]
Hi! We have made some small changes to the documentation for custom annotations and labels that should help https://grafana.com/docs/grafana/next/alerting/fundamentals/annotation-label/variables-label-annotation/
