### ISSUE TITLE
Dashboard UID generation issue

### ISSUE THREAD

**Issue by FVAVEIRO** [grafana/grafana#44033]
**What happened**: 
I use a script to generate dashboards with rest api (using a grafana python lib), and the script gives a fix UID to each dashboard (so if I have to generate them again fro some reason, the link to the dashboard is the same). But I got the error `Server Error 500: Error while checking if dashboard is provisioned` 

**What you expected to happen**:
Before, for older versions, the script was working fine and generating dashboards with the given UID.

**How to reproduce it (as minimally and precisely as possible)**:
Send a dashboard through api with any already written UID

**Anything else we need to know?**:
When I dont send the UID, the script just works fine but all the links I have are deprecated every time the grafana instance is reset

**Environment**:
- Grafana version: 8.4.0

**Comment by marefr** [comment]
Please enable [debug logging](https://grafana.com/docs/grafana/latest/administration/configuration/#level) and check Grafana server log for detailed error description.

**Comment by marefr** [comment]
Closing this due to lack of response. We'll consider reopen the issue if you provide more information.
