### ISSUE TITLE
[Bug] InfluxDB querybuilder regex incorrect when using templating

### ISSUE THREAD

**Issue by jasonjclifford** [grafana/grafana#4405]
Generated query while using template variables is not enforcing exact match.

Details:
Template variable 
Name:  environment
Query: SHOW TAG VALUES FROM "openstack_cinder_limits" WITH KEY = "environment" 
Sample Values: Dev, Test, Prod, FOO_PROD

In the query builder selecting to filter by environment and selecting the $environment templating variable creates:
environment =~ /$environment$/
Full Query Example:
SELECT mean("totalVolumesUsed") FROM "openstack_cinder_limits" WHERE "environment" =~ /$environment$/ AND $timeFilter GROUP BY time($interval), "environment" fill(null)
Since this is grouped by the 'environment' tag when selecting the PROD environment both FOO_PROD and PROD data is displayed.  Both items appear in the legend.

Manually editing the query for the where statement fixes this issue.
environment =~ /^$environment$/

Grafana Version: 2.6.0
Datasource: InfluxDB
OS: rhel 6.6

**Comment by bergquist** [comment]
Thank you for reporting this.

Not sure that I would label this as a bug. Rather as a request for more options regarding how strict template matching should be.
