### ISSUE TITLE
[Question] Can't see KairosDB option in latest build.

### ISSUE THREAD

**Issue by abhagupta** [grafana/grafana#4406]
Hi, 
I have been trying to connect KairosDB with Grafana and I am having few issues.  Kairos DB is running in my machine and I can reach it at http://localhost:8080/. I built the grafana latest code (2.6) and when I try to add a Data Source, I do not see an option for KairosDB.

In another effort, I ran the grafana as a docker container, I saw the KairosDB option, but it could not connect to the application running at http://localhost:8080/.  It could successfully connect to Graphite but not KairosDB

Any pointers?

Grafana version : 2.6(latest)
Data Source: KairosDB
OS : Mac OSX Version 10.9.5

**Comment by bergquist** [comment]
Did you build from master? 

I master KairosDB have been moved out of grafana core into a plugin. 
https://github.com/grafana/kairosdb-datasource
