### ISSUE TITLE
Playlist URL Unavailable in Grafana UI

### ISSUE THREAD

**Issue by melgl** [grafana/grafana#44070]
**What happened**: Unable to obtain the Playlist URL to share a Playlist, the "Copy Link Address" functionality is not available. 

**What you expected to happen**: Obtain a Playlist URL in Grafana UI for sharing a Playlist.

**How to reproduce it (as minimally and precisely as possible)**: Navigate to a Playlist following [instructions in Playlist Docs](https://grafana.com/docs/grafana/latest/dashboards/playlist/#share-a-playlist-in-a-view-mode), try to obtain a Playlist URL. 

**Anything else we need to know?**: Same behavior observed with Playlists on https://play.grafana.org/playlists

**Environment**: 
- Grafana version: Grafana OSS v8.3.3, Grafana Cloud v8.3.3
- OS Grafana is installed on: Ubuntu 20.04.3 LTS, hosted Grafana Cloud
- User OS & Browser: Chrome Version 97.0.4692.71 (Official Build) (64-bit) for Windows 10, Firefox Version 96.0.1 (64-bit) for Windows 10, Microsoft Edge Version 97.0.1072.62 (Official build) (64-bit) for Windows 10, Chrome Version 96.0.4664.110 for MacOS Big Sur 11.6.2, Chrome Version 97.0.4692.71 (Official Build) (arm64) for MacOS Big Sur 11.6.2, Chrome Version 97.0.4692.71 (Official Build) (64-bit) for Ubuntu 20.04.3 LTS, Firefox Version 96.0 (64-bit) Mozilla Firefox for Ubuntu 20.04.3 LTS 

<img width="783" alt="copylinkaddress_grafanacloud" src="https://user-images.githubusercontent.com/81323402/149575322-b3fee379-102d-4262-8016-bf27288c1d1e.png">
<img width="823" alt="copylinkaddress_grafanaoss" src="https://user-images.githubusercontent.com/81323402/149575329-924ec576-9ce9-4607-810c-d47c9a49707f.png">
<img width="1515" alt="copylinkaddress_grafanaoss2" src="https://user-images.githubusercontent.com/81323402/149575334-496324d4-b93c-419b-a583-43fda7d7a10f.png">

![image](https://user-images.githubusercontent.com/81323402/149575337-81fdc59b-5748-47f8-b155-a69ea6edd606.png)

<img width="437" alt="Screen Shot 2022-01-14 at 12 21 37 PM" src="https://user-images.githubusercontent.com/81323402/149575345-188246fd-a0d6-49c2-838e-a714c64e058e.png">

**Comment by hugohaggmark** [comment]
Hi @melgl and thanks for reporting this, seems like we missed this scenario when we migrated from Angular to React. Thank you 🙏
