### ISSUE TITLE
Docs feedback: /auth/github.md

### ISSUE THREAD

**Issue by mhebrard** [grafana/grafana#44088]
Please specify where to find the option to create a github OAuth apps:
* Click on your user (top right icon)
* In the drop down, click on Settings
* In the left menu, click on Developer settings
* In the left menu, click on OAuth Apps
* Click on Register a new application

Also, please indicate in which file we should copy the grafana configuration

**Comment by achatterjee-grafana** [comment]
This information should be available in GitHub documentation: https://docs.github.com/en/developers/apps/building-oauth-apps/creating-an-oauth-app. 
Are you looking for a link to this information from Grafana docs?

**Comment by achatterjee-grafana** [comment]
Closing this issue, as the information requested is not Grafana specific.

**Comment by mhebrard** [comment]
yes the Grafana documentation is scares on that topic 

> To enable the GitHub OAuth2 you must register your application with GitHub. GitHub will generate a client ID and secret key for you to use.

> You need to create a GitHub OAuth application (you will find this under the GitHub settings page). When you create the application you will need to specify a callback URL. Specify this as callback:

I would advice to add a clear step by step guide, or at least a link to github documentation.
my point is reading current Grafana doc I am missing needed information
