### ISSUE TITLE
'never' connect null values in time series not respected since Grafana 8.3.0

### ISSUE THREAD

**Issue by agebhar1** [grafana/grafana#44085]
**What happened**:

Time series graph connect data points with 'holes' despite of 'Never' option for 'Connect null values' since Grafana 8.3.0.

**What you expected to happen**:

No connection of data points if 'Never' option for 'Connect null values' is set and 'holes' exists, which is the case in Grafana 8.2.7.

**How to reproduce it (as minimally and precisely as possible)**:

Prometheus data source with a metric where some data points not exists.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.x
- Data source type & version: Prometheus, 2.32.1
- OS Grafana is installed on: Ubuntu 21.10
- User OS & Browser: Ubuntu 21.10, Firefox
- Grafana plugins: default

![time-series_connect-null-values 1](https://user-images.githubusercontent.com/2443866/149670599-d689bc9b-c568-4ca4-b025-859a1f467654.png)

Query response is similar, the schema was changed from 8.2 to 8.3.
![time-series_connect-null-values 2](https://user-images.githubusercontent.com/2443866/149670679-096b80f9-65d7-48c3-b334-48ff10e4a8ca.png)

The non formatted data from inspect panel differs from 8.2.7 to 8.3.0. The response data does not contain a value for time 1642344660000, the 'hole', which is inserted in 8.2.7 but not in 8.3.x.
![time-series_connect-null-values 3](https://user-images.githubusercontent.com/2443866/149670831-4ab31975-69d6-489f-a7e9-fd1bcc8427d8.png)

The downloaded CSV files: 
* [grafana-8.2.7.csv](https://github.com/grafana/grafana/files/7877521/grafana-8.2.7.csv)
* [grafana-8.3.0.csv](https://github.com/grafana/grafana/files/7877522/grafana-8.3.0.csv)

**Comment by leeoniya** [comment]
sounds like a dupe of the issue fixed by https://github.com/grafana/grafana/pull/43622. will be in 8.3.4.

can you try latest nightly build?

https://grafana.com/grafana/download/nightly?edition=oss

**Comment by agebhar1** [comment]
It is, with 8.4.0-47863pre the null value is back and the graph rendered fine.
![time-series_connect-null-values 4](https://user-images.githubusercontent.com/2443866/149673404-e8ebcfba-46eb-4af9-9c9b-9cd59197f0c7.png)

Thanks.
