### ISSUE TITLE
State timeline shows points that shouldn't appear

### ISSUE THREAD

**Issue by xafer337** [grafana/grafana#44099]
I want to show a timeline where the firing alerts are shown everytime they are triggered.
**What happened**:
When I try to show a state timeline with the alerts that are firing, the visualization shows some points where shouldn't be anything (the more clear points) 
![image](https://user-images.githubusercontent.com/61606830/149765318-b7de2b7e-9389-4f62-b97d-2d264a930959.png)

**What I expected to happen**:
I expected something like in the Status history panel, were there only are shown the points where the Alert is firing (same data):
![image](https://user-images.githubusercontent.com/61606830/149765778-91fb4f0a-60f9-44c3-b19e-6e16362b5217.png)

**How to reproduce it**:
Using the query ALERTS{alertstate="firing"} and triggering alerts on and off

**Environment**:
- Grafana version: v8.3.0
- Data source type & version: Prometheus (v2.29.2)
- OS Grafana is installed on: Official Docker image

**Comment by leeoniya** [comment]
that's the fundamental defference between the two panels. State timeline's states are "sticky" until the next state or a `null` state; it's meant to display state _transitions_, such as a valve open/close or a switch on/off.

it sounds like Status history is the one you'll want to use if your data points effectively act as a periodic heartbeat for status.

**Comment by hugohaggmark** [comment]
Closing this issue because we're trying to limit open GitHub issues in order to better track planned work and features.

Thank You to you for taking the time to create this issue!
