### ISSUE TITLE
Alerting: No get method in webhook

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#44100]
In New notification channel, when type webhook is selected, there is no get method in the dropdown line.

![Снимок экрана 2022-01-17 в 15 05 51](https://user-images.githubusercontent.com/97888813/149766721-af2f3074-4bdb-4faf-8b56-ba074e8a5bf1.png)

**Comment by ael-p** [comment]
Hello @ejaysss. 
IMO, that's because that's the way you'll PUT in message in the notifiers, depending on what your Notifier API works.
GET wont be able to push alerts on your media.
