### ISSUE TITLE
Over ride for second axis doesn't work when units match

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#44118]
**What happened**:
When I create an override with "Axis Placement > Right" and choose "Standard options > Unit"  with a unit that either does not exist or matches the left, the right side axis is not created. If I change the metric to another unit (as long as it is not nothing, the right axis appears.

**What you expected to happen**:
When I select "Axis Placement > Right", the right hand axis should always be presented, along with the matching fields.

**How to reproduce it (as minimally and precisely as possible)**:
See above.

**Anything else we need to know?**:
This worked perfectly in version 6. Overrides in version 8 are not as useful.

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: collectd
- OS Grafana is installed on: CentOS 7.9
- User OS & Browser: firefox

**Comment by leeoniya** [comment]
i think this was fixed by https://github.com/grafana/grafana/pull/41635. can you try 8.3.x?

**Comment by yellowpattern** [comment]
Yes. 8.3.3 fixes this regression.
