### ISSUE TITLE
[Question] Annotations & elasticsearch, query lucene ?

### ISSUE THREAD

**Issue by FheA** [grafana/grafana#4416]
Hello,

I discover Grafana this week and for my work i want to put annotations in my dashboard.

But i dont find what syntax i must to put.

![grafana](https://cloud.githubusercontent.com/assets/17929622/13881238/56080976-ed20-11e5-81eb-fb1b8ef3ddf5.png)

Thanks a lot

**Comment by torkelo** [comment]
Look up elasticsearch docs for lucene query syntax. 

Think there is an elasticsearch annotation on the annotation dashboard on play.grafana.org
