### ISSUE TITLE
Write down a step-by-step procedure for creating a coremodel component

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#44160]
We should create a step-by-step guide to creating a coremodel component - that is, a package/tree of packages, included in the Grafana backend at compile time, that at minimum offers a YAML CRD expression of a schema. (Definition subject to change)

Writing a good guide will require us hammering out a number of design questions that are currently uncertain. As such, this issue is intended more as a milestone/medium-term goal to help give us a clear definition of done to aim for - and one that supports our broader goal of continuously widening the circle of people who can work on the overarching intent api project.

- [ ] #44232
- [x] #44715

**Comment by GrafanaWriter** [comment]
Labeling as "Needs Research" as we are in the midst of working on this project. Assigning @achatterjee-grafana also for visibility.

**Comment by sdboyer** [comment]
This, along with intent API is dead, as it has evolved into the kind system!
