### ISSUE TITLE
[Documentation Bug] two PieChart plugins: is the 1st abandoned? If yes, this should be documented everywhere

### ISSUE THREAD

**Issue by mikebdp2** [grafana/grafana#44162]
Here's the 1st PieChart plugin: [https://github.com/grafana/piechart-panel](https://github.com/grafana/piechart-panel) , [https://grafana.com/grafana/plugins/grafana-piechart-panel/](https://grafana.com/grafana/plugins/grafana-piechart-panel/)
There are only indirect signs, by which an uninformed observer might guess that this 1st PieChart plugin is outdated and deprecated:
**1)** outdated README: it even suggests to git clone `release-1.3.8`, while the latest version is `1.6.2`
**2)** despite the latest version is `1.6.2` according to this plugin's homepage at Grafana website where it's also available for download, at Github - only 1.6.1 is tagged and no-one tagged 1.6.2
**3)** no-one is replying to these many users' issues - https://github.com/grafana/piechart-panel/issues

And here's the 2nd PieChart plugin: [https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/piechart](https://github.com/grafana/grafana/tree/main/public/app/plugins/panel/piechart). It is a new PieChart, available out-of-the-box at new versions of Grafana. However, it doesn't seem to have its' own homepage on Grafana website like its' ancestor, and anyone searching for "grafana piechart" will inevitably land on the homepage of seemingly-deprecated "1st PieChart".

**What I'm suggesting:**

if the 1st one is abandoned - please, openly state this on the pages above! So that the users won't waste time playing with the "1st PieChart" and bug reporting its' issues to essentially a /dev/null . Also, if the users will know that new Grafana has a new PieChart, they'll be more likely to take the effort to upgrade. But, you should warn that the "1st PieChart" dashboards created at older Grafana like 7.0.3 ===> will get broken while importing to the newer Grafana like 8.3.3: even if you'll install the outdated "1st PieChart" to a newer Grafana, the majority of PieCharts aren't visible - and the only solution is to manually copy-paste their SQL queries into the newer PieCharts.

**P.S.** Also, I'm wondering out of curiosity if the 2nd PieChart has been written from scratch, or if its' source code is based on the 1st one.

**Comment by mikebdp2** [comment]
**CC** the 2nd PieChart contributors: @corpglory-dev @torkelo @ryantxu @dprokop @tskarhed @mckn @thisisobate @oscarkilhed @ashharrison90 @hugohaggmark @jackw @kaydelaney @nikki-kiga

**Comment by mikebdp2** [comment]
**CC** the 1st PieChart contributors: @bergquist @Ijin08 @daniellee @briangann @torkelo @ryantxu @xadhoom @marefr @maniac103 @dprokop @oddlittlebird @utkarshcmu @robert-milan @mpchadwick @oscarkilhed @Jamim @gretamosa @eastcirclek @sunker @h4wkmoon @fl0ge @conet @smalik03 @rotemreiss @ferozsalam

**Comment by ashharrison90** [comment]
hey @mikebdp2 👋 

the 1st is deprecated. a PR to add a call to action to migrate to the newer version was merged here: https://github.com/grafana/piechart-panel/pull/268, but looks like maybe a new version would need releasing for that to actually be picked up. i'm not sure. it does also render as `Pie chart (old)`: 
![image](https://user-images.githubusercontent.com/20999846/149976203-12f41203-a472-4ba5-bd3c-d76e63fb919f.png)

in terms of code, it's a complete rewrite.

as a community manager i'm sure you're aware of this already, but please try to avoid tagging every person who's ever contributed to the component for a docs bug which would have gone through our normal triage process anyway.

hope that helps!

**Comment by oddlittlebird** [comment]
@scoren-gl, FYI

**Comment by mckn** [comment]
We should probably update the readme of the "old" piechart so it is obvious that it is deprecated in favor of the new one. @grafana/grafana-bi-squad

**Comment by mikebdp2** [comment]
@ashharrison90 Thank you very much for your kind reply
> it does also render as Pie chart (old)

Yes, after the Grafana upgrade - together with a "1st PieChart" plugin installation before the dashboards importing - I've noticed the previously-created piecharts are `Pie Chart (old)` like on your picture above. However, the great majority of these piecharts - with an exception of few those which also happen to be a single slice (100%) - weren't visible in their panels. And trying to switch them from `Pie Chart (old)` to `Pie Chart` by choosing a different dashboard visualization - didn't fix their visibility.

I suspect, there might be some JSON incompatibility between the old and new Grafana which may break the imported dashboards, seeing that the same SQL queries - if copied into the newly-created Pie Chart dashboards - produce the valid visible piecharts.

**Comment by mikebdp2** [comment]
@mckn
> We should probably update the readme of the "old" piechart so it is obvious that it is deprecated in favor of the new one.

Yes, and also - probably someone need to review the issues of the people who have been waiting a reply for a couple of years _(I was one of them :roll_eyes: )_ since some issues may contain the suggestions that may be useful for a new PieChart as well - and reply to them to at least notify these people about a new PieChart available at new Grafana.

**Comment by dprokop** [comment]
@mikebdp2 thank you so much for raising this issue. I have just opened a PR adding a deprecation notice to the piechart-panel Readme: https://github.com/grafana/piechart-panel/pull/288

**Comment by gavk34** [comment]
Hi, facing something similar when upgrading to v8.3.4

```
✔ Downloaded devopsprodigy-kubegraf-app v1.5.2 zip successfully

Fetching devopsprodigy-kubegraf-app dependencies...

Error: ✗ failed to install plugin grafana-piechart-panel: grafana-piechart-panel v>=1.3.7 either does not exist or is not supported on your system (Grafana v8.3.4 linux-amd64)
```

Any ideas on how to resolve that dependency on `grafana-piechart-panel` which looks to be deprecated now? Or is that an issue for https://github.com/devopsprodigy/kubegraf#requirements
