### ISSUE TITLE
Create a rough graphviz dependency diagram of the planned parts of Intent API

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#44167]
Per @kylebrandt's suggestion, we should create a dot diagram of the various moving parts and their expected dependency patterns within the overall work in support of an intent API.

i've just found https://github.com/TLmaK0/gravizo, which should allow the simplest possible workflow for this - write it directly in a `.md` file somewhere within the new fs structures we're creating as part of the componentization work, and it'll render directly within Github. That's great, as we can be sure that a stable linkable URL for it will always be up to date, as it's dynamically generated.

**Comment by GrafanaWriter** [comment]
Adding @achatterjee-grafana to track
