### ISSUE TITLE
Remove golang.org/x/net/context

### ISSUE THREAD

**Issue by zserge** [grafana/grafana#44178]
The codebase still uses `golang.org/x/net/context` import as well as `ctxhttp` helper.
We need to:

1) Replace `golang.org/x/net/context` with the stdlib `context` package in the imports.
2) Replace `golang.org/x/net/context/ctxhttp` with `http.NewRequest` + `req.WithContext` + `client.Do` or something similar.

As bus removal #44130 progresses - there's only 2 places left:

```
pkg/expr/transform.go
11:     "golang.org/x/net/context"

pkg/services/provisioning/notifiers/alert_notifications.go
8:      "golang.org/x/net/context"
```

**Comment by marefr** [comment]
I removed this from Backend Platform Backlog project - it's a project we don't want to use anylonger.
