### ISSUE TITLE
Add e2e artifacts to .gitignore

### ISSUE THREAD

**Issue by hdecarne** [grafana/grafana#44176]
**What happened**:
I downloaded the source archive for release 8.3.4 and noticed an increase in size 10Mb -> 50Mb. This is caused by file ./e2e/build_results.zip. Looks like a temporary artifact to me and not meant to be stored in repo.

**What you expected to happen**:
File should be excluded via .gitignore or created outside repo.

**How to reproduce it (as minimally and precisely as possible)**:
Simply download the release package.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by ashharrison90** [comment]
thanks for spotting this @hdecarne 🚀
