### ISSUE TITLE
Question - Restored Grafana db not updating dashboard

### ISSUE THREAD

**Issue by pckeyan** [grafana/grafana#4418]
I started using Grafana recently. I am in the process of backing up the grafana.db and restore it when a new instance comes up in cloud. It all starts fine and shows up the dashboard. If I modify the same dashboard or create new dashboard, it is not saving it. Giving a message - "Problem! Dashboard not found". Can you please help me how I can restore and use the db so that I do not recreate Dashboards/users everytime I bring up new instance?

Appreciate your time.

Regards
Karthik

**Comment by torkelo** [comment]
It should work, are you sure your restoring grafana.db in /var/lib/grafana , and then starting grafana-server ?

**Comment by rayprill** [comment]
I recently tried what the OP mentions with v 2.5 and I had no problems.  It worked OK.

**Comment by pckeyan** [comment]
I am using version grafana-2.6.0-1.x86_64.rpm in AWS EC2. Yes I have placed the backed up database correctly in /var/lib/grafana. App started correctly and shows the backed dashboard/datasources correctly. But it is not allowing to update or create dashboard showing the error message. I can try 2.5 version.

**Comment by utkarshcmu** [comment]
It worked for me with Grafana 2.6 , make sure your db user has permission to write data or something. Looks like a permission issue to me.

**Comment by pckeyan** [comment]
I am using the admin default user; When restore the db it is installed by root user. Does it need to be grafana user/group?

**Comment by pckeyan** [comment]
Thanks all for all your time appreciated; I updated the user/group to grafana and saves it. Thanks @utkarshcmu

**Comment by hiroshi** [comment]
I had same kind of error when update, create anything after restoring db, but my bad I forgot to restart grafana.
When I restart grafana (for me recreate kubernetes pod), it works again.
