### ISSUE TITLE
Ability to configure the default log group name in Grafana CW plugin

### ISSUE THREAD

**Issue by ainapudi** [grafana/grafana#44182]
Grafana CW plugin lists all log groups from CW letting the user pick from thousands of log group names. We plan to run 200 Grafana instances, each instance can only access a few log groups from CW. We need the ability to only list accessible log groups in a drop down if there are more than one. If only one log group is accessible, default to it so the user does not have to input the name.

Edit by @iwysiu : Feature request to add a `Default Log Groups` field to the CloudWatch plugin configuration that will pre-populate log queries.

**Comment by iwysiu** [comment]
Hi @ainapudi ! Unfortunately, aws [DescribeLogGroups](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_DescribeLogGroups.html) doesn't allow us to filter by access. However, you can type in the `Log Groups` box to find the log group you want.

**Comment by ainapudi** [comment]
Typing in the Log Groups box is a pain point for the users since the Log Group names are really long and hard to remember. Customer needs a way to set the default log group name in the plugin config, so their users can see this pre-populated.

**Comment by iwysiu** [comment]
Hi @ainapudi ! That should be possible. I'll edit the issue description to better describe the feature request.

**Comment by ainapudi** [comment]
Thanks @iwysiu ! This is a top priority for our customer.

**Comment by ainapudi** [comment]
@iwysiu Any update on this?

**Comment by iwysiu** [comment]
Hi @ainapudi !

I've just linked a pr for it to this issue.

**Comment by ainapudi** [comment]
thanks @iwysiu !
