### ISSUE TITLE
Dashboard: Shared tooltip requires reload of page to activate

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#44187]
**What happened**: I enabled the shared tooltip from the dashboard options page and when I returned to the dashboard, the crosshairs on each graph were not visible. I had to save and reload the page.

**What you expected to happen**: for the shared tooltip to be instantly visible on all graphs as it was back in version 6.

**How to reproduce it (as minimally and precisely as possible)**:change a dashboard to have a shared tool tip.

**Anything else we need to know?**:
This is another regression from earlier versions of grafana.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version:
- OS Grafana is installed on: CentOS 7.9
- User OS & Browser: firefox
- Grafana plugins:
- Others:

**Comment by hugohaggmark** [comment]
Confirmed on main and Play

**Comment by yellowpattern** [comment]
is there a tag/label to use for bugs introduced with the main UI rewrite?

**Comment by hugohaggmark** [comment]
I don't think so but which previous versions did this work on before @yellowpattern?

**Comment by yellowpattern** [comment]
6.5
