### ISSUE TITLE
"Azure Resource Graph" missing in Azure Monitor resource dropdown

### ISSUE THREAD

**Issue by senses0** [grafana/grafana#44189]
**What happened**: In my local instance of Grafana, "Azure Resource Graph" no longer appears in the service dropdown. This definitely worked in version 8.0 but stopped working in one of the subsequent versions... 

I regularly update this local instance, so not sure exactly at which point it stopped working

![Explore - Azure Monitor - Grafana](https://user-images.githubusercontent.com/17622644/150046710-6479cefc-23ba-4dc3-82db-6e9241ccc7cd.png)

**Environment**:
- Grafana version: v8.3.4 (a551d74b11)
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Windows 10, Chrome Version 97.0.4692.71 (Official Build) (64-bit)
- Grafana plugins: Azure Monitor

**Comment by andresmgot** [comment]
This is a side effect of https://github.com/grafana/grafana/issues/43401. To fix it, you should uninstall the external Azure monitor plugin. The version of the core plugin should be 0.3.0. Please re-open it if it's still misbehaving for you.
