### ISSUE TITLE
Prometheus: Proxied queries with Trickster sometimes fail

### ISSUE THREAD

**Issue by d9705996** [grafana/grafana#44198]
**What happened**: 

After updating Grafana to 8.3.4 any panels using a variable in the Min Step show a `Internal Server Error - Check the Grafana server logs for the detailed error message.` error

![image](https://user-images.githubusercontent.com/2470279/150106841-ea246947-ff27-4477-ae51-94c8ce591f26.png)

**What you expected to happen**:

The panels to show the requested time series data with the step matching the variable value.

**How to reproduce it (as minimally and precisely as possible)**:

1. On a grafana 8.3.4 instance, create a new dashboard and add a new interval variable
2. Add a new time series panel
3. Add a new Prometheus query e.g. `count(up)` (Any query will cause this issue)
4. Set the Min Step to the variable name

![image](https://user-images.githubusercontent.com/2470279/150107161-f9bb66db-d00e-499b-ad9d-3081e538b291.png)

**Anything else we need to know?**:

Issue was previously resolved in 8.3.3 from https://github.com/grafana/grafana/pull/42637  

An example log entry is

```
t=2022-01-19T09:57:43+0000 lvl=eror msg="Request error" logger=context userId=2 orgId=1 uname=dwalker error="runtime error: index out of range [31] with length 31" stack="/usr/local/go/src/runtime/panic.go:90 (0x43c554)\n/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.118.0/data/vector.gen.go:809 (0x8779e4)\n/root/go/pkg/mod/github.com/grafana/grafana-plugin-sdk-go@v0.118.0/data/field.go:197 (0x24149cb)\n/drone/src/pkg/tsdb/prometheus/time_series_query.go:336 (0x2414898)\n/drone/src/pkg/tsdb/prometheus/time_series_query.go:217 (0x24131f1)\n/drone/src/pkg/tsdb/prometheus/time_series_query.go:104 (0x24121fc)\n/drone/src/pkg/tsdb/prometheus/time_series_query.go:131 (0x2412726)\n/drone/src/pkg/tsdb/prometheus/prometheus.go:95 (0x241126e)\n/drone/src/pkg/plugins/backendplugin/coreplugin/core_plugin.go:81 (0x1107270)\n/drone/src/pkg/plugins/plugins.go:244 (0xf0430d)\n/drone/src/pkg/plugins/manager/manager.go:224 (0x21dc451)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:38 (0x21d7c17)\n/drone/src/pkg/plugins/backendplugin/instrumentation/instrumentation.go:67 (0x21dc1b8)\n/drone/src/pkg/plugins/manager/manager.go:223 (0x21dc0e9)\n/drone/src/pkg/api/metrics.go:95 (0x213b4aa)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/api/routing/routing.go:18 (0x1649179)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/context.go:62 (0x1645073)\n/drone/src/pkg/middleware/request_metrics.go:55 (0x1645062)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/context.go:62 (0xdc50fa)\n/drone/src/pkg/macaron/macaron.go:155 (0xdc50ec)\n/usr/local/go/src/net/http/server.go:2047 (0x6d990e)\n/drone/src/pkg/middleware/csp.go:22 (0x1641872)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/context.go:62 (0xdc50fa)\n/drone/src/pkg/macaron/macaron.go:155 (0xdc50ec)\n/usr/local/go/src/net/http/server.go:2047 (0x6d990e)\n/drone/src/pkg/macaron/render.go:44 (0xdbfda6)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/context.go:62 (0x16443ca)\n/drone/src/pkg/middleware/recovery.go:167 (0x16443c1)\n/drone/src/pkg/macaron/context.go:32 (0xdbcebb)\n/drone/src/pkg/macaron/inject.go:139 (0xdbde54)\n/drone/src/pkg/macaron/inject.go:117 (0xdbdd7c)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/context.go:62 (0x1642284)\n/drone/src/pkg/middleware/logger.go:33 (0x164226d)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/context.go:62 (0x1646c59)\n/drone/src/pkg/middleware/request_tracing.go:57 (0x1646c48)\n/usr/local/go/src/reflect/value.go:556 (0x4e65a4)\n/usr/local/go/src/reflect/value.go:339 (0x4e5b24)\n/drone/src/pkg/macaron/inject.go:159 (0xdbe0e6)\n/drone/src/pkg/macaron/inject.go:119 (0xdbdd34)\n/drone/src/pkg/macaron/context.go:67 (0xdbcfcb)\n/drone/src/pkg/macaron/router.go:156 (0xdc171d)\n/drone/src/pkg/macaron/router.go:213 (0xdc23d5)\n/drone/src/pkg/macaron/macaron.go:189 (0xdbf6f0)\n/usr/local/go/src/net/http/server.go:2879 (0x6dce7a)\n/usr/local/go/src/net/http/server.go:1930 (0x6d89e7)\n/usr/local/go/src/runtime/asm_amd64.s:1581 (0x473060)\n"
```

Removing the variable from the Min Step field removes the error and the query executes successfully.

![image](https://user-images.githubusercontent.com/2470279/150106996-6a92eb05-5cb3-4352-ab61-b9f5569c17ed.png)

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: prometheus
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome/Firefox and Edge

**Comment by Warlock667** [comment]
Same issue here, just a small difference with

"4. Set the Min Step to the variable name"

None of my dashboards in Grafana 8.3.4 has a "min step" set. Though I get the same error. As soon als I click into the empty "min step" field and then click on something else, the error is gone.
After I reload a Dashboard the error is back again.

**Comment by svs1979** [comment]
Happens when using $interval etc. in the query itself too. Errors occur on panels with some PromQL `rate(...[$__rate_interval])`:
`bad_data: parse error at char xxx: bad duration syntax "1m1"`

**Comment by carboneater** [comment]
Same error here with 8.3.4 OSS, using $__rate_interval

![image](https://user-images.githubusercontent.com/1527214/150136542-33d27916-5925-40b2-b321-2f72644fb781.png)

Whereas replacing `$__rate_interval` with `1m` yields a graph.

![image](https://user-images.githubusercontent.com/1527214/150136769-679cab7d-90ce-41da-bc13-65faee03628a.png)

**Comment by DasSkelett** [comment]
#44035 looks like the culprit at first sight

**Comment by ivanahuckova** [comment]
@carboneater @DasSkelett  @Warlock667  @svs1979  What OS is your Grafana installed on?

**Comment by carboneater** [comment]
@ivanahuckova
Ubuntu 18.04.6 LTS
APT-Sources: https://packages.grafana.com/oss/deb stable/main amd64 Packages

**Comment by Warlock667** [comment]
Ubuntu 20.04.3 LTS 
deb https://packages.grafana.com/oss/deb stable main

**Comment by ivanahuckova** [comment]
@Warlock667

>  As soon als I click into the empty "min step" field and then click on something else, the error is gone.

Could you please go to Query inspect and check if the `interval` value changes when you click into empty Min step. In other words, if it there is any change between when it works and doesn't work. Thank you so much!
 
![image](https://user-images.githubusercontent.com/30407135/150181744-60710399-b70c-4572-84c1-105ad1bbcc90.png)

**Comment by Warlock667** [comment]
That's really a strange one.
My "klick in min step" doesn't work in all cases and I can't figure out any difference between my tries. Sometimes it works and sometimes not..

If it does work I can't figure out the interval.

Step 1
![1](https://user-images.githubusercontent.com/52013314/150189095-6948cdd7-022e-4f94-b361-ea4013c7b918.jpg)

That's how my dashboard look like in case my workaround works

Step 2
![2](https://user-images.githubusercontent.com/52013314/150189225-dc09d0b3-a291-43fd-add7-ea36e9fbc1f1.jpg)
If I then want to check the interval I only get a "Refresh" Button

Step 3
![3](https://user-images.githubusercontent.com/52013314/150189318-240cdee2-71c4-4f04-921b-ecd475fa85f2.jpg)
If I press the "Refresh" Button my Metrics in the background are gone.



One thing that just came to my mind: I got a Trickster Proxy between Grafana and Prometheus.
I will change my environment to check if the error also occurs if I connect directly ( Although the behaviour started right after the Grafana Update)

**Comment by kaibaesler** [comment]
Same error here with 8.3.4 CE, using $__rate_interval

**Comment by svs1979** [comment]
> @carboneater @DasSkelett @Warlock667 @svs1979 What OS is your Grafana installed on?

Running on Kubernetes, official Grafana image

**Comment by Warlock667** [comment]
Just connected directly from Grafana -> Prometheus and the behaviour ist absolutely the same.

**Comment by ivanahuckova** [comment]
Ok, seems like couple different issues mixed here. I am creating new one for the $__rate_interval as original issue doesn't mention using it. If your issue is related to `$__rate_interval`, please follow up in that issue.

**Comment by ivanahuckova** [comment]
Thanks @Warlock667, doesn't seem that interval changes at all. In this case, could I ask you to send us full request, error and check server logs if there are any errors.

**Comment by d9705996** [comment]
The issue is happening for multiple queries but a particular example is 

`linux_load_1{fqdn="$fqdn"}` where `$fqdn` is populated from a query variable on the same prometheus datasource using `label_values(up{job="linux"},fqdn)` (which populates correctly in the dashboard.)

```
Object
status:500
statusText:"Internal Server Error"
data:Object
error:"Server Error"
message:"Internal Server Error - Check the Grafana server logs for the detailed error message."
config:Object
url:"api/ds/query"
method:"POST"
data:Object
requestId:"Q127"
retry:0
headers:Object
hideFromInspector:false
message:"Internal Server Error - Check the Grafana server logs for the detailed error message."
```
This issue also affects running the query in explore (the error in inspector is the same as above)

![image](https://user-images.githubusercontent.com/2470279/150329358-e3c219d4-fabc-499a-b95e-9a7883e39dff.png)

It is worth noting that the reloading the same dashboard will sometimes work but their is no obvious pattern

**Comment by d9705996** [comment]
Upon further investigation the prometheus datasource is pointing to a trickster proxy (running the latest [version](https://github.com/trickstercache/trickster/releases/tag/v1.1.5))

When I reconfigure the datasource to point directly to the prometheus API I cannot replicate the errors.  

When the datasource is configured to use trickster and a request is made that throws an error in Grafana there are no errors shown in the trickster logs and the debug logs do not show any relevant differences between a request that fails and one that succeeds

The prometheus URL trickster is requesting data from prometheus looks correct and when queried outside grafana is successfully processed.  Below is an example query that trickster is making.

```
http://127.0.0.1:9090/prometheus/api/v1/query_range?end=1642680480&query=linux_load_1%7Bfqdn%3D%22REDACTED%22%7D&start=1642680000&step=120
```

Please also note that issue may not be directly related to using a variable in the Min Step as the error can occur if there is a hardcoded value enter e.g. `1m`

For reference the prometheus version that is being queried is `2.32.1` (although I can replicate fault with `v2.31.1` also)

**Comment by ivanahuckova** [comment]
@Warlock667 Could you try again to see if removing `trickster` between Grafana and Prometheus doesn't resolve the issue for you as well?

**Comment by gabor** [comment]
@Warlock667 maybe your problem is not the same as @d9705996 's problem (although it's a big coincidence that both of you use Trickster Proxy). 
@Warlock667 , could you please find in the logs the error message that you receive? (should be a line similar to what @d9705996 reported in the first message)

**Comment by gabor** [comment]
@d9705996 i do not have experience with Trickster Proxy, but based on a quick github check, it says it is a caching proxy. 
could you retry with caching disabled?

or, in other words, is the trickster proxy modifying the response in any way, or is it just passing it through? as long as it just passes the request through to Prometheus unmodified, and afterwards passes the response from prometheus to grafana through unmodified, and never returns old, cached prometheus-responses, it should work.

one caching scenario that might cause the problem:
- you make a time-range query for the last 4 hours
- the grafana system calculates the exact START and END timestamps for the 4hour time-region and does the prometheus query
- you get back a result, all is ok
- after a couple minutes, you run a query for the last 4 hours again
- the grafana system calculates the exact START and END timestamps. please note, at this point, "last 4 hours" is not the same time range as before, it has moved by a couple minutes
- the caching proxy decides this query is "close enough" to the previous query, and does not go to Prometheus, and returns the old Prometheus result instead

i don't know if trickster does something like this though.

**Comment by d9705996** [comment]
@gabor  - I have just tested updating our trickster proxy to the latest non-stable version [v2.0.0-beta2](https://github.com/trickstercache/trickster/releases/tag/v2.0.0-beta2) which has resolved our issue.  I am going to leave the system running and see if I can replicate the fault with the latest versions in case updating to v2 has invalidated ll of the data cached in redis,

**Comment by svs1979** [comment]
In our case, it's not trickster that Grafana is talking to but Promxy. I'll try to do some checks without Promxy and update Promxy if possible.

**Comment by Warlock667** [comment]
Doublechecked with trickster :

A: it really does work if I connect directly to Prometheus (Sorry, in my first try I set the datasource that is directly connected to Prometheus as default and did not recognise, that this does not affect dashboards that are already there - my fault(

B: it also works if I switch to trickster 2.0.0-beta2

Thanks to all of you !

**Comment by d9705996** [comment]
I cannot replicate with the latest version of trickster so I will close this issue but might be worth adding something the release notes
