### ISSUE TITLE
Grafana crash due to huge response for Cloud Monitoring `HEADERS` request

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#44190]
**What happened**:
In some GCP project which has too many k8s metrics, Grafana crash before query finished.

**What you expected to happen**:
Query finished without crash.

**How to reproduce it (as minimally and precisely as possible)**:
1. Prepare environment which has too many time series for one metric type
2. Build query for the metric in Explore
![image](https://user-images.githubusercontent.com/224552/150080506-9439bf67-a8d8-466b-8dbb-58288b1defde.png)
3. Run Query

**Anything else we need to know?**:
After investigate this issue, I notice that HEADERS response size is too huge, in our env, it is 74.56MB.

We use Grafana Cloud, and I guess the instance memory is limited.
So crash is caused by OOM. If the instance has enough memory, query will finish without error.

Cloud Monitoirng API provide the way to limit response size.
https://cloud.google.com/monitoring/api/ref_v3/rest/v3/projects.timeSeries/list
> If view is set to HEADERS, this is the maximum number of TimeSeries returned.

CloudWatch datasource already limit metric suggestion response size.
https://github.com/grafana/grafana/pull/31788

Cloud Monitoring should limit the size at here.
https://github.com/grafana/grafana/blob/v8.3.3/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L140-L158

**Environment**:
- Grafana version: Grafana v8.3.3 (30bb7a93c)
- Data source type & version: Cloud Monitoring
- OS Grafana is installed on: n/a
- User OS & Browser: Firefox & Windows 10
- Grafana plugins:
- Others:
Grafana is running on Grafana Cloud.

**Comment by andresmgot** [comment]
Thanks for the report @mtanda, the details are super helpful. Unfortunately, I am not able to reproduce the issue with our current data. Are you able to verify that you can limit the size of the answer adding a `pageSize` there (to something smaller than 100.000, like 1.000)? You will probably needed to add support for this parameter as well in the metricQuery definition at https://github.com/grafana/grafana/blob/v8.3.3/pkg/tsdb/cloudmonitoring/types.go#L44

If we can verify that, then we can see how we can add support for proper pagination so all the content can eventually be reached.

**Comment by mtanda** [comment]
@andresmgot  Thanks for your help.
I modified Grafana and confirmed that the response size is significantly reduced.

I attach screenshot of developer tools.

Before modified, response size is 57.44MB.
![cloud_monitoring_before](https://user-images.githubusercontent.com/224552/150241357-7fa54d4f-a115-4c5d-962f-3e11440b2b0c.png)

Modify pageSize to 1000, response size is 32.50MB.
![cloud_monitoring_after1000](https://user-images.githubusercontent.com/224552/150241626-c6947756-0181-4bce-89a1-82340d01d651.png)

Modify pageSize to 100, response size is 485.56KB.
![cloud_monitoring_after100](https://user-images.githubusercontent.com/224552/150241874-242bb970-eed5-4add-9998-ef8b0de23aaf.png)
The number of list items is 100, `pageSize` actually works as intended.
![cloud_monitoring_after100_response](https://user-images.githubusercontent.com/224552/150241985-b7ebaf81-a453-4206-94aa-b96ecf69d1cc.png)

**Comment by mtanda** [comment]
Cloud Monitoring datasource set same custom data and deep links to all frame.
If the datasource can change response format to set only one custom data and deep links, the response size becomes more smaller.
When `pageSize` is 100, the response size becomes 96.99KB. (significantly reduced from 485.56KB)

[diff with original code](https://gist.github.com/mtanda/71b5247d30c484e9771e4bf963b7aeeb)

screenshot of developer tools
![without_meta](https://user-images.githubusercontent.com/224552/150246000-f0207c4e-84a4-4942-a508-90c505152bb4.png)

**Comment by andresmgot** [comment]
Thanks again for the details @mtanda. Actually, checking the code, from that request it seems that we are only interested in the first entry:

https://github.com/grafana/grafana/blob/5b61273497526dbb9b6e14bc9cf3588fd5df7bba/public/app/plugins/datasource/cloud-monitoring/datasource.ts#L182

So we can actually set the pageSize to 1 and avoid pagination. Can you try that? If that solves the issue (and the same behavior is kept), please send a PR with the proposal :)

**Comment by mtanda** [comment]
@andresmgot 
I tried to set pageSize to 1. It doesn't work. It only show 1 label value in Filter dropdown.
To collect many label values, the pageSize should be enough big number.

I think the real problem is that, Grafana backend amplify response size by copying same metadata to all frames.
If Grafana frontend is only interested in the first entry, Grafana backend should not generate rest of entries.

Current implementation, `parseResponse()` parse response for `HEADERS` and `FULL`.
https://github.com/grafana/grafana/blob/5b61273497526dbb9b6e14bc9cf3588fd5df7bba/pkg/tsdb/cloudmonitoring/time_series_filter.go#L92
It might be better to add another `parseResponse()` for `HEADERS`, and optimize it.

**Comment by mtanda** [comment]
We need to think about How Grafana should work for the label completion.

If Grafana need to show all label values in filter dropdown, backend need to support pagination or another solution.
If Grafana doesn't need to show all label values, simply limit pageSize to 100 or enough small number.

The pagination will cause API throttling, I propose another solution.

Cloud Monitoring API support filter with `HEADERS`, Grafana can filter result by setting filter like `metric.labels.instance_name=starts_with("gke")`.
If Grafana defer Cloud Monitoring API call until user input some character in filter, Grafana can limit response size (and API call?) more effectively.

I imagine user operation flow like following.
- When user type "g", Grafana call API with filter `<some label key>=starts_with("g")` and pageSize to 10.
- When user type "k", Grafana call API with filter `<some label key>=starts_with("gk")` and pageSize to 10.
- Continue this cycle until user find the label value what they want to input.

**Comment by andresmgot** [comment]
That sounds good to me but the changes in the fronted would be quite more complex though. If we do that, the fronted should still have the full list of options in memory because if not, when you select one label, no other label would be shown in the dropdown menu (if they don't match the selected label).

> I think the real problem is that, Grafana backend amplify response size by copying same metadata to all frames. If Grafana frontend is only interested in the first entry, Grafana backend should not generate rest of entries.

Can you verify if this is the problem? If that's the case, we can maintain the current behavior and request the default amount of pages but only populate the labels of the first frame. That should reduce the size of the response. 

Sorry, I am not very familiar with the backend code here so I am not that helpful here :sweat_smile: .

**Comment by mtanda** [comment]
> If we do that, the fronted should still have the full list of options in memory because if not, when you select one label, no other label would be shown in the dropdown menu (if they don't match the selected label).

Sorry, I was not considered enough. My proposal is not good.

> Can you verify if this is the problem? If that's the case, we can maintain the current behavior and request the default amount of pages but only populate the labels of the first frame. That should reduce the size of the response.

I check original Cloud Monitoring API call response size and Grafana backend response size.

[patch for debug print](https://gist.github.com/mtanda/1fd5fdc0d01bd9d361badf8277ee67be)

Actual Cloud Monitoring API call response size is 700228B (683KB).
```
query = aggregation.alignmentPeriod=%2B60s&aggregation.crossSeriesReducer=REDUCE_NONE&aggregation.groupByFields=metadata.system_labels.name&aggregation.perSeriesAligner=ALIGN_MEAN&filter=metric.type%3D%22kubernetes.io%2Fcontainer%2Fcpu%2Flimit_utilization%22&interval.endTime=2022-01-24T01%3A40%3A48Z&interval.startTime=2022-01-24T00%3A40%3A48Z&pageSize=0&view=HEADERS
len = 700228
query = aggregation.alignmentPeriod=%2B60s&aggregation.crossSeriesReducer=REDUCE_MEAN&aggregation.groupByFields=metadata.system_labels.name&aggregation.perSeriesAligner=ALIGN_MEAN&filter=metric.type%3D%22kubernetes.io%2Fcontainer%2Fcpu%2Flimit_utilization%22&interval.endTime=2022-01-24T01%3A40%3A48Z&interval.startTime=2022-01-24T00%3A40%3A48Z&pageSize=0&view=FULL
len = 756029
```

Grafana backend response size is 56.13MB.
![Screenshot 2022-01-24 104320](https://user-images.githubusercontent.com/224552/150709791-cee858e6-ac8f-4a51-ac18-6bbb3be95bd3.png)

The Grafana backend response size is 84 times as large as Cloud Monitoring response size.

If dropping unused frames, Grafana backend response size becomes 43.52KB, significantly reduce size.

[patch for dropping unused frames](https://gist.github.com/mtanda/a5cdcbb5f1da8d2aebb17c07fec3d180)
![Screenshot 2022-01-24 104320](https://user-images.githubusercontent.com/224552/150710463-8415a757-4c6f-43e0-9c0d-20297e25b15d.png)

**Comment by mtanda** [comment]
This [PR](https://github.com/grafana/grafana/pull/38650/files?w=1#diff-be823fa860127465e4c9518eab333dec6bbac9b158c01a59f62ac302cd825269R252-R258) seems to related for performance issue.

**Comment by mtanda** [comment]
@sunker Could you check this? Because this issue is caused by backend code change.

**Comment by mtanda** [comment]
I prepare code to fix this issue.
https://github.com/grafana/grafana/pull/44365
