### ISSUE TITLE
Azure Monitor: Outdated documentation in plugins page

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#44209]
**What happened**:

The documentation for the Azure Monitor plugin in https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/ is pointing to a very old version of the plugin that was external once. Now is part of core Grafana so this documentation should be similar to [CloudWatch](https://grafana.com/grafana/plugins/cloudwatch/?tab=installation).

On top of the wrong documentation, people following these docs may end up with the wrong version of the plugin on their Grafana (because #43401).

**What you expected to happen**:

The page above to just point to the core plugin.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Note that for some reason, the core plugin version is 0.3.0 while the external (older) version of the plugin is 0.3.1. Would increasing the version of the core plugin fix the issue?

cc/  @grafana/docs-squad @grafana/plugins-platform-backend 

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by lombardialess** [comment]
I have grafana 8.4.0 and the core plugin to me is 0.3.0. The latest core version is 0.3.0 or 0.3.1? If I install 0.3.1 manually the nothing is not working well

**Comment by andresmgot** [comment]
yes, please, use the core plugin with version 0.3.0

**Comment by sarahzinger** [comment]
@fridgepoet is it fair to say this issue will be fixed whenever we release the next minor version of grafana? Or do we think the documentation is a separate issue?

**Comment by andresmgot** [comment]
I suspect it won't, I don't think that is so automated but we can check again once that is released.

**Comment by fridgepoet** [comment]
Hi @grafana/docs-squad could we get help updating the text on the [Azure monitor plugins page](https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/)? It is currently outdated

What we'd like is something like:
```
Azure Monitor Data Source - Native Plugin
Grafana ships with built in support for Azure Monitor. You just have to add it as a data source and you will be ready to build dashboards for you Azure Monitor metrics.

Read more about it here:

http://docs.grafana.org/datasources/azuremonitor/
```

Do let me know if there is someone else more appropriate to contact -- we weren't really where to update it. Thanks!

**Comment by andresmgot** [comment]
> @fridgepoet is it fair to say this issue will be fixed whenever we release the next minor version of grafana? Or do we think the documentation is a separate issue?

so this didn't work, Grafana 8.4.5 already bundles Azure Monitor 1.0.0 but the plugin page still points to the old page: https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/

**Comment by andresmgot** [comment]
it's working now :clap:  https://grafana.com/grafana/plugins/grafana-azure-monitor-datasource/ (I guess it was finally synced).
