### ISSUE TITLE
[Feature Request] Datasource: Apache Solr

### ISSUE THREAD

**Issue by jdrews** [grafana/grafana#4422]
Requesting the addition of Apache Solr as a datasource. It also uses Lucene like Elasticsearch so hopefully the transition would be smooth.

**Comment by gpatwa** [comment]
+1

**Comment by bergquist** [comment]
This should be implemented as a plugin.

**Comment by rw72777** [comment]
SOLR support would be really awesome!

**Comment by torkelo** [comment]
This could be a great plugin, if anyone wants to develop it here are some instructions
http://docs.grafana.org/plugins/development/
http://grafana.net

**Comment by jdrews** [comment]
I wonder if we can utilize this to jumpstart solr support?
https://github.com/grafana/simple-json-datasource

**Comment by jdrews** [comment]
Chronix (based on solr) is working on a grafana plugin. It might be worth watching. 
https://github.com/ChronixDB/chronix.grafana
https://github.com/ChronixDB/chronix.grafana/pull/1

**Comment by mikich** [comment]
+1
It would be really useful to have SOLR support!!!
Thanks

**Comment by shishircc** [comment]
+1
It would be great to have Solr support.

**Comment by stockii** [comment]
+1

**Comment by mbrizbee** [comment]
+1

**Comment by jhon0010** [comment]
+ 1

**Comment by enahwe** [comment]
I'm looking forward to use a Solr Source for Grafana, because SolrCloud is often deployed above Hadoop clusters, also he is full compliant YARN, Elasticsearch isn't compliant YARN yet. By proposing a Solr connector, Grafana could become a really interested part of architectures full compliant Big Data !

**Comment by matthewwicks** [comment]
+1

**Comment by bcarun** [comment]
It would be great to have Solr support. We use Cassandra and Solr, waiting to use Grafana talking to solr. As elastic search is there already, getting Solr support should be easy.

**Comment by deadlocks** [comment]
+1

**Comment by revolutionisme** [comment]
+1

**Comment by allxone** [comment]
+1

**Comment by wisekaa03** [comment]
+1

**Comment by demarkle** [comment]
+1

**Comment by jahtux** [comment]
+1

**Comment by ziq211** [comment]
++++1

**Comment by sdwsk** [comment]
+1

**Comment by mosuka** [comment]
+1

**Comment by mathiasbrem** [comment]
+1

**Comment by beingyash** [comment]
Did any development happen here? Is this even in Grafana's roadmap? @torkelo
