### ISSUE TITLE
Field size limit when using Postgres

### ISSUE THREAD

**Issue by nikita-b** [grafana/grafana#44230]
**What happened**:
We want to migrate Grafana database from SQLite to Postgres and we have an issue with fields size.
For example: When we used SQLite with Grafana all fields had TEXT type:
```
CREATE TABLE `tag` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `key` TEXT NOT NULL
, `value` TEXT NOT NULL
);
```
and didn't have any size limits but Postgres has a different schema:
```
 id     | integer                |           | not null | nextval('tag_id_seq'::regclass)
 key    | character varying(100) |           | not null |
 value  | character varying(100) |           | not null |
```
Only 100 characters. Also, Grafana API doesn't have proper error handling here and we just have database errors in logs:
```
pq: value too long for type character varying(120)
```
It's just one case with tags, we have the same behavior with a title for dashboards and other fields.

To be honest, isn't clear to me why  `character varying` was chosen over `TEXT`. `TEXT` doesn't have a performance penalty, and internally it's the same type:
https://www.postgresql.org/docs/current/datatype-character.html

More difficult case with MySQL (need to specify prefixes and so on) but I think it's also possible to find compatibility with SQLite solution.

Do you know about this problem? Does this count as an issue?

**What you expected to happen**:
1. The same behavior for SQLite and Postgres
OR/AND
2. Proper error handling.

**How to reproduce it (as minimally and precisely as possible)**:

Create an annotation tag with 101 symbols.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on: Grafana 8.3.3 
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
Was able to replicate the issue of long tags failing with a 500 error of

```json
{"error":"pq: value too long for type character varying(100)","message":"Failed to save annotation"}
```

I'm not sure if it's intended to store such long tags, but nonetheless this error message isn't great.

**Comment by idafurjes** [comment]
@nikita-b, I can refer you to some community sites https://community.grafana.com/t/migration-sqlite-to-postrgessql/10393 there have been some discussions on the topic

**Comment by nikita-b** [comment]
@idafurjes To be honest I think it's not related to this issue at all.
1. I have an issue even with a new instance.
2. Grafana doesn't have any docs about this behavior.
3. I think we can do a better solution here. If Grafana team doesn't have time for this issue I can suggest my solution.

**Comment by idafurjes** [comment]
@nikita-b if it is regarding a different issue, you can always open another issue and suggest a solution :)
