### ISSUE TITLE
[Question] How to add plugin?

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#4423]
```
Hi, bro

I want to add custom-plugin.

I download source-code in '$GOPATH/src/github.com/grafana/grafana'
and I ran $GOPATH/src/github.com/grafana/grafana/bin/grafana-server.

It's Ok! Grafana is good running.

so I want to add custom-plugin
I  see http://docs.grafana.org/v3.0/plugins/panels/ 
   && example/panel page not found (https://github.com/grafana/grafana/blob/master/examples/panel-boilerplate-es5/module.js#L27-L38)
   &&  https://github.com/grafana/example-app..

I understood how to work on plugin.

but I don't know directory(position) && add-custom-setting for my plugin

I want to run NO daemon, 
then I want to run $GOPATH/src/github.com/grafana/grafana/bin/grafana-server

Procedures wonder, How to add custom-plugin????

Ah, grafana-cli don't work (I think that grafana-cli base on daemon but I don't want daemon start)

I am beginning angularjs and go-lang.

Have you could help me? plz

Thanks!
```

**Comment by bergquist** [comment]
Hi

You have to place the plugin in the plugin directory. If your running grafana from source its "$GOPATH/src/github.com/grafana/grafana/data/plugins" 

The easiest way is just to clone the plugin repo into that folder. 
Grafana-cli will be the prefered way to install plugins once 3.0 beta is released.

**Comment by tuyy** [comment]
@bergquist 
Hi. Your advice helped me.. but I have panel-error such Below Image..

How to remove error?

<img width="701" alt="2016-03-21 6 16 33" src="https://cloud.githubusercontent.com/assets/13308314/13914364/3e69750c-ef91-11e5-85a8-42c72ed0dcef.png">

**Comment by bergquist** [comment]
@tuyy apps are not really finished yet. Have you enabled example-app? 
/plugins/example-app/edit -> enable

**Comment by tuyy** [comment]
@bergquist

um.. I tried in the same way .. data/plugins/example-app && data/plugins/piechart-panel

same result... 

I don't understand this
```
/plugins/example-app/edit -> enable
```
data/plugins/example-app/edit file does not exist.

I have to make edit-file? then How to write code? .. sorry I'm grafana-begginer..

Thanks! bro.
