### ISSUE TITLE
intent: Write a proper design doc for component, component group system

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#44233]
#44232 introduced sketched-out definitions for "Components" and "Component Groups" as constructs we can use to better organize backend code overall. Being that it's several layers of dependency away from what we actually care about with the intent API, we think it's good enough to sketch out ideas that we're pretty sure are feasible to implement later, then use them to guide our prototyping work.

At some point, though, we'll need a proper design doc, and then an implementation of the rules in the form of a CLI tool which can be run locally, and will be run as part of CI. This ticket should be closed out once that design doc exists (and no doubt, other issues will be created)

**Comment by hugohaggmark** [comment]
@sdboyer this is a friendly reminder to add appropriate labels to make the issue triage smoother for people on issue triage. Thank you.

**Comment by sdboyer** [comment]
sorry, using the new project interface, it creates them without a label prompt - missed this one

**Comment by sdboyer** [comment]
Direction has changed, and we're not formalizing a "component" concept anytime soon.
