### ISSUE TITLE
how to configure widget on my mobile phone

### ISSUE THREAD

**Issue by TSprinter** [grafana/grafana#4424]
We are using latest grafana and added a lot of different activities from oracle and zabbix to it. And it would be very usefull to see at least 1 of them any time on my mobile. How to make it? Is there any simple solution which allows just to take 1 graph and refresh it?

**Comment by torkelo** [comment]
you can create a dashboard with only one graph and open it in the your mobile :) 

But there is no android/iphone widgets.
