### ISSUE TITLE
Grafana fails to start when trying to provision a single datasource to be deleted

### ISSUE THREAD

**Issue by filewalkwithme** [grafana/grafana#44243]
**What happened**:
We tried to delete a data source through the provisioning of a YAML file, like below:

```
datasources: []
delete_datasources:
  - name: old-data-source
```

Grafana failed to start, printing the following error:
```
logger=provisioning t=2022-01-20T03:42:04.34-0300 lvl=eror msg="Failed to provision data sources" error="Datasource provisioning error: unique identifier and org id are needed to be able to get or delete a datasource"
Failed to start grafana. error: Datasource provisioning error: unique identifier and org id are needed to be able to get or delete a datasource
Datasource provisioning error: unique identifier and org id are needed to be able to get or delete a datasource
```

**What you expected to happen**:
Given that the YAML is valid, we expected the datasource deletion to complete and Grafana to start correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Start Grafana including the file below under the datasources provisioning folder:

```
datasources: []
delete_datasources:
  - name: old-data-source
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: - 
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Ubuntu / Chrome
- Grafana plugins: - 
- Others: -

**Comment by idafurjes** [comment]
@filewalkwithme you need to add orgId to delete a provisioned datasource.

See the example yaml below.

```
# config file version
apiVersion: 1

# list of datasources that should be deleted from the database
deleteDatasources:
  - name: old-datasource
    orgId: 1
```

if adding orgId doesn;t solve your problem please reopen the issue.

**Comment by filewalkwithme** [comment]
Hi @idafurjes, you are right. If we manually add an `orgID`, then Grafana will start correctly and delete the datasource. 

However, there is an inconsistency when Grafana sets the default orgId. 

Grafana is setting a default orgId (for `datasources` and `deleteDatasources`) when there is at least 1 datasource to be added. 

However, if there are zero datasources to be added, then the default orgId wont be set for `deleteDatasources`.

For example, the file below will cause Grafana fail to start:

```
apiVersion: 1

deleteDatasources:
  - name: Prometheus
```
---> `Failed to start grafana. error: Datasource provisioning error: unique identifier and org id are needed to be able to get or delete a datasource
Datasource provisioning error: unique identifier and org id are needed to be able to get or delete a datasource`

However, if we add a datasource to be added to the same file, then both operations are going to succeed (the removal of Prometheus datasource and provisioning of Graphite), even if we didn't have specified an orgId at all. This behavior is not consistent. 

```
apiVersion: 1

deleteDatasources:
  - name: Prometheus

datasources:
  - name: Graphite
    type: graphite
    access: proxy
```

I think that the main issue here can be described as the lack of consistency when setting a default orgID for `deleteDatasources` -> it depends on the number of elements inside `datasources`

**Comment by filewalkwithme** [comment]
@idafurjes can we reopen this?
