### ISSUE TITLE
Loki Query Editor text highlighting issue.

### ISSUE THREAD

**Issue by gubjanos** [grafana/grafana#44252]
Exactly the same issue as https://github.com/grafana/grafana/issues/31736 but with Loki Query Editor, which has not since migrated to Monaco.

**What happened**:
Text highlighting with Shift+right stuck at specific parts of the query text when editing a Loki query.

**What you expected to happen**:
The highlighting should go on until the right arrow is released, or at least re-pressing the right arrow should continue the highlighting when stuck.

**How to reproduce it (as minimally and precisely as possible)**:
Selecting Loki data source in explorer and scrolling in `{job="something"}`
![lokiquerystuck](https://user-images.githubusercontent.com/3594544/150310541-c15fe7ae-d98a-4d0d-83d7-8d038573d3d2.gif)

**Anything else we need to know?**:
This issue has already been fixed for Prometheus in the issue linked above, by changing editor to Monaco.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser: Windows & Chrome
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
@gubjanos thanks for reporting the issue! we are planning to do the same migration for Loki too, so it should be fixed when https://github.com/grafana/grafana/issues/44985 is implemented.
