### ISSUE TITLE
[grafana 8.3.x][prometheus] Allowed cookies not forwarded to the datasource

### ISSUE THREAD

**Issue by alainknaebel** [grafana/grafana#44250]
**What happened**:
Starting with grafana 8.3.0, the following configuration doesn't work anymore.
![Capture d’écran du 2022-01-19 17-18-25](https://user-images.githubusercontent.com/76945466/150305595-405ddca0-b549-4975-8d2d-9966fe9b676a.png)
we expose with a public address the grafana server and the prometheus server, both are behind a oauth2-proxy instance which set a `_oauth2_proxy` cookie.
It seems that the cookie specified (`_oauth2_proxy`) in the `Allowed cookies` section is no longer passed to the the prometheus datasource, this mean that the datasource can't be fetched by the grafana server (unauthorized)
With grafana 8.2.7, the cookie was well passed to the datasource and grafana was able to fetch prometheus
To be able to have a functionnal setup, we need to hardcode the cookie header using the `Custom HTTP Headers` section

**What you expected to happen**:
Forwarding the `_oauth2_proxy` cookie to the server to be able to query the datasource

**How to reproduce it (as minimally and precisely as possible)**:
- Set a prometheus server behind a proxy using a cookie header for the authentication
- fix the name of the cookie to `_oauth2_proxy`
- Install a grafana 8.2.7 server using the prometheus datasource
- Add the `_oauth2_proxy`cookie in the `Allowed cookies` section
- Test the connection to the datasource (using the `save and test` button)
- Upgrade the grafana server to 8.3.0 
- Test the connection to the datasource (using the `save and test` button)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.x
- Data source type & version: prometheus
- OS Grafana is installed on: docker image
- User OS & Browser: firefox/chrome
- Grafana plugins: None
- Others:

**Comment by ivanahuckova** [comment]
@MasslessParticle Do you think https://github.com/grafana/grafana/pull/43922 could have fixed this issue?

**Comment by MasslessParticle** [comment]
I don't think so. Afaik, we're not setting any cookies on the outgoing http requests.

**Comment by gabor** [comment]
@josiahg what do you think, should we support this for backend datasources?

**Comment by MasslessParticle** [comment]
I think this issue was introduced when we moved to the backend Prometheus implementation before the lru cache.

**Comment by jbradleynh** [comment]
This appears to be a similar case related to our issue as well https://github.com/grafana/grafana/issues/46033

**Comment by till** [comment]
Doesn't work in 8.4.1 either. What is the proposed solution?

**Comment by pmint93** [comment]
#49541 Only solve half of the problem. We still experiencing this bug with variables. Details:

Grafana version: v9.2.7
Datasource: configured to forward session cookie
Dashboard variable type: query
My datasource does not support [labels API](https://github.com/grafana/grafana/blob/main/docs/sources/whatsnew/whats-new-in-v9-2.md#match-parameter-support-in-prometheus-labels-api) then Grafana use `/api/v1/series`

The result:

![image](https://user-images.githubusercontent.com/7886909/207807664-f7dbe920-ef6e-45cc-b2a2-544b142ff184.png)

As you can see `/api/v1/query` is working fine (thanks to #49541), but `/api/v1/series` fail (due to no session forwarded)

**Comment by marefr** [comment]
@pmint93 would suggest trying Grafana 9.3.x
