### ISSUE TITLE
CSV export not putting all the fields

### ISSUE THREAD

**Issue by ajijohn** [grafana/grafana#4425]
Grafana Admin
v 3.0.0-pre1

Using InfluxDB
Mac OSX - EL Capitan

I'm displaying four values, but  I was expecting it'd export all the displayed columns. Is there a way to get export of what I see ?

<img width="333" alt="screen shot 2016-03-20 at 11 53 23 pm" src="https://cloud.githubusercontent.com/assets/602875/13912135/05b16818-eef7-11e5-9bc8-027668406216.png">

**Comment by torkelo** [comment]
are not getting a csv file with all your series, is one series missing?

**Comment by ajijohn** [comment]
Apologies, we can close this, the rows are stacked by measurement, and its all there.(somehow I missed that).
