### ISSUE TITLE
Tempo->Splunk logs (similar to Loki)

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#44256]
Requests from bank: showing Splunk logs in Tempo traces (we do this for Loki already), and adding link-to-trace from Splunk logs to Tempo.Discuss with Squad and update @Ward as SE on project

**Comment by hugohaggmark** [comment]
@meanmina this is a friendly reminder to add appropriate labels to make the issue triage smoother for people on issue triage. Thank you 🙏
