### ISSUE TITLE
Loki back-end migration

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#44254]
Include performance considerations (based on learnings from prometheus) and also direct access deprecation(notify future deprecation in release notes and mark for deprecation in 9.0)

**Comment by hugohaggmark** [comment]
@meanmina this is a friendly reminder to add appropriate labels to make the issue triage smoother for people on issue triage. Thank you 🙏

**Comment by gabor** [comment]
the "main" part of this is done, for the rest i created two new separate issues:
https://github.com/grafana/grafana/issues/49501
https://github.com/grafana/grafana/issues/49789
