### ISSUE TITLE
Prometheus: $__rate_interval interpolation issue

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#44251]
**What happened**:

@svs1979  https://github.com/grafana/grafana/issues/44198#issuecomment-1016443182
Happens when using $interval etc. in the query itself too. Errors occur on panels with some PromQL rate(...[$__rate_interval]):
bad_data: parse error at char xxx: bad duration syntax "1m1"

@carboneater https://github.com/grafana/grafana/issues/44198#issuecomment-1016449509
Same error here with 8.3.4 OSS, using $__rate_interval

@kaibaesler https://github.com/grafana/grafana/issues/44198#issuecomment-1016739378
Same error here with 8.3.4 CE, using $__rate_interval

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Prometheus
- OS Grafana is installed on: 

Ubuntu 18.04.6 LTS
APT-Sources: https://packages.grafana.com/oss/deb stable/main amd64 Packages

Ubuntu 20.04.3, Grafana was at 8.3.4

**Comment by ivanahuckova** [comment]
@svs1979 @carboneater @kaibaesler Could you please send full query request, response, error and possibly server errors from when the issue happens. We have tried to reproduce it locally, but we couldn't reproduce the issue.

**Comment by kaibaesler** [comment]
@ivanahuckova here we go:

server logs:

> Jan 20 14:12:44 grafana grafana-server[3666]: t=2022-01-20T14:12:44+0100 lvl=eror msg="Range query failed" logger=tsdb.prometheus query="rate(node_network_receive_bytes_total{device=\"br0\"}[1m0s])" err="bad_data: 1:53: parse error: bad duration syntax: \"1m0\""
> Jan 20 14:12:44 grafana grafana-server[3666]: t=2022-01-20T14:12:44+0100 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/ds/query status=400 remote_addr=192.168.2.106 time_ms=4 size=88 referer="https://grafana.example.com/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Prometheus%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:false,%22expr%22:%22rate(node_network_receive_bytes_total%7Bdevice%3D%5C%22br0%5C%22%7D%5B1m%5D)%22%7D%5D"

query:

> {
>   "request": {
>     "url": "api/ds/query",
>     "method": "POST",
>     "data": {
>       "queries": [
>         {
>           "refId": "A",
>           "key": "Q-3f97c44c-e8cb-4ea6-8c73-2019e3ffe60a-0",
>           "instant": true,
>           "range": true,
>           "exemplar": false,
>           "expr": "rate(node_network_receive_bytes_total{device=\"br0\"}[$__rate_interval])",
>           "datasource": {
>             "uid": "XLqDXmv7z",
>             "type": "prometheus"
>           },
>           "queryType": "timeSeriesQuery",
>           "requestId": "Q-3f97c44c-e8cb-4ea6-8c73-2019e3ffe60a-0A",
>           "utcOffsetSec": 3600,
>           "legendFormat": "",
>           "interval": "",
>           "datasourceId": 1,
>           "intervalMs": 15000,
>           "maxDataPoints": 2057
>         }
>       ],
>       "range": {
>         "from": "2022-01-20T12:12:44.431Z",
>         "to": "2022-01-20T13:12:44.431Z",
>         "raw": {
>           "from": "now-1h",
>           "to": "now"
>         }
>       },
>       "from": "1642680764431",
>       "to": "1642684364431"
>     },
>     "hideFromInspector": false
>   },
>   "response": {
>     "results": {
>       "A": {
>         "error": "bad_data: 1:53: parse error: bad duration syntax: \"1m0\"",
>         "refId": "A"
>       }
>     }
>   }
> }
>

**Comment by ivanahuckova** [comment]
@kaibaesler in `rate(node_network_receive_bytes_total{device="br0"}[12d12h])` do you input and run it as `rate(node_network_receive_bytes_total{device="br0"}[12d12h])` or `rate(node_network_receive_bytes_total{device="br0"}[$__rate_interval])`?

**Comment by gabor** [comment]
@kaibaesler just to clarify: if you paste that query ( `rate(node_network_receive_bytes_total{device="br0"}[12d12h])` ) in grafana, let's say in explore-mode, you get that error-message?

for reference, i just tried it on an empty prometheus database with grafana8.3.4, and i did not get an error message (of course i got no data returned, but also no error)

**Comment by kaibaesler** [comment]
@ivanahuckova: the "12d12h" is literal input, the query is exactly as I posted it.
@gabor: yes, I tried exactly that query in the explorer, see screenshot

<img width="655" alt="Bildschirmfoto 2022-01-20 um 15 08 32" src="https://user-images.githubusercontent.com/199007/150354690-ae5b434f-9d79-459b-ae14-a5079404ca86.png">

**Comment by gabor** [comment]
@kaibaesler thanks for the info, this is very strange.

some questions:
1. is this grafana 8.3.4?
2. is this a normal prometheus database or perhaps an another prometheus-compatible database?
3. what is your prometheus version?
4. is there something "between" grafana and prometheus? a proxy perhaps?

thanks!

**Comment by carboneater** [comment]
Here's my take:
Query: I'm assuming using `inspect > Query`
```json
{
  "request": {
    "url": "api/ds/query",
    "method": "POST",
    "data": {
      "queries": [
        {
          "exemplar": true,
          "expr": "sum(rate(Position{instance=\"acc-app-2\"}[$__rate_interval])) by (processName, instance)",
          "interval": "",
          "intervalFactor": 1,
          "legendFormat": "{{processName}}",
          "refId": "A",
          "datasource": {
            "uid": "000000001",
            "type": "prometheus"
          },
          "queryType": "timeSeriesQuery",
          "requestId": "13A",
          "utcOffsetSec": -18000,
          "datasourceId": 1,
          "intervalMs": 15000,
          "maxDataPoints": 916
        }
      ],
      "range": {
        "from": "2022-01-20T14:29:15.365Z",
        "to": "2022-01-20T14:34:15.365Z",
        "raw": {
          "from": "now-5m",
          "to": "now"
        }
      },
      "from": "1642688955365",
      "to": "1642689255365"
    },
    "hideFromInspector": false
  },
  "response": {
    "results": {
      "A": {
        "error": "bad_data: parse error at char 41: bad duration syntax: \"1m0\"",
        "refId": "A"
      }
    }
  }
}
```

Server Log:
```
t=2022-01-20T09:34:18-0500 lvl=eror msg="Range query failed" logger=tsdb.prometheus query="sum(rate(Position{instance=\"acc-goa-gps-1\"}[1m0s])) by (processName,instance)" err="bad_data: parse error at char 45: bad duration syntax: \"1m0\""
```

Pasting the litteral query in Explore
![image](https://user-images.githubusercontent.com/1527214/150359789-2de62efa-5ec3-4c7c-97dc-7a1bc6dbd557.png)

Even running it directly in Prometheus yields the same error
![image](https://user-images.githubusercontent.com/1527214/150360051-6d546f98-0cc2-4cc4-918f-5619f32802c9.png)


> 1. is this grafana 8.3.4?
Yes.
```
$ grafana-server -v
Version 8.3.4 (commit: a551d74b11, branch: HEAD)
```
```
Package: grafana
Version: 8.3.4
Priority: extra
Section: default
Maintainer: contact@grafana.com
Installed-Size: 245 MB
Depends: adduser, libfontconfig1
Homepage: https://grafana.com
License: AGPLv3
Vendor: Grafana
Download-Size: 72.7 MB
APT-Manual-Installed: yes
APT-Sources: https://packages.grafana.com/oss/deb stable/main amd64 Packages
Description: Grafana
```
> 2. is this a normal prometheus database or perhaps an another prometheus-compatible database?
Normal Prometheus
> 3. what is your prometheus version?
```
$ prometheus --version
prometheus, version 2.1.0+ds (branch: debian/sid, revision: 2.1.0+ds-1)
  build user:       pkg-go-maintainers@lists.alioth.debian.org
  build date:       20180121-21:30:42
  go version:       go1.9.2
```
> 4. is there something "between" grafana and prometheus? a proxy perhaps?
Nothing. Grafana calls prometheus on its 9090 port

**Comment by kaibaesler** [comment]
I can confirm that.
After upgrading prometheus to v2.31 the error message is gone and the charts are working again.

Thanks for your support!

**Comment by ivanahuckova** [comment]
@carboneater @svs1979 are you able to update your prometheus to v2.22.0+ ?

**Comment by svs1979** [comment]
@ivanahuckova Prometheus is on 2.31.1
I guess the culprit is Promxy here, might be it hasn't been updated for some time. I'll take a look, update if possible and come back here

**Comment by carboneater** [comment]
@ivanahuckova 
I often resent Ubuntu basically abandoning its LTS releases update-wise...
https://packages.ubuntu.com/search?keywords=prometheus&searchon=names&suite=all&section=all

However, if updating Prometheus is the way to solve this issue, then that's on me.

Thanks for the help!

**Comment by ivanahuckova** [comment]
I am closing the issue as this seems like an issue with  pre v2.22.0 versions of Prometheus. Updating to v2.22.0+ Prometheus fixes the issue.

**Comment by svs1979** [comment]
I can also confirm that upgrading Promxy solved the issue for us.

**Comment by chfast** [comment]
> I am closing the issue as this seems like an issue with pre v2.22.0 versions of Prometheus. Updating to v2.22.0+ Prometheus fixes the issue.

Nice, but what if you cannot upgrade prometheus? Do you know what the core issues is? This bug in particular breaks Ubuntu 20.04 LTS.

**Comment by ivanahuckova** [comment]
What we could do is change all ranges to seconds or milliseconds because with pre-v2.22.0 even 1m30s won't work. +cc @grafana/observability-metrics

**Comment by kaibaesler** [comment]
> > I am closing the issue as this seems like an issue with pre v2.22.0 versions of Prometheus. Updating to v2.22.0+ Prometheus fixes the issue.
> 
> Nice, but what if you cannot upgrade prometheus? Do you know what the core issues is? This bug in particular breaks Ubuntu 20.04 LTS.

On Ubuntu 20.04 LTS you could switch to the snap version: `snap info prometheus`.

**Comment by chfast** [comment]
> On Ubuntu 20.04 LTS you could switch to the snap version: `snap info prometheus`.

This seems to be bad advice. The snap prometheus is not maintained by the prometheus authors but by Canonical. It is already ~18 releases behind what indicates it might have been abandoned.

**Comment by DasSkelett** [comment]
> > On Ubuntu 20.04 LTS you could switch to the snap version: `snap info prometheus`.
> 
> This seems to be bad advice. The snap prometheus is not maintained by the prometheus authors but by Canonical. It is already ~18 releases behind what indicates it might have been abandoned.

To be fair, still a lot better than the apt package (maintained by Canonical as well), which is at [2.15.2](https://packages.ubuntu.com/search?keywords=prometheus&searchon=names&exact=1&suite=focal&section=all) compared to [2.28.1](https://snapcraft.io/prometheus) from the Snap store.
That said, I cannot recommend anyone to use snap.

I for one have fixed this by switching the base system to Fedora, which ships much more up to date releases of their packages.

**Comment by carboneater** [comment]
> > > On Ubuntu 20.04 LTS you could switch to the snap version: `snap info prometheus`.
> > 
> > 
> > This seems to be bad advice. The snap prometheus is not maintained by the prometheus authors but by Canonical. It is already ~18 releases behind what indicates it might have been abandoned.
> 
> To be fair, still a lot better than the apt package (maintained by Canonical as well), which is at [2.15.2](https://packages.ubuntu.com/search?keywords=prometheus&searchon=names&exact=1&suite=focal&section=all) compared to [2.28.1](https://snapcraft.io/prometheus) from the Snap store. That said, I cannot recommend anyone to use snap.
> 
> I for one have fixed this by switching the base system to Fedora, which ships much more up to date releases of their packages.

Same here, I'm rebuilding over Debian.
And taking advantage of all of Grafana-supplied example compose files to rebuild my observability stack over docker-compose.
I believe these images are maintained by the official projects, so that should prevent this kind of issues for a good while...

**Comment by ZhenyaPav** [comment]
I am having this issue right now:
```
Ubuntu 22 LTS
Prometheus 2.31.2
Grafana 11.1.4
https://grafana.com/grafana/dashboards/14420-mikrotik-monitoring/
```
The query is `irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8`, if I replace `__rate_interval` with `__interval`, it works (though I don't know if the data is correct)
