### ISSUE TITLE
I dont get the option for influx0.10 in grafana 2.6 

### ISSUE THREAD

**Issue by areebahmushtaq** [grafana/grafana#4426]
I have upgraded the influx to 0.10 from 0.9 , currently i have Grafana version 2.6. But i dont see the option to take Influx version 0.10 from grafana web page's data source in 'Type' option i have ony 0.8 and 0.9. How do i get 0.10 there. Whereas on my system ( **Ubuntu 14.04.1 LTS (GNU/Linux 3.13.0-32-generic x86_64)**) if i type :influx i get 
```
Connected to http://localhost:8086 version 0.10.0
InfluxDB shell 0.10.0
```
which seems fine. What am i missing?

**Comment by torkelo** [comment]
InfluxDB 0.10 was not released when 2.6 was released, use the InfluxDB 0.9 data source it will work :)
