### ISSUE TITLE
 [Bug] InfluxDB Error: undefined

### ISSUE THREAD

**Issue by runner-mei** [grafana/grafana#4428]
While influxdb can't connect, and test influxdb source, and show as:
![_2016-02-29t03-23-29 641z](https://cloud.githubusercontent.com/assets/1052632/13914701/15c66200-ef8b-11e5-94c3-4a41514bdac5.png)

I hope show "InfluxDB Error: No connection could be made because the target machine actively
 refused it."

* What grafana version are you using?

      newest version, I am copy it from git

* What datasource are you using?

     Influxdb

* What OS are you running grafana on?

   windows

**Comment by torkelo** [comment]
whats the http url (and port) you specified for InfluxDB? Is it reachable from the same computer as you have grafana running? Please open questions like this in the mailing list

**Comment by runner-mei** [comment]
I close influxdb and run grafana.
Test the datasource and show this.

I hope show connect error.

**Comment by bergquist** [comment]
I'm working on improving the error message right now. Will commit soon :)

**Comment by runner-mei** [comment]
Oooo, Datasource is proxy mode.
