### ISSUE TITLE
Identify and document a minimal and (hopefully) stable set of config options required by Intent API

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#44291]
The Intent API will be an experimental feature for some time, and likely an opt-in feature for some time after that. Consequently, it's a hard prerequisite for any kind of first milestone that it be placed behind some config options, and maybe a feature flag as well.

As part of the overall focus on effective communication around this project, i think it's worth being intentional about this config from the outset - it's a key part of the public face the project will present. Let's use this issue to discuss possible configuration options that may be needed.

The main goal with trying to think ahead to the future - usually a ridiculous exercise - is to simply enumerate any obviously-avoidable situations where a valid config becomes invalid, or where the meaning of a given config changes based on some weird defaulting behavior.

From a configuration perspective, the project is likely to have three distinct phases:

* **Initial prototyping:** what we're doing now. No new HTTP API is exposed, no config is needed.
* **Early experiment to mature alternative API:** API runs on separate port. Implementation will certainly rely on external kube apiserver initially; eventually, we may embed it directly in the backend.
* **Canonical API:** the eventual, _eventual_ goal is that the Intent API just becomes the Grafana backend API, and we retire the old one completely.

Given this, it seems like there are a few possible bits of config:

* **On/Off toggle:** a simple boolean that toggles the Intent API on or off. We might technically be able to do without this and operate on inference, but being explicit seems better. It would only become not-useful in the final phase, when the Intent API just becomes the API.
* **Bind addr:** we are exposing an HTTP server, after all.
* **external apiserver address:** a string containing the URL of an external apiserver that the Grafana instance should rely on. Definitely necessary right from the outset. Only becomes unnecessary if/when we develop an embedded approach.
* **external apiserver credentials:** used to auth to the external apiserver. Will contain secret material! Required only if address is non-empty.

What am i missing?

**Comment by sdboyer** [comment]
Gonna toss this one your way, @radiohead - seems naturally aligned with the high-level planning you're thinking about this week.

**Comment by radiohead** [comment]
Closed by #46005
