### ISSUE TITLE
Refactor threshold editor out of grafana-ui

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#44298]
Move threshold editor to be in public directory instead of inside of grafana-ui package in order to reduce surface area of grafana-ui

**Comment by hugohaggmark** [comment]
@nmarrs this is a friendly reminder to add appropriate labels to make the issue triage smoother for people on issue triage. Thank you 🙏

**Comment by nmarrs** [comment]
@hugohaggmark Thanks for the reminder, wasn't sure what label this would fit under so it's good to know we have a `type/chore` label
