### ISSUE TITLE
How to set alias for grouped query?

### ISSUE THREAD

**Issue by lcrenix** [grafana/grafana#4429]
I have an InfluxDB query that has a group by clause, and the results returned were categorized as measurement.function.tag:values. for example: code_spot_stat.mean {svn_name: Topic Yuanfang's code}code_spot_stat.mean {svn_name: Yun V3}

now, I want to set the legend just display the value of the tag, no measurement name and function name, how do I use the Alias Naming Pattern?

**Comment by torkelo** [comment]
http://docs.grafana.org/datasources/influxdb/#alias-patterns

please use the mailing list for questions
