### ISSUE TITLE
Chained variables don't refresh

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#44304]
**What (didn't) happened**:

When using the child in a panel of a series of chained variables, the panel doesn't update when the variable does.

**What you expected to happen**:

When changing the variable, the panel using it should update as well.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a [JSON API data source](https://grafana.com/plugins/marcusolsson-json-datasource) (1.3.0).
2. Import the following dashboard.

<details>
<summary>
<strong>DASHBOARD JSON</strong>
</summary>
<pre>
{
  "__inputs": [
    {
      "name": "DS_TV_MAZE",
      "label": "TV Maze",
      "description": "",
      "type": "datasource",
      "pluginId": "marcusolsson-json-datasource",
      "pluginName": "JSON API"
    }
  ],
  "__elements": [],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.3.3"
    },
    {
      "type": "datasource",
      "id": "marcusolsson-json-datasource",
      "name": "JSON API",
      "version": "1.3.0"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1642754355432,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "marcusolsson-json-datasource",
        "uid": "${DS_TV_MAZE}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "8.3.3",
      "targets": [
        {
          "cacheDurationSeconds": 300,
          "datasource": {
            "type": "marcusolsson-json-datasource",
            "uid": "${DS_TV_MAZE}"
          },
          "fields": [
            {
              "jsonPath": "$.name"
            },
            {
              "jsonPath": "$.airdate",
              "language": "jsonpath",
              "name": ""
            },
            {
              "jsonPath": "$.runtime",
              "language": "jsonpath",
              "name": ""
            },
            {
              "jsonPath": "$.summary",
              "language": "jsonpath",
              "name": ""
            }
          ],
          "method": "GET",
          "params": [
            [
              "season",
              "${season}"
            ],
            [
              "number",
              "${episode}"
            ]
          ],
          "queryParams": "",
          "refId": "A",
          "urlPath": "/shows/${show}/episodebynumber"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "refresh": "",
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "216",
          "value": "216"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "show",
        "options": [
          {
            "selected": true,
            "text": "216",
            "value": "216"
          }
        ],
        "query": "216",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "current": {},
        "datasource": {
          "type": "marcusolsson-json-datasource",
          "uid": "${DS_TV_MAZE}"
        },
        "definition": "$.[*].number",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "season",
        "options": [],
        "query": {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "$.[*].number"
            }
          ],
          "method": "GET",
          "queryParams": "",
          "urlPath": "/shows/${show}/seasons"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      },
      {
        "current": {},
        "datasource": {
          "type": "marcusolsson-json-datasource",
          "uid": "${DS_TV_MAZE}"
        },
        "definition": "$.[?(@.season == ${season})].number",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "episode",
        "options": [],
        "query": {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "$.[?(@.season == ${season})].number"
            }
          ],
          "method": "GET",
          "params": [],
          "queryParams": "",
          "urlPath": "/shows/${show}/episodes"
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "TV Shows",
  "uid": "n4o7BRx7k",
  "version": 4,
  "weekStart": ""
}
</pre>
</details>

3. Change the `season` variable and watch the `episode` variable update.
4. Change the `episode` variable. The panel doesn't reflect the new value. Only if you reload the dashboard.

**Anything else we need to know?**:

Works in 8.2.0.

Related issues:

https://github.com/marcusolsson/grafana-json-datasource/issues/95
https://github.com/marcusolsson/grafana-json-datasource/issues/155

**Environment**:

- Grafana version: 8.3.3
- Data source type & version: JSON API 1.3.0
- OS Grafana is installed on: Official Docker image on macOS 12.1
- User OS & Browser: Firefox on macOS 12.1

**Comment by ashharrison90** [comment]
hey @marcusolsson 👋 

we tried with this dashboard json and couldn't repro, everything seems to work as expected 🤔 
<details>
   <summary>JSON dashboard</summary>
   
```json
{
  "__inputs": [
    {
      "name": "DS_BREAKING_BAD",
      "label": "Breaking Bad",
      "description": "",
      "type": "datasource",
      "pluginId": "marcusolsson-json-datasource",
      "pluginName": "JSON API"
    }
  ],
  "__elements": [],
  "__requires": [
    {
      "type": "grafana",
      "id": "grafana",
      "name": "Grafana",
      "version": "8.5.0-pre"
    },
    {
      "type": "datasource",
      "id": "marcusolsson-json-datasource",
      "name": "JSON API",
      "version": "1.3.1"
    },
    {
      "type": "panel",
      "id": "table",
      "name": "Table",
      "version": ""
    }
  ],
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": null,
  "iteration": 1644402746752,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "marcusolsson-json-datasource",
        "uid": "${DS_BREAKING_BAD}"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "align": "auto",
            "displayMode": "auto"
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 10,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "footer": {
          "fields": "",
          "reducer": [
            "sum"
          ],
          "show": false
        },
        "showHeader": true
      },
      "pluginVersion": "8.5.0-pre",
      "targets": [
        {
          "cacheDurationSeconds": 300,
          "datasource": {
            "type": "marcusolsson-json-datasource",
            "uid": "${DS_BREAKING_BAD}"
          },
          "fields": [
            {
              "jsonPath": "$.0.title",
              "language": "jsonpath",
              "name": ""
            }
          ],
          "method": "GET",
          "params": [
            [
              "episode",
              "${episode}"
            ],
            [
              "season",
              "${season}"
            ]
          ],
          "queryParams": "",
          "refId": "A",
          "urlPath": "/${episode}"
        }
      ],
      "title": "Panel Title",
      "type": "table"
    }
  ],
  "refresh": "",
  "schemaVersion": 35,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": [
      {
        "current": {
          "selected": false,
          "text": "216",
          "value": "216"
        },
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "show",
        "options": [
          {
            "selected": true,
            "text": "216",
            "value": "216"
          }
        ],
        "query": "216",
        "queryValue": "",
        "skipUrlSync": false,
        "type": "custom"
      },
      {
        "current": {},
        "datasource": {
          "type": "marcusolsson-json-datasource",
          "uid": "${DS_BREAKING_BAD}"
        },
        "definition": "$.[*].season",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "season",
        "options": [],
        "query": {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "$.[*].season"
            }
          ],
          "method": "GET",
          "queryParams": "",
          "urlPath": ""
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      },
      {
        "current": {},
        "datasource": {
          "type": "marcusolsson-json-datasource",
          "uid": "${DS_BREAKING_BAD}"
        },
        "definition": "$.[?(@.season == ${season})].episode_id",
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "episode",
        "options": [],
        "query": {
          "cacheDurationSeconds": 300,
          "fields": [
            {
              "jsonPath": "$.[?(@.season == ${season})].episode_id"
            }
          ],
          "method": "GET",
          "params": [],
          "queryParams": "",
          "urlPath": ""
        },
        "refresh": 1,
        "regex": "",
        "skipUrlSync": false,
        "sort": 0,
        "type": "query"
      }
    ]
  },
  "time": {
    "from": "now/y",
    "to": "now/y"
  },
  "timepicker": {},
  "timezone": "",
  "title": "TV Shows",
  "uid": "n4o7BRx7k",
  "version": 9,
  "weekStart": ""
}
```
</details>

**Comment by bode689** [comment]
Hi all,
I just realized that _parent-var_ does update correctly if it is referenced inside the body of _child-var_.
Unfortunately, if the query of _child-var_ is a GET request and we need to pass _parent-var_ as a Param , it updates only after a manual refresh.

Hope it helps

**Comment by ideasman69** [comment]
I've got the same issue with my dashboards using @marcusolsson's amazing JSON API.

All Grafana versions up to 8.2.7 work as expected:
- select a variable from the dropdown
- chained variables and dashboard update accordingly

From 8.3.0 upwards (including 8.4.x versions), variables / dashboards just don't attempt to refresh using newly selected variables. 

I have some dashboards that use SQL to populate the varible dropdowns and some dashboard panels, the SQL variables and panels all update as expected - but on those same dashboards, any panels using the JSON API plugin don't refresh.

**Comment by hugohaggmark** [comment]
@ideasman69 that's great!! Care to share any dashboards that aren't working anymore?

**Comment by torkelo** [comment]
Strange, testing 8.4 I am unable to replicate

**Comment by torkelo** [comment]
the dashboard you linked the variables the variable query is mssql , and if I change the first variable (tag), the host variable query executes.

**Comment by ideasman69** [comment]
I mentioned that in a [previous comment](https://github.com/grafana/grafana/issues/44304#issuecomment-1047679428), any SQL panels update when a new variable is selected. JSON API panels do not - but only from 8.3.0 and upwards.

**Comment by joshhunt** [comment]
Thanks for the additional comments. We weren't able to reproduce the issue with @marcusolsson's original dashboard, but @bode689's comment about the issue happening only when variables are in the Params field helped us reproduce.

The issue is due to the specific query structure JSON API data source uses and how it confuses Grafana's variable dependency tracking. This is a bug in Grafana, not JSON API data source.

Because a query can essentially be any arbitrary object, its hard for Grafana to know if a query contains a specific variable. The code stringifies the query object to JSON and performs regex matches on the JSON string to find five variable syntaxes: `$season`, `[[var2]]`, `[[var2:fmt2]]`, `${var3}`, or `${var3:fmt3}`.

When the JSON API params are stringified, it will look something like `{"params":[["myParam","$season"]]}`. The regex for the double-brackets syntax is very generous (essentially `\[\[(.*\)]\]`), and the array-of-tuples structure of params looks just enough like a variable to cause it to "hide" the variable inside and cause the issue.

We're still looking into a fix - this code is in a tough spot that can affect dashboard performance, so we want to make sure we don't cause any regressions. On the other hand, the `[[var]]` syntax has been deprecated for nearly two years.
