### ISSUE TITLE
[Bug] Scripted dashboard still accessible after deleting the source file

### ISSUE THREAD

**Issue by gou1** [grafana/grafana#4430]
Hey,

I'm using grafana 2.6.0 on ubuntu 15.10 with a Graphite datasource.

I previously had a scripted dashboard located at `/usr/share/grafana/scripts/dashboards/dashboard.js` and therefore accessible at `http://grafana-url/dashboard/script/dashboard.js`.

If I delete the source file and restart grafana-server, the dashboard is still accessible ; how can I ensure its deletion to prevent users from still accessing those deleted dashboards?

Thanks!

**Comment by torkelo** [comment]
maybe clear our your browser cache? grafana-server does not cache or store it anywhere

**Comment by gou1** [comment]
Ah yes my bad, I was deleting at `/usr/share/grafana/scripts/dashboards` but the actual graphs are located at `/usr/share/grafana/public/dashboards`. 

Thanks!
