### ISSUE TITLE
Docs feedback: /alerting/unified-alerting/alerting-rules/alert-annotation-label.md

### ISSUE THREAD

**Issue by mloiseleur** [grafana/grafana#44318]
Hi,

Would this be possible to have a list of currently supported annotations by Grafana 8 Alerting ?

It's not very easy to find that the dashboard links can be made with __dashboardUid__, for instance.

Thanks,

**Comment by zuchka** [comment]
cc @achatterjee-grafana

**Comment by achatterjee-grafana** [comment]
Apologies for the delay. Can you share the link to the documentation you are looking at?

**Comment by mloiseleur** [comment]
It's in the name of this issue, which was generated by clicking on "request doc changes" :). 

It's here : https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/alert-annotation-label/
