### ISSUE TITLE
Default datasource selection for panel causes confusion behaviour

### ISSUE THREAD

**Issue by wardbekker** [grafana/grafana#44329]
**What happened**:

Selecting the default datasource, sets the datasource in the panel to null, and this causes confusing behaviour. When you promote another datasource as the default, it breaks all panels that have the default datasource as a selection. 

https://user-images.githubusercontent.com/35603/150552028-b6dad329-6efb-4f21-917f-1049d54a8dbf.mov

**What you expected to happen**:

Default datasource selection will no set the panel datasource to null, but just have the same behaviour as any other datasource selection

**How to reproduce it (as minimally and precisely as possible)**:

See video

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by wardbekker** [comment]
This also seems to results in issues with exported dashboards. When importing, it does not show a datasource picker for dashboards using the default datasource.

**Comment by BitProcessor** [comment]
@wardbekker a possible workaround for the export/import issue is to edit the dashboard JSON at export side, and manually add the missing datasource blocks, for example:

```
      "datasource": {
        "type": "loki",
        "uid": "P8E80F9AEF21F6940"
      },
```
Next, hit the share button, make sure to toggle `Export for sharing externally ` and you will now be asked to select the new datasource on import side.

**Comment by torkelo** [comment]
Srange, looks like we have always ignored default datasource in exporter. So not sure this has ever worked.

**Comment by jabjoe** [comment]
I've just hit this too. Took me about two hours to work out what was going on and to work round it. My fix was to manually fix the export JSON before I imported it on the other system. Just add the datasource reference to the start of each panel's block. Similiar fix as @BitProcessor as it turns out.

**Comment by natellium** [comment]
@torkelo does your PR https://github.com/grafana/grafana/pull/45132 fix this?

**Comment by torkelo** [comment]
@natellium yes
