### ISSUE TITLE
UX(): New checkbox styles

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#4432]
The checkbox styles dont fit the new form styles very well. 

Example:
![pasted_image_at_2016_03_20_05_33_pm](https://cloud.githubusercontent.com/assets/10999/13919438/c3237320-ef6d-11e5-84d0-06fbe24fcd84.png)

Alternative checkbox style:
<img width="913" alt="screen shot 2016-03-21 at 13 48 32" src="https://cloud.githubusercontent.com/assets/10999/13919475/f2943ca2-ef6d-11e5-8570-54d6bec55965.png">

Can also be made to align like other gf-form elements:

Before:
<img width="697" alt="screen shot 2016-03-21 at 13 52 00" src="https://cloud.githubusercontent.com/assets/10999/13919478/fb57b68e-ef6d-11e5-8537-358c0536b9e3.png">

After:
<img width="682" alt="screen shot 2016-03-21 at 14 02 16" src="https://cloud.githubusercontent.com/assets/10999/13919484/04cb117a-ef6e-11e5-89b6-d8743fbd3c97.png">

annimation:
![checkbox_v3](https://cloud.githubusercontent.com/assets/10999/13919493/19e3cf3e-ef6e-11e5-959f-6c494c255475.gif)

Feedback @mattttt @bulletfactory  ?

**Comment by sslupsky** [comment]
I think this is kind of cool.  :-) :+1:

**Comment by mattttt** [comment]
Talked to @torkelo about this for a bit yesterday. My main concern is a lack of affordance to let you know that it's an interactive element that toggles between 2 states. 

I think we can come up with an evolution of this idea that keep the structure/style while making it clear what it does.

**Comment by sslupsky** [comment]
Maybe if it was styled as a "button" it would be obvious that it was clickable?

Example:
![screen shot 2016-03-22 at 11 15 53 am](https://cloud.githubusercontent.com/assets/16888734/13960829/7d242ec0-f01f-11e5-90f2-9274efa09552.png)
