### ISSUE TITLE
[Bug]? Data not changing when changing template parameter

### ISSUE THREAD

**Issue by zabeloliver** [grafana/grafana#4433]
Hi, 

i have a measurment with two tags. "$com" and "$ucpin". i managed to show the right values when selecting the "$ucpin". however, changing the "$com" parameter doesn't change anything. Only when enabling the "repeat row" feature, then the graphs are displayed right.

Here is a screenshot with the query:
![2016-03-21 15_31_24-grafana - avc fan test 3](https://cloud.githubusercontent.com/assets/9071408/13922100/1fb7ed70-ef7b-11e5-8eaf-6db061453d5d.png)

i'm using grafana 2.6 with InfluxDB.

Thanks for your help and the great framework!

**Comment by torkelo** [comment]
are you sure you configured correctly? 
works here:
http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&edit

**Comment by zabeloliver** [comment]
hi, like i said, it works for the template parameter $ucpin, but not for the parameter $com. the only difference is, like you see, that $ucpin should have the possibility to display multiple selected values. with $com only one at a time. when the row with the graph has to option "repeat row" enabled, then changing the parameter $com changes the graph, otherwise not.

**Comment by torkelo** [comment]
try removing the panel and readd it again (or edit panel json and remove scopedVars), could be that you have enabled panel repeat have lingering scopedVars property (bug that should be fixed in master)

**Comment by zabeloliver** [comment]
thanks, removing "scopedVars" section from json and readding the panel did the trick!
