### ISSUE TITLE
Navigation improvements for apps

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#4434]
There are a handful of improvements necessary for apps:

- [ ] Allow App creator to specify default link when the user clicks the Main Menu items (currently goes to Plugin Overview)

- [ ] Allow App creator to link directly to dashboards. No external links right now - just pages and dashboards. 

- [ ] Add Plugin Details item to every app's menu, below an HR. This will allow the user to easily and reliably get to the details & config areas without having to hunt through the plugins section. Alternate menu text: "Plugin Overview" instead of details. 

![screenshot 2016-03-21 10 38 01](https://cloud.githubusercontent.com/assets/2886187/13922823/721ef03a-ef54-11e5-8513-f377185bfcdf.png)

- [ ] Add a Nav Bar to all app pages, to easily navigate around apps without having to access the main menu. 

![image](https://cloud.githubusercontent.com/assets/2886187/13922814/68a1da5e-ef54-11e5-9e1e-def702a107be.png)

Styles used from Dashboard picker. 

**^^ Bonus idea:** We allow app creators to specify one or two actions that appear as buttons in the dropdown. As an app creator, it is a shortcut way to encourage primary actions.

**Comment by mattttt** [comment]
Also, I'd like to see the base URL redirect somewhere within the app:

![screenshot 2016-03-21 11 31 09](https://cloud.githubusercontent.com/assets/2886187/13923836/8568743c-ef58-11e5-8b6d-8f18d18b17d1.png)

**Comment by torkelo** [comment]
worked on this, now merged pages section in plugin.json with includes section. 

You now have to new properties as well, "addToNav" , and "defaultNav" , applicable to both included pages and dashboards. 

```
 "includes": [
    {
      "type": "page",
      "name": "Home",
      "component": "HomeCtrl",
      "role": "Editor",
      "addToNav": true,
      "defaultNav": true
    },
    {
      "type": "page",
      "name": "Add Device",
      "component": "AddDeviceCtrl",
      "role": "Editor",
      "addToNav": true
    },
    {
      "type": "dashboard",
      "name": "Top Talkers",
      "path": "dashboards/top_talkers.json",
      "addToNav": true
    },
    {
      "type": "panel",
      "name": "Kentik Call To Action"
    },
    {
      "type": "panel",
      "name": "Kentik Device List"
    },
    {
      "type": "datasource",
      "name": "Kentik-ds"
    }
  ],
```

Also added divider and link to app config page, 
![image](https://cloud.githubusercontent.com/assets/10999/13929055/9a929a1e-ef98-11e5-9bba-90a37852141c.png)

Unrelated to this issue, I added icons to subnav hover menu:
![image](https://cloud.githubusercontent.com/assets/10999/13929094/c14a352c-ef98-11e5-8917-e45fb956a780.png)

**Comment by torkelo** [comment]
sorry for closing this prematurely, figured I do the most pressing bit, and leave the navbar dropdown for later (as we have done for all other pages where we have been talking about a navbar dropdown).

Created new issue for that:
https://github.com/grafana/grafana/issues/4452 

As for using plugin logo instead of plugins icon in navbar, can you open an issue for that?

**Comment by marefr** [comment]
@kmohide that's not supported, but there are an open PR from a contributor, see #11824
