### ISSUE TITLE
grafana renders values outside of panel

### ISSUE THREAD

**Issue by yellowpattern** [grafana/grafana#44351]
**What happened**: In grafana 6, when the panel to put the value in is too small for the value as well as the title, the title can be seen but the value is hidden. In grafana 8, the value for the panel is put on the screen even when the panel is too small.

**What you expected to happen**: The same behaviour as grafana 6 - for only items that are visible in the panel to be drawn on the screen.

**How to reproduce it (as minimally and precisely as possible)**: Resize a panel to a size too small to show the value, just the title.

**Anything else we need to know?**: See attachment to see how bad this is. This worked properly in grafana 6. Panels displayed here are blackmirror1-singlestat-math-panel.

This is yet another regression from earlier versions of grafana.

![Screen Shot 2022-01-23 at 9 52 27 pm](https://user-images.githubusercontent.com/24280758/150675218-41970225-552e-4352-9a55-2cad1777de10.png)

In this graphic, the values "3" and "60" belong to the two panels. In version 6, these values cannot be seen because rendering them would place them outside of the appropriate container. In version 8, these values are being rendered on the screen without regard for if they should be rendered, never mind where.

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: influxdb
- OS Grafana is installed on: CentOS
- User OS & Browser: MacOS X, Chrome
- Grafana plugins: blackmirror1-singlestat-math-panel
- Others:

**Comment by ashharrison90** [comment]
hi @yellowpattern 👋 

i can only reproduce this using the `blackmirror1-singlestat-math-panel` plugin. suggest you raise an issue on the plugin here: https://github.com/black-mirror-1/singlestat-math/issues

out of curiosity, what's your use case for making the panel so small that only the title is visible?

thanks!

**Comment by yellowpattern** [comment]
@ashharrison90 By reducing the size of the panel so that only the title is visible, it lets me have a colored box that changes per the value of the metrics but with the title of the panel visible so that I know what the color belongs to. In this case I've got several queries that I extract a value from influxdb and then use with single-stat-math to determine what color the background of the panel should be and the title of the panel is the hostname. The title of the panel is the value of a variable that's used to repeat the panel with.
