### ISSUE TITLE
Feature Request:  Waveform Math

### ISSUE THREAD

**Issue by sslupsky** [grafana/grafana#4435]
I would like to suggest a new feature in the graph panel, a "Waveform Math" tab.  This tab would allow you to perform math on one or more of the metrics returned from the query.  A trivial use case would be to add/subtract/multiply/divide two metrics together.  A more notable use case would be a signal processing function such as an Analog or Digital Filter, Fourier Transform, interpolation or other scientific or statistical signal processing technique.  Ideally, the FUNCTIONS could be a form of plugin that could be easily created by the user.

I have attached a screen shot below illustrating the concept.

Thoughts, ideas, feedback?

![grafana waveform math](https://cloud.githubusercontent.com/assets/16888734/13923096/cacc23f2-ef44-11e5-86a5-4de69f6c272b.png)

**Comment by torkelo** [comment]
will close as similar thing is already proposed in issue, https://github.com/grafana/grafana/issues/3677
