### ISSUE TITLE
Include sigv4 auth in alertmanager datasource

### ISSUE THREAD

**Issue by hussain-ujjaini** [grafana/grafana#44361]
### Discussed in https://github.com/grafana/grafana/discussions/44360

<div type='discussions-op-text'>

<sup>Originally posted by **hussain-ujjaini** January 24, 2022</sup>
Include sigv4 auth in alertmanager datasource to support aws prometheus alertmanager

<img width="566" alt="Screenshot 2022-01-24 at 1 31 35 PM" src="https://user-images.githubusercontent.com/34863783/150743948-83886aa6-135c-4088-8f2b-11513175deaf.png">

</div>

**Comment by hussain-ujjaini** [comment]
@dsotirakis Please add support for sigv4 auth in alertmanager datasource at the earliest, we are unable to use Amazon managed Prometheus alertmanager as a datasource in Grafana.

**Comment by jeromeinsf** [comment]
Prior work: https://github.com/grafana/grafana/pull/27552

**Comment by hussain-ujjaini** [comment]
@jeromeinsf sigv4auth is available for prometheus and Elasticsearch, but its not available for alertmanager datasource as i shared in the screenshot above.

**Comment by jeromeinsf** [comment]
@hussain-ujjaini agreed, I was just pointing out prior related work. Wondering if sigv4auth could be more generically implemented rather than a follow up each type a new data source is added.

**Comment by hussain-ujjaini** [comment]
agreed @jeromeinsf

**Comment by hussain-ujjaini** [comment]
@grafana-admin-it @grafana-eddie @grafana-dylan 
Any updates on this, it's really required now

**Comment by gillesdemey** [comment]
This looks like it's an alerting squad related issue, I'm not sure why it's on the metrics team backlog – tagging @armandgrillet to triage this but there is currently no bandwidth to get this done for Grafana 9.

**Comment by taleena** [comment]
Request to also backport this for 8.5.
