### ISSUE TITLE
Alerting: Filtering improvements

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#44369]
- [x] #56875
	We support two ways of searching by labels:
	  - `key=value`
	  - `{key="value"}`
Maybe we should stick to only one (probably the latter as it allows supporting commas). However, typing without brackets and quotes is faster
- [ ] Would be good to use controlled components for filter inputs if possible
- [ ] Some filters use debounce, others do not
- [ ] `SilencesFilter` could use `MatcherFilter` to avoid code duplication
- [ ] General RWD improvements

**Comment by Bilanda** [comment]
Hello, same issue with values containing dots.
I opened a [topic](https://community.grafana.com/t/heartbeat-field-name-are-invalid-in-unified-alerting/59417) on grafana's forum for further details
