### ISSUE TITLE
Search page discards search results if Starred and recents request takes longer than searching

### ISSUE THREAD

**Issue by jukeks** [grafana/grafana#44374]
**What happened**:

Searching doesn't work until Starred and recents request (`GET /api/search?query=&starred=false&skipRecent=false&skipStarred=false&folderIds=0&layout=folders&prevSort=null`) has returned. If user tries to search before that, their search result gets replaced by the Starred and recents list.

There seems to be a race condition in the UI. Could be fixed by keeping track of the order of requests and rendering only the last request's response.

**What you expected to happen**:

Be able to search while the UI allows me to search.

**How to reproduce it (as minimally and precisely as possible)**:

1. Click the Search button
2. Start typing search term before the Starred and recents response is received.
3. Search results might appear but they are replaced after Starred and recents request you see the Starred and recents list.

**Anything else we need to know?**:

In this env `GET /api/search?query=&starred=false&skipRecent=false&skipStarred=false&folderIds=0&layout=folders&prevSort=null` takes 3.3 seconds and searching with a query string `GET /api/search?query=searchterm&starred=false&skipRecent=false&skipStarred=false&layout=folders&prevSort=null` takes 500 ms.

**Environment**:
- Grafana version: 7.5.11
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: MacOS Firefox 96.0.1
- Grafana plugins: 
- Others:

**Comment by idafurjes** [comment]
Hi @jukeks, I have hard time reproducing this, would you mind trying a newer version of grafana (above 8) and reopen the issue if the problem still exists.
