### ISSUE TITLE
Azure Monitor Data Source: Selecting a variable in one field, resets the variables in other fields

### ISSUE THREAD

**Issue by wengelbrecht-grafana** [grafana/grafana#44394]
**What happened**:

Using Azure Monitor Data Source, and each field is using variables from template variables, when I select a field with a variable, it resets the other field's variables: 
![image](https://user-images.githubusercontent.com/83230950/150834333-abadb0fe-5dcb-4017-b606-bd03351fef72.png)

It's a little hard to explain by text, but in the screenshot above you have multiple Azure fields like Subscription, Resource Type, Resource Group, Resource Name and so on. So if in any of these fields you're using a variable, and you select a template variable as the value, then it resets the other field's variables back to blank. Then you have to reset all the fields again. 

**What you expected to happen**:
The other fields' variables should not be reset to blank, they should remain if they are template variables. 

**How to reproduce it (as minimally and precisely as possible)**:
The best way to reproduce this is the set all the fields with template variable names, and then change the subscription field to something else. It will reset all the other fields' values back to blank. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana Cloud, Enterprise version, currently 8.3.3
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Latest Chrome

**Comment by sarahzinger** [comment]
Hey Apologies this has taken me a while. 

I've done some work on this, and started to refactor what we have quite a bit, but after some more thought I've decided that a lot of the awkwardness of this feature should be resolved when we add the Resource Picker to Metrics https://github.com/grafana/grafana/issues/44439, which we're hoping to release with Grafana 9.

I'm going to put this in the backlog for now, and when this feature is released we can close this bug with it.

**Comment by andresmgot** [comment]
I was about to close this since the resource picker is now available for Metrics but notice a similar bug with the namespace not being cleared out after changing the resource:
![Peek 2022-06-06 10-04](https://user-images.githubusercontent.com/4025665/172121009-99afcbbf-4077-4eb2-a0d2-1b1a0fd43373.gif)
