### ISSUE TITLE
Curl authorization

### ISSUE THREAD

**Issue by jedi132000** [grafana/grafana#4439]
Thank you! For helping us make Grafana even better.

To help us respond to your issues faster, please make sure to add as much information as possible.

If this issue is about a plugin, please open the issue in that repository.

Start your issues title with [Feature Request] / [Bug] / [Question] or no tag if your unsure.

Ex
* What grafana version are you using? 
2.6
* What datasource are you using?
grahite
* What OS are you running grafana on?
ubuntu14.04

curl -H "Authorization: Bearer your_key_above" http://your.grafana.com/api/dashboards/db/mydash

I am getting authorization errors.

{"message":"Invalid Basic Auth Header"}ubuntu@ip-172-31-46-103:~/myhubot$

**Comment by jedi132000** [comment]
sorry the datasource is Grafana.

**Comment by bergquist** [comment]
Did you replace "Invalid Basic Auth Header" with the api key from grafana?
