### ISSUE TITLE
New navbar doesn't allow nested menus as before

### ISSUE THREAD

**Issue by fabio-silva** [grafana/grafana#44406]
**What happened**: When having children of children (and more) links in the navbar, only the top-level children are rendered.

**What you expected to happen**: As with the previous version (`TopSection`), sub-menus should be rendered recursively.

**How to reproduce it (as minimally and precisely as possible)**: 
- Go to `pkg/api/index.go`;
- Add some nested children or change one of the existing to check the behaviour. For example, adding children to "Data Sources" on `configNodes`;
- When navigating, "Data Sources" item is rendered, but not its children.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.3.3
- OS Grafana is installed on: OSX

**Comment by torkelo** [comment]
Can you show a screenshot of this? I have no memory of nested menus in the sidebar

**Comment by fabio-silva** [comment]
> Can you show a screenshot of this? I have no memory of nested menus in the sidebar

Sure, here it is:

![Screenshot 2022-01-25 at 09 47 56](https://user-images.githubusercontent.com/4190654/150952969-bc69d834-a094-4386-b8f8-07ee45979328.png)

**Comment by fabio-silva** [comment]
@torkelo actually, I just found out this feature wasn't implemented by Grafana, sorry for this :/
You can close this issue.
