### ISSUE TITLE
Turn off Grafana autocomplete

### ISSUE THREAD

**Issue by Madhu94** [grafana/grafana#4441]
I'm using Grafana 2.6.0 with influxdb 0.11 data source. Is there any way to turn off autocomplete feature?

**Comment by torkelo** [comment]
no. there is no option for this. 

I guess you talking about the measurement autocomplete? How many measurements do you have?

**Comment by Madhu94** [comment]
Choosing "Switch Editor Mode" worked for me. I was talking about the where clause autocomplete.

Thanks
