### ISSUE TITLE
No points rendered after zoom

### ISSUE THREAD

**Issue by marknorton-sabio** [grafana/grafana#44413]
**What happened**: Zooming into a time series graph eventually stops rendering points even though there are data points within range

**What you expected to happen**: Points are rendered

**How to reproduce it (as minimally and precisely as possible)**: [Demo snapshot](https://marknortonsabio.grafana.net/dashboard/snapshot/3I688QBdrqw17HadLvJDWUvNnROxkG2X?orgId=0)
Zoom into this data down to about a 30 second timeframe, points will not be rendered, Y-axis will drop to a max of 100ms even though there are data points above that range.

![zoom_bug_capture](https://user-images.githubusercontent.com/95362420/150952669-9621d7bf-da65-405d-a391-6c064eb46863.gif)

**Anything else we need to know?**: This graph is using the infinity plugin to transform the data. When in edit view, switching to table display does show the data points that should be rendered.

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Infinity plugin, this example uses inline CSV data
- OS Grafana is installed on: Tested on Grafana Cloud and using Grafana 8.3.4 Docker image
- User OS & Browser: MacOS Safari & Chrome
- Grafana plugins: Infinity plugin 0.8.0
- Others:

**Comment by leeoniya** [comment]
@marknorton-sabio try sorting your x axis dates in ascending order.

**Comment by marknorton-sabio** [comment]
I thought they were sorted but I've added an explicit sort using Infinity and that seems to have fixed the issue. Thank you.
