### ISSUE TITLE
jaeger datasource:enable query with grafana variable

### ISSUE THREAD

**Issue by zdyj3170101136** [grafana/grafana#44422]
### Discussed in https://github.com/grafana/grafana/discussions/44421

<div type='discussions-op-text'>

<sup>Originally posted by **zdyj3170101136** January 25, 2022</sup>
jaeger datasource do not support grafana variable:
![截屏2022-01-25 下午8 03 20](https://user-images.githubusercontent.com/52686065/150973675-f1067916-6b72-49f4-87a6-9d73164a5d4a.png)

It is very useful for us if jaeger datasource service and operation support grafana variable just like prometheus datasource:
![截屏2022-01-25 下午8 04 57](https://user-images.githubusercontent.com/52686065/150973899-73ee861d-111e-4144-817b-c5ddc26fdd0d.png)

</div>

**Comment by nicolastakashi** [comment]
@joey-grafana is there anything that I can do to help with this?

If you think that makes sense, we can discuss the implementation and I'm free to send this contribution.

**Comment by joey-grafana** [comment]
Hello, thank you so much for reaching out. This is currently on my todo list and is very near the top (it's planned to be worked on). Please bear with me and keep an eye on this issue.

**Comment by nicolastakashi** [comment]
@joey-grafana really good to heat it.

If you need help, let me know 💪🏼
