### ISSUE TITLE
Cannot create any dashboard after adding a Graphite datasource

### ISSUE THREAD

**Issue by megastallman** [grafana/grafana#4442]
[Bug]
I've added a Graphite datasource. "Test Connection" button says "Success Data source is working". I save it, and can do nothing else. The "Dashboards" tab returns me to "Home" dashboard and there are no data-related tabs/fields like in that manual http://docs.grafana.org/datasources/graphite/ 
Grafana version used: 2.6.0

**Comment by torkelo** [comment]
"Dashboards" tab? where is this?

From the home dashboard, open the dashboard picker and click on the "New" button. This creates a new empty dashboard. Use the green row icon to the right to open the row menu from which you can add a new panel (for example graph). 

I know Grafana can be tricky when you are new to the UI, finding your way around and building dashboards is not super intuitive the first time (we are working on improving this for next release)
http://docs.grafana.org/guides/gettingstarted/
