### ISSUE TITLE
Send `X-Cache-Skip` header in explore mode

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#44437]
### Discussed in https://github.com/grafana/grafana/discussions/38339

<div type='discussions-op-text'>

<sup>Originally posted by **kminehart** May 11, 2021</sup>

**What would you like to be added**:

We should be sending a custom header for Grafana Enterprise, `X-Cache-Skip`, in explore mode so that we do not cache requests sent from this view.

**Why is this needed**:

Caching explore mode queries is likely an unexpected behavior. Sending this header with requests will cause them to not be cached.</div>

**Comment by AaronTJDev** [comment]
Can I be assigned this issue?
