### ISSUE TITLE
AzureMonitor: Migrate query editor to use new UI

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#44432]
Similarly to the CloudWatch metrics query editor, we should refactor the Azure Monitor query editor so that it's using the new query editor UI components from the [grafana-experimental](https://github.com/grafana/grafana-experimental) repo. Would be good if we could involve UX in this work. 

---

Here's the roadmap of issues since we've changed this to an epic

- [x] #48709
- [x] #48711
- [x] #48713
- [x] #50170 
- [x] #50171
- [ ] #52003

**Comment by asimpson** [comment]
The goal with this work is to move AzureMonitor to [grafana-experimental](https://github.com/grafana/grafana-experimental). 
This is part of a larger goal to unify the look and feel of all the datasource plugins.

CloudWatch already uses these new form controls and fields as you can see in the screenshot below:

![image](https://user-images.githubusercontent.com/1048831/165974194-8f634aa1-72b0-47c6-bfc9-5e371af08d97.png)

Compare that to Azure Monitor in the screenshot below:

![image](https://user-images.githubusercontent.com/1048831/165974350-02129f8e-b75c-4467-b8de-1bdb7386ac3e.png)

Some notable differences include:

- The "header toolbar" on Cloudwatch for "global query" options.
- Cloudwatch can group controls and fields together as it makes sense.
