### ISSUE TITLE
CloudMonitoring: Migrate query editor to use new UI

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#44431]
Similarly to the CloudWatch metrics query editor, we should refactor the CloudMonitoring query editor so that it's using the new query editor UI components from the [grafana-experimental](https://github.com/grafana/grafana-experimental) repo. Would be good if we could involve UX in this work.

**Comment by mtanda** [comment]
I hope https://github.com/grafana/grafana/issues/30344 is solved with migrating query editor.

**Comment by sunker** [comment]
Yeah definitely! Hopefully we can address this soon

**Comment by andresmgot** [comment]
@kevinwcyu all components have been migrated, the only thing missing is re-checking the style to the think that makes most sense, right? (and adding more tests, if necessary)

**Comment by kevinwcyu** [comment]
> @kevinwcyu all components have been migrated, the only thing missing is re-checking the style to the think that makes most sense, right? (and adding more tests, if necessary)

Yea that's correct.

**Comment by asimpson** [comment]
Re-opened to do some additional clean up.

- [ ] Clean up the Metric Query Editor and SLO Editor UX. 
  - in part the UI should more closely align with Google's metric explorer at least as far as groupings of common options go.
 
Goal is to release this in 9.1

**Comment by andresmgot** [comment]
quick bug report here. When creating a new query, it doesn't select a query type:

![Screenshot from 2022-08-01 11-34-29](https://user-images.githubusercontent.com/4025665/182119560-7b97ca98-a7a9-4c81-9da4-2816901c14cc.png)

while it should select "Metrics" by default.
