### ISSUE TITLE
[Bug] Second metric alias screwed up when metric name includes template variables

### ISSUE THREAD

**Issue by emarock** [grafana/grafana#4443]
Grafana v2.6.0, on RH 7 (rpm install), OpenTSDB datasource.

The attached screenshots should be quite self-explainatory. Basically, when adding a 'B' metric on a graph panel, in case the metric name includes a template variable, the series aliases are built according to the 'A' metric logic, both for 'A' and for 'B'.

I'm not familiar with the code structure, but if someone can point out where to look for possibly relevant code I will be happy to give it a try.

![screen shot 2016-03-22 at 10 56 04](https://cloud.githubusercontent.com/assets/13051155/13948009/04602bfc-f01e-11e5-9c61-008c25f099e4.png)
![screen shot 2016-03-22 at 10 55 54](https://cloud.githubusercontent.com/assets/13051155/13948010/04ad2c18-f01e-11e5-8d7e-acdd8c976912.png)

**Comment by torkelo** [comment]
This has been reported many times already (for example, https://github.com/grafana/grafana/issues/2687) 

Due to a limitation in the OpenTSDB query api,
https://github.com/grafana/grafana/issues/1876
