### ISSUE TITLE
Azure Monitor plugin missing Log Analytics Workspace selection

### ISSUE THREAD

**Issue by BostjanBozic** [grafana/grafana#44444]
**What happened**:
Using "Logs" capability of Azure Monitor plugin is missing selector for Log Analytics Workspace, where queries should run.

**What you expected to happen**:
Capability to select Log Analytics Workspace when using creating log queries toward Azure Monitor.

**How to reproduce it (as minimally and precisely as possible)**:
* Configure Azure Monitor datasource
* Create new dashboard
* Select correct datasource and resource, e.g. Function App
* try to query `trace` table

**Anything else we need to know?**:
Problem seems to be that workspace parameter (`queries[0].azureLogAnalytics.workspace`) in request payload is empty. In old version of Grafana (`v7.x`), there was an option to provide default log analytics workspace when creating data source, but this is no longer available.
<img width="1905" alt="Screenshot 2022-01-25 at 17 55 28" src="https://user-images.githubusercontent.com/31651092/151023250-26fde952-d958-4e82-b336-2aa871ff2ff3.png">

Performing queries on Log Analytics Workspace scope works, but not on other scopes (e.g. Function App). Maybe I am also understanding this capability wrong though.

**Environment**:
- Grafana version: `8.3.4` (also tried `8.2.7` and `8.1.8`)
- Data source type & version: Azure Monitor, version `3.0.0` or `3.1.0` (depending on Grafana version)
- OS Grafana is installed on: container deployed on Kubernetes
- User OS & Browser: MacOS 12.1, Google Chrome 97.0.4692.99
- Grafana plugins: only core plugins
- Other: I checked around and found similar issue, though there in the end problem was that Log Analytics Workspace was not visible when selecting resource (https://github.com/grafana/grafana/issues/40511)

**Comment by BostjanBozic** [comment]
Ignore this, I am an idiot - of course you can not query logs directly from resource scope (e.g. Function App), since it does not include logs, those are actually stored in Application Insights, so queries work from there.

Would it maybe make sense to mask resources from selecting them in case they are not "log-retrieving" capable? Since it does make a bit of confusion - if you want logs for specific resource, you would select this resource.

**Comment by sarahzinger** [comment]
@BostjanBozic so just to make sure I understand the problem you ran into:
- you tried to select a workspace to find logs, 
- and found that didn't work for the kind of query you were trying to run (running traces)
- and you are suggesting that we remove or mask workspace resources from our resource picker to make it less confusing?

is that an accurate summary of the suggestion/problem? There might be other queries that would work for those resources, but maybe I'm mistaken?

**Comment by BostjanBozic** [comment]
@sarahzinger thanks for coming back to me!

At the beginning I was an idiot myself, as I was trying to e.g. run some queries on "Resource" of Function App itself. To my understanding, Function App logs are stored in Application Insights, so the only way to access them is by selecting "Resource" Application Insights.

I believe most logs are stored either in Application Insights or Log Analytics Workspace. What my suggestion would be is to mask "non-log" resources from "Resource" selection - e.g. there is nothing you can query when selecting Function App in "Resource" selection.
Maybe it is just me and my intuition that I went first for Function App "Resource", and it took me a while to realise I am trying to fetch logs from wrong "Resource" :)

**Comment by sarahzinger** [comment]
@BostjanBozic not an idiot :) there's a lot to it, I know I'm still learning and we're always trying to make it easier to use!

I'm not terribly familiar with "Function App" is that the same as Azure Functions? If so, it looks to me like you can send them to Log Analytics, so I would think you should be able to query for them here in the Logs section, although it does seem not to be on by default if I'm understanding the docs correctly you might have to mess around with your settings to send them there: https://docs.microsoft.com/en-us/azure/azure-functions/functions-monitor-log-analytics?tabs=csharp

I believe this work is as designed so I'll close the issue, but if I'm misunderstanding feel free to ping me and I can reopen!
