### ISSUE TITLE
[Bug][Elasticsearch] Grouping by terms containing data with hyphen not working

### ISSUE THREAD

**Issue by friesoft** [grafana/grafana#4444]
- What grafana version are you using?: **2.6.0 (installed from precompiled binary tar.gz)**
- What datasource are you using?: **Elasticsearch (connected to Elasticsearch 1.7.2)**
- What OS are you running grafana on?: **Suse Linux Enterprise Server 11 SP4 x64**

We are currently trying to create a graph with Elasticsearch datasource using a query similar to this:
Query: type:accesslog AND (provider:"asdf-default" OR provider:"asdf-internet-default")
Metric: Count
Group by: Terms provider Order by: term value (desc)
Then by Date Histogram [at]timestamp Interval auto Min Doc Count 0

The graph however doesn't contain the two mentioned providers ("asdf-default" and "asdf-internet-default") but instead those 3 split up terms:
- asdf
- internet
- default

I guess this is a bug or am I missing something here?

**Comment by torkelo** [comment]
Sounds like your `provider` field in your elasticsearch document is analyzed in the ES index, this causes a terms query to split the word on hyphens. 

So you need to update your elasticsearch index mapping.
