### ISSUE TITLE
Come up with general categories for variations of schematized objects

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#44441]
In working on the datasource schema component, @papagian noted that there may be some variations on the way the object is represented. This has a significant impact on schema - having to have more than one representation of an object puts us in dangerous territory, basically because of the [Zero One Infinity rule](https://wiki.c2.com/?ZeroOneInfinityRule).

We may need to do this anyway, so if we do, we should be principled about it: ideally, if we need variations on object schemas, we can standardize those variations, and then decide whether or not a given object needs a given variation.

Best way to figure that out is with a bit of a research spike, looking through the DTOs we have.
In looking through the extant set of DTOs/object definitions, i can immediately imagine three meta-categories:

* Noise that we'd like to eliminate in the course of proper schematization. (We should note these where they exist, but largely ignore them because they become a question, at least with Thema, of defining an "onboarding" path - grafana/thema#32). Example: fields with differing names (camel vs. snake)
* Addition of fields or wrappers around the the schematized object that compose cleanly
* Additional rules or actual differing types of fields on e.g. two different struct defs that still appear to be intended to be "the same object, just...a little different"

**Comment by kylebrandt** [comment]
https://gist.github.com/kylebrandt/e6f38b6421a17ee8d0d64ce5703b2721

**Comment by sdboyer** [comment]
@DanCech made a comment today that gave me a realization: one such standard variation we'd plausibly need is a version of a schema's canonical Go struct, adapted for querying, where all of its fields are nil-able (pointers)

**Comment by sdboyer** [comment]
I think there's a generally-useful thing to be captured here (and we captured some of it, here and in #44591's spreadsheet), but generally speaking it was premature to go too far, here. "Standard variations on schema" is something that's hard to predict ahead of time; we'll figure out more as we iterate.
