### ISSUE TITLE
CloudWatch: Improve policy documentation

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#44442]
Currently, the [CloudWatch docs](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#cloudwatch-specific-data-source-configuration) specifies a minimal policy required to run the plugin. This is not completely accurate though - it is possible to add only the policies required by CloudWatch logs and use only that part of the data source. Similarly, it's possible to add only the policies required by CloudWatch logs and use that part of the data source. Therefore, we should update the documentation so that it includes examples for:
* minimal policies required for running CloudWatch Logs only
* minimal policies required for running CloudWatch Metrics only
* minimal policies required for running both

If this is not already the case, we should make sure that [test data source](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/datasource.ts#L889-L905) in the config page is asserting according to these three options.

**Comment by mhausenblas** [comment]
> This is not completely accurate though - it is possible to add only the policies required by CloudWatch logs and use only that part of the data source.

Confirmed for AMG.

**Comment by juliocorzo** [comment]
Hi, I'm interested in helping out with this, I have experience with IAM policies and work regularly with CloudWatch.

Reading through the documentation to see how Grafana needs to access these resources, it seems to me like there are a few areas that could be expanded:

1. Like this issue details, adding simple policies for CloudWatch logs and/or CloudWatch metrics for users that only wish to do this.
2. Adding a disclaimer with examples of [IAM security best practices](https://docs.aws.amazon.com/IAM/latest/UserGuide/best-practices.html#grant-least-privilege). For example, restricting the policies to only access the EC2 instances that Grafana needs to work and restricting the path to the logs as well. 

May I work on this?
