### ISSUE TITLE
intent: Create a docker-compose/equivalent setup for working on Intent API

### ISSUE THREAD

**Issue by sdboyer** [grafana/grafana#44454]
For the forseeable future, Grafana will rely on an external k8s server in order to fulfill the intent API, essentially just proxying calls straight through. Initially, for development and demo purposes, we should do this with some simple local setup, e.g. via `docker-compose`.

Eventually, as we widen the circle, we'll probably want to adapt this approach to whatever we decide the model should be for OSS and Enterprise users wanting to experiment with the new system.

**Comment by radiohead** [comment]
Closed by #45613
