### ISSUE TITLE
Question - Read Custom Metrics from Cloudwatch

### ISSUE THREAD

**Issue by pckeyan** [grafana/grafana#4445]
Hello,

I am setting Grafana to view data from Cloudwatch for a Custom Metrics. Custom Metrics Namespace is JVMStats, Metric is JVMHeapUsed, Dimension is instance Id. If I configure these data, I am not able to get the graph/datapoints. Can you please advice me on how to get the data? 

Appreciate your help and time.

Thanks and Regards
Karthik

**Comment by mtanda** [comment]
Hi,

What Grafana version do you use?
Custom Metrics support is available from version 3.0.
To use the feature, you need to use 3.0 pre-release build.
If you already use it, please configure CloudWatch datasource to set Namespaces of Custom Metrics.
![image](https://cloud.githubusercontent.com/assets/224552/13954811/bc7d1bf2-f085-11e5-9497-d5687a800961.png)

After that, query editor suggestion should work for Custom Metrics.

**Comment by pckeyan** [comment]
I am using 2.6.0 and I could not find 3.0 rpm.

**Comment by mtanda** [comment]
You can download from http://grafana.org/download/builds .

**Comment by pckeyan** [comment]
@mtanda  Thanks a Lot. Let me try

**Comment by magnusboman** [comment]
I'm using the latest nightly build (29th of March) and have set the Custom Metrics namespace. When I go to build up a dashboard I can select the namespace and metric but Grafana doesn't show any values.
I can graph the same metrics in CloudWatch.

**Comment by mtanda** [comment]
Hi, I tested nightly build (29th of March), it works in my environment.

I put metric data like following,
```
aws cloudwatch put-metric-data --region ap-northeast-1 --namespace "Foo" --metric-name "TestMetrics" --dimensions DimName=DimValue --value 1 --timestamp 2016-03-29T00:00:00.000Z
aws cloudwatch put-metric-data --region ap-northeast-1 --namespace "Foo" --metric-name "TestMetrics" --dimensions DimName=DimValue --value 1 --timestamp 2016-03-29T01:00:00.000Z
aws cloudwatch put-metric-data --region ap-northeast-1 --namespace "Foo" --metric-name "TestMetrics" --dimensions DimName=DimValue --value 1 --timestamp 2016-03-29T02:00:00.000Z
aws cloudwatch put-metric-data --region ap-northeast-1 --namespace "Foo" --metric-name "TestMetrics" --dimensions DimName=DimValue --value 1 --timestamp 2016-03-29T03:00:00.000Z
```

and this is screenshot of query editor.
![custom_metrics](https://cloud.githubusercontent.com/assets/224552/14095775/8f8692ea-f59e-11e5-8560-452737e5520c.png)

I'm not sure how is your environment, there is any error in console?
Other metrics (not Custom Metrics) is shown in Grafana?

**Comment by magnusboman** [comment]
All Amazon metrics are working fine, just not custom metrics. I copied your command line but changed the region and still get nothing;

![screenshot from 2016-03-29 13-51-19](https://cloud.githubusercontent.com/assets/11380569/14096571/9cd7d744-f5b5-11e5-8929-b16a78cca960.png)

I've set the loglevel to Debug but still don't get anything useful in the logfile:

```
[log]
# Either "console", "file", default is "console"
# Use comma to separate multiple modes, e.g. "console, file"
;mode = console, file

# Buffer length of channel, keep it as it is if you don't know what it is.
;buffer_len = 10000

# Either "Trace", "Debug", "Info", "Warn", "Error", "Critical", default is "Trace"
;level = Info
level = Debug

# For "console" mode only
[log.console]
level = Debug

# For "file" mode only
[log.file]
;level =
level = Debug
# This enables automated log rotate(switch of following options), default is true
;log_rotate = true

# Max line number of single file, default is 1000000
;max_lines = 1000000

# Max size shift of single file, default is 28 means 1 << 28, 256MB
;max_lines_shift = 28

# Segment log daily, default is true
;daily_rotate = true

# Expired days of log file(delete after max days), default is 7
;max_days = 7
```

**Comment by mtanda** [comment]
There is no error indicator on graph panel, so the CloudWatch API request might be succeeded.
And, the internal logic to call API is not differ between non custom / custom metrics. (just calling GetMetricStatistics with parameter in query editor)

I'm not sure why the problem is occured...
If you use Google Chrome, and you have experience to use Developer Tools, please investigate CloudWatch API call response from Grafana backend.

**Comment by pckeyan** [comment]
Hi,

I am seeing data in cloud watch and I took the 29th March build to verify. Still I could not get the data into grafana. I checked the log in the chrome tools and I get the below error:

boot.f1193162.js:36 Objectmessage: "Metric measurement is missing"__proto__: Object__defineGetter__: __defineGetter__()__defineSetter__: __defineSetter__()__lookupGetter__: __lookupGetter__()__lookupSetter__: __lookupSetter__()constructor: Object()hasOwnProperty: hasOwnProperty()isPrototypeOf: isPrototypeOf()propertyIsEnumerable: propertyIsEnumerable()toLocaleString: toLocaleString()arguments: nullcaller: nulllength: 0name: "toLocaleString"__proto__: ()<function scope>toString: toString()valueOf: valueOf()get __proto__: get __proto__()set __proto__: set __proto__()(anonymous function) @ boot.f1193162.js:36

**Comment by mtanda** [comment]
hmm, I don't get such error.
Would you open the network panel in chrome tools, and check the reponse to cloudwatch datasource proxy?

The request destination might be like,
```
https://<your grafana ip>/api/datasources/proxy/<your cloudwatch datasource id>
```

**Comment by pckeyan** [comment]
Please find below few information:

Request URL:http://<IP>/public/app/plugins/datasource/cloudwatch/module.js?bust=1459434442236
Request Method:GET
Status Code:200 OK
Remote Address:<IP>:<PORT>
Response
============
/*! grafana - v3.0.0-pre1 - 2016-03-22
 * Copyright (c) 2016 Torkel Ödegaard; Licensed Apache-2.0 */

System.register(["./query_parameter_ctrl","./datasource","./query_ctrl"],function(a){var b,c,d,e;return{setters:[function(a){},function(a){b=a},function(a){c=a}],execute:function(){d=function(){function a(){}return a.templateUrl="partials/config.html",a}(),e=function(){function a(){}return a.templateUrl="partials/annotations.editor.html",a}(),a("Datasource",b.CloudWatchDatasource),a("QueryCtrl",c.CloudWatchQueryCtrl),a("ConfigCtrl",d),a("AnnotationsQueryCtrl",e)}}});

Next Request
=============
Request URL:http://<IP>/public/app/plugins/datasource/cloudwatch/query_parameter_ctrl.js?bust=1459434442236
Request Method:GET
Status Code:200 OK
Remote Address:<IP>:<PORT>

Response
==========
/*! grafana - v3.0.0-pre1 - 2016-03-22
 * Copyright (c) 2016 Torkel Ödegaard; Licensed Apache-2.0 */

define(["angular","lodash"],function(a,b){"use strict";var c=a.module("grafana.controllers");c.directive("cloudwatchQueryParameter",function(){return{templateUrl:"public/app/plugins/datasource/cloudwatch/partials/query.parameter.html",controller:"CloudWatchQueryParameterCtrl",restrict:"E",scope:{target:"=",datasource:"=",onChange:"&"}}}),c.controller("CloudWatchQueryParameterCtrl",["$scope","templateSrv","uiSegmentSrv","datasourceSrv","$q",function(c,d,e,f,g){c.init=function(){var a=c.target;a.namespace=a.namespace||"",a.metricName=a.metricName||"",a.statistics=a.statistics||["Average"],a.dimensions=a.dimensions||{},a.period=a.period||"",a.region=a.region||"",c.regionSegment=e.getSegmentForValue(c.target.region,"select region"),c.namespaceSegment=e.getSegmentForValue(c.target.namespace,"select namespace"),c.metricSegment=e.getSegmentForValue(c.target.metricName,"select metric"),c.dimSegments=b.reduce(c.target.dimensions,function(a,b,c){return a.push(e.newKey(c)),a.push(e.newOperator("=")),a.push(e.newKeyValue(b)),a},[]),c.statSegments=b.map(c.target.statistics,function(a){return e.getSegmentForValue(a)}),c.ensurePlusButton(c.statSegments),c.ensurePlusButton(c.dimSegments),c.removeDimSegment=e.newSegment({fake:!0,value:"-- remove dimension --"}),c.removeStatSegment=e.newSegment({fake:!0,value:"-- remove stat --"}),b.isEmpty(c.target.region)&&(c.target.region=c.datasource.getDefaultRegion()),c.onChange||(c.onChange=function(){})},c.getStatSegments=function(){return g.when([a.copy(c.removeStatSegment),e.getSegmentForValue("Average"),e.getSegmentForValue("Maximum"),e.getSegmentForValue("Minimum"),e.getSegmentForValue("Sum"),e.getSegmentForValue("SampleCount")])},c.statSegmentChanged=function(a,d){a.value===c.removeStatSegment.value?c.statSegments.splice(d,1):a.type="value",c.target.statistics=b.reduce(c.statSegments,function(a,b){return b.fake||a.push(b.value),a},[]),c.ensurePlusButton(c.statSegments),c.onChange()},c.ensurePlusButton=function(a){var b=a.length,c=a[Math.max(b-1,0)];c&&"plus-button"===c.type||a.push(e.newPlusButton())},c.getDimSegments=function(b,d){if("operator"===b.type)return g.when([]);var e=c.target,f=g.when([]);if("key"===b.type||"plus-button"===b.type)f=c.datasource.getDimensionKeys(c.target.namespace,c.target.region);else if("value"===b.type){var h=c.dimSegments[d-2].value;f=c.datasource.getDimensionValues(e.region,e.namespace,e.metricName,h,{})}return f.then(c.transformToSegments(!0)).then(function(d){return"key"===b.type&&d.splice(0,0,a.copy(c.removeDimSegment)),d})},c.dimSegmentChanged=function(a,b){c.dimSegments[b]=a,a.value===c.removeDimSegment.value?c.dimSegments.splice(b,3):"plus-button"===a.type&&(c.dimSegments.push(e.newOperator("=")),c.dimSegments.push(e.newFake("select dimension value","value","query-segment-value")),a.type="key",a.cssClass="query-segment-key"),c.syncDimSegmentsWithModel(),c.ensurePlusButton(c.dimSegments),c.onChange()},c.syncDimSegmentsWithModel=function(){for(var a={},b=c.dimSegments.length,d=0;b-2>d;d+=3){var e=c.dimSegments[d],f=c.dimSegments[d+2];f.fake||(a[e.value]=f.value)}c.target.dimensions=a},c.getRegions=function(){return c.datasource.metricFindQuery("regions()").then(c.transformToSegments(!0))},c.getNamespaces=function(){return c.datasource.metricFindQuery("namespaces()").then(c.transformToSegments(!0))},c.getMetrics=function(){return c.datasource.metricFindQuery("metrics("+c.target.namespace+","+c.target.region+")").then(c.transformToSegments(!0))},c.regionChanged=function(){c.target.region=c.regionSegment.value,c.onChange()},c.namespaceChanged=function(){c.target.namespace=c.namespaceSegment.value,c.onChange()},c.metricChanged=function(){c.target.metricName=c.metricSegment.value,c.onChange()},c.transformToSegments=function(a){return function(c){var f=b.map(c,function(a){return e.newSegment({value:a.text,expandable:a.expandable})});return a&&b.each(d.variables,function(a){f.unshift(e.newSegment({type:"template",value:"$"+a.name,expandable:!0}))}),f}},c.init()}])});

**Comment by mtanda** [comment]
Sorry, these are source code of Grafana, not API response...

Please fill in "Filter field" with the substring of request URL "api/datasources/proxy", you may find API response.
![devtool](https://cloud.githubusercontent.com/assets/224552/14179990/2e4f7fbe-f79c-11e5-9df9-0b6d912eb686.png)

I want to solve your problem. And if it is a bug, I want to fix it.
Please help me to know what happen in your environment.

**Comment by pckeyan** [comment]
{"Datapoints":null,"Label":"ThreadCount"}

**Comment by mtanda** [comment]
Thanks!
It's valid response of GetMetricStatistics. So, the API request should success.
http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html

How do you put the custom metrics from your environment?
The metrics is recorded every minutes, or every hour or more long time?
The screenshot of Grafana query editor is helpful.

Thanks for your cooperation :-)

**Comment by pckeyan** [comment]
We have a script to drop metric data every minute. I can see the data in Cloudwatch and not is grafana.

<img width="1098" alt="screen shot 2016-03-31 at 11 58 58 am" src="https://cloud.githubusercontent.com/assets/9466493/14182169/22fa8316-f738-11e5-89b9-efa82f839086.png">

**Comment by mtanda** [comment]
I got it. The metrics is put with Dimension?

**Comment by pckeyan** [comment]
Yes with ServiceName, InstanceId and ContainerId.

**Comment by mtanda** [comment]
I'm not sure, whether multiple dimension cause such issue.
So try to reproduce.

```
aws cloudwatch put-metric-data --region ap-southeast-2 --namespace "Foo" --metric-name "ThreadCount" --dimensions ServiceName=TestService,InstanceId=i-12345678,ContainerId=TestContainer --value 5 --timestamp 2016-03-31T00:00:00.000Z
aws cloudwatch put-metric-data --region ap-southeast-2 --namespace "Foo" --metric-name "ThreadCount" --dimensions ServiceName=TestService,InstanceId=i-12345678,ContainerId=TestContainer --value 5 --timestamp 2016-03-31T00:01:00.000Z
aws cloudwatch put-metric-data --region ap-southeast-2 --namespace "Foo" --metric-name "ThreadCount" --dimensions ServiceName=TestService,InstanceId=i-12345678,ContainerId=TestContainer --value 5 --timestamp 2016-03-31T00:02:00.000Z
aws cloudwatch put-metric-data --region ap-southeast-2 --namespace "Foo" --metric-name "ThreadCount" --dimensions ServiceName=TestService,InstanceId=i-12345678,ContainerId=TestContainer --value 5 --timestamp 2016-03-31T00:03:00.000Z
aws cloudwatch put-metric-data --region ap-southeast-2 --namespace "Foo" --metric-name "ThreadCount" --dimensions ServiceName=TestService,InstanceId=i-12345678,ContainerId=TestContainer --value 5 --timestamp 2016-03-31T00:04:00.000Z
aws cloudwatch put-metric-data --region ap-southeast-2 --namespace "Foo" --metric-name "ThreadCount" --dimensions ServiceName=TestService,InstanceId=i-12345678,ContainerId=TestContainer --value 5 --timestamp 2016-03-31T00:05:00.000Z
```

This is the result. I failed to reproduce...
![cloudwatch_custom_metrics](https://cloud.githubusercontent.com/assets/224552/14184408/fddb5f1a-f7af-11e5-8a35-de1e225d8377.png)

**Comment by pckeyan** [comment]
Hi,

I see the data after I added all the three Dimensions based on your above graph. But why cannot I query based on only one Dimension?

Any suggestion?

Regards
Karthik

**Comment by mtanda** [comment]
It seems to be spec of CloudWatch.

Please read this.
> This technique for retrieving all dimensions across an AWS namespace does not work for custom namespaces that you publish to Amazon CloudWatch. With custom namespaces, you must specify the complete set of dimensions that are associated with any given data point to retrieve statistics that include the data point.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/DeveloperGuide/GetSingleMetricAllDimensions.html
