### ISSUE TITLE
Alerting: custom headers not being sent from alert queries

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#44460]
**What happened**:

Custom headers not being sent for queries which invoked from alerts (e.g. **it affects Prometheus datasource**).

**What you expected to happen**:

When user configured custom headers for a datasource which supports it (e.g. Prometheus), the headers should be consistently sent from both dashboard and from alerts.

**How to reproduce it (as minimally and precisely as possible)**:

1. Configure a Prometheus datasource and point it to a RequestBin URL.
2. Configure a custom header.
3. Configure an alert for the datasource.

Observe presence/absence of the configured header depending on whether the request was originated from dashboard or alert.

**Anything else we need to know?**:

Queries from dashboard and alerts have different code paths to call `pluginsClient.QueryData`.

query from a dashboard:
[pkg/services/query/query.go](https://github.com/grafana/grafana/blob/9eb82f9fff6635176ea6816c8c153abbece6b6c6/pkg/services/query/query.go#L157)

query from alerts:
[pkg/tsdb/legacydata/service/service.go](https://github.com/grafana/grafana/blob/baab021fec6b2cab7e54ed574af2a0662752ce5b/pkg/tsdb/legacydata/service/service.go#L96)

Query from dashboard has code that collects custom headers from the datasource JsonData and sets them into query request ([here](https://github.com/grafana/grafana/blob/9eb82f9fff6635176ea6816c8c153abbece6b6c6/pkg/services/query/query.go#L149-L151)):
```go
for k, v := range customHeaders(ds.JsonData, instanceSettings.DecryptedSecureJSONData) {
    req.Headers[k] = v
}
```

Alerting doesn't have such code.
As result custom headers are not being sent from alerts.

**Environment**:
- Grafana version: 8.3, main
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by jonathansm1th** [comment]
I was stuck on a similar issue ( We use Cortex, and need the `X-Scope-OrgID` header, which stopped working once we updated to v8.4.6 with legacy alerting); However, I discovered that custom headers are sent correctly when [unified-alerting](https://grafana.com/docs/grafana/latest/administration/configuration/#unified_alerting) is enabled.

**Comment by chrissng** [comment]
@joeblubaugh thanks for the fix. 

Will this fix be backported to earlier versions, especially from v8.3.x and onwards given that the regression happened with Legacy Alerting.
