### ISSUE TITLE
Prometheus Datasource: not sending X-Grafana-User headers

### ISSUE THREAD

**Issue by Nicofuma** [grafana/grafana#44464]
**What happened**:

I have a prometheus datasource configured and `dataproxy.send_user_header` set to true.
Between the prometheus instance and Grafana I have a proxy dumping all headers and I can see that the `X-Grafana-User` is not sent. The only headers I have are `{"Accept-Encoding":["gzip"],"Content-Length":["31"],"Content-Type":["application/x-www-form-urlencoded"],"User-Agent":["Grafana/8.3.4"`

**What you expected to happen**:
`X-Grafana-User` header should be sent

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: prometheus 

EDIT: I have tested with the version 8.2.7 and it appears to be forwarding the headers correctly

**Comment by ve4eslav** [comment]
i faced the same issue

**Comment by dmitry-tiger** [comment]
Grafana 8.4.4 is affected too

**Comment by ve4eslav** [comment]
Looks like this issue 
https://github.com/grafana/grafana/issues/41623
and these issues appeared after 
https://github.com/grafana/grafana/issues/37784

**Comment by mildwonkey** [comment]
Duplicate - Closing this in favor of #47734
