### ISSUE TITLE
Timeseries: fill below to still fills to disabled / empty query

### ISSUE THREAD

**Issue by yoyo421** [grafana/grafana#44466]
Hello,

Im trying to have a fill that works only when a dashboard variable is true, I apply that by adding a Where in the sql and checking if the variable is true, if it does than fill to it and if the variable is false, don't fill but instead i get the fill to 0

after that I used TestData DB plugin to test the following example:
I have 2 queries
A) CSV Metric Values: 1,20,90,30,5,0
B) CSV Metric Values: 30,30,30,,,
and as an override, I fill A to B

result (good):
![image](https://user-images.githubusercontent.com/20062424/151141268-ed4c37fd-99ca-4864-bee2-90904f4d8bd3.png)

when I change B to CSV Metric Values: "," or just disabled it this happens:
![image](https://user-images.githubusercontent.com/20062424/151141364-23ec00cd-8f90-4be2-8d43-d05f2dd2ceb9.png)

but I expected:
![image](https://user-images.githubusercontent.com/20062424/151141571-f0328d50-ee4c-42ca-8d6a-06a52dd3e0a3.png)

is it supposed to do that? (because now it has no data so why it should fill to 0 and not just disable the fill)

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": "-- Grafana --",
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 17,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "FdB6ptxnk"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 0,
            "gradientMode": "none",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "linear",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": [
          {
            "matcher": {
              "id": "byName",
              "options": "A-series"
            },
            "properties": [
              {
                "id": "custom.fillBelowTo",
                "value": "B-series"
              }
            ]
          }
        ]
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [],
          "displayMode": "list",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "FdB6ptxnk"
          },
          "refId": "A",
          "scenarioId": "csv_metric_values",
          "stringInput": "1,20,90,30,5,0"
        },
        {
          "datasource": {
            "type": "testdata",
            "uid": "FdB6ptxnk"
          },
          "hide": false,
          "refId": "B",
          "scenarioId": "csv_metric_values",
          "stringInput": "30,30,30,,,"
        }
      ],
      "title": "Panel Title",
      "type": "timeseries"
    }
  ],
  "schemaVersion": 34,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard 2",
  "uid": "JptFftxnz",
  "version": 2,
  "weekStart": ""
}
```

(edit: add dashboard json)

**Comment by nicolaerosia** [comment]
@leeoniya are you aware of a change between 8.3.3 to 8.3.4 that might be causing this? It seems like the behavior is different than what we see in the reproducer up - I can't make a simple example without dependencies on SQL that would reproduce it.

# version 8.3.3

when the SQL query returns an empty set it looks like this - OK
![github-8 3 3-boundary-false](https://user-images.githubusercontent.com/4127983/151157067-b9193be4-ef80-4897-b283-3e5eaf8fa2e3.png)

When the SQL query returns more timeseries - NOT OK
![github-8 3 3-boundary-true](https://user-images.githubusercontent.com/4127983/151157118-1b2a52d1-256e-4ee7-a01d-87ada913deca.png)

# version 8.3.4

when the SQL query returns an empty set it looks like this - NOT OK
![github-8 3 4-boundary-false](https://user-images.githubusercontent.com/4127983/151157213-da7f4831-1b19-45fc-b119-b27a70ba193d.png)

When the SQL query returns more timeseries - OK
![github-8 3 4-boundary-true](https://user-images.githubusercontent.com/4127983/151157234-b8f46851-efe1-4dff-b9d3-5f4ce848cc94.png)

**Comment by nicolaerosia** [comment]
I took v8.3.4 tag, reverted the following and I get back the behaviour on 8.3.3
```
commit 3362ccd1cc14fcbc63c5f13ff72d818529f7fb0e
Author: Grot (@grafanabot) <43478413+grafanabot@users.noreply.github.com>
Date:   Thu Dec 16 22:12:48 2021 +0100

    TimeSeries: don't auto-disable fill of fillBelowTo targets (#43165) (#43244)
    
    (cherry picked from commit 8fdbc6cc20077783bd356f9086814b3e23726c6e)
    
    Co-authored-by: Leon Sorokin <leeoniya@gmail.com>
```

cc @leeoniya

**Comment by nicolaerosia** [comment]
I took v8.3.4 tag, reverted the following and I get back the behaviour on 8.3.3
```
commit 3362ccd1cc14fcbc63c5f13ff72d818529f7fb0e
Author: Grot (@grafanabot) <43478413+grafanabot@users.noreply.github.com>
Date:   Thu Dec 16 22:12:48 2021 +0100

    TimeSeries: don't auto-disable fill of fillBelowTo targets (#43165) (#43244)
    
    (cherry picked from commit 8fdbc6cc20077783bd356f9086814b3e23726c6e)
    
    Co-authored-by: Leon Sorokin <leeoniya@gmail.com>
```

cc @leeoniya

**Comment by leeoniya** [comment]
hmm, it seems to behave differently for legend toggle vs in-data toggle. i'll take a look today.

https://user-images.githubusercontent.com/43234/151215504-aa1fc001-42b9-4764-870b-4bde06803387.mp4

**Comment by nicolaerosia** [comment]
@leeoniya thank you very much, it fixes both cases!
