### ISSUE TITLE
[Bug] Direct rendered image sometimes render a blank image

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4448]
* What grafana version are you using? Nightly from 16-03-2016
* What datasource are you using? OpenTSDB
* What OS are you running grafana on? CentOS 6

It happens frequently on some panels, but I couldn't reproduce in others. A refresh or two is usually enough to get the image.

What I could gather so far:

- It looks like it's not related to the complexity/range of the query. I have some panels that are slow to render and they work every time.
- With log level set to Debug, the only message I have in log is the request:

> 2016/03/22 11:17:29 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/panel-name-here?panelId=1&from=1426492625351&to=1427869367323&width=1000&height=500

- Panels rendered on the browser never suffer from the same problem

I didn't had the problem before updating to this version. Unfortunately I don't know exactly which nightly I was using before.

**Comment by torkelo** [comment]
Try latest build, have failed to replicate this with a different data sources and query times.

**Comment by vitorboschi** [comment]
I'm testing it on a newer version and the problem seem fixed. I'll reopen if it arises again.
