### ISSUE TITLE
Azure Monitor: Regex Template Filters based on value, not display name

### ISSUE THREAD

**Issue by mdsgrafana** [grafana/grafana#44490]
**What happened**: I needed to set up template variables for the Azure monitor and needed to filter some of the objects. When creating the filters, I realized that I could not filter on what I could see in the UI, I had to filter on the values. For example I needed to filter the subscription on "PROD" to capture my "PROD" and "PREPROD" environments. I realized I needed to filter on the actual subscription IDs - the long strings. The Namespaces were similar - "Front Door" is what I see in the UI and "frontdoor" is what I needed to filter on. I ended up needing to pull the values out of the JSON in the Dev Console because they are not available in the UI.

**What you expected to happen**: To be able to filter on something I can see in the UI.

**How to reproduce it (as minimally and precisely as possible)**: Just try to set up template variables with regex filters for the Azure Monitor Datasource using the Grafana Query Filters. Try to filter on what you can see in the UI.

**Anything else we need to know?**: Filtering on the values is fine as long as they get exposed to the user so they can see that is what they need to filter on. Having to dig the values out of the JSON is not easy for a lot of users. 

Another thing is that very few people are regex experts. I'm not one of them. Setting up a regex that I'm pretty sure will work based on what I see in the UI and then have it not work as expected was a pretty frustrating experience. It was even more frustrating to realize that my regex was actually good but it was not operating against what I thought it was. That cost me a lot of time.

**Environment**:
- Grafana version: 8.3.4 & 8.3.5 Grafana Cloud
- Data source type & version: Microsoft Azure
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: OSX & Chrome
- Grafana plugins:
- Others:
<img width="798" alt="Values" src="https://user-images.githubusercontent.com/83845780/151229125-ac84154a-0988-45f2-8b72-5e1c3ba89930.png">

**Comment by aangelisc** [comment]
This looks like a core Grafana issue to me rather than a datasource issue.

**Comment by taleena** [comment]
@mdsgrafana I'm going to close this one given it is now 2 major versions behind (so it could be fixed), and it seems to be an issue that is not nec. specific to Azure Monitor. Please feel free to reopen with a different label if desired!

**Comment by jlangford9284** [comment]
+1 here, also have the exact same issue. I have to filter on the subscription ID rather than the name.

**Comment by taleena** [comment]
I'm referencing your comment to the linked open ticket.

**Comment by mamorett** [comment]
Hi. I have exactly the same issue. I am using OCI Metrics plugin and if I apply regex on compartments, it applies on values and not on text. I tested with v9.x, 10.0, 10.1, 10.2 and 10.3. Same results. In my case, text has the compartment name, values the ocid. regex should applies on text (the output in the template var shows correctly the text field), but it applies on value only.

**Comment by taleena** [comment]
This was filed and addressed here: https://github.com/grafana/grafana/issues/76302
