### ISSUE TITLE
Docs feedback: /datasources/mysql.md

### ISSUE THREAD

**Issue by FlorinAndreiSpree3D** [grafana/grafana#44494]
The Time Series Queries would be MUCH clearer and easier to understand if the table used as an example was shown at the beginning of that section.

Basically, do `select * from test_data limit 10;` and show the output at the start of that section.

**Comment by zoltanbedi** [comment]
Thanks for your feedback @FlorinAndreiSpree3D, I think that would be a good addition and an easy thing to do. We will find time and add it to the docs.
