### ISSUE TITLE
library element API returns 404 when updating an existing element

### ISSUE THREAD

**Issue by sjkingo** [grafana/grafana#44508]
When attempting to PATCH an existing library element (as returned by GET all), Grafana returns a 404:

```
PATCH /api/library-elements/ztaGXeJ7z
<Response [404]> {"message":"library element could not be found"}
```

The UID is a valid library panel and is returned in the results from `GET /api/library-elements/` prior to the above request.

Grafana v8.2.1 (88622d7f09)

**Comment by idafurjes** [comment]
@sjkingo I am having difficulties reproducing the bug, can I provide additional information?

**Comment by wbrowne** [comment]
I'm also unable to reproduce - will close as there's no new info to work from
