### ISSUE TITLE
Bug:  Tooltip All Series values incorrect when series specific override applied

### ISSUE THREAD

**Issue by sslupsky** [grafana/grafana#4450]
I think there may be a bug with the tooltip value(s) when the series specific override is applied.  Specifically, when you:

1. Have multiple series in a graph panel
2. Apply "Transform: negative-Y" to all series in the series specific override in the Display Styles panel
3. Select "Tooltip All Series" in the Display Styles panel

When the tooltip pops up, the values are shown as if the "Transform: negative-Y" was not applied.  If you deselect the "Tooltip All Series" so that just one series is show, the correct value appears.

Screen shots below:

Incorrect values:
![screen shot 2016-03-22 at 8 35 45 am](https://cloud.githubusercontent.com/assets/16888734/13955139/3538749c-f009-11e5-99e9-f8b777470097.png)

Correct value(s):
![screen shot 2016-03-22 at 8 35 24 am](https://cloud.githubusercontent.com/assets/16888734/13955145/3bb87970-f009-11e5-87d4-6d3fb0f35d4f.png)

**Comment by torkelo** [comment]
Seems to work as intended. Transform Negative-Y does not affect the tooltip, only the graph display. 

![image](https://cloud.githubusercontent.com/assets/10999/14234504/0a0b16aa-f999-11e5-9645-3a09c95a7f18.png)

**Comment by sslupsky** [comment]
Hi @torkelo 

One of the two examples I provided must be generating an incorrect result.  The example you posted is the same as my first example.  If you look carefully in my second example, the tool tip value has been inverted (multiplied by -1).  Thus, there is an inconsistency in how the tooltip is calculated depending on whether or not the "All Series" checkbox is selected.

My preference would be that the value in the tooltip is the same as the Y-axis.  Otherwise, it leads to confusion.

**Comment by torkelo** [comment]
no, I mean you seem to have inverted it from -1 to positive, but tooltip still shows the real value, as it was designed, the Transform Negative Y only affects the display, not the tooltip

**Comment by sslupsky** [comment]
@torkelo I think I understand what you mean.  However, what I am saying is that grafana show two *different* values, the real value or the inverted value, depending on the "All Series" checkbox setting.  In both cases, the "Transform Negative Y" is applied, shouldn't the value in the tooltip be the same value?
