### ISSUE TITLE
root_url without protocol

### ISSUE THREAD

**Issue by anlutro** [grafana/grafana#4451]
I'm using Grafana 2.6.0 on Debian 8.

I'm planning to run it behind Nginx. Eventually, I might want to put HTTPS on top. To facilitate this, I was hoping to change the `root_url` to one without http or https - for example `//grafana.mydomain.com`. URLs that start with `//` instead of `http://` or `https://` will automatically expand to either http or https URLs, depending on which protocol is being used for the "parent" page in the browser.

Currently, this causes grafana to redirect with a `Location: /grafana.mydomain.com` - apparently the first slash is trimmed. I tried adding 2 more slashes and quotes in case there was escaping going on, but it didn't work.

Is this something that's currently possible or can be made possible?

**Comment by torkelo** [comment]
just use the full http url that you use in the browser, if it is behind https use root_url = https://grafana.mydomain.com
