### ISSUE TITLE
Grafana Windows Installation Run As Specific Windows User

### ISSUE THREAD

**Issue by kn327** [grafana/grafana#44514]
Currently when installing and running grafana on Windows, when the “Run As Windows Service” option is selected in the msi installer, the service starts and runs as SERVICE on the local machine

This presents issues when connecting to a MSSQL data source using Windows Authentication as it attempts to authenticate as the machine instead of a specific windows user with permissions

Is there a way to configure Grafana to run as a specific domain user still as a service similar to how Jenkins allows you to specify the windows username and password in installation OR allow me to add a windows user to use for authentication when connecting to a MSSQL database ?

**Comment by dsotirakis** [comment]
@grafana/grafana-bi-squad long shot but any inputs here? (not you area most likely)

**Comment by zoltanbedi** [comment]
This is not supported yet https://github.com/grafana/grafana/issues/19795

**Comment by kn327** [comment]
Actually, I found a workaround that solves my problem.

On the computer running Grafana:
1. Open services.msc
2. Find the Grafana service
3. Right-click, select Properties
4. Click on the "Log On" tab
5. The selected option is set to "Local System Account"
6. Change to "This account"
7. Enter domain username and password
8. Click "Ok" (the username and password will be verified)
9. Restart the Grafana service

My datasources now authenticate with the desired user credentials, and the service is now running under the correct domain account instead of the "SYSTEM" account :)

**Comment by zoltanbedi** [comment]
@kn327 glad you figured it out and shared with us 🙏
