### ISSUE TITLE
time series: Connect null values does not work at all or enforces 'always' value

### ISSUE THREAD

**Issue by nvtkaszpir** [grafana/grafana#44513]
**What happened**:
select time series
select `Connect null values: never` ... or any other value, it does nothing.

**What you expected to happen**:
this feature worked in 7.x for sure.
now if null values are there then graph is connected, as if `Connect null values: always` was enforced.

**How to reproduce it (as minimally and precisely as possible)**:
set up some basic prometheus setup, create basic cronfig scraping something where it will generate hole in metrics (for example another service, and disable service access for few minutes to have a null metric due to access restriction)

**Anything else we need to know?**:
current line graph - `Connect null values: never`:
![image](https://user-images.githubusercontent.com/1480252/151317896-d2831d6d-a3f2-47db-b24f-8e8e75c88b18.png)
current line graph - `Connect null values: always`:
![image](https://user-images.githubusercontent.com/1480252/151318065-e3bd2694-914c-4dbe-b6e1-dfeca419892e.png)

look the same.

switching to graph style: bars will show that graphs have null values:
![image](https://user-images.githubusercontent.com/1480252/151318416-0c726e3c-b69e-43b6-bf5f-2484946732f1.png)

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: prometheus 2.32.1
- OS Grafana is installed on: official grafana container 
- User OS & Browser: ubuntu 20.04 LTS + google chrome Version 97.0.4692.99 (Official Build) (64-bit)
- Grafana plugins: none
- Others:

**Comment by nvtkaszpir** [comment]
possibly related to:
#35928
#39740

**Comment by Dr4g0nM4st3r** [comment]
also possibly related. 
#43134

**Comment by belm0** [comment]
I'm seeing this as well (series behave as "always connected"), but only on the legacy Graph component.  We didn't notice it until 8.4.x.

It's a troubling regression, since we have 100's of panels on the old Graph.

**Comment by leeoniya** [comment]
@belm0 that looks like a regression. PR with the fix is here: https://github.com/grafana/grafana/pull/46069

**Comment by baryluk** [comment]
Note sure if this is related, but in Grafana 8.4.2 (from kube-prometheus-stack helm chart in k8s), I just noticed null value: null (so not connected) produces connected (old) graph anyway:

![Screenshot at 2022-03-04 12-58-35](https://user-images.githubusercontent.com/110322/156759705-c48049b7-89d8-4cfd-83d0-108e3cb01dce.png)

It renders fine directly in Prometheus / Thanos:

![Screenshot at 2022-03-04 13-01-02](https://user-images.githubusercontent.com/110322/156760063-96e20860-53e7-4843-992c-6d8b85e10201.png)

I believe it was working some time before upgrade, but I do not remember when and what version exactly.

**Comment by HWiese1980** [comment]
I think I'm seeing this on 9.1.6 again. 

![image](https://user-images.githubusercontent.com/743912/197052065-27b645e0-2528-4409-8e31-7463f56b1710.png)

**Comment by leeoniya** [comment]
please open a new issue with the DataFrame JSON via:

Panel > Inspect > JSON > DataFrame JSON

**Comment by HWiese1980** [comment]
Your guess might be good already. I'll check that out. It's very likely. 

I'll open another issue if your guess turns out to be wrong. But I'm pretty sure it won't. 

Thanks

**Comment by shrx** [comment]
> please open a new issue with the DataFrame JSON via:
> 
> Panel > Inspect > JSON > DataFrame JSON (in select dropdown)
> 
> my guess is that there is no `null` there and it's just two sequential timestamps with a difference of several days (10/6 - 10/12) and your datasource is not returning an `interval` for us to auto-insert nulls into time gaps over the defined threshold.

Hi, just to clarify, in that case it's not possible to have a gap in the data based on a threshold timespan between two consecutive datapoints?

**Comment by leeoniya** [comment]
correct, adding a "disconnect over threshold" option is being considered: https://github.com/grafana/grafana/issues/7086#issuecomment-1241776217
