### ISSUE TITLE
Grafana variable metrics function e.g. `metrics(cpu)` - not working

### ISSUE THREAD

**Issue by felixtheflex** [grafana/grafana#44512]
**What happened**:

`metrics(cpu)` - is meant to return all cpu metric; but instead preview value is none

**What you expected to happen**:

 return all cpu metrics

**How to reproduce it (as minimally and precisely as possible)**:

Go to dashboard setting > variables > add new variables > 
  variable type: Query
  Name: foo
  Label: bar

Under Query Options: 
  Databa Source: Prometheus
  Query:  `metrics(cpu)`

**Anything else we need to know?**:

The following of similar construct works fine:

`label_values(label) `
`label_values(metric, label)`

similar issue: https://stackoverflow.com/questions/60874653/grafana-variable-for-all-prometheus-metrics-with-prefix
some docs: https://docs.huihoo.com/grafana/2.6/datasources/prometheus/index.html

- Grafana version:7.5.12

**Comment by felixtheflex** [comment]
yes; it is prometheus

**Comment by felixtheflex** [comment]
> Hello @felixtheflex! Thanks for raising the issue. Can you please be more specific, as in which datasource you use? From the links you posted I guess it's Prometheus?

yes; it is prometheus

**Comment by felixtheflex** [comment]
any updates please...?

**Comment by dsotirakis** [comment]
@grafana/observability-experience-squad looping you in!

**Comment by felixtheflex** [comment]
any updates please...?

**Comment by aocenas** [comment]
Trying to reproduce but seems this works fine now. Considering this is about 7.5 version and the newest one is 8.4, even if this was a bug in 7.5 we would not backport it that far. Please try with a newer version, if the problem still persists let us know.
