### ISSUE TITLE
[Change Request]: Mixed data source should ignore errors if one query is successful 

### ISSUE THREAD

**Issue by shalstea** [grafana/grafana#4453]
Grafana v 2.6.0
Opentsdb
Linux el7

We have configured grafana with multiple backends stores (2 opentsdb instances).  The metrics/tags are not replicated across the instances, the data is distinct.

Our tags include machine names and clusters.  Our dashboards need to query both opentsdb instances as we don't know which instance will have the data.  If we use a tag name that only exists in one opentsdb instance then that query returns results, however the other one returns a failure indicating that the tag does not exist.  The failure then blocks the display of the successfully returned result set.

An option to ignore failures would be useful.

Also note that when duplicating a query I can't change the data source - this would be very useful as well.

**Comment by torkelo** [comment]
Sounds like an issue for OpenTSDB fix? 

If OpenTSDB returns an error for missing tag, maybe they should return an empty result set instead?

**Comment by shalstea** [comment]
Well that is a possibility but it isn't clear what exactly one should expect in this case.  One could argue an error is warranted, but then there are no standards around this behavior.  In my opinion if there are multiple queries associated with a graph then it might be reasonable to treat an error as a no-result set and display the results found.

**Comment by gavinwoolley** [comment]
I would also like to see this feature working. We have a Panel with multiple WebApps feeding data into it. If one of those queries does not get a response, for whatever reason, it breaks the whole graph, rather than just showing me the graph with one error on it

**Comment by sutirtha1234** [comment]
As a similar use case, i have a High Availability Prometheus setup. Let's say 2 machines. I want to run a query on both machines and plot them on the same graph. I used Mixed resources for this but it seems the graph crashes if any one prometheus is down.

Query A: up{job="SLO"}   on datasource 1
Query B: up{job="SLO"}   on datasource 2

Both results are same and i want the graph to show the value even if one prometheus crashes. Federation/Thanos would probably solve this but that seems like a lot of setup for this case.
