### ISSUE TITLE
Template Variables broken with InfluxDB 0.11 RC1 ?

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4454]
![screen shot 2016-03-22 at 3 03 55 pm](https://cloud.githubusercontent.com/assets/406777/13969324/63662fa4-f03f-11e5-9e9c-267b3c4a8ea2.png)
![screen shot 2016-03-22 at 3 04 04 pm](https://cloud.githubusercontent.com/assets/406777/13969326/6369bd04-f03f-11e5-9176-a6724f792b0e.png)
![screen shot 2016-03-22 at 3 04 14 pm](https://cloud.githubusercontent.com/assets/406777/13969325/63698852-f03f-11e5-8721-2723ac045584.png)

Any suggestions ?

**Comment by bergquist** [comment]
Which version? We had a broken master for influxdb today for 3h

**Comment by deepujain** [comment]
Is the error in InfluxDB or Grafana ? (The query is returning result). InfluxDB version is Rc1(that was released few days ago)

**Comment by bergquist** [comment]
The error is in grafana.

**Comment by deepujain** [comment]
Do i upgrade Grafana ? Why is this issue closed ?

**Comment by bergquist** [comment]
Sorry for not getting back to you!

Upgrading Grafana should solve your issue.

**Comment by modax** [comment]
@bergquist could this be fixed in 2.6.1? I think it is pretty important

**Comment by andrenarchy** [comment]
I'd also appreciate a Grafana release that is compatible with Influx 0.11. @bergquist are there plans for a release in the near future?
