### ISSUE TITLE
$__rate_interval is broken in v8.3.4

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#44542]
**What happened**:

Using a simple rate query with `$__rate_interval`, the variable is substituted with an invalid `1m0` value.

![Screenshot 2022-01-27 09-13-24 rate interval bug](https://user-images.githubusercontent.com/3270755/151376210-e092b4b6-9a1f-4bc3-9589-e375253ecf1d.png)

**What you expected to happen**:

The variable is substituted with a valid PromQL duration like `60s`.

**How to reproduce it (as minimally and precisely as possible)**:

Use this query in Grafana v8.3.4:  
`rate(node_cpu_seconds_total[$__rate_interval])`

**Anything else we need to know?**:

Possibly the same issue as https://github.com/grafana/grafana/issues/44381.

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
@adeverteuil do you get this always on 8.3.4 ? Unable to replicate it with a plan new query:
https://play.grafana.org/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22demo.robustperception.io%22,%7B%22refId%22:%22A%22,%22instant%22:true,%22range%22:true,%22exemplar%22:true,%22expr%22:%22rate(node_cpu_seconds_total%5B$__rate_interval%5D)%22%7D%5D  

This should have been fixed in 8.3.4 but the error you get makes it look like it is interpolated but incorrectly. What is the data source scrub interval setting set to?

**Comment by adeverteuil** [comment]
I experimented a little and the issue seems to be correlated with the Prometheus data source.

Works normally: http://demo.robustperception.io:9090/ (v2.27.1)
Works normally: https://prometheus.demo.do.prometheus.io/ (v2.27.0)
Works normally: http://prometheus:9090 (my home Prometheus) (v2.30.0)
Breaks: https://35.208.239.24/prometheus (my training lab, must skip TLS verify) (v2.19.0)

`[1m0]` is definitely not valid in PromQL because it fails when I query the Prometheus demo directly:
https://prometheus.demo.do.prometheus.io/graph?g0.expr=rate(node_cpu_seconds_total%5B1m0%5D)&g0.tab=1&g0.stacked=0&g0.range_input=1h
http://demo.robustperception.io:9090/graph?g0.expr=rate(node_cpu_seconds_total%5B1m0%5D)&g0.tab=1&g0.stacked=0&g0.range_input=1h

I upgraded Prometheus from v2.19.0 to v2.33.0 on my lab (https://35.208.239.24/prometheus) and this fixed the issue.

I downloaded Prometheus v.2.19.3 and Grafana v8.4.3 locally and I'm able to reproduce the issue consistently.
https://github.com/prometheus/prometheus/releases/download/v2.19.3/prometheus-2.19.3.linux-amd64.tar.gz

This issue makes it difficult to inspect the `$__rate_interval`: https://github.com/grafana/grafana/issues/44434.

[Enabling the query log in Prometheus](https://prometheus.io/docs/guides/query-log/) didn't help to inspect what happens. Prometheus doesn't log the problem query and doesn't log an error.

I used Grafana's debug logs and found this:

---

**When the query works normally:**

```
DBUG[02-01|11:35:51] Sending query                            logger=tsdb.prometheus start=2022-02-01T15:35:51+0000 end=2022-02-01T16:35:51+0000 step=15s query=rate(node_cpu_seconds_total[1m0s])
```
Notice the `query=rate(node_cpu_seconds_total[1m0s])`.

**When the query fails:**

```
DBUG[02-01|11:35:24] Sending query                            logger=tsdb.prometheus start=2022-02-01T15:35:24+0000 end=2022-02-01T16:35:24+0000 step=15s query=rate(node_cpu_seconds_total[1m0s])         
EROR[02-01|11:35:24] Range query failed                       logger=tsdb.prometheus query=rate(node_cpu_seconds_total[1m0s]) err="bad_data: 1:29: parse error: bad duration syntax: \"1m0\""              
EROR[02-01|11:35:24] error processing cache middleware        logger=cache.query.middleware error="{\"results\":{\"A\":{\"error\":\"bad_data: 1:29: parse error: bad duration syntax: \\\"1m0\\\"\"}}}\n: d
atasource responded with an error"
```

Notice the same `query=rate(node_cpu_seconds_total[1m0s])` but the error message `parse error: bad duration syntax: "1m0"`.

---

So what I think happens is that Grafana is interpolating `$__rate_interval` with `1m0s`, and this probably changed since Grafana v8.4.3.
Something happened between Prometheus v2.19 and v2.27 in regards to syntax like `[1m0s]` ([time duration concatenation](https://prometheus.io/docs/prometheus/latest/querying/basics/#time-durations)). It caused a bug in v2.19, and the error message complained as `[1m0]` being invalid (notice the 's' is missing in the error message), but in the latest version of Prometheus, using `[1m0s]` is valid.

I believe the change came in Prometheus v2.21.0.
https://github.com/prometheus/prometheus/blob/main/CHANGELOG.md#2210--2020-09-11
"[ENHANCEMENT] Support composite durations in PromQL, config and UI, e.g. 1h30m."

I suggest the solution to fix those dashboards and Explore errors is to upgrade Prometheus.

**Comment by ccitops** [comment]
Or the Grafana devs can revert whatever they changed that introduced this sudden breakage. The suggestion to upgrade prometheus isn't an option for everyone, for example, I am running the latest Ubuntu LTS server and there are no package updates for prom. And its not fair either to expect people to compile prom from source to work around that fact.

Can we please have whatever introduced this problem in grafana suddenly undone?

**Comment by chaitan94** [comment]
We just faced this issue as well. After upgrading our prometheus to latest version (2.32.0), it went away. We were using 2.4.0 till now.

**Comment by ivanahuckova** [comment]
This is an issue with pre-v2.22.0 versions of Prometheus. Updating to v2.22.0+ Prometheus fixes the issue.
More here: https://github.com/grafana/grafana/issues/44251

**Comment by ivanahuckova** [comment]
> This issue makes it difficult to inspect the $__rate_interval: https://github.com/grafana/grafana/issues/44434.
Btw with https://github.com/grafana/grafana/pull/44802 merged couple days ago you can find what interval/step was used. It doesn't show the `$__rate_interval` though. 
![image](https://user-images.githubusercontent.com/30407135/152802272-f2259180-6f10-467d-920e-7a901687cc97.png)
