### ISSUE TITLE
[Question] Trouble with Elastic search annotations showing 

### ISSUE THREAD

**Issue by cr42** [grafana/grafana#4456]
Hi,
My annotations aren't showing up on my graphs. I'm not sure what I'm missing.

I'm using Elasticsearch as my annotations datasource
I'm using Grafana 2.6.0
I'm running Grafana on Windows server 2003

Here's a screenshot of the settings. The chrome dev tools indicate that the annotation is correctly being queried.

![image](https://cloud.githubusercontent.com/assets/18017377/13971602/95bcd3ea-f04e-11e5-8759-3fac8709faa1.png)

For clarity grafana is sending the following request to elasticsearch:
`{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"events"}
{"fields":["@timestamp","_source"],"query":{"filtered":{"query":{"bool":{"should":[{"query_string":{"query":"*"}}]}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"from":1454557319010,"to":1456880057826}}}]}}}},"size":10000}`

This receives the response:
`{"responses":[{"took":7,"timed_out":false,"_shards":{"total":5,"successful":5,"failed":0},"hits":{"total":1,"max_score":1.0,"hits":[{"_index":"events","_type":"test","_id":"1","_score":1.0,"_source":{
    "tags" : ["test","start"],
    "desc" : "I hope this works",
    "message" : "Just a test of events for grafana. Test start. ",
    "@timestamp" : [1455668868001]
},"fields":{"@timestamp":[1455668868001]}}]}}]}`

The annotation should show up around the date 2/18 on the graph but I don't see anything. Is there a problem with the field mapping or with the schema of the annotation? Any help is appreciated.

**Comment by volter** [comment]
Put "message" (without quotes) into Text box.

**Comment by cr42** [comment]
I tried that. I also tried explicitly typing "@timestamp" in the Time field mapping, "desc" in the Title field mapping and "tags" in the Tags field to match the ES schema. None of these fix the issue.

**Comment by cr42** [comment]
I was able to find the problem. The ES data for @timestamp was an int type rather than a date type. I changed the @timestamp value to "2016-02-17T00:30:00.800Z" in ES and now Grafana correctly shows the annotation.

**Comment by ZSkowronS** [comment]
I don't think this bug should be closed. When "time" field is a date in Elasticsearch, but in epoch format, Grafana doesn't show the annotations.
Tested on Grafana 4.4.3.

**Comment by torkelo** [comment]
@ZSkowronS strange, works here. what is the index mapping?

**Comment by ZSkowronS** [comment]
My index mapping:
PUT jmeter-annotations
{
    "settings": {
        "number_of_shards": 1,
        "number_of_replicas": 0,
        "index.refresh_interval": "5s"
    },
    "mappings": {
        "annotations": {
            "properties": {
                "taskId": {
                    "type": "keyword"
                },
                "tag": {
                    "type": "keyword"
                },
                "title": {
                    "type": "text"
                },
                "description": {
                    "type": "text"
                },
                "time": {
                    "type": "date",
		            "format": "epoch_millis"
                }
            }
        }
    }
}

When I change "epoch_millis" to "yyyy-MM-dd HH:mm:ss.SSSZ" everything works.
What is odd, is that this affects only display of annotations. When I displayed this data on a graph Grafana did not have any problem.

**Comment by roidelapluie** [comment]
Same here

**Comment by roidelapluie** [comment]
Okay:

curl 127.0.0.127.0.0.1:9200/annotations/deployments/foo2
{"_index":"annotations","_type":"deployments","_id":"foo2","_version":2,"found":true,"_source":{"name":"test", "@timestamp": "1507644863000"}}

curl 127.0.0.127.0.0.1:9200/annotations/deployments/foo3
{"_index":"annotations","_type":"deployments","_id":"foo2","_version":2,"found":true,"_source":{"name":"test", "@timestamp": 1507644863000"}}

**Comment by roidelapluie** [comment]
foo3 works (date it datetime but in JSON it is an integer)

**Comment by ctide** [comment]
Was seeing the same problem, so I went and fixed it. moment.utc chokes on strings, so need to parseInt the input before passing it along to handle the various ways ES will send back data.
