### ISSUE TITLE
Format the "Start Time" column in Tempo Search Panel

### ISSUE THREAD

**Issue by connorlindsey** [grafana/grafana#44562]
### Discussed in https://github.com/grafana/grafana/discussions/40667

<div type='discussions-op-text'>

<sup>Originally posted by **annanay25** October 20, 2021</sup>
At the moment, the start time panel is really hard to read and make sense of, I usually just gloss over it. It would be interesting to display the time-diff between now and the trace start time, which would read like `1m ago` / `30s ago`, and is easier for human consumption. However, this might make sense upto the 1h mark beyond which we might want to use the real timestamp, but I think the Grafana team will know how to handle this better!

![Screenshot from 2021-10-19 15-27-58](https://user-images.githubusercontent.com/10982987/138043721-bc1cbe9c-a71a-44ca-bcd1-e15b1eb8572f.png)

</div>

**Comment by tharun208** [comment]
@connorlindsey I like to work on this

**Comment by m1hanick** [comment]
Is there a way to disable this formatting?
We'd like to draw a time series graph of our traces, just like the Jaeger GUI does.
But without timestamp values, we cannot

**Comment by connorlindsey** [comment]
Hey @m1hanick, going to cc our tracing team on this @joey-grafana

**Comment by m1hanick** [comment]
Here is an example of what we'd like to achieve (now we're using Jaeger datasource, but seeking a way to migrate to Tempo)
<img width="962" alt="image" src="https://user-images.githubusercontent.com/52662457/188677594-40334f64-93fb-45e7-b840-e5a15ae63479.png">

**Comment by joey-grafana** [comment]
Thanks for reaching out. So you're right about the time series needing a time field. At the moment the closest we have to a time field is probably the start time field. This is the case for both Jaeger & Tempo.

We can probably take a similar approach with Tempo that we did with Jaeger. Not sure how disabling the formatting would solve this. Can you open a separate issue - which we can add to the backlog.

**Comment by m1hanick** [comment]
@joey-grafana 
honestly speaking, we were trying to play with Tempo time-series graph in the desire to overcome the issue of wrong datalinks: #54768
I managed to disable this "Start time formatting", and finally I got the graph
But it has the same problem with datalinks getting values from opposite data-points
