### ISSUE TITLE
Sub second granularity on kairosdb

### ISSUE THREAD

**Issue by javicho21** [grafana/grafana#4457]
[Question]
I'm trying to send sensor data via kairosdb to grafana which will have around 40 values per second. I was wondering if there was a way to display this data in grafana. At the moment the most granular I can get is up to 1 minute of resolution. Can someone please advise if this is possible*?

*I've seen posts regarding how to do this if using InfluxDB but nothing for KairosDB.

Also, this is a requirement for only one type of data that I'm inserting. The rest of my data works just fine with 1 minute resolution and if possible I'd like to be able to specify which graphs have sub-second granularity and which do not.

Ex
* What grafana version are you using?
* What datasource are you using?
* What OS are you running grafana on?

**Comment by torkelo** [comment]
you will have to ask KairosDB devs about that, you can checkout the code for the grafana integration here: https://github.com/grafana/kairosdb-datasource

**Comment by javicho21** [comment]
Hi Torkelo and thanks for your reply.

I'm able to insert the data into the database just fine. I am unable to visualize that data in Grafana which I believe is not a kairosdb question but a Grafana question. I'm not sure why you referred me to a Kairosdb dev. 

Can you please clarify your comment?

Sincerely

Javier

**Comment by torkelo** [comment]
well the question is at what resolution does KairosDB return data? Grafana support sub second resolution metrics fine, so it's likely an issue with the KairosDB data source or KairosDB itself

**Comment by javicho21** [comment]
Kairosdb supports milliseconds resolution. Where can I tweak Grafana to support milliseconds resolution?

**Comment by torkelo** [comment]
the code for the kairosdb data source is here:
https://github.com/grafana/kairosdb-datasource/blob/master/datasource.js

Not sure where the datapoints are transformed.
