### ISSUE TITLE
Docs feedback: /developers/plugins/add-support-for-variables.md

### ISSUE THREAD

**Issue by johndwalker** [grafana/grafana#44572]
"[Deprecation warning] LocationSrv: update is deprecated. Use partial, push or replace instead"

https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/#set-a-variable-from-your-plugin

The example should be updated with partial, push, or replace.

**Comment by johndwalker** [comment]
Also, there is no mention of any function other than update in the LocationSrv docs:

https://grafana.com/docs/grafana/latest/packages_api/runtime/locationsrv/

**Comment by mckn** [comment]
Awesome feedback! Will have a look at it today.
