### ISSUE TITLE
[Question] I can't edit the property of Grafana dashboards

### ISSUE THREAD

**Issue by GhostComputing** [grafana/grafana#4458]
When I modify the property of dashboards, as the following screen capture shown:

<img width="1266" alt="2016-03-23 11 45 27" src="https://cloud.githubusercontent.com/assets/1625098/13975110/01679a82-f0ed-11e5-9266-daff4e4e7d72.png">

Limit number to 10 -> 100

After my modification, it works, but when I refresh my page, back to the old settings, and I can't find any 'save' button when I modify the dashboards ( I'm the admin).

**Comment by bergquist** [comment]
The Home dashboard cannot be modified from the GUI.
We will make home dashboard configurable in the future. But for now you can only change it by editing the /public/dashboard/home.json file.
