### ISSUE TITLE
Wrong stacked graph rendering with flot

### ISSUE THREAD

**Issue by sbarrier** [grafana/grafana#4459]
The issue is with Grafana 2.6.0 (64 bits) on Linux Centos 6.x with graphite 0.9.15 source.

As you can see here is the stacked version:

![stacked_gfx](https://cloud.githubusercontent.com/assets/4797999/13982948/02be9374-f0aa-11e5-88df-0acb511dcb5a.png)

and the non stacked version:

![non_stacked_gfx](https://cloud.githubusercontent.com/assets/4797999/13982949/02ee1bbc-f0aa-11e5-9af6-a6ffe3179cdc.png)

the stacked version is missing the two spikes.

Max data points is set to _auto_ 
Stacked Values _Individual_
Rendering is set to _flot_

Switching to Rendering _Graphite PNG_ produce the right one:

![stacked_grapite_gfx](https://cloud.githubusercontent.com/assets/4797999/13983290/0185a630-f0ac-11e5-9781-4cc5f3354f75.png)

**Comment by torkelo** [comment]
be sure your "Null point mode" option (in display styles tab) is set to null as zero when using stack. Stacking requires that all series and all points have a value, it does not stack null values
