### ISSUE TITLE
Unable to add secure headers to grafana session cookie 

### ISSUE THREAD

**Issue by YamasakiRhys** [grafana/grafana#44617]
I am having some issues with trying to configure grafana cookie to be secure as shown in image below:

![image](https://user-images.githubusercontent.com/18525628/151635658-e53b0e5e-948a-4e9c-8ab6-a7e2974f5187.png)

I tried modifying the grafana.ini file by adding the configuration changes suggested through the docs, but no change has been seen when restarting grafana.  

When calling the /grafana/login api, it's going through a proxy.  

Any help or suggestions on a solution would be appreciated.

**Comment by joshhunt** [comment]
Having trouble reproducing this using Grafana to serve HTTPS, or using an HTTPS reverse proxy.

<img width="1151" alt="Screen Shot 2022-01-31 at 12 27 50" src="https://user-images.githubusercontent.com/46142/151727193-576d234c-cf84-4c80-8ace-4c0aea555b86.png">

My Grafana config:

```ini
[security]
cookie_secure = true
```

I did notice that when I had set just `cookie_secure = true` but accessed over http the Secure flag was not set, but I'm not sure if it would make much sense for a Secure cookie to by set on an HTTP response anyway.

**Comment by YamasakiRhys** [comment]
Thank you for your response!  

I forgot to mention this is for version 7.5.2.  But not sure if that matters in this case.
Over https, the secure flag for you was not and has not been set for the grafana_session cookie?
This came up as an issue with a security scan that we had done as the secure flag for this cookie are a potential problem.

**Comment by alex-restless** [comment]
This has also been flagged to me by pentesters in Grafana 9.4.3

**Comment by diegommm** [comment]
Couldn't reproduce on any of 7.5.2, 9.4.3 or latest. I'm using the following Docker compose:
<details><summary><code>compose.yaml</code> file</summary>

```yaml
services:
  grafana:
    build:
      dockerfile_inline: |
        # try changing the Grafana version in the next line, or remove from the colon onwards for latest
        FROM grafana/grafana:7.5.2

        USER root
        RUN apk update && apk upgrade && apk add openssl && \
          openssl req -x509 -newkey rsa:2048 -sha256 -days 3650 \
            -out /etc/grafana/server.crt \
            -keyout /etc/grafana/server.key \
            -nodes -subj "/C=ZA/ST=Western Cape/L=Cape Town/O=Fake Inc/OU=Fake Section/CN=127.0.0.1" && \
        chown grafana \
            /etc/grafana/server.crt \
            /etc/grafana/server.key
        USER grafana
    ports:
      - "3030:3030"
    configs:
      - source: grafana
        target: /etc/grafana/grafana.ini

configs:
  grafana:
    content: |
      [server]
      protocol = https
      http_port = 3030
      cert_file = /etc/grafana/server.crt
      cert_key = /etc/grafana/server.key
      [security]
      csrf_trusted_origins = 127.0.0.1
      cookie_secure = true
```

</details>

Then from the terminal I do get the `Secure` token in the `Set-Cookie` header. The following is the output for 7.5.2, the output for the other two versions is roughly the same (although one more cookie was later added, but no change for that token):

<details><summary>Shell output</summary>

```shell
$ curl 'https://127.0.0.1:3030/login' -k -D - -X POST -H 'content-type: application/json' \
--data-raw '{"user":"admin","password":"admin"}'
HTTP/1.1 200 OK
Cache-Control: no-cache
Content-Type: application/json
Expires: -1
Pragma: no-cache
Set-Cookie: grafana_session=6dda059ed6fb771748b018ae3b3f59cb; Path=/; Max-Age=2592000; HttpOnly; Secure; SameSite=Lax
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
Date: Thu, 01 Feb 2024 02:27:14 GMT
Content-Length: 23

{"message":"Logged in"}
```

</details>

Also trying from latest Firefox with [Cookie Quick Manager](https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/) extension I was able to verify for all the three versions (7.5.2, 9.4.3 and latest) had the `isSecure` flag set. The following is a screenshot for the cookie set by 7.5.2:

![Screenshot from 2024-01-31 23-40-44](https://github.com/grafana/grafana/assets/2166426/a975ec50-6abd-4915-b7c4-1c46ba98bd36)

Could you provide more information on your setup?

**Comment by diegommm** [comment]
Closing this since there hasn't been any activity since the last comment, and there are no consistent repro steps. Please, feel free to reopen if this is observed again, and you have repro steps or more info.
