### ISSUE TITLE
Loki LogQL: unpack doesn't autocomplete

### ISSUE THREAD

**Issue by danpoltawski** [grafana/grafana#44623]
**What happened**: 
Typing a loki query into the explore view and [unpack](https://grafana.com/docs/loki/latest/logql/log_queries/#unpack) didn't get offered as autocomplete suggestion. Only `unwrap` - this confuses me when writing loki queries.

**What you expected to happen**:
`unpack` is offered as an autocomplete suggestion.

**How to reproduce it (as minimally and precisely as possible)**:
* Go to the loki explore view
* Type a query (e.g. `{type="generic"} | unpack`)
* When typing `unpack` notice that `unwrap` is the only option offered

![Screenshot 2022-01-30 at 09 40 34](https://user-images.githubusercontent.com/533249/151694599-13ccc45b-5b24-43d6-8a6d-a1fa8e0e136a.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.3.4 (a551d74b11)
- Data source type & version: Loki (core)
- OS Grafana is installed on: Linux via Debian Package
- User OS & Browser: macOS (Edge/Firefox/Safari)

**Comment by glintik** [comment]
Hi @ivanahuckova,

Please take a look at my PR for this issue.
Also I discovered another bug with `TypeaheadInfo` related to shortened Operators info popup - #46574. PR also suggested.
