### ISSUE TITLE
$hosts$ in annotations

### ISSUE THREAD

**Issue by devilldog** [grafana/grafana#4463]
Hi I am using grafana 2.6.0 with influxdb .9 I am able to use a template and use the $host$ variable to get each dashboard for the specific host. Is there a way also use the host to select which annotations to show ? right now it shows all annotations can seem to gt the query syntax correct. here is the schema for my annotation db
`time	description	duration	host	tags	title	value
2016-03-22T22:26:24Z	"Chef Run xxxxx01"	"2.177008756"	"xxxxx01"	"dev"	"Chef Run Complete"	2`

**Comment by torkelo** [comment]
have your tried to use `host =~ /$host$`  in your annotation query?
