### ISSUE TITLE
carbon stops writing metrics

### ISSUE THREAD

**Issue by bcwazoku** [grafana/grafana#44635]
### Discussed in https://github.com/grafana/grafana/discussions/44634

<div type='discussions-op-text'>

<sup>Originally posted by **bcwazoku** January 31, 2022</sup>
Hi,
 After a few days or working properly, carbon randomly stops writing metrics to disk. The OS and the disks are otherwise fine. Restarting carbon-cache brings things back to normal.
Am I doing anything wrong in the configuration or is this a known issue ? 
Could somene help me please on how to fix this.
Attached is the log of console when it errors [carbon.txt](https://github.com/grafana/grafana/files/7968909/carbon.txt)
I am using 
graphite-carbon                       1.1.4-2

on debian 10 (buster)
</div>

**Comment by torkelo** [comment]
https://github.com/graphite-project/carbon
