### ISSUE TITLE
[Question] KariosDB + Templating + Multi-Select (display multiple CPU on one graph using templates)

### ISSUE THREAD

**Issue by vguhesan** [grafana/grafana#4464]
Grafana version..... v2.6.0
Datasource..... KariosDB
OS.................. Linux - CentOS 7

In the KariosDB, I have metrics under these metric-names:
cpu.0.cpu.user
cpu.1.cpu.user
...
cpu.30.cpu.user

Objective: I would like to plot all cpu.user in one graph without having to add 30-queries.
What I tried to do?

1. Under "templating", added a variable $cpuuser with the following:
Name.... cpuuser
Type..... query
Datasource.... kariosdb
Value Options.... metrics(cpu.user)
Regex...... /cpu.[0-9]*.cpu.user/
-- The above regular-expression gets rid of other metric-names like "aggregate.cpu.user" etc.
Multi-value Selection:
Enable.... checked
Multi format..... glob
Under Preview of values:  cpu.0.cpu.user    cpu.1.cpu.user ... cpu.30.cpu.user

2. Under a graph settings:
Metric.... $cpuuser
Aggregators.... rate(second)

When I only select one of the cpu's it works fine. But if I select two or more, the Template-Selector for "cpuuser" drop-down shows as "cpu.0.cpu.user+cpu.1.cpu.user". But graph shows as "No datapoints".

How can I manage such that I am graphing multiple CPUs on one graph?

Similarly, under General > "Templating options", if I select "Repeat Panel: cpuuser" and if multiple values are selected in the template, I can that Grafana generated N Graph panels but displays "No datapoints" under all the N graphs.

Please advise on how I can get this functionality to work.

Thank you.
#----------------------
Attachments: two-screens capturing the specified panels
![grafana_screen1](https://cloud.githubusercontent.com/assets/193960/13996022/3dcfe960-f102-11e5-95c4-57bf6777da12.png)
![grafana_screen2](https://cloud.githubusercontent.com/assets/193960/13996025/41900170-f102-11e5-9e3c-db9262da969a.png)

**Comment by torkelo** [comment]
not sure if KairosDB supports regex, please redirect your question to kairosdb mailing list or to this repo, https://github.com/grafana/kairosdb-datasource 

KairosDB has been removed from main repo as it was used by very few people.

**Comment by vguhesan** [comment]
The question was not about regex support in KariosDB but rather how to plot multiple entries on the same panel. Even if I remove the reg-expression from the template. The same issue happens.

**Comment by vguhesan** [comment]
@torkelo - are you saying that KariosDB's query mechanism may not support multiple metrics?
http://kairosdb.github.io/docs/build/html/restapi/QueryMetrics.html

And is that why you asked me to redirect that question to kariosdb mailing list?

I believe that when I choose multiple items for $cpuuser drop-down, the code behind the drop-down is sending a comma-seperated list instead of instantiating multiple Metric-Query rows.

Can you guide me to where this logic would reside? In the main Grafana GIT project or under the individual grafana-kairosdb GIT project?

This would help in looking at the code to figure out where it needs to be tweaked.

Thanks.

**Comment by torkelo** [comment]
the code for the kairosdb data source is here:
https://github.com/grafana/kairosdb-datasource  

Template variable interpolation is here:
https://github.com/grafana/kairosdb-datasource/blob/master/datasource.js#L285

**Comment by vguhesan** [comment]
@torkelo - much appreciated. thank you!

**Comment by gmangin** [comment]
@vguhesan did you find a solution ?

**Comment by vguhesan** [comment]
No - not through the Grafana UI. I've taken the route to pre-aggregate the
data on the receiving end into a new metric variable.

*Venkatt Guhesan*
