### ISSUE TITLE
Duplicating "type/type", "host/host", "type_instance/type_instance"

### ISSUE THREAD

**Issue by dbiers** [grafana/grafana#4465]
I've posted this on reddit as well to see if I can get a quick response.  In addition, I am not sure if this is a bug or if I have configured something incorrectly.  I've done everything the same on my CentOS6.x x64 system at home but this is on CentOS7.x x64

=============

I seem to be having an issue with a new deploy of Grafana on InfluxDB and CollectD showing duplicate "type=type/type/type".  I don't know what other way to explain it really, so a screenshot would be sufficient:

http://i.imgur.com/0b4nAE1.jpg

As you can see from the above, "type_instance" shows a "type_instance" under each type_instance field that is available (idle, interrupt, etc).  In addition to this, the same thing also happens for the "FROM host" field as well (shows "host, $host1, host, $host2, etc).

I think this is originating from Grafana as the influxDB database looks fine and I don't see any duplicates in there:

    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=idle
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=interrupt
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=nice
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=softirq
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=steal
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=system
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=user
    cpu_value,host=icingadns.localdomain,instance=0,type=cpu,type_instance=wait

To supplement this evidence, I've nuked the database and re-created it.  Alas, the fields are still being "duplicated" in Grafana.

Anyone seen this before?

    CentOS Linux release 7.2.1511 (Core)
    collectd.x86_64                     5.5.1-2.el7                        @epel
    grafana.x86_64                      2.6.0-1                            @grafana
    influxdb.x86_64                     0.11.0-1                           @influxdb

**Comment by torkelo** [comment]
InfluxDB 0.11 had breaking changes in their API, grafana master (3.0) supports influxdb 0.11 
Grafana 3.0 is soon to be released, but nighly packages are available here:
http://grafana.org/download/builds.html

**Comment by dbiers** [comment]
@torkelo Awesome, thanks.  Is there a release date set?  Are the nightly packages available via a yum repository?
