### ISSUE TITLE
Templating of data sources

### ISSUE THREAD

**Issue by evanbreznyik** [grafana/grafana#4466]
Can you template or script the data source of a metric?

Since I collect Graphite stats by region.zone (but have instances in region.zone.host spread out), it would be great if I could dynamically switch the data source from being just "Graphite" to the name of my collection/graphite node.

(In my case, the graphite data source is horrendously slow but the individual region.zone nodes I have for graphite are VERY fast.)

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/816

**Comment by torkelo** [comment]
not right now, but in future release (maybe 3.1 or something), this might be possible
