### ISSUE TITLE
Users added to Teams via External Group are not added to the correct Org

### ISSUE THREAD

**Issue by techgnosis** [grafana/grafana#44676]
**What happened**:
When a Team is backed by an External Group, and a new user logs in and their user is created in Grafana, that user is always assigned to the default Main Org (org 1), even if the Team is not part of the default Main Org

**What you expected to happen**:
When a Team is backed by an External Group, and a new user logs in and their user is created in Grafana, that user is assigned to the Org in which their Team belongs

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new Org. Let's say "NewOrg"
2. Create a Team inside NewOrg. Let's call it NewTeam
3. Assign an External Group to NewTeam. I used LDAP but I don't think it matters.
4. Log in to Grafana with a user that is part of the External Group
5. See that the user is assigned to "Main Org" instead of "NewOrg"

**Anything else we need to know?**:
If the user's external group/groups is part of multiple orgs, the user should be added to all those respective orgs.

**Environment**:
- Grafana version: All

**Comment by Jguer** [comment]
Hey @techgnosis , teamsync does not govern org membership, only team membership. 
For team sync to work correctly it assumes the member is part of the desired org

You can take a look at https://grafana.com/docs/grafana/latest/setup-grafana/configure-security/configure-authentication/ldap/#group-mappings to check how to map LDAP groups to different orgs before adding the group mapping to a team
