### ISSUE TITLE
Support paging in the dashboard search API

### ISSUE THREAD

**Issue by ldkingvivi** [grafana/grafana#4468]
Hi Guys,

We are trying to get all the dashboard we have by api, and only way we can think about right now is using the api search function to give a empty search, which suppose to return all the Dashboard, but lately we find out there's only 1000 dashboard return, and even we trying to give limit=2000, it still returns 1000 only, and looks like it's hard coded at    

sql.WriteString(fmt.Sprintf(" ORDER BY dashboard.title ASC LIMIT 1000"))

Is there other way we can get all the dashboard by API or maybe remove the 1000 hard code limit

**Comment by ldkingvivi** [comment]
any update on this

**Comment by ldkingvivi** [comment]
any update

**Comment by ldkingvivi** [comment]
still no update ?

**Comment by torkelo** [comment]
sorry for no update. Changed title to better match what needs to be done

**Comment by wleese** [comment]
At the very least, why not provide a parameter to set a higher limit?
Currently I cannot use the API because of this

**Comment by bergquist** [comment]
You can override the limit with `?limit=12345`

Paging still needs to be implemented. Which is possible now since all dashboards are stored in the database. Up to recently we stored dashboards in the database and on disk which made paging very hard to get right.

**Comment by marefr** [comment]
Fixed by #16458 and #16652
