### ISSUE TITLE
[Feature Request] Option to align/match Y-axis width 

### ISSUE THREAD

**Issue by khenderick** [grafana/grafana#4469]
I would love to have the Y-axises' width aligned on multiple graphs. 

For example on the below screenshot, I have 2 graphs with information about a given humidity sensor, and at the bottom a graph that shows the speed of my ventilation. However, the different type of axis data cause the axises to have a different width. This makes it harder to compare the graphs because they are basically shifted and stretched compared to each other.

![grafana_alignment](https://cloud.githubusercontent.com/assets/1453214/14010150/f38ebb74-f192-11e5-8b0b-df49c5196a9c.png)

I'm running versoin 2.6.0

**Comment by benrubson** [comment]
This is what @torkelo in #4349 and #4352, good idea :+1:

**Comment by timgriffiths** [comment]
+1

**Comment by steverweber** [comment]
also experienced this paper-cut.

**Comment by bbczeuz** [comment]
I'd like to have aligned zero lines (For example have Bits/second on the left and Packets/second on the right, but zero lines of both axes should be aligned).
Semi-Workaround: If both axes have the same (manual) min or max, one can align the zero lines; but in my case I split Rx and Tx to positive-Y and negative-Y, so this doesn't help in my application.

**Comment by sergeybinfinidat** [comment]
Hi, we also need this feature... How can I upvote?

**Comment by simPod** [comment]
The main challenge here is IMO that the y-axis widths would have to be computed in grafana and not flot

**Comment by hsmptg** [comment]
It is a pity that more than 2 years have passed since the first "Feature Request" and the problem remains! :(
Note that one reason for having several graphs in the same dashboard is the ability of correlate them, but if the time axes do not match that ability is compromised!

**Comment by simPod** [comment]
@torkelo that doesn't suffice when you want to compare several charts below. When graphs's starts and ends are not aligned, it's difficult to compare whether for example a peak on _chart A_ is somehow related to peak you see on _chart B_ below because those peaks are shifted. And you have to go and try to compare crosshairs manually for each such case.

**Comment by hsmptg** [comment]
The "Graph Tooltip option" even not being the perfect solution for me is an acceptable compromise.
Thanks

**Comment by nharkins** [comment]
+1 for this feature request. The Graph Tooltip option only helps a little. I often screenshot a grafana dashboard (multiple graphs, vertically stacked, and ideally aligned to show correlation) into post-mortem documents.

**Comment by nicolasStevenin** [comment]
+1 for this feature request.
Even if the Graph Tooltip helps, it's not perfect and an alignment is preferable. It's not very cumfortable to see multiple alignments in 3 or 4 graphs

**Comment by pcarlile** [comment]
+1 for this feature request.

**Comment by kyschouv** [comment]
This would be really helpful, as the legends on some graphs often have different widths, causing the graphs to be different sizes.

**Comment by Diglador** [comment]
real align will be nice

**Comment by meberli** [comment]
any news here?? this cannot be too hard..

**Comment by ManuCart** [comment]
long time waiting....
+1 please

**Comment by montanaflynn** [comment]
This would be very welcome indeed! I thought maybe thats what y-axis level was used for but I guess not.

**Comment by jgehrcke** [comment]
When I want to visually correlate time series then I need to make the time axes match.
I have done this for many years using classical plotting tools like gnuplot, matplotlib, Matlab, Mathematica.

I have just started using Grafana and am surprised that it is not yet able to do this, being all about comparing time series, and adding panels to a single dashboard.

How beautiful would it be if you could simply add panels in the vertical direction and have their time axes match precisely? Ha... :)

**Comment by svenito92** [comment]
Couldn't there be an option to set minimum width of y-Axis?
I think this should be possible similarly to the minimum width of the legend when placed "to the right". This would provide the possibility of a work-around if one can live with the reduced effective plot width.
![image](https://user-images.githubusercontent.com/61381861/75993950-88e89400-5efa-11ea-86ce-90f014bfee64.png)

**Comment by mradziwo** [comment]
+1!
cross-hair helps, but alignment of axis would be great - especially when one graph has values in thousands and the other just single digits

**Comment by AutoDoc1955** [comment]
+1.  What alternative graphing solutions might provide this?  It might be time to look for a better mousetrap.

**Comment by leeoniya** [comment]
https://github.com/leeoniya/uPlot has explicit axis sizing as well as cursor sync across multiple charts.

there's an active PR for uPlot in grafana:

https://github.com/grafana/grafana/pull/21835

**Comment by bradfc** [comment]
I'd also like to see this implemented.  I have a set of 5 time series for which I make direct comparisons.

There is a potential workaround that's a bit of a kludge, and that's to force the legends to have the same widths by specifying the number of displayed decimals.  It's not ideal but I can get pretty close to exact alignment.

Given some posts above, this may suggest a solution: rather than directly adjust the width of the graphs, provide an option to force the legends to have the same width using leading or trailing space.

**Comment by Yevgenie7** [comment]
+1

**Comment by marcelmfs** [comment]
I like a lot that we have the ability to hide the subtitles using keyboard shortcuts (keys p l), and it would be great to be able to also hide Y axis units, then the grid would(could?) align perfectly, with the crosshair hover being the way to show data from the hovered panel (or even on all panels). I guess having the flexibility is key, and keyboard shortcuts are AWESOME!

**Comment by MikOsle** [comment]
+1

**Comment by mpenn0** [comment]
+1

**Comment by bjoernbg** [comment]
+1

**Comment by harm-7** [comment]
+1

**Comment by Knocks83** [comment]
+1 more than 4 years later

**Comment by Kusado** [comment]
+1

**Comment by eni24** [comment]
+1

**Comment by leeoniya** [comment]
#29553 is only a partial fix for this, as it cannot support aligning the bottom chart without a right-side y axis. the rest of the fix must expose explicit control of the right gutter width.

**Comment by boboland1234** [comment]
As workaround I put the legend on the right and put a fixed width for the legend, choose the largest legend you have as ref.

**Comment by nabelekt** [comment]
That is what I usually do to get closest, but unfortunately that doesn't work for plots where the y-axis values and units use different widths.

**Comment by Strunck** [comment]
Grafana is a great tool and fun to work with. 
**This is really a missing feature.** 
I think it is a common task to have more than one graph panels with different units. To analyse them only one time axis is needed.

Maybe an option to group the panels would be straightforward to implement. A parameter for the start and end position of the x-axis would be shared across the panels within this group.

Another workaround is to adjust the decimals in the "Axes" sektion.

**Comment by 01findus** [comment]
+1  
I am doing Grafena now for 6h visualising time dependent data in one dashboard and already came across that missing feature. Overall its a great tool.

**Comment by hsmptg** [comment]
5 years have passed since this request and... NOTHING!
Are we asking the impossible?!?

**Comment by tgree** [comment]
The only workaround I've found is to set the units to "scientific notation" and then use the same number of decimal places on all plots.  /puke

**Comment by leeoniya** [comment]
for those hoping that there will be a simple "auto" toggle for this, please read carefully through the multiple complexties [1] which make this highly improbable without someone offering concrete, _generalizable_ ideas that will work properly for 1,000 differently-configured dashboards.

i'm personally more than happy to engage in productive discussion, but +1 comments and "i can't believe this isn't done yet!" are not going to move this forward at all.

[1] https://github.com/grafana/grafana/issues/33014#issuecomment-821541209

**Comment by steverweber** [comment]
shrug perhaps add a display option for the graph to set a custom width for example the CSS clas on flot-x-axis.tickLabel or style of the tickLabel .. that way a user can manually make them larger than needed in order to line up with the other graphs that have tickLabels that take up more space.. Sorry if this idea was already presented.

**Comment by leeoniya** [comment]
is this different than setting an explicit, static axis width, which we added in https://github.com/grafana/grafana/pull/29553? 🤔

**Comment by steverweber** [comment]
@leeoniya Ah cool problem solved from my point of view :)

**Comment by Knocks83** [comment]
> 
> 
> is this different than setting an explicit, static axis width, which we added in #29553? 🤔

It works, but only if both graphs have 1 or 2 y-axes. If one has 1 and the other has 2, they're still misaligned

![image](https://user-images.githubusercontent.com/22529815/125912128-cfa1a035-fa11-44d2-be4d-f28682170638.png)

**Comment by leeoniya** [comment]
> It works, but only if both graphs have 1 or 2 y-axes. If one has 1 and the other has 2, they're still misaligned

yeah, we'd have to add an option to explicitly control the chart's left/right padding, so the bottom chart can have right padding matched to the top chart's right axes widths.

**Comment by hoegge** [comment]
Yes this is definitely needed. There should be the option to make "alignement groups" of both left and right axes.

**Comment by VashCrHm** [comment]
![grafanaw](https://github.com/grafana/grafana/assets/60843351/902ad1cd-fe48-4546-a2b6-064d23e30f5a)

Grafana v10.0.3

**Comment by Strunck** [comment]
![Shared_axis](https://github.com/grafana/grafana/assets/64785859/ed14c75f-bc03-4da8-bf05-ee88e34e110e)

Here is an example from a software called ProfiSignal. I use it to monitor a cold room storage. Coming from PLC programming there is a lot of importance.

**Comment by spartako** [comment]
> is this different than setting an explicit, static axis width, which we added in #29553? 🤔

#29553 does not seem to allow to set the explicit static axis width on the state timeline (or state history) graphs either

**Comment by leeoniya** [comment]
added https://github.com/grafana/grafana/issues/85040 to track this.

**Comment by Superskyyy** [comment]
It's been eight years since the issue opened... We recently encountered the same requirement and need to stack a timeline with a time series, now the start of the time (x-axis) can't align with each other due to the legend.

**Comment by CRUDOBHM** [comment]
Hehe. This is really fucking stupid but it works for wholescreen dashboards:

Grab a blank mark: 
```
‎ 
```

Check how many letters does your values have in max(60 °C is 5 characters)
Go to unit, and add blank marks for every value to match character amount.

**Comment by Phalanxguard** [comment]
Just coming to look if someone mentioned this feature. Definitely something that's desirable to properly compare data.

**Comment by dr0bz** [comment]
> Hehe. This is really fucking stupid but it works for wholescreen dashboards:
> 
> Grab a blank mark:
> 
> ```
> ‎ 
> ```
> 
> Check how many letters does your values have in max(60 °C is 5 characters) Go to unit, and add blank marks for every value to match character amount.


LMAO - it just works! Best solution so far!

**Comment by gelicia** [comment]
Hello everyone! I took a look at this and think the best solution would be to close this broad ticket so we can focus on specific ones that can solve this problem with known areas of Grafana. Grafana was a lot less developed as a product when this ticket was written, and as it stands now, there is no one great solution for this as it is.

I feel like we cover what people are looking for with the following tickets:

- Panel Groups: https://github.com/grafana/grafana/issues/10916
- Sharing a time axis https://github.com/grafana/grafana/issues/91614
- Add Y axis control on other timeline panels https://github.com/grafana/grafana/issues/85040 

If you have a use case that isn't covered by one of these please post a comment, and we can be sure it gets added. Thank you!
