### ISSUE TITLE
Table Panel: String dates should be parsed assuming utc instead of local time

### ISSUE THREAD

**Issue by Elfo404** [grafana/grafana#44708]
**What happened**:
When using the Table panel, date strings without timzone information are assumed to be in users' local timezone, unlike numeric dates which are always assumed to be UTC.

This cause issues when different people from different timezones are looking at the same dashboards as with the same data they'll see different results.

There's already an open PR to fix this behavior in the logs panel at https://github.com/grafana/grafana/pull/44664 with steps to reproduce the issue, and the thing happens in the table panel.

**What you expected to happen**:
String and numeric dates should be assumed to be UTC regardless of their type if no timezone is explicitly set.

**How to reproduce it (as minimally and precisely as possible)**:

Using `elasticsearch77`, create an index and insert a document having a date without timezone info:

```
curl -XPUT http://localhost:13200/without-tz -H "Content-Type: application/json" -d '{"mappings": {"properties": {"@timestamp": {"type": "date", "format": "yyyy-MM-dd HH:mm:ss"}}}}'

curl -XPUT http://localhost:13200/without-tz/_doc/example -H "Content-Type: application/json" -d '{ "@timestamp": "2022-01-31 13:30:00", "foo": "bar" }'
```

then configure the datasource to use that index (without-tx) and create a dashboard with 2 panels:

  -  count group by date histogram (timeseries panel)
  - logs or raw data (table panel).

now, depending on the timezone you live in (if you are in a UTC-like timezone then go in another country. changing your computer timezone manually works as well) you'll see that the logs panel time is not aligned with the one from the timeseries panel.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: N/A
- OS Grafana is installed on: 
- User OS & Browser: MacOs / FF 89
- Grafana plugins: N/A
- Others:

**Comment by annelaurefroment** [comment]
thanks, I'll follow the the issue. I think we can close the escalation.
Thank you again for all your work on this !
