### ISSUE TITLE
Improve connectivity errors handling

### ISSUE THREAD

**Issue by jifwin** [grafana/grafana#4471]
Hi
I've noticed that KairosDB plugin does not handle connectivity errors appropriately. For example: when datasource is down or there is an SSL handshake error Grafana throws errors like: "Cannot read property errors of undefined", "a.data is undefined" etc. As far as I understand Grafana expects response json to be in Kairos format. But when Kairos is unreachable, then response format is definitely not in such format (usually it's simply null). 

Javascript type errors are not really appropriate in such case. Error messages should be more meaningful, to give user a sign, that there's a network problem and not with his query. Since it's not easy to distinguish what type of network error occured, my initial proposal is to set a general network error message ("Connectivity error" or something similar).

**Comment by torkelo** [comment]
please reopen for the kairosdb plugin repo, https://github.com/grafana/kairosdb-datasource
