### ISSUE TITLE
XY Chart not respecting MIN MAX

### ISSUE THREAD

**Issue by OverWorldD** [grafana/grafana#44712]
Grafana 8

The XY Chart (alpha) does not respect set max and min override values for axis:
![image](https://user-images.githubusercontent.com/12225528/151979025-043ce635-e42c-41a7-8ef8-d4518e0812ff.png)
Or am I doing something Wrong here?

**Comment by zuchka** [comment]
Thanks for creating this issue, @OverWorldD 

Can you provide some of your raw, unfrmatted data so that the squads can quickly mock this up and test it?

**Comment by leeoniya** [comment]
there's no need for extra data, this is simply not in the code yet:

https://github.com/grafana/grafana/blob/984c95de6349a16679f56b889118297ab44f5956/public/app/plugins/panel/xychart/scatter.ts#L573

**Comment by OverWorldD** [comment]
Hi, okay so did I understand this correct you do not need my data? I believe so but just to be sure

**Comment by malmr** [comment]
Thank you for the explanation @leeoniya 
Are there any updates on this? I tried the new beta `9.1.0-beta1` but seems still not implemented.
