### ISSUE TITLE
Links with same URL but different port than the grafana URL are handled incorrectly

### ISSUE THREAD

**Issue by diericd** [grafana/grafana#44711]
**What happened**:

When using links in dashboard that have the same URL as the grafana instance but a different port the links appear to be treated as internal links. 

![grafana_url](https://user-images.githubusercontent.com/80964995/151977384-5067ca94-4ae0-4fa9-8ef0-d8a9872bc883.png)

![grafana_result](https://user-images.githubusercontent.com/80964995/151977372-5b147e33-4809-478e-bfaa-141d2c99ad54.png)

**What you expected to happen**:

I would expect the link to be handled as any other external link.

**How to reproduce it (as minimally and precisely as possible)**:

* Create a textpanel on a grafana instance with url: https://grafana.example.com
* Add a link  https://grafana.example.com:8888/some_target
* Save and click the link

**Environment**:
- Grafana version: 8.1.1
- Data source type & version: -
- OS Grafana is installed on: ubuntu
- User OS & Browser: ubuntu - chrome
- Grafana plugins: -
- Others: -

**Comment by diericd** [comment]
It seems that the stripBaseFromUrl  function from https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/location.ts does not take into account the port used in the url.

**Comment by zuchka** [comment]
Thanks for creating this issue, @diericd 

Are you using a reverse proxy? Testing this on localhost, I couldn't reproduce the error. Which is to say, I can run Grafana on localhost:3000 and link to prometheus on localhost:9090 without issue. I can test this with a reverse proxy and proper subdomain, but if you could share more details about your setup first, that would be great. Thanks!

**Comment by zuchka** [comment]
follow up: is your issue repeatable as a proper data link, or only when adding links to the text panel?

**Comment by diericd** [comment]
Hi, 

Our setup is indeed behind a reverse proxy but I can also recreate it locally by running grafana on port 80 or 443.  It is normal that you would not have the issue if grafana is run on http://localhost:3000 as the other URLs  will not match the beginning with "http://localhost:3000".  You should have this issue when running grafana on port 80 and using URL "http://localhost"  as the beginning of http://localhost:9000 matches "http://localhost" .  

This issue is also repeatable with proper data links: 
![localhost-link-error](https://user-images.githubusercontent.com/80964995/152999317-b2e91db0-11d8-42b6-9af1-bf2aa84c54ab.png)
![localhost-link](https://user-images.githubusercontent.com/80964995/152999319-4453defb-11a5-400d-bb64-17d85887b026.png)

Best regards!

**Comment by zuchka** [comment]
fwiw if you run one Grafana on `80` and another on, say `3001`, data links work when `Open in new tab` is selected"

https://user-images.githubusercontent.com/37156449/153241404-303f62f5-cba5-4ff2-b3c8-8186fd2be24d.mp4

**Comment by joshhunt** [comment]
Confirmed the issue occurs when Grafana is on an origin without an explicit port (http 80, or https 443), with the Markdown text panels.

Also noticed that the unit tests for location.test.ts will fail if in a scenario like this.
