### ISSUE TITLE
Cloudwatch datasource API error when alerting

### ISSUE THREAD

**Issue by Akisaji** [grafana/grafana#44722]
**What happened**:
Created a panel with datasource from cloudwatch and used the logs querry mode. Then i wanted to covert this into an alert with grafana 8 alerting and when i run the query there i receive an "API ERROR"
The query used is the following: `filter @message like /duration/ | stats count() as duration by bin(5m), @ log`
See screenshots below

**What you expected to happen**:
I expected the same graph to show as was created in the panel.

**How to reproduce it (as minimally and precisely as possible)**:
Running the query with 2 by statements in the alert creation section

**Anything else we need to know?**:
This is the panel i wanted to create the alert from:
![image](https://user-images.githubusercontent.com/43436777/152001488-e2a1d632-bdd2-4f13-a5fa-d292c484f1b7.png)

And when running this same query in the alert creation i get the following:
![image](https://user-images.githubusercontent.com/43436777/152001819-9598fffc-bb56-4210-bf58-c47bfa99fbf1.png)

When for example removing the `@log` from the query it functions:
![image](https://user-images.githubusercontent.com/43436777/152002023-7350ef3b-acab-4da4-8ceb-445242c3465c.png)

This looks kinda to be related to: https://github.com/grafana/grafana/issues/39711

**Environment**:
- Grafana version: Grafana v8.3.4 - docker
- Data source type & version: Cloudwatch 5.0.0
- OS Grafana is installed on: Kubernetes - official Grafana docker image
- User OS & Browser:  Arch/Firefox
- Grafana plugins:
- Others:

**Comment by sunker** [comment]
Seems like alert rules are not executing properly when the query returns more than one time series. Is this something you can look into @grafana/alerting-squad?

**Comment by Akisaji** [comment]
@zoltanbedi I doubt the response is helpful but here is a screenshot of the response when the API error occurs
![image](https://user-images.githubusercontent.com/43436777/154044948-f024630e-fb80-4fe0-9a8b-662eeed3588e.png)

**Comment by zoltanbedi** [comment]
Hah @Akisaji that indeed is not helpful 😄  The alerting squad is taking a look at this.

**Comment by Akisaji** [comment]
@zoltanbedi  to further drill down the issue this is what is logged in the grafana pod
`t=2022-02-15T10:40:06+0000 lvl=eror msg="API error" logger=context userId=0 orgId=1 uname= error="Failed to evaluate queries and expressions: failed to execute conditions: input data must be a wide series but got type not (input refid)" remote_addr=10.***
t=2022-02-15T10:40:06+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=1 uname= method=POST path=/api/v1/eval status=400 remote_addr=10.*** time_ms=3165 size=23 referer="https://grafana.***/alerting/new?returnTo=%2Falerting%2Flist"`

**Comment by zoltanbedi** [comment]
That is helpful thank you!

**Comment by gerobinson** [comment]
In alerting the data must be a wide series, which means that it has no string fields, and has a series of timestamps and values. I think `@log` adds a string field to the results:

> @log is a log group identifier in the form of account-id:log-group-name. When querying multiple log groups, this can be usefule to identify which log group a particular event belongs to.

https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/CWL_AnalyzeLogData-discoverable-fields.html

**Comment by Akisaji** [comment]
@gerobinson It is correct that in the query a string field was specified and this will be the cause of the error, i'm looking to rework the query so it will be only a timestamp and values.
Thx for the help
