### ISSUE TITLE
[regression] [8.3.3 => 8.3.4] Prometheus Metrics with gaps breaks alerting with NaN

### ISSUE THREAD

**Issue by vasekboch** [grafana/grafana#44735]
**What happened**:
When I have metric with some gap, reduce in alerting failes to calculate min (or any other value) and fails with NaN. It breaks whole alert, until gap is outside the time range.
![image](https://user-images.githubusercontent.com/1482932/152028226-cb795d41-1d5f-4db9-8509-69cb3218c488.png)

This worked on 8.3.3 without any problems. But its broken on 8.3.4. Probably related to this patch: https://github.com/grafana/grafana/pull/43622 

**What you expected to happen**:
Reduce in alerts shoud be able to process metric with gap. 

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Prometheus

**Comment by broferek** [comment]
This is a critical problem which breaks many of our alert rules using reduce expression and raises alerts which were not triggered in 8.3.3.
I thought that I could work around the problem ticking "instant" button but in certain rules using "count" reduction it doesn't work as I need to have the count of points over a given period of time.

We had to rollback to 8.3.3.

**Comment by zuchka** [comment]
@broferek just checking: these are alerts on a Prometheus data source, yes?

**Comment by broferek** [comment]
It's indeed a Prometheus data source.

**Comment by armandgrillet** [comment]
This should have been fixed in 8.3.6, can you confirm?

**Comment by broferek** [comment]
Great !

I've just upgraded to Grafana 8.4.0 and the problem is indeed solved.

Alerts containing NaN no longer trigger on my end.

I can see a new dropdown menu with strict mode activated by default in my alerts definition. I guess this is somehow related to the fix, isn't it ?

Let's also wait for the feedback of the author of the issue for a final confirmation.

**Comment by vasekboch** [comment]
Fixed. Thank You!
