### ISSUE TITLE
CloudWatch: "multi template variables are not supported for region" when using repeating rows

### ISSUE THREAD

**Issue by wjbuys** [grafana/grafana#44733]
(Originally reported as a comment in #20960, and this case is still not fixed as of 8.3.4)

I'm trying to make a graph with Repeating Rows for multiple AWS Regions, so I made a Template Variable with the Regions we're using:

![image](https://user-images.githubusercontent.com/31602/121754974-d1620a80-caca-11eb-90c6-d5f843e05fb2.png)

Then I added a repeating row for `$Region` to the dashboard, and tried to use the `$Region` variable as the `Region` field on the Cloudwatch query for the panels in this row. This works, and correctly displays all the graphs in multiple repeating rows, but unfortunately it always pops up an error message:

![image](https://user-images.githubusercontent.com/31602/121755047-05d5c680-cacb-11eb-912c-11fc2f308791.png)

_Originally posted by @wjbuys in https://github.com/grafana/grafana/issues/20960#issuecomment-859942465_

**Comment by justinTM** [comment]
across the board CloudWatch does not apear to support templating variables in a variety of places. I will try to open a PR soon.

**Comment by mourya92** [comment]
The exact problem exist for `Log Groups` as well. It is extremely common use-case to have multiple Log Groups in a single CW Log Insights query. But, when I use multi-template variables I get this error : 

```
CloudWatch templating error
Multi template variables are not supported for log groups
```
