### ISSUE TITLE
Unreadable error message

### ISSUE THREAD

**Issue by voroninp** [grafana/grafana#44746]
**What happened**:
I got a error when previewing alert rule. That's fine. But it's not fully readable.

**What you expected to happen**:
I expect the message to be fully on the screen.

**How to reproduce it (as minimally and precisely as possible)**:
Probably with using laptop with not huge screen?

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/9202028/152093286-3430ba3a-cf07-4799-84e3-1948ff9c3d21.png)

**Environment**:
- Grafana version: 8.2.0
- Data source type & version: Loki
- OS Grafana is installed on: IDK
- User OS & Browser: Windows 10, Chrome Version 97.0.4692.99 (64-bit)

**Comment by zuchka** [comment]
Thanks for creating this issue, @voroninp 

just curious: are you able to scroll to the right to view the rest of the message?

**Comment by voroninp** [comment]
@zuchka I can, but with touchpad it's quite painful, I always miss the point when I should stop. It's a bit easier with Shift+Arrow key.

**Comment by peterholmberg** [comment]
Fixed in 8.3.0 via https://github.com/grafana/grafana/pull/42445
