### ISSUE TITLE
[Bug] Error with multiple queries

### ISSUE THREAD

**Issue by nlamirault** [grafana/grafana#4475]
Grafana version : 2.5
InfluxDB 0.9.6
OS: Linux

I try to display metrics using Telegraf. With one query (display path usage for "/") from Grafana UI it works fine. I see the graph. Query in log is [1]
I try to add another query for disk usage for /home. I've got an error : 

Query in logs is [2]

Request details
Url	/api/datasources/proxy/1/query
Method	GET
Accept	application/json, text/plain, */*
Request parameters
u	
p	
q	SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" = '/' AND time > now() - 5m GROUP BY time(100ms) SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" = '/home' AND time > now() - 5m GROUP BY time(100ms)

Response : 
{
  "error": "error parsing query: found SELECT, expected ; at line 2, char 1"
}

Any idea why there is no ";" between the queries ?
Thanks

[1] : SELECT first(used_percent) AS used_percent FROM telegraf."default".disk WHERE path = '/' AND time > now() - 5m GROUP BY time(100ms)

[2]: SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" = '/' AND time > now() - 5m GROUP BY time(100ms) SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" = '/home' AND time > now() - 5m GROUP BY time(100ms)

**Comment by torkelo** [comment]
did you add two queries in the Grafana UI? Can you show panel json?

**Comment by nlamirault** [comment]
In the first screenshot, i disable the second query.
In the second, i enable 2 queries
In the third, i disable the first and enable the second.

![2016-03-25-113256_1683x804_scrot](https://cloud.githubusercontent.com/assets/29233/14042773/6e812ae8-f27d-11e5-8594-3cc330264029.png)
![2016-03-25-113309_1679x842_scrot](https://cloud.githubusercontent.com/assets/29233/14042774/6e814f5a-f27d-11e5-8685-55a322363840.png)
![2016-03-25-113432_1667x794_scrot](https://cloud.githubusercontent.com/assets/29233/14042789/9024ecfc-f27d-11e5-902f-e0efef94fe5a.png)

**Comment by torkelo** [comment]
strange, maybe you have a proxy that is removing the ";" ? try upgrading to 2.6,  no one else has reported anything like this for 2.5 or 2.6 so pretty strange

**Comment by nlamirault** [comment]
OK. I will upgrade to 2.6. Thanks.

**Comment by nlamirault** [comment]
I've got the same error using 2.6.0

**Comment by torkelo** [comment]
strange, maybe an issue with your influxdb server or setup? Multiple queries is working in all installs I have  (for example: http://play.grafana.org/dashboard/db/influxdb?panelId=1&fullscreen&edit)

and no one else has reported issues like this. any proxy ? What browser are you using?

**Comment by nlamirault** [comment]
i try many browser. I change my InfluxDB server and it works now. I will check this server's configuration. Thanks.
Sorry for noise

**Comment by nlamirault** [comment]
I've got a question : i suppose it's Grafana which make the multiple queries request, why a character would be missing?

**Comment by torkelo** [comment]
the queries are seperated by newline char

**Comment by StefanZoerner** [comment]
I have the same problem with 
* Grafana version: 3.0.0-pre, commit: v2.6.0-1629-gd3a4b7a, build date: 2016-03-31 06:27:08
and 
* InfluxDB Server: v0.12.0

{
  "error": "error parsing query: found SELECT, expected ; at line 2, char 1",
  "message": "error parsing query: found SELECT, expected ; at line 2, char 1"
}

I have two queries for one chart panel, same datasource, and InfluxDB seems to expect an semicolon. In the InfluxDB Admin console, the query causes the same error, and works fine with a ;

```
Request details

Url	/api/datasources/proxy/2/query
Method	GET
Accept	application/json, text/plain, */*
Request parameters

u	
p	
db	psutil
q	SELECT mean("free") FROM "virtual_memory" WHERE time > now() - 1h GROUP BY time(20m) fill(null) SELECT mean("available") FROM "virtual_memory" WHERE time > now() - 1h GROUP BY time(20m) fill(null)

```

**Comment by blacklensman** [comment]
Same here. I just upgrade to influxdb 0.12 and all the latest releases including going through Grafana 2.6 -> 3.0.  I have multiple dashboards with multiple queries that broke. You can look at the each series individually if you add semi-colons using the other query editor, but it will not plot all of them together on the same graph.  Also, the single stat graph populates the Add Query page with multiple queries.

 Inspector
Request
Response
JS Error

Request details

Url	/api/datasources/proxy/1/query
Method	GET
Accept	application/json, text/plain, */*
Request parameters

u	
p	
q	SELECT sum("value") FROM "smtad_accepted" WHERE time > now() - 6h GROUP BY time(5m) SELECT sum("value") FROM "spam" WHERE time > now() - 6h GROUP BY time(5m)

**Comment by torkelo** [comment]
Yea, it's a shame InfluxDB introduced this breaking change, any news about if they are going to fix it?

**Comment by jixuan1989** [comment]
the same issue. :(

**Comment by filipskokorevs** [comment]
Same problem here: Grafana 3.0 + Influxdb 12.0

**Comment by alekiv** [comment]
+1

**Comment by StefanZoerner** [comment]
Most simple workaround for me was changing to an older InfluxDB version.

The old packages are still available. 
https://s3.amazonaws.com/influxdb/

I changed to InfluxDB v0.9.5, which seems to work fine with Grafana 3.0.0

**Comment by gridlack** [comment]
InfluxDB v0.11.1 works too.

**Comment by bithive** [comment]
Just ran into this after upgrading to 2.6.0/0.12.0 from the Debian packages.

**Comment by jixuan1989** [comment]
Now I have a compromises: take advantage of  GROUP BY.
 
for example as nlamirault wants:
 
    1. SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" = '/' AND time > now() - 5m GROUP BY time(100ms) 

    2. SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" = '/home' AND time > now() - 5m GROUP BY time(100ms)

Solution 1:
We can write one SQL:

    SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE ("path" = '/' OR "path" = '/home' ) AND time > now() - 5m GROUP BY time(100ms),"path"

However, grafana does not support "()" by graphical interface, you can write it yourself.

Solution 2 (stupid but useful):
We can write one SQL:

    SELECT mean("used_percent") AS "used_percent" FROM "disk" WHERE "path" <> '/boot' AND "path" <> '/root' AND.... AND time > now() - 5m GROUP BY time(100ms),"path"

just emulate all the possible path you do not care...

**Comment by torkelo** [comment]
The multi query issue is fixed I master and latest nightly

**Comment by filipskokorevs** [comment]
Thanks for the quick solution. Works like a charm. Grafana nightly (from today) + influxdb 0.12.

**Comment by luqasz** [comment]
Can you release it in 2.6 ?
