### ISSUE TITLE
Loki Log Volume: Show error in the UI not on the console

### ISSUE THREAD

**Issue by kavirajk** [grafana/grafana#44753]
**What happened**:

When using `fullRangeLogsVolume` feature toggle in Grafana 8.3 with Loki, any error in actual Log Volume Histogram metrics query sent from Grafana is currently show on the console.

<img width="534" alt="Screenshot 2022-01-24 at 22 42 44" src="https://user-images.githubusercontent.com/3735252/152130461-5291de0b-96ba-4b1f-a1a9-42ae5381a604.png">

This means that there is no way from the Grafana UI to differentiate between a log histogram that failed to load due to timeout versus failure due to a parser error, versus failure due to some other issue. 

**What you expected to happen**:

There are a variety of reasons that the log volume histogram could fail to load. We want the user to be able to determine the reason the histogram failed to load without having to look in the console. 

Some of the possible reasons the log histogram could fail to load:
1. The query to generate the log volume histogram could have timed out. Grafana Cloud is instituting a 10 second timeout for generating the log volume histogram, which is a more aggressive timeout than gets applied to other queries. There will be no 10 second timeout for OSS Loki users - instead the log volume histogram query will timeout at whatever the timeout is for all Loki queries. In either case, if a timeout occurs, we want to surface to the user that the histogram failed to load due to timeout. The original error message that the observability squad had used would work well here: `Request timed out. Please make your query more specific and try again.`
<img width="720" alt="Screen Shot 2022-02-07 at 8 15 26 PM" src="https://user-images.githubusercontent.com/9610816/152917122-73ba85d2-2559-49d5-8929-511c5755b39a.png">

2. The log volume histogram could fail to load because of a parser error. For example, a user could append a `| json` to their logs query, even though not all of their log lines are json format. Today when this happens, the histogram fails to render and says to 'check the console logs for more details.' This decision was made [here](https://github.com/grafana/grafana/pull/42534) so that we didn't print a massive error message like this:
<img width="1636" alt="ugly error message" src="https://user-images.githubusercontent.com/9610816/152917635-df0d6195-c0ff-45f4-acb8-3553bc7344e6.png">

However, now we have a much more generic error message that doesn't differentiate between this kind of failure, and a timeout failure:
<img width="1481" alt="parserfailure2" src="https://user-images.githubusercontent.com/9610816/152918731-532d5c8b-02c6-4ab3-af14-2cbed4c45d05.png">

The ideal behavior would be to add `__error__=""` to the underlying Log Volume metric query so that the query would complete, while also indicating to the user that the histogram only represents the non-erroring lines. The UI would show a histogram, but also add an error message like: `Error parsing some of the logs. Histogram showing distribution of non-erroring log lines`. This would mirror the behavior of the explore window on a parser error. There we show an error that says `error parsing the lines`, but also show the log lines. 
![Screen Shot 2022-02-04 at 1 19 40 PM](https://user-images.githubusercontent.com/9610816/152918231-4b927119-ad2e-4794-b692-8e2e1aff8b0a.png)

3. The log volume histogram could fail to load for some other reason that's not a timeout or a parser error. In this case, we'd like to print the error message to the UI. We believe that the error messages for these other failure cases should be concise, so we're fine printing them directly to the UI. If users report frustration due to unwieldy error messages for certain failure scenarios, we can dive into those and fix them in later iterations. 

**How to reproduce it (as minimally and precisely as possible)**:

Run Grafana8.3 + Loki datasource with config[feature_toggles][enable]=`fullRangeLogsVolume` 

**Anything else we need to know?**:

The Loki team would like to have this fixed before enabling the full range log histogram by default. 

**Environment**:
- Grafana version: 8.3
- Data source type & version: Loki 2.4.2
- OS Grafana is installed on: Linux
- User OS & Browser: Linux & Chrome
- Grafana plugins:
- Others:

**Comment by tharun208** [comment]
@kavirajk I like to work on this issue

**Comment by 09jvilla** [comment]
Added a bit more detail to the description, and consolidated some of the asks from https://github.com/grafana/grafana/issues/44755.

**Comment by gabor** [comment]
@kavirajk about the part with adding `| __error__=""` ... i did some tests, and if i add it to the query, then no errors are returned... so, how do we detect that there were some errors?

**Comment by gabor** [comment]
yes, from what i can see, the response-format is different for metric-query vs log-line-query. for log-line-query we can detect the "we have both data and error" situation, but for metric queries i do not see such an option. but maybe i'm missing something.. @kavirajk any ideas?

**Comment by kavirajk** [comment]
Yes @gabor is right. it depends on response from Loki. In log query we can have partial results + error but on metric query it's either results or error.

I also don't know what right solution here.

Ideally, Grafana can make request without `__error__=""`, and if loki returns `ParseError` then Grafana can make another request without `__error__=""` to get the results. But that may cause at most 2 expensive metric query for single log query. And it's bad idea to overload Loki in this way.

Another option could be

wait till Log query returns and if there are parseError, then add `__error__=""` to the log volume query, else don't. this UX behavior delays the visualization of Log Volume Histogram a little bit. But it's safe IMHO because doesn't overload Loki.
Does this UX behavior acceptable?

**Comment by kavirajk** [comment]
> @kavirajk -- I imagine that returning a count of all lines (regardless of whether there are log formatting errors or not) is difficult for Loki to do? can you confirm either way?

That would be a breaking change for all the "metrics" query responses. In Loki, AFAIK, no differentiation in response structure between `count_over_time*` or `sum_over_time` or any other metric queries. So returning partial count with error would break the guarantee we have with all the metric queries I think. probably /cc @slim-bean can correct if I'm missing anything.

And +1 for [a]

**Comment by kavirajk** [comment]
> That would be a breaking change for all the "metrics" query responses. In Loki, AFAIK, no differentiation in response structure between count_over_time* or sum_over_time or any other metric queries. So returning partial count with error would break the guarantee we have with all the metric queries I think. probably /cc @slim-bean can correct if I'm missing anything.
I checked with the team internally

I also double checked with the team. Changing this behavior of metric query to say return partial count (or partial sum or similar) is a breaking change. And we would break the compatibility with Prometheus. Note: These are the metric queries we also use in Recording rules, alerts, etc. So partial results are incorrect for metric queries
/cc @09jvilla

**Comment by 09jvilla** [comment]
Got it - thanks for checking in Kavi. I'm gonna close this one for now since we've made a decision to simply error out the histogram on parser errors. We can revisit later if needed.
