### ISSUE TITLE
Instrumentation: The HTTP status code are not instrumented correctly for a few handlers. 

### ISSUE THREAD

**Issue by bergquist** [grafana/grafana#44776]
```javascript
[
  "/api/live/ws", 
  "/api/live/push/:streamId",
  "/api/datasources/proxy/:id/*"
]
``` 

Are sometimes instrumented with status code `0`. 

https://ops.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22ops-cortex%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%20by%20(handler)%20(grafana_http_request_duration_seconds_count%7Bstatus_code%3D%5C%220%5C%22%7D)%22,%22range%22:false,%22exemplar%22:false,%22instant%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

this is quite confusing for alerts / visualizations.

**Comment by FZambia** [comment]
For `/api/live/ws` and `/api/live/push/:streamId` zero status code reported since both using WebSocket (connection hijacked). Do we want 101 instead of 0 for them?

**Comment by tolzhabayev** [comment]
Still relevant @bergquist ?

**Comment by bergquist** [comment]
@tolzhabayev yes. I'll share a link with you on slack

**Comment by tolzhabayev** [comment]
[The link](https://ops.grafana-ops.net/explore?orgId=1&left=%7B%22datasource%22:%22000000193%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22000000193%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bcluster%3D%5C%22ops-us-east-0%5C%22,%20slug%3D%5C%22ops%5C%22%7D%20%7C%3D%20%5C%22request%20instrumented%20as%20unknown%5C%22%22,%22queryType%22:%22range%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D) Carl shared with me, to log it here.
