### ISSUE TITLE
Variables: Submenu for variables does not show for snapshots

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#44773]
With the introduction of a keyed variable state in #44642 snapshots the submenu with all the variable pickers no longer shows any pickers.

**OBS**
The variable system is very limited and doesn't really work in snapshots because there is no data requests made in a snapshot. So this issue has low prio.

1. Open a dashboard with any variable with at least one picker
![image](https://user-images.githubusercontent.com/562238/152164373-9972980d-8d46-435e-9ea9-c1b92228cd0f.png)
2. Create a local snapshot of the dashboard
3. Navigate to the snapshot
4. Submenu doesn't show any pickers **[NOT OK]**
![image](https://user-images.githubusercontent.com/562238/152164420-85a71ec1-9af0-4f6f-ad50-84ccf5a128f3.png)

**Comment by ashharrison90** [comment]
@grafana/user-essentials gonna close this given we solved it in the mob
