### ISSUE TITLE
[Question] Disappearing data when zooming

### ISSUE THREAD

**Issue by geekdave** [grafana/grafana#4478]
First of all, thank you so much for your work on Grafana!  

Grafana 2.6 / Graphite backend.  Running on ubuntu 14 on docker image.

Sending data via the `gauge` data type.

On certain dashboards, when I am looking at older data, I can see all the data as long as I'm zoomed out to show 6 hours or more.  Note all 3 metrics are showing.

![grafana_-_otto_stats_dashboard](https://cloud.githubusercontent.com/assets/1438478/14048802/4a28a38a-f276-11e5-8e55-81dcb80dde50.gif)

However, if I zoom in to see *less than 6 hours of data*, one of the metrics is graphed but the other two disappear.

Perhaps alarmingly the data seems to look different at this zoom level.  See for instance the data around 13:30

![grafana_-_otto_stats_dashboard](https://cloud.githubusercontent.com/assets/1438478/14048829/818640ee-f276-11e5-9204-8bb39efa79d5.gif)

To debug the two missing metrics, I inspected the Network tab and saw that indeed all metrics are coming back null:

```
[
  {
    "target": "Online VMs",
    "datapoints": [
      [
        null,
        1458843000
      ],
      [
        null,
        1458843030
      ],
      [
        null,
        1458843060
      ],
```

Here are my graphite configs:

```
$ more storage-schemas.conf 
[stats]
pattern = ^stats.*
retentions = 10s:6h,1min:6d,10min:1800d

$ more storage-aggregation.conf 
[default_average]
pattern = .*
xFilesFactor = 0.5
aggregationMethod = max
```

Settings:

![grafana_-_otto_stats_dashboard](https://cloud.githubusercontent.com/assets/1438478/14048974/8bcc372e-f277-11e5-9447-575fc74bc7ce.gif)

![grafana_-_otto_stats_dashboard](https://cloud.githubusercontent.com/assets/1438478/14048980/974b4f18-f277-11e5-8697-dd5f407cb328.gif)

![grafana_-_otto_stats_dashboard](https://cloud.githubusercontent.com/assets/1438478/14048987/a492933e-f277-11e5-8c6a-376644019ec2.gif)

Any help or theories would be greatly appreciated.  Thanks so much!

**Comment by torkelo** [comment]
Not sure, something wrong with your graphite config, but cant figure out what.
