### ISSUE TITLE
Google Cloud Monitoring plugin cannot parse labels

### ISSUE THREAD

**Issue by mstefa27-ford** [grafana/grafana#44796]
**What happened**:
Grafana only returns default "metadata" labels when attempting to retrieve label values for a Google Cloud Monitoring metric. When querying Google Cloud Monitoring through the Grafana UI, the labels appear to be returned, but not used.

**What you expected to happen**:
The Google Cloud Monitoring metric labels to be returned AND have them available in the UI.

**How to reproduce it (as minimally and precisely as possible)**:
Setup a Google Cloud Monitoring plugin, then try to setup a variable to pull label values from any metric in Google Cloud Monitoring.

**Anything else we need to know?**:
Although my example uses Apigee, this issue appears to occur on all metrics in Google Cloud Monitoring.

**Environment**:
- Grafana version: v8.3.4 (a551d74b11)
- Data source type & version: Google Cloud Monitoring (bundled ver)
- OS Grafana is installed on: 8.3.4-ubuntu, directly from DockerHub
- User OS & Browser: Windows 10, Firefox
- Grafana plugins: Only other data sources

Only metadata labels are available when creating variables:
![OnlyMetadata](https://user-images.githubusercontent.com/32850843/152216762-22d21140-bf1b-4727-ab89-bdf91d355f83.jpg)

Here's what's returned on the call to obtain label values from the variable UI:
![WhenObtainingLabelValues](https://user-images.githubusercontent.com/32850843/152216906-d0da831d-d27b-4289-91a5-72c392534b84.JPG)

When I create a query to Google Cloud Monitoring - notice how label values are not applied to the time series by default:
![When querying](https://user-images.githubusercontent.com/32850843/152216955-18cd0ef8-a180-4de7-8a37-232fff586f78.jpg)

Label values are present in the response from the Grafana server, but not available in the UI:
![When querying network tab](https://user-images.githubusercontent.com/32850843/152217036-584db5f9-3012-4e75-b7ff-6dd24b8eeb89.png)

**Comment by mstefa27-ford** [comment]
Hmm, maybe it's a problem specific to how Apigee metrics are returned? I got a crazy workaround right now where I use another custom variable hardcoded as "resource.label.proxy_name" which is the label key name. This does actually return what I expect, a list of label values. It's too bad it doesn't show up in the drop down though...

![image](https://user-images.githubusercontent.com/32850843/153500581-2a8ceea5-e947-43e2-995f-f3e0a161ad90.png)

**Comment by mstefa27-ford** [comment]
I went to grab a screenshot of the drop down and now I get values to populate? We didn't even upgrade Grafana, so perhaps this was something on Google's end for the past week?

Most interesting of all, looking at my previous screenshots, we were using some data source called "gdev-cloud-monitoring" which is not a data source we have anywhere in our Grafana. Very strange... probably not worth looking into at the moment though.

Thanks for taking a look! Guess I'll just walk away scratching my head as to what was up for the past week

**Comment by yaelleC** [comment]
> gdev-cloud-monitoring

FYI, the "gdev-cloud-monitoring" is the datasource in my screenshot, not yours 😉 !
Thanks for closing, my guess would be something with Google API too 🤞
