### ISSUE TITLE
[Feature Request] Annotation Checkmark same color as Annotation Line Color

### ISSUE THREAD

**Issue by EdClune** [grafana/grafana#4480]
Hi,
Love working with Grafana.  I find the Annotations especially useful.  I recently discovered that you can change the color of the annotation line for a particular annotation and used this to differentiate three different annotation types on my dashboard.  Someone made a suggestion that the text or the checkmark for the annotation (at the top of the dashboard) should have the same color as the annotation line (right now the text is white and the checkmark is light blue).  My preference would be to change the checkmark color, but you get the idea.  This would be helpful if there are multiple types of annotations to be able to visually tell which line colors denote which event type.  Currently, if I've forgotten I need to roll-over an annotation or click a checkbox on and off to see which lines disappear.  The visual cue would be better.
Tnx

**Comment by torkelo** [comment]
In Grafana 3.0 (master/upcoming release), there is only one color option, that controls both the line and the mark icon
