### ISSUE TITLE
[Question] Cannot run Grafana service in Debian 8

### ISSUE THREAD

**Issue by l0oky** [grafana/grafana#4481]
I am using Grafana 2.6.0 I got from this APT repository 
`deb https://packagecloud.io/grafana/stable/debian/ wheezy main`
 
It installed great I configured it. As I tried to follow [this step](http://docs.grafana.org/installation/debian/#start-the-server-initd-service) 
I got this error:

`bash: /usr/sbin/grafana-server: cannot execute binary file: Exec format error`

I tried `chmod +x /usr/sbin` and other directories Grafana may use, to no avail. 

What should I do? I even tried reinstalling the package.
Thank you.

**Comment by torkelo** [comment]
Not sure, did you try to start it with systemd? A lot are running it on debian 8 (official docker images as are using it)

Please use the mailing list for questions

**Comment by l0oky** [comment]
Sorry, did you mean mailing list as in email? If so, on what email should I ask questions?

**Comment by l0oky** [comment]
Ok, for everyone else who is wondering what mailing list is here's the [link](https://groups.io/g/grafana).

**Comment by l0oky** [comment]
I think this is related to this issue https://github.com/grafana/grafana/issues/1968

**Comment by dahamtouch** [comment]
+1
