### ISSUE TITLE
[Feature Request] kdb support

### ISSUE THREAD

**Issue by joelandman** [grafana/grafana#4482]
Hi folks:

   We are working with users of kdb+ from Kx.  I'd like to see if we can hook Grafana to kdb+, if work has not already commenced.

  This would be 2.6.0 and later of Grafana.  If there hasn't been work done on this, I am happy to work on this (I just need a pointer to what elements need to be in place on the Grafana side of the code base to talk to the kdb+ servers).  If there has been work, please let me know what state it might be in, and I am happy to help out.

  Thanks!

**Comment by nopzor1200** [comment]
Hi Joe,

We'd love to have support for kdb+. There hasn't been any work started on it, but we're certainly aware of kdb and would love to see support for it in Grafana.

Grafana 3.0 (beta1 going to be released in a matter of days) has a fully pluggable system for Data Sources. Plus, we're launching a central repository to help people discover and share Data Sources (and Panels, and even complete Applications) to install into Grafana. Overall, the timing of this is great.

This documentation may be useful to help get you started:
https://github.com/grafana/grafana/blob/master/docs/sources/plugins/datasources.md

Feel free to reach out if you have any questions.

**Comment by timgriffiths** [comment]
+1 I would be very keen for kdb plugin

**Comment by torkelo** [comment]
we are not going to

**Comment by torkelo** [comment]
http://docs.grafana.org/plugins/development/
http://grafana.net

**Comment by PDCLeska** [comment]
Hi,
Grafana is really great and looks like KDB+ is our choice for DB.
Would like to test Grafana with KDB. is there a version supporting KDB already?

**Comment by nathansmithz23** [comment]
Also interested if anyone has successfully visualized KDB data in Grafana. Happy to test or even help develop.

**Comment by PDCLeska** [comment]
Hi,
We've just finished a basic connectivity testing successfully. Looks like we will move on to full implementation soon.

**Comment by timgriffiths** [comment]
How are you going with this @PDCLeska do you have anything to share yet?

**Comment by PDCLeska** [comment]
Hey,
This task is part of a corporate project we run. Still deciding if to code in house or out source to Grafana labs...

Will update soon.

**Comment by jeromegit** [comment]
+1 on this
PDCLeska, any luck?

**Comment by PDCLeska** [comment]
Yes! Will ask our developer to upload whatever we have done so far this week.

**Comment by jeromegit** [comment]
That's great!
Thanks PDCLeska

Jérôme  / Blog <http://provensal.com/lbb/> / FB
<https://www.facebook.com/jerome.provensal> / LinkedIn
<http://www.linkedin.com/in/jeromeprovensal> / IG
<http://instagram.com/jeromeig> / Tumblr <http://creativejp.tumblr.com/> /
INTP <http://www.mypersonality.info/personality-types/intp/>

**Comment by mattttt** [comment]
HI @PDCLeska! Thanks for taking this and pushing it along. Just spoke with a Grafana user very excited about this. Did you ever get approval to upload the KDB data source?

**Comment by digash** [comment]
Hi @PDCLeska, any update on this, I would love to test it out. We have to copy data into influx from kdb+ and would love to use it directly from Grafana.

**Comment by ad05bzag** [comment]
hi @PDCLeska just piggybacking on @digash's question. Would love to test the kdb+ with grafana!

**Comment by nrupaldesai** [comment]
Hi @PDCLeska , any update on this ? really looking forward to test with kdb+.

**Comment by zak-b2c2** [comment]
Any updates please?
