### ISSUE TITLE
Alerting: support "start of n until end of n" time ranges

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#44823]
**What happened**:

This is a follow-up to https://github.com/grafana/grafana/issues/36154. 

We currently do not support these types of time ranges since the ruler API expects a fixed time offset in seconds.

There are various use-cases for why you would want to use an expression such as `now-1d/d` or `now-1m/m` but this does require a change in the ruler API and will have to be assessed how viable supporting these expressions would be.

- [ ] Ruler API support
- [ ] Front-end support
- [ ] Documentation updated

**What you expected to happen**:

Expressions such as `now-1d/d` would be supported for alerting rules.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new alert
2. Specify the following timerange
<img width="255" alt="image" src="https://user-images.githubusercontent.com/868844/152326261-c06a4b9c-e15d-48b7-b29a-d14a01e88695.png">

**Anything else we need to know?**:

**Comment by gillesdemey** [comment]
Those are what we call "[semi-relative](https://grafana.com/blog/2022/02/03/pro-tip-how-to-use-semi-relative-time-ranges-in-grafana/)" time ranges. We don't support those either since AlertManager (and by extension, alerting) only works with a fixed time window. 

Using semi-relative time ranges produces variable window sizes (they grow larger as the day goes by). 

In other words 

`from: now-24h to: now` works fine since the time window is always exactly 24 hours wide.
`from: now/d to: now` doesn't work because the window size depends on how far the current day has progressed.

**Comment by slhck** [comment]
Thanks for the explanation. Do you think the documentation could be updated to better reflect that?

**Comment by gillesdemey** [comment]
Yea if the docs are not sufficiently clear on this we should add it – I can work with @brendamuir to document the caveats around semi-relative time ranges 👍

**Comment by brendamuir** [comment]
PR to update the docs here: https://github.com/grafana/grafana/pull/66760/files.
