### ISSUE TITLE
Question: How can I zoom out the graph made available in-line?

### ISSUE THREAD

**Issue by seesiva** [grafana/grafana#4485]
I'm  using Grafana 2.6.0 with KairosDB. I would like to know the following:
a. How can I zoom out the inline graph?
b. How can I make the relative graph change when I have made multiple graphs in-line like we do in the grafana dashboards?

**Comment by torkelo** [comment]
a) not sure what you mean "inline graph", use the mouse and drag click region to zoom in?

b) ?

**Comment by seesiva** [comment]
In-line graph is something where I have used the IFrame.

**Comment by torkelo** [comment]
Ok, you cant zoom out currently on iframed graphs. 

If you have mulitple iframed graphs they are independent, zoom in on one will not affect the other

**Comment by seesiva** [comment]
Is there an alternative strategy  or suggestion?
