### ISSUE TITLE
[Bug] npm install 

### ISSUE THREAD

**Issue by antjori** [grafana/grafana#4487]
While executing `npm install`, on Grafana 3.0.0-pre1 with Linux RHEL6.4 x86_64 and NPM 3.3.12, the following error occurred:

    ├── UNMET PEER DEPENDENCY es6-shim@0.35.0
    └── UNMET PEER DEPENDENCY rxjs@5.0.0-beta.2

    npm WARN EPEERINVALID angular2@2.0.0-beta.0 requires a peer of es6-shim@^0.33.3 but none was installed.
    npm WARN EPEERINVALID angular2@2.0.0-beta.0 requires a peer of rxjs@5.0.0-beta.0 but none was installed.
    npm ERR! code 1

The only way I manage to overcome the error was editing the *package.json* file and modifying the versions of each dependency.

**Comment by torkelo** [comment]
thanks for reporting this, fixed!

**Comment by antjori** [comment]
Thanks @torkelo for fixing it!

Unfortunately, after I updated and rebuilt the front-end, a similar dependency problem arose:

    └── UNMET PEER DEPENDENCY zone.js@^0.6.6

    npm WARN EPEERINVALID angular2@2.0.0-beta.12 requires a peer of zone.js@^0.6.6 but none was installed.

**Comment by torkelo** [comment]
Try removing  node modules directory and run npm install again, that solved it for me

**Comment by antjori** [comment]
I followed your suggestion, removed the *node_modules* directory, but I still got the same error. :disappointed:

The only way I managed to solve it was by manually install it: `npm install zone.js@^0.6.6`.

**Comment by torkelo** [comment]
strange, build server (who does clean install) is not getting it, and I am not getting it either on mac & ubuntu

**Comment by torkelo** [comment]
what version of npm do you have?

**Comment by antjori** [comment]
I'm using npm 3.3.12.

**Comment by torkelo** [comment]
@antjori I did some package.json updates (added zone.js) hope it works for you now

**Comment by antjori** [comment]
I'll fetch the new changes and rebuild the front-end. Thank you so much for all your help @torkelo.
