### ISSUE TITLE
Alert tab missing post upgrade from 7.5.7 to 8.2.3

### ISSUE THREAD

**Issue by iamyogeshg** [grafana/grafana#44878]
**What happened**: After upgrading Grafana from 7.5.7 to 8.2.3, we noticed that graph type is set to "Graph(old)" and the alerting tab is missing. Its only when we manually change type to "Time series", alert tab comes up. 

**What you expected to happen**: Alert tab should show up as it was and perhaps default type should be changed to TimeSeries. https://grafana.com/docs/grafana/latest/visualizations/time-series/

![image](https://user-images.githubusercontent.com/25523197/152441526-9d31d2b4-6799-4bfa-aa82-0572c5aa4010.png)

**Anything else we need to know?**: We have 100s of dashboards and we would like to change all of them. 

**Environment**:
- Grafana version: 8.2.3
- Data source type & version: Prometheus
- OS Grafana is installed on: Amazon Linux 2
- User OS & Browser: MacOs/Brave
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
Can you please help us figure out what went wrong by providing a dashboard json you can share with us before you migrated to 8.2?

**Comment by zoltanbedi** [comment]
Happy to hear that. I'm going to close this issue then.
