### ISSUE TITLE
Grafana Documentation HTTP User API - Broken Link

### ISSUE THREAD

**Issue by jfagoagas** [grafana/grafana#44886]
**What happened**:
At https://grafana.com/docs/grafana/latest/http_api/ `User API` link is not rendered.

<img width="536" alt="Screenshot 2022-02-04 at 08 26 30" src="https://user-images.githubusercontent.com/16007882/152488928-57549d1c-cab9-40b7-ad50-c5f993be7d1c.png">

**What you expected to happen**:
`User API` link is not render without problem.

**How to reproduce it (as minimally and precisely as possible)**:
Just navigate to https://grafana.com/docs/grafana/latest/http_api/ 

**Anything else we need to know?**:
Nothing relevant.

**Environment**:
- Grafana version:  N/A
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: Every Browser and OS
- Grafana plugins: N/A
- Others: N/A

**Comment by jfagoagas** [comment]
Maybe it's related with https://github.com/grafana/grafana/pull/44342

**Comment by zuchka** [comment]
@achatterjee-grafana is the linked PR was not back-ported. Should this have been fixed by now? thx!

**Comment by achatterjee-grafana** [comment]
> @achatterjee-grafana is the linked PR was not back-ported. Should this have been fixed by now? thx!

Yes, I will fix it for 8.4.x branch, which is the `latest` branch.
