### ISSUE TITLE
Zoom out on embed panel issue

### ISSUE THREAD

**Issue by W4lken** [grafana/grafana#4489]
Hello everyone,

I'm unable to zoom out on an embed panel. I saw that this problem was solved with #3581 but it doesn't work for me. Any suggestions ? (i tested with chrome and safari)

* What grafana version are you using?
2.6.0
* What datasource are you using?
Any
* What OS are you running grafana on?
Grafana docker official container

Thank you for your amazing job, grafana is really an incredible tool.

Best regards,
Alexis

**Comment by torkelo** [comment]
in Grafana 3.0 you can zoom out by double clicking on the graph.

**Comment by xf-** [comment]
@torkelo please reopen. won't work in embed and no way to zoom out
Example in your demo http://play.grafana.org/dashboard-solo/db/graphite-carbon-metrics?panelId=1

**Comment by dominicnicholas** [comment]
Yes, having same issue with beta7.
