### ISSUE TITLE
[Question][Bug] Grafana Datasource Proxy HTTP API not working

### ISSUE THREAD

**Issue by thanyawzinmin** [grafana/grafana#4492]
I have this Grafana Instance running at :3000 and I tried to access the datasource through proxy which I configured correctly as below.

<img width="742" alt="screen shot 2016-03-29 at 9 08 57 am" src="https://cloud.githubusercontent.com/assets/434180/14096354/ee655708-f58d-11e5-87a6-286bb75e4324.png">

The following is how I tried to access it and how it failed. The log from /var/log/grafana/ doesn't give me much except it is failing in dataproxy.go. So I decided to come and here and shot a question.

<img width="1440" alt="screen shot 2016-03-29 at 9 10 17 am" src="https://cloud.githubusercontent.com/assets/434180/14096368/304c05e0-f58e-11e5-8867-71d9c4780cdb.png">

Ex
* Grafana 2.6.0 (commit: v2.6.0)
* InfluxDB 0.9
* Ubuntu 12.05 LTS

Thanks

**Comment by thanyawzinmin** [comment]
Tried to get a list of datasource by following command.

```
$ curl admin:admin@localhost:3000/api/datasources
```
And tried these two but former is 404 page not found and later is "message":"Unable to load datasource meta data" !
```
$ curl admin:admin@localhost:3000/api/datasources/proxy/1
$ curl admin:admin@localhost:3000/api/datasources/proxy/collectd
```

**Comment by torkelo** [comment]
curl admin:admin@localhost:3000/api/datasources  works here,

**Comment by thanyawzinmin** [comment]
Yes that worked but what about /proxy/datasourceid ?
