### ISSUE TITLE
Inconsistent error returned when getting vs updating a nonexistent alert notification

### ISSUE THREAD

**Issue by pianohacker** [grafana/grafana#44931]
**What happened**:

When getting a nonexistent alert notification by ID or UID, a slightly different error is returned than when a nonexistent alert notification is deleted or updated.

**What you expected to happen**:

Getting a nonexistent alert should return `models.ErrAlertNotificationNotFound` from `pkg/models/alert_notifications.go`.

**Comment by tharun208** [comment]
@pianohacker i like to work on this issue
