### ISSUE TITLE
[Feature Request] version field for dashboards in REST API search response

### ISSUE THREAD

**Issue by alchuk** [grafana/grafana#4495]
When searching for dashboards it would be convenient and much faster to have dashboard version returned in search query response rather than having to make tons of http requests for each and every single dashboard

**Comment by torkelo** [comment]
why do you need version in search result?

**Comment by alchuk** [comment]
When preparing for mass update via REST I need to know the current version of each dashboard. So the number of http requests for DB version directly connected to the number of dashboards. If the version property of each dashboard is returned in search response it would eliminate the need for hundreds/thousands of independent http requests

**Comment by torkelo** [comment]
No you don't, if you set overwrite true in the save dashboard api call you can overwrite any dashboard no matter if versions don't match
