### ISSUE TITLE
[Feature Request] make thresholds variable

### ISSUE THREAD

**Issue by alchuk** [grafana/grafana#4497]
Thresholds are initially meant to replace rrdtool's HRULE feature. For now there's no way to automatically set thresholds for graphs except generating the whole dashboard via REST or using scripted dashboards. Is it possible to implement filling this field with some query result?

**Comment by torkelo** [comment]
there is already an issue for this

**Comment by simPod** [comment]
Here https://github.com/grafana/grafana/issues/922
