### ISSUE TITLE
Docs feedback: /visualizations/geomap.md

### ISSUE THREAD

**Issue by simonc6372** [grafana/grafana#44977]
Seems to be something missing here. 
![image](https://user-images.githubusercontent.com/8004654/152777759-28b6d05a-6f1c-4ec7-829a-c495b1a6673d.png)

**Comment by nmarrs** [comment]
It seems that missing type is
![Screen Shot 2022-02-11 at 3 29 38 PM](https://user-images.githubusercontent.com/22381771/153684358-fb30cd1c-7723-4b55-9ded-e93388f0d4d4.png)

Not sure though if this option shows up for all users or not. If it doesn't show up then we can just update documentation to say three layers, else add the alpha icon at last point layer in docs.

Thoughts @ryantxu?

**Comment by iAziz786** [comment]
Waiting for the confirmation from @ryantxu.

**Comment by ryantxu** [comment]
@iAziz786 sounds great -- always feel free to start any docs issues :)

**Comment by iAziz786** [comment]
@ryantxu Does this content looks right?

* **Icon at last point (alpha)** visualizes an icon at the last point (currently in alpha stage)
