### ISSUE TITLE
Add event tracking to navigation (Rudderstack)

### ISSUE THREAD

**Issue by zsofiakomaromigrafana** [grafana/grafana#44976]
_Edited based on new navigation approach_

We would like to understand which navigation items are most frequently used (similar to a heatmap), as well as understand the usage of the expand/collapse feature.

**Navigation item clicked**
**Given** Grafana navigation bar
**When** A user clicks a nav item in the navigation bar. The nav bar can be collapsed or expanded but this event is only logged when the menu item opens a page or a modal, not if a top level menu item is clicked to expand its contents (in the expanded state).
**Then** A tracking event to RudderStack is emitted with the following attributes:

Proposed event name: **grafana_navigation_item_clicked**

Event properties: 

- **path**: relative path of the page opened (e.g. /library-panels). In case of external page (Help/Support), full URL. For modals (Keyboard shortcuts): ?
- **state**: collapsed/expanded. On small screens, when using the hamburger menu, it will be expanded. Using 'state' instead of 'isExpanded' in case a new state (pinned) is introduced later.
____________________________________________________________________
**Navigation expanded/collapsed**
**Given** Grafana navigation bar
**When** A user expands or collapses the navigation bar by clicking the chevron.
**Then** A tracking event to RudderStack is emitted with the following attributes:

Proposed event names: 
**grafana_navigation_expanded**
**grafana_navigation_collapsed**

Event properties: none

**Comment by zsofiakomaromigrafana** [comment]
@jmarbach As User Essentials is just getting started with RudderStack, I wanted to check with you: does the above event name and properties seem right?

I added config_level as an event property to define on what level the configuration happens: it's for an individual user, a team or an org.

**Comment by jmarbach** [comment]
@zsofiakomaromigrafana Nice work!

A few suggestions:

1. We can remove `visit_id` -- I assume you saw this in one of my older examples? It's not needed as we can join all visits from a user automatically.
2. We can remove `user_id` -- this will be tracked automatically in Hosted Grafana to the user's email address
3. `org_id` is not available to us in Hosted Grafana. We should change this to `org_slug`.
4. `config_level` sounds good!
