### ISSUE TITLE
[Bug] Failure to reconnect to LDAP after connection disruption

### ISSUE THREAD

**Issue by bhinkle-work** [grafana/grafana#4500]
We use Grafana hosted in AWS and configured with LDAP for authentication, but our Active Directory LDAP infrastructure is on-prem accessed over a VPN. We have noticed twice that if the VPN is disrupted even momentarily, the Grafana container becomes unresponsive and continuously logs "Failed to start session" messages until it is restarted.

* Grafana 2.6 - official Docker container
* Docker 1.10.3, Ubuntu 14.04.4 LTS

Example logs:

3/29/2016 8:47:07 AM2016/03/29 13:47:07 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=mkdir /var/lib/grafana: file exists)
3/29/2016 8:47:07 AM2016/03/29 13:47:07 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'REDACTED': Organization not found
3/29/2016 8:47:07 AM2016/03/29 13:47:07 [I] Completed 10.164.48.217 - "GET / HTTP/1.1" 302 Found 29 bytes in 354us
3/29/2016 8:47:37 AM2016/03/29 13:47:37 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=mkdir /var/lib/grafana: file exists)
3/29/2016 8:47:37 AM2016/03/29 13:47:37 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'REDACTED': Organization not found
3/29/2016 8:47:37 AM2016/03/29 13:47:37 [I] Completed 10.164.48.217 - "GET / HTTP/1.1" 302 Found 29 bytes in 490us
3/29/2016 8:48:07 AM2016/03/29 13:48:07 [middleware.go:78 initContextWithUserSessionCookie()] [E] Failed to start session%!(EXTRA *os.PathError=mkdir /var/lib/grafana: file exists)
3/29/2016 8:48:07 AM2016/03/29 13:48:07 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'REDACTED': Organization not found
3/29/2016 8:48:07 AM2016/03/29 13:48:07 [I] Completed 10.164.48.217 - "GET / HTTP/1.1" 302 Found 29 bytes in 461us

**Comment by torkelo** [comment]
This does not look to be related to LDAP but some failure to write to session directory.

Maybe an issue with the docker volume disc?
