### ISSUE TITLE
Deleting Invalid Notifier from Pop-up Window Also Deletes Valid Notifiers

### ISSUE THREAD

**Issue by FanAndRan** [grafana/grafana#45021]
**What happened**:
Deleting an invalid notifier from the pop-up window could also get valid notifiers deleted.

**What you expected to happen**:
Only the invalid notifier is removed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Remove a notifier (alert notification)
2. Visit an alert that uses it as one of the notifiers
3. A pop-up window appears
4. Type "Delete" to delete the invalid notifier
5. Save the dashboard and refresh
6. Not only the invalid notifiers is gone but also the valid ones (from UI & json)

![grafana_notifiers_wiped](https://user-images.githubusercontent.com/11284159/152893081-83f3f30f-4817-4039-8def-804842b5921c.gif)

**Anything else we need to know?**:
https://github.com/grafana/grafana/blob/main/public/app/features/alerting/AlertTabCtrl.ts#L168
An `undefined === undefined` case could happen here and get all notifiers selected.
Eg: 
![image](https://user-images.githubusercontent.com/11284159/152895449-11907148-efb8-4c27-8e77-71623411eb65.png)

**Environment**:
- Grafana version: 7.5.12
- Data source type & version: TestData DB
- OS Grafana is installed on: MacOS
- User OS & Browser: MacOS & Chrome
- Grafana plugins: None
- Others: None

@mtomwing

**Comment by zoltanbedi** [comment]
@FanAndRan thanks for the detailed error report. You should try out our new alerting system https://grafana.com/docs/grafana/latest/alerting/
