### ISSUE TITLE
Chore: Clean up logs and warnings from BI unit tests

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#45025]
The following tests are outputting errant logs and warnings to the console during unit tests. Some of these are pointing out genuine errors and things that should be looked at, while others might be a bit more benign but should be cleaned up to make testing more pleasant.

In the future we may consider making console logs to be a failure condition in tests, so it would be good to sort these out sooner 😇

 - [ ] 1 log  from `packages/grafana-ui/src/components/GraphNG/nullInsertThreshold.test.ts`

See [this comment](https://github.com/grafana/grafana/issues/42359#issuecomment-1032179575) for common warnings and how to fix them.

If you have any questions be sure to reach out to the User Essentials team ✌🏻 

Part of https://github.com/grafana/grafana/issues/42359

**Comment by leeoniya** [comment]
this is a non-deterministic perf test.

if i'm interested in running such tests periodically with visible console output so i can manually assert whether regressions or improvements are significant (without hard-coding any specific numbers into the assertions), what's the recommended way to do it besides having uncommited test code sitting on my computer.

i'm fine with with switching this one to `test.skip()` for the time being, but there will be many more of these things in the future and should figure out how to keep them commited and/or deterministic, and proactively tracked in CI.

**Comment by joshhunt** [comment]
We've been talking about/investigating using [Betterer](https://github.com/phenomnomnominal/betterer) to make tracking (and preventing) regressions easier. @ashharrison90 has a stab here at "trying to make number go down". Next step after betterer is to send these to [our Grafana](https://play.grafana.org/d/VEy5UXjmk/grafana-ci-code-stats?orgId=1) to track (and alert!!) them over time

**Comment by joshhunt** [comment]
oops, forgot link https://github.com/grafana/grafana/pull/44830

**Comment by ashharrison90** [comment]
@leeoniya you must have a mental threshold in your head for what's considered significant (the test description states <10ms), so what's stopping just rewriting the test to have `expect(timeTaken).toBeLessThan(10)` or something similar? 🤔

**Comment by ashharrison90** [comment]
@leeoniya ah gotcha 👍  in that case probably skipping is the best way forward, maybe with a comment so that someone doesn't accidentally delete it 😅
