### ISSUE TITLE
Notification Channel configuration is not properly saved (version: 8.3.3 30bb7a93ca)

### ISSUE THREAD

**Issue by pschwippert** [grafana/grafana#45048]
**What happened**:

Good afternoon,

We are running the grafana helm chart in a kubernetes cluster and using a Postgres DB to store grafana's configuration data. We use Legacy Alerting here. I have run into an issue where the webhook url of a notification channel is not saved properly.

**What you expected to happen**:
I expect that the webhook for Slack and bot token for Telegram are saved properly.

**How to reproduce it (as minimally and precisely as possible)**:
1. Add a Slack notification channel for the first time
2. Enter the webhook url in the field
3. Test the notification channel -> this returns OK and message is visible in slack
4. Press save
5. After the redirect open the notification channel configuration again
6. Click Test again, it shows an error
7. Observe that the webhook field is empty.

I have looked in the postgres pod, and the `secure_settings` row is the `alert_notification` is filled, but am unable to verify if the data is correct as it's hashed.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: **8.3.3**
- Component: **Legacy Alerting**
- OS Grafana is installed on: **Kubernetes using helm chart**
- User OS & Browser: **Ubuntu, Firefox**

Additional info:
- There are no logs present in the grafana pod, apart from the error when testing the second time. 
- The network tab in my browser doesn't give me any information as to what might have gone wrong either
- This also happens with mattermost webhooks (which use the slack format) or telegram bot tokens.

**Detailed explanation with images:**

When adding a Slack notification channel for the first time I enter the webhook here:
![image](https://user-images.githubusercontent.com/1703558/152798607-d2008535-774e-4aac-83a1-655d14eb8939.png)

![image](https://user-images.githubusercontent.com/1703558/152798952-2367654c-78e6-47ad-8135-a7304abd7190.png)

In slack I correctly see the test message meaning the webhook works:
![image](https://user-images.githubusercontent.com/1703558/152799026-4578df00-807f-4758-9e3f-650ba6b456fb.png)

I then press save and get redirected to the notification channel page:
![image](https://user-images.githubusercontent.com/1703558/152799239-1ee9e240-9859-454c-82a2-92e13508d3ef.png)

If I click on the added channel and click test again, it gives me an error:
![image](https://user-images.githubusercontent.com/1703558/152799316-d4900950-0de9-410e-8f3e-731848dda6a6.png)

When I open the settings it seems that the Token field is now also configured which is odd:
![image](https://user-images.githubusercontent.com/1703558/152799425-50ae7309-f41c-4292-9f5d-8daf1fc1674d.png)

If I click on "clear" the field is empty, and so is the Token.
![image](https://user-images.githubusercontent.com/1703558/152799523-fb09af09-f3e4-4b24-b9c1-430f019e8c98.png)

I hope someone is able to help identify if this is an issue with the postgres database, our grafana installation or whether or not this is a bug in grafana itself.

**Comment by zuchka** [comment]
possibly related: https://github.com/grafana/grafana/issues/43591#issuecomment-1032363412

**Comment by ParanormalBrothers** [comment]
Same problem. Tg alerting.
![Clip2net_220211151159](https://user-images.githubusercontent.com/93286644/153589546-1bd4c46b-138e-413f-811d-059dfdefec86.png)

**Comment by JacobsonMT** [comment]
Seems likely related to https://github.com/grafana/grafana/issues/47404 which has an open [PR](https://github.com/grafana/grafana/pull/47559) to fix it.

**Comment by grobinson-grafana** [comment]
The fix for this issue should be in Grafana 8.5. Would it be possible to upgrade Grafana to 8.5 and confirm if the issue still persists?

**Comment by tommiz1989** [comment]
From the release noted of 8.5.0 it doesn't seem the code in the PR mentioned has been added to that release.
Can you please share if in the next release the fix will be present? And if so, when will it be?

> Seems likely related to #47404 which has an open [PR](https://github.com/grafana/grafana/pull/47559) to fix it.

**Comment by JacobsonMT** [comment]
> Can you please share if in the next release the fix will be present? And if so, when will it be?

The [PR](https://github.com/grafana/grafana/pull/47559) didn't end up making it into Grafana 8.5.0 but it is now merged and will be available in 8.5.1 which should release this Thursday as far as I know.

**Comment by JacobsonMT** [comment]
> From the release noted of 8.5.0 it doesn't seem the code in the PR mentioned has been added to that release. Can you please share if in the next release the fix will be present? And if so, when will it be?

You're right that it doesn't show up in the release notes, it was likely just an oversight. After a quick test on my end though, I can say that it did indeed make it into Grafana 8.5.0.
