### ISSUE TITLE
Grafana queries cause InfluxDB to spike in CPU and end the influx process

### ISSUE THREAD

**Issue by finneysm7** [grafana/grafana#4505]
I am having issues with grafana queries taking out my influxdb database by ramping up the CPU and killing the docker container that is running influxdb. My grafana queries are of the following format:

select * from "/^service\.environment\.cluster\..*measurement\.sub-type$/"

These queries can get data from up to 100 servers at once for the clusters that I am monitoring. I want this because I want to display data for an entire cluster over the course of a week to a month. I feel like there are ways to make the queries more efficient, but I am not sure how to make this work with the clunky interface that Grafana presents. Is there anyway of telling what Grafana is sending to InfluxDB?

Here is a screenshot of what my query field typically looks like:
![screen shot 2016-03-28 at 2 51 59 pm](https://cloud.githubusercontent.com/assets/8519852/14117993/34c1b88c-f59c-11e5-9503-e4b6ce0fd473.png)

Any help on this would be very much appreciated as my InfluxDB + Grafana setup is currently unusable due to the CPU spikes that any user can trigger from just looking at a graph in Grafana.

**Comment by torkelo** [comment]
If want to look at long time ranges influxdb is not very good, you need to create CQ in influxdb to work around slow queries (and roll up data), I suggest you use Graphite instead if you want to a TSDB with good integrated roll ups and fast queries for long time ranges
