### ISSUE TITLE
[Bug] Server Side Rendering Auth Screen instead of graph

### ISSUE THREAD

**Issue by kevin1024** [grafana/grafana#4506]
Hello!  I'm having an issue with the server side rendering.  I'm using the "Direct link rendered image" feature, but it's rendering a nice png screenshot of the grafana login screen.  I'm using Google oauth for authentication.

* Version 2.6.0 
* CloudWatch data source
* Running official docker image
* Using Google Oauth

![screenshot](https://cloud.githubusercontent.com/assets/21099/14122464/ad46f5e2-f597-11e5-853b-21a54e876fe1.png)

**Comment by balrogthane** [comment]
I'm experiencing the same problem, but using proxy auth. Very strangely, it's behaving like the proxy auth is supposed to and creating the user as per the X-WEBAUTH-USER header, but then it gives me the login screen like @kevin1024.

![render](https://cloud.githubusercontent.com/assets/12754560/14758372/605a89a4-08bd-11e6-9be7-b280607c2419.png)

**Comment by kartoffelheinz** [comment]
I have the same issue using grafana 3.0.4 from grafanas repositories. Any idea how I can debug this myself? Setting loglevel to Debug does not change anything, unfortunately :(

**Comment by ericescalante** [comment]
Hi, any suggestions on this case? Happens to me as well using v3.1 on docker (not just with hubot but even when sharing a panel manually).

**Comment by ericescalante** [comment]
Fixed! the solution was:
`GF_SERVER_ROOT_URL="http://localhost:3000"` 
instead of 
`GF_SERVER_ROOT_URL="http://xxxxx.com"`

**Comment by torkelo** [comment]
fixed in 175c651 !
