### ISSUE TITLE
[Question] Disable routes / allow view only snapshots

### ISSUE THREAD

**Issue by elinkev** [grafana/grafana#4510]
I want to only display snapshot routes to users - example.com/dashboard/snapshot/some_hash. Other routes would be inaccessible to everyone else. I dont want them to be able to access dashboards or login pages or anything like that, only snapshots.

I would know how to do this with .htaccess but from what i understand this wont work with grafana. 
Is there a 'routes' config file that i can edit for my server? Reading the minified code in a language that is new to me gave no results..Everything i google pretty much always redirects me to the docs page and i cant find any useful info there..

**Comment by torkelo** [comment]
snapshots are by default viewable by anyone (you do not have to be logged in to view them)
