### ISSUE TITLE
Unable to Create/Save Dashboard after v8.3.5 Update

### ISSUE THREAD

**Issue by jdmaloney** [grafana/grafana#45117]
**What happened**:
Unable to create a new dashboard or save changes to existing dashboards following update to Grafana v8.3.5 

**What you expected to happen**:
Ability to create/modify dashboards in Grafana

**How to reproduce it (as minimally and precisely as possible)**:
- Log into Grafana instance and click on "+" button and create new dashboard
- Go to save the dashboard into a folder
- Attempt to save fails, "Origin Not Allowed" error shows up in upper right corner

**Anything else we need to know?**:
Attached is what I'm seeing in the console upon trying to save; looks like it is getting a 403 Forbidden for FQDN/api/dashboards/db and this is preventing dashboard from saving.  Clicking the "Save" button prompts one of these errors in the console.  I'm also seeing a 403 Forbidden on FQDN/api/frontend-metrics and a screenshot for that is attached too.  I'm not seeing anything of particular use in the /var/log/grafana/grafana.log at INFO level, let me know if I should try debug level.  
<img width="1676" alt="Screen Shot 2022-02-08 at 10 26 05 PM" src="https://user-images.githubusercontent.com/16138910/153122711-779a4b11-48f3-4071-a5da-b7dd218859de.png">
<img width="1675" alt="Screen Shot 2022-02-08 at 10 31 46 PM" src="https://user-images.githubusercontent.com/16138910/153122716-9a93814d-2712-43ee-83cf-6883646cfb9c.png">

**Environment**:
- Grafana version: 8.3.5
- Data source type & version: InfluxDB
- OS Grafana is installed on: RHEL 8
- User OS & Browser: Safari, Chrome
- Grafana plugins: None
- Others: None

**Comment by remifrazierucsf** [comment]
Same with the 8.3.5 upgrade on RHEL7.x

**Comment by LKaemmerling** [comment]
I can confirm the issue too after updating to 8.3.5, for me it also affects the loading of the template variables so ATM Grafana is not usable

**Comment by rsommer** [comment]
Here, too - **origin not allowed** all over the place, like in #45115 and this one. Rollback to 8.3.4 instantly fixed the problem for now.

**Comment by smowky** [comment]
Can confirm docker image has this problem too, image v8.3.4 works without issue.

**Comment by BlackDex** [comment]
I have the same, but only on a system which uses a sub_path, the other one seems to be working fine.
Both using docker and nginx.

**Comment by DasSkelett** [comment]
In my particulars case the bug was triggered because nginx had a `proxy_pass` directive with an IPv6 address, and adding `proxy_set_header Host $http_host; ` worked around it.  
For those who also use nginx, and proxy_pass to a raw IPv6 address, this would be worth trying out.

**Comment by MichaIng** [comment]
I see "403 origin not allowed" on any attempt to connect to an InfluxDB data source, since upgrading to v8.3.5. This makes Grafana of course unusable. Downgrading back to v8.3.4 solves it as well here.

**Comment by jdmaloney** [comment]
@dominik-bln Looks like they've pulled the release after announcement; it definitely was released on purpose though yesterday.  They even have a blog post out about it because there was a XSS vuln in it. https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/

**Comment by MichaIng** [comment]
This XSS vuln fix may exactly have caused our issues, as it is about the way how Grafana handles data sources. I btw tried to restart InfluxDB and logout/login from Grafana interface. InfluxDB is bound to loopback IP `127.0.0.1` and Grafana is accessing it via this IP, so not sure how I should configure anything more secure or differently in the way intended after the XSS vuln fix.

**Comment by DasSkelett** [comment]
Looking at the new [CSRF check](https://github.com/grafana/grafana/blob/a53fcac7b1b7ebda8c0cb18f7ce92788af92fa32/pkg/middleware/csrf.go#L29-L35) again, this is not only broken for IPv6 addresses but every reverse proxy setup where the rev proxy changes the `Host` header. **Configure your rev proxy to keep the original `Host` header.**

For nginx: `proxy_set_header Host $http_host;`
For Apache2: `ProxyPreserveHost On` (please confirm, don't have an Apache2 running to try out)

**Comment by MichaIng** [comment]
Thanks, I can confirm it works with Apache2, many thanks!

Now it would be interesting to understand the background of why Grafana now wants to know the originating host and how this is connected to the XSS vulnerability. Does it now assure that any answer/information/action, triggered by a request from an origin, can only be retrieved from the same origin, and does not allow the proxy host for validation which is naturally the same for multiple origins?

**Comment by BlackDex** [comment]
Thanks @DasSkelett that seems to work fine for my nginx environment.

**Comment by zoltanbedi** [comment]
I think everyone figured this out after reading the release notes again and there isn't a bug so I'm closing this issue now.

**Comment by BlackDex** [comment]
Might i suggest that someone updates the example here: https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by zoltanbedi** [comment]
Yes, make sense.

**Comment by zuchka** [comment]
tested our nginx config on fresh VMs using the suggested `proxy_set_header Host $http_host;` and it worked, both using the root domain and using a subdomain. 

I've been testing and updating that tutorial so I will add this to the new edits and publish soon

**Comment by zuchka** [comment]
@MichaIng we don't have Apache2 in our reverse proxy tutorial, but if you'd like to add a sample config, that would be very much appreciated!

**Comment by MichaIng** [comment]
Jep, I can do that when I find time. Just found it here: https://github.com/grafana/tutorials/blob/master/content/tutorials/run-grafana-behind-a-proxy.md

**Comment by onlime** [comment]
Thanks @DasSkelett @MichaIng - adding `ProxyPreserveHost On` fixed it and Grafan 8.3.6 now runs fine. The [Grafana 8.3.5 release notes](https://grafana.com/blog/2022/02/08/grafana-7.5.15-and-8.3.5-released-with-moderate-severity-security-fixes/) were a little bit too long, so I didn't read all the way down there. Would have been nice if Grafana could have put this on top as I think a lot of us are running Grafana behind a proxy and if it requires any configuration changes on a minor/security upgrade, I would expect a fat warning on top of the release notes.

But, well, it's solved now. Thanks for your help!

**Comment by MichaIng** [comment]
Agreed, when config changes are required, even in a subset of setups only, it makes sense to list/warn about this near the top. Also, for the future, IMHO such satisfies a minor version increment instead of a patch version increment only. While for such cases there are no strict rules regarding semantic versioning (we have no public API change here), it implied a breaking change for a common setup, and is hence not an update which one can have applied automatically during night, thinking it is definitely non-breaking as its a patch version increment only. While a minor version increment doesn't explicitly imply breaking changes, but new features only, it is at least something where admins have a closer look first, usually not applying such completely unattended.

**Comment by dominik-bln** [comment]
What I'd like to add is, that it was also unexpected for me that the potential breaking change is only mentioned in the blog post. Neither the Github [release page for 8.3.5](https://github.com/grafana/grafana/releases/tag/v8.3.5) nor the [release page on Grafana.com](https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-3-5/) contain this information.

**Comment by MichaIng** [comment]
Though the links to the blog are given 😉. But I agree, it would have been nice for admins to have this information more prominent.

**Comment by Limess** [comment]
Is there a suggestion for serving Grafana behind an ALB + Nginx now? We cannot set the `Host` header for the backend Grafana request to the actual exposed origin, as the ALB only uses `Host` header based routing and cannot mutate it.

We also set `X-Forwarded-Host` but it seems that's not sufficient here.

**Comment by daveymathijssen** [comment]
Does anyone have a solution for this problem when using IIS?

**Comment by alvintownsend** [comment]
For Grafana 8.4.0, @DasSkelett's [solution](https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787) worked flawlessly, in combination with setting these flags for configuring Grafana in Docker, [based off of these instructions](https://grafana.com/tutorials/run-grafana-behind-a-proxy/):

```
GF_SERVER_DOMAIN=grafana.ourdomain.com
GF_SERVER_ROOT_URL=http://grafana.ourdomain.com:80
```

If you're not using Docker, this is what you'd need in the config file:

```
[server]
domain = grafana.ourdomain.com
root_url = http://grafana.ourdomain.com:80
```

(where grafana.ourdomain.com is the domain and the port of 80 is what your reverse proxy is listening to)

**Comment by WGH-** [comment]
And if I don't use a reverse proxy, and connect directly to an IPv6 address?

**Comment by DasSkelett** [comment]
> And if I don't use a reverse proxy, and connect directly to an IPv6 address?

I've opened #45115 for that one

**Comment by sebader** [comment]
> Looking at the new [CSRF check](https://github.com/grafana/grafana/blob/a53fcac7b1b7ebda8c0cb18f7ce92788af92fa32/pkg/middleware/csrf.go#L29-L35) again, this is not only broken for IPv6 addresses but every reverse proxy setup where the rev proxy changes the `Host` header. **Configure your rev proxy to keep the original `Host` header.**
> 
> For nginx: `proxy_set_header Host $http_host;` For Apache2: `ProxyPreserveHost On`

This PR should fix the actual issue without requiring any changes on the proxy https://github.com/grafana/grafana/pull/46418

**Comment by taintedkernel** [comment]
@Limess @dswarbrick I have a related scenario where I run Grafana on k8s w/ingress (via grafana.domain.tld), but sitting in front of that is another nginx instance and serves up an grafana.admin.domain.tld host and provides SSL wildcard cert for the admin subdomain.

In order to get it working, on the admin subdomain nginx I had to add `proxy_set_header Origin "https://grafana.domain.tld"` in addition to my existing `proxy_set_header Host "grafana.domain.tld"`.

**Comment by rylerin** [comment]
Unfortunately, @DasSkelett's solution did not work for me. This is likely because I am running Grafana in my kubernetes cluster behind ingress-nginx, which has the nginx.conf file configured differently.

From my understanding, "origin not allowed" errors often arise due to CORS misconfigurations, where ingress-nginx has annotations that allow you to configure that, [ref](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/annotations/#enable-cors).

Does anyone here have the experience with configuring this to fix the "origin not allowed" error message?

**Comment by ilovemysillybanana** [comment]
@rylerin did you ever find a fix for this?

**Comment by ii343hbka** [comment]
@ilovemysillybanana managed to overcome this issue with nginx upstream named as domain name, like 
`upstream api.example.com {  
  server internal_2nd_nginx:8180;  
}  
` and `Host $http_host` at the first and second nginx'es

**Comment by bpawel-bclub** [comment]
> proxy_set_header Host $http_host;

sorted it for me! thanks

**Comment by dac2020** [comment]
I've just installed 9.4.7 and am experiencing the same problem.
There are a lot of posts about it, none seem to work for me and then I found this old issue.

In my case, rocky 9 with latest nginx.
Suggestions included changing the nginx config;

From; proxy_set_header Host $http_host; (which supposedly was the fix)
To; proxy_set_header Host [www.domain.com](http://www.domain.com/);

Using $http_host seems to have been the fix but it's not working now in this new install.
No change no matter which I use.

[20/Apr/2023:15:12:18 -0700] "POST /api/datasources HTTP/1.1" 403 19 "https://www.domain.com/datasources/new?utm_source=grafana_gettingstarted" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/111.0"

I'm not a developer, just an end user but wondering how many are giving up quickly after seeing this problem.
Can someone point me to the actual solution because reading many posts from Google is not helping.

**Comment by dac2020** [comment]
Folks, if I'm having this problem on the very latest version, maybe someone should care.
I'm pretty technical but not a developer and cannot find a solution which implies to me that many others will give up and not bother for very long.

**Comment by A-afflatus** [comment]
> 再次查看新的[CSRF 检查](https://github.com/grafana/grafana/blob/a53fcac7b1b7ebda8c0cb18f7ce92788af92fa32/pkg/middleware/csrf.go#L29-L35)，这不仅对 IPv6 地址有影响，而且在反向代理设置中更改标头的情况下也是`Host`如此。**配置您的 rev 代​​理以保留原始`Host`标头。**
> 
> 对于 nginx：`proxy_set_header Host $http_host;` 对于 Apache2：`ProxyPreserveHost On`

I am using Spring Gateway, how should I configure it? After configuring it this way, the problem is still not resolved.
```java
@Override
    public Mono<Void> filter(ServerWebExchange exchange, GatewayFilterChain chain) {
        String originalHost = exchange.getRequest().getHeaders().getFirst(HttpHeaders.HOST);
        String originalOrigin = exchange.getRequest().getHeaders().getFirst(HttpHeaders.ORIGIN);
        return super.filter(exchange.mutate()
                .request(builder -> builder
                        .header(HttpHeaders.HOST, originalHost)
                        .header(HttpHeaders.ORIGIN, originalOrigin))
                .build(), chain);
    }
```

**Comment by jmthomas** [comment]
I'm using traefik and this worked for me:
```
http:
  routers:
    grafana-router:
      rule: PathPrefix(`/grafana`)
      service: service-grafana
  services:
    service-grafana:
      loadBalancer:
        passHostHeader: true
        servers:
          - url: "http://openc3-grafana:3000"
```

**Comment by mndxt007** [comment]
For IIS, below worked fine (CMD - Admin):

`%WINDIR%/system32/inetsrv/appcmd.exe set config  -section:system.webServer/proxy /preserveHostHeader:"True"  /commit:apphost`

**Comment by tsvetomilaignatova** [comment]
> For IIS, below worked fine (CMD - Admin):
> 
> `%WINDIR%/system32/inetsrv/appcmd.exe set config -section:system.webServer/proxy /preserveHostHeader:"True" /commit:apphost`

Thank you :) It worked for me as well and saved a lot of time and efforts. Thanks for sharing!
