### ISSUE TITLE
question: Builds and downloads

### ISSUE THREAD

**Issue by joeblew99** [grafana/grafana#4511]
I was looking here: http://grafana.org/download/

where are the download for OSX ?

Also any downloads for Arm V7 or V8 ?

I see that its a pretty easy build : http://docs.grafana.org/project/building_from_source/

Would be cool then if the build tool coudl be changed to make a osx and ARM builds :)

**Comment by torkelo** [comment]
you can make builds for arm or osx using those instructions. 

just "go run build.go build" , then "grunt release"

**Comment by torkelo** [comment]
oh, and btw, we want to add osx builds & homebrew at some time in the future (or if we get a PR with it) , but so much else to do
