### ISSUE TITLE
cannot query elastic search

### ISSUE THREAD

**Issue by nskalis** [grafana/grafana#4512]
Hi guys,

Would you be so kind please and possibly advise on what is wrong when am trying to connect to an Elasticsearch instance (?) More specifically, while I do have connectivity to the Elasticsearch instance from nl-ams02c-ispctl01 where Grafana is installed 
```
@nl-ams02c-ispctl01 grafana]$ curl http://nl-ams02c-isptrf01.SNIP:9204/ { "name" : "nl-ams02c-isptrf01", "cluster_name" : "IP-spotlight.IXmac", "version" : { "number" : "2.2.1", "build_hash" : "d045fc29d1932bce18b2e65ab8b297fbf6cd41a1", "build_timestamp" : "2016-03-09T09:38:54Z", "build_snapshot" : false, "lucene_version" : "5.4.1" }, "tagline" : "You Know, for Search" }
```
And when I try to add the data source in Grafana's UI with the following parameters: 
```
Url: http://nl-ams02c-isptrf01.SNIP:9204 
Index name: IXmac which is an alias for all the indices 
Version: 2 
Time field name: time_stamp
```

Test connection does not return anything and I cannot see anything in the logs also. When I try to add a graph into a panel, the fields are not autocompleting. But network-wise and elastic-configuration-wise everything looks good. Could you please advise on how-to troubleshoot this ?

Nikos

**Comment by torkelo** [comment]
that is strange, what does you browser console & network say? (chrome dev tools)

Also anything in the grafana server log?

**Comment by nskalis** [comment]
@torkelo sorry just came to the office.
i noticed that the browser tries to establish a connection to the elastic search port (which was not expected by me), i thought that the browser (client-side) should contact the grafana server (port 3000) and grafana server to query elastic search server, rather than exposing the es port..
i'll open the communication for the es port, and that should resolve the issue. will do tonight.
