### ISSUE TITLE
Docs: Developers page could include more information and links to resources

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#45145]
The [Developers](https://grafana.com/docs/grafana/latest/developers/) page is currently quite empty , only containing 

> This section of the documentation contains pages with resources for Grafana developers.

Based on feedback, could be a good place to link to resources, like Grafana contribue guide, Tutorials, community site etc.

**Comment by GrafanaWriter** [comment]
I agree. We are evaluating how best to surface developer content. @achatterjee-grafana adding you for visibility.
