### ISSUE TITLE
Tooltip of last data point shows up for older data points

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4514]
* What grafana version are you using?
grafana-3.0.0-pre1.linux-x64.tar.gz
* What datasource are you using?
InfluxDB 0.11.1 (Latest release)
* What OS are you running grafana on?
Ubuntu.

<img width="1311" alt="screen shot 2016-03-30 at 3 05 46 pm" src="https://cloud.githubusercontent.com/assets/406777/14159107/edf036c0-f688-11e5-86c6-ab9469a094f7.png">

In above the last data point is at 3/26 but tooltip highlights points of 3/26 and tooltip shows of 3/23.

Is this a bug ?

**Comment by deepujain** [comment]
Series are ending at different dates and not all end on 3/26. If i select series one at a time, the date shown at the top is 3/26 (when mouse is at extreme right) after one data moves to old date ( as that series has data only till then) and the date in tool tip changes to older date, however the data point values are still referring to last values for each series (again cursor is at extreme right)

**Comment by torkelo** [comment]
you can fix this by using fill(0) or fill(null) (fill null in combination with nullpoint mode like null or null as zero). 

The all series tooltip requires data points for all series

**Comment by torkelo** [comment]
duplicate https://github.com/grafana/grafana/issues/3063
