### ISSUE TITLE
Grafana play: No elasticsearch dashboard works / shows data

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#45154]
**What happened**:

I am looking for dashboard examples and I went to play.grafana.org to check how to make queries for ES on the newest grafana.
However, none of them work / show data which is queried to ES.

**How to reproduce it (as minimally and precisely as possible)**:

https://play.grafana.org/d/AGS-2BKGz/elasticsearch-join-issue?orgId=1&search=open&query=elastic

Go to play.grafana.org
Search for any dashboard with name `elastic`

**Comment by zuchka** [comment]
@nikobearrr thank for making this issue.

I did some research and the Elastic data sources on play.grafana were disabled following news of the `log4j` vulnerability. We are working on a plan to stand them back up. More on this soon!

**Comment by zuchka** [comment]
@DrMxxxxx hello!

I've added a new ES services with three new dummy datasets. See this folder for newer dashboards for many different datasources.

I will replace the broken Elasticsearch ones that are linked on the homepage right away. Thank you! ❤️ 

folder:
https://play.grafana.org/dashboards/f/2EvL7P9nk/play-2-0?query=

[ES ecommerce data dashboard](https://play.grafana.org/d/PSA7M667k/elasticsearch-8-2-0-sample-ecommerce-orders?orgId=1)

[ES sample flight data](https://play.grafana.org/d/z8OZC66nk/elasticsearch-8-2-0-sample-flight-data?orgId=1&from=1660212000000&to=1660643999000)

[ES sample web logs](https://play.grafana.org/d/PXyvC66nz/elasticsearch-8-2-0-sample-web-logs?from=1657533600000&to=1657792799000&orgId=1)

**Comment by zuchka** [comment]
lmk if you see any issues or places for improvement @DrMxxxxx
