### ISSUE TITLE
Table Panel: Footer not working correctly in macOS Safari Browser

### ISSUE THREAD

**Issue by tillsteinbach** [grafana/grafana#45183]
**What happened**: The new Footer option is not behaving correctly on macOS Safari. When the table is short the footer is not visible until scrolling down. When the table is long the footer appears when scrolling to the bottom and disappears again when completely scrolling to the top

**What you expected to happen**: Expectation is to have the footer always visible as in other browsers

**How to reproduce it (as minimally and precisely as possible)**: Enable footer on any table, view with macOS Safari.

**Anything else we need to know?**: see gif:
![ezgif-7-9fcf3651d2](https://user-images.githubusercontent.com/3825852/153293881-748416f2-ceb1-42bb-8b51-d381bc21e1d6.gif)

**Environment**:
- Grafana version: 8.3.6 (but also seen on play git running 8.4)
- Data source type & version: Any data source
- OS Grafana is installed on: Docker running on Ubuntu Linux
- User OS & Browser: macOS 11.6.3, Safari 15.3
- Others:

**Comment by steefan85** [comment]
Have the same problem at MacOS / Safari: #52365

**Comment by mdvictor** [comment]
Hello! This is now fixed and will be available in the next patch for v9.1.
