### ISSUE TITLE
Axis label is displayed on both X and Y axes

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#45181]
**What happened**:

Defined an axis label. Label is displayed both on X and Y axes on the Time Series visualization.

![Screenshot 2022-02-09 14-35-31 axis label](https://user-images.githubusercontent.com/3270755/153276879-e9b0fe2a-353f-4162-87d6-d0e2d1e77097.png)

Note that the problem doesn't happen when the axis label is defined in an override. Override axis labels are only displayed on the Y axis.

![Screenshot 2022-02-09 14-29-31 base label](https://user-images.githubusercontent.com/3270755/153276550-98fe6700-30a6-4ea6-ad67-4a3bed310d9b.png)
![Screenshot 2022-02-09 14-29-57 override label](https://user-images.githubusercontent.com/3270755/153276575-ac8600d9-b59c-443a-940d-6679305e4844.png)

**What you expected to happen**:

The axis label is only displayed on the Y axis.

**How to reproduce it (as minimally and precisely as possible)**:

Select the Time series panel, define an axis label.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.3.6
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Firefox 96.0
- Grafana plugins:
- Others:

**Comment by adeverteuil** [comment]
Never mind, I see that the Axis:Label field is for the X axis (https://github.com/grafana/grafana/pull/41142), and setting the Y axis is now done by series overrides.

This issue is fixed by https://github.com/grafana/grafana/pull/44713 (Grafana v8.4.0 probably)

**Comment by zoltanbedi** [comment]
Yes this is going to be fixed in 8.4.0.
