### ISSUE TITLE
"bad login data" instead of "Logged In" at /login after upgrade to 8.3.6

### ISSUE THREAD

**Issue by brettbeeson** [grafana/grafana#45198]
I'm using Grafana 8.2.5 in linux. The following works for this version:
```
grafana-server -v
Version 8.2.5 (commit: b57a137acd, branch: HEAD)
curl -d "user=rc549&password=XXXXXX" -X POST http://localhost:3000/login
{"message":"Logged in"}
```
and I get a session cookie. I use this method to "auto" login users via a PHP script. 

I upgraded and this now fails:
```
sudo apt upgrade grafana
grafana-server -v
Version 8.3.6 (commit: bf8766bbf2, branch: HEAD)
curl -d "user=rc549&password=XXXXXX" -X POST http://localhost:3000/login
{"message":"bad login data"}
```
I've excluded proxy/https issues (see urls above). I can't find official docs to /login so maybe this is an outdated method? Nevertheless, I'll need to retain it for existing users, and hence can't upgrade (eeck).

Thanks in advance,  Brett

**Environment**:
- Grafana version: 8.3.6 (tested 8.3.4 too)
- Data source type & version: n/a
- OS Grafana is installed on: Ubuntu 20
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by zoltanbedi** [comment]
Take a look at this pr https://github.com/grafana/grafana/pull/39837 you need to send the credentials as json now. Also in the future please ask questions in our slack channel.
