### ISSUE TITLE
2 logs from `packages/grafana-ui/src/components/Logs/LogDetailsRow.test.tsx`

### ISSUE THREAD

**Issue by hugohaggmark** [grafana/grafana#45194]
I had a quick look at this and there seems to be some semantic problem with the HTML here that RTL doesn't understand and fixing it would mean to change the component html. Because this component is very connected to use cases in Explore I'm going to pass this issue on to the @grafana/observability-experience-squad instead. Let me know if this is the correct squad @aocenas @ivanahuckova.

**Comment by ivanahuckova** [comment]
I have moved this to @grafana/observability-logs-and-traces. Will have a look at this. Thanks @hugohaggmark!
