### ISSUE TITLE
React panel plugin - Form component register props issue

### ISSUE THREAD

**Issue by CurlyDev1** [grafana/grafana#45208]
**What happened**: I've created a panel plugin using the command npx @grafana/toolkit plugin:create my-plugin and I have tried to create a simple form using the @grafana/ui Form component, however following the examples from the storybook(https://developers.grafana.com/ui/latest/index.html?path=/docs/forms-example-forms--basic) I can't the ref prop to accept the register function as typescript complains with the following error:
**`ERROR in src/SimplePanel.tsx:25:17
  TS2322: Type 'UseFormRegisterReturn' is not assignable to type 'Ref<HTMLInputElement> | undefined'.
    Property 'current' is missing in type 'UseFormRegisterReturn' but required in type 'RefObject<HTMLInputElement>'.
      23 |                 type='text'
      24 |                 name='test'
    > 25 |                 ref={register({ required: true })}
         |                 ^^^
      26 |               />
      27 |               <Button type='submit'>Submit</Button>
      28 |             </>
  
  ERROR in src/SimplePanel.tsx:25:33
  TS2322: Type 'boolean' is not assignable to type 'never'.
      23 |                 type='text'
      24 |                 name='test'
    > 25 |                 ref={register({ required: true })}
         |                                 ^^^^^^^^
      26 |               />
      27 |               <Button type='submit'>Submit</Button>
      28 |             </>`**

**What you expected to happen**:
I expect no errors or documentation to be correct 

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel plugin by running the command `npx @grafana/toolkit plugin:create my-plugin`
2. cd into my-plugin and `run npm install`
3. run  `npm run watch`
4. cd into src/SimplePanel.tsx and replace all contents with the following:
**`import React, { PureComponent } from 'react';
import { PanelProps } from '@grafana/data';
import { SimpleOptions } from 'types';
import { Form, Input, Button } from '@grafana/ui';

interface Props extends PanelProps<SimpleOptions> {}

export class SimplePanel extends PureComponent<Props> {
  constructor(props: any){
    super(props)
    this.state = {}
  }

  render() {
    return (
      <Form 
        onSubmit={() => alert('submitted')}
      >{
        ({register, errors}) => (
            <>
              <Input
                type='text'
                name='test'
                ref={register({ required: true })}
              />
              <Button type='submit'>Submit</Button>
            </>
          )
        }
      </Form>
    )
  }
}
`** 

**Anything else we need to know?**:

**Environment**:
- @grafana/data: 8.3.5
- @grafana/toolkit: 8.3.5
- @grafana/ui: 8.3.6

**Comment by zoltanbedi** [comment]
Please take a look at the https://developers.grafana.com/ui/canary/index.html?path=/docs/forms-form--basic canary relaes of our storybook site it has the uptodate code you need to use for the form to work. We are working on updating the latest site right now.

**Comment by CurlyDev1** [comment]
Thanks @zoltanbedi in my case it was the fact that I was omitting the defaultValues props from Form
