### ISSUE TITLE
[Feature Request]  Template variables update on dashboard refresh

### ISSUE THREAD

**Issue by nav-star** [grafana/grafana#4520]
Hello,

I'm hitting a situation where a template variable must be updated upon every dashboard refresh (or autorefresh). That is not to be confused with the page reload.

For example. I'm polling an influxdb measurement showing the top N IP speakers as visible from a router.
So I'm setting up a template variables populated by selecting the last field entries  of a measurement (the values are string - IPv4 address for the top speaker, the second, the third and so on.). 
Then I need to use those varibles as a tag values for selecting another influxdb measurement, which will then show what the traffic looks like for the particular TOP N speaker.

And since the top N speakers change pretty dynamically, I need this to be updated with the dashboard refresh.

So I imagine this as adding extra option - "On dashboard refresh" along with ("Never", "Refresh on load" and "On Time range change"  for Grafana 3.0.0).
And of course selecting  "On dashboard refresh", must also include the rest of the update  triggers.

Another potential enhancement - in Grafana 3.0.0 I saw the template variable of type "query" has gotten much more strict and limited. In Grafana 2.6.0 I'm able to query a measurement (instead of tag keys and values only) and use the result after applying RegExp to get rid of the time stamps. Thanks to Grafana returning the whole select output.

But in Grafana  3.0.0 it seems there is some internal limitation added and the same query on a measurement returns just the timestamps and not the actual values. Which is of course useless.
So why don't make the usage of the queries more flexible and open. 

Also assigning values to  template variable by parsing text files residing on the local file system seems to me quite appropriate.

Best regards!

**Comment by torkelo** [comment]
> Another potential enhancement - in Grafana 3.0.0 I saw the template variable of type "query" has  gotten much more strict and limited. In Grafana 2.6.0 I'm able to query a measurement (instead of tag keys and values only) and use the result after applying RegExp to get rid of the time stamps. Thanks to Grafana returning the whole select output.

No there has been no change like this. What you probably encounter is InfluxDB 0.11 breaking change, in that it returns data in a different format. Try latest 3.0 build for support for Influxdb 0.11


Not sure what this issue is about. Grafana 3.0 allows you to refresh variables when time range changes.

**Comment by nav-star** [comment]
Hi,

Thanks for commenting on this.

Is the template variable update on "time range change" the same as  update on "dashboard refresh"?
I mean, if for example there is auto-refresh set for every 30 seconds (by setting "Refreshing every:" in Time range control)  - will the template variables be updated too?

Thanks!
