### ISSUE TITLE
SingleStat - Missing/Zero/Null Value

### ISSUE THREAD

**Issue by kramsey79** [grafana/grafana#4521]
Issue: I'm currently pushing Windows perf stats to a Graphite/Carbon DB for Grafana to display via graphs and it's working great!!! Now I'm just trying to setup some health checks but when trying to send a single stat value every 5-10 minutes or so it will not show using Singlestat dashboard in Grafana. I have tried a couple different ways to test this, both of which are basically using the same simple method. I verified the stat is present and looks correct in the .wsp file just in case. And when I login to Graphite to verify the stat IS in the database even though I don't see it right away, when I select "Line Mode -> Draw Null as Zero" I can see the single stat value just fine in the Graphite Composer.

So like I said this is a single value that only gets updated every 5-10 minutes as a health check for an SMTP relay. So I just wanted to run the check and update the DB with one value or another so I can see Green/Healthy or Red/Failed in Grafana. And I'm pretty sure Grafana see's the value because it sets the coloring thresholds automatically within the range of integers I'm sending. It looks really easy to do in the dashboard setup and from what I've read online yet I can't get it to work.

I currently have the "Big value" set to "current" in Options and "keepLastValue(100)" set in Metrics but have tried many combinations which do not work either.

I'm sure it's something really simple that I have just not yet tried. Please advise. Thank you in advance.

Version: 2.6.0
DataSource: Graphite/Carbon
OS: Ubuntu 14.04

**Comment by kramsey79** [comment]
So I just went through functions list again and "changed()" looks like exactly what I want. I could set either 0 or 1. 

0 = Healthy | 1 = Failed

So I guess the important settings I need help with are:
-Metric config ("changed" or something else) and then add to it???
-Max data points (change from 100 or leave it??) I only need the most recent value
-Big value (current/min/max???) none of these sound right...maybe current???
-Time range (probably can leave this at 1h)???

**Comment by kramsey79** [comment]
Actually drawAsInfinite() sounds even more like what I want. But can't get that one to work either :(

**Comment by torkelo** [comment]
keepLastValue()  (without any arguments), and in the Options tab select "current", should work.

**Comment by kramsey79** [comment]
That was the first thing I tried which did not work. The only difference is I could only get it to show with a (0) or as undefined and not (). Is there a trick to making this show without a value?
