### ISSUE TITLE
[Bug] Singlestat background color 

### ISSUE THREAD

**Issue by herver** [grafana/grafana#4523]
Hi all, 

I'm testing Grafana 3.0-beta1 and noticed a behaviour change in the way background colors are handled in singlestat panels:

With grafana 2.6, I had this:
![2016-04-01-09-08-56_1255x701](https://cloud.githubusercontent.com/assets/218323/14200238/c0888c2a-f7e9-11e5-9293-ba690f1be496.png)

And now with grafana 3.0-beta1 I get this:
![2016-04-01-09-07-47_1261x686](https://cloud.githubusercontent.com/assets/218323/14200257/e02f1e0e-f7e9-11e5-9db1-99b733fd3137.png)

It seems like it's always selecting the 2nd color although I do not have thresholds configured. Is this a new undocumented behaviour or maybe just a regression ?

**Comment by torkelo** [comment]
your color thresholds look empty, try specifying values in the threshold input box
