### ISSUE TITLE
Time-Series panel with large scale and small thresholds as coloured regions broken

### ISSUE THREAD

**Issue by siegenthalerroger** [grafana/grafana#45235]
**What happened**: The time-series panel started behaving weirdly, showing no data and having the legend render off-screen.

**What you expected to happen**: For the time-series panel to just work or at least show an error message.

**How to reproduce it (as minimally and precisely as possible)**: 

1. Have a time-series that has values that range from 0 - 10000.
2. Set thresholds to base -> green, 0.1 -> yellow, 0.25 -> red.
3. Show the thresholds as coloured regions(!)

<img width="933" alt="image" src="https://user-images.githubusercontent.com/6848427/153417476-c86a23b0-1582-439c-80bc-d3201577becf.png">

The data is still loaded and show, however the time-series are no longer displayed. It is also possible to get the legend to render outside of the panel. 

<img width="1055" alt="image" src="https://user-images.githubusercontent.com/6848427/153417669-7265d41f-4d55-4d46-a453-345af90b03ba.png">

With a max value for the y axis set we get a graph again:

<img width="834" alt="image" src="https://user-images.githubusercontent.com/6848427/153417835-54cfb2e0-4c0b-45c2-b17b-4930c071f910.png">

**Environment**:
- Grafana version: 8.3.5
- Data source type & version: Prometheus
- OS Grafana is installed on: Docker
- User OS & Browser: MacOS & Chrome
- Grafana plugins: No additional
- Others:

**Comment by torkelo** [comment]
@leeoniya was able to replicate this, can you investigate this when you have time. Something funky is going on. 

Was able to replicate it with this panel but only some times

<details>
   <summary>JSON Block</summary>
```json
{
  "id": 2,
  "gridPos": {
    "x": 0,
    "y": 0,
    "w": 12,
    "h": 9
  },
  "type": "timeseries",
  "title": "Panel Title",
  "targets": [
    {
      "refId": "A",
      "datasource": {
        "type": "testdata",
        "uid": "PD8C576611E62080A"
      }
    },
    {
      "datasource": {
        "uid": "PD8C576611E62080A",
        "type": "testdata"
      },
      "refId": "B",
      "hide": false
    },
    {
      "datasource": {
        "uid": "PD8C576611E62080A",
        "type": "testdata"
      },
      "refId": "C",
      "hide": false
    },
    {
      "datasource": {
        "uid": "PD8C576611E62080A",
        "type": "testdata"
      },
      "refId": "D",
      "hide": false
    }
  ],
  "options": {
    "tooltip": {
      "mode": "single",
      "sort": "none"
    },
    "legend": {
      "displayMode": "list",
      "placement": "bottom",
      "calcs": []
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "linear",
        "barAlignment": 0,
        "lineWidth": 1,
        "fillOpacity": 0,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "auto",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "area"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 0.02
          }
        ]
      }
    },
    "overrides": []
  },
  "datasource": null
}
```
</details>

**Comment by siegenthalerroger** [comment]
@leeoniya yes I had the same console error, thanks for the quick resolution
