### ISSUE TITLE
apt packages have Origin "grafana stable" and Suite "stable"

### ISSUE THREAD

**Issue by caugner** [grafana/grafana#45242]
**What happened**:

In order to have `unattended-ugprades` upgrade grafana automatically on Ubuntu 20.04 LTS (focal), I had to add the following line to the `/etc/apt/apt.conf.d/50unattended-upgrades` config:

```
Unattended-Upgrade::Allowed-Origins {
        "${distro_id}:${distro_codename}";
        "${distro_id}:${distro_codename}-security";
        // Extended Security Maintenance; doesn't necessarily exist for
        // every release and this system may not have it installed, but if
        // available, the policy for updates is such that unattended-upgrades
        // should also install from here by default.
        "${distro_id}ESMApps:${distro_codename}-apps-security";
        "${distro_id}ESM:${distro_codename}-infra-security";
//      "${distro_id}:${distro_codename}-updates";
//      "${distro_id}:${distro_codename}-proposed";
//      "${distro_id}:${distro_codename}-backports";
        "grafana stable:stable"; // Added.
};
```

This is due to the fact that the apt packages have the following Origin and Suite:

```
# grep -P "Origin|Suite" /var/lib/apt/lists/packages.grafana.com_oss_deb_dists_stable_InRelease
Origin: grafana stable
Suite: stable
```

**What you expected to happen**: 

Afaik the Origin would usually just be `grafana` and the Suite would be `focal` (`${distro_codename}`).

**How to reproduce it (as minimally and precisely as possible)**:

Add `"grafana:${distro_codename}";` instead and `unattended-upgrades` won't upgrade grafana.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4 -> 8.3.6
- Data source type & version: n/a
- OS Grafana is installed on: Ubuntu 20.04.3 LTS
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

I suggested a similar change over at https://github.com/mattermost/mattermost-omnibus/issues/58.

**Comment by tleopold** [comment]
@julienduchesne Do you have any updates on this issue?

**Comment by julienduchesne** [comment]
My initial guess is that it's probably too late to fix this once the repository has been initially created

**Comment by caugner** [comment]
> My initial guess is that it's probably too late to fix this once the repository has been initially created

Afaik you specify the Origin/Suite for each release, so fixing it for upcoming releases is indeed possible.

**Comment by summerwollin** [comment]
Closing as this is stale

**Comment by caugner** [comment]
@summerwollin Did you intend to close this as wontfix? IIRC This issue prevents admins from upgrading their Grafana instances with unattended upgrades.
