### ISSUE TITLE
[Bug] Template Interval doesn't work when zoomed out 

### ISSUE THREAD

**Issue by xpinkyx** [grafana/grafana#4525]
In my dashboard, I have got a template interval variable, which is used to display the chosen time in some different panels. When I zoom out, the template gets overridden from the time picker. When I now change my template interval, the panels seems to reload, but the shown time range doesn't change back to the template value. I'm using a grafana ran from master, done a few minutes ago on ubuntu 15.1.

Also, I'm not sure if it's also a bug that it's possible to zoom out the panels where I used the template variables? And if not, is there a way to limit the shown time range? I just want to prevent that it comes to any problems if some users viewing the dashboard try to show the last 5 years, in my case the relevant data are just some hours in the past..

**Comment by torkelo** [comment]
Can you show your queries?

**Comment by xpinkyx** [comment]
I'm not sure, if this is what you want to know, but I just added in the Time Range Tab at "Override relative time Last" my interval template. In my panels I haven't specified any queries to feed it with data from elasticsearch, I used the given dropdown-menu for this.

**Comment by torkelo** [comment]
Relative time override is only applied when dashboard time is relative, so if you zoom out the time range become absolute and panel relative time override is disable (until you change dashboard to relative time range again)

**Comment by xpinkyx** [comment]
Okay, thanks.. Is there a way to change this behaviour, e.g. disable zoom out or disable changing to absolute time?

**Comment by torkelo** [comment]
You want to disable zoom in / out? No there us no way to do that
