### ISSUE TITLE
client error 403 with new unified alerting and prometheus data source in 8.3.x (8.3.6)

### ISSUE THREAD

**Issue by ericfaure007** [grafana/grafana#45250]
**What happened**:
I have enabled the new unified_alerting feature.
I would like to create an alert from a panel using prometheus datasource:
The metric is:
instance:node_cpu_utilisation:rate1m{job="node-exporter", instance="an-openshift-node"}
The graph is worrking fine.
When I add an alert and save the setup. The alert is triggered, but because of an error in the alert itself, hereunder the logs:

t=2022-02-10T15:36:11+0000 lvl=eror msg="Range query failed" logger=tsdb.prometheus query="instance:node_cpu_utilisation:rate1m{job=\"node-exporter\", instance=\"an-openshift-node\"}" err="client_error: client error: 403"
t=2022-02-10T15:36:11+0000 lvl=info msg="level=debug component=dispatcher msg=\"Received alert\" alert=\"Panel Title[83d7796][active]\"" logger=alertmanager org=1
t=2022-02-10T15:36:13+0000 lvl=eror msg="Range query failed" logger=tsdb.prometheus query="instance:node_cpu_utilisation:rate1m{job=\"node-exporter\", instance=\"an-openshift-node\"}" err="client_error: client error: 403"
t=2022-02-10T15:36:13+0000 lvl=eror msg="Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: client_error: client error: 403" logger=context userId=11 orgId=1 uname=myuser error="Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: client_error: client error: 403" remote_addr=my-ip
t=2022-02-10T15:36:13+0000 lvl=info msg="Request Completed" logger=context userId=11 orgId=1 uname=my-user method=POST path=/api/v1/eval status=400 remote_addr=my-ip time_ms=24 size=146 referer=https://my-server:3000/alerting/VS0Lrf-7k/edit

I also get some other errors like:
2022-02-10T15:50:11+0000 lvl=info msg="level=debug component=dispatcher msg=\"Received alert\" alert=\"Panel Title[83d7796][active]\"" logger=alertmanager org=1
t=2022-02-10T15:51:11+0000 lvl=eror msg="Range query failed" logger=tsdb.prometheus query="instance:node_cpu_utilisation:rate1m{job=\"node-exporter\", instance=\"an-openshift-node\"}" err="server_error: server error: 504"

**What you expected to happen**:
No error and alert working.

**How to reproduce it (as minimally and precisely as possible)**:
enable unified_alerting in grafana.ini, restart server
using an existing prometheus data source.
create a new panel with prometheus data source
metric browser: instance:node_cpu_utilisation:rate1m{job="node-exporter", instance="an-openshift-node"}
add an alert.
The alert is triggering an error, due to 'client error: 403'

**Anything else we need to know?**:
Using prometheus data source:
prometheus server is the builtin one from openshift 4.7.
Using 'Custom HTTP Headers': Authorization: bearer the-openshift-token

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: prometheus (version from grafana 8.3.6?)
- OS Grafana is installed on: centos8 stream
- User OS & Browser: AAD user & chrome
- Grafana plugins: some
- Others: N/A

**Comment by zuchka** [comment]
Thanks for creating this issue, @ericfaure007 

the timing of this issue to 8.3.6 reminds me of this problem, which a lot of users were hitting when running Grafana behind a reverse proxy.  

Are you still encountering this error?

**Comment by ericfaure007** [comment]
The connection is not going through a reverse proxy as far as I know.
I removed the prometheus config and use azure datasources now to set the needed alerts.
I can't test anymore.
Thanks for your help.

**Comment by egenii007** [comment]
I have the same problems on grafana 8.3.4

**Comment by ctron** [comment]
I am having the same issue with grafana 8.5.3

**Comment by ctron** [comment]
What worked for me was to change the HTTP method from POST to GET.
