### ISSUE TITLE
Datasource provisioned throught API with editable False / readonly True are still editable

### ISSUE THREAD

**Issue by xenofree** [grafana/grafana#45274]
**What happened**:

Datasource created through API

```
        data = {'name': 'Prometheus', 'type': 'prometheus', \
                'access': 'proxy', 'editable': False, 'readOnly': True, \
                'jsonData': {''httpMethod': 'POST', \
                             'manageAlerts': False, 'timeInterval': '1m'}, \
                'url': 'http://xxxx:9191', 'isDefault': True}

r = requests.post("{grafana_url}/api/datasources", auth=self.grafana_auth, headers=self.grafana_headers, data=data)
```
![datasource_editable](https://user-images.githubusercontent.com/35098906/153566482-07a5e14e-0501-489a-ba27-898b4fc94fbd.png)

**What you expected to happen**:

Same as datasource created through provisionning file

![datasource_readonly](https://user-images.githubusercontent.com/35098906/153566651-07ba35bc-6654-41e7-9455-74a2d76c31e7.png)

**Environment**:
- Grafana version: Docker Version 8.3.6 (commit: bf8766bbf2, branch: HEAD)

**Comment by zoltanbedi** [comment]
This is by design see https://github.com/grafana/grafana/pull/19006
