### ISSUE TITLE
Datasource: Securejsondata stripped away while creating/updating data source

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#45273]
**What happened**:
Securejsondata stripped away while creating/updating data source

**How to reproduce it (as minimally and precisely as possible)**:
Create a new data source that uses secure json data - CloudWatch or Azure Monitor for example. 

**Environment**:
- Grafana version: 8.4-pre (main)
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

![securejsondata](https://user-images.githubusercontent.com/2388950/153560872-6f88d73e-4ff2-4853-82d4-bff390631c9f.gif)

**Comment by leventebalogh** [comment]
Hmm, this is strange.

I just tried to reproduce it locally using the `v8.4.x` branch but it seems to work all fine for me 🤔 

https://user-images.githubusercontent.com/9974811/153567351-d2aeef21-036f-4f79-94a2-8f277c5a4ae2.mov

**Comment by marefr** [comment]
Seems to have been introduced by #44987
