### ISSUE TITLE
Plugins: can't uninstall deprecated plugin via the plugin catalog

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#45281]
**What happened**:
If you have a plugin installed that gets deprecated it can not be uninstalled via the plugin catalog. The reason is that the property `isPublished` is returned from the backend with the value `false` which makes the frontend think that this is a plugin not managed via grafana.com.

Backend is returning `isPublished: false` because as soon as the plugin is deprecated it is excluded from the data returned from grafana.com. 

See example below:
![image](https://user-images.githubusercontent.com/172951/153575755-6450f607-d097-420b-82b5-f76ebe685ff7.png)

**What you expected to happen**:
I can uninstall the plugin even if it gets deprecated.

**How to reproduce it (as minimally and precisely as possible)**:
1. install the `grafana-k6cloud-datasource` via the grafana-cli
2. go to the plugin catalog in the UI and find the k6 datasource plugin.
3. try to uninstall the plugin via the UI.

**Anything else we need to know?**:
Proposed solution:
- Extend the garafan.com API with a new boolean property `deprecated` that will include deprecated plugins in the result if specified.
- Check the status returned from the API when fetching the data from the grafana.com API and act accordingly.
- It might be a good idea to expose some kind of information to the frontend about the plugin being deprecated so we can display that to the end user.

**Environment**:
- Grafana version: 8.4
- Grafana plugins: grafana-k6cloud-datasource

**Comment by FTFX** [comment]
This issue is still occurring on 10.1.5, plugin is Cloudflare Grafana App.

**Comment by andresmgot** [comment]
hi @FTFX I could verify that the bug is fixed in 10.1.5:

https://github.com/grafana/grafana/assets/4025665/94f1fb91-99f9-4163-9f2c-0ebfd5307549

Maybe you are seeing a different issue?

**Comment by FTFX** [comment]
Hi @andresmgot, thanks for your response! There is no "Uninstall" button on my side, but I noticed that my plugin version is 0.2.4, maybe that could cause differences? I noticed that Grafana says plugin update is available, but there is also no update button.
![image](https://github.com/grafana/grafana/assets/12870191/8228cc06-4451-4933-960d-0833f34365b2)
![image](https://github.com/grafana/grafana/assets/12870191/15a10951-c299-4512-9f22-09d563da66e7)
Browser: Microsoft Edge 117.0.2045.60

**Comment by andresmgot** [comment]
I see, it seems indeed a bug only present if the plugin is not up to date. The bug will be fixed in 10.2.0 but in the meantime you can upgrade the plugin to the latest version 0.2.5 and uninstall it or directly uninstall it with the Grafana cli: `grafana cli plugins uninstall cloudflare-app`

**Comment by FTFX** [comment]
I can confirm this is fixed in 10.2.0, thanks!
