### ISSUE TITLE
[Question] grafana behind reverse-proxy, icons missing

### ISSUE THREAD

**Issue by hryamzik** [grafana/grafana#4528]
I'm running grafana version: 2.6.0+dfsg-1 on ubuntu 16.04.

I have the following line in my ```/etc/grafana.ini```:

```ini
root_url = https://some.some.com:443/grafana/
```

Everything works except I miss all the icons:

![image](https://cloud.githubusercontent.com/assets/1643962/14211442/cdaf821c-f836-11e5-8196-1bb6e1946698.png)

And I don't see any errors in chrome console so I'm a bit stuck about the cause of this issue.

**Comment by torkelo** [comment]
Very strange, no one else has reported anything similar (and many run it behind reverse proxy and https).

Try removing the 443 port from root_url (its the default https port)

**Comment by hryamzik** [comment]
Nope, it didn't make any sense but it's good to know default port could be omitted.
