### ISSUE TITLE
Docs: Update plugin migration guide with information how to migrate from using TimeSrv

### ISSUE THREAD

**Issue by marefr** [grafana/grafana#45294]
Update https://grafana.com/docs/grafana/latest/developers/plugins/migration-guide/ and https://grafana.com/docs/grafana/latest/developers/angular_deprecation/ guide with information how to migrate from using TimeSrv. 

Think the work I did for the SQL datasources in this [PR](https://github.com/grafana/grafana/pull/45241) could be used as a base for the updates.

**Comment by marefr** [comment]
@GrafanaWriter my team are planning to write this because it's technical/nearly impossible for you (I think). We'll ask you to review it when ready.

**Comment by GrafanaWriter** [comment]
Thank you for clarifying @marefr. We look forward to helping.

**Comment by chri2547** [comment]
Closing per guidance from @marefr. There may be associated work in the future, but it's yet to be defined. A new issue can be opened at that time.
