### ISSUE TITLE
confused to Tooltip values sort

### ISSUE THREAD

**Issue by Fiv5** [grafana/grafana#45292]
**What happened**:
when specify tooltip option `Values sort order`, the final display is sort by formatted value, i'm confused
 that why not sort by raw value.

for example this:
![8xbmBITuvb](https://user-images.githubusercontent.com/23014093/153588798-f732ab58-5821-4524-a915-f33a36412d2c.png)

See the implementation code: https://github.dev/grafana/grafana/blob/fed112ef3bd699ece8e6a66c3b012dc6fbb0ee0f/packages/grafana-ui/src/components/uPlot/plugins/TooltipPlugin.tsx#L246

**What you expected to happen**:
In the example above, **backend_01**'s raw value smaller than **backend_02**'s raw value but look like bigger than **backend_02** in display.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I also found that we use `Intl.Collator` for sort compareFunction, when specify `numeric: true`, it would not get the same result if use native sort compareFunction in comparing decimals. e.g.  
```js
[0.1, 0.21, 0.3].sort((a, b) => new Intl.Collator(undefined, {numeric: true, sensitivity: 'base'}).compare(a, b)) // [0.1, 0.3, 0.21]
```
Intl.Collator issue: https://bugzilla.mozilla.org/show_bug.cgi?id=1312388
Related Conversation: https://github.com/grafana/grafana/pull/43615

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by Fiv5** [comment]
I seem to understand why this is done, and the values of different series may not be on the same dimension.

![image](https://user-images.githubusercontent.com/23014093/153592462-1a9e5419-635f-4bf3-ba96-f6a0ab5660ed.png)

**Comment by boombatower** [comment]
This makes the sorting semi-useless in my case.

![image](https://user-images.githubusercontent.com/209374/155192454-0198b77c-5787-43ad-aea1-e76fa90fd486.png)

**Comment by jdmaloney** [comment]
I'm running into this here also.  I just noticed after our upgrade to 8.4.1 that the Tooltip supported sorting and got excited, but have hit same situation that sort IS working, just by formatted value and not the raw value like it should. Not very useful when plotting file system usage either with PB less than GB.
<img width="612" alt="Screen Shot 2022-02-22 at 2 44 45 PM" src="https://user-images.githubusercontent.com/16138910/155216532-beb06c6f-b391-4f03-bef2-29dcf9f9b016.png">

**Comment by CarsonHoffman** [comment]
It seems that even when the units are the same, it sorts things lexicographically but ignoring leading zeros (this is with descending sort):

<img width="95" alt="image" src="https://user-images.githubusercontent.com/19721219/155224242-1baa814a-18b7-4d33-b6ed-7f6ccda99990.png">

(Also on 8.4.1.)

**Comment by boombatower** [comment]
This seems rather breaking. Any chance this gets corrected?

**Comment by justinsmalley** [comment]
Still not working on 8.4.7. Perhaps testing of PR did not account for leading zeros and negative values?
![image](https://user-images.githubusercontent.com/99200643/164556800-90f0d375-27bf-4f3d-b163-2f80cdecdd73.png)

**Comment by CarsonHoffman** [comment]
[The commit](https://github.com/grafana/grafana/commit/a55274a72d8bf24a7b127c7020c48d831ec4cee3) was merged in at `v8.5.0`.

**Comment by justinsmalley** [comment]
retested on 8.5.0 today and am seeing the same behaviour. Tooltip is set to sort descending. It roughly sorts correctly, but many values are out of order. 

time series panel:
![image](https://user-images.githubusercontent.com/99200643/165142650-9fa5978d-1a38-4802-9ffb-a77a9888da4f.png)

The same in the old graph panel:
![image](https://user-images.githubusercontent.com/99200643/165142602-95af8713-97f6-447c-86e2-05db71845724.png)

**Comment by Gurkanaydn** [comment]
how can i sort by value on bar gauge table
