### ISSUE TITLE
Provisioning UI for Alerting

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#45297]
Add basic support for provisioned alert rules, notification policies, contact points, etc

See BE issue & status here: https://github.com/grafana/grafana/issues/36153 - the FE issues can start when the BE support is there (for each resource type) and we've finalized details.

If the provenance indicates API / File / etc (do we have a final list?), show a banner and prevent user edits:
- [x] #48490
- [x] #48491
- [x] #48492
- [x] #48493

For when the BE impl is complete:
- [x] #48622
- [x] #48623

**Comment by armandgrillet** [comment]
The provisioning UI will be done once we have the provisioning API (8.5.0), we will backport it to 8.5.x.

**Comment by armandgrillet** [comment]
Moving this to Q2 column as we don't need this for 9.0.

**Comment by gillesdemey** [comment]
Moving this back to the backlog as the remaining items are not yet implemented in the API

**Comment by jtheory** [comment]
Update: the API changes are done; we can wrap this up when it makes sense in priorities.

**Comment by Dima-Diachenko-work** [comment]
Probably, this issue could be considered as closed at your next triaging.
