### ISSUE TITLE
Alerting: add detailURL to webhook payload

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#45301]
We currently only add the `generatorURL` which links back to the `edit` page of a particular alert. I'm proposing to add an additional `detailURL` property which links to the detail view of the alert instead.

**Comment by gillesdemey** [comment]
Go for it! 💪

**Comment by joeblubaugh** [comment]
The `generatorURL` comes from the Prometheus alertmanager template system. What if we just replace the edit link with the detail view link instead? Semantically I think that's closer to the "generator" of the alert.
