### ISSUE TITLE
Allow to overwrite alert name with alertname label

### ISSUE THREAD

**Issue by M0rdecay** [grafana/grafana#45308]
### Discussed in https://github.com/grafana/grafana/discussions/45307

<div type='discussions-op-text'>

<sup>Originally posted by **M0rdecay** February 11, 2022</sup>
Right now, the alert name is taken directly from the rule name. Allow to overwrite the name of the alert with the appropriate label.

In our case, we have a few alerts with the same name but different query/label details. In version 7, it was allowed to have several alerts with the same name, but in version 8, this is not allowed if the rules are located in the same directory.</div>

**Comment by grobinson-grafana** [comment]
Let's keep this as a feature request. I will discuss it with the team this afternoon to figure out how we can help here.

**Comment by grobinson-grafana** [comment]
Let's keep this as a feature request. I am going to talk about it with the team this afternoon to figure out how we can help here.

**Comment by grobinson-grafana** [comment]
I suggest we also move the conversation to https://github.com/grafana/grafana/discussions/45307 if that's OK!
