### ISSUE TITLE
[Feature Request] / Add --proxy option to grafana-cli

### ISSUE THREAD

**Issue by PaulKuiper** [grafana/grafana#4530]
I tried to install the Influx 0.8 plugin for grafana 3.0 beta using the grafana-cli, however this does not work behind a company proxy. Just like any other package management like tool (yum, git, pip, etc.) there should be an option to set the proxy (http://user:password@proxyserver:port), globally or using a switch. 

As a workaround you can use git (after setting the proxy settings on git) to download the plugin. So it is a minor inconvience, but it reduces the usabilty of grafana-cli

**Comment by torkelo** [comment]
Have you tried setting standard environment variables for http proxy?

**Comment by PaulKuiper** [comment]
Yes, but I use Influx and other webservices on the localhost. I do not want them to proxy. I googled a little and found that you can bypass disble the proxy for certain locations using the "no_proxy" (or "export_no_proxy") setting. I will try that. Thanks!

**Comment by Othyus** [comment]
I think a proxy option for the grafana-cli is a better option, which can be used by more people
