### ISSUE TITLE
Docs feedback: /developers/plugins/add-support-for-annotations.md

### ISSUE THREAD

**Issue by ecanchev-tibco** [grafana/grafana#45339]
The latest docs for annotations (https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/) are missing important sections. Please refer to older versions of the docs: https://grafana.com/docs/grafana/v7.1/developers/plugins/add-support-for-annotations/

Where can I find more developer info about annotations related to the newer implementation of a plugin (react-based plugin)?
Thanks

**Comment by zuchka** [comment]
attn @achatterjee-grafana & @marcusolsson

**Comment by marcusolsson** [comment]
The docs looks up-to-date to me. In recent versions of Grafana, the annotation editor lets you build the query using the normal query editor and then select dimensions from the query results. Could you share more about what you'd like to do and what you think is missing?

**Comment by ecanchev-tibco** [comment]
Well, for me it isn't very clear how I can create the 'Annotation query editor'.
Once I followed the steps as described in https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-annotations/, I realized that when going to the annotations configuration of a dashboard, my plugin is shown in the dropdown.
But how can I render the query editor there? what are the methods to override or how can I set up my plugin to show that?

**Comment by marcusolsson** [comment]
What version of Grafana are you using? You linked to docs for 7.1, which uses an older API for building annotation query editors. If you need to support earlier versions, you should still be able to use the docs for that version. 

You can build your own custom query editor for annotations, but AFAIK it depends on Angular, and you'd need to support two separate query editors (one for annotations, one for the dashboard queries). You can still use it, but be aware that Angular support is being deprecated starting in Grafana 9.0.

**Comment by Eve832** [comment]
@josmperez - is it safe to close this ticket, or are planning to do something with it?

**Comment by josmperez** [comment]
This issue pertains to Angular, which is deprecated. Closing as icebox.
