### ISSUE TITLE
Docker hub flooded with 8.5.0 tags - on each commit

### ISSUE THREAD

**Issue by AskAlexSharov** [grafana/grafana#45343]
Hi. Dozen of pages on DockerHub are flooded with: https://hub.docker.com/r/grafana/grafana/tags?page=8 
It build now on each commit. 
Hard to find real releases there. 
Probably it's just some bug in DockerHub build/tagging settings.

**Comment by zuchka** [comment]
Thanks for creating this issue, @AskAlexSharov 

the linked PR should fix this behavior. Thank you! ❤️

**Comment by dsotirakis** [comment]
Thanks @AskAlexSharov!
Images have been cleaned up as well in `grafana/grafana` and `grafana/grafana-oss` DockerHub repos!

**Comment by dsotirakis** [comment]
Thanks @AskAlexSharov!
Images have been cleaned up as well in `grafana/grafana` and `grafana/grafana-oss` DockerHub repos!
