### ISSUE TITLE
[Bug] template variable definition not-working when variable value includes lucene special character

### ISSUE THREAD

**Issue by nskalis** [grafana/grafana#4534]
* What grafana version are you using? 2.6
* What datasource are you using? Elasticsearch
* What OS are you running grafana on? Linux

When using templated variables, using the Lucene syntax, and the prior variable contains a Lucene special character, let's say `/`, the filter `terms` lookup does not because it is failing to escape the char.

Example templated variables definition:
```
$netelement	{"find": "terms", "field": "dev_name"}
$interface	{"find": "terms", "field": "iface_phy", "query":"dev_name:$netelement"}
$asn	{"find": "terms", "field": "peer_as", "query":"dev_name:$netelement AND iface_phy:$interface"}
```
Example templated variables assignment:
```
$netelement = us-nyc-01
$interface = xe-0/0/2
$asn = `not-working` unless if i remove the iface_phy:$interface
```
NOTE: it does work on a graph panel on the query section if i do
```
dev_name:$netelement AND iface_phy:"$interface"
```
so the problem is that creating templated variables is not possible, because there is no way to escape special chars, like `/`, because defining a variable with single quotes (in order to be able to `iface_phy:"$interface"`) is not working.

Nikos

**Comment by torkelo** [comment]
this should be fixed in Grafana 3.0

**Comment by nskalis** [comment]
v3 is in beta. would you be so kind please to keep this issue open in order to track it and confirm if/when gets resolved (?)

**Comment by torkelo** [comment]
@nskalis ? it is resolved, the templating system underwhen a major refactoring one month ago in order to solve this issue and similar problems.
