### ISSUE TITLE
Rename 'Create New Alert' button to 'Create New Rule' to reduce confusion

### ISSUE THREAD

**Issue by 09jvilla** [grafana/grafana#45359]
<img width="1185" alt="Screen Shot 2022-02-13 at 3 39 59 PM" src="https://user-images.githubusercontent.com/9610816/153780615-36770ab7-d1c6-44a4-b673-ee2e3c7aeef7.png">
<img width="1075" alt="Screen Shot 2022-02-13 at 3 42 00 PM" src="https://user-images.githubusercontent.com/9610816/153780616-426fd421-63ab-42a7-bfad-8602eb4f9759.png">

In Unified Alerting, the button to create a new recording or alerting rule says 'New alert rule' or 'Create alert rule' (see screenshots above). However, this same button is also used to create new recording rules. With the button named as it is today, this isn't necessarily obvious and people looking to create a recording rule may not know where to go. 

My suggestion is to modify the button to either just call it a 'new rule' or say 'new alerting and recording rule'. 

--

Some more context: 

Here's where you land after clicking:
![Image](https://user-images.githubusercontent.com/350728/166420498-ff600522-f3b7-478c-9ad7-aa57782fef5b.png)

The Mimir/Loki rule types are grayed out in this example because there are no compatible data sources.

**Comment by jtheory** [comment]
Checking with @jessover9000 -- thoughts on the best name?

Also note we'll want to update docs (and any screenshots included?) that have the old button name.

**Comment by jessover9000** [comment]
Discussing this with Rob, I propose not to omit the "alert" part on the button, as novice users in the usability tests weren't fully familiar with our concepts of "rules" vs "instances" and so "New alert" coupled together was helpful for them. Then again, "New alert and recording rule" makes the button really long. Have we had complaints from customers struggling to find this?

Maybe we could add a hover tooltip that explains "Add a new alert rule or recording rule"? Or we change it into a split button with a dropdown that also offers adding recording rules directly as a list item?

**Comment by 09jvilla** [comment]
I'm fine to backburner this. This was my observation as a user when testing out alerting but I personally haven't seen any other external folks be confused about this (DevinC might be more likely to know if this is coming up as the PM here), so I would say this is not high priority, and perhaps the change might cause more harm then good. 

I'm going to close for now and if we see external requests for this, we can always revisit.
