### ISSUE TITLE
PanelEditorQueries: default datasource trigger useless query running

### ISSUE THREAD

**Issue by MeetzhDing** [grafana/grafana#45366]
**What happened**:

In datasource developing, QueryEditor.props.onChange may cause useless query run.
This will happen when the data source is the default.

<img width="738" alt="image" src="https://user-images.githubusercontent.com/12808432/153885529-e237b03a-7d53-44c5-9f0b-a1740c93178a.png">

https://github.com/grafana/grafana/blob/095ea44e97457e1ae9b03780531928f20a25a1ca/public/app/features/dashboard/components/PanelEditor/PanelEditorQueries.tsx#L60

`newDataSourceID === null`
`panel.datasource?.uid === null?.uid === undefined`
-> dataSourceChanged is `null === undefined`

**What you expected to happen**:
stop useless query run.

**How to reproduce it (as minimally and precisely as possible)**:
create a datasource having input component, then make it as default, trigger value onChange.

**Environment**:
- Grafana version:  8.3.5
- Data source type & version: any
- OS Grafana is installed on: macos
- User OS & Browser: macos chrome latest

**Comment by torkelo** [comment]
where is the query run? it just calls panel.updateQueries

**Comment by torkelo** [comment]
ah  dataSourceChanged is evaluated to true?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/45132  

should fix this, as after that default data source should not be stored as null but the actual current default

**Comment by MeetzhDing** [comment]
> #45132
> 
> should fix this, as after that default data source should not be stored as null but the actual current default

looks great!
