### ISSUE TITLE
Histogram Panel: Values repeated on X axis, and multiple bar within a single range

### ISSUE THREAD

**Issue by rajeshroy18031994** [grafana/grafana#45365]
**What happened**:
I made a histogram visualization, using Scenario "CSV Metric Values" of  "TestData DB" data source. The bucket size is Auto.
1. Each number on the X axis is repeated multiple times.
2. For each value range on the X axis, bars are repeated multiple times(e.g. within the range 146 to 147, we have 6 bars)

![Screenshot (42)](https://user-images.githubusercontent.com/55080055/153855679-ebcc39d8-75d0-4eec-a8ba-6950d3fe8200.png)

**What you expected to happen**:
1. Each number on the X axis occurring only once
2. For each value range on the X axis a single bar(e.g. within the range 146 to 147, single bar is expected)

**How to reproduce it (as minimally and precisely as possible)**:
Use the below mentioned data set in "String Input" option
145.3 , 145.4 , 147.7 , 145.7 , 145.7 , 146.4 , 146.4 , 146.6 , 146.1 , 145.5 , 146 , 145.6 , 146.1 , 145.2 , 146.6 , 146.5 , 145.3 , 146.1 , 145.6 , 145 , 147 , 145.7 , 146.8 , 145.3 , 144.8 , 146.2 , 145.4 , 145.9 , 147 , 146.2 , 146.7 , 145.6 , 145.2 , 146.7 , 146 , 145.8 , 146.5 , 146.2 , 146.8 , 145.8 , 146.1 , 145.9 , 147 , 145 , 145.8 , 145.8 , 146.2 , 145.1 , 146 , 146.1 , 146.3 , 146.1 , 145.9 , 145.4 , 146.5 , 146.5 , 145.9 , 146.1 , 146.1 , 146.7 , 146.3 , 145.8 , 146.5 , 145.6 , 145.6 , 146.2 , 146.7 , 145.4 , 145.4 , 146.7 , 147.4 , 145.4 , 146.8 , 145.8 , 145.5 , 145.3 , 145.3 , 146.8 , 145.8 , 146.6 , 146 , 145.8 , 144.7 , 145.4 , 146.2 , 146.3 , 146.4 , 144.7 , 146.5 , 145.1 , 145.9 , 145.5 , 145 , 146.6 , 146.8 , 146 , 146.1 , 143.6 , 146.2 , 145.5 , 145.8 , 147.2 , 146.7 , 145.9 , 145.2 , 146.5 , 146.4 , 145.3 , 146.1 , 145.4 , 146.3 , 146.2 , 145.9 , 146.9 , 145.4 , 145 , 145.9 , 147.3 , 146.6 , 146.9 , 146.4 , 145.8 , 146.6 , 146 , 145.7 , 146.1 , 144.8 , 146.5 , 145.1 , 146.8 , 145.7 , 146.1 , 146.4 , 145.6 , 145.2 , 146.5 , 146.7 , 147.8 , 145.5 , 145.9 , 145.3 , 145.6 , 145.1 , 145.9

**Anything else we need to know?**:
This behavior also happened for integer values.

**Environment**:
- Grafana version: 8.2.3
- User OS & Browser: Chrome browser
- Grafana plugins: Histogram

**Comment by zuchka** [comment]
Thanks for creating this issue, @rajeshroy18031994 

reproduced here: 
https://play.grafana.org/d/pPYafxBnz/45365?orgId=1

having trouble adding decimal precision to the buckets / x-axis 🤷

**Comment by mdvictor** [comment]
For a set of int values this could not be reproduced in the latest Grafana version. The bug is still reproducible for the given set of floats. I am looking into it.

I have tested with these ints:
```
145 , 145 , 147 , 145 , 145 , 146 , 146 , 146 , 146 , 145 , 146 , 145 , 146 , 145 , 146 , 146 , 145 , 146 , 145 , 145 , 147 , 145 , 146 , 145 , 144 , 146 , 145 , 145 , 147 , 146 , 146 , 145 , 145 , 146 , 146 , 145 , 146 , 146 , 146 , 145 , 146 , 145 , 147 , 145 , 145 , 145 , 146 , 145 , 146 , 146 , 146 , 146 , 145 , 145 , 146 , 146 , 145 , 146 , 146 , 146 , 146 , 145 , 146 , 145 , 145 , 146 , 146 , 145 , 145 , 146 , 147 , 145 , 146 , 145 , 145 , 145 , 145 , 146 , 145 , 146 , 146 , 145 , 144 , 145 , 146 , 146 , 146 , 144 , 146 , 145 , 145 , 145 , 145 , 146 , 146 , 146 , 146 , 143 , 146 , 145 , 145 , 147 , 146 , 145 , 145 , 146 , 146 , 145 , 146 , 145 , 146 , 146 , 145 , 146 , 145 , 145 , 145 , 147 , 146 , 146 , 146 , 145 , 146 , 146 , 145 , 146 , 144 , 146 , 145 , 146 , 145 , 146 , 146 , 145 , 145 , 146 , 146 , 147 , 145 , 145 , 145 , 145 , 145 , 145
```
