### ISSUE TITLE
soft link from /usr/local/grafana to /var/lib/grafana caused migration failure "attempt to write a readonly database" while upgrading grafana v8.3.5

### ISSUE THREAD

**Issue by driverCYZ** [grafana/grafana#45377]
**What happened**:
when i was updating grafana v8.1.5 to v8.3.5 (the original version is v6.7.1), errors occurred as the following logs:
grafana-server[32284]: t=2021-12-08T14:29:35+0800 lvl=info msg="Starting DB migrations" logger=migrator
grafana-server[32284]: t=2021-12-08T14:29:35+0800 lvl=info msg="Executing migration" logger=migrator id="Add is_service_account column to user"
grafana-server[32284]: t=2021-12-08T14:29:35+0800 **lvl=eror msg="Executing migration failed" logger=migrator id="Add is_service_account column to user" error="attempt to write a readonly database"**
grafana-server[32284]: t=2021-12-08T14:29:35+0800 lvl=eror msg="Exec failed" logger=migrator error="attempt to write a readonly database" sql="alter table user ADD COLUMN is_service_account INTEGER NOT NULL DEFAULT 0 "
grafana-server[32284]: Failed to start grafana. error: migration failed (id = Add is_service_account column to user): attempt to write a readonly database
grafana-server[32284]: migration failed (id = Add is_service_account column to user): attempt to write a readonly database
grafana-server.service: Main process exited, code=exited, status=1/FAILURE
Failed to start Grafana instance.

All the related folders and the grafana.db's mod has been changed to  777, own is grafana:grafana

After serveral times of attempts , we found that the failure maybe related to the soft link from  /usr/local/grafana to /var/lib/grafana
Before we installed the original version v6.7.1，we created a soft link as below:
> **ln -s /usr/local/grafana /var/lib/grafana**
**Both the original installation and v8.1.5 upgrade succeed before.**
**But the upgrade of v8.3.5 failed...**
  
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:v8.1.5 to v8.3.5
- Data source type & version:sqlite3
- OS Grafana is installed on:suse linux 12
- User OS & Browser:chrome
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @driverCYZ 

can you share the exact command sequence that you used to upgrade? did you use a package manager like RPM? did you download a standalone binary? is docker in use?

Just trying to find the fastest and most accurate way to try and replicate this 👍

**Comment by driverCYZ** [comment]
> Thanks for creating this issue, @driverCYZ
> 
> can you share the exact command sequence that you used to upgrade? did you use a package manager like RPM? did you download a standalone binary? is docker in use?
> 
> Just trying to find the fastest and most accurate way to try and replicate this 👍

Thanks，we finally figured it out that the service-file of grafana caused the miguration failure ! 
In file /usr/lib/systemd/system/grafana-server.service, "ProtectSystem=full" makes the running grafana process has no permission to write into /usr or other protected system FS. But it didn't happen during the upgrade from v6.7 to v8.1.5...
After we delete  "ProtectSystem=full" from the config file in latest RPM and rebuild the RPM, the upgrade succeed.

**Comment by papagian** [comment]
@grafana/grafana-release-eng may have more context on how `ProtectSystem=full` affects the service behaviour.

**Comment by tleopold** [comment]
Release Engineering have nothing to add to this issue as this behaviour is not managed by us.  It looks like this issue has been resolved?

**Comment by zuchka** [comment]
closing for now. OP can add to thread if this needs reopening 👍
