### ISSUE TITLE
Duplicate Sum lines per fields with non alpha numeric characters

### ISSUE THREAD

**Issue by dod83** [grafana/grafana#4537]
Hi,

I'm running Grafana v2.6.0 on my local Windows 7 laptop reading reading data from ES 1.7
The table I created sums up application latency (seconds) per user:

Create Table -> 
   Query A:
     Metric - Sum - latency
     Group By - Terms - user

When I look at the table I  see duplicate lines per users with non alpha numeric characters in their names, for example for the following 4 users: 
abc$123 
xyz-098-vvv
ufo_111
utest

I get 7 sum lines:

abc -              100
123 -             100
ufo_111 -      70 
utest -           60
xyz -              50
098 -             50
vvv -              50

Of course the expected result is 4 sum lines per each user:

abc$123 -       100
ufo_111 -        70
utest -             60
xyz-098-vvv -  50      

so for names with '-' or '$' and maybe others I get duplicate sum but for names with '_' or without any special chars I get the correct result in a single line. Any ideas whats happening?

Thanks,
Dudu.

**Comment by torkelo** [comment]
This is an issue with you elasticsearch index mapping, if you want terms query to split on the whole term you need to change you ES index to not analyze the user field

**Comment by dod83** [comment]
Thanks! 
So that means I need to reindex my whole elastic index (~60GB) and reset the user field to not analyzed? 
In kibana I can see that it first shows me the same as in grafana but then somehow refreshes and normalizes all counts to one filed.
Is there any way I can workaround this in grafan or re indexing the elastic is the only way?

Regards,
Dudu.
