### ISSUE TITLE
[Bug] InfluxDB: Manually query editor doesn't update query builder

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#4538]
Grafana Version 3.0.0-beta1 (commit: v3.0-beta1+2-gdecede3)
InfluxDB version 0.10.3
RH 6.4

Hi,
I was trying to learn a bit more about influxDB, so playing with the query generator model on dashboards:

When you edit something on manually and changes to query builder (by the pencil icon), it updates the Graph but not the query builder. Furthermore, if you go manually again, it appears again as the initial query. As an example that you can reproduce:

0. The initial query, get from  [Here]( http://play.grafana.org/dashboard/db/influxdb-templated-queries?panelId=1&fullscreen&edit) is:
`SELECT mean("value") FROM "logins.count" WHERE "hostname" =~ /$Hostname$/ AND $timeFilter GROUP BY time($interval), "hostname"`
1. Manually, `WHERE "hostname" =~ /$Hostname$/ to WHERE "test" =~ /$Test$/`
2. Click pencil, the Dashboards refresh OK, but it doesn't refresh the all query editor, so it keeps appearing:
![graf1](https://cloud.githubusercontent.com/assets/13196237/14234507/89a1b84c-f9e4-11e5-8515-9a3cb2f5f49b.jpg)
3. If you cick the pencil again, it appears as the query editor, with incorrect query:
`SELECT mean("value") FROM "logins.count" WHERE "hostname" =~ /$Hostname$/ AND $timeFilter GROUP BY time($interval), "hostname"`

**Comment by torkelo** [comment]
Yes, this is by design, there is no parser for InfluxDB that can translate from the text query to the editor model. When you switch to raw text mode and make changes in the text box those changes will be discarded if you later want to try to use the query editor. You have to decide which one of those you want to use (the query editor or the text field)

**Comment by sbengo** [comment]
Oh, sorry then Torkelo,

Thanks for the info!
