### ISSUE TITLE
Issue when exporting dashboard via api only 1000 uid returned

### ISSUE THREAD

**Issue by Neurozone** [grafana/grafana#45385]
Hello.
I have the following script to export / import dashboards from grafana:
-----
echo -e "\033[1;32m- Fetching all dashboards UIDs from the \033[1;31mfolderID: $SOURCE_FOLDER_ID\033[m \033[1;32mand save output into the file named\033[m \033[1;208mdashboards_uids.txt\033[m"
curl -s -H "Authorization: Bearer $PROD_API_KEY" "https://***/api/search?folderIds=$SOURCE_FOLDER_ID&query=&starred=false" | jq -r '.[].uid' > dashboards_uids.txt

input="dashboards_uids.txt"

echo -e "\033[1;32m- Looping for each dashboard UID for import/export operation \033[m"
while IFS= read -r line
do
----

But that line is returning only 1000 uids:
curl -s -H "Authorization: Bearer $API_KEY" "https://***/api/search?folderIds=$SOURCE_FOLDER_ID&query=&starred=false" | jq -r '.[].uid' > dashboards_uids.txt

Is it normal ?

**Comment by zuchka** [comment]
can you link to the documentation page where you read the note about the 5000 results upper limit?

**Comment by zuchka** [comment]
guessing it was this?

https://grafana.com/docs/grafana/latest/http_api/folder_dashboard_search/#search-folders-and-dashboards

**Comment by Neurozone** [comment]
yes sorry
