### ISSUE TITLE
[Question] Influxdb: format of templated vars on autocomplete query builder

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#4539]
Grafana Version 3.0.0-beta1 (commit: v3.0-beta1+2-gdecede3)
InfluxDB version 0.10.3
RH 6.4

On the query builder, when you click for the autocomplete, the format to select the templating vars appears as: `/$templatevar$/`, that makes me wonder some questions:

1. If you don't put the $/ ... $/ on the Where clause, it seems that doesn't split on pipe format.
2. On the fields of the query builder: "field" and "group by -> tag", it's doesn't working the format $/.../$, it seems that those fields must load they template vars as $templatevar

Thanks for all,

**Comment by torkelo** [comment]
1) True InfluxDB needs regex syntax to support multi value filter
2) The group by clause in InfluxDB does not support regex
