### ISSUE TITLE
Unified Alerting: Internal alertmanager missing

### ISSUE THREAD

**Issue by devminded** [grafana/grafana#45412]
**What happened**:
Trying to configure alert groups. According to documentation there should be a dropdown where the built in alert managers named "Grafana" should be. There is none.

**What you expected to happen**:
To be able to select the built in alert manager.

**How to reproduce it (as minimally and precisely as possible)**:
Enabled unified_alerting and disable legacy alerting in grafana.ini. Restart. Follow documentation - become confused.

**Anything else we need to know?**:
Have I misunderstood everything?

![Konfuuuuzed](https://user-images.githubusercontent.com/10235454/154112076-9d258030-61bb-4ba4-823b-2572a30c14c8.png)
![contact](https://user-images.githubusercontent.com/10235454/154116510-b9b81dd4-a135-4f91-8730-56361130603d.png)
![rules](https://user-images.githubusercontent.com/10235454/154116750-c1b11b03-e49a-4967-901c-a52dae9eec65.png)

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: Prometheus 2.33+
- OS Grafana is installed on: Ubuntu 20.04 x64 HWE
- User OS & Browser: Chrome Windows x64 98.0.4758.82
- Grafana plugins: None
- Others:

Logs:
```
t=2022-02-15T20:25:21+0000 lvl=info msg="Path Home" logger=settings path=/usr/share/grafana
t=2022-02-15T20:25:21+0000 lvl=info msg="Path Data" logger=settings path=/var/lib/grafana
t=2022-02-15T20:25:21+0000 lvl=info msg="Path Logs" logger=settings path=/var/log/grafana
t=2022-02-15T20:25:21+0000 lvl=info msg="Path Plugins" logger=settings path=/var/lib/grafana/plugins
t=2022-02-15T20:25:21+0000 lvl=info msg="Path Provisioning" logger=settings path=/etc/grafana/provisioning
t=2022-02-15T20:25:21+0000 lvl=info msg="App mode production" logger=settings
t=2022-02-15T20:25:21+0000 lvl=info msg="Connecting to DB" logger=sqlstore dbtype=sqlite3
t=2022-02-15T20:25:21+0000 lvl=warn msg="SQLite database file has broader permissions than it should" logger=sqlstore path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
t=2022-02-15T20:25:21+0000 lvl=info msg="Starting DB migrations" logger=migrator
t=2022-02-15T20:25:21+0000 lvl=info msg="migrations completed" logger=migrator performed=0 skipped=377 duration=5.224095ms
t=2022-02-15T20:25:21+0000 lvl=info msg="Initialising plugins" logger=plugin.manager
t=2022-02-15T20:25:21+0000 lvl=info msg="Plugin registered" logger=plugin.manager pluginId=input
t=2022-02-15T20:25:21+0000 lvl=info msg="Plugin registered" logger=plugin.manager pluginId=grafana-piechart-panel
t=2022-02-15T20:25:21+0000 lvl=info msg="Plugin registered" logger=plugin.manager pluginId=grafana-worldmap-panel
t=2022-02-15T20:25:21+0000 lvl=info msg="Live Push Gateway initialization" logger=live.push_http
t=2022-02-15T20:25:21+0000 lvl=info msg="HTTP Server Listen" logger=http.server address=[::]:3000 protocol=http subUrl=/grafana socket=
t=2022-02-15T20:25:21+0000 lvl=info msg="warming cache for startup" logger=ngalert
t=2022-02-15T20:25:21+0000 lvl=info msg="starting MultiOrg Alertmanager" logger=ngalert.multiorg.alertmanager
t=2022-02-15T20:25:23+0000 lvl=info msg="Request Completed" logger=context userId=21 orgId=1 uname=daniel.sandberg method=GET path=/api/live/ws status=0 remote_addr=10.10.250.64 time_ms=7 size=0 referer=
t=2022-02-15T20:26:12+0000 lvl=eror msg="unexpected content type from upstream. expected YAML, got text/html; charset=utf-8" logger=context userId=21 orgId=1 uname=daniel.sandberg error="unexpected content type from upstream. expected YAML, got text/html; charset=utf-8" remote_addr=10.10.250.64
```

**UPDATE**
By enabling "alpha plugins" and adding a dummy alertmanager I can now see the both the dummy and the built in Grafana alert manager. I can still not do any grouping or filtering or anything - "No options found".

**Comment by zuchka** [comment]
Thanks for creating this issue, @devminded 

do either of these recent issues sound related to you?

https://github.com/grafana/grafana/issues/41517
https://github.com/grafana/grafana/issues/41483

thx

**Comment by devminded** [comment]
Maybe. I had the Ruler error in the UI before it was patched. But the way it was patched kind of disturbs be since the YAML/TEXT error is still there in the log. And with all the other issues we have with NGalerts right now it feels like it could be a related issue.

It might just be me that does not understand how the internal alert manager is supposed to work with regards to groups. I suspect groups can only be handled with Cortex at this time(?).

**Comment by armandgrillet** [comment]
This is fixed in Grafana 9, you only have the option to choose an Alertmanager if multiple are set up though.
