### ISSUE TITLE
[Bug] Grafana datasource edtior interface slow to load/respond

### ISSUE THREAD

**Issue by jmgilman** [grafana/grafana#4541]
* What grafana version are you using? 3.0.0-beta1 (latest git source)
* What datasource are you using? InfluxDB 0.11
* What OS are you running grafana on? Arch Linux x64

The datasource editor is unusually slow to respond. Some requests take anywhere from 20-40 seconds to respond while others simply never respond. 

Here's a screenshot from trying to edit a datasource:
<img width="1440" alt="screen shot 2016-04-03 at 5 27 42 pm" src="https://cloud.githubusercontent.com/assets/2308444/14235965/be3893be-f9c1-11e5-82a5-abd71fb07017.png">

Here's a screenshot of trying to test the connection and it never responded. Screenshot was taken 2 minutes after sending the request.

<img width="1438" alt="screen shot 2016-04-03 at 5 28 59 pm" src="https://cloud.githubusercontent.com/assets/2308444/14235976/fbce8b5c-f9c1-11e5-87cc-6eefb301c700.png">

Besides these screens, everything else seems to be running smooth, and I've noticed practically no latency between the dashboard and the datasource. This issue seems to reside solely with the web server and the datasource editor.

FYI, I'm on a local LAN connection with the machine running the server and have tried the machine in both a KVM Arch installation and an LXC Arch installation just to make sure it wasn't something underlying.

**Comment by torkelo** [comment]
Please build using go 1.5, there is an issue with go 1.6 and the db lib grafana use
