### ISSUE TITLE
[Bug] Cannot change password in latest version

### ISSUE THREAD

**Issue by jmgilman** [grafana/grafana#4542]
* What grafana version are you using? 3.0.0-beta1
* What datasource are you using? InfluxDB 0.11
* What OS are you running grafana on? Arch Linux x64

Looks like the change password button is attempting to load the following partial:

/public/app/features/org/partials/password.html

However, that doesn't exist. I double-checked the src directory of the build and verified it's not there either. What I have found though is this:

/public/app/features/org/partials/change_password.html

When I navigate to that I get what seems like the correct change password form.

**Comment by torkelo** [comment]
@bergquist dammit, missed that you

**Comment by torkelo** [comment]
had assigned yourself to this

**Comment by bergquist** [comment]
@torkelo doh! double work. I was just about to push
