### ISSUE TITLE
tooltip display is flakey

### ISSUE THREAD

**Issue by belm0** [grafana/grafana#45433]
**What happened**:
Sometimes tooltip does not display (unexpectedly behaves as Hidden).

**What you expected to happen**:
Display honors tooltip mode setting.

**How to reproduce it (as minimally and precisely as possible)**:
1. https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&viewPanel=230&editPanel=230
2. hover over series -> tooltip is shown
3. change tooltip mode to Hidden, hover again -> tooltip is hidden
4. change tooltip mode back to Single, hover again -> **tooltip is still hidden**

**Anything else we need to know?**:
I've also observed lack of tooltip display on non-edit mode, even though tooltip is enabled.  Seems to be an 8.4 regression.

**Environment**:
- Grafana version: 8.4.0-beta1
- User OS & Browser: macOS / Chrome

**Comment by ryantxu** [comment]
@leeoniya -- looks like tooltip changes should be added to the `propsToDiff`?

**Comment by leeoniya** [comment]
`propsToDiff` is half of it. the other half is actually drilling down `options.tooltip` just to diff it internally, which is ++uncool.

i'm gonna try to rework the flow so we can rely on a panel-level `useMemo` which outputs a random `vizConfigRev` string and uses `propsToDiff` as its invalidation array.

**Comment by belm0** [comment]
This is a very visible problem, and disincentive for migrating / using the new "Time series" visualization.   Every panel we have using new Time series does not correctly show hover.

Please...
