### ISSUE TITLE
`email_attribute_name` and alike are shown for all OAuth providers in settings

### ISSUE THREAD

**Issue by pallxk** [grafana/grafana#45446]
**What happened**:

`email_attribute_name`, `email_attribute_path`, `groups_attribute_path`, `team_ids_attribute_path`, `teams_url`, `tls_client_cert`, `tls_client_key`, `tls_client_ca`, `tls_skip_verify_insecure` and `use_pkce` are shown for all OAuth provider sections in settings page, yet they seem to be specific to `auth.generic_oauth` only, which makes me confusing about available configuration fields for each auth provider.

Likewise, `role_attribute_path` and `role_attribute_strict` seem to be only valid for `auth.generic_oauth`, `auth.gitlab` and `auth.okta`, yet they are shown for `auth.github`, `auth.google`, etc.

**What you expected to happen**:

`auth.*` sections show only meaningful fields for respective providers.

**How to reproduce it (as minimally and precisely as possible)**:

Go to `grafana.example/admin/settings`.

(A side suggestion here is to add an id to each settings section/field on the webpage for easier reference and navigation.)

**Anything else we need to know?**:

**Environment**:
- Grafana version: `8.4.0-beta1`
- Data source type & version: N/A
- OS Grafana is installed on: docker
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kminehart** [comment]
I think that makes sense, the OAuth options could use some more consistency and documentation.

**Comment by mgyongyosi** [comment]
@vtorosyan Do you know who does own this part?

**Comment by Jguer** [comment]
Verified in Grafana 10.2 

Options present are actually part of each provider. `email_attribute_name` is only present for Generic OAuth
