### ISSUE TITLE
React panel plugin - props do not get updated when template variable changes

### ISSUE THREAD

**Issue by CurlyDev1** [grafana/grafana#45469]
Hi,

I have created a custom panel plugin in react and through the use of componentDidUpdate I can detect when there is a change in the time range options, but when you change a template variable nothing is triggered.

I'm not if this is a bug or I'm using the wrong method to detect changes,

The Grafana version I'm testing with is 8.3.2

**Comment by CurlyDev1** [comment]
I've resolved this by using the eventBus that is passed down to the panel props, you can then subscribe to refresh events.

**Comment by torkelo** [comment]
@CurlyDev1 the panel should re-render if there is a change in the template variables.
