### ISSUE TITLE
snapshot shows empty and 'No Title'

### ISSUE THREAD

**Issue by dataselfservice** [grafana/grafana#45468]
**What happened**:
Snapshots not working, returning empty white/black page and "No Title". 
![image](https://user-images.githubusercontent.com/76566850/154276174-6e186df6-2a6b-4fe2-b61e-3cbec05919ef.png)

**What you expected to happen**:
Show a snapshot content (as usual)

**How to reproduce it (as minimally and precisely as possible)**:
Generate a snapshot. Click on `View`. 

**Anything else we need to know?**:
This was noticed after turning to v8.3.6 and adding `proxy_set_header Host $http_host;` to nginx

**Environment**:
- Grafana version: 8.3.6
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Any Linux, iOS; Chrome, Safari
- Grafana plugins: NA
- Others: NA

**Comment by torkelo** [comment]
Can you show the browser console output? What panel/ dashboard did you snapshot ? (what panel types?) ?

**Comment by dataselfservice** [comment]
> Can you show the browser console output? What panel/ dashboard did you snapshot ? (what panel types?) ?

Hi,

here is the log (<GRAFANA_URL> is redacted):
[1645112199844.log](https://github.com/grafana/grafana/files/8089964/1645112199844.log)

It happens e.g. with random datasource; also InfluxDB or SQL. 

A `Time Series` panel is an example: 
![image](https://user-images.githubusercontent.com/76566850/154516513-81d88dcd-6a47-4329-8e72-ab8d415b4f0a.png)

**Comment by dataselfservice** [comment]
it got solved with #8.4.1
