### ISSUE TITLE
Email address for ad users is samaccountname

### ISSUE THREAD

**Issue by willemdh** [grafana/grafana#4547]
Hello
Server: CentOS 7.2.1511
Grafana: 3.0.0-beta11459429091
Datasource: InfluxDB 0.11.1

Just managed to configure LDAP integration for my Grafana server. But I noticed that AD users logging in have not the email address in the email filed, but the sAMAccountName. How can I make sure Grafana sets the correct email address set in AD?

![image](https://cloud.githubusercontent.com/assets/6462991/14246512/ee9c527e-fa67-11e5-9544-3716b4e43f13.png)

/etc/grafana/ldap.toml
```
# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
#username = "cn"
username = "sAMAccountName"
member_of = "memberOf"
email =  "email"
```

**Comment by willemdh** [comment]
Found the issue:

LDAP attribute for mail is "mail", not "email":

email =  "mail"

Shouldn't this be updated as default?

**Comment by torkelo** [comment]
email attribute is very different for different ldap systems, mail attribute is pretty standard for OpenLDAP systems
