### ISSUE TITLE
Value mappings not working as expected in bar gauge and bar graph

### ISSUE THREAD

**Issue by docolli** [grafana/grafana#45474]
**What happened**:
The result of my SQL query is a table with two colomns named metric and value:
![grafik](https://user-images.githubusercontent.com/78646938/154281641-222f89be-3e14-4928-b377-710c6dc0f432.png)

I am using bar gauge to visualize these values as bar graph.
![grafik](https://user-images.githubusercontent.com/78646938/154282070-7acfc3e6-26b6-443a-ba23-8214226498f1.png)

Now I want to colorize the bars depending on the metric values, so all negative metrics are blue, metrics between 7 and 29 are yellow and metrics from 30 and above are red.
If I use threshold settings, for example 10, I get the following, a colorization according to the value. This is as expected, but not what I want.
![grafik](https://user-images.githubusercontent.com/78646938/154282888-447c1d5e-358d-47ec-b6c8-14800d2f4a5d.png)

So I tried to use the value mappings to get my needed result.
![grafik](https://user-images.githubusercontent.com/78646938/154283192-6fc3e2fd-4069-46ed-91be-5efe2edf669f.png)
One for the value=6, where I use "six" and "blue" to track what happens at what place.
The second one a simple Regex [7] that matches the "7" and I use "seven" and "yellow" to track.
Here what happens:
![grafik](https://user-images.githubusercontent.com/78646938/154283504-39477bae-124b-4f86-bbf0-93263a79b540.png)

1) for value=6 the bar color changed to blue (OK), the "6" above the bar changed to "six" (OK). However, also the metric text "6" changed to "six" (unexpected).
2) for Regex [7], I have a match for the metric text "7", this one changed to "seven" (OK), however, the bar color did not change (unexpected).

With Grafana 7.x.x I had used the following Overrides with Regex to colorize my bar gauge (here for negative values).
![grafik](https://user-images.githubusercontent.com/78646938/154285410-56cb9fe5-6f80-4d3d-aa46-a864080f7caf.png)

However, this does not work any more, when the bar gauge has been migrated as suggested in upgrade manual:
_For any existing panels/visualizations using a Time series query, where the time column is only needed for filtering the time range, for example, using the bar gauge or pie chart panel, we recommend that you use a Table query instead and exclude the time column as a field in the response._ 

If I don't change from time series to table, my bar gauge is not sorted correctly any more, however colorization works.
![grafik](https://user-images.githubusercontent.com/78646938/154286160-bf064c55-a9c1-412f-92bd-e4d81517ff53.png)

**What you expected to happen**:

I expect, that the Regex matches the bar metric and changes the bar properties (text, color).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.6
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows / Firefox 97.0
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Why not add multiple thresholds for your desired ranges? 

See the thresholds, the base is blue (negative infinity), next is 0 as green, so between 0 and 7 will be green, between 7 and 29 will be orange, and 29 and above will be red 

![Screenshot from 2022-02-16 21-19-42](https://user-images.githubusercontent.com/10999/154350274-a2fabe57-56d7-42c0-99c6-fc4a843bef65.png)

**Comment by docolli** [comment]
Hi @torkelo ,

thanks for this quick answer, but have you seen, that I want to have coloring based on the **metric**, not on the value?
If your sample data had sda1 to sda9 as metric, I want to have sda1 and sda2 green and sda8 and sda9 red, for example.

How can I get this result?

**Comment by torkelo** [comment]
Thresholds and value mappings only color values. If you want to color  by series or field (column) name you have to create one override rule per field and set a single color (per override rule)

**Comment by torkelo** [comment]
The color scheme option have a single color option

**Comment by torkelo** [comment]
But not sure gauge will use the field color, might only use the value color. You you could set threshold in each override rule (one per metric) and just remove all tbreshold and set the base color to the color you want

**Comment by docolli** [comment]
I was using this way to set override rules per field name (Regex) and single color successfully on Grafana 7.x.x, however after upgrading to 8.x.x the sorting of my metric(field) was no longer correct:
![grafik](https://user-images.githubusercontent.com/78646938/154480519-0be4c53f-c2cf-4c98-9158-e12d442cb58a.png)
![grafik](https://user-images.githubusercontent.com/78646938/154481075-4559fddd-2eaa-4b0b-8bf5-60e945801e4f.png)

You see that fields are now sorted like "-8,-39,0,1,11,12,2,20,21,...", before it was "-39,-8,0,1,2,11,12,20,21,...". So I though I need to follow the upgrade recommendation to now use a Table query and no longer the Time series, where I have set  "now() as time" to get a pseudo Time series.

Well, if you know how I can get the correct ordering of metric/field values again, I am also fine with using a Time series query. With this I get the coloring, that I want.

**Comment by torkelo** [comment]
Grafana does no sorting, it's what ever order your query returns

**Comment by torkelo** [comment]
you can re-order fields in the "organize fields" transform

**Comment by docolli** [comment]
Well, if Iperform the mySQL query I get the following:

---
| time | metric | value | 
| --- | --- | ---: | 
| 2022-02-17 16:26:59 | -38 | 1 | 
| 2022-02-17 16:26:59 | -21 | 2 | 
| 2022-02-17 16:26:59 | -20 | 2 | 
| 2022-02-17 16:26:59 | -14 | 4 | 
| 2022-02-17 16:26:59 | -13 | 2 | 
| 2022-02-17 16:26:59 | -7 | 20 | 
| 2022-02-17 16:26:59 | -6 | 6 | 
| 2022-02-17 16:26:59 | 0 | 20 | 
| 2022-02-17 16:26:59 | 1 | 7 | 
| 2022-02-17 16:26:59 | 2 | 1 | 
| 2022-02-17 16:26:59 | 6 | 1 | 
| 2022-02-17 16:26:59 | 7 | 2 | 
| 2022-02-17 16:26:59 | 8 | 2 | 
| 2022-02-17 16:26:59 | 14 | 1 | 
| 2022-02-17 16:26:59 | 15 | 2 | 
| 2022-02-17 16:26:59 | 16 | 1 | 
| 2022-02-17 16:26:59 | 36 | 1 | 
| 2022-02-17 16:26:59 | 43 | 2 | 
| 2022-02-17 16:26:59 | 50 | 3 | 
| 2022-02-17 16:26:59 | 57 | 3 | 
| 2022-02-17 16:26:59 | 64 | 3 | 
| 2022-02-17 16:26:59 | 71 | 1 | 
| 2022-02-17 16:26:59 | 78 | 1 | 

Grafana shows me this when I activate table view:

![grafik](https://user-images.githubusercontent.com/78646938/154514841-4336790a-34d1-4c15-9261-fc01f7b8f3ee.png)
Not the ordering from my query result.

**Comment by docolli** [comment]
FYI: I am showing the count of goods receipts against the delay in days in relation to the confirmed delivery date. Therefore the field values are changing from query to query for each supplier, we have.

In the organize fields transform I can only reorder, when the field names are constant and not changing, I think.

**Comment by docolli** [comment]
![grafik](https://user-images.githubusercontent.com/78646938/154519175-451afab8-7129-49d9-8563-b2d1658e5c75.png)
A different Threshold base color in an override rule has also no effect.

Howver, the same regex did work in my old bar graph colorization! So I don't think the regular expression is wrong.

**Comment by docolli** [comment]
OK, I try... Table format in query:
![grafik](https://user-images.githubusercontent.com/78646938/154537354-0698b957-45fb-415a-84e9-3a1e62d879f4.png)

Bar gauge with show all values:
![grafik](https://user-images.githubusercontent.com/78646938/154537504-54461152-58f0-4615-815a-38662973f970.png)

Color scheme from thresholds:
![grafik](https://user-images.githubusercontent.com/78646938/154537659-df06a163-4598-4266-a4ee-1fde454c61a5.png)
![grafik](https://user-images.githubusercontent.com/78646938/154537776-0dd2fe6c-4016-4f92-916f-bf5c657d24b6.png)

Override with regex and thresholds:
![grafik](https://user-images.githubusercontent.com/78646938/154538138-707c4af8-247b-4ce1-9304-7074930cadbc.png)

Sorry, but no color change:
![grafik](https://user-images.githubusercontent.com/78646938/154538275-04959304-6961-47ee-ab72-8add31b74231.png)

Only if I change the regex to the general match ".*" I get ALL bar colors changed:
![grafik](https://user-images.githubusercontent.com/78646938/154538505-45841c54-77fd-4b07-b97e-d95216882ebe.png)

I tested the regex on a web service, it seems to be correct:
![grafik](https://user-images.githubusercontent.com/78646938/154539417-4d19e1e7-ca37-4671-a773-63280da3d5a6.png)

**Comment by docolli** [comment]
Additional Info: If I just switch from time series to table, I am getting the correct field order, but I loose coloring!

1) Time series:
![grafik](https://user-images.githubusercontent.com/78646938/154540795-5800d6a1-3eb0-489d-b39a-bc9121ae0c1b.png)

2) Table:
![grafik](https://user-images.githubusercontent.com/78646938/154540857-804b98cd-038e-418f-8493-b2724fa0f376.png)

Any idea?

**Comment by leeoniya** [comment]
hmm, the way thresholds behave in BarChart should be improved instead of simply looking like stacked bars. i think that would cover this use case.

currently meh:

![image](https://user-images.githubusercontent.com/43234/154541852-b319ef96-1d4a-40d3-90da-ce0b3480278d.png)

**Comment by torkelo** [comment]
@docolli when you switch to table (And all values in value options) you have to use the color by value options (thresholds, value mappings etC)

**Comment by docolli** [comment]
It is set like you suggested, or is it not?
![grafik](https://user-images.githubusercontent.com/78646938/154542968-2ab7c405-9da5-4e16-baeb-73b764faea72.png)
![grafik](https://user-images.githubusercontent.com/78646938/154543177-5e6e643b-057a-44e2-be96-b737ef80307c.png)

Isn't more likely a non-evaluation of the regex in field name, when I switch to table?

**Comment by torkelo** [comment]
@docolli ah, I forgot you want to color not by value but by the metric name (which is very unusual) 

Overrides only work on field names, and you only have a single "metric" field

**Comment by docolli** [comment]
@torkelo that was was the trick, that really solved my coloring problem. Thank you. Great support!!!
I now added some IF statements in my SQL query that generate a new colomn with the wanted color name. Using "Rows to fields" transform then colorizes my bars as it is needed for my use case.

 ```
IF (
    daysdelay < -7,
    "blue",
    IF (
      (daysdelay > 7 AND daysdelay < 30,
      "yellow",
      IF (
        daysdelay > 29,
        "red",
        "green"
  ))) 
  AS color

```
![grafik](https://user-images.githubusercontent.com/78646938/154649062-c78a065b-2eb1-4d7d-81b3-47a62a386755.png)
![grafik](https://user-images.githubusercontent.com/78646938/154649405-6af3e85e-3bb6-4dc9-ba7a-65b553afb4da.png)
