### ISSUE TITLE
[Bug] Grafana 3.0.0-beta1 template variable influxdb

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#4548]
* What grafana version are you using?: 3.0.0.-beta1
* What datasource are you using? Influxdb 0.11
* What OS are you running grafana on? centos 7

If my query has **"instance" =~ /^AS/** then i get data, but using a template varibale custome type "process" and putting it as ^AS or /^AS/ does not work when used as **"instance" =~ /$process$/** or **"instance" =~ /$process/** ,, this worked fine in 3.0.0-pre

**Comment by bergquist** [comment]
Might be due to https://github.com/grafana/grafana/issues/4405

**Comment by torkelo** [comment]
Have you tested "instance" =~ /^$process$/  ?

Whats the raw query grafana sends to InfluxDB (check chrome dev tools network tab)

**Comment by discoduck2x** [comment]
@torkelo 
_Have you tested "instance" =~ /^$process$/ ?_  that does not work,, however
**_"instance" =~ /^$process/_** does work (removing the "^" from the template variable...
obv i didnt try every possible change of syntax , and for me this wasnt really crystal clear :) 

thanks anyway @torkelo
