### ISSUE TITLE
slow rendering in firefox, especially point rendering

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4549]
using any version of grafana, rendering can be really slow (despite reasonable maxDataPoints setting). this seems to be only a problem in firefox, not with chrome. especially point rendering.
often javascript gets so busy the UI blocks for a second or two (after the datasource has sucessfully returned the data)

see this video for a demonstration https://vimeo.com/158151263
for more details see https://github.com/raintank/grafana/issues/570

**Comment by torkelo** [comment]
Seems like firefox canvas rendering is not as fast as chrome

**Comment by mlushpenko** [comment]
Same here, firefox sometimes totally hangs and offers to close grafana page

**Comment by Dieterbe** [comment]
firefox has been working on a completely new engine, which is apparently available as beta now.
https://blog.mozilla.org/blog/2017/09/26/firefox-quantum-beta-developer-edition/
i suggest to close this ticket now

**Comment by AxelG-DE** [comment]
This issue is closed but I do have exactly that problem since last half year or so. First it was merely on my PC but now also on my laptop. Both running Gentoo with more or less up to date firefox (for my PC it is 102.13.0)

Anyone has an idea, where I can find help?
