### ISSUE TITLE
Table Allignment issue in 3.0 Beta

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#4551]
Question:

Hi @torkelo,

When i created the table in 3.0 beta release, there was an alignment issue, can you please have a look at the attachment or am i doing something wrong?

This was running good in 2.6 release.

![image](https://cloud.githubusercontent.com/assets/15123322/14255343/3b924158-fab1-11e5-95d6-378bc9252a22.png)

Ex
* What grafana version are you using? 3.0 beta
* What datasource are you using? Graphite
* What OS are you running grafana on?  RHEL6.5

**Comment by torkelo** [comment]
thanks for reporting this, fixed this, as well as fix another issue (be able to see what series are on right y when legend is in table mode)

![image](https://cloud.githubusercontent.com/assets/10999/14256343/77613338-fa4d-11e5-8c8a-5d261d2c58cf.png)

**Comment by Himanshu-pupneja** [comment]
Its Awesome,

Thanks Much
