### ISSUE TITLE
AzureMonitor: "Learn more" links are redirecting to archived repo

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#45510]
**What happened**:
The links from "Learn more" are redirecting to this [archived repo](https://github.com/grafana/azure-monitor-datasource?utm_source=grafana_add_ds).

<img width="1406" alt="Screen Shot 2022-02-17 at 12 13 53" src="https://user-images.githubusercontent.com/4163034/154470251-f7a9812f-f579-4fbe-a251-e95fcd89c6a1.png">
<img width="914" alt="Screen Shot 2022-02-17 at 12 13 41" src="https://user-images.githubusercontent.com/4163034/154470256-5f83c2fb-0f40-4b30-8c5e-881942608d48.png">

**What you expected to happen**:
Comparing to other Core plugins, these "Learn more" probably have to be removed.

**Environment**:
- Grafana version: 8.5.0-pre

**Comment by yaelleC** [comment]
Fixed in #46776
