### ISSUE TITLE
Graph is not refreshing every 5 seconds on 3/29 build

### ISSUE THREAD

**Issue by pckeyan** [grafana/grafana#4552]
Hi,

I am using the latest build from 3/29; after the upgrade I noticed that the graph is not refreshing automatically. Can you please let me know if any settings I need to update?

I took 3/29 build for Cloudwatch Custom Metrics Calculation

Regards
Karthik

**Comment by torkelo** [comment]
Stange, is working here with beta1 build. Did you set auto refresh in timepicker and then hit the apply button?
