### ISSUE TITLE
Light theme colors

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#4553]
Hi, just tested the light theme on Grafana Version 3.0.0-beta1 (commit: v3.0-beta1+2-gdecede3) and that white background color is normal?
In my opinion,should be darker, as it was on 2.6. 
You can test it on http://play.grafana.org, selecting light theme.

![light](https://cloud.githubusercontent.com/assets/13196237/14258648/985a76b6-faa3-11e5-8542-4302aeb86d00.jpg)

Thanks

**Comment by torkelo** [comment]
yes, that is by design. Can be improved though.
