### ISSUE TITLE
Issue with plotting when first data frame has gaps

### ISSUE THREAD

**Issue by ml054** [grafana/grafana#45560]
**What happened**:
I’m getting following graph

![image](https://user-images.githubusercontent.com/1250431/154548413-de804e54-5e77-469d-a7f4-338dbd4f7e46.png)

when first data frame has gaps (ie. value is defined for 01.01.2021, ten for 03.01.2021)
My data frames:
First:
```
timestamp”,“Cases countries/1”
2020-03-09 01:00:00,5
2020-03-11 01:00:00,5
2020-03-12 01:00:00,9
```

Second:
```
“timestamp”,“Cases countries/2”
2020-03-09 01:00:00,5
2020-03-10 01:00:00,6
2020-03-11 01:00:00,5
2020-03-12 01:00:00,9
```

**What you expected to happen**:

Graph should sort items and then draw - sometimes second and next series are hidden in plot....

**How to reproduce it (as minimally and precisely as possible)**:
See data frames above

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: 
- OS Grafana is installed on:windows
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by ml054** [comment]
It happens here: https://github.com/ravendb/ravendb-grafana-datasource

but I assume it isn't releted to particular datasource.

**Comment by zuchka** [comment]
Thanks for creating this issue, @ml054 

I'm having trouble replicating this. Here are your two queries mocked up on our sandbox. Everything looks in order here so far, no?

https://play.grafana.org/d/AhWVxxBnz/45560?orgId=1&editPanel=2&from=1645502637567&to=1645502761726

**Comment by ml054** [comment]
ok looks like dataframe doesn't work properly when time column contains strings with ISO date, ex. 
2020-03-09T00:00:00.0000000Z

Once I converted those to datatime or unix timestamp (number) it plots correctly. 

The question is: do you want to have validation for that or support string values

**Comment by zuchka** [comment]
hmmm @grafana/user-essentials might have an opinion on this 

in the meantime, I think I will close this issue. happy to reopen as needed. Glad you got unblocked! 👍 

curious: did you convert your timestamps manually, or did you try [the `Convert field type` transformation](https://grafana.com/docs/grafana/next/panels/reference-transformation-functions/#convert-field-type)?

**Comment by ml054** [comment]
@zuchka I converted that inside plugin, see:

https://github.com/ravendb/ravendb-grafana-datasource/blob/4aade38d3d80d7e8485671027da341ce46328537/src/DataFrameUtils.ts#L239

Also I had to do little hack when I detect 'time' column:

https://github.com/ravendb/ravendb-grafana-datasource/blob/4aade38d3d80d7e8485671027da341ce46328537/src/DataFrameUtils.ts#L55

Anyway will have a look at user-essentials, thanks for help.

**Comment by ml054** [comment]
Can't find @grafana/user-essentials. @zuchka  Could you point me to right direction?

**Comment by zuchka** [comment]
ah I see, you're developing this plugin. You best avenue moving forward is to post in the plugin development channel on our public forum:

https://community.grafana.com/c/plugin-development/30
