### ISSUE TITLE
[Bug] Regression: Stacked graph doesn't stack at re-render

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#4557]
I can reproduce this on Grafana 3.0.0-pre1, as well as on http://play.grafana.org/dashboard/db/graph-styles

When command-clicking on a metric in a stacked graphs' legend (to disable it) and then later re-enable it, it renders along the bottom as if it were its own graph. Thus overlapping other metrics instead of being stacked.

<img width="1077" alt="screen shot 2016-04-05 at 02 07 36" src="https://cloud.githubusercontent.com/assets/156867/14268467/2ed90164-fad3-11e5-8f55-9d1550afce1d.png">

**Comment by torkelo** [comment]
thanks for reporting this! fixed!
