### ISSUE TITLE
Elasticsearch Variable "terms" query returns None

### ISSUE THREAD

**Issue by IamShubhamGupto** [grafana/grafana#45589]
**What happened**:
The Variable editor on Grafana is not fetching values from the field specified in elasticsearch data source.

<img width="702" alt="image" src="https://user-images.githubusercontent.com/32878682/154659540-5665fffc-2b87-4191-b63f-dac6f49d31ff.png">

**What you expected to happen**:
Return a list of unique values the field "cluster-name" holds in the data source.

**How to reproduce it (as minimally and precisely as possible)**:
Use elasticsearch as a datasource

Sample data schema:
```
{
  "cluster-name": "text",
  "type": "text",
  "timestamp": "time in milli-seconds"
  ...
}
```
**Anything else we need to know?**:
I have tried:
- restarting grafana and elasticsearch service
- checked other versions, same issue posted even on community - https://community.grafana.com/t/elasticsearch-query-variable-for-terms-does-not-work/58858
- Tried OpenSearch and OpenDistro plugins 

**Environment**:
- Grafana version: v8.3.0 (914fcedb72)
- Data source type & version: ElasticSearch V7.0+ (cluster version - 7.15.2)
- OS Grafana is installed on: ubuntu 20
- User OS & Browser: Windows 10 & Microsoft edge
- Grafana plugins: OpenSearch, OpenDistro
- Others:

**Comment by IamShubhamGupto** [comment]
@grafanabot 
Solving this is urgent
Thanks

**Comment by mellieA** [comment]
@IamShubhamGupto I tried this out and saw the same behavior, that no values are returned in the preview. I used the browser's developer tools and I can see this error on the query sent to my elasticsearch datasource: 

```
error: {root_cause: [{type: "illegal_argument_exception",…}], type: "search_phase_execution_exception",…}
caused_by: {type: "illegal_argument_exception",…}
caused_by: {type: "illegal_argument_exception",…}
reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [cluster-name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
type: "illegal_argument_exception"
```

I tried again with the keyword field and I was able to see the cluster names in the preview: 
![Screen Shot 2022-02-25 at 3 29 18 PM](https://user-images.githubusercontent.com/18175287/155811733-a81ca616-6251-40f3-9ec2-285188af8af5.png)

I'm going to look into documenting this in the variable section of our docs.

**Comment by mellieA** [comment]
Found https://github.com/grafana/grafana/issues/25483

@Elfo404 before I update the docs, can you confirm that the terms query expects a `.keyword` field? I can try to clarify a couple of other items from #25483 while I'm working on it.

**Comment by IamShubhamGupto** [comment]
> @IamShubhamGupto I tried this out and saw the same behavior, that no values are returned in the preview. I used the browser's developer tools and I can see this error on the query sent to my elasticsearch datasource:
> 
> ```
> error: {root_cause: [{type: "illegal_argument_exception",…}], type: "search_phase_execution_exception",…}
> caused_by: {type: "illegal_argument_exception",…}
> caused_by: {type: "illegal_argument_exception",…}
> reason: "Text fields are not optimised for operations that require per-document field data like aggregations and sorting, so these operations are disabled by default. Please use a keyword field instead. Alternatively, set fielddata=true on [cluster-name] in order to load field data by uninverting the inverted index. Note that this can use significant memory."
> type: "illegal_argument_exception"
> ```
> 
> I tried again with the keyword field and I was able to see the cluster names in the preview: ![Screen Shot 2022-02-25 at 3 29 18 PM](https://user-images.githubusercontent.com/18175287/155811733-a81ca616-6251-40f3-9ec2-285188af8af5.png)
> 
> I'm going to look into documenting this in the variable section of our docs.

Hey @mellieA 
Thank you for clarifying, but does that mean when I describe cluster-name in the elasticsearch schema, it is of type keyword?

like so
```
...
"cluster-name" : {
  "type" : "keyword"
}
...
```

**Comment by IamShubhamGupto** [comment]
The issue could be somewhere else, I have created a new index where "cluster-name" and other text fields are now keywords.
No change in outcome
<img width="701" alt="image" src="https://user-images.githubusercontent.com/32878682/155828152-52c3d209-4d9c-4480-ab09-117ed6e56594.png">

`{"find": "fields", "type": "keyword"}` result
<img width="698" alt="image" src="https://user-images.githubusercontent.com/32878682/155828204-39370b7f-65f0-4e57-be7b-2d43990ab7f9.png">

**Comment by IamShubhamGupto** [comment]
UPDATE: Fixed
@mellieA Thanks for your help.

The issue had two parts:

1. The text items must be stored as keyword type in the elasticsearch index schema, if they are going to be used as query variables
Segment of the schema fed to elasticsearch in order to create the index:
```
...
"cluster-name" : {
  "type" : "keyword"
}
...
```
2. The actual query to get all terms of a field is `{"find": "terms", "field": "cluster-name"}`
