### ISSUE TITLE
[Bug] possible bug, Uncaught RangeError

### ISSUE THREAD

**Issue by mtanda** [grafana/grafana#4559]
By this error, Chrome becomes unresponsive.

1. Create new dashboard
2. Add template variables by Prometheus query
3. Add graph which use template variables, (I also add a CloudWatch graph panel)
4. Save dashboard

At step 4, the Grafana doesn't response for save is slow, so I click save button two or three times.
I try to replicate this by saving dashboard, after restarting Chrome, but I can't replicate this issue.
So, I'm not sure this is bug or not.
But, if this is bug, this bug is critical.

* What grafana version are you using?
  * ```"buildInfo":{"buildstamp":1459806573,"commit":"v3.0-beta2+1-ge027770","version":"3.0.0-beta2"}```
* What datasource are you using?
  * Prometheus, CloudWatch
* What OS are you running grafana on?
  * Mac OS, Google Chrome

![uncaught_range_error](https://cloud.githubusercontent.com/assets/224552/14269573/d8f572b6-fb20-11e5-83ea-c36f4256e3f8.png)

**Comment by torkelo** [comment]
strange, some bug in cloudwatch or prometheus plugins that seem cause infinite recursion. Cant replicate it yet here.

**Comment by mtanda** [comment]
I wonder why confirm modal is shown, and I understand it now.
I upgrade from Grafana 2.6 before testing Grafana 3.0 beta2.
The "New dashboard" might be saved in ver 2.6.
When I click save button first, "version-mismatch" error is occur, then confirm modal is shown.
https://github.com/grafana/grafana/blob/e0277702135c9c2e8eeee2a1cd75ee5c7b71c391/public/app/features/dashboard/dashnav/dashnav.ts#L107-L135

To replicate this issue, need to create version mismatch error.

**Comment by mtanda** [comment]
Call "$scope.appEvent('confirm-modal')" might cause this error.
https://gist.github.com/mtanda/e0f452fc5861669b9a8d0f50890bf094

I succeed to replicate this without Prometheus/CloudWatch plugin. (The dashboard has only one graph which use dummy Grafana datasource.)

**Comment by mtanda** [comment]
The "$scope.saveDashboard()" function should block re-entrance while processing dashboard save request?

**Comment by mtanda** [comment]
@torkelo I modify code little and success to replicate.
Would you try to replicate this one in your env?

**Comment by torkelo** [comment]
I have been able to replicate it but not find the cause for recursion

**Comment by torkelo** [comment]
is this still an issue?

**Comment by mtanda** [comment]
I can't replicate this with latest Grafana.
I close this.

**Comment by bendem** [comment]
Just a heads up that I experienced this when updating to 4.3.0 and it was due to my datasource being named "default". I did not investigate further but the recursion happens here.

```js
c.default.service("datasourceSrv", ["$q", "$injector", "$rootScope", "templateSrv", function(a, c, e, f) {
    var g = this;
    this.init = function() {
        this.datasources = {}
    }
    ,
    this.get = function(b) {
        return b ? (b = f.replace(b),
        // <---- here ---->
        "default" === b ? this.get(d.defaultDatasource) : this.datasources[b] ? a.when(this.datasources[b]) : this.loadDatasource(b)) : this.get(d.defaultDatasource)
```
