### ISSUE TITLE
[Bug] Incorrect Graph Scaling

### ISSUE THREAD

**Issue by tral** [grafana/grafana#4560]
I don't know if it's grafana's or "simple-json-datasource" plugin's bug, but scaling does not work.
a) Full data, scale is OK: http://dn.imagy.me/201604/04/00a939443dd57c5ab86b3f1b2baffcad.png
b) Partial data, scale is not ok (a lot of empty space on top): http://dn.imagy.me/201604/04/b02556366d42fe1f4657a4103e8b9467.png

You can reproduce it in Grafana 3.0.0 beta1
It reproduces under Windows and Linux.
It reproduces if you use "simple-json-datasource" as datasource (other datasources is good).

Will appreciate any help!

**Comment by torkelo** [comment]
Think this might be that when your zooming in your returning data points outside the time range that still effect the min/max of of the grid

**Comment by tral** [comment]
so how can I avoid this? I'm just using the plugin, is it plugin's issue?

**Comment by torkelo** [comment]
Can you check what your returning for the network request when you zoom in? (Chrome dev tools), whats the min/max of all data points returned? The plugin is not responsible for date range filtering that must be done in the server responding with metrics

**Comment by tral** [comment]
When I zoom in i see 2 queries: 
1) POST query on proxy: http://imageshack.com/i/pmb5NFHOp
2) GET query to my backend: http://imageshack.com/i/pmHlkOVgp
And I see range parameters only in POST query, so my backend doesn't get any ranges and yes it always returns the same data.
Is it wrong settings of plugin or what can it be? You already helped a lot, thanks

**Comment by torkelo** [comment]
Your backend looks like it is returning a redirect , grafana is sending the correct time range filter

**Comment by tral** [comment]
No, it's Grafana's Proxy returns 301: http://imageshack.com/i/poqguiIbp
is that normal?

**Comment by torkelo** [comment]
it returns 301 because your backend does that :) its a proxy, everything that it returns is from your backend

**Comment by tral** [comment]
I do not agree :) I made a very simple backend:
`<?php
header('Access-Control-Allow-Origin : *');
echo '[{"target":"metric_name","datapoints":[[1,1459814881000],[1,1459814941000].....skipped.....
?>`

and Grafana works this way:
1) It sends POST on 
`http://GRAFANA_SERVER:3000/api/datasources/proxy/29/query`
and then sends GET on 
`(http://MY_BACKEND/grafana/query/)`

And even if I try inserting in browsers address line this: `http://GRAFANA_SERVER:3000/api/datasources/proxy/29/query`
Browser redirects me on 
`http://MY_BACKEND/grafana/query/`

(I thought that grafana's proxy works this way, please tell me if I'm wrong)

**Comment by torkelo** [comment]
your backend web server seems to redirect POST requests, there is no redirect code in the HTTP proxy, so the redirect is coming from your web server,

**Comment by tral** [comment]
Nope, tried in Postman - backend works fine with POST queries http://imageshack.com/i/pmS7eEuqp
To tell the truth, I don't know now what else I can do :(

**Comment by torkelo** [comment]
well it is nginx that is responding with 301, did you specify the URL for your backend correctly in datasource settings?

http://imageshack.com/i/pmb5NFHOp

**Comment by torkelo** [comment]
I dont know what else to do either, the grafana ds proxy has worked for all backends so far without any redirects :(


Have you tried direct access? (will require that your backend returns CORS headers to allow cross domain resource requests)

**Comment by tral** [comment]
I think 301 error is because of last "/"
(server redirecst "addr/subaddr" to "addr/subaddr**/**"

**Comment by tral** [comment]
Yes, it works now!
Thank you for help and answers! Good luck!
