### ISSUE TITLE
Templating doesn't work anymore 

### ISSUE THREAD

**Issue by MartinSbs** [grafana/grafana#4561]
Good morning.
I made a templating on grafana for influxdb. 
I was working with grafana 2.6 and influxdb 0.10, I upgraded grafana to 3.0 and influxdb to 0.11. It was working but I restarted my computer and the templating doesn't work anymore. You can find on the picture the configuration before and now, it's look the same but I can't get the same results. The datasource is the same just the name change. Any idea? 
![settemplating](https://cloud.githubusercontent.com/assets/17618554/14274132/cbe51786-fb0f-11e5-82d3-906b53d2c773.png)
![templating](https://cloud.githubusercontent.com/assets/17618554/14274185/14453506-fb10-11e5-99d7-fca631e1b228.png)

**Comment by torkelo** [comment]
Can you open chrome dev tools network tab and inspect the response from InfluxDB ?

**Comment by MartinSbs** [comment]
I'm using firefox on fedora, is Inspect element is the same? I don't find the influxDB answer with this.
![screenshot from 2016-04-06 09-08-28](https://cloud.githubusercontent.com/assets/17618554/14308564/384d89f4-fbd7-11e5-92c7-a016fc299032.png)

**Comment by MartinSbs** [comment]
It's not working with influx 0.11 and 0.12 but with 0.10.3-1 it's working again.

**Comment by torkelo** [comment]
Yes, they broke their api in influxdb 0.11,
