### ISSUE TITLE
grafana-cli reports success on failed plugin install

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#4562]
When installing a plugin as a non-root user other than "grafana", i.e. a user that does not have write access to the grafana plugin directory, the installation command reports success, even though nothing is installed:

1. Login as a user that is not `grafana` or `root`
2. `grafana-cli plugins install grafana-simple-json-datasource`
3. Output is `✔ Installed grafana-simple-json-datasource successfully`
4. `/var/lib/grafana/plugins` is empty

Expected:
3. Output shows a permission error (and perhaps suggests using `sudo`) 

Workaround: Use `sudo` to install plugin.
1. `sudo grafana-cli plugins install grafana-simple-json-datasource`
2. `/var/lib/grafana/plugins` contains a directory `grafana-simple-json-datasource`

(Grafana 3.0.0 pre1459399258 on Centos 7)

**Comment by bergquist** [comment]
Thank you for reporting this! 

This cli will now give an better error message informing about missing permissions.
