### ISSUE TITLE
Loki: Grafana expects prexisting test rules

### ISSUE THREAD

**Issue by ilovemysillybanana** [grafana/grafana#45629]
I went to setup loki with ruler+alert manager to use the new Grafana alert's management functionality. 

When I went to create alerts via the page in Grafana I see this notification:

```
Failed to determine if "Loki test" allows editing rules: failed to get rule group rules/<tenant-id>/dGVzdA==/dGVzdA==: storage: object doesn't exist
```

This in the console
```
{"message":"failed to get rule group rules/<tenant-id>/dGVzdA==/dGVzdA==: storage: object doesn't exist\n"}
```

Realizing that `dGVzdA==` is base64 encoded, decoding reveals that this is `test`. To get `dGVzdA==/dGVzdA==` path structure you also need to set the file name when uploading rule sets via cortextool. The file name required by this is also `test.yaml`

How to reproduce it (as minimally and precisely as possible):
Spin up grafana using Loki as a data source with no rules in your GCS bucket.

Anything else we need to know?:

This same error prevents us from saving any rules in a new namespace when we create in the UI because it will complain as well that it expects there to already be a base64 encoded file structure as noted above. Here is the error I see after having added the test file and trying to create a new rule in a new namespace:

```
{"message":"failed to get rule group rules/<tenant_id>/dGVzdDI=/dGVzdDI=: storage: object doesn't exist\n"}
```

Note that that `dGVzdDI=` is base64 encoded for `test2`.

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: Loki Ruler on GCS with 2.4.2

**Comment by gabor** [comment]
hmm. to me this seems like an alerting issue, @grafana/alerting-squad , could you please take a look?

**Comment by JohnnyQQQQ** [comment]
@ilovemysillybanana can you try the latest version of Grafana? We are aware that we had similar issues in the past.
