### ISSUE TITLE
This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

### ISSUE THREAD

**Issue by kaey** [grafana/grafana#45642]
Checking out v8.4.1 tag results in an error:
```
$ git remote -v
origin	git@github.com:grafana/grafana (fetch)
origin	git@github.com:grafana/grafana (push)
$ git fetch
remote: Enumerating objects: 242, done.
remote: Counting objects: 100% (210/210), done.
remote: Compressing objects: 100% (114/114), done.
remote: Total 242 (delta 157), reused 141 (delta 96), pack-reused 32
Receiving objects: 100% (242/242), 48.59 KiB | 5.40 MiB/s, done.
Resolving deltas: 100% (161/161), completed with 17 local objects.
From github.com:grafana/grafana
   0436f9d333..dfff9174e7  gio/feat/explore-to-dashboard -> origin/gio/feat/explore-to-dashboard
 * [new branch]            joey/influxdb_annotations     -> origin/joey/influxdb_annotations
 * [new branch]            joey/influxdb_test_datasource -> origin/joey/influxdb_test_datasource
   4dafdfc9f5..95561c787a  prom-parser                   -> origin/prom-parser
   49465edb3c..a3763a0cb6  search-page                   -> origin/search-page
$ git checkout v8.4.1
error: pathspec 'v8.4.1' did not match any file(s) known to git
```

At github page https://github.com/grafana/grafana/tree/v8.4.1 you can also see the message:

>This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository.

This was not a problem with previous releases. So how do i checkout code for v8.4.1?

**Comment by kaey** [comment]
I can checkout that tag if I do fresh `git clone`. Doesn't explain weird github message though.

**Comment by dsotirakis** [comment]
@kaey Hello! Did you try `git fetch --tags`?

**Comment by kaey** [comment]
> @kaey Hello! Did you try `git fetch --tags`?

No. `git fetch` without any flags properly fetched all tags for ~2 years up until 8.4.0.

I also replaced my repo with fresh `git clone` so I can no longer reproduce this problem locally.

**Comment by DasSkelett** [comment]
> > @kaey Hello! Did you try `git fetch --tags`?
> 
> No. `git fetch` without any flags properly fetched all tags for ~2 years up until 8.4.0.

See https://git-scm.com/docs/git-fetch#_description on why `git fetch` without `--tags` does not guarantee to fetch all tags, and why it didn't in this instance:

> By default, any tag **that points into the histories being fetched** is also fetched; the effect is to fetch tags that point at branches that you are interested in. This default behavior can be changed by using the --tags or --no-tags options or by configuring remote.<name>.tagOpt. By using a refspec that fetches tags explicitly, you can fetch tags that do not point into branches you are interested in as well.
