### ISSUE TITLE
[Feature Request] Disable link sign out and page /login when using auth.proxy or auth.basic

### ISSUE THREAD

**Issue by francispereira** [grafana/grafana#4564]
- What grafana version are you using?
  3.0.0-beta21459807175
- What datasource are you using?
  Elasticsearch
- What OS are you running grafana on?
  Debian GNU/Linux 8.1 (jessie)

When either auth.proxy or auth.basic is enabled and is the only authentication mode, disable the sign out link and access to /login. It makes no sense because authentication is managed by the fronted web server.

**Comment by kfitzpatrick** [comment]
:+1: 

@francispereira I'm not very familiar with the codebase. If you are and can point me in the right direction I can try putting a PR together.

**Comment by kfitzpatrick** [comment]
@bergquist check out what I've done in #4675

**Comment by francispereira** [comment]
@kfitzpatrick I am not familiar with the codebase :(

**Comment by marcv81** [comment]
I have not contributed to Grafana before but I would be happy to try to work on this, @torkelo could you please maybe assign to me? I have verified that I can build on my dev machine.

I think there should be a setting in the configuration file to indicate we are running behind a reverse proxy. In addition to removing the signout/login pages I propose the following additional changes.

- The users should not be able to edit their username or password in their profile.
- Same as above for admins editing user profiles.
- We might want to disable account creation altogether when auto_sign_up = true (to be discussed).
- There should be a warning in the logs in the following conditions. Basically running auth.proxy behind a reverse proxy is incompatible with all other forms of authentication.
 - auth / disable_login_form = false
 - auth / allow_sign_up = true
 - auth / github.enabled = true
 - auth.google / enabled = true
 - auth.generic_oauth / enabled = true
 - auth.grafananet / enabled = true
 - auth.ldap / enabled = true

Comments?

**Comment by pkolyvas** [comment]
We're migrating a number of Feature Requests to our [GitHub Discussion](https://github.com/grafana/grafana/discussions) board. I'm going to close this issue. Please start a discussion if it's still pertinent to your workflow(s).
