### ISSUE TITLE
Build: Change from drone build number to git commit sha in maintaining build artifacts

### ISSUE THREAD

**Issue by mckn** [grafana/grafana#45654]
**What happened**:
We are trying to align the pre-releases of the grafana npm packages (https://www.npmjs.com/package/@grafana/data) and the docker images.

We are writing an integration pipeline for plugins and to get that in place we would need to be able to get the corresponding version of the npm packages and docker hub image.

**Comment by dsotirakis** [comment]
Closing due to https://github.com/grafana/build-pipeline/pull/377
