### ISSUE TITLE
Templating/ repeat panel intégrate all/

### ISSUE THREAD

**Issue by floppy84** [grafana/grafana#4565]
Hi All,

* What grafana version are you using? ==> Grafana 3.0 beta 2
* What datasource are you using? ==> Graphite 
* What OS are you running grafana on? Centos 6

i got issue on repeat pannel.

Before upgrade grafana, panel was repeated for each value in template variable.

Now i got value All as panel in more.
I don't want it to display "All" panel like before, how i can do that .

![image](https://cloud.githubusercontent.com/assets/3499449/14279085/6f37af96-fb2b-11e5-821e-20b7ffcb853c.png)

**Comment by jessetan** [comment]
Disable "include all option" for your template variable?
![Include All option](https://cloud.githubusercontent.com/assets/3284111/14279386/3c325928-fb2d-11e5-82ea-75a8dcfc4fb0.png)

**Comment by torkelo** [comment]
go into the template variable options and update the variable  (hit update), then save and reload

**Comment by floppy84** [comment]
same issue on variable update and save and reload.

is there an issue with to repeat row option ?

![image](https://cloud.githubusercontent.com/assets/3499449/14284112/6e801faa-fb46-11e5-9f4e-692b1a1f46f2.png)

**Comment by torkelo** [comment]
Try removing the variable and create new one. Also can you show your dashboard json?

**Comment by floppy84** [comment]
Delete variable on recreate the same one with the same name don't fix it
I made the clone of production and same on a new one grafana.
I have multiple issue on repeat panel functionality.


exemple in single stat edition ::

![image](https://cloud.githubusercontent.com/assets/3499449/14309224/5e24c918-fbdb-11e5-8f33-81b63ca7e2b4.png)

on  display ::

![image](https://cloud.githubusercontent.com/assets/3499449/14309250/7e60f490-fbdb-11e5-88f0-7e4eabb605c9.png)


here is the json 

`{
  "id": 2,
  "title": "000 - HYPERION - Appli",
  "originalTitle": "000 - HYPERION - Appli",
  "tags": [],
  "style": "dark",
  "timezone": "browser",
  "editable": true,
  "hideControls": false,
  "sharedCrosshair": false,
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 6,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": "S06HYPERIONP",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP1",
              "value": "S06-HYPERIONP1"
            }
          },
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Cpu.Avg_CPU_Utilisation"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg"
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 7,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP2",
              "value": "S06-HYPERIONP2"
            }
          },
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Cpu.Avg_CPU_Utilisation"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "repeatIteration": 1459928280207,
          "repeatPanelId": 6
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 8,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP3",
              "value": "S06-HYPERIONP3"
            }
          },
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Cpu.Avg_CPU_Utilisation"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "repeatIteration": 1459928280207,
          "repeatPanelId": 6
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 9,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP4",
              "value": "S06-HYPERIONP4"
            }
          },
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Cpu.Avg_CPU_Utilisation"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "repeatIteration": 1459928280207,
          "repeatPanelId": 6
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 10,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP5",
              "value": "S06-HYPERIONP5"
            }
          },
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Cpu.Avg_CPU_Utilisation"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "repeatIteration": 1459928280207,
          "repeatPanelId": 6
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 11,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP6",
              "value": "S06-HYPERIONP6"
            }
          },
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Cpu.Avg_CPU_Utilisation"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "repeatIteration": 1459928280207,
          "repeatPanelId": 6
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 12,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": "S06HYPERIONP",
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.PhysicalMemory.Physical_Memory_Used"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP1",
              "value": "S06-HYPERIONP1"
            }
          }
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 13,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.PhysicalMemory.Physical_Memory_Used"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP2",
              "value": "S06-HYPERIONP2"
            }
          },
          "repeatIteration": 1459928280207,
          "repeatPanelId": 12
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 14,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.PhysicalMemory.Physical_Memory_Used"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP3",
              "value": "S06-HYPERIONP3"
            }
          },
          "repeatIteration": 1459928280207,
          "repeatPanelId": 12
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 15,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.PhysicalMemory.Physical_Memory_Used"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP4",
              "value": "S06-HYPERIONP4"
            }
          },
          "repeatIteration": 1459928280207,
          "repeatPanelId": 12
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 16,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.PhysicalMemory.Physical_Memory_Used"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP5",
              "value": "S06-HYPERIONP5"
            }
          },
          "repeatIteration": 1459928280207,
          "repeatPanelId": 12
        },
        {
          "cacheTimeout": null,
          "colorBackground": false,
          "colorValue": false,
          "colors": [
            "rgba(245, 54, 54, 0.9)",
            "rgba(237, 129, 40, 0.89)",
            "rgba(50, 172, 45, 0.97)"
          ],
          "datasource": null,
          "editable": true,
          "error": false,
          "format": "none",
          "id": 17,
          "interval": null,
          "isNew": true,
          "links": [],
          "maxDataPoints": 100,
          "nullPointMode": "connected",
          "nullText": null,
          "postfix": "",
          "postfixFontSize": "50%",
          "prefix": "",
          "prefixFontSize": "50%",
          "repeat": null,
          "span": null,
          "sparkline": {
            "fillColor": "rgba(31, 118, 189, 0.18)",
            "full": false,
            "lineColor": "rgb(31, 120, 193)",
            "show": false
          },
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.PhysicalMemory.Physical_Memory_Used"
            }
          ],
          "thresholds": "",
          "title": "Panel Title",
          "type": "singlestat",
          "valueFontSize": "80%",
          "valueMaps": [
            {
              "op": "=",
              "text": "N/A",
              "value": "null"
            }
          ],
          "valueName": "avg",
          "scopedVars": {
            "S06HYPERIONP": {
              "selected": false,
              "text": "S06-HYPERIONP6",
              "value": "S06-HYPERIONP6"
            }
          },
          "repeatIteration": 1459928280207,
          "repeatPanelId": 12
        }
      ],
      "title": "New row"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "350px",
      "panels": [
        {
          "aliasColors": {
            "S06-HYPERIONP1.PhysicalMemory.Physical_Memory_Utilisation_crit": "#BF1B00"
          },
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 4,
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": true,
            "max": true,
            "min": true,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 1,
          "points": true,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "S06-HYPERIONP1.PhysicalMemory.Physical_Memory_Utilisation_warn",
              "fill": 0,
              "points": false
            },
            {
              "alias": "S06-HYPERIONP1.PhysicalMemory.Physical_Memory_Utilisation_crit",
              "fill": 0,
              "points": false
            }
          ],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "refId": "A",
              "target": "aliasByMetric($S06HYPERIONP.PhysicalMemory.Physical_Memory_Utilisation)"
            },
            {
              "refId": "B",
              "target": "aliasByMetric($S06HYPERIONP.PhysicalMemory.Physical_Memory_Utilisation_warn)"
            },
            {
              "refId": "C",
              "target": "aliasByMetric($S06HYPERIONP.PhysicalMemory.Physical_Memory_Utilisation_crit)"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "RAM",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "show": true
          },
          "yaxes": [
            {
              "format": "percent",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "title": "New row"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "300px",
      "panels": [
        {
          "aliasColors": {
            "S06-HYPERIONP1.Cpu.Avg_CPU_Utilisation_crit": "#BF1B00",
            "S06-HYPERIONP1.Cpu.Avg_CPU_Utilisation_warn": "#EAB839"
          },
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 2,
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": true,
            "hideEmpty": false,
            "max": true,
            "min": true,
            "rightSide": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 1,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 1,
          "points": true,
          "renderer": "flot",
          "seriesOverrides": [
            {
              "alias": "S06-HYPERIONP1.Cpu.Avg_CPU_Utilisation_crit",
              "fill": 0,
              "points": false
            },
            {
              "alias": "S06-HYPERIONP1.Cpu.Avg_CPU_Utilisation_warn",
              "fill": 0,
              "points": false
            }
          ],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "refId": "A",
              "target": "aliasByMetric($S06HYPERIONP.Cpu.Avg_CPU_Utilisation)"
            },
            {
              "refId": "B",
              "target": "aliasByMetric($S06HYPERIONP.Cpu.Avg_CPU_Utilisation_warn)"
            },
            {
              "refId": "C",
              "target": "aliasByMetric($S06HYPERIONP.Cpu.Avg_CPU_Utilisation_crit)"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "CPU usage",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "show": true
          },
          "yaxes": [
            {
              "format": "percent",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "title": "New row"
    },
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 5,
          "legend": {
            "alignAsTable": true,
            "avg": true,
            "current": true,
            "hideEmpty": false,
            "max": true,
            "min": true,
            "rightSide": false,
            "show": true,
            "total": false,
            "values": true
          },
          "lines": true,
          "linewidth": 2,
          "links": [],
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 12,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "refId": "A",
              "target": "$S06HYPERIONP.Network.OutputQueueLength"
            },
            {
              "refId": "B",
              "target": "$S06HYPERIONP.Network.PacketsReceivedErrors"
            },
            {
              "refId": "C",
              "target": "$S06HYPERIONP.Network._BytesReceivedPersec"
            },
            {
              "refId": "D",
              "target": "$S06HYPERIONP.Network._BytesSentPersec"
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "NETWORK",
          "tooltip": {
            "msResolution": false,
            "shared": true,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "show": true
          },
          "yaxes": [
            {
              "format": "short",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ]
        }
      ],
      "title": "New row"
    }
  ],
  "time": {
    "from": "now/d",
    "to": "now/d"
  },
  "timepicker": {
    "collapse": false,
    "enable": true,
    "notice": false,
    "now": true,
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "status": "Stable",
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ],
    "type": "timepicker"
  },
  "templating": {
    "list": [
      {
        "current": {
          "tags": [],
          "text": "All",
          "value": "$__all"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": true,
        "multi": false,
        "name": "S06HYPERIONP",
        "options": [
          {
            "selected": true,
            "text": "All",
            "value": "$__all"
          },
          {
            "selected": false,
            "text": "S06-HYPERIONP1",
            "value": "S06-HYPERIONP1"
          },
          {
            "selected": false,
            "text": "S06-HYPERIONP2",
            "value": "S06-HYPERIONP2"
          },
          {
            "selected": false,
            "text": "S06-HYPERIONP3",
            "value": "S06-HYPERIONP3"
          },
          {
            "selected": false,
            "text": "S06-HYPERIONP4",
            "value": "S06-HYPERIONP4"
          },
          {
            "selected": false,
            "text": "S06-HYPERIONP5",
            "value": "S06-HYPERIONP5"
          },
          {
            "selected": false,
            "text": "S06-HYPERIONP6",
            "value": "S06-HYPERIONP6"
          }
        ],
        "query": "S06-HYPERIONP*",
        "refresh": 0,
        "regex": "",
        "type": "query"
      }
    ]
  },
  "annotations": {
    "list": []
  },
  "refresh": false,
  "schemaVersion": 12,
  "version": 24,
  "links": []
}`

**Comment by floppy84** [comment]
In now in beta 3.

I still have issue on specific dashboard.

I use Two variable, with all value selected.

i repeat singlestat panel in fonction of "bank" variable
I repeat the row containing the previous singlestat panel in fonction of "Pdu" variable.


![image](https://cloud.githubusercontent.com/assets/3499449/14323672/bd2026c4-fc21-11e5-8f49-b8231eb849e6.png)

when i select ALL and ALL on both variable, i got a new panel ALL that appear.

![image](https://cloud.githubusercontent.com/assets/3499449/14323665/aee8fb8a-fc21-11e5-8ea6-005bdae58460.png)

i should miss a thing, but in my previous 2.6 version i got not issue

**Comment by torkelo** [comment]
strange, works great here:
http://play.grafana.org/dashboard/db/graphite-panel-repeats

**Comment by floppy84** [comment]
Ok but do you try to use **row repeat fonction** with singlestat repeat panel ?

![image](https://cloud.githubusercontent.com/assets/3499449/14343524/e3e287ea-fca1-11e5-9e13-eb5b6139325a.png)
