### ISSUE TITLE
[Question] Stack metrics per tag

### ISSUE THREAD

**Issue by dirkaholic** [grafana/grafana#4566]
Hi,

I would like know if the following is possible with grafana at the moment:

I have a dashboard showing the cpu usage of instances in my infrastructure collected via telegraf into InfluxDB. I used templating in order to repeat rows using the node type (like web server, etc.). There are usually several instances per node type. The metrics data in InfluxDB now has a usage_user and a usage_system column for the CPU which I want to show as one single metric (overall CPU usage of the instance). My first choice was the stack option for multiple series but it stacks all the metrics from the different instances together which is not what I want. My second try was to do something like  ```SELECT ("usage_system" + "usage_user") AS cpu_total``` in the InfluxDB query but then I couldn't use the grouping by hosts any more due to this error ```GROUP BY requires at least one aggregate function```. Using a max() or count() around the calculated value does not work as well (query parse error). 

Now my question is, what is the best practice of stacking metrics together per tag (like per instance in my case) ? Is it even possible or should this be a feature request ?

**Comment by torkelo** [comment]
InfluxDB query language and engine does not support that case I think, check with the InfluxDB project on github or their mailing list.

**Comment by dirkaholic** [comment]
And you don't think it would be a nice feature for grafana to be able to do that ?

**Comment by torkelo** [comment]
Grafana can if the datasource can, I mean you can do that with graphite. It's just influxdb does not support it. You can sort of getting it work by manually asigning stack groups in series overrides
