### ISSUE TITLE
[Bug] threshold green value are removed from single stat after upgrade to grafana 3

### ISSUE THREAD

**Issue by floppy84** [grafana/grafana#4567]
Hi All,

* What grafana version are you using? ==> Grafana 3.0 beta 2
* What datasource are you using? ==> Graphite 
* What OS are you running grafana on? Centos 

After upgrade i have lost on my single stat panels, all threshold for the green value 

![image](https://cloud.githubusercontent.com/assets/3499449/14282483/de5f09f6-fb3e-11e5-9559-eebaf6a660ad.png)

**Comment by bergquist** [comment]
@floppy84 could you please include the current value in the screenshot?

**Comment by torkelo** [comment]
This is by design, we discovered that we only need 2 values to describe the thresholds,

**Comment by floppy84** [comment]
ok it come from the fact that i didn't set treshold value on previous grafna 2.6.
![image](https://cloud.githubusercontent.com/assets/3499449/14282743/115bd18a-fb40-11e5-9485-55717f74e415.png)

and by default the color is green.

so i just have to set a default value on each singlestat panel

**Comment by floppy84** [comment]
default color value is orange. Whatever I do i can't change it to green

**Comment by floppy84** [comment]
Here too it's a bug for me, value still to orange color ::

![image](https://cloud.githubusercontent.com/assets/3499449/14309983/dd129b5c-fbdf-11e5-9005-1ce1f0bfd0e8.png)

**Comment by bergquist** [comment]
@floppy84 Make sure the value is below the first threshold. 
so if the value is 10 you could set the thresholds to "-4000, 4000"

Assuming you just want to set the color to green.
