### ISSUE TITLE
Yet another non_negative_derivative problem

### ISSUE THREAD

**Issue by iowelinux** [grafana/grafana#4568]
Hi,

I use InfluxDB 0.10.1 to keep counters and collectd 5.5.1 to push data to it.
It was told a lot about "broken" derivative function in previous InfluxDB versions. Seems it was fixed and a new function was created to exclude negative values.

I use the following query to display a graph:
`SELECT non_negative_derivative(mean("value"), 10s) FROM "interface_tx" WHERE "instance" = 'team0' AND $timeFilter GROUP BY time($interval) fill(null)`

interface_tx is a counter to calculate interface throughput

**The first problem** is that displayed values are wrong.
![grafana_wrong_values](https://cloud.githubusercontent.com/assets/11652212/14283113/6e9f2fc2-fb4a-11e5-9d1c-3725c2465bec.png)

Zabbix displays correct values and this is also confirmed by SNMP counter from the switch.
![zabbix](https://cloud.githubusercontent.com/assets/11652212/14283216/0a3bf3a2-fb4b-11e5-865e-5393a2dfe4c8.png)

Is there any known issue?

**The second one** is the absence of graph data in case of displaying short time period.
The query is still the same but it's impossible to see data for less than 3 hours.

For instance the data could be seen here using 3 hours time period
![grafana_3_hours](https://cloud.githubusercontent.com/assets/11652212/14283324/9ae46038-fb4b-11e5-98ee-4e5a8848aef6.png)

And couldn't be seen here for 1 hour
![grafana_1_hour](https://cloud.githubusercontent.com/assets/11652212/14283415/fe8d5b3a-fb4b-11e5-9c04-a93f9de87977.png)

Am I doing something wrong?

Thanks.

**Comment by torkelo** [comment]
For the first issue with wrong value, you will have to ask in the influxdb mailing list or support options. 

The last case where data is missing for last hour  it can be because group by time interval is lower the  the rate at which you 
Write metrics. You can  set min level like >10s in the group by time field bellow the queries
