### ISSUE TITLE
New Y-negative transformation not migrated while converting "old Graph" to "Time Series"

### ISSUE THREAD

**Issue by luizluca** [grafana/grafana#45697]
**What happened**:
When I convert an old graph to timestamp, Y-negative transformation is lost (grafana 8.4.1). If that was the only overwrite for a specific match, the match is also removed.

**What you expected to happen**:
It should have migrated it correctly 

**How to reproduce it (as minimally and precisely as possible)**:
- In an old gaprh, add a single overwrite to transformation to use negative Y.
- Migrate to Time series

**Anything else we need to know?**:
As an easier path, add a second property modification to the same overwrite that negates the Y-axis. That way, you will keep it and can simply add the new Y-negative transformation and remove the temporary extra property change.

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: prometheus
- OS Grafana is installed on: SUSE
- User OS & Browser: Any
- Grafana plugins: Time series
- Others:

**Comment by ashharrison90** [comment]
@grafana/grafana-bi-squad not sure if this should be on your board or user essentials. think it's probably yours given you've just introduced the negative y transform in timeseries? 

also noticed this message which isn't true anymore: 
![image](https://user-images.githubusercontent.com/20999846/155975355-22980e8d-8f0a-4306-bfe1-77b01650b01b.png)

**Comment by luizluca** [comment]
Sure! [old-intenet.json.gz](https://github.com/grafana/grafana/files/8247181/old-intenet.json.gz)

**Comment by dprokop** [comment]
@luizluca thank you, I'll have a look at this in the morning, and I'll get back to you.
