### ISSUE TITLE
Grafana discussion group/forum

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#457]
Does there exist a discussion group/forum for uses of grafana to gather and discuss? I can't find any pointers on the website or in the documentation.
I'm looking at building a certain framework around grafana that would require the enhancement with some features and would like to discuss with people what they think about these ideas and how to best implement them in grafana.

**Comment by torkelo** [comment]
https://groups.io/org/groupsio/grafana

**Comment by digambarGitHub** [comment]
We are using grafana to show values in format of $123.45k this. We have done all the settings under '**Axes & grid**' tab. see below

![image](https://cloud.githubusercontent.com/assets/8347565/15044741/37f40be8-12f4-11e6-9236-4abdf544081d.png)

But once we apply setting and save,it visible to us as $123.45k but when we refresh the page it shows again like 12345. Even **$** sign goes away. See the inconsistency in below screenshot : 

![image](https://cloud.githubusercontent.com/assets/8347565/15044812/9fabec9c-12f4-11e6-9722-008a9c63e937.png)

Please provide the information if anyone knows to get rid of this issue.

@torkelo @edasque @dennisjac
