### ISSUE TITLE
Hovering over "Cycle view mode" makes scrollbar appear

### ISSUE THREAD

**Issue by septatrix** [grafana/grafana#45700]
**What happened**:

I hovered with my mouse over the "Cycle view mode" button in the dashboard view and a scrollbar appeared together with the hover-text. (Screencast attached.)

**What you expected to happen**:

The hover-text should be clamped to the right screen border and not generate a scrollbar.

**How to reproduce it (as minimally and precisely as possible)**:

Hover over the "Cycle view mode" button in any dashboard view.

**Anything else we need to know?**:

This might cause some annoying layout shift with certain dashboards or on different screen sizes.

**Environment**:
- Grafana version: 8.4.1
- User OS & Browser: Fedora 35 / Google Chrome 98

https://user-images.githubusercontent.com/24257556/155022077-164217ed-2fd7-41d4-84a0-40db410c2972.mp4

**Comment by zuchka** [comment]
Thanks for creating this issue, @septatrix 

I'm having trouble reproducing this. Can you see if this occurs when you visit play.grafana.org?

If so, can you give additional info about your OS and specific Chrome version? thank you!

**Comment by septatrix** [comment]
Yes I can reproduce it at play.grafana.org. I am not sure what further information about the OS would be helpful to you but the prices Chrome version is 98.0.4758.102.

One thing to note is that this might not be as apparent when using Chrome on MacOS as the scrollbars are layered above the content and therefore not as visible. However even in that case it should be possible to see that the page gets wide as horizontal scrolling (using shift+mouse wheel or left/right arrow keys) is possible when hovering.

**Comment by septatrix** [comment]
I can no longer reproduce this myself. It might have been fixed in the meantime by some other UI changes
