### ISSUE TITLE
Interface Utilization (ifinoctets, ifoutoctets) 

### ISSUE THREAD

**Issue by Ivan076** [grafana/grafana#4571]
I need some help on the expression that i need to write as i have a huge discrepancy between prtg and grafana.

can somone kindly advise.

best regards

**Comment by torkelo** [comment]
Please ask in the mailing list for the time series database you use, can also maybe find help in the grafana mailing list.

**Comment by Ivan076** [comment]
What is the like to these mailing lists? You wrote the application can't
you help me pls?

**Comment by torkelo** [comment]
Your question is a datasource query question, have no idea what datasource
you even use, how you collect metrics etc. Please check with for support
links for you time series database :)
