### ISSUE TITLE
CloudWatch: `go test -count <any number above 1>` will not finish

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#45717]
**How to reproduce it (as minimally and precisely as possible)**:
1. Navigate to `/github.com/grafana/grafana/pkg/tsdb/cloudwatch`
2. Run `go test -count 2`

Expected: It should run the go tests there twice
Actual: It will not terminate

**Anything else we need to know?**:
Merits an investigation for some weird parallel process happening. 
With the verbose flag `go test -v count 2` it is hanging on `TestGetMetricDataExecutorTest`

Ran across this while I was wondering if we still needed this sort line [here](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/response_parser.go#L91) ([original PR](https://github.com/grafana/grafana/pull/21572)). I wanted to run the tests several times to see if they were flaky without the sort.

**Environment**:
- Grafana version: 8.5.0-pre

**Comment by iwysiu** [comment]
The issue is that the `counter` variable in [the test file](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/get_metric_data_executor_test.go) should get set to 1 at the start of `TestGetMetricDataExecutorTest`

**Comment by fridgepoet** [comment]
Oooh thank you!
