### ISSUE TITLE
y ordinate does not match the data ?

### ISSUE THREAD

**Issue by gongchangyou** [grafana/grafana#45710]
<img width="1425" alt="image" src="https://user-images.githubusercontent.com/2409053/155099439-344477f8-2a46-41e5-8566-9b0a4ebb8073.png">

**Comment by torkelo** [comment]
you have stacking enabled, but the tooltip is configured to show unstacked values

**Comment by gongchangyou** [comment]
sorry , I can't understand yet.  since GPU 1's Power Usage is always low (59.1w), much less than other GPU. 
why the line of GPU 1 is much higher than other GPUs ？

**Comment by torkelo** [comment]
The values are stacked (added on top of each other) you can disable it, or you can configure the tooltip to show stacked values

**Comment by gongchangyou** [comment]
Oh, I C! 
 the green line means GPU7's power usage . 
 the purple line means GPU0-GPU7  all of the gpu's power usage.
 
 hard to understand……

**Comment by gongchangyou** [comment]
where is  the configure if I  want to disable stacked ?

**Comment by gongchangyou** [comment]
I found it! 

/var/lib/grafana/dashboards/gpu-dashboard.json

Thank you very much!
