### ISSUE TITLE
[Feat Req]: grafana-cli should use default data/plugins dir when used from development dir

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4572]
when compiling grafana (and hence also grafana-cli) installing plugins is broken
because grafana-cli defaults to /var/lib/grafana/plugins whereas grafana defaults to data/plugins
so grafana won't find the plugins installed with grafana-cli.

**Comment by bergquist** [comment]
Did you execute the cli from the /pkg/cmd/grafana-cli folder? 

https://github.com/grafana/grafana/commit/583c0f09a8de635f11625bdbfa6be8f01ce889a4 this commit would fix that. 

I should make sure it can be executed from the /grafana/bin folder as well.

**Comment by Dieterbe** [comment]
if i remember correctly i just ran it from wherever the build command put the binary, which i believe was in the bin folder.

**Comment by torkelo** [comment]
> @Dieterbe Did you execute the cli from the /pkg/cmd/grafana-cli folder?
Does the binary every end up there? Though it always ended up in `<repo>/bin`

**Comment by Dieterbe** [comment]
after running the build commands the grafana-cli file only exists in 1 place
```
root@f51a521b6a91:/go/src/github.com/grafana/grafana# ls -alh bin/
total 30M
drwxr-xr-x  2 root root 4.0K Apr  9 21:33 .
drwxr-xr-x 22 root root 4.0K Apr  9 21:41 ..
-rwxr-xr-x  1 root root 7.3M Apr  9 21:33 grafana-cli
-rw-r--r--  1 root root   33 Apr  9 21:33 grafana-cli.md5
-rwxr-xr-x  1 root root  23M Apr  9 21:33 grafana-server
-rw-r--r--  1 root root   33 Apr  9 21:33 grafana-server.md5
root@f51a521b6a91:/go/src/github.com/grafana/grafana# find / -name grafana-cli
/go/src/github.com/grafana/grafana/bin/grafana-cli
/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli
/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/grafana/grafana-cli
root@f51a521b6a91:/go/src/github.com/grafana/grafana# find / -name grafana-cli -type d
/go/src/github.com/grafana/grafana/pkg/cmd/grafana-cli
/go/src/github.com/grafana/grafana/Godeps/_workspace/src/github.com/grafana/grafana-cli
root@f51a521b6a91:/go/src/github.com/grafana/grafana# find / -name grafana-cli -type f
/go/src/github.com/grafana/grafana/bin/grafana-cli
root@f51a521b6a91:/go/src/github.com/grafana/grafana# 
```

**Comment by bergquist** [comment]
It was my sleep depraved brain that was assuming everyone else compiles and runs the cli from the /pkg/cmd/grafana-cli folder. which ofc... they don't unless they develop the cli. 

I'm no '*nix pro but just looking at "/bin" seems like it could cause problems in the future (acting like dev env when installed on server)

How about checking if "../data" exists. I think this would work for *nix installations, dev env and windows installations. What do you think @torkelo and @Dieterbe

**Comment by torkelo** [comment]
@bergquist yes, that is what grafana-server does for the conf folder (when run in development mode), it checks for ../conf/defaults.ini 

How do you get the binary to land in /pkg/cmd/grafana-cli  ? go run build.go build always puts it in `<repo>/bin`  do you go into /pkg/cmd/ and run "go build ."?

**Comment by bergquist** [comment]
Yes. When developing the cli I've been compiling and running it from /pkg/cmd/grafana-cli.

Checking for ../conf/defaults.ini would be more consistent. Seems like a good idea.

**Comment by alopezdu** [comment]
Hello, i've just installed the latest build and plugin installation fails until i move the folder manually. My installation as a package (dpkg -i grafana_3.0.0-beta41460581169_amd64.deb) uses the defaults.ini instead of using /etc/grafana/grafana.ini.
As a consecuence, it detects my environment as a development and returns ../data/plugins instead of 
 	defaultNix := "/var/lib/grafana/plugins"

How can i change the installation package to launch from the /etc/grafana/grafana.ini ?

Thanks in advance.

**Comment by torkelo** [comment]
How are you not using /etc/grafana/grafana.ini ? Custom init'd script ? You can specify plugins dir with --pluginsDir

**Comment by alopezdu** [comment]
Followed dpkg instructions:
### NOT starting on installation, please execute the following statements to configure grafana to start automatically using systemd
 sudo /bin/systemctl daemon-reload
 sudo /bin/systemctl enable grafana-server
### You can start grafana-server by executing
 sudo /bin/systemctl start grafana-server

I've not done my custom init.d script yet, but launching the program with service restart or systemctl, it uses de defaults.ini. How can i launch grafana using /etc/grafana.ini?

**Comment by torkelo** [comment]
reverted this commit that closed this as the commit broke the non development build scenarios :) in all the official (deb/rpm) builds the cli tool would use "../data/plugins" directory .

Think there was only a `!` wrong that caused the issue, but did not have time to investigate at the time so only reverted the commit to get a proper build out.

**Comment by alopezdu** [comment]
Ok thanks, i installed it manually, i will try whole installation again.

**Comment by alopezdu** [comment]
I'm consistently testing 3.0 nightly builds over a graphite with 70k metrics, so if you want me to test specific things please let me know.
