### ISSUE TITLE
NGAlert: Alertmanager log level regression

### ISSUE THREAD

**Issue by jwood-krg** [grafana/grafana#45738]
**What happened**:

Alertmanager is not respecting the default log level specified in grafana.ini, and is writing debug level to the console and file.

**What you expected to happen**:

Alertmanager should follow the default log level specified in grafana.ini

**How to reproduce it (as minimally and precisely as possible)**:

Install Grafana 8.4.1, and configure some alerts using Grafana's internal alertmanager.

**Anything else we need to know?**:

This appears to be a regression of the fix for #39146 after the removal of log15 in #41636 and the removal of the log15/go-kit bridge in #43769.

**Environment**:
- Grafana version: 8.4.0-beta1 and newer.
- Data source type & version: N/A
- OS Grafana is installed on: RHEL
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by ying-jeanne** [comment]
I think this should be a real bug, since now we overwrite the level of gokit/log debug into dbug because of log15, we still need to do the mapping for alerting. Or we can just remove the overwrite now since we migrate the log since a while, if hosted grafana agree.

**Comment by marefr** [comment]
Think I understand what's going on now. Grafana uses a custom level package and embedded alertmanager uses the level package provided by gokit. 

To resolve this think we need to take gokit level package into consideration as well here: https://github.com/grafana/grafana/blob/9d3b701797d4b7685fbed5047da356b29edc554d/pkg/infra/log/level/level.go#L51-L56
