### ISSUE TITLE
newly enabled plugins don't show up in menu until page reloaded

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4574]
g3 beta3

**Comment by torkelo** [comment]
this is how the sidemenu works, and the page is reloaded after plugins are enabled (if the process is successfull)

**Comment by torkelo** [comment]
there are other stuff for plugins that require a page reload not just the sidemenu, some of this is for legacy reasons since grafana's web only days.s

**Comment by Dieterbe** [comment]
in my case i had disabled the app and reenabled it (successfull)  and the page didn't reload

**Comment by torkelo** [comment]
strange, it does here (when I disable an app, page reloads and it is no longer in menu). 

As I said if something results in an error (like dashboard import) the process is aborted and the page is not reloaded.

**Comment by Dieterbe** [comment]
> As I said if something results in an error (like dashboard import) the process is aborted and the page is not reloaded. 

the dashboard import definitely failed because it had already imported them. not sure the process was aborted because after a (manual) page reload the plugin was enabled in its settings and also listed in the menu.
