### ISSUE TITLE
Escaping of newline \r\n results in double newlines in "Explore"

### ISSUE THREAD

**Issue by perosb** [grafana/grafana#45746]
**What happened**:
the escaping of newlines replaces \n and \r separately https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/logs.ts#L232 which results in multiple newlines.

Windows newlines \r\n should be escaped as a single newline.

![image](https://user-images.githubusercontent.com/982752/155196062-e1828ec1-38dd-4992-a1dd-cb71af0ff5f2.png)

**What you expected to happen**:
![image](https://user-images.githubusercontent.com/982752/155196289-41c9c1a3-a0ee-4ee3-b5f0-086ac465a6cb.png)

**Environment**:
- Grafana version: 8.3.5
- Data source type & version: Loki
- OS Grafana is installed on: Docker/Linux
- User OS & Browser: Chrome

**Comment by ivanahuckova** [comment]
This is a small change where regex in [here]( https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/utils/logs.ts#L232) should be change from `/\\n|\\t|\\r/g` to `/\\r\\n|\\n|\\t|\\r/g`.
