### ISSUE TITLE
Cannot Add Zabbix as Data Source

### ISSUE THREAD

**Issue by mzromadhoni** [grafana/grafana#45764]
I use grafana v8.4.1 and install zabbix 4.2.5

but when I go to the data source menu, I don't find Zabbix

why?

![image](https://user-images.githubusercontent.com/70420081/155298977-c9167b75-4d67-416e-ae91-e7cd48a18d10.png)

![image](https://user-images.githubusercontent.com/70420081/155299091-dbed5fd9-e618-4f3c-86a8-3f1b23b2cda9.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @mzromadhoni 

Because Zabbix is a third-party plugin, I think the best place to start is to file in issue in that specific repo 👍 

https://github.com/alexanderzobnin/grafana-zabbix/issues

**Comment by mzromadhoni** [comment]
Thanks for your advice
