### ISSUE TITLE
datasource help dialog looks wrong

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4576]
g3 beta3

1) why is the "proxy" button in there? (firefox on linux)
2) instead of "http://localhost:8080"  it should say something like "for example: http://localhost:8080",
otherwise people might think we recommend they add that url.
![ds-help](https://cloud.githubusercontent.com/assets/20774/14297781/afe00246-fb4e-11e5-8875-de38fca5458f.png)

**Comment by torkelo** [comment]
must have been the late addition of the "code" tag styles. will fix
