### ISSUE TITLE
datasource entry: auto-suggest default URL

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4577]
for example, when adding a snap datasource, it can automatically fill in the default http://localhost:8181

**Comment by torkelo** [comment]
yea, this is something I have wanting to do for a long time to make adding a ds easier.

**Comment by rmoff** [comment]
+1
This will help power users save time, and new users with fewer configuration options to have to set.

**Comment by utkarshcmu** [comment]
+1
