### ISSUE TITLE
Docs: Improve wording for tooltip in "Add escaping feature" in Explore

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#45770]
A ~year ago we have added this [smart feature](https://github.com/grafana/grafana/pull/31352) to Explore that checks if it is possible that logs have incorrectly escaped log content and if so, we add option to try to escape it correctly. 

**What was mentioned in original PR:**

```
❗️What is very important - we should communicate to users that the lines aren't correctly 
escaped and that the first step should be fixing escaping. However, for some logs it is very 
hard/almost impossible to correctly escape them. And for thos cases, we would provide them 
with a feature that would replace incorrectly escapes newlines with actual newlines. Of course, 
it might always produce incorrect results, as we don't know which characters are actual newlines
 and which have just the \n pattern, but I think that if we communicate it clearly, users will 
understand.
```

So we added to tooltip following info: `We suggest to try to fix the escaping of your log lines first. This is an experimental feature, your logs might not be correctly escaped."`

However, we got feedback from users that `This is an experimental feature` makes them feel like we might remove this feature which we don't plan. So we could improve wording to remove `experimental feature` wording.

This is how feature looks:
![image](https://user-images.githubusercontent.com/30407135/155304932-abb84f0a-eeaf-4539-ac3e-ad3cf3463cea.png)

https://user-images.githubusercontent.com/30407135/155304940-738a1f72-3391-4d22-a90b-e66b0f77b8bc.mov

**Comment by ivanahuckova** [comment]
@grafana/docs-squad Could you please help us with this one? 🙏

**Comment by GrafanaWriter** [comment]
@gguillotte-grafana - Can you please take a look?

**Comment by gguillotte-grafana** [comment]
Bumping to note the discussion in #46709 around how (or whether) to communicate the feature's reliability in the docs.
