### ISSUE TITLE
[Feature Request] OrientDB datasource plugin

### ISSUE THREAD

**Issue by imainetti** [grafana/grafana#4581]
Hi all,

do you think is possible to include the support for **OrientDB** in the datasource list?

**Comment by adolci** [comment]
+1

**Comment by ogubchenko** [comment]
+1
#orientdb #grafana

**Comment by torkelo** [comment]
we are not going to add more data sources to the core project right now but as external plugins, 

http://docs.grafana.org/plugins/development/

Plugin site:
http://grafana.net
