### ISSUE TITLE
[Bug] Unit changed for unrelated graph

### ISSUE THREAD

**Issue by pstibrany** [grafana/grafana#4582]
I'm using Grafana 3.0 beta, with Prometheus, running on 64-bit Linux.

When building dashboards, I often see following behaviour. First, I add some graphs, with units. Then I add another graph and set its units too. Now when I look at previous graphs, their units are sometimes wrong, and often set to the unit of last changed graph.

I've seen this happen several times, but when I try to reproduce it systematically, I fail. I will keep an eye on it, and add more details.

**Comment by milesich** [comment]
It happened to me too. All charts were showing the same units.

**Comment by torkelo** [comment]
please let me know if you can find a consistent way to replicate. Have not been able to thus far

**Comment by milesich** [comment]
I managed to reproduce it by adding new charts on the dashboard without saving the dashboard. Then change unit on one of the newly added chart and click on the refresh icon in the top right. At this point all charts should have the same unit.

**Comment by torkelo** [comment]
tried to do that here but no still failing to see this issue, http://play.grafana.org/dashboard/db/graph-styles

**Comment by pstibrany** [comment]
I can reproduce using the instructions from @milesich. See https://www.youtube.com/watch?v=_Nwr6GVViMI

**Comment by torkelo** [comment]
ok, so it doesnt change units on already existing charts only on newly added ones? will try to replicate again with 2 newly added charts

**Comment by torkelo** [comment]
ok found the issue and fixed it!  thanks for helping me replicate it!

**Comment by pstibrany** [comment]
Thank you!
