### ISSUE TITLE
Remove CloudWatch integration test

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#45829]
**What happened**:

Integration tests for CloudWatch were removed [here](https://github.com/grafana/grafana/pull/45800/files#diff-e56e9a352a0a6148771d4cebd70b5d5f66bba93fd0bdb5ae8a110396b74caa54) because they were flaky. We should:

 - Evaluate the root cause of the flakiness: is it a CloudWatch issue or something related to the test environment?
 - Evaluate if we should maintain those tests. The test starts a real Grafana instance and mocks the AWS client to return results. We may be able to cover the same functionality just with unit test (since it's not the responsibility of the plugin to test the Grafana API).

Inspiration possible from #54379

**Comment by fridgepoet** [comment]
We may just remove the test itself completely.
