### ISSUE TITLE
Grafana 8.4.1: build binaries failed

### ISSUE THREAD

**Issue by flynn1973** [grafana/grafana#45840]
**What happened**:
binaries failed to build
````
root@lpgaixmgmtlx01:/scratch/go/dev/src/github.com/grafana/grafana>go run build.go setup
Version: 8.4.1, Linux Version: 8.4.1, Package Iteration: 1645710638
go install -v ./pkg/cmd/grafana-server
github.com/grafana/grafana/pkg/cmd/grafana-server/commands
# github.com/grafana/grafana/pkg/cmd/grafana-server/commands
pkg/cmd/grafana-server/commands/cli.go:170:12: undefined: server.Initialize
exit status 2
exit status 1
root@lpgaixmgmtlx01:/scratch/go/dev/src/github.com/grafana/grafana>go run build.go build
Version: 8.4.1, Linux Version: 8.4.1, Package Iteration: 1645710653
building binaries build
building grafana-server ./pkg/cmd/grafana-server
rm -r ./bin/linux-ppc64le/grafana-server
rm -r ./bin/linux-ppc64le/grafana-server.md5
go build -ldflags -w -X main.version=8.4.1 -X main.commit=53f5c6a -X main.buildstamp=1645182847 -X main.buildBranch=HEAD -o ./bin/linux-ppc64le/grafana-server ./pkg/cmd/grafana-server
# github.com/grafana/grafana/pkg/cmd/grafana-server/commands
pkg/cmd/grafana-server/commands/cli.go:170:12: undefined: server.Initialize
exit status 2
exit status 1
````

**What you expected to happen**:
functional binaries built

**How to reproduce it (as minimally and precisely as possible)**:
run go run build.go setup in the grafana source tree
run go run build.go build in the grafana source tree

**Anything else we need to know?**:
nope

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: None
- OS Grafana is installed on: RedHat EL 
- User OS & Browser: Linux & Mozilla
- Grafana plugins: None
- Others:

**Comment by flynn1973** [comment]
seems related:
https://github.com/grafana/grafana/issues/40839
https://github.com/grafana/grafana/pull/42390

alas the PR seems to be merged error still exists....

**Comment by eaibmz** [comment]
I'm having the same issue on s390x and Grafana 8.4.2

**Comment by flynn1973** [comment]
Executing make gen-go before building the Go source make the compile run through, but i dont see this as the "solution". this is documented nowhere as usual, every new grafana release brings up its on new odd "surprises". pathetic!

**Comment by kylebrandt** [comment]
Which instructions are being followed here for building? 

There backend guide for developing says to use `make` on nix style operating systems which include the generate commands, and for Windows (without make) the generate instruction is there. https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#backend

But perhaps this is documented elsewhere that I am not aware of that needs to be updated?

**Comment by flynn1973** [comment]
this whole rumble stems from the fact that grafana makes building custom packages without using the "magic" garafana labs interal ci crap quite a heavy task.

read on:

https://github.com/grafana/grafana/issues/30963
https://github.com/grafana/grafana/issues/30963#issuecomment-882645531
https://github.com/grafana/grafana/issues/36798

**Comment by eaibmz** [comment]
Sorry for the noise, was my fault, the official Grafan Docker image works but NOT on s390x (big-endian arch):

```
Internal Error: Execution failed with a non-error rejection (rejected value: "Runtime error: expected the system to be little-endian!")
    at oo.error (/grafana/.yarn/releases/yarn-3.1.0.cjs:377:305)
    at r (/grafana/.yarn/releases/yarn-3.1.0.cjs:448:10660)
```

**Comment by malcolmholmes** [comment]
Here are the [official docs](https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md#backend) for building Grafana. If those don't work for you, please do open an issue, they will need fixing.

Regarding building custom deb/rpm packages, this is not something we plan to support publicly.

Regarding the CI tooling - yes, it is more complex than it needs to be. We also feel some pain there. We're exploring other approaches.
