### ISSUE TITLE
[State Timeline] Absence of data not represented anymore

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#45852]
**What happened**:

Since we upgraded  to 8.4.x, I observe a behavior very similar to the one reported in https://github.com/grafana/grafana/issues/42868 and supposedly fixed. State timeline panel doesn't close the horizontal bar when a time-series vanish. Bar continues with the same value / color until it reaches the right axis rather than stopping when time-series disappeared.  I think it's a regression as 8.3.4 was working fine.

**What you expected to happen**:

state timeline panel should close horizontal bars when there is no data for a time-series.

**How to reproduce it (as minimally and precisely as possible)**:

I use a very simple PromQL query: `vm_app_uptime_seconds < 60` and a state timeline panel with color scheme set to a _by value_. I also define time series panel using the same query as a reference point. 

Using Grafana 8.4.0, we observe that time series panel behave as expected but state timeline doesn't. Last bar should stop at 16:20 but doesn't. 

![image](https://user-images.githubusercontent.com/1764725/155555374-9403e64a-8eba-48f2-acc3-f7d1a0b89cae.png)

Using Grafana 8.3.4, we observe that both time series panel and state timeline panel behave as expected.

![image](https://user-images.githubusercontent.com/1764725/155556988-a55240a0-2275-4f11-9ec8-13cda67b68f1.png)

**Anything else we need to know?**:

Behavior also seems to differ according to the color scheme. For example  8.3.4 & (single color|classic palette| GYR by value) works fine; but _from thresholds (by value)_ doesn't.

**Environment**:
- Grafana version: 8.4.0 (8.4.1 seems impacted too)
- Data source type & version: Prometheus
- User OS & Browser: Firefox 97

**Comment by cykl** [comment]
@ivanahuckova Created a new issue to not pollute the old one (ref. https://github.com/grafana/grafana/issues/42868#issuecomment-1049881983)

**Comment by leeoniya** [comment]
@cykl 

can you please add your exact response data here?

https://user-images.githubusercontent.com/43234/155532434-85374538-4835-49d8-9bbd-5bf9595fb5c9.mp4

**Comment by cykl** [comment]
```json
{"results":{"A":{"frames":[{"schema":{"name":"vm_app_uptime_seconds{instance=\"self\", job=\"victoria-metrics\"}","refId":"A","meta":{"custom":{"resultType":"matrix"}},"fields":[{"name":"Time","type":"time","typeInfo":{"frame":"time.Time"},"config":{"interval":15000}},{"name":"Value","type":"number","typeInfo":{"frame":"float64","nullable":true},"labels":{"__name__":"vm_app_uptime_seconds","instance":"self","job":"victoria-metrics"},"config":{"displayNameFromDS":"vm_app_uptime_seconds{instance=\"self\", job=\"victoria-metrics\"}"}}]},"data":{"values":[[1645715325000,1645715340000,1645715355000,1645715715000,1645715730000,1645715745000,1645715970000,1645715985000,1645716000000,1645716930000,1645716945000,1645716960000],[15,30,45,15,30,45,15,30,45,15,30,45]]}},{"schema":{"name":"exemplar","refId":"A","meta":{"custom":{"resultType":"exemplar"}},"fields":[{"name":"Time","type":"time","typeInfo":{"frame":"time.Time"}},{"name":"Value","type":"number","typeInfo":{"frame":"float64"}}]},"data":{"values":[[],[]]}}]}}}
```
It should be very easy to reproduce with detailed steps though.

**Comment by leeoniya** [comment]
i wanted to make sure `"config":{"interval":15000}` was being returned and that the data did not have pre-exisitng `null` values. the first part is  not easy to verify with repro steps because it depends on the datasource and cannot be set via UI options.

it looks like we should insert a terminating `null` at 1645716960000 + 15000.

**Comment by argibbs** [comment]
Hiya, as per https://github.com/grafana/grafana/issues/42868#issuecomment-1073792718

This isn't working for me in 8.4.4

**Comment by cykl** [comment]
Updated to 8.4.4 this morning, fix seems to work for me.

**Comment by leeoniya** [comment]
@cykl can you open a new issue with above info?
