### ISSUE TITLE
"managed" alerting terminology is confusing.

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#45869]
I notice that https://grafana.com/docs/grafana/latest/alerting/unified-alerting/ talks about "cortex managed alerting rules" and "loki managed alerting rules".

That page has a link with title "View existing alerting rules and manage their current state", going to a url https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/rule-list/, and the page has the title "Manage alerting rules". why are title, url and link text so different? You would think that maybe this page explains what terms like "cortex managed alerting rules" mean, but it doesn't. It does talk about "Grafana managed alerting rules" .
This might lead one to think that maybe there's a separate page for managing alerting rules for "cortex/loki managed alerting rules", just like the creation pages are separated out ("Create Grafana managed alerting rules" and "Create Cortex or Loki managed alerting rules") but i could find no separate page for these.

So that page talks about the various management operations (grouping, filtering, editing, deleting,...).  This seems like a different meaning of the term "manage" as in terms "cortex managed alerting rules". And btw, why is "creating" not considered part of managing?  I note that elsewhere (e.g. https://grafana.com/docs/grafana/latest/manage-users/server-admin/server-admin-manage-users/ , managing includes creation and editing)

This page talks about "Alerting rules for an external Cortex or Loki instance".  Is this the same as 
 the "Cortex or Loki managed alerting rules" term that's used elsewhere?
I suspect we are now using different terms here precisely because we have changed the meaning of the word "manage"? 

My suggestion:
- since the word management is used all over the place, try to be consistent in what it means.  E.g. creating, filtering, viewing, etc like elsewhere.
- AFAICT cortex and loki don't manage the rules, a human operator does. cortex/loki seem to "host" or perhaps "run" the alerts? can we find better terms than "Cortex or Loki managed alerting rules"?
- can we create more consistency between url's, page titles, and link text?
- where's the information on how to manage alerts in "cortex managed rules"? or if the answer is "you can't manage those alerts, they are managed by cortex" then why does that last page say you can manage "Alerting rules for an external Cortex or Loki instance". what is the difference?

**Comment by leeoniya** [comment]
would `monitored` work better in the context of `* managed`. and leave "manage" to mean the create/update/delete human actions.

**Comment by armandgrillet** [comment]
We explain the differences in https://grafana.com/docs/grafana/next/alerting/fundamentals/alert-rules/alert-rule-types/ and try to be clearer with Grafana v. Datasources managed alerts since this issue has been created.
