### ISSUE TITLE
Panel doesn't update data coming from Data Source created from HTTP API, unless Test Connection is performed

### ISSUE THREAD

**Issue by kartiksomani** [grafana/grafana#4586]
Using grafana 2.9, data source is elastic search, running on Red hat linux.

I'm creating data source via HTTP api, and then importing a dashboard, whose panels take data from one of those created data sources (data source name is mentioned in json)
I don't see dashboard getting updated with new data, unless i go to each data source and click "Test Connection" on the UI

Is the any way to avoid the need to click "Test Connection", via the HTTP API?

**Comment by torkelo** [comment]
test connection has nothing to to with getting data or not, just verifies that grafana can reach your data source. 

Do you see any data in your dashboard, is the dashboard time picker set to auto refresh? What is the elasticsearch queries and responses? (check chrome dev tools network tab)

**Comment by kartiksomani** [comment]
No, I don't see the data in dashboard, even after i refresh the web page. It starts receiving data as soon as I go to data sources and either click on "Save" or "Test Connection"

**Comment by kartiksomani** [comment]
Any update on this?

**Comment by torkelo** [comment]
No waiting on update form you :)

Make sure when you create the ds via the api that you make the same requestime the UI makes (same data etc)

**Comment by kartiksomani** [comment]
You're right. I checked, and it was the timestamp field which was missing. It's working now. Thank.
