### ISSUE TITLE
Unexpected `query` field value in `/api/prometheus/grafana/api/v1/rules`

### ISSUE THREAD

**Issue by codesome** [grafana/grafana#45882]
**What happened**:

*This is for Prometheus alert-generator compliance, read more [here](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md). Using Grafana managed alert on a Prometheus datasource.*

To get Prometheus compliant behaviour out of Grafana Alerting, user would have a single query specified in the alerting rule like this:

![Screenshot from 2022-02-25 13-32-35](https://user-images.githubusercontent.com/15064823/155685037-db7453b8-56a7-49ec-a5d8-793ba2fc0860.png)

The `query` field for rules in `/api/prometheus/grafana/api/v1/rules` would expect only the query that was specified in the alerting rule when there is only one condition specified. Instead it has this which is not compliant:
```
"query": "[{\"refId\":\"A\",\"queryType\":\"\",\"relativeTimeRange\":{\"from\":300,\"to\":0},\"datasourceUid\":\"0ReGYlBnk\",\"model\":{\"exemplar\":false,\"expr\":\"test_rule_1 \\u003e 0\",\"hide\":false,\"instant\":true,\"interval\":\"\",\"intervalMs\":1000,\"legendFormat\":\"\",\"maxDataPoints\":43200,\"refId\":\"A\"}}]"
```

**What you expected to happen**:

For `/api/prometheus/grafana/api/v1/rules`, when the rule has only one query, the API to only have that query in the `query` field.

For the example above, it would be `"query": "test_rule_1 > 0"`

**Anything else we need to know?**:

This is mainly for how the API outputs the data. The internals of the alerting engine might not require any changes for this.

**Environment**:
- Grafana version: 8.4.2

**Comment by gotjosh** [comment]
Draft PR created at: https://github.com/grafana/grafana/pull/45969

Can you test the branch for me Ganesh?
