### ISSUE TITLE
Timeseries: Negative Y does not render properly, when there is metric for short period of time

### ISSUE THREAD

**Issue by frenkye** [grafana/grafana#45916]
**What happened**:
Trying new Negative Y transformation and I notice, that our nightly backup LVM snapshots are causing graph not to render, because on now-24h range there are only metrics from 5 min to N hours over night depend on server. Datapoint are there on mouseover, but graph will not render unless we hide the temporal metric or cancel the transofrmation. As shown in the video.

**What you expected to happen**:
Graph will render.

**How to reproduce it (as minimally and precisely as possible)**:
Create some temporal mountpoint with node_exporter & prometheus as datasource.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.1 (53f5c6a44c) also happen on v8.4.2 (9fc02d717f)
- Data source type & version:  Prometheus 2.29.2 & node_exporter 1.3.1
- OS Grafana is installed on: Debian 10.10
- User OS & Browser: MacOS Monterey 12.1 & FF 97 and Chrome 98.0.4758.109 
- Grafana plugins: Clickhouse & Pie Chart

https://user-images.githubusercontent.com/13994937/155727698-00d9df74-04ec-4d3e-9cbb-be6e13e1db8c.mov

**Comment by sdilk** [comment]
we have the same issue, i think it is if there are 0 or null values.

in the sourcecode the * -1 part is done without checking the input.
[packages/grafana-ui/src/components/uPlot/utils.ts](https://github.com/grafana/grafana/issues/45916#diff-c75a7c9e5ef533accc3027a439b4a6889eae9ebe25f59bd3b61b3bf6b6d97327) line 67

i think a simple input validation should fix it.
