### ISSUE TITLE
[Question] Hook to create org + datasource upon new user signing up?

### ISSUE THREAD

**Issue by abraae** [grafana/grafana#4592]
I have a multitenant scenario where every user has their own, private org, and pulls data from their own, private datasource.

To achieve this I feel I need to gain control just at the point where a new user signs up (after email confirmation is complete), and:
- create an org for them
- create a data source for them in that org

I see we can set auto_assign_org = false, which causes the new user to get their own org, which feels like part of the solution. However the sign up screen then asks the user for their org name, which ideally I'd rather not do since:
a) it won't mean anything to them (in my scenario)
b) if they go with something like "my org" then there's some risk of a name clash

Any hints you could give me would be awesome!

**Comment by torkelo** [comment]
maybe create your own signup page that uses the Grafana api to create the user, org and datasource ?

**Comment by kfitzpatrick** [comment]
@torkelo I'm curious, I can see an API for creating an AdminUser, but not for User. Is this by design?

**Comment by kfitzpatrick** [comment]
Or perhaps I'm misunderstanding and [this function](https://github.com/grafana/grafana/blob/master/pkg/api/admin_users.go#L12) is the method that's called. If so, is this feature just undocumented?

**Comment by torkelo** [comment]
That is not for creating admin users but api handler for admin api to create any yser

**Comment by kfitzpatrick** [comment]
Great, thank you, @torkelo. Is that API documented?

**Comment by torkelo** [comment]
http://docs.grafana.org/http_api/admin/

**Comment by kfitzpatrick** [comment]
@torkelo If i wanted to create a PR for the docs, where would I do that?

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/tree/master/docs
