### ISSUE TITLE
grafana interprets column with year as epoch time

### ISSUE THREAD

**Issue by fedezubo** [grafana/grafana#45923]
**What happened**:
On a fresh install I am using dummy data to test grafana grabbed from [https://www.cybertec-postgresql.com/secret/oil_ext.txt](url) I have created a PSQL12 database containing such data. 

When querying the databse using very basic SQL with grafana and setting the year column as time, I get the years converted to epoch and my data is set to 01-01-1970. but the graph Y correctly shows the different years

By using the query inspector i can see that if i switch the "format data" off, i can get the correct years displayed. 

**What you expected to happen**:

Querying the database and using the year column as time should return the year and not 01-01-1970 

**How to reproduce it (as minimally and precisely as possible)**:

get data in a db from the link above, 
using the time series query the db with 

SELECT
  time AS "time",
  consumption
FROM yourdb
WHERE
  nation = 'USA'

**Environment**:
- Grafana version:  latest
- Data source type & version: psql 12
- OS Grafana is installed on: aws linux 2
- User OS & Browser: win 10 / chrome
- Grafana plugins: n/a
- Others: n/a

![gf1](https://user-images.githubusercontent.com/43973729/155739853-da925cd1-0ca5-41e0-9b74-895be916aff8.jpg)
![gf](https://user-images.githubusercontent.com/43973729/155739855-e9a6124a-a1d7-4c4a-9151-71f745b54dd6.jpg)
![gf2](https://user-images.githubusercontent.com/43973729/155739857-9cd6847c-83d0-4528-a780-b648632fdcd9.jpg)

**Comment by zuchka** [comment]
Thanks for creating this issue, @fedezubo 

I think I have an explanation for this behavior, but first, here is a current workaround:
- use a series of two `convert field data type' transformations.
 - convert your 'time' field to strings, and then convert it again to the time data type. this should trick the graph into working
![CleanShot 2022-02-25 at 16 07 52@2x](https://user-images.githubusercontent.com/37156449/155824914-79e6085c-d5d7-4b16-b434-e1929da83541.png)

check out this dashboard our public instance to see you data graphed:
https://play.grafana.org/d/tmDFfrfnk/only-years-to-timestamp-test?orgId=1&from=-164608463170&to=-20421718744

If you encounter this situation again, I might try a script to convert that field into [a proper ISO 8601](https://www.postgresql.org/docs/9.1/datatype-datetime.html#DATATYPE-DATETIME-DATE-TABLE) timestamp like `1968-01-01`, or try some other strategy that solves the problem on the database side 👍
