### ISSUE TITLE
Grafana oauthPassThru external plugins?

### ISSUE THREAD

**Issue by bradenhs** [grafana/grafana#45938]
Does Grafana `oauthPassThru` only work for datasources embedded within Grafana itself? Looking at the code this appears to be the case. Is there a specific reason for this? The documentation here https://grafana.com/docs/grafana/latest/developers/plugins/add-authentication-for-data-source-plugins/#forward-oauth-identity-for-the-logged-in-user doesn't make any mention of this limitation but the code example it provides isn't compatible with the grafana-plugin-sdk-go module (i.e. there isn't a "Headers" property on the "DataQuery" type so the code example given doesn't even compile).

**Comment by zuchka** [comment]
> the code example it provides isn't compatible with the grafana-plugin-sdk-go module

passing this to the plugin folks for a closer look.

Regarding your larger question, the best place for future questions about plugin development is the plugin-dev category on the forum here.

https://community.grafana.com/c/plugin-development/30

https://community.grafana.com/c/plugin-development/30

**Comment by marefr** [comment]
@bradenhs nicely spotted. That's an unfortunate typo, it should be:

```go
func (ds *dataSource) QueryData(ctx context.Context, req *backend.QueryDataRequest) (*backend.QueryDataResponse, error) {
	token := strings.Fields(req.Headers.Get("Authorization"))
	var (
		tokenType = token[0]
		accessToken = token[1]
        )

        // ...
    }
}
```

Whenever in doubt, you can always navigate via [Grafana plugin SDK for Go](https://grafana.com/docs/grafana/latest/developers/plugins/backend/grafana-plugin-sdk-for-go/) to [grafana-plugin-sdk-go Go package references](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go) and then navigate to [backend package and the QueryDataRequest](https://pkg.go.dev/github.com/grafana/grafana-plugin-sdk-go@v0.127.0/backend#QueryDataRequest).

I'm going to open a PR to resolve this typo.

**Comment by bradenhs** [comment]
Unfortunately I don't think this fix works.

```
token := strings.Fields(req.Headers["Authorization"])
```

![image](https://user-images.githubusercontent.com/22484684/156229921-3df7b91a-3aff-4a57-ba28-1b4c143a6aad.png)

`strings.Fields` expects a string not an array of strings which is the type of `req.Headers["Authorization"]`

Regardless, of the specifics on the docs having confirmed that this is indeed intended to work for external plugins the real issue is that this "Authorization" header doesn't appear to be populated despite having the oauthPassThru setting in the data source instance settings. I could try to create a minimal repo if that's useful?

**Comment by marefr** [comment]
@bradenhs very sorry, my fault. I'm pretty sure I tested things, but apparently not. I'll look into fixing the documentation. 

> Regardless, of the specifics on the docs having confirmed that this is indeed intended to work for external plugins the real issue is that this "Authorization" header doesn't appear to be populated despite having the oauthPassThru setting in the data source instance settings. I could try to create a minimal repo if that's useful?

Hmm, you're authenticating with for example Azure OAuth when testing this? A minimal reproduction would be helpful or at least a list of reproduction steps, thanks.

**Comment by bradenhs** [comment]
No worries @marefr! I appreciate your help. I'll try to get a repro together today or tomorrow.

**Comment by marefr** [comment]
@bradenhs have verified my latest documentation and it works as expected for me. I'm using Go version 1.17, but not sure that makes any difference. Make sure you compile your code in case your editor given you incorrect feedback. 

I've also tested setting the `oauthPassThru: true` for my test datasource and it works as expected using the following code and me being signed in with Grafana.com OAuth:
```go
package plugin

import (
	"context"
	"strings"

	"github.com/grafana/grafana-plugin-sdk-go/backend"
)

func handleQuery(ctx context.Context, req *backend.QueryDataRequest) (*backend.QueryDataResponse, error) {
	token := strings.Fields(req.Headers["Authorization"])
	backend.Logger.Info("handleQuery", "tokenType", token[0], "accessToken", token[1])
	...
	return resp, nil
```

Getting the following log in Grafana:
`INFO[03-02|19:58:49] handleQuery                       logger=plugin.grafana-test-datasource accessToken="<access token>" tokenType=Bearer`

I should add that I did use the cd3fb8e8321259c41d566b7fda394dd4b8c61398 from main branch when testing above.

**Comment by marefr** [comment]
In addition, if your token is an ID token you need to read from the `X-ID-Token` header instead of `Authorization` - this should probably be added to our documentation.

**Comment by bradenhs** [comment]
Okay I believe unearthed the issue here.

While the QueryData function in a datasource backend will get the authorization header the CallResource function does not. I verified this with both Azure and GitHub OAuth providers. (Also I don't think you have access at all to headers in the CheckHealth function so accessing the auth header there also won't be possible). I can make a repository for you to verify this against if that'd be helpful (I already have it mostly ready to go). Or if you're able to validate this yourself that works too. Provided you are able to validate this on your end and confirm the issue I'd be happy to make a PR against Grafana to add the auth header to requests processed by the CallResource function.

**Comment by marefr** [comment]
> I'd be happy to make a PR against Grafana to add the auth header to requests processed by the CallResource function

Thanks. Feel free to open a PR and we'll happily review it. Regarding CheckHealth you're right and that might be something we need to address, [protocol](https://github.com/grafana/grafana-plugin-sdk-go/blob/06ad448ce99f902b05c1d90be4dc0d917b05b83f/proto/backend.proto#L158) needs changes as a first step.
