### ISSUE TITLE
Graphite functions are not available in 8.4.2

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#45948]
**What happened**:

When adding series from a Graphite data source the function list is not showing

**What you expected to happen**:

I expect that it is showing as it was showing on 8.4.1

**How to reproduce it (as minimally and precisely as possible)**:

1. Run grafana 8.4.2
2. Add graphite data source
3. Try adding a function to series

How it looks:

v8.4.1:

![image](https://user-images.githubusercontent.com/8693064/155890925-0be997b2-7edd-40c8-954e-736d3d2a06ef.png)

v8.4.2:

![image](https://user-images.githubusercontent.com/8693064/155890879-d6742cd2-ff7d-4ba7-857b-5a95deedc7c0.png)

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: graphite
- OS Grafana is installed on: docker
- User OS & Browser: macOS / chrome

**Comment by ashharrison90** [comment]
i can't repro this locally in main:
![image](https://user-images.githubusercontent.com/20999846/155978136-7a06ad89-a5a7-484f-a2d5-e5add55093ba.png)

although there is a suspicious network error:
![image](https://user-images.githubusercontent.com/20999846/155978054-fcd977a0-a0df-4106-bd52-4e25b81ded1d.png)

@nikobearrr are there any errors in your browser console/network tab? (right click -> inspect -> console/network)

**Comment by sjwk** [comment]
I'm seeing what appears to be the same issue.  Running Grafana 8.4.2 in a docker container where it had updated from previous versions, following the 'latest' tag.
As well as the blank box in 'add function', I'm seeing a warning on existing functions on saved dashboards, although the existing saved functions appear to work:
![image](https://user-images.githubusercontent.com/9693896/155985802-f1c0ddd8-aa99-4d4b-b8e2-862126c89c3e.png)
 
Looking in the console on my browser, I see an error:
![image](https://user-images.githubusercontent.com/9693896/155986004-0e7f7380-2d0a-44fe-9bcb-6a5d5675b3b4.png)

**Comment by sjwk** [comment]
@ashharrison90 @nikobearrr 
Having looked at the JSON being pulled, I believe the issue is here, specifically the unquoted Infinity near the bottom - at least that's where the unexpected 'I' it references is:

    "interpolate": {
        "name": "interpolate",
        "function": "interpolate(seriesList, limit=inf)",
        "description": "Takes one metric or a wildcard seriesList, and optionally a limit to the number of 'None' values to skip over.\nContinues the line with the last received value when gaps ('None' values) appear in your data, rather than breaking your line.\n\nExample:\n\n.. code-block:: none\n\n  &target=interpolate(Server01.connections.handled)\n  &target=interpolate(Server01.connections.handled, 10)",
        "module": "graphite.render.functions",
        "group": "Transform",
        "params": [
            {
                "name": "seriesList",
                "type": "seriesList",
                "required": true
            },
            {
                "name": "limit",
                "type": "intOrInf",
                "default": Infinity
            }
        ]
    }

**Comment by Roguelazer** [comment]
This is still broken in 8.4.3

**Comment by reyjrar** [comment]
Can confirm, this is broken for me.. I have multiple Graphite Datasources and only one is working which is odd.. Yes, I saved all the Version/Type data and they are right. Creating a new graphite Datasource causes the failure this as well. It was working in 8.3.6.

@ashharrison90 Try creating more than one Graphite datasources to see if the problem occurs.

**Comment by sjwk** [comment]
> Can confirm, this is broken for me.. I have multiple Graphite Datasources and only one is working which is odd.. Yes, I saved all the Version/Type data and they are right. Creating a new graphite Datasource causes the failure this as well. It was working in 8.3.6.

I do have two graphite datasources too, just in case that's the missing link.  Although both of mine are broken.  The graphite servers are both running as containers also, running from the latest tag.  In a brief look I couldn't work out where the apparently faulty JSON referenced above came from, whether it was generated from/by the graphite server itself (and therefore whether the problem lies with graphite rather than grafana).

**Comment by reyjrar** [comment]
I am running Grafana OSS 8.4.2 from the official RPMs.

**Comment by bobemoe** [comment]
Seeing the same here running in docker. Updated from 8.3.6 to 8.4.3, graphite functions stopped working, stepped back to 8.4.2 (still broken) and then 8.4.1 where they started working again.

I only have 1 Graphite source, and also a MySQL source (which is not used in this query)

**Comment by bobemoe** [comment]
..when I say "functions" working or not, I mean "function picker".

I also see the "Unexpected 'I'" error, but also see this on 8.4.1 when function picker works, so not sure that's related?

**Comment by bobemoe** [comment]
I have confirmed that it is indeed the above JSON error that is causing this issue. 

This is a bug in Graphite. I have added a PR on the graphite-project repo that should fix this.

I'm not sure why we still see the error is 8.4.1 but the function picker works.  Maybe there was a workaround in place that got removed?!

**Comment by Nhyalgotphores** [comment]
Apache reverse proxy workaround

```
  <Location /api/datasources/proxy/2/functions>
    AddOutputFilterByType INFLATE;SUBSTITUTE;DEFLATE application/json
    Substitute "s/\ Infinity\}/\ \"Infinity\"\}/"
  </Location>
```

**Comment by delfuego** [comment]
@ifrost I presume that Grafana will also include the graphite bug fix that uncovered this need to fix the hardcoded-function-list fallback? (I think I saw that graphite has fixed that bug now.)

**Comment by mirelia** [comment]
I've managed to fix this ( Grafana 8.8.4 ) by changing 

Datasource ---> Grafite ---> Graphite version 

from 1.1.x  to 1.0.x

<img width="520" alt="Screenshot 2022-03-21 at 12 40 56" src="https://user-images.githubusercontent.com/73648516/159245415-f09619f1-b5af-4c6a-b8d0-0f834e36731b.png">

**Comment by dbidwell94** [comment]
![image](https://user-images.githubusercontent.com/25497078/159386894-a0ba3825-562c-4329-9eda-a09d7e078bfe.png)

I can confirm it's no longer working for me as well. Running Grafana in a docker container. It got updated and broke the functions dropdown. Interestingly enough, however, the graphs still work.

**Comment by dbidwell94** [comment]
And to be clear: I'm running Grafana @ 8.4.4

**Comment by prwood** [comment]
Can confirm I'm having this issue with Grafana 8.4.4 (fcfb01faeb) pulled from grafana/grafana:latest docker container. Graphite functions work correctly but Grafana's picker shows errors on existing queries, as seen in the screenshot here, or just shows blanks when selecting functions from the picker while creating new queries.

![Screen Shot 2022-03-29 at 10 55 43 AM](https://user-images.githubusercontent.com/20217503/160641216-ca1cc644-f401-4084-bebf-fe37afab58be.png)
