### ISSUE TITLE
Fields Name on Pie chart table

### ISSUE THREAD

**Issue by Himanshu-pupneja** [grafana/grafana#4595]
Hi @torkelo ,

PieChart plugin looks good, Is it possible to add field name above table values?
Its so confusing right now what values the pie chart and tables showing.

Attached is the snapshot of the same.

![image](https://cloud.githubusercontent.com/assets/15123322/14342497/99bc9c8a-fcb7-11e5-8fd7-8907c7261b44.png)

Thanks in advance!!

Ex
* What grafana version are you using? 3.0 beta2
* What datasource are you using? graphite
* What OS are you running grafana on? RHEL6.5

**Comment by bergquist** [comment]
@Himanshu-pupneja Thank you for helping us making grafana even better. But this issue belongs in https://github.com/grafana/piechart-panel Please reopen the issue in that repository. 

Thanks you!

**Comment by Himanshu-pupneja** [comment]
Hi @bergquist ,

Thanks for your response,
I found this plugin on grafana.net only that why i asked here.

can you or @torkelo guide me the other repo where i should ask this?

Thanks!

**Comment by Himanshu-pupneja** [comment]
Please ignore the last comment

**Comment by bergquist** [comment]
@Himanshu-pupneja Thanks you for describing the way you found it. I will add a note about this ins the issue template :)
