### ISSUE TITLE
BUG: "Reduce" expression produces "NaN" when part of (not all) input is NoData

### ISSUE THREAD

**Issue by hamlet-lee** [grafana/grafana#45952]
**What happened**:
In alert rule。When query response have some "Data" and some "NoData". "Reduce" expression "min/max/mean/sum" produces NaN。

for example，for Reduce (min) 
input: 3, 5, NoData, 2
reduce(min) actual output: NaN

**What you expected to happen**:
When the series has some data, it should ignore NoData points.
for example，for Reduce (min) 
input: 3, 5, NoData, 2
reduce(min) expected output: 2

**How to reproduce it (as minimally and precisely as possible)**:
1) use push-gateway or other way to create a metric (e.g. test_eval), value can be 1 or 2 in prometheus (at t1), and clear it after some minutes (at t2). 
2) create alert rule.  
Add Prometheus query "P", cover the time range plus some time before. (e.g.:  "now - 1 week" to "now") - "see snapshot 1"

3) create an expr "Reduce"，named "R" - see "snapshot 1"
4) create an expr "Math", named "M" - see "snapshot 1"
5) click "Run queries"
6) define alert conditions on "M", click "Preview alerts"
You can see State is "Alerting"。And the value of "R" and "M" are both NaN.

Since the minimum of metric in the time range is 1. **This is a false alarm.**  
In my opinion the bug come from the way "Reduce" dealing with input data series with some "Data" and some "NoData"

snapshot 1:
![image](https://user-images.githubusercontent.com/12079531/155934284-b9142c24-7014-4755-9dc6-1ecfb3c139ff.png)

snapshot 2:
![image](https://user-images.githubusercontent.com/12079531/155934641-62062216-7da6-4a28-babd-b5b9502d62d1.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment]
hi @hamlet-lee 👋 

believe this has been fixed in 8.4.0. we've added a new mode option which allows you to specify what you want to do with null/`NaN` values:

![image](https://user-images.githubusercontent.com/20999846/155987113-d73ff4f7-de7c-4447-8ff3-3bdcd0d13f18.png)

hope that helps! 😄

**Comment by hamlet-lee** [comment]
many thanks!

**Comment by hamlet-lee** [comment]
I can confirm 8.4.2 has this feature.  And you may need ctrl+f5 to refresh to see the new feature.
@ashharrison90 I cannot find this feature description in any of following document:

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/

https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-0-beta1/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-1/
https://grafana.com/docs/grafana/latest/release-notes/release-notes-8-4-2/

would someone add this to the doc?
