### ISSUE TITLE
[bug]/ Annotation in table panel are not clickable anymore

### ISSUE THREAD

**Issue by floppy84** [grafana/grafana#4596]
* What grafana version are you using? grafana beta 3
* What datasource are you using? graphite
* What OS are you running grafana on? centos 6

Ok Now i can see my events in table since last fix.

But in grafana 2.6 the html link was interpreted and clickable:

Now i can't do this anymore

![image](https://cloud.githubusercontent.com/assets/3499449/14343737/31e2eb8c-fca3-11e5-809a-40768468dd30.png)

In previous 2.6 :: i got ::

![image](https://cloud.githubusercontent.com/assets/3499449/14343764/5996ec28-fca3-11e5-81ed-205a6d16377b.png)

**Comment by bergquist** [comment]
Due to security reasons we started html escape all content in the table panel. https://github.com/grafana/grafana/issues/3673 

But I can see the need for something that you did with table panel.

**Comment by torkelo** [comment]
@bergquist we should use the angular $sce sanitize service, that is what the pop over uses
