### ISSUE TITLE
Getting information about a repo's test coverage from Drone builds

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#45960]
### Discussed in https://github.com/grafana/grafana/discussions/45959

and in Slack: https://raintank-corp.slack.com/archives/C01LVB0CYTW/p1645804354932519 with @dsotirakis 

<div type='discussions-op-text'>

<sup>Originally posted by **yaelleC** February 28, 2022</sup>
_This is a Feature Request for the release team_

## Background
- I have a dashboard that shows test coverage for our team's repos: https://ops.grafana.net/d/3kxjo4fnz/cloud-datasource-unit-test-coverage?orgId=1&from=now-7d&to=now

- For now, most steps about data collection are manual (using a google sheet as datasource). 

- Drone build logs have information about test coverage (at least for external plugins - see bottom of previous dashboard). I would love to be able to use that as input for the dashboard

## Request/Questions

- [ ] Could we emit a metric from the drone build instead of scrapping the logs? Getting a new datapoint every time a build passes on the main branch would be ideal.
- [ ] Could we have that information (from metric or logs) for `grafana/grafana` too? So far I have not been able to find it
</div>

**Comment by summerwollin** [comment]
Closing as stale
