### ISSUE TITLE
When looking at the "What’s new in Grafana v8.4" docs page, it says this is a future version

### ISSUE THREAD

**Issue by nikobearrr** [grafana/grafana#45975]
**What happened**:

When you go to https://grafana.com/docs/grafana/next/whatsnew/whats-new-in-v8-4/ there is text saying

```
This is documentation for the next version of Grafana. For the latest stable release, go to the [latest version](https://grafana.com/docs/grafana/latest/)[](https://grafana.com/docs/grafana/next/).
```

![image](https://user-images.githubusercontent.com/8693064/156011236-d6638e55-35f3-400e-ac1f-7c9965eebe9b.png)

Actually it does not matter which version you go to, e.g. What's new in Grafana v5.0: https://grafana.com/docs/grafana/next/whatsnew/whats-new-in-v5-0/ also shows it

![image](https://user-images.githubusercontent.com/8693064/156011630-ab1f5967-a7be-4b6a-96c2-e2052ffb5a32.png)

**Comment by GrafanaWriter** [comment]
I'm unable to replicate this using:

Browser: Chrome
MacOS: 12.0.1

Can you confirm that it's fixed or still present? Thank you.

**Comment by nikobearrr** [comment]
@GrafanaWriter yes it is still present. I tried to do it on:
- Chrome
- Chrome incognito
- Safari

Details:
macOS: 12.2.1 (21D62)
Chrome: Version 99.0.4844.51 (Official Build) (x86_64)
Safari: Version 15.3 (17612.4.9.1.8)

**Comment by GrafanaWriter** [comment]
Ok. Thanks for testing. That's actually correct. Note the `/next` in the URL, which points to the future version. The correct URL is `/latest`, which works as expected.

That being said, once we've published `/latest`, the URL should route there regardless. 

@robbymilo - any automated adjustment we can make here?

**Comment by robbymilo** [comment]
> @robbymilo - any automated adjustment we can make here?

The problem is all "What's new" pages are included in every version: https://github.com/grafana/grafana/tree/main/docs/sources/whatsnew

Ideally the previous version's file would be deleted when a new version branch is cut.

**Comment by GrafanaWriter** [comment]
Thanks for the context, @robbymilo. We can improve this, for sure. 

@jdbaldry - can we please track this for resolution?

**Comment by achatterjee-grafana** [comment]
This is not a bug. I do agree with @robbymilo's comment/suggestion.

**Comment by GrafanaWriter** [comment]
Closing as we have implemented new text that explains to users that old versions of content are specific to that version.
