### ISSUE TITLE
Bug annotations-query-ctrl-grafana

### ISSUE THREAD

**Issue by luluprat** [grafana/grafana#4598]
* What grafana version are you using?
3.0.0  beta
* What datasource are you using?
opentsdb & elasticsearch
* What OS are you running grafana on?
ubuntu

hello
i cant add annotation it give me this error
Plugin Error
Failed to find exported plugin component for annotations-query-ctrl-grafana

**Comment by utkarshcmu** [comment]
Might be related to https://github.com/grafana/grafana/issues/4387

**Comment by torkelo** [comment]
Do you have a datasource that supports annotations? Do you have a datasource makes as default?
