### ISSUE TITLE
Explore: Improve UI when Explore returns no results

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#45998]
**What happened**:

A query that returns nothing in Explore is just an empty page, nothing that really indicates the query was executed and that there were no errors, just no data returned.

![image](https://user-images.githubusercontent.com/745532/156125294-b1f8e011-5f43-4ed9-9b5a-91e0d9f8b610.png)

**What you expected to happen**:

Display somehow that the query did not return any data.

We could use something similar to what we have in Dashboards:

<img width="1121" alt="Screen Shot 2022-03-01 at 08 38 23" src="https://user-images.githubusercontent.com/745532/156125599-78fc6e32-d95c-43c5-b45c-b642ab1cf138.png">

or 

![image](https://user-images.githubusercontent.com/745532/156126197-d35eab72-4f95-47fc-b068-df21d3823921.png)

**How to reproduce it (as minimally and precisely as possible)**:

Run a query that returns no results in Explore (e.g. Prometheus for non-existing labels).

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.0
- Data source type & version: any
- OS Grafana is installed on: any
- User OS & Browser: any
- Grafana plugins: n/a
- Others: n/a

**Comment by ifrost** [comment]
@grafana/grafana-labs-ux-design how do you think it should be tackled?

**Comment by radiorental** [comment]
Cross checked with the UX team on slack.  Thumbs up to "No Data" as presented above.

**Comment by PeterKwesiAnsah** [comment]
I  would love to work on this..can you please assign it to me

**Comment by sliceking** [comment]
Same, I would like a chance to work on this 😄
