### ISSUE TITLE
Dashboard link does not always reflect current time range.

### ISSUE THREAD

**Issue by skysense-victor** [grafana/grafana#46004]
**What happened**:
My dashboard link that has "include current time range" and "open link in new tab" enabled does not update the time range content if the time range is changed in the dashboard more than once. After I press CTRL+R or F5 to refresh the page the correct time range is once again reflected in the dashboard link. Until it is changed more than once.

**What you expected to happen**:
I expect the time range content in the dashboard link to always reflect the time range selected in the dashboard, no matter how many times it is changed.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new empty dashboard.
2. Go to dashboard settings->Links
3. Add a dashboard link. Set type to link.
4. Set URL to http://127.0.0.1/dummy
5. Check the box "include current time range" and "open link in new tab". Save the dashboard.
6. Press the link in the dashboard. A new tab should pop up with URL containing correct time range (ie "from=now-6h&to=now").
7. Change the time range and press the link again. A new tab should pop up with URL containing correct time range (ie "from=now-3h&to=now").
8. Change the time range and press the link again. A new tab should pop up with URL containing wrong time range. The range selected from step 7 is till included in the link URL.

**Environment**:
- Grafana version: v8.2.3
- Data source type & version: No data source needed.
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: windows 10 (google chrome) 
					 Ubuntu 18.04 (google chrome) 
					 Ubuntu 20.04 (Chrome and firefox)

**Comment by ashharrison90** [comment]
hi @skysense-victor 👋 

this has been fixed in a newer version of grafana! 🚀 
can you try upgrading to v8.4.2?

thanks! 😄
