### ISSUE TITLE
Datalink for Status History and State Timeline not working

### ISSUE THREAD

**Issue by SreeniMurthy-Reviewer** [grafana/grafana#46022]
Datalink for Status History and State Timeline is not working.

Steps to reproduce:

1) Create a Datalink for a Status History or State Timeline Visualizations.
2) Click on the point in the Status History or State Timeline Visualizations.

Expected Result:
1) The link should navigate to the location as specified in the Data link setting

Actual Result:
1) It doesn't navigate at all.

Observation:
This works fine for the table based visualization.

**Environment**:
- Grafana version: 8.3.4
- Data source type & version: Influx DB 1.8
- OS Grafana is installed on: OSS
- User OS & Browser: Windows 10/Chrome 98
- Grafana plugins: NA
- Others: NA

**Comment by ashharrison90** [comment]
hi @SreeniMurthy-Reviewer 👋 

can confirm this doesn't work in main for either the status history or state timeline visualizations
not sure if this is a bug or feature request. will leave it up to @grafana/grafana-bi-squad to decide 😄 

thanks!

**Comment by SreeniMurthy-Reviewer** [comment]
Hi @ashharrison90 

This doesn't work in the main itself. I have used the installer from 8.3.4 release.

Issue is same as: https://community.grafana.com/t/data-links-on-status-history-not-working-8-1-1/51887/4

I checked the release notes for the all the builds post 8.3.4 build but didn't find anything mentioned.

Thanks!

**Comment by zoltanbedi** [comment]
This feature is not supported yet and we already have 2 separated feature requests for it.
https://github.com/grafana/grafana/discussions/38318
https://github.com/grafana/grafana/discussions/46026
