### ISSUE TITLE
[Bug] Template variables in annotations are not working (InfluxDB)

### ISSUE THREAD

**Issue by katirena** [grafana/grafana#4602]
* grafana version: 3.0.0-beta31460024165
* Datasource: InfluxDB (0.10)
* OS: Debian Jessie

I created a new template variable with a name "host":
`show tag values FROM "something" with key = "host"`

Then I created a new annotation:
`select value from "something" where host =~ /$host$/ and $timeFilter`

When I enable it, I can see from the influxdb logs that it will be formated incorrectrly:
`SELECT value FROM testdb."default".something WHERE host =~ /{host1,host2}$/ AND time > now() - 1d`

When I use the template with a WHERE condition on a graph, it it is formated correctrly. From the influxdb log:
`SELECT value FROM testdb."default".something WHERE host =~ /host1|host2$/ AND time > now() - 1d`

**Comment by torkelo** [comment]
thanks for reporting this! will be fixed asap

**Comment by descrepes** [comment]
Hi,

Got the same issue with the latest build for debian with ES as datasource in annotations.
It only happen when selecting multi values:
`
{
"fields":["date","_source"],
"query":{
  "filtered":{
    "query":{
      "bool":{
        "should":[{
          "query_string":{
            "query":"host:/{host1,host2}/"}
          }]
      }
    },
    "filter":{
      "bool":{
        "must":[{
          "range":{
            "date":{
              "from":1460117264973,"to":1460119064973,"format":"epoch_millis"
            }
          }
        }]
      }
    }
  }
},
"size":10000
}
`

Regards.

**Comment by torkelo** [comment]
thanks for reporting this fixed!
