### ISSUE TITLE
AnnotationQueryRunner failed following upgrade to 8.3.6

### ISSUE THREAD

**Issue by jbradleynh** [grafana/grafana#46033]
**What happened**:
We performed an upgrade from Grafana 8.2.7 -> 8.3.6

Following this we found that all annotations requests are being met with a 400 bad request.

**What you expected to happen**:

Upgrade would not have a change in behavior which breaks annotations requests. 

**How to reproduce it (as minimally and precisely as possible)**:
Any attempt to  load a new annotation will be redirected to authentication endpoint and fails

![Screen Shot 2022-03-01 at 9 47 04 AM](https://user-images.githubusercontent.com/49180168/156190944-45fff57b-ddf1-4515-9072-8aba119394f6.png)

**Anything else we need to know?**:
This appears to be impacting only annotations calls to prometheus and bigquery datasources, standard visualization panels renders without issue. 

In our environment we run Grafana behind a reverse proxy which handles oauth, and all data sources are configured via provisioning yaml like the following:
```datasources:
- name: ABC123
  type: prometheus
  access: direct
  url: https://observability.example.com/ABC123
  editable: false
```

It appears that direct datasources calls are no longer passing auth cookie, and attempting to modify data source with jsonData to set `keepCookies` option still fails on POST to https://observability.example.com/grafana/api/ds/query

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: Prometheus, doitintl-bigquery-datasource 2.0.1
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: Mac OS 12.2.1, Chrome and Safari

**Comment by jbradleynh** [comment]
appears related behavior found in https://github.com/grafana/grafana/issues/44250

**Comment by sanchomuzax** [comment]
Similar prolem after the v8.5.1 (61fe4a1859) update.

Our all org. dashboards in org = 1 report this now. My screenshots show that this is a custom dasboard created on 2022-01-15 where I did not add an Annotation setting.

![image](https://user-images.githubusercontent.com/2911588/166956466-b065dfe7-2855-49e6-b47d-6ad342cbded7.png)
![image](https://user-images.githubusercontent.com/2911588/166956485-fd7d7c21-39af-4e30-ba3a-68e2a365d064.png)
![image](https://user-images.githubusercontent.com/2911588/166956505-751a3ee7-cd1f-4b57-8ff5-ec834e7d1fe0.png)

**Comment by ajithcyriac** [comment]
Just noticed this issue with V9.0.6 version also.

![image](https://user-images.githubusercontent.com/40192659/192900149-3329883f-e9d4-49dc-8f86-8a951c691ecd.png)

**Comment by fzyzcjy** [comment]
Same issue here, is there any updates?

**Comment by danielthedm** [comment]
This is no longer a major support version so we are closing this issue.
