### ISSUE TITLE
[Bug] Templating in CENT OS influxdb for grafana build 3.0 breaks, while query in grafana 2.6 works

### ISSUE THREAD

**Issue by ivwhatthe** [grafana/grafana#4603]
In Grafana 2.6 stable build the query works with templating and displays graph properly:
In editor mode under Metrics tab of a graph:
SELECT "value" FROM "$measurement" GROUP BY "source"

On the most recent build:
Redhat/Centos (64bit) .rpm package	grafana-3.0.0-beta31460041852.x86_64.rpm	4/7/2016, 11:15:09 AM

In 3.0, the graph no longer displays the data.
In editor mode under Metrics tab of a graph:
SELECT "value" FROM "$measurement" GROUP BY "source"

error of this format in 3.0 grafana Inspector query: ( the "\." seems to be causing problems, hardcoding the measurement name works. (as in "data.jdbc.pool.TotalConnections" rather than "$measurement")

The error query:
q
	SELECT "value" FROM "data\.jdbc\.pool\.TotalConnections" GROUP BY "source"

Response:
{
  "message": "Unable to load datasource meta data"
}

**Comment by torkelo** [comment]
so when you have `SELECT "value" FROM "$measurement" GROUP BY "source"` as the query, can tou check chrome dev tools, what is the query sent by grafana in this case that is causing the error?

**Comment by ivwhatthe** [comment]
boot.7911bd75.js:36 GET http://<host>:3000/api/datasources/proxy/2/query?db=db&epoch=m…ta%5C.jdbc%5C.pool%5C.TotalConnections%22+GROUP+BY+%22source%22  401 (Unauthorized)

**Comment by torkelo** [comment]
can you go into the datasource list and find you datasource and run "Test connection" ? what database have you configured grafana to use (for users and dashboards etc), sqlite3 (default) or someithing else? 

sounds related to some other issues, like https://github.com/grafana/grafana/issues/3323

Not sure what the cause is, corrupt database or something. Try removing the datasource and re-add it again.

**Comment by ivwhatthe** [comment]
http://host:3000/api/datasources/proxy/5/query?db=db&epoch=ms&q=SELECT+%22value%22+FROM+%22data%5C.jdbc%5C.pool%5C.TotalConnections%22+GROUP+BY+%22source%22

message
:
"InfluxDB Error Response: error parsing query: found \., expected identifier at line 1, char 27"

Looks like I accidentally gave the wrong error message in my initial post.

Test connection worked and I tried removing the datasource and re-adding it. The problem persisted.

**Comment by ivwhatthe** [comment]
There is a \\ before the . in the error message, but it has been stripped out of the post. So it should be:

"InfluxDB Error Response: error parsing query: found \\., expected identifier at line 1, char 27"

**Comment by ivwhatthe** [comment]
%5C is \\ in URL encoding, which is found in the query - so I think the issue is related to that.

**Comment by torkelo** [comment]
You you show me the variable definition (in the dashboard json). and also a screenshot for the template variable options ?

Sounds like the template variable has All value or Multi value options enabled. That means that Grafan will try to regex encode it (so it works when many values are selected, InfluxDB only support many matching when using regex). 

So you might be able to solve this issue by disabling All value or Multi value selection.

**Comment by ivwhatthe** [comment]
Unfortunately, the disabling All or Multi value did not fix the issue.

I attached two screenshots of the error.
 
Thanks.

Here is the JSON:
{
  "id": 5,
  "title": "Grafana 3.1.0 5/24/16 latest",
  "originalTitle": "Grafana 3.1.0 5/24/16 latest",
  "tags": [],
  "style": "dark",
  "timezone": "browser",
  "editable": true,
  "hideControls": false,
  "sharedCrosshair": false,
  "rows": [
    {
      "collapse": false,
      "editable": true,
      "height": "250px",
      "panels": [
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 1,
          "isNew": true,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 2,
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "jvm.memory.heap.used",
              "policy": "default",
              "query": "SELECT mean(\"value\"), MOVING_AVERAGE(mean(\"value\"),10) FROM \"cpu.os.load\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
              "rawQuery": true,
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  }
                ]
              ],
              "tags": []
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "cpu.os.load, no $ measurement used",
          "tooltip": {
            "msResolution": true,
            "ordering": "alphabetical",
            "shared": true,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "show": true
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "links": []
        },
        {
          "aliasColors": {},
          "bars": false,
          "datasource": null,
          "editable": true,
          "error": false,
          "fill": 1,
          "grid": {
            "threshold1": null,
            "threshold1Color": "rgba(216, 200, 27, 0.27)",
            "threshold2": null,
            "threshold2Color": "rgba(234, 112, 112, 0.22)"
          },
          "id": 3,
          "isNew": true,
          "legend": {
            "avg": false,
            "current": false,
            "max": false,
            "min": false,
            "show": true,
            "total": false,
            "values": false
          },
          "lines": true,
          "linewidth": 2,
          "nullPointMode": "connected",
          "percentage": false,
          "pointradius": 5,
          "points": false,
          "renderer": "flot",
          "seriesOverrides": [],
          "span": 6,
          "stack": false,
          "steppedLine": false,
          "targets": [
            {
              "dsType": "influxdb",
              "groupBy": [
                {
                  "params": [
                    "$interval"
                  ],
                  "type": "time"
                },
                {
                  "params": [
                    "null"
                  ],
                  "type": "fill"
                }
              ],
              "measurement": "jvm.memory.heap.used",
              "policy": "default",
              "query": "SELECT mean(\"value\"), MOVING_AVERAGE(mean(\"value\"),10) FROM \"$m\" WHERE $timeFilter GROUP BY time($interval) fill(null)",
              "rawQuery": true,
              "refId": "A",
              "resultFormat": "time_series",
              "select": [
                [
                  {
                    "params": [
                      "value"
                    ],
                    "type": "field"
                  },
                  {
                    "params": [],
                    "type": "mean"
                  }
                ]
              ],
              "tags": []
            }
          ],
          "timeFrom": null,
          "timeShift": null,
          "title": "Same as previous graph but \"$ measurement\" used",
          "tooltip": {
            "msResolution": true,
            "ordering": "alphabetical",
            "shared": true,
            "value_type": "cumulative"
          },
          "type": "graph",
          "xaxis": {
            "show": true
          },
          "yaxes": [
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            },
            {
              "format": "short",
              "label": null,
              "logBase": 1,
              "max": null,
              "min": null,
              "show": true
            }
          ],
          "links": []
        }
      ],
      "title": "Row"
    }
  ],
  "time": {
    "from": "now-6h",
    "to": "now"
  },
  "timepicker": {
    "refresh_intervals": [
      "5s",
      "10s",
      "30s",
      "1m",
      "5m",
      "15m",
      "30m",
      "1h",
      "2h",
      "1d"
    ],
    "time_options": [
      "5m",
      "15m",
      "1h",
      "6h",
      "12h",
      "24h",
      "2d",
      "7d",
      "30d"
    ]
  },
  "templating": {
    "list": [
      {
        "current": {
          "value": [
            "cpu.os.info"
          ],
          "text": "cpu.os.info"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "m",
        "options": [
          {
            "text": "cpu",
            "value": "cpu",
            "selected": false
          },
          {
            "text": "cpu.os.info",
            "value": "cpu.os.info",
            "selected": true
          },
          {
            "text": "cpu.os.load",
            "value": "cpu.os.load",
            "selected": false
          },
          {
            "text": "jvm.memory.heap.used",
            "value": "jvm.memory.heap.used",
            "selected": false
          }
        ],
        "query": "SHOW MEASUREMENTS",
        "refresh": 0,
        "type": "query",
        "useTags": false
      },
      {
        "current": {
          "text": "1m",
          "value": "1m"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "summarize",
        "options": [
          {
            "selected": true,
            "text": "1m",
            "value": "1m"
          },
          {
            "selected": false,
            "text": "10m",
            "value": "10m"
          },
          {
            "selected": false,
            "text": "30m",
            "value": "30m"
          },
          {
            "selected": false,
            "text": "1h",
            "value": "1h"
          },
          {
            "selected": false,
            "text": "3h",
            "value": "3h"
          },
          {
            "selected": false,
            "text": "6h",
            "value": "6h"
          },
          {
            "selected": false,
            "text": "12h",
            "value": "12h"
          },
          {
            "selected": false,
            "text": "1d",
            "value": "1d"
          },
          {
            "selected": false,
            "text": "7d",
            "value": "7d"
          },
          {
            "selected": false,
            "text": "14d",
            "value": "14d"
          },
          {
            "selected": false,
            "text": "30d",
            "value": "30d"
          }
        ],
        "query": "1m,10m,30m,1h,3h,6h,12h,1d,7d,14d,30d",
        "refresh": 0,
        "type": "interval"
      },
      {
        "current": {
          "text": "some.source",
          "value": "some.source"
        },
        "datasource": null,
        "hide": 0,
        "includeAll": false,
        "multi": false,
        "name": "source",
        "options": [
          {
            "text": "some.source",
            "value": "some.source",
            "selected": true
          },
          {
            "text": "other.source",
            "value": "other.source",
            "selected": false
          }
        ],
        "query": "SHOW TAG VALUES FROM \"cpu.os.load\" WITH KEY = \"source\"",
        "refresh": 0,
        "regex": "",
        "type": "query"
      }
    ]
  },
  "annotations": {
    "list": []
  },
  "schemaVersion": 12,
  "version": 12,
  "links": []
}

![image](https://cloud.githubusercontent.com/assets/18332155/15522262/3d31b480-21df-11e6-8679-1eb920dc8d1d.png)

![image](https://cloud.githubusercontent.com/assets/18332155/15522306/90daee44-21df-11e6-83ee-89a729d033af.png)

**Comment by ivwhatthe** [comment]
using #4548 format allowed it to work.

[Bug] Grafana 3.0.0-beta1 template variable influxdb #4548
