### ISSUE TITLE
Missing log level labels in Explore - histogram in Grafana v8.4.0+

### ISSUE THREAD

**Issue by pulecp** [grafana/grafana#46040]
**What happened**:

Log levels are missing in Explore - Log volume/Logs in histograms in Grafana v8.4.0. All logs are gray, labeled as `Logs`. The log levels work fine in the previous version 8.3.7, I see `info` and `error` labels correctly. See the attached pictures.

**Grafana v8.3.7**
![image](https://user-images.githubusercontent.com/2362780/156201323-b2739ce5-a3c5-49e8-9a0b-dee783afbfc0.png)

**Grafana v8.4.0**
![image](https://user-images.githubusercontent.com/2362780/156201370-24456161-0d04-461f-bd35-7ad11c230ab1.png)

We use Loki as a backend. 

**How to reproduce it (as minimally and precisely as possible)**:

Use Explorer in Grafana v8.4.0, v8.4.1 or v8.4.2 with Loki as a backend.

**Environment**:
- Grafana version: v8.4.0
- Data source type & version: Loki v2.3.0
- OS Grafana is installed on: K8s, official Docker image from hub.docker.com
- User OS & Browser: Linux, Chromium 98.0.4758.102
- Grafana plugins: no plugins

**Comment by ashharrison90** [comment]
hi @pulecp 👋 

this is due to the changes we've made to support the full-range log volume histogram. see https://grafana.com/blog/2022/02/17/grafana-8.4-release-new-panels-better-query-caching-increased-security-accessibility-features-and-more/#full-range-logs-volume

assuming your log lines contain a `level` label, you can visualise those levels as before by appending `| logfmt`, e.g. `{app="varnish"} | logfmt`

hope that helps! 😄 

cc @ivanahuckova 👍

**Comment by ivanahuckova** [comment]
@pulecp we are also sharing a blog post today with more tips on how to use new log volumes. I recommend to check it out! 🙂

**Comment by ivanahuckova** [comment]
You need to choose parser based on structure of your logs. You can find more in [logql documentaion](https://grafana.com/docs/loki/latest/logql/log_queries/#parser-expression)

**Comment by walkafwalka** [comment]
This broke our log level. I assume it is because .NET Serilog outputs `Level` with a capital instead of `level`.

**Comment by pulecp** [comment]
Thanks a lot! I need to use `{app="varnish"} | json` to get it working.
![image](https://user-images.githubusercontent.com/2362780/156533530-aee1d975-d41a-4a8c-8da6-d113fa2eadf7.png)

**Comment by pulecp** [comment]
Another option is to turn off the `fullRangeLogsVolume` feature in `grafana.ini`:

```
[feature_toggles]
fullRangeLogsVolume = false
```
