### ISSUE TITLE
Bug(3.0 beta2): Mixed data source is not working

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4604]
Running on windows 7 chrome
works fine on 2.6
but on 3.0 beta, get plugin error
failed to find exported plugin component for query-ctrl-mixed

**Comment by torkelo** [comment]
thanks for reporting this, fixed now!

**Comment by Dieterbe** [comment]
is it possible to still see this error with 859ef48e51d2c16b3a000c6f541c128438c9479b ? i just got this in devstack.

**Comment by torkelo** [comment]
@Dieterbe pushed new packages to testing APT repo yesterday, doing beta3 release now

**Comment by rubycut** [comment]
I just installed 3.0.0-beta5 and still have this problem.

**Comment by torkelo** [comment]
Strange, working here

**Comment by rubycut** [comment]
Then it must be database, I initially install grafana on verision 2.6, then switch to 3.0.0 master and then to 3.0.0beta5, I can look in the log for particulars if you want.

**Comment by torkelo** [comment]
If you create a new panel and change to mixed a few add 2 queries, what happens? Any error in console ?

**Comment by rubycut** [comment]
Works now.
