### ISSUE TITLE
Azure Monitor: Add support for Template Variables in the Resource Picker

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#46057]
In one pr or multiple prs behind a feature flag of some sort:
 - [x] Replace existing selection row in Resource Picker with an input field
 - [x] Ensure when a selects something with the picker that the input field updates
 - [x] Ensure that when a user types in the input field, the picker updates 
 - [X] Ensure that multiple template variables are properly interpolated by the input field
 - [x] Ensure that if the user types something in the input field that can not be recognized by the picker that we handle this expected use-case gracefully with meaningful error messages that do not block the query. 

Consider running plan or WIP past UX rep or feedback session to ensure it's workable.

**Comment by sunker** [comment]
Sarah from from our team has put together a design doc that is looking into how template variable queries can used effectively in the resource picker. This is a direct quote from her doc that summarizes the current state we're at:

> Right now, we are not set up well to use template variables with the picker. The resource picker builds what is called a Resource URI which is similar to a file path with a structure like:
> 
> subscription/resourceGroup/resource
> 
> Right now it is possible to create a template variable for the entire URI, but it is not easy to do this dynamically with multiple template variables:
> 
> $subscription/$resourceGroup/$resource
> 
> 
> Unfortunately this is a common enough use case that the folks at Azure have requested it and tried to implement this when creating new curated dashboards for us. The only workaround right now is to directly edit and save a grafana dashboard’s json, which is clunky to use.
>  

We're aiming to have better template variable support in the resource picker in place for 9.0 which will be released in June this year.
