### ISSUE TITLE
When selecting "Plugins" (and other) pages, prior page title for dashboard remains in place.

### ISSUE THREAD

**Issue by tdyas** [grafana/grafana#4606]
Select the dropdown -> "Dashboards" -> "New". Note that the page title in tab header is now "Grafana - New dashboard". Select dropdown -> "Plugins". Plugins page appears but title is still "Grafana - New dashboard".

This also applies if you select settings pages as well. My guess is it applies to any non-dashboard page.

Version: master as of 4/7/16

**Comment by torkelo** [comment]
thanks for reporting this, already a known issue however, https://github.com/grafana/grafana/issues/4606
