### ISSUE TITLE
Azure Monitor: Explore if it's possible to remove Metric Namespace Dropdowns from the UI

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#46061]
Right now when making a metric query with Azure Monitor, users must select a Metric Namespace from a dropdown, but those namespaces appear (at least at a cursory glance for me) to have a 1:1 mapping with Resource Types. When we switch from dropdowns to the Resource Picker, is it possible to remove this filter from our UI entirely?

I didn't do a deep dive into this question when creating the design doc, but it seemed like a potential area for clean up. If we have time perhaps we can see if we can remove this. Otherwise I suppose we can keep it as is.

**Comment by yaelleC** [comment]
After a quick investigation, I found something in: https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/tutorial-metrics

> Many resource types only have one namespace.

Which leads me to believe that, although not common, it could happen that the mapping is not exactly 1:1

I'm proposing to close this issue as we can't safely remove the namespace. @sarahzinger would you agree?

**Comment by sarahzinger** [comment]
@yaelleC thanks for your research! Seems very reasonable!
