### ISSUE TITLE
Azure Monitor: Migrate old Metrics Queries to New Ones for Resource Picker

### ISSUE THREAD

**Issue by sarahzinger** [grafana/grafana#46065]
After we've added feature gating (https://github.com/grafana/grafana/issues/46058) and after we've added the resource picker to metrics (https://github.com/grafana/grafana/issues/46060), create dashboards from the latest Grafana 7 and Grafana 8 with template variables and ensure that they properly migrate with the new resource picker. This is not necessarily a full backend migration, as much as it is a frontend one that will not change until saved. 

Write tests to ensure we continue properly handling these older dashboards.

**Comment by kevinwcyu** [comment]
In https://github.com/grafana/grafana/pull/47164, some new methods prefixed with `new` were added in `public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/azure_monitor_datasource.ts` e.g. `newGetMetricNames`, these should replace their existing counterpart in this issue.
