### ISSUE TITLE
Traceview: Go to top button

### ISSUE THREAD

**Issue by joey-grafana** [grafana/grafana#46075]
We would like there to be a button that takes a user to the top of the trace view on press.

As [suggested in #5](https://docs.google.com/document/d/1Gke6jGTQ-gM3rY9zvVEc20c4hrs1jm6Z_t1GfI__SlY/edit#) of the Large trace viewing document.

**Comment by ashharrison90** [comment]
@joey-grafana friendly reminder to add labels to issues you're working on so they don't appear in the [issue triage list](https://github.com/grafana/grafana/issues?q=is%3Aopen+is%3Aissue+no%3Alabel) 🙌
