### ISSUE TITLE
Bug (3.0 beta 2) not able to create new datasource

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4608]
on widows 7
using chrome browser
the test connection, save,  buttons do not seem to be working

**Comment by torkelo** [comment]
Have you filled in required fields?

**Comment by eben23** [comment]
all the fields
i created in 2.6..(as i could not in 3.0) .works fine...then i want to change the name..does not work
i even downloaded the latest and greatest version of firefox to see if it will work there..but no luck t here too

**Comment by eben23** [comment]
should we open this?

**Comment by torkelo** [comment]
works fine here with beta2 build in any browser and OS I try, so maybe you did something wrong when you installed it? Maybe the grafana.db has gotten wrong user owner and grafana cant modify it? DO you get any errors in the grafana.log or in the browser console? Do see any network requests happening ? (chrome dev tools network tab), 

Please when you open issues try to give as much information as you possibly can :)
