### ISSUE TITLE
@Grafana/Data {PanelProps} panel ID returns different values depending on the view of the panel.. 

### ISSUE THREAD

**Issue by madnanadnan** [grafana/grafana#46091]
export const Panel: React.FC<Props> = ({ options, data, width, height, id }) => {
//When in Editor View 
Console.log(id) => will return a unique ID => 2348689028

//When in Dashboard View
console.log(id) => will return ID of the panel within the current dashboard  => 2

}

Question is.. is it possible to return the same unified ID between the two different views?

Currently writing a plugin with backend database support, the panel id will be inserted into the database as a unique identifier for which objects need to be rendered; To differentiate between which panels need to return which data from the database, this means I need the IDs to be unified. Is this possible? Im i accessing a different value then i should be? Im also struggling to find isPanelEditorOpen boolean, does this boolean exist or do i need to instantiate my own?

Additionally - I could also achieve this using two values instead of one. i.e. Dashboard ID coupled with Panel ID should be sufficient enough, although i also cannot locate the prop for dashboard ID. 

@torkelo you seem to be the one thats most involved in these libraries, would you be able to assist on this please?

**Comment by ashharrison90** [comment]
hi @madnanadnan 👋 

> //When in Editor View
Console.log(id) => will return a unique ID => 2348689028
//When in Dashboard View
console.log(id) => will return ID of the panel within the current dashboard => 2

are you sure this is true? running locally, i always see the ID equal to the panel within the current dashboard whether viewed on the dashboard or editing the panel.

either way, this isn't really the correct place to ask these questions. i suggest you ask these questions either in the [community forums](https://community.grafana.com/) or on the [community slack](grafana.slack.com)

hope that helps! 😄
