### ISSUE TITLE
Alerting: `value` field is empty for alerts in `/api/prometheus/grafana/api/v1/alerts` and `/api/prometheus/grafana/api/v1/rules`

### ISSUE THREAD

**Issue by codesome** [grafana/grafana#46095]
**What happened**:

_This is for Prometheus alert-generator compliance, read more [here](https://github.com/prometheus/compliance/blob/main/alert_generator/specification.md). Using Grafana managed alert on a Prometheus datasource._

`value` field is empty for alerts in `/api/prometheus/grafana/api/v1/alerts` and `/api/prometheus/grafana/api/v1/rules`.

**What you expected to happen**:

`value` having the value of the query result from the alerting rule query.

**How to reproduce it (as minimally and precisely as possible)**:

Set a simple alerting rule with `up == 0` query (only one query, no expressions) and have a series satisfying that condition. The alert produced should have `"value": "0"`, but it has `"value": ""`

**Anything else we need to know?**:

Tested using Prometheus data source

**Environment**:
- Grafana version: Latest at the time of opening this PR

**Comment by gotjosh** [comment]
Is `up == 0` the right example here? 

Looking at Prometheus, for a query that's `http://localhost:9090/api/v1/query?query=up+%3D%3D+0&time=1647454368.896`

The response I get is:

```json
{
	"status": "success",
	"data": {
		"resultType": "vector",
		"result": []
	}
}
```

This is different from `http://localhost:9090/api/v1/query?query=vector%280%29&start=1647450838.313&end=1647454438.313&step=14` where the result is:


```json
{
	"status": "success",
	"data": {
		"resultType": "vector",
		"result": [{
			"metric": {},
			"value": [
				1647454470.051,
				"0"
			]
		}]
	}
}
```


I take it that what we want is the latter as oppose to the former.

**Comment by gotjosh** [comment]
As an example, for the above I have created two rules:

1) `up == 0` where up only has a single series in my local prometheus
2) `vector(0) == 0`

The result is that `up == 0` does not show anything while the other:

```json
{
	"status": "success",
	"data": {
		"alerts": [{
				"labels": {
					"__alert_rule_uid__": "1",
					"alertname": "AlwaysFiring"
				},
				"annotations": {},
				"state": "firing",
				"activeAt": "2022-03-16T18:17:56.129456503Z",
				"value": "1e+00"
			},
			{
				"labels": {
					"alertname": "VectorZero"
				},
				"annotations": {},
				"state": "firing",
				"activeAt": "2022-03-16T18:17:56.129456503Z",
				"value": "0e+00"
			}
		]
	}
}
```

**Comment by gotjosh** [comment]
I'm gonna assume that your statement above, refers to when the value returned whatever result and build up from that.
