### ISSUE TITLE
[Bug] pq: operator does not exist: character varying = integer

### ISSUE THREAD

**Issue by MaximeDevalland** [grafana/grafana#4609]
[What grafana version are you using?] 3.0.0-beta21459801392
[What datasource are you using?] None
[What OS are you running grafana on?] Ubuntu 14.04 - 3.16.0-30-generic

After installing Grafana using the .deb package, I get a blank page with this : 

```
Server side error :(
Failed to get settings

pq: operator does not exist: character varying = integer
```

Here's different config I have tested so far :

* grafana 3.0 + postgres DOES NOT work
* grafana 3.0 + sqlite3 works
* grafana 2.6.0 + postgres works
* grafana 2.6.0 + sqlite3 works

I think libpq is missing in the .deb package in the 3.0 version.

Thanks for looking into it.

**Comment by torkelo** [comment]
This is already fixed in master and beta3 (nightly builds)
