### ISSUE TITLE
Tooltip and sort order

### ISSUE THREAD

**Issue by Fursel** [grafana/grafana#46096]
Hello,

Tooltip for timeseries is not sorting correctly if values are as short Unit in thousands - Used descending

![image](https://user-images.githubusercontent.com/62752723/156365963-3a8d120f-bfa0-4b4f-997e-7c4780a8d701.png)

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: SQL Server
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows  - Edge
- Grafana plugins: Default - TimeSeries

**Comment by uselessjargon** [comment]
8.4.3 same issue on Time series graph.
