### ISSUE TITLE
Not possible to install plugins from UI

### ISSUE THREAD

**Issue by yeplaa** [grafana/grafana#46104]
What happened:

From UI, i can't install a plugin with this error message : "You do not have permission to INSTALL this plugin"
But, it works from grafana-cli command. 

It's seems related to auth configuration. Indeed, i use this variables for oauth2 authent : 

  GF_AUTH_PROXY_ENABLED: true
  GF_AUTH_DISABLE_LOGIN_FORM: true
  GF_AUTH_DISABLE_SIGNOUT_MENU: true 

When i use a local authentification, it works.
Is it wanted? 

Environment:
Grafana version: 8.3.4
Data source type & version: none
OS Grafana is installed on: K8s . The https://github.com/grafana/helm-charts/tree/main/charts/grafana chart is used to deploy
Grafana plugins: none
Others: none

**Comment by tolzhabayev** [comment]
@yeplaa I can not reproduce the issue, are you sure you are following the documentation https://grafana.com/docs/grafana/latest/auth/auth-proxy/ and setting the right configuration?

In our documentation we are using a header called `X-WEBAUTH-USER`. In this case you would also need to set
`GF_AUTH_PROXY_HEADER_NAME: X-WEBAUTH-USER`

**Comment by yeplaa** [comment]
@tolzhabayev i use also this parameters : 

```bash
auth.proxy:
    header_name: X-Forwarded-User
    header_property: username
    auto_sign_up: true
  users:
    auto_assign_org_role: Admin
```
My user has a Admin role automatically associated which is automatically associated with the *auto_assign_org_role: Admin* value.

**Comment by tolzhabayev** [comment]
@yeplaa what happens when you set X-Forwarded-User value in your proxy to "admin"?

Maybe setup a docker-compose.yml to showcase the issue as I can not reproduce it.

**Comment by yeplaa** [comment]
- I don't know how i can set X-Forwarded-User to "admin" value in my proxy. I use https://github.com/openshift/oauth-proxy on a Openshift platform. Currently, i think that  X-Forwarded-User contains my user send by my SSO.

- When i run _window.grafanaBootData.user.isGrafanaAdmin_ in my browser console, i have the 'false' value instead 'true'. Do you know why? 

Thanks :)

**Comment by marefr** [comment]
You need user to be Grafana Server Admin to be able to install plugins, see https://grafana.com/docs/grafana/latest/manage-users/#server for information about Grafana Server Admin. Auth proxy currently don't support setting the Grafana Server Admin role for a user. 

I'm closing this now. Please continue the discussions in [feature request discussion](https://github.com/grafana/grafana/discussions/44000).
