### ISSUE TITLE
OS X Safari 13.1.2 no longer loads Grafana after update to 8.4.2

### ISSUE THREAD

**Issue by SaKiEQ** [grafana/grafana#46110]
**What happened**:
After updating Grafana to 8.4.2 Safari 13.1.2 (latest of that line of versions), Grafana can longer be accessed. On the same machine Chrome / Firefox load the page. 

**What you expected to happen**:
That it continues to load, like 2h earlier before updating to Grafana 8.4.2. 

**Anything else we need to know?**:
I know this an old version of Mac OS and Safari, but it is still one of the preferred development environments of many in regards to many aspects such as minimal SIP integration, stability, many hardware drivers for older lab / development equipment is no longer being supported on never systems. 
I can live with some UI snags, but getting cut-off on a default browser seems a bit harsh. I won't switch to another browser i rather downgrade Grafana and leave it at that. 

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: 
- OS Grafana is installed on: Linux / Raspberry Pi
- User OS & Browser: OS X High Sierra 10.13.6, Safari 13.1.2

**Comment by leeoniya** [comment]
replied here: https://github.com/grafana/grafana/issues/35594#issuecomment-1057184253

**Comment by leeoniya** [comment]
@SaKiEQ keep in mind that i don't have access to a real MacOS machine (or filesystem), or to an old version of Safari except through BrowserStack. so this debugging process is quite slow and labor intensive for me. i cannot promise i will have time to pursue it to the end.

to try to get the error message to reveal the location of the problem, i've pretty-printed the problematic file since Safari is unable to parse it: [9389.fae938a4d93950cd619c.js.tar.gz](https://github.com/grafana/grafana/files/8172904/9389.fae938a4d93950cd619c.js.tar.gz)

1. open up https://play.grafana.org/
2. open safari's devtools and navigate to the file in the Source panel and enable a local override for it using the attached file.
3. reload the page and hopefully it will provide a more readable location for the issue

https://user-images.githubusercontent.com/43234/156449000-c1edbaf4-5148-4565-aea4-d42a8019b39e.mp4

**Comment by SaKiEQ** [comment]
Hi, thanks for the effort. 

I followed your instructions, but I get the exact same result in the console. The same on the 'play.grafana.org' link and on my internal server.  

I further went and uninstalled all third party plugins, restarted grafana, flushed cash, reloaded - with same result. 
So I think I can rule out the 'offending' code comes from a plugin... Which was most likely ruled out by loading your 
development server anyway.

I will try and load the same on a never OS X version, to see if the console throws something.

**Comment by leeoniya** [comment]
Ok, let's do this properly, then.

Make sure you have Go 1.17, [NodeJS 16.14.0](https://nodejs.org/en/download/) and [Yarn](https://classic.yarnpkg.com/lang/en/docs/install/#debian-stable) installed.

1. Download and extract latest https://github.com/grafana/grafana/archive/refs/heads/main.zip
2. Run `YARN_CHECKSUM_BEHAVIOR=update yarn` to download the JS deps
3. Run `yarn run build:nominify` to create an uncompressed production build of the JS frontend
4. Run `make run` to download Go deps, build & run the server
5. Open http://localhost:3000/ and look at the Webkit/Safari console for errors and locations

**Comment by SaKiEQ** [comment]
Sorry for late reply, end of the week stuff have taken hold of me. 

Yeah despite having all update and upgraded, my NodeJS is at 14.19.0, Yarn 1.22.7. Go I never heard off. 

I guess  I have to do some updating and installing first.

**Comment by SaKiEQ** [comment]
On every other machine, up to the latest OS X M1 version it runs flawless, iOS devices including.

**Comment by peembe** [comment]
Hi

I had similar issues on raspberry pi browser that was not updated for a long time (browser is chromium 65.0.3325.181). Easy fix was just to perform an update.

I also observe issues on smart TV browser which displays grafana dashboard and I can't do any upgrades there.

I've built from sources following your instructions and listed below what i was able to observe (there were multiple places where catch was without an argument in 5746.f9c2c4b959d71713de16.js, I just include one, all were just the same)

```
// 4026.f9c2c4b959d71713de16.js:216160 Uncaught SyntaxError: Unexpected token {

216151 const ELEMENT_NODE = 1;
216152 const TEXT_NODE = 3;
216153 const COMMENT_NODE = 8;
216154 const FRAGMENT_NODE = 11;
216155 const ELEMENT_REGEXP = /^((HTML|SVG)\w*)?Element$/;
216156 
216157 const testHasAttribute = val => {
216158   try {
216159     return typeof val.hasAttribute === 'function' && val.hasAttribute('is');
216160   } catch {
216161     return false;
216162   }
216163 };
216164 
216165 const testNode = val => {
216166   const constructorName = val.constructor.name;
216167   const {nodeType, tagName} = val;

// 5746.f9c2c4b959d71713de16.js:8931 Uncaught SyntaxError: Unexpected token {

  8925 function fieldToComplexField(field) {
  8926   const complexValues = field.values.toArray().slice();
  8927 
  8928   for (let s = 0; s < complexValues.length; s++) {
  8929     try {
  8930       complexValues[s] = JSON.parse(complexValues[s]);
  8931     } catch {
  8932       complexValues[s] = null;
  8933     }
  8934   }
  8935 
  8936   return Object.assign({}, field, {
  8937     type: dataFrame/* FieldType.other */.fS.other,
  8938     values: new vector/* ArrayVector */.Gt(complexValues)
  8939   });
  8940 }

// 5746.f9c2c4b959d71713de16.js:10676 Uncaught SyntaxError: Unexpected token =

 10665         for (const labelName of Object.keys(field.labels)) {
 10666           if (keepLabels && !keepLabels.has(labelName)) {
 10667             continue;
 10668           } // if we should use this label as the value field name store it and skip adding this as a separate field
 10669
 10670
 10671           if (options.valueLabel === labelName) {
 10672             sansLabels.name = field.labels[labelName];
 10673             continue;
 10674           }
 10675
 10676           const uniqueValues = uniqueLabels[labelName] ||= new Set();
 10677           uniqueValues.add(field.labels[labelName]);
 10678         }
 10679       }

// 5746.f9c2c4b959d71713de16.js:88705 Uncaught SyntaxError: Unexpected token ?

 88701         let yMax = row.gridPos.y;
 88702
 88703         for (const panel of row.panels) {
 88704           // set the y gridPos if it wasn't already set
 88705           panel.gridPos.y ??= row.gridPos.y; // make sure y is adjusted (in case row moved while collapsed)
 88706
 88707           panel.gridPos.y -= yDiff; // insert after row
 88708
 88709           this.panels.splice(insertPos, 0, new PanelModel/* PanelModel */.r(panel)); // update insert post and y max
 88710
 88711           insertPos += 1;
 88712           yMax = Math.max(yMax, panel.gridPos.y + panel.gridPos.h);
 88713         }

// 5746.f9c2c4b959d71713de16.js:112463 Uncaught SyntaxError: Invalid or unexpected token

112460   }).addNumberInput({
112461     path: 'hideThreshold',
112462     name: 'Hide cell counts <=',
112463     defaultValue: 0.000_000_001,
112464     // 1e-9
112465     category
112466   }).addSliderInput({
112467     name: 'Cell gap',
112468     path: 'cellGap',
112469     defaultValue: heatmap_new_models_gen_defaultPanelOptions.cellGap,
112470     category,
112471     settings: {
```

Fixing all catches, changing ||= and ??= operators to if statements and rewriting 0.000_000_001 as 0.000000001 made my old browsers to successfully load login page

**Comment by leeoniya** [comment]
awesome, now we're getting somewhere :)

here's the try/catch situation:

Optional catch binding in 2019
https://stackoverflow.com/a/56001361

> One important note is that in Typescript, if you target esnext this syntax will be emitted, breaking browsers like Edge that don't support it. (I believe there's actually a merged PR to add this capability to Edge, but it was last year and still hasn't landed. I can't find the page I read this on in my history now...)

since this is not crashing Safari 13.1, it's unlikely we would change our target version in tsconfig for even older browsers since it bloats and slows the code for everyone else. i dont know if there's a granular compiler setting to force emitting catch w/error. you may have to keep & build a patched fork of Grafana for this -- at least it looks pretty simple for now. use `yarn run build` to make a minified production build, btw. you might need to adjust webpack minifier (terser) options in case the minification pass re-introduces this issue.

> Fixing all catches, changing ||= and ??= operators to if statements and rewriting 0.000_000_001 as 0.000000001 made my old browsers to successfully load login page

this looks like an easy adjustment.

can you check if replacing `x ??= y` with the logically equivalent `x ?? (x = y)` works properly in Safari 13.1 (with and wthout minification)...and same for `||=`. 🙏 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_nullish_assignment

**Comment by peembe** [comment]
Just to be clear: I'm not checking on safari. I just happen to see similar errors when using old chomium and smart TV browsers.

Replacing operators with longer equivalent worked just fine in both minified and unminified builds.

Unfortunately fixing catch statement issues in a way that not requires manual editing of files produced by build process is beyond my skills. I'll focus on eliminating old browsers from my environment.

Thanks for taking time too look into this.

**Comment by leeoniya** [comment]
> I'll focus on eliminating old browsers from my environment.

best done by hooking up a Raspberry Pi instead of relying on built-in tv browsers, btw.

**Comment by leeoniya** [comment]
Hopefully https://github.com/grafana/grafana/pull/46260 will fix Safari 13.1

**Comment by SaKiEQ** [comment]
I did just install the '8.5.0~54211pre' nightly build. 

It does still throw the same 'Line 2: Unexpected Token '='' - BUT only 1 Error, where before it reported two of the same error...

**Comment by leeoniya** [comment]
nightly builds at that link are only off the `main` branch, so would not include that PR until it's reviewed and merged. if you want to test those changes sooner you have to make your own build off https://github.com/grafana/grafana/tree/leeoniya/safari-13.1 using the mentioned steps.

**Comment by SaKiEQ** [comment]
As much as I would love to contribute to solving the problem, i think the above steps are slightly over my head since I do not yet fully understand them... Will try and educate myself more.

**Comment by leeoniya** [comment]
i encourage you to put some effort into this if you want to extend the longevity of you legacy setup. we have no plans to officially support old browsers and lack the hardware/software setups to even test this. if @peembe had not done a non-minified build and run it ona legacy setup this issue would have gone nowhere and benn closed as WONTFIX after a few weeks.

**Comment by SaKiEQ** [comment]
> 2\. YARN_CHECKSUM_BEHAVIOR=update yarn

ok I got Go, Yarn and NodeJS all on the respective versions and running (NodeJS update broke some other services running on the same system... so just updating/upgrading it was a very bad idea). 

Now you say 'just' download and  extract latest source. Can you tell me which path / directory this should be done in ?
I am running on raspberry pi. Should this be in the 'old' Grafana folder, or just in the root folder ?? 

Thx.

**Comment by SaKiEQ** [comment]
> 3\. Run `yarn run build:nominify` to create an uncompressed production build of the JS frontend

Do you have a hint for me ? What am I doing wrong... downloaded with 
~/>wget https://github.com/grafana/grafana/archive/refs/heads/main.zip
~/>Unzip grafana-main.zip. 
~/>cd grafana-main
/grafana-main> YARN_CHECKSUM_BEHAVIOR=update yarn
/grafana-main> yarn run build:nominify

the last step throws the below response...

![Screen Shot 2022-03-06 at 3 20 27 PM](https://user-images.githubusercontent.com/35499064/156922904-0fb23b00-e85d-4a40-b3bd-7b9d64ab4f6c.jpg)

**Comment by SaKiEQ** [comment]
Well I tried the pure 'yarn install' last night, it ran - but then gave me an out of memory error - for obvious reasons on a Pi, after installing all the other dependencies. I was not sure if it is a RAM error or a disk space error, while disk space should be ok. 


Cool will swap card on the Pi to give it more room (never a bad idea to keep them fresh anyway), then install the nightly build, but will also try to to get Yarn to work it should... just to make sure.

**Comment by peembe** [comment]
I had OOM problems too. Fixed with exporting `NODE_OPTIONS=--max-old-space-size=8192` before building.
No idea what's minimal magic number here, I just arbitrarily picked one and it worked.

**Comment by peembe** [comment]
Yes it does.
But besides fixing it in all places that `grep -iR "catch {"` finds in unzipped `main` I have to fix one more occurrence that is present in files produced by build process.

**Comment by SaKiEQ** [comment]
it would help if the 'error page' contained the build version somehow. Now I never know if the original or the modified version shows up.

**Comment by Raboo** [comment]
This fixed it for my two Sony Bravia TV's (Android TV) with user agents

```
Mozilla/5.0 (Linux; Andr0id 8.0.0; BRAVIA 4K GB ATV3 Build/OPR2.170623.027.S30) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36 OPR/46.0.2207.0 OMI/4.11.2.40.DIA4.95 SonyCEBrowser/1.0 (FW-49BZ35F; CTV/PKG6.6545.0255BBA; )
```

```
Mozilla/5.0 (Linux; BRAVIA 4K GB ATV3 Build/PTT1.190515.001.S43) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/71.0.3578.98 Safari/537.36 MRC/1.1.26 SonyCEBrowser/1.0 (FW-49BZ35F; CTV/PKG6.7165.0360BBA; )
```

Waiting eagerly for next release with this bugfix #46260
