### ISSUE TITLE
New user notification email fail send

### ISSUE THREAD

**Issue by trombini77** [grafana/grafana#46126]
- Questions should be posted to: https://community.grafana.com
- Use query inspector to troubleshoot issues: https://bit.ly/2XNF6YS
- How to record and attach gif: https://bit.ly/2Mi8T6K
-->

**What happened**:

Hi, I tried 6 days ago openning a topic in Grafana Comunity https://community.grafana.com/t/add-user-workflow-invite-email-fail/61402 but without answers I´m trying here to understand what is going on.
I´ll replicate the question here:

> I would like to explain what is going on with me.
I have a Grafana 8.3.5 configured through config.ini with SMTP setup using AWS SES to send by only one registered email account.
The email test send from Concat Point config worked fine.
But when I added a new user account sending the invite email what happened as the following error:
>
> `lvl=eror msg=“Async sent email 0 succeed, not send emails: “email” err: Failed to send notification to email addresses: “email”: gomail: could not send email 1: 554 Message rejected: Email address is not verified. The
following identities failed the check in region US-EAST-1: “email”” logger=notifications`
>
> PS. the “email” is a fake email that I changed to copy the message here without show the real email and this community system block more than 2 email address here, but this “email” was the new email user account.
>
> Well, what happened is that the new user email was used as sender in the AWS SES SMTP server and it doesn´t agree, in my opinion, with the config.ini SMTP “from_address” config that would the default sender.
>
> I don´t know if it is a issue or a missing configuration.
>
> Thanks if some one have some light about this workflow.

**What you expected to happen**:

I expected that the email alert sender would be the email configured in ConfigMap > grafana.ini > [SMTP] > from_address but the error message suggested that was used the user email to send.

**How to reproduce it (as minimally and precisely as possible)**:

Add Prometheus from Helm Chart https://prometheus-community.github.io/helm-charts version 14.11.1 and Grafana from Helm Chart https://grafana.github.io/helm-charts version 6.21.5 adding in values.yaml:

```
grafana.ini:
  smtp:
    enabled: true
    host: email-smtp.us-east-1.amazonaws.com:587
    user: IAM-User
    password: IAM-User-Secret
    from_address: Email-enabled-AWS-SES
    startTLS_policy: MandatoryStartTLS
    from_name: Grafana Email
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.5
- Data source type & version: Prometheus 2.26.0, AWS CloudWatch and Redis
- OS Grafana is installed on: AWS EKS v1.21
- User OS & Browser: Windows 10, Microsoft Edge (Chromium)
- Grafana plugins: grafana-clock-panel,grafana-worldmap-panel,grafana-piechart-panel,xginn8-pagerduty-datasource,redis-app,grafana-github-datasource
- Others:

**Comment by ashharrison90** [comment]
hmmmm, looks like it's trying to send to the user `<email>` correctly, but it's also using the users `<email>` to send from as well? weird 😕 

not sure if it's a configuration problem or a bug on our end. passing to the backend team to investigate

**Comment by trombini77** [comment]
Hi, sorry ask about this point but I guess problably could be a miss configuration from mine because nobody gave a answer about it, right?
