### ISSUE TITLE
[Bug] Show warning when enabling "fill below to" & "staircase line"

### ISSUE THREAD

**Issue by earwin** [grafana/grafana#4612]
The combination mentioned in subject, under some specific conditions breaks when rendering a "fill below to" fill, and all subsequent graph lines.
The bug was present in latest 2.6.x and is still present in latest (released as .deb) 3.0.x

Broken display:
<img width="886" alt="screenshot 2016-04-08 12 02 39" src="https://cloud.githubusercontent.com/assets/299579/14379481/34fa9de0-fd8b-11e5-8b67-c2350aeaec69.png">

With _staircase_ off:
<img width="875" alt="screenshot 2016-04-08 12 02 20" src="https://cloud.githubusercontent.com/assets/299579/14379487/38cc7ea2-fd8b-11e5-993d-42805013fd7f.png">

There are javascript errors in console:
<img width="752" alt="screenshot 2016-04-08 12 03 20" src="https://cloud.githubusercontent.com/assets/299579/14379495/49461310-fd8b-11e5-8df2-015d1a329498.png">

That originate from (public/vendor/flot/jquery.flot.fillbelow.js):
<img width="739" alt="screenshot 2016-04-08 12 03 36" src="https://cloud.githubusercontent.com/assets/299579/14379500/501941f8-fd8b-11e5-8437-fd98d896ed39.png">

Now let us explore `p` and `r` arrays (which correspond to `points` and `otherpoints` in original source):
<img width="757" alt="screenshot 2016-04-08 12 04 10" src="https://cloud.githubusercontent.com/assets/299579/14379531/741afcae-fd8b-11e5-9fd2-ee3e47a0d37e.png">
<img width="754" alt="screenshot 2016-04-08 12 04 24" src="https://cloud.githubusercontent.com/assets/299579/14379534/7726e6ba-fd8b-11e5-8a2c-8d3506ecbf34.png">

Pay close attention to the first few records.
In usual line mode there is a single point per timestamp.
In staircase line mode there are two points per timestamp, for the left and right side.
That is the case for the `r` array, but in `p` array there is only one point for `1460058600000` timestamp.
Presumably, because the value to the left and right side exactly match and these two identical points were deduplicated somewhere earlier in the pipeline.

**Comment by earwin** [comment]
Just in case you may wonder, the source points (coming from influxdb) should perfectly aligned, as they come from a query like this:
<img width="701" alt="screenshot 2016-04-08 12 14 19" src="https://cloud.githubusercontent.com/assets/299579/14379974/3bdae14e-fd8e-11e5-8df5-60985cf991b9.png">

**Comment by torkelo** [comment]
Yes, this combination is not supported yet. Requires a lot of changes to fill below flot charts plugin

**Comment by earwin** [comment]
shouldn't the user get a warning then? or have it somewhere in the docs?
it breaks in much less obvious ways sometimes and caused quite a lot of grey hair.

**Comment by torkelo** [comment]
Yes, your right this should generate a warning in the UI

**Comment by steaksauce-** [comment]
Is this supported yet? I see it's been inactive for sometime

**Comment by MikeTheTux** [comment]
Had a similar issue with two metrics not using exactly the same time stamps.
`fill(0)` in my metrics helped as workaround.

**Comment by 8666** [comment]
> `fill(0)` in my my metrics helped as workaround.

How exacly is this done? I have the same issue @MikeTheTux

**Comment by MikeTheTux** [comment]
afai can rember i just added `fill(0)` to the series specific overrides

**Comment by meustrus** [comment]
This is working for me if _both_ metrics have `Staircase line: true` (and `Line fill: 0`) in `Grafana v7.3.6 (ea06633c34)`. Was this issue fixed at some point?

![(graph with "fill below to" & "staircase line")](https://user-images.githubusercontent.com/15673282/102641790-478c4280-4122-11eb-96b2-acdc8c63540c.png)

**Comment by ryantxu** [comment]
Interesting -- nothing significant has changed with the graph panel in a long while.  The case described here will be solved soon in an updated graph panel based on [uPlot](https://github.com/leeoniya/uPlot)   See https://github.com/grafana/grafana/issues/27848

**Comment by leeoniya** [comment]
preview ;)

https://leeoniya.github.io/uPlot/demos/high-low-bands.html
