### ISSUE TITLE
Tooltip display goes beyond the screen size

### ISSUE THREAD

**Issue by ambekarnikhil** [grafana/grafana#46131]
**What happened**: Tooltip goes beyond the screen if too many time-series metrics

**What you expected to happen**: Adjust tooltip location according to the panel placement

**How to reproduce it (as minimally and precisely as possible)**: Time series panel with too many metrics

**Anything else we need to know?**: No

**Environment**:
- Grafana version: v8.4.1(53f5c6a44c)
- Data source type & version: Influx v1.7
- OS Grafana is installed on: Docker
- User OS & Browser: Mac OS & Safari
- Grafana plugins: Timeseries
- Others:
![Grafana tooltip issue](https://user-images.githubusercontent.com/18604000/156469477-5ad0617a-6469-4971-87d3-1ddaa3870f0d.png)

**Comment by ambekarnikhil** [comment]
Hi @ashharrison90,

We have tooltip sorted based on values, so the current tooltip becomes unusable as top N values are not visible. Also, we don't have an option today to limit tooltip values.

I tried the same data on v4.4.3. It does adjust well and clips values towards the end.

![Grafana tooltip issue 4 4 3](https://user-images.githubusercontent.com/18604000/156647385-552fe866-1f35-4d97-a70a-1f8be5e86900.png)

**Comment by iamyeka** [comment]
Same problem for me

**Comment by timba** [comment]
This affects when "Tooltip mode" is set to "All" and the panel is in full screen view or located in the bottom of the dashboard, and the cursor is moved to the lower position, then the tooltip goes beyond the screen and barely fits a couple of labels. In this scenario one can't identify which series is clicked/highlighted. Why can't the tooltip be moved/scrolled when it doesn't fit the screen?

<img width="2755" height="1296" alt="Image" src="https://github.com/user-attachments/assets/f2e618b5-3756-4042-ac0a-f5cf6d850dcb" />
