### ISSUE TITLE
[Feature Request] Ability to lock zero between left and right Y-axis

### ISSUE THREAD

**Issue by earwin** [grafana/grafana#4613]
When graphing two values of different kind on left and right Y-axis, it is sometimes much better on the eyes and more readable to have zero-points of these axis match.

This can be done by fixing `Y-Min` to 0, if your values are always positive.

But, eg, if you use `Transform: negative-Y`, this no longer applies.

(my exact use case is graphing in/out traffic + in/out errors)

**Comment by torkelo** [comment]
Think there already is an issue for this

**Comment by torkelo** [comment]
Will link to it later on mobile now

**Comment by earwin** [comment]
Oh, beg my pardon, didn't look for them well enough. I think they are #2740 & #1271
