### ISSUE TITLE
[Bug] Changing organization without saving dashboard

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#4614]
* What grafana version are you using? grafana-3.0.0-beta21459801392.x86_64
* What datasource are you using? InfluxDB 0.12
* What OS are you running grafana on? RHEL7.2
* Chromium: 49.0.2623.108 (64-bit)

If I'm in Org A, make some changes to a dashboard, and **without** saving I change to other Org
![captura de pantalla de 2016-04-08 13-14-01](https://cloud.githubusercontent.com/assets/3237784/14382133/d1394576-fd8b-11e5-9611-0664c9d2483c.png)

The green alert tells that I have changed the Organization, but if i tell Chromium "Keep in this page", I keep viewing the same dashboard. But if I try to save now the dashboard:
![captura de pantalla de 2016-04-08 13-15-19](https://cloud.githubusercontent.com/assets/3237784/14382179/2e35ae2c-fd8c-11e5-925d-eed326c429d4.png).

**Comment by torkelo** [comment]
thanks for reporting this, fixed!
