### ISSUE TITLE
Rendering broke with 8.4.0: "Error: SyntaxError: Unexpected token '='"

### ISSUE THREAD

**Issue by vlcty** [grafana/grafana#46147]
**What happened**:

Since upgrading to 8.4.0 (and above) and above rendering broke with the following error message in the trace logs:

> logger=rendering renderer=plugin t=2022-03-03T09:53:44.68+0100 lvl=info msg=Rendering path="d-solo/some/dashboard?orgId=1&refresh=5m&from=1646122563249&to=1646295363249&panelId=0&width=1000&height=500&tz=Europe%2FBerlin"
> logger=rendering renderer=plugin t=2022-03-03T09:53:44.68+0100 lvl=dbug msg="Calling renderer plugin" req="url:\"http://127.0.0.1:3000/d-solo/some/dashboard?orgId=1&refresh=5m&from=1646122563249&to=1646295363249&panelId=0&width=1000&height=500&tz=Europe%2FBerlin&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/naoM0wJ2M9pX6QToTSJ5.png\" renderKey:\"redacted\" domain:\"127.0.0.1\" timeout:60 timezone:\"Europe/Berlin\" headers:{key:\"Accept-Language\" value:{values:\"de,en-US;q=0.7,en;q=0.3\"}}"
> logger=plugin.grafana-image-renderer t=2022-03-03T09:53:44.69+0100 lvl=dbug msg="Render request received" url="http://127.0.0.1:3000/d-solo/some/dashboard?orgId=1&refresh=5m&from=1646122563249&to=1646295363249&panelId=0&width=1000&height=500&tz=Europe%2FBerlin&render=1"
> logger=plugin.grafana-image-renderer t=2022-03-03T09:53:44.86+0100 lvl=dbug msg="Setting extra HTTP headers for page" headers="unsupported value type"
> logger=plugin.grafana-image-renderer t=2022-03-03T09:53:45.22+0100 lvl=eror msg="Browser uncaught exception" error="Error: SyntaxError: Unexpected token '='"
> logger=rendering t=2022-03-03T09:53:49.41+0100 lvl=eror msg="Failed to delete render key" error="context canceled"
> logger=context t=2022-03-03T09:53:49.41+0100 lvl=eror msg="Rendering failed." error="rpc error: code = Canceled desc = context canceled"
> logger=context t=2022-03-03T09:53:49.41+0100 lvl=eror msg="Request Completed" method=GET path=/render/d-solo/some/dashboard status=500 remote_addr=127.0.0.1 time_ms=4731 size=620 referer=

**What you expected to happen**:

Rendering would still work. Downgrading version by version until reaching `8.3.7 (commit: c5b6f7883e, branch: HEAD)` restores rendering functionality. The trace logs:

> t=2022-03-03T10:06:30+0100 lvl=dbug msg="seen token" logger=auth tokenId=2142 userId=3 clientIP=127.0.0.1 userAgent="Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0" authToken=redacted
> t=2022-03-03T10:06:30+0100 lvl=info msg=Rendering logger=rendering renderer=plugin path="d-solo/some/dashboard?orgId=1&refresh=5m&from=1646122563249&to=1646295363249&panelId=0&width=1000&height=500&tz=Europe%2FBerlin"
> t=2022-03-03T10:06:30+0100 lvl=dbug msg="Calling renderer plugin" logger=rendering renderer=plugin req="url:\"http://127.0.0.1:3000/d-solo/some/dashboard?orgId=1&refresh=5m&from=1646122563249&to=1646295363249&panelId=0&width=1000&height=500&tz=Europe%2FBerlin&render=1\" width:1000 height:500 deviceScaleFactor:1 filePath:\"/var/lib/grafana/png/FXLakDJoR7up9AK8SD81.png\" renderKey:\"redacted\" domain:\"127.0.0.1\" timeout:60 timezone:\"Europe/Berlin\" headers:{key:\"Accept-Language\" value:{values:\"de,en-US;q=0.7,en;q=0.3\"}}"
> t=2022-03-03T10:06:30+0100 lvl=dbug msg="Render request received" logger=plugin.initializer pluginID=grafana-image-renderer url="http://127.0.0.1:3000/d-solo/some/dashboard?orgId=1&refresh=5m&from=1646122563249&to=1646295363249&panelId=0&width=1000&height=500&tz=Europe%2FBerlin&render=1"
> t=2022-03-03T10:06:30+0100 lvl=dbug msg="Setting extra HTTP headers for page" logger=plugin.initializer pluginID=grafana-image-renderer headers="map[Accept-Language:de,en-US;q=0.7,en;q=0.3]"
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="Client connected" logger=live user=3 client=474cc8be-c814-4355-b3b8-e93891a618f8
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=3 orgId=1 uname= dashId=1819416 action=View
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=3 orgId=1 uname= dashId=1819416 action=Edit
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=3 orgId=1 uname= dashId=1819416 action=Edit
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="User denied access to execute action" logger=dashboard.permissions userId=3 orgId=1 uname= dashId=1819416 action=Admin
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="Client wants to subscribe" logger=live user=3 client=474cc8be-c814-4355-b3b8-e93891a618f8 channel=1/grafana/dashboard/uid/40214636
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="Found cached channel handler" logger=live channel=grafana/dashboard/uid/40214636
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="User granted access to execute action" logger=dashboard.permissions userId=3 orgId=1 uname= dashId=1819416 action=View
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="Client subscribed" logger=live user=3 client=474cc8be-c814-4355-b3b8-e93891a618f8 channel=1/grafana/dashboard/uid/redacted
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="Querying for data source via SQL store" logger=datasources id=16 orgId=1
> t=2022-03-03T10:06:31+0100 lvl=dbug msg="Applying default URL parsing for this data source type" logger=datasource type=graphite url=http://redacted
> t=2022-03-03T10:06:32+0100 lvl=dbug msg="token needs rotation" logger=auth tokenId=2070 authTokenSeen=false rotatedAt=2022-03-03T10:05:23+0100
> t=2022-03-03T10:06:32+0100 lvl=dbug msg="auth token rotated" logger=auth affected=1 auth_token_id=2070 userId=8
> t=2022-03-03T10:06:32+0100 lvl=dbug msg="Client disconnected" logger=live user=3 client=474cc8be-c814-4355-b3b8-e93891a618f8 reason=normal elapsed=878.90176ms

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Installation source: RPM mirror https://packages.grafana.com/oss/rpm

**Environment**:
- Grafana version: Works up to 8.3.7, breaks after 8.4.0 and above
- Data source type & version: Graphite
- OS Grafana is installed on: CentOS Linux release 7.9 fully up to date
- User OS & Browser: Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0, curl
- Grafana plugins: none
- Others: nothing

**Comment by torkelo** [comment]
what version of render plugin are you using?

**Comment by torkelo** [comment]
no worries, happy you got it working

**Comment by vlcty** [comment]
My browser is: `Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:97.0) Gecko/20100101 Firefox/97.0`. The render plugin itself used something "headless chrome". Do you mean that?

**Comment by vlcty** [comment]
Safari 13.1.2 is from July 15, 2020. Heavily outdated. Current version is 15.2 and grafana loads fine. I'd not invest too much time.

**Comment by leeoniya** [comment]
> Current version is 15.2 and grafana loads fine. I'd not invest too much time.

yes, but interestingly, the devtools even in 15.1 fail to properly parse that file in the Source panel when you try to open it. other files in the bundle work fine. to me it looks like they're still using an old JS parser in devtools. if it turns out to be an easy fix, like tweaking some minification options, it's still worth doing, and we get 13.1.2 support back as a bonus. at this point it's more curiosity :)

**Comment by olly69** [comment]
I had this issue upgrading to grafana 8.4.3-1.  My renderer was already 3.4.1 (latest at time of writing) but on reinstalling it the problem disappeared.  O/S = RHEL 8.
