### ISSUE TITLE
Error "database is locked" when using new alerting system

### ISSUE THREAD

**Issue by KillianS27** [grafana/grafana#46142]
Hi all,

**What happened**:

After upgrading to Grafana 8.4.3 and migrate to the new alerting system we are facing an issue. The state of our alert is variating betwenn "ok" and "error", for the "error" state Grafana says "database is locked". We didn't change anything on our database. The new system send a lot of mail and they are all false. Our alert monitor SQL Query with SQL Server Data sources provided by Grafana. Before the migrating all working fine.

**What you expected to happen**:

Alert working again.

**How to reproduce it (as minimally and precisely as possible)**:

- Add a SQL Server Data source.
- Create a panel with a SQL query who return the count of the line.
- Create an alert and a trigger when the query return more than 0 line.

**Environment**:

- Grafana version: 8.4.3
- Data source type & version: SQL Server provided by Grafana
- OS Grafana is installed on: Ubuntu Server 18.04.6

Thanks.

**Comment by ashharrison90** [comment]
hi @KillianS27 

thanks for raising this! 🙌 

i've routed to a squad to investigate, but in the mean time are you able to try this workaround and see if it fixes your problem https://github.com/grafana/grafana/issues/43528#issuecomment-1039385851?

hope that helps! 😄

**Comment by Dhyanesh97** [comment]
![image](https://user-images.githubusercontent.com/89400147/157373235-fe13d82e-2070-4ec4-ad2f-c0defbe19324.png)

We are also facing same issue. Error occurred for both cloud-watch (5 rules) and influx-db (25 rules) as data source.

**Comment by KillianS27** [comment]
@Dhyanesh97 For us that was not exactly the same issue, Grafana just say "database is locked".

**Comment by Dhyanesh97** [comment]
@KillianS27 May be it is because of version difference. Grafana 8.2 and 8.4 shows slightly different error messages.

**Comment by KillianS27** [comment]
@Dhyanesh97 I don't think. We have this issue since the new alerting system is available and I'm not sure but I think this was with Grafana 8.0

**Comment by pkirubak** [comment]
apart from workaround, is the fix for this is being worked on? even grafana 9.x has this problem

**Comment by KillianS27** [comment]
@pkirubak I have apply this workaround on a testing environment with Grafana 9.0, after that, I have upgraded to Grafana 9.1.6 and it seems that work, the error "database is locked" is not displaying again in Grafana but I don't think it's a real solution ...

**Comment by JohnnyQQQQ** [comment]
We are aware that SQLite may cause locking. We are in the process of documenting this in our performance documentation.
