### ISSUE TITLE
Global variables not replaced when using an expression and elasticsearch query together

### ISSUE THREAD

**Issue by nathanleyton** [grafana/grafana#46150]
**What happened**:  When using multiple elastic queries and then an expression on those queries global variables are not being substituted in the query.  

**What you expected to happen**: It should give the value of the variable and not the variable name / full string

**How to reproduce it (as minimally and precisely as possible)**: Add 2 elastic queries, then add an expression of type Math and do a calculation on those queries. See the screen shot at the end showing the variable not being replaced. 

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.3.7
- Data source type & version: ElasticSearch 7.8.0
- OS Grafana is installed on: Alpine Linux 3.15.0
- User OS & Browser: Chrome / Ubuntu
- Grafana plugins: N/A
- Others:
- 
![image](https://user-images.githubusercontent.com/637276/156547796-84dfe181-619e-421a-a43c-6a6169e4701e.png)

**Comment by ashharrison90** [comment]
hi @nathanleyton 👋 

can confirm this doesn't seem to be working in v8.3.7

however this has been fixed in a later version! 🥳 
i can't find the exact PR that fixes it so can't tell you exactly which version to upgrade to unfortunately, but if you can try upgrading to the latest version you should be fine 👍 

hope that helps! 😄

**Comment by nathanleyton** [comment]
Apologies, I should have confirmed that first, I thought we were at the latest version. Thanks

**Comment by nathanleyton** [comment]
@ashharrison90 I just updated to version grafana/grafana:8.4.3 from dockerhub and still have the same issue. I don't see any releases since then. Any idea where I can find the fix? Thanks

**Comment by ashharrison90** [comment]
@nathanleyton ah, maybe it's just in latest main and not yet been released yet... that should help me narrow down where the fix was, let me see if i can find it

**Comment by nathanleyton** [comment]
I just used: grafana/grafana-oss-dev:8.5.0-53658pre and it is working :-) thank you

**Comment by ashharrison90** [comment]
@nathanleyton yeah i still can't seem to find the commit/PR that fixed it 😅 , but looks like it'll be released officially in 8.5.0

**Comment by itzhoujun** [comment]
waiting for 8.5.0
