### ISSUE TITLE
[HTTP API] Change Theme in User Update not works 

### ISSUE THREAD

**Issue by borjapazr** [grafana/grafana#4615]
The title explains it clearly .

**Comment by torkelo** [comment]
Theme is not part of the user api call now, but the `/api/user/preferences` 

And all user preferences are unique per org

**Comment by borjapazr** [comment]
So here if I change the theme field in user json and then I update it, not works? Where I should change the theme with the HTTP api?

Thanks in andvance.

**Comment by utkarshcmu** [comment]
Its on ur profile page under preferences 😊

**Comment by borjapazr** [comment]
Ok, I know do it this way but I thought that I can do it with HTTP api.

Thanks again.

**Comment by utkarshcmu** [comment]
Looks like there is no documentation for preferences api... will try to document it asap... :(

**Comment by borjapazr** [comment]
Thanks for all ☺
