### ISSUE TITLE
[Bug] User preferences changes between organizations

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#4616]
* What grafana version are you using? grafana-3.0.0-beta21459801392.x86_64
* What datasource are you using? InfluxDB 0.12
* What OS are you running grafana on? RHEL7.2
* Chromium: 49.0.2623.108 (64-bit)

In the _Main Org._ if I go to `http://grafana/profile` I could see that my my selected _UI Theme_ is _Light_.

Now I change the org to another one, go to the profile web and _UI Theme_ is set to _Default_.

**Comment by torkelo** [comment]
Yes, user preferences are per org. This should probably be stated in the UI :)
