### ISSUE TITLE
[Bug] Grafana 2.6 and 3.0.0-beta 21459801392 does not work with the new version InfluxDB 0.12

### ISSUE THREAD

**Issue by CHERTS** [grafana/grafana#4617]
I use Grafana 3.0.0-beta 21459801392 on Debian 8.3 + InfluxDB 0.12

Before InfluxDB upgrade from version 0.11 to 0.12 everything worked.
After upgrading to InfluxDB 0.12 graphics are not displayed.

![Error](http://f2.s.qip.ru/L8wqLrdn.png)

![Connect test OK](http://f5.s.qip.ru/L8wqLrdr.png)

In grafana.log
He writes:
>2016/04/08 18:14:06 [I] Completed 192.168.100.40 admin "GET / query HTTP / 1.1" 400 Bad Request 95 bytes in 21930us
>2016/04/08 18:14:06 [I] Completed 192.168.100.40 admin "GET / query HTTP / 1.1" 400 Bad Request 95 bytes in 155335us

In influxd.log writes:
>[http] 2016/04/08 18:14:55 ::1 - cherts [08/Apr/2016:18:14:55 +0500] GET /query?db=collectd&db=collectd&epoch=ms&q=SELECT+mean%28%22value%22%29+FROM+%22df_value%22+WHERE+%22host%22+%3D+%27DC1.corp.a-r-b.ru%27+AND+%22instance%22+%3D+%27C%27+AND+%22type%22+%3D+%27percent_bytes%27+AND+%22type_instance%22+%3D+%27free%27+AND+time+%3E+1458202363s+and+time+%3C+1458212336s+GROUP+BY+time%2815s%29+fill%28null%29%0ASELECT+mean%28%22value%22%29+FROM+%22df_value%22+WHERE+%22host%22+%3D+%27DC1.corp.a-r-b.ru%27+AND+%22instance%22+%3D+%27C%27+AND+%22type%22+%3D+%27percent_bytes%27+AND+%22type_instance%22+%3D+%27used%27+AND+time+%3E+1458202363s+and+time+%3C+1458212336s+GROUP+BY+time%2815s%29+fill%28null%29 HTTP/1.1 400 95 https://xxxxx.ru:3000/dashboard/db/dc1 Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.110 Safari/537.36 e32b4bfe-fd8b-11e5-8078-000000000000 1.870422ms

**Comment by hgfischer** [comment]
I think the problem is a missing `;` at the end of the InfluxDB queries, when you have more then one query per graph.

**Comment by torkelo** [comment]
Yea, this is due to a breaking change in InfluxDB that require a change in how Grafana sends queries.

**Comment by hgfischer** [comment]
Why is this issue closed if it requires a change in Grafana?

**Comment by CHERTS** [comment]
torkelo, why this question is closed, the problem is solved?

**Comment by torkelo** [comment]
Because there are 4-5 duplicated Issue for this (already reported),  and yes it is solved in latest beta3 nightly builds :)

**Comment by CHERTS** [comment]
How can I download the beta3 nightly builds for debian?

**Comment by CHERTS** [comment]
Already found, http://grafana.org/download/builds.html

**Comment by torkelo** [comment]
From nighly builds download page?

Http://grafana.org 

Go to download then click nightly builds

**Comment by hgfischer** [comment]
Can you please upload the deb file to PackageCloud, please? I only get the `version 3.0.0-pre1459399258` of it on the testing repository.

**Comment by torkelo** [comment]
Yes! Will do later today,  check again in 4-6 hours

**Comment by hgfischer** [comment]
@torkelo Still waiting.

**Comment by torkelo** [comment]
https://packagecloud.io/grafana/testing

**Comment by torkelo** [comment]
was uploaded yesterday morning

**Comment by hgfischer** [comment]
There is some issue with the packages then, maybe file naming? I opened #4665
