### ISSUE TITLE
Help users understand which notification policies will be invoked for a new alert

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#46179]
### Problem
We're currently doing a poor job at helping the user understand which notification policies are going to be invoked for a new alert. Users have to
- write label key-value pairs by recall, which is error-prone
- or look up key-value pairs from another screen, having to go back and forth with many clicks
- guess and/or manually look up how their alert will be routed from a potentially long list of policies. There is no direct feedback about this during alert creation and editing of labels

### Solution
We could improve this by:

1. Showing a preview of which alert policies match the labels configured for the alert
2. Allow the user to pick from an existing list of notification policies and pre-fill the labels with the matchers
3. Make it more obvious that there is a default "root" policy that will match and if you don't have any custom policies that one will be invoked

**Comment by konrad147** [comment]
Duplicate of #49009
