### ISSUE TITLE
[Question]/ timer(upper) rendering some unknown values

### ISSUE THREAD

**Issue by varun06** [grafana/grafana#4619]
Hi,

I have a timer where I am posting the values in millisecond. This value is `lag` that we want to track. It goes to 4-5 minutes sometimes, but that's it. But grafana render some values in days and graph is also scaled to days.

![screen shot 2016-04-08 at 11 18 55 am](https://cloud.githubusercontent.com/assets/1284070/14390244/b8fde292-fd7b-11e5-9e49-f642f8548299.png)

When I render value with `count`, it shows the scale in ms, but with upper it just go bonkers. Please help.
Ex

* Data Source: Statsd
* Mac OSX

**Comment by torkelo** [comment]
maybe because of rollups? have you checked the graphite response? Please check what graphite returns using chrome dev tools network tab before opening an issue like this :)
