### ISSUE TITLE
Consolidate sign a plugin instructions

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#46210]
What Happened: 
The 'Sign a plugin' docs include instructions to create a PR to an archived repository. That repository has instructions on how to submit a plugin for review, but having the instructions in the doc itself would be more clear.

https://github.com/grafana/grafana/blob/main/docs/sources/developers/plugins/sign-a-plugin.md?plain=1#L35

**Comment by chri2547** [comment]
Closing this issue because it's over a year old, in an unresourced area, and not likely to be worked on in the next year.
