### ISSUE TITLE
[Feat Req Graphite]: Add graphite version to ds config and to functions, to only show available functions

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4622]
in #461 @tmonk42 added the isNonNull function to grafana.
however this function is not yet released in graphite.

i just verified this by getting the latest release from http://graphite.readthedocs.org/en/latest/releases.html and checking like below.  the only place where this function is mentioned is in the changelog for 0.10, currently unreleased http://graphite.readthedocs.org/en/latest/releases/0_10_0.html

```
~/downloads ❯❯❯ dtrx graphite-web-0.9.15.tar.gz
~/downloads ❯❯❯ cd graphite-web-0.9.15
~/d/graphite-web-0.9.15 ❯❯❯ ack -i isnonnull
docs/releases/0_10_0.rst
63:* ``isNonNull``
~/d/graphite-web-0.9.15 ❯❯❯ 
```

people are trying to use this function and getting graphite key errors because of this.

we should probably mark functions with a warning icon if they're not yet in a graphite stable release, or something

see also https://github.com/graphite-project/graphite-web/issues/1121

**Comment by torkelo** [comment]
ok, thought I checked that that function was in 0.9.13 when i merged it,
