### ISSUE TITLE
Prometheus Alertmanager Channel Could not resolve alerts

### ISSUE THREAD

**Issue by PaulYuanJ** [grafana/grafana#46220]
**What happened**:
1. Use Prometheus Alertmanager as notification channel.
2. Trigger alerts
3. Trigger resolve alerts.
4. Alerts still in Alertmanager until it reaches the "resolve_timeout" of alertmanager.

**What you expected to happen**:
1. Use Prometheus Alertmanager as notification channel.
2. Trigger alerts
3. Trigger resolve alerts.
4. Alerts resolve in Alertmanager.

**How to reproduce it (as minimally and precisely as possible)**:
1. Use Prometheus Alertmanager as notification channel.
2. Trigger alerts
3. Trigger resolve alerts.
4. watch alertmanager UI, it is still there.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.1.4 (6855cdff7c)
- Data source type & version:
- OS Grafana is installed on: Kubernetes
- User OS & Browser: Chrome
- Grafana plugins: Time Series

I have captured the package between grafana and alertmanager.
grafana ip: 10.26.9.1
alertnamager ip: 10.30.176.34

![image](https://user-images.githubusercontent.com/32631327/156716978-cc4969b4-6b10-4191-b1ff-0c0570e818f1.png)

you can see the pic above, the first ping-pong package is "firing", the last ping-pong package is "resolve", follow tcp stream to see the detail, "resolve" message is *not match* "firing" message, so alertmanager will not resolve such alert until it reaches the "resolve_timeout" of alertmanager.

![image](https://user-images.githubusercontent.com/32631327/156718500-9a0a4de6-4c4e-46ae-a20c-1c982c148f6d.png)

![image](https://user-images.githubusercontent.com/32631327/156718755-ce70e188-660b-4ff2-9cbb-5406889ca8d3.png)

**Comment by ashharrison90** [comment]
hi @PaulYuanJ 👋 

can you confirm whether you're using legacy alerting or the new unified alerting? 

thanks! 😄

**Comment by PaulYuanJ** [comment]
I Don't know how to distinguish these 2 kinds alerts you mentioned last email, would you like teach me?



发自我的iPhone


------------------ Original ------------------
From: Ashley Harrison ***@***.***&gt;
Date: Fri,Mar 4,2022 7:03 PM
To: grafana/grafana ***@***.***&gt;
Cc: PaulYuanJ ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [grafana/grafana] Prometheus Alertmanager Channel Could not resolve alerts (Issue #46220)





 
hi @PaulYuanJ 👋
 
can you confirm whether you're using legacy alerting or the new unified alerting?
 
thanks! 😄
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by ashharrison90** [comment]
@PaulYuanJ sure! 😄 

starting in Grafana 8, we rolled out a new alerting system: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
prior to v8.3, you had to [opt in to using this](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/)
after v8.3, it became the default.

if you're running on v8.1.4 and you haven't made any config changes around this, you're probably running legacy alerting. it might be worth trying on the new unified alerting and seeing if that works? 🤔

**Comment by PaulYuanJ** [comment]
Thank you Ashley, I'd like to try this feature and feedback for you :)



发自我的iPhone


------------------ Original ------------------
From: Ashley Harrison ***@***.***&gt;
Date: Fri,Mar 4,2022 7:27 PM
To: grafana/grafana ***@***.***&gt;
Cc: PaulYuanJ ***@***.***&gt;, Mention ***@***.***&gt;
Subject: Re: [grafana/grafana] Prometheus Alertmanager Channel Could notresolve alerts (Issue #46220)





 
@PaulYuanJ sure! 😄
 
starting in Grafana 8, we rolled out a new alerting system: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
 prior to v8.3, you had to opt in to using this
 after v8.3, it became the default.
 
if you're running on v8.1.4 and you haven't made any config changes around this, you're probably running legacy alerting. it might be worth trying on the new unified alerting and seeing if that works? 🤔
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by PaulYuanJ** [comment]
I have tested the unified alerting on v8.4.3 (b7d2911cac), it works fine.

here's the package detail captured between grafana and alertmanager

*alerting*
![image](https://user-images.githubusercontent.com/32631327/156977184-22485ed8-c102-4054-b33a-4094ec2610b2.png)


*resolve*
![image](https://user-images.githubusercontent.com/32631327/156977266-a87028d1-353d-41fc-b31f-973a8eab971c.png)


My question is how to do migration from 8.1.3 to 8.4.X ? we may have lots of alerts needs to be migrated.  :(

**Comment by alexweav** [comment]
> My question is how to do migration from 8.1.3 to 8.4.X ? we may have lots of alerts needs to be migrated. :(

When enabling unified alerting on an instance, it should automatically migrate things for you.

> I have tested the unified alerting on v8.4.3 (https://github.com/grafana/grafana/commit/b7d2911caccbc79c63d2e585b95087824d945ede), it works fine.

That is to say, this bug only appears in legacy alerting? There is a check-box in the unified alerting notifier (Disable resolved message) which seems intended to control this exact behavior.

**Comment by PaulYuanJ** [comment]
Yes, this bug only appears in legacy alerting, I have ever raised issue(30269) for this repo, they are the same issue.

BTW, disable resolved message may be a workaround in some scenes, but it maybe not very fit for my scene. We should have to know if the alerts resolved, while disabled the resolved message the resolve events must depends on the parameter "resolve_timeout" in alertmanager, it will make delay while the alerts resolved.

**Comment by armandgrillet** [comment]
We are closing this issue as legacy alerting is deprecated and will be removed in Grafana 10, if you face issues migrating to Grafana Alerting please let us know.
