### ISSUE TITLE
[Feature Request] In Tooltip Mode = All Series, highlight series under mouse pointer within tooltip

### ISSUE THREAD

**Issue by toddwh50** [grafana/grafana#4624]
When using Tooltip Mode =  All Series, it can be hard to tell which series corresponds to each color in the graph. It would help, as the mouse pointer moves over different series (colors), if the series being pointed to were highlighted some how (font color, bold, etc) within the tooltip as mocked up in image below.

![image](https://cloud.githubusercontent.com/assets/17885456/14398646/5e802192-fdab-11e5-8299-a99f9bedd306.png)

**Comment by torkelo** [comment]
implemented in https://github.com/grafana/grafana/pull/4493
