### ISSUE TITLE
Grafana Tempo plugin does not forward OAuth credentials when getting traces 

### ISSUE THREAD

**Issue by albgus** [grafana/grafana#46248]
**What happened**:
I have a Grafana Tempo instance, for which I have managed to configure authentication by using an oauth2-proxy instance in front of the query-frontend nad using "Forward OAuth Identity" to pass on the JWT issued to Grafana. This appeared to work well, the datasource test works and I can list and search traces. However, when attempting to actually view a Trace I get a 401 unauthorized from ingress-nginx.

**What you expected to happen**:
Requests to `/api/traces` to behave consistently with the connection test and search requests.

**How to reproduce it (as minimally and precisely as possible)**:
1. Setup a Grafana with OAuth authentication
2. Configure a Tempo datasource
3. Enable Forward OAuth identity for Tempo
4. Configure 
5. The datasource connection test works, as well as searching and populating. Viewing a trace does not.

**Anything else we need to know?**:
I ceptured requests by temporarily setting the datasource URL to a server and capturing the request with netcat.

Datasource test:
```
GET /api/echo HTTP/1.1
Host: test-server.example.com:8080
User-Agent: Grafana/8.4.2
Accept: application/json, text/plain, */*
Accept-Encoding: gzip, deflate, br
Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,sv;q=0.7
Authorization: Bearer REDACTED
Sec-Ch-Ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
Sec-Ch-Ua-Mobile: ?0
Sec-Ch-Ua-Platform: "macOS"
Sec-Fetch-Dest: empty
Sec-Fetch-Mode: cors
Sec-Fetch-Site: same-origin
X-Forwarded-For: 10.80.129.21, 10.80.130.115, 10.80.130.115
X-Forwarded-Scheme: https
X-Grafana-Nocache: true
X-Grafana-Org-Id: 1
X-Id-Token: REDACTED
X-Real-Ip: 10.80.129.21
X-Request-Id: be32047aff201208e868b72f7f930321
X-Scheme: https
```

GET /api/traces
```
GET /api/traces/55ea28e45b54a18694c4819c7ced8d2a HTTP/1.1
Host: test-server.example.com:8080
User-Agent: Grafana/8.4.2
Accept: application/protobuf
Accept-Encoding: gzip
```

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: Tempo
- OS Grafana is installed on: grafana docker container
- User OS & Browser: macOS, Chrome 98
- Grafana plugins:
- Others:

**Comment by Chilinot** [comment]
I am also having these issues. Would love if this could be resolved.

**Comment by dansl1982** [comment]
> **What happened**: I have a Grafana Tempo instance, for which I have managed to configure authentication by using an oauth2-proxy instance in front of the query-frontend nad using "Forward OAuth Identity" to pass on the JWT issued to Grafana. This appeared to work well, the datasource test works and I can list and search traces. However, when attempting to actually view a Trace I get a 401 unauthorized from ingress-nginx.
> 
> **What you expected to happen**: Requests to `/api/traces` to behave consistently with the connection test and search requests.
> 
> **How to reproduce it (as minimally and precisely as possible)**:
> 
> 1. Setup a Grafana with OAuth authentication
> 2. Configure a Tempo datasource
> 3. Enable Forward OAuth identity for Tempo
> 4. Configure
> 5. The datasource connection test works, as well as searching and populating. Viewing a trace does not.
> 
> **Anything else we need to know?**: I ceptured requests by temporarily setting the datasource URL to a server and capturing the request with netcat.
> 
> Datasource test:
> 
> ```
> GET /api/echo HTTP/1.1
> Host: test-server.example.com:8080
> User-Agent: Grafana/8.4.2
> Accept: application/json, text/plain, */*
> Accept-Encoding: gzip, deflate, br
> Accept-Language: en-GB,en-US;q=0.9,en;q=0.8,sv;q=0.7
> Authorization: Bearer REDACTED
> Sec-Ch-Ua: " Not A;Brand";v="99", "Chromium";v="98", "Google Chrome";v="98"
> Sec-Ch-Ua-Mobile: ?0
> Sec-Ch-Ua-Platform: "macOS"
> Sec-Fetch-Dest: empty
> Sec-Fetch-Mode: cors
> Sec-Fetch-Site: same-origin
> X-Forwarded-For: 10.80.129.21, 10.80.130.115, 10.80.130.115
> X-Forwarded-Scheme: https
> X-Grafana-Nocache: true
> X-Grafana-Org-Id: 1
> X-Id-Token: REDACTED
> X-Real-Ip: 10.80.129.21
> X-Request-Id: be32047aff201208e868b72f7f930321
> X-Scheme: https
> ```
> 
> GET /api/traces
> 
> ```
> GET /api/traces/55ea28e45b54a18694c4819c7ced8d2a HTTP/1.1
> Host: test-server.example.com:8080
> User-Agent: Grafana/8.4.2
> Accept: application/protobuf
> Accept-Encoding: gzip
> ```
> 
> **Environment**:
> 
> * Grafana version: 8.4.2
> * Data source type & version: Tempo
> * OS Grafana is installed on: grafana docker container
> * User OS & Browser: macOS, Chrome 98
> * Grafana plugins:
> * Others:

Hi, 

I'm also interested in protecting the tempo. Question if your tempo is running in multi-tenancy mode + with GRPC injection? I'm referring to this https://github.com/grafana/tempo/issues/495#issuecomment-1003062769.

 I want to protect the tempo from unauthorized writing/reading.  


thank you in advance

**Comment by gabor** [comment]
note: implementation detail:  the reason for the problem is that the `forward-oauth-identity` ( also `allowed-cookies` ) functionality needs to be specially handled in the backend-codebase, somewhere in `QueryData` 
 : https://github.com/grafana/grafana/blob/ede7b29db5e467fc20dd37d5883214b1ca9d6895/pkg/tsdb/tempo/tempo.go#L60 

one needs to take the headers from `req.Headers`, and apply them to the outgoing http request.

for example, here it is done for the Loki datasource: https://github.com/grafana/grafana/blob/ede7b29db5e467fc20dd37d5883214b1ca9d6895/pkg/tsdb/loki/loki.go#L176-L193

**Comment by aocenas** [comment]
This isn't problem anymore for queries after this PR https://github.com/grafana/grafana/pull/50466. That middleware though isn't added for resource calls https://github.com/grafana/grafana/blob/062d255124160420f48c2af9a09a8cf89681369e/pkg/api/plugin_resource.go#L79 or health check calls https://github.com/grafana/grafana/blob/a14621fff679add99c494628f1fb9a001a734f47/pkg/api/datasources.go#L788.

@marefr wouldn't it make sense to add the middleware also to those 2 calls to make this handling automatic for all datasources?

**Comment by marefr** [comment]
@aocenas yes it would, I was just discussing this with @gabor.

**Comment by marefr** [comment]
@aocenas @gabor are you planning to add middleware also to those 2 calls or should I?

**Comment by gabor** [comment]
@marefr i'm not planning to do it currently, not sure about @aocenas .

**Comment by marefr** [comment]
Created an issue to track this for now https://github.com/grafana/grafana/issues/54135

**Comment by albgus** [comment]
Closing the issue as this has begun working for us after updating to Grafana 9
