### ISSUE TITLE
Template Variables broken with InfluxDB & Grafana

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4625]
* What grafana version are you using : Grafana v3.0.0-beta2 (2016-04-04)
* What datasource are you using?: influxdb-0.11.0-1
* What OS are you running grafana on? 
# uname -a
Linux influxdb-hybrid-860058 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux
root@influxdb-hybrid-860058:~/healthmonitor/influxdb-0.11.0-1# 

Query 1: SELECT count(distinct(eId)) FROM "epdetail" WHERE "alertId" = '1'  AND businessUnit='$businessUnit' AND $timeFilter GROUP BY time(1d) fill(none)

Query 2: SELECT count(distinct(eId)) FROM "epdetail" WHERE "alertId" = '1'  AND businessUnit="$businessUnit" AND $timeFilter GROUP BY time(1d) fill(none)

In the InfluxDB logs i see query as

[query] 2016/04/08 14:58:06 SELECT count(distinct(eId)) FROM ep."default".epdetail WHERE alertId = '1' AND businessUnit = '$businessUnit' AND time > 1458338287s AND time < now() GROUP BY time(1d) fill(none)

Essentially $businessUnit is not replaced with "All/any specific unit selection"

![screen shot 2016-04-08 at 3 00 49 pm](https://cloud.githubusercontent.com/assets/406777/14398659/ba10713a-fd9a-11e5-8421-5e0aabfa8465.png)

If i have just $businessUnit, i see a client side error

Query 3: SELECT count(distinct(eId)) FROM "epdetail" WHERE "alertId" = '1'  AND 
businessUnit=$businessUnit AND $timeFilter GROUP BY time(1d) fill(none)

![screen shot 2016-04-08 at 3 01 45 pm](https://cloud.githubusercontent.com/assets/406777/14398675/d61fe6b2-fd9a-11e5-97ac-06862ffab442.png)

Any suggestions ?

**Comment by torkelo** [comment]
looks like a case difference between the template variable and the one you use in your query

**Comment by deepujain** [comment]
Yes, noticed that.
