### ISSUE TITLE
"NetworkError when attemting to fetch resource -> Unexpected error" with more then 10 queries

### ISSUE THREAD

**Issue by Weuxel** [grafana/grafana#46268]
**What happened**:
When adding more then 10 queries to a panel, in this case showing CPU utilization, the panel throws an error. Even duplicating a working query.
Inspector, Error: NetworkError when attemting to fetch resource
Inspector, Query: Unexpected error

Working Panel:
<img width="1376" alt="Graphana_CPU1" src="https://user-images.githubusercontent.com/1791989/156917840-96ad04c2-b064-4ce6-9eb9-dae2d6d5f855.png">

Duplicate any of the queries:
<img width="1376" alt="Graphana_CPU2" src="https://user-images.githubusercontent.com/1791989/156917915-e0cf0f81-178f-4f29-8d5d-afce71bd1d74.png">

Error messages:
<img width="456" alt="Graphana_CPU3" src="https://user-images.githubusercontent.com/1791989/156917941-d07fec0a-b897-4a76-b045-29b9d75ee900.png">

<img width="493" alt="Graphana_CPU4" src="https://user-images.githubusercontent.com/1791989/156917943-2b4563f0-a0b8-4ad7-b14c-3a77824bad6b.png">

**What you expected to happen**:
Show all queries in the panel.

**How to reproduce it (as minimally and precisely as possible)**:
Add an 11th query.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.5
- Data source type & version: InfluxDB-1.8.3
- OS Grafana is installed on: Linux-5.15.16
- User OS & Browser: MacOS 12.2.1 (21D62), Firefox
- Grafana plugins: Only Core
- Others:

**Comment by Elfo404** [comment]
Hi @Weuxel thanks for reporting this!
Unfortunately i'm not able to reproduce this either in main or 8.3.5 using some sample influx query (i'm adding 25 and i see no error).

Would you be able to share Grafana logs? also maybe the response in the network tab of the browser devtools may help.

Thank you!

**Comment by Weuxel** [comment]
Hi @Elfo404, thanks for looking into this.
Is there any specific log setting i should be setting? 
So far it looks like no log entry is written, when this error happens.

Here is the error in devtools. I am not very knowledgeable in this area, so i hope this is useful information.
<img width="1624" alt="dev" src="https://user-images.githubusercontent.com/1791989/158053722-4ef91baa-439f-4bad-98e5-fa96f369fd61.png">

**Comment by Weuxel** [comment]
Hello,

thank you for the explanation.
It does not look like there is any response to this query.
<img width="1130" alt="Network_Response" src="https://user-images.githubusercontent.com/1791989/158634310-a246444b-7078-4184-be20-df52001e0995.png">

**Comment by Weuxel** [comment]
@Elfo404 I know i am of not much help here. So i created a copy of the dashboard and a user for you for testing, if you are interested.
Would it be ok if i sent you the credentials?

**Comment by Elfo404** [comment]
that won't hurt for sure, looping in @grafana/observability-metrics

**Comment by Weuxel** [comment]
Credentials are sent.

**Comment by Weuxel** [comment]
This is not a Grafana issue, but rather a problem in the nginx config serving this instance.

By setting the client header buffer four times larger then default, the problem goes away.

large_client_header_buffers 4 32k;

Thank you @Elfo404 for pointing this out.
Closing this issue.
