### ISSUE TITLE
Granularity of data misrepresented when two series of different granularities used and larger one is stacked

### ISSUE THREAD

**Issue by erozen** [grafana/grafana#46263]
**What happened**: When displaying two data series of two different granularities (e.g. daily and weekly), if the less granular is overridden to represent as a stacked bar graph, it displays values with the granularity of the smaller dataset.  Non-stacked bar graph works fine.

**What you expected to happen**: The bars to appear with the same width as in non-stacked, but stacked on top of each other instead of overlaid.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a time series graph with two data series of different granularities (sample data attached)
2. Represent the more granular set (Query A - _daily.cost_per_kwh_) as a line chart.
3. Add an override for the less granular set (Query B - _<time-of-day>.cost_per_kwh_) and set 'Graph styles > Style' to 'Bar'.  Notice that the bars are wide and represent the full time window of the data.
5. Add another override for the same query - 'Graph styles > Stack series'.  Set it to 'Normal' and observe the bars reduce in width to the granularity of the other dataset.  When set to back to 'Off' original column width is restored.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker/linux
- User OS & Browser: Firefox 97.0
- Grafana plugins: None
- Others
![1 correct-width](https://user-images.githubusercontent.com/8446560/156898553-4805a424-1848-4461-9412-29f30438028a.png)
![2 incorrect-width](https://user-images.githubusercontent.com/8446560/156898555-3e86a0b4-dc02-477c-bfa8-8df711d09cc1.png)
![3 correct-width-with-stacking-off](https://user-images.githubusercontent.com/8446560/156898556-d607c9fd-067a-40f9-8fd7-f12fa538c305.png)
[Cost per kWh-data-as-seriestocolumns-06_03_2022, 09 11 21.csv](https://github.com/grafana/grafana/files/8191390/Cost.per.kWh-data-as-seriestocolumns-06_03_2022.09.11.21.csv)

**Comment by Elfo404** [comment]
hi @erozen thanks for reporting this.
looping in @grafana/grafana-bi-squad as they own the timeseries plugin

**Comment by bossinc** [comment]
This is a continuation of https://github.com/grafana/grafana/issues/43134
I'll add it todo. @erozen thank you for the detail!
