### ISSUE TITLE
[Bug] Vertical axis labels obscured by axis scale

### ISSUE THREAD

**Issue by toddwh50** [grafana/grafana#4626]
Using Grafana v3.0.0-beta2 (2016-04-04), vertical axis labels are obscured by the numeric axis scale values. See image below.

![image](https://cloud.githubusercontent.com/assets/17885456/14398728/01da9c50-fdac-11e5-956a-2b253fc34aa7.png)

**Comment by torkelo** [comment]
thanks for reporting this! Fixed!
