### ISSUE TITLE
Explore: clicking log level in log volume window does not filter anymore

### ISSUE THREAD

**Issue by oktal** [grafana/grafana#46279]
**What happened**:

After updating to Grafana 8.4.0, we were missing log levels in "Log volume" histogram panel of Explore section. 
After reading about [full-range log volume histograms](https://grafana.com/blog/2022/03/02/new-in-grafana-8.4-how-to-use-full-range-log-volume-histograms-with-grafana-loki/?pg=getting-started-shipping-logs-to-grafana-loki) we were able to get it back by using the following Loki Query:

```
{service_id="my-service"}
  | logfmt
  | __error__=""
  | label_format level=lvl
```

However, when clicking a log level inside the "Log volume" window, logs are not filtered anymore in the Logs section

**What you expected to happen**:

When clicking "info", "warning" or "error", I would expect logs to be filtered by their respective level inside the "Logs" section (e.g, I only want to see errors simply by clicking on the log level).

This was working fine on Grafana 7.x

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.1
- Data source type & version: Grafana Loki Cloud
- OS Grafana is installed on: Ubuntu Linux
- User OS & Browser: Windows, Firefox 97.0
- Grafana plugins:
- Others:

**Comment by Mario-Hofstaetter** [comment]
Reproducible in `v8.4.5` , issue can also be seen here: [https://play.grafana.org/explore Query](https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Berror_level%3D~%5C%22ERROR%7CINFO%7CWARN%5C%22%7D%20%7C%20json%20%7C%20__error__!%3D%5C%22JSONParserErr%5C%22%20%7C%20label_format%20level%3Derror_level%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D)

using `{error_level=~"ERROR|INFO|WARN"} | json | __error__!="JSONParserErr" | label_format level=error_level`

![explorer_4NnBHkJg4J](https://user-images.githubusercontent.com/33002073/164320725-82a364bc-0012-4943-8f1f-f37edbe82a0e.gif)

**Comment by tonychoe** [comment]
Reproducible in v8.5.0. 

Can this be prioritized?

**Comment by ivanahuckova** [comment]
@gabor this is fixed, right?

**Comment by gabor** [comment]
@ivanahuckova yes, fixed in https://github.com/grafana/grafana/pull/49931 . will be in grafana9.1.0. 

(i was thinking about backporting it to 9.0.1, but it's a visual change and there are some minor visual problems that still need ironing out (like, suddenly you have two loading-progress-indicators etc.))
