### ISSUE TITLE
[Feature Request] Combining Single Stat tiles

### ISSUE THREAD

**Issue by sanilveeravu** [grafana/grafana#4627]
I have a dashboard created showing all the single stat tiles with required thresholds turning red when issues comes up.

Is there a feature to create a high level dashboard, which could look at this single stat dashboard to see if any of them are red, then make my overall single stat as red.

Details
* What grafana version are you using? latest
* What datasource are you using? influx
* What OS are you running grafana on? redhat

**Comment by torkelo** [comment]
no, maybe in the future after we tackle alerting

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/2209
