### ISSUE TITLE
[Question] Can't build grafana from source

### ISSUE THREAD

**Issue by navedalam** [grafana/grafana#4629]
I tried building grafana from source by using the steps in README.md. However, when i run `go get github.com/grafana/grafana` I get this error `can't load package: package github.com/grafana/grafana: no buildable Go source files in $GOPATH/src/github.com/grafana/grafana` even though I can see build.go in that directory.
I'm pretty sure I'm doing something wrong but can't figure out what. Some help would be highly appreciated.

grafana version - 3.0
OS - OSX 10.10.5 and RHEL 6.6

**Comment by torkelo** [comment]
That is just a warning you should  expect able to continue with the instructions

**Comment by andreas23** [comment]
Please put a note in the documentation - this was a roadblock for me.

**Comment by daniellee** [comment]
It is in the [docs](http://docs.grafana.org/project/building_from_source/#building-grafana-from-source) already:

> You may see an error such as: package github.com/grafana/grafana: no buildable Go source files. This is just a warning, and you can proceed with the directions.

**Comment by AnithaH** [comment]
while running thr build.go im getting no such file directory. can you help meout for this?
go get github.com/grafana/grafana
can't load package: package github.com/grafana/grafana: no Go files in /mnt/d/gocode/src/src/github.com/grafana/grafana
anithapoojary@LAPTOP-FKM55T27:/mnt/d/gocode/src$ cd $GOPATH/src/github.com/grafana/grafana
anithapoojary@LAPTOP-FKM55T27:/mnt/d/gocode/src/src/github.com/grafana/grafana$ go run build.go setup
stat build.go: no such file or directory
anithapoojary@LAPTOP-FKM55T27:/mnt/d/gocode/src/src/github.com/grafana/grafana$ ls
anithapoojary@LAPTOP-FKM55T27:/mnt/d/gocode/src/src/github.com/grafana/grafana$ go run build.go setup
stat build.go: no such file or directory
