### ISSUE TITLE
Changing the format from MiB to MB etc

### ISSUE THREAD

**Issue by blaztoff** [grafana/grafana#463]
I updated my version of grafana and now all of my results are showing up as MiB or GiB etc instead of MB or GB. Is there a way to update this so it shows up as MB or Gb?

**Comment by rroethof** [comment]
This would be perfect for i.e. diskspace

**Comment by torkelo** [comment]
it is the same as before just the correct unit,One mebibyte (MiB) is 2^20 (i.e., 1024 x 1024) bytes

**Comment by rroethof** [comment]
True, but who uses MiB nowadays ? None of the NOC's where I have worked uses this notation.

**Comment by torkelo** [comment]
I prefer MB as well, but some users requested the correct unit
