### ISSUE TITLE
[BUG] Series color not respected after reload of Series?

### ISSUE THREAD

**Issue by mablae** [grafana/grafana#4630]
Hello, 

for me it seems the color is only stored on the current index of the series. When the count and order changes due to timerange change and activated option: "hide series with only nulls" 
the color is for the new first item is picked up when it has a greater alphabetical order.

Also the option to set a overiding color by series is broken for me. No function after clicking "change"

grafana version: 3.0.0-beta2
datasource: Elasticsearch
os: Ubuntu 14.04

**Comment by torkelo** [comment]
Color is auto assignment based on order returned by time series db. So you can sort the series in you ES query to get consistent colors, or manually asign colors based on series name (or regex using series override)

**Comment by mablae** [comment]
Thanks for the quick reply. I tried the override approach as written above. I was't able to pick a color there. The color picker doesnt show up. Same is working fine with point size for example. 

I am using latest beta2 - maybe it is a regression or some caching issue? Can I rebuild some frontend assets server side using `grafana-cli` or sth?

**Comment by torkelo** [comment]
The series override color picker was recently fixed. But you can also setake color by clicking on the series colored icon in the legend
