### ISSUE TITLE
Grafana does not convert a Tempo span tag including a `.` to an `_` when moving from traces to logs

### ISSUE THREAD

**Issue by hedss** [grafana/grafana#46304]
**What happened**:
When configuring a Tempo data sources 'Traces to log' fields, using a valid span tag including a `.` (for example `service.name` or `http.target`), this does not get reformatted to a valid Loki label name when the LogQL query is sent to the Loki data source.

See the following for a configured data source:
![TempoDatasource](https://user-images.githubusercontent.com/8259026/157101519-b5cef1ff-a847-4819-ab16-2d2e621ec0f0.png)

Here's a screenshot showing Grafana sending `service.name` as a label to lookup via Loki's LogQL query (see bottom of screenshot for internal URI being used including expression):
![IncorrectFormatting](https://user-images.githubusercontent.com/8259026/157101761-95074eb3-77a2-4665-b8ba-a770cdd9eebd.png)

**What you expected to happen**:
Grafana should convert the `.` to a `_` to allow for valid label names. There is already a precedent for this in the way that the Grafana Agent converts metrics/log span names. The following is a screenshot where the label name has been converted manually to show the association required:

![ManuallAlteredLabel](https://user-images.githubusercontent.com/8259026/157101928-696fdd69-96df-4f2a-bfc1-66aff48ad38f.png)

**How to reproduce it (as minimally and precisely as possible)**:
See the above screenshots on how to reproduce accurately, but simply:
* Create a new Tempo data source that has valid trace spans whose key includes a `.` (eg. `service.name`).
* Ensure Loki is ingesting logs which include the same key/value associations with the span tag, where the label for the key is correctly formatted (eg. `service_name`).
* Use the Explorer to discover a valid trace that includes a log entry for the same span key/label key, and click 'Logs' next to a span. It will fail as the `.` has not been formatted to `_`.

**Anything else we need to know?**:
Additionally, it appears the LogQL returned is attempting to query the same label twice. Out of scope for this issue, but curious.

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: Any recent Tempo and Loki data source
- OS Grafana is installed on: Linux/GCP
- User OS & Browser: Grafana 8.4.3 docker image/Firefox (https://www.whatsmybrowser.org/b/8X7SP)
- Grafana plugins: Many, but not relevant.
- Others: N/A

**Comment by connorlindsey** [comment]
Hey @hedss, we recently added the ability to map trace attribute names (`service.name`) to log label names (`service_name`). If you toggle the `Map tag names` option in your Tempo config and map the attribute/label names, that should resolve this issue. Let me know if that works for you

**Comment by hedss** [comment]
Yep, thanks @connorlindsey , I had missed this toggle (muscle memory failure!). Closing.
