### ISSUE TITLE
[BUG][ES] Browser Timezone not taken into account when calculating index patterns

### ISSUE THREAD

**Issue by mablae** [grafana/grafana#4631]
Hello, 

I have encountered a bug with the relative options "This day so far" and "This week so far": 
My data on all systems runs in Europe/Berlin timezone. So does my browser I asume. :smiley: 

The daterange query in the elasticsearch query is correct, but the queried indexes are not, i.e due to 2 hours offset to UTC, only yesterdays index is queried between 0:00 and 2:00. After 2:00 o'clock local time, everything is working as expected again. 

Maybe related to: #3010

grafana-version: 3.0.0-beta2

**Comment by torkelo** [comment]
for ES index daily pattern they are assumed to follow UTC, think logstash uses UTC etc for index naming

**Comment by mablae** [comment]
Odd, thanks
