### ISSUE TITLE
[bug] Don't escape wildcard regexp value in template variable

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4632]
I just upgraded to grafana 3.0.0-beta3 e8a209c. Selecting the `All` option in a template variable will result in a `.*`value being set. The regexp will then be escaped.

Example resulting query for a Prometheus datasource: `fooo{job=~"\\.\\*"}`.

**Comment by torkelo** [comment]
Try updating the variable (in templating / variable view hit update button). 

Can you show your template variable options? and dashboard json (the templating section in it at least).

**Comment by grobie** [comment]
Thanks, updating fixed it indeed. Is there an easy way to do that across all our dashboards?

**Comment by torkelo** [comment]
No :(
