### ISSUE TITLE
403 - Grafana 8.3.5+ on Azure AppService behind Azure Front Door

### ISSUE THREAD

**Issue by heoelri** [grafana/grafana#46321]
**What happened**:

We're operating Grafana (via the grafana/grafana docker image) on Azure App Service behind Azure Front Door. Retrieving data from Azure Log Analytics  via the buildin Azure Monitor 0.3.0 data source plugin.

![image](https://user-images.githubusercontent.com/17407022/157234724-dee0a6aa-03db-435b-8c65-ff8d95515e8b.png)

This went well with Grafana 8.3.4 (and older) releases, with 8.3.5 and newer this does not work anymore and we're getting 403 "origin not allowed" errors when retrieving data from Azure Log Analytics.

Accessing the App Service instance of grafana directly (which is usually limited to Azure Front Door) does still work as expected:

![image](https://user-images.githubusercontent.com/17407022/157235118-6eb88b22-4a9b-4963-a37f-464931bf2126.png)

Accessing it through Front Door though generates the following errors when accessing data:

```text
[Object]()
[status:403]()
[statusText:"Forbidden"]()
[data:Object]()
message:"origin not allowed
"
[error:"Forbidden"]()
response:"origin not allowed
"
[config:Object]()
[url:"api/ds/query"]()
[method:"POST"]()
[data:Object]()
[requestId:"Q115-A"]()
[retry:0]()
[headers:Object]()
[hideFromInspector:false]()
message:"origin not allowed"
```

Based on the various issues we've found we've already added the `GF_SERVER_DOMAIN` and `GF_SERVER_ROOT_URL`, but this hasn't changed anything:

```hcl
    "GF_SERVER_DOMAIN"     = var.frontdoor_fqdn
    "GF_SERVER_ROOT_URL"   = "https://${var.frontdoor_fqdn}:443"
```

> `var.frontdoor_fqdn` contains the fqdn of Azure Front Door. For example `xyzgrafana-global-fd.azurefd.net`. Front Door offers some capabilities to modify headers, but it doesn't have an option like `preserveHostHeaders` as suggested for Apache- and nginx-based reverse proxies.

**What you expected to happen**:

Grafana being able to retrieve data when accessed through Azure Front Door the same way as without Azure Front Door.

**How to reproduce it (as minimally and precisely as possible)**:

As described above, multi-tier architecture with Azure Front Door as a global load balancer and Azure App Service as the compute platform.

**Anything else we need to know?**:

As described our deployment contains Azure Front Door as a global L7 load balancer and Azure App Service as the platform to host the grafana/grafana docker image.

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: Azure Monitor 0.3.0
- OS Grafana is installed on: Docker image `grafana/grafana:8.4.2` on Azure App Service
- User OS & Browser: Windows 10 / Firefox and Edge (no difference)
- Grafana plugins: Various core and custom plugins.
- Others: Azure Front Door + Azure App Service with grafana/grafana docker image and Azure Monitor (Log Analytics) backend.

**Comment by sebader** [comment]
The issue was discussed here already. https://github.com/grafana/grafana/issues/45117
The problem is that with Front Door and App Service as the backend you cannot preserve the host header

**Comment by heoelri** [comment]
cc: @zserge / https://github.com/grafana/grafana/commit/405654b33f205b903caf04ff9d8ba13e6db7ee39#diff-e4d18962aa8417a6897f0da6f0650266898a36364c885286e23b5f9e35395893R29-R32

**Comment by Elfo404** [comment]
Duplicate of #45117

**Comment by sebader** [comment]
@Elfo404 this is not a duplicate! as we state above, the workaround discussed in that thread does not help when running behind Azure Front Door. Hence this new issue. please reopen

**Comment by Elfo404** [comment]
@sebader  whoops, sorry! i only checked the titles and i blindly assumed your last comment implied this was a duplicate of that one, my bad!

**Comment by wbrowne** [comment]
Ping @grafana/backend-platform / abstractions

**Comment by ying-jeanne** [comment]
seems related to https://github.com/grafana/grafana/pull/45911, it is fixed in 8.3.7

**Comment by sebader** [comment]
> seems related to #45911, it is fixed in 8.3.7

I think it is a different issue. This was about the split of the host/port not working properly with IPv6, if I understand this correctly.

This issue here is about the origin being different from the host header when running in a proxied scenario

**Comment by ying-jeanne** [comment]
> > seems related to #45911, it is fixed in 8.3.7
> 
> I think it is a different issue. This was about the split of the host/port not working properly with IPv6, if I understand this correctly.
> 
> This issue here is about the origin being different from the host header when running in a proxied scenario

seeing the origin problem it fixed here: https://github.com/grafana/grafana/issues/45115, the way we split the ipv6 address was buggy, it got a wrong host header, then we compare the origin and host header, it results in different then 403 is returned.

**Comment by ying-jeanne** [comment]
> > seems related to #45911, it is fixed in 8.3.7
> 
> I think it is a different issue. This was about the split of the host/port not working properly with IPv6, if I understand this correctly.
> 
> This issue here is about the origin being different from the host header when running in a proxied scenario

look at the origin issue for that fix: https://github.com/grafana/grafana/issues/45115, the way we parse host is buggy, then when compare to the origin it ends up in difference, then 403 is returned, it happened exactly on 8.3.5. not sure you could do similar work around as in the ticket or not. If yes, you could probably know whether it is the same issue or not.

**Comment by loopfish** [comment]
@heoelri we have just built exactly the same setup as you - FD > App Service > Grafana, and have hit this same issue. Unfortunately, all our automated alerting depends on changes introduced in 8.4.5, so we cannot roll back to 8.3.4.

**Comment by floushee** [comment]
In case anyone needs a fix for this. I checked the code and found an undocumented setting here: https://github.com/grafana/grafana/blob/main/pkg/middleware/csrf/csrf.go

All you need to do is either configure the GF_SECURITY_CSRF_TRUSTED_ORIGINS environment variable when you use Docker and set its value to the host that redirects to it. Or you configure it in the ini file: security section and setting would be csrf_additional_headers

**Comment by heoelri** [comment]
> In case anyone needs a fix for this. I checked the code and found an undocumented setting here: https://github.com/grafana/grafana/blob/main/pkg/middleware/csrf/csrf.go
> 
> All you need to do is either configure the GF_SECURITY_CSRF_TRUSTED_ORIGINS environment variable when you use Docker and set its value to the host that redirects to it. Or you configure it in the ini file: security section and setting would be csrf_additional_headers
> 
> Using that approach I was able to upgrade to Grafana 8.5.5

This is currently actively discussed in https://github.com/grafana/grafana/pull/50589 and https://github.com/grafana/grafana/pull/48120.

**Comment by eleijonmarck** [comment]
@heoelri and @floushee we are working on a way to address the host and header check

**Comment by eleijonmarck** [comment]
@heoelri @floushee we should have a refactored CSRF coming for the next release of v9.0.3.
See line https://github.com/grafana/grafana/pull/50629/files#diff-3f360d342f7cfc6698b58cf7f84614d6588244dd661824909a6436abe6389328R130 for implementation

here we would check both origin and header to be the same values as specified in the configuration or environment variable. See @heoelri s excellent comment https://github.com/grafana/grafana/pull/48120#issuecomment-1152119395 to why this was not working previously.

**Comment by floushee** [comment]
Looks like that change did not end up in the 9.0.3 version that was released :( https://github.com/grafana/grafana/blob/v9.0.3/pkg/middleware/csrf.go

**Comment by eleijonmarck** [comment]
@floushee Was hoping for it to come through. Wait for next release which should be in a week 👍

**Comment by floushee** [comment]
Is there someone to talk to to make sure that this will be included? I don't know the process how this is handled in the Grafana releases.

**Comment by eleijonmarck** [comment]
@floushee the release process was started around the same time for the merge. I overpromised on the v9.0.3 release. It will most definitely be in the v9.0.4. Everything from main will be taken into the release at each stage. So there is no cherry-picking happing. Hope this answers your question

**Comment by floushee** [comment]
I am not sure about the statement with everything from main will move into the release, because there is a fix for the CSRF issue in the main branch for a while now. So we were able to upgrade to Grafana 8.5.6 and we are currently already at 8.5.9. And during that time there were at least the 9.0.2 release where I had hopes that it might be included.

**Comment by eleijonmarck** [comment]
@floushee i see. Let me get back to you on that

**Comment by kminehart** [comment]
The release for 9.0.3 was created from the HEAD of 9.0.x. If it's in main, but not 9.0.x, then that means it won't be released until 10.0.0. In order for your change to land into the next release, make sure it's been backported to 9.0.x (using the `backport 9.0.x` label on the PR), and that the milestone for the backport is set to 9.0.4.

**Comment by vtorosyan** [comment]
Thanks everyone for contributions, I'll close this issue now, please feel free to reopen if anything comes up after testing out the fix.

**Comment by heoelri** [comment]
I've successfully deployed 9.0.4 in my environment this morning and everything works as expected now. Thank you very much @eleijonmarck, @aholyoake-bc et al.!

**Comment by superg28-dm** [comment]
@heoelri were you able to do so using the env variable mentioned previously? Have a similar route in place AFD -> APPGw but then to an istio ingress in AKS where GF is deployed but still getting an 'origin not allowed' error when testing prometheus datasource connectivity

**Comment by heoelri** [comment]
> @heoelri Heyko Oelrichs FTE were you able to do so using the env variable mentioned previously? Have a similar route in place AFD -> APPGw but then to an istio ingress in AKS where GF is deployed but still getting an 'origin not allowed' error when testing prometheus datasource connectivity

Yes, works well in our setup (we've only a single hop -> front door -> appsvc). We've set the following two parameters via envvars:

```
csrf_additional_headers X-FORWARDED-HOST
csrf_trusted_origins https://<frontdoor>.azurefd.net
```

**Comment by loopfish** [comment]
I'd like to add that using the new settings, we've been able to get our setup fully working now:

`
root_url = https://grafana-prod.<ourdomain>.com/
csrf_additional_headers = <empty>
csrf_trusted_origins = grafana-prod.<ourdomain>.com
`
Front Door frontend (https://grafana-prod.<ourdomain>.com) -> App Service (no custom domain needed - FD does the SSL offloading and reverse proxying)

thank you to all involved in this :)
