### ISSUE TITLE
[Bug] Request data from influxDB with IP value as url argument dosen't work in 3.0.0-beta2

### ISSUE THREAD

**Issue by wu8685** [grafana/grafana#4633]
Hi,
I'm using grafana 3.0.0-beta2 on centos 7. When I try to configure a graph panel to retrieve data from InfluxDB, it dosen't work.

I have captured the url sent to influxDB:
http://10.199.184.150:3000/api/datasources/proxy/4/query?db=prometheus&epoch=ms&q=SELECT+mean(%22value%22)+FROM+%22kubelet_pod_worker_latency_microseconds%22+WHERE+%22kubernetes_role%22+%3D+%27node%27+AND+%22instance%22+%3D~+%2F%5E10%5C%5C%5C.199%5C%5C%5C.234%5C%5C%5C.209$%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(5m)+fill(null)
![no working](https://raw.githubusercontent.com/wu8685/tmp/master/grafana-no-working.png)

But the same configuration is working in 2.6.0. And the url is like this:
http://10.199.184.150:3000/api/datasources/proxy/4/query?epoch=ms&q=SELECT+mean(%22value%22)+FROM+%22kubelet_pod_worker_latency_microseconds%22+WHERE+%22kubernetes_role%22+%3D+%27node%27+AND+%22instance%22+%3D~+%2F10%5C.199%5C.234%5C.209$%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(5m)+fill(null)
![working](https://raw.githubusercontent.com/wu8685/tmp/master/grafana-woring.jpg)

Obviously, the difference is how to deal with IP value as url argument: 10%5C%5C%5C.199%5C%5C%5C.234%5C%5C%5C.209 in 3.0.0-beta3, but 10%5C.199%5C.234%5C.209 in 2.6.0

Additionally, after removing the IP query condition from url argument, it works again in 3.0.0-beta2. However, I need this condition.

Could you please take a look at this problem? Thanks.

**Comment by torkelo** [comment]
Try going into the template variable definition  and hit update button

**Comment by torkelo** [comment]
<img width="544" alt="screen shot 2016-04-10 at 15 02 05" src="https://cloud.githubusercontent.com/assets/10999/14412290/3cf6d826-ff2d-11e5-8b2c-a6e5f5c643e8.png">

Works here so I think it's just a matter of you having to update the values of your template variable so that they are not already regex encoded.

**Comment by wu8685** [comment]
Hi,
The problem appears again when I check the "Include All Option". And it works again after I dis-check it. @torkelo

**Comment by torkelo** [comment]
Have you gone into the template variable and updated it and saved ? Is it used in a regex where condition in the query?

**Comment by wu8685** [comment]
It works with influxDB. But after changing data source to prometheus, I encouter the problem again. I have update and save the template. But the strange thing, like I described, is that when I check the "Include All Option", then choose a ip value, it doesn't work, however after I dis-check the option, and also choose the ip value, it does....And the request urls arguments are encoded differently like I described before.
@torkelo 

the template is like this:
![](https://raw.githubusercontent.com/wu8685/tmp/master/template.jpg)

**Comment by torkelo** [comment]
And for the Prometheus query do you use it in a regex condition (in your metric query)

**Comment by wu8685** [comment]
no, this is the query exp in graph:
kubelet_pod_worker_latency_microseconds{kubernetes_role="node", instance="$node",quantile="0.5",operation_type="$operation_type"}
the "$node" stands for the node variable

**Comment by torkelo** [comment]
The query does not look right,  Prometheus need regex match operator to match multiple values
