### ISSUE TITLE
Alerting: Don't allow users to create alert rules against frontend-only datasources

### ISSUE THREAD

**Issue by bestboylm** [grafana/grafana#46347]
Hello 

**What happened**:
I get a API error when I want to create a new alert rule,

The following error appears in the WEB UI interface:
![创建告警规则错误1](https://user-images.githubusercontent.com/18669928/157397943-8b42e1e9-8ec2-48d8-ab1b-31260bbf289a.png)
![image](https://user-images.githubusercontent.com/18669928/157399324-75cb72a6-46f4-4b0b-9e4b-41f0591750e8.png)

The following error appears in the  Grafana log:
`
t=2022-03-09T15:34:53+0800 lvl=eror msg="API error" logger=context userId=1 orgId=1 uname=admin error="Failed to evaluate queries and expressions: failed to execute conditions: plugin unavailable" remote_addr=xx.xxx.xxx.xxx
t=2022-03-09T15:34:53+0800 lvl=info msg="Request Completed" logger=context userId=1 orgId=1 uname=admin method=POST path=/api/v1/eval status=400 remote_addr=xx.xxx.xxx.xxx time_ms=3 size=23 referer="https://mygrafana/grafana/alerting/8EzcRQLnk/edit?returnTo=%2Falerting%2Flist"
`

It works fine when using Explorer
![image](https://user-images.githubusercontent.com/18669928/157398604-f46efbcb-f781-4ee0-95e2-f988e9ec54ba.png)

**What you expected to happen**:
create a normal alert rule

**Environment**:
- Grafana version: v8.3.4
- Data source type & version: JSON plugin & 0.4.1
- plugins link: https://grafana.com/grafana/plugins/simpod-json-datasource/
- OS Grafana is installed on: Centos 7
- User OS & Browser:  windows10 & Chrome/96.0.4664.110

Thanks in advance

**Comment by egorichevs** [comment]
I have the same problem when I set up an alert using the plugin https://grafana-test.int.gpbmobile.ru/grafana/plugins/marcusolsson-json-datasource

Grafana v8.3.4 (a551d74b1)
OS Centos 7.9

**Comment by rasoolim** [comment]
I have the same problem while setting alert (Grafana v8.3.5) 

 
<img width="522" alt="Screenshot 2022-04-26 at 9 03 34" src="https://user-images.githubusercontent.com/1411960/165232426-c412f9ed-4f22-4ac1-bb4c-b2eb2132694d.png">

**Comment by bigunyak** [comment]
I get the same when trying to create a Silence rule.
Grafana v8.3.4

**Comment by arthgajjar-rr** [comment]
getting similiar error when I hit "Run Queries" button because same /eval is called, HELP
<img width="1108" alt="Screenshot 2022-06-14 at 4 57 13 PM" src="https://user-images.githubusercontent.com/97149104/173566969-4f473227-5fc9-4185-b198-f5d81d64b59a.png">

**Comment by CJCShadowsan** [comment]
Same error when I use a kairosdb-datasource (that works in explore and for existing graphs)

**Comment by alexweav** [comment]
It looks like these are both frontend datasources. The alerting engine in the backend can only issue requests using backend plugins. If the plugin is installed in the frontend only, it has no way of seeing it or utilizing it without a browser.

**Comment by alexweav** [comment]
We should not allow users to use frontend-based datasources for Grafana Alerting. Renaming this issue accordingly.

**Comment by CJCShadowsan** [comment]
> It looks like these are both frontend datasources. The alerting engine in the backend can only issue requests using backend plugins. If the plugin is installed in the frontend only, it has no way of seeing it or utilizing it without a browser.

The kairosdb plugin was installed manually putting into /var/lib/grafana/plugins, not via a GUI front-end?

**Comment by arthgajjar-rr** [comment]
@alexweav, the plugin i'm developing has backend: true, alerting: true and metrics: true in plugin.json still getting plugin unavailable

**Comment by gillesdemey** [comment]
A data source is a front-end only data source if it does not include a Go plugin that implements the `QueryData` method. Grafana Alerting runs on the server-side and sends requests to the plugin (via the gRPC protocol) to receive [Data frames](https://grafana.com/docs/grafana/latest/developers/plugins/data-frames/) it can work with for evaluation.

Specifying `{ "alerting": true }` in the [`plugin.json`](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#properties) file indicates that the data source plugin is compatible with Grafana Alerting, if you are building your own data source make sure it is a [backend plugin](https://grafana.com/docs/grafana/latest/developers/plugins/backend/) as this is a requirement for Grafana Alerting to be able to evaluate rules using the data source.

I am still somewhat confused about how the KairosDB plugin is available for selection as a data source for Alerting as it also does not have the `{ "alerting": true }` indicator 🤔

**Comment by gillesdemey** [comment]
Unless someone wants to put in the work to make the [KairosDB data source](https://github.com/grafana/kairosdb-datasource) compatible (by adding a Go back-end to the plugin) it's very unlikely that it would be usable as an alerting source.

We are no longer maintaining it and there is no community maintained fork that we're aware of either.
