### ISSUE TITLE
Alerting: Filter on dashboard variables in panel alert indicator

### ISSUE THREAD

**Issue by vivekanandg** [grafana/grafana#46353]
**What happened**: I was trying out multi dimensional alerts feature on grafana.
I’ve setup an alert for high cpu per pod and linked it to the pod dashboard’s cpu panel. It shows broken symbol on the panel if any of the pods is breaching the limit.

**What you expected to happen**:
I would expect it to show _unhealthy_ only if the currently selected pod is breaching the limit

Grafana version: v8.4.2

![Screenshot 2022-03-09 at 2 44 30 PM](https://user-images.githubusercontent.com/988523/157413253-74ceadc1-26b6-4d45-92d2-6882484a6769.png)

**Comment by peterholmberg** [comment]
The way this works is that the indicator is based on the most severe alert state so if any instance is firing it will show firing. We do not take dashboard variables into account but it might be something we want to do. Removing the bug label and putting this as an enhancement to this feature.

**Comment by gillesdemey** [comment]
We suggest using a "alert list panel" and using the dashboard filter in the "alert instance label filter" instead of the alert tab in the panel editor.
