### ISSUE TITLE
Disable certain relative time ranges provided by default grafana dashboard

### ISSUE THREAD

**Issue by IamShubhamGupto** [grafana/grafana#46357]
**Steps to reproduce**:
Open any grafana dashboard and select the time range button
<img width="405" alt="image" src="https://user-images.githubusercontent.com/32878682/157429525-5582d69a-a43a-48ea-a2d4-29c6a1c2881d.png">

**Actual Result**:
Relative time ranges in minutes, hours, days etc
**Expected Result**
Relative time range only in days

**Relevant WCAG Criteria:** [#.#.# WCAG Criterion](link to https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0)

**Environment**:
- Grafana version: v8.3.0 (914fcedb72)
- Data source type & version: ElasticSearch V7+
- User OS & Browser: Windows 10 & Microsoft Edge
- Others:

**Comment by Elfo404** [comment]
hi @IamShubhamGupto, we use issues to track bugs and actual issues with Grafana. For feature requests please open a discussion at https://github.com/grafana/grafana/discussions/new. It may also help describing your use case and why do you think it would be a needed feature.
