### ISSUE TITLE
Panels with -Dashboard- datasource reference wrong panel in repeated row

### ISSUE THREAD

**Issue by jtommi** [grafana/grafana#46361]
**What happened**:
I was using a datasource variable and a row repeated with that variable.
Inside that row is one panel with a MariaDB query and three other panels taking the data from the first one and applying some transformations.
When selecting a second datasource for that variable, the row repeats, the "main panel" executes its query on the correct datasource, but the 3 other panels still reference the data from the main panel of the first row

![image](https://user-images.githubusercontent.com/33985391/157442588-60545821-b07a-4839-9820-30c4b61b488f.png)

**What you expected to happen**:
I expected the 3 panels of the second row to reference the main panel of the second row

**How to reproduce it (as minimally and precisely as possible)**:
- Create a datasource variable with at least two datasources
- Create a row
- In that row, put a panel that runs a query and choose the datasource variable as datasource
- In that row, put also a second panel that uses "- Dashboard -" as datasource and then the first panel as "Use result from panel"
- Activate "Repeat for" on the row and choose the datasource variable

**Anything else we need to know?**:
I tried to reproduce the issue on play.grafana.com but there is too much stuff not working.
e.g. I wanted to use CloudWatch and CloudWatch-1 as datasources but I get "SharedCredsLoad: failed to load shared credentials file\ncaused by: FailedRead: unable to open file\ncaused by: open /usr/share/grafana/.aws/credentials: no such file or directory""

**Environment**:
- Grafana version: 8.2.1
- Data source type & version: MariaDB 10.4
- OS Grafana is installed on: don't know
- User OS & Browser: Win 10, Firefox 97

**Comment by torkelo** [comment]
reusing the data from another panel is currently not supported for repeated rows:
https://github.com/grafana/grafana/discussions/38182
