### ISSUE TITLE
[bug] When graph has duplicated influxDB queries, it doesn't work in 2.6.0

### ISSUE THREAD

**Issue by wu8685** [grafana/grafana#4636]
Hi,
I m using grafana 2.6.0 . When I duplicate another influxDB query in graph panel, it gives me an error:
InfluxDB Error Response: error parsing query: found SELECT, expected ; at line 2, char 1

Following is the url sent to query influxDB:
http://10.199.184.150:3000/api/datasources/proxy/4/query?epoch=ms&q=SELECT+mean(%22value%22)+FROM+%22kubelet_pod_worker_latency_microseconds%22+WHERE+%22kubernetes_role%22+%3D+%27node%27+AND+%22instance%22+%3D~+%2F10%5C.199%5C.234%5C.209$%2F+AND+%22operation_type%22+%3D~+%2F(create%7Coperation_type%7Csync%7Cupdate)$%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(30s)+fill(null)%0ASELECT+mean(%22value%22)+FROM+%22kubelet_pod_worker_latency_microseconds%22+WHERE+%22kubernetes_role%22+%3D+%27node%27+AND+%22instance%22+%3D~+%2F10%5C.199%5C.234%5C.209$%2F+AND+%22operation_type%22+%3D~+%2F(create%7Coperation_type%7Csync%7Cupdate)$%2F+AND+time+%3E+now()+-+6h+GROUP+BY+time(30s)+fill(null)

There truly is lack of a ";" before the second SELECT. After inserting a ";" before the SELECT in url argument, it works again.

Could you please take a look at this problem? thanks.

PS
It works before:
![](https://raw.githubusercontent.com/wu8685/tmp/master/duplicated-working.jpg)

It doesn't after duplicated, and reports an error:
![](https://raw.githubusercontent.com/wu8685/tmp/master/duplicate-no-working.jpg)

**Comment by torkelo** [comment]
Please mention what version of InfluxDB your using and please search github before opening issue :) 

There already are 3-4 issues for exactly this problem, which are due to InfluxDB made breaking change in their api in 0.11, you need latest beta3 build of Grafana
