### ISSUE TITLE
FR: Dashboard restored from previous versions

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4638]
One should be able to restore a dashboard from a previous version of it if needed. If we can save the history of the dashboard in a history table, then we can always restore it back from any previous version. This will also allow us to see what changes were made in every version by doing a JSON diff.

Also, this feature might get heavy on the database so we can keep this feature configurable for the user if he wants to turn this feature or not.

Somewhat related to #1504

**Comment by utkarshcmu** [comment]
@torkelo 
Started some work in https://github.com/utkarshcmu/grafana/tree/history
It would be great if you can create a history branch in grafana/grafana, where I can merge my changes one by one, and then can be easily reviewed by you and other project collaborators.
Thanks!!!

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/tree/dashboard-history

**Comment by utkarshcmu** [comment]
@torkelo @bergquist 

I have implemented the following in #4653 
1. While saving a dashboard json in the dashboard table, your dashboard json will also be saved in dashboard history table.
2. When deleting a dashboard, rows corresponding to that dashboard in the dashboard history table will also be deleted automatically.

Now, how should we give the user the option to restore his dashboard from the history and compare any of the previous versions with the current version? This is somewhat tricky!!!

IMO, as the first version of the dashboard history feature,
1. We can give the user an option to download historical JSON.
2. Show a JSON diff - https://github.com/flitbit/diff

Any thoughts?

**Comment by torkelo** [comment]
think a simple "restore" and "open" open should good (restore = save over current with old version, open works similar to import, it will open a unsaved dashboard). 

json diff would be nice but not needed for v1 of the feature I think .

**Comment by smalik03** [comment]
any updates on this?

**Comment by utkarshcmu** [comment]
@smalik03 Will work on this as soon as I get some time. Some initial work is done.

**Comment by utkarshcmu** [comment]
I want to use Github repo to store dashboard history, then user can have the whole history in a github repo and we store only the version -> commit mapping in the db.

Any thoughts?

**Comment by torkelo** [comment]
Not sure, sounds like an external plugin that does that, dashboard history if built will be built into grafana.

**Comment by utkarshcmu** [comment]
Dashboard history can be version controlled in Git using wizzy - https://utkarshcmu.github.io/wizzy/

**Comment by jayannah** [comment]
+1

**Comment by torkelo** [comment]
This is now implemented via PR, https://github.com/grafana/grafana/pull/8472 , big thanks to **Walmart Labs** for this contribution. 

Some screenshots:
![image](https://user-images.githubusercontent.com/10999/26879026-eb37d106-4b8f-11e7-8ae6-3d6c3093373e.png)

Summary diff
![image](https://user-images.githubusercontent.com/10999/26879068-0f9c2cd6-4b90-11e7-9a99-6fa0153d1390.png)

Json diff:
![image](https://user-images.githubusercontent.com/10999/26879164-5bca890e-4b90-11e7-997a-1ac7991f9615.png)
