### ISSUE TITLE
Grafana Transformation "Filter data by query" not working

### ISSUE THREAD

**Issue by MatinF** [grafana/grafana#46385]
I'm using the latest Grafana Cloud 8.4.1 release. 

**Context** 
I have Panel 1 in which I have set up 2 queries, `Variables` and `Position` as below:
![image](https://user-images.githubusercontent.com/26184427/157514242-eb69ecdc-f4cf-4e75-82dd-76a2a8544d49.png)

In Panel 2, I have used the query sharing to reference these two queries. Now I wish to use the Grafana Transformation method "Filter by query" to filter the panel to only display one of the queries. However, when I try to do so I simply get the below, which I am not able to modify/use. This seems like a bug and is not covered by the documentation.
![image](https://user-images.githubusercontent.com/26184427/157514382-11573e81-4fad-4e83-b2da-7228e3c4ec67.png)

**Expected observation**
I would have expected a drop down that would display each available query, so that I could specifically select the ones I'd like to show in Panel 2.

**Comment by ivanahuckova** [comment]
The response need to have `refId` for this transform to work. Make sure that the data source you are using implements and supports this.
