### ISSUE TITLE
 Advanced variable format options in pipe mode, $__interval_ms went wrong

### ISSUE THREAD

**Issue by YuanXingH** [grafana/grafana#46396]
**What happened**:

[Add support for variables in plugins](https://grafana.com/docs/grafana/latest/developers/plugins/add-support-for-variables/)

`
import { getTemplateSrv } from '@grafana/runtime';

getTemplateSrv().replace('$__interval_ms', options.scopedVars, 'pipe');
`
![image](https://user-images.githubusercontent.com/26616949/157614798-b2d9548a-ba2e-442c-8ad8-da272a4d9beb.png)
![image](https://user-images.githubusercontent.com/26616949/157614932-fc942b81-8ba4-4bcf-bf20-e2da697953b7.png)

**What you expected to happen**:

$__interval_ms should returns directly

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.5
- Data source type & version:  
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins: 
- Others:
    -   "@grafana/runtime": "^8.2.3"
    -  "@grafana/toolkit": "latest",

**Comment by Elfo404** [comment]
As described in https://grafana.com/docs/grafana/latest/variables/variable-types/global-variables/#__interval_ms , `$__interval_ms` is a number representing the interval in milliseconds (so a single value). You should probably be using 
```ts
getTemplateSrv().replace('$__interval_ms', options.scopedVars);
```

any reason why you are using the `pipe` format?

**Comment by torkelo** [comment]
yea, pipe is only for multi valued variables

**Comment by YuanXingH** [comment]
when i build a plugin， I need to escape the query statement by pipe mode，but i can not use $__interval_ms In the query statement
