### ISSUE TITLE
Value to text on y-axis ?

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4641]
Hi,

Is it possible to replace a value to text on y-axis ?
![graph99](https://cloud.githubusercontent.com/assets/15362041/14413211/249abe46-ff73-11e5-8514-71e27c9cb286.png)
On the graph i have 4 values (3=OK; 2=Warning1, 1=Warning2, 0=Critical), and i would like replace the number to a string. 
Should I use annotations ?

Thx

**Comment by torkelo** [comment]
no this is not possible. 

Not sure what you mean "should I use annotations". Annotations do not seem to solve your requirement
http://play.grafana.org/dashboard/db/annotations
