### ISSUE TITLE
[Question] How to have a stacked graph where user can choose which data points to include?

### ISSUE THREAD

**Issue by abraae** [grafana/grafana#4642]
I want to combine in one dashboard:

a) ability for user to choose which hosts appear in the graph 
b) display a stacked graph, showing a point for the cpu usage of each selected host

Its certainly my lack of understanding, but although I can do either of these individually, I don't see how to combine them.

I can achieve a) as follows:

1) I structure my data like this:

```
cpu,host=a value=22 1460063028000000000
cpu,host=b value=12 1460063028000000000
cpu,host=a value=23 1460063031000000000
cpu,host=b value=14 1460063031000000000
cpu,host=a value=25 1460063035000000000
cpu,host=b value=16 1460063035000000000

```
2) I set up a template variable like this:
  
`$hostname: SHOW TAG VALUES WITH KEY = "host"
`

3) And a metric query like this:

`FROM cpu WHERE host =~ /$hostname$/
`

Now the user can successfully choose the host. The graph shows the sum() of cpu for the selected hosts - great. But not stacked.

And I can achieve (b) as follows:

1) I structure my data like this:

```
a.cpu value=22 1460063028000000000
b.cpu value=12 1460063028000000000
a.cpu value=23 1460063031000000000
b.cpu value=14 1460063031000000000
a.cpu value=25 1460063035000000000
b.cpu value=16 1460063035000000000
```

3) I set up a metric query like this:

`FROM /[a-z].cpu/
`

Now the user can see stacked graph, one point for each cpu. But cannot select which hosts should appear.

Any idea how I achieve both a) and b) at same time?

**Comment by torkelo** [comment]
not sure why you can stack in case 2, just remember to group by the tag.


http://play.grafana.org/dashboard/db/influxdb-templated-queries

**Comment by abraae** [comment]
Fantastic, thank you.
