### ISSUE TITLE
Migrating from SQLite3 to MySql

### ISSUE THREAD

**Issue by ert56** [grafana/grafana#4643]
Hello @torkelo,

I am trying to migrate data from SQLite to Mysql. Sqlite3 is embedded inside Grafana. Is mysql also embedded or we need to install it seperately on our system.?

In my case , it is not able to make the connection to mysql? In defaults.ini file :
type = mysql
host = 127.0.0.1:3306
name = grafana
user = grafana
password = Grafana123

provider = mysql
provider_config = grafana:Grafana123@tcp(127.0.0.1:3306)/grafana

These are the only changes i have made. Do i need to make any other changes in order to make it working. Below is the error i get 

2016/04/11 14:41:16 [I] Database: mysql Connection String is :: grafana:Grafana123@tcp(127.0.0.1:3306)/grafana?charset=utf8
2016/04/11 14:41:16 [I] Migrator: Starting DB migration
2016/04/11 14:41:17 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: dial tcp 127.0.0.1:3306: connectex: No conn
ection could be made because the target machine actively refused it.

There is one section which says to create SESSION table in mysql. How do i connect to mysql and create the table?

**Comment by torkelo** [comment]
Mysql runs in a separate process, the session tables is created automatically
