### ISSUE TITLE
Timeseries: Annotations from multiple datasources do not show the full annotation

### ISSUE THREAD

**Issue by soulgalore** [grafana/grafana#46440]
**What happened**:
We get annotations from multiple Graphite datasources and display them in the same graph. One of the annotations have both subject/description (_"Show each tests"_ in the video)  and if we have two annotations enabled, the description part is not shown, see the video. If we only enable that specific annotation, the annotation is shown correctly.

https://user-images.githubusercontent.com/540757/157834617-b5210725-225f-44e7-87de-731e77a5b128.mp4

**What you expected to happen**:
I expect the annotation to look the same independently if we have multiple annotation datasources enabled or not.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure but you can verify the behaviour at our public instance:
https://grafana.wikimedia.org/d/IvAfnmLMk/page-drilldown?orgId=1&viewPanel=80

**Anything else we need to know?**:
We haven't been able to pinpoint when this happened, but I'm pretty sure it used to work :) I also tested on a 8.4.3 install but there I do not have multiple datasources and I couldn't reproduce it.

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: Two different Graphite instances that stores the annotations. I could reproduce also by storing a annotation in Grafana.
- OS Grafana is installed on:
- User OS & Browser: Reproducible on latest Chrome/Firefox/Safari on Mac OS
- Grafana plugins:
- Others:

**Comment by Elfo404** [comment]
Hi @soulgalore, thanks for reporting this.

I had a look at your public instance, and to me it seems to be working as expected:


https://user-images.githubusercontent.com/1170767/157851745-9397331d-0039-48f7-8fd7-ae9259a15d93.mp4

am i missing something obvious?

**Comment by soulgalore** [comment]
@Elfo404 you are right! This has magically been fixed, so strange! I also verified that it works for me both as logged in and logged out. Thanks for taking the time to have a look!

**Comment by shdubsh** [comment]
I think this needs closer inspection. 

There is missing annotation data in the video @Elfo404 posted:
![Screenshot from 2022-03-11 15-50-47](https://user-images.githubusercontent.com/42356806/157901471-738c7da8-1cdb-4e3c-b8af-e735426ffb57.png)
![Screenshot from 2022-03-11 15-51-07](https://user-images.githubusercontent.com/42356806/157901499-12cb465a-c561-4e51-a399-39ad368dd8e5.png)

When changing the timespan to exclude annotations from different sources, the data in the annotation popup changes:

https://user-images.githubusercontent.com/42356806/157902198-c24fbf55-41d5-4b89-8e38-f2041cb364bf.mov

**Comment by axelavargas** [comment]
Hey ,@soulgalore 😄 I was able to reproduce the issue using your public instance, noticed it worked sometimes but was unstable. I'm moving it to the appropriate team.

@grafana/grafana-bi-squad I had a look at our codebase and noticed that the problem has something to do with `AnnotationTooltip` in the `timeseries` panel, every time we want to display a description in the annotation the plugin expects a `text` prop that is sanitized and rendered. But for some reason, if we have annotations from multiple datasources, sometimes that property is not present, causing this error.

I'm forwarding this to your team, but I'm not 100% sure if it belongs to you 😅 (or if the problem is related to the datasource)

Thank you 🤗

**Comment by soulgalore** [comment]
Ah thanks for looking into it. Just want to add that I could reproduce it also in the "Graph (old)" panel.

**Comment by codeincarnate** [comment]
This one fell through the cracks for me. Definitely seeing it happen in the above linked dashboard at least in certain conditions. Playing around with it it does seem like loading time effects it at least somewhat. It might be a race condition of some kind with the annotation tooltip data expecting data from one datasource but not finding it if it get replaced.

I'm trying to get a stable reproduction of this locally to see what's going on.

**Comment by nmarrs** [comment]
Hi just wanted to double check and see if this is still an issue on the latest version of Grafana. Thanks!

**Comment by soulgalore** [comment]
Ah I've tested  (we are on 9.4.14) and now it works! So I guess it also works with latest but we haven't upgraded, we can close this one.
