### ISSUE TITLE
Repeated rows are not refreshed after change of variable (Grafana 8.4.3)

### ISSUE THREAD

**Issue by machytkafitanalytics** [grafana/grafana#46444]
**What happened**:
We are seeing a bug in latest Grafana 8.4.3. We have dashboard combining several data sources and showing data for multiple shops using repeated rows. When I enter dashboard all works as expected. But after changing selection in variable to see different group of shops only first row and its graphs are fully refreshed, all other rows and graphs just change shop names in titles but graphs are not refreshed showing still previous content. Button "refresh dashboard" in the right top corner of Grafana screen does not work either, only full refresh of the window using "reload this page" button in browser works.

**What you expected to happen**:
All graphs should be properly refreshed.

**How to reproduce it (as minimally and precisely as possible)**:
see in "what happened"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: MySQL + PostgreSQL + Elasticsearch
- OS Grafana is installed on: Debian 10
- User OS & Browser: Ubuntu 20 & latest Chrome
- Grafana plugins:
- Others:

**Comment by cfz** [comment]
observed same issue on 8.4.3(influxdb/centos 7.5/windows edge)
tried roll back to 8.4.2 --> no ok
tried roll back to 8.3.5 --> ok

**Comment by joshhunt** [comment]
Bisect results:

```
f3859f8b60dd27aad138d4ef1dbd349e14665933 is the first bad commit
commit f3859f8b60dd27aad138d4ef1dbd349e14665933
Author: Torkel Ödegaard <torkel@grafana.org>
Date:   Fri Jan 21 11:26:40 2022 +0100

    Templating: Fixes flickering of repeated panels and rows (#43399)

 public/app/features/dashboard/state/DashboardModel.repeat.test.ts | 8 +++++++-
 public/app/features/dashboard/state/DashboardModel.ts             | 1 -
 2 files changed, 7 insertions(+), 2 deletions(-)
```

Looks like issue was introduced in #43399
