### ISSUE TITLE
Content-Security-Policy is set twice in the Data source proxy calls

### ISSUE THREAD

**Issue by rchicoli** [grafana/grafana#46456]
**What happened**:

After upgrading Grafana from version `8.3.3` to the latest release `8.4.3`, the "[Data source proxy calls](https://grafana.com/docs/grafana/latest/http_api/data_source/#data-source-proxy-calls)" stopped to work.

![image](https://user-images.githubusercontent.com/10183963/157886917-8add73dd-225d-404e-94c4-dcc527af0924.png)

**What you expected to happen**:

To be able to access the datasource by the proxy API with no errors and to set the **Content-Security-Policy** in the **defaults.ini** and see it once in the response headers.

![image](https://user-images.githubusercontent.com/10183963/157886994-4eec6186-584d-48a6-8b29-3942c2cee55e.png)

**How to reproduce it (as minimally and precisely as possible)**:

1.) Either checks out Grafana v8.4.3 (or use latest in this case) and start it with the "`make run`" command or download the release v8.4.3 to reproduce this bug.

2.) Afterwards add Prometheus to the Data Sources:

* use the URL http://127.0.0.1:9090/
* make sure the “Access” is set to “Server (default)”

3.) Download the prometheus binary (the version is irrelevant) and run following command:

```bash
prometheus --web.listen-address=127.0.0.1:9090 --config.file=./prometheus.yml \
    --web.external-url=http://127.0.0.1:9090/api/datasources/proxy/1/ \
    --web.route-prefix=/
```

4.) Check for the **Content-Security-Policy** header and verify that “**sandbox**” is set:

```bash
curl -s -i -u admin:admin http://127.0.0.1:3000/api/datasources/proxy/1/
HTTP/1.1 302 Found
Content-Length: 53
Content-Security-Policy: sandbox
Content-Type: text/html; charset=utf-8
Date: Thu, 10 Mar 2022 15:07:04 GMT
Location: /api/datasources/proxy/1/graph
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

5.) Try to change or update this header in the grafana `defaults.ini` configuration file, even though it was disabled by default:

```ini
content_security_policy = true

content_security_policy_template = """script-src 'self' 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' $NONCE;object-src 'none';font-src 'self';style-src 'self' 'unsafe-inline' blob:;img-src * data:;base-uri 'self';connect-src 'self' grafana.com ws://$ROOT_PATH wss://$ROOT_PATH;manifest-src 'self';media-src 'none';form-action 'self';"""
```

6.) After applying the change rerun the same curl command from above. You should see the _Content-Security-Policy_ header set twice:

```bash
curl -s -i -u admin:admin http://127.0.0.1:3000/api/datasources/proxy/1/

HTTP/1.1 302 Found
Content-Length: 53
# defined in the defaults.ini <----------------------------------------- 1#
Content-Security-Policy: script-src 'self' 'unsafe-eval' 'unsafe-inline' 'strict-dynamic' 'nonce-9WKe0+AGmpoDBtHOdhOtEw';object-src 'none';font-src 'self';style-src 'self' 'unsafe-inline' blob:;img-src * data:;base-uri 'self';connect-src 'self' grafana.com ws://localhost:3000/ wss://localhost:3000/;manifest-src 'self';media-src 'none';form-action 'self';
# set in the proxyutil package <---------------------------------------- 2#
Content-Security-Policy: sandbox
Content-Type: text/html; charset=utf-8
Date: Thu, 10 Mar 2022 15:06:06 GMT
Location: /api/datasources/proxy/1/graph
X-Content-Type-Options: nosniff
X-Frame-Options: deny
X-Xss-Protection: 1; mode=block
```

**Anything else we need to know?**:

For this test case, Grafana is the only external endpoint available to the monitoring system and all used Datasources are accessible via the Grafana Datasource Proxy API

**Environment**:
- Grafana version: **8.4.3**
- Data source type & version:
  - Prometheus
- OS Grafana is installed on:
  - Test on Debian and CoreOS systems
- User OS & Browser:
  - Tested on Firefox and Chrome
- Grafana plugins: None
- Others:

**Comment by rchicoli** [comment]
@marefr I've created this new bug report as you requested

**Comment by marefr** [comment]
@rchicoli thanks a lot.

That 2 CSP headers are rendered are not great I guess. Just for understanding, your use case is basically accessing the prometheus UI thru the Grafana datasource proxy? I would recommend accessing prometheus UI directly. Even if we fix so that there will only be one CSP header it will be set to `sandbox` due to security reasons.

**Comment by rchicoli** [comment]
Yes @marefr, you got it right.

There are few other things to mention:

* Lets suppose the infrastructure is extrem strict and there is no way to open up further ports in the firewall.
* The authentication would have be configured for each specific datasource. Imagine, if someone is using Oauth, LDAP or some other authentication mechanisms, this would multiply the configuration setup.
* The Datasources are barely accessed directly, because everything is automated. There is no special need of an extra reverse proxy.
* I also don't think I am the only affected by this security change, because so far it used to work that way. Additionally, I've seen on the internet some people hacking around with a reverse proxy to solve this issue.

Honestly this proxy API is also new for me, but it solves a lot of overhead in the configuration of a monitoring system.
There wouldn't be a problem to have the CPS header set once to `sandbox`, as long there is a way to modify this value. By the way, this would be possible by looking at the [PR](https://github.com/grafana/grafana/pull/46427) and setting the default values are as following:

```ini
content_security_policy = true
content_security_policy_template = """sandbox"""
```

Although I am not so sure, if this would break something else, because it would affect all the api routes `/api/*`

**Comment by ying-jeanne** [comment]
per @marefr reply, the dsproxy should only use CSP policy sandbox and configuration content_security_policy_template in config.ini should be ingored by dsproxy and only used in other cases. The fix would be keep the hardcoded sandbox CSP header and ignore overwrite in the config.ini

**Comment by rchicoli** [comment]
ok @ying-jeanne , it is kinda strange though that security is enforced by default and there is no way to overcome that.

A similar example would be, when an application would only listen on port 443 and the enduser must care of generating the required certificates. Please don't get me wrong, but depending on the use case sometimes some people would only want the application to listen on port 80.

No worries, should I close this issue then or leave it open until this bug is fixed?

**Comment by marefr** [comment]
We'll keep this open since we want to fix the bug
