### ISSUE TITLE
[Feature Request] Save graph series visibility

### ISSUE THREAD

**Issue by troky** [grafana/grafana#4645]
Maybe this option exists but I can't find it.

I want to preserve graph series visibility in legend.

For example:
![2016-04-11 13_50_10-grafana - single energy meter](https://cloud.githubusercontent.com/assets/5564542/14426142/fcc7747a-ffec-11e5-85c4-538d652a4d76.png)

I want to keep Qt, St and Remain time series displayed in legend but hidden from graph.

Is that possible?

**Comment by blak3r2** [comment]
+1 I have a similar use case.

Use Case: I'd like to show only slowest bucket in my histograms so they jump out upon a visual scan.  If you notice them being high, you then generally want to see what percentage are like / the total count of events, etc which is easily accomplished by toggling the series from the legend. 

![image](https://cloud.githubusercontent.com/assets/10790899/21402694/5a7a3f8a-c77f-11e6-9528-65b788e4ff99.png)


Also, another user requested this on stackoverflow here: http://stackoverflow.com/questions/40128685/grafana-toggle-off-series-by-default

**Comment by machytkafitanalytics** [comment]
+1

**Comment by eden881** [comment]
+1

**Comment by philip-wernersbach** [comment]
This would be great for hiding graph series that confuse basic users, while giving power users the option to display the hidden series.

**Comment by PeggyFree** [comment]
+1 , this would be great. I have elementary metrics that must keep visible, and agregated metrics that shoud be shown only when needed.

**Comment by alrghods** [comment]
+1

**Comment by AndrewStickler** [comment]
+1

**Comment by ClayAtWork** [comment]
This would be very useful

**Comment by CoronaExtra** [comment]
I was also looking for an easy way to do this. Hopefully we can get it implemented.

**Comment by js-olx** [comment]
Would be super useful

**Comment by Gauravshah** [comment]
I think from UI perspective it should part of  series override.
<img width="1018" alt="Screen Shot 2019-05-06 at 4 50 10 PM" src="https://user-images.githubusercontent.com/620559/57261989-19c2ba80-701f-11e9-9725-2c27467ea806.png">

I would be able to put in some time for this if there are some directions. is grafana using flot library for plotting ? seems very old version here https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js

**Comment by Gauravshah** [comment]
Should we look at implementing  https://github.com/markrcote/flot-hiddengraphs ?

**Comment by Gauravshah** [comment]
@troky tried implementing via `seriesOverrides`. IMO it is a better way to save the state since thats `edit` UI

**Comment by eherot** [comment]
Potential +1 for implementing via `seriesOverrides` because it's possible to produce a more consistent result when using interactive graph variables. In my particular case, selecting "All" in the variable box causes the metric to sum the values of every item in the metric which is not desired (and renders the scale of the graph useless).

**Comment by cujarrett** [comment]
I'd like this feature as well. It would offer more info without the data skewing the graph on load when there are a variety of values per timeframe sampled.

**Comment by preynoldssco** [comment]
I'd also like this as an option. 
My example: I'd like to make 8 metrics available in one panel and hide 4 of them by default

**Comment by anthonymoon** [comment]
+1 we're uber desperate for this feature.

**Comment by Gauravshah** [comment]
there is an open PR that does this https://github.com/grafana/grafana/pull/17388 unable to get review not sure why

**Comment by karthikkota** [comment]
+1

**Comment by chenzhuoyu** [comment]
> I think from UI perspective it should part of series override.
> <img alt="Screen Shot 2019-05-06 at 4 50 10 PM" width="1018" src="https://user-images.githubusercontent.com/620559/57261989-19c2ba80-701f-11e9-9725-2c27467ea806.png">
> 
> I would be able to put in some time for this if there are some directions. is grafana using flot library for plotting ? seems very old version here https://github.com/grafana/grafana/blob/master/public/vendor/flot/jquery.flot.js

This works for me (I want certain series to be hidden forever, but leave their legend visible).
