### ISSUE TITLE
Trace to logs does not work for milliseconds

### ISSUE THREAD

**Issue by pkrishnanreflexion** [grafana/grafana#46454]
**Describe the bug**
I have few spans that start and end in the same millisecond. The span has tags, "traceID" and "spanID". See attached image.

<img width="820" alt="Screen Shot 2022-03-10 at 7 17 56 PM" src="https://user-images.githubusercontent.com/94964199/157867218-a0afde09-7f97-454a-830e-164c5e895b87.png">

My logs have traceIDs and spanIDs, that are labelled correctly in loki. See attached image.
<img width="775" alt="Screen Shot 2022-03-10 at 7 16 33 PM" src="https://user-images.githubusercontent.com/94964199/157868833-c0fb717f-8ec5-4620-a284-9a03aeaa8b65.png">

When I jump from traces to logs for spans with short duration (same millisecond) I am not able to see the log line in loki. But log volume shows presence of 1 logline
<img width="844" alt="Screen Shot 2022-03-10 at 7 18 21 PM" src="https://user-images.githubusercontent.com/94964199/157842021-53bf06dd-3181-4f64-a560-dce151b0fee0.png">

However, in loki, if I narrow the time range, I can see the logs.

I tried to changing start/end time shift for tempo. But still it does not work.

<img width="602" alt="Screen Shot 2022-03-11 at 3 07 26 PM" src="https://user-images.githubusercontent.com/94964199/157841437-430bfe19-66aa-460b-b32d-da10064e2de1.png">

**To Reproduce**
Jump to logs  from trace with time range very small (upto) 15 milli seconds.

**Expected behavior**
I expect to be taken to my log line with same spanId

**Comment by JavaPerformance** [comment]
I had a similar problem so I started using nanoseconds instead 

```
    struct timespec tp;
    int rc = clock_gettime(CLOCK_REALTIME, &tp);

```
