### ISSUE TITLE
A11y : Focus issues with dash settings/dash links

### ISSUE THREAD

**Issue by zuchka** [grafana/grafana#46499]
**Steps to reproduce**:

try to move a dashboard link in dashboard settings using only a keyboard

**Actual Result**:

We don’t use the same reorderable component

Moving a link down doesn’t keep focus in the same row

UI inconsistency + issue with ID keys probably that make us lose focus?

**Expected Result**

workflow accessible for keyboard-only users

**Relevant WCAG Criteria:**

[2.4.7 Focus visible - Level AA](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#focus-visible)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by jjromary** [comment]
HI, @zuchka This issue is still available?

**Comment by zuchka** [comment]
@jjromary I believe so :)
