### ISSUE TITLE
Keep Dashboards in Sync

### ISSUE THREAD

**Issue by ert56** [grafana/grafana#4650]
Hello @torkelo,

We have multiple deployments of grafana with different grafana.db.

is there any way to keep the grafana dashboards in sync across multiple deployments.?

**Comment by torkelo** [comment]
The easiest is to share the database by switching to a mysql or postgres database, that way everything is shared and in sync (users and Dashboards)

Other way is write custom software that uses the http api to keep the different instances in sync

**Comment by utkarshcmu** [comment]
Try mysql master-master replication if u r using mysql.

**Comment by r3cgm** [comment]
We reached the same conclusion about "write custom software that uses the http api to keep the different instances in sync".  Surely someone else has done this before, right?  If anyone knows of a tool like this please let me know; would rather not have to reinvent the wheel ourselves if someone else already did it.

**Comment by tinder-ubhatnagar** [comment]
@r3cgm You may use https://github.com/utkarshcmu/wizzy

**Comment by r3cgm** [comment]
@tinder-ubhatnagar wizzy is awesome!  Thank you so much for mentioning it; I might not have found it otherwise.

**Comment by marefr** [comment]
We've built a docker image for syncing grafana dashboards, datasources and organization to git using wizzy: https://hub.docker.com/r/tradera/grafana-git-sync/

**Comment by torkelo** [comment]
Nice!
