### ISSUE TITLE
Cannot save single annotation

### ISSUE THREAD

**Issue by zuchka** [grafana/grafana#46500]
**Steps to reproduce**:

try to save a single annotation 

**Actual Result**:

This is a UI issue : there is no button to save the link we have to navigate out of the link tab and then back in to see our changes

**Expected Result**

workflow accessible for keyboard-only users

**Relevant WCAG Criteria:**

[2.1.1 Keyboard - Level A](https://www.w3.org/WAI/WCAG21/quickref/?versions=2.0&showtechniques=335%2C332#keyboard)

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- User OS & Browser:
- Others:

**Comment by xrisaD** [comment]
Hi @yaelleC,
could you provide more details about this issue? With which files is it related?
Thank you

**Comment by zuchka** [comment]
@xrisaD I believe that was the component/file in question: inside the annotations tab in dashboard settings

**Comment by zuchka** [comment]
this appears to be fixed now. Closing for now unless I missed something!

![CleanShot 2022-11-13 at 04 36 21@2x](https://user-images.githubusercontent.com/37156449/201527374-dad269a6-7f66-4422-a177-888e74a7553d.png)

![CleanShot 2022-11-13 at 04 36 15@2x](https://user-images.githubusercontent.com/37156449/201527380-a9f50ea6-a084-40c0-9506-a8fe74a63c24.png)
