### ISSUE TITLE
Upgrade to 3.0 Beta 2 causes Hosted Graphite to return png data 

### ISSUE THREAD

**Issue by joshughes** [grafana/grafana#4652]
Original install was Grafana 2.6.0 on Ubuntu 14.04 with mysql backend. Installed via the official debian package

Install Grafana 3.0 Beta 2 via debian package. 

Restart Grafana and all dashboards are present but any hostedgraphite dashboard is now displaying no data. Looking at the request response I see png data being returned. 

**Request information from chrome**
![request](https://cloud.githubusercontent.com/assets/1671822/14443319/aef54326-fffb-11e5-8f37-3f246923f9ae.png)

**Response information from chrome**
![response](https://cloud.githubusercontent.com/assets/1671822/14443359/f3582376-fffb-11e5-89e9-c230ecfe82cd.png)

I have found similar issues that pointed to the version of graphite needing to be fixed... in this case since 2.6.0 was working and now 3.0 Beta 2 is not... I feel like something else must be going on. I have tried with multiple browser and also with a completely cleared cached to ensure I was not using any old javascript.

**Comment by torkelo** [comment]
since the format is json, not sure why they are returning png data, ,maybe a bug with hosted graphite?

**Comment by joshughes** [comment]
For anyone that find this issue... It was a hosted graphite bug... they started returning png data instead of json. Confirmed that the endpoint was failing on 2.6.0 and 3.0
