### ISSUE TITLE
JSON parsing problem / Prettify

### ISSUE THREAD

**Issue by hoegge** [grafana/grafana#46545]
**What happened**:
When you explore Loki logs JSON Prettify only works on some entries, even though the are all good JSON

![image](https://user-images.githubusercontent.com/15846310/158222815-5c8111f9-c4ac-452f-b92e-fa2f0974ef94.png)

**What you expected to happen**:
Prettifying all JSON content

**How to reproduce it (as minimally and precisely as possible)**:

Hard to tell, since I just see it in my logs. But it also means, most fields are not detected. So there must be some JSON parsing issue. That made me use the `| json` in the query and it showed parsing errors. 

![image](https://user-images.githubusercontent.com/15846310/158223452-4dcd5492-0125-4664-a510-de5a1ee853b7.png)

When I copy the offending JSON to JSONedit I see the issue. There are single quotes inside the JSON text, which Grafana cannot handle?

![image](https://user-images.githubusercontent.com/15846310/158223778-be914348-9244-40cf-b52b-36e3c2907374.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: Loki version 2.4.2 (branch: HEAD, revision: 525040a32)
- OS Grafana is installed on: Docker in Ubuntu
- User OS & Browser: Chrome newest on Mac
- Grafana plugins:
- Others:

**Comment by hoegge** [comment]
Well, actually this SEEMS to be a problem. Even when quotes inside quotes in JSON are escaped correctly, loki does not accep the JSON data. E.g. this is not accepted, although valid JSON:
```
{
  "streams": [
    {
      "stream": {
        "unit": "node-red",
        "flow": "myuplink",
        "section": "http-response"
      },
      "values": [
        [
          "1647357369574000000",
          {
            "payload": "",
            "topic": "",
            "_msgid": "5163eae58450e0b6",
            "headers": {
              "date": "Tue, 15 Mar 2022 15:16:09 GMT",
              "content-length": "0",
              "connection": "close",
              "www-authenticate": "Bearer error=\"invalid_token\", error_description=\"The token expired at '03/15/2022 15:11:08'\"",
              "request-context": "appId=cid-v1:88a4c4fd-f195-45de-afe8-9a5f73e378a8",
              "strict-transport-security": "max-age=2592000",
              "content-security-policy": "default-src 'none'; frame-ancestors 'none'",
              "traceparent": "00-8a692c8defb6da4b9301326fe63b89ed-47f2d0d85ff8b847-00",
              "request-id": "8a692c8defb6da4b9301326fe63b89ed",
              "x-rate-limit-limit": "1h",
              "x-rate-limit-remaining": "9999999952",
              "x-rate-limit-reset": "2022-03-15T15:49:18.5059546Z",
              "x-node-red-request-node": "5f9202b5"
            },
            "statusCode": 401,
            "responseUrl": "https://api.myuplink.com/v2/devices/20162037-2020-4-21-11-55-27/points",
            "redirectList": [],
            "retry": 0
          }
        ]
      ]
    }
  ]
}
```

**Comment by ivanahuckova** [comment]
Yes, prettify only works with valid JSON, so as you already mentioned, when JSON is fixed, prettify works. 

If you are experiencing different issue with Loki accepting/not accepting JSON, please could you create a separate issue and provide more context on this, because I am not sure if the issue is in Grafana or Loki and what do you mean by accepting/not accepting JSON. Thank you! 🙏

**Comment by hoegge** [comment]
The data it chokes on IS valid JSON. Here is the JSON data after I retrieve it from loki with curl which reveals the issue. It does not seem like loke escapes already escaped qoutes again when adding string, which then means the result will be quotes that are note escaped when retrieving them from loki again and then Grafana (of course) chokes on them.

Will open a loki ticket instead
