### ISSUE TITLE
[Feature Request] Don't include hidden variables in URL parameters

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4654]
I use template variables for repeated columns/rows. There is no point in showing a selection box for them, as I always want it to use the "All" value anyway. Similarly, there is no point in appending the variable to URL parameters when creating a link to the dashboard. That variable isn't supposed to be changed.

Version: grafana 3.0.0-beta3

**Comment by torkelo** [comment]
That is not the only scenario where you use hidden variables, it there are a lot of scenarios where they are needed in the URL
