### ISSUE TITLE
Alerting: Need improved notification for alerts in Error state

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#46556]
**What happened**:

The default behavior for alerts is to go to Alerting when there is an execution error (although, this is configurable). Since the alert goes to Alerting, it sends notifications.

Users who are experiencing Alert evaluation failures tend to find this very hard to debug, as it is very difficult to differentiate between a notification sent by a "real" firing alert vs. one sent by a broken evaluation. Usually, this can be determined by the fact that in an Error alert notification, the `value` field will be missing as @annelaurefroment pointed out. However, this is fairly subtle.

**What you expected to happen**:

We should make it more obvious when an alert is firing due to Error state vs. firing because it actually breached the alert condition. A couple ways to do this, open to more suggestions:
- Add a new field to the template language `EvaluationError`, and adjust the default templates to show a warning if it's present. This field could be a simple boolean, or something more complex that actually describes the error.
- Add a new default behavior for execution errors that uses a different message template. Keep the other options around as to not break existing users.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create any alert and don't change the behavior on error.
2. Set up notifications on that alert.
3. Force an evaluation error. One way is to shut down the DB that a datasource is bound to.
4. Observe the resulting notification. It is nearly indistinguishable from a normal alerting message, aside from some likely missing fields.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.x
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by alexweav** [comment]
The PR https://github.com/grafana/grafana/pull/49352 adds a `grafana_state_reason` annotation which is very similar to option 1 above.

**Comment by alexweav** [comment]
There is another in-flight PR which augments this and should close this issue.

**Comment by grobinson-grafana** [comment]
Do we need to make this change if we change the default state from **Alerting** to **Error**?
