### ISSUE TITLE
Unable to modify Grafana's dashboard variable name color

### ISSUE THREAD

**Issue by jfagoagas** [grafana/grafana#46569]
**What happened**:

I'm trying to change Grafana's color palette but I'm not able to modify the variable's name box color (next image is the default blue)
<img width="852" alt="Screenshot 2022-03-15 at 09 36 11" src="https://user-images.githubusercontent.com/16007882/158338146-3fb4a9e2-a398-4e5c-8703-3d2ba163bc3f.png">

I was able to modify the vast majority of the Grafana's color palette changing the following https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/themes/palette.ts:
<img width="486" alt="Screenshot 2022-03-15 at 09 42 33" src="https://user-images.githubusercontent.com/16007882/158339273-87fefca7-d5dd-40a9-ae63-0a2aae9e30d5.png">

But once I've compiled all Grafana's frontend I'm still seeing the following and  https://github.com/grafana/grafana/blob/main/public/sass/_variables.light.generated.scss (obv, my own generated file once the compile is done) still shows the default color `#1F62E0`
<img width="852" alt="Screenshot 2022-03-15 at 09 36 11" src="https://user-images.githubusercontent.com/16007882/158338146-3fb4a9e2-a398-4e5c-8703-3d2ba163bc3f.png">

I don't know if this is an issue or maybe I'm doing it wrong.

**What you expected to happen**:

The expected behaviour is to have this variable name color like the one define in `blueDarkText` or `blueLightText` whether your Grafana theme is.

**How to reproduce it (as minimally and precisely as possible)**:

1. Edit https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/themes/palette.ts and change the colors for the ones you want.
2. Follow the [Developer Guide](https://github.com/grafana/grafana/blob/HEAD/contribute/developer-guide.md) focusing on the frontend side with `yarn install --immutable && yarn start` 
3. Create a new Grafana's dashboard
4. Create a new variable
<img width="1496" alt="Screenshot 2022-03-15 at 10 09 33" src="https://user-images.githubusercontent.com/16007882/158344217-c2f2f77b-aef8-4eef-b680-a383be12f46d.png">
5. Save the dashboard configuration

**Anything else we need to know?**:

**Environment**:
- Grafana version: Version 8.5.0-pre (commit: unknown-dev, branch: main)
- Data source type & version: N/A
- OS Grafana is installed on: Docker environment using Makefile `build-docker-full`
- User OS & Browser: MacOS 12.2.1 & Chrome Version 99.0.4844.51 (Official Build) (arm64)
- Grafana plugins: None
- Others: None

**Comment by ivanahuckova** [comment]
This doesn't seem like a problem with Grafana. The color is then probably coming from somewhere else. You can find out where is ti coming from in developer tools and modify it there, if needd.
