### ISSUE TITLE
Table Panel : Column filter does not maintain state

### ISSUE THREAD

**Issue by zuchka** [grafana/grafana#46562]
**What happened**:

Column filters do not always maintain their state. Filter values are lost when user resizes a column or refreshes panel

see [this forum thread](https://community.grafana.com/t/dashboard-refresh-clears-table-column-filter/57999/3) for more

![3e5edae9dc1ff227b3ac6e306a60949bd7d96653](https://user-images.githubusercontent.com/37156449/158282068-0d89fd9b-b8a0-42dd-9acd-5f13f20cd365.gif)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

[add a filter to this table](https://play.grafana.org/d/8dMUIHP7z/filter-state-on-resize-or-refresh?orgId=1) and then resize or refresh panel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.3
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ChenChen0718** [comment]
Grafana version: 8.3.3 also can reproduce this issue. Are there any workaround or solution?

**Comment by mindw** [comment]
Another way of triggering it is by having auto refresh enabled - both filter and sorting is lost.
