### ISSUE TITLE
[Bug] Unexpected encoding of template all value

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4656]
Since updating to grafana 3.0.0-beta3 one of our dashboards isn't fully working anymore. The all value is rendered as `{value1, value2}` for a Prometheus datasource. Example result of a query: `{app="api-pss", proc=~"{staging,web}"}`. It'd need to be `staging|web` to be a valid regex.

I already updated and even re-created the template variable to no avail.

**Comment by torkelo** [comment]
Is this in  metric query or annotation query ? What's the dashboard json?
