### ISSUE TITLE
PolyStat is giving empty when metric vaue is non-numerical

### ISSUE THREAD

**Issue by sunnygadumadeinvizag** [grafana/grafana#46564]
When we try to build a polystat panel grafana with numerical values the polystat is plotting properly but when one metric is having non-numerical value, then panel simply showing empty.

**What happened**: Polystat is showing empty when metric value is non-numerical

**What you expected to happen**:Polystat show value when even metric value is non-numerical

**How to reproduce it (as minimally and precisely as possible)**: Push data with atleast one metrc with non-numerical value and build polystat panel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5
- OS Grafana is installed on: Windows
- User OS & Browser: Chrome
- Grafana plugins: Polystat

**Comment by torkelo** [comment]
please open issues here: https://github.com/grafana/grafana-polystat-panel 

polystat only supports numbers
