### ISSUE TITLE
[Question] How to config request method of datasource graphite in grafana 2.~ or 3.0

### ISSUE THREAD

**Issue by kevin5476** [grafana/grafana#4657]
If my url only expose render_method: 'GET', in grafana 1.9 I can config it as below

datasources: {
 graphite: {
   type: 'graphite',
   url: "http://127.0.0.1:8181/tsdr/nbi",
   render_method: 'GET'
 }
},

now I want to use grafana 2.6 or 3.0, how should I do ?

**Comment by torkelo** [comment]
Grafana 2.x - 3 only support POST request for graphite render call, all graphite installs support this

**Comment by kevin5476** [comment]
thanks for your answer, because I config 2.x datasource graphite url as 1.9 (http://127.0.0.1:8181/tsdr/nbi) , but it doesn't work. Do you have any suggestion for me ?

**Comment by torkelo** [comment]
Upgrade graphite, probably an extremely old version
