### ISSUE TITLE
Shared crosshair not working

### ISSUE THREAD

**Issue by jonkerj** [grafana/grafana#46581]
**What happened**:
I enabled "shared crosshair" in my dashboard with time series graphs. The crosshair is not getting shared, but remains per graph. When I change the graphs to "Graph (old)" they _do_ have a shared crosshair.

**What you expected to happen**:
A shared crosshair in time series graphs.

I understand from #30564 and #33433 that this functionality should be available, as the boxes are checked and this seems merged since v8.0.0 (according to `git tag --contains 9f8fa421`).

**How to reproduce it (as minimally and precisely as possible)**:
- Install Grafana (8.3.6 in my case)
- create at least two time series graphs
- edit graph settings, enable "Shared crosshair" in the bottom
- go back, observe crosshair not being shared
- change graphs to "Graph (old)"
- go back, observe crosshair to be shared

**Anything else we need to know?**:
I have not tried v8.4.x yet

**Environment**:
- Grafana version: v8.3.6
- Data source type & version: Prometheus, InfluxDB and fetzerch-sunandmoon-datasource
- OS Grafana is installed on: Talos OS v0.4.3 (Linux 5.15.26 + Kubernetes v1.23.4)
- User OS & Browser: MacOS + Chrome
- Grafana plugins: fetzerch-sunandmoon-datasource

**Comment by ivanahuckova** [comment]
Hello @jonkerj I wasn't able to reproduce this on 8.3.6, but could you please share the dashboard json that would help us with investigations.

**Comment by jonkerj** [comment]
I've exported it to [a gist](https://gist.github.com/jonkerj/889b57d69fa03b9c23d20f02232d8e1d)

**Comment by Rohlik** [comment]
I have pretty much same issue.
I'm having very easy dashboard with one old Graph panel and one Time series panel.
When I hover on the old panel, crosshair is shared with the new one, but when I hover on the new one, crosshair is not shared with the old one.
Grafana v8.2.3 and latest Google Chrome on Linux.

**Comment by zoltanbedi** [comment]
Hey @jonkerj,
Thanks for reporting this. I was able to reproduce this but also there is a workaround. In order to see the shared crosshair work with the time series panel you need to refresh your browser or navigate away from your dashboard and back. I know this is not ideal so we will take a look at this and try to fix it.

https://user-images.githubusercontent.com/13729989/165470575-d8718d27-0c03-4560-a3de-6f88c486a7bd.mp4

@Rohlik shared crosshair should work with old and new panel as well.

**Comment by pschichtel** [comment]
Has this been fixed?

**Comment by leeoniya** [comment]
yes

**Comment by pschichtel** [comment]
just tested it. I can confirm that it works. Differently compared to the older version and it seemed to be a little "sluggish", but I guess that would be a follow-up bug report. I'd be fine with closing this.
