### ISSUE TITLE
[Feature Request] Enable test connection before datasource save

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4658]
So far the "Test Connection" button only appears once a datasource has been added+saved. It'd be helpful to check all settings even before the initial save by displaying the button already.

**Comment by torkelo** [comment]
not easy to do right now as all the code that uses the datasource proxy (and the frontend) requires a persisted data source

**Comment by mattttt** [comment]
Perhaps combine the save and test into a single action button "Save & Test". Testing is an inexpensive call and even if you know everything is right, it's nice to be confirmed.

**Comment by torkelo** [comment]
That is what the Test connection does right now (save and test)

**Comment by torkelo** [comment]
was quite simple to combine the save and test to a single action, think that was a good idea @mattttt, now it is more clear that you have to save to test (before click on Test Connection I guess some users would be confused by the message that also said "Datasource saved" at the same time)
