### ISSUE TITLE
Y Axis label garbled with values on Y Axis

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4659]
What grafana version are you using : Grafana v3.0.0-beta2 (2016-04-04)
What datasource are you using?: influxdb-0.11.0-1
What OS are you running grafana on? # uname -a Linux influxdb-hybrid-860058 3.13.0-24-generic #47-Ubuntu SMP Fri May 2 23:30:00 UTC 2014 x86_64 x86_64 x86_64 GNU/Linux 

<img width="80" alt="screen shot 2016-04-12 at 12 55 18 am" src="https://cloud.githubusercontent.com/assets/406777/14453400/79cbb2fe-0049-11e6-9c4c-60901c7ea0fd.png">

Chrome browser

**Comment by torkelo** [comment]
fixed in beta3 build
