### ISSUE TITLE
[Feature Request] Instruct variables' values in url when accessing

### ISSUE THREAD

**Issue by wu8685** [grafana/grafana#4660]
I have integrated Grafana with another Web html by iframe. It is supported to show different templating variables' value depend on url or something else in http request.
For example, if a url was: **http://10.199.184.150:8080/dashboard/db/apps?namespace=paas-staging&app=apiserver&pod=cw2gm** , the templating variables' values could be reset depend on the url arguments and the panels could refresh automatically.
![](https://raw.githubusercontent.com/wu8685/tmp/master/instruct_by_url.jpg)

Or could it work around?

**Comment by torkelo** [comment]
you can set template variables via url paramters using syntax `var-<var_name>=value`

**Comment by wu8685** [comment]
It is exactly what I need. Thanks. @torkelo
