### ISSUE TITLE
[Question] How to access added page in routes.js

### ISSUE THREAD

**Issue by tuyy** [grafana/grafana#4662]
Hello, bro!

Two weeks ago, It was operating correctly.

After merged latest grafana, It can't access custom pages.

I added route-info in core/routes/routes.js.

<img width="825" alt="2016-04-12 6 33 43" src="https://cloud.githubusercontent.com/assets/13308314/14456246/e4272512-00de-11e6-9d2f-121439841ace.png">

Problem is,

<img width="401" alt="2016-04-12 6 34 32" src="https://cloud.githubusercontent.com/assets/13308314/14456388/a09b3ed6-00df-11e6-9982-f6012bf0cefc.png">

This should not be connected from the outside.

I want to connected directively.

If the connection is moved from the grafana.
(If click custom button)

<img width="1069" alt="2016-04-12 6 35 03" src="https://cloud.githubusercontent.com/assets/13308314/14456452/f66d7bda-00df-11e6-9ac7-e281cebaf4f7.png">

Did you ever add?
Do I need to add for access page in outside?

**Comment by torkelo** [comment]
Did you rerun grunt?

**Comment by torkelo** [comment]
routes.js is moved to typescript now
