### ISSUE TITLE
error when MORE queries for 1 graph - grafana 3.0 beta

### ISSUE THREAD

**Issue by tomazbracic** [grafana/grafana#4663]
I wanted to create a dashboard with 2 queries (or more), but I am receiving this error

{
  "error": "error parsing query: found SELECT, expected ; at line 2, char 1",
  "message": "error parsing query: found SELECT, expected ; at line 2, char 1"
}

And I can see that "q" for query has 2 SELECTs without ";" character. 

This approach worked on grafana 2.6.

**Comment by torkelo** [comment]
Please search github before posting , probably the 5th time this is reported,  problem is due to InfluxDB breaking change, you need latest grafana 3.0 beta3 build
