### ISSUE TITLE
Support dynamic registration of components

### ISSUE THREAD

**Issue by radiohead** [grafana/grafana#46633]
### What

In #46532 we've introduced a generic component registry, but removed the ability to dynamically register component schemas, instead relying on a static component registry for now.

We should figure out a new, dynamic registry, that can be used to add new components without having to rely on Wire and hard-coded list of registered components.

Additionally, as a stretch goal, it would be nice to support ability to register new components during runtime, but that might be out of scope of this issue.

### Why

We need at least dynamic compile-time component registration to support Grafana Enterprise, since that codebase is not linked to the main one via code and instead uses its own DI system (because we cannot expose certain proprietary parts in an OSS repo).

Additionally, this should improve QoL for developers / owners of new components.

**Comment by radiohead** [comment]
There's some WIP in - https://github.com/grafana/grafana/tree/intentapi/dynamic-compregistry, I'm planning to continue with this once we're in Phase 2. Going to hold this off until then.

**Comment by sdboyer** [comment]
Conceivably something we'll return to when needed in the future, but not applicable in new coremodel arch now.
