### ISSUE TITLE
[Bug] Unnecessary whitespace after graph-legend section

### ISSUE THREAD

**Issue by banzayats** [grafana/grafana#4664]
I'm using Grafana version: 3.0.0-pre, commit: v2.6.0-1629-gd3a4b7a on CentOS 7

When I add a legend to the graph, the whitespace appears:

![err](https://cloud.githubusercontent.com/assets/477161/14459581/73d7dcce-00c1-11e6-9785-162dc3ae0323.png)

There is no empty space in my old Grafana:

![ok](https://cloud.githubusercontent.com/assets/477161/14459616/9d3eed50-00c1-11e6-9b34-46af781a7608.png)

I've found an additional parameter in the new version:

- before:

```
<section class="graph-legend graph-legend-table">...</section>
```

- after:
```
<section class="graph-legend graph-legend-table" style="height: 204px;">...</section>
```

**Comment by torkelo** [comment]
should be fixed in latest nighly
