### ISSUE TITLE
Dashboard variable selections don't persist after clicking the breadcrumb for search

### ISSUE THREAD

**Issue by tcpdumper** [grafana/grafana#46659]
**What happened**:
When viewing a dashboard and setting some variable drop down selections, clicking the the breadcrumb at the top left and then cancelling (ESC) will revert the selections to some default state. Clicking on the magnifying glass (Search Dashboards) does not revert the state.

**What you expected to happen**:
Cancelling out of search dashboards should retain whatever values you selected in the variables before.

**How to reproduce it (as minimally and precisely as possible)**:
- open a dashboard with variable dropdowns created
- select some variables 
- click on the breadcrumb (on any folder)
- hit the ESC key or the X to close it

**Anything else we need to know?**:
No

**Environment**:
- Grafana version: 8.3.3
- Data source type & version: prometheus v2.18.0
- OS Grafana is installed on: Ubuntu 16.04
- User OS & Browser: MacOS 12.2.1 Safari
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
I was able to reproduce this as well. 
https://user-images.githubusercontent.com/30407135/158995409-b84949ce-d906-4389-9552-be16bceb8fdf.mov
