### ISSUE TITLE
Alerting: Sharing alert rule UIDs across Grafana instances

### ISSUE THREAD

**Issue by abestel** [grafana/grafana#46666]
**What happened**:

I am trying to synchronize alerts across Grafana instances (I have one instance of Grafana per execution environment, all sharing Datasources, Folders, Dashboards and Alerts).
As far as I can understand, each "item" in Grafana has two ids:
- a UID that is automatically generated, and can be overridden when creating an item (ie can be shared across instances of Grafana)
- an ID, that is "local" to a Grafana instance

For folders and dashboards, what I'm doing is basically to always use the same UID across all instances.
For the ID, it depends on what is present in the target instance:
- if the instance has the folder/dashboard, I set it to the current id of the folder/dashboard on the instance
- otherwise, a new folder/dashboard needs to be created and the id is set to `null`

I was hoping the behavior would be the same for the new alerting API... however if I set the uid of a rule that does not exist yet, the creation of the rule fails, with the following log:

```
failed to update rule group: failed to get alert rule XXXXXXXX: could not find alert rule" error="failed to update rule group: failed to get alert rule XXXXXXXX: could not find alert rule"
```
When setting the UID to null, the request works and the alert is created... but with a different UID.
For now I'm able to work around this by considering that the "id shared across instances" for alert rules is the title, but that's not great.

Further context:
**Endpoint:** https://mygrafanainstance.com/api/ruler/grafana/api/v1/rules/Namespace

**Failing request**
```json
{
   "name":"Alert",
   "interval":"1m",
   "rules":[
      {
         "expr":"",
         "for":"5m",
         "annotations":{
            "__dashboardUid__":"XXXX",
            "__panelId__":"123"
         },
         "grafana_alert":{
            "id":null,
            "uid":"ALERT_UID",
            "namespace_id":123,
            "namespace_uid":"XXXX",
            "orgId":1,
            "title":"Title",
            "condition":"B",
            "data":[
               {
                  "refId":"A",
                  "queryType":"",
                  "relativeTimeRange":{
                     "from":1800,
                     "to":0
                  },
                  "datasourceUid":"XXX",
                  "model":{
                     "datasource":{
                        "type":"prometheus",
                        "uid":"XXX"
                     },
                     "exemplar":true,
                     "expr":"...",
                     "interval":"",
                     "intervalMs":15000,
                     "legendFormat":"Value",
                     "maxDataPoints":43200,
                     "refId":"A"
                  }
               },
               {
                  "refId":"B",
                  "queryType":"",
                  "relativeTimeRange":{
                     "from":0,
                     "to":0
                  },
                  "datasourceUid":"-100",
                  "model":{
                     "conditions":[
                        {
                           "evaluator":{
                              "params":[
                                 15000
                              ],
                              "type":"gt"
                           },
                           "operator":{
                              "type":"and"
                           },
                           "query":{
                              "params":[
                                 "A"
                              ]
                           },
                           "reducer":{
                              "params":[
                                 
                              ],
                              "type":"avg"
                           },
                           "type":"query"
                        }
                     ],
                     "datasource":{
                        "type":"__expr__",
                        "uid":"-100"
                     },
                     "hide":false,
                     "intervalMs":1000,
                     "maxDataPoints":43200,
                     "refId":"B",
                     "type":"classic_conditions"
                  }
               }
            ],
            "updated":"2022-03-16T16:13:54Z",
            "intervalSeconds":60,
            "version":4,
            "rule_group":"Alert",
            "no_data_state":"NoData",
            "exec_err_state":"Alerting"
         }
      }
   ]
}
```

**Working request**
```json
{
   "name":"Alert",
   "interval":"1m",
   "rules":[
      {
         "expr":"",
         "for":"5m",
         "annotations":{
            "__dashboardUid__":"XXXX",
            "__panelId__":"123"
         },
         "grafana_alert":{
            "id":null,
            "uid":null,
            "namespace_id":123,
            "namespace_uid":"XXXX",
            "orgId":1,
            "title":"Title",
            "condition":"B",
            "data":[
               {
                  "refId":"A",
                  "queryType":"",
                  "relativeTimeRange":{
                     "from":1800,
                     "to":0
                  },
                  "datasourceUid":"XXX",
                  "model":{
                     "datasource":{
                        "type":"prometheus",
                        "uid":"XXX"
                     },
                     "exemplar":true,
                     "expr":"...",
                     "interval":"",
                     "intervalMs":15000,
                     "legendFormat":"Value",
                     "maxDataPoints":43200,
                     "refId":"A"
                  }
               },
               {
                  "refId":"B",
                  "queryType":"",
                  "relativeTimeRange":{
                     "from":0,
                     "to":0
                  },
                  "datasourceUid":"-100",
                  "model":{
                     "conditions":[
                        {
                           "evaluator":{
                              "params":[
                                 15000
                              ],
                              "type":"gt"
                           },
                           "operator":{
                              "type":"and"
                           },
                           "query":{
                              "params":[
                                 "A"
                              ]
                           },
                           "reducer":{
                              "params":[
                                 
                              ],
                              "type":"avg"
                           },
                           "type":"query"
                        }
                     ],
                     "datasource":{
                        "type":"__expr__",
                        "uid":"-100"
                     },
                     "hide":false,
                     "intervalMs":1000,
                     "maxDataPoints":43200,
                     "refId":"B",
                     "type":"classic_conditions"
                  }
               }
            ],
            "updated":"2022-03-16T16:13:54Z",
            "intervalSeconds":60,
            "version":4,
            "rule_group":"Alert",
            "no_data_state":"NoData",
            "exec_err_state":"Alerting"
         }
      }
   ]
}
```

(only the `grafana_alert.rules.uid` has changed from `ALERT_UID` to `null`)

**What you expected to happen**:

A request with a `null` id and a specific `uid` is created with a new `id` and the specified `uid`.

**How to reproduce it (as minimally and precisely as possible)**:

Setup an alert, keep the payload (removing the `id` from it), delete the alert and try to recreate using said payload.

**Anything else we need to know?**:

/

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Running in Kubernetes using the community helm charts
- User OS & Browser: MacOs / Firefox 97.0.2 (but the APIs are accessed using cURL mostly)
- Grafana plugins: /
- Others: /

**Comment by bygui86** [comment]
@abestel do you have the link to the documentation of the `/api/ruler`? I don't find it...
and from my understanding that's the only way to get a full list of alert rules... am I wrong?

**Comment by armandgrillet** [comment]
Provisioning solves this: https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting

**Comment by darks00ul** [comment]
@armandgrillet 

> Provisioning solves this: https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting

It solves but in my case I'm still trying to figure out how to provisiong alert on Grafana when a organization isn't created yet...
For example if I use Grafana provision (datasources, alerts, etc)  on a new grafana instance I get an error because the organizations are not yet provisioned.

In my case I was trying to use provisioning but because of this I fall back to this method, having the same issue with UID...

**Comment by yuri-tceretian** [comment]
Hi @darks00ul, it is not possible to create any resource until the organization is created. Currently, it is not possible to provision organizations, and it is tracked at https://github.com/grafana/grafana/issues/12119

The regular alerting API does not support user-defined UIDs. Currently, if UID is specified in the request, the API tries to find a rule with this UID and fails the request if the rule does not exist. This was implemented as a mechanism to manage concurrent updates to a single group because API manages rules by a group but in the database, they are stored individually. Therefore, missing UID is treated as a situation that there was a concurrent update to the group that deleted the rule.
Technically it is possible to change this logic, but it will change the semantics of the API, which warrants a broader discussion. 

@armandgrillet did you reopen it to support user-defined UIDs?

**Comment by armandgrillet** [comment]
@yuri-tceretian Thanks for the detailed answer, I think we can close this again based on your feedback.
