### ISSUE TITLE
Unable to delete disabled Library Panels

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#46672]
**What happened**:
Library panels can be disabled due to a deprecated plugin. Not allowing them to be used in this case is fine, but the delete icon is also disabled and panels are unable to be deleted. Users may want to clean up library panels from deprecated plugins.

**What you expected to happen**:
Even if a panel cannot be used in this case, it should still be able to be deleted.

**How to reproduce it (as minimally and precisely as possible)**:
Have a library panel for a deprecated plugin (or change https://github.com/grafana/grafana/blob/main/public/app/features/panel/components/VizTypePicker/PanelTypeCard.tsx#L33 to be true). Navigate to library-panels, and see the whole card is grayed out and not clickable.

**Environment**:
- Grafana version: 8.4.3

**Comment by dorianm** [comment]
Hello, I've got this issue in my Grafana instance (v9.0.7 in Grafana Cloud). Is there any workaround to delete them ?

**Comment by ivanortegaalba** [comment]
Hi @dorianm, yes there is a way to work around this issue 😄 You can just disable the `user-event: none` with the dev tools for the library item.

![2022-09-02 18 24 30](https://user-images.githubusercontent.com/5699976/188197467-02acf0c0-6fe9-4227-a5de-5f538bca5109.gif)
