### ISSUE TITLE
[Bug] InfluxDB wrong character escaping

### ISSUE THREAD

**Issue by enigmapsi** [grafana/grafana#4667]
Hi,

I've tried Grafana beta 1 to grafana-3.0.0-beta31460425332 (last nightly build) and I've seen this isue with InfluxDB that doesn't seem to have been reported before.

This is the query in the query editor:
`SELECT 8 * derivative(mean(value), 1s) FROM "snmp_rx", "snmp_tx" WHERE "host" = '$host' AND "type_instance" = '$networkInterface' AND $timeFilter GROUP BY time($interval);`

The $host variable is populated like this:
`SHOW TAG VALUES FROM "snmp_rx", "snmp_tx", "snmp_value" WITH KEY = "host" ORDER BY ASC`

The $host variable contains dots and brackets, and Grafana seems to escape them - not sure if that happens in the templating section or in the  code that produces the final query, but the end result is not valid, as follows:

`SELECT 8 * derivative(mean(value), 1s) FROM "snmp_rx", "snmp_tx" WHERE "host" = 'CES00000019-01 \(213\.218\.194\.197\)' AND "type_instance" = 'GigabitEthernet0_0' AND time > 1460415600s and time < now() GROUP BY time(1m);`

Please note the escaping in `CES00000019-01 \(213\.218\.194\.197\)`

Error message:
```
{
  "error": "error parsing query: found \\(, expected identifier, string, number, bool at line 1, char 98",
  "message": "error parsing query: found \\(, expected identifier, string, number, bool at line 1, char 98"
}
```

OS is centOS 7.

Couldn't find a way around this till now.

I don't think this was reported anywhere else before.

Thanks

**Comment by torkelo** [comment]
Can you show the template variable options? Have you enabled multi value or all value? In that case you need to use the variable in a regex operator context in your influxdb query. 

Since you do not have that, try disabling all value (or multi value), and the regex escaping should be disabled.

Also show the influxdb query? Are you using the query editor or manual entered raw query ?

**Comment by enigmapsi** [comment]
1. None of the "multi-value" or "Include All option" is selected, bot are disabled. Only one host can be selected at a time.
2. I am using the raw query editor.
3. This issue was not present in 2.6, it only appeared in 3.0, immediately after upgrade.

**Comment by torkelo** [comment]
Please use the query editor, for raw queries grafana does not know if your using a template variable in a regex context or not so defaults to regex encoding. If you use the query editor it will know that your condition is a regex condition and will only apply regex escaping when required.

**Comment by enigmapsi** [comment]
Hi again,

I've had success using the query editor, thanks (although the previous Grafana versions did not have this restriction).

Anyway, the escaping problem is still present, this time in the *Template variables* section, and there is no query editor there.

I have the following template variables:
```
$host	            SHOW TAG VALUES FROM "snmp_rx", "snmp_tx", "snmp_value" WITH KEY = "host" ORDER BY ASC
$networkInterface	SHOW TAG VALUES FROM "snmp_rx", "snmp_tx" WITH KEY = "type_instance" WHERE "host" = '$host';
```
The second query fails, with: 
```
Templating
Template variables could not be initialized: error parsing query: found \(, expected identifier, string, number, bool at line 1, char 102
```
The `$host` variable contains brackets and dots which get incorrectly escaped when used in the second query (for `$networkInterface`).

**Comment by torkelo** [comment]
try WHERE "host" =~ /$host/   as a work around. 

Wil have to investigate a fix for the templating scenario, maybe parse the the string and look if the template variable is enclosed in quotes then do not do regex escaping.

**Comment by hanynowsky** [comment]
why was this closed. It is still a blocking issue.
In variables, if a value from the retrieved list has any special character even a dot, the templating fails on client side  and one needs to reload the whole dashboard for the query to complete.

It happens that our server names uses this pattern: serverXXXX.rackX
If we use a pattern like serverXXXX_rackX. The templating succeeds.

Followed the work around above with no success.
Both query types are affacted: SELECT .... and SHOW TAG VALUES .....

**Comment by dannyfreak** [comment]
> why was this closed. It is still a blocking issue.
> In variables, if a value from the retrieved list has any special character even a dot, the templating fails on client side and one needs to reload the whole dashboard for the query to complete.
> 
> It happens that our server names uses this pattern: serverXXXX.rackX
> If we use a pattern like serverXXXX_rackX. The templating succeeds.
> 
> Followed the work around above with no success.
> Both query types are affacted: SELECT .... and SHOW TAG VALUES .....

Same here, in variable I have group name that uses the pattern xx.xxx and this causes "error parsing query: found \., expected..." workaround also doesn't work for me.

**Comment by sawo1337** [comment]
Why is this closed? Same issue here with the latest version and URL in the variable. All the above workarounds didn't help.
