### ISSUE TITLE
Changelog for 8.4.4 missing

### ISSUE THREAD

**Issue by dreua** [grafana/grafana#46684]
**What happened**:
Debian and [grafana.com](https://grafana.com/grafana/download) offers an Update to 8.4.4

**What you expected to happen**:
Find a changelog entry explaining the changes made in this new version.

**Comment by ivanahuckova** [comment]
You can find release notes https://grafana.com/docs/grafana/next/release-notes/release-notes-8-4-4/ and https://github.com/grafana/grafana/releases/tag/v8.4.4. Where exactly is changelog missing?

**Comment by dreua** [comment]
Yes, they were added in the meantime, I couldn't find anything when I created this issue yesterday. (I distinctively remember looking at https://github.com/grafana/grafana/blob/main/CHANGELOG.md and the Github Releases.) It would be nice to have the release notes prior or in sync with the official releases.

**Comment by ivanahuckova** [comment]
I think this could have been because of yesterday's issues with github. But I am glad it is resolved! Closing the issue. 🙂
