### ISSUE TITLE
[Question] Using template variables with SimpleJson

### ISSUE THREAD

**Issue by dannaril** [grafana/grafana#4668]
Hi All,
I'm trying to use this plugin: https://grafana.net/plugins/grafana-simple-json-datasource and build my own data series. I've follow all the instructions of User Guide and I can plot the example series (Upper_25, Upper_50, etc) in the chart. However, when I try to use metrics or create a template variables, grafana is not recognizing it. 
Is it possible to grafana provide the same resources as we have using InfluxDB, or  any other data source, using a SimpleJson source?
Thank you very much!
BR,
Danilo

**Comment by torkelo** [comment]
not sure the simple json datasource supports templating yet, please open an issue for that with that plugin

**Comment by dannaril** [comment]
Hello Torkel,
Thank you very much for your early reply.
Just one more question, I'll need to use grafana to visualize my data which is on Redis database, my first try is to use a Simple Json data source.
Do you know or you can recommend a good approach to have my Redis data using grafana tool?
Thanks again!
BR,
Danilo
