### ISSUE TITLE
Alerts broke on upgrade to 8.4.0+

### ISSUE THREAD

**Issue by fredrik84** [grafana/grafana#46680]
**What happened**:
Alerts stopped working on 8.4.0+ with this very tiny error:
`Execution Error: request handler error: plugin unavailable`
Turned on debugging to get more information but none was given.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
We have slack + email notification channels set up, but other than that we just run very basic alerts.

**Anything else we need to know?**:
I have tested and the issue occurs when I upgrade to 8.4.0 and still exists in 8.4.3.
Workaround is downgrade to 8.3.7 where it works.

**Environment**:
- Grafana version: 8.4.0+
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux + docker
- User OS & Browser: 
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
Grafana's transition from legacy alerting to the Unified Alerting platform represents a big step forward. But, there are many factors that can influence behavior, and it is often hard for the community to troubleshoot issues without a thorough understanding of your unique setup. 

- Please list ALL configuration options related to alerting. You can find these in the `Alerting` and `Unified Alerting` sections of Grafana's config file. If you are now using or have previously used the beta version of `ngalert` (released with Grafana 8), please note that too.
  - you can use [this table](https://github.com/grafana/grafana/pull/42200#issue-1062269188) to better understand how configuration options can interact with each other

**Comment by fredrik84** [comment]
The only setting we have pertaining Alerting is `max_annotation_age = 3M`. Otherwise it is fully default settings.
So if I read that table properly we are using `Legacy Alerting` by not setting enabled for either.

**Comment by zuchka** [comment]
@fredrik84 what grafana version?

**Comment by fredrik84** [comment]
@zuchka alerting broke on both 8.4.0 and 8.4.3. Works on 8.3.7 which is what we are running right now.

**Comment by fredrik84** [comment]
I tried upgrading a couple of days ago again and it still broke on version 8.5.2.

**Comment by armandgrillet** [comment]
> Alerts stopped working on 8.4.0+ with this very tiny error: Execution Error: request handler error: plugin unavailable

Alerting is not a plugin, is there a reason why you think both are related? Furthermore, legacy alerting is now deprecated and we suggest you to migrate to Grafana Alerting (which is enabled by default in Grafana >= 9.0).
