### ISSUE TITLE
Azure Monitor - wrong version of the plugin installed

### ISSUE THREAD

**Issue by olivierperdaens** [grafana/grafana#46691]
Resetting the Client Secret does not reset at all the client secrets... It redirects to the home page without doing anything

Using Grafana 8.4.3

**Comment by andresmgot** [comment]
I suspect you may be using an old version of the plugin, that should be a button, not a link:

![Screenshot from 2022-03-17 17-27-27](https://user-images.githubusercontent.com/4025665/158847703-4e5bde18-30cf-4b73-9925-dc178d8184d7.png)

What version of the plugin are you using? did you install it or you are using the one bundled with Grafana?

**Comment by olivierperdaens** [comment]
I'm using the 0.3.1 plugin version. The installation of the plugin was a long time ago, but I think I installed it manually (with grafana-cli)

**Comment by andresmgot** [comment]
then yes, you have hit this issue: https://github.com/grafana/grafana/issues/43401

You need to uninstall that plugin and it should fallback to the version bundled with Grafana. I thought this issue should have gone away with Grafana 8.4.x but it seems that it's still there.

We should probably bump the version of the core plugin to check if that finally solves the issue. I believe setting it to 1.0.0 should be fine.
