### ISSUE TITLE
[Feature Request] Please provide linux static binaries (amd64?) for builds/releases

### ISSUE THREAD

**Issue by gena01** [grafana/grafana#4669]
Having linux static binaries would make installing and using grafana on a non glibc system much easier. One use case is on Alpine Linux which is gaining popularity as the base image for Docker containers. This would provide for a much smaller working docker image(s) among other benefits.

**Comment by grobie** [comment]
I'm not sure this will be easy. There might be dependencies which require CGO.

**Comment by torkelo** [comment]
Grafana requires glibc , if you need build that does not you can compile custom build yourself,  one that does not include sqlite3

**Comment by gena01** [comment]
what about linking glibc statically?

**Comment by torkelo** [comment]
I think there was some things in go / gccgo that could not be statically linked (something with dns look that used system calls), but maybe you can now
