### ISSUE TITLE
docker build failed with Dockerfile.ubuntu

### ISSUE THREAD

**Issue by ggpaue** [grafana/grafana#46707]
**What happened**:
docker build from source failed
**What you expected to happen**:
docker build should success
**How to reproduce it (as minimally and precisely as possible)**:
docker build -t grafana:test -f Dockerfile.ubuntu .
**Anything else we need to know?**:
I keep getting this error, can someone tell me how to bypass this error in docker build?
```
 > [js-builder  6/12] RUN yarn install --pure-lockfile:
#27 1.765 yarn install v1.22.5
#27 2.511 [1/5] Validating package.json...
#27 2.583 [2/5] Resolving packages...
#27 5.871 [3/5] Fetching packages...
#27 8.977 [1/4] Resolving packages...
#27 9.608 [2/4] Fetching packages...
#27 10.53 error https://registry.yarnpkg.com/resolve/-/resolve-1.12.0.tgz: Extracting tar content of undefined failed, the file appears to be corrupt: "ENOENT: no such file or directory, chmod '/usr/local/share/.cache/yarn/v6/npm-resolve-1.12.0-3fc644a35c84a48554609ff26ec52b66fa577df6-integrity/node_modules/resolve/test/resolver/mug.js'"
#27 10.53 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
#27 66.26 info There appears to be trouble with your network connection. Retrying...
#27 69.88 info There appears to be trouble with your network connection. Retrying...
#27 73.99 info There appears to be trouble with your network connection. Retrying...
#27 78.02 info There appears to be trouble with your network connection. Retrying...
#27 82.08 info There appears to be trouble with your network connection. Retrying...
```
------
executor failed running [/bin/sh -c yarn install --pure-lockfile]: exit code: 1

**Environment**:
- Grafana version: v7.5.11
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ivanahuckova** [comment]
This seems to be an issue with your network rather than Grafana. I recommend to ask for advice on our community site: https://community.grafana.com/
