### ISSUE TITLE
[FR - UX] Fixed Navbar when scrolling

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#4670]
Hi,

First of all, thanks for your awesome work!

I want to propse you the possibility to set the navbar as fixed when scrolling down and set the time picker/non-pinned side menu as a floating panel.

It will grant the user to do not lose the focus on the panel if he wants to set a new time (i.e going back on time when you zoom on panel) or wants to load another dashboard in new tab.

We actually have huge dashboards with a lot of panels, so it will be very helpful!

As a mockup (setting navbar and tabberdview with position:fixed):
![positionfixedtimepicker](https://cloud.githubusercontent.com/assets/13196237/14470225/95c0d10c-00e8-11e6-849e-fa4ac673d962.jpg)

![positionfixed](https://cloud.githubusercontent.com/assets/13196237/14470227/95c3aca6-00e8-11e6-9ca2-cfae7a95a863.jpg)

![positionfixedsidemenu](https://cloud.githubusercontent.com/assets/13196237/14470226/95c31354-00e8-11e6-9276-1d5024961e13.jpg)

What do you think?
Thanks, 
Best regards

**Comment by roscoe57** [comment]
+1

**Comment by roscoe57** [comment]
I commonly like to use a row of SINGLESTATs for summary information i like to keep on the screen always.

It would be cool if you could also consider allowing in some a row to be sticky as well. 

![stickysinglestatrow](https://cloud.githubusercontent.com/assets/10706467/20262663/0e1eced0-aa5b-11e6-8cc5-73b2c73989f1.JPG)

**Comment by cemo** [comment]
I see that some issues are already closed. @torkelo  I am curious why you did not like this idea so much?

**Comment by torkelo** [comment]
not sure, why do you think I do not like it?

**Comment by cemo** [comment]
Actually I saw #1562 this and thought you did not like idea.

**Comment by torkelo** [comment]
well I am not a big fan of floating navs that's true.

**Comment by divishkumar** [comment]
+ 1 for fixing the position of the navbar. I'd also like to include the template variables of the dashboard in that scope as its very useful to change the variables while not losing focus of the panel.

**Comment by timtofan** [comment]
+1

and also +1 to fixed rows, we usually have a summary row on the top and then many rows with  in-depth graphs, would be cool to have a checkbox to freeze a row when needed

**Comment by torkelo** [comment]
implemented in master https://www.youtube.com/watch?v=BC_YRNpqj5k&t=16s
