### ISSUE TITLE
Grafana 8.4.4 cannot loadZabbix-plugin

### ISSUE THREAD

**Issue by cristanxu** [grafana/grafana#46716]
**What happened**:
Installed Zabbix plugin, saved and tested successfully, but when clicked 'Dashboards', the page pop-up error message: Failed to get plugin dashboards on the right corner.
**What you expected to happen**:
Need to connect Zabbix dashboard
**How to reproduce it (as minimally and precisely as possible)**:
click install Zabbix on the grafana page
Test successfully
clicked dashboards and pop-up error message
**Anything else we need to know?**:

**Environment**:
centos7.9
- Grafana version:
- grafana-8.4.4-1.x86_64
- Data source type & version:
- OS Grafana is installed on:
- localhost
- User OS & Browser:
- Chrome
- Grafana plugins:
- zabbix plugin: 4.2.5
- Others:
![1](https://user-images.githubusercontent.com/92715864/158932186-d05d7aad-7f76-41fc-
![2](https://user-images.githubusercontent.com/92715864/158932195-71326e44-7285-4893-9c2e-54d885dbe74d.jpg)
8052-65affed8c770.jpg)
![1](https://user-images.githubusercontent.com/92715864/158932257-7e4d8859-2e43-4d33-a6da-9dd273c448f3.jpg)

Zabbix server: 5.0

**Comment by ivanahuckova** [comment]
Thanks for creating this issue, [cristanxu](https://github.com/cristanxu).Because Zabbix is a third-party plugin, I think the best place to start is to file in issue in that specific repo: https://github.com/alexanderzobnin/grafana-zabbix/issues
