### ISSUE TITLE
Starting Grafana in HA mode from two VM instances caused the inconsistent DB state

### ISSUE THREAD

**Issue by yuwaMSFT2** [grafana/grafana#46718]
**What happened**:
We host Grafana in a scaleset with 2 VMs; both run with the same configuration and point to the same PostgreSQL DB.
Occasionally after the provisioning, we saw DB error when trying to login. It complained about missing column "pq: column \"help_flags1\" does not exist"

After some investigation, this seems a race condition in Grafana migration code when there are multiple instances trying to start at the same time.
I looked at one DB which has this problem:
The user table is in incorrect state (missing columns help_flags)

![image](https://user-images.githubusercontent.com/23645697/158941093-148944ff-e457-4fe5-8900-2fbbe23e626e.png)

And also there is another temporary table user_v1 which is supposed to be deleted during migration:
![image](https://user-images.githubusercontent.com/23645697/158941111-4f364f82-9354-43b0-9390-6e70f377b112.png)

Surprisingly, it has the column help_flags1.
 
According to the code here:
https://github.com/grafana/grafana/blob/main/pkg/services/sqlstore/migrations/user_mig.go#L48

Grafana first tries to rename user table to user_v1; then create a new user table; then copy user_v1 to user; then add a column help_flags1 to user table; finally drops user_v1.
So if it executed correctly, there should be no way user table doesn't have the field but user_v1 does. However, this could happen if there is another instance tried to do the same thing. From the migration log, I saw the above sequence happened; then the process was repeated but only for the first 3 steps (rename user to user_v1; create new user table; copy data over (no new columns). This explained the result.
 
I also checked the logs of one instance. The log seems to verify this. Both instances started migration at the same time, and caused the above race condition. Then both failed and restarted, which resumed the migration. But it just started from the last failure point so the side effect was persistent now.

**What you expected to happen**:
The DB is in consistent state

**How to reproduce it (as minimally and precisely as possible)**:
As described above, running two computing instances pointing to the same PostgreSQL DB.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- 8.4
- Data source type & version:
- OS Grafana is installed on:
- Ubuntu
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by yuwaMSFT2** [comment]
@jongyllen @taleena @timlevett

**Comment by leandro-deveikis** [comment]
Hi! 
Another team at Grafana is already working on this issue. 
This is the original issue #41834 and there is some work done that is on beta state #44101 to have a locking mechanism for DB migration on a HA environment

**Comment by yuwaMSFT2** [comment]
Thanks @leandro-deveikis for the update!
It can be a bit hard to control the sequence of startup of the instances. We would like to try it out once you have the feature implementation.

Meanwhile, is there a way to recover if hitting the issue? Is there a way to force a new migration manually to fix the DB?

**Comment by timlevett** [comment]
>Meanwhile, is there a way to recover if hitting the issue?

[Per the upgrade docs](https://grafana.com/docs/grafana/latest/installation/upgrading/#backup), you could recover from your backup if you have hit a corrupted state. 

Also you could scale down to 1 instance for the update, then scale back up. Alternatively you could do a blue/green deployment.

There are many options here for doing this.

**Comment by ying-jeanne** [comment]
Hey @yuwaMSFT2, you could do the workaround as mentioned above, or in the latest 8.4.x version, this problem should be solved by this PR https://github.com/grafana/grafana/pull/45447/files#diff-b2b080d123efb0cece25e7b261e82f88fe2e35bf80193e42af65e725e1104861, If the problem persists, please don't hesitate to reopen the ticket.
