### ISSUE TITLE
Tempo logs is searching the wrong time range

### ISSUE THREAD

**Issue by Jojoooo1** [grafana/grafana#46731]
**What happened**: When trying to search logs from tempo span the search query seems to look for a wrong time range

**What you expected to happen**: Search related logs from tempo trace

**How to reproduce it (as minimally and precisely as possible)**: click on "explore the logs for this in split view from tempo trace view=

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: helm chart from kube prometheus stack (prometheus community) v34.1.1 '' & helm chart loki v2.10.1
- OS Grafana is installed on:
- User OS & Browser: Mozilla 98.0.1 Ubuntu 20.04

Observation on the picture: trace happened at 8h52 and log search is being shown at 12h52

![Screenshot from 2022-03-18 08-53-46](https://user-images.githubusercontent.com/17641873/159134353-7475f7dc-b9bb-419f-9c80-c666303ed58e.png)

**Comment by connorlindsey** [comment]
Could you share your logs to traces config from Tempo?

**Comment by Jojoooo1** [comment]
logs timestamp was not correct. closing the issue.
