### ISSUE TITLE
Grafana 8.4.3 after upgrade, query datasource issue

### ISSUE THREAD

**Issue by xgattuso** [grafana/grafana#46730]
**What happened**:
After migrating from 7.5.3 to 8.4.3 we have a strange behavior with the data source.
We are using a variable Data source, named datasource, of type Prometheus.
If you edit a panel that contains this variable you see that the value is the name of the data source instead of being the variable.

When a query of the panel is modified and saved the value of the data source is changed and stored permanently.
Meaning that after applying the change when the variable value change in the dashboard we are still seeing the wrong graph.

**What you expected to happen**:
The query datasource should match ${datasource} variable in the query tab since it's the behavior prior edition of the query.

**How to reproduce it (as minimally and precisely as possible)**:
Edit a panel, edit a query save it, change the value of ${datasource}. If you edit again the panel, you'll see that the datasource of the query took the value of ${datasource} when it was saved. 
If you change ${datasource} value, it doesn't change anymore. Example in the video attached.

**Anything else we need to know?**:
We upgraded Grafana from 7.5.3.

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: Prometheus core
- OS Grafana is installed on: Linux Ubuntu 18.04.2 LTS
- User OS & Browser: Linux Firefox
- Grafana plugins:

- Others:

![Grafanaissue](https://user-images.githubusercontent.com/79837141/158999159-9545c2b2-d934-48b9-bddf-a1cd017abbcc.gif)

**Comment by zuchka** [comment]
Thanks for creating this issue, @xgattuso 

It looks like you are using the `Graph (old)` panel. Is this behavior reproducible on the newer `Timeseries` replacement panel?

**Comment by xgattuso** [comment]
Hi @zuchka,

unfortunately as long as the data source in the query is not ${datasource} we have the same issue. Even with new `Timeseries` panel and as it implies a save it breaks the data datasource.

**Comment by xgattuso** [comment]
Hello,

after digging further, here are some findings:
* prior v8.x the datasource wasn't viewable next to the query name in the edit panel
* from v8.x to 8.4 (as a feature?) the datasource showed up next to the query name. 
  The video above (https://user-images.githubusercontent.com/79837141/158999159-9545c2b2-d934-48b9-bddf-a1cd017abbcc.gif) shows a workaround (although unpractical with lot of dashboards).
* from 8.5.x the workaround above doesn't work anymore.

In the json file we can see what is happening
```
  "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "5cLI5nMGz"
          },
          "expr": "prometheus_tsdb_storage_blocks_bytes",
          "refId": "A"
```

If we update the json it works until we edit the panel and touch the data source as the video below demonstrate.

```
  "targets": [
        {
          "datasource": {
            "type": "prometheus",
            "uid": "${datasource}"
          },
          "expr": "prometheus_tsdb_storage_blocks_bytes",
          "refId": "A"
```
![Grafanaissue2](https://user-images.githubusercontent.com/79837141/165919887-7e47f332-fbea-4699-b221-612b7559ff4e.gif)

**Comment by SebastianPereiro** [comment]
We have the same issue after upgrading Grafana version from 7.x.x to 8.5.2. Does anybody have a workaround or a fix?

**Comment by aauren** [comment]
I could be wrong, but I'm pretty sure this issue is the same as: https://github.com/grafana/grafana/issues/49456
