### ISSUE TITLE
[Bug] New "Browse grafana.net" link broken

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4673]
The new "No additional ... installed. Browse grafana.net" links to `grafana/net/plugins` and not `grafana.net/plugins`.

**Comment by nopzor1200** [comment]
ltns :)
Thanks for catching this. Should be fixed in master.

**Comment by grobie** [comment]
Fixed in c13ebce2f6c20cea8e69015bf184376bd80c48f3.
