### ISSUE TITLE
how to edit elasticsearch datasource and elasticsearch query?  have example ???

### ISSUE THREAD

**Issue by 1512100046** [grafana/grafana#4676]
Suppose I have some elasticsearch data, How to edit datasource and query?
![elasticsearch-data](https://cloud.githubusercontent.com/assets/10609344/14482573/c04ddea0-0170-11e6-85eb-8be0fabdc895.png)
![elasticsearch-data-2](https://cloud.githubusercontent.com/assets/10609344/14482575/c127496a-0170-11e6-9be6-49bd1a98f380.png)
![garfana-data-source](https://cloud.githubusercontent.com/assets/10609344/14482572/bf901bd6-0170-11e6-9412-08c9dfbe22a9.png)

**Comment by torkelo** [comment]
please use the mailing list for questions https://groups.io/g/grafana
