### ISSUE TITLE
[Bug] Bar graph scaling issues (bar graphs double in size then shrink in size)

### ISSUE THREAD

**Issue by johnnybobbybee** [grafana/grafana#4678]
Hi -- I'm using Grafana v2.6.0, Graphite 0.9.12-3 as data source on a Ubuntu 14.04LTS Linux box.

Please forgive the inarticulate description of this 'bug' but I can't seem to find any other issues like this from my Google searches nor from looking over this github issues page. I'll describe as best I can, and include a link to a video screen grab of the issue I'm seeing.

This seems to happen only on graphs with display style set to bars.

Happens randomly, but often. Sometimes a couple times in 1 minute, sometimes a few times within 5-10 minutes. But often enough to be noticeable.

The issue is, the bars in this graph will sometimes double in size (width) so the scale of the width of the graph stretches long, just for a quick second then comes back to proper (single) width size. I could almost ignore that issue. The more troubling issue is occasionally, instead of bars doubling, we'll see about 1/4 of the frontend and 1/4 of the backend of the graph (the bars) will just disappear and only show the middle 1/2 of the graph. As though the width of the bar graph was cut in half, only showing the middle half. Both ends will disappear. Again for only a quick second, then bar graph scales back to normal full-length size.

Please see this uploaded video for the screen grab to see what I'm talking about. The double-width issue happens a few times throughout this 13 second video. The 'disappearing' bars issue happens around the 10 second mark.

The video was edited from a 5-min grab just to show the issues in the shortened time frame.
https://www.youtube.com/watch?v=1n_bY8Lsgas

Anyone know what may be causing this?

cheers.
johnny

**Comment by torkelo** [comment]
could be that your close to a graphite rollup limit and your sometimes hitting a graphite rollup and sometimes not. The bar size is determined by the distance between first data points. 

You can also try to change the max data points to change how many bars are shown

**Comment by torkelo** [comment]
Also upgrade graphite, that version is very very old and probably does not even have max data points feature (a feature that is crucial for fast querying in grafana)

**Comment by johnnybobbybee** [comment]
Thanks for the reply, Torkel. I have it sorted with a combination of setting "cache timeout to 1" and Time Picker "Now delay" (removing the 1m). This was a pretty intense real-time graph with a refresh rate of 1s. 

Seems good now.

Thanks for the tips. And thank you (and the team) for Grafana. Truly and amazing piece of software.

cheers.
johnny

**Comment by torkelo** [comment]
@johnnybobbybee thanks for the comment! glad you solved the issue!
