### ISSUE TITLE
[Feature Request] Return the height of the singlestat panel to 100px

### ISSUE THREAD

**Issue by banzayats** [grafana/grafana#4679]
In grafana 2.x the minimum height of the singlestat panel was **100px**. Now in the 3.0.0 version its minimum height has become equal to **135px**. 
In some cases, for example if any dashboard has lots of triggers, some items do not fit the screen now. And I think it is not necessary to have lots of whitespace on the simple widget:

![before](https://cloud.githubusercontent.com/assets/477161/14484444/394f374e-0159-11e6-88c6-0c3978941031.png) - old Grafana
![after](https://cloud.githubusercontent.com/assets/477161/14484446/3d386f88-0159-11e6-8b99-f62a941b450b.png) - new Grafana

**Comment by bscholze** [comment]
:+1:
