### ISSUE TITLE
Label overlapping on PostgreSQL datasource configuration

### ISSUE THREAD

**Issue by tbille** [grafana/grafana#46800]
**What happened**:

PostgreSQL data source has labels that go out of their label "box"

![image](https://user-images.githubusercontent.com/2707508/159313528-1459beef-f9f2-4d4a-b94f-08933c319a01.png)
 

**What you expected to happen**:

The text should be part of the label "box"

**How to reproduce it (as minimally and precisely as possible)**:

- On a fresh install of Grafana.
- Go on data source (`Configurations -> Data sources` or `<host>/datasources/` )
- Add a new data source
- Select `PostgreSQL`
- Look at the `TLS/SSL Auth Details` section

**Anything else we need to know?**:

None

**Environment**:
- Grafana version: `v8.4.4 (fcfb01faeb)`
- Data source type & version: PostreSQL
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Firefox
- Grafana plugins: - 
- Others: Running with Docker image `grafana/grafana-oss`

**Comment by zuchka** [comment]
thanks for reporting this, @tbille 

I've submitted a PR for a fix
