### ISSUE TITLE
[State Timeline] Absence of data not represented anymore (part 3)

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#46805]
**What happened**:

This is a follow up of https://github.com/grafana/grafana/issues/45852 which should have been fixed by https://github.com/grafana/grafana/pull/45997 in 8.4.4 but some glitches remain (see https://github.com/grafana/grafana/issues/45852#issuecomment-1074190354). Ping @leeoniya.

In some cases, bars from the state timeline panel still remain open while should be be closed (time-series vanished, value should be null).

**What you expected to happen**:

See https://github.com/grafana/grafana/issues/45852

**How to reproduce it (as minimally and precisely as possible)**:

I don't have a proper reproducer yet but here is my initial observation / gut feeling. I think remaining issue is related to the frame having a single data point.

Here is a truncated & redacted response leading to bar not being closed.

```
{
	"frames": [
		{
			"schema": {
				"name": "<redacted>",
				"refId": "A",
				"meta": {
					"custom": {
						"resultType": "matrix"
					}
				},
				"fields": [
					{
						"name": "Time",
						"type": "time",
						"typeInfo": {
							"frame": "time.Time"
						},
						"config": {
							"interval": 120000
						}
					},
					{
						"name": "Value",
						"type": "number",
						"typeInfo": {
							"frame": "float64",
							"nullable": true
						},
						"labels": {
							"exported_app": "<redacted>",
							"fqdn": "<redacted>"
						},
						"config": {
							"displayNameFromDS": "<redacted>"
						}
					}
				]
			},
			"data": {
				"values": [
					[
						1647875040000
					],
					[
						0
					]
				]
			}
		}
	]
}
```

Real response has many similar frames all leading to similar behaviors. Same response has a frame with multiple timestamps and its bar behave like expected

```
{
	"data": {
		"values": [
			[
				1647869880000,
				1647870000000,
				1647870120000
			],
			[
				503,
				503,
				503
			]
		]
	}
}
```

**Environment**:
- Grafana version: 8.4.4
- User OS & Browser: Firefox 98

**Comment by hawran** [comment]
A quick examples of the issue:
![220322-091446 grafana statetimeline displminstep-10m](https://user-images.githubusercontent.com/25924718/159437842-5723a75f-3419-414b-8671-f10613e6cf41.png)
![220322-091556 grafana statetimeline displminstep-2m png](https://user-images.githubusercontent.com/25924718/159437850-d744f067-42f1-4723-b025-8f9352a0c06f.png)

The top panel: Status Timeline
The bottom panel: Time Series / Style: Bars / Stack Series: Normal

**Comment by hawran** [comment]
I'd say that *Time series* visualisation has similar issue as well:
![220322-132233 grafana 8 4 4 last-3h step-5m](https://user-images.githubusercontent.com/25924718/159485607-89dd933f-a30f-4263-9ef8-f09c58fec363.png)
![220322-132322 grafana 8 4 4 last-3h step-1m](https://user-images.githubusercontent.com/25924718/159485616-9ebf3520-8eca-4f1a-b68c-6ff6dc42520e.png)
![220322-132946 grafana 8 4 4 future step-10m](https://user-images.githubusercontent.com/25924718/159485619-43baefe2-31fb-4011-95aa-11b0a626bbdd.png)
![220322-133120 grafana 8 4 4 future step-30m](https://user-images.githubusercontent.com/25924718/159485622-2df9704b-ec16-4b79-a37f-e593a127d5f4.png)

**Comment by leeoniya** [comment]
will be fixed by https://github.com/grafana/grafana/pull/47240

**Comment by xealits** [comment]
but in 9.0.7 it does not work.

**Comment by leeoniya** [comment]
> but in 9.0.7 it does not work.

please open a new issue with the data, screenshot(s), and panel JSON.
