### ISSUE TITLE
Grafana 3 beta3 - single stat panel - background colors don't work

### ISSUE THREAD

**Issue by tomazbracic** [grafana/grafana#4680]
I have few single stats panels, where I can not change the color. In Grafana 2.6 I was able to invert colors and even better, change the color to something else, that you had multiple colors for those panels... like in Dashing (from Shopify). 

Now in Grafana 3 beta3, I only have Orange color. Can't use anything else.

**Comment by torkelo** [comment]
have you specified any threshold levels for the colors? Can you provide dashboard/panel json?

**Comment by tomazbracic** [comment]
No I did not specify treshold levels. Neither did I in Grafana 2.6 (I think
so). And that functionality was great. In that way I visually colored the
single panel boxes to visually separate them.

**Comment by torkelo** [comment]
well you can still do that, but you need to specify the some color thresholds, (or change the middle color)
