### ISSUE TITLE
[Feature Request] Possibility to highlight a sub-section of a graph

### ISSUE THREAD

**Issue by kmoppel** [grafana/grafana#4681]
Would be really nice to be able to provide some URL params in addition to "from/to" so that this specified sub-timerange would be somehow highlighted (extra with, other color, doesn't matter) throughout zoom-ins/outs.

Our use case is about detecting shady metrics (timeline analysis) and then providing a link to the user who could then zoom out for example and visually decide if the highlighted section indeed looks  unusual compared to normal patterns.

**Comment by drewboswell** [comment]
Highlighting might be painful when users have used thresholds, bar graphs, filled line graphs etc. Any chance this might be changed to annotation style bars at beginning and end of selected period, and then  maybe change the color of the x axis according to the range (or y axis why limit ourselves?).

Ctrl+select drag? Or some other identifiable action?

**Comment by torkelo** [comment]
Will close this for lack in interest, and think this might be better solved by enabling users to mark regions and create region annotations/comments from within Grafana.
