### ISSUE TITLE
Docs: Broken transformations docs

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#46818]
1) Cannot find any docs for the transformation operations (they are hidden in a different category, with a prefix that makes them next to impossible to find, and not even linked to on the transform data page) 

![Screenshot from 2022-03-22 07-53-25](https://user-images.githubusercontent.com/10999/159424936-701dc96b-cc56-4a1a-b4e4-235fa995db76.png)

2) The apply transformation function to data page has a section at the bottom that does not belong there, it's from the docs I wrote for the "Config from query" transformation.  https://grafana.com/docs/grafana/latest/panels/transform-data/apply-transformation-to-data/   

![Screenshot from 2022-03-22 07-54-42](https://user-images.githubusercontent.com/10999/159425405-727f3835-8441-4110-93cb-853475e211d2.png)

3) Do we need the about transform page when we have the "Transform data" root (menu category page). They look to serve the same purpose. 

4) Having Apply (should just say add not apply) transformation, debug & delete as separate small separate pages seems to only make navigating and finding info about transformations harder.  But this with my nondocs professional hat on. 

Think a simple structure like this would make things easier to find:

* Transform data
  * Using transformations (covers general info, adding, deleting, debugging)
  * Transformation functions (Reference)

**Comment by gguillotte-grafana** [comment]
Re:

> The apply transformation function to data page has a section at the bottom that does not belong there, it's from the docs I wrote for the "Config from query" transformation. https://grafana.com/docs/grafana/latest/panels/transform-data/apply-transformation-to-data/

The pre-refactor "Config from query" transformation doc as seen in commit 449c608 had the "Options" subsection in question, and also a field mapping table. The context for that table appears to now be under the "Rows to fields" transformation instead of "Config from query", and the table is gone. Is this intentional? CC @chri2547

**Comment by gguillotte-grafana** [comment]
Re:

> Action item: Move the 'Options' section currently located in the 'Apply transformation function to data' topic to the 'Config from query results' section of the transformation functions reference topic.

That's been merged in #46865.

**Comment by chri2547** [comment]
Perfect, thanks!

**Comment by gguillotte-grafana** [comment]
Breaking out the actions:

- [ ] Add a link to the transformation functions reference to the _index page
- [ ] Remove 'Reference' prefix from all reference topics
- [X] Move the 'Options' section currently located in the 'Apply transformation function to data' topic to the 'Config from query results' section of the transformation functions reference topic
- [ ] Change 'Apply a transformation' to 'Add a transformation'

**Comment by gguillotte-grafana** [comment]
Filed #46903 to tackle the other three actions.

As that PR shows, renaming all four of the "Reference:"-prefixed topics requires changes to about two dozen other docs files that already link to them with the `reference-`prefixed filename. While aliases could make some of these edits unnecessary, we'd still have to edit several links to them across the docs because their link text also uses the "Reference:"-prefixed titles.

To add a link to the transformation function reference on _index, #46903 moves that reference doc into the transform-data directory, which adds it to the automatically generated links in _index. This also organizes the reference content alongside the topics that most rely on it. If we don't want to move this reference doc there (or at all), I have a separate branch that manually adds a link.

**Comment by gguillotte-grafana** [comment]
@torkelo FYI, #46903 is still up for review. It has one approved review, and I do not have permission to merge it.

**Comment by torkelo** [comment]
@gguillotte-grafana sorry, was not added as reviewer so missed the PR

**Comment by torkelo** [comment]
> We have moved to a more granular approach to writing topics. While this does present some usability issues with navigating between topics at present, we're planning to implement a plan to compose longer form content from atomic content.

What's the reasoning here? should every icon / button have it's own page? that feels so wrong to me. I would not expect to read about removing a transform on a separate page/article from where I find how I add them, or short info on what they do. 

> Having discrete files for each topic enhances our ability to repurpose content in other guides. This is top of mind for us, and appreciate your feedback.

Yes, but every button and action does not live in isolation and deserve it's own topic. How do you define what a topic is (what deserves a full page)? We can still link to sections/headings within topics (pages). 

I would also weigh the maintainability cost of having every action in it's own page, not just discoverability. 

Looks like elastic docs have a very different philosophy:
https://www.elastic.co/guide/en/kibana/current/dashboard.html

I agree major workflows/feature areas & workflows should have their own pages. But single actions within those workflows/feature areas seem too granular, and will hurt discoverability and maintainability 

> We are now moving all meaningful information out of _index topics and into 'About' topics. The reason for this change is that users can technically bypass _index content by navigating the TOC with the chevron rather than clicking the section link.'

If the only reason for the "About" pages is that users can click the small 16px16px icon to expand the section without opening the section index, hm... seems like not a great reason to have to maintain two 90% identical pages. If we want to keep the About pages make them identical to the index pages (ask for a copy step or script do this).

**Comment by osg-grafana** [comment]
> @torkelo FYI, #46903 is still up for review. It has one approved review, and I do not have permission to merge it.

Merged.

**Comment by osg-grafana** [comment]
@gguillotte-grafana should this issue remain open for subsequent work? If so, please reopen.
