### ISSUE TITLE
datasource cloudwatch: some aws opensearch metrics with wrong name

### ISSUE THREAD

**Issue by CompuGlobalHyperMegaNet-VP** [grafana/grafana#46823]
**What happened**:
Cloudwatch datasource, namespace AWS/ES metrics OpenSearchDashboard* do not fetch any results, because they have the wrong name:
![grafik](https://user-images.githubusercontent.com/51958658/159463066-13a64146-737b-48c4-9b42-5a9500473e76.png)

If one manually creates a metric, ommiting the "(previously ...)" suffix, and does not use the default from the drop down, it works.
```
--OpenSearchDashboardsHealthyNodes (previously KibanaHealthyNodes)
++OpenSearchDashboardsHealthyNodes
```

**What you expected to happen**:
The correct metric names are displayed in the drop down,  no need to edit them manually.

**How to reproduce it (as minimally and precisely as possible)**:
Cloudwatch datasource, namespace AWS/ES, select any metric "OpenSearchDashboard.* (previously .*)". It will result in an empty data set. 

Manually create the metric without the suffix, and it works.
![grafik](https://user-images.githubusercontent.com/51958658/159464136-aeec9447-32fd-4204-ac09-cefed60b2fa2.png)

**Anything else we need to know?**:
AWS Elastic Search got renamed to Opensearch, so AWS changed the names of some kibana metrics as well. This [commit](https://github.com/grafana/grafana/commit/043680371f0342e805a95afdcdafabd92ae03606) added them. Probably following the [official documentation](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-cloudwatchmetrics.html), the suffix "(previously ...) was copied literally, too:
```
"OpenSearchDashboardsConcurrentConnections (previously KibanaConcurrentConnections)",
"OpenSearchDashboardsHealthyNode (previously KibanaHealthyNode)",
"OpenSearchDashboardsHealthyNodes (previously KibanaHealthyNodes)",
"OpenSearchDashboardsHeapTotal (previously KibanaHeapTotal)",
"OpenSearchDashboardsHeapUsed (previously KibanaHeapUsed)",
"OpenSearchDashboardsHeapUtilization (previously KibanaHeapUtilization)",
"OpenSearchDashboardsOS1MinuteLoad (previously KibanaOS1MinuteLoad)",
"OpenSearchDashboardsRequestTotal (previously KibanaRequestTotal)",
"OpenSearchDashboardsResponseTimesMaxInMillis (previously KibanaResponseTimesMaxInMillis)",
```
However, the actual metric names to not have that suffix (fetched via aws cli)
```
 OpenSearchDashboardsConcurrentConnections
 OpenSearchDashboardsHealthyNode
 OpenSearchDashboardsHealthyNodes
 OpenSearchDashboardsHeapTotal
 OpenSearchDashboardsHeapUsed
 OpenSearchDashboardsHeapUtilization
 OpenSearchDashboardsOS1MinuteLoad
 OpensearchDashboardsReportingFailedRequestSysErrCount
 OpensearchDashboardsReportingFailedRequestUserErrCount
 OpensearchDashboardsReportingRequestCount
 OpensearchDashboardsReportingSuccessCount
 OpenSearchDashboardsRequestTotal
 OpenSearchDashboardsResponseTimesMaxInMillis
```

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: Cloudwatch 5.0
- OS Grafana is installed on: official docker image
- User OS & Browser: Win10 / Firefox 98.0.1
- Grafana plugins: Cloudwatch

**Comment by zuchka** [comment]
Thanks for creating this issue, @CompuGlobalHyperMegaNet-VP 

can confirm this behavior on main. The `(previously.*)` gets encoded into the request:

![CleanShot 2022-03-22 at 11 59 38@2x](https://user-images.githubusercontent.com/37156449/159583707-fd86167d-f189-4321-9b35-39fa52052fbd.png)

**Comment by sarahzinger** [comment]
@CompuGlobalHyperMegaNet-VP thanks so much for reporting this issue! Just tried to reproduce and was able to, will move it to our sprint to work on as soon as we can! 

As a temporary work around until we fix the issue I believe you should be able to switch from "Buillder" mode to "Code" and can type in any search query you'd like so for example:
`REMOVE_EMPTY(SEARCH('{"AWS/ES","InstanceId"} MetricName="OpenSearchDashboardsHeapUtilization"', 'Minimum', 300))`
