### ISSUE TITLE
 [Feature Request] template variable in graphite events query

### ISSUE THREAD

**Issue by cosmos78** [grafana/grafana#4682]
I am using evens in graphite.

I am unable to use template variables when configuring annotations in grafana.

When using $tag in the field graphite events query the variable does not seem to be used ?

**Comment by torkelo** [comment]
it is used when I test it here, so you have a $tag variable and try to use it in a graphite event tags query, 

Can you check in Chrome dev tools what the query sent to graphite is for the events call?

**Comment by cosmos78** [comment]
I do not have chrome dev tools and do not have proper admin rights to install this. however I can explain a little better what I did

I created a custom variable called $tag with multiple values ( these values are graphite tags example: backend2)

when creating an annotation I left Graphite metrics query empty and entered $tag in the next field " Graphite events query"

when I now select the tag from the list box (custom variable) in grafana, the event line is not shown

**Comment by cosmos78** [comment]
problem solved
