### ISSUE TITLE
Docker Images: Grafana 7.5.11-7.5.15 are missing from `grafana/grafana-oss` DockerHub repo

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#46831]
**What happened**:

Grafana versions `7.5.11-7.5.15` are missing from `grafana/grafana-oss` DockerHub repo.
https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=7.5.1

This makes downloading of those Grafana versions unavailable to download, since this is the default DockerHub repo to download from the grafana.com website.

They exist in https://hub.docker.com/r/grafana/grafana/tags?page=1&name=7.5.1.

**What you expected to happen**:

Images should appear in `grafana/grafana-oss`

**Comment by tleopold** [comment]
No longer interested
