### ISSUE TITLE
Some questions on grafana related to upgrading to newer version and how to downgrade if required?

### ISSUE THREAD

**Issue by chigurupati** [grafana/grafana#4683]
Hello,

Currently I have grafana 2.6. and I want to install 3.0 beta. 

So my questions are:

1. Can I have 2.6 and 3.0 both on a same machine? if I install 3.0 now.
2. If I upgrade my version to 3.0 beta, then for any reason, is it possible for me to downgrade my version to 2.6?
3. Please let me know how do I find my current grafana version installed.
    - on web grafana ui
    - and on terminal.

I am running grafana on Ubuntu 14 machine.

Regards,
Amar.

**Comment by torkelo** [comment]
you see current version on footer of login page. 

You can downgrade but for to be sure we recommend you also backup the database, not guarantee that downgrade works with upgraded 3.0 database (think it will work though)

**Comment by Wai-Avantia** [comment]
> you see current version on footer of login page.
> 
> You can downgrade but for to be sure we recommend you also backup the database, not guarantee that downgrade works with upgraded 3.0 database (think it will work though)

How do we Downgrade grafana? Is there any documentation/tutorial about it?

**Comment by satishdotpatel** [comment]
I have same question how to take backup (what files? ) and how to downgrade version?
