### ISSUE TITLE
[Question] Error Template with ElasticSearch

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4684]
Hi,

I try to use template with ElasticSearch source. But i have a error in a red popup:
**Templating
Template variables could not be initialized: a.responses[0].aggregations is undefined**

What does it mean? 

My query is:
{"find": "terms", "field": "hostname"}

I confirm the hostname field exist.
If my query is  {"find": "fields", "type": "string"}, the query works.

I using Grafana 3.0 beta2 and i have same error with Grafana 2.6

Edit:
I noticed my terms contains dot (eg: myhost.mycorp.com) and if my terms doesn't contains dot the query works.

**Comment by torkelo** [comment]
ok, maybe an elasticsearch error? Can you check what the response is from ES ? (open chrome dev tools network tab)

**Comment by Azef1** [comment]
```
Error: a.responses[0].aggregations is undefined
h/this.getTerms/<@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:13:11462
h@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:36:28121
i/<@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:36:28293
vc/this.$get</n.prototype.$eval@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:37:3805
vc/this.$get</n.prototype.$digest@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:37:2309
vc/this.$get</n.prototype.$apply@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:37:4090
f@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:36:10936
q@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:36:12786
Ib/</v.onload@http://myhost.mycorp.com:3001/public/app/boot.f3fb1341.js:36:13329
```

**Comment by Azef1** [comment]
i found the error:
My query should be {"find": "terms", "field": "hostname.raw"}  (add '.raw' ) and all works now.
Thx you very much, i found the answer with error "Field data loading is forbidden on hostname" on google and [here](https://github.com/elastic/elasticsearch/issues/15267)

thx again
