### ISSUE TITLE
Panels created by Repeat Options->Repeat by variable are not saved in a local snapshot

### ISSUE THREAD

**Issue by IlyaDeskov** [grafana/grafana#46844]
**What happened**:
Panels created by Repeat Options->Repeat by variable are not saved in a local snapshot. Values of used variable are not saved too.
**What you expected to happen**:
Created snapshot contains all panels
**How to reproduce it (as minimally and precisely as possible)**:
1. acquire an influxDB datasource
2. Create a variable with several values
3. Create a panel and use a repeat option to repeat panel for each value in the variable
4. make a local snapshot
5. open created snapshot
**Anything else we need to know?**:
Issue is actual for "Graph (old)" and "Time series" panels
**Environment**:
- Grafana version: Grafana v8.2.2 (6232fe07c0)
- Data source type & version: InfluxDB 5.0.0
- OS Grafana is installed on: "Debian GNU/Linux 9 (stretch)
- User OS & Browser: any, i guess
- Grafana plugins: 
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @IlyaDeskov 

this is a snapshot of a dashboard I made on play.grafana.org. Three of the four panels were generated from the `Repeat by variable` option

https://play.grafana.org/dashboard/snapshot/HgjJw4YC0474A0YT735qrLlBIbjH5xdD?orgId=1

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by IlyaDeskov** [comment]
@zuchka looks like the newer version (8.4.4 vs 8.2.2) of grafana makes the difference. In new version snaps works well in this case.
Thank you!
