### ISSUE TITLE
Anonymous transparency 

### ISSUE THREAD

**Issue by TomerBrosh** [grafana/grafana#4685]
Hi,
I'm embedding my graphs with the anonymous configuration and I'd like to have another option for the theme, transparent. The default is the dark theme, not the current theme of my dashboard.
I tried the dark and the light theme and they just don't fit. 

Thanks!

**Comment by torkelo** [comment]
in grafana 3.0 you can set theme on organisation level as well (to cover anonymous user scenarios)
