### ISSUE TITLE
Grafana 7.5.15 panics when defer calls .Close() on .nil

### ISSUE THREAD

**Issue by L1ghtman2k** [grafana/grafana#46856]
Grafana is guaranteed to panic at: https://github.com/grafana/grafana/blob/7dd69b2442fa97981a25b7696b51432218f086b4/pkg/api/static/static.go#L159

Since the defer statement at: https://github.com/grafana/grafana/blob/7dd69b2442fa97981a25b7696b51432218f086b4/pkg/api/static/static.go#L137-L141 is executed when `f` is nil

**What happened**: Grafana panics when a https://github.com/grafana/grafana/blob/7dd69b2442fa97981a25b7696b51432218f086b4/pkg/api/static/static.go#L156 refers to a file path that grafana is unable to open

Not exactly sure what input caused the panic, but I assume something along the lines of: "path is too long", or "relative/inaccessible path"

**What you expected to happen**: Grafana stays up, despite the malformed request

**Anything else we need to know?**:
perhaps rewriting it as:

```
f_tmp, err := opt.FileSystem.Open(file)
if err != nil {
	return false // Discard error.
}
f = f_tmp
```

Trace:
```
{"error":"runtime error: invalid memory address or nil pointer dereference","lvl":"eror","msg":"Request error","stack":"/usr/local/go/src/runtime/panic.go:212 (0x4369ba)\n/usr/local/go/src/runtime/signal_unix.go:734 (0x4503d2)\n/drone/src/pkg/api/static/static.go:138 (0x195ddcd)\n/drone/src/pkg/api/static/static.go:159 (0x195da35)\n/drone/src/pkg/api/static/static.go:191 (0x195dfbe)\n/drone/src/pkg/macaron/logger.go:40 (0xf868b7)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0xf802f1)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0xf80064)\n/drone/src/pkg/macaron/context.go:125 (0xf8295c)\n/drone/src/pkg/macaron/context.go:115 (0x1580dc4)\n/drone/src/pkg/middleware/recovery.go:166 (0x1580db7)\n/drone/src/pkg/macaron/context.go:81 (0xf827d2)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:157 (0xf802f1)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:135 (0xf80064)\n/drone/src/pkg/macaron/context.go:125 (0xf8295c)\n/drone/src/pkg/macaron/context.go:115 (0x157ee71)\n/drone/src/pkg/middleware/logger.go:35 (0x157ee45)\n/usr/local/go/src/reflect/value.go:476 (0x4a04e6)\n/usr/local/go/src/reflect/value.go:337 (0x49f9b8)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:177 (0xf805f6)\n/root/go/pkg/mod/github.com/go-macaron/inject@v0.0.0-20160627170012-d8a0b8677191/inject.go:137 (0xf7ff71)\n/drone/src/pkg/macaron/context.go:125 (0xf8295c)\n/drone/src/pkg/macaron/router.go:267 (0xf9473c)\n/drone/src/pkg/macaron/router.go:310 (0xf8e9f4)\n/drone/src/pkg/macaron/macaron.go:220 (0xf87c2c)\n/usr/local/go/src/net/http/server.go:2887 (0x70eb22)\n/usr/local/go/src/net/http/server.go:1952 (0x70a04c)\n/usr/local/go/src/runtime/asm_amd64.s:1371 (0x472f20)\n","t":"2022-03-21T13:52:54.695497375Z"}
```

This seems to be fixed on master branch, but I am not quite sure if there are any plans to update 7.5* versions to fix this

**Environment**:
- Grafana version: 7.5.15
- OS Grafana is installed on: EKS
- User OS & Browser: Edge

**Comment by zuchka** [comment]
> This seems to be fixed on master branch, but I am not quite sure if there are any plans to update 7.5* versions to fix this

thanks for reporting this @L1ghtman2k

**Comment by tolzhabayev** [comment]
closing as we are currently not planning another patch version for Grafana 7
