### ISSUE TITLE
ManageDashboards: "All items" checked gets into a inconsistent state unchecking a child

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#46874]
**What happened**:

 1. Go to a manage folder page with multiple child dashboards
 2. Check the "All items" checkbox at the top.
 3. Uncheck a single child dashboard.

The "All items" checkbox will still be checked, despite all items not being checked.

![1287_2022-03-23-11-21_chrome](https://user-images.githubusercontent.com/46142/159689908-7d0d59e3-819d-4681-acfe-8b421bf7650d.png)

**What you expected to happen**:

When unselecting a child item, it should uncheck the "all items" checkbox. OR, it should switch it to an [indeterminate checkbox](https://css-tricks.com/indeterminate-checkboxes/), but that might require more work (to switch from `checked: boolean` to `checked: Checked | Unchecked | Indeterminate`)

**Environment**:
- Grafana version: main

**Comment by ashharrison90** [comment]
looks like this has been fixed by https://github.com/grafana/grafana/pull/49363
