### ISSUE TITLE
grafana's log pannel displays 'Data is missing a string field' when no data found in loki query

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#46870]
**Steps to reproduce**:
create a logs panel and query loki for non-existing data
**Actual Result**:
<img width="1610" alt="Screen Shot 2022-03-23 at 10 09 16" src="https://user-images.githubusercontent.com/4352719/159658937-030454d7-7a9c-4583-9a87-6ac525aa3735.png">

**Expected Result**
empty panel or more descriptive message

**Environment**:
- Grafana version: v8.4.2
- Data source type & version: Loki 2.3.0
- User OS & Browser: 
- Others:

**Comment by gabor** [comment]
hi @vbichov , i cannot reproduce this unfortunately. i get a "no data" message in the panel when there is no data.
looking at the screenshot you provided, i see you have a Transform added. could you try the following:

1. remove the transform. is the problem still happening? if it got fixed, please tell us what transform you used.
2. reduce the query to simply querying a non-existing label in the stream-selector, something like `{label="doest_not_exist"}`. is the problem still happening?

**Comment by vbichov** [comment]
sorry - my bad - removed the transform and it seems to be working
