### ISSUE TITLE
grafana 3.0 api: /api/datasources/plugins 

### ISSUE THREAD

**Issue by adejoux** [grafana/grafana#4688]
Hello,

I am running grafana 3.0.0-beta3. When sending GET /api/datasources/plugins, I receive:
`````
{"message":"Data source not found"}
```````

Accordingly to the documentation here it should work:
http://docs.grafana.org/http_api/data_source/#available-data-source-types

Working well with version 2.6.

Thanks

**Comment by torkelo** [comment]
thanks for informing me, that api resource is no longer there. 

Use this:
GET `/api/plugins?type=datasource`

**Comment by torkelo** [comment]
also updated docs, removed the old api example
https://github.com/grafana/grafana/commit/7302ddaba5006d1be0d35ed7dc72a1847c97f1b2
