### ISSUE TITLE
[Feature Request] precision_threshold for accurate unique counts in ElasticSearch

### ISSUE THREAD

**Issue by lucasrodcosta** [grafana/grafana#4689]
Related to #4231 and #3536.

The unique counts in ElasticSearch are approximate, because exact counts requires large memory usage.
Details in https://www.elastic.co/guide/en/elasticsearch/reference/current/search-aggregations-metrics-cardinality-aggregation.html#_counts_are_approximate.

But ElasticSearch offers the option `precision_threshold` to trade memory for accuracy.
In Kibana, to set a custom `precision_threshold` you can use the advanced section and put a custom JSON Input to the aggregation:

![](http://i.stack.imgur.com/Q2Joo.png)

However, Grafana doesn't support this option yet...
It would be really nice to have this option in Grafana.

**Comment by rafaelzacarias** [comment]
+1. When field cardinality gets too high, the `precision_threshold` must be increased, or the graph will lose some accuracy.
In this following graph, I have the same query in two lines, but using different precisions. 

![](http://i.imgur.com/LfKjwW8.png)
PS: (I had to hardcode an aggregation with `precision_threshold:1000` to generate the yellow line)

**Comment by robsonsnjr** [comment]
+1
