### ISSUE TITLE
Date picker is partially hidden in Explore split pane view

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#46900]
**What happened**:

In Grafana Explore, with the split-pane view, when I click on the calendar button to select an absolute time range, the popup date picker is hidden behind the split-pane separator. When I try the same on the left pane, the date picker is partially hidden to the left of the browser viewport.

Date picker on the right pane:
![Screenshot 2022-03-23 13-50-27 split pane bug](https://user-images.githubusercontent.com/3270755/159764427-2be267ea-d6e7-45ec-8342-35056388e67e.png)

Date picker on the left pane:
![Screenshot 2022-03-23 13-54-04 split pane bug](https://user-images.githubusercontent.com/3270755/159764600-ff005bf0-8595-4612-b64d-e122828f57b2.png)

**What you expected to happen**:

The date picker should be positioned in a way that it is entirely visible on the screen.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to Grafana Explore.
2. Click the Split button.
3. Select an absolute time range on either pane using the date picker.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.4
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Ubuntu 20.04, Firefox 98.0.1
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
thanks, @adeverteuil 

reproducible on play.grafana.org

**Comment by glintik** [comment]
Hi,

PR suggested, please take a look.
