### ISSUE TITLE
Alerting: New custom policies are added in the bottom of the list, which is clunky if you have many items in the list

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#46919]
https://user-images.githubusercontent.com/53754871/159900014-10e0c3ab-4258-4c4e-9651-08f95797bb80.mov

After looking at this problem, I recommend moving the "Add new" interaction to a modal and only adding it to the bottom of the list once the user actually finishes creating the custom policy.

**Comment by DiegoFlop** [comment]
You can use nested notification policies for organize  by logic things your alerts,
The problem I have seen, its when save the notification policy, add new version on the database and reset the nested policies and you need to move again your father policy for add new notification policy.

**Comment by gillesdemey** [comment]
closing this one in favor of https://github.com/grafana/grafana/issues/46919
