### ISSUE TITLE
Remove Plugin list Panel

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#46910]
**Why?**
The Plugin list Panel core plugin is being deprecated in favour of using the internal plugin catalogue.

**Acceptance criteria**
- Plugin list Panel  is marked as deleted in grafana catalogue
- Plugin list Panel is not bundled in and used in newer versions of Grafana
- Process of removing core plugins is documented

**Comment by torkelo** [comment]
I don't think we need to deprecate this one, just remove it

**Comment by torkelo** [comment]
It used to be primary be used on the default home dashboard, but it was removed from the default home dashboard in v7

**Comment by tolzhabayev** [comment]
There are some customers that are currently using it, so I would like to give them a chance to adjust their dashboards first before we remove it.

**Comment by tolzhabayev** [comment]
@torkelo you are right, I will remove it completely and target the v9 for it.

**Comment by tolzhabayev** [comment]
For documentation only - this is how it will look like for the customers:

![SCR-20220325-oka](https://user-images.githubusercontent.com/580672/160163818-26654104-9fb4-492f-b166-db69bd745bc0.png)
