### ISSUE TITLE
Alert List shows Grafana alerts (unified alerting) with "Normal" status as INACTIVE

### ISSUE THREAD

**Issue by Drakonhawk** [grafana/grafana#46932]
After migration from 8.2.4 with legacy alerting to 8.4.4 with Grafana Alerting, alerts in "Normal" status are not displayed any longer with "Normal" filter enable. The alerts are now listed as "Inactive". I expected the only silenced or paused alerts are shown under inactive filter. Pending and Firing status are working correctly.

Alert rule displayed as "Normal" status in 8.4.4 in alert list panel correctly, with Grafana Alerting:
![Grafana_Alerts](https://user-images.githubusercontent.com/8604822/159945630-191cfdcd-766f-4536-ab28-e2e5346a6bb0.png)

Alert rule displayed as "Inactive" in panel in 8.4.4, **tile in a dashboard**, with Grafana Alerting:
![Grafana_AlertList](https://user-images.githubusercontent.com/8604822/159945596-e999f515-a210-4842-926a-3f9f4cecbb72.png)

Alert List in 8.2.4 or 8.4.4 with legacy alerting:
![Grafana_AlertList_8 2](https://user-images.githubusercontent.com/8604822/159945663-fd2b79e4-894e-48de-9067-23ac48b00543.png)

2nd and 3rd screenshots are from the same panel. 

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: Promtheus
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Chrome

**Comment by zuchka** [comment]
Thanks for creating this issue, @DanielWebelsiep 

- Please list ALL configuration options related to alerting. You can find these in the `Alerting` and `Unified Alerting` sections of Grafana's config file. If you are now using or have previously used the beta version of `ngalert` (released with Grafana 8), please note that too.
  - you can use [this table](https://github.com/grafana/grafana/pull/42200#issue-1062269188) to better understand how configuration options can interact with each other
- was the alert in question migrated from the legacy platform into Unified Alerting, or did you first create it inside the new platform?

**Comment by DanielWebelsiep** [comment]
@zuchka We are using a Docker compose environment. In 8.2.4 we had 3 alerts and after upgrading to 8.4.4 we did not change any alert settings for the container (all default in 8.2.4 and 8.4.4). For testing we now added the GF_UNIFIED_ALERTING_ENABLED: "true" environment variable to our docker configuration. All other alert related settings are default. 

The problem is reproducable with migrated and new alert. The old alert was removed.

**Comment by dajuno** [comment]
I have the same issue using Grafana 8.5.0-beta1. The alerts were created within this platform. Alerting/Unified Alerting settings have not been modified in Grafana's config file.

The alert status is "Normal", but in the alert list I have to select "inactive" and "normal" in the alert filter for them to show. Alert List shows "Inactive" as reported by @DanielWebelsiep Daniel

**Comment by saketbairoliya2** [comment]
Anyone else facing this similar issue with Grafana 9.5.1 as well?
