### ISSUE TITLE
Grafana alerts rules errors when using $__rate_interval in query

### ISSUE THREAD

**Issue by rohitsngh27** [grafana/grafana#46930]
**What happened**: Got the error `[tsdb.HandleRequest() error bad_data: 1:61: parse error: missing unit character in duration]()` while creating rules in grafana alerts.

**What you expected to happen**: No error should have been there and rule should have tested successfully. 

**How to reproduce it (as minimally and precisely as possible)**: Just create a query in grafana with prometheus data source and use `$__rate_interval]` in query. After this try to create any alert rules and test it.

**Anything else we need to know?**: The error comes when query contains `$__rate_interval]`. Rules tested successfully if we replace this with any hardcode value like `1m`.

**Environment**:
- Grafana version: Grafana v7.2.0
- Data source type & version: Prometheus 
- OS Grafana is installed on: Linux
- User OS & Browser: Mac, Chrome
<img width="750" alt="image" src="https://user-images.githubusercontent.com/13554835/159942788-a37c8e52-74d3-476d-b0df-c6276f946af8.png">

**Comment by zuchka** [comment]
Have you tried reproducing this error using the new Unified Alerting platform? 7.2.0 is starting to age a bit...

https://grafana.com/docs/grafana/latest/alerting/unified-alerting/
https://grafana.com/docs/grafana/latest/alerting/unified-alerting/difference-old-new/

**Comment by rohitsngh27** [comment]
> Have you tried reproducing this error using the new Unified Alerting platform? 7.2.0 is starting to age a bit...
> 
> https://grafana.com/docs/grafana/latest/alerting/unified-alerting/ https://grafana.com/docs/grafana/latest/alerting/unified-alerting/difference-old-new/

No. I haven't upgraded the version of grafana yet but as far as I know this should be working with 7.2.0 as well.

**Comment by zuchka** [comment]
sounds very similar to this:

https://github.com/grafana/grafana/issues/43002

**Comment by B1773rm4n** [comment]
Confirm. Same issue here.
When I change  "$__rate_interval" to "5m" it solves the issue. So confirm what OP says.
Environment:
    Grafana version: Grafana v8.4.5
    Data source type & version: Prometheus
    OS Grafana is installed on: Alpine Linux 3.15.3 (Docker container)
    User OS & Browser: Arch, Firefox

**Comment by zuchka** [comment]
Thanks all, I think we should close this issue as a duplicate and link it to the older one, #43002. 

If you disagree let us know. thx! 👍
