### ISSUE TITLE
Grafana not passing credentials to datasource

### ISSUE THREAD

**Issue by philipfoulkes** [grafana/grafana#46947]
We're running Grafana 8.2.4, but I'm trying to upgrade to Grafana 8.4.4. Grafana and Prometheus are running as shown below. Grafana and Prometheus sit behind NGINX. NGINX does TLS termination and basic authentication. We authenticate individual users in NGINX for Grafana and Prometheus.

```
NGINX => Grafana => NGINX => Prometheus
```

For the Prometheus datasource, we set With Credentials, as shown below.

![image](https://user-images.githubusercontent.com/44870662/160074158-e297a8d9-a3c5-4c1d-acd3-3972a2a6c6f9.png)

This works well for us in Grafana 8.2.4 as Grafana passes the logged in user's credentials to NGINX/Prometheus.

We tried to upgrade to Grafana 8.4.4, but Grafana does not always pass through the credentials to the datasource, and as a result, the graphs do not load.

We have various variables, which are populated, but the graphs do not load, and indicate HTTP 401.

![Screenshot from 2022-03-25 09-14-44](https://user-images.githubusercontent.com/44870662/160074915-e55113fe-7679-4191-80bb-91c947e5f574.png)

Looking at the NGINX logs, we observed that the username is not always passed through to the datasource. Observing the logs when using Grafana 8.2.4 shows that the credentials are always passed through.

```
10.154.12.22 - username [25/Mar/2022:10:12:14 +0300] "prometheus.customer.corp" "POST /api/v1/series HTTP/1.1" 200 34954 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - username [25/Mar/2022:10:12:14 +0300] "prometheus.customer.corp" "POST /api/v1/series HTTP/1.1" 200 34954 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - username [25/Mar/2022:10:12:15 +0300] "prometheus.customer.corp" "POST /api/v1/series HTTP/1.1" 200 33717 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - username [25/Mar/2022:10:12:15 +0300] "prometheus.customer.corp" "POST /api/v1/series HTTP/1.1" 200 33725 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - username [25/Mar/2022:10:12:15 +0300] "prometheus.customer.corp" "POST /api/v1/series HTTP/1.1" 200 981 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - - [25/Mar/2022:10:12:16 +0300] "prometheus.customer.corp" "POST /api/v1/query HTTP/1.1" 401 172 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - - [25/Mar/2022:10:12:16 +0300] "prometheus.customer.corp" "POST /api/v1/query_range HTTP/1.1" 401 172 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - - [25/Mar/2022:10:12:16 +0300] "prometheus.customer.corp" "POST /api/v1/query HTTP/1.1" 401 172 "prometheus.customer.corp" "Grafana/8.4.4"
10.154.12.22 - - [25/Mar/2022:10:12:16 +0300] "prometheus.customer.corp" "POST /api/v1/query_range HTTP/1.1" 401 172 "prometheus.customer.corp" "Grafana/8.4.4"
```

**Comment by zuchka** [comment]
Thanks for creating this issue, @philipfoulkes 

can you please include more detailed steps for reproducing this error?

also, these might be relevant?

Change to how we proxy headers:
https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787

and this in the changelog:
**Prometheus:** Forward oauth tokens after prometheus datasource migration. [#43686](https://github.com/grafana/grafana/pull/43686), [@MasslessParticle](https://github.com/MasslessParticle)

**Comment by greatbn** [comment]
we have same issue. We would like to forward credentials header from browser to datasource. We can did that on older version (7.x) .

**Comment by pmint93** [comment]
Seem related https://github.com/grafana/grafana/issues/44250
