### ISSUE TITLE
The PromQueryEditor PromLink is set to "about:blank" on page load

### ISSUE THREAD

**Issue by koppchen** [grafana/grafana#46944]
**What happened**:

When editing a panel that uses a Prometheus data source, the "PromLink" is set to "about:blank" and opens a blank page when selected.

![grafana-promlink-issue](https://user-images.githubusercontent.com/8094490/160034940-e0a138a6-15cb-412f-b0a0-fc776fac4129.gif)

If an edit is made in the PromQueryEditor, the PromLInk is updated correctly.  Reloading the editor page also updates the link to the correct value.

![grafana-promlink-issue-good](https://user-images.githubusercontent.com/8094490/160035610-21d162c4-d74b-4f9b-96e3-b564307972de.gif)

**What you expected to happen**:

The PromLink should link to the correct location on the first load.

**How to reproduce it (as minimally and precisely as possible)**:

1. Open a dashboard (example: https://play.grafana.org/d/000000029/prometheus-demo-dashboard )
2. "Edit" a panel that uses the Prometheus data source. (example: "CPU usage" on the demo dashboard linked to above)
3. Select (or mouse over) the PromLink. (The "Prometheus" link between "Instant" & "Exemplars", which has the tool tip "Link to Graph in Prometheus")
4. When you mouse over, you should see that this links to "about:blank". Selecting the link opens a blank page in a new tab.

**Anything else we need to know?**:
After a quick test earlier, this issue seems to have started in 8.0.0, while 7.5.15 worked fine.

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: Prometheus 5.0.0
- OS Grafana is installed on: Debian bookworm
- User OS & Browser: Ubuntu impish, Firefox 98.0.1 & Chrome 99.0.4844.51
- Grafana plugins: No extra plugins have been installed
- Others:

**Comment by schustersv** [comment]
On Grafana 8.5.1, the Prometheus query link seems to be gone completely?

**Comment by itsmylife** [comment]
The Prometheus link feature had been broken for a while, without complaints, and the feature does not work in many setups where the Prometheus UI is not available. Taking those two things into count, we opted to remove the feature. If you wish we add it back; please create a GitHub discussion feature request.

**Comment by juliantaylor** [comment]
The about:blank link could be fixed by clicking the refresh graph link in the editor. Then the prometheus link worked as expected.

I really miss this button and have opened a feature request to add it back:
https://github.com/grafana/grafana/discussions/49382
