### ISSUE TITLE
[Feature Request] Descriptive title

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4695]
The HTML title format of dashboards is currently "Grafana - $title". When having many tabs open, it'd actually be helpful to have the title first like "$title - Grafana" or "$title proudly presented by Grafana" ;)

**Comment by utkarshcmu** [comment]
Or may be just "$title" with Grafana logo. Grafana logo is sufficient to represent a Grafana tab.

**Comment by torkelo** [comment]
will merge this issue with https://github.com/grafana/grafana/issues/3211
