### ISSUE TITLE
Alerting: handing large amount of alerts and alert instances

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#46955]
**What happened**:

When a user has many alerts or alert instances (many thousands) the UI becomes slow and unresponsive; we should investigate client-side pagination (the current API does not support pagination) or use a virtualized list so we can render all rows.

**What you expected to happen**:

The UI should be responsive regardless of how many alerts / instances you have.

**Comment by wiardvanrij** [comment]
Maybe related: https://github.com/grafana/grafana/issues/46976 :)

**Comment by 1tft** [comment]
Same issue applies to silences page, which has no pagination and is loading very slowly (with hundreds of silences).
