### ISSUE TITLE
Varaibles not being resolved in alert annotations and labels

### ISSUE THREAD

**Issue by julienmmm** [grafana/grafana#46956]
Hello,

I have created a grafana managed alert which is using a query with a Prometheus data source and a Math expression. I have also added a label to uniquely identify each alert instance, that label value will be retrieved from the Prometheus metrics by using the template variables as explained in https://grafana.com/docs/grafana/next/alerting/unified-alerting/alerting-rules/alert-annotation-label/.
The alerts works correctly as it is firing up as expected, however the status of the alerts is in error with the message : "invalid format of evaluation results for the alert definition : frame cannot uniquely be identified by its labels: has duplicate results with labels {}".
By looking at the alert status, I see that this label was evaluated to `<no value>` for each alert instance,which is casing the error.

Below are some details of my alert:

- grafana version: community edition 8.4.4 on-prem
- unified alerting: enabled
- classic alerting disabled
- Alert query using prometheus datasource:  ibm_mq_statq_queue_depth{queue = "SYSTEM.MQTT.TRANSMIT.QUEUE"}  (that metrics contains the qmname label)
- Alert expression of type Math: $A > 0
- custom label qm set to {{ $values.A.Labels.qmname }}

When firing up, the alert  status show that the label qm is set to <no value>.

I have tried a lot of combinations as described in the official documentation and I always have the same result.

**Comment by DiegoFlop** [comment]
You need use reduce function between query and condition expression and use the reduce expression as value of condition.
https://grafana.com/docs/grafana/next/alerting/unified-alerting/alerting-rules/create-grafana-managed-rule/

**Comment by julienmmm** [comment]
Hello Diego,

Thanks for responding. Indeed it works now when I put a Reduce expression between my prometheus query and a Math expression. However, I do not understand why a Reduce expression is required as nothing in the documentation says that.

**Comment by julienmmm** [comment]
@zuchka : Hello zuka. I am little bit surprised that this has been flagged as type/question and closed. I did not find any mention int he documentation that a multi dimension alert must contains a Reduce expression (if it contains only a math expression then the alert raises an error when it fires up). Or may be should I open a new issue describing more precisely the error when using only Math expression in a multi dimensional alert?
