### ISSUE TITLE
[Feature Request] Grafana instrumentation

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4696]
> As an operator of Grafana,
> I want to have metrics about the Grafana server,
> so that I can analyze issues and create automatic alerts.

And to no surprise, I'm obviously looking for [Prometheus](https://prometheus.io/) metrics. We have a golang client already which [has been optimized](https://github.com/gophercon/2015-talks/tree/master/Bj%C3%B6rn%20Rabenstein%20-%20Prometheus) to remove the overhead of instrumentation. If it helps, we're planning to provide a Graphite bridge to the client library so that the collected metrics can be optionally pushed to graphite in addition to / instead of being scraped by Prometheus.

With literally 3 lines of code will the [go client](https://godoc.org/github.com/prometheus/client_golang/prometheus) already provide basic HTTP request and process (CPU, memory usage, fd usage, etc.) metrics.

Would you accept a contribution here @torkelo ?

**Comment by torkelo** [comment]
you would have to hook up with the current metrics lib, add new metric output etc
https://github.com/grafana/grafana/blob/master/pkg/metrics/metrics.go

**Comment by torkelo** [comment]
Having better Grafana instrumentation is something that I have wanted to do for very long, but never found the time. Like request timers/counters, timers for data source proxy calls, maybe some in memory list of top 10 most expensive queries and dashboards etc

**Comment by grobie** [comment]
Thanks for the pointer, I wasn't aware of that. It seems these metrics are only meant for analytical use by raintank? The target seems to be hard-coded.

If I were maintaining the current interface to stats.grafana.org, would you accept a replacement of the current client with the prometheus client? That would provide float counters for timers and label support.

**Comment by torkelo** [comment]
That is just for a small part of it currently, it was ment to be expanded to also handle high resolution metrics and timmers to different backends , just never got to that part :)

**Comment by utkarshcmu** [comment]
+1
