### ISSUE TITLE
npm start stuck at 94% sealing after seal

### ISSUE THREAD

**Issue by chandradot99** [grafana/grafana#46977]
**What happened**:
yarn start got stuck at 94%

<img width="474" alt="Screenshot 2022-03-26 at 1 03 53 PM" src="https://user-images.githubusercontent.com/13932478/160229679-7b55dc02-44ae-46d6-ad85-2ae72afb6218.png">
 

**What you expected to happen**:
yarn start should complete to 100%

**How to reproduce it (as minimally and precisely as possible)**:
1. Clone Grafana from github
2. yarn install --immutable
3. yarn start

**Anything else we need to know?**:

**Environment**:
macOS big sur(node v16.13.2)

- Grafana version: main
- Data source type & version: none
- OS Grafana is installed on: macOS big sur
- User OS & Browser:
- Grafana plugins:
- Others:

Also added `custom.ini`  as shown below

```
app_mode = development

```

Not sure if this is grafana issue or some different issue.

**Comment by torkelo** [comment]
Update to node 16.14.2 (LTS) or latest 17 think also fixes this
