### ISSUE TITLE
Unable to setup dev env or docker dev env

### ISSUE THREAD

**Issue by wiardvanrij** [grafana/grafana#46974]
**What happened**:

```
yarn start              

SASS variable files generated
Compiling message catalogs…
Done!
94% sealing after seal
```
and it is stuck on 94%

and it's stuck there as well. 

**What you expected to happen**:

To be able to run yarn start

**How to reproduce it (as minimally and precisely as possible)**:

checkout main in a clean setup and execute the command shown above

**Anything else we need to know?**:
Also tried it on an other system and I've followed the dev guidelines to setup my env. 

**Environment**:
commit d5f40b63bbafe0126086d42bde2caae59bed452b (HEAD -> main, origin/main, origin/HEAD)

edit: Title is wrong, I thought it did not work in Docker, but that was an other issue

**Comment by zuchka** [comment]
have you tried using node `16.14.0` or `17.6.0`?

https://github.com/grafana/grafana/pull/45714
