### ISSUE TITLE
[Feature Request] New InfluxDB 0.12.0 functions

### ISSUE THREAD

**Issue by pavleec** [grafana/grafana#4698]
Hi,

New version of InfluxDB (0.12) has been released recently and it finally supports a long waited MOVING_AVERAGE() and DIFFERENCE() functions. Are you planning to support them in the query builder?

**Comment by torkelo** [comment]
yes, this should added! :)

**Comment by TheOneValen** [comment]
Using the query text input (Grafana 2.6) the moving_average from influxdb already works. The graph is truncated at the left though. Grafana should automatically query more (older) data depending on the moving average window chosen.

**Comment by torkelo** [comment]
@TheOneValen that should be handled in InfluxDB

**Comment by notes-jj** [comment]
:+1: Please add Influx 0.12 Features: 
 - MOVING_AVERAGE() 
 - DIFFERENCE()
 - SPREAD() 

in Query Builder.
