### ISSUE TITLE
[Bug] grafana 2.6.0 tooptip does not disappear in Firefox (from 35.0 to latest)

### ISSUE THREAD

**Issue by speed-of-light** [grafana/grafana#4699]
OS: osx/ubuntu
Browser: Firefox (ver 35.0 to 44.0)
Datasource: kairos db

Environments: 
We have 6 rows
each row contains 2 graphs
each graph contains 2 lines
each line are data from last 5 mins and refresh by 10s, which is typically 10~20 dots per line.
each dot is a usual system network information. (Ranges from 0 to several mil)

Trigger:
Hover to the left green tab from one row, select `Add panel` -> `Add graph` 
And the tooltip just stocked on the top of the edit area.

![image](https://cloud.githubusercontent.com/assets/2149541/14522547/9eca164e-0261-11e6-81a3-d1c033a01591.png)

related issue: #450 
Thanks.

**Comment by torkelo** [comment]
tested with firefox 44 with Grafana 3.0 and 2.6, could not replicate, is it happening when you do something special?
