### ISSUE TITLE
[Bug] Grafana 3.0.0 + OpenTSDB 2.2 - invalid tags serialization

### ISSUE THREAD

**Issue by ovx** [grafana/grafana#4700]
Grafana 3.0.0-beta4
OpenTSDB 2.2.0

When leaving 'tags' empty, Grafana builds a query with `"tags":[]`. This annotation is invalid and causes "Unable to parse the given JSON" response from OpenTSDB. The property `tags` has to be an object serialized into `"tags":{}` if empty.

**Comment by utkarshcmu** [comment]
So, in Grafana 3.0.0-beta4 , both tags and filters are supported but only one of them can be used to query Opentsdb. Are you trying to fetch data from Opentsdb by using tags or filters? Also, can you please post your Grafana query to Opentsdb for further investigation of the issue? It will be helpful to debug the issue. Thanks !!!

**Comment by ovx** [comment]
Neither one, both filters and tags are empty. And this is what causes the issue, Grafana appends empty `tags:[]` to the query.

And there seems to be another issue with the filters - they aren't included in the query.

Query (copied from Grafana):

`{"start":1460627244416,"queries":[{"metric":"cpu","aggregator":"avg","downsample":"2s-avg","tags":[]}],"msResolution":false,"globalAnnotations":true}`

Response:
`{"error":{"code":400,"message":"Unable to parse the given JSON","details":"com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token\n at [Source: {\"start\":1460627244416,\"queries\":[{\"metric\":\"cpu\",\"aggregator\":\"avg\",\"downsample\":\"2s-avg\",\"tags\":[]}],\"msResolution\":false,\"globalAnnotations\":true}; line: 1, column: 91] (through reference chain: net.opentsdb.core.TSQuery[\"queries\"]->java.util.ArrayList[0]->net.opentsdb.core.TSSubQuery[\"tags\"])","trace":"net.opentsdb.tsd.BadRequestException: Unable to parse the given JSON\n\tat net.opentsdb.tsd.HttpJsonSerializer.parseQueryV1(HttpJsonSerializer.java:212) ~[tsdb-2.2.0.jar:07d0464]\n\tat net.opentsdb.tsd.QueryRpc.handleQuery(QueryRpc.java:119) ~[tsdb-2.2.0.jar:07d0464]\n\tat net.opentsdb.tsd.QueryRpc.execute(QueryRpc.java:103) ~[tsdb-2.2.0.jar:07d0464]\n\tat net.opentsdb.tsd.RpcHandler.handleHttpQuery(RpcHandler.java:283) [tsdb-2.2.0.jar:07d0464]\n\tat net.opentsdb.tsd.RpcHandler.messageReceived(RpcHandler.java:134) [tsdb-2.2.0.jar:07d0464]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateAwareChannelUpstreamHandler.handleUpstream(IdleStateAwareChannelUpstreamHandler.java:36) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.timeout.IdleStateHandler.messageReceived(IdleStateHandler.java:294) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpContentEncoder.messageReceived(HttpContentEncoder.java:82) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.messageReceived(SimpleChannelHandler.java:142) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88) [netty-3.9.4.Final.jar:na]\n\tat net.opentsdb.tsd.ConnectionManager.handleUpstream(ConnectionManager.java:87) [tsdb-2.2.0.jar:07d0464]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:318) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108) [netty-3.9.4.Final.jar:na]\n\tat org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42) [netty-3.9.4.Final.jar:na]\n\tat java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145) [na:1.7.0_91]\n\tat java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615) [na:1.7.0_91]\n\tat java.lang.Thread.run(Thread.java:745) [na:1.7.0_91]\nCaused by: java.lang.IllegalArgumentException: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token\n at [Source: {\"start\":1460627244416,\"queries\":[{\"metric\":\"cpu\",\"aggregator\":\"avg\",\"downsample\":\"2s-avg\",\"tags\":[]}],\"msResolution\":false,\"globalAnnotations\":true}; line: 1, column: 91] (through reference chain: net.opentsdb.core.TSQuery[\"queries\"]->java.util.ArrayList[0]->net.opentsdb.core.TSSubQuery[\"tags\"])\n\tat net.opentsdb.utils.JSON.parseToObject(JSON.java:112) ~[tsdb-2.2.0.jar:07d0464]\n\tat net.opentsdb.tsd.HttpJsonSerializer.parseQueryV1(HttpJsonSerializer.java:210) ~[tsdb-2.2.0.jar:07d0464]\n\t... 44 common frames omitted\nCaused by: com.fasterxml.jackson.databind.JsonMappingException: Can not deserialize instance of java.util.LinkedHashMap out of START_ARRAY token\n at [Source: {\"start\":1460627244416,\"queries\":[{\"metric\":\"cpu\",\"aggregator\":\"avg\",\"downsample\":\"2s-avg\",\"tags\":[]}],\"msResolution\":false,\"globalAnnotations\":true}; line: 1, column: 91] (through reference chain: net.opentsdb.core.TSQuery[\"queries\"]->java.util.ArrayList[0]->net.opentsdb.core.TSSubQuery[\"tags\"])\n\tat com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:148) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:749) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:745) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:307) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:26) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:232) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:206) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:25) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:538) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:99) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:238) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:118) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3051) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2146) ~[jackson-databind-2.4.3.jar:2.4.3]\n\tat net.opentsdb.utils.JSON.parseToObject(JSON.java:108) ~[tsdb-2.2.0.jar:07d0464]\n\t... 45 common frames omitted\n"}}`

**Comment by ovx** [comment]
Update: filters work, I just didn't click "add filter" button, which is not really a button - UI could be improved. When the filters are set, the tags are ignored and the query is fine. So the issue occurs only when the filters are empty.

**Comment by ovx** [comment]
Also, is it possible to use templates in the filters? A filter like this: `host = iliteral_or($host) , groupBy = false` doesn't work - it doesn't replace `$host` (the template $host is defined and works in the Title)

**Comment by paolo-ran** [comment]
1+

I am using the same setup as ovx (see the first message for more info) and I can't make the template values work in the Grafana Metrics Filters too.

E.g.:
- $host is not converted into its selected value/s when mentioned in a Grafana Metrics Filter; <- FAILS
- $host is converted into its selected value/s when mentioned in a Grafana Metrics Tag. <- SUCCEED.

I was please to see they work in the Grafana Metrics Tags. However, in my use case I really need them working in the Grafana Metrics Filters, otherwise I will have to migrate to another solution.

Is that a bug, a current limitation in Grafana or am I missing something?

**Comment by utkarshcmu** [comment]
So there are two issues here:

1. When tags and filters both are empty, the query sent to opentsdb has the wrong format with tags[]. - Possibly a bug.

2. Filters do not work in templates for opentsdb currently in master. - Its a feature request for which PR #4594 is pending.

Will update the issue as soon as I can make some progress on these.

**Comment by paolo-ran** [comment]
Thank you, much appreciated. Looking forward to it.

**Comment by utkarshcmu** [comment]
@ovx ,

My setup : 
Grafana-3.0.0.-beta5
Opentsdb 2.2.0

Grafana builds this query for me, where tags is object and not an array.:
```
{"start":1460710670899,"queries":[{"metric":"httpcode_backend_2xx.sum.count","aggregator":"sum","downsample":"30s-avg","tags":{}}],"msResolution":true,"globalAnnotations":true}:""
```

Here is the query editor, where tags and filters are both empty:
<img width="1426" alt="screen shot 2016-04-15 at 8 01 08 am" src="https://cloud.githubusercontent.com/assets/1019609/14565546/781c30c0-02e0-11e6-91dd-c8270e809edf.png">

Here is my datasource configuration:
<img width="699" alt="screen shot 2016-04-15 at 8 01 36 am" src="https://cloud.githubusercontent.com/assets/1019609/14565556/8d7fb20c-02e0-11e6-98d6-c6b0a32836eb.png">

Not able to reproduce the 1st issue for **tags** being an array.

**Comment by ovx** [comment]
Upgraded to Grafana 3.0.0-beta5. It is still happening, but only IF you have multiple data sources and your 'default' is InfluxDB. Looks like some configuration isn't 'forgotten' after switching to OpenTSDB.

When OpenTSDB is set as default, it works fine.

**Comment by utkarshcmu** [comment]
I think its your panel JSON which was having Influxdb tags saved as an array. If you try to create a new graph with Opentsdb datasource (even though Opentsdb is not your default datasource), you should be good I guess.
