### ISSUE TITLE
auth.ldap: sync_cron is not standard UNIX cron format

### ISSUE THREAD

**Issue by Dentrax** [grafana/grafana#47001]
_I couldn't find the right issue template, so decided to go with _bug_ template. Feel free to move correct place to discuss this._

---

**What happened**:

Grafana uses non-standard cron expression format that have 6 space-separated fields, which is not UNIX standard. It was the first time I had used this `sync_cron` field, and it was a bit difficult to distinguish cron syntax in the first place, as I could not parse that syntax in cron editors.

Ref: https://github.com/grafana/grafana/blob/main/docs/sources/enterprise/enhanced_ldap.md#active-ldap-synchronization=

**What you expected to happen**:

cron format must contain 5 asterisks (*).

* https://linux.die.net/man/5/crontab
* https://www.ibm.com/docs/en/db2oc?topic=task-unix-cron-format

**How to reproduce it (as minimally and precisely as possible)**:

Set [sync_cron](https://github.com/grafana/grafana/blob/6c468daabcce01c833201a1bb5d9d3afdd14d271/conf/sample.ini#L584) field that have 6 separated fields.

I also would like to listen the motivation that we can sync ldap in under a minute.

**Anything else we need to know?**:

**Environment**:
- Grafana version: `v8.4.4`
- Data source type & version: `-`
- OS Grafana is installed on: `-`
- User OS & Browser: `-` 
- Grafana plugins: `-`
- Others: `-`

**Comment by Jguer** [comment]
Hey @Dentrax, this was fixed in Grafana v9.0.0 in this PR https://github.com/grafana/grafana/pull/47983 

Ping me to reopen this issue if you spot any other issue with the cron sync
