### ISSUE TITLE
Router_logging missing userid and uname

### ISSUE THREAD

**Issue by nicolastakashi** [grafana/grafana#47006]
**What happened**:

I’m using AzureAD as an Identity Provider and in the previous Grafana version that I was using 7.6, I was able to see the user ids and names in the router Logging

**What you expected to happen**:

In Grafana 8 I would like to keep seeing the userid and uname in the router logs

**How to reproduce it (as minimally and precisely as possible)**:

Just enabling Azure AD authentication and enabling the router_logging

**Anything else we need to know?**: 

N/A

**Environment**:
- Grafana version: 8.4
- Data source type & version: N/A
- OS Grafana is installed on: Kubernetes 1.22
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others:

**Comment by mckn** [comment]
Related to https://github.com/grafana/grafana/issues/45752

**Comment by marefr** [comment]
Duplicate of #45752

**Comment by marefr** [comment]
Oops sorry noticed the comment in #45752 now.

**Comment by nicolastakashi** [comment]
Hi, @marefr could this fix be released alongside the log info?

**Comment by marefr** [comment]
@nicolastakashi yes, we'll try to include this fix as well.

**Comment by krzysion** [comment]
In Grafana 8.4.5 logs there are still no uname, userId, orgId fields.

**Comment by nicolaerosia** [comment]
hopefully 8.4.6 gets out fast

**Comment by marefr** [comment]
@nicolaerosia yes that's correct. [8.4.6](https://grafana.com/blog/2022/04/12/grafana-enterprise-8.4.6-released-with-high-severity-security-fix/) was a security release only including that security fix. This will be included in 8.4.7 hopefully released soon.
