### ISSUE TITLE
[Question] Changes on "grafana.db" when updating Grafana to v.3.0.0

### ISSUE THREAD

**Issue by sbengo** [grafana/grafana#4701]
Hi,

We are preparing to update Grafana to v.3.0.0 from 2.6.
· We have 2 environments `test` and `pro`. 
· Each environment has it's own grafana.db, let me alias them as `test.db` and `pro.db`

To ensure there is no problem at production enviroment, we will copy pro.db and set as grafana.db on test environment. 

The next step is be sure that the dashboards keep working on the new version. After the check, we will upgrade Grafana version on production and just copy pro.db(from test) into our pro environment.

The problem is that we don't want to lose our test.db (non used when upgrading to 3.0 in any environment) so the following question comes up:

· What happens if we use an old Grafana 2.6 grafana.db on a host with 3.0 version?
· The grafana.db changes when we upgrade Grafana?
· When grafana service is started, it checks what db version is using?

Hope I have explained well,
Thanks for all!

**Comment by torkelo** [comment]
When grafana starts it will look in the migration_log table and upgrade the database via a series of migrations so it conforms to the latest schema, so if you start Grafana 3.0 with a Grafana 2.6 db it will upgrade the database (so if you later downgrade grafana to 2.6 there are no guarantee that it will work, it will likely work as it quite rare that we do changes to the db that are not backward compatible)
