### ISSUE TITLE
[Bug] Wrong colors in tooltip with Light theme

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#4702]
* What grafana version are you using? grafana-3.0.0-beta41460581169.x86_64
* What datasource are you using? InfluxDB
* What OS are you running grafana on? RHEL7.2

![captura de pantalla de 2016-04-14 12-32-00](https://cloud.githubusercontent.com/assets/3237784/14525278/fb92530c-023c-11e6-922f-caf419747286.png)

**Comment by torkelo** [comment]
thanks for reporting this, will fix!
