### ISSUE TITLE
Alert email does not show details

### ISSUE THREAD

**Issue by tooptoop4** [grafana/grafana#47037]
**What happened**:

received an email with no details about the alert:

![image](https://user-images.githubusercontent.com/33283496/160755003-98d90abc-50c5-4b53-816a-ee8ab6e01c35.png)

**What you expected to happen**:

receive an email with details about the alert (below shows the value/description i expect which i assumed would be default):

![image](https://user-images.githubusercontent.com/33283496/160755332-99c0a6d9-36d4-4f26-97a9-8cdbceb78e39.png)
here is more about my alert definition:
![image](https://user-images.githubusercontent.com/33283496/160755431-ee70d882-5fdc-462e-9297-9216b1f32722.png)

**Environment**:
- Grafana version: 8.4.4 (unified alerting enabled)

**Comment by JacobsonMT** [comment]
Duplicate https://github.com/grafana/grafana/issues/42946
