### ISSUE TITLE
LogQL from Log Browser not masking regular expressions

### ISSUE THREAD

**Issue by Falco20019** [grafana/grafana#47039]
**Describe the bug**
When selecting more than one entry from the Log Browser, it creates an or'd regex matcher. The resulting selector is not valid when the label contains regex meta-characters like here:
`{start_time=~"2022-03-30T07:38:30.7156355+02:00|2022-03-30T07:38:40.7643603+02:00"}`

**To Reproduce**
1. Started Loki v2.4.2
2. Import any data with labels containing regex meta-characters (at least two necessary)
3. Select at least two items in Log Browser to get an invalid selector
4. Run the selector to get no data

**Expected behavior**
The selector should escape the meta-characters like this:
`{start_time=~"2022-03-30T07:38:30\\.7156355\\+02:00|2022-03-30T07:38:40\\.7643603\\+02:00"}`

**Environment:**
 - Infrastructure: Docker using grafana/loki:2.4.2 and grafana/grafana:8.4.4
 - Deployment tool: Docker

**Screenshots, Promtail config, or terminal output**
![image](https://user-images.githubusercontent.com/940619/160760736-04c69cfd-0ada-4e09-9992-2864b727614b.png)

**Comment by dannykopping** [comment]
Transferred here from `grafana/loki` as it concerns the Grafana frontend only, not Loki the database

**Comment by Falco20019** [comment]
Using variables in dashboards works by the way. It's only occurring in the Log Browser.

**Comment by gabor** [comment]
should be fixed by https://github.com/grafana/grafana/pull/47412, closing the issue.

(if it is still not fixed, please comment here and we can reopen the issue)
