### ISSUE TITLE
Docs feedback: /datasources/azuremonitor/template-variables.md

### ISSUE THREAD

**Issue by W1ll1amz** [grafana/grafana#47047]
I've encountered a couple of issues while trying to implement Azure metrics variables using the info on this page:

1) the variable references on the page have the letter 'a' as the variable prefix instead of the correct '$' (dollar) prefix character. This is confusing to newcomers. Example: Namespaces(aResourceGroup) should be shown as Namespaces($ResourceGroup).

2) it is not possible to define the 'MetricNames' variable using the info on this page because one of the prerequisite parameters ($MetricDefinition) has not been defined on the page. I think this is an omission/oversight.

MetricNames(aResourceGroup, **aMetricDefinition**, aResourceName, aMetricNamespace)

**Comment by bmoe24x** [comment]
Same issue.

**Comment by taleena** [comment]
I know this is from a bit ago, so is this still valid?

I did a search in our docs (https://grafana.com/search/?type=doc) for each "aResourceGroup", "aMetricNamespace", etc, and didn't find anything, so this may no longer be valid, in which case, let's close it out.

**Comment by W1ll1amz** [comment]
The original page was: https://grafana.com/docs/grafana/latest/datasources/azure-monitor/template-variables/

Looking at it now, it has been updated and there are no references to e.g. "Namespaces(aResourceGroup)" anymore.

I have no idea whether the other issue that I reported is still relevant or not as I gave up on this.

**Comment by taleena** [comment]
Got it, maybe that now lives more in https://grafana.com/docs/grafana/latest/dashboards/variables/add-template-variables/? In any case, I'll close this out. Thank you.
