### ISSUE TITLE
[UX] Unreadable color for code block with light theme

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#4704]
Text in a code block has same color as regular text, which is fine in the Dark theme:
![plugintext-dark](https://cloud.githubusercontent.com/assets/3284111/14527236/d97f6a96-0248-11e6-9a25-fdb2da3087d4.png)

But in the Light theme it is too similar to the background of the code block:
![plugintext-light](https://cloud.githubusercontent.com/assets/3284111/14527237/db720b56-0248-11e6-9eca-2c41c4217560.png)

Grafana 3.0.0-beta4

**Comment by torkelo** [comment]
thx for reporting this

**Comment by mattttt** [comment]
Fixed in PR https://github.com/grafana/grafana/pull/4711
