### ISSUE TITLE
Elasticsearch datasource alerts don't respect datasource setting max_concurrent_shard_requests

### ISSUE THREAD

**Issue by symmetriac** [grafana/grafana#47042]
**What happened**:
Alert query with elasticsearch datasource always happens with max_concurrent_shard_requests = 256 regardless of value in datasource settings, even if it set to 5. While queries from panels go with the right value.

**What you expected to happen**:
Alert query executes with max_concurrent_shard_requests parameter value as it's set in datasource settings.

**How to reproduce it (as minimally and precisely as possible)**:
Create elasticsearch datasource, set `Max concurrent Shard Requests` to 6 and Elasticsearch version 7.0+
Create panel with query and alert for with that query. Execute query from panel, look at query inspector and see the right value

`api/datasources/proxy/716/_msearch?max_concurrent_shard_requests=6`

Then run query from alert rule based on this query and see the log

`logger=tsdb.elasticsearch.client t=2022-03-28T12:27:14.43+0300 lvl=dbug msg="Executing request" url="https://elasticsearch/_msearch?max_concurrent_shard_requests=256" method=POST`

**Anything else we need to know?**:
If elasticsearch datasource was created with default `Max concurrent Shard Requests` for 7.0+ version, which is 5 and this values wasn't changed or updated, the alert query runs with max_concurrent_shard_requests=5. But if this value was changed and then returned to 5, it will be always 256.

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: Elasticsearch 
- OS Grafana is installed on: tested on deb package and docker image
- User OS & Browser: MacOS Chrome 99.0.4844.83
- Grafana plugins:
- Others:

**Comment by alexandrst88** [comment]
seems like issue related to type check 
https://github.com/grafana/grafana/blob/main/pkg/tsdb/elasticsearch/elasticsearch.go#L98.
