### ISSUE TITLE
Creating Annotations on an unnamed/unsaved Dashboard results in a broken Annotation

### ISSUE THREAD

**Issue by malcolmradelet** [grafana/grafana#47040]
**What happened**:

Created a new dashboard and panel, when satisfied I created an annotation to mark an incident. The annotation did not appear. I created an "annotations" panel to see what happened. It was there. But clicking on it fails.

1. After creation, the annotation will not show up on the panel
2. The annotation will appear in the "annotations" panel
3. Clicking the entry in the "annotations" panel will show an error "Unknown Dashboard: 0"
4. The annotation can not be deleted

![image](https://user-images.githubusercontent.com/29856299/160764660-648bf179-aa7b-482e-a680-d4d127b9d0d9.png)

**What you expected to happen**:

I expected the annotation to be visible (with no dashboard required) OR generate an error that the dashboard must be saved first

**How to reproduce it (as minimally and precisely as possible)**:
New Dashboard > Add a New Panel > Configure a Query > Add an Annotation

**Anything else we need to know?**:

**Environment**:
- Grafana version: v8.4.4 (fcfb01faeb)
- Data source type & version: Prometheus 2.32.1
- OS Grafana is installed on: Docker Container (Image: sha256:bdc63515e8db65a82cfb3c5422120d74993f805d8d608a3dc9e5974d9a0457fc)
- User OS & Browser: Windows 11, Google Chrome Version 99.0.4844.84
- Grafana plugins: Core only installed
- Others: N/A

**Comment by malcolmradelet** [comment]
Also, I cannot find any documentation on how to delete Annotations. They remain even after panels are deleted. Can I clear them out somehow?

**Comment by axelavargas** [comment]
Hey @malcolmradelet 👋🏾 , thanks for reporting this issue, I was able to reproduce it,  and I am moving it to our board to fix it in the future.

As a side note, we do support annotations without a dashboard id, these are considered global annotations and therefore should be displayed.  Maybe as a workaround in how to delete those annotations, we do offer [for built-in annotations API ](https://grafana.com/docs/grafana/latest/http_api/annotations/), you could use that API to delete them (not the easiest workaround, but still a workaround)
