### ISSUE TITLE
Clicking plugin in home dashboard uses extra redirect

### ISSUE THREAD

**Issue by jessetan** [grafana/grafana#4705]
Sorry about the title, could not find a better description.

1. Install a plugin (e.g. pie chart panel)
2. Go to Home Dashboard
3. Click plugin in "Installed Panels"
4. Browser goes to `/plugins/grafana-piechart-panel/edit?panelId=null&fullscreen=null&edit=null&editview=null`, *immediately* followed by going to `/plugins/grafana-piechart-panel/edit`
5. Pressing browser back button does not go back to Home Dashboard, but to `/plugins/grafana-piechart-panel/edit?panelId=null&fullscreen=null&edit=null&editview=null`

Expected:
5. Pressing back returns to Home Dashboard

Grafana 3.0.0-beta4

**Comment by torkelo** [comment]
thx for reporting this, will fix!
