### ISSUE TITLE
[Bug] Snapshot empty on Grafana 3.0

### ISSUE THREAD

**Issue by FireHelmet** [grafana/grafana#4706]
Hello all,

We have a problem with snapshots on Grafana 3.0 beta 1 (Grafana version: 3.0.0-pre, commit: v2.6.0-1629-gd3a4b7a, build date: 2016-03-31 06:27:08). All graphs are empty on the snapshot. You can look the screenshot in attachment. The problem is for all dashboards and I don't have this problem on 2.6.0 version.
![2016-04-14_13-23-52](https://cloud.githubusercontent.com/assets/17533298/14527473/91a19530-024a-11e6-9bee-1664c15f71c2.gif)

Do you have the same problem ?

Thank you for your support,

Jérôme

**Comment by torkelo** [comment]
thanks for reporting this, will fix asap

**Comment by FireHelmet** [comment]
Hello torkelo,

In addition you have the same problem on your live demo on grafana.org ;).

Thank you for your quick support ! :)

**Comment by FireHelmet** [comment]
Hello torkelo,

I have edited each file is your commit (6355896) but the problem is not fixed.

Thank you,

Jérôme

**Comment by torkelo** [comment]
@FireHelmet you need to rebuild the frontend assets to a concatenated minifed js file. Use latest beta5 build

**Comment by FireHelmet** [comment]
@torkelo Okay :).

Thank you for your quick answer and support.

**Comment by vitorboschi** [comment]
Using yesterday's nightly I still have some problems with snapshots. Opening the snapshot link in the same browser works, but when I open it on another one, only singlestats and graph legends appears. The graph lines don't appear and series avg,min,max values are displayed as NaN.

![image](https://cloud.githubusercontent.com/assets/71193/14817609/b15efed8-0b8e-11e6-9c1f-19201e07856e.png)

After loading everything, if I click  Grafana's refresh button, data is then displayed correctly. I can reproduce this behavior consistently here

**Comment by torkelo** [comment]
@victorhooi local or external snapshot?

**Comment by vitorboschi** [comment]
local.

ps: you've got the wrong vitor ;)

**Comment by torkelo** [comment]
@vitorboschi oḱ, found the cause, was introduced yesterday or this weekend when I did an panel loading optimization. 

fixed in https://github.com/grafana/grafana/commit/aa98ada141be668da628b48e721d5cb4128b2c70
