### ISSUE TITLE
[State Timeline] Absence of data not represented when color scheme is from threshold 

### ISSUE THREAD

**Issue by cykl** [grafana/grafana#47098]
**What happened**:

When using the the state timeline panel and _from thresholds_ color scheme absence of data is represented by the base color rather than no color (i.e. horizontal bar should stop). My use case is to use state timeline to visualize some ratio and I definitely want to distinguish absence of something from 0. 

Assuming your are using Grafana 8.3.4, absence of data is properly represented when using other color scheme (but doesn't work with later releases see https://github.com/grafana/grafana/issues/46805 and all parents issues).

**What you expected to happen**:

See above. 

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/1764725/161001860-6c0e9496-8923-4074-89cb-f04b4fa35a9f.mp4

**Anything else we need to know?**:

While I understand this is a beta panel, state timeline seems to have many issues and would benefit from some more QA.

**Environment**:
- Grafana version: 8.3.4 (cannot use later version because of https://github.com/grafana/grafana/issues/46805 which is still not fixed in any subsequent release)
- Data source type & version: Prometheus
- User OS & Browser: Firefox

**Comment by cykl** [comment]
Note that there might be two issues.

The first one seems like #46805 but only for _from threshold_ color scheme. If a time-series has no value for a time-series in the TSDB,  state timeline panel still draw a bar using the base color. I my example, this happens before ~15:00.

The second one is that null value is allow mapped to the base color. In my example, this happens after ~15:00 because my PromQL query is something like `sum(name(outcome="success")[2m]) / sum(name(outcome))` and denominator is 0 which according to the query inspector returns null values.

**Comment by cykl** [comment]
I just discovered a possible workaround by defining a null threshold with maximum transparency.

![image](https://user-images.githubusercontent.com/1764725/161042787-3c83bede-5129-4aa6-ac4d-4949cff38f12.png)

Defining a 0 threshold with some color and making base transparent doesn't work.

**Comment by JoaoSilvaGrafana** [comment]
Thanks for raising this! I have managed to reproduce it in 8.3.4, but not sure how new changes in state timeline affect it, so assigned it to the team responsible for it.

**Comment by zoltanbedi** [comment]
I was not able to reproduce this in 8.5.3 @cykl can you check if upgrading to latest fixes the issue for you?
![Screenshot 2022-05-26 at 15 01 42](https://user-images.githubusercontent.com/13729989/170492836-e460f6c1-e691-4a9e-a5b9-24c40655f632.png)


<details>
<summary>Dashboard json</summary>

```json
{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "links": [],
  "liveNow": false,
  "panels": [
    {
      "datasource": {
        "type": "testdata",
        "uid": "_6POemr7k"
      },
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "thresholds"
          },
          "custom": {
            "fillOpacity": 70,
            "lineWidth": 0,
            "spanNulls": false
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          }
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 0
      },
      "id": 2,
      "options": {
        "alignValue": "left",
        "legend": {
          "displayMode": "list",
          "placement": "bottom"
        },
        "mergeValues": true,
        "rowHeight": 0.9,
        "showValue": "auto",
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "datasource": {
            "type": "testdata",
            "uid": "_6POemr7k"
          },
          "rawFrameContent": "[\n\t\t{\n\t\t\t\"schema\": {\n\t\t\t\t\"name\": \"Something\",\n\t\t\t\t\"refId\": \"A\",\n\t\t\t\t\"meta\": {\n\t\t\t\t\t\"custom\": {\n\t\t\t\t\t\t\"resultType\": \"matrix\"\n\t\t\t\t\t}\n\t\t\t\t},\n\t\t\t\t\"fields\": [\n\t\t\t\t\t{\n\t\t\t\t\t\t\"name\": \"Time\",\n\t\t\t\t\t\t\"type\": \"time\",\n\t\t\t\t\t\t\"typeInfo\": {\n\t\t\t\t\t\t\t\"frame\": \"time.Time\"\n\t\t\t\t\t\t},\n\t\t\t\t\t\t\"config\": {\n\t\t\t\t\t\t\t\"interval\": 120000\n\t\t\t\t\t\t}\n\t\t\t\t\t},\n\t\t\t\t\t{\n\t\t\t\t\t\t\"name\": \"Value\",\n\t\t\t\t\t\t\"type\": \"number\",\n\t\t\t\t\t\t\"typeInfo\": {\n\t\t\t\t\t\t\t\"frame\": \"float64\",\n\t\t\t\t\t\t\t\"nullable\": true\n\t\t\t\t\t\t}\n\t\t\t\t\t}\n\t\t\t\t]\n\t\t\t},\n\t\t\t\"data\": {\n\t\t\t\t\"values\": [\n\t\t\t\t\t[\n\t\t\t\t\t\t1647875040000\n\t\t\t\t\t],\n\t\t\t\t\t[\n\t\t\t\t\t\t0\n\t\t\t\t\t]\n\t\t\t\t]\n\t\t\t}\n\t\t}\n\t]",
          "refId": "A",
          "scenarioId": "raw_frame"
        }
      ],
      "title": "Panel Title",
      "type": "state-timeline"
    }
  ],
  "schemaVersion": 36,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "2022-03-21T15:04:00.000Z",
    "to": "2022-03-21T16:06:00.000Z"
  },
  "timepicker": {},
  "timezone": "",
  "title": "New dashboard",
  "version": 0,
  "weekStart": ""
}
```
</details>

**Comment by cykl** [comment]
@zoltanbedi I wasn't able to it using 8.5.2. Let's assume it as been fixed as a side effect of some other changes. Thanks for having looked into this.
