### ISSUE TITLE
[Feat req]: Elastic search / Table panel, support many aggregations of same type

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4709]
Hi,

I created a table, with two metrics "sum":
In the picture: First Sum is daily_2 and Second Sum is sla_duration:
![table](https://cloud.githubusercontent.com/assets/15362041/14530356/ee73bbae-0258-11e6-8e68-b18ee20c6954.png)

The problem is: The table show only same sum, i cannot show different sum :
![tabole3](https://cloud.githubusercontent.com/assets/15362041/14530640/21929428-025a-11e6-9148-b76bc4ba04ef.PNG)

I configured my table as this
![table2](https://cloud.githubusercontent.com/assets/15362041/14530487/81b5b55c-0259-11e6-9433-8f2fef920a31.PNG)

I cannot select my second sum

I using Grafana 3.0 beta5 with ElasticSearch

**Comment by Azef1** [comment]
Up!
I really need to have his feature to finish my project in good conditions.
thx

**Comment by pierrecdn** [comment]
Is it not the same with Graphite as datasource ?
I'm currently trying to use Time series aggregation to show 2 columns, coming from 2 different metrics.
Does the table panel support that ?

**Comment by ldktta** [comment]
I need to have his feature to. 
thx

**Comment by ldktta** [comment]
Could you add this item in the next release?
I really need to see the information in this way. thx.!!

**Comment by snc29590** [comment]
+1. This is a very useful feature, and it would be great if this could be added in the upcoming Grafana release!
