### ISSUE TITLE
Alerting: Create a contact point type, which is an extension of Webhook.

### ISSUE THREAD

**Issue by YeongchanSeo** [grafana/grafana#47102]
**What happened**:
I want to pass the required url parameters in key and value format when sending an alert message using a Webhook contact point type. With using the current Webhook contact point type, I can still pass the url parameters as url components. But I cannot customize the title, body of alert message, and long sentences with url encoding are needed to be passed.

**What you expected to happen**:
I would like to add a contact point type called Webhook_ext, which is an extension of Webhook.
URL parameters can be added in key and value format like the screenshot below.
![Screen Shot 2022-03-31 at 5 49 42 PM](https://user-images.githubusercontent.com/28811725/161016191-530c94c5-18a9-4f36-bcf0-cdb2cc598db8.png)

I've done some code modifications for that part, so I'd like to write a PR if possible.

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: None
- OS Grafana is installed on: CentOS7
- User OS & Browser: macOS 12.0.1
- Grafana plugins: None
- Others: None

**Comment by mckn** [comment]
This should not really be an issue but rather a Github discussion but I let the developers working with alerting to do that if needed.

**Comment by YeongchanSeo** [comment]
@mckn 
I made 3 commits for this. It would be helpful if I can make a PR with this commits.

https://github.com/YeongchanSeo/grafana/commit/98f34bc23e2a3135263345434fea43f011922455
https://github.com/YeongchanSeo/grafana/commit/adeeeeaa2b3dde68309ac5cc170d2c24a593d360
https://github.com/YeongchanSeo/grafana/commit/2562a1225d160a0b8d3d74a3a293a67081c1f5f6

**Comment by YeongchanSeo** [comment]
@mckn
Hi,
How is this issue going?

**Comment by YeongchanSeo** [comment]
@mckn 
Hi,
Can I create a PR for this issue?

**Comment by YeongchanSeo** [comment]
@joeblubaugh 
Could you take a look at this one if I can create a PR for this issue? I wonder if you are the right person to ask about this, I just checked that you had commented from other alerting issue.

**Comment by joeblubaugh** [comment]
Hi @YeongchanSeo, I don't think we should make a PR directly from these commits. I'm opening a discussion titled ["Allow templating of URL parameters in the Webhook Contact Point" here](https://github.com/grafana/grafana/discussions/49973). My initial gut reaction is that we should discuss making this a first-class feature of the existing webhook contact point.

I've linked back to this issue so we don't lose context. Please feel free to correct my description there. We are currently [thinking about and working on template standardization](https://github.com/grafana/grafana/issues/49716) across Grafana Contact Points, so this discussion fits nicely in there.

**Comment by alexweav** [comment]
I agree with @joeblubaugh. In this case we should not add a new notifier that is an extension of webhook, but rather add these features to the existing webhook notifier directly. If you are still open to providing a PR in this direction, we'd be happy to review it!

Closing this for now, in favor of the discussion here where the extension is captured: https://github.com/grafana/grafana/discussions/49973
