### ISSUE TITLE
[Feature Request] Add support for performing math across multiple fields to InfluxDB query builder

### ISSUE THREAD

**Issue by pprkut** [grafana/grafana#4710]
Currently, Grafana (2.6) supports math functionality with the field on the left side within the InfluxDB query builder. I.e. it can build queries like

```
SELECT mean("field") / 100 AS "field" FROM "measurement" WHERE "tag" = 'value' AND $timeFilter GROUP BY time($interval) fill(null)
```

It would be nice to also have support for math with fields on both sides, for example something like

```
SELECT mean("field1") + mean("field2") + mean("field3") AS "field" FROM "measurement" WHERE "tag" = 'value' AND $timeFilter GROUP BY time($interval) fill(null)
```

**Comment by deric** [comment]
:+1:

**Comment by roycepope** [comment]
This would be amazing!

**Comment by dugwood** [comment]
Isn't it a duplicate of #3552?

**Comment by torkelo** [comment]
you can do this in the raw query build mode, with the editor it becomes hard to do
