### ISSUE TITLE
Angular migration guide: "using getValueFormat vs getMappedValue"

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#47104]
Goal: 
- Have a migration guide on what to use `getValueFormat` or `getMappedValue` as all of the mapping helpers are similarly named and work differently
- `convertOldAngularValueMappings` also has a bunch of similar names and non-exported helpers

**Comment by mckn** [comment]
Maybe this is enough: https://grafana.com/developers/plugin-tools/migration-guides/angular-react/angular-react-convert-from-kbn
