### ISSUE TITLE
Previews: Track the OSS adoption

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#47127]
Grafana uses the [usage stats service](https://github.com/grafana/grafana/blob/d5883c1b278efcc7bda52b73b98c8e239c561c7a/pkg/infra/usagestats/service/usage_stats.go#L276-L282) to gather simple information from grafana instances running in the wild: https://grafana.com/docs/grafana/latest/administration/configuration/#reporting_enabled. We would like to use the usage stats service to keep track of the adoption of the dashboard preview feature after we roll out the beta version. 

Usage stats tracking is designed to be as minimal and as unobtrusive as possible, so we need to keep that mind when figuring out what data to send - we need to balance between its usefulness and simplicity.

####  1 - a boolean indicating whether the feature flag is enabled

```
stats.features.dashboardPreviews: 1 
```

The major con of this stat is that the feature might not be usable even if its enabled because of e.g. outdated image renderer. The stat would be useful for measuring interest rather than actual usage

#### 2 - booleans for each enabled feature flag

```
stats.features.dashboardPreviews: 1 
stats.features.annotationComments: 1 
stats.features.migrationLocking: 1 
```

Our use case is not unique, so we might save some work in the long run by implementing the tracking in a generic way

#### 3 - send the number of previews saved in the db

```
stats.dashboard_previews.count: 50
```

Sending the number of previews allows for tracking # of instances which were correctly set up for the feature, ie. have the feature flag enabled and have an up-to-date image renderer plugin. Still, having the previews in the database doesn't actually mean that they are being used.

#### 4 - send the number of users with enabled `show previews` toggle

```
stats.dashboard_previews_users.count: 50
```

This one covers it all but it requires some extra (small) dev work and is already covered by rudderstack integration in the cloud version

**Comment by ArturWierzbicki** [comment]
@pkolyvas - thoughts? I think a combination of option 1 & 3 or 2 & 3 should be good enough

**Comment by ryantxu** [comment]
2 is interesting in general -- especially as we make more feature flags "public" and not just developer process
