### ISSUE TITLE
[Bug] Icons are missing on ubuntu 16.04

### ISSUE THREAD

**Issue by hryamzik** [grafana/grafana#4712]
Grafana version is 2.6.0+dfsg-1, installed with official repository. 

Already reported at #4528 and it turned out to be an issue not related with proxy. Also described [here](https://groups.io/g/grafana/thread/icons_missing_from_grafana/843895?p=,,,20,0,0,0:RecentPostDate,,,20,2,0,843895)

**Comment by torkelo** [comment]
a bug in safari when using some ports, try changing port. 

What OS and browser are you using?

**Comment by hryamzik** [comment]
Well it's the default https port, I've also tried default http. Chrome and Safari on Mac OS.

**Comment by torkelo** [comment]
strange, do you get icons on http://play.grafana.org ? No one else has reported any issues with icons (except with some version of safari and port 3000)

**Comment by hryamzik** [comment]
I do get them in any browser. Well, 16.04 is an RC yet and will be released on 21st of April so there might not be many grafana users on it.

**Comment by torkelo** [comment]
not sure the OS your running grafana-server on matters, 

> I do get them in any browser

was that a typo? did you mean not?

**Comment by hryamzik** [comment]
Nope:

![image](https://cloud.githubusercontent.com/assets/1643962/14538187/1cc1aa6e-0283-11e6-9686-1bf6fe8a9038.png)


And I didn't face any issues with icons before. The other strange thing is that I don't see any console errors so I'm stuck on figuring out the issue. Does this gear have a separate file or is it fully described in css?

**Comment by torkelo** [comment]
everything is combined and minified in the css, but the fonts area also loaded, check chrome dev tools network tab, could be that your web server is blocking the font files

**Comment by hryamzik** [comment]
All the status codes are 200 and I've connected directly to grafana server over ssh port binding to avoid any proxy related issues.

**Comment by hryamzik** [comment]
Here's the answer:

```
grafana:
  Installed: 2.6.0+dfsg-1
  Candidate: 2.6.0+dfsg-1
  Version table:
 *** 2.6.0+dfsg-1 500
        500 http://mirror.servers.com/ubuntu xenial/universe amd64 Packages
        100 /var/lib/dpkg/status
     2.6.0 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.5.0 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.1.3 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.1.2 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.1.1 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.1.0 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.0.2 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
     2.0.1 500
        500 https://packagecloud.io/grafana/stable/debian wheezy/main amd64 Packages
```

**Comment by donpdonp** [comment]
I'm a little confused as to what the fix is to this. I've got a 16.04 VM with nginx in front of grafana. Everything works except about half the menu icons are gone, and half are there (live updates seem to be broken too, but not completely sure on that). The network tab in the browser shows no 404 errors.

**Comment by hryamzik** [comment]
@donpdonp you have wrong package installed. Ubuntu 16.04 repositories contain grafana without icons, it's version is ```2.6.0+dfsg-1```. Just prevent it from being installed from Ubuntu repos:

```
cat /etc/apt/preferences.d/grafana
Package: grafana
Pin: release o=Ubuntu
Pin-Priority: -1
```

**Comment by donpdonp** [comment]
hmm. 2.6.0+dfsg-1 appears to be the installed version.

```
root@gaia:~# dpkg -l grafana
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                  Version         Architecture    Description
+++-=====================-===============-===============-===============================================
ii  grafana               2.6.0+dfsg-1    amd64           feature rich metrics dashboard and graph editor
```

**Comment by donpdonp** [comment]
What other repo is available for Ubuntu installs? https://packagecloud.io/grafana/stable/ appears to not have entries for ubuntu versions.

**Comment by hryamzik** [comment]
https://github.com/gitinsky/ansible-role-grafana/blob/master/tasks/main.yml#L5

**Comment by hryamzik** [comment]
Don't forget to uninstall the dfsg-1 version and all it's dependencies first.

**Comment by minida28** [comment]
I am also having exact same problem (missing icon) when I tried dfsg-1 version. I am on Lubuntu 16.04, 32 bit (i686).

Is there other repo where I can find latest grafana for 32bit OS?
All packages for Debian at official packagecloud.io are 64bit.

Thanks in advance.

**Comment by hryamzik** [comment]
@minida28 all the answers are in this issue...

**Comment by minida28** [comment]
@hryamzik Thanks. I think the only option for me is to build for my self, as depicted here #1968 :disappointed_relieved:

**Comment by hryamzik** [comment]
@minida28 well, if you can't install from the official repo as described here...

**Comment by hryamzik** [comment]
Yep, 32 bit packages seem to be missing, that's OK in 2016. ;-)

**Comment by minida28** [comment]
Ok just want to report the build guide works in Lubuntu 16.04 32bit and the icons now show up.
The build guide recommend to install Golang v1.5, instead I install Golang 1.7, but not sure what the side effect will be...

![capture](https://cloud.githubusercontent.com/assets/3026584/17745584/947b4ea6-64d6-11e6-8e40-4d887af10d29.JPG)

Cheers,

**Comment by anash28** [comment]
@minida28 Sorry for the confusion, how did you manage to downgrade Grafana on 16.04. Unfortunately I dont want to rebuild the package from source

**Comment by minida28** [comment]
@anash28 No I did not downgrade it, I built it from source!
My system is 32 bit and AFAIK there is no repo for 32 bit Ubuntu 16.04, so building from scratch was the only option for me.
If you are in 64 bit, you can try using older Debian binary here: https://packages.debian.org/sid/grafana

**Comment by xLorix** [comment]
Hi, 
I know no one will probably benefit from this but I found how to solve the problem of the missing icons in the ubunutu 32 bit version of Grafana: there are some missing css files in /usr/share/grafana/public/css !
The original 32 bit installation includes only the .original files below, while the complete set includes 7 .css files.
I copied them from the 64 bit version and it seems to work.

This is my current listing of /usr/share/grafana/public/css:
```
-rw-r--r-- 1 root root 141122 ott  4 22:55 bootstrap.dark.min.css
-rw-r--r-- 1 root root 139964 ott  4 22:55 bootstrap.light.min.css
-rw-r--r-- 1 root root  14192 ott  4 22:55 bootstrap-responsive.min.css
-rw-r--r-- 1 root root 202611 ott  4 22:57 grafana.dark.min.a95b3754.css
-rw-r--r-- 1 root root 202611 ott  4 23:01 grafana.dark.min.css
-rw-r--r-- 1 root root 168798 feb 14  2016 grafana.dark.min.original
-rw-r--r-- 1 root root 201453 ott  4 23:01 grafana.light.min.css
-rw-r--r-- 1 root root 201453 ott  4 22:57 grafana.light.min.fbdfba63.css
-rw-r--r-- 1 root root 167706 feb 14  2016 grafana.light.min.original
```

Bye,
Loris
