### ISSUE TITLE
template query regex capture changes after upgrade

### ISSUE THREAD

**Issue by davidbirdsong** [grafana/grafana#4713]
Ex
* What grafana version are you using?
3.0.0-beta3
* What datasource are you using?
prometheus

* What OS are you running grafana on?
Ubuntu 14.04.2 

upgrading from
```shell
Version: 3.0.0-pre1, Commit: v2.6.0+70-gf355f36, Build date: 2015-12-15 13:23:37 +0000 UTC
```
to:
```shell
Version 3.0.0-beta3 (commit: v3.0-beta2+93-g782c484)
```

previous to upgrade, I had a list of servernames that were extracted from a prometheus query. i had the values set on 'never' for update. here's the list:
<img width="1396" alt="grafana_template_values_frozen" src="https://cloud.githubusercontent.com/assets/407603/14538713/ef724a74-0231-11e6-97f2-710eea68d03b.png">

by editing the regex, clicking out, then editing back to the saved value, I caused grafana to re-query for tags. The captures don't work as before:
<img width="1411" alt="grafana_template_values_requeried" src="https://cloud.githubusercontent.com/assets/407603/14538888/cb9311fa-0232-11e6-9cdb-6f4753f02173.png">

Was there a change to the regex capture syntax?

**Comment by torkelo** [comment]
fixed in latest beta4, 
https://github.com/grafana/grafana/issues/4672
