### ISSUE TITLE
Improve narrow viewport behavior for alert edit view

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#47140]
I found a couple of responsiveness/narrow view issues in the alert edit view.

1. Horizontal scrollbar causes hamburger to be covered by other content
![image](https://user-images.githubusercontent.com/53754871/161074353-30361247-1574-46af-83d6-4bb097821c50.png)

2. Horizontal scrollbar is introduced without optimizing whitespace
👇   Not space-efficient: Around 70px of margins that are not needed for narrow widths
![image](https://user-images.githubusercontent.com/53754871/161074125-9e71add4-6f15-42d7-9748-5aa0da3e3fd5.png)

👇  ✅  Space-efficient: Start with the content right on the left
![image](https://user-images.githubusercontent.com/53754871/161074318-45c00477-381e-4fc8-9d10-88aaf0ead920.png)

3. Expressions are overflowing their container for narrow widths
![image](https://user-images.githubusercontent.com/53754871/161074398-c69b9920-dd29-446a-a316-86e466213365.png)

**Comment by peterholmberg** [comment]
@jessover9000 what's the minimum width used here?

**Comment by jessover9000** [comment]
@peterholmberg Not fully sure what you mean by min-width? The problematic behavior starts at <768px, the classic condition rows don't break/resize at <900px. Is that what you were asking?

**Comment by VikaCep** [comment]
We've been reviewing this issue with @soniaAguilarPeiron and we found that most of what's reported here no longer happens and with the upcoming changes related to the alert rule creation flow this view will be completely redesigned so we think it's safe to close this issue. Please reopen if you disagree.
