### ISSUE TITLE
Grafana panel throws Unknown Error During Query Transaction when the value All is selected

### ISSUE THREAD

**Issue by NiyiOdumosu** [grafana/grafana#47159]
**What happened**:
I have panels that use template variables for filtering. All of a sudden, whenever I select `All` as the value, it shows no data and gives the following error.

<img width="950" alt="Screen Shot 2022-03-31 at 1 42 37 PM" src="https://user-images.githubusercontent.com/35928853/161119652-ded6c4b3-c074-4dc7-b1d6-4c089a5508a1.png">

But when we filter for one or more values, it works:

<img width="1364" alt="Screen Shot 2022-03-31 at 1 55 10 PM" src="https://user-images.githubusercontent.com/35928853/161119305-caab9e59-3f43-4402-80db-5a000780ee60.png">

**What you expected to happen**:
I expect it to show all the metrics for all the values in the time series. 

**How to reproduce it (as minimally and precisely as possible)**:
Create a panel that uses a Grafana variable and Prometheus label. `{variable=~"$variable"}`. Then select `All`

**Anything else we need to know?**:
This issue happens intermittently. 

**Environment**:
- Grafana version: 7.5.4
- Data source type & version: Prometheus

- OS Grafana is installed on: Linux
- User OS & Browser:
- Grafana plugins: None
- Others:

**Comment by mckn** [comment]
Can you please provide the panel query information to assist with further investigation. You can extract it by doing the following steps:

1. Inspect the panel to bring up the panel inspector.
<img width="633" alt="Skärmavbild 2021-11-18 kl  15 19 44" src="https://user-images.githubusercontent.com/172951/142432997-6ab30370-1913-46e7-a729-cef329d2ddcf.png">

2. Press the `refresh` button to trigger a new query request.
<img width="588" alt="Skärmavbild 2021-11-18 kl  15 20 36" src="https://user-images.githubusercontent.com/172951/142433065-95a9272c-bd37-42f6-ac96-0c53df128260.png">

3. Copy the data from the query-tab to get the raw backend response.
<img width="738" alt="Skärmavbild 2021-11-18 kl  15 20 47" src="https://user-images.githubusercontent.com/172951/142433393-21af3652-350e-49a5-990a-fce2fb0702e7.png">

4. Attach the data to a comment in this issue. Thank you for helping us helping you 🙏🏻

**Comment by NiyiOdumosu** [comment]
Hello, for when the template variable's value is set to `all`, this is what I see below:

<img width="520" alt="Screen Shot 2022-04-01 at 11 34 02 AM" src="https://user-images.githubusercontent.com/35928853/161295895-b84d01dd-01de-4529-998d-f6f82a9c9e7f.png">


```
{
  "response": {
    "message": "Unexpected error"
  }
}
```

However, when one value is selected from the Grafana variable, it shows the following:
<img width="890" alt="Screen Shot 2022-04-01 at 11 36 54 AM" src="https://user-images.githubusercontent.com/35928853/161296227-00b03c09-4a1d-40f1-99e1-355785bdf388.png">


```
{
  "request": {
    "url": "api/datasources/proxy/1/api/v1/query_range?query=sum(kafka_connect_source_task_metrics_source_record_poll_total%7Bconnector%3D~%22(src-RDS-oasisreference-dbo-releaseversion-v0-pd%7Csrc-voip-ucce_hds-dbo-t_Call_Type_SG_Interval-inc2)%22%7D)%20by%20(connector)&start=1648827105&end=1648827405&step=15",
    "method": "GET",
    "hideFromInspector": false
  },
  "response": {
    "status": "success",
    "data": {
      "resultType": "matrix",
      "result": [
        {
          "metric": {
            "connector": "src-voip-ucce_hds-dbo-t_Call_Type_SG_Interval-inc2"
          },
          "values": [
            [
              1648827105,
              "1685250"
            ],
            [
              1648827120,
              "1685250"
            ],
            [
              1648827135,
              "1685250"
            ],
            [
              1648827150,
              "1685250"
            ],
            [
              1648827165,
              "1685250"
            ],
            [
              1648827180,
              "1685250"
            ],
            [
              1648827195,
              "1685250"
            ],
            [
              1648827210,
              "1685250"
            ],
            [
              1648827225,
              "1685250"
            ],
            [
              1648827240,
              "1685250"
            ],
            [
              1648827255,
              "1685250"
            ],
            [
              1648827270,
              "1685250"
            ],
            [
              1648827285,
              "1685250"
            ],
            [
              1648827300,
              "1685250"
            ],
            [
              1648827315,
              "1685250"
            ],
            [
              1648827330,
              "1685250"
            ],
            [
              1648827345,
              "1685250"
            ],
            [
              1648827360,
              "1685250"
            ],
            [
              1648827375,
              "1685250"
            ],
            [
              1648827390,
              "1685250"
            ],
            [
              1648827405,
              "1685250"
            ]
          ]
        }
      ]
    }
  }
}
```

**Comment by aocenas** [comment]
Hey @NiyiOdumosu sorry I could not reproduce it in new Grafana version. Can you upgrade? Otherwise 7.5 is pretty old so not sure we are going to backport a fix that far. Also one thing you can try is use regex or pipe format if that helps: https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/
