### ISSUE TITLE
[Question] Linux CPU %

### ISSUE THREAD

**Issue by Drewster727** [grafana/grafana#4716]
* What grafana version are you using? v2.6.0
* What datasource are you using? influxdb
* What OS are you running grafana on?  Ubuntu Server 15.10

Hello,

I'm very new to Grafana and have a question regarding CPU % graphing. Using telegraf/influxdb on the remote machine.

I want to track CPU % usage in addition to CPU load. I've got the load part figured out and that works great. However, the results of the CPU % graph are a bit puzzling. They go to wildly high percentages (500-1000%) -- I believe it is due to the fact that I have processes waiting so it has taken into account the number of cores and is just making the calculcation based on that?

What I really want is a cpu % that maxes out at 100%. This should take all cores into account. It seems like a simple thing that I should be able to do. Similar to how windows task manager reports overall CPU % usage, it shouldn't go past 100%.

Here's the graph currently, notice the high Y axis, and below it the query for it
![1](https://cloud.githubusercontent.com/assets/4528753/14542462/a7e07bd6-0254-11e6-9642-986b5b12bc22.png)

![2](https://cloud.githubusercontent.com/assets/4528753/14542500/c77a6326-0254-11e6-83d7-a2369341d293.png)

Thanks!

**Comment by torkelo** [comment]
You should pose this question in a InfluxDB forum or maybe for a telegraf forum. It all depends on how you collect the data. Grafana just shows you the data result from your query.

**Comment by Dual-Boot** [comment]
the query is incomplete.
the WHERE clause need Host=sever + cpu=cpu-total

**Comment by Drewster727** [comment]
https://github.com/influxdata/telegraf/issues/1029

I asked the telegraf guys and they're pointing the finger back here... Any ideas?

I did add the where clause on my query @Dual-Boot same issue...

**Comment by torkelo** [comment]
its not a Grafana issue, its a metric collection or a InfluxDB query issue, you InfluxDB query is returning spikes in the cpu data,  not sure what you want Grafana to do about that :)

**Comment by Drewster727** [comment]
@torkelo ok that makes sense. Sorry, not trying to blame grafana, just trying to figure out where I may have screwed up :)

**Comment by torkelo** [comment]
maybe you have multiple servers or multiple cores and need to divide or filter the query

**Comment by Drewster727** [comment]
@torkelo  I thought about that, but I am actually installing influx/telegraf on each machine separately, so I've ruled out the multiple server scenario, and as for the multiple cores, I am utilizing the cpu_total field which should take that into account, maybe I need to divide by # cores
