### ISSUE TITLE
[grafana-json-data-source] Grafana8+ Panel does not refresh after variables are changed

### ISSUE THREAD

**Issue by ChinaYyy** [grafana/grafana#47172]
The bug appears in the grafana version 8.2.3.
When i change variable, the json-api panel does not fresh.

- Grafana version: 8.3.2
- Data source type & version: [grafana-json-data-source](https://github.com/simPod/GrafanaJsonDatasource)
- OS Grafana is installed on:
- Grafana plugins: [grafana-json-data-source]

**Comment by ChinaYyy** [comment]
https://user-images.githubusercontent.com/23259782/161215740-d6280644-fc5c-41b7-bdee-3829832790fe.mov

**Comment by mckn** [comment]
This should be opened in the `grafana-json-data-source` project.

**Comment by ChinaYyy** [comment]
> 

I have opened an issue in  [grafana-json-data-source](https://github.com/simPod/GrafanaJsonDatasource/issues/221), but is has been closed because of no body processed.

**Comment by berlonics** [comment]
I had the same issue and fixed by playing with "Cache Time"  which corresponds to "cacheDurationSeconds" on a json file of a dashboard.
![github](https://github.com/simPod/GrafanaJsonDatasource/assets/12860263/fe58886d-8c2c-47a0-aca0-118ac3bd56eb)
