### ISSUE TITLE
Add row variables and selectors

### ISSUE THREAD

**Issue by mjf** [grafana/grafana#47180]
### Discussed in https://github.com/grafana/grafana/discussions/47179

<div type='discussions-op-text'>

<sup>Originally posted by **mjf** April  1, 2022</sup>
Hello team.

I propose to add variables we could assign to a particular (existing?) row (or multiple rows?) in the dashboard. Variable selectors of these variables would appear right under the particular row line (above the row content; the same way as the "global" variable selectors do now so that this part of code can be certainly reused).</div>

**Comment by mckn** [comment]
Closing this in favor of the GH discussion
