### ISSUE TITLE
Graph panel: Data Link editor automcomplete gives double $

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#47184]
**What happened**:
When I press `$` I get a pop-up, but after I select an item I have two `$$`, which causes an error when the link is used.

https://user-images.githubusercontent.com/8125524/161244703-54e82042-928d-4116-961a-6cc6d7c41b3f.mp4

**What you expected to happen**:

Just one `$`

**How to reproduce it (as minimally and precisely as possible)**:
In Graph panel, click on Data Link, edit, position cursor in the middle of existing text.

**Environment**:
- Grafana version: 8.5.0-a2463818pre
- User OS & Browser: MacOS 11.6.1; Chrome Version 99.0.4844.74 (Official Build) (arm64)

**Comment by zuchka** [comment]
Thanks for reporting this, @bboreham 

Here is a video with a quick reproduction method. It appears that if the datalink is not at the end of the string, the interpolation gets buggy:

https://user-images.githubusercontent.com/37156449/161619200-b5d11413-9d08-4414-9689-8383e8f0b068.mp4

**Comment by dprokop** [comment]
Seems like this bug only applies when selecting a template variable from the available options. To fix this we need to change the if/else statement here https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/DataLinks/DataLinkInput.tsx#L141
