### ISSUE TITLE
Time picker: zoom out on zero-width range does nothing

### ISSUE THREAD

**Issue by bboreham** [grafana/grafana#47186]
**What happened**:
Clicking on the magnifying glass does nothing, if the 'from' and 'to' times are equal.

https://user-images.githubusercontent.com/8125524/161247287-354d77ea-f7a6-4ed1-93d5-8cd5dc881d69.mp4

**What you expected to happen**:
I expected it to zoom out a little, maybe 20 seconds.

**How to reproduce it (as minimally and precisely as possible)**:
Select an absolute time range.
Make the end time the same as the start time.

**Anything else we need to know?**:
I did this because I was trying to select logs from a point in a metric panel, via the 'Data Link' function.

**Environment**:
Grafana version: 8.5.0-a2463818pre
User OS & Browser: MacOS 11.6.1; Chrome Version 99.0.4844.74 (Official Build) (arm64)

**Comment by JoaoSilvaGrafana** [comment]
Thanks for raising this! Opening a PR for a simple fix :)
