### ISSUE TITLE
[Question]

### ISSUE THREAD

**Issue by knightseal** [grafana/grafana#4720]
* What grafana version are you using?  grafana 3.0 beta4
* What datasource are you using? inflxudb 0.11.1
* What OS are you running grafana on? Centos 6.5

my questions is inflxudb Template Variables Can use in fileds?

![image](https://cloud.githubusercontent.com/assets/2109057/14551099/7c139c56-0301-11e6-8abd-da42f1d4a624.png)

![image](https://cloud.githubusercontent.com/assets/2109057/14551053/1c3d56a0-0301-11e6-8317-055a635d7c16.png)

it not work, But,I change The varibles name $/^item$/ -->$item it work!!!, mabe it is a bug

![image](https://cloud.githubusercontent.com/assets/2109057/14551222/b7f8a4ae-0302-11e6-85ec-e4d8b6dbdc1b.png)

**Comment by torkelo** [comment]
the auto complete is a just a suggestion, InfluxDB does not support regex in field selection I think
