### ISSUE TITLE
alerting query doesn't work

### ISSUE THREAD

**Issue by juanitomaille** [grafana/grafana#47204]
**What happened**:

Query in Alerting interface answer "nodata"
"view in explore" give 1 row

**What you expected to happen**:

1 row in query results

**How to reproduce it (as minimally and precisely as possible)**:

see captures.
![image](https://user-images.githubusercontent.com/44920274/161291989-7a2b97d5-2177-4a79-b5bc-39d7df5b7abd.png)

click on "view in Explore"
![image](https://user-images.githubusercontent.com/44920274/161292086-b6a22f38-e0ed-444c-8cb8-b2e8579f2944.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: influxDB 2.1
- OS Grafana is installed on: rpi zero 2 W
- User OS & Browser: chrome on win10
- Grafana plugins: nop
- Others:

**Comment by juanitomaille** [comment]
with removing last() , the same...

![image](https://user-images.githubusercontent.com/44920274/161297180-30ffeb25-c760-4c2b-959f-6a76712ad661.png)

**Comment by juanitomaille** [comment]
not completely sure, but I think that it worked in 8.4.3... (I firstly erased old alert and don't remember if the query was exactly the same)

**Comment by zuchka** [comment]
Thanks for creating this issue, @juanitomaille 

can you please try to share some steps so that we can reliably reproduce this issue? Or any other details? Anything in the developer console?

**Comment by zuchka** [comment]
> My alert is not based on numeric field, so, I don't have numeric field in my query result. (It's a state of machine)

I'm not sure if this is a bug...

**Comment by juanitomaille** [comment]
> I'm not sure if this is a bug...

What do you mean:
It's the origin of the problem but it's a normal behavior?
Or
It's not the origin of the problem?

**Comment by zuchka** [comment]
Apologies if don't understand, but it seems that you received and error saying that you are missing a numeric field, and then you state that you do not have a numeric field. So, I think you need to adjust your query or something on the DB side so that you are returning a query.

If you feel this is incorrect, please provide detailed steps so that the squads can reproduce the error. thank you! 👍

**Comment by juanitomaille** [comment]
Hello,

Ok, if you don't understand, I think it's the first solution -> it's a normal situation.

Simply : I don't have numeric field because I don't need numeric field.
I want to have an alert on string field : "on", "off", "error" -> if "error" send alert.

as I understand, alerting system of grafana is based on numeric comparizon and **its a limitation.** 

I will change my strategy with numeric codes and try again.

Something like : 0 -> off, 1 -> on, 2 -> standby, 3 -> error, if >=2 send alert.

Thanks for your help.
