### ISSUE TITLE
[Feature Request] Add organizations & users using API

### ISSUE THREAD

**Issue by linuxbutler** [grafana/grafana#4721]
Hi there

I would like the ability to create organizations and then users within that organization using the REST API. Right now I can do this manually using the front end, but I have to invite a user, log out, "accept" the invite as that user and then continue with the rest of my workflow. 

It would be ideal if this can be automated using the API from a programmatic viewpoint, where I can just create orgs/users with passwords. Just skip the whole invitation thing :)

It looks like right now, I can only "get" with the API, I can't really create new orgs/users.

Currently I am using Grafana 3.0 beta 3. 

Let me know if more information is required.
Thanks

**Comment by torkelo** [comment]
The http admin api allows you create users and orgs
http://docs.grafana.org/http_api/admin/
