### ISSUE TITLE
Docker: unable to open database file

### ISSUE THREAD

**Issue by raptor235** [grafana/grafana#4724]
Hey guys, I'm trying to follow the https://www.sitespeed.io/documentation/performance-dashboard/ instlalation instructions for grafana. 

I've setup a data folder outside of docker but when I run the docker run command the machine won't start. I'm getting 

Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
	Environment variables used:
  [0]: GF_SECURITY_ADMIN_USER=myuser
  [1]: GF_SECURITY_ADMIN_PASSWORD=*********
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2016/04/15 15:19:05 [I] Database: sqlite3
2016/04/15 15:19:05 [I] Migrator: Starting DB migration
2016/04/15 15:19:05 [log.go:75 Fatal()] [E] fail to initialize orm engine: Sqlstore::Migration failed err: unable to open database file

using this command to run 

docker run -d -p 3000:3000 \
-v /Users/bartdabek/Sites/general/sitespeed_docker/data:/var/lib/grafana \
-e "GF_SECURITY_ADMIN_USER=myuser" \
-e "GF_SECURITY_ADMIN_PASSWORD=MY_SUPER_STRONG_PASSWORD" \
--name grafana \
--restart="always" \
grafana/grafana

**Comment by torkelo** [comment]
maybe you dont have permission to write to /Users/bartdabek/Sites/general/sitespeed_docker/data ?

**Comment by crazy-canux** [comment]
why closed?
How to fix it?
