### ISSUE TITLE
[Question] Auto refresh URL parameter

### ISSUE THREAD

**Issue by jonatanblue** [grafana/grafana#4725]
Is it possible to pass a parameter in the URL to enable auto refresh (and set the refresh time) for a dashboard?

Grafana version: 2.6.0, commit: v2.6.0, build date: 2015-12-14 14:18:01
Datasource: Elasticsearch
OS: Docker container on Ubuntu 14.04

**Comment by torkelo** [comment]
no, this is not currently possible

**Comment by torkelo** [comment]
please use mailing list / slack for questions, http://grafana.org/support/

**Comment by jsjohnst** [comment]
Or you know, add the feature and document it, or document that you don't intend to support it. As there has been multiple requests for this, seems like that would be better than to blow off your users, but that is just me.

**Comment by torkelo** [comment]
Is not implementing every request blowing of your users ? Is asking them politely to ask question in the correct place blowing them off ? Really sorry if this was perceived that way, Anyway this was implemented long time ago, set auto refresh and see the url parameter being added

**Comment by jsjohnst** [comment]
@torkelo no, but sending them to a paid support page for a simple feature request does give that perception. If it's needed to pay a $7,200+ a year support contract to get a feature request to be considered and not just closed and punted, then something is wrong. I realize the OP worded it as a question, but at the time of their issue, it wasn't supported and I assume you knew that. I realize you get a decent volume of tickets, but this one seemed to be a recurring issue that's come up enough to warrant a better response. Sorry if I offended anyone by being direct with my reply, but it was frustrating at the time and I don't think I was completely out of line (albeit I could've soft handled it better and for that I apologize).

**Comment by jsjohnst** [comment]
Also, for the record, using Grafana 4.0.0 it doesn't add a URL parameter when auto-refresh is set and I tried every variation of query param naming I could think of and it never set auto-refresh, hence why I was digging through the code / docs.

**Comment by torkelo** [comment]
sorry, the mailing list / slack should also have been a link, not meant to link only to paid support. 

It was implemented in around v4.4 I think not sure

**Comment by jsjohnst** [comment]
Ty! Very helpful! I saw it tagged in milestone 4.0.0, so was confused.

**Comment by chrisatomix** [comment]
For anyone actually looking for the auto-refresh URL parameter (such as myself just now), it seems to be:
`&refresh=5s` (replace 5s with whatever interval you need, eg `30s`).
Even `1s` seems to work :+1: 

I believe the Grafana demo I'm using is version 4.6.2

Example public demo: ```https://demo.lightbend.com/grafana/dashboard/db/node-metrics?from=1517620727359&to=1517624327360&var-SelfNodes=All&var-RemoteNodes=All&kiosk=true&refresh=1s```
