### ISSUE TITLE
Not able to download windows version of beta 5...same was the case for beta 4

### ISSUE THREAD

**Issue by eben23** [grafana/grafana#4727]

**Comment by eben23** [comment]
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>winbuilds/dist/grafana-3.0.0-beta5.windows-x64.zip</Key>
<RequestId>A677588011DB44BF</RequestId>
<HostId>
eQ47A0/aFJr3N+9IGfv9lj8GYTw3hVoDgV2AEaGRPa/mK7MoRKgKF1yMW0roNfqTKABkfkrccqA=
</HostId>
</Error>

**Comment by torkelo** [comment]
thanks , fixed now
