### ISSUE TITLE
Alert error - "could not find datasource: database is locked"

### ISSUE THREAD

**Issue by Dhyanesh97** [grafana/grafana#47296]
**What happened**:

Configured 30 alert rules. 
25 alert rules - data source (influxdb)
5 alert rules - data source (cloudwatch)

For 4-5 alerts rules we are getting an error as "could not find datasource: database is locked". And it sends an error alert.
In the next run error goes away. But again after some time same error appears for different alert rule.

Error -

![image](https://user-images.githubusercontent.com/89400147/161500251-c084c89c-8ce0-4ca9-9fc3-18249ebe52a8.png)

Logs - 

![image](https://user-images.githubusercontent.com/89400147/161522969-dee67080-8d14-4394-9d55-132ef1e7e10d.png)

**What you expected to happen**:

Alert rules should be executed without any errors.

**How to reproduce it (as minimally and precisely as possible)**:

Configure multiple alerts using data source as influxdb. For few alerts error will occur as database is locked.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana - 8.2.1
- Data source type & version: Influxdb 2.0
- OS Grafana is installed on: Ubuntu 20.04.2
- User OS & Browser: Windows/Firefox

**Comment by Dhyanesh97** [comment]
![image](https://user-images.githubusercontent.com/89400147/161698113-87d5dcab-d42d-4ba4-945a-46fba2f6c984.png)

**Comment by zenzedoon** [comment]
i have the same issue , what type of database you use ??

**Comment by Dhyanesh97** [comment]
> i have the same issue , what type of database you use ??

InfluxDb

**Comment by zenzedoon** [comment]
i mean with grafana did you use SQLite , Postgres or Mysql ??

**Comment by Dhyanesh97** [comment]
> i mean with grafana did you use SQLite , Postgres or Mysql ??

InfluxDB only to fetch the data and setup an alert. Also I setup alerts using cloudwatch as data source.

**Comment by zenzedoon** [comment]
it is ok for the datasource but Grafana itself use a database to store dashbords, and all its relatd data , by default grafana comes with SQlite but we can use Mysql or Postgresql , the error database is locked comes from the perfomrance of SQlite as i think so may be the best solution is to migrate the default database (grafana.db) to MySQL or PostgreSQL.

**Comment by alexweav** [comment]
There will be a threshold of traffic at which SQLite becomes insufficient and cannot handle the number of concurrent requests. We generally advise that larger/prod deployments move to MySQL/PostgreSQL which can handle concurrent operations much better.

We have reduced several sources of database lock contention over the last few months so this problem likely has improved, but there will always be some point at which it will happen.

We provide some helpful tools for doing so: https://github.com/grafana/database-migrator

**Comment by zenzedoon** [comment]
Hello everyone, i come back to you ( :p with some delay sorry for that) to give you my feedback , i resolve that issue with the migration of the database from sqlite to mysql , the sqlite was insuffisiant for the number of request . So i some one get the same error please think to migrate your database as soon as possible . 
Thaks all for your comments.
