### ISSUE TITLE
[Bug] Time range zoom Tooltip

### ISSUE THREAD

**Issue by prajwalrao** [grafana/grafana#4729]
* What grafana version are you using? - v3.0.0b5
* What datasource are you using? - Custom
* What OS are you running grafana on? - Yosemite (10.10.5)

Time Range Zoom out tooltip says "Time range zoom in" instead of "Time range zoom out"..

<img width="312" alt="screen shot 2016-04-15 at 1 32 13 pm" src="https://cloud.githubusercontent.com/assets/15118150/14574144/956caf82-030e-11e6-9dae-ff3012de5e6a.png">

**Comment by torkelo** [comment]
ah, thanks, will fix
