### ISSUE TITLE
bug link on http://grafana.net/plugins/

### ISSUE THREAD

**Issue by roysbike** [grafana/grafana#4730]
Link is not correct http://grafana/net/plugins/ 
Please fix to http://grafana.net/plugins/

<img width="699" alt="2016-04-16 0 20 14" src="https://cloud.githubusercontent.com/assets/2388223/14575158/bfac45f0-0368-11e6-970c-0e9f4c3613b2.png">

**Comment by torkelo** [comment]
this has been fixed! :)
