### ISSUE TITLE
[Feature Request] More seamless playlist playback

### ISSUE THREAD

**Issue by rgelobterFH** [grafana/grafana#4731]
I would like to see improvements made to the Playlist functionality where there is not a full page refresh when switching between dashboards. I find it very annoying and not elegant when my playlist cycles between dashboards say every minute or every 5 minutes on a TV/kiosk and everything has to be re-rendered and the whole page refreshes/flashes. I imagine something where either the next dashboard is loaded/rendered in the background or there is a transition of sorts between each dashboard in the playlist.

grafana-3.0.0-beta51460725904.

**Comment by torkelo** [comment]
never seen this issue, dashboards usually loads within a seconds or so. 

There no option to load it behind in the background. that would be incredibly complex. Use a fast time series store or faster queries :)
