### ISSUE TITLE
At Grafana 9, we would remove the feature toggle for level and timestamp.

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#47319]

**Comment by marefr** [comment]
A description would be good.

We normally do breaking changes in major versions. So that would imply deprecation of things in v9 and removal in v10, or deprecation in v8.5 and removal in v9.

**Comment by mellieA** [comment]
From the parent issue - this is the final step **Make the new behaviour default at v9.0 then remove the feature toggle at v9.1 or v9.2**

We moved from log15 to gokit/log, there are several remaining issues to be solved: 

* The log printed out in the unit-tests, we need to find a decent way to discard them in the test.
Ticket: https://github.com/grafana/grafana/issues/47265
PR: https://github.com/grafana/grafana/pull/47353
* Once we correct the key/timestamp in the current log, we have to inform cloud and Grafana end-users (whoever is monitoring Grafana server) that the key/timestamp are changed, and they have to migrate the alerts etc if there are any. The safe way is to create feature toggle and activate/deactivate to make it backward compatible?
Ticket: https://github.com/grafana/grafana/issues/47266
PR: https://github.com/grafana/grafana/pull/47336
* Do a global presentation about current log system and share the best practice. https://github.com/grafana/grafana/issues/47270
* Remove level mapping we did in alerting and syslog https://github.com/grafana/grafana/issues/47299
* Add Unit into context logger for HG
Ticket: https://github.com/grafana/grafana/issues/47306
PR: https://github.com/grafana/grafana/pull/47356
* Make the new behaviour default at v9.0 then remove the feature toggle at v9.1 or v9.2 https://github.com/grafana/grafana/issues/47319

**Comment by marefr** [comment]
Sounds good to me :+1: 

Regarding matter of breaking an API I had this issue in mind #45752
