### ISSUE TITLE
Issue with the pie chart plugin

### ISSUE THREAD

**Issue by kramach1980** [grafana/grafana#4732]
I recently added the pie chart plugin in grafana. I have noticed an issue with it and would like to know if its my configuration or a real issue.

I read documents from elasticsearch by querying the index. If i have a graph that displays a bar for each document received, i get the right data. However, when i try to create a pie chart for total number of documents received, i see that it gets reset after about 15-20 mins even though i set the time to for ex: past 1 hour. The config is as follows:

Metric => SUm of count
Group by ==> Terms ==>passOrFail (This is a term in my ES document) which indicates if the document indicates a pass or a fail
Then by ==> Date Histogram ==>@timestamp

Any idea what could be happening?

**Comment by torkelo** [comment]
please open issue with pie chart panel repo
