### ISSUE TITLE
Displayed values change based on browser window width

### ISSUE THREAD

**Issue by kurtmd** [grafana/grafana#47332]
**What happened**:
Some values change based on browser window width.

**What you expected to happen**:
All values stay the same regardless of browser window width. 

**How to reproduce it (as minimally and precisely as possible)**:
I've copied some partially redacted panel JSON below:
```
{
  "datasource": "Example",
  "fieldConfig": {
    "defaults": {
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": []
  },
  "gridPos": {
    "h": 7,
    "w": 12,
    "x": 0,
    "y": 0
  },
  "id": 4,
  "links": [],
  "options": {
    "reduceOptions": {
      "values": false,
      "calcs": [
        "max"
      ],
      "fields": ""
    },
    "orientation": "auto",
    "text": {},
    "textMode": "auto",
    "colorMode": "value",
    "graphMode": "area",
    "justifyMode": "auto"
  },
  "pluginVersion": "7.5.10",
  "targets": [
    {
      "alias": "Example",
      "groupBy": [
        {
          "params": [
            "$__interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "0"
          ],
          "type": "fill"
        }
      ],
      "measurement": "/^$service$/",
      "orderByTime": "ASC",
      "policy": "default",
      "refId": "E",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "<my_param>"
            ],
            "type": "field"
          },
          {
            "params": [],
            "type": "sum"
          }
        ]
      ],
      "tags": [
        {
          "key": "env",
          "operator": "=",
          "value": "<my_env>"
        }
      ]
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Example 1",
  "type": "stat"
}
```

Once you've got data coming into that panel (big numbers will be easier to distinguish), fill one entire monitor with that browser window, refresh the dashboard (top right), and copy down that number.
![image](https://user-images.githubusercontent.com/70540353/161780650-b34dada1-5b47-46d0-8a5b-2bf833b4bf9a.png)
from query inspector:
![image](https://user-images.githubusercontent.com/70540353/161783102-2376104c-5de4-490a-8a69-1c62a84b7d31.png)

Then, shrink the window (say, by snapping the window to half of that monitor), and refresh the dashboard again.
![image](https://user-images.githubusercontent.com/70540353/161780971-2d380808-8c07-4603-9088-9ead9ebd7c43.png)
from query inspector:
![image](https://user-images.githubusercontent.com/70540353/161782835-0475c98f-91ff-419f-a72c-ea1565481f2f.png)

**Anything else we need to know?**:
I've heard of this happening on Windows and in other browsers as well, so I suspect it is not browser-dependent. Also, when I give half-a-monitor to Chrome and the other half to Safari, they show the same number on that panel.

This is also not DPI or monitor dependent, as moving a browser window from a 4k monitor to a 1080p monitor (without resizing) results in the same value.

**Environment**:
- Grafana version: Grafana v7.5.10
- Data source type & version: InfluxDB (built-in)
- OS Grafana is installed on: CentOS 7
- User OS & Browser:
MacOS Big Sur: 11.6
Chrome Version 99.0.4844.84 (Official Build) (x86_64), and
Safari Version 15.0 (16612.1.29.41.4, 16612)

**Comment by mellieA** [comment]
@kurtmd a few questions for you: 

* Are you using a specific time range in your dashboard? 
* From query inspector, can you share the time ranges included in the query result when the window is resized?
* What is the value of **max data points** for each size of browser window? Some datasources consolidate points to fit the width of the graph.

**Comment by ashharrison90** [comment]
hi @kurtmd 👋 

thanks for raising this!
i believe this is expected behaviour. by default, datasource queries are sampled differently based on the size of the panel. this is to ensure we're not retrieving more data than can realistically be displayed in our graphs. 

you can manually set the `max data points` option to a specific value to ensure you always get the same results 
![image](https://user-images.githubusercontent.com/20999846/162164614-a8bc4356-fefb-4ecb-85db-fec4b7e71c25.png)

hope that helps! 😄
