### ISSUE TITLE
[Bug] Regression when using templated variable which contains dots with annotations and influxdb

### ISSUE THREAD

**Issue by dje4om** [grafana/grafana#4733]
* What grafana version are you using : 3.0.0 beta5
* What datasource are you using : influxdb
* What OS are you running grafana on : Ubuntu 14.04

Hi,

I note a regression since beta3 when using this simple query in annotations :

`select text from events where $timeFilter and host = '$host'`

templated variable is : 
`show tag values with key = "host"`

if host contains this type of string : my.host.net (host in fqdn form), then i have this error : 

`Annotations error
InfluxDB Error Response: error parsing query: found \., expected identifier, string, number, bool at line 1, char 65`

if host = 'myhostnet' (hostname only), everything is ok

if i replace the annotation query with `select text from events where $timeFilter and host = 'my.host.net'`, it works fine.

i didn't test other characters which could be escaped.
the string is well formed in influxdb whithout backslashes.

its seems to be related to the fix of this closed issue for beta3 : https://github.com/grafana/grafana/issues/4602

**Comment by torkelo** [comment]
InfluxDB query template variables (when used in annotation queries and raw metric queries) are regex escaped in order to support matching multiple values. 

Ty this
`
select text from events where $timeFilter and host =~ /$host/
`

**Comment by dje4om** [comment]
thx ! i don't know why i didn't check this before ;), forgot to try with the ~ !
