### ISSUE TITLE
Incorrect timezone shown on hover display

### ISSUE THREAD

**Issue by slemire** [grafana/grafana#4734]
Version: 3.0.0-beta21459801392

Timezone on the X axis is correct (EST), time shown on the hover window is not (using UTC).

<img width="250" alt="screen shot 2016-04-16 at 1 21 27 pm" src="https://cloud.githubusercontent.com/assets/1174683/14582553/790a2c0c-03d6-11e6-87ed-b0e4b69c5907.png">

TImezone settings in the profile is set to 'Default'.

**Comment by torkelo** [comment]
and timezone on the dashboard?

**Comment by slemire** [comment]
The time range selector is also incorrect, it's using UTC instead of EST.

**Comment by torkelo** [comment]
what is your dashboard timezone? (dashboard settings / General tab), what is the organisation default timezone option set to?

**Comment by slemire** [comment]
It is set to default.

When I change it to local browser type the time is displayed correctly across the dashboard.

**Comment by torkelo** [comment]
so maybe the organisation timezone preference is set to UTC?
