### ISSUE TITLE
Feature Request : Install plugins directly from web interface at  /plugins 

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4735]
Grafana plugins web interface must have an option to add plugins that are available in local machine (similar to jenkins plugins installation) or user must be simply able to drop the plugin into /plugins space.

Today, installation is possible only via CLI and if the machine is not accessible to internet there is no way to install plugins.

<img width="1091" alt="screen shot 2016-04-16 at 2 30 24 pm" src="https://cloud.githubusercontent.com/assets/406777/14583733/cca57930-03df-11e6-864e-dce12818feaf.png">

**Comment by torkelo** [comment]
you can install plugins by just copying the files into the plugins dir

**Comment by deepujain** [comment]
how can i download them ?

**Comment by deepujain** [comment]
In addition to be original request, its good to have the ability to install plugins from a single interface (web is convenient) instead of switching to CLI.

**Comment by torkelo** [comment]
doing it from the web interface has some serious security implications (which is why we opted not do do that yet). Since grafana-server is not running as root (or is not recommended) it feels bad to install software, even frontend only components. 

>  how can i download them ?

Your server mush have some kind of network access? Just copy the plugin files into the plugins directory.

**Comment by stobias123** [comment]
+1 for this request. When running on docker or a cloud platform (for me it's Openshift) I have to manually go find my mounted volume and drop the files directly. This is a huge pain when the NFS export I'm mounting isn't directly available for me to drop files in.

**Comment by hemajv** [comment]
Will this feature be available anytime soon or is it still under consideration due to security issues?

**Comment by wbrowne** [comment]
This feature is implemented as of Grafana V8.0 and is documented [here](https://grafana.com/docs/grafana/latest/plugins/catalog/) 

Solved by #33869 and #33836
