### ISSUE TITLE
Missing traceID in logs of data-proxy-log logger

### ISSUE THREAD

**Issue by zhichli** [grafana/grafana#47365]
**What happened**:
For logs of a data proxy request, the `traceID` is only logged by `context` logger but NOT logged by `data-proxy-log` logger. This fact makes it hard to find correlated logs/traces and troubleshoot an end-to-end proxied request failure. Because sometimes the `data-proxy-log` logger contains critical error message for RCA in a distributed tracing pipeline. For example, suppose we started searching traces using a `traceID` that is grabbed from a service in front of Grafana, e.g. a reverse proxy, and the same traceID was injected into Grafana's tracing pipeline via context propagation of openTracing or openTelemetry, then we can only find logs with the same `traceID` logged by `context` logger and it just returned `Request Completed` as the log message when the upstream proxied request completed, which is not helpful for troubleshooting the data proxy error while the real error was logged by `data-proxy-log` logger.

**What you expected to happen**:
For a single end-to-end data proxy request, the `data-proxy-log` logger also logs the same `traceID` as the `context` logger, which would enable searching logs across loggers via a correlated `traceID`.

**How to reproduce it (as minimally and precisely as possible)**:
- [enable dataproxy logging (set as `true`)](https://grafana.com/docs/grafana/latest/administration/configuration/#logging) for the Grafana backend
- set up some `gdev dashboards` by following https://github.com/grafana/grafana/blob/main/contribute/developer-guide.md#add-data-sources 
- open a dashboard with a misconfigured data source like the one below (without configuring the endpoint of data source `gdev-opentsdb`)
![image](https://user-images.githubusercontent.com/57812115/161854658-377d2bd9-16cd-4501-b9a6-aed626aaef30.png)
- find console logs of Grafana and check the log statement for `data-proxy-log` logger which should have no `traceID` logged

**Anything else we need to know?**:

**Environment**:
- Grafana version: any version
- Data source type & version:
- OS Grafana is installed on: WSL
- User OS & Browser: Chrome
- Grafana plugins: OpenTSDB
- Others:

**Comment by zhichli** [comment]
@zserge @taleena for awareness

**Comment by zhichli** [comment]
- **PR fix proposal:** the following code snippet (to replace [line 118 in `ds_proxy.go`](https://github.com/grafana/grafana/blob/cb6124c92113040d723adfd51efe75b99755d354/pkg/api/pluginproxy/ds_proxy.go#L118)) is a candidate fix for this issue, which is basically extracting the `traceID` from the `context` and inject it into the `data-proxy-log` logger
![image](https://user-images.githubusercontent.com/57812115/161850294-dee58c0c-1e30-4074-a18d-af777f3daba4.png)
- **PR fix example result demo:** the end result of the fix would be that the same `traceID` is logged in both `data-proxy-log` logger and `context` logger for a single end-to-end request. This would enable engineers to find request error messages in both loggers by referring to a single `traceID`.
![image](https://user-images.githubusercontent.com/57812115/161851988-daf3853a-3fa5-425c-9fcc-18b963130caa.png)

**Comment by mellieA** [comment]
added labels to match #46411

**Comment by ying-jeanne** [comment]
PR https://github.com/grafana/grafana/pull/46411 is merged into main and branch 8.5, should be released at the end of the week.
