### ISSUE TITLE
Bad time grouped in bar mode

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4739]
Hi,
I have a really strange problem with grafana. I using grafana 3.0 beta2 and elasticSearch as source.

An example of doc in Elasticsearch:
> {
  "_index": "test",
  "_type": "logs",
  "_id": "151bbdac57d176bb769f5b875fa00753",
  "_score": 1,
  "_source": {
    "@timestamp": "2016-04-16T22:00:00Z",
    "hostname": "host_dev",
    "daily_0": 0,
    "daily_1": 0,
    "daily_2": 0,
    "daily_3": 0,
    "daily_4": 86400,
  },
  "fields": {
    "@timestamp": [
      1460844000000
    ]
  }

![aaaaaaaaaaaaaaaaaaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/15362041/14587467/0b6eec80-04b4-11e6-8bf7-0ca0f7e56da1.png)

In grafana when i select draw bar, the point is positioned at bad time (2016-04-16 02:00:00).
My browser is configured on GMT+2.
Logically, (22h)+ (GMT+2) = midnight.
my goal it's to show a bar begin at midnight for each day.

If i change on my query, interval to 20m, the point is correctly positioned at midnight.

**Comment by torkelo** [comment]
not sure if elasticsearch has a feature to align buckets with real days, maybe if you select time range in Grafana that starts at midnight.

**Comment by Azef1** [comment]
I could reproduce the bug on http://play.grafana.org on ElasticSearch Metrics:
- Change Interval of Date Histogram to 1d
- Enable Bars on Display  tab and disable "Lines"
- Change time range to "Last 7 days"

For me the result is:
![wtf](https://cloud.githubusercontent.com/assets/15362041/14588677/209b20b8-04cf-11e6-8d1f-97b265f2f24f.png)

When you can see, each bars doesn't start to midnight.
I think, Grafana should show the same result if timezone is UTC or "Local browser time" for Bars Mode. 
Do not start a day at midnight that doesn't make any sense.

**Comment by torkelo** [comment]
As I said elasticsearch don't automatically align group by time intervals,  sinice your grafana time range is last 7 days to now, it won't align, the time range is now-24h*7  

You can  try the time ranges this week so far, that should align  with midnight

**Comment by Azef1** [comment]
I'm sorry but the problem is the same with "this week so far" time range:
![captureaaaaaaaaaaa](https://cloud.githubusercontent.com/assets/15362041/14598831/6ee64a38-0554-11e6-9cca-2e892616c633.PNG)

Here the time range start to midnight and end to midnight:
![captureaa](https://cloud.githubusercontent.com/assets/15362041/14598807/44cd6092-0554-11e6-8905-9afba1c74cf3.PNG)

I have read [ElasticSearch DateHistorigram aggregation documentation](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/search-aggregations-bucket-datehistogram-aggregation.html), and they talk about `post_zone`, `pre_zone` ,

**Comment by torkelo** [comment]
yes, the elasticsearch query editor probably needs to add support to specify 
pre and post offset, think they are related to rounding the intervals, post_zone, and pre_zone only relate to time range not to date histogram intervals, but not sure.
