### ISSUE TITLE
[State Timeline] Selecting only one table wrongly displays states 

### ISSUE THREAD

**Issue by kaiosjfds** [grafana/grafana#47397]
**What happened**:
At least from Grafana 8.4.4, when selecting only one table from an InfluxDB source, the State Timeline plugin won't display all values. 
![Screenshot of the bug](https://user-images.githubusercontent.com/38870691/161984702-eec5a150-afab-4d5d-8b93-aecae101dbc9.png)
The states will have wrong ending time and will have big overlaps.
![First state overlapping the next states](https://user-images.githubusercontent.com/38870691/161987936-01ba63b4-8773-47ba-b2ae-76d1d5449cc0.png)
![Second state starting before the end of the last state](https://user-images.githubusercontent.com/38870691/161987809-faaf3241-e6af-4525-a8b7-fe993a8e29ef.png)

This bug only appears when we select one table, adding another one gives the expected result.
![Expected Result](https://user-images.githubusercontent.com/38870691/161984005-2f8c092a-da1e-4965-a1b5-f5b810a19b3a.png)
The table view gives the expected result.
![Table View](https://user-images.githubusercontent.com/38870691/161985121-4c8ef240-0b68-41aa-9151-6c970718a79a.png)

**How to reproduce it**:
The minimal Query for my data : 
```
RawSeries = from(bucket: "main")
  |> range(start: v.timeRangeStart)
  |> filter(fn: (r) => 
      r.resource == "dell-compute-2" or 
      r.resource == "dell-compute-1")
  |> map(fn: (r) => ({resource:r.resource, _time:r._time, _value:r.user}))
  |> yield()
```

**Anything else we need to know?**:
"Merge equal consecutive values" does not affect the result.
"Value Mapping", "Thresholds" and "Color Scheme" do not affect the result. 
Toggling "Showing Values" to "Always" will show more states, but not all of them

**Environment**:
- Grafana version: 8.4.5 (also tested on 8.4.4)
- Data source type & version: influxbDB 2.0.9
- OS Grafana is installed on: Debian 10
- User OS & Browser: Tested on Firefox 91.0.7 (esr) & Chromium 90.0.4430.212
- Grafana plugins: None

**Comment by dprokop** [comment]
@kaiosjfds do you mind sharing your raw panel data with us? This would help us investigate this issue a lot. You can export it as CSV using the Panel Inspect feature - please make sure transformations and field config is disabled when exporting.

**Comment by BGodding** [comment]
I think I am running into the same issue when using JSON API datasource. State tables with multiple show all states correctly, but single tables only show the first value for the entire duration. Query inspector shows all values are received as expected.

Environment:

Grafana version: 8.4.6
Data source type & version: JSON API 1.3.1
OS Grafana is installed on: macOS 12.3.1
User OS & Browser: macOS 12.3.1 & Chrome 100.0.4896.88

**Comment by BGodding** [comment]
Updating to Grafana version 8.5 has resolved this for me.

**Comment by kaiosjfds** [comment]
I still have the same issue after upgrading to 8.5.0

**Comment by kaiosjfds** [comment]
Adding time ordering fixed the issue, thank you. 

However I don't understand why it's only an issue when there is a single table. Does having two tables automatically sort by time ?

**Comment by zoltanbedi** [comment]
Hey @kaiosjfds,

I'm glad it fixed for you. You were right we only sort by time field when there are multiple frames. I've created a fix for it to try and sort when there is only one frame.
