### ISSUE TITLE
Distributed tracing via context propagation is broken after openTelemetry implementation

### ISSUE THREAD

**Issue by zhichli** [grafana/grafana#47408]
**What happened**:
Suppose there is a reverse proxy set up in front of self-hosted Grafana and the proxy injects a `uber-trace-id` header with a valid `uber-trace-id` value into proxies requests going to the Grafana, the Grafana tracing middleware failed to extract the trace id (tracing context) from the incoming request. This bug leads to that the context would create a brand new root span instead of keep using the trace id in the incoming request as the root trace id, in other words, the context propagation of distributed tracing is broken.

**What you expected to happen**:
Grafana tracing middleware should properly extract the trace id (trace context) from incoming requests and use it as a root trace id (trace context) so that users can search traces in the reverse proxy (or any other kind of services in front of Grafana) and in Grafana using the same propagated trace id for distributed tracing.

**How to reproduce it (as minimally and precisely as possible)**:
- enable tracing by either giving the address of [jaeger](https://grafana.com/docs/grafana/latest/administration/configuration/#address-1) or [opentelemetry jaeger](https://github.com/grafana/grafana/blob/38c842cf4ae13e9a83ded413095fc1fe28e26141/conf/defaults.ini#L972)
- send HTTP requests to Grafana e.g. using `curl` with a header `uber-trace-id` and a [valid `uber-trace-id` value](https://www.jaegertracing.io/docs/1.32/client-libraries/#value)
- for any context logs printed by Grafana, there would not be any `traceID` that matches the trace id in the `uber-trace-id` value of the incoming request

**Anything else we need to know?**:

**Environment**:
- Grafana version: versions after [8.4.0](https://github.com/grafana/grafana/releases/tag/v8.4.0) including this #42674
- Data source type & version:
- OS Grafana is installed on: WSL
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by zhichli** [comment]
@taleena @zserge for awareness

**Comment by zhichli** [comment]
This distributed tracing via context propagation worked before and it was broken since a couple of months ago. I'm not an expert in the tracing infra and middleware pipeline but I may have a couple of pointers on possible cause and fix.

**Possible root cause:** I tracked down the source code and PR history and found a possible root cause which is merged in main by this change #42674: the [line 54 in request_tracing.go](https://github.com/grafana/grafana/blob/49505b9a3bc284b1d18bcf5ea1ddf4aa19c6b547/pkg/middleware/request_tracing.go#L54) seems doing the context extraction but it actually uses an unset TextMapPropagator which failed to extract the trace context from the incoming request context. Prior to this change #42674, the openTracing extract call does the trick and the context propagation worked. The diff change is shown below. 
![image](https://user-images.githubusercontent.com/57812115/162032119-d3f1cb90-81e4-4bd5-9afd-209934ca1a16.png)

**Potential fix:** 
The TextMapPropagator of openTelemetry has to be explicitly set at initialization stage. Adding a line `otel.SetTextMapPropagator(jaegerpropagator.Jaeger{})` after [line 98 in opentelemetry_tracing.go](https://github.com/grafana/grafana/blob/b2f24e9d5b1c4e2f165607a4ffc33c31882f1f78/pkg/infra/tracing/opentelemetry_tracing.go#L98) might does the trick, which requires an external package ["go.opentelemetry.io/contrib/propagators/jaeger"]()
```
import {
	jaegerpropagator "go.opentelemetry.io/contrib/propagators/jaeger"
}
```
```
	if ots.enabled {
		otel.SetTracerProvider(tp) // line 98
		otel.SetTextMapPropagator(jaegerpropagator.Jaeger{}) // line 99
	}
```
The `Jaeger{}` propagator will extract `uber-trace-id` header value from the incoming request context.

Besides, if we want it to support extraction of W3C context (extract `traceparent` header to get trace Id), we may change the added line to `otel.SetTextMapPropagator(propagation.TraceContext{})` without requiring the additional package. But I believe we still need to support Jaeger tracing anyway while W3C support might require additional refactoring.

**Comment by taleena** [comment]
I've added the high prio as per feedback, if at all possible, please let us know when this might be addressed.

**Comment by idafurjes** [comment]
Hi @zhichli we are working on the fix, we will be adding configuration for w3c and jaeger text map propagation.

**Comment by taleena** [comment]
@idafurjes it seems that this issue is still happening, even with the merged PR. Do you know if there was any other recent work related to this?

**Comment by idafurjes** [comment]
@taleena can you give me more information about propagation being broken? As far as I knew it was working after the fix.

**Comment by taleena** [comment]
Here's the additional context I've got at the moment:

> I tried searching a TraceId(extracted from Grafana logs) in any other kind of services in front of Grafana, and this TraceId still can not be found. Looks like the Grafana tracing middleware failed to extract the trace id (tracing context) from the incoming request. And the context still create a brand new TraceId instead of keep using the TraceId in the incoming request as the root trace id. So the propagation of global distributed tracing still broken. My testing Grafana namespace version is 9.0.1.

**Comment by idafurjes** [comment]
is it possible that the issue you're describing is related to https://github.com/grafana/grafana/issues/50079

**Comment by taleena** [comment]
They've confirmed that seems very similar, so I'm following that one now. They've made mention that this would be their additional context/repro details for that new issue as well.
