### ISSUE TITLE
[Feature Req]: SingleStat panel, option to show series name 

### ISSUE THREAD

**Issue by fhelje** [grafana/grafana#4740]
I was playing around with the mostDeviant functionallity in graphite together with the SingleStats panel. Which work just great, but I lack the possibility to show the alias for the most deviant "node". So have I missed something or would this be a good thing to add to the SingleStats panel?

**Comment by torkelo** [comment]
yea, this option is missing. For queries like this (where you not sure about the series name returned, having an option to show the series name would be good).

**Comment by bergquist** [comment]
@fhelje go master branch! :)

**Comment by michaelmarziani** [comment]
This is awesome, and very close to one thing we're trying to achieve in Grafana. We have a Singlestat for the fullest disk in a cluster. It's great to see just the one fullest disk that may need attention, but when showing the value, we see 70%, for instance, but don't know which node it's on. Thanks to this feature, we can now select name, which shows the name, but then the value disappears along with the visualization.

Any chance there's a way we can show both the name and value at the same time, while visualizing the value?
