### ISSUE TITLE
Does grafana support arbitrary time range sum aggregation? 

### ISSUE THREAD

**Issue by StarWindMoonCloud** [grafana/grafana#4741]
E.g. I have qps metrics (query per second) qps.m1, then is that possible to aggregate in a different way, say total requests per day?

Grafana version: 2.6.0

**Comment by torkelo** [comment]
It all depends on your time series store and what types of queries it supports and how you store the metric. 

In your case you seem to have stored a rate, which makes getting totals over time tricky. It's better to store count's and aggregate the counts using `sum`, then you can get accurate totals (and calculate rates on demand by dividing the value). 

But grafana does not do any metrics processing/transformation at this point, it is all up to the data source you use and the types of queries it supports.

**Comment by StarWindMoonCloud** [comment]
Hi Torkelo,

I didn't quite get it, there's no difference between count and rate to me, since metrics are always sent periodically. 

Did you mean I have to sent daily another metrics instead?

**Comment by torkelo** [comment]
is the rate the same as the sum? you said it was query per second, is the metric stored every second? If not it is only a rate as you say and to get accurate totals is tricky. 

If you save it each 10s you can multiply it by 10 to get the total queries for each 10s interval, then use sum aggregation in the query

**Comment by StarWindMoonCloud** [comment]
It's stored every minutes.  The request is quite simple, say I wanna know the total count in one hour.
Did you mean aggregator against Metric or via "Down sample", I tried, it didn't work.

Is it some feature after Grafana version: 2.6.0

**Comment by torkelo** [comment]
Did you read the issue template when you created your issue? You removed the most important info from the new issue template, the data source you use :) 

As I said, this question depends on what your data source supports.

It all depends on your time series store and what types of queries it supports and how you store the metric. Sounds like you use OpenTSDB, not sure it has a "group by time" feature to aggregate totals over different time periods, most TSDB has this, not sure about OpenTSDB.
