### ISSUE TITLE
[Feature Request]: MiB/sec as a Unit

### ISSUE THREAD

**Issue by surendarchandra** [grafana/grafana#4742]
Version 3.0 b5/InfluxDb 0.12:
  The new units are awesome. Can we also support MiB/s (and KiB/sec, GiB/sec etc.). I can manually divide a byte value /1024*1024 to get MiB. However, when it goes over 1000 MiB, it is terms GB. It would be great if we can natively support multiples of 1024. Thanks

**Comment by bergquist** [comment]
can be found in the data rate category.
