### ISSUE TITLE
log panel or log explore with Elasticsearch data cannot show custom fields such as "logger name"

### ISSUE THREAD

**Issue by fzyzcjy** [grafana/grafana#47428]
**What happened**:
Hi thanks for the lib! When using log panel or log explore with Elasticsearch data, it cannot show custom fields such as "logger name". I have tried to show the labels, but it says there are none. I have also tried to see whether I can specify some extra fields, without any solutions.

![image](https://user-images.githubusercontent.com/5236035/162180389-70dc8469-0af5-4f05-be97-cf57fab9befc.png)
![image](https://user-images.githubusercontent.com/5236035/162180493-37a43c7a-f8c7-4e60-9d22-564ba589813a.png)

**What you expected to happen**:
see above

**How to reproduce it (as minimally and precisely as possible)**:
just use grafana to visualize elasticsearch logs

**Anything else we need to know?**:
none

**Environment**:
- Grafana version:latest
- Data source type & version: es latest
- OS Grafana is installed on:linux
- User OS & Browser:chrome
- Grafana plugins:es
- Others:none

**Comment by mellieA** [comment]
@fzyzcjy it's hard to see from the screenshots included what would be expected to show in the logs panel for this case. This looks more like a question about how to use the logs panel for elasticsearch logs. The best place to get help with that is our community at commmunity.grafana.com

Some information you'll want to include in your post: 
* what is the mapping for your log index data in elasticsearch?
* which fields have you configured in your elasticsearch datasource for this log index?

**Comment by fzyzcjy** [comment]
> it's hard to see from the screenshots included what would be expected to show in the logs panel for this case

Just show: (1) timestamp (2) *logger name* (3) log message

> what is the mapping for your log index data in elasticsearch?

@timestamp, logger.level, message, logger.name, some.other.fields, etc

> which fields have you configured in your elasticsearch datasource for this log index?

log level is configured to logger.level, and message is configured to message.
