### ISSUE TITLE
Dimension Operator not supporting ne and startsWith for Azure Monitor

### ISSUE THREAD

**Issue by r1ckr** [grafana/grafana#47427]
## Issue:
When adding a new dimension, we can't select the `ne` operator on the UI as shown below:

![image](https://user-images.githubusercontent.com/1575507/162176512-7077268d-0d6d-48fc-9a6a-76a605ad1e79.png)

But we can add it in the json model like below (work around)

![image](https://user-images.githubusercontent.com/1575507/162178424-88c810d5-5175-4916-b306-111b3e303f50.png)

## Expectation:
What we expect is to be able to select at least the `ne` operator in the UI, optimally to select the `startsWith` operator too.

## To reproduce:
Use Azure Monitor with any metric and try to select another operator for the dimension as explained before.

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: Azure Monitor (Core)
- OS Grafana is installed on: AWS
- User OS & Browser: macOS, Chrome
- Grafana plugins: Azure Monitor

**Comment by sunker** [comment]
Thanks for reporting this @r1ckr! I don't believe specifying the operator in the UI ever was supported so, I'll relabel this a feature request. Anyway, this would be a nice feature to have so I'll put it in our backlog and hopefully we can look into this sometime soon.

**Comment by r1ckr** [comment]
Thanks a lot @sunker 🙌

**Comment by aangelisc** [comment]
Hi @r1ckr,

Support for this has now been added in #48077 and will be available in the next release of Grafana 8.5 😊 Hope this helps!
