### ISSUE TITLE
Docs: Clarify server admin role

### ISSUE THREAD

**Issue by sakjur** [grafana/grafana#47422]
Permissions documentation could be clearer that server admin does not imply org admin here:

https://github.com/grafana/grafana/blob/0cff2d5980c99a0a009c7215a48e57176510d8ae/docs/sources/administration/manage-users-and-permissions/about-users-and-permissions.md?plain=1#L19-L31

**Comment by vtorosyan** [comment]
@chri2547 marking this for you as this is a good point to consider when thinking about the differences of Admin, Editor, Viewer and the rest of the RBAC roles, next to the Grafana Server Admin.
