### ISSUE TITLE
[Feature Request]: support InfluxDB authorization model

### ISSUE THREAD

**Issue by surendarchandra** [grafana/grafana#4743]
Grafana 3.0 b5/Influxdb 0.12.

InfluxDb has a wierd authorization model in that access rights of Read/Write/All can be granted to individual users. However, 'use database' invokes 'show database' which is only available to admins. The preferred mechanism is to directly call with the database that I have access rather then do a 'use database'. I think Grafana uses 'use database' functionality because I could not access anything when all the access rights for the database was granted to a non-admin user. Thanks

**Comment by bergquist** [comment]
Im sorry but I think something else is broken.

Grafana sends the db/user/password that is configured in the config page for every request. Grafana does not list the databases in influxdb in any way.
