### ISSUE TITLE
Unified alerting migrations not working.  No unified alerts and also legacy alerts are removed.

### ISSUE THREAD

**Issue by danfinn** [grafana/grafana#47455]
**What happened**:

Upgraded from 8.0.6 to 8.4.5 (also tried 8.3.7) to try out unified alerting 

**What you expected to happen**:

According to the docs our legacy alerts should be migrated to unified alerts on any version newer than 8.3

I've tried upgrading our grafana deployment to both 8.3.7 and 8.4.5 and I get the same results with either.  There are no unified alerts and the legacy style alerts that we had previously are no longer there.   I also made sure to add the following to our config:

```
[unified_alerting]
enabled = true
```

I see some logs about migrations related to alerts running however there are no errors.  This line seemed particularly interesting:
```
logger=migrator t=2022-04-05T18:01:36.59+0000 lvl=info msg="alerts found to migrate" alerts=0
```

When attempting to access the alert rules in the UI this is logged:
```
logger=context t=2022-04-05T18:23:35.37+0000 lvl=eror msg="no rule groups found\n" error="no rule groups found\n" remote_addr=[172.18.251.97](https://172.18.251.97/)

logger=context t=2022-04-05T18:23:35.37+0000 lvl=info msg="Request Completed" method=GET path=/api/ruler/15/api/v1/rules status=404 remote_addr=[172.18.251.97](https://172.18.251.97/) time_ms=77 size=36 referer=[https://grafana.dev-mgmt-eastus.domain.com/alerting/list](https://grafana.dev-mgmt-eastus.bentleyhosted.com/alerting/list)
```

For datasources we are using primarily elasticsearch with some loki and azure.  

We are running grafana on k8s.  We load our config and dashboards from git.  I'm not sure that this should matter but wanted to include it.  Could it be possible that the unified alert migration only works if you have previous alerts in the database and it doesn't work on new dashboards that get loaded with legacy style alerts?

**Comment by zuchka** [comment]
- Please list ALL configuration options related to alerting. You can find these in the `Alerting` and `Unified Alerting` sections of Grafana's config file. If you are now using or have previously used the beta version of `ngalert` (released with Grafana 8), please note that too.
  - you can use [this table](https://github.com/grafana/grafana/pull/42200#issue-1062269188) to better understand how configuration options can interact with each other

**Comment by danfinn** [comment]
All I have in the config related to alerting is:

```
    [unified_alerting]
    enabled = true
    [alerting]
    enabled = false
```

We have never used anything related to ngalert.

**Comment by MaggotMouth** [comment]
@danfinn I'm having the same issues and seeing the same log entry for `lvl=info msg="alerts found to migrate" alerts=0`

I see you're also running k8s - do you have persistence for your `/var/lib/grafana` dir?

I did not have any persistence (not sure if we want it, due to also loading dashboards via files), but once I added it, my log entry is now `lvl=info msg="alerts found to migrate" logger=migrator alerts=20` and I can see the migrated alerts in the GUI.

For my use case, I'm still using the default sqllite database, single replica for grafana.  If you're running multiple replicas, maybe worth looking into read-write-many storage or postgres instead of sqllite.

**Comment by MaggotMouth** [comment]
I'm not familiar with the Grafana project enough to know for sure, but I assume that the [migrations](https://github.com/grafana/grafana/blob/398f2b3d18ed69a6bcd0145b5024b8bd454889fd/pkg/services/sqlstore/migrations/ualert/dash_alert.go#L45-L61) are happening before the dashboards are loaded, thus the empty alerts table.

**Comment by danfinn** [comment]
We are not using persistence for the same reason you mentioned, we load everything in when the pod starts from git via files.  We are also only running a single grafana instance which should be fine for us for the foreseeable future.

I will test out enable persistence and report back.  Thanks.

**Comment by danfinn** [comment]
OK, that did fix this issue.  Adding persistent storage for /var/lib/grafana does get unified alert migration working.  Thanks @MaggotMouth.

This however made me realize that it sort of breaks our ability to manage our alerts using gitops.  Currently if we make changes to our dashboards or alerts we export that to a JSON file, save it in git and we then have a simple workflow to continually pull those git changes via an init container.

Switching to unified alerts we lose the ability to do that.  If we modify alerts via the UI we have no way to keep that in sync with git.  There is no way to export them.

I know that there is an API to read and load these but that means writing something around that.  Does anyone know if there will be any plans to somehow export and load unified alerts from a file?

**Comment by zuchka** [comment]
@danfinn If I understand correctly, then yes. provisioning alert rules is on the roadmap. These two threads are probably the most up to date:

https://github.com/grafana/grafana/discussions/39510#discussioncomment-1390773

https://github.com/grafana/terraform-provider-grafana/issues/57#issuecomment-1020194152
