### ISSUE TITLE
Dashboard Export: Dashboards with library panels don't correctly export/import

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#47460]
**What happened**:
There are several issues at present with exporting and importing a dashboard containing library panels.
While the library panels present in the dashboard _are_ correctly extracted and placed in the `__elements` property of the exported JSON, the full panel model is also still present in `panels`, when those corresponding to library panels should just have the library panel's id/name.
As well as this, when the dashboard is imported, for some reason library panels are incorrectly assigned a `type` param of their UID + name, so something is going wrong there.

**What you expected to happen**:
Dashboards containing library panels to correctly export and import.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create some library panels
2. Create a dashboard and add those library panels to it
3. Export for external sharing
4. Inspect returned JSON and notice redundant library panel info
5. Import JSON
6. Notice error messages
7. Notice incorrect type on library panels in dashboard json

**Comment by joshhunt** [comment]
> As well as this, when the dashboard is imported, for some reason library panel's are incorrectly assigned a type param of their UID + name, so something is going wrong there.

When loading library panels for a dashboard, the backend will set a bunch of properties (including this weird type) if the library panel does not appear in the list of library panels connected to that specific dashboard https://github.com/grafana/grafana/blob/43358c72487acb359b657b1acbd6b179434f090c/pkg/services/librarypanels/librarypanels.go/#L82-L92

It appears that when you import a dashboard (at least from externally shared JSON), the library panel connection is not created for the dashboard. I'm not sure whether this is a problem with the exported JSON, or how we process it when importing it.

**Comment by joshhunt** [comment]
Also while investigating this (doing a bunch of imports and exports), I've somehow gotten into a state where I have an orphaned library panel connection which prevents me from deleting the library panel:

![image](https://user-images.githubusercontent.com/46142/169029327-c68150dd-1263-4cd5-aff0-34e75b53c5fa.png)


![image](https://user-images.githubusercontent.com/46142/169029667-b22e6647-f449-43c3-8b16-5d0e9254b3e1.png)

What's interesting is the page makes a call to list all the connections, which returns an empty array

![image](https://user-images.githubusercontent.com/46142/169029900-d655ff8f-f63d-4374-bed5-38ea75cd9468.png)

Indeed, in the database I can see the orphaned connection 

![image](https://user-images.githubusercontent.com/46142/169029988-2dc85c5e-0515-48ad-bd27-15fe048e22a9.png)

I don't yet have exact steps to reproduce this, so haven't made a separate issue for it yet.
