### ISSUE TITLE
Prometheus datasource parses exemplar values as heatmap, discarding remainder of fields in frame

### ISSUE THREAD

**Issue by srclosson** [grafana/grafana#47462]
**What happened**: When requesting a heatmap from prometheus, along with exemplars, the heatmap is calculated first. This goes through all numeric fields in frames, and copies them over. 

In the case of exemplars, this causes the frame to be split up from the rest of it's metadata, including the trace id.

**What you expected to happen**:

That exemplars would be returned in a different frame with a `refID` of the query in a separate frame with other supporting metadata including the traceid as fields.

**How to reproduce it (as minimally and precisely as possible)**:

Query as follows:
![image](https://user-images.githubusercontent.com/7053010/162248735-7c21df5c-858b-4d56-a7ab-077898c4df60.png)

**Environment**:
- Grafana version: latest main
- Data source type & version: Prometheus
- OS Grafana is installed on: Linux (ubuntu jammy)
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by leeoniya** [comment]
fixed by #47463
