### ISSUE TITLE
Azure Monitor: New Metrics Query Editor UI improvements

### ISSUE THREAD

**Issue by kevinwcyu** [grafana/grafana#47475]
The new Azure Monitor Query Editor implemented in https://github.com/grafana/grafana/pull/47164 uses the `ResourceField` component that was taken from the Azure Logs Query Editor.

When a resource is picked, the label applied to the resource picker might be too long and overflow past the edge of the query editor. The width of the Resource Picker should fill the space of the query editor.

The resource picker can display the resource name only without the subscription, and resource group in the smallest view. See the last screenshot for how this would look.

![161946209-b1490992-7584-4991-ab14-6f6cdc21e297](https://user-images.githubusercontent.com/19530599/162278901-51b7f813-03f9-4956-9d4e-5620eef9c483.png)
![161946918-8cbc7c36-c5f1-48c8-9973-4e4f8dc3fdfd](https://user-images.githubusercontent.com/19530599/162278906-36e91a81-122b-41fd-9408-08b36965cdde.png)

There is also a gap between certain groups of selectors (e.g. Metric namespace and Metric have a wider gap) The spacing between the selectors should be equal.

![161947557-f81d2d06-6169-4a80-83bc-9628fbaaa5c2](https://user-images.githubusercontent.com/19530599/162278911-5314e013-b3fb-4a44-8a4e-59a720da1d34.png)

**Comment by asimpson** [comment]
A possible related issue is that the editor grows too wide for the browser viewport and introduces a horizontal scrollbar after a log resource with a long name (e.g. `GithubTestDataVM_OsDisk_1_a6f3772d5ace448c8569ac1987677843`)  is picked.

![image](https://user-images.githubusercontent.com/1048831/165369583-b9421672-61d1-4798-a62a-f0a12bb384ae.png)
