### ISSUE TITLE
[Feature Request] Convert time unit to date and time in singlestat panel

### ISSUE THREAD

**Issue by jaegr** [grafana/grafana#4747]
It would be nice if you could convert time units in singlestat panels into a date and time. For example, if you have a series which records uptime in seconds, you could convert the boot time to "2016-03-18 21:03:19" instead of "3.9 week (ago)".

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/5379

**Comment by bergquist** [comment]
Reopening this since I reverted previous PR

**Comment by torkelo** [comment]
how would this work? What is the metric value unit in? epoch?

**Comment by torkelo** [comment]
dont think this makes much sense, will do this instead https://github.com/grafana/grafana/issues/4747

**Comment by bergquist** [comment]
@torkelo You linked to this ticket :)

**Comment by torkelo** [comment]
I meant this https://github.com/grafana/grafana/issues/2971
