### ISSUE TITLE
Unified alert query duplication does not set  correct timerange to the new query

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#47484]
**What happened**:
query time range was reset to default range which is last 10 min

**What you expected to happen**:
The duplicated query will have the same time range as the source query

**How to reproduce it (as minimally and precisely as possible)**:
* create  a unified  alert  with prometheus/sqlserver datasource. 
*  set time range to last 5 min
* Then click the duplicate query button

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: Sql Server & Prometheus 
- OS Grafana is installed on: Windows server 2019
- User OS & Browser: 100.0.4896.75 (Official Build) (64-bit)
- Grafana plugins: 
- Others:

**Comment by armandgrillet** [comment]
Still happening in 9.1:

<img width="1497" alt="PS 2022-08-19 à 18 29 58" src="https://user-images.githubusercontent.com/2117580/185665033-2734a3f0-d9d1-43ae-8271-10e1654a5977.png">
