### ISSUE TITLE
[Bug] Unable to select color in "Series specific overrides" (3.0.0-pre)

### ISSUE THREAD

**Issue by fillest** [grafana/grafana#4749]
I edit a graph, Display -> Series specific overrides -> add an option group -> + -> color -> click on "change" -- color picker doesn't appear.
Alias/regex selector is correct -- other options do work (e.g. line fill, stack, z-index).
I do not see any errors in devtools console when it happens.
In stable 2.6 color picker works.
Is there a temporary workaround? I would like not to downgrade back..

* browsers: firefox 45 windows, chrome 50, firefox linux
* Grafana version: 3.0.0-pre, commit: v2.6.0-1629-gd3a4b7a, build date: 2016-03-31 07:27:08
* Grafana installed from `deb https://packagecloud.io/grafana/testing/debian/ wheezy main`
* datasource: influxdb 0.12.1

**Comment by fillest** [comment]
Damn, it's a duplicate for #4620 Sorry!
Still -- I guess no workaround except manually patching js -- are there any rough estimates when the next update with these fixes will be released (e.g. weeks, months)? Thanks!

**Comment by torkelo** [comment]
there has been 5 beta releases since pre1, and builds are published multiple times per day here, 
http://grafana.org/download/builds.html

Released stable/beta builds
http://grafana.org/download/builds.html

**Comment by fillest** [comment]
Ooh, cool, thanks.
They don't get to deb repository? I did sudo apt-get update+upgrade but I don't see grafana package in apt output.

**Comment by torkelo** [comment]
yes, they are, but there was an issue with packagecloud / or apt that sorted pre > beta.  lesson for next time, so you have to force the upgrade

**Comment by fillest** [comment]
Oh. OK, thanks!

**Comment by fillest** [comment]
Yep, `sudo apt-get install grafana=3.0.0-beta51460725904` worked for me
