### ISSUE TITLE
[Question] Is it possible to select multiple metrics ?

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4751]
Hi, 

For example on this graph [http://play.grafana.org/dashboard/db/big-dashboard?panelId=14&fullscreen&edit](http://play.grafana.org/dashboard/db/big-dashboard?panelId=14&fullscreen&edit)
I would like to know if it's possible to show web_server_01 AND webs_server_03. It's to compare series.

Currently, it's possible to show ONE or ALL series ?

**Comment by bergquist** [comment]
@Azef1 Grafana don't support time series manipulation. That's up to the time series database so it depends on which database your using. 

In graphite you can use sumSeries

**Comment by torkelo** [comment]
In graphite you can use function like sumSeries diffSeries, asPercent   you can nest queries and combine these functions
