### ISSUE TITLE
[Grafana 8.4.4] After grafana upgrade Alertmanager datasource started behaving strange. One time displaying alarm annotation next time labels

### ISSUE THREAD

**Issue by tahchiev** [grafana/grafana#47518]
After upgrade from 7.5.0 to 8.4.4 alert manager data source (camptocamp-prometheus-alertmanager-datasource) started to behave  differently. It used to show only alarm labels as a table but now started rotating in time showing alarm labels or annotations. I cannot catch why and at what interval or how to control it. 
Labels:
![image](https://user-images.githubusercontent.com/103194805/162448707-2c50ad9e-9cea-4369-8e5c-71e536fa5123.png)

Annotations:
![image](https://user-images.githubusercontent.com/103194805/162448619-253e16ce-c230-471d-af26-d4d6520d9266.png)

 Any ideas?or recommendations?

**Comment by zuchka** [comment]
Thanks for creating this issue, @tahchiev 

This looks like a third-party datasource:

https://github.com/camptocamp/grafana-prometheus-alertmanager-datasource

Unless this issue can be replicated using grafana products, it might be best to make an issue in that repo.

In the meantime, here is a useful table that explains how alert migration work:

  - you can use [this table](https://github.com/grafana/grafana/pull/42200#issue-1062269188) to better understand how configuration options can interact with each other
