### ISSUE TITLE
[Feature Request] Exact Count of documents using Elasticsearch

### ISSUE THREAD

**Issue by DanielWebster** [grafana/grafana#4754]
I am currently using grafana v3.0b5 with Elasticsearch 2.3.1

I am looking to get an exact count of the documents in my TSDB using the single stat metric. The problem is that it is downsampling and not returning the correct count of documents.  When i try to remove the group by clause, the query fails.

Is there a way to get the exact count currently? Or is this something that could be added?

**Comment by torkelo** [comment]
you can change the date histogram interval to 1year (1y), and then set the panel time range to 1year, should give to the total documents for one 1
