### ISSUE TITLE
Alerting: clarify that no matchers on notification policies match all alert instances

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#47553]
**What happened**:

If a notification policy is created without any matchers (such as the root policy) the default behavior is to match _all_ alert instances.

This is the intended behavior but does allow users to create notification policies that will catch all alert instances but not send them to any contact point.

**What you expected to happen**:

We should improve the inline documentation to clarify the behavior of notification policies with no matchers.

**Comment by joeblubaugh** [comment]
@gillesdemey don't make any changes here. I already have a branch I can make a PR from.
