### ISSUE TITLE
"All" template option improperly expanded

### ISSUE THREAD

**Issue by r0bj** [grafana/grafana#4755]
grafana version: 3.0.0-beta51460725904

I added template "disk":
Data source: influxdb
Query: SHOW TAG VALUES FROM "diskio" WITH KEY = "name" WHERE host =~ /^$server$/
Regex: /^sd\w$/
Include All option: check

Preview of values: All sda sdb sdc
<img width="746" alt="screen shot 2016-04-18 at 21 54 25" src="https://cloud.githubusercontent.com/assets/1297747/14617849/2bdaaf16-05b0-11e6-8e2f-1795a48cf7a7.png">
So I have three disks and "All" option, all ok!

I've created graph:
FROM default diskio WHERE host=~/^$server$/ AND dc=~/^$dc$/ AND name=~/^$disk$/
https://gist.github.com/r0bj/c3a7245ff56604447e787c132122f4be
<img width="895" alt="screen shot 2016-04-18 at 21 55 43" src="https://cloud.githubusercontent.com/assets/1297747/14617908/68368660-05b0-11e6-9493-b9d9e6683d9e.png">

When I use specific disk as template variable everything is ok. But when I use "All" as template variable I got:
<img width="633" alt="screen shot 2016-04-18 at 21 57 08" src="https://cloud.githubusercontent.com/assets/1297747/14617930/8a702934-05b0-11e6-977d-c55dae16e2a1.png">

Instead of having only three disk: sda, sdb, sdc I got also some partitions, eg. sda1, sda2, etc.

**Comment by torkelo** [comment]
fixed :)
