### ISSUE TITLE
[Feature Request] single stat panel with values for Prefix and Postfix 

### ISSUE THREAD

**Issue by hwinkel** [grafana/grafana#4756]
grafana 3.0-beta3, influx 0.12

It is possible to select Values for the Prefix and Postfix in the single Stat value panel.

i.e.  

Prefix: max of last 24h with 24h timeshift (max. day before)
Value: current
Postfix: max of last 24 current day

**Comment by torkelo** [comment]
no, singlestat is for a single stat :)

**Comment by hwinkel** [comment]
but would give you what is close to #233 and depends roughly how you define a stat.  anyway with panel plugins a trend stat is not far away.
