### ISSUE TITLE
InfluxDB: Remove Influx browser/direct access mode

### ISSUE THREAD

**Issue by meanmina** [grafana/grafana#47570]
For Grafana 9.0 we should remove browser/direct access mode. This includes:
- [ ] remove the option to select browser mode from FE
- [ ] remove unutilised code for browser mode

**Comment by evandandrea** [comment]
- Beto has questions for Joey, but can redirect those to other former team members as we see fit.
- We affirm that this doesn't need to have happened by 9.0, which already released. Same for 9.1.
- Covered on deprecation plan.
- Seeing other areas that can be affected by this change. Will confirm with Joey that there are plans to address.
- Need to investigate whether documentation will be affected.
- Beto to add a document that explains why we decided to remove direct mode.
- Planning to start coding this week.
