### ISSUE TITLE
[Feature Request] Embed an entire read-only dashboard as iframe

### ISSUE THREAD

**Issue by yee379** [grafana/grafana#4757]
I'm using 3.0.0beta5 and i would like to embed the entire templated dashboard into another webpage.

i can easily do this just by pointing the `iframe src` to the URL of the grafana dashboard; however, i would like the dashboard dropdown to be removed, along with all the sharing, settings etc icons. as well as the 'add row' and 'edit' features.

i would, however, still like anonymous user accessing grafana directly to have write access to all dashboards.

**Comment by bergquist** [comment]
Iframe embedding for dashboard is not supported. But panels can be iframe embeded by clicking the panel header -> share -> embed 

All anonymous users can only be mapped to one role http://docs.grafana.org/installation/configuration/#authanonymous

**Comment by yee379** [comment]
thanks @bergquist, i would like to request the ability to embed read-only entire dashboards as a feature. i think it would be very useful for enabling things like the shared cursor and shared zoom across multiple graphs that embedding individual graphs could not support.

**Comment by ketul917** [comment]
I agree, Embedded read-only dashboard as iframe would be very helpful.

**Comment by jmls** [comment]
did this ever get done ?

**Comment by darasion** [comment]
yes, need embed entire dashboard, not only a panel.

**Comment by byakuinss** [comment]
+1. Embedded read-only dashboard is a big plus!

**Comment by xiuxiu** [comment]
+1 need embeded dashboard.

**Comment by beaver71** [comment]
+1 Really useful to embed entire dashboard, removing dashboard dropdown

**Comment by torkelo** [comment]
add &kiosk to url to remove dashboard header / dashboard picker, will remove dashboard time range as well.

**Comment by slucase** [comment]
+1

**Comment by rogerioaf** [comment]
+1

**Comment by hadigoh** [comment]
> add &kiosk to url to remove dashboard header / dashboard picker, will remove dashboard time range as well.

But this way, people can hit Escape and it will show the full dashboard

**Comment by pemartini** [comment]
Any updates on this?

**Comment by HeverMarc** [comment]
I'm using Style="pointer-events : none" for while until some update to fix it.

**Comment by ctaity** [comment]
> I'm using Style="pointer-events : none" for while until some update to fix it.

Where i can put this?

**Comment by HeverMarc** [comment]
Hi @ctaity, in the tag "ifram": 
<iframe name="myIframe" id="myIframe" style="width: 100%; height: 100%; position: fixed; z-index: 1;pointer-events : auto;" runat="server"></iframe>
