### ISSUE TITLE
Data Source Plugin Fetch is not returning stream

### ISSUE THREAD

**Issue by junixzh** [grafana/grafana#47587]
**What happened**:
I am building a datasource plugin that should fetch from a streaming endpoint that returns results as nd-jsonstream. 

The call returns an rx-js Observable which should process the results as a stream via pipe; however, the results short circuit any streaming and it's fetching all the results as a single result.
```
        getBackendSrv()
          .fetch<any>({
            url: `${this.url}/query`,
            method: "POST",
            headers: {
              "Access-Control-Allow-Origin": "*",
              Accept: "application/x-ndjson",
            },
            data: {
            },
          })
          .pipe(
            map((resp: any) => {
              const reader = ndjsonStream(resp.data).getReader();
              let read: any;
              reader.read().then(
                (read = (result: any) => {
                  if (result.done) {
                    return;
                  }
                  reader.read().then(read);
                })
              );
              return;
            })
          )
```

```
response
"{\"item\":{\"isAggregateQuery\":false,\"columns\":[]},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",\"itemType\":\"metadata\"}
{\"item\":{\"id\":\"2711447046973064575\",\"schema\":\"aws_cloudtrail\",\"timestamp\":1602102154000,\"data\":{}},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",\"itemType\":\"record\"}
{\"item\":{\"id\":\"7141534161798723355\",\"schema\":\"aws_cloudtrail\",\"timestamp\":1602102154000,\"data\":{}},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",\"itemType\":\"record\"}
{\"item\":{\"id\":\"4783144213480576720\",\"schema\":\"aws_cloudtrail\",\"timestamp\":1602102153000,\"data\":{}},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",\"itemType\":\"record\"}
{\"item\":{\"id\":\"10059140975309186284\",\"schema\":\"aws_cloudtrail\",\"timestamp\":1602102152000,\"data\":{}},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",\"itemType\":\"record\"}
{\"item\":{\"id\":\"15215104293767086553\",\"schema\":\"aws_cloudtrail\",\"timestamp\":1602102151000,\"data\":{}},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",…"

```

**What you expected to happen**:
```
response 
{\"item\":{\"isAggregateQuery\":false,\"columns\":[]},\"queryId\":\"znEfjkXDE3XYhNwVn2e5gGQ\",\"status\":\"processing\",\"itemType\":\"metadata\"}
```
Each item should be processed individually inside the Observable pipe.

**How to reproduce it (as minimally and precisely as possible)**:
Make a fetch call with `getBackendSrv.fetch().pipe(...)` on a streaming endpoint and the results are not processed as a stream but rather as a monolith. 

**Anything else we need to know?**:
It seems that the documentation for using fetch on a streaming endpoint is actually meant for polling: https://grafana.com/docs/grafana/latest/developers/plugins/build-a-streaming-data-source-plugin/

**Environment**:
- Grafana version: 8.0.0
- Data source type & version: Datasource Plugin & 8.4.4
- OS Grafana is installed on: Mac
- User OS & Browser: Mac v 10.15.4 && Firefox
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Is your server returning response with [Chunked transfer encoding](https://en.wikipedia.org/wiki/Chunked_transfer_encoding), e.g. a json response in each chunk? If not, I wont expect you to be able to get it to work using fetch and ndjson even outside of Grafana with your server. 

Please provide more information:
- Can you please include details of the response you get from Grafana datasource proxy call/your server, you can use Developer Tools of your browser and extract the information from the network tab normally. 
- What's the implementation of `ndjsonStream`

**Comment by dassana-junix** [comment]
Response Body
```
{
    "item": {
        "isAggregateQuery": true,
        "columns": [
            {
                "name": "name",
                "type": "string"
            },
            {
                "name": "query",
                "type": "string"
            },
            {
                "name": "rule",
                "type": "string"
            },
            {
                "name": "severity",
                "type": "string"
            }
        ]
    },
    "queryId": "...",
    "status": "processing",
    "itemType": "metadata"
}
{
    "item": {
        "data": {
            "name": "AWS Security Group Open to the World",
            "query": "...",
            "rule": "a > 0",
            "severity": "high"
        }
    },
    "queryId": "...",
    "status": "processing",
    "itemType": "record"
}
```

Response Headers
```
[{"key":"Transfer-Encoding","value":"chunked","description":"Specifying the form of encoding used to transfer the entity to the user.","enabled":true,"disableEdit":true,"info":"Specifying the form of encoding used to transfer the entity to the user."},{"key":"Content-Type","value":"application/x-ndjson","description":"Indicates the resource's media type.","enabled":true,"disableEdit":true,"info":"Indicates the resource's media type."},{"key":"date","value":"Tue, 12 Apr 2022 22:45:28 GMT","description":"A general header containing the date and time the message was sent.","enabled":true,"disableEdit":true,"info":"A general header containing the date and time the message was sent."},{"key":"Via","value":"1.1 google","description":"Added by proxies and used to track message forwards, avoid request loops and identify protocol capabilities of senders.","enabled":true,"disableEdit":true,"info":"Added by proxies and used to track message forwards, avoid request loops and identify protocol capabilities of senders."}]
```

Implementation of ndjsonStream:
https://www.npmjs.com/package/can-ndjson-stream

We have an equivalent frontend team able to perform streaming calls on the same endpoint, but similar behavior has not been exhibited in Grafana backendSrv.fetch

**Comment by marefr** [comment]
Thanks. Looks like Grafana doesn't support your use case then, but I'm no expert client side. Would need to ask someone else for help understanding this better.

Grafana's fetch implementation is [here](https://github.com/grafana/grafana/blob/4fbc481d1f7df27939647f583093aabf5e5d4fbb/public/app/core/services/backend_srv.ts#L82) in case you would like to dig into it yourself.

**Comment by tolzhabayev** [comment]
closing as stale
