### ISSUE TITLE
Docs: Clarify use of template variables for Mimir & Loki alerting

### ISSUE THREAD

**Issue by ghost** [grafana/grafana#47583]
There is no indication on this page that the recommended solution to utilizing the new unified alerting requires or recommends using both Cortex and Loki in order to use template variables and no documentation exists as to what you expect users to do. This frequently cited thread https://community.grafana.com/t/template-variables-are-not-supported-in-alert-queries-while-setting-up-alert/2514/23 but there is no documentation anywhere on how to accomplish the same functionality in Cortex/Loki that I can find. I we want to receive alerts of metric data from a variable name like  {{ $labels.instance }} and since that no longer works in classic what is the new method? Thanks!

**Comment by osg-grafana** [comment]
Because the meaning of `old-new` in the file name (or content in general) changes the minute a release is cut, consider renaming this to something else that will be more future proof.

**Comment by achatterjee-grafana** [comment]
We have removed the particular topic from our documentation, in preparation for the upcoming release. 

It will be good to document how we can achieve the ask. @armandgrillet and @gotjosh can you help?

**Comment by achatterjee-grafana** [comment]
@armandgrillet, can you help us with updating the documentation for 9.0. TY

**Comment by armandgrillet** [comment]
This is part of https://github.com/grafana/grafana/issues/48943, @santihernandezc can help with this.

**Comment by armandgrillet** [comment]
The definition is unclear and the user is gone thus we will pause this for now.
