### ISSUE TITLE
Annotation with timeEnd in future does not end at that time

### ISSUE THREAD

**Issue by joe-balough** [grafana/grafana#47589]
**What happened**:
I used the annotation API to create an annotation with the timeEnd set to a time in the future (like 5 minutes). This annotation shows up on my dashboard immediately and looks nice, but after 5 minutes have passed, the annotation does not end as I expect. In fact, the annotation does not appear to ever end.
![image](https://user-images.githubusercontent.com/64433873/162814788-bd0bf018-aa0a-4de8-a72b-2c15be3a230f.png)
This example was supposed to end one minute after it started.

**What you expected to happen**:

The annotation to end at the specified timeEnd, even though it was in the future.

**How to reproduce it (as minimally and precisely as possible)**:

```
# Provide relevant values for $GRAFANA_AUTH and $tags
now=$(date +%s000)
later=$((now+3600000)) # One minute
curl -X POST -H "Accept: application/json" \
    -H "Content-Type: application/json" \
    -H "Authorization: Bearer $GRAFANA_AUTH" 'http://127.0.0.1:3000/api/annotations' \
    -d "{\"text\":\"test annotation\", \"time\":${now}, \"timeEnd\":${later}, \"tags\":${tags}}"
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v7.5.15 (7dd69b2442)
- Data source type & version: Random data
- OS Grafana is installed on: Docker grafana/grafana-enterprise:7.5.15
- User OS & Browser: Arch linux, Firefox 97.0.1
- Grafana plugins: None, vanilla install
- Others:

**Comment by mellieA** [comment]
@joe-balough I tested this out and found that `later=$((now+3600000)) # One minute` is actually 60 minutes. 

I updated it to remove one zero to make $later 6minutes, it seems to work as expected.

The longer annotation shown is the 60 minute one still in effect, the 6 minute annotation ended when the 6 minutes were up:
```
% now=$(date +%s000)                                        
% later=$(($now+360000))  
% echo $now
1649800724000
% echo $later
1649801084000
```

`--data-raw '{"dashboardId":56,"panelId":2,"isRegion":false,"time":1649800724000,"timeEnd":1649801084000,"tags":[],"text":"annotation text API with vars2"}'`

![Screen Shot 2022-04-12 at 4 11 08 PM](https://user-images.githubusercontent.com/18175287/163063271-11e411dd-786e-4411-bfae-269fed9c7db4.png)

I'll close this one for now, but let me know if you're seeing something different:
