### ISSUE TITLE
[Feature Request] add support for graphite's aggregateLine()

### ISSUE THREAD

**Issue by alchuk** [grafana/grafana#4759]
Please, add support for graphite's aggregateLine() function

**Comment by torkelo** [comment]
it is not in the list of functions for latest graphite, 
http://graphite.readthedocs.org/en/0.9.15/functions.html

**Comment by Sune1337** [comment]
I'd also like to see this function implemented.

It actually is listed in the function list, but not for the version you referenced.
http://graphite.readthedocs.io/en/latest/functions.html

**Comment by alchuk** [comment]
Dear Torkel.
Time goes by, Graphite at least of v.1.1 is reported to by supported by the latest Grafana, still there's no aggregateLine() among the allowed functions.
Is there any chance, or should I use alternative edit mode forever? (:

**Comment by torkelo** [comment]
a PR would be greatly appreciated
