### ISSUE TITLE
Alerts triggering at erratic and unpredictable times

### ISSUE THREAD

**Issue by cudamoss** [grafana/grafana#47592]
**What happened**:
I am using both legacy alerts and the new alerting feature. In both cases, it is unclear from the documentation and the UI when the alert will trigger. When setting a 24h alert to test, I have observed the alert triggering at seemingly random times approximately every 4 hours using the new alerts and approximately every day using legacy alerts.

The new Grafana Managed Alerts have triggered roughly every four hours since their creation (+/- roughly an hour). The legacy alert has been more erratic but closer to its intended frequency, alerting roughly every day. In the first couple days of it running, we observed this behavior:
- 3/22 – 8:49pm
- 3/24 – 8:09am
- 3/25 – 6:13am
- 3/26 – 2:12am
- 3/27 – 12:12am
- 3/27 – 10:12pm

**What you expected to happen**:
I expect an alert set to check every 24h to fire at most once a day. further, I expect it to fire at exactly the same time every day (plus or minus a random number of seconds as per the grafana alert documentation on staggering alerts). I do not expect to see multiple firings in the same day, nor do I expect the alerts to trigger at seemingly random times.

**How to reproduce it (as minimally and precisely as possible)**:
(using clickhouse plugin, but I do not believe that is important to replicating this issue)

**Grafana Managed Alert:** 
rule name: TEST ALERT
rule type: Grafana managed alert
folder: folder name

query A: `SELECT now() as day, 1`
query B: 
-Operation: Classic Condition
-Conditions:
  -WHEN last() OF A IS ABOVE 0

define alert conditions:
-condition: B
-evaluate: 
  -evaluate every: 24h for 0s

![Screen Shot 2022-04-05 at 9 17 20 AM](https://user-images.githubusercontent.com/103458370/162825883-7fb7f76c-c280-4d16-a4dc-1213ce0392bd.png)

**Legacy Alerts:**
query: `SELECT now() as day, 1`

Name: test alert
Evaluate every 24h for 0s

Conditions:
-WHEN last() OF query(B, 48h, now) IS ABOVE 0

No data and error handling
if no data or all values are null set state to: Alerting
if execution error or timeout set state to: Alerting

Notification
Send to: slack-channel
Message: foo bar

![Screen Shot 2022-03-28 at 10 08 32 AM](https://user-images.githubusercontent.com/103458370/162826220-2c481ac8-52fb-49c0-82d5-539a4c4c6f65.png)

**Anything else we need to know?**:
I think your documentation on alerts would be greatly benefited by more clarity around when alerts actually trigger and you may consider adding a feature to manually schedule exactly when an alert gets tested, rather than "every x hours for y seconds", have something like "at 12pm UTC the alert will run for 4 min"

**Environment**:
- Grafana version: grafana 8.4.4 OSS edition
- Data source type & version: ClickHouse server version 21.4.5 revision 54447 (via vertamedia-clickhouse-datasource @ 2.4.3 plugin)
- OS Grafana is installed on: Debian 9
- User OS & Browser: OSX 12.3, Chrome (my preference is for firefox but Grafana seems to have issues running there)
- Grafana plugins:
  - briangann-datatable-panel @ 1.0.2
  - flant-statusmap-panel @ 0.3.2
  - grafana-clickhouse-datasource @ 0.12.0
  - grafana-image-renderer @ 3.2.0
  - grafana-piechart-panel @ 1.6.0
  - grafana-polystat-panel @ 1.2.0
  - grafana-redshift-datasource @ 1.0.2
  - isaozler-paretochart-panel @ 0.3.1
  - vertamedia-clickhouse-datasource @ 2.4.3
  - vonage-status-panel @ 1.0.9
  - xginn8-pagerduty-datasource @ 0.2.1
  - yesoreyeram-boomtable-panel @ 1.4.0
- Others:

Thanks for your help!

**Comment by buntsp3cht** [comment]
+1

We are having the exact same issue using:

- Grafana 8.4.6
- InfluxDB with the Flux Querying Language

The first alert that is being triggered is legitimate but then approximately every 4 hours (to be very exact, in our case it’s always 4 hours and 5 minutes) the alert is being fired again, although it hasn’t been resolved in the mean time.


Also mentioned here:
https://community.grafana.com/t/unified-alerting-alert-triggers-every-4-hours/55053

**Comment by buntsp3cht** [comment]
So, the solution was actually quite easy. The user vshaev in the Grafana forum pointed us to the solution: You have to set the correct repeat interval, which will automatically default to 4 hours if not set:
https://grafana.com/docs/grafana/latest/alerting/unified-alerting/notifications/ 

To sum it up:

* Go to your alerting page and then to “Notification policies”
* There is one root policy at the top which you can edit
* Expand “Timing options”
* Under Repeat interval you can set a value, when an already firing alert should be resent. If you don’t set a value it will default to 4 hours
* Alternatively, you can leave the root policy as it is and instead edit your custom notification policy. Enable the option “Override General Timings” and set the repeat interval there.

**Comment by gotjosh** [comment]
That's correct, we want to make sure you can control how often you'd like to be notified about your ongoing alerts. We thought a sensible default was 4 hours.

Closing this for now given its expected behaviour and its well documented.

**Comment by milinpatel13298** [comment]
@gotjosh
I am facing a similar issue and I am not sure the resolution; i.e., repeat interval addresses the following part of issue brought up by @bn-gmoss . Is there a best practice for this kind of situation, where one wants an alert to be evaluated at a certain point in a day/week?
> **What you expected to happen**: I expect an alert set to check every 24h to fire at most once a day. further, I expect it to fire at exactly the same time every day (plus or minus a random number of seconds as per the grafana alert documentation on staggering alerts).
