### ISSUE TITLE
[Display issue] Big scrolbar on the legend table with firefox 

### ISSUE THREAD

**Issue by max3163** [grafana/grafana#4760]
On firefox, the table legend is display with a big scrollbar who make the display of grafana rly weird...

![image](https://cloud.githubusercontent.com/assets/13835366/14634405/0acea792-0622-11e6-8b19-89e9b128220e.png)

No pb with chrome :

![image](https://cloud.githubusercontent.com/assets/13835366/14634630/240d15a8-0623-11e6-96d2-39aefd8fb813.png)

* What grafana version are you using? 3.0 beta-6
* What datasource are you using? InfluxDB
* What OS are you running grafana on? Linux
* What browser are you running? Firefox

**Comment by bergquist** [comment]
Caused by https://github.com/grafana/grafana/commit/260c731f6b1fbd0f1acb60815c5cae7c92e9e22e

**Comment by pather87** [comment]
Hi,

i just updated Grafana from 2.6 to 3.0.4. Problem persists when using 'As Table' Option in Graph Legend. Scrollbar also partially covers legend when using 'To the right' option.

What grafana version are you using? 3.0.4
What datasource are you using? Graphite
What OS are you running grafana on? Debian Jessie
What browser are you running? Iceweasel 38.8.0

Regards
Simon
