### ISSUE TITLE
Extract Fields Transformer - Line splitting applying to values enclosed in quotes

### ISSUE THREAD

**Issue by Helloworld-can** [grafana/grafana#47604]
As the Title says at the time of using Google Cloud Monitoring Datasource - Table Panel is treating words of one sentence as different Objects specially when there's a space, colon, comma are available within a sentence

Please have a look at this issue and assist with fixing it

- [Questions should be posted to: https://community.grafana.com](https://community.grafana.com/t/grafana-table-span/40885/6)
- How to record and attach gif: https://bit.ly/2Mi8T6K
![Data Parsing](https://user-images.githubusercontent.com/4076563/162875785-77f4a2b8-592e-4722-b9b3-497cfe4619e7.gif)

**Google Cloud Monitoring Datasource  - Table Panel Treating words of one sentence as different Objects**:

**Words should not be treated as separate Object but it instead treat whole sentence as one Object**:

**Datasource (Google Cloud Monitoring)>> Select a label which has a big sentence with multiple words and symbols from Stackdriver  metric >> Table Panel >> Transform >> Series to Row >> Extract to Fields (metric) **:

**Environment**:
- Grafana version: Grafana v8.3.1
- Data source type & version: Google Cloud Monitoring (Not sure of version, don't have access to view)
- OS Grafana is installed on: Linux
- User OS & Browser: Windows & Chrome
- Grafana plugins: Stackdriver/Google Cloud Monitoring
- Others: Use of Metrics, Table Panel > Transform

**Comment by aangelisc** [comment]
Hey @Helloworld-can,

I can confirm that we've been able to reproduce the issue where any metric value with spaces leads to a separate field being produced when the `Extract Fields` transformer is used. It seems to be as a result of the regex found [here](https://github.com/grafana/grafana/blob/f62c2619008d4a803e53710eabf9d4b6c0da268c/public/app/features/transformers/extractFields/fieldExtractors.ts#L25) which is then used as a part of the key-value extraction function [here](https://github.com/grafana/grafana/blob/f62c2619008d4a803e53710eabf9d4b6c0da268c/public/app/features/transformers/extractFields/fieldExtractors.ts#L38).

**Comment by Helloworld-can** [comment]
Thank you @aangelisc , @fridgepoet for your confirmation and looking into it so promptly,
I am curious though by when do we expect this bug to be fixed and would it be treated as a Google Cloud Monitoring Plugin release or would it fall under Grafana release?

**Comment by aangelisc** [comment]
Hi @Helloworld-can,

We're currently still investigating the best way to implement a fix so no ETA as of yet. This thread will be kept up-to-date with any progress. The fix will be a Grafana release and we should be able to backport to 8.3.x as well.

**Comment by aangelisc** [comment]
Hey @Helloworld-can! I can confirm this has been fixed and will be released in the next version of 8.4.x and 8.5.x. Unfortunately there isn't likely to be another 8.3.x release. You can see the relevant PR [here](https://github.com/grafana/grafana/pull/47901). Let me know if you have any further questions 😊

**Comment by aangelisc** [comment]
Hey @Helloworld-can, it'll be released in the latest version of both 8.4.x and 8.5.x. It's actually available now in [this](https://github.com/grafana/grafana/releases/tag/v8.5.0) 8.5.x release.

**Comment by Helloworld-can** [comment]
Thanks @aangelisc , 

So we've updated our **Grafana to 8.5.1**  

However, the bug is not completed resolved - I can confirm the change has fixed space problem however when special characters are encountered it creates a new field. I can share a sample string 

Recording:
![Data Parsing 8 5 1](https://user-images.githubusercontent.com/4076563/167027858-8a0f382f-db51-4390-bde6-671b1e3e9a70.gif)

**Sample String:** `metric.label._payload=\"{\"routeKey\":120,\"cfLocationKey\":4,\"name\":\"new test route\",\"courierName\":\"new test route\",\"statusFlag\":\"N\",\"type\":\"R\",\"holidayKey\":null,\"effStartTimestamp\":1651797901000,\"effEndTimestamp\":1651797901000,\"insertTimestamp\":1651783502000,\"updateTimestamp\":1651783583000,\"userName\":\"Dummy Name\"}\"`

At the same time with version 8.5.1 - I've noticed there's problem with Duplicate Data in Table Panels, something I've tried to demonstrate at the end of recording where without using Group By we can't simply achieve a particular use case.

Let me know if you require further details.

**Comment by aangelisc** [comment]
Hi @Helloworld-can, thanks for coming back to me on this. I'll investigate the issue with special characters further. 

With regards to the second issue you mentioned - would it be possible for you to open up another issue for this expanding on it in greater detail please?

**Comment by aangelisc** [comment]
On further investigation @Helloworld-can, I can see the reason that the string you've provided is failing is due to the fact that the nested quotes aren't escaped appropriately. We expect a nested quote to be escaped appropriately based on its level. For example this string would be valid:

`metric.label._payload=\"{\\"routeKey\\":120,\\"cfLocationKey\\":4,\\"name\\":\\"new test route\\",\\"courierName\\":\\"new test route\\",\\"statusFlag\\":\\"N\\",\\"type\\":\\"R\\",\\"holidayKey\\":null,\\"effStartTimestamp\\":1651797901000,\\"effEndTimestamp\\":1651797901000,\\"insertTimestamp\\":1651783502000,\\"updateTimestamp\\":1651783583000,\\"userName\\":\\"Dummy Name\\"}\"`.

Is this data that you're producing?

**Comment by Helloworld-can** [comment]
Hi @aangelisc ,

Apologies on delayed response, so the original data that we have in the metric is Payload: 

```
{"routeKey":166,"cfLocationKey":2,"name":"new test route","courierName":"new test route","statusFlag":"N","type":"R","holidayKey":null,"effStartTimestamp":1651797901000,"effEndTimestamp":1651797901000,"insertTimestamp":1651783502000,
"updateTimestamp":1651783583000,"userName":"Dummy Name"}"
```
So are you suggesting we should replace all `"` with `\"`?

**Comment by aangelisc** [comment]
Hi @Helloworld-can,

No worries at all! The object you've shared is valid JSON. If I use the `JSON.stringify` method on said object this is the output: 
```'{"routeKey":166,"cfLocationKey":2,"name":"new test route","courierName":"new test route","statusFlag":"N","type":"R","holidayKey":null,"effStartTimestamp":1651797901000,"effEndTimestamp":1651797901000,"insertTimestamp":1651783502000,"updateTimestamp":1651783583000,"userName":"Dummy Name"}'```

As you can see the object is enclosed in a string quoted with `'` rather than `"`. This is valid and will be parsed correctly. An alternative option to this is to ensure that any nested quotes are correctly escaped as shown in my previous comment.  If you were to choose the second option then you would replace all double quotes, except the outer ones, with `\\"` as follows: 
```\"{\\"routeKey\\":166,\\"cfLocationKey\\":2,\\"name\\":\\"new test route\\",\\"courierName\\":\\"new test route\\",\\"statusFlag\\":\\"N\\",\\"type\\":\\"R\\",\\"holidayKey\\":null,\\"effStartTimestamp\\":1651797901000,\\"effEndTimestamp\\":1651797901000,\\"insertTimestamp\\":1651783502000,\\"updateTimestamp\\":1651783583000,\\"userName\\":\\"Dummy Name\\"}\"```

The tests found [here](https://github.com/grafana/grafana/blob/main/public/app/features/transformers/extractFields/fieldExtractor.test.ts) may help in clarifying!

**Comment by Helloworld-can** [comment]
Thanks @aangelisc,

For the first one - if you are suggesting it should work fine knowing JSON.stringify method will automatically enclose the string within `'` but that doesn't seem to be happening here think that could be the problem, because in "Series to Rows" Transformation i do not see string enclosed within single `'` but instead its double `"`

![Data Parsing 8 5 1](https://user-images.githubusercontent.com/4076563/167950888-2e6a673f-d345-404f-afae-c20750727938.gif)

**Comment by aangelisc** [comment]
Hi @Helloworld-can, I have opened another issue to track as the original issue has been resolved. The new issue is #48951, I hope this helps 😊

**Comment by Helloworld-can** [comment]
Thanks alot @aangelisc !
