### ISSUE TITLE
Grafana is showing the different time in different location/machine

### ISSUE THREAD

**Issue by NavneetMathpal** [grafana/grafana#4761]
Hi,

I am using grafana version 2.6.0 , and the timezone I have selected is browser , but it is showing the different time in different machines . when I am changing it to UTC again the same problem.

How can I uniform the time that is displayed in various browser and timezone ?

**Comment by torkelo** [comment]
so when you have local it should show the local browser/machine timezone. 

With UTC it should display the time in UTC, so it should be the same for different browsers with different time zones. For example this dashboard,
http://play.grafana.org/dashboard/db/graphite-carbon-metrics

It shows the same time, even if I change timzone on my laptop.
