### ISSUE TITLE
Being able to merge results for single stat panel when using InfluxDB

### ISSUE THREAD

**Issue by DMarby** [grafana/grafana#4762]
Hello,

We have multiple values for a series that are being reported at different times, which each has a different value for a tag. It would be nice to be able to use get the last value of each tag value, and sum them for the single stat panel. Is there a possibility that the single stat panel could allow multiple series and sum them?

Running latest 3.0.0 beta, with InfluxDB 0.12.

**Comment by bergquist** [comment]
This is not possible at the moment. But meta queries(aggregation within grafana) is something that we have been looking at for quite some time. https://github.com/grafana/grafana/issues/3677 

But closing since its a dupe.
