### ISSUE TITLE
Rename VictorOps notifier to Splunk OnCall

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#47632]
**What happened**:

VictorOps has been acquired by Splunk: https://www.splunk.com/en_us/investor-relations/acquisitions/splunk-on-call.html

The notifier should be updated to reflect the new name.

Care should be taken to migrate existing VictorOps notifiers in existing user configurations. Some potential ways around this:
1. Create a migration to update all old-style notifiers to the new one
2. Only change display names, etc, and keep type identifiers the same
3. Have the code support both type identifiers indefinitely

**What you expected to happen**:

I expected there to not be deprecated names in the notifier list.

**How to reproduce it (as minimally and precisely as possible)**:

Open the Contact Point Type drop-down.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.x

**Comment by grobinson-grafana** [comment]
I've not had time to start this, can be picked up at a later time or someone else

**Comment by ArmaanKatyal** [comment]
Hi @armandgrillet, I would like to work on this issue.

**Comment by chauchausoup** [comment]
Hello @armandgrillet @alexweav 
I am interested to fix this issue. As per the ways around suggested in above issues section I am a bit confused on following points.

`Only change display names, etc, and keep type identifiers the same
`
This means we will only have visual parts changes but the identifiers, filenames etc will still be the older ones right ?

`Have the code support both type identifiers indefinitely
`
I am a bit confused on this part. Can you explain us about it in more details ?
