### ISSUE TITLE
[Feature Request] Enable shifting time window

### ISSUE THREAD

**Issue by coussej** [grafana/grafana#4764]
It would be useful to be able to allow shifting the time window for a dashboard by `Δt = end - start` by means of arrow buttons next to the time selector. 

For example: there is a dashboard with default time `now-30m` to `now`. In many cases, I'd also want to shift the time to look at the data of `now-60m` to `now-30m`, `now-90m` to `now-60m`, ... with the same zoom level. For now, this is only possible by manually adjusting the start and end times, which is pretty laborious.

**Comment by coussej** [comment]
While looking for the piece of code where these buttons should belong, i saw commit 3ab54270198f898573ed5e197f73799af9ed31e8, which by the look of it implements exactly what I want. Is this already available in the latest beta package?

**Comment by torkelo** [comment]
You can test it on play.grafana.org or install the latest 3.0 beta
