### ISSUE TITLE
Check if `NoDataSourceCallToAction` is still relevant

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#47641]
"new" grafana versions have a "Grafana" datasource by default which seems like is not removable. 

`NoDataSourceCallToAction` is rendered in explore when there's no available datasource, but given (as per the previous statement) there is always at least one datasource, it is never rendered.

We should check wether we could remove that component and do some cleanup OR if/how we should remove the "Grafana" DS from Explore.

**Comment by gelicia** [comment]
We are going to keep the handling of this scenario in case it is relevant.
