### ISSUE TITLE
[Bug] Number not center when width of singlestat panel is very small

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4766]
Hi,

I inform you a little bug:
I using the singlestat panel with a very small width. The problem is the number it's not center and so i should to descrease the size of number. The result it's not beautiful:
![centezr](https://cloud.githubusercontent.com/assets/15362041/14643004/0df2ff74-064d-11e6-9adc-ca91542f42ff.PNG)

I think the problem come from the padding-left of 20px on css class:  `singlestat-panel-value-container `

**Comment by torkelo** [comment]
looks like fixded
