### ISSUE TITLE
grafana:latest pushed with incorrect grafana version vv1.0

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#47664]
one of my deployments had grafana:klatest, and the new image that was pushed to dockerhub https://hub.docker.com/layers/grafana/grafana/grafana/latest/images/sha256-43c088a2b956540508e5e173c530309cb8d5c93180620b41d4f6c82e69571aa7?context=explore has incorrect version tagging. In the help menu it shows a beta version where as in the bottom of the screen shows vv1.0, and it makes many panels which expect at least grafana 7 to fail to render. 

![image](https://user-images.githubusercontent.com/8618235/163056051-8e88a8f9-642d-415f-8e57-96f91e4afda2.png)

Steps to recreate:
`docker run --rm  -p 3000:3000 grafana/grafana:latest`

Navigate to any dashboards using panels such as https://grafana.com/grafana/plugins/marcusolsson-hexmap-panel/
![image](https://user-images.githubusercontent.com/8618235/163056543-b12846d0-d2e3-478e-adde-46e7663d35d5.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @mvadu 

This PR addresses the problem for `8.5.0`:
https://github.com/grafana/grafana/pull/47402
