### ISSUE TITLE
The "No Value" box does not override the "No Data" output

### ISSUE THREAD

**Issue by techgnosis** [grafana/grafana#47662]
**What happened**:
A customer asked me how to override what a panel says when there is no data. Usually it says "No Data" but I found a box in the panel config called "No Value" that sounded like it was for overriding the "No Data" output. I was told that was the correct box but I've never been able to get it to work and the customer was not able to get it to work either. 

It's possible that it's dependent on how you achieve a "No Data" scenario. I tried by changing the name of the metric to one that doesn't exist. That gave me "No Data" immediately but it was never overwritten by the "No Value" field.

Customers words - "I tried editing the “No Value” box with integer, string value and string variable in the panel for Pie Chart Visualization. Also tried with the value mapping options which is next to the “No Value” but still no luck in replacing the no data option."

**What you expected to happen**:
I would expect that whatever I type into "No Value" would show instead of "No Data" in a "No Data" scenario.

**How to reproduce it (as minimally and precisely as possible)**:
1. Choose a Prometheus data source
2. Find a metric that exists and graph it so you know you're in a good state
3. Add "fake" to the end of the metric name so you get a "No Data" output
4. Set the "No Value" field in the panel options section to something other than blank
5. I still see "No Data" instead of whatever I set the "No Value" field to

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: Prometheus
- OS Grafana is installed on: official Docker image
- User OS & Browser: Chrome on Ubuntu
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
related discussion for the table panel, which was marked as feature request:

https://github.com/grafana/grafana/issues/28458

@techgnosis this functionality appears panel-specific. Was this regarding the pie-chart panel specifically? Different squads own different panels, is why I ask 👍

**Comment by techgnosis** [comment]
Yeah the customer asked specifically about Pie Chart. I was testing things out with Time Series

**Comment by sharyjose91** [comment]
@techgnosis I am facing the same issue.  I tried editing the “No Value” box with integer, string value and string variable in the panel for Table Visualization, but I cant replace the "No Data" with meaningful sentence.

Environment:
Grafana version: 9.2.2
Data source type & version: Microsoft SQL Server
