### ISSUE TITLE
provisioned dashboards: add config option to disable dashboard refresh (updateIntervalSeconds)

### ISSUE THREAD

**Issue by yuwaMSFT2** [grafana/grafana#47667]
**What happened**:
When we enable pre-provisioned dashboards in Grafana, we noticed higher number of DB calls periodically.
After some investigation, it turns out that this is introduced by the auto refresh of the provisioned dashboards.
For each provisioned dashboard, when updateIntervalSeconds expires, Grafana will retrieve the  dashboard package from disk, and then make two database queries (one query to Dashboard table, and one to Dashboard_Provisioning table) to check if there is any change.

In my cases, we do not update the provisioned dashboards on the fly. It could be significant DB operations if there are many provisioned dashboards and if the Database server is shared.

**What you expected to happen**:
Since the dashboard package is from provision folder, probably it can be optimized to avoid DB calls if there is no file change
Also, for many cases, the provisioned dashboards don't change. In that case, probably having a configuration to disable auto update is appropriate.

**How to reproduce it (as minimally and precisely as possible)**:
Enable several provisioned dashboards, and check the DB statement.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@yuwaMSFT2 this looks like it could be considered a feature request. We've moved feature requests to github discussions - but I'll leave it here for now while the team reviews it

**Comment by pciavald** [comment]
This is marked as completed, but I can't find how to do this. Has an option been implemented ?
