### ISSUE TITLE
Docker image :latest is missing ARM variants

### ISSUE THREAD

**Issue by p-schneider** [grafana/grafana#47676]
**What happened**:
<img width="346" alt="image" src="https://user-images.githubusercontent.com/2636101/163111076-23b1eebc-7f61-4bd3-bb91-a613619a21b5.png">

<img width="354" alt="image" src="https://user-images.githubusercontent.com/2636101/163322465-ef95dbba-06b9-4e91-a22b-3b6d1e9488f0.png">

<img width="349" alt="image" src="https://user-images.githubusercontent.com/2636101/163322542-b816cc6d-c3de-4658-8415-90d05601508d.png">

The [`:latest`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=latest) docker tag/image ([`grafana/grafana`](https://hub.docker.com/r/grafana/grafana/tags) / [`grafana/grafana-oss`](https://hub.docker.com/r/grafana/grafana-oss/tags)) is currently **only** listing **`linux/amd64`** (`43c088a2b956`).
That is the same digest as the `linux/amd64` variant in in [`:8.5.0-beta1`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=8.5.0-beta1). 
The [`:8.5.0-beta1`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=8.5.0-beta1) image however additionally also has the **`linux/arm/v7`** and **`linux/arm64/v8`** variants.
Similarly also for the [`:latest-ubuntu`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=latest-ubuntu) tag/image.
The [`:latest[ubuntu]` docker tags for grafana-enterprise](https://hub.docker.com/r/grafana/grafana-enterprise/tags?page=1&name=latest) are also only providing `linux/amd64` images.

**What you expected to happen**:

- I would expect the [`:latest`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=latest) tag/image to also have the **`linux/arm/v7`** and **`linux/arm64/v8`** variants
- I would expect the [`:latest`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=latest) tag/image not to link to a **beta version** (currently [8.5.0-beta1](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=8.5.0-beta1)) 
  but to the latest **stable release** (currently [8.4.6](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=8.4.6)) instead
- I would expect the same for [`:latest-ubuntu`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=latest-ubuntu)
- ... and similarly for [grafana-enterprise](https://hub.docker.com/r/grafana/grafana-enterprise/tags?page=1&name=latest)

**Environment**:
- Grafana version: Docker OSS+Enterprise [`:latest[-ubuntu]`](https://hub.docker.com/r/grafana/grafana-oss/tags?page=1&name=latest)
- OS Grafana is installed on: Docker (ARM v7/v8)

**Comment by crtvrmn** [comment]
same happend with me.

**Comment by 4d1m** [comment]
Same here! A temporary fix to have grafana working would be to use the :main tag.

**Comment by S474N** [comment]
Same problem, and if use `:latest`, then in docker logs:
`standard_init_linux.go:228: exec user process caused: exec format error`

**Comment by dneary** [comment]
I noticed that builds uploaded by the @grafanaci user have arm64, only the upload by @dsotirakis two days ago has the missing builds.

**Comment by tomthetommy** [comment]
Just came here to say this. My raspberry pi cluster has been complaining since a few days ago. I guess this is a valid reason to stop using “latest” on images. Lesson learned I think. :)

**Comment by agneevX** [comment]
Yeah, version pinning is a safe bet.

**Comment by dsotirakis** [comment]
Hello all! Thanks for raising this.
We accidentally tagged latest with the wrong version, then we force-pushed the correct `latest` image and the archs were messed up. Normally, our `latest` images include all architectures. Will fix asap. 🙏

**Comment by dsotirakis** [comment]
Hello again!
Should be fixed by now:

![image](https://user-images.githubusercontent.com/15115078/163782720-e5588aea-6c4c-4c3d-9686-c7c24c083eff.png)

Also: 
* Changed the user from my personal one `dimsotirakis` (had docker hub permissions issues that are resolved now), to `grafanaci`.
* `latest` tags point to `8.4.6` now. 

Please let me know if something still is/looks wrong!
Thanks!

**Comment by S474N** [comment]
Now are `:main` and `:latest` same version 8.4.6?

Where is 9.0?

**Comment by dsotirakis** [comment]
> Now are :main and :latest same version 8.4.6?

`main` tag will change on the next merge against the OSS main branch.

> Where is 9.0?

Hang in there, not ready yet! 😉

**Comment by p-schneider** [comment]
`:latest` and `:8.4.6` (incl. `-ubuntu` in both oss and enterprise) looks good to me now.
`:main[ubuntu]` currenty points to the same images as `:latest` / `:8.4.6`, I assume that will change with the next commit to the main branch.
Thank you!

**Comment by S474N** [comment]
@dsotirakis yesterday was 9.0.0 on `:latest`, look:
https://github.com/grafana/grafana/issues/47834

**Comment by dsotirakis** [comment]
> @dsotirakis yesterday was 9.0.0 on :latest, look:

That was on the `main` tag. Will change again soon as mentioned above.

**Comment by dneary** [comment]
Thank you @dsotirakis!
