### ISSUE TITLE
UnifiedAlerting: Email cert issue can cause Grafana to crash

### ISSUE THREAD

**Issue by bunnyevans** [grafana/grafana#47671]
**What happened**:
Grafana kept dying when the battery voltage was "zero" (it was just missing data)

**What you expected to happen**:
No crash.

**How to reproduce it (as minimally and precisely as possible)**:
Not sure. it seems to be when trying to send mail.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.6
- Data source type & version: influxdb 1
- OS Grafana is installed on: freebsd 13
- User OS & Browser: chrome on W10
- Grafana plugins: none that I know of.
- Others:

grafana.log 

t=2022-04-12T23:05:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.net, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:10:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-12T22:55:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-defaul
t-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@
cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.ne
t, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:00:08+0900 lvl=eror msg="alert rule panic" logger=ngalert error="runtime error: invalid memory address or nil pointer derefe
rence" stack="goroutine 337 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/services/ng
alert/eval.executeQueriesAndExpressions.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:259 +0x5d\npanic({0x5c9f40,
0x4819ae0})\n\truntime/panic.go:838 +0x207\nreflect.mapiterinit(0x95e7c0?, 0xc000c951c0?, 0xc000c951c0?)\n\truntime/map.go:1373 +0x19\ngonum
.org/v1/gonum/graph/iterator.(*mapIter).next(0xc0010c73a0)\n\tgonum.org/v1/gonum/graph/iterator/map.go:89 +0x5e\ngonum.org/v1/gonum/graph/it
erator.(*Nodes).Next(0xc000a8e6c0)\n\tgonum.org/v1/gonum/graph/iterator/nodes_map.go:40 +0x36\ngithub.com/grafana/grafana/pkg/expr.buildNode
Registry(0xc000a903a0)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:115 +0x149\ngithub.com/grafana/grafana/pkg/expr.(*Service).buildDepen
dencyGraph(0xc000c95288?, 0x26e34b7?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:85 +0x28\ngithub.com/grafana/grafana/pkg/expr.(*Servic
e).buildPipeline(0xc08d7f5a10239a8e?, 0x390b9badefb?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:65 +0x19\ngithub.com/grafana/grafana/p
kg/expr.(*Service).BuildPipeline(...)\n\tgithub.com/grafana/grafana/pkg/expr/service.go:61\ngithub.com/grafana/grafana/pkg/expr.(*Service).T
ransformData(0xc00178fda0, {0x108d3f0, 0xc00027d140}, 0xc000ab31d0)\n\tgithub.com/grafana/grafana/pkg/expr/transform.go:134 +0x114\ngithub.c
om/grafana/grafana/pkg/services/ngalert/eval.executeQueriesAndExpressions({0x1, 0x1, {0x82c397058, 0xc00177d400}, {0x108d3f0, 0xc00027d140}}
, {0xc000c14000?, 0xc00195535c?, 0x1?}, {0xc08d7f5a10239a8e, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:274
+0x1ce\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeCondition({0x1, 0x1, {0x82c397058, 0xc00177d400}, {0x108d3f0, 0xc00027d1
40}}, 0xc000c95c18, {0xc08d7f5a10239a8e, 0x390b9badefb, 0x4abe160}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:173
 +0xed\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*Evaluator).ConditionEval(0xc000ea5eb8, 0xc000edac18, {0x26992d1?, 0x80?, 0x4a
be160?}, 0xc00106a340?)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:510 +0x16f\ngithub.com/grafana/grafana/pkg/services/
ngalert/schedule.(*schedule).ruleRoutine.func2(0xc0004a6b40, 0x2?, 0xc000ab1fc0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule
/schedule.go:460 +0x30a\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4.2(0x38?)\n\tgithub.com/grafa
na/grafana/pkg/services/ngalert/schedule/schedule.go:556 +0x1b7\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRo
utine.func3(0xc000872f40)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:517 +0x5c\ngithub.com/grafana/grafana/pkg/
services/ngalert/schedule.(*schedule).ruleRoutine.func4(0x0?, 0x26a0853?, {0x2691801?, {0xc0014fe4e0?, 0x0?}}, 0xc000ab1fc0, 0xc000edaeb0, 0
xc00125a3a8, 0xc0014ee480, {0x109b0b0, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:546 +0x194\ngithub
.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc000ea5e60, {0x108d380, 0xc0014ee3c0}, {0xc000ea5e68?, {0xc0014
fe4e0?, 0xc000d00f01?}}, 0xc0014e2060)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:561 +0x6b5\ngithub.com/grafan
a/grafana/pkg/services/ngalert/schedule.(*schedule).schedulePeriodic.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/sch
edule.go:367 +0x38\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\tgolang.org/x/sync/errgroup/errgroup.go:57 +0x67\ncreated by golang.org
/x/sync/errgroup.(*Group).Go\n\tgolang.org/x/sync/errgroup/errgroup.go:54 +0x8d\n"
t=2022-04-12T23:00:08+0900 lvl=info msg="level=debug component=dispatcher msg=\"Received alert\" alert=Battery[a24babd][active]" logger=aler
tmanager org=1
t=2022-04-12T23:00:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" lo
gger=alertmanager org=1
t=2022-04-12T23:00:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-defaul
t-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@
cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.ne
t, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:05:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" lo
gger=alertmanager org=1
t=2022-04-12T23:05:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-defaul
t-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@
cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.ne
t, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:10:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" lo
gger=alertmanager org=1
t=2022-04-12T23:10:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.net, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:15:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-12T23:15:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.net, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:20:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-12T23:20:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.net, not localhost\"" logger=alertmanager org=1
t=2022-04-12T23:25:38+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-12T23:25:38+0900 lvl=info msg="level=error component=dispatcher msg=\"Notify for alerts failed\" num_alerts=1 err=\"grafana-default-email/email[0]: notify retry canceled due to unrecoverable error after 1 attempts: Failed to send notification to email addresses: <xyzzy@cute.net>: x509: certificate is valid for *.anime.org, *.bunny.haus, *.deadmicrophone.org, *.ixp.jp, *.kirameki.edu, *.manga.org, *.usagi.net, not localhost\"" logger=alertmanager org=1

After this, nothing, it has silently died.

Could be the default smtp settings? but still, premature death with no autopsy?

**Comment by bunnyevans** [comment]
Changed to disable opportunistic TLS.

t=2022-04-13T12:00:03+0900 lvl=eror msg="alert rule panic" logger=ngalert error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 530 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeQueriesAndExpressions.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:259 +0x5d\npanic({0x5c9f40, 0x4819ae0})\n\truntime/panic.go:838 +0x207\nreflect.mapiterinit(0x95e7c0?, 0xc0008691c0?, 0xc0008691c0?)\n\truntime/map.go:1373 +0x19\ngonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc000e7a940)\n\tgonum.org/v1/gonum/graph/iterator/map.go:89 +0x5e\ngonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0xc001325a10)\n\tgonum.org/v1/gonum/graph/iterator/nodes_map.go:40 +0x36\ngithub.com/grafana/grafana/pkg/expr.buildNodeRegistry(0xc0014cf5a0)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:115 +0x149\ngithub.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0xc000869288?, 0x26e34b7?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:85 +0x28\ngithub.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0xc08dad0cdfff5e2e?, 0xaea6bcfba6?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:65 +0x19\ngithub.com/grafana/grafana/pkg/expr.(*Service).BuildPipeline(...)\n\tgithub.com/grafana/grafana/pkg/expr/service.go:61\ngithub.com/grafana/grafana/pkg/expr.(*Service).TransformData(0xc00135d170, {0x108d3f0, 0xc000dd9200}, 0xc001324060)\n\tgithub.com/grafana/grafana/pkg/expr/transform.go:134 +0x114\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeQueriesAndExpressions({0x1, 0x1, {0x82c2bbd98, 0xc00134afa0}, {0x108d3f0, 0xc000dd9200}}, {0xc000888000?, 0x4abe160?, 0x5348e0?}, {0xc08dad0cdfff5e2e, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:274 +0x1ce\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeCondition({0x1, 0x1, {0x82c2bbd98, 0xc00134afa0}, {0x108d3f0, 0xc000dd9200}}, 0xc000869c18, {0xc08dad0cdfff5e2e, 0xaea6bcfba6, 0x4abe160}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:173 +0xed\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*Evaluator).ConditionEval(0xc000719a38, 0xc000869c18, {0x29ef6f2?, 0xc0?, 0x4abe160?}, 0xd0?)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:510 +0x16f\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func2(0xc00075c960, 0xacd84f?, 0xc0014cf3a0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:460 +0x30a\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4.2(0x38?)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:556 +0x1b7\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3(0xc000ea9ac0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:517 +0x5c\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0x0?, 0x804c96108?, {0x1?, {0xc0016d6550?, 0xc000b4de10?}}, 0xc0014cf3a0, 0xc00146feb0, 0xc0013ff990, 0xc0011d8300, {0x109b0b0, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:546 +0x194\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc0007199e0, {0x108d380, 0xc0011d8240}, {0xc0007199e8?, {0xc0016d6550?, 0x1068610?}}, 0xc0008aa8a0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:561 +0x6b5\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).schedulePeriodic.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:367 +0x38\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\tgolang.org/x/sync/errgroup/errgroup.go:57 +0x67\ncreated by golang.org/x/sync/errgroup.(*Group).Go\n\tgolang.org/x/sync/errgroup/errgroup.go:54 +0x8d\n"
t=2022-04-13T12:00:03+0900 lvl=info msg="level=debug component=dispatcher msg=\"Received alert\" alert=Battery[a24babd][active]" logger=alertmanager org=1


Not crashed yet but that error worries me ^^;

**Comment by bunnyevans** [comment]
I'm not sure it's the certificate thing,. 
After turning off that "opportunisticTLS" thing, it still crashed silently.

t=2022-04-13T13:30:03+0900 lvl=eror msg="alert rule panic" logger=ngalert error="runtime error: invalid memory address or nil pointer dereference" stack="goroutine 530 [running]:\nruntime/debug.Stack()\n\truntime/debug/stack.go:24 +0x65\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeQueriesAndExpressions.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:259 +0x5d\npanic({0x5c9f40, 0x4819ae0})\n\truntime/panic.go:838 +0x207\nreflect.mapiterinit(0x95e7c0?, 0xc00075b1c0?, 0xc00075b1c0?)\n\truntime/map.go:1373 +0x19\ngonum.org/v1/gonum/graph/iterator.(*mapIter).next(0xc000e7b480)\n\tgonum.org/v1/gonum/graph/iterator/map.go:89 +0x5e\ngonum.org/v1/gonum/graph/iterator.(*Nodes).Next(0xc000bf1050)\n\tgonum.org/v1/gonum/graph/iterator/nodes_map.go:40 +0x36\ngithub.com/grafana/grafana/pkg/expr.buildNodeRegistry(0xc0013020c0)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:115 +0x149\ngithub.com/grafana/grafana/pkg/expr.(*Service).buildDependencyGraph(0xc00075b288?, 0x26e34b7?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:85 +0x28\ngithub.com/grafana/grafana/pkg/expr.(*Service).buildPipeline(0xc08db252dfff5e2e?, 0x597efd1eba6?)\n\tgithub.com/grafana/grafana/pkg/expr/graph.go:65 +0x19\ngithub.com/grafana/grafana/pkg/expr.(*Service).BuildPipeline(...)\n\tgithub.com/grafana/grafana/pkg/expr/service.go:61\ngithub.com/grafana/grafana/pkg/expr.(*Service).TransformData(0xc00135d170, {0x108d3f0, 0xc00153c120}, 0xc000bf02d0)\n\tgithub.com/grafana/grafana/pkg/expr/transform.go:134 +0x114\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeQueriesAndExpressions({0x1, 0x1, {0x82c2bbd98, 0xc00134afa0}, {0x108d3f0, 0xc00153c120}}, {0xc000888000?, 0x82cda9950?, 0x30?}, {0xc08db252dfff5e2e, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:274 +0x1ce\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.executeCondition({0x1, 0x1, {0x82c2bbd98, 0xc00134afa0}, {0x108d3f0, 0xc00153c120}}, 0xc00075bc18, {0xc08db252dfff5e2e, 0x597efd1eba6, 0x4abe160}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:173 +0xed\ngithub.com/grafana/grafana/pkg/services/ngalert/eval.(*Evaluator).ConditionEval(0xc000719a38, 0xc00146bc18, {0xc00146bb18?, 0x3047e9e?, 0x4abe160?}, 0x108d3b8?)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/eval/eval.go:510 +0x16f\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func2(0xc00075c960, 0x2?, 0xc001302040)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:460 +0x30a\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4.2(0x38?)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:556 +0x1b7\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func3(0xc00050a340)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:517 +0x5c\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine.func4(0x0?, 0x804c96108?, {0x1?, {0xc0016d6550?, 0xc000b4de10?}}, 0xc001302040, 0xc00146beb0, 0xc0013ff990, 0xc0011d8300, {0x109b0b0, ...}, ...)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:546 +0x194\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).ruleRoutine(0xc0007199e0, {0x108d380, 0xc0011d8240}, {0xc0007199e8?, {0xc0016d6550?, 0x1068610?}}, 0xc0008aa8a0)\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:561 +0x6b5\ngithub.com/grafana/grafana/pkg/services/ngalert/schedule.(*schedule).schedulePeriodic.func1()\n\tgithub.com/grafana/grafana/pkg/services/ngalert/schedule/schedule.go:367 +0x38\ngolang.org/x/sync/errgroup.(*Group).Go.func1()\n\tgolang.org/x/sync/errgroup/errgroup.go:57 +0x67\ncreated by golang.org/x/sync/errgroup.(*Group).Go\n\tgolang.org/x/sync/errgroup/errgroup.go:54 +0x8d\n"
t=2022-04-13T13:30:03+0900 lvl=info msg="level=debug component=dispatcher msg=\"Received alert\" alert=Battery[a24babd][active]" logger=alertmanager org=1
t=2022-04-13T13:30:03+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-13T13:35:03+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-13T13:40:03+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-13T13:45:03+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-13T13:50:03+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1
t=2022-04-13T13:55:03+0900 lvl=info msg="level=debug component=dispatcher aggrGroup={}:{} msg=flushing alerts=[Battery[a24babd][active]]" logger=alertmanager org=1

**Comment by bunnyevans** [comment]
changed logging to debug. still a silent death.  Note, didn't send any email this time:

t=2022-04-13T17:28:40+0900 lvl=dbug msg="neither config nor template have changed, skipping configuration sync." logger=alertmanager org=1
t=2022-04-13T17:28:40+0900 lvl=dbug msg="done synchronizing Alertmanagers for orgs" logger=ngalert.multiorg.alertmanager
t=2022-04-13T17:28:49+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:28:54+0900 lvl=dbug msg="recording state cache metrics" logger=ngalert now=2022-04-13T17:28:54+0900
t=2022-04-13T17:28:59+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:29:09+0900 lvl=dbug msg="recording state cache metrics" logger=ngalert now=2022-04-13T17:29:09+0900
t=2022-04-13T17:29:09+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:29:19+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:29:24+0900 lvl=dbug msg="recording state cache metrics" logger=ngalert now=2022-04-13T17:29:24+0900
t=2022-04-13T17:29:29+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:29:39+0900 lvl=dbug msg="recording state cache metrics" logger=ngalert now=2022-04-13T17:29:39+0900
t=2022-04-13T17:29:39+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:29:39+0900 lvl=dbug msg="removing expired data encryption keys from cache..." logger=secrets
t=2022-04-13T17:29:39+0900 lvl=dbug msg="done removing expired data encryption keys from cache" logger=secrets
t=2022-04-13T17:29:40+0900 lvl=dbug msg="synchronizing Alertmanagers for orgs" logger=ngalert.multiorg.alertmanager
t=2022-04-13T17:29:40+0900 lvl=dbug msg="neither config nor template have changed, skipping configuration sync." logger=alertmanager org=1
t=2022-04-13T17:29:40+0900 lvl=dbug msg="done synchronizing Alertmanagers for orgs" logger=ngalert.multiorg.alertmanager
t=2022-04-13T17:29:40+0900 lvl=dbug msg="start of admin configuration sync" logger=ngalert
t=2022-04-13T17:29:40+0900 lvl=dbug msg="found admin configurations" logger=ngalert count=0
t=2022-04-13T17:29:40+0900 lvl=dbug msg="finish of admin configuration sync" logger=ngalert
t=2022-04-13T17:29:49+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:29:54+0900 lvl=dbug msg="recording state cache metrics" logger=ngalert now=2022-04-13T17:29:54+0900
t=2022-04-13T17:29:59+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]
t=2022-04-13T17:30:09+0900 lvl=dbug msg="recording state cache metrics" logger=ngalert now=2022-04-13T17:30:09+0900
t=2022-04-13T17:30:09+0900 lvl=dbug msg="alert rules fetched" logger=ngalert count=1 disabled_orgs=[]

**Comment by bunnyevans** [comment]
Removing the alert does prevent crashing. It has now been running for 3 days, which is a big improvement over an hour or so.

**Comment by mhoffm-aiven** [comment]
this could be related to #46997 ( saw gonum a few times in the trace ).

**Comment by alexweav** [comment]
Agree, the email issue and the nil dereference do not seem to be related. According to the log time stamps, the nil deref happened well before the email issue.

It seems very likely that the dereference is related to that gonum issue. That issue was only backported to 8.5 and up, could you please try again on the latest 8.5.x? Closing this for now as I believe it will have fixed this, but please feel free to re-open if the issue still happens.
