### ISSUE TITLE
References are impossible to see in markdown panels

### ISSUE THREAD

**Issue by volter** [grafana/grafana#4767]
Hyperlinks are not visible, unless you cross them with the pointer, and even then, it is hard. I tried with light and dark style and in FF and Chromium.

**Comment by mattttt** [comment]
Going to make it match the new blue links we're using elsewhere  (on the app pages, etc). Will commit shortly.

**Comment by mattttt** [comment]
Fixed in PR: https://github.com/grafana/grafana/pull/4794

![screenshot 2016-04-22 11 31 22](https://cloud.githubusercontent.com/assets/2886187/14746503/f4fc6752-087d-11e6-80ea-b4eb470f2c70.png)
