### ISSUE TITLE
TablePanel: Horizontal scrolling broken in v8.5 beta 

### ISSUE THREAD

**Issue by nguyencaochien** [grafana/grafana#47672]
**What happened**: My table have a lot of columns, and when i scroll horizontal, it's only show header, not show value.

**What you expected to happen**: show all value when scroll horizontal
![Screen Shot 2022-04-13 at 11 34 27](https://user-images.githubusercontent.com/24190909/163101110-8caefebb-c166-48c9-99b9-cbe7ab02c952.png)

I already check in https://play.grafana.org/d/OhR1ID6Mk/3-table?orgId=1 , have a same problem when i reduce width of table

![Screen Shot 2022-04-13 at 11 40 05](https://user-images.githubusercontent.com/24190909/163101697-1ae7d2ac-bfc3-469a-ba4d-5ebdf097bd62.png)

**Environment**:
- Grafana version: 8.5.0 - beta1
- Data source type & version:
- OS Grafana is installed on: MAC
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
when you hover over the table, do you not see a horizontal scrollbar?

**Comment by torkelo** [comment]
ah, wait I can replicate  it now as well, strange

**Comment by nguyencaochien** [comment]
@torkelo yes, a horizontal scrollbar at the bottom only show when i scroll.

**Comment by torkelo** [comment]
Looks like https://github.com/grafana/grafana/pull/45732 introduced this 

* Horizontal scrolling just shows blank empty space 
* The pagination is not working at all with horizontal scrolling, the scrollbar is below the pagination and is scrolling the pagination footer as well. It should be above the pagination footer and it should not scroll the pagination footer.

**Comment by nguyencaochien** [comment]
I think it not related with my issue. i only have two row and no need to use pagination. But my table have many columns and i need to see it with horizontal scrolling.

Last version (8.1), it's not happened. 

This problem still have with pagination. See my attach when horizontal scrolling
![Screen Shot 2022-04-13 at 13 57 31](https://user-images.githubusercontent.com/24190909/163118476-84d57da3-1cea-422d-9dbb-cc7400a74839.png)
![Uploading Screen Shot 2022-04-13 at 13.57.38.png…]()

**Comment by torkelo** [comment]
I mean that PR introduced it, I know the issue is present even without pagination enabled

**Comment by nguyencaochien** [comment]
yes, so please help to fix it. Thanks!
