### ISSUE TITLE
Grafana 8.4.3 Alerting: Webhooks do not support sending template messages

### ISSUE THREAD

**Issue by Geek-Joey** [grafana/grafana#47682]
**What happened**:
When I choose  contact points type which named **webhook**, I find that there is no place to post message，for example : 
```go
报警: {{.Status}}
{{ range .Alerts.Firing }} 
 {{ .Labels}}
 {{ .Annotations }} 
{{ end }}
```
<img width="1265" alt="image" src="https://user-images.githubusercontent.com/80373700/163139776-9b250d4b-a576-4f5a-9f76-0656d0fcd77e.png">

**What you expected to happen**:
but when i choose contact points type which named **dingtalk**, there is what I want to submit messgae : 
<img width="774" alt="image" src="https://user-images.githubusercontent.com/80373700/163141520-c9c040ab-1eaf-42b7-a993-949151a3d8cd.png">

My goal is to use webhook to submit defined template. 
Is this a bug or am I using it wrong ? I would be very grateful if you could give me an answer .

**Environment**:
- Grafana version:8.4.3
- OS Grafana is installed on: docker
- User OS :Mac M1

**Comment by mellieA** [comment]
@Geek-Joey I found [this issue comment]( https://github.com/grafana/grafana/issues/39569#issuecomment-938473121) that says that message, state and title were included for backwards compatibility, but they were deprecated in version 8.1 per this comment in the code `// Deprecated, to be removed in 8.1.`
