### ISSUE TITLE
Bar chart: x-axis labels not updating

### ISSUE THREAD

**Issue by McPlayHD** [grafana/grafana#47697]
**What happened**:

I created a Bar chart and am feeding it with a table of keys and values selected from a MySQL data source.

![table](https://user-images.githubusercontent.com/7106489/163173007-cd692b71-e8e1-41dd-916d-68f031fae008.png)

I am plotting it as seen in this screenshot:

![chart](https://user-images.githubusercontent.com/7106489/163173194-e32808e4-398c-4591-8de9-a16305d61391.png)

In the background, a program is using the exact same MySQL query and taking away elements from the left resulting in this Bar chart showing a queue and the bars are slowly moving to the left while the background process is working on the items. **But** for some reason only the bars (displaying the amount waiting for the specific key) are going to the left but the keys themselves displayed in the x-axis labels don't go to the left when the panel is refreshed.

![bug](https://user-images.githubusercontent.com/7106489/163173575-a3c78fdc-b278-4191-a5eb-cf6fe71aa0c9.png)
_You can see that in the second screenshot the labels stayed the same but the bars moved to the left._ 

**What you expected to happen**:

I expect the labels to update at every refresh since the table changed.

![expected](https://user-images.githubusercontent.com/7106489/163174110-c49ab823-8bcf-43ce-b10a-2083bf984e22.png)

**How to reproduce it (as minimally and precisely as possible)**:

- Create a table `dummy` with `N` rows (With N the amount of numbers you want to display)
- Create a bar chart with the following MySQL query:
```sql
SELECT 
floor(rand()*100) as "key", 
rand()*10 as "value" 
from dummy
limit N
```
- Make sure to select "Format as: Table" below the MySQL-Query
- Select the "key" as X-Axis
- Refresh several times. For me it usually works the first 5-10 refreshes and then it stops updating and only a full refresh (F5) fixes the issue. Sometimes it also works almost all the time and only on very rare instances does the x-axis skips an update. Seems to be some sort of racing condition. Especially since my initial query takes about 0.3 seconds to process and the dummy query I gave here is an almost instant query.

**Anything else we need to know?**:

Might be similar to https://github.com/grafana/grafana/issues/36247

**Environment**:
- Grafana version: Version 8.4.6 (commit: c53173ff6b, branch: HEAD)
- Data source type & version: 10.3.34-MariaDB
- OS Grafana is installed on: Debian 8.3.0 - Linux version 4.19.0-19-amd64
- User OS & Browser: Windows 10 Professional - Google Chrome
- Grafana plugins: - 
- Others: -

**Comment by mdvictor** [comment]
Hello!
I managed to reproduce and am looking into fixing it!

**Comment by leeoniya** [comment]
there is cache-busting bit of code that only works when the x values are strings, so we should convert any selected xField of type `number` to a `string` field.

https://github.com/grafana/grafana/blob/0b4af38bfa087967bebbac057e8e9f8375da9476/packages/grafana-ui/src/components/uPlot/Plot.tsx#L106-L112

alternatively, you can add a transformer that converts whatever numeric field you want for x to a string and the Bar chart panel will automatically pick it up without needing to select it manually.

![image](https://user-images.githubusercontent.com/43234/177621200-cf325c55-dc74-450e-baef-ad82ccb8ec58.png)

we'll have a patch soon.
