### ISSUE TITLE
[Bug] Cache Issue

### ISSUE THREAD

**Issue by mholttech** [grafana/grafana#4770]
* What grafana version are you using? 3.0
* What datasource are you using? Zabbix
* What OS are you running grafana on? Ubuntu 14.04

I've also filed this on the grafana-zabbix repo (https://github.com/alexanderzobnin/grafana-zabbix/issues/200) but I wanted to go ahead and post this here as well since it could be a Grafana issue

I'm seeing an issue with Caching and SingleStat Panels in Grafana 3.0. I have the same metric showing as a singlestat and as a graph, in this example it's memory usage in bytes.... Zabbix is currently reporting memory usage at 57.87GB, Grafana SingleStat is reporting 87.6 GiB, Grafana Graph is reporting 57.9GiB.

**Comment by torkelo** [comment]
Maybe you have not specified what value to show in singlestat (Avg, Max, Min, Current, Total), you can do that in Options tab.
