### ISSUE TITLE
Stats Panel -> calculation -> difference stop working upgrading from Grafana 7.5.5 to Grafana 8.4.5 on same OS and same DB

### ISSUE THREAD

**Issue by andreabisello** [grafana/grafana#47716]
**What happened**:

Calculation -> Differences stop working

**What you expected to happen**:

Same query should return same data so calculation -> differences should return same value

**How to reproduce it (as minimally and precisely as possible)**:

In Grafana 7.5.5 this query

```
SELECT
  now() as "time", 
  results as "value",
  cast(anno as CHAR) as 'metric'
FROM monitoring_conservazione_ambienti
WHERE
  missing_type='pda' AND anno=2021 AND company='2csolutionprod' AND ts BETWEEN FROM_UNIXTIME(1649840597) AND FROM_UNIXTIME(1649862197)

```
returns these data

![image](https://user-images.githubusercontent.com/2149815/163212145-bc4e8dec-30e2-49bc-9df4-9860520e3821.png)

and there are the correct one

![image](https://user-images.githubusercontent.com/2149815/163217631-75baebe8-6753-463e-8016-c372fbab2bdc.png)

so Calculate -> difference

evaluate -3918

![image](https://user-images.githubusercontent.com/2149815/163212400-cf1565e6-bd6e-4cdb-8d85-040775b5790b.png)

and this is true because first value is 5142 and latest values is 9060 and 5142-9060 is equal to -3918

but same query on same Panels on Grafana 8.4.5 returns a totally different data, with only 2 rows

![image](https://user-images.githubusercontent.com/2149815/163212943-0aaee532-9089-40cc-8ff6-aa37f4b3c9c9.png)

and calculation -> difference is zero.

As you can see,

this is the dashboard on Grafana 7.5.5

![image](https://user-images.githubusercontent.com/2149815/163214345-bb29fb3f-3c36-4a67-9340-5d21c8b83327.png)

and this is the same on Grafana 8.4.5

![image](https://user-images.githubusercontent.com/2149815/163215699-2edda74a-426f-4272-847a-2aa9affaf608.png)

every panel with calculation diff stop working.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana 7.5.5 Vs Grafana 8.4.5
- Data source type & version: same auroradb
- OS Grafana is installed on: ubuntu 20.04.2
- User OS & Browser: same windows, same chrome
- Grafana plugins: no
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @andreabisello 

> Data source type & version: same auroradb

can you link to the repo for this datasource? Are you using a third-party plugin? If so, it is possible that this is an issue with the datasource plugin codebase and not the Grafana OSS codebase...

**Comment by andreabisello** [comment]
@zuchka thanks. 
[auroradb ](https://aws.amazon.com/rds/aurora/)i s used as a standard mysql datasource
![image](https://user-images.githubusercontent.com/2149815/163326379-f5293e26-3a8a-4d0c-9a0f-7051fae6f2ef.png)

**Comment by zuchka** [comment]
@andreabisello could you provide steps for reproducing this using some sample data?

**Comment by andreabisello** [comment]
@zuchka ok thanks, i'll try.

in the zip attached i put

- empty_table.sql : is the sql dump of the empty table monitoring_conservazione_ambienti
- insert_data.sql : is the sql dump of the insert of the data of this issue (22 rows)
- grafana 7-5-5-panel.json : is the json of the panel in grafana 7.5.5
- grafana 8-4-5-panel.json : is the json of the panel in grafana 8.4.5

i cannot make this grafana public accessible, as i would, to make debug easily. i was thinking about creating a docker image with db and grafana istances, but i'm not authorized :(.

[issue-47716.zip](https://github.com/grafana/grafana/files/8494908/issue-47716.zip)

**Comment by zuchka** [comment]
Is it possible to reproduce this using dummy data? I'm just hoping to find the simplest method possible for the squads to reproduce this issue 👍

**Comment by andreabisello** [comment]
@zuchka i understand ... i don't know how to pass dummy data ... maybe with this? https://grafana.com/docs/grafana/latest/datasources/testdata/

**Comment by andreabisello** [comment]
@zuchka or maybe i can try the query with a temp table or something like this?

**Comment by andreabisello** [comment]
@zuchka we spot the difference.
the difference is that selecting now() i obtain only a row.
selecting the original timestamp column called "ts" i obtain all the rows, so the difference can be done.

this is the original way

![image](https://user-images.githubusercontent.com/2149815/164472772-7b9929bc-9fa7-492c-9ebe-3b868376ceef.png)

this is updating now() to ts.

![image](https://user-images.githubusercontent.com/2149815/164472635-d72bfb8a-b495-4f32-b01d-607c346d1255.png)

**Comment by andreabisello** [comment]
@zuchka 
the "problem" is this row

`cast(anno as CHAR) as 'metric'`

removing it, the data was not a single raw and the difference works.
