### ISSUE TITLE
[BUG] Graph cell are not align

### ISSUE THREAD

**Issue by max3163** [grafana/grafana#4772]
I can't explain this issue with words, so look at the picture to explain the problem :

![image](https://cloud.githubusercontent.com/assets/13835366/14667555/2ab4aaac-06e0-11e6-9523-3f7d0d4a6ee2.png)

* What grafana version are you using? 3.0 Beta6
* What datasource are you using? Influxdb
* What OS are you running grafana on? Linux

**Comment by sbengo** [comment]
Correct me if I'm wrong, but rows are made to contain panels whom can't exceed the maximum span (12). As first view you are using 3 panels with 6 of span each one.

If you don't want to set them on a new row (i.e ordered repeated row), there is a small trick that I use:
Create a "text panel" and move as to the 3rd panel position with:
· No text written on it
· Height: 1
· Transparent true
Set the span to 12 and you will create a blank space, a bit bigger than the padding between panels, but you won't have any glitch on it.

![graffiss](https://cloud.githubusercontent.com/assets/13196237/14678835/a4a8c56e-0717-11e6-82d4-0e0dd1532171.png)

**Comment by max3163** [comment]
Thanks for the trick.
I didn't have this behaviour with grafana 2.6 so for me it's a bug which could be fixed.

**Comment by torkelo** [comment]
strange, cant replicate on play.grafana.org,  
<img width="1195" alt="screen shot 2016-04-20 at 09 01 33" src="https://cloud.githubusercontent.com/assets/10999/14681580/8d1227d8-06d6-11e6-8c96-5174b2109fa6.png">

can you try describe some steps to replicate it there?

**Comment by sbengo** [comment]
Hi @torkelo,

To replicate:
http://play.grafana.org/dashboard/db/big-dashboard

Go to Row 2:
1. Duplicate "Server Request" panel, set span to 3
2. Duplicate again "Server Request" panel, set span to 5
3. Duplicate the last "Server Request" duplicated panel (with span 5, the 2nd step).


![grafanaissue](https://cloud.githubusercontent.com/assets/13196237/14688097/29d7349a-0741-11e6-9b9e-48eefa814855.jpg)

If you keep replicating the panel already duplicated (panel created on 2 or 3), it appears those panel on another subrow

Thanks for all

**Comment by torkelo** [comment]
That is  not the same case,  there you have a legend in non table mode that does not fit, and will push the panel to be higher than expected , for cases like that you need to change the legend to table mode

**Comment by max3163** [comment]
I attach you the export template which has this problem. 
I hope it will help you.

[Statistiques Influxdb-1461224344751.zip](https://github.com/grafana/grafana/files/229393/Statistiques.Influxdb-1461224344751.zip)

![image](https://cloud.githubusercontent.com/assets/13835366/14701340/37a885b0-07a5-11e6-85d7-885f35a94866.png)

**Comment by torkelo** [comment]
fixed in next nightly build. But you can fix it quickly yourself by placing your panels in separate rows :)
