### ISSUE TITLE
Pie chart labels cut off

### ISSUE THREAD

**Issue by Krinkle** [grafana/grafana#47735]
**What you expected to happen**:

That the label **a**pi_appserver is not cut-off.

**What happened**:

From: <https://grafana.wikimedia.org/d/000000438/mediawiki-exceptions-alerts>

| <img width="1178" alt="Screenshot 1" src="https://user-images.githubusercontent.com/156867/163251446-fba8ba6b-ccb5-48f4-b8ff-3d6cfb9b2c18.png"> | <img width="895" alt="Screenshot 2" src="https://user-images.githubusercontent.com/156867/163251482-ed72d209-bd51-461c-ac14-aaa09c9bdf4d.png">
|--|--
| <img width="451" alt="Screenshot 3" src="https://user-images.githubusercontent.com/156867/163251738-b83612ff-d4af-46e1-a0d1-c7f5bf329cb8.png"> | <img width="403" alt="Screenshot 4" src="https://user-images.githubusercontent.com/156867/163251589-e83cbf5f-b7ae-454d-923e-8cc0dc25c07d.png">

**How to reproduce it (as minimally and precisely as possible)**:

1. https://play.grafana.org/d/ktMs4D6Mk/5-bar-charts-and-pie-charts?orgId=1&editPanel=16
2. Change "Override 1" to be for "Github Stars", and set "Display name" to "Vue with a longer name".

<img width="1414" alt="Screenshot 5" src="https://user-images.githubusercontent.com/156867/163252021-52b172ce-d524-45c9-860f-f2125a504463.png">

**Anything else we need to know?**:

It appears the rendering is artifically constrained to a square, regardless of the width or available space for the panel in the dashboard layout (since it's allowed to be non-square). It is remains this way both in full-screen mode when viewing a single panel, and when editing it.

I suppose this could work so long as the labels are rendered such that they go inwards from the closest edge if their center-default position would have them exceed the invisible square. Possibly trimmed from the end using ellipsis like other parts of the interface do. Though it'd be great if it (also) used the available space when possible.

**Environment**:
- Grafana version: 8.3.6 (grafana.wikimedia.org) and also 8.5.0-beta1 (play.grafana.org).
- Browser: Firefox 98, macOS.

**Comment by mdvictor** [comment]
Hey @Krinkle ! A PR has been opened for this issue and should fix it by v9.5

**Comment by oscarkilhed** [comment]
@mdvictor thank you for picking up this one!
