### ISSUE TITLE
alerting: slack webhook alerted with a different state than seen in the dashboard

### ISSUE THREAD

**Issue by lclpsoz** [grafana/grafana#47733]
**What happened**:
The slack integration, that uses the Grafana webhook, notified a problem `Alerting`, but Grafana's dashboard marked as `OK`. And even after hours of the platform being stable, the OK status only came back after we forced the threshold to be low enough for a real `alerting` to occur.

![print-grafana-slack-bug](https://user-images.githubusercontent.com/19523324/163246728-5da64368-35c5-462f-9e1b-9db4385eb4a6.jpg)
![Screenshot from 2022-04-13 15-21-33](https://user-images.githubusercontent.com/19523324/163246732-30412c6e-30dd-4d9c-996a-e53f5433a3a1.png)
![print-grafana-until-now](https://user-images.githubusercontent.com/19523324/163246740-693c916b-112c-4fe5-9ebb-e254fcc03467.jpg)

**What you expected to happen**:
The webhook, used by the slack integration, to follow what is shown in the dashboard.

**How to reproduce it (as minimally and precisely as possible)**:
It's an Grafana automation/integration, don't know how to replicate.

**Anything else we need to know?**:
Notice how the value was very close to the threshold: `120.03832816886` vs `120`
Maybe the problem is related to that.

**Environment**:
- Grafana version: v8.4.0
- Data source type & version: NA
- OS Grafana is installed on: NA
- User OS & Browser: Ubuntu 20.04.4 LTS & Chrome 100.0.4896.60 (Official Build) (64-bit)
- Grafana plugins: NA
- Others: NA

**Comment by mellieA** [comment]
@lclpsoz can you share more information about the alert and the data that it's reporting on: 

* show us the alert definition
* share the results from query inspector's data tab at the time that the notification was triggered
* based on your alert condition, what behavior did you expect to see?

**Comment by lclpsoz** [comment]
### Alert definition:
![image](https://user-images.githubusercontent.com/19523324/163463045-0bb700a6-7e6b-4637-b40d-2f2ef779c6ae.png)
![image](https://user-images.githubusercontent.com/19523324/163464859-a7d47916-11a3-4b94-bca0-5139cbca5c97.png)
`sum(irate(replication_source_delay_seconds_sum{status="success", table=~"dispatch_package|dispatch_task|dispatch_packagestatus|wms_sortingrecord|wms_packageinunitload"}[2m])) by (table) / sum(irate(replication_source_delay_seconds_count{status="success", table=~"dispatch_package|dispatch_task|dispatch_packagestatus|wms_sortingrecord|wms_packageinunitload"}[2m])) by (table)`

### Files from inspection from 10:45 to 11:05
[Formatted csv](https://pastebin.com/auGArjB2)
[Raw csv](https://pastebin.com/pDh6cH9z)
[Query inspect JSON](https://pastebin.com/QWDJDm3P)

I expected the alert on Slack to be with OK status, or no alert to be sent, since the average didn't go over 120, at least based on the Dashboard info on 11:00:07, seen in my second screenshot in this issue description.

The problem is the difference in status on the dashboard and on the webhook.

**Comment by alexweav** [comment]
Hello :wave: have you tried the new Unified alerting? Does this issue still reproduce with the same query?

**Comment by armandgrillet** [comment]
Closing this as we got no answer for 4 weeks, please reopen if you can reproduce this with Grafana Alerting.
