### ISSUE TITLE
Inability to sign out when using auth.proxy

### ISSUE THREAD

**Issue by mathewcrane** [grafana/grafana#4775]
Hello,

I am using auth.proxy with an external Authz/Authn configuration. I'm able to authenticate correctly, but there is some strange behavior with Grafana.

Is there any way to force httpd to unset the X-WEBAUTH-USER header when a user signs out? 
Does nginx play nicer with this config?

I have to manually clear my cache in order to log off. Additionally, 'Sign Out' redirects to /login, which isn't able to be used in a auth.proxy config.

grafana-3.0.0-beta51460725904.x86_64
graphite-api
CentOS 7, using httpd

grafana configuration:
basic auth disabled
proxy auth enabled, auto login enabled

httpd configuration:

```
 <VirtualHost *:443>
  LogLevel debug
  ServerName server

  SSLEngine On
  ProxyRequests Off

  SSLCertificateFile /etc/pki/tls/certs/server.crt
  SSLCertificateKeyFile /etc/pki/tls/private/server.key
  SSLCertificateChainFile /etc/pki/tls/private/server.csr
  
  # only allow TLSv1.2
  SSLProtocol -ALL +TLSv1.2
  SSLCipherSuite HIGH:!aNULL:!eNULL:!MEDIUM:!LOW:!MD5:!3DES:!RC4:!EXP:!PSK:!SRP:!DSS

  <Proxy *>

    AuthType Basic
    AuthName "Grafana Server"
    AuthBasicProvider ldap

    AuthLDAPBindAuthoritative Off
    AuthLDAPBindDN bindDN
    AuthLDAPBindPassword authtok
    AuthLDAPURL "ldaps URI"
    Require ldap-group "ldap group DN"

    RewriteEngine On
    RewriteRule . - [E=PROXY_USER:%{LA-U:REMOTE_USER},NS]
    RequestHeader set X-WEBAUTH-USER "%{PROXY_USER}e"

  </Proxy>

  RequestHeader unset Authorization

  ProxyPass / http://localhost:3000/
  ProxyPassReverse / http://localhost:3000/

</VirtualHost>
```

**Comment by torkelo** [comment]
You cant sign out when using auth proxy from grafana, you need to sign out with the system that acts as  the auth, apache in your case.

**Comment by mathewcrane** [comment]
Thanks. Should /login still be available?

**Comment by torkelo** [comment]
you should not be redirected to it when go to /,  but if you go it manually you wont be redirected away
