### ISSUE TITLE
Table panel crashes upon choosing JSON View cell display mode

### ISSUE THREAD

**Issue by semekh** [grafana/grafana#47754]
**What happened**:
Looks like the JSON View cell display mode crashes upon rendering most input data.

**What you expected to happen**:
It should not crash.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a Table panel
- Use Direct Input datasource and feed it the following data:
```
x,y
1,"{""a"":""b""}"
```
- Add a new override for field name `y` and set its Cell display mode to `JSON View`
- The panel crashes although everything should be working fine.

**Anything else we need to know?**:
This used to work before. I suspect it started crashing after a recent upgrade.

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Any, Direct Input used as an example
- OS Grafana is installed on: Alpine Linux 3.15 (Docker)
- User OS & Browser: Linux, Chrome
- Grafana plugins: N/A

**Comment by semekh** [comment]
Downgrading to 8.4.4 fixes the issue, and upgrading to 8.4.5 reintroduces it.

**Comment by mellieA** [comment]
@semekh can you verify these are the steps to reproduce: 

- Create a table panel
- Use the **Test DataDB** datasource, choose **CSV Content** and add the following input: 
```
x,y
1,"{""a"":""b""}"
```
- Add a new override for field name `y` and set the **Cell display mode** to **JSON View**
- Observe the react error: 

>Objects are not valid as a React child (found: object with keys {a}). If you meant to render a collection of children, use an array instead.

I tested these same steps on 8.3.3 and confirmed that it does not error and produces the table below: 

![Screen Shot 2022-04-14 at 1 53 16 PM](https://user-images.githubusercontent.com/18175287/163465766-fc8c5ee1-9ac9-40d9-8555-39ef1401817a.png)

**Comment by semekh** [comment]
@mellieA Correct. That is exactly what is happening.

**Comment by semekh** [comment]
Closing as this seems to be fixed in 8.5.0
