### ISSUE TITLE
Cannot authenticate Grafana using LDAP 

### ISSUE THREAD

**Issue by sksegha** [grafana/grafana#4776]
I am currently running Grafana 2.6.3, with a NetApp HArvest which works excellently well with no issues which runs on RHEL 6.7

I have been trying to authenticate using LDAP/Active directory and i have not made any head way 

Here is my ldap.toml file below 

# Ldap server host
host= "XX.XXX.XXX.XX"
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if ldap server supports TLS
use_ssl = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = true

# Search user bind dn
bind_dn = "cn=userid,dc=i,dc=example,dc=com"
# Search user bind password
bind_password = 'password'

# Search filter, for example "(cn=%s)" or "(sAMAccountName=%s)"
search_filter = "(cn=%s,dc=i,dc=example,dc=com)"
# An array of base dns to search through
search_base_dns = ["OU=USERS,OU=CORP,dc=i,dc=example,dc=com"]

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "OU=GROUPS,OU=AFI INFRASTRUCTURE,dc=i,dc=example,dc=com"
org_role = "Admin"
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"

also my grafana.ini file 

#################################### Basic Auth ##########################
[auth.basic]
;enabled = true

#################################### Auth LDAP ##########################
[auth.ldap]
enabled = true
;config_file = /etc/grafana/ldap.toml

here is what i see in my var/log/grafana

2016/04/20 13:32:41 [I] Database: sqlite3
2016/04/20 13:32:41 [I] Migrator: Starting DB migration
2016/04/20 13:32:41 [I] Login: Ldap enabled, reading config file: /etc/grafana/ldap.toml
2016/04/20 13:32:41 [I] Listen: https://0.0.0.0:443
2016/04/20 13:45:26 [I] LDAP initial bind failed, LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1
2016/04/20 13:45:26 [login.go:99 LoginPost()] [E] Invalid username or password: Invalid Username or Password
2016/04/20 13:45:26 [I] Completed 10.145.204.181 - "POST /login HTTP/1.1" 401 Unauthorized 42 bytes in 2152826us
2016/04/20 13:45:26 [I] Completed 10.145.204.181 - "GET /api/login/ping HTTP/1.1" 401 Unauthorized 26 bytes in 412us

here is my ldap.conf file 

# This file should be world readable but not world writable.

#BASE   dc=i,dc=example,dc=com
#URI    ldap://ldapserver.i.example.com

#SIZELIMIT      12
#TIMELIMIT      15
#DEREF          never

TLS_CACERTDIR /etc/openldap/cacerts
URI ldap://ldapserver.i.example.com ldap://--enablesssd/
BASE dc=i,dc=example,dc=com

my userID and password is definitely correct, kindly assist.

**Comment by torkelo** [comment]
must be something wrong with you bind_password or bind_dn , maybe pose a question to the mailing list, maybe someone that can help, not sure what could be wrong with your config.

**Comment by wujianhua0427** [comment]
I have also encountered the same question, can I help me, thank you

**Comment by azavrin** [comment]
I searched google inside out, i did not find a single successful LDAP binding config yet.
Is there an example of a working config against MS AD?

**Comment by yuriomae** [comment]
> I searched google inside out, i did not find a single successful LDAP binding config yet.
> Is there an example of a working config against MS AD?

@azavrin 

Can you solve it?

I am having the same problem presented in grafana log ("Initial bind failed" logger = ldap error = "LDAP Result Code 49 \" Invalid Credentials \ ")

**Comment by azavrin** [comment]
@yuriomae - here the config that works for me - ldap.toml:
# To troubleshoot and get more log info enable ldap debug logging in grafana.ini
# [log]
# filters = ldap:debug

[[servers]]
# Ldap server host (specify multiple hosts space separated)
host = "127.0.0.1"
# Default port is 389 or 636 if use_ssl = true
port = 389
# Set to true if ldap server supports TLS
use_ssl = false
# Set to true if connect ldap server with STARTTLS pattern (create connection in insecure, then upgrade to secure connection with TLS)
start_tls = false
# set to true if you want to skip ssl cert validation
ssl_skip_verify = false
# set to the path to your root CA certificate or leave unset to use system defaults
# root_ca_cert = "/path/to/certificate.crt"
# Authentication against LDAP servers requiring client certificates
# client_cert = "/path/to/client.crt"
# client_key = "/path/to/client.key"

# Search user bind dn
bind_dn = "cn=admin,dc=grafana,dc=org"
# Search user bind password
# If the password contains # or ; you have to wrap it with triple quotes. Ex """#password;"""
bind_password = 'your-password'

# User search filter, for example "(cn=%s)" or "(sAMAccountName=%s)" or "(uid=%s)"
search_filter = "(cn=%s)"

# An array of base dns to search through
search_base_dns = ["dc=grafana,dc=org"]

## For Posix or LDAP setups that does not support member_of attribute you can define the below settings
## Please check grafana LDAP docs for examples
# group_search_filter = "(&(objectClass=posixGroup)(memberUid=%s))"
# group_search_base_dns = ["ou=groups,dc=grafana,dc=org"]
# group_search_filter_user_attribute = "uid"

# Specify names of the ldap attributes your ldap uses
[servers.attributes]
name = "givenName"
surname = "sn"
username = "cn"
member_of = "memberOf"
email =  "email"

# Map ldap groups to grafana org roles
[[servers.group_mappings]]
group_dn = "cn=admins,dc=grafana,dc=org"
org_role = "Admin"
# To make user an instance admin  (Grafana Admin) uncomment line below
# grafana_admin = true
# The Grafana organization database id, optional, if left out the default org (id 1) will be used
# org_id = 1

[[servers.group_mappings]]
group_dn = "cn=users,dc=grafana,dc=org"
org_role = "Editor"

[[servers.group_mappings]]
# If you want to match all (or no ldap groups) then you can use wildcard
group_dn = "*"
org_role = "Viewer"
=================
In the grafana.ini file section looks like this:
#################################### Auth LDAP ###########################
[auth.ldap]
enabled = false
config_file = /etc/grafana/ldap.toml
allow_sign_up = true

**Comment by DAx-cGn** [comment]
@azavrin - how could your config possibly work vs any LDAP with the "[auth.ldap] enabled = false" in it?
