### ISSUE TITLE
Missing database field when adding InfluxDB datasource

### ISSUE THREAD

**Issue by anderskvist** [grafana/grafana#4777]
Grafana 3.0.0-beta61461050660
InfluxDB 0.12

Grafana is missing database field in the web interface when adding a InfluxDB datasource. I tried many times to add a datasource, but it didn't work. When I added it manuallay with the same query, but added a database field as well, everything just worked...

**Comment by bergquist** [comment]
I cannot reproduce this in master
![image](https://cloud.githubusercontent.com/assets/618863/14703088/442d7396-07ae-11e6-92ff-2c62fedfecdd.png)

**Comment by anderskvist** [comment]
Hm, I just installed todays nightly build (3.0.0-beta61461227773) and it's still not there - must be very recent or not included in the nightly builds?

![screenshot from 2016-04-21 11 02 26](https://cloud.githubusercontent.com/assets/8784074/14703607/f4959c3e-07b0-11e6-9a7c-f17e87f6c455.png)

And the "Edit data source" doesn't look like yours as well...

![screenshot from 2016-04-21 11 06 47](https://cloud.githubusercontent.com/assets/8784074/14703671/6eb9b40a-07b1-11e6-8a05-a47d34a55a28.png)

But giving that you have all the fields in your screenshot, I take it will get into 3.0 eventually :)

**Comment by bergquist** [comment]
A new nightly build should be released soon :)

**Comment by torkelo** [comment]
@bergquist did you find the cause for this issue? See no linked commit , just wondering what it could be :)

**Comment by bergquist** [comment]
@torkelo Nope. Didn't investigate.

**Comment by torkelo** [comment]
> A new nightly build should be released soon :)

Ah, got confused, sounded like you had made a fix :)

**Comment by anderskvist** [comment]
I tried installing yet an other daily build and still have the correct InfluxDB settings. I found this - is it the master branch that is being released as the nightly builds?

![screenshot from 2016-04-24 23-29-43](https://cloud.githubusercontent.com/assets/8784074/14770541/863e2abe-0a74-11e6-8882-ada8d0bb843c.png)

**Comment by bergquist** [comment]
@anderskvist weird! If you enable developer console (ctrl + shift + i) in chrome. Do you get any error in the console tab?

**Comment by anderskvist** [comment]
@bergquist That pointed me to the fix! I run both grafana and influxdb through a nginx, on the same hostname, where I had a regex match on /influxdb for the influxdb proxy - which resulted in that plugin query were sent to influx and not grafana. A ^ solved it - many thanks and sorry for the inconvenience! :)

**Comment by bergquist** [comment]
@anderskvist np! :)
