### ISSUE TITLE
[Bug] snapshot.raintank.io is not compatible with data posted by Grafana 2.6

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4778]
There is a change in the json of the dashboard params passed to snapshot.raintaink.io by the local grafana server between 2.6 and 3.0:

![image](https://cloud.githubusercontent.com/assets/917241/14700161/cba62090-079d-11e6-862c-a47d65cbf849.png)

The lack of the name parameter is causing snapshot.raintank.io to return a 422 error.  

If I modify the json posted by the 2.6 instance to include a name:"value" parameter then snapshot.raintank.io accepts it properly.

Issue request is for snapshot.raintaink.io to accept json in the format sent by a 2.6 server to provide backward compatibility.

**Comment by bergquist** [comment]
@dutchiechris thank you for reporting this!

This changed at https://github.com/grafana/grafana/commit/41fd0ed46712b1fb820750be4a819c05c851ebd8 

I think we should have a default value name instead of breaking the contract.
