### ISSUE TITLE
Strange anchor behaviour in html

### ISSUE THREAD

**Issue by aptakhin** [grafana/grafana#47799]
Hello!

A add the Text block in Grafana dashboard with url `https://SOME_URL/d/SOME_UID/...` and html with anchor below:

```html
<a href="#tag">link</a>

<a name="tag"></a>
```

When I click the link on saved dashboard.

**What happened**:

Grafana opens page at origin home root `https://SOME_URL?orgId=1`
Without anchor and dashboard content. 

**What you expected to happen**:

Grafana remains on same dashboard page and scroll to anchor #tag (if it's exists).

**How to reproduce it (as minimally and precisely as possible)**:

Easily reproduced with Text block at https://play.grafana.org/d/000000012/grafana-play-home?orgId=1

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.1
- Data source type & version: seems doesn't matter
- OS Grafana is installed on: Ubuntu
- User OS & Browser: Mac OS & Google Chrome Version 100.0.4896.88 (Official Build) (x86_64)
- Grafana plugins: `vertamedia-clickhouse-datasource 2.4.4,grafana-worldmap-panel,flant-statusmap-panel,natel-plotly-panel,citilogics-geoloop-panel,jdbranham-diagram-panel,grafana-piechart-panel,briangann-datatable-panel`
- Others (in config):
```
disable_sanitize_html = true
```

update1. Captured some gif on play.grafana. It redirects to original dashboard, but through root and without anchor tag
![CleanShot2022-04-15at06 46 32](https://user-images.githubusercontent.com/186950/163532844-18336cdd-bdfd-4596-a9a1-b1d77cd918b2.gif)

**Comment by joshhunt** [comment]
Grafana has some logic that tries to determine how to correctly route links to external websites vs in-app links. It looks like that logic is incorrect here.
