### ISSUE TITLE
[Feature Request] User Authentication via SAML

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4780]
LDAP works great !!! But there will be a need for SAML support in Grafana for Authenticators like OKTA. A lot of big organizations uses OKTA for user authentication using SAML. If Grafana can support SAML and can be integrated with OKTA, it would be great.

**Comment by Dual-Boot** [comment]
Sure it will be great, but very hard to implement.

**Comment by torkelo** [comment]
you could use SAML nginx/apache modules and use grafana auth proxy feature

**Comment by abraae** [comment]
Handling SAML in a proxy in front of grafana is surely the way to go. SAML can be a real pain.

For apache, apache mod_auth_mellon is a simple SAML SP that appears to be well maintained.

For nginx, some time ago we looked for, but did not find, a useful SAML module. It is possible to use lua and offload the SAML work to a separate app (e.g. a Java app with Spring SAML security) but this is not for the faint hearted.

**Comment by iMartyn** [comment]
A proxy doesn't exactly work for a lot of purposes - our scenario for example :
* TVs around the business displaying read-only access to grafana (no login)
* Users updating those dasboards need to be authenticated.
* Same network, same address, but auth has to be only for editing, therefore auth has to be native, not just allow/deny.

So +1 for SAML as an auth backend.

**Comment by mattttt** [comment]
This came up in two separate conversations today 👍

**Comment by abraae** [comment]
I found that grafana's Auth proxy functionality works pretty well.

SAML authentication can be handled via a separate web app. For SAML, the web app could be Java, with Spring Security SAML. This authentication app then handles the complexity of SAML, and mediates access to grafana via auth proxy.

This seems to work well for us, and it keeps complexity out of grafana.

In our case we also want to protect against the grafana user issuing malicious queries.

i.e. even if we know who it is who is logged in, we still don't trust them with the unrestricted query access  that grafana basically provides.

So we also intercept all grafana database traffic and inject additional filters into the where clauses.

That is fiddly for sure, but that's just the sort of requirement that might pop  up immediately after adding SAML to grafana.

**Comment by zpol** [comment]
@abraae  do you know where to find some documentation about how to configure mod_auth_mellon with grafana ? I tried, I get redirected to Okta's web page, I can authenticate against Okta and then I'm redirected to Grafana but it complains about this: 
`[{"fieldNames":["User"],"classification":"RequiredError","message":"Required"},{"fieldNames":["Password"],"classification":"RequiredError","message":"Required"}]`

I'm not sure about what I'm doing wrong. 
Some tip? 
Thanks in advance.

**Comment by abraae** [comment]
Sorry, have not used mod_auth_mellon so can't help. We ended up using grafana Auth proxy (https://grafana.com/blog/2015/12/07/grafana-authproxy-have-it-your-way/), and nginx.

nginx intercepts any unauthorized requests and redirects them to a Java/Spring app. That app in turn is protected using whatever you want - for SAML, it could be spring-security-saml.

If its helpful here are some salient lines from the nginx config (grafana is part of a larger app, so grafana lives under /g/):

````
# the grafana, set up as per https://github.com/grafana/grafana/issues/2066 
location /g/ {
        auth_request /auth;
        # the auth service returns user's email in a response header
        auth_request_set $email $upstream_http_x_app_email;
# add_header X-debug-email "$email" always;
		# and we pass it on to grafana
    	proxy_set_header x-app-email $email;    
        proxy_pass http://g.int.app.com:3000/;
}

# auth is done against the spring app's API
location = /auth {
    proxy_pass http://spring.int.app.com:8080/api/authCheck/hard;
    proxy_pass_request_body off;
    proxy_set_header Content-Length "";
    proxy_set_header X-Original-URI $request_uri;
}
````

**Comment by moogjet** [comment]
This feature would be great. Any news or rough timescale for this?

**Comment by zhang2kai** [comment]
Is there any new ideals about tihis?

**Comment by PXMYH** [comment]
@abraae how did you deal with Authentication header issue sent to Grafana backend? I'm trying to use the same set up (Nginx + Authproxy), but even if I set Authentication header to nothing (`proxy_set_header Authorization ""`) so no auth request is sent to backend Grafana, I still get `Invalid API key` error back:
```
t=2019-05-08T03:01:00+0000 lvl=eror msg="Invalid API key" logger=context error="Invalid Api Key"
t=2019-05-08T03:01:00+0000 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/ status=401 remote_addr=10.166.34.167 time_ms=0 size=29 referer="<my sso app>"```

I was basically following advice @torkelo gave on https://github.com/grafana/grafana/issues/7090#issuecomment-269484930
