### ISSUE TITLE
CloudWatch Logs: Explore did not return a visualization with returned data

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#47815]
**What happened**:
The following query in Explore of CloudWatch Logs has data but displays "nothing":
![Screen Shot 2022-04-15 at 11 44 25](https://user-images.githubusercontent.com/4163034/163555929-440ec67c-974d-4ca3-95cf-788008311b46.png)

I do observe the data values in the Explore query inspector:
![Screen Shot 2022-04-15 at 12 00 02](https://user-images.githubusercontent.com/4163034/163557649-0b092aa9-f3ae-487c-bbae-32afde114894.png)

**What you expected to happen**:
The visualization should not say "No logs found." 
The same query in AWS Logs Insights displays:
![Screen Shot 2022-04-15 at 13 27 19](https://user-images.githubusercontent.com/4163034/163578596-e16c2a10-a872-4d13-995e-2263ac04707d.png)

**Anything else we need to know?:**
Might have missed something obvious here, sorry if that's the case.

Grafana v8.4.5
And just confirmed the same on ~main Grafana v9.0.0-pre

**Comment by yaelleC** [comment]
Hi @grafana/observability-experience-squad would you mind 👀  this issue. 
Any reason why logs that are shown in the `Data` tab of the query inspector would not be shown in the explore view?

**Comment by yaelleC** [comment]
Actually, looking more into that it does not seem to be an inconsistency between explore and panel views.
If you set the visualisation to `Logs` you would not get any data displayed in a panel either (see below) , the only way to see anything is a `table` . 

![Screenshot 2022-04-15 at 12 44 59](https://user-images.githubusercontent.com/42030685/163562143-34150caa-c229-432e-836e-7627425d41d9.png)

**Comment by fridgepoet** [comment]
Thanks @yaelleC, I've edited the description.
It's probably better to say that I would expect the visualization in Explore to:
* return something (for example similar to a table panel in Grafana)
* return something similar to the AWS CloudWatch Logs Insights visualization (screenshot has been updated)

Currently it looks like nothing with "No logs found."

**Comment by ifrost** [comment]
It looks like a data source-specific problem, not Explore. @grafana/observability-logs-and-traces is it something you could have a look at?

**Comment by andresmgot** [comment]
I don't think this is an issue. By default, the Cloudwatch logs plugin sets the preferred visualization to "Logs":

https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/live.go#L27

This is used by the Explore view to automatically set a panel visualization. The Logs panel requires at least a timestamp and another field (I believe a string) so if your query only return timestamps it's not a valid Logs query.

**Comment by fridgepoet** [comment]
Gotcha, thanks for having a look
