### ISSUE TITLE
Wrong message template  using in contact point with type opsgenie (unified alerting).

### ISSUE THREAD

**Issue by enikioy** [grafana/grafana#47813]
**What happened**: Opsgenie receive message from Grafana formatted by default template "default.message"

**What you expected to happen**: Message would be formatted by template "opsgenie.default.description"

**How to reproduce it (as minimally and precisely as possible)**: Create contact point with type opsgenie and use it by default. Create any triggered alert and view result message in Opsgenie.

**Anything else we need to know?**: Used unified alerting.

**Environment**:
- Grafana version: v8.4.5
- User OS & Browser:  Windows 10 Enterprise build19044.1586 & Chrome Version 100.0.4896.75 
- Others: Docker v20.10.12

**Comment by masterlittle** [comment]
Facing the same issue. Can this be fixed in the next release and have template as a custom field?

**Comment by muravsky** [comment]
Same issue. Can't use Grafana Unified alerting with opsgenie as it is right now. 
Please fix.

**Comment by andrzejressel** [comment]
From what I understand from researching Grafana cloud you must have external alertmanager for it. With it additional options like setting own templates are unlocked:

![image](https://user-images.githubusercontent.com/1307829/166841183-c0ef15ec-e062-4fca-8776-78f418c7290c.png)

**Comment by yuri-tceretian** [comment]
In Grafana we use custom notifiers that are not Alertmanager's. However, I agree that we should let users change the format of the message. The quick win could be adding a field so users can specify a custom template.

**Comment by muravsky** [comment]
Any ability to change message format - would be a game changer. Just having same 2 fields, where we could specify template, as already available for Slack would be awesome.

**Comment by topolmaxim** [comment]
Same issue

**Comment by hazmei** [comment]
Same issue

**Comment by santihernandezc** [comment]
@enikioy just FYI, I just opened a [PR](https://github.com/grafana/grafana/pull/50131) to customize the title and description for OpsGenie notifications. I think this will solve your issue.

**Comment by santihernandezc** [comment]
@enikioy the PR has been merged and it's going to be part of v9.0.1.
I'm closing this, feel free to reopen if your issue is still not solved!

**Comment by lgounot** [comment]
@santihernandezc Issue has not been included in v9.0.1.
Do you know when it would be released ?

**Comment by josefzahner** [comment]
It's included into v9.0.2. I've tested it
