### ISSUE TITLE
[Bug] multiple values template variable not working with influxdb

### ISSUE THREAD

**Issue by RoadRunnr** [grafana/grafana#4783]
Grafana 3.0.0-beta51460725904, on Ubuntu Xenial

This is similar to #2555, but not the same issue.

Two template queries:

```
$Host	SHOW TAG VALUES WITH KEY = "host" WHERE type = 'snmp'
$Interface	SHOW TAG VALUES WITH KEY = "column" WHERE type = 'snmp' AND host = "$Host"
```

No matter what I do, the second query always throws errors:

```
Template variables could not be initialized: error parsing query: found \., expected identifier, string, number, bool at line 1, char 73
```

I tried the host argument with single quotes, with double quotes and without quotes.

The issue seems to be, that the first queries returns an IP address: "192.168.1.1". This would explain the error that complains about the DOT (\.).

**Comment by torkelo** [comment]
You need to use regex operator in the where filter for the second variable

**Comment by RoadRunnr** [comment]
argh, after more trials and errors, I found that it works with:

```
SHOW TAG VALUES WITH KEY = "column" WHERE type = 'snmp' AND host =~ /$Host/
```

Why is it so hard to find that information?
