### ISSUE TITLE
Grafana Docker - no ARM image

### ISSUE THREAD

**Issue by himuura** [grafana/grafana#47833]
**What happened**:
Deployed a new version of grafana (8.4.6) on Rasp Pi 4 (with docker)
**What you expected to happen**:
I expected to upgrade grafana to v.8.4.6 like with my ubuntu server...
**How to reproduce it (as minimally and precisely as possible)**:
Portainer or docker-compose, try to download the new grafana image and start the container...
**Anything else we need to know?**:
Yes, this is the error after downloading the new docker image: standard_init_linux.go:228: exec user process caused: exec format error

**Environment**:
- Grafana version: 8.4.5
- Data source type & version: Not important
- OS Grafana is installed on: Rasp OS 64 Bit
- User OS & Browser: Not important
- Grafana plugins: Not important
- Others: Docker version 20.10.14, build a224086 / Portainer 2.11.1

I think the ARM image has no candidate, hence the error. Should be pretty simple to fix, i'm guessing.

**Comment by vdbrink** [comment]
Same here

**Comment by himuura** [comment]
Solved in 8.5.0. The issue does not persist. It can be closed.
