### ISSUE TITLE
grafana-cli plugins ls only shows restart grafana message when invoked

### ISSUE THREAD

**Issue by samuraii78** [grafana/grafana#47835]
**What happened**:
When invoking ```grafana-cli plugins ls``` the only output gotten is ```"Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary."```

**What you expected to happen**:
Get a list of installed plugins

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Plugins directory is set to default in grafana.ini. No overrides

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Prometheus version 2.15.2+ds (branch: debian/sid, revision: 2.15.2+ds-2)
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows 10 - Chrome
- Grafana plugins: grafana-image-renderer
- Others:

**Comment by mellieA** [comment]
@samuraii78 I tried this and saw something similar until I installed a plugin. 

Do you see any messages in `/var/log/grafana/grafana.log` about the plugins directory? 
Have you installed plugins beyond the bundled ones? Once I installed a plugin I see it listed

**Comment by samuraii78** [comment]
@mellieA thanks for the reply. I had installed Grafana Image Renderer but i guess since the version of Grafana i use doesn't require this plugin anymore it was not activated a therefore when listing plugins i ran into the issue.

**Comment by jsoref** [comment]
So, in short, the reporter is correct, `grafana-cli plugins <any-valid command>` will unconditionally show `Please restart Grafana after installing plugins. Refer to Grafana documentation for instructions if necessary.` (unless there's an error):
https://github.com/grafana/grafana/blob/38809d73c246a75d0892ee9754c5737b38ac67a4/pkg/cmd/grafana-cli/commands/commands.go#L91-L98

Problems (in no particularly order):
* It's often useful to be told _I understand you asked for a list of things, there aren't any_
* If one uses the gui to list plugins, there are ~`41` which is a lot more than `0`
* Being told about a restart grafana when one hasn't installed anything (in my case, i did an extra restart of grafana just to figure out what's going on) is definitely misleading
* In my case (kubernetes), there's no `/var/log/grafana/grafana.log`

**Comment by mckn** [comment]
Seems either like a bug in the CLI or in the help output

<img width="593" alt="Skärmavbild 2023-02-02 kl  14 49 17" src="https://user-images.githubusercontent.com/172951/216342482-31e30477-f67b-452c-ae04-76ab97dd4634.png">
