### ISSUE TITLE
Not saves options in dashboard JSON Model 

### ISSUE THREAD

**Issue by kirill-khalevin-lt** [grafana/grafana#47838]
Hello everyone!

**I want to setup display_name for values of variable
But I can't save JSON Model.**

Before save:

<img width="863" alt="Screenshot 2022-04-17 at 18 19 50" src="https://user-images.githubusercontent.com/91889953/163720969-773fe8f3-6159-4f1f-8afe-93cf69e552c1.png">

After save, options is empty:
<img width="905" alt="Screenshot 2022-04-17 at 18 21 25" src="https://user-images.githubusercontent.com/91889953/163721017-e1aa0186-ac97-4e85-a105-25bdb64d0465.png">

**Comment by mellieA** [comment]
@kirill-khalevin-lt we haven't heard from you since @joshhunt explained how display labels should be changed. I'll close this issue for now, feel free to reopen with more information if we've misunderstood your request.
