### ISSUE TITLE
Threshold colors not loading properly

### ISSUE THREAD

**Issue by Amreeshbaskar** [grafana/grafana#47844]
What happened:
The Bargraph is set up for mysql Table, Threshold color is setup. The color are working properly at the time of dashboard loading and once any variable changes at dashboard top and bar graph values are changed the threshold colors are not working properly.
The dashboard is setup to reload every 5s. also tried with overide property, same issue exist.

The threshold color setup like this base red,>70 yellow,>90 Green
Graph at time of loading of dashboard
![s1](https://user-images.githubusercontent.com/42416179/163776391-1687123c-c334-468c-a26d-717c52514bd7.PNG)

Graph showing incorrect threshold colors when variables and values are changed
![s2](https://user-images.githubusercontent.com/42416179/163776433-32c97bd4-e14a-4113-8e2e-a53794ee39cc.PNG)

What you expected to happen:
The threshold color needs to be changed when the values of the graph changes in the dynamic dashboards

How to reproduce it (as minimally and precisely as possible):

Anything else we need to know?:

Environment:

Grafana version: 8.4.5
Data source type & version: MySQL 8.0.28
OS Grafana is installed on: Windows
User OS & Browser: Chrome
Grafana plugins: Mysql

<details>
<summary>Dashboard JSON</summary>

```json
{
"__inputs": [
{
"name": "DS_MYSQL-2",
"label": "MySQL-2",
"description": "",
"type": "datasource",
"pluginId": "mysql",
"pluginName": "MySQL"
}
],
"__elements": [],
"__requires": [
{
"type": "panel",
"id": "barchart",
"name": "Bar chart",
"version": ""
},
{
"type": "grafana",
"id": "grafana",
"name": "Grafana",
"version": "8.4.5"
},
{
"type": "datasource",
"id": "mysql",
"name": "MySQL",
"version": "1.0.0"
}
],
"annotations": {
"list": [
{
"builtIn": 1,
"datasource": "-- Grafana --",
"enable": true,
"hide": true,
"iconColor": "rgba(0, 211, 255, 1)",
"name": "Annotations & Alerts",
"target": {
"limit": 100,
"matchAny": false,
"tags": [],
"type": "dashboard"
},
"type": "dashboard"
}
]
},
"editable": true,
"fiscalYearStartMonth": 0,
"graphTooltip": 0,
"id": null,
"iteration": 1649330492339,
"links": [],
"liveNow": false,
"panels": [
{
"datasource": {
"type": "mysql",
"uid": "${DS_MYSQL-2}"
},
"fieldConfig": {
"defaults": {
"color": {
"mode": "thresholds"
},
"custom": {
"axisLabel": "",
"axisPlacement": "auto",
"axisSoftMin": 0,
"fillOpacity": 80,
"gradientMode": "none",
"hideFrom": {
"legend": false,
"tooltip": false,
"viz": false
},
"lineWidth": 1,
"scaleDistribution": {
"type": "linear"
}
},
"mappings": [],
"thresholds": {
"mode": "absolute",
"steps": [
{
"color": "semi-dark-red",
"value": null
},
{
"color": "semi-dark-yellow",
"value": 70
},
{
"color": "semi-dark-green",
"value": 90
}
]
},
"unit": "short"
},
"overrides": []
},
"gridPos": {
"h": 9,
"w": 12,
"x": 0,
"y": 0
},
"id": 2,
"options": {
"barRadius": 0,
"barWidth": 0.97,
"colorByField": "value",
"groupWidth": 0.7,
"legend": {
"calcs": [],
"displayMode": "hidden",
"placement": "right"
},
"orientation": "auto",
"showValue": "always",
"stacking": "none",
"text": {
"valueSize": 14
},
"tooltip": {
"mode": "single",
"sort": "none"
},
"xTickLabelRotation": 0,
"xTickLabelSpacing": 0
},
"pluginVersion": "8.4.5",
"targets": [
{
"datasource": {
"type": "mysql",
"uid": "${DS_MYSQL-2}"
},
"format": "table",
"group": [],
"metricColumn": "none",
"rawQuery": true,
"rawSql": "select * from sample where f1='$f1';",
"refId": "A",
"select": [
[
{
"params": [
"value"
],
"type": "column"
}
]
],
"timeColumn": "time",
"where": [
{
"name": "$__timeFilter",
"params": [],
"type": "macro"
}
]
}
],
"title": "Panel Title",
"type": "barchart"
}
],
"schemaVersion": 35,
"style": "dark",
"tags": [],
"templating": {
"list": [
{
"current": {},
"datasource": {
"type": "mysql",
"uid": "${DS_MYSQL-2}"
},
"definition": "select f1 from sample;",
"hide": 0,
"includeAll": false,
"multi": false,
"name": "f1",
"options": [],
"query": "select f1 from sample;",
"refresh": 2,
"regex": "",
"skipUrlSync": false,
"sort": 0,
"type": "query"
}
]
},
"time": {
"from": "now-6h",
"to": "now"
},
"timepicker": {},
"timezone": "",
"title": "sample2",
"uid": "D574fMU7k",
"version": 4,
"weekStart": ""
}
```

</summary>

**Comment by mellieA** [comment]
@Amreeshbaskar I was able to reproduce this issue on play.grafana.org with your dashboard json and changed the datasource to TestDataDB: https://play.grafana.org/d/D574fMU7k/sample2?orgId=1 

Steps to reproduce: 
* Edit the panel and change one of the CSV metric values to a threshold that should change the bar color, the bar won't change color. In the example below, 70 should be yellow.
 
![Screen Shot 2022-04-28 at 5 06 59 PM](https://user-images.githubusercontent.com/18175287/165861918-0563b37b-b3c5-4f79-a73e-43a7e6e9fe79.png)

* Change the panel type to bar gauge
* Change **value options** to **all values**
* Change one of the metric values to a threshold that should change the bar color. The bar color immediately changes to the new color

![Screen Shot 2022-04-28 at 5 09 50 PM](https://user-images.githubusercontent.com/18175287/165862192-e759df47-9952-499e-8a08-cdf6fdde2d43.png)

**Comment by leeoniya** [comment]
no loner reproducible at https://play.grafana.org/d/D574fMU7k/sample2?orgId=1
