### ISSUE TITLE
Bad Gateway is happen when "Data Sources / Elasticsearch", "URL: https://localhost:9200/"

### ISSUE THREAD

**Issue by G121332871** [grafana/grafana#47867]
What happened:
Bad Gateway is happen when "Data Sources / Elasticsearch", "URL: https://localhost:9200/",
Auth: None

(Version: 8.4.5)
What you expected to happen:
Index OK. Time field name OK. 
How to reproduce it (as minimally and precisely as possible):
Use opendistro for Elasticsearch https://opendistro.github.io/for-elasticsearch/
Anything else we need to know?:
none

Environment:

Grafana version: 8.4.5
Data source type & version: 
[Plugins][Elasticsearch] Elasticsearch Data Source - Native Plugin Version:5.0.0
OS Grafana is installed on: Centos7
User OS & Browser: Chrome 100.0.4896.88
Grafana plugins: none
Others: non
<img width="397" alt="ES-Bad Gateway" src="https://user-images.githubusercontent.com/57835014/163968465-d5fd750b-b065-491d-9e91-8e553a335d80.PNG">
e

**Comment by joshhunt** [comment]
Not able to reproduce this issue using Elasticsearch 7

![image](https://user-images.githubusercontent.com/46142/164250862-c019f65e-9954-46a9-b0f2-c5c5cd8e9adc.png)

Check the URL is correct, and the other details about the Elasticsearch installation (version, etc).

**Comment by ramonpaolo** [comment]
I resolve this passing `host.docker.internal:9200` instead `https://localhost:9200`
