### ISSUE TITLE
There should be a way to control template value escaping for prometheus

### ISSUE THREAD

**Issue by drscre** [grafana/grafana#4786]
I am using grafana build v3.0.0-beta61461227773 - 2016-04-21

I try to display the following prometheus metric:
```
request_seconds{hostname~="$hostname"}
```
$hostname is a template var `label_values(hostname)` with custom All value `".*"`
In this case i need the $hostname values to be escaped, *except* for my custom All value.
But All value is still escaped and sent to prometheus API like `"\.\*"`

I think, the simplest and most  flexible solution is to introduce a pair of checkboxes for template variables, so users can manually control how they want their variables to be escaped:
```
[ ] escape values
[x] escape all value
```
Or never escape All value at all and leave the proper escaping up to user

Because for prometheus there can also be cases where i don't need any escaping at all:
```
request_seconds{hostname="$hostname"} 
```

**Comment by torkelo** [comment]
custom all values should not be escaped in latest nightly builds 
https://github.com/grafana/grafana/commit/bd21a08bc9c25dc7c03643ec0d91a22c0deab932

But found an issue with that fix, will require another minor fix. will come soon.

**Comment by drscre** [comment]
Thanks!

And what about controlling escaping for ordinary template values?

**Comment by torkelo** [comment]
for prometheus queries they will be regex escaped if the variable has enabled All value or multi value

**Comment by torkelo** [comment]
fixed by https://github.com/grafana/grafana/commit/1dfeb192a31f8a6fcfc9265a4ab99a25da3b8b74

**Comment by SimenB** [comment]
@torkelo why escape? This means my query fails, whereas if I manually remove the escapes, the query succeeds.

**Comment by torkelo** [comment]
to support use cases where multiple values are selected

**Comment by SimenB** [comment]
I stil don't really get that, but would it be possible to opt-out of escaping?
If it's JS I can provide a PR

**Comment by torkelo** [comment]
you cant use the `~=` operator?

**Comment by SimenB** [comment]
Hmm, didn't think of that. I'll give it a whirl Monday :smile:

**Comment by SimenB** [comment]
There we go! The operator is `=~` and not the other way around, but then it worked. 😄 Thanks for the help!

**Comment by kaykayehnn** [comment]
I stumbled on this issue while searching for a way to disable Grafana's variable escaping. For me, the solution was to use the [raw](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/#raw) [format option](https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/) like so `${var_name:raw}`
