### ISSUE TITLE
Minified Redux error #9 when returning from editing old table panel

### ISSUE THREAD

**Issue by pprkut** [grafana/grafana#47875]
**What happened**:

When I exit the edit view of an (old) table panel, I see this error:

```
Error: Minified Redux error #9; visit https://redux.js.org/Errors?code=9 for the full message or use the non-minified dev environment for full errors. 
```

**What you expected to happen**:

Grafana should return to showing the complete dashboard

**How to reproduce it (as minimally and precisely as possible)**:

<details>
<summary>Panel JSON</summary>

```json
{
  "id": 2,
  "gridPos": {
    "h": 16,
    "w": 24,
    "x": 0,
    "y": 5
  },
  "type": "table-old",
  "title": "Log",
  "datasource": {
    "uid": "dap-influxdb-avalon",
    "type": "influxdb"
  },
  "links": [],
  "columns": [],
  "fontSize": "90%",
  "pageSize": 200,
  "scroll": true,
  "showHeader": true,
  "sort": {
    "col": 0,
    "desc": true
  },
  "styles": [
    {
      "alias": "Time",
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "pattern": "Time",
      "type": "date",
      "align": "auto"
    },
    {
      "alias": "",
      "colorMode": null,
      "colors": [
        "rgba(245, 54, 54, 0.9)",
        "rgba(237, 129, 40, 0.89)",
        "rgba(50, 172, 45, 0.97)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 2,
      "link": true,
      "linkTargetBlank": true,
      "linkTooltip": "Nginx Dashboard - RequestID ${__cell}",
      "linkUrl": "/d/dapnginxdetails-/nginx-request-details?var-RequestID=${__cell}",
      "mappingType": 1,
      "pattern": "request_id",
      "thresholds": [],
      "type": "string",
      "unit": "short",
      "align": "auto"
    },
    {
      "alias": "",
      "colorMode": "cell",
      "colors": [
        "#73BF69",
        "rgba(237, 129, 40, 0.89)",
        "rgba(245, 54, 54, 0.9)"
      ],
      "dateFormat": "YYYY-MM-DD HH:mm:ss",
      "decimals": 0,
      "mappingType": 1,
      "pattern": "level",
      "thresholds": [
        "300",
        "400"
      ],
      "type": "number",
      "unit": "none",
      "align": "auto"
    }
  ],
  "targets": [
    {
      "alias": "$col",
      "groupBy": [],
      "measurement": "php_log",
      "orderByTime": "ASC",
      "policy": "3m",
      "query": "SELECT \"hostname\", \"call\", \"request_id\", \"level\", \"level_name\", \"message\" FROM \"3m\".\"php_log\" WHERE (\"environment\" =~ /^$Environment$/) AND $timeFilter",
      "rawQuery": true,
      "refId": "A",
      "resultFormat": "time_series",
      "select": [
        [
          {
            "params": [
              "level_name"
            ],
            "type": "field"
          }
        ],
        [
          {
            "params": [
              "message"
            ],
            "type": "field"
          }
        ]
      ],
      "tags": []
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "transform": "timeseries_to_columns"
}
```

</details>

[Log-data-as-seriestocolumns-2022-04-19 13 04 12.csv](https://github.com/grafana/grafana/files/8512365/Log-data-as-seriestocolumns-2022-04-19.13.04.12.csv)

Problem does not happen when there is no data for the panel to display.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: InfluxDB 5.0.0
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Slackware Linux - Firefox 98.0.2
- Grafana plugins: -
- Others: -

**Comment by joshhunt** [comment]
I'm not able to replicate the issue - on this dashboard https://play.grafana.org/d/atdfvVw7z/47875-old-table-panel

I created one panel from scratch (but overrode visualisation to the Old Table), and created another one from your JSON and I was not able to replicate the issue.

Old Table is deprecated and does not receive much maintenance, so without a solid way to replicate the issue for us it's tricky to do much.

**Comment by pprkut** [comment]
Just updated to 8.5.0 and I can still reproduce it there as well

**Comment by mellieA** [comment]
@pprkut are you able to reproduce it if you create a table panel? I'm curious if all of the tables you're seeing it on have been existing ones.

**Comment by pprkut** [comment]
@mellieA I recreated the entire dashboard from scratch, and I have a hint :)

The new dashboard starts exhibiting the error after I set the refresh interval to `30s`. On the other hand, the old dashboard stops exhibiting the error when I set the refresh interval to `Off`. I can confirm the same behavior on another dashboard as well.

**Comment by zoltanbedi** [comment]
Thanks for reporting this @pprkut I was able to replicate this. I think this is something that @grafana/user-essentials should take a look at. Let me know if you think we(BI) should fix it.

**Comment by JoaoSilvaGrafana** [comment]
Hey 👋 Thank you for raising this, I have managed to reproduce this locally on 8.5.0, but there seems to be a fix for the next minor version that already fixes it 😄 Can't say exactly when it gets released but when it does I will ping you to test again!

**Comment by pprkut** [comment]
@JoaoSilvaGrafana Tested with 8.5.1 and it's working indeed :)
