### ISSUE TITLE
Plugins: filterQuery isn't called for frontend data sources

### ISSUE THREAD

**Issue by marcusolsson** [grafana/grafana#47876]
**What happened**:

Overloading the `filterQuery` method in a frontend data source has no effect.

**What you expected to happen**:

I expected the query to be skipped and to log 'filterQuery'.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create a new plugin based on the Data Source (frontend) plugin starter.
2. In `datasource.ts`, add the following:

   ```ts
     filterQuery(query: MyQuery): boolean {
       console.log('filterQuery');
       return false;
     }
   ```

3. Add the data source and create a dashboard with a panel that queries the data source.
4. The query still runs and there's no console output.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Data source plugin starter
- OS Grafana is installed on: Linux (Docker)
- User OS & Browser: macOS (Firefox)
- Grafana plugins:
- Others:

**Comment by marefr** [comment]
Maybe only supported for backend datasources extending `DataSourceWithBackend`? 

https://github.com/grafana/grafana/blob/0c31399e34ce1a4d9cb0d1453b2e72f3cd6d54ba/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L112

**Comment by marcusolsson** [comment]
Indeed looks like it it's only for backend data sources, but since the method is declared in DataSourceApi rather than DataSourceWithBackend it suggests that it should be supported for frontend data sources as well?

Maybe we can clarify this in the [documentation](https://github.com/grafana/grafana/blob/0c31399e34ce1a4d9cb0d1453b2e72f3cd6d54ba/packages/grafana-data/src/types/datasource.ts#L241-L248) for filterQuery?

A simple fix would be to copy-paste to following in your `query()` method:

```go
if (this.filterQuery) {
  targets = targets.filter((q) => this.filterQuery!(q));
}
```

**Comment by mckn** [comment]
> Indeed looks like it it's only for backend data sources, but since the method is declared in DataSourceApi rather than DataSourceWithBackend it suggests that it should be supported for frontend data sources as well?
> 
> Maybe we can clarify this in the [documentation](https://github.com/grafana/grafana/blob/0c31399e34ce1a4d9cb0d1453b2e72f3cd6d54ba/packages/grafana-data/src/types/datasource.ts#L241-L248) for filterQuery?
> 
> A simple fix would be to copy-paste the following in your `query()` method:
> 
> ```go
> if (this.filterQuery) {
>   targets = targets.filter((q) => this.filterQuery!(q));
> }
> ```

Yes - this makes sense to me! We should probably make sure it is being done prior to running the query for a non-backend datasource. 

https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/datasource.ts#L272
