### ISSUE TITLE
[Bug] All values are '0' when in graphs

### ISSUE THREAD

**Issue by javicho21** [grafana/grafana#4787]
Hello,

I'm using Grafana version: 3.0.0-beta2, commit: v3.0-beta2, build date: 2016-04-04 12:52:41
I'm running InfluxDB 0.9.6.1
I'm running on Ubuntu 14.04

I am inserting values into InfluxDB as shown here:
testmetric,host=test01,cpu=cpu01 value=12 1461274650055000000

when I look in InfluxDB I see my inserted value:
> select * from testmetric 
name: testmetric
----------------
time			                   cpu	host	        value
1461274650055000000	cpu01	test01	12

However, when I look in Grafana all that I see are values that = 0

Why is Grafana only seeing the value 0? Why is it not seeing value = 12?

Thanks,

JRV

**Comment by javicho21** [comment]
![screen shot 2016-04-21 at 4 43 34 pm](https://cloud.githubusercontent.com/assets/14881625/14725239/598f722a-07e0-11e6-8396-3f9fb39c99a5.png)

**Comment by torkelo** [comment]
not sure, try changing group by time interval, try another aggregation function.

Grafana does show 0, which means your InfluxDB query returns zero. So problably something wrong with your query :)

**Comment by javicho21** [comment]
Can you please indicate a different test query that I could exec into the influx command line to test these values?  As you can see from my case I opened I executed: select * from testmetric and I received back the proper value.

**Comment by torkelo** [comment]
you could try using the same query you use in grafana :) 

something like `select mean(value) from testmetric where time > now() - 1h group by time(1s) fill(null)`
