### ISSUE TITLE
Support Google Analytics 4

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#47883]
Our currently Google Analytics implementation is deprecated, and we are recommended to switch to Google Analytics 4. See https://support.google.com/analytics/answer/10089681?hl=en. It looks like there's a hard cut off date of July 1, 2023.

As the two implementations are incompatible on GA's side (they require changes to the GA account), we would need to add GA as a _new_ [services/echo backend](https://github.com/grafana/grafana/blob/76bc1d5b585beadaf5ed1854f071ea1fbc6fb297/public/app/core/services/echo/backends/analytics/GABackend.ts) and have both in parallel, and deprecate the existing one.

**Comment by zsofiakomaromigrafana** [comment]
It would be good to tackle this a year before Universal Analytics is sunset, so that those using their own analytics in Grafana could have a year's worth of data in their GA4 account.

**Comment by eledobleefe** [comment]
```
<!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=abc123"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'abc123');
</script>
```

**Comment by joshhunt** [comment]
Taking a look at Echo service, and I think the implementation could/should be improved a bit to prevent bugs...

At the moment Echo service uses a single method `addEvent` to send page views, interaction events, and experiment views to the various backends. [RudderstackBackend](https://github.com/grafana/grafana/blob/485006d8d4a17653c3c8403ea44c757dfada8b1d/public/app/core/services/echo/backends/analytics/RudderstackBackend.ts/#L77-L91) is a good implementation which correctly checks the event type, and tracks it appropriately. However other backends are more inconsistent, with the [GABackend](https://github.com/grafana/grafana/blob/485006d8d4a17653c3c8403ea44c757dfada8b1d/public/app/core/services/echo/backends/analytics/GABackend.ts/#L34-L47) incorrectly tracking all events as pageviews. This means pages that implement interaction events would be over-tracked as page views.

I think this type of implementation easily leads to drift and bugs like this between analytics backends, so I propose to extend the `EchoBackend` interface to add separate methods for each event type, rather than use the one `addEvent` method. It would look something like:

```
class RudderstackBackend implements EchoBackend {
  constructor() {}

  reportPageView(ev: PageViewEchoEvent) {}
  reportInteraction(ev: InteractionEchoEvent) {} // reportEvent instead?
  reportExperimentView(ev: ExperimentViewEchoEvent) {}
}
```

@dprokop You've been involved in Echo srv a bit in the past - what's your thoughts on this?

**Comment by joshhunt** [comment]
Ahh, I see each EchoBackend declares an array of `supportedEvents` https://github.com/grafana/grafana/blob/d1b98499462d5e21e13c306ae7e659a33c936b7f/public/app/core/services/echo/backends/analytics/GABackend.ts/#L11, which kind of mitigates a part of the drift

**Comment by dprokop** [comment]
@joshhunt I think you figured it out with `supportedEvents`. That's the actual filtering of what a given backend is "subscribed" to.
