### ISSUE TITLE
Grafana-Elasticsearch

### ISSUE THREAD

**Issue by kisienya** [grafana/grafana#4788]
[Question]

I am using the following
* grafana version: Grafana version: 2.6.0   
* datasource: 2.2.0
* OS grafana is runing on: Fedora 22.x86_64

I an trying out template queries on a string field.
I have the following
{"find": "terms", "field": "Description", "query": "NoteCategoryID: 1"}	
This gives me the results
(\"activities\" OR \"daily\" OR \"living\" OR \"of\")
I need it to return one result because thats a phrase
Activities of daily living
See image
![question](https://cloud.githubusercontent.com/assets/9349591/14737113/0cf1d0f4-0883-11e6-8850-9418d8cd824b.png)

How can I change the query to yield results needed?

**Comment by torkelo** [comment]
Terms aggregation will return each word in an analyzed text field. So you would have to change your elasticsearch index mapping to not analyze the description field.

**Comment by kisienya** [comment]
Many thanks will do that
