### ISSUE TITLE
Templating with InfluxDB v0.12

### ISSUE THREAD

**Issue by hiskind** [grafana/grafana#4789]
InfluxDB v0.12 has changed response format for queries like `SHOW TAG VALUES FROM "measurement" WITH KEY = "tag_key"`. Now it returns two series: `key` and `value` (previous version returned only `value`). Grafana uses the first one by default and assigns to a variable a tag key, instead of tag values.

I don't think this is grafana's bug, and maybe there are some other ways how to do it, but for me it makes almost impossible to use templating with InfluxDB. 

I'm using grafana build v3.0.0-pre1 - 2016-02-19

**Comment by torkelo** [comment]
this is fixed in master and in latest nightly build, 
https://github.com/grafana/grafana/issues/4726
