### ISSUE TITLE
index UQE_alert_rule_org_id_uid in alert_rule conflict

### ISSUE THREAD

**Issue by andywu1998** [grafana/grafana#47909]
**What happened**:
I want to update grafana from v7.3.5 to v8.4.6, so I copied history data from our live environment, and then start grafana. 

the log show that 'Apr 18 16:53:30 sg2-shopee-log-thanos-live-10-129-60-226 grafana-server[60349]: logger=migrator t=2022-04-18T16:53:30.52+0800 lvl=eror msg="Executing migration failed" id="move dashboard alerts to unified alerting" error="Error 1062: Duplicate entry '9-lHvvEgw7k' for key 'UQE_alert_rule_org_id_uid'"'

**What you expected to happen**:
grafana started normally after I copied the old data

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

I see the source code, UID field of alertRule struct generate by util.GenerateShortUID(). it seems that UID will not conflict, but it happened.

**Environment**:
- Grafana version: v8.4.6
- Data source type & version:
- OS Grafana is installed on: linux
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by andywu1998** [comment]
hi all:

we add a log in this file:  pkg/services/sqlstore/migrations/ualert/alert_rule.go:
```
func (m *migration) makeAlertRule(cond condition, da dashAlert, folderUID string) (*alertRule, error) {
        lbls, annotations := addMigrationInfo(&da)
        lbls["alertname"] = da.Name
        annotations["message"] = da.Message
        var err error

        data, err := migrateAlertRuleQueries(cond.Data)
        if err != nil {
                return nil, fmt.Errorf("failed to migrate alert rule queries: %w", err)
        }
        uid := util.GenerateShortUID() 
        m.mg.Logger.Info("log util.GenerateShortUID(): ", uid)

        ar := &alertRule{
                OrgID:           da.OrgId,
                Title:           da.Name, // TODO: Make sure all names are unique, make new name on constraint insert error.
                UID:             uid,
                Condition:       cond.Condition,
                Data:            data,
                IntervalSeconds: ruleAdjustInterval(da.Frequency),
                Version:         1,
                NamespaceUID:    folderUID, // Folder already created, comes from env var.
                RuleGroup:       da.Name,
                For:             duration(da.For),
                Updated:         time.Now().UTC(),
                Annotations:     annotations,
                Labels:          lbls,
        }
```
log:
```
        uid := util.GenerateShortUID() 
        m.mg.Logger.Info("log util.GenerateShortUID(): ", uid)
```

and we make sure that util.GenerateShortUID()  generate two the same uid.

In addition to that, we found this code in this file (pkg/services/dashboards/database/database.go):

```
func generateNewDashboardUid(sess *sqlstore.DBSession, orgId int64) (string, error) {
	for i := 0; i < 3; i++ {
		uid := util.GenerateShortUID()

		exists, err := sess.Where("org_id=? AND uid=?", orgId, uid).Get(&models.Dashboard{})
		if err != nil {
			return "", err
		}

		if !exists {
			return uid, nil
		}
	}

	return "", models.ErrDashboardFailedGenerateUniqueUid
}
```

in this code, will generate uid three times.
so, Does this mean that the generation of the uid is faulty and that previous developers have discovered the problem?

**Comment by joeblubaugh** [comment]
Hi - thanks for the report! Are you running Grafana in HA mode? If so, how many replicas are you using?

**Comment by andywu1998** [comment]
@joshhunt hi, thanks for replying. we are not running Grafana in HA mode, just one instance in our test machine. we also found this error was caused by our invalid data. 

```
EROR[04-20|20:40:15] Executing migration failed               logger=migrator id="move dashboard alerts to unified alerting" error="failed to validate receiver \"xxxx(our private data)\" of type \"webhook\": could not find url property in settings"
EROR[04-20|20:40:15] Exec failed                              logger=migrator error="failed to validate receiver \"xxxx(our private data)\" of type \"webhook\": could not find url property in settings" sql="code migration"
Failed to start grafana. error: migration failed (id = move dashboard alerts to unified alerting): failed to validate receiver "xxxx(our private data)" of type "webhook": could not find url property in settings
migration failed (id = move dashboard alerts to unified alerting): failed to validate receiver "xxxx(our private data)" of type "webhook": could not find url property in settings
[Bra] 04-20 20:40:15 [ WARN] Fail to execute command: ./bin/grafana-server [-packaging=dev cfg:app_mode=development] - exit status 1
```

but after we deleted that invalid notification channel, the first problem which was caused by the unique index also disappear. I feel so confused about this problem, this problem may be difficult to reproduce, and now we updated Grafana v8.4.6 normally. so if it's hard to find the real reason, you can close this issue.

**Comment by joeblubaugh** [comment]
Are all the alert rules that you expect to be there available? Do they seem to be working normally?

**Comment by andywu1998** [comment]
@joeblubaugh yeah, it is working normally.

**Comment by joeblubaugh** [comment]
Since everything is working for you, I'm going to close the issue. We haven't come up with a good theory for why this would occur.
