### ISSUE TITLE
Navigation: Update Import + Export page documentation now `+` button functionality has been moved

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#47945]

**Comment by JoaoSilvaGrafana** [comment]
Also in the following docs (might be more, these are the ones I could find):
- "Dashboard Folders" https://grafana.com/docs/grafana/latest/dashboards/dashboard_folders/#how-to-create-a-folder
- "Getting Started" https://grafana.com/docs/grafana/latest/getting-started/getting-started/#step-3-create-a-dashboard
- "Add a Library Panel" https://grafana.com/docs/grafana/latest/getting-started/getting-started/#step-3-create-a-dashboard

**Comment by natellium** [comment]
@gguillotte-grafana Maybe you can help with this. At what point should we update the docs? And we're not sure if there are more. Our plan is to enable the feature flag (see https://github.com/grafana/grafana/issues/48268) by default so this will become more important once that's released.
