### ISSUE TITLE
Shared Annotation Configurations

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#4795]
When creating annotation sources for a dashboard, they are often useful in many places.

For example, you might have things like "puppet deploys, builds, and system reboots". There are many dashboards where you might want to be able to turn those on so the relationship of annotation filters to dashboards can be one to many.

It would be nice to make these available as options when adding annotations to a dashboard, so the same configuration is not repeated in many places.

**Comment by max-matiukhin** [comment]
Any chance it would be added to grafana in the foreseeable future? This feature would be pretty useful for us
