### ISSUE TITLE
Remove "you are here" indicator from the OSS homepage (orange bar next to the Grafana logo when on the home page)

### ISSUE THREAD

**Issue by zsofiakomaromigrafana** [grafana/grafana#47965]

**Comment by JoaoSilvaGrafana** [comment]
@zsofiakomaromigrafana Do we also want to remove it from the expanded menu? The "active" state in the expanded menu controls both that orange bar and the lighter text color, so might be more complicated to decouple that. Easy to remove from the collapsed menu though

![Screenshot 2022-04-22 at 16 11 42](https://user-images.githubusercontent.com/100691367/164743206-f1687474-ae94-4c07-b56c-4c195d3491b7.png)
