### ISSUE TITLE
AzureMonitor: Automatic time grain selection is not correctly set in backend

### ISSUE THREAD

**Issue by aangelisc** [grafana/grafana#47979]
**What happened**:

When selecting a metric using the Azure Monitor datasource, the automatic time grain is correctly inferred on the frontend. However, selecting auto as the time grain causes an API error as the backend does not make use of the defined metrics defined time grains and instead uses hardcoded defaults. This causes the wrong time grain to be selected when the query is executed.

![Screen Recording 2022-04-20 at 15 32 24](https://user-images.githubusercontent.com/15019026/164263119-89f548ed-3f88-4069-a36b-f66598754160.gif)

**What you expected to happen**:

The automatic time grain inferred in the frontend should be used in the backend request.

**How to reproduce it (as minimally and precisely as possible)**:

See screenshot.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aangelisc** [comment]
Progress made on https://github.com/grafana/grafana/compare/main...mob/main-mob/azure-monitor-timegrains with @sunker, @andresmgot, @kevinwcyu. We've correctly identified and updated the frontend query so that the supported time grains for a metric are passed to the backend in the required format.

A separate issue has now been picked up where the `resourceUri` is not updating when other parameters are changed.

**Comment by kevinwcyu** [comment]
> A separate issue has now been picked up where the `resourceUri` is not updating when other parameters are changed.

https://github.com/grafana/grafana/blob/836f5c1f4a2f5a03b91121a2e80f23369f711e13/public/app/plugins/datasource/grafana-azure-monitor-datasource/utils/migrateQuery.ts#L143-L145 is the issue. It just returns the query if the resourceUri is already set.

We can set `resourceUri: '',` in these query setters. https://github.com/grafana/grafana/blob/94d2155f44787cee4b11ffe4260290f89a6cf243/public/app/plugins/datasource/grafana-azure-monitor-datasource/components/MetricsQueryEditor/setQueryValue.ts#L18-L101
