### ISSUE TITLE
[Question] Can't access Dashboards with my dynamic dns address

### ISSUE THREAD

**Issue by hl68fx** [grafana/grafana#4801]
Hi,

when I would like to access my Grafana dashboards with my dynamic dns adress from outside my local network I get the following error message: InfluxDB Error: Cannot read property 'message' of null
It is only possible to login, but when I choose one of my dasboards I get the error message.

Everything works fine when I am in my local network. I would be very grateful if you can provide me a solution for my problem :)

OS: Ubuntu 15.10 Server
Datasource: Influxdb 0.12
Grafana version: 3.0.0-beta5
Both Grafana and Influxdb run in their own docker container

Kind regards,
Tom

**Comment by torkelo** [comment]
you could try changing data source access mode from direct to proxy, so the influxdb requests go through grafana server.

Beside that, not sure what your issue could be, maybe something with your vpn / network setup :)
