### ISSUE TITLE
generic_oauth not working correctly

### ISSUE THREAD

**Issue by xuanxiang** [grafana/grafana#48028]
https://github.com/grafana/grafana/blob/5c3be630f2763f5477c48aee336367d06e674da4/pkg/login/social/generic_oauth.go#L91

I am using Grafana grafana-8.4.5-1.x86_64.rpm . 
When the attributes is 'map<string, string>' is not a map<string,string []> array, the 'JSON. Unmarshal (rawjson, & data)' conversion in line 292 will report an error, hope change it

**Comment by IevaVasiljeva** [comment]
Thanks @yangkb09! I've added this to our backlog.

**Comment by alexanderzobnin** [comment]
@xuanxiang Hi! could you please give more details. What OAuth provider do you use? What's a token schema?

**Comment by Jguer** [comment]
Closing as stale, feel free to reopen if new information is provided
