### ISSUE TITLE
Grafana does not run headless (on Ubuntu16.04 LTS/Phantomjs 2.0.0+dfsg)

### ISSUE THREAD

**Issue by Adorfer** [grafana/grafana#4802]
sysupgrading from an ubuntu 14.04LTS to 15.10, we face a problem. 
```
Apr 24 18:45:08 eulenmap2 grafana[694]: QXcbConnection: Could not connect to display
Apr 24 18:45:08 eulenmap2 grafana[694]: PhantomJS has crashed. Please read the bug reporting guide at
Apr 24 18:45:08 eulenmap2 grafana[694]: <http://phantomjs.org/bug-reporting.html> and file a bug report.
```

as a result, no prerendered PNG-graphs available. 
And in the web-ui most icons and legends (color-blocks) are missing.

a hint may be: 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808242 phantomjs: Does not run headless

This may look similar to closed issues
https://github.com/grafana/grafana/issues/4712
and 
https://github.com/grafana/grafana/issues/4528

**Comment by torkelo** [comment]
what version of grafana are you testing with?

Please test with latest Grafana 3.0 beta

**Comment by plumpudding** [comment]
It works with the 3.0 beta because it has a different phantomjs binary included, because it's not an official ubuntu package. 
I have access to the named server and can confirm it working.

You can close this issue.
