### ISSUE TITLE
Email Alerts Url contains localhost with private sign plugin

### ISSUE THREAD

**Issue by Gulraiz832** [grafana/grafana#48027]
I am using Grafana docker image 8.4.5 with a custom private signed plugin. To sign the plugin I am using localhost in root_url. Everything works fine till here. The problem arises when grafana send email alerts. In the email URL it doesn’t contain the host IP address instead it contains localhost.

One solution would be to replace GF_ROOT_URL with the host machine URL but when I do that it makes the plugin signature invalid. Signing the plugin every time with the host URL is not practical because most of the time I don’t know the host IP.

I think there shall be some way to sign a private plugin without defining route_url.

**Comment by marefr** [comment]
Please refer to [Error signing manifest: Field is required: rootUrls
](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#error-signing-manifest-field-is-required-rooturls)

> The rootUrls must match the root_url configuration.

And [Sign a private plugin](https://grafana.com/docs/grafana/latest/developers/plugins/sign-a-plugin/#sign-a-private-plugin):

> The rootUrls flag accepts a comma-separated list of URLs to the Grafana instances where you intend to install the plugin.
