### ISSUE TITLE
[Bug] Tooltip doesn't respect time display settings

### ISSUE THREAD

**Issue by joshrp** [grafana/grafana#4803]
Using Grafana 3.0.0-beta51460725904

Metrics are coming in at UTC, the "timezone" preference is set to local browser time.

The X axis works as expected, showing the time in local browser time (BST for me). Hovering over the graph though, the Tooltip still displays UTC time.
![Screenshot](https://cloud.githubusercontent.com/assets/695943/14783036/f923befc-0ae4-11e6-9935-ec096fe17409.png)

**Comment by torkelo** [comment]
cant replicate this on any Grafana instance, do you get this on all graphs, or just some?

**Comment by joshrp** [comment]
Nice quick response, cheers!

Yep, all my current graphs do this, though that's not many as I've only just setup this instance, the last time I used grafana was back in version 1.

Not sure what other information would help here? 

Graphite version 0.9.15 
Cent OS 6.6
Firefox 38.3

**Comment by joshrp** [comment]
Ah, I just figured something else out. The dashboard timezone was set to "Default" and the Organisation is set to local browser time. 

If I change the Dashboard to local browser time, the tooltip time is corrected, it doesn't seem to follow whatever the Organisation setting is (any of the three), only the dashboard setting.

**Comment by utkarshcmu** [comment]
I think preferences should follow this order of priority:
1. User preference
2. Org preference
3. Default/Dashboard preference

**Comment by torkelo** [comment]
@utkarshcmu is that not he current order?

**Comment by utkarshcmu** [comment]
Indeed! That is the current order and I am not able to reproduce the above mentioned issue in 3.0.0-beta6.

**Comment by joshrp** [comment]
But having the dashboard set to "Default" should leave it to follow the Org preference? That's what seems to be broken, the Org is set Local Time and the dashboard to Default, but it's using UTC. Also, the axis should not be different to the tooltip, no matter the preference, no?

I will try beta6 soon (hopefully tomorrow) and see if it's still present.

**Comment by utkarshcmu** [comment]
@joshrp Can you please check all the three preferences? Your user preference (under profile), Org preference (under Org preferences) and Dashbaord default preference (under dashboard settings)?

I tried setting the following:
1. User preference - default
2. Org preference - local
3. Dashboard preference - default

And the result is default due to User preference as it overrides other two. If you can reproduce the issue, please provide all the 3 preferences and I will try to replicate here. :)

And axis is showing the right time according to the preference for me here in Grafana 3.0.0-beta6.

**Comment by joshrp** [comment]
OK I just tried again (still beta5) and my preferences exactly match yours above @utkarshcmu default, local, default. And the axis and the tooltip display as in my screenshot. I will try and update to beta6 today and try it again.

**Comment by joshrp** [comment]
OK, Just did the upgrade (yay RPMs) and it's still present. I don't mind if the settings aren't quite as I expect but the tooltip and X axis should always agree on the time, since they're looking at the same settings.

Not sure what other info to provide, there's very little to my installation at all, we're only just getting up and running. 

If I do change the dashboard setting to "Local time" then the X Axis doesn't change at all (as expected because it's already local time based on the Org setting) but the tooltip switches to local time.

**Comment by joshrp** [comment]
OK I've done some digging, for my own curiosity, and I know nothing about the codebase, so take all this with a large pinch of salt but:

It seems the timepicker uses `dashboard.formatDate` [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph_tooltip.js#L175) which as far as I can tell (really not sure) points to [here](https://github.com/grafana/grafana/blob/469c43ca25f98362ee35c85f9ec017e3a0c9b8f6/public/app/features/dashboard/dashboardSrv.js#L184) if it doesn't then my theory is totally wrong. 

That `formatDate` looks at whether the `dashboard.timezone === 'browser'` then does the timezone switch. It doesn't seem to look at the user settings.

As opposed to what I think is the axis rendering [here](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/graph.js#L278) which uses `dashboard.getTimezone` which looks like it checks the user settings (which I assume also inherit the org settings ??) [here](https://github.com/grafana/grafana/blob/469c43ca25f98362ee35c85f9ec017e3a0c9b8f6/public/app/features/dashboard/dashboardSrv.js#L215) 

Apologies if that is entirely wrong, but hopefully it helps.
