### ISSUE TITLE
[Bug] Can't add multiple queries in Grafana 2.6

### ISSUE THREAD

**Issue by Trefex** [grafana/grafana#4804]
* What grafana version are you using?

2.6.0

* What datasource are you using?

InfluxDB 0.9

* What OS are you running grafana on?

CentOS 7.2

![image](https://cloud.githubusercontent.com/assets/2877665/14783668/77554a3c-0af1-11e6-9612-94a68bae430d.png)

Or with one query alone, it works.

![image](https://cloud.githubusercontent.com/assets/2877665/14783679/86d41d1c-0af1-11e6-96b7-66cdcf2ef7ba.png)

Any ideas?

**Comment by torkelo** [comment]
Are you use you are using InfluxDB 0.9 and not 0.11 ? 

InfluxDB 0.11 introduced breaking change that required a Grafana update, so you must use Grafana 3.0 for InfluxDB 0.11 or 0.12

Try upgrading to Grafana 3.0

**Comment by Trefex** [comment]
@torkelo I'm actually using 0.12. I mention 0.9 above because it's the only thing available as Data Source in 2.6. I will try Beta 3.

Thanks for fast answer 👍

**Comment by Trefex** [comment]
@torkelo Works beautifully. In fact, it's much more beautiful overall.

Thanks for great tool so far :)
