### ISSUE TITLE
[Question] How to use multi-values in Templating using InfluxDB

### ISSUE THREAD

**Issue by Trefex** [grafana/grafana#4805]
* What grafana version are you using? 3.0-Beta
* What datasource are you using? InfluxDB 0.12
* What OS are you running grafana on? CentOS 7.2

I defined a template variable as follows:

![image](https://cloud.githubusercontent.com/assets/2877665/14787653/95e81fd4-0b04-11e6-9409-b9a3cdcd1c74.png)

I defined my dashboard as follows:

![image](https://cloud.githubusercontent.com/assets/2877665/14787663/a54f5adc-0b04-11e6-97e0-2545f3b39db7.png)

However, when I select a Host in the dropdown from the template variable, I get no graph, and no error message.

Any thoughts?

If I uncheck multi-value in the template variable, it works, but only with 1 host (as it should).

Thanks,

**Comment by torkelo** [comment]
this was fixed earlier today, https://github.com/grafana/grafana/issues/4797

try latest nightly 
http://grafana.org/download/builds.html
