### ISSUE TITLE
[Feature] Support building via make

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#4806]
It would be nice to be able to runn the various dependency/build/test commands via make deps/build/test, and remove the unnecessary dependency on a global install of grunt-cli.

**Comment by torkelo** [comment]
you don't need a globaly installed grunt, `./node_modules/grunt-cli/bin/grunt`

also `go run build.go test`  will test go code and run `grunt test`

**Comment by DanCech** [comment]
you don't but the README.md says you do.  The PR also updates the grunt invocations to use the preferred `./node_modules/.bin/grunt` path for directly executing grunt, and adds an npm target for test (npm adds `./node_modules/.bin` to `PATH` automatically) so you can run the node tests with `npm test`.
