### ISSUE TITLE
Unified Alerting: failed to execute conditions: no float64 value column found in frame - Azure Log Analytics

### ISSUE THREAD

**Issue by lcmarques** [grafana/grafana#48072]
Hello,

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Linux x86-64
- User OS & Browser: Ubuntu 20.04 
- Grafana plugins: Unified Alerting system

When writing an KSQL query to deploy an alarm with Datasource "Azure Monitor" and Service "Logs", if the query doesn't return any data for the time of the evaluation (now-15m, as example) the following error appears: 

"Failed to evaluate queries and expressions: failed to execute conditions: no float64 value column found in frame"

If the query returns any numerical value, no error appears. While you can handle this behavior using "no data & error handling", the health state of the alarm is always "error".

To reproduce it, write an KustoSQL query that doesn't return any data for the period.
![image](https://user-images.githubusercontent.com/1311287/164497514-2c0d89ff-f226-4b22-8161-8b9c38bc09c7.png)
![image](https://user-images.githubusercontent.com/1311287/164496991-0605f7aa-6cda-4f57-87cf-bd92fc1f1840.png)

**Comment by mellieA** [comment]
Sounds similar to https://github.com/grafana/grafana/pull/43441

**Comment by iwysiu** [comment]
Thanks for reporting the issue @lcmarques ! Reproduced with the `cloud-datasources` resource and a query of
```
Update
|where OSType != "Linux" and UpdateState == "Needed" and Optional == "false" 
| summarize Count=count() by TimeGenerated
```
Initial investigation suggests its a similar error to the influxDB one. I'll move this to our backlog.

**Comment by santihernandezc** [comment]
@armandgrillet seems like pretty much the same thing, different data source.

**Comment by lloiacono** [comment]
Any update on this? Also is there a workaround to avoid having the alert constantly triggering or in an error state?

**Comment by andresmgot** [comment]
I don't think this is a data source error, right? This should happen for any data source that returns empty data @grafana/alerting-squad. It seems that the problem is that even if you say that no data is okay, it still fails with the warning:

![Screenshot from 2022-09-22 13-00-52](https://user-images.githubusercontent.com/4025665/191730131-e7333083-b8be-4163-b1ad-3ebeb744b248.png)

Removing it from our board but let us know if there is something we should handle at the data source level.

**Comment by grobinson-grafana** [comment]
Hi @andresmgot! 👋 What is the data frame format returned from the Azure datasource plugin for no data responses?

**Comment by andresmgot** [comment]
For example:

```js
{
  "response": {
    "results": {
      "A": {
        "frames": [
          {
            "schema": {
              "refId": "A",
              "meta": {
                "custom": {
                  "azureColumnTypes": [
                    "datetime",
                    "long"
                  ],
                  "subscription": "",
                  "workspace": "",
                  "encodedQuery": ""
                },
                "executedQueryString": "Update\n|where OSType != \"Linux\" and UpdateState == \"Needed\" and Optional == \"false\" \n| summarize Count=count() by TimeGenerated\n"
              },
              "fields": [
                {
                  "name": "TimeGenerated",
                  "type": "time",
                  "typeInfo": {
                    "frame": "time.Time",
                    "nullable": true
                  }
                },
                {
                  "name": "Count",
                  "type": "number",
                  "typeInfo": {
                    "frame": "int64",
                    "nullable": true
                  }
                }
              ]
            },
            "data": {
              "values": [
                [],
                []
              ]
            }
          }
        ],
        "refId": "A"
      }
    }
  }
}
```

**Comment by grobinson-grafana** [comment]
Hi @andresmgot! 👋 Thanks for the quick answer. This explains the issue as the data frame format doesn't match the expected no data format. I can help fix this in the datasource plugin.

**Comment by andresmgot** [comment]
I see, what's the expected format?

**Comment by grobinson-grafana** [comment]
The current expected NoData response in Grafana are either of the following:

#### No frames

```
{
  "response": {
    "results": {
      "A": {
        "frames": []
      }
    }
  }
}
```

#### 1 frame but with no fields, might have metadata

```
{
  "response": {
    "results": {
      "A": {
        "frames": [{
          "fields": [],
          "meta": {
            // some meta
          }
        }]
      }
    }
  }
}
```

**Comment by andresmgot** [comment]
Got it, we can change that, adding it back to our board.

Anyway, I am wondering if it makes sense to include our case as "no data" or if there is something inherently wrong with that format.
