### ISSUE TITLE
cannot hover to bring up annotation window when zoomed out on short duration annotations in time-series panel

### ISSUE THREAD

**Issue by justinsmalley** [grafana/grafana#48087]
**What happened**:
![Kapture 2022-04-21 at 15 13 59](https://user-images.githubusercontent.com/99200643/164553433-21fcef69-6a5f-494c-af73-ac8985212dc7.gif)
Under the following conditions, their are zero pixels (hitbox?)to mouseover to activate the annotation window:

1. Time Series panel is used ( the old graph does not have this issue)
2. Annotation has an endtime
3. endtime is sufficiently small (the demo video has annotations 1 second in length)
4. you are sufficiently zoomed out.

**What you expected to happen**:
There should be a mouseover for annotations at any zoom level.
 
**How to reproduce it (as minimally and precisely as possible)**:

1. Create a short annotation (must have endtime). 
2. Use Time Series panel. 
3. zoom out until the issue occurs 

**Anything else we need to know?**:
Does not occur consistently. If it is not reproducible right away, zoom out further and/or adjust the time window and it should occur eventually.

**Environment**:
- Grafana version: 8.4.7
- Datasource: annotations (reading from postgres datasource but I expect any annotation source to behave the same)
- OS Grafana is installed on: docker
- User OS & Browser: MacOS + chrome
- Grafana plugins: N/a
- Others:

**Comment by mellieA** [comment]
Reproduced this with 8.5.0 and the TestDB datasource

Created an annotation with a sub-second duration using the API: 
<img width="527" alt="Screen Shot 2022-04-26 at 5 34 00 PM" src="https://user-images.githubusercontent.com/18175287/165409550-74051ff4-c3ac-46f8-993e-b23bd1c06ada.png">

Tested with a 1 minute duration and a small sliver appeared, so I was able to hover and see the annotation content: 

<img width="579" alt="Screen Shot 2022-04-26 at 5 46 42 PM" src="https://user-images.githubusercontent.com/18175287/165410456-377750d6-8de2-47e4-942c-a8cbb37d5ca6.png">

**Comment by codeincarnate** [comment]
With range annotations a bar is typically rendered to hover for an annotation, the short time range is causing that bar to not be rendered. I think we'll likely use the triangle from single point in time annotations for these short time ranges to fix this.
