### ISSUE TITLE
alert query panel is switched to timeseries panel after changing query order

### ISSUE THREAD

**Issue by gjemp** [grafana/grafana#48094]
**What happened**:
alert query panel is switched to timeseries panel after changing query order

**What you expected to happen**:
query panel will not change 

**How to reproduce it (as minimally and precisely as possible)**:
* add a new unified alert 
* use testdata datasource where scenario is Random Walk for the query A
**   you will see a timeseries panel with data
*  switch the panel view to table 
** using save  alert is  optional after order panel view change. does not change the problem
*  drag query B to the top of the query list , so the query order is B, A ( was A, B)

**Anything else we need to know?**:
It is affecting only those queries over what the query is dragged  ( in other words which order in the list is changed due that). 

**Environment**:
- Grafana version: 8.4.5
- Data source type & version:  TestData DB, Prometheus DB, MSSQL DB 
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Windows 11
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
Replicated this, but not totally sure about what the expected behaviour it.

**Comment by gjemp** [comment]
![chrome-capture-2022-3-25](https://user-images.githubusercontent.com/4919667/165040477-b9084b52-6e67-48b6-8057-51187ba1573d.gif)
I would expect that it will not change my selected query view mode .
