### ISSUE TITLE
[Bug] singlestat panel not auto-refreshing when options change

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#4809]
It was expected that it would auto refresh itself after the user leave the field, but this doesn't happen. Only after manually refreshing the changes are applied. 
This happens on current nightly, from 25/04/2016 14:16:12

Edit: there are other options suffering from this: Value(min, max, avg...), Decimals and Unit

**Comment by bergquist** [comment]
This bug is for the whole singlestat panel.
