### ISSUE TITLE
Change Request: Adding a Data Source that doesnt support tests

### ISSUE THREAD

**Issue by mattttt** [grafana/grafana#4811]
When a data source does not support testing, you get a big yellow warning/error when adding it for the first time:

![screenshot 2016-04-25 15 03 38](https://cloud.githubusercontent.com/assets/2886187/14795573/153cb8e8-0af7-11e6-844e-58d04b789da3.png)

Instead,ideal behavior would be:
- On the Add Data source screen, change the primary button copy to be `Save` instead of `Save & Test`, and only Save the Data Source.

**Comment by torkelo** [comment]
The message is no longer displayed. Can't change the button text without big changes, I only have access to the data source instance (where the testDatasource method lives) after the data source is created. So to solve that  I would need some kind of flag in plugin.json or an easy way to instantiate a data source that has yet been created.
