### ISSUE TITLE
Remove "filter for this value" from table cells when we don't want filtering (or can't support it)

### ISSUE THREAD

**Issue by tab0r** [grafana/grafana#48129]
The "filter for this value" and "filter out this value" spyglass icons in table cells disrupt UX when they cannot be supported, and there is no built in way to hide them. The "enable filtering" option only hides/removes the filter icon at the top of a column. [Users have noticed this issue](https://community.grafana.com/t/how-to-hide-filter-out-value-and-filter-for-value-option-in-table-columns/29740/8)

**Comment by tab0r** [comment]
This seems to be isolated to use of "Instant" queries. See [this dashboard](https://ops.grafana.net/d/1Te2qaw7k/datasources-filtering-experiment?orgId=1)

**Comment by tab0r** [comment]
Where I would expect to be able to "Filter for this value" but cannot:
![Screenshot from 2022-04-27 09-31-13](https://user-images.githubusercontent.com/4989811/165569619-7e13fb62-08f3-4748-bffd-d9a0a3a23b63.png)

Where the "Filter for this value" spyglass shows up:
![Screenshot from 2022-04-27 09-31-21](https://user-images.githubusercontent.com/4989811/165569630-ee3388b9-abab-48bf-a22e-b9dec41e96e2.png)

What it does:
![Screenshot from 2022-04-27 09-32-11](https://user-images.githubusercontent.com/4989811/165569639-3679e1db-bf98-4c75-b49d-89c4686d00df.png)

It treats the filter label/value assuming it's valid, when it's not. In this case, it's parsed from `logfmt`

**Comment by tab0r** [comment]
Looking at other issues, this appears to a feature with many requests and issues around it:
* [request to be able to turn them off](https://github.com/grafana/grafana/issues/15386)
* [request for number value support](https://github.com/grafana/grafana/issues/12209)
* [broken when combined with prometheus label replace and regex](https://github.com/grafana/grafana/issues/26526)
* [some general confusion about using it](https://github.com/grafana/grafana/issues/11008)
* [UX improvement issue](https://github.com/grafana/grafana/issues/25529)
* [another community thread](https://community.grafana.com/t/turning-off-ad-hoc-filters-in-tables/11856)

**Comment by tab0r** [comment]
Marking this as closed as it appears fixed.

**Comment by mvadu** [comment]
@tab0r  why and how was this fixed? or appeared fixed? As of now I am on Grafana Cloud, and still see this ad-hoc filters showing up in my table visualizations and no way of turning them off. I really don't want the filter option in this case, and its just a hindrance than help.

**Comment by mvadu** [comment]
Just adding for future visitors.. to turn it off you need to add a field override option with Ad-hoc filterable set to false.
![image](https://github.com/grafana/grafana/assets/8618235/925cfb96-9b0a-43b7-8b82-864c4fb924a3)

**Comment by denismoc** [comment]
This is great after find it but it appears to have a bug. 
I've a dashboard that refreshes every 5 mins and once the time frame changes the filters are applied to the query which is really annoying. 
Has anyone experienced this and have a workaround or should I report this a bug?

**Comment by tab0r** [comment]
@denismoc I would encourage you to report it in a new issue, but probably worth linking to this one. The fix for the original issue was in place last year, but the ad-hoc filters are relatively new. Chances are the bug is something to do with that.
