### ISSUE TITLE
[Question] Bool data display issue

### ISSUE THREAD

**Issue by Hewey2** [grafana/grafana#4813]
Hi there. I am new to Grafana and am having an issue with the display of Boolean data on a Panel.

The datasource is OpenTSDB. The database only stores a value when there is a change of state. For example a running indication changes from 0 to 255 when it becomes true. For the rest of the time the data is not saved.

If I choose a time range in Grafana that does not include a state change then the value is not displayed on the panel. Once I zoom out far enough the change of state is included in the time range and the value is displayed. It makes it difficult to diagnose faults when zooming in to get more detail.

Is there a way to force Grafana to look further back in time to look for the last known value and to add that the panel?

Thank you.

**Comment by torkelo** [comment]
no, this is currently not possible.
