### ISSUE TITLE
[Feature Request] Exclude current dashboard from recently used list

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#4814]
With grafana 3.0 it's possible to set a different organization wide default home dashboard. This dashboard is always the first item in the recently dashboard list, where that widget is most commonly used.

I'd suggest to exclude the dashboard the "recently viewed" widget is shown on from the list.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
