### ISSUE TITLE
[Bar chart] Setting axis to hidden now hides both X and Y axes

### ISSUE THREAD

**Issue by greg-mcnamara** [grafana/grafana#48148]
**What happened**:
I have recently upgraded from Grafana 8.3.6 to 8.4.6 and I noticed that the new version has "broken" some existing bar charts by hiding both the X and Y axes when previously only the Y axis was hidden. In 8.3.6 the setting Axis -> Placement for Bar chart panels would only hide the Y-axis when set to Hidden. I have some bar charts with categorical data on the X-axis and I want to display the bars as relative values, but I don't need the absolute values referenced or displayed so I don't need the Y-axis. Was this breaking change intentional? How do I get that functionality back?

**What you expected to happen**:
Bar charts with Axis -> Placement set to Hidden to continue only hiding the Y-axis as in previous versions.

**How to reproduce it (as minimally and precisely as possible)**:
In version 8.3.6:
- Add panel
- Select type Bar chart
- Set Axis -> Placement to Hidden
- Only the Y-axis is hidden, the X-axis is still displayed

In version 8.4.6:
- As above, but the X-axis is also hidden.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Postgresql 14.2
- OS Grafana is installed on: Linux (Kubernetes pod)
- User OS & Browser: Windows 10, Edge
- Grafana plugins: N/A
- Others:

**Comment by torkelo** [comment]
You will need to an override for the time field and add property axis placement, set to auto. Now your x axis should be restored

**Comment by greg-mcnamara** [comment]
Thanks @torkelo will the docs be updated to reflect this new functionality? Currently the docs specify that the Axis settings only affect the Y-axis.

**Comment by torkelo** [comment]
@dprokop @leeoniya I am correct in the above? I think we did a deliberate change so that axis placement affects both axis. Maybe we forgot to update docs?
