### ISSUE TITLE
Adding a member to a team causes PostgreSQL error with grafana v8.4.4

### ISSUE THREAD

**Issue by ledmonster** [grafana/grafana#48158]
**What happened**:

I can't add a member to a team. grafana server responds with 500 error.

**What you expected to happen**:

I want to add a member to a team.

**How to reproduce it (as minimally and precisely as possible)**:

select a team, and try to add a member there

**Anything else we need to know?**:

The issue is reported in the community forum too.
- https://community.grafana.com/t/psql-error-if-adding-user-to-a-team/63705

Here is logs on grafana server.
```
logger=context t=2022-04-21T10:03:42.88+0000 lvl=eror msg="Failed to add Member to Team" error="failed setting permissions for user 4 in team 4: pq: could not determine data type of parameter $1" remote_addr="221.241.190.170, 34.120.248.143"
logger=context t=2022-04-21T10:03:42.88+0000 lvl=eror msg="Request Completed" method=POST path=/api/teams/4/members status=500 remote_addr="221.241.190.170, 34.120.248.143" time_ms=23 size=42 referer=https://grafana.groove-x.io/org/teams/edit/4
```

and PostgreSQL server.

```
2022-04-21 10:03:42.880 UTC [1468552]: [2-1] db=postgres,user=postgres STATEMENT:  
	SELECT
		p.*,
		$1 AS resource_id,
		ur.user_id AS user_id,
		u.login AS user_login,
		u.email AS user_email,
		tr.team_id AS team_id,
		t.name AS team,
		t.email AS team_email,
		r.name as role_name
	FROM permission p
		LEFT JOIN role r ON p.role_id = r.id
		LEFT JOIN team_role tr ON r.id = tr.role_id
		LEFT JOIN team t ON tr.team_id = t.id
		LEFT JOIN user_role ur ON r.id = ur.role_id
		LEFT JOIN "user" u ON ur.user_id = u.id
	WHERE p.id = $2
2022-04-21 10:03:42.880 UTC [1468552]: [1-1] db=postgres,user=postgres ERROR:  could not determine data type of parameter $1
```

**Environment**:
- Grafana version: v8.4.4
- OS Grafana is installed on: GKE. grafana helm chart 6.16.11
- User OS & Browser: Ubuntu 20.04, Brave 1.37.114 (Chromium: 100.0.4896.88)
- Grafana plugins: we use gmail login

**Other**:
It may be a migration related issue

**Comment by mellieA** [comment]
@ledmonster I have a few questions, you mentioned you thought this could be a migration error: 

* Did you recently upgrade your granfana instance? What was the previous version? 
* What version of postgresDB are you using, there is a known issue with some releases per our install guide: 
> Note: PostgreSQL versions 9.5.18, 9.4.23, 9.6.14, 10.9, 11.4, and 12-beta2 are affected by a bug (tracked by the PostgreSQL project as [bug #15865](https://www.postgresql.org/message-id/flat/15865-17940eacc8f8b081%40postgresql.org)) which prevents those versions from being used with Grafana. The bug has been fixed in more recent versions of PostgreSQL.

**Comment by ledmonster** [comment]
> Did you recently upgrade your granfana instance? What was the previous version?

I've been upgraded grafana with following path, but unfortunately, I'm not aware from which version the issue occurs.

- 7.5.2
- 8.1.5
- 8.1.6
- 8.2.5
- 8.3.6
- 8.4.0-beta1
- 8.4.2
- 8.4.3
- 8.4.4 (version I found the issue)
- 8.5.0 (upgraded after I noticed the issue)

> What version of postgresDB are you using, there is a known issue with some releases per our install guide:

I'm using `PostgreSQL 9.6.24` through GCP Cloud SQL.

**Comment by papagian** [comment]
We are able to reproduce it in `main` using PostgreSQL (`9.6.24`) as backend. We believe that is related to #46421.
