### ISSUE TITLE
[feat req]: Pass Authorization header to proxied data source API

### ISSUE THREAD

**Issue by jazdw** [grafana/grafana#4815]
I'm writing a data source plugin and there is no way to pass an Authorization header to the data source's REST api call when you use the Proxy access mode.

If you set a header like this, then it works for direct access but with proxy access Grafana tries to use the token itself instead of passing it through to the data sources REST endpoint.

````
this.backendSrv.datasourceRequest({
      headers: {
        'Authorization': 'Bearer ' + this.authToken
      },
      ...
````

**Comment by torkelo** [comment]
yes, might need to have another header name so it does not conflict with Grafana auth. Grafana data source proxy could then translate that header name to `Authorization`. 

For example instead of setting `Authorization` set `X-DS-Authorization` 

Another option you have is to create an Grafana App, which can store secureJsonData (encrypted, never exposed to frontend), and you can use that in calls to APIs: 

https://github.com/raintank/worldping-app/blob/master/plugin.json#L44

**Comment by jazdw** [comment]
Adding an extra header like that was exactly what I was thinking, might I suggest that we implement a generic solution to allow any headers to be passed through, not just Authorization. Unless I'm not seeing it, this doesn't seem to be implemented in the API at all.

**Comment by torkelo** [comment]
well it should not be needed for other things, all other headers are proxied, just Authorization that conflicts with Grafana Auth

**Comment by jazdw** [comment]
Ah ok, right I see now how the proxying of other headers works. Hope the PR I submitted is all good, first time using Go.

**Comment by jazdw** [comment]
@torkelo will this PR be able to be merged in for beta 7? Note the CI test failed due to a ECONNRESET.

**Comment by pmazzuca** [comment]
I have my data source behind a proxy that authenticates using a static API key.  Is there a generic way to update the header info that Grafana sends to the data source proxy so that I can include the API key?

**Comment by MeetzhDing** [comment]
Why grafana plugin.json route doesn't support header mapper?  I think config it in json file can slove this question indeed

**Comment by MeetzhDing** [comment]
> yes, might need to have another header name so it does not conflict with Grafana auth. Grafana data source proxy could then translate that header name to `Authorization`.
> 
> For example instead of setting `Authorization` set `X-DS-Authorization`
> 
> Another option you have is to create an Grafana App, which can store secureJsonData (encrypted, never exposed to frontend), and you can use that in calls to APIs:
> 
> https://github.com/raintank/worldping-app/blob/master/plugin.json#L44

Hello， Can you explain how to use ' Grafana data source proxy ' to translate that header name to Authorization ???
