### ISSUE TITLE
Stacking series with one series of 0 values not working and sets Y-axis to 0

### ISSUE THREAD

**Issue by phriedrich** [grafana/grafana#48165]
**What happened**:

When stacking two series, where one contains only 0 values, they are not stacked. Also since the second series is at 0, the Y-axis starts at 0.

**What you expected to happen**:

* Stacking series even if one contains only zeros.
* Don't set the Y-axis to start at 0.

**How to reproduce it (as minimally and precisely as possible)**:

* I have two series, of which the second one is often filled with zeros, both are stacked. 
* If I open it with a time range where the second one is all zeros (30 days here), they are not stacked and the Y-axis minimum is set to 0:
![1 open with second all zeros](https://user-images.githubusercontent.com/470153/165056077-c0aa314a-bf83-41fd-bc23-f7cbb21367e3.png)
* If I extend the range so the second series contains some values (90 days), still both are not shown stacked:
![2 extend time range](https://user-images.githubusercontent.com/470153/165056253-e2bae52d-0b88-4477-a0de-36c3cff82c3c.png)
* _reloading_ the browser window with this time range shows the correct behavior. Both are stacked, and Y-axis starting at a higher value for better scaling:
![3 after reloading](https://user-images.githubusercontent.com/470153/165056420-58b6abc2-9fd0-40b9-9a40-3524536d6e43.png)
* reducing the time range again to 30 days keeps the correct behaviour, albeit the second series is now all zeros again, it's still correctly stacked and Y-axis starting above 0:
![4 reducing time range](https://user-images.githubusercontent.com/470153/165056931-068a9bb4-32eb-4f82-995d-abefeac6be18.png)
* reloading the browser window brings back the display like the first screenshot

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: Docker Container on Gentoo
- User OS & Browser: macOS 12.3.1, Safari 15.4 and Firefox 99.0.1
- Grafana plugins: standard time series panel

**Comment by leeoniya** [comment]
we try to automatically detect positive and negative stacked series during initial chart creation by scanning the data.

as soon as we find a datapoint > 0, which usually happens within the first few datapoints, that series gets placed into the positive stack. otherwise it goes into the negative stack. that's basically what's going on here.

if we instead scanned all the data for < 0 values, we would almost always be scanning the entire dataset since neg values are much less common.

we could probably switch to putting any >= 0 series ino the positie stack, which would instead miscategorize negative series that also contain 0, but that case is likely less common than this bug.

thoughts @dprokop

**Comment by dprokop** [comment]
@leeoniya I think we should classify 0-only series as (+) stack. I don't have any data to support this, unfortunately (whether positive stacks are more common than negative, wouldn't jump to any conclusions here). 

But regardless of the path we take I expect this kind of issue to show up now and then - so let's also make a clear statement about how we treat 0-only series in our docs, ok?

**Comment by leeoniya** [comment]
> 0-only series

to know this you have to scan every datapoint, as opposed to just finding the first >= 0 datapoint. let's try the cheap variation first in https://github.com/grafana/grafana/pull/48197

**Comment by phriedrich** [comment]
Thank you very much @leeoniya

**Comment by leeoniya** [comment]
thanks for reporting!
