### ISSUE TITLE
[Bug] cant re-import app dashboards.

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#4817]
I have never been able to use the "re-import" dashboard feature to re-load dashboards for an App.

This still isnt working with master.

```
2016/04/26 16:54:39 [plugins.go:167 ImportDashboard()] [E] Failed to install dashboard: A dashboard with the same name already exists
2016/04/26 16:54:39 [I] Completed 192.168.0.110 admin "POST /api/dashboards/import HTTP/1.1" 500 Internal Server Error 41 bytes in 1466us
```

The payload sent in the request is:
```
{"pluginId":"kentik-app","path":"dashboards/kentik-top-talkers.json","reinstall":true,"inputs":[]}
```

Given "reinstall" is set to true, i would expect the existing dashboard to be replaced.

**Comment by torkelo** [comment]
ah, good, there should be an issue for this!
