### ISSUE TITLE
[Bug] Templating Query From Multiple Measurements

### ISSUE THREAD

**Issue by gtrs** [grafana/grafana#4818]
InfluxDB allows to specify multiple measurements in a single `SHOW TAG VALUES` statement. The result of this query, however, returns a separate table for each measurement.

When I use such a query (see example below), grafana only takes the first table.

Example:

The query:
`SHOW TAG VALUES FROM system , ifHCInOctets WITH KEY = host `
returns:
```
name: ifHCInOctets
------------------
key	value
host	router1
host	switch1

name: system
------------
key	value
host	server1
host	server2
```

Grafana just takes the values "router1" and "switch1" for templating.

Versions:
InfluxDB 0.11
Grafana 2.6.0

**Comment by torkelo** [comment]
This is due to a change in InfluxDB 0.11, you need to use latest Grafana 3.0 version to get have full support for InfluxDB 0.11

**Comment by gtrs** [comment]
I just tried grafana 3.0.0-beta51460725904, but I get the same result.

**Comment by torkelo** [comment]
sorry, it is only fixed in beta6 nightly build.
http://grafana.org/download/builds.html

**Comment by gtrs** [comment]
Yes, it works! Thank you!
