### ISSUE TITLE
[Feature request] Add nano scale to Joules and Watts

### ISSUE THREAD

**Issue by algefaen** [grafana/grafana#4819]
From looking at the code, I hope this is a fairly simple request.

We have some data that's measured in nano Joules / micro Watts. If I understand it correctly, adding "nJ" and "nW" to kbn.js will let grafana scale things appropriately, for example a value of 125000000 nW will be shown as 125mW. I've tried to do the opposite: Select "watts" and apply a groovy filter that multiplies the data by 0.0000001, but it doesn't seem to scale the other way - it shows "0W", not "125mW".

If there's a way to achieve this without altering grafana code then I'm all ears. My data lives in elasticsearch, if that matters.

(Thanks for an awesome tool!)

**Comment by torkelo** [comment]
should that multiplication not be `1000000000` instead of `0.0000001` ?

**Comment by algefaen** [comment]
Say I have data in nW in es. Say my reading is 125uW, and my data is "125000". If I selected "Watts" as the unit, and multiplied by 1000000000, I would get gigawatts output. This works as I would expect it to, and I do indeed get GW in the graph. It looks like the scaling doesn't work "the other way", though. If I multiply it with 0.0000000001, it gives me me 0.000125W.

So I would have been happy if I was working on time travelling Deloreans, but it doesn't really work for my low power semiconductor data. ^_^

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
