### ISSUE TITLE
Live measurements table with transformation "Organize fields" doesn't order the values correctly

### ISSUE THREAD

**Issue by hemerfaSICKAG** [grafana/grafana#48195]
**What happened**:
The transformation "Organize fields" doesn't work correctly with live measurements.
New data is inserted into the wrong column when the columns are reorderd with this transformation.

Normal:
![image](https://user-images.githubusercontent.com/102162936/165105431-d7048312-0719-445e-895e-10875f550dd8.png)

Change positions of Min and Max:
![image](https://user-images.githubusercontent.com/102162936/165101494-7ea11381-541e-47b9-ab83-9de24f374957.png)

**What you expected to happen**:
You can use the "Organize fields" transformation with a live measurement to reorder the columns.

**How to reproduce it (as minimally and precisely as possible)**:
 - Generate new table panel
 - Select "-- Grafana --" as Datasource, "Live Measurements" as Query Type and "plugin/testdata/random-2s-stream" for example as Channel
 - Add the "Organize fields" transformation
 - Now change the positions of Min and Max and see how the newly added column values are inserted in the original column.

**Environment**:
- Grafana version: 8.4.4
- Data source type & version: -- Grafana -- / Live Measurements
- OS Grafana is installed on: Linux ARM
- User OS & Browser: Windows 10 & Chrome 100.0.4896.127

**Comment by mellieA** [comment]
Reproduced this on 8.5.0 - also noticed that this applies to the time column. If you put min/max in the first column the formatting is off and the time in the second column is wrong: 

![Screen Shot 2022-04-29 at 1 27 18 PM](https://user-images.githubusercontent.com/18175287/166056971-be947c12-1bee-4f2a-b393-e4cf52cff94f.png)

![Screen Shot 2022-04-29 at 1 26 54 PM](https://user-images.githubusercontent.com/18175287/166056999-3bba88eb-ba8e-4460-86d3-d048b94b8c00.png)

**Comment by mdvictor** [comment]
Hey @sickfabian. Thanks for opening this issue. We will have a look as soon as possible and come back to you!

**Comment by hemerfaSICKAG** [comment]
I tested it with Grafana 11 and the issue is solved there.
