### ISSUE TITLE
Table Panel coloring shouldn't require display of referenced column

### ISSUE THREAD

**Issue by RollingFred** [grafana/grafana#4821]
Grafana 2.6, ElasticSearch, Centos

I have table Panel, Metric set to raw Document, Table Transform "JSON Data".
I'm displaying log entries. I want to color the lines by severity. I have a field "sev" containing a number (1 to 7). (**a separate issue is only 3 colors are available**). I also have a field "severity_text" displaying ERROR, CRITICAL, WARNING, etc...
I use the "sev" column with thresholds to color the lines. I don't want to see the values for this column (as it's a numeric representation of "severity_text".
However, if I do not display it, the coloring doesn't work anymore.

I'd like to be able to select a field to color without having to select it for display.

Thanks!

**Comment by ldktta** [comment]
I would also add the power to show more than one metric by the same query.

example:
Metric: Sum -> network_in
Metric: Sum -> network_out

And to be able to mask the names of columns by a custom text.

example:
Colum: Sum -> change label for "Network Out"

Thank you very much. Grafana is an excellent tool.

**Comment by marefr** [comment]
We've created a new issue, #11418, in favor of this to express the requirements needed to solve this together with several similar feature requests. By this we're hoping to find one solution for solving all (or most) of the feature requests for formatting/thresholds in panels and by that delivering a good and consistent user experience. We hope that this initiative can inspire and guide the community and contributors moving forward.
