### ISSUE TITLE
Templates All option not working with influxDB regex 

### ISSUE THREAD

**Issue by RainerW** [grafana/grafana#4822]
I think we have a 3.x beta running, but not sure. ( Because the grafana ui isn't showing this ), the backend is influx db 0.12.

To create a template for all hosts in my influx DB, i created :
 - created a template with : knoten : SHOW TAG VALUES WITH KEY = "host"
 - This works for Singles singles selections and works for multiselection with : " WHERE "host" =~ /$knoten/ "

BUT when adding "Include All option" with a pattern ".*" (without quotation) this will select nothing.

It looks like the All Option is 'escaped as {.*} to influxdb, which as far as I understand #2555 should be circumvented this by changing the format to regex ... but this option seems to be missing in 3.0x?

**Comment by torkelo** [comment]
this is fixed in master and in latest nightly build. Beta6 will be released later in the week.
