### ISSUE TITLE
Canvas: Improve position UX

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#48229]
We currently define position via top / bottom, left / right which isn't the best UX

Copy Figma's approach of using x,y coordinates where 0,0 is the top left corner of the parent frame. Functionality wise this should just be a conversion and not any substantive change to core layout engine

Current 
<img width="282" alt="Screen Shot 2022-04-25 at 3 48 09 PM" src="https://user-images.githubusercontent.com/22381771/165187154-3e9675eb-d001-46ca-bff8-d1f6b6bbeb29.png">

Desired
<img width="168" alt="Screen Shot 2022-04-25 at 3 49 14 PM" src="https://user-images.githubusercontent.com/22381771/165187198-7bbdc1aa-75fe-4200-b576-b4780732d288.png">

**Comment by drew08t** [comment]
How do we want to handle "Left & right", "Top & bottom", and "Scale"?

For "Scale", we could use "Width %" and "Height %".

For "Left & right" and "Top & bottom", if we are trying to constrain a fixed distance from the right or bottom, it may be misleading to present the user with options for width and height.

**Comment by nmarrs** [comment]
I think % for width / height for scale makes sense.

Hiding width / height for top / left, top / bottom also makes sense to me as well 👍 

I think critical thing here is that positioning becomes based on x / y (visually / conceptually for end user) regardless of underlying constraints

**Comment by nmarrs** [comment]
Actually on a second look it seems that what Figma does is just allows user to edit height / width regardless of constraint which I think is probably what we would want to do as well (i.e. when user types in new width update width regardless of constraint, constraints should only really matter when screen size changes)
