### ISSUE TITLE
Canvas: Add quick positioning UX

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#48226]
Add quick positioning UX (row of icon buttons) that allows user to quickly position selected elements. We can add this in the layout editor options right above the constraints.

https://user-images.githubusercontent.com/22381771/165180844-e98e63dc-de24-49b1-bcf3-65ecc2de4f9f.mov

![Screen Shot 2022-04-25 at 2 49 21 PM](https://user-images.githubusercontent.com/22381771/165180858-c87139c7-2152-4c4f-9cfc-d50b10cbdb05.png)

Options in order are as follows:
`Align left`
`Align horizontal centers`
`Align right`
`Align top`
`Align vertical centers`
`Align bottom`

I think we don't need to worry about the additional option drop downs at this point for beta (`Tidy up`, `Distribute vertical spacing`, and `Distribute horizontal spacing`)

**Comment by radiorental** [comment]
for the icons, 16x16 svg or png?

**Comment by adela-almasan** [comment]
svg. thank you!
