### ISSUE TITLE
Canvas: Improve element resizing UX

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#48231]
Currently the user can resize an element in canvas so that it completely disappears. Figma's approach to solve this is to "mirror" the element based on the amount resized

Implemented a stopgap solution (https://github.com/grafana/grafana/issues/49289)

Current UX

https://user-images.githubusercontent.com/22381771/165189989-1d19f12e-9b85-4012-8b12-7362fe80db80.mov

Desired UX

https://user-images.githubusercontent.com/22381771/165190079-eb586546-9a28-4f82-96b9-9dea79238616.mov

**Comment by adela-almasan** [comment]
Postponed for a future release (TBD).
