### ISSUE TITLE
Feature request: allow using grafana-cli to install plugins from a git path

### ISSUE THREAD

**Issue by azylman** [grafana/grafana#4823]
I forked the influxdb 0.8 data source plugin to fix [a bug](https://github.com/grafana/influxdb-08-datasource/pull/5). Right now, there's no way to install my fork of the plugin with grafana-cli. I have to add something else to my build step (in this close, I clone into the plugins directory). It'd be nice of grafana-cli supported installing plugins from a git path or something like that.

**Comment by linkslice** [comment]
I'd like this as well, but would also request support for local zip. e.g. my grafana host is firewalled fromthe internet. So I'd need to download the zip and put it on the host. Something like:grafana-cli -f </local/path/to/zip>

**Comment by mtanda** [comment]
grafana-cli should support this feature, because plugin developer need to wait so long time until release.
I'm waiting for almost 10 days...
https://github.com/grafana/grafana-plugin-repository/pull/31

**Comment by gbrian** [comment]
+1

**Comment by thanhlv93** [comment]
@azylman so How can you install plugin from github ? . I just builded new plugin and when I copy my plugin to /var/lib/grafana/plugins it's not working.
