### ISSUE TITLE
[Bug] New tags not searchable

### ISSUE THREAD

**Issue by johnmca** [grafana/grafana#4824]
I have an issue where new tags are not searchable from /api/search. I created a new dashboard named test and then added a tag named test22 and saved. When accessing /api/search?limit=100&tag=test22
there are no dashboards returned.  Some existing tags are searchable, just not new ones.  
From the dashboard search dropdown I can see the new tag and even the number count on the tag. When I select the tag from search, no dashboards are returned.

Grafana: 2.6
Datasource: mysql (AWS RDS)
OS: AMZ Linux

**Comment by prajwalrao** [comment]
I thought we always needed a query parameter..

 /api/search?query=x&tag=tag_name

**Comment by utkarshcmu** [comment]
I am not able to reproduce this with same stack:
Grafana: 2.6
Datasource: mysql (AWS RDS)
OS: AMZ Linux

New tag addition and search works for me.

I followed these steps:
1. Added new tags.
2. Saved my dashboard. [Saving is required to make an entry in DB]
3. Called /api/search endpoint and it returned the dashboard which I tagged.

**Comment by torkelo** [comment]
yea, I am also not able to reproduce it :(

**Comment by iksaif** [comment]
This seems to be a duplicate of #3623
