### ISSUE TITLE
Table panel: filter table columns error v8.5.0

### ISSUE THREAD

**Issue by q337881648** [grafana/grafana#48246]
**What happened**:

If not open enable pagination,  the following errors will appear in the filter table columns.
Only the first column filter is normal, other errors will occur.
Cannot set properties of undefined (setting 'getRowProps')

![image](https://user-images.githubusercontent.com/22782870/165267045-e5b8b157-7aea-40cd-be16-fa43d5c29ee5.png)

![image](https://user-images.githubusercontent.com/22782870/165264666-2643aef5-b0a8-4e3f-b5d7-8f496dac6cf5.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
Thanks for reporting this @q337881648
