### ISSUE TITLE
Nav: support dynamic menu items for plugins

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#48243]
[Slack thread](https://raintank-corp.slack.com/archives/C01C4K8DETW/p1650868976327229)

**Important!** Update the Slack thread if this is prioritised by the team.

### What is the problem?
![screenshot_2022-04-25_at_09 40 16](https://user-images.githubusercontent.com/9974811/165262436-e56aaa5f-be4c-41d6-ad36-3f0919f31abd.png)

There are scenarios when we would like to add items to the menu-item of a plugin dynamically, for example based on the response of an API request. This is currently not possible, the backend-generated NavTree is "static". Although adding this functionality can have implications (SSR, etc.), I think it could be a valuable addition and something that is worth talking about.

**Links**
[Docs on how to specify plugin menu items (static)](https://github.com/grafana/grafana-plugin-examples/tree/master/examples/app-basic#how-to-add-menu-items-to-the-left-sidebar)
[Current NavTree generation on the backend](https://github.com/grafana/grafana/blob/68ca5b2e0561d33fd7910ae605b608225fbe3d87/pkg/api/index.go#L249)
[Using the NavTree on the frontend](https://github.com/grafana/grafana/blob/3c6e0e8ef85048af952367751e478c08342e17b4/public/app/core/components/NavBar/NavBar.tsx#L56)
[Using the NavTree on the frontend (next version)](https://github.com/grafana/grafana/blob/ebe34ddcbaa2f43b112b9f7dfe41c233810ad637/public/app/core/components/NavBar/Next/NavBarNext.tsx#L59)

**Comment by academo** [comment]
@leventebalogh is this something we can move to the extension points?

**Comment by leventebalogh** [comment]
That might be a good point actually! I think we need to brainstorm a bit about it - the main problem with this is that the NavModel is generated on the backend and is sent down as part of the config. The tricky question is what side-effects could it cause if we only change it from the frontend (what other parts of the app should be notified).

**Comment by zsofiakm** [comment]
One thing I can immediately think of that would be impacted by the extension points approach is the command palette. The command palette also relies on the nav tree for searching pages.

**Comment by sympatheticmoose** [comment]
It would be interesting to see if we get more requests or use cases around this, but I think we should hold off for now. Dynamic changes to the menu could potentially negatively impact users' navigation if what they expect to see keeps changing.

**Comment by leventebalogh** [comment]
I will close this issue for now, and we can revive it once we feel it's important.

**Comment by sympatheticmoose** [comment]
hold off closing for now, we could still get some more feedback on this before a final decision :)
