### ISSUE TITLE
Icon Panel: support file upload

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#48259]
- [x] basic support under a dev-mode-only feature flag https://github.com/grafana/grafana/pull/46749
- [x] switch the implementation to use SQL-based FS storage
- [ ] security hardening
   - [ ] `svgs` https://github.com/grafana/grafana/issues/50597
   - [ ] `jpg`, `png`, `gif`, `webm`, `webp`
   - [ ] rate limit
- [ ] add at least one integration test
- [ ] make sure file size validation can't be circumvented
- [ ] list uploaded files
- [ ] UX improvements
   - [ ] override file flow
   - [ ] prettify preview

**Comment by nmarrs** [comment]
The decision was made to remove icon panel from Grafana core starting in v10.1. We recommend using [the canvas panel](https://grafana.com/docs/grafana/latest/panels-visualizations/visualizations/canvas/) instead for this functionality
