### ISSUE TITLE
Convert all remaining enzyme tests to React Testing Library

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#48253]
Enzyme doesn't officially support react 18, or even react 17 yet...

- [x] #49586
- [x] #49063
- [x] #48292
- [x] #49067
- [x] #49587
- [x] #49250
- [x] #49588
- [x] #49589
- [x] #48283
- [x] #48886
- [x] Convert `packages/grafana-ui/src/components/Logs/LogMessageAnsi.test.tsx` to RTL
- [x] #55030
- [x] https://github.com/grafana/grafana/pull/48982
- [ ] #57884
- [x] #48260
- [x] #49707
- [x] #49507
- [x] #48290
- [x] Convert `packages/grafana-ui/src/slate-plugins/braces.test.tsx` to RTL
- [x] Convert `packages/grafana-ui/src/slate-plugins/clear.test.tsx` to RTL
- [x] Convert `packages/grafana-ui/src/slate-plugins/runner.test.tsx` to RTL
- [x] Convert `packages/grafana-ui/src/slate-plugins/suggestions.test.tsx` to RTL
- [x] #50348
- [x] #50349
- [x] #50402
- [x] #50577
- [x] #57885
- [x] #57886
- [x] #51227
- [x] #49992
- [x] #57887
- [x] Convert `packages/jaeger-ui-components/src/TraceTimelineViewer/ReferencesButton.test.js` to RTL
- [x] #49107 
- [x] #49119
- [x] #51258
- [x] #51266
- [x] #51365
- [x] https://github.com/grafana/grafana/pull/49148
- [x] #51299
- [x] https://github.com/grafana/grafana/pull/49148
- [x] #56017
- [x] https://github.com/grafana/grafana/issues/51688
- [x] #56178
- [x] #50041
- [x] #51300
- [x] #57888
- [x] #51741
- [x] #57889
- [x] #57890
- [x] #56275
- [x] Convert `packages/jaeger-ui-components/src/common/CopyIcon.test.js` to RTL
- [x] #49827
- [x] #49994
- [x] #50332
- [x] #49590
- [x] #51146
- [x] #51625
- [x] #49835
- [x] #56800
- [x] Convert `public/app/features/alerting/AlertRuleList.test.tsx` to RTL
- [x] #53952
- [x] #50668
- [x] #49591
- [x] #49435
- [x] #49430
- [x] #49592
- [x] #49593
- [x] #49594
- [x] #50251
- [x] Convert `public/app/features/datasources/DataSourceDashboards.test.tsx` to RTL https://github.com/grafana/grafana/pull/51294
- [x] #51147
- [x] #49595
- [x] #49596
- [x] #56790
- [x] https://github.com/grafana/grafana/issues/52712
- [x] ~Convert `public/app/features/explore/RichHistory/RichHistoryStarredTab.test.tsx` to RTL~ https://github.com/grafana/grafana/pull/49492
- [x] ~Convert `public/app/features/explore/SecondaryActions.test.tsx` to RTL~ https://github.com/grafana/grafana/pull/48745
- [x] https://github.com/grafana/grafana/pull/48404
- [x] #49597
- [x] #50673
- [x] #49598
- [x] #49599
- [x] #49299 
- [x] https://github.com/grafana/grafana/issues/49399
- [x] https://github.com/grafana/grafana/issues/49467
- [x] https://github.com/grafana/grafana/issues/49808
- [x] https://github.com/grafana/grafana/issues/49914
- [x] https://github.com/grafana/grafana/issues/49974
- [x] https://github.com/grafana/grafana/issues/49975
- [x] #48257
- [x] #48256
- [x] #48255
- [x] #49403
- [x] #49402 
- [x] #49404
- [x] https://github.com/grafana/grafana/issues/52713
- [x] #51154
- [x] #49406 
- [x] #54331
- [x] https://github.com/grafana/grafana/issues/52714
- [x] https://github.com/grafana/grafana/issues/52715
- [x] https://github.com/grafana/grafana/issues/52716
- [x] https://github.com/grafana/grafana/issues/52717
- [x] https://github.com/grafana/grafana/issues/52718
- [x] #53958
- [x] #48254

**Comment by xrisaD** [comment]
Hi @ashharrison90, I would like to contribute on that one

**Comment by ashharrison90** [comment]
Hi @xrisaD 👋 sure, go for it!

**Comment by xrisaD** [comment]
Hi @ashharrison90, 
could you hep me open an issue for: Convert `packages/grafana-ui/src/components/Logs/LogLabels.test.tsx` to RTL?
Thank you :)

**Comment by ashharrison90** [comment]
@xrisaD here you go https://github.com/grafana/grafana/issues/48886

**Comment by ashharrison90** [comment]
Hey @edith007 and anyone else that wants to work on this 👋

That's great! Feel free to pick one, raise a PR and tag me as a reviewer. Thanks!

**Comment by svennergr** [comment]
Hi @ashharrison90 ,

just fyi: I already fixed `packages/jaeger-ui-components/src/common/CopyIcon.test.js` in https://github.com/grafana/grafana/pull/49271.
