### ISSUE TITLE
Cloudwatch AssumeRole broken for af-south-1 on 8.5.0

### ISSUE THREAD

**Issue by MeNsaaH** [grafana/grafana#48267]
**What happened**:
I've been using the `awsAssumeRoleArn` on cloudwatch to authenticate and fetch metrics and logs. After upgrading to `8.5.0` however, I throws this error for the `af-south1` region. 

```shell
1. CloudWatch metrics query failed: InvalidClientTokenId: The security token included in the request is invalid status code: 403, request id: b5b1acac-0061-4a79-baad-9acc85efd60b 2. CloudWatch logs query failed: UnrecognizedClientException: The security token included in the request is invalid
```

Other regions seem to be working fine. A rollback to 8.4.6 seems to resolve the issue:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
- Configure EKS IAM Role for service account for Grafana
- Allow the IAM Role attached to the Service account to be able to assume another role with Cloudwatch access
- Create new cloudwatch datasource and try to assume new role in `af-south-1` region. 
- Save and test and the error pops up

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Kubernetes
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by iwysiu** [comment]
After an initial investigation, I believe this is linked to https://github.com/grafana/grafana-aws-sdk/issues/46 , which, interestingly, was meant to solve this problem.

**Comment by MeNsaaH** [comment]
🤦🏿 . Anyway around it?

**Comment by iwysiu** [comment]
Hi @MeNsaaH ! Don't worry, we're going to look at this more next week and work on a fix 🙂  Unfortunately I think you'll have to wait on v8.4.x until then.

**Comment by sarahzinger** [comment]
Ah I was able to recreate this error on main just now, I'm not sure why this is still breaking, going to keep investigating this week.

**Comment by MeNsaaH** [comment]
@sarahzinger  I was about to say it still fails on `8.5.1`.  It seems you've already reproduced the error. 👍🏿

**Comment by sarahzinger** [comment]
@MeNsaaH I'm reading through https://github.com/grafana/grafana-aws-sdk/issues/46 after which I believe caused this bug and I'm wondering do you have `AWS_STS_REGIONAL_ENDPOINTS=regional` set in your environment variables?

**Comment by MeNsaaH** [comment]
@sarahzinger  I've checked and I don't. I'll set that and let you know how it goes

**Comment by MeNsaaH** [comment]
@sarahzinger  setting `AWS_STS_REGIONAL_ENDPOINTS=regional` seems to fix the issues 👍🏿 . Shouldn't that be the default value?

**Comment by sarahzinger** [comment]
@MeNsaaH I'm glad that fixed the issue for now at least 🎉 

Regarding your question of should that be the default, it's a good question, and I'm not sure the answer on that, will see if the team has any thoughts. 

I did some poking around to see what I could find on this. 
- It does seem like the current default is legacy and the future is going to be regional? https://docs.aws.amazon.com/sdkref/latest/guide/feature-sts-regionalized-endpoints.html
- it does look like users have wanted this functionality before: https://github.com/grafana/grafana/pull/21773
- I'm guessing we want to err on the side of not causing breaking changes, and relying on whatever defaults the sdk provides?

**Comment by sarahzinger** [comment]
so discussed this briefly with some folks here. I think for now we'll close this issue since the issue has been resolved for now, but I do think there might be some work we'll have to do to prepare customers if and when we upgrade the sdk with the new default. 

Thanks for bringing this to our attention, I imagine we could do some work to improve documenting how to handle this better on our end!

**Comment by hitk6** [comment]
Anyone who bumped on this post which looking for solution of `The provided token is malformed or otherwise invalid` in opt in regions.
Checkout: https://repost.aws/knowledge-center/iam-validate-access-credentials
