### ISSUE TITLE
[Bug] remove headers and template dropdowns on embedded panels

### ISSUE THREAD

**Issue by yee379** [grafana/grafana#4826]
On 3.0.0beta5: i have setup a templated dashboard and i use the share link to determine the iframe src to put into my webpage for the graph. however, the resultant iframe contains the grafana header and template dropdowns. How do i remove these items from the graphs?

**Comment by torkelo** [comment]
this is only possible when you embed a single panel, not the whole dashboard. 

There is already an issue for this.

**Comment by yee379** [comment]
yes, this is for a single panel; when the dashboard is template'd and i use the share iframe link, it still shows the header and the dropdown lists for the templates.

**Comment by torkelo** [comment]
ah, I see that sounds like a bug

**Comment by torkelo** [comment]
cannot replicate this, does your iframe url contain `dashboard-solo/`  ?

**Comment by manishakhurana25** [comment]
I am using grafana 5.0 and is facing the same issue.. when i am sharing grafana panel to my web page its displaying the headers.. Can someone pls help me as to how can i remove the header from the panel when it is displayed on my web page?

**Comment by janbols** [comment]
I'm using grafana 5.1.0 and sharing a panel on my dashboard by using it as an embedded iframe. In the screenshot below you can see the result of the iframe url. 

You can fold open the panel title and select view/share/more... I would expect those features to be removed from the embedded version of the panel.

 ![screenshot from 2018-05-31 08-59-45](https://user-images.githubusercontent.com/1818153/40767183-13ab403c-64b2-11e8-965f-e99e0fb6cfe0.png)

**Comment by marefr** [comment]
@janbols could you please create a separate issue since this issue is closed. Thanks

**Comment by janbols** [comment]
Ok, I did on  #12124
