### ISSUE TITLE
[Feature Request] Dashboard-wide CSV Export of data

### ISSUE THREAD

**Issue by yee379** [grafana/grafana#4827]
Would it be possible to get a global 'Export CSV' command for an entire dashboard? (rather than on a per panel basis). Some of my users, for some reason, like to download all the data and import into excel.

**Comment by royemmerich** [comment]
One problem I envisage with this is if you have duplicated plots in various panels. Data would be duplicated.

Another consideration is whether to create one CSV file for all data in all panels or one CSV file per panel?

**Comment by yee379** [comment]
I don't think duplication of data would be an issue - Easy enough to
remove; but it's difficult to consolidate the data.

**Comment by schaebo** [comment]
Another option would be a zip file with all the available single csv files.

**Comment by colramos-amd** [comment]
This would be extremely helpful to me.

Any updates on this? Has similar functionality since been implemented?
