### ISSUE TITLE
Images in alert notifications tied to a panel

### ISSUE THREAD

**Issue by jtheory** [grafana/grafana#48287]
To keep parity with screenshots in notifications in legacy alerting.
* Use the existing grafana-image-renderer to generate screenshots for notifications
* only for alerts that have a `dashboardId` and `panelId` configured

This is proposal 2 in the design doc below.
Epic #47275 covers the long-term, flexible feature.

Initial proposal, prototype and exploration
https://docs.google.com/presentation/d/1ss7tiI5NA092J2ZqWXjMGE7NTRR7MdAjqlkermA8yIA/edit#slide=id.g7a34fe5133_3_198

Design document discussing the road to images in alerting for Grafana 9
https://docs.google.com/document/d/1gdQuJ7xBwcP6Zj2u_0VUid1j8w_3gF-qDMwJIMAHmj4/edit

Related discussion: https://github.com/grafana/grafana/discussions/38030

**Comment by yuri-tceretian** [comment]
It is worth mentioning that In the legacy alerting a panel query and the corresponding rule query were synchronized. In Grafana 8 alerting it's not true anymore: panel and alert rule queries are on their own, and therefore there is a chance that the panel displays something different than the alert.  Therefore, I think we should mention that important detail somewhere.
