### ISSUE TITLE
Azure Monitor: Re-saving a data source removes its client secret

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#48282]
**What happened**:

When first saving an Azure data source, if the credentials are fine, it succeeds but clicking on that a second time causes the secret to be removed and it errors:

![Screenshot from 2022-04-26 16-51-21](https://user-images.githubusercontent.com/4025665/165328452-933f8ec5-b2cd-44ea-b796-9101e46835c3.png)

**What you expected to happen**:

The data source to be validated again, with the same credentials.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0-pre
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by fridgepoet** [comment]
I think we can close this issue because it's a broader problem https://github.com/grafana/grafana/issues/48525
Please re-open if I'm mistaken and we want to track here
