### ISSUE TITLE
Multiple Annotations per rule when running Unified Alerting in High Availability (HA) mode.

### ISSUE THREAD

**Issue by gotjosh** [grafana/grafana#48294]
**What happened**:

In Unified Alerting, with an alert rule that's tied to a panel, I saw a number of annotations for the same alert instance that matches the number of replicas currently running in my cluster. 

In HA mode, alert rules are evaluated twice - and then deduplicated in the Alertmanager. Because annotations are created as an alert rule evaluates and then saved to the database, we write twice the amount of potentially _needed_ annotations to the database and thus people see them in their Graphs. This is because, in HA mode, the two instances share the same database.

**What you expected to happen**:

Expected to only see 1 line (annotation) ever on the panel per alert instance when running Grafana in HA mode.

**How to reproduce it (as minimally and precisely as possible)**:

Set up an alert rule that's tied to a panel, have it fire, and scale-up grafana to > 2 replicas.

Even if we deduplicate alerts at an alertmanager level, alerts still get evaluated on both replicas meaning annotations are created twice.

**Comment by nadeda01** [comment]
We are seeing the same issue.

**Comment by armandgrillet** [comment]
This does not match our expectations on HA work, are you able to get more info on why this is happening or does this need an additional investigation?

**Comment by yuri-tceretian** [comment]
With introduction of https://github.com/grafana/grafana/pull/50197 that made all tickers of all Grafana produce the same ticks, this problem can be solved in two ways:
- update the state manager to check whether annotation for the state already exists. Probably just unique key constraint by fields alert_id, org_id, epoch, text would be sufficient along with handling that error in code.
- deduplicate on read by grouping by the fields above.

**Comment by grobinson-grafana** [comment]
Even when Grafana is run in HA mode, shouldn't the labels for a firing alert be the same irrespective of which Grafana instance fired the alert?

For example, if I have an alert rule on metric `http_requests_total{status="500"}`, each Grafana instance in Grafana HA will fire an alert with the labels:

```
alertname=test, instance=nginx:80, job=nginx, status=500
```

**Comment by grobinson-grafana** [comment]
Even when Grafana is run in HA mode, shouldn't the labels for a firing alert be the same irrespective of which Grafana instance fired the alert?

For example, if I have an alert rule on metric `http_requests_total{status="500"}`, each Grafana instance in Grafana HA will fire an alert with the labels:

```
{alertname="test", instance="nginx:80", job="nginx", status="500"}
```
