### ISSUE TITLE
Plugins Catalog: Use PageHeader component

### ISSUE THREAD

**Issue by jackw** [grafana/grafana#48319]
As highlighted in #48315 we should use the same PageHeader component in the Plugins Catalog that the rest of the app uses.

**Comment by Ukochka** [comment]
Seems like it is done already in this commit https://github.com/grafana/grafana/commit/159607fe6f5f2db997b2d42124a6464a73898434#diff-23e3f7c06850c3adbfd40c8854c54a78ae2225d8bac07cac70a0e33b27ef5865
