### ISSUE TITLE
Dashboards: support showing changes when saving a dashboard

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#48310]
Currently when saving dashboards, there is no way to know what (if anything!) you have actually changed.  We added a UI to show changes, but it currently requires setting the feature toggle "saveDashboardDrawer" -- at grafana 9, we should not have this flag, and ideally start getting feedback on the behavior ASAP.

The main issues with the drawer are:

1. When navigating away from a dashboard with *unsaved* changes, we show a modal, then link to a drawer 😬 
https://user-images.githubusercontent.com/705951/165420300-8f265ca9-d1cd-4e06-898c-65efa936e5be.mp4
    * Should the "unsaved changes" dialog happen in the drawer?  (also a bit awkward) but nice to immediately see what would happen
    * Is this interaction awkward, but not bad enough we should block releasing the other improvements?

2.  When there are many nested changes, the "user friendly" view is not so easy to understand.  This can happen for simple operations like moving a dashboard.
     * simple solution: https://github.com/grafana/grafana/pull/48309
     * this could obviously be a much larger project to identify the meaning behind changes

**Comment by zsofiakomaromigrafana** [comment]
1) I think that interaction is not great, but after discussing it with UX, it looks like it would be better to think through the search interactions we have on dashboards and panels and make changes in a consistent way. So I am okay with sticking with this interaction for now.

2) I couldn't find a good example of how we could present the diff in a better way. I'll let others review the PR and raise their concerns (if any). If there are no concerns then let's release it and see what feedback we get.
