### ISSUE TITLE
viewers without permission to explore still can use /api/ds/query, isn't it a security problem?

### ISSUE THREAD

**Issue by taleintervenor** [grafana/grafana#48313]
**What happened**:
Explore page has permission restriction which by default refuse viewer to explore the data arbitrarily. But the /api/ds/query almost has the same function as explore page. Viewers can use this api to get and calculate any data they interested. So why this api does not need authorization?
**What you expected to happen**:
/api/ds/query should have same permission restriction as explore page.
**How to reproduce it (as minimally and precisely as possible)**:
keep [viewers_can_edit option] as false, post /api/ds/query anonymously, you can successfully query the data.
**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.7
- Data source type & version: prometheus_2.28
- OS Grafana is installed on: centos7
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@taleintervenor Before we try to test this, can you post an example of the query you're using? Is anonymous access enabled or are you using a user with viewer permission?

**Comment by taleintervenor** [comment]
> @taleintervenor Before we try to test this, can you post an example of the query you're using? Is anonymous access enabled or are you using a user with viewer permission?

Yes, our grafana enabled anonymous access as the following settings:
```
####################################` Anonymous Auth ######################
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = public.org

# specify role for unauthenticated users
org_role = Viewer

# mask the Grafana version number for unauthenticated users
hide_version = true
```

Anonymous visiter to our web site cannot see the explore page. This is OK.
![image](https://user-images.githubusercontent.com/8164697/166889297-ed3e7f10-8ecb-41d0-a815-6ebcd4af96f4.png)
But at the mean time visiter can call api/ds/query to get any data without authorization, such as
```
curl --location --request POST 'https://****/api/ds/query' --header 'Content-Type: application/json' --data-raw '{
    "queries": [
        {
            "datasource": {
                "uid": "w1Ks0L4nz",
                "type": "prometheus"
            },
            "exemplar": true,
            "expr": "node_load1{instance='\''puppet:9100'\''}",
            "format": "time_series",
            "hide": false,
            "interval": "",
            "legendFormat": "load average",
            "refId": "A",
            "queryType": "timeSeriesQuery",
            "requestId": "21A",
            "utcOffsetSec": 28800,
            "datasourceId": 2,
            "intervalMs": 120000,
            "maxDataPoints": 193
        }
    ],
    "from": "now-5m",
    "to": "now"
}'
```
it will get response:
```
{"results":{"A":{"frames":[{"schema":{"name":"load average","refId":"A","meta":{"custom":{"resultType":"matrix"}},"fields":[{"name":"Time","type":"time","typeInfo":{"frame":"time.Time"},"config":{"interval":120000}},{"name":"Value","type":"number","typeInfo":{"frame":"float64","nullable":true},"labels":{"__name__":"node_load1","cluster":"sjtuhpc","instance":"puppet:9100","job":"server","namespace":"pi"},"config":{"displayNameFromDS":"load average"}}]},"data":{"values":[[1651740000000,1651740120000,1651740240000,1651740360000],[0.8,0.48,0.72,0.63]]}}]}}}
```

**Comment by torkelo** [comment]
this is how Grafana data source permissions work, dashboard queries are very dynamic, so for the dashboard to function a user with a viewer role still needs to be able to issue any possible query. 

To isolate and secure data you need to use data source permissions (and create multiple data sources with different data) or use create multiple Grafana organizations and use separate data sources in those.
