### ISSUE TITLE
Replace serial IDs with UIDs at the API level

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#48327]
We need to deprecate serial IDs in Grafana HTTP API to simplify objects provisioning, the current existing IDs on the APIs are listed below:

**The must to have for Grafana v9:**
- [x] #48331
- [x] #48332
- [x] #48333
- [x] #48334

**The nice to have for Grafana v9:**
- [ ] #48335
- [x] #48336

**The bonus for Grafana v9:**
- [ ] #48337

All the following items are not required, ID is enough for both short and long term:
- PanelID
- AlertID
- NotificationChannelID
- OrgID
- AuthTokenID
- DashboardVersionID
- ApiKeyID
- LibraryElementID

The document describe in details IDs existing in Grafana APIs: [API ID/UID Status](https://docs.google.com/spreadsheets/d/1uXm8ItHkQ_Otal1sf7ronTRTpagPfrVS8kDWUTsOmFA/edit#gid=792609984)

Frontend epic:
- https://github.com/grafana/grafana/issues/48850

**Comment by sakjur** [comment]
#48333

I think @papagian mentioned that recipientID is a data source ID?

**Comment by papagian** [comment]
> #48333
> 
> I think @papagian mentioned that recipientID is a data source ID?

correct and actually this is in progress: I will update the #48333 with the details
