### ISSUE TITLE
[Bug] Singlestat coloring invert order applies to entire row 

### ISSUE THREAD

**Issue by dzr0001** [grafana/grafana#4833]
I'm using  3.0.0-beta5, commit: v3.0-beta4+14-gd98839f on CentOS 7 with an InfluxDB 0.12 backend. If I have multiple singlestat panels in a single row, using 'invert order' on a singlestat panel will cause other panels on the same row to invert the color order as well. In order to work around this behavior I must either edit the colors in the interface or reverse them in the dashboard's json.

**Comment by bergquist** [comment]
This was due to a defaultsettnings clone issue that was fixed by https://github.com/grafana/grafana/commit/16dbf3166d2246904a8766d5d403dd23706f4892
