### ISSUE TITLE
Replace dashboardID by dashboardUID in grafana API for V9

### ISSUE THREAD

**Issue by ying-jeanne** [grafana/grafana#48331]
| Http Method  | url | pull request | Assigned |
| ------------- | ------------- | ------------- | ------------- |
| PATCH  | /org/preferences  | [48281](https://github.com/grafana/grafana/pull/48281) | @ying-jeanne |
| PUT  | /org/preferences  | [48281](https://github.com/grafana/grafana/pull/48281) | @ying-jeanne |
| PUT | /teams/{team_id}/preferences | [48281](https://github.com/grafana/grafana/pull/48281) | @ying-jeanne |
| PATCH  | /user/preferences  | [48281](https://github.com/grafana/grafana/pull/48281) | @ying-jeanne |
| PUT  | /user/preferences | [48281](https://github.com/grafana/grafana/pull/48281) | @ying-jeanne |
| GET  | /dashboards/id/versions | [48364](https://github.com/grafana/grafana/pull/48364) | @yangkb09 |
| POST  | /dashboards/id/restore | [48364](https://github.com/grafana/grafana/pull/48364) | @yangkb09 |
| POST | /annotations | [48481](https://github.com/grafana/grafana/pull/48481) | @ying-jeanne |
| POST | /annotations/mass-delete | [48481](https://github.com/grafana/grafana/pull/48481) | @ying-jeanne |
| GET  | /dashboards/versions/:uid | [48364](https://github.com/grafana/grafana/pull/48600) | @yangkb09 |

**Comment by ivanortegaalba** [comment]
Hi @ying-jeanne, @yangkb09 we were working on [this issue](https://github.com/grafana/grafana/issues/52586) to stop using `dashboardIds`. We found the `/connections/` endpoint doesn't return the dashboard ID, only the ID of the pannel library item. More info [here](https://github.com/grafana/grafana/issues/52586#issuecomment-1191509911).

To complete the migration we need that endpoint to return dashboard UID instead. Can you help with that?

**How to reproduce the issue**
1. Go to https://play.grafana.org/library-panels
2. Open network settings and click in one of the library items
3. See there is a call to `api/library-elements/<uid>/connections` which returns only dashboard ID
4. There is also a query to `/search?dashboardIds=<id>` which should be replaced by `/search?dashboardUIDs=<uid>`

**Comment by ying-jeanne** [comment]
the endpoint in problem is Get library-elements by uid /api/library-elements/{uid}/connections, we need to add ConnectionUID which point to dashboardUID

**Comment by ivanortegaalba** [comment]
> the endpoint in problem is Get library-elements by uid /api/library-elements/{uid}/connections, we need to add ConnectionUID which point to dashboardUID

Using the new endpoint and it is already solved in the frontend. Thanks!
