### ISSUE TITLE
[Question] Cloudwatch queries and template variables

### ISSUE THREAD

**Issue by cmalek** [grafana/grafana#4834]
Hello,

I'm using grafana-3.0.0beta51460725904 on ubuntu 14.04, and I'm using the cloudwatch datasource.

I want to graph, say, CPUUtilization for a set of instances on the same graph as a stacked set of graphs.  I saw that you can do that for graphite data sources, and it looked really useful.

So, I've set up a template variable,`$instance_id`, which uses `ec2_instance_attribute` to return some instance ids.  I define it like so:

   ec2_instance_attribute(us-west-1,InstanceId, { "tag:Name": ["www.caltech.edu-prod-*"] })

That seems to work.   In the dropdown that gets created for the variable, I see all the instance ids I expect to see.

Then I defined a graph to use that instance variable:

 * **Metric**: us-west-1 -> AWS/EC2 -> CPUUtilization -> Average
 * **Dimensions**: InstanceId = $instance_id
 * **Period**: auto

If I ensure that "Multi-value" is not checked under "Selection Options" for that template variable, I can select one instance from the dropdown, and see the data for that instance.

But if I do enable "Multi-value" for the template variable, I no longer see any data in the graph, even if I only select one instance in the dropdown.  Selecting "All" or checking multiple instances also causes no data to be displayed in the graph.

Does what I want to do just not work for cloudwatch data sources right now?  Or do I need to do it another way?

best wishes
Chris Malek

**Comment by torkelo** [comment]
cloudwatch datasource does not support multi value variables at the moment.

**Comment by mtanda** [comment]
This PR provide the feature what you want.
https://github.com/grafana/grafana/pull/4421

**Comment by AlexMaksimkin** [comment]
+1 to PR #4421. 
It's really useful thing that we need in prod.
@torkelo is it possible merge it to master?

**Comment by tsupertramp** [comment]
I am waiting for this as well! That would be nice! :)

**Comment by stephanadler** [comment]
+1

**Comment by senthil17** [comment]
Available now

**Comment by Mexx77** [comment]
@senthil17 I using Grafana 5.1.3 and still have the issue, that multi-value variables do not work? How and in what version is this available now? Can you point me to documentation, release note or commit? thx

**Comment by torkelo** [comment]
Multi value variable support for cloud watch is limited due to cloud watch api limitations
