### ISSUE TITLE
Connecting grafana with graphite

### ISSUE THREAD

**Issue by alex-moreno** [grafana/grafana#4836]
Hi,

I'm trying to connect grafana with my graphite instance. I am able to access via browser with no problems, but direct access returns a 504. When click on test connection (adding source) I get this: "Unknown error Cannot read property 'message' of null"

Using proxy simply returns this: "HTTP Error Internal Server Error"

Inspecting in chrome, this last one is trying to connect to a port which is empty (3000)

I am using the docker instances that sitespeed.io is providing.

Thanks in advance.

**Comment by torkelo** [comment]
if you use `direct` access mode your graphite server needs CORS headers defined (browser security checks for accessing another domain from javascript), maybe open an issue with the sitespeed docker container repo

**Comment by alex-moreno** [comment]
Thank you, I will

**Comment by Quentinvarquet** [comment]
Hello @alex-moreno , how did you fix it ? I have the same problem on chrome. Everything works on IE ...
