### ISSUE TITLE
add Drilldown / detail link cause gap in the same row

### ISSUE THREAD

**Issue by nicolelovecoding** [grafana/grafana#4837]
I am running grafana on MAC. And I think I am using the latest grafana version. I have a dashboard that the same row has several panels. The problem is when I am adding Drilldown / detail link to a panel, there will show a gap between panels.

**Comment by torkelo** [comment]
unable to replicate this, can you describe your dashboard (screenshot) or try replicate it at play.grafana.org

**Comment by torkelo** [comment]
closing this due to lack of more detail
