### ISSUE TITLE
"Show this field" does not honor "Wrap lines" option in Explore

### ISSUE THREAD

**Issue by Mario-Hofstaetter** [grafana/grafana#48398]
**What happened**:

When using Grafana Explore with structured logs, enabling `Show this field instead of the message` activates line-wrapping, dispite the `Wrap lines` option being off.

**What you expected to happen**:

`Show this field instead of the message` should honor line wrap settings.

**How to reproduce it (as minimally and precisely as possible)**:

- Go to <https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bfilename%3D%5C%22%2Fvar%2Flog%2Fnginx%2Fjson_access.log%5C%22%7D%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D>
or get some structed logs with long properties, the explore loki query is `{filename="/var/log/nginx/json_access.log"}`
- There are structured `json` logs
- Default: "Wrap lines" and "Prettify JSON" is Disabled
- Expand a message and use `Show this field instead of the message` on a long text property, here `http_user_agent` is suitable
- Long lines are now "wrapped", dispite `Wrap lines` being disabled (See screenshots)

![grafik](https://user-images.githubusercontent.com/33002073/165708276-ca9990fb-ebab-47e9-a414-cec6af174ad1.png)

![grafik](https://user-images.githubusercontent.com/33002073/165707768-39a117ac-e6fa-4a0b-9e1c-216189c038b0.png)

![grafik](https://user-images.githubusercontent.com/33002073/165708054-2e059987-b469-4eeb-84f7-ddb13003b606.png)

![firefox_mdLAlhgzKc](https://user-images.githubusercontent.com/33002073/165709183-3a9b3bd5-d0cb-476b-ab07-07525cbbf3b3.gif)

**Environment**:
- Grafana version: `v8.5.0`
- Data source type & version: loki

**Comment by ifrost** [comment]
cc @grafana/observability-logs-and-traces

**Comment by svennergr** [comment]
Hi @Mario-Hofstaetter,

thanks for reporting this issue!
We implemented a fix, which will be rolled-out with the next Grafana 9 release.
