### ISSUE TITLE
[Feature Request] Allow to use math function on metric results retrieved from Elasticsearch

### ISSUE THREAD

**Issue by hassanfarid** [grafana/grafana#4840]
I think, it will be helpful to be able to play between output of existing metrics and calculate new metric out of it. For example if I have 2 metrics, a) sum of value1, and b) sum of value2, and then I can get 2 more metrics c) ration of (a) / (b) and d) Delta of two metrics (a) - (b)

Grafana information:
* What grafana version are you using? 2.6.0
* What datasource are you using? Elasticsearch
* What OS are you running grafana on? Windows Server

**Comment by torkelo** [comment]
good idea, 

already have an issue for this.:
https://github.com/grafana/grafana/issues/3677
