### ISSUE TITLE
[Feature Request] Support for annotations for Elasticsearch

### ISSUE THREAD

**Issue by hassanfarid** [grafana/grafana#4841]
Grafana information:
* What grafana version are you using? 2.6.0
* What datasource are you using? Elasticsearch
* What OS are you running grafana on? Windows Server

**Comment by torkelo** [comment]
this has been implemented for about 2 years :) 
http://play.grafana.org/dashboard/db/annotations

**Comment by hassanfarid** [comment]
The dashboard says that it is only supported by graphite metric and events.

Is there an example for elasticsearch metric with annotation?

**Comment by torkelo** [comment]
I just linked you one in the previous comment :) 

What version of Grafana are you running? Where do you see that text?

**Comment by hassanfarid** [comment]
Just saw the new annotation you added to it. I understand the idea now. Thanks @torkelo
