### ISSUE TITLE
Unified Alerting workflows

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#48438]
### Background / Why we're doing this

In order to better measure the ease of use of Grafana Alerting, we will map out the user workflows and identify areas of friction and improvement potentials. Part of this effort is to validate our early ideas of critical workflows:

Alert creation
- Automate alert creation and setup via API
- Create an error rate alert from Grafana Cloud Metrics
- Create an alert from Grafana's top 3 most used logs data sources
- Create a baseline alert

Day to day
- Receive an alert from Grafana Cloud Metrics in Slack, Phone or MS Teams
- Silence an Alert from Grafana Cloud Alerting

Admin
- Review monthly alerting data

### Deliverables

1. Validate draft critical workflows
- [ ] Talk to SE team about workflows regarding automating alert creation
- [ ] Collect 3+ screen recordings of engineers creating an alert from top 3 most used logs-based data sources
- [ ] Include questions to validate workflow theses in future exploratory research 

2. Map out workflows
- [ ] Unified Alerting workflow map (Miro board)
- [ ] Legacy Alerting workflow map (Miro board)
- [ ] Comparison of Legacy vs Unified workflows for feature parity and ease of use

**Comment by cbernard-psee** [comment]
Hi @jessover9000  , is there a plan in this issue to include the use case mentionned here?  
[https://community.grafana.com/t/ngalert-grafana-8-alert-feature-how-to-export-import-alerts-as-yml-json/51677/7]

**Comment by cbernard-psee** [comment]
To be noted this is not really a "new feature", since the feature was available in 8.2.7 release ;-)
