### ISSUE TITLE
Allow live reload config and plugins in backend

### ISSUE THREAD

**Issue by woodsaj** [grafana/grafana#4843]
If new plugins are added or removed the grafana-server binary currently needs to be restarted.

It would be preferable if the server could instead just re-scan the plugin directory and update all necessary routes.

**Comment by bergquist** [comment]
https://github.com/grafana/grafana/pull/4844 Could be used as inspiration for solving this issue.

**Comment by bergquist** [comment]
This should include the LDAP configuration file

**Comment by ntting** [comment]
is this issue resolved?

**Comment by bergquist** [comment]
no not yet

**Comment by SamuelToh** [comment]
Looking at the `plugin` code underpinned by the hashcorp` plugin tech, it  shouldn't be too difficult to do this. Will give this a go.

**Comment by SamuelToh** [comment]
Just a quick update on this.
I have got it working (i think) it is on my fork [here](https://github.com/SamuelToh/grafana/tree/4843-restart_endpoint).

Will send a PR once doc is written and test is written.

**Comment by bergquist** [comment]
@SamuelToh awesome! feel free to create the pull request before writing docs so we can review it :)

**Comment by rakheshkumbi** [comment]
Hi @bergquist, is it better to add an automatic reload of configs? So, when user makes changes to the config, grafana should detect the changes in the config and reload the config.

**Comment by azadsagar** [comment]
is this feature still pending ?
