### ISSUE TITLE
CloudWatch: Migrate alias patterns to dynamic labels

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#48434]
Co-authored with @sunker 
 
### What
1) We would like to replace the existing [alias patterns](https://grafana.com/docs/grafana/latest/datasources/aws-cloudwatch/#alias) system in the CloudWatch plugin with [dynamic labels](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/graph-dynamic-labels.html) from the [GetMetricData API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricData.html).

2) We'll also remove a set of rules for naming metric legends in the case no alias was specified. We want to replace that in favor of always using the metric label that is returned by the GetMetricData API.

### Why

1) We’d like to replace the current alias pattern system with dynamic labels because:
- It’s one of the most requested features among our open source users and paying customers. Ref: https://github.com/grafana/grafana/discussions/43894 https://github.com/grafana/grafana/discussions/38337 https://github.com/grafana/grafana/discussions/43386)
- Dynamic labels already support all patterns in the current alias pattern system, so it will be easy to migrate
- Beyond support for the existing patterns, dynamic labels have support for some 20 additional patterns
  
2) We’d like to remove the current rules for naming metric legends because:
- It will align our UI better with the CloudWatch API
- Always using the metric label returned by the API will create parity across the different metric query types and query modes that the plugin supports. 
- The metric legend naming rules are inconsistent, unintuitive and error-prone. Ref: grafana/grafana#45189 grafana/grafana#40114 https://github.com/grafana/grafana/issues/20729 https://github.com/grafana/grafana/issues/20927 

### Problem with the alias pattern system
In case an alias pattern is not provided, Grafana will create a legend name based on the following rules:
- If it is a math expression, the ID becomes the metric legend.
- If it is an inferred search expression (wildcard used in the metric search builder dimension field), the label returned from the GetMetricData API becomes the metric legend.
- If it is a Metric Query, the label returned from the GetMetricData API becomes the metric legend.
- For all other metric query types, `{MetricName}_{Stat}` becomes the metric legend. 

The above rules are difficult to follow. 

The `{MetricName}_{Stat}` rule used to make sense when the CloudWatch plugin used the [GetMetricStatistics API](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_GetMetricStatistics.html) which allowed multiple statistics per query. Since the GetMetricData API only supports one statistic per query, visualizing the statistic in the legend is no longer useful. 

The request query is processed by Grafana to format alias values, and it would have become increasingly difficult to parse queries such as math expressions (especially search expressions) and SQL queries and further evolve the alias pattern system.

### Proposed solution
A feature flag to use dynamic labels will be enabled by default in Grafana 9.0.

There will be a migration of existing Grafana alias patterns to dynamic label patterns. The migrated value will be placed in a new "label" field. In case the migrated label is not an empty string, it will be sent in the request to the GetMetricData API and the API response's label will be used as the metric legend.

The migration will be handled on the fly, and will be propagated to the dashboard json model only when the user opens the query editor. Once the user has saved the dashboard model with the migrated label value, migration won't happen again. 

The time zone used in the dashboard [time range picker](https://grafana.com/docs/grafana/latest/dashboards/time-range-controls/#dashboard-time-settings) will be used in the label options for the GetMetricData API request. 

In case dynamic labels are enabled and a label is specified, it should also be in link that is used for deep linking between Grafana and the CloudWatch console.

Disabling this feature flag will revert to the alias pattern system and previous alias formatting logic will be followed. The alias field will be considered deprecated and removed in a future version of Grafana. During this period, we won’t fix bugs related to the alias pattern system.

#### Migration examples
Legacy alias patterns will migrated to the equivalent dynamic label as follows:

| Legacy alias pattern   | Dynamic label                 |
|------------------------|-------------------------------|
| `{{region}}`           | `${PROP('Region')}`             |
| `{{period}}`           | `${PROP('Period')}`             |
| `{{metric}}`           | `${PROP('MetricName')}`         |
| `{{label}}`            | `${LABEL}`                      |
| `{{namespace}}`        | `${PROP('Namespace')}`          |
| `{{stat}}`             | `${PROP('Stat')}`               |
| `{{[dimension name]}}` | `${PROP('Dim.dimension_name')}` |
| `Metric: {{metric}} Period: {{period}}`           | `Metric: ${PROP('MetricName')} Period: ${PROP('Period')}`         |
| `{{metric}} {{period}} {{stat}} {{[dimension_name1]}} {{[dimension_name2]}}`           | `${PROP('MetricName')} ${PROP('Period')} ${PROP('Stat')} ${PROP('Dim.dimension_name1')} ${PROP('Dim.dimension_name1')}`    |

### Breaking changes
* According to the dynamic labels documentation, you can use up to five dynamic values per label. There’s currently no such restriction in the alias pattern system, so if more than 5 patterns are being used the GetMetricData API will return an error. 
* Also, dynamic labels only allow ${LABEL} to be used once per query. There’s no such restriction in the alias pattern system, so in case more than 1 is being used the GetMetricData API will return an error. 
* When no alias is provided by the user, Grafana will no longer fallback with custom rules for naming the legend. 
* In case a search expression is being used and no data is returned, Grafana will no longer expand dimension values, for instance when using a multi-valued template variable or star wildcard `*` in the dimension value field. Ref https://github.com/grafana/grafana/issues/20729
* Time series might be displayed in a different order. Using for example the dynamic label `${PROP('MetricName')}`, might have the consequence that the time series are returned in a different order compared to when the alias pattern `{{metric}}` is used

### Tasks
- [x] #48501
- [x] #48529
- [x] #48578
- [x] #48613
- [x] #48502
- [x] #48510
- [x] #48683
- [x] #48797
- [x] #49158
- [x] #48513
- [x] #49462

**Comment by sunker** [comment]
Closing this issue since all sub tasks are implemented.
