### ISSUE TITLE
Only the first query makes the correct Exemplar request

### ISSUE THREAD

**Issue by roadSurfer** [grafana/grafana#48451]
**What happened**:
First query in a time series chart had `exemplar: true` as expected and data was recived.
Second query did not, the value wast `false` when it should have been `true`.

**What you expected to happen**:
Both queries to request and receive Exemplar data.

**How to reproduce it (as minimally and precisely as possible)**:
Run Prometheus with Exemplar support enabled
Create a new time series chart with two queries that should have Exemplar data.
(Copy and pasting the first query is fine)
Disable Exemplars for the first query.
Enable them again.
Observe that the Exmplars are removed and added back.
Disable Exemplars for the second query.
Enable them again.
Observe that the second query will no long request Exemplars

**Anything else we need to know?**:
A forced page refresh will solve the issue

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: Prometheus 2.5.0 (Exemplars enabled), SpringBoot 2.6.6, OpenTelemetry 1.12.1 JavaAgent
- OS Grafana is installed on: KDE  Neon
- User OS & Browser: KDE Neon, Firefox
- Grafana plugins: None

![ExemplarWrong](https://user-images.githubusercontent.com/38717523/165788871-d4038899-e1e4-40ad-819b-de46fab50cb8.png)

**Comment by zoltanbedi** [comment]
This is by design, we only run the first exemplar query if the metric names are same. It would gave back the same exemplars if we wouldn't and you would see two different symbols in the same position which would be confusing.

**Comment by roadSurfer** [comment]
The metrics are not the same though, and when it is working (e.g. after a forced page refresh) separate Exemplars for the different services are seen as one would expect:
![DIfferentExemplarMetrics](https://user-images.githubusercontent.com/38717523/166261947-948cf2b2-4884-4830-9e9b-77a6b24339d2.PNG)
