### ISSUE TITLE
Unknown error InfluxDB Error: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by Alpanakabra** [grafana/grafana#4845]
Hi iam trying to Add influx Db data source to grafana , but when i test connection it give me cannot read property 'message' of null error.

i have follwoing version of influx db
Visit https://enterprise.influxdata.com to register for updates, InfluxDB server management, and monitoring.
Connected to http://localhost:8086 version 0.9.6.1
InfluxDB shell 0.9.6.1

i am very nre to influx db and grafana , please kind me how can i fix this problem

**Comment by Alpanakabra** [comment]
![grafana](https://cloud.githubusercontent.com/assets/18720508/14886841/95fc1bc4-0d70-11e6-973e-107b896e1230.PNG)

**Comment by Alpanakabra** [comment]
![influxdb](https://cloud.githubusercontent.com/assets/18720508/14886859/a8c2bccc-0d70-11e6-84cf-9568036ddd69.PNG)

**Comment by leesjensen** [comment]
I got this same message when my InfluxDB server went down. Perhaps your service is not running properly or is not accessible with the provided settings. Have you verified that you can use these same settings from your grafana server to make a request to Influx?

**Comment by Alpanakabra** [comment]
i am trying to connect my datasource form grafana server, and i have installed influxdb using docker container and service seems to
![grafana-influx](https://cloud.githubusercontent.com/assets/18720508/14888598/b8550412-0d78-11e6-93d8-4d24d6b01d96.PNG)
 be running fine

**Comment by Alpanakabra** [comment]
would be great if you can help me with the same

**Comment by torkelo** [comment]
make sure the url you specify is accessable from the browser (as you specified direct access)

**Comment by Alpanakabra** [comment]
Ok thanks .. i will sort it

**Comment by xLorix** [comment]
I solved by changing Data Source, Http Settings:
Access, changed from _direct_ to _proxy_
