### ISSUE TITLE
Log volume legend-buttons do not filter the logs

### ISSUE THREAD

**Issue by tjsampson** [grafana/grafana#48450]
**Describe the bug**
When attempting to filter the log levels down, the toggles are not filter the actual logs. The Log Volume panel updates, but not the Log panel.

**To Reproduce**
1. Go To Explore Loki
2. Select some logs that produce multiple log levels (info, debug, error, warning, etc.)
3. Select a single Log Level to filter on

**Expected behavior**
The Log lines filter down to only the selected Log Level

**Actual behavior**
All Logs are still showing, regardless of the Log Level toggle that was selected. No filtering is happening.

**Environment:**
 - Infrastructure: Kubernetes
 - Deployment tool: helm
 - Version: First noticed this when I updated to 8.4.6 and it is still broken in the newly released 8.5.0
 
![Info](https://user-images.githubusercontent.com/8485836/165788575-f63fa239-1ef0-415f-853f-b1f416b473bf.png)
![Error](https://user-images.githubusercontent.com/8485836/165788586-0b9b3d68-1a83-4950-8962-93e636855a8f.png)
![Error_Info](https://user-images.githubusercontent.com/8485836/165788591-a1b474b9-9337-495a-882b-e950858ecdd3.png)

**Comment by ifrost** [comment]
cc @grafana/observability-logs-and-traces

**Comment by tjsampson** [comment]
@ifrost Any updates to share on this issue? I'm surprised this isn't affecting your SaaS offering, or other tenant installations. 

If it helps at all, we are running these helm charts:

https://artifacthub.io/packages/helm/grafana/grafana
https://artifacthub.io/packages/helm/grafana/loki-distributed

**Comment by gabor** [comment]
hi @tjsampson thanks for reporting the issue.
this is a regression that happened when we changed the way we draw the histograms ( https://grafana.com/blog/2022/03/02/new-in-grafana-8.4-how-to-use-full-range-log-volume-histograms-with-grafana-loki/ ) .
we are planning to fix this problem, but right now i cannot tell you when that will happen. for now, as a workaround, i recommend opening a log-line's details, and clicking on the [+] button next to the log-level, to filter by that log-level.

**Comment by gabor** [comment]
fixed in https://github.com/grafana/grafana/pull/49931
