### ISSUE TITLE
Cannot authenticate more than 1 user with LDAP

### ISSUE THREAD

**Issue by aldevar** [grafana/grafana#4846]
Hi!

I'm using grafana Version 3.0.0-pre (commit: v2.6.0-1629-gd3a4b7a) installed via the yum repo. Everything is running on a Centos 7 Virtual Machine

```
# yum info grafana
Paquets installés
Nom                 : grafana
Architecture        : x86_64
Version             : 3.0.0
Révision            : pre1459399258
Taille              : 127 M
Dépôt               : installed
Depuis le dépôt     : grafana
Résumé              : Grafana
URL                 : http://grafana.org
Licence             : "Apache 2.0"
Description         : Grafana
```

```
# cat /etc/redhat-release
CentOS Linux release 7.2.1511 (Core)
```

The issue i have is with ldap authentication. I'm trying to authenticate against an Active Directory.
Everything works fine for me, I can authenticate and i'm automatically put in the right Org (Admin).
When my teammate tries to authenticate, the following errors appear in the grafana logs : 

```
2016/04/28 16:58:54 [I] Completed 10.35.100.142 - "GET / HTTP/1.1" 302 Found 29 bytes in 772us
2016/04/28 16:59:07 [login.go:102 LoginPost()] [E] Error while trying to authenticate user: Error 1062: Duplicate entry '' for key 'UQE_user_login'
2016/04/28 16:59:07 [I] Completed 10.35.100.142 - "POST /login HTTP/1.1" 500 Internal Server Error 53 bytes in 22419us
2016/04/28 16:59:15 [login.go:102 LoginPost()] [E] Error while trying to authenticate user: Error 1062: Duplicate entry '' for key 'UQE_user_login'
2016/04/28 16:59:15 [I] Completed 10.35.100.142 - "POST /login HTTP/1.1" 500 Internal Server Error 53 bytes in 19989us
```

If I delete my accountn then my teammate can authenticate himself on grafana, but I can't authenticate myself. The same error shows in the logs.

**Comment by torkelo** [comment]
try setting a correct mapping for ldap email property

**Comment by aldevar** [comment]
Thank you, that was a misconfiguration in the ldap properties.
