### ISSUE TITLE
CloudWatch: Shouldn't remove the client key and secret when config is edited

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#48467]
**What happened**:
When any field in the CloudWatch datasource config is edited, it clears the `Access key ID` and `Secret access key` fields.

**What you expected to happen**:
Changing the non-secret fields should not erase the secret fields

**How to reproduce it (as minimally and precisely as possible)**:
Configure a cloudwatch datasource with Access & secret key, save.
Change the region.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by fridgepoet** [comment]
I think we can close this issue because it's a broader problem https://github.com/grafana/grafana/issues/48525
Please re-open if I'm mistaken and we want to track here
