### ISSUE TITLE
[Bug] Grafana 3.0.0-beta: Unable to set root_url

### ISSUE THREAD

**Issue by dwelch91** [grafana/grafana#4847]
Version: 3.0.0-beta31460467884
OS: Ubuntu 14.04
Datasource: InfluxDb

Trying to get Grafana to run behind nginx at /stats/. Changed grafana.ini to:

`root_url = %(protocol)s://%(domain)s:%(http_port)s/stats`

And restart grafana. 
Will no longer operate properly when hitting it directly (not via nginx). Get 404 errors for all pages in grafana.log. Seems like the same issue that was previously reported against 2.x.

**Comment by torkelo** [comment]
grafana cannot be configured to run properly under proxied subdir and accessed directly under root url.

**Comment by AndriiOmelianenko** [comment]
@torkelo 
I have same issue: 
when I change to `root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/` and restart grafana-server, logs tells me that 
```
Listen: http://0.0.0.0:3000/grafana
```
but I can't access it on that instance.
Nginx proxy works though.

**Comment by torkelo** [comment]
If configured to be accessed begin subpath  then that will work only, (direct access won't work)

**Comment by AndriiOmelianenko** [comment]
@torkelo why isn't it an issue then?
Grafana should be configurable to be available both by actual location (instance where it was started, with port etc.) and configured nginx proxy.
Other web services (kibana etc.) works both ways.

**Comment by torkelo** [comment]
no since Grafana needs to generate links and handle redirects etc, it can only work properly under one URL and not under subpath and under root at the same time, this is true of most complex web apps / systems
