### ISSUE TITLE
Deleting notification policies deletes the wrong policy

### ISSUE THREAD

**Issue by townsendduong** [grafana/grafana#48472]
**What happened**:
In the Notifications policies, I clicked on the trash can icon to delete a notification policy. The last notification policy in the list got deleted instead of the one I tried to delete.

**What you expected to happen**:
I expected the notification policy in the row where I clicked the trash can icon to be deleted and no other rules to be affected.

**How to reproduce it (as minimally and precisely as possible)**:
I was able to reproduce this reliably by running a clean instance of Grafana using images `grafana/grafana:8.5.0`, `grafana/grafana:8.5.1`, and `grafana/grafana-enterprise:8.5.0`. I did not test with other versions.

1. docker run -d -p 3000:3000 -e "GF_ALERTING_ENABLED=false" -e "GF_UNIFIED_ALERTING_ENABLED=true" grafana/grafana:8.5.1
2. Open Grafana in a browser and log in
3. Go to Notification policies
4. Create a new specific policy using a matcher like "rule_uid=1" and save
5. Repeat step 4 several times to have many notification policies with "rule_uid=2", "rule_uid=3", etc.
6. Click on the trash can icon to delete any notification policy and confirm
7. Whatever was the last policy in the list has been deleted

**Anything else we need to know?**:
The same issue occurs when deleting a nested policy. The last sibling policy in the same nested level gets deleted instead of the one that was intended.

**Environment**:
- Grafana version: 8.5.0 or 8.5.1
- Data source type & version: N/A
- OS Grafana is installed on: Official docker image
- User OS & Browser: Windows 10 and Google Chrome
- Grafana plugins: N/A
- Others: N/A

**Comment by zoltanbedi** [comment]
Thank you for your detailed issue @townsendduong I was able to reproduce this in 8.5.1 and on main as well.

**Comment by Sheldun21** [comment]
@konrad147 Hey Konrad, thanks for the update. The Grafana 9 release is ~a month out. Do we have any potential work around customers can use to have things work in the interim?

**Comment by townsendduong** [comment]
@Sheldun21 I believe the fix will be included in 8.5.3 as well.

**Comment by konrad147** [comment]
@Sheldun21 The fix will be released in the next 8.5.x version
