### ISSUE TITLE
When the unit is percentage (percent(0.0-1.0)), the sorting of Tooltip does not work

### ISSUE THREAD

**Issue by murongfeng66** [grafana/grafana#48489]
**What happened**:
![QQ20220429-162631](https://user-images.githubusercontent.com/29116895/165910440-98523c00-1268-479a-aaf8-06eb870549f0.png)

**What you expected to happen**:
values are sorted from largest to smallest
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.1
- Data source type & version: prometheus:2.34.0
- OS Grafana is installed on: docker
- User OS & Browser: MacOS:12.3.1    Microsoft Edge:101.0.1210.32
- Grafana plugins: Time series
- Others:

**Comment by znakaska** [comment]
Even after https://github.com/grafana/grafana/pull/46738, the raw values are [still being sorted](https://github.com/grafana/grafana/blob/90701be19c03a5a2f20856e298160753f49cb8b3/packages/grafana-data/src/utils/arrayUtils.ts#L14-L33) using [Intl.Collator.prototype.compare()](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/compare) which AFAIK [doesn't work properly](https://bugzilla.mozilla.org/show_bug.cgi?id=1312388) for negative or fractional floating point numbers. But then again, I'm not a JavaScript developer so perhaps I'm missing something.

**Comment by peterbourgon** [comment]
Tooltip sorting is apparently done lexicographically on the strings displayed to the user, rather than on the actual underlying values. Consider this example panel, which has tooltip values sort order descending, and a unit of bytes (IEC).

![Screen Shot 2022-05-07 at 03 15 12](https://user-images.githubusercontent.com/114509/167232162-57ef614b-bc11-4e1a-b2dc-fabf31c9624b.png)

The order is clearly based on the strings, not on the actual values.

**Comment by justinsmalley** [comment]
An example of how to easily reproduce using gdev-testdata. The negative values are in reverse order and there is a positive value out of order too.
![image](https://user-images.githubusercontent.com/99200643/167486018-a966c6eb-8ec5-4ee4-b662-51bd43d772ca.png)

**Comment by dprokop** [comment]
This indeed is a bug, caused by the way the internally used `Intl.Collater` works, as described here: https://stackoverflow.com/questions/40107588/intl-collator-and-natural-sort-with-numeric-option-sorts-incorrectly-with-decima
