### ISSUE TITLE
Dashboard: change dashboard ask always to save dashboard

### ISSUE THREAD

**Issue by UlrichThiess** [grafana/grafana#48485]
Since v. 5.0, also in 5.1

- Windows Server 2019
- Grafana OSS 5.0 or 5.1
- Firefox or Chrome
- Reinstalled 4.7 everything is ok

Change dashboard asks to save dashboard even if nothing was changed.

![grafik](https://user-images.githubusercontent.com/79257887/165907417-618ce52e-9b48-4af8-9153-5e51247bf6ce.png)

**Comment by mellieA** [comment]
@UlrichThiess grafana 5.0/5.1 was released in 2018. I tested and this issue does not exist in our current release 8.5.0.

**Comment by UlrichThiess** [comment]
Of course I mean 8.5.1 or 8.4.7.

It's more complicated. I made a movie to show the problem. You have to scroll for it to happen. Maybe it's a plugin I'm using?

I would be happy to activate access to the installation to assess the problem.

https://user-images.githubusercontent.com/79257887/166100495-48a5670c-dcd3-4759-9cfc-fdb86284d709.mp4

**Comment by UlrichThiess** [comment]
@mellieA Please reopen. This issue also exists in 8.5.2. See video above.

**Comment by torkelo** [comment]
Just save the dashboard and it should stop showing, when you scroll down and lazy panels are loaded on demand, sometimes they need to update the panel schema (model), this can cause this dialog to show

**Comment by UlrichThiess** [comment]
I create a new dashboard with a time line panel, i duplicated the panel, saved the dashboard, scroll .... and it will happened also. :-(

https://user-images.githubusercontent.com/79257887/166878890-0c4ab374-1f97-44b6-a58d-3012d4ac778c.mp4

**Comment by UlrichThiess** [comment]
Still not fixed in 8.5.4  - will try 9.0.0b2
Maybe it has to do with my installation on Windows Server 2022 behing Sophos Firewall? But i have no issues with  8.4.7.
