### ISSUE TITLE
newNavigation: icons misaligned on Safari

### ISSUE THREAD

**Issue by zsofiakomaromigrafana** [grafana/grafana#48499]
![image](https://user-images.githubusercontent.com/97596715/165915805-cc395ee8-4197-4772-96aa-367bb5e3e99a.png)
Customer requested to enable newNavigation and it is working well in general. They did report that on Safari 15.4 (17613.1.17.1.13) there is an alignment issue with arrow icon for the menu. We have attached a screenshot. They also confirmed that it renders properly in Chrome so seems isolated to Safari.

**Comment by ashharrison90** [comment]
worth mentioning this isn't limited to the new navigation - this behaviour occurs for every `IconButton` in grafana on safari at the moment:

![image](https://user-images.githubusercontent.com/20999846/166488958-714e21e0-99c1-4465-93ff-2afc78c3ab09.png)
![image](https://user-images.githubusercontent.com/20999846/166489074-f92b6f23-77ba-4540-8fdb-5f351201e55b.png)
