### ISSUE TITLE
Detail group timings default values when overriding

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#48505]
Right now it looks like this which is not useful:
<img width="536" alt="PS 2022-04-29 à 11 26 02" src="https://user-images.githubusercontent.com/2117580/165919032-0bd9c61e-f85e-47d6-ae9b-2466ba4a26d9.png">

Also, we got some user reports that overriding does not actually work and that canceling the overrides also does not work, we should investigate this.

**Comment by jessover9000** [comment]
We also need to decide on how we want to display / surface the information about what overrides what and what the default values are from a UX perspective. I don't know much about user goals or needs here, can anyone add more context?
