### ISSUE TITLE
Rephrase warning when evaluation interval is set with a "for" that is the same or shorter than the evaluation cycle

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#48509]
This message is not clear:
<img width="1365" alt="PS 2022-04-29 à 11 45 12" src="https://user-images.githubusercontent.com/2117580/165922012-89d86d0f-3567-464a-ae4d-95945f494c16.png">

**Comment by peterholmberg** [comment]
@armandgrillet any suggestion what we want to say here?

**Comment by armandgrillet** [comment]
A shorter sentence with an example in a newline could be clearer, @achatterjee-grafana could you help us on that matter? It's quite docs-related.

**Comment by achatterjee-grafana** [comment]
Hello, my suggestion is:

The evaluation duration must be bigger than the interval. Otherwise, your alert will close as soon as it stops receiving any alerting data.

**Comment by achatterjee-grafana** [comment]
Assigning issue to @armandgrillet and @gillesdemey as the work from the docs squad is completed.

**Comment by achatterjee-grafana** [comment]
Adding @GrafanaWriter and @alyssawada for visibility.

**Comment by armandgrillet** [comment]
@gillesdemey Should we block a "for" duration that is less than the evaluation interval if it results in such a behavior?

**Comment by gillesdemey** [comment]
That makes the most sense to me, I'm not entirely sure what use-case there is for a "for" to be smaller than the evaluation interval.
