### ISSUE TITLE
Stat panel: Text mode = Name (only) but I see exta text on panel 

### ISSUE THREAD

**Issue by baur** [grafana/grafana#48516]
**What happened**:

![image](https://user-images.githubusercontent.com/2898361/165926875-c0e8d5ee-9513-4610-9eb8-3f2457549b81.png)

**What you expected to happen**:

Stat panel with only text **"Some text"**

**How to reproduce it (as minimally and precisely as possible)**:

* Panel = Stat
* Query -> Format as = table
* Value options -> Fields = any filed
* Stat styles -> Text mode = Name
* Finally (Query with 3 Field):
Query -> `select 1 as __id, 'some text' as __text, 1 as var_value_for_data_link` 
```
I need extra field var_value_for_data_link to use it in data link
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: any version and v8.5.1 (61fe4a185) also
- Data source type & version: MSSQL
- OS Grafana is installed on: Win10
- User OS & Browser: Chrome

**Comment by zuchka** [comment]
Hi Baur,

I'm confused, can't you set what fields you want to appear?

![CleanShot 2022-04-29 at 15 48 27@2x](https://user-images.githubusercontent.com/37156449/166085896-c09965a7-0287-47fe-9a2e-e5219c1954a0.png)


what does your raw, unformatted data look like?

**Comment by baur** [comment]
@zuchka

> I'm confused, can't you set what fields you want to appear?

In my case want to hide filed **name** `__value` from stat panel, stay only dates,

before

![image](https://user-images.githubusercontent.com/2898361/166395381-92e51af3-81dd-4a3c-9035-7384c2f7cc6f.png)

after

![image](https://user-images.githubusercontent.com/2898361/166395686-d08a0543-94fb-46c3-a7a6-ae4f86e060c3.png)

but It's not possible if more than 3 fields in query
