### ISSUE TITLE
[Bug] Using eye icon to hide queries in graph panel editor results in incorrect legend labels

### ISSUE THREAD

**Issue by joelanford** [grafana/grafana#4851]
I'm running docker images for 2.6.0, 3.0.0-beta5, and master, using a Prometheus data source running on Ubuntu 16.04, and I've noticed this issue in all 3 versions. And I've also noticed it in the binary 2.6.0 tar.gz distribution running on CentOS 7.

Steps to recreate:

1. Create new graph panel
2. Build two queries, A and B, using Prometheus (not sure if it happens with other data sources)
3. Fill in "Legend Format" values for A (e.g. "Query A") and B (e.g. "Query B")
4. Hide the A query using its eye icon.
5. Observe that the graph correctly shows only the result of the B query, but the legend label associated with that time series is "Query A" when it should be "Query B"

When adding a C query with the label "Query C" and with the A query still hidden, the result is the C query being labelled with "Query B" (and the B query still labeled "Query A").  Hiding query B using its eye icon results in the C query being labeled "Query A".

It seems like the "Legend Format" values, whether part of hidden queries or not, are getting used in order on the non-hidden queries.

Hope that all makes sense.

**Comment by utkarshcmu** [comment]
Not able to reproduce this bug using OpenTSDB datasource. Looks like a Prometheus bug.

**Comment by joelanford** [comment]
Yeah it looks like it's around public/app/plugins/datasource/prometheus/datasource.ts:112

`options.targets` is the set of all targets. The hidden targets haven't been filtered out.  However, the hidden targets look like they have been filtered out of the `allResponse` responses (traced back to lines 68-69).

Therefore, `index` is the index of the filtered `allResponse` data, so using it on the unfiltered options.targets causes the bug.

Currently working on a fix.
