### ISSUE TITLE
how to display top 100 order fee in history

### ISSUE THREAD

**Issue by minotaursu** [grafana/grafana#4852]
This question is  similar  to #3332. I use elasticsearch2.1 and grafana2.6. I want display top 100 order fee in history with table. elasticsearch dsl like this `{"from":1,"size":100,"query":{"match_all":{}},"sort":[{"totalFee":{"order":"desc"}}]}` . I try to do it with granfana , but nothing is showed in table.

the config like this

> 
Metric   Max totalFee  Options
Group by Terms orderId  Order by: Term value (desc)
Then by Date Histogram gmtCreate  Interval: 1y, Min Doc Count: 0

**Comment by torkelo** [comment]
strange, that works for me. 

![image](https://cloud.githubusercontent.com/assets/10999/14911071/2afb4e48-0df3-11e6-9b0f-b3e852a854e1.png)

What is the response from your elasticsearch server? (check raw response in chrome dev tools network tab, then response)

**Comment by minotaursu** [comment]
I find the problem. the field of my elasticserch mapping is gmtCreate. but the field of request is still timestamp

`
{
  "size": 0,
  "query": {
    "filtered": {
      "query": {
        "query_string": {
          "analyze_wildcard": true,
          "query": "*"
        }
      },
      "filter": {
        "bool": {
          "must": [
            {
              "range": {
                "@timestamp": {
                  "gte": "1461897855337",
                  "lte": "1461919455337",
                  "format": "epoch_millis"
                }
              }
            }
          ]
        }
      }
    }
  },
  "aggs": {
    "3": {
      "terms": {
        "field": "orderId",
        "size": 0,
        "order": {
          "_term": "asc"
        }
      },
      "aggs": {
        "2": {
          "date_histogram": {
            "interval": "1y",
            "field": "@timestamp",
            "min_doc_count": 0,
            "extended_bounds": {
              "min": "1461897855337",
              "max": "1461919455337"
            },
            "format": "epoch_millis"
          },
          "aggs": {
            "1": {
              "max": {
                "field": "totalFee"
              }
            }
          }
        }
      }
    }
  }
}
`
<img width="755" alt="2016-04-29 4 57 21" src="https://cloud.githubusercontent.com/assets/2766948/14911951/7f2e86f0-0e2b-11e6-9461-a05569ad184e.png">

**Comment by torkelo** [comment]
you need to set the timestamp field used for date range filtering in your data source options.
