### ISSUE TITLE
Loki Query Builder: Remember preferred editor in Explore

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#48534]
For explore it should remember preferred editor

**Comment by torkelo** [comment]
wat does this mean? The editor mode selector should already be remembered.

**Comment by ivanahuckova** [comment]
I thought so as well, but when I was testing it, it didn't work. So I created this issue for it to implement it/make sure it works.

**Comment by loyd** [comment]
Does it work for prometheus too? Now (v9.0.2) I always see the builder mode every time.
