### ISSUE TITLE
[Bug] Tooltip time is not the same as in timeline

### ISSUE THREAD

**Issue by Liudvikas** [grafana/grafana#4853]
![Example](http://storage6.static.itmages.com/i/16/0429/h_1461914039_2668663_257ef4a204.png)

* What grafana version are you using?
 * Version 3.0.0-beta5 (commit: v3.0-beta4+14-gd98839f)
* What datasource are you using?
 * OpenTSDB
* What OS are you running grafana on?
 * Red Hat Enterprise Linux Server release 6.7 
* Renderer
 * The same with Flot and PNG

**Comment by utkarshcmu** [comment]
This is like #4803 

Can you please check all the three preferences? Your user preference (under profile), Org preference (under Org preferences) and Dashbaord default preference (under dashboard settings)?

**Comment by torkelo** [comment]
Can you replicate this on play.grafana.org? 

Anything that would help us replicate it would help :)

**Comment by Liudvikas** [comment]
It is possible to reproduce in play.grafana.org:
1. Open http://play.grafana.org/
2. Settings -> Switch timezone to any other
3. Move mouse on any graph to see the tooltip

Tooltip time and graph time sometimes stay in sync, but sometimes not. If I set all timezones to Default (which was the case for me), tooltip is always not in sync with the graph.

**Comment by torkelo** [comment]
yes, I can replicate it now, when I pick Default in the dashboard settings.

**Comment by utkarshcmu** [comment]
Was able to replicate the bug too !! #4855 is the fix. Comments in #4803 helped in debugging the issue. Thanks @joshrp !!!

**Comment by utkarshcmu** [comment]
Looks like we are ready for 3.0.0 stable release after this bug fix. :)

**Comment by Liudvikas** [comment]
Thanks for fixing this! (And for Grafana! :+1:  :) )
