### ISSUE TITLE
Alerting: instances preview does not respect evaluation behavior

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#48545]
Currently the preview feature for alert instances does not respect the alert evaluation behavior configuration. This is a known limitation but we've identified several ways to improve the preview results.

1. Support the configurations for `NoData` and `Error / Timeout`.
1. Return the `originalState` and `mappedState` so we can visualize those separately.

![image](https://user-images.githubusercontent.com/868844/165970254-0fc19fdb-7082-4bbf-9fef-588adef0503b.png)

Other relevant issue: https://github.com/grafana/grafana/issues/45306

**Comment by konrad147** [comment]
The preview endpoint needs to be fixed before we can make FE changes

**Comment by gillesdemey** [comment]
Currently the existing endpoints for previewing instances don't return the mapped state from what I can recall (though I'm unsure if the states of the instances are affected by the settings or if it's just the alert rule state)

**Comment by armandgrillet** [comment]
We no longer use that endpoint.
