### ISSUE TITLE
Singlestat panel time units should be plural

### ISSUE THREAD

**Issue by jpaw1** [grafana/grafana#4854]
Using 3.0.0-beta5 with InfluxDB 0.9.6 data source...

When creating a Singlestat panel using data with units of time, the units should be plural. i.e. 6.3 day should be 6.3 days, 5 minute should be 5 minutes, etc.

**Comment by Azef1** [comment]
+1 and the must shoud have the choice of presentation:
6.3 days = 6 days 7 hours 12 minutes ...

**Comment by torkelo** [comment]
closing in favor of an already existing issue, https://github.com/grafana/grafana/issues/2971
