### ISSUE TITLE
Some Graphite functions are not available in 8.5.1

### ISSUE THREAD

**Issue by vin011** [grafana/grafana#48554]
**What happened:**

When adding new series from a Graphite data source, the `timeFunction`, `time`, and `round` functions do not show. These functions are listed on [Graphite's documentation](https://graphite.readthedocs.io/en/latest/functions.html), so they are not depreciated and should not have any issues. 
For existing functions on a saved dashboard, a warning appears although the function works.

**What you expected to happen:**

I expect it to show without a warning as it did previously in version 8.3.7.
I expect it to show similar to the other functions in version 8.5.1.

**How to reproduce it (as minimally and precisely as possible):**

1. Run grafana 8.5.1
2. Add graphite data source
3. Try adding a function to series

**How it looks:**

v8.5.1:
![image](https://user-images.githubusercontent.com/104641464/165979099-16ab76f5-d19f-4415-a58a-b7a28bb56dc6.png)
![image](https://user-images.githubusercontent.com/104641464/165979345-3ff532d3-fd15-447c-8208-f169df203b79.png)
(timeFunction and time are not options)

v8.3.7:
![image](https://user-images.githubusercontent.com/104641464/165982289-f7c9f25d-aa85-4740-985f-87c9f1e31200.png)
![image](https://user-images.githubusercontent.com/104641464/165982315-fa3cec9c-1cd3-4d3d-a148-0f4fd23b2263.png)

**Environment:**

- Grafana version: 8.5.1
- Data source type & version: graphite
- OS Grafana is installed on: docker
- User OS & Browser: macOS / chrome

**Comment by bobemoe** [comment]
This is likely related to work done in https://github.com/grafana/grafana/issues/45948 where a hardcoded fallback list of functions was added for when a bug in graphite returns a malformed json. There is link to graphite patch and workarounds listed in that issue too.

**Comment by zoltanbedi** [comment]
I'm going to close this. Thanks @bobemoe for the link. @vin011 please check https://github.com/grafana/grafana/issues/45948 for explanation.
