### ISSUE TITLE
3.0 - Title field is quite short with no tooltip if truncated

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4859]
Using Grafana 3.0 I observed that the dashboard title is now truncated at ~25 characters with a ... after it:

![image](https://cloud.githubusercontent.com/assets/917241/14928210/bd5dc9ba-0e56-11e6-8818-1efafdf91d0c.png)

In 2.x this limit was either non-existent or much higher:
![image](https://cloud.githubusercontent.com/assets/917241/14928232/e6e20d46-0e56-11e6-80fc-db8a789f648b.png)

If you have lots of dashboards and prefix them consistently it is quite easy to overflow the new limit making it hard to tell which dashboard you are looking at [short of reading the URI].

Preference would be to increase the width, and/or add a mouseover to show the full name if it is truncated.  In my example there is tons of screen real estate left to display the full name....

**Comment by torkelo** [comment]
thanks for reporting this! was bug in the responsive css rules that caused the rule for large screens to not take effect.
