### ISSUE TITLE
Scripted dashboard: One graph per matching graphite metric

### ISSUE THREAD

**Issue by Zirafarafa** [grafana/grafana#486]
Hi

I would like to create a scripted dashboard which does a graphite metric find to extract all metrics matching a pattern, and then create one graph for each matching metric.

Are there any examples of this?  Does the scripted.js allow for easy querying/iterating through a graphite query result set?

Thanks
Chris

**Comment by nopzor1200** [comment]
There's a feature we're currently testing that I think meets this exact use case - issue #1888 . 

You can iterate through the graphite namespace to create a panel (or row) per server. 

We'd love your feedback on it. Please feel free to continue the discussion there. Thanks!
