### ISSUE TITLE
Stars: move star check from backend to frontend.

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#48609]
The current dashboard and search APIs include "isStarred" in the object metadata.  This requires the services to know about the user and include special user defined metadata as part of their core payload.

Given that the number of stars is small -- it seems reasonable to simply hold the list of stared UIDs in the frontend, and check manually when displaying a star.  We can also use that to fill up the list of starred items for search -- this will let it match the same semantics a "recent items"

**Comment by torkelo** [comment]
yea, this makes sense. Should simplify the backend search service.
