### ISSUE TITLE
[Bug] appending a invalid character in InfluxDB query

### ISSUE THREAD

**Issue by jpereira** [grafana/grafana#4860]
I have a grafana instance with a single InfluxDB datasource. I created many charts, but the first always shows an error related to a wrong query.

```
q	SELECT mean("value") FROM "webapps_requests" WHERE time > now() - 30m GROUP BY time(1y) fill(null)
```

It results in:

```
{
  "error": "error parsing query: found y, expected ) at line 1, char 86",
  "message": "error parsing query: found y, expected ) at line 1, char 86"
}
```

conclusion: I am completely sure that I don't have this 'y' in my $interval. 

My setup:

* Grafana 3.0
* Influx
* Ubuntu Linux

**Comment by torkelo** [comment]
are you using the panel repeat feature? try specifying a min panel span (in the panel general tab, next to repeat option)
