### ISSUE TITLE
[Templating] Nested templates with multi-pick do not cascade changes to children

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4861]
Using Graphite ds I noticed if the 2nd (or later) nested template is multi-pick enabled that changing the selection at the higher level does not cause the 2nd (or later) template to be refreshed properly.  Observed in my own dashboards and also visible on the play site.

To reproduce:
1) Go to  [http://play.grafana.org/dashboard/db/templated-graphs-nested](url)
2) Select from server template web-server1
3) Select from app template backend
4) Observe web-server1 (now an invalid choice) is still listed and all panels go black
5) If you have a 3rd nested template item the graphite query will also use the now invalid choice causing them to populate with an empty list.  Further, you have to pick a different option from the parent (toggle away and then back) to get the child to refresh properly.

Expected behavior would be instead of displaying an invalid choice (and cascading that to child template items) that it would use the default behavior of all or the 1st item as selected

**Comment by torkelo** [comment]
@nopzor1200 this is now fixed and will be included in 3.0.4
