### ISSUE TITLE
Logs panel: 'Data is missing a string field' displayed when more than one query is used

### ISSUE THREAD

**Issue by fabsrc** [grafana/grafana#48631]
**What happened**:

When using more than one query in a Logs Panel the panel displays a "Data is missing a string field" if none of the queries returns any log entries.

<img width="1103" alt="Screenshot 2022-05-03 at 14 06 20" src="https://user-images.githubusercontent.com/8853782/166451660-55ace4a8-c32b-4358-aa65-aa617263e10b.png">

**What you expected to happen**:

The Logs Panel should display "No data", i.e. the same message that is displayed when only one query is used and the query returns no log entries.

<img width="1096" alt="Screenshot 2022-05-03 at 14 06 36" src="https://user-images.githubusercontent.com/8853782/166451667-e8cf2df1-240b-41bf-8d2f-07bbe163bb2a.png">

**How to reproduce it (as minimally and precisely as possible)**:

1. Add a Loki datasource
2. Create a dashboard with "Logs Panel"
3. Create two queries, which both don't return any log entries
4. Check Log Panel message

**Anything else we need to know?**:

Seems like the same message is displayed when only one query with a transform is used: #46870

**Environment**:
- Grafana version: 8.5.1
- Data source type & version: Loki 2.5.0
- OS Grafana is installed on: Docker grafana/grafana:8.5.1 image
- User OS & Browser: MacOS & Google Chrome
- Grafana plugins: -
- Others: -

**Comment by zuchka** [comment]
Thanks for creating this issue, @fabsrc 

This behavior is not specific to the Logs panel--I reproduced it using mock data and two queries.

I believe this works as intended. See the comment here:

https://github.com/grafana/grafana/blob/main/public/app/features/panel/components/PanelDataErrorView.tsx#L69-L87
