### ISSUE TITLE
3.0b7 - Graphite + render as PNG gives "Cannot read property 'map' of undefined" error

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4864]
Graphite + 3.0b7

Visible on play.grafana.org: http://play.grafana.org/dashboard/db/graph-styles

Or, just edit a graphite ds graph, change render to png, hit refresh in the corner and you will see this error:

![image](https://cloud.githubusercontent.com/assets/917241/14935670/3fd73970-0eda-11e6-9061-44b434e52a06.png)

**Comment by torkelo** [comment]
thanks for reporting this! fixed!
