### ISSUE TITLE
Dashboard: Time range is not updating from url properly 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#48652]
Changing time range and using browser back to change to previous time range is only working the first time (not really figured out when it's working and when it stops)

This means that data links that set time range on current dashboard is also not working.

**Comment by baur** [comment]
Confirm, it reflects to other plugins like [this ](https://github.com/WilliamVenner/grafana-timepicker-buttons) and [this one](https://github.com/isaozler/grafana-shift-selector)

It would be nice to have such native plugins to select date and params on interactive mode (button, list etc) on kiosk mode

**Comment by Sulomus** [comment]
Even after the fix in #48657 the problem in the Grafana Cloud Pro license still persists. As @baur pointed out TimePicker button and Shift plugins are affected by this as well. 

Updating the URL from Table plugin doesn't work also.
