### ISSUE TITLE
3.0 - Modify span from edit menu changes your edit window size making it almost unusable

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4865]
3.0b7 (and visible on 3.0b4 play.grafana.org)

If you modify the span from the edit menu it changes your edit window too.  If you are sizing a singlestat to span of 1 (for example) the edit tabs are almost unusable.

![image](https://cloud.githubusercontent.com/assets/917241/14935786/76f0449e-0edd-11e6-8221-82ccca503e00.png)

Workaround is to 'go back to dashboard' and then edit again and the edit view is full width again.

Also, while in that code maybe remove '0' from a span choice since it results in an unusable panel.

**Comment by torkelo** [comment]
you can also use the + and - icons in the panel menu to change span (as well as drag the right lower corner). 

But this is indeed a bug, one reported before, https://github.com/grafana/grafana/issues/4018
