### ISSUE TITLE
Add documentation for building grafana when cloned from a different user (for contribution)

### ISSUE THREAD

**Issue by Gueust** [grafana/grafana#4866]
When one wants to contribute and fork the repository, he will not be able to do that:

``` bash
cd $GOPATH/src/github.com/*one's account*/grafana
go run build.go setup            (only needed once to install godep)
godep restore                    (will pull down all golang lib dependencies in your current GOPATH)
go run build.go build
```

because some import are absolute in pkg/cmd/grafana-server/main.go such as
    "github.com/grafana/grafana/pkg/log"
    "github.com/grafana/grafana/pkg/login"

provoking such error:

```
pkg/cmd/grafana-server/main.go:23:2: cannot find package "github.com/grafana/grafana/pkg/setting" in any of:
    /usr/local/go/src/github.com/grafana/grafana/pkg/setting (from $GOROOT)
    /home/gueust/go/src/github.com/*account**/grafana/Godeps/_workspace/src/github.com/grafana/grafana/pkg/setting (from $GOPATH)
```

One solution can be that the willing committer creates a symlink from his or her own version to grafana/grafana. The following documentation could be added to the README at the end of the "contribute" paragraph.

> To be able to develop and build grafana on a cloned repository, the easiest is to create a symbolic
> link from your version of the code to $GOPATH/src/github.com/grafana/grafana
> 
> ``` bash
> go get github.com/*your_account*/grafana
> mkdir $GOPATH/src/github.com/grafana
> ln -s  github.com/*your_account*/grafana $GOPATH/src/github.com/grafana/grafana
> ```

An other solution would be to have relative (or automatically discovered) or configurable path in the pkg/cmd/grafana-server/main.go file. This could enable the build of several code base without having to symlink to grafana/grafana all the time we want to build an other version.

**Comment by torkelo** [comment]
this is a problem all go libraries/apps have (thanks to the poor dependency management in go). The simplest thing to do is just clone your fork (or add as origin) to `$GOPATH/src/github.com/grafana/grafana` . But I agree the docs should mention this problem.

**Comment by Gueust** [comment]
I can submit a PR in the next days if you wish.

**Comment by torkelo** [comment]
that would be nice
