### ISSUE TITLE
Can't set custom unit MIN

### ISSUE THREAD

**Issue by baur** [grafana/grafana#48670]
**What happened**:

Can't set custom unit **MIN**

![min_max](https://user-images.githubusercontent.com/2898361/166617832-64763175-2aee-41ab-b092-b3141b38a55c.gif)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: any version, also 8.5
- Data source type & version: MSSQL
- OS Grafana is installed on: Win10
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by zoltanbedi** [comment]
You need to select `custom: min`

**Comment by baur** [comment]
> You need to select custom: min

there is no option **custom**

![image](https://user-images.githubusercontent.com/2898361/166674686-1f133d16-a7f1-4fd2-9af2-ff2753851b10.png)

**Comment by zoltanbedi** [comment]
@baur see
https://user-images.githubusercontent.com/13729989/166677408-390f3bb4-a8f2-4e90-b3ac-4d19a5ef79e9.mp4
