### ISSUE TITLE
Time series: Browser crash when min/max values are the same

### ISSUE THREAD

**Issue by SinRoot** [grafana/grafana#48689]
Chrome tab crash when in panel set Standard options Min and Max same values. 
Firefox tab freeze for 10-20 sec then write to console "Uncaught Out of memory".
Memory usage by Firefox is up to 5Gb+ (default ~1.5Gb) at that moment.

**Reproduce:**

- Login to Grafana (Sign in with Google in my case)
- Create > Dashboard > Add new panel
- Set Data source = TestData DB (or any other metrics)
- In Standart options set Min = 5, Max = 5 (any same values)
- *crash here*

**Win 11, Firefox** _100.0b9 (dev edition)_
Tab freeze, then
> Uncaught Out of memory

**Win 10, Chrome** _version 100.0.4896.127 (Official), (64 бит)_
Tab crash.
> Error code: STATUS_BREAKPOINT

**Arch Linux, Chrome** _version 100.0*_
Tab crash with
> Error code: SIGILL

**Environment**:
- Grafana version: 8.5.2 (tested in v8.4.4 too)
- Data source type & version: Tested on "TestData DB" and "Zabbix" with [Zabbix plugin for Grafana](https://grafana.com/grafana/plugins/alexanderzobnin-zabbix-app/) v4.1.5
- OS Grafana is installed on: Amazon Linux 2
- Grafana installation type: Standalone Linux Binaries
- User OS & Browser: Win 10, Win 11, Arch Linux. Google Chrome and Firefox (dev edition)
- Grafana plugins:
alexanderzobnin-zabbix-app
briangann-datatable-panel 
frser-sqlite-datasource   
grafana-polystat-panel    
- Others: I understand that it is wrong to set the same values, but tab crash (and lose everything I did before) if I made a mistake it is sad

**Comment by zoltanbedi** [comment]
I was able to reproduce this easily in current main. I agree this is not ideal.

**Comment by JoaoSilvaGrafana** [comment]
Thanks for raising this! I reproduced it and it is pretty annoying... I have added it to our board so we can fix it when we have some time soon

**Comment by justinsmalley** [comment]
Found another way to reproduce this in a way that is not a user configuration error and can occur on legitimate data. 

1. Load a data set where the mean is < 1 (e.g "0, 0.5, 0, 0.75,0")
2. Set "Standard Options": Min = 1, and Max is blank/auto

Browser will crash instantly.

Presumably the "Max" value will be set to 1 internally as the next integer rounded up in our dataset.

![Kapture 2022-05-25 at 14 59 58](https://user-images.githubusercontent.com/99200643/170366422-bd417d22-29ba-4b91-a12e-27c957dafd42.gif)

**Comment by Sam-H101** [comment]
I get a similar issue in 8.5.5 or 9.0 
STATUS_BREAKPOINT when loading a very large Prometheus table. It works fine in 8.4.7

**Comment by wzuqui** [comment]
I had this problem too, I updated to version grafana/grafana:9.0.4-ubuntu and now it's working

**Comment by dprokop** [comment]
I can confirm this is still an issue on the latest main, reproduced following steps https://github.com/grafana/grafana/issues/48689#issuecomment-1137844223 . Looking into what's going on there.

**Comment by dprokop** [comment]
I didn't manage to find the problem in Grafana codebase, but I've successfully reproduced this against plain uPlot. No matter whether the range is provided as a function or static value, the range that has the same values makes uPlot crash:

```js
function prepData() {
    let data = [
    [
        1661150543022,
        1661153243022,
        1661155943022,
        1661158643022,
        1661161343022,
        1661164043022,
        1661166743022,
        1661169443022,
        1661172143022
    ],
    [0, 0.25, 0.5, 0.25, 0, 0.25, 0.5, 0.25, 0]
    ];
    return data;
}

function makeChart(data) {

    const opts = {
    title: "Server Events",
    width: 1920,
    height: 600,
    series: [
        {},
        {
        label: "CPU",
        scale: "perc",
        value: (u, v) => (v == null ? "-" : v.toFixed(1) + "%"),
        stroke: "red",
        width: 1 / devicePixelRatio,
        range: () => {
            console.log("range");
            return [0, 100];
        }
        }
    ],
    scales: {
        x: { time: true, auto: false, dir: 1, ori: 0 },
        perc: {
        auto: true,
        dir: 1,
        distr: 1,
        log: undefined,
        ori: 1,
        range: [1, 1]
        }
    },
    axes: [
        {},
        {
        scale: "perc"
        }
    ]
    };

    let uplot = new uPlot(opts, data, document.body);			 
}

let data = prepData();
makeChart(data);
```

It falls into an infinite loop here https://github.com/leeoniya/uPlot/blob/master/src/opts.js#L536

One cannot record perf profile in Chrome, but in firefox it's possible, that's pretty much what's going on:

<img width="1467" alt="image" src="https://user-images.githubusercontent.com/2376619/185935460-c99c497e-a909-427e-8aff-a3a541fb59f2.png">

@leeoniya - think you have time to try fixing this in uPlot?

**Comment by leeoniya** [comment]
> @leeoniya - think you have time to try fixing this in uPlot?

the range() functions in uPlot are final/unsafe by design, as this allows for a user-controlled fallback strategies. i think we should add guards for invalid settings like this in Grafana, since we supply our own ranging function.
