### ISSUE TITLE
Panel Links color on Light theme

### ISSUE THREAD

**Issue by sanchomuzax** [grafana/grafana#48692]
**What happened**:
When you use Grafana with Light theme, you can't see any links in Link Tooltip panel.

Dark theme:
![image](https://user-images.githubusercontent.com/2911588/166670294-da614b0d-d4e1-486a-b672-11e46fc5875e.png)

Light theme:
![image](https://user-images.githubusercontent.com/2911588/166670305-d803a8c9-2970-49a6-b537-1f6643d3eba8.png)

**Environment**:
- Grafana version: v8.5.1 (61fe4a1859)
- Data source type & version:
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Chrome 101.0.4951.54

**Comment by joshhunt** [comment]
Thanks for reporting! This should go out in the next patch release, 8.5.3
