### ISSUE TITLE
Docs feedback: /visualizations/status-history.md

### ISSUE THREAD

**Issue by cicciopizza** [grafana/grafana#48696]
It would be useful to have a vertical scrollbar in status history panel, when the data series are many and the display is not clear:

![Selezione_029](https://user-images.githubusercontent.com/26459829/166676301-c9a0648e-1e22-42f2-8eea-463b33b3a1dd.png)

**Comment by zoltanbedi** [comment]
I don't think this a docs feedback more like a feature request. Please choose feature request when you create a new issue.

**Comment by cicciopizza** [comment]
Sorry, I got the wrong section .... 
I moved it to the right one ... 
sorry again
