### ISSUE TITLE
[Feature Request] Export/Import Datasource

### ISSUE THREAD

**Issue by coding-jj** [grafana/grafana#4872]
For testing multiple Instances and testing is cumbersome to configure the data souces
Please implement a export/import to a data source.
For testing multiple instances/containers it is cumbersome to configure the data souces always from scratch again.

I'm using docker container grafana:grafana
Grafana version: 3.0.0-beta7, commit: v3.0.0-beta6+8-gf6d538b, build date: 2016-04-30 16:41:24

**Comment by akram** [comment]
Hi,

that would be great if we could have a feature similar to `[dashboards.json]` with `[datasources.json]` that we could set in `grafana.ini` file

**Comment by mikaoelitiana** [comment]
I am also looking forward to having this. We work with multiple org that shares same datasources and we have to manually create the datasource in each org. Having and import/export (even as a command line tool) would be really appreciated.

**Comment by daniellee** [comment]
The [provisioning](https://grafana.com/docs/grafana/latest/administration/provisioning/#data-sources) feature partially solves this issue.

Closing this in favour of #11495 which is a more specific issue on exporting the data source to the YAML format that we use for provisioning.
