### ISSUE TITLE
[Feature Request] Grafana Version display on every Page

### ISSUE THREAD

**Issue by notes-jj** [grafana/grafana#4873]
Please implement the display of the version on the bottom line of every Page.
It is difficult to find the version number in different version of grafana, they moved around multiple times. You can see the from the login page. but it is inconvenience to log out to see the version number. If you add the version number simply to every page in a same font. It is easy to see.

Support would be easier, if screenshots directly show the version of grafana, no matter on what page you are. The issue of finding the version number was discussed in #1249 with a little bit other background (read from api). All the mentioned places where the version number is shown are not valid for the current version (3.0.0-beta7).

I'm using docker container grafana:grafana
Grafana version: 3.0.0-beta7, commit: v3.0.0-beta6+8-gf6d538b, build date: 2016-04-30 16:41:24

**Comment by dutchiechris** [comment]
Perhaps also include logged in username when adding this request.

**Comment by bergquist** [comment]
Closing this issue and referencing it to .https://github.com/grafana/grafana/issues/4889

**Comment by torkelo** [comment]
The new page footer is now in master (visible on all pages except dashboard page). 
https://github.com/grafana/grafana/issues/4889

![image](https://cloud.githubusercontent.com/assets/10999/15493905/6093b336-2187-11e6-91aa-3a7dc273dcaf.png)
