### ISSUE TITLE
Where to find the time cost for query in grafana 8.x?

### ISSUE THREAD

**Issue by btdan** [grafana/grafana#48736]
Hello, When I query data in grafana 7.x , I can find the time cost for each query. Just as shown in this picture:
![timeshow](https://user-images.githubusercontent.com/5276480/166856338-9a8ed205-05db-49b2-a7de-f65e5f9b7ab6.png)
However , I can not find the time in grafana 8.x.
Can you tell me how to solve this problem?
Thanks very much.

**Comment by torkelo** [comment]
if you open inspector you can find this info in the stats tab
