### ISSUE TITLE
Alerting: tab doesn't show for anonymous users since 8.5.0, UI errors

### ISSUE THREAD

**Issue by pharaujo** [grafana/grafana#48731]
**What happened**:

Since v8.5.0 the alerting tab on the left stopped appearing to anonymous users when the unified alerting is enabled. Accessing `/alerting` directly shows the unified alerting UI, but with a "404 page not found" banner at the top.
<img width="1297" alt="Screenshot 2022-05-04 at 18 45 32" src="https://user-images.githubusercontent.com/555927/166749168-a1dadf17-143d-41a2-9f25-6af3946f9475.png">

**What you expected to happen**:

I expected the alerting tab and UI to be available, as was the case in v8.4.7.

**How to reproduce it (as minimally and precisely as possible)**:

Minimal grafana config that reproduces the problem:
```ini
[auth.anonymous]
enabled = true
hide_version = true
org_name = Main Org.
org_role = Viewer
[auth.basic]
enabled = false
[users]
viewers_can_edit = true
[unified_alerting]
enabled = true
execute_alerts = false
[alerting]
enabled = false
execute_alerts = false
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.0-8.5.2
- Data source type & version: N/A
- OS Grafana is installed on: linux
- User OS & Browser: macOS 11, Google Chrome
- Grafana plugins: N/A
- Others:

**Comment by LinFor** [comment]
I have the same issue after update to 8.5.2

**Comment by yuri-tceretian** [comment]
@pharaujo @LinFor thanks for reporting the problem. It was fixed and will be included in the next patch release (next week)
