### ISSUE TITLE
sub second granularity

### ISSUE THREAD

**Issue by javicho21** [grafana/grafana#4874]
[Question] How can I modify my Grafana instance to display sub-second granularity on my metrics?

I saw issue #728 but I was unable to make the changes necessary. Can you please advise me on the steps required for changing InfluxDBDatasource and timeSeries.js and implementing sub second granularity?

Thanks

* What grafana version are you using? v3.0.0-beta6
* What datasource are you using? InfluxDB v0.9.6.1
* What OS are you running grafana on? 3.16.0-30-generic #40 ~14.04.1-Ubuntu

**Comment by torkelo** [comment]
you should not have to do anything
