### ISSUE TITLE
ValueMapping by Regex: improve handling of newlines

### ISSUE THREAD

**Issue by fialky** [grafana/grafana#48751]
**What happened**:
When you set up regex replace:
![image](https://user-images.githubusercontent.com/43816134/166898442-c9827e97-f518-47be-8e20-0f577e914f5c.png)

Not all rows are replaced:
![image](https://user-images.githubusercontent.com/43816134/166898781-bf195fc5-cfc6-4153-9a2f-a7b9a80617b2.png)

**What you expected to happen**:
Regex does not fail on some rows: (e.g. 3rd row - manually rewrited)
![image](https://user-images.githubusercontent.com/43816134/166899124-52228972-0359-484b-9b61-c67e473b45a2.png)

**How to reproduce it (as minimally and precisely as possible)**:
- make Table Visualization Overrides - regex replace
- check that **\n** is present in some background data for which regex replace fails

**Anything else we need to know?**:
If **\n** is in background data, regex replace fails:
![image](https://user-images.githubusercontent.com/43816134/166900003-d3ee7cce-f71e-4b73-b63a-d6948b2f7168.png)

If **\\\n** is in background data, regex replace works:
![image](https://user-images.githubusercontent.com/43816134/166903459-406e3cc8-283f-42f2-bb9c-21434cf61c0e.png)

**Environment**:
- Grafana version: Grafana v8.3.5 (a53fcac7b1) and Grafana v8.5.0 (6134e3cf35)
- Data source type & version: Elasticsearch 7.17.0
- OS Grafana is installed on: Kubernetes - official Grafana docker image
- User OS & Browser: Microsoft Windows [Version 10.0.19042.1645] & Microsoft Edge Version 101.0.1210.32 (Official build) (64-bit)
- Grafana plugins: -
- Others: -

**Comment by zuchka** [comment]
Thanks for creating this issue, @fialky 

I couldn't quite reproducing this using your suggested steps. Granted, I used mocked data. Can you try and fiddle with this panel on our public sandbox?

Also to reproduce your scenario exactly can you [inspect your raw request and response](https://grafana.com/docs/grafana/latest/panels/inspect-panel/#view-raw-request-and-response-to-data-source)?

and paste it inside triple backticks (` ``` `) instead of screenshots?
