### ISSUE TITLE
Icon to modify parameter letter on metrics edit page does not work

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4875]
3.0b7 with graphite

I was updating some dashboards to have the best look/feel for Grafana 3.0 and noticed what I thought was a new feature to change the parameter letter for a metric:
![image](https://cloud.githubusercontent.com/assets/917241/14943805/56e645fc-0fe3-11e6-9195-549ef1d23f7a.png)

Unfortunately, if you click the parameter letter nothing happens as verified in Chrome and Firefox.  One can still adjust by editing the JSON manually but this would be a nice feature and I assume was the idea when someone added the icon.

**Comment by torkelo** [comment]
This is not edit query letter, its a query editor collapse feature, graphite query editor does not support/need it (but influxDB and elasticsearch query editors does), hence the dark muted color of the collapse icon. This could be better displayed to lessen confusion.

**Comment by dutchiechris** [comment]
Gotcha, thanks!  I would suggest to update the code that makes it muted to instead remove it if the DS doesn't need expand/collapse support.

**Comment by torkelo** [comment]
I tried that but it looks bad when you mix different data sources (using -- Mixed -- datasource)

**Comment by mattttt** [comment]
@dutchiechris Great feedback, that's interesting. I do agree that we need to have some better feedback when you're only seeing Graphite DS that cannot be expanded.
