### ISSUE TITLE
[BUG] Gauge: better value size handling

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#4876]
Hi,

I using the new feature "Gauge" it's really nice! But i have some bugs...
My use case it's to show SLA. My result:
![gauge](https://cloud.githubusercontent.com/assets/15362041/14950971/11ca920c-1056-11e6-80f2-c5ee86e9cb7e.PNG)

- The text color "100%" should be green instead of red.
- I haven't the color inside gauge  (i think the red color inside gauge represents the value of 1 (100%=1.0) so the unit percent(0.0-1.0) isn't supported ?)
- Is it possible to change text size ? My 100% is too big

Perhaps i made a mistake in my options:
![sla](https://cloud.githubusercontent.com/assets/15362041/14951125/04a72508-1057-11e6-8ab6-5e27c54be997.PNG)

I using Grafana beta7

Thx

**Comment by torkelo** [comment]
since your values are really 0 - 1, your thresholds should be 0.8,0.9

**Comment by Azef1** [comment]
Thx it's works now
![gauge2](https://cloud.githubusercontent.com/assets/15362041/14951371/bb2d7a74-1058-11e6-8b46-0cab6b06206c.PNG)

I try to find a solution for text size

**Comment by Azef1** [comment]
A workaround is to change "unit" to none:
![workarou](https://cloud.githubusercontent.com/assets/15362041/15008156/8995126a-11de-11e6-923c-7f381801abcb.PNG)
The result is better:
![okkkkk](https://cloud.githubusercontent.com/assets/15362041/15008164/a3bb2ad0-11de-11e6-899f-8f9f52099e0b.PNG)

**Comment by torkelo** [comment]
this is fixed now. Now the value font size is used in the calculation to determine gauge value font size.
