### ISSUE TITLE
[Bug]  Graph is not resized when changing Span parameter

### ISSUE THREAD

**Issue by Liudvikas** [grafana/grafana#4877]
![Example](http://i.imgur.com/7d6n2mk.png)

* What grafana version are you using?
 * Version 3.0.0-beta5 (commit: v3.0-beta4+14-gd98839f)
* What datasource are you using?
 * OpenTSDB
* What OS are you running grafana on?
 * Red Hat Enterprise Linux Server release 6.7 
* Browser
 * Google Chrome 50.0.2261.86 (64bit)

**Comment by torkelo** [comment]
this related to changing span while in fullscreen edit mode, you can easily change span while in dashboard mode using the panel menu's plus/minus icons. 

You seem to be using panel repeats as well, and a min span. 

https://github.com/grafana/grafana/issues/4018
