### ISSUE TITLE
[Bug] Span size is lost when using Repeat panel with multiple values

### ISSUE THREAD

**Issue by Liudvikas** [grafana/grafana#4878]
To reproduce:
1. Go to http://play.grafana.org/dashboard/db/templated-graphs-nested
2. Edit "REQUESTS app" graph;
3. Set Span "6", Repeat panel: "server", Min Span: "6"; Back to dashboard
4. On top select any two servers; See how dashboard changes;
5. On top now leave only one server selected; See how Panel expanded (if you edit panel, you will see that the Span is now set to 12).

* What grafana version are you using?
 * http://play.grafana.org
* Browser
 * Google Chrome 50.0.2261.86 (64bit)

**Comment by torkelo** [comment]
if you repeat a panel, it will assume it is the only one on the row, so if you only select one value it will get span 12, it will respect the min span option, but the regular span option is ignored.

**Comment by gabosvk** [comment]
I would say this is rather a bug than a feature. If I setup my row with all the panels I wish to have it like that all the time. Don't understand why this bug was closed... 😞
