### ISSUE TITLE
CloudWatch: Set time zone offset in GMD request

### ISSUE THREAD

**Issue by sunker** [grafana/grafana#48797]
In case the dynamic labels feature toggle is enabled, [LabelOptions](https://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_LabelOptions.html) in the GMD API should be set. Timezone offset should be calculated based on the time settings in the time range picker. 

Part of https://github.com/grafana/grafana/issues/48434

**Comment by daviddone** [comment]
mark
