### ISSUE TITLE
Can't get metrics for Azure Storage Queue (Queue Message Count, for example)

### ISSUE THREAD

**Issue by xiaomi7732** [grafana/grafana#48794]
**What happened**:

Can't get metrics data for Azure Storage **Queue** (Message Count, for example)

**What you expected to happen**:

Be able to get the metrics.

**How to reproduce it (as minimally and precisely as possible)**:

Try to add a metrics query:

![image](https://user-images.githubusercontent.com/3674549/167048139-e5ea69ca-da63-4999-a75c-235f95d87913.png)

**Anything else we need to know?**:

Other metrics works like, like `Storage Account`, `App Service` ... but not the queue, blob, table, etc.
![image](https://user-images.githubusercontent.com/3674549/167047909-82717117-a2cf-425c-858d-54ab6f2660e0.png)

**Environment**:
- Grafana version: v8.4.5 (4cafe613e)
- Data source type & version: Azure Monitor (hosted, where to get the version?)
- OS Grafana is installed on: Azure Hosted.
- User OS & Browser: Windows 11, Chrome.
- Grafana plugins: Azure Monitor
- Others:

**Comment by sarahzinger** [comment]
@xiaomi7732 thank you so much for opening this issue, I can recreate this issue on my end as well, so I'll make sure to share it with the rest of the team to see if we can resolve it!

I'm curious, did you happen to notice this bug recently after upgrading and if so let us know what version of grafana you were previously on, or if this is a more recent issue. I'm trying to pinpoint if this is a regression and when this may have happened. 

Thanks so much for your help!

**Comment by xiaomi7732** [comment]
@sarahzinger Thanks for the quick turn-around. And I am glad you have reproduced it.

I wish I could be more helpful with regarding to which version does the issue happens, but I just start to create a dashboard recently and this is the first version I used.

Let me know if there's anything else that I can help with.

**Comment by aangelisc** [comment]
Hey @xiaomi7732 can you confirm what storage resource you're using? Are you creating a general purpose V2 Storage Account? 

I believe this issue may be due to a change in the way Azure handles queues/tables/blobs/files in new storage accounts. These resources are no longer considered separate from the storage account and so do not show in the general list resources request. When we then attempt to filter returned resources in a resource group they do not exist. We'd have to handle storage accounts in a different way in order to retrieve any nested resources.

**Comment by xiaomi7732** [comment]
Hey @aangelisc Thanks for the update. It is `StorageV2 (general purpose v2)`.

**Comment by xiaomi7732** [comment]
Hey @aangelisc I am glad to see this bug has been fixed. Is there any ETA that we will get it as end user?

**Comment by aangelisc** [comment]
Hi @xiaomi7732, this fix will be released in the next patch version of Grafana, I will try to confirm when that'll be 😊

**Comment by xiaomi7732** [comment]
Terrific! Thanks for the effort!

**Comment by nharper285** [comment]
Hi! Is there any update on this patch? We are currently dealing with the same issue.

**Comment by aangelisc** [comment]
Hi @nharper285, this fix became available in 8.5.4 😊
