### ISSUE TITLE
Loki LogQL: `unpack` log label filters get applied to the wrong part of the query

### ISSUE THREAD

**Issue by danpoltawski** [grafana/grafana#48820]
**What happened**:
When using [unpack](https://grafana.com/docs/loki/latest/logql/log_queries/#unpack) with LogQL, filtering for a label in the UI puts the filter into the wrong part of the query. 

e.g. from the logql query:
```
{unit="ssh.service"} | unpack
````
Clicking on one of the 'packed' labels, puts the filter inside the log selector:
```
{priority!="info",unit="ssh.service"} | unpack
```
This will not work because they are labels generated by the unpack parser.

**What you expected to happen**:
The same as what happens with the `json` parser instead, grafana does the right thing and does the filtering outside of the log selector:
```
{unit="ssh.service"} | json | priority!="info"
```

**How to reproduce it (as minimally and precisely as possible)**:
* Go to the explore view
* On a `packed` log stream, use `| unpack`attempt to filter one of the labels
* Compare the behaviour with `json` parser

![Animation](https://user-images.githubusercontent.com/533249/167153715-8f06cb1a-3efc-4308-8c70-e9782a34a915.gif)

**Anything else we need to know?**:
The ideal solution here would be if grafana knew which were original labels and which were generated.

**Environment**:
- Grafana version:  8.5.2
- Data source type & version:  loki 2.5.0
- OS Grafana is installed on: Debian
- User OS & Browser: Windows/Firefox

**Comment by danpoltawski** [comment]
This looks to be the related issue https://github.com/grafana/grafana/pull/42590

**Comment by joey-grafana** [comment]
Hey @gabor, this is the issue I was talking about :)
