### ISSUE TITLE
When using TimeSeries with repeating panel, the tooltip is on top of each other in Edge

### ISSUE THREAD

**Issue by selvavm** [grafana/grafana#48825]
**What happened**: The tooltip of two panels in a row overlaps on each other so not able to see the metrics

**What you expected to happen**: The tooltip has vertical distance so that they don't overlap (similar to the old graph panel)

**How to reproduce it (as minimally and precisely as possible)**: 
![image](https://user-images.githubusercontent.com/16543422/167180792-7cda9aab-8331-4d1d-b68e-0a5c364e3ccc.png)

**Anything else we need to know?**:

**Environment**: Windows
- Grafana version: Latest
- Data source type & version:
- OS Grafana is installed on: Windows
- User OS & Browser: Edge
- Grafana plugins: TimeSeries
- Others:

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by selvavm** [comment]
@zuchka Hi. I am not able to replicate the same in public sandbox because there is no dashboard has the capability to show tooltip for all the panels at the same time. Do you know how I can modify the dashboard settings to enable this?

**Comment by ashharrison90** [comment]
@selvavm i don't think there's a nice way to solve this unfortunately. the tooltips can be arbitrarily tall, so having some vertical offset won't help all the time. it's also slightly misleading as the tooltip needs to sit where the crosshair is. 

a more general solution would be to rename your series such that they're not so long. 

hope that makes sense!
