### ISSUE TITLE
bug: singlestat is not updating 

### ISSUE THREAD

**Issue by gurjyan** [grafana/grafana#4882]
Version: 3.0.0-beta7, Commit: v3.0.0-beta7+14-g152e085, Build date: 2016-05-02 10:34:07 -0400 EDT
OS X El Capitan version 10.11.13
data source InfluxDB
Singlestat is not updating . I have exactly the same query to select a variable. I am using two grafana presentations: on as a Graph another as a singlestat. The graph forks without a problem, yet singlestat is stuck on a same value.

**Comment by torkelo** [comment]
can you show your singlestat options? What value are you showing in singlestat (current, avg, total?) (set in options tab), can you show the influxdb query and response for the singlestat  panel?
