### ISSUE TITLE
[BUG] singlestat is not updating 

### ISSUE THREAD

**Issue by gurjyan** [grafana/grafana#4883]
Version: 3.0.0-beta7, Commit: v3.0.0-beta7+14-g152e085, Build date: 2016-05-02 10:34:07 -0400 EDT
OS X El Capitan version 10.11.13
data source InfluxDB
Singlestat is not updating . I have exactly the same query to select a variable. I am using two grafana presentations: on as a Graph another as a singlestat. The graph forks without a problem, yet singlestat is stuck on a same value.

**Comment by torkelo** [comment]
did you accidentally open the same issue twice? https://github.com/grafana/grafana/issues/4882

**Comment by gurjyan** [comment]
Sorry, yes I did.
Thanks for your prompt response. Your questions helped me find my mistake. I had "avg" set in the options.
Best,
-vg


----- Original Message -----
