### ISSUE TITLE
Deleting dashboard results in dashboard not found warning

### ISSUE THREAD

**Issue by BitProcessor** [grafana/grafana#48854]
**What happened**:
When deleting a dashboard, a dashboard not found warning is thrown 

**What you expected to happen**:
The warning should not be thrown. The dashboard was deleted, of course it's not found

**How to reproduce it (as minimally and precisely as possible)**:
Delete a dashboard, observe notifications on top right of screen

**Environment**:
- Grafana version: Cloud Advanced v8.5.2 (90701be19)

![Screen Recording 2022-05-09 at 12 02 41](https://user-images.githubusercontent.com/50638541/167387993-4f748be6-e75b-44c8-94e4-f053f29f2ee0.gif)

**Comment by BitProcessor** [comment]
Additional video, showing dashboard creation, saving and deletion (from scratch): 
![Screen-Recording-2022-05-09-at-15 27 44](https://user-images.githubusercontent.com/50638541/167458958-5bac53d7-77e1-412a-821b-ca2a4d11111c.gif)

**Comment by BitProcessor** [comment]
https://github.com/grafana/grafana/pull/50316

**Comment by daniellee** [comment]
This is fixed in Grafana Cloud (current stable is 9.0.7):

![NotFoundFixed](https://user-images.githubusercontent.com/434655/184678307-28d3713e-28b7-480a-ad69-c5877fbe25ee.gif)

Fixed by #50316 in 9.0.1.
