### ISSUE TITLE
Unified Alerting - Azure Resource Graph Query - Failed to evaluatie queries when adding expression

### ISSUE THREAD

**Issue by stefanpetter** [grafana/grafana#48874]
**What happened**:
I want to create an alert based on a numeric value (the amount of active high security alerts in the given Azure context). If the value is above 0, I should be notified. When adding the query (mentioned below) I get the following error : "Error
Failed to evaluate queries and expressions: failed to execute conditions: can only reduce type series, got type numberSet". If I select "Stat" instead of time series and run the query without any expression, the query does work. However, when I re-add the expression, it looks like my selection of "Stat"gets completely ignored and it defaults back to "Time Series" 

**How to reproduce it (as minimally and precisely as possible)**:
- created a new alert rule, 
- used my Azure Monitor datasource 
- Selected 'Azure Resource graph' under 'Service'
- Pasted the following query in:
`securityresources
  | where type =~ 'microsoft.security/locations/alerts'
  | where properties.Status in ('Active')
  | where properties.Severity in ('High')
| summarize count()`

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: Azure Monitor (Core?)
- OS Grafana is installed on: Linux Ubuntu Server 18.04
- User OS & Browser: Windows 10, Firefox 100
- Grafana plugins: JSON API Datasource
- Others:

I also created a forum post about it with screenshots:
https://community.grafana.com/t/grafana-8-alert-azure-resource-graph-query-failed-to-evaluatie-queries-when-adding-expression/65245

**Comment by stefanpetter** [comment]
Someone proposed a functioning workaround in the forum:

Adding 
```
| extend timestamp = now()
```

Will do the trick! It would be nice however if this issue can be fixed. At least the pressue is off :)

**Comment by mellieA** [comment]
@stefanpetter thanks for sharing your workaround. Since it sounds like this isn't really time-series data, are you able to use the table format instead or stat as is demo'd here: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/fundamentals/evaluate-grafana-alerts/#alerting-on-numeric-data-1

**Comment by yuri-tceretian** [comment]
@stefanpetter did you use any expression on top of the query A? For example, "Reduce". If yes, did you try to remove it and make alert rule fire on query A?

**Comment by armandgrillet** [comment]
The plugin should tell us this is not a time series but e.g. a vector so that our expression engine can treat this appropriately.
