### ISSUE TITLE
Grafana 8.5.0 breaks Cloudwatch plugin for AWS in China (Ningxia, Beijing)

### ISSUE THREAD

**Issue by Vimao** [grafana/grafana#48872]
After upgrading from Grafana 8.4.0 to Grafana 8.5.0, application cannout authenticate to AWS in China to access cloudwatch metrics and logs using an IAM role on a different account. During upgrade there were zero changes to how the instance-profile and iam roles are set-up, yet Grafana fails to query any external account Cloudwatch service with error:

![2022-05-10_12-00](https://user-images.githubusercontent.com/47415312/167605623-f9e75b92-2a61-4346-a00b-7a874ea46dd4.png)

This is even weirder as during start-up grafana logs the following entries:

![image](https://user-images.githubusercontent.com/47415312/167605898-32880566-ad5c-4bf9-a2ae-e26f2fdff281.png)

This is for the same role ARN.

It seems that something breaks the creation or acquisition of the authorization token. This is also NOT broken on Global AWS, only on AWS China APIs

**Environment**:
- Grafana version: 8.5.0 - OSS
- Data source type & version: Cloudwatch
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Edge/Firefox on Ubuntu
- Grafana plugins: None

**Comment by mellieA** [comment]
@Vimao this looks like https://github.com/grafana/grafana/issues/48267#issuecomment-1119592852 

The recommendation there was to set AWS_STS_REGIONAL_ENDPOINTS=regional environment variable

**Comment by Vimao** [comment]
@mellieA Thanks! I will check this out and report if that's actually the same issue

**Comment by Vimao** [comment]
Setting Env AWS_STS_REGIONAL_ENDPOINTS=regional fixes this issue

I think such cases as updates to used SDK should be pointed out in changelog, especially if someone finds they break stuff :)
