### ISSUE TITLE
AzureMonitor: Store reference to datasource UID in queries

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#48877]
**What happened**:

Recorded queries (enterprise feature) require a reference to the data source UID in the request for it to work. At the moment, only the data source ID is stored for Azure Monitor queries. See more info in this [link](https://github.com/grafana/grafana-enterprise/pull/3266).

For reference, the DataSource ref is [already part of the DataQuery contract](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/types/query.ts#L53), but it's optional to set. 

**What you expected to happen**:

Recorded queries to work.

**How to reproduce it (as minimally and precisely as possible)**:

See the referenced PR.

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ethirolle** [comment]
@andresmgot @kevinwcyu, just curious if you have an ETA for this fix? I see that the related fix (https://github.com/grafana/grafana-enterprise/pull/3266) is merged and set for next Grafana release. I believe both of these fixes are needed to address the problem raised in https://github.com/grafana/support-escalations/issues/2469.

Thanks!!

**Comment by gelicia** [comment]
> I believe both of these fixes are needed to address the problem 
Sorry for not being more clear, that is not correct. The fix I added should solve this problem for recorded queries.. I asked the azure folks to also include the datasource to bring it in line with what we expect data sources to have.
