### ISSUE TITLE
AzureMonitor: Remove references for Germany cloud

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#48876]
**What happened**:

The cloud for Germany has been removed since Oct 2021. More info here: https://docs.microsoft.com/en-us/previous-versions/azure/germany/germany-welcome.

So we should remove any references to that (in code and documentation).

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by kostrse** [comment]
Lat's have it removed across the board: in Azure Monitor, Prometheus and Grafana Azure SDK.
