### ISSUE TITLE
[Bug] Graph panels "Terms" does not give correct result 

### ISSUE THREAD

**Issue by evil2bart** [grafana/grafana#4888]
Grafana version 3.0.0
Data source: ElasticSearch
OS: CentOS

When I try to use Terms to split the data on a string, it "splits too much".
If I in Elastic have a field with 2 different strings I want to split on: "fruit-banana" and "fruit-apple", the result in Grafana when i split on that field will end up being: "banana", "apple", "fruit", which is not quite the desired result :-)

**Comment by torkelo** [comment]
It is Elasticsearch that is executing your elasticsearch query not Grafana :) 

The behavior is the default behavior on analyzed strings in index. You need to update your elasticsearch document index and specify that his fields should not be analyzed.
