### ISSUE TITLE
Not sending alerts to notification policies

### ISSUE THREAD

**Issue by Danial968** [grafana/grafana#48895]
**What happened**:
Alert is firing. It is attached to a notification policy which is different from the default contact policy.
The alert only sends to default contact policy (email) after 5mins of the alert firing.
No alert is sent to the notification policy (GChat)

**What you expected to happen**:
Should get alerts on both email and google chat.

**How to reproduce it (as minimally and precisely as possible)**:
Create a contact policy pointing to Google Chat and attach it to a notification policy

**Anything else we need to know?**:
When adding google chat to the default notification policy it is able to send the alert
The only log when alerting:
`logger=alertmanager org=1 level=debug component=dispatcher receiver="Default Email" integration=email[0] msg="Notify success" attempts=1`

We just enabled the grafana unified alerting previously was using the legacy alerting with the same grafana version

**Environment**:
- Grafana version: 8.4.3
- Data source type & version: Thanos v0.24.0 with Prometheus v2.33.3
- OS Grafana is installed on: Linux v5.4.+
- User OS & Browser: Google Chrome v101.0.4951.54 (Official Build) (arm64)
- Grafana plugins: None
- Others:
![Alert Rule](https://user-images.githubusercontent.com/42598994/167808356-b7ba79fd-aa0c-4b56-9e4c-dc2dc862ccd3.png)
![Contact Point](https://user-images.githubusercontent.com/42598994/167808014-5f77e809-9f09-4cc2-a1da-4b9def1af220.png)
![Notification Policy](https://user-images.githubusercontent.com/42598994/167808064-6f552a85-cbff-4b84-a270-dca42b144bd4.png)

**Comment by Danial968** [comment]
Realise that the match label selector had to be unique based on the key, was assuming that I could group up based on the folders.

**Comment by mattixpet** [comment]
Just in case this helps anyone else, my issue was that I didn't realize Grafana notification policy AND's the labels. So I had to make a separate notification for all my labels (they were all unique for each alert).

**Comment by Danial968** [comment]
Hey @rahul-janoria I actually just needed all the alerts to go to the same root channel so I added "..." to the group by which just sends all alerts individually to the chat.

This is in notification policies
![image](https://user-images.githubusercontent.com/42598994/227501561-cc6a03ef-897f-49f0-a4c4-9f0338f5c4b4.png)
