### ISSUE TITLE
Jaeger datasource, the search option on service don't allow for typing values.

### ISSUE THREAD

**Issue by heliapb** [grafana/grafana#48905]
**What happened**:
In the Jaeger datasource, when selecting the search option and typing for a service, it doesn't match the service typed, but instead will pick up the first service value. In here a gif of the issue, were I typed Grafana, but after enter, it selected the first service on the service list. It only allows for scrolling for the value in order to select one.

![jaeger](https://user-images.githubusercontent.com/66432275/167867824-506bd6b2-9290-4de8-99b4-6feb7508b807.gif)

**What you expected to happen**:
When typing the service, to mach it with the service on the list.

**How to reproduce it (as minimally and precisely as possible)**:
Have Grafana (8.5.2) with Jaeger (v1.33.0) datasource, and try to search for service by typing for the name of the service.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: Jaeger 1.33.0
- OS Grafana is installed on: Kubernetes version 1.22.6
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others: n/a

**Comment by joey-grafana** [comment]
Hello and thank you for your bug report :) 

This issue was fixed in #48209 and will be released in Grafana 9.0.

**Comment by heliapb** [comment]
Hi there, thanks for the feedback, glad the issue is going to be solved soon.
