### ISSUE TITLE
Grafana unified alerting sending clear/ok alert after 5mins even if alert is in firing state

### ISSUE THREAD

**Issue by sushovan23** [grafana/grafana#48908]
**What happened**: Alert clear is sent even though alert state is firing.

**What you expected to happen**: After alert is state firing. I expect that no clear is sent after 5mins. Rather after my configured repeat interval it should resend the alert to alert manager.

**How to reproduce it (as minimally and precisely as possible)**: Configure Grafana alert in new unified alerting using clickhouse or prometheus query. Set the threshold to make sure that alert is firing state. 

Alert fires and alert state is firing.
We are see alerts in our external alert manager
However after 5mins Alert cleared/ok is sent and alert is closed in alertmanager even though state of alert is firing in grafana.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.7
- Data source type & version: ClickHouse/Prometheus Datasource with External AlertManager
- OS Grafana is installed on: Centos 7
- User OS & Browser: Chrome (mac/windows)
- Grafana plugins:
- Others:

**Comment by sushovan23** [comment]
So Issue seems to be that grafana is not sending the `endAt` time to external alertmanager.
Due to which alertmanager is auto-resolving it based on global config in alertmanager for `resolve_timeout`

So currently I have increased the `resolve_timeout ` in alertmanager to be more than repeat interval for notification endpoint. 

However is there a way to send `endsAt` to alertmanager to avoid having to change that global setting?

**Comment by vc43** [comment]
@sushovan23  Did you find any solution?
