### ISSUE TITLE
[Bug] Grafana 3.0 doesn't create snapshots in firefox and chrome

### ISSUE THREAD

**Issue by Chirico** [grafana/grafana#4891]
I tried to create snapshots from whole dashboards and single panels. It works fine in Chromium. When trying in firefox in get script errors and my browser freezes. In chrome the creating process lasts very long and ends up with an empty snapshot. I tried it on Ubuntu 14.04. Chrome was also tested on Mac

**Comment by torkelo** [comment]
not able to replicate this here :(

**Comment by Chirico** [comment]
My fault, I created a tool which generates dashboards in JSON format and publishes them via Grafana API and had an error in generating the panel IDs. I thought the IDs were unique inside a single row and not the whole dashboard. Seems to work now.
