### ISSUE TITLE
Grafana Alert / Loki Source with Long Range Errors out

### ISSUE THREAD

**Issue by zanderson-aim** [grafana/grafana#48913]
**What happened**:
Trying to make alert for a long range in loki ( > 3 days) gives a error about parsing
`Failed to evaluate queries and expressions: failed to execute conditions: failed to execute query A: cannot parse "3.928s" to a valid duration`
**What you expected to happen**:
Should return the number of events in the time range. 
**How to reproduce it (as minimally and precisely as possible)**:
Running this Query `count_over_time({source=~"ESET.*"}[1m])` against my Loki source for any time frame > 3 hours results in a instance pop up / error.
![image](https://user-images.githubusercontent.com/39353837/167918985-37358b95-e04d-42ba-950a-69e042a8ba9b.png)

**Anything else we need to know?**:
I'm able to run the same query under Explorer and it works fine. It is a long query, probably 3-4mins in most of my runs under Explorer.  Adjusting the range results in the same error, but a different number of s are displayed in the error messages.
**Environment**:
- Grafana version: 8.5.2
- Data source type & version: Loki 2.5.0
- OS Grafana is installed on: Official Docker Image
- User OS & Browser: Windows 10 / FireFox
- Grafana plugins:
- Others:

**Comment by broferek** [comment]
This is not only affecting queries > 3 hours but actually any queries with a time range greater than 3 hours since I can reproduce the problem with a query ranging `from now-7h to now-3h` for instance.

**Comment by Cobesz** [comment]
We have the exact same problem. Lowering the range to 1hr solves it.

**Comment by armandgrillet** [comment]
This seems to come from the expression engine, @grafana/loki-squad do you know where this could be coming from?

**Comment by imtzc** [comment]
同样遇到了这个问题，请问有解决方案吗？我选什么时间段都不可以，但是相同的查询在Explore中是可以的

**Comment by ttcy** [comment]
> We have the exact same problem. Lowering the range to 1hr solves it.

Thanks! Resolved this problem with lowering the range. It was 15m in my case.

**Comment by imtzc** [comment]
您好，邮件已经收到，我会尽快给您回复。

**Comment by brunodema** [comment]
Hi

I've seen people commenting that the solution is to lower the time range, that's great...

But what exactly is causing this? I'm facing the same issue at the moment, and I wouldn't like to change the time range that I'm using, I'd rather understand the cause and fix it.
