### ISSUE TITLE
Dashboards | Timestamps: improve handling of ms precision for timestamps

### ISSUE THREAD

**Issue by hsdxpro** [grafana/grafana#48917]
Issue happening with both MySQL 5.6, and latest version of PostgreSQL

Basic TimeSeries chart.
I have 4 records in the table and millisecond resolution datetime properly shows up (both in Grafana table and chart view)
![image](https://user-images.githubusercontent.com/5315603/167954054-26bbc04a-1671-4b0b-a70f-9d5377c259f1.png)

After inserting one more record, the query starts to return seconds resolution, even though I didn't touch the query.
![image](https://user-images.githubusercontent.com/5315603/167953959-d2145e48-b1b2-439c-99e7-4474a1750859.png)

Also note I text DIFF - ed the EXPANDED query and there is no difference just that it queried 5 samples instead of 4.

I expect to get millisecond resolution queried always, regardless of how many records are in the table.

In MySQL timestamp(3) column type used, in PostgreSQL timestamp without timezone (with 3 precision)

How to reproduce?
Create table, insert some {'2022.05.12 23:40:50.398', anyValue} values, and millisecond display eventually changes to seconds by itself without changing the query.

Use the following query:
SELECT
  DateTime AS "time",
  Value
FROM table
ORDER by DateTime

**Environment**:
- Grafana version: v8.5.0 (6134e3cf3)
- Data source type & version: MySQL 5.6, and latest PostgreSQL both reproducable
- OS Grafana is installed on: Win10
- User OS & Browser: Win10 + Google Chrome
- Grafana plugins: Built-in TimeSeries
- Others:

**Comment by zuchka** [comment]
Can you [inspect your raw request and response](https://grafana.com/docs/grafana/latest/panels/inspect-panel/#view-raw-request-and-response-to-data-source) and share that here?

**Comment by zuchka** [comment]
also see this demo dashboard. Perhaps this is worth reporting: improving the handling of ms precision for timestamps. I tried to get the field-type transformation to recognize `hh:mm:ss.SSS` but it didn't quite work.

https://play.grafana.org/d/j6JMITX7z/grafana-grafana-48917?orgId=1

**Comment by zuchka** [comment]
also can you share your exact SQL statement that your are using in MySQL / Postgres to generate these tables? The more precise you are in your reproduction steps, the more confident the squads can be in confirming this issue 👍

**Comment by aptenodytes-forsteri** [comment]
I think I know what causes this. I'm seeing this as well. 

I commented on this PR: https://github.com/grafana/grafana/pull/37569

The above PR added logic to display the timestamp in milliseconds on a tooltip when the range is less than a minute and hide the milliseconds when the range is greater than a minute.

This logic doesn't make a lot of sense in the context of a table. I want to specify the format of the cells in my table exactly; I don't want it to optionally use millisecond precision.

**Comment by leeoniya** [comment]
@hsdxpro see additional discussion in https://github.com/grafana/grafana/pull/37569#pullrequestreview-1099573015

since we use a single displayProcessor for per field in multiple contexts, it would be too much extra UI real estate and options complexity to provide explicit controls for value display separately for tooltip, legend, and viz independently.

long story short, if you don't want this behavior you should provide an explicit `time:` prefixed datetime format in `unit`. e.g.:

https://github.com/grafana/grafana/pull/54923/files#diff-ae274270eb271909a74b7197e95f8e39875da7692e7dab85c63f55464f8f75dcR522
