### ISSUE TITLE
[Query] Goal Graph?

### ISSUE THREAD

**Issue by dod83** [grafana/grafana#4892]
Hi,

I'm using Grafana 2.6.0 and looking to create a goal chart. 
For example: my daily goal is for a sum of a variable is 100 (or any other custom value that I can change at any given time) and I'm looking for a graph to show how close I reached that goal. Is this possible with the current grafana tools?

Thanks,
D.

**Comment by bergquist** [comment]
You can do that using singlestat panel with gauges for example. Its available in 3.0beta7

**Comment by dod83** [comment]
Cool thanks!

**Comment by dod83** [comment]
Having some issues with 3.0beta7 It has no dashboards and when I go to the site it says that some of them are not supported yet. Not seeing the singlestat option.

**Comment by torkelo** [comment]
@dod83 what do you mean "it has no dashboards" ? Grafana does not come with dashboards, you have to make them :) 

"when I go to the site it says that some of them are not supported yet"  what site? where?

**Comment by dod83** [comment]
When I go to Google Chrome Version 49.0.2623.112 m (64-bit) the Grafan UI is messed up and adding a panel doesn't work.

I now switched to IE 11 and all looks good there (surprisingly).

Should I upgrade the Chrome or there are some known issues that you plan to fix?

**Comment by torkelo** [comment]
does http://play.grafana.org look strange in chrome 49? there has been no reports of chrome issues, and it is working fine on chrome 49 here

**Comment by dod83** [comment]
play looks good. 

This is what I see after installing beta7 installing locally:

![capture](https://cloud.githubusercontent.com/assets/18245478/14984325/c2dec708-114a-11e6-8093-9a36ae3c970e.PNG)

**Comment by torkelo** [comment]
did you restart grafana-server after install? strange, not sure what's going on with your install :(

**Comment by dod83** [comment]
No worries I can use IE for now and try reinstalling later.

Now for the interesting stuff :)

1. Why there is no timestamp on the X and no count on Y?
2. Why is the gauge green although I'm at 95% capacity?

Thanks.
![capture](https://cloud.githubusercontent.com/assets/18245478/14984729/e133201c-114c-11e6-90f3-74748342d971.PNG)
