### ISSUE TITLE
Service accounts: Service Account Token detail page and token modal UI issues

### ISSUE THREAD

**Issue by vtorosyan** [grafana/grafana#48925]
feature flag:

```conf
[feature_toggles]
enable = service-accounts accesscontrol
```

component: `public/app/features/serviceaccounts` 
path: `http://127.0.0.1:3000/org/serviceaccounts` detail view (ex: `http://127.0.0.1:3000/org/serviceaccounts/2`)

## Definition of Done 

![image](https://user-images.githubusercontent.com/8071073/158137021-32fd8382-6d61-43fe-9db2-ce4fba75d602.png)

- [ ] Date modal isn't hidden during date pick
- [ ] Optional name should appear with the placeholder of the name of the service account
- [ ] You should be able to generate a token without inputting anything in the modal form

- [ ] Modal doesn't allow picking date older than today+1

![image](https://user-images.githubusercontent.com/8071073/158137458-2652439e-9bb6-4936-a945-151a80f06af2.png)

- [ ] expire the day after should say: Expire in 1 day

![image](https://user-images.githubusercontent.com/8071073/158137822-ace618c6-e102-4845-b7c8-e3fd0384c9c4.png)
^ figma

- [ ] Add token should be inlined with `Tokens` on the left hand side
- [ ] Add token button should be renamed to Add service account token

![image](https://user-images.githubusercontent.com/8071073/158137944-3f2d56e8-32fa-4aae-8124-67d5fe9391dd.png)

- [ ] Enable service account should display notification action was done
- [ ] Enable service account button and Delete service account button should be moved to upper right corner

![image](https://user-images.githubusercontent.com/8071073/158343301-0e8d9b7e-f1bc-4b84-a4e8-54aed0cccbf8.png)
^ figma

- [ ] Improve display of teams to match figma ( No URL necessary)

**Comment by vtorosyan** [comment]
@alexanderzobnin can we close this? It seems that the improvements have been done with the PRs?

**Comment by alexanderzobnin** [comment]
Fixed by https://github.com/grafana/grafana/pull/49508
