### ISSUE TITLE
v7.5.6 license need to fix

### ISSUE THREAD

**Issue by ssungwxx** [grafana/grafana#48927]
**What happened**:
The license applied to a specific version(v7.5.6) is differently.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
- https://grafana.com/grafana/download/7.5.6?edition=oss  v7.5.6 Download page is Apache2.0
- https://github.com/grafana/grafana/blob/v7.5.6/LICENSE v7.5.6 LICENSE file is AGPLv3
- https://github.com/grafana/grafana/blob/v7.5.7/LICENSE v7.5.7 ~ v7.5.11 LICENSE file is Apache 2.0
- https://github.com/grafana/grafana/pull/36742 AGPLv3 update for 8.0.0 release

**Environment**:
- Grafana version: 7.5.6

**Comment by zuchka** [comment]
Thanks for creating this issue, @ssungwxx 

I agree that things are not very clear on that page. I think this means that the `grafana/grafana` repo is __currently__ AGPL3, but the branches associated with those tags are apache2. This, I believe, is why the `7.5.x` branch's license has that AGPL3 header but the license content is Apache2:

cc @daniellee @RichiH 

![CleanShot 2022-05-18 at 09 33 48@2x](https://user-images.githubusercontent.com/37156449/169141597-eb49e00d-a90e-4338-b727-285eb91d77bf.png)

![CleanShot 2022-05-18 at 09 27 13@2x](https://user-images.githubusercontent.com/37156449/169140606-2607ef2a-4e61-4bd3-b1ec-0f9735360861.png)

**Comment by ssungwxx** [comment]
Thx to check license page.
But, I wonder why **only v7.5.6 tag** has AGPL License content but v7.5.6 license is Apache2.0 on download page.

![image](https://user-images.githubusercontent.com/21700738/172041105-bdfd3569-a570-497a-8647-ee215c643dbd.png)
![image](https://user-images.githubusercontent.com/21700738/172041181-55936acc-7233-434d-b0a0-153a6c7614ca.png)

**Comment by WarheadsSE** [comment]
@zuchka If the team could remove this problematic branch, this would "go away" :wink:

**Comment by zuchka** [comment]
@WarheadsSE @ssungwxx branch deleted! thank you!
