### ISSUE TITLE
TimeSeries problem with bar 8.5.2 (narrow bar)

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#48923]
**What happened**:
The bar are narrow
![image](https://user-images.githubusercontent.com/73607094/168000882-a1c09d3a-6ed5-4259-9fd0-4b62835fbe1c.png)
**What you expected to happen**:
correct this issue

**Anything else we need to know?**:
In the version 8.4.4 everything was okay
**Environment**:
- Grafana version: 8.5.2
- Data source type & version: MSSQL
- OS Grafana is installed on: Ubuntu 20.04.4 LTS
- User OS & Browser: Chrome
- Grafana plugins: TimeSeries
- Others: N/A

**Comment by deejayluk** [comment]
version 8.5.2 (latest), on the previous 8.4.4. worked very well
![image](https://user-images.githubusercontent.com/73607094/168524634-330d6ac7-126d-4512-9ec7-851bac1362c5.png)
![image](https://user-images.githubusercontent.com/73607094/168524664-d73a5b37-67be-48a2-8310-f8fc9a480189.png)

**Comment by torkelo** [comment]
@leeoniya any ideas? could it be caused by https://github.com/grafana/grafana/pull/48030 ?

**Comment by torkelo** [comment]
@deejayluk can you include raw data ? (panel inspect -> data export)

**Comment by deejayluk** [comment]
[data-2022-05-16 10_52_30.csv](https://github.com/grafana/grafana/files/8698601/data-2022-05-16.10_52_30.csv)

**Comment by deejayluk** [comment]
Could you help me? I need a solution.
