### ISSUE TITLE
Service accounts: UI improvements on Service accounts listing page

### ISSUE THREAD

**Issue by vtorosyan** [grafana/grafana#48926]
feature flag:

```
// custom.ini
[feature_toggles]
enable = service-accounts accesscontrol
```

component: public/app/features/serviceaccounts
path: http://127.0.0.1:3000/org/serviceaccounts
---
# Definition of done

![image](https://user-images.githubusercontent.com/7727602/160123645-32a415fa-4fc1-40d3-9e6a-d7ed2d845324.png)

- [ ] prettify rows, needs alignment and some adjustments to icon plaacement to numbers
- [x] move new service account button to upperright
- [ ] info description indicator to explain the concept of service accounts

---
component: public/app/features/apikeys

path: http://127.0.0.1:3000/org/apikeys

# Definition of done

![image](https://user-images.githubusercontent.com/7727602/160126206-2d7eafe8-f980-475a-9332-0ec07a6c81c5.png)

- [ ] banner to display information about the "new" concept around service account if the feature toggle has been enabled

**Comment by alexanderzobnin** [comment]
Closed by https://github.com/grafana/grafana/pull/49508
