### ISSUE TITLE
Flux Query Stat no data when refreshing dashboard

### ISSUE THREAD

**Issue by shassan-el** [grafana/grafana#48931]
**What happened**:
![grafana_bug](https://user-images.githubusercontent.com/103039492/168055457-f46dc3fe-9ffe-48d5-84f2-0388fc0171d4.gif)

**What you expected to happen**:
When refreshing the dashboard, the total sum of _values should appear but instead it states 'No Data'. Currently, the correct value appears when toggling between calculation field options.

**How to reproduce it (as minimally and precisely as possible)**:
Flux query:

import "timezone"

option location = timezone.location(name: "Europe/London")

from(bucket: "Mybucket")
  |> range(start: today())
  |> filter(fn: (r) => r["_measurement"] == "gas")
  |> filter(fn: (r) => r["_field"] == "pulse" or r["_field"] == "consumption_per_pulse")
  |> pivot(rowKey: ["_time"], columnKey: ["_field"], valueColumn: "_value")
  |> difference(nonNegative:true, initialZero:true, columns: ["pulse"])
  |> rename(columns: {"pulse":"pulse_diff"})
  |> map(fn: (r) => ({r with _value: r.consumption_per_pulse * r.pulse_diff * ${m3_to_kWh}}))

**Anything else we need to know?**:

**Environment**: Grafana Cloud
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by shassan-el** [comment]
@zuchka I don't have permission to create a dashboard or add data source there. Therefore I am not sure how to replicate the same flux query.
