### ISSUE TITLE
Grafana Unified Alerting Contact Point API not working

### ISSUE THREAD

**Issue by huuzing** [grafana/grafana#48935]
**What happened**:
I have installed grafana 8.5.6 locally in a kubernetes cluster for testing the contact points API endpoint.

When executing a simple curl to get all contact points out of grafana it results in `{"message":"Not Found"}`. I have tested both the given URL from the Swagger documentation en the path founded in the github code

Swagger (https://editor.swagger.io/?url=https://raw.githubusercontent.com/grafana/grafana/main/pkg/services/ngalert/api/tooling/post.json):
```
curl -sS -u "<user>:<pass>" http://127.0.0.1:8080/api/v1/api/provisioning/contact-points
{"message":"Not found"}
```

Github (https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/generated_base_api_provisioning.go#L113):
```
curl -sS -u "<user>:<pass>" http://127.0.0.1:8080/api/provisioning/contact-points
{"message":"Not found"}
```

**What you expected to happen**:
I expected to get a status of HTTP 200 back with the JSON of the existing contact points I have in grafana.

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Anything else we need to know?**:
I have also tested it with version 8.5.0, since this was the release it was implemented for the first time.
It is also giving a Not Found with the Post request.

**Environment**: 
- Grafana version: 8.5.2
- Data source type & version: Default Datasource
- OS Grafana is installed on: Debian (Docker hub image: bitnami/grafana:8.5.2-debian-10-r0
- User OS & Browser: Mac OS 12.3.3, Browser: Chrome latest version
- Grafana plugins: Default plugins

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm afraid the Provisioning API is a Grafana 9.1 feature. You can find the blog post for it [here](https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/).

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm afraid the Provisioning API is a Grafana 9.1 feature. You can find the blog post for it [here](https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/).

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm afraid the Provisioning API is a Grafana 9.1 feature. You can find the blog post for it [here](https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/).

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm afraid the Provisioning API is a Grafana 9.1 feature. You can find the blog post for it [here](https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/).

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm afraid the Provisioning API is a Grafana 9.1 feature. You can find the blog post for it [here](https://grafana.com/blog/2022/08/25/new-in-grafana-alerting-file-provisioning/).
