### ISSUE TITLE
Alerting: After migration contact points and notifications lost AND alerts sending to `example@email.com`

### ISSUE THREAD

**Issue by sveinf** [grafana/grafana#48934]
**What happened**:
The entire configuration of Contact Points and Notification Policies was reset/deleted. This has happened three times over the last few months. 

**What you expected to happen**:
I expected this not to be deleted unless I choose to do so. And until fixed, I am prevented from
putting in the desired set of notification policies, since they may disappear any time. 

**How to reproduce it (as minimally and precisely as possible)**:
I have not yet found a way to reproduce, there seem to be no pattern about it. I am still working
through logs.

**Anything else we need to know?**:
See below extract from custom.ini
I have tried to follow [this ](https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/) description, but so far, I see no misconfiguration.

**Environment**:
- Grafana version: 8.4.4 OSS, .zip out of the box / sqlite
- Data source type & version: Prometheus 
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Windows 10
- Grafana plugins: N/A
- Others:

Extracts from custom.ini (please let me know if you need anything else that may apply/be relevant):

#################################### Unified Alerting ####################
[unified_alerting]
enabled = true
disabled_orgs =
admin_config_poll_interval = 60s
alertmanager_config_poll_interval = 60s
ha_listen_address = "0.0.0.0:9094"
ha_advertise_address = ""
ha_peers = ""
ha_peer_timeout = 15s
ha_gossip_interval = 200ms
ha_push_pull_interval = 60s
execute_alerts = true
evaluation_timeout = 30s
max_attempts = 3
min_interval = 10s
#################################### Alerting ############################
[alerting]
enabled = false
execute_alerts = true
error_or_timeout = alerting
nodata_or_nullvalues = no_data
concurrent_render_limit = 5
evaluation_timeout_seconds = 30
notification_timeout_seconds = 30
max_attempts = 3
min_interval_seconds = 1
max_annotation_age =
max_annotations_to_keep =

#################################### Annotations #########################

Grateful if anyone can point me in a direction, and apologies up front if this has already been addressed somewhere.

**Comment by zuchka** [comment]
are you still trying on 8.4.4 or have you tried yet on 8.5.2? Has it only ever happened on 8.4.4?

**Comment by sveinf** [comment]
I have only seen this on
8.4.4, but will upgrade to the latest version
and report back.

**Comment by bugbountyguy** [comment]
Just FYI this happened to me on my latest docker update last night to v9.0.0-beta2 - I was getting email delivery failure messages constantly and found it was reset to `<example@email.com>` in the settings. Fortunately no malicious actors are using that domain or email address.

**Comment by sveinf** [comment]
> Just FYI this happened to me on my latest docker update last night to v9.0.0-beta2 - I was getting email delivery failure messages constantly and found it was reset to `<example@email.com>` in the settings. Fortunately no malicious actors are using that domain or email address.

The issue has been seen in in 8.5.2 too. However I will try what you suggest in my end as well and report back.

**Comment by Cronian** [comment]
It happened 8.5.0 too.
I was setting slack, but it was reset. (default)

**Comment by sveinf** [comment]
I have a proposal to a temporary workaround for this issue.

After defining the required set of Contact Points and Notification policies, I ran the following sqlite query to understand the size of my desired configuration:
sqlite3 grafana.db "select id, length(alertmanager_configuration), datetime(created_at, 'unixepoch', 'localtime') from alert_configuration;" ".exit"
That gave me this:
(...)
139|1812|2022-06-04 09:07:35

Later, when the CP/NP appeared to be lost, I ran the same query - which gave me this:
(...)
139|1812|2022-06-04 09:07:35
140|350|2022-06-09 13:15:27
141|350|2022-06-09 13:15:30

As we can see, record 140 and 141 for some unknown reason went significantly less.
So, I decided to simply delete all records like this: 
sqlite3 grafana.db "delete from alert_configuration where length(alertmanager_configuration) < 1000;" ".exit" 

Testing Grafana after this, shows all Notification Policies and Contact Points to be available again.

I will now run this delete script on a schedule, until a permanent fix is found.

**Comment by zuchka** [comment]
Can you confirm: are you using the new Grafana Alerting platform (first released in Grafana 8) or the legacy alerting platform? I should note that the legacy platform is no longer actively developed:

https://grafana.com/docs/grafana/next/alerting/migrating-alerts/

**Comment by sveinf** [comment]
I have the following configuration in my custom.ini:
(...)
[unified_alerting]
enabled = true
(...)
[alerting]
enabled = false
(...)

note: this is for Grafana 8.5.2

**Comment by zuchka** [comment]
alerting has undergone a lot of development since 8.5.2, especially with the launch of v9. Have you tried upgrading to 9+?

**Comment by RenWal** [comment]
We've moved from 8.4.3 to 9.1.5 from the `https://packages.grafana.com/oss/deb stable/main amd64` Debian package repo and came across this. After that upgrade, all of our alerts were sent to that default email address.

Fun fact: That address does exist!

```
[example@email.com](mailto:example@email.com)
    host mx00.mail.com [74.208.5.20]
    SMTP error from remote mail server after RCPT TO:[<example@email.com>](mailto:example@email.com):
    552-Requested mail action aborted: exceeded storage allocation
    552-Quota exceeded.
```
Looks like all the Grafana instances out there have managed to fill up that inbox.

This is a great way to announce your Grafana instance and whatever it is monitoring to a third party. :neutral_face:

**Comment by armandgrillet** [comment]
You are using SQLite with legacy alerting provisioning for notification channels, notification channels do not exist anymore and have been replaced by contact points. Provisioned notification channels have not been migrated to contact points as your SQLite database might have been reset, during migration to Grafana Alerting we migrate only what is in the database but not files used for provisioning. You should use https://grafana.com/docs/grafana/latest/administration/provisioning/#alerting or a stateful database to fix this.

**Comment by Roberto6969** [comment]
I'm running Grafana v9.4.0 in a container. I still have no idea how to change or remove this mail email@example.com. Would you be so kind and explain me?

Thank You

**Comment by frodgim** [comment]
Why is this ticket closed if you don't have a solution for it?

**Comment by godber** [comment]
The domain `example.com` is reserved for purposes like this, I would suggest that the email be changed to `email@example.com`

See this RFC for confirmation

https://datatracker.ietf.org/doc/html/rfc2606
