### ISSUE TITLE
Alerting: Improve templating

### ISSUE THREAD

**Issue by santihernandezc** [grafana/grafana#48943]
I divided issues in four different categories:
- Improvements: issues opened by us to do before 9.0.
- Bugs: opened by the community. Some need investigation/info before knowing if we even need to make a fix.
- Feature requests: also opened by the community, we need to evaluate which of those we want to address before 9.0.
- Docs: improvements for the UA docs.

**Improvements:**
- https://github.com/grafana/grafana/issues/46094
- https://github.com/grafana/grafana/issues/48493

**Bugs:**
- https://github.com/grafana/grafana/issues/47813
- https://github.com/grafana/grafana/issues/48567
- https://github.com/grafana/grafana/issues/44038
- https://github.com/grafana/grafana/issues/45543
- https://github.com/grafana/grafana/issues/45459

**Feature requests:**
- https://github.com/grafana/grafana/issues/32479
- https://github.com/grafana/grafana/issues/49716
- https://github.com/grafana/support-escalations/issues/2598
- Legacy:
    - https://github.com/grafana/grafana/issues/12176

**Docs:**
- https://github.com/grafana/grafana/issues/47583
- https://github.com/grafana/grafana/issues/51502

**Comment by santihernandezc** [comment]
@wudongwang hi, I couldn't understand your message, sorry.
A few things:
- I think opening an issue could be a better option for your message. You can open an issue with the appropriate labels and we'll try to do our best to help you.
- If this is not an issue but rather a question, you can take a look at our [alerting docs](https://grafana.com/docs/grafana/latest/alerting/) or leave a question in our [community forum](https://community.grafana.com/about).
- If you're using an automatic translator, I'd recommend using [DeepL](https://www.deepl.com/translator). This is what I personally use and find to be the most accurate one out there.

I hope you get your issue sorted out, cheers!

**Comment by wudongwang** [comment]
Hi, there is a requirement to help look at.


Architecture: telegraf+influxdb+grafana
grafana docked to nail alerting.
Is it possible to implement 10 servers using one alert template for alerting?





------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Send time:&nbsp;Monday, Oct 24, 2022 10:33 PM
***@***.***&gt;; 
***@***.***&gt;; ***@***.***&gt;; 
Subject: &nbsp;Re: [grafana/grafana] Alerting: Improve templating (Issue #48943)





 
@wudongwang hi, I couldn't understand your message, sorry.
 A few things:
  
I think opening an issue could be a better option for your message. You can open an issue with the appropriate labels and we'll try to do our best to help you.
 
If this is not an issue but rather a question, you can take a look at our alerting docs or leave a question in our community forum.
 
If you're using an automatic translator, I'd recommend using DeepL. This is what I personally use and find to be the most accurate one out there.
  
I hope you get your issue sorted out, cheers!
