### ISSUE TITLE
Alerting: externalLabels are missing for grouping or filtering in Alert list panel

### ISSUE THREAD

**Issue by AbelThorne** [grafana/grafana#48948]
**What happened**:
When wanting to group alerts according to an external label, the external labels are missing from the available ones. Same behaviours happens when using an external label to filter alerts, the list comes up empty.

**What you expected to happen**:
As with the Unified Alerting view, I'm expecting external labels to be available for filtering alerts in the alert list panel

**How to reproduce it (as minimally and precisely as possible)**:
Have a set up where external labels are applied to alerts and metrics (using Thanos as a datasource for instance). Create an Alert List panel. Confirm that external labels are missing from grouping options and are not recognized when filtering.

**Anything else we need to know?**:
This is very very annoying for creating multi-cluster dashboards for instance where the cluster name is typically an external label

**Environment**:
- Grafana version: 8.5.0
- Data source type & version: Prometheus Operator 0.56.2 & Thanos 0.24 
- OS Grafana is installed on: Helm Chart on Kubernetes 
- User OS & Browser: MacOS
- Grafana plugins:
- Others:

```[tasklist]
- [ ] https://github.com/grafana/grafana/issues/63570
```

**Comment by zuchka** [comment]
Thanks for creating this issue, @AbelThorne 

to clarify: are you referring to this option in the AlertList panel editor?

![CleanShot 2022-05-18 at 19 01 11@2x](https://user-images.githubusercontent.com/37156449/169211888-2464b45a-392b-4607-82cf-53382d59def3.png)

**Comment by AbelThorne** [comment]
Indeed that is the one. Thanks for picking that up :-)

**Comment by Migueljfs** [comment]
Is this being worked on?

In alerting I have:
<img width="718" alt="image" src="https://user-images.githubusercontent.com/25540481/199949291-e2fcf48e-582e-4379-b606-0913b2052460.png">

In the panel:
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/25540481/199949446-d4d5b385-1766-458d-8be2-cb009ea9bd3a.png">

**Comment by Migueljfs** [comment]
@zuchka Any news on this? This is blocking us from presenting alerts in dashboards 😞

**Comment by konrad147** [comment]
I created an [issue](https://github.com/grafana/grafana/issues/63570) tracking missing values of the `Group by` dropdown
Regarding rules labels, we need to gather more information about users' expectations and decide how to proceed

**Comment by Migueljfs** [comment]
Hey @konrad147 thanks for picking this up and working on it, really appreciated!

Seems like it's already available as of v9.4.1, unless I misinterpreted the issues/pull request.
 
I'm running Grafana version 9.4.3 but still do not see any options on the `Group By` dropdown

**Comment by konrad147** [comment]
The patch will be released in Grafana v9.4.4 in late March. v9.4.1 - v9.4.3 were minor releases with only specific fixes applied.
The problem you describe was caused by having data sources that don't return HTTP 200 statutes. 
Perhaps you could check if all of your data sources are correctly configured.

**Comment by Migueljfs** [comment]
Hey @konrad147 we do actually, they are legacy datasources that are just there for historic purposes only since we migrated from one datasource to another.

After deleting that datasource I can confirm I can see the external labels in the grouping, thanks for helping!

**Comment by Migueljfs** [comment]
Actually, the "cluster" label is not present. Other external labels are also not present.
<img width="411" alt="image" src="https://user-images.githubusercontent.com/25540481/223131585-9fe22a3d-f4a8-4725-9367-759272bbf217.png">

**Comment by Migueljfs** [comment]
Hey @konrad147 thanks for taking a look at it again.

Taking account into what I said I managed to _somewhat_ have a workaround, by configuring a Prometheus datasource pointing to my Thanos-Ruler instance. By doing this I now have `external_labels` available to me and can filter by cluster.

The one problem is Grafana Alerting only allows Alertmanager datasources, it would be nice if it could support Prometheus Datasource or even create a new datasource for ThanosRuler type

**Comment by Migueljfs** [comment]
Yes I meant this page here:
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/25540481/224303314-46ddc37f-2a3a-41e9-b099-7444e9a165bc.png">
