### ISSUE TITLE
Docs feedback: /dashboards/dashboard-create.md

### ISSUE THREAD

**Issue by eJayYoung** [grafana/grafana#48955]
![image](https://user-images.githubusercontent.com/18661091/168235527-3b3bae60-7863-4779-b7e4-fe29a99d017e.png)

video is disappeared

**Comment by zuchka** [comment]
cc: @achatterjee-grafana

**Comment by achatterjee-grafana** [comment]
@chri2547 and @gguillotte-grafana, for you to look at during refactor.

**Comment by Eve832** [comment]
fixed with UI update of docs in 9.4
