### ISSUE TITLE
[Bug] Logging in using LDAP for the first creates an organisation with the email of the user

### ISSUE THREAD

**Issue by ConorNevin** [grafana/grafana#4895]
Hi,

I'm experimenting with LDAP integration and I think that I've found a bug when a user attempts to login for the first time.

It looks like Grafana creates an organisation for the user which it then tries to delete and fails with the error message "Error while trying to authenticate user: Cannot remove last organization admin"

I'm running 3.0.0-beta7 on Centos 7.

**Comment by torkelo** [comment]
what's your grafana.ini and ldap config? 

Especially your grafana.ini auto_assign_org setting, and ldap group mappings?  

Do you have org with id = 1 ? (or have you removed it?), if not specified that is what the ldap group mappings use.

**Comment by ConorNevin** [comment]
I have auto_assign_org set to false in my grafana.ini.

I have removed the org with id = 1. I have created two orgs and set my ldap group mappings to give all users the Viewer role on both.

My config files are below:
grafana.ini: http://hastebin.com/uqamujajej.coffee
ldap.toml: http://hastebin.com/iqayilicub.lua

**Comment by torkelo** [comment]
if auto_assign_org is set to false then each use will be getting it's own org when it is created, and the ldap group mapping will try to remove it. 

set auto_assign_org to true,   if you removed org with id 1, have you specified an org id in ldap group mappings?
