### ISSUE TITLE
NodeGraph not clearing variable value

### ISSUE THREAD

**Issue by nickper** [grafana/grafana#48956]
**What happened**:
After much of trail and error I managed to create NodeGraph panels containing traceroute pathing.
When I change my ip variable it doesn't delete the arrows. It clears only when I F5 the page.
Those leftover lines do not appear in the dataset (checked via query inspector), and do not react when hovering over them.

![image](https://user-images.githubusercontent.com/8981951/168103705-68d8b488-0b7a-4dfd-a6d6-ec5f5ea70937.png)
![image](https://user-images.githubusercontent.com/8981951/168103771-3e6b077f-a0bd-4355-81bb-23a9f815eebc.png)

**What you expected to happen**:
I expect the arrows to not be there. The official release noted are not mentioning any issues or improvements to NodeGraph.

**How to reproduce it (as minimally and precisely as possible)**:
My setup uses the custom plugin [nodegraph-api-plugin](https://github.com/hoptical/nodegraph-api-plugin) which format the data and based on 2 urls to my own api. The api handles the querying to an influxdb database which contain the nodes-edge information.
Have a list of IP's which are accessible via a dasboard variable, and give it the custom plugin.
![image](https://user-images.githubusercontent.com/8981951/168253649-1bf0f382-63b4-411e-b800-6b78786522aa.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.4.2
- Data source type & version: Custom api calling to Influxdb 1.8
- OS Grafana is installed on: Docker - Alphine v3.15 (official grafana docker image)
- User OS & Browser: Windows 10, Edge & Firefox
- Grafana plugins: Custom plugin [nodegraph-api-plugin]
- Others:

**Comment by zuchka** [comment]
Thanks for creating this issue, @nickper 

> My setup uses the custom plugin [nodegraph-api-plugin](https://github.com/hoptical/nodegraph-api-plugin)

Please file issues specific to community-built plugins in that plugin's github repo.

Or you might want to start a discussion in the plugin development category in our forum:

https://community.grafana.com/c/plugin-development/30

**Comment by zuchka** [comment]
or the grafana - developers and api category

https://community.grafana.com/c/support/developers-api/44

**Comment by nickper** [comment]
I don't think it is from the plugin, because the data received in does not those 'edge' lines.
