### ISSUE TITLE
[Question] Plugin Documentation

### ISSUE THREAD

**Issue by moserke** [grafana/grafana#4896]
Been working on trying to write a datasource plugin and have been struggling a lot because I just can't figure out what Angular objects are there, the methods on the classes, etc.  Is there a place that I haven't found that has deep documentation on the plugin system?  Or is there a better place to start looking to get an idea of what things are possible in which part of the system.  I feel like I've just been cargo culting from other plugins and it's quite the hog pog.

**Comment by peggyl** [comment]
http://docs.grafana.org/plugins/development/ was a decent starting point (more links from the Plugins dropdown on the navigation bar). 

Looking at the examples on that page and at the official supported plugins (https://github.com/grafana/grafana/tree/master/public/app/plugins/datasource) was also helpful.

Agree that more documentation on https://github.com/grafana/grafana/tree/master/pkg/plugins (at least exported fields, to satisfy `golint`) would be great though.

**Comment by torkelo** [comment]
exported fields? golint? not sure what they have to do with plugins. you mean the plugin.json ?
