### ISSUE TITLE
AzureAD groups automatic mapped to grafana teams

### ISSUE THREAD

**Issue by mkarci** [grafana/grafana#48964]
### Discussed in https://github.com/grafana/grafana/discussions/48962

<div type='discussions-op-text'>

<sup>Originally posted by **mkarci** May 13, 2022</sup>
Hi all, 

The team sync unfortunately works only when you have manually created a team. Within the team setting you are able to add external groups sync, so each user of this group will be sync automatically to this team.

Eventually what you want is that also the the groups defined within AzureAD mapped automatically to the teams within in Grafana.</div>

**Comment by zuchka** [comment]
https://github.com/grafana/grafana/discussions/48962
