### ISSUE TITLE
Data source of the query doesn't update when changing corresponding Data source variable

### ISSUE THREAD

**Issue by alex-svat** [grafana/grafana#48979]
**What happened**:
Changing Data Source variable doesn't update Data Source of the query. It does, however, update another variable which is based on the Data Source variable. 

I have set up Data Source variable called env to dynamically switch databases:
![image](https://user-images.githubusercontent.com/48870382/168389537-919f8fcf-6dc4-4301-82e4-ed0a45085618.png)

In the Data Source for the query I selected `${env}` and it correctly sets the environment that is initially selected (Production). However, when changing the variable to another data source (Staging), the query seems to be targeting the old (Production) data source. To prove that it still incorrectly points to Production, after switching to the Staging data source I used the device value D1839-00662 (which I made sure only exists on Production!) and indeed data appeared, proving my hypothesis.

![Screen-Recording-2022-05-13-at-1](https://user-images.githubusercontent.com/48870382/168390116-660a4a2b-6d80-4159-9373-f17b8a2e9d45.gif)

**What you expected to happen**:
When changing Data Source variable, if a query depends on that variable to determine its data source, it must start targeting new data source automatically.

**How to reproduce it (as minimally and precisely as possible)**:
1. Set up variable using Data Source option and have at least 2 options available.
2. In the query settings select that variable as the data source.
3. When changing values of the variable, data source of the query stays the same.

**Anything else we need to know?**:
Interestingly, I used `${env}` variable in the query of another variable and it does respond to changing the value of `${env}`, so it only affects the queries.

**Environment**:
- Grafana version: v8.5.2
- Data source type & version: PostgreSQL
- OS Grafana is installed on: Mac, Windows
- User OS & Browser: Firefox, Chrome, Safari
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
Thanks for creating this issue, @alex-svat 

is this error only reproducible when using the Postgres-specific options in the Variables > Edit > Data source options config?

**Comment by alex-svat** [comment]
> Thanks for creating this issue, @alex-svat
> 
> is this error only reproducible when using the Postgres-specific options in the Variables > Edit > Data source options config?

Just tested with Google Cloud Monitoring data source and the bug is still happening, which leads me to believe it's more of a generic issue of query's data source not dynamically updating when using `${env}`:
![image](https://user-images.githubusercontent.com/48870382/169386485-0340215b-f0e3-4cf9-89fd-1b5a5fff364e.png)

**Comment by Hsinin** [comment]
Can confirm this is happening when using a Mysql data source.

Version: 8.5.2

**Comment by rvdwijngaard** [comment]
Can confirm this is happening when using a CloudWatch data source 

Version: 8.5.3
