### ISSUE TITLE
Bar charts don't show display name when single value is returned from prometheus query

### ISSUE THREAD

**Issue by uselessjargon** [grafana/grafana#48983]
**What happened**:
In a bar chart with a prom query like `sum(aobiz_cust_node_gauge2{custtag=~"cnp"}) by (ostype)` the bar chart displays all 'ostype's in the proper format (ostype name, bar and value) when there is more than one 'ostype' to display. However, when there is only a single 'ostype' returned, the display name for the 'ostype' does not appear. For example, if all nodes for the dashboard are of ostype 'linux-rh7.9' that ostype name is not displayed in the chart. 

**What you expected to happen**:
The ostype name should display in the bar chart. I believe it's the legend value that is not being displayed.

**How to reproduce it (as minimally and precisely as possible)**:
This is what the bar chart looks like when multiple 'ostypes' are returned from the query:
<img width="259" alt="image" src="https://user-images.githubusercontent.com/15000796/168443787-b9bad129-6d70-4300-8ff4-24b7a03433af.png">

This is what bar chart looks like when only one 'ostype' is returned from the query. Notice the name 'linux-rh7.9' is not displayed and the bar itself is not filled in):
<img width="259" alt="image" src="https://user-images.githubusercontent.com/15000796/168443816-d403a14c-9ed3-48c1-80de-acae42c0937f.png">

Return query:
<img width="496" alt="image" src="https://user-images.githubusercontent.com/15000796/168443913-5f4e3bc9-3582-4862-acf2-8eeeb47a8f2e.png">

**Anything else we need to know?**:

**Environment**:
- Grafana version: Version 8.5.2 (commit: 90701be19c, branch: HEAD)
- Data source type & version: prometheus, version 2.35.0 
- OS Grafana is installed on: CentOS Linux release 7.9.2009 (Core)
- User OS & Browser: macOS Monterey 12.3.1 with FF or Chrome
- Grafana plugins: None

**Comment by uselessjargon** [comment]
Here's a screenshot of the bar chart query
<img width="888" alt="image" src="https://user-images.githubusercontent.com/15000796/168444532-a75c77da-8bf9-4ed6-ba71-ae6789277e7e.png">

**Comment by torkelo** [comment]
This is by design, so that you can use the panel title for name if you only have one gauge. 

You can change it in the stat syles / text mode option 
![Screenshot from 2022-05-03 14-09-22](https://user-images.githubusercontent.com/10999/168561093-0bd34205-ad63-40de-99e3-e0e78229fa9d.png)

**Comment by uselessjargon** [comment]
Hi @torkelo, thanks for the response. What version of Grafana are you running? There is no Stats/Text mode in the 'Bar Gauge.' 

My apologies, as I stated "Bar Chart" in my title and issue previously, not 'Bar gauge' . I'll try to switch my graphs 'bar chart' to see if I can use it instead in the meantime. 

![image](https://user-images.githubusercontent.com/15000796/168631798-88a1a780-b052-4b49-802a-c8e7e9a7a69f.png)

**Comment by uselessjargon** [comment]
The 'beta' Bar chart is not solving my issue. Can we re-open this one or should I open a new issue with the correct panel "Bar guage" vs "Bar chart". 

Incidentally, using the panel title for the name with one gauge is not an option since these panel are generated dynamically based on the promQL query. Also, I still am not seeing that Stat Styles/Text Mode option in the Bar chart panel. Maybe I'm dense but it could be you are on previous version of Grafana where that exists.

**Comment by torkelo** [comment]
Sorry i meant bar gauge, your screenshot is from bar gauge and it has an option to always show name and value

**Comment by uselessjargon** [comment]
@torkelo thanks again for the response. It looks like you are actually looking at the **Stat** visualization (below screenshot), not the **Bar gauge**. There is no Stat Styles/Text Mode option in Bar gauge. I even went back to grafana 7.5 to check. 

 I guess I can open a feature request to have this same/similar option added to Bar gauge.

<img width="365" alt="image" src="https://user-images.githubusercontent.com/15000796/168663214-e1b43509-137a-4c25-9490-97fb4341a6a1.png">

**Comment by torkelo** [comment]
Hi, sorry, forgot that Bar gauge does not have this option.  

You can work around this problem by specifying `${__field.displayName}` in the Display name field under **Standard options**

**Comment by uselessjargon** [comment]
You da man! Thanks for the work around! Works as I need now.

**Comment by petergsn** [comment]
> ${__field.displayName}

Hi Torkelo,

Where I need to add that,
![image](https://user-images.githubusercontent.com/107683247/193016923-455b2258-c2e2-46a7-8cf0-22da6037fe4c.png)

Regards,
Peter G

**Comment by petergsn** [comment]
![image](https://user-images.githubusercontent.com/107683247/193027522-19f4017e-4479-4141-b417-e343c7ddf5d4.png)
 I am also facing same issue, Value is there but it is not displaying in bar gauge.
![image](https://user-images.githubusercontent.com/107683247/193027918-a393a280-93df-442d-b959-642f7b7ca032.png)
I am using KQL in Grafana.

**Comment by uselessjargon** [comment]
@petergsn This is where I added it...
<img width="380" alt="image" src="https://user-images.githubusercontent.com/15000796/193088754-a56a9788-fc18-48aa-87d9-96f14153f6b9.png">

**Comment by petergsn** [comment]
Hi, I am getting below, 
![image](https://user-images.githubusercontent.com/107683247/193101922-c5122a60-044b-4da8-a0d1-2e0ee9318b92.png)

But I am looking for below one,
![image](https://user-images.githubusercontent.com/107683247/193102065-538b9c40-a788-4000-8505-5c0c3aac6255.png)
 please advice if you have any idea, I am using KQL query,

alertsmanagementresources
|where ['type'] =~ 'microsoft.alertsmanagement/alerts'
and properties.essentials.targetResourceGroup in~ ('name') 
and properties.essentials.monitorCondition in~ ('Fired','Resolved')
and properties.essentials.severity in~ ('Sev0')
and todatetime(properties.essentials.startDateTime) >= $__timeFrom 
and todatetime(properties.essentials.startDateTime) <= $__timeTo
|project name, properties.essentials.severity
|summarize  count() by name

But it works perfectly if multiple values are there.
![image](https://user-images.githubusercontent.com/107683247/193102545-74f138f1-9ab2-4cae-9e8a-76705a51c102.png)

**Comment by anton-bystrov** [comment]
Hello @petergsn! I catch the same issue, and for me working `${__field.labels}` Also I found more details here https://grafana.com/docs/grafana/latest/panels-visualizations/configure-standard-options/

**Comment by AndreBooysen** [comment]
Hi, just run into the same issue on the Bar Gauge where I have a score card repeating for each area. the ${__field.labels} work around works

**Comment by LucasTelho** [comment]
> [@petergsn](https://github.com/petergsn) This is where I added it... <img alt="image" width="380" src="https://user-images.githubusercontent.com/15000796/193088754-a56a9788-fc18-48aa-87d9-96f14153f6b9.png">

Just a quick update,  the solution provided from @petergsn worked for me too, but dependeing on your Grafana Version it can be instead of displayName, change it to display.name and it'll work.

`${__field.display.name}`

My grafana version is 10.2.3.

**Comment by buirkan** [comment]
Sharing my experience with the Gauge chart in `Grafana v12.0.0`: I needed to use `${__field.display.name}` to display the value correctly when the query returns a single value. Thanks!

**Comment by JoshuaEmslie** [comment]
@LucasTelho You are a good man
