### ISSUE TITLE
Prometheus annotations don't show its tags

### ISSUE THREAD

**Issue by jinnuae40** [grafana/grafana#48984]
**What happened**:
When I create Annotations for Prometheus datasource, Tags(Located in Field formats in "Annotations > Edit") doesn't appear.

**What you expected to happen**:
It looks should be shown in the annotation's tag

**How to reproduce it (as minimally and precisely as possible)**:
Configure like below
![image](https://user-images.githubusercontent.com/26201488/168463337-4c962a8e-5c63-4467-a344-fbfe98603296.png)

Doesn't show the tag
![image](https://user-images.githubusercontent.com/26201488/168463369-0edd91aa-6ac6-46a0-ab6d-6935b8cf8713.png)

**Anything else we need to know?**:
Please kindly guide how to use tags for the Prometheus annotations

**Environment**:
- Grafana version: Version 8.5.2 (commit: 90701be19c, branch: HEAD)
- Data source type & version: Prometheus: prometheus, version 2.35.0
- OS Grafana is installed on: Alpine Linux 3.15.4
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by torkelo** [comment]
Your query must not be returning a label with name "alert". The tags field in the annotation query settings is for specifying label names that should be turned into tags and shown in the event
