### ISSUE TITLE
[QUESTION/BUG] Giving an already-existing Grafana anonymous access does not seem to invoke necessary db updates

### ISSUE THREAD

**Issue by TannerMoore** [grafana/grafana#4899]
**What grafana version are you using?**

2.1.2

**What OS are you running grafana on?**

Windows

### Issue notes

**Anonymous access was recently activated from the config using the following settings:**
```
#################################### Anonymous Auth ##########################
[auth.anonymous]
# enable anonymous access
enabled = true

# specify organization name that should be used for unauthenticated users
org_name = admin@localhost

# specify role for unauthenticated users
org_role = Admin
```
**Now that new code paths are being accessed, I am getting errors when I try to access Grafana through the rest API**

**When using the golang http.get command, the Response object returned is as follows (I added new lines in an attempt to make it easier to read):**
```
Response: &{
401 Unauthorized 401 HTTP/1.1 1 1
map[Content-Type:[application/json; charset=UTF-8] Set-Cookie:[grafana_sess=f3dea0816a51dd1a; Path=/; HttpOnly]
Date:[Mon, 02 May 2016 20:49:09 GMT] Content-Length:[32]] 
0xc0824161c0 32 [] false map[] 0xc082350ee0 <nil>}
```

**The grafana log says the organization doesn't exist:**
```
2016/05/03 13:52:26 [I] Completed /api/datasources 401 Unauthorized in 1ms
2016/05/03 13:52:26 [middleware.go:62 initContextWithAnonymousUser()] [E] Anonymous access organization error: 'admin@localhost': Organization not found
```

I looked at the source code and found that "admin@localhost" is coming from the variable "setting.AnonymousOrgName" Maybe that can help the diagnosis.

**When dumping out grafana.db, I can see that the user I want is there, but maybe it isn't being entered into the org table? Here are the relevant logs I have found so far:**
```
INSERT INTO "user" VALUES(1,0,'admin','admin@localhost','','5c531d4464de802053eb5e39b8a5ba6b07236a1512628039d91c10c14d495fa8469219514c36f93f680863821ba5bb9adfe1','vrjxCaqLQt','lnQPWiELRF','',1,1,0,'','2015-08-19 21:32:15','2015-09-23 18:48:16');
CREATE TABLE `star` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `user_id` INTEGER NOT NULL
, `dashboard_id` INTEGER NOT NULL
);
CREATE TABLE `org` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `version` INTEGER NOT NULL
, `name` TEXT NOT NULL
, `address1` TEXT NULL
, `address2` TEXT NULL
, `city` TEXT NULL
, `state` TEXT NULL
, `zip_code` TEXT NULL
, `country` TEXT NULL
, `billing_email` TEXT NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
);
INSERT INTO "org" VALUES(1,0,'Main Org.',NULL,NULL,NULL,NULL,NULL,NULL,NULL,'2015-08-19 21:32:15','2015-08-19 21:32:15');
CREATE TABLE `org_user` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `org_id` INTEGER NOT NULL
, `user_id` INTEGER NOT NULL
, `role` TEXT NOT NULL
, `created` DATETIME NOT NULL
, `updated` DATETIME NOT NULL
);
INSERT INTO "org_user" VALUES(1,1,1,'Admin','2015-08-19 21:32:15','2015-08-19 21:32:15');
CREATE TABLE `dashboard_tag` (
`id` INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL
, `dashboard_id` INTEGER NOT NULL
, `term` TEXT NOT NULL
);
```

Notes: User seems to be getting the entry from the organization name and the org table doesn't get anything other than Main Org

**Manual fix so far:**

Delete grafana.db. When Grafana starts from scratch, everything works again.

**Comments:**
Is this a possible bug in Grafana where changing an existing db from not anonymous to anonymous doesn't invoke the proper db updating?

**Comment by torkelo** [comment]
No this is not a bug,  the default organization is named Main Org.

**Comment by TannerMoore** [comment]
That was not my question. I changed the organization in my config and it was not updated in the db. please re open this.

**Comment by torkelo** [comment]
That is now how it works.  You need to make sure you have an organization with the same name you specified in your configuration.  

You can set org name in organization preferences view

**Comment by TannerMoore** [comment]
That was the solution! Thank you. I am going to look into how to change the organization outside of the web gui. If you know how to do that, please share. I will edit this comment if I figure it out.

**Comment by torkelo** [comment]
You can use the http api, should be in docs

**Comment by TannerMoore** [comment]
Found the call. Thank you for the help.

**Comment by bradleypeabody** [comment]
> the default organization is named Main Org.

It's really quite an important detail that it's not "Main Org", but actually "Main Org." - with a period at the end (and without the quotes of course). This was a source of much confusion for me.
