### ISSUE TITLE
Time series panel - time axis does not autoscaling

### ISSUE THREAD

**Issue by sven-hash** [grafana/grafana#48998]
**What happened**:

No autoscaling for x-axis timeseries on Brave or chromium based browser

![](https://i.imgur.com/lJvi32y.png)

**Environment**:
- Grafana version: v8.5.2 (90701be19c)
- Data source type & version: Influxdb v2
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Windows/ GNU/Linux  & Brave
- Grafana plugins: None
- Others: -

**Comment by torkelo** [comment]
that is very strange, what data do you have? (panel menu / Inspect / Data)

**Comment by sven-hash** [comment]
If you want to check it in [live](https://grafana.ono.re/grafana/goto/yrw79NX7k?orgId=1) 
![](https://i.imgur.com/xAyXmyr.png)

**Comment by sven-hash** [comment]
Nevermind it was the Brave Browser shield that block something

Sorry for the false alert
