### ISSUE TITLE
TimeSeries: allow toggling of Legends like w/ Graph (old)

### ISSUE THREAD

**Issue by towolf** [grafana/grafana#49005]
**What happened**:

On the old Graph panel we used to be able to toggle panel legends on or off using the panel popup menu ("More..." → "Toggle legend") or using keyboard shortcuts `pl` for panel legend and `dl` for all dashboards.

We used to use this quite often. Our legends are complicated and they clutter the dashboard so we keep them off.  But sometimes the legend is useful and so it can be toggled on-demand.

**What you expected to happen**:

After migrating to the "Time series" panel, the legend toggle shortcuts listed in the help overlay should continue working.

**How to reproduce it (as minimally and precisely as possible)**:

Compare Graph and Time series panel, when hovering press `p l`, `d l`, or look in the panel menu.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.2

**Comment by zuchka** [comment]
I would hop on this recent thread about graph / timeseries parity:

https://github.com/grafana/grafana/issues/49031

**Comment by towolf** [comment]
I don't see how this issue is a duplicate?

**Comment by bobrik** [comment]
I see `p` `l` working for a single panel, but not `d` `l` for the whole dashboard. Is there an issue for that?

**Comment by bobrik** [comment]
I opened #60754 to address `d` `l`.
