### ISSUE TITLE
Alerting: Show matching notification policies in alert creation

### ISSUE THREAD

**Issue by jtheory** [grafana/grafana#49009]
During the alert creation flow, it would be useful to show matching notification policies
![image](https://user-images.githubusercontent.com/6293563/172373975-99d58f0c-219b-49df-96a6-d63698c7e5a1.png)

There is a pretty complex issue related to this though.
Notification policies come from the Alert manager and usually, we don't know what alert manager will be used for a particular rule.

1. For Grafana Managed rules it *may* be the built-in Grafana alert manager but it doesn't have to. 

2. For Prometheus-based rules, it depends on the data source configuration and may be handled entirely out of the control of Grafana.
 
**Partial solution**
For Grafana Managed rules we could fetch the alert manager configuration and if it's configured to use only the internal one we would be able to provide correct notification policies during the alert creation step

Unfortunately, currently to get the information if the internal alert manager is used we need to call the `api/v1/ngalert/admin_config` endpoint which requires admin permission. 
Instead, we would need to create a separate endpoint or pass the information through other channels (`grafanaBootData` maybe?)

The next challenge is to find out all matching notification policies. Due to their hierarchical structure, it's not so easy. Maybe it would be easier to do this on the backend?

**Backend work**
It would be great if there would be an API in the backend to return matching notification policies. This could also be done in the frontend but the logic would be complicated as notification policies can be nested and have options to not stop after matching one notification policy.

**Comment by gillesdemey** [comment]
Blocked by https://github.com/grafana/grafana/issues/49212

**Comment by gillesdemey** [comment]
No longer blocked but we have a few caveats that make this implementation tricky and without 100% confidence.

**Comment by gillesdemey** [comment]
As discussed offline we'll be putting this one on ice and perhaps focus on a debug tool to help debug which notification policy will handle a set of labels.

**Comment by armandgrillet** [comment]
@gillesdemey  Is it resolved by https://github.com/grafana/grafana/pull/61952 ?

**Comment by gillesdemey** [comment]
Partially, ideally we'd want it for the alert rule creation flow too.

**Comment by gillesdemey** [comment]
We need to figure out where this fits in a larger alert creation overhaul epic, no blockers

**Comment by soniaAguilarPeiron** [comment]
closing as we have this one already merged https://github.com/grafana/grafana/issues/68098
