### ISSUE TITLE
Alerting: create legacy alerting deprecation notice

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#49015]
We are deprecating legacy alerting in Grafana 9, we should display a message indicating that legacy alerting is deprecated, will be gone in the next major version of Grafana, and that they should migrate to the new Alerting experience (with a link to the docs).

**Comment by armandgrillet** [comment]
Current message, more informal than ⚠️:
<img width="1407" alt="PS 2022-05-16 à 17 22 19" src="https://user-images.githubusercontent.com/2117580/168627550-703c34c6-7ac4-4b74-8ce4-226cddcd28fb.png">
