### ISSUE TITLE
"null as zero" broken for prometheus queries in "Graph (old)" panels since v8.4.0

### ISSUE THREAD

**Issue by lukeyeager** [grafana/grafana#49030]
**What happened**:
I have a prometheus query which often returns nulls. I want to treat those nulls as 0. This worked prior to v8.3, was broken in 8.3.0, was fixed in 8.3.4, and then was broken again(!) in 8.4.0.

Along with many others, I am eagerly awaiting an implementation for "null as zero" in the new TimeSeries panel type (https://github.com/grafana/grafana/discussions/43093). Until then, it seems the only way I can get what I want is to stay on version 8.3.6.

When it's working (versions 8.0.0-8.2.7, and also 8.3.4-8.3.6), you can see that the average values in the legend are correct.
![image](https://user-images.githubusercontent.com/687269/168667517-f9d18cc8-7825-4c4e-a887-3015c3ea63f1.png)

When it's not working (versions 8.3.0-8.3.3, and also 8.4.0-current), you can see that nulls are not actually set to zero, and the average values in the legend do not match the previous behavior.
![image](https://user-images.githubusercontent.com/687269/168667673-86cfe436-c813-4316-9ae2-e22a8f846ea4.png)

**How to reproduce it (as minimally and precisely as possible)**:
* Setup a prometheus query which returns some nulls (this method seems good: https://github.com/grafana/grafana/pull/43622#issue-1092696347)
* Create a panel for the query: Visualization="Graph (old)", Null value="null as zero"
* Check whether the nulls are set to 0 or not

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: prometheus 2.34.0
- OS Grafana is installed on: docker image `grafana/grafana:8.5.2` (so, Alpine v3.15)
- User OS & Browser: Windows, Firefox
- Grafana plugins: none

**Comment by leeoniya** [comment]
hmm, i think we might need to add a null insertion mode that inserts `null` at _every_ missed interval instead of just the first one.

https://github.com/grafana/grafana/blob/952cb4fc0bbbe7159fc4117cca24307acb7d461e/public/app/plugins/panel/graph/data_processor.ts#L42

**Comment by ryantxu** [comment]
I am eager to fix anything that make it possible for you to run this in the timeseris graph.  It sounds like "null as zero" is the blocker.

**Comment by lukeyeager** [comment]
Yes, I would love to migrate over to timeseries panels. This is one blocker for me.

The other blocker is "Hide all 0's / nulls", too: https://github.com/grafana/grafana/discussions/38299. But if you have energy to fix one today and not the other, I'll gladly take what I can get!

**Comment by JWilson45** [comment]
@lukeyeager were you able to get your time series graph to zero out on null data points? I'm experiencing the same issue.

**Comment by lukeyeager** [comment]
This is not working in v9.0.1.
