### ISSUE TITLE
[bug] Template subsitution in Prometheus queries does not work when template var prefixes metric

### ISSUE THREAD

**Issue by millerjp** [grafana/grafana#4904]
grafana - 2.6.0
prometheus data source
Ubuntu 14

I am trying to template my dashboards and am hitting an issue with how the template vars get substituted (hopefully I am just missing something)

Imagine I had two queries
http_requests_total{job="xxx", handler="yyy"}[5m]
db_requests_total{job="xxx", handler="yyyy"}[5m]

and I defined a template variable "$service" which could have two values "db" or "http"

If I then used that to create a dashboard that lets me choose the service, the prometheus query would (ideally) be 
$service_requests_total{job="xxx", handler="yyyy"}[5m]

However, this does not get substituted and the query to prom just passes in the $service as part of the query (and not substituted)

the following examples Grafana substitutes the correct values, but (obviously) the queries become invalid:

this works (but the prometheus query is then invalid as it includes the quotes in the query):
"$service"_requests_total{job="xxx", handler="yyyy"}[5m]
'$service'_requests_total{job="xxx", handler="yyyy"}[5m]

Also, just as an example of what also works:
http_requests_total$service{job="xxx", handler="yyy"}[5m]

**Comment by millerjp** [comment]
@bergquist is there anyway this can be looked at sooner? Basically, without this its not possible to leverage the histogram functionality (https://prometheus.io/docs/practices/histograms/)  in Prometheus (when using templates) due to the convention it uses for naming metrics.

**Comment by mtanda** [comment]
@millerjp 
Would you try to specify "[[service]]_requests_total", not "$service_requests_total".
Not sure but it might be not a bug.

If you specify like "$service_requests_total{job="xxx", handler="yyyy"}[5m]", Grafana recognize variable name as "$service_requests_total".
https://github.com/grafana/grafana/blob/bd21a08bc9c25dc7c03643ec0d91a22c0deab932/public/app/features/templating/templateSrv.js#L15

**Comment by millerjp** [comment]
@mtanda thanks lots!!!!!! thats done the trick :) You have just saved me hours of hardcoding dashboards!

**Comment by millerjp** [comment]
This is not a bug - there is a way of doing this as described above.

**Comment by mtanda** [comment]
It's my pleasure :-)

**Comment by bergquist** [comment]
@mtanda thank you for helping out! :)
