### ISSUE TITLE
[Feature Request] Mixed datasources with template variables

### ISSUE THREAD

**Issue by evil2bart** [grafana/grafana#4906]
Grafana version 3.0.0 beta 7
Datasource: ElasticSearch
OS: CentOs

I have a dashboard where I in some graphs use mixed datasources. I want to be able to select both of the 2 datasources(or more) I want to use at one time on the dashboard - with only one template variable. I.E. to avoid having 2(or more) template variables I need to change, to get the right view.

I have tried using a Custom template variable where i entered the names of the systems I want to monitor, and then a Datasource template variable where I used the Custom variable in the regex field. This only works partly - the first datasource is correctly selected, but every time I try to change my Custom template variable (switch system), the Datasource variable does not change - it only changes on updates or page reload.

So what i need is: The Datasource template variable to update each time i update another template variable - or some other solution that solves the same problem :-)

Best regards
Søren Schmidt

**Comment by torkelo** [comment]
could you describe more the setup, not understanding your scenario. 

What panels do you have with what queries, what template variables do you want?

**Comment by evil2bart** [comment]
Lets say i have a dashboard with 2 graph panels:
- a graph panel that uses datasource "one" 
- a graph panel that uses datasource "two".
Both datasource "one" and "two" belongs to the same system/environment.

Now i add a second system/environment that should show the exact same graphs as the first system/environment. - but this system uses datasource "three" and "four" instead of "one" and "two".
"three" contains the same kind of data as "one" - e.g room temperatures
"four" contains the same kind of data as "two" - e.g cpu usage

Now, if i only want to create both graphs once(and only one dashboard), and then just change datasource (via template variable), i would be needed to create 2 template variables to switch between system:
- one for "one" and "three"
- one for "two" and "four" 

But what i want is: only to have one template variable(that are visible), so i dont need to change both template variables each time i switch between systems/environments.

A solution would be to create a custom template variable where i manually enter "system 1" and "system 2". This variable are then to be used in the first two template variables, so:
- i select "system 1"  --> the two first datasource template variables switch to: "system 1 - room temp" and "system 1 - cpu usage"
- i select "system 2" --> the two first datasource template variables switch to: "system 2 - room temp" and "system 2 - cpu usage"

I can do this by using regex - but it only updates when i create/update the two first datasource template variables - i need it to update the two first template variables each time i select a new system from my custom template variable
