### ISSUE TITLE
Bar chart displays no bars when all values in one Row are 0 and stacking is 100%

### ISSUE THREAD

**Issue by 2000Slash** [grafana/grafana#49077]
**What happened**:
All bars disappeared in the Bar chart

**What you expected to happen**:
Only the chart which contains the zeros should disappear

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new Bar chart panel
2. Set Stacking -> 100%
3. Use testdata DB to input this example csv:
```csv
name, number, number2, number3, number4
Name1, 40, 5, 20, 10
Name2, 0, 0, 0, 0
Name3, 6, 3, 5, 1
Name4, 1, 1, 1, 2
```
4. No bar is displayed:
![image](https://user-images.githubusercontent.com/10107972/168809212-36a26d01-6f40-4f6b-8334-8c7b4d53d9cb.png)

6. Change a zero to any other number:
```csv
name, number, number2, number3, number4
Name1, 40, 5, 20, 10
Name2, 0, 0, 0, 1
Name3, 6, 3, 5, 1
Name4, 1, 1, 1, 2
```
7. Bars are displayed correctly

**Environment**:
- Grafana version: 8.5.2 (90701be19)
- Data source type & version:  Loki v2.5.0 but also TestData DB
- OS Grafana is installed on: Windows
- User OS & Browser: Windows. Firefox and Chrome
- Grafana plugins: -
- Others: This happens on https://play.grafana.org/ as well

**Comment by mellieA** [comment]
Reproduced this on play
