### ISSUE TITLE
[Bug] Templating with filtering on another template is not working

### ISSUE THREAD

**Issue by menardorama** [grafana/grafana#4907]
Hi,

In recent influxdb version (or maybe it's just that I found it last month...) we have the possiblity to filter the "show tag value" against other tags.

It was working in previous releases of grafana (maybe the latest stable) by issuing like that  :
`SHOW TAG VALUES FROM disk WITH KEY = "path" where host='$host'`

the $host is another template variable.

Now when I try on the latest "testing" version I get this error : 
`Template variables could not be initialized: error parsing query: found \., expected identifier, string, number, bool at line 1, char 63`

If I substitute with a hard coded hostname it's working fine.

Grafana version : grafana-3.0.0-beta71462173753.x86_64
OS : Centos6
Datasource : influxdb-0.12.2-1

Thanks for your help and great product

**Comment by torkelo** [comment]
try this instead:
SHOW TAG VALUES FROM disk WITH KEY = "path" where host=~/$host/

**Comment by menardorama** [comment]
It gives me another error : 
`Template variables could not be initialized: error parsing query: found /, expected regex at line 1, char 57`

**Comment by torkelo** [comment]
Sorry there should be some whitespace before regex, 
`SHOW TAG VALUES FROM disk WITH KEY = "path" where host =~ /$host/`

**Comment by menardorama** [comment]
OK great thanks it's working now
