### ISSUE TITLE
[9.0] Check for Angular usage in Explore

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#49087]
This is for investigation only - the outcome of this ticket should be a list of where Explore uses Angular to fix in later tickets.

**Comment by ifrost** [comment]
- [x] no Angular components in `public/app/feature/explore`
- [x] no Angular components Explore would depend on
- [x] Check Angular runtime code 
  - [x] https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L837
  - [x] https://github.com/grafana/grafana/blob/main/public/app/features/explore/state/query.ts#L847
  - [ ] we can wrap the code in `if (config.angularSupportEnabled) { ... }` - this way we won't forget to remove it when the flag is removed in Grafana 10.0
- [x] Tested manually Explore with `[security]` flag: `angular_support_enabled = false`
  - [x] Selecting a data source
  - [x] Adding and running queries
  - [x] Split view
  - [x] Query history
  - [x] Linking time range
  - [x] Inspector
  - [x] Add to Dashboard
  - [x] Command Palette
