### ISSUE TITLE
[Feature Request] Add a column panel and row panel in a row 

### ISSUE THREAD

**Issue by menardorama** [grafana/grafana#4908]
Hi

In order to have more possibility to design a dashboard it could be great to have a sort of "html frame" free to define instead of the legacy "row mode" herited from kibana

Do you think it could be feasable to have a row and column panel in a row ?

This could permit to have something more user friendly

Thanks

**Comment by torkelo** [comment]
yea, we want to improve layout possibilities in the future, 

will close as there is already an issue for columns, https://github.com/grafana/grafana/issues/170
