### ISSUE TITLE
Bug Bash for unified secrets

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#49092]
- [x] Create doc for bug bash
- [x] Create invite
- [x] Share broadly for cross-team collaboration
- [x] Log any findings as bug fixes

**Comment by timlevett** [comment]
Created internal doc for test cases; https://docs.google.com/document/d/1yUodgKJh2uodO6HX6XYLqB4HYhrnFsvTUd9t5ZJlGy4/edit?usp=sharing

**Comment by timlevett** [comment]
Scheduled for Thursday (May 19)

**Comment by timlevett** [comment]
Link to the event can be found on the "Grafana Team" calendar.

**Comment by mmandrus** [comment]
@timlevett I don't believe we have any actions coming out of this doc, the only issues that were found were not unified secrets related. Please have another look to confirm, but I think we are good to close this.
