### ISSUE TITLE
[Feature Request] Add more theme or a theme designer

### ISSUE THREAD

**Issue by menardorama** [grafana/grafana#4909]
Well most of my idea is in the subject, lots of users complains about the dark and light theme in my company.

Having something to design it's own theme could be great and in some company where they have some "color web design" guideline it could be easily adapted

**Comment by torkelo** [comment]
The dark UI is usually the top rated thing users love about Grafana :) But can't please everyone. 

I think the light UI could need some improvements. But supporting more themes is not going to happen, it's a lot of work to support 2.  

You can create your own theme by forking Grafana and changing the sass variable files :)

**Comment by menardorama** [comment]
Well that's a quite expeditive point of view.... When it's a user feedback  anyway 

Could at least it could be possible to have a hook where we could define an additionnal theme definition file in the /etc/grafana ?
Forking is not a good option I Will loose future change

And i don't Want to change the frontend yet 

Thomas

**Comment by Dunky13** [comment]
I concur with the above stated comment^

**Comment by menardorama** [comment]
And What do you think to have a slack like theming ?
