### ISSUE TITLE
Auth: Provide ID token via PluginContext.User in case of OAuth AAD authentication

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#49104]
In case if user was signed-in to Grafana using OAuth AAD authentication and ID token was provided as result of the authentication request, then pass the received ID token to Grafana plugins via PluginContext.User struct.

This is OAuth AAD implementation task for:
* https://github.com/grafana/grafana-plugin-sdk-go/issues/506

**Comment by tolzhabayev** [comment]
related https://github.com/grafana/grafana-plugin-sdk-go/issues/579#issuecomment-1402186835

**Comment by marefr** [comment]
I'll close this since already partly supported and tracked via https://github.com/grafana/grafana-plugin-sdk-go/issues/579
