### ISSUE TITLE
Template variables do not work with annotations

### ISSUE THREAD

**Issue by janrich** [grafana/grafana#4911]
Template variables do not seem to work with annotations (but they do work with graph, table etc.). The datasource used was Elasticsearch 2.x.

Grafana Version: 3.0.0-beta7
OS: Ubuntu Server 14.04
Error Message:
![annotation_error](https://cloud.githubusercontent.com/assets/7627360/15026170/6b6cb3ce-123d-11e6-93bc-0ab8351e748d.png)

**Comment by torkelo** [comment]
could you show the templating query and the elasticsearch response? Chrome dev tools network tab, both request and response would be interesting.

**Comment by janrich** [comment]
The template query is a simple lucene query: {"find": "terms", "field": "user"}. The response is a list of user names (unfortunately I can't show the data here). The Annotation query is: type:session AND $User. The name of the template variable is 'User'. Both the template variable and the annotation without the User variable work, but not when I use the template variable in the annotation query.

**Comment by torkelo** [comment]
And does the value of $User constitute a valid ES lucene query? You did not show the ES response, so I don't know the error ES returns :(

**Comment by janrich** [comment]
'User' refers to the template query which is: {"find": "terms", "field": "user"}. The same setup worked in Grafana 2.6. I took the query from the Grafana Documentation for Elasticsearch. The field 'user' contains only user names, and the query (template variable) gives the list of user names.

**Comment by torkelo** [comment]
What's the response from ES for the annotation query?

**Comment by janrich** [comment]
I installed Grafana v3.0.4 and the issue is fixed!
Many thanks!
