### ISSUE TITLE
Template variables link in basic_concepts.md is not working

### ISSUE THREAD

**Issue by adigov** [grafana/grafana#4912]
This link is broken - https://github.com/grafana/grafana/blob/master/reference/templating 
in the page https://github.com/grafana/grafana/blob/master/docs/sources/guides/basic_concepts.md

Basically I am looking for how to add Template variables for simple-json-datasource

**Comment by torkelo** [comment]
the links works better on the real docs site:
http://docs.grafana.org/guides/basic_concepts/

if you want to implement templating you need to modify the simple json data source, it does not support templating yet. 
https://github.com/grafana/simple-json-datasource/blob/master/src/datasource.js#L54
