### ISSUE TITLE
add datasource -> "with credentials" does nothing?

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4913]
grafana 3beta master.
trying to add a datasource, i get this option, but when i click it, nothing happens besides the animation of the toggle itself. same thing whether 'basic auth' is enabled or not.

![creds](https://cloud.githubusercontent.com/assets/20774/15028196/9feaae80-1215-11e6-88dc-fc8a31ba115d.png)

quite confusing.

**Comment by torkelo** [comment]
it is an option on browser http requests that controls if client cookies are included in a CORS request.

https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/withCredentials
