### ISSUE TITLE
PanelEditor: Table view height does not account for frame selector 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#49145]
With a multi-data frame result switch to table view in panel edit, the frame selector extends beyond the panel bounds intersecting the tabs below  

![Screenshot from 2022-05-18 11-01-20](https://user-images.githubusercontent.com/10999/169003065-fb7c5f6c-55ee-40e8-a5d2-1559b67f9d57.png)

**Comment by torkelo** [comment]
Relevant are of the code: https://github.com/grafana/grafana/blob/main/public/app/features/dashboard/components/PanelEditor/PanelEditorTableView.tsx

**Comment by JoaoSilvaGrafana** [comment]
Moved this to our "Next" column and adding it to the bug bash [spreadsheet](https://docs.google.com/spreadsheets/d/1GrH7hgCH8_-D2QOJ3bTwoMVQ68wYUBW2X7UQv62Ql0E/edit#gid=0) that we are planning to fix in the next couple of weeks!
