### ISSUE TITLE
Unable to get a bar graph to work

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4914]
influxdb-0.11.0-1
grafana-3.0.0-pre1

![screen shot 2016-05-04 at 2 05 19 pm](https://cloud.githubusercontent.com/assets/406777/15029217/7a854eac-1201-11e6-957f-fd464f1e9e77.png)

When i enable Bars it looks like this
![screen shot 2016-05-04 at 2 07 22 pm](https://cloud.githubusercontent.com/assets/406777/15029233/8e5cc108-1201-11e6-8517-aba4e778aa9c.png)

I have 4 metrics that is measured every quarter and i want a bar graph.

SELECT sum(exptVolume) AS exptVolume, sum(qualityFailure) AS qualityFailure, sum(deltaFailure) as deltaFailure, sum(totalFailure) as totalFailure, sum(qualitySuccessRate) as qualitySuccessRate FROM ep."default".epprogram WHERE time > 1430773262s AND time < now() GROUP BY time(12h) fill(none)

---------------
time			exptVolume	qualityFailure	deltaFailure	totalFailure	qualitySuccessRate
2016-01-01T00:00:00Z	452		24		48		72		168.14
2016-04-01T00:00:00Z	210		6		26		32		169.52
2016-05-03T00:00:00Z	662		30		74		104		168.58

**Comment by torkelo** [comment]
try chaning fill(none) to fill(null), bars require continuous series (so does stacking in grafana), so it is usually always good to have fill(null) to include missing data points, otherwise grafana does not know where data is missing or it's harder to determine interval between points.

**Comment by deepujain** [comment]
![screen shot 2016-05-05 at 3 27 52 pm](https://cloud.githubusercontent.com/assets/406777/15059225/f5bb3c4c-12d5-11e6-8077-a8f685aa6667.png)


The width of bar is too less. Very thin bars. How do fix that ?


And how do i change the label names and remove the db name (epprogram)

**Comment by torkelo** [comment]
Change the group by time interval if you want bigger bars, use alias patterns to get the legend name you want
