### ISSUE TITLE
Label is not aligned

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4915]
influxdb-0.11.0-1
grafana-3.0.0-pre1

![screen shot 2016-05-04 at 2 15 46 pm](https://cloud.githubusercontent.com/assets/406777/15029515/c07bb29c-1202-11e6-9179-0e5c717d03b7.png)

1. epprogram.Experiment Volume is coming in next line despite increasing the width of widget
2. No way to get rid of measurement name (epprogram) from labels.

**Comment by torkelo** [comment]
when you have legend to the right, also enable table mode for the legend. It should fix the alignment. 

2) Please review the alias pattern options, you have a help field below your queries "Alias patterns" that describes how to get short series names. 
<img width="745" alt="screen shot 2016-05-05 at 10 05 17" src="https://cloud.githubusercontent.com/assets/10999/15038970/ee9fccca-12a8-11e6-9a3d-21de55553620.png">
