### ISSUE TITLE
setting http header options for datasources

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4916]
it would be nice if we could configure http headers for datasources.
it seems like we need this to use the tsdb service (https://github.com/raintank/raintank-apps/issues/2), so we can pass the api key along. would like to have this confirmed by @woodsaj when he's back from paternity though.

**Comment by torkelo** [comment]
this is already handled with a feature in app plugins that allows them to specify an api proxy route that can use templating and data from an encrypted plugin config field. 

https://github.com/raintank/worldping-app/blob/master/plugin.json#L14
