### ISSUE TITLE
[Bug] Metric choice

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#4917]
Hi,

On last Grafana beta 3, when we choose "Raw Documents" as metric (ES source in table element, I don't try with other) if we have made a mistake and want to change the metrics there is no effect.
If we exit editor and come back, query field is unavailable and replaced with "{{ctrl.target.refld}}({{ctrl.target.datasource}})".
![selection_004](https://cloud.githubusercontent.com/assets/6485132/15037899/4df70c88-129f-11e6-8478-26b201d462cd.png)

Solution is to remove element and recreate it.

Thank you

**Comment by torkelo** [comment]
Cannot replicate it here, try latest beta7 and remember to restart grafana-server. 

<img width="873" alt="screen shot 2016-05-05 at 10 14 02" src="https://cloud.githubusercontent.com/assets/10999/15039094/202d5702-12aa-11e6-9bc5-558cc002b825.png">

**Comment by torkelo** [comment]
if the issue persists, can you tell me what your javascript console says (Js errors)

**Comment by matthgyver** [comment]
On latest firefox and Grafana beta71462173753 I get this message if I would change "Raw Documents" to another metric :

```
Object { message: "Invalid query" } boot.8401a6a2.js:35:10965
e/<() boot.8401a6a2.js:35
vb/this.$get</<() boot.8401a6a2.js:34
vc/this.$get</n.prototype.$digest() boot.8401a6a2.js:35
vc/this.$get</n.prototype.$apply() boot.8401a6a2.js:35
.link/h.updateVariableValue() boot.8401a6a2.js:20
.link/h.switchToLink() boot.8401a6a2.js:20
.link/h.updater() boot.8401a6a2.js:20
b.prototype.select() boot.8401a6a2.js:8
b.prototype.click() boot.8401a6a2.js:8
.proxy/e() boot.8401a6a2.js:31
aa.event.dispatch() boot.8401a6a2.js:32
aa.event.add/q.handle() boot.8401a6a2.js:32
```

**Comment by torkelo** [comment]
And your using table panel?

**Comment by matthgyver** [comment]
Not only.
Problem is for each element with metrics.

**Comment by danielkman** [comment]
+1
