### ISSUE TITLE
[Bug] thresholds don't seem to work in latest beta

### ISSUE THREAD

**Issue by evanrich** [grafana/grafana#4920]
I'm running grafana on debian 8.4 x64, running latest beta ( 3.0.0-beta71462173753) with an influxdb (0.11) backend

I just tried setting up a couple single stat panels, using thresholds to set the color based on value, but I don't think they're working right.
![grafana](https://cloud.githubusercontent.com/assets/518320/15039028/f8dc7a76-125d-11e6-9637-fef6b0d024fd.jpg)

As you can see, I've set thresholds for 30,40, which according to the tooltip, should mean that the current value of 25.1 should be green, but it's orange.   I've tried every possible combo I can think of, 0,1, 0,1... even 30000,40000, just to cover all bases.    Nothing I've entered will make the value turn green.  The only thing that will turn green, is the border around the gauge, if i reverse the color order, but nothing will make the text color/background color change.

Am I missing something, or is this broken?

**Comment by torkelo** [comment]
thanks for reporting this. If you try to hit the refresh after you made the thresholds change you should see them take effect, this worked for me at least. 

But did implement a fix so that the panel rerenders correctly directly after you changed the thresholds
