### ISSUE TITLE
Alerting | Notifications | Telegram: Markdown markups are not rendered in alerts

### ISSUE THREAD

**Issue by cuihaoleo** [grafana/grafana#49200]
I've read https://github.com/grafana/grafana/issues/43485 but I believe "adding images" isn't the whole point. The default text looks like in markdown format but it doesn't get rendered:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/889871/169144529-07545db1-54fa-4872-afed-878323af333e.png">

I think the line `**Firing**` intended to use markdown markup to bold the text but failed.

I found this after a quick search of Telegram-related code:
https://github.com/grafana/grafana/blob/e135b8531a7e0e9606f58bfd4b291cec1394c3d5/pkg/services/ngalert/notifier/channels/telegram.go#L145

If the message string here is not rendered HTML but raw markdown, then `parse_mode` should be set to `MarkdownV2` instead of `html` (ref: [Telegram doc](https://core.telegram.org/bots/api#formatting-options)).

I tried HTML tags in my own templates to accomodate the `html` parse mode, and confirm that HTML tags indeed get rendered.

Example template code: `{{ len .Alerts.Firing }} <b>BOLD</b> <i>ITALIC</i> <code>CODE</code>`

Telegram message:
<img width="151" alt="image" src="https://user-images.githubusercontent.com/889871/169146528-68e04590-2a9c-49af-8df6-1a37405c2aed.png">

This is not really a bug but I feel the default setting should be adjusted to avoid bad default layout. My suggestions:
- If the default template produces markdown, then the default `parse_mode` should be set to `MarkdownV2`.
- Telegram `parse_mode` param should be made configurable in the contact point setting.

**Environment**:
- Grafana version: docker.io/grafana/grafana:8.5.2 arm64 build

**Comment by Mtt6300** [comment]
I have same issue. There is any plan to fix this ? 
![image](https://user-images.githubusercontent.com/45437060/184473075-5bea8de2-f20f-4155-9168-d818a830aa56.png)

* Grafana version: docker.io/grafana/grafana:9.1.0-beta1

**Comment by HATRED-arh** [comment]
Same issue here

**Comment by arturucraft** [comment]
> I had some issues while sending md formatted text to telegram. I switched to html and it solved my issue. So for the grafana, I think it should be html format but with appropriate formatting:
> 
> ```
> <b>Firing</b>
> Value: [bla bla ]
> 
> etc...
> ```

he <a href>-s in telegram, it is not showing the links, it simply shows text:

`<a href="{{ .DashboardURL}}"> DashboardURL</a>`

but if i am putting

`<a href="https://example.com"> DashboardURL</a>`

it works perfectly. or if i put

`{{ .DashboardURL}}`

it also correctly shows the `DashboardURL `value

for whatever reason the `href `and `{{ .DashboardURL}`} are not working together

i am running grafana:latest (the 10 version) and my parse mode is set to HTML. everything is working fine, just the href + Dashboard or any other variables are not working 

any hints are appreciated to solve this
