### ISSUE TITLE
How to pie chart ?

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#4921]
Hi,

I've informations of NAS quota by users like this : space used 12Gb / Quota 15 Gb.
I'd like to build a pie chart to represent usage compared to quota.
After lot of tests I can't do that maybe because I'm noob with Elasticsearch or Grafana.
Have you an idea to do that please ?

Thank you

**Comment by torkelo** [comment]
`How to pie chart` that is **the** question! :) 

Well there is answer, there is an external plugin you can use. It is not super polished as the built in panels but works for some basic pie chart scenarios.

https://grafana.net/plugins/grafana-piechart-panel

**Comment by matthgyver** [comment]
Yes I've tried the plugin but my quesstion was'nt clear. I was tired :-/
I've 2 datas : space used and quota.
I'd like ti build a pie chart that represent space usage in repport with quota.
So quota is full pie chart if space used is 0% and pie chart is divide in 2 if space used is 50% by exemple.
I'll ask this question in the project github page.
Thank you

**Comment by digrich** [comment]
I believe, if you have space used/available data under same metrics key with different tags, you can draw that information on pie chart.
