### ISSUE TITLE
inconsistent test in the alerting codebase

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#49225]
when the Drone CI runs the backend tests for a pull request, it often fails with this:
`FAIL	github.com/grafana/grafana/pkg/tests/api/alerting`
for code that does not change anything related to that place.
re-running the CI-job often fixes the problem, so i assume it's an inconsistent test.

**Comment by gotjosh** [comment]
Can you please post an example of the test that's failing? A link to drone should suffice so that we can investigate the failing test.

**Comment by gabor** [comment]
sorry, i do not have an example CI-job currently, i haven't seen the problem lately, maybe it got fixed somehow?

i remember that it looked like a timeout-thing, i mean, the test did not finish in a long time and had to stopped.

**Comment by gotjosh** [comment]
We're usually pretty good and fixing these when they come up, so I'll assume it's been resolved but please feel free to re-open if you see it again.
