### ISSUE TITLE
[Bug] Setting [security] admin_password does not set the admin password

### ISSUE THREAD

**Issue by LaszloHont** [grafana/grafana#4923]
Hi,

I don't know if this is a bug or a feature request or a question, but from my reading of the docs, it seems like setting admin_password in the [security] section should change the password that the admin user uses.

It doesn't though: the password in the sqlite database remains the same and the old default "admin" continues to work.

**Comment by torkelo** [comment]
The documentation should perhaps be made more clear for this setting, but the setting only controls the initial admin user's password that is created the first time you start grafana when there are no users.

**Comment by LaszloHont** [comment]
It would be a nice feature to be able to change the admin password this way, as part of Puppet or ansible (or to warn when the admin password mismatches). If it is a once only setting, does it belong in the configuration file?
