### ISSUE TITLE
Alerting: Grafana alertmanager's email notifier eats newlines in templates

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#49256]
**What happened**: 

When sending an email using the Grafana Alertmanager and a custom/templated message, any newlines in the template are removed and the message appears all on one line.

This does not happen in any of the other notifiers - newlines work as expected in Slack or Teams. This isn't due to go-template behavior, but rather, this happens because our second layer of templating on emails wraps the message in HTML formatting, which breaks the newlines in the raw text template.

We should try to modify the HTML wrapping here: https://github.com/grafana/grafana/blob/main/public/emails/ng_alert_notification.html

so that it properly handles newlines in the message body.

**What you expected to happen**:

I expected newlines in my template to be visible in the resulting email. Instead, all the text was mushed together into a single giant line.

**How to reproduce it (as minimally and precisely as possible)**:

Send an email using Grafana Alerting, with a custom template that contains a newline.

The template I used was:
firing: {{ len .Alerts.Firing }}
another line

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version: n/a
- OS Grafana is installed on: Linux
- User OS & Browser: FIrefox
- Grafana plugins: n/a
- Others: n/a

**Comment by kianelbo** [comment]
I'd be happy to fix this as my first contribution!
Just a tiny question, shouldn't this file be changed instead?
https://github.com/grafana/grafana/blob/main/emails/templates/ng_alert_notification.html

**Comment by killafunkinmofo** [comment]
> I'd be happy to fix this as my first contribution! Just a tiny question, shouldn't this file be changed instead? https://github.com/grafana/grafana/blob/main/emails/templates/ng_alert_notification.html

Isn't that file just good for the main default template though? What if there are several contact points that want to have several different templates with new lines?

**Comment by alexweav** [comment]
Fixed by https://github.com/grafana/grafana/pull/52253
