### ISSUE TITLE
[Question]  Grafana capabilities in large time windows 

### ISSUE THREAD

**Issue by bischofs** [grafana/grafana#4925]
We are using grafana hooked up to an influxDB instance on the same machine for some testing. We preloaded about 1.1 million time series points into the database ( 80 series * 132000 points each)  from the past year. In Grafana only showing 3 series the browser eats ram and fails to load a simple query when the time window is large enough. Does the view get lower resolution as the time window is increased? How can we improve the performance so that we get a basic overview?

I have heard that new versions of graphite fix this? im using 3.0.0-beta7 of grafana.

The server has a PCI-E ssd
running ubuntu 16.04 server

**Comment by torkelo** [comment]
What's your InfluxDB query? Especially group by time parameter.  If you let grafana set group by time option  (using query editor), it should set group by time interval based on time range

**Comment by bischofs** [comment]
I am not doing any group by, just querying the value field of 3 measurements

**Comment by torkelo** [comment]
You need to group by time, otherwise InfluxDB will return millions of data points and bang your browser :)

**Comment by bischofs** [comment]
Ok that makes sense,  but shouldn't the client limit the amount of rendered points in an effort to not destroy itself?

**Comment by torkelo** [comment]
It does if you use the query editor and the auto group by time

**Comment by bischofs** [comment]
Ok thanks for the help!

**Comment by bischofs** [comment]
When I group by time it gives an error requiring an aggregate function, which doesn't make sense to me. Is this because of the structure of influx?

**Comment by torkelo** [comment]
Yes, InfluxDB needs to know how to merge a number of values to one value (in an aggregation function)
