### ISSUE TITLE
Unable to create a home dashboard per organization

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4927]
I want to create a home dashboard per organization and am unable to do it. If i save in home.json it gets overwritten across organizations.

**Comment by torkelo** [comment]
You can do this in Grafana 3.0,  in org preferences page you can choose what home dashboard you want

**Comment by deepujain** [comment]
It does not allow me to choose a different dashboard.

I want to set "Experimentation Data Quality" as home page. But it shows only one option in drop down,


![Uploading Screen Shot 2016-05-05 at 10.07.49 PM.png…]()
<img width="590" alt="screen shot 2016-05-05 at 10 07 36 pm" src="https://cloud.githubusercontent.com/assets/406777/15064850/ecb6a8c4-130d-11e6-8dbc-698bef016928.png">

**Comment by deepujain** [comment]
<img width="591" alt="screen shot 2016-05-05 at 10 18 15 pm" src="https://cloud.githubusercontent.com/assets/406777/15064971/4b03fd4a-130f-11e6-8b95-54fd4a0605ab.png">


Stop showing that as well

**Comment by utkarshcmu** [comment]
You need to star a dashboard to see it in the dropdown

**Comment by deepujain** [comment]
+1 Awesome tip

**Comment by torkelo** [comment]
I know this isnt self evident,  in latest beta there should be a tootip and help icon that explains it

**Comment by caseylucas** [comment]
This is a great feature. Thanks.  Is it possible to select/use a non-starred dashboard?  I'd like to make a file based (vs db based) dashboard the default.  Apparently file based dashboards cannot be starred.

**Comment by torkelo** [comment]
No only DB dashboards can be picked :(

**Comment by caseylucas** [comment]
What about starring a file based dashboard?

**Comment by muellerk22** [comment]
I install dashboard programmaticlly and  want to set the home dashboard in the "Main Org." as well.  Is there a way to "star" the dashboard while installing and then set the 'Home Dashboard" too?
