### ISSUE TITLE
Too thin bars in bar graph

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4928]
influxdb-0.11.0-1
grafana-3.0.0-pre1

These bars are too thin, how do make them fat ? (thicker bars)

![screen shot 2016-05-05 at 3 36 46 pm](https://cloud.githubusercontent.com/assets/406777/15059404/362f59e2-12d7-11e6-962c-e735ac93516d.png)
![screen shot 2016-05-05 at 3 37 15 pm](https://cloud.githubusercontent.com/assets/406777/15059409/4242b3d2-12d7-11e6-8362-deb69d255cd3.png)

**Comment by timgriffiths** [comment]
Most likely you just need to increase\set the group by time interval

**Comment by deepujain** [comment]
I do have group by and it's randomly set to 10d and I tried different
values.
I have only three data points one for each quarter.

**Comment by torkelo** [comment]
Increase group by
