### ISSUE TITLE
Add a `ProvideService` to the screenshot service.

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#49296]
services/ngalert currently sets up a screenshot and image service in its own initialization function. We should make the screenshot service available to dependency injection by implementing ProvideService.

**Comment by alexweav** [comment]
Related epic: https://github.com/grafana/grafana/issues/47275

**Comment by grobinson-grafana** [comment]
I think before we can do this we need to figure out how different consumers of the screenshot service can provide different configurations to `ProvideService`. For example, the reporting service doesn't want to use the configuration from alerting, and vice versa.

**Comment by joeblubaugh** [comment]
I think we can close this; it's not high priority, and given the work to render graphs without screenshotting it may not get us anything.
