### ISSUE TITLE
[Feature Request] Gauge min/max value as variable

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#4929]
Hi,
It's will be nice if we could use a variable as min and max value in gauge panel.
In my case, I monitor utilization of data and have data formatted like this : 

```
Login | Space used | Quota
Foo   | 35 Gb      |50 Gb
Bar   | 65 Gb      |100 Gb 
...
```

So "space used" is the query result and "Quota" should be Max value of gauge.
I think that is there other usage of variable as min/max value.

Thank you very much for your great job !

**Comment by bodsch** [comment]
Ohh, i want exact this!
as example: We have many tomcat container here, and i will display the used memory, gc and other values in a gauge panel.
i need an configurable max value for this.

**Comment by prologic** [comment]
I wan this too! My use case is to display a gauge of disk/file-system usage where max is based on a non-visualized query (disk1.Total)

**Comment by tristanbes** [comment]
I'm totally +1 for it , one simple use case:

Number of login inside an application
Maximum value : MAX Number of login SINCE 7 days

**Comment by jeremyscalpello** [comment]
Another +1 from me. 

I'd love this feature to be able to display the number of "up" devices out of a total instead having 2 individual stats, "up" and "down".

**Comment by abmaymic** [comment]
Another +1 from me.

**Comment by vdemonchy** [comment]
I'm seconding this, I can think of countless applications for this features at work :)

**Comment by MatrixCrawler** [comment]
+1 from me.

That feature would really come in handy.

**Comment by norganna** [comment]
+1, just tried to do this and was devastated that it didn't work.

**Comment by sco01** [comment]
+1 This is really needed.

**Comment by fork04** [comment]
+1 it would be really useful

**Comment by kbabioch** [comment]
Monitoring OSDs in a Ceph cluster, could also use this feature!

**Comment by jbbth** [comment]
+1 here too!

**Comment by Architecttheday** [comment]
this would be really appreciated.

**Comment by dynek** [comment]
Hello,

Any defined milestone? Last update was for 4.2.0 but it obviously doesn't contain this shiny new feature :-)

Thanks for the great work!

**Comment by jdmaloney** [comment]
+1 Definitely would use this, would be way better than having to manually update the max TB/PB when we grow a file system

**Comment by cloudsre** [comment]
+1 this is really an useful feature.

**Comment by caedev** [comment]
+1

**Comment by jyvet** [comment]
+1

**Comment by bentzys** [comment]
+1

**Comment by MaartenUreel** [comment]
+1

**Comment by jflory7** [comment]
+1, I was just trying to see if this was doable and came across this issue. It would be nice to see this get reworked into a new milestone since v4.2.0 has passed for some time.

**Comment by Eloo** [comment]
+1

**Comment by cims-admin** [comment]
+1

**Comment by sgoodliff** [comment]
+1

**Comment by cattt84** [comment]
+1 (I really need this!)

**Comment by andybyrne** [comment]
Another +1 from me. Wanted to see if I could set the max to be whatever the jam_threads_peak value was from prometheus metrics.

**Comment by spectralsun** [comment]
+1

**Comment by dangshui** [comment]
+1

**Comment by Szabadember** [comment]
+1

**Comment by AlexGreg** [comment]
+1

**Comment by SeriousM** [comment]
+1

**Comment by andrewaldasoro** [comment]
+1

**Comment by fork04** [comment]
+1

**Comment by Othyus** [comment]
+1

**Comment by ptagr** [comment]
+1

**Comment by saurabhchakrabarti** [comment]
+1

**Comment by mmoya** [comment]
Please add your reaction to the first post instead of posting a `+1` message. People subscribed to notifications of this issue will appreciate it. Thanks.

**Comment by audioscavenger** [comment]
+1
I would definitely appreciate the use of variables in the gauges for max settings, as it is easy to query a value  into a variable.

**Comment by sharenz** [comment]
+1

**Comment by liKe2k1** [comment]
+1

**Comment by Meghna-singh** [comment]
+1

**Comment by jinh-dk** [comment]
+1, this will give us flexibility to monitor the disk usage, because disk capacity may change in the future, hardcode value give us a lot of boring work to update.

**Comment by brice86** [comment]
+1

**Comment by masterdam79** [comment]
+1

**Comment by rockaut** [comment]
+1

**Comment by ljb2of3** [comment]
This would definitely be useful! I have dashboard monitoring IPs leased per scope on my DHCP servers. This is based on a repeating panel for each scope. I'd love to be able to use a gauge to set the max and warning values dynamically. I'd need to use math to do this, where the max is used + free IPs since those are the two stats I have available. Of course, I could manually set up this dashboard, but I have hundreds of scopes to monitor.

**Comment by rockaut** [comment]
I always thought it would be great to add more than one query to the SingleStat panel and then just use the additional queries for min, max, etc....

**Comment by ipsecguy** [comment]
I'd like to use it show Connection Speed Ranges of 30+ sites with varying max values. So +1!

**Comment by hungdohuy** [comment]
+1, it's very useful if we have this feature

**Comment by aaron-613** [comment]
+1 for max please!  Gauge is almost useless without it for me.

**Comment by StefanSa** [comment]
+1 the same for me, i need this feature too.

**Comment by realies** [comment]
+1

**Comment by PatrykGala** [comment]
+1

**Comment by xkisu** [comment]
+1

**Comment by kadern0** [comment]
+1

**Comment by tristanbes** [comment]
How come it seems that ALL the people receive those annoying notification EXCEPT the maintainers :s 🤔

**Comment by torkelo** [comment]
We see them all right , about a 100 a day :). Anything we should do about it?

**Comment by sanderploegsma** [comment]
To the people having to adjust every gauge when something like disk space changes, why not display a usage in percentages? So `current()/max()` 

I can still see how this feature request is an improvement to that, but I thought it could help in the meantime.

**Comment by Miller-STGT** [comment]
@sanderploegsma Great idea as a workaround!
But I hope they will make it possible in the near future to use variables for min/max values.

**Comment by veve90** [comment]
+1

**Comment by dyordanovv** [comment]
> @sanderploegsma Unfortunately that only is possible with certain backends, can't do that with InfluxDB AFAIK... ☹️

It is possible, we are using it with InfluxDB with the following metric:

`SELECT mean("used_space")/mean("total_space")*100 FROM "disk_space"  WHERE ("hostname" =~ /^$server$/) AND $timeFilter GROUP BY time($__interval) fill(null)
`
Now all you have to do is to change the unit to percent (0-100), define your thresholds and configure max Gauge to 100 in the option tab

**Comment by Tenchi2xh** [comment]
@dyordanovv Only works if your "total" value is contained in the same metric, which is not the case for me. Also this will only give you a percentage and not a gauge saying `572 MB / 1024 MB` for example, which is useful to see at a glance.

So it would really be nice to be able to define a separate query for getting the max value, shouldn't be too hard!

**Comment by veve90** [comment]
Hello, can this be done with a custom plugin? 
(asking in order to know if there is any "grafana" limitation about that or if we could do it ourselfs)

**Comment by frimik** [comment]
> To the people having to adjust every gauge when something like disk space changes, why not display a usage in percentages? So `current()/max()`
> 
> I can still see how this feature request is an improvement to that, but I thought it could help in the meantime.

Singlestat (Multistat?) successor could allow:
1. using more than one metric; A, B, C etc.
2. refering to a metrics value result in min, max etc. or even in the display of stat values itself.

With such things in place, the rest could be made logical and simple, right?

Today, we end up sprinkling tons of *repeat* graphs for the same variable just to get the numbers clearly displayed.

Perhaps this is the thing where this needs to be done? -- https://github.com/grafana/grafana/issues/10358

Although, what I'm after is mainly a way to get a dynamic max value ... ie, simpler than a complete multistat panel.

**Comment by rwesterbur** [comment]
+1

**Comment by sola91** [comment]
+1

**Comment by Felipemirand0** [comment]
+1 I really need this!, it will so functional and usable for values that can change at any time. How is the staus of this feature? I'm really excited about that.

**Comment by yves-bourgeois** [comment]
+1

**Comment by alex2grad** [comment]
+1

**Comment by Zaazik** [comment]
+1

**Comment by jamesddube** [comment]
2019 +1

**Comment by ch-hristov** [comment]
Is anyone working on this?

**Comment by marefr** [comment]
@ch-hristov Doesn't look like that. Please note though that the gauge functionality in singlestat is being migrated to a new panel called Gauge and is written in React. If you want to work with this it should be implemented for the React Gauge panel.

**Comment by peawet08** [comment]
+1 Please

**Comment by baur** [comment]
any updates? this would be useful for Plan/Fact metrics

**Comment by zhujintao** [comment]
+1

**Comment by weq** [comment]
Could we stop with the +1? Just vote any other post. All others who subscribe to this issue get a stupid mail because you want to be "cool". Please stop.

**Comment by Theoooooo** [comment]
> 
> 
> Could we stop with the +1? Just vote any other post. All others who subscribe to this issue get a stupid mail because you want to be "cool". Please stop.

You can mute the thread ...

**Comment by weq** [comment]
> You can mute the thread ...
That is moronic. We subscribed to this thread for a reason, not to see people think they are cool by doing +1 like this is that dead thing called google+. We subscribed because we wish to see the progress on the issue, this is about Grafana. Let's keep it about grafana and it's features/issues whatever.

**Comment by Theoooooo** [comment]
> 
> 
> > You can mute the thread ...
> 
> That is moronic. We subscribed to this thread for a reason, not to see people think they are cool by doing +1 like this is that dead thing called google+. We subscribed because we wish to see the progress on the issue, this is about Grafana. Let's keep it about grafana and it's features/issues whatever.

Fair enough

**Comment by dguendisch** [comment]
I was mainly looking into the bar gauge because I wanted horizontal bar charts, but needed dynamic/auto max values.
Found now that https://grafana.com/grafana/plugins/michaeldmoore-multistat-panel provides all of this already and works great for me.

**Comment by mboehm21** [comment]
+1

**Comment by SaigyoujiYuyuko233** [comment]
2020 +1

**Comment by veloxidSchweiz** [comment]
Hi,
I am very interested on that.
is anyone working on this at the moment?

**Comment by dominik-ba** [comment]
This issue is open for nearly four years and it has so many likes but it does not get implemented? Why? I did not see any maintainer comment here? Or did I miss it?
The percentage workaround is only that, a workaround.
If you have examples like mentioned here with memory (RAM) or storage or (in my case) nodes in a cluster, percentage can give you an idea, but it is psychological different for human brains if you see percentages or a total value.

If I see our cluster has a usage of 70 percent or I see there are 70 Nodes in usage but 30 are idling, that makes a total difference in its statement and also helps to provide actionable information.
If I only have the percentage I need to do the math on my own or in another panel. But then I have two panels to get a good idea about the status instead of simply one **really** helpful panel.

**Comment by AndrewSav** [comment]
>This issue is open for nearly four years and it has so many likes but it does not get implemented? Why?

I'd love this to be implemented, but to answer the question above would be - because no one implemented it. People were busy, had another priorities, or simply did not know how to code. So no one submitted a PR and no one was able to put the efforts required. That's most likely why.

**Comment by ryantxu** [comment]
FYI.. this (at least in some form) will be coming in 7.0 as we have a more general property override infrastructure that lets you use template variables (and metadata from the query response)

**Comment by leppeles** [comment]
This feature is more than 4 years old, so I don't think anyone will do it now, if it hadn't been done in 4 years. A possible workaround I implemented is with the Pie chart (this is the closest-looking to the gauge) with selecting two values (let's say we're displaying used RAM / total RAM):
- select used RAM
- select (total RAM - used RAM) - this gives the free RAM
Picking pie chart for the job, it gives you a full circle with the used + free RAM as the slices.

**Comment by hb0nes** [comment]
> FYI.. this (at least in some form) will be coming in 7.0 as we have a more general property override infrastructure that lets you use template variables (and metadata from the query response)

We have 7.0.3 now and this is still an issue. I simply can't imagine how people are using charts without being able to set the max value, it is a super big letdown for me.

**Comment by jdbarnes-isi** [comment]
> This feature is more than 4 years old, so I don't think anyone will do it now, if it hadn't been done in 4 years. A possible workaround I implemented is with the Pie chart (this is the closest-looking to the gauge) with selecting two values (let's say we're displaying used RAM / total RAM):
> 
>     * select used RAM
> 
>     * select (total RAM - used RAM) - this gives the free RAM
>       Picking pie chart for the job, it gives you a full circle with the used + free RAM as the slices.

@leppeles  have you figured out how to do multiple hosts/instances or a host group in a single panel?

**Comment by leppeles** [comment]
> > This feature is more than 4 years old, so I don't think anyone will do it now, if it hadn't been done in 4 years. A possible workaround I implemented is with the Pie chart (this is the closest-looking to the gauge) with selecting two values (let's say we're displaying used RAM / total RAM):
> > ```
> > * select used RAM
> > 
> > * select (total RAM - used RAM) - this gives the free RAM
> >   Picking pie chart for the job, it gives you a full circle with the used + free RAM as the slices.
> > ```
> 
> @leppeles have you figured out how to do multiple hosts/instances or a host group in a single panel?

Nope, in my case it was not needed.

**Comment by torkelo** [comment]
So to understand the use case more, how is it a query variable that you want to use? what data source? or custom variables with hardcoded values? Are these variables visible or hidden? 

Could a query that returns a table with columns for min & max work? (if we could map that to be used for min & max for the value field)

**Comment by peawet08** [comment]
> So to understand the use case more, how is it a query variable that you want to use? what data source? or custom variables with hardcoded values? Are these variables visible or hidden?
> 
> Could a query that returns a table with columns for min & max work? (if we could map that to be used for min & max for the value field)

I don't think it needs to be a new type of variable, in my instance I just want to be able to use existing variable functionality within gauges/plugins to set Min/Max values (I'm sure there are other instances). 
My use case is that I monitor temperature values but the min/max values change depending on what product is in the ovens. We would retrieve these min/max values from the database and store in two separate variables to use in a gauge or on a graph.  At the minute we display these values another series on a graph because we can't display it as a gauge.

Not sure how this would be implemented if the variable contains a table value but I'm sure some cleaver person could think of the logic

Thanks

**Comment by ryantxu** [comment]
I *think* this is currently possible if you use field overrides with strings in the values -- however I think the UI only supports entering numbers.  Worth messing with that option and then evaluating how/if we can have the override UI let you put in a variable

**Comment by genebean** [comment]
> So to understand the use case more, how is it a query variable that you want to use? what data source? or custom variables with hardcoded values? Are these variables visible or hidden?
> 
> Could a query that returns a table with columns for min & max work? (if we could map that to be used for min & max for the value field)

We have tools that are part of our CI platform that expose max values as one of their prometheus metrics. I want to be able to query for the current value and the max allowed from prometheus, use the max to set the upper bound of the gauge, and then display the current value on the gauge.

**Comment by bygui86** [comment]
@genebean good example!

In my case, our whole infrastructure is running on Kubernetes and I would like to set a Gauge with 3 values:
- the _requested_ amount of memory (set in yaml manifests but available as a metric)
- the _current_ amount of memory in use (available as a metric)
- the _limit_ amount of memory (set in yaml manifests but available as a metric)

This is just one out some similar examples.

**Comment by torkelo** [comment]
What makes me hesitant to implement this feature is that template variable on the dashboard level are mostly designed to allow dynamic filtering and selecting of data, filters that are applied to most commonly many panels on the dashboard. 

Having a variable for min & max makes little sense to me, does the user select it? If not I think dashboard level variables are a poor fit. 

> We have tools that are part of our CI platform that expose max values as one of their prometheus metrics. I want to be able to query for the current value and the max allowed from prometheus, use the max to set the upper bound of the gauge, and then display the current value on the gauge.

So the min & max are in a prometheus metric, would it then not make more sense to add this metric query to the gauge panel itself and then somehow be able to use that as the min & max for the main query?

**Comment by bygui86** [comment]
> So the min & max are in a prometheus metric, would it then not make more sense to add this metric query to the gauge panel itself and then somehow be able to use that as the min & max for the main query?

Yeah that would be really good!
Adding the min and max provided as prometheus metric in the gauge panel itself, being able to use it for the main query and to set thresholds and limits

**Comment by shalstea** [comment]
In my opinion using template variables is not the best fit as well.  What I would like is to be able to either put in a specific value (which is what is supported today), or specify a query / data source.  This would have to be separate options for the min and max.  For example I might be fine with a static min value of zero but want to run a query to determine the max.

**Comment by genebean** [comment]
> So the min & max are in a prometheus metric, would it then not make more sense to add this metric query to the gauge panel itself and then somehow be able to use that as the min & max for the main query?

Being able to use a query to define the min and another to define the max would be ideal.

**Comment by veloxidSchweiz** [comment]
Thank you for looking at this again.
I am using influxdb as a source and in the query I use a variable to filter. 
The min and max values are also accessible via an influxdb query, using the variable as a filter.
Using querys, which allow variables would be ideal

**Comment by dominik-ba** [comment]
> 
> 
> So to understand the use case more, how is it a query variable that you want to use? what data source? or custom variables with hardcoded values? Are these variables visible or hidden?
> 
> Could a query that returns a table with columns for min & max work? (if we could map that to be used for min & max for the value field)

My use case would be that in memory/cpu/storage/amount of nodes in a cluster the percentage helps getting a feeling but actual numbers are easier to deviate real action items.
Tentatively one can say the bigger the numbers are the higher the percentage can get until you are in need to add more resources into a cluster. Therefore having the real max reflected would be awesome.

**Comment by veloxidSchweiz** [comment]
@torkelo , I am wondering if the use case is now more clear or if you would need any additional information. Is there something how i can support?  This would be a really helpful feature for my team.

**Comment by jkmnt** [comment]
Would be nice to have this feature too. Just an implementation idea, maybe the Grafana team cosider it someday: new kind of transform. 

Get min/max as reduced value in query B, set as min/max to query A. There are already transforms to change metric attributes (displayname), and cross-query transforms (join series ?) 
Maybe even some generic 'Query B=> Query A attribute' transform for the numeric/only attributes ?

**Comment by RouNNdeL** [comment]
@torkelo it makes it easier to use a max value in multiple graphs and allows us to change it only in one place, instead of having to go into every graph and changing it manually.

**Comment by gjuchault** [comment]
I might have found a workaround:

```sql
select
  count(1) as "value",
  1000 as "max"
from "..."
```

Then in `Value options > Fields`, only select `value`. Grafana seems to take the max in its `auto` calculation

**Comment by torkelo** [comment]
So in v8.1 we are adding two new transforms that will allow you to extract config like min, max, unit and thresholds from a normal query:

[Config from query results](https://grafana.com/docs/grafana/next/panels/transformations/config-from-query/)
[Rows to fields](https://grafana.com/docs/grafana/next/panels/transformations/rows-to-fields/) 

We are soon switching to Github discussions for feature requests, will create an issue there next week to collect feedback on these new transforms

**Comment by pkolyvas** [comment]
Discussion & feedback thread here: https://github.com/grafana/grafana/discussions/38029
