### ISSUE TITLE
[Question/Bug] Can't render multiple InfluxDB queries

### ISSUE THREAD

**Issue by alexzorin** [grafana/grafana#4930]
```
# rpm -q grafana
grafana-2.6.0-1.x86_64
# rpm -q influxdb
influxdb-0.12.1-1.x86_64
# cat /etc/redhat-release 
CentOS release 6.7 (Final)
```

Been struggling this for a few weeks, have given up finding a problem in the server environment.

When I create an InfluxDB panel, I cannot render multiple queries/metrics/series at a time.

e.g. I can add two queries as indicated here, but only one series is rendered (all other settings are default).
![1](http://i.imgur.com/HMhToMD.png)

If I move the "b" query to the top, or "hide" the "a" query, the "b" query (only) will be rendered.

The request being made via AJAX is:

```
https://grafana/api/datasources/proxy/4/query?epoch=ms&q=select+upstream_time+AS+%22b%22+from+logstash;%0Aselect+upstream_time+AS+%22a%22+from+logstash;
```

Both queries are present there (though not sure if correctly). The resultset only contains the data for one query or the other, never both.

Out of ideas :(.

**Comment by torkelo** [comment]
This is due to a change in InfluxDB.  You need grafana 3.0, please search before opening new issue,  this has been reported like 5-6 times before :)

**Comment by alexzorin** [comment]
No problem, did search many times but looked like I didn't hit the right terms. Can you please ref the issue #s for me? Thanks for the quick response.

**Comment by torkelo** [comment]
I am om mobile right now,  but search for multiple and Influxdb
