### ISSUE TITLE
Unable to switch grafana data source with one click

### ISSUE THREAD

**Issue by qiu-peng20** [grafana/grafana#49307]
**What happened**:
I want to switch grafana data source，
plan to switch from prometheus to vm
![image](https://user-images.githubusercontent.com/55682965/169484195-dddf97a5-9174-492a-b908-1f1a1e9fcc4b.png)
![image](https://user-images.githubusercontent.com/55682965/169484241-e05b3ee8-4a42-400f-9e7b-25e03f35f7ef.png)
![image](https://user-images.githubusercontent.com/55682965/169484313-03cd9a5e-7ee6-489c-8e89-01378585a8b3.png)

But I see my grafana view datasource doesn't change
![image](https://user-images.githubusercontent.com/55682965/169484643-9abf2a74-15ac-45d6-a438-7a461b134005.png)
![image](https://user-images.githubusercontent.com/55682965/169484743-bcf98630-06d7-4872-b530-f00b271a24f0.png)

**What you expected to happen**:
What I expect is to directly replace the data source of all views，No need to adjust one by one

**Environment**:
- Grafana version:
![image](https://user-images.githubusercontent.com/55682965/169485452-586711e0-23b4-4055-9459-74f7fc1ad433.png)

- Data source type & version:
- OS Grafana is installed on: Docker
- User OS & Browser:  Linux

**Comment by zuchka** [comment]
I don't think that changing the `default` datasource will propogate changes through Grafana. In other words, I don't think you can't expect to change the default datasource and expect every existing panel and dashboard using `default` to change along with it 🙏
