### ISSUE TITLE
[Bug] Space in value into templating variable

### ISSUE THREAD

**Issue by matthgyver** [grafana/grafana#4931]
Hi,

In last beta with ES source, I created a variable with query like this : 
`{"find": "terms", "query": "source:serverX AND adminCN:Foo Bar"}`
"Foo Bar" contain space so I've tried this (add \") : 
`{"find": "terms", "query": "source:serverX AND adminCN:\"Foo Bar\""}`
And this : 
`{"find": "terms", "query": "source:serverX AND adminCN:'Foo Bar'"}`

But nothing works. I get this error message : 
`Template variables could not be initialized: a.responses[0].aggregations is undefined`

Thank you

**Comment by xpinkyx** [comment]
Hey,
I get the same error message whenever I change something on running variables (e.g. change the datasource and change it back or change the query) in a dashboard, imported from an older grafana-version (I'm not sure, which one exactly, it was a 3.0.0-beta-Version). After that changes, the template variable doesn't work anymore. Also, when I add a new template variable in that dashboard and copy-paste a working query, I get the error message. The only query that works (Although I get the error message here, too) is, when I look for fields with strings.
When I create a new dashboard, templating works fine. I'm using 3.0.1Stable

**Comment by matthgyver** [comment]
Hy,
In stable version 3.0.4, it's work fine with this syntax : 
`{"find": "terms", "query": "source:serverX AND adminCN:\"Foo Bar\""}`
I close this bug.
