### ISSUE TITLE
Colors inconsistency in repeated Bar Chart graphs

### ISSUE THREAD

**Issue by picolu** [grafana/grafana#49314]
**What happened**:
Noted a color inconsistency in repeated Bar Chart graphs, see attached screenshot.
The bars showed in 2022/04 should be green because their values are 100%. Please compare it with the others (2022/01, 2022/02, ...). 
The graphs come from a Bar Chart repeated for 2022/01 ... 2022/08.
The color Scheme is "Red-Yellow-Green (by value)"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: Postgresql 
- OS Grafana is installed on: Ubuntu 16.04.7 LTS
- User OS & Browser: Windows 10 / Firefox 100.0.1 
- Grafana plugins:
- Others:
![Clipboard01](https://user-images.githubusercontent.com/44204889/169502171-23b86197-4cbc-4256-851b-c712cdace86b.png)

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

maybe using testdata db and mocking up some data? Otherwise:

can you please follow [these steps](https://cln.sh/PTgRFb) to share your raw unformatted data? That way, the community can try and mock up your problem :+1: 

https://cln.sh/PTgRFb

**Comment by zuchka** [comment]
also are you using bar chart or bar gauge?

**Comment by picolu** [comment]
Thanks for you reply.
I am using bar chart and repetead it by year/month. 
Hoping it can help, I edited the graph and fixed the query to 2022/1 ("anno/mese" in talian mean "year/month"), the colors in this case are OK.  Than I did the same thing for 2022/4 and this time I got wrong colors.
Attached you will find:
1. exported csv data from DB for month = 4 
2. screenshot for month = 1 where colors are OK
3. screenshot for month = 4 where colors are NOT ok

Please let me know if you need anything else.


![Screenshot 2022-05-23 at 10-27-14 Report - Grafana](https://user-images.githubusercontent.com/44204889/169778053-54d77f86-e3f4-4e50-b4e9-12a4a6837749.png)

![Screenshot 2022-05-23 at 10-23-15 Report - Grafana](https://user-images.githubusercontent.com/44204889/169778100-9b1f00f5-7da7-4aa3-9db5-35bef3878ff5.png)

[data-2022-05-23 08 22 03.csv](https://github.com/grafana/grafana/files/8752810/data-2022-05-23.08.22.03.csv)

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by picolu** [comment]
Could ypu please tell me how I can import a csv file into a table DB on play.grafana.org ?

**Comment by ashharrison90** [comment]
@picolu sorry for the late reply, you should be able to use the `gdev-testdata` datasource and paste the data into the `csv content` scenario

**Comment by picolu** [comment]
I did it (thanks for you tip), but unfortunately this did not reproduced the problem. The bars are green as they should be (see sceenshot)
I think the problem is in some way related to the repetition of the graph. If you look at my first post, the graph was repeated several times, one for each month, and only the 4th has wrong colors. All the others looks ok.

Thanks,
Pino

![Screenshot 2022-07-25 at 16-49-41 Grafana Play Home - Grafana](https://user-images.githubusercontent.com/44204889/180806059-c9c90e39-517b-428e-a97f-ac8a9b36bb9c.png)
.

**Comment by zuchka** [comment]
@picolu are you still encountering this issue?

**Comment by picolu** [comment]
Yes. Grafana 9.2.4Screenshot shows the same graph repeated 12 times. The #4 and #8 have wrong colors.

Best regards,Pino



    Il martedì 8 novembre 2022 23:39:53 CET, matt abrams ***@***.***> ha scritto:  
 
 


@picolu are you still encountering this issue?

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by leeoniya** [comment]
we landed a few [fixes for barchart coloring](https://github.com/grafana/grafana/pull/58285) in v9.3.0-beta1, so it would help to test with latest beta build: https://grafana.com/grafana/download/9.3.0-beta1?edition=oss

@picolu you can also use the "Get Help" menu to export and attache a debug dashboard from the panel with the query data so we can try to reproduce this locally: https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#panel-help-menu

if you're running an earlier version, without Get Help option, you can instead attach the output of `Panel > Inspect > Panel JSON > DataFrame JSON`

![image](https://user-images.githubusercontent.com/43234/199793806-9d1560a0-acb8-438a-862d-9ef2cb7c75e7.png)

**Comment by picolu** [comment]
Attached you can find debug dashboard files. I hope this help.How can I install beta build to test the fix ? I run Grafana on Ubuntu server.

Best regards,Pino



    Il lunedì 21 novembre 2022 20:29:00 CET, Leon Sorokin ***@***.***> ha scritto:  
 
 


we landed a few fixes for barchart coloring in v9.3.0-beta1, so it would help to test with latest beta build: https://grafana.com/grafana/download/9.3.0-beta1?edition=oss

@picolu you can also use the "Get Help" menu to export and attache a debug dashboard from the panel with the query data so we can try to reproduce this locally: https://grafana.com/docs/grafana/latest/whatsnew/whats-new-in-v9-2/#panel-help-menu

if you're running an earlier version, without Get Help option, you can instead attach the output of Panel > Inspect > Panel JSON > DataFrame JSON



—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you were mentioned.Message ID: ***@***.***>
  
{
  "panels": [
    {
      "id": 2,
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "type": "barchart",
      "title": "Reproduced with embedded data",
      "repeat": "mese",
      "repeatDirection": "h",
      "maxPerRow": 4,
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "lineWidth": 1,
            "fillOpacity": 80,
            "gradientMode": "none",
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "axisSoftMin": 0
          },
          "color": {
            "mode": "continuous-RdYlGr",
            "fixedColor": "blue"
          },
          "mappings": [],
          "thresholds": {
            "mode": "percentage",
            "steps": [
              {
                "color": "dark-red",
                "value": null
              },
              {
                "color": "dark-orange",
                "value": 25
              },
              {
                "color": "dark-yellow",
                "value": 50
              },
              {
                "color": "dark-green",
                "value": 75
              }
            ]
          },
          "max": 100,
          "unit": "percent"
        },
        "overrides": []
      },
      "options": {
        "orientation": "auto",
        "xTickLabelRotation": 90,
        "xTickLabelSpacing": 0,
        "showValue": "always",
        "stacking": "none",
        "groupWidth": 0.7,
        "barWidth": 0.9,
        "barRadius": 0.1,
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": false,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        },
        "colorByField": "perc"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "executedQueryString": "SELECT\n  SUBSTRING(v_stazioni.id_stazione,0,5) AS metric,\n  perc\nFROM v_stazioni\nLEFT JOIN v_conta_rinex2d ON v_stazioni.id_stazione = stazione\nAND anno = 2022 \nAND mese = '1'\nWHERE v_stazioni.descrizione_stato in ('Operativa ENI','Operativa STOGIT')\nAND SUBSTRING(v_stazioni.id_stazione,0,5) in ('AGOB','AGR1','ANGA','ARMI','BREN','CALI','CF34','COR2','COST','DARB','FALC','FIUN','GELA','GRUM','PCTA','RAGU','RUBI','SABB','SMAR','TREV')\nORDER BY 1\n"
                },
                "fields": [
                  {
                    "name": "metric",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "perc",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "AGOB",
                    "AGR1",
                    "ANGA",
                    "ARMI",
                    "BREN",
                    "CALI",
                    "CF34",
                    "COR2",
                    "COST",
                    "DARB",
                    "FALC",
                    "FIUN",
                    "GELA",
                    "GRUM",
                    "PCTA",
                    "RAGU",
                    "RUBI",
                    "SABB",
                    "SMAR",
                    "TREV"
                  ],
                  [
                    100,
                    100,
                    null,
                    100,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    100,
                    100,
                    58.06451612903226,
                    90.32258064516128,
                    100,
                    null,
                    null,
                    93.54838709677419,
                    100
                  ]
                ]
              }
            }
          ]
        }
      ],
      "scopedVars": {
        "mese": {
          "selected": true,
          "text": "1",
          "value": "1"
        }
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >barchart @ 9.2.4 (64017e8ca6)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[postgres]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 20 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.2.4 (64017e8ca6) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 2,\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 6,\n    \"x\": 0,\n    \"y\": 1\n  },\n  \"type\": \"barchart\",\n  \"title\": \"% mensile files ricevuti - ${anno}  / ${mese}\",\n  \"repeat\": \"mese\",\n  \"repeatDirection\": \"h\",\n  \"maxPerRow\": 4,\n  \"datasource\": {\n    \"type\": \"postgres\",\n    \"uid\": \"000000001\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"lineWidth\": 1,\n        \"fillOpacity\": 80,\n        \"gradientMode\": \"none\",\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"axisSoftMin\": 0\n      },\n      \"color\": {\n        \"mode\": \"continuous-RdYlGr\",\n        \"fixedColor\": \"blue\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"percentage\",\n        \"steps\": [\n          {\n            \"color\": \"dark-red\",\n            \"value\": null\n          },\n          {\n            \"color\": \"dark-orange\",\n            \"value\": 25\n          },\n          {\n            \"color\": \"dark-yellow\",\n            \"value\": 50\n          },\n          {\n            \"color\": \"dark-green\",\n            \"value\": 75\n          }\n        ]\n      },\n      \"max\": 100,\n      \"unit\": \"percent\"\n    },\n    \"overrides\": []\n  },\n  \"options\": {\n    \"orientation\": \"auto\",\n    \"xTickLabelRotation\": 90,\n    \"xTickLabelSpacing\": 0,\n    \"showValue\": \"always\",\n    \"stacking\": \"none\",\n    \"groupWidth\": 0.7,\n    \"barWidth\": 0.9,\n    \"barRadius\": 0.1,\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": false,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    },\n    \"colorByField\": \"perc\"\n  },\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"postgres\",\n        \"uid\": \"000000001\"\n      },\n      \"format\": \"table\",\n      \"group\": [],\n      \"metricColumn\": \"stazione\",\n      \"rawQuery\": true,\n      \"rawSql\": \"SELECT\\n  SUBSTRING(v_stazioni.id_stazione,0,5) AS metric,\\n  perc\\nFROM v_stazioni\\nLEFT JOIN v_conta_rinex2d ON v_stazioni.id_stazione = stazione\\nAND anno = ${anno} \\nAND mese = ${mese}\\nWHERE v_stazioni.descrizione_stato in (${stato_stazione})\\nAND SUBSTRING(v_stazioni.id_stazione,0,5) in (${stazione})\\nORDER BY 1\\n\",\n      \"refId\": \"A\",\n      \"select\": [\n        [\n          {\n            \"params\": [\n              \"perc\"\n            ],\n            \"type\": \"column\"\n          }\n        ]\n      ],\n      \"table\": \"v_metrics_files_count\",\n      \"timeColumn\": \"anno\",\n      \"timeColumnType\": \"float8\",\n      \"where\": [\n        {\n          \"name\": \"$__unixEpochFilter\",\n          \"params\": [],\n          \"type\": \"macro\"\n        }\n      ]\n    }\n  ],\n  \"scopedVars\": {\n    \"mese\": {\n      \"selected\": true,\n      \"text\": \"1\",\n      \"value\": \"1\"\n    }\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: % mensile files ricevuti - ${anno}  / ${mese} // 2022-11-22 09:51:45",
  "tags": [
    "debug",
    "debug-barchart"
  ],
  "time": {
    "from": "2022-11-22T03:51:45.400Z",
    "to": "2022-11-22T09:51:45.401Z"
  }
}
| Key | Value |
|--|--|
| Panel | barchart @ 9.2.4 (64017e8ca6) |
| Grafana | 9.2.4 (64017e8ca6) // Open Source |
<details><summary>Panel debug snapshot dashboard</summary>

```json
{
  "panels": [
    {
      "id": 2,
      "gridPos": {
        "h": 13,
        "w": 15,
        "x": 0,
        "y": 0
      },
      "type": "barchart",
      "title": "Reproduced with embedded data",
      "repeat": "mese",
      "repeatDirection": "h",
      "maxPerRow": 4,
      "datasource": {
        "type": "grafana",
        "uid": "grafana"
      },
      "fieldConfig": {
        "defaults": {
          "custom": {
            "lineWidth": 1,
            "fillOpacity": 80,
            "gradientMode": "none",
            "axisPlacement": "auto",
            "axisLabel": "",
            "axisColorMode": "text",
            "scaleDistribution": {
              "type": "linear"
            },
            "axisCenteredZero": false,
            "hideFrom": {
              "tooltip": false,
              "viz": false,
              "legend": false
            },
            "axisSoftMin": 0
          },
          "color": {
            "mode": "continuous-RdYlGr",
            "fixedColor": "blue"
          },
          "mappings": [],
          "thresholds": {
            "mode": "percentage",
            "steps": [
              {
                "color": "dark-red",
                "value": null
              },
              {
                "color": "dark-orange",
                "value": 25
              },
              {
                "color": "dark-yellow",
                "value": 50
              },
              {
                "color": "dark-green",
                "value": 75
              }
            ]
          },
          "max": 100,
          "unit": "percent"
        },
        "overrides": []
      },
      "options": {
        "orientation": "auto",
        "xTickLabelRotation": 90,
        "xTickLabelSpacing": 0,
        "showValue": "always",
        "stacking": "none",
        "groupWidth": 0.7,
        "barWidth": 0.9,
        "barRadius": 0.1,
        "tooltip": {
          "mode": "single",
          "sort": "none"
        },
        "legend": {
          "showLegend": false,
          "displayMode": "list",
          "placement": "bottom",
          "calcs": []
        },
        "colorByField": "perc"
      },
      "targets": [
        {
          "refId": "A",
          "datasource": {
            "type": "grafana",
            "uid": "grafana"
          },
          "queryType": "snapshot",
          "snapshot": [
            {
              "schema": {
                "refId": "A",
                "meta": {
                  "executedQueryString": "SELECT\n  SUBSTRING(v_stazioni.id_stazione,0,5) AS metric,\n  perc\nFROM v_stazioni\nLEFT JOIN v_conta_rinex2d ON v_stazioni.id_stazione = stazione\nAND anno = 2022 \nAND mese = '1'\nWHERE v_stazioni.descrizione_stato in ('Operativa ENI','Operativa STOGIT')\nAND SUBSTRING(v_stazioni.id_stazione,0,5) in ('AGOB','AGR1','ANGA','ARMI','BREN','CALI','CF34','COR2','COST','DARB','FALC','FIUN','GELA','GRUM','PCTA','RAGU','RUBI','SABB','SMAR','TREV')\nORDER BY 1\n"
                },
                "fields": [
                  {
                    "name": "metric",
                    "type": "string",
                    "typeInfo": {
                      "frame": "string",
                      "nullable": true
                    },
                    "config": {}
                  },
                  {
                    "name": "perc",
                    "type": "number",
                    "typeInfo": {
                      "frame": "float64",
                      "nullable": true
                    },
                    "config": {}
                  }
                ]
              },
              "data": {
                "values": [
                  [
                    "AGOB",
                    "AGR1",
                    "ANGA",
                    "ARMI",
                    "BREN",
                    "CALI",
                    "CF34",
                    "COR2",
                    "COST",
                    "DARB",
                    "FALC",
                    "FIUN",
                    "GELA",
                    "GRUM",
                    "PCTA",
                    "RAGU",
                    "RUBI",
                    "SABB",
                    "SMAR",
                    "TREV"
                  ],
                  [
                    100,
                    100,
                    null,
                    100,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    null,
                    100,
                    100,
                    58.06451612903226,
                    90.32258064516128,
                    100,
                    null,
                    null,
                    93.54838709677419,
                    100
                  ]
                ]
              }
            }
          ]
        }
      ],
      "scopedVars": {
        "mese": {
          "selected": true,
          "text": "1",
          "value": "1"
        }
      }
    },
    {
      "gridPos": {
        "h": 7,
        "w": 9,
        "x": 15,
        "y": 0
      },
      "id": 5,
      "options": {
        "content": "<table width=\"100%\">\n    <tr>\n      <th width=\"2%\">Panel</th>\n      <td >barchart @ 9.2.4 (64017e8ca6)</td>\n    </tr>\n    <tr>\n      <th>Queries</th>\n      <td>A[postgres]</td>\n    </tr>\n    \n    <tr><th>Data</th><td> 1 frames, 2 fields, 20 rows </td></tr>\n    \n    <tr>\n      <th>Grafana</th>\n      <td>9.2.4 (64017e8ca6) // Open Source</td>\n    </tr>\n  </table>",
        "mode": "html"
      },
      "title": "Debug info",
      "type": "text"
    },
    {
      "id": 6,
      "title": "Original Panel JSON",
      "type": "text",
      "gridPos": {
        "h": 13,
        "w": 9,
        "x": 15,
        "y": 7
      },
      "options": {
        "content": "{\n  \"id\": 2,\n  \"gridPos\": {\n    \"h\": 8,\n    \"w\": 6,\n    \"x\": 0,\n    \"y\": 1\n  },\n  \"type\": \"barchart\",\n  \"title\": \"% mensile files ricevuti - ${anno}  / ${mese}\",\n  \"repeat\": \"mese\",\n  \"repeatDirection\": \"h\",\n  \"maxPerRow\": 4,\n  \"datasource\": {\n    \"type\": \"postgres\",\n    \"uid\": \"000000001\"\n  },\n  \"fieldConfig\": {\n    \"defaults\": {\n      \"custom\": {\n        \"lineWidth\": 1,\n        \"fillOpacity\": 80,\n        \"gradientMode\": \"none\",\n        \"axisPlacement\": \"auto\",\n        \"axisLabel\": \"\",\n        \"axisColorMode\": \"text\",\n        \"scaleDistribution\": {\n          \"type\": \"linear\"\n        },\n        \"axisCenteredZero\": false,\n        \"hideFrom\": {\n          \"tooltip\": false,\n          \"viz\": false,\n          \"legend\": false\n        },\n        \"axisSoftMin\": 0\n      },\n      \"color\": {\n        \"mode\": \"continuous-RdYlGr\",\n        \"fixedColor\": \"blue\"\n      },\n      \"mappings\": [],\n      \"thresholds\": {\n        \"mode\": \"percentage\",\n        \"steps\": [\n          {\n            \"color\": \"dark-red\",\n            \"value\": null\n          },\n          {\n            \"color\": \"dark-orange\",\n            \"value\": 25\n          },\n          {\n            \"color\": \"dark-yellow\",\n            \"value\": 50\n          },\n          {\n            \"color\": \"dark-green\",\n            \"value\": 75\n          }\n        ]\n      },\n      \"max\": 100,\n      \"unit\": \"percent\"\n    },\n    \"overrides\": []\n  },\n  \"options\": {\n    \"orientation\": \"auto\",\n    \"xTickLabelRotation\": 90,\n    \"xTickLabelSpacing\": 0,\n    \"showValue\": \"always\",\n    \"stacking\": \"none\",\n    \"groupWidth\": 0.7,\n    \"barWidth\": 0.9,\n    \"barRadius\": 0.1,\n    \"tooltip\": {\n      \"mode\": \"single\",\n      \"sort\": \"none\"\n    },\n    \"legend\": {\n      \"showLegend\": false,\n      \"displayMode\": \"list\",\n      \"placement\": \"bottom\",\n      \"calcs\": []\n    },\n    \"colorByField\": \"perc\"\n  },\n  \"targets\": [\n    {\n      \"datasource\": {\n        \"type\": \"postgres\",\n        \"uid\": \"000000001\"\n      },\n      \"format\": \"table\",\n      \"group\": [],\n      \"metricColumn\": \"stazione\",\n      \"rawQuery\": true,\n      \"rawSql\": \"SELECT\\n  SUBSTRING(v_stazioni.id_stazione,0,5) AS metric,\\n  perc\\nFROM v_stazioni\\nLEFT JOIN v_conta_rinex2d ON v_stazioni.id_stazione = stazione\\nAND anno = ${anno} \\nAND mese = ${mese}\\nWHERE v_stazioni.descrizione_stato in (${stato_stazione})\\nAND SUBSTRING(v_stazioni.id_stazione,0,5) in (${stazione})\\nORDER BY 1\\n\",\n      \"refId\": \"A\",\n      \"select\": [\n        [\n          {\n            \"params\": [\n              \"perc\"\n            ],\n            \"type\": \"column\"\n          }\n        ]\n      ],\n      \"table\": \"v_metrics_files_count\",\n      \"timeColumn\": \"anno\",\n      \"timeColumnType\": \"float8\",\n      \"where\": [\n        {\n          \"name\": \"$__unixEpochFilter\",\n          \"params\": [],\n          \"type\": \"macro\"\n        }\n      ]\n    }\n  ],\n  \"scopedVars\": {\n    \"mese\": {\n      \"selected\": true,\n      \"text\": \"1\",\n      \"value\": \"1\"\n    }\n  }\n}",
        "mode": "code",
        "code": {
          "language": "json",
          "showLineNumbers": true,
          "showMiniMap": true
        }
      }
    },
    {
      "id": 3,
      "title": "Data from panel above",
      "type": "table",
      "datasource": {
        "type": "datasource",
        "uid": "-- Dashboard --"
      },
      "gridPos": {
        "h": 7,
        "w": 15,
        "x": 0,
        "y": 13
      },
      "options": {
        "showTypeIcons": true
      },
      "targets": [
        {
          "datasource": {
            "type": "datasource",
            "uid": "-- Dashboard --"
          },
          "panelId": 2,
          "withTransforms": true,
          "refId": "A"
        }
      ]
    }
  ],
  "schemaVersion": 37,
  "title": "Debug: % mensile files ricevuti - ${anno}  / ${mese} // 2022-11-22 09:51:45",
  "tags": [
    "debug",
    "debug-barchart"
  ],
  "time": {
    "from": "2022-11-22T03:51:45.400Z",
    "to": "2022-11-22T09:51:45.401Z"
  }
}
```
</details>

**Comment by leeoniya** [comment]
thanks, unfortunately this only contains a single (correct) month of data. can you make a snapshot for the month that is incorrect?

<details><summary>dataframe.json</summary>

```json
[
  {
    "schema": {
      "refId": "A",
      "meta": {
        "executedQueryString": "SELECT\n  SUBSTRING(v_stazioni.id_stazione,0,5) AS metric,\n  perc\nFROM v_stazioni\nLEFT JOIN v_conta_rinex2d ON v_stazioni.id_stazione = stazione\nAND anno = 2022 \nAND mese = '1'\nWHERE v_stazioni.descrizione_stato in ('Operativa ENI','Operativa STOGIT')\nAND SUBSTRING(v_stazioni.id_stazione,0,5) in ('AGOB','AGR1','ANGA','ARMI','BREN','CALI','CF34','COR2','COST','DARB','FALC','FIUN','GELA','GRUM','PCTA','RAGU','RUBI','SABB','SMAR','TREV')\nORDER BY 1\n"
      },
      "fields": [
        {
          "config": {},
          "name": "metric",
          "type": "string",
          "typeInfo": {
            "frame": "string",
            "nullable": true
          }
        },
        {
          "config": {},
          "name": "perc",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          }
        }
      ]
    },
    "data": {
      "values": [
        [
          "AGOB",
          "AGR1",
          "ANGA",
          "ARMI",
          "BREN",
          "CALI",
          "CF34",
          "COR2",
          "COST",
          "DARB",
          "FALC",
          "FIUN",
          "GELA",
          "GRUM",
          "PCTA",
          "RAGU",
          "RUBI",
          "SABB",
          "SMAR",
          "TREV"
        ],
        [
          100,
          100,
          null,
          100,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          100,
          100,
          58.06451612903226,
          90.32258064516128,
          100,
          null,
          null,
          93.54838709677419,
          100
        ]
      ]
    }
  }
]
```
</details>

![image](https://user-images.githubusercontent.com/43234/203340191-8a7525db-ac04-4bd1-ae86-bd03b6697628.png)

> The color Scheme is "Red-Yellow-Green (by value)"

your options do not look correct to me.

![image](https://user-images.githubusercontent.com/43234/203346112-8023a5a8-3b35-4307-8243-b88ff061cd68.png)

you have thresholds with colors defined, so your scheme should be `From thresholds (by value)`:

![image](https://user-images.githubusercontent.com/43234/203346514-9e71c505-3b32-4c19-919f-a0f21e42a880.png)

> How can I install beta build to test the fix ? I run Grafana on Ubuntu server.

please try by downloading with latest beta and new settings. https://grafana.com/grafana/download/9.3.0-beta1?edition=oss. the instructions are on that page.

**Comment by picolu** [comment]
Dear Leon,
I wil try the beta version as soon as possibile, I would like to not install it on a production machine.
About the problem, let me try to clarify better what I noted.If I generate the graph for each month one by one, all the graphs are correct. The color inconsistency appears only if I use the "repeat" option in the panel setupand particularly this inconsistency appears, in my case, on the 4th and 8th repeating graphs (the last of each row ?).This is what I got when I use the automatic "Repeat" option.


This is Panel option I use to setup the automatic "Repeat" option.





    Il martedì 22 novembre 2022 16:00:45 CET, Leon Sorokin ***@***.***> ha scritto:  
 
 


thanks, unfortunately this only contains a single (correct) month of data. can you make a snapshot for the month that is incorrect?
 dataframe.json [
  {
    "schema": {
      "refId": "A",
      "meta": {
        "executedQueryString": "SELECT\n  SUBSTRING(v_stazioni.id_stazione,0,5) AS metric,\n  perc\nFROM v_stazioni\nLEFT JOIN v_conta_rinex2d ON v_stazioni.id_stazione = stazione\nAND anno = 2022 \nAND mese = '1'\nWHERE v_stazioni.descrizione_stato in ('Operativa ENI','Operativa STOGIT')\nAND SUBSTRING(v_stazioni.id_stazione,0,5) in ('AGOB','AGR1','ANGA','ARMI','BREN','CALI','CF34','COR2','COST','DARB','FALC','FIUN','GELA','GRUM','PCTA','RAGU','RUBI','SABB','SMAR','TREV')\nORDER BY 1\n"
      },
      "fields": [
        {
          "config": {},
          "name": "metric",
          "type": "string",
          "typeInfo": {
            "frame": "string",
            "nullable": true
          }
        },
        {
          "config": {},
          "name": "perc",
          "type": "number",
          "typeInfo": {
            "frame": "float64",
            "nullable": true
          }
        }
      ]
    },
    "data": {
      "values": [
        [
          "AGOB",
          "AGR1",
          "ANGA",
          "ARMI",
          "BREN",
          "CALI",
          "CF34",
          "COR2",
          "COST",
          "DARB",
          "FALC",
          "FIUN",
          "GELA",
          "GRUM",
          "PCTA",
          "RAGU",
          "RUBI",
          "SABB",
          "SMAR",
          "TREV"
        ],
        [
          100,
          100,
          null,
          100,
          null,
          null,
          null,
          null,
          null,
          null,
          null,
          100,
          100,
          58.06451612903226,
          90.32258064516128,
          100,
          null,
          null,
          93.54838709677419,
          100
        ]
      ]
    }
  }
] 



The color Scheme is "Red-Yellow-Green (by value)"


your options do not look correct to me.



you have thresholds with colors defined, so your scheme should be From thresholds (by value):




How can I install beta build to test the fix ? I run Grafana on Ubuntu server.


please try by downloading with latest beta and new settings. https://grafana.com/grafana/download/9.3.0-beta1?edition=oss. the instructions are on that page.

**Comment by picolu** [comment]
Dear Leon,

I was wrong, the problem was not related to the "Repeat" option.
Today I discovered that I had to set the Min value in in Standard Options section in order to have the right colors.
If I leave the Min value empty (i.e. automatic) the colors were not the ones I espected.

I think you can close this issue.
Thank you very much for your support.


Best regards,
Pino

**Comment by leeoniya** [comment]
ok, thanks for the update 👍
