### ISSUE TITLE
Percent in Graphs

### ISSUE THREAD

**Issue by ert56** [grafana/grafana#4932]
hello @torkelo ,

Is there any way in grafana to calculate the % value for some metrics.

Like i have one metric abc, this is having one tag with 3 values, a, b, c,
a = 20
b = 30
c = 50

sum of all these is 100, so a is 20% of total, b is 30% of total and c is 50% of total. How can we show this is grafana.

**Comment by torkelo** [comment]
It depends on your time series store. Graphite has functions like asPercent that can calculate percentages based on two other series (or against a query that returns a total). 

There is also the stacked render mode in grafana that has a stacked option, but this render mode is a bit buggy.
