### ISSUE TITLE
Azure AD Oath GroupMember.Read.All requirement not backwards compatible

### ISSUE THREAD

**Issue by lukerogers** [grafana/grafana#49339]
**What happened**:
The original issue was #43356 to fetch user groups when groups > 200. The PR #43470 was implemented that required access to the GroupMember.Read.All API. If this access isn't granted, authentication is broken.

**What you expected to happen**:
I would expect it to function as it did previously and if the implementation needs to fetch groups, access to the API should be granted to account for it.

**How to reproduce it (as minimally and precisely as possible)**:
Use Azure AD for authentication, only grant User.Read to the app registration as was previously required.

**Comment by sunker** [comment]
Is this something you can look into @grafana/grafana-authnz-team ?
