### ISSUE TITLE
Unified Alerting API spec is broken and doesn't match real responses from the server.

### ISSUE THREAD

**Issue by artemgavrilov** [grafana/grafana#49341]
**What happened**:
I tried new Grafana alerting API and faced multiple problems with API spec:

1. Spec is broken out of box. I used `grafana/pkg/services/ngalert/api/tooling> make serve` command to start local Swagger Editor and it showed a lot of semantic errors in spec file. For example spec uses such reference `#/responses/Accepted`, but this reference can't be resolved within spec itself. So it's impossible to generate API client from this spec.
![Screen Shot 2022-05-20 at 13 25 55](https://user-images.githubusercontent.com/21174514/169578345-d2f8da32-182e-4761-b51b-6f10dee4d4db.png)

2. Some endpoints returns HTTP status codes other that defined in spec. For example spec says that [/api/ruler/grafana/api/v1/rules](https://github.com/grafana/grafana/blob/3d5d8c785bf37d5fbb0e832001f54ecedc0a2476/pkg/services/ngalert/api/tooling/post.json#L5079-L5111) returns `202` code, but in fact it returns `200`.
![Screen Shot 2022-05-20 at 19 07 28](https://user-images.githubusercontent.com/21174514/169578280-6dca2ddf-6f00-4b0b-9dee-69d22bb6e233.png)

3. Spec says that [Duration](https://github.com/grafana/grafana/blob/main/pkg/services/ngalert/api/tooling/post.json#L519-L522) type is `int64`, but in fact API returns string with golang formatted duration (example: `10s`)
![Screen Shot 2022-05-20 at 19 11 24](https://user-images.githubusercontent.com/21174514/169578896-45f5faf8-d53c-4806-bc3e-1b6574495546.png)

**What you expected to happen**:
I expected that API specification is valid and  I will be able to generate API client from it.

**How to reproduce it (as minimally and precisely as possible)**:
Just run `make serve` in `pkg/services/ngalert/api/tooling` directory, open `localhost` in browser and you will see a lot of errors.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.3.5 and greater. All described problems exists also in latest revision in main branch ([3d5d8c7](https://github.com/grafana/grafana/commit/3d5d8c785bf37d5fbb0e832001f54ecedc0a2476))
- Data source type & version: -
- OS Grafana is installed on: -
- User OS & Browser: -
- Grafana plugins: -
- Others: -

**Comment by gotjosh** [comment]
This API is private, experimental and not for public consumption. If you're trying to provision rules programmatically, the provisioning API is now ready and will be launched as part of Grafana 9. 

You should be able to find it in the documentation in the next few weeks.

**Comment by artemgavrilov** [comment]
Great, will wait for Grafana 9 then. Thanks!
