### ISSUE TITLE
Button "Upload JSON file" does not work (for importing dashboards)

### ISSUE THREAD

**Issue by edin008** [grafana/grafana#49359]
**What happened**: Button for importing dashboards does not work. We're on version 8.5.3, it did not work as well on version 8.5.2 however the button works on version 8.5.1.

![image](https://user-images.githubusercontent.com/66313770/169662043-99e7f955-3958-44b8-9885-136d8fd1e8f4.png)

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: /
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows 10, Chrome 101
- Grafana plugins: /
- Others: /

**Comment by Vollbrecht** [comment]
thank you, but this was already reported and the fix was was merged in main here https://github.com/grafana/grafana/pull/48766

**Comment by ritaCanavarro** [comment]
Hello, we are currently facing a similar issue to this one. When opening the plus tab we do not have the option to Import a Dashboard anymore. Is this also going to be fixed on Grafana 9 or should I open a specific bug for it?

![Screenshot from 2022-05-26 16-00-02](https://user-images.githubusercontent.com/98762287/170515696-56d43bcd-dc8f-42e4-bdc8-73f3aad38043.png)

Thanks in advance

**Comment by zuchka** [comment]
this should be fixed in 8.5.4 with https://github.com/grafana/grafana/pull/48766
