### ISSUE TITLE
Alerting: should alerting image tokens have an expiration time?

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#49366]
The ngAlert image store sets a 1 minute expiration time on image references when they're stored. It's not clear to me why this is needed, since the size of image rows are small, and if the images are cleaned off of disk while the row remains, the worst that will happen is a "Not Found"

If we need to delete rows, another cleanup approach could be to base any cleanup code on the temporary data retention setting in config.

**Comment by grobinson-grafana** [comment]
The purpose of expiration was to avoid having orphaned images in the database where the image is no longer on disk or on a bucket. In future it would be nice if Grafana could also delete the image from the remote store when the image is expired too as this will avoid the customer incurring increasing costs as the number of images in the store increases over time.

**Comment by joeblubaugh** [comment]
Why is the default expiration time 1 minute?

**Comment by grobinson-grafana** [comment]
That was just to have some expiration time while writing the code, there is a TODO on the original pull request that recommends changing it from 1 minute https://github.com/grafana/grafana/pull/48449#discussion_r876830715.

**Comment by alexweav** [comment]
Related epic: https://github.com/grafana/grafana/issues/47275

**Comment by alexweav** [comment]
Yes it seems it should have an expiration time, but should potentially be increased from the current setting.

We should base it on the existing temporary data retention setting. This seems like a straightforward enough change for consistency.
