### ISSUE TITLE
Width of Bars in bar graph are varying between dashboard & shared dashboard (link sharing)

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#4936]
influxdb-0.11.0-1
grafana-3.0.0-pre1

Bar widths are completely different between a dashboard & a shared dashboard.

Dashboard that i see 
<img width="433" alt="screen shot 2016-05-06 at 9 49 40 am" src="https://cloud.githubusercontent.com/assets/406777/15079863/e139305e-136f-11e6-8e36-481aab6520a5.png">

When i click Share dashboard i see this

<img width="439" alt="screen shot 2016-05-06 at 9 49 32 am" src="https://cloud.githubusercontent.com/assets/406777/15079864/e1393e32-136f-11e6-8eef-ea0b88984c50.png">

I was hoping to see exact same graph visually and data wise.

**Comment by deepujain** [comment]
Dashboard has time selected as Last 15 days, shared dashboard has a date range (April 21 to May 6) again 15 days. In shared dashboard if I modify to Last 15 days, the bars become thinner and match both.

**Comment by deepujain** [comment]
<img width="410" alt="screen shot 2016-05-06 at 9 53 13 am" src="https://cloud.githubusercontent.com/assets/406777/15079945/5fc11b58-1370-11e6-862e-dba15957a668.png">

**Comment by torkelo** [comment]
What's you query? Any template variables?

**Comment by deepujain** [comment]
<img width="1362" alt="screen shot 2016-05-06 at 2 26 30 pm" src="https://cloud.githubusercontent.com/assets/406777/15086569/9246a13a-1396-11e6-9d81-7fd5cb582cf9.png">

**Comment by torkelo** [comment]
since you use fill(null) and fill(0), what's your null point mode (in display tab), is it connected or null as zero? Try changing this to null as zero or change to fill(0)
