### ISSUE TITLE
TypeError: propTypes is undefined

### ISSUE THREAD

**Issue by AlexanderBrese** [grafana/grafana#49369]
Hi
I am using vite+vu3+veaury+grafana/ui and i get this error in build mode. Dev mode works fine.
Steps to reproduce:
[vue3-vite-grafana.zip](https://github.com/grafana/grafana/files/8750339/vue3-vite-grafana.zip)

npm i && npm run build && npm run preview

**Comment by zuchka** [comment]
it sounds like you are using the grafana component library for some external project? The library wasn't really designed for that...
