### ISSUE TITLE
auth.azuread: improve error mesaging when Setting `role_attribute_strict = true`

### ISSUE THREAD

**Issue by OmarBazaraa** [grafana/grafana#49367]
**What happened**:
Grafana throws "Internal Server Error" when a user tries to sign in using Azure AD and he/she has no roles assigned. That happens when `role_attribute_strict ` is set to `true`.

![image](https://user-images.githubusercontent.com/6713329/169704901-d148ea6b-2e58-4508-af96-fd07c54d14b9.png)

**What you expected to happen**:
I expected Grafana to show a reasonable message that the user is not authorized to log in.

**How to reproduce it (as minimally and precisely as possible)**:
1. Under `auth.azuread`, set `role_attribute_strict` to `true`.
2. Try to sign into Grafana with Microsoft using a user with no assigned roles (i.e., unauthorized user).
3. You'll get the above server error screen and those logs:
```txt
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-05-22T16:31:04.53+0000 lvl=eror msg="login.OAuthLogin(get info from azuread)" error="user does not have a valid role"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=0 uname= t=2022-05-22T16:31:04.53+0000 lvl=eror msg="Request Completed" method=GET path=/login/azuread status=500 remote_addr=156.213.21.227 time_ms=755 duration=755.665083ms size=641 referer=https://login.microsoftonline.com/ traceID=00000000000000000000000000000000
```

I tried it only using Azure AD authentication but maybe the same applies using other OAuth methods.

**Anything else we need to know?**:
I enabled `role_attribute_strict` so that I can avoid giving the default "Viewer" access to anyone. I want all users to have no access at all by default.

**Environment**:
- Grafana version: 8.5.2
- OS Grafana is installed on: Linux Ubuntu
- User OS & Browser: Edge Chromium

**Comment by Jguer** [comment]
Extra context, can be improved when taking this issue: https://github.com/grafana/grafana/issues/26824
