### ISSUE TITLE
provide some form of "null as zero" in time-series-panel

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#49380]
(the issue was raised in https://github.com/grafana/grafana/issues/48880 , i created a new separate issue to make it easier to follow the situation)

@leeoniya  wrote:
> @gabor
> 
> we're currently working through how to implement `null-as-zero`. it's a bit trickier that it seems, since it needs to also affect calculations in fieldReducers (done pre-panel) and not just the rendering in the panels.
> 
> > so, even if we would insert the nulls in Loki like we did before, it would not help, sorry.
> 
> yeah, we do this nulls-at-missing-intervals insertion in the panels now, but moving this up out of the panels into the datasource js, or transformers, or `fieldOverrides.ts` could result in `null` log lines shown in tables. this means we'd have to filter them out in other places, i think.
> 
> we have two PoCs, but also considering adding a Value-mapping transformer.
> 
> #49118 #49124
> 
> feel free to ping me on slack if you have some ideas :)

**Comment by gabor** [comment]
to use it, find the `Standard options > No value` option, and set it to `0`.

**Comment by JordanZimmitti** [comment]
@gabor How do I get this to work with Loki for time-series? When I set the no value to zero nothing happends

**Comment by gabor** [comment]
@JordanZimmitti hmm.. first thing, are you running a new-enough Grafana version? i tested it with Grafana9.0.2, and it worked:

i have a query that produces a single data-point:
<img width="726" alt="before" src="https://user-images.githubusercontent.com/51989/178423120-b3ab56d9-85e2-4a28-bf51-07eaa103e3b4.png">

and now i set no_value=0:
<img width="1023" alt="after" src="https://user-images.githubusercontent.com/51989/178423219-e6e2b97c-7290-49f5-9da7-14f745e7f466.png">

could you try the same?

**Comment by JordanZimmitti** [comment]
@gabor I am on 9.0.0 I'll try upgrading to 9.0.2 and try again, will get back to you with my update, thanks!
