### ISSUE TITLE
How to reload scripted dashboard after selecting different node from templated filter

### ISSUE THREAD

**Issue by zdenekpizl** [grafana/grafana#494]
Hallo,

 let's have following scripted dashboard's features:
- script gets set of nodes from external source and create a filter to be used  as a template
- script gets info about node's metrics from external source
- there is not the same set of metrics for different nodes necessarily 
- for each node's metric there is a graph is standalone row generated

Question:
How to achieve full reload of dashboard after selecting another node from filter. That means to re-create all rows according to newly selected node?

Is there any hook or event I can connect to and call my event-handler or similar technique how to achieve this?

Thank you, best regards .zp.

**Comment by mtanda** [comment]
May be related to https://github.com/grafana/grafana/issues/1229

**Comment by torkelo** [comment]
closing this in favor of https://github.com/grafana/grafana/issues/1229
