### ISSUE TITLE
[Feature Request] Add quick templates drop-down to left of new metrics rows

### ISSUE THREAD

**Issue by jshook** [grafana/grafana#4940]
For the purposes of quickly filling out detailed metrics lines, it would be nice to have a dropdown of macros that could be managed in a pre-populated list. Optionally, one could click "save to templates" on the metrics editor context menu.

When a user has this enabled, they could simply select one of the quick templates on the left and have the metric definition pre-filled with the initial values.

This would help greatly when dashboards have many metrics with the same path structure. Using the drill-downs over and over to navigate the same 8 levels is a time waster. Even template variables don't make this streamlined enough. If I could just have a few templates to quickly populate new metrics lines from, it would save lots of time and effort.

**Comment by jshook** [comment]
Thinking about how this could be designed...

Next to the +Query button could be a a drop-down with the names given to all the quick templates. This puts the templates immediately where they are needed without cluttering up the metrics line view too much.

**Comment by torkelo** [comment]
yes, this was actually something that I also thought about, like 2 years ago. would be cool

**Comment by itsmylife** [comment]
We have "Kick start your query" button doing same kind of job 

![Image](https://github.com/grafana/grafana/assets/820946/f5eb2fb0-a3a7-45bc-9b38-bbb3b26ac219)
