### ISSUE TITLE
Convert `public/app/plugins/datasource/grafana-azure-monitor-datasource/components/deprecated/components/InsightsConfig.test.tsx` to RTL

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#49406]
Convert Enzyme test to RTL in Azure Monitor `InsightsConfig`

Requirement for Grafana to move to React 18 (see https://github.com/grafana/grafana/issues/48253)

**Comment by andresmgot** [comment]
actually, this file does not exist anymore
