### ISSUE TITLE
Convert public/app/plugins/datasource/cloudwatch/components/ConfigEditor.test.tsx to RTL

### ISSUE THREAD

**Issue by yaelleC** [grafana/grafana#49402]
Convert Enzyme test to RTL in CloudWatch ConfigEditor

Requirement for Grafana to move to React 18 (see #48253)

**Comment by aangelisc** [comment]
Started this in mob on [this](https://github.com/grafana/grafana/tree/mob/main-config-editor-rtl) branch. Would be prudent to have [this](https://github.com/grafana/grafana/pull/49286/files#diff-3079bb2753f6b2bb7b2caceb001a58783bf13716d112ce7c67e41e53fba8068a) merged in first as some of the mocks would be useful generalised when moving tests from enzyme to RTL.

**Comment by ashharrison90** [comment]
looks like this has been done: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/components/ConfigEditor.test.tsx 🙌
