### ISSUE TITLE
Loki: Metrics query with unwrap is not parsed correctly 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#49401]
1. Specify this text query `sum(sum_over_time({job="grafana"} |= "error" | logfmt | unwrap duration | __error__="" [$__interval]))`
2. Move to builder mode 
3. Get warning that the query cannot be presented in the builder mode, and if you continue anyway you see no unwrap operation

**Comment by ivanahuckova** [comment]
The cause of the issue is incorrect parsing. I have created PR in lezer-logql repo to fix this https://github.com/grafana/lezer-logql/pull/7
