### ISSUE TITLE
Cann't find the `grafana` binary after running docker/production/build.sh

### ISSUE THREAD

**Issue by hzy001** [grafana/grafana#4942]
- Grafana: 3.0.0_beta6
- OS: Ubuntu 14.04 LTS    

I builded grafana docker image with **docker/production/build.sh**. However, after building, I couldn't find `grafana` binary which is used in **docker/production/Dockerfile** as an entrypoint. I found I only had `grafana-server` and `grafana-cli` binaries after building. Is there something wrong?

**Comment by torkelo** [comment]
I should remove that one, it's not the current one. 

The official docker container (https://hub.docker.com/r/grafana/grafana/) is build from this repo
https://github.com/grafana/grafana-docker
