### ISSUE TITLE
[Bug] Editing datasources broken on master

### ISSUE THREAD

**Issue by CamJN** [grafana/grafana#4945]
* What grafana version are you using? built from master 04ef25b6ff4d631bab5d9eb7aa7617356d322419
* What datasource are you using? any
* What OS are you running grafana on? OS X

With proxying enabled the save & test button makes a PUT request to /api/datasources/1, and the backend never replies.

**Comment by torkelo** [comment]
this is related to a go 1.6 issue we have yet to find the cause for, 
https://github.com/grafana/grafana/issues/4367

downgrade go 1.5
