### ISSUE TITLE
Datasource Selection is broken in recent releases

### ISSUE THREAD

**Issue by gaurkuma** [grafana/grafana#49456]
**What happened**:
I have different prometheus Data sources, all hooked up to a single Grafana instance. This is to give all the users a uniform experience when looking at different panels. In grafana, I have created a template variable (of type datasource) to select between the different datasources.

**What you expected to happen**:
I can select the different data sources from the dropdown but i was expecting the panels will show data for the data source selected. Instead, the panels were blank where i know for sure there should be some data. Also, it was working (8.4.1-1 works fine) and recently got broken (8.5.2-1 and 8.5.3.-1 doesnt work).

I tried to see whats going wrong and here is what i think is the problem.

Let's assume we have datasource variable called **server** that has the values X, Y, Z. This is at the dashboard level. Then we have a datasource selection at the panel level and a datasource shown in each query as well. 
  
In the panel, lets say we have one query A and on the side to it, it shows $server as on the datasource on the panel is selected to be $server. At this point, things work fine. When i select a different data source my query o/p changes, the query A still shows $server on the side. But if i select a specific data source on the panel, then the datasource shown on the query A also changes which is right but now if i set back the datasource to $server, the query A data source is shown the one which is selected in the $server variable. If i select the a different data source on the dashboard, it doesnt refresh the query datasource and the only way to refresh is to select the $server variable  in the panel datasource even though it is already set to $server variable.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3-1
- Data source type & version: Prometheus
- OS Grafana is installed on: Centos
- User OS & Browser: MacOS and Chrome
- Grafana plugins:
- Others:

**Comment by Hsinin** [comment]
+1

**Comment by torkelo** [comment]
I think this caused by an update to updateQueries function in PR https://github.com/grafana/grafana/pull/47435

**Comment by torkelo** [comment]
have a fix incoming

**Comment by torkelo** [comment]
A bad temporary workaround is to add a new query, new queries will have the correct ds variable as the data source, then manually copy or redo the queries. Using the duplicate will preserve the wrong datasource.uid prop. Or you can edit the dashboard JSON and update the queries that should have a datasource uid value that is a variable expression (copy the datasource object prop from the panel level and replace it on the query level)

**Comment by gaurkuma** [comment]
Thanks @torkelo for taking care of it. As a workaround, I went back to the previous version of Grafana. WIll wait for 8.5.4

**Comment by torkelo** [comment]
@gaurkuma just FYI the fix is not retro active, you will have to select a another data source, and then select the variable data source again (in the panel query tab)

**Comment by sbhushankr** [comment]
Hi,

Where we can put this jq query

Regards,
Shashi

**Comment by clementnuss** [comment]
you can use it when you export your dashboard as a json file and save it as e.g. `dashboard.json`. then in that same directory you can just run the command above

**Comment by pierreyvesv** [comment]
> for those of you who need to edit a large numbers of dashboards, you can use the following `jq` snippet to make your life easier ;)
> 
> ```shell
> jq '.panels[].datasource = {uid: "${datasource}"}' dashboard.json > corrected_dashboard.json
> ```
Hi,
datasource is set in panel for each "targets" with a static uid and should be replaced with `uid: "${datasource}"`
