### ISSUE TITLE
Grafana short URL throws a 404 for some random links

### ISSUE THREAD

**Issue by faisal-khalique** [grafana/grafana#49469]
**What happened**:
- When creating a short URL and clicking the *COPY* button on the overlay window, the URL does not gets copied. This issue is persistence and happens almost everytime
- On visiting the short URL (created) for a dashboard, Grafana throws a 404. For example for the link https://my.domain.com/grafana/goto/EBI_cRw7z?orgId=1 we get below page

![Screenshot 2022-05-24 at 09 37 47](https://user-images.githubusercontent.com/34666636/169978927-60ff2edf-1d71-46b2-92f6-ccdcd132a688.png)

Enable trace for logs does not give any meaningful information as to why this is a 404
```bash
t=2022-05-24T10:05:13+0200 lvl=info msg="Request Completed" logger=context userId=0 orgId=0 uname= method=GET path=/goto/EBI_cRw7z status=302 remote_addr=aa.bb.cc.dd time_ms=1 size=37 referer=
```
Only thing I can note here is the field `userId` is set to `0` whereas the user which I used to login has `userId=224`. We have provisioned grafana to use LDAP authentication and no dashboard cam be accessed without authentication. So, I would expected to see my userId(224 and not 0) in the logs. This does happen when I view a working short URL.

For example, when visiting the URL at `https://my.domain.com/grafana/goto/BcyVdju7k?orgId=1`, in the logs I can see
```bash
t=2022-05-24T10:13:14+0200 lvl=info msg="Request Completed" logger=context userId=224 orgId=1 uname="John, Doe" method=GET path=/goto/BcyVdju7k status=302 remote_addr=aa.bb.cc.dd time_ms=56 size=142 referer=
```

After checking the database, the short URL is not available in DB. But we definitely created one and made no changes to DB. So, perhaps the issue is when saving the short URL?
```sql
SELECT * FROM SHORT_URL WHERE UID = 'BcyVdju7k'; -- returns one entry
SELECT * FROM SHORT_URL WHERE UID = 'EBI_cRw7z'; -- returns no entry
```

**What you expected to happen**:
The link for short URL should work and take me to the actual dashboard with all the filters (time and variables) applied.

**How to reproduce it (as minimally and precisely as possible)**:
The issue happens randomly for few URLs. We continue to look for steps for reproducing this but have not found a way yet.

**Anything else we need to know?**:

**Environment**:
- Grafana version: _Grafana (OSS) v8.3.2 (afb9e8e5f3)_
- Data source type & version:
  - ElasticSearch
  - InfluxDB
  - Prometheus
- OS Grafana is installed on: _Oracle Linux Server v6.10_
- User OS & Browser: _MacOS/ Windows and Chrome/Safari/Firefox_
- Grafana plugins: _The list of installed plugins is given below. We don't suspect the issue is to do with any specific plugin._
  - Alert list
  - Annotation list
  - Azure monitor
  - Bar chart
  - Bar gauge
  - Candlestick
  - Cloudwatch
  - Dashboard list
  - Elastic Search
  - Gauge
  - Geomap
  - Getting started
  - Google cloud monitoring
  - Graph (old)
  - Graphite
  - Heatmap
  - Histogram
  - InfluxDB
  - Jaegar
  - Logs
  - Loki
  - Microsoft SQL server
  - MySQL
  - News
  - Node graph
  - OpenTSDB
  - Pie Chart
  - Plugin List
  - PostgreSQL
  - Prometheus
  - Stat
  - Stat timeline
  - Status (history)
  - Table
  - Table (old)
  - Temp
  - Testdata DB
  - Text
  - Time series
  - Welcome
  - Zipkin
- Grafana Persistence: _We use MySQL for persistence. MySQL v8.0.12 (Community edition)_

**Comment by zuchka** [comment]
this sounds like a nasty one to try and pin down / reproduce. Keep us updated if it keeps happening and if you have clear steps to reproduce? Thanks a bunch 👍

**Comment by helgeschreyer** [comment]
Hi, it appears furthermore but it's hard to create a reproducable stepbystep guide ;-)

Have you checked the first analysis of Faisal above in description regarding the userid=0 ?

thx Helge

**Comment by helgeschreyer** [comment]
please do you have any update?

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

**Comment by helgeschreyer** [comment]
thx, in this environment it seems to work, I did several tests to save the link and open it some days later correctly


But I still find in our current PROD environment this issue:
![image](https://user-images.githubusercontent.com/107844708/186369976-4b4ce508-c23e-4d3a-82ba-87866a91af88.png)

You see in the screenshot the dasboard and its configuration.
Based on this I created at the 6th of August the **short** link but this doesn't work: https://logging-dc-emea.1dc.com/grafana/goto/xgXcXRm4k?orgId=1

Today I recreate the link: https://logging-dc-emea.1dc.com:443/grafana/goto/w3JJNOZ4k?orgId=1 (which is currently working)

long link is: 
https://logging-dc-emea.1dc.com/grafana/d/yLybk5knz/counting-for-andreas?orgId=1&var-filter=server_group_env%7C%3D%7Cprod&var-filter=REQUEST_TYPE%7C%3D%7CTRANSACTION&var-filter=RESULT%7C%3D%7CFAILED&var-filter=IPG_APPROVAL_CODE%7C%3D%7CN%3A-30051%3ACommunication+Error&var-group=RESELLER&from=1659789052000&to=1659801285000

Is there any plan to update the version?

**Comment by helgeschreyer** [comment]
So do you have any information regarding updating to the new version?

**Comment by zuchka** [comment]
@helgeschreyer 

are you still having issues?

what do you mean by this?

> updating to the new version...

**Comment by helgeschreyer** [comment]
Hello
Yes indeed the issue still occur:
Example:
***@***.***
WORKING URLS at the moment:

  *   Long URL: https://logging-dc-emea.1dc.com/grafana/d/yLybk5knz/counting-for-andreas?orgId=1&from=1663827440783&to=1664256764223&var-filter=server_group_env%7C%3D%7Cprod&var-filter=REQUEST_TYPE%7C%3D%7CTRANSACTION&var-filter=KEY_CLIENT%7C%3D%7CPOKERSTARS&var-group=RESULT
  *   Short URL: https://logging-dc-emea.1dc.com:443/grafana/goto/DEpj9Av4z?orgId=1

This short URL I have saved in my documentation but this one is NOT WORKING:

  *   https://logging-dc-emea.1dc.com:443/grafana/goto/Rg-vxk4Vk?orgId=1


Regarding “updating to the new version” > This was a misunderstanding


Thanks, Helge

**Comment by zuchka** [comment]
> thx, in this environment it seems to work

if this issue is working on our sandbox, but not in your own prod environment, can you think of anything else that might be causing this?

We can't do much here until we have a reliable way to reproduce your issue. Is it maybe an issue specific to your template variables?

And have you tried upgrading from Grafana (OSS) v8.3.2 (https://github.com/grafana/grafana/commit/afb9e8e5f3c33fa59c5a1053d98d8d97815af002)?

**Comment by helgeschreyer** [comment]
Thx, Matt
You can close the ticket

Best, Helge
