### ISSUE TITLE
[Feature Request] Toggling legend on repeating panel should (optionally?) toggle legend on all repeated panels

### ISSUE THREAD

**Issue by discordianfish** [grafana/grafana#4947]
Hi,

I think it would be useful if toggling the legend on a panel which is set to repeat itself would toggle all repeated panels. I'd argue that, if you have a variant of the same graph and toggle it legend, you usually want to toggle the legend of all those graphs.

**Comment by torkelo** [comment]
it will do that if you save and reload, or after you toggled you change the template variable. But the panel repeats are only processed on load or after you change the selected value a template variable.
