### ISSUE TITLE
Semi-relative time range breaks since Grafana 8 when 'to' is before 'from'

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#49495]
**Context**:

In response to the blog post [Pro tip: How to use semi-relative time ranges in Grafana](https://grafana.com/blog/2022/02/03/pro-tip-how-to-use-semi-relative-time-ranges-in-grafana/), a user reported an issue, which I was able to reproduce.

There is a dashboard which displays metrics for "the day so far", starting at 9:30am local time. This is achieved with the following time range controls:

* **from**: `now/d+9h+30m`
* **to**: `now+30m`

**What you expected to happen**:

Before Grafana 8, when the dashboard was opened before 9:30am, the graphs would be empty. As soon as the clock hit 9:30am and the dashboard is auto-refreshed, the graphs will display the data between 9:30am and 'now'.

Here is an example:

![Screenshot 2022-05-24 09-40-12 now before start](https://user-images.githubusercontent.com/3270755/170051015-4eb510ff-fae1-4446-8554-1a24a1726c44.png)

![Screenshot 2022-05-24 09-41-26 now after start](https://user-images.githubusercontent.com/3270755/170051010-6a841408-53c0-4334-b348-c4d34f972a0b.png)

**What happened**:

Since Grafana 8, when the dashboard is opened before 9:30am, the time controls are reversed. On 2022-05-24 at 9:25am, the displayed time range is `2022-05-24 09:25:00` to `2022-05-25 09:30:00`.

![Screenshot 2022-05-24 09-25-52 before 9:30](https://user-images.githubusercontent.com/3270755/170051387-909643b6-94e5-4ac0-a147-09bec8d048db.png)

After 9:30am passes and as the dashboard auto-refreshes, the dashboard time controls remain reversed.

![Screenshot 2022-05-24 09-31-26 after 9:30](https://user-images.githubusercontent.com/3270755/170051386-8eadf4ab-39d7-4546-a121-f87601299b25.png)

Refreshing the page on the browser controls fixes the issue:

![Screenshot 2022-05-24 09-32-23 after refresh](https://user-images.githubusercontent.com/3270755/170051383-dcf4fd69-3c2a-4e58-aec4-cd87ffdab7cd.png)

**Environment**:
- Grafana version: v8.5.2
- Data source type & version: Prometheus
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox v100
- Grafana plugins:
- Others:

**Comment by JoaoSilvaGrafana** [comment]
Can confirm I can reproduce this, it is due to this piece of code when initialising the `TimeSrv`:
```
    if (range.to.isBefore(range.from)) {
      this.setTime(
        {
          from: range.raw.to,
          to: range.raw.from,
        },
        false
      );
    }
```

I generally understand the purpose of this, to prevent empty graphs, but also find it strange that we are taking this action that the user didn't really ask for. I will bring this to the team to ask for opinions today and then move it to our backlog accordingly.

**Comment by joshhunt** [comment]
We've decided we want to undo this change - if the 'To' time is before 'From', we will no longer swap them. Instead we'll just show a small discrete warning that it may not return any data.
