### ISSUE TITLE
[Bug] Self-referential template variable results in blank page

### ISSUE THREAD

**Issue by cout** [grafana/grafana#4949]
Using grafana 3.0beta7, I have a dashboard with the following contents:

        {"annotations":{"list":[]},"editable":true,"hideControls":false,"id":29,"links":[],"originalTitle":"Disk","refresh":false,"rows":[],"schemaVersion":12,"sharedCrosshair":true,"style":"dark","tags":[],"templating":{"list":[{"current":{"tags":[],"text":"All","value":["$__all"]},"datasource":"$source","hide":0,"includeAll":true,"label":"Disk","multi":true,"name":"disk","options":[{"selected":true,"text":"All","value":"$__all"},{"selected":false,"text":"disk-sda","value":"disk-sda"},{"selected":false,"text":"disk-sdb","value":"disk-sdb"}],"query":"$disk_group","refresh":1,"regex":"","type":"query"}]},"time":{"from":"2016-05-04T14:24:59.063Z","now":false,"to":"2016-05-04T14:35:11.406Z"},"timepicker":{"collapse":false,"enable":true,"notice":false,"now":false,"refresh_intervals":["5s","10s","30s","1m","5m","15m","30m","1h","2h","1d"],"status":"Stable","time_options":["1h","2h","3h","6h","8h","12h","24h","2d","7d","30d"],"type":"timepicker"},"timezone":"browser","title":"Disk","version":55}

When I try to load this dashboard, I get a blank page (no navbar or sidebar).  If I remove the $disk template variable, the dashboard loads successfully.

(I originally reached this thinking I was referencing a variable called $disk_group, forgetting that this means the value of $disk followed by the string "_group" rather than the value of the variable $disk_group).

**Comment by torkelo** [comment]
Yes recursive variables are a bad idea, you can use [[disk_group]]  as alternative interpolation syntax that will not match on the first disk word
