### ISSUE TITLE
Graphite Annotations Use Direct Mode Regardless of Datasource Setting

### ISSUE THREAD

**Issue by gurumeditator** [grafana/grafana#4950]
In Grafana 3.0 I am unable to query for Graphite annotations in Proxy mode. The annotations are queried as if the datasource is configure for direct mode. I have verified this works in Grafana 2.1.3.

grafana-3.0.0-beta71462173753.x86_64

**Comment by torkelo** [comment]
cant replicate this, with either annotation metric query or events query, both use the proxy correctly. 

![image](https://cloud.githubusercontent.com/assets/10999/15137121/d4d88f7e-1687-11e6-88a7-9269133af153.png)
