### ISSUE TITLE
datasource selector doesn't show datasource anymore

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#4952]
old grafana (2.x)
![old](https://cloud.githubusercontent.com/assets/20774/15129320/e99e659c-160e-11e6-9e65-3c3046269f4d.png)

new (git master):
![huh3](https://cloud.githubusercontent.com/assets/20774/15129324/f5b2d610-160e-11e6-8f8f-5b23a1fbb918.png)

this is annoying when you have multiple datasources and you can't tell which one it has selected.

**Comment by bergquist** [comment]
The datasource selector on the metrics page have been rebuilt and should look like this
![image](https://cloud.githubusercontent.com/assets/618863/15136993/e77c21e6-1686-11e6-8c46-d34567168ff1.png)

Have you tried cleaning public_gen/ and rebuild all front end assets?

**Comment by torkelo** [comment]
looks like your Grafana version is old or you have not properly rebuilt frontend.
