### ISSUE TITLE
SLES15 can't build grafana > 8.5.0.x due to build hanging (possible root cause)

### ISSUE THREAD

**Issue by crunchyjohn** [grafana/grafana#49527]
**What happened**:

When building grafana v8.5.3 (and also v8.5.0) on Suse Enterprise Linux 15, our builds would hang.  Note that we did not have any such issues on other operating systems that we tested against.

The issue happens when "yarn run plugins:build-bundled". is invoked.  This task seems to hang forever.
After a bit of digging, it appears that the issue occurs during this function call:

              await execa('yarn', ['build'], { cwd: `${MANAGED_PLUGINS_PATH}/${scope}/${plugin}` });

Drilling down a little further, we noticed that this issue was not present in the v8.3.7 line.  Doing a diff of impacted directories, we found that there was literally one minor change between the code in the following file:

- plugins-bundled/internal/input-datasource/src/InputDatasource.test.ts

The change was that

         expect(describeDataFrame((null as unknown) as Array<DataFrameDTO | DataFrame>)).toEqual('');

became

         expect(describeDataFrame(null as unknown as Array<DataFrameDTO | DataFrame>)).toEqual('');

Funny enough, changing that single line back makes everything build just fine.

I have traced this change to PR https://github.com/grafana/grafana/pull/43473/files, which is pretty complicated.

I'm not really a coding expert, but thought it would be worth reporting the problem.

**What you expected to happen**:

grafana builds of 8.5.x would complete on SLES15.

**How to reproduce it (as minimally and precisely as possible)**:

Just try building grafana on SLES15.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: 8.5.3 (no change)
- OS Grafana is installed on: SLES15
- User OS & Browser: SLES15 defaults
- Grafana plugins: no extras
- Others: no extras

**Comment by mastertheknife** [comment]
I'm also having the same issue, on el8 (Rocky Linux 8).
It hangs at "yarn run plugins:build-bundled"
I've found out that this is an issue with Jest, it deadlocks. This issue was fixed in jest v27, but grafana doesn't support new jest yet.

**Comment by zoltanbedi** [comment]
Hi @crunchytyler, @crunchyjohn,
Can you please try it with node 16.14 or 18?

**Comment by tolzhabayev** [comment]
@mastertheknife @crunchytyler please also try the https://github.com/grafana/grafana/commits/main branch as we have jest 28 in it for 8 days - just to confirm if it can fixed by jest update.
