### ISSUE TITLE
[Bug] Annotations and repeat panel by tag don't work together

### ISSUE THREAD

**Issue by popstas** [grafana/grafana#4953]
If I create annotations with query
```
select title,text,tags from event where $timeFilter and "host" =~ /^$host$/
```

And add panel or row with repeat by `host`,

I see events from all hosts on each panel.

I expect that 3 events was only on one panel:
![80ff5d795b](https://cloud.githubusercontent.com/assets/3027126/15130544/13b05d0c-166b-11e6-9c8a-cb976d8097ac.png)

* What grafana version are you using?
3.0beta5

* What datasource are you using?
InfluxDB 0.12

* What OS are you running grafana on?
Ubuntu 14.04

**Comment by torkelo** [comment]
Annotations are global for the whole dashboard, panel specific annotations have not been implemented yet. 

https://github.com/grafana/grafana/issues/717

**Comment by mbjelac** [comment]
@torkelo any ETA on this? How come this issue is closed?

**Comment by torkelo** [comment]
on what? panel specific annotations?

**Comment by mbjelac** [comment]
I believe @popstas wanted the same thing that I want: Display of annotation vertical lines on panels for annotations fetched with query containing template variables should respect the repeat context for the panel on which they are displayed.

In other words, a panel generated by repeat for `x=42` should display annotations from annotation query with `x=42`, regardless of how many `x` values are selected in the `x` template dropdown. So, another panel (in another row, or not) generated for `x=43` should *not* display annotations from annotation query `x=42`, but only from annotation query `x=43`.

**Comment by torkelo** [comment]
ok, well for that we need panel specific annotation queries which has not been implemented/started
