### ISSUE TITLE
Cloudwatch metric query fails when 2 queries run in same request

### ISSUE THREAD

**Issue by vbichov** [grafana/grafana#49530]
**What happened**:
Cloudwatch datasource returns an error when attempting to run 2 queries on the same dashboard or in explore mode

**What you expected to happen**:
Dashboard with requested data is returned

**How to reproduce it (as minimally and precisely as possible)**:
attempt to run multiple queries in the explore console (or on the same dashboard)

**Anything else we need to know?**:
The error
<img width="1785" alt="Screen Shot 2022-05-24 at 20 02 31" src="https://user-images.githubusercontent.com/4352719/170092544-c4672378-f34d-4ffe-a40c-1f1ffcb2f9d6.png">

when those queries executed in parallel panels (split view) - they work together

**Environment**:
- Grafana version: v8.5.3
- Data source type & version: Coudwatch
- OS Grafana is installed on: debian with apt
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by vbichov** [comment]
| Query results from the inspect drawer (data tab & query inspector)
No Data
| Panel settings can be extracted in the panel inspect drawer JSON tab
`{
  "state": "Error",
  "series": [],
  "request": {
    "app": "explore",
    "dashboardId": 0,
    "timezone": "utc",
    "startTime": 1655111768796,
    "interval": "2s",
    "intervalMs": 2000,
    "panelId": "Q-47c7ed06-e40b-4149-9650-aa081cf5de55-0Q-6beaf1fc-a11c-40bd-9c03-bf1e95aed45b-1",
    "targets": [
      {
        "queryMode": "Metrics",
        "namespace": "",
        "metricName": "",
        "expression": "",
        "dimensions": {},
        "region": "us-east-1",
        "id": "",
        "alias": "",
        "statistic": "Average",
        "period": "",
        "metricQueryType": 1,
        "metricEditorMode": 1,
        "sqlExpression": "SELECT AVG(GroupInServiceInstances) FROM \"AWS/AutoScaling\"",
        "refId": "A",
        "key": "Q-47c7ed06-e40b-4149-9650-aa081cf5de55-0",
        "matchExact": true,
        "sql": {
          "select": {
            "type": "function",
            "name": "AVG"
          }
        },
        "datasource": {
          "type": "cloudwatch",
          "uid": "000000041"
        }
      },
      {
        "queryMode": "Metrics",
        "namespace": "",
        "metricName": "",
        "expression": "SELECT AVG(GroupMaxSize) FROM \"AWS/AutoScaling\"",
        "dimensions": {},
        "region": "default",
        "id": "",
        "alias": "",
        "statistic": "Average",
        "period": "",
        "metricQueryType": 0,
        "metricEditorMode": 1,
        "sqlExpression": "",
        "refId": "B",
        "key": "Q-6beaf1fc-a11c-40bd-9c03-bf1e95aed45b-1",
        "matchExact": true,
        "datasource": {
          "type": "cloudwatch",
          "uid": "000000041"
        }
      }
    ],
    "range": {
      "from": "2022-06-13T08:16:08.781Z",
      "to": "2022-06-13T09:16:08.781Z",
      "raw": {
        "from": "now-1h",
        "to": "now"
      }
    },
    "requestId": "explore_left",
    "rangeRaw": {
      "from": "now-1h",
      "to": "now"
    },
    "scopedVars": {
      "__interval": {
        "text": "2s",
        "value": "2s"
      },
      "__interval_ms": {
        "text": 2000,
        "value": 2000
      }
    },
    "maxDataPoints": 1774,
    "liveStreaming": false
  },
  "timeRange": {
    "from": "2022-06-13T08:16:08.781Z",
    "to": "2022-06-13T09:16:08.781Z",
    "raw": {
      "from": "now-1h",
      "to": "now"
    }
  },
  "error": {
    "status": 400,
    "statusText": "Bad Request",
    "data": {
      "results": {
        "": {
          "error": "metric request error: \"ValidationError: Maximum number of queries (1) exceeded\\n\\tstatus code: 400, request id: 522191bd-6fde-462c-b681-8178bf128c29\""
        }
      }
    },
    "config": {
      "method": "POST",
      "url": "api/ds/query",
      "data": {
        "from": "1655108168781",
        "to": "1655111768781",
        "queries": [
          {
            "intervalMs": 2000,
            "maxDataPoints": 1774,
            "queryMode": "Metrics",
            "namespace": "",
            "metricName": "",
            "expression": "",
            "dimensions": {},
            "region": "us-east-1",
            "id": "",
            "alias": "",
            "statistic": "Average",
            "period": "",
            "metricQueryType": 1,
            "metricEditorMode": 1,
            "sqlExpression": "SELECT AVG(GroupInServiceInstances) FROM \"AWS/AutoScaling\"",
            "refId": "A",
            "key": "Q-47c7ed06-e40b-4149-9650-aa081cf5de55-0",
            "matchExact": true,
            "sql": {
              "select": {
                "type": "function",
                "name": "AVG"
              }
            },
            "datasource": {
              "type": "cloudwatch",
              "uid": "000000041"
            },
            "type": "timeSeriesQuery"
          },
          {
            "intervalMs": 2000,
            "maxDataPoints": 1774,
            "queryMode": "Metrics",
            "namespace": "",
            "metricName": "",
            "expression": "SELECT AVG(GroupMaxSize) FROM \"AWS/AutoScaling\"",
            "dimensions": {},
            "region": "us-east-1",
            "id": "",
            "alias": "",
            "statistic": "Average",
            "period": "",
            "metricQueryType": 0,
            "metricEditorMode": 1,
            "sqlExpression": "",
            "refId": "B",
            "key": "Q-6beaf1fc-a11c-40bd-9c03-bf1e95aed45b-1",
            "matchExact": true,
            "datasource": {
              "type": "cloudwatch",
              "uid": "000000041"
            },
            "type": "timeSeriesQuery"
          }
        ]
      },
      "hideFromInspector": false
    },
    "message": "metric request error: \"ValidationError: Maximum number of queries (1) exceeded\\n\\tstatus code: 400, request id: 522191bd-6fde-462c-b681-8178bf128c29\""
  },
  "annotations": [],
  "timings": {
    "dataProcessingTime": 0
  },
  "graphFrames": [],
  "tableFrames": [],
  "logsFrames": [],
  "traceFrames": [],
  "nodeGraphFrames": [],
  "graphResult": null,
  "tableResult": null,
  "logsResult": null
}`

**Comment by kevinwcyu** [comment]
Hi @vbichov, the CW datasource uses the GetMetricData API for metric queries, which limits the number of queries to 1 per API call https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/cloudwatch-metrics-insights-limits.html. The recommended way to have multiple queries is to use separate panels for each query. So I believe this is the expected behaviour.

**Comment by iwysiu** [comment]
This should be fixed in https://github.com/grafana/grafana/issues/74563
