### ISSUE TITLE
Legend Sorting sorts by string value, not numerical value.

### ISSUE THREAD

**Issue by mermino** [grafana/grafana#4954]
[Bug]

Grafana version: v3.0.0-beta7 (2016-05-02)
Datasource: InfluxDB 0.10
OS running Grafana:  Ubuntu 12.04

Hello,

It looks like when sorting values in the legend the values are being sorted by string value, not the numerical value.

![screen shot 2016-05-09 at 16 35 18](https://cloud.githubusercontent.com/assets/6807784/15131458/ef167d34-1604-11e6-8680-0ffbf3cf9ef7.png)

I've verified that values in Influx are being saved as number values, not string values.

Thanks

**Comment by torkelo** [comment]
The sorting looks correct to me.

**Comment by mermino** [comment]
The screenshot I provide shows the value of $733.72 in between $80.23 and $7.56.  $733.72 should appear at the top of the list above $99.10.

**Comment by torkelo** [comment]
sorry, missed that. Must be caused by the dollar sign. If you remove the unit does it still sort incorrectly?

**Comment by mermino** [comment]
Changing the Left Y Unit does not fix the sort.  Using "none" shows the same issue

**Comment by mermino** [comment]
<img width="62" alt="screen shot 2016-05-10 at 12 39 17" src="https://cloud.githubusercontent.com/assets/6807784/15159976/46c7d9ae-16ac-11e6-8b5b-c93a0d2018ed.png">

**Comment by mermino** [comment]
@torkelo - Is there a way to sort the legend by the measurement/label?

**Comment by mermino** [comment]
@torkelo - I upgraded my InfluxDB instance from 0.10 to 0.12 and it looks like it resolved this issue.  Not sure if you want to continue with resolving this issue for InfluxDB 0.10 implementations. Just wanted to let you know this is no longer an issue for me.

**Comment by torkelo** [comment]
Ok great
