### ISSUE TITLE
[Question] Debugging XORM query

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#4955]
* What grafana version are you using? - Master Branch
* What OS are you running grafana on? - Mac OS

This is a development question, I am trying to implement the "restore from history" feature.

I have a function in *pkg/services/sqlstore/dashboard.go" which has the following lines:
```
func GetHistoricalVersions(query *m.GetDashboardHistoryQuery) error {
  var rawSql = `SELECT dashboard_version from dashboard_history WHERE dashboard_id=?`

  query.Result = make([]*int64, 0)
  sess := x.Sql(rawSql, query.Id)
  err := sess.Find(&query.Result)

  log.Info("%v", query.Result)

  return err
}

type GetDashboardHistoryQuery struct {
  Id int64
  Result []*int64
}
```
The log output from the above function is an empty query:
```
[]
```
This is the screenshot of my dashboard_history table:
Data:
![screen shot 2016-05-09 at 4 37 21 pm](https://cloud.githubusercontent.com/assets/1019609/15131399/6a41ffa2-1604-11e6-88d1-8ccba7a12233.png)
Schema:
![screen shot 2016-05-09 at 4 36 54 pm](https://cloud.githubusercontent.com/assets/1019609/15131402/71380c34-1604-11e6-8059-b78336130f47.png)

So, the issue is that when I run the above function with **dashboard_id=2**, I get an empty array. I am expecting an array filled up with all the historical versions from the table instead for **dashboard_id=2** .

**Comment by torkelo** [comment]
I am not sure how to read an array of ids like that, maybe open an issue with https://github.com/go-xorm/xorm
