### ISSUE TITLE
[Bug] Grafana 3 does not show data properly with "repeat panel" when min span is not set

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#4957]
* What grafana version are you using?

Grafana 3, beta 6 & 7; installed from RPM on AMD64 CentOS

* What datasource are you using?

Prometheus

* Description

We are graphing ha proxy stats feed from two variables, and all is fine:
![grafana_3_beta7-0](https://cloud.githubusercontent.com/assets/754723/15140062/bc362dde-1699-11e6-80bf-c61e729b3071.png)

When I set it to repeat panel on `$haproxy_frontends`, this happens:

![grafana_3_beta7-1](https://cloud.githubusercontent.com/assets/754723/15140033/80225214-1699-11e6-8424-c1994984a016.png)

When I try to unset repeat panel, this is the UI in the edit dialogue:

![grafana_3_beta7-2](https://cloud.githubusercontent.com/assets/754723/15140034/8022b7e0-1699-11e6-8634-8d66e02d1d49.png)

And when I change it back, the graph looks like this:

![grafana_3_beta7-3](https://cloud.githubusercontent.com/assets/754723/15140035/80236ba4-1699-11e6-8558-85a976a34f75.png)

JSON dumps of all three stages are available, but I would prefer to share those by direct mail or some other non-public means.

**Comment by torkelo** [comment]
So the second image where the panels are repeated but the graph is blank, what is the prometheus query and promethus response?

**Comment by RichiH** [comment]
In Grafana: `irate(haproxy_frontend_bytes_in_total{fqdn=~"$haproxies",frontend=~"$haproxy_frontends"}[1m])`

Link to prometheus:
`irate(haproxy_frontend_bytes_in_total{fqdn=~"<redacted>",frontend=~"<redacted>"}[1m])`

![grafana_3_beta7-4](https://cloud.githubusercontent.com/assets/754723/15141330/e0646c92-169f-11e6-8770-01d6dbc2187b.png)

**Comment by torkelo** [comment]
and what is the raw query sent to prometheus and prometheus response? (check in chrome dev tools network tab)

**Comment by RichiH** [comment]
I am not sure if that's what you need/want, but assuming I got it right, here goes the cURL link from the dev tools.

`curl 'http://<url>:3000/api/datasources/proxy/1/api/v1/query_range?query=irate(haproxy_frontend_bytes_in_total%7Bfqdn%3D~%22<redacted>%22%2Cfrontend%3D~%22<redacted>%22%7D%5B1m%5D)&start=1462786643&end=1462873043&step=63072000' -H 'Accept-Encoding: gzip, deflate, sdch' -H 'Accept-Language: en-US,en;q=0.8' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/50.0.2661.94 Safari/537.36' -H 'Accept: application/json, text/plain, */*' -H 'Referer: http://<redacted>:3000/dashboard/db/services-loadbalancers-haproxy-instance?panelId=4&fullscreen&edit' -H 'Cookie: grafana_sess=<redacted>; grafana_user=<redacted>; grafana_remember=<redacted>' -H 'Connection: keep-alive' --compressed`

There is a second one which is the same, just for `haproxy_frontend_bytes_out_total` instead of `haproxy_frontend_bytes_in_total`.

**Comment by torkelo** [comment]
and what is prometheus's response? Can you see any problem with the query Grafana generated and sent to Prometheus?

**Comment by RichiH** [comment]
Sorry for being dense, before...

I see that prometheus only replies with one data point. This is the same when I execute the query by hand. 

The time I want it for is 24 hours, so 86400 seconds:

`1462873043 - 1462786643 = 86400`

But the step is 63072000, which is one year. Looking at Grafana with open eyes, I see that step is being set to `1y` for whatever reason; changing that back e.g. `60s` fixes this.

So I guess part of the problem is wrong stepping. That does not explain the weird effect in the settings, though.

**Comment by torkelo** [comment]
did you specify a min span in the repeat options (this should be a required option)

**Comment by RichiH** [comment]
Setting a min span fixed all issues.

It was not a required field, and, arguably, Grafana should not fail in such a way even when that's empty. An import might lack that field/information.

**Comment by torkelo** [comment]
yes, I agree, min-span should have value by default.

**Comment by rubycut** [comment]
I have this same issue while using in influxdb backend.

**Comment by rubycut** [comment]
Seeting MinSpan solves issue with influxdb also.

**Comment by RichiH** [comment]
Just for housekeeping: Still applies to Grafana 3

**Comment by shpsec-dennis** [comment]
I'm not sure this was explicitly mention, but this happens editing just the panel in 'fullscreen' mode. If I have a templated query and I just edit the first panel, I'm taken to full screen mode, but because the minSpan is not set it looks like the screenshots in this bug. It was pretty frustrating figuring out what settings prevented this from happening as a new user.

**Comment by torkelo** [comment]
fixed!

**Comment by RichiH** [comment]
Thanks!

Richard

Sent by mobile; excuse my brevity.
