### ISSUE TITLE
can not query azure resource graph

### ISSUE THREAD

**Issue by macropan** [grafana/grafana#49575]
**What happened**: can not query azure resource graph, show me the error api version, but I did not find "2021-06-01-preview" in resource code.

**What you expected to happen**: get error message below

request failed, status: 404 Not Found, body: {"error":{"code":"InvalidResourceType","message":"The resource type 'resources' could not be found in the namespace 'Microsoft.ResourceGraph' for api version '2021-06-01-preview'. The supported api-versions are '2018-09-01-preview,2019-04-01,2021-03-01'."}}

**How to reproduce it (as minimally and precisely as possible)**:
add "Azure monitor" for "Azure China" Cloud

<img width="1112" alt="image" src="https://user-images.githubusercontent.com/6326663/170237825-0243b9cd-1cfe-44dc-a00e-99716e9183b2.png">

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 8.2.7
- Data source type & version: Azure mornitor ( China )
- OS Grafana is installed on: CentOS 7.9 running Docker 1.13.1
- User OS & Browser: Edge
- Grafana plugins: 
- Others:

**Comment by kostrse** [comment]
@aangelisc @andresmgot: type/bug datasource/Azure

Looks like Public and China support different `api-version` values.
Need to check if there's any recent `api-version` which works in both environments.

**Comment by aangelisc** [comment]
Hi @macropan - thanks for reporting this! @kostrse, it seems like 2021-03-01 should be find to use from checking with the docs. I'll confirm that this is the case.

**Comment by macropan** [comment]
@aangelisc  
Why is this API version "2021-06-01-preview" not found in the resource code?
just found this
./grafana-azure-monitor-datasource/resourcePicker/resourcePickerData.ts:const RESOURCE_GRAPH_URL = '/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01';

**Comment by aangelisc** [comment]
Hi @macropan, this is actually set [here](https://github.com/grafana/grafana/blob/93f9792199728723bc4f683a54913d77c04510ab/pkg/tsdb/azuremonitor/resourcegraph/azure-resource-graph-datasource.go#L50). I will review this and make necessary changes 😊

**Comment by macropan** [comment]
Hi @aangelisc 
Thanks for your reply. 
Will you update the version of 8.2.7? 
I was unable to upgrade to a higher version, such as 8.3 and above, due to some alerting configurations

**Comment by kostrse** [comment]
Azure Resource Graph explorer in Azure Portal uses in Public cloud:
`https://management.azure.com/providers/Microsoft.ResourceGraph/resources?api-version=2021-03-01`

So, this API version should work at least in Public cloud, probably in China cloud too.
Do not have subscription to confirm.

**Comment by macropan** [comment]
I have check with api-version=2021-03-01, it is working
<img width="982" alt="image" src="https://user-images.githubusercontent.com/6326663/170634749-2400edfe-05e3-4ce9-acd9-7034e1682ec0.png">

**Comment by macropan** [comment]
Hi，any update?

**Comment by jcolladokuri** [comment]
Hi @macropan sorry for the delay, the ARG API version has been rolled out to all clouds so you should not be running into any issues anymore. Could you please give it a try and let me know if it still is not working for you?

**Comment by aangelisc** [comment]
I'll close this issue as it should be resolved, if there are any problems please feel free to reopen 😊

**Comment by macropan** [comment]
Hi @jcolladokuri , do I need download docker image for 8.2.7 and redeploy it?
