### ISSUE TITLE
[Bug] User Role is overridden when viewing embed graph and then logging in

### ISSUE THREAD

**Issue by Liudvikas** [grafana/grafana#4958]
To reproduce:
1. [Browser1][Admin] Set User role to Editor;
2. [Browser2][User][logged out] View embed graph on 3rd party system (wiki);
3. [Browser2][User] Log in to grafana;
4. [Browser1][Admin] Refresh users page - User role is "Viewer".

* What grafana version are you using? 
Grafana v3.0.0-beta7 (2016-05-02)
* What OS are you running grafana on?
Red Hat Enterprise Linux Server release 6.7 (Santiago)

Attached grafana.ini:
[grafana.ini.txt](https://github.com/grafana/grafana/files/256723/grafana.ini.txt)

**Comment by torkelo** [comment]
It looks like you have ldap enabled, ldap group mappings will set user roles when logging (so they match the your ldap group -> grafana role mapping)
