### ISSUE TITLE
[Bug] labels are cut off in image export

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#4959]
- What grafana version are you using?

Grafana 3, beta 7; installed from RPM on AMD64 CentOS
- What datasource are you using?

Prometheus

When I use "share" -> "direct link rendered image" on the graph in https://github.com/grafana/grafana/issues/4957 (with labels added), the result is cut off at the bottom:

![grafana_3_beta7-10](https://cloud.githubusercontent.com/assets/754723/15141173/16d46f58-169f-11e6-897e-f1bd4340587e.png)

**Comment by torkelo** [comment]
this looks to be fixed, think it was fixed sometime during 4.0 dev

**Comment by RichiH** [comment]
Not quite, but this is arguably a new bug report:

![labels_cut_off_second_attempt](https://cloud.githubusercontent.com/assets/754723/21590396/b6a85d98-d0fb-11e6-8909-64592bc65e33.png)

**Comment by RichiH** [comment]
As you can see, the scroll part is cut off.

**Comment by torkelo** [comment]
you screenshot did not use a table legend :)

**Comment by RichiH** [comment]
You are, of course, right. It works as expected without table.

**Comment by RichiH** [comment]
And thanks :)
