### ISSUE TITLE
Applying a query expression on a template Lucene query fails

### ISSUE THREAD

**Issue by McPatate** [grafana/grafana#49602]
**What happened**:

I'm currently trying to apply an expression to a template ElasticSearch Lucene query. The issue I have is that when I create the expression and refresh, there is no more data.

I'm getting a few errors in grafana logs :
- `expression request error: failed to query data: context canceled`
- `http: proxy error: context canceled`

The queries look like this :
- Query A : `some.es_var: $my_grafana_var AND some.other_es_var:*`
- Query B : `$A / 60`

**What you expected to happen**:

I was expecting the expression to be applied correctly to my data.

**How to reproduce it (as minimally and precisely as possible)**:

1. Create panel and choose the ES data source
2. Create a dashboard variable based on a lucene query
  a. variable name : `my_grafana_var`
  b. query: `{"find": "terms", "field": "some.es_var"}`
3. Select the appropriate interval (for me 1m)
4. Enter `some.es_var: $my_grafana_var AND some.other_es_var:*`
5. Add another expression query
6. Enter `$A / 60`

Optional steps :

7. Change visualisation to Stats
8. In value options > Show, choose Calculate
9. In value options > Calculation, choose Mean
10. In value options > Field, choose B

**Anything else we need to know?**:

When I remove my grafana variable from the query and replace it by a hardcoded value or a wildcard, things work.

Also, when I write `AND` in lowercase (`and`) I get data again but the data looks incorrect.

The generated json of the panel targets looks like this :
```json
      "targets": [
        {
          "alias": "",
          "bucketAggs": [
            {
              "field": "@timestamp",
              "id": "2",
              "settings": {
                "interval": "1m"
              },
              "type": "date_histogram"
            }
          ],
          "datasource": {
            "type": "elasticsearch",
            "uid": "<some_uid>"
          },
          "metrics": [
            {
              "id": "1",
              "type": "count"
            }
          ],
          "query": "some.es_var: \\/path\\/$my_grafana_var AND some.other_es_var:*",
          "refId": "A",
          "timeField": "@timestamp"
        },
        {
          "datasource": {
            "type": "__expr__",
            "uid": "__expr__"
          },
          "expression": "$A / 60",
          "hide": false,
          "refId": "B",
          "type": "math"
        }
      ],
```

**Environment**:
- Grafana version: `8.4.5`
- Data source type & version: `elasticsearch` & ElasticSearch 8.x
- OS Grafana is installed on: Grafana docker image running in kubernetes
- User OS & Browser: Linux & Firefox
- Grafana plugins: N/A
- Others: N/A

**Comment by zuchka** [comment]
looks like you are using a server-side expression in conjunction with some browser-side calculations provided by the stat panel options. does the first expression work when you remove that second level of complexity?

**Comment by McPatate** [comment]
Indeed, removing the second expression works. Is it not possible to apply an expression to the result of the query then ?

**Comment by gabor** [comment]
hi @McPatate thanks for reporting the issue. the server-side expressions are mostly used in alerting queries, so they might have problems when using in a dashboard. can we try to make the test-case smaller?
can you reproduce the issue just by having one elasticsearch query and one expression? (without the dashboard variable)

**Comment by gabor** [comment]
hi @McPatate i did some testing, and i can reproduce the problem in grafana8.4.5, but it works in grafana8.5.5. could you try updating to a newer grafana version? thanks!

**Comment by gabor** [comment]
@McPatate no problem, i'm glad it got solved at the end!
