### ISSUE TITLE
Access and Creation metadata for API keys and SATs

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#4961]
Due to internal security/due diligence reasons, we need to review access methods every once in a while.

It would help immensely if the following additional data would be stored & shown, in decreasing order of importance:
1. Creation timestamp
2. Last used timestamp
3. User who created the API key
4. Comment field

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).

**Comment by RichiH** [comment]
@oanamangiurea @ChrisD-Git I was under the impression that we're actively working on this for Grafana itself and for Cloud as we need it for security compliance reasons?

**Comment by RichiH** [comment]
Re-opening until we know either way.

**Comment by Jguer** [comment]
Repurposing this issue for both API keys and Service Account tokens.

Implementing one means implementing the other, only frontend might differ or not be implemented for API keys

**Comment by Jguer** [comment]
1. Creation timestamp

Implemented and displayed for service accounts and their tokens

2. Last used timestamp

Implemented in https://github.com/grafana/grafana/pull/51446

3. User who created the API key

Currently viewable through audit logs. Display will evaluated after 9.1 

4. Comment field

Display and need will evaluated after 9.1
