### ISSUE TITLE
[Question] How to specify yesterday on a second metric

### ISSUE THREAD

**Issue by oazabir** [grafana/grafana#4962]
I would like to overlay today and yesterday lines on the same graph, so that I can compare how things are today vs yesterday. 

I was trying adding another metric to get another line and was trying to put condition like:

@timestamp gt now-1d
@timestamp>now-1d
@timestamp:>now-1d
@timestamp:now-1d
@timestamp:[now-1d TO *]
@timestamp:[2016-05-08 TO *]
etc

Nothing works. 
Data source is ElasticSearch.

**Comment by torkelo** [comment]
Elasticsearch does not have a timeshift function or transform in it's query api  (Like Graphite for example). 

This could potentially be implemented in https://github.com/grafana/grafana/issues/3677

**Comment by imaben** [comment]
@torkelo If use influxdb, Can be achieved?
