### ISSUE TITLE
[Question] Influxdb group by function

### ISSUE THREAD

**Issue by d01mf** [grafana/grafana#4963]
Grafana version: 3.0.0-beta7 (on Ubuntu)
Data source: InfluxDB v0.9.5

I've added my own templating variable with which I want to control the data point grouping resolution. This works as expected by adding $myvar to the "Group by time interval" field for my graphs.
However, I notice some bad performance when I zoom out and pick a high resolution, e.g. 1min resolution spanning over a year.
From what I understand the "GROUP BY time($interval)" makes sure we don't ask for more data points needed by the screen resolution. It seems like adding my own $myvar in the graph-global "Group by time interval" field overrides the less granular time($interval).

So, my question is how I could control the group by time interval through my templating variable, but still use  time($interval) as a upper limit on the resolution. There doesn't seem to be any support for functions inside the group by field, e.g. group by max($myvar, time($interval)).

Thanks!

**Comment by torkelo** [comment]
you can't, you can either let Grafana control the interval, in this case it will try to set it so that InfluxDB returns at most the same number of data points as the graph has pixels. It will also respect a min limit you can specify below your influxdb queries or in the data source options (like `>10s`) if you write every 10s. 

You can also create a interval template variable that also has an auto option that works similar but you have some control over how many steps the auto option should aim for. 

http://play.grafana.org/dashboard/db/influxdb-templated-queries

**Comment by d01mf** [comment]
Thanks for the quick response!

Are there any use cases for queries that return substantially more data points than horizontal pixels? Otherwise one could argue that the group by time($interval) should always be in effect.

I understand if there are no clean ways of adding this "feature". I'll just need to avoid selecting stupid combinations of resolution and time span.


Thanks!

**Comment by torkelo** [comment]
group by time($interval)  is the default . but in some cases you want larger group by buckets (for bar charts for example)

**Comment by d01mf** [comment]
Ah yes, larger groups I understand. That's what I want to accomplish; select-ably larger groups. But still with the "way too many data points"-protection of time($interval).

Some logic to select the maximum between user specified group (if available) and time($interval).

**Comment by torkelo** [comment]
that is what the interval variable does :)

http://play.grafana.org/dashboard/db/interval-template-variable

**Comment by d01mf** [comment]
The $interval isn't used in the example you provided. Instead the user selectable $summarize is used in the graph-specific "group by" ("Group by time interval" below all the queries).
The series-specific "group by" is set to "time(auto)" - rather than the default "time($interval)". I'm not quite sure what this change does.

Now, the example provided does not have that many data points, so performance is not that bad. Still you can see the issue I'm trying to point out if you zoom out to last 90 days and toggle between 10m and 30m resolution. There's a performance penalty for 10m. Both 10m and 30m result in sub-pixel resolution regardless of the series specific "group by" is set to "time(auto)" or "time($interval)". 

I would have liked to see the same performance and same graph for 10m and 30m if the "group by" was set to "time($interval)" when zoomed out far enough (e.g. last 90 days). Both should be capped by the graph resolution.

Anyway, I hope I hav explained the issue clear enough for others to understand. Could be useful regardless of the issue being fixed or not.

Thanks!

**Comment by torkelo** [comment]
I think you are misunderstanding how this works, if you have ave last 90 days and group by 10m and a small graph influxdb will return more data points than needed, and InfluxDB is really slow for large time ranges, (if you dont have rollups).  There is nothing Grafana can do if you specify a group by time manually. 

The dashboard I linked to has a template variable called summarize that is set to auto, but you can specify how many bars you want, so when you zoom out the same number of bars will be shown. So you will never overload Grafana with a million data points. but you can control how many bars you want in the template variable options.

**Comment by d01mf** [comment]
I understand. 

But "$interval" and "$summarize" are never passed to influxdb, are they? Their _values_ are, right? 

I take it that Grafana does some pre-processing of the queries before passing them to influxdb. For example the $interval is replaced by an actual time range that influxdb understands. Same with the templating variables. 

So, rather than just substituting variables with their values Grafana could(?) evaluate some function. In my case I would like to return the largest time range out of two; $summarize and time($interval).

**Comment by torkelo** [comment]
yes Grafana interpolates them, you can set a lower limit for the $interval built in variable

**Comment by temenoskrpavithra** [comment]
I have a query on using Interval variable. I have selected a Time range for the dashboard [  Jan 2016 to Feb end 2017 ] and my data points are only in Feb 2017.
On the metrics, I'm calculating mean. 
On the graph, i see month on X axis and mean is plotted against 2-Feb-2017
When i use Summarize for 30days, i see the mean plotted against 24-Jan-2017.
I fail to understand the reason why Feb's points would move to Jan month on the graph when calculating average and summarizing for 30d
