### ISSUE TITLE
[Bug] Grafana 3 beta 6 no longer work on iPad 1

### ISSUE THREAD

**Issue by zsxking** [grafana/grafana#4964]
I upgraded from grafana 2.6 to grafana 3 beta 6, and it stops loading on my iPad 1. Debug console said there is a TypeError of undefined, can't get more detail about the error from the device. It works fine from my other devices like ipad mini, macbook, android phone. Only one other device has the same problem is Kindle Whitepaper. Both device works fine with grafana 2.6.

My iPad 1 is setup as dashboard display as part of my home monitoring.

**Comment by torkelo** [comment]
what browser are you using on your ipad 1 ? can you test updating to latest version of safari or chrome?

**Comment by zsxking** [comment]
I tested on both safari and chrome, same thing, blank page. 

Because iPad 1 can only update to iOS 5.1.1, it can't install the latest version of the browsers. What it have installed are the latest available to it. Basically there is no way to fix the device to make it work with the grafana 3 beta 6 build I tried.

**Comment by torkelo** [comment]
do you know what the latest version of chrome is that works on ipad 1?

**Comment by zsxking** [comment]
29.0.1547.11
