### ISSUE TITLE
[HG] URLs in the header of /plugins/[plugin_name] in Grafana doesn't appear as a URL

### ISSUE THREAD

**Issue by timlevett** [grafana/grafana#49644]
On the /plugins/[pluginname] page, the name of the plugin is not a URL but it should be! Also docs and license should be underlined.

[Internal reference](https://grafana.productboard.com/feature-board/4266220-self-serve-feature-ux-docs-requests/features/13434656/detail)

**Comment by leandro-deveikis** [comment]
PR: https://github.com/grafana/grafana/pull/55581
