### ISSUE TITLE
[BUG] OpenTSDB queries using wrong content-type

### ISSUE THREAD

**Issue by fzoske** [grafana/grafana#4965]
Please include some basic information:
- What grafana version are you using? **v3.0.0-beta61461604293**
- What datasource are you using? **OpenTSDB**
- What OS are you running grafana on? **Docker**
- What did you do?
Created a Java Application using Spring Boot and Netflix Zuul Proxy
Added route for OpenTSDB in Zuul Proxy Configuration
Added Zuul route as Datasource in Grafana

- What was the expected result?
Everything should work as Zuul is only a reverse proxy.
- What happenend instead?
No content is delivered.

I digged into the datasource for OpenTSDB and found out, that https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/opentsdb/datasource.js#L139 is causing the problem as 'application/x-www-urlencoded' is set as Content-Type but the content actually is 'application/json'.
Spring requests that content and content-type header does match.

**Comment by bergquist** [comment]
The link is broken. the file in master have changes since you posted this issue.

**Comment by fzoske** [comment]
The new link is: https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/opentsdb/datasource.js#L135
