### ISSUE TITLE
[Bug] Tooltip/Legend value on stacked graphs with percent

### ISSUE THREAD

**Issue by nordewal** [grafana/grafana#4966]
When creating stacked graphs with percent values, the tooltips/legends are incorrect and display the 'raw' value instead of the percent value:

![grafana-tooltip-percent2](https://cloud.githubusercontent.com/assets/3670669/15147004/6ba53aa2-16be-11e6-8a0b-c4ae545f6972.png)

There is a special case: If you select tooltip mode 'single' and tooltip value 'individual', it is working as expected:

![grafana-tooltip-percent](https://cloud.githubusercontent.com/assets/3670669/15146891/f1a8a81a-16bd-11e6-8449-a7001a874d79.png)

The tooltip/legend values should always be the percent value in case of a stacked graph with percent - as in the tooltip of the second image.

**Comment by torkelo** [comment]
This is related to a very old issue with stacked + percent mode. I would not recommend using percent mode if you want the legend and tooltip to also show percent values. If you need that calculate the percent in the metric query if you can (Graphite has functions like asPercent and divideSeries)

https://github.com/grafana/grafana/issues/1107

**Comment by toni-moreno** [comment]
There is also  a pending PR ( with this job already done) 
https://github.com/grafana/grafana/pull/3362

**Comment by pawadski** [comment]
I'm still seeing this behavior in v7.3.7
