### ISSUE TITLE
build failure in the recent releases

### ISSUE THREAD

**Issue by dengliu** [grafana/grafana#4967]
I starting seeing build error since 3.0.0-beta6 
The most recent version I am able to successfully build grafana is 3.0.0-beta3

Build environment:
OS: Ubuntu14.0.2
node (v0.12.0), npm (v2.5.0) and grunt (v0.4.5)

Build errors are as below:
npm WARN package.json expect.js@0.2.0 No repository field.
|
> phantomjs@1.9.19 install /home/dennis/git/goworkspace/src/bitbucket.org/dengliu/grafana/node_modules/phantomjs
> node install.js

> PhantomJS is previously installed at phantom/bin/phantomjs
> npm ERR! Linux 3.19.0-25-generic
> npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
> npm ERR! node v0.12.0
> npm ERR! npm  v2.5.1
> npm ERR! code EPEERINVALID

**Comment by torkelo** [comment]
have not seen any build errors like that on our CI build server 
https://circleci.com/gh/grafana/grafana

You need Nodejs 4+

**Comment by dengliu** [comment]
Thanks. It would be great to update the dependency section in READ.me
It was still v0.12.0 there

<img width="300" alt="screen shot 2016-05-10 at 6 59 47 am" src="https://cloud.githubusercontent.com/assets/5108773/15149068/f6962960-167c-11e6-8133-b1df13a36216.png">

**Comment by torkelo** [comment]
done :)

**Comment by dengliu** [comment]
"Building frontend assets" section is also outdated :)
<img width="1126" alt="screen shot 2016-05-10 at 7 25 29 am" src="https://cloud.githubusercontent.com/assets/5108773/15149974/6fc85706-1680-11e6-8719-a5a9105eddfd.png">
