### ISSUE TITLE
Table Panel, horizontal scroll bar disappeared

### ISSUE THREAD

**Issue by fsa1803** [grafana/grafana#49704]
**What happened**:

When enable paging, on Table Panel, the horizontal scroll bar, in the footer of table, disappeared.

**What you expected to happen**:

The horizontal scroll bar remain visible

**How to reproduce it (as minimally and precisely as possible)**:

Use a table with many column

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3 OSS
- Data source type & version: OpenSearch 1.1.2
- OS Grafana is installed on: RedHat 8.3
- User OS & Browser: Windows 10, Chrome and Firefox
- Grafana plugins:
- Others:
![Cattura1](https://user-images.githubusercontent.com/66841577/170498896-31d62bc0-2191-449d-8fa2-6a6c8bfc4f93.PNG)

![Cattura2](https://user-images.githubusercontent.com/66841577/170499145-b2fd6bdb-a224-4a4a-93af-0b6b267a6bd8.PNG)

**Comment by aj-ps** [comment]
Hi, I am facing similar issue. There is no horizontal scroll bar in table panel with many columns. Was this resolved or being worked on?

**Comment by zuchka** [comment]
this appears fixed now:

https://play.grafana.org/d/s2xOEMz4z/49704?orgId=1
