### ISSUE TITLE
[Question] Templating using KairosDB datasource is not working

### ISSUE THREAD

**Issue by shriramsharma** [grafana/grafana#4971]
Please include some basic information:
- What grafana version are you using? 
2.6.0
- What datasource are you using?
kairosDB
- What OS are you running grafana on?
RedHat 6.5
- What did you do?
I tried to create a template using regex and it doesn't seems to work. The same regex works if the datasource is graphite. My metric names start with test.XXX. 
Query=*
Regex=^test\.(.*)

- What was the expected result?
Show matched regex in the dropdown.
- What happenend instead?
The template dropdown is blank.

**Comment by torkelo** [comment]
wildcard: `*` is not in the list of supported templating queries for KairosDB
http://docs.grafana.org/datasources/kairosdb/#templated-queries

**Comment by shriramsharma** [comment]
Thanks @torkelo . That worked.
