### ISSUE TITLE
Change settings in preparation for deprecating old alerting

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#49721]
In Grafana 9 we will enable UA (Unified Alerting) in two further situations:

1. `GF_ALERTING_ENABLED` is true, `GF_UNIFIED_ALERTING_ENABLED` is not set (neither true or false) and the `alerts` table has one or more alerts

2. Neither `GF_ALERTING_ENABLED` nor `GF_UNIFIED_ALERTING_ENABLED` are set (neither true or false) and the `alerts` table has one or more alerts

Prior to Grafana 9 both of these situations would result in running legacy alerting.

**Comment by joeblubaugh** [comment]
Isn't the `alerts` table what holds definitions for legacy alerting? Should they read `alert rule` table?

Let's be sure to write this down with extensive documentation. Will both of these conditions result in migrations being run?

GF_ALERTING_ENABLED being unset currently defaults to true. Is this update essentially saying:
A) GF_ALERTING_ENABLED now defaults to false
C) GF_UNIFIED_ALERTING defaults to true
D) GF_UNIFIED_ALERTING being true always overrides GF_ALERTING_ENABLED

Is there a case I'm missing?

**Comment by joeblubaugh** [comment]
This PR is related to this issue:
https://github.com/grafana/grafana/pull/49834/
