### ISSUE TITLE
Feature Request: Change "zoom out" behaviour to restore previous positioning (i.e. from before zooming in), rather than just zooming out by factor of 2

### ISSUE THREAD

**Issue by abraae** [grafana/grafana#4973]
It would be cool if the "zoom out" button restored the previous positioning, rather than the current behaviour (which appears to be to zoom out by a factor of 2).

This would provide a better experience when zooming in, examining a small area, then zooming back out, zooming in to the next area for review, zooming back out, etc.

This is currently impossible. Now, if I zoom in to a tiny area, afterwards I need to click zoom out maybe 8 times to get back to somewhere like my previous position. Even then, the scale is wrong and the view is centered on the region I zoomed to, rather than the previous position - and there is no scroll right or left to correct it. In this situation I personally find it easier to constantly do "last 30 days" to get back to the big picture, then zoom right in again, but that is less than ideal.

The implementation might be to somehow maintain a stack of zoom levels. When clicking "zoom out" and the stack was empty (e.g. when you arrive at a saved dashboard that is already zoomed in to a tight area) I would fall back to the existing behaviour and zoom out by 2.

Somewhat related to requests to add left/right scrolling:
https://github.com/grafana/grafana/issues/1565
https://github.com/grafana/grafana/issues/1387

**Comment by torkelo** [comment]
good idea, might not be what you want in some cases, but worth considering!

moving time range left and right is implemented in Grafana 3.0

![image](https://cloud.githubusercontent.com/assets/10999/15172330/b9b18c18-1755-11e6-82ba-8947ef1cdf8d.png)

**Comment by abraae** [comment]
Scroll left and right will be enormously useful.

**Comment by abraae** [comment]
Since using scroll left and right for a while I no longer feel this is a priority for me.

**Comment by skupjoe** [comment]
A typical operation that I do in other tools is drag and zoom into a particular part on the graph and then I want to zoom back out.

Having a "Reset Zoom" button would be extremely useful.

**Comment by LukasK13** [comment]
Is there any plan for this to be implemented?

**Comment by mdbridge** [comment]
agree that adding a zoom reset would be very useful

**Comment by gruaGit** [comment]
also miss that function!

**Comment by leeoniya** [comment]
the dashboard timerange is part of the url history, so undo-zoom/restore previous range is simply the browser back button.
