### ISSUE TITLE
Cookies conflict when running multiple Grafana instances on same host

### ISSUE THREAD

**Issue by dutchiechris** [grafana/grafana#4974]
3.0b7

I am running a couple of Grafana instances on the same host using Docker containers.  I access them via http://hostname:port with Docker TCP port mapping the default 3000 internal to something unique external. If I use multiple tabs in Chrome I can only be logged into one instance at a time and as soon as I login a different instance my previous logins are no longer valid.  I've been using a workaround of incognito browser windows, but it would be nice if Grafana's use of cookies would work properly if multiple Grafana instances are running on the same host.

**Comment by torkelo** [comment]
if the two instances only differ by port then there is no way to solve it (that I know, as port is not part of cookie namespace, only hostname and url)

**Comment by torkelo** [comment]
try putting a nginx infront that proxies request so you get http://hostname/grafana1 http://hostname/grafana2  , then the cookies will not conflict (if you specified a full url here, http://docs.grafana.org/installation/configuration/#root_url)

**Comment by torkelo** [comment]
oh, another easier way is to change the cookie name :)
http://docs.grafana.org/installation/configuration/#cookie_name
