### ISSUE TITLE
Explore: Loki Log volume graph on Instant query buggy

### ISSUE THREAD

**Issue by danpoltawski** [grafana/grafana#49749]
**What happened**:
When using the **Explore** view to view high-volume loki stream and choosing **Instant** Query Type - the log volume graph gets stuck at 'Log volume is loading...' and has the constant loading animation even though the log stream has completed loading. This seems to happen particularly at low time periods in the time period.

While it doesn't really make sense to do instant queries like this for standard exploring of data, I use this approach to work on metric queries and it constantly catches me out because it gives the impression the query has failed or is timing out.

**What you expected to happen**:
I don't think displaying the Log volume graph when doing an instant query is necessary as it doesn't display valuable information.  But I'd expect to not constantly spin loading

**How to reproduce it (as minimally and precisely as possible)**:
1. Choose a high volume Loki log stream in Explore view 
2. Choose a short time period in the range selector 
3. Switch the query type to 'Instant'

![loki-log-error](https://user-images.githubusercontent.com/533249/170668774-784601c9-9024-49a2-9748-111c02307604.gif)

**Anything else we need to know?**:

It seems like changign the time period to a longer range prevents this.

The browser error console has:
```
Uncaught TypeError: this.fieldByType[e] is undefined
    getFirstFieldOfType Aframe
    C logs_model.ts:597
    C logs_model.ts:579
    C logs_model.ts:577
    complete logs_model.ts:656
    RxJS 2
FieldCache.ts:63:4
    getFirstFieldOfType Aframe
    C logs_model.ts:597
    C logs_model.ts:579
    map self-hosted:180
    C logs_model.ts:577
    complete logs_model.ts:656
    RxJS 78

```
or in Chrome:
```
reportUnhandledError.js:10 Uncaught TypeError: Cannot read properties of undefined (reading 'find')
    at i.getFirstFieldOfType (FieldCache.ts:62:31)
    at logs_model.ts:597:51
    at logs_model.ts:578:12
    at Array.map (<anonymous>)
    at C (logs_model.ts:577:44)
    at Object.complete (logs_model.ts:656:38)
    at e.complete (Subscriber.js:121:33)
    at t._complete (Subscriber.js:75:30)
    at t.complete (Subscriber.js:52:18)
    at t._complete (Subscriber.js:75:30)
```

My Loki config has:
```
querier:
  query_ingesters_within: 3h
```

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: Loki 2.5.0
- OS Grafana is installed on: Linux- Debian
- User OS & Browser: Windows - Firefox/Chrome/Edge

**Comment by mellieA** [comment]
@danpoltawski thanks for all of the details. Do you happen to have full volume logs enabled?  I noticed this issue that sounds similar: 

https://github.com/grafana/grafana/pull/40327

**Comment by danpoltawski** [comment]
> Do you happen to have full volume logs enabled?

I assume from [this blog post](https://grafana.com/blog/2022/03/02/new-in-grafana-8.4-how-to-use-full-range-log-volume-histograms-with-grafana-loki/) that they are enabled by default in Grafana 8.5? In which case yes they are enabled, we've not taken any action to disable it.

I assume also that https://github.com/grafana/grafana/pull/40327 is already present in 8.5 so wouldn't be the fix

**Comment by ifrost** [comment]
Good point. We can disable log volume for instant queries by adding additional check to https://github.com/grafana/grafana/blob/v9.0.0-beta2/public/app/plugins/datasource/loki/datasource.ts#L144 (cc @grafana/observability-logs-and-traces)

**Comment by gabor** [comment]
@ifrost i'll do that. (i had some other ideas, but this one seems to be the best). we will not include logs-producing instant-queries in the histogram.

**Comment by gabor** [comment]
reopening this, sorry. the fix was not the correct fix, need to revert it. will fix it better later 😄
