### ISSUE TITLE
Variables: variables in Markdown links are not expanded in the text panel

### ISSUE THREAD

**Issue by Lekensteyn** [grafana/grafana#49759]
**What happened**:
Variable references such as `${__url_time_range}` are not expanded in Markdown links. It used to work with 8.2.7.

The reproducer below turned into:
```
[Example: from=now-6h&to=now](https://example.com/?$%7B__url_time_range%7D)
```

**What you expected to happen**:
It should have been expanded to:
```
[Example: from=now-6h&to=now](https://example.com/?from=now-6h&to=now)
```

**How to reproduce it (as minimally and precisely as possible)**:
To reproduce, modify the text panel example at https://play.grafana.org/d/bPZNLW_Mz/text-panel?orgId=1&editPanel=2 and add:
```
[Example: ${__url_time_range}](https://example.com/?${__url_time_range})
```

**Anything else we need to know?**:
It was originally reproduced with a variable expansion such as `${foo:queryparam}`.

**Environment**:
- Grafana version: 8.5.3 and 8.5.2
- Data source type & version:
- OS Grafana is installed on: Linux
- User OS & Browser: Firefox 100.0.2 on macOS 12.4
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@Lekensteyn it seems like this is working for me. I'm using a mac with chrome, can you confirm? 

<img width="1237" alt="Screen Shot 2022-05-31 at 8 55 08 PM" src="https://user-images.githubusercontent.com/18175287/171318566-8fe7e4d3-687d-4456-b544-810df4cdbc80.png">

**Comment by Grimmish** [comment]
I can confirm this same issue with Chrome 102.0.5005.61 on Ubuntu 20.04.

Issue appeared after upgrading from Grafana 8.3.4 to 8.5.4.

**Comment by mellieA** [comment]
I just upgraded my chrome to the latest and tried again on play, it still seems to work for me. Are you reproducing this on play or on your local instance?

**Comment by Grimmish** [comment]
I am able to reproduce this on https://play.grafana.org/d/bPZNLW_Mz/text-panel?orgId=1&editPanel=2

Here is the content:
```
# Title

[This link uses Markdown syntax](http://example.com/${__url_time_range})

<a href="http://example.com/${__url_time_range}">This link uses HTML syntax</a>
```
![Screenshot at 2022-06-02 14-40-13](https://user-images.githubusercontent.com/2854533/171724826-0fb85d7e-a8e7-4090-8e3b-111fa82fc276.png)

![Screenshot at 2022-06-02 14-40-40](https://user-images.githubusercontent.com/2854533/171724843-c23c6808-7ca7-455c-9e55-7eb5eea7979f.png)

**Comment by mellieA** [comment]
Thanks for your patience, I'm following now! Now I see that the variable substitution isn't happening. I'll get this moved to the right squad!

**Comment by Reprazent** [comment]
Thanks for getting that fixed merged @polibb! :pray:. 

Do you have an idea what release it will be in and when that release is planned for?

We noticed this problem at GitLab in https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1674

**Comment by polibb** [comment]
> Thanks for getting that fixed merged @polibb! 🙏.
> 
> Do you have an idea what release it will be in and when that release is planned for?
> 
> We noticed this problem at GitLab in https://gitlab.com/gitlab-com/gl-infra/scalability/-/issues/1674

@Reprazent It should go out in the next patch release, which usually happens weekly, though we can't make any commitments to a specific date.

**Comment by Reprazent** [comment]
Thanks @polibb! Do these kind of fixes also get backported to Grafana 8? We're currently still on 8.5.6, though I can't see anything in the changelog that should stop us from going straight to 9.x after :smile:

**Comment by polibb** [comment]
@Reprazent no worries :). No, all new patch releases are going to patch Grafana 9.x.x only.
