### ISSUE TITLE
Stat panel incorrectly rounding up values

### ISSUE THREAD

**Issue by mux** [grafana/grafana#49761]
**What happened**:

When using the Stat panel to display availability for one of our application (using percentages), I noticed that the values were somehow rounded up. This was easy to spot, as I have a different color configured for 100% vs values below, and I noticed panels showing 100% and yet having the color configured for values less than 100%. I further confirmed that the value was incorrectly rounded up by changing the configuration of the field decimals option from 'auto' to '1'. This changed the numerical value displayed to 99.7% in that specific case. It is my understanding that this is not the expected behavior when setting decimals to 'auto'.

Here is the actual query used, with the application name obfuscated:
![Screen Shot 2022-05-27 at 2 45 12 PM](https://user-images.githubusercontent.com/1478358/170772049-7e103e1e-d85b-48ed-9668-9cec53c5b301.png)

**What you expected to happen**:

I expected the Stat panel to show 99.7% (or whatever the value is), instead of rounding it up to 100%.

**How to reproduce it (as minimally and precisely as possible)**:

Overriding the value for the metric queried using the 'Script' textbox in the metric options to 99.9 was the easiest way I found to reproduce the problem. I did not try using other data sources, but, from the point of view of someone who does not know about the code of Grafana, it does not look to be related to the actual data source being used.

**Anything else we need to know?**:

I have also been unable to properly customize the text displayed using the Alias textbox. While {{term datacenter_name}} works, I wanted to include the value of other metrics using the {{my_metric}} syntax but was unsuccessful. I suppose that I should probably open another issue about that though, and this is probably due to my misunderstanding of how this should work.

**Environment**:
- Grafana version: 7.0.3
- Data source type & version: ElasticSearch
- OS Grafana is installed on: Unknown
- User OS & Browser: */Chrome
- Grafana plugins: Unknown

**Comment by mellieA** [comment]
I tried this with Grafana 8.5.0 and a value of 99.9, the stat panel correctly reports the value with decimal set to auto. It could be worth checking if you're using **calculation** which stat you're using. 

<img width="1201" alt="Screen Shot 2022-05-31 at 9 09 13 PM" src="https://user-images.githubusercontent.com/18175287/171320048-d1e9a859-ba02-4936-85cf-d6274682b2a4.png">

I'll close this for now since it seems to work as expected in the current releases. Feel free to reopen if you want to share more information.

**Comment by mellieA** [comment]
@mux the last calculation should give you the last (most recent) value for the stat. It shouldn't be rounding that value. I'm glad to hear you're planning to upgrade, I tested on 8.5 but it could be fixed in an earlier release. I didn't find a PR for the fix, so I can't say for sure.
