### ISSUE TITLE
[Feature Request] - UX - New Data Sources should have default URL

### ISSUE THREAD

**Issue by rmoff** [grafana/grafana#4977]
When creating a new datasource, the Url field should get populated by default with the appropriate one for the Type. For example, InfluxDB - localhost:8086, Elasticsearch - localhost:9200. 

The rationale for this is that a lot of the time people will (at least initially) be running Grafana local to the data source, and so this (a) speeds up the UX and (b) reduces the friction for new users of the tool by making it one less configuration setting to have to set.

**Comment by utkarshcmu** [comment]
Isn't this same as #4577

**Comment by rmoff** [comment]
Yes my bad - I did search beforehand, but didn't spot this one :) Thanks.
