### ISSUE TITLE
Cannot delete library panel

### ISSUE THREAD

**Issue by szerwi** [grafana/grafana#49774]
**What happened**:
I have some old library panels that had been created on some older Grafana versions.
I have deleted the library panel from all the dashboards, but I still cannot delete it.
I get the error "the library element has connections"
![image](https://user-images.githubusercontent.com/19311511/170865898-63d9d047-9c2c-433e-bb10-98073aea2a75.png)

![image](https://user-images.githubusercontent.com/19311511/170865903-07b4bae5-34c2-461f-9743-45aa7cd72ca9.png)

Is there any way to manually delete library panels?

**How to reproduce it (as minimally and precisely as possible)**:
I do not know what happened that these panels cannot be deleted. When I create new library panel, I can delete it without any issue.

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: InfluxDB 2.2.0
- OS Grafana is installed on: Ubuntu 5.4.0

**Comment by rany2** [comment]
I could also confirm this issue.

**Comment by szerwi** [comment]
@mellieA Unfortunately I cannot remember the exact version, but I've added those panels shortly after the library panels were released.

**Comment by joshhunt** [comment]
Thanks for reporting!

We recently discovered ([and fixed](https://github.com/grafana/grafana/pull/49161)) an issue where Library Panels can get into this state when attempting to import a dashboard using library panels, however we have not implemented a retroactive fix for Library Panels that cannot be deleted.

If you (or anyone) has a reproduction (over multiple grafana versions?) that can get Library Panels into this state (where they cannot be deleted), it would be appreciated to check if there's still another scenario that we've missed.

---

When a Library Panel is linked to a dashboard, we create a `library_element_connection` row in the database to represent the connection between the library panel and the dashboard. The Library Panels list will list all _valid_ dashboard connections, but _invalid_ connections (such as connections to a non-existent dashboard) will not show. As you've seen here, a Library Panel cannot be deleted if it has _any_ connections (but the UI will not show the invalid connections).

It is not recommended, but a workaround would be to first manually edit your database to remove the `library_element_connection` rows for the associated library panel, however this has the risk of data loss as you manually edit your database.

**Comment by joshhunt** [comment]
Yup, this is on our short-term list of priorities. Can't make any commitments to a date or release though :)

**Comment by rany2** [comment]
@mellieA I faced this issue on v8.5.3 (409e9bc9a55)
