### ISSUE TITLE
nodegraph with mysql not rendering colors on nodes

### ISSUE THREAD

**Issue by yosiasz** [grafana/grafana#49773]
hello

**What happened**:
When using nodeGraph with mysql the arc_* values are not being properly rendered on the nodes

**What you expected to happen**:
To properly render on the nodes per size of arc_*

**How to reproduce it (as minimally and precisely as possible)**:
using mysql as data source
nodegraph as visualisation
2 queries

```
Query #1
select 1 as id, 'node1' as title, 'seattle' as subtitle, 23 mainstat, 2 secondarystat, 0.25 arc__cpu, 0.75 arc__disk  union
select 2 as id, 'node2' as title, 'renton' as subtitle,12 mainstat, 6 secondarystat, 0.15 arc__cpu, 0.85 arc__disk 

Query #2
select 'a' as id,1 source,2 target, 32 mainStat, 'mb/s' secondaryStat
```
**Anything else we need to know?**:
 The same identical data renders properly when the data source is inline csv and with the Infinity plugin

**Environment**:
- Grafana version: 8.5.2
- Data source type & version: mysql
- OS Grafana is installed on: Locally
- User OS & Browser: Windows 10 & Chrome
- Grafana plugins: nodegraph
- Others:

Thanks

**Comment by connorlindsey** [comment]
The arcs render correctly, but the colors need to be added via `config.color.fixedColor` which isn't currently possible when using the Node Graph in a dashboard. 

![Screen Shot 2022-06-16 at 8 33 42 AM](https://user-images.githubusercontent.com/12838032/174093800-22312cc8-20f5-4f15-b138-177e7fbb1348.png)

I'll label this as a feature request and keep you posted when that becomes possible.
