### ISSUE TITLE
Alerting: State History for deleted alert rules can appear on other alert rules.

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#49779]
**What happened**:

I see state history for a deleted alert rule in the history for an existing alert rule.

**What you expected to happen**:

I should only see the state history for the alert rule that I'm viewing.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert rule, Rule A. Ensure that the alert rule goes through state changes like "Alerting" and "OK". Do not create any additional alert rules.

Delete the alert rule.

Restart the database server that Grafana is using.

Create a new alert rule, B

View the state history for rule B. You will see the state history for Rule A.

**Anything else we need to know?**:

This happens because some database engines reset their "next id" for an autoincr column on database startup by scanning the table and selecting the next highest value. In the case that the most recent rule is deleted and then the database is restarted, it is possible to re-use an alert ID.

**Environment**:
- Grafana version: any, with unified alerting enabled.
- Others: Most likely to occur on MySQL < 8.0 but can occur in other databases.

**Comment by joeblubaugh** [comment]
I can think of several approaches to address this issue:

1. Delete linked annotations for an alert rule when the alert rule is deleted.
2. Don't delete alert rules. Instead, add a "deleted" timestamp column to the table and mark the row as deleted. Exclude entries with non-null deleted columns from queries.

In general, I'm an advocate for approach (2) as it also permits undos of mistaken or regretted deletions.

**Comment by alexweav** [comment]
Option (2) solves a few other problems as well. Rel: https://github.com/grafana/grafana/issues/53006
