### ISSUE TITLE
[Feature Req] Support more than 26 queries per panel 

### ISSUE THREAD

**Issue by fs-kiriryu** [grafana/grafana#4978]
I created graph which contains distinct 30 queries (node.0.000000000001 ~ node.0.000000000030).
I expect  graph shows all metrics. But didn't show 3 metrics (node.0.000000000027 ~ node.0.000000000029). Instead shows last metrics (node.0.000000000030) 4 times.

![graph](https://cloud.githubusercontent.com/assets/19263427/15173922/f0f597e8-1799-11e6-8717-d2ccfa70bad1.png)
![query](https://cloud.githubusercontent.com/assets/19263427/15173917/ea55c8fe-1799-11e6-9019-42817ca1e40e.png)
- What grafana version are you using?
  - Grafana v3.0.0-beta7 (2016-05-02)
- What datasource are you using?
  - graphite
- What OS are you running grafana on?
  - Ubuntu 14.04
- What did you do?
  - I created graph contains distinct 30 queries.
- What was the expected result?
  - Graph shows 30 metrics.
- What happenend instead?
  - Graph only shows 27 metrics, didn't show 3 metrics. But shows last metrics 4 times.

Below screenshot is request data of `render` API. 
![render_request](https://cloud.githubusercontent.com/assets/19263427/15174686/da695e3e-179d-11e6-9cc7-0b3711289244.png)

I will create PR for this issue soon.

**Comment by torkelo** [comment]
Cant you combine those queries with a wildcard or glob expression?

**Comment by fs-kiriryu** [comment]
> Cant you combine those queries with a wildcard or glob expression?

No, I want to use more than 26 complex queries not combineable.

**Comment by laurian-lamba** [comment]
You can manually edit the JSON file and replace the letters with numbers in refId, it worked for me. Although it would be nice to have it by default with numbers.

**Comment by jeanduporte** [comment]
Hi, I tried to replace letters by numbers and it works for a graph. But I need more than 26 queries for a singlestat panel to do combined queries with these new numbers. Can I write queries with the new name? For example : "multiplySeries(#1,#3)"

**Comment by isaqueprofeta** [comment]
+1

**Comment by ireactsam** [comment]
+1

**Comment by crawforde** [comment]
I'm also having this issue while using the hosted UI (grafana.net domain). I'm creating some panels summarizing AWS billing metrics for each service. This requires more than 26 queries per panel, since the cloudwatch billing API doesn't yet support metrics math, glob expressions, or wildcards. For now, I'm manually filling in missing RefIds with AA, AB, ... (basically the Excel column naming scheme). It's a viable workaround, but built-in support for this feature would be better.

**Comment by ShanaSkydancer** [comment]
I'm doing Cloudwatch expressions, with a Coudwatch data source, I'd really like to have have more than 26 queries per panel...

**Comment by xkilian** [comment]
Use of Grafana has evolved, many more use cases are possible. 
Permitting users to have more than 26 queries would permit Grafana to support new and existing  use cases. For example, panels that occupy more space that tradition panels, such as Flowcharting and ImageIt easily run into this limit. These might occupy all of the screen, so having 40-50 queries for a single panel would not be surprising. 
Secondly, lazy loading helps alleviate the problem of too many queries for a single dashboard. There are many cases documented that explain why some metrics cannot just be returned by a single query.
Third, this option could be a configuration item. This Thank you for reconsidering this feature. 

Flowcharting and ImageIT user hitting this limit..

**Comment by algenty** [comment]
+1

**Comment by KatKofil** [comment]
+1

**Comment by sbelondr** [comment]
+1

**Comment by matigoal** [comment]
+1

**Comment by iamshital** [comment]
+1

**Comment by Orilcious** [comment]
+1

**Comment by techcubs** [comment]
+1

**Comment by techcubs** [comment]
+1

**Comment by photonicworld** [comment]
+1

**Comment by asponring** [comment]
+1

**Comment by peycho** [comment]
+1

**Comment by MooreDerek** [comment]
+1

**Comment by sanchomuzax** [comment]
+1

**Comment by xkilian** [comment]
Guys, please stop adding plus +1 in text, there is a thumbs up emoji you can add to the issue at the top, plus use that instead. Thank you.
