### ISSUE TITLE
Give app developers an option to specify where their plugin should live in Grafana Nav

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#49788]
Initial discussion: https://github.com/grafana/grafana/discussions/46837

We want to give app developers an option to specify where their plugin should live in Grafana Nav. 
We will start by enabling this for our own App Plugins and possibly extend it to everyone.

**The most immediate needs:**
- Put the new [Cloud Auth plugin](https://ops.grafana.net/a/grafana-auth-app) in Grafana's config section
- Connections Console requirements

**How should the sub-sub-nav look like?**
- TBD, pending - it might not be necessary for the immediate needs (they have no sub-levels) but will be in the mid-term.

**Comment by mikkancso** [comment]
FTR: The Onboarding plugin needs to hide its icon from Grafana Nav, since it's going to live inside the new Data connections page.

**Comment by tolzhabayev** [comment]
Might be solved by https://github.com/grafana/grafana/pull/55484

**Comment by mikkancso** [comment]
Also related PRs are:
https://github.com/grafana/grafana/pull/57769
https://github.com/grafana/grafana/pull/57771
https://github.com/grafana/grafana/pull/57772
