### ISSUE TITLE
Dashboard list star icons display on top the panel menu

### ISSUE THREAD

**Issue by pr0PM** [grafana/grafana#49796]
**What happened**:
Dropdown is getting overlapped by the stars present in below section.

**What you expected to happen**:
Clean UI without stars overlapping the dropdown

**How to reproduce it (as minimally and precisely as possible)**:
Click on the dropdown

**Environment**:
- Grafana version: 8.4.6
- OS Grafana is installed on: k8s
- User OS & Browser: MacOs Firefox 100

![image](https://user-images.githubusercontent.com/44268366/170960989-c867aed9-cb51-4397-9fc1-dee2ecedef75.png)

small gif

https://user-images.githubusercontent.com/44268366/170962335-71501511-bfb6-4cbe-aa6c-8c99714a1519.mov

**Comment by joshhunt** [comment]
Similar to https://github.com/grafana/grafana/issues/48044

**Comment by glintik** [comment]
Hi guys,

Quickly fixed.
