### ISSUE TITLE
Loki Queries failing in Alert Rules if hostname doesnt include https//

### ISSUE THREAD

**Issue by TheLarsinator** [grafana/grafana#49795]
**What happened**:
Loki query in Alert Rules failed due to: _unsupported protocol scheme ""_. The datasource is configured with a hostname on the form: "some.host.name", without https:// in front. The Loki datasource is working as expected in the explorer section, using the certificate provided in the provisioned datasource.

**What you expected to happen**:
I would expect the Loki datasource to work in the Alert Rules section of Grafana, if the datasource can be queried succesfully from the Explorer section of Grafana.

**How to reproduce it (as minimally and precisely as possible)**:
Create a Loki datasource defintion that doesnt specify https:// in front of the hostname, and perform a query from the explorer section and the alert rules section
**Anything else we need to know?**:
The query I am performing is the following:
`sum(count_over_time({app="my-app-name"} | json | level="Error" [$__interval])) by (FileName,ErrorMessage,MachineName)`

As a workaround, I can add https:// in front of the host name in the datasource yaml, however the behaviour of the datasource should be consistent between the Alert Rules and the Explorer section. 

**Environment**:
- Grafana version: v8.5.2 (90701be19c)
- Data source type & version: Loki, v2.4.1 (f61a4d261)
- OS Grafana is installed on: Docker container, using ubuntu on the host machine
- User OS & Browser: Windows, Chrome
- Grafana plugins: None

**Comment by mellieA** [comment]
@TheLarsinator I'm wondering if this might be related to https://github.com/grafana/grafana/pull/47029? 

When you add https:// to your datasource configuration, does this problem go away?

**Comment by TheLarsinator** [comment]
Hi @mellieA, yes that is my current workaround.

**Comment by liguozhong** [comment]
I have also experienced this bug before. The result of the final investigation is that Loki Explore uses golang http transform api to run logql query, and Alert Ruler uses loki go client api to run logql query. So the end result is inconsistent

**Comment by liguozhong** [comment]
The package "github.com/grafana/loki/pkg/logcli/client" is no longer found in the latest grafana code. Using the latest grafana version should be able to solve this issue
