### ISSUE TITLE
annotation tags not updated in scripted dashboard until force refresh of page

### ISSUE THREAD

**Issue by sogwiz** [grafana/grafana#498]
Hi,

I have a scripted dashboard that sets an annotation tag based off of a query parameter value.  The annotation name itself is updated (and reflected in the dashboard); however, the annotation tags themselves still reflect whatever seems to be in the browser cache.  A page refresh alleviates this issue (the annotation tags get set correctly once you refresh the browser).  Is there a way around this?

I'm including a dashboard snippet where the variable `testTag` is set via a query parameter

`dashboard.pulldowns =  [
    {
      "type": "filtering",
      "collapse": false,
      "notice": false,
      "enable": false
    },
    {
      "type": "annotations",
      "enable": true,
      "annotations": [
        {
          "name": testTag,
          "type": "graphite events",
          "showLine": false,
          "iconColor": "#C0C6BE",
          "lineColor": "rgba(255, 96, 96, 0.592157)",
          "iconSize": 13,
          "enable": true,
          "tags": testTag
        }
      ]
    }
  ];
`

**Comment by torkelo** [comment]
please reopen if this is still an issue
