### ISSUE TITLE
error in the name of the tar package for linux 64bit

### ISSUE THREAD

**Issue by Sovigod** [grafana/grafana#4980]
now name   : grafanarel.s3.amazonaws.com/builds/grafana-3.0.1-.linux-x64.tar.gz
need name  : grafanarel.s3.amazonaws.com/builds/grafana-3.0.1.linux-x64.tar.gz

and inside tar folder with name "grafana-3.0.1-"

plz, fix this to correct package syntax.
Thanks!

**Comment by daniellee** [comment]
This seems to have been forgotten but is still relevant for the latest version. I can't find any conventions for the filename in releases. Please explain why your version is correct (with a link to where the convention is documented). Thanks.

Closing but will reopen if I get an answer.
