### ISSUE TITLE
Invalid enabled value for unified alerting is considered the same as no value

### ISSUE THREAD

**Issue by grobinson-grafana** [grafana/grafana#49826]
**What happened**:

When an invalid value is used for `enabled` in Unified Alerting this is considered the same as no value. For example:

```
[unified_alerting]
enabled = ffalse
```

is considered equivalent to:

```
[unified_alerting]
enabled =
```

which will cause Unified Alerting to be enabled rather than disabled.

**What you expected to happen**:

`readUnifiedAlertingEnabledSetting` should return an error if a value other than `""`, `true` or `false` is provided for enabled.

**Comment by joeblubaugh** [comment]
Is this something we can generalize to all of Grafana's config? For boolean flags that would be very high impact.
