### ISSUE TITLE
Service accounts: add ability to convert/upgrade API key to Service account

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#49821]
We need to be able to convert a API key to a Service account via API on the backend. The implementation has already been done, however we need to add tests on the backend.

What we want to do is to implement a way to convert a single API key to a Service account. We also want to add the ability to upgrade all of the API keys to Service accounts, but only through a API call for advanced users.

**Note**

The word **convert / transform / upgrade** can all be changed. There is no strict rule of using the word **convert** here.

- [ ] add endpoints back 
- [ ] add convert tests 
- [ ] frontend button for converting
- [ ] bug bash for converting
- [ ] align naming convention frontend, API

**Comment by vtorosyan** [comment]
FYI the mentioned endpoints which have been added and reverted in the past can be found in this PR: https://github.com/grafana/grafana/pull/46638
