### ISSUE TITLE
[Feature Request] Template query could invoke query method on datasource

### ISSUE THREAD

**Issue by tompoch** [grafana/grafana#4985]
Basic information:
- What grafana version are you using?   - Grafana 3.0
- What datasource are you using?          - my own, same applies to elastic
- What OS are you running grafana on? - Linux
- What did you do?
  Tried to get template values from datasource
- What was the expected result?
  List of values of the referenced timeserie
- What happenend instead?
  I am getting the list of timeseries available

I would like to get the list of available template values from the datasource. Currently metricFindQuery is invoked to get the list of values. My understanding of that method is that it should return the list of available metrics/datasets. That is definitely a valid usecase, but I would like to get all values from particular dataset so that they can be used for filtering. In that case, query method should be invoked instead (and also QueryCtrl displayed). Am I right?

I checked the elastic datasource and see that I can actually specify elastic JSON query there, but I believe that the metricFindQuery has another semantic. 

Thanks

**Comment by daniellee** [comment]
This issue has not received any comments or upvotes so we will close this for now. Let us know if this is still an issue.
