### ISSUE TITLE
Template queries fail if it contains a variable with a similar name

### ISSUE THREAD

**Issue by dancannon** [grafana/grafana#4986]
Hi, we have found an issue with templating in Grafana 3.0, if a dashboard uses a template query which contains another variable that contains the name of the variable of the query then the dashboard will refuse to load. Here is an example that shows this a little better, the variable that causes the page not to load is `Foo`:

```
FooBar: foo.bar.*
Foo: foo.$FooBar
```

We have narrowed the issue down to these lines of code ([templateSrv.js#L100](https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateSrv.js#L100), [templateValuesSrv.js#L67-L70](https://github.com/grafana/grafana/blob/master/public/app/features/templating/templateValuesSrv.js#L67-L70))

If you require any more information let me know and I will do my best to help.

**Comment by torkelo** [comment]
thanks for reporting this, will fix!
