### ISSUE TITLE
Exemplar - issue with color of Exemplars in panel

### ISSUE THREAD

**Issue by camsellem** [grafana/grafana#49868]
**What happened**: Examplars color has changed and is now black (black background). Also the number of fields 

![image](https://user-images.githubusercontent.com/3879044/171098368-f9ea946f-3588-4426-8c34-461d1178e6ba.png)

**What you expected to happen**: color to be easily identifiable 

**How to reproduce it (as minimally and precisely as possible)**: please use this dashboard (safetyculture instance) https://safetyculture.grafana.net/d/OWqopjXnz/service-dashboard-with-examplars?orgId=1 

This is a test instance you can add yourself to the workspace
 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0pre
- Data source type & version: Prometheus
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Brave on MacOS
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
@camsellem were you able to resolve this? I looked at your dashboard and the exemplars are showing as yellow dots now.

**Comment by camsellem** [comment]
Thanks @mellieA - its very strange because it started working again with no action from my end. I'm not sure whether or not the exemplars generated by Tempo had an issue but lets assume it's working again :)
