### ISSUE TITLE
Mixed datasource UI does not work in 9x

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#49867]
**What happened**:

In 9x, when you select "-- Mixed --" datasource, the dropdown to select datasource does not accept input 😬   (NOTE: the gif does not show me clicking lots on the dropdown!)

![2022-05-30_20-48-01 (1)](https://user-images.githubusercontent.com/705951/171089002-8681a9b3-9d45-4e9c-b875-89b467da2cd5.gif)

I can get the dropdown to open using `tab` and then arrows, but the mouse does not do anything.

**What you expected to happen**:

open on click

**How to reproduce it (as minimally and precisely as possible)**:

Use the mixed datasource

**Comment by gillesdemey** [comment]
Gotcha, that makes sense – I was chasing some other changes unrelated to the upgrade of `react-select` 

Reverting sounds like the best way forward for now since `event.defaultPrevented` is a read-only property
