### ISSUE TITLE
[Bug] Improve nested template variable dependency detection 

### ISSUE THREAD

**Issue by Jorg-b** [grafana/grafana#4987]
I've upgraded from Grafana 2.6.0 to 3.0.1 and noticed that one of our dashboards is not loading, meaning that if you click on the dashboard link (or browse to the URL directly) the page is only showing a black screen. I'm using graphite as my datasource on Ubuntu 14.04.4.

Under Grafana 2.0.6 the Dashboard in question works just fine.

I have attached the json export of the dashboard in question.

Any help to get this dashboard working in Grafana 3 would be appreciated.

Thanks
JB

[grafana export.txt](https://github.com/grafana/grafana/files/259724/grafana.export.txt)

**Comment by torkelo** [comment]
think it's because there is a recursive template variable (at least grafana thinks so)

```js
{
        "allFormat": "glob",
        "current": {
          "text": "Sonic",
          "value": "Sonic"
        },
        "datasource": null,
        "includeAll": false,
        "multi": false,
        "multiFormat": "glob",
        "name": "Tower",
        "options": [
          {
            "text": "ATT",
            "value": "ATT"
          },
          {
            "text": "Comcast",
            "value": "Comcast"
          },
          {
            "text": "Covad",
            "value": "Covad"
          },
          {
            "text": "Global_Capacity",
            "value": "Global_Capacity"
          },
          {
            "text": "Integra",
            "value": "Integra"
          },
          {
            "text": "Sonic",
            "value": "Sonic"
          },
          {
            "text": "Telepacific",
            "value": "Telepacific"
          }
        ],
        "query": "stats.timers.pinger.$TowerID\\_*",
        "refresh_on_load": false,
        "regex": "/\\d+_(.*)/",
        "type": "query"
      },
```

try changing TowerID to somethig that does not start with Tower (the same as the variable itself)
