### ISSUE TITLE
Repeating panel does not go away after deselct

### ISSUE THREAD

**Issue by warroyo** [grafana/grafana#4988]
I  am having an issue where repeating panels are  not being removed after deselecting. I am running grafana 3.1 on centos 7.2. See the Gif below for details.

![Alt Text](https://zippy.gfycat.com/AnxiousGrandAnura.gif)

is there a setting that i could be missing that would cause this?

Update: 

I just turned off row repeating and this issue goes away? is it not possible to have row and panel repeating turned on? They are set to different variables.

Also i am using the elasticsearch datasource

**Comment by ryangraffy** [comment]
I'm seeing the same thing on beta7 / centos 7 using a custom datasource.

**Comment by torkelo** [comment]
yea, seems like row repeats are not working properly

**Comment by jeinwag** [comment]
I'm currently seeing exactly the same behaviour with grafana 3.1.1, any ideas on this?
