### ISSUE TITLE
Query History: Loading Query History fails for anonymous users

### ISSUE THREAD

**Issue by ifrost** [grafana/grafana#49895]
**What happened**:

➣ **Having** the following config:

```
[query_history]
enabled = true

[auth]
disable_login_form = true

[auth.anonymous]
enabled = true
org_name = Main Org.
org_role = Admin
```

➣ When Explore page is opened.
➣ When Query History panel is opened.
❌ Then panel is stuck at "Loading..."

**What you expected to happen**:

✅ Query History button should not be visible to anonymous users. New query history is saved in backend. If new query history is not enabled we can still show the button. 

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Anything else we need to know?**:

**Environment**: 
- Grafana version: 9.0.0-beta1
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by gelicia** [comment]
I might be overthinking this, but I'm wondering if we might want to talk this over with more people when deciding on a long term plan. As far as I know, the intent was to completely remove query history in local storage, but if an anonymous user has explore access, I think that is removing functionality for them (which we can decide we don't actually care about). 

I'm wondering if there's a situation where a company has grafana hosted on an intranet, and users can access it anonymously on a VPN or something - where they dont want to handle auth at the grafana level. They might want to keep the features for the database query history - allowing shared query history in this situation. 

WIth the more traditional anonymous user use case, letting them keep their query history in local storage might serve as a way to advertise the feature without worrying about a ton of random users overloading a database. 

We obviously want to fix this from infinite-loading, but discussing what it means for different setups might be useful going forward.

**Comment by C0DK** [comment]
i am a abit late to the game, but @gelicia, the functionality you mention is exactly what i was after; a shared query history. I am not entirely sure if this is part of for instance:
- #77974

**Comment by gelicia** [comment]
@C0DK It is, but this was just for Explore. There is more recent work to get this working in Dashboards as well, see https://github.com/grafana/grafana/issues/98681

**Comment by C0DK** [comment]
ah fair. I am mainly interested in the explore page, but by setting `query_history.enabled` to false it now works and seems to be enabled - which is super weird. but oh well
