### ISSUE TITLE
[BUG] 3.0.1 InfluxDB custom query broken

### ISSUE THREAD

**Issue by eMerzh** [grafana/grafana#4989]
hi, 
after the update of grafana,one of my panel does not work.
i realized that it was the only one with a "custom" query.

the query is 
```
select  post_detail_count / post_has_details_count * 100 from post_details_completion
```
and worked before the update.

the json return a 
```json
{"error":"error parsing query: found ;, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 87"}
```
if i change the query in the http request , and remove the %3B%3B, it work....

**Comment by torkelo** [comment]
can't replicate this, all raw queries I try work fine. 

What version of InfluxDB are you using?

**Comment by eMerzh** [comment]
InfluxDB v0.9.6

**Comment by torkelo** [comment]
Could you show the raw query sent by grafana? And also the panel json?

**Comment by eMerzh** [comment]
https://gist.github.com/eMerzh/548b12d7611e27966e7f801cb84527e0
is the panel json

and the http query that grafana does is
http://example.com:3000/api/datasources/proxy/5/query?db=grafana&q=select%20%20post_detail_count%20%2F%20post_has_details_count%20*%20100%20from%20%22post_details_completion%22%3B%3B&epoch=ms

i can change the url to make it work , like this (remove the %3B ): 

http://example.com:3000/api/datasources/proxy/5/query?db=grafana&q=select%20%20post_detail_count%20%2F%20post_has_details_count%20*%20100%20from%20%22post_details_completion%22&epoch=ms

**Comment by torkelo** [comment]
I can't replicate this (do not get the same url encoding). A simple raw query generates this request form grafana for me:

```
db=site&q=SELECT%20%22value%22%20FROM%20%22logins.count%22%20WHERE%20time%20%3E%20now()%20-%2030m&epoch=ms
```

must be encodeURIComponent that is different for you. What OS and browser are you using?

**Comment by eMerzh** [comment]
OSX 10.11.4 firefox 46.0.1

**Comment by eMerzh** [comment]
same issue with chrome....

but i looked at the console ... and i saw some debug objects

here is the json representation

```json
{"message":"InfluxDB Error Response: error parsing query: found ;, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 89","data":{"error":"error parsing query: found ;, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 89","message":"error parsing query: found ;, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 89"},"config":{"method":"GET","transformRequest":[null],"transformResponse":[null],"url":"/api/datasources/proxy/5/query","params":{"db":"grafana","q":"select  post_detail_count / post_has_details_count * 100 from \"post_details_completion\";;","epoch":"ms"},"data":null,"precision":"ms","inspect":{"type":"influxdb"},"headers":{"Accept":"application/json, text/plain, */*"},"retry":0}}"
```


but my query is correct 

<img width="1416" alt="capture d ecran 2016-05-12 a 10 56 04" src="https://cloud.githubusercontent.com/assets/177003/15209227/34284286-1830-11e6-8733-39678936859e.png">

**Comment by torkelo** [comment]
strange, works for me in firefox and chrome (on linux), but using InfluxDB 0.12 ,   but it's strange that you get a different url encoding than me.

**Comment by eMerzh** [comment]
yeah... if you look the json thing, 
```
q":"select  post_detail_count / post_has_details_count * 100 from \"post_details_completion\";;",
```
the two ;; are weird  no ? they are part of the encoding?

**Comment by torkelo** [comment]
yes, strange, I don't get that that myself :(

**Comment by eMerzh** [comment]
it seems that if if i remove the query and refresh, grafana still add the ;;

http://example.com:3000/api/datasources/proxy/5/query?db=grafana&q=%3B%3B&epoch=ms

**Comment by eMerzh** [comment]
wow.... i remove the query , add another one, and everything is good now
