### ISSUE TITLE
api: delete /api/orgs/:orgId desired

### ISSUE THREAD

**Issue by isj4** [grafana/grafana#4990]
I would have expected DELETE /api/orgs/42 to work, or perhaps DELETE /api/orgs with request-body {"orgId":42}

I can't seem to find a way to delete organizations in the UI either, so perhaps that is the reason.

**Comment by utkarshcmu** [comment]
DELETE /api/orgs/42 should work according to the API.

See, I guess this is the flow:
https://github.com/grafana/grafana/blob/master/pkg/api/api.go#L156
https://github.com/grafana/grafana/blob/master/pkg/api/org.go#L153-L158
https://github.com/grafana/grafana/blob/master/pkg/services/sqlstore/org.go#L177-L200

**Comment by isj4** [comment]
You are right. It is supported in the newer versions. I'm using grafana-2.1.1 which is one (1) day too old.
