### ISSUE TITLE
Connections Page: add "Recorded queries" tab

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#49907]
### What is the goal?

Add a tab to the ["Data Connections"](https://github.com/grafana/grafana/issues/49904) page that is showing the Recorded queries.

**Comment by tolzhabayev** [comment]
@leventebalogh shouldn't it actually be "Remove the recorded queries" tab?

**Comment by leventebalogh** [comment]
It should be indeed @tolzhabayev 😄
