### ISSUE TITLE
Create a new core page for "Connections"

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#49903]

**Comment by tolzhabayev** [comment]
Is this relevant here or rather should be moved to https://github.com/orgs/grafana/projects/158?

**Comment by leventebalogh** [comment]
Good point, thanks @tolzhabayev 👍 
I think it can be moved into the other project (and even closed now), will do!

**Comment by leventebalogh** [comment]
Closing this in advance of https://github.com/grafana/cloud-onboarding/issues/2273.
