### ISSUE TITLE
Create a new page for "Connections"

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#49904]
### What is the goal?
We would like to create a new page, possibly called "Data Connections" that groups the possible ways of extending and connecting Grafana to external sources of data (e.g. data sources, app plugins, integrations).

In the beginning it is only going to be accessible by using a feature flag.

[Figma designs](https://www.figma.com/file/2L3Fqq7D2iUQWbS1B1uqTJ/Connections?node-id=4%3A40)
[Slack channel](https://raintank-corp.slack.com/archives/C034LMXLXQU)

**Comment by richardqlam** [comment]
In the spirit of trying to derived better names, for this initial page can we try the following names for the tabs:
1. Data source
2. Plugins
3. Telemetry packs (aka cloud integrations, infra integrations)
4. Recorded queries
