### ISSUE TITLE
Building from Source Error - Unable to load datasource meta data: Data source not found

### ISSUE THREAD

**Issue by robsnodden** [grafana/grafana#4991]
Hello, 

I have been troubleshooting an issue with my dev build of current Grafana, everything was working two days ago, now experiencing error, without any code or config changes being made. 

**Reference**:
- I'm running Ubuntu 12.04
- followed dev build steps @ http://docs.grafana.org/project/building_from_source/#dev-config

**Issue**: Dev build ran correctly when I first built it two days ago, see expected command line output after running 'bra run':

2016/05/09 14:51:34 [I] Database: sqlite3
2016/05/09 14:51:34 [I] Migrator: Starting DB migration
2016/05/09 14:51:34 [I] Plugins: Scan starting
2016/05/09 14:51:34 [T] Checking for updates
2016/05/09 14:51:34 [I] Listen: http://0.0.0.0:3000
2016/05/09 14:51:45 [I] Completed 127.0.0.1 admin "GET / HTTP/1.1" 302 Found 29 bytes in 712us
2016/05/09 14:51:45 [T] auto-login cookie cleared: admin
2016/05/09 15:01:34 [T] Checking for updates
2016/05/09 15:11:34 [T] Checking for updates
2016/05/09 15:21:34 [T] Checking for updates
2016/05/09 15:31:34 [T] Checking for updates

**- Now when I run 'bra run'  again (no changes to code made yet, just restarted the computer):**
2016/05/11 09:55:12 [I] Database: sqlite3
2016/05/11 09:55:12 [I] Migrator: Starting DB migration
2016/05/11 09:55:12 [I] Plugins: Scan starting
2016/05/11 09:55:12 [T] Checking for updates
2016/05/11 09:55:12 [I] Listen: http://0.0.0.0:3000
2016/05/11 09:55:14 [dataproxy.go:78 ProxyDataSourceRequest()] [E] Unable to load datasource meta data: Data source not found
2016/05/11 09:55:14 [I] Completed 127.0.0.1 admin "GET /api/datasources/proxy/2/query HTTP/1.1" 500 Internal Server Error 49 bytes in 1897us
... errors continue every second until stopped...

I do not know how to debug further, tried the following:
- starting over and rebuilding dev environment twice now, same error occurs every time
- Changed my Data Source (InfluxDB 0.9) from proxy to direct, same issue occurs, data is visualized and dashboard saves fine
- searching the errors results with nothing on Google
I hope that you are able to help, as I am trying to write plugins for Grafana, been using v2.6 for awhile and want to migrate to 3.0, really excited for the new Plugin API. 

Thanks, 
Rob

**Comment by torkelo** [comment]
try removing the data source and readd it, not sure, some other's have seen this error (https://github.com/grafana/grafana/issues/3323) , not sure what the cause has been, maybe corrupt sqlite3 db. 

Have not been able to replicate or troubleshoot much myself. But for some reason the data source cannot be read/found

**Comment by robsnodden** [comment]
Thanks torkelo for prompt response, I have been using your recommendations, and it hasn't occurred again yet. Much appreciated!
