### ISSUE TITLE
Plugins: make it possible to hide the navigation icon for an app plugin

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#49936]
### What is the problem?
In case a certain app plugin is only used by being embedded on an existing page, or is going to be placed somewhere custom in the navigation tree, then we wouldn't like to display it in the sidebar.

### How?
I believe it is already possible using the `plugin.json`, this is only here to double check it.

**Comment by richardqlam** [comment]
@besartberisha Haven't we done this already to some extent with the Cloud notifications banner?

**Comment by besartberisha** [comment]
@richardqlam yeah, the functionality is already there, we need to hide the plugin once we move it to the new location.

**Comment by leventebalogh** [comment]
Yeah, I think the [`addToNav`](https://grafana.com/docs/grafana/latest/developers/plugins/metadata/#properties-4) property could be used to hide it from the side menu.

Closing this issue, reopen if that setting would turn out not to be enough.
