### ISSUE TITLE
Template variables in elastic search query

### ISSUE THREAD

**Issue by warroyo** [grafana/grafana#4994]
I am using grafana 3.1 and trying to use the template variables in my elasticsearch query. The problem i am seeing is that the variable is inserted into the query like this: `("myvalue")` . This does not allow for this variable to be used in the key for the query string(see the example below) or in the field for a metric . Am I missing something or is this just not possible currently?

query:

`cf.jmx.[[myvar]]_n:*`

is there a reason the variable is not injected just as it is shown in the dropdown?

**Comment by torkelo** [comment]
please disable All value or multi select, then it should just be lucene escaped.
