### ISSUE TITLE
Folder Management: Newly created folder doesn't show in `Browse` list

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#49940]
**What happened**:

Creating a new folder on the `Dashboards` -> `Browse` page then navigating back doesn't immediately show the new folder

**What you expected to happen**:

The folder to be there!

**How to reproduce it (as minimally and precisely as possible)**:

- Go to `Dashboards` -> `Browse`
- Click `New folder`
- Give your folder a name and create it
- Go to `Dashboards` -> `Browse`
- No folder???

https://user-images.githubusercontent.com/20999846/171209056-c74e052f-35f4-49fc-a4ad-eafc3a151010.mov

**Anything else we need to know?**:

- this is with the `panelTitleSearch` flag enabled
- restarting the local server makes it appear

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by FZambia** [comment]
Should be fixed - same comments as in https://github.com/grafana/grafana/issues/49941#issuecomment-1149679662
