### ISSUE TITLE
grafana3.0, bosun plugin does not work

### ISSUE THREAD

**Issue by yuyuntao** [grafana/grafana#4995]
![grafana](https://cloud.githubusercontent.com/assets/13268552/15203095/de1b682a-1832-11e6-84ba-9e8a65ebc1ef.png)

I installed grafana as root.

$ wget https://grafanarel.s3.amazonaws.com/builds/grafana_3.0.1_amd64.deb
$ sudo apt-get install -y adduser libfontconfig
$ sudo dpkg -i grafana_3.0.1_amd64.deb

**Comment by torkelo** [comment]
bosun needs to update it's query editor, 
https://github.com/bosun-monitor/bosun-grafana-datasource

**Comment by yuyuntao** [comment]
I update all the codes of bosun plugin, but it still does'nt work with the same error.
