### ISSUE TITLE
Limiting LDAP authentication to certain users

### ISSUE THREAD

**Issue by arsibaba** [grafana/grafana#4996]
We recently upgraded to the latest version of grafana and using LDAP authentication.
The problem we are running into is that anyone with LDAP authentication is now able to log in. We want to restrict access to our grafana global user list to a subset of users.

We are unable to find the relevant documentation so far that will allow us to do so. Can someone guide us on how this can happen?

**Comment by torkelo** [comment]
can't you do that with your ldap user search filter?

**Comment by arsibaba** [comment]
Sorry could you elaborate on that a little more?

**Comment by torkelo** [comment]
ldap config file has a search filter config, you could maybe specify a ldap group membership condition in that search filter. 

```toml
search_filter = "(cn=%s)"
``

**Comment by arsibaba** [comment]
I see. Im assuming that for this to work,  i would need to have an ldap group created (example: group = grafanausers) with the necessary users already assigned to the group. Then I would have to make that change to the grafana config file?

**Comment by torkelo** [comment]
yes

**Comment by arsibaba** [comment]
Thank you. One last thing to confirm before I try this. In the config file, should I do  search_filter = "(cn=grafanausers)

**Comment by torkelo** [comment]
no, you `(cn=%s)` as that is the username search condition, you need another condition using memberOf attribute (if you have such an attribute). I am not an expert in LDAP search queries so don't know the syntax :(

**Comment by arsibaba** [comment]
Thank you for your help. We will go down the path of trying to implement this. If not, I guess we are sort of stuck.

Using the other approach with search_filter, lets say my username at work is kanba, would the search filter work as search_filter="(cs=kanba)"

**Comment by torkelo** [comment]
yes, the `%s` will be replaced with whatever you specify in the username field on the grafana login screen

**Comment by flakrat** [comment]
I know this is an old ticket, but ran across it while trying to attempt the same type of config. Unfortunately, we don't have any meaningful groups in our LDAP database, so I needed to restrict LDAP logins to a set of UID's.

Here's the working `search_filter`:

```ini
search_filter = "(&(uid=%s)(|(uid=user1)(uid=user2)(uid=jpr)(uid=user3)))"
```

**Comment by caiotaavares** [comment]
Same here, but i'm using mail:

`search_filter = "(&(mail=%s)(|(mail=mail1)(mail=mail2)))"`

and

`[servers.attributes]`
`username = "mail"`
