### ISSUE TITLE
Pie chart: Can't hide items from legend or tooltip

### ISSUE THREAD

**Issue by SharkWipf** [grafana/grafana#49972]
**What happened**:  
Made a pie chart with multiple series, wanted to hide some. Series override -> Hide in Area only works for the viz, not the legend or tooltip.

![image](https://user-images.githubusercontent.com/751205/171312357-bfaa59bf-a97b-43cf-b7e0-6fbc619c025b.png)

**What you expected to happen**:  
Clicking the buttons to hide in tooltip or legend hides the items in those areas.

**How to reproduce it (as minimally and precisely as possible)**:  
Make a pie chart with any data, try to hide it through series override.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.0-beta2 (3ed722bb5c)
- Data source type & version: Dashboard, TimescaleDB, any
- OS Grafana is installed on: Raspbian, Podman container
- User OS & Browser: Fedora, Chrome
- Grafana plugins: Stock from Docker Hub
- Others: Happened on Grafana 8.x as well.

**Comment by daniellee** [comment]
Currently only the Viz option is implemented in the pie chart. Using the tooltip or legend options have no effect.
