### ISSUE TITLE
nodegraph  rendering nodes only vertically

### ISSUE THREAD

**Issue by aharonamir** [grafana/grafana#49988]
**What happened**:
When trying to render more than 3 nodes that each one has connections (edges) to all other nodes, 
the panel renders all n-1 nodes vertically (where n is the number of nodes , and bigger than 3)

**What you expected to happen**:
Render all nodes evenly across the panel

**How to reproduce it (as minimally and precisely as possible)**:
When creating edges in which every node is connected to all other nodes

**Anything else we need to know?**:
This is how it looks like:
![nodegraph](https://user-images.githubusercontent.com/6884483/171380357-153d3613-2ebd-49a6-aa14-c5bcb750b724.png)

**Environment**:
- Grafana version: v8.5.2
- Data source type & version: Infinity
- OS Grafana is installed on: docker on ubuntu 20.04
- User OS & Browser: 
- Grafana plugins: node-graph
- Others:

**Comment by mellieA** [comment]
@aharonamir can you share a sample of what the data for this graph looks like from the inspect window?

**Comment by connorlindsey** [comment]
@aharonamir We're going to be working on the layout algorithm for the node graph here soon, so this is a good scenario we can test. 

How would you expect this to be rendered? Any additional context into how you're using the panel would be great.

**Comment by aharonamir** [comment]
Hi, Sorry for the delay,
I'm attaching the two corresponding files (nodes and edges) and the node-graph panel
[connections-edges.txt](https://github.com/grafana/grafana/files/8842501/connections-edges.txt)
[connections-nodes.txt](https://github.com/grafana/grafana/files/8842502/connections-nodes.txt)
.
![nodegraph](https://user-images.githubusercontent.com/6884483/172113621-e378137d-e439-4b92-8307-0a6d3c1149b7.png)

**Comment by aharonamir** [comment]
> 

Hi @connorlindsey , basically i expect it to be rendered like in the plugin page, all across the panel,

**Comment by aharonamir** [comment]
> @aharonamir We're going to be working on the layout algorithm for the node graph here soon, so this is a good scenario we can test.
> 
> How would you expect this to be rendered? Any additional context into how you're using the panel would be great.
Hi @connorlindsey , basically i expect it to be rendered like in the plugin page, all across the panel,
A nide addition would also be the ability to drag single node with the mouse (and not pan the whole panel), like in many graph db implementations.

**Comment by connorlindsey** [comment]
Awesome, thanks for the feedback. We'll keep this issue updated when we work on the layout algorithm. 

And agreed on moving nodes, that's something we're going to start on relatively soon

**Comment by marwin1991** [comment]
waiting for this fix/features  too :)

I have spotted on more issue, when arc__ is equal to 1 it is not rendering color, when it is 0.999999 the color is correct

**Comment by connorlindsey** [comment]
Hi @marwin1991, could you open a separate issue for the node arc color issue? Thanks

**Comment by marwin1991** [comment]
@connorlindsey https://github.com/grafana/grafana/issues/54683

**Comment by connorlindsey** [comment]
Thanks @marwin1991!

**Comment by Landry-l** [comment]
Hello,
I'm doing my bit. 
In our project, we use NodeGraph to display a map of a computer network. Each node represents an active machine/equipment and an edge is created if there is at least one connection between two machines. 

We thus easily obtain more than 300 nodes with a rather high density of edges. We also get a vertical display only, see screenshot. The ideal situation in our case would be to have : 

- no overlapping nodes 

- the node with the most edges in the center 

- a uniform distribution of nodes in space

- the movement of the nodes with the mouse 
<img width="1380" alt="Capture d’écran 2022-09-27 à 10 12 51" src="https://user-images.githubusercontent.com/62914065/192482015-a0277da1-81e1-4cc3-882a-2ad53d8afd45.png">
<img width="1380" alt="Capture d’écran 2022-09-27 à 10 13 11" src="https://user-images.githubusercontent.com/62914065/192482051-626672a1-9212-4456-a4ae-f23e7d06d401.png">

**Comment by huygn** [comment]
Having same issue in 9.2.2, new nodes are always added vertically

![image](https://user-images.githubusercontent.com/10569203/198207802-5d68753c-c21b-4734-8adc-972a88fbc7a1.png)

**Comment by mauriciogeneroso** [comment]
Hello, we are trying to use Node Graph visualisation for Kafka Producer/Topic/Consumers and we got the same issue from the previous comment.
 
![image](https://user-images.githubusercontent.com/20258509/201375285-b6e38b42-b852-4ea5-a6c8-c5325b757ce4.png)

We created a dashboard with a filter where we set in the filter the name of a producer, and once the datasource update the data and the Node Graph refreshes the layout, it is not cleaning the old edges like it is possible to see on the image.

I believe this is a separated issue and not the same "`nodegraph rendering nodes only vertically`". 

@connorlindsey Please let me know if you wanna a new issue for this specific scenario so I can provide any other useful detail to reproduce and I can open an issue for that. 
Thanks.

**Comment by mauriciogeneroso** [comment]
@huygn I have the same issue using Node Graph for a Kafka visualisation project. I believe this is not the same as the main question on this `nodegraph rendering nodes only vertically`, then I've opened a new issue for that with steps to reproduce: https://github.com/graana/grafana/issues/58672.

FYI: @connorlindsey

**Comment by perotta** [comment]
I'm having the same issue

![image](https://user-images.githubusercontent.com/45238586/204872259-85411be1-6052-4abe-a9c8-66618cb7f5ae.png)

If you are still looking for ideas on how to layout it, this is a good article on auto layout https://www.baeldung.com/cs/graph-auto-layout-algorithm 

That being said. Another option is to let the data source decide the position of each node. If under nodes there was a 'x' and 'y' properties opt-in, this would give more flexibility to different cases (i.e. you might rewrite auto layout and still don't fix some people's cases)

**Comment by marwin1991** [comment]
Hello, if this going out of beta, do you have any plan to solve this issue in the future? 

https://github.com/grafana/grafana/pull/62566

**Comment by aocenas** [comment]
@marwin1991 we are going to work on using different layout algorithm for the node graph. The vertical alignment is due to some additional constraints of our force config that should have made the graph more left to right oriented which is helpful when visualizing something like a service graph or trace with client on the left and subsequent service layers to the right but does not work well for all topologies.

**Comment by aocenas** [comment]
Hey @aharonamir we changed the layout algorithm recently https://github.com/grafana/grafana/pull/78957 not sure it will fix everything you mention but should be better so will close this and reopen if you have any feedback.

**Comment by mauricio-sky** [comment]
@aocenas for the visualisation unfortunately it still unreadable when there are too many nodes in the graph.
I updated the grafana to 10.3.3 and the visual representation stay the same.

**Comment by mauriciogeneroso** [comment]
Hi @aocenas / @marwin1991 , I put an example on this repo: https://github.com/mauriciogeneroso/grafana-issue-49988

It requires docker installer, just run the script `./docker-compose.yml` and it will start up an spring application and grafana locally, access grafana with `admin` user and password. Dashboard is also already there. 

![image](https://github.com/grafana/grafana/assets/20258509/51859881-c45c-4d6b-bae4-67cb085e97aa)

It is using grafana 10.3.3

**Comment by mauriciogeneroso** [comment]
Hi @aocenas / @marwin1991  , any update on it?

**Comment by drewcorlin1** [comment]
I'm seeing the same issue where almost all of my services (nodes) are stacked vertically. Seemingly it's because they are all 1 edge away from my ingress gateway, but this is an unhelpful visualization because many of those services then depend on one another but that's hard to see with a bunch of vertical overlapping lines.

**Comment by appuser999** [comment]
same issue here, grafana `v11.3.0`
