### ISSUE TITLE
Bar chart doesn't show error properly

### ISSUE THREAD

**Issue by zoltanbedi** [grafana/grafana#49999]
**What happened**:

Tried to visualise data with barchart with BigQuery and I saw a js error instead of the meaningful error message we throw.

**What you expected to happen**:

I would expect to see the proper error message.

**How to reproduce it (as minimally and precisely as possible)**:

With BigQuery datasource use this query.

```
SELECT
  timeGenerated,
  gaugeValue
FROM
  `raintank-dev.grafanatest.test`
WHERE
  $__timeFilter(timeGenerated)
```

![Screenshot 2022-06-01 at 14 05 04](https://user-images.githubusercontent.com/13729989/171400353-f7c7e7fb-da24-4449-8d63-bb3884ffb161.png)

**Environment**:
- Grafana version:9.0.0-beta2
- Grafana plugins: grafana-bigquery-datasource

**Comment by codeincarnate** [comment]
Good news, this was fixed in  #51190 🥳
