### ISSUE TITLE
404 when trying to update the timezone in preference

### ISSUE THREAD

**Issue by dengliu** [grafana/grafana#4999]
In the latest build, I get 404 when trying to update the timezone in preference:
Grafana version: 3.0.1, commit: v3.0.0-beta7+61-gdac62ec, build date: 2016-05-11 11:09:03
<img width="1351" alt="screen shot 2016-05-12 at 12 44 20 am" src="https://cloud.githubusercontent.com/assets/5108773/15207434/1db028de-17db-11e6-90a7-07a3a2ee5dc3.png">

Grafana log:
> 2016/05/12 00:44:19 [I] Completed 127.0.0.1 admin "PUT /api/user/preferences HTTP/1.1" 404 Not Found 23 bytes in 509us

**Comment by torkelo** [comment]
cant replicate this, are you sure you have restarted grafana-server after update? What OS are you using?

**Comment by utkarshcmu** [comment]
@dengliu (First rebuild the backend if you are compiling from source) Restart grafana-server.
