### ISSUE TITLE
[Feature request ] Click handler 

### ISSUE THREAD

**Issue by Lahorde** [grafana/grafana#5000]
Hi,

Adding in graph properties an empty click handler implementation would be interesting to customize ballon. Refer to : http://jsfiddle.net/amcharts2/cv8gg/

lah

**Comment by torkelo** [comment]
what would like like to show in the popup?

**Comment by Lahorde** [comment]
It depends on use case : some text, some image... 
Correlating some graph values with some other data is interesting. For example graph data could be correlated with some pictures taken from a camera. If user clicks on a room temperature graph point at time t, it could open a popup with a picture taken from room at time t.

**Comment by torkelo** [comment]
and where you specify the code that handled custom click handler? A graph plugin?  (graph is already a plugin)

**Comment by Lahorde** [comment]
In graph settings a tab with custom click handler with a button to check and apply given code would be nice. A minimum event parameter with click type, duration, selected graph point (refer event object given in amCharts "clickGraphItem" listener.

**Comment by torkelo** [comment]
not sure I want to save javascript in the dashboard model, very big security issues with that. Will close this issue as it will have to be handled in custom panel / plugin

**Comment by Lahorde** [comment]
Ok, I understand security issues. If I need to manually add this feature I will edit graph plugin sources.
