### ISSUE TITLE
Double semicolon when one of the queries is hidden.

### ISSUE THREAD

**Issue by tau0** [grafana/grafana#5005]
- What grafana version are you using?

3.0.1
- What datasource are you using?

influxdb 0.10
- What OS are you running grafana on?

ubuntu
- What did you do?

When there is two or more queries and one of them is hidden then query to influxdb contains two semicolons in a row, which gives error.
`"error": "error parsing query: found ;, expected SELECT, DELETE, SHOW, CREATE, DROP, GRANT, REVOKE, ALTER, SET at line 1, char 136",`

- What was the expected result?

Query should be `... BY time(6h);SELECT last ...`
- What happenend instead?

Query is `... BY time(6h);;SELECT last ...`

**Comment by tau0** [comment]
I think that error somewhere here: 
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/influxdb/datasource.ts#L48

**Comment by bergquist** [comment]
@tau0 thank you for reporting this! The fix will be available in nightly and in 3.0.2 which should be released sooonish :)
