### ISSUE TITLE
Alerting: Slack Image Uploads Do Not Work With API Token

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#50056]
The Grafana 9.0.0 Beta uses the pkg/services/webhook package to upload files. It expects error codes when something is wrong with the upload, but the Slack API returns 200s on a variety of error conditions.

In order to debug failed image uploads, we need some HTTP code that is tailored to the Slack API.

**Comment by joeblubaugh** [comment]
This only affects image uploads (used when files are only stored locally, and not uploaded to an external host).

**Comment by joeblubaugh** [comment]
After some investigation:
The Slack file upload API has gotten more restricted and complex over the years. I believe that legacy alerting’s file upload approach would fail in the same way that I saw when generating this ticket

To send slack messages you can either make:
1. An incoming webhook URL, via a Slack App.
2. A bot or user token with chat.write and chat:write:public permissions.

You can attach images to chat messages sent via these routes using publicly-accessible URLs. That’s what Grafana does if it is set up with external image storage, and the images will be rendered in the notification message.

To also upload photos from local disk directly to slack, the client must:
1. Add channels:read, users:read, channels:join, file.write scopes to the token / app
2. Read the list of channels to get their aliases and encoded IDs
3. Find the channels configured in the notifier in the conversations.list response and extract their IDs (C123456).
4. Join the channel
5. Upload the file.

These files aren’t attached to a message as written - they’re just uploaded immediately after the notification message is sent. Attachment images are significantly cleaner looking, show up in mobile notifications …

The multi-step process with several HTTP calls leads to a lot of complexity that is difficult to test without a live Slack instance, it doesn’t work properly right now, and 9.0.0-beta-3 is imminent.

I have tested and confirmed that image attachments via URL works, using a test GCS bucket, a local Grafana server, and a Slack instance that I control (see attached image)
<img width="747" alt="Screenshot 2022-06-02 at 4 01 47 PM" src="https://user-images.githubusercontent.com/1951900/171585185-c97dc3aa-33ec-49f5-b888-21628f28e229.png">

I’m making a judgement call to remove image uploads from the Slack notifier. That means that if there are Slack notifications, screenshots are enabled, and they are stored only on the local filesystem without a publicly-accessible URL, then no screenshot will be uploaded.

**Comment by JohnnyQQQQ** [comment]
Just to be sure I understand everything correctly:

What we changed here is that we removed to upload of the image to the slack server and always __only__ use the attachment approach with an external image, right?

**Comment by matteocontrini** [comment]
@joeblubaugh could you clarify if image upload for notifications is currently available for Slack?

I'm unable to get them to work after upgrading from Grafana 8 to 10, the documentation [says](https://grafana.com/docs/grafana/latest/alerting/manage-notifications/images-in-notifications/) that image uploads to Slack are supported, while this issue seems to imply otherwise. The Slack notifier code [seems to have](https://github.com/grafana/grafana/blob/43356e28e7d2bddac0fbfff8a6a89720985a357e/pkg/services/alerting/notifiers/slack.go#L407) a file upload implementation though.

**Comment by Huangvivi** [comment]
> After some investigation: The Slack file upload API has gotten more restricted and complex over the years. I believe that legacy alerting’s file upload approach would fail in the same way that I saw when generating this ticket
> 
> To send slack messages you can either make:
> 
> 1. An incoming webhook URL, via a Slack App.
> 2. A bot or user token with chat.write and chat:write:public permissions.
> 
> You can attach images to chat messages sent via these routes using publicly-accessible URLs. That’s what Grafana does if it is set up with external image storage, and the images will be rendered in the notification message.
> 
> To also upload photos from local disk directly to slack, the client must:
> 
> 1. Add channels:read, users:read, channels:join, file.write scopes to the token / app
> 2. Read the list of channels to get their aliases and encoded IDs
> 3. Find the channels configured in the notifier in the conversations.list response and extract their IDs (C123456).
> 4. Join the channel
> 5. Upload the file.
> 
> These files aren’t attached to a message as written - they’re just uploaded immediately after the notification message is sent. Attachment images are significantly cleaner looking, show up in mobile notifications …
> 
> The multi-step process with several HTTP calls leads to a lot of complexity that is difficult to test without a live Slack instance, it doesn’t work properly right now, and 9.0.0-beta-3 is imminent.
> 
> I have tested and confirmed that image attachments via URL works, using a test GCS bucket, a local Grafana server, and a Slack instance that I control (see attached image) <img alt="Screenshot 2022-06-02 at 4 01 47 PM" width="747" src="https://user-images.githubusercontent.com/1951900/171585185-c97dc3aa-33ec-49f5-b888-21628f28e229.png">
> 
> I’m making a judgement call to remove image uploads from the Slack notifier. That means that if there are Slack notifications, screenshots are enabled, and they are stored only on the local filesystem without a publicly-accessible URL, then no screenshot will be uploaded.

May I ask how did you send test notification with a picture?
I try to type a grafana-rendered link to there, and still not work
