### ISSUE TITLE
Response time  item return no data and no graph in grafana 8.5

### ISSUE THREAD

**Issue by amirajoodani** [grafana/grafana#50050]
hello .
in new version of grafana  (8.5.0~8.5.4) response time  item does not get data from zabbix server with zabbix datasource
i test with other verion of zabbix data source but still does not show any graph . (return no data)

**What happened**:
no data and no graph from response time item 

**What you expected to happen**:
make graph when choose response time item .

**Anything else we need to know?**:
with this zabbix server i have grafana 7.1 and zabbix datasource (3.12.4) and create graph without any problem but after updating grafana we got problem .

**Environment**:
- Grafana version: 8.5.0 ~8.5.4 (all version tested)
- Data source type & version: (zabbix -alexesander-zobnin-app (4.2.0 ~ 4.2.8 -->all version tested))
- OS Grafana is installed on: Redhat Enterprise Linux 8.5
- User OS & Browser: windows 10 & chrome
- Grafana plugins: zabbix 

thanks in advance . 
 

more details: https://community.grafana.com/t/response-time-does-not-show-in-grafna-8-5-return-no-data/66409
![time server graph](https://user-images.githubusercontent.com/42912741/171515796-ea4a2c1a-bf5d-43b4-a185-e728b29ee0b8.PNG)

**Comment by mellieA** [comment]
@amirajoodani the zabbix datasource is community supported and maintained. I recommend opening an issue in the repository for the project here: 

https://github.com/alexanderzobnin/grafana-zabbix/issues
