### ISSUE TITLE
Parent trace not picked up by Grafana after 8.4.0 

### ISSUE THREAD

**Issue by chaudyg** [grafana/grafana#50079]
**What happened**:

I have a simple reverse proxy in front of grafana injecting traces headers onto every request. 

In 8.3.6, the reported traces are properly propagated between the proxy and grafana
![image](https://user-images.githubusercontent.com/7817963/171621392-cd419b65-6364-4a62-9ebe-5b320e5ee9c1.png)

After 8.4.0, the traces between the two services are disjointed. 

![image](https://user-images.githubusercontent.com/7817963/171622007-2a889f8b-6949-441e-aacf-61fdfab1d020.png)
![image](https://user-images.githubusercontent.com/7817963/171622083-434e94c5-9ae2-48e0-a76d-d2a09efeb3fb.png)

**What you expected to happen**:
The parent trace should be picked-up by grafana.

**How to reproduce it (as minimally and precisely as possible)**:
1. deploy a reverse proxy in front of grafana. Here i am using `opentracing-go` with jaeger.
2. make a request
3. check the trace

**Environment**:
- Grafana version: works in 8.3.6, broken after 8.4.0+

cc @hairyhenderson

**Comment by chaudyg** [comment]
`git bisect` points at https://github.com/grafana/grafana/commit/30aa24a18396f61bfbcbfbeee78b1c0d23685fc3

**Comment by tolzhabayev** [comment]
seems to be already fixed
