### ISSUE TITLE
server-side expressions problem in dashboard

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#50077]
since https://github.com/grafana/grafana/commit/8c477a288a73e009733419e445c1062e78b8d776 something broke with server-side expressions.

try this:
- create a dashboard-panel
- add a datasource that creates metric data, for example Prometheus, add a query that creates one "line" on the graph
- add an Expression, operation=Math, Expression=`$A*2`

now you should see two "lines" in the graph, but you will only see one.

if i revert the mentioned commit, it starts to work again.

(i do not know why that commit broke this, i found the commit by `git bisect`)

**Comment by cracker0dks** [comment]
I have the same error for the same expression. Server logs: `msg="Query data error" error="expression request error: invalid expression command type in 'A'"`

**Comment by gabor** [comment]
this got fixed in https://github.com/grafana/grafana/pull/50446 , so closing the issue

@cracker0dks please check whether your problem got fixed too. if not, then it's a different issue, and i recommend creating a separate new github issue for it.
