### ISSUE TITLE
log file permissions too strict on RHEL 8

### ISSUE THREAD

**Issue by sspieker** [grafana/grafana#50085]
**What happened**:
The "grafana.log" log file's permissions are 0640 in our installation which make it inaccessible to log file agents like logstash.
This applies to "grafana.log" and the rotated files.
We're hosting Grafana on a Red Hat Enterprise Linux 8 machine.

**What you expected to happen**:
I expected the file's permissons to be 0644.
After all, this is what I found in the code: [log/file.go#L130](https://github.com/grafana/grafana/blob/v8.5.3/pkg/infra/log/file.go#L130).

**How to reproduce it (as minimally and precisely as possible)**:
Install Grafana on RHEL 8 machine, enable log mode "file", start Grafana and look into /var/log/grafana folder.
I believe the same applies to CentOS which might be a more accessable OS for testing purposes, but I'm not able to test this myself.

**Anything else we need to know?**:
I'm pretty sure the systemd unit file provided in the rpm package causes this issue: [grafana-server.service#L50](https://github.com/grafana/grafana/blob/v8.5.4/packaging/rpm/systemd/grafana-server.service#L50)
```UMask=0027``` generally removes the "other" flags from new files created by grafana-server (at least that's what I understand consulting the Red Hat docs [here](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/configuring_basic_system_settings/assembly_managing-file-permissions_configuring-basic-system-settings#user-file-creation-mode-mask_assembly_managing-file-permissions)).
I did a small test to verify this:
```bash
# log file with 0640 permission
$ ls -l /var/log/grafana/grafana.log
-rw-r----- 1 grafana grafana 106663 Jun  2 14:34 /var/log/grafana/grafana.log

# modify systemd unit (this does not touch the original unit so future grafana updates are safe)
$ systemctl edit grafana-server.service

# this opens a new editor where I could specify the modified UMask

# this is what just has been created
$ cat /etc/systemd/system/grafana-server.service.d/override.conf
[Service]
UMask=0023

# reload systemd unit and restart grafana
$ systemctl daemon-reload
$ systemctl restart grafana-server

# log file with correct 0644 permission
$ ls -l /var/log/grafana/grafana.log
-rw-r--r-- 1 grafana grafana 175668 Jun  2 14:40 /var/log/grafana/grafana.log
```
So the UMask setting obviously has a higher priority than the file creation flags in the Go code.
To me, modifying the systemd UMask setting is a bad idea because it will apply to *all* new files, not only the log files. The real question seems to be "why does the Go code not work as expected?".

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: -
- OS Grafana is installed on: Red Hat Enterprise Linux 8
- User OS & Browser: -
- Grafana plugins: -
- Others: log mode "file" enabled

**Comment by daniellee** [comment]
Ref https://github.com/grafana/grafana/issues/2468 from 2015 that added the creation flags in the go code.

**Comment by sspieker** [comment]
@daniellee
I have nearly zero experience with Go, but the [OpenFile](https://pkg.go.dev/os#OpenFile) documentation mentions `umask` :
> [...] If the file does not exist, and the O_CREATE flag is passed, it is created with mode perm (before umask). [...]

My knowledge regarding `umask` is quite limited as well, but maybe this is a clue?

**Comment by sspieker** [comment]
Is there any news on this?
This is still an issue in Grafana 9.0.7 which I was testing today...

Right now, Grafana logs can not be gathered by our centralized logmanagement because its agents are not allowed to read the files.
My originally described workaround still is a no-go in my opinion, because I'm unable to tell if there are any other implications I'm not aware of...
