### ISSUE TITLE
Migration: CLI command to remove legacy passwords from datasources

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#50105]
Create a CLI command that deletes all datasource secrets grafana databases, including legacy and unified secrets locations. This is intended to be run after a migration to the plugin, so ideally it will display some warnings.

We may also want to add some validation to ensure things are in sync between Grafana and AWS before doing the deletion. When the command is run, we can fetch all secrets from both locations and compare them. If there are any secrets missing on the AWS side, we can migrate them and then do the deletion.

**Comment by timlevett** [comment]
Won't fix
