### ISSUE TITLE
UI: Dashboard settings button not present on dashboard view with viewer role and user_can_edit = true

### ISSUE THREAD

**Issue by fgouteroux** [grafana/grafana#50148]
Hello Grafana Team,

I want to share with you this UI bug. The **open dashboard setting button** is not present (anymore since few grafana versions now) when current user role is **viewer**, with the setting **viewers_can_edit**  is set to true.

![image](https://user-images.githubusercontent.com/1460473/171827100-d5280f48-b385-4312-b82c-f047f72d1d6f.png)

The workaround is to edit a panel, then the button is present 
![image](https://user-images.githubusercontent.com/1460473/171827204-039aed96-c55f-4248-b04a-51b9c7f7025d.png)

And we can edit dashboard variables...
![image](https://user-images.githubusercontent.com/1460473/171829654-a569a3bb-470c-45eb-93b4-4299dc3d9988.png)

**What happened**:
The dashboard setting button is not present on dashboard view when current user role is viewer and `viewers_can_edit = true`

**What you expected to happen**:
The dashboard setting button must be present on dashboard view when current user role is viewer and `viewers_can_edit = true`

**How to reproduce it (as minimally and precisely as possible)**:
- Set grafana.ini setting `viewers_can_edit = true` as explained in the [doc](https://grafana.com/docs/grafana/latest/administration/configuration/#viewers_can_edit)
- Login with a user with viewer role
- Go to a dashboard
- Dashboard setting button not present

**Anything else we need to know?**:
The workaround is to edit a panel (which possible with the grafana.ini setting viewers_can_edit = true), then the button is showed

**Environment**:
- Grafana version: 8.5.4
- OS Grafana is installed on: Linux Centos 7
- User OS & Browser: Centos 7, Mozilla Firefox for cCentOS Linux Redhat -1.0 (91.9.1esr (64-bit))

**Comment by mellieA** [comment]
@fgouteroux thanks for reporting this. I see the same thing. I'll move this to the right squad to take a look

**Comment by IevaVasiljeva** [comment]
Hi, @fgouteroux! Thanks for reporting the issue and for sharing a workaround! We've added a fix which will be released with versions `9.1.0` and `9.0.5`.
