### ISSUE TITLE
fiscal year selection does not update legend data

### ISSUE THREAD

**Issue by atartareanu** [grafana/grafana#50153]
**What happened**:
when defining a custom fiscal year range and selecting a fiscal year timeframe, the legend values are still shown for the year and not fiscal year

**What you expected to happen**:
the legend values should update for the specified time range, in our case a custom fiscal year data definition.

**How to reproduce it (as minimally and precisely as possible)**:
go to
https://play.grafana.org/d/000000012/grafana-play-home?orgId=1&from=now%2Ffy&to=now%2Ffy&editPanel=3
define the fiscal year starting april
add total for the legend values
![image](https://user-images.githubusercontent.com/22320901/171838174-55fd9750-216d-4793-bb31-40b15b7fa36b.png)

select "this fiscal year" (01.04.2022 to 31.03.2023) to view the desired time range for that specific graph, the total numbers in the legend is 51k

try another selection for the current year(01.01.2022 to 31.12.2023), the total value on the legend is still 51k although the timeframe is completely different.
![image](https://user-images.githubusercontent.com/22320901/171837905-46420369-c034-48e0-9adf-ce940a329b42.png)

**Comment by ashharrison90** [comment]
can repro this on the play dashboard with the steps you've provided 👍

**Comment by codeincarnate** [comment]
Was able to reproduce as well. It appears stats aren't being recalculated in certain instances (but are in others). @mdvictor is going to be taking a look.

**Comment by atartareanu** [comment]
Can you please reopen this issue ?
It's not solved (9.06 version) and it can still be reproduced as described above.

Thank you.

**Comment by mdvictor** [comment]
Hey @atartareanu. You are right, the fix didn't reach that version. Really sorry about that. It should be available on the next patch.
