### ISSUE TITLE
[Feature Request] Add Megawatt-hours (MWh) to singlestat unit of measures

### ISSUE THREAD

**Issue by kevincolyar** [grafana/grafana#5016]
I could really use the MWh unit of measure in the singlestat panel.

**Comment by woutertP1** [comment]
Divide your metric by 1000 and it will display MWh automatically (on version 2.6)

**Comment by kevincolyar** [comment]
Ah, got it.  I think you meant multiply by 1,000.  My metric is stored in MWh. Thanks!
