### ISSUE TITLE
[Bug] Unable to remove query in Chrome

### ISSUE THREAD

**Issue by gregorybrzeski** [grafana/grafana#5017]
Grafana: 3.0.1
DS: graphite
OS: Linux
Browser: Chrome 50.0.2661.94 (64bit)

Unable to remove a query in Chrome browser (version above) when clicking on the trash icon on the right hand side of the query box. Works as expected in Safari.

Console returns following error:

![image](https://cloud.githubusercontent.com/assets/2437752/15234039/c3c7f120-18ad-11e6-8700-ad0132d2840f.png)

**Comment by torkelo** [comment]
not able to replicate this :(

**Comment by bergquist** [comment]
@gregorybrzeski is this on a new or existing dashboard? What is your flow when this happened?

**Comment by gregorybrzeski** [comment]
@bergquist installed clean end of April from grafana_3.0.0-beta61461918338_amd64.deb, then updated to grafana_3.0.1_amd64.deb. In both versions problem occured.

Now we have reinstalled from clean using grafana_3.0.1_amd64.deb and imported dashboards by hand. All works as expected on Chrome and Safari.

This was occuring in any flow but only using Chrome browser, Safari was fine (no more browsers tested).
