### ISSUE TITLE
User with viewer role shouldn't see Create playlist button

### ISSUE THREAD

**Issue by rcastro33** [grafana/grafana#50177]
**What happened**:
User with Viewer Role can see UI elements for create a Playlist in Dashboards section. After complete name, Dashboards to include and click save, the creation fails with toast messages "Permission Denied".

**What you expected to happen**:
Viewer user mustn't see the "Create Playlist" button

**How to reproduce it (as minimally and precisely as possible)**:
- Create organization
- Create simple dashboard
- Create an user an assign a viewer role to organization
- Login with that user
- In navbar, click on Playlist
- There is the Create Playlist button

**Anything else we need to know?**:

I understand this issue was resolved in [PR #28992](https://github.com/grafana/grafana/pull/28992) to version 7.4.0, about issue [24987: Create new playlist button shouldn't be visible for user with viewer role on playlists page](https://github.com/grafana/grafana/issues/24987)

**Environment**:
- Grafana version: 8.4.1
- Data source type & version:
  - Zabbix
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Mozilla Firefox 100.0.2, Chrome 102.0.5005.61
- Grafana plugins:
  - Zabbix: 4.1.5
- Others: Grafana running as Docker container

![image](https://user-images.githubusercontent.com/51093376/171884916-49dd90c0-c380-4d1f-9e40-ea3314ba9bcf.png)

**Comment by asymness** [comment]
@torkelo, I can take this up.
