### ISSUE TITLE
logging configuration seems to be broken

### ISSUE THREAD

**Issue by dennisjac** [grafana/grafana#5018]
I just installed grafana 3.0.1 and it seems the logging settings in the configuration file are ignored.

I'm calling grafana like this:
/usr/bin/grafana-server -config /etc/grafana/grafana-server.ini -homepath /opt/grafana

the grafana-server.ini file contains these two logging related directives:
```
[paths]
...
logs = /var/log/grafana
...
[log]
mode = console
...
```
When I try to start the server I get the following error:
2016/05/13 03:14:40 [log.go:312 Error()] [E] Fail to set logger(file): open /opt/grafana/data/log/grafana.log: permission denied

There seem to be two problems here:
1) The logging path in the configuration file is apparently ignored
2) Even though I removed the "file" target from the logging configuration Grafana still wants to create a log file

As a workaround I did the following:
```
mkdir /opt/grafana/data
ln -s /var/log/grafana /opt/grafana/data/log
chown grafana:grafana /opt/grafana/data/log
```
After this grafana-server starts normally.

**Comment by torkelo** [comment]
yes, this is a known issue :( 

There is a good workaround and that is to set the logs path from the command line instead, 

```
/usr/bin/grafana-server \
   --config /etc/grafana/grafana-server.ini \
   --homepath /opt/grafana \ 
   cfg:default.paths.logs=/var/log/grafana

This is what the deb/rpm package init scripts does.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/3349
