### ISSUE TITLE
DatasourceNoData alerts sent whenever Grafana package is updated via apt

### ISSUE THREAD

**Issue by Drakynn** [grafana/grafana#50186]
**What happened**:  
Updating the Grafana package on Debian causes "no-data" alerts to fire when the service restarts.

**What you expected to happen**:  
Grafana should have a brief settle time after service restart so team alerts aren't going out during an expected normal operation such as upgrading the software.

**How to reproduce it (as minimally and precisely as possible)**:   
1.  Set up a basic monitor with an MQTT data source
2. Define alert condition with a no-data alert enabled
3. Upgrade Grafana with 'apt upgrade'
4. Monitor alert path for incoming "DatasourceNoData Value" message

**Anything else we need to know?**:

Apt upgrade output
```
apt-listchanges: Reading changelogs...
(Reading database ... 64238 files and directories currently installed.)
Preparing to unpack .../grafana_8.5.4_arm64.deb ...
Unpacking grafana (8.5.4) over (8.5.3) ...
Setting up grafana (8.5.4) ...
Restarting grafana-server service... OK
Processing triggers for man-db (2.9.4-2) ...
```
Upgrade is working properly and messages saying that the DatasourceNoData Value has been resolved goes out about one minute after the false alarm.

**Environment**:
- Grafana version:  8.5.4 and all recent versions for at least the last two months
- Data source type & version: grafana/mqtt-datasource (latest)
- OS Grafana is installed on:  Debian 11.3
- User OS & Browser:  MacOS / Chrome
- Grafana plugins:  grafana/mqtt-datasource
- Others: N/A

**Comment by ryantxu** [comment]
Interesting -- IIUC, with MQTT, it is expected that there will be no-data when the system first starts.  It is just listening for messages as they come in, and then alerting on the history.  If the alert condition runs before any messages arrive... 💣 

Do you need/want to add a no-data alert?  IIUC, for MQTT, it would only fire if nothing has beenr received since startup.

Perhaps a different alert that checks the timestamp of the last point + total number of points?  or something like that

**Comment by alexweav** [comment]
Dropping the alerting tag, as this appears to be an issue with the underlying datasource.

**Comment by Drakynn** [comment]
It is only an issue when Grafana first starts up.  If there was some sort of timeout or pause before firing off the alert on a fresh startup, this would resolve the problem from my perspective.

**Comment by alexweav** [comment]
This can be approximated with the notification policy tree. You can add a policy entry that routes DatasourceNoData alerts separately, then increase its `group_wait` so it will not be evaluated for a few minutes after the system starts up. However, this will also reduce the resolution of the alerts.

**Comment by alexweav** [comment]
We have an item on our backlog which will make this more straightfoward to use, but right now `group_wait` is the closest thing that approximates this in the system today.

**Comment by Drakynn** [comment]
Thanks Alex, that works for me.
