### ISSUE TITLE
Prometheus: templating queries fail when custom headers configured

### ISSUE THREAD

**Issue by kostrse** [grafana/grafana#50199]
**What happened**:

When **Custom HTTP Headers** configured in Prometheus datasource, templating queries fail with invalid header message:

<img width="75%" src="https://user-images.githubusercontent.com/1131253/171964973-329e9063-8842-4d38-b08a-d5bd1af523cf.png" />

<img width="75%" src="https://user-images.githubusercontent.com/1131253/171965007-6020a0d9-43d9-4c0d-a56a-a881e4672908.png" />

<img width="50%" src="https://user-images.githubusercontent.com/1131253/171965388-4c9d3dbb-7736-4265-8da7-5a0bc98856d3.png" />

**What you expected to happen**:

Templating queries should be consistent with panels in support of headers.

**How to reproduce it (as minimally and precisely as possible)**:

Add a custom header to a working datasource and open a dashboard with templating queries.

**Anything else we need to know?**:

Related to #48790 
Possible regression after #49921 

This breaks Prometheus in Azure as it relies on custom queries.

**Environment**:
- Grafana version: main
- Data source type & version: Prometheus
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by srclosson** [comment]
@kostrse I want to add a unit test so this regression does not happen again. Is it safe to say then, if I add a custom-header to a query, that the backend request keep the header? (Ie: this is less about template queries, and more about ensuring the custom header is propagated?

**Comment by kostrse** [comment]
> Is it safe to say then, if I add a custom-header to a query, that the backend request keep the header? (Ie: this is less about template queries, and more about ensuring the custom header is propagated?

Currently queries from panels and from alerts do propagate custom headers to final endpoint.
The same behavior should be for templating queries as well.

Resulting HTTP request should be same regardless of where it was originated from.

**Comment by srclosson** [comment]
@kostrse I didn't answer your question before merging #50344. The reason for the difference is that resource calls act like a proxy in the backend. They act like a standard http request, and as such it makes sense (to me anyway) to try to preserve as much of the original query as possible so that the proxy modifies the query as little as possible.

With QueryData, it's a little different, as a query to the backend are literally instructions to the backend, and the backend issues the query.

**Comment by kostrse** [comment]
OK, I think we can close this.
