### ISSUE TITLE
unable to create user with the admin api key

### ISSUE THREAD

**Issue by raj990** [grafana/grafana#5019]
Hi,

I am using grafana 2.6. I have created an admin API key in one organization. Used that key for authentication using HTTP API. I am getting a permission denied error while creating a new user.

I would like to know what is the problem. Correct me if i'm doing anything wrong. 

Thanks,
Raj

**Comment by torkelo** [comment]
an org admin api key cannot use the "Grafana Server Admin" api routes. You can add existing users, org admin api key: http://docs.grafana.org/http_api/org/#add-a-new-user-to-the-actual-organisation

For these you need to authenticate using basic auth 
http://docs.grafana.org/http_api/admin/

**Comment by raj990** [comment]
Thanks a ton for the quick reply. Now I'm able to create new user with basic auth.

**Comment by raj990** [comment]
But in the documentation  

[http://docs.grafana.org/v2.6/reference/http_api/#global-users ](url)

It is mentioned that we can create new user. There is also an example to given as below

Global Users
POST /api/admin/users

Create new user

Example Request:

POST /api/admin/users HTTP/1.1
Accept: application/json
Content-Type: application/json
Authorization: Bearer eyJrIjoiT0tTcG1pUlY2RnVKZTFVaDFsNFZXdE9ZWmNrMkZYbk

{
  "name":"User",
  "email":"user@graf.com",
  "login":"user",
  "password":"userpassword"
}
Example Response:

HTTP/1.1 200
Content-Type: application/json

{"id":5,"message":"User created"}

**Comment by anmolsingh008** [comment]
Same problem, created a super user, added API key. But can not use it for admin purpose , always giving permission denied.

**Comment by torkelo** [comment]
@anmolsingh008 api keys are not supported for server admin usage yet, only org admin apis, for server admin usage you need to use basic auth with a user given Grafana Server Admin permission

**Comment by anmolsingh008** [comment]
Thanks for the quick reply. I am able to create a new user now.
Is there no API to create a new organisation?
