### ISSUE TITLE
about  grafana  templating Variables 

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5020]
i  got a nested mode with es,when i  add a variables , like owner.name,
i use {"find":"terms","field":"owner.name"}
sometimes i can get the data ,but sometimes it failed, i used the version of grafana is 2.6.0 
anyone can give helps?
Thank you! For helping us make Grafana even better.

To help us respond to your issues faster, please make sure to add as much information as possible.

If this issue is about a plugin, please open the issue in that repository.

Start your issues title with [Feature Request] / [Bug] / [Question] or no tag if your unsure. Also, please be aware that GitHub now supports uploading of screenshots; look at the bottom of this input field.

Please include some basic information:
- What grafana version are you using?
- What datasource are you using?
- What OS are you running grafana on?
- What did you do?
- What was the expected result?
- What happenend instead?

If you question/bug relates to a metric query / unexpected data visualization, please include:
- An image or text representation of your metric query
- The raw query and response from your data source (check this in chrome dev tools network tab)

**Comment by tonyC2016** [comment]
if i del the dashboard and new another ,it can get the data,

**Comment by torkelo** [comment]
What's elasticsearch error message when the template query fails?

**Comment by tonyC2016** [comment]
@torkelo 
 QueryParsingException[Failed to parse query [owner.name:()]]; nested: NotSerializableExceptionWrapper[parse_exception: Cannot parse 'owner.name:()': Encountered " ")" ") "" at line 1, column 22.

**Comment by torkelo** [comment]
can you also check the raw query sent by grafana to ES (using chrome dev tools)? 

Maybe something your ES documents that is causing ES to throw an error?

**Comment by tonyC2016** [comment]
the es is local, and just me to operate this, ,if some fields is null or some dirty data,is it causing the error?
