### ISSUE TITLE
Question about Authentication API

### ISSUE THREAD

**Issue by dizzzz** [grafana/grafana#5022]
Is there a way (an API), e.g. upon 1st time startup, to generate an API token?

I certainly would like to avoid to have passwords stored in our scripts, but our server needs to be installed and configured without any user interaction.

**Comment by torkelo** [comment]
you can using a grafana server admin (using basic auth) create a organization admin api key. 

```
POST http://localhost/grafana/api/auth/keys
{"role":"Admin","name":"My key"}
```

The response will contain the api key
