### ISSUE TITLE
intervalSeconds value ignored when updating alerts via API

### ISSUE THREAD

**Issue by BrianFarnhill** [grafana/grafana#50222]
**What happened**:

When posting updates to the alertmanager API, the `intervalSeconds` value seems to be ignore. Here are the steps to repro:

1. Create an alert with these settings (most props of alert body removed for brevity but I can share separately if you believe it matters). API path is `/api/ruler/grafana/api/v1/rules/SAMPLE` as a `POST`

```
{
	"name": "sample-alert",
	"interval": "10s",
	"rules": [
		{
			"for": "20s",
			"grafana_alert": {
				"title": "sample",
				"intervalSeconds": 10,
				"namespace_uid": "SAMPLE",
				"rule_group": "sample-group"
			}
		}
	]
}
```
2. Browse to Grafana and observe the alert is created successfully, but the `for` field shows `30s` as it's value
3. Change the value to `10s` in the UI (note - in this environment `GF_UNIFIED_ALERTING_MIN_INTERVAL` is set to `10s` and `GF_ALERTING_MIN_INTERVAL_SECONDS` is set to `10`), observe the value saves correctly and can be observed when refreshing the page
4. Perform a `GET` for the alert group, observe that `intervalSeconds` is set to 10 as expected (same URL but with the group appended for the get - `/api/ruler/grafana/api/v1/rules/SAMPLE/sample-group`)
5. Attempt to update the alert via the API again (set the `intervalSeconds` to be 20 for example)
6. Observe the UI shows a value of `30s` again

**What you expected to happen**:

The `intervalSeconds` value should be updated as per the value in the API

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

Not that I can think of

**Environment**:
- Grafana version: v9.0.0-64566pre (f566958555)
- Data source type & version: Amazon Timestream 2.0.0
- OS Grafana is installed on: Ubuntu (from docker image `grafana-oss/latest-ubuntu` on dockerhub)
- User OS & Browser: Firefox 91.9.0esr
- Grafana plugins: None in this scenario

**Comment by JacobsonMT** [comment]
The field `intervalSeconds` is calculated and is not modifiable so it's being ignored. The correct field to use to modify a group's interval is the `interval` field at the top level (`"interval": "10s"`).

Closing for now, feel free to re-open if this did not fix/answer your issue.
