### ISSUE TITLE
I got err_connection_refused when accessing Grafana login page

### ISSUE THREAD

**Issue by thinhduckhoi** [grafana/grafana#5023]
Hi guys,
I'm trying to install Graphite and Grafana following this tutorial for Ubuntu 14.04
http://community.netapp.com/fukiw75442/attachments/fukiw75442/oncommand-storage-management-software-articles-and-resources/717/2/Graphite_Grafana_Quick_Start_v1.4.pdf
The point is i wasn't be able to see the Grafana login page, i get Err_connection_refused error.
I'm testing this on my Cloud service using Ubuntu 14.04 version and set open all port in "Security group". 
I also checked the /var/log/grafana but didn't see any file in there.
Could someone tell me how to fix it, please?

**Comment by torkelo** [comment]
did you start grafana-server after install? Can you check that it is running? (`ps -aux | grep grafana`)

**Comment by thinhduckhoi** [comment]
@torkelo 
root@ubuntu14-graphite:~# ps -aux | grep grafana
root      3875  0.0  0.0  10464   924 pts/0    S+   08:01   0:00 grep --color=auto grafana
Here's the ouput.

Silly me! Seems like i use http instead of https and that was reason why i got error.
