### ISSUE TITLE
AzureMonitor: Don't maintain whitelist of supported metric namespaces

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#50239]
### Discussed in https://github.com/grafana/grafana/discussions/41982

<div type='discussions-op-text'>

<sup>Originally posted by **joshhunt** April 13, 2021</sup>
Having a manually maintained list of [`supportedMetricNamespaces`](https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/supported_namespaces.ts) that controls the metric namespaces that can be queries through Azure Monitor metrics leads to a maintenance burden and feature requests from missing services, such as #28733.

Needs investigating, but we should either remove this list (don't filter on our end) or use an API to get supported metric namespaces. Will need to investigate how National Clouds plays into this.</div>

As far as I can see, there is no need to filter resources by namespace so we can remove the file: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azure_monitor/supported_namespaces.ts

**Comment by fridgepoet** [comment]
By the way I noticed while investigating [this escalation](https://github.com/grafana/support-escalations/issues/2815) that on my local Grafana v9.0.0-pre `main` branch that I was already auto-suggested a metric namespace which isn't in the list. I wonder why it is already populated without it being part of this list?

**Comment by andresmgot** [comment]
> By the way I noticed while investigating [this escalation](https://github.com/grafana/support-escalations/issues/2815) that on my local Grafana v9.0.0-pre `main` branch that I was already auto-suggested a metric namespace which isn't in the list. I wonder why it is already populated without it being part of this list?

There is some inconsistency here. As a summary, to populate the resource picker for Metrics, we are using the supported types for Logs, which is defined here:

https://github.com/grafana/grafana/blob/a8354a031933c80afbd7a95cf7b5453b4608f987/public/app/plugins/datasource/grafana-azure-monitor-datasource/azureMetadata/resourceTypes.ts

You were lucky enough that `Microsoft.MachineLearningServices/workspaces` was added as supported for Logs, but not for metrics. I'll fix that separately.

Once a resource is selected, we specifically obtain the metric namespace(s) for that resource and we no longer filter out based on our list. The list is only used to filter resources in the resource picker.

**Comment by andresmgot** [comment]
After #50788 we have updated the list of supported namespaces and added instructions about how to update that list but it's still hardcoded. There are three list:

 1. The list of metric namespaces supported for Azure Monitor Metrics.
 2. The list of metric namespaces (also named as categories or resource types) supported for Azure Monitor Logs.
 3. The map between namespaces and human-readable names.

For 1., we can use the [metric-namespaces list](https://docs.microsoft.com/en-us/rest/api/monitor/metric-namespaces/list?tabs=HTTP) API endpoint. The only required input for this is a subscription. This means that we can only get the list of namespaces _after_ we have the list of subscriptions. We already have a function for this: [getMetricNamespaces](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts#L157).

For 3., we can obtain that information using the [metric-definitions list](https://docs.microsoft.com/en-us/rest/api/monitor/metric-definitions/list?tabs=HTTP) API endpoint. The problem is that for this, we require a subscription, a resource group and a resource (with the special case of composed resources like `microsoft.classicstorage/storageaccounts/tableservices`). Again, we can reuse the existing method for [getMetricDefinitions](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/datasource.ts#L150)

For 2. we don't know yet if there is an available endpoint that we can use to filter which resources or namespaces are valid Log scopes.

**Comment by andresmgot** [comment]
More info on 2.:

There isn’t an equivalent API for AzMon Logs to return all of the resource types that support using Diagnostic settings to emit logs to Azure Monitor Log analytics.

Depending on the resource SKU logs (or some types of logs) may or may not be supported via Diagnostic settings. For example, Load Balancers using a basic SKU don’t support emitting logs but Load Balancers with a standard SKU can be configured to emit logs. So it’s not technically possible to return the supported list by resource name.

It can be done for a single resource. This [API call](https://docs.microsoft.com/en-us/rest/api/monitor/diagnostic-settings-category/list?tabs=HTTP) will list the available diagnostic settings (logs and log categories) for an individual resource.

**Comment by aangelisc** [comment]
On point 2, it seems that [this](https://docs.microsoft.com/en-us/azure/azure-monitor/essentials/resource-logs-categories) page details which resources have logs that are exportable to Log Analytics and it does provide indication that the list is autogenerated. However, it doesn't detail how or any caveats around resources such as the load balancer SKU difference mentioned above.

**Comment by andresmgot** [comment]
yes, Microsoft confirmed that there is not a way to get that list from a single API call so we should keep using that doc page [as stated in the list that we maintain](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/grafana-azure-monitor-datasource/azureMetadata/logsResourceTypes.ts#L2).

Since 3. also needs an API call per resource, which can be tedious and expensive to handle, I think we can close this issue just implementing the automation for 1.
