### ISSUE TITLE
AzureMonitor: Add Azure Resource Graph editor for dashboard variables

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#50233]
**What happened**:

From: https://github.com/grafana/grafana/discussions/39970

It should be possible for users to write their own ARG query for generating a template variable.

The editor should be the same one than the one for normal queries.

**Environment**:
- Grafana version: 9.0
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by ovidiubuligan** [comment]
any timeline on this ? (I just wanted to get a resource name)

**Comment by andresmgot** [comment]
It's on the works here: https://github.com/grafana/grafana/pull/53059 so it should be included in comming releases in the following weeks
