### ISSUE TITLE
[Bug] Not able to hide X-Axis in Graph Panel

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#5024]
- What grafana version are you using? - grafana/master
- What datasource are you using? - Opentsdb
- What OS are you running grafana on? - MacOS
Browser - Firefox
- What did you do? - Tried hiding the time-axis (x-axis)
- What was the expected result? - X-axis should be hidden
- What happenend instead? - Nothing happened, I can still see x-axis :(

**Comment by bergquist** [comment]
@utkarshcmu thank you for an excellent report! :)

**Comment by utkarshcmu** [comment]
Thanks for fixing the bug. :)
