### ISSUE TITLE
[Question/Bug] PNG render doesn't work after upgrade from grafana 2.6 to 3

### ISSUE THREAD

**Issue by mcortinas** [grafana/grafana#5025]
Hello,

 Last wednesday I upgrade my grafana from 2.6 to 3 and I use a graphite datasource , graphite-webapp with version 0.9.13 runing over python 2.7 in Ubuntu with kernel 3.10.0-327.4.4.el7.x86_64 #1 SMP Tue Jan 5 16:07:00 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

 We currently use multiple dashboards using PNG render because flot render needs more resources.
 Last wednesday I upgrade from 2.6 to 3 and I can see all PNG graphs with RENDER isn't working fine.

 I can see in grafana log 
`Completed 10.2.24.251 admin "GET /render HTTP/1.1" 500 Internal Server Error 673 bytes in 353717us
`

 In my graphite server I can see these log traces
`
Fri May 13 11:25:05 2016 :: Exception Caught
Traceback (most recent call last):
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 231, in fetchData
    cachedResults = CarbonLink.query(dbFile.real_metric)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 140, in query
    results = self.send_request(request)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 166, in send_request
    result = self.recv_response(conn)
  File "/opt/graphite/webapp/graphite/render/datalib.py", line 181, in recv_response
    return unpickle.loads(body)
  File "/opt/graphite/webapp/graphite/util.py", line 108, in loads
    return pickle_obj.load()
  File "/opt/graphite/webapp/graphite/util.py", line 97, in find_class
    raise pickle.UnpicklingError('Attempting to unpickle unsafe module %s' % module)
UnpicklingError: Attempting to unpickle unsafe module collections
`

 Fuirthermore I attached the browsers screenshots requesting directly in grafana and graphite
![grafanaerrorpng](https://cloud.githubusercontent.com/assets/692263/15243885/ae6260ee-18fe-11e6-9005-5fe698c87e5a.png)
![graphiteerrorpng-netowrktools](https://cloud.githubusercontent.com/assets/692263/15243983/29769b88-18ff-11e6-8a00-1fbcf3590ccd.png)

![graphiteerrorpng1](https://cloud.githubusercontent.com/assets/692263/15243904/bcb8eaaa-18fe-11e6-9d1e-bb3fc6f88a2a.png)

**Comment by bergquist** [comment]
@mcortinas Should be fixed by now :) Thank you for reporting this!

**Comment by mcortinas** [comment]
Super! Fixed! Thank you @bergquist !
