### ISSUE TITLE
[Question] How to know the current version of Grafana?

### ISSUE THREAD

**Issue by thinhduckhoi** [grafana/grafana#5026]
Hi guys,
I want to know exactly what version my Grafana is.
But i couldn't see any where shows  the version.
Hope someone could help me.

<img src="http://www.upsieutoc.com/images/2016/05/13/ver.jpg" alt="ver.jpg" border="0">

**Comment by bergquist** [comment]
Right now the only way is to visist the login page. http://grafana/login

This will be improved by https://github.com/grafana/grafana/issues/4889

**Comment by thinhduckhoi** [comment]
@bergquist What do you mean by visiting login page? I didn't see any login button there.

**Comment by utkarshcmu** [comment]
You can go to any dashboard first, then click on "manage dashboard" icon, then click on settings. In the settings section, version is written in bottom left.

**Comment by thinhduckhoi** [comment]
Followed your instruction but still din't see any Version written. :( Ok, not a big deal. Thank you.

**Comment by bitdivine** [comment]
For some versions of grafana you can find the version number in the javascript console: 

    grafanaBootData.settings.buildInfo

**Comment by daniellee** [comment]
@bitdivine go to any page that is not a dashboard (Data Sources page for example) and look at the footer:

![image](https://user-images.githubusercontent.com/434655/29516484-c7efed2a-8670-11e7-8cad-1a9a76f7be9e.png)

**Comment by digambarGitHub** [comment]
@daniellee : thanks Dani. It is helpful.

**Comment by Siddhu1096** [comment]
5.3.1

**Comment by Ashwinv23** [comment]
you can go to the path where Grafana is installed. In my case, it's on /usr/share/grafana. There's a file called VERSION which has the version of the grafana installed.

**Comment by Siddhu1096** [comment]
If you've successfully installed grafana, then just go the webview, scroll down to bottom and there you'll see grafana version

**Comment by zuchka** [comment]
There is now an endpoint for this. `/api/health`

https://grafana.com/docs/grafana/latest/http_api/other/#health-api

**Comment by rewanthtammana** [comment]
Best answer by @zuchka 🚀

**Comment by Onmo-Deepika** [comment]
> In my Grafana 7.1.5 I can hover over the question mark icon in the bottom left corner. Popup menu shows version at the top: ![image](https://user-images.githubusercontent.com/364890/117355561-9b948b00-ae67-11eb-9fa2-a3c2e85dd309.png)

thanks alot ! finally i got the version

**Comment by bmdeshmukh18** [comment]
If you need to check it using the linux console, then just run below.

cat /usr/share/grafana/VERSION.

This will print out the current installed version of grafana.

**Comment by m0a0k0s** [comment]
How to find if it OSS or not ?

**Comment by daniellee** [comment]
You can see if it is OSS or not in the `Stats and license` section:

<img width="1511" alt="Image" src="https://github.com/user-attachments/assets/d4144e8f-da0f-49bf-bb21-e960099aeb0b" />

And the version is in the help menu at the top right:

<img width="319" alt="Image" src="https://github.com/user-attachments/assets/450b1040-0414-4332-aea6-b7c9b612ca89" />

**Comment by HarimbolaSantatra** [comment]
You can also view it with `grafana-server --version`
