### ISSUE TITLE
Grafana doesn't send an alert if still alerting after Mute Timing period

### ISSUE THREAD

**Issue by jameselderxe** [grafana/grafana#50266]
**What happened**:

Grafana didn't send an alert even though it was still in an alerting state after the Mute Timing period ended.

**What you expected to happen**:

Once the Mute Timing period ended, if the Alert Rule was still in an alerting state a notification would be sent.

**How to reproduce it (as minimally and precisely as possible)**:

1. Setup an Alert Rule for something which is alerting in 15 minutes time
2. Create a Notification Policy to alert to somewhere - say send an email
3. Create a Mute Timing for say the next hour
4. The alert state should change in 15 minutes time but the notification will not be sent due to the Mute Timing period
5. After an hour the notification will still not be sent despite the fact the alert is still in "alerting" state

**Anything else we need to know?**:

**Environment**:
- Grafana version: ALL, but we are on 8.5.4
- Data source type & version: N/A
- OS Grafana is installed on: N/A
- User OS & Browser: N/A
- Grafana plugins: N/A
- Others: N/A

**Comment by jameselderxe** [comment]
Hi sorry I meant to get back to you sooner on this.

Sure our Mute Timing policy has two intervals (so we can cover all of Friday evening and then all of Saturday/Sunday):

<img width="791" alt="Screen Shot 2022-06-08 at 18 33 52" src="https://user-images.githubusercontent.com/103572206/172680966-c23c990a-1895-4013-b945-96b27d1a053a.png">

In terms of the repeat interval, group interval or group wait interval we don't use these at all (we actually have override general timings toggled off):
<img width="516" alt="Screen Shot 2022-06-08 at 18 35 38" src="https://user-images.githubusercontent.com/103572206/172681268-b5054ebc-5f19-41da-9e27-c222b9f373d8.png">

Hope this helps!

**Comment by joeblubaugh** [comment]
Have you changed the default timings of the root notification policy? The default repeat_interval is 4 hours, which may explain the fact that the alert isn't sent. If you're able to test this with a shorter repeat interval that would be great - if not, that's absolutely OK. Muted notification policies simply skip notifications.

The Prometheus alertmanager also behaves this way, and we are following that model. Here's a related discussion: https://github.com/prometheus/alertmanager/issues/2496

A workaround for your issue then, could be to set a shorter repeat interval for some notification policies. If the Prometheus alertmanager changes this behavior, we would update ours to match.

**Comment by jameselderxe** [comment]
No we haven't changed the default root policy, although this alert with the Mute Timing policy does not use the default root policy as it has it's own Notification Policy.

Also in addition, even after 4 hours have passed since the Mute Timing policy has ended we still don't get a notification.

The datasource is elasticsearch not prometheus, so I don't think we are hitting the prometheus issue.

I have gone ahead and set a repeat interval of 1 hour explicitly on the Notification Policy used by this alert with the Mute Timing policy, in the hope that 1 hour after the end of the Mute Timing policy, if the alert is still firing a notification would be sent. I'm just waiting on a sufficient example to test this - which could be a couple of weeks.

That said the enablement of a repeat interval is something you need to toggle on for each notification policy by toggling the Override General Timings switch. But I think that is a bug as imho if an alert is still firing after a Mute Timing policy ends then a notification should be sent regardless.

Thanks!

**Comment by joeblubaugh** [comment]
> The datasource is elasticsearch not prometheus, so I don't think we are hitting the prometheus issue.

What I mean is that the Grafana backend uses the same algorithm as the prometheus alertmanager to decide when notifications should be sent, so it doesn't matter what the datasource that you're querying is.

> That said the enablement of a repeat interval is something you need to toggle on for each notification policy by toggling the Override General Timings switch.

I agree that this isn't very ergonomic. If you're OK with having the same repeat and group intervals for all of your notification policies, you can change the timing values on the root, default notification policy. Then you'll get those timings for any notification policy that doesn't override them.

Thank you for the report - this is working-as-implemented, but we will keep the feedback in mind as a rough part of the experience that we can work on improving.

**Comment by jameselderxe** [comment]
Thanks for the response @joeblubaugh, we can definitely work with overriding for now at the root or individually. But the issue is the default 4 hour repeat interval from the didn't work (i've yet to see if the override on the specific notification policy works either).

In terms of the root policy do we also have to toggle the "Override General Timings" for it to take effect? I assume not as you mentioned the Default General Timing is 4 hours?
