### ISSUE TITLE
LogContext: Feature UX touch up

### ISSUE THREAD

**Issue by 09jvilla** [grafana/grafana#50270]
List of a few small changes to make to the 'Show Context' feature to make it a little more user friendly.

- [x] #55472
- [x] #55919
- [x] #56282
- [x] #56384
- [x] #56281
- [ ] #56038
- [x] #56070 
- [x] #56122

See attached mockups for illustration

![Bildschirmfoto 2022-06-15 um 12 52 25](https://user-images.githubusercontent.com/88372197/173810560-fc6116c5-da3f-4361-9222-76219ca527ba.png)
![Bildschirmfoto 2022-06-15 um 12 52 46](https://user-images.githubusercontent.com/88372197/173810578-272ce523-d78b-4736-b9a5-73f5d22be246.png)

Log line highlight:
![Storybook](https://user-images.githubusercontent.com/88372197/173811280-7cd7213f-33b1-44f1-b111-24a3b05f5797.jpg)

**Comment by niat22** [comment]
- [ ] Add time stamp to log line in 'Show Context'

**Comment by svennergr** [comment]
@09jvilla I added #56070 which fixes the scroll behaviour in the context modal.

**Comment by 09jvilla** [comment]
This is great @svennergr . I also added https://github.com/grafana/grafana/issues/56122 to this list, which also came out of the RAMP call.

**Comment by svennergr** [comment]
https://github.com/grafana/grafana/issues/56038 is not trivial with the way the context is currently designed and implemented. I'll close this issue and cover https://github.com/grafana/grafana/issues/56038 in https://github.com/grafana/grafana/issues/58032.

**Comment by 09jvilla** [comment]
SGTM, Sven.
