### ISSUE TITLE
[Bug] Associations User <> Organization resets in 3.0.1 and previus beta

### ISSUE THREAD

**Issue by BMarvi** [grafana/grafana#5027]
Grafana 3.0.1, prev. tried also  beta7 with the same behaviour.
used with InfluxDB. Linux R.H. Server

I'm using Grafana with Active Directory for the authentication. 
I have two organizations: the default "Main Org", and a second one, "My Company"
As admin, after an user did his first login ad appear in the list of the users, I remove him from "Main Org" and add to "My Company".
Everything seems ok until the user log in a second time. 
As he log in, the associations with the organizations get resetted. So he is now associated with "Main Org" but not with "My Company".

**Comment by torkelo** [comment]
When you use LDAP Grafana will look at your ldap group mappings to map LDAP group membership to Grafana organization membership and role
http://docs.grafana.org/installation/ldap/#mappings

**Comment by BMarvi** [comment]
Ok Thanks!
