### ISSUE TITLE
Grafana cannot start when Plugin not found

### ISSUE THREAD

**Issue by peterschmitzer** [grafana/grafana#50280]
**What happened**:
After a kubernetes cluster reboot that was triggered by deploying security patches to our nodes the grafana pod was not starting anymore. The only information we had was one suspicious log entry saying:
"Error: ✗ Plugin not found (Grafana v8.3.5 linux-amd64)"
The situation was solved by removing the requried plugins from the helm chart one by one until identifying the one that caused the issue.

**What you expected to happen**:
We would expect grafana to start successfully and log an error specifiying the "plugin not found" error including the plugin that caused this error.

**How to reproduce it (as minimally and precisely as possible)**:
Specify a grafana plugin in the helm chart to be loaded on startup from the internet, which is not available.

**Anything else we need to know?**:

**Environment**:
- Grafana version: Grafana v8.3.5 linux-amd64
- Data source type & version:  n/a
- OS Grafana is installed on: kube-prometheus-stack on Kubernetes 1.21
- User OS & Browser: n/a
- Grafana plugins: azure-datasource
- Others:

**Comment by marefr** [comment]
Trying to figure out if this is a Grafana or Helm problem. 
- What plugins did you have installed?
- Can you include the helm configuration you used (replace any sensitive information)?

**Comment by atlemagnussen** [comment]
Got the same problem here. 
But I never had Helm plugin, only `grafana-azure-monitor-datasource`

**Comment by peterschmitzer** [comment]
- What plugins did you have installed?
    - grafana-azure-monitor-datasource
    - camptocamp-prometheus-alertmanager-datasource
    - blackmirror1-statusbygroup-panel
    - flant-statusmap-panel
    - natel-discrete-panel
    - vonage-status-panel

Can you include the helm configuration you used (replace any sensitive information)?
`
## Configuration for alertmanager
## ref: https://prometheus.io/docs/alerting/alertmanager/
##
## Provide a name in place of kube-prometheus-stack for `app:` labels
##

alertmanager:

  ## Deploy alertmanager
  ## The AlertManager is enabled in values.yaml - to disable/false in a case your infrastructure fireing Prometheus/Grafana to reduce the amount traffic to external systems like mattermost and opsgenie
  # enabled: false

  ingress:
    enabled: true
    ingressClassName: XXXXXXXXXXXXXXXXXXXXXXXXXXXXx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      acme.cert-manager.io/http01-ingress-class: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/api/v1/status"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'

    hosts:
      - XXXXXXXXXXXXXXXXXXXXX

    paths:
    - /alert/health

    tls:
    - secretName: XXXXXXXXXXXXXXXXXXXXXXX
      hosts:
      - XXXXXXXXXXXXXXXXXXXXX

  ## Settings affecting alertmanagerSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/api.md#alertmanagerspec
  ##
  alertmanagerSpec:

    ## Image of Alertmanager
    ##
    image:
      repository: XXXXXXXXXXXXXXXXXXXXX/prometheus/kube-prometheus-stack/alertmanager
      tag: v0.23.0
      sha: ""

    ## Define resources requests and limits for single Pods.
    ## ref: https://kubernetes.io/docs/user-guide/compute-resources/
    ##
    resources:
      requests:
        memory: 256Mi
        cpu: 100m
      limits:
        memory: 512Mi
        # cpu: 1
## Using default values from https://github.com/grafana/helm-charts/blob/main/charts/grafana/values.yaml
##
grafana:
  enabled: true
  image:
    repository: XXXXXXXXXXXXXXXXXXXXXX/grafana/grafana
    tag: "8.3.5"
    sha: ""
    pullPolicy: IfNotPresent
  
  replicas: 2

  testFramework:
    image: XXXXXXXXXXXXXXXXXXXXX/grafana/bats/bats
    tag: "v1.4.1"
    imagePullPolicy: IfNotPresent

  downloadDashboardsImage:
    repository: XXXXXXXXXXXXXXXXXXXXX/grafana/curlimages/curl
    tag: "7.73.0"
    sha: ""
    pullPolicy: IfNotPresent

  initChownData:
    ## initChownData container image
    image:
      repository: XXXXXXXXXXXXXXXXXXXXX/grafana/busybox
      tag: "1.31.1"
      sha: ""
      pullPolicy: IfNotPresent
    
    replicas: 1

    ## initChownData resource requests and limits
    ## Ref: http://kubernetes.io/docs/user-guide/compute-resources/
    resources:
      requests:
        memory: 128Mi
        cpu: 100m
      limits:
        memory: 256Mi
        # cpu: 200m

  grafana.ini:
    server:
      domain: XXXXXXXXXXXXXXXXXXXXX
      root_url: "%(protocol)s://%(domain)s/grafana/"
      serve_from_sub_path: tru


  ## Resource limits & requests for Grafana
  resources:
    requests:
      memory: 256Mi
      cpu: 200m
    limits:
      memory: 512Mi
      # cpu: 300m

  ## Sidecars that collect the configmaps with specified label and stores the included files them into the respective folders
  ## Requires at least Grafana 5 to work and can't be used together with parameters dashboardProviders, datasources and dashboards
  sidecar:
    image:
      repository: XXXXXXXXXXXXXXXXXXXXX/grafana/quay.io/kiwigrid/k8s-sidecar
      tag: "1.15.1"
      sha: ""
    imagePullPolicy: IfNotPresent

    replicas: 1
    
    ## Resource limits & requests for Grafana Sidecar (grafana-sc-dashboard)
    resources:
      requests:
        memory: 64Mi
        cpu: 20m
      limits:
        memory: 96Mi
        # cpu: 40m - disabled to avoid to much alerts


    dashboards:
      enabled: true
      
    datasources:
      enabled: true
      defaultDatasourceEnabled: false
  # Grafana plugins what will be installed over the Internet
  plugins:
    - camptocamp-prometheus-alertmanager-datasource
    - blackmirror1-statusbygroup-panel
    - flant-statusmap-panel
    - natel-discrete-panel
    - vonage-status-panel

## Configuration for kube-state-metrics subchart
##
kube-state-metrics:
  prometheusScrape: true
  image:
    repository: XXXXXXXXXXXXXXXXXXXXX/kube-state-metrics/k8s.gcr.io/kube-state-metrics/kube-state-metrics
    tag: "v2.3.0"
    pullPolicy: IfNotPresent

  # If set to true, this will deploy kube-state-metrics as a StatefulSet and the data
  # will be automatically sharded across <.Values.replicas> pods using the built-in
  # autodiscovery feature: https://github.com/kubernetes/kube-state-metrics#automated-sharding
  # This is an experimental feature and there are no stability guarantees.
  autosharding:
    enabled: false

  replicas: 1

  service:
    port: 8080
    # Default to clusterIP for backward compatibility
    type: ClusterIP
    nodePort: 0
    loadBalancerIP: ""
    annotations: {}

  ## Resource limits & requests for kube-state-metrics
  resources:
    requests:
      memory: 256Mi
      cpu: 50m
    limits:
      memory: 384Mi
      # cpu: 100m


## Configuration for prometheus-node-exporter subchart
##
prometheus-node-exporter:
  image:
    repository: XXXXXXXXXXXXXXXXXXXXX/node-exporter/quay.io/prometheus/node-exporter
    # Overrides the image tag whose default is {{ printf "v%s" .Chart.AppVersion }}
    tag: "v1.3.1"
    pullPolicy: IfNotPresent

  ## Resource limits & requests for prometheus-node-exporter 
  resources:
    requests:
      memory: 24Mi
      cpu: 100m
    limits:
      memory: 32Mi
      # cpu: 200m  - disabled to avoid to much alerts

## Manages Prometheus and Alertmanager components
##
prometheusOperator:
  enabled: true

  ## Resource limits & requests for Prometheus Operator
  ##
  resources:
    requests:
      memory: 128Mi
      cpu: 100m
    limits:
      memory: 128Mi
      # cpu: 1

  ## Prometheus-operator image
  ##
  image:
    repository: XXXXXXXXXXXXXXXXXXXXX/prometheus/kube-prometheus-stack/prometheus-operator
    tag: v0.54.0
    sha: ""
    pullPolicy: IfNotPresent

  ## Prometheus-config-reloader image to use for config and rule reloading
  ##
  prometheusConfigReloader:
    # image to use for config and rule reloading
    image:
      repository: XXXXXXXXXXXXXXXXXXXXX/prometheus/kube-prometheus-stack/prometheus-config-reloader
      tag: v0.54.0
      sha: ""

    # resource config for prometheusConfigReloader
    resources:
      requests:
        memory: 32Mi
        cpu: 20m
      limits:
        memory: 64Mi
        # In case of the Config Reloader, if we remove the CPU Limit setting the Prometheus Operator will set a default instead (100m).
        # However, if we set this value to zero, the Prometheus Operator will not set any CPU Limit.
        # See: https://github.com/prometheus-operator/prometheus-operator/issues/2575
        cpu: 0

  thanosImage:
    repository: XXXXXXXXXXXXXXXXXXXXX/prometheus/kube-prometheus-stack/thanos/thanos
    tag: v0.24.0
    sha: ""

## Deploy a Prometheus instance
##
prometheus:

  enabled: true

  ingress:
    enabled: true
    ingressClassName: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt"
      acme.cert-manager.io/http01-ingress-class: nginx-ops
      kubernetes.io/tls-acme: "true"
      nginx.ingress.kubernetes.io/rewrite-target: "/-/healthy"
      nginx.ingress.kubernetes.io/ssl-redirect: "true"
      nginx.ingress.kubernetes.io/auth-type: basic
      nginx.ingress.kubernetes.io/auth-secret: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx
      nginx.ingress.kubernetes.io/auth-realm: 'Authentication Required'

    hosts:
      - XXXXXXXXXXXXXXXXXXXXX

    tls:
    - secretName: XXXXXXXXXXXXXXXXXXXXXXXXXx
      hosts:
        - XXXXXXXXXXXXXXXXXXXXX

  ## Settings affecting prometheusSpec
  ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/api.md#prometheusspec
  ##
  prometheusSpec:

    ## Image of Prometheus.
    ##
    image:
      repository: XXXXXXXXXXXXXXXXXXXXX/prometheus/kube-prometheus-stack/prometheus
      tag: v2.33.1
      sha: ""

    ## Number of replicas of each shard to deploy for a Prometheus deployment.
    ## Number of replicas multiplied by shards is the total number of Pods created.
    ##
    replicas: 1

    ## Resource limits & requests
    ##
    resources:
      requests:
        memory: 4096Mi
        cpu: 1
      limits:
        memory: 8192Mi
        # cpu: 2

    ## Prometheus StorageSpec for persistent data
    ## ref: https://github.com/prometheus-operator/prometheus-operator/blob/master/Documentation/user-guides/storage.md
    ##
    storageSpec:
    ## Using PersistentVolumeClaim
    ##
      volumeClaimTemplate:
        spec:
          storageClassName: "resizeable-azuredisk"
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 50Gi
        # selector: {}

    ## External labels to add to any time series or alerts when communicating with external systems
    ##
    externalLabels:
      cluster_id: XXXXXXXXXX

    ## AdditionalAlertRelabelConfigs allows specifying Prometheus alert relabel configurations. Alert relabel configurations specified are appended
    ## to the configurations generated by the Prometheus Operator. Alert relabel configurations specified must have the form as specified in the
    ## official Prometheus documentation: https://prometheus.io/docs/prometheus/latest/configuration/configuration/#alert_relabel_configs.
    ## As alert relabel configs are appended, the user is responsible to make sure it is valid. Note that using this feature may expose the
    ## possibility to break upgrades of Prometheus. It is advised to review Prometheus release notes to ensure that no incompatible alert relabel
    ## configs are going to break Prometheus after the upgrade.
    ##
    additionalAlertRelabelConfigs:
      - action: labelmap
        regex: label_env
        replacement: env
      - action: labeldrop
        regex: label_env`

**Comment by marefr** [comment]
Thanks. I think this is a duplicate of #43401 which was fixed via #46842 and released in Grafana v8.4.5 so I'm going to close this. We'll consider reopen if you still see this behavior in recent Grafana versions.

**Comment by marefr** [comment]
Duplicate of #43401
