### ISSUE TITLE
[QUESTION] ElasticSearch source error 403 whitelist ?

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5028]
Hi,

I try to add ElasticSearch as source but when i click on "Save&Test" button i have this error:
ERROR : 403

In my cache browser i have more informations:
`{"message":"Data proxy hostname and ip are not included in whitelist"}`
The access method is "proxy"

 What does it mean ?

I using Firefox and grafana 3 beta 6 in docker and ElasticSearch in docker in other server

**Comment by torkelo** [comment]
what's your config setting for `data_source_proxy_whitelist`   (this by default emtpy so all should be accepted)

**Comment by Azef1** [comment]
Ok, data_source_proxy_whitelist **isn't** empty. there are an IP address. 
I understand, i will change this IP or erase IP.
Can I config two @IP in data_source_proxy_whitelist ?

**Comment by torkelo** [comment]
yes you can have multipe seperated by whitespace

**Comment by Azef1** [comment]
Thx you very much for your help
It's works now
