### ISSUE TITLE
Grafana protected iframe.

### ISSUE THREAD

**Issue by Michsh** [grafana/grafana#5029]
I want to use Grafana on my website using Iframe.
But i want to use authentication like digest, key ,ssl certificate or if can grafana to alow specific website (by domanin/ip/other criteria)  to access his resources it will be great.   
And i did not find any solution to do a protected authentication between Grafana and Apache both on Debian same machine . 

Thanks !

**Comment by torkelo** [comment]
you can put any proxy auth infront of grafana, for example if you let apache proxy requests. 

You can read about all the different built in auth options here 
http://docs.grafana.org/installation/configuration
