### ISSUE TITLE
Unified Alerting: All alarms are reset when saving one alarm

### ISSUE THREAD

**Issue by Jessimon** [grafana/grafana#50290]
Hello Grafana,

When you edit an alert rule and save it ALL alerts rules are reset to resolved.
This creates confusion and unnecessary checking and communication of various teams. 

Before when you edited an alert rule, only that alert rule was reset. 

To reproduce it create two rules.
One rule (rule1) that goes in alert and one rule (rule2) where the status does not matter.
When you get the alert notification edit the second rule and save it.
Now rule one is gets the resolved status.

- Grafana version: 8.5.3
- Data source type & version: Prometheus 2.35.0
- OS Grafana is installed on: Debian 11
- User OS & Browser: Windows with Firefox

**Comment by ashharrison90** [comment]
can repro this on main

made a very simple example as suggested: 
![image](https://user-images.githubusercontent.com/20999846/172355779-b73b247e-4e61-4acc-b9d7-e92b70c0ff68.png)

if i then edit `doesntMatter` and rename it to `doesntMatter2`:
![image](https://user-images.githubusercontent.com/20999846/172355889-0d935cba-5e0f-478d-b6f2-5e75ac6620a2.png)

**Comment by gillesdemey** [comment]
Correct, for now we've documented this caveat inline but this really requires a somewhat different UI approach.

**Comment by matthias-huber** [comment]
I also stumbled over the reset of all alerts within the same group by editing one alert. It isn't a problem if alerts are in OK state. But as already mentioned, it is really confusing when alerts change from firing to ok and then back to firing. 

To be honest, this kind of forces to not use the grouping at all (more precisely, to add each alert into a single one as a group always has to be defined). Most likely this has other disadvantages that I am not aware of.

**Comment by yuri-tceretian** [comment]
@matthias-huber thanks for the feedback! Prior to Grafana 9, the grouping field was not available and every alert belonged to its own group. The notion of groups is taken from Prometheus alerting where all alerts that belong to the same group are evaluated sequentially. Currently, Grafana supports grouping only on API level: we consider the group during authorization (allow the user to access an alert rule only if it can access all rules in the group the alert belongs to) and state changes (the behavior you encountered, if a rule is updated the all state of all rules in that group is reset). The rules are still handled individually by the core engine. Currently, we're working on the changes to make alerting engine be compliant with Prometheus way of handling alert rules

**Comment by soniaAguilarPeiron** [comment]
Link to the experimental design regarding evaluation interval :
https://www.figma.com/file/2s7EGevGeI4GuiArOmUECK/Unified-Alerting?node-id=4325%3A26479

**Comment by yuri-tceretian** [comment]
@soniaAguilarPeiron, design looks nice! One thing to note: The rule evaluation interval is set per group whereas `for` interval is set per rule

**Comment by soniaAguilarPeiron** [comment]
💯 I agree @yuri-tceretian, we should move the `for` to a second line or something like that. Maybe @jessover9000 has a better idea.

**Comment by soniaAguilarPeiron** [comment]
This improvement will be released in the next 9.4 release.
