### ISSUE TITLE
[Question] How to show multiple text in annotations ?

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5030]
Hi,

In annotations, is it possible to show multiple text with Elasticsearch source ?

Somethings like that:
![something](https://cloud.githubusercontent.com/assets/15362041/15252191/08a88c58-192d-11e6-91d1-c0160c1dea6c.PNG)
In Text field show `description` and `message`

I using Grafana 3

**Comment by torkelo** [comment]
you can show a title, a tags field and a description field
