### ISSUE TITLE
[Bug] Row editor buttons not hidden properly when sidemenu is pinned

### ISSUE THREAD

**Issue by zachd** [grafana/grafana#5031]
Hi, on **Grafana 3.0.1** (and play.grafana.org) when the sidebar is pinned and a row is added to a dashboard that extends the length of the page past the screen size, the green "row editor" buttons are not hidden properly (See screenshot below).

![image](https://cloud.githubusercontent.com/assets/1366937/15255480/292bb962-1934-11e6-90d0-541dae35ec74.png)

Looks like this needs a CSS tweak for the sidebar height.

Thanks,
A Hosted Graphite employee.

**Comment by torkelo** [comment]
fixed in master (no row menu anymore)
