### ISSUE TITLE
Unified alerting screenshot rendering not works

### ISSUE THREAD

**Issue by N0tronic** [grafana/grafana#50315]
Hey guys,

I tried to use the image rendering for unified alerting. I read that you built in the rendering for unified alerting in the v9 beta version from grafana. 

I enabled the screenshot rendering with the environment variable GF_UNIFIED_ALERTING_SCREENSHOTS_ENABLED. Logfile confirm this action:
`level=info msg="Config overridden from Environment variable" var="GF_UNIFIED_ALERTING_SCREENSHOTS_ENABLED=true" `

No idea, why rendering not works. I can see the call in grafana log, but there is no image in the alerting message:
`level=debug msg="calling remote rendering service" url=http://renderer:8081/render/version`

Any idea?

**Environment**:
- Grafana version: docker grafana/grafana:9.0.0-beta2
- Data source type & version: Elasticsearch
- OS Grafana is installed on: Docker Container
- Grafana plugins: Default
- Contact Point: Mail
- Image Store: No external image store
- Others: External Rendering Service

**Comment by joeblubaugh** [comment]
I'm reopening because there is an actual bug in the email templating that doesn't have anything to do with the config value bug. I've made change #50370 to fix that.
