### ISSUE TITLE
Dashboard to folder navigation doesn't work from direct link

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#50330]
**What happened**:
Going to a dashboard from a direct link, and attempting to navigate to a folder from the breadcrumb trail does not navigate to the folder.

**What you expected to happen**:
See the folder with the dashboards inside it.

**How to reproduce it (as minimally and precisely as possible)**:

1. Go to a dashboard in a folder directly from a link (ie https://ops.grafana.net/d/zc1bFbrnk/query-history?orgId=1)
2. Click the folder on top to navigate there (Grafana feature tracking)
3. See incorrect query in box and "no results found"

**Environment**:
- Grafana version: 9.0

**Comment by ashharrison90** [comment]
@gelicia are you still seeing this? believe it has now been fixed

**Comment by axelavargas** [comment]
Attaching the PR that fixed this issue https://github.com/grafana/grafana/pull/50175
