### ISSUE TITLE
Question-Templating in Grafana with KairosDB Datasource

### ISSUE THREAD

**Issue by sarahmorr** [grafana/grafana#5033]
Hi, I am using Grafana v 2.6.0 with a Kairosdb datasource on Windows 7.I am using the custom type templating option. I would like to create a template with specific tags and template value. However when I do so the tags value query does not return the value for a given tag when applied. Has anyone else encountered this problem?

**Comment by torkelo** [comment]
not sure it's supported by the kairosdb api,
please open kairosdb related issues in the kariosdb datasource plugin repo
https://github.com/grafana/kairosdb-datasource
