### ISSUE TITLE
Template spanning issue

### ISSUE THREAD

**Issue by sarahmorr** [grafana/grafana#5034]
Hi, I am using Grafana v 2.6.0 with a Kairosdb datasource on Windows 7. I am having an issue with the spanning of my graphs, tables and single stats when a template variable is applied. When a template variable is applied my dashboard looses its layout. For example if I had a graph set to a span 4 it would change to a span of 12 once a template variable is applied. I have tried unsuccessfully in the General tab>Templating options > min span to rectify this. Has anyone had a similar issue?

**Comment by torkelo** [comment]
are you using panel repeats? A repeated panel require a min span option, and it expects the repeated panel to take up a whole row (or more), so if you only have one value selected it will set panel to span 12, if you have 4 values it will set span to 4  (depending on min span)
