### ISSUE TITLE
Grafana 8.5.5 can't start in Docker

### ISSUE THREAD

**Issue by karelkryda** [grafana/grafana#50353]
**What happened**:

I have WatchTower installed in Docker for automatic container updates. Grafana was automatically updated a few minutes ago and has not started. Looking at the logs, I see this:
![image](https://user-images.githubusercontent.com/59953812/172432165-a99010ac-da42-4a1f-a5ce-21936568f26e.png)

The file cannot be modified because the terminal will not connect to the container if the container is not running.

**What you expected to happen**:

Grafana starts without any problems

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: latest (8.5.5)
- Data source type & version: /
- OS Grafana is installed on: Docker + Raspbian GNU/Linux 10 (buster)
- User OS & Browser: Windows 11 + Chrome
- Grafana plugins: /
- Others: /

**Comment by ashharrison90** [comment]
@karelkryda you should be able to `docker cp` your file out of the stopped container, edit it then `docker cp` it back in. see something like https://stackoverflow.com/a/50166314 for an example. lemme know if that resolves your issue. 👍

**Comment by karelkryda** [comment]
@ashharrison90 great, the problem is solved. I have some questions:

1. Should I activate a new alert system instead of legacy alerting to prevent future problems?
2. How exactly do I do that in Docker?
3. Should I set force_migration to false again?

**Comment by ashharrison90** [comment]
hi @karelkryda 

great! glad you managed to solve the problem. 

we would definitely recommend moving to unified alerting, see the docs here for how to do that: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/opt-in/

yeah i'd recommend setting `force_migration` back to `false`
