### ISSUE TITLE
PostgreSQL: WHERE clause expression values not populated

### ISSUE THREAD

**Issue by bossinc** [grafana/grafana#50360]
The Postgres query builder is not populating WHERE clause expression values like it shows [here in the docs](https://grafana.com/docs/grafana/latest/datasources/postgres/#query-editor)

This issue was brought up here: https://github.com/grafana/support-escalations/issues/2550

**Comment by dprokop** [comment]
@oscarkilhed / @zoltanbedi is there an epic issue collecting all work related to sql-ish data sources migration?

**Comment by mdvictor** [comment]
I think the docs have been changed after the migration, I can't see where it says values are pre-populated anymore. In any case, we have this [issue](https://github.com/grafana/grafana/issues/53053) to keep evidence on improvements that need to be made to the new sql query builder. I'll close this issue and leave a comment there to take this into account and discuss whether we want to add this feature or not.
