### ISSUE TITLE
Logs/Metrics Resource Picker UI not updating right away

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#50364]
**What happened**: Updates to the Resource Picker UI are only happening until after clicking Apply and reopening the panel. This 
also only seems to happen when modifying the advanced Resource URI editor: 

![brokenAdvancedResourceURI](https://user-images.githubusercontent.com/20448042/172479970-0d44b0df-f387-495f-a974-6bac64da3896.gif)

This does not seem to happen when going from custom advanced URI to one of the values in the resource picker (which is the expected behavior)

**What you expected to happen**: the Resource picker UI to update to the right value right after the new value has been selected:

![properlyWorkingAdvURI](https://user-images.githubusercontent.com/20448042/172481189-3f19be31-aa88-4ac6-86ed-ea0aea7f4126.gif)

**How to reproduce it (as minimally and precisely as possible)**:

1. Create some template variables
2. Use them to populate an advanced Resource URI (preferably a path that points to a resource i.e. `/subscriptions/$subid/resourceGroups/$resourcegroup/providers/$namespace/$resourName`)
3. Modify the Resource URI path (going from a full resource path to a resource group path or viceversa

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0-pre
- Data source type & version: Azure Monitor 1.0.0
- OS Grafana is installed on: NA
- User OS & Browser: Edge, Windows
- Grafana plugins: NA
- Others: NA

**Comment by kevinwcyu** [comment]
I can reproduce this whenever there is any template variable in the resource URI. E.g. if you something like `/subscriptions/$subscription/resourceGroups/$rg/providers/Microsoft.Compute/virtualMachines/$rn` and then change `$rn` to an actual resource name, it won't show until you apply the change and then open up the panel again. But if you changed `$subscription`, `$rg` and `$rn` to actual values, it will update right away without having to reopen the panel.

I'll move this to our backlog.

**Comment by jcolladokuri** [comment]
Great, thank you for taking a look at this and getting it added to the backlog!

**Comment by asimpson** [comment]
This appears to have been fixed in #52982. Of course feel free to re-open if the issue persists.
