### ISSUE TITLE
Service accounts: ability to add service accounts to teams

### ISSUE THREAD

**Issue by eleijonmarck** [grafana/grafana#50375]
**why/what**
We need to add the ability to add service accounts to teams.

- [ ] add api call for adding a service account as a teamMember
**Note:** be vary of what actions are needed here

- [ ] add button in UI, where would this be placed? @VesnaDean
initially we will add it to the details page of a service account

### proposal 1
Use the /api/teams/:teamId/members route in the teams.go api director and see service accounts more like users.

**notes:**
- we need to remove the limit of only showing users from the getTeammembers route
- we need to account for different ways of viewing the users in the teammembers page

### proposal 2
Add addToTeam route in /api/serviceaccounts api. However this is not really for adding X to a team

### proposal 1
**action plan:**
- add backend capabilities
- add frontend capabilties and UI
- refactoring backend to use teamPermissionsService to add permissions to the db

**Comment by ashharrison90** [comment]
@eleijonmarck friendly reminder to add labels to your issues so they don't appear on the issue triage list:
![image](https://user-images.githubusercontent.com/20999846/172799756-0c9035c6-9fb4-42e1-a130-8cd5e5881930.png)

**Comment by IevaVasiljeva** [comment]
Closed in https://github.com/grafana/grafana/pull/51536

**Comment by pferrot** [comment]
This issue is marked as completed, but the functionality was actually reverted (see https://github.com/grafana/grafana/pull/52710), so adding service accounts to teams is still not possible from what I understand.

**Comment by eleijonmarck** [comment]
@pferrot you are right. we are evaluating still the use of service accounts for teams

changing from closed as complete to won't do for now
