### ISSUE TITLE
[Bug]plugins directory on windows is resolved to a relative dir to bin

### ISSUE THREAD

**Issue by bscholze** [grafana/grafana#5037]
On Windows - it seems that the plugin directory resolves to a relative directory to the bin folder. 

```
Config files:
  [0]: C:\grafana-3.0.1/conf/defaults.ini
  [1]: C:\grafana-3.0.1\conf\custom.ini
Paths:
  home: C:\grafana-3.0.1
  data: C:\grafana-3.0.1\data
  logs: C:\grafana-3.0.1\data\log
  plugins: data/plugins
```
grafana-server.exe creates
```
c:\grafana-3.0.1\bin\data\plugins
```

grafana-cli.exe will install in 
```
c:\grafana-3.0.1\data\plugins
```

I was able to make the plugins work by copying everything from `grafana-3.0.1\data\plugins` to `grafana-3.0.1\bin\data\plugins`.

I tried to configure an absolute path for the `plugins:` config entry, and grafana-server.exe will discover the plugins, but the front-end fails, as the XHR requests seem to still look relative to the bin directory.

Please include some basic information:
- What grafana version are you using?
3.0.1
- What datasource are you using?
Graphite
- What OS are you running grafana on?
Windows (7 and 2008 server)

**Comment by torkelo** [comment]
how are you starting grafana? if you dont specify plugins dir with cfg:default.paths.plugins=${PLUGINS_DIR}  (command line option) it will default to data/plugins

**Comment by bscholze** [comment]
I started the grafana-server.exe from the command line manually (testing it locally before upgrade on server).

I must have made a mistake before. Providing the absolute path in `custom.ini` solved my problem. My confusion came from the fact, that you use `makeAbsolute` for all data and log paths but not for the plugins path.

```
DataPath = makeAbsolute(Cfg.Section("paths").Key("data").String(), HomePath)
...
PluginsPath = Cfg.Section("paths").Key("plugins").String()
```
