### ISSUE TITLE
Riemann + Grafana + InfluxDB

### ISSUE THREAD

**Issue by akamalov** [grafana/grafana#5038]
**Environment:** 

```
Grafana: 3.0.1
InfluxDB: 0.13
Riemann: 0.2.11-1
```

Greetings folks,

Trying to graf ZooKeeper stats using Grafana + Influxdb + Riemann ( I am new to Grafana + Riemann + InfluxDB). All components are working as expected, however, I am having hard to creating a graph from the InfluxDB + Riemann data source (which has been configured and connection verified).  I am running a simple riemann-health and it is populating InfluxDB.  

I thought templating would give me the options, however I am getting "type-in" option (```SELECT mean("value") FROM "measurement" WHERE $timeFilter GROUP BY time($interval) fill(null)``` ), instead of drop down from available sources. From InfluxDB, I am getting stats for: 

```
zookeeper\ zk_approximate_data_size,host=localhost
zookeeper\ zk_avg_latency,host=localhost
zookeeper\ zk_ephemerals_count,host=localhost
zookeeper\ zk_followers,host=localhost
zookeeper\ zk_max_latency,host=localhost
zookeeper\ zk_min_latency,host=localhost
zookeeper\ zk_num_alive_connections,host=localhost
zookeeper\ zk_outstanding_requests,host=localhost
zookeeper\ zk_packets_received,host=localhost
zookeeper\ zk_packets_sent,host=localhost
zookeeper\ zk_pending_syncs,host=localhost
zookeeper\ zk_server_state,host=localhost
zookeeper\ zk_synced_followers,host=localhost
zookeeper\ zk_version,host=localhost
zookeeper\ zk_watch_count,host=localhost
zookeeper\ zk_znode_count,host=localhost
```
Any guides or an example how could I proceed with graphing ?

Thanks a ton!!

**Comment by torkelo** [comment]
>I thought templating would give me the options, however I am getting "type-in" option (SELECT mean("value") FROM "measurement" WHERE $timeFilter GROUP BY time($interval) fill(null) ), instead of drop down from available sources. From InfluxDB, I am getting stats for:

Not sure what you mean?  Try clicking on that query which will expand the query into a query editor, then select a measurement, and add a group by tag (if you want)
