### ISSUE TITLE
[Question] How to install plugins without CLI?

### ISSUE THREAD

**Issue by hl68fx** [grafana/grafana#5039]
Hi, 

I am running Grafana 3.0.1 in a Docker container and would like to install plugins. For example when I run `grafana-cli plugins install grafana-worldmap-panel` then I get the response "command not found". 
Is there any other way to install plugins without the CLI?

- Grafana version: 3.0.1
- Datasource: Influxdb 0.12
- OS: Ubuntu server 16.04

Kind regards,
Tom

**Comment by torkelo** [comment]
`grafana-cli plugins install grafana-worldmap-panel` needs to be executed inside the container. 

https://github.com/grafana/grafana-docker/pull/41
