### ISSUE TITLE
Enabling pagination in a table panel makes horizontal scrollbar disappear

### ISSUE THREAD

**Issue by larshove** [grafana/grafana#50394]
**What happened**:
When enabling pagination in a table panel, the horizontal scrollbar disappears.

**What you expected to happen**:
When not having pagination enabled, the horizontal scrollbar works as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Having more columns in a table panel than the screen can show, makes a horizontal scrollbar visible.
When enabling pagination in a table panel, the horizontal scrollbar disappears.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: Prometheus 2.36.0
- OS Grafana is installed on: Windows Server 2019
- User OS & Browser: Chrome
- Grafana plugins: None
- Others:

**Comment by ashharrison90** [comment]
can repro. worth mentioning the scrollbar is still there, it's just hidden behind the new pagination controls.

**Comment by codeincarnate** [comment]
@zoltanbedi has been working on this and from the sounds of it should be a fairly straightforward fix
