### ISSUE TITLE
Azure Monitor datasource isnt working error "Azure Log Analytics requires access to Azure Monitor but had the following error: InternalServerError"

### ISSUE THREAD

**Issue by astafan8** [grafana/grafana#50397]
**DUPLICATE ON STACKOVERFLOW**: https://stackoverflow.com/questions/71999482/azure-monitor-datasource-isnt-working-error-azure-log-analytics-requires-access/72024940

**What happened**: I am trying to add Azure Monitor data source using managed identity. Grafana 8.5.* open source docker image. But I am getting this weird error:
![image](https://user-images.githubusercontent.com/15662810/172593126-2a17d42e-20f7-4e7c-9f08-29039f53363d.png)

**What you expected to happen**: It should load the list of available subscriptions and then i should be able to select one, then press "test and save" and all should be great.

**How to reproduce it (as minimally and precisely as possible)**: Try to add an Azure Monitor data source with managed identity using Grafana 8.5.* open source docker image..

**Anything else we need to know?**: It works on 8.4.7.

**Environment**:
- Grafana version: Grafana 8.5.* open source docker image.
- Data source type & version: Azure Monitor
- OS Grafana is installed on: Linux
- User OS & Browser: Microsoft Windows 11 and Edge
- Grafana plugins:
- Others:

**Comment by JorisVandenbroeck** [comment]
Can confirm we're seeing the same as well, however for us this is on a new deployment so cannot confirm it if worked on an older version.

From the Azure Web App log stream:
```
2022-06-09T09:08:01.473516225Z Hosting environment: Production
2022-06-09T09:08:01.474026635Z Content root path: /app
2022-06-09T09:08:01.474538744Z Now listening on: http://[::]:8081
2022-06-09T09:08:01.474845949Z Application started. Press Ctrl+C to shut down.
2022-06-09T09:08:08.752152253Z grafana : [XXXXXXX-b2fe-48a2-a99e-51abbcca8c6c] Incoming request on /healthcheck?api-version=2021-08-01
2022-06-09T09:08:14.769076299Z grafana : [XXXXXXX-1dce-439b-8429-980aa9243934] Incoming request on /robots933456.txt
2022-06-09T09:12:44.889134928Z grafana : [XXXXXXX-9010-4d24-80ab-fa5032b02ab5] Incoming request on /msi/token?api-version=2019-08-01&client_id=&resource=https%3A%2F%2Fmanagement.azure.com
2022-06-09T09:12:45.483883272Z grafana : [XXXXXXX-9010-4d24-80ab-fa5032b02ab5] Request to retrieve token received
2022-06-09T09:12:45.491377078Z grafana : [XXXXXXX-9010-4d24-80ab-fa5032b02ab5] No User Assigned or Delegated Managed Identity found for specified ClientId/ResourceId/PrincipalId.
2022-06-09T09:12:45.608782425Z grafana : [XXXXXXX-3792-4955-b700-7ec573ea7988] Incoming request on /msi/token?api-version=2019-08-01&client_id=&resource=https%3A%2F%2Fmanagement.azure.com
2022-06-09T09:12:45.611399361Z grafana : [XXXXXXX-3792-4955-b700-7ec573ea7988] Request to retrieve token received
2022-06-09T09:12:45.617627349Z grafana : [XXXXXXX-3792-4955-b700-7ec573ea7988] No User Assigned or Delegated Managed Identity found for specified ClientId/ResourceId/PrincipalId.
```

I'm reading this as the Add-In being unable to aquire the Managed Identity details?

**Comment by fridgepoet** [comment]
Hi @astafan8 was there any other information about that error in the browser console or in the grafana server logs?

**Comment by astafan8** [comment]
@fridgepoet i have not checked the browser console or grafana server log (actually don't know how to check for that). The message that you see on the screenshot is the only message I got :( in order to help fix this issue, i'm happy to test things again, however i'd appreciate instructions on where to look and what to look for (e.g. where and how to find the logs and what not).

Since i couldn't find any information online, i ended up trying all the 8.5.* versions and then figured that things work on 8.4.7, so perhaps the bug is in the diff between 8.4.7 and 8.5.0.

**Comment by JorisVandenbroeck** [comment]
@fridgepoet when the message shows the following messages are shown in the browser console:
`XHRGEThttps://XXXXX.azurewebsites.net/api/datasources/6/resources/azuremonitor/subscriptions?api-version=2019-03-01
[HTTP/1.1 500 Internal Server Error 409ms]

	
GET
	https://XXXXX.azurewebsites.net/api/datasources/6/resources/azuremonitor/subscriptions?api-version=2019-03-01
Status
500
Internal Server Error
VersionHTTP/1.1
Transferred998 B (684 B size)
Referrer Policystrict-origin-when-cross-origin

    	
    Cache-Control
    	no-cache
    Content-Security-Policy
    	sandbox
    Content-Type
    	application/json
    Date
    	Fri, 10 Jun 2022 08:07:13 GMT
    Expires
    	-1
    Pragma
    	no-cache
    Transfer-Encoding
    	chunked
    X-Content-Type-Options
    	nosniff
    X-Frame-Options
    	DENY
    X-XSS-Protection
    	1; mode=block
    	
    Accept
    	application/json, text/plain, */*
    Accept-Encoding
    	gzip, deflate, br
    Accept-Language
    	en-CA,en-US;q=0.7,en;q=0.3
    Connection
    	keep-alive
    Cookie
    	grafana_session=7e4672f318dad456d90ba8ce9b004921
    Host
    	XXXXX.azurewebsites.net
    Referer
    	https://XXXXX.azurewebsites.net/datasources/edit/Tjd8xVjnz
    Sec-Fetch-Dest
    	empty
    Sec-Fetch-Mode
    	cors
    Sec-Fetch-Site
    	same-origin
    User-Agent
    	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:101.0) Gecko/20100101 Firefox/101.0
    x-grafana-org-id
    	1



https://XXXXX.azurewebsites.net/api/datasources/6/resources/azuremonitor/subscriptions?api-version=2019-03-01 returned an invalid JSON - SyntaxError: JSON.parse: unexpected character at line 1 column 1 of the JSON data fetch.ts:112:18
`

**Comment by fridgepoet** [comment]
@astafan8 in the browser, you can right-click anywhere on the page and there is some option like "Inspect" and then go to the Network tab just to check out the calls being made when you click on "Save & Test". [here's a tutorial for Edge with visuals](https://docs.microsoft.com/en-us/microsoft-edge/devtools-guide-chromium/network/)
Where is your Grafana installed? We're using a Virtual Machine on Azure and to access the logs we ssh onto the machine and view `/var/log/grafana/grafana.log`. That's described [here](https://grafana.com/docs/grafana/latest/troubleshooting/).

Also thanks @JorisVandenbroeck. You're not using docker in any way, right? And what is your version of Grafana? 

We're still looking into this.

**Comment by astafan8** [comment]
@fridgepoet thanks for the guidance! will try next week!

I am deploying grafana using it's OSS (open source) docker image as Azure AppService.

> We're still looking into this.

thanks!!

**Comment by JorisVandenbroeck** [comment]
> You're not using docker in any way, right? And what is your version of Grafana?

We are, Grafana is deployed as an Azure Web App which uses Docker hub in the backend to deploy.
Config looks like this:
![image](https://user-images.githubusercontent.com/98815294/173062276-46a47025-455c-4e4b-be89-d881359556e5.png)
This is also why in my previous posts I mentioned things like 'Log Stream' which is the Azure Web App mechanism for viewing log output.

The deployed version of Grafana is v8.5.5.

**Comment by fridgepoet** [comment]
Just a quick update: We've been able to reproduce the issue in 8.5.0 both in App Service and in a VM. We're continuing to investigate.

**Comment by astafan8** [comment]
> a question would be if @astafan8 also deployed through Docker Hub

@JorisVandenbroeck yes, indeed via dockerhub.

**Comment by fridgepoet** [comment]
Hi @kostrse, would you be able to help us investigate this issue?
We're unable to load a datasource with Managed Identity on an App Service.

Details: App Service on Azure with Grafana images from the Docker Hub (**not** able to reproduce in a VM)
Version where it is not working: [v8.5.0-beta1](https://github.com/grafana/grafana/releases/tag/v8.5.0-beta1) as well as the `latest` image corresponding right now to v9.0.0
Error response message from browser network v8.5.0-beta1:
```
unexpected error Get "https://management.azure.com/subscriptions?api-version=2019-03-01": failed to retrieve Azure access token: ManagedIdentityCredential authentication failed
GET http://xxxx/msi/token
--------------------------------------------------------------------------------
RESPONSE 400 Bad Request
--------------------------------------------------------------------------------
{
  "statusCode": 400,
  "message": "No User Assigned or Delegated Managed Identity found for specified ClientId/ResourceId/PrincipalId.",
  "correlationId": "xxxx"
}
--------------------------------------------------------------------------------
```

Version where it was last working: [v8.4.7](https://hub.docker.com/layers/grafana/grafana/grafana/8.4.7/images/sha256-03c9efd08cff9e39a93c77dc231734f2dcd48d905ff3b3034951b61477b07ca1?context=explore)

Some thoughts:
I believe that the version of the `github.com/Azure/azure-sdk-for-go/sdk/azidentity` library was bumped from `0.10.0` to `0.13.2`:
https://github.com/grafana/grafana/pull/46535/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R255

There seem to have been a number of changes around Managed Identity between those two versions and the problem may be there. Please let me know if it would be better to create an issue in the Azure/azure-sdk-for-go repo.

**Comment by astafan8** [comment]
@fridgepoet could you mention the issue number here so that we can also follow it?
