### ISSUE TITLE
configmaps of dashboards are not being updated after the grafana restart

### ISSUE THREAD

**Issue by obaranov1** [grafana/grafana#50392]
**What happened**: the graphs are not shown on the dashboard. I am trying to get the graphs in my dashboard. The dashboard is deployed via configmap with the “grafana_dashboard=1” label. Graphs are rendered in the cluster where I deployed Grafana manually without helm chart, but does not work in cluster where I deployed Grafana using kube-prometheus-stack. When I restart the Grafana deployment, configmaps are not updated as well.  I tried to update queries manually, and then graphs appeared. 

**What you expected to happen**: all graphs are visible on each panel of the dashboard.

**How to reproduce it (as minimally and precisely as possible)**: install kube-prometheus-stack and upgrade configuration using this config:

grafana:
  env:
   GF_SERVER_ROOT_URL: 'http://kube-prometheus-stack-grafana.monitoring.svc.cluster.local:3000/grafana/'
   GF_SERVER_DOMAIN: kube-prometheus-stack-grafana.monitoring.svc.cluster.local
   GF_SERVER_SERVE_FROM_SUB_PATH: true
  sidecar:
    dashboards:
      enabled: true
      label: grafana_dashboard
      folder: /tmp/dashboards
      searchNamespace: ALL

prometheus:
  prometheusSpec:
    additionalScrapeConfigs:

    - job_name: 'istiod'
      kubernetes_sd_configs:
      - role: endpoints
        namespaces:
          names:
          - istio-system
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: istiod;http-monitoring

    - job_name: 'envoy-stats'
      metrics_path: /stats/prometheus
      kubernetes_sd_configs:
      - role: pod
      relabel_configs:
      - source_labels: [__meta_kubernetes_pod_container_port_name]
        action: keep
        regex: '.*-envoy-prom'
    routePrefix: /
    externalUrl: 'https://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090/prometheus/'

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://kube-prometheus-stack-prometheus.monitoring:9090/prometheus/
      access: proxy
      isDefault: true

**Anything else we need to know?**: In Grafana logs I have the issue:
01T07:39:04.09+0000 lvl=eror msg=“Failed to look up user based on cookie” error=“user token not found”

**Environment**:
- Grafana version: helm.sh/chart=grafana-6.29.2
- Data source type & version: Prometheus Operator 
                         app.kubernetes.io/version=35.2.0
                        chart=kube-prometheus-stack-35.2.0
- OS Grafana is installed on:
- User OS & Browser: Ubuntu 20.04.3 LTS (k8s node) & Google Chrome

**Comment by obaranov1** [comment]
@ashharrison90,  the description of the issue has been updated according to the template provided. PTAL :)

**Comment by swapnilpotnis** [comment]
The issue seems to be persistent even now. Can someone change the status to OPEN?
