### ISSUE TITLE
Template Variables: Variables are not refreshed when they have the same text label

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#50424]
**What happened**:

_based on escalation: https://github.com/grafana/support-escalations/issues/2748._

When a variable has the same label( with a different value) we don't trigger a refresh when changing the value from the dropdown. 

[play.grafana.org/d/qQSWsx97k/2748-esc-variables-with-same-name?orgId=1](https://play.grafana.org/d/qQSWsx97k/2748-esc-variables-with-same-name?orgId=1)

![VariableWithSameLabelDoesNotRefresh](https://user-images.githubusercontent.com/239999/172623011-d00db662-cf48-4c46-80c8-56b8f0ae2890.gif)

Grafana Version: v9.0.0-pre (xxxx)

**Comment by JoaoSilvaGrafana** [comment]
Suspicious line we found:
https://github.com/grafana/grafana/blob/main/public/app/features/variables/pickers/OptionsPicker/actions.ts#L93

Next mob we should investigate why that line is comparing only text
