### ISSUE TITLE
graphite /render query timestamp is broken (because it's localized)

### ISSUE THREAD

**Issue by projekt01** [grafana/grafana#5042]
Grafana sends the timestamp for the Graphite /render query as a local(ized) timestamp. The timestamp used for 1.1.2016 is 1451602800 (in my timezone +0100) which is in UTC Thu, 31 Dec 2015 23:00:00 +0000. The timestamp includes the different from local to UTC timestamp.
The graphite-web library will convert such timestamp based on Django.conf.settings.TIME_ZONE
and Graphite-api will convert them based on the Graphite-api Settings.time_zone config.
This means the grahite web/api server must define the timezone which grafana sends query local (browser) or UTC
it is not possible to use another server timezone or the grafana query timestamp get not correct mapped to the Server timezone.
Graphite-api offers a tz request atttribute which if used will get used as the timezone the query get sent. But that's not supported by graphit-web. 
The only solution I see is, that grafana must send the timestamp related to UTC.
for 1.1.2016, this should be 1451606400 and not 1451602800 because grafana is running in a timezone (+0100) which includes the different between the UTC and local timezone in seconds. 
Note; your timestamp for 1.1.2016 is probably not 1451602800  if you are not in the timezone +0100

Note: this has nothing to do with the grafana browser/UTC Settings which is only used for render the Graphite data in the chart. This get correct rendered because raphite allways Returns the data with the correct epoch timestamps.

For more Information about a timestamp (not localized) see: http://www.epochconverter.com/
or http://www.epochconverter.com/timestamp-list
For timestamp conversion see: http://www.unixtimestamp.com/index.php

**Comment by torkelo** [comment]
Grafana sends the timestamp as unix epoch, which is always in UTC , so no matter if you specify local browser time in Grafana or UTC time Grafana will send the timestamp in UTC, and Graphite will always evaluate the epoch values as UTC, so it should not matter what time zone setting you have in Graphite. It has been so for quite some time and no one has reported any timezone related issues with Grafana and graphite since Grafana switched to send epochs to Graphite

**Comment by projekt01** [comment]
Thanks for the very quick answer. And thanks for the great product! 

But sorry to say that Grafana doesn't send the graphite /render query as an UTC timestamp.

The problem is, that the moment dates used for send the graphite render query (from and until) are  local dates and not UTC.

The problem seems to be located in the graphite/datasource.ts method translateTime which will generate a local moment date without a timezone.

The date.unix() method in graphite/datasource.ts line: 156 just returns
the timestamp in seconds as integer and will not convert the local date to utc.
The moment unix() method looks like:

    function unix () {
        return Math.floor(+this / 1000);
    }


The request received from grafana looks like:

CONTENT_LENGTH: 93
CONTENT_TYPE:   application/x-www-form-urlencoded
GATEWAY_INTERFACE:      CGI/1.1
HTTP_ACCEPT:    application/json, text/plain, */*
HTTP_ACCEPT_ENCODING:   gzip, deflate
HTTP_ACCEPT_LANGUAGE:   de-DE
HTTP_CACHE_CONTROL:     no-cache
HTTP_DNT:       1
HTTP_HOST:      127.0.0.1:9150
HTTP_REFERER:   http://127.0.0.1:3000/dashboard/db/tsmetric?panelId=1&fullscreen&edit
HTTP_USER_AGENT:        Mozilla/5.0 (iPad; CPU OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53
HTTP_X_FORWARDED_FOR:   127.0.0.1
PATH_INFO:      /render
QUERY_STRING:
REMOTE_ADDR:    127.0.0.1
REMOTE_PORT:    51893
REQUEST_METHOD: POST
SCRIPT_NAME:
SERVER_PORT:    9150
SERVER_PROTOCOL:        HTTP/1.1
SERVER_SOFTWARE:        gevent/1.1 Python/2.7
format: json
from:   1463176800
maxDataPoints:  1484
target: xdash.tsmetric.sampler
until:  1463263259
wsgi.errors:    <tsmetric.wsgi.server.ErrorLogger object at 0x0339EA70>
wsgi.input:     <gevent.pywsgi.Input object at 0x03CD3768>
wsgi.multiprocess:      False
wsgi.multithread:       False
wsgi.run_once:  False
wsgi.url_scheme:        http
wsgi.version:   (1, 0)

There you can see from and until.

The query was "Today" and from is "1463176800" this is:
GMT: Fri, 13 May 2016 22:00:00 GMT

And in my timezone +0100 + 1 hour daylight saving time:
Your time zone: ‎14‎.‎05‎.‎2016‎ ‎00‎:‎00‎:‎00 GMT+2:00 DST

This means I receive a local timestamp from grafana. right?

I also wondering why nobody was reporting this. But I guess if you are running Graphite with a local timezone (graphite-api) does this by default and graphite-web is using django. settings, you will not recognize the local timestamp issue.

**Comment by torkelo** [comment]
>But sorry to say that Grafana doesn't send the graphite /render query as an UTC timestamp.
>The problem is, that the moment dates used for send the graphite render query (from and until) are >local dates and not UTC.

Your wrong, try zooming on on a time range and save. Then change timezone on your local computer, the time sent to graphite will be the same and the same time range will be shown (but with different time axis, if you have selected local time in grafana). 

The problem you have is that the time range `Today` does not work as you expect. Today means mindight to midnight, so if you have local time setting will mean midnight to midnight your local time, if you have UTC selected it will mean midnight to midnight UTC time.
