### ISSUE TITLE
grafana v9.0.0-beta3 crashes when downgrading to 8.5.5 (alerting related)

### ISSUE THREAD

**Issue by briangann** [grafana/grafana#50421]
**What happened**:

Existing grafana running with 8.5.5 with alerting rules.  Upgraded to v9.0.0-beta3.  No new alerting rules were created. 
Due to a panel plugin not working properly (polystat), I reverted back to 8.5.5, and grafana crashes:

```
grafana     | logger=sqlstore t=2022-06-08T11:55:08.32+0000 lvl=info msg="Connecting to DB" dbtype=sqlite3
grafana     | logger=sqlstore t=2022-06-08T11:55:08.32+0000 lvl=warn msg="SQLite database file has broader permissions than it should" path=/var/lib/grafana/grafana.db mode=-rw-r--r-- expected=-rw-r-----
grafana     | panic: New alert rules created while using unified alerting will be deleted, set force_migration=true in your grafana.ini and try again if this is okay.
grafana     |
grafana     | goroutine 1 [running]:
grafana     | github.com/grafana/grafana/pkg/services/sqlstore/migrations/ualert.AddDashAlertMigration(0xc000b77040)
grafana     |   /drone/src/pkg/services/sqlstore/migrations/ualert/ualert.go:78 +0x797
grafana     | github.com/grafana/grafana/pkg/services/sqlstore/migrations.(*OSSMigrations).AddMigration(0xc000051340, 0xc000b77040)
grafana     |   /drone/src/pkg/services/sqlstore/migrations/migrations.go:61 +0x265
grafana     | github.com/grafana/grafana/pkg/services/sqlstore.(*SQLStore).Migrate(0xc0004e6f00, 0x0)
grafana     |   /drone/src/pkg/services/sqlstore/sqlstore.go:135 +0x6f
grafana     | github.com/grafana/grafana/pkg/services/sqlstore.ProvideService(0xc000a55600, 0x18, {0x36eff40, 0x5760838}, {0x3715a80, 0xc000b76c30})
grafana     |   /drone/src/pkg/services/sqlstore/sqlstore.go:67 +0xdc
grafana     | github.com/grafana/grafana/pkg/server.Initialize({{0x7ffcb86ccbbc, 0x18}, {0x7ffcb86ccba0, 0x12}, {0xc00004e0d0, 0x5, 0x5}}, {{0x0, 0x0}, {0x0, ...}, ...}, ...)
grafana     |   /drone/src/pkg/server/wire_gen.go:148 +0x1b6
grafana     | github.com/grafana/grafana/pkg/cmd/grafana-server/commands.executeServer({0x7ffcb86ccbbc, 0x18}, {0x7ffcb86ccba0, 0x12}, {0x0, 0x0}, {0x7ffcb86ccbe1, 0x6}, 0x0, {{0x36713e0, ...}, ...})
grafana     |   /drone/src/pkg/cmd/grafana-server/commands/cli.go:170 +0x625
grafana     | github.com/grafana/grafana/pkg/cmd/grafana-server/commands.RunServer({{0x36713e0, 0x5}, {0x3672d38, 0xa}, {0x36713d8, 0x4}, {0x3672d28, 0xa}})
grafana     |   /drone/src/pkg/cmd/grafana-server/commands/cli.go:107 +0x785
grafana     | main.main()
grafana     |   /drone/src/pkg/cmd/grafana-server/main.go:16 +0xc5
grafana exited with code 2
```

**What you expected to happen**:

downgrading with existing 8.5.5 alerts in place should not crash

**How to reproduce it (as minimally and precisely as possible)**:

spin up 8.5.5, create alerting rule, then upgrade to 9.0.0-beta3, then downgrade back to 8.5.5

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: prometheus
- OS Grafana is installed on: linux/docker
- User OS & Browser: macos/chrome
- Grafana plugins: polystat
- Others:

**Comment by tentious** [comment]
Also affected by this because I'm using latest docker image tag. Is there a workaround for this?

**Comment by RedSpid3r** [comment]
+1 Affected by this. Grafana install now unusable

**Comment by sibberio** [comment]
I have the same issue.
Yesterday, via watchtower, my instance was "upgraded" and now crash.

I read in a different post that some days ago the latest tag was containing the version 9 beta 2 and now is 8.5.5

The user was able to start again his container by restoring an older version of the DB. Here the link [https://github.com/grafana/helm-charts/issues/1451]() to this topic. Hope this can help you to solve our issue

**Comment by jpolzfuss** [comment]
Simply do what the text says and add "force_migration=true" to your grafana.ini

**Comment by himuura** [comment]
@sibberio how did you remove the alert from the db? force_migration on the .ini did not solve my issue, i got no grafana whatsoever...

**Comment by sibberio** [comment]
@himuura I have downloaded the grafana.db file from my docker container folder then open with DB Browser for SQLite. Once opened the DB I went on these tables (alert, alert_instance, alert_notification_state, alert_rule and alert_rule_version) and delete all the raws inside them. Then uploaded again after rename the original one.

@jpolzfuss I tried to set FORCE_MIGRATION to TRUE on my docker environment variable but seems is not recognized by the container

**Comment by himuura** [comment]
> @himuura I have downloaded the grafana.db file from my docker container folder then open with DB Browser for SQLite. Once opened the DB I went on these tables (alert, alert_instance, alert_notification_state, alert_rule and alert_rule_version) and delete all the raws inside them. Then uploaded again after rename the original one.
> 
> @jpolzfuss I tried to set FORCE_MIGRATION to TRUE on my docker environment variable but seems is not recognized by the container

db viewer on the grafana.db, deleted the lines on each table and copy the db back do grafana on docker. Solved my issue, grafana is now starting. i got no alerts though but still, it's solved. thanks @sibberio!!

**Comment by RedSpid3r** [comment]
> @himuura I have downloaded the grafana.db file from my docker container folder then open with DB Browser for SQLite. Once opened the DB I went on these tables (alert, alert_instance, alert_notification_state, alert_rule and alert_rule_version) and delete all the raws inside them. Then uploaded again after rename the original one.

Just adding in here that I did this and I still had issues, I had to also delete the `alerting` folder from my grafana directory but all is working now.

**Comment by blackholefinder** [comment]
Hi, got also version 9 beta 2 by "latest" tag and now container does not start again with "latest", since it points back to 8.x.
Temporary switched over to 9.0.0beta2 again to get stuff running again, but this should only be a workaround.

**Comment by armandgrillet** [comment]
The message has been clarified in https://github.com/grafana/grafana/pull/50470 which will be part of 9.0 GA and we also document this in our docs now: https://grafana.com/docs/grafana/next/alerting/migrating-alerts/roll-back/$

Closing this for now, if the community feedback shows that it's not enough we will keep on making this clearer. The reason for the crash is that we don't want users to delete Grafana Alerting alerts without realizing that fact.
