### ISSUE TITLE
migrate to new graph graph legend colour mismatch

### ISSUE THREAD

**Issue by russog** [grafana/grafana#50438]
**What happened**:
Migrate old graph to new. legend not longer match graph colour

**What you expected to happen**:
graph and legend should have the same colour

**How to reproduce it (as minimally and precisely as possible)**:

https://user-images.githubusercontent.com/2963870/172646649-881986e6-814b-457d-a6d6-b1acfc49ab15.mov

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.5.
- Data source type & version: GraphQL Data Source
- OS Grafana is installed on: Docker
- User OS & Browser: Mac/Linux both chrome
- Grafana plugins: GraphQL Data Source by FIFImon
- [Others:]

**Comment by russog** [comment]
I guess the video was not enough? to be honest I do not know whether the problem could be related the graphql plugin? I'm not sure if that would make any difference.
did you try replicating it on your local environment with a graphql query?

thanks a lot for looking into it!

**Comment by willgraham0** [comment]
I'm also experiencing this on the Time Series visualization:

Docker Image: grafana/grafana:8.5.4
Data source: InfluxDB

![Screenshot from 2022-06-10 12-17-02](https://user-images.githubusercontent.com/22656848/173054391-9879c239-c318-4014-b4c8-fa58fc893a1a.png)
ualization:

**Comment by willgraham0** [comment]
I think this is not an issue with Grafana. I think what is happening here is there are multiple timeseries being selected with the same label, so when the dashboard refreshes, it randomly grabs one of these timeseries and gives it a colour accordingly. So I think the issue was on my end!

**Comment by russog** [comment]
To be honest it happens even with a single time series….

**Comment by russog** [comment]
If look at the video that I posted I only have one time series….

**Comment by tomtastic** [comment]
Happens in v9.0.4 too
![PNG image](https://user-images.githubusercontent.com/302127/180501679-df857fbd-5bab-49d7-9254-7e5decbd103c.png)

**Comment by tomtastic** [comment]
Where I'm querying a single InfluxDB datasource 'telegraf', with :
```
from(bucket: v.bucket)
  |> range(start: v.timeRangeStart, stop:v.timeRangeStop)
  |> filter(fn: (r) => r._measurement == "zigbee2mqtt")
  |> filter(fn: (r) => r._field == "temperature")
```

**Comment by zuchka** [comment]
hey all--closing this issue in favor of https://github.com/grafana/grafana/issues/39614, which appears to be older and have a larger discussion. It's also actively tracked in a project board 👍
