### ISSUE TITLE
CloudMonitoring: Disable query not working alongside Expression 

### ISSUE THREAD

**Issue by fridgepoet** [grafana/grafana#50449]
**What happened**:
Disable (hide) query button does not seem to work when there is another Expression which references that query.

**What you expected to happen**:
Referenced query can be hidden from visualization.

**How to reproduce it (as minimally and precisely as possible)**:
1.  Create a Cloud Monitoring query, for example in Metrics
2.  Add an expression based the query from the previous step, for example a Math expression 

In the following screenshot:
Expected: `A` is hidden
Actual: `A` is still showing in the visualization
![Screen Shot 2022-06-08 at 18 10 29](https://user-images.githubusercontent.com/4163034/172665527-c6d51631-8116-4e4c-afd5-543753c156bd.png)

**Anything else we need to know?**:
First reported in https://github.com/grafana/support-escalations/issues/2810

**Environment**:
- Grafana version: v8.5.4, also confirmed in 9.0.0-pre `main`
- Data source type & version: Google Cloud Monitoring

**Comment by sunker** [comment]
Looks like a platform issue.

**Comment by skeilson** [comment]
Another customer has reported this very issue https://grafana.zendesk.com/agent/tickets/58392

Confirmed problem exists in 9.0.4, minimum.

**Comment by skeilson** [comment]
@fridgepoet any word on forward progress with this issue?

**Comment by aangelisc** [comment]
Hi @skeilson, can confirm that I've reproduced this and I'm actively investigating now 😊
