### ISSUE TITLE
Update .proto message definition according to feedback

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#50456]
https://github.com/grafana/grafana/pull/49544#discussion_r892575488

https://github.com/grafana/grafana/pull/49544#discussion_r892579693

https://github.com/grafana/grafana/pull/49544#discussion_r892583639

https://github.com/grafana/grafana/pull/50542#discussion_r895562488

- Rename message types to use <verb><subject>Request/Response convention
- Create custom response type for each endpoint instead of using SecretsErrorResponse for everything (allows for easier mods later)
- Consider renaming "RemoteSecretsManager" (remote is implied)
- Make error field into "user friendly error" so that we can show detailed and controlled error messages in the front end

**Comment by ashharrison90** [comment]
@mmandrus friendly reminder to add labels to your issues so they don't appear on the issue triage list:
![image](https://user-images.githubusercontent.com/20999846/172799901-ed7bdca8-52a2-4c8c-a89d-f7efad51ba7b.png)
