### ISSUE TITLE
[Question]  The Grafana can not identify the macro variables of ZABBIX

### ISSUE THREAD

**Issue by zhuleiandy888** [grafana/grafana#5047]
Hi,

When I created Metrics in Graph , the macro variable {$IP}, {$HOSTNAME} defined in ZABBIX can not be identified. see image below：
   
![image](https://cloud.githubusercontent.com/assets/13164631/15280426/c8c2173e-1b62-11e6-88f5-692bc583c298.png)

1. Grafana version: 3.0.1
2. Datasource: ZABBIX 2.4.7  - MYSQL Server version: 5.6.30 MySQL Community Server
3. OS:  CentOS Linux release 7.2.1511 (Core) 3.10.0-327.13.1.el7.x86_64
4. If there is no this function, can be added in the future version?

Kind regards,
andy

**Comment by torkelo** [comment]
please open questions for zabbix plugin with the zabbix plugin (it's an external project not maintained by the core  Grafana Team) 
https://github.com/alexanderzobnin/grafana-zabbix
