### ISSUE TITLE
Can not Edit Grafana Dashboard

### ISSUE THREAD

**Issue by summer0nguyen** [grafana/grafana#5048]
Hello,
I'm using Grafana with InfluxDB  for my reporting System. It's the  best solution right now for me.
However, I have got some problem since I update grafana FROM: 3.0 beta5 => 3.0 beta7 => 3.0.1 ( stable) . Here is the detail : 

- Firstly, I use Grafana 3.0 beta 5 Everything works well 
- After upgrading to Grafana 3.0 beta 7, Or even now Grafana 3.0.1 stable , I got error while editing Dashboard : 
+ See the images 
+ The grafana Log : "POST /api/dashboards/db/ HTTP/1.0" 412 Precondition Failed 88 bytes in 10042us 

- I realize that the problem may be in the Version : so, I update the version to 1, there still error : UPDATE dashboard SET VERSION =1 WHERE id=6  

Could you please explain and fix this . Thank you. 

![screen shot 2016-05-16 at 12 06 17 pm](https://cloud.githubusercontent.com/assets/6456947/15280785/ba879f8a-1b5e-11e6-8baa-3a02ff801c5f.png)

What grafana version are you using? 3.0 beta7 - 3.0.1 stable
What datasource are you using? InfluxDB
What OS are you running grafana on? CentOS 6 6.4 bits 
What did you do? Edit the Dashboard
What was the expected result? Edit updated 
What happened instead?  Editing doesn't make any changes

**Comment by summer0nguyen** [comment]
Hello,
Some more clues that I just figure out: 

1. I used domain : grafana1.example.com when I first install grafana
2. some days ago ( same time with upgrading grafana) , I change the URL to : grafana2.example.com . 

domain = grafana2.example.com
http_addr = 127.0.0.1


and Now : 
- When I access : grafana1.example.com, everything is OK 
- When I access : grafana2.example.com, I got the error above. and , I don't see Data Source , I always get 401 http response 

I think the problem is somewhere in the Session. 
I delete the directory : /var/lib/grafana/session/* and restart grafana but doesn't help.

Now, I have to temporary switch to grafana1.example.com, Plan to install a new grafana instance with domain grafana2.example.com

**Comment by torkelo** [comment]
Cannot replicate on any of our grafana servers. 

domain name should not have any effect on this. 

Did you reload the dashboard before trying to save it? 

> UPDATE dashboard SET VERSION =1 WHERE id=6

When you load the dashboard check in chrome dev tools for the api call to load the dashboard. What is the meta.version field and the dashboard.version field? 

![image](https://cloud.githubusercontent.com/assets/10999/15283319/dd61bb40-1b49-11e6-9f57-22a9455a1a8c.png)
