### ISSUE TITLE
Not able to hide X-Axis in the graph panel.

### ISSUE THREAD

**Issue by digrich** [grafana/grafana#5049]
- What grafana version are you using? -  3.0.1
- What datasource are you using? - OpenTSDB
- What OS are you running grafana on? - Linux
- What did you do? - Under Axis tab, unchecked the X-Axis Show checkbox button.
- What was the expected result? - It should hide the x-axis.
- What happenend instead? - It didn't hide.

Same behavior is noticed in play.grafana.org. This used to work in old versions.

**Comment by torkelo** [comment]
already reported and fixed, will be included in patch release 3.0.2 (probably released this week)

There are also nightly builds with the fix
http://grafana.org/download/builds.html

**Comment by digrich** [comment]
Thanks @torkelo
