### ISSUE TITLE
Doesn't Influxdb support collectd's types.db data source type?

### ISSUE THREAD

**Issue by minkikim89** [grafana/grafana#5051]
I am running collectd + influxdb + grafana.
And I read that Influxdb supports collectd.
I defined types.db with type instance and data source type(ex: DERIVE).
But influxdb stored stats just original value, not calculated value.

I know that influxdb has derivate query, but I don't want that logic because of performance.

Doesn't Influxdb support collectd's types.db data source type? Have I to use query? Isn't any other choice?

Thanks for reading :)

**Comment by bergquist** [comment]
This seems to be an questions about collectd and influxdb. 
I think it would be better suited in https://github.com/influxdata/influxdb
