### ISSUE TITLE
[Bug]Changing metrics by itself (Grafana 3.0)

### ISSUE THREAD

**Issue by Hengum** [grafana/grafana#5053]
I'm using Grafana 3.0.
I'm using Graphite with StatsD.
I'm running Grafana on a viritual machine with Ubunto. Grafana, statsD and Graphite is installad insida a container using Docker. 
I selected a metric-path insida a "single stat panel" and saved the dashboard.
the expected result was that the metrics-path would stay the same (because I saved the dashboard) as the one I sat it to be.
Instead the metrics-path changed itself to a different path without me doing anything.  

![dev tools](https://cloud.githubusercontent.com/assets/11866979/15290887/8cda7658-1b7b-11e6-9e13-e46b9265547c.jpg)
![metric](https://cloud.githubusercontent.com/assets/11866979/15290886/8cd7b012-1b7b-11e6-914a-b795891281f5.jpg)

**Comment by torkelo** [comment]
I am unable to replicate this. Does this consistently happen? Can you show recording of it or describe the steps you do? 

The first image with the render requests does not help really.
