### ISSUE TITLE
DashboardHistory: selecting one version on the history page, selects all rows

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#50534]
![Versions-select-bug](https://user-images.githubusercontent.com/434655/172887289-d95b54ea-ec79-4ecf-8f78-41bdd1beb86e.gif)

**What happened**:
When clicking on a checkbox on the versions page for a dashboard, then every row is selected.

**What you expected to happen**:
For one row to be selected when I click on the checkbox.

**How to reproduce it (as minimally and precisely as possible)**:
Can see it on our internal ops which is running latest main.

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.0-a6943cb3pre (a6943cb39) (main)
- User OS & Browser: Chrome, Ubuntu

**Comment by joshhunt** [comment]
Fixed by [50534](https://github.com/grafana/grafana/pull/50544)
