### ISSUE TITLE
[Feature Request] Annotations from templated datasources

### ISSUE THREAD

**Issue by sanga** [grafana/grafana#5054]
I realise that datasources for metrics support templating, but it seems that templating datasources for **annotation** sources does not yet exist.

To give you an example of what I'd like to do:

- I'd like to create an annotation for when our server application starts
- I can parse this from our logs ("server starting...")
- I can create an annotation source the greps that startup string from our Elasticsearch instance and that displays annotations for our server starting very nicely
however:
- we have 2 separate elasticsearch instances and templates dashboards to switch between multiple environments (e.g. staging and production). And when I switch our templated dashboard between staging and production I see all the graphs update but the 'server started' annotations don't update as annotations don't support templating.

I hope that was clear enough

- v3.0.1+1-g03663c5
- Elasticsearch
- MacOS/Chrome

Just noticed that the bottom of the elasticsearch docs page lists this as TODO http://docs.grafana.org/datasources/elasticsearch/

So yeah, that would be lovely if it were done :)

**Comment by sanga** [comment]
Thanks for the fast fix!

**Comment by sanga** [comment]
btw it's still listed as "TODO" in http://docs.grafana.org/datasources/elasticsearch/

**Comment by torkelo** [comment]
@sanga yes, that's a TODO for writing docs about elasticsearch annotations
