### ISSUE TITLE
Microsoft.ClassicCompute/domainNames not supported

### ISSUE THREAD

**Issue by jcolladokuri** [grafana/grafana#50543]
**What happened**:
Microsoft.ClassicCompute/domain names shows an error saying it is not suported: 

![image](https://user-images.githubusercontent.com/20448042/172914501-73ffdc80-62d8-4f3e-9daf-00142f189f63.png)

The fix for this was introduced in this PR: https://github.com/grafana/grafana/pull/47877

But even though my instance is on 8.5.1, I am still seeing the error

**What you expected to happen**: proper support for Microsoft.ClassicCompute/domainNames namespace

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a panel using Azure Monitor datasource
2. use metrics
3. use a sub and resource group that contain a cloud service (classic) resource
4. select Cloud service as the namespace

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.1
- Data source type & version: Azure Monitor 1.0.0
- OS Grafana is installed on: NA
- User OS & Browser: Edge, Windows
- Grafana plugins:
- Others:

**Comment by andresmgot** [comment]
Hi @jcolladokuri,

Does it work if you manually type `Microsoft.ClassicCompute/domainNames/slots/roles` in the metric namespace field? We have seen some inconsistency between the `metricDefinition` and the `metricNamespace` for that entry.

**Comment by jcolladokuri** [comment]
I get a different type of error saying that it should be domainNames only:

<img width="728" alt="image" src="https://user-images.githubusercontent.com/20448042/173415221-8d858f0f-6f58-473f-9e14-f9a68d036ac8.png">

I tried it locally though and I don't seem to be getting this error in a newer version than 8.5.1

**Comment by andresmgot** [comment]
which version are you running locally? I know that this should not happen in Grafana 9, but I am curious if it got also fixed for 8.5.

Also, what's the JSON content of your query? (The one that is failing). We have had reports in the past that the resourceName wrongly includes the  `slots/roles`, causing the issue. It should look something like:

```
{
  "targets": [{
    "azureMonitor": {
      "metricDefinition": "Microsoft.ClassicCompute/domainNames/slots/roles",
      "resourceName": "<resource_name>"
    }
  }]
}
```

**Comment by jcolladokuri** [comment]
Locally I am running 9.0.0-pre, which does not show an error for the namespace. On my AGS instance I am running 8.5.1 and that is where I am seeing the error.

The JSON model does not seem to add the `/slots/roles/` portion: 
<img width="328" alt="image" src="https://user-images.githubusercontent.com/20448042/173710005-f5a1f0e1-ecec-4ab2-9576-3eebb208d0f0.png">

The resource name also only has the resource name with no additional `/slots/roles`

**Comment by jcolladokuri** [comment]
Sorry for the delay in replying, I have been OOF.

I Tried modifying the JSON directly but still seem to run into issues, does show a different error though (this is on 8.5.1): 

![image](https://user-images.githubusercontent.com/20448042/176552063-41b3158f-8d50-459b-a71d-9f4a657ca4c0.png)


I add the slots to metricNamespace how the error message suggests and then I am back to the original error: 
![image](https://user-images.githubusercontent.com/20448042/176552377-69457481-d0d8-41c0-838c-b20e75679d20.png)

**Comment by andresmgot** [comment]
Thanks for the details @jcolladokuri, since we are trying to move away from this legacy query editor and there is no easy workaround for it. Is there anything preventing you from upgrading to 9.0 so you can avoid this issue?

**Comment by jcolladokuri** [comment]
Hi @andresmgot thank you for checking and helping out! We'll use the upgrade to 9.0 route to resolve this issue!

**Comment by andresmgot** [comment]
Great, then let me close this issue but feel free to reopen it if you still find any problem!
