### ISSUE TITLE
Error with dashboard variables parameters (Multi-value, Include All option)

### ISSUE THREAD

**Issue by NikitaElmanov** [grafana/grafana#50568]
**What happened**:
Our team has its own graph deployed on. In its functionality, I ran into a problem: the parameters do not work in the dashboard variable: Multi-value, Include All option (screenshot in the attachment).
In my opinion, the Multi-value parameter is not parsed, since if you select one element, the request works, and the Include All option parameter does not work completely, since when you select it, the panel freezes and is not updated.

Variable select query:
_SELECT DISTINCT "name" FROM "SYTESTER_DRUID"_
I want to use select query below:
_SELECT
  __time as "time",
  name as "service",
  count(sla) as " "
FROM SYTESTER_DRUID
**WHERE name in ('${service}')**
AND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})
GROUP BY __time, name_
I call variable "service" in look like '$service' and '${service}'. I received the same error in both cases.

**Environment**: Openshift
- Grafana version: grafana-enterprise:9.0.0-beta3, grafana:latest, grafana:main
- Data source type & version: druid, 0.22.1
- OS Grafana is installed on: linux
- User OS & Browser: mac os, safari
- Grafana plugins: grafadruid-druid-datasource

Maybe I make something wrong?
Screenshot where variable "service" has several parameters:
<img width="1378" alt="Снимок экрана 2022-06-09 в 14 12 28" src="https://user-images.githubusercontent.com/39399744/173020032-40812063-e61f-4152-8f25-24fae52d3e8c.png">

Screenshot where variable "service" has single parameter:
<img width="1379" alt="Снимок экрана 2022-06-10 в 11 17 32" src="https://user-images.githubusercontent.com/39399744/173022786-f326c375-4f24-4db6-997a-1deab68a133d.png">

**Comment by ashharrison90** [comment]
hi @NikitaElmanov 👋 

are you able to share the results from the query inspector to see what is being sent? 

thanks! 😄

**Comment by NikitaElmanov** [comment]
hello, @ashharrison90!
> are you able to share the results from the query inspector to see what is being sent?

**Json from query inspector:**
{
  "id": 7,
  "gridPos": {
    "h": 10,
    "w": 12,
    "x": 12,
    "y": 0
  },
  "type": "timeseries",
  "title": "Transactions",
  "pluginVersion": "8.4.0-48300pre",
  "links": [],
  "fieldConfig": {
    "defaults": {
      "custom": {
        "drawStyle": "line",
        "lineInterpolation": "smooth",
        "barAlignment": 0,
        "lineWidth": 2,
        "fillOpacity": 10,
        "gradientMode": "none",
        "spanNulls": false,
        "showPoints": "never",
        "pointSize": 5,
        "stacking": {
          "mode": "none",
          "group": "A"
        },
        "axisPlacement": "auto",
        "axisLabel": "",
        "scaleDistribution": {
          "type": "linear"
        },
        "hideFrom": {
          "tooltip": false,
          "viz": false,
          "legend": false
        },
        "thresholdsStyle": {
          "mode": "off"
        }
      },
      "color": {
        "mode": "palette-classic"
      },
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "color": "green",
            "value": null
          },
          {
            "color": "red",
            "value": 80
          }
        ]
      },
      "mappings": [],
      "unit": "none"
    },
    "overrides": []
  },
  "options": {
    "tooltip": {
      "mode": "multi",
      "sort": "none"
    },
    "legend": {
      "displayMode": "table",
      "placement": "bottom",
      "calcs": [
        "mean",
        "max"
      ]
    }
  },
  "targets": [
    {
      "builder": {
        "queryType": "sql",
        "query": "SELECT\n  __time as \"time\",\n  name as \"service\",\n  count(sla) as \" \"\nFROM SYTESTER_DRUID\n-- WHERE name in (select case when '${service}' = 'Show All' then name else '${service}' end from SYTESTER_DRUID)\nwhere name in ('${service}')\nAND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})\nGROUP BY __time, name",
        "intervals": {
          "type": "intervals",
          "intervals": [
            "${__from:date:iso}/${__to:date:iso}"
          ]
        }
      },
      "datasource": {
        "type": "grafadruid-druid-datasource",
        "uid": "P274814F1A96FB52D"
      },
      "diff_period": 1000,
      "diff_period_enabled": false,
      "diff_values": false,
      "error": {
        "config": {
          "data": {
            "query": "EXPLAIN PLAN FOR SELECT __time as \"time\", count(\"sla\") as \"tps\", \"name\" as \"service\" FROM \"SYTESTER_DRUID\"\nwhere $service = \"name\"\ngroup by __time, \"name\"\n\n"
          },
          "headers": {
            "Accept": "application/json, text/plain, */*",
            "Content-Type": "application/json;charset=utf-8",
            "X-Grafana-Org-Id": 24
          },
          "jsonpCallbackParam": "callback",
          "method": "POST",
          "retry": 0,
          "transformRequest": [
            null
          ],
          "transformResponse": [
            null
          ],
          "url": "api/datasources/proxy/142/druid/v2/sql/"
        },
        "data": {
          "error": "Unknown exception",
          "errorClass": "org.apache.calcite.tools.ValidationException",
          "errorMessage": "org.apache.calcite.runtime.CalciteContextException: From line 2, column 7 to line 2, column 14: Column '$service' not found in any table",
          "message": "Unknown exception"
        },
        "status": 500,
        "statusText": "Internal Server Error",
        "xhrStatus": "complete"
      },
      "expr": "{\"builder\":{\"queryType\":\"sql\",\"query\":\"SELECT\\n  __time as \\\"time\\\",\\n  name as \\\"service\\\",\\n  count(sla) as \\\" \\\"\\nFROM SYTESTER_DRUID\\n-- WHERE name in (select case when '${service}' = 'Show All' then name else '${service}' end from SYTESTER_DRUID)\\nwhere name in ('${service}')\\nAND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})\\nGROUP BY __time, name\",\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"${__from:date:iso}/${__to:date:iso}\"]}},\"settings\":{\"contextParameters\":[],\"format\":\"wide\",\"hideEmptyColumns\":false}}",
      "fillnull": true,
      "format": "series",
      "plan": "DruidJoinQueryRel(condition=[=($2, $7)], joinType=[inner], query=[{\"queryType\":\"groupBy\",\"dataSource\":{\"type\":\"table\",\"name\":\"__join__\"},\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"2021-11-25T11:29:40.000Z/2021-11-25T11:34:40.000Z\"]},\"virtualColumns\":[],\"filter\":null,\"granularity\":{\"type\":\"all\"},\"dimensions\":[{\"type\":\"default\",\"dimension\":\"__time\",\"outputName\":\"d0\",\"outputType\":\"LONG\"},{\"type\":\"default\",\"dimension\":\"name\",\"outputName\":\"d1\",\"outputType\":\"STRING\"}],\"aggregations\":[{\"type\":\"filtered\",\"aggregator\":{\"type\":\"count\",\"name\":\"a0\"},\"filter\":{\"type\":\"not\",\"field\":{\"type\":\"selector\",\"dimension\":\"sla\",\"value\":null,\"extractionFn\":null}},\"name\":\"a0\"}],\"postAggregations\":[],\"having\":null,\"limitSpec\":{\"type\":\"NoopLimitSpec\"},\"context\":{\"sqlQueryId\":\"d909dcd3-eb00-4c05-8f9f-23e81642f786\"},\"descending\":false}], signature=[{d0:LONG, a0:LONG, d1:STRING}])\n  DruidQueryRel(query=[{\"queryType\":\"scan\",\"dataSource\":{\"type\":\"table\",\"name\":\"SYTESTER_DRUID\"},\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z\"]},\"virtualColumns\":[],\"resultFormat\":\"compactedList\",\"batchSize\":20480,\"limit\":9223372036854775807,\"order\":\"none\",\"filter\":null,\"columns\":[\"__time\",\"message\",\"name\",\"rnd\",\"sla\",\"status\",\"value\"],\"legacy\":false,\"context\":{\"sqlQueryId\":\"d909dcd3-eb00-4c05-8f9f-23e81642f786\"},\"descending\":false,\"granularity\":{\"type\":\"all\"}}], signature=[{__time:LONG, message:STRING, name:STRING, rnd:STRING, sla:STRING, status:STRING, value:STRING}])\n  DruidQueryRel(query=[{\"queryType\":\"groupBy\",\"dataSource\":{\"type\":\"table\",\"name\":\"SYTESTER_DRUID\"},\"intervals\":{\"type\":\"intervals\",\"intervals\":[\"-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z\"]},\"virtualColumns\":[],\"filter\":null,\"granularity\":{\"type\":\"all\"},\"dimensions\":[{\"type\":\"default\",\"dimension\":\"name\",\"outputName\":\"d0\",\"outputType\":\"STRING\"}],\"aggregations\":[],\"postAggregations\":[],\"having\":null,\"limitSpec\":{\"type\":\"NoopLimitSpec\"},\"context\":{\"sqlQueryId\":\"d909dcd3-eb00-4c05-8f9f-23e81642f786\"},\"descending\":false}], signature=[{d0:STRING}])\n",
      "rawSql": "-- transactions\nSELECT __time as \"time\", count(\"sla\") as \"tps\", \"name\" as \"service\" FROM \"SYTESTER_DRUID\"\nwhere \"name\" IN($service) and $timeFilter \n--where $timeFilter\ngroup by __time, \"name\"\n\n",
      "refId": "A",
      "settings": {
        "contextParameters": [],
        "format": "wide",
        "hideEmptyColumns": false
      },
      "show_error": false,
      "show_plan": true
    }
  ],
  "datasource": null
}

**Query from inspector:**
<img width="520" alt="Снимок экрана 2022-06-10 в 18 11 55" src="https://user-images.githubusercontent.com/39399744/173096519-6aa99022-e361-4baa-9675-f6dc3affb307.png">

**Comment by gelicia** [comment]
@NikitaElmanov Sorry - one more question, can you please send details about the `service` variable? Wondering what the type is and what the other options are set to. Thank you!

**Comment by NikitaElmanov** [comment]
@gelicia, hello!

> one more question, can you please send details about the `service` variable? Wondering what the type is and what the other options are set to. Thank you!

<img width="790" alt="Снимок экрана 2022-06-14 в 07 45 38" src="https://user-images.githubusercontent.com/39399744/173495156-6a13090a-6d17-491a-a82e-bb457772551c.png">

Json from query inspector in code block):
```
{
"id": 7,
"gridPos": {
"h": 10,
"w": 12,
"x": 12,
"y": 0
},
"type": "timeseries",
"title": "Transactions",
"pluginVersion": "8.4.0-48300pre",
"links": [],
"fieldConfig": {
"defaults": {
"custom": {
"drawStyle": "line",
"lineInterpolation": "smooth",
"barAlignment": 0,
"lineWidth": 2,
"fillOpacity": 10,
"gradientMode": "none",
"spanNulls": false,
"showPoints": "never",
"pointSize": 5,
"stacking": {
"mode": "none",
"group": "A"
},
"axisPlacement": "auto",
"axisLabel": "",
"scaleDistribution": {
"type": "linear"
},
"hideFrom": {
"tooltip": false,
"viz": false,
"legend": false
},
"thresholdsStyle": {
"mode": "off"
}
},
"color": {
"mode": "palette-classic"
},
"thresholds": {
"mode": "absolute",
"steps": [
{
"color": "green",
"value": null
},
{
"color": "red",
"value": 80
}
]
},
"mappings": [],
"unit": "none"
},
"overrides": []
},
"options": {
"tooltip": {
"mode": "multi",
"sort": "none"
},
"legend": {
"displayMode": "table",
"placement": "bottom",
"calcs": [
"mean",
"max"
]
}
},
"targets": [
{
"builder": {
"queryType": "sql",
"query": "SELECT\n __time as "time",\n name as "service",\n count(sla) as " "\nFROM SYTESTER_DRUID\n-- WHERE name in (select case when '{service}' end from SYTESTER_DRUID)\nwhere name in ('{service}')\nAND __time >= MILLIS_TO_TIMESTAMP({__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})\nGROUP BY __time, name",
"intervals": {
"type": "intervals",
"intervals": [
"{__from:date:iso}/{__to:date:iso}"
]
}
},
"datasource": {
"type": "grafadruid-druid-datasource",
"uid": "P274814F1A96FB52D"
},
"diff_period": 1000,
"diff_period_enabled": false,
"diff_values": false,
"error": {
"config": {
"data": {
"query": "EXPLAIN PLAN FOR SELECT __time as "time", count("sla") as "tps", "name" as "service" FROM "SYTESTER_DRUID"\nwhere $service = "name"\ngroup by __time, "name"\n\n"
},
"headers": {
"Accept": "application/json, text/plain, /",
"Content-Type": "application/json;charset=utf-8",
"X-Grafana-Org-Id": 24
},
"jsonpCallbackParam": "callback",
"method": "POST",
"retry": 0,
"transformRequest": [
null
],
"transformResponse": [
null
],
"url": "api/datasources/proxy/142/druid/v2/sql/"
},
"data": {
"error": "Unknown exception",
"errorClass": "org.apache.calcite.tools.ValidationException",
"errorMessage": "org.apache.calcite.runtime.CalciteContextException: From line 2, column 7 to line 2, column 14: Column '$service' not found in any table",
"message": "Unknown exception"
},
"status": 500,
"statusText": "Internal Server Error",
"xhrStatus": "complete"
},
"expr": "{"builder":{"queryType":"sql","query":"SELECT\n __time as \"time\",\n name as \"service\",\n count(sla) as \" \"\nFROM SYTESTER_DRUID\n-- WHERE name in (select case when '{service}' end from SYTESTER_DRUID)\nwhere name in ('{service}')\nAND __time >= MILLIS_TO_TIMESTAMP({__from}) AND __time <= MILLIS_TO_TIMESTAMP({__from:date:iso}/${__to:date:iso}"]}},"settings":{"contextParameters":[],"format":"wide","hideEmptyColumns":false}}",
"fillnull": true,
"format": "series",
"plan": "DruidJoinQueryRel(condition=[=($2, $7)], joinType=[inner], query=[{"queryType":"groupBy","dataSource":{"type":"table","name":"join"},"intervals":{"type":"intervals","intervals":["2021-11-25T11:29:40.000Z/2021-11-25T11:34:40.000Z"]},"virtualColumns":[],"filter":null,"granularity":{"type":"all"},"dimensions":[{"type":"default","dimension":"__time","outputName":"d0","outputType":"LONG"},{"type":"default","dimension":"name","outputName":"d1","outputType":"STRING"}],"aggregations":[{"type":"filtered","aggregator":{"type":"count","name":"a0"},"filter":{"type":"not","field":{"type":"selector","dimension":"sla","value":null,"extractionFn":null}},"name":"a0"}],"postAggregations":[],"having":null,"limitSpec":{"type":"NoopLimitSpec"},"context":{"sqlQueryId":"d909dcd3-eb00-4c05-8f9f-23e81642f786"},"descending":false}], signature=[{d0:LONG, a0:LONG, d1:STRING}])\n DruidQueryRel(query=[{"queryType":"scan","dataSource":{"type":"table","name":"SYTESTER_DRUID"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"resultFormat":"compactedList","batchSize":20480,"limit":9223372036854775807,"order":"none","filter":null,"columns":["__time","message","name","rnd","sla","status","value"],"legacy":false,"context":{"sqlQueryId":"d909dcd3-eb00-4c05-8f9f-23e81642f786"},"descending":false,"granularity":{"type":"all"}}], signature=[{__time:LONG, message:STRING, name:STRING, rnd:STRING, sla:STRING, status:STRING, value:STRING}])\n DruidQueryRel(query=[{"queryType":"groupBy","dataSource":{"type":"table","name":"SYTESTER_DRUID"},"intervals":{"type":"intervals","intervals":["-146136543-09-08T08:23:32.096Z/146140482-04-24T15:36:27.903Z"]},"virtualColumns":[],"filter":null,"granularity":{"type":"all"},"dimensions":[{"type":"default","dimension":"name","outputName":"d0","outputType":"STRING"}],"aggregations":[],"postAggregations":[],"having":null,"limitSpec":{"type":"NoopLimitSpec"},"context":{"sqlQueryId":"d909dcd3-eb00-4c05-8f9f-23e81642f786"},"descending":false}], signature=[{d0:STRING}])\n",
"rawSql": "-- transactions\nSELECT __time as "time", count("sla") as "tps", "name" as "service" FROM "SYTESTER_DRUID"\nwhere "name" IN($service) and $timeFilter \n--where $timeFilter\ngroup by __time, "name"\n\n",
"refId": "A",
"settings": {
"contextParameters": [],
"format": "wide",
"hideEmptyColumns": false
},
"show_error": false,
"show_plan": true
}
],
"datasource": null
}
```

**Comment by jbguerraz** [comment]
Hello @NikitaElmanov 
Try with `in (${service:sqlstring})`. That's what we're using (since it's sql) and it works (at least until grafana 8).
The new variable API is not yet required AFAIK; you may confirm for grafana 9 @gelicia ?
Thank you!

**Comment by gelicia** [comment]
Yep, what @jbguerraz says is right, you will need to format the string since it is going into a sql statement. Please see https://grafana.com/docs/grafana/latest/variables/advanced-variable-format-options/ for more information and other format alternatives. Feel free to open the ticket if this doesn't work for you.

**Comment by NikitaElmanov** [comment]
> Try with `in (${service:sqlstring})`. That's what we're using (since it's sql) and it works (at least until grafana 8).
> The new variable API is not yet required AFAIK; you may confirm for grafana 9 @gelicia ?
> Thank you!

@jbguerraz thanks so much!
${service:sqlstring} is working for 'multiple option' but 'All option' does not work for me.
select query is looking like this:
```
SELECT
  __time as "time",
  name as "service",
  count(sla) as " "
FROM SYTESTER_DRUID
-- WHERE name in (select case when ${service:sqlstring} = 'Show All' then name else ${service:sqlstring} end from SYTESTER_DRUID)
where name in (${service:sqlstring})
AND __time >= MILLIS_TO_TIMESTAMP(${__from}) AND __time <= MILLIS_TO_TIMESTAMP(${__to})
GROUP BY __time, name   
```

**Comment by gelicia** [comment]
@NikitaElmanov How about splitting out the two cases in an OR instead of everything in the case statement?

```...
WHERE (${service:sqlstring} = 'Show All' OR name in (${service:sqlstring}))

**Comment by NikitaElmanov** [comment]
> How about splitting out the two cases in an OR instead of everything in the case statement?
> 
> ```
> WHERE (${service:sqlstring} = 'Show All' OR name in (${service:sqlstring}))
> ```

This is what I wanted! Thank you very much!
I did not find anything about 'OR' construction in documentation. It would be so useful for future developers if you add information about 'OR' in documentation with several examples.
