### ISSUE TITLE
Grafana 3.0.1  - Anonymous Dashboard Organization

### ISSUE THREAD

**Issue by tundratim** [grafana/grafana#5056]
After much headscratching and poking about, I'm unable to answer the questions below and am hoping some kind soul can point me in the right direction:

- Is there a way to edit the default dashboards an anonymous user sees?  Ideally, I'd like to add references to dashboards from different organizations.

- What is the current state of the code as regards to permitting multiple orgs to be seen anonymously?

Thanks,

**Comment by torkelo** [comment]
I am not sure what you mean "edit the default dashboards", what default dashboards? 

Dashboards are local to only one organization. Organizations are for multi tenant installations where you have one grafana server running for DIFFERENT isolated companies.  

Multiple anonymous orgs will likely nerver be implemented, the needs for that should be solved some other way.

**Comment by tundratim** [comment]
> I am not sure what you mean "edit the default dashboards", what default dashboards? 

Sorry I was not more specific.  What I meant is, how does one edit what is presented to an anonymous user (i.e., not logged in).  I guess another way to ask this would be, how does one edit the anonymous dashboard.

Thanks
