### ISSUE TITLE
Auth: case insensitive add usage stats and prometheus metrics

### ISSUE THREAD

**Issue by Jguer** [grafana/grafana#50567]
Adding usage stats on case sensitive logins should allow us to estimate the impact of making case insensitive logins obligatory for grafana.

**Definition of Done**:

### Add usage statistics:
- [x] Number of users with duplicate entries - PR https://github.com/grafana/grafana/pull/50724
ex: 

count of

```
SELECT
    a.login,
    a.email,
    (SELECT login FROM user WHERE (LOWER(login) = LOWER(a.login)) AND (login != a.login)) AS dup_login,
    (SELECT email FROM user WHERE (LOWER(email) = LOWER(a.email)) AND (email != a.email)) AS dup_email
FROM user a
WHERE (dup_login IS NOT NULL OR dup_email IS NOT NULL)
```

- [x] Number of users with mixed casing in DB

ex:

```
SELECT COUNT(*) as mixed_cased_users
FROM user
WHERE (LOWER(login) != login OR lower(email) != email) 
```

### prometheus metrics
We should make the prometheus metrics non-heavy on the prometheus engine. Specifically to update the metric from a background job every 4h to remove database code from the Prometheus critical path, following the conversation of the earlier PR - https://github.com/grafana/grafana/pull/50724#issuecomment-1162883884
- [x] add prometheus metrics on `duplicate_user_entries` - PR https://github.com/grafana/grafana/pull/52162
- [x] add prometheus metrics on `mixed_cased_users`

**Comment by eleijonmarck** [comment]
updated the issue with prometheus metrics tasks and explaination

**Comment by Jguer** [comment]
You should be able to, the stat itself only gets updated every 30 min meaning it should not be blocking the DB

**Comment by eleijonmarck** [comment]
@Jguer adding prometheus metrics in this PR https://github.com/grafana/grafana/pull/52162. updated the description of the issue.

Will tackle the `mixed_users` stats and metric in another PR
