### ISSUE TITLE
Export CSV in Grafana as per Time correction settings

### ISSUE THREAD

**Issue by ankaggar** [grafana/grafana#5059]
Hi Team,
Whenever I am Exporting CSV for any graph, the time it shows is GMT time zone, while when I can see in the graph, it shows browser's time zone because I have selected Browser in Time Correction Setting.
Can't we use the same logic for downloading CSV as well?

Any help would be appreciated.
- What grafana version are you using?
  Grafana version: 1.9.0  
- What datasource are you using?
  NA
- What OS are you running grafana on?
  Linux
- What did you do?
  Chose the Time Correction as Browser
- What was the expected result?
  CSV file should be generated in Browser timing or as per Time correction setting.
- What happened instead?
  Time is coming in CSV file in UTC format instead of Browser time, although the Time correction setting is Browser.

**Comment by sebbalex** [comment]
any update on this?

**Comment by chaitanya-ather** [comment]
+1 for this.
Downloaded csv data is almost misleading because we are expecting the data appear with the same time zone as viewed in the browser.
