### ISSUE TITLE
Icon Panel: svg support

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#50597]
We need to sanitize all user-uploaded SVG files in order to avoid XSS attacks. The go-to JS library for this task seems to be [DOMPurify](https://github.com/cure53/DOMPurify) - unfortunately it looks like there is no golang alternative.

Reference: https://owasp.org/www-pdf-archive/Mario_Heiderich_OWASP_Sweden_The_image_that_called_me.pdf

**Comment by ArturWierzbicki** [comment]
I see at least these options:

1. go with some relatively untested golang library
2. roll our own implementation (possibly with [bluemonday](https://github.com/microcosm-cc/bluemonday))
3. use `image-renderer` for sanitization - no `svg` upload if `image-renderer` isn't available
4. [convert svgs to jpgs on the UI](https://stackoverflow.com/questions/3975499/convert-svg-to-image-jpeg-png-etc-in-the-browser) for smooth upload UX, disallow svg upload
5. add config option for enabling svg uploads + "use at your own risk" note
6. do not support svgs

thoughts @ryantxu @grafana/grafana-edge-squad ? I am not sure what would be the impact of the 4th option on the overall UX (e.g. dynamically resizing icons in canvas), but it honestly looks like the easiest/most viable approach

**Comment by ryantxu** [comment]
I think worth evaluating option 2 -- if we can do it with options to bluemonday, that seems like the best option

3... maybe for cloud
5... fine for OSS

4,6 -- not good options.  SVG is pretty powerful/necessary :)

**Comment by marefr** [comment]
@ArturWierzbicki did you evaluate option 2? Would be interesting to hear why [bluemonday](https://github.com/microcosm-cc/bluemonday) doesn't work. Option 3) feels like a hack and not convinced putting it into the image renderer make sense

**Comment by ArturWierzbicki** [comment]
hey @marefr ! Some more context on input vs output sanitization

The options I posted were about input sanitization, that is striping the bad staff out of SVGs during the upload, right before saving them to the DB. This should ensure that SVGs served from your Grafana instance (potentially with public access - `https://your-grafana.com/assets/abc.svg`) are script-free. 

However, we will still likely implement UI-based output sanitization, because not all files used in the UI will go through the user-upload path. So, while input sanitization is great, output sanitization is still necessary, _and_ sufficient in most cases (caveats - csp, `content-disposition: attachment;`). That is my current understanding - I'll go through the whole file upload story with the security team once it's in a demoable state

Now, for the libraries: bluemonday's author is our own @buro9 :) We would need to modify the library's internals to support SVGs, which is a project on its own. It's doable, but it does add some risk (both via missing vulns and via overly constraining whats possible) and maintenance overhead. DOMPurify can be used as-is, with a minimal development effort. On top of that, it's battle-tested and pretty popular (2mln weekly downloads). 

In general, I agree that using bluemonday seems to be the _ideal_ option that we should eventually adopt. 
However, in the context of this feature, I think that adding a new capability to the existing Node process is a good enough implementation, since
- input sanitization is a strong "should", rather than an absolute "must"
- the NodeJS ecosystem solves this problem
- we already have the infra required to use leverage NodeJS ecosystem (kind of :))

**Comment by AgnesToulet** [comment]
> The overhead of creating (CI, packaging, publishing, docs, ...) and maintaining a new plugin is IMO not worth it for this functionality, especially since it's not intended to be the target/final implementation

This process is quite standardized now I think and creating a new plugin shouldn't be much more work than updating an existing one. 

But I wonder then, what would be the target implementation and do you have an idea on when you'll be able to switch to this implementation?

**Comment by AgnesToulet** [comment]
OK thanks for the info! I'm just thinking about deprecating this in the future, when the target implementation will be done. It will also be a bit of work to smoothly remove this from the image renderer - work that wouldn't be required if this is a separate plugin (you can then leave the plugin as-is and say it's not maintained anymore).

**Comment by marefr** [comment]
@ArturWierzbicki thanks for that thorough response. Sorry for the slow response. 

What's the planned release for this upload feature/icon panel? Feels like disable svg upload by default that you can enable with a config setting could at least buy us some time not having to stress something out now? 

Otherwise, I'm with @AgnesToulet here creating a new kind of plugin.

7) Sounds interesting as well

**Comment by ArturWierzbicki** [comment]
@AgnesToulet 
> OK thanks for the info! I'm just thinking about deprecating this in the future, when the target implementation will be done. It will also be a bit of work to smoothly remove this from the image renderer - work that wouldn't be required if this is a separate plugin (you can then leave the plugin as-is and say it's not maintained anymore).

Copy pasting from slack convo - 


> I looked into the bundled backend plugins today! It looked possible, cause we do have a special “plugins-bundled” folder, although its not yet used for backend plugins. There were two main issues I ran into
> 1. the lack of scripts to support backend plugins, both for development and publish. This gets especially gnarly especially as we have many supported distros (arm!)
> 2. the size of the binary. I created a stripped down version of the IR plugin (no http, no chrome, no puppeteer, minimal deps) on sanitizer-stripped-down-version branch and the resulting binary weighs around 70mb~~ - that’s close to the binary size of Grafana’s backend 😓 

-> lots of work as well, easily balancing out the work needed to deprecate the new code added to renderer.

re: 7 rephrased copy paste

> I looked into this, but I am not a huge fan. This is basically an embedded JS interpreter; a v8 alternative written in golang that is still under the development. It means an extra build step on the backend where we build & minify the JS code consisting of our custom code, the dompurify NPM package, and the `jsdom` with its 27 dependencies! to a Goja-executable string, and then call that script on each sanitize request. 

I _think_ we are on the same page now - looking forward to your review:)

> What's the planned release for this upload feature/icon panel? Feels like disable svg upload by default that you can enable with a config setting could at least buy us some time not having to stress something out now?

As soon as we can! :) IR is a working solution that we can later replace - I don't think this should be a blocker. Added my thoughts on #7 above

**Comment by AgnesToulet** [comment]
Working on the review right now but I'd just like to bring this solution one last time: what about creating a specific plugin for that? (even if we can't make it a bundled plugin, I think it still has some pros to consider) 

From my point of view (and what you said @ArturWierzbicki earlier), here are the pros and cons for this solution:
**Pros**:
- Cleaner code as it keeps the image rendering feature and the sanitizing feature separate (both in the image renderer plugin code but also in Grafana)
- A cleaner code is easier to extend and maintain in the future - I saw in Ryan's review in the image renderer that you may want to use that for other things than SVG.
- Could be a good target implementation (we also discussed getting rid of NodeJS for the image renderer and build something in Golang multiple times but years later, we are still here as it still seems the best solution).
-  But if it isn't the target implementation, no deprecation overhead - deprecating a plugin is easier than breaking changes in a maintained plugin.
- *Create a new plugin type would allow anyone to build their own sanitizer plugin* (Is it a real pro? I'm missing context there to know if some users could be interested to build their own sanitizing rules or if everyone wants the same rules to be safe).

**Cons**:
- Users will be required to install a plugin to be able to upload SVGs (for me it's a small con as users would need to install / upgrade the renderer plugin to upload SVGs anyway)
- Overhead of creating (CI, packaging, publishing, docs ...) and maintaining a new plugin

If the last pro is a real pro, I think it's totally worth the cons. Else, IMO pros are worth the cons but I guess it would depend on how much overhead creating and mainting a plugin really is (I think it's not so much but as we are talking about a NodeJS plugin, there may be surprises...).
