### ISSUE TITLE
Storage: limit the # of uploaded files 

### ISSUE THREAD

**Issue by ArturWierzbicki** [grafana/grafana#50608]
As part of https://github.com/grafana/grafana/issues/48259, we will allow the users to upload images via the new FS API and store them in our SQL DB. We need to put a configurable cap on the # of uploaded files to avoid overloading the DB, especially in a cloud environment.

#### 1. Should we take into account all files, regardless of how they ended up in the storage? Storage can contain e.g.:
   - images uploaded through a form in the UI
   - dashboards created manually in the UI
   - dashboards imported via JSON in the UI
   - files manually put in the storage (direct sql write etc)
   - ...
#### 2. Lets consider the simple image upload case - should we have different limits per use case and differentiate between e.g. uploading files to be used in panels vs files to be used for custom branding? Scenario:
   - Grafana is setup with a 1000 limit for uploaded files   
   - Users exhaust the limit and upload all 1000 files
   - An admin tries to set up custom branding - this requires him to upload additional images. Should we stop him?
#### Opt 1 - add some kind of a "count" function to the [FS API](https://github.com/grafana/grafana/blob/6243c72a863ddc6b816f685a3aafab7026c41c71/pkg/infra/filestorage/api.go#L159-L170) 

We could add a `Count(filter)` function to the FS API and compare its result with the limit. This implementation won't be the most efficient, especially with object storage backends and filters.

#### Opt 2 - use `SearchV2` 

We can also query the `SearchV2` service instead of going directly to the storage. As a nice side effect, implementing limits per use case or entity type will be a lot simpler, since `SearchV2` will contain all the metadata necessary for creating these filters.

**Comment by ArturWierzbicki** [comment]
I think we can go for the following in 9.1, assuming that a) both custom branding and icon panel target that release, and b) we will not use the FS API for any other entity type in that release

1. set the limit for all files, regardless of entity type
2. custom branding images should not count towards the configurable limit, BUT they should have a separate cap
3. limit per org, to match the storage per org convention
4. apply to all backends

as for the implementation, using `SearchV2` seems like a perfect fit. We currently don't index uploaded files but we have enough time to make that happen.

thoughts? @ryantxu @grafana/grafana-edge-squad

**Comment by ryantxu** [comment]
We have a quota service... maybe we can leverage that?

I am less worried about this getting abused at this point -- it is still limited to admin users, and the numbers should be pretty low.  We could cap the number of files, but I expect it will be pretty low

**Comment by ArturWierzbicki** [comment]
@ryantxu I think the main risk is cloud deployment, where org admins could still abuse that feature. From what I understand, the quota service:
- needs to be called on every new entity
- stores the state in the DB
- currently does not support decrementing the current count (related iss https://community.grafana.com/t/quota-reached-grafana-cloud-free/46742 ?)

Which means we would need to modify it so that its kept in sync with filestorage.. which imo is searchv2's purpose. Alternatively, we could just set something high (1000?) just to prevent extreme abuse and hope no real users run into the limitation?
