### ISSUE TITLE
 [Feature Request] Allow color RGB/HEX codes as input for threshold colors

### ISSUE THREAD

**Issue by drewboswell** [grafana/grafana#5061]
Currently colors for thresholds are set by manually using the color palette, however when we need to edit multiple styles on (x) number of panels it becomes a pain to maintain the same color settings.

An easy way to counter this would be to accept RGB/HEX codes, for instance CSS style \#111111 settings. This would also open the door to templating the colors, updating all panels with css-color value in one go would be possible.

--- Configuration Info ---
Grafana V. 3.0.2
Datasource: graphite/elasticsearch
Server OS: Linux x64

**Comment by Sutrannu** [comment]
This should be a high priority accessibility issue. Color-blind users have no method of working with the interface without the use of coded coloring.

**Comment by torkelo** [comment]
This is not going to be needed as thresholds for the Graph panel is going to be rewritten to align with the new alerting features v4.0, thresholds will be migrated to "visual only alert", where you can still set two thresholds, but the color will be defined by Grafana and not set by the user
