### ISSUE TITLE
Anonymous user with editor role is missing dashboard controls

### ISSUE THREAD

**Issue by jphx** [grafana/grafana#50628]
We want our anonymous Grafana users to be able to create and import dashboards.  We therefore include this configuration:

```yaml
[auth.anonymous]
enabled = true
org_role = Editor
```
**What happened**:

This has worked well for us until v8.5.0 and later releases.  Starting with v8.5.0, the controls on the gui to create and import dashboards are missing.  They appear as:

![grafana-plus-button](https://user-images.githubusercontent.com/14140294/173096694-763d363b-e89b-440f-a82e-778dc1b337c7.png)

instead of:

![image](https://user-images.githubusercontent.com/14140294/173096921-6c807d99-d1a9-4780-b04a-a927de57c0a0.png)

If I click on the icon on the left that looks like four squares and select `Browse`, I see a page that offers an `Import` button.  When I click on that, I see the following:

![grafana-import-page](https://user-images.githubusercontent.com/14140294/173099561-1f8e7384-2e4f-4ef4-8498-05ee4f03ea19.png)

The 404 "Page not found" appears where there is normally a header, like this:

![image](https://user-images.githubusercontent.com/14140294/173100008-a0f152da-3d07-49d4-8579-dbfa4e591f2a.png)

Interestingly, if I upload json from this page, it does work.

**What you expected to happen**:

I would like to restore the pre-v8.5.0 behavior where it is possible to grant anonymous users the `Editor` role.

**How to reproduce it (as minimally and precisely as possible)**:

Use the configuration above with a Grafana release of v8.5.0 or later.

**Comment by gamab** [comment]
Thanks for reporting in such details. I took a look at this and could reproduce.

The faulty lines are: [pkg/api/index.go#L580](https://github.com/grafana/grafana/blob/3ace91016ebf7034f95ce1843370b36d96c6a18c/pkg/api/index.go#L580),  [pkg/api/index.go#L591](https://github.com/grafana/grafana/blob/3ace91016ebf7034f95ce1843370b36d96c6a18c/pkg/api/index.go#L591) and  [pkg/api/index.go#L601](https://github.com/grafana/grafana/blob/3ace91016ebf7034f95ce1843370b36d96c6a18c/pkg/api/index.go#L601)

`ac.ReqSignedIn` restricts access to signed in users, preventing anonymous users from getting the links.

I'll work on a fix and hopefully will get it in by next week. 
Switching to newer versions (> v9.0.0) the problem should not be present as we use RBAC permissions instead.

**Comment by gamab** [comment]
Fix has been merged in v8.5.x

**Comment by jphx** [comment]
Thank you very much!
