### ISSUE TITLE
[Bug] / [Question] Grafana terms and geo hash grid problems

### ISSUE THREAD

**Issue by evil2bart** [grafana/grafana#5062]
Hi :-)

I am trying to use the new Worldmap panel on grafana v. 3.0.1, but ran into problems. When I try to select my ElasticSearch geo_point field, it is no where to find in Grafana from the dropdown menu (but can find it in Kibana).
(the same goes for the Graph panel)

By doing a little investigation, I can see that Grafana does not find any of my fields that contain a "." in the name, like: address.zipcode and address.street.

So my request is: can grafana please also accept these kind of fields? :-)

**Comment by torkelo** [comment]
nested bucket aggs is not implemented yet, https://github.com/grafana/grafana/issues/4693

**Comment by evil2bart** [comment]
Thanks for quick response 👍
