### ISSUE TITLE
[Feature Request] Tooltip mode All series coloring

### ISSUE THREAD

**Issue by discoduck2x** [grafana/grafana#5063]
In 3.0.0-beta3 when using **Tooltip Mode All series** you would get the mouse hover over series colored in orange like this:
![image](https://cloud.githubusercontent.com/assets/12600004/15317108/5caa73ac-1c20-11e6-87af-dc8edb7022f1.png)

but in 3.0.2 its just bold white which makes it hard to see - please revert to the more distinct coloring!

**Comment by torkelo** [comment]
it was changed as the color did not match the line/series color

**Comment by discoduck2x** [comment]
@torkelo  ok but do you think its better to just have it bolded in white? if so then i need to request work sponsored terminal glasses ;)
