### ISSUE TITLE
Remove Angular dependencies from OpenTSDB

### ISSUE THREAD

**Issue by szabalza** [grafana/grafana#50639]
Migrate the annotations and query builder in OpenTSDB from angular to React and remove all angular code in the datasource.

**Comment by torkelo** [comment]
The plan is I think to remove this plugin and make it external and community supported

**Comment by evandandrea** [comment]
- This week: starting with the annotations, should be done this week. Query editor will be more complicated, but have examples to work from (Graphite).
- Conservatively estimating 3-4 weeks for the query editor. Will re-review estimate a couple of weeks in.

**Comment by bohandley** [comment]
Annotations are [merged](https://github.com/grafana/grafana/pull/53856), moving onto the query builder. PThe plan for migrating the query builder is [here](https://docs.google.com/document/d/1HQ5xb8VZ0EKMgLtkacem1x5tJWjrD2Zs5lk81pz38Eo/edit#), it is a WIP. I will be adding testing scenarios as I work on the code.

**Comment by evandandrea** [comment]
@bohandley this week: work on OpenTSDB query editor (~40% done), tags section next.

**Comment by bohandley** [comment]
Completed the filter section and moving onto tags section and revisiting error handling next (~60% done).
