### ISSUE TITLE
[Bug] Template expansion broken in "Link to Graph in Prometheus"

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5064]
Using Grafana 3.0.0 with Prometheus on CentOS

Graphs are shown correctly when using templates, but "Link to Graph in Prometheus" expands them incorrectly.

Query:

`sum(irate(ifInErrors{fqdn=~"$ciscos"}[2m])*8)`

Template expands to:

`foo1.bar.net|foo2.bar.net`

Used to get a graph (HTTP URL Encoding made human readable):

`http://source.url/api/datasources/proxy/1/api/v1/query_range?query=sum(irate(ifInErrors{fqdn=~"foo1\\.bar\\.net|foo2\\.bar\\.net"}[2m])*8)&start=1463390616&end=1463477016&step=240`

Clicking "Link to Graph in Prometheus" produces and puts into Prometheus' PromQL prompt: 

`sum(irate(ifInErrors{fqdn=~"{foo1.bar.net,foo2.bar.net}"}[2m])*8)`

Note two problems:
1. Insertion of spurious curly brackets
2. comma instead of pipe

JSON dump of the template:

````
  "templating": {
    "list": [
      {
        "allFormat": "pipe",
        "current": {
          "text": "All",
          "value": "$__all"
        },
        "datasource": null,
        "includeAll": true,
        "label": "All Ciscos",
        "multi": true,
        "multiFormat": "pipe",
        "name": "ciscos",
        "options": [
          {
            "text": "All",
            "value": "$__all",
            "selected": true
          },
````

**Comment by bergquist** [comment]
closed by https://github.com/grafana/grafana/pull/5074

**Comment by RichiH** [comment]
Thanks, and thanks @mtanda.

Richard

Sent by mobile; excuse my brevity.

**Comment by RichiH** [comment]
@bergquist Will there be a point release soon-ish or do I need to switch to Git for this fix?

**Comment by bergquist** [comment]
@RichiH Should be a point release coming soon.
