### ISSUE TITLE
Datasource of type "alertmanager" showing errors

### ISSUE THREAD

**Issue by MStumpp** [grafana/grafana#50648]
**What happened**:

Installed Prometheus and Grafana via prometheus-community/kube-prometheus-stack helm chart via:

helm upgrade \
--set grafana.additionalDataSources[0].name="Prometheus Alertmanager" \
--set grafana.additionalDataSources[0].type="alertmanager" \
--set grafana.additionalDataSources[0].url="http://prometheus-kube-prometheus-alertmanager.monitoring:9093/" \
--set grafana.additionalDataSources[0].access="proxy" \
--set grafana.'grafana\.ini'.plugins.enable_alpha=true \
prometheus prometheus-community/kube-prometheus-stack

Installation succesful.

However, following errors showing up:

![Bildschirmfoto 2022-06-12 um 23 12 46](https://user-images.githubusercontent.com/1505314/173253961-71ad7460-41ac-4b6a-8e93-2dab54b2d50e.png)
![Bildschirmfoto 2022-06-12 um 23 12 29](https://user-images.githubusercontent.com/1505314/173253967-ed2d3044-b777-49c9-8de9-c31a49909407.png)

**What you expected to happen**:

Managing alerts provided by Prometheus Alertmanager with Grafana.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run the above helm command
2. Go to "Data source" = >  "Prometheus Alertmanager" => "Implementation" => Select "Prometheus"
and/or
3. Go to "Alert rules" = >  "Notification policies"

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.3
- Data source type & version: type: alertmanager
- OS Grafana is installed on: -
- User OS & Browser: Chrome Browser Version 102.0.5005.61 (Offizieller Build) (x86_64)
- Grafana plugins: None besides default plugins
- Others: -

**Comment by towolf** [comment]
I think you can try to add this:

`--set grafana.additionalDataSources[0].jsonData.implementation="prometheus"`

Found here: https://dev.to/mikeyglitz/proactive-kubernetes-monitoring-with-alerting-58en#:~:text=implementation%3A%20prometheus

**Comment by jimethn** [comment]
I am having this issue in Grafana 9.0.2

**Comment by konrad147** [comment]
I believe the lack of proper documentation has caused this issue. I created a [PR](https://github.com/grafana/grafana/pull/63611) with the docs update
