### ISSUE TITLE
Support wildcards when signing plugins

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#50652]
**Why?**
We have introduced different types of signatures in manifest v2 https://github.com/grafana/grafana/pull/29240. One of those, `signatureType` `private` requires a `rootUrls` parameter to define list of urls that the plugin is authorized to run on.
Even though it is possible to pass a list of URLs as a value for this parameter, it is not always easy for plugin maintainers to know in advance what URLs they want to support.  To address this issues we would like to extend this functionality to enable wildcard plugins signing. 

Based on feedback from https://github.com/grafana/grafana/issues/36355, https://github.com/grafana/grafana/discussions/48914 and internal discussions.

**What do we want to offer?**
Based on our internal [discussions](https://docs.google.com/document/d/1LvXJoKKlJXHG-0tgXsDFC00xvjvlhISilucyhMgUods/edit) we want to go with the following proposal (Proposal 2 in the doc):
- Introduce a new plugin signature type. Name is up to the one taking over this ticket, talk to the plugins platform squad to align on naming.
- On grafana side it should allow any wildcards given by this plugin type, so less restrictive than https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/signature/manifest.go#L148-L177
- On signing api side (GCOM) we should manually maintain a whitelist per plugin slug of allowed wildcards, whoever want's to use wildcard signing should reach out to us. This can be done very lightweight in the beginning until we see how much demand is really there.
- The signing requests for the new plugin signature type that do not match the wildcard must be rejected.

**What different kind of wildcards do we want to add support for?**

| rootUrl  | Grafana instance URL | Should Match | Notes |
| ------------- | ------------- | ------------- |------------- |
| `*.example.com`  | `https://test.example.com`  | ✅  |  |
| `*.example.com`  | `https://more.test.example.com`  | ❌ |  |
| `**.example.com`  | `https://test.example.com`  | ✅  |  |
| `**.example.com` | `https://more.test.example.com`  | ✅ |  |
| `https://www.example.com/*`  | `https://www.example.com/grafana1` | ✅ |  |
| `https://www.example.com/**`  | `https://www.example.com/other/grafana2`  | ✅ |  |
| `https://www.example.com/*`  | `https://www.example.com/somethingelse` | ✅ |  |
| `https://www.example.com/grafana3`  | `https://www.example.com/grafana1`  | ❌ | should already be the case |
| `https://www.example.com/grafana*`  | `https://www.example.com/grafana1`  | ✅ | |
| `https://www.example.com/grafana*`  | `https://www.example.com/somethingelse`  | ❌ |  |
| `https://www.example.com/grafana`  | `https://www.example.com/grafana1`  | ❌ | should already be the case |
| `https://*.example.com/*`  | `https://www.example.com/grafana1`  | ✅ |  |
| `https://example.*`  | `https://www.example.com/grafana1`  | ❌ | we do not want to support wildcards without TLDs |

**Notes**
- We have similar url matching in grafana enterprise license validation

**Comment by wbrowne** [comment]
Just want to clarify the following should be `false` right? 🤔 

![image](https://user-images.githubusercontent.com/1173299/177744435-5a52c547-de56-4c07-ae42-678327fcad2a.png)

**Comment by marefr** [comment]
> Just want to clarify the following should be `false` right? thinking
> 
> ![image](https://user-images.githubusercontent.com/1173299/177744435-5a52c547-de56-4c07-ae42-678327fcad2a.png)

Yes would imagine that. Looks like the intention might have been to use `https://www.example.com/**` as rootUrl in the example?

**Comment by sinspiral** [comment]
Hi! I have noticed that the tool for signing is always returning an error:

````
npx @grafana/toolkit plugin:sign --rootUrls https://*.domain.com --signatureType private-glob
  Building manifest...
  Signing manifest...
  Error: Error signing manifest: Root Url is not permitted: https://*.domain.com/
```

I don't see yet anywhere in the documentation about how to use this new feature.

Is there something I am missing? 

Thanks!!

**Comment by tolzhabayev** [comment]
Hey there @sinspiral 👋 
This feature is not GA. 

We are currently testing this feature out with customers that have internal tools they want to distribute. Please write me on timur.olzhabayev@grafana.com or in our community slack and tell me about your use case.
