### ISSUE TITLE
Max value changes in Zoom in

### ISSUE THREAD

**Issue by jesusgalvezos** [grafana/grafana#50654]
**What happened**:

When Zoom is done, values change.

**What you expected to happen**:

Values must be the same.

**How to reproduce it (as minimally and precisely as possible)**:

Just doing Zoom in graph.

![imagen](https://user-images.githubusercontent.com/69301954/173309249-af6ad19d-c94a-4c7b-b539-c3ceb7ab6659.png)

![imagen](https://user-images.githubusercontent.com/69301954/173309327-54569aa5-7f8b-44f0-84f3-83bd0f70d173.png)

**Anything else we need to know?**:

No 

**Environment**:
- Grafana version: 7.5.10
- Data source type & version: InfluxDB 
- OS Grafana is installed on: RedHat 7.4
- User OS & Browser: Debian 9 Firefox
- Grafana plugins: -
- Others: -

**Comment by gelicia** [comment]
@jesusgalvezos Can you provide your query for the second image? I think you might be showing more than the in and out values - if you look carefully, there is a very faint light blue outline inside the larger blue parts that looks to correspond to the data in the zoomed out view. The same with the red parts. The tooktip provided shows three groups of in and out values that are all layered on top of each other. I'm guessing the zoomed out view is only showing one of the smaller layers and the zoomed in view has more, and the smaller layer gets lost being the same color as one of the other layers. 

![zii](https://user-images.githubusercontent.com/1533128/173369734-88244181-17f3-4681-a5eb-776bf6c6f469.png)

**Comment by jesusgalvezos** [comment]
But maybe you are right:

In Zoom out we can see four metrics:

![imagen](https://user-images.githubusercontent.com/69301954/173535483-5c628d61-cf8e-4ed3-99ad-a523376cd70f.png)

In Zoom in we can see more:

![imagen](https://user-images.githubusercontent.com/69301954/173535629-6a5af8d1-0eac-4295-91e1-d39af6b15350.png)

Why is this happening?

**Comment by jesusgalvezos** [comment]
Well, it was due to max-row-limit in InfluxDB conf. When I set thus value to 0 (infinite) series are showed correctly.
