### ISSUE TITLE
Chore: Improve `ToolbarButton` story

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#50660]
- [ ] Add .mdx documentation
- [ ] Add support for [controls](https://storybook.js.org/docs/react/essentials/controls)

Use `Button` as an example

**Comment by sonjafeitsch** [comment]
Hello, I am very interested in Storybook and component design with React. I am a newbie in contributing to open source projects, but you have great guidelines so I would like to try this issue 🙋‍♀️
