### ISSUE TITLE
[Bug] Template variables content empty on browser refresh

### ISSUE THREAD

**Issue by lgenier** [grafana/grafana#5067]
Please include some basic information:
- What grafana version are you using?
Grafana version: 3.0.1, commit: v3.0.1+2-g549eb15, build date: 2016-05-11 10:37:21
- What datasource are you using?
elasticsearch-1.x on elasticsearch 1.7
- What OS are you running grafana on?
debian 8.3
- What did you do?
open a dashboard using templates on different organization, using different datasources (each on the same ES cluster)
- What was the expected result?
each template variables must be filled
- What happenend instead?
some dashboard have their template variables filled and some other have their template variables empty

When tracing with chrome dev tools, the dashboard content differs.
When the template variables are filled correctly, the dashboard contents : 
"templating":{"list":[{"allFormat":"lucene","current":{"tags":[],"text":"data expected" ...

When the template variables are empty, it contents :
"templating":{"list":[{"allFormat":"lucene","current":{"isNone":true,"text":"None","value":""}
As editing the variable the preview is empty, but if i click any box like "include all options" or "Enable Value Groups/Tags", the preview becomes filled with the right values.

**Comment by torkelo** [comment]
Can you show your template variable definitions (screenshots, or dashboard json) , also show the ES requests that Grafana makes and the ES response's

**Comment by lgenier** [comment]
Here are 2 dashboards data, one working and one failing refresh
[dashboard-refresh-fail.txt](https://github.com/grafana/grafana/files/268333/dashboard-refresh-fail.txt)
[dashboard-refresh-ok.txt](https://github.com/grafana/grafana/files/268332/dashboard-refresh-ok.txt)

I'll post for the request and response as soon as i find them. thanks.

**Comment by lgenier** [comment]
Here is a failed request used for displaing a panel.
[request-failed.txt](https://github.com/grafana/grafana/files/268417/request-failed.txt)

The elementName is empty because the template variable is empty. ES obviously sends an error response.

I haven't found any template variable refresh request from grafana to ES, except when i force the reload by clicking any option in the template variable edition.

Here is the request-response when the reload is forced.
[refresh-template-vars.txt](https://github.com/grafana/grafana/files/268432/refresh-template-vars.txt)

**Comment by torkelo** [comment]
The only thing I can see is in the dashboard you named as failed the template variable is saved with refresh disabled (so it's values will not be updated on dashboard load)

**Comment by lgenier** [comment]
Ok. Double checking. In the two dashboard GUI, the esx template variable refresh is set to never.
In the working dashboard json, "refresh": 0,
In the refresh fail dashboard json, "refresh": false,

i don't know why these values differ and it perhaps explains the different behaviours. Anyway, setting variable refresh to "on dashboard load" works well for the two dashboards. My problem is fixed, thanks !
