### ISSUE TITLE
UX: Top bar for Alert creation is not sticky and scrolls away if you have too many navbar items (responsive behavior issue)

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#50697]
On smaller screens where the left-hand icon toolbar is too long the scrolling behavior for the alert creation seems to mess up.

https://user-images.githubusercontent.com/53754871/173379751-a413e83e-6420-4d69-a422-f8b988ada39f.mov

**Comment by matheusmuniz03** [comment]
I tried to reproduce, but it seems to be normal, loom:https://www.loom.com/share/b911c8973d6f4dbd949c93a5d4464c6f
