### ISSUE TITLE
Alerting: Alert rule panel

### ISSUE THREAD

**Issue by peterholmberg** [grafana/grafana#50691]
### Why do we need this
With the introduction of Grafana 8 alerting (unified alerting) alerts and panels are no longer tightly coupled, this means that an alert rule is not tied to a specific panel but is its own entity. Obviously a side effect of this is that many panels that were "alerting panel", ie panels that had alert created on them stopped working. 

After receiving feedback from the community where users wanted feedback on a dashboard if an alert was firing and duct tape solution was implemented. You can now "connect" an alert rule to one or many panels by specifying a `dashbaordId` and `panelId` as an annotation on the alert rule.

One not insignificant drawback with this is that the panel is only querying the evaluation of the rule, the queries are **not** synced between rule and panel. Therefore the visualization on the panel can look differently if the alert rule query changes at some point. 

### Suggestion
Instead of having a weird connection between an alert rule panel I propose that we create an _Alert rule panel_ which will be a visual representation of an alert rule. It will use the rules queries and evaluation and base its visualization on these. This means that the alert rule will be the single source of truth for what the panel displays. 

Some work is already started by me in a hackathon branch but it is severely outdated so I believe it's easier to create a new branch based on main and copy relevant code.

**Comment by wjordan** [comment]
👍

My org uses a number of alerts attached to actively-maintained dashboards, where some queries are tweaked and adjusted on a regular basis. This issue (that queries are no longer kept in sync between a Grafana Alerting rule and dashboard panel) is a significant [undocumented difference](https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/migrating-legacy-alerts/#differences) from legacy alerting that will cause serious migration confusion - a new requirement to always save updates to both places is not only a hassle, but will be nearly impossible to consistently enforce across a team (especially one already trained on the existing behavior).

The proposed alert rule panel is one interesting solution (I would be interested in a link to the branch if available). Alternative approaches would include a hook to synchronize an alert-rule query with its linked dashboard after every save (either a bidirectional sync, or preventing the alert-rule query from being edited directly when a `panelId` annotation is present), or an extra 'special' built-in [data source](https://grafana.com/docs/grafana/latest/datasources/) that makes the result set from a linked alert rule available to a panel (similar to the `Dashboard` source).
