### ISSUE TITLE
UX: For alerts created from panels, an example expression/condition is added automatically without validation

### ISSUE THREAD

**Issue by jessover9000** [grafana/grafana#50698]
If I create a new alert rule from an existing panel, queries and details are partially filled out from the panel. The cursor focuses on the rule name field, notifying the user that they should review and possibly change that field. But there could be more parts that might need reviewing. Especially the alert condition – some threshold is added there, not sure if it's just a random value or some logic to which threshold gets added. But there should be a highlight or validation that "You might want to review or change this value". Fresh users might miss that they need to change their alert condition or struggle to find this very important part of creating an alert in the middle of all the options and fields.

**Comment by gillesdemey** [comment]
The new alert creation automatically adds 2 expressions – reduce + threshold and selecting the latter as the alert condition.
