### ISSUE TITLE
[Bug] Building RPM Fails with Node 6.1.0

### ISSUE THREAD

**Issue by CamJN** [grafana/grafana#5071]
- What grafana version are you using? `master e4a24e17855cd79f053f08e94924d22c0551ffd6`
- What datasource are you using? `N/A`
- What OS are you running grafana on? `OS X 10.11.5`
- What did you do? `go run build.go pkg-rpm`
- What was the expected result? `rpm is built`
- Node version: `v6.1.0`
- What happened instead?
```
#... truncated to relevant section
Running "compress:release" (compress) task
>> Compressed 3096 files.
Fatal error: If encoding is specified then the first argument must be a string
exit status 3
exit status 1
```
possibly related: https://github.com/senshu/Sozi/issues/361

**Comment by nfnty** [comment]
Upstream issue: https://github.com/gruntjs/grunt-contrib-compress/issues/180
Fixed with latest upstream release `1.3.0`
