### ISSUE TITLE
[Question] Is it possible to apply thresholds by row instead of by column in table panels?

### ISSUE THREAD

**Issue by LoaderMick** [grafana/grafana#5072]
Please include some basic information:
- What grafana version are you using? Version 3.0.1
- What datasource are you using? openTSDB
- What OS are you running grafana on? Windows

I had a question regarding data displayed in a table panel. Is it possible to apply thresholds to each row of a table?

My use case is creating a summary dashboard to display the average, min and max values of several different metrics of differing units. The different metrics also have different threshold values - and therein lies my problem.

![image](https://cloud.githubusercontent.com/assets/19419495/15344353/8ac2f7fe-1ce9-11e6-8a92-54b386a3d52e.png)

**Comment by torkelo** [comment]
No, thresholds are currently only defined per column, depending on your query you could swap the rows and columns (in the table options select table transform `Time series to columns`)

**Comment by aditya-manit** [comment]
I want to add exception for a few rows when it comes to thresholds, I have color coded other rows but for two rows I don't want them to get color coded by those exceptions, is it possible ?

**Comment by adambridge** [comment]
Same here, per row thresholds would be a useful feature for me right now.

**Comment by bat-manav** [comment]
I also have the same requirement.
