### ISSUE TITLE
Docs: Extraneous `<pre><code><ol></code></pre>` tags inserted by `{{< docs/list >}}`

### ISSUE THREAD

**Issue by weslord** [grafana/grafana#50729]
**What happened**:
There are a bunch of `<ol>`'s visible on docs pages that use `{{< docs/list >}}`, like:
https://grafana.com/docs/grafana/latest/administration/preferences/change-home-dashboard/#set-the-home-dashboard-for-your-organization

**Environment**:
- User OS & Browser: MacOS 13, Firefox 101.0.1
- Others: Online Documentation

**Comment by chri2547** [comment]
@jdbaldry , can you please have a look at this? This issue is also mentioned here: https://raintank-corp.slack.com/archives/C5PG2JK8W/p1656018988162389 and here: https://raintank-corp.slack.com/archives/C5PG2JK8W/p1656622764939299.

Thank you!
