### ISSUE TITLE
[Question] Stat Permissions

### ISSUE THREAD

**Issue by lingrlongr** [grafana/grafana#5073]
I'm currently trying out Grafana 2.  Is there a way to set permissions to stats?  For example, can I give multiple people access to Grafana (via orgs?) so that people in org1 can only read org1 stats, and org2 can only read org2 stats?  For example:

org1.stats.gauges.fuel.amount
org2.stats.gauges.fuel.amount

I'm currently using a Graphite back-end...

Thanks,
Keith

**Comment by torkelo** [comment]
Graphite does not have any per metric permissions. And Grafana does only proxy the request to graphite, so if you expose a Graphite data source, all metrics will be available
