### ISSUE TITLE
Alerting: Impossible to create token-based Slack bots due to incorrect form validation

### ISSUE THREAD

**Issue by alexweav** [grafana/grafana#50736]
**What happened**:

When creating a Slack contact point, I am unable to save unless the `Webhook URL` field is populated. However, right above the field, it says that the field is optional. This doesn't make sense.

Also, if you are trying to make a token-based (non-webhook) Slack bot, this bug makes it impossible. Token-based bots must have a blank webhook URL, or it'll try to send it as a webhook instead.

**What you expected to happen**:

The field to be optional.

**How to reproduce it (as minimally and precisely as possible)**:

![2022-06-13-165724_526x154_scrot](https://user-images.githubusercontent.com/8410871/173452049-39b61208-f15f-4b0b-b9c6-b58021b87182.png)

It says "Optionally provide" and "Required" at the same time.

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by alexweav** [comment]
The screenshot truncates it, but I already have a token provided. It makes sense that one of the two fields should be required, but I already provided the other one.

**Comment by user10x** [comment]
Should this be grouped into "mode" with subcategories a) token b) webhook? It's a required field if you have to send a message (screen shot above) but also it gets a readonly class appended to it as soon as the token is typed (screen shot above)

![Screen Shot 2022-06-18 at 1 41 48 AM](https://user-images.githubusercontent.com/4950828/174430086-4742ac5c-c104-4c90-bdc6-549dd62deb7d.png)

![Screen Shot 2022-06-18 at 1 34 26 AM](https://user-images.githubusercontent.com/4950828/174430093-78bf57d4-4506-4e96-8f3e-0c4d792a01fc.png)

**Comment by user10x** [comment]
@armandgrillet  is this still an issue or any comments on grouping them like i mentioned above?
