### ISSUE TITLE
[Feature Request] Clock / radar panel

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5076]
I know this would be long-term, but a panel like
https://www.facebook.com/PrinevilleDataCenter/app/399244020173259/ would be rather nice.

Obligatory screenshot:
![facebook_dc_dashboard_1](https://cloud.githubusercontent.com/assets/754723/15351077/92273d36-1cdd-11e6-9eb2-964cccfdaeb6.png)

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
