### ISSUE TITLE
annotations not show on initial dashboard load, only when disabling one of them

### ISSUE THREAD

**Issue by Dieterbe** [grafana/grafana#5077]
using grafana 3.0.2 (i think)
i have a dashboard with 2 annotations defined.
when i do the initial dashboard load, no annotations show up.
i have to 2nd one to have some of the first show up, re-enabling the 2nd makes the 1st one stay.
but fresh load shows nothing.

see https://www.youtube.com/watch?v=9xNGo9-vygI&feature=youtu.be for a demo

**Comment by torkelo** [comment]
can replicate this here, they show up the first time, (also ES annotation)
http://play.grafana.org/dashboard/db/annotations

It looks like from your video that the ES annotation query is performed but nothing is shown, have you looked at the response from ES for this query?

**Comment by torkelo** [comment]
seems to have been caused by a missing data source on one of the annotation definitions, not sure why the result did not give any error or caused the other annotation to be not shown

**Comment by Dieterbe** [comment]
> not sure why the result did not give any error or caused the other annotation to be not shown

and that's not something we want to fix?

**Comment by torkelo** [comment]
yes :)
