### ISSUE TITLE
Alerting: Improve Cloud alert rule authoring experience

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#50783]
**What happened**:

The current authoring experience for cloud rules (Mimir / Cortex / Loki) is somewhat disappointing and has fewer visual elements than the alert creation flow of Grafana managed rules.

We should align the experience as much as possible, some areas where we can improve:

- [x] #54948
- [ ]  https://github.com/grafana/grafana/issues/35699

**Comment by jtheory** [comment]
See https://github.com/grafana/grafana/issues/45306 -- Gilles flagged that as blocked, for now, given API limitations
(are those the same previews this issues is talking about?)

**Comment by gillesdemey** [comment]
No, that's a different blocker – we have all we need to proceed with previews of recording rules.

**Comment by gillesdemey** [comment]
Closing this as a duplicate of https://github.com/grafana/grafana/issues/35699
