### ISSUE TITLE
Variable - Query issue - After migrating from 8.5.5 to 9.0.0-beta3 with VictoriaMetrics datasource

### ISSUE THREAD

**Issue by prakashvra** [grafana/grafana#50798]
**What happened?**

Earlier had the version 8.5.5 running with VictoriaMetrics 1.77.2. Was using a bunch of dashboard variables and the queries were working fine. 

After the upgrade to 9.0.0-beta3 the variable query validation keeps failing. Shows "missing match[] query arg"

**What was expected?**
Was expecting the variables will be compatible with the newer version. The variable queries are working fine when I use 8.5.5 version with VictoriaMetrics 1.77.2

**When does it happen?**
This happens when the data source is VictoriaMetrics. Found this error while checking the logs of VictoriaMetrics found this error

> VictoriaMetrics/app/vmselect/main.go:467	error in "/api/v1/series": missing `match[]` query arg

**Environment**
The stack is running on AWS EKS with Amazon Linux
Grafana - 9.0.0-beta3
VictoriaMetrics - 1.77.2

**Comment by hagen1778** [comment]
Looks like Grafana sends [required params](https://prometheus.io/docs/prometheus/latest/querying/api/#finding-series-by-label-matchers) as form data instead of sending as query params:
<img width="473" alt="image" src="https://user-images.githubusercontent.com/2902918/173664456-4705c32e-b814-4e71-87c6-d7ccf743c0be.png">
<img width="493" alt="image" src="https://user-images.githubusercontent.com/2902918/173664486-6bb20e3e-6d38-4661-b9f9-45baa68cf5d2.png">

**Comment by hagen1778** [comment]
Could it be that Grafana strips body params when proxying request to the datasource? Logging received request in VictoriaMetrics shows that received request is actually POST with correct header, but contains no payload:
```
&{POST /api/v1/series HTTP/1.1 1 1 map[Accept-Encoding:[gzip] Content-Type:[application/x-www-form-urlencoded] User-Agent:[Grafana/9.0.0]] 0xc0000365c0 <nil> -1 [chunked] false localhost:8428 map[] map[] <nil> map[] 127.0.0.1:60475 /api/v1/series <nil> <nil> <nil> 0xc000036600}
```
I expect, such request should fail for Promethes as well.

**Comment by prakashvra** [comment]
hi, Thanks for the updates. 
I tried installing 9.0.0 using helm chart and I am still seeing the issue with POST method in Datasource

`helm install --set image.tag=9.0.0 grafana-900 grafana/grafana`

Is it possible the image is not updated yet?
