### ISSUE TITLE
CloudWatch: Update Docs for metric math expressions

### ISSUE THREAD

**Issue by iwysiu** [grafana/grafana#50817]
In the `Metric math expressions` section of the [CloudWatch plugin docs](https://grafana.com/docs/grafana/next/datasources/aws-cloudwatch/#metrics-query-editor) it mentions the expression field, which no longer exists. We should point them to the editor `code` mode instead.

**Comment by chri2547** [comment]
This issue appear to no longer be relevant as there have been significant changes to the data sources docs. Closing.
