### ISSUE TITLE
Allow re-ordering of columns in table panel configuration

### ISSUE THREAD

**Issue by volter** [grafana/grafana#5082]
There currently is no way (other than editing the JSON) to re-order existing fields in a table panel. This is pretty painful, if you have a lot of columns, in particular, if there is no auto-completion.

**Comment by jayannah** [comment]
+1

**Comment by MrBoggi** [comment]
I agree. It would be nice to be able to reorganize the columns.
Now I'm stuck with <timestamp><item><lastvalue> but would like <item><lastvalue><timestamp>

**Comment by marianob85** [comment]
+1

**Comment by jameswongyou** [comment]
+1

**Comment by boeboe** [comment]
+1

**Comment by anneq** [comment]
+1

**Comment by AInoob** [comment]
+1

**Comment by amgorb** [comment]
indeed +1

**Comment by JinlinSong** [comment]
+1

**Comment by paol** [comment]
With Prometheus data sources there is no way that I can tell to reorder columns, not even editing the JSON.
The column appears effectively random, which can make tables really awkard to read.

**Comment by torkelo** [comment]
Strange , means Prometheus returns them in random order (I think)

**Comment by paol** [comment]
@torkelo Well, prometheus labels are being turned into columns and labels have no inherent ordering, so that's to be expected.

**Comment by cxxly** [comment]
+1

**Comment by cxxly** [comment]
is there any progress?

**Comment by Stono** [comment]
+1billion to this, a prometheus data source results in columns being displayed in a non-deterministic order which is bloody well rubbish! :)

**Comment by Rellek72** [comment]
+1

**Comment by iamash** [comment]
Is there any progress???????????? This is a MUST have feature!

**Comment by iamash** [comment]
Is there any progress??? This is a MUST have feature, right now you have no control over the table which is ridiculous.
And for Prometheus, I think the order is alphabetically depending on the label name (Giving another column name in Granada won't do anything)

**Comment by jeremyxu2010** [comment]
+1

**Comment by jeremyxu2010** [comment]
+1
For Prometheus, the order is alphabetically depending on the label name.
So i get a solution, but it's ugly...
Use `label_replace` in promQL, rename label to `_xx_old_label`,  something like that:
```
label_replace(some_metric, "_01_old_label", "$1", "old_label", "(.*)")
```

**Comment by curi0s** [comment]
+1

**Comment by Meta4X** [comment]
+1

**Comment by yanivroz** [comment]
+1

**Comment by ksemaev** [comment]
+1

**Comment by sjentzsch** [comment]
sry but here is another +1 ...

**Comment by cactusgame** [comment]
I think this feature is very useful. +1

**Comment by ilucatero** [comment]
+1 
Can sort by default the columns, but works if you click on the actual column...

**Comment by cluffja** [comment]
+1

**Comment by ncamx** [comment]
+1

**Comment by dry013** [comment]
Even simple MoveUp/MoveDown buttons would be better than nothing
+1

**Comment by martinrw** [comment]
+ 1

**Comment by kekkokk** [comment]
+1

**Comment by fabio-rigato** [comment]
+1

**Comment by ward-eric** [comment]
+1

**Comment by onedr0p** [comment]
Please stop with the +1, I (like many others) are tired of receiving notifications for those comments.

**Comment by TylerZale** [comment]
+1

**Comment by onedr0p** [comment]
:shakes_fist:

**Comment by sbenzakountradelab** [comment]
yes for influxdb when dealing with tags, the order of columns is imposed by the alpha-numeric order. 
please do it 🙏🏻

**Comment by debmalyapan53** [comment]
+1

**Comment by jutley** [comment]
For people using Prometheus, I have the world's ugliest hack to get around this.

Suppose I have a query $QUERY that returns vectors with labels $A_LABEL, $SOME_LABEL, and $THIS_LABEL. In my table, I will see the columns in this same order, since I listed them alphabetically. However, I want the order to be $SOME_LABEL, $A_LABEL, $THIS_LABEL.

We can use Prometheus's `label_replace` to rename my labels so that they are done alphabetically. Then, we can use a sum_by to remove the original labels. This looks like this:
```
sum by (_0_some_label, _1_a_label, _2_this_label) (
  label_replace(
  label_replace(
  label_replace(

    # The actual query
    $QUERY

  , "_0_some_label", "$1", "some_label", "(.*)")
  , "_1_a_label",    "$1", "a_label",    "(.*)")
  , "_2_this_label", "$1", "this_label", "(.*)")
)
```

Pretty dumb, right? But it works. Unfortunately, these are ugly names to read, so let's reformat them. Add a column style that matches the regular expression `/_\d+_(.*)/`. Then set the column header to `$1`. This way, we strip off our ugly hack and get our original labels as our column headers.

The fact that this is necessary is ridiculous. Column ordering should really be a built in feature. So, you know, +1.

**Comment by c6h3un** [comment]
+1

**Comment by sbenzakountradelab** [comment]
To solve this issue, i ussed a custom backend using the json data source plugin https://grafana.com/plugins/simpod-json-datasource.

**Comment by WilliamLHarms** [comment]
+1

**Comment by amytleonard** [comment]
I would like this as well

**Comment by apanagar** [comment]
This would be a great feature

**Comment by qyvlik** [comment]
+1

**Comment by WilliamLHarms** [comment]
FYI - the work around to this bug is to edit the panel json directly.   Look for the columns block then move the column definition around in the json.  (panel dropdown --> more --> Panel Json)

``` "columns": [
    {
      "text": "level",
      "value": "level"
    },
    {
      "text": "message.text",
      "value": "message.text"
    },
    {
      "text": "@timestamp",
      "value": "@timestamp"
    }
```

**Comment by paol** [comment]
@WilliamLHarms That only works for some data sources. Prometheus for example builds the columns dynamically, there is no JSON to edit.

**Comment by WilliamLHarms** [comment]
@paol  - yea, it was an elastic datasource.  I guess there isn't a work around for the bug.  Just scrap your panel and start over.

**Comment by bzon** [comment]
We are all waiting for the hero who will apply this feature.

**Comment by binduv124** [comment]
This would be a great feature to have.

**Comment by zimmertr** [comment]
Would love to be able to do this as well.

**Comment by joker234** [comment]
I'd like to see that feature realised.

**Comment by ZeroMagic** [comment]
The feature will improve the user experience greatly.

**Comment by r2dedios** [comment]
> @WilliamLHarms That only works for some data sources. Prometheus for example builds the columns dynamically, there is no JSON to edit.


Prometheus sort the labels attributes by alphabetic order. Not randomly.

If you have the labels: "hostname", "ip", "cluster", the order will be:

{cluster="", hostname="", ip=""}

But if one label name begins by capital letter the order change.

{IP="", cluster="", hostname=""}

**Comment by AIXruth** [comment]
+1 and btw if the amount of columns is to high, the header row is stuck and not able to scroll with the rest (#4157)

**Comment by neeles83** [comment]
+1 Why not order on the Column styles order and make them, easy to move so you can drag them on the screen.

**Comment by torkelo** [comment]
Coming in 7.0 via the new transform tab!

**Comment by jothibasu-kamaraj** [comment]
> sum by (_0_some_label, _1_a_label, _2_this_label) (
>   label_replace(
>   label_replace(
>   label_replace(
> 
>     # The actual query
>     $QUERY
> 
>   , "_0_some_label", "$1", "some_label", "(.*)")
>   , "_1_a_label",    "$1", "a_label",    "(.*)")
>   , "_2_this_label", "$1", "this_label", "(.*)")
> )

it worked for me with 20 columns thank you
