### ISSUE TITLE
[Bug] Templated dashboard broke in refresh after upgrade from 2.6.0 to 3.0.1

### ISSUE THREAD

**Issue by Slach** [grafana/grafana#5083]
grafana 3.0.1 installed over debian package
datasource: graphite 0.10a
Ubuntu 14.04
- What did you do?
i create templated dashboard with one row repeated by templated variable $host and one graph inside this row repeated by $profiling metric
see Dashboard JSON here http://pastebin.com/GtWykjna

i change $percentile variable on dashboard from 95 to 75 or

- What was the expected result?
refresh dashboard and show all graphs repeated by $profiling_metric inside rows repeated by $host

- What happenend instead?
i have multiple wrong graphs with "All" title
see https://snapshot.raintank.io/dashboard/snapshot/P8fDrxmH0UIUc4vFaD7XnxD6z20nIzc4

**Comment by torkelo** [comment]
Update to 3.0.2 there was a fix relating to row repeats , also if this is an old dashboard, go into the template variable options and hit the Update button (then save and reload dashboard)
