### ISSUE TITLE
wrong "mm" unit in Stat panel after upgrade to Grafana 9.0

### ISSUE THREAD

**Issue by jostrasser** [grafana/grafana#50836]
**What happened**:
Upgraded to Grafana 9.0

**What you expected to happen**: 
Unit "millimeter (mm)" is incorrect in Stat panel and will be displayed as "fm", expected "mm".

**How to reproduce it (as minimally and precisely as possible)**:
Upgrade to 9.0 and use unit "Length / millimeter (mm)

**Environment**:
- Grafana version: 9.0
- Data source type & version: influxes 1.8
- OS Grafana is installed on: LXC / Ubuntu Focal
- User OS & Browser: Safari on macOS 12.4

![image](https://user-images.githubusercontent.com/14274103/173699162-5b9c3f0c-947d-400c-abc1-bec6752a16bc.png)

**Comment by ashharrison90** [comment]
hey @jostrasser 👋 

it'll be fixed in 9.0.1 by https://github.com/grafana/grafana/pull/50719 👍

**Comment by jostrasser** [comment]
> hey @jostrasser 👋 
> 
> 
> 
> it'll be fixed in 9.0.1 by https://github.com/grafana/grafana/pull/50719 👍 

Great, thank you!
