### ISSUE TITLE
Switching from mixed to Azure monitor loses query data

### ISSUE THREAD

**Issue by shuotli** [grafana/grafana#50831]
**What happened**:
![azure monitor](https://user-images.githubusercontent.com/63325084/173680381-021dd252-9aa0-47e1-97b7-cf6be6304ff0.gif)

**What you expected to happen**:
Switching between mixed and Azure monitor should keep the query data
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
In grafana/public/app/features/query/state/updateQueries.ts, as Azure monitor Datasource does not have `importQueries`, the query data are lost in the method.
**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by iwysiu** [comment]
Hi @shuotli ,

Thanks for reporting the issue, I'll add it to our backlog. Note for the person implementing this, `importQueries` is deprecated, but implementing the `DataSourceWithQueryImportSupport` interface will also fix this.
