### ISSUE TITLE
9.0 log panels, line spacing increased a lot

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#50842]
After upgrading from Grafana 8.5 to 9.0 the line spacing between log entries in Loki log panels and explore window is a lot bigger.
Previously a small browser window that could fit 43 lines now only fits 33, this makes reading logs more difficult.

Left side: 9.0, Right side:8.5
![image](https://user-images.githubusercontent.com/89977373/173754603-3f387cc1-492c-472f-83d1-9328ec1c5716.png)

Using Firefox, zoom level 150% on both sides. Issue can be observed at 100% also but less prominent.

**Comment by gabor** [comment]
implementation note: the PR that caused this is https://github.com/grafana/grafana/pull/48759 ... we'll need to decide how best to solve it here.
