### ISSUE TITLE
Export / Import Dashboard

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5084]
Remake export & import so that dashboards can be shared more easily

Export:
- [x] Templetize data source usage in panels 
- [x] Templetize data source usage in annotations & template vars
- [x] Exported dashboard should remove repeated panels & rows
- [x] Exported dashboard should remove query template variable's options 
- [x] Add Grafana version to exported dashboard
- [x] Add a `__requires` array with info about used panels & data source plugins
- [x] Update design for share modal 
- [x] Decide what to do with Title and Description on export

Import:
- [x] Create new import modal that allows a user to specify data source mappings 
- [x] Import directly from grafana.net using url/id
- [ ] Column in grafana dashboard table for grafana gnet id

**Comment by chancez** [comment]
@torkelo Is this API for importing fairly safe to use (stable?) if I wanted to use imports programmatically, to integrate Grafana in other systems?

**Comment by torkelo** [comment]
Of course

**Comment by chancez** [comment]
Sweet, this is going to be great for UX.
