### ISSUE TITLE
Template Variable not updating correct

### ISSUE THREAD

**Issue by discostur** [grafana/grafana#5085]
Hi,

i'm running Grafana version: 3.0.2 against a Prometheus 0.18.0 Database inside a Kubernetes 1.2.2 Cluster. I'm trying to display Memory / CPU Metrics from my Pods.

I've created a template variable $pod which is filled by a query and regex:

`query: container_start_time_seconds{kubernetes_namespace="$namespace"}`

`regex: /kubernetes_pod_name="([^"]+)"/`

Refresh of the variable is set to "On Time Range Change". Now, wether i set my time-range to 5 minutes or to 3 hours, i always get back the same pod-names for my variable $pod. 

If i do the exact same query on the prometheus backend directly i only get the actual running pod-names back. 

My question now is: Does Grafana ignore the time-range i set in the right corner when it is querying prometheus for the $pod variable?

**Result:** Grafana shows all pods ever created for my $pod variable
**Expected behaviour:** only show the corresponding pods for the time-range i selected

**edit:** $namespace is another variable which is set to "default" in this example

**Comment by torkelo** [comment]
the Prometheus Grafana data source plugin does not support time ranged template queries in 3.0, 

It was just merged to master so is available in 3.1 pre release nightly builds

**Comment by discostur** [comment]
Just tested it with the latest nightly build:

Grafana version: 3.1.0, commit: 5aaaeb0, build date: 2016-05-18 11:40:33

Should it work with that version? Because nothing has changed for me ...

**Comment by mtanda** [comment]
How do you set templating query?
Do you use label_values?

Anyway, time range filtering is not supported in Prometheus 0.18.0.
https://github.com/grafana/grafana/pull/5007

You need to wait next release.

**Comment by discostur** [comment]
ok then i'll have to wait for the next prometheus version, too.

Thanks for your help
