### ISSUE TITLE
Increase test coverage in New Search/Folder Management components

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#50856]
Increase test coverage in New Search/Folder Management Components

List of components (`public/app/features/search/page/components`) that need to have unit test:

- [x] ManageActions  @axelavargas  https://github.com/grafana/grafana/pull/51131
- [x] FolderSection @ashharrison90 https://github.com/grafana/grafana/pull/50961
- [x] FolderView @ashharrison90 https://github.com/grafana/grafana/pull/51114
- [x] SearchResultsGrid @axelavargas  https://github.com/grafana/grafana/pull/51296
- [x] SearchResultsTable @ashharrison90 https://github.com/grafana/grafana/pull/51269
- [x] SearchView @JoaoSilvaGrafana https://github.com/grafana/grafana/pull/51248

These tests are required to merge this PR https://github.com/grafana/grafana/pull/50125

**Comment by ashharrison90** [comment]
closing now we've delivered all the unit tests 🥳
