### ISSUE TITLE
NavBar: Menu doesn't open after clicking sub-menu item

### ISSUE THREAD

**Issue by kaydelaney** [grafana/grafana#50884]
**What happened**:
Clicked a sub-menu item, then hovered over the parent item in the navbar, but the menu didn't open.

https://user-images.githubusercontent.com/45561153/173843363-4727065c-b174-4931-9d2e-958061610edc.mp4

**What you expected to happen**:
For the menu to open as usual.

**How to reproduce it (as minimally and precisely as possible)**:
1. Hover over the "dashboards" navbar item.
2. Click "Browse"
3. Hove over the "dashboards" navbar item again
4. Notice the submenu doesn't open

**Environment**:
- Grafana version: v9.0.0-pre (68691d7775)
- OS Grafana is installed on: macOS 12.4
- User OS & Browser: macOS 12.4, Chrome 102.0.5005.115 x86_64

**Comment by ashharrison90** [comment]
currently implementing some new navigation designs - plan to tackle this as part of that

**Comment by eledobleefe** [comment]
Thanks for the contribution @gitstart!
We're not quite ready to accept outside contributions for this because, as @ashharrison90 said, we are currently implementing some new navigation designs that will tackle this issue.

**Comment by ashharrison90** [comment]
so as mentioned this is fixed as part of the new navigation experience we're implementing. you can check out these changes via the `topnav` feature toggle - there's still some bugs to fix, etc. as such, i'm going to close this as completed, and look out for the new navigation release soon™️ 🥳
