### ISSUE TITLE
Alerting: broken docs link in legacy alerting message

### ISSUE THREAD

**Issue by daniellee** [grafana/grafana#50888]
When on legacy alerting, then the link to the docs is broken:

![image](https://user-images.githubusercontent.com/434655/173864162-03fd85a2-a426-4a24-86b5-53b596c90603.png)

This link is broken: https://grafana.com/docs/grafana/latest/alerting/unified-alerting/difference-old-new/

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.0-65693beta.3 (29b2c7151)
- Grafana Cloud

**Comment by peterholmberg** [comment]
Both links work for me @daniellee , got a moment to retest?

**Comment by brendamuir** [comment]
I updated this link to work on Friday - https://github.com/grafana/grafana/pull/51023. I retested to be sure the changes are in and it's working as planned!
