### ISSUE TITLE
[Bug] Single stat panels with spark lines break with a 25px row height

### ISSUE THREAD

**Issue by zachd** [grafana/grafana#5089]
Hi, using **Grafana 3.0.2** (and play.grafana.org) single stat panels with spark lines enabled seem to show an error when the row height or individual panel height is set to 25px.

Steps to reproduce:
1. Go to [http://play.grafana.org/dashboard/db/big-dashboard](http://play.grafana.org/dashboard/db/big-dashboard), open the settings and uncheck "Hide controls".
2. Select the green row editor icon on the first row of single stat panels, then select "Set height" and set it to `25px`.
3. Click the refresh icon in the top right, and all the single stat panels in the first row will show an error (as shown in screenshot below).

![image](https://cloud.githubusercontent.com/assets/1366937/15367205/e8774b76-1d1f-11e6-9180-a543b8b2263a.png)

Kind regards,
A Hosted Graphite employee <a href="https://www.hostedgraphite.com/" target="_blank">[.]</a>

**Comment by torkelo** [comment]
height requires a min of 120px height I think currently, 

But already reported to fix this 
https://github.com/grafana/grafana/issues/4679
