### ISSUE TITLE
8.5.5 to 9.0.0 - Broken Dashboard (Query Error: 500 Internal Server Error) with Expression Operation

### ISSUE THREAD

**Issue by fatalbyte** [grafana/grafana#50895]
**What happened**:
Upgraded from 8.5.5 to 9.0.0.

**What you expected to happen**:
All dashboards to load as expected.

**How to reproduce it (as minimally and precisely as possible)**:
Dashboard with custom expression in panel causes a Query Error: 500 Internal Server Error.

**Anything else we need to know?**:
It would be good to know how to properly downgrade from 9.0.0 back to 8.5.5 until this issue is resolved.  When I tried to downgrade to 8.5.5 using `sudo dpkg -i grafana_8.5.5_armhf.deb grafana` would not load after.

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: InfluxDB v1.8.10 (git: 1.8 688e697c51fd)
- OS Grafana is installed on: RaspberryPi Buster
- User OS & Browser: Windows 10 / Firefox
- Grafana plugins: None.
- Others:
![grafana_error_20220615](https://user-images.githubusercontent.com/52629807/173875989-5a480bc8-93f3-4abe-93a0-1a4d7c3e9828.png)

**Comment by akarl10** [comment]
I have the same issue. Some simple playing around shows that it does not work anymore if
we have `"expression": "$A-$B" ` and any of $A or $B has `"hide": true`

**Comment by fatalbyte** [comment]
So sorry for the confusion.  I believe I've found the issue after reading an update about v8.5.5.

`Upgrading to 8.5

The concept of a default data source existed in Grafana since the beginning. However, the meaning and behavior were not clear. The default data source was not just the starting data source for new panels but it was also saved using a special value (null). This made it possible to change the default data source to another and have that change impact all dashboards that used the default data source.

This behavior was not very intuitive and creates issues for users who want to change the default without it impacting existing dashboards. That is why we are changing the behavior in 8.5. From now on, the default data source will not be a persisted property but just the starting data source for new panels and queries. Existing dashboards that still have panels with a datasource set to null will be migrated when the dashboard opens. The migration will set the data source property to the current default data source.`

For me, my issue was that the data source was set to "expression" rather than "mixed".  Also, the from data source was set to "default".  After changing it to my data source, the panel started loading and working again.

Hope this helps others.  Otherwise I can still supply my JSON if needed, just let me know.

Thanks!

**Comment by gelicia** [comment]
> I have the same issue. Some simple playing around shows that it does not work anymore if we have `"expression": "$A-$B" ` and any of $A or $B has `"hide": true`
> 
> I think 9.0.1 might have already a fix: #50659

@akarl10 Yep, that will fix any issue with hidden expressions, but the one posted by @cyborgxxl isn't hidden. 

I'm going to treat this as a separate bug for now.

**Comment by gelicia** [comment]
> For me, my issue was that the data source was set to "expression" rather than "mixed". Also, the from data source was set to "default". After changing it to my data source, the panel started loading and working again.

This seems to be the issue since `__expr__` is shown as a datasource in the posted panel JSON as well. I'm wondering if this was anticipated and if theres a way we can handle this scenario more gracefully.

**Comment by torkelo** [comment]
Anyone who can share the dashboard json prior to v9 upgrade ?

**Comment by akarl10** [comment]
> > I have the same issue. Some simple playing around shows that it does not work anymore if we have `"expression": "$A-$B" ` and any of $A or $B has `"hide": true`
> > I think 9.0.1 might have already a fix: #50659
> 
> @akarl10 Yep, that will fix any issue with hidden expressions, but the one posted by @cyborgxxl isn't hidden.
> 
> I'm going to treat this as a separate bug for now.

cyborgxxl's panel has refId: "A" hidden. In my comment I copied from his panel. I never said the expression is hidden, I meant $A or $B itself is hidden. I had the very same problem. The nigtly build of 9.0 has already the mentioned merge and for me that version works

**Comment by torkelo** [comment]
Fix PR is up, hopefully get it merged before 9.0.1 is released
