### ISSUE TITLE
Adding copy icon to label values

### ISSUE THREAD

**Issue by niat22** [grafana/grafana#50904]
### Background / Why we're doing this

**Problem**
Today the user has to click, highlight and use a keyboard shortcut to copy a label value.

### Deliverables

**Solution**
We'd like to add a copy icon next to the log label value (and detected field value) to enable the user to copy the value by only applying one click.

The "copy" icon will only be visible when the user hovers over the log label value (in the example below, the value is `hm-east-2`). 

Here's a mockup of what it would look like after this change:
**Hover state**
![Bildschirmfoto 2022-06-15 um 19 20 42](https://user-images.githubusercontent.com/88372197/173887644-8d954c60-fef3-4cdf-bb25-2714d95d1725.png)
**Spacing**
![Bildschirmfoto 2022-06-15 um 19 11 37](https://user-images.githubusercontent.com/88372197/173887708-6ac4b81d-f674-4318-a0f3-c6112d18a1c1.png)

**Comment by 09jvilla** [comment]
@niat22 -- Can we be super explicit with what we expect will be copied once you click the copy button? 

In your example, we'd expect that `hm-us-east2`, the label value, is what gets copied to the clipboard. We would not copy the label name, `cluster`.
