### ISSUE TITLE
[Question] Need help creating a "Save to Machine" functionality

### ISSUE THREAD

**Issue by robsnodden** [grafana/grafana#5091]
Hello Grafana Devs, 

I have been using Grafana for a while now, and really love it. However, I have a question for a feature I'm working on, that I am unable to get an answer on yet by searching:

I am developing a plugin for Grafana for the intended functionality, "Save to Remote Machine":
1. User selects desired _graph_ then  selects _Share_
2. In _Share Panel_, user selects _Snapshot Sharing_
3. Additional option _button_ that saves the graph and all metadata (data points in selected graph) to a machine.

I intended to capture the metadata that is already used in the (awesome) snapshot functionality and save those data points and values to a machine. 

**Questions:**
- Is this a feature that is already in production? Where does the metadata (data points) get stored when a snapshot is saved?
- Is this idea even possible based on your knowledge of Grafana? 
- Is there an optimal way of implementing the "Save to Machine" functionality? I have been exploring Grafana by way of the plugins, but not sure if this is the right path. I can get this done and create a pull request to add it to Grafana, with some guidance and help from you and/or the community.

Thanks, 
Rob

**Reference:**
- What grafana version are you using?
3.0 
- What datasource are you using?
InfluxDB
- What OS are you running grafana on?
Ubuntu 12.04

**Comment by bergquist** [comment]
What data are you referring to as metadata. I think many fields in the dashboard could be considred meta data. When creating a snapshot all the datapoints is added to the dashboard and then sent to a remote server. So the server can render the dashboard based on the dasboard json and the datapoints provided in the snapshoted dashboard. 

I think snapshot does exactly what you want to achieve. If not, please feel free to reopen this issue.

**Comment by torkelo** [comment]
You can also specify an alternative remote snapshot receiver in configuration file

**Comment by mtanda** [comment]
You can change external snapshot url by "external_snapshot_url" config.
https://github.com/grafana/grafana/blob/c6744925c469f43ba658c5c351c3a6c21bd1c0c6/conf/defaults.ini#L152

Implement API compatible with raintank snapshot service, you can create alternative snapshot service.
https://github.com/grafana/grafana/blob/c6744925c469f43ba658c5c351c3a6c21bd1c0c6/public/app/features/dashboard/shareSnapshotCtrl.js#L69-L91

@torkelo Is my understanding correct?

**Comment by torkelo** [comment]
yes

**Comment by robsnodden** [comment]
Thank you very much for your advice, torkelo, mtanda, and bergquist.

Over the weekend I created a lightweight API compatible with raintank snapshot service, just changed the configs, and data is being snapshotted like a dream. Great success, thank you for the help.

**One additional question:**
I am sending batches of 100 data points per second on my graph, though the graph is only displaying 10 points per second (see pic below), even if I configure the time range refresh intervals for miliseconds, like seen in https://github.com/grafana/grafana/issues/1231

I would greatly appreciate any advice on the graphical display for 100 data points per second (perhaps it is a configuration fix, or perhaps 10 points per second is the max). If this is not already a feature, shall I create a **Feature Request to display > 10 data points per second**?

![grafana10pps](https://cloud.githubusercontent.com/assets/19312863/15555253/c4694bb4-227c-11e6-9854-799fd4f9047c.png)
