### ISSUE TITLE
Explore: Logs should use split-view with "Show Context"

### ISSUE THREAD

**Issue by hunkjun** [grafana/grafana#50913]
### Background / Why we're doing this

This function "Show Context" cannot meet requirements when the log volume is very large. Too much context requires a secondary filter or search

### Is there existing research for this?

No research yet

### Problems or tasks

The "show context" feature is too limited. 

"Show Context" should open in the split view, highlighting the filtered line and showing the context of that file (say +/- 10 log lines). One could add then additional files to even see data from other logs/systems in that context. "Load more" entries should also be possible to skip further back and forth.

about: https://codesti.com/issue/grafana/loki/6031

### Deliverables

- "show context" should have "time field"

- "show context" should have "The secondary search", like elk ”View surrounding documents“ filters. (It is very important in the case of large log.)

![image](https://user-images.githubusercontent.com/22727550/173979180-495d1141-c275-452e-9768-0f2b68585abc.png)

![image](https://user-images.githubusercontent.com/22727550/173979313-ad0a2a59-36d3-4bdc-b2d5-98abe9a70b2d.png)

**Comment by gelicia** [comment]
@hunkjun This looks more suited for a feature request discussion. Grafana uses github discussions for feature requests. Please add this as a discussion and the team will prioritize it. Thank you! 

For more information, see our FAQ https://github.com/grafana/grafana/discussions/36963
