### ISSUE TITLE
[datasource.elasticsearch] Datasource can not be adding correctly when es index name contains `m`!!! 

### ISSUE THREAD

**Issue by SethWen** [grafana/grafana#50924]
**What happened**:
When adding es datasource, if the index name contains `m`, the  es datasource can not be adding correctly.
The response error shows that the `m` become `0`. It is so tricky!
However, inputing the index name contains `m` by `\m`,  everything is ok. 
The following images shows the case.
![case1-1](https://modorone-public.oss-cn-beijing.aliyuncs.com/pictures/grafana1.png)
![case1-2](https://modorone-public.oss-cn-beijing.aliyuncs.com/pictures/grafana2.png)

Then another case.
![case2-1](https://modorone-public.oss-cn-beijing.aliyuncs.com/pictures/grafana3.png)
![case2-2](https://modorone-public.oss-cn-beijing.aliyuncs.com/pictures/grafana4.png)

**Environment**:
- Grafana version: 8.0.6
- Data source type & version: elasticsearch-7.8.0
- OS Grafana is installed on: Ubuntu16.04
- User OS & Browser: chrome
- Grafana plugins:
- Others:

**Comment by SethWen** [comment]
up! up! up!

**Comment by gabor** [comment]
hi @SethWen , if you'd like to use a time-pattern, i recommend putting the not-changing part inside square-brackets, like you can see in the screenshot at https://grafana.com/docs/grafana/latest/datasources/elasticsearch/#index-settings ,

for example : `[rum-]YYYY-MM-DD`

the part in the square-bracket will not be modified.

i hope this helps.
