### ISSUE TITLE
[Feature Request] IPC/localhost only interface to dump configuration, dashboards, data sources.

### ISSUE THREAD

**Issue by pinkisemils** [grafana/grafana#5092]
Hello, I am looking to setup a _slightly_ parametrizable build/deployment of Grafana, where I can push dashboard configurations and data sources directly to a freshly instantiated Grafana instance running with a Postgres database. Currently, I see no way to easily push or pull Grafana's configuration out of a running instance without creating a user and an access token and executing a large amount of HTTP requests.

I might be misreading the docs as well, so maybe this problem has already been solved.

**Comment by bergquist** [comment]
Dashboard and users data would be saved in the postgres database. So just pointing at the database should be enough? 

You can use environment variables to override the default config http://docs.grafana.org/installation/configuration/#config-file-locations . Or you could point to another config when starting grafana using the --config flag. (./grafana-server --config /custom/path)

If you want to recreate dashboards and users at every start then the API is the only way at the moment.
