### ISSUE TITLE
Grafana 9.0.0: autocomplete annotation tags

### ISSUE THREAD

**Issue by garnachod** [grafana/grafana#50928]
**What happened**:
When I try to create a new annotation in a metric and type (autocomplete) for the proper tag, the interface launch an error.
![Screenshot from 2022-06-16 10-47-46](https://user-images.githubusercontent.com/6834252/174031600-b2e306e2-c6fc-4521-a0a2-5793ee8d3aa9.png)

**What you expected to happen**:
In version 8.5.2 the annotation tag is autocomplete 

**How to reproduce it (as minimally and precisely as possible)**:
In a dashboard annotated with tags, try to create a new annotation and when the tag is searched may raise the error, in my case always the error is raised

**Anything else we need to know?**:
Error raised in file https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/utils/tags.ts Line:70
Maybe one value undefined is passed to this function?

**Environment**:
- Grafana version: OSS 9.0.0
- Data source type & version: Prometheus 2.36.0
- OS Grafana is installed on: Amazon Linux 2, binary .tar.gz
- User OS & Browser: Chrome Linux
- Grafana plugins: Default
- Others: Grafana configuration database, postgres

**Comment by garnachod** [comment]
@gelicia sorry I didn't added the message before. I thought the messages were not related ![Screenshot from 2022-06-16 10-45-34](https://user-images.githubusercontent.com/6834252/174076196-373422dd-7747-4284-a20c-48b7767e7bd3.png)

**Comment by gelicia** [comment]
@garnachod Ah that is helpful, but I have one more question. Can you go to your network tab in dev tools and see if any calls there are failing? I'm looking for calls to something like `api/datasources` failing?

**Comment by garnachod** [comment]
@gelicia I can't see any request falling at this moment, the API returns correctly the tags.
![Screenshot from 2022-06-16 15-51-43](https://user-images.githubusercontent.com/6834252/174085621-73cb87f5-bd81-4798-9b4f-5677a3b7e772.png)
The system only fail if I try to search one tag.
![Screenshot from 2022-06-16 15-55-22](https://user-images.githubusercontent.com/6834252/174085949-ec857c05-3b5e-400f-b061-4a09cdb04bef.png)

**Comment by carlkid1499** [comment]
Hello there @gelicia , I just experienced this same issue ~5 minutes ago.
**Environment**:
Grafana version: OSS 9.0.0 - ![image](https://user-images.githubusercontent.com/27721404/174101016-d5e49595-5320-49d7-8337-c9b49507d626.png)

Data source type & version: PSQL 13.7
OS Grafana is installed on: ![image](https://user-images.githubusercontent.com/27721404/174101415-7922637f-e2cd-4dce-8ed0-166cb1f9c49a.png)
User OS & Browser: Chrome Linux - ![image](https://user-images.githubusercontent.com/27721404/174101602-f842afb8-695d-45b9-bb76-9d4c8f0a4644.png)
Grafana plugins: Default, Grafana Image Render



Steps to reproduce:

1. click on a panel and attempt to create an annotation
2. Then search for a Tag under 'Add tags'
3. Error shows up: 
![image](https://user-images.githubusercontent.com/27721404/174102084-8137f002-3e10-41d3-81d0-70efc9566a50.png)
![image](https://user-images.githubusercontent.com/27721404/174102140-5a4724e6-7b1a-45af-929f-7e973b04938a.png)
