### ISSUE TITLE
v9 Text Panel & HTML (from SQL) in Variable

### ISSUE THREAD

**Issue by peawet08** [grafana/grafana#50927]
Hi,

We have a Text Panel that has just a variable in it "**${MyHtml:raw}**".  The variable is populated from the result of a stored procedure "EXEC myStoredprocedure" in SQL Server.   This is working fine in v8.5.5

Just upgraded to v9 and the panel is no longer displaying any content.  Also, looking in the variable and nothing looks to be returned from SQL to the variable.
I have rolled the server back to v8.5.5 and this is working again.

I'm assuming this may be an issue with the variable.  Maybe when using a stored proc or filtering the HTML returned.
Other graph panels using Select statements are working.

I can do some more testing on it to see if it's just Stored procedures but I just thought I'd ask before I spend any time looking into it

**Environment**:
- v9
- SQL Server
- CentOS

Thanks

**Comment by ashharrison90** [comment]
hi @peawet08 👋 

can you confirm exactly which datasource you're using?

definitely sounds like a backend issue if the variable isn't even being populated with the data

**Comment by peawet08** [comment]
> hi @peawet08 👋
> 
> can you confirm exactly which datasource you're using?
> 
> definitely sounds like a backend issue if the variable isn't even being populated with the data

HI Ash,

Yes, Using SQL Server Datasource, however it is working fine under v8.5.5 just not v9.  If it were a problem with SQL then I would have thought it wouldn't work under v8.5.5 too

**Comment by ashharrison90** [comment]
sorry, by backend i didn't mean a problem with sql itself, more likely the sql server datasource. 👍 

thanks for the info, i'll route to the correct team.

**Comment by ashharrison90** [comment]
@grafana/grafana-bi-squad if i populate the variable manually this works correctly in the text panel, so sounds like something has changed in the mssql datasource which is stopping the variable from populating correctly? 🤔
