### ISSUE TITLE
Preferences: /api/preferences/set-home-dash overrides other preferences

### ISSUE THREAD

**Issue by sakjur** [grafana/grafana#50934]
**What happened**:

When setting a new home dashboard using a very obscure API (`POST /api/preferences/set-home-dash` introduced in #4513) for that purpose that's not mentioned anywhere or used anywhere, the other settings were overridden (you can also pass new settings for those preferences).

**What you expected to happen**:

Only the home dashboard should change.

**How to reproduce it (as minimally and precisely as possible)**:

Set the theme to the non default theme and run this filling in your Grafana URL and an arbitrary existing dashboard UID:

`curl "…/api/preferences/set-home-dash" -H "content-type: application/json" -d '{"homeDashboardUID": "…"}'`

**Anything else we need to know?**:

https://github.com/grafana/grafana/blob/3cebd87bbb285995d852c8850656ccef4c1d9fcd/pkg/api/preferences.go#L20-L48

**Environment**:
- Grafana version: main, I think it's been this way for a while. Not sure how long 🤔
- Data source type & version: n/a
- OS Grafana is installed on: n/a
- User OS & Browser: n/a
- Grafana plugins: n/a
- Others:

**Comment by yashp4858** [comment]
Hey I like to work on this issue 
@sakjur @zserge

**Comment by sakjur** [comment]
@yashp4858 👋 Hi! I’m no longer at Grafana, so I’m unfortunately not the right person to ask anymore 🙂
