### ISSUE TITLE
[Feature Request] ability to display metric label value in single state panel [Prometheus] 

### ISSUE THREAD

**Issue by daodennis** [grafana/grafana#5094]
Hi,

Given a prometheus metric such as:

`kubernetes_build_info{gitCommit="123412341234",gitTreeState="clean",gitVersion="vx.y.z",instance="1.1.1.1:8080",job="kubernetes",major="1",minor="2"}`

It would be useful for the prometheus/grafana community to display the value of one of the labels in a single-state panel.  Build Info / Version / Kernel are use cases that I can think of for this panel.

As far as @grobie and myself can tell this is not possible at the moment.

I'm not sure if any of these are the direction that Grafana would like to implement this, but a couple of ideas that came up regarding the user experience of this feature be to make use of the "Legend Format" (alias) in the single-stat panel or make a new panel type altogether.

Thank you,

Dennis O.

**Comment by RichiH** [comment]
Having this is templates would be even better.

If `label_values()` had a way to enter queries and not only metric matches that would be perfect.

http://docs.grafana.org/datasources/prometheus/

**Comment by RichiH** [comment]
I.e. `label_values(state{cluster="production"} == 1, cluster_site}` would return all label values of `cluster_site` which metric `state` is 1.

**Comment by grobie** [comment]
@RichiH This is already possible using `query_result()` instead fo `label_values()`.

**Comment by RichiH** [comment]
@grobie I didn't manage to extract label values from a query result via PromQL; any pointers would be appreciated.

As a workaround, I simply grab the full result, including value and timestamp, via `query_result()` and mangle that with regexp; that's far from clean, though.

**Comment by grobie** [comment]
I think it'd be better to open a new issue for the questions/improvements around template variable expressions. This ticket is about alias usage in singlestat panels.

**Comment by grobie** [comment]
As discussed in #5095 the implementation should add a new "Alias" option to the value dropdown.

**Comment by torkelo** [comment]
this is possible in master, just select "name" in the single stat options tab, value dropdown

**Comment by bitsofinfo** [comment]
@daodennis @RichiH  @grobie can someone point me to an example of this? 

> This is already possible using query_result() instead fo label_values().

When I try to use either of these functions in the single stat panel Prometheus query editor I get unknown function. Just looking for some example of displaying a metric label in a single stat panel and can't find one.

**Comment by marefr** [comment]
@bitsofinfo see https://play.grafana.org/d/77d47mNik/prometheus-singlestat-label-value?orgId=1

**Comment by bitsofinfo** [comment]
Thanks so much!

**Comment by kaihendry** [comment]
https://play.grafana.org/d/77d47mNik/prometheus-singlestat-label-value?orgId=1 doesn't work for me. Does anyone have an example or screenshot of how one can display **prometheus_build_info** in Grafana so rollouts can be better tracked?

**Comment by marefr** [comment]
@kaihendry have updated the dashboard, see prometheus version panel.

**Comment by naughtyGitCat** [comment]
> this is possible in master, just select "name" in the single stat options tab, value dropdown

Does not supported by the new `Stat` panel

**Comment by ctrabold** [comment]
@marefr after migrating to the new stats panel the prometheus version panel on the demo site does not show the expected value. I've tested with Grafana v7.0.3 (00ee734baf) on play.grafana.org.

*Steps to reproduce this*

- Open https://play.grafana.org/d/77d47mNik/prometheus-singlestat-label-value?editPanel=2&orgId=1
- Click on `Migrate to Stat panel` button
- The `Prometheus version` is now `1`

So far I couldn't find a way to display the version string.

Is there a regression in Grafana v7.0.3 (00ee734baf) or a bug in the 'panel migration' step?

**Comment by marefr** [comment]
@ctrabold should be an an open issue regarding that. Can't find it right now though.

**Comment by ctrabold** [comment]
@marefr 👍 the 'migration issue' is tracked in #24076 thanks!
