### ISSUE TITLE
Last Table Column Not Centered

### ISSUE THREAD

**Issue by austinwilcox555** [grafana/grafana#50960]
It seems like items in the last column of a table are not centered like other centered columns in the same table. See screenshot. I believe this may be occurring because the styling is calculating the scrollbar, which does not appear when data does not exceed the table height. It does not change if the column width is defined or not.

![image](https://user-images.githubusercontent.com/77515137/174097034-7e7d3b95-b3a4-4843-affc-76409a4b2a0e.png)

**Comment by MuriloAmarals** [comment]
Hey @austinwilcox555, could you make a video or basic instructions to get to this bug ?

**Comment by austinwilcox555** [comment]
@MuriloAmarals Sorry for the delay. Please see below the steps I take to get the issue.
![ezgif-4-a2961c3d61](https://user-images.githubusercontent.com/77515137/186490036-e4c98d2c-f76d-4da9-9236-15a5f48e8f5a.gif)

**Comment by AstronautLenny** [comment]
I would like to work on this issue but Im not sure where to start.
