### ISSUE TITLE
Unit / Stat: Unit selection not being used (autoscaling down)

### ISSUE THREAD

**Issue by nhulsch** [grafana/grafana#50975]
**What happened**:
Unit format not respected after upgrading to Grafana 9.0
Unit is set to kWh (not Wh), but i.e. 140 Wh are displayed as "140 Wh".

![image](https://user-images.githubusercontent.com/2807381/174122201-3e5fd61f-ad99-458d-8257-b37c4c4e81ae.png)

**What you expected to happen**:
Display as 0.14 kWh as unit is set to kWh as on Grafana 8.x

**How to reproduce it (as minimally and precisely as possible)**:
Have value lower than 1000 with unit containing kilo

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0
- Data source type & version:  InfluxDB 1.8.10-1
- OS Grafana is installed on: Raspbian 10.12
- User OS & Browser: Windows 10 // Chrome 102
- Grafana plugins: Default
- Others:

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/pull/50117

**Comment by Drachenkaetzchen** [comment]
We monitor the power consumption in our flat, and right now it's pretty hard to figure out the consumption levels at a glance.

The prefixes are fixed to kWh, yet Grafana shows Wh.

![image](https://user-images.githubusercontent.com/162974/183043799-f7ecbc99-86d4-4413-9406-1b8ebd78bda5.png)

**Comment by amnonh** [comment]
I've opened https://github.com/grafana/grafana/issues/61736 that was closed as duplicate, looking at the suggestion it's not the same.
After grafana 9, if you have a custom ```si:``` unit, numbers that are lower than 1 are shown in ms, this is confusing and just one more chagne for the worse that is done with Grafana,
I've opened other issues about the overall usuability that is deteriorating, right now I'm keep adding workaround just to make the dashboards work similiar to what they use to in the past.
