### ISSUE TITLE
Permissions needed, user scope is not returned correctly: userId=0 and uname= empty

### ISSUE THREAD

**Issue by oxmie** [grafana/grafana#50979]
**What happened**:
- User cannot _editing_, _creating_ alert rules
- User has **admin** role and is even **grafana admin**
![Grafana Alert Editing No Permissions](https://user-images.githubusercontent.com/61626020/174125327-46eeb325-1903-4800-b47b-62ddeaff9c9f.gif)

---

**What you expected to happen**:
- User should be able to _edit_ existing alert-rules, if user is admin or permissions are granted

---

**Anything else we need to know?**:

It seams, that Grafana does not recognize my user, because watching the logs I could see, that the `userId=0` is not correct and no `uname=` is recorded.

corresponding error log:
```txt
logger=ngalert t=2022-06-16T16:49:22.032616748+02:00 level=debug msg="alert rules fetched" count=4 disabled_orgs="unsupported value type"
logger=provisioning.dashboard type=file name=default t=2022-06-16T16:49:22.706820195+02:00 level=debug msg="Start walking disk" path=/var/lib/grafana/dashboards
logger=accesscontrol.resolver t=2022-06-16T16:49:22.946317766+02:00 level=debug msg="resolved '%v' to '%v'" folders:name:ABC="unsupported value type"
logger=accesscontrol.resolver t=2022-06-16T16:49:22.946404924+02:00 level=debug msg="used cache to resolve '%v' to '%v'" folders:name:ABC="unsupported value type"
logger=accesscontrol.resolver t=2022-06-16T16:49:22.946425572+02:00 level=debug msg="used cache to resolve '%v' to '%v'" folders:name:ABC="unsupported value type"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-06-16T16:49:22.9464519+02:00 level=info msg="Access denied" userID=0 accessErrorID=ACE7174620033 permissions="any(alert.rules:write alert.rules:create alert.rules:delete)"
logger=context traceID=00000000000000000000000000000000 userId=0 orgId=1 uname= t=2022-06-16T16:49:22.946639748+02:00 level=info msg="Request Completed" method=POST path=/api/ruler/grafana/api/v1/rules/ABC status=403 remote_addr=x.x.x.x time_ms=2 duration=2.437298ms size=214 referer="https://<myhost>/grafana/alerting/T6dYefjnz/edit?returnTo=%2Falerting%2Flist" traceID=00000000000000000000000000000000
```

On other Grafana pages the logging is getting my correct `userId=9`
```txt
logger=context traceID=00000000000000000000000000000000 userId=9 orgId=1 uname=<myusername> t=2022-06-16T16:49:16.507469208+02:00 level=info msg="Request Completed" method=GET path=/api/live/ws status=400 remote_addr=x.x.x.x time_ms=16 duration=16.732875ms size=12 referer= traceID=00000000000000000000000000000000
```

During some researches, I could find out, that this code block is executed:
https://github.com/grafana/grafana/blob/b5c56f63710e09f37b8557ddd8b99ae3fc583169/pkg/services/accesscontrol/resolvers.go#L44

Current I use Grafana version: `Version 9.0.0 (commit: b5c56f6371, branch: HEAD)`
This line mentioned above is already changed during some refactoring:
https://github.com/grafana/grafana/blob/c043a8818a978fba05e54420a2f3dcad047f1af6/pkg/services/accesscontrol/resolvers.go#L44

But actually, only the logging was fixed. Therefore I am sure, this dysfunction still exists :/

User Authentication:
```sh
root@<myhost>:~# grep "\[auth\]" -A14 /etc/grafana/grafana.ini 
[auth]
disable_login_form = False
oauth_auto_login = False
disable_signout_menu = False
signout_redirect_url = https://<myhost>/Shibboleth.sso/Logout?return=https://<myhost>/grafana
[auth.proxy]
enabled = True
header_name = X-WEBAUTH-USER
header_property = username
headers = Name:X-WEBAUTH-NAME Email:X-WEBAUTH-EMAIL
auto_sign_up = True

[auth.anonymous]
enabled = True
```
---

**Environment**: Debian GNU/Linux 11 (bullseye)
- Grafana version: 
```txt
Version 9.0.0 (commit: b5c56f6371, branch: HEAD)
```
- Data source type & version:
```sh
root@<myhost>:~# apt policy grafana
grafana:
  Installed: 9.0.0
  Candidate: 9.0.0
  Version table:
 *** 9.0.0 500
        500 https://packages.grafana.com/oss/deb stable/main amd64 Packages
        100 /var/lib/dpkg/status
```
- User OS & Browser: FireFox 101.0 (64-bit) and Chromium Version 102.0.5005.61 (Official Build) (64-bit)
- Grafana plugins:
```sh
root@<myhost>:~# ls /var/lib/grafana/plugins
grafana-image-renderer
```

**Comment by joshw123** [comment]
We are also seeing this with version 9.0.1

`="Access denied to folder or dashboard" userId=0 id=8 permissions="any(all of dashboards.permissions:read, dashboards.permissions:write all of dashboards.permissions:read, dashboards.permissions:write)"`

We have anonymous enabled with Role Editor as we have SSO from the ALB.

**Comment by alexweav** [comment]
Hi, does this reproduce on the latest patch of Grafana? There have been quite a number of RBAC infrastructure fixes since this version. There were certainly bugs with anonymous users around that time, so it would be definitely worth trying.

**Comment by oxmie** [comment]
@alexweav I could not reproduce this misbehavior anymore.
I am running `Grafana v9.2.1 (34f7baebda) right now`
