### ISSUE TITLE
Why i couldn't add CloudMetric in DataSource?

### ISSUE THREAD

**Issue by thinhduckhoi** [grafana/grafana#5098]
Hi everyone.
So i'm running Ubuntu 14.04 on my company's cloud service (not AWS).
I installed grafana, grapheti as well as AWS command line.
Because i configured AWS Credentials on ./aws/credentials so i tried to add datasource into grafana but it didn't work.
It said: Problem! Failed to add datasource.
[IMG]http://i.imgur.com/lKmr0qO.jpg[/IMG]
So i don't understand how to do this. Any help would be great appreciate!

**Comment by torkelo** [comment]
Strange, this should work. 

can you look in your grafana.log (under `/var/log/grafana.log`)

**Comment by thinhduckhoi** [comment]
Now Datasource updated but i get this error:
HTTP Error
Internal Server Error

**Comment by thinhduckhoi** [comment]
Here's the content of grafana.log

2016/05/19 00:02:55 [T] Checking for updates
2016/05/19 00:12:55 [T] Checking for updates
2016/05/19 00:22:55 [T] Checking for updates
2016/05/19 00:32:55 [T] Checking for updates
2016/05/19 00:42:55 [T] Checking for updates
2016/05/19 00:52:55 [T] Checking for updates
2016/05/19 01:02:55 [T] Checking for updates
2016/05/19 01:06:27 [I] Completed 74.82.47.4 - "GET / HTTP/1.1" 302 Found 29 bytes in 770us
2016/05/19 01:12:55 [T] Checking for updates
2016/05/19 01:22:55 [T] Checking for updates
2016/05/19 01:32:55 [T] Checking for updates
2016/05/19 01:42:55 [T] Checking for updates
2016/05/19 01:52:55 [T] Checking for updates
2016/05/19 02:02:55 [T] Checking for updates
2016/05/19 02:12:55 [T] Checking for updates
2016/05/19 02:22:55 [T] Checking for updates
2016/05/19 02:32:55 [T] Checking for updates
2016/05/19 02:42:55 [T] Checking for updates
2016/05/19 02:52:55 [T] Checking for updates
2016/05/19 03:02:55 [T] Checking for updates
2016/05/19 03:12:55 [T] Checking for updates
2016/05/19 03:22:55 [T] Checking for updates
2016/05/19 03:32:55 [T] Checking for updates
2016/05/19 03:42:55 [T] Checking for updates
2016/05/19 03:52:55 [T] Checking for updates
2016/05/19 04:02:55 [T] Checking for updates
2016/05/19 04:12:55 [T] Checking for updates
2016/05/19 04:22:55 [T] Checking for updates
2016/05/19 04:32:55 [T] Checking for updates
2016/05/19 04:42:55 [T] Checking for updates
2016/05/19 04:52:55 [T] Checking for updates
2016/05/19 05:02:55 [T] Checking for updates
2016/05/19 05:12:55 [T] Checking for updates
2016/05/19 05:22:55 [T] Checking for updates
2016/05/19 05:32:55 [T] Checking for updates
2016/05/19 05:42:55 [T] Checking for updates
2016/05/19 05:52:55 [T] Checking for updates
2016/05/19 06:02:55 [T] Checking for updates
2016/05/19 06:12:55 [T] Checking for updates
2016/05/19 06:22:55 [T] Checking for updates
2016/05/19 06:32:55 [T] Checking for updates
2016/05/19 06:42:55 [T] Checking for updates
2016/05/19 06:43:00 [T] Failed to get plugins repo from grafana.net, Get https://grafana.net/api/plugins/versioncheck?slugIn=&grafanaVersion=3.0.1: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
2016/05/19 06:49:01 [I] Completed 203.174.65.44 admin "GET / HTTP/1.1" 302 Found 29 bytes in 754us
2016/05/19 06:49:01 [I] Completed 203.174.65.44 admin "GET /login HTTP/1.1" 302 Found 24 bytes in 1836us
2016/05/19 06:49:05 [D] avatar.fetch(fetch new avatar): http://secure.gravatar.com/avatar/?
2016/05/19 06:51:39 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:51:39 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 6446us
2016/05/19 06:52:13 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:52:13 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1524us
2016/05/19 06:52:16 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:52:16 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1574us
2016/05/19 06:52:55 [T] Checking for updates
2016/05/19 06:55:36 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:36 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1744us
2016/05/19 06:55:37 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:37 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2211us
2016/05/19 06:55:37 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:37 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2003us
2016/05/19 06:55:37 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:37 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1630us
2016/05/19 06:55:39 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:39 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1802us
2016/05/19 06:55:40 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:40 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2842us
2016/05/19 06:55:40 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:40 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1733us
2016/05/19 06:55:40 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:40 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1452us
2016/05/19 06:55:40 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:40 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2926us
2016/05/19 06:55:42 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:42 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2961us
2016/05/19 06:55:43 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:43 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1716us
2016/05/19 06:55:43 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:43 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2834us
2016/05/19 06:55:43 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:43 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2772us
2016/05/19 06:55:44 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:44 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2738us
2016/05/19 06:55:44 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:55:44 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2741us
2016/05/19 06:57:27 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:57:27 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 2652us
2016/05/19 06:57:56 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:57:56 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 3012us
2016/05/19 06:58:11 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:58:11 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 4023us
2016/05/19 06:59:38 [datasources.go:95 AddDataSource()] [E] Failed to add datasource: UNIQUE constraint failed: data_source.org_id, data_source.name
2016/05/19 06:59:38 [I] Completed 203.174.65.44 admin "POST /api/datasources HTTP/1.1" 500 Internal Server Error 38 bytes in 1731us
2016/05/19 07:02:55 [T] Checking for updates
2016/05/19 07:07:19 [I] Completed 203.174.65.44 admin "POST /render HTTP/1.1" 500 Internal Server Error 616 bytes in 784685us
2016/05/19 07:07:23 [D] avatar.fetch(fetch new avatar): http://secure.gravatar.com/avatar/?
2016/05/19 07:08:31 [I] Completed 203.174.65.44 admin "GET /datasources/new HTTP/1.1" 404 Not Found 19 bytes in 2062us
2016/05/19 07:08:31 [I] Completed 203.174.65.44 admin "GET /favicon.ico HTTP/1.1" 404 Not Found 19 bytes in 1894us
2016/05/19 07:08:33 [I] Completed 203.174.65.44 admin "GET /datasources/new HTTP/1.1" 404 Not Found 19 bytes in 1760us
2016/05/19 07:12:55 [T] Checking for updates
2016/05/19 07:22:55 [T] Checking for updates
2016/05/19 07:32:55 [T] Checking for updates
2016/05/19 07:42:55 [T] Checking for updates
2016/05/19 07:52:55 [T] Checking for updates
2016/05/19 08:02:55 [T] Checking for updates
2016/05/19 08:02:55 [T] Sending anonymous usage stats to stats.grafana.org
2016/05/19 08:12:55 [T] Checking for updates
2016/05/19 08:22:55 [T] Checking for updates
2016/05/19 08:32:55 [T] Checking for updates
2016/05/19 08:42:55 [T] Checking for updates
2016/05/19 08:52:55 [T] Checking for updates
2016/05/19 09:02:55 [T] Checking for updates
2016/05/19 09:12:55 [T] Checking for updates
2016/05/19 09:22:55 [T] Checking for updates
2016/05/19 09:32:55 [T] Checking for updates
2016/05/19 09:42:55 [T] Checking for updates
2016/05/19 09:52:35 [D] avatar.fetch(fetch new avatar): http://secure.gravatar.com/avatar/?
2016/05/19 09:52:42 [cloudwatch.go:139 handleListMetrics()] [E] Unable to call AWS API: NoCredentialProviders: no valid providers in chain
2016/05/19 09:52:42 [I] Completed 203.174.65.44 admin "POST /api/datasources/proxy/3 HTTP/1.1" 500 Internal Server Error 36 bytes in 358356us
2016/05/19 09:52:55 [T] Checking for updates
2016/05/19 09:52:56 [cloudwatch.go:139 handleListMetrics()] [E] Unable to call AWS API: NoCredentialProviders: no valid providers in chain
2016/05/19 09:52:56 [I] Completed 203.174.65.44 admin "POST /api/datasources/proxy/3 HTTP/1.1" 500 Internal Server Error 36 bytes in 310590us
2016/05/19 09:53:17 [cloudwatch.go:139 handleListMetrics()] [E] Unable to call AWS API: NoCredentialProviders: no valid providers in chain
2016/05/19 09:53:17 [I] Completed 203.174.65.44 admin "POST /api/datasources/proxy/3 HTTP/1.1" 500 Internal Server Error 36 bytes in 282988us

**Comment by torkelo** [comment]
looks like you already have a data source with the same name

**Comment by thinhduckhoi** [comment]
That's the first data source that I added so it can't be the same name.
