### ISSUE TITLE
Postgres Datasource: Query Data Error in UI, but not Manual Provision

### ISSUE THREAD

**Issue by Skulltulla** [grafana/grafana#50981]
**What happened**:

I attempted to add a new **Data Source** of type **PostgreSQL** through the Web UI and when I click "**Save and test**" it displays a "**Query Data Error**" , but if I add the data source manually through Grafana's provisioning system, by creating a yaml file, the error does not occur.

**What you expected to happen**:

When I click "Save and test" it displays "Database Connection OK" for a Data Source added through the Web UI.

---
**How to reproduce it (as minimally and precisely as possible)**:
- New Data Source through Web UI
  - Add a Data Source of type PostgreSQL
  - Set the properties name, host, database, user, password, TLS/SSL Mode, TLS/SSL Method, TLS/SSL Client Certificate, TLS/SSL Client Key, and Version as shown in the image below.

![image](https://user-images.githubusercontent.com/40704287/174131340-4d046707-fd09-4059-b5ba-9fc5aee5a878.png)

- New Data Source through Provisioning
  - Create a provision file, such as `/etc/grafana/provisioning/datasources/test.yaml`, with content similar to the following content and file permissions `-rw-r----- 1 grafana grafana`
---

    apiVersion: 1
    
    datasources:
      - name: TestQueryError-Provision
        type: postgres
        url: REDACTED
        database: test-query-error
        user: REDACTED
        secureJsonData:
                password: "REDACTED"
                tlsCACert: ""
                tlsClientCert: "/etc/grafana/client-cert.pem"
                tlsClientKey: "/etc/grafana/client-key.pem"
        jsonData:
              sslmode: 'require' # disable/require/verify-ca/verify-full
              maxOpenConns: 0 # Grafana v5.4+
              maxIdleConns: 2 # Grafana v5.4+
              connMaxLifetime: 14400 # Grafana v5.4+
              postgresVersion: 13 # 903=9.3, 904=9.4, 905=9.5, 906=9.6, 1000=10
              timescaledb: false
              editable: true

---
**Anything else we need to know?**:

I already had a few preconfigured PostgreSQL Data Sources that were configured in previous versions of Grafana and the connection test returns "OK". If I attempt to add a new Data Source with the exact same configuration, the new Data Source will display the "Query Data Error" message.

I was able to manually add the Postgres Data Source by creating a Provision in `/etc/grafana/provisioning/datasources` and when I click "Save and test" it returns "OK".

---
**Environment**:
- Grafana version: v9.0.0 (b5c56f6371)
- Data source type & version:
  - PostgreSQL 13 (Digital Ocean Database)
- OS Grafana is installed on:
  - Ubuntu 20.04.4 LTS
- User OS & Browser:
  - Windows 10 Home
  - Google Chrome Version 102.0.5005.115 (Official Build) (64-bit)
- Grafana plugins:
  - The following plugins are installed: "Alert List", "Alertmanager", "Annotations list", "Azure Monitor", "Bar Chart", "Bar gauge", "Candlestick", "CloudWatch", "Dashboard list", "Elasticsearch", "Gague", "Geomap",  "Getting Started", "Graph", "Graphite", "Heatmap", "Histogram", "InfluxDB", "Jaeger", "Logs", "Loki", "Microsoft SQL Server", "MySQL", "News", "Node Graph", "OpenTSDB", "Pie Chart", "PostgreSQL", "Prometheus", "Stackdriver", "Stat", "State timeline", "Status history", "Table", "Table (old)", "Tempo", "TestData DB", "Text", "Time series", "Traces", "Welcome", "Zipkin"

- Others:
  - NA

**Comment by dprokop** [comment]
@Skulltulla @jshroff-cls - has this happened before Grafana v9? Is there any information in Grafana logs or the response from the health check (when Save and test is clicked)?

**Comment by DmitrySidorow** [comment]
same issue, grafana 9.0.2 docker, postgres 12

**Comment by gabor** [comment]
as we got no response from @Skulltulla @jshroff-cls , closing the issue for now. if you are still facing this problem, please respond with the information asked  in https://github.com/grafana/grafana/issues/50981#issuecomment-1167359793 , and also these additional questions, and we can reopen the issue:

1. please try it with current grafana versions, does the problem still persist?
2. is it correct that using provisioning it works, but manually creating the datasource does not work?
3. please try to reduce the config-options to the minimum needed to reproduce the problem (for example, can you temporarily turn off TLS and connect to a local postgres instance? or perhaps turn off tls-client-auth temporarily and connect to a local postgres instance? (tls works with postgres, here we are trying to find out what exactly is wrong)

thanks!

**Comment by gabor** [comment]
@DmitrySidorow thank you for the info, but please create a separate issue, your problem may not be related to the original post ( the original dealt with the [save&test] button, your example deals with a query. they may be the same problem, but for now let's keep them separate. we can always merge them together later.).

also, please answer the questions i listed in https://github.com/grafana/grafana/issues/50981#issuecomment-1775208974 .

thanks!
