### ISSUE TITLE
UX: Clicking "refresh" should run a first time query

### ISSUE THREAD

**Issue by eyoung8** [grafana/grafana#50995]
### Background / Why we're doing this

When building a new query you have to click the "play" button at the end of the query builder to run it for the first time. I didn't notice this button as it was introduced since the last time I built a new graph and it's fairly small. My usual way of forcing a query to be run again is to click refresh, either at the top right of the graph I'm editing or within the query inspector. I think it would be a nice UX feature for either of those refreshes to run the query for the first time the same was as the "play" button does. The query inspector just spins forever, which made me think my query was somehow incorrect. At the very least having the query inspector or refresh throw a helpful error could point me toward the "play" button. Separately, I think the play button could be made more obvious though I'll leave that to an actual UX person to design.

### Is there existing research for this?

No research yet

### Problems or tasks

- The new "play" button to run a query for the first time is easy to miss for users who are unfamiliar

**Comment by gelicia** [comment]
@eyoung8 what kind of datasource are you referring to?

**Comment by torkelo** [comment]
Not sure I understand. The refresh and play button does the exact same thing
