### ISSUE TITLE
Grafana 9.0.0: Dashboard fails to load Prometheus label_values as a variable

### ISSUE THREAD

**Issue by maemigh** [grafana/grafana#51002]
**What happened**:

Grafana 8.1.2 used to load label_values as a dashboard variable, but now fails after upgrading to 9.0.0. It shows the error:

 missing `match[]` query arg

**What you expected to happen**:

Load as per older version

**How to reproduce it (as minimally and precisely as possible)**:

Using Prometheus as a data source in a dashboard variable with the template:
label_values(node_uname_info, nodename)

**Anything else we need to know?**:
<img width="1467" alt="Screen Shot 2022-06-17 at 11 06 25" src="https://user-images.githubusercontent.com/4478053/174211529-c9aabcaf-fe92-4dbc-aa8d-00b07667126d.png">

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: Prometheus
- OS Grafana is installed on: RedHat 8
- User OS & Browser: Safari 15.5
- Grafana plugins:
- Others:

**Comment by mprasil** [comment]
I think this is a duplicate of #50798. The fixed version wasn't released yet AFAIK, but there's a [workaround mentioned](https://github.com/grafana/grafana/issues/50798#issuecomment-1155622485) for the time being.

**Comment by maemigh** [comment]
I agree, this looks like a duplicate and the workaround fixed the problem. Thanks!
