### ISSUE TITLE
[Bug] tooltip cut off

### ISSUE THREAD

**Issue by RichiH** [grafana/grafana#5100]
- What grafana version are you using?

3.0.2

- What datasource are you using?

Prometheus

- What OS are you running grafana on?

CentOS

As you can see from the screen-shot, the value is cut off even though there's enough screen space to show the full graph label and value.
![grafana_3_tootltip](https://cloud.githubusercontent.com/assets/754723/15387368/0fe2f240-1dad-11e6-8e13-00ae81e34be8.png)

**Comment by torkelo** [comment]
you need to have a shorter series name, use the legend patterns to create a shorter more readable series name

**Comment by RichiH** [comment]
That's what I did; still, this seems to be a bug.

**Comment by torkelo** [comment]
It does not look like that, the series name loks very long. what is your legend format?

**Comment by RichiH** [comment]
Sorry, I meant:

I fixed it by simply using `{{fqdn}}` as legend format. That being said, the issue above is still a bug.

**Comment by torkelo** [comment]
in what way is it a bug? 

There is a max width for the series tooltip. it can always be improved and made more flexible of course :)

**Comment by RichiH** [comment]
Well, given that information is lost without need, I would consider a max width smaller than window, or screen, width a bug. I.e. allowing it to expand to 100% might be better. If you want a static max width, dropping part of the label in favour of displaying the full value is arguably better.
