### ISSUE TITLE
[Feature Request] Make it possible to reference Org by its name in LDAP config

### ISSUE THREAD

**Issue by zstyblik** [grafana/grafana#5102]
Hello,

I think it would be useful to make it possible to reference(lookup) organization by its name and not only its `org_id` in `ldap.toml` as it is now. It seems to me to be cumbersome to keep track of IDs through multiple environments, eg. dev and prod, and it seems to me it would be easier to just put organization name into `ldap.toml` and "fire and forget".

I mean, role and group assignment is done based on LDAP group membership like so:

```
[[servers.group_mappings]]
group_dn = "CN=somegroup,OU=users,DC=myorg,DC=world"
org_role = "Admin"
org_id = 3
```

But it wouldn't it be more convenient to do it like:

```
[[servers.group_mappings]]
group_dn = "CN=somegroup,OU=users,DC=myorg,DC=world"
org_role = "Admin"
org_name = "self-responsible dept"
```

Then you don't have to care that ID in dev is different, because you've created a test org and now you have to do it elsewhere as well, because ID is different. Yes, orgs have the same privileges to dashboards they own in both environments.

The main drawback I can think of are two organizations with the exactly same name. However, you can still fall back to `org_id` to distinguish between orgs.

Thank you for consideration.

**Comment by torkelo** [comment]
One problem with only name is that if you change the name no one can login :)

**Comment by zstyblik** [comment]
@torkelo, true, I haven't thought of that. I'm still in pain over `org_id`, though, since org names are given and stable. :\

**Comment by yesoreyeram** [comment]
> One problem with only name is that if you change the name no one can login :)

Otherwise, Allow to specify org_id when creating orgs. Like we do for dashboards.  I see we have options to edit dashboard id.

**Comment by pkolyvas** [comment]
We're in the process of moving Grafana feature requests to [GitHub Discussions](https://community.grafana.com/t/were-moving-grafana-feature-requests-to-github-discussions/50341/3). I'm closing feature requests that have seen limited from the community and/or the Grafana team. 

Should this feature still be of interest to you, please re-create it in our [Discussions area](https://github.com/grafana/grafana/discussions). In doing so the community can continue to contribute to exploring, confirming and sharing their use cases (and more).

As with all things Grafana, we value your input and participation in this project and appreciate your patience during this transitional period. Should you wish to connect to discuss anything Grafana-related, I have an open door policy and [my contact details are on my GitHub profile page](https://github.com/pkolyvas).
