### ISSUE TITLE
[Bug] 401 Unauthorized error logs with ElasticSearch as a data source.

### ISSUE THREAD

**Issue by korablin** [grafana/grafana#5104]
I am trying to use Grafana with ElasticSearch as a data source. We have a proxy server in between. 
Once Grafana installed from scratch - it works fine for a while, then it stops displaying data.
ES version is 1.5.2, for Grafana we have tested different versions from 2.0 to 3.0 and result is the same everywhere - no data is being visualized and 401 error in logs.

We have tried installing Grafana on different servers. Mostly it was RHEL 7 OS.

Also, if I will create a graph with empty query and count function - it will show how many metrics we receive.

Here are logs:
```
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 7917us
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 8236us
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 763us
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 1426us
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 1418us
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 4619us
May 18 17:12:10 server grafana-server[30009]: 2016/05/18 17:12:10 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 4929us
May 18 17:12:40 server grafana-server[30009]: 2016/05/18 17:12:40 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 179us
May 18 17:12:40 server grafana-server[30009]: 2016/05/18 17:12:40 [I] Completed *** "POST /api/datasources/proxy/1/_msearch HTTP/1.1" 401 Unauthorized 26 bytes in 249us
```

**Comment by torkelo** [comment]
this is strange, no one else has reported anything similar. Maybe your proxy server has issues? 
What's your method of authenticating in Grafana?

**Comment by korablin** [comment]
@torkelo Hey! Thanks for response!
We are using basic authentication for acces to ES, and Grafna works fine for a while, but then it's stops showing any data.. and we are seeing 401 in logs

**Comment by korablin** [comment]
Hi @torkelo !
I played a bit more with grafana and ES configurations.

There is a thing I have noticed:
If I change ES template (even with insignificantly), Grafana starts throwing 401 errors. So it works just with a default template for me.

What other information I could provide you?

**Comment by torkelo** [comment]
ES template?

**Comment by korablin** [comment]
**## [root@build-server-omar ~]# curl -XGET localhost:9200/_template?pretty**
```
{
  "logstash" : {
    "order" : 0,
    "template" : "logstash-*",
    "settings" : {
      "index.refresh_interval" : "5s"
    },
    "mappings" : {
      "_default_" : {
        "dynamic_templates" : [ {
          "message_field" : {
            "mapping" : {
              "index" : "analyzed",
              "omit_norms" : true,
              "type" : "string"
            },
            "match_mapping_type" : "string",
            "match" : "message"
          }
        }, {
          "string_fields" : {
            "mapping" : {
              "index" : "analyzed",
              "omit_norms" : true,
              "type" : "string",
              "fields" : {
                "raw" : {
                  "ignore_above" : 256,
                  "index" : "not_analyzed",
                  "type" : "string"
                }
              }
            },
            "match_mapping_type" : "string",
            "match" : "*"
          }
        } ],
        "_all" : {
          "omit_norms" : true,
          "enabled" : true
        },
        "properties" : {
          "geoip" : {
            "dynamic" : true,
            "type" : "object",
            "properties" : {
              "location" : {
                "type" : "geo_point"
              }
            }
          },
          "@version" : {
            "index" : "not_analyzed",
            "type" : "string"
          }
        }
      }
    },
    "aliases" : { }
  },
  "metrics" : {
    "order" : 0,
    "template" : "collectd-*",
    "settings" : {
      "index.refresh_interval" : "5s"
    },
    "mappings" : {
      "_default_" : {
        "dynamic_templates" : [ {
          "message_field" : {
            "mapping" : {
              "index" : "analyzed",
              "omit_norms" : true,
              "type" : "string",
              "doc_values" : true
            },
            "match_mapping_type" : "string",
            "match" : "message"
          }
        }, {
          "string_fields" : {
            "mapping" : {
              "index" : "analyzed",
              "omit_norms" : true,
              "type" : "string",
              "fields" : {
                "raw" : {
                  "ignore_above" : 256,
                  "index" : "not_analyzed",
                  "type" : "string",
                  "doc_values" : true
                }
              }
            },
            "match_mapping_type" : "string",
            "match" : "*"
          }
        } ],
        "_all" : {
          "enabled" : true
        },
        "properties" : {
          "@timestamp" : {
            "type" : "date",
            "doc_values" : true
          },
          "geoip" : {
            "dynamic" : true,
            "type" : "object",
            "properties" : {
              "location" : {
                "type" : "geo_point",
                "doc_values" : true
              }
            }
          },
          "host" : {
            "index" : "not_analyzed",
            "type" : "string",
            "doc_values" : true
          },
          "@version" : {
            "index" : "not_analyzed",
            "type" : "string"
          }
        }
      }
    },
    "aliases" : { }
  }
}

```


I have 2 templates for 2 different indexes. One for logs, and one for metrics, so Grafana works with the 2nd one, called "metrics". (Provided first just in case..).

Basically both of them are exactly default, except  this part:
  ` "host" : {
            "index" : "not_analyzed",
            "type" : "string",
            "doc_values" : true
          },`

I just want the host name to be not_analyzed, otherwise it brakes  the term into parts. Using of .raw fields doesn't help - Grafana still shows fields that are not related.

**Comment by torkelo** [comment]
Not related? Not sure what your terms query had to do with the 401 errors from your proxy

**Comment by korablin** [comment]
@torkelo 
One more thing I have noticed - if I disable _all field, it also starts throwing 401 errors..

Like this:
`"_all" : {
          "enabled" : false`

In the same time Kibana works fine, and able to query any metrics...

**Comment by erezny** [comment]
I ran into this same error today. 

We run Elasticsearch with the ReadOnlyRest plugin and expected to be able to use the default read_only profile. The default read_only profile only allows GET requests through. Grafana queries tends to be POSTs which were blocked by the plugin.

**Comment by msn** [comment]
We're also affected by this:

https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/elasticsearch/datasource.js#L101

uses a POST request which due to nginx fronting our ES cluster and restricting to ro requests this get's 401 denied. If grafana used GET here instead, this would be fine.

**Comment by torkelo** [comment]
ES msearch api ford not support GET

**Comment by torkelo** [comment]
strange, it appear's Elasticsearch supports body in GET requests, which is kind of in violation of the HTTP spec :) 

> Yes, you can send a request body with GET but it should not have any meaning. If you give it meaning by parsing it on the server and changing your response based on its contents, then you are ignoring this recommendation in the HTTP/1.1 spec, section 4.3:

**Comment by torkelo** [comment]
closing this for lack of updates and others who have encountered  the same issue
