### ISSUE TITLE
Grafana v9 returns 500 error when math expressions use hidden query

### ISSUE THREAD

**Issue by zmiguel** [grafana/grafana#51058]
**What happened**:

Since version 9 the math expressions stopped working when the query field they use is hidden.

**What you expected to happen**:

Math expressions should work when the query they use is hidden like it did in the previous versions

**How to reproduce it (as minimally and precisely as possible)**:

* Add a new panel (state timeline, time series, etc)
* Add 2 queries
* Add simple math expression using those 2 queries, ex: $A -$B
* Hide A or B or both and the panel will return a 500 error

**Anything else we need to know?**:

See attached video for an example.

https://user-images.githubusercontent.com/4400540/174352233-64b7ea33-2f2f-4cd9-8b18-faeab962dabb.mov

**Environment**:
- Grafana version: v9.0.0 (b5c56f637)
- Data source type & version: InfluxDB 2
- OS Grafana is installed on: Docker, Ubuntu host
- User OS & Browser: Mac OS 12.4 + Chrome, Windows 10 + Chrome
- Grafana plugins: Core plugins only
- Others:

**Comment by gelicia** [comment]
This should be fixed in 9.0.1 with https://github.com/grafana/grafana/pull/50636 - please reopen the ticket if this still occurs after 9.0.1 is released. Thank you!
