### ISSUE TITLE
Unable to manage loki rules with grafana

### ISSUE THREAD

**Issue by rlex** [grafana/grafana#51077]
**What happened**:

loki-distributed helm chart. Ruler enabled, configured with S3 storage. Test rules created. Loki configured with "manage alerts" toggle set to on. Loki datasource works in general - ingesting and showing logs.

Test alert created with cortextool - i can see them in alerting panel (grafana_url/alerting/list), so ruler works. Folders and files with alerts also appear in s3 storage.

However, when i go to alerting/new, and choose to create loki or mimir alert / recording rule, i do not see my loki datasource in dropdown menu with datasources - only mimir (test install).

**What you expected to happen**:

I should see loki in drop down menu when selecting alerting rules datasource

**How to reproduce it (as minimally and precisely as possible)**:

Install loki from loki-distributed helm chart with ruler and gateway enabled and s3 storage configured
Add loki datasource with managed alerts enabled
Try to create loki rule from grafana

**Anything else we need to know?**:

**Environment**:
- Grafana version: https://github.com/grafana/grafana/commit/244650835e82e7e7a8c13ca6d71c131cb0d727cc
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox 101.0.1, OS X 12.4

**Comment by peterholmberg** [comment]
Hi @rlex , is it available in the data source drop down if you try a Grafana managed alert?

**Comment by rlex** [comment]
No, i only see mimir there. But i can see alerts i uploaded with cortextool to loki in /alerting/list. Can't edit them or delete - only view is avaiable.

**Comment by peterholmberg** [comment]
Thanks, I'll investigate further 🕵️

**Comment by peterholmberg** [comment]
@rlex do you see any errors on the Alert list page or in your server logs that indicate that something is off?

**Comment by rlex** [comment]
Yeah, https://grafana_host/api/ruler/jLCNwmanz/api/v1/rules/test/test returns 404
Where jLCNwmanz is ID of loki datasource.

It seems like default loki-gateway configmap in helm chart lacks proper route to ruler endpoint?

```
worker_processes  5;  ## Default: 1
error_log  /dev/stderr;
pid        /tmp/nginx.pid;
worker_rlimit_nofile 8192;

events {
  worker_connections  4096;  ## Default: 1024
}

http {
  client_body_temp_path /tmp/client_temp;
  proxy_temp_path       /tmp/proxy_temp_path;
  fastcgi_temp_path     /tmp/fastcgi_temp;
  uwsgi_temp_path       /tmp/uwsgi_temp;
  scgi_temp_path        /tmp/scgi_temp;

  default_type application/octet-stream;
  log_format   main '$remote_addr - $remote_user [$time_local]  $status '
        '"$request" $body_bytes_sent "$http_referer" '
        '"$http_user_agent" "$http_x_forwarded_for"';
  access_log   /dev/stderr  main;

  sendfile     on;
  tcp_nopush   on;
  resolver kube-dns.kube-system.svc.cluster.local;
  
  proxy_http_version 1.1;
  

  server {
    listen             8080;
    auth_basic           "Loki";
    auth_basic_user_file /etc/nginx/secrets/.htpasswd;

    location = / {
      return 200 'OK';
      auth_basic off;
    }

    location = /api/prom/push {
      proxy_pass       http://loki-distributor.loki.svc.cluster.local:3100$request_uri;
    }

    location = /api/prom/tail {
      proxy_pass       http://loki-querier.loki.svc.cluster.local:3100$request_uri;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    # Ruler
    location ~ /prometheus/api/v1/alerts.* {
      proxy_pass       http://loki-ruler.loki.svc.cluster.local:3100$request_uri;
    }
    location ~ /prometheus/api/v1/rules.* {
      proxy_pass       http://loki-ruler.loki.svc.cluster.local:3100$request_uri;
    }
    location ~ /api/prom/rules.* {
      proxy_pass       http://loki-ruler.loki.svc.cluster.local:3100$request_uri;
    }
    location ~ /api/prom/alerts.* {
      proxy_pass       http://loki-ruler.loki.svc.cluster.local:3100$request_uri;
    }

    location ~ /api/prom/.* {
      proxy_pass       http://loki-query-frontend.loki.svc.cluster.local:3100$request_uri;
    }

    location = /loki/api/v1/push {
      proxy_pass       http://loki-distributor.loki.svc.cluster.local:3100$request_uri;
    }

    location = /loki/api/v1/tail {
      proxy_pass       http://loki-querier.loki.svc.cluster.local:3100$request_uri;
      proxy_set_header Upgrade $http_upgrade;
      proxy_set_header Connection "upgrade";
    }

    location ~ /loki/api/.* {
      proxy_pass       http://loki-query-frontend.loki.svc.cluster.local:3100$request_uri;
    }
  }
}
```

**Comment by peterholmberg** [comment]
What 404 error are you getting? We're also seeing a 404 with loki and s3 object storage but that's a test to see if the ruler api is enabled. And we're seeing our loki data source in the "Create mimir or loki rule" dropdown. 

Have you tried reaching out to https://github.com/grafana/helm-charts/tree/main/charts/loki-distributed and see if they have any thoughts on what the issue could be?

**Comment by rlex** [comment]
Yeah, i tried adding all endpoints that potentially can affect this with no luckl.

**Comment by craftyc0der** [comment]
I ran into this same problem. It went away as soon as I added a loki managed rule in the `test` namespace with a group name of `test`. My server logs showed a suspicious 404 error going to `GET /loki/api/prom/rules/test/test HTTP/1.1" 404`.
The grafana go code looks like it bails on any error so I added a dummy rule and I it works.
```
cortextool rules list --id=fake --backend=loki --address=https://foo.bar/loki
Namespace | Rule Group
test      | test
```
![image](https://user-images.githubusercontent.com/7999936/183293090-9b2a036c-835a-4d38-869b-23e33d385718.png)

**Comment by armandgrillet** [comment]
We should add some information to the Loki `buildinfo` to avoid having to do some guesswork, we already do this with Mimir.

**Comment by wkshare** [comment]
@armandgrillet 
https://github.com/grafana/grafana/blob/712f3fb8b271985e72b609127dfb51b6cea395ed/public/app/features/alerting/unified/api/ruler.ts#L97

this code need to fix.

**Comment by wkshare** [comment]
I think so
