### ISSUE TITLE
Openhab 3.2 / InfluxDB + Grafana 9 not working

### ISSUE THREAD

**Issue by renekar** [grafana/grafana#51076]
Update openhab 3.2/ influxDB from 8.5.x to 9.0. After successful update access to data is not possible any longer

Message at the grafana panels: `'InfluxDB Error: Bad Request'`
Details:
```
Authentication to data source failed
Object
message:"InfluxDB Error: Bad Request"
data:Object
message:"Authentication to data source failed"
error:"Bad Request"
response:"Authentication to data source failed"
config:Object
method:"POST"
url:"api/datasources/proxy/1/query"
params:Object
data:"q=SELECT%20mean(%22value%22)%20FROM%20%22localCurrentPressure%22%20WHERE%20time%20%3E%3D%20now()%20-%2024h%20and%20time%20%3C%3D%20now()%20GROUP%20BY%20time(2m)%20fill(null)"
precision:"ms"
inspect:Object
paramSerializer:function serializeParams(e){…}
headers:Object
retry:0
hideFromInspector:false
```

**Comment by tkranz** [comment]
have the same error !

**Comment by Toniob** [comment]
Same issue on a Debian Bullseye since the update to 9.0 with an InfluxDB source.

**Comment by sjorge** [comment]
I'm guessing https://github.com/grafana/grafana/issues/49987 is the reason why

**Comment by Diapolo** [comment]
Same here, after re-entering the PW it seems to work again.

**Comment by itsmylife** [comment]
Entering the password and saving will resolve the issue. As @sjorge stated https://github.com/grafana/grafana/pull/49987 is the reason why. I am closing this one. If you still have problems feel free to open a new issue.
