### ISSUE TITLE
Error compiling grafana front end at grafana 8.5.6

### ISSUE THREAD

**Issue by HelloWorDomain** [grafana/grafana#51079]
**What happened**:
Error compiling grafana front end at grafana 8.5.6,
My back-end go has been compiled.
When I execute the following command to compile the front-end nodejs, the following error occurs

**What you expected to happen**:
yarn OK when exec the yarn

**How to reproduce it (as minimally and precisely as possible)**:
```
cd /code/grafana-8.5.6 && yarn install --pure-lockfile
```
error An unexpected error occurred: "https://registry.npmjs.org/@jaegertracing%2fjaeger-ui-components: Not found".

**Anything else we need to know?**:
However, it seem like nodejs web does not work , I'm not sure。

**Environment**:
- Grafana version: 8.5.6
- Data source type & version:
- OS Grafana is installed on: CentOS 7.9
- User OS & Browser:
- Grafana plugins:
- Others:
- node 16.15.1
- yarn 1.22.19

**Comment by joshhunt** [comment]
I'm not able to replicate this. 

```
> git co v8.5.6
HEAD is now at 623255cf2d "Release: Updated versions in package to 8.5.6" (#370)

> yarn --version
3.2.0

> yarn cache clean --all
➤ YN0000: Done in 0s 5ms

> yarn
[a lot of output]
➤ YN0000: ┌ Link step
➤ YN0000: │ ESM support for PnP uses the experimental loader API and is therefore experimental
➤ YN0000: └ Completed in 0s 604ms
➤ YN0000: Done with warnings in 1m 36s
```

When you run `yarn --version` from within the Grafana directory, what version do you get? The repo bundles yarn 3.2, which your yarn on path should look up from our `.yarnrc.yml` file and use.

If you're able to create a Dockerfile which replicates the problem it would be appreciated

**Comment by HelloWorDomain** [comment]
3X, I found the reason. Because I deleted the "." under the source folder Hidden folder at the beginning. Thank you very much for your help~
