### ISSUE TITLE
Grafana 9.0.0 - Gantt is not working

### ISSUE THREAD

**Issue by deejayluk** [grafana/grafana#51086]
**What happened**:
![image](https://user-images.githubusercontent.com/73607094/174532050-c565871c-21ac-42fa-b1bc-d43e2ed917e3.png)

**What you expected to happen**:
to solve this problem

**Anything else we need to know?**:
in version 8.5.2 worked correct

**Environment**:
Grafana version: 8.5.2
Data source type & version: MSSQL
OS Grafana is installed on: Ubuntu 20.04.4 LTS
User OS & Browser: Chrome
Grafana plugins: TimeSeries
Others: N/A

**Comment by daniellee** [comment]
This is referring to the [Gantt plugin](https://grafana.com/grafana/plugins/marcusolsson-gantt-panel/) from @marcusolsson 

@deejayluk are you on the latest version of the plugin (version 0.8.0)?

**Comment by deejayluk** [comment]
sorry 0.7.4, I will check new version and inform you

**Comment by deejayluk** [comment]
the same issue

![image](https://user-images.githubusercontent.com/73607094/174577436-09cfbbe7-e1dd-47cc-8a1f-c2faadfee511.png)

**Comment by deejayluk** [comment]
before I had a table
![image](https://user-images.githubusercontent.com/73607094/174577546-b744fc3a-bfe2-4f85-b824-93dc0e3c527d.png)
If change to time series then:
![image](https://user-images.githubusercontent.com/73607094/174577625-fcd0d2a4-e550-4c39-9e4c-4e1838b37dd7.png)
but previously I had table and everythink worked okay

**Comment by deejayluk** [comment]
okay, I changed code, the time column is first and bar are okay

**Comment by leeoniya** [comment]
@deejayluk you can also try the State timeline panel that's in Grafana core:

https://play.grafana.org/d/qD-rVv6Mz/6-state-timeline-and-status-history?orgId=1
