### ISSUE TITLE
Explore queries containing %-character redirect incorrectly on login-flow.

### ISSUE THREAD

**Issue by hterik** [grafana/grafana#51097]
**What happened**:

**Example of working flow:**
A1. Log in to grafana
A2. Open url: `/explore?orgId=1&left={"datasource":"Loki","queries":[{"refId":"A","expr":"{job%3D\"test\"} | line_format \"{{printf \\\"%25-100s\\\" .message}}\"","hide":false}],"range":{"from":"1655480401649","to":"1655481610633"}}`
A3. Query is displayed correctly 

**Repeat same thing, with same url, but start as logged out:**
B1. Log out from grafana 
B2. Open url: `/explore?orgId=1&left={"datasource":"Loki","queries":[{"refId":"A","expr":"{job%3D\"test\"} | line_format \"{{printf \\\"%25-100s\\\" .message}}\"","hide":false}],"range":{"from":"1655480401649","to":"1655481610633"}}`
B3. Log in when prompted
B4. Grafana dos not display query correctly, instead it redirects to `/explore?orgId=1&left={"datasource":"-- Grafana --","queries":[{"refId":"A"}],"range":{"from":"now-1h","to":"now"}}`

**Anything else we need to know?**:
It appears that somewhere in the redirection flow, the `redirect_to`-cookie gets the uri-encoding wrong for the percentage-character (`%25` becomes plain `%`).
Queries that don't contain a `%`-character don't have the problem described above.

**Environment**:
- Grafana version: 8.5.5
- User OS & Browser: Firefox
- Grafana plugins: Azure AD auth

**Comment by gelicia** [comment]
I just attempted to replicate this on `main` after the fix I put in for explore URLs more generically (https://github.com/grafana/grafana/pull/57381) and I can't replicate this. Are you able to test on `main` ?

**Comment by hterik** [comment]
Thanks for the fix gelicia, i can only test on 9.2 so far and there the issue still remains. I will try again once 9.3 is released.

**Comment by gelicia** [comment]
Please reopen if this is still an issue for you. Thank you!

**Comment by hterik** [comment]
Sorry, this is still broken in **9.3.0**. 
The symptom in B4 is slightly different from before but the end result is still that the user doesn't see the query that was originally provided in the url.
Now when following B1-B2, it redirects to following url instead: `/explore?orgId=1&left={"datasource":"Loki","queries":[{"refId":"A","datasource":{"type":"loki","uid":"Loki"}}],"range":{"from":"now-1h","to":"now"}}`

**Comment by hterik** [comment]
By inspecting the log i can see following during B2:
`logger=context t=2022-12-01T08:22:50.204695879Z level=error msg="Failed to parse query parameters" error="invalid URL escape \"%-1\""
`

**Comment by hterik** [comment]
@gelicia can you please reopen this, i don't have access to do so.

**Comment by gelicia** [comment]
@hterik I'm not sure what happened but at some point I was unable to reproduce this again. Can you take a look at this and let me know what I might be missing? This is 9.3 in a new incognito window.

https://user-images.githubusercontent.com/1533128/206036153-d915b11d-6342-4b7a-9408-9a88397f7156.mov

**Comment by hterik** [comment]
Your video appears to be using basic-auth. For me the problem only occurs with Azure AD.  https://grafana.com/docs/grafana/v9.3/setup-grafana/configure-security/configure-authentication/azuread/
I tried with basic auth also and there i experience no problem, works fine just like in your video.

```

[auth]
oauth_auto_login = true
disable_login_form = true

[auth.basic]
enabled = false

[auth.azuread]
enabled = true
etc...
```

**Comment by gelicia** [comment]
Sending this to a team more focused on Auth, since I don't have any sort of oauth set up to use to replicate/test.

To TL;DR for that team, the scenario described works in basic login and does not in oauth login. I believe the issue can be fixed by not unescaping the cookie itself before redirecting.

Here, in normal auth (that works), the redirect is simply the value of the cookie. This same logic is used in the response to the login POST, where the cookie value is set as a parameter that is returned with the response.
https://github.com/grafana/grafana/blob/main/pkg/api/login.go#L121
https://github.com/grafana/grafana/blob/main/pkg/api/login.go#L244

In oauth (that breaks), the cookie is unescaped, and then the redirect is that unescaped value. https://github.com/grafana/grafana/blob/main/pkg/api/login_oauth.go#L261

**Comment by hterik** [comment]
Sorry, @kalleep can you please reopen. This is still not working in 9.3.4.

**Comment by kalleep** [comment]
@hterik Yeah seems like I forgot to merge the backport, https://github.com/grafana/grafana/pull/60878. Will get that one merged asap

**Comment by hterik** [comment]
Works good in 9.3.6. Thanks a lot :+1:

**Comment by bmdeshmukh18** [comment]
We started to get this issue after we upgraded from v6.5.2 to v8.4.10.

Is it possible to implement these changes in Grafana v8.4.10?
Changes done in #60878 

If so, how and where can we make those changes?
