### ISSUE TITLE
Cloudwatch variable editor crashes when migrating variable query (v9 issue)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#51094]
I tried to import a dashboard with a variable query that looked like `dimension_values($region,CWAgent,cpu_usage_active,host,{"role":${role:json},"pop":${pop:json}})`  

This caused "unable to migrate poorly formed filters" errors during dashboard load and the variable query editor crashed. 

https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/cloudwatch/migrations/variableQueryMigrations.ts#L98

**Comment by yaelleC** [comment]
Same error ("unable to migrate poorly formed filters") but does not crash in `8.5.x` too.
The change was possibly introduced by https://github.com/grafana/grafana/pull/46943 
And for the `9.0.0` version of the issue (variable query editor crashing) : https://github.com/grafana/grafana/pull/47596
