### ISSUE TITLE
Is there a way to to swith panels in  one  Row using a "Tab Control"

### ISSUE THREAD

**Issue by superwood** [grafana/grafana#5110]
Is there a way to to swith panels in  one  Row using a "Tab Control"?

**Comment by torkelo** [comment]
not sure what you mean switch?

**Comment by utkarshcmu** [comment]
@superwood No, there is no current way of doing that. I would love to have it too. :)

**Comment by superwood** [comment]
Is there a way to to switch panels in one Row using a "Tab Control"?
