### ISSUE TITLE
Alerting: cannot delete/update incorrect notification policy provisioned with HTTP API

### ISSUE THREAD

**Issue by gjed** [grafana/grafana#51108]
**What happened**:
Cannot delete or update an incorrect policy that was provisioned with the Alerting Provisioning API. 
From API:
```
{
  "message": "failed to deserialize alertmanager configuration: unexpected receiver (grafana-default-email2) is undefined",
  "traceID": "00000000000000000000000000000000"
}
```
From GUI:

![Screenshot from 2022-06-20 12-43-32](https://user-images.githubusercontent.com/12700875/174585110-d3b3b1ee-eb86-4f9d-bf5e-78c527742f54.png)

**What you expected to happen**:
Either of the following:
- being able to update the incorrect policy
- eliminate the incorrect policy

**How to reproduce it (as minimally and precisely as possible)**:
On a fresh grafana instance:
```
curl -X PUT \
  'http://loclahost:3000/api/v1/provisioning/policies' \
  --header 'Accept: application/json' \
  --header 'Content-Type: application/json' \
  --header 'Authorization: Basic <you auth here>' \
  --data-raw '{
  "receiver": "grafana-default-email2"
}'
```

**Anything else we need to know?**:
Fyi: i fixed it with a replace on the db:
```
update alert_configuration set alertmanager_configuration = replace(alertmanager_configuration, 'email2', 'email');
```

**Environment**:
- Grafana version: 9.0.0 b5c56f6371 (docker)
- Data source type & version: /
- OS Grafana is installed on: (Docker)
- User OS & Browser: Debian 11, Chrome
- Grafana plugins: /
- Others: /

**Comment by fatbasstard** [comment]
Hit the same issue here against a grafana 8.5.15 instance. Removed an Alert rule successfully from the API. And now the Entire alerting part of Grafana is not loading.

Seems like a "bug" (in the API?), you should not be able to remove rules if they are in use

**Comment by yuri-tceretian** [comment]
This was fixed in https://github.com/grafana/grafana/pull/51561 (Grafana 9.0.3)
