### ISSUE TITLE
Backend does not run correctly on i386 - please upgrade to segmentio/encoding >= 0.3.3

### ISSUE THREAD

**Issue by blaniel** [grafana/grafana#51118]
Hello,

When run on i386, grafana-server 8.5.5 stops on 'panic: not implemented'.

Problem comes from segmentio/asm/keyset v1.1.1 which only has an amd64 implementation (https://github.com/segmentio/asm/blob/v1.1.1/keyset/keyset_default.go). It has been fixed in commit https://github.com/segmentio/asm/commit/df903c96001307d7705d693df6fb377e1eff89ff (available in segmentio/asm >= 1.1.2)

This module dependency comes from segmentio/encoding. Fix has been added in v0.3.3 (https://github.com/segmentio/encoding/commit/42eedba359fe40fbffdd4c31c031032aa58f1867).

Would it be possible to update segmentio/encoding to v0.3.3 or later?

Thanks for your great software!

**Comment by tolzhabayev** [comment]
segmentio/encoding was bumped in https://github.com/grafana/grafana/pull/51977 please use the latest version.
