### ISSUE TITLE
Repeating panel should re-evaluate variables dependent on repeating variable

### ISSUE THREAD

**Issue by lukebigum** [grafana/grafana#51116]
**What happened**:

An InfluxDB Query variable used in the definition of another variable does not trigger the 2nd variable to be re-evaluated when the 1st variable is used in a repeating panel.

**What you expected to happen**:

When repeating a panel over $var1, I expected the values of $var2 to be re-evaluated with each value of $var1, thus changing the values of $var2 for each panel.

What appears to be happening is $var2 is avaluated once, or takes the "global" dashboard's query result.  This can lead to some odd results where a a panel that is repeating over $var1 but making use of $var2 will look odd, because $var2's value is not changing.

**How to reproduce it (as minimally and precisely as possible)**:

Best demonstrated with Telgraf & InfluxDB.  The attached ZIP has a simple Telegraf config, sample data, and a Grafana dashboard.  This is a contrived example, but it does demonstrate the problem.

[sample.zip](https://github.com/grafana/grafana/files/8940754/sample.zip)

Using Influx 1.x as it's slightly simpler, problem would exist on InfluxDB 2.x as well:

```
docker run -p8086:8086 influxdb:1.8.10
```

Load the data:

```
telegraf --config=sample-telegraf.conf
```

Start Grafana and import the dashboard.  It should look like this:

![Screenshot from 2022-06-20 13-57-10](https://user-images.githubusercontent.com/1107881/174606844-b8faf91a-5a2e-4efc-abf5-21155f60992a.png)

The dashboard has two multi-value variables, one dependent on the other.  Their queries are:

```
show tag values on "telegraf" with key = "fstype"
show tag values on "telegraf" with key = "path" where "fstype" =~ /$fstype/
```

The panel repeats over the variable `$fstype` which has 3 values: `ext4`, `vfat` and `xfs`.

If you run the Query Inspector for each panel, it displays the same query each time:

```
SELECT sum("free") FROM "disk" WHERE ("path" =~ /^(\/|\/boot|\/boot\/efi|\/home)$/) AND time >= 1655724975740ms and time <= 1655729598619ms GROUP BY time(10s) fill(previous)
SELECT sum("free") FROM "disk" WHERE ("path" =~ /^(\/|\/boot|\/boot\/efi|\/home)$/) AND time >= 1655724975740ms and time <= 1655729598619ms GROUP BY time(10s) fill(previous)
SELECT sum("free") FROM "disk" WHERE ("path" =~ /^(\/|\/boot|\/boot\/efi|\/home)$/) AND time >= 1655724975740ms and time <= 1655729598619ms GROUP BY time(10s) fill(previous)
```

The value of variable $path comes from the dashboard's point of view, which is to have $fstype set to "All".  However, with the panel repeating over each fstype, it would be much more useful if $path was re-evaluated for every value of $fstype.  The expected values would be:

```
$fstype = 'ext4',  $path = [ '/boot' ]
$fstype = 'vfat',  $path = [ '/boot/efi' ]
$fstype = 'xfs',  $path = [ '/', '/home' ]
```

Now, in this very specific example you could "fix" the problem by adjusting the query to make use of $fstype.   That would work for this dashboard, but as stated before this is a contrived example.  I have other more complicated queries and dashboards where this behaviour is in the way.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.2  &  9.0.0
- Data source type & version: Telegraf & InfluxDB
- OS Grafana is installed on: CentOS 8
- User OS & Browser: Fedora 34
- Grafana plugins: n/a

**Comment by halfway258** [comment]
Was this addressed in new Grafana versions? I believe it's an important issue
