### ISSUE TITLE
Docker: Explore the use of `docker buildx build` for cross compilation

### ISSUE THREAD

**Issue by dsotirakis** [grafana/grafana#51128]
**What happened**:

Currently when we build docker images, we need to build them for multiple architectures. Our building process is using `docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64` which sometimes fails to get fetched and thus the whole pipeline fails. 

Lately, `docker buildx build` seems stable and it may be the way to move forward for building various architectures.

Documentation: https://docs.docker.com/buildx/working-with-buildx/

**Comment by summerwollin** [comment]
Implemented by grafana-build
