### ISSUE TITLE
[bug] Panel "text" are not aligned properly

### ISSUE THREAD

**Issue by thouveng** [grafana/grafana#5113]
I'm using Grafana version: 3.0.2, commit: v3.0.1+21-g0c345e2, build date: 2016-05-16 09:06:39.
I observed an issue where panel are not aligned as expected. 

In my row I have six panels each with a span of 2. The first panel is a _text_ panel, the following four panels are _singlestat_ panel and the sixth panel is a _text_ panel. So all panels fit on one line. Then I add a seventh panel that is a _text_ panel with also a span of 2. I expected to see this panel aligned with the first one but instead it is aligned with the sixth one. I observe this behaviour if panel number 6 and number 7 are both _text_ panels.

Here is a schema to describe the issue.

I see that (all spans are equal to 2)
```
+----------------+ +----------------+     +---------------+ +----------------+
|     Text #1    | | singlestast #2 | ... | singlestat #5 | |     text #6    |
+----------------+ +----------------+     +---------------+ +----------------+
                                                            +----------------+
                                                            |     text #7    |
                                                            +----------------+
```

where I expected that:
```
+----------------+ +----------------+     +---------------+ +----------------+
|     Text #1    | | singlestast #2 | ... | singlestat #5 | |     text #6    |
+----------------+ +----------------+     +---------------+ +----------------+
+----------------+
|     Text #7    |
+----------------+
```

Regards,

**Comment by thouveng** [comment]
Here is a screenshot of the same issue but with: a text panel of 2 spans + singlestat panel of 2 spans + text panel of 8 spans. 

On the picture I expected to see the panel "Up" and "Down" aligned.

![grafana_bug](https://cloud.githubusercontent.com/assets/135217/15423115/3fbf5cfe-1e7c-11e6-87fd-9288cd19c55c.png)

**Comment by thouveng** [comment]
And to add more informations:
I observed the same issue with Grafana version: 3.0.1, commit: v3.0.1+2-g549eb15
but not with Grafana version: 2.6.0, commit: v2.6.0

I'm using the same dashboards and the same configuration file for both versions.

**Comment by torkelo** [comment]
thanks for reporting this, fixed! 

One tip though is that you can create a new row and place panels in, a row is not really meant to wrap multiple "rows"

**Comment by thouveng** [comment]
Excellent... and pretty fast ;-). Yes I agree for multiple rows but in our case one row is dedicated to one service and we already have many dashboards so if we can keep the current structure it's better ;-).
Any idea when 3.0.3 will be available with the fix? I didn't see the roadmap on the site.

Thanks for the great and quick help

**Comment by torkelo** [comment]
I hope to release 3.0.3 on monday
