### ISSUE TITLE
I18n: Decide on what to do with automatic locale detection

### ISSUE THREAD

**Issue by joshhunt** [grafana/grafana#51133]
Currently, the backend reads the Accept-Language header the browser automatically sends and sets this value into the `locale` property on the user data.

https://github.com/grafana/grafana/blob/c2aee2b6dadcb7fad86e54a79d300b3abe36c062/pkg/api/index.go#L694-L701

I18n changes this to instead return the user/org/server preference, and no longer returns the Accept-Language locale. 

It should also be taken into account that internationalisation will, at least initially, only support a very small list of languages.

We need to consider, and decide:
 - currently, what is the `locale` property on `CurrentUserDTO` used for?
 - what is the impact of changing this to be different to the browser's Accept-Language?
 - should the UI language preference be different than what `locale` is currently used for? Should we have two different properties on `CurrentUserDTO`  for this?

**Comment by natellium** [comment]
@zsofiakomaromigrafana @joshhunt did we say for the moment we don't want to do anything? Should we close and reevaluate later on?
