### ISSUE TITLE
[Bug] Panel graph shows scribbling in certain unknown cases

### ISSUE THREAD

**Issue by mvadu** [grafana/grafana#5114]
Grafana : Latest stable 3.0.2, InfluxDB 0.11
Panel graph shows scribbling in certain unknown cases. See below for an example. This is repeatable on this machine, but if we zoom in to a specific time range, it shows normal data.
![image](https://cloud.githubusercontent.com/assets/8618235/15425727/eb5308ce-1ea7-11e6-8b74-5929943778cd.png)

Req: query?db=MyDB&q=SELECT percentile("ResponseTimeNinetiethPercentile", 90) FROM "Application_Transaction_Metrics" WHERE "BusinessTransaction" <> 'Others' AND "State" =~ /(California)$/ AND time > 1463551200s and time < 1463637600s GROUP BY time(5m), "State"&epoch=ms

Response: 
[response.txt](https://github.com/grafana/grafana/files/274435/response.txt)

Panel Json: 
[Panel.txt](https://github.com/grafana/grafana/files/274437/Panel.txt)

Zoom In to a time frame within the scribbled area:
![image](https://cloud.githubusercontent.com/assets/8618235/15426144/3a1fe966-1eaa-11e6-9c81-71f1ec208cf9.png)

**Comment by torkelo** [comment]
Looks like a bug in InfluxDB that is not properly sorting the resulting data points
