### ISSUE TITLE
Loki Dashboard - Table Transformation "Reduce" - Calculation "Last" error

### ISSUE THREAD

**Issue by kennie98** [grafana/grafana#51143]
**Describe the bug**

After querying Loki logs, I reached a table with 2 time stamps, and two group of values at these timestamps. I tried to keep the last timestamp, so I use transformation "Reduce", and calculation "Last".

Most of the time, the result is correct.
But sometimes the result becomes "First" instead of "Last"

Please check the attached screen captures for details.

**To Reproduce**
1. Started Loki (SHA or version)
2. Started Promtail (SHA or version) to tail '...'
3. Query: `{} term`

**Expected behavior**

"Last" should always be the timestamp later in time.

**Environment:**
 - Infrastructure: [e.g., Kubernetes, bare-metal, laptop]
 - Deployment tool: [e.g., helm, jsonnet]
Company Grafana Cloud

**Screenshots, Promtail config, or terminal output**
If applicable, add any output to help explain your problem.
![Loki-dashboard-table-reduce-last-error-1](https://user-images.githubusercontent.com/40083253/174712246-98581573-ecd6-4f54-8276-5c4318129506.png)
![Loki-dashboard-table-reduce-last-error-2](https://user-images.githubusercontent.com/40083253/174712259-7c9a6875-fb80-46b6-88f5-2cc7d86a0197.png)
![Loki-dashboard-table-reduce-last-error-3](https://user-images.githubusercontent.com/40083253/174712268-6bf6e1ff-7066-4f68-ae7a-360db1622b9a.png)
![Loki-dashboard-table-reduce-last-error-4](https://user-images.githubusercontent.com/40083253/174712277-ddb74447-d4ba-49ed-bc07-c5b1ead8c0c4.png)

**Comment by zuchka** [comment]
Thanks for creating this issue, @kennie98 

before you apply your `Series to rows; Last` transformation, can you [use the Grafana Panel Inspector](https://grafana.com/docs/grafana/next/panels/working-with-panels/navigate-inspector-panel/#navigate-the-grafana-inspector-panel) and share your data from the `data` tab? I think that could help us mock this up

**Comment by kennie98** [comment]
Thanks for the reply @zuchka 

As the data contain some of our customer's email addresses, it is not quite appropriate to share here. However, I think I have found a way to easily reproduce: if the "Last" timestamp is right at "00:00:00.000", then this problem will happen, such as:
![image](https://user-images.githubusercontent.com/40083253/175055547-184e1387-a984-43ea-96e3-6c5be99087fb.png)

**Comment by zuchka** [comment]
Hi @kennie98 

I am not able to reproduce this issue. Check out this dashboard with dummy data:

https://play.grafana.org/d/CMymPGzVz/51143?orgId=1&editPanel=2

are you still encountering this? if so, can you try to reproduce on play.grafana.org? ty
