### ISSUE TITLE
Feature: Prometheus Query Editor Make Over

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5117]
Rewrite Prometheus query editor with using the techniques and components used in graphite and InfluxDB query editors. Will make it easier to manage label filters, add nested functions (visualized as a chain of functions), edit function params etc.

**Comment by bergquist** [comment]
Kicking it down the road.

**Comment by torkelo** [comment]
![image](https://user-images.githubusercontent.com/10999/30027143-ead79472-917f-11e7-8dc8-28f2420ae277.png)

[video](https://twitter.com/grafana/status/898143069886980096?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fgrafana.com%2Fblog%2F2017%2F08%2F18%2Ftimeshiftgrafanabuzz-1w-issue-9%2F)
