### ISSUE TITLE
Labels for alerting rules (Google Cloud Monitoring data source) seem not to work

### ISSUE THREAD

**Issue by GedPL** [grafana/grafana#51184]
**What happened**:
I have an alert rule as shown on attached picture:

![image](https://user-images.githubusercontent.com/31762538/174839002-5cdf097f-e53f-4f26-a68f-545617b8d11a.png)

In Alerts Preview i see data with following labels:

![image](https://user-images.githubusercontent.com/31762538/174840618-81d61a59-40d1-4d4f-9926-7056b58b6364.png)

Now, I'm trying to use labels based on variables {{$labels.metric.label.device}} and {{$labels.metadata.system_labels.name}} in Summary section:

![image](https://user-images.githubusercontent.com/31762538/174843600-67c9a58c-a9b7-4e00-9033-dd0d52fb50c6.png)

Notification channel is email.
When I receive notification email I see:

![image](https://user-images.githubusercontent.com/31762538/174845743-3dd0cf15-a580-4311-b3e0-81f1dee2123b.png)

Question is why {{$labels.metadata.system_labels.name}} and {{$labels.metric.label.device}} show no value in Summary while they are correctly shown in Value and Labels sections ?

**What you expected to happen**:
Variables used above should be replaced with correct values.
Also I have almost the same alert rule for Prometheus data source and it works correctly.

**How to reproduce it (as minimally and precisely as possible)**:
Create an alert rule as shown above and send alert notification via email channel.

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: Google Cloud Monitoring
- OS Grafana is installed on: Red Hat Enterprise Linux 7
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins: none

**Comment by JohnnyQQQQ** [comment]
When having a dot in the name the golang template engine will interpret it as a separator. As the labels are a map you should be able to get the value by doing `{{ index $labels "metadata.system_labels.name" }}` instead.

**Comment by JohnnyQQQQ** [comment]
Checked again, `{{ index $labels "metadata.system_labels.name" }}` should work for your use-case, I used custom labels to test which are not part of the evaluation result, and therefore not in the payload. Let me know if it doesn't work.

**Comment by GedPL** [comment]
Checked and works fine with {{ index $labels "metadata.system_labels.name" }} !
Many thanks for quick response and solving my problem.
Really appreciate !
