### ISSUE TITLE
[New UI Component] Circle Bar Chart 

### ISSUE THREAD

**Issue by MaikiGirardi** [grafana/grafana#51186]
**Why is this component needed**:
This component is interesting to enable us to suit more information on screen. Like we saw on some vendors smartwatches these are very interesting charts that could provide us an improvement on our dashboards suiting more information with a simple component.
___
 - [x] Is/could it be used in more than one place in Grafana?
 Yes, it could be used for multiple purposes and for many tools.

**Where is/could it be used?**:
 1. It could be used in a replacement for bar chart in some situations
 2. Machine monitoring: CPU %, Memory %, Disk Usage %, etc.
 3. HTTP Response Status (Error, Info, Warning)
 4. HTTP Response Codes (200, 202, 404, 500)
 5. And so many other usage cases
___
- [x] Post screenshots possible.

![image](https://user-images.githubusercontent.com/20565056/174849847-03d89bba-7536-4d0a-bb94-514b9cbc1448.png)
![image](https://user-images.githubusercontent.com/20565056/174850858-c2a943e7-fe3d-4b54-9efe-7094d3387436.png)

- [ ] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [ ] Component has a story in Storybook.
- [ ] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [ ] It is extendable (rest props are spread, styles with className work, and so on).
- [ ] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [ ] Works with both light and dark theme.

**Documentation**

- [ ] Properties are documented.
- [ ] Use cases are described.
- [ ] Code examples for the different use cases.
- [ ] Dos and don'ts.
- [ ] Styling guidelines, specific color usage (if applicable).

**Comment by leeoniya** [comment]
> This component is interesting to enable us to suit more information on screen. Like we saw on some vendors smartwatches these are very interesting charts that could provide us an improvement on our dashboards suiting more information with a simple component.

how is this more space-efficient or easier to read than a horizontal bar chart? :thinking: seems like it has all the same problems of low information density of pie/donut charts. not saying we shouldn't do it, but i dont find current justification too compelling :)

![image](https://user-images.githubusercontent.com/43234/174855333-84b49be7-b74d-4238-a708-3e3bfe787e0f.png)

**Comment by MaikiGirardi** [comment]
Yes, I agree, looking closely it would be much harder to identify the origin that the data comes from when we have a lot of values. I will close that. Thanks for the view.
