### ISSUE TITLE
[Bug] Template variables won't refresh with more than 2 consecutive variables 

### ISSUE THREAD

**Issue by agaon** [grafana/grafana#5119]
We have a few dashboards that rely on multiple templating variables, each variable change changes the next template variable. This has worked perfectly on v2.6. 

After we upgraded to v3.0.2, it seems that any more than 2 template variables, the next ones won't auto update/refresh.

We have changed the refresh setting on all the variables to "On Dashboard Load" , but it didn't work.

![image](https://cloud.githubusercontent.com/assets/12067107/15433570/e6b41ee2-1e80-11e6-87b4-0f4378f90835.png)

**Comment by torkelo** [comment]
this has already been reported and fixed :) 

https://github.com/grafana/grafana/issues/5103
