### ISSUE TITLE
Improve mobile support

### ISSUE THREAD

**Issue by calben** [grafana/grafana#512]
Navigation is broken on mobile (and tablet) when editing graphs, disallowing returning to the primary dashboard.

**Comment by adamhamner** [comment]
+1 to mobile support.

**Comment by damm** [comment]
+1 I tend to use Grafana on my ipad alot; it works good but there's some scaling issues occasionally.

**Comment by Fox32** [comment]
I think it works quite well on a mobile device, at least for viewing some metrics. But I see the following issues:

* On large screens, moving the legend to the right is really useful, but I just doesn't make sense on a mobile device (to low resolution). One could detect the screen width and disable the right legend mode if it is to low.
* Table Panel is somehow broken, there is proper scrolling for the body, but the table headers are flowing outside of the layout.
* Can't access the save and manage buttons in the toolbar. But they aren't that neccessary for viewing.

**Comment by M-Sivanraj** [comment]
+1 to mobile support.

**Comment by ssenthil416** [comment]
Were can I find Android APK for Grafana

**Comment by carlbennett** [comment]
+1 mobile web support and possibly Android APK!!

**Comment by rileytg** [comment]
confirming only issue i have as a heavy mobile user is the saving and other buttons in nav when editing a dash

**Comment by carlbennett** [comment]
Agreed. Experience has actually improved since my last comment. A lot.

**Comment by calben** [comment]
Everything in the original comment is now working.
Seems time to close it!

**Comment by carlbennett** [comment]
![screenshot_20171110-144519](https://user-images.githubusercontent.com/592196/32677932-fcac79ee-c625-11e7-98d6-d8e4e327cd93.png)

**Comment by carlbennett** [comment]
This is what it looks like at present
