### ISSUE TITLE
[Bug] Template with multiple template dependencies only cascades on change of first dependency listed in WHERE clause

### ISSUE THREAD

**Issue by thunderstumpges** [grafana/grafana#5120]
Hello,

We just upgraded our Grafana server from 2.x to 3.0.2 
- What Grafana version are you using?
  ** 3.0.2
- What datasource are you using?
  ** Influx DB 0.10

We have several dashboards that use cascading (dependent) templates. In somecases we have the following scenario:

Template A (`SHOW TAG VALUES WITH KEY = A`)
Template B (`SHOW TAG VALUES WITH KEY = B WHERE A = '$A'`)
Template C (`SHOW TAG VALUES WITH KEY = C WHERE A = '$A' and B = '$B'`)

In this case, when I change the value of A, both B and C update. However when I change the value of B, C does NOT update. If I change the ordering of the WHERE clause in C to put B first:
 (`SHOW TAG VALUES WITH KEY = C WHERE B = '$B' and A = '$A'`)

Then C updates when we change B but NOT when we change A. 

I don't recall having this issue with 2.x, and I noticed it right away after the upgrade, so I think this must be a new problem.

**Comment by torkelo** [comment]
https://github.com/grafana/grafana/issues/5120

**Comment by thunderstumpges** [comment]
Huh? Duplicate of what bug? I tried to search for an existing one matching this. didn't see it. Sorry if I just missed it.

**Comment by thunderstumpges** [comment]
@torkelo did you mistakenly think this was a duplicate of itself or did you enter the wrong reference bug somehow?

**Comment by torkelo** [comment]
yes, sorry, wrong link, and also sorry for being so short, I thought you double posted the same issue twice, but someone opened the same issue 2 hours before. 

https://github.com/grafana/grafana/issues/5119

And here is the original issue that was fixed:
https://github.com/grafana/grafana/issues/5103

Fix will be included in 3.0.3 patch release on monday (and is included in 3.1 nightly builds)

**Comment by thunderstumpges** [comment]
Wonderful. Thank you! Sorry I didn't spot the duplicate before entering it.
