### ISSUE TITLE
When collapsing a row, the row will absorb any panel that is below it

### ISSUE THREAD

**Issue by ajenez** [grafana/grafana#51215]
**What happened**:

When I collapsed a row, the panel beneath it is absorbed into the above row.

**What you expected to happen**:

I expected the panel to stay as it's own piece rather than become part of the row above.

**How to reproduce it (as minimally and precisely as possible)**:

Create a row with at least one panel. Close that row. Create a panel and put it below the previous row. Open the row, then close it again and the panel will be absorbed into that row.

**Comment by zuchka** [comment]
Thanks for creating this issue, @ajenez 

this actually works-as-intended, at least for now. Please see this open issue and then this open discussion about hungry rows:
- https://github.com/grafana/grafana/issues/22368
- https://github.com/grafana/grafana/discussions/42308
