### ISSUE TITLE
LDAP integration: would like to specify multiple bind_dn to try for initial bind

### ISSUE THREAD

**Issue by dbcook** [grafana/grafana#5122]
To accommodate service accounts that have different OU's than our regular users, it would be nice to be able to specify more than one bind_dn that would be tried sequentially for the initial LDAP bind, perhaps something like this in ldap.toml:

```
[servers.ldap_bind]
bind_dn = "uid=%s,ou=People, dc=foo,dc=bar"

[servers.ldap_bind]
bind-dn = "uid=%s,ou=ServiceAccts,dc=foo,dc=bar"
```

This would avoid having to propagate plaintext credentials through our deployment tooling.  Hopefully this would be a fairly minor addition to `pkg/login/ldap.go`

**Comment by torkelo** [comment]
you can specify multiple LDAP servers (the root config object) to try. 

Or you use a search user for the initial bind and use the search_base_dns that does support an array
