### ISSUE TITLE
Origin not allowed after update to v8.4.6

### ISSUE THREAD

**Issue by Krungs** [grafana/grafana#51225]
**What happened**:
I updated my grafana a few days ago and now I wanted to change some dashboards. I can't do this because of an error "origin not allowed".

In Firefox I cant even login because of "origin not allowed"

**What you expected to happen**:
I expected that I can change my dashboards.

**How to reproduce it (as minimally and precisely as possible)**:
I can reproduce it every time I want to change something.

**Anything else we need to know?**:
I am using nginx as an docker container.
I have read some other issues but nothing helped.

**Environment**:
- Grafana version: 8.4.6
- Data source type & version: InfluxDB
- OS Grafana is installed on: Debian 10
- User OS & Browser: Windows on Chrome and Firefox
- Grafana plugins: -
- Others: -

**Comment by zuchka** [comment]
Thanks for creating this issue, @Krungs 

there was a breaking change regarding headers and reverse proxies with grafana 8.3.6.

Here is the fix:

https://github.com/grafana/grafana/issues/45117#issuecomment-1033842787

and the new sample config in the docs:

https://grafana.com/tutorials/run-grafana-behind-a-proxy/#configure-nginx
