### ISSUE TITLE
Docs feedback: /datasources/_index.md

### ISSUE THREAD

**Issue by mjseaman** [grafana/grafana#51235]
Some links on this page redirect back to this page. Broken?

**Comment by melgl** [comment]
Specifically, it appears the following data sources are all hyperlinked back to the same page:

- Alertmanager
- Elasticsearch
- Graphite
- Loki
- MySQL
- OpenTSDB
- PostgreSQL
- Prometheus
- Jaeger
- Zipkin
- Tempo
- Testdata

For example: [Alertmanager](https://grafana.com/docs/grafana/latest/datasources/)

**Comment by chri2547** [comment]
This issue has been resolved. Closing.
