### ISSUE TITLE
Logs: Rename files using snake_case to camelCase to follow convention

### ISSUE THREAD

**Issue by ivanahuckova** [grafana/grafana#51230]
Some files that are maintained by logs squad have snake_case name. According to convention https://github.com/grafana/grafana/blob/765b995b1bcafe8b94d0bbe53737ea6c751d63c9/contribute/style-guides/frontend.md#file-and-directory-naming-conventions we should use `camelCase`. We should go trough the files and update names, so they use correct convention.

Files in `grafana/grafana` repo
- [ ] `public/app/plugins/datasource/loki`
- [ ] `public/app/plugins/datasource/elasticsearch`
- [x] `public/app/core/logs_model.ts` https://github.com/grafana/grafana/pull/51468
- [ ] Files in `grafana/opensearch-datasource`

Maybe there are other files related to logs and log datasources

**Comment by user10x** [comment]
@ivanahuckova I am no front end expert but seems like it's an find and replace I could do in my editor. Here's gist  on how the diff looks on  public/app/core/logs_model.ts for two variables LIMIT_LABEL and COMMON_LABELS. Lemme know if this is what you were expecting

https://gist.github.com/user10x/063e59923d24a6852a11c40e70f57752

**Comment by ivanahuckova** [comment]
@user10x this issue was mostly aimed at the names of files. E.r. `logs_model.ts` should be `logsModel.ts`.

**Comment by user10x** [comment]
@ivanahuckova https://github.com/grafana/grafana/pull/51406/files maybe should open a second PR for the remaining changes?

**Comment by ivanahuckova** [comment]
I am closing this and instead I'll create individual issues for each files.
