### ISSUE TITLE
Template queries issue with Elastic search

### ISSUE THREAD

**Issue by chaithrar** [grafana/grafana#5123]
Hi,

I am using 2.5.0 version of grafana with elastic search (1.7.2)

I am using below template queries to list all the hosts for a given appid to get the data from ES.

{"find": "terms", "field": "appid"}  -- The name for this tamplate is "AppId"

**This is first template query which returns appids as below** 

/apt/uwwwtest 
/test-node1 
/app-temp-node3

**The second template query looks as below.**

{"find": "terms", "field": "hostip", "query":"appid:$AppId"} -- The name of this template is "Hosts"

But I get an error when executing the second template query. Is it because "/" present in the first template query result.
_"Template variables could not be initialized: Cannot read property '1' of undefined"_

How can I use template queries on data with special character

**Comment by torkelo** [comment]
this is fixed in 3.0
