### ISSUE TITLE
[Feature Requests] Allow Mathematics to be applied to template variables

### ISSUE THREAD

**Issue by drewboswell** [grafana/grafana#5125]
Having the ability to perform even basic mathematics on number type template variables would enable people to scale graphs, limits, etc.

Personally I would see an instant benefit combining this with using variables in the singlestat-gauge limits (OK, Warn, critical), I could scale those limit numbers based on the time period in seconds.

Just the ability to use */+- would be a start , though maybe one could enter a formula with "x" as the value tu mutate. I.e.: "log(x**2)"

And of course the use of variables inside would further be useful, and the above would apply to all values listed in the template variable.

**Comment by JamesGalt** [comment]
Would be useful for time range template variable. so we can have a panel with $interval/2 or sth like this.

**Comment by rnsc** [comment]
Is this something that is going to be added in the future?

**Comment by oandewaal** [comment]
I am aslo still very keen on this, will this feature be enabled?

**Comment by tomminux** [comment]
Any news about this?

**Comment by trallnag** [comment]
I agree that this feature would add value to Grafana. In combination with Grafanas `$__interval` or `$__rate_interval` and Prometheus this would finally allow us to seamlessly switch between high resolution with short averages and long-term trend views. Right know I have to either maintain two dashboards or (mis)use the min step parameter.  This works fairly well, but it does not allow me to have a big rate range and a small step at the same time
