### ISSUE TITLE
Clear text password in journalctl

### ISSUE THREAD

**Issue by pbirokas** [grafana/grafana#5126]
Hi,

I 'm quite new to this but found today in my journalctl something thats a no go!

My Server:
CentOS 7.2
Grafana 3.0.2
Graphite Backend
WorldPing Plugin

After I install Woldping and try to add some endpoints, got an auth error.
Checking my journalctl i found this:

[...] grafana-server[13508]: 2016/05/21 10:45:47 [I] setting key Authorization value Bearer "clear text PW"

Not sure if this is the right place to post this issue, but in this situation I can't use grafana/worldping.

Hope this will get fixed soon.

Thanks in advance.

**Comment by torkelo** [comment]
ah, thanks for bringing this to our attention. This is the wrong logging level. It should be logged with Trace level.

This fix will be included in today's release of Grafana 3.0.3, but you can change the log level to Warn as a temp work around.
