### ISSUE TITLE
Explore: Remove support for compact URLs

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#51276]
Design Document https://docs.google.com/document/d/1YYljgT52u30AbmlKpFjl4s0MC6fZg2SnPIyAAn0aQks/edit

- [x] Add a deprecation notice ([Done](https://github.com/grafana/grafana/pull/50873))
- [x] #51277
- [x] #59686
- [ ] #60904
- [ ] Disable compact URLs permanently (After we decide its appropriate based on usage tracking of the notification and feedback of feature flag)

**Comment by mllab-nl** [comment]
Would be nice to remove the nice warning message. It does bring a lot of user confusion

**Comment by mllab-nl** [comment]
Thank you !

**Comment by gelicia** [comment]
This will be tackled in other URL state work
