### ISSUE TITLE
Error rendering dashboard after upgrading to Grafana 9

### ISSUE THREAD

**Issue by pedrocadiz13** [grafana/grafana#51271]
**What happened**:

The following error message is displayed when navigating to Grafana home page:

TypeError: Object(o.getColorForTheme) is not a function. (In 'Object(o.getColorForTheme)(l,i)', 'Object(o.getColorForTheme)' is an instance of Object)

t@
WithTheme(undefined)

**What you expected to happen**:

Dashboard to be displayed.

**How to reproduce it (as minimally and precisely as possible)**:

Error started after upgrading to Grafana 9.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.1
- Data source type & version: 
- OS Grafana is installed on: Raspbian Linux 10
- User OS & Browser: Mac OS 12.4, Safari
- Grafana plugins: DK.
- Others:

**Comment by CardenPool** [comment]
Same error here in the same conditions.

**Comment by pedrocadiz13** [comment]
It was an old plugin, I had grafana-clock-panel and snuids-trafficlights-panel. Used 'grafana-cli plugins update-all' which updated both and fixed.

Thanks for your help.

**Comment by CardenPool** [comment]
> It was an old plugin, I had grafana-clock-panel and snuids-trafficlights-panel. Used 'grafana-cli plugins update-all' which updated both and fixed.
> 
> Thanks for your help.

Thanks, you made my day! To solve the issue from my side, "update-all" was not enough. Reinstalling the clock-panel was the key. 

`sudo systemctl restart grafana-server.service`

**Comment by bigjohns97** [comment]
> It was an old plugin, I had grafana-clock-panel and snuids-trafficlights-panel. Used 'grafana-cli plugins update-all' which updated both and fixed.
> 
> Thanks for your help.

Just noticed this on my setup and was able to find this thread in under a couple of minutes, what a time we live in.
