### ISSUE TITLE
[Bug] Grafana with Firefox on Linux shows scrollbar where it should not

### ISSUE THREAD

**Issue by mar-v-in** [grafana/grafana#5128]
Grafana 3.0.1 (happens on play.grafana.org "client side full page load" graph with legend table), Linux, Firefox 46 (not seen on Firefox/Windows or Chrome/Linux).

see http://i.imgur.com/s8XYEcA.png

This is due to `.graph-legend-table { overflow-y: auto; }`. Setting `overflow-y: hidden` will hide the scrollbar but I did not test for any unwanted impact.

**Comment by torkelo** [comment]
can't replicate on Firefox 44 on linux :(

**Comment by RalfJung** [comment]
This is probably related to FF switching to GTK3 with 46 (or was it 45?).

**Comment by torkelo** [comment]
is this still an issue?

**Comment by RalfJung** [comment]
Yes, I am still seeing this with Firefox 48 (the Debian-compiled version) and Grafana `3.1.0-1468321182`.

**Comment by torkelo** [comment]
this might be fixed in 4.1 / master
