### ISSUE TITLE
Alerting: return structured response from preview endpoint

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#51319]
**What happened**:

The current preview endpoint (`/api/v1/rule/test/<grafana | datasourceUID>`) does not return a very structured response that enables us to visualize labels and values during the preview step in the alert creation.

The JSON response below encode this information in a stringified format.

This would enable us to move forward with https://github.com/grafana/grafana/issues/45306

<details>
<summary><strong>JSON response</strong></summary>

```json
{
	"instances": [
		{
			"schema": {
				"name": "evaluation results",
				"fields": [
					{
						"name": "cpu",
						"type": "string",
						"typeInfo": {
							"frame": "string"
						}
					},
					{
						"name": "State",
						"type": "string",
						"typeInfo": {
							"frame": "string"
						}
					},
					{
						"name": "Info",
						"type": "string",
						"typeInfo": {
							"frame": "string"
						}
					}
				]
			},
			"data": {
				"values": [
					[
						"0",
						"1",
						"2",
						"3",
						"4",
						"5",
						"6",
						"7"
					],
					[
						"Normal",
						"Normal",
						"Normal",
						"Normal",
						"Normal",
						"Alerting",
						"Normal",
						"Normal"
					],
					[
						"[ var='B' labels={cpu=0} value=0.0029190840585508982 ], [ var='C' labels={cpu=0} value=0 ]",
						"[ var='B' labels={cpu=1} value=0.002122970224400649 ], [ var='C' labels={cpu=1} value=0 ]",
						"[ var='B' labels={cpu=2} value=0.0013268563902504096 ], [ var='C' labels={cpu=2} value=0 ]",
						"[ var='B' labels={cpu=3} value=0.0018575989463505732 ], [ var='C' labels={cpu=3} value=0 ]",
						"[ var='B' labels={cpu=4} value=0.004693349671568137 ], [ var='C' labels={cpu=4} value=0 ]",
						"[ var='B' labels={cpu=5} value=0.009553366009802937 ], [ var='C' labels={cpu=5} value=1 ]",
						"[ var='B' labels={cpu=6} value=0.0013268563902504096 ], [ var='C' labels={cpu=6} value=0 ]",
						"[ var='B' labels={cpu=7} value=0.0018575989463505734 ], [ var='C' labels={cpu=7} value=0 ]"
					]
				]
			}
		}
	]
}
```
</details>

**What you expected to happen**:

The response could return the labels, reference and values separately.

**Comment by joeblubaugh** [comment]
Note that the format Gilles is using here in his example is a data frame response. I've been playing with those lately, so this might be good for me to take on.

**Comment by gotjosh** [comment]
This is not as easy as it looks @joeblubaugh I think.

There are a couple of things to uncover as the format specified by Gilles only relates to classic conditions, the expressions evaluation format is already structured.

So it poses the questions:

1. Is the expression frame format already acceptable or are you expecting more changes to that too? Is there a design that we could take a look at?
2. The "unstructured format" described here, is the `valueString` which I think can be removed entirely after #46971 - The belief back when we started capturing values was that is not possible to capture values for classic conditions. Now that is possible, I think we should show values for all alerts - so I'm guessing you would like the value to be included in the response?

It's important to note that the same alert query can be applied to both classic conditions and expressions - they would produce a different result. So while unifying the response format for the evaluation is possible, we'd need to make sure we display them differently on the frontend and specifically in the alert preview.

It also depends on what we consider a "preview" - would it include custom labels defined by the user? What about annotations? Should we show them expanded or unexpanded?

I can appreciate this comment being very meta, but I think that it's important that we nail the alert preview so I'd love if we could spend a tiny bit of time thinking about the experience.

For the sake of transparency, I started writing the above but then quickly realised that without examples my message might be hard to get across. I had a quick sync with @gillesdemey and @konrad147 to show them the different examples and problems that I think alert preview could solve.

There were some items that were clear from that conversation:

- Yes to custom labels in the response that get taken from whatever the user has input in the form, and show how they would affect the alert instance.
- `__value__` as the value that the instance has 
-

**Comment by gotjosh** [comment]
Finally, I don't want my comment leading to inaction but I do want us to solve the pain points that I have (and our customers probably do too) if returning a more structured response for the labels of a classic conditions helps now then we can do it in a heartbeat. However, it's not clear to me how that helps.

**Comment by joeblubaugh** [comment]
I'd like to see any preview UI design discussions happen over on #45306, so they're collected in one place. My own two cents are that we should essentially evaluate the condition as though it were being handled by the alert scheduler, including augmenting it with any user-defined labels or annotations *before* it's sent to an alertmanager. It sounds like that's the agreement that came out of your conversation with Gilles and Konrad.

"In general" I'd like to see a preview API that represents states as data frame timeseries, similar to the approach we might take with Alert State History API (#51531) so that we can build similar components to represent them in the UI, whether that's timelines, tables, etc. Retroactive previews are mentioned in [the comment ](https://github.com/grafana/grafana/issues/45306#issuecomment-1038922646)on #45306, and I think there's an opportunity to build an API that can support that. The "instant preview" case would return one row, with a frame per instance. Retrospective previews eventually returning multiple rows, one for each evaluation or state change.

I think there are only small differences between classic conditions and other expression types here - you can have any number of refIDs, you have the refID that is being evaluated for alerting - which is 0/1 for classic conditions, and for quite a few other alerting queries.

cc @gillesdemey @konrad147

**Comment by yuri-tceretian** [comment]
Currently, I am working on an evaluation API endpoint (as part of the external multitenant ruler) and I have the same dilemma: 
- whether use data frames (precisely QueryBackendResponse), and therefore the endpoint will be pretty similar to the API endpoint `/api/ds/query` that is used by Explore,
- create a new response format that closely resembles what the scheduler consumes (i.e. eval.Results).

I think that the purpose of the data frames is to provide a unified format of heterogeneous data (time series, vectors, etc) that can have a random number of fields with random types of values. 
However, the purpose of the rule preview (as well as the eval endpoint I mentioned above) is to provide the result of the rule evaluation which format is pretty defined: generally, it is a collection of objects like:
``` json 
{
    "labels": {
        "label1": "label-value",
        "label2": "label-value2",
        ... 
    },
    "exceedsThreshold": true,
    "value": <some_scalar>,
    "metadata":  <can_contain_results_of_every_stage_of_evaluation>
}
```

This test API can be generalized to just evaluation of a rule's queries + conditions + a collection of arbitrary labels that can be expanded based on the results. Therefore the request will be something like 

```json
{
    "queries": [<a collection of queries and expressions each has RefID>],
    "condition":  "<RefID of the expression that calculates the threshold>",
    "labels": {<a map of arbitrary labels that need to be expanded and included to the each result above>}
}
```

Ideally, I would like eval API I am working on and test API be served by the same endpoint.

**Comment by joeblubaugh** [comment]
I think a "well known schema" is perfectly fine for a Data Frames API - we could even propose adding an alerting-specific one for https://github.com/grafana/grafana-plugin-sdk-go/tree/main/data/contract_docs

Given that "preview" is essentially "eval" it sounds good to me that we use the same endpoint eventually. We could point the existing route to the eval controller or just switch the frontend over directly to the new endpoint.

The attraction of using data frames in both the history and the preview APIs is that it lets the frontend code use the same processing functions and share API components. With a fairly simple extension, you can also do "retrospective previews" that can tell you whether an evaluation would have alerted in the past. Do you think that's a capability that you need for the eval endpoint you're working on? It's probably something we could incorporate as optional parameters that a caller can decide whether to use.

I view the history and preview APIs as primarily serving the Grafana UI (at least for now) so I think the effect they have on frontend code is most important to me.

**Comment by gotjosh** [comment]
> I think there are only small differences between classic conditions and other expression types here - you can have any number of refIDs, you have the refID that is being evaluated for alerting - which is 0/1 for classic conditions, and for quite a few other alerting queries.

I'm not sure about this (and it's what my original comment was trying to expand on - apologies for my poor choice of words) - fundamentally, there's plenty of difference between how previous alerts worked and how new alerts worked. Now, with the recent string of changes, there's an avenue to unify a bit the exposition format (API response described above) but it'll require some work and understand about what you get with the different types of conditions.

**Comment by gotjosh** [comment]
To be clear, I agree with this principle:

> Ideally, I would like eval API I am working on and test API be served by the same endpoint.

As long as we figure out how the different edge cases (classic vs expressions) are handled.
