### ISSUE TITLE
[Feature Request] Shortcut to share a link

### ISSUE THREAD

**Issue by grobie** [grafana/grafana#5132]
One of the most common actions in our dashboard usage is to share links to specific time ranges in order to discuss interesting data, outages, etc.

Background: In promdash that was very easy as all user changes were always reflected in the URL. Changing the time range or template variables added the appropriate parameters to the URL in the address bar so that it could just be selected and copied.

It would be great to support a workflow to copy a link of the dashboard I'm currently looking at into the buffer only by using shortcuts. One option could be to update the URL upon changes of timerange+variables so that the normal browser shortcuts `Ctrl+l` + `Ctrl+c` already work (could be a user settings feature). The current link sharing dialog could also be made more accessible by providing a shortcut to open it like `l`. The exporting feature already has its own. Inside of the dialog the link should already be selected and the dialog should be closable with `Esc`. Then `l`, `Ctrl+c` + `Esc` would support the workflow.

**Comment by bergquist** [comment]
Since https://github.com/grafana/grafana/commit/a81806d3d08b15ff08486a6298cb7f38e2f11951 from and until are put in the url and copy pasteable.

**Comment by grobie** [comment]
Oh great! In the same line of reasoning, I assume support for manipulating
the URL upon change of template variables is going to be added as well?
On May 31, 2016 9:58 AM, "Carl Bergquist" <notifications@github.com> wrote:

Since a81806d
<https://github.com/grafana/grafana/commit/a81806d3d08b15ff08486a6298cb7f38e2f11951>
from and until are put in the url and copy pasteable.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/grafana/grafana/issues/5132#issuecomment-222715259>,
or mute
the thread
<https://github.com/notifications/unsubscribe/AAANaBdpMfLh1P1T2Oo7gKX7Hk-QkoFJks5qHEyggaJpZM4Ij7nd>
.

**Comment by bergquist** [comment]
yes :) thats been added as well.
