### ISSUE TITLE
Alerting: Alertmanager configuration status endpoint

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#51321]
To proceed with https://github.com/grafana/grafana/issues/49212 we would need a new endpoint / augment an existing endpoint to figure out of Grafana has been configured to _only_ use an external Alertmanager.

**Comment by grobinson-grafana** [comment]
Can we use `api/v1/ngalert/admin_config`? I set up a Hosted Grafana with one external Alertmanager:

```
{"alertmanagers":["https://alertmanager.example.com"],"alertmanagersChoice":"external"}
```

and if I set to use the both Alertmanagers:

```
{"alertmanagers":["https://alertmanager.example.com"],"alertmanagersChoice":"all"}
```

and if there are two or more Alertmanagers:

```
{"alertmanagers":["https://alertmanager1.example.com", "https://alertmanager2.example.com"],"alertmanagersChoice":"all"}
```

**Comment by gillesdemey** [comment]
Yep that's the one, but I believe administrator privileges are required to access that route which makes it unsuitable to use for displaying a warning to non-administrator users.

**Comment by grobinson-grafana** [comment]
I talked with @gotjosh about whether we could use the same data that we use to populate the Alertmanager dropdown menu to also communicate the Alertmanager choice. One thought was that we could add a boolean field to each datasource to hint at whether it has been configured to receive alerts. However, having looked into this further I am not sure this achievable as datasource permissions can mean some, or even all Alertmanagers, are not visible to certain users.

We could put the choice in `grafanaBootData`, which I understand is also where we read the list of datasources. However, I don't think `grafanaBootData` is updated unless the page is reloaded, which could be an issue?

The other options would be to add a field to the response of `/api/datasources`, or add a new endpoint.
