### ISSUE TITLE
GLDS- Storybook; Add Controls — Epic

### ISSUE THREAD

**Issue by JoaoSilvaGrafana** [grafana/grafana#51330]
Storybook at the moment is quite inconsistent in the level of documentation of components and the existence of controls. This needs to be cleaned up to become consistent within itself and also with Figma.

Tasks:
- [x] Compile list of issues around storybook components documentation/controls

Stories missing controls, some of these might also need cleaning up so that the controls can work properly:
  - [x] #54161
  - [x] #54166
  - [x] #54167
  - [x] #52617
  - [x] #54168
  - [x] #54957
  - [x] #54170
  - [x] #54958
  - [x] #54171
  - [x] #54173
  - [x] #54210
  - [x] Add controls to `Legend` story
  - [x] #51622
  - [x] #51782
  - [x] #54221
  - [x] #54798
  - [x] #54799
  - [x] #52868
  - [x] #54222
  - [x] #53039
  - [x] #54631
  - [x] #53458
  - [x] #53375
  - [x] #53218
  - [x] #53453
  - [x] #54630
  - [x] #54628

When adding controls, if you find a story that has a lot of different examples of the component in the same view (i.e. https://developers.grafana.com/ui/latest/index.html?path=/story/overlays-alert--examples), please leave it there and make sure it is called "Examples" and has no controls attached to it. You can then create a different story that shows only a single instance of that component and has controls attached to it.

To create an issue based on this look at the example of #51622, just add some similar description, add it to the same project as this epic and the tags `area/storybook`, `area/design-system`, `type/chore` and `good-first-issue` if you won't be picking it up immediately.

**Comment by sonjafeitsch** [comment]
Hi @JoaoSilvaGrafana , is it possible to contribute something on this topic? Last week I did #50660 and I noticed that the controls don't exist everywhere. I am very interested in design systems, storybook and component development with React so I would like to contribute on this topic 😊 but I am not quite sure what's the best way for me to start. Can you help me?

**Comment by JoaoSilvaGrafana** [comment]
Hi @sonjafeitsch ! Thanks for your contributions and for your interest in helping with this 😄 
We are currently on the process of compiling a list of documentation / controls that are missing for the components. 
We don't have a full list of issues created for all of them yet, but would be very appreciative of any help! For instance the `Tag` or `TagList` components don't have any controls, I can create issues for those for you if you think that would be something that you'd want to help with?

**Comment by sonjafeitsch** [comment]
@JoaoSilvaGrafana nice, thank you for the list and the other informations about this topic 😊

**Comment by ashharrison90** [comment]
@JoaoSilvaGrafana another task we should do is to migrate from using the custom `UseState` component we created (see e.g. https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/RefreshPicker/RefreshPicker.story.tsx#L30) to using the `@storybook/client-api` package.

this lets us keep the control state in sync with the component state. super clean.

here's a commit where i've added it to @eledobleefe's PR: https://github.com/grafana/grafana/commit/4c006cf7f1848acf296ff1fb360aef219f0a3ebe

see https://github.com/storybookjs/storybook/issues/3855#issuecomment-660158622

**Comment by sonjafeitsch** [comment]
@JoaoSilvaGrafana I would like to have a look at the `TagList` story. Can you create an issue and assign it to me? ☺️

**Comment by orarbel** [comment]
Hi all 👋 

Our team is working on a Storybook to Figma solution with auto-layout and native variants. It's working great, and we'd love to work with you closely to get Grafana's Storybook synced with Figma.

Let me know if relevant :)

**Comment by torkelo** [comment]
@JoaoSilvaGrafana i don't think controls are that useful , showing component in all its states / use cases are 10 times more useful than a single component where you have to toggle a bunch of controls  to explore what it can do, that is terrible both from a component consumer and developer so what ever you do don't remove the actual useful stories that have many examples of different component states

**Comment by JoaoSilvaGrafana** [comment]
Don't worry @torkelo these tasks aren't meant to be to remove any other stories, there's space for both types :)

**Comment by timagixe** [comment]
Hey @JoaoSilvaGrafana, I would like to help with `Add controls to UnitPicker story` and `Add controls to PanelChrome story`. Could you please create respective issues and assign them to me? Thanks.

**Comment by JoaoSilvaGrafana** [comment]
Hi @timagixe thank you for helping out with these! I have created those tasks now, could you please comment on the tasks themselves when you want to pick them up and I'll assign you to them? 😄

**Comment by JoaoSilvaGrafana** [comment]
@timagixe created both of those, please comment on the tasks when you start working and I can assign you to them 😃

**Comment by timagixe** [comment]
@JoaoSilvaGrafana, could you please create issues for `Add controls to Segment story` and `Add controls to FieldSet story`. I would like to work on those two. Thank you in advance! 🙌

**Comment by gqio** [comment]
Hello, story.to.design team member here.

I made this https://github.com/grafana/grafana/pull/55023 to help you on this particular bullet point

> Figure out why Storybook does not work with [Story-to-design](https://story.to.design/)

The team effort on this PR is huge 👍 and definitely helps story.to.design to work seamlessly with this new approach aligned with the Storybook controls.

I can definitely help if you need anything from our team to figure out what is missing and what should be fixed (on our side or on yours) 🤗

**Comment by ashharrison90** [comment]
@JoaoSilvaGrafana can we close this now? 😱

**Comment by JoaoSilvaGrafana** [comment]
Yes it seems like we can!! 🎉 🎉
