### ISSUE TITLE
SQL query editor and sql data source form fields are missing

### ISSUE THREAD

**Issue by danielband** [grafana/grafana#51340]
**What happened**:

The interface to add sql data sources (mysql, pgsql, mssql) and the query editor vanished starting from 8.5.0. The same happens in the explore feature. Queries that were created in the past are getting executed and displayed. 

![query](https://user-images.githubusercontent.com/72872468/175354750-4654e071-616a-475d-bead-3d06b6b551e0.png)
![datasource](https://user-images.githubusercontent.com/72872468/175354759-7498e349-55be-4e33-b498-d6f834ec694e.png)

**What you expected to happen**:
The required form fields to be displayed

**How to reproduce it (as minimally and precisely as possible)**:
Add a new sql data source, edit a panel, create a new panel or use the explore feature

**Anything else we need to know?**:

**Environment**:
- Grafana version: starting from 8.5.0
- Data source type & version: all sql data sources
- OS Grafana is installed on: Debian 11
- User OS & Browser: Firefox 102.0b9 or Chrome 103.0.5060.53 MacOS 12.4
- Grafana plugins: Only core plugins

**Comment by zuchka** [comment]
Thanks for creating this issue, @danielband 

do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

in either case the teams will need more details to attempt to reproduce your issue 👍

**Comment by danielband** [comment]
@zuchka thanks for the reply. In the sandbox it works fine. The issue appears when I upgrade from 8.4.* or when I install a  grafana 8.5.* upwards on a new VPS Server. For both cases I use the apt installer. Did something change, that I need to configure? I will try to use the docker image and setup grafana in my Vagrant VM.

**Comment by zuchka** [comment]
still blocked on this, @danielband.

will close this for now, but happy to reopen if still blocked.
