### ISSUE TITLE
bug in isMsResolutionNeeded method

### ISSUE THREAD

**Issue by godfreyhe** [grafana/grafana#5136]
the datapoints to show are like [[value, timestamp], [value, timestamp]], but the method isMsResolutionNeeded in time_series2.ts gets timestamp from index 0, which should be 1.

  isMsResolutionNeeded() {
    for (var i = 0; i < this.datapoints.length; i++) {
      if (this.datapoints[i][0] !== null) {
        var timestamp = this.datapoints[i][0].toString();
        if (timestamp.length === 13 && (timestamp % 1000) !== 0) {
          return true;
        }
      }
    }
    return false;
  }

**Comment by torkelo** [comment]
@utkarshcmu can you verify this?

**Comment by utkarshcmu** [comment]
@godfreyhe Thanks for reporting this. Its a bug. I assumed index 0 was timestamp(even in the tests I wrote). :(

Fix is here but looks like Github servers are slow right now. Not able to create a PR right now. Will create a PR as soon as Github allows me to do so.
https://github.com/grafana/grafana/compare/master...utkarshcmu:bug-fix

**Comment by utkarshcmu** [comment]
Created PR #5142

**Comment by utkarshcmu** [comment]
Thanks for merging #5142 , this issue can be closed now. :)
