### ISSUE TITLE
Adhoc Filter: Wrong time range for Elasticsearch

### ISSUE THREAD

**Issue by jlaudenbach** [grafana/grafana#51381]
**What happened**:

When using adhoc filter with Elasticsearch data-source, the filter options for given field X are mostly empty - `No Options found`.
(There are only options for fields which datasets are up to 6 hours old.)

**What you expected to happen**:

For a given time range, all options should be in the adhoc filter which are found in Elasticsearch query.
This was the case in Grafana version 6.4

**How to reproduce it (as minimally and precisely as possible)**:

* Set up an Elasitsearch index (Elasticsearch version 7.10+).
* Create a data-source with this index.
* Create a new dashboard with an adhoc filter for this index.
* Entries in index have to be at least 6 hours old.
* Select a index field as filter -> click on `select value` 
![image](https://user-images.githubusercontent.com/14938512/175548304-8b819f0e-6e60-4410-be27-fa46a17d037f.png)

You might think now there is just no value for this field available, but this is not the case, as you see in the table of the attached image. The problem is, that the Elasticsearch query for filter values only looks for the Elasticsearch entries of the past 6 hours.

**Anything else we need to know?**:

I also opened an grafana community issue:
https://community.grafana.com/t/adhoc-filter-do-not-find-options/60379

Here again what I found out in my research:

The request payload to find the filter options loos like this:
```
{"search_type":"query_then_fetch","ignore_unavailable":true,"index":"my_index"}
{"size":0,"query":{"bool":{"filter":[{"range":{"general.data_source_time_field":{"gte":"1654660925962","lte":"1654682525962","format":"epoch_millis"}}}]}},
"aggs":{"1":{"terms":{"field":"my_field","size":500,"order":{"_key":"asc"}}}}}
```
As you can see the query time-range is quite short:
```
"filter":[{"range":{"general.data_source_time_field":{"gte":"1654660925962","lte":"1654682525962","format":"epoch_millis"}
```
Make Unix time-stamp human readable shows:

    1654670375696 → Wednesday, 8. June 2022 06:39:35.696
    1654691975696 → Wednesday, 8. June 2022 12:39:35.696

So the time range is 6 hours and not related in any way to the range choose in dashboard.

Now, if there is no  entry in my_field for the last 6 hours (which is common in my case), Elasticsearch will give an empty result which leaves to an empty drop down for adhoc filter values.
Even if there would be some entries in the last 6 hours, the shown options will not correlate with the dataset of the chosen time range.

**Environment**:
- Grafana version: 8.5.5
- Data source type & version: Elasticsearch 7.15
- OS Grafana is installed on: Sorry, not sure. Some Linux
- User OS & Browser: Chrome
- Grafana plugins: No
- Others:

**Comment by gabor** [comment]
hi @jlaudenbach , it's fixed now, will be available in grafana 9.2.0

**Comment by gabor** [comment]
hi @jlaudenbach sorry, no, this is a change in functionality technically, so we are only doing it in the next major-version release (9.2.0)

**Comment by jlaudenbach** [comment]
Ah, OK. 
But isn't it more an error, since it worked on Grafana version 6.4 but not in Grafana Version 8.

**Comment by gabor** [comment]
i'm sorry @jlaudenbach , i understand it would be useful for you to have this in grafana8, but even if we consider this a bugfix, we don't backport non-security bugfixes so far back (considering since then both grafana9.0 and grafana9.1 has been released).

**Comment by jlaudenbach** [comment]
To consider only security bug-fixes sounds reasonable for me.
Thank you again for your support.
