### ISSUE TITLE
Improvement: Support dashed lines

### ISSUE THREAD

**Issue by jonathanrelf** [grafana/grafana#514]
In addition to selecting the colour of a line, I'd like to be able to choose a line to be a Dashed Line. 
Graphite supports a dashed() function and flot supports dashed lines ( e.g. http://jsfiddle.net/pmorch/bJwY8/1/ )

**Comment by TotallyInformation** [comment]
This is the only open request for this feature - surely it can be easily implemented?

**Comment by daniellee** [comment]
Closed by #5491
