### ISSUE TITLE
Grafana graph snapshot sharing not working!

### ISSUE THREAD

**Issue by ningxie1991** [grafana/grafana#5140]
When I click share on a graph and select snapshot sharing => local snapshot, an then click on the link, the snapshot does not show graph lines and there's an error warning icon on the top left that says InfluxDB Error Response: missing required parameter "q". I have 10+ queries running behind the graph. Is it because the queries are too slow? But what's the error about? 

I'm using InfluxDB v0.11 and Grafana v2.6.

Thanks!

**Comment by torkelo** [comment]
yes, could be due to slow queries, snapshot requires that all queries finish within 4 seconds.
