### ISSUE TITLE
db error when deleting default dashboard..

### ISSUE THREAD

**Issue by ThomasADavis** [grafana/grafana#5141]
Thank you for helping us make Grafana even better!

To help us respond to your issues more quickly, please make sure to add as much information as possible.

If this issue is about a plugin, please open the issue in that plugin's repository.

Start your issue's title with [Feature Request] / [Bug] / [Question] or no tag if you're unsure. Also, please be aware that GitHub now supports uploading of screenshots; look at the bottom of this input field.

Please include some basic information:
- What Grafana version are you using?

3.0.3

- What datasource are you using?

elasticsearch.

- What OS are you running grafana on?
Centos -7.1

- What did you do?

Deleted the default dashboard for the user.

- What was the expected result?

no more default dashboard.

- What happenend instead?

db error

Problem!
Failed to get slug from database

from the logfile:

2016/05/23 08:59:08 [dashboard.go:171 GetHomeDashboard()] [E] Failed to get slug from database: Dashboard not found
2016/05/23 08:59:08 [I] Completed 128.3.135.160 tdavis "GET /api/dashboards/home HTTP/1.1" 500 Internal Server Error 46 bytes in 777us

Now I am trying to figure how to either fix the sql record, or reload the default db.

**Comment by ThomasADavis** [comment]
Yea, I found and changed the sqlite db to fix this.

It is in the preferences table.

So it's back up and working.

**Comment by torkelo** [comment]
if you delete the dashboard you configured as your home dashboard, it will result in an error. You can change home dashboard in org or user profile settings

**Comment by ThomasADavis** [comment]
All I get is a blank screen, with a red box stating as above.  I also tried logging in as Admin, and it did it also.

**Comment by torkelo** [comment]
ah, your right, thought the regular "dashboard not found" empty dashboard would show (with that error), not a blank screen. This is indeed a bug that should be fixed!
