### ISSUE TITLE
Create grafana contact point with Alerting provisioning API.

### ISSUE THREAD

**Issue by ktarnaris** [grafana/grafana#51423]
**What happened**:
After some [posts](https://grafana.com/docs/grafana/latest/developers/http_api/alerting_provisioning/) (~ 10-20) i did notice some latency in response time, which on every post the time is increasing dramatically, for example on 22th post the response time was raised to ~5min. After that i did some digging and find out that the size of internal DB is doubled on each post. On 22th post the size reached the size of ~200Gb(23th 400Gb and so on). Those tests are produced on docker container grafana:latest 

**What you expected to happen**:
I expected to to create a new contact point just as I did with alerts and policies

**Reproduce**:
In order to reproduce this issue just make ~15 posts 

curl -X 'POST' \                                                                         
  'http://admin:admin@127.0.0.1:3000/api/v1/provisioning/contact-points' \
  -H 'accept: application/json' \
  -H 'Content-Type: application/json' \
  -d '{
  "disableResolveMessage": false,
  "name": "test",
  "settings": {"addresses": "test@test.gr"},
  "type": "email",
  "uid": "my_external_reference"
}'

**Environment**:
- Grafana version: v9.0.1
- User OS & Browser: Arch Linux x86_64

**Comment by JohnnyQQQQ** [comment]
Thanks for opening the issue. We are aware of this issue and are tracking it here https://github.com/grafana/grafana/issues/51356
