### ISSUE TITLE
[Bug] SingleStat Gauge metric does not render inside the panel

### ISSUE THREAD

**Issue by bscholze** [grafana/grafana#5143]
If you switch a SingleStat panel to Gauge it does render inside the panel.

![image](https://cloud.githubusercontent.com/assets/7476164/15479487/70bcd736-20ee-11e6-9643-259ab0514ce2.png)

This is the only error I see in the development console

![image](https://cloud.githubusercontent.com/assets/7476164/15479544/b07c9f5a-20ee-11e6-90ce-cfc4c5c66e70.png)

Same dashboards that worked 3.0.1 are showing now this behavior

Please include some basic information:
- What Grafana version are you using? 3.0.3
- What datasource are you using? Graphite
- What OS are you running grafana on? Windows

**Comment by torkelo** [comment]
what's the span of the panel?

**Comment by bscholze** [comment]
Doesn't seem to matter what the span is. If I start with an empty dashboard, and add just one single stat panel - it spans across the whole row, and it is centered

![image](https://cloud.githubusercontent.com/assets/7476164/15480133/dc5c28cc-20f1-11e6-87d2-1000469d0f8d.png)


but as soon as you change the panel size (via +/- or resize handle) you get this

![image](https://cloud.githubusercontent.com/assets/7476164/15480153/fbdf652e-20f1-11e6-8392-da53737a1da3.png)

**Comment by torkelo** [comment]
thanks for reporting this, this is really strange

**Comment by bbczeuz** [comment]
Using Grafana 3.0.4, 1464167696 I still get the error. Sometimes the gauge is displayed outside of the panel, sometimes not at all: ```Invalid dimensions for plot: width = 126, height = 0```
--> Row height is set to 100px, Panel height is set to 100px. No change I remove one or both heights.

I'm trying to dynamically generate gauges based on template selections (p.e. host names)
