### ISSUE TITLE
Cannot remove a user from an organization

### ISSUE THREAD

**Issue by hakro** [grafana/grafana#51443]
**What happened**:
After migrating to Grafana 9, Trying to remove a user from an organization, but getting a "404 not found"
The user is part of other organizations, and needs to keep that access.
Nothing shows up in the logs related to this.

![2022-06-27_16-10](https://user-images.githubusercontent.com/3624853/175963277-dcc680d3-58fe-4e36-a10a-b46d28e3a99c.png)

The browser network inspector : 
![2022-06-27_16-12](https://user-images.githubusercontent.com/3624853/175963488-79eef8f7-64da-4087-8f55-58a42c823dbf.png)

And the console : 
![2022-06-27_16-21](https://user-images.githubusercontent.com/3624853/175963852-1634553c-52c3-4cbb-b16f-4b7d4b240d2a.png)

We are using the Generic Oauth provider with the following config : 

![2022-06-27_16-17](https://user-images.githubusercontent.com/3624853/175964066-b66bf911-79ab-4bd5-a0e2-ed982ffea3a7.png)

**What you expected to happen**:
Just that the user gets deleted

**How to reproduce it (as minimally and precisely as possible)**:
Using an Oauth provider, try creating an org, add a provisionned user to it. Then try to remove it from that org.
The error popup appears (see screenshot above)
Also, unable to change the role initially attached to the user, even if it was set from grafana, not from the ID Provider.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.0
- Data source type & version: Core
- OS Grafana is installed on: Official Docker image : grafana/grafana:9.0.0
- User OS & Browser: PopOS 22.04, Firefox
- Grafana plugins: None
- Others: None

**Comment by AlessandroBravo** [comment]
Same problem in 9.0.1 using gitlab as oauth provider

**Comment by shaardie** [comment]
Same problem in 9.0.2 with auth.jwt

**Comment by krzysdabro** [comment]
Fixed in #52473

**Comment by diogouchoas** [comment]
In which grafana version will  this fix be available?

**Comment by tolzhabayev** [comment]
closed, see above
