### ISSUE TITLE
Docs feedback: /administration/data-source-management/_index.md

### ISSUE THREAD

**Issue by skeilson** [grafana/grafana#51441]
Data source permissions page no longer matches the description in the customer-facing Documentation. 

See example screenshot from Configuration --> Data Sources
![Screen Shot 2022-06-27 at 8 09 06 AM](https://user-images.githubusercontent.com/106830544/175961445-1e9d2a7c-9a2f-42f6-93a8-21f37707c519.png)

**Comment by chri2547** [comment]
It appears that step 5 in https://grafana.com/docs/grafana/latest/administration/data-source-management/#assign-data-source-permissions-to-users-teams-or-roles is incorrect.

**Comment by Willie-The-Lord** [comment]
Hi @chri2547  I would like to work on this issue. Thanks!

**Comment by Eve832** [comment]
This was fixed by @imatwawana when she updated all of the tasks/screenshots for Grafana 9.0. **Service Account** has been added to step 5 above
