### ISSUE TITLE
Create Alerts, Notification Policies via REST-API

### ISSUE THREAD

**Issue by dfoxg** [grafana/grafana#51455]
**What happened**:
I want to automate the creation of alerting rules, notification policies and contact points. But after I created the objects over the API, I can’t manually edit the created objects in the UI:
![image](https://user-images.githubusercontent.com/28670365/175989195-1820a438-a754-45df-b0bb-73413e95985e.png)

**What you expected to happen**:
I want to create the objects via the API, but also want to use the UI to edit the created objects

**How to reproduce it (as minimally and precisely as possible)**:
- 

**Anything else we need to know?**:
Python-Code to create the notificaction policy:
```
 obj = {
        "receiver": "test@test.de",
        "object_matchers": [],
        "repeat_interval": "8h",
        "routes": [
            {
                "receiver": fullSN,
                "object_matchers": [["sn", "=", sn]],
            }
        ],
    }

    resp = session.put(grafanaParsedURL + "/api/v1/provisioning/policies", json=obj)
```

**Environment**:
- Grafana version: 9.0.1
- Data source type & version: Prometheus
- OS Grafana is installed on: Kubernetes via helm charts
- User OS & Browser: Windows 10 with Edge
- Others: [My Post on the forum, but with no response at all](https://community.grafana.com/t/create-alerts-notification-policies-via-rest-api/67426)

**Comment by JohnnyQQQQ** [comment]
Hey 👋 this is the expected behavior, as we don't allow to mix things up otherwise they might end up in a strange place where you do changes in the UI but you might have some provisioning tooling running that will overwrite those changes.
