### ISSUE TITLE
Folder 'Editor' permissions don't match description in docs

### ISSUE THREAD

**Issue by mure** [grafana/grafana#51464]
**What happened**:

The docs say, regarding folder-specific permissions:
> Edit: Can create and edit dashboards. Editors cannot change folder or dashboard permissions, or add, __edit__, or __delete__ folders.

I have a user with Viewer permissions in the org:

![Screen Shot 2022-06-27 at 2 35 09 PM](https://user-images.githubusercontent.com/9257800/176021626-30b40bc0-0da5-4c35-9a54-999e46d49044.png)
But Editor permissions on a specific folder:

![Screen Shot 2022-06-27 at 2 37 54 PM](https://user-images.githubusercontent.com/9257800/176022081-1ca32fc7-4355-42db-8a1b-0b4ed24fde14.png)

And when I login as that user, they can edit the folder or delete it, which the docs explicitly say is not allowed:

![Screen Shot 2022-06-27 at 2 36 43 PM](https://user-images.githubusercontent.com/9257800/176021855-5fbab590-ebde-4baa-9600-4c32e69852cb.png)

**Environment**:
- Grafana version: 9.0.1 (homebrew)
- Data source type & version: n/a
- OS Grafana is installed on: MacOS 12
- User OS & Browser: MacOS 12 Chrome
- Grafana plugins: n/a
- Others: n/a

**Comment by mure** [comment]
Forgot the link to the docs: https://grafana.com/docs/grafana/next/administration/roles-and-permissions/#dashboard-permissions

**Comment by ivanahuckova** [comment]
I was able to reproduce this as well.

**Comment by kaydelaney** [comment]
I think this is probably a backend issue? @grafana/backend-platform

**Comment by ying-jeanne** [comment]
hey @grafana/enterprise-engagement-squad could you take a look at this? It seems the viewer has permission to delete the folders which should not be the in case on Grafana v9

**Comment by vtorosyan** [comment]
I think this is for @grafana/grafana-authnz-team , I will add this to next items to check.

**Comment by gamab** [comment]
Thanks for pointing it out :+1: 
We need to update the docs to reflect the truth as the code has been allowing deletion with Folder "Edit" for a while (~5yrs):

https://github.com/grafana/grafana/blob/268fb4dc6c1c573bcddc44bae7a9e2413fb37544/pkg/api/folder.go#L137

https://github.com/grafana/grafana/blob/268fb4dc6c1c573bcddc44bae7a9e2413fb37544/pkg/services/dashboards/folder_service.go#L174

https://github.com/grafana/grafana/blob/268fb4dc6c1c573bcddc44bae7a9e2413fb37544/pkg/services/guardian/guardian.go#L41

And I guess there was a small mistake made in the docs (~2yrs ago):
https://github.com/grafana/grafana/blob/5e3465a100e4e5150aa140124c1ffa8f02fb8728/docs/sources/permissions/dashboard_folder_permissions.md#L25

I'll do this ASAP :slightly_smiling_face:
