### ISSUE TITLE
Download Filename Tweak Breaking my Scripts

### ISSUE THREAD

**Issue by andyl** [grafana/grafana#5146]
I install/config Grafana with Ansible.  The install method takes a version number as a parameter - (eg 3.0.0).  So far so good.

But starting in version 3.0.3, you add another funky bit to the download filename:

`grafana_3.0.3-1463994644_amd64.deb`

Feature request: please remove the funky bit, so I don't have to go look it up each time you come out with a new release.  The filename should look like this:

`grafana_3.0.3_amd64.deb`

**Comment by torkelo** [comment]
ok, the iteration number is part of the version. But I can try to modify the release script so it is removed for official release builds.

**Comment by andyl** [comment]
Thanks!!
