### ISSUE TITLE
Using query builder model. when the number of metrics is too large, the page freezes

### ISSUE THREAD

**Issue by BruceMa29** [grafana/grafana#51477]
**What happened**:
<img width="854" alt="image" src="https://user-images.githubusercontent.com/63951257/176125909-b5cc8f99-af93-4f8a-b47a-ef378ed924ed.png">

- Grafana version: v9.0.1
- User OS & Browser: Mac & chrome

**Comment by BruceMa29** [comment]
@yesoreyeram hi, is there any plan to fix this bug？

**Comment by aocenas** [comment]
Looks like a duplicate of https://github.com/grafana/grafana/issues/52171
