### ISSUE TITLE
Explore: Slow animations when entering split mode with a Prometheus query

### ISSUE THREAD

**Issue by jorgelbg** [grafana/grafana#51487]
**What happened**:

When we click in the <kbd>Split</kbd> button in the Explore UI with a Prometheus query already entered and displaying in the graph the animation is quite slow. From the visualization it seems that the graph is being refreshed multiple times as the right container gets resized (see the following video):

https://user-images.githubusercontent.com/1291846/176146942-6bff94e8-c94d-4923-bfb7-dd847a510405.mp4

**What you expected to happen**:

What seems to happen with other datasources is that the execution of the query seems to wait until the right panel is completely visible and there seems to be no animation either. Otherwise the animation should be smoother. 

**How to reproduce it (as minimally and precisely as possible)**:

Go into the explore mode, select a Prometheus datasource and introduce a query. After the graph (with the result of the query) is visible click the <kbd>Split</kbd> button.

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.1
- Data source type & version: Prometheus 
- OS Grafana is installed on: Docker image based on `grafana/grafana`.
- User OS & Browser: macOS Monterey 12.4 (21F79) / Version 103.0.5060.53 (Official Build) (x86_64)
- Grafana plugins:
- Others:

**Comment by gelicia** [comment]
I checked this out and I think it's some sort of interaction with the prometheus query editor and the rest of explore. If you put a console log in the resize function of explore ([src](https://github.com/grafana/grafana/blob/main/public/app/features/explore/Explore.tsx#L180)), you see with non-prometheus editors, it is called twice or so. With prometheus, it's called around 30 something times.

I tried to figure out why this might be but am not quite able to get there. There's a resize function within Monaco ([src](https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/components/monaco-query-field/MonacoQueryField.tsx#L184)) but that only gets called twice. I'm wondering if theres something in there that would slow down the resize. We can add a debounce in there if we think that is needed but I'm wondering if someone who knows the query editor better has any other ideas?

**Comment by gtk-grafana** [comment]
@grafana/observability-metrics @gelicia We're going to try to take a look at this (as a low priority) and see if this is something we can improve on the prometheus side.

**Comment by LudoVio** [comment]
Investigated this. 
Now the rendering of the Prometheus editor is in line with other datasources editors on resize (which split trigger)
The performance is not the best, particurly in dev environment. It is way better with assets build for production and react-dev-tool browser extension disable
