### ISSUE TITLE
Elasticsearch: Support metric aggregations like Percentiles and extended stats in Order By

### ISSUE THREAD

**Issue by felixbarny** [grafana/grafana#5148]
**What Grafana version**
3.0.2

**What datasource**
Elasticsearch

**What did you do?**

* Go to http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=1&fullscreen&edit
* Edit metric to percentile and set percentiles to 99
* Modify Order By of `@hostname` terms aggregation -> set to `Percentiles @value`
![orderbypercentiles](https://cloud.githubusercontent.com/assets/2163464/15497221/e465433e-2199-11e6-8ca8-1094d7d6d191.png)

**What was the expected result?**
When only one percentile is entered, the aggregation order path should be set automatically (see error message below). When multiple percentiles are entered, the user should be able to choose one.

**What happenend instead**

```
{
"root_cause": [
{
"type": "aggregation_execution_exception",
"reason": "Invalid terms aggregation order path [1]. When ordering on a multi-value metrics aggregation a metric name must be specified"
}
],
"type": "search_phase_execution_exception",
"reason": "all shards failed",
"phase": "query",
"grouped": true,
"failed_shards": [
{
"shard": 0,
"index": "metrics-2016.05.24",
"node": "Fs1eG42kRquwBzlAS_nB-w",
"reason": {
"type": "aggregation_execution_exception",
"reason": "Invalid terms aggregation order path [1]. When ordering on a multi-value metrics aggregation a metric name must be specified"
}
}
]
}
```

**Comment by irocks04** [comment]
Hi Torkelo,

Is this issue fixed? since i am facing similar problem for percentiles. I get the exact error message " when ordering on a multi-value aggregation a metric name must be specified".  I used Elasticsearch v1.5.2 and Kibanav4.0.2. Please let me know if this works fine for you and the version i need to upgrade to get this working.

**Comment by pedrokiefer** [comment]
👍 

Just got to this issue trying to create an extended stats aggregation.

**Comment by NikitaZhdanov** [comment]
Hi All,

Is it still not fixed? Nobody knows a workaround?

**Comment by chanjarster** [comment]
got same issue

**Comment by phrfpeixoto** [comment]
I'm also facing the same when trying to order by aggregated percentiles.

**Comment by simianhacker** [comment]
I'm going to start looking into a fix for this issue.
