### ISSUE TITLE
[Help]  Have the display benefits of connected and null as zero

### ISSUE THREAD

**Issue by Azef1** [grafana/grafana#5149]
Hi,

I would like to have help, perhaps it's a pull resuest:
I using Grafana to show the state of service over time (OK, Warning Critical) from Nagios log. My grafana using ElasticSearch as source:
![stateovertime](https://cloud.githubusercontent.com/assets/15362041/15497861/1501f3ea-219d-11e6-9be7-8522384e02bc.png)

The problem is: Nagios doesn't send log periodically when a service is OK. Nagios send one OK only after Critical or Warning state. So Grafana, doesn't show a line from last Ok to now (you can see on picture there isn't line from 5/20 18h to now), if my service keep OK.

A partial solution is to set "Null value" to "null as zero", the result is:
![stateovertime2](https://cloud.githubusercontent.com/assets/15362041/15498189/dd5bb096-219e-11e6-81e5-2ce63659c0a2.png)

So my question is: Can we have the benefits of `connected` and `null as zero` both  for last point on my graph?

Tell me, it is not clear.
Grafana 3.0 
ElasticSearch 2

**Technical informations**
In Nagios log:
Critical state = 2
Warning state = 1
Ok state = 0
I using Transform: negative-Y to show OK in top of graph and Critical in bottom

**Comment by torkelo** [comment]
when you set null value to null as zero, make sure your date histogram interval does go below the rate at which nagios write at (specify for example `>10s`  in the group by time option below the queries.

**Comment by Azef1** [comment]
Thx for your answer. I set "date histogram interval" at 1h, it'works but the precision is poor.
For example:
![poor](https://cloud.githubusercontent.com/assets/15362041/15502152/805984ea-21b2-11e6-9a6a-e18de00fa463.png)
The critical event start from 2016-05-18 13:36:35 and on picture line start before. So, it does not reflect reality.

On the other example, i set interval to 30min it's too bad:
![poor2](https://cloud.githubusercontent.com/assets/15362041/15502257/1b2e9e10-21b3-11e6-9191-2e494ff8802b.png)

And here, i set interval to 10s:
![poor3](https://cloud.githubusercontent.com/assets/15362041/15502362/bcac42f6-21b3-11e6-917e-74b6f18a1e12.png)


If i set `>10s`, Grafana say Failed to parse [>10s]
