### ISSUE TITLE
Wecom contact channel can't define the title which I want

### ISSUE THREAD

**Issue by dingweiqings** [grafana/grafana#51528]
**What happened**:
1. I add a wecom contact point  and notification policy , then click test msg, then I got a message in wecom.
![image](https://user-images.githubusercontent.com/30000877/176338296-c38fa582-b05b-4a4f-afd2-3325c5b783dd.png)
2. I add a wecom contact point  and notification policy , then add a rule for example cpu usage > 10% ,then I got a alert message in wecom.
![image](https://user-images.githubusercontent.com/30000877/176338918-9581ef9f-fbec-4a6a-9330-f17652a11d0d.png)

**What you expected to happen**:
I can define the msg title which I want in test and alert msg  ,like this message 
![image](https://user-images.githubusercontent.com/30000877/176338395-e9e6d327-cbd1-4874-a9cf-d2c140f8ddc3.png)

**How to reproduce it (as minimally and precisely as possible)**:
   Use wecom contact point as notification type ,and you will reproduce it .
**Anything else we need to know?**:

**Environment**:
- Grafana version: docker image grafana/grafana:9.0
- Data source type & version: Prometheus 2.26.0
- OS Grafana is installed on: ubuntu18.04 and docker 20.10.17
- User OS & Browser: 
- Grafana plugins:
- Others:
**Link Issues**
#48159

**Comment by armandgrillet** [comment]
This should be fixed since 9.1, thanks for the contribution!
