### ISSUE TITLE
Unknown error   Cannot read property 'message' of null

### ISSUE THREAD

**Issue by galdreiman** [grafana/grafana#5152]
I'm trying to set Grafana with Graphite and in Data Sources page I use the configuration as follows:
```
Name: Graphite (default- true)
Type: Graphite
url: XXX:8080
Access: direct
Http Auth: Basic Auth- true   With Credentials - true
user: XXX
pass: XXX
```

I press 'Save & Test' and get:
```
Unknown error
Cannot read property 'message' of null
```

versions:
Graphite: 1.6.1
Grafana: 3.0.3

There were previous issues like this but no solution was good here.
I really need your help please.

**Comment by torkelo** [comment]
Since you used "direct" access, have you configured CORS headers for Graphite? Can you open chrome dev tools console and check for any error there?
