### ISSUE TITLE
[Feature Request] Support template variable refreshing on variable change

### ISSUE THREAD

**Issue by samstarling** [grafana/grafana#5153]
Some of my template variables depend on each other. For example, the first one is a dropdown that allows to choose the data source, and the other two variables are populated with data from this data source.

As such, it would be really useful to have "On variable change" as an option for when these selection options should be refreshed.

**Comment by torkelo** [comment]
this is enabled by default. If a variable uses another variable a chang in the "parent" wil trigger an update. 

There was a bug in 3.0-beta to 3.0.2 that caused the check for child variables to not work correctly. This might be the cause for it not working for you. Please try 3.0.3

**Comment by samstarling** [comment]
OK - will do. Thanks!
