### ISSUE TITLE
[Bug] InfluxDB source: Escaping in template variables

### ISSUE THREAD

**Issue by bbczeuz** [grafana/grafana#5154]
- What Grafana version are you using?
```
Grafana version: 3.0.3, commit: v3.0.3, build date: 2016-05-23 10:58:31
```
- What datasource are you using?
```
InfluxDB 0.13.0
```
- What OS are you running grafana on?
```
Centos7
```
- What did you do?

1. Add a new template variable $templatename of type query: SHOW MEASUREMENTS
2. Add a table with the following query:
```
SELECT * FROM "store30d"."$templatename" WHERE "id" =~ /^$Id$/ AND "agent_id" =~ /^$agent_id$/ AND "name" =~ /^$name$/ ORDER BY time DESC LIMIT 5
```
- What was the expected result?
--> Real data
- What happenend instead?
```
"message": "error parsing query: found \\., expected identifier at line 1, char 37"
```
```
	SELECT * FROM "store30d"."test_web\.php" WHERE "id" =~ /^(5988|5990|6037)$/ AND "agent_id" =~ /^(1017|1021|1022)$/ AND "name" =~ /^(Dentblanche|Toedi|Wiwanni)$/ ORDER BY time DESC LIMIT 5
```

--> Grafana escapes the dot. Not a nice design, but correct according to the spec (The dot typically separates retention policies from measurement names. If they're in double quotes, the dot doesn't do anything.)
- In a comment of #4667 it's proposed that Grafana should check if the variable is being used in a quoted environment and then not escape it.
The reference says: https://docs.influxdata.com/influxdb/v0.13/query_language/spec/#identifiers
```
Identifiers are tokens which refer to database names, retention policy names, user names, measurement names, tag keys, and field keys.

The rules:
    double quoted identifiers can contain any unicode character other than a new line
    double quoted identifiers can contain escaped " characters (i.e., \")
    double quoted identifiers can contain InfluxQL keywords
    unquoted identifiers must start with an upper or lowercase ASCII character or “_”
    unquoted identifiers may contain only ASCII letters, decimal digits, and “_”
```
Ergo: No escaping within double quotes except for the double quotes contained within.

**Comment by torkelo** [comment]
It works fine when I use the query editor. The query editor knows that the measurement should not be regex escaped. 

![image](https://cloud.githubusercontent.com/assets/10999/15534189/f91b8f30-2267-11e6-8f5e-6b86f9c0a799.png)

If you use the raw query mode, all template variables will be regex escaped. So you can either switch to query editor mode, or change the measurement part of your query to `SELECT * FROM "store30d"./$templatename/ WHERE

**Comment by bbczeuz** [comment]
Works, thanks
Lesson: Variables in Regexes are not being escaped.

**Comment by torkelo** [comment]
yes they are, they are regex escaped.
