### ISSUE TITLE
InfluxDB: Backend migration discrepancies / issues

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#51547]
When investigating an InfluxDB issue, found few issues/discrepancies when `GF_FEATURE_TOGGLES_ENABLE=influxdbBackendMigration` enabled.

- [x] epoch parameter in the query is now changed from ms to s
- [x] URL encoding of the query is mismatching
- [x] time range in query is change from related time to absolute time. Ex:`time >= now() - 30m and time <= now()` to `time > 1656493891361ms and time < 1656495691361ms` ( also noticed ms added to the timestamp. Not sure if this is influx convention )
- [x] also noticed `ORDER BY time ASC` appended to they query automatically in some cases after migration
- [x] `;` is appended to the query after migration
- [x] time range filter is expanded to `>` instead `>=` after migration.

Even though these may not be actual issues, recording here for future reference.

cc @itsmylife @joey-grafana

**Comment by itsmylife** [comment]
https://github.com/grafana/grafana/pull/51624 Addresses `URL encoding of the query is mismatching`

**Comment by itsmylife** [comment]
https://github.com/grafana/grafana/pull/51651 Addresses `epoch parameter in the query is now changed from ms to s`

**Comment by itsmylife** [comment]
`ORDER BY time ASC` is ok to have. On the frontend order by time is a dropdown and ASC is the default value of it. 
See: 
<img width="279" alt="image" src="https://user-images.githubusercontent.com/820946/177607319-2b19e8db-c7dc-4fb1-b333-7c545a8a463a.png">

**Comment by itsmylife** [comment]
Appending `;` is also ok. If there are multiple queries we send them in one request. So we need `;` in between those.
See: 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/820946/177607510-30e85678-a279-42ec-9816-edce428b6b43.png">

**Comment by itsmylife** [comment]
@yesoreyeram time range is being handled here: https://github.com/grafana/grafana/blob/main/packages/grafana-runtime/src/utils/DataSourceWithBackend.ts#L158-L162
I think it is ok to have it this way. What do you think?

**Comment by itsmylife** [comment]
` time range filter is expanded to > instead >= after migration.` will be fixed in: https://github.com/grafana/grafana/pull/51835
