### ISSUE TITLE
"servers.group_mappings" ldap config overrides admin added acl

### ISSUE THREAD

**Issue by mowntan** [grafana/grafana#5155]
we are trying to give all (ldap) authenticated users viewer permissions to all the organizations, and then use the built in RBAC in grafana to designate editor and admin roles. Initially we thought that adding a "servers.group_mappings" option in the ldap config would setup a default, but it looks like it's resetting the users ACL on login. Is there a way to setup a default viewer for all orgs, but then overlay higher roles as people login?

Grafana: grafana-3.0.2-1463383025.x86_64
w/ LDAP integration

**Comment by torkelo** [comment]
no, currently the LDAP group mappings will always decide what roles and orgs users should belong to.

**Comment by mowntan** [comment]
Is there anything that we could do in order to achieve what we want to do.

**Comment by torkelo** [comment]
the only way to currently disable the ldap group -> grafana org role syncing is to not define any `[[servers.group_mappings]]` at all your ldap.toml file. But then you can't login, hm.. no I don't see any way around this at the moment.

**Comment by DaShepsky** [comment]
What are the plans to address this issue? Will any future versions of Grafana allow for a one-time mapping?
