### ISSUE TITLE
Chore: Improve `RefreshPicker` story

### ISSUE THREAD

**Issue by ashharrison90** [grafana/grafana#51567]
- [ ] Add documentation in the form of `RefreshPicker.mdx`
  - Where it's used in the product
  - What it's used for
- [ ] Add support for [controls](https://storybook.js.org/docs/react/essentials/controls) for the various props

**Comment by sonjafeitsch** [comment]
Hi @ashharrison90 I would like to work on this ticket. Can you assign it to me?

**Comment by ashharrison90** [comment]
hi @sonjafeitsch 👋 

i was hoping to use this as an intro task for one of our new team members if that's alright? 😅 
if you're like a storybook task to work on, there's several other similar ones i can suggest... the main one that springs to mind is adding control support in the `Button` story?

lmk what you think 😄

**Comment by ashharrison90** [comment]
there's also a bunch of tasks to add controls as part of this epic https://github.com/grafana/grafana/issues/51330 👍

**Comment by sonjafeitsch** [comment]
@ashharrison90 alright, that's no problem 😊 I will have a look at the epic #51330 and look for something there 👍
