### ISSUE TITLE
Binary package Raspberry Pi / Raspbian

### ISSUE THREAD

**Issue by mzac** [grafana/grafana#5156]
Are there any plans to create a ARM HF package for Raspbian / Raspberry Pi support?

Of course one could compile from source but it would be much easier if packages existed!

**Comment by bergquist** [comment]
We don't have any plans for this but It would be nice to have some time in the future.

**Comment by fg2it** [comment]
@mzac I can only agree with you, that would be very nice! I try to keep up with the latest releases and provide the package on a repo on github but the poor pi2 has a lot of work lately.

@bergquist I see the "state: help wanted (PR)" label. Do you have something specific in mind ? From what I can see, it seems the work is on the automatic building process only, since everything already build nicely on pi (except maybe phantomjs, but I would have to check the latest release).

**Comment by captSL** [comment]
A package for Raspberry Pi/ARM would be really nice. In my case I'm using a RPi for home automation and Grafana for the graphing of temperatures etc.

**Comment by TotallyInformation** [comment]
Interesting that the InfluxDB guys had few problems getting their repos updated for ARM releases very quickly once we prompted them.

InfluxDB, Telegraf and Grafana are ideal for the Pi and IoT. It is a shame to be held back this way.

**Comment by Lenbok** [comment]
I have been using the packages from @fg2it which work great, thanks! Is it just the lack of a build system that is the issue in making "official" builds?

**Comment by fg2it** [comment]
@Lenbok glad to read that. I guess that phantomjs is a bit of a problem too.
By the way, maybe that, since now grafana has a plugin system, the png snapshot feature could go to a plugin. An official plugin could be provided for some specific platform. Then, the core of grafana would be easier to package. And the problem would only concern a single feature.

**Comment by TotallyInformation** [comment]
I too really appreciate the repo from @fg2it - without it I wouldn't be using Grafana at all.

However, it seems unfair to make someone else maintain a separate repo when this should be part of the automated build.

In addition, if @fg2it becomes busy with other projects or stops using Grafana then that build will get more and more out of date and we will have to stop using it. Building from source on a Pi is extremely painful to do manually.

**Comment by scargill** [comment]
I went looking today for the Pi2 - the best we have is the BETA1 version - how difficult could it be to provide Arm versions along with the rest.... I've love to upgrade to the latest on my Pi.

**Comment by TotallyInformation** [comment]
Hi Pete,

This thread is a little outdated now. The repo for the Pi works just fine and the latest version of Grafana is available in it though I did have to force an update on m Pi2.

The new version is great and there are a lot of new plugins that make a real difference.

**Comment by scargill** [comment]
Link?

**Comment by fg2it** [comment]
@scargill I think @TotallyInformation had my repo in mind, either the github release [section](https://github.com/fg2it/grafana-on-raspberry/releases), or the [bintray deb repo](https://dl.bintray.com/fg2it/deb), but I think you know them if I remember your blog posts correctly.

@TotallyInformation I am not sure this post is outdated. I am pretty sure @mzac had in mind an *official* package and, me too, I would be very happy to see one.

@bergquist aren't we "some time in the future" yet ? 😉

**Comment by TotallyInformation** [comment]
@fg2it, yes I got a little mixed up with my repos!

I agree that there really should be an official ARM version, crazy that it is being left up to you even though you have done a great job on it - and thanks again for sorting it all out.

**Comment by torkelo** [comment]
latest beta now have arm builds :)

**Comment by mcaulifn** [comment]
I don't see the package in the repo. I was able to download it from S3.

**Comment by bergquist** [comment]
All downloads can be found at grafana.com ex
https://grafana.com/grafana/download/5.2.0-beta2?platform=arm

**Comment by rawctl** [comment]
Any chance we could get those new packages into the packagecloud repositories at [1]?

[1] https://packagecloud.io/grafana/stable

**Comment by rawctl** [comment]
Just for reference, I created an issue for this at #12761.
