### ISSUE TITLE
Table Panel - incoherent display value on rarely used column - null vs Blank

### ISSUE THREAD

**Issue by Trovalo** [grafana/grafana#51574]
**What happened**:
I've noticed something weird in the displayed value on a rarely populated column.

Let's say I run a plain select on InfluxDB, note that _NonExisting_ does not exist in the DB, this will return null values in the object received by Grafana (query inspector).
`SELECT "datacenter", "hostname","value","NonExisting" FROM "cpu" WHERE $timeFilter`

If all the values of that column are `null` → the Grafana cell displays null, the cursor will become a "hand" (as for links), and there will also be a link-style window when you hover on top of it...
If even just one value **is not** `null` → The column will be blank when the value is null...

In both cases, a column filter will display Blank as a possible value (null is never shown in the filter), therefore I think something is wrong with the displayed value
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
I've been able to reproduce half of it the Grafana playground, the part in which null is displayed, which is the anomaly anyway...
For the other half you need a field/tag or generally a column even with just one single point, if the point is within the time range I see blanks, otherwise null

<details>
  <summary>here is the panel code</summary>
  
```
{
  "id": 1,
  "gridPos": {
    "h": 9,
    "w": 24,
    "x": 0,
    "y": 0
  },
  "type": "table",
  "title": "Selected Servers",
  "datasource": {
    "uid": "000000002",
    "type": "influxdb"
  },
  "interval": "$summarize",
  "links": [],
  "targets": [
    {
      "refId": "A",
      "datasource": {
        "type": "influxdb",
        "uid": "000000002"
      },
      "policy": "default",
      "resultFormat": "table",
      "orderByTime": "ASC",
      "tags": [],
      "groupBy": [
        {
          "type": "time",
          "params": [
            "$__interval"
          ]
        },
        {
          "type": "tag",
          "params": [
            "datacenter"
          ]
        },
        {
          "type": "tag",
          "params": [
            "hostname"
          ]
        },
        {
          "type": "fill",
          "params": [
            "null"
          ]
        }
      ],
      "select": [
        [
          {
            "type": "field",
            "params": [
              "value"
            ]
          },
          {
            "type": "mean",
            "params": []
          }
        ]
      ],
      "measurement": "cpu",
      "query": "SELECT \"datacenter\", \"hostname\",\"value\",\"NonExisting\" FROM \"cpu\" WHERE $timeFilter",
      "rawQuery": true
    }
  ],
  "options": {
    "showHeader": true,
    "footer": {
      "show": false,
      "reducer": [
        "sum"
      ],
      "fields": ""
    }
  },
  "fieldConfig": {
    "defaults": {
      "custom": {
        "align": "auto",
        "displayMode": "auto",
        "inspect": false
      },
      "mappings": [],
      "thresholds": {
        "mode": "absolute",
        "steps": [
          {
            "value": null,
            "color": "green"
          },
          {
            "value": 80,
            "color": "red"
          }
        ]
      },
      "color": {
        "mode": "thresholds"
      }
    },
    "overrides": []
  },
  "pluginVersion": "9.0.2-2200920",
  "timeFrom": null,
  "timeShift": null
}
```
</details>

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.2.5
- Data source type & version: InflxDB 1.8
- OS Grafana is installed on: Windows
- User OS & Browser: Windows & Google Chrome
- Grafana plugins: No

**Comment by dprokop** [comment]
@Trovalo can you export raw CSV results of your query by using Panel Inspect -> Download CSV? Please disable data formatting and transformations.

**Comment by Trovalo** [comment]
here you go, this is a subset of my data in which you can see both cases.
SPID - No values, displayed as null
Blocking SPID - Has few values, displayed as blank
[Queries-data-2022-07-05 15_52_42.csv](https://github.com/grafana/grafana/files/9046937/Queries-data-2022-07-05.15_52_42.csv)

**Comment by zoltanbedi** [comment]
Hey @Trovalo,
I was able to see the issue you described however I have a hard time understanding what is wrong and what would you expect should happen?

**Comment by Trovalo** [comment]
as a simple rule, I don't want to see the column "change" from `blank` to `null` (or vice-versa) while changing the time range.

Take the case of Blocking SPID, which has a few values, what might happens is that:
- filter the last 30min → there is at least one value → the column displays `blanks`
- filter the last 5min → there are no values in that range → the column displays `null`


as a user, I find it incoherent, and I ask myself: _why is it null? it was blank before I changed_

**Comment by aocenas** [comment]
This seems like it's more about the table panel right? Don't seem like we should somehow change the data from influx so I will remove this from metrics project.

**Comment by dprokop** [comment]
@Trovalo thanks for providing more info. I've noticed that the cell type for Blocking SPID is JSON View Cell when all values are null. Can you confirm what the cell type is when there are both null and some values in that column (screenshot 1 in the comment above). I see in your panel JSON that the cell display mode is set to `auto` and I'm trying to figure out if the automatic behavior does not change the cell type for some reasone. That would explain why you see blank cells and `null` interchangeably.

**Comment by Trovalo** [comment]
As you said, the table is set to use `auto`.
I'm not 100% sure about how to find the datatype, but using the `Inspect → JSON → DataFrame Structure` I've found that
- without any value → "type": "other"
- with values → "type": "number"

**Comment by dprokop** [comment]
> As you said, the table is set to use `auto`. I'm not 100% sure about how to find the datatype, but using the `Inspect → JSON → DataFrame Structure` I've found that
> 
> * without any value → "type": "other"
> * with values → "type": "number"

Ok, then I think this explains a lot. With `auto` cell display mode the cell is displayed with JSON View Cell. That's why I thought this might be related to InfluxDB, not the table panel. This is the desired behavior, and I think the fix should be applied in the InfluxDB data source - for the numeric column the field type should be `number` instead of `other`. @aocenas any thoughts on this?

**Comment by zoltanbedi** [comment]
Removing this from our board as Dominik said this is a desired behavior. Pinging @grafana/observability-metrics squad if they want to do anything with this.

**Comment by itsmylife** [comment]
I cannot reproduce the issue with the latest version. Could you please upgrade and try again?
