### ISSUE TITLE
Invalid ar/.deb format at official Grafana Debian packages 

### ISSUE THREAD

**Issue by xenuser** [grafana/grafana#5157]
I tried to import the (official ?) Grafana Debian packages from https://packagecloud.io/grafana/stable?filter=debs into my own reprepro Debian repository, but the tool is claming that the ar format is wrong:

```
Missing ar header '!<arch>' at the beginning of grafana_3.0.3-1463994644_amd64.deb
There have been errors!
```

I also tried older packages, but reprepro still throws an error. In addition I also tried to look into the package with various other tools (e.g. "mc" is able to extract .deb files), but all tools claim that there is something wrong with the format.

I am just curious: Is this really an issue? It might be the case that reprepro is too strict here, but I am not able to install Debian packages directly and have to put them into my mirror.

When trying to extract something manually from the package, I receive the following message:
```

ar p grafana_3.0.3-1463994644_amd64.deb control.tar.gz |tar -xz
ar: grafana_3.0.3-1463994644_amd64.deb: File format not recognized

gzip: stdin: unexpected end of file

```

Debian packages are defined as ar archives, so I am wondering if I miss something. Any feedback is highly appreciated!

(I am working with Debian Jessie.)

**Comment by torkelo** [comment]
Strange, no one else has reported any install issues with the packages

**Comment by xenuser** [comment]
I also tried to install the package directly:
```
root@someserver:~# wget https://packagecloud.io/grafana/stable/packages/debian/jessie/grafana_3.0.3-1463994644_amd64.deb
--2016-05-24 18:03:37--  https://packagecloud.io/grafana/stable/packages/debian/jessie/grafana_3.0.3-1463994644_amd64.deb
Resolving packagecloud.io (packagecloud.io)... 50.97.198.58
Connecting to packagecloud.io (packagecloud.io)|50.97.198.58|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘grafana_3.0.3-1463994644_amd64.deb’

grafana_3.0.3-1463994644_amd64.deb                       [ <=>                                                                                                                    ]  18.86K  --.-KB/s   in 0s     

2016-05-24 18:03:38 (73.2 MB/s) - ‘grafana_3.0.3-1463994644_amd64.deb’ saved [19310]

root@someserver:~# dpkg -i grafana_3.0.3-1463994644_amd64.deb
dpkg-deb: error: `grafana_3.0.3-1463994644_amd64.deb' is not a debian format archive
dpkg: error processing archive grafana_3.0.3-1463994644_amd64.deb (--install):
 subprocess dpkg-deb --control returned error exit status 2
Errors were encountered while processing:
 grafana_3.0.3-1463994644_amd64.deb

```

**Comment by xenuser** [comment]
Ok, this is embarrassing - obviously I downloaded a HTML document via wget each time, this is why I had these issues. So: layer 8 issue. Sorry, please delete/close.
