### ISSUE TITLE
[9.0.x] Azure Monitor dashboard migration results in broken dashboards

### ISSUE THREAD

**Issue by skgsergio** [grafana/grafana#51570]
**What happened**: Importing an Azure Monitor based dashboard results in a broken dashboard where all panels show a `request failed, status: 404 Not Found` error.

**What you expected to happen**: Dashboards show the actual data.

**How to reproduce it (as minimally and precisely as possible)**:
1. Have an Azure Monitor datasource configured
2. Import https://grafana.com/grafana/dashboards/14469 or https://grafana.com/grafana/dashboards/14487
3. Open the dashboard

**Anything else we need to know?**: I've spotted several issues in the migration process:

_Issue 1:_

Looks like the migration process that generates the new `resourceUri` property is not appending the `resourceName`.

Importing https://grafana.com/grafana/dashboards/14487 you can edit and inspect "Total Requests" panel JSON and observe the following:

```json
{
  // [...]
  "targets": [
    {
      "azureMonitor": {
        // [...]
        "metricDefinition": "$ns",
        "metricName": "TotalRequests",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns"
      },
      // [...]
    }
  ],
  // [...]
}
```

And if you append the `resourceName` to the `resourceUri` as follows then the panel starts working again:

```json
{
  // [...]
  "targets": [
    {
      "azureMonitor": {
        // [...]
        "metricDefinition": "$ns",
        "metricName": "IndexUsage",
        "metricNamespace": "Microsoft.DocumentDB/databaseAccounts",
        "resourceGroup": "$rg",
        "resourceName": "$resource",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource"
      },
      // [...]
    }
  ],
  // [...]
}
```

_Issue 2:_

Importing https://grafana.com/grafana/dashboards/14469 if you edit the "Transactions by storage type" panel and then inspect its JSON you can see that now the $resource is present, but the resourceUri still looks wrong.
```json
        "metricDefinition": "$ns/tableServices",
        "metricName": "Transactions",
        "metricNamespace": "Microsoft.Storage/storageAccounts/tableServices",
        "resourceGroup": "$rg",
        "resourceName": "$resource/default",
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/tableServices/$resource"
```

In this case, I managed to get it working with the following `resourceUri` which looks like a more slightly complicated transformation than in issue 1.

```json
        "resourceUri": "/subscriptions/$sub/resourceGroups/$rg/providers/$ns/$resource/tableServices/default",
```

I think that #47696 is the PR introducing the change that builds this new resourceUri:
https://github.com/grafana/grafana/blob/v9.0.1/public/app/plugins/datasource/grafana-azure-monitor-datasource/utils/migrateQuery.ts#L96-L121

**Environment**:
- Grafana version: 9.0.1
- Data source type & version: Azure Monitor (bundled version with Grafana 9.0.1)
- OS Grafana is installed on: Official Docker Container on Kubernetes with official Helm chart
- User OS & Browser: Arch Linux & Google Chrome 103.0.5060.53
- Grafana plugins: None
- Others: N/A

**Comment by andresmgot** [comment]
Thanks the report @skgsergio! We are aware of this issue, see https://github.com/grafana/grafana/issues/50530. There is some work in progress for this at https://github.com/grafana/grafana/pull/51331.

Let me close this issue as a duplicate but feel free to comment any use case that we may be missing.
