### ISSUE TITLE
Is there some easy way to integrate grafana with alerta?

### ISSUE THREAD

**Issue by rydeng** [grafana/grafana#5158]
Please include some basic information:
- What Grafana version are you using?
grafana 3.0.0-beta7 
- What datasource are you using?
influxdb
- What OS are you running grafana on?
ubuntu 14.04
- What did you do?
I want to integrate grafana with alerta.
- What was the expected result?
I want to have a plugin for using alerta in grafana. So, I want to know if there is the plan to develop an integration with alerta.

**Comment by bergquist** [comment]
We do not have any plans for that at the moment. 

If this is critical for your business I suggest you contact alerta and our commercial support https://grafana.net/support/plans maybe they can come up with something.

**Comment by satterly** [comment]
Assuming the alert handler being discussed in issue #2209 supports custom alert handlers as has been suggested then it should be very straightforward to integrate Alerta with Grafana in future.
