### ISSUE TITLE
Docs: List what data sources are compatible with Grafana Alerting

### ISSUE THREAD

**Issue by gillesdemey** [grafana/grafana#51582]
Not every data source is compatible with Grafana Alerting. 

See [this comment](https://github.com/grafana/grafana/issues/46347#issuecomment-1167236218) for what the requirements are to be compatible.

Compatible data sources are annotated in the plugin's `plugin.json` file with `{ "alerting": true }`.

We should have a docs article listing the compatible data sources and a short explanation on what is required for a data source to be compatible.

@brendamuir I've assigned this to you but the front-end team will help you get that list of data sources :)

**Comment by brendamuir** [comment]
Done - https://github.com/grafana/grafana/pull/51898
