### ISSUE TITLE
[Bug] Graph update issue with dependent tags used in influxdb query

### ISSUE THREAD

**Issue by tenortim** [grafana/grafana#5159]
Grafana version grafana-3.0.3-1463994644.x86_64
Datasource: influxdb (v0.9+) (actually running 0.13.0
OS version: CentOS Linux release 7.2.1511 (Core) 

Problem description.
Dashboard has multiple template variables.
The first 3 map to InfluxDB tags. The latter 2 are extracted via "SHOW MEASUREMENTS".
Graphs are pulling from series using these latter 2 tags. The first is protocol. The second is operation and is dependent on the first (e.g. for nfs3, operations include getattr, write, commit, ...)
Changing the first causes all of the graphs to blank until manually refreshed because it appears that
the graphs themselves refresh before the second dependent template variable is correctly refreshed.

Concrete example/data:

protocol template variable:
Query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /protocol.*/
Regex: /protocol.([^.]+)/
All option: No
operation template variable:
Query: SHOW MEASUREMENTS WITH MEASUREMENT =~ /protocol.*/
Regex: /protocol.$protocol.([^.]+)/
All option: Yes

Graph definition:
Metrics pull from e.g.
/^protocol.$protocol.$operation.opsrate/

When changing from e.g. protocol nfs3 to protocol http, the graphs blank and do not show correctly
until the page is manually refreshed even though the operation dropdown does correctly update.

**Comment by torkelo** [comment]
try changing your operation variable definition to include the first variable, then Grafana will understand the dependency chain. 

operation template variable:
Query: `SHOW MEASUREMENTS WITH MEASUREMENT =~ /protocol.$protocol./`
Regex: /protocol.$protocol.([^.]+)/
All option: Yes

**Comment by tenortim** [comment]
That fixed it. Thank you!
