### ISSUE TITLE
Preferences : Home Dashboard not working anymore for Teams

### ISSUE THREAD

**Issue by yongbi85** [grafana/grafana#51610]
**What happened**: Home dashboard is not the team home dashboard but the general home dashboard for the organization.

**What you expected to happen**:
To get to the team home dashboard and not the default one of the whole organization

**How to reproduce it (as minimally and precisely as possible)**:
Set a dashboard as default in Configuration/Preferences
Set another dashboard as default for the Team you are part of
Click the home button

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: PostgreSQL 11
- OS Grafana is installed on: CentOS 7.9
- User OS & Browser: Chrome & Edge
- Grafana plugins: None
- Others:

**Comment by ZHumphries** [comment]
Confirmed. After the upgrade every single user now has the default dashboard as their home dashboard despite it being set at the team level. Rolling back to 8 for now
