### ISSUE TITLE
Azure Monitor: Unable to use Metric namespace template variable with Microsoft.Sql/servers/databases

### ISSUE THREAD

**Issue by andresmgot** [grafana/grafana#51621]
**What happened**:

The `MetricNamespace()` template variable for some resources return `Microsoft.Sql/servers/databases` but when using that namespace in a resource URI it should be use as  `Microsoft.Sql/servers/<server_name>/databases/<database_name>` where the resource name is `<server_name>/<database_name>`.

**What you expected to happen**:

In Grafana 8.5, the resource URI was calculated on the fly using the metric namespace and resource name so it should either work in 9.0 or have a good upgrade path.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by aangelisc** [comment]
This is currently handled by #52054 pending a complete solution.
