### ISSUE TITLE
Query Builder throws away values when switching from `=~` to `!~`. 

### ISSUE THREAD

**Issue by metalmatze** [grafana/grafana#51628]
When using the new Grafana 9 (9.0.2) query builder to adjust queries to go from `match regex =~` to `not match regex !~` the values disappear except the first one when I expect to be able to still have the same values available:

Before:
![Screenshot from 2022-06-30 13-00-01](https://user-images.githubusercontent.com/872251/176662159-3d2ae0d7-5b13-47a3-81f6-c3a89cc0d818.png)
After: 
![Screenshot from 2022-06-30 13-04-31](https://user-images.githubusercontent.com/872251/176662178-d52039a3-fc77-4e10-b551-f9c043764e55.png)

See how `grpc_code!~"Aborted"` instead of the many previous values.

**Comment by joshhunt** [comment]
It appears the `~!` operator doesn't support multiple values.

**Comment by ivanahuckova** [comment]
This affects also Loki, so I am moving it to our board as I am working on fix.
