### ISSUE TITLE
[Feature Request] Grafana Table Column aggregation

### ISSUE THREAD

**Issue by summer0nguyen** [grafana/grafana#5164]
Please include some basic information:
- What Grafana version are you using? 3.0.3
- What datasource are you using? InfluxDB
- What OS are you running grafana on? CentOS 6 64bits 
- What did you do? 
- What was the expected result?
- What happenend instead?

Hello,
I am using Grafana and InfluxDB for reporting our Platform. 
I have to report some metrics like :  Number of New User daily , Number of Active Users Daily, Income Daily, .. etc
I used the Table for reporting it , something like : 

![selection_002](https://cloud.githubusercontent.com/assets/6456947/15527910/1b4532fe-2269-11e6-935d-9cd6a73bf7d5.png)

Now, I need a aggregation feature for each column at the end ( or the top) of this table  , for example : 
- Total Revenuef of This  Table Result, Column "Revenue"
- Total Number of  New User This  Table Result , Column "N1"
- Average Daily Active User  of This  Table Result, Column "A1"

Each Column has it's own defined  aggregation function ( or Disable) 
I appreciate for what you are doing.
Thank you

**Comment by TheOneValen** [comment]
This would be really useful. For example to make a sum over table rows in which rows were created by different queries.

**Comment by xelite** [comment]
+1

**Comment by dallasyo** [comment]
+1

**Comment by inselbuch** [comment]
+1

**Comment by maciejp** [comment]
I see it's marked as important but not assigned to anything so I'm not expecting it anytime soon.

Is there some hacky way to achieve this in the current version?

**Comment by mkkeffeler** [comment]
+1. Also looking for this.

**Comment by petertang2012** [comment]
+1 Is it possible to do script query for getting the aggregation column?

**Comment by stanwanghk** [comment]
+1

**Comment by jigpjames** [comment]
+1

**Comment by hudeldudel** [comment]
+1

**Comment by dannykopping** [comment]
For my use-case, I'd love a simple total of the `Value` column in the _Instant_ table query result; I find myself needing to calculate this value often.

![image](https://user-images.githubusercontent.com/373762/100447205-d88a7380-30b8-11eb-9fd0-cb5dd57867c8.png)

**Comment by mckn** [comment]
> For my use-case, I'd love a simple total of the `Value` column in the _Instant_ table query result; I find myself needing to calculate this value often.
> 
> ![image](https://user-images.githubusercontent.com/373762/100447205-d88a7380-30b8-11eb-9fd0-cb5dd57867c8.png)

In the scenario where you have a dashboard you can get this in place by doing the following:

1. Add a new panel with the targeted panel as the data source.

<img width="1227" alt="Skärmavbild 2020-12-02 kl  10 10 10" src="https://user-images.githubusercontent.com/172951/100852530-f1af6d80-3486-11eb-94b3-26ad04eda098.png">

2. Switch over to the transformation tab and add a reduce transformation.

<img width="1224" alt="Skärmavbild 2020-12-02 kl  10 10 01" src="https://user-images.githubusercontent.com/172951/100852587-fffd8980-3486-11eb-87b2-47d4aa39f59a.png">

3. You should end up with a result like the image below.

<img width="1227" alt="Skärmavbild 2020-12-02 kl  10 07 26" src="https://user-images.githubusercontent.com/172951/100852631-0f7cd280-3487-11eb-894b-cbe9b51d964d.png">

**Comment by amir-am** [comment]
+1

**Comment by cyh-ustc** [comment]
> > For my use-case, I'd love a simple total of the `Value` column in the _Instant_ table query result; I find myself needing to calculate this value often.
> > ![image](https://user-images.githubusercontent.com/373762/100447205-d88a7380-30b8-11eb-9fd0-cb5dd57867c8.png)
> 
> In the scenario where you have a dashboard you can get this in place by doing the following:
> 
> 1. Add a new panel with the targeted panel as the data source.
> 
> <img alt="Skärmavbild 2020-12-02 kl 10 10 10" width="1227" src="https://user-images.githubusercontent.com/172951/100852530-f1af6d80-3486-11eb-94b3-26ad04eda098.png">
> 
> 1. Switch over to the transformation tab and add a reduce transformation.
> 
> <img alt="Skärmavbild 2020-12-02 kl 10 10 01" width="1224" src="https://user-images.githubusercontent.com/172951/100852587-fffd8980-3486-11eb-87b2-47d4aa39f59a.png">
> 
> 1. You should end up with a result like the image below.
> 
> <img alt="Skärmavbild 2020-12-02 kl 10 10 17" width="817" src="https://user-images.githubusercontent.com/172951/100852773-3935f980-3487-11eb-9024-ccbf392de8fd.png">

when a filter applyed to a colum, the table rows  may be changed while the summarized result won't changed.

**Comment by mckn** [comment]
> > > For my use-case, I'd love a simple total of the `Value` column in the _Instant_ table query result; I find myself needing to calculate this value often.
> > > ![image](https://user-images.githubusercontent.com/373762/100447205-d88a7380-30b8-11eb-9fd0-cb5dd57867c8.png)
> > 
> > 
> > In the scenario where you have a dashboard you can get this in place by doing the following:
> > 
> > 1. Add a new panel with the targeted panel as the data source.
> > 
> > <img alt="Skärmavbild 2020-12-02 kl 10 10 10" width="1227" src="https://user-images.githubusercontent.com/172951/100852530-f1af6d80-3486-11eb-94b3-26ad04eda098.png">
> > 
> > 1. Switch over to the transformation tab and add a reduce transformation.
> > 
> > <img alt="Skärmavbild 2020-12-02 kl 10 10 01" width="1224" src="https://user-images.githubusercontent.com/172951/100852587-fffd8980-3486-11eb-87b2-47d4aa39f59a.png">
> > 
> > 1. You should end up with a result like the image below.
> > 
> > <img alt="Skärmavbild 2020-12-02 kl 10 10 17" width="817" src="https://user-images.githubusercontent.com/172951/100852773-3935f980-3487-11eb-9024-ccbf392de8fd.png">
> 
> when a filter applyed to a colum, the table rows may be changed while the summarized result won't changed.

Ah, you have a valid point. 

@torkelo @hugohaggmark what do you think about ad hoc filters? Should those be included in the data being transformed? Or maybe even applied as transformations?

**Comment by hugohaggmark** [comment]
@mckn not sure I follow, ad hoc filters operate on the data source level so the data transformed is already filtered.

**Comment by mckn** [comment]
Aha, totally forgot about how that worked - but what kind of filter other then the ad hoc can you apply in that view?

**Comment by hugohaggmark** [comment]
There are column filters in the new Table Panels, but those are transient. Reading the title of this issue and I think we recently added a Table Footer that aggregates data in the footer. Not sure that solves this issue though.

**Comment by jigpjames** [comment]
It sounds like aggregating Table Footers is what I need. Hope to be able to use that soon! THANK YOU!!

**Comment by hugohaggmark** [comment]
@jigpjames @mckn I was talking about this PR that should be released in Grafana 8.3 https://github.com/grafana/grafana/pull/38653. I think we could probably close this issue now?

**Comment by jigpjames** [comment]
Yes, I did find the PR and reviewed it. This should work nicely!! I also think we can close this issue.

**Comment by hugohaggmark** [comment]
Hi everyone seems like the "new" Table Panel now has support for aggregated values in the footer see #38653. Because of that we're going to close this issue but we'll reopen it if you think this is a mistake. Thank you 🙏
