### ISSUE TITLE
[Bug] template doesn't work well with datasource valiable

### ISSUE THREAD

**Issue by wyukawa** [grafana/grafana#5165]
- What Grafana version are you using?
3.0.3

- What datasource are you using?
prometheus

- What OS are you running grafana on?
CentOS6.6

- What did you do?
I want to create template with datasource valiable 

- What was the expected result?

I set the following.
![](https://gyazo.com/626db918bf2a7d7388fb635af7effb3d.png)

When I switch datasource valiable, aaa valiable changes automatically in dashbord.

Actually, it works in v3.0.1

- What happenend instead?

When I switch datasource valiable, aaa valiable doesn't change automatically in dashbord in v3.0.3.

**Comment by torkelo** [comment]
thanks for reporting this! fixed now and will be included in new patch release (will be released today)
