### ISSUE TITLE
NO option “Log Groups”  in Template variable “Query Type” with Data source “Cloudwatch”

### ISSUE THREAD

**Issue by wokwong** [grafana/grafana#51662]
**What happened**:
The template variable query function ->"Query Options"->in "Query Type" ，No option “Log Groups” (Data source is CloudWatch Logs).
![image](https://user-images.githubusercontent.com/47806459/176836594-25ee8df8-68f8-45eb-b92c-20d619e9c5e7.png)

**What you expected to happen**:
List the “Log Groups” option 。
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.2 (0641b5d0c)
- Data source type & version:  CloudWatch
- OS Grafana is installed on: CentOS 7
- User OS & Browser: Google Chrome
- Grafana plugins:
- Others:

**Comment by wokwong** [comment]
Thanks for your reply。
I want to see CloudWatch logs in Grafana Dashbord, for example, to see slow queries for AWS RDS MySQL。I want to set a variable to select the RDS instance。There are two options:
1. Like issue#50532, set the“Log Group prefix” , but there is no Log Group prefix option in my Variables. 
2. Get the RDS instance from Cloudwatch Metrics as a variable, and then reference the variable in Dashbord.  Can you do that? 

![image](https://user-images.githubusercontent.com/47806459/178198100-571b3fc6-8ae6-40eb-8210-1b64ab2346fb.png)

**Comment by iwysiu** [comment]
Hi @atartareanu , I've [backported ](https://github.com/grafana/grafana/pull/52898) the related commit and it should release in v9.0.6!
