### ISSUE TITLE
Geo Map 2 Queries Markers don't change size

### ISSUE THREAD

**Issue by BenHesketh21** [grafana/grafana#51669]
**What happened**:

When using the geo map type panel we want to change the size of markers based on a field. We have 2 queries and based on advice on the Grafana forum and other issues I have made a layer for each query. The problem is that the size based on the values isn't working with this set up, they are both showing as the same size. 

**What you expected to happen**:

The size should change based on the number coming through from both queries.

**How to reproduce it (as minimally and precisely as possible)**:

Have 2 queries giving long, lat and a number. Create 2 layers, one for each query and then concatenate the fields. Set up both layers to change size based on the number given. If the queries give different numbers, you should see the markers remain the same size.

**Comment by joshhunt** [comment]
You should be able to use the Merge or Outer Join transformations to merge your two queries into one data table, and then configure the Geo map appropriately with your size value. See [this dashboard](https://play.grafana.org/d/XfazlSenk/51669?orgId=1&editPanel=2&tab=transform) for an example.

**Comment by mellieA** [comment]
@BenHesketh21 we haven't heard back on this issue, I hope that joshhunt's suggestion resolved this for you. If you think this is a bug, feel free to reopen. Otherwise, for more consultative help - please post your question in our community at [community.grafana.com](https://community.grafana.com/)

**Comment by motogutzi** [comment]
Hi

i think the bug is still there. Even in the given example.
For example if you change the value of foo, the circle diameter of beep is changing.

On the other hand when using the size values for rotation; this works totally fine. For size is does not.
