### ISSUE TITLE
Bar Chart: "soft minimum" can't be removed: Setting axis "minimum" to negative does not take effect*

### ISSUE THREAD

**Issue by JValtteri** [grafana/grafana#51675]
**What happened**:

I set the ***Bar Chart (beta)*** **axis minumum** to **-5**. 
--> it did not take effect. 

![image](https://user-images.githubusercontent.com/46611993/177000256-8ad5f94f-a228-40b8-add3-c15674130c5f.png)
![image](https://user-images.githubusercontent.com/46611993/177001350-bcbafca0-045d-4151-a2e1-2779a508538d.png)
**What you expected to happen**:

Bar chart axis minimum to be -5 
(as the maximum is+5, as set)

**How to reproduce it (as minimally and precisely as possible)**:

- Make a new **Bar Chart (Beta)**
- Set axis minimum that is  **lower than the ***minimum value*** of the current query**. 
![image](https://user-images.githubusercontent.com/46611993/176999724-98139ed3-c696-428c-9781-4a7cb3d9e3e6.png)
![image](https://user-images.githubusercontent.com/46611993/176999920-03b4eecc-186b-4128-af2c-ac14c296bcb2.png)

**Anything else we need to know?**:

**Bar Chart (beta)** seems to have a default **soft minimum** of **0**. Removing it has **no effect**. Only setting it as negative, will "solve" the issue. I, however am not aware of an option to set it as **negative infinity**.

This behavior differs from all the Grafana visualizations I've used so far.

**Environment**:
- Grafana version: 9.0.2 (0641b5d0cd)
- Data source type & version: InfluxDB 1.8.0
- OS Grafana is installed on: (official Grafana docker image: grafana/grafana:latest)
- User OS & Browser: WIndows 10, Firefox 102.0
- Grafana plugins: None
- Others: None

**Comment by joshhunt** [comment]
Reproduced this on play https://play.grafana.org/d/fiiAZS67z/51675-bar-chart-negative-minimum-value?orgId=1

The Bar Chart does not appear to respect a negative minimum value, but it will respect a negative _soft_ minimum value. It doesn't appear that Time Series has this issue.

**Comment by dprokop** [comment]
It's because of the default soft mi set here: https://github.com/grafana/grafana/blob/main/public/app/plugins/panel/barchart/models.gen.ts#L48 

@leeoniya any clues why the default is set there?

**Comment by leeoniya** [comment]
i think it's there to avoid making barcharts that dont start at 0, a famously common criticism :D

a softMin of 0 shouldnt prevent a _smaller_ min from taking effect tho. will take a look tomorrow (holiday today).
