### ISSUE TITLE
[Bug] All format "wildcard" no longer honoured in Grafana 3

### ISSUE THREAD

**Issue by zachd** [grafana/grafana#5169]
Hi there, we're running into a problem on Grafana 3.0.4 where dashboards that contain template variables with the setting `allFormat: wildcard` are no longer using `*` as the all format, but glob instead. 

I understand that the all value can now be set, like `allValue: *` (see screenshot), but is there a way that this could be made backwards compatible with all current dashboards, so the wildcard setting is not being overridden with glob?

![image](https://cloud.githubusercontent.com/assets/1366937/15538641/6532e508-2275-11e6-93e9-c72f69ba1797.png)

It's not ideal to set the all value of every template variable that previously had the format set to wildcard. Maybe a dashboard schema migration would be suitable, or a change in templateValuesSrv to honour the old setting?

Thanks,
A Hosted Graphite employee.

**Comment by torkelo** [comment]
strange, cannot replicate this. Did you click the Update button? (in template variable options)

![image](https://cloud.githubusercontent.com/assets/10999/15537924/5afd4408-2279-11e6-9262-43e68d5a8dd5.png)

The query sent to graphite is using the wildcard.
![image](https://cloud.githubusercontent.com/assets/10999/15537943/73dcd1e6-2279-11e6-9d6d-255ca6f49277.png)

**Comment by zachd** [comment]
Steps to reproduce:

1. Create dashboard with a templated variable query (Graphite), and select `Include All` option, and leave `Custom All Value` blank.
2. Create a graph panel using the templated variable above.
3. Save dashboard. Export to file.
4. Open JSON and add `"allFormat": "wildcard",` to first element in templating->list array. 
![image](https://cloud.githubusercontent.com/assets/1366937/15538433/2005080e-2274-11e6-8f9f-ea76b9ba20da.png)
5. Import JSON to new dashboard.
6. Go to templated variable, and click Update button. 
7. Look at Graphite query, shows glob instead of wildcard as set in the allFormat. ![image](https://cloud.githubusercontent.com/assets/1366937/15538427/0c63698a-2274-11e6-8930-5bc3210c3efb.png)

**Comment by zachd** [comment]
Another example which might be easier for you to reproduce. Using "Templated Graphs Nested" on play.grafana.org:
![image](https://cloud.githubusercontent.com/assets/1366937/15538779/223f7580-2276-11e6-9783-fe55edacacd2.png)

**Comment by torkelo** [comment]
> leave Custom All Value blank.
Why ? Thought you wanted a `*` wildcard here.

> Open JSON and add "allFormat": "wildcard", to first element in templating->list array.
There is no such option anymore.

**Comment by zachd** [comment]
The problem is that any current dashboard that was previously using the `allFormat: wildcard` (like the play.grafana.org one above) is forced to use glob, regardless of whether it previously specified an all format. Should this not be made backwards compatible with dashboard schema pre-grafana 3?
