### ISSUE TITLE
Don't trigger query automatically when switching datasource

### ISSUE THREAD

**Issue by dannykopping** [grafana/grafana#51708]
**What happened**:

When switching from one datasource to another, a query is triggered automatically.

**What you expected to happen**:

Switch datasources and maintain the labels (which is super helpful), but don't trigger a query when switching.

**How to reproduce it (as minimally and precisely as possible)**:

When using a Loki datasource and then changing to a Prometheus datasource (for example), the label selectors are maintained:

LogQL:
```logql
{cluster="us-east1"} |= `something`
```

=> PromQL after switch:
```promql
{cluster="us-east1"}
```

Note that this is a valid Prometheus query, however it's potentially extremely expensive because it tries to match **every metric stream which matches those labels**.

**Anything else we need to know?**:

**Environment**: k8s
- Grafana version: v9.1.0-571e69bcpre (571e69bcc)
- Data source type & version: LogQL / PromQL
- OS Grafana is installed on: Linux
- User OS & Browser: Google Chrome
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
When you switch data sources (...to a different type?) it _should_ clear the query out completely, right? @torkelo I think i recall you mentioning something about this earlier? Is Loki -> Prometheus doing something special here?

**Comment by dannykopping** [comment]
> When you switch data sources (...to a different type?) it _should_ clear the query out completely, right? @torkelo I think i recall you mentioning something about this earlier? Is Loki -> Prometheus doing something special here?

I believe it does. It tries to maintain the labelset between the two datasources. This is great, but triggering a query automatically is not.

**Comment by gelicia** [comment]
We are going to continue this discussion as a more broad topic in #51979
