### ISSUE TITLE
[Grafana 8.4.4]   Losing/Disappearing  all contact points/notification policies few times a day.

### ISSUE THREAD

**Issue by tahchiev** [grafana/grafana#51716]
[Grafana 8.4.4]  When Grafana pod is restarted on EKS cluster we are losing all contact points/notification policies. Does you know where they are stored? grafana.db? or some other place i was searching for it but no luck. Also checked in they are in the external alertnamager config but not trace of them. So if i know where it is i can mount it to nfs pv so each time when restart to be there?
Thanks in advance.

**Comment by tahchiev** [comment]
Today contact point and notification policies are missing again and grafana pod or others haven't been restarted....very strange.

**Comment by joeblubaugh** [comment]
Hi - as you've found, contact points and notification policies are stored in the Grafana SQL database as part of the `alert_configuration` table's object. The configuration that is applied is the row with the highest `id`. You can see what is stored there - contact points are the `receivers` array and notification policies in the `route` object.

I think that the validation failure means that the internal alertmanager is never able to apply the configuration, hence why you see no notification policies or contact points in the UI. I don't think the error is from a missing UID. It looks like the #kubernetes receiver configuration isn't validating.

Can I ask how you created the Slack contact point initially? `WebhookURL` is not a field that we check when loading a Slack contact point - we check the `url` field of the configuration. If the `url` field is set, we send messages to that URL - this is usually how people use webhooks with Slack like I think you want to. If it's *not* set, we default to the Slack chat API endpoint, and for that endpoint to work you need both a `recipient` and a `token`. The code is here: https://github.com/grafana/grafana/blob/a438073e3a93f7b9f9eaa47274ef794cd255e3b1/pkg/services/ngalert/notifier/channels/slack.go#L82

For a quick fix, I think you can simply change the `WebhookURL` field to `url` in your configuration - I'd like to get the context though, so we can figure out if there are fixes we need to make in Grafana. 

Alerting rules are stored in the `alert_rule` table, so you may see them even if the alert_configuration fails to load.

**Comment by tahchiev** [comment]
Thanks, i will test it but it is a workaround for me. When contact points and notification policies disappear to try to apply saved configuration. **I think bigger issues is why when i apply configuration manually from the GUI after some time only contact points/notification policies disappear , alerts are there...** 
Currently i have mounted only   /var/lib/grafana to nfs...i my try to mount grafana.db ,too but i doubt it will help.
<html>
<body>


- mountPath: /var/lib/grafana
--
86 | name: grafana-volume


</body>
</html>

**Comment by joeblubaugh** [comment]
The reason alerts remain is that alerting rules are not part of the alert_configuration object. The alert_configuration object contains information about "how to deliver alerts", including contact points and notification policies. Alerting rules are stored in their own database table, so problems with that alert_configuration object won't affect them.

I don't think there is any data going missing, only that some data validation is failing and therefor the alert delivery configuration isn't applied.

**Comment by tahchiev** [comment]
Hi,Joe!
if it is like you said "data validation is failing " , why when i apply configuration manually it works, next day when i connect i see them missing? i may be wrong but if it is validation issue it would have appeared when i configure them manually via the gui- not to allow me or give errors. But if it is a validation issue how can i fix it permanently ?

**Comment by tahchiev** [comment]
Today around noon again configuration disappear...tried to narrow search inside the logs with debug...and i saw two interesting things...
First is that Alertmanager cannot load its configuration? why it needs to load it anyway...

2022-07-06 13:19:09	
logger=ngalert.multiorg.alertmanager t=2022-07-06T10:19:09.73+0000 lvl=eror msg="failed to load Alertmanager configurations" err="database is locked"

Second is a little bit later notification manager is restarted ...so may be at this point it is losing contact points and notification policies ...

2022-07-06 13:19:16	
logger=ngalert t=2022-07-06T10:19:16.63+0000 lvl=info msg="stopped sender" org=1
2022-07-06 13:19:16	
logger=sender level=info msg="Stopping notification manager..."

![image](https://user-images.githubusercontent.com/103194805/177550798-96a775e5-816d-4c88-9c84-9ededd437243.png)

**Comment by joeblubaugh** [comment]
The log shows a lot "database is locked" messages. See this forum post: https://community.grafana.com/t/database-is-locked-unable-to-use-grafana-anymore/16557/2

Alertmanager periodically reloads its configuration because the configuration can be changed in the database by another process - for example, two or more Grafana instances running in high-availability mode.

The alertmanager configuration is written into the grafana database, so if it's unable to write it then it will also be unable to load it later - that definitely explains the issues after restart.

"Stopping sender" is called at the [end of the alertmanager synchronization process](https://github.com/grafana/grafana/blob/fcfb01faebb9f1e91fa465ec5f3399560abcfb8b/pkg/services/ngalert/schedule/schedule.go#L291)

My next recommendation would be to try and repair the SQLite database as mentioned in the forum post.

**Comment by tahchiev** [comment]
Issue fixed after after migration to posgresql database. No sqlite repair helped.

**Comment by joeblubaugh** [comment]
Thanks for your patience and walking through all of that with me.

**Comment by bertrandp** [comment]
I faced the same issue. For the second time.
@joeblubaugh does it mean sqlite is not suitable for production use of grafana 8 alerts ?
