### ISSUE TITLE
Variables can't be loaded from a Query when data source is Postgresql (TimescaleDB)

### ISSUE THREAD

**Issue by dmilith** [grafana/grafana#51723]
Steps to reproduce:
List the minimal actions needed to reproduce the behavior.

My data source: TimescaleDB 2.6.1 (on Postgresql 13.7)

On 7.5.15 I read my hosts list like this: https://s.verknowsys.com/b1a573d4618e3c2889a800ee90ac3a50.png

The preview shows valid hosts from my home server room.
After I upgrade to Grafana 8 or 9, the same query shows nothing, and it's impossible to do a proper query.

Expected behavior:
Well, it should fetch the hosts.

Actual behavior:
It does work only with InfluxDB, but not with TimescaleDB

Environment info:

    System info: FreeBSD 13.1-RELEASE arm64, FreeBSD 13.1-RELEASE amd64
    InfluxDB version: None, but working one is latest 1.8.10
    Other relevant environment details: Postgresql 13.7 with TimescaleDB 2.6.1

**Comment by joshhunt** [comment]
Tested with Grafana 9.0.2 and Postgres 9.3, I was unable to replicate this.


![image](https://user-images.githubusercontent.com/46142/177307374-952d90fe-d264-4b5e-b4bf-5fa5af83ae54.png)

What data is your query returning? Can you confirm it returns rows in Explore or in a Dashboard panel?

**Comment by dmilith** [comment]
Oh, thanks for pointing out that missing "distinct" :) It worked before with missing "distinct" in Grafana 7.5… Anyway, it works now, thanks again.
