### ISSUE TITLE
[Bug] templating nested variable value All is displayed incorrectly as $_all

### ISSUE THREAD

**Issue by decentlab** [grafana/grafana#5172]
Grafana version: 5040570ea9ec96d8577af50324272afcbdd1e534
Datasource: InfluxDB
OS: Docker image

I created a templated dashboard with repeating panels and nested variables.
When I change the parent variable, the nested variable value in the dropdown list is displayed as `$__all` instead of `All`.
This affects refreshing the panels properly.

I suspect that this is introduced with 6f094ef215261bcf0c44313a74e299c2cb1e4856.
![screen recording mov](https://cloud.githubusercontent.com/assets/17007399/15546749/67aaf59c-22a1-11e6-85a8-f3ff1f2bc8e0.gif)

**Comment by torkelo** [comment]
I saw this once when I did the last fix for template variables. But never managed to replicate it. Tested a bunch now but never get this. Can you reliably replicate this?

**Comment by marcoc610** [comment]
I have a similar issue, but in a simpler case. How do I reproduce it:

- Templating with a variable coming from a Graphite query with refresh "on dashboard load" or " on time change".
- Save the dashboard with "All" selected.
- Reload the dashboard.

The menu shows "<Variable Name>: $__all" and in the dashboard any templated content is not displayed properly (for example graphs are there, but empty and not repeated)
If I open the menu and click on the label "All", the dashboard reloads properly with all content.

**Comment by decentlab** [comment]
I confirm that I have more or less same scenario as @marcoc610. But with InfluxDB and refresh "on dashboard load".

**Comment by torkelo** [comment]
yes, was able to replicate it now with the refresh "On Dashboard load" option set

**Comment by marcoc610** [comment]
It happens also if the variable is loaded by an Elasticsearch query.

**Comment by decentlab** [comment]
The commit fixes the issue nicely. But this introduces another similar issue with Interval template variable. This happens with no special settings, just an interval template variable.

<img src="https://cloud.githubusercontent.com/assets/17007399/15574529/2fde97a6-234e-11e6-9da9-58330a6e7b8d.gif" width="400">
