### ISSUE TITLE
Alerts broken after upgrading to v9

### ISSUE THREAD

**Issue by emexelem** [grafana/grafana#51735]
**What happened**:
I've just upgraded Grafana from v8 to v9 (.0.2) and started to get alerts from old / deprecated dashboards. I've deleted the dashboards or even the org, but i still get alerts from these. I've tried to restart Grafana service after deleting these resources, thinking of a caching issue, but it did not help, i still get these alerts and i don't have any way to delete them.

I just browsed other dashboards having alerts and i see the alert thresholds in the graph, but the alert panel is completely empty, as if there was no alert defined there.

It seems there's a global issue to display alerts with v9, it seems there are running in the background and sending notifications, but somehow they cannot be displayed in the UI.

Not sure if there's any specific migration task to perform following upgrade to v9?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: InfluxDB
- OS Grafana is installed on: running as docker image
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by emexelem** [comment]
One small complement:
When i click on "go to dashboard", or panel, or source in the alert email, i get a "not found" error in Grafana.
But still those "not found" alerts get triggered...

**Comment by JohnnyQQQQ** [comment]
With Grafana 9, we removed the direct relationship between Dashboards and Alerts. So deleting a Dashboard in Grafana 9 won't delete any alert. 

If you could provide us with screenshots of your Alerts and of your silencing configuration, we could perhaps tell you more about the issues you are facing with silencing.
