### ISSUE TITLE
Import Graphite to Grafana

### ISSUE THREAD

**Issue by dnayyl** [grafana/grafana#5173]
I am uploading data to Graphite via carbon and graphite-weewx extension:(https://github.com/ampledata/weewx_graphite), and then import graphite to grafana. Data uploaded via Carbon can be fully represent at Grafana, but data upload from Graphit-weewx can only be showed at Today so far, it wont show any data in "For the Lat seven days", or "Last X hours". 

Has anyone met similar issues?

**Comment by torkelo** [comment]
strange, better ask https://github.com/ampledata/weewx_graphite , sounds like a whisper storage issue
