### ISSUE TITLE
Grafana 8.5: Graphs are blurry compared to 7.5

### ISSUE THREAD

**Issue by RedShift1** [grafana/grafana#51737]
Grafana 8.5's graphs are blurrier compared to 7.5. This happens with the old graph panel and the new timeseries panel.

**What happened**:
### Grafana 8.5:
**Complete chart:**
![image](https://user-images.githubusercontent.com/3098010/177313674-26fc2759-0a57-4817-92f2-a4e16943de78.png)
**Gridlines:**
Notice how there's an extra very light gray pixel to the horizontal grid lines that are not there in Grafana 7.5
![image](https://user-images.githubusercontent.com/3098010/177313759-8b1f2617-143b-438b-bf50-8cb107a0f6b0.png)
![image](https://user-images.githubusercontent.com/3098010/177314510-8304b8dc-029c-42d9-82c4-72505dfd0f56.png)
**Line:**
The line overall is made out of more lightly colored pixels and doesn't have the sharp edge at the bottom (where the line goes back up) compared to Grafana 7.5
![image](https://user-images.githubusercontent.com/3098010/177314037-7c557258-b757-4ab5-a6cc-46f78a998193.png)
![image](https://user-images.githubusercontent.com/3098010/177314124-caedf688-b4f3-46ef-81f8-87498d2e9f8c.png)

### Grafana 7.5:
**Complete chart:**
![image](https://user-images.githubusercontent.com/3098010/177313701-ea82ddcb-7638-42c2-b24e-15b5c3fd435a.png)
**Gridlines:**
![image](https://user-images.githubusercontent.com/3098010/177313906-0e95302b-d462-4c98-a899-94955557e577.png)
![image](https://user-images.githubusercontent.com/3098010/177314401-35ee7d95-1973-4af6-8df8-c3d6acca7cf7.png)
**Line:**
![image](https://user-images.githubusercontent.com/3098010/177314015-f2c075ae-d206-49ef-b3d8-868c847d6f9e.png)
![image](https://user-images.githubusercontent.com/3098010/177314174-79503731-9940-46f4-852e-3e4afb30c775.png)

**Environment**:
- Grafana version: 7.5.11 and 8.5.6
- Data source type & version: PostgreSQL 12
- OS Grafana is installed on: AlmaLinux 8.6
- User OS & Browser: Windows 10 Pro 21H1 & Chrome 103.0.5060.66 (Official Build) (64-bit)

It looks like the canvas coordinates are off by half a pixel or something, causing everything to become blurry.

**Comment by joshhunt** [comment]
What resolution and display scaling factor are you running at? For me on Win 11, Chrome 103.0.5060.66, 3440x1440 100% display scaling, I get clean 1px grid lines with the time series panel.

![image](https://user-images.githubusercontent.com/46142/177342437-4f77f346-226b-4411-a241-80e8f2e6a571.png)

Is your browser zoomed in?

**Comment by RedShift1** [comment]
> What resolution and display scaling factor are you running at? For me on Win 11, Chrome 103.0.5060.66, 3440x1440 100% display scaling, I get clean 1px grid lines with the time series panel.
>
> Is your browser zoomed in?

Display is 1920x1200, scaling factor 100%, zoom 100%. So everything should be pixel perfect.

Investigating this some more, it doesn't appear to be happening all the time, however I can reproduce it reliably by toggling between "Fill" and "Actual" when editing the panel:

Set to "Fill", pixel perfect:
![image](https://user-images.githubusercontent.com/3098010/177344711-102914f0-137f-403c-bb89-c84061269742.png)

Set to "Actual", blurry (notice the extra pixels around the vertical gridlines now):
![image](https://user-images.githubusercontent.com/3098010/177344651-140fccfb-068c-4b94-9cbe-84954647bca7.png)

**Comment by RedShift1** [comment]
It also happens with the new "Time series" panel:

"Actual":
![image](https://user-images.githubusercontent.com/3098010/177345786-574fe500-73f1-441b-8cbc-4f4c9d9b3bcb.png)

"Fill":
![image](https://user-images.githubusercontent.com/3098010/177345937-52336237-42fd-49e7-a9f2-3ea1eca0c616.png)

**Comment by leeoniya** [comment]
@RedShift1 do you get `1` when running `devicePixelRatio` in your devtools console?

![image](https://user-images.githubusercontent.com/43234/177351160-c512c4ae-f9ce-406a-ba23-9d8cc658c87e.png)

we have not touched rendering aspects in Graph (old) for several years, so the fact that it behaves differently in 7.5 vs 8.5 is quite surprising.

in the Time series panel, there is some logic for pixel rounding when drawing horizontal and vertical gridlines, but that's not something that can be done for arbitrary diagonal lines that will always get anti-aliased in some unpredictable way by the browser based on canvas position, sizing, and data coords.

can you check if you have similar grid anti-aliasing issues with any of the demos here?

https://leeoniya.github.io/uPlot/demos/index.html

something that could potentially cause this is fractional pixel dimensions (we should be rounding this), but i'm only able to see this in the width:

![image](https://user-images.githubusercontent.com/43234/177355794-755cda28-7245-4a1a-873e-cc56b66dbda6.png)

**Comment by RedShift1** [comment]
> @RedShift1 do you get `1` when running `devicePixelRatio` in your devtools console?

Yes:

![image](https://user-images.githubusercontent.com/3098010/177386848-8dbe3316-f386-4379-8336-539e051dc63e.png)


> we have not touched rendering aspects in Graph (old) for several years, so the fact that it behaves differently in 7.5 vs 8.5 is quite surprising.
> 
> in the Time series panel, there is some logic for pixel rounding when drawing horizontal and vertical gridlines, but that's not something that can be done for arbitrary diagonal lines that will always get anti-aliased in some unpredictable way by the browser based on canvas position, sizing, and data coords.
> 
> can you check if you have similar grid anti-aliasing issues with any of the demos here?
> 
> https://leeoniya.github.io/uPlot/demos/index.html
> 

No issues there, even the junk charts render perfectly.

**Comment by leeoniya** [comment]
i'm able to reproduce this in some circumstances, but still cannot narrow down the reduced set of conditions necessary to look into a fix :(

**Comment by jasonacox** [comment]
I know this is an older issue, but I see something similar between "old time series" graphs and the "new time series" graphs - when you convert it appears to change the color of the grid lines. It is much harder to see the gridlines in the  new ts graph:

Old TS:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/836718/194211180-73ff1e26-b247-4d71-8ec0-52260533a19a.png">

New TS: 
<img width="542" alt="image" src="https://user-images.githubusercontent.com/836718/194211238-a8ac5013-16bd-4a7a-bf48-b2c1cc1299f4.png">

I didn't find any user control to adjust the color of the gridlines but did see that there appears to be a hardcoded #c8c8c8 as part of this commit: https://github.com/grafana/grafana/commit/1daa0dfe653002dff991f607db38f22ba314f3af

Could we make the gridColor a user editable value or could it be that the color is the same and the pixel rounding is causing the grid to fade?  I would like the option to 'unfade' if that were possible. 😁  

Thanks for a great project!  ❤️  Grafana.

**Comment by leeoniya** [comment]
@jasonacox that's unrelated to this issue. please open a new feature request in https://github.com/grafana/grafana/discussions for styling changes.
