### ISSUE TITLE
Adhoc variable: incorrectly added to query when query contains dashboard variable

### ISSUE THREAD

**Issue by afirth** [grafana/grafana#51743]
**What happened**:
Query 
```
alertmanager_notification_requests_total > $A
```
is incorrectly expanded to
```
expr:"alertmanager_notification_requests_total{environment=~\"dev\"} > 99{environment=~\"dev\"}"
```
when dashboard variable `$A` is `99` and adhoc filter `environment =~ "dev"` is set

**What you expected to happen**:

Query should expand to `expr:"alertmanager_notification_requests_total{environment=~\"dev\"} > 99` (as it does when `$A` is not used, but `99` hardcoded in the query)

**How to reproduce it (as minimally and precisely as possible)**:

Set a dashboard variable of constant or custom type, and another adhoc filter. Use the dasboard variable in the query and notice that the adhoc filter is added too.

Here's another example:

Query
```
(($SLO-100)
    * sum( 
        rate(nginx_ingress_controller_requests{controller_pod=~"$controller",controller_class=~"$controller_class",namespace=~"$namespace",status=~"[25].."}[$SLO_span])
    )
)
```
Error
```
bad_data: 7:9: parse error: unexpected "{"
```
Expanded query
```
expr:"
((99{environment=~\"dev\"}-100)  ###<<<< ERROR HERE
    * sum(
        rate(nginx_ingress_controller_requests{controller_pod=~\".*\", controller_class=~\".*\", namespace=~\".*\", status=~\"[25]..\", environment=~\"dev\"}[7d])
    )
)
"
```

**Anything else we need to know?**:
Based on my very limited knowledge, I suspect the issue is that other variables are not expanded before the adhoc regexs are parsed.

**Environment**:
- Grafana version: 9.0.1
- Data source type & version: prometheus
- OS Grafana is installed on: linux
- User OS & Browser: chrome/linux
- Grafana plugins: n/a
- Others: n/a

**Comment by mellieA** [comment]
Confirmed this behavior still exists on 9.1.0, the ad-hoc filter appended to the end of constant template variable. The problem causing the query error is only visible in the inspect query pane: 

`expr:"grafanacloud_instance_alertmanager_alerts{org_name=\"meloriarellano\"} > 99{org_name=\"meloriarellano\"}"`

**Comment by barcus** [comment]
Hello, same issue here, using simple textbox variable to define a threshold, which finally contains the value + k/v of the ad-hoc filter
looks like this:
`indexing_size{domain="domain1"} >  100{domain="domain1"}`
