### ISSUE TITLE
[Bug] $tag_tagname substitution not working with with tag names containing dashes

### ISSUE THREAD

**Issue by dwo** [grafana/grafana#5174]
>What Grafana version are you using?

2.6.0

> What datasource are you using?

OpenTSDB

> What OS are you running grafana on?

I'm observing this in Firefox 47b6 on Mac OS X 10.11.5 (Grafana itself is on Linux)

> What did you do?

I queried an OpenTSDB metric with a tag like `foo-bar=*` and added `$tag_foo-bar` in the Alias field.

> What was the expected result?

For the various values of the `foo-bar` tag to be substituted into the legend.

> What happenend instead?

The legend displays `$tag_foo-bar` as is for each of the graphed lines in the Legend.

I confirmed that this bug doesn't happen for a non-dashed tag for the same metric. I haven't tried this against Grafana 3.0 yet.

![grafana - tag_tagname bug](https://cloud.githubusercontent.com/assets/131652/15549514/c8d6e2e2-22a4-11e6-85af-763b369274b6.png)

**Comment by dwo** [comment]
We reproduced this on Grafana 3.0.4 too.

**Comment by johnewing1** [comment]
As a work around you can use [[tag_foo-bar]]

**Comment by utkarshcmu** [comment]
We should fix this though. I use underscores so never encountered this issue. :(

**Comment by torkelo** [comment]
the $varname syntax does not support dashes. The regex for interpolating template vars using the $varname syntax is using the `\w` word character class.  A dash `-` is not part of that character class, I cannot change this now as that would break things for current users who expect things like:

 `my.$env-$group.*` to work.

So if you have dashes use the `[[var_tag]]` syntax

**Comment by dwo** [comment]
How about mentioning this alternate syntax in the "Alias (?)" tooltip? We only found the work-around after looking at the source.

**Comment by torkelo** [comment]
@dwo it is there in the alias help!
![image](https://cloud.githubusercontent.com/assets/10999/15568237/1697b6c4-232b-11e6-982c-9b713a9fd83a.png)

**Comment by dwo** [comment]
I'm not sure where to find that help (in 2.6.0 at least, maybe 3.0.x's interface is better?). I was referring to the tooltip here in 2.6.0 when adding OpenTSDB metrics:

<img width="1217" alt="screen shot 2016-05-26 at 9 40 13 am" src="https://cloud.githubusercontent.com/assets/131652/15568887/2524b96c-2326-11e6-826a-2ecbb23171a4.png">

If the tooltip had read "Use patterns like $tag_tagname **or [[tag_tagname]]**", I would have succeeded in what I was trying to do. Like I said, maybe 3.0's interface already improved on this and my point is moot.

**Comment by torkelo** [comment]
ah,I thought it was InfluxDB that was being used  (they have the same tag aliasing )

**Comment by truongkhanh** [comment]
If we use `[[tag_hostname]]`, the alert will not be able to resolved. It will show something like
```
message:"Condition[1]: Eval: false, Metric: [[tag_hostname]], Value: 398.514"
data:null
```
