### ISSUE TITLE
[Feature Request] Add instructions on /plugins for installing new plugins

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#5176]
There is a link to the grafana.net plugins repo from the plugin list panel on the home dashboard (if no plugins for a given category are installed already), but when using the main Plugins list (at /plugins) there is no indication to the user of what they should do if they want to install more plugins.

We should add a section there explaining that it's a list of the currently-installed plugins and letting the user know how they can find and install new plugins via https://grafana.net/plugins

**Comment by torkelo** [comment]
good idea!

**Comment by torkelo** [comment]
![image](https://cloud.githubusercontent.com/assets/10999/18743163/163282b4-80b8-11e6-8631-ff44aef34bf3.png)

Added a (currently installed) info text to the header. And we added the link to Grafana.net to this page as well.
