### ISSUE TITLE
GLDS-Color Token Documentation

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#51766]
We need to audit how we are leveraging color within Grafana to dictate particular system feedback to the users. Not only does color explicitly inform users of system statuses but it also carries _tone_. Grafana's color system needs to consistently represent system status and tone to the users.

**Tone Example**
https://seek-oss.github.io/braid-design-system/foundations/tones/

**Ideal file structure**
https://github.com/carbon-design-system/carbon/blob/main/packages/colors/src/colors.js

**Goal**
- Improve usability of our colors
- Reduce color duplicates
- Provide concise, semantic structure to our tokens for clarity of use
- Produce a token structure that makes theming Grafana more feasible

**Comment by staton-hyse11** [comment]
[Google Sheet](https://docs.google.com/spreadsheets/d/1ACSjHl0uFSYUBTdU5G-YmjTHBmr8Sc--lJlNSPNuLQ4/edit?pli=1#gid=634405159) for exploration of current color usage and storage.

**Update**
I consolidated the color values and organized by HEX/RGBA and I removed duplicates (except for colors with transparencies)

**Comment by Aires-Grafana** [comment]
This issue can be closed as it is being covered at #78865
