### ISSUE TITLE
Infinity for threshold results in malformed list state

### ISSUE THREAD

**Issue by AsumFace** [grafana/grafana#51770]
**What happened**:
Producing infinities for thresholds creates additional irremovable "Base" entries. If there are two or more "Base" entries and the topmost is "Base", all newly added entries are automatically "Base" as well. Since "Base" has no button for removal, there is no immediate obvious way to recover from this. It can be recovered from by saving the dashboard and reopening it.

**What you expected to happen**:
Such values should probably be either rejected or rounded to the nearest finite number. It should not be possible to produce additional "Base" entries.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new Panel
2. Choose "Stat" for visualization; others like the gauge work too
3. In the options sidepanel, go down to "Thresholds"
4. Change the predefined value 80 to anything that will be rounded to either positive or negative infinity, like 9e999
5. Find that the thresholds menu has become useless

**Anything else we need to know?**:
\-

**Environment**:
- Grafana version:
   v9.0.2 (0641b5d0c)
- Data source type & version:
    Postgresql 14
- OS Grafana is installed on:
    Fedora 35
- User OS & Browser:
    Gentoo Linux, Firefox 100.0
- Grafana plugins:
- Others:

**Comment by AsumFace** [comment]
I have now quickly checked if it's browser-specific, and indeed, it only happens in Firefox, but not Chrome.

**Comment by joshhunt** [comment]
Strange - I swear I tested Firefox, but I now see that entering a threshold of `9e999` gets parsed to Infinity which is the value we use for "Base". Thanks for the information!

![2561_2022-07-07-09-40_firefox](https://user-images.githubusercontent.com/46142/177730879-e51ad383-6658-4882-b2e1-0eb5662c214f.png)
