### ISSUE TITLE
[Bug] Table Panel Showcase is missing from play.grafana.org

### ISSUE THREAD

**Issue by DanCech** [grafana/grafana#5177]
The [Table Panel Showcase](http://play.grafana.org/dashboard/db/table-panel-showcase) dashboard referred to in [the grafana documentation](http://docs.grafana.org/reference/table_panel/) and [table panel README](https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/table/README.md) is missing from play.grafana.org and needs to be recreated.

**Comment by torkelo** [comment]
good catch, it was named http://play.grafana.org/dashboard/db/new-features-in-v2-6 , created a copy with Table Panel Showcase name so the links works
