### ISSUE TITLE
[BUG] Image generation broken since 3.0.4 update

### ISSUE THREAD

**Issue by xf-** [grafana/grafana#5178]
- What Grafana version are you using?
3.0.3 - downgrade from 3.0.4
- What datasource are you using?
graphite
- What OS are you running grafana on?
Ubuntu
- What did you do?
update
- What was the expected result?
Get a image with graph
- What happenend instead?
Get a white image (PNG)

Typo in happenend

**Comment by torkelo** [comment]
I am unable to replicate this, the panel rendering works fine here. 

Anything interesting in your grafana.log file?

**Comment by xf-** [comment]
hi,

log of phantomjs
> 2016/05/25 23:04:29 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/all-nodes?panelId=1&from=now-7d&var-nodeid=6372513a81b3&var-host=name&width=650&height=350&theme=light
2016/05/25 23:04:29 [I] PhantomRenderer::renderToPng url http://localhost:3000/dashboard-solo/db/all-nodes?panelId=2&from=now-7d&var-nodeid=6372513a81b3&var-host=name&width=650&height=350&theme=light
2016/05/25 23:04:30 [I] Completed [::1] - "GET /metrics/find HTTP/1.1" 500 Internal Server Error 0 bytes in 274745us
2016/05/25 23:04:30 [I] Completed [::1] - "GET /metrics/find HTTP/1.1" 500 Internal Server Error 0 bytes in 270753us

**Comment by torkelo** [comment]
Very strange.  What's you datasource settings? Especially URL and access mode, is that accessible from the grafana server?

**Comment by xf-** [comment]
markdown removed my answers to questions
Normal frontend and embed works as expected.

graphite api is accessible for grafana throw a gunicorn server

**Comment by torkelo** [comment]
?
