### ISSUE TITLE
JWT: Add support for assigning org roles

### ISSUE THREAD

**Issue by Jguer** [grafana/grafana#51783]
Implement org role mapping for JWT Authentication.

Approach:

- `role_attribute_path` config setting similar to the one present in oauth (generic, github, gitlab)

**Comment by nrwiersma** [comment]
I was just looking for a feature in JWT that operated like `role_attribute_path` in OAuth Generic. I would be happy to put together a PR for this if it is along the lines if what you were thinking?

**Comment by Jguer** [comment]
Hey @nrwiersma , `role_attribute_path` like in oauth generic (or gitlab/github) would be the approach I'm aiming for. :slightly_smiling_face: if you acknowledge the will to implement this, I'll assign you this issue. 

I'm happy to coach however needed and handle the review :+1:

:smile: thanks for taking the time to check this out and for reaching out before implementing

**Comment by Jguer** [comment]
I'm also in the process of implementing server admin mapping to the existing oauth `role_attribute_path` ([diff](https://github.com/grafana/grafana/compare/main...jguer/add-serveradmin-oauth)) if you'd like to implement the same in the process.

The only part of it which is a bit specific is [here](https://github.com/grafana/grafana/compare/main...jguer/add-serveradmin-oauth#diff-1932ec0f0e9483143b8e2d48df6f864540ae8a15a938d40011e5ca2712391077R87-R93) as it's better to have a separate option restricting server admin

**Comment by nrwiersma** [comment]
Will gladly take this issue on with the improvements you are planning. I would start with the simplest implementation first and make the needed refactoring on review.
