### ISSUE TITLE
Grafana Loki browser makes thousands of log volume queries. Loki got overloaded.

### ISSUE THREAD

**Issue by vpetrushin** [grafana/grafana#51786]
**What happened**: Grafana Loki browser tries to draw log volume graph. It makes thousands of queries to loki and it is got overloaded. Grafana shows timeouts errors. For ex. for 1 hour time range Grafana produces up to 3600 queries like `sum by(level)(count_over_time({app="myservice"}[1s]))` and Loki eats all available CPU's and can't answer until timeout.

**What you expected to happen**:
I expect to have 10-20-30 of stacks on log volume graph. For ex, if it will try to get volumes for 5m on 1 hour timerange, it will take only 12 queries, not 3600. 

**How to reproduce it (as minimally and precisely as possible)**:
Run a small Grafana/Loki environment and check how many queries Loki will get if Grafana runs on modern 4k laptop/monitor

**Anything else we need to know?**:

**Environment**:
- Grafana version: tested on 8.5 - 9.0.2
- Data source type & version: Loki 2.5.0
- OS Grafana is installed on: Linux
- User OS & Browser: Latest Chrome
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
Is this in a Dashboard panel, or in Explore? Are you able to supply steps for reproduction? I'm not noticing an excessive amount of requests being made.

![image](https://user-images.githubusercontent.com/46142/177540592-24500858-3c40-481e-bb4b-c00accdb78ce.png)

**Comment by vpetrushin** [comment]
thank you Josh for reply!
1. The problem is in Explore -> Loki datasource, I did not test the dashboard
2. you will not see the queries in the browser network panel, you can only see them in Loki logs.

What I did for debugging:
1. Open Loki logs with `kubectl -n loki get logs ...` in one terminal pad
2. Open Grafana logs `kubectl -n grafana get logs ...` in another
3. In browser navigate to Explore -> Loki and execute something like `{namespace="loki"}` on timerange 15 min, for example

And in loki logs you will see hundreds of lines like this

`level=info ts=2022-07-06T13:29:20.204923752Z caller=metrics.go:122 component=querier org_id=fake latency=fast query="sum by(level)(count_over_time({app="loki"}[1s]))" query_type=metric range_type=range length=14m59s step=1s duration=9.70353ms status=200 limit=1583 returned_lines=0 throughput=651kB total_bytes=6.3kB queue_time=14.232298ms subqueries=1 source=logvolhist`

It is ok on a small number of logs, but this behavior freezes the Loki on large or medium databases.

**Comment by gabor** [comment]
@vpetrushin i think that Loki log line can be confusing. it does not mean Loki received multiple requests.
you can try it out by sending a single metric loki query in grafana, for example `count_over_time({...}[10s])`, and you will see many such loki log lines.

a single logs-query should produce a single query for the logs, and a single query for the log-volume-graph. i have tested it right now and for me it works like that for me. if you see that it creates multiple http requests, please tell us and we'll reopen the issue.

**Comment by vpetrushin** [comment]
It is confusing when you see the 900 lines like this.

**Comment by vpetrushin** [comment]
Please open the issue, it is not solved. Or I have to grab and put here all the 900 lines of logs per one request?

**Comment by vpetrushin** [comment]
kubectl logs loki2-read-2 -n loki | grep "sum by(level)(count_over_time({namespace=" | wc -l
     900

**Comment by gabor** [comment]
@vpetrushin sorry, maybe there is a misunderstanding. the fact that you see those log-lines is OK. there is no problem there.  Grafana sends a single http request to Loki, and Loki internally splits it up into parts to execute it faster. it does not mean that multiple http requests were sent to Loki.

if you think Loki should change how this event is logged, feel free to create an issue about this in the Loki repository at https://github.com/grafana/loki

**Comment by vpetrushin** [comment]
Ok, thanks for explanations @gabor !
