### ISSUE TITLE
[Feature Request] Graphical display of 100 points per second

### ISSUE THREAD

**Issue by robsnodden** [grafana/grafana#5180]
Thank you very much for your advice, **torkelo**, **mtanda**, and **bergquist** and helping me with https://github.com/grafana/grafana/issues/5091 Over the weekend I created a lightweight API compatible with raintank snapshot service as per your suggestions, overrode the configs, and data is being snapshotted like a dream. Great success, thank you for the help, and the timely response!

**Additional question:**
I am sending batches of 100 data points per second on my graph, though the graph is only displaying 10 points per second (see pic below):
![grafana10pps](https://cloud.githubusercontent.com/assets/19312863/15555253/c4694bb4-227c-11e6-9854-799fd4f9047c.png)
even if I configure the time range refresh intervals for miliseconds, like seen in https://github.com/grafana/grafana/issues/1231

I would appreciate any advice on the graphical display for 100 data points per second (perhaps it is a configuration fix, or perhaps 10 points per second is the max). If this is not already a feature, it would be GREATLY beneficial to myself and my friends who rely on Grafana!

Thanks, 
Rob

**Comment by torkelo** [comment]
just tested this, and it works fine to have datapoints only 10 milliseconds apart. 

![image](https://cloud.githubusercontent.com/assets/10999/15566217/e551ad00-231f-11e6-8f83-dfc7c2ee1a31.png)

**Comment by robsnodden** [comment]
Thanks Torkelo, 

How can I configure the datapoints to be only 10 miliseconds apart? Please let me know how you were able to do that, thank you so much. 

I have been configuring the graph in a variety of combinations, and unable to show more than 10 datapoints per second, when the graph should display 100 datapoints per second (testing against the number of values in my InfluxDB data source)

Thanks, 
Rob

**Comment by torkelo** [comment]
I just specified timestamps 10ms apart

**Comment by erikvda** [comment]
I also experience the problem that only 10 data points per second are displayed in the graph. But the datasource contains about 200 data points per second. 

Could you please tell me how I could configure grafana to do this? I'm using grafana v3.0.4 and the kairosdb datasource plugin.

Thanks,

Erik

![image](https://cloud.githubusercontent.com/assets/5605816/15708399/ab4d7740-27fe-11e6-9fd8-8212b9e973f9.png)

![image](https://cloud.githubusercontent.com/assets/5605816/15708504/1bf058c8-27ff-11e6-9884-23d9088c8774.png)


{
  "addFilterTagMode": false,
  "addGroupByMode": false,
  "aliasColors": {},
  "bars": false,
  "datasource": null,
  "downsampling": "(NONE)",
  "editable": true,
  "error": false,
  "fill": 0,
  "grid": {
    "threshold1": null,
    "threshold1Color": "rgba(216, 200, 27, 0.27)",
    "threshold2": null,
    "threshold2Color": "rgba(234, 112, 112, 0.22)"
  },
  "height": "400px",
  "id": 2,
  "isGroupByValid": true,
  "isNew": true,
  "isTagGroupBy": false,
  "isTimeGroupBy": false,
  "isValueGroupBy": false,
  "legend": {
    "avg": false,
    "current": false,
    "max": false,
    "min": false,
    "show": true,
    "total": false,
    "values": false
  },
  "lines": true,
  "linewidth": 1,
  "links": [],
  "nullPointMode": "connected",
  "percentage": false,
  "pointradius": 5,
  "points": true,
  "renderer": "flot",
  "seriesOverrides": [],
  "span": 12,
  "stack": false,
  "steppedLine": false,
  "targets": [
    {
      "currentGroupByType": "tag",
      "downsampling": "avg",
      "errors": {},
      "groupBy": {
        "tagKey": "",
        "timeInterval": "1s"
      },
      "groupByTags": [
        "DeviceID"
      ],
      "horAggregator": {
        "factor": "1",
        "percentile": "0.75",
        "samplingRate": "1s",
        "unit": "millisecond"
      },
      "metric": "Accelerometer",
      "refId": "A",
      "tags": {}
    }
  ],
  "timeFrom": null,
  "timeShift": null,
  "title": "Accelerometer",
  "tooltip": {
    "msResolution": true,
    "shared": true,
    "value_type": "cumulative"
  },
  "type": "graph",
  "xaxis": {
    "show": true
  },
  "yaxes": [
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    },
    {
      "format": "short",
      "label": null,
      "logBase": 1,
      "max": null,
      "min": null,
      "show": true
    }
  ]
}

**Comment by torkelo** [comment]
What is the query sent to kairoadb and it's response?

**Comment by erikvda** [comment]
The kairosdb datasource plugin added an aggregator by itself. I removed it from the datasource.js and now it's working

Thanks Torkelo

if (target.downsampling !== '(NONE)') {
      if (target.downsampling === undefined) {
        target.downsampling = 'avg';
        target.sampling = '10s';
      }
      query.aggregators.push({
        name: target.downsampling,
        align_sampling: true,
        //align_start_time: true,
        sampling: self.convertToKairosInterval(target.sampling || options.interval)
      });
    }

**Comment by robsnodden** [comment]
Thanks Torkelo, 

I am using the standard InfluxDB data source (0.9.0), and still unable to see all 100 data points per second. I do not see that there is an aggregation happening on the InfluxDB side. 

Can you please show the steps in which you specified datapoints with specified timestamps at 10ms apart? (As you showed in earlier reponse). It would be greatly appreciated. 

Thanks, 
Rob

**Comment by torkelo** [comment]
I just returned data from a custom data source with timestamps 10ms apart, it can you show data returned by InfluxDB? What's you group by time?

**Comment by robsnodden** [comment]
Thanks Torkelo, 

See below for my group by time (from the JSON):
...
      "dsType": "influxdb",
      "groupBy": [
        {
          "params": [
            "$interval"
          ],
          "type": "time"
        },
        {
          "params": [
            "null"
          ],
          "type": "fill"
        }
      ],
...

This is the graph with the same settings as shown above (groupBy is 10ms):

![scn10ms](https://cloud.githubusercontent.com/assets/19312863/15793478/110ef6ee-2999-11e6-9665-2ad3eba6bacf.png)

![tenm](https://cloud.githubusercontent.com/assets/19312863/15793492/25d24aae-2999-11e6-825f-40e4eed1bcf8.png)

Please let me know what I am doing incorrectly, the logic appears that the datapoints would be displayed 10ms apart, resulting in 100 datapoints per second, though the graph only shows 10 datapoints per second.

Thanks, 
Rob

**Comment by torkelo** [comment]
O idea, ask InfluxDB, open chrome dev tools, check the request grafana sends and InfluxDB response. Think it couldbe caused by the 10ms group by time parameter, Ms text intervals where not supported in Grafana, just a parsing thing, fixed in master.  Try 3.1 nightly builxs
