### ISSUE TITLE
[Bug] Buttons in top bar disappear on less wide screens

### ISSUE THREAD

**Issue by theevocater** [grafana/grafana#5181]
- What Grafana version are you using?
3.0.3
- What OS are you running grafana on?
linux centos6

Hey yall,

Something I noticed after upgrading to 3.X.X was a small bug in the responsive design. When you shrink a window below some value the buttons on the top disappear. I generally use half of my screen for dashes which triggers this. I think somewhere around 700px wide is where the buttons start to poof. 

Looks great! 
<img width="1207" alt="Full width with buttons" src="https://cloud.githubusercontent.com/assets/688882/15556298/32cf4fc2-229b-11e6-9d45-8fd7605b25e3.png">

Make the window smaller and the buttons are gone 😢 
<img width="729" alt="shrunk window with no buttons" src="https://cloud.githubusercontent.com/assets/688882/15556301/38db2f3a-229b-11e6-9aeb-5819f1c64084.png">

Thanks yall, appreciate all you do.

**Comment by torkelo** [comment]
this is by design to make room for longer dashboard title and so that the menu does not wrap to 2 lines. 

This is not very good solution, we will try to collapse all the dashboard buttons to a hamburger or something in the future
