### ISSUE TITLE
Dashboards created by non-logged-in users have incorrect permissions

### ISSUE THREAD

**Issue by sevenval-admins** [grafana/grafana#51828]
**What happened**:

Since our update to 9.0.2 we have observed a problematic behaviour after creating new dashboards.

The installation is a Grafana running internally at our company. There are two organisations and the options for authentication are set like this:

auth.anonymous
enabled	true
hide_version	false
org_name	MYORG
org_role	Editor

If a user who is not logged in now creates a dashboard, he gets the message that he is not allowed to see the dashboard and these messages appear in the logs:

`
6.7.2022 17:13:41logger=dashboard-service t=2022-07-06T15:13:41.92554616Z level=error msg="Could not make user admin" dashboard="Test 2 New dashboard" user=0 error="'' built-in role is not valid"
6.7.2022 17:13:42logger=dashboard.permissions t=2022-07-06T15:13:42.204456645Z level=info msg="Access denied to folder or dashboard" userId=0 id=395 permissions="any(dashboards:read dashboards:read)"
6.7.2022 17:13:42logger=context traceID=00000000000000000000000000000000 userId=0 orgId=2 uname= t=2022-07-06T15:13:42.204547314Z level=info msg="Request Completed" method=GET path=/api/dashboards/uid/EgI2wc6nz status=403 remote_addr=172.20.x.x time_ms=26 duration=26.166045ms size=45 referer=https://grafana.my.org/d/EgI2wc6nz/test-2-new-dashboard traceID=00000000000000000000000000000000
`

If I then log in with the user admin, I see the new dashboard and can use it. The permissions look like this:

![screenshot 2022-07-06 um 17 43 40](https://user-images.githubusercontent.com/13047464/177591545-bcc36e22-4fdd-41c5-961b-999c07d3e31e.png)

If I look at a dashboard created before the update, the permissions look like this:

![screenshot 2022-07-06 um 17 44 10](https://user-images.githubusercontent.com/13047464/177591576-8aa7fda5-c367-417e-9e11-5800a0ab4e6c.png)

**What you expected to happen**:

Dashboards created by users who are not logged in should still be accessible to all.

**How to reproduce it (as minimally and precisely as possible)**:

Create a new dashboard as a user who is not logged in

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: all
- OS Grafana is installed on: Docker image grafana/grafana:9.0.2
- User OS & Browser: all
- Grafana plugins:
- Others:

**Comment by IevaVasiljeva** [comment]
Hi! Thanks for reporting! We will attempt to investigate this next week.

**Comment by gmarkey** [comment]
The same issue occurs for anonymous users assigned the "Editor" role when creating folders. They can create a folder, but the resulting permissions allow only admin role. v9.0.2 via prom-operator.

**Comment by gamab** [comment]
Hi!

I can reproduce, thanks for the setup.
The faulty line is [here](https://github.com/grafana/grafana/blob/v9.0.2/pkg/services/dashboards/service/dashboard_service.go#L483), we try to set Admin permissions for the creator of the dashboard without accounting for Anonymous access.
Same goes for the [folders](https://github.com/grafana/grafana/blob/v9.0.2/pkg/services/dashboards/service/folder_service.go#L171-L179).

I'll push a fix ASAP and backport to 9.0.X

**Comment by gamab** [comment]
Backports have been merged. The fix should be available in the next releases. (v9.0.5, v9.1.0) :slightly_smiling_face:
