### ISSUE TITLE
Dashboard folder deletion ambiguity when an alert rule is associated with that folder

### ISSUE THREAD

**Issue by darrenjaneczek** [grafana/grafana#51825]
**What happened**:

Deleting a folder that has an alert associated with it fails with a yellow warning. The UI acts as though the folder was deleted, but refreshing indicates that it was not.

https://user-images.githubusercontent.com/38694490/177587440-baf3da51-ace8-4414-b33f-f529f0e44caa.mp4

**What you expected to happen**:

Any of the following:
- When viewing the dashboard folder, show some indication that there are alerts associated with it
- When attempting to delete a folder with alerts associated, allow the dialog to indicate this and provide a "yes I want to delete the alerts too" 
- If the deletion fails, don't remove the folder from the list

**How to reproduce it (as minimally and precisely as possible)**:

- Unified alerting is enabled
- Create a dashboard folder: "A"
- Create a new alert, and associate it with folder "A"
  ![image](https://user-images.githubusercontent.com/38694490/177578369-69cfe0f2-3abd-461a-9dbc-6de28d423b8b.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.2

**Comment by kaydelaney** [comment]
Looked into this but wasn't able to reproduce the issue on 9.0.2 or main

**Comment by darrenjaneczek** [comment]
Peculiar. I am still experiencing it in v9.0.4 (enterprise) with `GF_UNIFIED_ALERTING_ENABLED=true`.
Maybe we can connect to investigate.

Currently, in my environment, this is used to delete selected folders:
/api/folders/feECc4zVk?forceDeleteRules=false

I am able to force a successful deletion by changing to this:
/api/folders/feECc4zVk?forceDeleteRules=true

The provided warning dialog is fair:
> Do you want to delete the selected folder and all its dashboards and alerts?

Thoughts?

**Comment by joshhunt** [comment]
Hey @darrenjaneczek We're trying to look into this but having trouble replicating. 

Few things we noted about your video that are a bit strange, and might be preventing us from being able to replicate:
 - You don't have any folders, not even the special General folder which all orgs should have, and arent able to be deleted
 - You're not logged in, yet are still able to create folders, alerts, and (supposedly) delete them. Anon access shouldn't permit this? Is this some funky RBAC thing?

Here's us trying to replicate. When we attempt to delete the folder it shows the error alert, but then the folder list auto-refreshes and the folder is still there.

https://user-images.githubusercontent.com/46142/195307025-f96c7341-3a38-4a51-8be4-38ef4cf94996.mp4

Does something stand out for you that we've done wrong?

**Comment by darrenjaneczek** [comment]
Note, "enterprise" has no impact on the resulting behavior.
```
services:
  grafana:
    image: grafana/grafana:9.2.2
    ports:
      - 3000:3000
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_UNIFIED_ALERTING_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS=grafana-cardinality-datasource
```
