### ISSUE TITLE
"Edit Folder" and "Edit Permission" in AlertRulesGroup ignores Grafana being hosted under relative subpath

### ISSUE THREAD

**Issue by the-get** [grafana/grafana#51830]
**What happened**:
Links to "Edit Folder" and "Edit Permission" in Alert rules list are using an absolute baseurl ("/dashboards/...)
**What you expected to happen**:
If Grafana is hosted using a subpath (e.g.  /grafana/ ) links should lead to "/grafana/dashboards/..."

**How to reproduce it (as minimally and precisely as possible)**:
Setup grafana with environment variables:

GF_SERVER_ROOT_URL=http://localhost/grafana/
GF_SERVER_SERVE_FROM_SUB_PATH=true

Create a dashboard in a folder, configure an alert in the dashboard. 

Open http://localhost/grafana/alerting/list
Click on Edit or Lock Icon in folder group.
-> links to http://localhost/dashboards/f/***folder_uid***/settings
should be 
-> http://localhost/dashboards/grafana/dashboards/f/***folder_uid***/settings

**Anything else we need to know?**:
in https://github.com/grafana/grafana/blob/3dfafbadef3f17ff4aefe64381caaf1fda03510f/public/app/features/alerting/unified/components/rules/RulesGroup.tsx#L72

the baseurl is set using an absolute link to "/dashboards/...", it should be used with a relative path or include the hosted subpath.

**Environment**:
- Grafana version: 9.02
- OS Grafana is installed on: docker container

**Comment by konrad147** [comment]
Working on this I discovered an issue on the folder's setting page https://github.com/grafana/grafana/issues/52378
