### ISSUE TITLE
https question

### ISSUE THREAD

**Issue by gouki777** [grafana/grafana#5184]
hi.
my computer is Centos6, grafana 2.5.. https key crt is OK!
I am doing the HTTPS,but i find the problem. ~help.
modify profile grafana.ini 
protocol = https
http_port = 3000
this profile is OK!  2016/05/26 13:04:34 [I] Listen: https://0.0.0.0:3000   #LOG!
but i need https://172.X.X.100:3000/.  https://xxxx:3000 not good!
i need https://grafana.ABC.com

modify profile grafana.ini 
protocol = https
http_port = 443
start grafana  FAILED 
 look log!
2016/05/26 13:18:55 [I] Starting Grafana
2016/05/26 13:18:55 [I] Version: 2.5.0, Commit: v2.5.0+1-g287d8ca, Build date: 2015-10-28 16:43:28 +0800 CST
2016/05/26 13:18:55 [I] Configuration Info
Config files:
  [0]: /usr/share/grafana/conf/defaults.ini
  [1]: /etc/grafana/grafana.ini
Command lines overrides:
  [0]: default.paths.data=/var/lib/grafana
  [1]: default.paths.logs=/var/log/grafana
Paths:
  home: /usr/share/grafana
  data: /var/lib/grafana
  logs: /var/log/grafana

2016/05/26 13:18:55 [I] Database: sqlite3
2016/05/26 13:18:55 [I] Migrator: Starting DB migration
2016/05/26 13:18:55 [I] Listen: https://0.0.0.0:443
2016/05/26 13:18:56 [web.go:93 StartServer()] [E] Fail to start server: listen tcp 0.0.0.0:443: bind: permission denied

my port 443 is not actually used. 
[root@zabbix ~]# lsof -i:443
[root@zabbix ~]# netstat -lntp |grep 443

i need https://grafana.ABC.com   ,how to configure.
thanks

**Comment by torkelo** [comment]
linux does not allow (by default) users to bind to port 80 and 433

you can give the grafana user this permission:
http://docs.grafana.org/installation/configuration/#http_addr
