### ISSUE TITLE
Embedding more than 1 panel / embedding whole set of panel row into a web page

### ISSUE THREAD

**Issue by EXPEvgowdaks** [grafana/grafana#5185]
Thank you for helping us make Grafana even better!

To help us respond to your issues more quickly, please make sure to add as much information as possible.

If this issue is about a plugin, please open the issue in that plugin's repository.

Start your issue's title with [Feature Request] / [Bug] / [Question] or no tag if you're unsure. Also, please be aware that GitHub now supports uploading of screenshots; look at the bottom of this input field.

Please include some basic information:
- What Grafana version are you using?
2.0
- What datasource are you using?
graphite

If your question/bug relates to a metric query / unexpected data visualization, please include:
- An image or text representation of your metric query
- The raw query and response from your data source (check this in chrome dev tools network tab)

**Comment by torkelo** [comment]
currently only single panel embedding is supported. Not very likely we will support other options,
