### ISSUE TITLE
[Bug] Query variable that includes "." is escaped on query to InfluxDB

### ISSUE THREAD

**Issue by MMore** [grafana/grafana#5186]
We are using Grafana v3.0.3.

There we configured a query variables that returns fqdn's -> there are "." in the values like `server23.dc1.example.org`.

We added a graph vis. with the following metric: 
`SELECT max("events_failure") FROM "puppetagent" WHERE "host" = '$host' AND $timeFilter GROUP BY time($interval) fill(null)`

This query works until I toggle the "Edit Mode" of this metric and have full control over this query.

I get the error `{"error":"error parsing query: found \\., expected identifier, string, number, bool at line 1, char 71"}`. This happens because the "." in the $host variable is escaped with "\" (`%5C`):

    http://server1.dc1.example.org:8086/query?u=telegraf&p=telegraf&db=telegraf&q=SELECT%20max(%22events_failure%22)%20FROM%20%22puppetagent%22%20WHERE%20%22host%22%20%3D%20%27server23%5C.dc1%5C.example%5C.org%27%20AND%20%22events_failure%22%20%3E%200%20AND%20time%20%3E%20now()%20-%2024h%20GROUP%20BY%20time(2m)%20fill(null)&epoch=ms

**Comment by torkelo** [comment]
if you use raw query mode template variables are regex escaped to support multi valued template values (if your variable is using multi or all value). 

So change your host tag filter to `host =~ /^$host$/
