### ISSUE TITLE
Missing data points in time series when using stack series

### ISSUE THREAD

**Issue by Christoph-AK** [grafana/grafana#51867]
**What happened**:
When switching to stacked series: normal with only a few data points, they don't show up at all.

![missing_points.gif](https://user-images.githubusercontent.com/72923608/177714387-75a862e7-50db-4a87-a392-c2354fad9ac4.gif)

**What you expected to happen**:
All data points show up.

**How to reproduce it (as minimally and precisely as possible)**:
Dashboard: https://gist.github.com/Christoph-AK/2fc7adb0c864bc526c4028559a3c3144
Data: 
```
"Time","live info"
2022-07-07 08:25:20,5
2022-07-07 08:49:40,2
2022-07-07 09:02:20,4
```

**Environment**:
- Grafana version: Grafana OSS 9.0.2 and grafana 9.1.0-pre
- Data source type & version: Loki:main
- OS Grafana is installed on: Docker Compose on AWS EC2 Ubuntu
- User OS & Browser: Edge, latest win11

**Comment by joshhunt** [comment]
Hmm, I'm not able to reproduce with [this dashboard](https://play.grafana.org/d/P5Nqwh6nz/51867-stacked-series-missing?orgId=1&editPanel=2)

Are you able to supply the data results where you get the error? Query Inspector > JSON > DataFrame JSON. Be aware that this will be the results from Loki, so make sure it doesn't contain any sensitive information (though, if your queries are just counts/aggregations it _should_ be fine, but please double check).

**Comment by Christoph-AK** [comment]
Thank you for looking into this!

https://gist.github.com/Christoph-AK/b1f7dc2ac0e89ce7fadbeddfe542c87b

This contains the entire dataset on my loki instance.

**Comment by Christoph-AK** [comment]
This is the dataframe for one part of the set where I get the issue:

https://gist.github.com/Christoph-AK/14dfda1d8eedf2801066d3bfdb024aba

![error_mini.gif](https://user-images.githubusercontent.com/72923608/177751772-5c820bdb-05e7-4007-8a91-9032691353ae.gif)
