### ISSUE TITLE
Upgrade typescript and related things to typescript 4.9.x

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#51871]
we have an automatic update PR for typescript upgrading 4.6x to 4.7x, but there are some incompatibilities:
- `levitate` .. something code-generation-related changed in typescript 4.7.x, so now we have api changes
- we should probably upgrade it together with typescript-related things like `babel`, `eslint`, etc.

the PR: https://github.com/grafana/grafana/pull/50847

**Comment by zoltanbedi** [comment]
We want to do this after moving away from yarn.

**Comment by gabor** [comment]
we're already on typescript5.x, closing the issue
