### ISSUE TITLE
Manage dashboard import from elasticsearch

### ISSUE THREAD

**Issue by xploit42** [grafana/grafana#5188]
Hi,

Is there a way to choose which dashboard import from es, or to delete many dashboards at a time?

For example, i have a grafana-dash index in my es, it contains 44 dashboards, i want to create a new organization, and to authorize users from this org to access only 3 dashboard, actualy the only way i found is to import all dashboards, and to open one by one to click params => delete dashboards => yes.

Regards

**Comment by torkelo** [comment]
yes, if you want to import dashboards from grafana 1.x your only option is to import all

**Comment by xploit42** [comment]
And can you add a way to select many dashboards and delete them all?
Something like a dashboard manager.

**Comment by torkelo** [comment]
@xploit42 yes, this is something that might come soon in 3.1 or 3.2

**Comment by xploit42** [comment]
Okay, thank you for your answers and for your work!
