### ISSUE TITLE
[Feature Request] Variables in annotation queries

### ISSUE THREAD

**Issue by samstarling** [grafana/grafana#5189]
I'd like to be able to use variables in annotation queries. Is this possible at present?

For example, this does not interpolate the `$system` variable:

<img width="657" alt="grafana_-_jvmkit___generic" src="https://cloud.githubusercontent.com/assets/42478/15573546/0e96878a-2348-11e6-8a11-327754d3cb65.png">

**Comment by torkelo** [comment]
it's possible in 3.0.4

**Comment by samstarling** [comment]
Hmm, I'm using 3.0.4 – is there something I'm missing? I still see AJAX requests from the page that don't interpolate the variable.
