### ISSUE TITLE
TimeSeries: Stacking makes single series graph disappear 

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#51893]
A graph with a single series can disappear (not be rendered) when stacking is enabled (it depends on time range bit)

![Screenshot from 2022-07-07 13-56-54](https://user-images.githubusercontent.com/10999/177767681-c13b1335-ffda-4c57-a645-3d4df0d95cee.png)

Can be replicated here: 
https://play.grafana.org/d/uiytRoenz/time-series-stacking-empty-graph?orgId=1&from=1651496551456&to=1662278434196

**Comment by joshhunt** [comment]
This sounds the same as this issue i had trouble replicating https://github.com/grafana/grafana/issues/51867 ?
