### ISSUE TITLE
Document open/close chevron direction guidelines

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#51901]
There have several conversations around the behavior and direction of icons for the collapse icon. We need to determine standard direction and behavior of the CollapsableSection throughout Grafana, including in Panel Edit.

Being that this conversation has been brought up several times, below is a list of historical conversations that have been had for reference in building the documentation:

- https://raintank-corp.slack.com/archives/C025WTVRBSN/p1649086697634589
- https://github.com/grafana/grafana/pull/47386
- https://raintank-corp.slack.com/archives/C0F5GDR4P/p1649421297368829
- https://raintank-corp.slack.com/archives/C0F5GDR4P/p1657194078565639

**Comment by joshhunt** [comment]
Dupe https://github.com/grafana/grafana/issues/56328
