### ISSUE TITLE
[Feature Request]: Dashboard / Panel Time Truncating

### ISSUE THREAD

**Issue by kylebrandt** [grafana/grafana#5190]
Feature: Have a dashboard wide and/or panel setting for truncating the time of the start and end times of the request to the nearest N seconds, minutes, etc

Why: To get better cache utilization from datasources. This way when multiple people go to the same dashboard, they have a better chance of asking for the same time range.

The reason to be able to do it at the panel level as well as some queries might be known to be more expensive and don't need to be refreshed as much.

**Comment by torkelo** [comment]
Like time step quantizing ?

**Comment by kylebrandt** [comment]
Don't know what that is :/

**Comment by kylebrandt** [comment]
I basically mean something like the following on the to and from:

`options.range.from.floor(15, 'seconds')`
http://momentjs.com/docs/#/plugins/round/

**Comment by kylebrandt** [comment]
Might call it "snap to time" where the option is a duration.

**Comment by torkelo** [comment]
Time quantization is term used in music sampling and encoding and also in midi editing,  basically it's snap to time at least in the editing case :)

**Comment by kylebrandt** [comment]
Right, but in my thinking not in terms of downsampling or the datapoints within a query result. Just the timeframe requested.

**Comment by jgoldschrafe** [comment]
Cache utilization aside, this is critically important when using `GROUP BY` in InfluxDB. `SUM()` returns a bad, misleading initial value when the time interval doesn't align correctly with the bucket start. This is mostly an issue when coupling `SUM()` with `DERIVATIVE()`, because this causes the first value to appear as a massive spike that renders the rest of the graph unreadable.

**Comment by iShift** [comment]
+1 good feature, i have same problem with cache

**Comment by kylebrandt** [comment]
> Time quantization is term used in music sampling and encoding and also in midi editing, basically it's snap to time at least in the editing case :)

4 years later - okay, having done some MIDI piano I know what it is now - cheat mode for rhythm :-P

**Comment by ahlaw** [comment]
Since requests are handled differently per data source anyways, would it make more sense to implement time alignment as a data source-level configuration first in every data source we want to support, and then have panel-level configuration as an overriding configuration?
