### ISSUE TITLE
No graphs shown for short quick ranges.

### ISSUE THREAD

**Issue by dbiers** [grafana/grafana#5191]
Grafana Version:    grafana-3.0.3-1463994644.x86_64
Datasource:         InfluxDB
OS:                 CentOS 7.x x64

Steps:  Moved quick ranges from "Last 3 hours" to "Last 1 hour"
Expected Result:  Graphs with last 1 hour datas.
Actual Result:    Blank graphs with no datas.

I believe I've seen this before but I could not find a solution anywhere.  I did also attempt to play with time and zone settings but this did not seem to resolve the issue (unless I did this incorrectly).

I am in CST/CDT (-6 UTC) while the servers are using time zone EST/EDT (-5 UTC).

I know there is data there because 1) I can see it on TCPDUMP and 2) I can see the last hour when using the last 3 hour view.

**Comment by torkelo** [comment]
Can you open chrome dev tools and look at the InfluxDB request and the response?

**Comment by dbiers** [comment]
@torkelo Yes it looks like data is getting back as far as I can tell.  Each graph has their queries and the responses contain the series and their respective data.  The graphs do not draw any lines or information, though.

![graph_blank](https://cloud.githubusercontent.com/assets/7914638/15586168/8da1df48-2348-11e6-931a-32bee602ca87.png)

**Comment by torkelo** [comment]
whats your group by time, fill (in your query),  and null point mode (graph display option)

**Comment by torkelo** [comment]
try setting a lower group by time limit that is equal to the rate at which you write data, for example `>10s` of you write every 10s  (this is done the the group by time option below your queries)

**Comment by dbiers** [comment]
@torkelo I tried changing this on the query itself as well as the bottom of the metrics tab.

![graphnote](https://cloud.githubusercontent.com/assets/7914638/15586822/fa3b285a-234b-11e6-9e9f-13eea4fef4ba.png)

Section NOTE-1: If I set a group time here, the entire graph appears blank and shows no statistics with exclamation mark in the upper left hand corner of the graph.

Section NOTE-2: If I set a group time here, it does not display any further information.

Maybe I am running the wrong queries or going about this the incorrect way?  If I run the queries with mean, last, etc (anything other than non_negative_derivative) then the graph does not show me what is happening and when but rather shows me a total and when that total rises.

**Comment by dbiers** [comment]
@torkelo Ok looks like this query is running for one of my single stats (viewing last 30 minutes):

```
SELECT mean("value") FROM "interface_tx" WHERE "host" = 'sql01.gflclan.com' AND "type" = 'if_octets' AND "instance" = 'eno16777728' AND time > now() - 15m GROUP BY time(10s) fill(null)
```

Which is returning blank results (or no results?).  I'm not sure why that is happening though when obviously, things have been logged in the past 30 minutes.

If I click+drag over a specific time frame on a graph, I can zoom into that section and I *can* see the last 30 minutes this way but it is definitely not ideal.

**Comment by torkelo** [comment]
If your InfluxDB query is returning no data the  investigate that I think,  not sure if I can help

**Comment by David-Development** [comment]
@dbiers Did you figure out a solution to this?

I'm facing the same problem right now. If I use the group_by `$__interval`, it's not showing any data in the 5 minutes time-frame. If I use a fixed group_by `10s`, it does show the data in the 5 minutes time-frame but not in a 7 day time-frame..

**Comment by David-Development** [comment]
Figured it out.. for anyone else looking for a solution, [this](https://github.com/grafana/grafana/issues/2310#issuecomment-392229872) did the trick for me.

Basically you edit the graph, go to `Display`, go to `Stacking & Null value` and select `connected` for `Null value`.

**Comment by ramarov** [comment]
Good job thank you for this trick it works. This should enabled to connected by default.

**Comment by chrissound** [comment]
Is this not a bug? Asking because it's been closed.

David's solution worked for me too.
