### ISSUE TITLE
Question regarding Single Stat Widget using prometheus query_range endpoint

### ISSUE THREAD

**Issue by daniellowtw** [grafana/grafana#5192]
Hi, I have a question regarding making a single stat widget with prometheus as the datasource.

I am trying to get the nth entry by doing `bottomk(1, topk(n, sum(metric) by (job)))`

Doing this in the prometheus graph console gives me a single vector whereas doing this in within grafana gives me a matrix, which causes the single stat widget to complain.

Digging deeper, I realised that from the console, it is making a request to the `/query` endpoint

```
/api/v1/query?query=bottomk(1, topk(n, sum(metric) by (job)))
```

but from grafana it is making a request to the `/query_range` endpoint

```
/api/v1/query_range?query=bottomk(1, topk(n, sum(metric) by (job)))
```

The respective responses are

```
{"status":"success","data":{"resultType":"vector","result":[{"metric":{"job":"demo"},"value":[1464283131.893,"100"]}]}}
```
and 

```
{"status":"success","data":{"resultType":"matrix","result":[

{"metric":{"job":"demo"},"values":[[1464275753,"160"],[1464275764,"160"],[1464275775,"160"],[1464275786,"160"]]},
{"metric":{"job":"foo"},"values":[[1464275709,"120"],[1464275720,"120"],[1464275731,"120"]]}
...
]}}
```

It seems to be that single stat should really make the request to `/query` instead of `/query_range`.

Is this the expected behaviour? Is there a reason why it needs a range in order to derive the single stat?

**Comment by torkelo** [comment]
Yes, single stat also supports graph line which requires a time series.  

The warning you get is probably because your query returns multiple series,  change it so it only returns a single series
