### ISSUE TITLE
Dashboards: Difference Percent Legend unit displays 0.0-1.0 when 0-100 expected

### ISSUE THREAD

**Issue by nuzayets** [grafana/grafana#51937]
**What happened**:
Difference Percent legend values formatted as 0.0-1.0 but displays a % sign for 0-100.

![](https://user-images.githubusercontent.com/1832518/177885747-2628baf7-ba8b-4b22-a820-45a5ba8d295c.png)

**What you expected to happen**:

![](https://user-images.githubusercontent.com/1832518/177885777-6b0444e8-f0ab-4f39-ad8b-bf041a4a6630.png)

**How to reproduce it (as minimally and precisely as possible)**:
Grafana latest on Docker connecting to TimescaleDB, use Difference Percent in the Legend in a Time Series panel.

**Anything else we need to know?**:
https://github.com/grafana/grafana/pull/49004 tried to resolve there being no units at all - their screenshot shows the value being formatted correctly, however I had to make this change to get the value to format correctly on my end:

```diff
--- a/packages/grafana-ui/src/components/uPlot/PlotLegend.tsx
+++ b/packages/grafana-ui/src/components/uPlot/PlotLegend.tsx
@@ -86,7 +86,7 @@ export const PlotLegend: React.FC<PlotLegendProps> = ({
                   ...field,
                   config: {
                     ...field.config,
-                    unit: 'percent',
+                    unit: 'percentunit',
                   },
                 },
                 theme,
```

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: Postgres 12+ /w TimescaleDB
- OS Grafana is installed on: Docker (alpine)
- User OS & Browser: All browsers
- Grafana plugins:
- Others:

**Comment by zuchka** [comment]
do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:

this doesn't sound specific to mysql, correct? Hoping we can mock this up with dummy data to share with the team. That would be the ideal situation 👍

**Comment by nuzayets** [comment]
> do you think you could try and replicate this on our public sandbox, https://play.grafana.org? :pray:
> 

Sorry I cannot. 

- I cannot create Dashboards on play.grafana. I see dashboards tagged with issue #s so I'm guessing this is the SOP. Tried logging in with Grafana Cloud account and tried SSO with Google. 
- There is no Postgres /w TimescaleDB data source on play.grafana


> this doesn't sound specific to mysql, correct? Hoping we can mock this up with dummy data to share with the team. That would be the ideal situation 👍 

I have not confirmed this on MySQL. My test case is on Postgres 12+ /w TimescaleDB.

**Comment by zuchka** [comment]
Can you use the data tab inside [the Grafana Inspector panel](https://grafana.com/docs/grafana/next/panels/working-with-panels/navigate-inspector-panel/) to share your data?

https://grafana.com/docs/grafana/next/panels/working-with-panels/navigate-inspector-panel/

**Comment by jedstar** [comment]
Is the solution for this to update the actual calculation from:
(last - first)/first
to
((last - first)/first)*100

not sure what other flow on effects that might have though.

calculations are done by:
[fieldReducer.ts](https://github.com/grafana/grafana/blob/main/packages/grafana-data/src/transformations/fieldReducer.ts)
`  if (isNumber(calcs.firstNotNull) && isNumber(calcs.diff)) {
    calcs.diffperc = calcs.diff / calcs.firstNotNull;
  }`

[time_series2.ts](https://github.com/grafana/grafana/blob/main/public/app/core/time_series2.ts)
`    if (this.stats.current !== null && this.stats.first !== null) {
      this.stats.diff = this.stats.current - this.stats.first;
      this.stats.diffperc = this.stats.diff / this.stats.first;
    }`

**Comment by minhaz1** [comment]
I also ran into this issue and was able to re-produce this inside of play.grafana.org.
Steps to re-produce:
https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&from=1665697563656&to=1665697888599&viewPanel=1&editPanel=1

You can see in the screenshot below for `backend_01` the `First` value is 0.200, `Last` is value is 23.4, `Difference` is 23.2 but the `Difference percent` is 116% when it should be 23.2/0.200 = 11600%, it's off by exactly a factor of 100. 

Most likely what's happening here is the value is calculated and then `%` is just tacked onto it without actually converting it to a percentage (multiply by 100). 

![image](https://user-images.githubusercontent.com/3103428/195722578-2088eb7d-1f26-44f4-a5c4-d33fae734d8a.png)

**Comment by nuzayets** [comment]
Making the change in my initial post resolves the issue, bringing the formatting in line with the calculation. @jedstar  suggestion brings the calculation in line with the formatting and the 'diffpct' implied behaviour. However either way it makes the legend value opinionated about using percent or ratio. A proper fix might just be to allow both? Diff pct and diff ratio?

**Comment by minhaz1** [comment]
I don’t think it’s a matter of opinion since it does say “Difference percent” and the moment it is just incorrect since it displays the % symbol next to the value. If someone wants a separate “Difference Ratio” then I would say that should be a separate feature request.

**Comment by Naresh-Edla** [comment]
> **What happened**: Difference Percent legend values formatted as 0.0-1.0 but displays a % sign for 0-100.
> 
> ![](https://user-images.githubusercontent.com/1832518/177885747-2628baf7-ba8b-4b22-a820-45a5ba8d295c.png)
> 
> **What you expected to happen**:
> 
> ![](https://user-images.githubusercontent.com/1832518/177885777-6b0444e8-f0ab-4f39-ad8b-bf041a4a6630.png)
> 
> **How to reproduce it (as minimally and precisely as possible)**: Grafana latest on Docker connecting to TimescaleDB, use Difference Percent in the Legend in a Time Series panel.
> 
> **Anything else we need to know?**: #49004 tried to resolve there being no units at all - their screenshot shows the value being formatted correctly, however I had to make this change to get the value to format correctly on my end:
> 
> ```diff
> --- a/packages/grafana-ui/src/components/uPlot/PlotLegend.tsx
> +++ b/packages/grafana-ui/src/components/uPlot/PlotLegend.tsx
> @@ -86,7 +86,7 @@ export const PlotLegend: React.FC<PlotLegendProps> = ({
>                    ...field,
>                    config: {
>                      ...field.config,
> -                    unit: 'percent',
> +                    unit: 'percentunit',
>                    },
>                  },
>                  theme,
> ```
> 
> **Environment**:
> 
> * Grafana version: 9.0.2
> * Data source type & version: Postgres 12+ /w TimescaleDB
> * OS Grafana is installed on: Docker (alpine)
> * User OS & Browser: All browsers
> * Grafana plugins:
> * Others:

@nuzayets Thanks for finding the issue, In which Grafana release this issue will be resolved.

**Comment by axelavargas** [comment]
Forwarding this issue to @grafana/grafana-bi-squad as this is related to the timeseries panel.
