### ISSUE TITLE
Adoc filter icon/ Filter for value icon should not appear/option to disable when it is not compactible with data source for adhoc filtering

### ISSUE THREAD

**Issue by satyatechy** [grafana/grafana#51947]
**What happened**: When we hover on the table cell we will see an icon to filter values when we click on it adds an Adhoc filter on top. Since Mix data source or custom data source is not compatible. So the icon appears even if it doesn't support it or no option to disable it.

**What you expected to happen**: Icon should not appear if the data source doesn't support or no option to disable it manually.

**How to reproduce it (as minimally and precisely as possible)**: crate a table panel> hover on table cell you will see an icon to filter values> once we click on it adds Adhoc filter on top> since mix data source not compatible with Adhoc filtering that option doesn't work. 

**Anything else we need to know?**:

**Environment**:
- Grafana version: 7.5.5
- Data source type & version: Mix or Custom
- OS Grafana is installed on: Any
- User OS & Browser: Any
- Grafana plugins: Table
- Others:

**Comment by zuchka** [comment]
have you tried using a newer version? We don't really support Grafana 7 any more 👍

**Comment by satyatechy** [comment]
> have you tried using a newer version? We don't really support Grafana 7 any more 👍

We are using 7.5.5 for some compatibility reasons. Is there any way to port these changes? Can you help me where is the option in the newer version to disable the Adhoc filter?
