### ISSUE TITLE
Binary operation with postgresql queries

### ISSUE THREAD

**Issue by eglyn** [grafana/grafana#51958]
Hi :)

I try to do a simple binary operation with 2 postgresql queries, but it does not work:

![image](https://user-images.githubusercontent.com/24936778/177956279-0b697d01-f1f1-4d16-ba74-238900c7b572.png)

There is no result , it display nothing :/ I can't do any operation between this 2 values...

Does someone knows why this simple addition does not work ?

thx :)

**Comment by zuchka** [comment]
check your data types and then use the convert field type transformation to make sure your two fields are numeric types:

https://grafana.com/docs/grafana/next/panels/transform-data/transformation-functions/#convert-field-type
