### ISSUE TITLE
UX: Glue - Create a catalogue of datalinks required for each DS pair

### ISSUE THREAD

**Issue by radiorental** [grafana/grafana#51967]
### Background / Why we're doing this

Having this catalogue will inform the UI design of the Glue config page

We need to know which piece of data from a given telemetry signal A could be fed into the query for telemetry signal B, which means having a least common denominator of data common between telemetry signals (and/or how dataframes for each kind of data are strucutred within Grafana)

### Is there existing research for this?

No research yet

### Problems or tasks

- A problem we're trying to solve
- A task the user needs to accomplish
- …

### Deliverables

Spreadsheet

**Comment by ifrost** [comment]
Just to clarify a bit more, it's  about getting some real-life examples of correlations, something like:

Client A:
* Uses Graphite to query for her application errors: app=myapp type=error 
* Uses Loki to query for these application errors: {app="myapp" type="error"} and that query returns log lines like:
2000-01-01 11:12 app=mypp type=error msg="big bada boom"

or something more complex like:

Client B:
* uses Prometheus to query memory usage of her apps: memory_usage{app="myapp"}
* uses Loki to query for application logs: {application="myapp"}  and that returns log lines like:
2000-01-01 11:12 lvl=error type=application name=MYAPP msg="big bada boom"

It would help us to validate if our design will solve client problems and what direction we should take to make defining correlations between data.

For example, to make Glue work for Client A, we simply need to extract labels from metrics and extract labels from formatted log line messages and map them 1-to-1 to make metrics-to-logs and logs-to-metrics correlations work.
If Client B was a real case making logs-to-metrics would be more complex as we would need a couple of transformations:
from a line 2000-01-01 11:12 lvl=error type=application name=MYAPP msg="big bada boom"  we would need to extract MYAPP  from name part of the message if type=application , make it lowercase, and only then map it to app in Prometheus query: {app="myapp"}

These are just examples. We need not only metrics and logs but also traces for the full picture. Maybe most cases are as simple as Client A, and almost no one would ever need anything like Client B in the example but we’d like to know it so we can decide better how far we need to go with our design.

**Comment by ifrost** [comment]
Example: https://se-demo.grafana.net/d/eGMMFxk4z/metadata-sharing-across-your-tools?orgId=1

**Comment by josiahg** [comment]
https://docs.google.com/spreadsheets/d/1q2uTTo2yJ944zPIfEPDmZWR6qg1XfyEPW53tMAWj--U/edit#gid=0
