### ISSUE TITLE
[Question] no data showing up

### ISSUE THREAD

**Issue by tc0208** [grafana/grafana#5196]
- What Grafana version are you using? grafana-3.0.4-1464167696.x86_64
- What datasource are you using? influxdb-0.13.0-1.x86_64
- What OS are you running grafana on? Centos-6.6

Hello,

I'm new to Grafana and have a question regarding graphing by using telegraf/influxdb on the remote machine.

I wanto to track system performance and I've installed telegraf-0.13.1-1.x86_64 on my host-A(centos-6.6), installed grafana-3.0.4-1464167696.x86_64 / influxdb-0.13.0-1.x86_64 on my host-B(centos-6.6).

I can see telegraf insert system metrics data to influxdb on host-B, but no data showing up on grafana dashboard(datasource works fine).

Thanks

**Comment by torkelo** [comment]
This is strange, this should work. 

can you show the query you specified in Grafana, and also open chrome dev tools and look at network tab, look at the request grafana makes and inspect (and paste here if you still dont understand), the response from InfluxDB

**Comment by tc0208** [comment]
please close it as it is configuration problem, sorry for inconvenience
