### ISSUE TITLE
Stacking graphs from CloudWatch doesn't work

### ISSUE THREAD

**Issue by fbrnc** [grafana/grafana#5198]
Hi guys,
not sure if I'm doing something wrong or if this is actually a bug, but I'm pretty sure I've seen this work before I upgraded to Grafana 3 (via Ubuntu apt-get).

I'm displaying data from a CloudWatch source and I'm trying to stack all the HTTPCode_Backend_* values. But when I enabled stacking the 5xx line disappears.

I also saw this happening with other data where graphs disappear when being stacked.

Thanks for you help :)
Fabrizio

Please include some basic information:
- What Grafana version are you using? 
3.0.4

- What datasource are you using?
CloudWatch ELB metrics 

- What OS are you running grafana on?
Ubuntu

- What was the expected result?
The graphs should be stacked correctly

- What happenend instead?
Instead the 4xx and 5xx disappear from the graph when stacking is enabled. 

![26-05-_2016_23-49-05](https://cloud.githubusercontent.com/assets/468820/15600097/b2ff240e-239c-11e6-8c50-05a2b00ac69f.png)
![26-05-_2016_23-48-08](https://cloud.githubusercontent.com/assets/468820/15600098/b300e352-239c-11e6-815e-280343a86895.png)

**Comment by torkelo** [comment]
try changing null value -> null as zero
