### ISSUE TITLE
Template variable "All" selection appears as "$__all"

### ISSUE THREAD

**Issue by kschang61** [grafana/grafana#5199]
Please include some basic information:
- What Grafana version are you using? 3.0.4
- What datasource are you using? InfluxDB 0.13
- What OS are you running grafana on? CentOS 7.2
- What did you do? Upgrade from 3.0.2 to 3.0.4
- What was the expected result? "All" template selection (Include All option) shows all values (as in 3.0.2 or below)
- What happened instead? it show "$__all' as attached.

![image](https://cloud.githubusercontent.com/assets/19594247/15600824/0e0cfefc-241f-11e6-8ad4-dd6800e9df40.png)

**Comment by torkelo** [comment]
This is already reported and fixed :) 
https://github.com/grafana/grafana/issues/5172
