### ISSUE TITLE
Cloudwatch: refactor DataQueryJson to be action specific

### ISSUE THREAD

**Issue by asimpson** [grafana/grafana#52001]
`DataQueryJson` is only used once in [`cloudwatch.go`](https://github.com/grafana/grafana/blob/05cdef50040c06bf7e876a3b99a997ea4e826cc1/pkg/tsdb/cloudwatch/cloudwatch.go#L347). It would be better for [each action function](https://github.com/grafana/grafana/blob/05cdef50040c06bf7e876a3b99a997ea4e826cc1/pkg/tsdb/cloudwatch/cloudwatch.go#L347-L370), e.g. `executeAnnotationQuery`, to `Unmarshal` to a specific struct instead of the generic `DataQueryJson`. 

Another goal would be to possibly move `executeLogAlertQuery` to `log_actions.go`?

This idea came from a  [discussion](https://github.com/grafana/grafana/pull/51062/files#r901319128) with @sunker in #51062

**Comment by sarahzinger** [comment]
@asimpson sounds like this is more a code clean up task than a pressing bug yeah? I'm going to move this to the backlog if that sounds ok to you?
