### ISSUE TITLE
[Bug] Template `Interval variable` value `auto` is displayed as `$__auto_interval`

### ISSUE THREAD

**Issue by decentlab** [grafana/grafana#5200]
This issue is related to #5172. Once #5172's fix 724a511995f70a84aa3e321cc9687b285b1ea732 is merged, the `auto` value is shown as `$__auto_interval`.

A screenshot is available at:
https://github.com/grafana/grafana/issues/5172#issuecomment-221857659

**Comment by torkelo** [comment]
can you test this again with latest master or v3.0.x branch? fail to replicate it now.

**Comment by decentlab** [comment]
724a511  seems to be the HEAD of v3.0.x currently. I'm gonna check it with master. Thanks.

**Comment by decentlab** [comment]
It's been fixed now. Apparently with bf90fbc6786e6185100431717f709b2808086095.
