### ISSUE TITLE
How to have a graph with percentage (only until 100%) for y-axis-2 and have integer for y-axis-1 (this could be count of field values) in grafana 3.0.4

### ISSUE THREAD

**Issue by chigurupati** [grafana/grafana#5201]
Hello,
I have an usecase where I want to have two different values types for y-axis 1 and 2:
I want to show the number of success vs failed requests with bars on y-axis 1 and show percentage of success requests on top of these bars (just a line), so % on y-axis 2. so thinking like in the below image.

![capture](https://cloud.githubusercontent.com/assets/11277338/15602957/6b33b2aa-23f8-11e6-986c-2082e2d53271.JPG)

for example: 
For y-axis-1: I want to have just integers. ex: 10 - 300 (this could be the count of requests). 
For x-axis-2: I want to have % until 100% 

is this possible with grafana? because when I apply stacked and percentage it applied to both the y-axises. and I can't separately override (remove) for y-axis-1.

Please help to develop this scenario. Many thanks.

Regards,
Amarnath

**Comment by torkelo** [comment]
dont use stacked + percentage, that feature is not very good. 

Instead calculate percentage in your metric query.  Then assign those series to the right y axis, set axis unit format to percentage (to get the % label).

**Comment by chigurupati** [comment]
@torkelo 
ok. How can I calculate percentage in my metric query.? I am using influxdb as a data-source.

**Comment by torkelo** [comment]
not sure, Graphite has a asPercent function that allows you to calculate the percentage diff between to time series or whole queries. 

InfluxDB is not very good at complex queries and transformations , but you could ask in their mailing list or in Grafana mailing list if someone has found a solution

**Comment by chigurupati** [comment]
ok. thanks for the suggestion. Perhaps having to override percentage separately like other properties would be helpful in my opinion.

**Comment by torkelo** [comment]
well percentage is not a display option. (It is there but no one uses it because it is a little broken). 

Percentage calculations are best done in the metric query

**Comment by fala13** [comment]
I think I figured how to show percentage change over time with grafana and influxdb:
```
SELECT cumulative_sum("change") FROM (
SELECT difference("metric")/first("metric")*100.0 as "change" FROM "results" WHERE $timeFilter fill(previous)
)
```

**Comment by portfedh** [comment]
@fala13 This worked perfectly. Thank you very much!

**Comment by seatrain** [comment]
hello! Which type of visualization are you using?
