### ISSUE TITLE
Show context empty after refresh

### ISSUE THREAD

**Issue by aitchjoe** [grafana/grafana#52018]
**What happened**:

Show context empty after refresh window.

**What you expected to happen**:

Show context should display the surrounding logs.

**How to reproduce it (as minimally and precisely as possible)**:

1. Goto log browser and filter some logs.
1. Click "Show context" button on a log line, then surrounding logs displayed.
1. Refresh the window.
1. Click "Show context" button on same line, but no other logs displayed except the original one.
1. Click "Run query" then "Show context", still same problem.
1. Goto home or any other page then go back and repeat step 1.
1. Click "Show context" button on a log line, the problem gone.
1. Refresh and the problem back.

**Anything else we need to know?**:

We checked the network calls in Chrome debug tools, and found the difference on `/api/ds/query` after clicked "Show context".

the request payload if no problem:

```
{
    "queries": [
        {
            "expr": "{app_instance=\"example\",cluster=\"example-cluster\",component=\"api\",container=\"example-api\",filename=\"/var/log/pods/example_example-api-6ccb895f9d-4lbkb_3fe840d5-d3db-4173-b5ff-2260584c5887/example-api/0.log\",job=\"example-api\",namespace=\"example\",node=\"example01.example-cluster.example.com\",pod=\"example-api-6ccb895f9d-4lbkb\",stream=\"stdout\",tenant=\"example\"}",
            "queryType": "range",
            "refId": "",
            "maxLines": 10,
            "direction": "backward",
            "legendFormat": "",
            "datasource": {
                "type": "loki",
                "uid": "PFBF92862F95315B6"
            },
            "datasourceId": 9,
            "intervalMs": 7200000
        }
    ],
    "range": {
        "from": "2022-07-11T04:17:24.357Z",
        "to": "2022-07-11T06:17:24.357Z",
        "raw": {
            "from": "2022-07-11T04:17:24.357Z",
            "to": "2022-07-11T06:17:24.357Z"
        }
    },
    "from": "1657513044357",
    "to": "1657520244357"
}
```

the request payload if there is problem (**the difference is expr is empty**):

```
{
    "queries": [
        {
            "expr": "{}",
            "queryType": "range",
            "refId": "",
            "maxLines": 10,
            "direction": "backward",
            "legendFormat": "",
            "datasource": {
                "type": "loki",
                "uid": "PFBF92862F95315B6"
            },
            "datasourceId": 9,
            "intervalMs": 7200000
        }
    ],
    "range": {
        "from": "2022-07-11T04:15:26.456Z",
        "to": "2022-07-11T06:15:26.456Z",
        "raw": {
            "from": "2022-07-11T04:15:26.456Z",
            "to": "2022-07-11T06:15:26.456Z"
        }
    },
    "from": "1657512926456",
    "to": "1657520126456"
}
```

and the response is 400:

```
{"results":{"":{"error":"parse error at line 1, col 2: syntax error: unexpected }, expecting IDENTIFIER"}}}
```

There are similar issue [Show context missing entries](https://github.com/grafana/grafana/issues/32044) but I think it is not same.

**Environment**:

- Grafana version: v9.0.2
- Data source type & version: MySQL 8.0.29
- OS Grafana is installed on: Ubuntu 20.04.4 LTS
- User OS & Browser: Chrome Version 103.0.5060.114
- Grafana plugins: Default

**Comment by zoltanbedi** [comment]
Can you please try 9.0.3 and see if the issue is still there? There were some issues with log row context that have been fixed.

**Comment by aitchjoe** [comment]
I have tried Grafana 9.0.3 in Chrome incognito window but got same error (the `expr` is empty).

**Comment by aitchjoe** [comment]
Hi, I have tried Grafana v9.0.4 (c256012971), this [release](https://github.com/grafana/grafana/releases/tag/v9.0.4) include “Fix show context not working in some occasions [#52458”](https://github.com/grafana/grafana/pull/52458), but I still got same error.

**Comment by svennergr** [comment]
Hi @aitchjoe,

thank you so much - that's a good observation and I am actually not quite sure, why this happened.
I will come back soon with an answer.

**Comment by svennergr** [comment]
Hi @aitchjoe,

again thanks a lot for your observation. Unfortunately the fix did not make it into the v9.0.4 release even though the generation of the changelog falsely included it.

You can either go with the version from the latest main or `v9.0.x` branch, which both include a bugfix. Or you can wait for next weeks 9.0.5 release, which will contain the bugfix.

**Comment by aitchjoe** [comment]
It is not a big bug so I will wait 9.0.5, thanks!

**Comment by aitchjoe** [comment]
I have upgraded to 9.0.5 and it is ok now, thanks!
