### ISSUE TITLE
Zabbix 6.2.0 breaks with grafana 9.0.2

### ISSUE THREAD

**Issue by taavit21** [grafana/grafana#52016]
Hello,

Zabbix 6.0.6 works perfectly fine with grafana. However when upgrading to Zabbix version 6.2.0 then all of our dashboards where showing "No data" although the data was in zabbix.

Best Regards
Taavi

**Comment by mellieA** [comment]
@taavit21 the zabbix plugin is community supported. I recommend opening an issue for the developer in their repository here: https://github.com/alexanderzobnin/grafana-zabbix/issues
