### ISSUE TITLE
[Feature Request] improve browsing through docs for a specific version

### ISSUE THREAD

**Issue by elouanKeryell-Even** [grafana/grafana#5202]
On the documentation pages, there is a drop-down menu to choose which version of grafana you want to read about. It works pretty well.

However, when you are in a documentation page, and you click on a link to another documentation page, the new page will be brought back to the latest version of grafana, which is obviously not what you want (you want to continue browsing through the docs of the specific grafana version you chose).

This has to be the lowest priority issue ever, but still I wanted to raise it ha ha

**Comment by torkelo** [comment]
I agree, this is strange. It used to stay with the version you selected. The navigation is now always using the "latest". strange

**Comment by torkelo** [comment]
this should be fixed (from now on). not for old doc pages however.
