### ISSUE TITLE
Docs: update Alertmanager docs

### ISSUE THREAD

**Issue by brendamuir** [grafana/grafana#52022]
Add a docs about which alertmanager to use best. 

Discussion/issue: https://github.com/grafana/grafana/discussions/45773

**Comment by armandgrillet** [comment]
This is mostly about putting https://github.com/grafana/grafana/discussions/45773#discussioncomment-2235732 in the docs as I see it in the discussion.

**Comment by brendamuir** [comment]
Added this info here: https://grafana.com/docs/grafana/latest/alerting/fundamentals/alertmanager/
