### ISSUE TITLE
GLDS-AutoSave Input

### ISSUE THREAD

**Issue by staton-hyse11** [grafana/grafana#52045]
Design system feature request! A design for inputs that (and other form elements) that are auto saving. So after save there is some feedback to user that the option was saved (easy for inputs with some green check animation maybe but trickier for other form elements). End goal would be to get rid of these update / save buttons in some form pages we have.

![Image](https://user-images.githubusercontent.com/101748563/178271932-30c83c5b-0729-4a1c-8d64-558a02515c00.png)

**Comment by staton-hyse11** [comment]
I'm working through some potential designs for this and am looking to use a _system feedback element_ as a new component to use in this auto-save element and in a new design for our "copy url" patterns.

[Figma design file](https://www.figma.com/file/44XtudFoU21ne08TN0UfDX/AutoSave-FIeld?node-id=0%3A1)

**Important Requirements for this**
- We will need clear guidelines on where this is component is able to used and where it should not be used.
- This component will need to be clearly different from field validation
- Visibility timing of this component will need temporary 
- Understanding save load on the system will be important to understand how viable this is and for how wide-spread it can be used.

**Comment by staton-hyse11** [comment]
@torkelo Wanted to give you eyes on this autosave component. 

Here is a [prototype for it](https://www.figma.com/proto/44XtudFoU21ne08TN0UfDX/AutoSave-FIeld?page-id=0%3A1&node-id=2%3A2605&viewport=512%2C293%2C0.47&scaling=min-zoom&starting-point-node-id=2%3A2605).

Let's chat if you have any questions or feedback

**Comment by torkelo** [comment]
@staton-hyse11 that looks really great!

**Comment by staton-hyse11** [comment]
(never connected these notes to this issue)
There was discussion with @JoaoSilvaGrafana and myself around some details of the autosave pattern today. In short:

- The addition of the autosave pattern will come with [field validation](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-input--with-field-validation). We found some fields that might get this don’t currently use our field validation
- To avoid confusing autosave status with validation, the green checkmark will be removed from the field
- A loading state will be include with the pattern after a set time to indicate the system is trying to update/save the field contents
- To avoid unnecessary saves we will need to check for changes before saving
