### ISSUE TITLE
Grafana 3 migration of scripted dashboard (requiredJS and datasources)

### ISSUE THREAD

**Issue by pieval** [grafana/grafana#5204]
I'm trying to migrate a Grafana v2 stack to Grafana v3 and I have a bug around requireJS:
Many of my actuals scripted dashboards have common generated graph parts that I've put into requireJS modules under /app/xxx and that I can load in my scripted dashboard with 
```
require(["xxx/my-module"], function (module) { ... });
```
It seems that  requireJS was not loaded and removed from Grafana v3 stack, can you confirm ?
Does it was replaced by other stuff that I can use in my scripted dashboards ?

Other question, does the datasource request works like in v2 using something like:
```
services.datasourceSrv.get(null).then(function (datasource) { ... }
```
to use the default datasource (or replacing null by the dsName for a specific datasource) ?

Finally is there are other things around scripted dashboard that were refactored during the v3 migration and that can cause error with old v2 dashboards ?

**Comment by torkelo** [comment]
yes, it  was replaced by systemjs (https://github.com/systemjs/systemjs) , you can load requirejs/amd files with systemjs so it should be easy to upgrade. 

yes, I think `services.datasourceSrv.get(null).then(function (datasource) { ... }` should still work

**Comment by calebtote** [comment]
Are there any docs for how to upgrade?
