### ISSUE TITLE
View Dashboard of multiple Organizations at same time

### ISSUE THREAD

**Issue by zzphamvanthanhzz** [grafana/grafana#5205]
Hi all,

I'm using Grafana 2.6 for monitoring our products.
I'm using Influxdb for my Datasource.

How can I view dashboard of multiple Organization at same tab.
Example: I have organization A and B. I want to open dashboard of A in a tab and dashboard of B in another tab. Now if I do so, an error occur:  **"message": "Unable to load datasource meta data"**

Thank you for your helps.

**Comment by utkarshcmu** [comment]
I do not think you can do that currently even with Grafana 3.0.

**Comment by torkelo** [comment]
This is not possible and will likely never be. Organizations where designed for two completely separate companies (isolated data sources, and dashboards, etc) to share a single grafana server. 

Sure the same user can be apart of many organization but then you have to select one that is active at any time. I know this is far from ideal for many as many use organizations to group dashboards and users into teams. Hope to have some other way to support that scenario.

**Comment by zzphamvanthanhzz** [comment]
Thank you for your explaination.
