### ISSUE TITLE
Time series panel legend table format does not right align values

### ISSUE THREAD

**Issue by selimt** [grafana/grafana#52066]
**What happened**:
When upgrading from the old Graph panel to the new Time series panel, the table legend no longer right aligns numeric values.

**What you expected to happen**:
The numeric values should be right aligned.

**How to reproduce it (as minimally and precisely as possible)**:
Edit the following panel: https://play.grafana.org/d/000000016/1-time-series-graphs?orgId=1&editPanel=13
Set the "Legend mode" to "Table"
Set "Legend placement" to "Right"
Add "Max" to "Legend Values".

It will look like this:

![image](https://user-images.githubusercontent.com/15021762/178339711-54830d8f-ca5e-4993-bd85-46e2c7855170.png)

**Anything else we need to know?**:
The old Graph panel correctly right aligns the numeric values.

**Environment**:
- Grafana version: 8.5.4
- Data source type & version: Prometheus
- OS Grafana is installed on: Cent OS 7.9
- User OS & Browser: Linux. Chrome.

**Comment by mellieA** [comment]
This is from 8.5.0 in the graph(old) visualization, I do see that all of the values are aligned to the right

![Screen Shot 2022-07-13 at 3 59 15 PM](https://user-images.githubusercontent.com/18175287/178843972-bae53df8-e39d-42b4-b96d-5a741cc07c9c.png)
