### ISSUE TITLE
Migration: Impression server should be based on UID, not IDs

### ISSUE THREAD

**Issue by ryantxu** [grafana/grafana#52065]
In an effort to remove dependencies on internal IDs, we should update the https://github.com/grafana/grafana/blob/68757cfa73cb675b8f3013f5e33a0e43ae40849a/public/app/core/services/impression_srv.ts#L9

So we track and manage UIDs in the frontend, not numeric IDs.

Right now the numeric IDs need to be converted to UIDs before we can use them:
https://github.com/grafana/grafana/blob/5ad27679549d6c9f2ea49a1fcb5ef9de6754ff1c/public/app/features/search/page/components/FolderView.tsx#L37-L38

In addition to this... it seems the impression server does not save values unless *something* has been starred -- I don't know if that is a related or independent bug

**Comment by lpskdl** [comment]
Hi @ryantxu ,

Nice to meet you :) I will be working on this ticket :)

I would like to ask if you still encounter the issue about impression server stated above? I'm trying to replicate it but Im not successful. I've attached a video of how I tried to replicate it.

Do you think it was fixed already or I'm not doing the scenario the right way

https://user-images.githubusercontent.com/108552997/182177705-e8d86475-737e-4d91-a71d-9d633360443a.mov

cc: @axelavargas
