### ISSUE TITLE
Filter and modify with named "text" "value" groups does not seem to work as described

### ISSUE THREAD

**Issue by aramnhammer** [grafana/grafana#52072]
**What happened**:
Running Grafana V9.0.2 with a Postgres datasource and the following relations:

```
sensors: id(uuid), name(text)
analog_sensors: sensor_id(uuid), value(real)
```
Where sensor_id is a foreign key to id

I am creating a time series dashboard, and I want to have a dropdown of sensor names for people to select. To avoid a join on the `analog_sensors` table to get the name of the sensor, I am creating a variable and trying to regex the 'text' and 'value' fields so we can query directly by `sensor_id` under the hood.

**What you expected to happen**:
I would expect the following to work (regex using named capture groups, for text and value)
<img width="1728" alt="image" src="https://user-images.githubusercontent.com/11874593/178369793-a6f9fdde-1a84-46eb-a8c4-dbd70e6bfcf7.png">

... but that does not work. We get None.

So I tried exactly as it was specified in the document (adding the "|" instead of the "," as the separator in the regex string), which results in this:
<img width="1602" alt="image" src="https://user-images.githubusercontent.com/11874593/178369728-015528f9-8899-4ee8-8c08-3d60a4986470.png">

NOTE: I blacked out some sensor names.

...This looks like a mix of "id" column and "name" column, which is definitely not what we want. And on the panel dropdown, it shows a mix of both.

**How to reproduce it (as minimally and precisely as possible)**:
Using a Postgres datasource with a table of descriptors (id, name) and a table of values(id, value) and try to create a variable that regexes the "text" part (name) and "value" part (id)

What am I doing wrong here? Is this a bug? 

Both regex (the text group and value group work separately, and I verified them against the entire return value when I query the database from outside of Grafana.

**Environment**:
- Grafana version: 9.0.2
- Data source type & version: PostgreSQL 11
- OS Grafana is installed on: Docker (Mac OS Monterey)
- User OS & Browser: safari
- Grafana plugins: N/A

**Comment by mellieA** [comment]
@aramnhammer is this the documentation you're following? https://grafana.com/docs/grafana/latest/variables/filter-variables-with-regex/#filter-and-modify-using-named-text-and-value-capture-groups
 
Can you provide a sample of the query result you're trying to apply the regex to? Something similar to what's shown there in the docs would help us to understand the problem more clearly. Feel free to change names or UIDs for security.

**Comment by aramnhammer** [comment]
Hi @mellieA , thanks for the response. 

Yes I am looking at that documentation, a sample query result would be as follows:
```
Chamber O2, <uuid>
```
Where the `text` would be the sensor by its common name, while the `value` would be its uuid (which would never change)

Here is a gif of a real result and the regex that was used to match its parts.
![Screen Recording 2022-07-15 at 9 23 52 AM](https://user-images.githubusercontent.com/11874593/179232462-c2d6a1db-6688-4584-adfb-4ec9a92873b3.gif)

**Comment by aramnhammer** [comment]
More info:

Lets say my database query returns the following: 
```
Chamber O2,123e4567-e89b-12d3-a456-426655440000
```
Where the text before the comma is what I would consider a human readable name, and the uuid after the comma being its internal ID. 

Because names can be changed (Chamber O2 -> ChamberO2 or chamberO2), it would be great to have the name be used only when a person modifying the query variables in the dashboard, otherwise when the variable is selected, in the query the uuid is used instead of the name. 

the regex I thought would be appropriate for this task was the following (querying from PostgreSQL):
```
(?<text>.*),(?<value>[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12})
```

Testing this regex on a result from this query seems to work:
<img width="948" alt="image" src="https://user-images.githubusercontent.com/11874593/179527069-88b49743-f9fc-46e3-a29a-d2cf3d4c0b3b.png">


But in grafana, it does not seem to produce any values at all:
<img width="1444" alt="image" src="https://user-images.githubusercontent.com/11874593/179527001-1cb5def3-dab9-4941-a0a7-3073ed878bb9.png">

Perhaps I am misunderstanding how this is supposed to behave but from the documentation it seems to be what Id expect from reading

> Using named capture groups, you can capture separate ‘text’ and ‘value’ parts from the options returned by the variable query. This allows the variable drop-down list to contain a friendly name for each value that can be selected.

**Comment by ivanortegaalba** [comment]
Hi @aramnhammer, the issue is related how you're doing the MySQL query. Since you're selecting 2 different cols, they will come as independent values. Try to concat them:
```sql
SELECT
  CONCAT(Name, '-',
  ID)
FROM city LIMIT 10
```
Then you can use a simple regex to split them in name and value: `(?<text>.*)-(?<value>.*)` and this is the result:

![Captura de Pantalla 2022-07-20 a las 14 24 18](https://user-images.githubusercontent.com/5699976/179981029-41bb5f57-fd97-41d8-b5a7-e619649ae68f.png)

The value of that variable will be the ID.

**Comment by aramnhammer** [comment]
@ivanortegaalba Thanks so much, looks like that works!

Last question would be if there is a way to reference the `text` portion of the variable when displaying the `value` portion of the query in the panel, seems the `value` portion of the variable (which is a UUID) is displayed when the panel legend is created.

**Comment by ivanortegaalba** [comment]
> @ivanortegaalba Thanks so much, looks like that works!

Awesome! 🎉 

> Last question would be if there is a way to reference the `text` portion of the variable when displaying the `value` portion of the query in the panel, seems the `value` portion of the variable (which is a UUID) is displayed when the panel legend is created.

Can you attach some screenshots to understand better? Thanks!

**Comment by ivanortegaalba** [comment]
@aramnhammer to define what attribute goes to the legend, you should modify your query and use the name instead.
If you check the MySQL instructions you will find the following
![Captura de Pantalla 2022-07-25 a las 19 22 25](https://user-images.githubusercontent.com/5699976/180837719-2bad823b-1ef7-4bc0-a9a1-8bc5ac16ac13.png)

Which explains if you name a column as `metric` it will be used as a label. Hopefully it helps :)

**Comment by aramnhammer** [comment]
@ivanortegaalba thanks, but ideally Id like to use the name regexed from the variable and not have the name `metric` for everything.

**Comment by ivanortegaalba** [comment]
The name "regexed" is used to compose the variable pickers. They are independent of the query performed in the panel, so there is no other way to populate this around the global context. Actually, it doesn't make sense from the product perspective.
The panel can be moved between dashboards so the query must be self-contained. I'd suggest to configure properly all the data sources since that's the standard way to get the visualizations configured out of the box.

**Comment by aramnhammer** [comment]
@ivanortegaalba I see. Thanks for those reasons.
