### ISSUE TITLE
Template query update returns error

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5208]
I have a template query that runs fine on one dashboard and throws 
Templating
Template variables could not be initialized: b.metricFindQuery is not a function

on a different dashboard.

How is that possible ?

Dashboard 1 (after update)
<img width="1338" alt="screen shot 2016-05-27 at 7 06 23 pm" src="https://cloud.githubusercontent.com/assets/406777/15624954/d8a3cc8c-244b-11e6-9bc1-16fd9dea7f02.png">

Dashboard 2 (After update)

<img width="1375" alt="screen shot 2016-05-27 at 7 06 44 pm" src="https://cloud.githubusercontent.com/assets/406777/15624955/e097f346-244b-11e6-84f2-7d81a1454246.png">

How do i fix it ?

**Comment by torkelo** [comment]
Make sure you picked the right datasource for the template query :) looks like you picked a datasource that does not support templating
