### ISSUE TITLE
Grafana API : adding a user in a org fails with the message LoginOrEmail : required

### ISSUE THREAD

**Issue by mytuxfr** [grafana/grafana#5209]
Hi,

I'm using Grafana 3.0.4-1464167696. Trying to add a user in an organization using the Grafana API results in an error message. I use the Python request library to send the post request.

My request: http://127.0.0.1:3000/api/orgs/15/users (the org with the id 15 currently exists)
Json payload : "loginOrEmail" : "johndoe" (this user currently exists), "role" : "Viewer"

The error message : 
```
[{"fieldNames":["LoginOrEmail"],"classification":"RequiredError","message":"Required"}]
```
From the API documentation I should provide a "loginOrEmail" and a "role" field. I'm puzzled why the LoginOrEmail in the error message has a capital letter "L" while in the documentation it is not a capital letter.  It seems in the code it is "loginOrEmail" which is expected. Anyway I tried both (capital and not capital letter for the first letter of loginOrEmail and could not succeed.

The log in grafana.log is the following one:
```
2016/05/29 11:36:44 [I] Completed 127.0.0.1 - "POST /api/orgs/15/users HTTP/1.1" 422  87 bytes in 41069us
```

**Comment by mytuxfr** [comment]
Ok I succeeded adding the user to a org  directly injecting the content of a json file. You can close the ticket if it is a normal behaviour for you.

**Comment by Joannou1** [comment]
Also having this issue, any ideas?
Using PHp with curl, everything else EXCEPT this works.

	```
return post("/orgs/$orgid/users", array(
		'loginOrEmail' => $user,
		'role' => $role
	));
```
