### ISSUE TITLE
Explore: better auto-detection of log-data

### ISSUE THREAD

**Issue by gelicia** [grafana/grafana#52109]
### Discussed in https://github.com/grafana/grafana/discussions/44637

<sup>Originally posted by **gabor** January 31, 2022</sup>
in explore, when data comes in, we detect what visualization to use.. we do it in two ways:
- if the dataframes have a preferred-visualization-type setting, we use that
- if not, we look at the shape of the data, and guess (for example, `isTimeSeries` here : https://github.com/grafana/grafana/blob/main/public/app/features/explore/utils/decorators.ts#L177-L182 )

there are cases where log-data comes in that does not have the preferred-visualization-type field set. for example, InfluxDB Flux queries that return timestamp+text data. (NOTE: a Flux query can return basically any data, metric, logs, etc.)

for these cases it would be great if explore could better autodetect this.

a couple potential approaches:
- similar to `isTimeSeries` add an `isLogs` function
- currently we have the visualization-suggestions in dashboards... we could maybe use that logic to choose the visualization in explore?
- ~add a way where the user can pick the visualization (logs/metrics/etc.) for every query in explore~ we can look into this in the future but this should not be part of this ticket - we can open a new ticket with something like this if we want it later, but it will require some significant design changes.

**Comment by Elfo404** [comment]
FWIW dataplane has a draf/proposal to formally define log data: https://grafana.github.io/dataplane/logs/
