### ISSUE TITLE
[Feature Request] Support InfluxDB's SPREAD function.

### ISSUE THREAD

**Issue by OrangeTux** [grafana/grafana#5211]
InfluxDB 0.12 added the [SPREAD()][1] function. Although #4698 is about adding this this and a few other functions, the SPREAD() function hasn't been implemented yet. 

[1]:https://docs.influxdata.com/influxdb/v0.13/query_language/functions/#spread

**Comment by bergquist** [comment]
Thank you for reporting this. This fix will be released in 3.1.0 and nightly build http://grafana.org/download/builds.html
