### ISSUE TITLE
Regex support in elasticsearch metrics alias pattern

### ISSUE THREAD

**Issue by soltiz** [grafana/grafana#5212]
Metrics field are often longer than wished in a legend.
Example: topbeat ==> "cpu.idle", "cpu.system", "cpu.user", "cpu.nice" 

a regex in alias pattern (like {{regex /cpu.(.*)/}} ) would allow more readible series names (here, only "idle", "user", "system"). This is especially powerful if we can chain it with {{term fieldname}} so as to transform terms values !!!

**Comment by charlescva** [comment]
Same. I have lookup values in my index.  e.g. 1, 2 ,3.  While I could create a new index, I think I would like to be able to Regex them. 1/httpd, 2/jboss, 3/auditd

**Comment by boernd** [comment]
+1

**Comment by dachenbach** [comment]
+1

**Comment by lucasrodcosta** [comment]
Related to #3545.  
Would be really nice to have this feature.

**Comment by lukanus** [comment]
+1

**Comment by tijlk** [comment]
+1

**Comment by amper43** [comment]
+1

**Comment by GedPL** [comment]
+1

**Comment by gekr** [comment]
+1

**Comment by MrSantamaria** [comment]
+1

**Comment by InspurKelly** [comment]
+1

**Comment by zhiyp** [comment]
+1

**Comment by holiiveira** [comment]
Is anyone working on this feature?
I'm interested in helping where needed.

**Comment by marefr** [comment]
@holiiveira you're welcome to contribute. No one else in working on this as far as I know. Please note that it's no guarantee that we'll accept your PR and/or it may take some time depending on how we see this feature fit. Right now there are no other core datasource having this feature so maybe this feature would be better to solve in a more generic way. However, how this generic way looks we don't know right now. 

If you want to open a PR you'll need to solve it both client and server side to support alerting.

**Comment by pathikmehta** [comment]
+1

**Comment by RubenDiaz** [comment]
+1

**Comment by davtex** [comment]
+1

I have two ES queries, both are simple "Count" metrics, unfortunately both of their names is "Count". I believe this prevents Grafana from displaying these next to each other (they are grouped by the same "group by") - this is not an issue with InfluxDB at all since aliasBy is available. This also prevents me from using Meta Queries plugin.

**Comment by AlessandroLacroce** [comment]
+1

**Comment by magaton** [comment]
+1

**Comment by smurfix** [comment]
Same here. Use case: My host names are stored as-is as tags in the time series databases, and I need to have a generic way to drop the domain part. :-/

**Comment by vmitris** [comment]
+++1

**Comment by danielmotaleite** [comment]
This is most useful in elasticsearch, but sadly, after 4 years, still no way to do this.
While a generic way to do this in all data sources is awesome, trying to aim just for that may be harder and block this features for several years. It is better to add this just to elasticsearch and then expand or rewrite if it is found a better way

**Comment by sujay1109** [comment]
+1

**Comment by Daphneitec** [comment]
+1
