### ISSUE TITLE
Alert messages malformed after upgrade to Grafana 9

### ISSUE THREAD

**Issue by lukma99** [grafana/grafana#52133]
**What happened**:
We upgraded from Grafana 8.5.0 to 9.0.2 and everything works fine except our alerting messages. These are sent to Google Chat. Before the upgrade the messages were nicely formatted. Now we just receive all kind of metadata in the messages, which makes them harder to read. Also the `Open in Grafana` Link is broken and leads to `/alerting/list` instead of the source dashboard of the alert.

Grafana 8.0.5:
![Grafana_8.0.5](https://user-images.githubusercontent.com/47565816/178685683-b84c8930-857c-41da-8107-7bacb8580399.png)

Grafana 9.0.2:
![Grafana_9.0.2](https://user-images.githubusercontent.com/47565816/178685745-5034dac0-9821-4238-b698-c38b8defbf91.png)

Other people seem to have the same problem with other providers such as Slack or E-Mail:
- https://community.grafana.com/t/v9-alerts-converted-but-i-have-some-questions/67746
- https://community.grafana.com/t/slack-notification-grafana-9-not-working/68570
- https://community.grafana.com/t/is-there-a-way-to-make-grafana-9-slack-alerts-prettier/67505

**What you expected to happen**:
I expected, that the alerts, despite the migration, still look the same as before.

**How to reproduce it (as minimally and precisely as possible)**:
- Having existing alerts in Grafana 8.5.0
- upgrading to 9.0.2

**Anything else we need to know?**:
- Grafana installed with official Helm Chart in Kubernetes Cluster

**Environment**:
- Grafana version: 9.0.2
- OS Grafana is installed on: Kubernetes with official Grafana Helm Chart
- User OS & Browser: Ubuntu 20.04 + Chromium

**Comment by bushig** [comment]
Are there any updates on this issue?
Having the same problem with slack alert messages.
<img width="507" alt="image" src="https://user-images.githubusercontent.com/2815779/179476829-5005687a-b0ef-4fdc-981f-7a7c634ee1c6.png">
<img width="626" alt="image" src="https://user-images.githubusercontent.com/2815779/179477042-25053c46-1465-439c-badd-eea613862639.png">

**Comment by mellieA** [comment]
@lukma99 @bushig I created a detailed response to a community member yesterday with an example of how to clean up these notifications using Annotations and a message template: https://community.grafana.com/t/custom-alert-templates-not-working/67537

What's happening is that the labels are stored in a map and that is what's being returned for Value. But there is a way to pull out only the labels and values you want to show in a neater presentation. 

If you were using legacy alerting before the upgrade, you'll also want to enable images in notifications for the ones that are associated with a panel (the configuration has changed) - those docs are [here](https://grafana.com/docs/grafana/latest/alerting/images-in-notifications/) 

I'll close this issue for now - you can comment on the thread I linked with questions
