### ISSUE TITLE
Value mapping regex incorrect work on version 8.3.4, (.*) not work

### ISSUE THREAD

**Issue by VovkaSOL** [grafana/grafana#52132]
Hi friends, i connect elasticsearch to grafana, receive raw data with json like:

`Отправка ответа ru.mts.multitransfer.api.protobuf.fee.get_calculated_fee.GetCalculatedFee.Response: commissionId: "56c45fa4-7202-ed11-b4a1-0050560b354e" paymentSystemId: "05026663-103f-4a30-a91a-ae43f4bfc702" countryCode: "ARM" nameCyrillic: "Юнистрим" accepted_money { currency_code: "RUB" amount: "70700.00" } withdraw_money { currency_code: "RUB" amount: "70000.00" } accepted_total_fee { currency_code: "RUB" amount: "700.00" } transfer_money { currency_code: "RUB" amount: "70000.00" } rate: "1.000000" terminalCode: "AXRW"`

i add override with message field value mapping with regex:
(.*)
![image](https://user-images.githubusercontent.com/52788297/178679593-b9421161-57c1-4298-a0bb-be555457afa6.png)

it don't work, but if i add regex 
([^>]+)
it work as espected
![image](https://user-images.githubusercontent.com/52788297/178679204-fc98083d-2fd2-40d9-ae90-ae70b5a5c7d6.png)

2 days i try to understand why, try to add transform field type to String, add Cell dispay mode=Color text. But .* pattern not match all on json messages. I think it is bug. Thank's for any feedback

**Comment by zoltanbedi** [comment]
I was not able to reproduce this in 9.0.0/4.
![Screenshot 2022-07-22 at 13 55 42](https://user-images.githubusercontent.com/13729989/180434213-bb170769-42d4-4026-a995-f5f061a10125.png)
