### ISSUE TITLE
InfluxDB and Grafana: Sum up network traffic from different Interfaces but same location 

### ISSUE THREAD

**Issue by StevePham88** [grafana/grafana#5214]
Hi there, 
I have a system that need to be monitored. Im using InfluxDB for storage and Grafana for visualuize, We have a few different Interfaces but they are on the same location. I can get statistic for each interface individually but how can i get the statistic for those which on the same location. 
I use InfluxDBClient Python to get the performance data then insert to InfluxDB
For ex: 
Interface1: Inbound/Outbound - 1555.52	/1862.34
interface2: Inbound/Outbound - 100002	/180000

**Comment by bergquist** [comment]
Influxdb does not support summerizing different series so the best you can do right now is to have one query per interface and use template variables for filtering http://docs.grafana.org/reference/templating/ and set the graph panel to stack the values.

**Comment by StevePham88** [comment]
Sorry but Im not quite understand, i think u are right about 2 different query per instance but what things i need to filter and how to stack the value? Thanks

**Comment by torkelo** [comment]
@StevePham88 if you have your location in an InfluxDB tag you can group by that tag

**Comment by StevePham88** [comment]
@torkelo : But i need the graph which show statistic of the whole location including 2 interfaces. Thanks

**Comment by torkelo** [comment]
Well the group by interface and location tag

**Comment by StevePham88** [comment]
@torkelo : Hi Torkelo, sorry for lack of explanation. The thing is i want to get the sum of each record to draw the traffic on one location.
For ex: These 2 interfaces are on the same location
Interface1: Inbound/Outbound - 1555.52 /1862.34
interface2: Inbound/Outbound - 100002 /180000
What i wanna have is the graph show: 
Inbound = Inbound of Int1 + Inbound of Int2 = (1555.52  + 100002)
Outbound = Outbound of Int1 + Outbound of Int2 = (1862.34+180000)
and many numbers rest.... 
@bergquist: Can you please suggess? 
Thanks

**Comment by bergquist** [comment]
@StevePham88 Influxdb does supports summarizing multiple series into one. But you could start writing the data into one serie named "interface" and have a tag for each interface (ex Interface1,Interface2)

A solution just for graping the data would be to use stacked values. like this http://play.grafana.org/dashboard/db/issue-5214

**Comment by StevePham88** [comment]
@bergquist: Thanks, you help me alot. As my understanding, after stacked
"payment.ended.mean" becomes the total of "started + ended", so how can i hid the line of started and change name of "payment.ended.mean" to something likes "payment.total"
