### ISSUE TITLE
[Feature]: Delay loading & Lazy load panels as they become visible (scrolled into view)

### ISSUE THREAD

**Issue by torkelo** [grafana/grafana#5216]

**Comment by jifwin** [comment]
I could take care of that feature. Actually I already have it working for Grafana 3.0, but I decided to use a little bit different approach than in https://github.com/grafana/grafana/tree/lazy_panels. One more thing: do you think it should be configurable (an option to enable/disable load on scroll for given dashboard)?

**Comment by torkelo** [comment]
not sure (if it should be an option), depends on how good it works and if it has any drawbacks. But if it works well could see it being the default behavior (without any option to disable it)

**Comment by jifwin** [comment]
I've submitted a PR #7452 . Let's discuss that there.

**Comment by inbilla** [comment]
IMO, I'd be keen to have it configurable, some of my queries can take some time to execute , so in many cases I'd prefer not to have any user interaction required to get them to load up. Definitely an option I'd like to have available to use though.

**Comment by jifwin** [comment]
At which level would you like it to be configurable? Organization? Dashboard? User?

**Comment by inbilla** [comment]
I'd say per dashboard personally

**Comment by torkelo** [comment]
@inbilla you consider scrolling down user interaction? (I mean it is but very passive, automatic)

 Would you not prefer to not issue those time consuming expensive queries for panels you might never even see?

**Comment by inbilla** [comment]
@torkelo it depends on the dashboard. I do have some that are a few pages long, with many panels repeated. Imagine a list of 20 applications that I'm tracking metrics in, with each row showing health information about each application. So each application has 5 metrics. I currently load the page, then switch to doing something else while it loads all the data, then scan through. If I were to scroll, then I would be presented with no data for around 30s while it loads. It just adds extra steps for my workflow.

**Comment by torkelo** [comment]
You have queries that take 30 seconds? Wow, seldom seen queries that take more than a second,,  usually a couple of milliseconds, but depends on backend I guess.

With queries that take that long I agree that you it could be a problem, but with queries that take that long won't they stress you backend a lot, and having them only loaded on demand make your backend less under stress and load queries quicker?

**Comment by inbilla** [comment]
Yeah, in this case the influxdb backend is on the other side of the world and we are connected to it through a slowish connection. 

I agree the feature is great for managing load on both the users machine and the server... I'll certainly enable it on many boards. But I also know I'll wish it was configurable for the cases I'm thinking of.

**Comment by jifwin** [comment]
Ok, I ill work on my PR to make it configurable

**Comment by jifwin** [comment]
Updated.
