### ISSUE TITLE
Bug report - ldap last admin org

### ISSUE THREAD

**Issue by xploit42** [grafana/grafana#5217]
Hello,

My users connect to grafana via ldap. They all get admin role on org1.

I connect with admin account (not ldap), i create org2, i add an ldap user (will call him john).
I remove admin user from org.

Now John can't connect, with error message "Error while trying to authenticate user"
And in grafana.log:

2016/05/30 15:43:18 [login.go:102 LoginPost()] [E] Error while trying to authenticate user: Cannot remove last organization admin

If I add another user to org2 with admin role, both can connect, if i remove John, the other user can't connect.

Regards

**Comment by torkelo** [comment]
if you use LDAP you can only use ldap group mappings to specify which user should belong to which role and role.

So for john does he belong to an ldap org that is matched to org2?

**Comment by xploit42** [comment]
Nop, i manualy add him, and works fine with 2 admins! :)

So in my usage, I will let admin user be admin of all orgs to avoid this problem, i just wanted notice this.

**Comment by torkelo** [comment]
so do you have an admin ldap group that you then map to the two orgs in ldap.toml? or are all users admin in both orgs? 

Not sure what your trying to do. 

>I remove admin user from org.

Why? 

Anyway. the LDAP login will try to match the ldap.toml group mappings on login, so if a user belongs to organizations that is not defined in ldap.toml Grafana will try to remove that user from that org. If the user is the only admin left in that Org then Grafana cannot remove that user from that Org as it will leave the org without an admin user.

**Comment by xploit42** [comment]
Ok, in ldap conf i just map all users of my ldap group to org1 with admin role, and i wanted to manage roles for other orgs directly on grafana.

> Anyway. the LDAP login will try to match the ldap.toml group mappings on login, so if a user belongs to organizations that is not defined in ldap.toml Grafana will try to remove that user from that org. If the user is the only admin left in that Org then Grafana cannot remove that user from that Org as it will leave the org without an admin user.

I guessed it was something like that
