### ISSUE TITLE
Missing caveats with root_url configuration parameter

### ISSUE THREAD

**Issue by itsmrwave** [grafana/grafana#5218]
This isn't a bug per se. If the documentation is clear ... the user/implementer shouldn't have an issue. That said, I just wanted to highlight what I _think_ is an issue.

I have Grafana (Docker) listening on `0.0.0.0:3000` on the container and that port is mapped to port 80 on the host and a load balancer in front of it forwarding 443 and 80 on the ELB to 80 on the host. With the config below ... the `redirect_url` has this ...

```
redirect_uri=http%3A%2F%2Fmonitor.example.com%3A3000%2Flogin%2Fgithub&response_type=code&scope=user%3Aemail%2Cread%3Aorg
``` 

... since the ELB is on `http://monitor.example.com` and `https://monitor.example.com` we will always end up with a redirect loop (see config below).

Relevant bits in config file:

```
[server]
protocol = http
http_addr = 0.0.0.0
http_port = 3000
domain = monitor.example.com
enforce_domain = true
root_url = %(protocol)s://%(domain)s:%(http_port)s/
router_logging = true
static_root_path = public
enable_gzip = true

[auth.github]
enabled = true
allow_sign_up = true
client_id = xxxxxxxxxxxxx
client_secret = xxxxxxxxxxxxxxxxxxxxxxxxxx
scopes = user:email,read:org
auth_url = https://github.com/login/oauth/authorize
token_url = https://github.com/login/oauth/access_token
api_url = https://api.github.com/user
allowed_organizations = ExampleOrg
```

I guess the `root_url` should be the exact ELB domain as opposed to `%(protocol)s://%(domain)s:%(http_port)s/`. What do you guys think?

Some basic information:
- Grafana version? 3.0
- Datasource - don't think this matters.
- Session store - MySQL
- Linux - official Docker images i.e. `grafana/grafana:3.0.3`
- What did I do?
  - Create app on GitHub and got the keys
  - Added details for Grafana config file
  - Tried to log in via Grafana
- What was the expected result?
  - Successful log in
  - User created on session store
- What happenend instead?
  - Endless redirect loop

**Comment by torkelo** [comment]
according to the docs

root_url
This is the full URL used to access Grafana from a web browser. This is important if you use Google or GitHub OAuth authentication (for the callback URL to be correct).

So for your case it set it to `https://monitor.example.com`

**Comment by itsmrwave** [comment]
@torkelo Well, that was quick! Thanks. I suspected as much.
