### ISSUE TITLE
Grafana 7.4.5 => 7.5.0 + 

### ISSUE THREAD

**Issue by pep3l** [grafana/grafana#52197]
Hello all! 
Sorry for my english, its translate.
After updating Grafana from 7.4.5 to 7.5.0, something has changed in sending mail. Those. I tried all versions of grafana, starting from 4. and ending with 9.1, before version 7.5.0, sending mail works, after version 7.4.5, sending stopped working.

I'm trying to send mail through my organization's smtp server

I don't understand why this is a bug or a feature. I did not find a solution in the search, and if it exists, please send it there.

My config SMTP is:
#################################### SMTP / Emailing ##########################
[smtp]
enabled = true
host = server:25
user = domen\user
password = """securitypass""
;cert_file =
;key_file =
skip_verify = true
from_address = user@domen
startTLS_policy = NoStartTLS
;from_name = Grafana

This config sends messages on all versions of grafana including version 7.4.5

And the same config does not send messages from grafana starting from 7.5.0 to the latest beta versions

my logs with error:

logger=context t=2022-07-14T09:40:15.67+0300 lvl=eror msg="Failed to send alert notifications" error="Failed to send notification to email addresses: email@domen: gomail: could not send email 1: 502 5.3.3 Command not implemented" remote_addr=127.0.0.1

The only thing I found between versions is that you entered the definition of what tls is. It's just a definition, I didn't find a word about it in the code.

**Environment**:
- Grafana version: all
- Data source type & version: email
- OS Grafana is installed on: WIndows Server 2019 \ Mac Os X 12.4
- User OS & Browser: Chromium
- Grafana plugins: not
- Others:

**Comment by pep3l** [comment]
> I think this is not grafana related more like something with your environment. Take a look at this https://serverfault.com/questions/640357/centos-smtp-error-command-not-implemented

I don't understand how it could be related. Sending messages takes place in all versions of grafana including 7.4.5, after this version of grafana sending does not work. How I checked: I took and downloaded the latest release of 4.x.x grafana and checked the sending - its works, then 5.x.x and checked again, and so on until I reached 7.5.0, where the dispreading stopped working. The question is, what has changed in this version and is it possible to fix it somehow?

**Comment by pep3l** [comment]
test telnet:

STARTTLS
220 2.0.0 SMTP server ready

**Comment by zoltanbedi** [comment]
You are probably hitting a firewall that's why you get back 502 Not implemented or it is something with tls. Have you tried using different startTLS_policy? Looks like you set it to NoStartTLS but your server expects it (STARTTLS). I couldn't find anything in the code related to this thats why I say that this is something on your side.

**Comment by pep3l** [comment]
I would guess it might be something on my side but then I don't understand why submit works on grafana 4.x.x<5.x.x<6.x.x<7.4.5 but on version 7.5.0<8.x.x<9.x.x and above doesn't work.

**Comment by pep3l** [comment]
the custom.ini file is the same on all versions I use

**Comment by zoltanbedi** [comment]
There is a note in Go 1.16's release notes that could be relevant:
net/smtp
> The Client’s Mail method now sends the SMTPUTF8 directive to servers that support it, signaling that addresses are encoded in UTF-8.

Maybe this change?

**Comment by papagian** [comment]
The `Command not implemented` is not a grafana error but returned [here](https://github.com/grafana/grafana/blob/b144fb1a9f3b307abfaa318e4431dd8fbb268929/pkg/services/notifications/mailer.go#L62) by [Dialer.DialAndSend()](https://github.com/go-mail/mail/blob/f59b9b83a4e522098e3d3eb94e6f81850ad6e973/smtp.go#L203)
Can you try changing `startTLS_policy` to `OpportunisticStartTLS` or `OpportunisticStartTLS ` and observe what happens? (as @zoltanbedi suggested)

**Comment by pep3l** [comment]
> 

I changed this parameter, but the error type is not affected.

**Comment by pep3l** [comment]
I tried to build grafana version 8.4.1 using golang version go1.15.15, I get an error like package io/fs is not in GOROOT (/usr/local/go/src/io/fs) saying that I am using too old compiler

**Comment by pep3l** [comment]
The ticket can be closed. The problem turned out to be that my e-mail was located on an exchange 2016 mailbox, which does not work correctly with the utf8 encoding, which is now strictly sent. Judging by the changes in the golang changelog. After migrating my account to the exchange 2019 server, the problem was solved.

**Comment by zoltanbedi** [comment]
Thank you for sharing the details with us @pep3l!
