### ISSUE TITLE
[Bug]  Template "all" value is as $__all after save

### ISSUE THREAD

**Issue by drewboswell** [grafana/grafana#5219]
When selecting all in a graphite templated variable, after saving and refreshing the following appears in stead of all "$__all". This breaks it's use as a template variable. When selecting all again it re-works, but is unable to save.

Example:
![screenshot from 2016-05-30 19-53-38](https://cloud.githubusercontent.com/assets/6523434/15655761/3be9dff6-26a0-11e6-92ba-c79b1692d60a.png)

\################
\# Version information
Grafana-server: 3.0.4
Server arch: Linux XEN x86_64 GNU/Linux

**Comment by bergquist** [comment]
Thank you for reporting this! 

This have been fixed by https://github.com/grafana/grafana/issues/5172 and should be available in the next release and nightly.
