### ISSUE TITLE
PNG exported panel has axis label in wrong orientation

### ISSUE THREAD

**Issue by conzyor34** [grafana/grafana#5220]
Using Grafana 3.0.4-1464167696 on Ubuntu, I export a panel to png via the option "Share" -> "Direct link rendered image". In the resulting image, the 1st Y axis label is in horizontal orientation instead of the usual vertical orientation seen in flot rendering.

As you can see in this example graph, the Y axis label "Temperature" is rendered in the wrong orientation:

![image](https://cloud.githubusercontent.com/assets/2005463/15658152/9acda2cc-267e-11e6-8744-38ea4fab2704.png)

Here is a screen-capture of the graph as it appears in the browser using flot:

![image_flot](https://cloud.githubusercontent.com/assets/2005463/15658241/8fad9e96-267f-11e6-80c6-e9e9d84af624.png)

Thanks for an awesome piece of software!

**Comment by torkelo** [comment]
strange, seems like phantomjs is ignoring the css rotation

**Comment by ekarak** [comment]
This bug appears to have resurfaced with grafana-4.0.0-1479719016beta2, phantomjs 2.1.1:
![application-performance-overview](https://cloud.githubusercontent.com/assets/587817/20524882/5eb197c2-b0c5-11e6-907c-46d6cb6b9943.png)

**Comment by conzyor34** [comment]
Agreed. After upgrading to grafana-4.0.0-1480439068, the y-axis label goes the wrong direction again.

![yum_install_urw_fonts](https://cloud.githubusercontent.com/assets/2005463/20820187/f64517ae-b7fe-11e6-9cbe-6818ac75df63.png)
