### ISSUE TITLE
[Feature Request] 1. Variable Selection in tree view and 2. Cross Rows Variable like Time-Range

### ISSUE THREAD

**Issue by ckdanny** [grafana/grafana#5221]
1. Let user to choose multiple items in tree view panel
    For example, in the following structure, user can check items/values that they want
    ```
$Device1
  ☑ A
      ☐ A1
      ☐ A2
      ☑ A3
          ☑ A31
          ☑ A32
  ☑ B
      ☑ B1
          ☑ B11
      ☑ B2
          ☐ B21
          ☑ B22
              ☑ B223
      ☑ B3
          ☑ .....
          ☑ .....
           .....
      ☐ B4

    ```
2. Cross Rows Variable like Time-Range
When Time-range is changed, all row/graph content are changed.
Is it possible to enable this features to customized variable like a global variable?

![2016-05-31 12_10_30-grafana - ultimate graphite query guide](https://cloud.githubusercontent.com/assets/11786201/15663061/320da3a8-2729-11e6-9e90-8237190785ab.png)

**Comment by torkelo** [comment]
Variables are global for the whole time range. 

Coud you describe more how the nested variable structure would work? 
1) How is the nested option tree created? manually? from metric names query? (what kind of query, how is the tree structure derived)
2) What does it mean? When A, A3 and A31, A32 are selected, what does that mean for this query: 
"my.query.$Device1.test" 

What will $Device1 be replaced with? A31 and A32 ?

**Comment by ckdanny** [comment]
1)
A variable contains multiple values
For example, a school has 5 rooms and each has 50 computers,
Data:
```json
{
"id" : "5678",
"path" : "Room1/Computer1"
}
```

*path* is split by "/", a tree list/ dropdown list generated

```
$SchoolComputer
☑ Room1
    ☐ Computer 1 (ID:1)
    ☐ Computer 2 (ID:2)
    ☑ Computer 3 (ID:3)
      ....
☑ Room 2 (if Room2 is checked, all the following items are checed)
    ☑ Computer 1 (ID:14)
    ☑ Computer 2 (ID:15)
    ☑ Computer 3 (ID:16)
     .....
....
```

It looks like this
![2016-06-01 14_26_27-jstree](https://cloud.githubusercontent.com/assets/11786201/15700639/bf79f6d6-2807-11e6-8529-fa6531625d6f.png)



2) When item is selected, the specific column will be joined by ","
For example , Room 2 and Room 1 Computer 3  is checked and ID is selected to join
The result will be -> 3, 14, 15, 16
That means `$SchoolComputer` will be replaced by (3, 14, 15, 16)


Many Thanks.

**Comment by torkelo** [comment]
You can create one variable that is Room and another one that is Computer. 

Here is one example of nested template variables using elasticsearch
http://play.grafana.org/dashboard/db/elasticsearch-templated

Another one using Graphite:
http://play.grafana.org/dashboard/db/templated-graphs-nested
