### ISSUE TITLE
loki: datasource-variable in dashboard causes stale label-browser-data

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#52215]
1. create two loki data sources
2. in a dashboard create a variable type=data_source
3. create a dashboard panel with the data-source being the newly created variable
4. if you start switching the datasource-variable-value, the label-browser in the query-editor does not update.

(for a video see https://github.com/grafana/grafana/issues/51355#issuecomment-1184200486  where it was reported originally)

**Comment by gabor** [comment]
after some investigation, it seems the datasource-prop the loki-query-editor receives is stale too, that will have to be fixed first, created an issue for that at: https://github.com/grafana/grafana/issues/52737

**Comment by matyax** [comment]
I wonder if this issue is still valid, since we are using a different editor since this issue  was created.

**Comment by matyax** [comment]
Tested locally and switching the datasource updates the instance and requests for new data.
