### ISSUE TITLE
Panel Search not working for imported Dashboard via API

### ISSUE THREAD

**Issue by Miccia94** [grafana/grafana#52212]
**What happened**: Panel Search is not working correctly for API imported dashboard. As soon as you search panels shows up, but instead of linking to the full view of the panel it redirect you to the dashboard containing the panel. As soon as you edit and save the dashboard the search start working correctly.

**How to reproduce it**: Import one dashboard via api, search the panel inside the imported dashboard. Search result has wrong link, all pointing too ?viewPanel=0, as soon you edit the dashboard it start working.

- Grafana version: 9.0.2

**Comment by FZambia** [comment]
@Miccia94 hello, thanks for the report!

We don't have the path which updates dashboard in search upon import now – we will fix this. But I can not understand why you see the panel in search – because it should be completely not visible in a search for some time after import (until next periodic re-index happens). So I can reproduce a missing panel in search after an import, but not a panel with wrong link after import. 

Just to make sure – you are using `panelTitleSearch` feature toggle right? Which exact API you are using (`/api/dashboards/import` or sth else)? Maybe you can provide a request so I could reproduce locally?

**Comment by Miccia94** [comment]
Hello @FZambia,

I can confirm im using `panelTitleSearch `toggle. Also i can cofirm that panels is immediately visible in the search with `?viewPanel=0`
Im using the `/dashboards/db` import path
This is the template used to import dashboard:
`{
  "annotations": {
    "list": [
      {
        "builtIn": 1,
        "datasource": {
          "type": "grafana",
          "uid": "-- Grafana --"
        },
        "enable": true,
        "hide": true,
        "iconColor": "rgba(0, 211, 255, 1)",
        "name": "Annotations & Alerts",
        "target": {
          "limit": 100,
          "matchAny": false,
          "tags": [],
          "type": "dashboard"
        },
        "type": "dashboard"
      }
    ]
  },
  "editable": true,
  "fiscalYearStartMonth": 0,
  "graphTooltip": 0,
  "id": 4091,
  "links": [],
  "liveNow": true,
  "panels": [
    {
      "collapsed": false,
      "gridPos": {
        "h": 1,
        "w": 24,
        "x": 0,
        "y": 0
      },
      "id": 1,
      "panels": [],
      "title": "title",
      "type": "row"
    },
    {
      "datasource": {
        "type": "alexanderzobnin-zabbix-datasource",
        "uid": "hKe3QKu7k"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 50,
            "gradientMode": "opacity",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "smooth",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "bps"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 0,
        "y": 1
      },
      "id": 2,
      "options": {
        "legend": {
          "calcs": [
            "lastNotNull",
            "min",
            "max",
            "mean"
          ],
          "displayMode": "table",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "application": {
            "filter": ""
          },
          "datasource": {
            "type": "alexanderzobnin-zabbix-datasource",
            "uid": "hKe3QKu7k"
          },
          "functions": [],
          "group": {
            "filter": "filter"
          },
          "host": {
            "filter": "filter"
          },
          "item": {
            "filter": "filter"
          },
          "itemTag": {
            "filter": ""
          },
          "options": {
            "disableDataAlignment": false,
            "showDisabledItems": false,
            "skipEmptyValues": false,
            "useZabbixValueMapping": false
          },
          "proxy": {
            "filter": ""
          },
          "queryType": "0",
          "refId": "A",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": {
            "type": "alexanderzobnin-zabbix-datasource",
            "uid": "hKe3QKu7k"
          },
          "functions": [],
          "group": {
            "filter": "filter"
          },
          "host": {
            "filter": "filter"
          },
          "item": {
            "filter": "filter"
          },
          "itemTag": {
            "filter": ""
          },
          "options": {
            "disableDataAlignment": false,
            "showDisabledItems": false,
            "skipEmptyValues": false,
            "useZabbixValueMapping": false
          },
          "proxy": {
            "filter": ""
          },
          "queryType": "0",
          "refId": "B",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        }
      ],
      "title": "title",
      "type": "timeseries"
    },
    {
      "datasource": {
        "type": "alexanderzobnin-zabbix-datasource",
        "uid": "hKe3QKu7k"
      },
      "description": "",
      "fieldConfig": {
        "defaults": {
          "color": {
            "mode": "palette-classic"
          },
          "custom": {
            "axisLabel": "",
            "axisPlacement": "auto",
            "barAlignment": 0,
            "drawStyle": "line",
            "fillOpacity": 50,
            "gradientMode": "opacity",
            "hideFrom": {
              "legend": false,
              "tooltip": false,
              "viz": false
            },
            "lineInterpolation": "smooth",
            "lineWidth": 1,
            "pointSize": 5,
            "scaleDistribution": {
              "type": "linear"
            },
            "showPoints": "auto",
            "spanNulls": false,
            "stacking": {
              "group": "A",
              "mode": "none"
            },
            "thresholdsStyle": {
              "mode": "off"
            }
          },
          "mappings": [],
          "thresholds": {
            "mode": "absolute",
            "steps": [
              {
                "color": "green",
                "value": null
              },
              {
                "color": "red",
                "value": 80
              }
            ]
          },
          "unit": "bps"
        },
        "overrides": []
      },
      "gridPos": {
        "h": 9,
        "w": 12,
        "x": 12,
        "y": 1
      },
      "id": 3,
      "options": {
        "legend": {
          "calcs": [
            "lastNotNull",
            "min",
            "max",
            "mean"
          ],
          "displayMode": "table",
          "placement": "bottom"
        },
        "tooltip": {
          "mode": "single",
          "sort": "none"
        }
      },
      "targets": [
        {
          "application": {
            "filter": ""
          },
          "datasource": {
            "type": "alexanderzobnin-zabbix-datasource",
            "uid": "hKe3QKu7k"
          },
          "functions": [],
          "group": {
            "filter": "filter"
          },
          "host": {
            "filter": "filter"
          },
          "item": {
            "filter": "filter"
          },
          "itemTag": {
            "filter": ""
          },
          "options": {
            "disableDataAlignment": false,
            "showDisabledItems": false,
            "skipEmptyValues": false,
            "useZabbixValueMapping": false
          },
          "proxy": {
            "filter": ""
          },
          "queryType": "0",
          "refId": "A",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        },
        {
          "application": {
            "filter": ""
          },
          "datasource": {
            "type": "alexanderzobnin-zabbix-datasource",
            "uid": "hKe3QKu7k"
          },
          "functions": [],
          "group": {
            "filter": "filter"
          },
          "host": {
            "filter": "filter"
          },
          "item": {
            "filter": "filter"
          },
          "itemTag": {
            "filter": ""
          },
          "options": {
            "disableDataAlignment": false,
            "showDisabledItems": false,
            "skipEmptyValues": false,
            "useZabbixValueMapping": false
          },
          "proxy": {
            "filter": ""
          },
          "queryType": "0",
          "refId": "B",
          "resultFormat": "time_series",
          "table": {
            "skipEmptyValues": false
          },
          "tags": {
            "filter": ""
          },
          "trigger": {
            "filter": ""
          },
          "triggers": {
            "acknowledged": 2,
            "count": true,
            "minSeverity": 3
          }
        }
      ],
      "title": "title",
      "type": "timeseries"
    }
  ],
  "refresh": "1m",
  "schemaVersion": 36,
  "style": "dark",
  "tags": [],
  "templating": {
    "list": []
  },
  "time": {
    "from": "now-24h",
    "to": "now"
  },
  "timepicker": {},
  "timezone": "browser",
  "title": "title",
  "uid": "NOCqFzR4z",
  "version": 1,
  "weekStart": ""
}`

**Comment by Miccia94** [comment]
@FZambia I saw that this should be fixed on 9.1 releases. Actually im on 9.1.4 but still getting the issue. Should i enable something besides panelTitleSearch flag?

Thanks
