### ISSUE TITLE
explore: exemplars option is missing in collapsed view when it is false

### ISSUE THREAD

**Issue by david-gang** [grafana/grafana#52239]
**What happened**:

In Explore view of prometheus data source it is not visible that the exemplars option is false in collapsed mode.

**What you expected to happen**:

The query option should show that exemplars is false

**How to reproduce it (as minimally and precisely as possible)**:

Go to metrics explorer

You will see this image.

<img width="525" alt="Screen Shot 2022-07-14 at 16 48 02" src="https://user-images.githubusercontent.com/1292882/178998509-245f5184-07c4-4638-81ec-d722fa689626.png">

There is nothing about exemplars.

But in the reality exemplars option is set to false as can be seen in the expanded view.

<img width="936" alt="Screen Shot 2022-07-14 at 16 48 15" src="https://user-images.githubusercontent.com/1292882/178998654-76c6f711-4a7c-4305-a0fd-757302b43054.png">

just if exemplars is set to true we see it in the collapsed view:

<img width="895" alt="Screen Shot 2022-07-14 at 16 48 35" src="https://user-images.githubusercontent.com/1292882/178998861-493e2efe-7b87-45df-918c-a3f6c87a6abc.png">

This is really annoying and it took us one day to understand why explore doesn't show us exemplars.

**Anything else we need to know?**:

**Environment**:
- Grafana version:9.0.3
- Data source type & version:prometheus
- OS Grafana is installed on:grafana cloud
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by mellieA** [comment]
verified this behavior - the exemplars state only shows when the slider is set to `true`

**Comment by david-gang** [comment]
I researched the issue a bit.

The problematic line looks here: https://github.com/grafana/grafana/blob/main/public/app/plugins/datasource/prometheus/querybuilder/components/PromQueryBuilderOptions.tsx#L132

I think that this was made because you show not always exemplars.

So it should be something like this in the lines:

```
if(shouldShowExemplarSwitch(query, app)) {
   if (query.exemplar) {
    items.push(`Exemplars: true`);
  }
 else {
  items.push(`Exemplars: false`);
 }
}
```

This is the rough idea.  In this case the function shouldShowExemplarSwitch should be renamed to shouldShowExemplars

If you would be interested i could craft a PR on this.
