### ISSUE TITLE
[Question] Elasticsearch / Table panel, is it possible to sort somehow table by multiple columns?

### ISSUE THREAD

**Issue by Turum** [grafana/grafana#5223]
Hi,
Build this table from json data/metric as raw document. I need to keep row with total always on the bottom and row with filled client code at the top.
![image](https://cloud.githubusercontent.com/assets/19665888/15672433/5e8b79fe-2739-11e6-8bf9-910c8ce20286.png)
Thanks.

**Comment by torkelo** [comment]
Sorry, this is currently not supported.

**Comment by Turum** [comment]
It's would be great to have such feature or just possibility to hide the column. For example I can add unique id for each row and id for "TOTAL would be always greater than for the other rows, after that I can sort by this row and hide it. It would be workaround to. 
Thanks.
