### ISSUE TITLE
Upgraded and now getting: InfluxDB Error: Cannot read property 'message' of null

### ISSUE THREAD

**Issue by poblabs** [grafana/grafana#5224]
Been using InfluxDB & Grafana for a year +/- now. Recently upgraded to Grafana -3.0.4-1464167696.x86_64 on CentOS 6.8 and I noticed my graphs were all missing. 

I went into datasources and I have the error `InfluxDB Error: Cannot read property 'message' of null.`

My access method is direct and I can access the direct URL externally. So I don't think that's the problem. 

Any thoughts?

**Comment by poblabs** [comment]
I suppose the issue could be that I'm running InfluxDB 0.8, and Grafana is now using the 0.9 API (since I don't see InfluxDB 0.8 in the datasource dropdown)? CentOS yum doesn't have 0.9 yet, so I'll look to upgrade using an RPM and see if that fixes it.

**Comment by torkelo** [comment]
For InfluxDB 0.8 you need an external plugin, install from grafana.net

**Comment by poblabs** [comment]
Thanks. I ended up stepping InfluxDB from `0.8` to `0.8.9`, to `0.9.5` then to `0.10`. Had to do a lot of re-configuring but all is good now.
