### ISSUE TITLE
[Question] this.datapoints[a][1] is undefined

### ISSUE THREAD

**Issue by defkev** [grafana/grafana#5225]
I am currently in the progress of migrating an age old ELK cluster and intend to (maybe) use Grafana instead of Kibana for visualization, since i have to rebuild all the dashboards anyway...yeah

Problem is i am so far not able to get Grafana to query any metrics by terms using analyzed string fields from Elasticsearch.

With the default template in Elasticsearch (`"fielddata" : { "format" : "disabled" }`) i get a `Field data loading is forbidden on [SOMEFIELD]` and trying to query the raw field (using `somefield.raw`) or changing the template (`"fielddata" : { "format" : "enabled" }`) followed by a reindexing i get a `this.datapoints[a][1] is undefined` in Grafana.

- What Grafana version are you using?
3.0.4, commit: v3.0.4, build date: 2016-05-25 10:46:55

- What datasource are you using?
Elasticsearch 2.3.3 (proxied, with re-enabled fielddata on analyzed string fields)

- What OS are you running grafana on?
CentOS 7.2.1511 (Core)

- What did you do?
Add a metric grouped by a (analyzed) term string field

- What was the expected result?
Getting a fancy graph

- What happenend instead?
A red bang!

Furthermore Firefox dev console logs:
```
Error: this.datapoints[a][1] is undefined
.execute/f</a.prototype.isMsResolutionNeeded@http://grafana.lab.local:3000/public/app/boot.16792590.js:19:10298
.execute/i</h.prototype.seriesHandler@http://grafana.lab.local:3000/public/app/boot.16792590.js:17:11919
ca.Call@http://grafana.lab.local:3000/public/app/boot.16792590.js:4:4095
@http://grafana.lab.local:3000/public/app/boot.16792590.js:4:17999
.execute/i</h.prototype.onDataReceived@http://grafana.lab.local:3000/public/app/boot.16792590.js:17:11220
e.prototype.emit@http://grafana.lab.local:3000/public/app/boot.16792590.js:38:21559
.execute/d</a.prototype.emit@http://grafana.lab.local:3000/public/app/boot.16792590.js:38:23640
.execute/i</f.prototype.handleQueryResult@http://grafana.lab.local:3000/public/app/boot.16792590.js:40:15271
h@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:19121
i/<@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:19293
vc/this.$get</n.prototype.$eval@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:26806
vc/this.$get</n.prototype.$digest@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:25310
vc/this.$get</n.prototype.$apply@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:27091
f@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:1936
q@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:3786
Ib/</v.onload@http://grafana.lab.local:3000/public/app/boot.16792590.js:35:4329
1 boot.16792590.js:35:12056
e/<() boot.16792590.js:35
vb/this.$get</<() boot.16792590.js:34
h() boot.16792590.js:35
i/<() boot.16792590.js:35
vc/this.$get</n.prototype.$eval() boot.16792590.js:35
vc/this.$get</n.prototype.$digest() boot.16792590.js:35
vc/this.$get</n.prototype.$apply() boot.16792590.js:35
f() boot.16792590.js:35
q() boot.16792590.js:35
Ib/</v.onload() boot.16792590.js:35
```
and for the sake of it Edge dev console logs:
```
TypeError: Unable to get property 'toString' of undefined or null reference
   at a.prototype.isMsResolutionNeeded (http://grafana.lab.local:3000/public/app/boot.16792590.js:19:10294)
   at h.prototype.seriesHandler (http://grafana.lab.local:3000/public/app/boot.16792590.js:17:11785)
   at Array.prototype.map (native code)
   at h.prototype.onDataReceived (http://grafana.lab.local:3000/public/app/boot.16792590.js:17:11076)
   at e.prototype.emit (http://grafana.lab.local:3000/public/app/boot.16792590.js:38:21552)
   at a.prototype.emit (http://grafana.lab.local:3000/public/app/boot.16792590.js:38:23640)
   at f.prototype.handleQueryResult (http://grafana.lab.local:3000/public/app/boot.16792590.js:40:15121)
   at h (http://grafana.lab.local:3000/public/app/boot.16792590.js:35:19111)
   at Anonymous function (http://grafana.lab.local:3000/public/app/boot.16792590.js:35:19293)
   at n.prototype.$eval (http://grafana.lab.local:3000/public/app/boot.16792590.js:35:26799)
```

- An image or text representation of your metric query
Clicking on the rectangle with the bang shows neither Request, Response nor JS Error populated (everything is empty) which would kind-of explain the error message in the first place.
Looking into Firefox dev console i can see the request payload:

> {"search_type":"count","ignore_unavailable":true,"index":["logstash-2016.05.30","logstash-2016.05.31"]}
> {"size":0,"query":{"filtered":{"query":{"query_string":{"analyze_wildcard":true,"query":"type=iptables"}},"filter":{"bool":{"must":[{"range":{"@timestamp":{"gte":"1464615603643","lte":"1464702003643","format":"epoch_millis"}}}]}}}},"aggs":{"2":{"terms":{"field":"protocol","size":10,"order":{"_term":"asc"}},"aggs":{}}}}

As well as the JSON response containing the bucket with the expected data yet Grafana seems to completly miss to pick it up.

- The raw query and response from your data source (check this in chrome dev tools network tab)
See above.

**Comment by utkarshcmu** [comment]
isMsResolutionNeeded function in time_series2.ts file expects datapoints to be an array of [value,timestamp] objects. Thats the reason why we are seeing this issue.

**Comment by torkelo** [comment]
If you using the Graph or Singelstat panel you need a date histogram aggregation, always. This is only a current limitation and something we will change in future release. The Graph and Singlestat panel expects time series results. You can still have a terms aggregation.

http://play.grafana.org/dashboard/db/elasticsearch-templated?panelId=1&fullscreen&edit

 The table panel is the only panel that supports Elasticsearch Raw Documents, and aggregations without date histogram
