### ISSUE TITLE
Summarise multiple graphs from multiple data sources

### ISSUE THREAD

**Issue by avneradania** [grafana/grafana#5226]
Thank you for helping us make Grafana even better!

To help us respond to your issues more quickly, please make sure to add as much information as possible.

If this issue is about a plugin, please open the issue in that plugin's repository.

Start your issue's title with [Feature Request] / [Bug] / [Question] or no tag if you're unsure. Also, please be aware that GitHub now supports uploading of screenshots; look at the bottom of this input field.

Please include some basic information:
- What Grafana version are you using? 3
- What datasource are you using? Graphite
- What OS are you running grafana on? CentOs6.6
- What did you do? Tried to summarise multiple graphs from multiple data sources
- What was the expected result? To have a feature to sum it
- What happenend instead? No such option

If your question/bug relates to a metric query / unexpected data visualization, please include:
- An image or text representation of your metric query
- The raw query and response from your data source (check this in chrome dev tools network tab)

**Comment by bergquist** [comment]
Grafana does not support summarizing data from different datasources. 

But you can display them in the same graph using mixed datasources. You can find an example on this dashboard http://play.grafana.org/dashboard/db/elasticsearch-metrics?panelId=4&fullscreen&edit

**Comment by TryTryAgain** [comment]
Can this be reconsidered now that Transformations exist? It's really a huge piece I'm missing within grafana: to be able to calculations on multiple source and output as a virtual metric along side the existing metrics (I understand that's now how transformations work but what I'd love to see).
