### ISSUE TITLE
[BUG] Escape inside template variable in elastics query

### ISSUE THREAD

**Issue by BcTpe4HbIu** [grafana/grafana#5227]
- What Grafana version are you using?

  RPM package 3.0.4-1464167696
- What datasource are you using?

  Elasticsearch 2.3
- What OS are you running grafana on?

  CentOS 7
- What did you do?

  Configured tempate variable from elastics with query: `{ "find": "terms", "field": "client" }`

  Used that variable in other tempate variable from elastics: `{ "find": "terms", "field": "source", "query":"client:$Client" }`

  Got error: 

  > Template variables could not be initialized: Unexpected token in JSON at position 58

  Error caused by escaping inside json after interpolating $Client variable to value with space in it:
  `"{ "find": "terms", "field": "source", "query":"client:Some\ Name" }"` (notice the \ in client field, it's invalid in json)

Is there any way to avoid this error?

Thanks.

**Comment by anuraaga** [comment]
I have the issue with dashes as well being escaped.

Until the bug is fixed, I've found a workaround to be to set the regex field to extract the entire string
```
/(.*)/
```

which seems to cause the bad escaping to not happen.

**Comment by anuraaga** [comment]
@torkelo This and the other issue also mention having problems with hyphens, which I don't see fixed since you just add escaping for whitespace.

Isn't it more correct to replace '\' with '\\' so when JSON parsed, it's turned back into '\'?
