### ISSUE TITLE
[Bug] nested template variable in Elasticsearch terms query

### ISSUE THREAD

**Issue by NoumanSaleem** [grafana/grafana#5228]
- What Grafana version are you using: 3.0.4
- What datasource are you using: Elasticsearch
- What OS are you running grafana on: Ubuntu 14.04
- What did you do: Tried to use a template variable (type: custom) in another template variable (type: query)
- What happenend instead?

> Templating
> Template variables could not be initialized: Unexpected number in JSON at position 65

<img width="695" alt="screen shot 2016-05-31 at 6 39 17 am" src="https://cloud.githubusercontent.com/assets/694071/15676590/abf10404-26fb-11e6-8d47-db7bfad00623.png">

the variable `$application` is set to static value: `web`

**Comment by torkelo** [comment]
Cannot replicate this issue:
Same scenario works here:
http://play.grafana.org/dashboard/db/elasticsearch-templated

You Custom all value does not look right though. Does not look like valid Lucene syntax (think a single wildcard should work) 

<img width="728" alt="screen shot 2016-06-01 at 08 13 50" src="https://cloud.githubusercontent.com/assets/10999/15699891/d4109492-27d0-11e6-962d-10ed5fde8670.png">

**Comment by NoumanSaleem** [comment]
@torkelo thanks for looking into it. I believe it is because $application is set to a string with a hyphen. My above example `$application: web` is actually `$application: mobile-web` in the case where it fails, I can observe this behavior by changing the static value of `$application` 

as soon as I click `update` when setting `application` to a hyphenated value, it displays the error.

<img width="513" alt="screen shot 2016-06-01 at 6 25 34 am" src="https://cloud.githubusercontent.com/assets/694071/15711140/b0779ce2-27c1-11e6-83fc-0e6f7122eb17.png">
<img width="515" alt="screen shot 2016-06-01 at 6 25 17 am" src="https://cloud.githubusercontent.com/assets/694071/15711141/b08af242-27c1-11e6-952d-d80743cf009a.png">

**Comment by BcTpe4HbIu** [comment]
@NoumanSaleem Please, see #5227

**Comment by NoumanSaleem** [comment]
@BcTpe4HbIu thanks, subscribed to issue
