### ISSUE TITLE
[Display issue] Big scrolbar on the legend table with Debian Iceweasel Browser

### ISSUE THREAD

**Issue by pather87** [grafana/grafana#5229]
Hi,

this issue might refer to #4760 

A Scrollbar is showing up on the right end of the Graph Panel when using 'As Table' Option in Graph Legend. Scrollbar also partially covers legend when using 'To the right' option.

- What Grafana version are you using? 3.0.4
- What datasource are you using? Graphite
- What OS are you running grafana on? Debian Jessie
- Browser? Iceweasel 38.8.0

Issue seems to only affect the Debian specific ( older ) Iceweasel version of Firefox. Issue does not exist on Ubuntu 14.04 tested with Firefox 46.

![grafana_3_0_4_firefox_scrolbar](https://cloud.githubusercontent.com/assets/2121716/15676662/6b0463e0-2747-11e6-85b1-a60a7a287a7b.png)
![grafana_3_0_4_firefox_scrolbar2](https://cloud.githubusercontent.com/assets/2121716/15676717/b1898ba6-2747-11e6-87a2-aa7b691d3ebd.png)

**Comment by torkelo** [comment]
#4760 was related to an issue with height calculation that caused scrollbar to appear when it should not. 

since it seems to be fixed in later versions of firefox I will close this
