### ISSUE TITLE
Loki Query Builder - Size of the box for a pattern stage goes over the width of the window/screen

### ISSUE THREAD

**Issue by camsellem** [grafana/grafana#52301]
**What happened**:

Size of the box for a pattern stage goes over the width of the window/screen

**What you expected to happen**:

Automatically word wrap the text / multiline 

**How to reproduce it (as minimally and precisely as possible)**:

Create a stage pattern with a long pattern /  see screenshot

**Anything else we need to know?**:

![image](https://user-images.githubusercontent.com/3879044/179121066-31660e28-6fe4-4bff-ae7a-32891fe8f8f4.png)

**Environment**:
- Grafana version: 9.0.1
- Data source type & version: Loki
- OS Grafana is installed on:
- User OS & Browser: Chrome/Brave
- Grafana plugins: 
- Others:

**Comment by usmangt** [comment]
Hi @camsellem ,

I see what you mean as I was (maybe not exact as in your screenshot but partially) able to reproduce it and I cannot use any of my keys to scroll left or right and have to zoom out to view the page page.

**Comment by svennergr** [comment]
Hi @usmangt and @camsellem,

I am having problems reproducing this on MacOS.
This link https://play.grafana.org/goto/Yfqdf0g4k?orgId=1 will show an horizontal scroll-bar. Also testing on Grafana 9.0.1 did show that scrollbar for me.

Could you maybe share more information about your OS/Browser versions?

Thanks.

**Comment by ivanahuckova** [comment]
@svennergr Btw, here is slightly more context on this issue: https://raintank-corp.slack.com/archives/C03045EE1EC/p1645175541121639. Probably the parent component should pass the `maxWidth` prop to prevent this.

**Comment by usmangt** [comment]
@svennergr 

I cannot reproduce from the above link and also this time my screen did not freeze and can move around with keyboard scroll up and down.

I am using Grafana-OSS ver. 9.0.3
Chorme Version 103.0.5060.114 (Official Build) (64-bit)
CentOS 8 Stream
