### ISSUE TITLE
[Bug] Graphite - offsetToZero doesn't work for any series

### ISSUE THREAD

**Issue by klaffke** [grafana/grafana#5230]
Applying "offsetToZero" to any Graphite data series results in the following error:

{
  "error": "Internal Server Error",
  "message": "Internal Server Error"
}

Grafana version: 3.0.4
Datasource: Graphite
OS: CentOS

Query:

offsetToZero(test.diskFree.C)

Response:

{
  "error": "Internal Server Error",
  "message": "Internal Server Error"
}
	
test.diskFree.C works as intended. This behaviour is the same for any other Graphite datasource I am using

**Comment by torkelo** [comment]
i cannot replicate this, works here. 

What version of Graphite do you have? It is only available if you run graphite-web master, or graphite-api

**Comment by klaffke** [comment]
I'm using the newest version of Graphite, 0.9.15 and am accessing it via graphite-web. It still doesn't work using Grafana v3.1.0 (commit: v3.1.0):

Response:

{
"error": "Internal Server Error",
"message": "Internal Server Error"
}

**Comment by torkelo** [comment]
offsetToZero is in graphite master only I think

**Comment by klaffke** [comment]
You're right! The function is also not available on the graphite-web dashboard. I don't think that there's any way to catch this error on your side?

Thanks!
