### ISSUE TITLE
Alerting: Grafana managed alert - Add query - shows no compatible data sources, if no default datasource is set

### ISSUE THREAD

**Issue by hastarin** [grafana/grafana#52304]
**What happened**:
I tried to edit an existing alert rule to add a query but the button is greyed out with an error "You appear to have no compatible data sources"
![image](https://user-images.githubusercontent.com/452393/179133486-613b6aba-7be0-4553-ad91-55c3463e4fc5.png)
After some diagnosis I discovered this was because I no longer had a datasource defined as a default.

**What you expected to happen**:
I expected to still be able to edit/create alerts, or be prevented from having no default data source.

**How to reproduce it (as minimally and precisely as possible)**:

- Find your default data source
- Turn off the default toggle
- Save changes
- Attempt to add/edit a Grafana managed alert

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.3
- Data source type & version: N/A
- OS Grafana is installed on: Docker
- User OS & Browser: Windows 10, Edge
- Grafana plugins: 
- Others:

**Comment by ashharrison90** [comment]
hi @hastarin 👋 

can't quite reproduce this locally. think there must be some extra steps we're missing.
do you have any other datasources configured?

thanks! 🙌

**Comment by hastarin** [comment]
Yes I've got plenty of other data sources, a couple of Zabbix, a few
elastic search, and several CloudWatch.

**Comment by yosiasz** [comment]
Had the same problem. Found the issue with mine was my default data source was infinity plugin. Seems like if the data source is not some sort of db wherein grafana can prepopulate the query seed below you get this error

![image](https://user-images.githubusercontent.com/900951/181775782-e0541009-cb87-4737-8359-a36467b3d025.png)

**Comment by alecxvs** [comment]
Nice catch... I can reproduce on 9.1.5, this was confusing because I could create an alert based on a panel but I could not add queries to it... It really is as simple as not having a default datasource set.
