### ISSUE TITLE
Vulnerabilities in gopkg (Grafana 8.5.9)

### ISSUE THREAD

**Issue by fatbasstard** [grafana/grafana#52315]
**What happened**:

Updated Grafana (Docker image) to 8.5.9 and there were security findings in there, related to  the`gopkg` package

Findings coming from AWS ECR image scanning.

![image](https://user-images.githubusercontent.com/35613489/179197294-e06a4233-22e2-47a1-bd91-f527d73b5d67.png)

**What you expected to happen**:

No (new) security findings.

**How to reproduce it (as minimally and precisely as possible)**:

Upload Docker image to ECR with repository scanning enabled

**Anything else we need to know?**:

The Go package is recently updated: https://github.com/grafana/grafana/pull/51042

**Environment**:
- Grafana version: 8.5.9
- OS Grafana is installed on: Official Docker image (`FROM grafana/grafana:8.5.9`)

**Comment by simonc6372** [comment]
Hi @fatbasstard 
The latest version of Grafana 8.5  is 8.5.20, which is built against Golang 1.19.4. Can you run your tests agaisnt that. 

Also, the finding against Loki is a false positive. That vulnerability was for the Loki Server, and not the loki client code that Grafana uses. The vulnerable code the scaner is detecting is in the server code (as of that version) and not the client code. 

If you are still haveing similar findings agsint 8.5.20, please feel free to reopen this issue.
