### ISSUE TITLE
New lines are remove from Alerting templates when used with e-mail contact point.

### ISSUE THREAD

**Issue by basvdl** [grafana/grafana#52310]
**What happened**:
If you use the default [example template](https://grafana.com/docs/grafana/latest/alerting/contact-points/message-templating/example-template/) for an e-mail contact point, it removes all the new lines, making the templating feature for e-mail not very friendly. I tried adding extra new lines (`\n`) but no luck. Do we have a secret trick?

**What you expected to happen**:
That new lines are kept when using the template for e-mail.

**How to reproduce it (as minimally and precisely as possible)**:
- Create the [example templates](https://grafana.com/docs/grafana/latest/alerting/contact-points/message-templating/example-template/)
- Create an e-mail contact point and set the message to `{{ template "mymessage" . }}`

**Environment**:
- Grafana Cloud / GE: 9.0.*

**Comment by alexweav** [comment]
PR to fix this is attached.

There is a workaround that OSS users can use: see the change made on line 289 of `public/ng_alert_notification.html` in that PR. This file is installed under the normal grafana installation directory. Making this change and then restarting the server will fix the problem for current deployments.

https://github.com/grafana/grafana/blob/aa18a74cb192bd173182f0365509a9e55d6e9aae/public/emails/ng_alert_notification.html#L288-L290
