### ISSUE TITLE
Cannot Update permission when  enable proxy auth.

### ISSUE THREAD

**Issue by Ggleny** [grafana/grafana#5231]
Grafana Version : 2.6
When I enable the parameter in grafana.ini [auth.proxy] enabled = true
and I update a user's permission via http
{ method: 'PUT',
  url: 'http://admin:admin@HOST:3000/api/admin/users/3/permissions',
  headers: 
   { 'content-type': 'application/json;charset=UTF-8',
     connection: 'close',
     'X-WEBAUTH-USER': 'admin' },
  qsStringifyOptions: { arrayFormat: 'repeat' } ,
  form: { isGrafanaAdmin: true }
 }

I get response
{"message":"User permissions updated"}
but the user's permission is not updated.
{"id":3,"name":"test","login":"test@test.com","email":"test@test.com","isAdmin":false},

**Comment by torkelo** [comment]
I cannot replicate this, it's updated everytime I do the exact same api call. It's the same api call used from the UI as well.

**Comment by zbindenren** [comment]
I have a similar issue. I have the following configuration in ldap.toml:

```
[[servers.group_mappings]]
group_dn = "*"
org_role = "Viewer"
```

So by default, every user has only Viewer role.

Then, when I change a users Role to Admin by editing the user with the gui, that user is Admin as long as he is logged in. As soon the user logs out and logs in again, the Admin role is gone and the user has Viewer.

Is that supposed to work like that?

**Comment by torkelo** [comment]
@zbindenren yes, LDAP currently only works with ldap -> grafana org role mappings, meaning it will sync  the roles defined in ldap.toml with the current ones. So if you only defined Viewer role then the Admin role will be removed

**Comment by zbindenren** [comment]
@torkelo tanks for the quick response.

A configuration option like:

```
[[servers.user_mappings]]
user_dn = "...."
org_role = "Admin"
org_id = 1
```

would be great.

**Comment by torkelo** [comment]
you don't have a group_dn for Admins to use?

**Comment by zbindenren** [comment]
Yes we have, but I was thinking maybe other people not. Thanks anyway.
