### ISSUE TITLE
Bar chart tool tip doesn't show values properly.

### ISSUE THREAD

**Issue by MKrabs** [grafana/grafana#52329]
**What happened**: Tooltip doesn't properly show (single | all) values.

**What you expected to happen**: Tooltip to show either single or all values on hover.

**How to reproduce it (as minimally and precisely as possible)**: Use a bar chart with Stacking Normal and different tooltip modes.

**Anything else we need to know?**: A similar table on Time series shows the tooltip properly, which is how it is expected.

**Environment**:

- Grafana version: v8.3.3 (30bb7a93ca)
- Data source type & version: Postgresql 
- OS Grafana is installed on: Ubuntu 20.04.4 LTS
- User OS & Browser: Ubuntu 20.04.4 LTS
- Grafana plugins: Bar Chart
- Others: see attached screenshots

![not_stacked_tooltip_single](https://user-images.githubusercontent.com/71791731/179226359-4ed24d34-3e9a-40a6-b33b-7b0e95180c71.png)
![not_stacked_tooltip_all](https://user-images.githubusercontent.com/71791731/179226367-3992276e-f6e2-4199-a108-13519bc915e6.png)
![stacked_tooltip_single](https://user-images.githubusercontent.com/71791731/179226369-0d0add54-f3dc-42f6-bc10-b75ebf50185c.png)
![stacked_tooltip_all](https://user-images.githubusercontent.com/71791731/179226371-5c01ac95-d922-4bae-82c6-9ca6a2814d01.png)

**Comment by usmangt** [comment]
I think I was able to reproduce this case.

Steps to reproduce;

1- Create any panel where you are plotting multiple values e.g. cpu stats from server 1, 2, 3
2- select visualization e.g. time series
3- goto the tool tip and then;
 a. select single (work as expected)
 b. then select all ((work as expected))
 c. And then select hidden (work as expected)
4- However if you now switch back to single or all then tooltip does not come up

It is like Hidden function hide it permanently.

Tested on Grafana-OSS ver. 9.0.3
Browser Chrome Version 103.0.5060.114 (Official Build) (64-bit)
O.S CentOS 8 Stream

**Comment by mdvictor** [comment]
Hey @MKrabs ! Thank you for opening this issue.

As far as I understand, the tooltip mode defaults to 'all' when the bars are stacked as in your example. The problem, IMO, is that a user can still select different tooltip modes from the options, even though the configuration is not set and thus causes confusion. 

We will take a look over this and see what's the best approach to clear such confusion.

**Comment by mdvictor** [comment]
Hey @usmangt. It seems that what you reproduced is a different bug. That's a great catch! I opened this issue for it here: https://github.com/grafana/grafana/issues/52875

**Comment by mdvictor** [comment]
Hello @MKrabs ,

Can you help me with some more clarifications? Do you expect to see the value of the stacked bar you are hovering on when the option stacking is set to normal and tooltip mode to single?

E.g: In this [image](https://user-images.githubusercontent.com/71791731/179226369-0d0add54-f3dc-42f6-bc10-b75ebf50185c.png) do you expect to only see the value for `two`?

**Comment by mdvictor** [comment]
Closing this to clean the board a bit. Please reopen if needed.

**Comment by grzesuav** [comment]
Hi,

have similar issue on `9.3.7` with both tooltip mode `All` and `Single` - the hover tooltip shows wrong information.

**Comment by grzesuav** [comment]
I was able to reproduce it on https://play.grafana.org/d/000000029/prometheus-demo-dashboard?orgId=1&refresh=5m&viewPanel=3

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/9568421/221546585-18e566e4-3ddf-461d-9d7a-389dda87717c.png">
[panel.txt](https://github.com/grafana/grafana/files/10838931/panel.txt)

**Comment by mdvictor** [comment]
Hi @grzesuav, can you please tell me the exact steps you took to reach this point in Play? I changed the `Memory usage` panel to have normal stacking and single tooltip but it looks different than your image. Thank you!

**Comment by grzesuav** [comment]
basically I added legend with `mean` and sorted from smallest to greatest values (as this reorders the bars in more readable way)

**Comment by mdvictor** [comment]
Hey @grzesuav,
My bad, I missed the `panel.txt`. I also managed to reproduce. Seems that the tooltip sort values are being applied even when the tooltip mode is set to `Single`. We will investigate this further.

Thank you!

**Comment by mdvictor** [comment]
Hey @grzesuav! Fix was merged and should be available by next patch!

**Comment by grzesuav** [comment]
Great, Thank you @mdvictor
