### ISSUE TITLE
$__rate_interval is not equal to 4 * Min Step when it should

### ISSUE THREAD

**Issue by AntoineThebaud** [grafana/grafana#52340]
**What happened**:
I have a Prometheus datasource defined with scrape interval = 30s. However I have one use case where the metrics are scraped every 4min and I want to use rate() with $__rate_interval, thus as explained [here](https://grafana.com/blog/2020/09/28/new-in-grafana-7.2-__rate_interval-for-prometheus-rate-queries-that-just-work/) I went for: _"But what to do if you have the odd metric that has been scraped with a different scrape interval? In that case, use the Min step field to enter the special scrape interval, and everything will just work again."_

But it looks like the query's min step is ignored and that it's still the default 30s scrape interval set at datasource level that is taken into account. See below screenshot: 
![image](https://user-images.githubusercontent.com/7058693/179247335-bb136e21-62f7-45af-931e-6d1c8059ea5e.png)

**What you expected to happen**:
I expected the documented behavior: 

> `$__rate_interval` is defined as max($__interval + Scrape interval, 4 * Scrape interval), **where Scrape interval is the Min step setting** (AKA queryinterval, a setting per PromQL query) **if any is set**. Otherwise, the Scrape interval setting in the Prometheus data source is used.

 Thus I was expecting to see max(4m + 4m, 4 * 4m) = **16m** here, instead it looks like Scrape interval ignores my Min Step and falls back to the default one from the datasource (30s) hence why the result is max(4m + 30s, 4 * 30s) = 4m30s.

**How to reproduce it (as minimally and precisely as possible)**:
Use a rate() query in a panel with $__rate_interval as time range parameter, set a min step larger than the Scrape interval defined in the Prometheus datasource, choose a short enough timerange so that $__interval is equal to the min step defined, then check the value computed for $__rate_interval with the query inspector.

**Environment**:
- Grafana version: v8.5.4 (78ee958143)
- Data source type & version: Prometheus - Thanos 0.26.0
- OS Grafana is installed on: Grafana official docker image running in Kubernetes
- User OS & Browser: Windows 10 & Firefox

**Comment by echatman-ias** [comment]
I think I am experiencing this same issue, but I can't find anything that tells me what exactly $__rate_interval is being set to. My query inspector does not have the top section shown in the screenshot; only the json that still has $__rate_interval in it. However, from the results I'm getting back, it's pretty clearly setting it too low.

My prometheus data source has a default scrape interval of 15s but these particular metrics are scraped at 1m interval. I tried setting both the "Min interval" under "Query options" and the "Min step" on the query itself but both are ignored.

Grafana v8.3.6 (bf8766bbf2)

**Comment by gtk-grafana** [comment]
@bohandley is this resolved by that PR you merged in last week?

**Comment by bohandley** [comment]
@gtk-grafana No, this one is not resolved by my the PR for using the `$__rate_interval` macro variable in the min step option. This one is about calculating the `$__rate_interval` which requires a significant amount more investigation.
