### ISSUE TITLE
Canvas: Enable ability to instantly select and drag an element

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#52355]
It would be great if we could select and be able to drag an element right away on initial mousedown event. This functionality is currently commented out due to an issue where the `dragStart` event would be applied even after the user stopped clicking down on the element, causing the element to continue to follow the user's cursor

See #52343 for more context

Possible fixes may be refactoring our moveable / selecto instances to use React instead (maybe? given the demo seems to work)

Figuring out a way to prevent dragStart event from firing if the mouse is currently not actively being pressed down

**Comment by drew08t** [comment]
Bug where clicking on an element that belongs in a frame "jumps" down is caused by the frames border width. Likely due to the setPlacementFromConstraint function that gets bounding box from the parent.
