### ISSUE TITLE
Unable to install plugins on Ubuntu

### ISSUE THREAD

**Issue by deepujain** [grafana/grafana#5235]
root@epci-7704:~/grafana-3.0.4-1464167696# wget https://grafana.net/api/plugins/repo
--2016-05-31 13:56:37--  https://grafana.net/api/plugins/repo
Resolving grafana.net (grafana.net)... 107.178.222.220
Connecting to grafana.net (grafana.net)|107.178.222.220|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 18195 (18K) [application/json]
Saving to: ‘repo’

100%[================================================================================================>] 18,195      --.-K/s   in 0s      

2016-05-31 13:56:47 (158 MB/s) - ‘repo’ saved [18195/18195]

root@epci-7704:~/grafana-3.0.4-1464167696# ./bin/grafana-cli  plugins list-remote

Error: Get https://grafana.net/api/plugins/repo: dial tcp: i/o timeout

NAME:
   Grafana cli plugins list-remote - list remote available plugins

USAGE:
   Grafana cli plugins list-remote [arguments...]
root@epci-7704:~/grafana-3.0.4-1464167696# 

I am able to access internet from this machine but install plugin does not seem to work. 
Please suggest a workaround.

**Comment by deepujain** [comment]
On MAC, when i download linux binary  I cannot even run grafana-cli 

:grafana-3.0.4-1464167696 dvasthimal$ ./bin/grafana-cli 
-sh: ./bin/grafana-cli: cannot execute binary file
:grafana-3.0.4-1464167696 dvasthimal$

**Comment by torkelo** [comment]
@deepujain last time I checked MAC does not run linux binaries :) 

It's strange, is the machine accessing the internet via an http proxy? is the http_proxy env variable set?

**Comment by deepujain** [comment]
Its a linux binary and not a generic linux shell script. Will check on proxy.
