### ISSUE TITLE
Loki datasource 414 Request-URI Too Large

### ISSUE THREAD

**Issue by gmavadiy** [grafana/grafana#52369]
**What happened**:
For large number of query parameters Loki datasource returns with 414 Request-URI Too Large

**What you expected to happen**:
Loki datasource should have configuration option to handle large uri's

**How to reproduce it (as minimally and precisely as possible)**:
- Create Loki datasource
- Have a grafana variable that can return large values with All option. Trigger the query. Panel responds with 
`<html><head><title>414 Request-URI Too Large</title></head><body><center><h1>414 Request-URI Too Large</h1></center><hr><center>nginx</center></body></html>`

**Anything else we need to know?**:

**Environment**:
- Grafana version: v9.0.3
- Data source type & version: Loki
- OS Grafana is installed on: Cloud
- User OS & Browser: OSX Firefox 102.0

**Comment by gabor** [comment]
hi @gmavadiy , for the specific case of using the `All` option in a variable, you can configure a custom "all value", so you could perhaps use a regular-expression like `.+` or something similar.

but in general, there is only one way the Loki database accepts requests, and it's by using a HTTP GET request, where the parameters are added to the query-string ( https://grafana.com/docs/loki/latest/api/#query-loki-over-a-range-of-time ). and this approach has the URL limitation. there's nothing that can be done from Grafana's side.

you may want to raise this issue in the Loki github repository at https://github.com/grafana/loki
