### ISSUE TITLE
Czech Republic 

### ISSUE THREAD

**Issue by Danielferencz21** [grafana/grafana#52366]
**Why is this component needed**:

___
 - [x] Is/could it be used in more than one place in Grafana?

**Where is/could it be used?**:

___
- [x] Post screenshots possible.
- [x] It has a single use case.
- [x] It is/could be used in multiple places.

**Implementation** (Checklist meant for the person implementing the component)

- [x] Component has a story in Storybook.
- [x] Props and naming follows [our style guide](https://github.com/grafana/grafana/blob/main/contribute/style-guides/frontend.md).
- [x] It is extendable (rest props are spread, styles with className work, and so on).
- [x] Uses [theme for spacing, colors, and so on](https://github.com/grafana/grafana/blob/main/contribute/style-guides/themes.md).
- [x] Works with both light and dark theme.

**Documentation**

- [x] Properties are documented.
- [x] Use cases are described.
- [x] Code examples for the different use cases.
- [x] Dos and don'ts.
- [x] Styling guidelines, specific color usage (if applicable).

**Comment by Danielferencz21** [comment]
Leave

**Comment by torkelo** [comment]
@Danielferencz21 ?
