### ISSUE TITLE
[Bug] 3.0.1 Incorrect y-axis scale when viewing more than 1 hour period

### ISSUE THREAD

**Issue by moloney** [grafana/grafana#5236]
I am using grafana 3.0.1 with an InfluxDB data source. I setup some very basic metric graphs and things look good until I change the time period to be over 1 hour, at which point the scale on the y-axis becomes incorrect.

Here is a graph with a 1-hour time span where the scale is correct:

![grafana-1-hour](https://cloud.githubusercontent.com/assets/1376566/15694258/03bef704-2751-11e6-95e5-72175e33ed3e.png)

And here is the same graph with a 3-hour time span where the scale is incorrect:

![grafana-3-hour](https://cloud.githubusercontent.com/assets/1376566/15694273/21e11410-2751-11e6-8b52-f01d2bdb8ed2.png)

Going higher than 3-hours makes the scale bar become even more incorrect.  Time spans under 1 hour look correct.

**Comment by torkelo** [comment]
Grafana will adapt the year axis based on the data returned by your InfluxDB query.  So maybe that data is incorrect? 

Saying that something is incorrect does not help in any way.  What's the data give  to Grafana??  Why are the Graph  options etc.  Will close this as it is is likely just cause by the InfluxDB data response not being what you expect

**Comment by torkelo** [comment]
Oh, that should read the y-axis, dam mobile autocomplete :)

**Comment by moloney** [comment]
Doing the query against InfluxDB manually seems to produce the correct data.

Here is one of the queries in grafana:

SELECT sum("value") FROM "memory_value" WHERE "host" = 'myserver.example.com' AND "type_instance" =~ /(free|cached|buffered)/ AND $timeFilter GROUP BY time($interval) fill(null)

So I manually ran this query against influxdb to get data from the last three hours:

SELECT sum("value") FROM "memory_value" WHERE "host" = 'myserver.example.com' AND "type_instance" =~ /(free|cached|buffered)/ AND time > now() - 3h GROUP BY time(10s)  fill(null)

The results from this query look correct (~3.7 GB of available memory) and match the results shown in grafana when time range is an hour or less. As you can see in the screenshots above, grafana reports about double the amount of memory when the time range is 3 hours.

**Comment by torkelo** [comment]
Since you aggregate using sum function it should not come as a surprise that the value is higher when looking at longer time range. 

Grafana does not do any metric value transforms, it is showing the values returned by InfluxDB.  Did you check chrome dev tools network tab, there you can see raw InfluxDB response data

**Comment by moloney** [comment]
I am summing three time series corresponding to "free", "cached", and "buffered" memory to get a single time series of "available memory". Any query that is less than an hour (5 minutes, 15 minutes, etc. ...) returns a consistent result that matches the data that comes from doing a manual query against InfluxDB. Only in grafana, and only when the query is longer than an hour, is the result inconsistent.

If you think my manual query was wrong somehow please let me know.

**Comment by torkelo** [comment]
You are more than summing up time series. You need to read some InfluxDB query docs :) 

`SELECT sum("value") FROM "memory_value" WHERE "host" = 'myserver.example.com' AND "type_instance" =~ /(free|cached|buffered)/ AND $timeFilter GROUP BY time($interval) fill(null)`

You have a group by time, that is the data points will be aggregated into time buckets based on the $interval variable. The $interval variable is a Grafana variable that will be replaced before to something like 10s or 1m before sending the query to InfluxDB. 

The group by time is very important as without it InfluxDB will send raw unaggregated data, which for long time ranges (> 1day) will return many thousands of data points that will hang your browser. 

Grafana sets the $interval variable automatically based on the time range so InfluxDB never returns more data points then there are pixels in the Graph. You can remove the group by time but then the query and Grafana will likely be very slow or hang if you look at longer time ranges. 

What you are trying to do, sum 3 series, and then apply an average time aggregation is not possible (that I know of) in InfluxDB. InfluxDB is not very good for doing cross series transformations and operations. Graphite is way better if you need to apply nested queries and series transformations. 

I think you would I found this out if you just looked at chrome dev tools and the network tab, there you could have seen the query Grafana sends to InfluxDB and InfluxDB's response :) 

Anyway hope you find a way to solve your scenario. InfluxDB mailing list might help.

**Comment by moloney** [comment]
Thanks for the explanation, I finally understand.  The manual queries show the same incorrect results if I increase the time interval.  For the smaller time spans it was basically working by accident, as the time interval was small enough to only grab one point from each measurement.
