### ISSUE TITLE
Invalid endpoint URL called when trying to remove snapshot

### ISSUE THREAD

**Issue by aso824** [grafana/grafana#52371]
**What happened**:

After creating snapshot with local link, popup has button "Delete snapshot", but it uses endpoint with base URL (default `localhost:3000` in my case) instead of using base URL from browser - I suppose everything else works in this way, because I'm accessing Grafana server by IP address without domain changed in config and everything works, except this feature.

**What you expected to happen**:

Snapshot removed.

**How to reproduce it (as minimally and precisely as possible)**:

1. Access Grafana by URL other than configured domain, like IP address
2. Create local snapshot
3. Press "Delete snapshot" button in modal shown after creation

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.3
- Data source type & version: -
- OS Grafana is installed on: Debian 11
- User OS & Browser: Chrome 103
- Grafana plugins: -
- Others: -

**Comment by juanicabanas** [comment]
After a team discussion, this won't be supported because it's a CORS issue.
The backend is bound to the config app URL and it's not possible to make an API call from a different domain (which includes the IP)
