### ISSUE TITLE
Folder name update redirects to 404 when Grafana is served from subpath

### ISSUE THREAD

**Issue by konrad147** [grafana/grafana#52378]
**What happened**:
When Grafana is being hosted under a subpath, then editing a folder's name redirects to an invalid url. 
The subpath gets duplicated

![Screen Recording 2022-07-18 at 09 25 49](https://user-images.githubusercontent.com/6293563/179463072-ce016a76-e284-4a99-a019-eb8b294cc924.gif)

**What you expected to happen**:
The user stays on the same folder's settings page

**How to reproduce it (as minimally and precisely as possible)**:
Serve Grafana from subpath. Sample config
```
[server]
root_url = http://localhost/grafana
serve_from_sub_path = true
```

**Anything else we need to know?**:

**Environment**:
- Grafana version: main
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by papagian** [comment]
fixed by #60721
