### ISSUE TITLE
Loki: step/resolution/interval/min_interval is confusing

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#52387]
there are too many options to control the step&interval in Loki, and some of them overlap, and the resulting mix is confusing.
we should find a better way to specify these values. a solution that works well in both dashboards & explore.

**Comment by adeverteuil** [comment]
The same confusion applies to Prometheus queries, and any other time-series data source for that matter. I think a blog post would be a good start.

This blog post from Robust Perception is a good explanation, and also applies to metric queries for Loki:
https://www.robustperception.io/step-and-query_range/

There is also the added complexity of how Grafana alters the time range start and end timestamps to align then on a multiple of a step starting at timestamp 0 (for Prometheus at least, I haven't checked if it does for other data sources). Here's an internal discussion with @bboreham on our private Slack with a bit more details.
https://raintank-corp.slack.com/archives/C01TQGE89GT/p1647263497533869

**Comment by gabor** [comment]
as mentioned in a previous github issue, one problem with "resolution-scaling" step, but not "resolution-scaling" `$__interval` is that things like `count_over_time({...}[$__interval])` will not cover the whole range.

**Comment by evandandrea** [comment]
@ivanahuckova remind me why we're keeping this issue open [given](https://raintank-corp.slack.com/archives/C02TXB92G6T/p1667404585919679?thread_ts=1666192269.896219&cid=C02TXB92G6T):

> Sooo, we think the option should be in Explore, but we won’t have the capacity to do this next quarter (at least). we are willing to support anyone wanting to implement this though.

And https://github.com/grafana/grafana/issues/58337 ?

**Comment by ivanahuckova** [comment]
I am closing this as the goal of this specific issue was to do research on what would be the best way to make step/interval/resolution less confusing (ideally not confusing at all). 

The findings are here: https://docs.google.com/document/d/1giA6oxb_gyAJYvI2b0qL1XACgVrsS1HsiN0ZzCDze7o/edit#heading=h.41dvitd003pb and the result of this is this issue: https://github.com/grafana/grafana/issues/58337.
