### ISSUE TITLE
Grafana keeps timeout 60s for loki datasource

### ISSUE THREAD

**Issue by khoatdvo** [grafana/grafana#52392]
**What happened**:
We have a use case where we query heavy logs (100GB/day compressed size) for a couple of days
For `logcli` it takes around 1m30s, but we have never successfully queried through grafana dashboard which always timeout at 60s as shown in the grafana log:
`logger=context traceID=00000000000000000000000000000000 userId=15 orgId=1 uname=xxxx t=2022-07-07T08:33:44.41+0000 lvl=info msg="Request Completed" method=GET path=/api/datasources/proxy/7/loki/api/v1/query_range status=499 remote_addr=10.16.25.235 time_ms=59752 duration=59.752702291s size=0 referer="https://xxxxxx" traceID=00000000000000000000000000000000`
We always get `499` error for query which runs over 60s
We have set `datasource` http timeout and `dataproxy` timeout to 300s but they seem to have no effect

**What you expected to happen**:
Timeout should be set successfully for loki datasource

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version: 8.5.6
- Data source type & version: Loki 2.5
- OS Grafana is installed on: https://hub.docker.com/layers/grafana/grafana/grafana/8.5.6/images/sha256-b6a29226351aaf49ff870beb31cfdced9b09d28c086f1b6f83bcacd60d458c66?context=explore
- User OS & Browser: Windows & Chrome
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
hi @khoatdvo , unfortunately i cannot reproduce this.

i took Grafana 8.5.6, set the dataproxy-timeout to `120`, and made sure Loki is responding very slowly. even if the response arrived after 1minute-and-40seconds, it was correctly displayed in grafana.

but, i found something interesting.

if i did the same test, but, during the slow loki response i canceled the request from the browser (i did the test in `explore`, and i simply clicked the run-query button again), in the grafana-logs this produced the `499` response-code that you mentioned. `499` means `client closed request`, so my guess is that something between your browser and the grafana-server is canceling that http-request. maybe the hosting-provider's proxy or something like that. could you check that direction?

**Comment by khoatdvo** [comment]
hi @gabor many thanks for your investigation, I seem to find out the issue, there are some lb/nginx between my browser and grafana server which caused the timeout. I increase their timeout and it seems working now
 I'll close the ticket here
