### ISSUE TITLE
Can't assign new users to organizations

### ISSUE THREAD

**Issue by isj4** [grafana/grafana#5241]
Seen with Grafana versions 3.0.1 and 3.0.4

I'm creating a new user and then want to move him to the intended organization.

Procedure:
step 1: Admin -> Global Users -> Create new user:
User is created and has the "Main Org" as the only organization

step 2: Admin -> Global Users -> Edit user -> Add organization:
Fails with the orange error message "Problem! User not found"

Log only reveals this line:
2016/06/01 11:29:08 [I] Completed 93.167.50.108 isj@sgb "POST /api/orgs/2/users/ HTTP/1.0" 404 Not Found 28 bytes in 935us

I tried adding an organization to an old existing user. That works fine.

DB (sqlite) entries for the new user looks fine to me:
user:
15|0|george@redacted|george@redacted|George Redacted|53eedbd972b9fcb21b4dc998ae4597e52826be4cc65256546c32ce8afc45b5487aac707700305eb0148388ca75368d68abf7|qKeuOMYKSX|6FxjjsLE56||1|0|0||2016-06-01 11:12:40|2016-06-01 11:12:40

org_user:
37|1|15|Viewer|2016-06-01 11:12:40|2016-06-01 11:12:40

**Comment by torkelo** [comment]
I fail to replicate this:
![image](https://cloud.githubusercontent.com/assets/10999/15741753/687c4988-28bb-11e6-93ba-3bbfc7ebc331.png)

Did you perhaps change the user's email or username in a separate tab?

**Comment by isj4** [comment]
> Did you perhaps change the user's email or username in a separate tab?

No, and I can repeatedly reproduce it for this user.
![snapshot2](https://cloud.githubusercontent.com/assets/12530623/15753683/adf377b4-28f4-11e6-853e-984ce402b714.png)
![snapshot3](https://cloud.githubusercontent.com/assets/12530623/15753684/adf3e258-28f4-11e6-9c63-22795ac01ccf.png)
![snapshot4](https://cloud.githubusercontent.com/assets/12530623/15753682/adf3262e-28f4-11e6-896c-4bc0d6667a0d.png)

**Comment by torkelo** [comment]
and does that organization exist?

**Comment by isj4** [comment]
Yes, the organization "Hyatt Regency, Sacramento" exists. It is auto-completed. (the field is just too short to show the whole name in the screenshot)

**Comment by torkelo** [comment]
no idea what is going on, test multiple times here to replicate it but works every time, even behind nginx or apache proxy and behind sub path. Maybe something with your build, the logo seems to have been changed. 

Maybe something with the browser? tried chrome?

**Comment by isj4** [comment]
I found the cause after many tests. It depends on the username and email:
  username=user@domainX, email=user@domainY: fails
  username=user@domainX, email=user@domainX: works
  username=usernamewithnotatsign, email=user@domainX: works

So if the username contains an @-sign and does not match the emailaddress something goes when adding user to an organization. My guess (without having looked at the source code) is that the backend tries to determine what "loginOrEmail" is by checking the precence of an @-sign.

versions: Stock downloads 3.0.1 and 3.0.4. Yes, the logo is changed (overwriting after installation) because my users were apparently getting confused :-/
