### ISSUE TITLE
Grafana 9.0.3 Admin can not remove User's organizations

### ISSUE THREAD

**Issue by pablozone** [grafana/grafana#52434]
Admin can not remove User's organizations , after confirm removal, "not found" message appear.

![bug](https://user-images.githubusercontent.com/29774180/179693892-4d3a9018-e07a-46ee-9199-a206caade21b.jpg)

**Comment by IevaVasiljeva** [comment]
Hi @pablozone and thanks for reporting this issue! I've created a fix for it [here](https://github.com/grafana/grafana/pull/52473).
