### ISSUE TITLE
loki/prometheus json parser: return result directly

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#52430]
the JSON parser used by Loki and Prometheus ( https://github.com/grafana/grafana/blob/main/pkg/util/converter/prom.go#L27 ) returns a pointer to `backend.DataResponse` . considering it's a small object, it should probably return it directly as a not-pointer.

when it's a pointer, there is one more `is-nil` check the caller has to do.

**Comment by arpitbhardwaj** [comment]
HI @gabor Let me know if this issue is still open. If yes then i would love to pick it up and start working on this.

**Comment by gabor** [comment]
hi @arpitbhardwaj , yes, the issue is still open, feel free to work on it 👍
