### ISSUE TITLE
Grafana 8.5.4 -> 8.5.9 breaks State Timeline

### ISSUE THREAD

**Issue by MHeus** [grafana/grafana#52449]
**What happened**:

After upgrade from grafana 8.5.4 to 8.5.9 (did not try intermediate versions), the State Timeline panels now show values even though the underlying metrics are absent part of the time.

**What you expected to happen**:

When a metric goes from having a value to being absent, this should be reflected in the State Timeline panel.

**How to reproduce it (as minimally and precisely as possible)**:

Take a time series for which metrics are only available part of the time, on **8.5.4** the State Timeline would only display state when there actually was a value (1 in this example), and show nothing if the value was absent:
![Screenshot 2022-07-19 at 12 22 41](https://user-images.githubusercontent.com/7256056/179737339-3a0b8256-afb0-44cb-8dc2-58f0ea2e703b.png)

On **8.5.9** the state change from 1 to absent is no longer displayed, and that last state is being continued indefinitely:
![Screenshot 2022-07-19 at 12 54 03](https://user-images.githubusercontent.com/7256056/179737658-dea53b13-0627-4429-a318-6fcbb6d9fc5d.png)

**Anything else we need to know?**:
NA

**Environment**:
- Grafana version: 8.5.9
- Data source type & version: prometheus v2.37.0
- OS Grafana is installed on: RHEL8
- User OS & Browser: MacOS Monterey + Firefox/Chrome/Safari
- Grafana plugins: -
- Others: -

**Comment by codeincarnate** [comment]
Thanks for this report @MHeus! There have been changes in the way that null and empty values are handled since 8.4.4 so that may be causing this. Would you be able to provide an export of your dashboard? That would help us see what's going on in this case.

**Comment by MHeus** [comment]
When fiddling around to create a clean version of the dashboard to send in, I actually found a workaround but at the same time causing some other issues:

But I am a bit puzzled on the right combinations:
- Color Scheme on Single Color and Merge equal consecutive values enabled -> this has the null issue, and the value mapping works fine
- Color Scheme on Single Color and Merge equal consecutive values disabled ->  the has the null issue, but values are correct (for the non-null part) and mapping works
- Color Scheme on  From Thresholds and Merge equal consecutive values disabled ->  the has the null issue, but values are correct (for the non-null part) and mapping works
- Color Scheme on From Thresholds and Merge equal consecutive values enabled -> the null issue is solved, but then the values are all incorrectly listed as `< -∞` and value mapping does not work

 
So it seems the only way I can get the visualization to display as I expect is the last option, but then I cannot get correct values to show up.
 
An example panel JSON:
[state-timeline.json.txt](https://github.com/grafana/grafana/files/9157647/state-timeline.json.txt)

**Comment by codeincarnate** [comment]
I'm having trouble reproducing this issue locally. When adding null values they're not shown as would be expected in this case. Is some value set for the "No Value" settings option? This would transform any null values in this case. Otherwise, with merge consecutive values the labels are expected as labels are based on thresholds.

![Screen Shot 2022-07-27 at 3 13 11 PM](https://user-images.githubusercontent.com/199847/181363764-2956bc95-4151-4bc4-a0c6-1e7ce07bff31.png)

**Comment by MHeus** [comment]
Based on your screen shot you now have configured the only combination I found to work as well.
If you would now set the "Color Scheme" to Single Color, the null gap in the graph will disappear.

**Comment by zumby** [comment]
+1 we experience the same issue in 9.4.3

@codeincarnate on your screen, your dataset contains _nulls_ - probably, you would have to use some time series dataset with NO VALUES during some periods. 
This is exactly how we receive such result:
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/26290616/226711945-a91c84a5-9699-42c1-951d-2869f553316b.png">

But in reality it should look at least like this:
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/26290616/226712157-9ac801c6-560b-4635-8493-68af9df99dfd.png">

This is after unchecking 'Merge equal consecutive values' + increasing 'Line width'

**Comment by zumby** [comment]
@codeincarnate seems like even in grafana 9.5.1 issue still persists

**Comment by zumby** [comment]
@codeincarnate any update on this? i see many similar issues like this https://github.com/grafana/grafana/issues/54815
is anyone going to take a look at this?
