### ISSUE TITLE
Explore: Explore page crashes when using query inspector in Grafana 9

### ISSUE THREAD

**Issue by yesoreyeram** [grafana/grafana#52440]
When performing Query inspector operation in explore page, grafana crashes/freeze/throw error.  ( at least with logs datasource and grafana 9.0.3 )

example url : https://play.grafana.org/explore?orgId=1&left=%7B%22datasource%22:%22Loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bagent%3D%5C%22promtail%5C%22%7D%20%7C%3D%20%60%60%22,%22queryType%22:%22range%22,%22editorMode%22:%22builder%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D

Grafana version : 9.0.3
Datasource : Loki

Steps to reproduce
* visit the above play url
* click inspector button
* click JSON tab in the inspector
* wait for few seconds and browser will crash in some browsers/unresponsive page/ throw error.

<img width="1792" alt="image" src="https://user-images.githubusercontent.com/153843/179716906-d4a7ab5f-baac-40ea-bb74-23ab1d579cc7.png">

**Comment by Elfo404** [comment]
closing this in favor of https://github.com/grafana/grafana/issues/54188
