### ISSUE TITLE
Need you assistance on Grafana

### ISSUE THREAD

**Issue by Abhishekpan** [grafana/grafana#5244]
We are using GRAFANA with InfluxDB for my project but before that I have some doubts. Can you help me to overcome this?
 1. Is it possible to insert data into influxDB using Grafana GUI?  (For example suppose I get some CSV file and I want to store csv data into InfluxDB)

2. Is it possible to create functions on Grafana like SUM,MEAN,AVG ? If yes then can we use two separate function in single query ?

3. Currently we are facing some display issue on Grafana
I want top 3 source IP along with dOctets for a particular router on a given time period 
PFB query using for generate the graph
SELECT top("dOctets",srcaddr, 3) AS  "SOURCE_DETAILS" FROM "IWANT_AGG_5MIN_ALL" WHERE "RouterIP" = '100.100.0.10' AND "fieldtype" = '1' AND time > now() – 15m GROUP BY time(5m) fill(none)
 
We are able to display the data as a tabular format but not in graph format(Line chart).
Here srcaddr,router and fieldtype are Tags and dOctets is field.
Is it possible to shown above result set in Graph format(Line chart)?

Grafana Running on :: UNIX server 
                                     Memory - 32GB
                                     CPU - 16

**Comment by torkelo** [comment]
for questions please use the support channels
http://grafana.org/support/
