### ISSUE TITLE
Search V2: Add Analytics to Search Results

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#52451]
On the Search and Browse page instrument using Rudderstack the following events:
- [ ] Report Clicking on a search result (where do they click on it, e.g. starred list, recent list)
- [ ] Instrument all filters ( Tags, starred, include panels checkbox)

Check if it is possible to:  
- [ ] Count when the page is opened and how many searches were performed. Add that to the clickthrough (we have tags and starred, do we have panels?)

**Comment by ivanortegaalba** [comment]
Following the [recommendations](https://docs.google.com/document/d/1MTS5O5qsxtDptzN6AvdMRRGP38pvFc1NULsQKQN_z2U/edit#bookmark=id.nsmco4chv63f) to define a good tracking story:

**I want** when the user finds the results that we're looking for
**So** that we can ensure the search results are good enough for the user to try if this is the dashboard/panel/folder it was looking for

**Given** a user trying to find data in Grafana
**When** the user is using Search or Browse experiences
**Then** we emit a new event to RudderStack, `grafana_search_result_clicked` 
**And** the event contains the following properties:
* `list_type`: `starred_list | recent_list | folder`
* <Something else?>

---
**I want** to know how the user interacts with the filter exposed in the search view
**So** that we can ensure the filters are usable and findable by the user 

**Given** a user trying to find data in Grafana
**When** the user is using Search or Browse experiences, and it interacts with any of the filters
**Then** we emit a new event to RudderStack, `grafana_search_filter_by_tag_submitted` , `grafana_search_include_panels_submitted` , `grafana_search_by_name_submitted`
**And** the event contains the following properties:
* <Something?>
