### ISSUE TITLE
More logging info for trace level

### ISSUE THREAD

**Issue by adrianlzt** [grafana/grafana#5245]
Today I have a problem with LDAP, I activated set log level to Trace and I was expecting hundres of lines tracing the server execution, but the log file was almost the same.

In my opinion, trace level should be much much more verbose.

**Comment by torkelo** [comment]
Yes, I agree. There is also a logging option in the ldap.toml file which when enabled prints more info from the response from the LDAP server.

**Comment by torkelo** [comment]
Could you be more specific though with exactly what your missing?

**Comment by adrianlzt** [comment]
For me, trace mode is, more or less, one line per function. Example of nagios in trace mode: https://support.nagios.com/forum/viewtopic.php?f=7&t=30119#p117441

I was having the problem that I comment in the PR and was hard to know why ldap wasn't working.

**Comment by torkelo** [comment]
Not sure why logging function calls is useful, current ldap logging will log ldap response and errors.  The org and role syncing could have much better logging though :)

**Comment by adrianlzt** [comment]
When something strange happens, be able to pinpoint which part of the code is the responsible helps a lot. At least I have seen this many times.
Sometimes will be some config error (like today for me), but other times could be some bug in the code.

**Comment by zstyblik** [comment]
I would say this has improved in 3.1:

```
INFO[06-08|07:55:44] Server Listening                         logger=server address=0.0.0.0:3000 protocol=http subUrl=
INFO[06-08|07:55:49] Request Completed                        logger=context userId=2 orgId=1 uname=XXXX method=GET path=/logout status=302 remote_addr=172.17.0.1 time_ns=0 size=29
INFO[06-08|07:55:56] Ldap User Info: [(*login.ldapUserInfo)(0xc82013fce0)({
 DN: (string) (len=75) "CN=XXX,OU=XXX,OU=XXX,DC=XXX",
 FirstName: (string) (len=6) "XXX",
 LastName: (string) (len=7) "XXX",
 Username: (string) (len=7) "XXX",
 Email: (string) (len=26) "XXX",
 MemberOf: ([]string) (len=19 cap=32) {
  (string) (len=51) "X",
  (string) (len=85) "X",
  (string) (len=67) "X",
  (string) (len=88) "X",
  (string) (len=91) "X",
  (string) (len=80) "X",
  (string) (len=73) "X",
  (string) (len=107) "X",
  (string) (len=89) "X",
  (string) (len=78) "X",
  (string) (len=92) "X",
  (string) (len=85) "X",
  (string) (len=83) "X",
  (string) (len=86) "X",
  (string) (len=70) "X",
  (string) (len=88) "X",
  (string) (len=82) "X",
  (string) (len=69) "X",
  (string) (len=66) "X"
 }
})
]

EROR[06-08|07:59:08] [Error while trying to authenticate user LDAP Result Code 200 "": dial tcp X:636: getsockopt: connection refused]: %!v(MISSING) 
INFO[06-08|07:59:08] Request Completed                        logger=context userId=0 orgId=1 uname= method=POST path=/login status=500 remote_addr=172.17.0.1 time_ns=79ns size=53

INFO[06-08|08:02:16] LDAP initial bind failed, [LDAP Result Code 49 "Invalid Credentials": 80090308: LdapErr: DSID-0C0903A9, comment: AcceptSecurityContext error, data 52e, v1db1] 
EROR[06-08|08:02:16] [Invalid username or password Invalid Username or Password]: %!v(MISSING) 
INFO[06-08|08:02:16] Request Completed                        logger=context userId=0 orgId=1 uname= method=POST path=/login status=401 remote_addr=172.17.0.1 time_ns=130ns size=42
```

**Comment by zstyblik** [comment]
@torkelo, btw `[Invalid username or password Invalid Username or Password]: %!v(MISSING)` is `(MISSING)` on purpose?
