### ISSUE TITLE
[Discussion] Deprecation of Tags from OpenTSDB metric editor

### ISSUE THREAD

**Issue by utkarshcmu** [grafana/grafana#5247]
This is question for all Grafana-OpenTSDB users:

As we know Tags are deprecated from OpenTSDB 2.2, but they are supported in Grafana for OpenTSDB 2.2 (with a deprecation warning). As we need to start supporting OpenTSDB 2.3 and expressions, the metric editor will be huge, so should we remove "Tags" from the editor completely and rely on "Filters" for the versions of OpenTSDB>=2.3 ?

Any feedback will be great, Thanks!!!

**Comment by utkarshcmu** [comment]
@vitorboschi @johann8384 @digrich @WengFenjin @bobrik @IzakMarais @amalshah 

Let me know what do you guys think on removing "Tags" from the metric editor for OpenTSDB>=2.3

Thanks !!!

**Comment by bobrik** [comment]
Can we transparently translate tags from saved dashboards into filters?

**Comment by vitorboschi** [comment]
I think the main issue is providing a good migration path, so that users don't have to fix tons of dashboards. Other than that, I don't see any problem in getting rid of tags.

**Comment by digrich** [comment]
We are having hundreds of dashboards, so only concern is the migration path.

**Comment by digrich** [comment]
Can anyone please tell, how we can use template 'All' option with filters? With tags option, it is easy to map All with * character but in filters we have to change the filter type to use that wildcard.

**Comment by ramm** [comment]
There's also a bug with alias strings like `something $tag_something` being messed up in the table panels

**Comment by markbaas** [comment]
Fix for issue #5273 mentioned by @ramm: https://github.com/grafana/grafana/pull/5275

**Comment by utkarshcmu** [comment]
I came up with 3 mappings:

Tags to Filters map:

1. tag_key = tag_value1|tag_value_2 -> tag_key = literal_or(tag_value1|tag_value_2)
2. tag_key = abc* -> tag_key = wildcard(abc*)
3. tag_key = tag_value_1 -> tag_key = literal_or(tag_value_1)

So, when you upgrade datasource to Opentsdb 2.3 in your Grafana setup, the tags will automatically get converted to Filters using the above map.

Can you guys think about more cases where we can apply Tag > Filter mappings.

**Comment by digrich** [comment]
How will the filters work with template variables? 
For 'All', we may have to use wildcard and for multi-selection, we have to use literal_or function.  Not sure on template variable change event, how the query will use right filter function.

**Comment by torkelo** [comment]
Sorry, stale bot was wrongly configured (should only have acted on PRs)

**Comment by daniellee** [comment]
This hasn't had any activity for a long time so closing. We can re-open it if it is still relevant.
