### ISSUE TITLE
[Question] Is it possible to read LDAP bind password from an environment variable?

### ISSUE THREAD

**Issue by sgarg7** [grafana/grafana#5248]
I would prefer not to add LDAP password for the first bind user to the ldap.toml file. It would be nice to be able to use environment variables like the main Grafana config file does. I couldn't find in the documentation that ldap.toml supports this. Does it? Can it be added if it doesn't?

**Comment by torkelo** [comment]
no, the ldap config does not support this, will likely not be added. 

The initial ldap bind password does not need to be user with many ldap permissions, only read/search permissions.

**Comment by nemo83** [comment]
is this still the case?

**Comment by wayneworkman** [comment]
I'd prefer LDAP to be configured via environment variables.

**Comment by flamein** [comment]
Please take a look at https://github.com/grafana/grafana/pull/17526
