### ISSUE TITLE
When saving a provisioned dashboard and clicking 'Copy to clipboard', newlines in prettified JSON are removed

### ISSUE THREAD

**Issue by adeverteuil** [grafana/grafana#52488]
**What happened**:

I have a provisioned dashboard. When I save edits made in the UI, I see the popup window with the JSON model in a text box and the 'Copy to clipboard' button.

This feature is documented here: https://grafana.com/docs/grafana/latest/administration/provisioning/#making-changes-to-a-provisioned-dashboard

When I click the 'Copy to clipboard' button, the JSON model is copied to my clipboard, but with newlines removed.

**What you expected to happen**:

I would expect the newlines to be preserved.

Pasting a single very long line (several kilobytes) in a text editor is not efficient. The software spends many seconds computing soft line wraps. It is also very difficult to diff changes. I don't care about the file size enough to expect a minimized JSON document.

**How to reproduce it (as minimally and precisely as possible)**:

Here is a sample dashboard with a single panel.

![Screenshot 2022-07-19 17-45-42 copy to clipboard](https://user-images.githubusercontent.com/3270755/179854151-c3988da0-8e9f-43b8-a5fc-1b59236e8e59.png)

I clicked 'Copy to clipboard' and pasted here:

```
{  "annotations": {    "list": [      {        "builtIn": 1,        "datasource": {          "type": "grafana",          "uid": "-- Grafana --"        },        "enable": true,        "hide": true,        "iconColor": "rgba(0, 211, 255, 1)",        "name": "Annotations & Alerts",        "target": {          "limit": 100,          "matchAny": false,          "tags": [],          "type": "dashboard"        },        "type": "dashboard"      }    ]  },  "editable": true,  "fiscalYearStartMonth": 0,  "graphTooltip": 0,  "links": [],  "liveNow": false,  "panels": [    {      "datasource": {        "type": "testdata",        "uid": "P53465F745837BCFD"      },      "fieldConfig": {        "defaults": {          "color": {            "mode": "palette-classic"          },          "custom": {            "axisLabel": "",            "axisPlacement": "auto",            "barAlignment": 0,            "drawStyle": "line",            "fillOpacity": 0,            "gradientMode": "none",            "hideFrom": {              "legend": false,              "tooltip": false,              "viz": false            },            "lineInterpolation": "linear",            "lineWidth": 1,            "pointSize": 5,            "scaleDistribution": {              "type": "linear"            },            "showPoints": "auto",            "spanNulls": false,            "stacking": {              "group": "A",              "mode": "none"            },            "thresholdsStyle": {              "mode": "off"            }          },          "mappings": [],          "thresholds": {            "mode": "absolute",            "steps": [              {                "color": "green",                "value": null              },              {                "color": "red",                "value": 80              }            ]          }        },        "overrides": []      },      "gridPos": {        "h": 9,        "w": 12,        "x": 0,        "y": 0      },      "id": 2,      "options": {        "legend": {          "calcs": [],          "displayMode": "list",          "placement": "bottom"        },        "tooltip": {          "mode": "single",          "sort": "none"        }      },      "title": "Panel Title",      "type": "timeseries"    }  ],  "schemaVersion": 36,  "style": "dark",  "tags": [],  "templating": {    "list": []  },  "time": {    "from": "now-6h",    "to": "now"  },  "timepicker": {},  "timezone": "",  "title": "Test provisioned dashboard",  "uid": "XFLTq2RVk",  "version": 1,  "weekStart": ""}
```

It seems that the indentation spaces of the prettified JSON are preserved, so I don't think the design intent was to copy the minified JSON. I wouldn't want the minified JSON.

**Anything else we need to know?**:

As a workaround, I click in the text box and I select all and copy the JSON text with `Ctrl + A` and `Ctrl + C`.

**Environment**:
- Grafana version: v9.0.3
- Data source type & version:
- OS Grafana is installed on: Ubuntu 20.04
- User OS & Browser: Firefox
- Grafana plugins:
- Others:

**Comment by joshhunt** [comment]
I'm curious @mellieA - do you know if this happened on Grafana running elsewhere and being served over HTTP***S*** (like Grafana Cloud?) or was Grafana running locally or over http.

**Comment by natellium** [comment]
We moved this one to user essentials as it seems like a general issue with the copy button rather than a dashboards related one.

**Comment by JoaoSilvaGrafana** [comment]
So this is due to the clipboard button's fallback usage from [this line](https://github.com/grafana/grafana/blob/main/packages/grafana-ui/src/components/ClipboardButton/ClipboardButton.tsx#L91).
Basically if the browser does not support the navigator API OR if the context is not secure (hence the question from Josh), it will put all the content into an `input` component and copy from that, however `input` components don't allow for newlines. I think the fix should be to change it from an `input` component to a `textarea` component
