### ISSUE TITLE
Alerting `state.Manager` writes alert instance states to the state history interface

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#52499]
Part of #48359 

[Grafana Internal Design Document](https://docs.google.com/document/d/15KMBhUFPDkzWWpjZSXw1L3zsuEVg2xzZJEuuNiEfFn8/edit#)

When a rule is evaluated, any generated alert instances should be written to the Alert State History interface. The implementation of the interface is responsible for deciding whether a given write should be actually persisted to storage. For example, the SQL implementation of the interface may not need to write down every evaluation of the rule - perhaps it need only write down state changes and periodic heartbeats of the state change.

**Comment by alexweav** [comment]
Completed by https://github.com/grafana/grafana/pull/56575
