### ISSUE TITLE
Create a fake or test data implementation of alert state history storage

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#52497]
Part of #48359

[Grafana Internal Design Document](https://docs.google.com/document/d/15KMBhUFPDkzWWpjZSXw1L3zsuEVg2xzZJEuuNiEfFn8/edit#)

Create a fake implementation of #52496. This will be useful for developing the external HTTP API format, and for building frontend components before #48359 is complete.

**Comment by alexweav** [comment]
Closed by https://github.com/grafana/grafana/pull/61006
