### ISSUE TITLE
Create a write interface for alert state history storage

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#52496]
Part of #48359 

[Grafana Internal Design Document](https://docs.google.com/document/d/15KMBhUFPDkzWWpjZSXw1L3zsuEVg2xzZJEuuNiEfFn8/edit#)

The interface should allow:
* Storing a `models.AlertInstance` with a timestamp.
* Retrieving a set of AlertInstances, ordered by time. They can be queried by 
    * a time range [start, limit) (required)
    * an alert rule ID (optional)

**Comment by alexweav** [comment]
Will be solved by https://github.com/grafana/grafana/pull/56575

**Comment by alexweav** [comment]
Split in half -the other half is https://github.com/grafana/grafana/issues/58351

**Comment by alexweav** [comment]
Solved by #56575
