### ISSUE TITLE
Weird behaviour. Singlestat and influxdb, is time shift ignored?

### ISSUE THREAD

**Issue by girgen** [grafana/grafana#5250]
Grafana 3.0.4, InfluxDB 0.13.0

I'm sending a simple metric, online_total, every 60 seconds from a bunch of servers to an influxdb. The metrics are not sent at each 00 seconds on the wall clock, instead, each server's start time is random and they each send a new metric every 60 seconds.

The query `select sum(value) from online_total where time > '2016-06-01 22:34:00' group by time(1m) ` gives the expected result in influxdb:

2016-06-01T22:51:00Z	9297
2016-06-01T22:52:00Z	9224
2016-06-01T22:53:00Z	9150
2016-06-01T22:54:00Z	9103
2016-06-01T22:55:00Z	9024
2016-06-01T22:56:00Z	8952
2016-06-01T22:57:00Z	2828

The last one should be ignored since it data is not completely reported for that minute yet. Fine. Grafana has *time shift* for this.

I'd like to show this in a Singlestat. Grafana behaves very randomly here.

`SELECT sum("value") FROM "online_total" WHERE "host" =~ /^$host$/ AND $timeFilter GROUP BY time($interval) fill(previous)` 

time interval = 1m  (exact, not >)
add time shift = 2m
value = current

When I change any parameter, the correct value pops up for a few seconds, but then it seems to fall back to the latst value, the one that is not complete. As if it forgets the **time shift**. Is it perhaps a bug?

Thanks,
Palle

**Comment by torkelo** [comment]
Have not managed to replicate this. 

Can you check the chrome dev tools network tab? There you can see all requests made to InfluxDB by Grafana, you can see the time range filter and validate that the correct timeshift is applied.

**Comment by girgen** [comment]
the query is

select sum("value") from "online_total" WHERE time > 1464700033s and time < 1464872833s GROUP BY time(1m) fill(previous)

the request was sent Date: Thu, 02 Jun 2016 13:09:13 GMT which is exactly 1464872833s

so, no, seems there is no time shift involved in the query?

**Comment by girgen** [comment]
@torkelo Hej, tack för ikväll! Se ovan, ser ut som jag lämnat detaljer? :-)

**Comment by torkelo** [comment]
I am still unable to replicate this. 

specifying a 2m timeshift, I always get a query with time < `epoch` 
where epoch is 2m from now.
