### ISSUE TITLE
Allow choosing of alert state history backend through configuration

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#52501]
Part of #48359 

[Grafana Internal Design Document](https://docs.google.com/document/d/15KMBhUFPDkzWWpjZSXw1L3zsuEVg2xzZJEuuNiEfFn8/edit#)

Configuration should:
* Enable or disable alert state history entirely
* Control which implementation ([test, sql, loki]) is in use
* Provide a configuration section where implementation-specific configuration flags can be defined.

**Comment by alexweav** [comment]
Scoping this down slightly -
Implementation-specific config flags will be implemented alongside the appropriate implementations.

We don't know what the set of flags are yet until the implementations are done. But, we need configuration support to happen first, so we are able to toggle the backend.

This issue now only captures the ability to toggle/configure state history _in general_.
