### ISSUE TITLE
Implement an HTTP API for alert state history

### ISSUE THREAD

**Issue by joeblubaugh** [grafana/grafana#52500]
Part of #48359 

[Grafana Internal Design Document](https://docs.google.com/document/d/15KMBhUFPDkzWWpjZSXw1L3zsuEVg2xzZJEuuNiEfFn8/edit#)

Related to #51319 - the preview endpoint and the state history endpoint should share the same response format.

**Comment by alexweav** [comment]
Closing in favor of a more granular set of tasks
