### ISSUE TITLE
Grafana shows data only for 'Today', but no data for 'This week', or 'last 7 days'

### ISSUE THREAD

**Issue by dnayyl** [grafana/grafana#5252]
I am importing graphite weewx weather data to grafana every 5min; however, the data only shows for 'Today', 'last 3 hour','last 24 hours', but not for 'the last 7 days' or 'this week'.

Dawei

**Comment by torkelo** [comment]
Check your graphite storage schema config file (retention settings).  

Please use the mailing list for questions:
http://grafana.org/support/
