### ISSUE TITLE
UX: Search V2 -  Add filters in small viewports

### ISSUE THREAD

**Issue by axelavargas** [grafana/grafana#52530]
Currently filters from the Search and Browse pages are hidden in small viewports, we would like to add them.

### Current behavior 
<img width="485" alt="image (3)" src="https://user-images.githubusercontent.com/239999/179983842-ba1fbce5-2dea-40ed-829b-4c30e250dd22.png">

**Comment by axelavargas** [comment]
@amy-super :)

**Comment by amy-super** [comment]
@axelavargas do you want to include sorting also?

**Comment by amy-super** [comment]
[Here's an idea](https://www.figma.com/proto/cCXNu2e810EwmurhDuhXYL/Search?page-id=585%3A27&node-id=594%3A193&scaling=min-zoom&starting-point-node-id=594%3A193&show-proto-sidebar=1) of how we might be able to do this without taking up too much screen real estate. Note this is exactly how `Query history` works in Explore.
