### ISSUE TITLE
[QUESTION] Is it possible to get a list of PanelID for a dashboard (and do not expose JSON file)?

### ISSUE THREAD

**Issue by NUS-Anonymous** [grafana/grafana#5254]
I would like to extract the list of panelID for the panels within my dashboard, currently, I have to extract that information from the JSON file, but I do not want to expose other information inside the JSON file so I wonder if there is any way to extract only panelID? Thanks in advance.

**Comment by torkelo** [comment]
no, the panel ids are only in the JSON file. 

Not sure what you mean "expose", the dashboard json is viewable with anyone with access to the dashboard (viewer role for example, or anonymous use if that is enabled in config)
