### ISSUE TITLE
Plugins page without sub path

### ISSUE THREAD

**Issue by S0ulHunt3r** [grafana/grafana#52556]
**What happened**:
When i load the list of plugins and i click one i get "page not found". 
This is a configuration behind a reverse proxy, so i am using sub path. I see that all the plugins dont have the subpath on the url, so i have to put it manually on browser url.
**What you expected to happen**:
I expect to see the details of plugin
**How to reproduce it (as minimally and precisely as possible)**:
1- Behind a reverse proxy with sub path "t-grafana"
1.1- Load plugins list
1.2- Click in any plugin

**Anything else we need to know?**:
Nope

**Environment**:
- Grafana version: 9.0.4
- Data source type & version: 
- OS Grafana is installed on: Red hat 7
- User OS & Browser: Chrome
- Grafana plugins: Defaults
- Others:

**Comment by ashharrison90** [comment]
hi @S0ulHunt3r 👋 

i'm not able to reproduce this, but have only tried locally so far (not behind nginx)

are you able to share what your grafana config looks like? specifically the `[server]` section? most interesting lines are:
```
[server]
domain = example.com
root_url = %(protocol)s://%(domain)s:%(http_port)s/grafana/
serve_from_sub_path = true
```

see e.g. https://grafana.com/tutorials/run-grafana-behind-a-proxy/

**Comment by S0ulHunt3r** [comment]
Hi, my config:
`[server]
domain = domain.dom.do
root_url = %(protocol)s://%(domain)s/t-grafana/
serve_from_sub_path = true
`

**Comment by ashharrison90** [comment]
@S0ulHunt3r with it working locally that url still doesn't have the subpath. assume it goes to the original url then reroutes to the subpath url, so i think that might be a red herring. 

my nginx isn't the best, but i think you're missing a section from your nginx config:
```
  rewrite  ^/t-grafana/(.*)  /$1 break;
```

see the `sub path` section in https://grafana.com/tutorials/run-grafana-behind-a-proxy/#configure-nginx

**Comment by S0ulHunt3r** [comment]
Hi, i think that that line is not needed, but ok, now try to open the plugin in a new tab.

**Comment by ashharrison90** [comment]
@S0ulHunt3r opening in a new tab also works locally

let me know if that resolves the problem 👍

**Comment by S0ulHunt3r** [comment]
For me it doesn't open because the tooltip url don't comes with the context, and for nginx it must have the context because i have 2 grafana instances being served. 
For example, i downloaded the windows version, and i can open the plugins page, and plugin, because the service respond's with and without context, but when you have a proxy behind you should serve that plugins page with the context.
![WhereIsContext](https://user-images.githubusercontent.com/916396/181304176-7a34a171-7f65-48db-92d8-8c24a53d3e71.png)

**Comment by S0ulHunt3r** [comment]
Hi, i installed version 9.1.2 and the problem persists even in private mode. Do i have to change something in my configuration?
![image](https://user-images.githubusercontent.com/916396/188182659-d671fdca-3420-4f3e-9e95-0ab7d50670ec.png)
