### ISSUE TITLE
Epic: Make migration of secrets to secretsmanager plugins faster

### ISSUE THREAD

**Issue by mmandrus** [grafana/grafana#52560]
- [x] #52563
- [x] #52564
- [ ] #52565

**Comment by torkelo** [comment]
plugin migration in the backend?

**Comment by mmandrus** [comment]
> plugin migration in the backend?

Updated the title to clarify.

We have all of these on a specific project board so we sometimes forget sufficient detail 😅

**Comment by torkelo** [comment]
ah, thanks :)
