### ISSUE TITLE
Connections Page: investigate user roles

### ISSUE THREAD

**Issue by leventebalogh** [grafana/grafana#52592]
### What is the problem?

We currently display the Connections page and it's contents regardless of the users' role.

---

### Proposed solution
- [x] Investigate / figure out what permissions we expect from the user to view our pages
- [x] Backend Guard: hide the page from the navigation in case the user doesn't have the necessary permission(s)
- [x] Frontend Guard: don't display the original content in case the user doesn't have the necessary permission(s)

We should use the [available fixed permissions](https://github.com/grafana/grafana/blob/v9.1.0-beta1/public/app/types/accessControl.ts#L10) instead of the basic roles (Viewer, Editor, Admin, Server Admin) with a meaningful fallback wherever possible.
  
**Example:**
```javascript
// contextSrv.hasAccess("<permission>", "<fallback role, used if RBAC is not enabled>");
contextSrv.hasAccess(AccessControlAction.DataSourcesRead, contextSrv.isGrafanaAdmin);
```
---

**Which role can do what?**
![Screenshot 2023-01-05 at 13 44 51](https://user-images.githubusercontent.com/9974811/210800926-d2d1a541-76ba-482d-9a17-23938c1e69ef.png)

**Comment by mikkancso** [comment]
FTR, I started to gather our pages and actions and the corresponding permissions needed for them in [this spreadsheet](https://docs.google.com/spreadsheets/d/1TSmFBMduh3BmFzPeRqHwldsfsdNW1C3rFONYcKumDOY/edit?usp=sharing)

**Comment by leventebalogh** [comment]
Amazing 👍

**Comment by mikkancso** [comment]
I think the two PRs above should cover everything in this ticket

**Comment by leventebalogh** [comment]
(Updated the PR (https://github.com/grafana/grafana/pull/60725) so it is closing this issue.)
