### ISSUE TITLE
[Feature request] ElasticSearch datasource - simple graph without aggregation

### ISSUE THREAD

**Issue by Turum** [grafana/grafana#5259]
It would be great to have simple graph without aggregation with ElasticSearch datasource.
Like in Timelion plugin for kibana.
https://www.elastic.co/blog/timelion-timeline
Thanks.

**Comment by torkelo** [comment]
you need at least one aggregation, it's impossible to get a time series graph otherwise. timelion makes a date histogram with all es queries. 

Could you describe your data and how you want to viz it?

**Comment by Turum** [comment]
I have information about trades, such as datetime, seccode, price and value. I want to make a dependency graph of the price from time. Y axis - Price, X- datetime, but as I see I only can do it with some math function like avg or min/max.
Thanks.

**Comment by torkelo** [comment]
yes? and if two documents are in the same "time bucket" what then? need a way to combine them to one point (aggregate) on the graph

**Comment by Turum** [comment]
Yes you are right, this is a problem. It's hard to move away from the relational thinking ))). Thanks. I think we can close the topic.
