### ISSUE TITLE
geomap plugin tooltip screen location

### ISSUE THREAD

**Issue by chaos-user** [grafana/grafana#52602]
**What happened**:

After update grafana 8X to 9X the geomap tooltipo screen location is not working as expected.
The tooltip window is not located near mouse pointer and have lost vertical scrool bar when serveral items are listed.

**What you expected to happen**:
Tooltip located near mouse pointer
When several objects listed at tooltip, make vertical scrool bar available

**How to reproduce it (as minimally and precisely as possible)**:
https://user-images.githubusercontent.com/75700201/180203872-9b7e3c3e-2b49-4b0c-b3e2-7a6618ecfa6e.mp4

**Anything else we need to know?**:
geomap configs:
view: coordinates
location: coordinates
layer type: CARTO reference map
Theme: auto
tooltip: details
color scheme: From Thresholds

**Environment**:
- Grafana version: 9.0.4 OSS
- Data source type & version: influxDB
- OS Grafana is installed on: UBUNTU 20.04
- User OS & Browser: Windows 11 - Chrome
- Grafana plugins: geomap 5.0.0
- Others:

**Comment by ShakreeElmi** [comment]
Having the same issue

**Comment by CourchesneA** [comment]
This have been a huge issue for us, it was also introduced in grafana cloud. It seems the tooltip location is computed using a wrong multiplier on the scroll location (i.e. the distance between the data point and the tooltip location gets bigger / smaller as we scroll the page)

**Comment by Shadrack88** [comment]
i try to activate the display tooltip button but i couldnt.
