### ISSUE TITLE
Dashboard: Time Range object doesn't update in table view

### ISSUE THREAD

**Issue by shoopapa** [grafana/grafana#52613]
**What happened**: The time range doesn't update in the data source query hook for a custom data source plugin when in table view

**What you expected to happen**: I expect to time range object to update even when in the table view.

**How to reproduce it (as minimally and precisely as possible)**: console log the time range object when in table view and change the time range, it will keep passing the same time range when you first switched to table view, if you turn off table view then time range will pass correctly.

**Anything else we need to know?**:

**Environment**: docker
- Grafana version: v9.0.3 (023f9251a9)
- Data source type & version: custom data source plugin
- OS Grafana is installed on: running in Docker: on Debian OS
- User OS & Browser: Mac: Chrome
- Grafana plugins: none, other than frontend Datasource template

![grafana-time-bug](https://user-images.githubusercontent.com/45986634/180244896-036a2e17-edc9-408d-a2f0-d79fdc063168.gif)

**Comment by axelavargas** [comment]
Hey @shoopapa 👋🏾, thanks for reporting this issue, I was able to reproduce it and will be prioritizing it in the near future.
