### ISSUE TITLE
about grafana elasticsearch query request timezone

### ISSUE THREAD

**Issue by tonyC2016** [grafana/grafana#5261]
i use grafana2.6.0 Unique Count for String ,and it respone a different time,maybe about timezone,

the request jsonStr is:
{
    "search_type": "count",
    "ignore_unavailable": true,
    "index": "goods-source-search-hot-log"
}{
    "size": 0,
    "query": {
        "filtered": {
            "query": {
                "query_string": {
                    "analyze_wildcard": true,
                    "query": "*"
                }
            },
            "filter": {
                "bool": {
                    "must": [
                        {
                            "range": {
                                "inputDate": {
                                    "gte": "1464710400000",
                                    "lte": "1464796799999"
                                }
                            }
                        }
                    ]
                }
            }
        }
    },
    "aggs": {
        "2": {
            "date_histogram": {
                "interval": "10m",
                "field": "inputDate",
                "min_doc_count": 0,
                "extended_bounds": {
                    "min": "1464710400000",
                    "max": "1464796799999"
                }
            },
            "aggs": {
                "1": {
                    "cardinality": {
                        "field": "driverParty.partyId"
                    }
                }
            }
        }
    }
}

and the respone STR
{
    "responses": [
        {
            "took": 62,
            "timed_out": false,
            "_shards": {
                "total": 5,
                "successful": 5,
                "failed": 0
            },
            "hits": {
                "total": 334746,
                "max_score": 0,
                "hits": []
            },
            "aggregations": {
                "2": {
                    "buckets": [
                        {
                            "1": {
                                "value": 47
                            },
                            "key_as_string": "2016-05-31T16:00:00.000Z",
                            "key": 1464710400000,
                            "doc_count": 195
                        },
                        {
                            "1": {
                                "value": 38
                            },
                            "key_as_string": "2016-05-31T16:10:00.000Z",
                            "key": 1464711000000,
                            "doc_count": 185
                        },
                        {
                            "1": {
                                "value": 41
                            },
                            "key_as_string": "2016-05-31T16:20:00.000Z",
                            "key": 1464711600000,
                            "doc_count": 205
                        },
                        {
                            "1": {
                                "value": 36
                            },
                            "key_as_string": "2016-05-31T16:30:00.000Z",
                            "key": 1464712200000,
                            "doc_count": 183
                        },
                        {
                            "1": {
                                "value": 33
                            },
                            "key_as_string": "2016-05-31T16:40:00.000Z",
                            "key": 1464712800000,
                            "doc_count": 161
                        },
                        {
                            "1": {
                                "value": 38
                            },
                            "key_as_string": "2016-05-31T16:50:00.000Z",
                            "key": 1464713400000,
                            "doc_count": 155
                        },
                        {
                            "1": {
                                "value": 24
                            },
                            "key_as_string": "2016-05-31T17:00:00.000Z",
                            "key": 1464714000000,
                            "doc_count": 129
                        },
                        {
                            "1": {
                                "value": 33
                            },
                            "key_as_string": "2016-05-31T17:10:00.000Z",
                            "key": 1464714600000,
                            "doc_count": 200
                        },
                        {
                            "1": {
                                "value": 35
                            },
                            "key_as_string": "2016-05-31T17:20:00.000Z",
                            "key": 1464715200000,
                            "doc_count": 203
                        },
                        {
                            "1": {
                                "value": 15
                            },
                            "key_as_string": "2016-05-31T17:30:00.000Z",
                            "key": 1464715800000,
                            "doc_count": 90
                        },
                        {
                            "1": {
                                "value": 21
                            },
                            "key_as_string": "2016-05-31T17:40:00.000Z",
                            "key": 1464716400000,
                            "doc_count": 126
                        },
                        {
                            "1": {
                                "value": 23
                            },
                            "key_as_string": "2016-05-31T17:50:00.000Z",
                            "key": 1464717000000,
                            "doc_count": 113
                        },
                        {
                            "1": {
                                "value": 23
                            },
                            "key_as_string": "2016-05-31T18:00:00.000Z",
                            "key": 1464717600000,
                            "doc_count": 165
                        },
                        {
                            "1": {
                                "value": 28
                            },
                            "key_as_string": "2016-05-31T18:10:00.000Z",
                            "key": 1464718200000,
                            "doc_count": 194
                        },
                        {
                            "1": {
                                "value": 25
                            },
                            "key_as_string": "2016-05-31T18:20:00.000Z",
                            "key": 1464718800000,
                            "doc_count": 162
                        },
                        {
                            "1": {
                                "value": 18
                            },
                            "key_as_string": "2016-05-31T18:30:00.000Z",
                            "key": 1464719400000,
                            "doc_count": 138
                        },
                        {
                            "1": {
                                "value": 19
                            },
                            "key_as_string": "2016-05-31T18:40:00.000Z",
                            "key": 1464720000000,
                            "doc_count": 161
                        },
                        {
                            "1": {
                                "value": 16
                            },
                            "key_as_string": "2016-05-31T18:50:00.000Z",
                            "key": 1464720600000,
                            "doc_count": 126
                        },
                        {
                            "1": {
                                "value": 16
                            },
                            "key_as_string": "2016-05-31T19:00:00.000Z",
                            "key": 1464721200000,
                            "doc_count": 165
                        },
                        {
                            "1": {
                                "value": 12
                            },
                            "key_as_string": "2016-05-31T19:10:00.000Z",
                            "key": 1464721800000,
                            "doc_count": 117
                        },
                        {
                            "1": {
                                "value": 22
                            },
                            "key_as_string": "2016-05-31T19:20:00.000Z",
                            "key": 1464722400000,
                            "doc_count": 149
                        },
                        {
                            "1": {
                                "value": 17
                            },
                            "key_as_string": "2016-05-31T19:30:00.000Z",
                            "key": 1464723000000,
                            "doc_count": 115
                        },
                        {
                            "1": {
                                "value": 19
                            },
                            "key_as_string": "2016-05-31T19:40:00.000Z",
                            "key": 1464723600000,
                            "doc_count": 132
                        },
                        {
                            "1": {
                                "value": 23
                            },
                            "key_as_string": "2016-05-31T19:50:00.000Z",
                            "key": 1464724200000,
                            "doc_count": 151
                        },
                        {
                            "1": {
                                "value": 12
                            },
                            "key_as_string": "2016-05-31T20:00:00.000Z",
                            "key": 1464724800000,
                            "doc_count": 103
                        },
                        {
                            "1": {
                                "value": 25
                            },
                            "key_as_string": "2016-05-31T20:10:00.000Z",
                            "key": 1464725400000,
                            "doc_count": 185
                        },
                        {
                            "1": {
                                "value": 27
                            },
                            "key_as_string": "2016-05-31T20:20:00.000Z",
                            "key": 1464726000000,
                            "doc_count": 136
                        },
                        {
                            "1": {
                                "value": 21
                            },
                            "key_as_string": "2016-05-31T20:30:00.000Z",
                            "key": 1464726600000,
                            "doc_count": 102
                        },
                        {
                            "1": {
                                "value": 35
                            },
                            "key_as_string": "2016-05-31T20:40:00.000Z",
                            "key": 1464727200000,
                            "doc_count": 213
                        },
                        {
                            "1": {
                                "value": 38
                            },
                            "key_as_string": "2016-05-31T20:50:00.000Z",
                            "key": 1464727800000,
                            "doc_count": 213
                        },
                        {
                            "1": {
                                "value": 55
                            },
                            "key_as_string": "2016-05-31T21:00:00.000Z",
                            "key": 1464728400000,
                            "doc_count": 397
                        },
                        {
                            "1": {
                                "value": 71
                            },
                            "key_as_string": "2016-05-31T21:10:00.000Z",
                            "key": 1464729000000,
                            "doc_count": 568
                        },
                        {
                            "1": {
                                "value": 93
                            },
                            "key_as_string": "2016-05-31T21:20:00.000Z",
                            "key": 1464729600000,
                            "doc_count": 665
                        },
                        {
                            "1": {
                                "value": 121
                            },
                            "key_as_string": "2016-05-31T21:30:00.000Z",
                            "key": 1464730200000,
                            "doc_count": 809
                        },
                        {
                            "1": {
                                "value": 162
                            },
                            "key_as_string": "2016-05-31T21:40:00.000Z",
                            "key": 1464730800000,
                            "doc_count": 999
                        },
                        {
                            "1": {
                                "value": 202
                            },
                            "key_as_string": "2016-05-31T21:50:00.000Z",
                            "key": 1464731400000,
                            "doc_count": 1226
                        },
                        {
                            "1": {
                                "value": 286
                            },
                            "key_as_string": "2016-05-31T22:00:00.000Z",
                            "key": 1464732000000,
                            "doc_count": 1656
                        },
                        {
                            "1": {
                                "value": 345
                            },
                            "key_as_string": "2016-05-31T22:10:00.000Z",
                            "key": 1464732600000,
                            "doc_count": 1979
                        },
                        {
                            "1": {
                                "value": 392
                            },
                            "key_as_string": "2016-05-31T22:20:00.000Z",
                            "key": 1464733200000,
                            "doc_count": 2266
                        },
                        {
                            "1": {
                                "value": 481
                            },
                            "key_as_string": "2016-05-31T22:30:00.000Z",
                            "key": 1464733800000,
                            "doc_count": 2487
                        },
                        {
                            "1": {
                                "value": 589
                            },
                            "key_as_string": "2016-05-31T22:40:00.000Z",
                            "key": 1464734400000,
                            "doc_count": 3122
                        },
                        {
                            "1": {
                                "value": 664
                            },
                            "key_as_string": "2016-05-31T22:50:00.000Z",
                            "key": 1464735000000,
                            "doc_count": 3541
                        },
                        {
                            "1": {
                                "value": 856
                            },
                            "key_as_string": "2016-05-31T23:00:00.000Z",
                            "key": 1464735600000,
                            "doc_count": 4510
                        },
                        {
                            "1": {
                                "value": 795
                            },
                            "key_as_string": "2016-05-31T23:10:00.000Z",
                            "key": 1464736200000,
                            "doc_count": 4696
                        },
                        {
                            "1": {
                                "value": 818
                            },
                            "key_as_string": "2016-05-31T23:20:00.000Z",
                            "key": 1464736800000,
                            "doc_count": 5306
                        },
                        {
                            "1": {
                                "value": 914
                            },
                            "key_as_string": "2016-05-31T23:30:00.000Z",
                            "key": 1464737400000,
                            "doc_count": 5535
                        },
                        {
                            "1": {
                                "value": 1053
                            },
                            "key_as_string": "2016-05-31T23:40:00.000Z",
                            "key": 1464738000000,
                            "doc_count": 5905
                        },
                        {
                            "1": {
                                "value": 1011
                            },
                            "key_as_string": "2016-05-31T23:50:00.000Z",
                            "key": 1464738600000,
                            "doc_count": 5936
                        },
                        {
                            "1": {
                                "value": 805
                            },
                            "key_as_string": "2016-06-01T00:00:00.000Z",
                            "key": 1464739200000,
                            "doc_count": 2314
                        },
                        {
                            "1": {
                                "value": 1001
                            },
                            "key_as_string": "2016-06-01T00:10:00.000Z",
                            "key": 1464739800000,
                            "doc_count": 3962
                        },
                        {
                            "1": {
                                "value": 934
                            },
                            "key_as_string": "2016-06-01T00:20:00.000Z",
                            "key": 1464740400000,
                            "doc_count": 2542
                        },
                        {
                            "1": {
                                "value": 942
                            },
                            "key_as_string": "2016-06-01T00:30:00.000Z",
                            "key": 1464741000000,
                            "doc_count": 2712
                        },
                        {
                            "1": {
                                "value": 895
                            },
                            "key_as_string": "2016-06-01T00:40:00.000Z",
                            "key": 1464741600000,
                            "doc_count": 2736
                        },
                        {
                            "1": {
                                "value": 883
                            },
                            "key_as_string": "2016-06-01T00:50:00.000Z",
                            "key": 1464742200000,
                            "doc_count": 2617
                        },
                        {
                            "1": {
                                "value": 1126
                            },
                            "key_as_string": "2016-06-01T01:00:00.000Z",
                            "key": 1464742800000,
                            "doc_count": 7494
                        },
                        {
                            "1": {
                                "value": 1025
                            },
                            "key_as_string": "2016-06-01T01:10:00.000Z",
                            "key": 1464743400000,
                            "doc_count": 7173
                        },
                        {
                            "1": {
                                "value": 1082
                            },
                            "key_as_string": "2016-06-01T01:20:00.000Z",
                            "key": 1464744000000,
                            "doc_count": 7228
                        },
                        {
                            "1": {
                                "value": 965
                            },
                            "key_as_string": "2016-06-01T01:30:00.000Z",
                            "key": 1464744600000,
                            "doc_count": 6902
                        },
                        {
                            "1": {
                                "value": 1016
                            },
                            "key_as_string": "2016-06-01T01:40:00.000Z",
                            "key": 1464745200000,
                            "doc_count": 6638
                        },
                        {
                            "1": {
                                "value": 1019
                            },
                            "key_as_string": "2016-06-01T01:50:00.000Z",
                            "key": 1464745800000,
                            "doc_count": 6723
                        },
                        {
                            "1": {
                                "value": 966
                            },
                            "key_as_string": "2016-06-01T02:00:00.000Z",
                            "key": 1464746400000,
                            "doc_count": 6626
                        },
                        {
                            "1": {
                                "value": 986
                            },
                            "key_as_string": "2016-06-01T02:10:00.000Z",
                            "key": 1464747000000,
                            "doc_count": 6215
                        },
                        {
                            "1": {
                                "value": 969
                            },
                            "key_as_string": "2016-06-01T02:20:00.000Z",
                            "key": 1464747600000,
                            "doc_count": 6151
                        },
                        {
                            "1": {
                                "value": 859
                            },
                            "key_as_string": "2016-06-01T02:30:00.000Z",
                            "key": 1464748200000,
                            "doc_count": 5696
                        },
                        {
                            "1": {
                                "value": 883
                            },
                            "key_as_string": "2016-06-01T02:40:00.000Z",
                            "key": 1464748800000,
                            "doc_count": 5481
                        },
                        {
                            "1": {
                                "value": 876
                            },
                            "key_as_string": "2016-06-01T02:50:00.000Z",
                            "key": 1464749400000,
                            "doc_count": 5853
                        },
                        {
                            "1": {
                                "value": 871
                            },
                            "key_as_string": "2016-06-01T03:00:00.000Z",
                            "key": 1464750000000,
                            "doc_count": 5461
                        },
                        {
                            "1": {
                                "value": 761
                            },
                            "key_as_string": "2016-06-01T03:10:00.000Z",
                            "key": 1464750600000,
                            "doc_count": 5206
                        },
                        {
                            "1": {
                                "value": 695
                            },
                            "key_as_string": "2016-06-01T03:20:00.000Z",
                            "key": 1464751200000,
                            "doc_count": 4915
                        },
                        {
                            "1": {
                                "value": 706
                            },
                            "key_as_string": "2016-06-01T03:30:00.000Z",
                            "key": 1464751800000,
                            "doc_count": 4133
                        },
                        {
                            "1": {
                                "value": 761
                            },
                            "key_as_string": "2016-06-01T03:40:00.000Z",
                            "key": 1464752400000,
                            "doc_count": 4451
                        },
                        {
                            "1": {
                                "value": 678
                            },
                            "key_as_string": "2016-06-01T03:50:00.000Z",
                            "key": 1464753000000,
                            "doc_count": 4282
                        },
                        {
                            "1": {
                                "value": 646
                            },
                            "key_as_string": "2016-06-01T04:00:00.000Z",
                            "key": 1464753600000,
                            "doc_count": 4404
                        },
                        {
                            "1": {
                                "value": 641
                            },
                            "key_as_string": "2016-06-01T04:10:00.000Z",
                            "key": 1464754200000,
                            "doc_count": 4120
                        },
                        {
                            "1": {
                                "value": 712
                            },
                            "key_as_string": "2016-06-01T04:20:00.000Z",
                            "key": 1464754800000,
                            "doc_count": 4265
                        },
                        {
                            "1": {
                                "value": 687
                            },
                            "key_as_string": "2016-06-01T04:30:00.000Z",
                            "key": 1464755400000,
                            "doc_count": 4149
                        },
                        {
                            "1": {
                                "value": 634
                            },
                            "key_as_string": "2016-06-01T04:40:00.000Z",
                            "key": 1464756000000,
                            "doc_count": 3871
                        },
                        {
                            "1": {
                                "value": 608
                            },
                            "key_as_string": "2016-06-01T04:50:00.000Z",
                            "key": 1464756600000,
                            "doc_count": 3899
                        },
                        {
                            "1": {
                                "value": 633
                            },
                            "key_as_string": "2016-06-01T05:00:00.000Z",
                            "key": 1464757200000,
                            "doc_count": 3972
                        },
                        {
                            "1": {
                                "value": 572
                            },
                            "key_as_string": "2016-06-01T05:10:00.000Z",
                            "key": 1464757800000,
                            "doc_count": 3630
                        },
                        {
                            "1": {
                                "value": 607
                            },
                            "key_as_string": "2016-06-01T05:20:00.000Z",
                            "key": 1464758400000,
                            "doc_count": 3752
                        },
                        {
                            "1": {
                                "value": 652
                            },
                            "key_as_string": "2016-06-01T05:30:00.000Z",
                            "key": 1464759000000,
                            "doc_count": 4083
                        },
                        {
                            "1": {
                                "value": 607
                            },
                            "key_as_string": "2016-06-01T05:40:00.000Z",
                            "key": 1464759600000,
                            "doc_count": 3650
                        },
                        {
                            "1": {
                                "value": 614
                            },
                            "key_as_string": "2016-06-01T05:50:00.000Z",
                            "key": 1464760200000,
                            "doc_count": 3640
                        },
                        {
                            "1": {
                                "value": 642
                            },
                            "key_as_string": "2016-06-01T06:00:00.000Z",
                            "key": 1464760800000,
                            "doc_count": 3501
                        },
                        {
                            "1": {
                                "value": 606
                            },
                            "key_as_string": "2016-06-01T06:10:00.000Z",
                            "key": 1464761400000,
                            "doc_count": 3374
                        },
                        {
                            "1": {
                                "value": 572
                            },
                            "key_as_string": "2016-06-01T06:20:00.000Z",
                            "key": 1464762000000,
                            "doc_count": 3074
                        },
                        {
                            "1": {
                                "value": 600
                            },
                            "key_as_string": "2016-06-01T06:30:00.000Z",
                            "key": 1464762600000,
                            "doc_count": 3391
                        },
                        {
                            "1": {
                                "value": 573
                            },
                            "key_as_string": "2016-06-01T06:40:00.000Z",
                            "key": 1464763200000,
                            "doc_count": 3228
                        },
                        {
                            "1": {
                                "value": 555
                            },
                            "key_as_string": "2016-06-01T06:50:00.000Z",
                            "key": 1464763800000,
                            "doc_count": 3040
                        },
                        {
                            "1": {
                                "value": 451
                            },
                            "key_as_string": "2016-06-01T07:00:00.000Z",
                            "key": 1464764400000,
                            "doc_count": 1202
                        },
                        {
                            "1": {
                                "value": 418
                            },
                            "key_as_string": "2016-06-01T07:10:00.000Z",
                            "key": 1464765000000,
                            "doc_count": 1069
                        },
                        {
                            "1": {
                                "value": 462
                            },
                            "key_as_string": "2016-06-01T07:20:00.000Z",
                            "key": 1464765600000,
                            "doc_count": 1120
                        },
                        {
                            "1": {
                                "value": 444
                            },
                            "key_as_string": "2016-06-01T07:30:00.000Z",
                            "key": 1464766200000,
                            "doc_count": 1185
                        },
                        {
                            "1": {
                                "value": 399
                            },
                            "key_as_string": "2016-06-01T07:40:00.000Z",
                            "key": 1464766800000,
                            "doc_count": 999
                        },
                        {
                            "1": {
                                "value": 399
                            },
                            "key_as_string": "2016-06-01T07:50:00.000Z",
                            "key": 1464767400000,
                            "doc_count": 1005
                        },
                        {
                            "1": {
                                "value": 544
                            },
                            "key_as_string": "2016-06-01T08:00:00.000Z",
                            "key": 1464768000000,
                            "doc_count": 3107
                        },
                        {
                            "1": {
                                "value": 538
                            },
                            "key_as_string": "2016-06-01T08:10:00.000Z",
                            "key": 1464768600000,
                            "doc_count": 3091
                        },
                        {
                            "1": {
                                "value": 530
                            },
                            "key_as_string": "2016-06-01T08:20:00.000Z",
                            "key": 1464769200000,
                            "doc_count": 3026
                        },
                        {
                            "1": {
                                "value": 532
                            },
                            "key_as_string": "2016-06-01T08:30:00.000Z",
                            "key": 1464769800000,
                            "doc_count": 2725
                        },
                        {
                            "1": {
                                "value": 506
                            },
                            "key_as_string": "2016-06-01T08:40:00.000Z",
                            "key": 1464770400000,
                            "doc_count": 2710
                        },
                        {
                            "1": {
                                "value": 480
                            },
                            "key_as_string": "2016-06-01T08:50:00.000Z",
                            "key": 1464771000000,
                            "doc_count": 2595
                        },
                        {
                            "1": {
                                "value": 522
                            },
                            "key_as_string": "2016-06-01T09:00:00.000Z",
                            "key": 1464771600000,
                            "doc_count": 2876
                        },
                        {
                            "1": {
                                "value": 479
                            },
                            "key_as_string": "2016-06-01T09:10:00.000Z",
                            "key": 1464772200000,
                            "doc_count": 2740
                        },
                        {
                            "1": {
                                "value": 492
                            },
                            "key_as_string": "2016-06-01T09:20:00.000Z",
                            "key": 1464772800000,
                            "doc_count": 3007
                        },
                        {
                            "1": {
                                "value": 495
                            },
                            "key_as_string": "2016-06-01T09:30:00.000Z",
                            "key": 1464773400000,
                            "doc_count": 2538
                        },
                        {
                            "1": {
                                "value": 444
                            },
                            "key_as_string": "2016-06-01T09:40:00.000Z",
                            "key": 1464774000000,
                            "doc_count": 2639
                        },
                        {
                            "1": {
                                "value": 455
                            },
                            "key_as_string": "2016-06-01T09:50:00.000Z",
                            "key": 1464774600000,
                            "doc_count": 2656
                        },
                        {
                            "1": {
                                "value": 444
                            },
                            "key_as_string": "2016-06-01T10:00:00.000Z",
                            "key": 1464775200000,
                            "doc_count": 2631
                        },
                        {
                            "1": {
                                "value": 431
                            },
                            "key_as_string": "2016-06-01T10:10:00.000Z",
                            "key": 1464775800000,
                            "doc_count": 2699
                        },
                        {
                            "1": {
                                "value": 415
                            },
                            "key_as_string": "2016-06-01T10:20:00.000Z",
                            "key": 1464776400000,
                            "doc_count": 2282
                        },
                        {
                            "1": {
                                "value": 392
                            },
                            "key_as_string": "2016-06-01T10:30:00.000Z",
                            "key": 1464777000000,
                            "doc_count": 2300
                        },
                        {
                            "1": {
                                "value": 416
                            },
                            "key_as_string": "2016-06-01T10:40:00.000Z",
                            "key": 1464777600000,
                            "doc_count": 2386
                        },
                        {
                            "1": {
                                "value": 361
                            },
                            "key_as_string": "2016-06-01T10:50:00.000Z",
                            "key": 1464778200000,
                            "doc_count": 2058
                        },
                        {
                            "1": {
                                "value": 388
                            },
                            "key_as_string": "2016-06-01T11:00:00.000Z",
                            "key": 1464778800000,
                            "doc_count": 2169
                        },
                        {
                            "1": {
                                "value": 361
                            },
                            "key_as_string": "2016-06-01T11:10:00.000Z",
                            "key": 1464779400000,
                            "doc_count": 2019
                        },
                        {
                            "1": {
                                "value": 330
                            },
                            "key_as_string": "2016-06-01T11:20:00.000Z",
                            "key": 1464780000000,
                            "doc_count": 2023
                        },
                        {
                            "1": {
                                "value": 307
                            },
                            "key_as_string": "2016-06-01T11:30:00.000Z",
                            "key": 1464780600000,
                            "doc_count": 1555
                        },
                        {
                            "1": {
                                "value": 304
                            },
                            "key_as_string": "2016-06-01T11:40:00.000Z",
                            "key": 1464781200000,
                            "doc_count": 1651
                        },
                        {
                            "1": {
                                "value": 335
                            },
                            "key_as_string": "2016-06-01T11:50:00.000Z",
                            "key": 1464781800000,
                            "doc_count": 1796
                        },
                        {
                            "1": {
                                "value": 322
                            },
                            "key_as_string": "2016-06-01T12:00:00.000Z",
                            "key": 1464782400000,
                            "doc_count": 1624
                        },
                        {
                            "1": {
                                "value": 316
                            },
                            "key_as_string": "2016-06-01T12:10:00.000Z",
                            "key": 1464783000000,
                            "doc_count": 1678
                        },
                        {
                            "1": {
                                "value": 313
                            },
                            "key_as_string": "2016-06-01T12:20:00.000Z",
                            "key": 1464783600000,
                            "doc_count": 1715
                        },
                        {
                            "1": {
                                "value": 270
                            },
                            "key_as_string": "2016-06-01T12:30:00.000Z",
                            "key": 1464784200000,
                            "doc_count": 1303
                        },
                        {
                            "1": {
                                "value": 291
                            },
                            "key_as_string": "2016-06-01T12:40:00.000Z",
                            "key": 1464784800000,
                            "doc_count": 1367
                        },
                        {
                            "1": {
                                "value": 252
                            },
                            "key_as_string": "2016-06-01T12:50:00.000Z",
                            "key": 1464785400000,
                            "doc_count": 1180
                        },
                        {
                            "1": {
                                "value": 252
                            },
                            "key_as_string": "2016-06-01T13:00:00.000Z",
                            "key": 1464786000000,
                            "doc_count": 1316
                        },
                        {
                            "1": {
                                "value": 237
                            },
                            "key_as_string": "2016-06-01T13:10:00.000Z",
                            "key": 1464786600000,
                            "doc_count": 1326
                        },
                        {
                            "1": {
                                "value": 239
                            },
                            "key_as_string": "2016-06-01T13:20:00.000Z",
                            "key": 1464787200000,
                            "doc_count": 1132
                        },
                        {
                            "1": {
                                "value": 222
                            },
                            "key_as_string": "2016-06-01T13:30:00.000Z",
                            "key": 1464787800000,
                            "doc_count": 1060
                        },
                        {
                            "1": {
                                "value": 204
                            },
                            "key_as_string": "2016-06-01T13:40:00.000Z",
                            "key": 1464788400000,
                            "doc_count": 1052
                        },
                        {
                            "1": {
                                "value": 179
                            },
                            "key_as_string": "2016-06-01T13:50:00.000Z",
                            "key": 1464789000000,
                            "doc_count": 863
                        },
                        {
                            "1": {
                                "value": 157
                            },
                            "key_as_string": "2016-06-01T14:00:00.000Z",
                            "key": 1464789600000,
                            "doc_count": 830
                        },
                        {
                            "1": {
                                "value": 147
                            },
                            "key_as_string": "2016-06-01T14:10:00.000Z",
                            "key": 1464790200000,
                            "doc_count": 767
                        },
                        {
                            "1": {
                                "value": 149
                            },
                            "key_as_string": "2016-06-01T14:20:00.000Z",
                            "key": 1464790800000,
                            "doc_count": 700
                        },
                        {
                            "1": {
                                "value": 151
                            },
                            "key_as_string": "2016-06-01T14:30:00.000Z",
                            "key": 1464791400000,
                            "doc_count": 618
                        },
                        {
                            "1": {
                                "value": 114
                            },
                            "key_as_string": "2016-06-01T14:40:00.000Z",
                            "key": 1464792000000,
                            "doc_count": 620
                        },
                        {
                            "1": {
                                "value": 128
                            },
                            "key_as_string": "2016-06-01T14:50:00.000Z",
                            "key": 1464792600000,
                            "doc_count": 596
                        },
                        {
                            "1": {
                                "value": 110
                            },
                            "key_as_string": "2016-06-01T15:00:00.000Z",
                            "key": 1464793200000,
                            "doc_count": 508
                        },
                        {
                            "1": {
                                "value": 87
                            },
                            "key_as_string": "2016-06-01T15:10:00.000Z",
                            "key": 1464793800000,
                            "doc_count": 395
                        },
                        {
                            "1": {
                                "value": 71
                            },
                            "key_as_string": "2016-06-01T15:20:00.000Z",
                            "key": 1464794400000,
                            "doc_count": 437
                        },
                        {
                            "1": {
                                "value": 83
                            },
                            "key_as_string": "2016-06-01T15:30:00.000Z",
                            "key": 1464795000000,
                            "doc_count": 388
                        },
                        {
                            "1": {
                                "value": 67
                            },
                            "key_as_string": "2016-06-01T15:40:00.000Z",
                            "key": 1464795600000,
                            "doc_count": 321
                        },
                        {
                            "1": {
                                "value": 53
                            },
                            "key_as_string": "2016-06-01T15:50:00.000Z",
                            "key": 1464796200000,
                            "doc_count": 262
                        }
                    ]
                }
            }
        }
    ]
}

**Comment by tonyC2016** [comment]
is it the timezone on the grafana machine or es machine cause the problem?

**Comment by torkelo** [comment]
Grafana issues queries in UTC (the range filter), and visualizes time depending on your Grafana options (local or UTC timezone). Elasticsearch returns and stores dates as UTC, so your ES server timezone should not matter. Maybe an issue with how you store the data? maybe you do not send UTC dates in your ES documents? 

If you have questions please use the mailing list or other support options:
http://grafana.org/support/

**Comment by tonyC2016** [comment]
@torkelo  how grafana send the request str，its parser the request str on grafana or elasticsearch?,
with the debugger i got the query Time Range is correct ,but the respone query time is worong ,i check the es machine and grafana machine ,the time all is right

**Comment by torkelo** [comment]
if the response query time is wrong, not sure, better ask in elasticsearch mailinglist / forum. 

check that the time in your documents are right.

**Comment by tonyC2016** [comment]
@torkelo  i store data by logstash ,and it create type by UTC time,and my data on two types.exp:06-01'sdata on type 06-01 and 05-31,and i wanna Unique Count the id on grafana's singlestat, and i set the time is yesterday,and how i set the Group by time interval num ,i set 1d and 2d,get differnet result ,i dont unstand how it works?

**Comment by torkelo** [comment]
sorry, not a logstash export, better ask in logash/elasticsearch forum with experts for these tools. If the Grafana query is correct it is likely an issue with your ES data.

**Comment by tonyC2016** [comment]
i think its maybe not es or logstash‘s problem, i wanna konw ,i use grafana 's singlestat, show the distinct result for 24h's data,  i just dont wanna anything else ,like date_histogram,how can i remove it ,or how i set the Group by time interval ,or can grafana support it ?

**Comment by torkelo** [comment]
Single stat panel only works with time series so you need date histogram , just Dat histogram interval to 1y to only return 1 data point

**Comment by tonyC2016** [comment]
@torkelo ,3q

**Comment by torkelo** [comment]
3q?

**Comment by tonyC2016** [comment]
@torkelo  just say thank you ,its chinese english, :)

**Comment by torkelo** [comment]
oh, thanks: )
