### ISSUE TITLE
Tempo datasource:enable query with grafana variable

### ISSUE THREAD

**Issue by nicolastakashi** [grafana/grafana#52629]
**What happened**:

Similar to this issue #44422 but now for Tempo Datasource, would be nice be able to use Grafana variables on Tempo DataSource to search services.

**What you expected to happen**:

Be able to search services on Tempo using Variables.

**How to reproduce it (as minimally and precisely as possible)**:

Just install Tempo DataSource and tries to create a variable and use on the service dropdown

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by joey-grafana** [comment]
Hello, that support was added in [9.0.4](https://github.com/grafana/grafana/pull/52381) 👍 

PS: thank you for the suggestion all the same!
