### ISSUE TITLE
[Bug] Singlestat value has wrong color

### ISSUE THREAD

**Issue by jk2K** [grafana/grafana#5262]
- Grafana Version 3.0.4
- datasource is InfluxDB
- OS is Ubuntu 14.04.4 LTS
- now system uptime is `36.9 week`(22277568 seconds), expected result: < 0.2 become red, 0.2-0.6 become orange, > 0.6 become green

![image](https://cloud.githubusercontent.com/assets/4025839/15746520/8727f500-2909-11e6-95bd-8fe0ead9cc27.png)
![image](https://cloud.githubusercontent.com/assets/4025839/15746532/9119de48-2909-11e6-8c99-e74c8a41aae0.png)
same thresholds setting, different result

**Comment by torkelo** [comment]
the thresholds are evaluated against the raw value (seconds it looks like in your case). so you need to specify the threshold in seconds

**Comment by jk2K** [comment]
Why do I get different color with same thresholds setting?  (default 50,80,  my settings is 50,80)

**Comment by torkelo** [comment]
Default is not 50,80 that is just example,, /place older text
