### ISSUE TITLE
SecretInput component is not exported from @grafana/ui/components

### ISSUE THREAD

**Issue by EccentricVamp** [grafana/grafana#52630]
**What happened**:
I'm developing some datasource plugins that need passwords and credentials. Most of the examples I could find use `LegacyForms.SecretFormField`. From the name alone, I can tell that this is not a good solution.

While browsing the Grafana UI [Storybook](https://developers.grafana.com/ui/latest/index.html?path=/story/forms-secretinput--basic) I found the `SecretInput` component which does exactly what I need. I checked the commit history for the `SecretInput` component and found it had been added 5 months ago. I pulled down the latest version of the `@grafana/ui` package and checked the components. It was there. However, when I tried to import it into my plugin, I started getting build errors.

```
  Using Node.js v18.6.0
  Using @grafana/toolkit v9.0.4
✔ Preparing
⠴ Compiling...  TS2305: Module '"@grafana/ui"' has no exported member 'SecretInput'.
      1 | import React, { PureComponent } from 'react';
      2 | import { DataSourceJsonData, DataSourcePluginOptionsEditorProps, onUpdateDatasourceOption } from '@grafana/data';
    > 3 | import { Input, InlineFieldRow, InlineField, SecretInput } from '@grafana/ui';
        |                                              ^^^^^^^^^^^
      4 | import { HistorianSecureJsonData } from './types';
      5 |
      6 | type Props = DataSourcePluginOptionsEditorProps<DataSourceJsonData, HistorianSecureJsonData>;
✖ Build failed
```

After looking at the compiled `index.d.ts` for `@grafana/ui/components` I was not able to find any export for the SecretInput component. My knowledge about Webpack and TypeScript build processes is limited, so I stopped digging and came here to open an issue.

**What you expected to happen**:
If `SecretInput` was meant for public use, then it should be included in the exports of the `@grafana/ui` package

If `SecretInput` was only meant to be used internally by Grafana, then I would not expect it to be included with examples in the Storybook.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new npm package
2. `npm install @grafana/toolkit @grafana/ui`
3. `npx grafana-toolkit plugin:create`
4. Reference `{ SecretInput } from "@grafana/ui"`
5. `npx grafana-tookit plugin:build`

**Anything else we need to know?**:
Npm complained about some peer dependency conflicts when I was updating to `@grafana/ui` 9.0.4, but I think I resolved those, so I don't think it's relevant.

I'm developing this plugin for internal use by the company that I work for. I got their permission to open-source it. Here's the source: https://github.com/EccentricVamp/historian-datasource

**Environment**:
- OS: Windows Server 2022
- IDE: Visual Studio Code
- npm: 8.13.2
- Node.js: 18.6.0
- @grafana/tookit: 9.0.4
- @grafana/ui: 9.0.4

**Comment by zoltanbedi** [comment]
Thanks for opening this detailed issue @EccentricVamp, you are right we don't export that component which was something we missed but there was a pr recently that fixed it and the SecretInput component will be exported properly. 
https://github.com/grafana/grafana/pull/51891/files#diff-c2d9b1cb1f1e8981c885fe372658c3715d1b0eb79dafa606c9aa9c0f7253db11

This will be released in 9.1.0
