### ISSUE TITLE
Problems after upgrading InfluxDB to 0.13 (from 0.11)

### ISSUE THREAD

**Issue by willemdh** [grafana/grafana#5264]
Hello,

I'm experiencing problems with Grafana after upgrading InfluxDB from v0.11.1 to v0.13.0.

So before I upgrade I'm taking a VMware snapshot. (thank god this exists). At that moment I'm at Grafana version 3.0.0-beta21459801392 on a CentOS 7 server.

I'm following this upgrde guide to upgrade InfluxDB => https://docs.influxdata.com/influxdb/v0.13/administration/upgrading/#upgrading-from-0-10-or-0-11-to-0-13

After the InfluxDB upgrade, the influxDB service starts fine. I can log in to the InfluxDB web interface and I'm seeing data coming in.

But when I go to Grafana, i'm seeing lots of red exclamation marks and empty graphs.

There seems to be an issue with template varaibles:

![image](https://cloud.githubusercontent.com/assets/6462991/15753362/e7b55b9a-28f2-11e6-89b9-f2698d04b6a1.png)

And the Graph Inspectors:

![image](https://cloud.githubusercontent.com/assets/6462991/15753411/3771e4aa-28f3-11e6-9da2-b56dfc9703c1.png)

![image](https://cloud.githubusercontent.com/assets/6462991/15753417/416c3b4a-28f3-11e6-8831-406a70afa2a2.png)

![image](https://cloud.githubusercontent.com/assets/6462991/15753452/66ddb8a4-28f3-11e6-864e-3958429c8819.png)

I tried updating to the latest version of Grafana 3.0.4-1464167696 with:

    sudo yum install https://grafanarel.s3.amazonaws.com/builds/grafana-3.0.4-1464167696.x86_64.rpm

But this resulted in same issues. The recently viewed dashboards are gone and replaced by this error on the home page:

![image](https://cloud.githubusercontent.com/assets/6462991/15753537/ce05a000-28f3-11e6-8478-59c9d107fcc9.png)

Thanks for any advice how to make my Grafana work with latest version of InfluxDB.

(Restoring to snapshot now :D )

Willem

**Comment by torkelo** [comment]
InfluxDB 0.13 should work fine with latest Grafana. 

did you restart grafana-server after upgrade? 

The unknown panel type error is suggestion that the upgrade of the new version was not done correctly, very strange.

**Comment by willemdh** [comment]
@torkelo You were correct. I was assuming the service restarted automatically after upgrade.
