### ISSUE TITLE
Grafana: make all backend plugin platform files executabe

### ISSUE THREAD

**Issue by tolzhabayev** [grafana/grafana#52640]
**Why?**
Currently we only mark some architecture types of backend plugins as executable. https://github.com/grafana/grafana/blob/main/pkg/plugins/manager/installer/installer.go#L633-L635

**Desired state**
We should mark all the backend plugin architecture types as executable - e.g. `_linux_arm64` and `_darwin_arm64`. Also check if `_windows_amd64` also needs to be marked as executable. 

**Additionally**
If possible add the permissions check to [plugin-validator](https://github.com/grafana/plugin-validator) `plugincheck2` and, if necessary, adjust the [report parsing in the pipeline](https://github.com/grafana/community-pipeline/blob/main/pkg/lib/report.go#L148)

**Backport**
- Yes, latest `8.x` and `9.x` version

**Comment by wbrowne** [comment]
Ideally this code wouldn't exist and we no longer rely of Grafana altering file permissions. But to support plugins who haven't been packaged properly, it makes sense to have it here and improve it 😞 

Maybe we can add logic to the plugin validator to catch this during the review stages.
