### ISSUE TITLE
Sign in not working in explore page for anonymous users

### ISSUE THREAD

**Issue by vtorosyan** [grafana/grafana#52655]
**What happened**:

When anonymous auth and `views_can_edit` are enabled, Sign In button in the sidebar does nothing and the page is just reloaded.

**What you expected to happen**:

When clicking on Sign In, it should redirect to the login page.

**How to reproduce it (as minimally and precisely as possible)**:

1. Run `docker run -e GF_AUTH_ANONYMOUS_ENABLED=true -e GF_USERS_VIEWERS_CAN_EDIT=true -p 3000:3000 grafana/grafana:main`
1. Visit `http://localhost:3000/explore`
1. Click Sign In link from the bottom left menu

**Anything else we need to know?**:

- Grafana version: 9.0.4

**Comment by Elfo404** [comment]
@grafana/backend-platform seems like `forceLogin` is not really checked for every route, or more precisely is only checked for routes in `pkg/api/index.go` that uses `reqAuth` or  `reqSignedIn`.

for instance, the same thing happens for every app plugin. could you check this?

**Comment by L-M-K-B** [comment]
@grafana/backend-platform 
Is this issue on you TODO column yet or do you have any plans yet?
