### ISSUE TITLE
[bug] Prometheus datasource not showing query editor

### ISSUE THREAD

**Issue by andmarios** [grafana/grafana#5265]
Hello, thanks for Grafana!

I have an issue with prometheus datasources.

System info:
- Grafana v3.0.4 (2016-05-25)
- Prometheus Datasource
- Centos 7.2
- Chrome 51.0.2704.36 beta

Problem: the query editor for prometheus sources stays like this, no matter what I do:
![grafana-issue](https://cloud.githubusercontent.com/assets/1239679/15762894/ff4244b8-2928-11e6-96fe-cbb37fbbbd30.png)

Inside your minified `query_ctrl.js`, there is an entry `step_input:c.target.step`. If i replace this with a fixed number (or empty string), the query editor shows normally.

I do not know js but maybe the issue is around here:
https://github.com/grafana/grafana/blob/master/public/app/plugins/datasource/prometheus/query_ctrl.ts#L71

It seems that in your js, instead of an empty `step_input` variable, you get the `endTime.target.step` variable assigned to it, which is undefined.

**Comment by torkelo** [comment]
Can you show you panek. Json
?

**Comment by torkelo** [comment]
Panel JSON, dam mobile autocomplete

**Comment by andmarios** [comment]
Oops! I am terribly sorry.

The problem came from me. I tried to install the Percona app, which suggests to apply a patch to grafana for better graphs. This broke the prometheus datasource query control.

Sorry again for this bug report and thank you for your patience!
