### ISSUE TITLE
[Question] Creating Panels to Perform Actions

### ISSUE THREAD

**Issue by bmundt** [grafana/grafana#5266]
My use for grafana will be monitoring and control of a network. Monitoring will be simple enough with the different graphical panels available. However, there doesn't seem to be an easy way to perform actions from grafana. I was wondering what the best way to go about tackling this would be. I have found one possible way, where I create a text panel, and add a button in html and have it send a post request upon clicking the button using simple jquery.

**Comment by torkelo** [comment]
please do not use github for questions, use the mailing list or other support channels:
http://grafana.org/support/
