### ISSUE TITLE
Alerting: Create silence preview wrongly evaluates some conditions

### ISSUE THREAD

**Issue by piotrp** [grafana/grafana#52676]
I found two issues with _Create silence form_:

1. When I go to _Create silence_ screen and click on _Add matcher_ the preview of matching alert instances disappears, making it difficult to change them because I need to remember exactly what I wanted to input (UX issue).

2. When _Label_ contains label name that doesn't exist within current alert instances, _Condition_ is set to "!=", and _Value is set, all alerts disappear from preview even though this condition is valid - silence is saved successfully and alert is silenced (bug)

My alert:
![obraz](https://user-images.githubusercontent.com/1409807/180598721-dca03514-47b0-4278-805f-8f7a113d7634.png)

Valid condition, preview is hiden even though matchers should match my alarm instance:
![obraz](https://user-images.githubusercontent.com/1409807/180598769-34b884ea-f224-4a82-a989-086db912193b.png)

After saving silence is properly applied:
![obraz](https://user-images.githubusercontent.com/1409807/180598887-447bb9ed-fdc9-4c68-adc3-4011099a8433.png)

Grafana 9.0.4

**Comment by cun-dp** [comment]
The same bug occurs for case insensitive regex matchers:

**Example matcher:**
alertname=~^(?i:(myalert)).*

**Result:**
Silence preview in the edit silence form does not show the MYALERT to be silenced. The "Affected alerts" on the /alerting/silences page does show MYALERT to match the silence.

**Expected result:**
The silence preview does show the MYALERT to be silenced.

**Comment by gillesdemey** [comment]
identified as a bug; we currently apply the preview to all grafana managed rule instances instead of the instances from the selected alert manager.
