### ISSUE TITLE
[Question] Network utilisation in percent

### ISSUE THREAD

**Issue by ArturasRa** [grafana/grafana#5267]
Hello,

I'm using grafana with influxdb to collect and visualise data from network switches. I'm collecting data via SNMP and sending it to influxdb. As of now, I'm able to get graph of current bandwidth usage with derivative function. I'm also collecting port speed values(constant value of 1Gbps, 10Gbps etc.) as TAG and also as VALUE. Is this possible to somehow get utilisation of port in percent? How such query should look like?

Let's say I have value of port speed of 10G and my current speed 1.5Gbps, so I want to have 15% value on my graph. Is this possible to do with grafana and influxdb? Thank you.

**Comment by torkelo** [comment]
please do not use github for questions, use the mailing list or other support channels:
http://grafana.org/support/

**Comment by ArturasRa** [comment]
Sorry about that, I thought questions could be asked here too. Anyway, you can delete my question then, will ask it in other source.

Thank you.
