### ISSUE TITLE
Alert rules created via an API are not showing up under the dashboard

### ISSUE THREAD

**Issue by svetur** [grafana/grafana#52674]
Created a new alert rule via /api/v1/provisioning/alert-rules referencing an existing dashboard uid. Alert shows up under alerting/list but not under the dashboard alert.

if i delete manually created one alert, after that for a few seconds api created ones show up briefly then disappear ( Firefox, Safari)

Reproduce: create an alert via POST host//api/v1/provisioning/alert-rules  referencing existing dashboard and panel.
  "__dashboardUid__": "****",
        "__panelId__": "***",

Go to the dashboard, alert - new alert won't be there

v9.0.2

**Comment by svetur** [comment]
[](url
![api_alerts](https://user-images.githubusercontent.com/109830552/180577756-584874ed-3778-4b8c-ad5a-851d89b74aed.png)
![after](https://user-images.githubusercontent.com/109830552/180577763-9282462c-ff70-4c83-ac1a-98eb7d246666.png)
)

**Comment by JohnnyQQQQ** [comment]
Those fields are not supported yet. We will add eventually.
