### ISSUE TITLE
Histogram Panel Hide in area wont work

### ISSUE THREAD

**Issue by gannaramu** [grafana/grafana#52671]
**What happened**: Histogram panel Hide series functionality not working.

**What you expected to happen**: it should hide/unhide when selecting a series from legend like it does for time series panel

**How to reproduce it (as minimally and precisely as possible)**:  any time series panel when switched to histogram panel looses the ability to hide the series.

**Anything else we need to know?**:

**Environment**: Grafana running on k8s
- Grafana version: v8.5.5 (d32ae1890)
- Data source type & version: MySQL ( not the issue)
- OS Grafana is installed on: K8s
- User OS & Browser: safari
- Grafana plugins: NA
- Others:

**Comment by codeincarnate** [comment]
Looks like this may have been missed from move from old graph panel. Should be fairly straightforward to add though.

**Comment by mdvictor** [comment]
Hello,

This will be fixed by https://github.com/grafana/grafana/pull/53651
