### ISSUE TITLE
Allow time shift relative to truncated date `now/d`

### ISSUE THREAD

**Issue by leehambley** [grafana/grafana#5268]
**I'm submitting a ...**
- Bug report
- Feature request

**Time shift should be relative to overridden time, not to the current time.**

Please include this information:
- **What Grafana version are you using?** 3.0.4
- **What datasource are you using?** InfluxDB
- **What OS are you running grafana on?** Linux
- **What did you do?** Tried to override time to `now/d` (read, today so far) and time shift it by `1d`
- **What was the expected result?** it would show yesterday midnight (`now-1d/d`) until today midnight (e.g 24 wall clock hours of one calendar day)
- **What happenend instead?** time shift is relative to the *current* (untruncated) time

See thread at the Grafana group for more information.

![0](https://cloud.githubusercontent.com/assets/18952/15771362/759827fe-296a-11e6-9d6e-45769f1cb7f2.png)

    now-1d/d: SELECT sum("value") FROM activity WHERE "activity_name" 
    = 'user.entered-segment-ideal' AND time > 1464645600s and time < now() 
    GROUP BY time(30m)
    (should be time > 1464645600s and time < 1464645600s + 86400s in my opinion)
    now-1w/w: SELECT sum("value") FROM activity WHERE "activity_name" 
    = 'user.entered-segment-ideal' AND time > 1463868000s and time < now() 
    GROUP BY time(3h)
    (should be time > 1463868000s and time < 1463868000s + 604800s in my opinion)

**Comment by leehambley** [comment]
Issue solved, the key is to put the `7d/d` into the time shift field which yields 24h1m beginning at midnight 7 days ago. (similarly for `2d/w` giving one week's data starting 2 days ago, etc, etc)

**Comment by bob454522** [comment]
THANKS so much for following up on this leehambley,  ive been searching and trying for exactly this for over a week now-  (ie to get a panel's graphs to show always show "yesterday's 24 hours" ie the prior 24h, not relative time=(now -24h).

For others,  you can also put this type into **"Time Shift" field: 1d/d-10m**    (ive had to do this to adjust the edges of some graphs)
(and i assume also in relative time, however in my case to get the 24h from yesterday, i only put 1d/d-10m into "Time Shift" , and leave "Relative Time" blanks
