### ISSUE TITLE
[Feature Request] import dashboard from file on startup

### ISSUE THREAD

**Issue by fabxc** [grafana/grafana#5269]
This is in the context that I just want to have Grafana running with pre-defined dashboards rather than letting users create their own. 

If I want to deploy a Grafana instance with a pre-defined set of dashboards I currently have to wait until Grafana is running and then POST the dashboard to the API.

At the example of Kubernetes, this is really inconvenient to do right now. I need a second container doing the API call every time a Grafana pod is scheduled. Or I need to populate a SQLite database that I then copy into my container image. Both solutions are more of a hack.

It would be ideal if I could point to the dashboard JSON files in my Grafana config that will be automatically inserted on startup.

**Comment by XANi** [comment]
There is `[dashboards.json]` section in config that seems to do that.

We use that to sync dashboards to 2 instances and it works reasonably well.

Only thing that is really missing is enabling it to load **per organization** as currently using it causes every org to get them instead of only ones that we need. 

For example we have "public" org that shares some dashboards without auth but we'd rather not have *all* of them as public.

**Comment by skygragon** [comment]
@XANi the [dashboard.json] has its limitation as well, for example: we can't star those dashboards because they are totally readonly in files instead stored in sqlite db. So it would be better if grafana server could auto import those jsons during startup once for all.

**Comment by fabxc** [comment]
I strongly disagree with this. There must be a way to load dashboards from source control and the main feature here is not having a stateful DB under the hood.

**Comment by XANi** [comment]
@fabxc one does not exclude the other.

It could either:

* just keep metadata (starred status etc.) in DB while keeping dashboard config on disk
* periodically (or triggered by inotify/external request) reload databases from drive

**Comment by torkelo** [comment]
>  @fabxc 

what do you disagree with? 

Do you disagree with the feature request title `import dashboard from file on startup`? 

The way I see we likely support file based dashboards is via continuously syncing them from file to db (so they are available in search, api, starring etc). But not editable in UI/api. 

Unrelated to this feature is a new feature coming soon that adds dashboard history & revert (so you can see diffs of dashboard changes, and view dashboard change log, and restore etc)

**Comment by joaquincasares** [comment]
@torkelo Great work on Grafana!

Based on your last comment:

* Having the ability to import dashboards from a file is amazing so far!
* Having the json backed files be editable in Grafana is useful for me to test and play around with settings/changes, without having fear of overwriting simple things like Time Ranges.
    * I am, however, okay with the edits not persisting. If they had the option to persist, that would be even better, but currently I have my json files mounted into my Docker container using a read-only mount point, due to permission issues I haven't looked into deeply.
* While dashboard history and revision control is nice, I would much rather have the ability to edit a json file, especially when doing bulk operations across multiple graphs and multiple dashboards.

I came to this comment by way of #7888, so having a way for JSON-backed files to include actionable alerts would also be highly useful if a Docker setup is being shared across multiple clusters with similar alert thresholds. If you're able to prefer DB-backed alerts, over JSON-backed alerts, that would be a nice way to continue to customize "stock" JSON dashboards/alerts, while also providing "stock" JSON alerts.

Wasn't sure if this the best place to comment, but wanted to ensure you had an idea of the JSON-backed setup I'm currently using for Grafana. Feel free to send me an email if you want a peek at my project, when it's ready to share, to see my current use case. :)

Thanks again for the great work!!

**Comment by lhoss** [comment]
+1 
plz annotate the issue with the `dashboard` label so that this one shows up in a filtered search by that label)

Related: Is there really no dashboard API method to import(create) a dashboard by ID (from the grafana community dashboards) ? 
I couldn't find a methond on http://docs.grafana.org/http_api/dashboard/ , nor an existing issue for such a feature.

**Comment by XANi** [comment]
@lhoss there is, it is first request documented and same web UI uses to save data

Put your dashboard json (one from "view JSON") in "dashboard" key and set "overwrite" key to true

We use that to import ours, as we need a bunch of "same" dashboards with tiny changes between orgs.

You do need to do whole login dance with it tho so in our case grew to ~200 lines of code (load list of orgs, get ID for org name provided in cmdline, do some find/replace in JSON, post a new dashboard

**Comment by bergquist** [comment]
Closed by https://github.com/grafana/grafana/pull/10052
