### ISSUE TITLE
Convert public/app/features/explore/LiveLogs.test.tsx to RTL

### ISSUE THREAD

**Issue by gabor** [grafana/grafana#52712]
convert this test to use the react-testing-library

**Comment by Toledodev** [comment]
Hey @gabor, I checked now and realized that LiveLogs.test is already in RTL format

![Screenshot from 2022-08-25 20-47-03](https://user-images.githubusercontent.com/87545086/186788139-c9fb49d3-edbc-4929-b5d0-3c169904ffe1.png)

**Comment by gabor** [comment]
oh, good catch @Toledodev , i will close the issue in that case. thanks!
