### ISSUE TITLE
Show context not working

### ISSUE THREAD

**Issue by mbastida123** [grafana/grafana#52729]
**What happened**:
When clicking on show context nothing is displayed:
![image](https://user-images.githubusercontent.com/78351485/180786186-00ec5524-5fa1-42d0-85e8-79ebe5a26671.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create a query
Click on any show context.

I attach the query just in case it's the root of the bug:
![image](https://user-images.githubusercontent.com/78351485/180786750-2995a9d6-9471-4bc3-8947-e8c7366beafa.png)

**Anything else we need to know?**:
Could this be related to [svennergr/fix-show-context-missing-labels](https://github.com/grafana/grafana/pull/52458)?
On the 9.0.4 it was marked as bug fix.

**Environment**:
- Grafana version:V9.0.4
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser: Windows 10, Google Chrome
- Grafana plugins:
- Others:

**Comment by gabor** [comment]
hi @mbastida123 , unfortunately there was a problem with the changelog for 9.0.4, the fix at https://github.com/grafana/grafana/pull/52458 did not get into 9.0.4. but it is available in 9.0.5, that has just been released. could you please try with grafana 9.0.5?

**Comment by mbastida123** [comment]
Hi @gabor
Yes, v9.0.5 fixes the issue.

Thanks!
