### ISSUE TITLE
Convert decimal time values

### ISSUE THREAD

**Issue by ogarcia** [grafana/grafana#5272]
With latest version of grafana, a value like `0.001s` not is converted to `1ms`.

Please add support for decimal values transformation cause software like chrony returns its offset in this format.

**Comment by torkelo** [comment]
0.001s ? is that what you have in your TSDB? a string?

**Comment by ogarcia** [comment]
No, the value is `0.001` (a decimal number). I added a `s` to explain that this occur with time values.

The problem is that I have `0.001` in seconds and not is converted to milliseconds.

**Comment by torkelo** [comment]
The unit scaling only works one way, say the 1000 is ms format is turned into 1s,  but just multiply you value by 1000 and change unit to ms
