### ISSUE TITLE
Prometheus: Remove old client

### ISSUE THREAD

**Issue by aocenas** [grafana/grafana#52738]
Recently a [new client was added](https://github.com/grafana/grafana/pull/48477) to the Prometheus plugin to simplify response processing and improve performance and memory consumption. We still did not remove the old client and before we can do that there are a few things:

- [ ] Put the old client behind the feature flag and make new client default
- [ ] Observe if there are any issues
- [ ] Remove old client code totally
- [ ] Remove comparison logic

https://github.com/grafana/grafana/issues/52738#tasklist-block-bcc03f8d-f78b-4640-98b8-0374fe890fdf

**Comment by gtk-grafana** [comment]
@itsmylife Create epic please!

**Comment by bohandley** [comment]
As of the plan put forward today put forward by Kyle,

- v9.2: New client flag is there, should be feature complete, we encourage people to use it
- v9.3: New client is default, flag to use old. Old client deprecated, no changes
- v9.4: Delete old client (Feb)

https://raintank-corp.slack.com/archives/C03FZ9T50R1/p1665073148493249

We are moving this out of Q3 and potentially Q1 of 2023

**Comment by bohandley** [comment]
Closing this to reorganize into this issue: https://github.com/grafana/grafana/issues/52738
