### ISSUE TITLE
wrong table aliases headers 

### ISSUE THREAD

**Issue by markbaas** [grafana/grafana#5273]
When setting filters somehow the column aliases for all subsequent metrics are exactly the same.

This happens for opentsdb 2.2 with grafana >= 3.0.x

Problem is due to incorrect determination of index in `mapMetricsToTargets` function in opentsdb plugin.

![pasted image at 2016_06_02 03_26 pm](https://cloud.githubusercontent.com/assets/1153495/15788943/d3ab85de-2997-11e6-850f-42d63781122b.png)

Columns are all `up proxyname`

**Comment by markbaas** [comment]
PR fixes this problem ^^^

**Comment by torkelo** [comment]
is this not related to this https://github.com/grafana/grafana/issues/1876?

**Comment by markbaas** [comment]
Looks like it.
