### ISSUE TITLE
[Bug] PNG rendering graph show "plugin error"

### ISSUE THREAD

**Issue by vitorboschi** [grafana/grafana#5274]
Please include this information:
- What Grafana version are you using? Nightly built 03/06/2016 13:55:51
- What datasource are you using? OpenTSDB
- What OS are you running grafana on? CentOS
- What did you do? Exported image from a panel
- What was the expected result? The panel

- What happenend instead? 

The panel with an error: 

> Plugin Error: null is not an object (evaluating 'b.$root.colors')

* If I remove the /render/ part from url, I get a interactive panel with the same error
* If I refresh the windows (F5), the error does not appear
* Although there's the error popup, I couldn't spot any problem on the resulting graph after closing it
* That same panel renders without any problem on the dashboard
* It looks like the problem affects every graph panel, in any dashboard

![image](https://cloud.githubusercontent.com/assets/71193/15788901/06e94b54-29a0-11e6-836e-5266fa95c5fc.png)

If it matters, the url used was http://server-name:9080/render/dashboard-solo/db/status-servidores?panelId=3&fullscreen&theme=light&width=900&height=300

**Comment by torkelo** [comment]
strange, unable to replicate it here :(

**Comment by vitorboschi** [comment]
problem seems to come from https://github.com/grafana/grafana/blob/master/public/app/plugins/panel/graph/module.ts#L118

**Comment by torkelo** [comment]
Yes but why do you get it? Can't replicate it :(
Try a new build?

**Comment by torkelo** [comment]
can you replicate this?

**Comment by vitorboschi** [comment]
yes, I can replicate it easily here. I'll see if I can find anything else about this problem.

**Comment by vitorboschi** [comment]
more info on how to replicate this problem:
1. go to any graph and select share ->  Direct link rendered image
2. The panel should load fine. Now, edit the current url and remove  `from`, `to` and `org` parameters and submit
3. the panel should refresh, but now displaying the error popup
