### ISSUE TITLE
Editing raw SQL not possible for PostgreSQL data source in version 8.5.9 and 9.0.4

### ISSUE THREAD

**Issue by christian-schlichtherle** [grafana/grafana#52754]
I'm trying to connect to PostgreSQL 14.1. The connection works and my datasource gets added, but when I explore or build a panel using this datasource I cannot edit raw SQL statements. Whenever I click on "Edit SQL", the query editor panel collapses, but there is no panel to input my SQL.

This bug applies to Grafana 9.0.4 and Grafana 8.5.9 at least.

After downgrading to Grafana 7.5.16, everything works as expected.

I have been trying with Safari 15.6 and Chrome 103.0.5060.134 on macOS 12.5 - it made no difference.

**Comment by zuchka** [comment]
Thanks for creating this issue, @christian-schlichtherle 

I'm having trouble reproducing this. Here is a postgres query builder running on v9.1.0-pre (9df9b1b5c3):

![CleanShot 2022-07-25 at 12 33 19](https://user-images.githubusercontent.com/37156449/180885526-2d1dcf0a-95a7-4f1d-8871-566be85e4a0c.gif)

**Comment by christian-schlichtherle** [comment]
Nevermind, now it works - thanks for the video and sorry!

**Comment by zuchka** [comment]
no worries glad you're unblocked!
