### ISSUE TITLE
`TypeError: Cannot read properties of undefined...` error with different graph types 

### ISSUE THREAD

**Issue by SharifiFaranak** [grafana/grafana#52753]
**What happened**:
We see this error, `TypeError: Cannot read properties of undefined (reading 'replace')` when running a query with the `Google Cloud Monitoring` datasource on a graph with `Stat` type (as well as some other types as well). 

**What you expected to happen**:
We expect the graph to load the data, and not throw the error. Currently the default graph (`Timeseries`) is able to load the data fine (after upgrading to Grafana `9.0.4`)
![Screen Shot 2022-07-25 at 1 34 06 PM](https://user-images.githubusercontent.com/35040509/180839268-91999b96-b5cb-4908-b97f-8359c34681cc.png)

**How to reproduce it (as minimally and precisely as possible)**:
Run a query such as the following:
![Screen Shot 2022-07-25 at 1 31 26 PM](https://user-images.githubusercontent.com/35040509/180839176-45181f66-a7a9-4a29-bab8-c145785737f6.png)

**Anything else we need to know?**:
We are not sure if it is a bug with Grafana or the google cloud monitoring Datasource.

**Environment**:
- Grafana version: `9.0.4`
- Data source type & version: `google cloud monitoring`. Not sure about the version.
- OS Grafana is installed on: linux, gke
- User OS & Browser: macos, chrome
- Grafana plugins:
- Others:

**Comment by andresmgot** [comment]
Hi @SharifiFaranak,

Does the issue happen for you only for SLO queries or also for Metrics queries?

**Comment by andresmgot** [comment]
I am able to reproduce this, only for SLO queries, the issue seems easy to fix so I'll send a quick PR.
