### ISSUE TITLE
Footer: Grafana Version / Commit is an empty link

### ISSUE THREAD

**Issue by zuchka** [grafana/grafana#52773]
**What happened**:
Wherever Grafana generates a footer, it adds the Grafana version and commit to the list of links:

https://github.com/grafana/grafana/blob/238d761450738cdef822589f321500879fa49b32/public/app/core/components/Footer/Footer.tsx#L48

The link is empty, which I've always found a little disappointing. I was thinking we could reference the commit like this:

```
links.push({ text: `v${buildInfo.version} (${buildInfo.commit})`, url: `https://github.com/grafana/grafana/search?q=${buildInfo.commit}&type=commits` });
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- Grafana version:
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by JoaoSilvaGrafana** [comment]
Hey @zuchka ! I think this could be a good idea, but I just checked play and if I copy the commit that is there into that search there is no commit found 🤔 just wondering if this is more common than not and if it could cause issues... Do you normally use these commits and do you find that sometimes you can't find them?

**Comment by zuchka** [comment]
Hi @JoaoSilvaGrafana!

Yep. You're right. That didn't work. Maybe my link idea doesn't work with the cloud / enterprise commits?

In any case, this all started because I often want to copy/paste the commit number from the HELP nav-bar, but it's not focusable:

![CleanShot 2022-07-26 at 09 29 52](https://user-images.githubusercontent.com/37156449/181096046-26f270a9-46aa-47df-a30d-2597efee9318.gif)


guessing that's a11y issue and I could make another issue for it. That is what I really want to fix. I just noticed this as I was researching.

It would still be nice if the link went somewhere, I feel. Even if the location isn't dynamic, like just to the latest docs or something?

**Comment by JoaoSilvaGrafana** [comment]
@zuchka Yeah maybe if it pointed at something like https://grafana.com/docs/grafana/latest/release-notes/ or even to the specific release notes version that could be good??

Thanks for raising the other issue about the `subTitle` not being highlightable as well!
