### ISSUE TITLE
Alerting : button to edit an alert rule is not easy to find

### ISSUE THREAD

**Issue by armandgrillet** [grafana/grafana#52778]
I have a folder with one alert rule, in `/alerting/list` I see this:
![PS 2022-07-26 à 09 36 05](https://user-images.githubusercontent.com/2117580/180950294-665e91a7-db37-4fc5-b405-d1a29a818486.png)

The pencil icon on the right does not edit the alert rule but the folder, as indicated after hovering the pencil icon for a while. To edit the alert rule, I need to expand the alert rule once more and then I can see the edit button for the alert rule:

![PS 2022-07-26 à 09 38 22](https://user-images.githubusercontent.com/2117580/180950618-0725f819-3eeb-4c8f-b0ea-b58fede36607.png)

I believe the edit button for the alert rule should already be available in the first screenshot, next to the name of the alert rule:
![PS 2022-07-26 à 09 38 22](https://user-images.githubusercontent.com/2117580/180950958-f873a047-95e4-49e4-a453-b289a9ec20e0.png)

That way, expanding the alert rule a second time will in many cases not be necessary.

**Comment by gillesdemey** [comment]
I agree that we could move some actions to the collapsed list item as I find it rather annoying you need to open up the detail view for viewing / editing 👍

**Comment by gillesdemey** [comment]
@KlingerMatheus that's great work! I wouldn't worry too much about the responsiveness of the action buttons – rule authoring (editing, creating, etc) is mostly done on desktops and takes up too much screen real estate for that to ever be feasible on mobile devices.

As far as actionable advice goes; try hiding the action buttons on smaller screens.

We're also planning on redesigning the list view in the future that will be more mobile friendly :)
