### ISSUE TITLE
would love utf-8 emoji support

### ISSUE THREAD

**Issue by si74** [grafana/grafana#5277]
- **I'm submitting a ...**
- [ ] Bug report
- [X ] Feature request
- [ ] Question / Support request: **Please do not** open a github issue. [Support Options](http://grafana.org/support/)

Please include this information:
- What Grafana version are you using? 2.7 
- What datasource are you using? prometheus
- What OS are you running grafana on? 
- What did you do?
- What was the expected result?
- What happenend instead?

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
where?

**Comment by si74** [comment]
@torkelo Tried to add emoji tags to a test grafana dashboard and unfortunately had a problem preventing me from accessing said dashboard again.

**Comment by eMerzh** [comment]
@torkelo , the problem still exists, and the issue is that i can't access the said dashboard to remove it

**Comment by sparr** [comment]
I find that I am able to add and remove emoji in the title of a row. Is there a specific place you can or can't add or remove them?

**Comment by bergquist** [comment]
@si74 @eMerzh I think its related to your database. What database and Grafana version are you using?

Ex http://play.grafana.org/dashboard/db/emoji?panelId=1&fullscreen&edit&orgId=1&tab=value%20mappings

The lack of color is troublesome. Perhaps we should look at https://github.com/eosrei/emojione-color-font

**Comment by eMerzh** [comment]
@bergquist , mine use  Grafana v4.6.2 (commit: 8db5f08)  with sqlite3

and the dashboard is only '🚲' no other text

**Comment by schmkr** [comment]
Also ran into this problem. Using sqlite3 as database, I had created a dashboard with a single emoji as its name. Trying to access it was not possible, so deleting it was also not possible.

Workaround for me was to create another dashboard and, with the Developer Tools open, delete this new dashboard. Then select the DELETE request from the network tab and select "Copy as Curl". With the request copied, look up the id of the dashboard with the emoji and replace the id of the deleted dashboard in the curl request. Excecute the request et voila, the dashboard with the emoji is now also gone.

**Comment by pkolyvas** [comment]
@schmkks for your note. The issue of a single emoji as a dashboard name seems to be resolved as of 8.x. If you're still seeing this issue would you be willing to open a bug report.
