### ISSUE TITLE
Stat panel does not apply "No Value" mapping

### ISSUE THREAD

**Issue by tomasmota** [grafana/grafana#52789]
**What happened**:
This is the raw graph that I am working with:

![image](https://user-images.githubusercontent.com/25929015/180967811-adb72b2a-f50d-48ef-9d4b-18a712ceeef6.png)

I want the top line, that stopped receiving new datapoints, to be mapped to zero. As a graph panel, I was able to do this using the "No Value" field: 
![image](https://user-images.githubusercontent.com/25929015/180967999-d01d475d-f732-45aa-a0cb-02ebfd9b73b8.png)

This resulted in the following graph:
![image](https://user-images.githubusercontent.com/25929015/180977725-62d8dba9-0551-4330-a503-434230f864f8.png)

Now I can use the fact that the green line is 0 to create my threshold.

The thing is I want this to be a stat panel, which shows SRVS00308 as red and SRVS00309 as green.

When I convert this to a stat panel, having the No Value set to 0 aswell, it does not seem to be applied in the same way, as can be seen here, where the graph just ends instead of dropping to 0:

![image](https://user-images.githubusercontent.com/25929015/180978168-c576f95d-3a1c-4b4c-b932-987757cb65e2.png)

This means I am not able to set it as red. There was no change besides setting it to a stat panel.

**What you expected to happen**:
I would have expected that the graph on the left in the last picture would drop to 0, such that I can take the last value in my stat panel and use the threshold on that.

**Environment**:
- Grafana version: 9.0.4
- Data source type & version: prometheus

**Comment by joshhunt** [comment]
Reproduction dashboard https://play.grafana.org/d/Qgc1MMF4z/52789-stat-panel-no-no-value?orgId=1

**Comment by xkilian** [comment]
It seems that no value is not honored in the stat panel. So that it does not display an alternate value or change colour based on thresholds. This leads to the last value being displayed instead of null and stat panel staying green, which has already led to operational errors being done. This is not a minor problem.

**Comment by xkilian** [comment]
This issue is still present in 9.2.6.

**Comment by joelmfonseca** [comment]
The issue is still present in 9.3.2. Please consider it. As xkilian shared, it can lead to operational consequences if value is misinterpreted.

Many thanks for your help.
