### ISSUE TITLE
helm chart: grafana-6.32.5 app version: 9.0.3 grafana-sc-dashboard fails to start

### ISSUE THREAD

**Issue by ceastman-r7** [grafana/grafana#52814]
**What happened**:
grafana-sc-dashboard fails to start with the following error:
Traceback (most recent call last):
  File "/app/sidecar.py", line 11, in <module>
    from helpers import REQ_RETRY_TOTAL, REQ_RETRY_CONNECT, REQ_RETRY_READ, REQ_RETRY_BACKOFF_FACTOR
  File "/app/helpers.py", line 8, in <module>
    from logger import get_logger
  File "/app/logger.py", line 69, in <module>
    root_logger.setLevel(level.upper() if isinstance(level, str) else level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 1452, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/lib/python3.10/logging/__init__.py", line 198, in _checkLevel
    raise ValueError("Unknown level: %r" % level)
ValueError: Unknown level: ''

**What you expected to happen**:
grafana-sc-dashboard to start without error

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
same exact values.yaml works with helm chart: 6.30.3 grafana 8.5.3

**Environment**:
- Grafana version: 9.0.3
- helm chart version: 6.32.5
- Data source type & version:
- OS Grafana is installed on:
- User OS & Browser:
- Grafana plugins:
- Others:

**Comment by tleopold** [comment]
Hi

Is this still an issue?  Are you seeing this behaviour on the latest version of Grafana?

Thanks

**Comment by tleopold** [comment]
No response so closing.
