### ISSUE TITLE
Fire alert when going green ?

### ISSUE THREAD

**Issue by dureiken** [grafana/grafana#52825]
**What happened**:

I have an alert which works well for firing, but I don’t understand why it fires its action again when going green ?

https://community.grafana.com/t/fire-alert-when-going-green/68505?u=dureiken

**What you expected to happen**:

No fire alert when going back green

**How to reproduce it (as minimally and precisely as possible)**:
Just add an alert and record its behaviour

thanks

**Comment by ashharrison90** [comment]
hi @dureiken 👋 

this is expected behaviour. an alert notifies (with the new state) when it goes back to a normal state. if you only want to do something when the alert notifies the first time, i think you'd need to look at the alert state. 
 
hope that makes sense!
