### ISSUE TITLE
Influxdb Error Undefined

### ISSUE THREAD

**Issue by SaaRaj** [grafana/grafana#5283]
![screenshot from 2016-04-01 13-27-06](https://cloud.githubusercontent.com/assets/19766241/15808690/0304cd7e-2b44-11e6-9706-5cde55f510e7.png)
* **I'm submitting a ...**

- [x] Question / Support request: 

Please include this information:
- What Grafana version are you using?

I am using Grafana version 3.0.4 the latest 
- What datasource are you using?
I am using the influxdb data source version 0.13
- What OS are you running grafana on?
I am running it on Ubuntu
- What did you do?

I am trying to add influx data source to grafana and I am unable to add it. I am new to Grafana so I would really appreciate if someone could help me with adding the data source. I have also added a screenshot of the error and I am unable to do anything about it.

![screenshot from 2016-06-05 17-14-18](https://cloud.githubusercontent.com/assets/19766241/15808662/d7943414-2b42-11e6-977b-7376b025652e.png)

- What was the expected result?
- What happenend instead?

**IMPORTANT** If it realates to metric data viz:
- An image or text representation of your metric query
- The raw query and response for the network request (check this in chrome dev tools network tab, here you can see metric requests and other request, please include the request body and request response)

**Comment by torkelo** [comment]
try the default api port, `8086`

**Comment by SaaRaj** [comment]
Thank you so much !
It did work

**Comment by stevenroose** [comment]
@torkelo Because you can see what his error was, doesn't solve the issue that "Unknown error InfluxDB Error: undefined" is an unhelpful error.
