### ISSUE TITLE
Unified alerting InfluxDB Alias By $measurement does not work.

### ISSUE THREAD

**Issue by justinsmalley** [grafana/grafana#52844]
**What happened**:
I have an influxQL query that I want to alert on. The structure is such that I want each measurement to be a different alert instance with the measurement name as the label value. When put "$m" or "$measurement" into the "Alias By" field, (as defined [here](https://grafana.com/docs/grafana/latest/datasources/influxdb/), the measurement name does not show up where expected.
![image](https://user-images.githubusercontent.com/99200643/181117519-1645dad2-a4b8-4dfb-9633-8cd05e10c561.png)

**What you expected to happen**:
I expect one instance of the alert to be created for each influxdb measurement. Below is a trend showing the exact same query in a time series panel working as expected.
![image](https://user-images.githubusercontent.com/99200643/181119506-4aa43626-c6a4-475f-b43d-0837c9b1ef69.png)

A very similar alert I was able to successfully create here but used $tag_xxxID as the alias instead of $measurement. In this case it worked and it resulted in 8 different instances of the alert. I would expect the same behaviour when using the $measurement alias.
![image](https://user-images.githubusercontent.com/99200643/181118786-52c9f44f-b97e-4fa3-92b7-bfcc275ad6ef.png)
![image](https://user-images.githubusercontent.com/99200643/181118933-8b96f475-c6ef-442d-ade1-12926dd365b5.png)

**How to reproduce it (as minimally and precisely as possible)**:

1. Have access to an influxdb with multiple measurements with the same field keys. 
2. The following generic query will work once you have that data source. 
`SELECT mean("value") FROM /.*/ WHERE $timeFilter GROUP BY time($__interval) fill(null)`
3. add $measurement to the alias by
4. Check alias in stats panel

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.4
- Data source type & version: InfluxDB 1.8
- OS Grafana is installed on: Alpine Docker
- User OS & Browser: MacOS + Chrome
- Grafana plugins:
- Others:

**Comment by aocenas** [comment]
@grafana/alerting-squad I left it only in the Alerting project and removed it from Metric squad project. It seems more likely to be alerting issue as it seems to work as expected in a dashboard panel so I assume the data we send from influx is correct and how that is interpreted needs to be changed in alerting. If that's not the case just ping the metric squad again.

**Comment by grobinson-grafana** [comment]
Hi! 👋 

I'm not sure I know how to reproduce the issue. I have a measurement in InfluxDB called `cpu` with two tags: `host` and `region`. When I use `$measurement` in the alias the measurement is shown as expected? 

<img width="1284" alt="Screenshot 2022-07-28 at 16 29 50" src="https://user-images.githubusercontent.com/85952834/181577487-dd8abc17-4e11-4af4-8260-23d87acfdafa.png">

**Comment by justinsmalley** [comment]
Our InfluxDB data has a slightly different data orientation than your test system. Under our methodology, instead of a measurement called "cpu" we would have a measurement for each server called "server1", "server2", etc. and within it there would be a field or tag key called "cpu". In your test query, you can simulate this by removing the group by "host", "region" (the test query won't really make sense with the data set, but it enough to show the issue). Thanks!

**Comment by yuri-tceretian** [comment]
I can confirm the bug. Apparently, there are differences in how InfluxDb is queried:
- panel and Explore tab query the data source by sending a GET request directly via Grafana reverse proxy `http://localhost:3000/api/datasources/proxy/8/query?db=site&q=SELECT max("value") FROM /.*/ WHERE time >= now() - 6h and time <= now() GROUP BY time(20s) fill(0)&epoch=ms` 
- alert rule engine sends it via expression engine which uses the backend plugin https://github.com/grafana/grafana/blob/3d68023606cf25103bc66c27a3f4d02eb199e2f7/pkg/tsdb/influxdb/influxdb.go#L83-L142
the plugin returns the data frames in the format that we see in the UI (i.e bug). Rule engine provides the query model in exactly the same format as UI part of the plugin generates
```
{
  "alias": "$measurement",
  "hide": false,
  "intervalMs": 1000,
  "maxDataPoints": 43200,
  "query": "SELECT max(\"value\") FROM /.*/ WHERE $timeFilter GROUP BY time($__interval) fill(0)",
  "rawQuery": true,
  "refId": "A",
  "resultFormat": "time_series"
}
```

Therefore, I can conclude that the bug is on the plugin side (backend part of it).
