### ISSUE TITLE
Canvas: Multi-selection of elements in tree view bug

### ISSUE THREAD

**Issue by nmarrs** [grafana/grafana#52847]
When selecting multiple elements the tree view list currently does not indicate that multiple elements are selected.

Given this is an issue that impacts a simple flat list of elements (not just nested frames) it probably makes sense to address as part of our beta

See #52701 for context

https://user-images.githubusercontent.com/22381771/181130126-19bea92c-9964-4764-a6bc-d255ef179a4c.mov

**Comment by adela-almasan** [comment]
Fixed by https://github.com/grafana/grafana/issues/52847
