### ISSUE TITLE
Is there any way that i can show single stat in a webpage??

### ISSUE THREAD

**Issue by raj990** [grafana/grafana#5284]
I'm using grafana 2.6 with the datasource graphite. I want to show a panel in a webpage. Can i do that??

**Comment by torkelo** [comment]
you can use the "Embed"  feature in the panel menu, will give you html for iframing a single panel. 

If the web page is public you grafana server needs to be accessible by anonymous users which mean all metrics from you graphite data source could potentially be accessed
