### ISSUE TITLE
[Bug][Alerting][Silence]fail to create alert when visit grafana via api keys

### ISSUE THREAD

**Issue by litiliu** [grafana/grafana#52853]
**What happened**:
when i want to create an alerting silence in grafana via api keys, the server return 500.

<img width="645" alt="Screen Shot 2022-07-27 at 15 45 02" src="https://user-images.githubusercontent.com/38579068/181191263-11f066c4-45dd-49fa-818b-ea4e4afbb84e.png">
this is the request body
<img width="573" alt="Screen Shot 2022-07-27 at 15 45 31" src="https://user-images.githubusercontent.com/38579068/181191327-1d086ce6-2771-470f-8737-4cdd95d04a82.png">

this is the server log:
logger=context userId=0 orgId=1 uname= t=2022-07-27T07:33:15.36+0000 lvl=eror msg="Request error" error="runtime error: invalid memory address or nil pointer dereference" stack="/usr/local/go/src/runtime/panic.go:221 (0x44df86)\n/usr/local/go/src/runtime/signal_unix.go:735 (0x44df56)\n/opt/drone/gomodcache/github.com/prometheus/alertmanager@v0.23.1-0.20211116083607-e2a10119aaf7/api/v2/compat.go:87 (0x1747229)\n/drone/src/pkg/services/ngalert/notifier/silences.go:78 (0x1757be7)\n/drone/src/pkg/services/ngalert/api/api_alertmanager.go:137 (0x1c63a83)\n/drone/src/pkg/services/ngalert/api/forked_am.go:57 (0x1c6e9c2)\n/drone/src/pkg/services/ngalert/api/generated_base_api_alertmanager.go:57 (0x1c6f5ba)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/services/ngalert/metrics/ngalert.go:286 (0x1736a76)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0xe2d69a)\n/drone/src/pkg/web/macaron.go:155 (0xe2d68c)\n/usr/local/go/src/net/http/server.go:2047 (0x6d2dce)\n/drone/src/pkg/middleware/csp.go:22 (0x172c0f2)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0xe2d69a)\n/drone/src/pkg/web/macaron.go:155 (0xe2d68c)\n/usr/local/go/src/net/http/server.go:2047 (0x6d2dce)\n/drone/src/pkg/web/render.go:44 (0xe28446)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0xe2d69a)\n/drone/src/pkg/web/macaron.go:155 (0xe2d68c)\n/usr/local/go/src/net/http/server.go:2047 (0x6d2dce)\n/drone/src/pkg/middleware/csrf.go:21 (0x172c50f)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0x172f4ca)\n/drone/src/pkg/middleware/recovery.go:168 (0x172f4c1)\n/drone/src/pkg/web/context.go:32 (0xe255fb)\n/drone/src/pkg/web/inject.go:139 (0xe264f4)\n/drone/src/pkg/web/inject.go:117 (0xe2641c)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0x172d1c4)\n/drone/src/pkg/middleware/logger.go:33 (0x172d1b0)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0x17301af)\n/drone/src/pkg/middleware/request_metrics.go:60 (0x173019e)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/context.go:62 (0x1731939)\n/drone/src/pkg/middleware/request_tracing.go:60 (0x1731928)\n/usr/local/go/src/reflect/value.go:556 (0x4df784)\n/usr/local/go/src/reflect/value.go:339 (0x4ded04)\n/drone/src/pkg/web/inject.go:159 (0xe26786)\n/drone/src/pkg/web/inject.go:119 (0xe263d4)\n/drone/src/pkg/web/context.go:67 (0xe2570b)\n/drone/src/pkg/web/router.go:156 (0xe29cbd)\n/drone/src/pkg/web/router.go:223 (0xe2a951)\n/drone/src/pkg/web/macaron.go:189 (0xe27d90)\n/usr/local/go/src/net/http/server.go:2879 (0x6d633a)\n/usr/local/go/src/net/http/server.go:1930 (0x6d1ea7)\n/usr/local/go/src/runtime/asm_amd64.s:1581 (0x46bf00)\n"

logger=context userId=0 orgId=1 uname= t=2022-07-27T07:33:15.36+0000 lvl=eror msg="Request Completed" method=POST path=/api/alertmanager/grafana/api/v2/silences status=500 remote_addr=172.17.242.128 time_ms=103 duration=103.042831ms size=123 referer="https://wapuip.webex.com/grafana/alerting/silence/new?alertmanager=grafana"

seems a param named "createdBy" is required, but not submitted when using api keys to visit grafana.

**What you expected to happen**:
successfuly create alerting silence when visiting grafana via api keys
**How to reproduce it (as minimally and precisely as possible)**:
visit  grafana  via api-keys , then 
````
curl --location --request POST '/grafana/api/alertmanager/grafana/api/v2/silences' \
--header 'Content-Type: application/json' \
--data-raw '{"startsAt":"2022-07-27T07:01:01.783Z","endsAt":"2022-07-27T09:01:01.783Z","comment":"created 2022-07-27 15:01","matchers":[{"name":"t","value":"t","isEqual":true,"isRegex":false}]}'
````
**Anything else we need to know?**:
i'm using grafana8
**Environment**:
- Grafana version:  v4.8.7
- Data source type & version:  prometheus
- OS Grafana is installed on: centos docker 
- User OS & Browser:  macos 12.4  + chrome Version 103.0.5060.134 (Official Build) (arm64)
- Grafana plugins:
- Others:

**Comment by ashharrison90** [comment]
hi @litiliu 👋 

> i'm using grafana8
Grafana version: v4.8.7

can you confirm which version of grafana you're using? 😅 

thanks!

**Comment by grobinson-grafana** [comment]
I think @litiliu is on 8.4.7, but I'm going to wait for confirmation first before investigating the issue further.

**Comment by grobinson-grafana** [comment]
Hi! 👋 Thanks for opening the issue, however I am going to close it as we haven't heard back! Please feel free to re-open it if the issue is still present on the latest version of Grafana 8.5.x or 9.x.

**Comment by antwacky** [comment]
I have the same issue, with authentication disabled, I try to create an alert silence, and I get the popup error:

Error: silence failed validation: validation failure list: validation failure list: createdBy in body is required

Grafana version, 8.5.27.

**Comment by antwacky** [comment]
@ashharrison90 do I need to raise a new issue...?
