### ISSUE TITLE
Annotations: Migrate Prometheus datasource to use dashboardUID in `addTracingHeaders`

### ISSUE THREAD

**Issue by lpskdl** [grafana/grafana#52863]
As part of the dashboardUID migration related to Annotations. The prometheus datasource is using `dashboardID` in addTracingHeaders and should need to migrate using `dashboardUID`

This issue is dependent with #52459 as a new property is added under `AnnotationEvent`

**Comment by aocenas** [comment]
@lpskdl I am not sure if this is just mistakenly added to our project or is meant that we should work on it. Going to remove the project but let us know if we should add it somewhere in our plan or not.

**Comment by lpskdl** [comment]
Hi @aocenas, Apologies for directly adding the metric squad in the issue. I was about to write it in the slack group channel about this topic. 

We have an [epic](https://github.com/grafana/grafana/issues/48850) to migrate from using `dashboardID` to `dashboardUID` in the frontend side to support the new search feature. While working with the annotations to use dashboardUID, we've noticed that the prometheus datasource is also using dashboardId `in `addTracingHeaders`. As per our team, this area is handled by the metrics squad. 

Apologies as I directly assigned metrics squad to the ticket. Let me know if that is incorrect or I need to move it to other team.

**Comment by aocenas** [comment]
Ah ok so I guess it depends. Even if we are "owning" that part of code, honestly it's no problem if you create a PR, especially if you want this faster or already somebody is working on this in other parts of Grafana and knows what to change where. If it isn't rushing then we can add it to our project and work on it later.

**Comment by lpskdl** [comment]
Aha! Nice! I will create a PR for that, but I might need some help how to replicate the scenario of reaching that specific case(`addTracingHeaders`). Will reach out to the channel metrics for some help :) Thanks a lot @aocenas
