### ISSUE TITLE
Alerting/Slack: notifications duplicating subject/title in channel message

### ISSUE THREAD

**Issue by guilherme-ton-afterverse** [grafana/grafana#52881]
hello my title is duplicated i upgraded to use the latest version of grafana with render image to have support in slack, but even using the unified alert my title keeps duplicating

**Environment**:
- Grafana version: 9.0.5
- OS Grafana is installed on: Linux 
- Grafana plugins: Grafana plugin render

<img width="501" alt="Captura de Tela 2022-07-27 às 09 33 36" src="https://user-images.githubusercontent.com/91225432/181257770-d48dfb5b-2458-4528-b3cb-090f72b8d5c2.png">

**Comment by grobinson-grafana** [comment]
Hi! 👋 

We had to [add a text field](https://github.com/grafana/grafana/pull/52391) to the Slack message to fix issue https://github.com/grafana/grafana/issues/42768. This is expected for now until we move to [Block Kit](https://api.slack.com/block-kit). However, we don't have an ETA for this as we would like to continue to be compatible with upstream Alertmanager, and there is an open issue https://github.com/prometheus/alertmanager/issues/2217 for adding Block Kit to Alertmanager.

**Comment by lfkdev** [comment]
Sad to see this is expected behaviour, it looks terrible in an professional environment. Looking forward to the Block Kit change!

**Comment by tomelliff** [comment]
Is the issue mentioned in #42768 still valid? Running the following shows notifications to me and also appears in unread:

```
curl -X POST -H 'Content-type: application/json' --data '{"blocks":[{"type": "section", "text": {"type": "mrkdwn", "text": "blocks *bold* text"}}]}' https://hooks.slack.com/services/TOKEN/HERE
```

I think that issue is saying that without there being a text field at the top level this message would be hidden by Slack notifications and in the unread list etc but it doesn't behave particularly different to when I run this:

```
curl -X POST -H 'Content-type: application/json' --data '{"text": "top level *bold* text", "blocks":[{"type": "section", "text": {"type": "mrkdwn", "text": "blocks *bold* text"}}]}' https://hooks.slack.com/services/TOKEN/HERE
```

The [documentation](https://api.slack.com/messaging/composing/layouts#limitations) still implies that this shouldn't be working yet but it might be out of date?

> At launch, messages built with blocks will not be supported in “All unreads”, “Threads”, “Pinned”, “Starred”, and “Shared Messages” views in Slack. Instead, users will see:
> ```
> This message can't be shown in full here. View message
> ```
> We’re working actively to support these views as soon as possible.

**Comment by grobinson-grafana** [comment]
Hi @tomelliff! That's interesting, I will test it next week and see if it has changed. Thanks!

**Comment by grobinson-grafana** [comment]
Hi @tomelliff! I will test this next week and see if it has changed. Thanks!

**Comment by grobinson-grafana** [comment]
Hi @tomelliff! Your example is using the BlockKit API which isn't used in Grafana at present. You'll need to use attachments to reproduce the issue.

**Comment by bpatton00** [comment]
is there an active workaround for this yet?  We finally made the leap to the new alerting and have noticed this as well, unable to bypass it so far.
