### ISSUE TITLE
InfluxDB template variables escaping

### ISSUE THREAD

**Issue by vasya4k** [grafana/grafana#5288]
- [X ] Bug report
- Grafana version Version 3.0.4 (commit: v3.0.4)
- Datasource InfluxDB Admin UI: v0.13.0 Server: v0.13.0
-OS Ubuntu 14.04.4 LTS

I have configured a template variable to use in a query called $interface the value of which I get by running another query to InfluxDB (SHOW TAG VALUES WITH KEY = "instance" WHERE snmp_host='aaaa-bbb-r1.xxxx.com'). I am using multi-value and include-all options in the templating section, note I have tried without same results. The value of the variable meant to be inserted in the the metric query untouched. Instead, grafana adds escape characters like this "instance" ='xe-1\/0\/5' which are not a part of the values stored in the InfluxDB should be  "instance" ='xe-1/0/5' . As a result my query becomes invalid. Here is the query:  "SELECT 8 * derivative(mean("ifHCOutOctets"),1s) AS "ifHCOutOctets" FROM "ifHCOutOctets" WHERE "instance" ='xe-1\/0\/5' AND "snmp_host"='aaaa-bbb-r1.xxxx.com' AND time > now() - 3h GROUP BY time(60s) fill(null);" Response: "message": "error parsing query: found \\/, expected identifier, string, number, bool at line 1, char 113""

**Comment by torkelo** [comment]
if you have multi value the tag filter in your query needs to use the regex syntax `instance =~ /^$yourvariable$/`  if you use raw query all variables will default to regex escaping to suport this scenario. If you use the query editor regex escaping will only be used if you  use the regex operator
