### ISSUE TITLE
[Cloudwatch] Cannot create template variable query based on `CloudWatchSynthetics` namespace

### ISSUE THREAD

**Issue by jleloup** [grafana/grafana#52892]
**What happened**:

I am working with AWS Synthetics Canaries which happens to output metrics in AWS Cloudwatch, in the `CloudWatchSynthetics` namespace.

While I am able to check for metrics in this namespace through the Explore UI, I am not able to get this namespace in template variable queries.

Example: a template variable to fetch dimension values out of the `SuccessPercent` metric from the `CloudWatchSynthetics` namespace.

In this screenshot I am able to fetch this metric through Explore UI:

![Explore UI](https://user-images.githubusercontent.com/20790125/181286805-2e02053e-81b1-4573-b322-6260c94d6480.png)

Then if I try to create a template variable based on a Cloudwatch query, this namespace is not available:

![Template variable](https://user-images.githubusercontent.com/20790125/181287025-9122fdd0-ecb5-4b8d-b230-ccd3fa5c9d15.png)

**What you expected to happen**:

AWS Cloudwatch namespace `CloudWatchSynthetics` shoulmd be available in template variable queries.

**How to reproduce it (as minimally and precisely as possible)**:

* create a Grafana datasource type AWS Cloudwatch
* have an AWS Synthetics canary running in order to make sure that synthethics metrics are available in the account
* create a new dashboard
* create a new template variable: type Query, any kind of Query type, then ask for namespace `CloudWatchSynthetics`

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: type Cloudwatch
- OS Grafana is installed on: EKS
- User OS & Browser: Macos & Chrome
- Grafana plugins:
- Others:

**Comment by iwysiu** [comment]
Hi @jleloup ! Thanks for reporting this issue. From investigating, I think this is actually a combination of two issues, the first is that the template variable editor should allow custom namespaces and metrics, and the second is that `CloudWatchSynthetics` should be included in the metrics map in [metrics.go](https://github.com/grafana/grafana/blob/main/pkg/tsdb/cloudwatch/metrics.go)

**Comment by iwysiu** [comment]
The fix for this will go out in the 9.0.7 release.

**Comment by jleloup** [comment]
Thanks for your feedback. Waiting for the 9.0.7 then :)
