### ISSUE TITLE
API endpoint (/api/alertmanager/grafana/config/api/v1/alerts) seems to be hanging waiting on database locks

### ISSUE THREAD

**Issue by mbentley** [grafana/grafana#52896]
**What happened**:

In Grafana `9.0.5`, I noticed that in the `Notification polices` and `Contact points` screens that operations were hanging after saving, deleting, etc.  It seems that the API endpoint that data is being sent to (`/api/alertmanager/grafana/config/api/v1/alerts`) is waiting on a lock in MySQL.  This does not happen in Grafana `9.0.4` if I revert to the `9.0.4` Docker image.

In the grafana logs, I see a message about this:

```
logger=ngalert t=2022-07-27T11:18:25.479508003-04:00 level=warn msg="failed to delete old am configs" org=1 err="Error 1205: Lock wait timeout exceeded; try restarting transaction"
logger=context traceID=00000000000000000000000000000000 userId=1 orgId=1 uname=admin t=2022-07-27T11:18:25.558920176-04:00 level=info msg="Request Completed" method=POST path=/api/alertmanager/grafana/config/api/v1/alerts status=202 remote_addr=192.168.0.144 time_ms=50252 duration=50.252506789s size=59 referer=https://grafana.casa.mbentley.net/alerting/routes traceID=00000000000000000000000000000000
```

Once it errors out, it returns a success message as you can see in the gif:

![ui-error](https://user-images.githubusercontent.com/414445/181289240-9cd48191-5f2a-4cee-9c08-6f1c56d3a9d8.gif)

Checking the database, I see the following which seems to correspond to the timeframe in which the lock is in place:

<img width="407" alt="screenshot 2022-07-27 at 11 22 13 AM" src="https://user-images.githubusercontent.com/414445/181289854-53281fb9-da2d-40ee-a258-f08187b1430c.png">

```
show open tables where in_use>0;
mbentley_grafana	alert_configuration	2	0	
```

**What you expected to happen**:

Saves should be quick.

**How to reproduce it (as minimally and precisely as possible)**:
Setup Grafana with a MariaDB backend; add a test `Notification polices` or `Contact points`.

**Anything else we need to know?**:

**Environment**:
- Grafana version: `9.0.5`
- Data source type & version: `InfluxDB v2.2.0` - Alpine Linux (`influxdb:2.2-alpine` Docker image)
- OS Grafana is installed on: `grafana/grafana:9.0.5` Docker image
- User OS & Browser: macOS Monterey 12.5
- Grafana plugins: just the default plugins
- Others: MariaDB 10.6.8

**Comment by MarijnKoesen** [comment]
I have the same problem with sqlite.

In an attempt to fix it I migrated to mysql, but I got the same result with mysql. I'm also on 9.0.5.

Downgrading to 9.0.4 fixed it for me too.

**Comment by yuri-tceretian** [comment]
I think it was fixed in https://github.com/grafana/grafana/pull/53069. Can you please upgrade to 9.1.0?

**Comment by mbentley** [comment]
I can confirm that the issue isn't present in 9.1.x.  Thanks!
