### ISSUE TITLE
Grafana 9: Unexpected error while trying to explore metrics from Prometheus datasource - possible br encoding issue

### ISSUE THREAD

**Issue by tmyhu** [grafana/grafana#52915]
**What happened**: After updating Grafana from 8.4.7 to 9.0.4/9.0.5 it is not possible to explore metrics for our Prometheus datasources behind [trickster ](https://github.com/trickstercache/trickster) acting as reverse proxy anymore. When opening the dropdown an Unexpected error occurs. Looking at network requests in the developer tools we can see a JSON parsing error as the response does not contain JSON:

![tempsnip1](https://user-images.githubusercontent.com/86459458/181409980-bf9fb17c-3fc9-4e18-9017-c214ffc3bf26.png)

Reviewing the payload it appears to be brotli/br encoded and can be manually decoded into JSON with `brotli -d` 
Manually resending the request while removing br from the Accept-Encoding header does get a valid JSON reponse. 

**What you expected to happen**: To get a list of metrics from the dropdown

**How to reproduce it (as minimally and precisely as possible)**:
This only occurs when using trickster in-between Grafana and Prometheus, when reconfiguring the datasource to connect to Prometheus directly the issue disappears so trickster is required to reproduce the issue. Minimal configs:

Datasource:
```
 {
    "id": 1,
    "uid": "P2791037C5DE65137",
    "orgId": 1,
    "name": "DATASOURCENAME",
    "type": "prometheus",
    "typeName": "Prometheus",
    "typeLogoUrl": "public/app/plugins/datasource/prometheus/img/prometheus_logo.svg",
    "access": "proxy",
    "url": "https://TRICKSTERSERVERNAME:8483/BACKENDNAME",
    "user": "",
    "database": "",
    "basicAuth": false,
    "isDefault": false,
    "jsonData": {
      "httpHeaderName1": "Authorization",
      "manageAlerts": true,
      "tlsAuthWithCACert": true
    },
    "readOnly": true
  },
```
Trickster config:
```
frontend:
  tls_listen_port: 8483

backends:
  BACKENDNAME:
    provider: prometheus
    origin_url: https://PROMETHEUSSERVERNAME:4500
    prometheus:
      labels:
        cluster: {{ cluster.cluster_domain }}
    tls:
      # TLS certificate used by trickster when serving requests
      full_chain_cert_path: '/path/to/crt'
      private_key_path: '/path/to/key'
```

**Anything else we need to know?**:
There seems to be a difference in how these requests go through the Grafana API. in v8 the request URI was `/api/datasources/**proxy**/1/api/v1/label/__name__/values?start=1658887082&end=1658890682`
In 9, the request URI is:
`/api/datasources/1/resources/api/v1/label/__name__/values?start=1658885293&end=1658888893`

The issue can also be reproduced with curl, sending the same requests with the same headers e.g.:
`curl 'https://GRAFANASERVERNAME:3000/api/datasources/1/resources/api/v1/label/__name__/values?start=1658885293&end=1658888893' -H 'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' --compressed -H 'Referer: https://GRAFANASERVERNAME:3000/explore?orgId=1&left=%7B%22datasource%22:%22DATASOURCENAME%22,%22queries%22:%5B%7B%22refId%22:%22A%22%7D%5D,%22range%22:%7B%22from%22:%22now-1h%22,%22to%22:%22now%22%7D%7D' -H 'x-grafana-org-id: 1' -H 'Connection: keep-alive' -H 'Cookie: grafana_session=SESSIONCOOKIE'`

Using curl to test, I was able to get correct JSON responses via the old /proxy/:datasourceid API on Grafana 9 as well as using the new /proxy/uid/:uid API.

Could there be a decoding issue in the non-proxy API?

**Environment**:
- Grafana version: 9.0.5
- Data source type & version: Prometheus
- OS Grafana is installed on: Using official grafana/grafana-enterprise image in podman on RHEL 8
- User OS & Browser: Windows Server 2016, Firefox 84
- Grafana plugins: None
- Others: Trickster v2.0.0

**Comment by theSuess** [comment]
We have encountered a similar issue when trying to use a prometheus datasource behind an oauth proxy (as is the case in openshift)

I've identified the cause to be in the construction of the `Authorization` header. It gets prefixed with `Basic <username>:` even though basic auth is disabled in the datasource settings.

The issue occurs since version 9.0.0

**Comment by itsmylife** [comment]
@tmyhu Could you please change your HTTP Method in the datasource settings page as `POST`. This should fix it. Grafana fallback to GET if `POST` doesn't work.

<img width="349" alt="image" src="https://user-images.githubusercontent.com/820946/185977061-facd7b74-1e6f-451a-8491-2d341b597f55.png">

**Comment by tmyhu** [comment]
@itsmylife , thanks for your reply. The datasource was already configured for `POST`, same as in your screenshot. But I took the opportunity to retest this in the latest version 9.1.1 and the issue appears to be gone now.

**Comment by itsmylife** [comment]
> @itsmylife , thanks for your reply. The datasource was already configured for `POST`, same as in your screenshot. But I took the opportunity to retest this in the latest version 9.1.1 and the issue appears to be gone now.

🎉 🎉 
Thanks for your input. I am happy that the issue resolved. I suspected SSL Certificates (expired/missing/etc) too. If it will come up again (I hope it won't) feel free to reach out.
