### ISSUE TITLE
barchart: when labels are rotated 90 degrees the top of the y-axis is truncated

### ISSUE THREAD

**Issue by mellieA** [grafana/grafana#52914]
**What happened**:

Change the label orientation to 90 degrees, the top of the y-axis is truncated. The length of the label doesn't matter also tried to adjust the maximum label length. 

**How to reproduce it (as minimally and precisely as possible)**:

Create a bar chart
Use the TestDB Datasource and select CSV Content
Add this CSV content: 

```
label,value
"kdjfdkjal",3000
"fjakjd",45000
"kdjfdkjal",3
```
Before rotation:

![Screen Shot 2022-07-27 at 6 15 34 PM](https://user-images.githubusercontent.com/18175287/181394087-3cfabc35-3e30-4992-a9ec-8df1cc9f4d21.png)

after rotation: 
![Screen Shot 2022-07-27 at 6 15 20 PM](https://user-images.githubusercontent.com/18175287/181394059-60928113-d491-45d7-8a66-7025f08d3873.png)

**Anything else we need to know?**:

**Environment**:
- Grafana version: 9.05
- Data source type & version: TestDataDB
- OS Grafana is installed on: Grafana Cloud
- User OS & Browser: Chrome
- Grafana plugins:
- Others:

**Comment by leeoniya** [comment]
noticed a similar issue regressed by https://github.com/grafana/grafana/pull/38881 the cause of that one is setting a top padding to 0:

https://github.com/grafana/grafana/pull/38881/files#diff-8632994a0bf4abf52a585fcbf2ac88cab6347d46258364784bcaf7e17993f389R23

very likely a similar cause here.

**Comment by leeoniya** [comment]
yep: https://github.com/grafana/grafana/pull/40299/files#diff-1493359d011abdb000a97b10b46cca944e8578b4aad63449a8513536ac782355R272

cc @oscarkilhed
