### ISSUE TITLE
Docker image of 3.0.4 doesn't have plugin load in run.sh

### ISSUE THREAD

**Issue by burdandrei** [grafana/grafana#5291]
[X] Bug report
Hi,
I had to downgrade to 3.3 cause docker image of 3.0.4 doesn't have plugin load in run.sh

**Comment by torkelo** [comment]
plugin load?

you mean the env variable GF_INSTALL_PLUGINS ? 

please open issues related to the docker image here:
https://github.com/grafana/grafana-docker

**Comment by burdandrei** [comment]
ah, you right, opening it there.
Yes in run.sh of 3.0.4 there  is no GF_INSTALL_PLUGINS checker
