### ISSUE TITLE
[minor] Docs: Clarify alerting configuration

### ISSUE THREAD

**Issue by svet-b** [grafana/grafana#52921]
The current version of the docs for `[alerting]` -> `enabled` ([link](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#enabled-4)) states:
> Set to false to [enable Grafana alerting](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#unified_alerting) and to disable legacy alerting engine. to disable Grafana alerting, set to true.

The last part seems nonsensical. For example, if I genuinely want _all_ alerting to be disabled, presumably I should set both `GF_UNIFIED_ALERTING_ENABLED=false` _and_ `GF_ALERTING_ENABLED=false`. But the documentation seems to indicate the opposite.

Also the first sentence implies that setting `GF_ALERTING_ENABLED=false` automatically enables unified alerting, but presumably that's not a direct consequence (i.e. the `GF_UNIFIED_ALERTING_ENABLED` option controls that).

This seems further complicated by the switch in default alerting engine (to unified alerting) that v9 brought in. Given the potential for confusion, it would be good for the docs to be more explicit with respect to what the different scenarios entail (e.g. incorporating some of the info from https://grafana.com/docs/grafana/next/alerting/migrating-alerts/opt-in/ and https://grafana.com/docs/grafana/latest/alerting/migrating-alerts/opt-out/ - assuming those are up-to-date).

**Comment by brendamuir** [comment]
@grobinson-grafana can you help me with this one?

**Comment by grobinson-grafana** [comment]
Hi @svet-b! :wave: Thanks for opening an issue! I'm not sure I can find the sentence you quoted in the link page https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#enabled-4. 

> Set to false to [enable Grafana alerting](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#unified_alerting) and to disable legacy alerting engine. to disable Grafana alerting, set to true.

Instead I see the following sentence:

> Set to true to [enable legacy dashboard alerting](https://grafana.com/docs/grafana/latest/setup-grafana/configure-grafana/#unified_alerting). The default value is false.

Could you help me find the sentence you're seeing and @brendamuir and I can fix it! 😄

**Comment by svet-b** [comment]
Thanks guys! @grobinson-grafana I guess the docs were updated since I opened the issue (two and a bit months ago), and the current version makes sense to me - so feel free to close this. Thanks for your work on this!
