### ISSUE TITLE
 Hidden series appear in legend after other series have been selected

### ISSUE THREAD

**Issue by mrthehud** [grafana/grafana#52925]
This sounds almost identical to https://github.com/grafana/grafana/issues/33261, but occurs with the `timeseries` panel, instead of the older `graph` panel.

This issue has begun somewhat recently (sorry, can't give versions) - within the last 3 months or so (we upgrade weekly where available).

A series used to be hidden by toggling the enable / disable query button. This seems to not work, and instead, we've been using series overrides to hide series that are used by others (metric math) in the Viz, Legend and Tooltip:
![Screenshot from 2022-07-28 09-51-53](https://user-images.githubusercontent.com/140144/181464338-a17291ec-dce4-45de-8706-2af78eb4426f.png)

However, when a (remaining) series is activated in the legend (e.g. to show only it, or it ans one other) then a new series override is created that hides "all except" the selected series, but only hides them in the Viz. This overrides the hiding in the Legend (but strangely, not the tooltip), causing the hidden series to be shown temporarily in the Legend, until the field selection is cancelled, at which point the new override is removed.
![Screenshot from 2022-07-28 09-52-33](https://user-images.githubusercontent.com/140144/181464885-6af4ecef-7b9c-40a7-8895-f51dacb5ee82.png)

I obviously expect only the visible series to be hidden by the temporary override, and not for any series to be made visible because it's not mentioned in the temporary override, but this isn't happening, and may sometimes be a desired configuration. 

Perhaps a different override to the "Series -> Hide in area" should be used for the temporary override - such as a "Series -> Hide viz only"?

![Screenshot from 2022-07-28 09-17-08](https://user-images.githubusercontent.com/140144/181464930-b9fa226f-2652-478e-89e6-0768214afc6a.png)

Grafana version: v9.0.4 (c256012971)
Data source: CloudWatch 5.0.0
User OS / Browser: Ubuntu / Chrome

**Comment by JustinTArthur** [comment]
I'm able to reproduce this bug on Grafana v9.0.5 (1b595e434a) as well. The temporary override created by a legend selection takes precedence over the overrides that hide other legend items.

**Comment by mdvictor** [comment]
Hey @mrthehud. Thank you for reporting this. Work is in progress to fix the issue!
